### ISSUE TITLE
Terraform v0.7.10 Has Internal Error When Updating UserData on Single `aws_instance`

### ISSUE THREAD

**Issue by druidsbane** [hashicorp/terraform#10001]
Hi,

On changing the userdata `terraform apply` no longer works and has an internal error.

### Terraform Version
Terraform v0.7.10

### Affected Resource(s)
aws_instance

### Terraform Configuration Files
```
resource "aws_instance" "squid-nat" {
    ami = "${data.aws_ami.xenial.id}"
    instance_type = "t2.micro"
    
    key_name = "${aws_key_pair.some_key.id}"
    
    # subnets to launch in
    subnet_id = "${aws_subnet.public_subnet_a.id}"
    vpc_security_group_ids = ["${aws_security_group.squid_nat_sg.id}"]
    associate_public_ip_address = true
        
    monitoring = false
    
    source_dest_check = false # needed to be a NAT instance
    
    user_data = "${file("userdata/squid_nat_startup_userdata.sh")}"
    
    tags {
        Name = "squid_nat"
    }
}
```

### Expected Behavior
Instance should be recreated using new user data.  This instance is a NAT gateway and it is being used in a route table so that may be related.

### Actual Behavior
The error below.  The only way to get around is to rename that instance and update all references to that new id then the apply works.

```
Error applying plan:

1 error(s) occurred:

* aws_instance.squid-nat: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.10
    Resource ID: aws_instance.squid-nat
    Mismatch reason: diff: Destroy; old: false, new: true
```

### Steps to Reproduce
`terraform apply`

### Important Factoids
Instance is a NAT gateway.

**Comment by mitchellh** [comment]
Hey there! I used 0.7.10 (same as you) and ran this configuration and I wasn't able to get this error. Hrm, can you think of any other differences?

**Comment by druidsbane** [comment]
Hi @mitchellh, that is a good point.  

I think this might be related to the fact that this machine is used in an `aws_route` as a _NAT instance_.  I noticed that every `terraform apply` it updates the route tables regardless of whether or not the _NAT instance_ has changed.

Also, for my non-NAT instances that aren't attached to any routes the update of userdata just causes the instance to be deleted and recreated rather than the internal error mentioned above confirming your findings.

**Comment by mitchellh** [comment]
@druidsbane Given I tried your exact config and couldn't reproduce this, do you have any steps that would allow me to reproduce this? If I can't reproduce this, we can't fix it. :(

**Comment by mitchellh** [comment]
Found this! Repro of #10125 (PR attached)
