### ISSUE TITLE
Experimental feature failure!

### ISSUE THREAD

**Issue by vysakhqb** [hashicorp/terraform#10013]
2 error(s) occurred:

* plan operation: Unknown 'ValidateResource' shadow value for "aws_lambda_function": &errors.errorString{s:"shadow closed"}
* plan operation: Diff "module.maraton-snapshot.aws_lambda_function.marathon_snapshots" had unequal states (real, then shadow):

&terraform.ResourceConfig{ComputedKeys:[]string{"role", "vpc_config.0.security_group_ids", "vpc_config.subnet_ids", "vpc_config.subnet_ids"}, Raw:map[string]interface {}{"role":"${aws_iam_role.iam_for_lambda.arn}", "handler":"index.handler", "timeout":"10", "source_code_hash":"${base64sha256(file(\"${path.module}/lambda_function_payload.zip\"))}", "filename":"${path.module}/lambda_function_payload.zip", "runtime":"nodejs4.3", "vpc_config":[]map[string]interface {}{map[string]interface {}{"subnet_ids":[]interface {}{"${var.private_primary_subnet_id}", "${var.private_secondary_subnet_id}"}, "security_group_ids":[]interface {}{"${var.private_security_group_id}"}}}, "function_name":"${var.pre_tag}-marathon-snapshots"}, Config:map[string]interface {}{"runtime":"nodejs4.3", "vpc_config":[]map[string]interface {}{map[string]interface {}{}}, "function_name":"terraform-210-marathon-snapshots", "handler":"index.handler", "timeout":"10", "source_code_hash":"47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=", "filename":"/home/centos/IaC-platform/.terraform/modules/65266bcdbceec944dc64cb76937021ad/lambda_function_payload.zip"}, raw:(*config.RawConfig)(0xc4212f9e60)}

&terraform.ResourceConfig{ComputedKeys:[]string{"role", "vpc_config.0.subnet_ids", "vpc_config.0.subnet_ids", "vpc_config.security_group_ids"}, Raw:map[string]interface {}{"vpc_config":[]map[string]interface {}{map[string]interface {}{"security_group_ids":[]interface {}{"${var.private_security_group_id}"}, "subnet_ids":[]interface {}{"${var.private_primary_subnet_id}", "${var.private_secondary_subnet_id}"}}}, "source_code_hash":"${base64sha256(file(\"${path.module}/lambda_function_payload.zip\"))}", "function_name":"${var.pre_tag}-marathon-snapshots", "role":"${aws_iam_role.iam_for_lambda.arn}", "handler":"index.handler", "timeout":"10", "filename":"${path.module}/lambda_function_payload.zip", "runtime":"nodejs4.3"}, Config:map[string]interface {}{"handler":"index.handler", "timeout":"10", "filename":"/home/centos/IaC-platform/.terraform/modules/65266bcdbceec944dc64cb76937021ad/lambda_function_payload.zip", "runtime":"nodejs4.3", "vpc_config":[]map[string]interface {}{map[string]interface {}{}}, "source_code_hash":"47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=", "function_name":"terraform-210-marathon-snapshots"}, raw:(*config.RawConfig)(0xc421157ec0)} 

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.

**Comment by stack72** [comment]
Hi @vysakhqb 

Please can you tell me what version of Terraform this is happening for you in?

Paul

**Comment by mitchellh** [comment]
This turns out to be the same as #10075. Going to close this one.
