### ISSUE TITLE
Experimental feature failure!

### ISSUE THREAD

**Issue by serialdoom** [hashicorp/terraform#10023]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.7.9

### Terraform Configuration Files
https://drive.google.com/open?id=0B6JMz9WnoXZAUHFDQ2dWQ25wc1k

### Debug Output
https://gist.github.com/serialdoom/07a85bd73bbecf0477bbd2420004523d

**Comment by mitchellh** [comment]
Hi! Thank you. This was fixed in 0.7.10 which we just released yesterday! If that turns out to not be the case, please reopen a new issue. I'm fairly confident though since this exact error message ("unknown variable") was a major fix in 0.7.10. Thanks!

**Comment by serialdoom** [comment]
tested 0.7.10 and its all good (i updated my tf a couple of days ago and didnt think that there would be a new version out )

**Comment by mitchellh** [comment]
Thanks @serialdoom
