### ISSUE TITLE
data source template_file not working properly for openstack resources

### ISSUE THREAD

**Issue by rhoml** [hashicorp/terraform#10035]
Hi There, I've been trying to spawn instances on openstack using cloud-init and terraform data sources. 

My use case is: we want to spawn instances and give them some puppet configuration so they can connect to the puppet master and apply the catalog.

### Terraform Version
terraform 0.7.7-0.7.9

### Affected Resource(s)
data template_file
data template_cloudinit_config
openstack_compute_instance_v2

### Terraform Configuration Files
main.tf
```hcl
data "template_file" "cloudconfig" {
  template = "${file("${path.module}/user_data.tpl")}"

  vars {
    fqdn = "${openstack_compute_instance_v2.instance.name}.${var.region}.${var.domain}"
    puppet_master = "${var.puppet_master}"
  }
}

data "template_cloudinit_config" "config" {
  gzip          = false
  base64_encode = false

  part {
    filename     = "init.cfg"
    content_type = "text/cloud-config"
    content      = "${data.template_file.cloudconfig.rendered}"
  }
}

resource "openstack_compute_instance_v2" "instance" {
  region            = "${var.region}"
  count             = "${var.count}"
  name              = "${format("${var.instance_name}${var.zone_number}%03d", count.index+1)}"
  image_name        = "${var.image_name}"
  flavor_name       = "${var.flavor_name}"
  floating_ip       = "${var.floating_ip}"
  key_pair          = "${var.key_pair}"
  availability_zone = "zone${var.zone_number}"
  security_groups   = ["${var.security_groups}"]

  metadata {
    environment = "${var.metadata_environment}"
    region      = "${var.region}"
    role   = "${var.role}"
    terraform   = true
  }

  user_data = "${data.template_cloudinit_config.config.rendered}"
}
```

user_data.tpl

```hcl
#cloud-config

fqdn: ${fqdn}

apt_sources:
  - source: "deb [arch=amd64] http://repositories.domain.com/puppetlabs/ trusty main dependencies"
    filename: puppetlabs.list

apt_update: true
apt_upgrade: false
manage_etc_hosts: false

runcmd:
  - apt-get install -y puppet=3.7.4-1puppetlabs1 puppet-common=3.7.4-1puppetlabs1 --force-yes

puppet:
 conf:
   agent:
     server: "${puppet_master}"
```
### Debug Output
This code actually generates a cycle for the fqdn variable and when I remove the fqdn variable it just never interpolate the puppet_master variable.

### Expected Behavior
Variables should be substituted on the user_data 

Am I getting the data resource usage wrong? I also tried by 

```
user_data = <<-USERDATA
  puppetmaster: ${var.puppet_master}
USERDATA 
```
within the instance resource and the variable never gets interpolated but no error shows up.

**Comment by mitchellh** [comment]
I see a cycle here:

- FQDN (`openstack_compute_instance_v2.instance`)
- `template_cloudinit_config.config.content`
- `openstack_compute_instance_v2.instance.content`

This isn't solvable in any automated way. The cycle has to be broken!

**Comment by rhoml** [comment]
So i guess there is no good way of actually building dynamic user_data?

**Comment by mitchellh** [comment]
What you're doing is fine as long as the dynamic user data doesn't contain a reference to the instance that must be created first. The cycle here just isn't solvable since you're asking to create a template from a value that isn't available to Terraform until after the instance is created (in which case its too late to supply the user data).

Users create dynamic user data all the time exactly how you're doing. You did it right. It is just the cycle that is the issue.

**Comment by rhoml** [comment]
Also what about the case where the obly variable defined in template_file is puppet_master and it just doesn't get replaced and no error from terraform? Is that the expected?

**Comment by mitchellh** [comment]
@rhoml I missed that. I just reread your issue and see that. 

I tried with the following config and it properly interpolated. This happens at a core Terraform level regardless of resource type so the openstack resource type should have no affect. This works though:

```
variable "foo" { default = "bar" }

data "template_file" "tpl" {
    template = <<-TPL
    Hello ${var.foo}
    TPL
}

output "result" { value = "${data.template_file.tpl.rendered}" }
```

Perhaps thats a good example? If you have tips to get yours to error as you said I'll try again.
