### ISSUE TITLE
provider/pagerduty: missing key for weekly layer restriction

### ISSUE THREAD

**Issue by blalor** [hashicorp/terraform#10033]
### Terraform Version

Terraform v0.7.10

### Affected Resource(s)

- pagerduty_schedule

### Terraform Configuration Files
```hcl
resource "pagerduty_schedule" "PlatformTest" {
    name = "Platform Test"
    time_zone = "America/New_York"
    description = "testing some terraformy stuff"
    
    ## Monday 9am to Wednesday 5pm
    layer {
        name = "M9a-W5p"
        start = "2016-11-13T23:00:00Z"
        rotation_virtual_start = "2016-11-09T23:00:00Z"

        rotation_turn_length_seconds = "${ 7 * 24 * 3600 }" ## 7 days

        restriction {
            type = "weekly_restriction"
            start_time_of_day = "09:00:00"
            start_day_of_week = 1
            duration_seconds = "${ 56 * 3600 }" ## 56 hours
        }
        
        users = [ "PDYDMY2" ]
    }
}
```

### Debug Output

- [terraform-without-start_day_of_week.txt](https://github.com/hashicorp/terraform/files/584753/terraform-without-start_day_of_week.txt)
- [terraform-with-start_day_of_week.txt](https://github.com/hashicorp/terraform/files/584754/terraform-with-start_day_of_week.txt)

### Expected Behavior

Should have been able to create schedule layer with a `weekly_restriction` restriction that specifies the starting day of the week.

### Actual Behavior

When not including the `start_day_of_week` attribute, `terraform apply` gets an error from the PagerDuty API because that attribute is required.  When specifying the attribute in the Terraform config, `terraform apply` fails because the attribute is unknown to the provider.

**Comment by heimweh** [comment]
Hi @blalor, thank you so much for this bug report. I'm currently looking into this.
This seems to be tracing back to the client library we're using which doesn't yet support the attribute `start_day_of_week`. I have a pending PR in the client library waiting and as soon that one's been merged I'll look into fixing the resource. 

Really sorry about this and I'm hoping to get this resolved quickly.

**Comment by blalor** [comment]
Thank you @heimweh!
