### ISSUE TITLE
winrm import incompatibility with packer

### ISSUE THREAD

**Issue by njt99** [hashicorp/terraform#10038]
Hi there,

I'm using both terraform and packer with atlas, and I'm 99.9% of the way to getting a monorepo which can build both projects with a shared set of dependencies (using a bazel workspace).

The issue I'm having is with the winrm import. In terraform and its vendored dependencies, the library is published imported using the historical "github.com/masterzen/winrm/winrm" location (e.g., [here](https://github.com/hashicorp/terraform/blob/351c6bed79abbb40e461d3f7d49fe4cf20bced41/vendor/github.com/packer-community/winrmcp/winrmcp/endpoint.go#L10)) while packer and its vendored dependencies use the current "github.com/masterzen/winrm" import (e.g., [here](https://github.com/mitchellh/packer/blob/02029503870181b139dee74faa4e270b6e32f5e1/communicator/winrm/communicator.go#L10))

I can work around this by maintaining a fork, but I'd prefer to send a PR.

**Comment by mitchellh** [comment]
Feel free to submit a PR for this and we'll be happy to fix it up. We vendor dependencies so as long as everything maps up, we're happy to point to the right place. Thanks!
