### ISSUE TITLE
Use AWS_DEFAULT_PROFILE for S3 remote config

### ISSUE THREAD

**Issue by jsonmaur** [hashicorp/terraform#10039]
When using Terraform's S3 remote config, it should pick up the `AWS_DEFAULT_PROFILE` environment variable to use a specific profile. Currently it only accepts `-backend-config="profile=..."`. According to http://docs.aws.amazon.com/cli/latest/topic/config-vars.html, this is now a valid config variable to configure the AWS CLI. Seeing that you currently check for `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY `, and `AWS_DEFAULT_REGION`, I'd assume you'd want to check for this one as well :)

I'm initializing remote state in a BASH script, and it would really help to have this. Currently I have to do this to conditionally set a profile:

```bash
if [[ ! -z $AWS_DEFAULT_PROFILE ]]; then
  PROFILE_FLAG=(-backend-config="profile=$AWS_DEFAULT_PROFILE")
fi

terraform remote config \
  -backend=S3 \
  -backend-config="bucket=$BUCKET" \
  -backend-config="key=state/$ENVIRONMENT.tfstate" \
  "${PROFILE_FLAG[@]}"
```

**Comment by pll** [comment]
This is on all resources, not just S3.  I was setting AWS_DEFAULT_PROFILE and exporting that before running terraform. Boto3 would obey this setting and do certain things in one account, but terraform for some reason was reverting the the [default] account listed in my credentials file despite setting AWS_DEFAULT_PROFILE to something else.
