### ISSUE TITLE
How to set instance_initiated_shutdown_behavior via a launch config?

### ISSUE THREAD

**Issue by ctindel** [hashicorp/terraform#10040]
I'm running into what I think must be some sort of timing issue.  I have 20 ASGs that I'm spinning up and down frequently.  Those instances themselves run a shutdown command at various intervals to force the ASG to spin them back up.  

force_delete = false for all the ASGs.

I'm getting into a weird state where some of the running instances are stuck in the stopped process instead of being terminated, I think because they halted themselves at the same time as I was running terraform destroy, and whatever terraform does is preventing the ASG from spinning up a new instance.  So terraform destroy just sits there forever, since the instance never terminates and it can't remove the ASG or any of the other properties.

I could tell the instance to manually set its instance initiated shutdown behavior to terminate with the AWS cli at boot time but it seems like there should be a way to make this happen without that hack.

I'm using terraform 0.7.8.  I just now downloaded 0.7.10 so i'll try that and see if that makes a difference but I'm wondering, is there a way to specify instance_initiated_shutdown_behavior in the launch configuration?

**Comment by stack72** [comment]
Hi @ctindel 

Thanks for opening the issue here - unfortunately, the AWS API doesn't support setting `instance_initiated_shutdown_behavior` in LaunchConfigs. I cannot find anything in the SDK or the documentation about this I am afraid

Sorry!

Paul

**Comment by ctindel** [comment]
Heh, I have no hope in their feature request process.  Apparently this request has been open since 2011:

https://forums.aws.amazon.com/message.jspa?messageID=648057

In case anybody stumbles onto this later here are some examples for how to do it via the aws cli:

http://stackoverflow.com/questions/10541363/self-terminating-aws-ec2-instance

**Comment by nytins** [comment]
Another workaround to achieve this behavior is to run a local provisioner which runs the aws cli command to set the instance_initiated_shutdown_behavior attribute.

**Comment by zirpu** [comment]
Note that if you shutdown an instance in an ASG group it will fail health check and be terminated.

**Comment by skstussy** [comment]
This is possible since  Nov 29, 2017 using EC2 launch templates. 

https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-launch-templates-for-amazon-ec2-instances/

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#create-launch-template

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#launch-templates-as
