### ISSUE TITLE
provider/aws: tags not being applied to resources

### ISSUE THREAD

**Issue by mazzy89** [hashicorp/terraform#10047]
### Terraform Version
0.7.10

### Affected Resource(s)
- aws_subnet
- aws_route_table

### Terraform Configuration Files
```hcl

resource "aws_subnet" "k8s_public_subnet" {
  count = "${var.public_subnets}"
  
  availability_zone       = "${var.availability_zones[idx]}"
  vpc_id                  = "${aws_vpc.k8s_vpc.id}"
  cidr_block              = "${cidrsubnet(var.k8s_vpc_cidr, length(var.availability_zones) + var.public_subnets, length(var.availability_zones) + count.index)}"
  map_public_ip_on_launch = true

  tags {
    Name = "k8s-public-subnet-${element(split("-", var.availability_zones[idx]), 2)}"
  }
  
  depends_on = ["aws_subnet.k8s_private_subnet"]
}

resource "aws_subnet" "k8s_private_subnet" {
  count = "${length(var.availability_zones)}"

  availability_zone = "${var.availability_zones[idx]}"
  vpc_id            = "${aws_vpc.k8s_vpc.id}"
  cidr_block        = "${cidrsubnet(var.k8s_vpc_cidr, length(var.availability_zones) + var.public_subnets, count.index)}"

  tags {
    Name = "k8s-private-subnet-${element(split("-", var.availability_zones[idx]), 2)}"
  }
}

resource "aws_route_table" "k8s_route_table" {
  count = "${length(var.availability_zones)}"

  vpc_id = "${aws_vpc.k8s_vpc.id}"

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = "${aws_nat_gateway.k8s_nat_gw.id}"
  }

  tags {
    Name = "k8s-route-table-${element(split("-", var.availability_zones[idx]), 2)}"
  }
}
```

### Expected Behavior
The resources should have the proper tags

### Actual Behavior
The tags are blank

### Steps to Reproduce
1. `terraform plan`
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/mazzy89/kubernetes/issues/1

**Comment by stack72** [comment]
Hi @mazzy89 

thanks for opening the issue here - just to confirm, are you saying that the tags are not being added to the 3 resources above or the VPC that they are created in?

Paul

**Comment by mazzy89** [comment]
@stack72 yes exactly just blank tag

**Comment by mazzy89** [comment]
@stack72 I've also tried to use `template_file` since in this case it seems much more appropriate but even in this case it doesn't work

**Comment by stack72** [comment]
got it - thanks for the clarification - i am going to adjust the title to be as follows:

provider/aws: tags not being applied to resources

This sound ok?

P.

**Comment by mazzy89** [comment]
yes it sounds ok. Thank you 👍

**Comment by mazzy89** [comment]
ok I found the solution:

interpolating the string in this way it solves the problem:
```hcl
"${element(split("-", element(var.availability_zones, count.index)), 2)}"
```

**Comment by mazzy89** [comment]
I found out that using the index with square brackets is very dangerous so I recommend to avoid the notation `list[idx]` in complex scenario. `element()` is much better
