### ISSUE TITLE
Crash When Invalid Domain Name Specified

### ISSUE THREAD

**Issue by waelsv** [hashicorp/terraform#10042]
### Terraform Version
v0.7.10

### Affected Resource(s)
Please list the resources as a list, for example:
- Route53 Zone (just NS records), including for completeness but no relation to this problem.

### Debug Output
https://gist.github.com/waelsv/6d92a8a7c3a2b1b4ad0cc8c0cf25d50c

### Panic Output
https://gist.github.com/waelsv/6d92a8a7c3a2b1b4ad0cc8c0cf25d50c

### Expected Behavior
An error should've been returned for a non-existent certificate/domain.

### Actual Behavior
It crashed!

### Steps to Reproduce
1. Specify an invalid domain in:
```
data "aws_acm_certificate" "mycert" {
        domain = "somedomain.com"
        statuses = ["ISSUED"]
}
```
2. Running `terraform plan` or `terraform apply`

### Important Factoids
Problem is not faced when a valid certificate/domain is specified.

### References
Not that I'm aware of.

**Comment by stack72** [comment]
Hi @waelsv 

Thanks for the report here - sorry that you have had the problem. I am fixing this right now already as this has been reported before

Paul
