### ISSUE TITLE
terraform fmt return constant error in the end: "Error running fmt: At 1:1: expected: IDENT | STRING got: LBRACE"

### ISSUE THREAD

**Issue by morkot** [hashicorp/terraform#10053]
### Terraform Version
v0.7.10

### Operating System
Windows

### Shell
Cygwin + ZSH
or
CMD

### Affected Resource(s)
All

### Debug Output
```
> terraform fmt                                                
Error running fmt: At 1:1: expected: IDENT | STRING got: LBRACE
```
However
```
> terraform validate
> echo $? 
0 
```

### Expected Behavior
No error

### Actual Behavior
Any run of ```terraform fmt``` returns error
```
Error running fmt: At 1:1: expected: IDENT | STRING got: LBRACE
```
And templates are formatted and everything works as expected except error message.

### Steps to Reproduce
1. `terraform fmt`

**Comment by mitchellh** [comment]
Can you please share the config this is happening with?

**Comment by mitchellh** [comment]
Closing due to lack of response, but please let us know if you can get us a repro. Thanks!

**Comment by morkot** [comment]
Hey @mitchellh , sorry for long silence on the issue. I found the reason: variables.tf with JSON syntax file in module. Should it be considered as bug?

**Comment by mitchellh** [comment]
Hm, that should work, can you show me the contents?

**Comment by morkot** [comment]
Here is the example content:
```json
{
  "variable": {
    "wildcard_dns_map": {
      "description": "",
      "default": {
        "domain1.example.com": "*.wildcard-domain1.",
        "domain2.example.com": "*.wildcard-domain2.",
        "domain3.example.com": "*.wildcard-domain3."
      }
    }
  }
}
```

**Comment by morkot** [comment]
@mitchellh , just a reminder....

**Comment by mitchellh** [comment]
@morkot Ah, you have JSON in a "tf" file. You should have the suffix of that be "tf.json"

I'll make this more robust in the future. We allow JSON in TF as a convenience but it its technically supposed to be in "tf.json" files.

**Comment by morkot** [comment]
@mitchellh , thanks. And yes, I found out this behavior experimentally, but should be explicitly mentioned in docs. It could be improved: if json, then do ```json pretty print``` (not sure, cause e.g. I use json variables only for programmatically generated values.
