### ISSUE TITLE
aws_iam_policy_document doesn't validate its fields, which leads to confusing error message

### ISSUE THREAD

**Issue by spenczar** [hashicorp/terraform#10057]
### Terraform Version

terraform -v
Terraform v0.7.9

### Affected Resource(s)
- aws_iam_policy

### Terraform Configuration Files
```hcl
data "aws_iam_policy_document" "es_write_access" {
  statement {
    sid = "1"
    effect = "allow"
    actions = [
      "es:ESHttp*",
    ]
    resources = [
      "*",
    ]
  }
}

```

### Debug Output
n/a

### Expected Behavior
I expected this to create an IAM policy

### Actual Behavior
I got a confusing error message, that "the policy failed legacy parsing":
```
* aws_iam_policy.es_write_access: Error creating IAM policy elasticsearch_writer: MalformedPolicyDocument: The policy failed legacy parsing
	status code: 400, request id: 49f6ca94-a827-11e6-bb3f-3b4c7a310c65
```

It turns out this is because I wrote `"allow"` as the `"effect"` in my policy document. This should actually be `"Allow"`. This was tricky to figure out! AWS sure isn't helping, but I think terraform could ease the pain.

### Steps to Reproduce
`terraform apply`

### Important Factoids
I'd like it if terraform told me that the only permitted values here are "Allow" and "Deny".

### References
Policy grammar:  http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html
> ```
> <effect_block> = "Effect" : ("Allow" | "Deny")  
> ```

**Comment by apparentlymart** [comment]
Hi @spenczar. Thanks for opening this issue!

We actually have a PR open for this one already in #10021, so I'm going to close this one just to consolidate the discussion over there.
