### ISSUE TITLE
Using "replace" interpolation on a variable string

### ISSUE THREAD

**Issue by jsonmaur** [hashicorp/terraform#10077]
### Terraform Version
0.7.10

### Affected Resource(s)
- core

### Terraform Configuration Files
```hcl
variable "zone_id" { default = "" }

resource "aws_route53_record" "main" {
  count = "${replace(replace(var.zone_id, "/^\\w.*/", 1), "/^[^\\w].*/", 0)}"
  zone_id = "${var.zone_id}"
  ttl = 300
  name = "db"
  type = "CNAME"
  records = ["${aws_db_instance.main.address}"]
}
```
and `var.zone_id` is coming from a module with this:
```hcl
resource "aws_route53_zone" "main" {
  name = "${var.name}"
  vpc_id = "${var.vpc_id}"
}

output "id" {
  value = "${aws_route53_zone.main.id}"
}
```

### Debug Output
```
Errors:
  * strconv.ParseInt: parsing "${replace(replace(var.zone_id, \"/^\\w.*/\", 1), \"/^[^\\w].*/\", 0)}": invalid syntax
```

### Expected Behavior
Should return either `0` or `1` depending on if `var.zone_id` is not empty.

### Important Factoids
This works great with an actual string in place of `var.zone_id`, but not with variables that are strings. Doesn't seem to be interpolated correctly.

**Comment by jsonmaur** [comment]
Update: seems to be a problem with all strings passed as variables. Is this a bug, or am I just missing something?

**Comment by mitchellh** [comment]
Unless I'm missing something, this is one of the older bugs that exists in Terraform. The result of this is that the `count` value is "computed" (because `aws_route53_zone.main.id` itself is computed). I actually just merged a PR onto master that makes this error a little more informative.

But, unfortunately, Terraform doesn't support this yet. See #3888

**Comment by jsonmaur** [comment]
Gotcha. Yeah it works if `var.zone_id` is a string itself, but errors if it gets its value through another variable. Thanks for the response :)

Are there any workarounds for this?

**Comment by mitchellh** [comment]
Unfortunately not. This is a difficult problem but we are slowly making progress towards fixing it. It's still some time away. This should fix itself with multiple applies, though.

**Comment by jsonmaur** [comment]
Cool 👍
