### ISSUE TITLE
Documentation Update: missing outputs of aws_iam_role resource

### ISSUE THREAD

**Issue by kjhosein** [hashicorp/terraform#10079]
Hi team TF,

I was able to get the following additional outputs from the _aws_iam_role_ resource (not shown in [docs](https://www.terraform.io/docs/providers/aws/r/iam_role.html)):

- path
- name

e.g. here's what `terraform show` gives me on a test _aws_iam_role_ resource:
```
aws_iam_role.test_role.role:
  id = kjh_test_app_name_kjh_test_app_id
  arn = arn:aws:iam::123456789123:role/kjh_test_app_name_kjh_test_app_id
  assume_role_policy = 
     {json policy}
  name = kjh_test_app_name_kjh_test_app_id
  path = /
  unique_id = AROAJUSUI3V5UPBW6D57G
```

And if I include some outputs for `aws_iam_role.test_role.name` and `aws_iam_role.test_role.path`, I get valid outputs.

Running some tests, it doesn't look like _create_date_ is also outputted. 

Unfortunately, Golang looks like Greek to me, and I didn't have the cycles to figure out what the code actually spits back.

Please close/delete if I have no idea what I'm talking about! Thanks!

-- Khalid

**Comment by stack72** [comment]
Hi @kjhosein 

Sorry that you had to open the issue on this - i think we need to make a change to our documentation to make it more clear. Just a FYI, *any* parameters that can be passed to a resource are also valid output parameters. The `Attributes Reference` of the documentation are *extra* attributes that are outputs as they are sent back to us from AWS

Hope this helps

Paul

**Comment by kjhosein** [comment]
Hi Paul,

Thanks for the info about params also being outputs - that's very valuable. Maybe I missed that in the documentation somewhere... And/or maybe that's a blurb that is prepended to the start of each `Attributes` section? Useful for those folks that dive into the TF deep-end without reading too much intro material. I know that's a lot of work, so I'm not advocating strongly for that. 

Creation dates would be great, but very low priority relative to many other requests (IMHO). Now if _date()_ was a built-in function, that would also be a good substitute, but that's a diff request!

Thanks!

-- Khalid

**Comment by stack72** [comment]
Hi @kjhosein 

Understood - we will make this more clear for sure :) Just a FYi, @Ninir has added your create_date :) it will be part of the Terraform 0.7.11 release

Thanks for helping us out

Paul
