### ISSUE TITLE
Feature Change: aws_ebs_volume: Modify kms_key_id argument to kms_key_arn

### ISSUE THREAD

**Issue by kjhosein** [hashicorp/terraform#10070]
According to the [documentation](https://www.terraform.io/docs/providers/aws/r/ebs_volume.html#kms_key_id), a **KMS key ARN** is required when encrypting an EBS volume, which is correct. However, the resource argument is called _kms_key_id_ which is confusing. Even more confusing is that passing a KMS Key ID to it _does not_ throw an error, but instead seeing it as a different value updates the resource.

Suggest changing the argument name to _**kms_key_arn**_.

### Terraform Version
0.7.10

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ebs_volume
- (possibly others)

### Terraform Configuration Files
```hcl
resource "aws_ebs_volume" "ebs_gp2_vol" { 
  encrypted = true
  kms_key_id = "ea0e8cbb-b968-4b2a-a534-ce66754a105b"
}
```

### Panic Output
None.

### Steps to Reproduce
Assuming that only a KMS Key ID is specified for the kms_key_id argument, then running `terraform apply` repeatedly will keep re-creating the resource.

### References
Similar in nature to, but not sure if that means this is a TF core issue:
- GH-9626

**Comment by stack72** [comment]
Hi @kjhosein 

Thanks for opening the issue here - we *try* to following the same conventions as AWS do in their documentation. The AWS cli [documentation](http://docs.aws.amazon.com/cli/latest/reference/ec2/create-volume.html) suggests the following:

```
--kms-key-id (string)

The full ARN of the AWS Key Management Service (AWS KMS) customer master key (CMK) to use when creating the encrypted volume. This parameter is only required if you want to use a non-default CMK; if this parameter is not specified, the default CMK for EBS is used. The ARN contains the arn:aws:kms namespace, followed by the region of the CMK, the AWS account ID of the CMK owner, the key namespace, and then the CMK ID. For example, arn:aws:kms:us-east-1 :012345678910 :key/abcd1234-a123-456a-a12b-a123b4cd56ef . If a KmsKeyId is specified, the Encrypted flag must also be set.
```

Do you think a better explanation in our documentation would be a better addition?

Thanks

Paul

**Comment by kjhosein** [comment]
Thanks for the quick reply Paul. Hmm, my feeling is that AWS is the confusing one! Don't quite get why they would name it kms-key-_id_. Oh well. 

Then yes, I completely agree with you - have a more fleshed out explanation in the TF docs, including the scenario where you enter the ID (instead of the ARN).

-- Khalid

**Comment by Ninir** [comment]
> Then yes, I completely agree with you - have a more fleshed out explanation in the TF docs, including the scenario where you enter the ID (instead of the ARN).

@kjhosein Are there scenarii where you should enter the ID rather than the ARN? I searched in the all documentation and found that it can be the full ARN, the Alias or the ID.

@stack72 Do you think it would a work that validates that the kms_key_id argument is a full ARN would be acceptable? It would force an ARN rather than aliases or IDs.

**Comment by kjhosein** [comment]
> Then yes, I completely agree with you - have a more fleshed out explanation in the TF docs, including the scenario where you enter the ID (instead of the ARN).

>> @kjhosein Are there scenarii where you should enter the ID rather than the ARN? I searched in the all documentation and found that it can be the full ARN, the Alias or the ID.

@ninir - good point. I guess I don't really care what I enter, but if they're essentially pointing to the same resource, then I don't want TF to recreate them. The initial point of my post was to just to have the documentation be clearer and point out pitfalls, but now it sounds like there are some potentially good improvements to be made in functionality as well.

+1 your idea of mapping/resolving the alias or ID to the ARN.

**Comment by coen-hyde** [comment]
I got bit by this. imo kms_key_id is confusing.

**Comment by jagregory** [comment]
Just got bit by this too with an `aws_db_instance`.

Supplying an ID does appear to work, but the state file reflects the ARN (I'm guessing AWS expands the ID to the full ARN when you create the resource) so on a subsequent run terraform considers the ID to have changed because ARN != ID.

**Comment by Ninir** [comment]
Hi guys,

Currently enforcing kms_key_* attributes to be ARN in #10356 
Currently running acceptance tests and updating the docs.

Hope it could fit into Terraform!
