### ISSUE TITLE
Experimental feature failure

### ISSUE THREAD

**Issue by dchancogne** [hashicorp/terraform#10071]
Terraform v0.7.9

2 error(s) occurred:

* apply operation: Unknown 'ValidateResource' shadow value: &errors.errorString{s:"shadow closed"}
* apply operation: Diff "module.provisioning.aws_instance.jenkins_instance" had unequal states (real, then shadow):

`&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{"availability_zone":"${var.instance_availability_zone}", "iam_instance_profile":"${var.instance_iam_instance_profile}", "key_name":"${var.instance_key_name}", "security_groups":[]interface {}{"DevOps Service", "${var.environment_security_group}", "${aws_security_group.jenkins_security_group.name}"}, "tags":[]map[string]interface {}{map[string]interface {}{"id":"${var.tag_id}", "Name":"${var.tag_name}", "function":"jenkins", "provider":"${var.tag_provider}", "service":"${var.tag_service}", "environment":"${var.tag_environment}"}}, "ami":"${var.instance_ami}", "instance_type":"${var.instance_type}"}, Config:map[string]interface {}{"tags":[]map[string]interface {}{map[string]interface {}{"environment":"builds", "id":"builds:devops:jenkins:provioning:0", "Name":"provisioning", "function":"jenkins", "provider":"terraform-aws", "service":"devops"}}, "ami":"ami-5b8ef94c", "instance_type":"m3.medium", "availability_zone":"us-east-1a", "iam_instance_profile":"DevOps", "key_name":"DevOps", "security_groups":[]interface {}{"DevOps Service", "DevOps Service - Builds", "DevOps - Provisioning"}}, raw:(*config.RawConfig)(0xc4207f2e40)}`

`&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{"security_groups":[]interface {}{"DevOps Service", "${var.environment_security_group}", "${aws_security_group.jenkins_security_group.name}"}, "tags":[]map[string]interface {}{map[string]interface {}{"environment":"${var.tag_environment}", "id":"${var.tag_id}", "Name":"${var.tag_name}", "function":"jenkins", "provider":"${var.tag_provider}", "service":"${var.tag_service}"}}, "ami":"${var.instance_ami}", "instance_type":"${var.instance_type}", "availability_zone":"${var.instance_availability_zone}", "iam_instance_profile":"${var.instance_iam_instance_profile}", "key_name":"${var.instance_key_name}"}, Config:map[string]interface {}{"availability_zone":"us-east-1a", "iam_instance_profile":"DevOps", "key_name":"DevOps", "security_groups":[]interface {}{"DevOps Service", "DevOps Service - Builds", "DevOps - Provisioning"}, "tags":[]map[string]interface {}{map[string]interface {}{"environment":"builds", "id":"builds:devops:jenkins:provioning:0", "Name":"provisioning", "function":"jenkins", "provider":"terraform-aws", "service":"devops"}}, "ami":"", "instance_type":"m3.medium"}, raw:(*config.RawConfig)(0xc420389b00)}`

**Comment by stack72** [comment]
Hi @dchancogne 

Sorry for the issue - we believe we have fixed this issue in 0.7.10 - please can you try upgrading. If this is still an issue, then please do let us know in this issue

Thanks

Paul
