### ISSUE TITLE
Website: The latest version of Terraform is still 0.7.9?

### ISSUE THREAD

**Issue by kamoljan** [hashicorp/terraform#10073]
The latest version in the [downloads page](https://github.com/hashicorp/terraform/blob/master/website/source/downloads.html.erb) is still v0.7.9.
I support it should be v0.7.10?

**Comment by jamtur01** [comment]
Looks like 0.7.10 to me.

![screenshot 2016-11-12 10 47 57](https://cloud.githubusercontent.com/assets/4365/20237286/89977e1e-a8c5-11e6-8bff-b5bec328ff63.jpg)

**Comment by stack72** [comment]
I think this must have been a caching issue @kamoljan 

Sorry for the hassle! It's definitely 0.7.10

Paul

**Comment by ashleydw** [comment]
had the same loading it, make sure to hard-refresh the page... seems like the caching expires tag needs to be lowered
