### ISSUE TITLE
cloudflare_record: Docs unclear on default value of "proxied"

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#10082]
https://www.terraform.io/docs/providers/cloudflare/r/record.html

Since `proxied` is a boolean (which the docs doesn't specify) and is Optional, it would be good to specify whether it defaults to false or true.

**Comment by tamsky** [comment]
https://github.com/hashicorp/terraform/blob/7d23570e2d9843ea79d6a59505221c8eb1a52fad/builtin/providers/cloudflare/resource_cloudflare_record.go#L59 says the default value is `false`
