### ISSUE TITLE
aws_vpn_connection_route - missing tags

### ISSUE THREAD

**Issue by ap-hyperbole** [hashicorp/terraform#10098]
Tags arguments not supported by terraform but can be added in AWS. 

`Errors:

  * aws_vpn_connection_route.test: : invalid or unknown key: tags
`

Running plan/apply removes manually added tags. 

```~ aws_vpn_connection.test
    tags.%:           "3" => "0"
    tags.Environment: "test" => ""
    tags.Managed:     "Terraform" => ""
    tags.Name:        "test-connection" => ""
```

**Comment by stack72** [comment]
Hi @ap-hyperbole 

Apologies for not getting back to you earlier on this. I have just started to look at this and cannot find a way to tag these routes in the AWS console. When i create an AWS VPN Connection, I can create tags (Also in terraform). But when i try and add a route, there is no option to do this

<img width="1040" alt="screen shot 2017-05-31 at 16 23 36" src="https://cloud.githubusercontent.com/assets/227823/26633876/85702430-461d-11e7-83ba-7d38917fe92b.png">

I am going to close this out as it's been a long time request and we can't really find a way of doing this. IF you can find a way, please post below and I will reopen and implement

Thanks

Paul
