### ISSUE TITLE
Security group rules get added then removed

### ISSUE THREAD

**Issue by tomstachura** [hashicorp/terraform#10100]
This snippet:
resource "aws_security_group_rule" "admin" {
  type = "ingress"
  from_port   = "${var.admin_ports[count.index]}"
  to_port     = "${var.admin_ports[count.index]}"
  protocol    = "tcp"
  security_group_id = "${aws_security_group.admin.id}"
  cidr_blocks = ["${var.admin_ips[count.index]}/32"]

  count       = "${length(var.admin_ips)}"
}

will create the 4 IPs and Ports configured when I run apply, however if I run apply again, they get removed. Then, if I run apply again, they get added, and so on.
I would of course expect that they get added and don't change.

**Comment by chadgrant** [comment]
Yeah, this has been happening for a long, long time.
