### ISSUE TITLE
Error on ECS Task Definition Update

### ISSUE THREAD

**Issue by brianknight10** [hashicorp/terraform#10111]
I am experiencing an explicit bug in Terraform when attempting to apply a Terraform state in Atlas. This deployment has worked for a while, and the only change made was a variable referring to the Docker container version used in the task definition. 

The Terraform apply fails with: `aws_ecs_task_definition.definition: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.`

### Terraform Version
0.7.10

### Affected Resource(s)
- aws_ecs_task_definition.definition

### Expected Behavior
Creation of an updated ECS task definition.

### Actual Behavior
See error message below.

### Error message
* aws_ecs_task_definition.definition: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.10
    Resource ID: aws_ecs_task_definition.definition
    Mismatch reason: diff: Destroy; old: false, new: true
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"network_mode":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"arn:aws:ecs:us-east-1:728517735075:task-definition/mobile-graphql:8", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "family":*terraform.ResourceAttrDiff{Old:"mobile-graphql", New:"mobile-graphql", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "revision":*terraform.ResourceAttrDiff{Old:"8", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "container_definitions":*terraform.ResourceAttrDiff{Old:"36e0e2ff8e14847001e6a44065ec9c82c06774fd", New:"38894e2e6e8e7e6f9a804905c9b24160cd6950f6", NewComputed:false, NewRemoved:false, NewExtra:"[\n  {\n    \"name\": \"mobile-graphql\",\n    \"image\": \"591536596437.dkr.ecr.us-east-1.amazonaws.com/mobile-graphql:1.0.332\",\n    \"memory\": 512,\n    \"portMappings\": [\n      {\n        \"containerPort\": 8080,\n        \"hostPort\": 0,\n        \"protocol\": \"tcp\"\n      }\n    ],\n    \"essential\": true,\n    \"command\": [\n      \"/sbin/my_init\"\n    ],\n    \"environment\": [\n      {\n        \"name\": \"CONSUL_HOST\",\n        \"value\": \"http://consul.snagdev.corp:8500\"\n      }\n    ],\n    \"ulimits\": [\n      {\n        \"name\": \"nofile\",\n        \"softLimit\": 1000000,\n        \"hardLimit\": 1000000\n      }\n    ]\n  }\n]\n", RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"family":*terraform.ResourceAttrDiff{Old:"mobile-graphql", New:"mobile-graphql", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "revision":*terraform.ResourceAttrDiff{Old:"8", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "container_definitions":*terraform.ResourceAttrDiff{Old:"36e0e2ff8e14847001e6a44065ec9c82c06774fd", New:"38894e2e6e8e7e6f9a804905c9b24160cd6950f6", NewComputed:false, NewRemoved:false, NewExtra:"[\n  {\n    \"name\": \"mobile-graphql\",\n    \"image\": \"591536596437.dkr.ecr.us-east-1.amazonaws.com/mobile-graphql:1.0.332\",\n    \"memory\": 512,\n    \"portMappings\": [\n      {\n        \"containerPort\": 8080,\n        \"hostPort\": 0,\n        \"protocol\": \"tcp\"\n      }\n    ],\n    \"essential\": true,\n    \"command\": [\n      \"/sbin/my_init\"\n    ],\n    \"environment\": [\n      {\n        \"name\": \"CONSUL_HOST\",\n        \"value\": \"http://consul.snagdev.corp:8500\"\n      }\n    ],\n    \"ulimits\": [\n      {\n        \"name\": \"nofile\",\n        \"softLimit\": 1000000,\n        \"hardLimit\": 1000000\n      }\n    ]\n  }\n]\n", RequiresNew:true, Sensitive:false, Type:0x0}, "network_mode":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"arn:aws:ecs:us-east-1:728517735075:task-definition/mobile-graphql:8", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:true, DestroyTainted:false}

**Comment by mitchellh** [comment]
Can you please post reproduction steps so we can reproduce this to fix it?

**Comment by brianknight10** [comment]
I apologize - despite the error message saying it was a Terraform bug, the issue actually lies with my configuration.
