### ISSUE TITLE
The documentation for AWS ElastiCache replication group is wrong/incomplete

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#10128]
Trying to create a AWS ElastiCache replication group and then a Route53 entry for that gives me an error.

The documentation say:

```
configuration_endpoint_address - (Redis only) The address of the replication group configuration endpoint when cluster mode is enabled.
```

but this don't seem to be the case.

### Terraform Version
0.7.8

### Affected Resource(s)
- aws_elasticache_replication_group

### Terraform Configuration Files
```hcl
resource "aws_elasticache_replication_group" "autoscaling_event_update_route53" {
  replication_group_id          = "asgevnt-route53"
  replication_group_description = "Autoscaling events updating Route53"

  engine_version                = "3.2.4"
  node_type                     = "cache.m3.medium"
# => The number of replicas per node group must be within 0 and 5.
  number_cache_clusters         = "${length(data.aws_availability_zones.available.names)}"
  port                          = 6379

  subnet_group_name             = "${aws_elasticache_subnet_group.main.name}"
  security_group_ids            = [
    "${aws_security_group.main-all.id}"
  ]
  parameter_group_name          = "default.redis3.2"

  automatic_failover_enabled    = "true"
  availability_zones            = ["${data.aws_availability_zones.available.names}"]
  apply_immediately             = "true"
  maintenance_window            = "sun:01:00-sun:02:00"

  tags {
    Name                        = "autoscaling_event_update_route53"
    environment                 = "core"
    service                     = "main"
  }
}

resource "aws_route53_record" "elasticache" {
 zone_id               = "${aws_route53_zone.main.zone_id}"
 name                  = "elasticache.${var.dns_zone}"
 type                  = "A"
 ttl                   = "300"
 records               = ["${aws_elasticache_replication_group.autoscaling_event_update_route53.configuration_endpoint_address}"]
}
```

Gives `* Resource 'aws_elasticache_replication_group.autoscaling_event_update_route53' does not have attribute 'configuration_endpoint_address' for variable 'aws_elasticache_replication_group.autoscaling_event_update_route53.configuration_endpoint_address'`

Looking at the ElastiCache Dashboard, it instead uses `Primary Endpoint` with `Configuration Endpoint: -`.

**Comment by xsellier** [comment]
Update the parameter group for `default.redis3.2.cluster.on`

**Comment by marcelboettcher** [comment]
From my current understanding redis cluster mode is not yet supported See feature request #9419

So you can use **primary_endpoint_address** - The address of the endpoint for the primary node in the replication group. If Redis, only present when cluster mode is disabled.

Just tried with number_cache_clusters = 2, which worked for me.
