### ISSUE TITLE
aws_launch_configuration.app_lc: diffs didn't match during apply

### ISSUE THREAD

**Issue by jmvbxx** [hashicorp/terraform#10125]
Unable to run `terraform apply` due to above error. Full text included in gist.

### Terraform Version
Terraform v0.7.10

### Affected Resource(s)
- aws_launch_configuration.app_lc

### Debug Output
https://gist.github.com/jmvbxx/fd297ec40b30a0336a157c51f5465439

### Panic Output
No `crash.log` produced

### Expected Behavior
`terraform apply` should have successfully completed

**Comment by catsby** [comment]
Thank you for the diff @jmvbxx – do you happen to have a minimal config that reproduces this error that you can share, without sharing any secrets?

**Comment by mitchellh** [comment]
Actually, staring at the error message long enough I think I've figured this out. Retagging and taking ownership.
