### ISSUE TITLE
ElastiCache cluster resource is 'broken'

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#10127]
I can't seem to create a ElastiCache cluster (and I'm not entirely sure why - hence just 'broken').

The parameters is mutually exclusive, but when I try to set them, they don't work. See example resource definition below (with inline comments on different values).

I'm pretty sure this is **documentation**, but I'm not sure..

### Terraform Version
0.7.8 (can't run 0.7.{9-10} because those are 'seriously' broken in other ways - several issues about that already exists).

### Affected Resource(s)
- aws_elasticache_cluster

### Terraform Configuration Files
```hcl
data "aws_availability_zones" "available" {}

resource "aws_elasticache_subnet_group" "main" {
  name                        = "elasticache-subnet-group"
  description                 = "Autoscaling events updating Route53"

  subnet_ids                  = [
    "${aws_subnet.main_0.id}",
    "${aws_subnet.main_1.id}",
    "${aws_subnet.main_2.id}"
  ]
}

# => Use of cache security groups is not permitted in this API version for your account.
#resource "aws_elasticache_security_group" "main" {
#  name                         = "elasticache-security-group"
#  security_group_names         = [
#    "${aws_security_group.main-all.name}"
#  ]
#}

resource "aws_elasticache_cluster" "autoscaling_event_update_route53" {
  cluster_id                    = "asgevnt-route53" # Maximum 16 chars - not documented anywhere in TF.

  engine                        = "redis"
  engine_version                = "3.2.4"
  port                          = 6379
  node_type                     = "cache.t2.micro" # Automatic failover is not supported for T1 and T2 cache node types - not documented anywhere in TF.
# => Must specify the same number of preferred availability zones as requested number of nodes.
#  num_cache_nodes               = "${length(data.aws_availability_zones.available.names)}"
# => Cannot create a Redis cluster with a NumCacheNodes parameter greater than 1.
#  num_cache_nodes               = 1 # According to docs, it can only be one. But when I  DO set it to "1", I get "Must specify the same number of preferred availability zones as requested number of nodes"..

  subnet_group_name             = "${aws_elasticache_subnet_group.main.name}"
# => Use of cache security groups is not permitted in this API version for your account.
#  security_group_ids            = ["${aws_elasticache_security_group.main.name}"]
  security_group_ids            = [
    "${aws_security_group.main-all.id}"
  ]
  parameter_group_name          = "default.redis3.2"

# => should be a list
  availability_zones            = "${data.aws_availability_zones.available.names}" # I thought this was SUPPOSED to be a list! ? But making it a list, gives me "Must specify the same number of preferred availability zones as requested number of nodes."

  apply_immediately             = "true"
  snapshot_arns                 = ["arn:aws:s3:::php-infrastructure-backups/autoscaling_event_update_route53.rdb"]
# => The requested configuration does not support snapshotting. Snapshot window parameter should not be specified.
#  snapshot_window               = "03:00-07:00"
# => The requested configuration does not support snapshotting. Snapshot retention limit parameter should not be specified.
#  snapshot_retention_limit      = "5"

  maintenance_window            = "sun:01:00-sun:02:00"

  tags {
    Name                        = "autoscaling_event_update_route53"
    environment                 = "core"
    service                     = "main"
  }
}
```

**Comment by catsby** [comment]
Hey @FransUrbo – Thanks for writing in! It looks like at the very least our docs need some cleanup or clarifications.

I've opened https://github.com/hashicorp/terraform/pull/10175 to start those, could you take a look? 

To address the specifics in your issue here:

    cluster_id                    = "asgevnt-route53" # Maximum 16 chars - not documented anywhere in TF.

We can add validation here and add this to the docs; I’ll put that in the PR shortly

    node_type                     = "cache.t2.micro" # Automatic failover is not supported for T1 and T2 cache node types - not documented anywhere in TF.

Documented now in the PR, however, this applies to `aws_elasticache_replication_group`. For reasons I don’t fully know, `aws_elasticache_cluster` only supports 
single node Redis “clusters”. 

    # => should be a list
      availability_zones            = "${data.aws_availability_zones.available.names}" # I thought this was     SUPPOSED to be a list! ? But making it a list, gives me "Must specify the same number of preferred     availability zones as requested number of nodes."

This parameter is documented as for use with memcache engine only. I believe the error you’re getting is related to trying to specify them when using Redis. Please use `availability_zone` for use with the Redis engine.

Hopefully that clears some things up. I’ll get to adding validation and docs for the `cluster_id`.

**Comment by mblakele** [comment]
> For reasons I don’t fully know, aws_elasticache_cluster only supports single node Redis “clusters”.

There's a PR that looks related: https://github.com/hashicorp/terraform/pull/9892

**Comment by shadycuz** [comment]
Just spent 2 hours trying to build a cluster, luckily I found this issue. Still not fixed here https://www.terraform.io/docs/providers/aws/r/elasticache_cluster.html

and the error msg is wrong. 

```
terraform plan
1 error(s) occurred:

* module.elasticache_tripeaks.aws_elasticache_cluster.cluster01: only lowercase alphanumeric characters and hyphens allowed in "cluster_id" ("var.cluster_name")
```
