### ISSUE TITLE
New resource waiting for already created resources

### ISSUE THREAD

**Issue by alexraju** [hashicorp/terraform#10120]
### Terraform Version
0.7.8, 0.7.9, 0.7.10

### Expected Behavior
On `terraform apply`, all resources should be created as given by plan.

### Actual Behavior
After creating some resources, new resources keep on waiting for already created resources.

### Steps to Reproduce
1. Clone from https://github.com/microservices-today/IaC-platform
2. Install following the README.

**Comment by stack72** [comment]
Hi @alexraju 

Thanks for opening the issue - please can you provide us some details as to what the issue you are getting is? IS it a specific resource that is causing you concern or ALL resources?

Please can you provide any debug information you get that can help us diagnose this

Thanks

Paul

**Comment by mitchellh** [comment]
Hi @alexraju, I'd like to add a bit more here: I started trying to reproduce this but the IaC-platform repro is HUGE and step-laden and I'm going to have to ask you for a much smaller reproduction to get this going.

**Comment by alexraju** [comment]
Thank you @mitchellh @stack72 . I will add the trace logs here for further investigation. 

In IaC-platform, we are running 8 modules and that is when we are getting the issue. Also, when executing the modules individually, everything is working fine.

**Comment by alexraju** [comment]
@mitchellh @stack72 The issue is resolved with TF v0.7.11. I believe the issue was related to template rendering. Closing this.
