### ISSUE TITLE
Support Linode

### ISSUE THREAD

**Issue by sobrinho** [hashicorp/terraform#1013]
Would be great to have support for Linode ;)

**Comment by ryanuber** [comment]
I think @pearkes started some work on this around the time of Terraform's public release.

**Comment by pearkes** [comment]
Yea, the TF work I did was before helper/schema, I also started https://github.com/pearkes/linode, again before helper/schema. There wasn't a suitable linode go library when I made that.

**Comment by sergeifilippov** [comment]
+1

**Comment by attila** [comment]
+1

**Comment by devinrsmith** [comment]
+1

**Comment by cmosetick** [comment]
+1

**Comment by realloc** [comment]
+1

**Comment by dwatrous** [comment]
+1

**Comment by miu-zsolt** [comment]
+1

**Comment by CpuID** [comment]
+1

**Comment by elct9620** [comment]
+1

**Comment by kudos** [comment]
Does this fit the bill? https://github.com/btobolaski/terraform-provider-linode

**Comment by alexsacr** [comment]
I've written a [complete set of bindings](https://github.com/alexsacr/linode) as a prereq for this.  I'm working on a provider at the moment.

**Comment by phinze** [comment]
@alexsacr, @btobolaski - we'd welcome a PR to add a linode provider to terraform core. Let me know if either of you are individually interested or would like to collaborate!

**Comment by btobolaski** [comment]
I'd be fine with that. What would you like to see before the pr? If we're using my plugin as a starting point, it could use some cleanup. Its definitely not the prettiest go that I've written. It also only covers servers currently, so we may want to extend it to support their DNS provider and the load balancers.

**Comment by phinze** [comment]
I'm happy to support however you'd like to approach it - we use PRs to iterate on work in progress so you're welcome to toss code up for review before it's totally done. Let's also see what @alexsacr thinks is the best way forward.

**Comment by alexsacr** [comment]
That seems reasonable.  I'd be happy to help out.

Working off a PR seems like the easiest way to collaborate on this.

**Comment by PaulCapestany** [comment]
+1

**Comment by patrickheeney** [comment]
+1

**Comment by sobrinho** [comment]
I didn't used yet but https://github.com/btobolaski/terraform-provider-linode seems the way to go

**Comment by bdwyertech** [comment]
+1

**Comment by bdwyertech** [comment]
:+1: I'm using https://github.com/btobolaski/terraform-provider-linode at the moment.  Seems to work pretty well.  Any reasoning behind why Linode isn't on the list of supported providers? Could probably use @btobolaski's project @phinze

**Comment by btobolaski** [comment]
I think I can speak to why it isn't an included provider, I just haven't gotten around to making a pull request for it yet.

**Comment by ejaz-ahmed** [comment]
This PR is still pending. Don't know why?

**Comment by babbarankit** [comment]
+1

**Comment by MauroJr** [comment]
+1

**Comment by lcacciagioni** [comment]
Any news on this guys?

**Comment by theoros** [comment]
Would love to see Linode officially supported!

**Comment by craig-m** [comment]
+1

**Comment by danielBingham** [comment]
Huge +1.  I've been using linode for years and really love the stability, consistency and support they offer.  It'd be nice to be able to bring my linodes into the modern world of automated provisioning and orchestration.

**Comment by jpasichnyk** [comment]
+1, we use linode as well, and would love to see this support.

**Comment by nielsonsantana** [comment]
+1

**Comment by mrjgreen** [comment]
+1

**Comment by 5tefan** [comment]
In light of today's announcement of $5 instances and other new features [1], I'd love to be able to transition my infrastructure to Linode and continue using Terraform!

[1] https://news.ycombinator.com/item?id=13645213 /

**Comment by negrusti** [comment]
+1

**Comment by koalalorenzo** [comment]
+1

**Comment by stack72** [comment]
Hi,

Thanks so much for the request for this new provider! 

While we'd love to see something like this, we don't currently have any plans to implement this ourselves. Until then, this issue is unlikely to see any movement and remain stale. We're trying to prune the stale issues (that aren't going to be addressed anytime soon) by closing them. Note that we only do this for enhancement requests and not bugs. 

We have future plans to enable community plugins to be available easily from the Terraform binary itself, allowing community members to "ship" plugins with Terraform much easier. There isn't a timeline for this yet but we hope that will allow much easier shipping of both new providers and updates to existing.

Thanks!

**Comment by lucaswxp** [comment]
+1

**Comment by displague** [comment]
Thanks to all the contributions and support from [HashiCorp](https://www.hashicorp.com/), [Linode](https://www.linode.com/), and the community, this project has become official!

Please **Star** ⭐️ , *Watch* 👁 , and Fork 🍴 :
- https://github.com/terraform-providers/terraform-provider-linode

It is now possible to use `terraform init` to automatically install the Linode Terraform provider without the need to build and install it by hand.

The new documentation is available at:
- https://www.terraform.io/docs/providers/linode/

An example of the provider's features is here:
- https://github.com/terraform-providers/terraform-provider-linode/tree/master/examples

Extra special thanks to @btobolaski whose repo was the base of all this!

--- 

Thanks for reporting this issue @sobrinho -- for getting the ball rolling!
