### ISSUE TITLE
DNSimple: Retrieve initial state

### ISSUE THREAD

**Issue by sobrinho** [hashicorp/terraform#1014]
Hi guys,

I didn't find anything about that on documentation and I'm not fluent in Go so I can't find it on codebase (may be there, although).

We have some domains which are currently managed on DNSimple web interface and we are going to replace it with terraform.

app_domain.tf:

``` tf
provider "dnsimple" {
    email = "${var.dnsimple_email}"
    token = "${var.dnsimple_token}"
}

resource "dnsimple_record" "www" {
    domain = "${var.app_domain}"
    name = "www"
    value = "xxx.xxx.xxx.xxx"
    type = "A"
    ttl = 3600
}
```

variables.tf:

``` tf
variable "dnsimple_token" {}
variable "dnsimple_email" {}

variable "app_domain" {
    default = "example.com"
}
```

terraform.tfvars:

``` tf
dnsimple_email = "user@example.com"
dnsimple_token = "secret"
```

terraform apply:

```
λ terraform apply
dnsimple_record.www: Creating...
  domain:    "" => "example.com"
  domain_id: "" => "<computed>"
  hostname:  "" => "<computed>"
  name:      "" => "www"
  priority:  "" => "<computed>"
  ttl:       "" => "3600"
  type:      "" => "A"
  value:     "" => "xxx.xxx.xxx.xxx"
dnsimple_record.www: Error: Failed to create record: Error creating record: API Error: 
Error applying plan:

1 error(s) occurred:

* Failed to create record: Error creating record: API Error: 

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

The message is not helpful but I discovered that if the record is already created on DNSimple, terraform apply will fail (deleting the record and running terraform apply works after that).

But that's not ideal because we have a lot a domains and a lot of records on each of them, I was expecting something like `terraform get-initial-state` to discover which domains are already configured, which aren't and so on.

Makes sense? There is already a way to do that?

Thanks.

**Comment by mitchellh** [comment]
There is another issue for this as well as numerous mailing list posts. Please check those. Thanks

**Comment by sobrinho** [comment]
@mitchellh do you know which one? I tried to find it unsuccessful, both on github issues and the mailing list.

thanks!

**Comment by mitchellh** [comment]
Not off the top of my head but this comes up a lot. Search for "recovery" "existing infrastructure" etc.
