### ISSUE TITLE
Panic: aws_ssh_key_file is not a map, this is a bug in Terraform.

### ISSUE THREAD

**Issue by hamadr** [hashicorp/terraform#10155]
Hi there,
I got a panic from Terraform when running `terraform plan`

### Terraform Version
`Terraform version: 0.7.10  fcf12bc46a34716652a5b9a4d7905361003293e7`

### Affected Resource(s)

- aws_instance

### Terraform Configuration Files
```
resource "aws_instance" "web" {
  ami                         = "${lookup(var.aws_coreos_ami, var.aws_region)}"
  instance_type               = "${lookup(var.aws_instance_type_web, var.environment)}"
  key_name                    = "${aws_key_pair.admin-key.key_name}"
  availability_zone           = "${aws_subnet.public.availability_zone}"
  vpc_security_group_ids      = ["${aws_security_group.base_sg.id}", "${aws_security_group.planbot_web_sg.id}"]
  subnet_id                   = "${aws_subnet.public.id}"
  associate_public_ip_address = true
  depends_on                  = ["aws_internet_gateway.gw"]
  private_ip                  = "10.0.0.101"
  user_data                   = "${data.template_file.web_cloud_config.rendered}"

  tags {
    Name        = "web_${var.environment}"
    Environment = "${var.environment}"
  }
}

resource "aws_key_pair" "admin-key" {
  key_name   = "admin-key-${var.environment}"
  public_key = "${file("lookup(var.aws_ssh_key_file, var.environment).pub")}"
}


variable "aws_ssh_key_file" {
    default = ""
}

variable "environment" {
  description = "The environment to run in"
}
```

### Debug Output
[https://gist.github.com/hamadr/ba10a2480805c4b28712c8a3e25c6edb](https://gist.github.com/hamadr/ba10a2480805c4b28712c8a3e25c6edb)

### Panic Output
[https://gist.github.com/hamadr/b20b7394d56a3c0656b8fdc6a357194c](https://gist.github.com/hamadr/b20b7394d56a3c0656b8fdc6a357194c
)
### Expected Behavior
Print the plan or an error.

### Actual Behavior
It panicked.

### Steps to Reproduce
1. `terraform plan -state=staging.tfstate -var environment=staging`

### Important Factoids
_

### References
_

**Comment by jbardin** [comment]
Hi @hamadr,

Thanks for filing this issue. I think there's something else in your config which is causing us to reach the panic. I've tried a few combinations of configs and variables, but the I get a correct validation error each time.

Just in case you're unsure about how to fix the issue, `aws_ssh_key_file` needs to be a map, so you can either default `type = "map"`, and/or `default = {}`. And I think the lookup interpolation line you want is:

    public_key = "${file("${lookup(var.aws_ssh_key_file, var.environment)}.pub")}"

**Comment by jbardin** [comment]
I have a simple reproduction now:

Just a single map variable in the config:
```
variable "test" {
	default = {}
}
```

and try to override that with string:

    terraform plan -var test=value

**Comment by hamadr** [comment]
Cool, I'm glad you could reproduce it.
