### ISSUE TITLE
Feature request - allow creating name composite metrics in the Librato provider

### ISSUE THREAD

**Issue by jonleighton** [hashicorp/terraform#10158]
It is now possible to [configure alerts in the Librato provider](https://www.terraform.io/docs/providers/librato/r/alert.html), which is very useful. However, sometimes we need to alert based on a composite metric. We must create the composite metric manually in the "metrics" section of the Librato admin and give it a name. We can then use the name to create the `librato_alert` resource.

It would be nice to be able to specify the composite metric in Terraform configuration as well, via some sort of `librato_metric` or `librato_composite_metric` resource. (The former naming might make sense if the resource would also allow setting default attributes on non-composite metrics, but that's a different request really.)

**Comment by wchrisjohnson** [comment]
I'm actively working on this and will be pushing a PR shortly.
