### ISSUE TITLE
Experimental diff feature failure on AWS resource creation on apply

### ISSUE THREAD

**Issue by ronniemu** [hashicorp/terraform#10156]
### Terraform Version
0.7.9

### Affected Resource(s)
Experimental feature affecting AWS resource creation on applying

### Debug Output
https://gist.github.com/ronniemu/f9dd1bb316bb483de662a5228fc7f691

### Steps to Reproduce
1. `terraform apply`

**Comment by mitchellh** [comment]
Thanks for reporting this. This should be fixed on newer versions (0.7.11) of Terraform, but I can't be 100% sure without seeing your configuration/state as well, which may contain sensitive information. Please try the latest version and if it doesn't fix it please report back, though we'll have to  try to get a reproduction together.
