### ISSUE TITLE
Feature Request: Specify IAM role(s) for RDS Cluster

### ISSUE THREAD

**Issue by thejaywhy** [hashicorp/terraform#10166]
AWS Aurora [recently](https://aws.amazon.com/about-aws/whats-new/2016/10/amazon-aurora-new-features-aws-lambda-integration-and-data-load-from-amazon-s3-to-aurora-tables/) added supports adding roles to the RDS cluster. This can be used to integrate Aurora with other AWS services, such as S3 or Lambda.

For details on this please see: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Aurora.Authorizing.AWSServices.html

It would be nice to have the ability to add IAM roles to an an `aws_rds_cluster` in much the same way as the `aws_redshift_cluster` resource's `iam_roles` attribute.

**Comment by thejaywhy** [comment]
I have a temporary work around that relies on the AWS CLI and `local-exec` provisioner:

```
resource "aws_rds_cluster" "default" {
  cluster_identifier = ${var.cluster_name}
  availability_zones = ["us-west-2a","us-west-2b","us-west-2c"]
  database_name      = "mydb"
  master_username    = "foo"
  master_password    = "barbut8chars"

  provisioner "local-exec" {
    command = <<EOF
aws rds add-role-to-db-cluster \
  --db-cluster-identifier ${var.cluster_name} \
  --role-arn ${var.cluster_role_arn}
EOF
  }
}
```

There is some assumptions I've made in this example, but it does appear to be working for my use case.

**Comment by rfink** [comment]
This would be great, as they've recently added the ability to load data directly from S3 into Aurora, but it requires an IAM role.

**Comment by vr001** [comment]
This feature is really important as many applications are trying to integrate various AWS resources. (like RDS with Lambda, S3 and etc.)

**Comment by rfink** [comment]
^ Not to mention, they just released a feature allowing Aurora to export directly to S3

**Comment by vr001** [comment]
@rfink good to know. Thanks.

I am really looking for ways to associate an IAM role with a DB cluster. (Unfortunately, I don't see the IAM roles on the consoles, though it is created successfully) So, the API method @thejaywhy  mentioned is the only solution?
