### ISSUE TITLE
aws_dynamo_db_table creates stream in disabled state, won't enable

### ISSUE THREAD

**Issue by jaygorrell** [hashicorp/terraform#10165]
### Terraform Version
0.7.10

### Affected Resource(s)
- aws_dynamodb_table

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "main" {
    name = "${var.name}"
    read_capacity = "${var.read_capacity}"
    write_capacity = "${var.write_capacity}"
    hash_key = "${var.hash_key}"
    attribute {
        name = "${var.hash_key}"
        type = "${var.hash_key_type}"
    }
    stream_enabled = true
    stream_view_type = "${var.stream_view_type}"
}
```

### Expected Behavior
Dynamodb table is created with stream enabled.

### Actual Behavior
Dynamodb table is created with stream disabled and plans show no expected changes.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Ninir** [comment]
Hi @jaygorrell ,

Just tried with this resource using TF 0.7.10:

```hcl
resource "aws_dynamodb_table" "main" {
    name = "test"
    read_capacity = "5"
    write_capacity = "5"
    hash_key = "UserId"
    attribute {
      name = "UserId"
      type = "S"
    }
    stream_enabled = true
    stream_view_type = "KEYS_ONLY"
}
```

The stream is created and here is what is exposed on the AWS console:
```
Stream enabled	Yes
View type	Keys only
```

As I had some issues with this, could you provide the vars you are using, and also the `terraform plan` output please? thank you 😄

**Comment by jaygorrell** [comment]
Hey @Ninir, thanks for the response. Here it is with variables filled in, though it's not much different!

```
resource "aws_dynamodb_table" "main" {
    name = "e2eresults"
    read_capacity = "5"
    write_capacity = "5"
    hash_key = "runId"
    attribute {
        name = "runId"
        type = "S"
    }
    stream_enabled = true
    stream_view_type = "NEW_AND_OLD_IMAGES"
}
```

After running this, the stream was created but in the disabled state. We only caught it right away because we also had a Lambda even source mapping being created:

```
resource "aws_lambda_event_source_mapping" "main" {
    event_source_arn = "${aws_dynamodb_table.main.stream_arn}"
    function_name = "${aws_lambda_function.main.arn}"
    starting_position = "LATEST"
    enabled = true
    batch_size = 100
}
```

Which resulted in:
```
* aws_lambda_event_source_mapping.main: Error creating Lambda event source mapping: InvalidParameterValueException: Stream arn:aws:dynamodb:us-west-2:<redacted>:table/e2eResults/stream/2016-11-15T14:57:33.231 is Disabled.  You cannot create a lambda mapping on a stream that is Disabled.
	status code: 400, request id: 01b54572-aba1-11e6-9ff5-bd86089f03f0
```

By manually enabling the DDB stream, TF (in Atlas) said no other changes were detected. What if you manually disable your stream - does TF pick up that it has changed? I think this stream was created with `"true"` instead of `true` and I changed it to the boolean format in case that was the problem. Perhaps something in that pattern caused this?

**Comment by Ninir** [comment]
Could you try adding:

```hcl
depends_on = ["aws_dynamodb_table.main"]
```
on the event_source_mapping resource and retry?

**Comment by jaygorrell** [comment]
I can try, but regardless of the lambda the DDB table was created with the stream disabled when set to both `"true"` and `true`. Also, depends on is just for ordering, right? Even after the table is created, further TF runs in Atlas say no changes needed.. I can flip the stream enabled/disabled either way and TF never sees any changes needed.

**Comment by Ninir** [comment]
@jaygorrell Just tried with this setup:

```hcl
resource "aws_dynamodb_table" "main" {
    name = "e2eresults"
    read_capacity = "5"
    write_capacity = "5"
    hash_key = "runId"
    attribute {
        name = "runId"
        type = "S"
    }
    stream_enabled = true
    stream_view_type = "NEW_AND_OLD_IMAGES"
}

resource "aws_lambda_event_source_mapping" "main" {
    event_source_arn = "${aws_dynamodb_table.main.stream_arn}"
    function_name = "${aws_lambda_function.main.arn}"
    starting_position = "LATEST"
    enabled = true
    batch_size = 100
}

resource "aws_lambda_function" "main" {
    filename = "test.zip"
    function_name = "lambda_function_name"
    role = "${aws_iam_role.iam_for_lambda.arn}"
    handler = "exports.test"
    source_code_hash = "${base64sha256(file("test.zip"))}"
}

resource "aws_iam_policy" "test" {
  name = "my_policy"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "*"
      ],
      "Resource": "*",
      "Effect": "Allow"
    }
  ]
}
POLICY
}

resource "aws_iam_role" "iam_for_lambda" {
    name = "iam_for_lambda"
    assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_policy_attachment" "test" {
  name       = "policy_atchmt"
  roles      = ["${aws_iam_role.iam_for_lambda.name}"]
  policy_arn = "${aws_iam_policy.test.arn}"
}
```

And the DynamoDB Stream & Lambda & Event Source mapping are created. The DynamoDB Stream is in an enabled state. Could you give the full configuration you're using?
