### ISSUE TITLE
aws_vpc_dhcp_options does not return ID

### ISSUE THREAD

**Issue by mcraig88** [hashicorp/terraform#10163]
### Terraform Version
Terraform v0.7.10

### Affected Resource(s)
aws_vpc_dhcp_options

### Terraform Configuration Files
```

source "aws_vpc_dhcp_options" "dns_resolver" {
	domain_name = "${var.dhcp_options_domain_name}"
	domain_name_servers = ["${var.dhcp_options_dns_servers}"]
	ntp_servers = ["${var.dhcp_options_dns_servers}"]
	#netbios_name_servers = ["127.0.0.1"]
	#netbios_node_type = 2
	
	tags{ 
		Name = "eCP Shared Services"
	}
}
output "aws_vpc_dhcp_options_ID" {
  value = "${aws_vpc_dhcp_options.dns_resolver.id}"
}

```
### Debug Output
module root: 2 error(s) occurred:

* Unknown root level key: source
* output 'aws_vpc_dhcp_options_ID': unknown resource 'aws_vpc_dhcp_options.dns_resolver' referenced in variable aws_vpc_dhcp_options.dns_resolver.id

### Expected Behavior
DHCP Options should be set, and return the ID associated with it. 

### Actual Behavior
Error occured, as above.

### Steps to Reproduce
1. `terraform plan`

### next steps
I was originally trying to consume the ID in the following:
`resource "aws_vpc_dhcp_options_association" "vpc_dhcp_options_association_ecp" {
    vpc_id = "${aws_vpc.main.id}"
    dhcp_options_id = "${aws_vpc_dhcp_options.dns_resolver.id}"
}`

**Comment by Ninir** [comment]
Hey @mcraig88 

Looking at your first error, i.e. `unknown root level key: source`, it seems that you are missing the `re` part in this. So from:

```hcl
source "aws_vpc_dhcp_options" "dns_resolver" {
```

Could you change to
```
resource "aws_vpc_dhcp_options" "dns_resolver" {
```
?

**Comment by mcraig88** [comment]
Oh! Thank you that fixed it. What a noob mistake. Bet you wish all bugs
were this easy to resolve.

Thanks again.

Mike

**Comment by stack72** [comment]
Thanks @Ninir for helping with this - @mcraig88 closing this out :)
