### ISSUE TITLE
Report from running experimental feature

### ISSUE THREAD

**Issue by opteemister** [hashicorp/terraform#10173]
Hi, just wanted to notice that I had an experimental warning, which you asked to report.

### Terraform Version
Terraform v0.7.10

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lambda_function

### Debug Output
2 error(s) occurred:

* plan operation: Unknown 'ValidateResource' shadow value for "aws_lambda_function": &errors.errorString{s:"shadow closed"}
* plan operation: Diff "aws_lambda_function.redshift_import_processing" had unequal states (real, then shadow):

&terraform.ResourceConfig{ComputedKeys:[]string{"role", "vpc_config.0.security_group_ids"}, Raw:map[string]interface {}{"vpc_config":[]map[string]interface {}{map[string]interface {}{"subnet_ids":[]interface {}{"${aws_subnet.private_az_a.id}", "${aws_subnet.private_az_b.id}"}, "security_group_ids":[]interface {}{"${aws_security_group.warehouse_sg.id}"}}}, "filename":"lambda/default.zip", "function_name":"warehouse-redshift-import-tf", "description":"Function for importing s3 files to the redshift", "role":"${aws_iam_role.warehouse_lambda_role.arn}", "handler":"index.handler", "runtime":"nodejs4.3", "timeout":30}, Config:map[string]interface {}{"handler":"index.handler", "runtime":"nodejs4.3", "timeout":30, "vpc_config":[]map[string]interface {}{map[string]interface {}{"subnet_ids":[]interface {}{"subnet-f8e9a19c", "subnet-d61262a0"}}}, "filename":"lambda/default.zip", "function_name":"warehouse-redshift-import-tf", "description":"Function for importing s3 files to the redshift"}, raw:(*config.RawConfig)(0xc4220a28a0)}

&terraform.ResourceConfig{ComputedKeys:[]string{"role", "vpc_config.security_group_ids"}, Raw:map[string]interface {}{"role":"${aws_iam_role.warehouse_lambda_role.arn}", "handler":"index.handler", "runtime":"nodejs4.3", "timeout":30, "vpc_config":[]map[string]interface {}{map[string]interface {}{"subnet_ids":[]interface {}{"${aws_subnet.private_az_a.id}", "${aws_subnet.private_az_b.id}"}, "security_group_ids":[]interface {}{"${aws_security_group.warehouse_sg.id}"}}}, "filename":"lambda/default.zip", "function_name":"warehouse-redshift-import-tf", "description":"Function for importing s3 files to the redshift"}, Config:map[string]interface {}{"runtime":"nodejs4.3", "timeout":30, "vpc_config":[]map[string]interface {}{map[string]interface {}{"subnet_ids":[]interface {}{"subnet-f8e9a19c", "subnet-d61262a0"}}}, "filename":"lambda/default.zip", "function_name":"warehouse-redshift-import-tf", "description":"Function for importing s3 files to the redshift", "handler":"index.handler"}, raw:(*config.RawConfig)(0xc421b587e0)}

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Steps to Reproduce
1. `terraform plan`

**Comment by mitchellh** [comment]
Thanks, this issue was just fixed in 0.7.11 ##10118
