### ISSUE TITLE
provider/rabbitmq: Arguments Map values are all strings

### ISSUE THREAD

**Issue by dmportella** [hashicorp/terraform#10186]
### Terraform Version
![Version](https://cloud.githubusercontent.com/assets/676817/20384722/beea35a8-acac-11e6-8cf0-30051c1e7c03.png)
> v0.7.11

### Affected Resource(s)
Please list the resources as a list, for example:
- RABBITMQ_BINDING
- RABBITMQ_EXCHANGE
- RABBITMQ_QUEUE
- RABBITMQ_POLICY (Possibly)

> If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

It is possible that its `core` because the Map Types `map[string]interface{}` see and return the values as strings when in the resource they have been expressed as integers or other types.

### Terraform Configuration Files
```
# Configure the Docker provider
provider "docker" {
	host = "unix:///var/run/docker.sock"
}

resource "docker_image" "rabbitmq" {
	name = "rabbitmq:3.6.5-management"
}

resource "docker_container" "rabbitmq" {
	image = "${docker_image.rabbitmq.latest}"
	name = "rabbitmq"

	env = ["RABBITMQ_DEFAULT_USER=guest", "RABBITMQ_DEFAULT_PASS=guest"]

        ports {
            internal = 15672
            external = 15672
            ip = "172.17.0.1"
        }

	restart = "always"
}

resource "null_resource" "wait" {
	depends_on = ["docker_container.rabbitmq"]

	provisioner "local-exec" {
		command = "echo 'Sleeping for 5...' && sleep 5"
	}
}


# Configure the RabbitMQ provider
provider "rabbitmq" {
	endpoint = "http://172.17.0.1:15672"
	username = "guest"
	password = "guest"
}

# Create a virtual host
resource "rabbitmq_vhost" "vhost_1" {
	depends_on = ["null_resource.wait"]

	name = "vhost_1"
}

resource "rabbitmq_permissions" "guest" {
	depends_on = ["null_resource.wait"]

	user = "guest"
	vhost = "${rabbitmq_vhost.vhost_1.name}"
	permissions {
		configure = ".*"
		write = ".*"
		read = ".*"
	}
}

resource "rabbitmq_exchange" "riverstyx" {
	depends_on = ["null_resource.wait"]
	
	name = "riverstyx"
	vhost = "${rabbitmq_permissions.guest.vhost}"
	settings {
		type = "fanout"
		durable = false
		auto_delete = true
	}
}

resource "rabbitmq_queue" "debug" {
	depends_on = ["null_resource.wait"]
	
	name = "debug-queue"
	vhost = "${rabbitmq_permissions.guest.vhost}"
	settings {
		durable = false
		auto_delete = true
		arguments = {
			x-message-ttl = 60000
		}
	}
}

resource "rabbitmq_binding" "binding" {
	depends_on = ["null_resource.wait"]
	
	source = "${rabbitmq_exchange.riverstyx.name}"
	vhost = "${rabbitmq_permissions.guest.vhost}"
	destination = "${rabbitmq_queue.debug.name}"
	destination_type = "queue"
	routing_key = "*"
	properties_key = "%23"
}
```

### Debug Output
Gist for Plan, Apply and debug apply: https://gist.github.com/dmportella/564505d677e5147f871771959fdd9c7a

### Panic Output
There was no panic log.

### Expected Behavior
map[string]interface{} values as they are marshalled into JSON should honor integer values and booleans.

For example:

```
# HTC
arguments = {
	x-message-ttl = 60000
}
```

Should out put a call to the Rabbitmq API with the body in json as:
```
#JSON
{
      "x-message-ttl": 60000
}
```
### Actual Behavior
What actually happened?
Json output and sent to rabbitmq API is all strings when rabbit api expects integers so it throws a `Bad Request 400`.

```
#JSON
{
      "x-message-ttl": "60000"
}
```

### Steps to Reproduce
Using the TF file pasted above you should be able to get the error by just doing an apply.
The terraform plan is completely self contained and it uses docker to create the rabbit instance.

1. `terraform apply`

### Important Factoids
Rabbitmq API arguments like x-message-ttl all are reserved keywords in rabbit that checks for the field type like if it is not integer it will fail the request with a `Bad Request 400`.

**Comment by dmportella** [comment]
@mitchellh Does map in the core understand that you specified `{ key = 100 }` and not `{ key = "100" }` first one is a integer the object properties are all getting marshaled all into strings.

**Comment by mitchellh** [comment]
@dmportella No, maps are single typed in the core. So even if we could understand ints it would mean that ALL value would have to be ints.

**Comment by dmportella** [comment]
hmmm oke, is there a work around like a type that allows you to enter any combination of values and honor  the type?

For the rabbit bug which is not a terraform problem just an oversight from implementation of the API for rabbit point of view we could just explicitly describe the properties rabbit expects to be other types and leave an arguments area where users can use the current functionality for adding custom headers to the rabbit object.

**Comment by jamescarr** [comment]
I see two options here that we could do to improve this:

* Allow optional type to be specified using a more verbose structure. So the default as it is now is a string but one could write the definition as 
```
definition {
      item {
         name = "shards-per-node"
         value = 2
         type = "number"
      }
    }
```
* provide a `raw_definition` or similar that is just a raw json string passed in and, as a result, passed through to rabbitmq's API. We do this now with AWS policy documents so why not?

With the typing issues I really feel like definitions should perhaps be json documents instead of `hcl` types.

**Comment by dmportella** [comment]
Sounds like a possibility

**Comment by dmportella** [comment]
Ops I meant to put it here

Do you mean like this: https://www.terraform.io/docs/providers/aws/r/iam_policy.html

```
resource "aws_iam_policy" "policy" {
  name        = "test_policy"
  path        = "/"
  description = "My test policy"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```

**Comment by jamescarr** [comment]
@dmportella bingo. Exactly what I'm thinking.

```hcl

raw_defintion = <<EOF
{
"shards-per-node": 2,
"routing-key": "foo.bar.baz"
}
EOF
