### ISSUE TITLE
Using interpolated values in required attributes of custom provider resource results in "required field is not set" error

### ISSUE THREAD

**Issue by balduncle** [hashicorp/terraform#10183]
### Terraform Version
Terraform v0.7.11

### Affected Resource(s)
- foo_bar (https://github.com/balduncle/terraform-provider-foo)
This is a simple custom provider plugin I created for easy consumption and reproduction of the problem I'm having.

### Terraform Configuration Files
```hcl
provider "foo" {
}

resource "foo_bar" "1" {
	name = "1"
}

resource "foo_bar" "2" {
	name = "${foo_bar.1.id}"
}
```

### Debug Output
https://gist.github.com/balduncle/e88ed16cedace3cf711f2004e13654c0

### Expected Behavior
The id of foo_bar.1 should be injected into the name of foo_bar.2.

### Actual Behavior
Any time interpolated values are included in the name attribute of a foo_bar resource it appears that some problem with the interpolation process leads to name being empty and the following error being displayed.
```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * foo_bar.2: "name": required field is not set
```

### Steps to Reproduce
1. Install the custom provider plugin
```
mkdir -p $GOPATH/src/github.com/balduncle
cd $GOPATH/src/github.com/balduncle
git clone https://github.com/balduncle/terraform-provider-foo
cd terraform-provider-foo
go get
go install
```
2. Configure terraform to use the plugin
```
cat <<EOF>> ~/.terraformrc
providers {
    foo = "$GOPATH/bin/terraform-provider-foo"
}
EOF
``` 
3. Save the terraform configuration listed above in main.tf.
4. Run `terraform plan`

### Important Factoids
I can see the id if I add it to an output block, so the problem seems to be unrelated to the value I'm trying to inject.  This is my first attempt at writing a terraform provider plugin, so hopefully this is just some obvious oversight on my part.

**Comment by mitchellh** [comment]
This looks like its caused by the resource name starting with a number. We should validate out of this but let me verify that causes it.

**Comment by balduncle** [comment]
No, I get this problem even with resources that have no numbers in their name.

```
provider "foo" {
}

resource "foo_bar" "a" {
	name = "1"
}

resource "foo_bar" "b" {
	name = "${foo_bar.a.id}"
}
```

```
» terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * foo_bar.b: "name": required field is not set
```

**Comment by balduncle** [comment]
I get the same error even if I add some extra characters, like this.

```
resource "foo_bar" "b" {
    name = "added characters ${foo_bar.a.id}"
}
```

So it seems like the presence of any interpolation there causes this to problem to surface.  I've used values from other non-custom resources as well and it always causes this problem, only when injecting them into required fields of my own custom resource.

**Comment by mitchellh** [comment]
This is weird, I'll look into this.

**Comment by mitchellh** [comment]
I tried your exact configuration and everything works for me (with 0.7.11 and master).

Master does have some weird behavior I'm looking into it but its not the error you brought up. There might be some weird stuff going on here due to that though (we're between a couple major releases which makes `master` a bit weird if you're running a plugin on 0.7.11)

**Comment by mitchellh** [comment]
Oh nevermind the weirdness was just my fault.

Yeah this is all working for me with Terraform on master.

**Comment by balduncle** [comment]
If it's not too much trouble, would you mind checking if you are able to reproduce this with 0.7.11?  Just to confirm there isn't something else weird about my environment...

**Comment by mitchellh** [comment]
I tested with 0.7.11 and it works fine AS LONG as your dependency is on the `0.7.11` tag (the `maint-0.7` branch should be safe as well). Note that this is sane to me since a LOT of our providers do exactly what you're doing here and TF would be pretty broken if this didn't work. :)

**Comment by balduncle** [comment]
Weird.  Would the version of Go I'm using matter?  Are my build/install steps messed up?  I can consistently reproduce this on my Mac running Sierra.

```
» go version
go version go1.7.3 darwin/amd64
```

**Comment by mitchellh** [comment]
Same version as you. The key thing is:

Terraform source version used to _build_ the provider must match the Terraform version _running_ the provider. So if you have 0.7.11 core running, you'll want to make sure your provider is built with `maint-0.7` branch. 

You reminded me that we should bump the plugin version so Terraform automatically notifies you of this.

**Comment by balduncle** [comment]
Ah, excellent.  That solved my problem.  Thank you!

**Comment by ragarcia26** [comment]
@mitchellh I'm not sure what you mean `your provider is built with maint-0.7 branch` aren't all the providers built into terraform now? I just ran into this issue unfortunately, but with my custom provider.

**Comment by mitchellh** [comment]
@ragarcia26 All core providers are unaffected, this only affects 3rd party providers unfortunately.

To fix it just go to `$GOPATH/src/github.com/hashicorp/terraform` and `git checkout maint-0.7`.

Once 0.8 is out officially though you can switch back to master. Sorry for the confusion, we're doing a beta alongside 0.7 stable releases.

**Comment by ragarcia26** [comment]
I was actually using govendor and it was pulling 0.8, forced it back to 0.7.11. But good to see 0.8 is coming in, I'm good to go now. Thank you :)
