### ISSUE TITLE
count doesn't iterate in subblocks under the resource

### ISSUE THREAD

**Issue by cblecker** [hashicorp/terraform#10182]
### Terraform Version
Terraform v0.7.11

### Affected Resource(s)
- Tested with `google_compute_backend_service`, but may affect others

### Terraform Configuration Files
```hcl
resource "google_compute_backend_service" "backend-service" {
  name        = "backend-service"
  port_name   = "port${var.svc_port}"
  protocol    = "HTTP"
  timeout_sec = 10

  backend {
    count = "${length(var.instance_groups)}"
    group = "https://www.googleapis.com/compute/v1/projects/${var.project_name}/zones/${lookup(var.instance_groups_regions, "${var.instance_groups[count.index]}")}/instanceGroups/${var.instance_groups[count.index]}"
  }

  health_checks = ["${google_compute_http_health_check.http-health-check.self_link}"]
}
```

### Expected Behavior
Terraform would have expanded and created multiple backend blocks inside the `google_compute_backend_service` resource.

### Actual Behavior
`  * google_compute_backend_service.backend-service: backend.0: invalid or unknown key: count`

### Important Factoids
This may not be intended functionality, but does have useful possibilities for resources with multiple of a subblock.

**Comment by hydroxide** [comment]
Chiming in because I have already encountered several cases where this would prove useful. 
* aws_instance - Conditionally declaring ebs_block_devices and ephemeral_block_devices depending on instance type
* aws_elb - Conditionally declare listeners based on environment (dev, stage, prod)

**Comment by davewalter** [comment]
We also encountered this when attempting to add a variable number of backends to a backend_service.

**Comment by zachgersh** [comment]
@cblecker - would love to actually implement this. Trying to figure out what level to implement this at and it would seem that it belongs in the `schema` package but I want to double check.

Other assumption, we would follow the same sort of API that count has on a resource. So, that you would get `backend.0..backend.n`.

**Comment by mitchellh** [comment]
Going to close this as a dup of #7034! Same idea.
