### ISSUE TITLE
Resource map-typed arguments various crashes

### ISSUE THREAD

**Issue by moio** [hashicorp/terraform#10187]
### Terraform Version
0.8.0 dev, current master (7293630f644dc8f2c1db41730f70a7e6762b3e60)

### Affected Resource(s)
Terraform core, any resource which has an argument of type map (eg. [heroku_app's config_vars](https://www.terraform.io/docs/providers/heroku/r/app.html#config_vars)).

### Terraform Configuration Files
```hcl
provider "heroku" {
    email = "dummy"
    api_key = "dummy"
}

variable "app_config" {
  type = "list"

  default = [
    {
      foo = "bar"
      baz = "bam"
    },
    {
      foo = "bar"
      baz = "bam"
    },
  ]
}
  
resource "heroku_app" "test" {
  name   = "test-app"
  region = "us"

  // Scenario 1
  // this works partially (number of resources is 1, should be 2, see #8867):
  #config_vars = ["${var.app_config}"]

  // this leads to terraform crash (expected type error):
  #config_vars = "${var.app_config}"

  // Scenario 2
  // this works:
  #config_vars = ["${map("foo", "bar")}"]

  // this leads to terraform crash (expected type error):
  #config_vars = "${list(map("foo", "bar"))}"
    
  // Scenario 3
  // this works (type error: should be a map):
  #config_vars = ["${map("foo", "bar")}"]
  #config_vars = ["lalala"]

  // this leads to misleading error (unknown type for string *ast.ListType):
  #config_vars = ["${map("foo", "bar")}"]
  #config_vars = "lalala"
}
```

### Expected Behavior
See comments in scenarios above.

### Actual Behavior
See comments in scenarios above.

### Steps to Reproduce
1. uncomment one or more lines according to comments above
1. `terraform plan`

### Important Factoids
 - I am not sure if this should be reported as 3 separate issues, or if cause is common. Please advise.
 - I have another similar bug I cannot presently reproduce with builtin providers, only with terraform-provider-libvirt. I am fairly sure it is a bug in core - should I open an issue for that too?

### References
- GH-9549: these issues emerged while testing resolution of this issue

**Comment by moio** [comment]
@jbardin great, thanks so far!

What about scenario 1, where plan is inconsistent on the number of vars? Even in latest terraform I get (emphasis mine):

> + heroku_app.test
>     all_config_vars.%: "<computed>"
>     config_vars.#:     "**2**"
>     config_vars.**0**.%:   "2"
>     config_vars.**0**.baz: "bam"
>     config_vars.**0**.foo: "bar"
>    git_url:           "<computed>"

Only 1 var is populated despite `config_vars.#` being 2. This obviously leads to failures during apply, too.

Is there a chance this could be fixed before 0.8, through #8867 or otherwise?

**Comment by jbardin** [comment]
@moio,

Let me see if I can get the first case working for 0.8. The underlying issue is rather deep, and is going to take a lot of work to solve in it's entirety, but we may be able to add another workaround here.

**Comment by jbardin** [comment]
These cases are now all working as expected. 

The string type error in scenario 3 is now:

    config_vars: should be a list


Thanks for the thorough bug report!

**Comment by moio** [comment]
Thanks for taking care of all of these corner cases @jbardin! I look forward to test them all in my rather complicated setup soon! :wink:
