### ISSUE TITLE
Computed values cannot be used in interpolation functions like length.

### ISSUE THREAD

**Issue by rupamroy** [hashicorp/terraform#10193]
### Terraform Version
v 0.7.9

### Affected Resource(s)
Please list the resources as a list, for example:
- interpolation functions

#### Issue
In my terraform project I have an alb module which is having the following output 
```
output "light_target_groups" {
  value = "${join(",", aws_alb_target_group.light.*.arn)}"
}
```

I call this module in my main.tf and then in another file alarm.tf i pass this output to another cloudwatch metric alarm module
```
# alarm.tf

module "ra_alb_public_light_targetgroup_alarms" {
  source = "./modules/alb_alarms"
  alb_targetgroup_arns = "${module.alb_public.light_target_groups}"
}
```

In the module i am trying to get the length of the targetgroups 
```
resource "aws_cloudwatch_metric_alarm" "alb_targetgroup_high_average_request_count" {
    count = "${length(split(",",var.alb_targetgroup_arns ))}"
    alarm_name = "xxx"
    comparison_operator = "GreaterThanOrEqualToThreshold"
    evaluation_periods = "${var.evaluation_periods_request_count}"
    metric_name = "RequestCount"
    namespace = "${var.namespace_alb}"
    period = "${var.period_high_request_count}"
    statistic = "Average"
    threshold = "${var.threshold_high_request_count}"
    dimensions {
        TargetGroup = "xxx"
    }
    alarm_description = "Monitors ALB metric for high request count"
}
```

I am getting an error like 
```
strconv.ParseInt: parsing "${length(split(\",\",var.alb_targetgroup_arns ))}": invalid syntax
```

I know the error is misleading and it is due to applying interpolation syntax on a computed value. But how do i fix it , or is there any workarround

**Comment by mitchellh** [comment]
This is fixed in the 0.8 beta series by showing a better error message.

This functionality isn't currently supported, the issue #3888 tracks making this work one day.
