### ISSUE TITLE
Add support for vmware

### ISSUE THREAD

**Issue by generalconsensus** [hashicorp/terraform#102]
Is there any interest in providing support for vmware?

**Comment by zarry** [comment]
+1

**Comment by mkuzmin** [comment]
I've started developing such plugin, here is the first version:
https://github.com/mkuzmin/terraform-vsphere
I doesn't do much so far, but VM creation (cloning) and deletion are supported.

Feedback, issues and pull requests are welcome!

**Comment by higebu** [comment]
@mkuzmin 
Cool!

**Comment by daniellockard** [comment]
I've started work on such a plugin as well... Here's my first version:
https://github.com/Banno/terraform-provider-vsphere

It supports instance creation from a template, static / DHCP IP Address, and other features of Guest Customizations in VMWare. It utilizes govmomi to talk to VSphere.

My current use case is: create a virtualbox vm with my (not yet released) packer-post-processer-vsphere.  From there, I use terraform to create a VM off of what packer has uploaded.  This uses a lot of defaults like default DC / Resource Pool and the default network that is marked in the vmware template. It also just plops the VM in the root of the VMFolder.

Maybe we should figure out how to merge the two of these, or get one included as an official terraform builtin?

Any thoughts @mitchellh @armon?

**Comment by bitwisekaizen** [comment]
I, too, have started work on this plugin.  My needs are a bit different since I'm creating testbeds consisting of multiple ESX hosts.  I've been trying to get some PRs into govmomi to support the changes, but I will post my fork and update this issue as soon as everything is working.  Would love to merge all three of our efforts into the terraform mainline so that there aren't three separate forks!

**Comment by daniellockard** [comment]
I also just open sourced my packer vsphere template creator which sort of goes hand-in-hand with my terraform provider: https://github.com/Banno/packer-post-processor-vsphere-ova

**Comment by tkak** [comment]
I have started developing this plugin, too. Now, it's in just company's private git repository. But, I'm thinking about releasing our "terraform-provider-vsphere" on Github, or making PR. I'd love to merge the all plugins for vsphere to one terraform provider. :)

**Comment by tylermauthe** [comment]
This thread is full of win. You all rock.

**Comment by tkak** [comment]
I published our terraform custom provider for VMware vSphere on GitHub.
https://github.com/rakutentech/terraform-provider-vsphere

It's tested for only our private VMware vSphere environment. Please try to use the provider. Feedbacks, Issues and pull request are welcome.

**Comment by mkuzmin** [comment]
Great. Now we have three incomplete plugins instead of a single working one.
Can we do something to stop competing with each other?

**Comment by tkak** [comment]
@mkuzmin Yes, we'd better develop a single project. I'd love to cooperate with you. Which plugin should we mainly develop? If you don't mind, I'd like to work my plugin continuously. But, I can try to send PR your plugin. Whichever is fine.

**Comment by shuichiro-makigaki** [comment]
+1

**Comment by tfhartmann** [comment]
I'd love to give one of these a try.. is there any consensus on a "prime" plugin at the moment?

**Comment by knuckolls** [comment]
I was part of the team that helped build one of them. We don't currently have active development in that plugin and I'm off on other responsibilities at this point. Here's my vote for the merge. Someone who cares enough and has the time should grab the code they need from one of the providers, licence willing, and PR it to terraform core. New users, try to use what's in master and port in the right code from the existing plugins. Place the right attribution in the right places as necessary.

Preserve the tests and chip away at the problem iteratively. If anyone is up for getting in there and start PRing stuff, I say go for it. Eventually, I hope to move over to whatever amalgamation of the existing codebases make it into master.

**Comment by daniellockard** [comment]
+1 to @knuckolls . I certainly would like to see one sane plugin in terraform core.

**Comment by andrewh** [comment]
+1

**Comment by mevansam** [comment]
To add to the mix of vsphere plugins in the wild, I too started working on one https://github.com/mevansam/terraform-provider-vsphere. I am taking a slightly different approach as my requirement is to be able to 'terraform' a VDC given a couple of ESX hosts and a vCenter server. So I have started by mapping the vSphere datacenter domain and host constructs to terraform - I borrowed from the plugins found in this thread to get me started as I am new to Go.. At some point we should definitely merge all the good work going on around creating a vSphere provider into a single fork of terraform which we can contribute back.

-Mevan

**Comment by wjimenez5271** [comment]
+1 for Vmware vsphere/vcloud support

**Comment by echohack** [comment]
+1 :dancer:

**Comment by bobbarebygg** [comment]
+1

**Comment by mazebuhu** [comment]
+1

**Comment by marcecaro** [comment]
+1

**Comment by dhoer** [comment]
+1

**Comment by alanplatt** [comment]
+1

**Comment by coxley** [comment]
:+1:

**Comment by fulloflilies** [comment]
+1

**Comment by rubbish** [comment]
Just a note that we're in the process of changing our infra to use https://github.com/rakutentech/terraform-provider-vsphere instead of the one we made: https://github.com/Banno/terraform-provider-vsphere. It mainly was done for the better device support, but the rakutentech provider has much better momentum behind it. We'll be deprecating our own soon.

**Comment by chrislovecnm** [comment]
Bunch of comments here.  Hashicorp peeps do we have a roadmapped direction here?

There are a bunch of directions that this could take.

Lowest api - vSphere
Next size - vRealize Automation (formerly vCloud Automation Center)
Another entry - vCloud Air.  vCloud 5.5 is kinda going away on the roadmap.  I will check with my VMware peeps on what the official pitch is.

I know that folks have worked on multiple providers, but what is the long term direction??  We have three different API entry points to do the same darn thing :)

@mitchellh any roadmap on your guys end?

**Comment by ringods** [comment]
@chrislovecnm I would definitely try to go as far as possible with the vSphere API. I know of a lot of people who are running a single vSphere (formerly ESXi) server at home (I'm one of them) and would very much like to use Terraform agains this setup.

**Comment by chrislovecnm** [comment]
@ringods I agree with that starting point.  vRealize is another product from VMware, and is not owned by all vSphere users.  vCloud Air is yet another entry point.  Looking to see if I can get an opinion from @mitchellh  or other Hashicorp peeps on roadmap direction.

**Comment by dhoer** [comment]
+1 for vSphere

**Comment by zrml** [comment]
+1 on this one.

vSphere: imperative if we want to be present in the Enterprise arena (where you, Hashicorp, can up-sale Atlas and pay back your wonderful investors).

I echo @chrislovecnm: 
@mitchellh we don't need it "yesterday", but roadmap is fundamental.

Thank you :-)

**Comment by josephholsten** [comment]
Seems that if we want an official vsphere provider, we probably need to pick one:

- https://github.com/rakutentech/terraform-provider-vsphere
- https://github.com/mkuzmin/terraform-vsphere
- https://github.com/mevansam/terraform-provider-vsphere
- https://github.com/Banno/terraform-provider-vsphere (deprecated in favor of rakutentech)

@mevansam, @mkuzmin, @tkak: Would any of you be interested in putting together a patch pulling your provider into the main source tree?

**Comment by chrislovecnm** [comment]
@tkak added a pull, and we are bringing it in!!!!! To let everyone know meetings will soon be under way to start to look at a roadmap.

We (mantl.io) guys are setting a lab with vSphere 6. This is going to rock!!

I really need a roll call of all of the companies that are really interested in this. I can pass it on to a couple of the C levels that are spending budget on this push.

**Comment by zrml** [comment]
@chrislovecnm all Enterprise playing companies :)
Public cloud is nice but hybrid is here to stay as stats shows.

**Comment by chrislovecnm** [comment]
@zrml I completely agree, I was looking for some company names that are using terraform and looking for this support. No worries.

**Comment by zrml** [comment]
@chrislovecnm we are not yet... so, sorry.

**Comment by dhoer** [comment]
Pearson https://www.pearson.com/ is very interested in this...

**Comment by dotnetdude** [comment]
+1

**Comment by apparentlymart** [comment]
A vSphere provider was contributed in #3419 and is now merged, so I think this is done aside from some docs outstanding in #3483.

I'm going to close this but please let me know if there's something in this ticket that *isn't* represented by that merge, and we can either reopen it or make a fresh ticket.
