### ISSUE TITLE
SoftLayer provider is grossly outdated. Behind by about 22 resources and tons of fixes.

### ISSUE THREAD

**Issue by renier** [hashicorp/terraform#10207]
I'm one of the members of the team that got the SoftLayer provider into the Terraform tree.

After [some](https://github.com/hashicorp/terraform/pull/7049) [attempts](https://github.com/hashicorp/terraform/pull/9024) to continue updating the provider and months of waiting, we decided to create an [out of the tree external provider](https://github.com/softlayer/terraform-provider-softlayer/) to make it easy for users to install binaries of an updated provider.

Currently the internal SoftLayer provider only has 2 resources: SSH Key and Virtual Guest. Enough to do simple things. On the external provider, [terraform-provider-softlayer](https://github.com/softlayer/terraform-provider-softlayer/), we are already up to 24 resources.

So the difference between the internal and external providers is pretty large by now. The external one even uses a different SoftLayer client under the covers. This is starting to confuse users who find the internal provider first and struggle through [issues](https://github.com/hashicorp/terraform/issues/9015) [that](https://github.com/hashicorp/terraform/issues/8326) [have](https://github.com/hashicorp/terraform/issues/8734) already been fixed in the external provider.

So it's clear that we need to get the internal provider updated. I would like to ask, after some failed attempts as referenced above, what should our strategy be here? Appreciate your advice.

**Comment by TheKevJames** [comment]
Relatedly, I've had #9668 open for -- wow, nearly a month now. It is still pending comments/reviews/etc from a terraform maintainer.

My impression is that softlayer integration is a low priority for the terraform team -- would it make more sense to completely remove the internal provider to try to reduce confusion, eg. force users to user the external provider?

**Comment by renier** [comment]
@TheKevJames I recommend you head over to [terraform-provider-softlayer](https://github.com/softlayer/terraform-provider-softlayer/) which uses the official softlayer-go. Covers all the issues you highlighted in your PR.

>My impression is that softlayer integration is a low priority for the terraform team -- would it make more sense to completely remove the internal provider to try to reduce confusion, eg. force users to user the external provider?

Yes, at this point all (update to the latest version) or nothing (remove it from the tree) is what makes sense to me. That is what I argued for in #9024.

**Comment by ckelner** [comment]
FWIW IBM is working on picking this back up.  We are working on a strategy with HashiCorp to deprecate this provider and implement a new on under the IBM Bluemix flag (as IBM has re-branded SoftLayer to Bluemix now).  The plan will be to move the internal provider efforts over from the work done by Renier and get it officially accepted upstream.  We're working out a partnership with Hashi to get help accelerate this time and get attention to our provider.

**Comment by ckelner** [comment]
An update: https://github.com/hashicorp/terraform/pull/12201 -- we intend to bring all resources from the repository @renier mentioned into the fold as we move forward, as well as many others.  Cheers.
