### ISSUE TITLE
vpc_security_group_ids  doesn't work for update procedure

### ISSUE THREAD

**Issue by jadzia71** [hashicorp/terraform#10210]
Hey there,

We found the following issue: after updating vpc_security_group_ids for any existing EC2 instance, Terraform can't set all security groups, e.g. if we would like to attach 2 security groups to EC2 instance, only 1 will be attached and will change on each Terraform run. If we don't update security groups for any existing EC2 instance, then everything is provisioned correctly - Terraform correctly detects security groups assigned to EC2 instances. EC2 instances are set up in other than default VPC.

### Terraform Version
Terraform v0.7.10

### Affected Resource(s)
- vpc_security_group_ids (provider/aws)

### Steps to Reproduce
For us, the issue is reproducible on each EC2 instance, but please comment if you have any troubles with reproducing it.

### Temporary hotfix
Setup correct security groups for EC2 instances by AWS console.

**Comment by dlanger** [comment]
I've encountered the same buggy behaviour when updating the `vpc_security_group_ids` parameter of a `aws_redshift_cluster` resource. 

The initial create is fine, but when I alter the `vpc_security_group_ids`list `terraform plan` sees the change (that it needs to add additional entries) correctly and `terraform apply` says it applied the change correctly, but looking at the result in the console, there's been no changes applied. If I run `terraform plan` again immediately after the apply, the proposed change from before is right back there.

**Comment by vic3lord** [comment]
Having the same issue with v0.7.10 to v0.8

**Comment by vic3lord** [comment]
Still valid on `v0.8.2`

**Comment by ddcprg** [comment]
I've opened a the PR https://github.com/hashicorp/terraform/pull/11025 to fix this issue

**Comment by stack72** [comment]
Closed via #11025 - apologies to all for the issue! This will be released in Terraform 0.8.3

**Comment by dlanger** [comment]
Confirmed this is fixed for the `aws_redshift_cluster` case in TF 0.8.4
