### ISSUE TITLE
provider/vsphere: not possible to set disk order on a virtual machine

### ISSUE THREAD

**Issue by moserke** [hashicorp/terraform#10225]
Is there a way to specify the disk order for vsphere virtual machines?  I am currently having a problem in that I need to know which /dev the disk is getting attached to and it's non-deterministic, because it depends on the SCSI device it's attached to, and that order is not being maintained.  Sometimes it will be SCSI 0:2 so /dev/sdb sometimes SCSI 0:3 so /dev/sdc.  Can I specify the SCSI device number so I can force the dev order?

**Comment by voki** [comment]
+1 @moserke Did you manage to find out if this is possible?

**Comment by moserke** [comment]
I ended up having to write a small script that looked at labels and then picked out the device from that.  Put that script in the user data and then called the script to set the device into an environment variable that the format command referenced.  Not that pretty but it worked....

**Comment by moserke** [comment]
script: ```- path: /opt/bin/find-docker-device.sh
    permissions: '0755'
    content: |
      configdrive=`findfs LABEL="config-2"`
      configletter=`echo ${configdrive: -1}`
      if [ $configletter == "b" ]; then
        device=/dev/sdc
      else
        device=/dev/sdb
      fi
      echo $device```

Units: ```- name: find-docker-device.service
      command: start
      content: |
        [Unit]
        Description=Generates /etc/docker-device.env file
        After=dev-sdb.device
        After=dev-sdc.device
        Requires=dev-sdb.device
        Requires=dev-sdc.device
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/sh -c "/usr/bin/echo -n DOCKER_DEVICE=$(/opt/bin/find-docker-device.sh) > /etc/docker-device.env"
    - name: format-ephemeral.service
      command: start
      content: |
        [Unit]
        Description=Formats the ephemeral drive
        After=find-docker-device.service
        Requires=find-docker-device.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=/etc/docker-device.env
        ExecStart=/usr/sbin/wipefs -f $DOCKER_DEVICE
        ExecStart=/usr/sbin/mkfs.ext4 -F $DOCKER_DEVICE -L var-lib-docker```

**Comment by voki** [comment]
Thanks, I have just noticed that terraform creates disks in reverse alphabetical order.
If I name disks "sdb" and "sdc" in config, first one created will be sdc, and because of that it will be /dev/sdb in VM.

**Comment by apparentlymart** [comment]
Sorry this has sat here for so long. :disappointed: 

It seems like this `disk` block is specified as a _set_ within Terraform, which makes Terraform treat it as unordered. This feels like a bug since there's no other way to influence the order and the order has a material effect on how the disks appear in the running VM.

Unfortunately this vSphere provider is not officially supported by Hashicorp at this time, and so we rely on community contributions to improve it. If anyone is motivated to work on a PR to fix this we'd be happy to review it, but unfortunately otherwise it is unlikely to be fixed for the forseeable future. :cry:

**Comment by notuscloud** [comment]
Hi, I've been facing the issue with terraform 0.9.11. It's quite a pain that it's not possible to order disk creation

**Comment by f1gjam** [comment]
So the work around is, you comment out the disks, and just do separate runs of terraform to have the disk created in the order you want
