### ISSUE TITLE
request: Update aws/aws-sdk-go to 1.5.8

### ISSUE THREAD

**Issue by Ninir** [hashicorp/terraform#10234]
Hi guys,

It would be awesome to bum the aws/aws-sdk-go version to 1.5.8. This way, we could benefit from apigateway binary format, lambda env vars, etc.

I tried to install govendor, but every govendor command on my Mac is hanging without doing anything... (excepted for sync, but that's another subject I guess)

(By the way, If someone can help on that, would be awesome!)

**Comment by ajlanghorn** [comment]
👍 to this as a pre-requisite to auto-scaling EMR instance groups.

**Comment by Ninir** [comment]
Finally managed using Docker, but couldn't get it with Mac OSX...
