### ISSUE TITLE
Terraform Apply breaking on template_file upgrade/change

### ISSUE THREAD

**Issue by ckawasaki-isp** [hashicorp/terraform#10231]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.7.11

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- template_file

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
This is the snippet that did not change - only the bootstrap.sh changed.
resource "template_file" "reporting_setup" {
  template = "${file("${path.module}/bootstrap.sh")}"

  vars = {
    service     = "${var.service}"
    environment = "${var.environment}"
    team        = "${var.team}"
  }
}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
Error applying plan:

1 error(s) occurred:

* template_file.reporting_setup: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.7.11
    Resource ID: template_file.reporting_setup
    Mismatch reason: diff: Destroy; old: false, new: true
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"vars.environment":*terraform.ResourceAttrDiff{Old:"Dev", New:"Dev", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vars.team":*terraform.ResourceAttrDiff{Old:"DRM", New:"DRM", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "rendered":*terraform.ResourceAttrDiff{Old:"#!/bin/bash\n##############################################################################\n# Configure InfluxDB\n##############################################################################\n\n# Add InfluxDB user\ntarget_service=influxdb\ndb_user=atlasinflux\ndb_password=\"a6232aca-31da-4d25-afcf-8ae45246c84a\"\nconfig_location=\"/etc/influxdb/influxdb.conf\"\n\nservice $target_service stop\nupdate-rc.d $target_service defaults 95 10\n\nsed -i \"s/\\(auth\\-enabled *= *\\).*/\\1true/\" $config_location\n\nservice $target_service start\n\ninflux -execute \"CREATE USER \\\"$db_user\\\" WITH PASSWORD '$db_password' WITH ALL PRIVILEGES\"\n\n##############################################################################\n# Configure Grafana\n##############################################################################\n\nservice grafana-server start\n", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "template":*terraform.ResourceAttrDiff{Old:"#!/bin/bash\n##############################################################################\n# Configure InfluxDB\n##############################################################################\n\n# Add InfluxDB user\ntarget_service=influxdb\ndb_user=atlasinflux\ndb_password=\"a6232aca-31da-4d25-afcf-8ae45246c84a\"\nconfig_location=\"/etc/influxdb/influxdb.conf\"\n\nservice $target_service stop\nupdate-rc.d $target_service defaults 95 10\n\nsed -i \"s/\\(auth\\-enabled *= *\\).*/\\1true/\" $config_location\n\nservice $target_service start\n\ninflux -execute \"CREATE USER \\\"$db_user\\\" WITH PASSWORD '$db_password' WITH ALL PRIVILEGES\"\n\n##############################################################################\n# Configure Grafana\n##############################################################################\n\nservice grafana-server start\n", New:"#!/bin/bash\n##############################################################################\n# Configure InfluxDB\n##############################################################################\n\n# Add InfluxDB user\ntarget_service=influxdb\ndb_user=atlasinflux\ndb_password=\"a6232aca-31da-4d25-afcf-8ae45246c84a\"\nconfig_location=\"/etc/influxdb/influxdb.conf\"\n\nservice $target_service stop\nupdate-rc.d $target_service defaults 95 10\n\nsed -i \"s/\\(auth\\-enabled *= *\\).*/\\1true/\" $config_location\n\nservice $target_service start\n\ninflux -execute \"CREATE USER \\\"$db_user\\\" WITH PASSWORD '$db_password' WITH ALL PRIVILEGES\"\n\n##############################################################################\n# Configure Grafana\n##############################################################################\n# Install the Simple JSON datasource\ngrafana-cli plugins install grafana-simple-json-datasource\n\nservice grafana-server start\n", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "vars.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vars.service":*terraform.ResourceAttrDiff{Old:"AtlasReporting", New:"AtlasReporting", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"vars.service":*terraform.ResourceAttrDiff{Old:"AtlasReporting", New:"AtlasReporting", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vars.environment":*terraform.ResourceAttrDiff{Old:"Dev", New:"Dev", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "rendered":*terraform.ResourceAttrDiff{Old:"#!/bin/bash\n##############################################################################\n# Configure InfluxDB\n##############################################################################\n\n# Add InfluxDB user\ntarget_service=influxdb\ndb_user=atlasinflux\ndb_password=\"a6232aca-31da-4d25-afcf-8ae45246c84a\"\nconfig_location=\"/etc/influxdb/influxdb.conf\"\n\nservice $target_service stop\nupdate-rc.d $target_service defaults 95 10\n\nsed -i \"s/\\(auth\\-enabled *= *\\).*/\\1true/\" $config_location\n\nservice $target_service start\n\ninflux -execute \"CREATE USER \\\"$db_user\\\" WITH PASSWORD '$db_password' WITH ALL PRIVILEGES\"\n\n##############################################################################\n# Configure Grafana\n##############################################################################\n\nservice grafana-server start\n", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "template":*terraform.ResourceAttrDiff{Old:"#!/bin/bash\n##############################################################################\n# Configure InfluxDB\n##############################################################################\n\n# Add InfluxDB user\ntarget_service=influxdb\ndb_user=atlasinflux\ndb_password=\"a6232aca-31da-4d25-afcf-8ae45246c84a\"\nconfig_location=\"/etc/influxdb/influxdb.conf\"\n\nservice $target_service stop\nupdate-rc.d $target_service defaults 95 10\n\nsed -i \"s/\\(auth\\-enabled *= *\\).*/\\1true/\" $config_location\n\nservice $target_service start\n\ninflux -execute \"CREATE USER \\\"$db_user\\\" WITH PASSWORD '$db_password' WITH ALL PRIVILEGES\"\n\n##############################################################################\n# Configure Grafana\n##############################################################################\n\nservice grafana-server start\n", New:"#!/bin/bash\n##############################################################################\n# Configure InfluxDB\n##############################################################################\n\n# Add InfluxDB user\ntarget_service=influxdb\ndb_user=atlasinflux\ndb_password=\"a6232aca-31da-4d25-afcf-8ae45246c84a\"\nconfig_location=\"/etc/influxdb/influxdb.conf\"\n\nservice $target_service stop\nupdate-rc.d $target_service defaults 95 10\n\nsed -i \"s/\\(auth\\-enabled *= *\\).*/\\1true/\" $config_location\n\nservice $target_service start\n\ninflux -execute \"CREATE USER \\\"$db_user\\\" WITH PASSWORD '$db_password' WITH ALL PRIVILEGES\"\n\n##############################################################################\n# Configure Grafana\n##############################################################################\n# Install the Simple JSON datasource\ngrafana-cli plugins install grafana-simple-json-datasource\n\nservice grafana-server start\n", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "vars.%":*terraform.ResourceAttrDiff{Old:"3", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vars.team":*terraform.ResourceAttrDiff{Old:"DRM", New:"DRM", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:true, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior
Terraform Apply should have worked when Terraform Plan worked

### Actual Behavior
Terraform Apply failed with the above error.

### Steps to Reproduce
1. Using Terraform 0.6.13, apply the changes.
2. Upgrade to Terraform 0.7.11
3. Terraform Plan - this should work (Minor renames were done to match the breaking changes, but the template_file breaking was not changed other than a bugfix.)
4. Terraform Apply 

### Important Factoids
This was a test of our upgrading to Terraform 0.7.11 from 0.6.16

**Comment by mitchellh** [comment]
Tracking this in #10192. Thanks!
