### ISSUE TITLE
Previously valid escaped sequence no longer valid in v0.8.0

### ISSUE THREAD

**Issue by jemmyw** [hashicorp/terraform#10236]
```
terraform -v
Terraform v0.8.0-dev (0522f4322f76e760c293c0c1141e4b3b9fbfbc9b)
```

This is the config:
```
data "null_data_source" "environment" {
  inputs {
    environment = <<ENV
    ${join(",\n", formatlist("{\"name\": \"%s\", \"value\": \"%s\"}", split(",",upper(join(",", keys(var.environment)))), values(var.environment)))}
ENV
  }
}
```

It works with v0.7.11. With v0.8.0 it gives the error:

```
Error loading Terraform: Error downloading modules: module web: Error loading .terraform/modules/c1dd1c6122392193110c2e3000873ee1/service.tf: Error reading config for null_data_source[environment]: parse error at 1:32: invalid backslash escape sequence
```

**Comment by apparentlymart** [comment]
Thanks for reporting this, @jemmyw. This is indeed a regression in the new version of HIL used in 0.8. I opened hashicorp/hil#35 for this, and I intend to work on fixing it now.

**Comment by mitchellh** [comment]
I believe this is a bug but there is some BC incompat in 0.8 around this documented in the changelog. More details here: https://github.com/hashicorp/hcl/pull/150

**Comment by mitchellh** [comment]
Fixed by referenced PR, I'm also going to add a context test case in `terraform` just to make sure we always catch this use case in core in the future.
