### ISSUE TITLE
AWS EFS Mount Target - Missing output (after update Terraform to v0.7.11)

### ISSUE THREAD

**Issue by gfisaris** [hashicorp/terraform#10240]
Hello guys,

i think there is an issue with the latest version of Terraform.

It seems that outputs for aws-efs-mount_targets are not generated.
Below you can see my configuration.

The resources are provisioned without any problem, but no outputs are generated.
Based on my configuration 3 resources should have been added.

Thank you,

### Terraform Version
| => terraform version
Terraform v0.7.11

### Affected Resource(s)
- aws-efs_mount_target

#### aws-efs-file_systems.tf

```hcl
resource "aws_efs_file_system" "master" {
  creation_token = "${data.terraform_remote_state.project.name}"

  tags {
    Name = "${data.terraform_remote_state.project.name}"
  }

}

output "filesystem_master_id"   {value = "${aws_efs_file_system.master.id}"}
```

#### aws-efs-mount_targets.tf

```hcl
resource "aws_efs_mount_target" "master_public_subnets" {
  count = "${lookup(var.selected_aws_region_subnets_public_count, var.selected_aws_region)}"
  file_system_id = "${aws_efs_file_system.master.id}"

  subnet_id = "${data.terraform_remote_state.aws_vpc.subnet_public_id[count.index]}"
  security_groups = ["${data.terraform_remote_state.aws_vpc.security_group_efs_id}"]
}

output "mount_target_master_public_subnets_id" {value = "${aws_efs_mount_target.master_public_subnets.id}"}
output "mount_target_master_public_subnets_dns_name" {value = "${aws_efs_mount_target.master_public_subnets.dns_name}"}
output "mount_target_master_public_subnets_network_interface_id" {value = "${aws_efs_mount_target.master_public_subnets.network_interface_id}"}
```

### Expected Behavior
Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:
filesystem_master_id = fs-5938dc20
mount_target_master_public_subnets_id = XXXXX
mount_target_master_public_subnets_dns_name = XXXXX.XXXX.XXX
mount_target_master_public_subnets_network_interface_id = XXXXX

### Actual Behavior
Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:
filesystem_master_id = fs-5938dc20

**Comment by stack72** [comment]
Hi @gfisaris 

Are you still getting this error? I cannot reproduce it i'm afraid

Thanks

Paul
