### ISSUE TITLE
TF crash with new nomad provider

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#10242]
Hi there,

I have built TF from source, based on today's master (I'm looking to test the nomad provider/resource with @mitchellh's latest update to that vendor code), and I am getting a panic/crash.

### Terraform Version

```
ᐅ ~/bin/terraform-v0.8.0-dev version
Terraform v0.8.0-dev (283d49f12fe203a2cd2ad23acec046f72f7842de+CHANGES)
```

### Affected Resource(s)
Please list the resources as a list, for example:
- nomad_job

### Terraform Configuration Files

```hcl
# Configure the Nomad provider
provider "nomad" {
    address = "http://127.0.0.1:4646"
    region = "us-west-2"
}

# Register a job
resource "nomad_job" "nomad-ui" {
    #jobspec = "${file("${path.module}/jobspec.hcl")}"
    jobspec = <<END_JOB
job "nomad-ui" {
    group "ui" {
    ...
    } # end group
    region = "us-west-2"
    datacenters = ["foobar"]
    # job type
    type = "service"
} # end job
END_JOB
}
```

### Panic Output

https://gist.github.com/ketzacoatl/c7e534f36db79fdeb19ab757766331aa

### References

#10235

**Comment by mitchellh** [comment]
Thanks, should be fixed here... 4406e27eaa6edf79541ac277252edf92988d0f04

**Comment by ketzacoatl** [comment]
Success here, thanks!
