### ISSUE TITLE
AWS EFS - Destroy Resources is not working (after update Terraform to v0.7.11)

### ISSUE THREAD

**Issue by gfisaris** [hashicorp/terraform#10241]
Hello guys,

i think there is an issue with the latest version of Terraform.

It seems that destroying AWS EFS Resources is not working!
Below you can find my complete configuration for the AWS EFS Resources
Thank you,

### Terraform Version
| => terraform version
Terraform v0.7.11

### Affected Resource(s)
- aws-efs_file_system
- aws-efs_mount_target

#### terraform.tfvars

```hcl
selected_aws_region = "us-east-2"

selected_aws_region_subnets_public_count = {
  us-east-2 = "2"
}
```

#### terraform-variables.tf

```hcl
variable "selected_aws_region"                      { type = "string" }
variable "selected_aws_region_subnets_public_count" { type = "map" }
```

#### terraform-imported-sources.tf

```hcl
data "terraform_remote_state" "project" {
  backend = "local"
  config {
    path = "${path.module}/../project/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_ds" {
  backend = "local"
  config {
    path = "${path.module}/../aws-data_sources/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_vpc" {
  backend = "local"
  config {
      path = "${path.module}/../aws-vpc/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_iam" {
  backend = "local"
  config {
    path = "${path.module}/../aws-iam/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_ec2" {
  backend = "local"
  config {
    path = "${path.module}/../aws-ec2/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_ec2_alb" {
  backend = "local"
  config {
    path = "${path.module}/../aws-ec2-alb/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_ecs" {
  backend = "local"
  config {
    path = "${path.module}/../aws-ecs/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_efs" {
  backend = "local"
  config {
    path = "${path.module}/../aws-efs/terraform.tfstate"
  }
}

data "terraform_remote_state" "aws_cloudwatch" {
  backend = "local"
  config {
    path = "${path.module}/../aws-cloudwatch/terraform.tfstate"
  }
}
```

#### terraform-providers.tf

```hcl
provider "aws" {
  region     = "${data.terraform_remote_state.project.aws_region}"
  access_key = "${data.terraform_remote_state.project.aws_access_key}"
  secret_key = "${data.terraform_remote_state.project.aws_secret_key}"
}
```

#### aws-efs-file_systems.tf

```hcl
resource "aws_efs_file_system" "master" {
  creation_token = "${data.terraform_remote_state.project.name}"

  tags {
    Name = "${data.terraform_remote_state.project.name}"
  }

}

output "filesystem_master_id"   {value = "${aws_efs_file_system.master.id}"}
```

#### aws-efs-mount_targets.tf

```hcl
resource "aws_efs_mount_target" "master_public_subnets" {
  count = "${lookup(var.selected_aws_region_subnets_public_count, var.selected_aws_region)}"
  file_system_id = "${aws_efs_file_system.master.id}"

  subnet_id = "${data.terraform_remote_state.aws_vpc.subnet_public_id[count.index]}"
  security_groups = ["${data.terraform_remote_state.aws_vpc.security_group_efs_id}"]
}

output "mount_target_master_public_subnets_id" {value = "${aws_efs_mount_target.master_public_subnets.id}"}
output "mount_target_master_public_subnets_dns_name" {value = "${aws_efs_mount_target.master_public_subnets.dns_name}"}
output "mount_target_master_public_subnets_network_interface_id" {value = "${aws_efs_mount_target.master_public_subnets.network_interface_id}"}
```

### Expected Behavior

data.terraform_remote_state.aws_ds: Refreshing state...
data.terraform_remote_state.aws_cloudwatch: Refreshing state...
data.terraform_remote_state.aws_ec2_alb: Refreshing state...
data.terraform_remote_state.aws_efs: Refreshing state...
data.terraform_remote_state.project: Refreshing state...
data.terraform_remote_state.aws_ecs: Refreshing state...
data.terraform_remote_state.aws_vpc: Refreshing state...
data.terraform_remote_state.aws_iam: Refreshing state...
data.terraform_remote_state.aws_ec2: Refreshing state...
aws_efs_file_system.master: Refreshing state... (ID: fs-5938dc20)
aws_efs_mount_target.master_public_subnets.0: Refreshing state... (ID: fsmt-2437d35d)
aws_efs_mount_target.master_public_subnets.1: Refreshing state... (ID: fsmt-2737d35e)
Destroy complete! Resources: 0 added, 0 changed, 3 destroyed.

### Actual Behavior

data.terraform_remote_state.aws_ds: Refreshing state...
data.terraform_remote_state.aws_cloudwatch: Refreshing state...
data.terraform_remote_state.aws_ec2_alb: Refreshing state...
data.terraform_remote_state.aws_efs: Refreshing state...
data.terraform_remote_state.project: Refreshing state...
data.terraform_remote_state.aws_ecs: Refreshing state...
data.terraform_remote_state.aws_vpc: Refreshing state...
data.terraform_remote_state.aws_iam: Refreshing state...
data.terraform_remote_state.aws_ec2: Refreshing state...
aws_efs_file_system.master: Refreshing state... (ID: fs-5938dc20)
aws_efs_mount_target.master_public_subnets.0: Refreshing state... (ID: fsmt-2437d35d)
aws_efs_mount_target.master_public_subnets.1: Refreshing state... (ID: fsmt-2737d35e)
Error creating plan: 1 error(s) occurred:

* Cycle: aws_efs_mount_target.master_public_subnets (destroy), provider.aws, aws_efs_file_system.master (destroy), data.terraform_remote_state.project (destroy), data.terraform_remote_state.project

**Comment by mitchellh** [comment]
Can you please attach the trace level log (specify `TF_LOG=trace` as an env var)? Please gist it since the contents will be very large. Please also check for any sensitive info.

**Comment by pbthorste** [comment]
This looks like the problem in #7741

**Comment by mitchellh** [comment]
Yeah it does, thanks @pbthorste 

Closing for dup, track over in 7741!
