### ISSUE TITLE
AWS Provider enhancement - Lambda Envrionment Variable Support

### ISSUE THREAD

**Issue by davidski** [hashicorp/terraform#10246]
The oceans have parted and Lambda now natively supports passing environment variables into functions. The API changes are documented at http://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html. Opening an issue for anyone heroic enough to build this into the current AWS provider. Support for selecting KMS keys for encryption (included in the native AWS functionality) also would be much appreciated. This would be an awesome one to trot out before CloudFormation. :)

**Comment by Ninir** [comment]
@davidski I already started working on this. We just need to wait for https://github.com/hashicorp/terraform/pull/10245 first, and then I will propose something :)

**Comment by Ninir** [comment]
@davidski Well, the work is now even prepared in 10255! 😄

**Comment by davidski** [comment]
@Ninir - That's awesome! I feel like a heel for asking, but is there any chance support for specifying the KMS key (http://docs.aws.amazon.com/lambda/latest/dg/API_FunctionConfiguration.html) could also be included? As part of the new feature roll out, environment variables are encrypted with a KMS key which is either a default key or one specified in the function configuration. Allowing the user to specify the key used, as you can on the current CLI, would be super terrific.

**Comment by Ninir** [comment]
@davidski Sure! Will do tomorrow :)

**Comment by Ninir** [comment]
@davidski Just added the KMS Key ARN handling :)

**Comment by Ninir** [comment]
@davidski This has been merged 10 hours ago, so you should be all set for 0.7.12 :)

**Comment by davidski** [comment]
Leaving this open and pinging @catsby from PR #10275. The merged code does not include the KMS specification work in #10255. Would love to get that code included as well, as being able to specify the encryption key is important for some environments (like mine) and it also brings feature parity with CFN. 😀

**Comment by davidski** [comment]
Removed previous incorrect comment about KMS not being included. It is indeed! Back to turkey contemplation!
