### ISSUE TITLE
Terraform does not remove deleted module variables/outputs from the state file

### ISSUE THREAD

**Issue by levinse** [hashicorp/terraform#10268]
v0.7.10

Given 

1. A module, X, which contains an output, e.g. 
```
output "region" {
  value = "us-east-1"
}
```
2. A module, Y, which imports the above module

If I delete "region", it is still maintained in the state file for Y. If you have a ton of modules that import X, the state file grows to be megabytes in size and does not shrink when refactors to remove parts of imported modules are removed from those modules.

**Comment by mitchellh** [comment]
This is all fixed up in 0.7.11

**Comment by levinse** [comment]
Same problem in 0.7.11

**Comment by mitchellh** [comment]
I verified it with 0.7.11 using your exact example.

Ah, I may have left out to use the new graphs `-Xnew-apply`. This has new functionality (such as this) not present in the legacy graphs. The new graphs are default on in 0.8.

I also write a unit test (with your exact example) and verified it removed it!

**Comment by levinse** [comment]
Would it only get removed if the importing module has diffs or would it get
removed in the state of all modules that import the imported module? That
could be the one missing detail here...

**Comment by mitchellh** [comment]
Hm, no, my modules are empty except for the snippet you gave me. :(

**Comment by levinse** [comment]
I think that's the issue. My state file has 25+ instances of an output
which I've removed in a module probably because that module is imported a
lot but the state of the importing modules still contain references to the
output that was removed.

**Comment by levinse** [comment]
It also appears that removing a module which imported another module results in the outputs for the imported module remaining in the state file.
