### ISSUE TITLE
Tag does not have attribute 'id'

### ISSUE THREAD

**Issue by kporembinski** [hashicorp/terraform#10269]
I'm using code from https://www.terraform.io/docs/providers/do/r/tag.html

and I'm getting error:

`* Resource 'digitalocean_tag.lb' does not have attribute 'id' for variable 'digitalocean_tag.lb.id'`

In plan everything is fine:
```
+ digitalocean_tag.lb
    name: "lb"
```

Code:
```
resource "digitalocean_tag" "lb" {
    name = "lb"
}

resource "digitalocean_droplet" "lb1" {
...
	tags = ["${digitalocean_tag.lb.id}"]
        private_networking = true
        ssh_keys = ["${digitalocean_ssh_key.default.id}"]
}
```

**Comment by mitchellh** [comment]
This looks like the DigitalOcean API is broken, I can reproduce this w/o Terraform as well:

```
terraform → curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer 3f7fd27dd69585474e2c2e135ff14d0f1db4f5bdebb68fe91e3a651456749535" -d '{"name":"foo"}' "https://api.digitalocean.com/v2/tags" | jq .
{
  "tag": {
    "name": "awesome",
    "resources": {
      "droplets": {
        "count": 0,
        "last_tagged": null
      }
    }
  }
}
```

The DO API seems to be ignoring the "name" option and just returning `awesome` and when you query that it says `awesome` doesn't exist. Can you please report this with DO?

**Comment by kporembinski** [comment]
Reported to DO. Thanks!

**Comment by tam7t** [comment]
FYI the DigitalOcean API problem that caused this has been fixed
