### ISSUE TITLE
Cannot execute 0.8.0 beta2 on windows

### ISSUE THREAD

**Issue by chrisrlong** [hashicorp/terraform#10266]
### Terraform Version
0.8.0beta2 amd64 and 386

### Affected Resource(s)
terraform.exe

### Panic Output
Couldn't start Terraform: fork/exec C:\Program Files\terraform\terraform.exe: not supported by windows

### Expected Behavior
Terraform should execute normally.

### Actual Behavior
The above output, showing no suport for windows.

### Steps to Reproduce
The above output is made but terraform -v or any other terraform command.

(Linux build works on an Ubuntu vm.)

**Comment by kwilczynski** [comment]
@chrisrlong hi there! I am very sorry that you are having issues! We definitely claim that we support Terraform on Windows, therefore this needs looking into.

Does the pre-0.8 version works for you? I wonder if this is us or rather Go version affecting this.

**Comment by chrisrlong** [comment]
Hi @kwilczynski the beta1 version ran for me, but my apply's kept hanging after a resource completed as per 0.7.9-11. So I kept upgrading......  

```
terraform -v
Terraform v0.8.0-beta1 (1889aee292eacf8b54018f2e9864a3aea6204242)
```

**Comment by mitchellh** [comment]
Figured it out :) Thanks!
