### ISSUE TITLE
Datadog provider Resource:Monitor include_tags bug  

### ISSUE THREAD

**Issue by shmooboy** [hashicorp/terraform#10264]
Hi there,

### Terraform Version
Terraform v0.7.11

### Affected Resource(s)
Please list the resources as a list, for example:
resource "datadog_monitor"

### Terraform Configuration Files
main.tf
{code}
variable "datadog_api_key" { default = "******************************************" }
variable "datadog_app_key" { default = "***************************************"}
variable "cm_email"        { default = "@***********@quantcast.com" }

# set up DATADOG_APP_KEY variable before running this.
provider "datadog" {
  api_key = "${var.datadog_api_key}"
  app_key = "${var.datadog_app_key}"
}

data "terraform_remote_state" "datadog" {
    backend = "s3"
    config {
        bucket = "*************-terraform-state"
        key = "datadog/prod/terraform.tfstate"
        region = "us-west-2"
    }
}

module "cm-datadog" {
  source          = "../../../modules/datadog"
  datadog_api_key = "${var.datadog_api_key}"
  datadog_app_key = "${var.datadog_app_key}"
  cm_email        = "${var.cm_email}"
}
{code}
module-**.tf
{code}
resource "datadog_monitor" "******************************" {
  name = "[NAME] http status check on *******"
  type = "service check"
  query = "\"http.can_connect\".over(\"name:*******-***-prod01-blue\",\"instance:*********_api_prod_status_check_********_***\").last(5).count_by_status()"

  message = <<EOT
{{#is_alert}}
{{***}}
@webhook-***
queue: *********
summary: ********-api-prod.********.**********.com http status page check failed
description: HTTP check of ******-api status page by DNS *******-api-prod [https://app.datadoghq.com/monitors\#manage]
severity: 3
{{***}}
{{/is_alert}}
EOT

  thresholds {
    critical = "5.0"
  }
  include_tags = "false"
}
{code}

### Debug Output
http://cryptb.in/ah7L3ezT

### Panic Output
n/a

### Expected Behavior
What should have happened?
In Datadog > Monitors > "Include triggering tags in notification title" should be unticked

### Actual Behavior
What actually happened?
In Datadog > Monitors > "Include triggering tags in notification title" is ticked

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply

### Important Factoids
not afaik

### References
n/a

**Comment by ojongerius** [comment]
Note this is suffering form the same issue as #8055
