### ISSUE TITLE
Fix or remove flaky BitBucket unit test

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#1027]
We have a unit test that depends on a response from BitBucket.

We get this failure sporadically:

```
--- FAIL: TestBitBucketDetector (0.08s)
	detect_bitbucket_test.go:42: err: error looking up BitBucket URL: invalid character '<' looking for beginning of value
```

We should either fix, rework, or decide it's okay to nuke this test.

**Comment by mitchellh** [comment]
Given it only recently started, I think we should just rework it to handle wehatever is happening

**Comment by mitchellh** [comment]
Done. We just retry a few times and special case this.
