### ISSUE TITLE
Not using S3 on AWS Lambda but still got an error for it when applying

### ISSUE THREAD

**Issue by dkade** [hashicorp/terraform#10270]
Hello

Terraform version: Terraform v0.7.11

Affected Resourse: AWS Lambda/S3 

I'm just trying to create the lambda function so I can map to a method in the API GW. I'm not even using S3 for the code deploy but I get an error for S3:

Terraform file:
resource "aws_lambda_function" "lambda_test" {
function_name = "test_lambda"
role = "lambda_basic_execution"
handler = "code.lambda_handler"
runtime = "python2.7"
}

Error:
aws_lambda_function.lambda_test: s3_bucket and s3_key must all be set while using S3 code source

Please advise.

Thank you

**Comment by apparentlymart** [comment]
Hi @dkade! Sorry for this confusing error message.

What Terraform is trying to say here is that you *must* set either `filename` or the S3 attributes.

The validation code is just missing a check for the "neither set" case and assuming that a lack of filename means you want to use S3.

**Comment by dkade** [comment]
@apparentlymart so the documentation is confusing, because it should state that one of them is required, filename or S3* .

Thank you for the quick answer.
