### ISSUE TITLE
Statuscake test resource sets Alert Trigger Rate and Confirmation Servers To Use to zero

### ISSUE THREAD

**Issue by parabolic** [hashicorp/terraform#10289]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.7.11

### Affected Resource(s)
Please list the resources as a list, for example:
- statuscake_test

### Terraform Configuration Files
```hcl
resource "statuscake_test" "ping" {
  website_name = "${var.website_name}"
  website_url  = "${var.website_url}"
  test_type    = "${var.test_type}"
  check_rate   = "${var.check_rate}"
}

```
### Debug Output
None

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Status cake test should have been created with ```Alert Trigger Rate``` and ```Confirmation Servers To Use``` with a non zero value

### Actual Behavior
```Alert Trigger Rate``` and ```Confirmation Servers To Use``` are both set to zero
![image](https://cloud.githubusercontent.com/assets/2648043/20525555/4892d690-b0c0-11e6-80f7-3ee86e3211fe.png)

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
None
### References
None

**Comment by mitchellh** [comment]
What should the default here be? As far as I can tell their API defaults to zero (hence we default), but I may be wrong there.

**Comment by parabolic** [comment]
Hi @mitchellh, 
thanks for the prompt reply.
From what I see in their documentation here
https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md
Trigger rate defaults to 5
``` 
TriggerRate	No	5	int	0,60	How many minutes to wait before sending an alert
```
And confirmation servers ( I am guessing it's this one ) is set to 0.
```
Confirmation	No	0	int	> 0 & < 10
```
I've have some tests which where created manually and I've just used the defaults with them. They have the following values.
![image](https://cloud.githubusercontent.com/assets/2648043/20538095/fee6fed8-b0ef-11e6-9516-dd61b7634ba5.png)

SO I would say that those are the default values that are set when creating tests via the GUI and those should be in the provider by default and if possible should be passed as params. But personally I would be satasfied with just a working defaults :)

Cheers,
Nikola.
