### ISSUE TITLE
Experimental feature failure

### ISSUE THREAD

**Issue by evanstachowiak** [hashicorp/terraform#10288]
### Terraform Version
0.7.11

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_iam_policy
- aws_s3_bucket

### Terraform Configuration Files
Please contact me, I will be happy to provide.

### Debug Output
https://gist.github.com/evanstachowiak/a4a9e9ae895887b15fe2c8e715510507

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
State should have been updated without error.

### Actual Behavior
Experimental feature failed.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
None

**Comment by mitchellh** [comment]
This should be fixed in 0.7.12 going out now.
