### ISSUE TITLE
provider/aws: Add a new aws_rds_snapshot data source

### ISSUE THREAD

**Issue by edmorley** [hashicorp/terraform#10287]
#10017 recently added the aws_ebs_snapshot data source, fixing #8828.

It would be great if we could have something similar for AWS RDS snapshots, which could be used like so:

```tcl
data "aws_rds_snapshot" "example" {
  most_recent = true
  filter {
    name = "name"
    values = ["foo-prod"]
  }
  owners = ["self"]
}

resource "aws_db_instance" "foo-dev-rds" {
    identifier = "foo-dev"
    snapshot_identifier = "${data.aws_rds_snapshot.example.id}"
    # ...
}
```

This would allow for the workflow of:
* taint existing development/staging RDS instance
* re-run terraform to recreate dev/stage RDS instance from latest snapshot of prod RDS

...without having to hard-code (and continually update) RDS snapshot identifier names like `"rds:foo-prod-2016-11-30-07-05"` in the Terraform config.

**Comment by stack72** [comment]
Hi @edmorley 

I added the PR above - please note that this specific use case is only for db-snapshots NOT db-cluster-snapshots

That second usecase is on the way :)

Paul

**Comment by stack72** [comment]
Closed via #10291

**Comment by edmorley** [comment]
Many thanks!

**Comment by joshuaspence** [comment]
But #10291 hasn't been merged yet?

**Comment by gtmtech** [comment]
Did someone forget about this @stack72 ? It seems to have been closed, but not merged, so... not really closed(?)

**Comment by stack72** [comment]
Hi @gtmtech 

This will be finished this week - I promise!

Paul

**Comment by Seraf** [comment]
Hello, is there some update ? Any chance to get this with the 0.9.3 please ? =)
It would be really awesome !
