### ISSUE TITLE
Feature Request: gsub

### ISSUE THREAD

**Issue by ctro** [hashicorp/terraform#1029]
I've run into a couple situations where I need to format an output string from resourceA as an input to resourceB.

As an example, suppose you want to create an aws_route53_record.  The `name` of the record needs to be built from the public_ip of the attached node.
If the public_ip is "12.34.56.78", the record's `name` has to be "foo-12-34-56-78".

```
resource "aws_route53_record" "foo" {
zone_id = "${var.some_zone_id}"
name = ???  # "foo-${gsub('.', '-', aws_eip.foo.public_ip }"
type = "A"
ttl = "300"
records = ["${aws_eip.foo.public_ip}"]
}
```

The only way I can think to do this now is to write a local-exec provisioner that does string manipulation, writes a json file, and shells out to `awscli`.  Which isn't pretty.

**Comment by pmoust** [comment]
since https://github.com/hashicorp/terraform/commit/adccaad252963f8bfb08b1699a787d00a8ce8066
```
name = "foo-${join("-", ${split(".",${aws_eip.foo.public_ip})})}"
```

But yeah, `gsub` would be welcomed I guess.

**Comment by mitchellh** [comment]
@pmoust Not exactly correct, but close: `name = "foo-${join("-", split(".", aws_eip.foo.public_ip))}"

And this is a decent idea.

**Comment by pmoust** [comment]
:+1:

**Comment by mwitkow-io** [comment]
This would be ridiculously useful in interpolation of files.

**Comment by mitchellh** [comment]
Done, see PR above for docs as well.
