### ISSUE TITLE
Possible documentation discrepancy with `aws_emr_cluster` 

### ISSUE THREAD

**Issue by fosskers** [hashicorp/terraform#10296]
### Terraform Version
`Terraform v0.7.11`

### Affected Resource(s)
- `aws_emr_cluster`

### Terraform Configuration Files
```hcl
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}

resource "aws_emr_cluster" "emr-spark-cluster" {
  name          = "emr-spark-test"
  release_label = "emr-5.2.0"         # 2016 November                                                     
  applications  = ["Hadoop", "Spark"]

  ec2_attributes {
    key_name  = "${var.key_name}"
    subnet_id = "subnet-c5fefdb1" # "${aws_subnet.main.id}"                                               
  }

  master_instance_type = "m3.xlarge"
  core_instance_type   = "m3.xlarge"
  core_instance_count  = 2
  log_uri              = "${var.s3_uri}"

  tags {
    name = "Test Spark Cluster"
    role = "rolename"
    env  = "env"
  }
}
```

### Debug Output
https://gist.github.com/fosskers/8a8fa6f44e3279b269b8e736d43cef99

### Expected Behavior
`service_role` and `ec2_attributes.instance_profile` are [marked as `Optional`](https://www.terraform.io/docs/providers/aws/r/emr_cluster.html#service_role) in the documentation. I expected that if left out, their values would be set to some sensible default. For `service_role` in particular, the `aws emr create-cluster` command has a `--use-default-roles` flag, which I assumed would be used in the background.

### Actual Behavior
`terraform plan` said:

```
  * aws_emr_cluster.emr-spark-cluster: "service_role": required field is not set
  * aws_emr_cluster.emr-spark-cluster: "ec2_attributes.0.instance_profile": required field is not set
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by fosskers** [comment]
`instance_profile` marked as `Required` in the source: https://github.com/hashicorp/terraform/blob/27527ef3cbc88c591721ceb648cb1b4193b5fe69/builtin/providers/aws/resource_aws_emr_cluster.go#L104

`service_role` marked as `Required` in the source: https://github.com/hashicorp/terraform/blob/27527ef3cbc88c591721ceb648cb1b4193b5fe69/builtin/providers/aws/resource_aws_emr_cluster.go#L144

**Comment by fosskers** [comment]
Setting `instance_profile = "EMR_EC2_DefaultRole` and `service_role = `EMR_DefaultRole` fixes the problem.

**Comment by fosskers** [comment]
The working example config given in the docs is quite extensive. The following is a minimum-viable example that works, provided you have the right permissions / keys:

https://github.com/fosskers/playground/blob/master/terraform/emr-spark/emr-spark.tf

**Comment by stack72** [comment]
Hi @fosskers 

Thanks for the work here - I Just opened a PR that fixes the docs up - you are 100% correct on those needing to be Required

https://github.com/hashicorp/terraform/pull/10578

Thanks

Paul
