### ISSUE TITLE
AWS ECS and Application-Auto-Scaling

### ISSUE THREAD

**Issue by yesteph** [hashicorp/terraform#10308]
Hello,

TF_version is 0.7.7.

In the same TF file (see attached file), I declared a aws_ecs_service with 'desired_count' set to 1.

After, I declared :

- an aws_appautoscaling_target for this ECS service : min_capacity is 1 / max_capacity is 10.
- an aws_appautoscaling_policy "scale_in"
- an aws_appautoscaling_policy "scale_out"
- a aws_cloudwatch_metric_alarm "cpu_scale_out"
- a aws_cloudwatch_metric_alarm "cpu_scale_in"

My problem : with auto-scaling, AWS ECS scheduler set desired_count to a value > 1 (ex : 5).
If I run terraform apply, it sets the desired_count to the value defined in the aws_ecs_service resource -> 1! So 4 instances are killed!

I think it is a bug because I cannot deploy a new version of my ECS service with autoscaling.

Thank you.

**Comment by pbthorste** [comment]
Hi, 

I ran into this also. I don't think this is a bug in terraform per-se, amazon requires you to set a desired count on ecs containers. (But you don't have this issue with ec2 autoscaling groups, where you only have to set min and max... go figure.)

To get around this in terraform, just set ignore_changes on the desired count, i.e.

    resource "aws_ecs_service" "my-service" {
      ...
      lifecycle {
        ignore_changes = ["desired_count"]
      }
    }

**Comment by yesteph** [comment]
Hello Petur,

Thank you for the answer, I close the issue.

Regards.
