### ISSUE TITLE
Autoload terraform.tfvars.json if terraform.tfvars does not exist?

### ISSUE THREAD

**Issue by sbward** [hashicorp/terraform#1030]
I've been using `terraform.tfvars.json` because it's easier to use with custom tooling, but Terraform does not autoload this file.  It would be convenient if both the JSON and TFVARS formatted files were autoloaded, if one is present.

**Comment by mitchellh** [comment]
Great idea. Tagged.

**Comment by mitchellh** [comment]
Got this in from above PR. Thanks!
