### ISSUE TITLE
Docs: format examples using terraform fmt

### ISSUE THREAD

**Issue by mtekel** [hashicorp/terraform#10309]
Hi,

I have noticed that some examples in documentation have "hand written" formatting. This is fine, but terraform already has canonical formatting, so it would be nice if all examples would be fomatted using that, so that there is consistency between what terraform considers the right way and what users are shown as example...

**Comment by stack72** [comment]
Hi @mtekel 

Thanks for opening an issue about this - you are correct - we do need to standardise on how we lay out our examples. We are planning an update to our documentation and will make sure that this is addressed

Hope this helps

Thanks

Paul
