### ISSUE TITLE
Crash when deploying Kemp marketplace image in Azure

### ISSUE THREAD

**Issue by davidnite** [hashicorp/terraform#10322]
I can deploy other VMs from the marketplace without any problems, but `azurerm_virtual_machine` is failing at the end of this Kemp image deployment.  Please see the crash log here:

https://gist.github.com/davidnite/f879fbc220edb7455ddd0d6676242e61

Interestingly, the VM is fully functional after the crash.  Here is my template:

[main.tf](https://github.com/hashicorp/terraform/files/609671/main.txt)

**Comment by zhurvla** [comment]
I see the same crash when deploy another Market image. Seems like issue with  'Plan' block.
