### ISSUE TITLE
Impossible for `aws_emr_cluster` workers to be spot instances?

### ISSUE THREAD

**Issue by fosskers** [hashicorp/terraform#10324]
### Terraform Version
`Terraform v0.7.11` 

### Affected Resource(s)
- `aws_emr_cluster`
- (maybe) `aws_spot_instance_request`

### Expected Behaviour
When running Spark apps on EMR, it's common to use an on-demand `master` node with the workers as spot instances. I expected to be able to set `spot_price` (as elsewhere) in `resource "aws_emr_cluster" ...`, but that doesn't seem possible.

When using the `aws emr` CL tool manually, setting `BidPrice=...` as is done [here](https://github.com/geotrellis/geotrellis-landsat-emr-demo/blob/master/Makefile#L76-L77) automatically makes each node a spot instance. Otherwise, it's assumed as on-demand.

**Questions:**

- Is this already possible with `terraform`, and I'm just missing something?
- If so, is it that `aws_spot_instance_request` needs to be connected to `aws_emr_cluster` somehow?
- Or, do I need to provide a custom [launch configuration](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html)?

I haven't found anyone mention this on this repo or elsewhere, which is surprising, unless I'm just an idiot.

Thank you kindly.

**Comment by fosskers** [comment]
As was mentioned elsewhere, having spot instances for EMR workers can save users *a lot* of money when testing large Spark clusters.

**Comment by serelk** [comment]
very interested in this feature as well.

**Comment by onedopiokin** [comment]
Does any one know status of this request?

**Comment by lmorfitt** [comment]
Hi,

Im also interested in this.

Any update please?

thanks.

**Comment by dolphane** [comment]
This would be a significant improvement considering the costs involved in running large Spark clusters

**Comment by dolphane** [comment]
A possible workaround is using the meta approach of deploying a cloudformation stack using terraform. I can confirm that this works and allows you to use spot instances

**Comment by kavitha-Relus** [comment]
any update on this request please ?
