### ISSUE TITLE
Terraform does not show the resource details when running apply.

### ISSUE THREAD

**Issue by chrisrlong** [hashicorp/terraform#10337]
Hi there,

### Terraform Version
Terraform v0.8.0-rc1 (aac47ecf8421da8573155951e36ce5c1aa3fd3a2) Windows AMD64 - (seems to work on linux build)

### Expected Behavior
When terraform apply starts creating a resource it should output the plan for that resource:

```
module.x_instance.mod: Creating...
  ami:                                       "" => "ami-ff0e758c"
  associate_public_ip_address:               "" => "<computed>"
  availability_zone:                         "" => "eu-west-1a"
  ebs_block_device.#:                        "" => "<computed>"
  ephemeral_block_device.#:                  "" => "<computed>"
  iam_instance_profile:                      "" => "x_role"
  instance_state:                            "" => "<computed>"
  instance_type:                             "" => "t2.micro"
  key_name:                                  "" => "terraform"
```

### Actual Behavior
I get blank lines, or more accurately it seems the plan details are output as black text on black background:

```
module.x_instance.mod: Creating...








module.x_instance.mod: Still creating... (10s elapsed)
module.x_instance.mod: Still creating... (20s elapsed)
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by mitchellh** [comment]
Got the fix in a PR!
