### ISSUE TITLE
AWS EMR additional security groups ec2 attributes do not accept list as documented

### ISSUE THREAD

**Issue by cpower** [hashicorp/terraform#10331]
Per the [aws_emr_cluster documentation](https://www.terraform.io/docs/providers/aws/r/emr_cluster.html) the resource is supposed to optionally accept type `list` as additional Amazon EC2 security group IDs for the master and slave nodes via `additional_master_security_groups` and `additional_slave_security_groups`.

### Terraform Version
0.7.12

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_emr_cluster

### Expected Behavior
Terraform should add, if provided, each security group in the respective list to the respective emr cluster's additional security groups field when the cluster is created.

### Actual Behavior
```
Errors:
aws_emr_cluster.emr_cluster: ec2_attributes.0.additional_master_security_groups must be a single value, not a list
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an aws_emr_cluster resource block
2. Set additional_master_security_groups to a list
3. `terraform apply`

**Comment by cpower** [comment]
Looking at the code in terraform/builtin/providers/aws/resource_aws_emr_cluster_test.go it looks like  the additional security groups fields are expecting the older "comma,separated,list,style,definition" of a list.  Not sure if this was mean to be converted to take type LIST with the 0.7 upgrade.

**Comment by nevins-b** [comment]
#10785 should address this issue
