### ISSUE TITLE
Can't import aws_iam_instance_profile

### ISSUE THREAD

**Issue by fubarbaz** [hashicorp/terraform#10341]
As a user I expect to be able to import any resource. Below is an example of a resource which has no `terraform import` implementation. 

### Terraform Version
0.7.11

### Affected Resource(s)
- aws_iam_instance_profile

**Comment by stack72** [comment]
Hi @fubarbaz 

Apologies for the delay here - it's thanksgiving week in the US so the company is off. With regards to imports... not everything is support yet.

We have a list of what is support [here](https://www.terraform.io/docs/import/importability.html)

We are adding to this list all the time! Hopefully we will get `aws_iam_instance_profile` added soon

IF you are in urgent need, please do feel free to open a PR - we love our community to help us make the project better 

Thanks

Paul
