### ISSUE TITLE
provider plugin fails with error "Incompatible API version with plugin. Plugin version: 2, Ours: 1"

### ISSUE THREAD

**Issue by scross01** [hashicorp/terraform#10351]
Provider plugins built against the latest terraform source fail with an incompatible API version error.  For example the [terraform-provider-opc](https://github.com/oracle/terraform) provider builds okay, but at runtime:

```
$ terraform plan
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 2, Ours: 1
```

This appears to be a regression introduced in v0.7.13.  Manually forcing the terraform source in the go build path build back to v0.7.12 and rebuilding the provider plugin resolves the problem, e.g.

```
cd $GOPATH/src/github.com/hashicorp/terraform
git checkout v0.7.12
cd $GOPATH
go build -o bin/terraform-provider-opc github.com/oracle/terraform/provider
```

**Comment by apparentlymart** [comment]
Hi @scross01,

The `master` branch of Terraform is currently tracking towards the forthcoming release of Terraform 0.8, which includes a plugin version change. However, you should still be able to build plugins for 0.7 using the either the `maint-0.7` branch or any of the 0.7 tags.

From your summary it sounds like you tried building with the code in v0.7.13 and found that it was incompatible. Did I understand that right? If so, it would indeed appear that there is a regression in that version.

**Comment by scross01** [comment]
I did try building against the v0.7.13 tag and got the incompatible API error.  I also tried building a different provider plugin to check the issue isn't specific to the `terraform-provider-opc` plugin. same behaviour - runs okay when built against v0.7.12, and generates the incompatible API error when built against v0.7.13

**Comment by akerl** [comment]
It appears that the push that bumped the plugin version snuck into the 0.7.13 tag: https://github.com/hashicorp/terraform/blob/v0.7.13/plugin/serve.go#L22

**Comment by mitchellh** [comment]
The 0.7.13 tag points to the wrong commit. I'm going to fix this now but until then you can also check out 0.7.12.

Otherwise, what @apparentlymart said is correct.
