### ISSUE TITLE
Add function for converting map to json

### ISSUE THREAD

**Issue by tarrant** [hashicorp/terraform#1035]
We store json data in our aws user data which other programs then parse. Currently you can only supply userdata as a string.

It would be convenient to be able to write the JSON data as a map/array and then use a function to convert it in terraform to a json string.

**Comment by phinze** [comment]
@tarrant not a whole lot of community activity on this one. Is this still functionality that would be worth adding for your use case?

**Comment by tarrant** [comment]
I don't think it is something we strongly need anymore. We switched to cloudconfig and yaml. I still don't think its a terrible idea but definitely a back-burner one.

**Comment by paultyng** [comment]
I'm in favor of this, maybe I will take a crack at it.  Since CoreOS's new Ignition format is JSON not YAML, this may be more useful.

**Comment by paultyng** [comment]
Ah nm, I guess you can use Fuze to do it in YAML.  But this would still be useful in some scenarios, still may look at it.

**Comment by paultyng** [comment]
I think this is exists, can probably close, `jsonencode`

**Comment by manojlds** [comment]
`jsonencode` doesn't handle nested maps unfortunately. 

My use case - I want to generate a part of a .json config with a map variable from terraform. Workaround is to have the variable be a string variable and have the json string in it. Having a map would make it a reusable variable.

**Comment by paultyng** [comment]
I think that may have to wait on this, its not specific to `jsonencode`: https://github.com/hashicorp/terraform/issues/2114

**Comment by mitchellh** [comment]
`jsonencode` is the proper approach for this so I'm going to close the enhancement request. What @paultyng brought up is definitely a liimitation that needs to be addressed for it.
