### ISSUE TITLE
provider/google: Support for managed instance group autohealing

### ISSUE THREAD

**Issue by premist** [hashicorp/terraform#10360]
Managed instance group on Google Compute Engine has a feature where you can monitor and automatically re-create instances based on associated health check. You can use `instanceGroupManagers.setAutoHealingPolicies` to apply the health check to the managed instance group, like the following:

```http
POST https://www.googleapis.com/compute/beta/projects/[PROJECT_ID]/zones/[ZONE]/instanceGroupManagers/[INSTANCE_GROUP]/setAutoHealingPolicies

{
 "autoHealingPolicies": [
  {
   "healthCheck": "global/httpHealthChecks/example-check",
   "initialDelaySec": 120
  }
 ]
}
```

Note that this API is currently in beta.

### Documentations

- [API Reference](https://cloud.google.com/compute/docs/reference/beta/instanceGroupManagers/setAutoHealingPolicies)
- [Setting up health checking for managed instance groups](https://cloud.google.com/compute/docs/instance-groups/creating-groups-of-managed-instances#monitoring_groups)

**Comment by evandbrown** [comment]
Thanks, @premist! @danawillow and I will track this for inclusion as it moves towards GA.

**Comment by mumblez** [comment]
sorry to sound pushy, just want to know wha the eta on this is?

**Comment by danawillow** [comment]
No worries! We don't currently support non-GA APIs in the google provider at the moment, but we'll try to add support without too much of a delay once `setAutoHealingPolicies` is in GA.
