### ISSUE TITLE
Terraform crashes if variable is a map

### ISSUE THREAD

**Issue by prabhjot018** [hashicorp/terraform#10361]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
7.10

terraform plan
panic: controller_nodes is not a map, this is a bug in Terraform.

goroutine 1 [running]:
panic(0x2458ae0, 0x4252b79d0)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/terraform.varSetMap(0x4255970b0, 0x425205db0, 0x10, 0x2458ae0, 0x42522cf20)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/variables.go:159 +0x34a
github.com/hashicorp/terraform/terraform.Variables(0x425376230, 0x425119bc0, 0x425597080, 0x0, 0x425597080)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/variables.go:111 +0x38a
github.com/hashicorp/terraform/terraform.NewContext(0x425201dd0, 0x42549d740, 0x0, 0x4362900)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/context.go:151 +0x636
github.com/hashicorp/terraform/command.(*Meta).Context(0x4250b4e00, 0x424ef6144, 0x49, 0x2c22f2e, 0x11, 0x0, 0xa, 0x4, 0x424ed9987, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:186 +0x30a
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0x4250b4e00, 0x425149a40, 0x2, 0x2, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:69 +0x5e2
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0x4250c66c0, 0x425119320, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:154 +0x24e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:154 +0x545
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:86 +0xcb
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:24 +0x38

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

**Comment by mitchellh** [comment]
Hi, can you please share reproduction steps for this?

Thanks for the crash log sometimes that is enough but unfortunately for this issue we'll need more info to reproduce.

**Comment by prabhjot018** [comment]
Hi,

I have a variable of type map as follows:-
variable "controller_nodes" {
  type = "map"
  default = {
    "1" = "01"
    "2" = "01,02"
    "3" = "01,02,03"
  }
}
I have a another variable which is controller_count 
I am using in lookup as:-
nodes                = "${lookup(var.controller_nodes, var.controller_count)}"

Here when i do terraform plan, terraform is crashing.

Thanks,
Prabhjot

**Comment by jbardin** [comment]
Hi @prabhjot018,

Most likely "controller_nodes" is being over-ridden somewhere, but we can't tell without a configuration and the steps used to reproduce the issue. This case was improved in a recent terraform release, and should now show a more useful error when a variable in incorrectly set instead of crashing. 

If the latest release doesn't help solve the problem, feel free to respond here and we can reopen the issue.
