### ISSUE TITLE
Build instructions are not fully automated

### ISSUE THREAD

**Issue by fubarbaz** [hashicorp/terraform#10372]
There is a script reproduced below for context with some commands which have to be executed by a human currently. 

A project should just have one command to build. I also tried to build it without vagrant, but that didn't work for both master and the release candidate. 

If you want to solve this dependency problem, you could provide a Nix expression (see http://nixos.org/nix/manual/) to solve this problem once and for all. 

Another more heavy weight solution is to use a Dockerfile. 

```
# clone the repository if needed
git clone https://github.com/hashicorp/terraform.git
cd terraform

# Spin up a fresh build VM
vagrant destroy -f
vagrant up
vagrant ssh

# The Vagrantfile installs Go and configures the $GOPATH at /opt/gopath
# The current "terraform" directory is then sync'd into the gopath
cd /opt/gopath/src/github.com/hashicorp/terraform/

# Verify unit tests pass
make test

# Build the release
# This generates binaries for each platform and places them in the pkg folder
make bin
```

**Comment by cblecker** [comment]
Terraform is primarily distributed as a signed binary: https://www.terraform.io/downloads.html

Building from source isn't usually necessary unless you're developing Terraform and need to integrate specific changes.

The Vagrantfile is designed for those who may not have a local go development environment set up, or want to test things in an isolated environment.

If you already have a local go development environment set up, and clone the repo into the right go path (required steps for any go-based application), it should work as intenteded:
```
git clone https://github.com/hashicorp/terraform.git $GOPATH/src/github.com/hashicorp/terraform/
cd $GOPATH/src/github.com/hashicorp/terraform/
make test bin
```

Or if you just want to download and install from HEAD without full tests:
```
go get -u github.com/hashicorp/terraform
```

Neither of these are recommended though as they make binaries based on HEAD, which may have pre-release features and bugs.

If you are encountering dependency problems, can you please provide a bit more detail on what exactly isn't working?

**Comment by mitchellh** [comment]
For development, you can build with a single command if you'd like using `go build` (assuming Go is installed, which can of course add a couple more steps but is a one-time cost).

There are a lot more steps involved than those posted above for "release" builds and many can't be automated easily (for example updating/merging the CHANGELOG for stable + master builds). So while we can surely improve there, we probably can't currently get down to a single command.

**Comment by fubarbaz** [comment]
I will probably open a bug with more specific build failures then and only for released versions. Is it correct that this is the only interface you support in terms of what should work? I.e. HEAD can be broken, release candidates can fail to build, but releases should always build?

**Comment by mitchellh** [comment]
@fubarbaz Since just before 0.7.0, we've vendored all dependencies, so `go build` with the latest Go version should always cleanly build on any supported platform without error. If you find errors then please let us know. It is rare for any commit on master to fail to build (as long as the Go version is correct, latest should always work).
