### ISSUE TITLE
Can't modify launch configuration

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#10384]
### Terraform Version
v0.7.8 + v0.7.13.

### Affected Resource(s)
- aws_launch_configuration

If I have a launch configuration (**without** the `ebs_block_device -> delete_on_termination` option set), run apply etc and then change this to include the `delete_on_termination` option, I get:

```
module.core-management.aws_launch_configuration.management-radius: Modifying...
  ebs_block_device.2576023345.delete_on_termination: "true" => "false"
module.core-management.aws_launch_configuration.management-ldap: Modifying...
  ebs_block_device.2576023345.delete_on_termination: "true" => "false"
module.core-management.aws_launch_configuration.management-puppet: Modifying...
  ebs_block_device.2576023345.delete_on_termination: "true" => "false"
module.core-management.aws_launch_configuration.management-krb5: Modifying...
  ebs_block_device.2576023345.delete_on_termination: "true" => "false"
Error applying plan:

4 error(s) occurred:

* aws_launch_configuration.management-radius: doesn't support update
* aws_launch_configuration.management-ldap: doesn't support update
* aws_launch_configuration.management-krb5: doesn't support update
* aws_launch_configuration.management-puppet: doesn't support update
```

I thought this was exactly the reason why TF should create a new launch configuration, "relink" this in the ASG and then delete the old one..

**Comment by cpoole** [comment]
Just experienced this... I ran it a second time and it worked. 

I did not touch the console in between runs but did look around for about 5 minutes.

**Comment by FransUrbo** [comment]
I've tried running it several times without any success.

**Comment by stack72** [comment]
Hi @FransUrbo 

By any chance are you giving the Launch Config a name rather than a name prefix?

Paul

**Comment by FransUrbo** [comment]
No, I used prefix. Just for this reason.

**Comment by jhoblitt** [comment]
Possibly related to this, I've just witnessed `0.7.13` not cleaning up launch configuration when 

``` 
 lifecycle {
    create_before_destroy = true
  }
```

is set.

**Comment by OleksandrBerezianskyi** [comment]
Same on 0.8.2
We change launch configuration pretty often, it is a pain to change related autoscaling groups by hand. 

With 
```
 lifecycle {
    create_before_destroy = true
  }
```
TF first tries to drop old version of launch configuration (that is in use) -> error

Without 
```
 lifecycle {
    create_before_destroy = true
  }
```
TF creates a new launch configuration first and then tries to drop old version of launch configuration (that is in use) -> error

The correct sequence would be:
1) Create a new launch config
2) Change autoscaling group
3) Delete an old launch config

Also, separate `create_depends_on` and `delete_depends_on` would also help a lot

**Comment by catsby** [comment]
Hello – This issue is quite old and I believe addressed with the mentioned `lifecycle` blocks above. If you're still hitting issues here, please let me know!
