### ISSUE TITLE
digitalocean_tag.tag_name shows error when accessed using id in terrafrom 0.7.13

### ISSUE THREAD

**Issue by girishramnani** [hashicorp/terraform#10388]
Hi there,

I am trying to provision a coreos cluster on digitalocean. This is how my `droplet` terraform file looks like

```
resource "digitalocean_droplet" "worker" {
  count = "${var.num_of_servers}"
  name = "****"
  size = "${var.size}"
  image = "coreos-stable"
  region = "${var.region}"
  private_networking = true
  ssh_keys = ["****"]
  tags   = ["${digitalocean_tag.autopilot.id}"]
  user_data = "${element(template_file.init.*.rendered, count.index)}"
}
```

this is the tag that i have added in the same file. 

```
resource "digitalocean_tag" "autopilot" {
  name = "abcd"
}

``` 

now when i am provisioning ( providing all the other terraform files and variables ) I am getting this error.

```
3 error(s) occurred:

* Resource 'digitalocean_tag.autopilot' does not have attribute 'id' for variable 'digitalocean_tag.autopilot.id'
* Resource 'digitalocean_tag.autopilot' does not have attribute 'id' for variable 'digitalocean_tag.autopilot.id'
* Resource 'digitalocean_tag.autopilot' does not have attribute 'id' for variable 'digitalocean_tag.autopilot.id'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

NOTE - Here the error shows up 3 times as the `num_of_servers` is `3` .

### Terraform version 
`v 0.7.13`

**Comment by NicholasPCole** [comment]
Hi Girish - DigitalOcean is looking into this as a potential issue in our API. (See also: issue #10269.) In the meantime, your Terraform configuration should work to create and destroy Droplets if you comment out this line (or anywhere else a tag is assigned to a Droplet):

    tags   = ["${digitalocean_tag.autopilot.id}"]

**Comment by tam7t** [comment]
@girishramnani could you try again and verify if this is still the case? The issue with digitalocean's API should be resolved now

**Comment by girishramnani** [comment]
its fixed. Thank you
