### ISSUE TITLE
terraform fmt changes Windows line endings to Unix

### ISSUE THREAD

**Issue by morkot** [hashicorp/terraform#10381]
### Terraform Version
0.7.10

### Affected Resource(s)
All

### Expected Behavior
No changes and diffs in case of Windows line ending

### Actual Behavior
```terraform fmt``` command overrides line endings to Unix (\n)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
```bash
> unix2dos main.tf                                                               
unix2dos: converting file main.tf to DOS format...                   
            
> terraform fmt -list=true -write=false -diff=true                               
main.tf                                                                          
diff a/main.tf b/main.tf                                                         
--- "C:\\cygwin64\\tmp\\849374163"      2016-11-27 00:39:28.611486200 +0200      
+++ "C:\\cygwin64\\tmp\\301510934"      2016-11-27 00:39:28.611988300 +0200      
@@ -1,5 +1,5 @@                                                                  
-module "acquia_wilcard_dns" {                                                   
-  source = "../../modules/wildcard_dns"                                         
-                                                                                
-  wildcard_dns_map = "${var.acquia_wildcard_dns_map}"                           
-}                                                                               
+module "acquia_wilcard_dns" {                                                   
+  source = "../../modules/wildcard_dns"                                         
+                                                                                
+  wildcard_dns_map = "${var.acquia_wildcard_dns_map}"                           
+}                                                                               

> dos2unix main.tf                                                               
dos2unix: converting file main.tf to Unix format...                              

> terraform fmt -list=true -write=false -diff=true                               
```

**Comment by leepa** [comment]
Are you running `terraform fmt` from the Cygwin of a Command Prompt? It looks like the cygwin prompt which can cause that issue.

**Comment by morkot** [comment]
I use Cygwin usually, but in clean CMD result is the same.

**Comment by morkot** [comment]
However, when I rename file to *.tf.json no error and ```terraform fmt``` just skipping the file:
```bash
> mv variables.tf variables.tf.json

> terraform fmt -list=true -write=false -diff=true

```

**Comment by mitchellh** [comment]
You may disagree, but this is working as intended.

Just as `go fmt`, our official line endings for Terraform configurations are Unix line endings. You're allowed to use `\r\n` if you'd like, but stylistically we prefer `\n`. All editors that are purpose-built for editing code handle this gracefully. Standardizing on one line ending makes it convenient when working with teams.

And, just as with `go fmt`: if you disagree with the styling, then you can choose to not use `terraform fmt`. Our formatting command will always be opinionated towards a singular style. 

We have some commits coming into TF 0.8 to fix some issues with formatting on Windows, but none of the above changes.
