### ISSUE TITLE
ALB load balancer provisioning not complete after an exit status of 0.

### ISSUE THREAD

**Issue by spy-tech** [hashicorp/terraform#10386]
`terraform apply` 0.7.13 returns while alb is still in `provisioning` state. As a user I would expect it to wait until it is in the `active` state.

**Comment by catsby** [comment]
Hey @spy-tech – `aws_alb` correctly waits for the ALB to be in the `active` state in Terraform v0.8.5. This was added in https://github.com/hashicorp/terraform/pull/11333
