### ISSUE TITLE
removal of github.com/terraform/remote breaks older builds 

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#1038]
We are are into merging upstream into our repo, but we face a small issue with the graph refactor, an edge node (an `aws_instance`) is deemed not present and is removed from the state and plan adds it back in. But that's a separate issue that I am trying to narrow down to a simple reproducible case.

We maintain a fork of terraform that we consider '''stable''' for our use case.
In order to get our acceptance tests our CI process has a step that builds terraform from that repo (since we add/remove stuff), and it currently breaks per abb523cc781adcc167448039b0ab84e3838419a2

**Comment by pmoust** [comment]
I guess I could just switch apply/init/meta/pull/push/refresh/remote to track packages from our repo.

**Comment by pmoust** [comment]
Cloning into `$GOPATH/src/github.com/hashicorp/terraform` was far more easier.
Brainfart, excuse the spam.

**Comment by mitchellh** [comment]
Sorry about that, but yes, if you're maintaining a fork please try to fork all of Terraform's internal libs as well. We don't have any external API guarantees on any of them except perhaps `helper/schema`.

**Comment by pmoust** [comment]
Gotcha. :+1:
