### ISSUE TITLE
Diffs Didn't Match During Apply

### ISSUE THREAD

**Issue by thehydroimpulse** [hashicorp/terraform#10405]
### Terraform Version

Terraform v0.7.13

### Affected Resource(s)
Please list the resources as a list, for example:
- null_resource.resource_allocation

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "null_resource" "resource_allocation" {
  triggers {
    cpu    = "${coalesce(var.cpu, lookup(map("low", "64", "medium", "256", "high", "1024"), var.resource_allocation), "64")}"
    memory = "${coalesce(var.memory, lookup(map("low", "104", "medium", "419", "high", "1677"), var.resource_allocation), "104")}"
  }
}
```

### Debug Output

https://gist.github.com/thehydroimpulse/d02d333db57b4ef7010680e16c429979

### Expected Behavior

Should have applied successfully.

### Actual Behavior

The apply errors saying the diffs didn't match.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by mitchellh** [comment]
Tried your exact changes on master and 0.7.13 and wasn't able to reproduce. Great reproduction config though, but it just always worked for me. I changed resource allocation from "low" to "medium" (which it appears you were doing based on your error) and it just worked.

If you can explain any further what may have happened, I'll try again!
