### ISSUE TITLE
vsphere certificate error

### ISSUE THREAD

**Issue by fulloflilies** [hashicorp/terraform#10400]
Hi,

I am getting an error for vsphere certificate when I tried to create a VM from template. 

### Terraform Version
Terraform v0.7.13

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files
```
resource "vsphere_virtual_machine" "newvm" {
  name   = "vm01"
  vcpu   = 1
  memory = 2048
  domain = "vsphere.local"
  datacenter = "datacenter"
  cluster = "cluster"

  network_interface {
      label = "VM Network"
  }

  disk {
    datastore = "datastore1"
    template = "template"
  }
}
```

### Actual Behavior
When I run "terraform plan", it shows error as following

Error refreshing state: 1 error(s) occurred:

* Error setting up client: Post https://xx.xx.xx.xx/sdk: x509: certificate is valid for yy.yy.yy.yy, not xx.xx.xx.xx

**Comment by fulloflilies** [comment]
I am getting another error after I reset vCenter server IP. It looks like self-signed certificate isn't working. Is there any way to workaround this? 

Error refreshing state: 1 error(s) occurred:

* Error setting up client: Post https://xx.xx.xx.xx/sdk: x509: certificate signed by unknown authority

**Comment by davey-dev** [comment]
You should use 'allow_unverified_ssl', like below:
```
provider "vsphere" {
    user = "${var.vsphere_user}"
    password = "${var.vsphere_password}"
    vsphere_server = "${var.vsphere_vcenter}"
    **allow_unverified_ssl = "${var.allow_unverified_ssl}"**
}
```

**Comment by fulloflilies** [comment]
@davey-dev 
allow_unverified_ssl works!
