### ISSUE TITLE
Map variable with single element considered type string

### ISSUE THREAD

**Issue by OmarDarwish** [hashicorp/terraform#10401]
When trying to interpolate a map with only one element, I get an error. This error does not affect maps with more than 1 element.

### Terraform Version
Terraform v0.7.13

### Affected Resource(s)
- data.terraform_remote_state
- map variables
- modules

Might be something related to core.

#### Global state 
Here's a snippet of the remote state file showing the output I am interested in using, assuming it lives in bucket `foo`, with key `bar.tfstate`.
```JSON
...
"aws_iam_role-exhibitor-unique_id": {
    "sensitive": false,
    "type": "map",
    "value": {
         "valA": "<redacted>"
    }
},
"aws_iam_role-role-arn": {
    "sensitive": false,
    "type": "map",
    "value": {
         "val1": "<redacted>",
         "val2": "<redacted",
         "val3": "<redacted>"
     }
},
...
```

#### Remote data source
```HCL
data "terraform_remote_state" "global_iam" {
  backend = "s3"
  config {
    bucket = "foo"
    key = "bar.tfstate
    region = "us-east-1"
    profile = "my_profile"
  }
}
```
#### Trying to use variables:
```HCL
module "myFirstModule" {
  source = "first"
  s3_role_ids = [
    "${data.terraform_remote_state.global_iam.aws_iam_role-exhibitor-unique_id["valA"]}",
  ]
}

module "mySecondModule" {
  source = "second"
  s3_role_ids = [
    "${data.terraform_remote_state.global_iam.aws_iam_role-role-unique_id["val1"]}",
  ]
}
```

The first one fails, the second one works fine.
### Debug Output
```
Error configuring: 1 error(s) occurred:

* At column 3, line 1: invalid index operation into non-indexable type: TypeString in:

${data.terraform_remote_state.global_iam.aws_iam_role-exhibitor-unique_id["valA"]}
```
### Panic Output
None

### Expected Behavior
When referencing an element in a map that only has that element, the map should be considered a map and not a string.

### Actual Behavior
Terraform seems to think that if a map only has one element, it is a string.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Set up s3 remote config in one module
2. Declare an output of type map with only element
3. In another module, set up a `remote_terraform_state` data source pointing to the remote state of the first module
4. Try to use the map output containing only one element

### References
- GH-7906

**Comment by OmarDarwish** [comment]
Doing some more experimentation, I added another key to the buggy map, but it did not solve the issue. Another engineer did notice though that we have similar key names but for different modules. One of them is a map, the other is a string, but both have the same name:

#### String output from submodule with same name
This might be the output that is being referenced accidently. It is from a submodule:

```JSON
"path": [
		"root",
		"exhibitor_logging"
],
"outputs": {
		"aws_iam_role-exhibitor-unique_id": {
				"sensitive": false,
				"type": "string",
				"value": "<redacted>"
		}
},
```

The for the first module that has a remote state contains a `main.tf` that contains the above module declarations re-exposes this output like this:
```HCL
module "exhibitor_logging" {
	source = "path/to/module"
	...
}

output "aws_iam_role-exhibitor-unique_id": {
	valA = "${module.exbibitor_logging.aws_iam_role-exhibitor-unique_id}"
}
```

**Comment by OmarDarwish** [comment]
We determined our issue to be related to a stale `data.terraform_remote_state` resource. Our dependent module did not pull the latest version of the remote state of the module it depended on. We fixed this issue by manually removing the `data.terraform_remote_sate.<dependency_module>` `resource` from the dependent modules `.tfstate` file.

After removing that resource, we re-ran `terraform plan`, and everything seemed to work. 

To future internet readers: your `terraform_remote_state` might be stale. Check your `.tfsate` file and look a the `attributes` of the resource you're having issues with.

**Comment by djalexd** [comment]
@OmarDarwish long overdue, but how could your `terraform_remote_state` become stale? We face the same issue with terraform `0.11.3`: we got 2 projects, one depends on state of another, but the downstream project doesn't seem to update its internal reference. Also, committing the removal (or worse, doing a manual intervention) + reversing the removal seems to not be the solution (it works once, but then it will happen again and again)

**Comment by richardgavel** [comment]
I had a similar issue where the data type of an output of a remote state changes from a list to a string. I would get an error module.foo_ecs.var.development_api_key: variable development_api_key in module foo_ecs should be type string, got list. TF should be refreshing the local copy of the remote state but isn't. I had to run a terraform refresh -target data.terraform_remote_state.my_state to make it unstale.
