### ISSUE TITLE
`terraform console` ignores terraform.tfvars

### ISSUE THREAD

**Issue by lalyos** [hashicorp/terraform#10412]
I'm trying to use the new `terraform console` command. But cant evaluate anything else than the sample mentioned in the docs: `1 + 5`.

### Terraform Version
both 0.8.0-rc1 and dev version built from master is tried
```
Terraform v0.8.0-rc1 (aac47ecf8421da8573155951e36ce5c1aa3fd3a2)
Terraform v0.8.0-dev (3bf93501a11738ce9b918b26299b8de4a03b40d2+CHANGES)
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
I expected to be able to reference the `foo` variable, and get back its actual value: `bar`

### Actual Behavior

```
$ echo 'foo' | terraform console -var 'foo=bar'

invalid variable syntax: "foo". If this is part of inline `template` parameter
then you must escape the interpolation with two dollar signs. For
example: ${a} becomes $${a}.
```

**Comment by mitchellh** [comment]
You'll want `var.foo`.

The syntax for Terraform console is the same syntax you'd put in a Terraform configuration file.

**Comment by lalyos** [comment]
i doesnt seem to work:

```
$ echo 'var.foo' | terraform console -var 'foo=bar'
1:3: unknown variable accessed: var.foo in:
${var.foo}
```

I even tried to put variables into `terraform.tfvars`, but they also not accessable

**Comment by mitchellh** [comment]
That's also correct, you never defined the variable in a configuration file:

```
variable "foo" {}
```

The console is giving you a REPL _on top_ of your state/config. Both are optional since you can still do things like math, function calls on strings, etc. But you can't access variables or resources unless you have one of state or config.

It behaves _just_ like a Terraform config.

**Comment by lalyos** [comment]
`terraform console --help` help suggests:

> If "terraform.tfvars" is present, it will be automatically loaded 

But it seems that its only working if the variable in the config file uses a default value. The values from `terraform.tfvars` are ignored.

I've created a gist where i can reproduce the issue:
https://gist.github.com/lalyos/3062a3c11c704c4e3a69869523faf21c

**Comment by mitchellh** [comment]
Ah hah, that looks like a bug. Thanks. I'll look into that today.

**Comment by mitchellh** [comment]
Got a fix queued up that will be in RC2
