### ISSUE TITLE
aws_default_route_table doesn't create entry on gateway_id, constantly recreates resource

### ISSUE THREAD

**Issue by chrisburrus** [hashicorp/terraform#10426]
This is an issue with assigning an entry in the aws_default_route_table on a VPC to point to an internet gateway. Surprised I could not find a bug report of it, it's very repeatable, and I was only on like, step 4 of terraforming my deployment.

### Terraform Version
v0.7.13

### Affected Resource(s)
- aws_internet_gateway
- aws_default_route_table

### Terraform Configuration Files
```
resource "aws_vpc" "bosh_vpc" {
  cidr_block = "10.0.0.0/16"

  tags {
    Name = "bosh-default-vpc"
  }
}

resource "aws_internet_gateway" "bosh_default_internet_gateway" {
  vpc_id = "${aws_vpc.bosh_vpc.id}"

  tags {
    Name = "bosh-default-internet-gateway"
  }
}

resource "aws_default_route_table" "bosh_default_route_table" {
  default_route_table_id = "${aws_vpc.bosh_vpc.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.bosh_default_internet_gateway.id}"
  }

  tags {
    Name = "bosh-default-route-table"
  }
}

resource "aws_default_security_group" "bosh_default_security_group" {
  vpc_id = "${aws_vpc.bosh_vpc.id}"

  tags {
    Name = "bosh-default-security-group"
  }

  ingress {
    from_port = 0
    to_port   = 0
    protocol  = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

```

### Debug Output
https://gist.github.com/chrisburrus/2c798c49a73596a68f5611b06529f018

### Panic Output
None

### Expected Behavior
It should have put an entry in the route table, with destination: 0.0.0.0/0 and target: the internet gateway created. I have another VPC with an identical setup that works with no issues.

### Actual Behavior
Not only did it not create the entry in the route table, but REALLY oddly, it just constantly recreates the resource entirely on every single `terraform apply`. I triple checked that I'm following the documentation right, it should be really simple - yet it constantly thinks the resource doesn't exist. `terraform show` also does not show the route table at all. Despite the entry and the attempted creation, it just does not exist in the tfstate file at all.

### Steps to Reproduce
1. `terraform apply`
2. Observe the lack of entry in tfstate file as well as the route table entry
3. Feel free to redo `terraform apply` and watch it chain-create the route table, thinking it doesn't exist each time. Really strange. Destroying and recreating, changing names etc, did not help.

### Important Factoids
Very standard AWS account, less than 2 years old so don't think it's a weird EC2 classic issue or anything.

### References
Could not find any references to this issue.

**Comment by r0c** [comment]
I am having the same issue, have to assign the route manually. Waiting for a solution.
