### ISSUE TITLE
Feature Request: force provisioner on resource update

### ISSUE THREAD

**Issue by ctro** [hashicorp/terraform#1042]
I have an `aws_instance` with an attached `aws_eip`.
Some provision steps on the instance require the aws_eip.public_ip as input.

In order to work around a cycle in the resource graph I'm using a remote-exec provisioner on the `aws_eip` that has a connection block specifying the `aws_instance`.

re-applying the `aws_instance` with changes will only Update the `aws_eip`.
Because it's only an update operation the associated provisioner does not run on the `aws_instance`

Perhaps the real fix is to figure out how to reference `${aws_eip.public_ip}` in a provisioner on the `aws_instance` without a cycle in the graph, but I'm not sure this is possible...

I hope GH Issues are an OK way to send ideas like this your way.
I've been so impressed with Terraform (and packer and consul and...)
Thanks so much for sharing all of this hard work.

**Comment by ctro** [comment]
This is kind of a dup of #557 
The same problem is discussed there.

**Comment by catsby** [comment]
Is this possibly addressed with #1065 ?

**Comment by mitchellh** [comment]
@clint Kind of, in a very blunt way, but with an EIP it is a bit sketchier since you'll get a different IP on each recreate and that might not be something you want to do. I'm going to keep thinking about this.

@ctro You're right, let's close in favor of #557

**Comment by ctro** [comment]
@mitchellh, Roger.  Thanks for thinking.
@catsby I hadn't seen any of this taint talk yet, but agree it could help solve the problem.  yes, EIP will change addresses, but that's handle-able.
