### ISSUE TITLE
Experimental Feature Failure

### ISSUE THREAD

**Issue by DustinChaloupka** [hashicorp/terraform#10423]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.7.13

### Affected Resource(s)
Unsure, but it appears to be the vsphere provider based on the variables.

### Terraform Configuration Files
Unsure of what configuration files to give that would be relevant. Some of the variables are coming from a tfvars file (password, user, and server) and the other one is a default in the provider:

```hcl
variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}

provider "vsphere" {
  allow_unverified_ssl = true

  user = "${var.vsphere_user}"
  password = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"
}
```

tfvars file:
```
vsphere_password = "<redacted>"
vsphere_user = "<redacted>"
vsphere_server = "10.203.131.24"
```

### Debug Output
`Experimental feature failure! Please report a bug.` was given after a `terraform plan` so opening this as it suggested to.

The log output that was given can be found in a [gist](https://gist.github.com/DustinChaloupka/7e77bfcf4ac7c232cb8fb720eeddbaeb).

### Panic Output
None

### Expected Behavior
No experimental failure I suppose?

### Actual Behavior
Experimental failure.

### Steps to Reproduce
Unsure how to reproduce

### Important Factoids
The vsphere provider being defined is in a nested module, but not sure if that would affect this or not.

### References
None

**Comment by mitchellh** [comment]
Thanks, unfortunately without a reproduction we won't be able to fix this. Viewing the log is sometimes enough to find a fix but in this case it is not. If you find a stable way to reproduce this, please reopen a new issue. Thanks!
