### ISSUE TITLE
Feature Request: default_* attributes for aws_vpc data source

### ISSUE THREAD

**Issue by cbarbour** [hashicorp/terraform#10428]
### Affected data source
- aws_vpc

### Terraform Configuration Files
```hcl
data "aws_vpc" "default" {
  default = true
}

resource "aws_default_route_table" "main" {
  default_route_table_id = "${data.aws_vpc.default.default_route_table_id}"

  tags {
    Name = "Main VPC Default table"
  }
}

resource "aws_default_security_group" "main" {
  vpc_id = "${data.aws_vpc.default.id}"

  tags {
    Name = "Main Default security group"
  }
}

resource "aws_default_network_acl" "main" {
  default_network_acl_id = "${data.aws_vpc.default.default_network_acl_id}"
  subnet_ids = [ "${aws_subnet.main.*.id}" ]

  tags {
    Name = "Main VPC Default Network ACL"
  }
}
```

### Expected Behavior
It would be useful if aws_default_network_acl, aws_default_route_table, & aws_default_security_group were available as attributes of the aws_vpc data source so that these resources could be managed without importing the default VPC.

### Actual Behavior
The aws_vpc data source doesn't export these attributes, making it impossible to discover their resource IDs.

### Important Factoids
The alternative would be to import the default VPC into Terraform, and reference it's attributes. However, if destroyed it's impossible for Terraform to recreate the default VPC.

`prevent_destroy` could be used, but that would break the blanket `terraform destroy` command.

### References
https://aws.amazon.com/premiumsupport/knowledge-center/deleted-default-vpc/

**Comment by ewbankkit** [comment]
@cbarbour : With a couple of open PRs

* https://github.com/hashicorp/terraform/pull/11710 to add an `aws_default_vpc` resource
* https://github.com/hashicorp/terraform/pull/12709 to add an `aws_network_acl` data source

I think this can be achieved without modifying the `aws_vpc` data source.

You can get the VPC ID from the `aws_vpc` data source and then use the existing `aws_route_table` data sources to get the ID you want:
```
data "aws_vpc" "default" {
  default = true
}

data "aws_route_table" "default" {
  vpc_id = "${data.aws_vpc.default.id}"

  filter {
    name = "association.main"

    values = [
      "true",
    ]
  }
}

resource "aws_default_route_table" "main" {
  default_route_table_id = "${data.aws_route_table.default.id}"

  tags {
    Name = "Main VPC Default table"
  }
}
```

Once https://github.com/hashicorp/terraform/pull/12709 is merged then you can do the same for the default NACL:
```
data "aws_network_acl" "default" {
  vpc_id = "${data.aws_vpc.default.id}"
  default = true
}

resource "aws_default_network_acl" "main" {
  default_network_acl_id = "${data.aws_network_acl.default.id}"
  subnet_ids = [ "${aws_subnet.main.*.id}" ]

  tags {
    Name = "Main VPC Default Network ACL"
  }
}
```

And once https://github.com/hashicorp/terraform/pull/11710 is merged:
```
resource "aws_default_vpc" "default" {
  tags {
    Name = "Main VPC"
  }
}

resource "aws_default_route_table" "main" {
  default_route_table_id = "${aws_default_vpc.default_route_table_id}"

  tags {
    Name = "Main VPC Default table"
  }
}

resource "aws_default_security_group" "main" {
  vpc_id = "${aws_default_vpc.id}"

  tags {
    Name = "Main Default security group"
  }
}

resource "aws_default_network_acl" "main" {
  default_network_acl_id = "${aws_default_vpc.default_network_acl_id}"
  subnet_ids = [ "${aws_subnet.main.*.id}" ]

  tags {
    Name = "Main VPC Default Network ACL"
  }
}
```
