### ISSUE TITLE
azurerm_virtual_machine_extension cannot update/create

### ISSUE THREAD

**Issue by TamasSzerb** [hashicorp/terraform#10443]
Hello,

### Affected Resource(s)
azurerm_virtual_machine_extension.xxx: Creating...
  location:             "" => "westus"
  name:                 "" => "docker-engine"
  publisher:            "" => "Microsoft.OSTCExtensions"
  resource_group_name:  "" => "xxx"
  settings:             "" => "    {\n        \"commandToExecute\": \"DEBIAN_FRONTEND=noninteractive apt install -qy docker.io\"\n    }\n"
  tags.%:               "" => "1"
  tags.environment:     "" => "dev"
  type:                 "" => "CustomScriptForLinux"
  type_handler_version: "" => "1.2"
  virtual_machine_name: "" => "xxx"
azurerm_virtual_machine_extension.xxx: Still creating... (10s elapsed)
azurerm_virtual_machine_extension.xxx: Still creating... (20s elapsed)
azurerm_virtual_machine_extension.xxx: Still creating... (30s elapsed)

and never ends or times out. From my experience, if the command is very short (eg. hostname) it will be created if we are creating new VM on new environment.

### Terraform Configuration Files
```hcl
# https://github.com/Azure/custom-script-extension-linux
resource "azurerm_virtual_machine_extension" "xxx" {
    name = "docker-engine"
    location = "West US"
    resource_group_name = "${azurerm_resource_group.xxx.name}"
    virtual_machine_name = "${azurerm_virtual_machine.xxx.name}"
    publisher = "Microsoft.OSTCExtensions"
    type = "CustomScriptForLinux"
    type_handler_version = "1.2"

    settings = <<EOF
    {
        "commandToExecute": "DEBIAN_FRONTEND=noninteractive apt install -qy docker.io"
    }
EOF

    tags {
        environment = "dev"
    }
}
```

### Expected Behavior
Create/modify the OS Extension on Azure

### Actual Behavior
Never ends, times out or reports that the object is not existing

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Microsoft Azure in ARM (new) mode

Thanks,

Tamas

**Comment by TamasSzerb** [comment]
eg. doing everything from scratch:

azurerm_virtual_machine_extension.xxx: Still modifying... (1h30m0s elapsed)
azurerm_virtual_machine_extension.xxx: Still modifying... (1h30m10s elapsed)
azurerm_virtual_machine_extension.xxx: Still modifying... (1h30m20s elapsed)
azurerm_virtual_machine_extension.xxx: Still modifying... (1h30m30s elapsed)
Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine_extension.xxx: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="VMExtensionProvisioningTimeout" Message="Provisioning of VM extension 'docker-engine' has timed out. Extension installation may be taking too long, or extension status could not be obtained."

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

...

azurerm_virtual_machine_extension.xxx: Still modifying... (1h30m10s elapsed)
azurerm_virtual_machine_extension.xxx: Still modifying... (1h30m20s elapsed)
azurerm_virtual_machine_extension.xxx: Still modifying... (1h30m30s elapsed)
Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine_extension.xxx: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="VMExtensionProvisioningTimeout" Message="Provisioning of VM extension 'docker-engine' has timed out. Extension installation may be taking too long, or extension status could not be obtained."

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by samirageb** [comment]
I ran into a similar issue today except I got a 404 error:

> azurerm_virtual_machine_extension.stage: Error making Read request on Virtual Machine Extension CustomScript: compute.VirtualMachineExtensionsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Compute/virtualMachines/Engine-Test-Vm/extensions/CustomScript' under resource group 'Engine-Test-WestUS-Rg' was not found."

I was able to remedy the issue by removing any hyphen (-) from the name field.

**Comment by samirageb** [comment]
This is Terraform version ## 0.8.2

Ok I have managed to get things working consistently after removing the .terraform directory and .tfstate files and starting from scratch. I had previously been manually deleting VMs from Azure and while the azurerm_virtual_machine resource can recover nicely, it appears that the azurerm_virtual_machine_extension resource is not as robust during the refresh process. Upon not detecting the existence of the extension, the entire script would break.

Even though I don't believe this to be Azure extension version specific, I can confirm this code works.

```hcl
resource "azurerm_virtual_machine_extension" "stage" {
    name = "CustomScript"
    location = "West US"
    resource_group_name = "${azurerm_resource_group.stage.name}"
    virtual_machine_name = "${azurerm_virtual_machine.stage.name}"
    publisher = "Microsoft.Azure.Extensions"
    type = "CustomScript"
    type_handler_version = "2.0"
    auto_upgrade_minor_version = true

    settings = <<SETTINGS
    {
        "commandToExecute": "sh engine-env-stage.sh",
        "fileUris": ["https://XXXXXXXXX.blob.core.windows.net/scripts-public/engine-env-stage.sh"]
    }
SETTINGS

    tags {
        environment = "Production"
    }
}
```

I believe my issue lies somewhere in the dependency handling with regards to the extension and refreshing the state. I will try recreating the issue and report back.
