### ISSUE TITLE
Amazon Lightsail

### ISSUE THREAD

**Issue by jgartrel** [hashicorp/terraform#10447]
This is a feature request to support Amazon Lightsail, per their public announcement there are separate APIs.

> As is almost always the case with AWS, there’s a full set of APIs behind all of the console functionality that we just reviewed. Here are just a few of the more interesting functions:
> 
> - GetBundles – Get a list of the bundles (machine configurations).
> - CreateInstances – Create one or more Lightsail instances.
> - GetInstances – Get a list of all Lightsail instances.
> - GetInstance – Get information about a specific instance.
> - CreateInstanceSnapshot – Create a snapshot of an instance.
> - CreateInstanceFromSnapshot – Create an instance from a snapshot.

https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/Welcome.html?fid=71746835D2E3C6B0-212737D1B3CC5C3F

Thank you,

James

**Comment by nodesocket** [comment]
👍  💯

**Comment by jessefulton** [comment]
Looks like this was partially implemented by #10473 - it would be amazing to add support for static ips as well!

**Comment by nodesocket** [comment]
👍  for static ips support.

**Comment by jgartrel** [comment]
@catsby It would be great to allow CreateInstanceFromSnapshot in the existing implementation of lightsail instance.   Are you interested in working on that?

**Comment by catsby** [comment]
@jgartrel I'm strapped ATM but otherwise would love to. If you're up for taking a stab at it, please ping me on the PR 😄

**Comment by radeksimko** [comment]
Hi folks,
I think we now have the initial support of Lightsail in place, including static IPs which I've done in #13175 & #13207

There's clearly a potential for 1 or 2 more resources (`aws_lightsail_domain_entry` & `aws_lightsail_public_port`), but as a "house-keeper" 🚿 I do not want to see this issue expanding into "anything Lightsail we might ever support" and going stale, hence I'm closing it. With that said we certainly welcome PRs with for the mentioned resources and will gladly review them. It is possible that the HC team may implement these resources at some point, but unlikely in the near-term.

Thanks!

**Comment by k99bw01** [comment]
Load balancer support and Snapshot support would be great.
