### ISSUE TITLE
docker_container network options

### ISSUE THREAD

**Issue by srirammageswaran** [hashicorp/terraform#10452]
Hi Team,

Any way we can add an network alias to the docker containers being provisioned. ..?

Wanted to see if we can use the --network-alias . I see that we can use "networks" to attach the container to multiple networks.

Thanks ,
Sriram.

**Comment by dmportella** [comment]
i will make this change

**Comment by dmportella** [comment]
mind you the network bit should add containers to multiple networks (by network id)

**Comment by jwayong** [comment]
Pull request available on #14710 for --network-alias

**Comment by grubernaut** [comment]
Closed via #14710, thanks!
