### ISSUE TITLE
[feature request] Setting remote state via terraform provider

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#10466]
It would be *extremely* useful to be able to programmatically set the `remote state` so it can automatically be part of the terraform `plan`/`apply`/etc.

Use case:
We use the same terraform `*.tf` files to deploy an application (and sometimes multiple applications) to multiple aws vpc and regions. Right now we use a wrapper script to avoid running `terraform remote config` which parses `*.tf` and `*.tfvars` files & the `-var`/`-var-file` command line options to determine which remote state file to use. But running it manually leads to significant user errors because it is too easily forgotten before deploying to a different environment.
e.g., we run `tf apply -var-file dev-aws-us-west-2.tfvars -var-file my-app.tfvars` or `tf apply -var-file staging-aws-eu-east-1 -var-file myother-app.tfvars` and the `tf` wrapper script sets the remote state based on the `application-name`, `region`, and `environment` variables defined in the `*.tf` and appropriate `tfvars` files.

Example code:
I'd like to propose something similar to this example to set the remote state automatically.

```
config "terraform_remote_state" "example" {
  backend = "s3"
  config {
    bucket = "my-bucket"
    key = "${var.application-name}/${var.region}/${var.environment}/terraform.tfstate"
  }
}
```

```
config "terraform_remote_state" "example" {
    backend = "atlas"
    config {
        name = "example/${var.application-name}-${var.region}-${var.environment}"
    }
}
```

This way it could use the existing `aws` or `atlas` provider and would automatically switch based on the `application-name`, `region`, and `environment` variables. 

I'm not sure if it belongs in a regular `.tf` file or if it should be its own file like `'terraform.remote`. 

Sorry if there's already an open issue for this. I vaguely remember discussing this with someone in the past but I don't remember if it was in person or here on GH. I searched but couldn't find one.

**Comment by stack72** [comment]
Hi @mtougeron 

Thanks for raising the issue here - do you mean that you would like to be able to do this as part of the provider block?

i.e.

```
provider "aws" {
  region = "us-west-2"
  config "terraform_remote_state" "example" {
    backend = "s3"
    config {
      bucket = "my-bucket"
      key = "${var.application-name}/${var.region}/${var.environment}/terraform.tfstate"
    }
  }
}
```

**Comment by mtougeron** [comment]
@stack72 I'm actually not sure the best place for it. I was thinking it'd be it's own resource type so that it'd easily work with any provider. In my current case I'm using an S3 bucket but I've had others where it was stored in Consul.

**Comment by apparentlymart** [comment]
I think this is the same as #1964; would you agree, @mtougeron?

**Comment by mtougeron** [comment]
@apparentlymart I knew it was out there somewhere! Thanks.
