### ISSUE TITLE
Null resource count.index not unique in remote-exec

### ISSUE THREAD

**Issue by chrisrlong** [hashicorp/terraform#10463]
Hi there,

### Terraform Version
Terraform v0.8.0-dev (b15b8bd99aae33c5b68cbecf5aef375c0798147c+CHANGES)

### Affected Resource(s)
Please list the resources as a list, for example:
- null_resource
      - remote-exec
          - inline

### Terraform Configuration Files
```hcl
resource "null_resource" "deploy_app" {
  count = "${var.instance_count}"
  triggers {
    current_ec2_instance_id = "${element(aws_instance.mod.*.id, count.index)}"
  }
  provisioner "remote-exec" {
    connection {
      type = "ssh"
      user = "deploy"
      host = "bastion.${var.vpc}.${var.environment}.foo.com"
      timeout = "10s"
      agent = true
    }
    inline = [
      "echo INSTANCE_NUMBER=${count.index + 1}"
    ]
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior
module.marketing_site.null_resource.deploy_app.0 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.1 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.1 (remote-exec): INSTANCE_NUMBER=1
module.marketing_site.null_resource.deploy_app.0 (remote-exec): INSTANCE_NUMBER=0

### Actual Behavior
module.marketing_site.null_resource.deploy_app.0 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.1 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.1 (remote-exec): INSTANCE_NUMBER=1
module.marketing_site.null_resource.deploy_app.0 (remote-exec): INSTANCE_NUMBER=1

OR

module.marketing_site.null_resource.deploy_app.0 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.1 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.0 (remote-exec): INSTANCE_NUMBER=2
module.marketing_site.null_resource.deploy_app.1 (remote-exec): INSTANCE_NUMBER=2
module.marketing_site.null_resource.deploy_app.0: Creation complete
module.marketing_site.null_resource.deploy_app.1: Creation complete

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This is a dev build from master to pre-empt an rc2 release. To test #10338 and #10337.

### References
This seems to work correctly on 0.8.0 beta2, could this have been broken by #10338 ?

**Comment by chrisrlong** [comment]
Same code with Terraform v0.8.0-rc1 (aac47ecf8421da8573155951e36ce5c1aa3fd3a2) got a crash and the wrong index count.

```
module.marketing_site.null_resource.deploy_app.0 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.1 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.0 (remote-exec): INSTANCE_NUMBER=2
module.marketing_site.null_resource.deploy_app.1 (remote-exec): INSTANCE_NUMBER=2
module.marketing_site.null_resource.deploy_app.0: Creation complete
module.marketing_site.null_resource.deploy_app.1: Creation complete
module.marketing_site.null_resource.deploy_app.1 (deposed #0): Destroying...
module.marketing_site.null_resource.deploy_app.0 (deposed #0): Destroying...
module.marketing_site.null_resource.deploy_app.1 (deposed #0): Destruction complete
module.marketing_site.null_resource.deploy_app.0 (deposed #0): Destruction complete
Error applying plan:

2 error(s) occurred:

* bad deposed index: 0, for resource: &terraform.ResourceState{Type:"null_resource", Dependencies:[]string{}, Primary:(*terraform.InstanceState)(0xc0429e4000), Deposed:[]*terraform.InstanceState{}, Provider:"", mu:sync.Mutex{state:0, sema:0x0}}
* bad deposed index: 0, for resource: &terraform.ResourceState{Type:"null_resource", Dependencies:[]string{}, Primary:(*terraform.InstanceState)(0xc042073ea0), Deposed:[]*terraform.InstanceState{}, Provider:"", mu:sync.Mutex{state:0, sema:0x0}}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by apparentlymart** [comment]
This does indeed seem like a bug.

Until it's fixed, the following might work as a workaround:

```hcl
resource "null_resource" "deploy_app" {
  count = "${var.instance_count}"
  triggers {
    current_ec2_instance_id = "${element(aws_instance.mod.*.id, count.index)}"
    instance_number = "${count.index + 1}"
  }
  provisioner "remote-exec" {
    connection {
      type = "ssh"
      user = "deploy"
      host = "bastion.${var.vpc}.${var.environment}.foo.com"
      timeout = "10s"
      agent = true
    }
    inline = [
      "echo INSTANCE_NUMBER=${self.triggers["instance_number"]}"
    ]
  }
  lifecycle {
    create_before_destroy = true
  }
}
```

I expect that `count.index` will work properly when used as a resource attribute, and that this bug is only affecting the association between provisioners and resources. Thus using an additional `triggers` value as an intermediate should -- I hope -- bypass the bug by getting the `count` value evaluated in "resource context".

**Comment by chrisrlong** [comment]
Hi @apparentlymart,

This morning I have tried your suggestion, seems that the resources part does work, but the provisioner still gets feed the wrong value:


module.marketing_site.null_resource.deploy_app.0: Creating...
  triggers.%:                       "" => "2"
  triggers.current_ec2_instance_id: "" => "i-037063e2b64730012"
  **triggers.instance_number:         "" => "1"**
module.marketing_site.null_resource.deploy_app.1: Creating...
  triggers.%:                       "" => "2"
  triggers.current_ec2_instance_id: "" => "i-0985d7e02f4f2b9e0"
  **triggers.instance_number:         "" => "2"**
module.marketing_site.null_resource.deploy_app.1: Provisioning with 'remote-exec'...
module.marketing_site.null_resource.deploy_app.0: Provisioning with 'remote-exec'...
module.marketing_site.null_resource.deploy_app.1 (remote-exec): Connected!
module.marketing_site.null_resource.deploy_app.0 (remote-exec): Connected!
**module.marketing_site.null_resource.deploy_app.1 (remote-exec): INSTANCE_NUMBER=1
module.marketing_site.null_resource.deploy_app.0 (remote-exec): INSTANCE_NUMBER=1**
module.marketing_site.null_resource.deploy_app.0: Creation complete
module.marketing_site.null_resource.deploy_app.1: Creation complete


Chris

**Comment by mitchellh** [comment]
Looking into this now for RC2.

**Comment by mitchellh** [comment]
I did the following config (almost identical) and couldn't get this to reproduce. It outputted the correct numbers. This was with HEAD as of this morning (on master).

```
variable "count" { default = "5" }

resource "null_resource" "deploy_app" {
  count = "${var.count}"

  triggers {
    key = "baz"
  }

  provisioner "remote-exec" {
    connection {
      type = "ssh"
      user = "mitchellh"
      host = "127.0.0.1"
      timeout = "10s"
      password = "<nope>"
    }
    inline = [
      "echo INSTANCE_NUMBER=${count.index + 1}"
    ]
  }


  lifecycle { create_before_destroy = true }
}
```

**Comment by chrisrlong** [comment]
I will pull the code right now and see if it still does it for me...

**Comment by chrisrlong** [comment]
Hi @mitchellh,

Still does the same thing for me (Terraform v0.8.0-dev (08a56304bb594dc289befed6f30f82d79b27ad29)), however could you try your test with count = 2.

I have 2 instances, if I taint one or the other the correct value is passed. If I do both instances on the same apply then it breaks as per my original post an odd/even number thing?

Thanks for looking.

Chris

**Comment by chrisrlong** [comment]
Hi again.

I used your code, but connecting to my aws bastion, 3 of the remote-exec didnt run... 2 did with the wrong count.index value. (Terraform v0.8.0-dev (08a56304bb594dc289befed6f30f82d79b27ad29))

```
Initialized blank state with remote state enabled!
Remote state configured and pulled.
null_resource.deploy_app.3: Refreshing state... (ID: 8908950105768749605)
null_resource.deploy_app.1: Refreshing state... (ID: 6629332378659190866)
null_resource.deploy_app.2: Refreshing state... (ID: 2841609227724349363)
null_resource.deploy_app.4: Refreshing state... (ID: 2579751302050980453)
null_resource.deploy_app.0: Refreshing state... (ID: 7033870292851276668)
null_resource.deploy_app.4: Creating...
  triggers.%:   "" => "1"
  triggers.key: "" => "baz"
null_resource.deploy_app.1: Creating...
  triggers.%:   "" => "1"
  triggers.key: "" => "baz"
null_resource.deploy_app.0: Creating...
  triggers.%:   "" => "1"
  triggers.key: "" => "baz"
null_resource.deploy_app.2: Creating...
  triggers.%:   "" => "1"
  triggers.key: "" => "baz"
null_resource.deploy_app.3: Creating...
  triggers.%:   "" => "1"
  triggers.key: "" => "baz"
null_resource.deploy_app.0: Provisioning with 'remote-exec'...
null_resource.deploy_app.4: Provisioning with 'remote-exec'...
null_resource.deploy_app.1: Provisioning with 'remote-exec'...
null_resource.deploy_app.2: Provisioning with 'remote-exec'...
null_resource.deploy_app.3: Provisioning with 'remote-exec'...
null_resource.deploy_app.0 (remote-exec): Connecting to remote host via SSH...
null_resource.deploy_app.0 (remote-exec):   Host: foo
null_resource.deploy_app.0 (remote-exec):   User: chris
null_resource.deploy_app.0 (remote-exec):   Password: false
null_resource.deploy_app.0 (remote-exec):   Private key: false
null_resource.deploy_app.0 (remote-exec):   SSH Agent: true
null_resource.deploy_app.2 (remote-exec): Connecting to remote host via SSH...
null_resource.deploy_app.2 (remote-exec):   Host: foo
null_resource.deploy_app.2 (remote-exec):   User: chris
null_resource.deploy_app.2 (remote-exec):   Password: false
null_resource.deploy_app.2 (remote-exec):   Private key: false
null_resource.deploy_app.2 (remote-exec):   SSH Agent: true
null_resource.deploy_app.4 (remote-exec): Connecting to remote host via SSH...
null_resource.deploy_app.4 (remote-exec):   Host: foo
null_resource.deploy_app.4 (remote-exec):   User: chris
null_resource.deploy_app.4 (remote-exec):   Password: false
null_resource.deploy_app.4 (remote-exec):   Private key: false
null_resource.deploy_app.4 (remote-exec):   SSH Agent: true
null_resource.deploy_app.3 (remote-exec): Connecting to remote host via SSH...
null_resource.deploy_app.3 (remote-exec):   Host: foo
null_resource.deploy_app.3 (remote-exec):   User: chris
null_resource.deploy_app.3 (remote-exec):   Password: false
null_resource.deploy_app.3 (remote-exec):   Private key: false
null_resource.deploy_app.3 (remote-exec):   SSH Agent: true
null_resource.deploy_app.1 (remote-exec): Connecting to remote host via SSH...
null_resource.deploy_app.1 (remote-exec):   Host: foo
null_resource.deploy_app.1 (remote-exec):   User: chris
null_resource.deploy_app.1 (remote-exec):   Password: false
null_resource.deploy_app.1 (remote-exec):   Private key: false
null_resource.deploy_app.1 (remote-exec):   SSH Agent: true
null_resource.deploy_app.0 (remote-exec): Connected!
null_resource.deploy_app.2 (remote-exec): Connected!
null_resource.deploy_app.3 (remote-exec): Connected!
null_resource.deploy_app.4 (remote-exec): Connected!
null_resource.deploy_app.1 (remote-exec): Connected!
null_resource.deploy_app.0 (remote-exec): INSTANCE_NUMBER=5
null_resource.deploy_app.2 (remote-exec): INSTANCE_NUMBER=5
null_resource.deploy_app.0: Creation complete
null_resource.deploy_app.0 (deposed #0): Destroying...
null_resource.deploy_app.0 (deposed #0): Destruction complete
null_resource.deploy_app.2: Creation complete
null_resource.deploy_app.2 (deposed #0): Destroying...
null_resource.deploy_app.2 (deposed #0): Destruction complete
null_resource.deploy_app.1: Creation complete
null_resource.deploy_app.1 (deposed #0): Destroying...
null_resource.deploy_app.1 (deposed #0): Destruction complete
null_resource.deploy_app.3: Creation complete
null_resource.deploy_app.4: Creation complete
null_resource.deploy_app.3 (deposed #0): Destroying...
null_resource.deploy_app.4 (deposed #0): Destroying...
null_resource.deploy_app.3 (deposed #0): Destruction complete
null_resource.deploy_app.4 (deposed #0): Destruction complete

Apply complete! Resources: 5 added, 0 changed, 5 destroyed.
```

**Comment by chrisrlong** [comment]
Sorry @mitchellh,

I missed a critical piece of information, this seems to only be an issue on the WINDOWS build. Same tests on ubuntu work as expected.

**Comment by mitchellh** [comment]
I won't have access to a Windows machine for a couple days so this will have to miss RC2. :( 

I tried with `count = 2` and various tainting behaviors and couldn't ever reproduce it.

**Comment by mitchellh** [comment]
Found it, PR submitted.
