### ISSUE TITLE
[Feature Request] OpsWorks for Chef Automate Support

### ISSUE THREAD

**Issue by eedwardsdisco** [hashicorp/terraform#10478]
Just announced at re:Invent 2016
https://www.chef.io/opsworks/

OpsWorks now supports Chef Automate (a managed chef server... woo!)

This is a feature request to add support for the new opsworks service to Terraform :)

**Comment by janschumann** [comment]
I started working on this, but too early to create a [WIP] PR.

**Comment by jpooler** [comment]
@janschumann any update on this? I'd be happy to help test as we're starting to look into using Chef Automate.

**Comment by eedwardsdisco** [comment]
@janschumann

Definitely would love any progress from you or any other contributors. Thanks all around!

**Comment by jpooler** [comment]
I mean there is https://github.com/johnbyrneio/chef-automate-terraform but it's likely to be unsupported longer term.

**Comment by eedwardsdisco** [comment]
@jpooler Yeah that's for standing up Chef Automate in AWS. I want to use the managed Chef Automate _Service_ which handles node provisioning, backend storage durability, HA, upgrades, etc all for me.

**Comment by myoung34** [comment]
@janschumann Any updates?

**Comment by janschumann** [comment]
I have not been working on this since December. Had to focus on other things. Sorry for not responding to previous asking!

**Comment by bradfeehan** [comment]
Starting an implementation of this, should have something to demonstrate soon.
