### ISSUE TITLE
graph refactor causes regression in plan

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#1047]
After #1010 with a state built with 0.3.7 some nodes on `terraform plan` are being removed from state and added back in the execution plan, even though the state before plan is fine and matches the actual cloud state.
Reverting our terraform build pre #1010 .

I tried to narrow it down to a minified reproducible case, but no luck yet.

What would be optimal way to trace down the graph plan pre and after #1010 TF builds in order to compare? 
Setting DEBUG display would suffice?

**Comment by catsby** [comment]
Probably related to / fixed by #1046

**Comment by pmoust** [comment]
Indeed #1046 did it. Thanks guys.

**Comment by catsby** [comment]
Great to hear, thank you for reporting the issue!

**Comment by pmoust** [comment]
Hmm, seems we are experiencing this again even after #1046

**Comment by pmoust** [comment]
Mentioned in https://github.com/PeoplePerHour/terraform/pull/11 this is almost the same output as when first opened the ticket after #1010 . Now also an edge node (that is not dependant on the other changes shown in plan) is marked for record change.
And again I fail in creating a small reproducible case. The issue does exist though,and is not present in our current head.

**Comment by mitchellh** [comment]
Let me know if you can get more luck in a repro case. I'll keep thinking about it as well.

**Comment by pmoust** [comment]
TF_LOG @ https://github.com/PeoplePerHour/terraform/pull/11#issuecomment-76452151

**Comment by mitchellh** [comment]
@pmoust Found it, and made a PR to fix here #1086. Note that this will cause your diff to delete two resources. If you look, these resources always existed in the state, but were always ignored. I imagine these are just orphan resources in your infrastructure that you forgot were running since TF never "saw" them, so the diff should be correct. 

Whew, a doozy.
