### ISSUE TITLE
Route 53 record normalize should lowercase the DNS name

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#10484]
We have the following Route 53 DNS record created with Terraform:

```
resource "aws_route53_record" "test" {
  zone_id = "${aws_route53_zone.test.zone_id}"
  name    = "www"
  type    = "A"

  alias {
    name                   = "${aws_elb.test.dns_name}"
    zone_id                = "${var.aws_elb_route53_hosted_zone_ids[var.region]}"
    evaluate_target_health = true
  }
}
```

The `aws_elb.test` resource contains a combination of uppercase and lowercase characters and, as a result, Terraform always wants to apply changes. It seems that the normalization for Route 53 DNS records should lowercase the values before comparing them to those returned from the AWS API.

**Comment by joshuaspence** [comment]
This issue has also been mentioned on #10007, #9289 and #10004.

**Comment by mitchellh** [comment]
Closing since this looks like a multi-dup! Thanks!
