### ISSUE TITLE
aws_db_parameter_group - apply_method - (Optional) Bug

### ISSUE THREAD

**Issue by ChrisFernandez** [hashicorp/terraform#10480]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
https://releases.hashicorp.com/terraform/0.7.10/terraform_0.7.10_linux_amd64.zip

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_rds
- rds parameter config

### Terraform Configuration Files
```hcl

```
resource "aws_db_parameter_group" "europa_parameter_group" {
  name = "rds-europa-parameter"
  family = "postgres9.4"

  parameter {
    name = "max_standby_archive_delay"
    value = "600000000"
  }

  parameter {
    name = "max_standby_streaming_delay"
    value = "600000000"
  }
}
```



### Debug Output

Parameter GroupDatabase parameter group to associate with this DB instance.	
rds-europa-parameter ( pending-reboot )

### Expected Behavior

Terraform should have had rds slave(read only rds) reboot instead of waiting for me to rebooted manually... 

### Actual Behavior
RDS is waiting for me to manually reboot to commit the parameter changes

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

Terraform documentation says that the default is to do the changes at the moment..

> apply_method - (Optional) "immediate" (default), or "pending-reboot". Some engines can't apply some parameters without a reboot, and you will need to specify "pending-reboot" here

![captura de pantalla de 2016-12-01 13-56-46](https://cloud.githubusercontent.com/assets/5316229/20814341/1155978e-b7ce-11e6-9dbd-b2f0eb31544b.png)

**Comment by stack72** [comment]
Hi @ChrisFernandez 

Thanks for opening the issue here - Terraform itself only interacts with the AWS API. We cannot actually create a resource to reboot directly - we would defer that to the AWS API. 

The SDK that we use has this in it's documentation

```
        // Valid Values (for the application method): immediate | pending-reboot
	//
	// You can use the immediate value with dynamic parameters only. You can use
	// the pending-reboot value for both dynamic and static parameters, and changes
	// are applied when you reboot the DB instance without failover.
```

For us to change terraform to reboot resources could have dramatic effects for our users who are unaware of this. I don't think this is the way we would go

Hopefully this makes a little more sense?

Thanks

Paul
