### ISSUE TITLE
Docs: Provide some clarity with "terraform state mv" usage and remote states.

### ISSUE THREAD

**Issue by dotspec** [hashicorp/terraform#10481]
Hi there,

I started refactoring a bunch of terraform configs a couple days ago and found this to be a gigantic hole in [the documentation](https://www.terraform.io/docs/commands/state/mv.html) for the command.  I don't know if my situation was too special snowflake-y to be of use to others but thought I'd open an issue in case.

My specific case revolved around breaking up a single monolithic remote state into per-environment states.  In order to make this work I needed to use the -state-out flag to target the new state but...wait what's this?  

> Path to the state file. Defaults to "terraform.tfstate". Ignored when remote state is used.

Then what's the proper thing to do here?  I finally settled on disabling remote states for both files, performing the moves and then re-enabling and while it works it sure feels kludgy.  

Even something as simple as including another usage example in the docs for moving between two states that aren't local would have been super helpful and saved me some pain.  Or if remote states don't work with 'state mv' calling that out would be great.  

Hopefully this stuff isn't too specific for general docs, and also that I just didn't miss some really basic usage and shamed myself by opening an issue.

**Comment by Gary-Armstrong** [comment]
@dotspec It's not just you.  I came here for the same clarification.  Would like to avoid de-remote-ing my state files for this operation.

**Comment by bdashrad** [comment]
When I did this previously, i had to disable remote state for both files. I was hoping that woudn't be the case anymore.

**Comment by gopisaba** [comment]
+1

**Comment by urtens** [comment]
+1

**Comment by aterreno** [comment]
+1

**Comment by lcostea** [comment]
+1

**Comment by fredsig** [comment]
+1

**Comment by heythisisnate** [comment]
+1

**Comment by liozN** [comment]
+1

**Comment by kforsthoevel** [comment]
+1

**Comment by Wambosa** [comment]
+1

**Comment by mathematician** [comment]
+1

**Comment by Gary-Armstrong** [comment]
Do I still have to de-remote my state files to mv resources between them?

**Comment by nbering** [comment]
@Gary-Armstrong I'm on v0.9.11 and can confirm that `terraform state mv` worked fine with the state in the s3 remote backend.

**Comment by Gary-Armstrong** [comment]
@nbering Thanks for the info. Did you mv from one state to another, or did you mv within a single state (rename)?

**Comment by nbering** [comment]
@Gary-Armstrong Within a single state. I was just moving resources out of a submodule and into the root module.

**Comment by Gary-Armstrong** [comment]
Ah, I was really hoping someone had risked life and state to find a way to do this. :)
Until then, I am going to de-remote both states and use the documented local state commands.

**Comment by jbardin** [comment]
Hi Everyone,

This does need to be cleared up in the documentation. As it stands now, the state commands could only infer a remote state which must be configured for `init`, and specify local files with via flags because we don't have an addressing scheme to be able to specify multiple remote states in general. 

If you want to work within a single state, the state commands should work with remote state (note that there may be a bug preventing this in the current 0.10rc). If you want to work with multiple states, you need to pull the states locally for the operations, and as always, it doesn't hurt to have extra backups. 

We'll get the behavior finalized in an upcoming release, and update the documentation.
