### ISSUE TITLE
Error applying plan with aws_appautoscaling_policy : does not have attribute 'arn'

### ISSUE THREAD

**Issue by yesteph** [hashicorp/terraform#10486]
Hello,

With terraform 0.7.13, we declared an aws_appautoscaling_policy :
_resource "aws_appautoscaling_policy" "scale_in" {
  name = "${aws_ecs_service.mlk_worker_sqs_to_post.name}-scale-in"
  service_namespace = "ecs"
  resource_id = "service/${var.cluster_name}/${aws_ecs_service.mlk_worker_sqs_to_post.name}"
  scalable_dimension = "ecs:service:DesiredCount"

  adjustment_type = "ChangeInCapacity"
  cooldown = 60
  metric_aggregation_type = "Average"

  step_adjustment {
    metric_interval_upper_bound = 0
    scaling_adjustment = -2
  }

  depends_on = ["aws_appautoscaling_target.scale_tgt"]
}_

Sometimes, we got the following error : 

_Error applying plan:

1 error(s) occurred:

* Resource 'aws_appautoscaling_policy.scale_in' does not have attribute 'arn' for variable 'aws_appautoscaling_policy.scale_in.arn'__

Strangely, the policy is correctly created.
A second terraform apply is ok.

**Comment by hrzbrg** [comment]
Running into the same issue with 0.7.13 when I want to loop over several services to enable autoscaling. If I run it with just one service it works fine.
