### ISSUE TITLE
count parameter does not accept `${length(ARRAY)}`

### ISSUE THREAD

**Issue by flypenguin** [hashicorp/terraform#10488]
### Terraform Version
0.7.13

### Affected Resource(s)
Every resource which accepts has `count` parameters. Might be a core issue.

### Terraform Configuration Files
https://www.dropbox.com/s/kzd97ykhjty67df/2016-12-02-terraform-issue_count_length.zip?dl=0 (DEBUG log included)

The crucial part is here:
```hcl
# in the main file

module "test" {
  source           = "./test_module"
  name             = "apptest"
  ami              = "ami-1c1bdc73"                       # eu-central-1 image
  attached_volumes = ["${data.aws_ebs_volume.volume.id}"]
}


# in the module

variable "attached_volumes" {
  type    = "list"
  default = []
}

# ...

resource "aws_volume_attachment" "vol" {
  # this does *NOT* work:
  count       = "${length(var.attached_volumes)}"
  # this does:
  #count = "1"

  device_name = "${element(var.never_touch_one, count.index)}"
  volume_id   = "${element(var.attached_volumes, count.index)}"
  instance_id = "${aws_instance.host.id}"
}
```

### Expected Behavior
1. with `attached_volumes` given: It should create one volume attachment with the example.
1. without `attached_volumes` given: It should create the host without any volumes attached.

### Actual Behavior
1. `* strconv.ParseInt: parsing "${length(var.attached_volumes)}": invalid syntax`
1. it behaves as expected (host is created without volumes attached)

### Steps to Reproduce
1. unzip example
2. `cd step1 ; terraform apply`
3. `cd ../step2 ; terraform get ; terraform plan`
(adjust examples according to comments as required)

**Comment by mitchellh** [comment]
This is "fixed" via a nicer error message in 0.8. The original issue towards ultimately supporting this: #3888

**Comment by flypenguin** [comment]
any timeline on 0.8? :)

**Comment by mitchellh** [comment]
Its a really really complicated issue and we laid a lot of important groundwork in 0.8 but it won't make it.

**Comment by flypenguin** [comment]
sh... . any idea when this is fixed? the alternative kinda sucks. (rough guess would be helpful)

**Comment by mitchellh** [comment]
No, but hopefully 0.9. Not a commitment though.

**Comment by flypenguin** [comment]
mh. thanks.
