### ISSUE TITLE
Add functionality to manipulate ebs_snapshots

### ISSUE THREAD

**Issue by djandruczyk** [hashicorp/terraform#10496]
### Terraform Version
0.7.11

### Affected Resource(s)
Please list the resources as a list, for example:
AWS provider

Add support for manipulating EBS snapshots, as it doesn't appear to be possible to enumerate the snapshot ID's based on filters/tags and then to be able to create and EBS_Volume from them.  Currently it requirs manually storing the snapshot ID in the terraform config and that's not nice.

**Comment by stack72** [comment]
Hi @djandruczyk 

Thanks for opening the issue here - luckily, we have already got this work taken care of in https://github.com/hashicorp/terraform/issues/10017

This will be part of the 0.8 release :)

Paul
