### ISSUE TITLE
Environment variables are not removed from AWS lambda functions

### ISSUE THREAD

**Issue by gurdulu** [hashicorp/terraform#10491]
Hi there,

deleting the section for setting environment variables the related variables on AWS Lambda are not removed.

Terraform version: 0.7.13

For replicating the issue create a first lambda function using environment variables

```
resource "aws_lambda_function" "test_1" {
    filename = "file.zip"
    function_name = "test_1"
    role = "${aws_iam_role.lambdas_role.arn}"
    handler = "test_1.handler"
    source_code_hash = "${base64sha256(file("file.zip"))}"
    environment {
       variables {
          test = 1
       }
}
```

generate the lambda function with `terraform --apply`, then change the script for removing the environment variables

```
resource "aws_lambda_function" "test_1" {
    filename = "file.zip"
    function_name = "test_1"
    role = "${aws_iam_role.lambdas_role.arn}"
    handler = "test_1.handler"
    source_code_hash = "${base64sha256(file("file.zip"))}"
}
```

run again `terraform --apply`, the variable is not deleted.

<img width="795" alt="screen shot 2016-12-02 at 09 34 59" src="https://cloud.githubusercontent.com/assets/4972226/20834742/bd666772-b88e-11e6-838f-de352d4d7f64.png">

**Comment by Ninir** [comment]
Hi @gurdulu ,
Sorry for the annoyance here. I just pushed a patch for this, which will be added to the next releases I guess.
