### ISSUE TITLE
Documentation problem for aws_api_gateway_domain_name

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#10493]
The documentation for `aws_api_gateway_domain_name` (the `aws_route53_record.example` resource) at https://www.terraform.io/docs/providers/aws/r/api_gateway_domain_name.html is missing the `evaluate_target_health` argument:

```
  * aws_route53_record.myapi: "alias.0.evaluate_target_health": required field is not set
```

No biggie, but for completeness, any example should 'work' as shown.

**Comment by stack72** [comment]
Closed via https://github.com/hashicorp/terraform/pull/10506

Thanks for pointing out the docs issue! Fixed in the PR above
