### ISSUE TITLE
support RDS encryption at rest

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#1050]
https://aws.amazon.com/about-aws/whats-new/2015/01/06/amazon-rds-encryption-with-kms-mysql-postgresql/

**Comment by catsby** [comment]
Looks like we'd need to add support for `StorageEncrypted` and `KmsKeyId` into [resource_aws_db_instance.go][1]

@ryanking is this something you want to take a stab at? If not, I can try and get to it in the near future, but I can't make promises as to when. I agree that it's a thing we should support :smile: 

[1]: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_instance.go

**Comment by josh-padnick** [comment]
+1 for this feature.  It's especially important because RDS will only let you set this option at RDS Launch Time.  You can't modify an existing RDS instance to support this.

**Comment by phinze** [comment]
Done in #1041 :+1:
