### ISSUE TITLE
AWS SQS FIFO Support

### ISSUE THREAD

**Issue by agarstang** [hashicorp/terraform#10503]
Hi,

There currently appears to be no support for FIFO queues on the `aws_sqs_queue` resource and no current feature raised for this (this SQS feature was only released a short while ago).

The `aws_sqs_queue` resource will require the ability to create FIFO queues and set the additional parameters required.

### Terraform Version
0.7.13

### Affected Resource(s)
- aws_sqs_queue

**Comment by Ninir** [comment]
Will get my eyes on this if noone wants to :)

**Comment by Ninir** [comment]
Started the work in https://github.com/hashicorp/terraform/pull/10614 ! hope it will fit :)
