### ISSUE TITLE
Behaviour of instance state with schema.TypeSet

### ISSUE THREAD

**Issue by tintoy** [hashicorp/terraform#10520]
Hi.

I've written a couple of providers for Terraform, and there's still one thing I don't understand about the behaviour of `schema.TypeSet`. The hash function produces a value used as the "index" for each item:

```
"set_item.#": "2",
"set_item.3452886897.prop1": "CCC",
"set_item.3452886897.prop2": "DDD",
"set_item.3452886897.prop3": "Foo",
"set_item.3605873202.prop1": "AAA",
"set_item.3605873202.prop2": "BBB",
"set_item.3605873202.prop3": "Foo"
```

So the hash uniquely identifies each element in the set - it's like a key. But the behaviour of the set seems to treat the set elements as simple values (rather than composite ones) even if the data-type if the set elements is a `schema.Resource`. This makes it very difficult to model some types of data in Terraform. For example, disks in a server have a LUN (logical unit Id) which uniquely identifies them. I'd expect to be able to use the LUN as a key to identify items in the set (and ensure their uniqueness). But the way it's all been implemented, sets don't work unless the hash is derived from _all_ properties of the element. And this means that if anything about the element changes, Terraform treats it as a completely different element. This wouldn't be so bad if it wasn't for the fact that this appears to be how Terraform matches up state for elements in the set. Change a property, and the `set_item.3605873202` prefix becomes something else entirely. So how can you calculate or display a useful diff from that?

I'm just wondering if this limitation is by design, or merely incidental. I'm also open to the idea that I've just plain wrong about how this is meant to work :)

### Terraform Version

Terraform v0.7.12

### Affected Resource(s)

Any resource with a schema.TypeSet property.

### Repro

main.go
```go
package main

import (
	"fmt"
	
	"github.com/hashicorp/terraform/helper/schema"
	"github.com/hashicorp/terraform/plugin"
	"github.com/hashicorp/terraform/terraform"
)

// The main program entry-point.
func main() {
	plugin.Serve(&plugin.ServeOpts{
		ProviderFunc: func() terraform.ResourceProvider {
			return &schema.Provider{
				Schema: map[string]*schema.Schema{},
				ResourcesMap: map[string]*schema.Resource{
					"playground_example": &schema.Resource{
						Schema: map[string]*schema.Schema{
							"name": &schema.Schema{
								Type:     schema.TypeString,
								Required: true,
							},
							"list_item": &schema.Schema{
								Type:     schema.TypeList,
								Optional: true,
								Elem: &schema.Resource{
									Schema: map[string]*schema.Schema{
										"prop1": &schema.Schema{
											Type:     schema.TypeString,
											Required: true,
										},
										"prop2": &schema.Schema{
											Type:     schema.TypeString,
											Required: true,
										},
										"prop3": &schema.Schema{
											Type:     schema.TypeString,
											Required: true,
										},
									},
								},
							},
							"set_item": &schema.Schema{
								Type:     schema.TypeSet,
								Optional: true,
								Elem: &schema.Resource{
									Schema: map[string]*schema.Schema{
										"prop1": &schema.Schema{
											Type:     schema.TypeString,
											Required: true,
										},
										"prop2": &schema.Schema{
											Type:     schema.TypeString,
											Required: true,
										},
										"prop3": &schema.Schema{
											Type:     schema.TypeString,
											Required: true,
										},
									},
								},
								Set: func(value interface{}) int {
									item := value.(map[string]interface{})

									return schema.HashString(fmt.Sprintf(
										"%s|%s", item["prop1"], item["prop2"],
									))
								},
							},
						},
						Create: func(data *schema.ResourceData, provider interface{}) error {
							name := data.Get("name").(string)
							data.SetId(name)

							return nil
						},
						Read: func(data *schema.ResourceData, provider interface{}) error {
							return nil
						},
						Update: func(data *schema.ResourceData, provider interface{}) error {
							return nil
						},
						Delete: func(data *schema.ResourceData, provider interface{}) error {
							return nil
						},
					},
				},
				ConfigureFunc: func(providerSettings *schema.ResourceData) (provider interface{}, err error) {
					return
				},
			}
		},
	})
}
```

main.tf
```hcl
resource "playground_example" "example1" {
    name = "Example 1"
    
    list_item {
        prop1 = "AAA"
        prop2 = "BBB"
        prop3 = "Foo"
    }
    
    list_item {
        prop1 = "CCC"
        prop2 = "DDD"
        prop3 = "Foo"
    }

    set_item {
        prop1 = "AAA"
        prop2 = "BBB"
        prop3 = "Foo"
    }
    
    set_item {
        prop1 = "CCC"
        prop2 = "DDD"
        prop3 = "Foo"
    }   
}
```

### Expected Behavior
If I change `prop3` on `list_item` and `set_item` blocks from "Foo" to "Bar", I expect it to show up as a change. After all, although the hash value has not changed, this particular property _has_ changed. I would expect the hash to represent that element's identity, and I would not expect the element identity to have to represent the entire entity's state.

### Actual Behavior
Although a change is detected for both `list_item` blocks, no change is detected for the `set_item` blocks (because the hash has not changed).
If I alter the hash function, however, to also include `prop3`, then a change is detected, but not a useful one. Instead, it shows a diff that indicates the original set item now has empty values, while there is a new set item with original values. In other words, the state data is never restored for the original element in the set returned by `data.Get("set_item")`.

### Steps to Reproduce

1. `terraform apply`
2. Update `main.tf` to change each `prop3` from "Foo" to "Bar".
3. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @tintoy. Sorry for the weirdness here...

The model for sets in Terraform is that, as you noted, their entire contents act as the "identity" in the set, and changing any of the values is supposed to cause Terraform to see it as an item being removed and another one being added. It's actually no longer suggested to use an explicit `Set` function since there's a default implementation that "does the right thing" of hashing the entire nested data structure; the ability to override it is mostly a vestige of an earlier time when this default wasn't present, to preserve compatibility with some older resources.

You can actually see a slightly-younger version of me asking a similar question in #2336, with a detailed response from Mitchell about the rationale for this behavior.

So this modelling is as intended, but you're right that it has some rather unfortunate consequences for the rendering of diffs for set members. This was discussed a bit in an earlier issue #5179.

**Comment by tintoy** [comment]
Thanks! That's a great write-up, and I really appreciate you taking the time to do so.

If that's the design then so be it, I can bend my design to fit :)
