### ISSUE TITLE
Terraform Count not supported while creating multiple rules within escalation policy

### ISSUE THREAD

**Issue by shukla2112** [hashicorp/terraform#10525]
While creating the escalation policy with multiple rules using [terraform count](https://www.terraform.io/intro/examples/count.html), it is not considered. Below is the code -
```
resource "pagerduty_escalation_policy" "policy" {
  name        = "${var.policy_name}"
  description = "${var.policy_description}"
  num_loops   = "${var.policy_loops}"

  rule {
    escalation_delay_in_minutes = "${var.rule_delay}"
    count = "${var.number_of_escalation}"
    target {
      type = "${element(var.rule_types, count.index)}"
      id   = "${element(var.rule_ids, count.index)}"
    }
  }
}
```
Error is - 
```
Errors:

  * pagerduty_escalation_policy.policy: rule.0: invalid or unknown key: count
```
Suspecting the `rule` is not resource and may be that is the cause as count is only applicable to the resource.

**Comment by mitchellh** [comment]
The `rule` is a configuration, `count` is only allowed on the resource itself (which is the `pagerduty_escalation_policy`). 

We have plans to support counts in more places but this currently doesn't work.
