### ISSUE TITLE
Map/Module/Target Bug? 0.7.x

### ISSUE THREAD

**Issue by robrankin** [hashicorp/terraform#10527]
I seem to be having a problem passing a map into a module, and then retrieving it as an output.

Specifically the output of 2 `apply` runs is different if the `-target` option is provided.

In the test case code below the module `test` is the only module/code other than the root module, so the `apply -target=module.test` should be equivalent to a simple `apply`

I've tried with a number of 0.7.x versions and this seems to be present in all of them.

### Terraform Version
`Terraform v0.7.14-dev (b939e5f8d4a6d957f0ab49e83b9681e92a627f78)`

### Affected Resource(s)
Modules?  Apply?  Not sure.

#### Root Module
```hcl
variable "testCodes" {
  type = "map"
  default = {
    "0" = "one",
    "1" = "two"
  }
}

module "test" {
  source    = "test/"
  testCodes = "${var.testCodes}"
}

output "module_testCodes" {
  value = "${module.test.testCodes}"
}
output "local_testCodes" {
  value = "${var.testCodes}"
}
```

#### Test Module (test/module.tf)
```
variable "testCodes" {
  type = "map"
}

output "testCodes" {
  value = "${var.testCodes}"
}
```

### Debug Output
https://gist.github.com/robrankin/7d125dd0b1fa94db8025ca147d396a36

### Expected Behavior
```
[user@terraform test]$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

local_testCodes = {
  0 = one
  1 = two
}
module_testCodes = {
  0 = one
  1 = two
}
```

### Actual Behavior
```
[user@terraform test]$ terraform apply -target=module.test

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

local_testCodes = {
  0 = one
  1 = two
}

Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

You can report an issue at: https://github.com/hashicorp/terraform/issues

The failure was written to "terraform-error-1480921882.log". Please
double check this file contains no sensitive information and report
it with your issue.

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply -target=module.test`

The two outputs are different, with the `-target` output missing the map that was passed into and out of the module, and produces the experimental feature error output.

### Important Factoids
With a more complex test case it appears the value of the `testCodes` map never makes it into the module, as a `key()` function applied in the module errors with a syntax related issue.

**Comment by jbardin** [comment]
Hi @robrankin, 

Thanks for filing the issue. This is fixed in the upcoming 0.8 release!
