### ISSUE TITLE
File provisioner fails when content uses wrong interpolation syntax 

### ISSUE THREAD

**Issue by oherrala** [hashicorp/terraform#10531]
### Terraform Configuration Files
```hcl
  provisioner "file" { 
    connection {
      user = "core"
    }
    content = "${invalidsomething}"
    destination = "/home/core/dontcare"
  }
```

The above configuration fails. It looks like `${invalidsomething}` does something funny in content. `terraform apply` exists with this message:

```
digitalocean_droplet.special-pet: Still creating... (40s elapsed)
digitalocean_droplet.special-pet: Provisioning with 'file'...
Error applying plan:

1 error(s) occurred:

* stat : no such file or directory
```

I assume there should be file name between `stat` and `:` in error message so it seems that Terraform tries to stat file without providing a file name.

Snippet for debug output:

```
2016/12/05 16:17:43 [DEBUG] root: eval: *terraform.EvalIf
2016/12/05 16:17:43 [DEBUG] root: eval: *terraform.EvalWriteState
2016/12/05 16:17:43 [DEBUG] root: eval: *terraform.EvalWriteDiff
2016/12/05 16:17:43 [DEBUG] root: eval: *terraform.EvalApplyPost
2016/12/05 16:17:43 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* stat : no such file or directory
2016/12/05 16:17:43 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* stat : no such file or directory
2016/12/05 16:17:43 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* stat : no such file or directory
2016/12/05 16:17:43 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* stat : no such file or directory
```

### Expected Behavior
If content is invalid, Terraform should say so without trying to do file operations. Now it tries to do something and fails with really hard to understand error message.

### Actual Behavior
I assume Terraform tries to do `stat` syscall without providing correct file name.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Add above configuration snippet to Terraform configuration
1. `terraform apply`

### Important Factoids
This is tested using CoreOS running on DigitalOcean.

**Comment by mitchellh** [comment]
This is fixedin TF 0.8 (in RC now)

**Comment by w32-blaster** [comment]
I have the same issue uploading a directory. Tested with 0.8.0-rc2 and did not help. Any idea how to debug? I see exactly the same error message.
