### ISSUE TITLE
EBS attachment with count + interpolated attributes being destroyed when count is increased

### ISSUE THREAD

**Issue by edsonmarquezani** [hashicorp/terraform#10542]
Terraform will destroy all EBS attachments and recreate them, when declaring it with `count`
 attribute and interpolated values, and raising count value.

Consider the following setup (this is a tested real scenario).

```hcl
provider "aws" {
  region = "us-east-1"
}

variable "instance-count" {
  default = "1"
}

resource "aws_instance" "instances" {
  count = "${var.instance-count}"

  ami = "ami-b73b63a0"
  instance_type = "t2.nano"
  key_name = "production_new"
  subnet_id = "subnet-4c52f661"
  vpc_security_group_ids = [ "sg-5e11d623" ]
  disable_api_termination = "false"

  root_block_device {
    volume_type = "gp2"
    volume_size = "10"
    delete_on_termination = true
  }

  tags {
    "Name" = "instance-${count.index}"
  }
}

resource "aws_ebs_volume" "volumes" {
  count = "${var.instance-count}"
  availability_zone = "us-east-1a"
  type = "gp2"
  size = "1"
}

resource "aws_volume_attachment" "volumes-attachment" {
  count = "${var.instance-count}"
  device_name = "/dev/sdb"
  volume_id = "${element(aws_ebs_volume.volumes.*.id, count.index)}"
  instance_id = "${element(aws_instance.instances.*.id, count.index)}"
}
```

It creates 1 EC2 instance, 1 EBS and attaches it.

Then, if I raise `instance-count` to, for example, `2`, I get the following plan. (I will omit the parts not related to the issue).

```
-/+ aws_volume_attachment.volumes-attachment.0
    device_name:  "/dev/sdb" => "/dev/sdb"
    force_detach: "" => "<computed>"
    instance_id:  "i-c1fc31d6" => "<computed>" (forces new resource)
    skip_destroy: "" => "<computed>"
    volume_id:    "vol-2e8823bd" => "<computed>" (forces new resource)

+ aws_volume_attachment.volumes-attachment.1
    device_name:  "/dev/sdb"
    force_detach: "<computed>"
    instance_id:  "<computed>"
    skip_destroy: "<computed>"
    volume_id:    "<computed>"
```

Notice that Terraform will **detach the disk from the first instance and reattach it**, even though there wasn't any changes to those resources. I can confirm that it actually detaches the disk and attaches it again, from the AWS Console. It should only add the additional resources and nothing else, right?

PS: There's a similar issue with `aws_alb_target_group_attachment`, reported on  https://github.com/hashicorp/terraform/issues/8684.

**Comment by edsonmarquezani** [comment]
It seems to be related to this core bug https://github.com/hashicorp/terraform/issues/3449. Should my issue be closed?

**Comment by mitchellh** [comment]
This goes back to #3449 as you've found. Yep :)
