### ISSUE TITLE
Allow multiple policies to be attached to an s3 bucket

### ISSUE THREAD

**Issue by evanstachowiak** [hashicorp/terraform#10543]
Hi there,
### Terraform Version
0.7.13

### Affected Resource(s)
- aws_s3_bucket_policy

### Expected Behavior
Instead of using a different bucket for different logs, I'm trying to use one bucket with different prefixes. The issue with this is that I cannot use more than one aws_s3_bucket_policy. If I specify this resource multiple times, the previous gets overwritten and only the last one is used. Ideally, there would be something like aws_iam_policy_attachment resource.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Try to use multiple s3 policies on a bucket.

**Comment by akerl** [comment]
AWS only supports a single bucket policy on a bucket. You can combine multiple Statements into a single policy, but not attach multiple policies.

**Comment by jemmyw** [comment]
I've also run across this problem. The issue is that I can't assemble a policy from resources in different modules unless I output all those policies. It's be nice to have a resource like "aws_s3_bucket_policy_statement"

**Comment by rajiv2205** [comment]
Can anybody suggest workaround for this? I have multiple environments (some are already existing and some I create with terraform). My requirement is that the bucket should be accessible to old infra and new one's. When I tier down new terraform infra.. the policy will get updated automatically and remove the ips of recently removed infra. However, the old infra ips should be there.

**Comment by hwscell** [comment]
+1 @rajiv2205  I have exactly the same problem.

**Comment by rajiv2205** [comment]
@hwscell I changed my approach to aws roles. Now, the instances that have the role attached on it can access s3 bucket. The IAM role has permissions to access the bucket. Hope this will help.
