### ISSUE TITLE
Changing remote-exec doesn't trigger a change.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#1054]
Changing `remote-exec` doesn't trigger a change to an `aws_instance` resource. I would expect when changing remote-exec, a new instance to be created and the old one removed. I would also expect that a change to the script would trigger a change to the instance as well.

Changing this:
```
resource "aws_instance" "web" {
  instance_type = "m1.small"
  ami = "${lookup(var.aws_amis, var.aws_region)}"

}
```

To this:
```
resource "aws_instance" "web" {
  instance_type = "m1.small"
  ami = "${lookup(var.aws_amis, var.aws_region)}"

  connection {
    user = "ec2-user"
    key_file = "${var.aws_key_path}"
  }

  provisioner "remote-exec" {
    scripts = [
      "${path.module}/scripts/install.sh",
    ]
  }

}
```

I expected the instance to be cycled out and a new one created.

**Comment by mitchellh** [comment]
This is working as intended. Provisioners (as documented, in case that was a concern) are meant for _bootstrapping_ a node. Changes to provisioners shouldn't affect nodes that are already bootstrapped. We did this on purpose to avoid people using Terraform as a jank config management tool. 

There is another issue (recently!) that is requesting a way to force a node to be destroyed/recreated. I think that is the better way to do this feature.

**Comment by clstokes** [comment]
+1 to that other issue then, I can't find it.
