### ISSUE TITLE
Get aws_emr_cluster endpoint

### ISSUE THREAD

**Issue by vkulov** [hashicorp/terraform#10551]
Hi,

I have successfully installed provisioned an EMR cluster using the aws_emr_cluster tag.

I'm having troubles accessing the EMR cluster endpoint or public DNS so I can use my cluster. I don't see an exported variable that points to any private or public address of my EMR cluster.

Please help. How do I use cluster if I don't have its IP or endpoint.

**Comment by Ninir** [comment]
Hi @vkulov 
Can you try using the `master_public_dns` attribute and tell us how it goes?

I think this is the thing you are looking for :)

**Comment by Ninir** [comment]
It is live in https://github.com/hashicorp/terraform/pull/10563 !

**Comment by vkulov** [comment]
Thank you. This is what I was looking for. :)

**Comment by dhaneshcode** [comment]
any chance can we get the hostname of the master.
