### ISSUE TITLE
experimental feature failure: plan operation: Real and shadow states do not match

### ISSUE THREAD

**Issue by rbuels** [hashicorp/terraform#10556]
### Terraform Version
0.7.13

### Affected Resource(s)
experimental feature failure dump:

 plan operation: Real and shadow states do not match!

### Debug Output

see attached gpg-encrypted failure dump
[terraform-error-1481046187.log.crypt.zip](https://github.com/hashicorp/terraform/files/634593/terraform-error-1481046187.log.crypt.zip)

**Comment by paulfgps** [comment]
Got the same error.


1 error(s) occurred:

* plan operation: Real and shadow diffs do not match! Real diff:

UPDATE: aws_route53_record.ftp
  records.#:          "2" => "1"
  records.1865467469: "ccensoredip" => ""
  records.3258862375: "ccensoredip" => "ccensoredip"

module.ftp_instance:
module.network:
module.setup:

Shadow diff:

UPDATE: aws_route53_record.ftp
  records.#:          "2" => "1"
  records.1865467469: "ccensoredip" => ""
  records.3258862375: "ccensoredip" => "ccensoredip"

module.ftp_instance:

**Comment by mitchellh** [comment]
Thanks, this is a dup of #10222 we're still trying to track it down.
