### ISSUE TITLE
Ability to create daily ami from running instance

### ISSUE THREAD

**Issue by michael-henderson** [hashicorp/terraform#10555]
I am trying to set up somewhat of a deploy process where I have one running instance that is keeping itself up to date, and I have terraform run aws_ami_from_instance daily, update my live ASG with the newly created ami ID, and have the ASG rotate in the new AMI.  Right now when I run aws_ami_from_instance more than once, terraform sees that an AMI was already created before and does nothing, rather than creating another AMI.  Is there a way to force the creation of a new AMI each time aws_ami_from_instance runs?  I was thinking a flag to set, something like "force_new = true" or something.

**Comment by mitchellh** [comment]
If you have a script, use `terraform taint` prior to the run perhaps? I think having a lifecycle flag to detach Terraform from management is not a bad idea either, but we already have a enhancement requset for something similar, so going to close! 

Taint should probably get you going though. Or pair that with `terraform state rm`

**Comment by michael-henderson** [comment]
Thanks for the hint :)  I tried using terraform taint, that results in the creation of a new ami, but destroys the previous one.  terraform state rm works, creates a new ami every run, and leaves the old, but you lose control of the old, so you might as well use the aws cli at that point.  :/
