### ISSUE TITLE
Cannot authenticate to Azure

### ISSUE THREAD

**Issue by 030** [hashicorp/terraform#10550]
I have followed [these instructions](https://www.terraform.io/docs/providers/azurerm/index.html), to authenticate to Azure, configured the following:

```
provider "azurerm" {
  subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
}

resource "azurerm_resource_group" "example" {
  name = "exampleGroup"
  location = "westus"
}
```

but it results in:

```
Error refreshing state: 1 error(s) occurred:

* Credentials for accessing the Azure Resource Manager API are likely to be incorrect, or
  the service principal does not have permission to use the Azure Service Management
  API.
```

when terraform plan or terraform apply is issued.

**Terraform version**

Terraform v0.7.13

**OS**

Centos 7

http://serverfault.com/questions/818406/how-to-connect-to-azure-using-terraform

Authentication was successful when a subscription file was used. However the actions were executed on the Classic portal instead of the new one. The following snippet created a network in the Classic Portal.

```
provider "azure" {
  publish_settings = "${file("file.publishsettings")}"
}

resource "azure_virtual_network" "default" {
  name = "vNet01"
  address_space = ["10.0.0.1/24"]
  location = "North Europe"
  subnet {
  name = "Subnet1"
  address_prefix = "10.0.0.1/25"
 }
}  
```

**Comment by 030** [comment]
@mitchellh Could you indicate how I could help to solve this issue?

**Comment by TStraub-rms** [comment]
@030 there are two Azure providers that can be used to represent the old and new azure resource manage. Namely, `azure` and `azurerm`.

It is recommended to use `azurerm` exclusively and that will create resources in the new Azure portal.

**Comment by jontreynes** [comment]
I am having this same issue... What are we doing wrong? I have already ran through the instructions found here: https://blogs.msdn.microsoft.com/eugene/2016/11/03/creating-azure-resources-with-terraform/

**Comment by tombuildsstuff** [comment]
Hey @030 @jontreynes 

The [AzureRM Provider guide referenced above has been rewritten](https://www.terraform.io/docs/providers/azurerm/index.html) and now provides some checks to verify the credentials have been created successfully.

If this is still an issue, would you mind taking another look at [the AzureRM Provider guide](https://www.terraform.io/docs/providers/azurerm/index.html#creating-credentials) and seeing if creating credentials through the new Azure CLI solves your issue? In particular the confirmation step (i.e. where we login as the generated service principle and list the VM sizes) ensures these credentials are configured correctly :)

Thanks!

**Comment by 030** [comment]
@tombuildsstuff I am able to authenticate now:

```
azurerm_resource_group.test: Creating...
  location: "" => "westus"
  name:     "" => "ABC"
  tags.%:   "" => "<computed>"
azurerm_resource_group.test: Creation complete (ID: /subscriptions/XYZ/resourceGroups/ABC)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by raisaurabh777** [comment]
@030 @jontreynes @tombuildsstuff  I tried using Azure CLI and I was able to authenticate. Still curious why doesn't the Portal Method work. Is there a Bug at the Terraform end ? I followed all the steps mentioned in the Terraform Documentation for the Portal Method but still got the above error.

**Comment by Muxxx** [comment]
@raisaurabh777 I am having the same issue. I even added use_msi and set it to true and it still cannot authenticate.

provider "azurerm" {
  alias         = "aus-sydney"
  client_id     = "${var.ARM_CLIENT_ID}"
  client_secret = "${var.ARM_CLIENT_SECRET}"
  use_msi       = true
}

**Comment by Muxxx** [comment]
> @030 @jontreynes @tombuildsstuff I tried using Azure CLI and I was able to authenticate. Still curious why doesn't the Portal Method work. Is there a Bug at the Terraform end ? I followed all the steps mentioned in the Terraform Documentation for the Portal Method but still got the above error.

@raisaurabh777 Can you please share a bit of your Configuration?

**Comment by raisaurabh777** [comment]
@Muxxx I just followed the steps in "Creating a Service Principal using the Azure CLI" present in the doc at https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html

The Portal Method is not working for me. Hence I tried using the Azure CLI Way and it worked for me.
Let me know if you face any issue following the Azure CLI method. Hope that helps.

**Comment by Muxxx** [comment]
@raisaurabh777 , I had the same issue as you, and was able to get it working using the Portal Method (Service Principal Authentication). I followed the guide as well and found my issue was caused by me using provider aliases and when I referenced the provider 'azurerm' for defining a new resourcegroup, I was getting the error. After I added my alias to the azure resource group 'resource', my issue went away.

**Comment by raisaurabh777** [comment]
@Muxxx  Thanks for your help. Here's the simple configuration that I am trying to deploy:

# Configure the Microsoft Azure Provider
provider "azurerm" {
    subscription_id = "6fb7661e-xxxx-xxxx-xxxx-xxxxeefxx6x9"
    client_id       = "83c22b23-xxxx-xxxx-xxxx-xxxx8cxx07x6"
    client_secret   = "xxxxxSjTR7Lj+xxxxxPDNTXZo67ja7Nr3OdWZwxxxxx="
    tenant_id       = "https://login.microsoftonline.com/1b2f97f1-xxxx-xxxx-xxxx-1360f3d0xxxx/oauth2/authorize"
}

# Create a resource group if it doesn’t exist
resource "azurerm_resource_group" "myterraformgroup" {
    name     = "myResourceGroup"
    location = "eastus"

    tags {
        environment = "Terraform Demo"
    }
}

However I am still getting the error. I didn't quite get the change that you are suggesting in the "Aliases". Please elaborate. Thanks !

**Comment by tombuildsstuff** [comment]
@raisaurabh777 in the code above the Tenant ID needs to be the GUID/UUID from the URI - rather than the full HTTP URI - [there's more information in the docs](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html).

Since the recent comment are unrelated to the original issue, which was resolved over a year ago - I'm going to lock this issue for the moment. Please feel free to open a new issue if that doesn't work for you and we can take a look :)

Thanks!
