### ISSUE TITLE
AWS assume_role works for plan, doesn't for apply

### ISSUE THREAD

**Issue by Fodoj** [hashicorp/terraform#10554]
### Terraform Version

0.7.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_iam_role
- aws_iam_policy

### Terraform Configuration Files
```hcl
provider "aws" {
  alias = "us"
  region = "us-east-1"
  assume_role {
    role_arn = "my_arn"
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior

During `terraform plan`:

```
+ aws_iam_role.my-role
    arn:                "<computed>"
    assume_role_policy: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\" : \"Allow\",\n      \"Principal\": {\n        \"Service\": \"ec2.amazonaws.com\"\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}\n"
    name:               "my-role"
    path:               "arn:aws:iam::XXXXXXX:role/my-role"
    unique_id:          "<computed>"
```

During `terraform apply`:

```hcl
* aws_iam_role.my-role: Error creating IAM Role my-role: EntityAlreadyExists: Role with name my-role already exists.
	status code: 409, request id: 9df0b1e7-bbc4-11e6-9e3d-b56be3af805f
```

### Steps to Reproduce

1. Have 2 AWS accounts
2. Create an IAM role in Account A with a trust relation for Account B and a policy to manage all of IAM
3. Create an IAM role in Account B that can assume the role created in step 2
4. Create a role "my-role" in Account B by hand
5. Try to create a role "my-role" for Account A by running terraform template configured with "assume_role" block that has an arn value that equals an arn of role created in step 2. Run this terraform template from an EC2 instance that has a role created in step 3.

Seems like when terraform is trying to apply the template, even though it is configured to assume role of Account A, it still tries to create an IAM role for Account B and because it already exists, it fails, even though there is no role "my-role" in Account A yet.

**Comment by catsby** [comment]
Are both roles named `my-role` (or the same, if `my-role` is just a filler here)? I see you're using an alias above, can you share how the both account provider blocks are configured, and how you're using the aliases? It's hard for me to see what's happening without more configuration to reproduce the issue. 
Thanks!

**Comment by Fodoj** [comment]
There are no aliases and there is just one provider with configuration I've put above. I've tried to note down steps to reproduce above. Steps 1-4 are manual. Step 5 is running terraform.
