### ISSUE TITLE
DNSimple: dnsimple_domain resource

### ISSUE THREAD

**Issue by sobrinho** [hashicorp/terraform#1055]
Hi,

Would be great to be able to create the domain itself using terraform, e.g.:

``` terraform
resource "dnsimple_domain" "example.com" {
  domain "example.com"
}

resource "dnsimple_record" "www" {
  domain "example.com"
  name "www"
  value "xxx.xxx.xxx.xxx"
  type "A"
  ttl 3600
  depends_on "dnsimple_domain.example.com"
}
```

**Comment by phinze** [comment]
Similarly to #1058, I'm going to close this to indicate that there are no active plans to pick this feature up. If anybody finds this issue and wants to give a PR a try we'd love to help out!
