### ISSUE TITLE
AWS Tags that begin with 'aws' are dropped

### ISSUE THREAD

**Issue by rocket-ron** [hashicorp/terraform#10566]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

**Terraform v0.7.13**

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_scaling_group
- aws_security_group
- aws_alb
- aws_elasticache_replication_group
- aws_internet_gateway
- aws_vpc
- aws_subnet
probably more but those are the ones I've looked at

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

# NOTE: this is an example, not fully functional, but illustrates the 2 main ways tags are used.

variable "default_tags" {
  type = "map"
  default = {
    aws_account = "591156577215"
  }
}

variable "tags" {
  type = "map"
  default = {
    Name = "Example"
    Environment = "Development"
  }
}
resource "aws_security_group" "albsg" {
  name        = "${var.name_prefix}-ALB-${var.env_prefix}-SG"
  description = "${var.name_prefix} Application Load Balancer ${var.env_prefix} SG"
  vpc_id      = "${var.aws_vpc_id}"

  # HTTP access from anywhere
  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # outbound internet access
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = "${merge(var.tags, var.default_tags)}"
}

resource "aws_autoscaling_group" "asg" {
  name                      = "${var.name_prefix}-${var.env_prefix}"
  max_size                  = "${var.asg_max}"
  min_size                  = "${var.asg_min}"
  desired_capacity          = "${var.asg_desired}"
  force_delete              = true
  launch_configuration      = "${aws_launch_configuration.lc-conf.name}"
  wait_for_capacity_timeout = "5m"

  vpc_zone_identifier = ["${var.subnet_ids}"]
  tag {
    key                 = "aws_account"
    value               = "12345678"
    propagate_at_launch = true
  }
  tag {
    key                 = "Name"
    value               = "${var.name_prefix}-${var.env_prefix}"
    propagate_at_launch = true
  }
  tag {
    key                 = "Environment"
    value               = "${var.env_prefix}"
    propagate_at_launch = true
  }
}
```

### Expected Behavior
Resource should be created with several tags

### Actual Behavior
Tags are created and attached to resources _except_ for tags that begin with `aws`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Ninir** [comment]
Hi @rocket-ron 

This is a known limitation about tags, which is described here: http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-tag-restrictions.html

There are some guards for this in the code, but the documentation should reflect this too! thanks for spotting the issue.

**Comment by rocket-ron** [comment]
Ninir pointed out that AWS restricts `aws` as a prefix as described here: http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-tag-restrictions.html
What tripped me up was that it is possible to enter a tag with a key that begins with `aws` from the AWS Console/UI, it's just that Terraform is enforcing the AWS recommendation (I believe). In any case, this issue should probably be closed.

**Comment by apparentlymart** [comment]
Terraform is doing this to avoid showing spurious diffs when such tags get changed internally by AWS, since Terraform can't understand relationships created by things like OpsWorks.
