### ISSUE TITLE
associate_public_ip_address true when subnet map_public_ip_on_launch is true

### ISSUE THREAD

**Issue by mengesb** [hashicorp/terraform#10568]
Some time ago I opened an issue whereby I explicitly set `associate_public_ip_address = false` on an `aws_instance`; however because the subnet's default for `map_public_ip_on_launch = true` a public IP was associated anyway.

I understand that if there is no provided value, we should adopt the subnet's defaults however when you explicitly set something, that should be obeyed. As a result, every 'apply' results in my aws instances being destroyed and re-created.

### Terraform Version
0.7.13

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_instance" "anastance" {
  count            = "${var.host_count}"
  ami              = "${var.instance["id"]}"
  instance_type    = "${var.instance["type"]}"
  subnet_id        = "${var.instance["subnet"]}"
  associate_public_ip_address = "${var.instance["public"]}"
  vpc_security_group_ids = ["${var.vpc_sgids}"]
  key_name         = "${var.instance_defs["key_name"]}"
  tags             = {
    Name           = "${element(random_id.guid.*.keepers.hostname, count.index)}.${var.host_domain}"
    Description    = "${var.host_desc}"
    Terraform      = "true"
    chef_environment = "${var.chef["env"]}"
  }
  root_block_device = {
    delete_on_termination = "${var.instance_defs["root_delete"]}"
  }
}
```

When I specify `var.instance["public"] = "false"`, the instance always attempts to recreate itself.

### Debug Output
N/A (sensitive material; draft a simple plan to see debug)

### Panic Output
N/A

### Expected Behavior
If an `aws_instance` declares `associate_public_ip_address`, override the subnet's default for `map_public_ip_on_launch` and accept user input.

### Actual Behavior
Recreate resource because of conflict with `associate_public_ip_address`

```hcl
-/+ module.host.aws_instance.myinstance
    ami:                                       "ami-ffffffff" => "ami-ffffffff"
    associate_public_ip_address:               "true" => "false" (forces new resource)
    availability_zone:                         "us-east-1b" => "<computed>"
    ebs_block_device.#:                        "0" => "<computed>"
    ephemeral_block_device.#:                  "0" => "<computed>"
    instance_state:                            "running" => "<computed>"
    instance_type:                             "t2.large" => "t2.large"
    key_name:                                  "key.pem" => "key.pem"
    network_interface_id:                      "eni-99403b67" => "<computed>"
    placement_group:                           "" => "<computed>"
    private_dns:                               "ip-10-0-0-35.ec2.internal" => "<computed>"
    private_ip:                                "10.0.0.35" => "<computed>"
    public_dns:                                "ec2-54-1-1-83.compute-1.amazonaws.com" => "<computed>"
    public_ip:                                 "54.1.1.83" => "<computed>"
    root_block_device.#:                       "1" => "1"
    root_block_device.0.delete_on_termination: "true" => "true"
    root_block_device.0.iops:                  "0" => "<computed>"
    root_block_device.0.volume_size:           "50" => "<computed>"
    root_block_device.0.volume_type:           "standard" => "<computed>"
    security_groups.#:                         "0" => "<computed>"
    source_dest_check:                         "true" => "true"
    subnet_id:                                 "subnet-ffffffff" => "subnet-ffffffff"
    tags.%:                                    "4" => "4"
    tags.Description:                          "Made by Terraform (sip)" => "Made by Terraform (sip)"
    tags.Name:                                 "ec2-host1-1-sip.domain.tld" => "ec2-host1-1-sip.domain.tld"
    tags.Terraform:                            "true" => "true"
    tags.chef_environment:                     "sip" => "sip"
    tenancy:                                   "default" => "<computed>"
    vpc_security_group_ids.#:                  "2" => "2"
    vpc_security_group_ids.1348469803:         "sg-ffffffff" => "sg-ffffffff"
    vpc_security_group_ids.390452254:          "sg-dddddddd" => "sg-dddddddd"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create plan with an `aws_instance.associate_public_ip_address` set to `false` on a subnet where `map_public_ip_on_launch` is set to `true`
1. `terraform apply`

### Important Factoids
If the subnet's default is to not map a public IP, you can map one by setting `associate_public_ip_address` to `true`. The reverse should work as well.

### References
Unable to search and find some, but I know I've encountered this before.

**Comment by tamsky** [comment]
#8244 and #5764 are related issues.

**Comment by ozinka** [comment]
Hi,
looks like this issue still not resolved? At least, when I create **aws_launch_configuration** with 
**associate_public_ip_address** = **false**
TF creates EC2 with assigned public IP. Subnet is public and with Auto-assign public IPv4. But I definitely set it to **False** in code. 
Are there any plan to fix it?
Thnx
