### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by skanchin1** [hashicorp/terraform#10569]
The crash happened when i tried  to introduce the below :+1

count = "2"
   Name = "${lookup(var.hostname,count.index)}"

In the variablesfile  I have:

variable "hostname" {
default = {
    "0" = "arch-t1"
    "1" = "arch-t2"
   }
}

2016/12/06 21:36:11 [INFO] Terraform version: 0.7.13  2a4b4bbc3f315d100f76a83570e0364275e0fc6b
2016/12/06 21:36:11 [INFO] CLI args: []string{"C:\\Sharma\\Setup\\Work\\AWS\\Terraform\\terraform_0.7.13_windows_amd64\\terraform.exe", "plan"}
2016/12/06 21:36:11 [DEBUG] Attempting to open CLI config file: C:\Users\skanchinadham\AppData\Roaming\terraform.rc
2016/12/06 21:36:11 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2016/12/06 21:36:11 [TRACE] Preserving existing state lineage "23bf0271-11a5-4446-9b8e-a1aac5bbaa7c"
2016/12/06 21:36:11 [TRACE] Preserving existing state lineage "23bf0271-11a5-4446-9b8e-a1aac5bbaa7c"
2016/12/06 21:36:11 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: hostname is not a map, this is a bug in Terraform.

goroutine 1 [running]:
panic(0x2b61c20, 0xc0423cd870)
	/opt/go/src/runtime/panic.go:500 +0x1af
github.com/hashicorp/terraform/terraform.varSetMap(0xc0423b92f0, 0xc042328340, 0x8, 0x2b61c20, 0xc042328790)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/variables.go:159 +0x351
github.com/hashicorp/terraform/terraform.Variables(0xc04238bef0, 0xc04232a2a0, 0xc0423b92c0, 0x0, 0xc0423b92c0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/variables.go:111 +0x391
github.com/hashicorp/terraform/terraform.NewContext(0xc042322a20, 0xc0423c3380, 0x0, 0x4e78600)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/context.go:151 +0x63d
github.com/hashicorp/terraform/command.(*Meta).Context(0xc04218ae00, 0xc042308320, 0x41, 0x342250a, 0x11, 0x0, 0xa, 0x4, 0xc041ff3a87, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta.go:189 +0x311
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc04218ae00, 0xc042233e40, 0x2, 0x2, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:69 +0x5e9
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc0421b2780, 0xc0421fd980, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:154 +0x255
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:154 +0x54c
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:86 +0xd2
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:24 +0x3f

--------------------------------------------------------------

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by mitchellh** [comment]
Can you give a set of reproduction steps? I'm not seeing this at the moment but your issue leaves a lot to be guessed so I'd like to cut that down.

**Comment by skanchin1** [comment]
Sure, shall reopen when I can gather more information. Thanks.
