### ISSUE TITLE
Allow (flag) to continue plan if resource already exists? 

### ISSUE THREAD

**Issue by ifuyivara** [hashicorp/terraform#10562]
Is there a way to flag a single resource to ignore if that particular resource already exists and don't fail the apply?

Example:

I have two microservices that use one SQS queue to communicate with eachother but both should be able to be deployed independently (and should be able to put things in the queue even if the other microservice is not on the environment yet).

I was thinking I could declare the same queue on both terraforms and whichever microservice gets deployed to the environment first will create the queue and the second one will just ignore the creation of the queue if it already exists (and continue with the creation of the rest of the infrastructure for that microservice).

Does it make sense?

Thanks!
-Ivan

**Comment by mitchellh** [comment]
Please ask usage questions like this on the mailing list or chat. Sorry to shut it down like this but we try to keep issues to confirmed bugs. Thanks! You'll get a LOT more eyeballs to see your question on the ML or community chat.
