### ISSUE TITLE
output resource swallows lookup() errors.

### ISSUE THREAD

**Issue by rkr-kununu** [hashicorp/terraform#10573]
It appears that output {} is not properly relaying errors, if a key within a map does not exist.

### Terraform Version
version 0.7.13

### Affected Resource(s)

- output

### Terraform Configuration Files
```hcl
variable "mymap" {
  type = "map"
  default = {
    a = "apple"
    b = "banana"
  }
}

output "exists" {
  value = "${var.mymap["a"]}"
}

output "failure" {
  value = "${var.mymap["non-existant"]}"
}

output "failure2" {
  value = "${lookup( var.mymap, "non-existant" )}"
}
```

### Expected Behavior

```
Error configuring: 1 error(s) occurred:

* key "non-existant" does not exist in map var.mymap in:
....

```

### Actual Behavior

The output for "failure" and "failure2" was not reported nor was displayed.

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

exists = apple
```

### Steps to Reproduce

1. `terraform apply`

**Comment by mitchellh** [comment]
Dup #9080
