### ISSUE TITLE
One should be able to disable loading env vars without unsetting them.

### ISSUE THREAD

**Issue by carlosonunez** [hashicorp/terraform#10571]
This is a feature request. I discovered while playing around that several Terraform providers source provider configurations from environment variables. While `unset`ing them works just fine, it would be nice to have a command line flag that effectively disables `os.Getenv` for everything except logging and Terraform internals. This would help detect issues with provider variables sooner and prevent unexpected behavior, me thinks.

Thanks a lot for making this awesome product!

**Comment by mitchellh** [comment]
Hi, for this we recommend instantiating a new shell that resets the env vars. I don't think it makes sense for Terraform to do this directly since shells do it so well!

**Comment by carlosonunez** [comment]
Figured as much; that was my plan. Thanks, Mitchell!
