### ISSUE TITLE
Experimental feature failure

### ISSUE THREAD

**Issue by johnhamelink** [hashicorp/terraform#10580]
Hi there,

I've encountered an experimental feature failure, as per the instructions in the error, I've redacted sensitive info from the log and have saved it here: https://gist.github.com/johnhamelink/bd47f033cd6f7beaf64436d8301c409e

### Terraform Version
Terraform v0.7.13

### Affected Resource(s)

- module.api.app.aws_autoscaling_group.api_app21
- module.api.app.aws_security_group.api_app

**Comment by mitchellh** [comment]
Thanks! 

This looks like a dup of #10222 actually.
