### ISSUE TITLE
Allow triggers for all resource types to enable rebuilding resources on trigger changes

### ISSUE THREAD

**Issue by bbakersmith** [hashicorp/terraform#10586]
Feature request.

Would love to see the null_resource "triggers" be made available to other resource types, so you could specify that if ${var.foobar} changes, the resource should be rebuilt.

This would work something like...

```
resource "aws_s3_bucket_object" "foo" {
    ...
}

resource "aws_instance" "bar" {
    triggers {
        new_application_version = "${aws_s3_bucket_object.foo.etag}"
    }
    ...
}
```

...and should take the place of hacky workarounds like injecting the etag of the above s3 object into some rebuild-requiring field of the aws_instance. Alternately, being able to specify that any and all changes to a given resource should trigger a full rebuild would make such hacky workarounds easier because then any changed field could be used to trigger a rebuild.

**Comment by mitchellh** [comment]
A feature request for this already exists, I believe the proposal was to make `depends_on` do this but I think the plan is to make a new metaparameter that is just like `depends_on` but this behavior... at any rate if you search core+enhancement it should pop up.

**Comment by bbakersmith** [comment]
Thanks @mitchellh - I searched for such an issue before, and again now, but this is the closest I've found, is this the one you mean?

https://github.com/hashicorp/terraform/issues/113

**Comment by mitchellh** [comment]
Thats it! :)
