### ISSUE TITLE
DNSimple: Allow to set the record priority

### ISSUE THREAD

**Issue by sobrinho** [hashicorp/terraform#1058]
Hi,

For MX records we must be able to set the priority, example:

``` tf
resource "dnsimple_record" "aspmx" {
    domain = "${var.app_domain}"
    name = ""
    value = "ASPMX.L.GOOGLE.COM."
    type = "MX"
    ttl = 3600
    priority = 10
}
```

Makes sense?

**Comment by sobrinho** [comment]
What can I tell for now is that attribute is set as computed: https://github.com/hashicorp/terraform/blob/master/builtin/providers/dnsimple/resource_dnsimple_record.go#L56

Probably changing this line to `Optional: true` would fix the problem but I have absolutely no idea how to boot the terraform development environment here.

**Comment by phinze** [comment]
I'm doing a sweep of old issues without recent activity. This would be a welcome addition and we'd happily review any PR adding this feature. I took a quick look and unfortunately it's not as trivial as adding `Optional: true` to the field - it also needs to be added as a field to the API call.

For now I'm going to close this issue. Anybody who ends up here and is interested in picking up the work feel free to chime in! :+1:

**Comment by fnmunhoz** [comment]
I missed this feature today. It would be great to have it in the future. Anyway, thanks :grinning:
