### ISSUE TITLE
Bug with aws_cloudfront_distribution

### ISSUE THREAD

**Issue by gsaslis** [hashicorp/terraform#10598]
Hi there,

Opening this cause terraform itself told me to. 
(see, humans are already following machine instructions... ) 

### Terraform Version
`Terraform Version: 0.7.13`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudfront_distribution

### Debug Output
https://gist.github.com/gsaslis/dbf4a5f908eaf312bf041d85731e7974

**Comment by gsaslis** [comment]
tried downgrading to `0.7.5`, error still persists

**Comment by cultavix** [comment]
Probably a good idea to include your config/code as well ;)

**Comment by gsaslis** [comment]
```

**Comment by gsaslis** [comment]
fwiw - a temporary workaround is to run `terraform apply` once more (after this bug shows). 

I was able to get the cloudfront_distribution going with this
