### ISSUE TITLE
aws_instance - Mismatch reason: diff: Destroy; old: false, new: true

### ISSUE THREAD

**Issue by mattpickle** [hashicorp/terraform#10609]
### Terraform Version
`0.7.13`

### Affected Resource(s)
`aws_instance`

### Terraform Configuration Files
```hcl
resource "aws_instance" "services" {
  instance_type = "${var.services_instance_type}"

  ami = "${lookup(var.base_services_image, var.aws_region)}"

  key_name = "${var.aws_ssh_key_name_services}"

  subnet_id = "${var.aws_public_subnet_id}"
  security_groups = ["${aws_security_group.circleci_services_sg.id}",
  "${aws_security_group.circleci_users_sg.id}"]

  iam_instance_profile = "${aws_iam_instance_profile.circleci_profile.name}"
  tags {
    Name = "circleci_services"
  }

  root_block_device {
    volume_type = "gp2"
    volume_size = "150"
    delete_on_termination = false
  }
}
```

### Debug Output
`terraform plan`: https://gist.github.com/mattpickle/ef2a05b385dc1ec7f80e066c460017bf
`terraform apply`: https://gist.github.com/mattpickle/663e53ce6c6f577857caca5bb82e0a2c

### Expected Behavior
Expected the instance to be destroyed and create a new instance.

### Actual Behavior
Nothing.

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

**Comment by mitchellh** [comment]
This was fixed on master. We MAY have backported it to 0.7.14 too... please check the CHANGELOG... but we got this. Thanks :)

**Comment by mattpickle** [comment]
@mitchellh Thanks.  I didn't see anything in the CHANGELOG earlier this morning before I posted the issue.  If it's in 0.7.14, any ETA on getting that released?

**Comment by mitchellh** [comment]
@mattpickle Ah you're right I just took a look and its not backported. I think its only coming down the pipe in 0.8 which is slated for final release next week.
