### ISSUE TITLE
Feature Request: New attribute reference for AWS_REDSHIFT_CLUSTER

### ISSUE THREAD

**Issue by opteemister** [hashicorp/terraform#10601]
Hello,

### Terraform Version
Terraform v0.7.13

### Affected Resource(s)
- AWS_REDSHIFT_CLUSTER

AWS_REDSHIFT_CLUSTER has "endpoint" attribute reference. But for publicly accessible cluster it returns public IP. But cluster also have defined private IP/IPs. It would be good to have ability to get private IP through the attribute references.

Thank you.

**Comment by stack72** [comment]
Hi @opteemister 

I am looking at the AWS API / SDK for this right now - this action of returning the private IPs for a redshift cluster isn't supported it seems. The endpoint attribute has the following:

```
// Describes a connection endpoint.
type Endpoint struct {
	_ struct{} `type:"structure"`

	// The DNS address of the Cluster.
	Address *string `type:"string"`

	// The port that the database engine is listening on.
	Port *int64 `type:"integer"`
}
```

I think this will need to be raised as an issue with AWS to support. As it stands, Terraform isn't able to add this I am afraid 

Thanks

Paul
