### ISSUE TITLE
Feature Request: Multiple levels of iteration (count)

### ISSUE THREAD

**Issue by PatrickDRusk** [hashicorp/terraform#10619]
It would be extremely handy if resources could support multiple levels of iteration, rather that just the one level provided by count.  Here is a use case that shows how a proposed syntax might work.

Suppose I have a list of domains for which I want to create SNS topics for critical, warning, and informational notifications.  I might currently do something like this:
```hcl
variable domains { type = "list", default = ["dom0", "dom1", "dom3"] }
variable severities { type = "list", default = ["critical", "warning", "info"]}

resource "aws_sns_topic" "topics0" {
  count = "${length(var.severities)}"
  name = "dom0-${element(var.severities, count.index)}"
}

resource "aws_sns_topic" "topics1" {
  count = "${length(var.severities)}"
  name = "dom1-${element(var.severities, count.index)}"
}

resource "aws_sns_topic" "topics2" {
  count = "${length(var.severities)}"
  name = "dom2-${element(var.severities, count.index)}"
}
```
The end result would be to create the SNS topics `dom0.critical`, `dom0.warning`, ..., `dom2.info`.

It would be much nicer, though, if I could do something like this:
```hcl
resource "aws_sns_topic" "topics" {
  count = ["${length(var.domains)}", "${length(var.severities)}"]
  name = "${element(var.domains, count[0].index)}-${element(var.severities, count[1].index)}"
}
```
Alternatively, the following syntax would be even nicer:
```hcl
resource "aws_sns_topic" "topics" {
  iterate = ["${var.domains}", "${var.severities}"]
  name = "${iterate[0].value}-${iterate[1].value}"
}
```
This would envision the iterate variable exposing both "count" and "value".  It would save the user from having to repeat the frequent pattern of "element(..., count.index)".

This would probably involve some complications regarding the naming of the eventual elements and the splat syntax to reference them.

**Comment by mitchellh** [comment]
You can do a count that is a multiple: `count = "${var.domains} * ${var.severities}"` and then use the modulus operator to achieve more or less the same thing. I think given the rarity of usage like this, I prefer that.

**Comment by PatrickDRusk** [comment]
I'm surprised this is considered rare usage. When I brought it up with others at my company who have used terraform, they had all experienced some level of frustration with the lack of support for multiple levels. A couple are actively considering using Ruby templates to generate tf files to get around and the similar inability to put a count on module calls.

The modulus idea is a pretty strained approach that quickly leads to ugly files. I have a need to essentially do a three-level iteration, and it would get even uglier in that situation. The elements from the lists I would iterate over would be used in two or three places in the spec, requiring elaborate element(...) calls in each case.

**Comment by mitchellh** [comment]
Hey @PatrickDRusk, it is rare in the sense that in the 2.5 years of the project, this is the first time this idea (even in the abstract of multi-level iteration) has been brought up.

We're currently working on more levels of iteration and conditionals in Terraform and I want to flush that out before we introduce this since that may affect this idea and that issue (the conditional issue or iterations of sub-blocks) affects many more people just according to +1s on GitHub.

The modulus idea is very ugly, but its a workaround while we move forward.

**Comment by kvz** [comment]
For those bumping into the same thing, I found this SO post to have a helpful example: https://stackoverflow.com/questions/48814646/produce-a-cartesian-product-with-two-lists-in-terraform

**Comment by gh02067** [comment]
Here is a simple solution I came up with
Below is your test terraform script
###################
provider "aws" {
  region = "us-east-1"
}

variable "lista" {
  default = ["1", "2", "3"]
}

variable "listb" {
  default = ["A", "B", "C", "D"]
}

resource "aws_eip" "eip" {
  count = "${length(var.lista) * length(var.listb)}"
  tags {
    Name = "test-eip ${count.index}. ${ceil(element(var.lista, count.index/length(var.listb)))}:${element(var.listb, count.index)}"
  }
}
###################

to test, run below command on linux prompt
terraform plan|grep tags.Name

Below is the output
      tags.Name:         "0. 1:A"
      tags.Name:         "1. 1:B"
      tags.Name:         "2. 1:C"
      tags.Name:         "3. 1:D"
      tags.Name:         "4. 2:A"
      tags.Name:         "5. 2:B"
      tags.Name:         "6. 2:C"
      tags.Name:         "7. 2:D"
      tags.Name:         "8. 3:A"
      tags.Name:         "9. 3:B"
      tags.Name:         "10. 3:C"
      tags.Name:         "11. 3:D"

My usecase was to map multiple peerings to multiple route-tables (one per AZ/NAT).
