### ISSUE TITLE
Nested module w/ string dep not being planned

### ISSUE THREAD

**Issue by tylerFowler** [hashicorp/terraform#10622]
So I have a module with a nested module (may not matter though) that is set up to depend on a variable in it's parent module that is an `aws_network_acl.*.id` value given as a string, though when I do a plan on the parent module those dependencies aren't picked up.

Example:

Sub-sub-module:
```hcl
variable network_acl_id {}

resource "aws_network_acl_rule" "some_rule" {
  network_acl_id = "${var.network_acl_id}"
  # other stuff...
}
```

Sub-module (parent to the one above):
```hcl
resource "aws_network_acl" "some_acl" {
  # stuff...
}

module "mymod" {
  source = "./mymod"
  network_acl_id = "${aws_network_acl.some_acl.id}"
}
```

So when I do a plan on the sub-module (parent one) it tells me there's nothing to add:
`terraform plan -target="module.submod"`

*However*, when I get really specific then it does pick it up:
`terraform plan -target="module.submod.module.mymod"`

### Version:
`Terraform v0.7.13`

**Comment by mitchellh** [comment]
I think there is an issue tracking this but until we can verify I've tagged it.

**Comment by mitchellh** [comment]
Found it #5190 is the dup.

**Comment by tylerFowler** [comment]
Ah, missed that one, thanks!
