### ISSUE TITLE
Terraform plan acts strangely when given a plan file as input

### ISSUE THREAD

**Issue by cosmopetrich** [hashicorp/terraform#10627]
Hi,

Apologies if this is a duplicate, I couldn't find an existing issue.

The usage information for `terraform plan` says the following:

```
Usage: terraform plan [options] [dir]

  Generates an execution plan for Terraform.

  This execution plan can be reviewed prior to running apply to get a
  sense for what Terraform will do. Optionally, the plan can be saved to
  a Terraform plan file, and apply can take this plan file to execute
  this plan exactly.
```

But it appears that providing an existing plan file as the `dir` option causes the plan to be a noop, even though it appears to work as normal. This isn't critical or anything, but it's something that can easily catch one out if one accidentally omits the `-out`.

### Terraform Version

v0.7.13

### Affected Resource(s)

All resource types.

### Terraform Configuration Files

Any config should work, for the purposes of reproduction let's assume just use the config from the [aws_instance example](https://www.terraform.io/docs/providers/aws/r/instance.html).

```hcl
provider "aws" {
    region = "us-west-2"
}

data "aws_ami" "ubuntu" {
  most_recent = true
  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }
  filter {
    name = "virtualization-type"
    values = ["hvm"]
  }
  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web" {
    ami = "${data.aws_ami.ubuntu.id}"
    instance_type = "t2.micro"
    tags {
        Name = "HelloWorld"
    }
}
```

### Expected Behavior

One of the following seems best:

 1. `terraform plan` should throw an error since the plan file isn't a directory containing terraform config.
 2. `terraform plan` should act as `terraform show` when given a plan file (i.e. not refresh and immediately output the human-readable plan) and the behaviour should be documented.

### Actual Behavior

Terraform performs a refresh, but outputs the previous plan file without any modifications.

### Steps to Reproduce

 1. Save the example config above as `example.tf`.

 2. `terraform plan -out plan-bug.tfplan`

    Terraform correctly determines that it has to create a new instance.

 3. `rm example.tf`.

 4. `terraform plan plan-bug.tfplan` (note the lack of `-out`).

    Terraform appears to act normally: it performs a refresh then outputs a human-readable plan. However, the displayed plan and the plan file will still contain the resources that were previously defined in `example.tf`.

**Comment by apparentlymart** [comment]
I think you're right that this should just be an error, since a plan file is not a valid configuration directory. I expect it's not doing that just because a lot of the parameter handling code is shared between the `refresh`/`plan`/`apply`/`destroy` family of commands and it's probably ignoring the plan file altogether and assuming that you're just asking it to plan for the current working directory.

**Comment by apparentlymart** [comment]
The `plan` command just passes its first argument into [the context factory function](https://github.com/hashicorp/terraform/blob/804a5bd3c5b6418fca83f3a92717c267e4c49abc/command/meta.go#L119) as `copts.Path`.

We can see in there that Terraform will happily accept a plan and set things up as if it were `terraform apply` that were being run.

**Comment by mitchellh** [comment]
@apparentlymart Aside: try to tag issues with two labels please (type + category) :)
