### ISSUE TITLE
Resource import - provider settings (*schema.ResourceData) is empty

### ISSUE THREAD

**Issue by tintoy** [hashicorp/terraform#10623]
Hi.

I'm trying to implement resource import for [our provider](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.2/vendor/ddcloud/resource_networkdomain.go#L299) but I'm getting stuck on some odd behaviour.

When my [ConfigureFunc](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.2/vendor/ddcloud/provider.go#L127) is being called to initialise the provider, the ResourceData it is passed that usually contains the provider settings is empty (has schema, but no data - see the attached log).

Am I doing anything obviously wrong? If I'm doing a regular `plan`, `apply`, or `destroy`, it works just fine (the ResourceData has settings from the current directory's .tf files). Or am I misunderstanding, and perhaps `terraform import` doesn't load the current configuration at all? If so, how is the provider meant to collect its configuration?

I've tried looking at the docs and source for other providers but nothing really stands out as being particularly different (except that most use the pass-through function; I get the same error when using this, though).

### Terraform Version

Terraform v0.7.13

### Affected Resource(s)

- `ddcloud_networkdomain` (although the issue seems more generalised)

### Terraform Configuration Files
```hcl
provider "ddcloud" {
	region      = "NA"
	retry_delay = 10 # seconds
}
resource "ddcloud_networkdomain" "test-domain-1" {
	name		           = "terraform-test-domain-1"
	description	           = "Terraform test domain 1."
	datacenter	           = "NA9"
}
```

### Debug Output

https://gist.github.com/tintoy/71d2fd04198f1b6c113674ed5aa3658d

### Expected Behavior

Provider's ConfigureFunc should receive ResourceData with the provider settings from .tf files in the current directory.

### Actual Behavior

Provider's ConfigureFunc returns an error indicating that required provider settings are missing. They do appear to be missing from the supplied ResourceData.

### Steps to Reproduce

1. `git clone --recursive https://github.com/DimensionDataResearch/dd-cloud-compute-terraform`
2. `make dev`
1. `TF_LOG=DEBUG terraform import ddcloud_networkdomain.test-domain-2 4b57b4d0-b334-4306-b46b-5571f4418ae3`

### Important Factoids

You won't need CloudControl credentials because the provider never even gets that far (fails during initialisation).

**Comment by tintoy** [comment]
Ah. Looking at [this commit](https://github.com/hashicorp/terraform/commit/f8ec7dad192d47e5933cbb83b5a4bea7ad513683), I'm guessing that it won't work until v0.8?

**Comment by mitchellh** [comment]
Correct. This should work with 0.8.

**Comment by tintoy** [comment]
Ok, thanks for the heads-up.
