### ISSUE TITLE
Allow defining account ID for provider/aws to prevent human error

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1063]
While calling the API, you obviously don't need to define any account ID (that's automatically paired up with provided access key + secret key), but the traditional use-case is that people have one account for production, another one for development etc.

As it's almost impossible to know what API keys are coming from which account (prod/dev), so it's relatively easy to make a mistake and run something against prod account instead of dev.

There's an API endpoint that terraform could call if there was `account_id` defined in the `provider "aws"`:

```
$ aws iam get-user
{
    "User": {
        "UserName": "username", 
        "PasswordLastUsed": "2015-02-26T18:40:08Z", 
        "CreateDate": "2015-02-01T13:40:42Z", 
        "UserId": "AAAABBBCCC1234567890", 
        "Path": "/", 
        "Arn": "arn:aws:iam::1111111111111:user/username"
    }
}
```

where the account ID is `1111111111111` inside `User.Arn`.

What do you think of such feature?

**Comment by elliotmoore** [comment]
+1 *ahem* whistles innocently....
