### ISSUE TITLE
DeadLetterConfig support for AWS Lambda 

### ISSUE THREAD

**Issue by varadharajan** [hashicorp/terraform#10630]
According to the [AWS docs](http://docs.aws.amazon.com/lambda/latest/dg/dlq.html) , it is possible to specify dead letter queues for AWS Lambda function. If Terraform could support this parameter, we could directly send the failed events to the dead letter queue rather than manually publishing it ourselves as part of the Lambda function

**Comment by Puneeth-n** [comment]
@varadharajan `redrive_policy` in `aws_sqs_queue` Should send the failed events to the deadletter.

**Comment by maksymkazakov** [comment]
@Puneeth-n That's for the flow Usual SQS -> Dead letter SQS
And @varadharajan asked for support of the new feature described in the given link.

@varadharajan, were you successful with that configuration applied? I'm trying to make it work via Cloudformation and receive "Encountered unsupported property DeadLetterConfig" error during stack creation. Not sure how young is this feature, maybe it's not available in every region? I'm in eu-west-1

**Comment by maksymkazakov** [comment]
@varadharajan So here it is, the feature was presented about 2 weeks ago https://aws.amazon.com/about-aws/whats-new/2016/12/aws-lambda-supports-dead-letter-queues/
Then it might be that CloudFormation doesn't support DLQ configuration yet. Not sure how to configure DLQ manually or via CLI, will figure out tomorrow.

**Comment by varadharajan** [comment]
@maksymkazakov, I did not try it out with CloudFormation, so i'm not sure if CloudFormation is already supporting it.

Based on the a quick skim through the codebase, i thought the schemas used by the resource (https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_lambda_function.go#L213) kind of matches with the parameters expected in the docs at http://docs.aws.amazon.com/lambda/latest/dg/dlq.html . So i thought, we can directly sneak in that DeadLetterQueue parameter and see if it works? I can give it a try tomorrow morning and let you know. 

Does the AWS Lambda resource use cloudformation or directly invoke the AWS HTTP API?

**Comment by FastNinja** [comment]
Would be nice to be able to configure redrive policy queue for `AWS Lambda` (Lambda triggered by SNS).
Is there a pull request waiting to be approved or it is not on the road map at all?

**Comment by jjmartin** [comment]
The CLI does support it now: http://docs.aws.amazon.com/cli/latest/reference/lambda/update-function-configuration.html

**Comment by Luuseens** [comment]
Any news on this? The doc still lists this as doable in CF, but I get the same "Encountered unsupported property DeadLetterConfig" error when actually creating the stack.
