### ISSUE TITLE
ca-central-1 region

### ISSUE THREAD

**Issue by eugenetaranov** [hashicorp/terraform#10644]
Hi,

recently added ca-central-1 region is not supported. Can you please add it to terraform?

Terraform v0.7.13

### Affected Resource(s)
ALL

### Expected Behavior
run plan/apply without error

### Actual Behavior
error: region invalid

**Comment by nouillet** [comment]
This is already in their pipeline for next release 0.8.x. I too have this problem :). See https://github.com/hashicorp/terraform/pull/10618 and https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md

**Comment by eugenetaranov** [comment]
thanks :) somehow search failed me, glad to hear it is there already

**Comment by eddywashere** [comment]
I'm not familiar with the release cycle. Is there a process or a better way to have submitted #10618 to land in a stable release vs a prerelease? It seemed like a small enough change. Happy to submit additional prs to help out. Thanks!

**Comment by stack72** [comment]
Hi @eddywashere 

This will be part of the 0.8 release - if we cannot release 0.8 in a timely manner, we will make it available in a 0.7.x release

Thanks

Paul
