### ISSUE TITLE
Feature Request: support rolling updates for google instance group manager.

### ISSUE THREAD

**Issue by qvallance-ctc** [hashicorp/terraform#10647]
Google has added functionality for performing rolling updates for managed instance groups.
https://cloud.google.com/compute/docs/instance-groups/updating-managed-instance-groups

Would like Terraform's google_compute_instance_group_manager to support rolling updates as an update policy.

(Functionality is currently in Alpha - opening request to track progress for when it goes GA)

InstanceGroupManagerUpdatePolicy (v0.alpha)
https://code.googlesource.com/google-api-go-client/+/master/compute/v0.alpha/compute-gen.go#7175
https://code.googlesource.com/google-api-go-client/+/master/compute/v0.alpha/compute-api.json#4339

**Comment by evandbrown** [comment]
Thanks, @qvallance-ctc. @danawillow and I will track this as it moves towards GA.

**Comment by danielcompton** [comment]
How do you envision expressing this in Terraform config? I'm having a hard time seeing how this would mesh with Terraform. Terraform will delete the old instance template after creating the new one, which I don't think would work for canary deployments? Additionally, I think you'd run into the same kind of problem with a standard rolling update unless you wanted to leave Terraform running until the update had finished so it could then delete the previous instance template.

I can vaguely imagine some sort of "old instance template" and "new instance template" resources and manually updating these after the update has completed, but it doesn't feel very elegant. Maybe I'm missing something though.
