### ISSUE TITLE
Terraform plan output - doesnt show resource dependencies

### ISSUE THREAD

**Issue by mv012004** [hashicorp/terraform#10640]
Hi, 

When provisioning the aws_security_group resources and having the aws_security_group_rule referencing a security group, there is no evidence or information of the rules referring to aws_security_group, is there a way to show resource dependencies ?

### Terraform Version
0.7.11

### Affected Resource(s)
Please list the resources as a list, for example:
aws_security_group

Template TF file
```
resource "aws_security_group" "test-sg" {
  vpc_id      = "vpc-xxxxxxxx"
  name        = "test-sg"
  description = "test-sg-group through TF"

  tags {
    Name = "test-sg"
  }
}

resource "aws_security_group_rule" "test_sg_https_rule" {
  security_group_id = "${aws_security_group.test-sg.id}"

  type = "ingress"
  cidr_blocks = ["10.0.0.0/8"]
  protocol    = "tcp"
  from_port   = 8443
  to_port     = 8443
}

```

when the plan spits out the output there is no correlation between the rile and the group,

the security_group_id value is "<computed>" vs older versions have ${aws_security_group.test-sg.id}

Also if the target state after the plan apply can be extracted from the plan out, will prevalidate the results before running the apply.

**Comment by gauravbhandare** [comment]
+1 
Having the dependency and target state displayed helps review process.

**Comment by mv012004** [comment]
Thanks a lot for the quick fix, for the target state to be extracted from the plan out, i understand its an enhancement request, so should I be creating a new issue to track that ?

**Comment by jbardin** [comment]
@mv012004,

Sorry, I missed that last part when checking this issue. Go ahead and open a new issue for an enhancement, but please add an example of what you mean. I'm afraid I don't understand what the request.

Thanks!
