### ISSUE TITLE
vSphere Provider machine creation issues

### ISSUE THREAD

**Issue by mdk754** [hashicorp/terraform#10653]
I've been experimenting with terraform and the vsphere provider to provision vms. At this point, I'm not sure if I'm looking at a bug or feature request.

I think my issues stem from not having vcenter or templates.

### Terraform Version
Terraform v0.7.13
vSphere 6.5 standalone (no vcenter)

### Affected Resource(s)
- vsphere

### Expected Behavior
Here's my *.tf:
```# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = "user"
  password       = "password"
  vsphere_server = "server.fqdn"
  allow_unverified_ssl = true
}

# Create a virtual machine within the folder
resource "vsphere_virtual_machine" "web" {
  name   = "terraform-web"
  vcpu   = 1
  memory = 512

  network_interface {
    label = "VM Network"
    adapter_type = "vmxnet3"
  }

  disk {
    name = "/sda"
    size = 8
    type = "thin"
    datastore = "flash"
    controller_type = "scsi-paravirtual"
  }
}
```

### Actual Behavior
When the VM is created, a few things show up that don't appear right:
- The vm is created with a guest id of "otherLinux64Guest" causing a few isssues
- scsi-paravirtual is not supported by this guest id, so the disk is not attached upon viewing in esxi host client (technically it is, but I'll get to that)
- vmxnet3 also does not appear to be supported by this guest id
- If I manually go change the guest id in vmware to debian8_64Guest the disk and NIC suddenly appear, but the following issues show up:
- There's an extra disk controller (there's a useless scsi0 which is lsi parallel, then the scsi1 shows up as proper paravirtual, with the disk attached to it.) Not a big deal, but no need for the unused controller.
- The NIC is now using E1000e instead of vmxnet3.

### Important Factoids
- vsphere is licensed, but not a vcenter member
- in looking at the code, the issue appears to be [here](https://github.com/hashicorp/terraform/blob/e6b1cda7db9c84f44eeb947e8f10f8418c633a0e/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L1757-L1759)
- I think if I had a way to inject the guest id into the terraform plan, the only issue that remains would be the fact that there's always an unused lsi parallel scsi0 controller.

**Comment by mikhail-bardash-mpf** [comment]
Is there any update on this ticket?

Not being able to set the Adapter Type to vmxnet3 is a major blocker for us. We have had major issues with E1000 and ESXi servers.
