### ISSUE TITLE
Support AWS Step Functions

### ISSUE THREAD

**Issue by davidski** [hashicorp/terraform#10652]
### Terraform Version
Terraform 0.7.13

### Affected Resource(s)
AWS Provider

This is a tracking issue for building Terraform support for AWS Step Functions (http://docs.aws.amazon.com/step-functions/latest/apireference/Welcome.html). As the CreateStateMachine function takes a substantially long JSON blob describing the flow, a data source similar to the existing `aws_iam_policy_document` would probably be a good idea.

**Comment by Ninir** [comment]
Hi guys,
Started working on this in #11420 . It's almost ready!

**Comment by bdgamble** [comment]
Saw that the PR #11420 was merged for this, will it be released in v0.8.6, and if so, what is the ETA on that release. I'm excited to use this new functionality! Thanks @Ninir for putting in the work!

**Comment by Ninir** [comment]
Hi @davidski ,

For now, Step Functions support basic inline documents and [templates files](https://www.terraform.io/docs/providers/template/d/file.html).
I'll see how a dedicated `aws_sfn_state_machine_definition` resource could be created!

**Comment by radeksimko** [comment]
Hi folks,
as far as I understand the SFN support is pretty much complete (`aws_sfn_state_machine` + `aws_sfn_activity`) and we can close this issue, am I right?

**Comment by davidski** [comment]
Hi, @radeksimko. Terraform support for SFN is indeed up and running. The current support requires template files or very long JSON blobs. This isn't as clean as the data source version that IAM policy resources have in this provider. I'm fine with closing this out, but we shouldn't loose visibility into the discrepancy between the implementation of SFN vs. IAM. I'd very much like to see a consistent user experience when dealing with long JSON documents within the AWS provider and am a little anxious about fragmenting designs across different resources.

Again, the SFN functionality works today. Which is awesome! :grin:

**Comment by Ninir** [comment]
Glad to hear @davidski :)

I think there is a much more complexity with the data source, but this is still in my bag for future contributions ;)

**Comment by radeksimko** [comment]
Thanks,
I will close this issue then, as it's describing SFNs as a feature and that's supported.
Feel free to raise a PR for the mentioned data sources whenever you're ready for it. 😺
