### ISSUE TITLE
SSH Key error

### ISSUE THREAD

**Issue by hkalyana** [hashicorp/terraform#10668]
I am getting an error invalid or unknown key while trying to launch an ubuntu machine in azure arm mode .How should I use the ssh_keys parameter mentioned in the documentation . The documentation around it is a little confusing .

**Comment by mitchellh** [comment]
Please ask usage questions in the mailing list or community. You'll get a lot more eyeballs on there who can probably help you out. 

However, the SSH keys we expect are in PEM format (OpenSSH private key defaults). If you determine that our docs are inadequate or incorrect, or there is actually a bug, please do open an issue and we'll get that resolved.
