### ISSUE TITLE
Error Accessing List of Lists generated by splatting private_ips from aws_network_interface

### ISSUE THREAD

**Issue by denmarm** [hashicorp/terraform#10672]
Hi there,

I am struggling with accessing a list of lists generated by splatting the private_ips for aws_network_interface. Any help would be appreciated.

### Terraform Version
Terraform v0.7.4

### Affected Resource(s)
- aws_network_interface
- aws_route53_record

### Terraform Configuration Files

```
resource "aws_network_interface" "INSTANCE_MAN" {
  count         = "${var.instance_count}"
  subnet_id  = "${split(",",var.management_subnets)}"
  description = "Management Interface"
}

output "management_ips" { value = ["${aws_network_interface.INSTANCE_MAN.*.private_ips}"] }
```

### Output from variable shows a list of lists, because private_ips is a list and the splat from INSTANCE_MAN also creates a list I am left with a list of lists, see below

```
management_ips = [
    [
        10.65.170.140
    ],
    [
        10.65.171.147
    ],
    [
        10.65.170.233
    ],
    [
        10.65.171.101
    ]
]
```

### Expected Behavior
I expected to be able to read the list of lists in a subsequent module to setup route53 records for each management ip.

### Actual Behavior

```
resource "aws_route53_record" "server_instance_route53" {
  count = "${var.instance_count}"
  zone_id = "${var.route53_zone_id}"

  name = "${element(split(",",var.instance_names), count.index)}.${var.route53_domain}"
  type = "A"
  ttl = "300"
  records = ["${element(var.instance_ips,count.index),0)}"]
}
```

Output 

```
**Error creating plan: 4 error(s) occurred:

* element: element() may not be used with an empty list in:**
```

# Also Tried... 

```
records = ["${element(var.instance_ips,count.index),0))}"]
```

Again same error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

I do the same for private_ips on the instances themselves and because they do not return a list I do not encounter this issue

**Comment by mitchellh** [comment]
Thanks, dup of #8013
