### ISSUE TITLE
Creating alarm fails with error "A separate request to update this alarm is in progress"

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#10689]
### Terraform Version

Terraform v0.7.7

### Affected Resource(s)

- aws_cloudwatch_metric_alarm

### Terraform Configuration Files

I have three modules that create CloudWatch alarms: CPU usage, one for memory usage, and one for disk space usage. They all look more or less like this:

```hcl
resource "aws_cloudwatch_metric_alarm" "ec2_high_cpu_utilization" {
  count = "${var.instance_count}"
  alarm_name = "ec2-high-cpu-utilization-${element(var.instance_ids, count.index)}"

  # (... all the standard alarm params ...)
}
```

### Expected Behavior

I'm passing these modules the ID of the same EC2 Instance, so I expect three alarms to be created.

### Actual Behavior

The memory usage alarm gets created, but the other two fail with this error:

```
* aws_cloudwatch_metric_alarm.ec2_high_disk_utilization: Creating metric alarm failed: ValidationError: A separate request to update this alarm is in progress.
    status code: 400, request id: dafd60e0-c0de-11e6-be81-87349c242d9e
* aws_cloudwatch_metric_alarm.ec2_high_cpu_utilization: Creating metric alarm failed: ValidationError: A separate request to update this alarm is in progress.
    status code: 400, request id: db0242e5-c0de-11e6-903c-8b6cee93e201
```

No other alarms exist in my account whatsoever. No one else is using the account at all, so there are no other API calls happening. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When I re-ran `terraform apply` after the error, the two alarms were created just fine.

**Comment by josh-padnick** [comment]
I received this same error, applying a very similar template in a different AWS account.

**Comment by catsby** [comment]
Hey all – can you help me with a reproduction case? I've started with this gist:

- https://gist.github.com/catsby/ba332b156f77ae0f34b4d35573a587e3

I'm unable to reproduce so far, what am I missing? Are they all named `alarm_name = "ec2-high-cpu-utilization-${element(var.instance_ids, count.index)}"` , even the `mem` and `disk`? I could see how that's happening in the `CREATE` method, assuming that's even allowed...

Please let me know what I'm missing in the reproduction config I shared. Thanks!

**Comment by brikis98** [comment]
The Gist you have is more or less what we have. The only differences are:

* Each CloudWatch alarm is defined in a separate module
* The alarms do NOT have the same name. The each have a different base name (e.g. ec2-high-cpu-usage, ec2-low-memory) and parameterize the name with the instance ID.
* They specify an SNS topic for `alarm_actions`

Not sure any of these will matter.

**Comment by catsby** [comment]
Is it the same SNS topic? How reproducible has/was this issue? By any chance were these created/destroyed in quick succession? I'm scratching my head as to why a `create` would fail because an `update` action was in progress 🤔 

My first thought is that the `update` is really a `destroy` from an earlier session, but I'm not sure if that's the case here :/

**Comment by brikis98** [comment]
Yup, same SNS topic. I haven't had a chance to run the same templates since, so I'm not sure if it's reproducible. I don't think it was a `destroy`, as I was creating this stuff in a fresh AWS account...

Agreed that it's a confusing error. Does the creation a single alarm resource by any chance require multiple API calls? For example, creating an `aws_instance` with tags requires one call to create the instance and then a separate one to add the tags.

**Comment by bjoernhaeuser** [comment]
We can reproduce this with latest terraform (v0.8.7). Is there any workaround for this? :)

**Comment by bjoernhaeuser** [comment]
Also if it's clear how to fix the problem, we would also love to contribute a fix for it :)

**Comment by vivekprahlad** [comment]
I've run into this bug as well, @bjoernhaeuser  . This seems to be a concurrency issue, I managed to get around it by serializing the creation of cloudwatch alarms (using depends_on)

**Comment by svenwltr** [comment]
@vivekprahlad Unfortunately it's hard to do a `depends_on` if the alarms are created in a module which is called multiple times. And adding the depends on a module isn't a solution, because the build duration would increase too much.

**Comment by vivekprahlad** [comment]
@svenwltr: Yes, I agree with you - I'm just pointing out that this bug seems to be due an underlying concurrency issue, and shared what worked for me :). I have a setup where I had to create 3 alarms without having to deal with modules.

**Comment by goochi1** [comment]
what was the fix for this?

**Comment by sprutner** [comment]
I still have this issue.

**Comment by nicovanniekerk** [comment]
I just ran into this issue while playing with alarms, and realized that the SNS topic i am using is not in the same region as the provider i am running terraform with. moving the SNS topic into the same region as my terraform run, and also as the lambda function, then it works.

**Comment by ethicalmohit** [comment]
I am still having this issue.

**Comment by apparentlymart** [comment]
Hi all,

This is an AWS provider issue that is now being tracked in the AWS provider repository, at terraform-providers/terraform-provider-aws#422. There will be no further updates on this issue in this repository, since AWS provider development no longer occurs here.
