### ISSUE TITLE
Not a valid region: ca-central-1

### ISSUE THREAD

**Issue by pulpfree** [hashicorp/terraform#10686]
Having an issue using the aws_instance resource.
Terraform version: v0.7.13

When running: `terraform apply` I get this result: Not a valid region: ca-central-1
I don't see a skip_region_validation flag and wondering if the region is going to be supported?

Regards,
ron

**Comment by apparentlymart** [comment]
Hi @pulpfree,

It looks like this was recently implemented in #10618, so this will become available in the forthcoming 0.8 release of Terraform, which I expect will hand any day now.
