### ISSUE TITLE
provider/aws: Add api_gateway_binary_media_types resource

### ISSUE THREAD

**Issue by lenaten** [hashicorp/terraform#10696]
Amazon [announced](https://aws.amazon.com/about-aws/whats-new/2016/11/binary-data-now-supported-by-api-gateway/) they add the ability to send and receive binary data through API endpoints hosted on Amazon API Gateway. It's could be very useful for image processing with lambda.

The value of api_gateway_binary_media_types should be a list of strings (HTTP Content Type). For example:
- image/jpeg
- image/png

**Comment by jmettes** [comment]
I'm giving this a crack - almost have it working I think. Hopefully will put in pull request soon.

**Comment by stack72** [comment]
Closed via #10776 - thanks to @jmettes :)

**Comment by lenaten** [comment]
Great! Thanks @jmettes!

**Comment by przemos** [comment]
+1 for reopen.

**Comment by stack72** [comment]
Reopening as this was only partially added

**Comment by stack72** [comment]
Folks, I have just opened #11002 that will take care of the rest of this request
