### ISSUE TITLE
`vendor.json` references `github.com/lrsmith/terraform`

### ISSUE THREAD

**Issue by mdb** [hashicorp/terraform#10699]
It appears that `vendor/vendor.json` contains the following, as per [this commit](https://github.com/hashicorp/terraform/commit/015e96d0ddeab096b1b8e1c76190fe697504db27):

```
"rootPath": "github.com/lrsmith/terraform"
```

### Expected Behavior

I would expect it to contain:

```
"rootPath": "github.com/hashicorp/terraform"
```

**Comment by stack72** [comment]
Closed via #10700
