### ISSUE TITLE
RDS/MySQL version upgrade - forces new resource

### ISSUE THREAD

**Issue by elliotmoore** [hashicorp/terraform#1070]
terraform -v
Terraform v0.4.0-dev
rev: b7459cb

Hi,

Playing around with terraform and RDS - went to bump a version and terraform plan advised me it would force a new resource. 

   ` engine_version:           "5.6.19b" => "5.6.21b" (forces new resource)`

I went ahead anyway, its only a test and indeed it did destroy the database but failed to re-create it.

```
<snip>
aws_db_instance.default: Refreshing state... (ID: estest-database)
aws_db_instance.default: Destroying...
aws_db_instance.default: Destruction complete
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* aws_db_instance.default: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Running `terraform apply` again recreated the database

Note, Running an upgrade in the console just requires a reboot and http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-engineversion also suggests it's a bug.

thanks. 

I understand the aws/go library is in transition - so this might be mute soon...

**Comment by catsby** [comment]
Thanks for reporting! Def. seems bug-ish, but maybe in more way than one.
I see that `engine_version` is currently set to force a new resource (the delete you saw):

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_instance.go#L50

The `This is a bug with Terraform and should be reported.` is definitely a bug for us, thanks! /cc @mitchellh 

I'll look more into the docs and do some research here on options.

**Comment by elliotmoore** [comment]
Thanks for replying.

If i'm reading that file correctly, There are a number of other incorrect 'ForceNew' instructions in that file.
eg: allocated_storage, instance_class, password etc

Some of these changes are disruptive, but not destructive (ie it reboots etc) can be deferred until the next maintenance window, depending on the value of `ApplyImmediately` on submission.
http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html

Keep up the good work, it's a great product!
