### ISSUE TITLE
0.8.0 - wants to destroy all aws_alb resources - indicates "deposed"

### ISSUE THREAD

**Issue by levinse** [hashicorp/terraform#10709]
Upgraded to 0.8.0 and ran plan. Terraform wants to destroy all aws_alb resources:
`
- module.lb-app-something.aws_alb.lb (deposed)

- module.lb-app-prd.aws_alb.lb (deposed)

- module.lb-app-stg.aws_alb.lb (deposed)

`

Let me know what further info you need.

**Comment by mitchellh** [comment]
Hey @levinse: Terraform 0.8 is able to see deposed resources in every case whereas Terraform 0.7 and before would ignore them. A "deposed" resource in Terraform is one that should be destroyed as part of a create-before-destroy operation. 

If you want to be sure of what it is destroying, see the state file and look for a non-empty `deposed` key. Those are the resources that are planning on being destroyed. 

If this doesn't look correct to you, please share your state file (censor sensitive info if any). That is all we need. :)

**Comment by mitchellh** [comment]
For extra info, here is the PR where we made plan show deposed: https://github.com/hashicorp/terraform/pull/10404
