### ISSUE TITLE
aws_iam_user - not recording secret to TF state file or showing in outputs

### ISSUE THREAD

**Issue by cultavix** [hashicorp/terraform#10701]
### Terraform Version
`0.8.0-rc3`

### Affected Resource(s)
`aws_iam_user`

### Terraform Configuration Files
```hcl
resource "aws_iam_user" "something" {
  name = "something"
}

resource "aws_iam_access_key" "something" {
  user = "${aws_iam_user.something.name}"
}
```

### Outputs config

```hcl
output "aws_iam_access_key_id" {
  value = "${aws_iam_access_key.something.id}"
}

output "aws_iam_access_key_secret" {
  value = "${aws_iam_access_key.something.secret}"
}
```

### Expected Behavior
User is created, access key is created. Details recorded in TF state file and show in output if called.

### Actual Behavior
User is created, access key is created but the secret key is not recorded in TF state nor does it display it in outputs which are configured to show it.

### Steps to Reproduce
`terraform apply`

### Comments
Really at a lost on this one, any help would be much welcomed. I've tried to delete the resources via `destroy`, I've tried to delete the resources manually on the AWS console and re-applying, nothing seems to work. 

Note: I'm aware that this could potentially be an issue with my setup, I've tried this on 2 different machines and I get the same results. I just can't for the life of me figure out why it would be doing this.
Thanks!

**Comment by cultavix** [comment]
@catsby ohh, that's great! Thank you so much.

**Comment by catsby** [comment]
I opened #10702 to only save the `secret` if no PGP key is given. #10694 at time of writing saves it regardless

**Comment by catsby** [comment]
Going to go ahead and close this issue, we'll get the bug patched up 😄
