### ISSUE TITLE
AWS Provider Enhancement -- Attach AWS WAF policies to ALBs

### ISSUE THREAD

**Issue by chroto** [hashicorp/terraform#10713]
### Terraform Version
0.7.13

### Affected Resource(s)
- aws_alb

AWS announced that they now support WAF policies attached to ALBs ( https://aws.amazon.com/about-aws/whats-new/2016/12/AWS-WAF-now-available-on-Application-Load-Balancer/ )

This would be an amazing feature to have on the 0.7 branch!

**Comment by 4dz** [comment]
+1 definitely need this feature :)

**Comment by goduncan** [comment]
+1 from me too. Any thoughts on what release it might make it in to? Cheers!

**Comment by charles-d-burton** [comment]
+1 I also need this feature.

**Comment by henryng24** [comment]
+1 need

**Comment by zoharsanchez** [comment]
+1 for me as well! 🙏

**Comment by sbeasey** [comment]
we need this feature

**Comment by hylaride** [comment]
+1 (million) ;-)

**Comment by arevell89** [comment]
+1
