### ISSUE TITLE
required_version has no effect

### ISSUE THREAD

**Issue by seanknox** [hashicorp/terraform#10715]
### Terraform Version
Terraform v0.8.0

### Affected Resource(s)
- `terraform {
  required_version = "> ..."
}`

### Terraform Configuration Files
```hcl
terraform {
  required_version = "> 0.8.1"
}
```

### Debug Output
Unfortunately I have a lot of sensitive information in my debug output that I can't include.

### Expected Behavior
An error is shown and TF exits due to TF version < 0.8.1

### Actual Behavior
Plans are executed with Terraform 0.8.0

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Add the following `terraform` configuration:
```hcl
terraform {
  required_version = "> 0.8.1"
}
```
1. `terraform apply`

**Comment by mitchellh** [comment]
![2016-12-13 at 8 43 pm](https://cloud.githubusercontent.com/assets/1299/21169850/c6a01de4-c174-11e6-86c3-c0b8b40a259a.png)

I'm not sure what you're doing wrong but your exact configuration works for me exactly. Can you double check and report back if I'm missing something? Thanks!

**Comment by seanknox** [comment]
@mitchellh should it matter if I'm declaring the `terraform` resource in a modules manifest (no direct resources otherwise)? e.g.

```hcl
terraform {
  required_version = "> 0.8.1"
}

module "s3" {
  source = "./modules/s3"
  depends-id = "${ module.vpc.depends-id }"

  bucket-prefix = "${ var.s3-bucket }"

  hyperkube-image = "${ var.k8s["hyperkube-image"] }"
  hyperkube-tag = "${ var.k8s["hyperkube-tag"] }"
  internal-tld = "${ var.internal-tld }"
  name = "${ var.name }"
  region = "${ var.aws["region"] }"
  service-cluster-ip-range = "${ var.cidr["service-cluster"] }"
}
```

**Comment by mitchellh** [comment]
@seanknox I tried two scenarios, both of which **were successful**:

  * No `terraform` block, do a `terraform get`, add the `terraform` block, `terraform apply` (errored)

  * `terraform` block in place, `terraform get` (errored)

**Comment by seanknox** [comment]
@mitchellh ok, this is interesting:

- I can successfully trigger the version error on a new project with a `main.tf` just like yours:
```
[seanknox:~/src/terraform-foo]$ cat main.tf
terraform {
  required_version = "> 0.8.1"
}

[seanknox:~/src/terraform-foo]$ terraform plan
The currently running version of Terraform doesn't meet the
version requirements explicitly specified by the configuration.
Please use the required version or update the configuration.
Note that version requirements are usually set for a reason, so
we recommend verifying with whoever set the version requirements
prior to making any manual changes.

  Module: root
  Required version: > 0.8.1
  Current version: 0.8.0
```

- In an existing project modeled after [tack](https://github.com/kz8s/tack), adding the `terraform` resources to the top level `modules.tf` file seems to have no effect:

```
[seanknox:~/src/devinfra]$ ls                                                                
Makefile            manifests           scripts             terraform.tfvars
README.md           modules             staff_ips.txt       test
io.tf               modules.tf          terraform.tfplan    tmp
makefiles           modules_override.tf terraform.tfstate   vpc-existing.tfvars

[seanknox:~/src/devinfra]$ head modules.tf                                                   
terraform {
  required_version = "> 0.8.1"
}

module "s3" {
  source = "./modules/s3"
  depends-id = "${ module.vpc.depends-id }"

  bucket-prefix = "${ var.s3-bucket }"

[seanknox:~/src/devinfra]$ terraform plan                                                   
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Warnings:

  * template_file.user-data: using template_file as a resource is deprecated; consider using the data source instead
  * template_file.cloud-config: using template_file as a resource is deprecated; consider using the data source instead
  * template_file.discover-client #0: using template_file as a resource is deprecated; consider using the data source instead
  * template_file.discover-client #2: using template_file as a resource is deprecated; consider using the data source instead

<snip>

No errors found. Continuing with 15 warning(s).

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

module.bastion.template_file.user-data: Refreshing state... (ID: 03bd397e91eda413a2ccae2a5d663415640b3c48f11eef1a01668c74c8e06885)
<snip>
```

**Comment by mitchellh** [comment]
That's it. I know what is happening.

When an `_override` is present it trigger's Terraform's _merge config_ behavior (which it otherwise doesn't need to invoke). This doesn't honor `terraform` blocks. Reopening and fixing this now.

**Reiterating: This only affects your config if the module with `terraform` also has an `_override` file.**

**Comment by mitchellh** [comment]
By the way, thanks for sticking with this and being helpful. It led to knowing whats going on. 👨‍❤️‍👨

**Comment by seanknox** [comment]
Ah! And I also learned that I have an `_override` and what it does. :)

**Comment by mitchellh** [comment]
Fixed in the referenced PR. Thanks again!
