### ISSUE TITLE
Small potential oversight

### ISSUE THREAD

**Issue by fosskers** [hashicorp/terraform#10710]
### Terraform Version
`terraform-0.8.0`

### Affected Resource(s)
`aws_emr_cluster`

### Issue
Hi there, [this commit](https://github.com/hashicorp/terraform/commit/a5f8352e1194ee7dc74a26999747b00ec299bcb5#diff-6910e11efe56fddf04a37c72652bd5df) increased the cluster creation state-change timeout to 75 from 40, with justification. [This commit](https://github.com/hashicorp/terraform/commit/a5f8352e1194ee7dc74a26999747b00ec299bcb5#diff-6910e11efe56fddf04a37c72652bd5df) decreased it back to 40 without justification. Given that the change to 75 wasn't commented in the code, the second committer might have thought it odd that the other timeouts in the same file didn't match, so he innocently made them match.

Thoughts? The timeout of 75 was quite useful, but it seems that 40 made it into the `0.8` release.

### References
- GH-10444

**Comment by apparentlymart** [comment]
Hi @fosskers... it looks like both of your links there are to the same commit, which appears to be the one that increased it. Do you still have the link to the second one handy?

**Comment by fosskers** [comment]
My mistake, here's the second commit: https://github.com/hashicorp/terraform/commit/8586e323dc55b953c48867c71f2ca7869794497a

**Comment by catsby** [comment]
Hey @fosskers thanks for pointing this out; looks like the second commit was just a "whoops" after a PR had to be rebased, simple mistake. I've bumped it back to `75` in 70b1f4e7085e659d2892cfa644afccdddf28d7e1 which should go out in `v0.8.1`, which may come as early as today 😄
