### ISSUE TITLE
Deposed resources are not destroyed

### ISSUE THREAD

**Issue by henrytk** [hashicorp/terraform#10721]
Issue https://github.com/hashicorp/terraform/issues/9844 was closed prematurely. A clear demonstration of how the issue can be replicated was provided in a comment shortly after closure: https://github.com/hashicorp/terraform/issues/9844#issuecomment-258872408

Please see the issue for full details of the problem.

**Comment by jbardin** [comment]
Hi @henrytk,

This should be fixed in the current release, and I could not replicate the issue with the steps laid out in 9844. Are you having this problem with v0.8?

**Comment by mitchellh** [comment]
Hey @henrytk, I'm in the same boat as @jbardin (didn't see he had tried since I had an old tab open).

I tried your exact example with 0.8 and could not reproduce your error. I believe as well that the issue wasn't closed prematurely and that it is fixed in the latest version. Can you try with 0.8?

**Comment by henrytk** [comment]
I cannot reproduce it with 0.8.* so I am happy to close this. Thank you both.
