### ISSUE TITLE
destroying multiple modules uses incorrect order and causes race conditions

### ISSUE THREAD

**Issue by pmcatominey** [hashicorp/terraform#10729]
Destroying resources in multiple modules does not appear to order dependencies correctly.

### Terraform Version

master - (a9637f6)

### Affected Resource(s)

Tested with the following resources but I believe this is a core issue.

- azurerm_public_ip
- azurerm_resource_group
- azurerm_lb
- azurerm_lb_backend_address_pool

### Terraform Configuration Files

https://github.com/BedeGaming/tf-module-bug

### Debug Output

See `debug.log` in linked repo, sensitive values scrubbed.

### Expected Behavior

The resources should have been deleted in the correct order, that is the reverse of the order applied.

### Actual Behavior

The resources defined in each module were deleted at the time causing an error as the Public IP resource cannot be deleted while it is attached to the Load Balancer.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. clone linked [repo](https://github.com/BedeGaming/tf-module-bug)
1. configure AzureRM provider credentials
1. `terraform get`
1. `terraform apply`
1. `terraform destroy`

**Comment by mitchellh** [comment]
Thanks, reproduced with null resources.

**Comment by mitchellh** [comment]
Fix in PR.

**Comment by pmcatominey** [comment]
Thanks for the quick fix!

All working our side now.
