### ISSUE TITLE
Feature request: Amazon CloudWatch SubscriptionFilter Lambda support

### ISSUE THREAD

**Issue by opteemister** [hashicorp/terraform#10727]
### Terraform Version
Terraform v0.7.13

### Affected Resource(s)
aws_cloudwatch_log_subscription_filter

### Expected Behavior
destination_arn - please add support AWS Lambda function 

### Actual Behavior
destination_arn - (Required) The ARN of the destination to deliver matching log events to. Currently only Kinesis stream / a logical destination

### References
http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutSubscriptionFilter.html
https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_subscription_filter.html

**Comment by stack72** [comment]
Hi @opteemister 

AFAICT, this is now supported in Terraform. No code changes were necessary - we just needed to update the SDK. Please can you let me know if this is actually the case?

Thanks

Paul

**Comment by opteemister** [comment]
Hi, @stack72 

Actually I already found the solution. In fact terraform was supported Lambda functions as a destination by design. Because AWS API supports it. So I tried and it worked.

And according to that I created pull request - https://github.com/hashicorp/terraform/pull/13659. To mention it in documentation. 

So it looks like this issue is not actual right now.

Thank you.

**Comment by stack72** [comment]
Thanks for letting me know :)
