### ISSUE TITLE
One of our unit tests is leaking a file

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#1072]
After a `make test` run, I end up with this:

![1__tuesday__tmux_](https://cloud.githubusercontent.com/assets/37534/6407507/1405d6f0-be07-11e4-9fec-67cd495dec1d.png)

Who is this mysterious `command/-`, and who is responsible for its trespassing?!?

Well, I know one thing. The culprit is _someone in this very room_!

**Comment by radeksimko** [comment]
There's actually more tests generating this:

```
$ grep '"-"' command/*_test.go
```
```
command/apply_test.go:		"-backup", "-",
command/plan_test.go:		"-backup", "-",
command/refresh_test.go:		"-backup", "-",
command/taint_test.go:		"-backup", "-",
```

I guess the dash is being interpreted wrongly when passed directly from code?

**Comment by mitchellh** [comment]
I'm on it, my refactor may have caused the `backup` flag to not work properly.

**Comment by mitchellh** [comment]
Indeed it was. fixed.

**Comment by phinze** [comment]
<3 <3
