### ISSUE TITLE
Support for CloudFoundry based PaaS (eg. IBM Bluemix) ?

### ISSUE THREAD

**Issue by shhaed100** [hashicorp/terraform#10725]
Are there any plans to support CloudFoundry based PaaS providers like IBM Bluemix ?

**Comment by stack72** [comment]
Hi @shhaed100 

There is an open PR for a cloudfoundry provider - #10385

please keep an eye on that for updates

Thanks

Paul

**Comment by mevansam** [comment]
#10385 has been closed and re-opened as #11057. Please visit that if you would like to download development builds and review the provider documentation.
