### ISSUE TITLE
SNS Topic trigger for lambda issue

### ISSUE THREAD

**Issue by varet** [hashicorp/terraform#10748]
Hey there,
I have an issue with SNS Topic and lambdas.

I do create a lambda function, then an sns topic and in the end an subscription using: aws_sns_topic_subscription

the problem is the Lambda doesn't register this under it's trigger, and with this missing I cannot get any lambda triggering.

**Comment by Ninir** [comment]
Hi @varet 

Sorry for the annoyance here. Did you add a `aws_lambda_permission` resource too?

As in:

```hcl
resource "aws_sns_topic" "topic" {
  name = "mytopic"
}

resource "aws_sns_topic_subscription" "topic_lambda" {
  topic_arn = "${aws_sns_topic.topic.arn}"
  protocol  = "lambda"
  endpoint  = "${aws_lambda_function.lambda.arn}"
}

resource "aws_lambda_function" "lambda" {
  filename         = "lambda.zip"
  function_name    = "lambda-handler"
  role             = "${aws_iam_role.cloudwatch_alarms_lambda.arn}"
  handler          = "entrypoint.lambda_handler"
  runtime          = "python2.7"
  source_code_hash = "..."

  environment {
    variables {
      env = "${var.stack}"
    }
  }
}

resource "aws_lambda_permission" "with_sns" {
    statement_id = "AllowExecutionFromSNS"
    action = "lambda:InvokeFunction"
    function_name = "${aws_lambda_function.lambda.arn}"
    principal = "sns.amazonaws.com"
    source_arn = "${aws_sns_topic.topic.arn}"
}

...
```

The `aws_lambda_permission.with_sns` will allow SNS to call Lambda :)

Tell me how it goes!

**Comment by iangelov** [comment]
Thank you, @Ninir, I had the same problem - your solution worked brilliantly, just needed to add the "aws_lambda_permission" resource and to taint the "aws_sns_topic_subscription" resource - otherwise simply granting the permission won't work.

**Comment by stack72** [comment]
Closing this since this is no longer an issue

**Comment by khotkevych** [comment]
Should `function_name = "${aws_lambda_function.lambda.arn}" ` be `function_name = "${aws_lambda_function.lambda.function_name}" ` for `aws_lambda_permission`? :smiley:

**Comment by aaron-ballard-530** [comment]
Can this information be added to the documentation for SNS?  The automagic that the console does behind the scenes masks the permissions that are needed for lambda
