### ISSUE TITLE
invalid or unknown key: pgp_key

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#10756]
### Terraform Version
0.7.13 (works in 0.8.1 though).

### Affected Resource(s)
- aws_iam_access_key

### Terraform Configuration Files
Example at https://www.terraform.io/docs/providers/aws/r/iam_access_key.html

### Expected Behavior
Key to be created.

### Actual Behavior
Error with:
```
  * aws_iam_access_key.lb: : invalid or unknown key: pgp_key
```

### Steps to Reproduce
1. `terraform apply`

**Comment by stack72** [comment]
Hi @FransUrbo 

This was a feature just added in the 0.8 release so it won't work in 0.7.13

Thanks

Paul

**Comment by FransUrbo** [comment]
Can such information be included in the documentation?

**Comment by stack72** [comment]
Hi @FransUrbo 

We are going to give our documentation an overhaul at some point - the general rule, is that the documentation on the terraform.io website relates to the terraform latest release (in this case 0.8.1)

We *usually* have this type of info in the changelog as well - that's a rich source of documentation for new features / deprecations

Paul
