### ISSUE TITLE
Improve documentation for aws_iam_access_key

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#10752]
The documentation example for `aws_iam_access_key` (https://www.terraform.io/docs/providers/aws/r/iam_access_key.html) creates a user and a access key, but the property `pgp_key` say

```
  pgp_key = "keybase:some_person_that_exists"
```

Then the documentation for `pgp_key` talks about `keybase:username`.

Shouldn't the example then read:

```
  pgp_key = "keybase:lb"
```

?

**Comment by jen20** [comment]
Hi @FransUrbo! Thanks for opening an issue. There is no requirement for the username on keybase to be the same as the name of the IAM user (or the name of the logical resource in Terraform). Separately from that, raw PGP public key material can be used in place of a keybase lookup, and it will likely be extended to other public directory services if they become available.

The change I think you're proposing conflates these - is there some other way that we could make this more understandable without conflating the different names involved? For example, we could change the example and the argument reference to refer to `keybase:keybase_username` or similar. This change probably also wants rolling out to `aws_iam_user_login_profile` also.

**Comment by FransUrbo** [comment]
I'm fine with that. My point was just that the two parts seemed to conflict slightly. 

Using the same example in all places will avoid ambiguity.

For example, it uses different `name` entries

```
resource "aws_iam_user" "lb" {
  name = "loadbalancer"
  path = "/system/"
}

resource "aws_iam_user_policy" "lb_ro" {
  name = "test"
  user = "${aws_iam_user.lb.name}"
}
```

instead of using something like

```
resource "aws_iam_user" "loadbalancer" {
  name = "loadbalancer"
  path = "/system/"
}
resource "aws_iam_user_policy" "loadbalancer_ro" {
  name = "loadbalancer_ro"
  user = "${aws_iam_user.loadbalancer.name}"
}
```

I know that there's technically no correlation between the resource name and ... whatever `name` is for (the AWS resource name?), but keeping them "the same" simplifies understanding.

This goes for my main point [of this issue] as well:

```
resource "aws_iam_access_key" "lb" {
  user    = "${aws_iam_user.lb.name}"
  pgp_key = "keybase:some_person_that_exists"
}
[...]
pgp_key - (Optional) Either a base-64 encoded PGP public key, or a keybase username in the form keybase:username.
```

Either use `username` in both examples, OR `some_person_that_exists` in both. Also, by trial and error, I actually figured out that it actually needs to be a _user_ (a **person**), not a role and what not - we need to attach the key to a someone, not something. A note about that would be nice to.
