### ISSUE TITLE
docker provider with tls support

### ISSUE THREAD

**Issue by dodwmd** [hashicorp/terraform#10754]
Trying to run against a docker server that has tls/certs setup with 0.8.0 and 0.8.1 doesn't work. Works fine in 0.7.13.

### Terraform Version
$ ./terraform_0.8.1 version
Terraform v0.8.1

### Affected Resource(s)
docker provider with tls support

### Terraform Configuration Files
```hcl
provider "docker" {
  cert_path = "./certs/"
  host = "tcp://docker.local:2376/"
}
```

### Steps to Reproduce
Dteps required to reproduce the issue:

$ mkdir certs
Put ca.pem, cert.pem key.pem in certs dir.
$ echo > provider.tf << EOF
provider "docker" {
  cert_path = "./certs/"
  host = "tcp://test.local:1234/"
}
$ ./terraform_0.8.1 apply
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * provider.docker: "ca_material": conflicts with cert_path ("./certs/")
  * provider.docker: "cert_material": conflicts with cert_path ("./certs/")
  * provider.docker: "key_material": conflicts with cert_path ("./certs/")

**Comment by hmcgonig** [comment]
I can confirm that I'm seeing this as well. Seems to be happening since the addition of https://github.com/hashicorp/terraform/pull/10151.

**Comment by mkuzmin** [comment]
I'm looking into this.

As a quick workaround you can switch to the new schema:
```
provider "docker" {
  cert_material = "${file("certs/cert.pem")}"
  key_material = "${file("certs/key.pem")}"
  ca_material = "${file("certs/ca.pem")}"
}
```

But that's definitely a bug, and I will fix it ASAP.

**Comment by dodwmd** [comment]
Confirmed that workaround works.

**Comment by gregzuro** [comment]
Looks like https://github.com/hashicorp/terraform/commit/7a599717771c5113a36a22c9037ef66be756c3fb broke the workaround?

**Comment by mkuzmin** [comment]
Both options should work correctly now. If you experience problems, please open a separate issue, and provide details.

Thanks
