### ISSUE TITLE
Add support for AWS CodeBuild projects

### ISSUE THREAD

**Issue by bacoboy** [hashicorp/terraform#10764]
It would be nice if I could manage AWS [CodeBuild](https://aws.amazon.com/documentation/codebuild/) project configurations with Terraform.

So, opening an enhancement request.

**Comment by stack72** [comment]
#10633

**Comment by imyousuf** [comment]
@stack72 Hi. Is there any update on when the PR would be merged?

**Comment by stack72** [comment]
This has been implemented as part of Terraform 0.8.6 - #11560
