### ISSUE TITLE
aws_autoscaling_group shourd take the same 'tags' param that aws_elb does

### ISSUE THREAD

**Issue by pccowboy** [hashicorp/terraform#10775]
I know it seems like a nit, but a consistent tags param seems like a given?

Currently, an aws_autoscaling_group tags a set of tag blocks:
```
  tag {
    key                 = "foo"
    value               = "bar"
    propagate_at_launch = true
  }

  tag {
    key                 = "lorem"
    value               = "ipsum"
    propagate_at_launch = false
  }
```

This is out of line with many other Terraform AWS providers, which take blocks like:
```
  tags {
    Name = "foobar-terraform-elb"
  }
```

**Comment by catsby** [comment]
Hey @pccowboy – I totally agree they should be consistent, and for just about every AWS resource, they are. However, the AutoScaling API offers it's own special case of tag, with additional parameters, namely `propagate_at_launch`, which specifies if the provided tag should be added to any instance that is created by this ASG. Without this, there's is no good way to indicate that you'd like those instances to have the tag in question, as opposed to tagging the ASG itself. 

Here are the corresponding Data Types in the AWS API docs:

- http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_Tag.html
- http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Tag.html

Each service has it's own `tag`, and most are just a copy of EC2's tag, but here you see some are not.

**Comment by pccowboy** [comment]
Fully understood that there are some tag elements that are special butterflies.  terraform has a chance to make up for some of the lack of architectural consistency in the AWS API, though, so in these instances why not use the tags object as a function, something like: 
```
  tags(propagate_at_launch=true, some_other_aws_special_overload="who knows") {
    Name = "foobar-terraform-elb",
    datacenter = "somewhere_over_the_rainbow"
  }
```

Which then generates the equivalent of:
```
  tag {
    key                 = "Name"
    value               = "foobar-terraform-elb"
    propagate_at_launch = true
    some_other_aws_special_overload= "who knows"
  }

  tag {
    key                 = "datacenter"
    value               = "somewhere_over_the_rainbow"
    propagate_at_launch = true
    some_other_aws_special_overload= "who knows"
  }
```

That gives me choices to manage my infrastructure - with a minimum of code when possible, and when I need to dive into AWS overloading of functionality into metadata, I can do that too.

I mean, I can do it with {jsonnet|python|whatever}, but being able to manage this within the providers/HCL seems a better solution to me?
