### ISSUE TITLE
Support for AWS Workspaces

### ISSUE THREAD

**Issue by mootpt** [hashicorp/terraform#10794]
Support for AWS Workspaces would be great, especially since there is existing support for AWS directory service directories in Terraform. Something like:

```
resource "aws_workspaces_workspace" {
  bundle_id              = "Some Bundle Id Here"
  directory_id           = "${aws_directory_service_directory.bar.id}"
  user_name              = "foo"
  root_volume_encryption = true,
  user_volume_encryption = false,
  volume_encryption_key  = "${aws_kms_key.foo.key_id}"
}
```

Ideally it would be nice to also have a `aws_workspaces_bundle` resource, but I'd settle for the former.

**Comment by liamjbennett** [comment]
I have done most of the work for this here: https://github.com/hashicorp/terraform/pull/7806 however it was blocked due to a missing API allowing you to register your directory service for use with workspaces.

**Comment by bsft-it-git** [comment]
@liamjbennett, I noted some feature announcements that I thought might mean some of the gaps in the APIs have been filled:

https://aws.amazon.com/about-aws/whats-new/2017/02/amazon-workspaces-now-supports-interforest-trusts-in-aws-directory-service-for-microsoft-active-directory-enterprise-edition/

**Comment by liamjbennett** [comment]
@bsft-it-git sadly not. I am keeping an eye on this issue very closely and I know the missing API is on the backlog for the workspaces team.

**Comment by cmaxwellau** [comment]
@liamjbennett

I work for AWS, and have a customer that would like to use terraform for workspaces. 

Would one of you be able to concisely describe the issue for me so that I can pass it on to the service teams?
Cam

**Comment by liamjbennett** [comment]
@cmaxwellau it’s a missing api for registration of the directory which prevents us writing tests for the terraform resources.

I raised this as a forum post in 2016 with reference to the internal api: https://forums.aws.amazon.com/thread.jspa?messageID=749994&#749994

As I understand it, this may actually be more the responsibility of the ADS team not the Workspaces team.

**Comment by pjohnstonv** [comment]
wot

**Comment by coderwearsprada** [comment]
Any updates on this topic?

**Comment by bflad** [comment]
Hi Folks 👋 

Since Terraform 0.10, Terraform providers (e.g. AWS resources within Terraform) are no longer distributed as part of Terraform Core and have their own release cadence. For this issue in particular, it was migrated to https://github.com/terraform-providers/terraform-provider-aws/issues/434, but the comment from the GitHub bot is missing 😖. You can follow that issue for additional updates.

I am going to lock this issue as it is no longer applicable to this repository and has a migrated issue for tracking.
