### ISSUE TITLE
Feature request: splat usage in output-ing a map

### ISSUE THREAD

**Issue by chrisrlong** [hashicorp/terraform#10795]
Hi there,

### Terraform Version
0.8.1 Windows AMD64

### Affected Resource(s)
Please list the resources as a list, for example:
- output

### Terraform Configuration Files
I would like to do this:
```hcl
output "azs_public_subnets_map" {
  value = "${
    map(
      "${aws_subnet.public.*.availability_zone}", "${aws_subnet.public.*.id}",
    )
  }"
}
```

But have to manually set the numbered values
```hcl
output "azs_public_subnets_map" {
  value = "${
    map(
      "${aws_subnet.public.0.availability_zone}", "${aws_subnet.public.0.id}",
      "${aws_subnet.public.1.availability_zone}", "${aws_subnet.public.1.id}",
    )
  }"
}
```

### Expected Behavior
When using the splat no output is made. I would like the same output as the second code snip but without having to state the count number.

### Actual Behavior
No out put is made.

### Steps to Reproduce

1. `terraform apply`

**Comment by mitchellh** [comment]
It seems reasonable that we support a map construction function that takes a list of keys and a list of values, tagged as enhancement.

**Comment by apparentlymart** [comment]
@mitchellh isn't that what the `zipmap` function does?

**Comment by mitchellh** [comment]
@apparentlymart Yep, yep it does. Didn't know that exists. There you go!

**Comment by chrisrlong** [comment]
I didn't find that either great work guys!
