### ISSUE TITLE
aws_autoscaling_attachment resource not shown in documentation sidebar

### ISSUE THREAD

**Issue by brbbs** [hashicorp/terraform#10800]
The aws_autoscaling_attachment resource was added in #9146 but it is not shown in the sidebar at https://www.terraform.io/docs/providers/aws/index.html. However, the documentation is directly navigable at https://www.terraform.io/docs/providers/aws/r/autoscaling_attachment.html.

**Comment by stack72** [comment]
Hi @brbbs 

This is closed via #10809 

Apologies for this! I will push it to the website right now

Paul
