### ISSUE TITLE
aws kms_key_id input validation doesn't allow empty string 

### ISSUE THREAD

**Issue by danielnbarbosa** [hashicorp/terraform#10806]
### Terraform Version
Terraform v0.8.1

### Affected Resource(s)
any resource that accepts a `kms_key_id` argument

### Terraform Configuration Files
```hcl
variable "kms_key_ids" {
  type        = "map"
  description = "if storage_encrypted == 'false' then kms_key_ids = '' "

  default = {
    "false" = ""
  }
}

resource "aws_db_instance" "papi" {
  identifier              = "${var.environment_name}-papi"
  allocated_storage       = "${var.papi_rds_allocated_storage}"
  engine                  = "mysql"
  instance_class          = "${var.papi_rds_instance_class}"
  storage_type            = "gp2"
  storage_encrypted       = "${var.papi_rds_storage_encrypted}"
  kms_key_id              = "${lookup(var.kms_key_ids, var.papi_rds_storage_encrypted, aws_kms_key.papi_rds.arn)}"
  multi_az                = "${var.papi_rds_multi_az}"
  name                    = "xxxxxxxx"
  username                = "xxxxxxxx"
  password                = "${var.papi_rds_password_admin}"
  backup_retention_period = 30
  publicly_accessible     = false
  vpc_security_group_ids  = ["${aws_security_group.papi_rds.id}"]
  parameter_group_name    = "${aws_db_parameter_group.papi.name}"
  db_subnet_group_name    = "${aws_db_subnet_group.papi.name}"
  skip_final_snapshot     = "${var.papi_rds_skip_final_snapshot}"
  maintenance_window      = "${var.papi_rds_maintenance_window}"
  backup_window           = "${var.papi_rds_backup_window}"
}
```

Note that the above lookup can now be done more elegantly using a conditional like:
```hcl
  kms_key_id              = "${var.papi_rds_storage_encrypted ? aws_kms_key.papi_rds.arn : ""}"
```

### Expected Behavior
Plan should succeed.

### Actual Behavior
```
Error running plan: 1 error(s) occurred:

* module.named_common.aws_db_instance.papi: "kms_key_id" doesn't look like a valid ARN ("^arn:aws:([a-zA-Z0-9\\-])+:([a-z]{2}-[a-z]+-\\d{1})?:(\\d{12})?:(.*)$"): ""
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
This is being done because I configure the databases differently depending on the environment.  In this case the RDS databases are encrypted in prod but not in dev.  `storage_encrypted` is configured with a variable so `kms_key_id` should only be set to an ARN if `storage_encrypted` is true.  If it is false then setting `kms_key_id` to an empty string works fine.  At least it did until the input validation requiring an ARN format was added.  The easy fix would be for the `kms_key_id` input validation to also allow an empty string as well.

Note that I tried many different ways to work around this issue but could not get anything to work.  I have other modules that depend on the attributes of `aws_db_instance` so it's not straightforward to create duplicate resources, one for the unencrypted databases and one for the encrypted ones.

**Comment by Ninir** [comment]
Hi @danielnbarbosa 

Sorry for the noise here.

As `""` is a valid value, the code tries to validate it... conditional expressions make stacks even more flexible, but there are drawbacks, as this issue :)

Passing `null` would have been the `code` way, or using [If gotchas] also.

In this case, I made a PR about ignoring empty values for kms_key attributes, and only for this case.

Ninir

**Comment by danielnbarbosa** [comment]
thanks @Ninir.  you made my day!

**Comment by mpas** [comment]
@Ninir Just being curious, i am facing the same issue as @danielnbarbosa, getting the `"kms_key_id" doesn't look like a valid ARN` We are trying to migrate to v0.8.2. What would be a `code` way or a using something else? The following **obviously** does not work, but i am trying to find /learn on how i can do this.

` kms_key_id = "${var.rds_encrypt == "true" ? var.rds_encryption_key : "null"}"`

**Comment by stack72** [comment]
Hi @mpas 

The code to include the validation was only merged 8 days ago - therefore, it will only make it into terraform 0.8.3

Paul

**Comment by mpas** [comment]
@stack72 Thanks for the tip! I was also trying to understand how this could be done without waiting for 0.8.3. Just for educational purpose.

**Comment by stack72** [comment]
oh i see, my apologies :) You won't have to wait too long for 0.8.3 - we expect within the week

**Comment by mpas** [comment]
@stack72 no problem! I will pick up 0.8.3 asap :)

**Comment by danielnbarbosa** [comment]
thanks guys!  am very happy to have this in 0.8.3.
