### ISSUE TITLE
changing aws_db_instance subnet group forces new resource

### ISSUE THREAD

**Issue by khadrin** [hashicorp/terraform#10811]
Hi. 

### Terraform Version
`Terraform v0.8.1`

### Affected Resource(s)
- aws_db_instance (postgres)

### Terraform Configuration Files
Can create a small test case if necessary.

### Debug Output
https://gist.github.com/khadrin/3efb91ce0e542d9cfe71dc4981366450

### Expected Behavior
Able to change an rds' subnet group without delete / recreate, [as documented](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.WorkingWithRDSInstanceinaVPC.html#USER_VPC.VPC2VPC) 

### Actual Behavior
Plan says forces new resource:
`    db_subnet_group_name:             "currents-test-db-subnet-group" => "${aws_db_subnet_group.group2.id}" (forces new resource)
`

### Steps to Reproduce
1. Create an RDS with terraform
2. Change the subnet group

### References
This issue is similar
- GH-9157

**Comment by stack72** [comment]
Hi @khadrin 

Thanks for the issue report on this - this is closed via #10818 

This will make the next release of Terraform

Thanks

Paul
