### ISSUE TITLE
Mismatch reason: extra attributes: s3_object_version

### ISSUE THREAD

**Issue by walid-halabi-myob** [hashicorp/terraform#10827]
Hi! I got here something that you Terraform folk insist is a bug with the latest version of Terraform, so hope this helps. Let me know if there's any further info you need.

### Terraform Version
0.8.1

### Affected Resource(s)
- aws_s3_bucket_object

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket" "deployment" {
  bucket = "${var.deployment_bucket_name}"
  acl = "private"
  versioning {
    enabled = true
  }
}

resource "aws_s3_bucket_object" "bundle" {
  bucket = "${aws_s3_bucket.deployment.id}"
  key = "${var.deployment_bundle_name}"
  source = "${var.deployment_bundle_path}"
  etag = "${md5(file("${var.deployment_bundle_path}"))}"
}

resource "aws_s3_bucket" "deployment_alternative" {
  provider = "aws.alternative"

  bucket = "${var.deployment_bucket_name}-${var.step_functions_region}"
  acl = "private"
  versioning {
    enabled = true
  }
}

resource "aws_s3_bucket_object" "bundle_alternative" {
  provider = "aws.alternative"

  bucket = "${aws_s3_bucket.deployment_alternative.id}"
  key = "${var.deployment_bundle_name}"
  source = "${var.deployment_bundle_path}"
  etag = "${md5(file("${var.deployment_bundle_path}"))}"
}

resource "aws_lambda_function" "create_batch_lambda" {
  s3_bucket = "${aws_s3_bucket.deployment.id}"
  s3_key = "${aws_s3_bucket_object.bundle.id}"
  s3_object_version = "${aws_s3_bucket_object.bundle.version_id}"
  function_name = "create_batch"
  role = "${aws_iam_role.create_batch_lambda.arn}"
  handler = "createBatch.handle"
  runtime = "nodejs4.3"
  memory_size = "128"
  timeout = "10"
  environment {
    variables = {
      STATE_MACHINE_ARN = "${data.null_data_source.step_function_arn.inputs.value}"
    }
  }
}
```

### Debug Output
https://gist.github.com/walid-halabi-myob/46268b7220b842e474d66f225e3495bc

### Panic Output
N/A

### Expected Behavior
The apply should complete successfully

### Actual Behavior
The apply fails with the output above

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The one thing we think might contribute: we're trying to configure two different S3 buckets, in different regions, but with the same key, source, and etag

### References
N/A

**Comment by jbardin** [comment]
Hi @walid-halabi-myob,

Do you have more config that what you've provided to reproduce this issue? The error output is from an error applying the `aws_lambda_function.create_batch_lambda` config, which isn't shown here.

**Comment by walid-halabi-myob** [comment]
Hi James, sorry about that, I updated the issue to include the lambda resource

**Comment by mitchellh** [comment]
I'm unable to determine steps to properly reproduce this. It appears that during plan and then apply the s3_object_version does indeed change so I think this error is correct and protecting you from some behavior but I'm not sure what is causing it.

Do you have any idea what might be causing that to change?

**Comment by walid-halabi-myob** [comment]
Hey Mitchell, thanks for the reply,

I might need to return to this after the break period, depending on time available

**Comment by mitchellh** [comment]
Hey @walid-halabi-myob. If you get back to it feel free to just open a new issue! Thanks!
