### ISSUE TITLE
How to send access keys to you for new provider of Alicloud

### ISSUE THREAD

**Issue by xiaozhu36** [hashicorp/terraform#10829]
Hi Terraform Group,

A few days ago, I had pulled request(https://github.com/hashicorp/terraform/pull/10761 ) about Alicloud provider that our team is developing. Although, the PR was executed failed in the testing, our team has found problems and is improving it. 

Considering acceptance tests often cost money to run, our team intends to provide access keys of Alicloud to you and help you to run acceptance tests using it conveniently. Could you provide me an email address or other contacts and I send the access keys to you by it?

**Comment by stack72** [comment]
Hi @xiaozhu36 

Please can you email on stack72 at hashicorp.com and we can take care of it?

Thanks

Paul

**Comment by xiaozhu36** [comment]
Hi  @stack72 

I am very appreciate of your reply, and I will send alicloud access keys to you when the next PRs.

Thanks

Guimin He

**Comment by xiaozhu36** [comment]
Hi @stack72 

I am going to pull a new request. Considering access keys security, I had sent a confirm email. Could you please confirm it? 

Thanks

Guimin He

**Comment by stack72** [comment]
got the email and responded :)
