### ISSUE TITLE
Add support for aws/cloudformation

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1083]
This may sound a bit silly as CF & TF are two competing products with similar functionality, but it is imo not.

As [there's support](https://github.com/awslabs/aws-sdk-go/blob/master/gen/cloudformation/cloudformation.go) in the new aws library we recently started using, I was thinking this could be a great chance to allow users to run/update/delete CF templates from terraform, which could make any transition from CF to terraform much more smooth.

Example of a new resource:

```ruby
resource "aws_cloudformation_template" {
  on_failure = "ROLLBACK"
  parameters {
    firstKey = "first-value"
    secondKey = "second-value"
  }
  stack_name = "sample-name"
  template_body = "${file(cf-templates/my-stack.json)}"
}
```

Eventually having the templating functionality at some point, Terraform could completely replace both [`cotdsa/cumulus`](https://github.com/cotdsa/cumulus) & [`cloudtools/troposphere`](https://github.com/cloudtools/troposphere) which I've seen people using to work around issues that CloudFormation has.

**Comment by mitchellh** [comment]
This actually makes sense to me. Terraform shouldn't discriminate against an AWS API because it seems to compete. Terraform should be able to managed all IaaS, PaaS, SaaS so interfacing with allowing you to CRUD CloudFormation makes sense.

**Comment by s0enke** [comment]
+1 as TF could work as a wrapper and glue language around existing CloudFormation setups which opens it to more potential users.

**Comment by jlordiales** [comment]
+1, this would make the transition from those huge, impossible to maintain CF templates a lot easier and safer.

**Comment by abhishektomar** [comment]
+1, There are few resources for which I am writing CF templates(because terraform doesn't support them), it would be great if I could use terraform to manage CF templates.

**Comment by phinze** [comment]
Hey folks - we're consolidating Requests for AWS resources over in the spreadsheet linked at #28 - head over there to record your username on what you'd like us to prioritize next!

**Comment by ejholmes** [comment]
For people that come to this from google, this was implemented in https://github.com/hashicorp/terraform/pull/2636. Nice job @radeksimko!
