### ISSUE TITLE
[Feature Request] GKE: Allow cluster version to be specified

### ISSUE THREAD

**Issue by unguiculus** [hashicorp/terraform#10831]
Please allow the cluster version to be specified for Google Container Clusters. Currently, GKE supports Kubernetes 1.4.7 and 1.5.1 for new clusters, the default still being 1.4.7. We need to spin up a 1.5.1 cluster and cannot do this with Terraform right now.

Here's the command-line for doing this with `gcloud`:

`gcloud container clusters create --cluster-version=1.5.1`

**Comment by cblecker** [comment]
Hi @unguiculus --
I believe this was fixed by #10817. The `node_version` attribute wasn't being used at cluster creation time, so if you specified it, it would always create the cluster at the GKE default.. except this would block upgrades if the GKE default was lower than the version you asked for.

As such, I believe this should be fixed whenever terraform 0.8.2 is released. :)

**Comment by unguiculus** [comment]
Hi @cblecker,
Indeed, this fixes the problem, thanks. Actually I thought, we'd have to distinguish between `node_version` and `master_version`. On cluster creation, it probably does not make sense to differentiate, but how about updates? With your fix, only nodes updates are supported but, even though GKE updates masters automatically, it is very well possible to trigger that explicitly if you don't want to wait for Google to do it. Terraform only sets `DesiredNodeVersion` while there is also `DesiredMasterVersion`. Using `gcloud` you'd do this to upgrade your master:

`gcloud container clusters upgrade CLUSTER_NAME --master`

See https://cloud.google.com/container-engine/docs/clusters/upgrade#opt-in_early_master_upgrades

**Comment by unguiculus** [comment]
@cblecker I just created PR #10856 updating the docs for `node_version`.

**Comment by cblecker** [comment]
As that link points out though, master versions are automatic, and can't be triggered to a specific version. You can opt in earlier than the auto upgrade cycle, but you can't manually specify a version higher or lower than default with that command.

Right now `node_version` is hooked into [initialClusterVersion](https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters#Cluster) and [desiredNodeVersion](https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters/update#ClusterUpdate). `desiredMasterVersion`  only has one valid value -- the latest supported version. As such, we can't link it in directly to that field.

**Comment by unguiculus** [comment]
OK, I guess you're right. Thanks. I'm closing this.

**Comment by cblecker** [comment]
FYI, Terraform 0.8.2 went out yesterday and this fix was included :)
