### ISSUE TITLE
aws_iam_policy_document json changing

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#10853]
I've stumbled across a peculiar bug which I think has to do with the use of `ignore_changes` on a computed field. I am able to reproduce this bug using the Terraform configuration:

```
data "aws_iam_policy_document" "role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "role" {
  name_prefix        = "${var.name_prefix}-"
  assume_role_policy = "${data.aws_iam_policy_document.role.json}"

  lifecycle {
    ignore_changes = ["name"]
  }
}

variable "name_prefix" {
  type = "string"
}
```

First, run `terraform apply -var name_prefix=foo`. Next, run `terraform plan -var name_prefix=bar`. Terraform shows the following changes to be applied:

```
~ aws_iam_role.role
    assume_role_policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"ec2.amazonaws.com\"\n      }\n    }\n  ]\n}"
```

**Comment by mitchellh** [comment]
I'm not convinced this has to do with the ignore changes. I think this is just the JSON of the policy actually changing for some reason. I'm going to retag as an AWS issue to look into it.

**Comment by joshuaspence** [comment]
Running `terraform plan -var name_prefix=foo` instead of `terraform plan -var name_prefix=bar` shows no changes at all, which is what makes me think it has to do with `ignore_changes` or `name_prefix`.

**Comment by mitchellh** [comment]
Thanks @joshuaspence, I agree I can reproduce this weirdly with `ignore_changes` but the reason this is happening at its core is because we're not generating the diff properly to begin with. That's the root cause that is surfacing itself in weird ways as part of ignore_changes. :) 

What we need to do here is normalize the JSON in some way to prevent this diff.

**Comment by joshuaspence** [comment]
Ah ok, makes sense.

**Comment by JeanFred** [comment]
I can confirm this behaviour.

While I did not really care for policies for S3 buckets as the non-change was pretty much instantaneous, I am provisioning `aws_elasticsearch_domain` for which any operation typically takes 15min − making this no-op a bit of an issue :)
