### ISSUE TITLE
AWS block device seems to be missing a parameter

### ISSUE THREAD

**Issue by kendawg2** [hashicorp/terraform#1085]
When I use the following:

block_device {
  	device_name = "/dev/sdf"
  	volume_type = "io1"
  	volume_size = 150
  	delete_on_termination = "false"
	}

I get an error on terraform apply stating that an IOPS parameter must be specified when "io1" is specified as a volume type.   There does not seem to be key to enter it in.   I tried adding "iops = 4000" but it rejects the parameter.   Is there another way to specify IOPS in a block device?

**Comment by mitchellh** [comment]
This should get fixed by #1045. @phinze?

**Comment by phinze** [comment]
Ah no, not yet. This is a good catch. I'll get it added to #1045

**Comment by catsby** [comment]
Support for setting `iops` was added in #1045, closing
