### ISSUE TITLE
Datadog provider include_tags default does not match documentation

### ISSUE THREAD

**Issue by jaygorrell** [hashicorp/terraform#10855]
### Terraform Version
0.7.10

### Affected Resource(s)
- datadog_monitor

### Expected Behavior
Creating a datadog_monitor resource without `include_tags` should match the documented expectations of defaulting to `true`.

### Actual Behavior
`include_tags:        "false"`

**Comment by stack72** [comment]
Hi @jaygorrell 

Sorry for this issue here - this has since been updated and can be closed :)

Paul
