### ISSUE TITLE
Terraform fails when Neutron is in a PENDING_UPDATE state 

### ISSUE THREAD

**Issue by mrantipyrine** [hashicorp/terraform#10852]
Environment:
```
Terraform v0.8.0
go version go1.6.2 darwin/amd64
```

```openstack_lb_member_v2```

main.tf
```
provider "openstack" {
  auth_url    = "${var.region != "dev" ? var.auth_url["prod_url"] : var.auth_url["dev_url"]}"
  domain_name = "${var.region != "dev" ? var.domain_name["prod_domain"] : var.domain_name["dev_domain"]}"
  tenant_name = "bnet-classic"
  insecure    = "true"
}

data "template_file" "userdata" {
  template = "$${file("${path.module}/userdata.tpl")}"

  vars {
    role = "${var.role}"
  }
}

resource "openstack_compute_instance_v2" "instance" {
  region          = "${var.region}"
  count           = "${var.instance_count["${var.role}"]}"
  name            = "${format("%s-cg-ncs-%s%02d", "${var.region_prefix}", "${var.role}", count.index + 1)}"
  image_id        = "${var.region != "dev" ? var.image_id["prod_image"] : var.image_id["dev_image"]}"
  flavor_name     = "${var.region != "dev" ? var.flavor_name["prod_flavor"] : var.flavor_name["dev_flavor"]}"
  security_groups = ["default"]

  network = {
    name = "${var.role != "gateway" ? var.network_name["internal"] : var.network_name["floating"]}"
  }

  security_groups = ["default"]
  user_data       = "${data.template_file.userdata.rendered}"
}

output "contents" {
  value = "${data.template_file.userdata.rendered}"
}

resource "openstack_lb_member_v2" "member" {
  depends_on     = ["openstack_compute_instance_v2.instance"]
  count          = "${var.load_balancer_count["${var.role}"]}"
  subnet_id      = "${var.vip_subnet_id}"
  pool_id        = "${var.pool_id}"
  protocol_port  = "${var.protocol_port["${var.role}"]}"
  admin_state_up = "true"
  region         = "${var.region}"
  address        = "${element(openstack_compute_instance_v2.instance.*.access_ip_v4, count.index)}"
}
```

variables.tf
```
variable "auth_url" {
  type = "map"

  default = {
    dev_url   = "https://dev.keystone.xxx.net:5000/v3"
    prod_url = "https://keystone.xxx.net:5000/v3"
  }
}

variable "domain_name" {
  type = "map"

  default = {
    dev_domain  = "development"
    prod_domain = "production"
  }
}

variable "tenant_name" {
  default = "classic"
}

variable "role" {
  default       =  "datastore"
  description = "Instance role"
}

variable "region" {
  default = "dev"
  description = "Tenant region"
}

variable "region_prefix" {
  default = "dev81b"
  description = "Site name"
}

variable "image" {
  default = "centos7.2-latest"
}

variable "flavor_name" {
  type = "map"

  default = {
    dev_flavor  = "t2.medium"
    prod_flavor = "m4.large"
  }
}

variable "instance_count" {
  default = "1"
  description = "Number of instances"
}

variable "network_name" {
  default = "classic-internal-net"
}
```

Error:
```
* openstack_lb_member_v2.member.2: Error creating OpenStack LBaaSV2 member: Expected HTTP response code [201 202] when accessing [POST http://dev.neutron.cloud.xxx:9696/v2.0/lbaas/pools/d90a6b80-92ea-4478-9576-16dcc70b8511/members], but got 409 instead
{"NeutronError": {"message": "Invalid state PENDING_UPDATE of loadbalancer resource 50748818-e2f6-4306-b20a-0cdcecf79565", "type": "StateInvalid", "detail": ""}}
```

Neutron will lock a resource into one of many PENDING_* states to avoid concurrent changes, which typically is not a problem, but there are edge cases where a load balancer will briefly be in a "PENDING_UPDATE" state, which causes the deployment to fail. Since the resource is technically available Terraform should attempt to recreate the resource rather than failing. This makes large scale deployments extremely difficult as there is no way to throttle how many resources are created at a given time, nor does Terraform provide the ability to add an arbitrary wait during resource creation.

**Comment by jtopjian** [comment]
@mrantipyrine Thanks for the report. Coincidentally I'm cleaning up some tests for LBaaS v2 right now.

409 statuses are pretty common with Neutron resources and they're accounted for in a lot of other places, so this should be an easy fix. 

Would you be able to update your `main.tf` example to include all of the LB resources?

**Comment by mrantipyrine** [comment]
Copy and paste fail on my part! I updated ```main.tf```. Let me know if you need anything else.

**Comment by jtopjian** [comment]
I think that should be good -- thanks!

**Comment by mrantipyrine** [comment]
I think this should fix the problem though I probably missing something
```
builtin/providers/openstack/resource_openstack_lb_member_v2.go 
diff --git a/builtin/providers/openstack/resource_openstack_lb_member_v2.go b/builtin/providers/openstack/resource_openstack_lb_member_v2.go
index 3df2182..be663f8 100644
--- a/builtin/providers/openstack/resource_openstack_lb_member_v2.go
+++ b/builtin/providers/openstack/resource_openstack_lb_member_v2.go
@@ -126,7 +126,7 @@ func resourceMemberV2Create(d *schema.ResourceData, meta interface{}) error {
        log.Printf("[DEBUG] Waiting for Openstack LBaaSV2 member (%s) to become available.", member.ID)
 
        stateConf := &resource.StateChangeConf{
-               Pending:    []string{"PENDING_CREATE"},
+               Pending:    []string{"PENDING_CREATE", "PENDING_UPDATE"},
                Target:     []string{"ACTIVE"},
                Refresh:    waitForMemberActive(networkingClient, poolID, member.ID),
                Timeout:    2 * time.Minute,
@@ -207,7 +207,7 @@ func resourceMemberV2Delete(d *schema.ResourceData, meta interface{}) error {
        }
 
        stateConf := &resource.StateChangeConf{
-               Pending:    []string{"ACTIVE", "PENDING_DELETE"},
+               Pending:    []string{"ACTIVE", "PENDING_DELETE", "PENDING_UPDATE"},
                Target:     []string{"DELETED"},
                Refresh:    waitForMemberDelete(networkingClient, d.Get("pool_id").(string), d.Id()),
                Timeout:    2 * time.Minute,
```

**Comment by jtopjian** [comment]
Interesting! Have you tried that with success? If so, that's great. It means the StateChangeConf is ignoring the unhandled 409 exception correctly.

**Comment by jtopjian** [comment]
Actually, digging into this a bit more, it looks like the existing PENDING statuses are moot. If you look at the `waitForMemberActive` and `waitForMemberDelete` functions, you'll see that the state is hard coded for ACTIVE and DELETED. This is due to a mixture of trusting the status and handling "unexpected" HTTP codes.

You can see in the `waitForMemberDelete` how the 409 is being handled. I think the same method needs to be applied to the `waitForMemberActive` function.

**Comment by mrantipyrine** [comment]
Yep, definitely missed that!

**Comment by rcreasey** [comment]
Not to necro this issue, but are these errors related?

```
* openstack_lb_member_v2.edge_2002.7: Error deleting OpenStack LBaaSV2 Member: timeout while waiting for state to become 'DELETED' (last state: 'PENDING_DELETE', timeout: 2m0s)
* openstack_lb_member_v2.edge_2002.4: Error deleting OpenStack LBaaSV2 Member: timeout while waiting for state to become 'DELETED' (last state: 'PENDING_DELETE', timeout: 2m0s)
* openstack_lb_monitor_v2.edge_icmp: Error deleting OpenStack LBaaSV2 Monitor: timeout while waiting for state to become 'DELETED' (last state: 'ACTIVE', timeout: 2m0s)
* openstack_lb_member_v2.edge_2001.12: Error deleting OpenStack LBaaSV2 Member: timeout while waiting for state to become 'DELETED' (last state: 'PENDING_DELETE', timeout: 2m0s)
* openstack_lb_member_v2.edge_2001.14: Error deleting OpenStack LBaaSV2 Member: timeout while waiting for state to become 'DELETED' (last state: 'PENDING_DELETE', timeout: 2m0s)
* openstack_lb_member_v2.edge_2001.7: Error deleting OpenStack LBaaSV2 Member: timeout while waiting for state to become 'DELETED' (last state: 'PENDING_DELETE', timeout: 2m0s)
* openstack_lb_member_v2.edge_2002.9: Error deleting OpenStack LBaaSV2 Member: timeout while waiting for state to become 'DELETED' (last state: 'PENDING_DELETE', timeout: 2m0s)
```

Is there any way to better deal with these states (ie: retries, etc), or is this just tied to the underlying go openstack api framework?

**Comment by jtopjian** [comment]
@rcreasey It's possible there's a bug with deleting members. It's also possible that it's just taking longer than 2 minutes for the member to be deleted. One of the fixes for this initial issue was a timeout increase during the create phase. Maybe the same needs done in delete.

The `PENDING_DELETE` status is set if a 409 response is received from Neutron. This usually means that the member is still in use and is waiting for other resources to let go of it. That's all determined by the Neutron server -- there's nothing the client API can do other than just patiently wait. Once a 404 is returned, then the member has been officially deleted and the status becomes `DELETED`. You can see the workflow of this [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_lb_member_v2.go#L258).

There's a new version of Terraform being released as we speak. This new version will have the ability to see the actual API requests and responses, so that might help debug your issue a bit more. Once the version is out, you can do:

```
OS_DEBUG=1 TF_LOG=DEBUG terraform apply 2>&1 | tee ~/openstack.log
```

And get a full report. Maybe give that a shot? Another option is to increase the timeout (which is hardcoded in the above linked file), compile a binary, and see if that helps. Let me know if you'd like to give that a shot. Unfortunately it's difficult for me to reproduce these kinds of scenarios in a test environment, so if your environment is able to easily hit this scenario, that's really helpful.
