### ISSUE TITLE
Interpolation in aws tag names 

### ISSUE THREAD

**Issue by chadgrant** [hashicorp/terraform#10867]
Is this expected behavior or an enhancement? I'm not sure how I can pass Tags to modules that are re-usable ?

aws_resource any {
  tags {
    "${var.tag_prefix}:environment" = "${var.environment}"
    "${var.tag_prefix}:team" = "${var.team}"
  }
}

terraform (0.8.1) plan shows :    

tags.${var.tag_prefix}:environment:          ""
tags.${var.tag_prefix}:team:                 ""

**Comment by mitchellh** [comment]
This is currently expected behavior. Map keys cannot contain interpolations. There is another issue tracking a way to try to make this possible but this isn't currently possible.
