### ISSUE TITLE
Experimental feature failed

### ISSUE THREAD

**Issue by yesteph** [hashicorp/terraform#10860]
Hi there,

I got failure with experimental feature.
Please find the error_log as enclosed file.

### Terraform Version
v0.7.13

regards
[terraform-error-1482228147.log.zip](https://github.com/hashicorp/terraform/files/663401/terraform-error-1482228147.log.zip)

**Comment by mitchellh** [comment]
This is all fixed in 0.8.1

**Comment by yesteph** [comment]
Thank you.
