### ISSUE TITLE
Dyn provider doesn't work in terraform 0.8.1

### ISSUE THREAD

**Issue by tviaud** [hashicorp/terraform#10882]
### Factoids
- Since I'm in version 0.8.1 of terraform the dyn provider is usable once in a while (like 1/50).
- If i make a PostMan request with my credentials to the dyn API I can log in and get my API token.

### Terraform Version
Terraform v0.8.1

### Affected Resource(s)
- provider "dyn"

### Debug Output
* Error setting up Dyn client: Post https://api.dynect.net/REST/Session: net/http: TLS handshake timeout

### Expected Behavior
The expected behavior is to create a dyn record.

### Actual Behavior
Can't create a record because we cannot set up the Dyn client, hence we can't use the dyn_record resource.

### Steps to Reproduce
1. `terraform apply`

**Comment by mitchellh** [comment]
Dup of #10779 we'll have it fixed for 0.8.2
