### ISSUE TITLE
aws_launch_configuration.XXX: cannot parse '' as int on volume_size

### ISSUE THREAD

**Issue by kobymeir-reposify** [hashicorp/terraform#10888]
### Terraform Version
v0.7.13

### Affected Resource(s)
Please list the resources as a list, for example:
aws_launch_configuration

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_launch_configuration" "server" {
  name_prefix          = "server~"
  image_id             = "${var.ami}"
  instance_type        = "c4.8xlarge"
  key_name             = "${var.key_name}"

  root_block_device {
      volume_type           = "gp2"
      volume_size           = 100
      delete_on_termination = true
  }

  # Data volume
  ebs_block_device {
    device_name           = "/dev/sdg"
    volume_type           = "gp2"
    delete_on_termination = "true"
    volume_size           = "${var.server_data_volume_size}"
    snapshot_id           = "${var.server_data_snapshot}"
  }

  lifecycle {
    create_before_destroy = true
  }
}

# server data volume size in GB
variable "server_data_volume_size" {
  type        = "string"
  description = "server data volume size in GB"
}

# server data volume size in GB
variable "server_data_snapshot" {
  type        = "string"
  description = "server data volume size in GB"
}
```

env1.tfvars
```hcl
server_data_volume_size = "100"
# Using a blank EBS
server_data_snapshot = ""
```

env2.tfvars
```hcl
server_data_volume_size = ""
# Using snapshot
server_data_snapshot = "snap-XXX"
```

### Debug Output
  * aws_launch_configuration.server: cannot parse '' as int: strconv.ParseInt: parsing "": invalid syntax

### Panic Output
NA

### Expected Behavior
What should have happened? 
I'm using terraform for multiple deployment to launch servers in environment 1 (env1.tfvars) the launch configurations is setuped to use a blank EBS without a snapshot, this configuration is working properly.
The environment 2 (env2.tfvars) which produced the error is setuped to use a snapshot thus setting the EBS data size to be used from the snapshot (which may differ from env1.tfvars configured size) the problem is terraform is trying to parseInt the value within `volume_size` ,what is should do is ignore it if it's empty and consider it as not being passed, which is exactly what happens on `snapshot_id` configuration if it's not passed.

### Actual Behavior
What actually happened? Terraform prints the output error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
AWS VPC

### References
None

**Comment by mitchellh** [comment]
There is another issue tracking this (an enhancement request): there is no way to set the absence of a value currently via variables. You can only set blank which is not a valid integer. Closing as a dup. I'm sorry I don't have the other one on hand.
