### ISSUE TITLE
depends_on module not working as expected

### ISSUE THREAD

**Issue by hafizullah** [hashicorp/terraform#10883]
Hi 
I was looking forward to using the `depends_on` module feature [[10076](https://github.com/hashicorp/terraform/pull/10076)].

However it is not working as expected I think.

**So my setup:**
I have two modules, `network` and `environment`

In the `environment` module I have some resources defined(ec2 instances) that needs to depend on the `network` module being fully created.

For each resource that depends on `network` module have added: 
```
depends_on = [
   "module.network"]
```

**Expected:**
Network module is created and then my resources that depends on it are created

**Actual:**
```
error loading Terraform: module env.root: 1 error(s) occurred:
* aws_instance.instance2: resource depends on non-existent module 'network'

```
I feel this is an issue but would like to be proven wrong :)

**Comment by mitchellh** [comment]
Modules are only visible in the module they're used. _Within_ your environment module, the "network" module doesn't exist (it exists in the parent). I tried with a couple modules and resources in the same module and did you exact line above and it worked great.

**Comment by cemo** [comment]
@mitchellh What is the proper way of handling such cases? I want true isolated modules and also using some modules from 3rd party projects as a dependency which makes impossible to create nested structures.

**Comment by predatorian3** [comment]
@cemo, what I ended up doing is using a shell script, or Rakefile, or some other task runner, to execute specific parts of my main.tf that was calling the modules I had created. So then I had one Rake task execute my router, network, and subnet setup, then once that's finished, I then applied another target resource for security groups, and then compute instances.

```bash
terraform plan
terraform apply -target=module.custom_module_name
```

So far this seems to be working for me. Its not solving it inside of terraform, but I figured this would do until that feature is added.

**Comment by predatorian3** [comment]
Alright to clarify my deleted post, what I did was use a Rakefile, and split my parts of my infrastructure up into multiple plans and apply's. I have one Rake task plan and apply my network specific stuff, then another for my security groups, and a 3rd for my compute infrastructure. That kind of logically splits it up, even though they're in the same main.tf calling those modules. 

This is my workaround until Terraform has a module depends_on function.
