### ISSUE TITLE
suggestion new resource aws_codedeploy_deployment_configuration

### ISSUE THREAD

**Issue by kobymeir-reposify** [hashicorp/terraform#10889]
Suggestion to add new resource to manage AWS CodeDeploy deployment configuration.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_codedeploy_deployment_configuration

### Terraform Configuration Files
```hcl
resource "aws_codedeploy_deployment_configuration" "foo" {
        minimum_healthy_hosts {
            type = "HOST_COUNT" | "FLEET_PERCENT:"
            value = 0
        }
}
```

Reference to AWS CLI help on this resource:
http://docs.aws.amazon.com/cli/latest/reference/deploy/create-deployment-config.html

**Comment by stack72** [comment]
Hi @kobymeir-reposify 

Thanks for the suggestion here - I have just started work on this and will try and get it into terraform 0.8.3

Thanks

Paul
