### ISSUE TITLE
mysql provider can't create user in AWS RDS

### ISSUE THREAD

**Issue by kshcherban** [hashicorp/terraform#10899]
### Descripion
mysql provider fails to create users in AWS MySQL RDS 5.7
Connectivity between RDS and local machine is fine, I can connect using mysql client.
Seems like bug in terraform's mysql code.

Logs from RDS
```
2016-12-22T10:03:57.309811Z 15983 [Note] Aborted connection 15983 to db: 'unconnected' user: 'root' host: '10.1.16.47' (Got an error reading communication packets)
```

### Steps to Reproduce
* Create AWS rds instance using mysql 5.7
* Apply example code below.

### Terraform Version
Terraform v0.8.1

### Affected Resource
- mysql_user

### Terraform Configuration Files
```hcl
provider "mysql" {
    endpoint = "${aws_db_instance.default.endpoint}"
    username = "root"
    password = "secret"
}
resource "mysql_user" "test_user" {
    user = "test"
    host = "%"
    password = "secret"
}
```

### Debug Output
Error applying plan:
```
1 error(s) occurred:

* mysql_user.test: Received #1396 error from MySQL server: "Operation CREATE USER failed for 'test'@'%'"
```
Nothing different in debug log.

### Expected Behavior
User should be created

### Actual Behavior
User was not created

**Comment by andreiashu** [comment]
hi @kshcherban I just tried this in 0.8.3 and it does work as expected.
From the host where you're running Terraform can you connect to the DB and create a new user with a Mysql client? I notice that you're using a `test` user - maybe this doesn't have the GRANT to create other users?
