### ISSUE TITLE
removing autoscaling_groups from aws_codedeploy_deployment_group also deletes any ec2_tag_filter

### ISSUE THREAD

**Issue by kobymeir-reposify** [hashicorp/terraform#10890]
### Terraform Version
v0.7.13

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_codedeploy_deployment_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Before.tf
```hcl
# Server Code deploy
resource "aws_codedeploy_app" "my_server" {
  name = "env-my_server"
}

# Server Deployment group for regular running instances
resource "aws_codedeploy_deployment_group" "my_server" {
  app_name               = "${aws_codedeploy_app.my_server.name}"
  deployment_group_name  = "env-my_server-deployment"
  service_role_arn       = "${aws_iam_role.service_role_arn.arn}"
  autoscaling_groups     = [ "${aws_autoscaling_group.my_server.id}" ]
  deployment_config_name = "CodeDeployDefault.AllAtOnce"

  # Run the deployment to servers matching these tags
  ec2_tag_filter {
    type  = "KEY_AND_VALUE"
    key   = "CodeDeploy"
    value = "env-my_server"
  }
}
```

After.tf (  without the `autoscaling_groups`)
```hcl
# Server Code deploy
resource "aws_codedeploy_app" "my_server" {
  name = "env-my_server"
}

# Server Deployment group for regular running instances
resource "aws_codedeploy_deployment_group" "my_server" {
  app_name               = "${aws_codedeploy_app.my_server.name}"
  deployment_group_name  = "env-my_server-deployment"
  service_role_arn       = "${aws_iam_role.service_role_arn.arn}"
  deployment_config_name = "CodeDeployDefault.AllAtOnce"

  # Run the deployment to servers matching these tags
  ec2_tag_filter {
    type  = "KEY_AND_VALUE"
    key   = "deploy-tag"
    value = "env-my_server"
  }
}
```

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
What should have happened?
The association for the deployment group should remain with only the `ec2_tag_filter` tags

### Actual Behavior
What actually happened?
All the association to `autoscaling_groups` and both `ec2_tag_filter` is being deleted ,leaving the deployment group with no instance association.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` on the first configuration
2. `terraform apply` on the second configuration

### Important Factoids
NA

### References
NA

**Comment by gonzaloserrano** [comment]
Yep just experienced this issue today, thanks for the report.
