### ISSUE TITLE
aws_lambda_function.vpc_config always detects a change when empty

### ISSUE THREAD

**Issue by rochdev** [hashicorp/terraform#10900]
### Terraform Version
0.8.2

### Affected Resource(s)
aws_lambda_function

### Terraform Configuration Files
```hcl
# Only relevant parts shown

variable "subnet_ids" {
  default = []
}

variable "security_group_ids" {
  default = []
}

resource "aws_lambda_function" "lambda" {
  vpc_config {
    subnet_ids         = ["${var.subnet_ids}"]
    security_group_ids = ["${var.security_group_ids}"]
  }
}
```

### Expected Behavior
Right after applying, `terraform plan` should not detect any change since there aren't any.

### Actual Behavior
Right after applying, `terraform plan` detects a change in `vpc_config`. If you apply the change, `terraform plan` will still detect the same change over and over again.

Relevant part of the output:

```text
-/+ module.auth.authorizer.authorizer_lambda.aws_lambda_function.lambda
    vpc_config.#:        "0" => "1" (forces new resource)
    vpc_config.0.vpc_id: "" => "<computed>"
```

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`
3. repeat

### References
Seem to be related:
- https://github.com/hashicorp/terraform/pull/6157
- https://github.com/hashicorp/terraform/pull/6191

**Comment by pgieser** [comment]
We've been seeing this behavior since 0.7.13.

**Comment by pgieser** [comment]
Anything happening here?

**Comment by danielwhite** [comment]
This is still happening in 0.9.4.

**Comment by hilaryhacksel** [comment]
This is still happening in 0.11.3. Any updates here?
