### ISSUE TITLE
aws_network_interface.private_ips empty string in 0.8.2

### ISSUE THREAD

**Issue by eric-johnson** [hashicorp/terraform#10908]
Hi there,

I upgraded to 0.8.2 and am having issues getting ip addresses off of `aws_network_interface`s.

### Terraform Version
0.8.2 (does not happen in 0.8.1)

### Affected Resource(s)
- aws_network_interface

### Terraform Configuration Files
The full config is here: https://gist.github.com/eric-johnson/e73255b833844fbb1e010daf1b5c107b
```hcl
...

resource "aws_network_interface" "test" {
  subnet_id = "${element(split(",", module.vpc.external_subnets), 0)}"
  subnet_id = "${aws_subnet.external.id}"
  security_groups = ["${aws_security_group.sg.id}"]
  tags { Name = "test-8.2" }
}

resource "null_resource" "test" {
  triggers {
    id = "${aws_network_interface.test.subnet_id}"
  }

  provisioner "local-exec" {
    command = "echo ${join("-", aws_network_interface.test.private_ips)} ${jsonencode(aws_network_interface.test.private_ips)}"
  }
}
```

### Output
https://gist.github.com/eric-johnson/e73255b833844fbb1e010daf1b5c107b
I have a debug log, but I'd rather not have to strip out sensitive info from it.

### Expected Behavior
The local-exec provisioner should be printing out the private_ips of the network_interface.
[This line](https://gist.github.com/eric-johnson/e73255b833844fbb1e010daf1b5c107b#file-output-txt-L45) should have the private ip address in it.

### Actual Behavior
The network interface's private_ips was a list with an empty string.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This does not occur in terraform 0.8.1

**Comment by 2rs2ts** [comment]
This broke a workaround I was using to get around another issue about list flattening. 😞 

Through bisecting, I was able to determine that this was caused by #10787 cc @jbardin. I'll try to see if I can fix it, but I'm not really familiar with the codebase and barely know Go, so I wouldn't get my hopes up if I were you.

**Comment by 2rs2ts** [comment]
Thanks to some help from a colleague, I was able to submit a fix. :crossed_fingers:

**Comment by stack72** [comment]
Related to #10926

**Comment by mcraig88** [comment]
This reproduces in v0.8.7. 

* resource 'null_resource.test' config: use of the splat ('*') operator must be wrapped in a list declaration
module vpc.us-west-2.root: 1 error(s) occurred:

* resource 'null_resource.test' config: use of the splat ('*') operator must be wrapped in a list declaration

**Comment by aaomoware** [comment]
Terraform v0.8.6

same ish.
"dns_ip_addresses.#": "0",
