### ISSUE TITLE
AWS Elastic File System DNS name has (silently?) changed

### ISSUE THREAD

**Issue by aisamu** [hashicorp/terraform#10902]
Hi there!

It turns out, as per the AWS Console and new EC2 mounting instructions, AWS has (silently?) dropped the availability zone from the EFS DNS name. 

The former `us-east-1a.fs-xxxxxxxx.efs.us-east-1.amazonaws.com` becomes just `fs-xxxxxxxx.efs.us-east-1.amazonaws.com`.

Unfortunately, `aws_efs_mount_target.xxx.dns_name` still outputs the old format.

For the moment, just dropping the AZ from the DNS works, as in `replace(aws_efs_mount_target.xxx.dns_name, "/\\A[^\\.]*\\./", "")`, but I figured it'd be useful to let you know!

Thanks a lot for this great tool!

### Affected Resource(s)
- aws_efs_file_system

**Comment by pdecat** [comment]
FWIW, this change was discreetly announced last week https://aws.amazon.com/fr/about-aws/whats-new/2016/12/simplified-mounting-of-amazon-efs-file-systems/

**Comment by stack72** [comment]
Hi @aisamu 

thanks for the bug report here - can you tell me if `terraform refresh` updates the dns_name?

Thanks

Paul

**Comment by aisamu** [comment]
Hey!

Sadly, it doesn't =(

**Comment by stack72** [comment]
Found the error! It will be fixed as of 0.8.3 :)

**Comment by aisamu** [comment]
Thanks for such awesome tool!
