### ISSUE TITLE
Unable to plan resources that include ASG

### ISSUE THREAD

**Issue by dominicbarnes** [hashicorp/terraform#10919]
As of v0.8.2, I can no longer `terraform plan` resources that include autoscaling groups. I get the following error:

```
Error refreshing state: 1 error(s) occurred:

* aws_appautoscaling_target.main: Error retrieving Application AutoScaling Target: InvalidSignatureException: Credential should be scoped to correct service: 'application-autoscaling'.
```

This error does not happen with v0.8.1 (or v0.8.0) so I believe this bug was introduced in v0.8.2.

**Comment by jun06t** [comment]
I have met the same issue.

**Comment by pchaganti** [comment]
+1

**Comment by ZhijieWang** [comment]
confirmed here, using Terraform 0.8.2
See terraform debug log 
https://gist.github.com/ZhijieWang/ea533e6756aed11e79846be7891a9568

**Comment by ronaldtse** [comment]
Same issue here, it works currently in 0.8.1 but not in 0.8.2.

**Comment by rvoitenko** [comment]
Would be nice to get it fixed in next release!
We had to downgrade to v.0.8.1, but its not big deal.
The pain was to patch all terraform state files and replace version 0.8.2 with 0.8.1 there :(.

**Comment by josh-padnick** [comment]
I'm also seeing this issue and can confirm it was a regression recently introduced.

**Comment by jim3ma** [comment]
+1

**Comment by mudasirmirza** [comment]
+1

**Comment by cyrilhagege** [comment]
+1

**Comment by rbranson** [comment]
+1

**Comment by pbthorste** [comment]
Not 100% sure - but this might be related to [https://github.com/aws/aws-sdk-go/issues/1009]()  - and can be fixed by updating the aws lib.

**Comment by rvoitenko** [comment]
It's seems it works perfectly  in new 0.8.3 
I  just have tested it.
