### ISSUE TITLE
-target does not prevent validation of excluded interpolations

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#10911]
Hi there,

### Terraform Version

Terraform v0.8.2

### Affected Resource(s)

Seems to be a core issue.

### Terraform Configuration Files

top.tf:

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_instance" "foo" {
  instance_type = "doesntmatter"
  ami = "doesntmatter"
}

module "child1" {
  source = "./child1"

  instance_id = "${aws_instance.foo.id}"
}

module "child2" {
  source = "./child2"
}
```

child1/child.tf:

```hcl
variable "instance_id" {
}

output "instance_id" {
  value = "${var.instance_id}"
}

resource "null_resource" "foo" {
  triggers = {
    instance_id = "${var.instance_id}"
  }
}
```

child2/child.tf

```
resource "null_resource" "foo" {
}
```

### Debug Output

https://gist.github.com/apparentlymart/fa1a338fb0317333bb62f92171c2f9b7

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

Plan alone works:

* `terraform plan -target=module.child2`

But apply fails:

* `terraform apply -target=module.child2`

### Expected Behavior

For both plan and apply, all of the resources in the root module and in `module.child1` are excluded by the `-target` and so `module.child2.null_resource.foo` is created/updated successfully.

### Actual Behavior

The plan command works, but apply fails:

```
$ terraform apply -target=module.child2
module.child2.null_resource.foo: Refreshing state... (ID: 6632890624950290071)
Error applying plan:

1 error(s) occurred:

* Resource 'aws_instance.foo' not found for variable 'aws_instance.foo.id'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

It would seem that Terraform attempted to evaluate an interpolation in `module.child1` even though it was excluded by the target, which then failed because `aws_instance.foo` is also excluded by the target.

I have also seen this happen with references to variables that are in modules that are excluded by target (e.g. `${var.instance_id}` in `module.child1` in this case), but I didn't manage to get a minimal repro for that; I think it only occurs when the excluded resources are already present in state and thus Terraform is able to evaluate them even though they are excluded, but I've not proven this.

My guess is that the new apply graph isn't pruning excluded resources as exhaustively as the old codepath did. Indeed this works as expected when I use the flag `-Xlegacy-graph`.

**Comment by mitchellh** [comment]
I got this for 0.9. New graphs for validation/input should fix this.

**Comment by eyespies** [comment]
@mitchellh in #11113 I was asked to upgrade to the latest TF. I've just done that but now I am receiving this error in 0.8.5.

We typically use -target much more often than running a full plan, but I see you said "I got this for 0.9". Should we expect to see this issue fixed in 0.8.x or is it really targeted to be fixed only in 0.9? I need to figure out which of the two bugs is a lessor of two evils.

**Comment by mitchellh** [comment]
@eyespies I didn't re-read this issue but I believe this issue in particular covered a case that could only be fixed in 0.9. If your error is something that could be easily backported we will!

**Comment by eyespies** [comment]
I see what you're saying @mitchellh and will continue looking around.

**Comment by mkuzmin** [comment]
@mitchellh Mitchell, you mentioned this issue should be fixed by #11373, but I reproduced the same behavior is today's build.

**Comment by mkuzmin** [comment]
oh, the PR is closed, but not merged yet. sorry

**Comment by mitchellh** [comment]
Verified this still exists. Looking into it.
