### ISSUE TITLE
vcloud provider does not understand multiple edge gateway in a VDC

### ISSUE THREAD

**Issue by poblin-orange** [hashicorp/terraform#10916]
### Affected Resource(s)
- vcd_firewall_rules

### Terraform Configuration Files
```
resource "vcd_firewall_rules" "fw" {
    edge_gateway   = "EDGE1"
    default_action = "drop"

    rule {
        description      = "enable https"
        policy           = "allow"
        protocol         = "tcp"
        destination_port = "443"
        destination_ip   = "10.10.0.1"
        source_port      = "any"
        source_ip        = "10.11.0.1"
    }
}
```

### Expected Behavior
the rule should apply on the specified edge gateway. 

### Actual Behavior
The provider seem to choose the first found edge gateway

**Comment by robcoward** [comment]
I believe that the default behaviour is that if 'EDGE1' is not found, it falls back to using the first edge found. Are you sure that you have the edge name 100% correct?

**Comment by poblin-orange** [comment]
Hello,
im double checked so i think yes 100%. Anyway, fallback to the first found edge seem does not seem to be a safe approach ?

**Comment by Boran** [comment]
Same issue here, despite having double checked the spelling of my edge_gateway ="foo-bar", it is silently ignored. Looking at the Vmware UI, the network is active, but with another gateway.

**Comment by Boran** [comment]
Same issue here, despite having double checked the spelling of my edge_gateway ="foo-bar", it is silently ignored. Looking at the Vmware UI, the network is active, but with another gateway.
