### ISSUE TITLE
aws_waf_ipset - requires ip_set_descriptors, but AWS says optional -- prevents from create empty "blacklist" to dynamically IP List.

### ISSUE THREAD

**Issue by ventz** [hashicorp/terraform#10914]
### Terraform Version
Terraform v0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
aws_waf_ipset

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
No

### Terraform Configuration Files
http://pastebin.com/g1CQpUbF

### Debug Output
http://pastebin.com/JLin9Zyu

### Panic Output
None

### Expected Behavior
If you create a resource with 1 field (just a name), it should create (which it does), but then it should just delete it. It fails to delete it since it claims the 2nd field "ip_set_descriptors" is required and missing. The "ip_set_descriptors" should be OPTIONAL (as per AWS docs - see in "References" bellow, specifically part: "Required: No")

### Actual Behavior
Complains about 2nd field being required -- per AWS docs it's not, and there are legitimate cases where it should not be (ex: blacklist -- you can't pre-populate an IP as a "default", since it would be rejected). This prevents you from creating the object and dynamically populating it with a lambda function.

### Steps to Reproduce
terraform apply

### Important Factoids
N/A

### References
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-waf-ipset.html
(see: IPSetDescriptors --> Required: No)

**Comment by vicfl** [comment]
+1

**Comment by PurrBiscuit** [comment]
+1

**Comment by charlieoleary** [comment]
Still happening in 0.9.2 as well.
