### ISSUE TITLE
AWS VPC security group loses ingresses if ingress to another security group is set

### ISSUE THREAD

**Issue by mahnve** [hashicorp/terraform#1091]
We have a security group as such: 

```
resource "aws_security_group" "db" {
  name="db-sg"
  vpc_id="${aws_vpc.dryleaf.id}"
  description="Accessible from Jump and Boxes"

  ingress {
    from_port=3306
    to_port=3306
    protocol="tcp"
    security_groups=["${aws_security_group.jump.id}"]
  }
  ingress {
    from_port=3306
    to_port=3306
    protocol="tcp"
    cidr_blocks=["10.1.1.0/24", "10.1.2.0/24"]
  }
  tags {
    app="our_app"
    Name="sg_name"
  }
}
```

Running this with 0.3.7 clears removes all ingresses. Removing the top ingress with the security groups works though.

**Comment by mahnve** [comment]
I just realized that you can't have more than one ingress block. Never mind.

**Comment by mitchellh** [comment]
You should be able to have more than once ingress block. The behavior I would've expected here is that one of them would've succeeded, but the other would be ignored or something, since the two ingress blocks mostly match.

**Comment by mahnve** [comment]
Yes, I just saw that as well :)

**Comment by mahnve** [comment]
Reopening

**Comment by mahnve** [comment]
Not sure if it is related - we have an existiing security group that has two security-group-bound ingresses. After changing to an CIDR-block setup instead and applying it, the tfstate-file says that everything is applied. Looking in the AWS-console though, nothing has changed.

**Comment by catsby** [comment]
hey @mahnve , do you have an example config file that illustrates this? 
Is it as simple as starting with a security group with this ingress:

```
  ingress {
    from_port=3306
    to_port=3306
    protocol="tcp"
    security_groups=["${aws_security_group.jump.id}"]
  }
```

and moving to this ingress?

```
  ingress {
    from_port=3306
    to_port=3306
    protocol="tcp"
    cidr_blocks=["10.1.1.0/24", "10.1.2.0/24"]
  }
```

**Comment by catsby** [comment]
I attempted to reproduce this using this config: https://gist.github.com/catsby/990a7bf4889f66328ebf

Every toggle of `security_groups` and `cidr_blocks` correctly updated the local state and the AWS console, so I'm closing this for now. Let me know if I misunderstood.
