### ISSUE TITLE
Can't refresh state with refresh command. Fails to sync with missing aws_spot_fleet_request.

### ISSUE THREAD

**Issue by jozuenoon** [hashicorp/terraform#10917]
### Actual Behavior
**Existing spot fleet request was deleted manually. It was created before by terraform **
After issuing ```terraform refresh``` command I'm getting permanent error:
```bash
Error refreshing state: 1 error(s) occurred:

* aws_spot_fleet_request.xlarge_fleet: InvalidSpotFleetRequestId.NotFound: The SpotFleetRequestId(s) xx-xx-xx-xx do not exist.
	status code: 400, request id: aa-aa-aa-aa
```
*NOTICE - ```plan``` command is failing with same error.

### Expected Behavior
Current state should be updated and thus other commands eg. plan, apply don't fails with same error.

## General information:
Varsion: Terraform v0.8.2

Resource: aws_spot_fleet_request

Command: terraform refresh

Relevant config part:
```hcl
"aws_spot_fleet_request":{  
         "xlarge_fleet":{  
            "launch_specification":{  
               "key_name":"somekey",
               "vpc_security_group_ids":[  
                  "some-id"
               ],
               "ami":"${data.aws_ami.slave_ami.id}",
               "ebs_optimized":true,
               "availability_zone":"eu-central-1a",
               "iam_instance_profile":"some-profile",
               "instance_type":"c4.xlarge"
            },
            "iam_fleet_role":"somerole",
            "target_capacity":1,
            "spot_price":"0.06",
            "allocation_strategy":"lowestPrice",
            "terminate_instances_with_expiration":true,
            "valid_until":"2019-11-04T20:44:20Z"
         }
      }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create aws_spot_fleet_request using terraform,
2. Delete spot request manually eg. from AWS console,
3. Try to refresh state using ```terraform refresh```.

### Workaround
I did recovered with following commands:
```bash
# To show current state:
terraform state list

# To delete not existing resource:
terraform state rm aws_spot_fleet_request.xlarge_fleet
```

**Comment by apparentlymart** [comment]
Hi @jozuenoon! Thanks for reporting this.

This is indeed a bug. The "refresh" action is supposed to detect when something is gone and automatically remove it from state. The usual reason for bugs like this is that AWS returns the "not found" error in a way other than what we expected, and indeed this one seems particularly subtle:

```go
		if ok && ec2err.Code() == "InvalidSpotFleetRequestID.NotFound" {
			d.SetId("")
			return nil
		}
```

Notice that we're checking for a string with "ID", but it looks like AWS is returning the string "Id".

I was going to suggest `terraform state rm` as a workaround but it looks like you already figured that out! :grinning:

**Comment by BVKkumar** [comment]
Hi I had a problem when I do terraform plan .Please find the attachement for the error which I got and please help me from that.
![terraform plan](https://user-images.githubusercontent.com/39926635/40940191-044ae668-6815-11e8-91af-f5108389eee1.PNG)

data.terraform_remote_state.global_core: Refreshing state...
data.terraform_remote_state.local_core: Refreshing state...
data.template_file.ansible_sh: Refreshing state...
data.template_file.provisioner: Refreshing state...
data.aws_caller_identity.current: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 4 error(s) occurred:

* module.public_instance.var.ami: Resource 'data.terraform_remote_state.local_core' does not have attribute 'public_amis' for variable 'data.terraform_remote_state.local_core.public_amis'
* output.public_web_app_public_ip: Resource 'data.terraform_remote_state.local_core' does not have attribute 'public_instance.public_ip' for variable 'data.terraform_remote_state.local_core.public_instance.public_ip'
* output.public_web_app_private_ip: Resource 'data.terraform_remote_state.local_core' does not have attribute 'public_instance.private_ip' for variable 'data.terraform_remote_state.local_core.public_instance.private_ip'
* module.public_instance.var.ssh_key_name: Resource 'data.terraform_remote_state.local_core' does not have attribute 'key_pair.ssh_key_name' for variable 'data.terraform_remote_state.local_core.key_pair.ssh_key_name'

**Comment by BVKkumar** [comment]
the following is the remote_state.tf file

/*
Reference the data in this remote state like this:
 "${data.terraform_remote_state.global_core.GLOBAL_OUTPUT_VARIABLE}"
*/

data "terraform_remote_state" "global_core" {
  backend = "s3"

  config {
    bucket = "${var.remote_state_bucket_global_core}"
    key    = "${var.remote_state_key_global_core}"
    region = "${var.region}"
  }
}

/*
Reference the data in this remote state like this:
 "${data.terraform_remote_state.local_core.LOCAL_OUTPUT_VARIABLE}"
*/

data "terraform_remote_state" "local_core" {
  backend = "s3"

  config {
    bucket = "q2ea-global${var.env}-s3-terraformstateinfra"
    key    = "env:/${var.env}/vpc/core.tfstate"
/*
    bucket = "${var.remote_state_bucket_vpc_core}"
    key    = "${var.remote_state_key_vpc_core}"
*/
    region = "${var.region}"
  }
}


/*
data "terraform_remote_state" "local_core" {
  backend = "s3"

  config {
    bucket = "${var.remote_state_bucket_local_core}"
    key    = "${var.remote_state_key_local_core}"
    region = "${var.region}"
  }
}
*/
