### ISSUE TITLE
Renaming aws_iam_role_policy_attachment resource requires double applies

### ISSUE THREAD

**Issue by makered** [hashicorp/terraform#10918]
Noticed that if I rename an existing `aws_iam_role_policy_attachment` resource and `terraform apply`, the old attachment is removed but not re-created, requiring a subsequent `terraform apply` to be added back.

Running v0.8.2

**Comment by mitchellh** [comment]
I believe this is actually an AWS issue, retagging. Unless I'm misunderstanding.
