### ISSUE TITLE
Shadow graph hangs terraform

### ISSUE THREAD

**Issue by rklyne** [hashicorp/terraform#10927]
Hi there,

### Terraform Version
I was running terraform-0.7.13 with no issues.
I upgraded to terraform-0.8.2 and found this. Also present in terraform-0.8.1.

### Terraform Configuration Files
https://github.com/rklyne/mini-datacenter/tree/615a1874e37f26f6dde157c543464c160740db05

### Expected Behavior
Plan should be displayed

### Actual Behavior
Terraform will hang

### Steps to Reproduce
1. `terraform plan`

`terraform plan -Xshadow=false` works around the problem.

**Comment by mitchellh** [comment]
Closing since we removed this from the latest version. Thanks!
