### ISSUE TITLE
terraform fmt should specify file name

### ISSUE THREAD

**Issue by jamtur01** [hashicorp/terraform#10923]
### Terraform Version

Terraform 0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- terraform fmt

### Expected Behavior

```
$ terraform fmt                                             
Error running fmt: At interface.tf:23:15: nested object expected: LBRACE got: ASSIGN
```

### Actual Behavior

```
$ terraform fmt                                             
Error running fmt: At 23:15: nested object expected: LBRACE got: ASSIGN
```

**Comment by mitchellh** [comment]
Fixed here: https://github.com/hashicorp/hcl/commit/e930f8e5febb8809b374767f94f85a88b816ba6f

Thanks!
