### ISSUE TITLE
[Feature] aws_autoscaling_group instances support for output

### ISSUE THREAD

**Issue by synhershko** [hashicorp/terraform#10925]
After applying a change that creates an ASG, it's useful to show the DNS / IPs of the currently running instances as outputs. Since Terraform waits for the Desired capacity to be fulfilled by default, as long as it is >0 it's relatively easy to support that.

Will you accept a PR adding this feature? :)

**Comment by phillbaker** [comment]
Looks similar to https://github.com/hashicorp/terraform/issues/8400.

**Comment by stack72** [comment]
Hey @synhershko - I guess this would cause no harm - it may be useful information for people to output. It may get stale quick though so it would nearly always need a refresh before being used elsewhere

I am going to close it as a duplicate of #8400 :)
