### ISSUE TITLE
Panic when using module with name "root"

### ISSUE THREAD

**Issue by spirius** [hashicorp/terraform#10939]
Hey guys,

I've noticed very strange behaviour and panics when I used module with name `root`. Looks like it's internally used in graphs, but nothing mentioned in documentation that it's reserved name for module.

I've spent couple of hour until I figured out that problem was because of name, so would be nice to have something in documentation about this and in generally disallow that name for modules.

### Terraform Version
Terraform v0.8.2

### Example 1 - Invalid result
```
// main.tf
module "root" {
  source =  "./root"
}
```

```
// root/module.tf
provider "aws" {
  region = "eu-central-1"
}

data "aws_caller_identity" "me" {}

output "id" {
  value = "${data.aws_caller_identity.me.account_id}"
}
```

Output:
```
module.root.data.aws_caller_identity.me: Refreshing state...
Error creating plan: 1 error(s) occurred:

* Not a valid region:
```

In this case it will complain that the region is invalid.

### Example 2 - Panic
Now if I add region as well in main.tf, it will crash.
```
provider "aws" {
  region = "eu-central-1"
}

module "root" {
  source =  "./root"
}
```

Output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12a24e]

goroutine 294 [running]:
panic(0x2e39fe0, 0xc42000e090)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/terraform.(*NodePlannableResource).EvalTree(0xc420444fc0, 0x337aca0, 0xc420444fc0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_plan.go:32 +0x5e
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x337aca0, 0xc420444fc0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:288 +0xb90
github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk.func3(0xc4204416e0, 0xc4203779f0, 0xc4204416f0, 0xc4203a8180, 0xc420441700, 0x337aca0, 0xc420444fc0, 0xc42041db60, 0xc42041dce0)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:246 +0x251
created by github.com/hashicorp/terraform/dag.(*AcyclicGraph).Walk
	/opt/gopath/src/github.com/hashicorp/terraform/dag/dag.go:255 +0x6a6
```

**Comment by mitchellh** [comment]
Ah dup of #11038. That's newer and your issue is better but we have a short term fixed attached to that one so I'm going to call this the dup. We have a longer term fix planned to allow this but for now we're going to disallow root children modules named "root"... until we can get a fix in place.
