### ISSUE TITLE
Lists of heredocs does not fmt correctly

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#10947]
Using TF 0.8.2. Probably an edge case, not to sure how many people would be using a list of here documents, but came across it during doing some testing on how to render lists and how they would look as heredocs.

Config:

```
variable "foo" {      
  type = "list"       
                      
  default = [         
    <<EOS             
one                   
EOS                   
,                     
    <<EOS             
two                   
EOS                   
,                     
  ]                   
}                     
                      
output "out" {        
  value = "${var.foo}"
}                     
```

fmts as (note how the comma has moved to the end of the heredoc marker):

```
variable "foo" {
  type = "list"

  default = [
    <<EOS
one
EOS,
    <<EOS
two
EOS,
  ]
}

output "out" {
  value = "${var.foo}"
}
```

Which gives this error on apply afterwards and on subsequent fmts:

```
Error loading config: Error parsing main.tf: At 9:1: error parsing list, expected comma or list end, got: IDENT
```

**Comment by mitchellh** [comment]
Weird indeed, but a bug certainly. Thanks. Fixed here: https://github.com/hashicorp/hcl/pull/177

Will be in 0.8.3.
