### ISSUE TITLE
Rancher provider try to access the API on "plan"

### ISSUE THREAD

**Issue by seb2411** [hashicorp/terraform#10945]
**Terraform version:** 8.2
**Affected Resource(s)** rancher provider

Hello I try to test the Rancher provider. But I face a problem and I don't know if it's a normal behavior or a bug.

My terraform scripts are setting up a cluster including a Rancher server and 7 hosts. My plan is, once the rancher server is working, to create a registration token using the rancher provider (ressource: rancher_registration_token) , and executing the command the resource is returning on each host to add this hosts on the Rancher cluster.

But it seem that the Rancher provider try to access the rancher API before the resource exist when executing the "terraform plan" command

My script
```nginx
provider "rancher" {
  api_url = "http://${scaleway_server.rancher.private_ip}:8080"
  access_key = "${var.rancherAccessKey}"
  secret_key = "${var.rancherSecretKey}"
}

resource "rancher_registration_token" "default" {
  name = "serversRegistrationToken"
  description = "Registration token for the default environment"
  environment_id = "1a5"
}
```
the scaleway_server.rancher.private_ip is the private IP of the Rancher server.

the error I got:

```
Error refreshing state: 1 error(s) occurred:
* Get /v1: unsupported protocol scheme ""
```

If I replace the `api_url` by a random url like that:
```nginx
provider "rancher" {
  api_url = "http://localhost:8080"
  access_key = "${var.rancherAccessKey}"
  secret_key = "${var.rancherSecretKey}"
}
```
I got the following message:

```
Error refreshing state: 1 error(s) occurred:
* Get http://localhost:8080//v1: dial tcp 127.0.0.1:8080: getsockopt: connection refused
```

As I understand the Rancher provider try to access the rancher server API on "terraform plan". And I expect this provider to contact the rancher onlywhen the rancher is ready (resource scaleway_server.rancher.private_ip ready)

**Comment by seb2411** [comment]
#9173

**Comment by johnrengelman** [comment]
Well, Terraform has to take to Rancher during a `plan` in order to refresh resource state.
I'm pretty sure you can't interpolate attributes from resources into providers like you are trying to do.
The providers are evaluated long before the resources in the graph. @stack72, right?

I don't believe this is an issue with the Rancher provider.
