### ISSUE TITLE
website: Incorrect description Variable page of Getting Started

### ISSUE THREAD

**Issue by mooyoul** [hashicorp/terraform#10949]
### Terraform Version

v0.8.1

### Affected Resource(s)

N/A

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Paragraph about loading variables from a file should go `From a file` section, not `Envirionment Variables` section. Please see below screenshot (highlighted), and please compare with screenshot in Actual Behavior section.

<img width="844" alt="2016-12-29 4 42 15" src="https://cloud.githubusercontent.com/assets/2101743/21530055/5734efca-cd81-11e6-81ed-0c7fd374a43c.png">

### Actual Behavior

Some paragraph about loading variables from a file should go `From a file` section are exists on `Envirionment Variables` section.

<img width="832" alt="2016-12-29 4 39 37" src="https://cloud.githubusercontent.com/assets/2101743/21530007/0067494a-cd81-11e6-9007-baeb0df7e7ea.png">

### Steps to Reproduce

1. Simply visit https://www.terraform.io/intro/getting-started/variables.html#from-environment-variables

### Important Factoids

N/A

### References

- #10950

**Comment by stack72** [comment]
Closed via #10950
