### ISSUE TITLE
Allow aws_acm_certificate datasource to be filtered by tags

### ISSUE THREAD

**Issue by bilco105** [hashicorp/terraform#10940]
Hi, 

It would be useful to allow for aws_acm_certificate datasources to be filterable by tags, as well as the certificate status. 

A typical use case for this is when creating new SSL certificates which replaces an existing certificate, tags can be used to denote which issued SSL certificate for a domain should be the one selected by the datasource.

Thanks!

**Comment by stack72** [comment]
Hi @bilco105 

Thanks for the feature request here - unfortunately, there is no way to do this via the AWS SDK / CLI

The SDK effectively uses something similar to this

```
http://docs.aws.amazon.com/cli/latest/reference/acm/describe-certificate.html
```

Therefore, this would have to be a feature request to AWS - sorry it's not better news!

Thanks for getting in touch

Paul
