### ISSUE TITLE
Bug Report Diff Didn't match

### ISSUE THREAD

**Issue by ZhijieWang** [hashicorp/terraform#10948]
Hi,

When applying AppAutoscaling group to ECS service on AWS. Using Terraform 0.8 I received a 
``* aws_cloudwatch_metric_alarm.service_cpu_high: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.``

See crush log here https://gist.github.com/ZhijieWang/514706e1fee6acd0ea52185ba0dc54f2

When running again, terraform outputs
``
module.service.aws_appautoscaling_policy.up: Modifying...
module.service.aws_appautoscaling_policy.up: Modifications complete
module.service.aws_cloudwatch_metric_alarm.service_cpu_low: Still modifying... (10s elapsed)
module.service.aws_cloudwatch_metric_alarm.service_cpu_low: Modifications complete
``
Then everything passed.

**Comment by tavisca-vtripathi** [comment]
+1
