### ISSUE TITLE
website: Broken markdown style on getting started page

### ISSUE THREAD

**Issue by mooyoul** [hashicorp/terraform#10943]
### Terraform Version

v0.8.1

### Affected Resource(s)

N/A

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

**N/A**

### Expected Behavior

Markdown should be rendered correctly on website

### Actual Behavior

<img width="865" alt="2016-12-29 12 23 48" src="https://cloud.githubusercontent.com/assets/2101743/21525246/5721852e-cd5f-11e6-97de-a76c894656ba.png">

**Broken code style on [Getting Started - Variables - Lists](https://www.terraform.io/intro/getting-started/variables.html#lists).**

### Steps to Reproduce

1. Simply visit https://www.terraform.io/intro/getting-started/variables.html#lists

### Important Factoids

N/A

### References

- #10944

**Comment by stack72** [comment]
Closed via #10944
