### ISSUE TITLE
Unable to destroy specific ec2 instances without wiping out other instances's dependent resources

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform#10952]
I haven't been able to destroy specific EC2 instances that were created with `count`. 

`terraform plan -destroy -var-file ../config.tfvars -target aws_instance.nomad[2]` shows that it will remove the specific instance but it will also wipe out dependent resources of the remaining instances which is not good. 

### Terraform Version
Terraform v0.8.3-dev (452552a2cb13c01c14a024096d9e2145a64ef487)

### Affected Resource(s)
Any resource created with count and dependent resources

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "private-nomad-nodes" {
	count	= "${var.node_count["nomad"]}"
	zone_id	= "${data.terraform_remote_state.network.private_dns_zone_id}"
	name	= "n${count.index+1}"
	type	= "A"
	ttl	= "60"
	records = ["${element(aws_instance.nomad.*.private_ip, count.index)}"]

	lifecycle {
		create_before_destroy = true
	}
}

# EC2 instances
resource "aws_instance" "nomad" {
	count				= "${var.node_count["nomad"]}"
	ami				= "${lookup(var.images, var.region)}"
	instance_type			= "${var.node_type["nomad"]}"
	availability_zone		= "${element(split(",", var.zones), count.index)}"
	subnet_id			= "${element(data.terraform_remote_state.network.public_subnets, count.index)}"
	vpc_security_group_ids	= [
		"${data.terraform_remote_state.network.common_security_group_id}",
		"${data.terraform_remote_state.consul.client_security_group_id}",
		"${aws_security_group.nomad.id}"
	]
	iam_instance_profile	= "${aws_iam_instance_profile.nomad.name}"

	tags {
		Name = "nomad${count.index+1}"
	}

	user_data = "${element(data.template_file.nomad.*.rendered, count.index)}"

	lifecycle {
		create_before_destroy	= true
		# Ignores changes in user_data or instance_type as we want to have better control on
		# cluster upgrades to avoid downtimes. Anytime we change bootstrapping configuration or instance types
		# the changes get applied to new launched instances only, keeping the existing ones untouched and forcing us
		# to increase the number of instances in order to apply new configuration changes or change on instance types.
		ignore_changes			= ["user_data", "instance_type"]
	}
}
```
### Command
`terraform plan -destroy -var-file ../config.tfvars -target aws_instance.nomad[2]`

### Expected Behavior
I would expect the above command to show the following diff:

```
- aws_instance.nomad.2

- aws_route53_record.nomad-nodes.2

- aws_volume_attachment.ebs_att.2

```
I would also expect it to modify `aws_route53_record.nomad` to remove the retired node from the resource record set.

### Actual Behavior
Instead, it shows me the following: 

```
- aws_instance.nomad.2

- aws_route53_record.nomad

- aws_route53_record.nomad-nodes.0

- aws_route53_record.nomad-nodes.1

- aws_route53_record.nomad-nodes.2

- aws_route53_record.nomad-nodes.3

- aws_route53_record.nomad-nodes.4

- aws_route53_record.nomad-nodes.5

- aws_route53_record.nomad-nodes.6

- aws_volume_attachment.ebs_att.0

- aws_volume_attachment.ebs_att.1

- aws_volume_attachment.ebs_att.2

- aws_volume_attachment.ebs_att.3

- aws_volume_attachment.ebs_att.4

- aws_volume_attachment.ebs_att.5

- aws_volume_attachment.ebs_att.6
```

**Comment by c4milo** [comment]
FWIW, this is the only missing piece for me to be able to carefully manage Consul and Nomad clusters, including route53 records and volumes, using only Terraform. 

The use cases I was exercising are: 

1. Being able to change instance count up and down without losing quorum. This works fine if `user_data` changes are ignored.
2. Being able to gradually change instance type without losing quorum by ignoring `user_data` and `instance_type` changes to avoid full cluster recreation at once. Here, gradually tainting individual nodes worked very well. 
3. Being able to change volume's `size`, `type` and `iops` for individual nodes. I couldn't get this to work by tainting since it creates the new instance first then destroys the old one, so the volume is still attached to the old instance and causes the new one to fail. However, I believe destroying and then applying would do it, but then I ran into the issue I'm describing above.

After this first testing I was planning to increase reliability a bit more by monitoring the raft log so changes are precisely executed without too much disruption.

Anyway, I hope this background information helps in anyway. Please let me know if there are better ways of achieving the same.

**Comment by apparentlymart** [comment]
Hi @c4milo! Thanks for reporting this.

I think this might be a `target`-specific variant of #3449; you triggered it in this case by eliminating the other instances from consideration, but it looks like this is still the same issue that an expression like `aws_instance.nomad.*.private_ip` becomes wholly computed as soon as any element of it is computed.

If so, I'd like to close this issue and consolidate discussion there.

---

I can certainly relate to your Consul problem here (and Nomad, though I'm not actually running Nomad myself!)... currently I use a different strategy to achieve some of the same goals you have here, which is to make a Terraform module for a cluster of servers and then treat that as immutable.

When I want to make changes like you described, I make a new module alongside it with the new settings, temporarily having a cluster twice the size. Once the new nodes have caught up with the old I then gracefully kick them from the cluster one by one until the machines are idle and then delete the module.

It's certainly not as elegant as what you were trying to do here, but I can confirm that it does work with Terraform's current constraints. I certainly wouldn't describe this as a "better" way to achieve these goals, but perhaps it's an *alternative* way to do it that doesn't run into the current limitations around `*` variables.

**Comment by c4milo** [comment]
@apparentlymart, yes! that seems to be the same issue. Feel free to close this one. Creating a module alongside sounds reasonable for now. Thanks for the suggestion!

**Comment by c4milo** [comment]
Closing in favor of #3449
