### ISSUE TITLE
provider defined on an ignored module causes "unknown variable accessed: var.region

### ISSUE THREAD

**Issue by jfromaniello** [hashicorp/terraform#10951]
A provider defined in a ignored module (-target) causes "unknown variable accessed: var.region".

If I run `terraform plan` without `-target` everything works as expected.

### Terraform Version

The issue is present in `0.8.1` and `0.8.2`. The 0.7 branch is not affected.

### Affected Resource(s)

The issue affects `provider "aws"` with variable region defined in modules when the module is ignored by a `-target` argument.

### Terraform Configuration Files

> The full directory can be downloaded from [this dropbox link](https://dl.dropboxusercontent.com/u/1525624/terraform-issue.zip).

The structure I used to reproduce this issue is the following (I will attach a zip at the end):

```
» tree
.
├── main.tf
├── module-1
│   └── module-1.tf
├── module-2
│   └── module-2.tf
├── terraform.tfstate
└── terraform.tfvars
```

`module-1.tf` and `module-2.tf` have exactly the same content:

```hcl
variable "region" {}

provider "aws" {
    region = "${var.region}"
}

data "aws_ami" "nat_ami" {
  most_recent = true
  filter {
    name = "name"
    values = ["amzn-ami-vpc-nat*"]
  }
  owners = ["amazon"]
}

output "ami" {
    value = "${data.aws_ami.nat_ami.id}"
}
```

main.tf has the following content:

```hcl
variable "region" {}


module "module-1" {
    source = "module-1"
    region = "${var.region}"
}

module "module-2" {
    source = "module-2"
    region = "${var.region}"
}

output "module-1-ami" {
    value = "${module.module-1.ami}"
}

output "module-2-ami" {
    value = "${module.module-2.ami}"
}

```

`terraform.tfvars`:

```
region = "us-west-1"
```

The full directory can be downloaded from [this dropbox link](https://dl.dropboxusercontent.com/u/1525624/terraform-issue.zip).

### Debug Output

This is the debug output https://gist.github.com/jfromaniello/42c2eae54428b153f0244552b0be775f

### Expected Behavior

I will expect `terraform plan -target=module.module-1` to succeed the same way that terraform 0.7 does.

### Actual Behavior

It is actually crashing with:

```
Error running plan: 1 error(s) occurred:

* 1:3: unknown variable accessed: var.region in:

${var.region}
```

**Comment by tjsingleton** [comment]
Just got hit by this. Any known workaround?

**Comment by apparentlymart** [comment]
Hi @jfromaniello! Thanks for filing this.

I think this is the same issue I filed in #10911, so I'm going to close this to consolidate the discussion over there. There is a limited workaround at the end of my long writeup of forcing Terraform to use the legacy graph, but that comes with some caveats that are described in the 0.8 upgrade guide so should be used with care. (My configs don't use any 0.8-specific features yet, so it worked okay for me.)

**Comment by gambol99** [comment]
@tjsingleton  .. i hit the same issue ... the only workaround i found was to export the variable and not pass as a module param .. in this case AWS_DEFAULT_REGION
