### ISSUE TITLE
404 on the website

### ISSUE THREAD

**Issue by lattwood** [hashicorp/terraform#10972]
https://www.terraform.io/docs/providers/aws/d/hosted_zone.html

**Comment by apparentlymart** [comment]
Thanks for reporting this, @lattwood.

Looks like it's supposed to be called `aws_route53_zone`: https://www.terraform.io/docs/providers/aws/d/route53_zone.html

**Comment by apparentlymart** [comment]
This'll get reflected on the website at the next update.
