### ISSUE TITLE
aws/rds: Be a bit more interactive when creating/deleting db instance

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1097]
Creating or destroying an RDS instance in AWS is a **very** slow process, sometimes may take even half an hour.

Terraform's current behaviour (which is very similar if not same as CloudFormation's):
1. Trigger the creation
2. Wait and let user starring XX minutes to `aws_db_instance.default: Creating...`
3. After XX minutes, say "OK" or "FAIL"
### 1. Make blocking optional

First of all I think that in many cases, user just may not want to wait for the RDS if it's really not a blocker in the dependency graph (i.e. you're not building other resources on the top of it).
### 2. Make waiting shorter + nicer

If we're waiting for the endpoint URL, then that's something, that becomes available already when the instance status becomes `backing-up` and the back-up process takes another ~10 mins or so, so we're IMO merely waiting for API response `available`, but we may not need to.

If the endpoint is actually useful (DB is in useful state) for another resource is a question I don't know answer to (yet).
### 3. Use the `DBInstanceStatus`

Even if you don't agree with any of the two points above, I think the user should at least be able to see what's happening behind the scenes if the API is able to give it. As mentioned above, there are three stages during the initial start in which instance can be:
- `creating`
- `backing-up`
- `available`

and we're only representing two stages which makes a huge difference in UX if we're talking about XX minutes.
---

Over and over, I wish AWS would be offering better API for this, something like Twitter Streaming API - one just listens on a socket and doesn't waste HTTP traffic on asking if it's ready when 90% of the time API says no. I may ask the AWS support about this.

**Comment by JeanMertz** [comment]
I am highly in favour of option 2.

We need the endpoint as an output variable, but there is no reason for us to wait for the backup to finish. This would greatly speed-up our deployment process. :+1:

**Comment by catsby** [comment]
Hey @radeksimko – I'm going to close this for now. 

- We now log the status during curation (assuming we have one) during creation: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_instance.go#L1048
- We have long term plans to expose a generic `timeout` block / config structure to allow users to fine-tune their own timeouts for create/update/delete

> First of all I think that in many cases, user just may not want to wait for the RDS if it's really not a blocker in the dependency graph (i.e. you're not building other resources on the top of it).

This is a really interesting idea (possible optimizations if a resource can know that it's a end vertex in the graph) I'll bring it up internally, thanks!
