### ISSUE TITLE
Resource Address parsing doesn't fail when given insufficient segments

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#10982]
When given a resource address that is missing the resource type element, the resource address parser behaves strangely.

For example:

```
bash-3.2$ terraform import module.event_store.eventstore-deadletter-queue-arn arn:aws:sqs:us-east-1:165918379116:qa-event-store-dead-letter

Error importing: 1 error(s) occurred:
* module.event_stor.e.eventstore-deadletter-queue-arn (import id: arn:aws:sqs:us-east-1:165918379116:qa-event-store-dead-letter): provider e couldn't be found
```

Notice that the last letter of the module name got matched as the resource type, which then caused Terraform to try to locate a provider called "e".

(Reported by @apenney on Glitter)

---

This invalid resource address should produce an error. The following test demonstrates the failure and should pass after it's fixed:

```go
func TestParseResourceAddress_invalid(t *testing.T) {
	cases := []string{
		"module.event_store.eventstore-deadletter-queue-arn",
	}

	for _, tc := range cases {
		t.Run(tc, func(t *testing.T) {
			_, err := ParseResourceAddress(tc)

			if err == nil {
				t.Fatalf("%q successfully parsed; want error", tc)
			}
		})
	}
}
```

My guess is that this is caused by the optional period at the end of the module part of the matching pattern:

```go
		// "module.foo.module.bar" (optional)
		`(?P<path>(?:module\.[^.]+\.?)*)` +
```

A period should be required here when something follows; it's presumably optional to allow the parsing of a direct reference to a module. It might be simplest to rewrite this to process each period-separated segment separately rather than try to match the whole thing as a single regex.

**Comment by mitchellh** [comment]
Test passes on master. The error message isn't super friendly but it'll do. Pushed the test so in the future we test against it.
