### ISSUE TITLE
VSphere Crash

### ISSUE THREAD

**Issue by ex3ndr** [hashicorp/terraform#10996]
My Terraform installation crashes on this line. DeviceId is equal to one, but i have only one network adapter.

https://github.com/hashicorp/terraform/blob/3840ff0f40138226bcea438f4155b2754d81f90d/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L1066

Latest Terraform (v0.8.2) and vSphere v5.5

**Comment by stack72** [comment]
Hi @ex3ndr 

Please can you send the crash log so we can try and reproduce this?

Thanks

Paul

**Comment by ex3ndr** [comment]
[crash.txt](https://github.com/hashicorp/terraform/files/682627/crash.txt)

More info:
I am using CoreOS. Where Docker and FlunnelD are installed there are much more IP Addresses and terraform crashes when trying to refresh their state. With machines without CoreOS (where only one IPv4 is reported by vmware) everything works fine.
