### ISSUE TITLE
[bug,aws, aws_kinesis_stream]"retention_period" must be between 24 and 168 hours

### ISSUE THREAD

**Issue by spy-tech** [hashicorp/terraform#10992]
Terraform claims for resource `aws_kinesis_stream` that  `"retention_period" must be between 24 and 168 hours. `

This is incorrect. See: http://docs.aws.amazon.com/kinesis/latest/APIReference/API_DecreaseStreamRetentionPeriod.html.

While the corresponding creation Amazon API might not allow lower values, an implementation is possible (and should be done) which first sets 24 and then calls the above API. That's one of the points of Terraform (that we can abstract about silly API stuff like this).

**Comment by spy-tech** [comment]
It appears that there is a bug in all AWS bindings: https://github.com/aws/aws-cli/issues/2357. As such, we currently cannot expect the Terraform project to fix this. However, please keep this ticket open, until Amazon fixes the implementation being used by Terraform.

**Comment by spy-tech** [comment]
@stack72 This ticket can be closed; Amazon claims that aws/aws-cli#2357 was a documentation bug, as opposed to a bug in their services. For the record, the API call `DecreaseStreamRetentionPeriod` is (still is at the time of writing) specified to accept `1-100000` as valid parameters, but in fact only accepts `24-168`.

I would be interested in hearing more such cases where Amazon decided that the documentation was wrong and not the service.

**Comment by stack72** [comment]
Thanks for letting me know @spy-tech 

Please do ping me on this ticket if you find things can be changed

Paul
