### ISSUE TITLE
terraform crashes while running 'terraform refresh' after powering off VSphere VM.

### ISSUE THREAD

**Issue by sripadkollur** [hashicorp/terraform#10998]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- Multiple Vsphere resources 

### Terraform Configuration Files
```json
{
    "provider": {
        "vsphere": {
            "user": "root",
            "password": "****",
            "vsphere_server": "X.X.X.X",
            "allow_unverified_ssl": true,
            "alias": "my_alias"
        }
    },
    "variable": {
        "count": {
            "description": "Number of VMs to create",
            "default": 1
        }
    },
    "resource": {
        "vsphere_virtual_machine": {
            "vsphere_vm": {
                "provider": "vsphere.my_alias",
                "count": "${var.count}",
                "name": "vsphere-vm-${count.index}",
                "vcpu": 2,
                "memory": 4096,
                "datacenter": "MY_DATA_CENTER",
                "cluster": "Dev_Cluster",
                "network_interface": {
                    "label": "MY_NETWORK"
                },
                "disk": {
                    "template": "Demo2_Windows_Template2",
                    "datastore": "SharedDatastore"
                },
                "dns_suffixes": ["mylab.local","mylab.remote"],
                "time_zone": "190"
            }
        }
    }
}
```

### Debug Output
https://gist.github.com/sripadkollur/19799526689746dc45ada3c4cd7eb889
### Panic Output
https://gist.github.com/sripadkollur/177e2eb41ff3ded1374b3d072a229fa9

### Expected Behavior
The 'terraform refresh' command should not crash, if there is any issue it should display valid error message.

### Actual Behavior
Terraform is crashing.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a VM on Vsphere provider(May happen on other providers as well . I did not check)
2. Add a virtual NIC to running Vsphere VM using Vcenter or some other vmware tool.
3. Power Off the VM
4 Run  `terraform refresh`

### Important Factoids
VMware  vCenter server version 5.5.0
vSphere client version 5.5.0
### References
None

**Comment by ex3ndr** [comment]
Looks like my issue #10996 is a same, but powering off is not related to it.
