### ISSUE TITLE
Add aws_api_gateway_integration_response content_handling

### ISSUE THREAD

**Issue by przemos** [hashicorp/terraform#11000]
It would be good to have a support for content_handling attribute in aws_api_gateway_integration_response element with values CONVERT_TO_TEXT/CONVERT_TO_BINARY.

http://docs.aws.amazon.com/cli/latest/reference/apigateway/put-integration-response.html

It is necessary to have proper support for assets like images or css that are served from S3 proxied through API Gateway.

**Comment by stack72** [comment]
Hi @przemos 

Thanks for getting in touch here - I believe that content handling was added here https://github.com/hashicorp/terraform/issues/10776 - this was released as part of Terraform 0.8.2

If there are any issues, please do let me know

Thanks

Paul

**Comment by przemos** [comment]
Hi @stack72 ,

I cannot find it in the document. Is it that it is yet to be added ?

**Comment by stack72** [comment]
Hi @przemos 

Apologies, this was only added to `aws_api_gateway_integration` it seems - I have reopened the original issue so we can get this added. #10696

Thanks

Paul
