### ISSUE TITLE
scaleway provider: TLS handshake timeout

### ISSUE THREAD

**Issue by mgilbir** [hashicorp/terraform#11007]
### Terraform Version
Terraform v0.8.2

### Terraform Configuration Files
I'm using [this project](https://github.com/edouardb/kubernetes-terraform-scaleway) with proper credentials.

### Expected Behavior
A new set of machines get deployed

### Actual Behavior
No resources are created and the whole thing fails with:
```
Error applying plan:

1 error(s) occurred:

* scaleway_server.kubernetes_master: Post https://cp-ams1.scaleway.com/servers: net/http: TLS handshake timeout
```

### Important Factoids
Using curl with valid credentials against the API endpoint works, so it is not a problem with the remote server being down. Certificates seem to be valid.

```
curl -H 'X-Auth-Token: REDACTED' -H 'Content-Type: application/json' https://cp-ams1.scaleway.com/servers -v
*   Trying 51.15.33.64...
* Connected to cp-ams1.scaleway.com (51.15.33.64) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.scaleway.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /servers HTTP/1.1
> Host: cp-ams1.scaleway.com
> User-Agent: curl/7.43.0
> Accept: */*
> X-Auth-Token: 5cdf25ef-9330-4647-bfdd-a0409f15fd95
> Content-Type: application/json
>
< HTTP/1.1 200 OK
< Server: Tengine
< Date: Tue, 03 Jan 2017 17:49:09 GMT
< Content-Type: application/json
< Content-Length: 15
< Connection: keep-alive
< X-Total-Count: 0
< Link: </servers?page=0&per_page=50&>; rel="last"
< Strict-Transport-Security: max-age=15552000
<
* Connection #0 to host cp-ams1.scaleway.com left intact
{"servers": []}%
```

### References
I've seen other issues mentioning problems with TLS timeouts but saw that @mitchellh mentioned [here](https://github.com/hashicorp/terraform/issues/10882#issuecomment-268609827) it would be fixed in 0.8.2. As I'm running that version, I'm not sure it is related or not.

**Comment by dwa** [comment]
I've run into the same problem, also with scaleway.

Perhaps it's worth pointing out that, for me at least, this is an intermittent problem.

When it manifests itself, I've noticed that I can work around it by setting the `TF_LOG` environment variable. E.g.,:

`$ TF_LOG=INFO terraform ...`

**Comment by nicolai86** [comment]
@mgilbir thanks for reporting this. I suspect this being a remote API issue, however I'd recommend running terraform with `TF_LOG=debug` and `SCW_VERBOSE_API=true`, which should trigger verbose logs from the scaleway API SDK. 

It would be great if you could gist the SDK logs.

**Comment by mwarkentin** [comment]
@mgilbir @dwa @nicolai86 Just wondering how you installed Terraform? We started running into similar issues with the cloudflare provider when using a brew installed terraform 0.8.2, however it worked fine with the download from terraform.io.

**Comment by mgilbir** [comment]
It seems to be working now 🤔

I had run it once with `TF_LOG=debug` I remember that I didn't see anything other than trying to talk to the API and failing with the previously mentioned `net/http: TLS handshake timeout`. Unfortunately, I didn't save the output :/

I didn't know about the `SCW_VERBOSE_API=true`, so I'll give it another try if/when I manage to reproduce the problem.

@mwarkentin Indeed, I installed it with homebrew

**Comment by mwarkentin** [comment]
@mgilbir Some other people have mentioned that it was intermittent with the brew installed version, so it may be worth retrying a few times (or maybe you did this already).

**Comment by nicolai86** [comment]
closing as this seemingly did not re-surface.

**Comment by mwarkentin** [comment]
This was fixed on the homebrew side of things (if that was the issue here). See the reference above.

**Comment by nicolai86** [comment]
thanks for the clarification, @mwarkentin ❤️
