### ISSUE TITLE
Unable to set region on resource level for scaleway_server

### ISSUE THREAD

**Issue by bkleef** [hashicorp/terraform#11017]
### Terraform Version
0.8.2

### Affected Resource(s)
- scaleway_server

### Expected Behavior
I expect to set (or override) region/zone on resource level like [Google](https://www.terraform.io/docs/providers/google/r/compute_instance.html#zone) or [DigitalOcean](https://www.terraform.io/docs/providers/do/r/droplet.html#region).

### Actual Behavior
I'm stuck with one region.

**Comment by nicolai86** [comment]
@bkleef what about using multiple, identical `scaleway` providers, just with different zones?

in theory this should work:

```
provider "scaleway" {
  alias = "paris"
  organization = ""
  access_key = ""
  region = "par1"
}

provider "scaleway" {
  alias = "amsterdam"
  organization = ""
  access_key = ""
  region = "ams1"
}

resource "scaleway_server" "paris-a" {
  provider = "scaleway.paris"
}

resource "scaleway_server" "amsterdam-a" {
  provider = "scaleway.amsterdam"
}
```

the other option (per resource zone) can't be implemented ATM since the region attribute is private inside the official scaleway sdk, meaning we can't change this without re-creating the underlying provider connection, which might bring all kinds of pain with it…

**Comment by bkleef** [comment]
@nicolai86 thanks a lot for your suggestion! I will try this and let you know!

**Comment by nicolai86** [comment]
I'll close this issue due to inactivity. @bkleef let me know if the above approach worked for you.

**Comment by bkleef** [comment]
@nicolai86 I'm using modules to isolate the same functionality over multiple cloud providers. Your example didn't work within that structure. I had to set `region` in de specific module.

```
➜  terraform git:(master) ✗ tree
.
├── Makefile
├── README.md
├── main.tf
├── modules
│   └── docker
│       └── scaleway
│           └── scaleway.tf
└── provider
    ├── cloudflare.tf
    └── scaleway.tf
```
```
➜  terraform git:(master) ✗ cat provider/scaleway.tf
variable "scaleway_organization" {
  description = "Set var or env SCALEWAY_ORGANIZATION."
}

variable "scaleway_access_key" {
  description = "Set var or env SCALEWAY_ACCESS_KEY."
}

provider "scaleway" {
  organization = "${var.scaleway_organization}"
  access_key   = "${var.scaleway_access_key}"
}
```
```
➜  terraform git:(master) ✗ cat modules/docker/scaleway/scaleway.tf
variable "count" {
  default = 0
}

variable "name" {}

variable "zone" {}

variable "domain" {}

variable "type" {}

provider "scaleway" {
  region = "${var.zone}"
}

...
```
