### ISSUE TITLE
Add AWS API Gateway Usage Plan support

### ISSUE THREAD

**Issue by przemos** [hashicorp/terraform#11022]
Hi,

API Gateway is evolving really fast and new features are arriving at a quick pace. One of the abilities usage plan provides and is quite important is securing your API with a key. 

http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-usage-plans-with-rest-api.html

Would it be possible to add support for defining usage plans?

**Comment by sebolabs** [comment]
+1

**Comment by madpawel** [comment]
+1

**Comment by ianxharris** [comment]
+1

**Comment by wbadowski** [comment]
+1

**Comment by svanzoest** [comment]
relates to #8532

**Comment by stack72** [comment]
Hi all

This is a duplicate of #8532

Going to close this one and direct all requested etc to that issue

Thanks

Paul
