### ISSUE TITLE
Creating RDS instance from snapshot errors - InvalidVPCNetworkStateFault: You cannot move DB instance _rds_instance_name_ to subnet group 

### ISSUE THREAD

**Issue by sasq31** [hashicorp/terraform#11024]
Hi,

I'm creating an issue off the back of a thread on the following PR - https://github.com/hashicorp/terraform/pull/10818

In there I've found that I can successfully create a RDS from snapshot on using 0.8.0 but cannot on 0.8.3 (yet to personally test .1 and .2)

The error message I get looks like the AWS api returning an error on a modify operation :

`Error applying plan:`
`1 error(s) occurred:`

`* aws_db_instance._resource_name_: Error modifying DB Instance _rds_instance_name_: InvalidVPCNetworkStateFault: You cannot move DB instance _rds_instance_name_ to subnet group _subnet_group_name_. The specified DB subnet group and DB instance are in the same VPC. Choose a DB subnet group in different VPC than the specified DB instance and try again. status code: 400, request id: 7f594101-cced-11e6-b996-2141c7b3473f`

`Terraform does not automatically rollback in the face of errors. Instead, your Terraform state file has been partially updated with any resources that successfully completed. Please address the error above and apply again to incrementally change your infrastructure.`

Terraform gets passed in the correct values for security group id and subnet group etc, creates it but bombs out when the rds instance goes into a modifying state.

I believe @stack72 is already looking into this, but I'm raising the issue here so others can see a fix is being looked into.

**Comment by stack72** [comment]
Thanks for opening a real issue on this for tracking @sasq31 :)

**Comment by n-my** [comment]
I had the same bug. It had been introduced in 0.8.2 (working fine with 0.8.1).

**Comment by stack72** [comment]
Hi all

I found the issue here, I am just opening a PR that fixes it

Paul
