### ISSUE TITLE
Microsoft Azure (RM) LB does not set the load balancing rules correctly 

### ISSUE THREAD

**Issue by dobrerazvan** [hashicorp/terraform#11028]
Hi there,

### Terraform Version
dobre-osx:Work dobre$ terraform -v
Terraform v0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_lb_rule

### Terraform Configuration Files
```hcl
provider "azurerm" {
  subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
}

variable "customer" {
  type = "string"
  default = "razvan"
}

variable "environment" {
  type = "string"
  default = "prod"
}

variable "region" {
  type = "string"
  default = "North Europe"
}

###############################################################################
# Customer X
resource "azurerm_resource_group" "customerx" {
    name = "customerx-${var.environment}"
    location = "${var.region}"
}

resource "azurerm_public_ip" "customerx_ip" {
    name = "customerx-ip-${var.environment}"
    location = "${var.region}"
    resource_group_name = "${azurerm_resource_group.customerx.name}"
    public_ip_address_allocation = "dynamic"
}

resource "azurerm_lb" "customerx_lb" {
    name = "customerx-lb-${var.environment}"
    location = "${var.region}"
    resource_group_name = "${azurerm_resource_group.customerx.name}"

    frontend_ip_configuration {
      name = "customerx-fep-ip-${var.environment}"
      public_ip_address_id = "${azurerm_public_ip.customerx_ip.id}"
    }
}

resource "azurerm_lb_rule" "port_80" {
  location = "${var.region}"
  resource_group_name = "${azurerm_resource_group.customerx.name}"
  loadbalancer_id = "${azurerm_lb.customerx_lb.id}"
  name = "customerx-port-80-${var.environment}"
  protocol = "Tcp"
  frontend_port = "80"
  backend_port = "80"
  frontend_ip_configuration_name = "customerx-fep-ip-${var.environment}"
}

resource "azurerm_lb_backend_address_pool" "customerx_lb_back_addr_pool" {
  location = "${var.region}"
  resource_group_name = "${azurerm_resource_group.customerx.name}"
  loadbalancer_id = "${azurerm_lb.customerx_lb.id}"
  name = "customerx-lb-back-addr-pool-${var.environment}"
}

resource "azurerm_lb_probe" "customerx_lb_probe" {
  location = "${var.region}"
  resource_group_name = "${azurerm_resource_group.customerx.name}"
  loadbalancer_id = "${azurerm_lb.customerx_lb.id}"
  name = "customerx-port-22-probe-${var.environment}"
  port = 22
}

```

### Actual Behavior
<img width="1268" alt="screen shot 2017-01-04 at 4 07 15 pm" src="https://cloud.githubusercontent.com/assets/11867948/21644947/b28678aa-d298-11e6-9eb3-8f08291d221b.png">

The form's mandatory fields does not fill up.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. check the lb rule in the azure portal

Thanks

**Comment by pmcatominey** [comment]
Hi @dobrerazvan 

I've just ran your included config and I see the same in the portal, empty fields, however the Azure API reports that the rule is there and has the correct values for both the frontend and backend ports.

Could you look at the [Resource Explorer](https://resources.azure.com) and find your load balancer in the tree on the left? If you can see the correct port like in the image below then I think this is actually an Azure Portal bug.

![image](https://cloud.githubusercontent.com/assets/918856/21646704/20606f02-d28f-11e6-9082-bb84710aad6a.png)

**Comment by dobrerazvan** [comment]
Hi @pmcatominey 

Thanks for the reply.

I just checked the cli and it looks ok. I will also check your suggestion.

`
data:    Name                            : customerx-lb-prod
data:    Type                            : Microsoft.Network/loadBalancers
data:    Location                        : northeurope
data:    Provisioning state              : Succeeded
data:
data:    Frontend IP configurations:
data:    Name                   Provisioning state  Private IP allocation  Private IP   Subnet  Public IP
data:    ---------------------  ------------------  ---------------------  -----------  ------  -----------------
data:    customerx-fep-ip-prod  Succeeded           Dynamic                                     customerx-ip-prod
data:
data:    Probes:
data:    Name                          Provisioning state  Protocol  Port  Path  Interval  Count
data:    ----------------------------  ------------------  --------  ----  ----  --------  -----
data:    customerx-port-22-probe-prod  Succeeded           Tcp       22          15        2
data:
data:    Backend Address Pools:
data:    Name                    Provisioning state
data:    ----------------------  ------------------
data:    customerx-lb-back-prod  Succeeded
data:
data:    Load Balancing Rules:
data:    Name                    Provisioning state  Load distribution  Protocol  Frontend port  Backend port  Enable floating IP  Idle timeout in minutes
data:    ----------------------  ------------------  -----------------  --------  -------------  ------------  ------------------  -----------------------
data:    customerx-port-80-prod  Succeeded           Default            Tcp       80             81            false               4
info:    network lb show command OK
`

**Comment by dobrerazvan** [comment]
Yep, bug in the Azure UI. Will open a case with Azure.

Thanks for your help.

**Comment by stack72** [comment]
Thanks for the report @dobrerazvan and thanks for troubleshooting @pmcatominey :)

**Comment by paveldokov** [comment]
Hi,

I have the same problem - most importantly, rules do not work. I redid the rules manually and they work.

Any further development?

**Comment by psteinmc** [comment]
I'm also having this problem, load balancers created this way do not pass traffic.
