### ISSUE TITLE
Terraform crash when testing Datadog provider inheritance

### ISSUE THREAD

**Issue by GrantSheehan** [hashicorp/terraform#11038]
Hi there,

I was trying to create a test scenario to determine why Datadog provider credentials weren't being inherited by deeply nested modules, and I ran into this crash when creating it. I have a pair of custom providers declared in my terraformrc, moving the terraformrc and rerunning made no difference.

### Terraform Version
`Terraform v0.8.2`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- datadog_monitor

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
[Link](https://www.dropbox.com/s/pq0fqgnd2a9q6s2/tf_crash.tar.gz?dl=0) for config files and crash log

### Panic Output
https://gist.github.com/GrantSheehan/717aef6a1f32508839ca683bf9247518

### Expected Behavior
Not crashing :(

### Actual Behavior
Crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform get`
2. `terraform apply`

**Comment by mitchellh** [comment]
LOL (at myself), this is caused by a module named "root". Oh my.

I'm looking into this. :(
