### ISSUE TITLE
Targeting resources on apply yields an error that not targeting does not

### ISSUE THREAD

**Issue by nwalke** [hashicorp/terraform#11039]
### Terraform Version
0.8.2

### Affected Resource(s)
Probably Terraform core...

### Terraform Configuration Files
I have a module called serc.  I define my variable `serc_instance_size` like this:
```
variable "serc_instance_size" {
  type = "string"
}
```
I then have another module nested within serc called auto-scaling.  I call it like so...
```
module "auto-scaling" {
  source                 = "auto-scaling"
  priv_ids               = "${var.priv_ids}"
  serc_elb_name          = "${module.load-balancing.serc_elb_name}"
  serc_instance_size     = "${var.serc_instance_size}"
  serc_security_group_id = "${module.security.serc_security_group_id}"
  fms_role_name          = "${var.fms_role_name}"
  codedeploy_environment = "${var.codedeploy_environment}"
  aws_region             = "${var.aws_region}"
}
```
The variable definition in the auto-scaling module is defined like so:
```
variable "serc_instance_size" {
  type = "string"
}
```
It is used in one spot here:
```
resource "aws_launch_configuration" "serc" {
  name_prefix                 = "serc"
  image_id                    = "${data.atlas_artifact.serc.metadata_full.ami_id}"
  instance_type               = "${var.serc_instance_size}"
  associate_public_ip_address = false
  security_groups             = ["${var.serc_security_group_id}"]
  iam_instance_profile        = "${var.fms_role_name}"
  user_data                   = "${file("${path.module}/set_hostname.sh")}"

  root_block_device {
    volume_type           = "gp2"
    volume_size           = 20
    delete_on_termination = true
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output
Here ya go...  https://gist.github.com/nwalke/54957b47c83d642e96c0b5ea4841e1da

### Expected Behavior
I expected Terraform to try to apply my changes.

### Actual Behavior
It gave me this error:
```
Error configuring: Unexpected value for InstanceType field: "serc"
```

### Important Factoids
This is a module within a module where the variable actually gets used.  I'm not sure if there's a difference in how that gets processed with a targeted apply vs a regular apply.  Note that my targeted apply is not referencing the parent module, but the child underneath.

**Comment by mitchellh** [comment]
Hey there, thanks for reporting this. I've tried a couple nested (double-nested) modules and vars and targeting and I couldn't find a way to get similar behavior. And unfortunately your infrastructure is quite complex so the log is hard to grok... I don't see anything obvious that stands out anyways.

If you can find a way to get a smaller reproduction that I can run on my machine with a bit of effort, then I'd be very very happy and would love to look at it. Right now though I'm kind of chasing things around and not getting much of anywhere. :) Thanks!

If you can do that, just open a new issue. It'll pop to the top that way.

**Comment by nwalke** [comment]
I appreciate the effort.  I'll try to recreate a more simple example.  Thanks!
