### ISSUE TITLE
Trying to create a CNAME 

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#11044]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

Terraform v0.7.11
Trying to create a CNAME and append the domain name 

resource "aws_route53_record" "CNAME_quartztest" {
  zone_id = "ZACAZ1YK2A6T"
  name = "quartztest.${var.environment}"
  type = "CNAME"
  ttl = "5"
  records = ["${module.mod_iweb.tag_name}.${var.domain}"]

I get below error. It works fine once I dont append the domain name, any way around this?

Error running plan: 1 error(s) occurred:

* At column 3, line 1: output of an HIL expression must be a string, or a single list (argument 1 is TypeList) in:

${module.mod_iweb.tag_name}.${var.domain}

**Comment by catsby** [comment]
Hey @davyt10 can you share what `${module.mod_iweb.tag_name}` is? Without exposing secrets of course 😄

**Comment by davyt10** [comment]
Sure.It's the Name tag output from the below module.

module "mod_iweb" {
  source            = "../../../modules/Roles/mod_win_instance"
  count             = "1"
  ami               = "${var.ami["Server2k8R2"]}"
  az                = ["${lookup(var.availability_zone, var.az_mapping)}"]
  userdata = "none"
  aws_key_name      = "${var.aws_key_name}"
  type              = "t2.medium"
  securitygroup_role= ["${module.iweb_sg.QA_IWEB_SG_ID}"]
  subnet_private    = ["${var.subnet_private_nat}"]
  data_vol_size     = "30"
  log_vol_size      = "10"
  environment       = "${var.environment}"
  domain            = "dev.xxxxxx.com"
  template          = "${var.template}"
  application       = "${var.application}"
  application_role  = "IntranetWeb"
  hostrole          = "IWEB"
  tag_owner         = "None"
  tag_owner_email   = "None"
}

**output "tag_name"    { value = ["${aws_instance.instance.*.tags.Name}"]}**
