### ISSUE TITLE
Change Suggestion - ability to dump variables after a plan

### ISSUE THREAD

**Issue by CarlInglis** [hashicorp/terraform#11048]
I am having issues with a large, modular, terraform setup. 

Specifically I want to be able to dump out the variables after interpolation in the plan - but without applying the plan (so the `output` command isn't any use here).

The `console` doesn't allow me to pass in values via the command line, which is how these values are being passed to the terraform command in my environment.

Ideally something along the lines of a `-dump-vars` option to the `plan` command, which would just dump out the key/value pairs for every variable it's been able to work out.

If there's another method of doing this then all help would be appreciated.

Thanks.

**Comment by apparentlymart** [comment]
Hi @CarlInglis! Thanks for the suggestion.

As a workaround for now, you could perhaps interpolate the interesting variables into the triggers of a dummy `null_resource`, which should then cause them to show up in the plan for that resource:

```hcl
resource "null_resource" "show_variables" {
  triggers {
    something_interesting = "${var.something_interesting}"
  }
}
```

A `null_resource` does nothing on its own, so you could potentially leave this in your config for ongoing use.

In the longer term, a way to get Terraform to more verbosely explain what values it has figured out could be pretty useful, I agree.

**Comment by CarlInglis** [comment]
Hi @apparentlymart,

null_resources are interesting - wasn't aware of them - however they do require a plan to be built, and my problem was that the plan wasn't building because of an interpolation issue screwing over a data resource. I've sorted the issue out (and taught myself to spell), so it's not an issue for me now, but I'll bear null_resources in mind! :)

(To my mind, the key is to be able to dump after a failed plan stage - I accept that it may not have been able to work out many of the variables, but some information is better than none.) :)

**Comment by mildwonkey** [comment]
Hello, thanks for submitting this!
We have a new option in terraform 0.12. You can write the output of the plan to a file, then run [`terraform show -json $planfile`](https://www.terraform.io/docs/commands/show.html#json-output) to dump all of the plan's data, including variables!
Between that and martin's suggestion, I am going to close this feature request. Thanks!
