### ISSUE TITLE
Rancher_stack wants to finish_upgrade even the upgrade is already finished

### ISSUE THREAD

**Issue by mcanevet** [hashicorp/terraform#11054]
### Terraform Version
v0.8.2

### Affected Resource(s)
- rancher_stack

### Terraform Configuration Files
```hcl
resource "rancher_stack" "foo" {
  name = "foo"
  environment_id = "${var.environment_id}"
  start_on_create = true
  finish_upgrade = true
}
```

### Expected Behavior
Terraform should be convergent when importing existing resource

### Actual Behavior
Terraform wants to finish upgrade when importing existing resource

### Steps to Reproduce
1. create you terraform manifest
2. Import an existing stack with `terraform import`
3. Run `terraform apply`

Terraform wants to finish an upgrade even if there is no upgrade to finish:

```
~ rancher_stack.foo
    finish_upgrade: "" => "true"
```

**Comment by johnrengelman** [comment]
This is simply a state setting. The `finish_upgrade` is not a value that is stored on the stack in Rancher. It's more of an operational flag when upgrading a stack.

Not sure that best way to address this. @mitchellh is there a way to mark a property in the `Schema` as a transient that is not stored in the state file?

**Comment by johnrengelman** [comment]
@stack72 thoughts on this? the `finish_upgrade` attribute is behavioral setting and not something stored on the actual resource.

I guess we could update the `read` method to set the value to the same default?

**Comment by stack72** [comment]
I would set it as follows:

`d.Set("finish_upgrade", d.Get("finish_upgrade).(bool))`

and not worry too much about it :)

**Comment by johnrengelman** [comment]
Patch https://github.com/hashicorp/terraform/pull/12545
