### ISSUE TITLE
terraform graph -type=legacy panics

### ISSUE THREAD

**Issue by kitsunde** [hashicorp/terraform#11052]
I have no idea what `-type=legacy` is for, I was just curious to see what it did and presumably it's supposed to work or at least not crash.

### Terraform Version

0.8.2

### Affected Resource(s)

Seems like anything causes it but specifically I tried:

- aws_route53_zone
- aws_s3_bucket

### Terraform Configuration Files

Something as small as:

```hcl
data "aws_route53_zone" "site" {
  name = "mediapop.co."
}
```

### Panic Output

https://gist.github.com/kitsunde/274e99a67c8af28f4e86d86e5c8620a1

**Comment by mitchellh** [comment]
I'm looking into this, but `-type=legacy` uses the graph builders that were present in Terraform 0.7.x (and introduced in Terraform 0.3.x). Terraform 0.8.0 introduced new graph builders so the flag is mostly there for situations where you feel the new graphs look weird and the old ones were right.
