### ISSUE TITLE
Diff shows changes to existing resource when increasing count

### ISSUE THREAD

**Issue by pmcatominey** [hashicorp/terraform#11061]
When increasing a count of resources which contain an interpolation that can't be resolved at plan time, the existing resources show up as requiring changes in the plan. The example before is smaller than our original test case and uses smaller resources in the AzureRM provider for ease of testing. Our original test case was with the `azurerm_virtual_machine` and it's `storage_os_disk.<hash>.vhd_uri` property contained the interpolation, unfortunately this property is ForceNew so increasing the count would cause Terraform to recreate existing VMs.

### Terraform Version

Terraform v0.8.3-dev (c7f6b3782695e8931370183e92ed387f7d968434)

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
variable "count" {
    default = 2
}

resource "azurerm_resource_group" "test" {
    name = "my-resource-group"
    location = "northeurope"
}

resource "azurerm_public_ip" "test" {
    name = "my-public-ip-${count.index}"
    location = "northeurope"
    resource_group_name = "${azurerm_resource_group.test.name}"
    public_ip_address_allocation = "Dynamic"
    count = "${var.count}"
}

resource "azurerm_lb" "test" {
    name = "my-lb-${count.index}"
    location = "northeurope"
    resource_group_name = "${azurerm_resource_group.test.name}"
    count = "${var.count}"

    frontend_ip_configuration {
      name = "PublicIPAddress"
      public_ip_address_id = "${element(azurerm_public_ip.test.*.id, count.index)}"
    }
}
```

### Expected Behavior
When increasing the count the existing resource(s) should not appear in the plan as they have not actually changed.

### Actual Behavior
When increasing the count the existing resource shows up as requiring modifications in the plan due to an interpolation which requires values at apply time:

```
~ azurerm_lb.test.0
    frontend_ip_configuration.0.public_ip_address_id: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/peter-testing-hash/providers/Microsoft.Network/publicIPAddresses/my-public-ip-0" => "${element(azurerm_public_ip.test.*.id, count.index)}"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
1. `terraform apply`
1. increase `count` variable
1. `terraform plan`

### Important Factoids
It appears that the reason the resources show up in the diff is because the value of the interpolation is not known until part way through the apply operation. I have also seen this issue affect the `azurerm_virtual_machine` resource with values in nested Sets. In those cases it appears that the hash function was being given the source of the interpolation string itself.

**Comment by mitchellh** [comment]
Dup #3449.
