### ISSUE TITLE
teraform github provider ignoring lifecycle -> prevent destroy

### ISSUE THREAD

**Issue by michalbagrowski** [hashicorp/terraform#11064]
```
 resource "github_repository" "test_repository_name" {
     name = "test_repository_name"
     has_downloads = false
     has_issues = false
     has_wiki = false
     private = true
     description = ""
     homepage_url= ""
     lifecycle {
         prevent_destroy = true
     }
 }
```

`terraform --version
Terraform v0.8.2`

After creating repository with prevent_destroy, and removing repository entry from tf file is cousing also delete for repository on github, no errors.

It looks like it is ignoring this entry.

**Comment by leowmjw** [comment]
As per doc; "prevent_destroy" comes into play only on "terraform plan":

"prevent_destroy (bool) - This flag provides extra protection against the destruction of a given resource. When this is set to true, any plan that includes a destroy of this resource will return an error message."

You can try the following (after creating the resource; set count=1); and you should see the error when running "terraform plan" (Note the use of count):

```
resource "github_repository" "test_repository_name" {
     count = 0
     name = "test_repository_name"
     has_downloads = false
     has_issues = false
     has_wiki = false
     private = true
     description = ""
     homepage_url= ""
     lifecycle {
         prevent_destroy = true
     }
 }
```

**Comment by mitchellh** [comment]
@leowmjw is correct.

By deleting it from the configuration you're actually removing the "prevent_destroy" option and therefore removing the termination protection: you're actually explicitly telling Terraform it is okay to delete it. 

There are some other enhancement+core tagged issues that are requesting an even stricter termination protection to get the behavior you want (where the "prevent destroy" is persisted into the state). We've left those open to support that in the future.
