### ISSUE TITLE
Can't provide map value via -var CLI flag.

### ISSUE THREAD

**Issue by CPWeaver** [hashicorp/terraform#11068]
I am unable to provide an HCL map value via the `-var` CLI flag. It works fine if I change `test` to be either a list of string. I found issues relating to maps but none that seemed the same to me...thanks! 

### Terraform Version
Terraform v0.8.2

### Affected Resource(s)
- map variables

### Terraform Configuration Files
```hcl
variable test {
  type="map"
}
```

### Expected Behavior
Terraform should successfully parse a map provided via the `-var` CLI flag.

### Actual Behavior
Terraform fails with this error, 
`invalid value "test={\"a\":\"b\"}" for flag -var: Cannot parse value for variable ("{\"a\":\"b\"}") as valid HCL: At 1:9: illegal char`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -var 'test={"a":"b"}' .`

**Comment by mitchellh** [comment]
`-var 'test={a = "b"}'`
