### ISSUE TITLE
non-existing changes being detected in security groups

### ISSUE THREAD

**Issue by tomstachura** [hashicorp/terraform#11069]
I just ran plan on an environment which hasn't changed since September, with the newest version of terraform, and it detects changes on security groups where there are no changes.
For example:
~ module.qa1.aws_security_group.ui
    ingress.#:                            "0" => "1"
    ingress.1226990705.cidr_blocks.#:     "0" => "0"
    ingress.1226990705.from_port:         "" => "80"
    ingress.1226990705.protocol:          "" => "tcp"
    ingress.1226990705.security_groups.#: "0" => "1"
    ingress.1226990705.security_groups.0: "" => ""
    ingress.1226990705.self:              "" => "false"
    ingress.1226990705.to_port:           "" => "80"

The port is already 80.

Not only that - if I try to run apply, I get this:

* aws_security_group.ui: Error authorizing security group ingress rules: MissingParameter: Source group ID missing.
        status code: 400, request id: 773ad5fb-e57d-41df-bdea-4d95e32a005f

I don't get what's missing from this code, because it worked:

resource "aws_security_group" "web" {
  name        = "${var.env_name}-WEB"
  description = "${var.env_name}-WEB"
  vpc_id      = "${module.vpc.vpc_id}"
  tags {
    Name  = "${var.env_name}-WEB"
    Group = "${var.env_name}"
  }

  # access from WEB load balancer
  ingress {
    from_port       = 8080
    to_port         = 8080
    protocol        = "tcp"
    security_groups = ["${module.lb_web.security_groups}"]
  }

  # outbound internet access
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

Terraform has actually removed these ingress rules and now the environment is broken.

Any ideas? 

Thank you.

**Comment by grubernaut** [comment]
Hi @tomstachura, thanks for the issue! 

What version of Terraform were you running before, and what version of Terraform were you on when you encountered the issues? 

Do you also have a full example config that I could use to reproduce the errors you're encountering? I'm mainly curious if there was a combination of in-line security group rules, and separate `aws_security_group_rule` resources.

Thanks!

**Comment by tomstachura** [comment]
Hi,

 

It happened with the latest version. I believe, it’s 0.8.2. I reverted to 0.8.1 and it’s working fine. 

 

Including the whole script would be tough – pretty large, too many modules and some proprietary things that’s not easy to cleanse. 

 

I believe, the relevant part is what I already included - the security group for an instance that includes a load balancer’s security group to restrict that instance to only be accessible from that load balancer. 

 

On PLAN, it shows differences and on APPLY it complains about the LB’s security group giving the invalid group id error.

 

Tom

Please note my email address has changed.
Tom Stachura
1-604-525-7096 <tel:1-604-525-7096>  / tom@stachura.me <mailto:tom@stachura.me> 
 <https://www.facebook.com/tstachura>   <https://twitter.com/tomstachura>   <https://www.linkedin.com/in/tomstachura>

**Comment by grubernaut** [comment]
@tomstachura, thanks for the reply!

Apologies, I misread the initial code provided due to the Markdown formatting of the code block. I'll be looking into this today and keep you posted.

**Comment by grubernaut** [comment]
Hi @tomstachura, thanks for your patience with this. 
I'm only able to reproduce this issue when I write an `aws_security_group` resource that contains `egress` and `ingress` rules, and then I attempt to add an `aws_security_group_rule` that references the original `aws_security_group`. 

Full example config: 
```
provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "vp" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_security_group" "one" {
  vpc_id = "${aws_vpc.vp.id}"

  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "test" {
  vpc_id      = "${aws_vpc.vp.id}"

  ingress {
    from_port       = 8080
    to_port         = 8080
    protocol        = "tcp"
    security_groups = ["${aws_security_group.one.id}"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group_rule" "add" {
  type = "ingress"
  from_port = 0
  to_port = 0
  protocol = "-1"
  cidr_blocks = ["0.0.0.0/0"]
  security_group_id = "${aws_security_group.test.id}"
}
```
As soon as I add the `aws_security_group_rule.add` resource, I see a similar diff to what you're experiencing. Also, when I run a `terraform apply` on that plan, it removes the original ingress rule from the one specified in the security group resource. 

Does this match with your configuration? If not I'll keep digging, thanks!

**Comment by grubernaut** [comment]
Ah so @tomstachura, the issue doesn't occur when including another security group inside of a rule. The issue arises when using the separate `aws_security_group_rule` with a security group that already has inline ingress/egress rules (See the last resource block in the example posted above). 

However, that issue has been around since before v0.8.1 between the `aws_security_group_rule` and `aws_security_group` resources, so the issue more than likely stems from a Core change, not a change to the resource itself. If possible, it would be a huge help if you could check your code for any `aws_security_group_rule` resources that reference the `aws_security_group` that we're seeing the issue with.
Thanks!

**Comment by grubernaut** [comment]
Hey @tomstachura, were you able to check if you were using both `ingress{}/egress{}` inline blocks to an `aws_security_group`, as well as an `aws_security_group_rule` that references the same `aws_security_group`? Thanks!
