### ISSUE TITLE
Ambiguous names for port range parameters in aws_security_group[_rule] resources

### ISSUE THREAD

**Issue by madamedwards** [hashicorp/terraform#11067]
In the `aws_security_group` (`ingress` and `egress` blocks) and `aws_security_group_rule` resources, the parameters for indicating a port range (`from_port` and `to_port`) have ambiguous/misleading names.

Since a security group is a firewall, the thing that comes to mind when I see `from_port` is the same as "source_port", whereas `to_port` strikes me as "destination_port". In reality, these _both_ refer to the destination port _range_.

When creating our Terraform infrastructure, I made the initial mistake of setting the `from_port` to 0, thinking that I was allowing traffic from any source port. But what I actually did was mistakingly open every port between 0 and 443, and then had to go back and clean this up once discovered.

Thinking it was just me, I spoke with a co-worker about it and found that he'd made the same mistake. This leads me to believe that there are others out there making this mistake. It does clearly state in the docs that `from_port` is "The start port," but this is easy to overlook, especially if you read the example code and don't read through the actual text.

For example, the example code in the `aws_security_group_rule` documentation page shows:
```
...
    from_port = 0
    to_port = 65535
...
```

My suggestion would be to make these parameter names clearer. I think a better way to represent them would be:
`port_range_start` and
`port_range_end`.
However, anything unambiguous would be fine.

**Comment by mitchellh** [comment]
I'd agree this would probably be better. However, this would be a very serious backwards incompatibility issue at this point for a config key that has been around for likely coming up on 2.5 years (and therefore, in the wild a lot).

We have mechanisms in place to automatically fix up state field names but we can't currently automatically fix-up configurations. Given that, I don't think its worth it currently. But like I said, I agree your proposed naming is better.
