### ISSUE TITLE
Feature request: Add 'most_recent' to aws_ebs_snapshot data source

### ISSUE THREAD

**Issue by sean-bennett112** [hashicorp/terraform#11072]
I was wondering if we could add `most_recent` to the parameters supported by the `aws_ebs_snapshot`, data source, since that would greatly increase the utility of that data source. I noticed that `aws_db_snapshot` does already seem to support `most_recent`.

**Comment by JakimLi** [comment]
I think [pull request 10986](https://github.com/hashicorp/terraform/pull/10986) already covered this, it's been merged, I guess it will be available in v0.8.3

**Comment by stack72** [comment]
Hi @sean-bennett112 

@JakimLi is indeed correct - this will be part of the 0.8.3 release :)

Thanks

Paul

**Comment by sean-bennett112** [comment]
Oh, fantastic! I was just looking at the code in the PR that introduced the data source, so I totally missed that. Thanks!
