### ISSUE TITLE
`dyn_record` fails with records for the top level domain

### ISSUE THREAD

**Issue by jbarreneche** [hashicorp/terraform#11078]
### Terraform Version
```
$ terraform -v
Terraform v0.8.2
```

### Affected Resource(s)
- dyn_record

### Terraform Configuration Files
```hcl
resource "dyn_record" "root_restorando_net" {
  zone = "restorando.net"
  name = ""
  ttl  = 90

  type  = "A"
  value = "127.0.0.1"
}
```

### Debug Output
https://gist.github.com/jbarreneche/78f6752aff380186fd0897c28a7d96f1

### Expected Behavior

An "A" record created at the top level domain

### Actual Behavior

Fail with 400 bad request. Probably the request in this case is malformed.

### Steps to Reproduce

1. `terraform apply` (with the dyn credentials and the above terraform file)

### Important Factoids

This also happens when trying to modify an existing record at that given level (this record were imported manually, and we wanted to change the TTL).

**Comment by maxvt** [comment]
https://github.com/hashicorp/terraform/pull/14076 will provide more detailed logs from the Dyn client.
