### ISSUE TITLE
aws_s3_bucket_object  Failed getting S3 object: BadRequest: 

### ISSUE THREAD

**Issue by davyt10** [hashicorp/terraform#11084]
$ terraform -v
Terraform v0.7.11

Anyone any ides why this has just started happening in only one of my environments. Exactly the same code to create a datasource to pull down my userdata script from S3. 

It works without issue in all of my other environments and did in this one also and has recently stopped with below error. All of the obvious things like incorrect bucket etc are not the issue, this exact code is working in other environments.

Pretty stumped on how to get around it.

data "aws_s3_bucket_object" "server_install_script" {
  bucket = "automation"
  key = "UserData-Win/Server-Install.ps1"
}

2017/01/06 16:58:11 [ERROR] Shadow graph error: 1 error(s) occurred:

* data.aws_s3_bucket_object.server_install_script: Failed getting S3 object: BadRequest: Bad Request
        status code: 400, request id: 754FE1341739B66C
Error refreshing state: 1 error(s) occurred:

* data.aws_s3_bucket_object.server_install_script: Failed getting S3 object: BadRequest: Bad Request
        status code: 400, request id: 754FE1341739B66C

**Comment by jszwedko** [comment]
@davyt10 I'm seeing the same issue -- was there something specific you did to solve it?
