### ISSUE TITLE
aws/route53 - Add support for reusable delegation sets

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1108]
This feature allows reusing the NS set between hosted zones:
http://docs.aws.amazon.com/Route53/latest/APIReference/api-create-reusable-delegation-set.html

It would most likely require a new resource, e.g.
```ruby
resource "aws_route53_delegation_set" "default" {
  caller_reference = "..."
  hosted_zone_id = "..."
}
```

and a new parameter for `aws_route53_zone`:

```ruby
resource "aws_route53_zone" "primary" {
  name = "example.com"
  delegation_set_id = "${aws_route53_delegation_set.default.id}"
}
```

**Comment by phinze** [comment]
Hey there - we're consolidating Requests for AWS API Coverage over in the spreadsheet linked at #28 - head over there to record your username on what you'd like us to prioritize next!
