### ISSUE TITLE
azurerm_template_deployment fails to pass "array" type parameters properly

### ISSUE THREAD

**Issue by rtyler** [hashicorp/terraform#11085]
### Terraform Version

v0.8.0

### Affected Resource(s)

- azurerm_template_deployment

### Terraform Configuration Files

Consider the an ARM template with an "array" parameter, e.g.:

```json
{
    "$schema": "http://schemas.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "documentDBs": {
            "type": "array"
        }
    },
```

```hcl
resource "azurerm_template_deployment" "thing" {
    name                = "a-big-parameterized-arm-template"
    resource_group_name = "${azurerm_resource_group.things.name}"
    parameters          = {
        documentDBs = [
            "github-events",
        ],
    }
    deployment_mode     = "Incremental"
    template_body       = "${file("./arm_templates/the-template.json")}"
}

```

### Output

```
Error running plan: 1 error(s) occurred:

* parameters: 1 error(s) decoding:

* '[documentDBs]' expected type 'string', got unconvertible type '[]interface {}'

```

### Expected Behavior

I would have expected the array to be marshalled through to the template properly.
What should have happened?

**Comment by pearcec** [comment]
Any possible workarounds?  I am working on automating the Protection of a VM.  Perhaps taking a string value from terraform and creating an array with it inside json?

**Comment by phekmat** [comment]
> Perhaps taking a string value from terraform and creating an array with it inside json?

I'm using `vars` with `template_file`s in a few places to generate the ARM template with the array/object values baked in. Unfortunately, this doesn't work for more complex scenarios like referencing a Key Vault secret, since that has to be in the parameters file instead of the main template.

**Comment by jkalwar** [comment]
I have a similar issue , unable to pass arrays as parameters in azurerm_template_deployment , do we have a solution for this issue ?

**Comment by aykay76** [comment]
We also have a requirement for this.
