### ISSUE TITLE
Where is the cycle?

### ISSUE THREAD

**Issue by JakimLi** [hashicorp/terraform#11090]
Hi there,

I have a set of terraform scripts to setup my qa environment as given in below GitHub repo, I can do the initial apply, and get all the resources created as expected, I can do `terraform plan` and `terraform destroy` without any issue, but when I try to change the value of the variable snapshot, I am expecting the value change will cause my_lc recreated, and also the my_asg, so that the asg can be replaced by the new one created, I included `lifecycle { create_before_destroy = true }` on all the places I can think of, but when I try to do `terraform apply` after I change the value, it gives Cycle error. I couldn't find where the cycle is.

Also googled a lot and tried to add `lifecycle { create_before_destroy = true }` in the template_file data source, but it gives an error says the key "lifecycle" is invalid there.

### Terraform Version
0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_autoscaling_group

### Terraform Configuration Files
https://github.com/JakimLi/terraform-error

### Graph
![a](https://cloud.githubusercontent.com/assets/4111971/21747770/d763b2e2-d5ad-11e6-8f24-133154517035.png)

### Debug Output
```
* Cycle: module.my_asg.aws_autoscaling_policy.scale_up (destroy), module.my_asg.aws_autoscaling_policy.scale_up, module.my_asg.aws_cloudwatch_metric_alarm.scale_up_alarm, module.asg.aws_cloudwatch_metric_alarm.scale_up_alarm(destroy), module.my_asg.aws_autoscaling_group.my_asg (destroy),module.my_asg.aws_cloudwatch_metric_alarm.scale_down_alarm (destroy), module.my_lc.output.my_lc_id, module.my_asg.var.my_lc_id, module.my_asg.aws_autoscaling_group.my_asg, module.my_asg.aws_autoscaling_policy.scale_down, module.my_asg.aws_cloudwatch_metric_alarm.scale_down_alarm, module.my_asg.aws_autoscaling_policy.scale_down (destroy), module.my_lc.aws_launch_configuration.my_lc (destroy)

```

### Expected Behavior
Should apply the new changes

### Actual Behavior
Cycle error

**Comment by mitchellh** [comment]
If you run `terraform graph -draw-cycles` it will highlight the cycle in red. You may have to run it with a plan file if there is no cycle during the plan phase and only during the apply phase (the `graph` command by default will output the plan-phase graph).

**Comment by JakimLi** [comment]
Thanks @mitchellh for the reply, I did what you suggested, it did give me some red lines, but it still hard to identify the cycle. but I did make it work by integrating my autoscaling group and launch configuration into the same module, but it's not working when split them into two modules, just want to understand why, thanks.
