### ISSUE TITLE
Datadog: When API call fails, it prints the datadog credentials, which might cause a credentials leak

### ISSUE THREAD

**Issue by keymon** [hashicorp/terraform#11107]
Using Datadog provider, if a API call fails, it prints the query to the API which includes the API keys, leaking the credentials.

Comes from https://github.com/hashicorp/terraform/issues/11106

### Terraform Version

0.7.1

### Affected Resource(s)

- datadog

### Terraform Configuration Files

See https://github.com/hashicorp/terraform/issues/11106

### Debug Output

See https://github.com/hashicorp/terraform/issues/11106

### Expected Behavior

Credentials should not be print. At least redacted.

### Actual Behavior

Prints the credentials See https://github.com/hashicorp/terraform/issues/11106

### Steps to Reproduce
See https://github.com/hashicorp/terraform/issues/11106

**Comment by grubernaut** [comment]
Noting to update the vendored dependency after the credential leak is fixed.

**Comment by stack72** [comment]
Closed via #12086

**Comment by ojongerius** [comment]
Not sure if this is resolved, it may happen less often but Datadog still only supports passing credentials via query params and credentials may still surface to end users. We have https://github.com/zorkian/go-datadog-api/issues/76 open for it, but no-one has volunteered to do the work of masking / hiding the credentials.
