### ISSUE TITLE
provider/aws: Add the ability to set the API Gateway Key value

### ISSUE THREAD

**Issue by Ninir** [hashicorp/terraform#11105]
Hi everyone,

#### Description
This PR is made post-PR to keep track of the request.

When using the `aws_api_gateway_api_key` resource, the value for the key is computed and generated by AWS. 
However from a SDK point-of-view it is possible to set it, thus allowing user-defined tokens, and bringing even more flexibility to resources and use-cases.

#### Use-cases
As such, the main use-case (for me at the moment) is for demo/training purposes. 
Let's say you have 5 users, you want to have domain `api1` with key `user1token`, you want to have domain `api2` with key `user2token`, etc.

### Terraform Version
Checked against: Terraform v0.7.8-dev (bdb6089+CHANGES) & newest ones

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_api_gateway_api_key

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
N/A

### Actual Behavior
N/A

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
Related PR: https://github.com/hashicorp/terraform/pull/9462

**Comment by sebolabs** [comment]
+1, really need this!
