### ISSUE TITLE
Diffs not matching on aws_route53_record with imported aws_route53_zone

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#11118]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- provider.aws
- aws_route53_zone * 2
- aws_route53_record * 4

### Terraform Configuration Files
```hcl
variable "region" {
  default = "ca-central-1"
}

variable "aws_profile" {}
variable "domain" {}
variable "primary_ip" {}

provider "aws" {
    region = "${var.region}"
    profile = "${var.aws_profile}"
}

resource "aws_route53_zone" "prod" {
  name = "${var.domain}"
}

resource "aws_route53_record" "main-www" {
  zone_id = "${aws_route53_zone.prod.zone_id}"
  name = "www"
  type = "CNAME"
  ttl = "5"
  records = ["${var.domain}"]
}

resource "aws_route53_record" "main-at" {
  zone_id = "${aws_route53_zone.prod.zone_id}"
  name = "@"
  type = "A"
  ttl = "1"
  records = ["${var.primary_ip}"]
}

resource "aws_route53_record" "main-star" {
  zone_id = "${aws_route53_zone.prod.zone_id}"
  name = "*"
  type = "A"
  ttl = "1"
  records = ["*.${var.domain}"]
}

resource "aws_route53_zone" "staging" {
  name = "staging.${var.domain}"

  tags {
    Environment = "staging"
  }
}

resource "aws_route53_record" "staging-ns" {
    zone_id = "${aws_route53_zone.prod.zone_id}"
    name = "staging.${var.domain}"
    type = "NS"
    ttl = "30"
    records = [
        "${aws_route53_zone.staging.name_servers.0}",
        "${aws_route53_zone.staging.name_servers.1}",
        "${aws_route53_zone.staging.name_servers.2}",
        "${aws_route53_zone.staging.name_servers.3}"
    ]
}

output "nameservers" {
  value = "${aws_route53_zone.prod.name_servers}"
}
```

### Debug Output
https://gist.github.com/nathanielks/30adee170662f36bb812f767a9fd23e3

### Expected Behavior
`aws_route53_record.staging-ns` should have been created without errors.

### Actual Behavior
The record was not created and an error was thrown.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

I had imported an existing Route53 zone `staging.textopress.com` as it was created by a separate terraform configuration.

**Comment by nathanielks** [comment]
A subsequent plan and apply made it work though!

**Comment by mitchellh** [comment]
I can't reproduce this. I have a feeling this had to do with that partial failure. Its definitely a bug but without a reproduction we're not going to be able to solidly fix this. If you see it again please let us know. Thanks!
