### ISSUE TITLE
Import ACM data resource by tag

### ISSUE THREAD

**Issue by hamstah** [hashicorp/terraform#11117]
Hi,

I'd like to be able to select domains with `aws_acm_certificate` by tag values as well as domain.
My use case is multiple wildcard certs for a domain in different AWS region (original cert in eu-west-1 but I need a new one for cloudfront in us-east-1).

Are there plans to support this or issues with the idea?

Thanks

**Comment by stack72** [comment]
Hi @hamstah 

Thanks for getting in touch here - I have been looking at the API for this today and it seems that this is not available to do via AWS. The API looks as follows:

```
// Please also see https://docs.aws.amazon.com/goto/WebAPI/acm-2015-12-08/ListCertificatesRequest
type ListCertificatesInput struct {
	_ struct{} `type:"structure"`

	// The status or statuses on which to filter the list of ACM Certificates.
	CertificateStatuses []*string `type:"list"`

	// Use this parameter when paginating results to specify the maximum number
	// of items to return in the response. If additional items exist beyond the
	// number you specify, the NextToken element is sent in the response. Use this
	// NextToken value in a subsequent request to retrieve additional items.
	MaxItems *int64 `min:"1" type:"integer"`

	// Use this parameter only when paginating results and only in a subsequent
	// request after you receive a response with truncated results. Set it to the
	// value of NextToken from the response you just received.
	NextToken *string `min:"1" type:"string"`
}
```

As you can see, it only takes a list of statuses not tags. Therefore, this isn't something that Terraform can support right now. This would have to be added on the AWS side of things

I think if you raise it with them, we can reopen / revisit this if they add it

Thanks

Paul

**Comment by hamstah** [comment]
Hi Paul,

Thanks for that. I had a look at the API, it doesn't offer a filtering server side, but we could use the ListCertificates api and have client side filtering to pick one of them.

It seems like it would work, but is it a good approach from the terraform point of view (ie should we stick to thin wrapping of the API or is it ok to do more logic too?).

Thanks
