### ISSUE TITLE
Make resource_newrelic_alert_condition enabled status configurable

### ISSUE THREAD

**Issue by garthkerr** [hashicorp/terraform#11123]
### Terraform Version
**v0.8.2**

### Affected Resource(s)
- resource_newrelic_alert_condition

The newrelic resource module by @paultyng is outstanding thus far. However, is would be useful to make the `enabled` status a configurable argument:

https://github.com/hashicorp/terraform/blob/3dfe5a47f1a2cb0df32f086b740bad89c028a9a2/builtin/providers/newrelic/resource_newrelic_alert_condition.go#L184

**Comment by paultyng** [comment]
I may not be remembering it correctly, its worth a test, but there were some things I found where the API didn't respect changes to the fields, this may be one of them.  Their API is pretty bad, missing endpoints, not an up to date swagger spec, etc.  I tried to smooth over as many of the edges as I could.

**Comment by paultyng** [comment]
Actually, it may have been a bug in my SDK library now that I look at it.

https://github.com/paultyng/go-newrelic/blob/37814ca9c24a7e5f9455c7e71a79b6732bab1912/api/types.go#L55

Since this is `omitempty` and `false` is the empty value for boolean.  So would need to change that probably.

**Comment by paultyng** [comment]
I wrote an issue up for that https://github.com/paultyng/go-newrelic/issues/2

**Comment by garthkerr** [comment]
Thank you for the details on this @paultyng
