### ISSUE TITLE
Passing a list to a count parameter produces a panic

### ISSUE THREAD

**Issue by rsalmond** [hashicorp/terraform#11124]
### Terraform Version
Terraform v0.8.2

### Affected Resource(s)
Seems to affect any resource.

### Terraform Configuration Files
```hcl
variable "paramater_two" {
  type = "list"
  default = ["thing1", "thing2"]
}

resource "null_resource" "foo_module" {
  count = "${var.paramater_two}"
}
```

### Debug/Panic Output
[Log level debug + Panic](https://gist.github.com/rsalmond/ec05c07740ed2c87b344ebc1b7a6634f).

### Expected Behavior
Throw an error for incorrect variable type.

### Actual Behavior
Crash.

### Steps to Reproduce
`terraform plan`

**Comment by jbardin** [comment]
closed via #11864
