### ISSUE TITLE
missing Windows download of 0.8.3 (https://www.terraform.io/downloads.html)

### ISSUE THREAD

**Issue by veqryn** [hashicorp/terraform#11138]
For whatever reason, there is no Windows download/version of 0.8.3
https://www.terraform.io/downloads.html
https://releases.hashicorp.com/terraform/0.8.3/

**Comment by richarddowner** [comment]
+1 need the windows version

**Comment by chrisrlong** [comment]
I was just going to raise this.... +1

**Comment by stack72** [comment]
Hi Friends

We solved this by releasing Terraform 0.8.4 

https://www.terraform.io/downloads.html

Thanks and sorry for the issue

Paul
