### ISSUE TITLE
azurerm_lb_rule is not created the right way

### ISSUE THREAD

**Issue by dobrerazvan** [hashicorp/terraform#11130]
Hi there,

### Terraform Version
dobre-osx:~ dobre$ terraform -v
Terraform v0.8.3

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_lb_rule

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
variable "customer" {
  type = "string"
  default = "razvan"
}

variable "environment" {
  type = "string"
  default = "prod"
}

variable "region" {
  type = "string"
  default = "North Europe"
}

###############################################################################
# Customer X
resource "azurerm_resource_group" "customerx" {
    name = "customerx-${var.environment}"
    location = "${var.region}"
}

resource "azurerm_public_ip" "customerx_ip" {
    name = "customerx-ip-${var.environment}"
    location = "${var.region}"
    resource_group_name = "${azurerm_resource_group.customerx.name}"
    public_ip_address_allocation = "dynamic"
}

resource "azurerm_lb" "customerx_lb" {
    name = "customerx-lb-${var.environment}"
    location = "${var.region}"
    resource_group_name = "${azurerm_resource_group.customerx.name}"

    frontend_ip_configuration {
      name = "customerx-fep-ip-${var.environment}"
      public_ip_address_id = "${azurerm_public_ip.customerx_ip.id}"
    }
}

resource "azurerm_lb_rule" "port_80" {
  name = "customerx-port-80-${var.environment}"
  location = "${var.region}"
  resource_group_name = "${azurerm_resource_group.customerx.name}"

  loadbalancer_id = "${azurerm_lb.customerx_lb.id}"
  protocol = "tcp"
  frontend_port = 80
  backend_port = 81
  frontend_ip_configuration_name = "customerx-fep-ip-${var.environment}"
  probe_id = "${azurerm_lb_probe.customerx_lb_probe.id}"
}

resource "azurerm_lb_backend_address_pool" "customerx_lb_back_addr_pool" {
  name = "customerx-lb-back-${var.environment}"
  location = "${var.region}"
  resource_group_name = "${azurerm_resource_group.customerx.name}"

  loadbalancer_id = "${azurerm_lb.customerx_lb.id}"
}

resource "azurerm_lb_probe" "customerx_lb_probe" {
  name = "customerx-port-22-probe-${var.environment}"
  location = "${var.region}"
  resource_group_name = "${azurerm_resource_group.customerx.name}"

  loadbalancer_id = "${azurerm_lb.customerx_lb.id}"
  port = 22
}
```

### Debug Output
I took the json from resources.azure.com in the following situations:
1. after the resource was created with terraform - https://gist.github.com/dobrerazvan/731a1f07ea9621d93849b27fa272b979
2. after the resource was created by hand with exactly the same content - https://gist.github.com/dobrerazvan/ff07c3d43daf953a67b8497336331687

The way terraform creates that resource prevents LB from working as expected, forwarding traffic in the backend. The manual setup from the portal with the exact settings is working.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-11028 (#11028)

Thanks

**Comment by pmcatominey** [comment]
Hi @dobrerazvan 

I can't seem to see the linked JSON values from the resource explorer, is that gist hosted on an internal system?

**Comment by dobrerazvan** [comment]
@pmcatominey I updated the links. Thanks.

**Comment by dobrerazvan** [comment]
Can, please, someone look into this? Thanks

**Comment by GreatSnoopy** [comment]
I am also interested in having this solved

**Comment by iondulgheru** [comment]
I also had issues while creating the Azure load balancer with Terraform, and I suspect the issue is what @dobrerazvan described.

**Comment by pmcatominey** [comment]
@dobrerazvan your example code is missing the `backend_address_pool_id` field in the `azurerm_lb_rule` resource, could you set this and try again?

**Comment by dobrerazvan** [comment]
@pmcatominey yep that did the trick. Was a little bit confusing since the fields in the UI are no mandatory but can't continue without them and so the backend_address_pool_id and the lb_rule level is set optional.

**Comment by sampcoug** [comment]
I am trying to add multiple protocols on my lb_rule for the load balancer but I am getting error that multiple resource "azurerm_lb_rule" is not allowed. This is how the rule looks like: 
`resource "azurerm_lb_rule" "lb_rule" {
  resource_group_name            = "${azurerm_resource_group.rg.name}"
  loadbalancer_id                = "${azurerm_lb.lb.id}"
  name                           = "LBRule"
  protocol                       = "tcp"
  frontend_port                  = 22
  backend_port                   = 22
  frontend_ip_configuration_name = "LoadBalancerFrontEnd"
  enable_floating_ip             = false
  backend_address_pool_id        = "${azurerm_lb_backend_address_pool.backend_pool.id}"
  idle_timeout_in_minutes        = 5
  probe_id                       = "${azurerm_lb_probe.lb_probe.id}"
  depends_on                     = ["azurerm_lb_probe.lb_probe"]
}`

1. How do I add a second rule for ports: 9005, 80 & 443?
2. How do I add IPv6 support on the Load balancer?
