### ISSUE TITLE
Please consider implementing an aws_kms_key_policy_attachment

### ISSUE THREAD

**Issue by kojiromike** [hashicorp/terraform#11137]
### Terraform Version
0.8.3

### Affected Resource(s)
- aws_kms_key
- aws_policy

### Terraform Configuration Files

Perhaps something like

```hcl
resource "aws_kms_key" "example-key" {
    description = "example"
    delete_window_in_days = 7
}
…
data "aws_iam_policy_document" "kms" {
  statement {
    sid     = "Enable IAM User Permissions"
    effect  = "Allow"
    actions = ["kms:*"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::somebody:root"]
    }

    resources = ["*"]
  }
}
…
resource "aws_kms_key_policy_attachment" "kms-attach" {
    name = "kms-attachment"
    key_id = "${aws_kms_key.example-key.id}"
    policy_document = "${aws_iam_policy.kms.json}"
}
```

### Important Factoids

The AWS API supports modifying the policy for a key after it's created. Sometimes it's important to do this to get ordering right in Terraform, particularly if the key itself is unmanaged or in a migration.

**Comment by dougneal** [comment]
I may pick this up, as have also found a need for a `aws_kms_key_policy_attachment` resource.

**Comment by chrisfu** [comment]
This is a tad more important now considering the upcoming changes enforcing service role utilisation on March 26th; especially where external CMK's are in use. Attaching a policy to a key that exists outside of Terraform's state will become less of an edge case.
