### ISSUE TITLE
[BUG] Terraform template file not rendering "@" sign

### ISSUE THREAD

**Issue by arehmandev** [hashicorp/terraform#11144]
Error: Template fails to render

* data.template_file.consul: failed to render : parse error at 79:23: expected expression but found invalid sequence "@"

Affected lines:
```
OTHER_IPS=( ${ALL_IPS[@]/{$IP}/} )
echo "Instance IP is: $IP, Cluster IPs are: ${ALL_IPS[@]}, Other IPs are: ${OTHER_IPS[@]}"
```
Terraform Version:
0.8.3

Link to userdata template:

https://github.com/arehmandev/Consul-bashstrap/blob/master/consul-node.sh

Workaround:
Could not seem to escape the @ character with my efforts, so I ended up executing it as such:

https://github.com/arehmandev/terraform-consul-cluster/blob/master/modules/consul/files/consul-node.sh

**Comment by apparentlymart** [comment]
Hi @arehmandev. Sorry for the weirdness here. 

The issue here appears to be the `${` sequences rather than the at signs... That is causing Terraform to treat these sequences as interpolation expressions, which then fails because the at sign is not valid interpolation syntax.

You can avoid this by replacing the `${` sequences with `$${`. Terraform treats this as an escape sequence and then removes the extra dollar sign to get the literal sequences I think you wanted here.

**Comment by arehmandev** [comment]
Hmm I have tried that before but I will give it another go, cheers

**Comment by metral** [comment]
I hit this error myself when trying to iterate on an array in bash embedded in a template_file for rendering. Escaping did not help as changing from `for i in "${IP_ADDRS[@]}"` to `for i in "$${IP_ADDRS[@]}"` still gives me the error: `failed to render : parse error at 15:22: expected expression but found invalid sequence "@"`

@apparentlymart was there anything else you did to work around this?

**Comment by apparentlymart** [comment]
@metral it's tough to guess what's going on there. Also tricky to track ongoing Q&A on github, so I suggest instead looking to one of the forums listed on [the Community page](https://www.terraform.io/community.html); in this case one if the Stack Exchange sites would probably be best so it's easy to share a more representative snippet of your configuration.

**Comment by syquus** [comment]
Just to enforce the idea that this is still a bug:

```
Terraform v0.12.18
+ provider.aws v2.43.0
+ provider.template v2.1.2

```
