### ISSUE TITLE
Add CHANGELOG.md entries to GitHub Releases

### ISSUE THREAD

**Issue by erydo** [hashicorp/terraform#11148]
The descriptions in [CHANGELOG.md](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#083-january-10-2017) are extremely helpful. So are the [GitHub releases](https://github.com/hashicorp/terraform/releases). We use GitHub's atom feed of the Releases page to notify us of new Terraform releases.

It would be helpful if a version's changelog entries could be included in the release notes.
As an example, here is a [Docker release](https://github.com/docker/docker/releases/tag/v1.13.0-rc5) with changelog notes.

This would avoid the current need of seeing an un-annotated release, browsing to the source, opening CHANGELOG.md and finding the referenced version. It's a small friction but a frequent one.

(Tagging @mitchellh @stack72 @catsby who have done the most recent releases).

**Comment by mitchellh** [comment]
This is not a bad idea and I'm not against it. For now we actually handle all that manually so I'd prefer we don't add steps to our manual process. However, I'm looking to automate more of the release process and as part of that I think this would be a pretty good idea. I'm going to close so we don't clutter the already pretty noisy issue list but this is something I'm on board with. :)
