### ISSUE TITLE
Azure web app deployment

### ISSUE THREAD

**Issue by dpnl87** [hashicorp/terraform#11154]
Hi there,

For a new project I need to depoy Azure web apps (https://azure.microsoft.com/en-us/services/app-service/web/?b=16.52).

It looks like the azurerm provisioner has no resources to do this. Would it be hard to add this functionality?

**Comment by jvdenning** [comment]
While the purist may reject this at is not strictly "infrastructure" the app service plan, app service environment and the various flavours of app service in azure represent platform-as-a-service that would be ideally supported by terraform as it feels like a seamless fit to be able to configure more of the services that make up a cloud environment. Can anyone indicate if this might be looked at?

**Comment by lstolyarov** [comment]
I have created some code that allow you to deploy Azure Web apps with terraform. The pull request is here https://github.com/hashicorp/terraform/pull/12001.
