### ISSUE TITLE
Can't compile older releases, due to DigitalOcean provider type change

### ISSUE THREAD

**Issue by james-masson** [hashicorp/terraform#1115]
I'm trying to get support for both AWS source_dest_check and AWS VPC peering. Basically a 0.3.7 release + source_dest_check fix.

I've tried checking out - https://github.com/hashicorp/terraform/commit/473b03ccae3857344f33ae1f1a6adc013d62f40d

but this no longer compiles.

```
go generate ./...
==> Getting dependencies...
# github.com/hashicorp/terraform/builtin/providers/digitalocean
builtin/providers/digitalocean/resource_digitalocean_droplet.go:115: cannot use attr.(string) (type string) as type bool in assignment
builtin/providers/digitalocean/resource_digitalocean_droplet.go:119: cannot use "true" (type string) as type bool in assignment
builtin/providers/digitalocean/resource_digitalocean_droplet.go:123: cannot use "true" (type string) as type bool in assignment
Makefile:13: recipe for target 'dev' failed
make: *** [dev] Error 2
```

Any ideas for getting a working non-master build?

**Comment by james-masson** [comment]
I've reverted github.com/pearkes/digitalocean to d1e3ab4 - and that seems to compile.

Is there a way to see what dependency versions a particular release of terraform was compiled against?

**Comment by mitchellh** [comment]
We don't have reproducible builds yet. Go just said they're hoping to bring this into Go 1.5, so hopefully we'll have them soon.
