### ISSUE TITLE
curl-able script for one-command installation

### ISSUE THREAD

**Issue by h2non** [hashicorp/terraform#1116]
Taking into account terraform is distributed as a set of binaries, a simple bash script would help a lot to invite and simplify the installation

What you think? I can create a multi version install script for POSIX platforms

**Comment by mitchellh** [comment]
I think we should submit Terraform to things like brew and so on, but I don't think this is especially useful. The install is incredibly simple: `curl && unzip`. The "bash script" would be a few lines at most. We also cover the install in the getting started guide (which is a few paragraphs about how to install). 

I really think the UX here is easy enough, and I don't want to risk the stigma associated with having a `curl | sh` for security reasons.

**Comment by h2non** [comment]
Definitely Brew and other package managers will be better

**Comment by radeksimko** [comment]
[It's already in Homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/terraform.rb).
