### ISSUE TITLE
Support Datadog Timeboard Resource Aggregator Field

### ISSUE THREAD

**Issue by NabilZaman** [hashicorp/terraform#11168]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Running Terraform v0.8.2

### Affected Resource(s)
- datadog_timeboard

### Terraform Configuration Files
```
resource "datadog_timeboard" "sample_timeboard" {
  title = "TEST"
  description = "Testing"
  graph {
    title = "Test Graph"
    viz = "query_value"
    request {
      q = "sum:blah_blah{*}"
      type = "line"
    }
  }
}
```
### Debug Output
N/A

### Panic Output
No panic

### Expected Behavior
What should have happened?
Should be able to specify the data aggregator function for a datadog timeboard graph

### Actual Behavior
What actually happened?
Aggregator is not a valid specifiable key. Instead the default aggregator of "avg" is chosen.

### Steps to Reproduce
Not a bug, but generate any datadog_timeboard resource with a nested graph block. The chosen aggregator in the generated graph will always be "avg" from what I can tell.

### Important Factoids
Interestingly in the JSON tab of the generated graph, there are two aggregator fields, which seems abnormal, but has no negative impact:
```
{
  "viz": "query_value",
  "Style": {},
  "yaxis": {},
  "requests": [
    {
      "q": "sum:blah_blah{*}",
      "Aggregator": "",
      "stacked": false,
      "type": "line",
      "conditional_formats": [],
      "aggregator": "avg"
    }
  ],
  "autoscale": true
}
```

This is possibly a bug but only cosmetically related to my request.

**Comment by NabilZaman** [comment]
Thanks!

**Comment by NabilZaman** [comment]
Actually... @grubernaut, it looks like this #11206 change supports the aggregation methods: average, max, min, sum.
My use case is actually for setting up some query_value graphs with the "last" aggregator.
Could this also be supported?

**Comment by grubernaut** [comment]
Hi @NabilZaman, according to the API docs, they only show the available aggregation methods as being: average, max, min, or sum. (http://docs.datadoghq.com/graphingjson/#aggregation)
It looks like `last` is a parameter to the `top()` function defined here: (http://docs.datadoghq.com/graphingjson/#functions). And it looks like functions are defined in the `q` attribute of the graph definition block. 
Is this the `last` that you're looking for, or is there another place where this is documented? Thanks!

**Comment by NabilZaman** [comment]
Hmmm that's curious.
I don't actually see any API documentation that describes what I'm seeing.
I generate the datadog graph (Just a query value) using terraform and the avg aggregator is chosen - by default.
So I modify the graph using the aggregator dropdown and select `last`.
And this is the result of the JSON tab:
```
{
  "viz": "query_value",
  "Style": {},
  "autoscale": true,
  "requests": [
    {
      "stacked": false,
      "Aggregator": "",
      "conditional_formats": [],
      "q": "sum:blah_blah{*}",
      "aggregator": "last",
      "type": "line"
    }
  ],
  "yaxis": {}
}
```
Not really sure what to make of this but perhaps I should contact datadog to clarify their API?

**Comment by grubernaut** [comment]
@NabilZaman interesting.... Yeah I would contact datadog to clarify their API. I don't see a restriction in the datadog go-api to prevent specifying the `last` aggregator, so it should be possible if that's a valid aggregator method. I added verification on the aggregator attribute, so if it is a valid aggregator method, it should be an easy change.
