### ISSUE TITLE
Codecommit repository always created in us-east-1

### ISSUE THREAD

**Issue by yesteph** [hashicorp/terraform#11175]
Hi there,

### Terraform Version
0.8.4

### Affected Resource(s)
- aws_codecommit_repository

### Terraform Configuration Files
```
provider "aws" {
  region = "eu-west-1"
}
resource "aws_codecommit_repository" "backend_java" {
  repository_name = "backend-java"
  description = "Barcode generator backend"
}
```

### Expected Behavior
backend-java repository created in eu-west-1 region

### Actual Behavior
backend-java repository created in us-east-1 region (default)

### Steps to Reproduce
1. `terraform apply`

**Comment by stack72** [comment]
Hi @yesteph 

Thanks for finding this bug - I just opened a PR that will fix it :)

It will be part of the next Terraform release

Thanks

Paul

**Comment by yesteph** [comment]
Thank you Paul.
