### ISSUE TITLE
Self-references in `ec2_instance` tags for `private_ip`

### ISSUE THREAD

**Issue by colout** [hashicorp/terraform#11185]
Hi there,

I realize that the issue https://github.com/hashicorp/terraform/issues/3069 has been closed, but I have a use case to add that might legitimize the use of self-references in `ec2_instance` tags for example `private_ip`.

Specifically, I am using Terraform and SaltStack to provision and configure a zookeeper cluster.  My terraform code looks something like this (slightly simplified):

```tf
resource "aws_instance" "zookeeper" {
  count                  = "${var.zookeeper_count}"
  <snip>

  tags      { 
    Name = "zookeeper-${format("%03d", count.index + 1)}" 
    Roles = "zookeeper"
    zookeeper_ips = "${join(",", aws_instance.zookeeper.*.private_ip)}"
    zookeeper_id = "${count.index + 1}"
    Saltmaster = "${aws_instance.saltmaster.private_ip}"
  }
}
```

I am using ec2_tags (set by Terraform) as the source of truth for my instance configurations (using the [ec2_tags](https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_tags.py) grain in Salt if anyone is interested).  By design, each instance is only able to read its own tags (and as you can see, we use tags to tell each instance the Saltmaster ip)
 
The idea is that each instance gets a tag with the comma separated list of all other zookeeper nodes which we can use to produce the zookeeper config:
```config
server.1=1.1.1.1:2888:3888
server.2=1.1.1.2:2888:3888
server.3=1.1.1.3:2888:3888
```

I understand this is a complicated problem to solve, but I wanted to plead another use case for self-references in `ec2_instance` tags :)

Thanks,
Colin

**Comment by mitchellh** [comment]
In the current architecture of Terraform this is not only a complicated problem to solve but effectively impossible. :) We send all attributes to update/create a resource at once, so Terraform core currently has no understanding that it can create the AWS instance and _then_ create the tag.

One thing that will solve this is nested resources, which are potentially coming soon (and another core enhancement ticket somewhere covers it). That would make `tag` implicitly become another resource... which would make it possible. 

Your case is legitimate though and if nested resources enable it that'd be ideal.

Currently we don't have short term plans to rework the core enough to support this other than through nested resources.

**Comment by x89** [comment]
Just posting to check if it's doable via nested resources now and if so if a simple example could be provided?
