### ISSUE TITLE
tls handshake failure creating instance on Openstack Mitaka

### ISSUE THREAD

**Issue by llevar** [hashicorp/terraform#11182]
Trying to create an Openstack instance seems to fail on an Openstack Mitaka installation with latest Terraform giving a tls handshake failure error.

### Terraform Version
Terraform v0.8.4

### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl
provider "openstack" {
	user_name = "${var.user_name}"
	password = "${var.password}"
	tenant_name = "${var.tenant_name}"
	auth_url = "${var.auth_url}"
}


resource "openstack_compute_instance_v2" "salt_master" {
  	image_id = "${var.image_id}"
	flavor_name = "s1.capacious"
	security_groups = ["internal"]
	name = "salt-master"
	network = {
		uuid = "${var.main_network_id}"
	}
	connection {
		user = "${var.user}"
	 	key_file = "${var.key_file}"
	 	bastion_key_file = "${var.bastion_key_file}"
	 	bastion_host = "${var.bastion_host}"
	 	bastion_user = "${var.bastion_user}"
	 	agent = true
	 	
	}
	key_pair = "${var.key_pair}"
}
```

### Debug Output
https://gist.github.com/llevar/6d9982c337dceeab8c64997987e486c4

### Expected Behavior
Expecting the Openstack instance to be created

### Actual Behavior
Terraform fails with error

Error refreshing state: 1 error(s) occurred:

* Post https://console.cancercollaboratory.org:5000/v2.0/tokens: remote error: tls: handshake failure

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply

### Important Factoids
go version go1.7.4 darwin/amd64
Mac OS
Openstack Mitaka

I've been using a virtually identical setup successfully against other Openstack installations.
I can manually communicate with the Openstack API in question and perform operations normally.

**Comment by jtopjian** [comment]
@llevar Thanks for the report and sorry you're running into this.

Have you taken a look at the `insecure` and `cacert_file` options as described here: https://www.terraform.io/docs/providers/openstack/index.html ?

**Comment by llevar** [comment]
Hi @jtopjian , thanks for your response. Neither of those options had an effect. The cert is not self-signed btw.

**Comment by jtopjian** [comment]
Are you able to interact with that URL through the OpenStack command-line tool and/or curl directly without error?

**Comment by llevar** [comment]
Yep.

**Comment by jtopjian** [comment]
hm. I'm leaning on this being a more generic SSL issue rather than OpenStack-specific.

Are you able to see the logs on the other side? If the endpoint is an SSL terminator like HAProxy, maybe it's logging something about why the handshake is failing?

**Comment by gmihaiescu** [comment]
There is a "SSL handshake failure" in the haproxy logged, but other clients (e.g. Openstack CLI, browsers) have no issues connecting.

**Comment by jtopjian** [comment]
Thank you for checking!

Alright, so no details on that side... 

The debug gist you posted looks like it was run on a Mac. Are you connecting to this cloud by a VPN? If you were to run Terraform on a Linux vm (perhaps within the OpenStack cloud), do you get the same error?

The first question is because I remember some mac-specific network bugs in the past with Go. The second is to rule out something weird with Go/mac/certificates.

**Comment by gmihaiescu** [comment]
Unfortunately the same  happens when trying from a Ubuntu 14.04 VM inside the environment.

I'll try to bring up a Mitaka devstack and put haproxy in front of it with the same cert and test terraform.

**Comment by jtopjian** [comment]
@gmihaiescu That sounds good. Do let me know if you need any help or have any questions!

**Comment by gmihaiescu** [comment]
The ciphers accepted by my haproxy config were too restrictive for the Golang's client library.

After going with the following I believe terraform works fine:

ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128:AES256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK:!RC4

**Comment by jtopjian** [comment]
@gmihaiescu wow - thank you for digging into this!

Are you able to provide the ciphers that your haproxy server was previously using? If I have some time, I'd like to figure out how to configure this in the OpenStack provider at a user-facing level.

**Comment by jtopjian** [comment]
Hi guys, I'm going to close this issue, but I'm definitely interested in knowing the cipher list that was causing problems.
