### ISSUE TITLE
"terraform destroy" does not wait for ASG to be deleted

### ISSUE THREAD

**Issue by rhelmer** [hashicorp/terraform#1118]
If I ```terraform destroy``` infra that has an autoscaling group and then immediately ```terraform apply```, the latter frequently fails because the ASG takes some time to actually be deleted.

Is this intentional? I notice that terraform seems to wait for e.g. EC2 nodes to be completely shut down before ```terraform destroy``` returns.

**Comment by mitchellh** [comment]
Dup of #1109. Thanks!
