### ISSUE TITLE
AWS Provider Enhancement -- String Match Conditions

### ISSUE THREAD

**Issue by phuesler** [hashicorp/terraform#11195]
### Terraform Version
0.8.3

### Affected Resource(s)

- aws_waf_rule

AWS has released [String Match Conditions ](http://docs.aws.amazon.com/waf/latest/developerguide/web-acl-string-conditions.html). They are available in the console, however, I could not find them in their API documentation yet.

**Comment by neildothunter** [comment]
As I understand it string match conditions are catered for by the aws_waf_byte_match_set resource? byte_match_tuples looks to cover all options from here https://docs.aws.amazon.com/waf/latest/APIReference/API_ByteMatchTuple.html.

**Comment by phuesler** [comment]
👍  That was exactly what I was looking for. Thank you!
