### ISSUE TITLE
Feature Request: Add `session_affinity` property on `google_compute_region_backend_service`

### ISSUE THREAD

**Issue by zopanix** [hashicorp/terraform#11199]
Hey, this is a feature request. Details below

### Terraform Version
Terraform v0.8.4

### Affected Resource(s)
* google_compute_region_backend_service

### Terraform Configuration Files Example
```hcl
resource "google_compute_region_backend_service" "bes" {
  name             = "bes-prgall"
  description      = "This resource is managed by Terraform, do not edit manually!"
  protocol         = "TCP"
  timeout_sec      = "30"
  health_checks    = ["${google_compute_health_check.hck.self_link}"]
  session_affinity = "CLIENT_IP"
  region           = "${var.region}"

  backend {
    group = "${google_compute_instance_group_manager.igm.instance_group}"
  }

}
```

### Expected Behavior
I would like to use the `session_affinity` attribute on a `google_compute_region_backend_service`.
I know that this is a new feature on google's part, so I'm just adding some backlog here. I'll see if I could contribute, although I'm not used of coding in go ^^'

### Actual Behavior
```
Errors:

  * google_compute_region_backend_service.bes-prgall: : invalid or unknown key: session_affinity

```

### References
I have found none, I'm sorry if there is an existing issue

**Comment by zopanix** [comment]
@cblecker: Thx a lot for this, had plaaned some tie today to try and contribute :)

**Comment by cblecker** [comment]
@zopanix: I'm sorry! I completely missed where you said you were going to give this a shot yourself. Didn't mean to pull the rug out from under you.

If you want to get involved in learning go, this is a great project to get involved with -- lots of smart, friendly people around these parts. There are always plenty of little issues, fixes, etc that you can go and break off.

**Comment by zopanix** [comment]
@cblecker: Don't worry about it, it's great to see things getting done this quickly. I can still do it my self and then compare it to what you've done :)

No thx a lot for this one, I really needed this feature :)
