### ISSUE TITLE
heredocs don't seem to work for data template_file objects

### ISSUE THREAD

**Issue by donnoman** [hashicorp/terraform#11203]
### Terraform Version

```
› terraform -v
Terraform v0.8.4
```

### Affected Resource(s)
- data.template_file

### Terraform Configuration Files

I am trying to get json as output, but the default terraform output --json outputs the variables with sensitive , type, and value keys which I don't wan't. I just want key->value json.

I am trying to use heredoc or multi line strings and neither seems to work.

Based on other documentation this SEEMS like it would work.

but i've tried with and without a declaration of  `inline_script = true`; 
with it true I get `invalid or unknown key: inline_script`

with it unset, everything runs normally.... but no output it just seems to ignore the whole output variable "json_config"

```
data "template_file" "json_config" {
  template = <<EOF
{
  "stage": "$${var.stage}",
  "security_group_id": "$${module.site.security_group_id}",
  "source_ami": "$${module.site.source_ami}",
  "region": "$${module.site.aws_region}",
  "instance_type": "$${module.site.instance_type}"
}
EOF
  vars {
    stage = "${var.stage}"
    security_group_id = "${module.site.security_group_id}"
    source_ami = "${module.site.source_ami}"
    region = "${module.site.aws_region}"
    instance_type = "${module.site.instance_type}"
  }
}

output "json_config" {
  value = "${data.template_file.json_config.rendered}"
}
```

### Expected Behavior

It should have output the rendered heredoc

### Actual Behavior

no error, complete skipped the output of that variable json_config

### Steps to Reproduce

1. `terraform refresh`

**Comment by jbardin** [comment]
Hi @donnoman,

There a few errors in the config here, causing the template file to fail. 
Inside the template you are referencing the variables you defined for that template, so it's not by the global name. You're config should probably look something like:

data "template_file" "json_config" {
  template = <<EOF
{
  "stage": "$${stage}",
  "security_group_id": "$${security_group_id}",
  "source_ami": "$${source_ami}",
  "region": "$${region}",
  "instance_type": "$${instance_type}"
}
EOF
  vars {
    stage = "${var.stage}"
    security_group_id = "${module.site.security_group_id}"
    source_ami = "${module.site.source_ami}"
    region = "${module.site.aws_region}"
    instance_type = "${module.site.instance_type}"
  }
}

output "json_config" {
  value = "${data.template_file.json_config.rendered}"
}

As for the empty output, on the latest master I'm getting an error about the variables not being defined, so I think that should be better in the next release.

**Comment by donnoman** [comment]
What I pasted was the second version because nothing was working; My first version was essentially what you posted.

I found an additional problem with `source_ami = "${module.site.source_ami}"` which was a nested module.   Any time I added a value from that the plan would stop echo'ing the real values to be interpolated with the variable names

so this is my current version, double $ escaped  no var prefix 

```
data "template_file" "json_config" {
  template = <<EOF
{
  "stage": "$${stage}",
  "security_group_id": "$${security_group_id}",
  "region": "$${region}",
  "instance_type": "$${instance_type}",
  "source_ami": "$${source_ami}"
}
EOF
  vars {
    stage = "${var.stage}"
    security_group_id = "${module.site.security_group_id}"
    source_ami = "${module.ami.ami_id}"
    region = "${module.site.aws_region}"
    instance_type = "${module.site.instance_type}"
  }
}

output "json_config" {
  value = "${data.template_file.json_config.rendered}"
}
```

and I've come back full circle with this error:

* data.template_file.json_config: failed to render : 2:15: unknown variable accessed: stage

**Comment by donnoman** [comment]
According to the documentation: 

https://www.terraform.io/docs/providers/template/d/file.html#inline-templates

The second example: 

```
variable "port" { default = 80 }

data "template_file" "init" {
    template = "$${foo}:${var.port}"

    vars {
        foo = "${count.index}"
    }
}
```

suggests you don't have to use the intermediary value, so I switched to.

```
output "stage" {
  value = "${var.stage}"
}

output "security_group_id" {
  value = "${module.site.security_group_id}"
}

output "source_ami" {
  value = "${module.ami.ami_id}"
}

output "region" {
  value = "${var.aws_region}"
}

output "instance_type" {
  value = "${var.instance_type}"
}

data "template_file" "json_config" {
  template = <<EOF
{
  "stage": "${var.stage}",
  "security_group_id": "${module.site.security_group_id}",
  "region": "${var.aws_region}",
  "instance_type": "${var.instance_type}",
  "source_ami": "${module.ami.ami_id}"
}
EOF
}

output "json_config" {
  value = "${data.template_file.json_config.rendered}"
}
```

and back to getting nothing

```
Outputs:

instance_type = m2.medium
json_config =
region = us-west-2
security_group_id = sg-9ec912e6
stage = staging
```

the outputs prove the values are available.

**Comment by donnoman** [comment]
if I remove this line from the template: `
   "source_ami": "${module.ami.ami_id}"`

then it works

```
Outputs:

instance_type = m2.medium
json_config = {
  "stage": "staging",
  "security_group_id": "sg-9ec912e6",
  "region": "us-west-2",
  "instance_type": "m2.medium",

}

region = us-west-2
security_group_id = sg-9ec912e6
stage = staging
```

and now I notice that source_ami WASN'T printed in the previous outputs
```
module "ami" {
  source = "github.com/terraform-community-modules/tf_aws_ubuntu_ami/ebs"
  region = "${var.aws_region}"
  distribution = "trusty"
  instance_type = "${var.instance_type}"
}
```

https://github.com/terraform-community-modules/tf_aws_ubuntu_ami

its not just because its a module because security_group_id IS working.

**Comment by donnoman** [comment]
I switched to the long form https://github.com/terraform-community-modules/tf_aws_ubuntu_ami

```
module "ami" {
  source = "github.com/terraform-community-modules/tf_aws_ubuntu_ami"
  region = "${var.aws_region}"
  distribution = "trusty"
  architecture = "amd64"
  virttype = "hvm"
  storagetype = "ebs"
}
```

now after much teeth gnashing I have something working

```
instance_type = m2.medium
json_config = {
  "stage": "staging",
  "security_group_id": "sg-9ec912e6",
  "region": "us-west-2",
  "instance_type": "m2.medium",
  "source_ami": "ami-6418c304"
}

region = us-west-2
security_group_id = sg-9ec912e6
source_ami = ami-6418c304
stage = staging
```

**Comment by donnoman** [comment]
I'll report that on the issue board over there, but it could have saved hours to have some kind of warning that whatever was going wrong was breaking that value.

That value wasn't coming back empty... it was just getting silently skipped.

Even if we accept that heredoc's weren't broke.. There is certainly a problem with visibility of errors.
