### ISSUE TITLE
Import with module address fails

### ISSUE THREAD

**Issue by Khodeir** [hashicorp/terraform#11212]
Attempting to import existing AWS resources into a module crashes on Terraform v0.8.4

### Terraform Version
Terraform v0.8.4

### Affected Resource(s)

(I think all resources are affected but below are ones i tried)
- aws_instance
- aws_s3_bucket
- aws_elastic_beanstalk

### Terraform Configuration Files
* ./main.tf:
```hcl
provider "aws" {
  access_key = "VALID_ACCESS_KEY"
  secret_key = "VALID_SECRET_KEY"
  region = "eu-west-1"
}

module "foo" {
  source = "./bar"
}
```
* ./bar/main.tf:
```hcl
resource "aws_s3_bucket" "bucket" {
  bucket = "my_tf_test_bucket"
  acl = "private"
}
```

### Debug Output
https://gist.github.com/Khodeir/1ea447980a1d9a11eb269c6398a7060f

### Expected Behavior
I expected this to import the existing resource under the correct module in my tfstate.

### Actual Behavior
Prompted me to enter the aws region and then failed with 
"No valid credential sources found for AWS Provider."

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform get`
2. `terraform import module.foo.aws_s3_bucket.bucket <bucket_name>`

### Important Factoids
Running on Mac osSierra

**Comment by mitchellh** [comment]
Reproduced. Taking a look!

**Comment by mitchellh** [comment]
PR to fix this queued up.
