### ISSUE TITLE
Cloudflare record import support

### ISSUE THREAD

**Issue by mwarkentin** [hashicorp/terraform#11219]
### Terraform Version

 All.

### Affected Resource(s)

Please list the resources as a list, for example:
- [`cloudflare_record`](https://www.terraform.io/docs/providers/cloudflare/r/record.html)

### Expected Behavior

Terraform supports import of existing cloudflare records into state.

### Important Factoids

Need to determine how the record would be referenced:

* Record ID
* Full DNS name (may be ambiguous as you could have multiple types of records for the same domain)

### References

First reported in #3715 but closed as `terraform import` wasn't a thing.

**Comment by w0mbat** [comment]
I would also totally love to see this :)
