### ISSUE TITLE
Inconsistency of Terraform command parameters

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/terraform#11211]
Hi,

Usually one uses variables to instruct terraform what to do with a resource and how. I.e. variables for production, variables for development, etc. Those would ideally live in separate files (I.e. `production.tfvars`, `development.tfvars`).

Then, when issuing terraform commands, one would do:
```
terraform plan -var-file=development.tfvars
```
Or:
```
terraform plan -var-file=production.tfvars
```

I see `terraform import` does not support the `-var-file` parameter. This makes the CLI parameters inconsistent and, IMO, breaks the user experience.

The lack of `-var-file` support in the `terraform import` command causes scenarios like the following:
```
# main.tf
terraform {
  required_version = "> 0.8.0"
}

provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}

resource "aws_vpc" "main_vpc" {
  cidr_block = "10.10.0.0/16"
  tags {
    Name = "main-vpc"
    Environment = "${var.environment}"
  }
}

# Then, on the CLI
$ terraform import aws_vpc.main_vpc {{vpc_id}}

Error importing: 1 error(s) occurred:

* 1:3: unknown variable accessed: var.access_key in:

${var.access_key}
```

As you can see, there's no way I can run an import.

I am aware of the `-config` command parameter applied to `terraform import`. But that requires the "[path to directory of Terraform configuration files that configure the provider for import](https://www.terraform.io/docs/commands/import.html#_config_path)". 

Configuring the provider is different from being aware of all the variables defined in the `*.tf` files needed to work with and let terraform know what to do and how. 

Unless I'm missing something, I think the `terraform import` command (and probably all other commands) should be variables-aware. 

### Terraform Version
`0.8.4`

### Affected Resource(s)
All `*.tf` files defining resources which interpolate variables in their parameters.

### Terraform Configuration Files
Please see above.

### Debug Output
Please see above.

### Panic Output
N/A

### Expected Behavior
Please see above.

### Actual Behavior
Please see above.

### Steps to Reproduce
Please see above.

### Important Factoids
Please see above.

### References
N/A

**Comment by mitchellh** [comment]
This was just missing docs. I've added docs and updated the tests to cover it as well. But this should work as-is in the current version of Terraform.
