### ISSUE TITLE
AWS RDS backup_window format not recognized

### ISSUE THREAD

**Issue by lajoie** [hashicorp/terraform#11225]
**Terraform Version:** 0.8.4

When using the `aws_db_instance` resource, the `backup_window` field  does not seem to be properly handled.  Here's some sample inputs that I've tried: `07:00-0:800`, `17:00-18:00`, `19:00-20:00`, and `19:11–20:51`.

All of these report the same error:
`aws_db_instance.db: "backup_window" must satisfy the format of "hh24:mi-hh24:mi".`

Looking at the [function](https://github.com/hashicorp/terraform/blob/b4053dcdc6ed1e49924c3a3cc98e55c2ade4462c/builtin/providers/aws/validators.go#L640) used to verify this, it looks like all of these should work.

**Comment by grubernaut** [comment]
Hi @lajoie, thanks for the issue! 

I've written a few tests to cover the sample inputs that you've provided, but I can't reproduce your failure. Would you be able to provide me with the `aws_db_instance` resource configuration that you're using and seeing the errors with? Thanks!

**Comment by lajoie** [comment]
Sure.

I first encountered the issue in a heavily parameterized module that I wrote, but here's the result of filling in all the variables by hand.  It produces the same error and can be run without all the other stuff in our environment.

```
provider "aws" {
  region = "us-west-2"
}

resource "aws_db_instance" "db" {
  # instance parameters
  identifier = "xxxxx"
  instance_class = "db.t2.medium"
  multi_az = false
  publicly_accessible = false
  db_subnet_group_name = "xxxxx"
  vpc_security_group_ids = ["sg_xxxxx"]

  # storage parameters
  storage_type = "gp2"
  iops = "0"
  allocated_storage = "100"

  # engine parameters
  engine = "postgres"
  engine_version = "9.6.1"
  port = "5432"
  username = "admin"
  password = "xxxxx"

  # backup and maintenance parameters
  backup_window = "07:00–08:00"
  backup_retention_period = 15
  maintenance_window = "Sun:10:00-Sun:12:00"
  auto_minor_version_upgrade = true
  allow_major_version_upgrade = false

  # final, on destroy, snapshot parameters
  skip_final_snapshot = false
  final_snapshot_identifier = "db-postgres-xxxxx-snapshot-final"
  copy_tags_to_snapshot = true

  tags { 
    Name = "xxxxx"
    Creator = "xxxxx"
  }
}
```

**Comment by grubernaut** [comment]
@lajoie, awesome! Was able to get a successful reproduction. Should have a fix pushed here shortly.

**Comment by grubernaut** [comment]
@lajoie so, interesting outcome...

The character in your config output `-` is not a true dash. If I replace the `–` (U+2014) character in your supplied configuration with the actual `-` (U+2013) character, it parses flawlessly. 

Can you attempt to rewrite the `backup_window` string with the `U+2013` character, and report back if it works or not? Thanks!

**Comment by lajoie** [comment]
wow... I wonder how I managed to fat finger something that ended up giving me a visually identical character to the one I wanted.

Oh well.  That worked.  Thank you!
