### ISSUE TITLE
FR: Ability to store vars-files in a config file

### ISSUE THREAD

**Issue by fgimian** [hashicorp/terraform#11230]
### Terraform Version

```
Terraform v0.8.4
```

### Feature Request

We current run Terraform with multiple vars-files, e.g.:

```
terraform plan \
  -var-file="global.tfvars" \
  -var-file="vpc1.tfvars" \
  -var-file="vpc2.tfvars" \
  -var-file="vpc3.tfvars" \
  -var-file="vpc4.tfvars" 
```

It would be awesome if there was a way to store the var-files required in a config file (or similar) so that they wouldn't have to be specified every time you run terraform.

**Comment by SPhu** [comment]
If you name the files *.auto.tfvars it will autoload.  This seems to negate the need for a separate config file.  Also you can just store your command in a shell script.  

> or all files which match terraform.tfvars or *.auto.tfvars present in the current directory, Terraform automatically loads them to populate variables. If the file is located somewhere else, you can pass the path to the file using the -var-file flag. It is recommended to name such files with names ending in .tfvars.

[https://www.terraform.io/docs/configuration/variables.html#variable-files](https://www.terraform.io/docs/configuration/variables.html#variable-files)

**Comment by pkolyvas** [comment]
I would second the above solution(s). I'm going to close this one out. Please ping me if you feel that's an error on my part.
