### ISSUE TITLE
new indexing with splat interpolates with wrong values

### ISSUE THREAD

**Issue by sjwl** [hashicorp/terraform#11241]
### Terraform Version
0.8.4

### Affected Resource(s)
- test_resource
- any resource that has a computed list as an attribute

### Terraform Configuration Files
```hcl
resource "test_resource" "foo" {
  count    = 2
  required = "${count.index}"

  required_map {
    foo = "foo"
  }
}

output "list_of_list_dump" {
  value = ["${test_resource.foo.*.computed_list}"]
}

output "new_indexing_splat_wrong" {
  value = ["${test_resource.foo.*.computed_list[1]}"]
}
output "old_indexing_correct" {
  value = ["${test_resource.foo.*.computed_list.1}"]
}
output "new_indexing_0_correct" {
  value = "${test_resource.foo.0.computed_list[1]}"
}
output "new_indexing_1_correct" {
  value = "${test_resource.foo.1.computed_list[1]}"
}

provider "test" {}

```

### Debug Output
```
Outputs:

list_of_list_dump = [
    [
        listval1,
        listval2
    ],
    [
        listval1,
        listval2
    ]
]
new_indexing_0_correct = listval2
new_indexing_1_correct = listval2
new_indexing_splat_wrong = [
    listval1,
    listval2
]
old_indexing_correct = [
    listval2,
    listval2
]
```
https://gist.github.com/sjwl/f98bb387dc1a78fd92f3f5a05467db3d

### Panic Output
n/a

### Expected Behavior
the new indexing interpolation (`new_indexing_splat_wrong`) should have returned 'listval2' for both elements
```hcl
new_indexing_splat_wrong = [
    listval2,
    listval2
]
```

### Actual Behavior
the new indexing interpolation (`new_indexing_splat_wrong`) returned
```hcl
new_indexing_splat_wrong = [
    listval1,
    listval2
]
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

- using the 'old indexing' method seems to work
- the problem seems to a combination of the splat ('*') and the new indexing []

### References
none

**Comment by jbardin** [comment]
Hi @sjwl,

I think this is working as intended here. 

The interpolation string `"${test_resource.foo.*.computed_list[1]}"` first expands the splat into 2 lists, of which you are indexing the second.

There currently is no notation to directly retrieve a list of the i'th elements from a series of lists..

**Comment by sjwl** [comment]
@jbardin you said, _There currently is no notation to directly retrieve a list of the i'th elements from a series of lists.._

But this notation seems to work: ```"${test_resource.foo.*.computed_list.1}"```

Are you saying this notation is 'unsupported' and likely change at any time?

**Comment by jbardin** [comment]
The difference is that isn't an "index operation". In that example, the expansion happens by looking for the set of addresses that satisfy the wildcard `test_resource.foo.*.computed_list.1`, which returns these 2 values and no other processing is done.

    ["test_resource.foo.0.computed_list.1", "test_resource.foo.1.computed_list.1"]

When using the square bracket notation, `test_resource.foo.*.computed_list` must first be expanded to evaluate _what_ is going to be indexed. In this case that returns a list of 2 lists, and then the square brackets can be evaluated like so:

    [["listval1", "listval2"], ["listval1", "listval2"]][1]
 
 resulting in:
    
    ["listval1", "listval2"]

**Comment by sjwl** [comment]
@jbardin you said, _There currently is no notation to directly retrieve a list of the i'th elements from a series of lists.._

Perhaps this issue is not a bug then, but then a feature request?  Is there another format issues should be submitted to become enhancement/wishlist requests?

**Comment by jbardin** [comment]
@sjwl, 

I can re-tag this as a feature request if you have a use case.

It could be implemented as interpolation function, maybe an `ziplist` equivalent to `zipmap`? This would still need to wait on the ability to index from a function result, but it's possible.
