### ISSUE TITLE
Iterating through an array of users in aws_opsworks_user_profile fails.

### ISSUE THREAD

**Issue by ole-flaregames** [hashicorp/terraform#11258]
Hi there,

i found a problem within the resource **aws_opsworks_user_profile** 
It seems like you cannot properly iterate with count through an array of users.
The initial `terraform apply` works perfectly. It creates all users in the correct way. Then you change one user within the array and terraform tries to modify the already existing user with a new username which is not possible in opsworks. I would expect a delete operation for the user that does not exist anymore and the creation of the new user.

### Terraform Version
0.8.4 (probably lower versions are effected as well)

### Affected Resource(s)
- aws_opsworks_user_profile

### Terraform Configuration Files
```
variable "aws_access_key" {} # reading from terraform.tfvars file
variable "aws_secret_key" {} # reading from terraform.tfvars file
variable "aws_region" {} # reading from terraform.tfvars file
variable "aws_iam_user_arn" { default = ["arn:aws:iam::0000000000000:user/testuNM27", "arn:aws:iam::0000000000000:user/testuNM28", "arn:aws:iam::0000000000000:user/testuNM29"]}
variable "aws_opsworks_stack_id" { default = "xxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxx" }
variable "aws_iam_user_ssh" { default = ["testuNM27", "testuNM28", "testuNM29"]}


##############

provider "aws" { access_key = "${var.aws_access_key}" secret_key = "${var.aws_secret_key}" region = "${var.aws_region}" }


resource "aws_opsworks_user_profile" "my_profile" {
  count = "${length(var.aws_iam_user_arn)}"
  ssh_username = "${element(var.aws_iam_user_ssh, count.index)}"
  user_arn = "${element(var.aws_iam_user_arn, count.index)}"
  allow_self_management = true
}

```

### Expected Behavior
 Delete and Create operation instead of modify.

### Actual Behavior

Modify operation - which will cause the AWS API to send an error, because this operation is not possible .
```

~ aws_opsworks_user_profile.my_profile.0
    ssh_username: "testuNM27" => "testuNM25"
    user_arn:     "arn:aws:iam::000000000000:user/testuNM27" => "arn:aws:iam::000000000000:user/testuNM25"


```

### Steps to Reproduce
1. Use code snippet above
2. Initial `terraform apply`
3. Change one user in both arrays (e.g. testuNM27" => "testuNM25" )
4. `terraform apply `

**Comment by Samangan** [comment]
The bug isn't related to using a list or count. 

You can reproduce this bug by using the following tf file:
```
variable "region" {}

provider "aws" {
  region = "${var.region}"
}

resource "aws_opsworks_user_profile" "user" {
  user_arn = "${aws_iam_user.TFBugUser1.arn}"
  ssh_username = "${aws_iam_user.TFBugUser1.name}"
}

resource "aws_iam_user" "TFBugUser1" {
	name = "TFBugUser1"
	path = "/"
}

# After applying, change 'aws_opsworks_user_profile.user.user_arn' to 'TFBugUser2.arn' to reproduce bug.
resource "aws_iam_user" "TFBugUser2" {
	name = "TFBugUser2"
	path = "/"
}
```

This issue name should probably be edited to reflect this.
