### ISSUE TITLE
Support tilde '~' in shared credentials path for providers

### ISSUE THREAD

**Issue by joshlove** [hashicorp/terraform#11268]
### Terraform Version
v.0.8.2

### Affected Resource(s)
- aws provider

### Terraform Configuration Files
```hcl
provider "aws" {
  region                   = "us-west-2"
  shared_credentials_file  = "~/.aws/creds"
  profile                  = "customprofile"
}
```

### Expected Behavior
Evaluate to my $HOME, and then use the aws creds file from there. This would be nice in a team environment so we don't have usernames hardcoded.

Workaround is a wrapper script for this, but this would be nice as an enhancement.

**Comment by grubernaut** [comment]
Hi @joshlove, thanks for the issue!

I've submitted #11277, which should allow you to use the `pathexpand()` interpolation function inside your provider config, and elsewhere.

```hcl
provider "aws" {
  region                   = "us-west-2"
  shared_credentials_file  = "${pathexpand(~/.aws/creds)}"
  profile                  = "customprofile"
}
```

**Comment by joshlove** [comment]
Appreciate your work on this, thanks!
