### ISSUE TITLE
Structured documentation

### ISSUE THREAD

**Issue by AndreaCrotti** [hashicorp/terraform#11262]
As an Emacs user, when working with ansible I use this little package:
https://github.com/lunaryorn/ansible-doc.el

And it's really great to be able to see the docs inline like that.
Looking at terraform docs, potentially we could do exactly the same thing, since it's quite well structured.
However now it's only in HTML AFAIK and there is no easy way to process it from some other automated tool, is that correct?

In the worst case we can still parse the HTML sure, but I was wondering if there was another way or there are any plans for this?
Thanks

**Comment by apparentlymart** [comment]
Hi @AndreaCrotti!

I'm not sure if this helps at all, but the docs are mastered in the git repo in markdown (see the "website" for in the root) so it can, at least in theory, be rendered into other text-oriented formats, though it's not structured enough to extract specific attribute docs automatically.

A caveat there is that the current structure of the docs is not an interface contract, so might well change in a breaking way in future.

One day it would be nice to be able to extract the schema info that lives in the code to enable tooling like autocomplete in Terraform configs.

**Comment by teamterraform** [comment]
Hi again @AndreaCrotti!

Terraform 0.12 now includes a command `terraform providers schema -json` which, when run in an already-initialized Terraform working directory, will produce a JSON representation of the schema for all of the providers used by the configuration.

That doesn't include _all_ of the details that are available in the markdown documentation, but it does include a full manifest of all of the supported arguments, exported attributes, the data types the expect, and in many cases also a short English language description of what they represent.

This mechanism may grow to include other information in future, but we believe there's enough there now for the use-case you described of integration with text editors, so we're going to close this out. Thanks for sharing this use-case, and sorry for the long delay in responding to it.
