### ISSUE TITLE
Experimental feature failure: `Unknown 'ValidateResource' shadow value for "aws_security_group"`

### ISSUE THREAD

**Issue by kojiromike** [hashicorp/terraform#11281]
Just doing what I'm told:

> Experimental feature failure! Please report a bug.

The error file had this content:

```
1 error(s) occurred:

* plan operation: Unknown 'ValidateResource' shadow value for "aws_security_group": &errors.errorString{s:"shadow closed"}
```

I'm using terraform 0.8.4

**Comment by mitchellh** [comment]
Thanks for reporting this. Do you have a configuration/state to reproduce this? Unfortunately without this we won't be able to do anything about this.

**Comment by kojiromike** [comment]
@mitchellh ah, no, sorry, I was a bit surprised that the error file didn't have more of the configuration in it. I'll close this and hopefully someone else with more available configs can help.
