### ISSUE TITLE
Allow converting existing resources into Terraform code & manage these

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1128]
If I have created previously my infrastructure via any GUI (like AWS Console or Google Cloud Console), I may want to be able to control it via Terraform instead of recreating it again.

I know that there's a certain gap between running infrastructure (very precise configuration and relationship) & DSL like TF.
I don't expect a final generated code with variables and meaningful relationships between resources. I would expect something to generate a code which I can take and just apply some further brain capacity and then put it actually into the Terraform codebase.

Example:
```
$ terraform manage -provider=aws -resource-type=aws_instance
```
```
Calling the API...
Downloaded 5 resources of type aws_instance, 3 are not managed by Terraform.

resource "aws_instance" "" {
    ami = "ami-1234"
    instance_type = "m1.small"
    tags {
        Name = "HelloWorld"
    }
}
resource "aws_instance" "" {
    ami = "ami-abcd"
    instance_type = "m2.large"
    tags {
        Name = "HelloWorld"
    }
}
resource "aws_instance" "" {
    ami = "ami-zzzz"
    instance_type = "m1.small"
    tags {
        Name = "HelloWorld"
    }
}
```

This would allow Terraform to be even less disruptive tool IMO.

**Comment by phinze** [comment]
Hey @radeksimko - this is very much a feature we'd like to add. We've been generally calling it `terraform import` but I kind of like the `manage` verb as well. I've also thought of it as `adopt`, too. But deciding on the verb will come down the line when we actually start implementing the feature. :grinning:

Closing so we can consolidate discussion of the feature over on its original issue at #581
