### ISSUE TITLE
Allow adding "instructions" into the output

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1129]
The only output format that one can use in these days is an alphabetically sorted list of variables (key = value).

What about allowing paragraphs of text as instructions?

Example:

``` ruby
output "etcd_discovery_url" {
  instruction = <<INSTRUCTION
Now use following to connect to the new box:
    ssh ec2-user@${aws_instance.default.public_ip}
INSTRUCTION
}
```

**Comment by phinze** [comment]
I think you can accomplish this today via heredocs + output values without too much trouble.

```tf
# For programmatic access
output "etcd_ip" { value = "${aws_instance.default.public_ip}" }
# For humans
output "_etcd_instructions" {
  value = <<INSTRUCTION
You can connect to etcd like so:
  ssh ec2-user@${aws_instance.default.public_ip}
INSTRUCTION
}
```

If we added `instructions` another piece of metadata to `output` - how would that work for display - it would show up by default on `terraform apply`, but not on `terraform output foo` without some flag perhaps?

To me, it feels like the workaround is reasonable enough to skip the feature, but let me know if you still think it would be valuable, @radeksimko.

**Comment by ketzacoatl** [comment]
maybe what we need is a section in docs with common scenarios and possible solutions like this?

**Comment by radeksimko** [comment]
I definitely don't treat this feature like a critical one and the workaround sounds reasonable, just the perfectionistic evil inside of me is moaning about the format of the output:

```
Outputs:

  _etcd_instructions = 
You can connect to etcd like so:
```

@spoon16 originally came up with this idea - wanna add anything to the discussion, Eric? :)

**Comment by mitchellh** [comment]
Although opened a year later, going to use #9678 as the issue for this. :)
