### ISSUE TITLE
Discrepancy in plan console output when no resource changes

### ISSUE THREAD

**Issue by dcosson** [hashicorp/terraform#11299]
This is a small issue, but I think the `terraform plan` output needs a small update after the 0.7 change that stopped writing to the tfstate file during a plan.

The console output is very clear when resources have changed - it shows what needs to change, and shows the path to the plan file that was written, if any.

But when no resources have changed, the last line of the output is `As a result, Terraform doesn't need to do anything.`, and it doesn't print the plan file location even though it does still write a plan file.  The `terraform output` command prints conflicting advice that `If you recently added this to your configuration, be sure to run 'terraform apply'`. This makes it seem like you need to run a "blind" terraform apply since it doesn't look like any plan file was written, but there actually is a plan file you can use.

I'm not sure if terraform knows that there is a new output or other metadata to write to the tfstate file when the `plan` runs, but if so it would be helpful if the console output said "no resources have changed but the tfstate file needs to be updated" or something like that.

And regardless, it would be useful if terraform would print the path to the (possibly empty) plan file any time it has written one.

**Comment by pkolyvas** [comment]
@dcosson great news, if a bit overdue. Terraform `0.13` now offers `output` updates, where no resources have changed, through the plan and apply workflow. While not exactly what you're asking for here, we hope this increased congruency in how outputs are declared, updated and written to state make this request a solved one!

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
