### ISSUE TITLE
terraform 0.8.4 does not set a non-zero exit code on failure

### ISSUE THREAD

**Issue by zapman449** [hashicorp/terraform#11302]
### Terraform Version
Terraform v0.8.4

### Affected Resource(s)
N/A

### Terraform Configuration Files
I'm struggling to come with something simple.

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
If terraform apply fails on any item, it should set a non-zero error code.

### Actual Behavior
Terraform set an error code of zero

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
n/a

### References
I didn't see anything

### Background:
In terraform 0.7.4 (at least) Terraform would set a non-zero exit code if anything failed to apply.  This is important if you're using Terraform in a pipeline, so that the harness running the pipeline can notice if something failed.

Terraform 0.8.4 does not follow this behavior.

**Comment by mitchellh** [comment]
I can't reproduce this. I've tried various resources and got them to fail at different stages (TF validation, remote API, provisioner, etc.) and in every case I've gotten an exit code '1'. 

I believe you're seeing an issue though so as a next step could you please give us some reproduction config and steps so we can look at this further?

**Comment by zapman449** [comment]
i'll look for a reproduction process.

**Comment by mitchellh** [comment]
Closing due to lack of response. If you do figure this out please open a new issue with the above information. Thanks!
