### ISSUE TITLE
[provider - newrelic] newrelic_alert_condition shows drift after applying

### ISSUE THREAD

**Issue by pickgr** [hashicorp/terraform#11317]
### Terraform Version
$ terraform -v
Terraform v0.8.4

### Affected Resource(s)
newrelic_alert_condition

### Terraform Configuration Files
```hcl
resource "newrelic_alert_condition" "error_critical" {
  policy_id = "${newrelic_alert_policy.critical.id}"

  name        = "Errors critical"
  type        = "apm_app_metric"
  entities    = ["${data.newrelic_application.foo.id}", "${data.newrelic_application.bar.id}", "${data.newrelic_application.bam.id}"]
  metric      = "error_percentage"
  runbook_url = "${var.runbook_url}"

  term {
    duration      = 5
    operator      = "above"
    priority      = "critical"
    threshold     = "5"
    time_function = "all"
  }

  term {
    duration      = 10
    operator      = "above"
    priority      = "warning"
    threshold     = "1"
    time_function = "all"
  }
}
```

### Expected Behavior
Configuration should apply successfully creating the alert condition.  Subsequent "terraform plan" should show no drift (diff) 

### Actual Behavior
The following diff is shown when running plan after apply:

```
~ newrelic_alert_condition.error_critical
    term.0.duration:  "10" => "5"
    term.0.priority:  "warning" => "critical"
    term.0.threshold: "1" => "5"
    term.1.duration:  "5" => "10"
    term.1.priority:  "critical" => "warning"
    term.1.threshold: "5" => "1"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

It's unknown if the NewRelic API returns the terms in a different order or how to reproduce this.  There are other alert conditions not showing drift.  Perhaps they just need to be sorted.

**Comment by pickgr** [comment]
@paultyng - thanks for the create new provider!

Was wondering if you had run into this?

**Comment by paultyng** [comment]
@pickgr it probably just needs to match existing terms better when they exist, I imagine its just some naive matching on my part and like you suggest the API just returns them in random order.

**Comment by paultyng** [comment]
Some more deterministic sorting of the terms would probably go a long way on this.

**Comment by PurrBiscuit** [comment]
I'm seeing this occur in my terraform plans as well (version 0.9.5).  It just seems like the terms keep flip flopping on every subsequent terraform run/plan since the first apply succeeded.

```
~ module.newrelic.newrelic_alert_condition.apm_app_server_apdex
    name:             "Apdex below .7" => "Apdex below 0.7"
    term.0.duration:  "10" => "5"
    term.0.priority:  "warning" => "critical"
    term.0.threshold: "0.85" => "0.7"
    term.1.duration:  "5" => "10"
    term.1.priority:  "critical" => "warning"
    term.1.threshold: "0.7" => "0.85"
```
