### ISSUE TITLE
Add Heroku Pipelines

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#11326]
The [currently used Go binding](https://github.com/cyberdelia/heroku-go/) doesn't support them, though.

However, [Heroku's API itself does](https://devcenter.heroku.com/articles/pipelines-using-the-platform-api).

Given that the library's generated from a schema, and that generator has been broken since 2014 (cf. cyberdelia/heroku-go#9; interagent/schematic#29) might it be worth abandoning it in favour of HTTP requests at this point?

**Comment by danp** [comment]
Fixed by #14078

**Comment by catsby** [comment]
Closed by #14078
