### ISSUE TITLE
provider/fastly Allow passing a dynamic list of domains to the fastly service

### ISSUE THREAD

**Issue by msuterski** [hashicorp/terraform#11322]
Fastly allows attaching multiple domains to their services. 

Current behavior:
To attach multiple domains to the Fastly's service they need to be listed explicitly one by one

```
resource "fastly_service_v1" "myservice" {
  name = "myservice.prd"

  domain {
    name = "myservice.example.com"
    comment = ""
  }

  domain {
    name = "myservice1.example.com"
    comment = ""
  }
...
}
```

This is very inconvenient (actually a deal breaker for us) when we'd like to reuse the same service configuration across different environments. I.e. in dev we might have 1 or 2 domains, but in prd we might have 20.

Expected behavior:

Pass a list of domains through a variable and the resources will be generated appropriately. Something like:
```
resource "fastly_service_v1" "myservice" {
  name = "myservice.prd"

  domain {
    count = "${length(var.domains)}"
    name = "${element(var.domains, count.index)}"
    comment = ""
  }
...
}
```

This is similar to https://github.com/hashicorp/terraform/issues/4726 but I'm not sure if it's going to be solved by linked to it https://github.com/hashicorp/terraform/issues/2275. The domains in Fastly cannot be created outside of the service create/update "transaction".

Similar limitation applies to `backend` resource, but this one can be workaround'ed with including backends definitions in custom VCL. But ideally, same fix could be made to the `backend`.

**Comment by JakeChampion** [comment]
This is also a deal-breaker for us. @msuterski, do you know if anything has progressed with this?

**Comment by msuterski** [comment]
@JakeChampion I didn't see any movement around it yet, but I also did not pay much attention. I might get to filing a patch for it at some point since I think it should not be complicated to allow domains to be applied from a variable or a var-file.

**Comment by msuterski** [comment]
So the "problem" (or inconvenience) with the domains [definition](https://github.com/hashicorp/terraform/blob/master/builtin/providers/fastly/resource_fastly_service_v1.go#L44-L61) is that I couldn't figure out how or if there is a way to represent this TypeSet using the basic datatypes that terraform supports. 

If it's possible and someone could paste it here, it would solve the problem without changes to the TF.

Otherwise, to be able to pass domains dynamically, domain would need to be a simple (list of?) map(s).

**Comment by karnauskas** [comment]
I need this too.
