### ISSUE TITLE
Chaining index lookup to interpolations which return arrays no longer works

### ISSUE THREAD

**Issue by thegranddesign** [hashicorp/terraform#11337]
I want to say that on 0.6 and possibly 0.7, this used to work.  I'm not sure which version broke the functionality.

### Terraform Version
0.8.4

### Affected Resource(s)
N/A

### Terraform Configuration Files
```json
{
  "variable": {
    "foobar": {
      "default": "hello,there"
    }
  },
  "output": {
    "foobar": {
      "value": "${split(\",\", hello)[0]}"
    }
  }
}
```

### Debug Output
N/A

### Panic Output
```
Error loading config: Error loading foo.tf.json: Error reading config for output foobar: parse error at 1:20: expected "}" but found "["
```

### Expected Behavior
The output variable `foobar` should be `hello`

### Actual Behavior
💣

### Steps to Reproduce
1. `terraform apply`

**Comment by mitchellh** [comment]
These never did work. Not yet. 

We have it planned to do this and @apparentlymart is working on it. I'm sorry to do this but: I don't know the issue # but there is a core bug/enhance tracking this feature (perhaps Martin knows) so I'm going to close this as a dup.

We hope to have this working soon!
