### ISSUE TITLE
Moving launch configuration name_prefix from Terraform to CloudFormation

### ISSUE THREAD

**Issue by tdeheurles** [hashicorp/terraform#11351]
Hi,

One of my project is developped with terraform and works as expected. 

A support company want my code to be written in CloudFormation instead of terraform. So I need to translate my terraform code into cloudFormation one.

My issue is when I try to translate the `name_prefix` of the launch configuration. This option seems not present in the cloudFOrmation configuration:
```json
{
   "Type" : "AWS::AutoScaling::LaunchConfiguration",
   "Properties" : {
      "AssociatePublicIpAddress" : Boolean,
      "BlockDeviceMappings" : [ BlockDeviceMapping, ... ],
      "ClassicLinkVPCId" : String,
      "ClassicLinkVPCSecurityGroups" : [ String, ... ],
      "EbsOptimized" : Boolean,
      "IamInstanceProfile" : String,
      "ImageId" : String,
      "InstanceId" : String,
      "InstanceMonitoring" : Boolean,
      "InstanceType" : String,
      "KernelId" : String,
      "KeyName" : String,
      "PlacementTenancy" : String,
      "RamDiskId" : String,
      "SecurityGroups" : [ SecurityGroup, ... ],
      "SpotPrice" : String,
      "UserData" : String
   }
}
```

Maybe someone know if terraform is doing a specific process for this specific `name_prefix`

### Terraform Version
version 8.2

### Affected Resource(s)
- aws_launch_configuration

### Terraform Configuration Files
```hcl
resource "aws_launch_configuration" "service_name" {
    name_prefix = "myprefix-"
    [...]
}
```

**Comment by stack72** [comment]
Hi @tdeheurles 

Thanks for the request here - in the terraform code, if you supply a name_prefix, we will append a random string (to the length of 26 characters) and then assign the contents of that 26 character string to the name parameter

So to translate this to cloudformation, you would need to stop using the name_prefix and start using name instead

Thanks

Paul
