### ISSUE TITLE
Better support for partial version in aws_db_instances

### ISSUE THREAD

**Issue by alext** [hashicorp/terraform#11355]
The AWS API allows specifying a partial version (ie "9.5" instead of "9.5.4") when creating an RDS instance. This when combined with `auto_minor_version_upgrade=true` can be used to specify that you want an instance using the latest point release of a given major version.

At present, this mostly works with terraform, but results in terraform trying to change the version on every run, which takes 30-40 seconds, even though the actual change is a no-op.

### Terraform Version

```
$ terraform -v
Terraform v0.8.4
```

### Affected Resource(s)

- aws_db_instance

### Terraform Configuration Files
```hcl
resource "aws_db_instance" "test" {
  identifier              = "tf-test"
  allocated_storage       = 5
  storage_type            = "gp2"
  instance_class          = "db.t2.micro"
  backup_retention_period = 0
  username                = "dbadmin"
  password                = "super-secret"

  engine                     = "postgres"
  engine_version             = "9.5"
  auto_minor_version_upgrade = true
}
```

### Debug Output

```
$ TF_LOG=DEBUG TF_LOG_PATH=rds_partial_version_debug.log terraform apply
aws_db_instance.test: Refreshing state... (ID: tf-test)
aws_db_instance.test: Modifying...
  engine_version: "9.5.4" => "9.5"
aws_db_instance.test: Still modifying... (10s elapsed)
aws_db_instance.test: Still modifying... (20s elapsed)
aws_db_instance.test: Still modifying... (30s elapsed)
aws_db_instance.test: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

Debug log: https://gist.github.com/alext/89824c542bf4d598e03af4cb90dd0d2e

### Expected Behavior

Terraform should not have attempted to update the resource.

### Actual Behavior

Terraform attempted to change the version from "9.5.4" to "9.5"

### Steps to Reproduce

1. `terraform apply` to create the initial resource
1. `terraform apply` a second time to see it being updated.

**Comment by stack72** [comment]
Hi @alext 

Thanks for getting in touch here. From looking at your terraform config, you are missing `apply_immediately = true` 

By adding that value, you are going to tell RDS to make the change now. The behaviour without this config change is to default to the next maintenance window. Therefore, the upgrade hasn't happened and terraform thinks that it has to re-try the upgrade again

Please be careful with apply_immediately though, it can cause a reboot of your RDS instance

Hope this helps

Paul

**Comment by alext** [comment]
Hi,

I take your point about `apply_immediately`, however in this example it's not a factor because this is a newly created instance (ie it doesn't exist before the first `terraform apply` run.

thanks,
Alex

**Comment by alext** [comment]
To be clear, I'm filing this as a feature-request, not as a bug.
