### ISSUE TITLE
Crash with latest dev: "panic: reflect: call of reflect.Value.Interface on zero Value"

### ISSUE THREAD

**Issue by s0enke** [hashicorp/terraform#1135]
Terraform setup: https://gist.github.com/s0enke/dcf43b43eff79618691e#file-setup

Crash Log: https://gist.github.com/s0enke/dcf43b43eff79618691e#file-crashlog-txt

**Comment by phinze** [comment]
Hey thanks for the report!

We think we might have _just_ landed the fix for this over in https://github.com/hashicorp/aws-sdk-go/pull/5

Would you mind running a fresh `make updatedeps`, rebuilding, and giving this another shot?

**Comment by s0enke** [comment]
:rocket: awesome, that fixed the issue for me! :rocket:
