### ISSUE TITLE
elasticache_replication_group = aws_elasticache_cluster + replication?

### ISSUE THREAD

**Issue by eyalzek** [hashicorp/terraform#11357]
I want to create an elasticache cluster with 1 primary node and 2 replicas, but since:
https://www.terraform.io/docs/providers/aws/r/elasticache_cluster.html
takes only `1` for `num_cache_nodes` (when using redis), and:
https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html
doesn't take a `primary_cluster_id`, I was wondering if creating an `elasticache_replication_group` and passing `number_cache_clusters = 2` would achieve the same thing?

From my testing it seemed it does, but I'm not entirely sure about that. Did I get it right and the documentation should be clearer, or am I wrong?

**Comment by jotum** [comment]
In your case, you need to use `elasticache_replication_group` and pass `number_cache_clusters = 3`.
`num_cache_clusters` is the total number of cache instances, so 3 = 1 master + 2 replicas
