### ISSUE TITLE
Add tag support to AWS DynamoDB resource

### ISSUE THREAD

**Issue by gpetras** [hashicorp/terraform#11386]
AWS just announced support for tags in DynamoDB:

https://aws.amazon.com/about-aws/whats-new/2017/01/amazon-dynamodb-now-supports-cost-allocation-tags

It'd be great if Terraform could add support for tags on DynamoDB resources too!

Thanks,

Greg

**Comment by kevellisaviva** [comment]
Thanks @gpetras , I was just about to raise the same thing!

Kev
