### ISSUE TITLE
RDS Changing final_snapshot_identifier causes the database to be destroyed

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/terraform#1138]
Changing the value of `final_snapshot_identifier` (which is only used internally when deleting a DB) causes the DB to be destroyed (the irony... it hurts).

**Comment by phinze** [comment]
Thanks for this report.

It's true that `final_snapshot_identifier` is currently marked incorrectly as `ForceNew`, since it's only a parameter of the delete call. Marking as an AWS provider bug and we'll get it fixed.
