### ISSUE TITLE
Cant seem to use ConflictsWith on a nested structure (NS1 provider)

### ISSUE THREAD

**Issue by pashap** [hashicorp/terraform#11387]
### Terraform Version

Terraform v0.8.5-dev

### Affected Resource(s)
- ns1_record

### Terraform Configuration Files
@cakoose put together a great acctest case with explanation on this forked commit: https://github.com/cakoose/terraform/commit/457178ebf2d4095120af9e0c55656fed9aa4384a

I cant put it any better than how @cakoose laid out the problem, maybe we can continue the conversation in this issue with that commit and its comment as reference.

From @cakoose comment:

> ## The issues we're facing with nested structs while trying to write the Terraform NS1 plugin.

> When defining the NS1 "record" resource, we want to use nested structs. We want to do this because NS1 records have nested "meta" structs in a few places.

> However, it looks like we can't directly define nested structures in a Terraform schema. @pashap mentioned a hack that involved creating a nested list, then put the structure in that list. That works to some extent, but we still run into some issues. The code in this commit sets up a small example that demonstrates the issues

> First, import the resource (you don't need a real API key for this):

> `$ NS1_APIKEY=x terraform import ns1_trial.blah blah`
> After import, terraform.tfstate will look like this:

```
            "resources": {
                "ns1_trial.blah": {
                    "type": "ns1_trial",
                    "depends_on": [],
                    "primary": {
                        "id": "blah",
                        "attributes": {
                            "a": "aaa",
                            "first.#": "1",
                            "first.0.x": "xxx",
                            "first.0.y": "",
                            "id": "blah",
                            "second.#": "1",
                            "second.0.x": "",
                            "second.0.y": "yyy"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                }
            },
```
> ISSUE 1: Because the read function doesn't return the top-level field b, it is not present in the state, which seems correct. However, the read function also doesn't return first.y or second.x, but those are present in the state as empty strings, which seems problematic.

> Next, create config.tf with the contents:

```
resource "ns1_trial" "blah" {
    a = "aaa"
    first {
        x = "xxx"
    }
    second {
        y = "yyy"
    }
}
```

> terraform plan behaves as expected:

> `$ NS1_APIKEY=x terraform plan -refresh=false`
No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.
ISSUE 2: Our ConflictsWith declarations don't seem to work with nested structs.

> If I add the top-level field b to config.tf, I correctly get an error:

> $ NS1_APIKEY=x terraform plan -refresh=false
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

> Errors:

>  * ns1_trial.blah: "a": conflicts with b ("b")
>  * ns1_trial.blah: "b": conflicts with a ("aaa")
However, if I remove that and add first.y instead, I'd expect it to conflict with first.x but I get no error:

> `$ NS1_APIKEY=x terraform plan -refresh=false`

```
...
~ ns1_trial.blah
    first.0.y: "" => "y"
...
Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by mitchellh** [comment]
This is correct, dup here! #11101

**Comment by pashap** [comment]
Ahhh, thanks @mitchellh
