### ISSUE TITLE
aws_api_gateway_method_response Concurrency

### ISSUE THREAD

**Issue by steve-gray** [hashicorp/terraform#11395]
When creating multiple method response codes that live beneath the same method, Terraform will typically fail due to concurrency/conflict errors on the AWS side. It appears that AWS (whilst not documented anywhere visible) is treating the api_gateway_method as the concurrency boundary.

### Terraform Version
0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_api_gateway_method_response

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
Multiple response codes should be created correctly for an API response

### Actual Behavior
Fails with error such as

````
 aws_api_gateway_method_response.dummy_function_response1: Error creating API Gateway Method Response: ConflictException: Response already exists for this resource
	status code: 409, request id: 56acda62-e292-11e6-b56a-85b5b33b47bd
* aws_api_gateway_method_response.dummy_function_response3: Error creating API Gateway Method Response: ConflictException: Response already exists for this resource
	status code: 409, request id: 56ae3a9c-e292-11e6-8218-a9497181c142
* aws_api_gateway_method_response.http409: ConflictException: Unable to complete operation due to concurrent modification. Please try again later.
	status code: 409, request id: 56acb348-e292-11e6-8d8e-77f3e0ae3f54
* aws_api_gateway_method_response.http401: ConflictException: Unable to complete operation due to concurrent modification. Please try again later.
	status code: 409, request id: 56ac6527-e292-11e6-8d8e-77f3e0ae3f54
* aws_api_gateway_method_response.dummy_function_response2: Error creating API Gateway Method Response: ConflictException: Unable to complete operation due to concurrent modification. Please try again later.
	status code: 409, request id: 56ac65c5-e292-11e6-99f9-efaae93431b6
````

### Steps to Reproduce
terraform apply where you have an API gateway operation with multiple (2+) HTTP response codes defined which are new and require creating. Subsequent attempts *may* work as individual responses get created, but will require many retries before the race conditions are not encountered.

**Comment by sebolabs** [comment]
`terraform 0.8.7`
I encountered the problem with `ConflictException: Unable to complete operation due to concurrent modification.` today, two occurrences in 5 minutes and after that it disappeared.
To be safe in the future I just added dependencies on those responses so that they are being created one by one. Hopefully it will help.

**Comment by gustavlasko** [comment]
Using terraform 0.9.4, I get the same issue. I attempted to use @sebolabs' workaround, but it seems that I still get the same error, so it appears that terraform doesn't always honor the depends_on.

**Comment by skehlet** [comment]
I made each method depend on the one before it, and that seemed to get me past the ConflictExceptions. 😕
