### ISSUE TITLE
Rancher orchestration type always cattle

### ISSUE THREAD

**Issue by justicel** [hashicorp/terraform#11392]
### Terraform Version

0.8.4

### Affected Resource(s)

rancher_environment

### Terraform Configuration Files
```hcl
resource "rancher_environment" "default" {
  name = "testing"
  description = "Testing Environment"
  orchestration = "kubernetes"
}
```

### Expected Behavior
Terraform should create a rancher environment with Kubernetes orchestration

### Actual Behavior
Terraform created a rancher environment with Cattle orchestration

### Steps to Reproduce
1. Install a rancher environment with rancher 1.3.0 or above
2. `terraform apply`

**Comment by johnrengelman** [comment]
I'm guessing this changed now with the way that orchestration is deployed in rancher environments (change in v1.2 of Rancher). 
I'll try and take a look at this soon.

**Comment by nextrevision** [comment]
See https://github.com/rancher/rancher/issues/7094

**Comment by jmalouf69** [comment]
Rancher tells me this occurs because of lack of support for their API v2. Any updates on this bug or support for the Rancher v2 API in general?

**Comment by tombmurphy** [comment]
This pretty much makes it impossible to manage Rancher Kubernetes in Terraform. Even if you import kubernetes environments created manually, terraform cannot match up with the resources defined. 
Does anyone know of any workarounds ?

**Comment by aemneina** [comment]
The PR here looks to address modern versions of rancher compatibility https://github.com/hashicorp/terraform/pull/13908
