### ISSUE TITLE
datadog: Add support for `new_host_delay` in the `datadog_monitor` resource

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#11397]
### Terraform Version

0.8.4

### Affected Resource(s)

- `datadog_monitor`

### Use case

Support the recently added `new_host_delay` attribute of monitors to have them ignore new hosts for a configurable time period (defaulting to 300s). Would allow configuration such as:

```hcl
resource "datadog_monitor" "foo" {
  name = "Name for monitor foo"
  type = "metric alert"
  message = "Monitor triggered. Notify: @hipchat-channel"
 
  // NEW
  new_host_delay = 600
}
```

Started to implement this before I realized the library being used needs to be updated first so opened https://github.com/zorkian/go-datadog-api/pull/82 instead which will need to be merged first so mostly opening this as a tracking issue. Happy to take care of this when support is added to the library.

**Comment by ojongerius** [comment]
🎉

**Comment by ojongerius** [comment]
Upstream is ready https://github.com/zorkian/go-datadog-api/commit/b4db85d36942d6ddf4bceb1ecf59093c84548f7f
