### ISSUE TITLE
Setup Aurora RDS cross-region read replica

### ISSUE THREAD

**Issue by susiklee** [hashicorp/terraform#11401]
We are trying to set up cross region read replica for Aurora MySQL RDS cluster via Terraform v0.7.9. Following the AWS docs, I'm specifying the ARN of Aurora Cluster.   However, when i try to use aws_rds_cluster ARN in the terraform, its giving "does not have attribute 'arn' for variable" error.  If I specify the ARN in cluster_identifier, it gives "Invalid database cluster identifier" error.  

```

resource "aws_rds_cluster_instance" "default" {
   count                        = "${var.vcdb_count}"
   identifier                   = "${aws_rds_cluster.default.id}-dr${count.index}"
  cluster_identifier           = "${aws_rds_cluster.default.arn}"
  instance_class               = "${var.vcdb_instance_class_dr}"
  db_subnet_group_name         = "${module.networks.rds_subnet_group}"
  apply_immediately            = "${var.vcdb_apply_immediately}"
  db_parameter_group_name      = "${aws_db_parameter_group.default.name}"
}

```

Since I can create the cross region read replica for Aurora via AWS web console, this could be a bug or terraform does not support cross region read replica for the Aurora Cluster. 

What will be the process to have terraform support cross region read replica for the Aurora Cluster?

**Comment by stack72** [comment]
Closed via #11428
