### ISSUE TITLE
Changing the value of the parameter_group_name in aws_db_instance causes the RDS instance to be destroyed and recreated

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/terraform#1140]
parameter_group_name should be a value that can be changed without destroying the database.

**Comment by phinze** [comment]
Yup totally. I think the first pass of the RDS resource just implemented the `CreateDBInstance`, `DescribeDBInstance`, and `DeleteDBInstance` API actions and marked all the parameters as `ForceNew`. 

That was a good start, but  ow we need to circle around and catch the attributes that can be updated with `ModifyDB*`.

The relevant API endpoint for this issue will be http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBParameterGroup.html

**Comment by catsby** [comment]
Fixed in #1341
