### ISSUE TITLE
data.aws_ami name field cannot be set

### ISSUE THREAD

**Issue by chadgrant** [hashicorp/terraform#11417]
### Terraform Version
0.8.4

### Affected Resource(s)
Please list the resources as a list, for example:
- data aws_ami

### Terraform Configuration Files
```hcl
data "aws_ami" "openvpn" {
  most_recent = "true"
  name = "OpenVPN Access Server"
}
```

### Debug Output
2017/01/25 20:03:36 [ERROR] root.openvpn: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: ["name": this field cannot be set]
2017/01/25 20:03:36 [ERROR] root.openvpn: eval: *terraform.EvalSequence, err: Warnings: []. Errors: ["name": this field cannot be set]
2017/01/25 20:03:36 [ERROR] root.openvpn: eval: *terraform.EvalOpFilter, err: Warnings: []. Errors: ["name": this field cannot be set]
2017/01/25 20:03:36 [ERROR] root.openvpn: eval: *terraform.EvalSequence, err: Warnings: []. Errors: ["name": this field cannot be set]
2017/01/25 20:03:36 [TRACE] [walkValidate] Exiting eval tree: data.aws_ami.openvpn
late

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should look up the ami based on Regex

### Actual Behavior
Errors:

  * data.aws_ami.openvpn: "name": this field cannot be set

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
It's inside a module

**Comment by chadgrant** [comment]
Looks like the docs aren't updated and this resource has changed name to name_regex with this commit: https://github.com/hashicorp/terraform/commit/bf68590f02252be225e5d4e9dec951f92a066e49

**Comment by stack72** [comment]
Hi @chadgrant 

So, the name parameter has actually always been a computed value. That means, that after we filter the selection down to a single value, we set that value to Terraform state. I use this data_source a lot and use it as follows:

```
data "aws_ami" "ecs_ami" {
  most_recent = true
  filter {
    name = "name"
    values = ["ecs-*"]
  }
}
```

As you can see, I build a selection criteria for the AMI via a set of filters. 

Hope this helps

Paul

**Comment by chadgrant** [comment]
It used to work fine with just name, now it's very slow (but works) ... with name_regex
