### ISSUE TITLE
aws_autoscaling_group resource doesn't notice deleted load_balancer attribute

### ISSUE THREAD

**Issue by kbruner** [hashicorp/terraform#11422]
Terraform version: 0.8.4

If I have an `aws_autoscaling_group` that was created with something like this:

```
resource "aws_autoscaling_group" "example-asg" {
  name = "example-asg"
  vpc_zone_identifier = ["subnet-000000", "subnet-000001"]
  lifecycle {
    prevent_destroy = true      // Protect resource from destruction
  }
  max_size = "2"
  min_size = "1"                                                                  
  launch_configuration = "${aws_launch_configuration.example-lc.name}"
  load_balancers = ["example-elb"]
  protect_from_scale_in = true
}
```

and then delete the `load_balancers` line, terraform does not pick up the change ever in subsequent `plan` and `apply` calls.  I had to detach the load balancer manually (with the CLI) and after `terraform refresh`, the `load_balancers` count in the tfstate file dropped to 0.

**Comment by frncmx** [comment]
holds true also for `v0.9.2`
