### ISSUE TITLE
Multiple regions fails on aws provider

### ISSUE THREAD

**Issue by outrunthewolf** [hashicorp/terraform#1142]
I'm using modules to create servers across multiple regions.

the AWS provider requires a region, and for some reason when the module parses the available AMI's across the different regions it fails because one of the AMI's doesn't exist in the other region.

Would love some advice for a fix

**Comment by jwestboston** [comment]
I'm having issues with this too.  In fact, I cant use any modules that have an AWS provider.

terraform plan always fails with:

  * provider.aws: region: required field is not set

even though it is definitely set.  Has the issue even if I hardcode the region within the module itself.

I suspect terraform is having issues with modules, when the module defines the provider.

**Comment by mitchellh** [comment]
Fixed by #1282

**Comment by outrunthewolf** [comment]
You're a :star:
