### ISSUE TITLE
 Resource 'x' not found for 'variable x.1.id' with new graph, works fine with legacy graph

### ISSUE THREAD

**Issue by dlcc** [hashicorp/terraform#11437]
Hi,

I have a problem with the new graphing algorithm...
The pertinent line in script is `terraform $1 $3 -state=./xxx`

ELSOXFM-213560:infrastructure murrayi$ terraform -v
Terraform v0.8.5

ELSOXFM-213560:infrastructure murrayi$ ./tf.sh plan dev
Get: file:///Users/murrayi/regionalmagento/pos-infrastructure/infrastructure/modules/elb
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

Error running plan: 1 error(s) occurred:

* Resource 'aws_subnet.public' not found for variable 'aws_subnet.public.1.id'
using TF state file pos-iodev-ireland-dev.tfstate
settings used in pos plan --> account [iodev] region [ireland] (eu-west-1) to the dev environment using key id [] and key [].
Time taken: 00:00:06

ELSOXFM-213560:infrastructure murrayi$ ./tf.sh plan dev -Xlegacy-graph
Get: file:///Users/murrayi/regionalmagento/pos-infrastructure/infrastructure/modules/elb
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_autoscaling_group.app
...

Plan: 57 to add, 0 to change, 0 to destroy.
using TF state file pos-iodev-ireland-dev.tfstate
settings used in pos plan --> account [iodev] region [ireland] (eu-west-1) to the dev environment using key id [] and key [].
Time taken: 00:00:06
ELSOXFM-213560:infrastructure murrayi$

**Comment by mitchellh** [comment]
Is this still happening? The timeframe for your issue was around the same time a lot of these popped up (with both graphs) due to an AWS issue. Terraform wasn't able to "catch" the issue because the AWS API was still responding with 200s (albeit empty ones) and the SDK didn't report an error.

This was an intermittent issue so some applies worked, some failed.

If this is still happening please do open a new issue though.
