### ISSUE TITLE
Module directories ending with "tgz" fail when running terraform get

### ISSUE THREAD

**Issue by philippevk** [hashicorp/terraform#11438]
This is a bug report. Steps to reproduce:

- create a module directory with the name "dir-to-tgz"
- add any .tf file to the module
- reference module in your main terraform file
- run ` terraform get `

Result:
- Error loading Terraform: Error downloading modules: source path must be a file

What is happening:
- I'm guessing terraform supports modules compressed to .tgz files
- I'm guessing terraform checks if source ends with "tgz" to determine this

Possible fix:
check for ".tgz" instead of "tgz" ?

**Comment by philippevk** [comment]
FYI, the obvious workaround is to rename module, but it still seems like a bug

**Comment by mattlqx** [comment]
As a practical exercise, I poked around and found the code to be here:
https://github.com/hashicorp/go-getter/blob/21d247ece01f1f7d5b56f130fd7b1db19bb0d0db/client.go#L156

And the map is here:
https://github.com/hashicorp/go-getter/blob/2fbd997432e72fe36060c8f07ec1eaf98d098177/decompress.go#L21-L27

So yep, only checking for ext at the end and not .ext.

**Comment by mitchellh** [comment]
Good bug. You can also force a specific getter type with a `type::` prefix on the source address. So you can do `file::` to force it as a file/directory. Bug going to keep this open to address the not looking for a "."

**Comment by mitchellh** [comment]
Fix is queued up in PR.
