### ISSUE TITLE
request: aws_iam_policy_document pre-flight checks

### ISSUE THREAD

**Issue by therealbill** [hashicorp/terraform#11444]
# Affected Resource(s)
- aws_iam_policy_document

AWS has a hard limit on the size in characters of a policy document (the JSON it uses) of 2048 bytes. Trying to add a policy larger than that will result in an error on apply. 
# Current Behavior
The plan "works", the apply will fail.

# Desired Behavior
I would rather see the plan indicate the policy it is going to write is too large so it can be caught in that stage

In this case, terraform knows the size of the JSON document it just created and will attempt to upload, so I think it reasonable for it to check since it does not need info from the provider (this is one of the hard limits, you can't get them to raise it for you).

Also, the value of "sid" can only be alphanumeric, so I'd like to see the plan report an error if non-alphanumeric characters are in it. Less important then the policy size, of course.

**Comment by apparentlymart** [comment]
Hi @therealbill! Thanks for opening this issue.

Do you know if is 2048 a global limit for IAM policies across all AWS services, or if this limit varies from one service to another?

We've seen that in a handful of cases each AWS service interprets IAM policies slightly differently, but if this limit is documented as being true globally then we can check it pretty easily from the `aws_iam_policy_document` data source as you suggested. If it varies from one service to another then we might end up needing to do this on a per-resource basis to capture the differing limits.

**Comment by therealbill** [comment]
Good day, @apparentlymart! 

The limit on inline policy size is in this case specific to where the policy is "inlined", but it is consistent and strictly on the IAM piece, regardless of what service(s) the policy is policing.

For policies attached to users the limit is 2048 characters. When inlined to a group it is 5120, and when inlined to a role 10240 characters. Now that I think about it it does, unfortunately, add a bit more complexity in that you'd have to evaluate them in that context to get all of them correctly checked. This would need to be done in the code for aws_iam_user_policy, aws_iam_group_policy, and aws_iam_role_policy rather than at the policy_document level. I hadn't thought about that.

The details on the limits are at the bottom of http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html

I also see there that _managed_ policies have a 5120 character limit. Fortunately, it appears relatively easy to know if you're dealing with a managed policy because it will have the "version" element. Further, managed policies are apparently all set to 5120 so for managed policies you could raise an error if there is a version element and the size exceed 5120c.
