### ISSUE TITLE
aws_autoscaling_group in deposed state, but shouldn't be

### ISSUE THREAD

**Issue by spy-tech** [hashicorp/terraform#11459]
The following applies to Terraform v0.8.5-dev (cb4ffd466222a2bc6839ce5989a73a63ed911202+CHANGES)

My understanding of "deposed" is that it's a resource which will be deleted if one does a subsequent `terraform apply`, which would be a huge problem. 

In the terraform.tfstate file, I see the autoscaling group with a particular ID with the deposed state: 
```
                    "deposed": [
                        {
                            "id": "ecs-asg-prod-ecs-prod-00ad9b82fc2aaba998ca643aae",
                            "attributes": {
                                "availability_zones.#": "0",
                                "desired_capacity": "2",
                                "force_delete": "false",
                                "health_check_grace_period": "300",
                                "id": "ecs-asg-prod-ecs-prod-00ad9b82fc2aaba998ca643aae",
                                "launch_configuration": "ecs-prod-00ad9b82fc2aaba998ca643aae",
                                "load_balancers.#": "0",
                                "max_size": "10",
                                "metrics_granularity": "1Minute",
                                "min_size": "1",
                                "name": "ecs-asg-prod-ecs-prod-00ad9b82fc2aaba998ca643aae",
                                "protect_from_scale_in": "false",
                                "target_group_arns.#": "1",
                                <snip>
                                "wait_for_capacity_timeout": "10m",
                                "wait_for_elb_capacity": "1"
                            },
```

If I compare the id with the one that should remain in the AWS Console, I see that they match, so it shouldn't be deleted. 

Relevant: #10753

**Comment by mitchellh** [comment]
See #10753 for more details on what deposed means.

Deposed only happens if you attempted a create before destroy apply earlier (that's how it shifts to "deposed"). Further, if a CBD resource depends on that ASG, it'll automatically make that resource CBD and cause deposition. 

As #10753 states correctly though: we need to do a way better job documenting this! Sorry!

**Comment by spy-tech** [comment]
@mitchellh Thanks for your reply and my apologies for what appears to all be the same issue. I know that I want to keep the machines associated with the ASG id above. Will the ASG and thus the associated machines be deleted or not when I would run `terraform apply` or not?

If the answer is "yes", how can I get a tfstate file which does meet my expectations, which is that everything is fine and nothing needs to happen?

**Comment by mitchellh** [comment]
If it is deposed then the ASG and associated machines likely will. 

You can move the "deposed" instance into the "primary" slot in the state. The `terraform state` commands currently don't have any way to target a deposed resource so you'd have to do this manually.

This is a strange state to get in though and one I haven't experienced before [in the community]. It'd help to understand how this happened and maybe we can build guardrails to prevent this in the future.

**Comment by mitchellh** [comment]
Note if you back up your state file and never run `terraform apply` (or destroy), no other Terraform command will actually make changes to your infra so you can safely run `plan` for example.

**Comment by spy-tech** [comment]
@mitchellh Create an ASG with a health check which fails, then it times out after 10 minutes and you get into this state. That's the only weird thing I did, at least.

**Comment by mitchellh** [comment]
Yes, that makes sense: if you have create before destroy, and the new creation fails, your old one is "deposed" (cause it was going to be destroyed anyways due to CBD) .You can see that from the explanation in #10753. That is the correct behavior for CBD.

"Deposed" is just a state that instances go between the create and destroy.

**Comment by spy-tech** [comment]
@mitchellh I don't want this resource to be destroyed and I would like it to work like Terraform expects it to work, but I am confused at this moment. Will something else be created first, before this is destroyed? It's really not clear what Terraform's plan is supposed to communicate to me in this case. Before 0.8 there was no such communication problem.

**Comment by mitchellh** [comment]
Yes, if CBD is set, a new ASG is created first, Terraform [by default] will wait for instances to populate that ASG, and then the old one will be destroyed. 

Note that even if you don't set CBD on the ASG, if any dependent (child) resource depends on the ASG has CBD and requires CBD, the ASG will "inherit" the CBD. Its hard to explain why that is necesasry, but if you manually sketch out how to do a CBD safely you'll see that that is necessary.

**Comment by spy-tech** [comment]
@mitchellh In this case there is the difficulty that I run ECS containers which are supposed to first scale up (with the new machines created by the ASG), but currently no new ECS containers are being launched, because the desired (not the maximum number) has already been deployed. This creates a "no progress"-situation. Do you have any suggestion how to get around this?

**Comment by artburkart** [comment]
I think one use case to consider:
1. apply an asg with a health check that succeeds
2. apply a new asg with instances whose health checks will fail
3. delete the new lingering asg manually
4. try deploying again, except with the original asg (as an attempt to clear the deposed state through an apply)
5. Watch it create the new asg successfully, then immediately delete it and tell you the `apply` was a success

**Comment by tamsky** [comment]
I'd offer that a manual action you've stated across a few different bugs [*] is the root cause of the undesired behavior you're observing:

In https://github.com/hashicorp/terraform/issues/11459#issuecomment-339811984
you wrote:
> I think one use case to consider:
> ...
> 3. delete the new lingering asg manually

Summary of the references below:
  Don't do stuff to the ASG, instead do stuff to the Launch Config.

* References:
- https://github.com/terraform-providers/terraform-provider-aws/issues/2438#issuecomment-426391266
- https://github.com/terraform-providers/terraform-provider-aws/issues/309#issuecomment-426410368
