### ISSUE TITLE
VMware - Vcloud Air/ Vcloud Director: error: "* Something went wrong: error finding LoginUrl: error parsing error body for non-200 request: EOF"

### ISSUE THREAD

**Issue by EllisFisher1994** [hashicorp/terraform#11455]
getting the error * Something went wrong: error finding LoginUrl: error parsing error body for non-200 request: EOF

Have variables in a separate file.
`# Configure the VMware vCloud Director Provider
provider "vcd" {
    user                 = "${var.vcd_user}"
    password             = "${var.vcd_pass}"
    org                  = "${var.vcd_org}"
    url                  = "${var.vcd_url}"
    vdc                  = "${var.vcd_vdc}"
}

resource "vcd_vapp" "web" {
    name          = "web"
    catalog_name  = "Test-Catalog"
    template_name = "lampstack-1.10.1-ubuntu-10.04"
    memory        = 2048
    cpus          = 1

    network_name  = "testing_network"

    ip            = "10.10.104.160"

    metadata {
        role    = "web"
        env     = "staging"
        version = "v1"
    }

}
`

Can anyone help?

**Comment by robcoward** [comment]
Check that ${var.vcd_url} is correct. It needs to have /api appended to the hostname in order for the underlying library code to construct the correct authentication request.

**Comment by robcoward** [comment]
@EllisFisher1994 how did you get on ? Are you still having an issue connecting to your vCloud API?

**Comment by srinarayanant** [comment]
what is the resolution for this issue , I am facing the same with vcd 8.2

**Comment by MartyFox** [comment]
During a quick test, I appended /api and Terraform attempted to process but could not connect, is the /api a requirement within Terraform?

Not all cloud providers use the /api domain suffix, I currently work with one who uses an "https://api.<domain>".com URL.

Using Terraform v0.10.2

**Comment by islamhamidul** [comment]
I am having the same issue. What will be resolution?

Thanks

**Comment by kumar5393** [comment]
On Terraform v0.7.3, following is the main.tf config.

still getting error * Something went wrong: error authorizing: error parsing error body for non-200 request: EOF

provider "vcd" {

    user                 = "xxxx"
    password             = "xxxx"
    url                  = "https://........./api"
    allow_unverified_ssl = "true"
}

resource "vcd_vapp" "sampletest" {

    name          = "sampletest"
    catalog_name  = "Templates"
    template_name = "xxxxx"
    network_name  = "xxxx"
}

can someone help ?

**Comment by spengilley** [comment]
I'm getting the same error as the original poster. The url that I need to use is https://api.foo.bar so appending /api isn't an option
