### ISSUE TITLE
Add support for git tags/branches in module sources

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1145]
It's only possible to always use `master` / `HEAD` of each module repository

```ruby
module "consul" {
    source = "github.com/hashicorp/consul/terraform/aws"
    servers = 3
}
```

which makes it:

 - hard to make any reproducible build
 - security hazard - imagine I'm using `tf_aws_sg` and accidentally upgrade to a version that exposes some ports to `0.0.0.0/0` for example

**Comment by mitchellh** [comment]
Sounds good to me. We already thought this through and it wouldn't be too hard to add. Here is how it would look:

**Note: Doesn't work yet! Just notes for implementation.**

```
module "consul" {
    source = "github.com/hashicorp/consul/terraform/aws?branch=foo"
    servers = 3
}
```

**Comment by radeksimko** [comment]
That's not bad, I was thinking about something like this:

```ruby
module "consul" {
    source = "github.com/hashicorp/consul/terraform/aws"
    branch = "foo"
    servers = 3
}
```
but maybe that's too verbose?

Generally the inspiration to me here was Bundler's `Gemfile`:
```
:git => 'https://github.com/rails/rails.git', :ref => '4aded'
:git => 'https://github.com/rails/rails.git', :branch => '2-3-stable'
:git => 'https://github.com/rails/rails.git', :tag => 'v2.3.5'
```

Go does not support anything naturally and probably won't be in the nearest future from what I've seen in the mailing list.

**Comment by mitchellh** [comment]
@radeksimko Yeah, we didn't design it that way because it conflates itself with the parameters to the module itself. We want the URL to be a single source of information.

**Comment by radeksimko** [comment]
I see, that makes sense to me then.

**Comment by ketzacoatl** [comment]
+1

**Comment by frankscholten** [comment]
+1

**Comment by radeksimko** [comment]
As @clstokes pointed out in #1439, there's a solution for this:
https://terraform.io/docs/modules/sources.html#ref

I just wonder why @mitchellh didn't point me there and more importantly why I didn't notice that bit in documentation...

Any reason why keep this open then?

**Comment by mitchellh** [comment]
For some reason I thought I didn't implement it yet, I knew I had PLANNED for it. 

_Well then_.

Thanks :)

**Comment by clstokes** [comment]
@radeksimko @mitchellh I think there's a bug in the branch/ref implementation FYI - https://github.com/hashicorp/terraform/issues/1568.
