### ISSUE TITLE
aws_alb_target_group_attachment enable the ability to provide an asg as a target

### ISSUE THREAD

**Issue by owenmorgan** [hashicorp/terraform#11457]
Hello, can you please prove support to specify a an ASG ID as a target_id for an aws_alb_target_group_attachment?

Thanks

**Comment by cannontrodder** [comment]
The docs suggest supplying a 'container ID', Is this not something we can query from within Terraform?

**Comment by stack72** [comment]
Hi Friends

We actually implemented this the other way around - provide an alb_target_group_arn to the autoscaling group

https://www.terraform.io/docs/providers/aws/r/autoscaling_attachment.html

Will this suffice?

Paul

**Comment by stack72** [comment]
Going to close this for now - if you feel this needs to change, then please do recomment on the issue

Paul
