### ISSUE TITLE
Terraform doesn't know what it does

### ISSUE THREAD

**Issue by spy-tech** [hashicorp/terraform#11456]
`Terraform v0.8.5-dev (cb4ffd466222a2bc6839ce5989a73a63ed911202+CHANGES)`  returns the following:

with the following relevant configuration:

```
resource "aws_autoscaling_group" "ecs" {
 lifecycle {
      create_before_destroy = true
 }
  name = "ecs-asg-prod-${aws_launch_configuration.ecs.name}"
  wait_for_elb_capacity = "1"
  vpc_zone_identifier =  ["${aws_subnet.private.*.id}"]
  launch_configuration = "${aws_launch_configuration.ecs.name}"
  min_size             = 1
  max_size             = 10
  desired_capacity     = "${var.ecs_desired_capacity}"
  target_group_arns = ["${aws_alb_target_group.collector.arn}"]

  depends_on = ["aws_vpc.my", "aws_launch_configuration.ecs"]
}

resource "aws_launch_configuration" "ecs" {
 lifecycle {
      create_before_destroy = true
 }
  name_prefix = "ecs-prod-"
  image_id             = "ami-e3fbd290" 
  instance_type        = "t2.small"
  key_name             = "mykey-prod"
  ebs_optimized = false
  root_block_device = {
    volume_type = "standard"
    volume_size = 8 
    delete_on_termination = true
  }

  # this overrides the docker configuration
  ebs_block_device{
    device_name="/dev/xvdcz"
    volume_type = "standard"
    volume_size = 22 
    delete_on_termination = true
    encrypted = false
  }

  security_groups      = ["${aws_security_group.ecs_node.id}"]
  iam_instance_profile = "${aws_iam_instance_profile.ecsInstanceRole.arn}"
  user_data            = <elided>
```

returns:

```
Error applying plan:

1 error(s) occurred:

* aws_autoscaling_group.ecs: Error creating AutoScaling Group: AlreadyExists: AutoScalingGroup by this name already exists - A group with the name ecs-asg-prod-ecs-prod-00ad9b82fc2aaba998ca643aae already exists
        status code: 400, request id: <id>
```

However, all resources created in this account are created via Terraform, and also with the same tfstate file. As such, Terraform seems to be suffering from memory loss. I.e., it doesn't know what resources it has created. 

This makes deployments extremely fragile and almost nullifies the added value of Terraform.

**Comment by mitchellh** [comment]
This is probably due to "create before destroy" being set. It is attempting to create an ASG that already exists just because the name matches. If you're convinced it is doing the wrong thing though, please follow up with a debug log (`TF_LOG=debug`) of both the plan and apply and we'll take a look!

Note that ASGs are notorious for having this error pop up with CBD set, so this isn't something unusual to see.

**Comment by mitchellh** [comment]
Closing due to lack of response. If you do figure this out please open a new issue with the above information. Thanks!
