### ISSUE TITLE
Error in executing the script

### ISSUE THREAD

**Issue by BalajiVM** [hashicorp/terraform#11468]
Hi,

I am trying to map the list private ip address to the list of servers, i am getting the below errors.

Errors:

  * 1:3: element: expected 2 arguments, got 1 in:

${element(split(",", lookup(var.private_ip_list,var.name_list)))}
  * 1:3: element: expected 2 arguments, got 1 in:

${element(split(",", lookup(var.private_ip_list,var.name_list)))}
  * 1:3: element: expected 2 arguments, got 1 in:

${element(split(",", lookup(var.private_ip_list,var.name_list)))}
  * 1:3: element: expected 2 arguments, got 1 in:

${element(split(",", lookup(var.private_ip_list,var.name_list)))}

Please find the code below
###code in instance resource:

resource "aws_instance" "instance" {
              -------
              private_ip = "${element(split(",", lookup(var.private_ip_list, var.tag)), count.index)}" 
              ----
}

###code in variable.tf file:

variable "private_ip_list" { default {}}
variable "tag" {description = "This is name of the server list"}

###code in terraform.tfvars

tag = "list"
name_list = {list = "server1,server2,server3,server4"}
private_ip_list= {list = "172.30.10.5,172.30.10.6,172.30.10.7,172.30.10.9"}

please do the needful.

Regards,
Balaji

**Comment by mitchellh** [comment]
Your element function call only has 1 argument, it expects 2.

**Comment by BalajiVM** [comment]
Is it possible to pass private ip adress as type:map

**Comment by mitchellh** [comment]
No it has to be a string, you'd have to reference into the map. 

Please ask usage questions on the mailing list or chat. Issues should remain bugs or enhancement requests. Thanks!
