### ISSUE TITLE
Removing resources causes a cycle 0.8.5

### ISSUE THREAD

**Issue by tecnobrat** [hashicorp/terraform#11469]
This is on terraform 0.8.5.

My plan returns:
`* Cycle: aws_iam_role.services (orphan), aws_iam_role_policy.services (orphan)`

This change is pretty simple, I'm removing two resources `aws_iam_role.services` and `aws_iam_role_policy.services`.  There is no other references to these resources in the entire repository.

Here is the change diff I'm trying to run a plan on.
![image](https://cloud.githubusercontent.com/assets/145406/22382502/c89e097a-e47a-11e6-80de-511b604d4ccf.png)

**Comment by mitchellh** [comment]
Hey there, do you mind grabbing a debug graph for me? That should give me the answers I need on how this is coming about: `TF_LOG=debug`. You may have to scrub for secrets, or feel free to email it to me if you want and I won't share it publicly.

**Comment by mitchellh** [comment]
Closing due to lack of response. If you do figure this out please open a new issue with the above information. Thanks!

**Comment by tecnobrat** [comment]
@mitchellh I've sent you an email, as the log is much too long to post to the github issue, and I didn't see any secrets, but you can never be too careful :)
