### ISSUE TITLE
Support count in load_balancer block for AWS ECS Service

### ISSUE THREAD

**Issue by bchen421** [hashicorp/terraform#11463]
Hi there,

Just a simple feature request, but we would like to try using conditionals to create aws ecs services.  Perhaps a count parameter or allowing us some other mechanism would be helpful.  With ELB's this is possible due to having an attachment resource which takes count, but since services are immutable, this doesn't seem possible since there is no way to attach an ALB after service creation.

**Comment by apparentlymart** [comment]
Hi @bchen421! Sorry for the long silence here.

This is a similar request as in #7034, which is now closed because there's a new feature for this coming in the forthcoming v0.12.0 release. See my comment over there for details!
