### ISSUE TITLE
aws_vpc_endpoint continuously updated

### ISSUE THREAD

**Issue by mcraig88** [hashicorp/terraform#11479]
### Terraform Version
Terraform v0.8.2

### Affected Resource(s)
aws_vpc_endpoint 

### Terraform Configuration Files
```hcl

resource "aws_vpc_endpoint" "vpc-s3-endpoint-prod" {
  vpc_id          = "${aws_vpc.main.id}"
  service_name    = "com.amazonaws.${var.region}.s3"
  route_table_ids = ["${aws_route_table.private-cust.*.id}", "${aws_route_table.public.id}", "${aws_route_table.idx-cust.*.id}"]
  count           = "${var.zone == "Secure" ? 1 : 0}"
  
  policy = <<EOF
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
          "Service": "s3.amazonaws.com"
        },
            "Action": [
                "s3:ListBucket",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::tools-production/release",
                "arn:aws:s3:::tools-production/release/*",
                "arn:aws:s3:::tools-production/resources",
                "arn:aws:s3:::tools-production/resources/*"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "s3.amazonaws.com"
        },
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::com.tools.deliverables",
                "arn:aws:s3:::com.tools.deliverables/*"
            ]
        }
    ]
}
EOF
}
```

### Expected Behavior
vpc endpoint should not be modified with every terraform apply action

### Actual Behavior
vpc endpoint is modified with every apply action. 
I also tried to add an ignore_chages = ["*"], and this did not resolve issue.
I also tried with and without the count parameter, same result.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

### References
Could not find other issues similar

**Comment by llavaud** [comment]
it is not because the policy is reformated by amazon and is no longer corresponding ?

you can try with an "aws_iam_policy_document" data sources

**Comment by lapthorn** [comment]
@llavaud Using an aws_iam_policy_document does work and stops the annoying:

``` terraform
~ aws_vpc_endpoint.s3_endpoint
    policy: ...
```

even when the policy hasn't changed.  I'd be intrigued to know why.

Tested with terraform 0.9.6
