### ISSUE TITLE
Cannot set esxi host for VM deployment

### ISSUE THREAD

**Issue by smenon78** [hashicorp/terraform#11473]
### Terraform Version
Terraform v0.6.16

### Affected Resource(s)
Please list the resources as a list, for example:
- vsphere_virtual_machine

Trying to create a VM in a specific esxi host. I see a Cluster option available. The cluster has multiple esxi hosts and I want to specify which esxi host to deploy the VM.

**Comment by smenon78** [comment]
Any resolution or workaround for this?

**Comment by robdaemon** [comment]
I'll submit a PR later today for this, as I have a need for this right now. There is no workaround that I can find.

**Comment by luntzel** [comment]
+1
