### ISSUE TITLE
Add support for Google Cloud DNS

### ISSUE THREAD

**Issue by kendawg2** [hashicorp/terraform#1148]
Please add support for Google Compute Cloud DNS.   Like AWS, it would be great to update the DNS in Google.

**Comment by max-voloshin** [comment]
:+1:

**Comment by permyakovsv** [comment]
+1

**Comment by sparkprime** [comment]
I had a quick look at the APIs and the existing AWS support.  This seems very feasible, I'll have a go soon.

**Comment by max-voloshin** [comment]
@mikkoc, @sparkprime, thanks!
