### ISSUE TITLE
AWS Container instance draining integration with ASG replacements

### ISSUE THREAD

**Issue by spy-tech** [hashicorp/terraform#11484]
In Amazon ECS one currently requires at least one extra cluster node during deployments of AMI upgrades of ASG backed ECS clusters, because otherwise there is nothing to fail over to (assuming a `wait_for_elb_capacity = "1"` and a desired number of ECS tasks equal to the number of instances in the ASG). 

Amazon has introduced the following feature, which would remove this limitation.
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-draining.html

I would like Terraform to do connection draining in a rolling upgrade fashion, such that tasks running on cluster nodes running old AMIs will automatically be scheduled to run on cluster nodes running new AMIs. This way there are no system resources being wasted and there is no need to write upgrade scripts which do multiple invocations of terraform to manage a deployment.

Related discussion: #11459

**Comment by acejam** [comment]
I'm also very interested in this. Right now this can already be done using a local provisioner shell script calling various AWS cli commands. It would be nice to have it native to Terraform though.
