### ISSUE TITLE
Bad idea to use option argument in terraform module?

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform#11508]
# Version
0.8.5

# Scenario
I create a AWS RDS module like below:

```
resource "aws_db_instance" "db" {
  ...
  #  (Optional) The days to retain backups for. Must be 1 or greater to be a source for a Read Replica
  backup_retention_period = "${var.backup_retention_period}"
  ...
}
```

And as it says in document, the value must be bigger than 1, but I need to set it to 0 to disable backup feature. Should I create a new module only without this option argument? 

Maybe the option argument is not friendly to module mechanism now. I hope the option argument should provide a value to disable itself.

**Comment by mitchellh** [comment]
I'd ask usage questions like this on the mailing list. You'll get more daily users that way that may have real world experience of why this may or may not be a good idea. Personally, I don't think its a bad idea as long as you set a reasonable default yourself.
