### ISSUE TITLE
Crash in `terraform plan`

### ISSUE THREAD

**Issue by arsdehnel** [hashicorp/terraform#11528]
This one seems weird to me.  I have a set of modules that are shared across our environments.  I've had them for a long time and the flow is to update the module as changes are needed and then roll up through the environments applying those changes one at a time.  Today I added an S3 bucket to one of the modules and started the application process.  First two environments were fine but the third one blew up with the indicated debug and panic outputs.

### Terraform Version
0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket

### HCL files
This is hosted on a private GitHub Enterprise and is pretty involved to get the whole setup.  The bit that I added today:

```
resource "aws_s3_bucket" "email_content" {
	bucket = "${var.email_subdomain}.goalquestprogram.com"
	acl = "public-read"
	policy = <<EOF
{
	"Id": "Policy1472270546009",
	"Statement": [
		{
			"Action": "s3:GetObject",
			"Effect": "Allow",
			"Principal": "*",
			"Resource": "arn:aws:s3:::${var.email_subdomain}.goalquestprogram.com/*",
			"Sid": "Stmt1472270544297"
		}
	],
	"Version": "2012-10-17"
}
EOF

    website {
        index_document = "index.html"
        error_document = "error.html"
    }

}

```

### Debug Output
https://gist.github.com/arsdehnel/02557e2078bddb126eccbc3f5fff5ca2#file-debug-og

### Panic Output
https://gist.githubusercontent.com/arsdehnel/02557e2078bddb126eccbc3f5fff5ca2/raw/ef3d14298423b4efea6a622a0e6b42a9f6bfc743/crash.log

### Expected Behavior
It should've created the S3 bucket like it did in the first couple environments.

### Actual Behavior
It got most of the way (maybe all the way) through the plan and then crashed before reporting the changeset.

### Steps to Reproduce
Not sure how I got to this point but right now all I do to recreate it is this:
1. `terraform plan`

**Comment by grubernaut** [comment]
Hi @arsdehnel, thanks for the issue! 

This has actually been fixed in #11321, and will be released in the next minor version of Terraform (v0.8.6). Thanks!

**Comment by arsdehnel** [comment]
Excellent! Any eta on 0.8.6? Or should I pull the latest and build my own?

**Comment by grubernaut** [comment]
@arsdehnel we unfortunately don't have a solid date set yet, but best guess would target sometime next week.
