### ISSUE TITLE
[NEW RESOURCE] Database Migration Service

### ISSUE THREAD

**Issue by dusansusic** [hashicorp/terraform#11527]
Hi,
Is it possible to support AWS DMS service, instance subnet group, instance itself, endpoints and tasks?
Thanks.

**Comment by stack72** [comment]
Hi @dusansusic 

Thanks for the request - luckily, we are in the final stages of trying to get a PR merged for this :) I assume it will be in 1 of the next 2 versions of TF

Keep an eye on the CHANGELOG :)

Paul
