### ISSUE TITLE
unexpected EOF [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred

### ISSUE THREAD

**Issue by marrotte** [hashicorp/terraform#11525]
### Terraform Version
Terraform v0.8.5

### Affected Resource(s)
- vsphere_virtual_machine

### Terraform Configuration Files
```variable "vsphere_password" {}

# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = "administrator@vsphere.local"
  password       = "${var.vsphere_password}"
  vsphere_server = "192.168.38.31"
  # if you have a self-signed cert
  allow_unverified_ssl = true
}


# Create a virtual machine 
resource "vsphere_virtual_machine" "ubuntu-docker" {
  count  = 3
  name   = "ubuntu-docker-master-${count.index}"
  vcpu   = 2
  memory = 4096

  network_interface {
    label = "VM Network"
  }

  network_interface {
    label = "vchPortGroup"
  }

  disk {
    template = "Templates/ubuntu-1604-docker"
    datastore = "datastore1"
  }
}
```

### Debug Output
https://gist.github.com/marrotte/b687a700bce33d1987a8bdd64d379313

### Panic Output
https://gist.github.com/marrotte/9c7b77d27cb8a14bd78a14981413407c

### Expected Behavior
Built 3 vm's on esxi host and report success

### Actual Behavior
Built 3 vm's on esxi host and report failure

### Steps to Reproduce
`terraform apply`

**Comment by mitchellh** [comment]
Notes: This is a crash (index out of range) coming out of the vsphere provdier.

**Comment by carlossg** [comment]
@mitchellh there are a bunch of vsphere issues reported with the same error, just searching for EOF and crash https://github.com/hashicorp/terraform/issues?utf8=%E2%9C%93&q=vsphere%20eof%20crash%20

The one with more detail seems to be https://github.com/hashicorp/terraform/issues/9495
