### ISSUE TITLE
Unable to create RDS cross Regions Encrypted Read Replica

### ISSUE THREAD

**Issue by karthimohan** [hashicorp/terraform#11538]
Hi there,

AWS has announced the support for Cross Region encrypted Read Replica on Jan 23rd https://aws.amazon.com/about-aws/whats-new/2017/01/amazon-rds-now-supports-read-replicas-of-encrypted-database-instances-across-regions/. I have tested this and i am able to created this via AWS console. 

I am trying to do this via Terraform and i get the following error
Error creating DB Instance: InvalidParameterCombination: Cannot create a cross region unencrypted read replica from encrypted source.
	status code: 400, request id: f6a701d0-e787-11e6-accd-4b34bdf2cec9

I have a Source DB in US-East and I am creating the Read Replica in US-WEST. 

I had the TF file to create the Cross Region read replica without encryption which was working fine. Now that i want to create a Cross Region read replica with encyption. I just added 2 new flags,  storage_encrypted = true
kms_key_id = us-west kms key ID

Here is my full TF file 
`  name:                       "" => "<computed>"
resource "aws_db_instance" "dbname-replica-us-west-2" {
    identifier                = "dbname-us-west-2"
    allocated_storage         = 100
    storage_type              = "io1"
    iops                      = 1000
    engine                    = "mysql"
    engine_version            = "5.6.29"
    replicate_source_db       = "arn:aws:rds:us-east-1:xxx:db:dbname"
    instance_class            = "db.m4.large"
    port                      = 3306
    publicly_accessible       = false
    availability_zone         = "us-west-2a"
    vpc_security_group_ids    = ["${aws_security_group.dr-rds-tf-sg.id}"]
    db_subnet_group_name      = "rds_subnetgroup"
    parameter_group_name      = "custom-rds-pg"
    license_model             = "general-public-license"
    backup_retention_period   = 7
    backup_window             = "04:15-04:45"
    maintenance_window        = "sat:08:00-sat:09:00"
    final_snapshot_identifier = "dbname-us-west-2-final"
    skip_final_snapshot       = false
    storage_encrypted         = true
    kms_key_id                = "arn:aws:kms:us-west-2:xxx:key/xxxxxxx"
    tags {
      "workload-type" = "production"
    }
}`
Could you please let me know if this feature is not yet available yet or am i missing something here.
Since this is recently announced by AWS. Terraform needs to rebuilt with latest AWS sdk?

### Terraform Version
terraform -v
Terraform v0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_db_instance

### Debug Output
https://gist.github.com/karthimohan/dc051c92328a94da99dde0e6a60660cf

**Comment by stack72** [comment]
Hi @karthimohan 

Thanks for getting in touch about this feature. This is currently not supported in Terraform but there is a PR open to support this. We are working out how we get this tested and it will be included in the next version of Terraform

Thanks

Paul

**Comment by karthimohan** [comment]
@stack72 Could you please provide with the PR number so i can follow the updates? Thanks

**Comment by stack72** [comment]
Hi @karthimohan 

It has been merged this afternoon and will be part of Terraform 0.8.6

Paul
