### ISSUE TITLE
aws/route53 - Add support for weighted resource record sets

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1155]
This would effectively allow some load-balancing features of Route53:
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-weighted
http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Requests.html#API_ChangeResourceRecordSets_RequestWRRAliasSyntax

It's already part of the API endpoint we use for basic resource record sets, so it may just need adding more options accordingly to `aws_route53_record`.

**Comment by rodrigodelmonte** [comment]
Thank you!
