### ISSUE TITLE
Inline remote-exec error checking breaks variable usage

### ISSUE THREAD

**Issue by kpersohn** [hashicorp/terraform#11569]
The fix in #11155 is great for exit codes, but an unfortunate side effect is that shell variable are no longer useful for carrying information between lines of an inline script. Maybe the benefit of exit codes is worth the price; however, I figure it's worth bringing up since this presents a fairly significant breaking behavior change for inline scripts that use shell vars. 

### Terraform Version
`Terraform v0.8.5`

### Expected Behavior
Variables exported in one line of an inline script are available in a subsequent line. 

### Actual Behavior
Shell errors on unbound local variable (or silently interpolates an empty value). 

### Steps to Reproduce
Here's a sample I use for provisioning a node that runs Terraform:
```
provisioner "remote-exec" {
    inline = [
      "export TERRAFORM_VERSION=0.8.5",
      "export TERRAFORM_SHA256SUM=4b4324e354c26257f0b830eacb0e7cc7e2ced017d78855f74cb9377f1abf1dd7",
      "set -eux; curl https://releases.hashicorp.com/terraform/$${TERRAFORM_VERSION}/terraform_$${TERRAFORM_VERSION}_linux_amd64.zip > /tmp/terraform_$${TERRAFORM_VERSION}_linux_amd64.zip",
      "echo \"$${TERRAFORM_SHA256SUM}  /tmp/terraform_$${TERRAFORM_VERSION}_linux_amd64.zip\" > /tmp/terraform_$${TERRAFORM_VERSION}_SHA256SUMS",
      "sha256sum --check --status /tmp/terraform_$${TERRAFORM_VERSION}_SHA256SUMS",
      "sudo unzip /tmp/terraform_$${TERRAFORM_VERSION}_linux_amd64.zip -d /bin",
      "rm -f /tmp/terraform_$${TERRAFORM_VERSION}_linux_amd64.zip",
    ]
  }
```

```
/tmp/terraform_1563683380.sh: line 2: TERRAFORM_VERSION: unbound variable
```

The exported shell vars on lines one and two are not accessible to the remainder of the script because each line is treated as an independent shell script now.

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. While provisioners, as a whole, aren’t a top priority for the team, when some time is available to focus on them we’re going to use that attention to tackle some long-standing defects.

We are also thinking about how to evolve provisioning for many of our community’s use cases but have yet to take a firm decision on the direction that work will take.

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
