### ISSUE TITLE
AWS undocumented command aws_vpc_peering_connection

### ISSUE THREAD

**Issue by kendawg2** [hashicorp/terraform#1157]
There is a resource_aws_vpc_peering_connection which does not appear in the docs.   It can be reached manually by going to https://www.terraform.io/docs/providers/aws/r/vpc_peering.html but there should be a link to it in the sidebar.   Going to that link indicates it's in VPC.

**Comment by mitchellh** [comment]
Fixed in master, we can't deploy until 0.4 though unfortunately!
