### ISSUE TITLE
Support ip_address_type on aws_alb resource

### ISSUE THREAD

**Issue by tjwallace** [hashicorp/terraform#11586]
AWS application load balancers now support a `IpAddressType` param ([documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateLoadBalancer.html)).

**Comment by ole-flaregames** [comment]
Duplicated issue #1429

**Comment by stack72** [comment]
Thanks for the request @tjwallace - closing as a dupe. Please keep an eye on the other issue for tracking
