### ISSUE TITLE
Some comments at end of file get formatted improperly with terraform fmt

### ISSUE THREAD

**Issue by grepory** [hashicorp/terraform#11585]
### Terraform Version
Terraform v0.8.5 (also tested with 0.8.4)

### Affected Resource(s)
This is specifically a problem with `terraform fmt`.

### Terraform Configuration Files
```hcl
resource "blah" "blah" {}

//
//
//
```

This behavior is also exhibited with:
```hcl
resource "blah" "blah" {}

#
#
#
```

### Debug Output
https://gist.github.com/grepory/6c28d2688cfb086d9a6f9af32b3c5fb2

### Expected Behavior
Well, I'd expect the comment not to have a bunch of additional spaces added to it.

### Actual Behavior
The file was modified to look like this:

```hcl
resource "foo" "nam" {}

//


//


//
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform fmt test.tf`

### Important Factoids
Nope. Nothing special, really.

**Comment by grubernaut** [comment]
HCL issue, related to https://github.com/hashicorp/hcl/pull/184, yet needs a subsequent fix (https://github.com/hashicorp/hcl/pull/184/files#diff-270e13ebd69dcf1e88f1d32edd8f2d9eR699).
cc: @mitchellh

**Comment by mitchellh** [comment]
Fix is in! We will backport this over to 0.8.x shortly. The fix isn't perfect (we still leave a newline we shouldn't) but it looks right and is much much better.

**Comment by grepory** [comment]
😗

**Comment by mitchellh** [comment]
Fixed!
