### ISSUE TITLE
Crash on removing vpc_config section from aws_lambda_function

### ISSUE THREAD

**Issue by shorn** [hashicorp/terraform#11582]
TF version 0.8.5, on Windows 10.

Had a lambda in a VPC in public subnet, realised that it was not going to be able to access internet unless I create a NAT.  
Instead, decided to move lambda out of VPC:

-  removed vpc_config section
-  ran apply
-  TF crashed

> panic: empty structure "vpc_config." has entry "vpc_config.0.vpc_id"

[crash.zip](https://github.com/hashicorp/terraform/files/743475/crash.zip)

**Comment by grubernaut** [comment]
Hi @shorn, thanks for the issue! 

Closing as this has actually been fixed in #11321, and should be released with the next minor version of Terraform (v0.8.6). Happy to discuss this further if the issue persists, however.
