### ISSUE TITLE
panic: empty structure "initial_lifecycle_hook." has entry "initial_lifecycle_hook.78676173.default_result"

### ISSUE THREAD

**Issue by pagemedias** [hashicorp/terraform#11588]
### Terraform Version
0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_autoscaling_group

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_group" "ecs_host_autoscaling_group" {
  # Required
  launch_configuration = "${aws_launch_configuration.host_launch_conf.name}"
  max_size = "${var.max_hosts}"
  min_size = "${var.min_hosts}"

  # Other
  name = "${aws_launch_configuration.host_launch_conf.name_prefix}autoscaling"
  vpc_zone_identifier = "${var.host_subnets}"
  initial_lifecycle_hook {
    name                   = "hook_ec2_instance_terminating"
    default_result         = "CONTINUE"
    heartbeat_timeout      = 3600
    lifecycle_transition   = "autoscaling:EC2_INSTANCE_TERMINATING"
    notification_target_arn = "${aws_sns_topic.ecs_host_autoscaling_group_lifecyclehook_notis.arn}"
    role_arn                = "${aws_iam_role.ecs_host_autoscaling_group_role.arn}"
  }

  depends_on = ["aws_launch_configuration.host_launch_conf","aws_sns_topic.ecs_host_autoscaling_group_lifecyclehook_notis"]
}
```

### Panic Output
panic: empty structure "initial_lifecycle_hook." has entry "initial_lifecycle_hook.78676173.default_result"
https://gist.github.com/pagemedias/b90b584ffc147be399437d53776332df

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create terraform config of ASG with `initial_lifecycle_hook` attribute
2. `terraform apply`
3. Remove `initial_lifecycle_hook` attribute from ASG
4. `terraform apply`

### References
Came across this while reporting... https://github.com/hashicorp/terraform/issues/11587

**Comment by mitchellh** [comment]
Hey @jbardin can you take a look at this since this was your context and fix awhile back?
