### ISSUE TITLE
Cannot use initial_lifecycle_hook attribute in aws_autoscaling_group if ASG already exists

### ISSUE THREAD

**Issue by pagemedias** [hashicorp/terraform#11587]
### Terraform Version
0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_autoscaling_group

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_group" "ecs_host_autoscaling_group" {
  # Required
  launch_configuration = "${aws_launch_configuration.host_launch_conf.name}"
  max_size = "${var.max_hosts}"
  min_size = "${var.min_hosts}"

  # Other
  name = "${aws_launch_configuration.host_launch_conf.name_prefix}autoscaling"
  vpc_zone_identifier = "${var.host_subnets}"
  initial_lifecycle_hook {
    name                   = "hook_ec2_instance_terminating"
    default_result         = "CONTINUE"
    heartbeat_timeout      = 3600
    lifecycle_transition   = "autoscaling:EC2_INSTANCE_TERMINATING"
    notification_target_arn = "${aws_sns_topic.ecs_host_autoscaling_group_lifecyclehook_notis.arn}"
    role_arn                = "${aws_iam_role.ecs_host_autoscaling_group_role.arn}"
  }
  initial_lifecycle_hook {
    name                   = "hook_ec2_instance_launching"
    default_result         = "CONTINUE"
    heartbeat_timeout      = 3600
    lifecycle_transition   = "autoscaling:EC2_INSTANCE_LAUNCHING"
    notification_target_arn = "${aws_sns_topic.ecs_host_autoscaling_group_lifecyclehook_notis.arn}"
    role_arn                = "${aws_iam_role.ecs_host_autoscaling_group_role.arn}"
  }

  depends_on = ["aws_launch_configuration.host_launch_conf","aws_sns_topic.ecs_host_autoscaling_group_lifecyclehook_notis"]
}
```

### Expected Behavior
Create lifecycle hooks in auto scaling group

### Actual Behavior
Does not create lifecycle hooks if Auto Scaling Group already exists (previously created ASG with Terraform, just adding initial_lifecycle_hooks)

Have to use the aws_autoscaling_lifecycle_hook resource instead.

Want to use initial_lifecycle_hook attribute so if ever create from scratch again

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create ASG with terraform without initial_lifecycle_hook attribute
2. add initial_lifecycle_hook attribute to terraform config for ASG
3. `terraform` apply
4. Use AWS CLI to confirm lifecycle hook created (aws autoscaling describe-lifecycle-hooks --auto-scaling-group-name <name of ASG>)

**Comment by FransUrbo** [comment]
Personally, I'm not sure if this is wrong. Yes, a change to a resource should be done (of course!), but it's always better to split it up if possible (as in, use the `aws_autoscaling_lifecycle_hook` separately).

It's more resources to maintain, and can be somewhat unruly to read the manifest(s) if you're not used to it, but in the long run, it's always better to split things up as much as possible because then you usually don't have to recreate a (big) resource because of a (small) change. Only the 'link' needs to be recreated, which most often than not is not a problem.

**Comment by pagemedias** [comment]
After some more work on this I actually agree with you.

There is also another reason to use the separate aws_autoscaling_lifecycle_hook resource... In my case I found that the terraform apply of a new ASG (with initial_lifecycle_hook) never completes (times out after 10mins) because terraform is waiting for the instances in the ASG to be created and they get stuck in Pending:Wait due to the lifecycle hook. This is the same if you try to destroy the ASG. 

Perhaps as so long as the documentation is clear that initial_lifecycle_hook only work when creating a new ASG, then this issue can be closed

**Comment by stack72** [comment]
Hi @pagemedias 

I am going to add a note to the documentation that this will only work on creation

Thanks to you both for the discussion here and working this out

Thanks

Paul

**Comment by stack72** [comment]
Hi @pagemedias 

Please can you have a look at the attached PR and let me know if this will allow me to close the issue?

Thanks

Paul

**Comment by pagemedias** [comment]
Thanks Paul. I think this is sufficient

**Comment by stack72** [comment]
👍 :)
