### ISSUE TITLE
AWS - Add Blue/Green Deployments support to CodeDeploy Deployment Groups

### ISSUE THREAD

**Issue by daaru00** [hashicorp/terraform#11592]
Can you add support to BlueGreenDeployment aka In-Place Deployment? 

Adding a flag "In-place deployment"/"Blue/green deployment" on aws_codedeploy_deployment_group as described in http://docs.aws.amazon.com/codedeploy/latest/userguide/welcome.html#welcome-deployment-overview

**Comment by codepushr** [comment]
Just stumbled over the same issue. Btw. isn't in-place != blue/green? I thought in-place is patching the application revision on the same instance whereas blue/green is booting a new ASG/ELB.

**Comment by daaru00** [comment]
Blue-green deployment does not create a new ASG/ELB but create a new instance in the same ASG with new revision subsequently destroy the instance with old revision.
Check this article: https://aws.amazon.com/about-aws/whats-new/2017/01/aws-codedeploy-introduces-blue-green-deployments/

**Comment by codepushr** [comment]
I see, so it's using the same ASG and ELB. Still in-place is patching the existing instances so it's not really "aka" right?

**Comment by daaru00** [comment]
I'm sorry, I have not seen, it's only a typo.

**Comment by niclic** [comment]
If this issue is intended to add support for Blue/Green Deployments, then I think the issue title should be changed.

@stack72 
Can you change the title of this issue to something like "Add Blue/Green Deployments support to CodeDeploy Deployment Groups"?

I've contributed a few patches to this particular resource so I was planning on adding this feature as well (unless it's already spoken for).

**Comment by niclic** [comment]
FYI

Here is the PR (WIP) to add this feature: https://github.com/hashicorp/terraform/pull/11700

**Comment by niclic** [comment]
UPDATE: The corresponding [PR](https://github.com/hashicorp/terraform/pull/11700) is ready for review.

**Comment by mtaracha** [comment]
hey @niclic - do you know if there is any plan to merge your PR into master? I'd really like to use it in our terraform infrastructure!

**Comment by niclic** [comment]
@stack72 Are you able to give us some idea when https://github.com/hashicorp/terraform/pull/11700 might be merged? 

;)

**Comment by zdobrenen** [comment]
any word on the progress of merging this PR? this functionality would be much appreciated!

**Comment by dwkerwin** [comment]
+1, would like to use this functionality...

**Comment by shifty1990** [comment]
+1 this would be useful

**Comment by zdobrenen** [comment]
any news on when this PR might be merged? thanks!

**Comment by huyanhvn** [comment]
+1

**Comment by niclic** [comment]
There has been some recent activity on the PR and it is now ready to be merged. I'm hoping that the committers will get it merged in the next couple of days. Thanks for your patience.

**Comment by carlosalan** [comment]
+1 this would be useful

**Comment by alexandrusavin** [comment]
Any news with this PR? I would really appreciate a status update. Thank you!

**Comment by golimer** [comment]
WHY CLOSED?

**Comment by Alberts00** [comment]
Hey @golimer, issue was moved to terraform-providers/terraform-provider-aws#504 and was fixed in 1.1.0.
