### ISSUE TITLE
Support for elasticsearch_version 5.1 within AWS_ELASTICSEARCH_DOMAIN

### ISSUE THREAD

**Issue by volcomism** [hashicorp/terraform#11595]
I noticed in the documentation that it states, "[elasticsearch_version](https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html#elasticsearch_version) - The version of ElasticSearch to deploy. Only valid values are 1.5 and 2.3. Defaults to 1.5"

With the new release of Elasticsearch version 5.1 within [AWS's Elasticsearch Service](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es_version_5_1.html) it'd be great to provision this with terraform.

### Terraform Version
v0.8.4

### Affected Resource(s)
- aws_elasticsearch_domain

**Comment by stack72** [comment]
Hi @volcomism 

I will update the documentation. Luckily, we have no hard coded restriction on the value - so AFAICT, 5.1 should just work. I am worried that there are some configuration parameters missing that are required for the 5.1 version

I can't find anything in the SDK specific to 5.1. So I guess you should be able to take this for a spin and try it :) If you do, please can you report back any errors in this thread?

Paul

**Comment by volcomism** [comment]
Hi @stack72 

Thanks for the quick reply. Everything seems to be working normal with elasticsearch_version 5.1! Cheers.
