### ISSUE TITLE
v0.3.7 AWS instance resource: source_dest_check not set appropriately

### ISSUE THREAD

**Issue by DoctorVin** [hashicorp/terraform#1160]
All AWS instances I deploy with Terraform 0.3.7 have the "Source/dest. check" property set to true, regardless of the value set in the specification file. I am defining a typical AWS NAT instance as follows:

resource "aws_instance" "nat" {
	ami = "${lookup(var.amis, var.region)}"
	instance_type = "t2.micro"
	subnet_id = "${aws_subnet.public.id}"
	security_groups = ["${aws_security_group.default.id}", "${aws_security_group.nat.id}"]
	key_name = "${aws_key_pair.deployer.key_name}"
	source_dest_check = false
	tags {
		Name = "src-dst"
	}
	connection {
		user = "ubuntu"
		key_file = "ssh/insecure_deployer"
	}
	provisioner "remote-exec" {
		inline = [
		"sudo iptables -t nat -A POSTROUTING -j MASQUERADE",
		"sudo sysctl -w net.ipv4.ip_forward=1"
		]
	}
}

**Comment by mitchellh** [comment]
This is fixed in master, we'll have a relase out soon!

**Comment by DoctorVin** [comment]
Awesome! Thanks!
