### ISSUE TITLE
aws_rds_snapshot data source

### ISSUE THREAD

**Issue by kojiromike** [hashicorp/terraform#11615]
Similar to #8828, it would be nice to have a data source to provide snapshot ids for rds when provisioning new rds resources.

### Terraform Version
0.8.5

### Affected Resource(s)
- aws_rds_cluster
- aws_db_instance

### Terraform Configuration Files (conceptual)

```hcl
data "aws_rds_snapshot" "example" {
  most_recent = true
  filter {
    name = "name"
    values = ["xmpl-snap-vpc-*"]
  }
  owners = ["self"]
}
resource "aws_db_instance" "db" {
  …
  snapshot_identifier = "${data.aws_rds_snapshot.example.id}"
  …
}
```

### Desired Behavior
This would pick the most recent snapshot matching the filters given, and use that to create the described db instance or rds cluster.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #8828

**Comment by tomelliff** [comment]
Is this not covered by https://github.com/hashicorp/terraform/pull/10291/ ?

**Comment by kojiromike** [comment]
Derp! I totally missed that. Thanks! (As an excuse/nitpick, it's a little unfortunate that Terraform uses both `_db_` and `_rds_` in its resource and data source names. It's hard to know what to search for.)
