### ISSUE TITLE
Unable to create Proxy resource in API gateway with aws_api_gateway_resource

### ISSUE THREAD

**Issue by djandruczyk** [hashicorp/terraform#11618]
aws_api_gateway_resource is missing functionality to be able to create a proxy resource as well as to enable  API gateway CORS on a resource...

### Terraform Version
0.8.5

### Affected Resource(s)
 - aws_api_gateway_resource

### Terraform Configuration Files

resource "aws_api_gateway_resource" "stage_proxy_api_resource" {
  rest_api_id = "${aws_api_gateway_rest_api.MyAapp_stage_api.id}"
  parent_id = "${aws_api_gateway_resource.stage_MyApp_api_resource.id}"
  path_part = "{proxy+}"
}

### Expected Behavior
There is no option to specify this is a proxy resource (At least in the current documentation) nor is there one to specify "Enable API Gateway CORS" either

**Comment by adm351** [comment]
@djandruczyk I've successfully created a proxy resource using the path_part {proxy+} when combined with a proxy integration_http_method. Agreed there is no way to enable CORS. If you click the [Enable CORS] in the console its just running multiple actions to enable an OPTIONS method and req/resp templates. You could replicate this with your own methods.

**Comment by djandruczyk** [comment]
Excellent, thanks!


-- David

**Comment by knaak** [comment]
Thank you!  That was the hint that I needed.

For the next person, this is the snippet that worked for me:

`
resource "aws_api_gateway_resource" "TerraProxyResource" {
  rest_api_id = "${aws_api_gateway_rest_api.TerraTest.id}"
  parent_id = "${aws_api_gateway_rest_api.TerraTest.root_resource_id}"
  path_part = "{proxy+}"
}

resource "aws_api_gateway_integration" "integration" {
    rest_api_id = "${aws_api_gateway_rest_api.TerraTest.id}"
    resource_id = "${aws_api_gateway_resource.TerraProxyResource.id}"
	http_method = "${aws_api_gateway_method.mymethod.http_method}"
	
	type = "HTTP_PROXY"
	integration_http_method = "ANY"
	uri = "http://api.endpoint.com/{proxy+}"
}

resource "aws_api_gateway_method" "mymethod" {
  rest_api_id = "${aws_api_gateway_rest_api.TerraTest.id}"
  resource_id = "${aws_api_gateway_resource.TerraProxyResource.id}"
  http_method = "ANY"
  authorization = "NONE"
}


`

**Comment by knaak** [comment]
What do you set the uri value in the gateway_integration?

`resource "aws_api_gateway_integration" "integration" {
    rest_api_id = "${aws_api_gateway_rest_api.TerraTest.id}"
    resource_id = "${aws_api_gateway_resource.TerraProxyResource.id}"
	http_method = "${aws_api_gateway_method.mymethod.http_method}"
	
	type = "HTTP_PROXY"
	integration_http_method = "ANY"
	
	uri = "https://api.myendpoint.com/{proxy}"
}'

I've tried {proxy}, *, {proxy+}, empty but I receive an internal error each time.  When I check the logs, it dies at the {:

Endpoint request URI: https://api.myendpoint.com/{proxy}
Execution failed due to configuration error: Illegal character in path at index 26: https://api.endpoint.com/{proxy}

**Comment by knaak** [comment]
I had trouble getting to work, but this stackexchange question/answer solved it for me.

http://stackoverflow.com/questions/39040739/in-terraform-how-do-you-specify-an-api-gateway-endpoint-with-a-variable-in-the
