### ISSUE TITLE
Deprecation warnings doesn't seem to appear (v0.9.0-dev)

### ISSUE THREAD

**Issue by heimweh** [hashicorp/terraform#11628]
Hi there,

in previous versions (`0.8.x`) when marking a field as `Deprecated` an error like this would be shown to the user:

```bash
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Warnings:
  * data.test.test: "name_regex": [DEPRECATED] Use field 'name' instead

No errors found. Continuing with 1 warning(s).
```

In `v0.9.0-dev` this warning doesn't seem to appear, 
but you can see the validation error in the log when you run `TF_LOG=TRACE`:
```bash
2017/02/02 11:19:58 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: ["name_regex": [DEPRECATED] Use field 'name' instead]. Errors: []
```

Not exactly sure what this might be but hopefully this will help debugging the issue 🙂 

### Terraform Version
v0.9.0-dev

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Mark a field as deprecated
2. `terraform plan` - No warning message appears
3. `TF_LOG=TRACE terraform plan 2>&1 | grep  "EvalValidateResource, err"` to see the warning

**Comment by mitchellh** [comment]
Fantastic. Thank you. I'll take a look at this.
