### ISSUE TITLE
changing identifier in RDS (aws_db_instance) will destroy/create the db

### ISSUE THREAD

**Issue by adrianlop** [hashicorp/terraform#11636]
### Terraform Version
0.8.5

### Affected Resource(s)
- aws_db_instance

### Expected Behavior
Using AWS RDS UI you can change the identifier and it won't recreate the database, it will only apply it on the preferred maintenance window/apply immediately if you select it.

![image](https://cloud.githubusercontent.com/assets/2879742/22552084/52172320-e94f-11e6-8051-2ffd3c1214fc.png)

This change also changes the endpoint, so AWS will give you a warn as expected: `Warning! Endpoint will also change`.

### Actual Behavior
Terraform will destroy + recreate the instance. It should only apply the change in the maintenance window or immediately if you selected `apply_immediately=true`, not destroy the DB.

Thanks.

**Comment by hnarimani** [comment]
Any answer?

**Comment by tgjamin** [comment]
This would be great if Terraform didn't try to destroy my DB instances when doing a "DB instance identifier change". Something you can do easily in the AWS console. So my current workaround is to change the db instance id via AWS console, manually change my tfstate json, and then run `terraform plan` and `terraform apply` to make sure it's all good. 

Also, why was this issue closed without any resolution/comment/discussion?
