### ISSUE TITLE
SQS FIFO has multiple, apparently incompatible assertions for name property

### ISSUE THREAD

**Issue by tragiclifestories** [hashicorp/terraform#11632]
### Terraform Version
0.8.4, 0.8.5

### Affected Resource(s)
- aws_sqs_queue

#### Version one
```hcl
resource "aws_sqs_queue" "scheduled_alerts" {
    name = "scheduled-alerts"
    fifo_queue = true
    content_based_deduplication = true
}
```

#### Version two
```hcl
resource "aws_sqs_queue" "scheduled_alerts" {
    name = "scheduled-alerts.fifo"
    fifo_queue = true
    content_based_deduplication = true
}
```

### Expected Behavior
One of the two ought to create the queue ... 

### Actual Behavior
In version one above, `terraform apply` fails with `FIFO queue name should ends with ".fifo"`

Correcting it to version two, we fail with `aws_sqs_queue.scheduled_alerts: Error creating SQS queue: InvalidParameterValue: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length`

### Steps to Reproduce
1. `terraform apply`

**Comment by tragiclifestories** [comment]
It turns out that we can't launch FIFO queues in the right region anyway, so me and my colleagues are out of luck regardless; but a little extra poking around setting the region to us-east-1 does not help, so this still seems to be a defect. If @Ninir is around, I'm wondering what the thinking was behind the assertion that the name should end in `.fifo` https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/validators.go#L605

**Comment by Ninir** [comment]
Hi @tragiclifestories 

Indeed, Only Ohio & Oregon at the moment. Heard it will be available more widely in the coming months.

Behind the assertion is the official documentation, here: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html:
> The name of a FIFO queue must end with the .fifo suffix. The suffix counts towards the 80-character queue name limit. To determine whether a queue is FIFO, you can check whether the queue name ends with the suffix.

So applying is fine BUT the AWS answer tells you that it should only contain `alphanumeric characters, hyphens, or underscores`?

**Comment by tragiclifestories** [comment]
Oh damn, I'm being daft - with us-east-2 it creates successfully.

I wonder if that could be checked at the planning stage, though. I'm unfamiliar with the codebase but will have a look later.

**Comment by grubernaut** [comment]
@tragiclifestories unfortunately it cannot be caught at the planning stage, as our validator interface can only take a single `interface{}` value based on a single schema value supplied. The `name` attribute for the `sqs_queue` resource has different validation assertions based on another key in the schema, `fifo_queue`. Thus, we have to perform validation after the schema for the resource is already evaluated, which happens during `apply`. 
We would love to allow this functionality in the future, as a lot of resources require multiple values to validate attribute assertions, but we're not quite there yet. 

Closing, as this is not an issue and working correctly. More than happy to discuss this further though. Thanks!

**Comment by alexwlchan** [comment]
Blergh. I just lost a bit of time debugging the same issue, only to learn I don’t have FIFO queues in eu-west-1. 😞

> unfortunately it cannot be caught at the planning stage, as our validator interface can only take a single interface{} value based on a single schema value supplied

I was going to suggest a better warning at the plan stage – _You’ve tried to create a FIFO queue, but FIFO queues are not available in your region_ – but if I’ve read the above correctly, is such a warning currently impossible? Can a validator only get the AWS region or the SQS queue name, but not both?

**Comment by grubernaut** [comment]
@alexwlchan that's correct, a validator cannot validate multiple schema values at the same time. We can validate a FIFO queue is placed in the correct region during `apply` time, but that doesn't help anyone with a CI setup to check `plan` output.
