### ISSUE TITLE
provider/google: google_compute_backend_service does not support full GCE API

### ISSUE THREAD

**Issue by gasparch** [hashicorp/terraform#11630]
### Terraform Version
Terraform v0.8.5

### Affected Resource(s)
- google_compute_backend_service

### Terraform Configuration Files
```hcl
resource "google_compute_backend_service" "infra_ls_backend_service" {
  name        = "ls-service"
  description = "Logstash"
  protocol    = "TCP"
  timeout_sec = 10
  enable_cdn  = false
  region      = "${var.gce_region}"

  backend {
    balancing_mode = "CONNECTION"
    group = "${google_compute_instance_group_manager.infra_ls_instance_grp_mgr.instance_group}"
  }

  health_checks = ["${google_compute_health_check.infra_ls_health_check.self_link}"]
}
```

### Debug Output

> * google_compute_backend_service.infra_ls_backend_service: Error creating backend service: googleapi: Error 400: Invalid value for field 'resource.backends[0].balancingMode': 'CONNECTION'. Either maxConnections or maxConnectionsPerInstance should be set with CONNECTION mode., invalid

Yes, that's a full message, it stop on word 'invalid'.

### Expected Behavior
Backend Service created in specified region with TCP CONNECTION mode. The service is not HTTP based, so there is no need for HTTP.

Also if I change balancing_mode to UTILIZATION I'm following error because if conflicts with manually created backend service. That hints me that terraform also tries to create global resource, despite I specifically asked to create it in region. (resource url is projects/xxxx/**global**/backendServices/intra-ls-backend-service)

> * google_compute_backend_service.infra_ls_backend_service: Error creating backend service: googleapi: Error 400: Validation failed for instance group 'projects/xxxx/zones/europe-west1-b/instanceGroups/infra-ls-group': backend services 'projects/xxxx/global/backendServices/intra-ls-backend-service' and 'projects/xxxx/regions/europe-west1/backendServices/tesing-manual-logstash-loadb' point to the same instance group but the backends have different 'balancing_mode'., incompatibleBackendServices

### Actual Behavior
terraform fails to process .tf file and does not create resources.

### Steps to Reproduce
terraform apply on manifest with snipped from above.

**Comment by danawillow** [comment]
Are you trying to create a region backend service? If so, you should use the https://www.terraform.io/docs/providers/google/r/compute_region_backend_service.html resource. The `region` parameter in `google_compute_backend_service` is deprecated.

**Comment by gasparch** [comment]
Hi, I figured that out, yes. But i would rather have terraform shout at me and tell that immediately than going through the bug report to find it out. :)
