### ISSUE TITLE
Need a proper error message for template_data resource if some values are not assigned 

### ISSUE THREAD

**Issue by dattatrayakumbhar** [hashicorp/terraform#11633]
### Terraform Version
Terraform v0.8.5

### Affected Resource(s)
data_template 

### Terraform Configuration Files
[root@gsljumphost terraform-issue]# ls
main.tf  rds  temp varible.tf

[root@gsljumphost terraform-issue]# terraform get
Get: file:///home/cloud-user/datkumbh/terraform-issue/rds
Get: file:///home/cloud-user/datkumbh/terraform-issue/temp

###main.tf
------------------------
module rds {
count = "2"
}
module temp {
 service_name        = "test#"
 service_count       = "2"
 service_ips         = "${module.rds.oracle_fnd_address}"
 service_port        = "${module.rds.oracle_fnd_port}"
}

###rds/output.tf
--------------------------------------------------
output "oracle_fnd_address" {
  value = ["${aws_db_instance.oracle_fnd_rds_instance.*.address}"]
}
output "oracle_fnd_port" {
   value = "${aws_db_instance.oracle_fnd_rds_instance.port}"
  }

###rds/instance.tf
-----------------------------------------------------
 resource "aws_db_instance" "oracle_fnd_rds_instance" {
   instance_class = "db.m4.xlarge"
   count = "${var.rds_count}"
   allocated_storage = 10
   engine = "postgres"
   username = "##"
   password = "##"
   db_subnet_group_name = "test_rds_subnet_group"
   }
 }

###temp/temp.tf 
---------------------------------------------
data "template_file" "metadata_service" {
  count    = "${var.service_count}"
  template = "${file("meta_service_json.tpl")}"
  vars {
    service_name    = "${replace("${var.service_name}","#","${count.index}")}"
    address         = "${var.service_ips["${count.index}"]}"
    port            =  "${var.service_port}"
 }
}

###meta_service_json.tpl
---------------------------------------------------
{
"service": {
	    "name": "${service_name}",
        "Address": "${address}",
        "port": ${port}
         }
}

After terraform apply, I got below error:
Error applying plan:

2 error(s) occurred:

* data.template_file.metadata_service.0: failed to render : 3:17: unknown variable accessed: service_name
* data.template_file.metadata_service.1: failed to render : 3:17: unknown variable accessed: service_name

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

I got this error because it was not able to render port value properly as used output ""${aws_db_instance.oracle_fnd_rds_instance.port}" instead of 
"${aws_db_instance.oracle_fnd_rds_instance.*.port}"

It is like confusing that it could not render port but it still gives error saying failed to render 'service_name'.
I spent a lot of time with whats wrong with service_name.

We could optimize error message.

### Expected Behavior
Failed with below error "* data.template_file.metadata_service.0: failed to render : 3:17: unknown variable accessed: service_name"

### Actual Behavior
Should fail with * data.template_file.metadata_service.0: failed to render : 3:17: unknown variable accessed: service_port 

### Steps to Reproduce
1. Steps are easy and simple.
2. Create .tf as explained in section (Terraform Configuration Files) and do terraform apply.

**Comment by mitchellh** [comment]
This is actually related to #9080. Terraform is giving the best error message it can currently: service_name is actually just not set because if you follow the chain up it errors with what you said is the original error. If we fix #9080 the error message should just happen way higher.
