### ISSUE TITLE
Pagerduty provider service integration

### ISSUE THREAD

**Issue by pollosp** [hashicorp/terraform#11656]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.8.5

### Affected Resource(s)
PAGERDUTY_SERVICE_INTEGRATION

### Terraform Configuration Files
```hcl
resource "pagerduty_service" "aws_platform" {
  name = "AWS platform"
  escalation_policy = "${pagerduty_escalation_policy.platform.id}"
  acknowledgement_timeout = 1800
  auto_resolve_timeout = 14400
}

resource "pagerduty_service_integration" "cloudwatch" {
  name = "Cloudwatch API inbound integration"
  type = "aws_cloudwatch_inbound_integration" 
  service = "${pagerduty_service.aws_platform.id}"
}
```

### Debug Output
* pagerduty_service_integration.cloudwatch: Failed call API endpoint. HTTP response code: 400. Error: &{2001 Invalid Input Provided [Type cannot be empty.]}

### Expected Behavior
Create AWS cloudwatch integration in PagerDuty

**Comment by heimweh** [comment]
Hi @pollosp,

sorry for the confusion here. There seems to be an issue with the docs, will look into that asap.

To get this to work, try changing the `type` to `generic_events_api_inbound_integration`.

Does it work for you then?

**Comment by heimweh** [comment]
Hi @pollosp,

thanks for submitting this issue.

Does the following configuration work for you?

```hcl
resource "pagerduty_service" "aws_platform" {
  name                    = "AWS platform"
  escalation_policy       = "${data.pagerduty_escalation_policy.test.id}"
  acknowledgement_timeout = 1800
  auto_resolve_timeout    = 14400
}

data "pagerduty_vendor" "cloudwatch" {
  name_regex = "Cloudwatch"
}

resource "pagerduty_service_integration" "cloudwatch" {
  name    = "Cloudwatch API inbound integration"
  service = "${pagerduty_service.aws_platform.id}"
  vendor  = "${data.pagerduty_vendor.cloudwatch.id}"
  type    = "event_transformer_api_inbound_integration"
}
```

There seems to be some inconsistencies in how you get different service integrations installed and it seems like the API handles different service integrations differently. I'll look into this asap.

The documentation is also somewhat lacking vital information, I'll look into updating this as well.

Thanks again for submitting this issue and sorry for the troubles caused.

**Comment by pollosp** [comment]
Thanks for your fast answer and don't worry the provider is awesome. 
I did a work around creating the integration manually :( that it. I'm going to try your solution with the `event_transformer_api_inbound_integration`.

**Comment by pollosp** [comment]
@heimweh it worked fine with your code :) thanks

**Comment by stack72** [comment]
@pollosp / @heimweh can this be closed?

**Comment by heimweh** [comment]
Thanks @pollosp, I'm glad it's working now. 

@stack72 I guess we can close this one for now if you're okay with that @pollosp? but I'd like to follow up on this resource in the upcoming days. 
Will especially look into the documentation and add more common examples :)

**Comment by pollosp** [comment]
Yes, there is a work around so I think we can close it. Thanks

**Comment by stack72** [comment]
Thanks all :)
