### ISSUE TITLE
Terraform plan output - doesnt show resource dependencies for referenced modules

### ISSUE THREAD

**Issue by gauravbhandare** [hashicorp/terraform#11665]
Hi,

When provisioning the aws_security_group resources and having the aws_security_group_rule referencing a security group from another module, there is no evidence or information of the rules referring to aws_security_group, is there a way to show resource dependencies ?

**Terraform Version**

0.6

**Affected Resource(s)**

Please list the resources as a list, for example:
aws_security_group

Template TF file
```
resource "aws_security_group" "test-sg" {
  vpc_id      = "vpc-xxxxxxxx"
  name        = "test-sg"
  description = "test-sg-group through TF"

  tags {
    Name = "test-sg"
  }
}

module "central_module_for_common_rules" {
  source = "git::https://github.com/XXXXXX/YYYYY.git//common_rules"

  security_group_id = "${aws_security_group.test-sg.id}"

  env           = "${var.env}"
  region        = "${var.region}"
  ingress_rules = 1
  egress_rules  = 1
}
```
when the plan spits out the output there is no correlation between the rile and the group,

the security_group_id value is "${var.security_group_id}" vs "${aws_security_group.test-sg.id}" which is displayed for resources "aws_security_group_rule"

**Comment by mitchellh** [comment]
Hello! I notice you're on a much much older version of Terraform but I don't think this behavior has changed. When a value is "computed" (can't be determined at plan-time), we simply show the raw value from the configuration. There isn't anything more clever in there to show the dependencies. For now, I think this is the right approach. Showing more detailed dependence in the future would be fine, too, but we have no plans of doing so in the short term.
