### ISSUE TITLE
Unknown 'ValidateResource' shadow value for "aws_route_table_association"

### ISSUE THREAD

**Issue by chrisoldwood** [hashicorp/terraform#11664]
The following error showed up on the console `Experimental feature failure! Please report a bug.`

Here is the content of the log file it generated:

```
2 error(s) occurred:

* plan operation: Unknown 'ValidateResource' shadow value for "aws_route_table_association": &errors.errorString{s:"shadow closed"}
* plan operation: Unknown 'ValidateResource' shadow value for "aws_route_table_association": &errors.errorString{s:"shadow closed"}
```

I was running a Terraform script to create the "shell" of an entire environment in AWS, i.e. VPC, subnets, security groups, ELB, etc., but not EC2 instances.

**Comment by mitchellh** [comment]
Fix by #11733 (we're just disabling this for end users). Thanks!

**Comment by eric-aldinger** [comment]
I am still seeing this in 0.8.6 requesting spot instances on AWS.

$ terraform version
Terraform v0.8.6

2 error(s) occurred:

* apply operation: Unknown 'ValidateResource' shadow value for "aws_spot_instance_request": &errors.errorString{s:"shadow closed"}
* apply operation: Diff "aws_spot_instance_request.ba-cheap-worker" had unequal states (real, then shadow):

Do you want a new issue?

**Comment by mitchellh** [comment]
Nah, the shadow graph is gone for end users in the next version (Wednesday)
