### ISSUE TITLE
Removing a trigger causes terraform to crash

### ISSUE THREAD

**Issue by netjunki** [hashicorp/terraform#11673]
### Affected Resource(s)
- null_resource

### Terraform Configuration Files/Steps to Reproduce
The following script reproduced the bug reliably on OS X.
```
cat - > main.tf <<"EOF"
resource "null_resource" "test" {
  triggers {
    run_every_time = "${uuid()}"
  }
  provisioner "local-exec" {
    command = "echo this is a test"
  }
}
EOF
cat main.tf
terraform apply
sed -i .bak '2,4d' main.tf
terraform apply
```
Also available as a [gist](https://gist.github.com/netjunki/666b99fac2445500fa66d2ee8033325c)

### Panic Output
1 error(s) occurred:

* null_resource.test: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.8.5
    Resource ID: null_resource.test
    Mismatch reason: diff RequiresNew; old: true, new: false
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"triggers.%":*terraform.ResourceAttrDiff{Old:"1", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "triggers.run_every_time":*terraform.ResourceAttrDiff{Old:"49d5760b-1822-d153-610a-eeacfcfc0d54", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{}, Destroy:false, DestroyDeposed:false, DestroyTainted:false}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

### Expected Behavior
Would expect the terraform script to run as usual and either run/not run the null resource again.

### Actual Behavior
Crash

**Comment by mitchellh** [comment]
Thank you for the perfect reproduction steps. Reproduced and taking a look now.

**Comment by mitchellh** [comment]
Fix is in referenced PR.

**Comment by netjunki** [comment]
Tested it out locally as well. Thanks so much! Looking forward to the next
release.

On Mon, Feb 6, 2017 at 5:48 PM, Mitchell Hashimoto <notifications@github.com
