### ISSUE TITLE
OpenStack volumes being mounted after the initial resource is created

### ISSUE THREAD

**Issue by JordanSussman** [hashicorp/terraform#11681]
### Terraform Version
Terraform v0.8.4

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2
- openstack_compute_volume_attach_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
resource "openstack_compute_instance_v2" "volume_server" {
  region = "${var.openstack_region}"
  name = "${var.volume_server_name}"
  image_name = "${var.image}"
  flavor_name = "${var.flavor}"
  key_pair = "${var.key_pair}"
  security_groups = ["${openstack_networking_secgroup_v2.<name>.name}"]
  floating_ip = "${var.volume_float}"
  network {
    name = "${openstack_networking_network_v2.<name>.name}"
    fixed_ip_v4 = "${var.volume_server_ip}"
  }

  provisioner "chef" {
    node_name = "${var.volume_server_name}"
    server_url = "https://company/organizations/${var.chef_org}"
    user_name = "${var.user_name}"
    user_key = "${file("~/.chef/${var.user_key}.pem")}"
    recreate_client = true
    environment = "${var.chef_environment}"
    run_list = ["role[volume-server]", "role[chef_client]"]
    version = "${var.chef_version}"
    vault_json = <<-EOF
    {
      "key": "value"
    }
    EOF

    connection {
      user = "${var.ssh_user}"
      private_key = "${file("${var.private_key}")}"
      timeout = "5m"
    }
  }
}

resource "openstack_compute_volume_attach_v2" "va_1" {
  instance_id = "${openstack_compute_instance_v2.volume_server.id}"
  volume_id = "${var.volume_server_volume}"
  device = "/dev/vdb"
}

resource "openstack_compute_volume_attach_v2" "va_2" {
  instance_id = "${openstack_compute_instance_v2.volume_server.id}"
  volume_id = "${var.volume_server_lvm}"
  device = "/dev/vdc"
}
```

### Expected Behavior
Terraform should mount the volumes during the initial creation of the openstack_compute_instance_v2 resource.

### Actual Behavior
Terraform is mounting the two volumes after the initial creation of openstack_compute_instance_v2 resource, thus allowing for the provisioner chef to be ran before the volumes are mounted.

I'm assuming that the volumes will be attached before the provisioner/connection resources are being executed. The expected behavior works when doing the attachment within the openstack_compute_instance_v2 resource.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Running in OpenStack RedHat Kilo

**Comment by jtopjian** [comment]
@JordanSussman Hi there!

Yes, this is expected. If you want the volumes to be attached during instance creation, look at the [`block_device`](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#block_device) argument. You can attach pre-existing volumes or have the instance create volumes on the fly.

I'm going to close this Issue, but do let me know if you have any other questions!
