### ISSUE TITLE
show --filter --format

### ISSUE THREAD

**Issue by ahammond** [hashicorp/terraform#11684]
I would like a clean way to get data out of `terraform show` for shell scripts and other hacks. I think the best pattern to follow is similar to the `docker images` command which supports `--format` and `--filter` options. https://docs.docker.com/engine/reference/commandline/images/ 

I didn't see such options for TF. Our use case is that we try to run ansible across our provisioned instances (small change so we'd rather just ansible it than taint && re-create hundreds of machines). We end up with a list of IPs for machines which couldn't be reached. If it's only a few, then just finding and nuking them in the cloud provider is fine. When there's more than a few, that's not fun, and worse provides lots of opportunities for human error. I ended up writing the following horrible hack to get a simple mapping of module to IP for our digital ocean nodes:

```bash
terraform show | perl -lane 'BEGIN {$n=""}; $n=$_ if m/module\.[^.]+\.digitalocean_droplet\.node\.\d+:/; $i=@F[2] if $n and m/ipv4_address/g; if ($n and $i) { print "$n$i"; $n=""; $i=""}'
# our ops guy is stuck doing the merge between our list of failed IPs and the above
```

This works for now, but I would much prefer to do something like:

```bash
while read ip module name; do
  if grep -qF "$ip" list_of_failed_ips; then
    terraform taint -module="$module" "$name"
  fi
done < $(terraform show --filter 'type=digitalocean_droplet' --format '{{ node.ipv4_address }} {{ node.module }} {{ node.name }})
```

**Comment by apparentlymart** [comment]
This is a cool idea, @ahammond!

Reminds me of something we discussed a little while ago, which has a similar goal but achieves it a different way:

```
terraform eval '${some-interpolation-expression}'
```

Your approach has the nice advantage of playing nicely with lists of things, by evaluating the format expression separately for each matched item.

Terraform already has the idea of "resource addressing" which provides the sort of thing you want to do with the `--filter` argument there, though notably I don't think it currently supports getting all of the resources of a given type... instead you'd need to say something like:

```
--target 'module.some-module.digitalocean_droplet.node'
```

This resource addressing scheme doesn't currently support wildcarding the module name, so this would permit only selecting from a single specified module.

For the format syntax, I think we would ideally use the same interpolation syntax we use elsewhere in Terraform. I guess it would behave similarly to how we evaluate interpolations inside provisioners, where you can use `self` to interpolate values from the current item, perhaps with an additional attribute to get resource metadata... perhaps `${show.address}`, `${show.module_address}` and `${show.local_address}`.

So putting that all together we'd end up with something like this:

```
terraform show \
    --target 'module.some-module.digitalocean_droplet.node' \
    --target 'module.some-other-module.digitalocean_droplet.node' \
    --expr '${self.ipv4_address} ${matched.module_address} ${self.name}'
```

Does that seem reasonable? Mainly just exploring how this could be built using existing Terraform features, so not suggesting it would work exactly like this but this general idea.

**Comment by mildwonkey** [comment]
Hi @ahammond!
Terraform 0.12 has a new option to `terraform show`: `-json`. This was designed as a machine-readable output that you can filter with whatever third-party tools or scripts that you prefer. 
While we might consider adding something like `-target` to terraform show in the future (there is already a feature request for this open), `terraform show -json` is the proper option for parsing the output of terraform show. Thanks!
