### ISSUE TITLE
Support disk snapshots operations for Google provider

### ISSUE THREAD

**Issue by Dnefedkin** [hashicorp/terraform#11690]
### Terraform Version
0.8.x and above

### Affected Resource(s)
- google_compute_snapshot

The proposal is to support ability to create disk snapshots via a new google_compute_snapshot resource and ability to retrieve snapshots for an existing disk via  a new google_compute_snapshot data source.

APIs:
- Snapshot creation - https://cloud.google.com/compute/docs/reference/latest/disks/createSnapshot
- Snapshot deletion - https://cloud.google.com/compute/docs/reference/latest/snapshots/delete
- getting information about a snapshot - https://cloud.google.com/compute/docs/reference/latest/snapshots/get
- getting a list of snapshots in the project -https://cloud.google.com/compute/docs/reference/latest/snapshots/list

**Comment by nodesocket** [comment]
I created an issue on how to create an instance disk from a snapshot https://github.com/hashicorp/terraform/issues/11770. Is this currently not possible?

**Comment by tpoindessous** [comment]
Hi

I proposed this PR https://github.com/hashicorp/terraform/pull/12482 , it adds snapshot's support for GCP.

**Comment by paddycarver** [comment]
#12482 has been merged! Thanks @tpoindessous for all the patience and hard work on this.

**Comment by madsonic** [comment]
is snapshot data source supported?
