### ISSUE TITLE
Bug in experimental feature failure

### ISSUE THREAD

**Issue by trungnguyen** [hashicorp/terraform#11701]
Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

You can report an issue at: https://github.com/hashicorp/terraform/issues

The failure was written to "terraform-error-1486230573.log". Please
double check this file contains no sensitive information and report
it with your issue.

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.

### The content of "terraform-error-1486230573.log"
2 error(s) occurred:

* apply operation: Unknown 'ValidateResource' shadow value for "aws_s3_bucket": &errors.errorString{s:"shadow closed"}
* apply operation: Diff "module.s3.aws_s3_bucket.pugin" had unequal states (real, then shadow):

&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{"tags":[]map[string]interface {}{map[string]interface {}{"Name":"pugin", "Account":"${module.account_alias.account_alias}", "LastChanged":"${timestamp()}"}}, "bucket":"${module.account_alias.account_alias}.pugin", "acl":"public-read", "website":[]map[string]interface {}{map[string]interface {}{"index_document":"index.html"}}}, Config:map[string]interface {}{"website":[]map[string]interface {}{map[string]interface {}{"index_document":"index.html"}}, "tags":[]map[string]interface {}{map[string]interface {}{"Account":"pdswebops", "LastChanged":"2017-02-04T17:49:29Z", "Name":"pugin"}}, "bucket":"pdswebops.pugin", "acl":"public-read"}, raw:(*config.RawConfig)(0xc420915c20)}

&terraform.ResourceConfig{ComputedKeys:[]string(nil), Raw:map[string]interface {}{"tags":[]map[string]interface {}{map[string]interface {}{"Name":"pugin", "Account":"${module.account_alias.account_alias}", "LastChanged":"${timestamp()}"}}, "bucket":"${module.account_alias.account_alias}.pugin", "acl":"public-read", "website":[]map[string]interface {}{map[string]interface {}{"index_document":"index.html"}}}, Config:map[string]interface {}{"acl":"public-read", "website":[]map[string]interface {}{map[string]interface {}{"index_document":"index.html"}}, "tags":[]map[string]interface {}{map[string]interface {}{"Name":"pugin", "Account":"pdswebops", "LastChanged":"2017-02-04T17:49:33Z"}}, "bucket":"pdswebops.pugin"}, raw:(*config.RawConfig)(0xc42058f260)}

### Terraform Version
0.8.5

### Affected Resource(s)
None

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by drags** [comment]
Not sure if the failure I received is similar enough to be included here or worth its own bug report, but figure I'll start by placing here in the interest of ticket cleanliness. Let me know if it should be in a separate issue.

## Contents of terraform-error-1487269323.log
```
$ cat terraform-error-1487269323.log
1 error(s) occurred:

* plan operation: Unknown 'ValidateResource' shadow value for "aws_route53_record": &errors.errorString{s:"shadow closed"}
```
