### ISSUE TITLE
Bad behavior on terraform openstack provider as attributed are not getting picked up

### ISSUE THREAD

**Issue by rhoml** [hashicorp/terraform#11711]
Hi there folks,

I am running terraform on v0.8.5 and I've noticed that unless I explicitly set OS_AUTH_URL, OS_USERNAME and OS_PASSWORD environment variables openstack terraform won't pick them up when I declare the openstack provider. 

Unless I am doing something wrong here I don't see the reason of this behavior thanks in advance

### Terraform Version
0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack provider

### Terraform Configuration Files
```hcl
provider "openstack" {
  user_name = "terraform"
  password = "pwd"
  tenant_name = "something"
  auth_url    = "https://xxx.xxx.com/v2.0"
}

terraform remote config -backend=swift -backend-config="path=terraform"
```

### Debug Output

```
missing either password or token configuration or OS_PASSWORD or OS_AUTH_TOKEN environment variable

If the error message above mentions requiring or modifying configuration
options, these are set using the `-backend-config` flag. Example:
-backend-config="name=foo" to set the `name` configuration
```

### Expected Behavior

`Initialized blank state with remote state enabled!`

### Actual Behavior

```
missing either password or token configuration or OS_PASSWORD or OS_AUTH_TOKEN environment variable

If the error message above mentions requiring or modifying configuration
options, these are set using the `-backend-config` flag. Example:
-backend-config="name=foo" to set the `name` configuration
```

**Comment by jtopjian** [comment]
@rhoml I believe this is due to using both an OpenStack resource _and_ the OpenStack Swift remote backend. Both require separate configuration and since Swift configuration is missing, it's falling back to asking for the environment variables.

Can you add a remote state configuration as described [here](https://www.terraform.io/docs/state/remote/swift.html) and let me know if that helps?

**Comment by rhoml** [comment]
Oh, that makes sense I'll test now

**Comment by rhoml** [comment]
@jtopjian you were absolutely right, it was asking for terraform-config vars not about the providers ones.

Thanks for giving me some light there
