### ISSUE TITLE
Volume Creation with different AZ in same region is wrong

### ISSUE THREAD

**Issue by sirajudheenam** [hashicorp/terraform#11714]
### Terraform Version
terraform -v
Terraform v0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_blockstorage_volume_v1

### Terraform Configuration Files
```hcl
variable "user_name" { default = "user_NAME" }
variable "tenant_name" { default = "Project_NAME" }
variable "domain_name" { default = "domain_NAME" }
variable "auth_url"    { default ="https://auth_URL:443/v3" }
variable "region" { default = "ap-au-1" }
variable "key_pair" { default = "Corporate_Key" }
variable "flavor" { default = "20" }
variable "security_group" { default = "default" }


provider "openstack"
{
  user_name   = "${var.user_name}"
  tenant_name = "${var.tenant_name}"
  domain_name = "${var.domain_name}"
  auth_url    = "${var.auth_url}"
}

resource "openstack_blockstorage_volume_v1" "volume_01"
{
 name = "terraform_volume1a"
 description = "terraform test01"
 size = 1 # in Giga Byte
 region = "ap-au-1"
 availability_zone = "ap-au-1a"
}
resource "openstack_blockstorage_volume_v1" "volume_02"
{
 name = "terraform_volume1b"
 description = "terraform test02"
 region = "ap-au-1"
 size = 1 # in Giga Byte
 availability_zone = "ap-au-1b"
}
```

### Debug Output

https://gist.github.com/sirajudheenam/00ddd017ba11171e6afb4e113b617ae4

### Expected Behavior
The config should have created a volume each in availability_zones `ap-au-1a` and `ap-au-1b` in the region `ap-au-1` as per config.

### Actual Behavior
It created both volumes in the availability zone `ap-au-1b`.
Openstack CLI and Dashboard is able to create volumes in different availability zone as intended.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have two different availability zones 
2. Replace your credentials in the config
3. `terraform plan`
4. `terraform apply`

### Important Factoids
None

### References
None

**Comment by jtopjian** [comment]
@sirajudheenam Thank you for reporting this! I think I see the problem... it might be an issue with the underlying API sending the parameter as [`Availability`](https://github.com/gophercloud/gophercloud/blob/master/openstack/blockstorage/v1/volumes/requests.go#L19) rather than `AvailabilityZone`.

By chance, does your OpenStack environment support Block Storage v2? You can easily test this by using the `openstack_blockstorage_volume_v2` resource instead of `openstack_blockstorage_volume_v1`. It looks like v2 is sending the right parameter.

**Comment by sirajudheenam** [comment]
yes, true. It happens only in `openstack_blockstorage_volume_v1`. It works as expected with `openstack_blockstorage_volume_v2`. Thanks @jtopjian for looking in to this. 👍

**Comment by jtopjian** [comment]
@sirajudheenam Great! I'll leave this opened until the underlying bug is fixed, but it's good to know that you have a workaround :)
