### ISSUE TITLE
Get Private IP of instance launched by autoscaling group

### ISSUE THREAD

**Issue by coolgooze** [hashicorp/terraform#11713]
ASG
resource "aws_autoscaling_group" "REDIS_ASG" {
    name = "${var.environment}-REDIS_ASG"
    launch_configuration = "${aws_launch_configuration.redis_launch_conf.name}"
    #availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]
    vpc_zone_identifier = ["${data.aws_subnet.PrivateDBSubnetAZ1.id}","${data.aws_subnet.PrivateDBSubnetAZ2.id}","${data.aws_subnet.PrivateDBSubnetAZ3.id}"]
    min_size = 1
    max_size = 1
    desired_capacity = 1
    health_check_grace_period = 600
    health_check_type = "EC2"   
    force_delete = "false"
    termination_policies = ["OldestInstance"]
    tag {
    key                 = "Name"
    value               = "${var.environment}-int-redis"
    propagate_at_launch = true
     }
}

i am trying to create a A Record
resource "aws_route53_record" "redis" {
  zone_id = "${data.aws_route53_zone.dns.zone_id}"
  name = "redis-${var.environment}.${data.aws_route53_zone.dns.name}"
  type = "A"
  ttl = "60"
  records = ["${aws_autoscaling_group.REDIS_ASG.private_ip}"]
}

Output- 
* Resource 'aws_autoscaling_group.REDIS_ASG' does not have attribute 'private_ip' for variable 'aws_autoscaling_group.REDIS_ASG.private_ip'

**Comment by coolgooze** [comment]
This is currently a blocker, can you please raise a PR

**Comment by insidepacket** [comment]
Looks like that there have been a FR for this
Feature Request: IDs & IPs for autoscaling group instances #8400

**Comment by igoratencompass** [comment]
Very useful, will provide same functionality as CloudFormation does. We can simply wait for ASG to finish creating all instances and report back with private ip's, instance id's etc. so we can have further actions follow in terraform like creating dns records for the instances etc.
