### ISSUE TITLE
Odd error - Error Getting CloudWatch Logs Tag List: %s

### ISSUE THREAD

**Issue by cultavix** [hashicorp/terraform#11712]
Good morning,

After upgrading from 0.8.4 to 0.8.5 everything is fine, except the following error. 

### Terraform Version
`0.8.5`
Note: With Terragrunt 0.9.9

### Affected Resource(s)
`aws_cloudwatch_log_group`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
resource "aws_cloudwatch_log_group" "cloudtrail" {
  name              = "cloudtrail"
  retention_in_days = 90
}
```

### Expected Behavior
It should just want to create a log grup called "cloudtrail" in AWS CloudWatch. (it's just a plan)

### Actual Behavior
It errors out with:
`* aws_cloudwatch_log_group.cloudtrail: Error Getting CloudWatch Logs Tag List: %s`

### Steps to Reproduce
`terraform init-no-refresh`
`terraform plan`

### Important Factoids
IAM permissions are generic, `arn:aws:iam:aws:policy/ReadOnlyAccess`

If I run using full AWS permissions, it works fine. (even with init-no-refresh).

Nothing has changed except Terraform and Terragrunt versions.

**Comment by cultavix** [comment]
I've traced the issue to Terragrunt changes. Closing. (sorry!)

**Comment by chhuang0123** [comment]
0.8.6 also has this issue.

**Comment by cultavix** [comment]
Yep, still there.

**Comment by st33v** [comment]
Same here but using the 'arn:aws-us-gov:iam:aws:policy/AdministratorAccess' policy.

**Comment by okzk** [comment]
In my workaround, add the "logs:ListTagsLogGroup" permission, then it works fine.
(I think the ReadOnlyAccess permissons should include this permission...)

**Comment by cultavix** [comment]
@okzk Thanks, I'll try adding that. I can see the ReadOnly policy only includes:
 ```        
"logs:Describe*",
"logs:Get*",
"logs:FilterLogEvents",
"logs:TestMetricFilter",
```

I'll come back with feedback.

**Comment by stack72** [comment]
Hi @cultavix 

Thanks for the issue report here - it looks like the specific error has been updated to not try and force a string

Please do let me know if you still get the same error going forward

Thanks

Paul
