### ISSUE TITLE
Support Kinesis Firehose Data Transformation

### ISSUE THREAD

**Issue by mlimaloureiro** [hashicorp/terraform#11723]
Hi Guys,

I would like to request Terraform to support `Kinesis Firehose` data transformation.

More info here

https://aws.amazon.com/about-aws/whats-new/2016/12/amazon-kinesis-firehose-can-now-prepare-and-transform-streaming-data-before-loading-it-to-data-stores/ 

Thanks!

**Comment by slajax** [comment]
I *really* need this to. Can anyone advise on where to start? I can take a stab at it.

**Comment by alessandroben** [comment]
I need this too. Could anyone answer that topic and give some visibility around that implementation? 
On IoT scenario it's a must have inside Terraform to suite all the needs of ETL without implementing complicated work-arounds.

**Comment by slajax** [comment]
It looks like AWS API doesn't support it yet.

**Comment by mdlavin** [comment]
It seems like the AWS Go library for Kinesis does have some concept of defining a Processor to handle transformations. Checkout the `ExtendedS3DestinationConfiguration` type in the [Go Kinesis documentation](https://docs.aws.amazon.com/sdk-for-go/api/service/firehose/) for an example type that allows defining a processor. That type includes a `ProcessingConfiguration` subtype and it looks like other Kinesis targets also allow that sort of configuration
