### ISSUE TITLE
Migrating Openstack Volumes from v1 to v2

### ISSUE THREAD

**Issue by afritzler** [hashicorp/terraform#11738]
Hi,

I have created a machine in Openstack using the v1 volume API. Moving to a newer terraform version I was thinking of migrating the whole thing to v2. Is there an elegant way to do that without losing the old disk content?

Regards,
Andreas

**Comment by jtopjian** [comment]
@afritzler There are two ways you can do this. The first is by editing the Terraform state file and replacing the existing v1-based volumes with the v2 equivalent attributes. The second way is to remove the v1 volumes from your state file and then import the v2-based volumes:

```
$ terraform import openstack_blockstorage_volume_v2.volume_1 <vol id>
```

The v1 and v2 docs list all of the attributes for each:

* [`openstack_blockstorage_volume_v1`](https://www.terraform.io/docs/providers/openstack/r/blockstorage_volume_v1.html)
* [`openstack_blockstorage_volume_v2`](https://www.terraform.io/docs/providers/openstack/r/blockstorage_volume_v2.html)

**Comment by afritzler** [comment]
Thanks a lot @jtopjian! I will give it a try.

**Comment by jtopjian** [comment]
@afritzler I'm going to close this Issue, but let me know if you ran into any problems with this. :)
