### ISSUE TITLE
azurerm_route does not delete routes associated with the table when removed

### ISSUE THREAD

**Issue by geofffranks** [hashicorp/terraform#11747]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

terraform v0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- awsrm_route

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "azurerm_route_table" "external" {
    name = "${var.resource_group_name}-external"
    location = "${var.azure_region}"
    resource_group_name = "${azurerm_resource_group.default.name}"

    route {
        name = "internet"
        address_prefix = "0.0.0.0/0"
        next_hop_type = "internet"
    }
}
```

### Expected Behavior
When removing the route from the above definition, terraform should remove the route from the routing table in Azure.

### Actual Behavior

Terraform says nothing will change during plan or apply phases

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Deploy above route table in sample config
2. Delete the route from the config
3. terraform plan + apply

**Comment by rrudduck** [comment]
I'm wondering if this has something to do with the route type. I added an acceptance test that verifies removal of a route (going from 2 to 1) in the config does in fact remove the route. I'll try checking your specific example.
