### ISSUE TITLE
Tearing down infrastructure destroys resources out of order - DeleteConflict: Cannot delete entity, must delete policies first

### ISSUE THREAD

**Issue by samuelkdavis** [hashicorp/terraform#11749]
### Terraform Version
terraform version 0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_iam_role
- aws_iam_role_policy
- aws_s3_bucket_object
- aws_lambda_function
- aws_lambda_permission

### Terraform Configuration Files
Folder structure:
![image](https://cloud.githubusercontent.com/assets/6887841/22704559/03425a94-edcd-11e6-97cd-ff1002af1be0.png)

application/infra/main.tf
```hcl
variable region {
}

variable env {
}

variable application {
}

variable unpublished_version {
}

variable fully_qualified_component_name {
}

module "component" {
    source = "../../infra"
    region="${var.region}"
    env="${var.env}"
    application="${var.application}"
    fully_qualified_component_name="${var.fully_qualified_component_name}"
    version="${var.unpublished_version}"
}
```

application/vars.tfvars

```hcl
account_id="12345"
region="ap-southeast-2"
env="dev"
application="ede6529e082a"
unpublished_version="0.0.3_1.gitcommit"
fully_qualified_component_name="component-api"
```
destroy/infra/main.tf

<empty>

Infra/main.tf

```hcl
variable component_name {
  default = "component"
}

variable region {
}

variable env {
}


variable version {
}

variable fully_qualified_component_name {
}

variable application {
}

resource "aws_iam_role" "execution_role" {
  name = "${var.component_name}-${var.application}-${var.env}"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": [
            "lambda.amazonaws.com",
            "apigateway.amazonaws.com"
        ]
      }
    }
  ]
}
  EOF
}

resource "aws_iam_role_policy" "execution" {
  depends_on = ["aws_iam_role.execution_role"]
  name   = "${var.component_name}-${var.application}-${var.env}"
  role   = "${aws_iam_role.execution_role.id}"
  policy= <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
      {
          "Effect": "Allow",
          "Action": [
              "lambda:GetFunctionConfiguration",
              "lambda:InvokeFunction"
          ],
          "Resource": "arn:aws:lambda:*:*:*:*"
      },
      {
          "Effect": "Allow",
          "Action": [
              "s3:GetObject"
          ],
          "Resource": "arn:aws:s3:::*"
      }
  ]
}
  EOF
}

data "aws_s3_bucket_object" "lambda_package" {
  bucket = "repos-billing-platform"
  key = "${var.fully_qualified_component_name}/${var.version}.zip"
}

resource "aws_lambda_function" "lambda_function" {
  function_name     = "${var.component_name}-${var.application}-${var.env}"
  description       = "description"
  role              = "${aws_iam_role.execution_role.arn}"
  handler           = "src/lambdas/Comp.handler"
  runtime           = "nodejs4.3"
  timeout           = 30
  s3_bucket         = "${data.aws_s3_bucket_object.lambda_package.bucket}"
  s3_key            = "${data.aws_s3_bucket_object.lambda_package.key}"
  s3_object_version = "${data.aws_s3_bucket_object.lambda_package.version_id}"
}

resource "aws_lambda_permission" "lambda_api_permission" {
  depends_on = ["aws_lambda_function.lambda_function"]
  statement_id  = "${var.component_name}-${var.env}-Lambda-AllowApiExecution"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.lambda_function.arn}"
  principal     = "apigateway.amazonaws.com"
}

```

### Expected Behavior
Running the following commands should set up and tear down the infrastructure:
terraform get -update=true ./application/infra
terraform apply -parallelism=1 -var-file=./application/vars.tfvars ./application/infra
terraform apply -parallelism=1 -var-file=./destroy/vars.tfvars ./destroy/infra

### Actual Behavior
The creation of terraform works as expected, but the destruction happens out of order
![image](https://cloud.githubusercontent.com/assets/6887841/22704541/f1b3108e-edcc-11e6-84ff-434781a85272.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform get -update=true ./application/infra
2. terraform apply -parallelism=1 -var-file=./application/vars.tfvars ./application/infra
3. terraform apply -parallelism=1 ./destroy/infra

### Important Factoids
Setting up and tearing down infra/main.tf directly seems to work, while calling application/infra/main.tf which references infra/main.tf is where the teardown breaks.

**Comment by samuelkdavis** [comment]
This had no issue in terraform 0.7.3, it only started occurring when updating to 0.8.5

**Comment by mitchellh** [comment]
Reproduced.

**Comment by mitchellh** [comment]
Have a fix in referenced PR.

**Comment by samuelkdavis** [comment]
Here's a bug which was exposed by 11749 - Add a cloudwatch log group & subscription filter to this code and you run into a corrupted state (can no longer run terraform apply, or terraform destroy on).

The bug has existed since <0.7.3 but likely hasn't come up due to there being so many permutations of resources being manually deleted/partially destroyed.

https://github.com/hashicorp/terraform/issues/11750
