### ISSUE TITLE
Terraform apply usage output, parallelism flag - Concurrency isn't Parallelism 

### ISSUE THREAD

**Issue by YahiaSweid** [hashicorp/terraform#11766]
Hi

### Terraform Version
0.8.5

### Expected Behavior
`parallelism` flag should be replaced with `concurrency` or something else that declares the process is concurrent.

### Actual Behavior
```
-parallelism=n         Limit the number of concurrent operations.
                         Defaults to 10.

```
### Steps to Reproduce
1. `terraform apply --help`

### References
@robpike https://blog.golang.org/concurrency-is-not-parallelism

**Comment by mitchellh** [comment]
Parallelism is the right word here. Its limiting the theoretical maximum parallel operations. If you have less cores than "n" then parallelism might be lower, but Terraform will never even attempt more than n. 

Fixing it now.

**Comment by seglo** [comment]
@mitchellh @ysweid Does this mean terraform parallelism is limited to the number of cores on the system?  Most modern systems can support many more _concurrent_ operations than the number of cores.  Why not terraform?
