### ISSUE TITLE
Rancher Provider Support for Catalog Id

### ISSUE THREAD

**Issue by goffinf** [hashicorp/terraform#11769]
Provider: Rancher
Resource: rancher_environment

New feature request.

The rancher provider currently supports the creation on a Rancher environment by name using the rancher_environment resource and the creation of service 'stacks' via the the rancher_stack resource. The latest version of Rancher has introduced environment templates which enable specification of the stacks that should be included in an environment when it is created.

Requirement is to pass a template id input property to the rancher_environment resource and thereby allow creation of both the environment and the stacks defined in the template.

**Comment by johnrengelman** [comment]
This is going to require supporting Rancher's `v2` API and I'm looking for some direction from the Terraform team on the best way to proceed.

Here are the option as I see it from:
https://github.com/hashicorp/terraform/pull/11545#issuecomment-278086896

1. Create a new rancher-v2 provider
1. Create resources that specify the version - i.e. rancher_stack_v2.foo vs rancher_stack.foo
1. Provide a configuration option on which API version to use and then only allow some resources to be created with the v2 API.
1. Try to transparently detect the API version under the covers - i.e. try the v2-beta api and use it if it works.

I wasn't able to find any examples of an API change in other resources but I'm sure there are some.
What's the preferred way of handling this in Terraform?

/cc @raphink @stack72

**Comment by raphink** [comment]
I agree this needs to be done. I'm willing to contribute once we decide which way to take.
