### ISSUE TITLE
Create Google Cloud Compute instance disk from snapshot

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#11770]
How can I create a Google Cloud Compute Instance disk from a snapshot instead of image? I tried:

````
disk {
        type = "pd-ssd"
        image = "blog-2017-02-08"
        auto_delete = true
        size = 10
}
````

This errors saying image does not exist. I also tried:

````
disk {
        type = "pd-ssd"
        snapshot = "blog-2017-02-08"
        auto_delete = true
        size = 10
}
````

This fails with `* google_compute_instance.blog: disk.0: invalid or unknown key: snapshot`.

**Comment by nodesocket** [comment]
I think I found a possible solution by creating a disk separately, but I think I may have found a race-condition or bug now.

````
resource "google_compute_disk" "blog" {
    name  = "blog"
    type  = "pd-ssd"
    zone  = "us-west1-a"
    snapshot = "blog-2017-02-08"
    size = 10
}
````

````
resource "google_compute_instance" "blog" {
    name = "blog"
    machine_type = "f1-micro"
    zone = "us-west1-a"

    tags = ["http"]

    disk {
        disk = "blog"
        auto_delete = true
    }

    network_interface {
        network = "default"
        access_config {
        }
    }

    metadata {
    }

    service_account {
        scopes = ["userinfo-email", "compute-ro", "storage-ro"]
    }

    scheduling {
        preemptible = false
        on_host_maintenance = "MIGRATE"
        automatic_restart = true
    }
}
````

However this consistently errors when creating the compute instance with:

    * google_compute_instance.blog: Error loading disk 'blog': googleapi: Error 404: The resource 'projects/elastic-byte/zones/us-west1-a/disks/blog' was not found, notFound

The disk is created in my Google Cloud project, but the instance is not.

**Comment by nodesocket** [comment]
I found the answer. The problem was related to hard coding `disk = "blog"`. You need to reference the Terraform disk so Terraform can resolve dependencies properly.

````
resource "google_compute_disk" "blog" {
    name  = "blog"
    type  = "pd-ssd"
    zone  = "us-west1-a"
    snapshot = "blog-2017-02-08-1"
    size = 10
}
````

Then for the VM instance:

````
disk {
   disk = "${google_compute_disk.blog.name}"
    auto_delete = true
}
````

**Comment by bbecomp99** [comment]
Thank you, here is a bit more on this topic: 

This bit shows you how to deploy from template with count index, its basically a GCP scale set. 

resource "google_compute_address" "static-ip-address" {
  count = "${var.node_count}"
  name = "prdwebe1-static-ip-${count.index + 1}"
  region = "us-central1"
}

resource "google_compute_disk" "fxprdwebe1" {
    count = "${var.node_count}"
    name  = "prdwebe4${count.index}-boot"
    type  = "pd-ssd"
    zone  = "us-central1-a"
    snapshot = "snap1"
    size = 17

}

resource "google_compute_instance" "fxprdwebe1" {
  count = "${var.node_count}"
  name = "prdwebe1${count.index}"
  machine_type = "n1-highmem-4"
  zone = "us-central1-a"
  allow_stopping_for_update = true

          boot_disk {
               
                  source      = "${element(google_compute_disk.fxprdwebe1.*.self_link, count.index)}"
                  device_name = "${element(google_compute_disk.fxprdwebe1.*.name, count.index)}"
            
                }

network_interface {
  network = "default"
  access_config {
    nat_ip = "${element(google_compute_address.static-ip-address.*.address, count.index)}"
  }

}

	metadata = {
    	sshKeys = "${var.ssh_user}:${file("${var.public_key}")}"
  	}

    	connection {
	  	type = "ssh"
	  	user = "${var.ssh_user}"
    	host = "${google_compute_instance.default.network_interface.0.access_config.0.nat_ip}" 
  		private_key = "${file("${var.private_key}")}"
	}


}
