### ISSUE TITLE
DynamoDB item creation using a aws_dynamodb_table_item resource

### ISSUE THREAD

**Issue by drieselliott** [hashicorp/terraform#11773]
Hi,

It would be nice to have a 'aws_dynamodb_table_item' resource that allows you to write configuration entries to DynamoDB tables when provisioning an environment. It should support both the DynamoDB JSON and the normal JSON format.

```hcl
resource "aws_dynamodb_table_item" "configuration_item" {
    table = "${aws_dynamodb_table.configuration_table.name}"
    format = "json"
    item = <<EOF
       //Some JSON content
EOF
}
```

table: The table name
format: Either 'json' or 'dynamodb' for 'normal json' or 'dynamodb json'
item: The item to insert into the table (either as inline content or template)

This is very useful in serverless applications that use DynamoDb as their configuration store and Terraform to provision everything. Otherwise you need to rely on a separate non-terraform script to upload your configuration entries.

Thanks for considering this.

Dries

**Comment by MikeMcMahon** [comment]
it would be great to have a dynodb data provider as well, as it would be nice to grab configuration elements for terraform from dynamodb

**Comment by ccgagnon** [comment]
+1 having the possibility to add table items could be very useful.
