### ISSUE TITLE
provider/aws: db_instance - Encrypted read-replica in a different region

### ISSUE THREAD

**Issue by gdowmont** [hashicorp/terraform#11784]
Hi,

It would be great if terraform supported creating encrypted RDS read-replicas in a different region than the parent instance inside the same/different account. AWS have recently added support for it and Go AWS SDK has been extended to include that functionality via 'DestinationRegion' [https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceReadReplicaInput](url).

This is very useful if you need to keep real-time backups away from your main region or in a different account.

Thanks for considering this.

Greg

**Comment by JoshiiSinfield** [comment]
The following states https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#RDS.CreateDBInstanceReadReplica

> To create an encrypted Read Replica in another AWS Region, you must provide the following values:
> 
> * KmsKeyId - The AWS Key Management System (KMS) key identifier for the
> key to use to encrypt the Read Replica in the destination region.
> 
> * PreSignedUrl - A URL that contains a Signature Version 4 signed request
> for the  CreateDBInstanceReadReplica API action in the AWS region that
> contains the source DB instance. The PreSignedUrl parameter must be used
> when encrypting a Read Replica from another AWS region.
> The presigned URL must be a valid request for the CreateDBInstanceReadReplica
> 
> API action that can be executed in the source region that contains the
> encrypted DB instance. The presigned URL request must contain the following
> parameter values:
> DestinationRegion - The AWS Region that the Read Replica is created in. This
> 
>  region is the same one where the CreateDBInstanceReadReplica action is
>  called that contains this presigned URL.
> 
> For example, if you create an encrypted Read Replica in the us-east-1 region,
>  and the source DB instance is in the west-2 region, then you call the
>  CreateDBInstanceReadReplica action in the us-east-1 region and provide
>  a presigned URL that contains a call to the CreateDBInstanceReadReplica
>  action in the us-west-2 region. For this example, the DestinationRegion
>  in the presigned URL must be set to the us-east-1 region.
> KmsKeyId - The KMS key identifier for the key to use to encrypt the Read
> 
> Replica in the destination region. This is the same identifier for both
> the CreateDBInstanceReadReplica action that is called in the destination
> region, and the action contained in the presigned URL.
> SourceDBInstanceIdentifier - The DB instance identifier for the encrypted
> 
> Read Replica to be created. This identifier must be in the Amazon Resource
> Name (ARN) format for the source region. For example, if you create an
> encrypted Read Replica from a DB instance in the us-west-2 region, then
> your SourceDBInstanceIdentifier would look like this example:  arn:aws:rds:us-west-2:123456789012:instance:mysql-instance1-instance-20161115.

**Comment by yfronto** [comment]
+1 on supporting this. Currently, I create a cross-region read replica manually, and then import the existing component.

Ideally, my instance module could include replicas:

```
resource "aws_db_instance" "main" {
...
  kms_key_id = "${var.kms_key_id}
  storage_encrypted = true
...
}

resource "aws_db_instance" "replica" {
...
  replicate_source_db = "${aws_db_instance.my-db.arn}"
  kms_key_id = "${var.kms_key_id}"
  storage_encrypted = true
...
}
```

**Comment by akitekt** [comment]
+1 on supporting this. This is the only piece we have to do manually right now.

**Comment by akitekt** [comment]
Hi @JoshiiSinfield,
Is this PR ready to be used? https://github.com/JoshiiSinfield/terraform/commit/fe91d70ca3f4e8b98b109a26ef18ff9c3252529a

Thanks, Eric
