### ISSUE TITLE
Terraform hangs an "Unrecognized remote plugin message"

### ISSUE THREAD

**Issue by grayaii** [hashicorp/terraform#11780]
### Terraform Version
`Terraform v0.8.5`
I am on OSX El Capitan

### Affected Resource(s)
Please list the resources as a list, for example:
- Currently Unknown.  The error indicates terraform is having a hard time with a plugin.  This plugin wored with 0.6.X
- I believe the plugin is: terraform-provider-spotinst
- We are upgrading from 0.6.X to v0.8.5 and we just hit this.

### Terraform Configuration Files
- Unknown at this time.  I suspect the issue is not with the configuration, but with a plugin.

### Debug Output
I used TRACE:
https://gist.github.com/grayaii/27b925cd932e15f5525de44e08f4f3f9

### Expected Behavior
Terraform should have exited with error.

### Actual Behavior
Terraform hangs indefinitely.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`terraform apply`

`[empire] Errors:
[empire]
[empire]   * Unrecognized remote plugin message: 2|unix|/var/folders/4l/7x7cm58n5f1cskskv5rt0pvh0000gp/T/tf-plugin505557682
[empire]
[empire] This usually means that the plugin is either invalid or simply
[empire] needs to be recompiled to support the latest protocol.`

That file is 0 bytes, which is strange.

### Important Factoids
I will investigate this today and add more relevant data, but I thought you guys should know sooner rather than later, since I noticed you take terraform hangs seriously and prioritize them rather highly.

**Comment by grayaii** [comment]
I figured out the issue.
Terraform v0.8.5 does indeed hang when using a wrong version of a provider.

This works with terraform v0.8.5:
https://s3.amazonaws.com/spotinst-terraform/v0.8.5/darwin_amd64/terraform-provider-spotinst

These cause terraform v0.8.5 to hang:
https://s3.amazonaws.com/spotinst-terraform/v0.6.16/darwin_amd64/terraform-provider-spotinst
https://s3.amazonaws.com/spotinst-terraform/v0.9.0/darwin_amd64/terraform-provider-spotinst

This is the link where customers can download this provider:
http://blog.spotinst.com/2016/02/29/spotinst-terraform-getting-started/

Ideally terraform should just error out.

**Comment by mitchellh** [comment]
On master I'm not getting a hang, it is exiting properly:

```
test → terraform apply -input=false
1 error(s) occurred:

* provider.spotinst: Unrecognized remote plugin message: 2|unix|/var/folders/gh/ts3cxwpd7l9cwb2n5z8j51980000gn/T/tf-plugin865801278

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

I don't think we changed anything to make this the case so maybe I'm missing some step. If you have any more information please let me know.
