### ISSUE TITLE
aws_directory_service_directory doesnt wait long enough

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#11781]
creating a aws_directory_service_directory (Type=microsoft) doesnt wait long enough for the resource to be created. Sometimes its notoriously slow. I believe the wait time is around 25/30m currently, but sometimes it takes longer - should up it to 60 I think

Terraform 0.8.4

**Comment by stack72** [comment]
Hi @gtmtech 

I just opened a PR for this - i am waiting on the tests to run right now

Paul
