### ISSUE TITLE
Data source - return "null" if the source does not have the specified value

### ISSUE THREAD

**Issue by w32-blaster** [hashicorp/terraform#11782]
I'm trying to solve a problem where a cloudformation stack output value is used. 
I'm getting a key does not exist using the aws_cloudformation_stack data source which is expected because the specified key is not set in the CF template. 

I'm wondering if it would make sense in general in all data sources to return a null value or empty string if the key does not exist in the source, so we can handle this situation using the function `coalesce` to return a default value. 
That would allow us to set a default value like in a variable and use that instead. Or going back to my original problem, we would be able to return a default cloudformation output if the first key does not return anything.

**Comment by apparentlymart** [comment]
Hi @w32-blaster! Thanks for this feature request.

I'd like to try to understand better what you're dealing with here. I *think* you are trying to retrieve the outputs of a cloudformation stack using the `aws_cloudformation_stack` data source, doing something like this:

```hcl
data "aws_cloudformation_stack" "example" {
  name = "some-example-stack"
}

resource "something_else" "example" {
  some_attribute = "${data.aws_cloudformation_stack.example.outputs["foobarbaz"]}"
}
```

The above would fail if the map retrieved from the Cloudformation API did not include an output named "foobarbaz".

I think this issue could be avoided by using the `lookup` function, which is similar to the indexing syntax `map[key]` but allows a default to be provided to use in the event that the given key is not in the map:

```hcl
resource "something_else" "example" {
  some_attribute = "${lookup(data.aws_cloudformation_stack.example.outputs, "foobarbaz", "default-foobarbaz")}"
}
```

Does that help you achieve the result you were looking for here, or is there something different going on?

**Comment by w32-blaster** [comment]
OK, somehow I didn't get that the `outputs` is a map. It make sense to use lookup to set a fallback/default in this case.  Thanks for the suggestion 👍

**Comment by apparentlymart** [comment]
Great, @w32-blaster! I'm glad that works for you.

I'm going to close this issue, since it seems like this will be a workable approach for you.

**Comment by jobmiller** [comment]
I'm wondering how I can get around an empty datasource also.   My issue seems slightly different.  
The data source is empty initially, before the template starts running, so it fails:

${lookup(data.oci_core_subnets.sub.subnets[count.index],"id","dummy")}
* oci_core_instance.TFInstance[0]: At column 43, line 1: list "data.oci_core_subnets.sub.subnets" does not have any elements so cannot determine type. in:

however, if the template just started running (or was run previously), this wouldn't be empty.

**Comment by RoryHolland** [comment]
Is anyone using a workaround for this?
