### ISSUE TITLE
Terraform crash during plan

### ISSUE THREAD

**Issue by nhuray** [hashicorp/terraform#11799]
Hi there,

Terraform crashes on plan. I didn't do anything in particular. 

### Terraform Version

I tried with different versions of Terraform in order to isolate the issue. It seems it works well with version `0.7.13` but failed with version `0.8.0`.

### Affected Resource(s)

This occurred when I run `plan`command to create a `mysql_database` resource.

### Terraform Configuration Files

```hcl
# RDS state
# ---------------------------------
data "terraform_remote_state" "rds" {
  backend = "s3"
  config {
    bucket = "bit-terraform"
    key    = "database/${var.environment_name}/database/rds.tfstate"
    region = "us-east-1"
  }
}

# MySQL provider
# ---------------------------------
provider "mysql" {
  endpoint = "${data.terraform_remote_state.rds.rds_mysql_endpoint}"
  username = "${data.terraform_remote_state.rds.rds_mysql_master_username}"
  password = "${data.terraform_remote_state.rds.rds_mysql_master_password}"
}

# MySQL database
# ---------------------------------
resource "mysql_database" "test" {
  name = "test"
}
```

### Panic Output

[Panic Log](https://gist.github.com/nhuray/cebac2f987919b34894ee4c6f020ee35)

### Expected Behavior

Plan properly the `mysql_database` resource

### Actual Behavior

Terraform crash

### Important Factoids

It seems when we hardcode the `endpoint`, `username` and `password` in the `mysql` provider, the `plan` command run correctly.

So it seems related to the `terraform_state` and the `mysql` provider, but the state exists and the path is the good one.

**Comment by nocode99** [comment]
Happens on 0.8.5 and 0.8.6.  It happens for both `mysql_database` and `mysql_user` resources.

**Comment by nhuray** [comment]
Do we have a plan to fix this soon ? I can help if needed...

**Comment by fillup** [comment]
Glad to see this reported already, I'm crashing for `mysql_user` and `mysql_grant` resources using terraform `0.8.6`.

**Comment by nhuray** [comment]
Still exists in 0.8.8 :(

**Comment by nabilnathani10** [comment]
Has this been fixed?

**Comment by nabilnathani10** [comment]
any word on this issue? Got this error today
