### ISSUE TITLE
Use golang.org/x/crypto/ssh

### ISSUE THREAD

**Issue by tv42** [hashicorp/terraform#1179]
```
perl -pi -e 's{code.google.com/p/go.crypto/ssh}{golang.org/x/crypto/ssh}' helper/ssh/*.go
```

**Comment by phinze** [comment]
Good catch - Thanks! If only GitHub issues could just automatically convert perl find/replaces into a PR for us... :grinning: 

Sounds like a good idea for some SaaS startup, doesn't it? Well, in the meantime... here's #1184
