### ISSUE TITLE
Terraform 0.8.6 crash while uploading

### ISSUE THREAD

**Issue by xinzhao0924** [hashicorp/terraform#11801]
[crash.zip](https://github.com/hashicorp/terraform/files/762087/crash.zip)

### Terraform Version
Terraform v0.8.6

### OS Version
Linux  2.6.18-406.el5

### SSH Version
OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5

resource "aws_instance" "unix_master" {

    connection {
        user = 
        private_key = 
        agent = false
    }

    provisioner "file" {
        source = 
        destination = 
    }
}

source is a file with size of more than 2.5 G.
Everything works fine if I use Terraform 0.6.16

**Comment by xinzhao0924** [comment]
Sometimes, it give error instead of crash:

Error applying plan:

1 error(s) occurred:

* Upload failed: ssh: disconnect, reason 2: Invalid ssh2 packet type: 226

**Comment by xinzhao0924** [comment]
Some more observations:

1. Issue happens only with that particular large file.

2. Issue doesn't happen with 0.8.4 but happen with 0.8.5

**Comment by jbardin** [comment]
There was some recent work done in the x/crypto/ssh package which may be to blame. We can try updating or rolling back that dependency.
