### ISSUE TITLE
template_file + LC + ASG Cycle: module

### ISSUE THREAD

**Issue by kuthz** [hashicorp/terraform#11808]
Hi,

I got a cycle issue when referencing template_file + LC module + ASG module with the version 0.8.6. This was working with version 0.7.x

`* Cycle: module.lc.output.id, module.asg.var.launch_configuration_id, module.lc.aws_launch_configuration.default (destroy), module.lc.output.name, module.asg.var.name, module.asg.aws_autoscaling_group.default, module.asg.aws_autoscaling_group.default (destroy)`

## Step to reproduce
I made a github repo to reproduce the case
https://github.com/kuthz/terraform-issue/tree/master/0.8.6

You probably need to adjust the file variables.tf to fit subnet + security group. The plan is working but not the apply.

`terraform get`
`terraform plan`
`terraform apply`
Change the value for the var test in the `data "template_file" "userdata"` from main.tf
`terraform apply`

The cycle error will appear. 

## Normal behavior
Normally this should create a new LC + ASG first and destroy the old one. This allow deployment without interruption.

Thanks

**Comment by jbardin** [comment]
Hi @kuthz,

Thanks for the complete reproduction case!

I've confirmed the bug in 0.8.6, but this is fixed in master by #11753, and will be in the 0.9 release.

**Comment by kuthz** [comment]
Thx for the quick follow up on this. Do you think this will be back ported to 0.8.x?

**Comment by jbardin** [comment]
@kuthz: Sorry, I missed that it was also backported. It will be in the next 0.8 release too.
