### ISSUE TITLE
Missing Delete Action for Chef Environment Provider

### ISSUE THREAD

**Issue by rb1whitney** [hashicorp/terraform#11805]
I am requesting that we add the missing delete function for chef_environment. Per the code in: https://github.com/hashicorp/terraform/blob/master/vendor/github.com/go-chef/chef/environment.go, there is mention of a delete function. Is it possible to have this missing feature implemented? When you provision a chef_environment with chef nodes, the chef environment sticks around and causes issues if the environment is re-created. I was able to monkey patch this issue locally by just copying the logic from client.go and renaming client to environment (to hit the right rest api for chef) and would like to see it fixed in future versions if possible.

### Terraform Version
0.8.6

### Affected Resource(s)
Please list the resources as a list, for example:
- chef_environment

### Expected Behavior
Chef Environment should be able to delete resource when calling terraform destroy

### Actual Behavior
Nothing happens since chef_environment is missing a delete function

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
0. `terraform apply`
1. `terraform destroy`

### References
None

**Comment by thebrianlopez** [comment]
+1

**Comment by mengesb** [comment]
I'm using terraform 0.9.2; the environment deletes on destroy...

```
~/tf_kesha $ terraform state show chef_environment.cheffy|grep -E '^(id|name)'
id                                          = kesha
name                                        = kesha
~/tf_kesha $ knife environment list | grep kesha
kesha
~/tf_kesha $ terraform destroy -force
chef_environment.cheffy: Refreshing state... (ID: kesha)
chef_environment.cheffy: Destroying... (ID: kesha)
chef_environment.cheffy: Destruction complete
Destroy complete! Resources: ... destroyed.
~/tf_kesha $ knife environment list | grep kesha ; echo $?
1
```

The above is sanitized, but I clearly destroyed the env that this plan manages. I haven't tried 0.8.6, however I don't recall this ever breaking when I was on 0.8.x versions of terraform.
