### ISSUE TITLE
Iterate over all elements of the map, or another way to create unique resource name.

### ISSUE THREAD

**Issue by wawrzek** [hashicorp/terraform#11813]
I'm found to way to iterate over elements of a list to create set of virtual identical resources (e.g. X number of VMs in Azure with matching resources - disk image, network card, ip address, dns entry).
It works fine to create extra elements.

E.g. Adding new entry works fine. Changing:
```hlc
variable vmlist = {
   type = list
   default = ['node1', 'node2', 'node3']
}
```
to
```hlc
variable vmlist = {
   type = list
   default = ['node1', 'node2', 'node3', 'node4']
}
``` 
creates new set of resources.

However, the problems start when you manipulate a list e.g.
removing node2 from the the middle of a list
```hlc
variable vmlist = {
   type = list
   default = ['node1', 'node3', 'node4']
}
```
is going to destroy (and then rebuild) node3 and node4.

It's because Terraform check only internal resource name, which has only a counter e.g.
```module.nodes.azurerm_virtual_machine.ubuntu.3:```

One of the way to address it would be to loop over all elements of the map rather then list and create resources name based on keys. In this case internal resource name would be:
```module.nodes.azurerm_virtual_machine.ubuntu.node3```
and therefore removing element from the map wouldn't destroy all succeeding resources. Of course any other way enabling to control a name of the resources would work.

**Comment by mitchellh** [comment]
This is reported somewhere else (same labels) and is a huge issue currently. It is difficult and we're not quite sure how to handle it yet but its something we really want to address. Closing as a dup, its on our radar!
