### ISSUE TITLE
Racy behavior creating aws_routes that are inserted before other routes

### ISSUE THREAD

**Issue by erickt** [hashicorp/terraform#11811]
I'm encountering some racy behavior creating an `aws_route`s. It appears that when a new route is created, and it is inserted before other routes, terraform doesn't consistently handle the destruction and creation of the routes correctly. This can result in breaking routing in a VPC, which requires manual intervention in fixing the routes in the console and manually updating the `terraform.tfstate` file.

### Terraform Version

Terraform v0.8.6

### Affected Resource(s)
- aws_route

### Terraform Configuration Files

I ended up writing some [python programs](https://gist.github.com/erickt/d49017ea9e9fac76f3cb2af85e81312e) to reproduce it since it doesn't happen consistently.

### Debug Output

Logs are in this [gist](https://gist.github.com/erickt/d49017ea9e9fac76f3cb2af85e81312e).

### Expected Behavior

The routes created.

### Actual Behavior

One route will occasionally not be created, or terraform won't add the created routes to the `terraform.tfstate` file.

### Steps to Reproduce

For the racy creation with `aws_internet_gateway`:

1. Run `AWS_PROFILE=... ./run-igw.py --vpc-cidr 10.0.0.0/16 --availability-zone us-west-2a --subnet-cidr 10.0.0.0/20 10`, which will create and remove routes in a loop, where `10` is the cycle.
2. After a number of cycles, this should eventually error out with:

```
* aws_route.private_peer_route.1: Error finding route after creating it: Unable to find matching route for Route Table (rtb-23e3d744) and destination CIDR block (12.0.0.0/32).
```

For the racy creation with VPC peers:

1. Run `AWS_PROFILE=... ./run-peer.py --vpc-cidr 10.0.0.0/16 --availability-zone us-west-2a --subnet-cidr 10.0.0.0/20 --peers pcx-d20181bb=11.0.0.0/32,pcx-aa0181c3=12.0.0.0/32 10`, which will create and remove routes in a loop, where `10` is the cycle. The peer cidrs don't matter.
2. After a number of cycles, this should eventually error out with:

```
* aws_route.private_peer_route.1: Error creating route: RouteAlreadyExists: The route identified by 11.0.0.0/32 already exists.
	status code: 400, request id: ccb35b15-6609-401e-8b0d-b9ce14f2f510
```

### References

Perhaps this just need locks `aws_security_group_rule` like in 6b6b5a43c32f7e6bc4b90db79d44494c72398819?

**Comment by CarlInglis** [comment]
I have today experienced a similar issue with 0.8.4.

39 routes in the table defined using code: 
````
resource "aws_route" "route-to-external-vpcs" {
  route_table_id            = "${aws_route_table.connect-to-external-vpcs.id}"
  count                     = "${length(keys(var.route_pcx_map))}"
  vpc_peering_connection_id = "${element(values(var.route_pcx_map),count.index)}"
  destination_cidr_block    = "${element(keys(var.route_pcx_map),count.index)}"
  depends_on                = ["aws_route_table.connect-to-external-vpcs"]
}
````
The map is CIDR (key) to PCX (value).

Because keys returns a sorted (and uniqued) list, if I insert a route that has a CIDR block which puts it in the middle of the sorted list, all the routes below get shuffled down (snip below for illustration) and the last route gets added as a new resource.
````
-/+ aws_route.route-to-external-vpcs.37
    destination_cidr_block:     "10.90.90.0/24" => "10.84.0.0/16" (forces new resource)
    destination_prefix_list_id: "" => "<computed>"
    gateway_id:                 "" => "<computed>"
    instance_id:                "" => "<computed>"
    instance_owner_id:          "" => "<computed>"
    nat_gateway_id:             "" => "<computed>"
    network_interface_id:       "" => "<computed>"
    origin:                     "CreateRoute" => "<computed>"
    route_table_id:             "rtb-e79e0e82" => "rtb-e79e0e82"
    state:                      "active" => "<computed>"
    vpc_peering_connection_id:  "pcx-6b38fb02" => "pcx-00a25969"

-/+ aws_route.route-to-external-vpcs.38
    destination_cidr_block:     "10.93.0.0/16" => "10.90.90.0/24" (forces new resource)
    destination_prefix_list_id: "" => "<computed>"
    gateway_id:                 "" => "<computed>"
    instance_id:                "" => "<computed>"
    instance_owner_id:          "" => "<computed>"
    nat_gateway_id:             "" => "<computed>"
    network_interface_id:       "" => "<computed>"
    origin:                     "CreateRoute" => "<computed>"
    route_table_id:             "rtb-e79e0e82" => "rtb-e79e0e82"
    state:                      "active" => "<computed>"
    vpc_peering_connection_id:  "pcx-2c63a345" => "pcx-6b38fb02"

+ aws_route.route-to-external-vpcs.39
    destination_cidr_block:     "10.93.0.0/16"
    destination_prefix_list_id: "<computed>"
    gateway_id:                 "<computed>"
    instance_id:                "<computed>"
    instance_owner_id:          "<computed>"
    nat_gateway_id:             "<computed>"
    network_interface_id:       "<computed>"
    origin:                     "<computed>"
    route_table_id:             "rtb-e79e0e82"
    state:                      "<computed>"
    vpc_peering_connection_id:  "pcx-2c63a345"
````
When TF got to the end it errored: 
````
Error applying plan:

1 error(s) occurred:

* aws_route.route-to-external-vpcs.39: Error creating route: RouteAlreadyExists: The route identified by 10.93.0.0/16 already exists.
	status code: 400, request id: 2eb96273-d777-4a30-a678-bc878959a99b
````
10.93.0.0/16 was the last entry in the map. When I checked the console the route did not exist. 

Re-planning and re-applying added the route correctly.
