### ISSUE TITLE
Error modifying DB Parameter Group: InvalidParameterValue: Could not find parameter with name: character_set_server

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#11820]
I'm trying to setup a RDS instance w/ "all the trimmings", but it's failing on the `aws_db_parameter_group` resource.

### Terraform Version
Terraform v0.8.1

### Affected Resource(s)
- aws_db_parameter_group

### Terraform Configuration Files
```hcl
resource "aws_rds_cluster_parameter_group" "main_fc2" {
  name                            = "main-fc2"
  family                          = "postgres9.6"
  description                     = "FC2 parameter group"

  parameter {
    name                          = "character_set_server"
    value                         = "utf8"
  }

  parameter {
    name                          = "character_set_client"
    value                         = "utf8"
  }

  tags {
    Name                          = "core-main_fc2"
    environment                   = "core"
    location                      = "rds-fc2"
  }
}
```

That's pretty much exactly what's used in the documentation at https://www.terraform.io/docs/providers/aws/r/rds_cluster_parameter_group.html.

### Expected Behavior
The parameter group should have been created.

### Actual Behavior
Got an error saying:

```
* aws_db_parameter_group.main_fc2: Error modifying DB Parameter Group: InvalidParameterValue: Could not find parameter with name: character_set_server
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply -no-color --target=module.core-main.aws_db_parameter_group.main_fc2`

**Comment by Ninir** [comment]
Hi @FransUrbo 

It seems you are using postgresql 9.6. However, the `character_set_server` & `character_set_client` parameters are not used by postgresql, but mysql / MariaDB.
To check it, create a parameter group in the console and edit its parameters.

Tell us how it goes!

**Comment by FransUrbo** [comment]
Ah, yes. I just copied-and-pasted the example at https://www.terraform.io/docs/providers/aws/r/rds_cluster_parameter_group.html and then changed the `family` argument.

Could this be retagged as `documentation` instead of `bug` and `provider/aws` and have something like:

```
Parameter blocks support the following:
[etc, bla bla]
Some variables might not be available for all DB families. Please see the AWS documentation at <whatever URL that would be>.
```
