### ISSUE TITLE
Is it possible to create aws_db_instance with "Encryption Enabled"?

### ISSUE THREAD

**Issue by RuslanHamidullin** [hashicorp/terraform#1182]
Hey guys,

I'm new in Terraform.
I just reviewed "aws_db_instance" resource in https://www.terraform.io/docs/providers/aws/r/db_instance.html
And can't find ability to set RDS instance with "Encryption Enabled" option.

So, is it possible to set it via terraform? 

Thanks for any help and for amazing product :beers:

**Comment by RuslanHamidullin** [comment]
Ahhh, I see it was merged to master
https://github.com/hashicorp/terraform/pull/1041/files
My bad :panda_face: 

Closing :beers:

**Comment by catsby** [comment]
Thanks for opening this @RuslanHamidullin , I'm glad you found your own answer :smile: 

That features hasn't shipped yet (officially), but we forgot to include updated documentation, which I added here: https://github.com/hashicorp/terraform/pull/1183

**Comment by RuslanHamidullin** [comment]
Thanks for amazing product :beers:
