### ISSUE TITLE
Offer: New Gandi.net provider

### ISSUE THREAD

**Issue by brycefisher** [hashicorp/terraform#11837]
I'd like to prepare a PR to add Gandi.net as a new provider, specifically its DNS services. I'm really excited about the potential to manage DNSSEC (and related records SSHFP and TLSA) through Terraform; right now, Gandi.net seems to be only purveyor of DNS/SEC with an API that I've seen.

Would a well written and tested PR to add Gandi.net as a new Provider be welcome? I've read through the contribution guidelines, and I feel ready to start working on such a PR.

**Comment by stack72** [comment]
Hi @brycefisher 

Please do feel free to open a PR :)

We are not against accepting new providers!

Paul

**Comment by tpoindessous** [comment]
Hi @brycefisher 

as a gandi happy customer, I would be glad to help you test your work and help you with this provider.

Ping me on my email thomas _at_ poindessous.com if you want.

Thanks.

**Comment by brycefisher** [comment]
@tpoindessous -- awesome! I'm also a happy Gandi.net customer (not an employee). Apologies for the delay in starting this work. I'll update as I make progress here. Thanks for the encouragement!

**Comment by gdchamal** [comment]
Hello I work for gandi. May I can help on this subject please ask

**Comment by tpoindessous** [comment]
Hi @gdchamal , does Gandi officially support an Go SDK for her API ?

I found this one : https://github.com/prasmussen/gandi-api

Thanks.

**Comment by gdchamal** [comment]
Hello @tpoindessous, the only piece of code in go for API usage that gandi support is this one https://github.com/Gandi/docker-machine-gandi

**Comment by kalou** [comment]
Hi there,

As long as DNS is concerned, I'd suggest using our new API rather than the XMLRPC one, as it features or has cool new add-ons planned soon (automatic zone signing, new records including ALIAS, etc.)

http://doc.livedns.gandi.net/

It's REST based, so it should not be too much of a headache to implement

**Comment by ajdexter** [comment]
@brycefisher Any updates on this one?? I'm embarking on this mission as well, and trying to get my head around workload.

**Comment by brycefisher** [comment]
@ajdexter sadly, I haven't started into this work. I accepted a job offer right about the time I was looking into making this PR.

When I looked into starting this, the main thing I got worried about was how the immutable versions of config in gandi's APIs could be squared against terraform's notions of mutable state.

Anyway, if you're interested in doing this, be my guest!

**Comment by sysadmiral** [comment]
If you need a test volunteer I'd be happy to test any PR

**Comment by ajdexter** [comment]
Thanks @brycefisher for the response, and @sysadmiral for the offer. If I do anything with this I'll keep you both posted, but may wait for some of the new LiveDNS api changes mentioned above to flesh out a bit.

**Comment by lttmtins** [comment]
I'm actually using this one in production now: https://github.com/tiramiseb/terraform-provider-gandi
