### ISSUE TITLE
Proposal: "explicit" mode for terraform remote

### ISSUE THREAD

**Issue by 2rs2ts** [hashicorp/terraform#11835]
Recently, I was using `terraform import` to import some KMS keys into my statefiles. I have a lot of them, so I have some automation around reconfiguring which remote state I am using with `terraform remote config`. I was doing something like this:

```bash
for region in $(all_regions) ; do
  terraform remote config \
    -backend=s3 \
    -backend-config="bucket=my-tfstates-bucket" \
    -backend-config="region=us-east-1" \
    -backend-config="key=my-project/${region}.tfstate"
  ...
  terraform import aws_kms_key.foo_key "$(get_key_arn)"
  terraform plan ...
done
```

However, I typoed the resource identifier, so my plan ended up showing me trying to delete the key! Fortunately, I didn't apply my plan, otherwise I would have had to restore the KMS key manually. Typos aside, my pain point was that the statefiles automatically synced to S3, so I had to notify my team that, until I fixed the statefiles, they had to hold off on applying any changes to them. Otherwise, they'd end up deleting the keys, since the resource that I typo'd wouldn't be defined in our `.tf` configuration.

If I had a way to make the configure the remote state such that it would only sync when I explicitly said to `terraform remote push` or `terraform remote pull`, this wouldn't have happened to me. I realize I could homebrew my own solution for remote state management that works like that, but wouldn't it be nice to have it built in?

**Comment by mitchellh** [comment]
Remote management has changed quite a lot in the next version of Terraform so I'm going to use those commands... this is possible there at least:

```
$ terraform remote pull > local.tfstate
$ terraform import -state=local.tfstate ...
$ terraform remote push local.tfstate
```

I'm 100% sure that's not exactly correct, but it is close. Basically: you can use the remote state as a local state temporarily and repush it.

**Comment by 2rs2ts** [comment]
@mitchellh I think you misunderstood what I was requesting. I was interested in setting a default behavior, not doing that on-demand. (Though that would have been a cool solution for what I was doing as described in my OP.)

**Comment by apparentlymart** [comment]
Unfortunately I expect what you are suggesting here would actually be a little harder in 0.9, because of two changes that are coming:

* Remote mode can be declared in configuration rather than on the command line, and that's likely to become the idiomatic way to do so, making it slightly harder to temporarily "work offline".
* The local state cache `.terraform/terraform.tfstate` is no longer used when remote is enabled.

I wonder if we could instead address your root problem here: `terraform import` didn't detect your typo. Perhaps we could refine this workflow by requiring the user to add a `resource` block to the configuration *first* before running `terraform import`, and thus allow us to catch when the import address does not line up with the configuration.

**Comment by mitchellh** [comment]
I agree there are some refinements that can be made, but I actually think this is _easier_ in 0.9 at the expense of being a bit manual. However, I think no more manual than before:

1. Remove the `backend` configuration.
2. `terraform init` will copy your state down locally
3. Perform the imports, edits to config, etc.
4. Add the backend config again
5. `terraform init` will ask if you want to migrate your local state back up.

As long as you communicate with your team that you're doing this so you don't end up with any conflicts (which Terraform will also detect, but not fix), this is a pretty simple process.

**Comment by 2rs2ts** [comment]
@apparentlymart 

>I wonder if we could instead address your root problem here: terraform import didn't detect your typo. Perhaps we could refine this workflow by requiring the user to add a resource block to the configuration first before running terraform import, and thus allow us to catch when the import address does not line up with the configuration.

I agree that this is a good change. I'm not sure if there are other reasons people would want this "explicit" mode I'm proposing; if there aren't, then this would solve my pain.

@mitchellh noted. That's actually not too bad to script around if you put the `backend` configuration in its own file and move it around.
