### ISSUE TITLE
EMR Security Configuration

### ISSUE THREAD

**Issue by wjordan** [hashicorp/terraform#11830]
[EMR Security Configuration](http://docs.aws.amazon.com//emr/latest/ReleaseGuide/emr-encryption-enable-security-configuration.html) is a new feature released on [Sep 21 2016](https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-emr-now-supports-data-encryption-for-apache-spark-tez-and-hadoop-mapreduce/) that allows a [JSON document](http://docs.aws.amazon.com//emr/latest/ReleaseGuide/emr-encryption-enable-security-configuration.html#emr-encryption-cli-parameters) to be created and associated with an EMR cluster to configure encryption keys, at-rest and in-transit encryption properties for the cluster. Security Configurations are implemented through the following new resource-oriented EMR service APIs:

- [`CreateSecurityConfiguration`](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_CreateSecurityConfiguration.html)
- [`DescribeSecurityConfiguration`](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeSecurityConfiguration.html)
- [`ListSecurityConfigurations`](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_ListSecurityConfigurations.html)
- [`DeleteSecurityConfiguration`](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DeleteSecurityConfiguration.html)

A Security Configuration is associated with an EMR cluster through the [`SecurityConfiguration`](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_RunJobFlow.html#EMR-RunJobFlow-request-SecurityConfiguration) Request Parameter of the [`RunJobFlow`](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_RunJobFlow.html) API.

**Comment by heyarnold1** [comment]
I was thinking of implementing this myself.  Before I do have either of you made any progress?

**Comment by wjordan** [comment]
I have not made any progress- I created this issue mostly to follow-up on a feature request I encountered when [answering](http://stackoverflow.com/a/42142791/2518355) a question on StackOverflow, I did not have a need for it myself.

Good luck with the implementation!

**Comment by catsby** [comment]
A new resource `emr_security_configuration` was added in #14080. It does not cover `ListSecurityConfigurations`, that should be a separate data source I think. 

I'd like to close this if you're ok with it 😄

**Comment by agalazis** [comment]
Any update on list security configurations?
