### ISSUE TITLE
documentation error on aws_lambda_permission

### ISSUE THREAD

**Issue by mmastoras** [hashicorp/terraform#11870]
There is an error in the `aws_lambda_permission` example. It should be 
```hcl
function_name = "${aws_lambda_function.test_lambda.name}"
```
 instead of 

```hcl
function_name = "${aws_lambda_function.test.lambda.arn}"
```

### Terraform Version
0.8.6

### Affected Resource(s)
aws_lambda_permission

### Terraform Documentation
```hcl
resource "aws_lambda_permission" "allow_cloudwatch" {
    statement_id = "AllowExecutionFromCloudWatch"
    action = "lambda:InvokeFunction"
    function_name = "${aws_lambda_function.test_lambda.arn}"
    principal = "events.amazonaws.com"
    source_account = "111122223333"
    source_arn = "arn:aws:events:eu-west-1:111122223333:rule/RunDaily"
    qualifier = "${aws_lambda_alias.test_alias.name}"
}
```

### References
https://www.terraform.io/docs/providers/aws/r/lambda_permission.html

**Comment by stack72** [comment]
Hi @mmastoras 

Thanks for the issue report here - apologies for this - I have just opened a PR that will fix it

As soon as it builds, I will push it to the website

Thanks

Paul
