### ISSUE TITLE
how to upgrade terraform state from one version to another?

### ISSUE THREAD

**Issue by safdarq19** [hashicorp/terraform#11884]
This is more of a question rather than issue.

I have a environment current running with terraform 0.6v and want to upgrade to 0.8v. I update the modules according to terraform 0.8v. if I dont want to rebuild an evironment, is there a way I can upgrade terraform 0.6v state file to 0.8v?

i did look at terraform import command to import arch but if there's already complex arch running it would tough job to import all the components. was wondering if there's an easy way to do this?

**Comment by mitchellh** [comment]
Please ask usage questions on the mailing list. More folks will see it there and people who have experienced first hand "real life" upgrades between 0.6 and 0.8 will be there.

From a maintainer perspective, we recommend really large upgrades like that to go to 0.7 first so you can get any deprecation warnings that may have been removed in 0.8.
