### ISSUE TITLE
Network interfaces and an instance-level security groups may not be specified on the same request

### ISSUE THREAD

**Issue by jaxxstorm** [hashicorp/terraform#1188]
It seems the last commit broke assigning security groups to an instance:

```
resource "aws_instance" "nat" {
  ami = "${var.nat_ami}"
  instance_type = "m1.small"
  security_groups = ["${aws_security_group.nat.id}"]
  subnet_id = "${aws_subnet.dmz_subnet.id}"
  associate_public_ip_address = true
  source_dest_check = false
  tags {
    Name = "${concat(var.vpc_name,"-nat")}"
  }
}
```

Output:

```
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error launching source instance: Network interfaces and an instance-level security groups may not be specified on the same request

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

If I hash out the security groups parameter it works fine.

**Comment by radeksimko** [comment]
Agreed, it was caused most likely by #1147

**Comment by radeksimko** [comment]
This is most likely the solution:
http://www.drewblas.com/2012/08/24/aws-vpc-error-client-invalidparametercombination/

**Comment by jaxxstorm** [comment]
@radeksimko I thought this might be only an issue when you have a public IP address, but it seems from the quick test I just did, it applies to any ec2 instance. Did you test it also?

Pinging @catsby :-D

**Comment by catsby** [comment]
Looking now. That was a tricky part of the API. `goamz` was doing some magic behind the scenes that I tried to carry over, and may have made mistakes. 

Relevant bits: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L295

**Comment by catsby** [comment]
I think this is fixed with #1189 . I'm currently testing. 

@jaxxstorm can you sanity check the example config I'm using there? I want to make sure it represents what you're trying to do, and then I'll turn it into an acceptance test :smile:

**Comment by kendawg2** [comment]
@catsby I tested this with a far more complex plan and it worked.   I no longer get the error and all security groups are properly applied.

**Comment by catsby** [comment]
Excellent, thanks @kendawg2 ! We're fixing this in #1189 then, just wrapping up some details in the acceptance test.

Thanks for reporting and diagnosing things :smile:
