### ISSUE TITLE
Destroy fails on rancher_registration_token and rancher_registry_credential

### ISSUE THREAD

**Issue by jclif** [hashicorp/terraform#11882]
### Terraform Version
Terraform v0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- rancher_registration_token.default: Get http://rancherv2.test.com/v1/projects/1a7/schemas: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
- rancher_registry_credential.dockerhub: Error waiting for registry (1c4) to be removed: Get http://rancherv2.test.com/v1/projects/1a7/registrycredentials/1c4: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
- aws_internet_gateway.test: Error waiting for internet gateway (igw-0acaee6d) to detach: couldn't find resource (31 retries)

<img width="1438" alt="screen shot 2017-02-11 at 3 51 11 pm" src="https://cloud.githubusercontent.com/assets/3463691/22857466/75d9cdf0-f073-11e6-96f8-54cb16d87ae6.png">

### Expected Behavior
It should have deleted all of my resources.

### Actual Behavior
It threw an error while destroying and now it will not allow me to destroy anything.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy`

**Comment by johnrengelman** [comment]
Seems like an environmental issue but could be related to https://github.com/hashicorp/terraform/issues/11971

**Comment by mcanevet** [comment]
I use this feature everyday and it works for me. This is weird, cas your rancher server available when launching the command?
