### ISSUE TITLE
Changes in root_block_device for aws_launch_configuration are not detected

### ISSUE THREAD

**Issue by rokka-n** [hashicorp/terraform#11890]
Hi,

aws_launch_configuration ignores changes in root_block_device 

### Terraform Version
0.8.6

### Affected Resource(s)
aws_launch_configuration

### Expected Behavior
aws_launch_configuration should be recreated on root_block_device changes  

### Actual Behavior
No changes in plan

**Comment by catsby** [comment]
Hello – 

Unfortunately at this time, this is a documented limitation of `aws_launch_configuration`:

- https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

Changes here need to be manually applied via the [taint](https://www.terraform.io/docs/commands/taint.html) command

**Comment by rn-daocloud** [comment]
Thanks.
