### ISSUE TITLE
Inconsistent error writing state file

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#11908]
Terraform: 0.8.6
OS: alpine 3.4

Getting an inconsistent error when running terraform (after a `terraform apply`:

```
Failed to save state: mkdir spec: no such file or directory
panic: error getting work directory: getwd: no such file or directory
goroutine 1 [running]:
panic(0x32fb400, 0xc420252e70)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hashicorp/terraform/vendor/github.com/Unknwon/macaron.init.2()
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/Unknwon/macaron/macaron.go:261 +0x141
github.com/hashicorp/terraform/vendor/github.com/Unknwon/macaron.init()
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/Unknwon/macaron/tree.go:380 +0x2ee
github.com/hashicorp/terraform/vendor/github.com/macaron-contrib/session.init()
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/macaron-contrib/session/utils.go:61 +0x85
github.com/hashicorp/terraform/vendor/github.com/grafana/grafana/pkg/setting.init()
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/grafana/grafana/pkg/setting/setting_smtp.go:32 +0x7b
github.com/hashicorp/terraform/vendor/github.com/grafana/grafana/pkg/models.init()
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/grafana/grafana/pkg/models/user.go:165 +0x58
github.com/hashicorp/terraform/vendor/github.com/grafana/grafana/pkg/api/dtos.init()
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/grafana/grafana/pkg/api/dtos/user.go:53 +0x2e
github.com/hashicorp/terraform/vendor/github.com/apparentlymart/go-grafana-api.init()
	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/apparentlymart/go-grafana-api/user.go:40 +0x42
github.com/hashicorp/terraform/builtin/providers/grafana.init()
	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/grafana/resource_data_source.go:185 +0x38
github.com/hashicorp/terraform/command.init()
	/opt/gopath/src/github.com/hashicorp/terraform/command/version.go:76 +0x157
main.init()
	/opt/gopath/src/github.com/hashicorp/terraform/version.go:10 +0x62
```

I'm running the command `terraform apply -state=spec/spec.tfstate` and the `spec` file exists for sure. There are files in that folder committed to the report when it's checked out.

Older, there is no `grafana` provider defined in my terraform project.

**Comment by jbardin** [comment]
Hi @johnrengelman,

Can you share any more details about the running environment? 

A call to getwd returning `no such file or directory` is usually caused from running within a directory that's been deleted.

**Comment by johnrengelman** [comment]
Running from inside a docker container created using this file:
```
FROM uzyexe/serverspec:2.37.2

ENV TERRAFORM_VERSION=0.8.6

RUN apk update && \
    apk add curl make bash && \
    curl -Ls https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform.zip && \
    unzip terraform.zip -d /usr/local/bin && \
    rm -f terraform.zip && \
    gem install awspec && \
  rm -rf /var/cache/apk/*
```
Running on Drone CI, so it's cloning out my repo and then mounting that as the directory in this container.
I'm then switch to a sub directory and running terraform.

This is my working dir:
```
 tf-modules git:(ci) tree -d .
.
├── fabric
│   └── single-az
│       └── spec
└── scripts

4 directories
```

so my build script is switching int `fabric/single-az` and running the provided TF command. So I don't see how that `spec` directory couldn't be available as it's part of the VCS and not created as part of the build process.

I realize this might not be a TF issue, so I will continue to do some more searching on my side as well. We just set this new CI system up, so as we get more stuff running I might be able to get more info.

**Comment by mitchellh** [comment]
Yeah at the moment this isn't a TF issue, the panic is coming from another package that expects `os.Getwd` to work during an `init` call. This is reasonable behavior. As @jbardin said the failure mode of this syscall is pretty much only that your wd no longer exists. 

I'd say something is wonky with your environment somehow!

**Comment by johnrengelman** [comment]
Good deal. :-)

**Comment by johnrengelman** [comment]
In case anyone cares, I found that this was being caused by Janitor (https://github.com/meltwater/docker-cleanup) removing the Docker volume for my build (Drone CI) while the build was running. So in the end, the problem was exactly as the panic suggested :)
