### ISSUE TITLE
Resource parameter types are almost never specified in the documentation

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/terraform#11904]
Hi,

I've been thinking about this for a while now and I came to the conclusion that the documentation should *always* specify the data type expected from a resource parameter. Currently I can't see any documentation page doing so.

Take the [cloudfront_distribution's aliases parameter](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#aliases) for example. Nothing states it should be a _string_, or a _list_, or a _map_. 

One could argue "_It contains aliaseS. Plural noun. So surely cannot be a string?_". Sure, but then again, is it a list? A map? 

Hope you see what I mean.

In order for Terraform users to be absolutely sure what they need to specify in the resource parameters and so to avoid confusion, errors and therefore waste of time by trial and error, I believe all terraform resources should specify the type expected from a parameter in the documentation.

Same should most probably apply for functions. An example of ambiguous definition can be found [here](https://www.terraform.io/docs/configuration/interpolation.html#cidrhost_iprange_hostnum_).

**Comment by mildwonkey** [comment]
I'm going to close this issue; provider documentation has moved out of the terraform repository, so any future issues w/provider documentation should be opened with the provider. Thanks!
