### ISSUE TITLE
Datasource aws_ecs_task_definition should be able to query inside container definitions.

### ISSUE THREAD

**Issue by maartenvanderhoef** [hashicorp/terraform#11907]
Hi Everyone,

Feature request regarding the latest added datasource: aws_ecs_task_definition. I think it would be an advantage to be able to query the inside of the container definitions, especially retrieving the docker image-path through the datasource aws_ecs_task_definition would be extremely practical to be able to make changes to the task_definition without having to input the current image defined in the task_definition. 
This would make it easier to deploy to ECS without terraform and meanwhile keep using TF for changes to the task_definition.

Adding to that having a data source for the aws_ecs_service would be helpful to get the desired_count of the current active aws_ecs_service or make the desired_count optional as described in https://github.com/hashicorp/terraform/issues/9690

With a setup as describe below I can use different tools for docker image deployment and still use Terraform for modifications to the task definition (memory, cpu, etc. ). When applying
those modifications the current running docker image is being used freeing me of inputting the current running running image which looks closer like
12345.dkr.ecr.us-east-1.amazonaws.com/myapp:201702-97cd14affc2f0dc965813929dfeb9cef60a308a2 than mongo:latest.

```
# new data source for ecs_service to be able to retrieve the current desired_count 
data "aws_ecs_service" "app" {     
  name = "${aws_ecs_service.app.name}"
}

data "aws_ecs_task_definition" "app" {
  task_definition = "${aws_ecs_task_definition.app.family}"
}

data "template_file" "task_definition" {
  template = "${file("${"${path.module}/task-definition.json"}")}"

  # Of the first container_definition take the image path. If it exists use this, otherwise take the given var.image_url.
  vars {
    #### NEW MAGIC HERE ###
    image_url        = "${data.aws_ecs_task_definition.app.container_definitions.0.image ? data.aws_ecs_task_definition.app.container_definitions.0.image : var.image_url}"
  }
}

resource "aws_ecs_task_definition" "app" {
  family = "${var.cluster_name}-${var.shortname}"
  task_role_arn = "${aws_iam_role.ecs_tasks_role.arn}"
  container_definitions = "${data.template_file.task_definition.rendered}"
}

resource "aws_ecs_service" "app" {
  name = "${var.ecs_service_name}"
  cluster = "${aws_ecs_cluster.foo.id}"
  # Copying the desired count of the current active service, when not available, take the desired_count of the current active aws_ecs_service
  desired_count = "${data.aws_ecs_service.desired_count ? data.aws_ecs_service.desired_count : var.desired_count }

  # Track the latest ACTIVE revision
  task_definition = "${aws_ecs_task_definition.app.family}:${max("${aws_ecs_task_definition.app.revision}", "${data.aws_ecs_task_definition.app.revision}")}"
}
```

**Comment by mlankenau** [comment]
For me this is kind of a blocker to continue with terraform. I need to put path to other elements of my deployment into the container definition. Would be super cool to put the container definition inside the tf file
