### ISSUE TITLE
Override for aws_network_acl replaces all rules instead of merging

### ISSUE THREAD

**Issue by willmcg** [hashicorp/terraform#1192]
Maybe I'm misunderstanding how overrides are supposed to work with aws_network_acl, but my expectation was that I would be able to define a base set of rules in an aws_network_acl resource and then use overrides to add additional rules to the base ACL. That is, merge the rule sets to achieve a kind of rule inheritance to incrementally build up rule sets from a base ACL.

However, it looks like the override for the ACL completely replaces the entire base rule set:

    resource "aws_vpc" "vpc" {
        cidr_block = "10.0.0.0/16"
    }

    resource "aws_subnet" "subnet" {
        vpc_id            = "${aws_vpc.vpc.id}"
        cidr_block        = "10.0.0.0/24"
        availability_zone = "us-west-2a"
    }

    resource "aws_network_acl" "acl" {
        vpc_id    = "${aws_vpc.vpc.id}"
        subnet_id = "${aws_subnet.subnet.id}"
        ingress = {
            protocol   = "tcp"
            rule_no    = 100
            action     = "allow"
            cidr_block = "10.100.0.0/16"
            from_port  = 1024
            to_port    = 65535
        }
    }

Here is what I get from plan:

    + aws_network_acl.acl
        ingress.#:                     "" => "1"
        ingress.3129751484.action:     "" => "allow"
        ingress.3129751484.cidr_block: "" => "10.100.0.0/16"
        ingress.3129751484.from_port:  "" => "1024"
        ingress.3129751484.protocol:   "" => "tcp"
        ingress.3129751484.rule_no:    "" => "100"
        ingress.3129751484.to_port:    "" => "65535"
        subnet_id:                     "" => "${aws_subnet.subnet.id}"
        vpc_id:                        "" => "${aws_vpc.vpc.id}"

    + aws_subnet.subnet
        availability_zone:       "" => "us-west-2a"
        cidr_block:              "" => "10.0.0.0/24"
        map_public_ip_on_launch: "" => "<computed>"
        vpc_id:                  "" => "${aws_vpc.vpc.id}"

    + aws_vpc.vpc
        cidr_block:                "" => "10.0.0.0/16"
        default_network_acl_id:    "" => "<computed>"
        default_security_group_id: "" => "<computed>"
        enable_dns_hostnames:      "" => "<computed>"
        enable_dns_support:        "" => "<computed>"
        main_route_table_id:       "" => "<computed>"

Now if I add an override.tf file:

    resource "aws_network_acl" "acl" {
        vpc_id    = "${aws_vpc.vpc.id}"
        subnet_id = "${aws_subnet.subnet.id}"
        ingress = {
            protocol   = "tcp"
            rule_no    = 200
            action     = "allow"
            cidr_block = "10.200.0.0/16"
            from_port  = 1024
            to_port    = 65535
        }
    }

Now I get this from plan and see that instead of two rules I only have one from the override:

    + aws_network_acl.acl
        ingress.#:                    "" => "1"
        ingress.565204634.action:     "" => "allow"
        ingress.565204634.cidr_block: "" => "10.200.0.0/16"
        ingress.565204634.from_port:  "" => "1024"
        ingress.565204634.protocol:   "" => "tcp"
        ingress.565204634.rule_no:    "" => "200"
        ingress.565204634.to_port:    "" => "65535"
        subnet_id:                    "" => "${aws_subnet.subnet.id}"
        vpc_id:                       "" => "${aws_vpc.vpc.id}"

    + aws_subnet.subnet
        availability_zone:       "" => "us-west-2a"
        cidr_block:              "" => "10.0.0.0/24"
        map_public_ip_on_launch: "" => "<computed>"
        vpc_id:                  "" => "${aws_vpc.vpc.id}"

    + aws_vpc.vpc
        cidr_block:                "" => "10.0.0.0/16"
        default_network_acl_id:    "" => "<computed>"
        default_security_group_id: "" => "<computed>"
        enable_dns_hostnames:      "" => "<computed>"
        enable_dns_support:        "" => "<computed>"
        main_route_table_id:       "" => "<computed>"

Is this expected behavior?

I can see the use case where you would want to replace the entire rule set, but the documentation is not clear on what happens with overrides for the as_security_group and aws_network_acl resources.

**Comment by inferiorhumanorgans** [comment]
Based on the documentation and the name override I'd guess that replacement is the intended course of action.  Chef does all sorts of merging magic, and named one of their attribute types "override" -- all of which leads to difficult to understand semantics.

I agree, however, that a merge behavior would be very welcomed -- in my case I'm trying to extend a variety of security groups.

**Comment by 7heo** [comment]
@inferiorhumanorgans the documation states:
> Terraform also has a concept of *overrides*, a way to create files that are loaded last and *merged* into your configuration, rather than appended.

You're probably right about the intention behind the behavior; but the documentation is wrong about it, and thus, there is a bug somewhere. And a missing feature too, override behaves like an override, which is great, but we don't have any way to extend. Also, the doc' could really use a better wording, the current one is wrong.

**Comment by catsby** [comment]
Hey all – I'm going to close this issue. The `override` feature of the configuration is meant behave as we're seeing here; something specified in a configuration is replaced with the contents of an override file;  that part is overwritten. I think the use of the term _merged_ in the documentation may be the source of confusion. It is clear however that nothing is appended. 

Sorry for the trouble here. If you have suggestions on better wording there I'd be happy to apply them.

Thanks!

**Comment by innovia** [comment]
@catsby does count meta parameter also overwrite/append to the original resource?

in the example below it  seems that the resource will never be created by default because of the oevrride

```## main.tf
resource "aws_s3_bucket" "s3_bucket" {
  count         = "${var.enabled}"
  bucket        = "${local.bucket_name}"
  region        = "${var.region}"
  force_destroy = "${var.force_destroy}"
  acl           = "private"

  versioning = {
    enabled = "${var.versioning_enabled}"
  }

## website_override.tf
resource "aws_s3_bucket" "s3_bucket" {
  count  = "${var.website}"
  bucket = "${var.full_domain_name}"
  region = "us-east-1"

  website = {
    index_document = "${var.index_document}"
    error_document = "${var.404_document}"
  }

  policy = "${data.aws_iam_policy_document.website.json}"
}

## variables.tf

variable "website" {
  default     = false
  description = "set the S3 bucket as a website static hosting."
}
```
