### ISSUE TITLE
Terraform v0.8.6 statuscake tcp test missing port

### ISSUE THREAD

**Issue by gibbsoft** [hashicorp/terraform#11923]
Reading the [statuscake_test resouce docs](https://www.terraform.io/docs/providers/statuscake/r/test.html) it's not clear how to specify the port for TCP based tests.  I tried adding `:22` to the test URL, but that didn't work so I suspect it's not currently possible.

Please add a `tcp_port` field, or similar to the `statuscake_test` resource.

**Comment by stack72** [comment]
Hi @gibbsoft 

I just added a PR that fixes this issue - but I am waiting on the PR for the upstream library to be merged :)

P.

**Comment by gibbsoft** [comment]
Brilliant, thank you! :)
