### ISSUE TITLE
aws_dynamodb_table resource reading tags from dynamodb-local throws UnknownOperationException

### ISSUE THREAD

**Issue by cstavro** [hashicorp/terraform#11926]
### Terraform Version
0.8.6

### Affected Resource(s)
- aws_dynamodb_table

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
  dynamodb_endpoint = "http://localhost:8000"
}

resource "aws_dynamodb_table" "mytable" {
  name = "mytable"
  read_capacity = 1
  write_capacity = 1
  hash_key = "id"

  attribute {
    name = "id"
    type = "S"
  }
}
```

### Debug Output
https://gist.github.com/cstavro/5e23b233ebfc29ffa48e5ead52d27c34

### Expected Behavior
- Should be able to plan and apply a config
- Should be able to plan after an apply

### Actual Behavior
- The initial plan works as expected but the apply errors when refreshing state. It does appear to create the tables and stores them in the tfstate file but you are unable to plan or apply any changes after that initial apply.
The output is here: https://gist.github.com/cstavro/d9d3686454fafd2d95a6ebc7cba43363

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
- This works fine in v0.8.5
- Running latest version of dynamodb-local for development

### References
Pretty sure this is the guy that causes the problem
- https://github.com/hashicorp/terraform/pull/11617

**Comment by CPWeaver** [comment]
@cstavro I'm running into this exact issue and wondering if you found any workaround? As you showed the apply errors out even when tags are excluded from the resource definition.

**Comment by cstavro** [comment]
I don't think there is a workaround. It's an incompatibility between the local and hosted versions of DynamoDB. The local version flat out doesn't support tags and returns an error that TF is interpreting as a hard failure.

I don't think the fix is going to be huge but I've had trouble getting TF to compile on my Windows box so I haven't gotten around to attempting to fix it myself yet.

My solution so far has been to stick with TF v0.8.5 for this project. It's either that or manage dynamodb differently between my dev and production environments which I don't really want to do.

**Comment by CPWeaver** [comment]
@cstavro Thanks, that's what I suspected. I'd like to stay on a newer version of TF so I'll probably just provision dev instances separately and hope Amazon releases an updated local Dynamo that supports tagging.
