### ISSUE TITLE
aws_instance does not support "domain"

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#11938]
Terraform 0.8.4+

If you are running an aws active_directory_service, you get the option of spawning an instance attached to the domain.

Terraform does not currently support this, which is highly annoying, meaning for seamless domain join, all instances still have to be created manually >.<

**Comment by stack72** [comment]
Hi @gtmtech 

I can't see anywhere where i can pass a domain to an instance - it's not in the SDK by the looks of it and I can't see it in the CLI either - http://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html

Thoughts?

**Comment by gtmtech** [comment]
Whilst the GUI represents a simple dropdown box "domain" - allowing you to join whichever domain you want, I believe this is not an ec2 api call, but an ssm one.

Under the covers when you select a domain, aws creates or uses an SSM document - see

https://aws.amazon.com/blogs/security/how-to-configure-your-ec2-instances-to-automatically-join-a-microsoft-active-directory-domain/

**Comment by gtmtech** [comment]
(So the SDK/API calls are probably there, just under ssm, not ec2)

**Comment by liamjbennett** [comment]
@gtmtech as you pointed out domain join is handled by the SSM service. TF now support creating [SSM documents](https://www.terraform.io/docs/providers/aws/r/ssm_document.html) and associations in order to support this use case.

**Comment by stack72** [comment]
@gtmtech looks like this is something we can close :)

**Comment by gtmtech** [comment]
@stack72  , @liamjbennett  - incorrect, please reopen this bug.

Although SSM document is supported by terraform, what is missing is SSM document association  (to associate it with an instance).

Please see `aws ssm create-association help` for more details.

Thanks

**Comment by liamjbennett** [comment]
@gtmtech https://www.terraform.io/docs/providers/aws/r/ssm_association.html

**Comment by gtmtech** [comment]
Haha thanks @liamjbennett  - the reason I missed it , is because it does not appear in the LHS menu - maybe the simplest document fix of all!

**Comment by stack72** [comment]
@gtmtech sorry about that - fixing right now https://github.com/hashicorp/terraform/pull/12202
