### ISSUE TITLE
AWS Elastic Volumes not supported

### ISSUE THREAD

**Issue by bentterp** [hashicorp/terraform#11931]
Hi!

Would be great to see Terraform support for Elastic Volumes, ie modifications to EBS volumes:

- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-expand-volume.html

```
[bent@######-admin01 terraform]$ terraform -v
Terraform v0.8.6

[bent@######-admin01 terraform]$ terraform plan
....................
    root_block_device.#:                       "1" => "1"
    root_block_device.0.delete_on_termination: "true" => "true"
    root_block_device.0.iops:                  "100" => "<computed>"
    root_block_device.0.volume_size:           "8" => "10" (forces new resource)
    root_block_device.0.volume_type:           "gp2" => "<computed>"
......................
[bent@######-admin01 terraform]$ cat jumphost.tf
resource "aws_instance" "jumphost" {
         ami = "${data.aws_ami.standard_ami.image_id}"
         instance_type = "t2.micro"
         key_name = "${var.sshkey}"
         monitoring = true
         private_ip = "${cidrhost(aws_subnet.dmz.cidr_block, 5)}"
         vpc_security_group_ids = [ "${aws_security_group.ssh.id}",
                                    "${aws_security_group.backend.id}",
                                    "${aws_security_group.ping.id}",
                                  , "${aws_security_group.egress.id}" ]
         subnet_id = "${aws_subnet.dmz.id}"
         root_block_device {
           volume_size = 10
         }
    tags {CostCenter = "${var.labtitle}"}
    tags {Name = "${var.labtitle}-jumphost"}
    user_data = "${file("include/userdata_bootstrap.sh")}"
}
[bent@######-admin01 terraform]$
```

------

(@catsby edited for format)

**Comment by bentterp** [comment]
Interesting (at least to me...) is that TF is aware of the volume size: if I increase it in the template as above, and plan wants to do a -/+ but then modify the volume using AWS console, then TF is happy with the volume as it is. That's nice as a temporary workaround.

**Comment by adespain** [comment]
I am still getting (forces new resource) when trying to increase a volume size, am I doing something wrong?  I am using terraform v0.8.7.  I changed the size from 10 to 12 and this is what the terraform plan output is:  

-/+ aws_ebs_volume.ebs_home
    availability_zone: "us-west-2a" => "us-west-2a"
    encrypted:         "true" => "true"
    iops:              "" => "<computed>"
    kms_key_id:        "xxx" => "xxx"
    size:              "10" => "12" (forces new resource)
    snapshot_id:       "" => "<computed>"
    type:              "gp2" => "gp2"

-/+ aws_volume_attachment.att_home
    device_name:  "/dev/xvdc" => "/dev/xvdc"
    force_detach: "" => "<computed>"
    instance_id:  "i-08d75faa0b4457571" => "i-08d75faa0b4457571"
    skip_destroy: "" => "<computed>"
    volume_id:    "vol-084aa2abd8d34121f" => "${aws_ebs_volume.ebs_home.id}" (forces new resource)

**Comment by stack72** [comment]
Hi @bentterp 

this isn't in 0.8.7 - it will only be part of 0.8.8

Paul
