### ISSUE TITLE
unable to create a k8s cluster with image type "container-vm" on Google Cloud

### ISSUE THREAD

**Issue by harshal-shah** [hashicorp/terraform#11934]
Below is the resource definition which I am using for creating a k8s cluster on Google Cloud. 
I want to create a cluster of type container-vm but under node_config, this key is not allowed

Details below:

### Terraform Version
Terraform v0.8.6

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

### Terraform Configuration Files
```hcl

resource "google_container_cluster" "primary" {
  name = "gfs-k8s"
  zone = "${var.region_zone}"
  initial_node_count = 3


  master_auth {
    username = "omar"
    password = "mouzone"
  }
  network = "${google_compute_network.default.name}"
  subnetwork = "${google_compute_subnetwork.public-subnet.name}"
  node_config {
    image_type = "container-vm"
    machine_type = "n1-standard-2"
    oauth_scopes = [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring"
    ]
  }
}
```

### Output
```
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * google_container_cluster.primary: node_config.0: invalid or unknown key: image_type
```

### Expected Behavior
A k8s cluster with image type "container-vm" should have been created.

### Actual Behavior
Syntax error as shown above.

### Steps to Reproduce
Use resource definition mentioned above and run ```terraform apply```

**Comment by danawillow** [comment]
Hey @harshal-shah, this actually isn't a problem with the type being "container-vm" but that our GKE provider just doesn't support the `image_type` field yet. I'm working on improving our GKE support so this should be fixed pretty soon.

**Comment by harshal-shah** [comment]
so as of now there is no way to create a cluster with ```image_type = container-vm``` ?

**Comment by danawillow** [comment]
correct

**Comment by harshal-shah** [comment]
ok thanks, eargerly waiting for the update.
