### ISSUE TITLE
Add ALL as protocol to aws_security_group

### ISSUE THREAD

**Issue by tarrant** [hashicorp/terraform#1193]
You can currently get it by putting in '-1', but it should accept the string 'ALL'.

**Comment by josephholsten** [comment]
@tarrant do you feel up to this patch, or will someone else need to implement?

**Comment by catsby** [comment]
Hey all – after a long wait, `"all"` support will come in #5881. Note that you need to set `to_port` and `from_port` to `0` for this. 

Thanks! Sorry for the silence :smile:
