### ISSUE TITLE
providers/aws: aws_route53_record rejected request due to Route53 still processing a prior request

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#1194]
When changing two `aws_route53_records` that are dependant on other resources, in the same plan, `ChangeResourceRecordSets` seem to fail consistently with a:
```
The request was rejected because Route 53 was still processing a prior request.
```

http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html ?

**Comment by catsby** [comment]
Hey @pmoust – thanks for reporting this. 
I may have accidentally fixed this with https://github.com/hashicorp/terraform/pull/1222 , can you check? 

We actually (try to) account for this, however when I ported Route53, I mistakenly didn't update the error checking and then this message popped up.

**Comment by pmoust** [comment]
@catsby Indeed seems to be ok for the specific part of our infrastructure that demonstrated this behavior. Thanks!
