### ISSUE TITLE
Add load balancer resource to digital ocean provider

### ISSUE THREAD

**Issue by justinjdickow** [hashicorp/terraform#11945]
https://www.digitalocean.com/company/blog/load-balancers-simplifying-high-availability/

https://developers.digitalocean.com/documentation/v2/#load-balancers

**Comment by andrewsomething** [comment]
FYI, support landed in godo:

https://godoc.org/github.com/digitalocean/godo#LoadBalancer

**Comment by stack72** [comment]
Hi @justinjdickow / @andrewsomething 

I just merged the PR to update the SDK for this - I am going to start looking at the functionality tomorrow ;)

P.
