### ISSUE TITLE
AWS Spot Fleet Overprovisioned!

### ISSUE THREAD

**Issue by abhishekamralkar** [hashicorp/terraform#11956]
Hi there,

### Terraform Version

**Terraform v0.8.6**

### Affected Resource(s)
-aws_spot_fleet_request

### Terraform Configuration Files

```
module "mesos-slave-spot-fleet" {
  source             = "../../../modules/testpad/application/mesos-slave_spot_fleet/"
  key_name           = "testing-terraform-key"
  aws_security_group = "${module.vpc.mesos_slave_sg_id}"
  org                = "abhishek"
  region             = "${var.region}"
  fullaz             = "${var.region}a"
  env                = "testpad"
  iam                = "abhishek-mesos-slave-iam-testpad"
  ami_id             = "ami-12fe34"
  subnets            = "${module.vpc.mesos_slave_subnet_id}"
  org_validator      = "abhishek-inc-validator"
  env                = "testpad"
  zone_id_public     = "${var.zone_id_public}"
  zone_id_private    = "${var.zone_id_private}"
  spotprice          = "0.05"
  depends_on         = "${module.mesos-master.mesos_master_trigger}"
  userdata           = "${var.userdata}"
  targetcapacity     = "10"
}
```
```
resource "aws_spot_fleet_request" "mesos-agents" {
    iam_fleet_role = "arn:aws:iam::1234567891011:role/aws-ec2-spot-fleet-role"
    spot_price = "${var.spotprice}"
    allocation_strategy = "diversified"
    target_capacity = "${var.targetcapacity}"
    valid_until = "2017-11-04T20:44:20Z"
    launch_specification {
        instance_type = "c4.large"
        ami = "${var.ami_id}"
        key_name = "${var.key_name}"
        availability_zone = "${var.fullaz}"
        vpc_security_group_ids = ["${var.aws_security_group}"]
        spot_price = "${var.spotprice}"
        subnet_id = "${var.subnets}"
        weighted_capacity = 2
        user_data = "${file(var.userdata)}"
        iam_instance_profile    = "abhishek-mesos-slave-iam-testpad"
    }
}
```

### Expected Behavior

Ideally it should launch 5 c4.large instances and requirement should get fulfil.

### Actual Behavior

https://gist.github.com/abhishekamralkar/a7c0d4cc374c5d6524ae983f7b1ef089

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by abhishekamralkar** [comment]
Just want to know when this issue will be addressed?

**Comment by optimisticanshul** [comment]
@abhishekamralkar you are passing ```targetcapacity     = "10"``` or am i missing something ?

**Comment by abhishekamralkar** [comment]
@optimisticanshul Yes I am passing `targetcapacity = "10"`.

**Comment by stack72** [comment]
Hi @abhishekamralkar 

I am not quite sure what the issue here is - you are saying you expect 5 instances but yet you are passing target capacity = 10?

Are you able to reliably recreate the issue?

thanks

Paul

**Comment by abhishekamralkar** [comment]
Hello @stack72,

I want to use SPOT fleet `vCPU's` and I am passing instance types as `instance_type = "c4.large"`, so when I say `target capacity = 10`, I should get 5 `c4.large` instances as its is `2 vCPU` machine.

**Comment by abhishekamralkar** [comment]
@stack72 @catsby Guys any update on this issue? Also how terraform understand that it need to provision vCPU's or instances?

**Comment by epetrovich** [comment]
@abhishekamralkar 
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html
"The Spot fleet attempts to launch the number of Spot instances that are required to meet the target capacity that you specified in the Spot fleet request."

**Comment by abhishekamralkar** [comment]
@epetrovich 
I want SPOT Fleet with vCPU and not with instance types. So in my case **TargetCapacity = 10** is vCPU's and not instances. With the latest Terraform version I am able to get the **TaregtCapacity = 10** but I am getting 10 instances and not 10  vCPU's. So I would like to know what parameter I need to pass to get 10 vCPU's and not 10 instances.

Also is there any example I can use CHEF as provisioner with SPOT Fleet, as I can do that with onDemands and SPOT instances.

**Comment by stack72** [comment]
Hi @abhishekamralkar 

I cannot find any documentation or examples that suggest you can pass a number of vCPUs to AWS and it will create the appropriate number of instances

This is the CLI request for this http://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-fleet.html

Can you link me to some documentation that supports what you need to do?

Paul

**Comment by abhishekamralkar** [comment]
Hi @stack72 

Okay so it seems if we use **weighting** feature it will boot the **TargetCapacity==vCPU**

[http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html#spot-instance-weighting](url)

Also is there any example I can use CHEF as provisioner with SPOT Fleet, as I can do that with onDemands and SPOT instances.

**Comment by epetrovich** [comment]
You can set the weight in the launch configuration.

**Comment by stack72** [comment]
Looks like we can close this issue out as `weighting` is available in the Launch Config
