### ISSUE TITLE
Expose SourceBundle to aws elastic beanstalk resources

### ISSUE THREAD

**Issue by spy-tech** [hashicorp/terraform#11955]
Amazon documents as follows:
```
// CreateApplicationVersion API operation for AWS Elastic Beanstalk.
//
// Creates an application version for the specified application. You can create
// an application version from a source bundle in Amazon S3, a commit in AWS
// CodeCommit, or the output of an AWS CodeBuild build as follows:
//
// Specify a commit in an AWS CodeCommit repository with SourceBuildInformation.
//
// Specify a build in an AWS CodeBuild with SourceBuildInformation and BuildConfiguration.
//
// Specify a source bundle in S3 with SourceBundle
```
This is currently not possible to do via native Terraform, which seems to make entire family of aws_elastic_beanstalk resources useless unless I am missing something?

To make the goal somewhat easier to understand here,
https://gitlab.com/dharrisio/terraform-elastic-beanstalk-application-version/blob/master/create_application_version.py provides a work around for this issue. (So, if feature parity with this is achieved, you can close this ticket.)

**Comment by dharrisio** [comment]
@spy-tech With #5770 It is now possible to specify the application version using the s3 source bundle. I was not aware that this could also be specified via CodeCommit or CodeBuild, but that seems like a reasonable enhancement for the resource.
