### ISSUE TITLE
core: Add list range expression

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#11950]
Sample code:

```
variable "foo" {
  type    = "list"
  default = ["foo", "bar", "baz"]
}

output "first" {
  value = "${var.foo[:0]}"
}

output "second_third" {
  value = "${var.foo[1:2]}"
}

output "second_third_alt" {
  value = "${var.foo[1:]}"
}
```

Breaks right now:

```
Error reading config for output first: parse error at 1:11: expected expression but found ":"
```

Probably would be nice if it was supported in the same fashion as golang [slice expressions][1].

[1]: https://golang.org/ref/spec#Slice_expressions

**Comment by apparentlymart** [comment]
I would like this too. In the short term we could probably do it more simply as an interpolation function but first-class syntax in HIL would be nice.

**Comment by vancluever** [comment]
@apparentlymart the `slice` interpolation function was indeed added as you mentioned in the HIL issue. So guess we just need to wait on 0.9 for the function which will tie me over (and I'd imagine tie other people over) until the expression form is added!

**Comment by mitchellh** [comment]
Slice was backported to 0.8.7 out today
