### ISSUE TITLE
count is not a valid parameter on a module

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/terraform#11965]
In Terraform 0.8.4 I get "count is not a valid parameter" when used in a module. It would be really handy to be able to conditionally execute a module like:

```
module "vpc_eu_central_1" {
  count  = "${var.env == "stage" ? "1" : "0"}"
  source = "modules/vpc"
```

Is there a design reason Terraform chooses not to allow this?

**Comment by mitchellh** [comment]
We don't support count on modules.

There is a feature request for this already search for label core and enhance
