### ISSUE TITLE
Using unset variable in conditional or function fails

### ISSUE THREAD

**Issue by marcelboettcher** [hashicorp/terraform#11961]
### Terraform Version
0.8.6

### Affected Resource(s)
conditional and functions (tested with coalesce)
 aws_route53_record

### Expected Behavior
evaluate and execute the expression even when a variable is not set.

### Actual Behavior
Stops with error: aws_route53_record.record: provider.aws: aws_route53_record: test.com: "records": required field is not set
The error message is misleading. The cause is that var.alb_dns_name is not set, but I would expect to ignore that since the condition will use the second value "foo.com"
I think this has nothing to do with aws_route53_record, but with all functions of terraform resulting in unset values if an unset variable is used.
The variable is unset as the input comes from another module, which is currently not active via count = 1.

### Steps to Reproduce
Input variables are:
active = 0
alb_dns_name not set as the ALB providing this value does not exist (count = 0)

`
resource "aws_route53_record" "record" {
  zone_id = "${var.route53_zone_id}"
  name = "test.com"
  type = "CNAME"
  ttl = "300"
  records = [
     "${var.active == 1 ? var.alb_dns_name : "foo.com"}"
  ]
}
`
1. `terraform apply`

**Comment by mitchellh** [comment]
We currently evaluate both sides of a condition. There is another issue tracking this and we intend to tackle it soon. We shipped with the more naive evaluation first so we can make it for 0.8.

**Comment by discordianfish** [comment]
@mitchellh Where?
