### ISSUE TITLE
Support for AWS Kinesis Analytics

### ISSUE THREAD

**Issue by andrewsykim** [hashicorp/terraform#11967]
It doesn't seem like terraform supports [AWS Kinesis Analytics](https://aws.amazon.com/kinesis/analytics/) and I wasn't able to find any open issues/PRs. The Go SDK does have an API for it [here](https://github.com/aws/aws-sdk-go/tree/master/service/kinesisanalytics). 

I wouldn't mind opening up a PR if no one else is willing to work on this. It'll take a while though as I'm not sure how much time I can fit into my schedule for this.

**Comment by apparentlymart** [comment]
Hi @andrewsykim!

The Terraform team doesn't have any short-term plan to work on this but we'd love to review a PR for it if you're able to find the time!

**Comment by andrewsykim** [comment]
@apparentlymart I'll see if I can find the time. No guarantees though :)

**Comment by Ouro130Ros** [comment]
We have a business case for this as well.  We shoehorned in a temporary workaround using provisioners but I am going to try to fit a PR in my schedule as well

**Comment by andrewsykim** [comment]
I definitely won't be working on this anytime soon, would be open to review any PRs you open.

**Comment by vinlok** [comment]
Hello,

I was also looking for terraform kinesis Analytics module. Any plans to work on this in near future?
