### ISSUE TITLE
Data source aws_vpn_gateway

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/terraform#11979]
The `aws_vpn_gateway` data source has been released as part of [v0.8.7](https://github.com/hashicorp/terraform/blob/v0.8.7/CHANGELOG.md) but its lacking documentation. This makes it difficult for users not familiar with the Go language - which could eventually look at the code - to use the new data source.

**Comment by stack72** [comment]
Hi @walterdolce 

We are going to be deploying the site very shortly - we are not quite done with our release cycle yet :)

Stay tuned

Sorry for the delay

Paul
