### ISSUE TITLE
Mechanism to allow rancher provider have a configurable timeout

### ISSUE THREAD

**Issue by jmahowald** [hashicorp/terraform#11971]
### Terraform Version
v0.8.6

### Affected Resource(s)
rancher_stack

I love the rancher provider that was added in GH-9173. My issue is that the rancher provider for me frequently but not always has a timeout.  Obviously this is dependent on my environment, but I feel like the timeout should be configurable in some way.  The underlying rancher go client does have a timeout setting, but I'd need to find a way to fit that in. I wanted to submit a pull request against this, but I don't yet know how to best tackle.   The only choices I can see are either through an environment variable setting or an additional setting on the provider.   If either seems acceptable, I'll send in a pull

Thanks,

**Comment by stack72** [comment]
Hi @jmahowald 

Closing - as explained in #12070 - the new timeout features in Terraform 0.9 will take care of this :)

Paul
