### ISSUE TITLE
AWS Provider - Feature Request: Elastic Beanstalk application version lifecycle.

### ISSUE THREAD

**Issue by beanaroo** [hashicorp/terraform#11986]
From AWS documentation on [Configuring Application Version Lifecycle Settings](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/applications-lifecycle.html)

The configuration parameter is [ApplicationResourceLifecycleConfig](http://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ApplicationResourceLifecycleConfig.html)

Maybe something along the lines of:
```
resource "aws_elastic_beanstalk_application" "tftest" {
  name = "tf-test-name"
  description = "tf-test-desc"
  appversion_lifecycle = {
    max_age = 7
    max_count = 350
    delete_from_s3 = true
  }
}
```

**Comment by stack72** [comment]
//cc @dharrisio

**Comment by sanjay-varanasi** [comment]
+1 to the feature. It would be incredibly great to not have to manually set version lifecycle on multiple beanstalk apps.
