### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by VincentSC** [hashicorp/terraform#11999]
Got an error when going to https://www.terraform.io/ :
> Secure Connection Failed
>
> An error occurred during a connection to www.terraform.io. Peer received a valid certificate, but access was denied. Error code: SSL_ERROR_ACCESS_DENIED_ALERT
>
> *   The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> *   Please contact the website owners to inform them of this problem.

**Comment by stack72** [comment]
Hi @VincentSC 

Sorry for the issue here - looks like it was an intermittent error - the site is back and working now

Thanks

Paul
