### ISSUE TITLE
`cloudflare_record` allows proxied = true on TXT domains

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#11991]
Reproduce:

```hcl
resource "cloudflare_record" "example_txt_domain" {
	domain = "example.com"
	name = "txt"
	type = "TXT"
	value = "whatever"
	proxied = true
}
```

`terraform plan` will happily accept this. Applying it will fail however:

```
* cloudflare_record.example_txt_domain: Failed to create record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"DNS Validation Error\",\"error_chain\":[{\"code\":9004,\"message\":\"This kind of record cannot be proxied\"}]}],\"messages\":[],\"result\":null}"
```

**NOTE**: There are other record types which cannot be proxied (such as MX). I haven't tested them and I can't find an exhaustive list.

**Comment by jleclanche** [comment]
The following types can't be proxied:

* `MX`
* `LOC`
* `SRV`
* `SPF`
* `TXT`
* `NS`

The following types can be proxied:

* `A`
* `AAAA`
* `CNAME`

**Comment by omeroner** [comment]
My tf file;

resource "cloudflare_record" "ankara" {
    domain = "ankara.net"
    name = "deneme"
    value = "10.10.10.12"
    type = "A"
    proxied = true
    ttl = 120
}

we have a problem. 

cloudflare_record.ankara: Modifying...
  proxied: "false" => "true"
Error applying plan:

1 error(s) occurred:

* cloudflare_record.ankara: Failed to update CloudFlare Record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"DNS Validation Error\",\"error_chain\":[{\"code\":9041,\"message\":\"Invalid proxied mode. Record cannot be proxied\"}]}],\"messages\":[],\"result\":null}"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

how you can help me!

**Comment by grubernaut** [comment]
Hi @omeroner!

Looks like the error you returned was directly from a cloudflare API request, and not a Terraform error.
Did this just recently start throwing these errors? I can reproduce both via Terraform and via the Cloudflare Web UI.

**Comment by cemo** [comment]
gentle ping @OJFord. Are you aware of this problem please?

**Comment by OJFord** [comment]
@cemo I'm afraid I'm the wrong person to ask, if it's an issue on Cloudflare's web UI I'd suggest contacting their Twitter or other support channels. (I don't work at CF :slightly_smiling_face:)
