### ISSUE TITLE
Instance IP

### ISSUE THREAD

**Issue by coolgooze** [hashicorp/terraform#11996]
I am trying to extract the Private IP of instances launched outside of terraform, can you help?

I tried
["${aws_instance.<instance-name>.*.private_ip}"]

terraform validate
Error validating: 1 error(s) occurred:

* resource 'aws_route53_record.redis' config: unknown resource 'aws_instance.*' referenced in variable aws_instance.*.*.private_ip

**Comment by stack72** [comment]
Hi @coolgooze 

IF the instance was not managed via terraform, you would have to import it to the Terraform tfstate file using the [import function](https://www.terraform.io/docs/providers/aws/r/instance.html)

Otherwise, this won't be able to work i'm afraid

Sorry for the bad news here

Paul

**Comment by cemo** [comment]
@stack72 Can he use [aws_instance] datasource? Tag his instances and select it. (However it can only select a single instance.) BTW that page is still not visible in side menu of documentation page.

[aws_instance]: https://www.terraform.io/docs/providers/aws/d/instance.html

**Comment by coolgooze** [comment]
The instance was launched as part of autoscaling group created by terraform, is there a way we can get the instance ip launched by autoscaling group?

**Comment by coolgooze** [comment]
@cemo - thank you for the input, however it errors out

Errors:

  * data.aws_instance.redis: Provider doesn't support data source: aws_instance


data "aws_instance" "redis" {
  filter {
    name = "tag:Name"
    values = ["redis"]
  }
}

**Comment by coolgooze** [comment]
i upgraded the terraform to 0.8.7 and can retrieve the ip. Thank you
