### ISSUE TITLE
aws_ssm_document doesn't update document

### ISSUE THREAD

**Issue by DenisBY** [hashicorp/terraform#12007]
### Terraform Version
```
$  terraform -v
Terraform v0.8.7
```
### Affected Resource(s)
- aws_ssm_document

### Terraform Configuration Files
```hcl
terraform {
    required_version = ">= 0.8.7"
}

provider "aws" {
    region = "${var.region}"
}

data "template_file" "document" {
    template = "${file("${path.module}/amiwindowsupdate.json")}"
}

resource "aws_ssm_document" "document" {
  name          = "MY-WindowsUpdate",
  content       = "${data.template_file.document.rendered}"
  document_type = "Automation"
}
```

### Expected Behavior
Document updated or new version created

### Actual Behavior
Terraform says:
```
aws_ssm_document.document: Modifications complete
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
but AWS console and `aws ssm get-document --name "MY-WindowsUpdate"` give the same document as before update

### Steps to Reproduce
1. `terraform apply`
2. change anything in document, i.e. in my case value of one of `timeoutSeconds`
3. `terraform apply`

**Comment by Dogers** [comment]
I've got something similar but I'm using type = Command. You can't actually update that type of document, it has to be deleted and recreated - Terraform appears to be trying to edit it rather than recreating it.
@DenisBY Try editing it manually in the AWS console and see if it lets you?

**Comment by DenisBY** [comment]
@Dogers in AWS console you can't edit current version of document. You need to create a new versions of document in order to update or change it.

**Comment by Dogers** [comment]
@DenisBY gotcha, I've just started messing with the SSM stuff. Having to taint it until I've got it right at the moment..
To keep with the issue - a new version would probably be preferable, but a new document instead wouldn't be a big problem.

**Comment by DenisBY** [comment]
Yes, new version probably is more 'proper' way, but keeping old version number with a new document will simplify usage document in different scripts. You will not have to change you script(s) if you changed document. So it would be nice to have an option - update version on document change or just recreate it with same version.
I.e. we have Jenkins job which uses docker container with our scripts. In case of version update we will have to rebuild container. Or update scripts to support versions.

**Comment by nicwise** [comment]
@stack72 any movement on this? We are seeing this too, and I can't work out a non-gank workaround :( Failing silently isn't .... ideal.

I'll try and have a dig into the code later and see if I can work out whats happening, but I'm a total Go n00b, so I doubt thats going to help much :)

**Comment by nicwise** [comment]
am I right in reading [this](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_ssm_document.go#L231-L242) that the update will update permissions, but just read the document back? ie, not actually even try to update it? Wouldn't it need to call one of [these methods](https://github.com/aws/aws-sdk-go/blob/master/service/ssm/ssmiface/interface.go#L381-L387) to actually update the document?

As I said, Go (and Terraform codebase) n00b....
