### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by imyashvinder** [hashicorp/terraform#12015]
MAIN.TF

provider "aws" {
 access_key = "${var.access_key}"
 secret_key = "${var.secret_key}"
 region = "${var.region}"
}

resource "aws_instance" "lamp-prod" {
 ami = "{lookup(var.aws_amis, var.region)}"
 instance_type = "t2.micro"
 tags { Name = "terraform-instance-test"}
}

VARIABLE.TF
variable "access_key" {}
variable "secret_key" {}
variable "region" {
 default = "ap-southeast-1"
}
variable "aws_amis" {
 type = "map"
 default = {
  us-east-1 = "ami-13be557e"
  ap-southeast-1 = "ami-83a713e0"
 }
}
ERROR :

aws_instance.lamp-prod: Error launching source instance: InvalidAMIID.Malformed: Invalid id: "{lookup(var.aws_amis, var.region)}" (expecting "ami-...")

**Comment by mitchellh** [comment]
That isn't a valid ID. You probably wanted an interpolation which is `${}` not `{}`
