### ISSUE TITLE
terraform 0.8.7 (and below) `terraform state mv` reorders counted resource if count > 10

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform#12019]
Terraform v0.8.7 and below.
Moving a counted resource (resource with multiple instances) with `terraform state mv` reorders the resources at the destination address if the resource count is greater than 10.
Attached ZIP file containing `terraform.tfstate`: [tfstate.zip](https://github.com/hashicorp/terraform/files/781161/tfstate.zip)
Run:
```
terraform state mv module.peerings.aws_vpc_peering_connection.src module.peerings.aws_vpc_peering_connection.dest
```
Note that **aws_vpc_peering_connection.src.1** != **aws_vpc_peering_connection.dest.1**.
Attached also updated test code `state_mv_test.go`: [state_mv_test.go.txt](https://github.com/hashicorp/terraform/files/781170/state_mv_test.go.txt) that shows the problem:
```
go test -v -run="TestStateMv_stateOutNew_largeCount"
```

**Comment by jbardin** [comment]
Thanks for the complete test case @ewbankkit!
