### ISSUE TITLE
`terraform fmt` requires multiple runs to converge

### ISSUE THREAD

**Issue by henrikhodne** [hashicorp/terraform#12017]
### Terraform Version
```
$ terraform -v
Terraform v0.8.7
```

### Affected Resource(s)
N/A

### Terraform Configuration Files
```hcl
variable "foo" { default = "bar" }
variable "bar" {}
variable "baz" { default = "bar" }
variable "foobar" {}
```

### Debug Output
https://gist.github.com/henrikhodne/99a6c72a1e6b4a93adc42e3a82c7e7cb

### Panic Output
N/A

### Expected Behavior

Running `terraform fmt` a second time immediately after running it shouldn't cause any further changes.

### Actual Behavior

`terraform fmt` seems to take at least two runs to guarantee that it's "converged" on a canonical format and doesn't change any further

### Steps to Reproduce
See debug output: https://gist.github.com/henrikhodne/99a6c72a1e6b4a93adc42e3a82c7e7cb

You'll notice that the two first runs say they modify `foo.tf`, but the third doesn't, i.e. it takes two runs to "converge".

### Important Factoids
None that I can think of.

### References
Couldn't find any.

**Comment by mitchellh** [comment]
Fixed this, will be backported and part of 0.8.8
