### ISSUE TITLE
Passing vars to modules when limiting scope with `-target`

### ISSUE THREAD

**Issue by Ashald** [hashicorp/terraform#12024]
### Terraform Version
`v0.8.7`

### Affected Resource(s)
Please list the resources as a list, for example:
- module

### Terraform Configuration Files
*root.tf*

```hcl
variable "consul_acl_token" {}

module "example" {
  source = "./modules/my-module"

  token = "${var.consul_acl_token}"
}
```

*modules/my-module/main.tf*
```hcl
variable "dc" { default = "aws-dev" }
variable "token" {}


provider "consul" {
  datacenter = "${var.dc}"
  token = "${var.token}"
}

resource "consul_prepared_query" "l5d" {
  datacenter = "${var.dc}"
  name = ""
  only_passing = true

  template {
    type = "name_prefix_match"
    regexp = "^(.*).l5d$"
  }

  service = "l5d"
}
```

### Debug Output
https://gist.github.com/Ashald/84ff764f01485cc1ec78cc6487762aee

### Expected Behavior
Terraform should've provided the same output as if ran without `-target` (as it's the only module).

### Actual Behavior
It looks like as though Terraform first filters resources out by the `target` prefix and then tries to render them. In this situation it either should look what the target depends on and "include" those resources as well or render everything first and then just filter out everything that doesn't start from given prefix.

### Steps to Reproduce
```
$ terraform plan -target=modules.example
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.


Error running plan: 1 error(s) occurred:

* 1:3: unknown variable accessed: var.token in:

${var.token}
```

**Comment by apparentlymart** [comment]
Hi @Ashald! Sorry this isn't working right.

I think this is the same as #12009, so I am going to close this to consolidate discussion over there. Please let me know if your think I'm mistaken and I will reopen

**Comment by Ashald** [comment]
@apparentlymart thanks for the quick response! Yeah, it indeed looks like the same issue. I'll follow the #12009
