### ISSUE TITLE
aws_s3_bucket_object always detected as changed when content attribute is generated dynamically

### ISSUE THREAD

**Issue by jimmycuadra** [hashicorp/terraform#12029]
### Terraform Version

Terraform v0.8.6

### Affected Resource(s)

* aws_s3_bucket_object

### Terraform Configuration Files

``` hcl
resource "aws_s3_bucket_object" "my_object" {
  bucket = "${aws_s3_bucket.my_bucket.id}"
  key = "my_object.yml"
  content = "${data.template_file.my_object.rendered}"
  etag = "${md5(data.template_file.my_object.rendered)}"
}
```

### Expected Behavior

If a `terraform apply` has just completed, running `terraform plan` immediately afterwards should not detect any changes to the S3 object.

### Actual Behavior

The S3 object is seen as having changed. The value of the etag attribute changes even though absolutely no files, variables, or data sources have been altered. That is, `"${data.template_file.my_object.rendered}"` will produce identical output from the previous Terraform run.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by jimmycuadra** [comment]
I created a reduced test case for this, and it seems whatever is causing my issue is not because of any inherent inability for aws_s3_bucket_object to detect changes. I'll reopen if I find more info that leads me to believe it's actually a problem with Terraform.

**Comment by wr0ngway** [comment]
I'm seeing similar behavior with terraform v0.8.8 - in my case its happening for binary content generated via:
```
data "template_cloudinit_config" "blob" {
  gzip = true
  base64_encode = false

  part {
    content_type = "text/x-shellscript"
    content = "echo foo"
  }
}

resource "aws_s3_bucket_object" "my_object" {
  bucket = "${aws_s3_bucket.my_bucket.id}"
  key = "data.bin"
  content = "${data.template_cloudinit_config.blob.rendered}"
  etag = "${md5(data.template_cloudinit_config.blob.rendered)}"
}

```

The etag in state seems correct and never changes, fetching the file from s3 and piping to md5sum matches etag value and never changes.  Yet aws_s3_bucket_object sees it as dirty and writes to s3 every time.

**Comment by wr0ngway** [comment]
Based on the display of the content, I'm guessing its failing a compare of binary vs text, but no idea why etag isn't taking precendence:
![image](https://cloud.githubusercontent.com/assets/3606/24677966/b4e36270-1956-11e7-8094-5bab766a471c.png)
