### ISSUE TITLE
EMR configurations field forcing new EMR cluster when path changes

### ISSUE THREAD

**Issue by cpower** [hashicorp/terraform#12047]
Hi there,

Running `terraform apply` on a Terraform managed EMR cluster that uses a path.module reference to configurations.json with remote state, when the path to the file changes, causes Terraform to destroy the EMR cluster and create a new one because the path to the configurations.json file is stored in the Terraform state which forces a new resource.

### Terraform Version
Terraform v0.8.5

### Affected Resource(s)
- aws_emr_cluster

### Terraform Configuration Files
```
resource "aws_emr_cluster" "emr" {
  name = "${var.cluster_name}"
  release_label = "${var.release_label}"
  applications  = ["${split(",",var.applications)}"]
  service_role  = "${var.service_role}"
  log_uri  = "s3n://${var.s3_bucket}"
  master_instance_type = "${var.master_instance_type}"
  core_instance_type   = "${var.core_instance_type}"
  core_instance_count  = "${var.core_instance_count}"
  ec2_attributes {
    key_name = "${var.ec2_key_name}"
    subnet_id = "${data.aws_subnet.subnet.id}"
    instance_profile = "${var.ec2_instance_profile}"
    service_access_security_group = "${var.security_groups["emr_service_access"]}"
    emr_managed_master_security_group = "${var.security_groups["emr_managed_master"]}"
    emr_managed_slave_security_group  = "${var.security_groups["emr_managed_slave"]}"
    additional_master_security_groups = "${var.security_groups["emr_additional_master"]}"
    additional_slave_security_groups  = "${var.security_groups["emr_additional_slave"]}"
  }
  configurations = "${path.module}/${var.configurations}"
}
```

### Expected Behavior
Updating a Terraform managed EMR cluster that uses a path.module reference to a configurations JSON file from a different path/machine when using remote state should not create and destroy a new EMR cluster.

### Actual Behavior
Running `terraform apply` on a Terraform managed EMR cluster that uses a path.module reference, causes Terraform to destroy the EMR cluster and create a new one because the path to the configurations.json file is stored in the Terraform state.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` to create an EMR cluster on MachineA that has a path.module reference to a configurations.json file (use remote state)
2. Move to MachineB or simply change the path to the Terraform code
3. Make no other changes and run`terraform apply`, Terraform should destroy the EMR cluster and create a new one

### References
Related Issues
https://github.com/hashicorp/terraform/issues/8754
https://github.com/hashicorp/terraform/issues/7927

**Comment by errriclee** [comment]
According to https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_emr_cluster.go#L764 you can specify the contents of the file as well, instead of the file path. Using a template_file as the value of configurations will work and not cause unnecessary diff's.

I have tested this with the 0.9.5. I did not check which version this first appeared.
