### ISSUE TITLE
datadog provider keeps updating monitor type from "query alert" to "metric alert"

### ISSUE THREAD

**Issue by PurrBiscuit** [hashicorp/terraform#12051]
### Terraform Version
0.8.7

### Affected Resource(s)
- datadog_monitor

### Terraform Configuration Files
```hcl
resource "datadog_monitor" "ordercontroller_create_opportunity_transaction" {
  count = "${lookup(var.monitor_flag, var.env)}"

  message           = "${var.app_name}: The [OrderController#create_opportunity](https://app.datadoghq.com/trace/resource/www/rails.request/bad2df95c385f8e5?end=1486422940380&env=prod&paused=false&start=1486419340380) transaction has had more than ${var.error_threshold} errors in the past minute @pagerduty-content"
  name              = "${var.app_name}: OrderController#create_opportunity Transaction Errors"
  notify_no_data    = false
  query             = "sum(last_1m):sum:trace.rails.request.errors{env:prod,app:www,resource:bad2df95c385f8e5}.as_count() > ${var.error_threshold}"
  renotify_interval = 30
  type              = "metric alert"

  thresholds {
    ok       = "0"
    warning  = "3"
    critical = "${var.error_threshold}"
  }
}
```

### Expected Behavior
No changes should be detected on this resource after the first terraform run that introduces these monitors to datadog.

### Actual Behavior
We're seeing the monitor type keep changing in subsequent terraform runs from "query alert" to "metric alert" (even though it's been a "metric alert" since it was created and it's showing up as a "metric alert" in datadog currently.)

![](http://drops.articulate.com/ivaL+)

### Steps to Reproduce
1. add the `datadog_monitor` resource with a type of "metric_alert".
2. run a `terraform apply` to see the monitor get added to your datadog acount.
3. run a `terraform plan` immediately after this with no changes being introduced and see the following output.

```
~ datadog_monitor.ordercontroller_create_opportunity_transaction
    type: "query alert" => "metric alert"

~ datadog_monitor.ordercontroller_order_transaction
    type: "query alert" => "metric alert"

~ datadog_monitor.ordercontroller_pay_transaction
    type: "query alert" => "metric alert"
```

**Comment by techjanitor** [comment]
DataDog itself is changing the type to 'query alert' on their side after you submit it. If you change the type in Terraform you won't see the message anymore.

**Comment by PurrBiscuit** [comment]
thanks @techjanitor, changing it to a `query alert` did stop the issue for us.
