### ISSUE TITLE
Feature Request: aws_ebs_volume - Support Elastic EBS Resizes

### ISSUE THREAD

**Issue by jaredledvina** [hashicorp/terraform#12052]
### Terraform Version
```
❯ terraform -v
Terraform v0.8.6
```

### Affected Resource(s)
- aws_ebs_volume

It'd be amazing if terraform supported the new Elastic EBS volume feature on AWS EC2. https://aws.amazon.com/blogs/aws/amazon-ebs-update-new-elastic-volumes-change-everything/

**Comment by stack72** [comment]
Hi @jaredledvina 

I am pleased to say that I have already added this to master and it will be available in Terraform 0.8.8 :)

Paul
