### ISSUE TITLE
Crash Report When Attempting Variation of "Using Variables With Count"

### ISSUE THREAD

**Issue by lusid** [hashicorp/terraform#1206]
I was following the example in the documentation (https://www.terraform.io/docs/configuration/resources.html#using-variables-with-count), but trying to place it deeper in a variable configuration instead of at the top level.

This is the variable causing the crash:
variable "config" {
	default = {
		other_stuff = "whatever"
		server_ips = {
			"0" = "192.168.10.10"
			"1" = "192.168.10.11"
			"2" = "192.168.10.12"
			"3" = "192.168.10.13"
		}
	}
}

When I remove this from the file, it seems to be ok.

2015/03/15 02:58:58 [INFO] Terraform version: 0.3.7  0bc0c03fece07c4f21ee5195743116a4d418f234+CHANGES
2015/03/15 02:58:58 Detected home directory from env var: /Users/marc
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: atlas = /usr/local/bin/terraform-provider-atlas
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: aws = /usr/local/bin/terraform-provider-aws
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: cloudflare = /usr/local/bin/terraform-provider-cloudflare
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: cloudstack = /usr/local/bin/terraform-provider-cloudstack
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: consul = /usr/local/bin/terraform-provider-consul
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: digitalocean = /usr/local/bin/terraform-provider-digitalocean
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: dnsimple = /usr/local/bin/terraform-provider-dnsimple
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: google = /usr/local/bin/terraform-provider-google
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: heroku = /usr/local/bin/terraform-provider-heroku
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: mailgun = /usr/local/bin/terraform-provider-mailgun
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: null = /usr/local/bin/terraform-provider-null
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: file = /usr/local/bin/terraform-provisioner-file
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: local-exec = /usr/local/bin/terraform-provisioner-local-exec
2015/03/15 02:58:58 [DEBUG] Discoverd plugin: remote-exec = /usr/local/bin/terraform-provisioner-remote-exec
2015/03/15 02:58:58 Detected home directory from env var: /Users/marc
2015/03/15 02:58:58 [DEBUG] Attempting to open CLI config file: /Users/marc/.terraformrc
2015/03/15 02:58:58 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2015/03/15 02:58:58 Detected home directory from env var: /Users/marc
2015/03/15 02:59:01 waiting for all plugin processes to complete...
panic: Unknown variable type: 0x0

goroutine 1 [running]:
github.com/hashicorp/terraform/terraform.(*Context).Input(0xc20802c320, 0x3, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/terraform/context.go:179 +0xc5a
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc20805e0e0, 0xc20800a010, 0x0, 0x0, 0xc2080368b0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/command/apply.go:124 +0x1108
github.com/mitchellh/cli.(*CLI).Run(0xc20802cf00, 0xc2080aaf90, 0x0, 0x0)
	/Users/mitchellh/code/go/src/github.com/mitchellh/cli/cli.go:100 +0x3ce
main.wrappedMain(0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/main.go:150 +0xb70
main.realMain(0x0)
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/main.go:82 +0x923
main.main()
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/main.go:18 +0x1f

goroutine 5 [syscall]:
os/signal.loop()
	/Users/mitchellh/code/3rdparty/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/Users/mitchellh/code/3rdparty/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [chan receive]:
main.func·014()
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/commands.go:132 +0x52
created by main.makeShutdownCh
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/commands.go:135 +0x1b4

goroutine 9 [semacquire]:
sync.(*Cond).Wait(0xc2080dc030)
	/Users/mitchellh/code/3rdparty/go/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2080dc000, 0xc2080de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc20803e1a0, 0xc2080de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/io/pipe.go:134 +0x5b
bufio.(*Scanner).Scan(0xc208060380, 0x0)
	/Users/mitchellh/code/3rdparty/go/src/bufio/scan.go:180 +0x688
github.com/hashicorp/terraform/command.func·006()
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/command/meta.go:346 +0x3d
created by github.com/hashicorp/terraform/command.(*Meta).flagSet
	/Users/mitchellh/code/go/src/github.com/hashicorp/terraform/command/meta.go:349 +0x519

**Comment by mitchellh** [comment]
Yeah this isn't valid you can't nest variables like that, but we should catch this error more cleanly.

**Comment by mitchellh** [comment]
Oh this is fixed in master, we added more validation. Hurray!
