### ISSUE TITLE
Programming support for terraform

### ISSUE THREAD

**Issue by siddheshb** [hashicorp/terraform#12074]
Hi,

Please can you let us know if Terraform developers are thinking about programming support. We find that there is a necessity for one so that it would help us to reuse the resources in better way.

**Comment by stack72** [comment]
Hi @siddheshb 

Thanks for getting in contact with us. Please can you give us a bit more of an idea what you mean about `programming support`? Is this a specific enhancement required for one of the providers?

Thanks

Paul

**Comment by mitchellh** [comment]
I'm guessing you mean scripting Terraform itself? In that case, that is exactly the use case we had in mind for the JSON inputs for Terraform. Just write in your favorite language, generate inputs to Terraform, and call out to it.

There is some additional work we'd like to do around better machine-readable outputs (JSON probably) from commands but many people are doing this very successfully with Terraform today.

**Comment by siddheshb** [comment]
Thanks @mitchellh for the reply.
