### ISSUE TITLE
heroku_app resource does not support import

### ISSUE THREAD

**Issue by davidski** [hashicorp/terraform#12087]
Feature request to support import on the `heroku_app` resource 😄 

### Terraform Version
Terraform 0.8.7

### Affected Resource(s)
- heroku_app

### Expected Behavior
Should import an existing app.

### Actual Behavior
Generates an error that import is not supported.

### Steps to Reproduce
run `terraform import heroku_app.foo`

**Comment by abienkowski** [comment]
+1
