### ISSUE TITLE
terraform init -

### ISSUE THREAD

**Issue by owenmorgan** [hashicorp/terraform#12085]
hello, when using 0.9.0-beta1 and performing -

`terraform init -backend=s3 -backend-config=bucket=hello-world -backend-config=key=terraform.tfstate -backend-config=region=eu-west-1`

I get the error: 

`invalid boolean value "s3" for -backend: strconv.ParseBool: parsing "s3": invalid syntax
`

**Comment by greenboxal** [comment]
The commands to initialize the remote backend changed on 0.9.0. You can check `website/source/docs/backends/config.md` for information on the new method.

Also, you can build terraform website to get the full updated documentation. Just run `make` on the website directory.

**Comment by owenmorgan** [comment]
sounds good thanks .any idea how to configure an s3 bucket in this way? the example only shows a consul backend.

https://github.com/hashicorp/terraform/blob/master/website/source/docs/backends/config.html.md

**Comment by minamijoyo** [comment]
Maybe this?
https://github.com/hashicorp/terraform/blob/master/website/source/docs/backends/types/s3.html.md

**Comment by owenmorgan** [comment]
Perfect. Thank you.

**Comment by owenmorgan** [comment]
one issue i have with this is if the remote bucket is variable. using a variable in the config doesnt seem to get picket up as a variable.

```
terraform {
  required_version = ">= 0.8.0"

  backend "s3" {
    bucket = "${var.terraform_state_bucket}"
    key    = "terraform.tfstate"
    region = "eu-west-1"
  }
}
```

> terraform init 

terraform.tfstate >> 
```

"backend": {
        "type": "s3",
        "config": {
            "bucket": "${var.terraform_state_bucket}",
            "key": "terraform.tfstate",
            "region": "eu-west-1"
        },
        "hash": 9090006319481010225
},
```

**Comment by mitchellh** [comment]
@owenmorgan Backend config doesn't support variables, we're validating this in the next beta version. You should use `-backend-config` files for parameterization. 

Looks like everything is working otherwise though. Thanks to others for pointing out the new docs!
