### ISSUE TITLE
Allow printing and/or saving output vars

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1209]
It would be nice if terraform could be moving a bit towards the concept of _"stacks"_ and sharing variables between these stacks. Inspiration [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html).

Module is a nice concept for code reuse, putting aside the fact that [dependencies don't work well yet](https://github.com/hashicorp/terraform/issues/1178), it's generally not always the right solution for all problems anyway.

I'm not sure how the right API & wrapper should look like, but here's an idea:

```
.
├── networking-stack
│   ├── template.tf
│   ├── terraform.tfout
│   └── networking-input.tfvars
├── computing-stack
│   ├── template.tf
│   ├── terraform.tfout
│   ├── networking-input.tfvars (symlink to ../networking-stack/terraform.tfout)
│   └── computing-input.tfvars
...
```

Which already expects #1084 to be solved.

I believe **it should have a special extension** (`tfout` or any similar) so that if it gets generated into the same directory, it is not picked up in next run as an input.
I believe **it should be generating this output by default** to any default location (`terraform.tfout` ?) so that user doesn't have to think about passing extra option for each stack. More importantly the only way I can get to the output now is to open a (possibly giant) `*.tfstate` and look for `outputs` which isn't really nice experience.

This could also be helpful for #610

**Comment by radeksimko** [comment]
I'm just looking at `terraform output` and thinking that it could be the right place for such functionality...

1. We could make the argument `NAME` optional and if it's not provided, it will simply print all the variables in format `key=value` (obviously escaped strings if necessary).
2. We could also add a new argument `-out=path` which would write the output to that file instead of stdout. Default may still stay `/dev/stdout`.

```
Usage: terraform output [options] NAME

  Reads an output variable from a Terraform state file and prints
  the value.

Options:

  -state=path      Path to the state file to read. Defaults to
                   "terraform.tfstate".
```

**Comment by mitchellh** [comment]
So, `tfvars` format is just JSON, so I think we can add a `-format=json` flag to `terraform output` to do this. I like it.

**Comment by ketzacoatl** [comment]
+1

**Comment by migibert** [comment]
+1

**Comment by donovanmuller** [comment]
+1

**Comment by chiriaev** [comment]
+1

**Comment by grebois** [comment]
+1

**Comment by mitchellh** [comment]
Going to centralize on Radek's mega issue since this is fairly simple (#2460)
