### ISSUE TITLE
Taking care of nested maps in Terraform

### ISSUE THREAD

**Issue by siddheshb** [hashicorp/terraform#12105]
Hi,

I am using azure and have a main configuration snippet similar to below

module "sample" {
    source = "../../.."
    sample_spec = {
                       sample1 = {
                                   sample_list1=["s1list1", "s1list2"]
                                   sample_list2=["s2list1", "s2list2"]
                                 }
                                 
                       sample2 = {
                                   sample_list1=["s1list1", "s1list2"]
                                   sample_list2=["s2list1", "s2list2"]
                                 }
                   }
}

I wish to extract the list ["s1list1", "s1list2"] in the underlying resource. Terraform is giving me the folPlease let me know if i can achieve this.

**Comment by siddheshb** [comment]
Hi,

I am finding the use case where I can extract complex data structures.

**Comment by mitchellh** [comment]
There are a number of other issues tracking nested maps/lists. We don't currently support this in Terraform (though we don't error either). We hope to solve this soon.
