### ISSUE TITLE
provider/aws: Invalid protocol aws_network_acl_rule

### ISSUE THREAD

**Issue by MattiasGees** [hashicorp/terraform#12103]
### Terraform Version
v0.8.7

### Affected Resource(s)
- aws_network_acl_rule

### Terraform Configuration Files
```hcl
resource "aws_network_acl" "nat" {
  vpc_id     = "${var.vpc_id}"
  subnet_ids = ["${var.nat_subnets}"]
}

resource "aws_network_acl_rule" "nat_ingress_vrrp_nat" {
  network_acl_id = "${aws_network_acl.nat.id}"
  rule_number    = "1110"
  egress         = false
  protocol       = 112
  rule_action    = "allow"
  cidr_block     = "10.20.20.0/24"
}
```

### Debug Output
```
* aws_network_acl_rule.nat_ingress_vrrp_nat: Invalid Protocol 112 for rule 1110
```

### Expected Behavior
That the `terraform plan` completes without giving any errors. 

### Actual Behavior
`terraform plan` gives errors at the end of the plan to say that 112 is an invalid protocol. While at the seem time this is saved in the terraform state file with the correct protocol. It is also correctly deployed on the AWS console
I looked it up in the protocol numbers and `112` is present in that list http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

**Comment by stack72** [comment]
Closed via #12107
