### ISSUE TITLE
Question / Proposal regarding new backend config

### ISSUE THREAD

**Issue by antonosmond** [hashicorp/terraform#12114]
### Terraform Version
Terraform v0.9.0-beta1 (4e96da57eef7b1bfd6e2752839e897f932752656)

Currently, the new backend configs under the `terraform {}` block don't support interpolations, however as well as having a default backend config there is the ability to specify additional config during the `terraform init` with the `-backend-config=path` flag. This is great, but if you only want to define a single additional value, creating a separate file for it seems unnecessary. As an example, I'm using an S3 backend and want my S3 key to include the environment I'm deploying to. The S3 key is my only value that's different from the main backend config. To achieve this in the current setup, I'd have to create separate files for dev, test, production etc, with just the S3 key value in then run `terraform init -backend-config=path/to/env/config`. It'd be nice if there was a shorthand way to define these, maybe with environment variables or something e.g. `TF_BACKEND_S3_KEY=somevalue`
That way I could avoid littering my repo with additional config files and on deployments just set the env var to the value I want before running the init.

**Comment by nanoz** [comment]
You may find an answer to this in https://github.com/hashicorp/terraform/pull/12067

**Comment by antonosmond** [comment]
Thanks! I appreciate backends are still in beta and I'm sure everyone has big ideas! 
TBH I decided having separate configs per env wasn't such a bad idea and have gone with that for now. In general the whole backend concept is awesome and at my company we've been waiting a LONG time for this and had to get by with wrapper scripts all over the place to configure the remotes! So glad to see proper backends are finally here! 😃  I'll close this issue.
