### ISSUE TITLE
Allow aws_acm_certificate to query the most recent certificate

### ISSUE THREAD

**Issue by fabian-dev** [hashicorp/terraform#12111]
By now using the `aws_acm_certificate` data source is no option for us. This is because we want to renew our ACM certs on a regular basis.

During our renewal phase and after issuing new certs, there will be more than one cert present (with equal domain names).
TF will then fail with:
```
data.aws_acm_certificate.xxx: Multiple certificates for domain "xxx" found in this region.
```

If I could use a most_recent=true flag (like it is with the `aws_ami` data source), I could gracefully apply the TF configuration during the renewal phase and switch to new certs.

I would appreciate your thought on this.

Cheers Fabian

**Comment by catsby** [comment]
You can now filter with type in #15063

**Comment by fabian-dev** [comment]
Awesome!

**Comment by fabian-dev** [comment]
I'm sorry. It seems #15063 does not solve my use case:

Renewed and approved ACM certificates always have type `AMAZON_ISSUED`. This means filtering by type does still not allow me to query for the latest certificate for the same domain. It is valid to have more than one approved ACM certificate for the same domain name (that are all of the same type as well). I still think a `most_recent` flag would capture that case.

@catsby: Can you reopen this issue?

**Comment by catsby** [comment]
Apologies! I may have hastily closed this thinking #15063 fixed it. Thanks for the ping, I'll reopen it 😄

**Comment by catsby** [comment]
Hey @fabian-dev I'm not sure how to do this with the API given, there does not appear to be any date information given

- http://docs.aws.amazon.com/acm/latest/APIReference/Welcome.html

We don't have any guarantee on the ordering we're given

**Comment by jerrycattell** [comment]
@catsby it looks like if you had multiple certificates matching the domain name/status/type, you could call DescribeCertificate (http://docs.aws.amazon.com/acm/latest/APIReference/API_DescribeCertificate.html) on each of those certificates and use one of the dates provided:
* CreatedAt
* ImportedAt
* IssuedAt
* NotBefore

While it may be a different feature, another potential way to avoid receiving multiple certificates for the same domain name would be to allow tags to be specified in the data source and check that the certificate has the appropriate tags if the domain name/status/type match.
