### ISSUE TITLE
Shut down vms cleanly during 'destroy' operation.

### ISSUE THREAD

**Issue by Rotwang** [hashicorp/terraform#12116]
Hi,

I've got a compute instance on my openstack with blockstorage volume attached to it. However if I destroy the compute instance and recreate it with the same volume as previously (volume is not destroyed) then data is missing that was not flushed during the destroy process.

**Comment by jtopjian** [comment]
Hi @Rotwang,

I believe the [`stop_before_destroy`](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#stop_before_destroy) argument  should help you out here. 

I'm going to close this issue, but do let me know if you're having a problem with it, though, and I'll re-open it.

Thanks,
Joe
