### ISSUE TITLE
[Feature Request] module dependency manager

### ISSUE THREAD

**Issue by knehring** [hashicorp/terraform#12117]
Currently managing versions of external modules can be a pain. In order to pull in a external module most are familiar with doing something similar to this:

module "vpc" {
  source = "ssh://git@{GIT HOST}/ter/vpc.git"
  name = "dev-vpc"
}

This will pull the module from the master branch, but in order to version this we need to change the source to be something like:

source = "ssh://git@{GIT HOST}/ter/vpc.git?ref=v1.0.0

There are some problems with this, first if we are using the module multiple times we can either A.) place the version in a variable, or B.) update the ref in multiple places.

At Cars.com we use a different approach that we would like to see built into terraform itself.

The Terrafile.

The Terrafile is similar to a Gemfile and is just simple yaml. It is accompanied by a Rakefile to parse out the information and pull the desired modules into our current environment. This gives us a central place to describe the modules used in our infrastructure and allows us to manage different versions of a module across different environments.

See [Terraform @ Cars.com: Implementing the Terrafile](https://tech.cars.com/terraform-cars-com-dd1291e46c88) for a more in depth explanation.

**Comment by mitchellh** [comment]
Thanks for this request! We plan on doing something like this "soon" (let's say sometime this year but not trying to make promises). Some of the core feature work necessary to make this happen is under way now. There is another issue tracking module versioning and such so I'll leave it at that.

Conclusion: I agree with you! We're working on it, and hopefully we'll have it for you soon. :)

**Comment by knehring** [comment]
Is there a link to the other issue already open? I didn't see one, thanks if I can contribute I will

**Comment by mitchellh** [comment]
@knehring There should be. If not, don't worry because I actually just came out of a meeting where we have been planning this out. :) I'll let you know and open a community issue when we have more data.

**Comment by ddi-wtag** [comment]
Any progress on that front? We would be very interested in that feature.

**Comment by AdamCoulterOz** [comment]
An open package manager repo dependency manager like; npm or nuget but for terraform modules... would really like that!!
