### ISSUE TITLE
enable lists to be assigned to variables

### ISSUE THREAD

**Issue by chrisferry** [hashicorp/terraform#1212]
I'd like to be able to do the following:
variables.tf-
variable "approved_ips" {
    description = "IPs allowed into the network"
    default = ["10.0.0.1/32","10.0.0.2/32"]
}

main.tf-
	ingress {
		from_port   = 22
		to_port     = 22
		protocol    = "tcp"
		cidr_blocks = "${var.approved_ips}"
	}

Currently I receive:
* Variable 'approved_ips': must be string or mapping
  * aws_security_group.use1-bastion: ingress.0.cidr_blocks: should be a list

**Comment by mitchellh** [comment]
In 0.4 please workaround this with `split` and `join`.
