### ISSUE TITLE
 openstack_compute_instance_v2 server error parsing time null error

### ISSUE THREAD

**Issue by tjend** [hashicorp/terraform#12126]
Hi @jtopjian 

Since terraform version 0.8.5, I have been getting the following error when running terraform plan against an existing openstack_compute_instance_v2 instance.

Error refreshing state: 1 error(s) occurred:
* openstack_compute_instance_v2.testing-123: server: parsing time "null" as ""2006-01-02T15:04:05Z07:00"": cannot parse "null" as """

I don't get this error with version 0.8.4.

### Terraform Version
versions 0.8.5, 0.8.6, 0.8.7

### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl
provider "openstack" {}
resource "openstack_compute_instance_v2" "test-binarylane" {
  name = "test.binarylane"

  image_id  = "39d70d36-dc1d-49f3-9953-98df6bbf6304"
  flavor_id = "plan-512"

  key_pair = "sshkey"

  connection {
    user        = "root"
    timeout     = "3m"
    private_key = "${file("~/.ssh/sshkey.pem")}"
  }
}
```

### Debug Output
failure with 0.8.7 - https://gist.github.com/tjend/4f52f829da65bb84d2e8acad0bac3610
success with 0.8.4 - https://gist.github.com/tjend/1100d0264c0cf32c56ff4911c61ca6a7

### Expected Behavior
Terraform plan should show no changes.

### Actual Behavior
Terraform plan showed an error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. have an existing instance in the tfstate, upgrade to terraform > 0.8.4
2. terraform plan

### Important Factoids
Binarylane's openstack implementation is very minimal, but works to create and destroy instances with 0.8.4.

### References
https://groups.google.com/forum/#!topic/terraform-tool/X_ZhH9UD168

**Comment by jtopjian** [comment]
@tjend Thank you for the report. There was an update to underlying Gophercloud library for parsing time and I bet this is where the error is coming from. I will look into this and figure out what's going on.

**Comment by jtopjian** [comment]
@tjend per discussion in https://github.com/gophercloud/gophercloud/issues/269, BinaryLane might be altering the response. 

The next release of Terraform will have an option to show all HTTP requests and responses which will help out for this. Alternatively, you could compile the latest Terraform from source and get access to that feature now. if you'd like to do that, let me know if you need help compiling the binary.

To use the feature, you'd do something like:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform plan
```

**Comment by tjend** [comment]
This issue went away with terraform v0.8.8.
