### ISSUE TITLE
Terraform v0.8.7 does not include slice interpolation

### ISSUE THREAD

**Issue by darrenswhite** [hashicorp/terraform#12131]
According to the CHANGELOG for v0.8.7 a new interpolation function `slice` is added. However this is not the case as it is not present.

### Terraform Version
v0.8.7

### Expected Behavior
Terraform should have compiled the files correctly.

### Actual Behavior
Terraform failed to compile the files. 

```
* 1:29: unknown function called: slice in:

${slice(libvirt_volume.storage.*.id, count.index * var.volume_storage_count, (count.index + 1) * var.volume_storage_count - 1)}
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Using libvirt plugin.

### References
- https://github.com/hashicorp/terraform/blob/v0.8.7/CHANGELOG.md
- https://github.com/hashicorp/terraform/pull/9729

**Comment by stack72** [comment]
Hi @darrenswhite 

My most sincere apologies here - you are indeed correct! This was merged to master and never cherry-picked to the correct branch

I have just done that and it will be available in Terraform 0.8.8 soon ™️ 

Sorry again for this

Paul
