### ISSUE TITLE
aws_network_interface.private_ips does not flatten 

### ISSUE THREAD

**Issue by mcraig88** [hashicorp/terraform#12143]
### Terraform Version
v0.8.7

### Affected Resource(s)
Please list the resources as a list, for example:
-aws_network_interface

### Terraform Configuration Files
```

resource "aws_network_interface" "net-interface-infra-dns" {
  count           = "${length(var.admin_subnet_cidr)}"
  subnet_id       = "${element(aws_subnet.idx.*.id, count.index)}"
  private_ips     = ["${cidrhost(element(aws_subnet.idx.*.cidr_block, count.index), 150)}"]
  security_groups = ["${aws_security_group.infra_common_endpoints.id}", "${aws_security_group.infra_dns.id}", "${aws_security_group.infra_s3_endpoints.id}", "${aws_security_group.infra_ecp_domainmembers.id}"]

  tags {
    "Name" = "${var.env_prefix}-INFRA-DNS-${upper(replace(element(var.availability_zones, count.index), var.region, ""))}"
  }

  lifecycle {
    create_before_destroy = false
  }
}


resource "aws_vpc_dhcp_options" "test_dns_resolver" {
  provider            = "aws.${var.region}"
  domain_name         = "test ${var.dhcp_options_domain_name}"
  
  domain_name_servers = ["${aws_network_interface.net-interface-infra-dns.*.private_ips}"]
  ntp_servers		 = ["${aws_network_interface.net-interface-infra-dns.*.private_ips}"]

  tags {
    Name = " test "
  }
}

```

### Debug Output
'''
Error running plan: 6 error(s) occurred:

* module.us-west-2.module.vpc.aws_vpc_dhcp_options.test_dns_resolver: domain_name_servers.0 must be a single value, not a list
* module.us-west-2.module.vpc.aws_vpc_dhcp_options.test_dns_resolver: domain_name_servers.1 must be a single value, not a list
* module.us-west-2.module.vpc.aws_vpc_dhcp_options.test_dns_resolver: domain_name_servers.2 must be a single value, not a list
* module.us-west-2.module.vpc.aws_vpc_dhcp_options.test_dns_resolver: ntp_servers.0 must be a single value, not a list
* module.us-west-2.module.vpc.aws_vpc_dhcp_options.test_dns_resolver: ntp_servers.1 must be a single value, not a list
* module.us-west-2.module.vpc.aws_vpc_dhcp_options.test_dns_resolver: ntp_servers.2 must be a single value, not a list
'''

### Expected Behavior
aws_network_interface's private_ips should expand to a list which can be passed to other properties expecting a list input.

### Actual Behavior
Object resolves to a single value instead of a list.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
I believe this is related to the following:
- https://github.com/hashicorp/terraform/pull/11042
- https://github.com/hashicorp/terraform/issues/8696

**Comment by 2rs2ts** [comment]
This is exactly the same issue as #8696
