### ISSUE TITLE
aws launch_configuration ebs_block_device encrypted not taking effect

### ISSUE THREAD

**Issue by craiggenner** [hashicorp/terraform#12158]
Hi there,

I'm having an issue where a launch config with an encrypted ebs volume is not being encrypted.  Any ideas?  I suspect the problem is either my config, or AWS but want to be sure.

### Terraform Version
Terraform v0.8.7

### Affected Resource(s)
- aws_launch_configuration

### Terraform Configuration Files
```hcl
resource "aws_launch_configuration" "agent" {
...
  ebs_block_device {
    device_name = "/dev/xvdd"
    volume_size = "20"
    volume_type = "gp2"
    encrypted   = true
  }
}
```

### Debug Output
https://gist.github.com/craiggenner/54e4823048110608393559f2a50a4769

### Expected Behavior
In the AWS console I see the ebs block device is encrypted:
`Encrypted: Encrypted`

### Actual Behavior
In the AWS console I then see the ebs block device as not encrypted:
`Encrypted: Not Encrypted`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Look in the AWS console

### Important Factoids
Nothing special

**Comment by senax** [comment]
I am seeing the same problem and found this: 
[http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html)

> Amazon EBS Encryption Unsupported
You can specify encrypted EBS volumes in the launch specification for your Spot instances, but these volumes are not encrypted.

So not sure if there is an easy fix. aws_ebs_volume and aws_volume_attachment does work with encryption but doesn't always attach in one run as the instance is not in running state yet.

**Comment by craiggenner** [comment]
oh great :-(

Good find.  Looks like I'm going to have to rethink how this is done.

**Comment by senax** [comment]
Just starting out with terraform and not sure if there is a way to make it wait for a spot instance to be in running state.
`1 error(s) occurred:
aws_volume_attachment.data_attach.1: [WARN] Error attaching volume (vol-0...7) to instance (i-0...48), message: "Instance 'i-0...48' is not 'running'.", code: "IncorrectState"`

**Comment by stack72** [comment]
Looks like I can close this out - if it's not a supported feature then I don't believe it's a Terraform bug

Thanks for the report

Paul
