### ISSUE TITLE
ignition_filesystem: Should always pass a create section - possibly empty

### ISSUE THREAD

**Issue by maikzumstrull** [hashicorp/terraform#12152]
### Terraform Version
Terraform v0.8.7

### Affected Resource(s)
- ignition_filesystem

### Expected Behavior
Booted CoreOS instance should create a filesystem

### Actual Behavior
If neither "force" nor "options" is set to a non-default value, Terraform doesn't pass a "create" section in the Ignition config. This is interpreted by Ignition as "you're not supposed to create this filesystem", see https://coreos.com/ignition/docs/latest/configuration.html:
"create (object): contains the set of options to be used when creating the filesystem. A non-null entry indicates that the filesystem shall be created."

**Comment by mcuadros** [comment]
I will take a look ASAP
