### ISSUE TITLE
Clarification required on consul_service, consul_agent_service, consul_catalog_entry resources

### ISSUE THREAD

**Issue by blalor** [hashicorp/terraform#12163]
From looking at the documentation, it's unclear how a user should choose between the above three resources.  Furthermore, both `consul_service` and `consul_agent_service` appear to do effectively the same thing, although the docs for `consul_service` indicate that registering a service with the catalog is something intended for the future.  I believe the design of `consul_service` is confusing: if you configure the provider to use a non-local agent (such as `consul.service.consul:8500` or some other mechanism that could non-deterministically choose a different agent on every Terraform plan or apply), subsequent Terraform invocations can fail if they're unable to find a service that was registered with a different agent previously.

**Comment by sean-** [comment]
@blalor Entirely valid points, and yeah, I agree.  It's one of the reasons the "consul_nodes" doesn't exist and instead I named it `consul_catalog_nodes` (same with "consul_self" vs `consul_agent_self`).  The lack of clarity between "catalog" vs "agent" is a common sticking point, but the implicit behavior with the missing implementation detail is problematic.  I'll update the docs soon.  Thank you for highlighting this.
