### ISSUE TITLE
Add Vault Provider with Resources To Manage Mounts, Backends and Policies (Not Secrets)

### ISSUE THREAD

**Issue by ekristen** [hashicorp/terraform#12167]
Terraform seems like the perfect tool to used to manage state with respect to managing backends, mounts, and overall configuration of vault (minus secrets).

Using terraform to manage policies, mounts, roles, and other basic configuration.

This is an interesting idea https://www.hashicorp.com/blog/codifying-vault-policies-and-configuration.html but having it always post the data to the endpoints seems like a way to cause problems even though it is idempotent.

Using terraform to manage and maintain state to know when a change is going to be made to me makes more sense.

**Comment by nickwales** [comment]
This is a great start. Would be nice to see providers for
- audit backends
- auth backend configurations such as for AWS roles.
