### ISSUE TITLE
Experimental Feature Failure bug report - refresh operation: Real and shadow states do not match! 

### ISSUE THREAD

**Issue by notjames** [hashicorp/terraform#12172]
While running `terraform refresh`, the following error occurred:

Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

You can report an issue at: https://github.com/hashicorp/terraform/issues

The failure was written to "terraform-error-1487788827.log". Please
double check this file contains no sensitive information and report
it with your issue.

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.

Per this request, I am reporting this bug.

### Terraform Version
Terraform v0.8.6

### Affected Resource(s)
- aws vpc, subnet, security-group, iam

### Terraform Configuration Files
please provide link to your GPG key.

### Debug Output
$ ./tf-wrapper --region us-west-2 --profile default --env test --priv-key ~/.ssh/companyproject.pem --credentials /some/user/path/company-projects/github/aws/project/terraform/credentials/provisioner_credentials --tf-command refresh
Overriding request for bastion credentials.
Previous state exists. Use -R switch to override.
FINAL VARS are: -var azones='["us-west-2a","us-west-2b","us-west-2c"]' -var region=us-west-2 -var environment=test -var private-key=/some/user/path/.ssh/companyproject.pem -var privkey-name=companyproject.pem -var privkey-path=/some/user/path/.ssh -var ssh_key_name=companyproject -var aws-id=XXXXXXXXXXXXXXXXXXXX -var aws-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -var aws-creds-profile=default -var credentials-path=/some/user/path/company-projects/github/aws/project/terraform/credentials -var action=refresh

Get: file:///some/user/path/company-projects/github/aws/project/terraform/base/test/phase1 (update)
Get: file:///some/user/path/company-projects/github/aws/project/terraform/base/test/phase1/vpc (update)
Get: file:///some/user/path/company-projects/github/aws/project/terraform/base/test/phase1/global (update)
Get: file:///some/user/path/company-projects/github/aws/project/terraform/base/test/phase1/chef/automate (update)
Get: file:///some/user/path/company-projects/github/aws/project/terraform/base/test/phase1/vpc/subnets/private (update)
Get: file:///some/user/path/company-projects/github/aws/project/terraform/base/test/phase1/vpc/subnets/public (update)
Get: file:///some/user/path/company-projects/github/aws/project/terraform/base/test/phase1/global/iam (update)
Get: file:///some/user/path/company-projects/github/aws/project/terraform/base/test/phase1/global/dns (update)
module.phase1.global.dns.aws_route53_zone.aws-prod-tld-sub: Refreshing state... (ID: Z129GIJKHK5DZ4)
module.phase1.vpc.aws_vpc.project: Refreshing state... (ID: vpc-f1006396)
module.phase1.global.dns.aws_route53_zone.aws-env-tld-sub: Refreshing state... (ID: Z33JHPRQING4O)
module.phase1.chefautomate.aws_iam_policy.opsworks-cm-ec2-role-for-ssm: Refreshing state... (ID: arn:aws:iam::999999999999:policy/service-role/AmazonEC2RoleforSSM-project)
module.phase1.chefautomate.aws_iam_role.chef-associations: Refreshing state... (ID: tf-ops-chefautomate-instance-autoassociations)
module.phase1.chefautomate.aws_iam_policy.opsworks-cm-instance-profile: Refreshing state... (ID: arn:aws:iam::999999999999:policy/service-role/AWSOpsWorksCMInstanceProfileRole-project)
module.phase1.chefautomate.aws_iam_policy.project-opsworks-chefautomate-policy: Refreshing state... (ID: arn:aws:iam::999999999999:policy/tf-ops-chefautomate-instance-autoassociation)
module.phase1.chefautomate.aws_iam_role.opsworks-cm-service-role: Refreshing state... (ID: aws-opsworks-cm-service-role-for-project)
module.phase1.chefautomate.aws_iam_role.opsworks-ec2-role: Refreshing state... (ID: aws-opsworks-cm-ec2-role-for-project)
module.phase1.global.iam.aws_iam_user.auto-provisioner: Refreshing state... (ID: provisioner)
module.phase1.chefautomate.aws_iam_policy.opsworks-cm-service-policy: Refreshing state... (ID: arn:aws:iam::999999999999:policy/service-role/AWSEC2RoleforSSM-project)
module.phase1.chefautomate.aws_iam_role_policy_attachment.chef-association: Refreshing state... (ID: tf-ops-chefautomate-instance-autoassociations-00c25f472ac01803a177ed7403)
module.phase1.chefautomate.aws_iam_instance_profile.opsworks-cm-service-role: Refreshing state... (ID: aws-opsworks-cm-service-instance-profile-project)
module.phase1.chefautomate.aws_iam_role_policy_attachment.opsworks-cm-instance-profile: Refreshing state... (ID: aws-opsworks-cm-ec2-role-for-project-00c25f472ac01803a177ed7400)
module.phase1.global.iam.aws_iam_user_policy.provisioner-ChefAutomate: Refreshing state... (ID: provisioner:Provisioner-OpsWorks-CM)
module.phase1.global.iam.aws_iam_access_key.auto-provisioner: Refreshing state... (ID: XXXXXXXXXXXXXXXXXXXX)
module.phase1.chefautomate.aws_iam_role_policy_attachment.opsworks-cm-ec2-role-for-ssm: Refreshing state... (ID: aws-opsworks-cm-ec2-role-for-project-00c25f472ac01803a177ed7401)
module.phase1.vpc.aws_security_group.bastion: Refreshing state... (ID: sg-b85b16c0)
module.phase1.vpc.aws_default_route_table.drt: Refreshing state... (ID: rtb-ad1919ca)
module.phase1.vpc.aws_security_group.public: Refreshing state... (ID: sg-ba5b16c2)
module.phase1.vpc.aws_default_security_group.default: Refreshing state... (ID: sg-cd5b16b5)
module.phase1.vpc.aws_security_group.vpn: Refreshing state... (ID: sg-b95b16c1)
module.phase1.vpc.aws_security_group.internal: Refreshing state... (ID: sg-bb5b16c3)
module.phase1.global.dns.aws_route53_record.aws-env-rec: Refreshing state... (ID: Z33JHPRQING4O_test.aws.companycloud.com._NS)
module.phase1.global.dns.aws_route53_record.aws-prod-rec: Refreshing state... (ID: Z129GIJKHK5DZ4_aws.companycloud.com._NS)
module.phase1.global.iam.aws_iam_user_policy_attachment.provisioner-AWS-SA: Refreshing state... (ID: provisioner-00c25f472ac01803a177ed7402)
module.phase1.chefautomate.aws_iam_role_policy_attachment.opsworks-cm-role: Refreshing state... (ID: aws-opsworks-cm-service-role-for-project-00c25f472ac01803a177ed7404)
module.phase1.vpc.private-subnets.aws_eip.nat: Refreshing state... (ID: eipalloc-2df6e14a)
module.phase1.vpc.private-subnets.aws_subnet.private.2: Refreshing state... (ID: subnet-955b65cd)
module.phase1.vpc.private-subnets.aws_subnet.private.1: Refreshing state... (ID: subnet-fe71cb99)
module.phase1.vpc.private-subnets.aws_subnet.private.0: Refreshing state... (ID: subnet-52f4281b)
module.phase1.vpc.public-subnets.aws_internet_gateway.public: Refreshing state... (ID: igw-ce7952aa)
module.phase1.vpc.public-subnets.aws_subnet.public.2: Refreshing state... (ID: subnet-945b65cc)
module.phase1.vpc.public-subnets.aws_subnet.public.0: Refreshing state... (ID: subnet-51f42818)
module.phase1.vpc.public-subnets.aws_subnet.public.1: Refreshing state... (ID: subnet-f271cb95)
module.phase1.vpc.private-subnets.aws_nat_gateway.private: Refreshing state... (ID: nat-07cc0dfbbc9d53bd2)
module.phase1.vpc.public-subnets.aws_route_table.internet: Refreshing state... (ID: rtb-bc1919db)
module.phase1.vpc.private-subnets.aws_route_table.private: Refreshing state... (ID: rtb-ff1a1a98)
module.phase1.vpc.public-subnets.aws_route_table_association.public.0: Refreshing state... (ID: rtbassoc-8c6f36ea)
module.phase1.vpc.public-subnets.aws_route_table_association.public.1: Refreshing state... (ID: rtbassoc-8f6f36e9)
module.phase1.vpc.public-subnets.aws_route_table_association.public.2: Refreshing state... (ID: rtbassoc-8d6f36eb)
module.phase1.vpc.private-subnets.aws_route_table_association.private.2: Refreshing state... (ID: rtbassoc-64613802)
module.phase1.vpc.private-subnets.aws_route_table_association.private.1: Refreshing state... (ID: rtbassoc-67613801)
module.phase1.vpc.private-subnets.aws_route_table_association.private.0: Refreshing state... (ID: rtbassoc-65613803)

Outputs:

chefautomate = chefautomate-wrapper --server project-test-chef-automate --command refresh --key-name companyproject --credentials-path /some/user/path/company-projects/github/aws/project/terraform/credentials
dns-env-zone-id = XXXXXXXXXXXXXX
dns-prod-zone-id = XXXXXXXXXXXXXX
environment = test
save-provisioner-creds = save-provisioner-creds --access-id XXXXXXXXXXXXXXXXXXXX --secret-key xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --profile default --credentials-path /some/user/path/company-projects/github/aws/project/terraform/credentials
vpc-id = vpc-f1006396

Experimental feature failure! Please report a bug.

This is not an error. Your Terraform operation completed successfully.
Your real infrastructure is unaffected by this message.

While running, Terraform sometimes tests experimental features in the
background. These features cannot affect real state and never touch
real infrastructure. If the features work properly, you see nothing.
If the features fail, this message appears.

You can report an issue at: https://github.com/hashicorp/terraform/issues

The failure was written to "terraform-error-1487788827.log". Please
double check this file contains no sensitive information and report
it with your issue.

This is not an error. Your terraform operation completed successfully
and your real infrastructure is unaffected by this message.
The preceeding was executed by the following command+arguments:
terraform refresh -var azones='["us-west-2a","us-west-2b","us-west-2c"]' -var region=us-west-2 -var environment=test -var private-key=/some/user/path/.ssh/companyproject.pem -var privkey-name=companyproject.pem -var privkey-path=/some/user/path/.ssh -var ssh_key_name=companyproject -var aws-id=XXXXXXXXXXXXXXXXXXXX -var aws-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -var aws-creds-profile=default -var credentials-path=/some/user/path/company-projects/github/aws/project/terraform/credentials -var action=refresh

### Panic Output
https://gist.github.com/notjames/8ed836337cd868eb5bb6936940939e21
### Expected Behavior
What should have happened?

### Actual Behavior
Nothing.

### Steps to Reproduce
1. `terraform apply` [SUCCESS]
2. `terraform refresh`

### Important Factoids
nothing that I can think of except that I have to use shell scripts as wrappers and a few `data.external`s to glue everything together.

### References
none of which I'm aware.

**Comment by grubernaut** [comment]
Hi @notjames, thanks for the issue!

This was fixed by @mitchellh, and released in the latest version of Terraform (v0.8.7). 
Closing for now, but more than happy to re-open if the issue persists with v0.8.7.
Thanks!!
