### ISSUE TITLE
azurerm_lb_rule protocol case forcing

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#12175]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

```
Terraform v0.9.0-dev (be5230c673824be2a9470cd4a408a2bc148842de)
```

### Affected Resource(s)

- `azurerm_lb_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_lb_rule" "demo" {
  name                    = "demo"
  resource_group_name     = "${azurerm_resource_group.demo.name}"
  loadbalancer_id         = "${azurerm_lb.demo.id}"
  backend_address_pool_id = "${azurerm_lb_backend_address_pool.demo.id}"

  protocol                       = "tcp" # <---
  frontend_port                  = 80
  backend_port                   = 80
  frontend_ip_configuration_name = "${lookup(azurerm_lb.demo.frontend_ip_configuration[0], "name")}"
}
```

### Expected Behavior

Terraform should not try to modify the attribute from `"Tcp"` to `"tcp"`.

### Actual Behavior

```
~ azurerm_lb_rule.demo
    protocol: "Tcp" => "tcp"
```

### Steps to Reproduce

1. `terraform plan` or `terraform apply`

### Important Factoids

Azure returns the "capitalized" version in the API.

**Comment by sethvargo** [comment]
Prolly just needs a `DiffSuppressFunc` on helper/schema.

**Comment by sethvargo** [comment]
(At least that's what @stack72 told me 😉)

**Comment by internetstaff** [comment]
security_rule appears to exhibit the same problem:  Tcp vs TCP.
