### ISSUE TITLE
Make the depends_on feature, and the state file optional

### ISSUE THREAD

**Issue by edgan** [hashicorp/terraform#12186]
I just ran across #10474, and believe in the option of no state file. The state file is the single biggest reason as to why I don't use terraform. I have investigated using terraform multiple times.

  I think there are plenty of potential users of terraform that would switch to it if all the complexity that depends_on, and a state file add were optional. I would rather work in pieces and not try to maintain a global state. Currently terraform is given a list of resources, and it figures out it's own plan for making it happen. I think many users would prefer to explicitly tell terraform the plan. We want more of a tool than an AI.

**Comment by apparentlymart** [comment]
Hi @edgan! Thanks for this feedback.

Would you mind sharing a little more details about what workflow you're looking for? From what you've said -- that you want to "explicitly tell Terraform the plan" -- it sounds like you want to just write an imperative list of instructions to create, update or delete objects, but if Terraform worked this way then I'm not sure what value it would add over e.g. just writing a simple script that calls the API functions to get the result you want.

I assume there's some compromise between these two extremes that you're interested in, so it would be helpful to have some examples of how you'd use Terraform and how you'd expect it to behave in a world where it did not have dependencies, state and the planning workflow.

**Comment by edgan** [comment]
Writing a boto script to do that is exactly what I already do. The downside is then I have to write such a script for each service. Terraform has the advantage of already having support for almost all cloud(AWS) services. I would like to be able to leverage that support.

Saltstack has many of the boto apis wrapped in a way I could do some of this with it. The problem is the support isn't high enough across AWS services, and there are some pieces of the process I that fall outside boto that I would have to write support into Salt to support.

One workflow is making an ELB or ALB, and attaching instances to it. So I wrote into the script the ability to look up instances by tags, and add them to the ALB or ELB. Along with all possible ELB/ALB settings as options of a yaml format.

Another work flow is generate a Saltstack key via the Salt api, feed the key as user-data during the creation of an instance. After the instance is created, create route53 entries for it. Additional things would making and attaching volumes to the instance. Yet another would be creating an elastic ip, and attaching it to the instance.

The part that I don't want to care about in relation to an instance is all the actual, but irrelevant dependencies of that instance. I don't care to worry about if the VPC, subnets, routing tables, etc already exist. I just want to say make me an instance in this VPC and AZ.

I also don't want to manage security groups by id. I want to manage them by name. I know this is a problem AWS created with VPCs. I have solved this two different ways at different times. One way I solved this is to use the ruby SDK, and it had a feature to look up a security group by tag. So I would look up a security group by the tag Name. The second way I have managed this is to write a table of security group ids and there matching names. Then in my instance, ELB, and ALB yaml configuration files I just refer to the security groups by name.

I realize this is sounding like the state file. I also realize that @mitchellh said that tags aren't always possible, and my mapping is a form of state file. A key difference is the format is human friendly. My understanding of the tfstate file is that it is hackable, but not human friendly.

This then gets into something else about state files. I have heard people say that one way or another a state file gets corrupted. They then have to hack it back to sanity. If it was human friendly, this should be easy. Maybe you already do this, and I am unaware, but having changes to the state file being atomic would be awesome. The simple way that comes to mind would be to first make a backup copy of the file. Then if the changed copy gets corrupted in the middle of an operation, I can go back to the backup.

**Comment by mitchellh** [comment]
I've documented why we need the state file and I'll say again **if you have an alternative that solves all the problems/uses listed here, I'm interested**: https://www.terraform.io/docs/state/purpose.html I just want to put that out there to avoid the "why the state file" discussion which I think you already read anyways! Just putting here just in case.

Another option that is possible is to write your own remote state backend. The interface is just read/write state. If you have ANOTHER way to persist that state (via tags, via YourDB, via whatever) then the state _file_ itself needn't exist. You only need to repopulate a mostly-usable state structure and Terraform will just work that out on its own. Take a look at the `backend/remote-state` directory for more info there. 

And finally, you can just delete the state file if you don't want to do any additional maintenance on your infrastructure beyond creation. Terraform doesn't need it after that if you're not going to run it again, of course. I don't think this is your use case but just being explicit here.

There are a couple things coming in 0.9 that greatly ease state file management though:

  1. Backends and their improved UX. See https://twitter.com/mitchellh/status/832006258857095168

  2. State locking. See https://twitter.com/mitchellh/status/831593917434834944

Overall, we're interested in improving your workflows as long as they apply to the greater Terraform community (more than a single or small-N data point). For the single or small-N cases we ask for manual customization on top of Terraform.

Given the workflows you described in addition to the 0.9 improvements above, I actually don't think the state file will cause you any grief. :) However, I hope I've given you some reasonable options above.

**Comment by apparentlymart** [comment]
In addition to what @mitchellh said, you might find it useful to use the data sources in Terraform to enable you to look up pre-existing VPCs, Subnets and Security Groups using their tags, thus avoiding the need to maintain a separate mapping outside of Terraform. This is effectively the same as what you said you do with your script, calling the API to look up the id corresponding to a given name.

```hcl
data "aws_vpc" "main" {
  tags = {
    Environment = "production"
  }
}

data "aws_subnet" "target" {
  availability_zone = "us-east-1c"
  vpc_id            = "${data.aws_vpc.main.id}"
}

data "aws_security_group" "public_http" {
  vpc_id = "${data.aws_vpc.main.id}"
  tags = {
    Name = "public-http"
  }
}

resource "aws_launch_configuration" "main" {
  security_groups = ["${data.aws_security_group.public_http.id}"]
  # ...
}

resource "aws_autoscaling_group" "main" {
  vpc_zone_identifier = ["${data.aws_subnet.main.id}"]
  # ...
}
```

(You can do this even if you do as Mitchell suggested and just delete/ignore the state file after you run, just using Terraform to create.)

**Comment by mitchellh** [comment]
That's a really good point and would allow you to look up resources by tag.
