### ISSUE TITLE
Panic on apply after destroy

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#12183]
Hi there,

### Terraform Version

```
Terraform v0.9.0-dev (9ae0e077f1a43956077f8e0ac7f706f1fb5f3edc)
```

### Affected Resource(s)

- core

### Panic Output

https://gist.github.com/sethvargo/9ca97d49f4e754607906bf63db54446b

### Expected Behavior

Terraform should not have crashed.

### Actual Behavior

Terraform crashed.

### Steps to Reproduce

1. Create resources
2. Destroy resources
3. Run apply

### Steps to Fix

1. Delete local statefile

### Important Factoids

- Using Azure, got an error on destroy, but subsequent destroy succeeded.

**Comment by sethvargo** [comment]
I've narrowed down the issue. In my configs, I'm grabbing the value of a nested attribute (which is a list of maps):

```hcl
frontend_ip_configuration_name = "${lookup(azurerm_lb.demo.frontend_ip_configuration[0], "name")}"
```

Where that is defined as

```hcl
resource "azurerm_lb" "demo" {
  name                = "demo"
  location            = "${var.azurerm_location}"
  resource_group_name = "${azurerm_resource_group.demo.name}"

  frontend_ip_configuration {
    name                          = "default"
    public_ip_address_id          = "${azurerm_public_ip.demo.id}"
    private_ip_address_allocation = "dynamic"
  }
}
```

It looks like the graph isn't correctly setting up that dependency.

**Comment by mitchellh** [comment]
On first look, it appears the graph is being setup properly. This looks like something else. I'm not 100% sure yet but your lookup is weird. I'm not saying you're doing something wrong, but its a usage style that I haven't seen often and I'm not sure how that plays well with computed maps. 

Do you have a consistent reproduction? 

I can play with this tomorrow.
