### ISSUE TITLE
Changing instance type recreates the instance and doesnt need to

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#12195]
Terraform 0.8.7

If you change the instance type of an instance, when you plan you get:

-/+ aws_instance.foo
    instance_type:               "m4.2xlarge" => "m4.xlarge" (forces new resource)

However this does not need to be so - the instance can be stopped, instance type changed, and instance type restarted. Doing this means more data is safeguarded (as long as ephemeral disks not used).

It would be better to provide stop/start mechanism

**Comment by stack72** [comment]
Hi @gtmtech 

Thanks for raising the issue - I am pleased to tell you I already changed this for Terraform 0.8.8 :)

#11998 :)

P.
