### ISSUE TITLE
AzureRM delegated user access?

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform#12208]
### Terraform Version
terraform 0.8.7

### Affected Resource(s)
Azure Provider

I've been using terraform to configure a few things with the azurerm provider, which is broadly working well.

The part I'm not entirely keen on is how I have to create an Azure AD application that has appropriate permissions to perform resource operations per user who I want to have that ability - and annoyingly that azure apps can't be added to groups for permissions.

Clearly this isn't really terraform's fault. Azure AD applications are also allowed to run in a delegated resource mode, where they perform commands as the user in question - this is how the NodeJS, Python CLI apps and the Powershell Cmdlets work. The python code samples are relatively easy to follow here: https://github.com/AzureAD/azure-activedirectory-library-for-python 

Currently terraform is effectively using the "Acquire Token with Client Credentials" method whereas the other CLI tools use "Acquire Token with device code".

Is this something that terraform could be extended to support? 

Annoyingly there's no existing go code in the AzureAD org, but the pieces it uses all seem to be standard parts of OAuth2. The other downside is that the token only lasts for 1 hour, but does provide a refresh token that can be used to get a fresh one.

Perhaps an "easy" extension would be to allow terraform to accept the fully resolved azure bearer token, and then it would be possible for users to use their own mechanism to get and keep a valid bearer token if they wanted?

**Comment by mynkow** [comment]
I am a terraform newbe
I am fighting this for 2 days and I still cant configure Azure to work with terraform. I did not find any tutorial which is working how to do this configuration.

**Comment by bpoland** [comment]
Yeah, would be great if you could log in with the az CLI or something to get a token, and then use that with Terraform to authenticate against Azure.

**Comment by KJTsanaktsidis** [comment]
Yup - would be awesome if Terraform could use the bearer tokens that the aqzure CLI can generate. Then you could do something like `export TF_VAR_bearer_token="$(az account get-access-token | jq -r .accessToken)"` and use terraform like normal.
