### ISSUE TITLE
Chicken and egg problem in aws_elasticsearch_domain

### ISSUE THREAD

**Issue by paktek123** [hashicorp/terraform#12209]
Hi, I am running into an issue where I have an access policy that needs to reference the ARN or unique ID of the resource itself. But this is a chicken and egg problem because if the resource if not generated, it can't get the arn for the `access_policies`. Not sure how to work around this. Its almost like access_polices needs to be decoupled with aws_elasticsearch_domain for `depends_on` to work

### Terraform Version
Terraform v0.8.7

### Affected Resource(s)
- aws_elasticsearch_domain

### Terraform Configuration Files
```
resource "aws_elasticsearch_domain" "test-logs" {
  domain_name = "test"
  elasticsearch_version = "5.1"
  advanced_options {
    "rest.action.multi.allow_explicit_index" = true
  }

  cluster_config {
    instance_count = "1"
    instance_type = "t2.small.elasticsearch"
    zone_awareness_enabled = "false"
  }

  access_policies = <<CONFIG
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "${aws_elasticsearch_domain.test-logs.arn}/*",
      "Condition": {
        "IpAddress": {
          "aws:SourceIp": [
            "1.2.3.4"
          ]
        }
      }
    }
  ]
}
CONFIG

  snapshot_options {
    automated_snapshot_start_hour = 23
  }

  tags {
    env = "dev"
  }
}

```
### Expected Behavior
Resource to be created with the resource arn in the access_policies

### Actual Behavior
```
Error configuring: 1 error(s) occurred:

* Self reference: aws_elasticsearch_domain.test-logs
```

### Steps to Reproduce
1. Put the above in a .tf file and run `terraform plan`

### Important Factoids
AWS Elasticsearch Service and Amazon policies

**Comment by paktek123** [comment]
ok I have found a solution, in my case the Resource ARN can be generated.

arn:aws:es:${region}:${account_id}:domain/${domain}

This fixes my issue, but I dont know if this can cause issues with other resources?

If not then this issue can be closed.

**Comment by lwilliams-oats** [comment]
Check out the [aws_elasticsearch_domain_policy](https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain_policy.html) resource. I think it exists specifically for cases like this.

**Comment by stack72** [comment]
Hi @paktek123 

Thanks for raising the issue here - @lwilliams-oats is completely correct - this is why we created the `aws_elasticsearch_domain_policy` resource

This will solve your problem

Thanks

Paul
