### ISSUE TITLE
consul/terraform - chicken or the egg dilemna

### ISSUE THREAD

**Issue by lesaux** [hashicorp/terraform#1221]
Hello,
I have a terraform template that creates a vpc and subnets, and also creates a consul instance in aws. I am trying to add some data to consul in this same template without success.

provider "consul" {
    address = "${aws_instance.consul1.public_dns}:8500"
    datacenter = "dc1"
}
${aws_instance.consul1.public_dns} is not evaluated so my consul_keys resource is not working.
What I am trying to do, is to store vpc_id and subnet_ids in consul, so I can reuse them from other terraform templates later on. I think there's something wrong with my approach. Would anyone be able to provide some advise around this?

**Comment by zxjinn** [comment]
If I understand correctly you probably want to look at outputs: http://www.terraform.io/docs/configuration/outputs.html
and how to use outputs in modules:
http://www.terraform.io/docs/modules/usage.html

**Comment by lesaux** [comment]
Thanks for pointing me to that. I somehow missed this documentation on modules. I should be able to achieve my goal now.
