### ISSUE TITLE
Terraform seems not to support multiple attributes in a DynamoDB key schema

### ISSUE THREAD

**Issue by jgryszko** [hashicorp/terraform#12229]
Hi,

It looks like multiple attributes are not supported for dynamodb key schema so far.

Looking at the source, only hash_key is included in the key schema.

resource_aws_dynamodb_table.go:
`hash_key_name := d.Get("hash_key").(string)
	keyschema := []*dynamodb.KeySchemaElement{
		{
			AttributeName: aws.String(hash_key_name),
			KeyType:       aws.String("HASH"),
		},
	}`
Are there plans to change this in near future?
Best,
Janusz

**Comment by ashb** [comment]
I would like to be able to create a dynamodb table for use with credstash and it wants this KeySchema:

```
            {
                "AttributeName": "name",
                "KeyType": "HASH",
            },
            {
                "AttributeName": "version",
                "KeyType": "RANGE",
            }
```
