### ISSUE TITLE
Beanstalk - SSHSourceRestriction - Terraform keeps re-applying

### ISSUE THREAD

**Issue by sanjay-varanasi** [hashicorp/terraform#12222]
Version:
terraform -v
Terraform v0.8.7

Affects:
aws_elastic_beanstalk_environment

Terraform Elasticbeanstalk environment option that seems to trigger a re-apply:
In other words, I've only been seeing this behaviour after adding this option.
We have to add this because the default SSH sec_grp behaviour is to open 22 to the world (0.0.0.0/0)

```  
setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "SSHSourceRestriction"
    value     = "tcp, 22, 22, 10.0.0.0/16"
  }
```

Expected Behaviour:
Detect and "apply" the SSH port change the first time the configuration is applied. 
Make no changes on subsequent applies.

Actual Behaviour:
Change show with every "plan".
Change applied with every "apply".

"terraform plan" will keep outputting this on every plan:

 ```
    setting.786963625.name:       "" => "SSHSourceRestriction"
    setting.786963625.namespace:  "" => "aws:autoscaling:launchconfiguration"
    setting.786963625.resource:   "" => ""
    setting.786963625.value:      "" => "tcp, 22, 22, 10.0.0.0/16"
```

and "terraform apply" will always modify the Beanstalk env

```
  setting.786963625.name:       "" => "SSHSourceRestriction"
  setting.786963625.namespace:  "" => "aws:autoscaling:launchconfiguration"
  setting.786963625.resource:   "" => ""
  setting.786963625.value:      "" => "tcp, 22, 22, 10.0.0.0/16"
aws_elastic_beanstalk_environment.eb_env: Still modifying... (10s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (20s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (30s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (40s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (50s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (1m0s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (1m10s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (1m20s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (1m30s elapsed)
aws_elastic_beanstalk_environment.eb_env: Still modifying... (1m40s elapsed)
aws_elastic_beanstalk_environment.eb_env: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

I can definitely see the option in tfstate:

```                            
                            "setting.3461474930.name": "SSHSourceRestriction",
                            "setting.3461474930.namespace": "aws:autoscaling:launchconfiguration",
                            "setting.3461474930.resource": "",
                            "setting.3461474930.value": "tcp,22,22,10.0.0.0/16",
                            .
                            .
                            .
                            "all_settings.3461474930.name": "SSHSourceRestriction",
                            "all_settings.3461474930.namespace": "aws:autoscaling:launchconfiguration",
                            "all_settings.3461474930.resource": "",
                            "all_settings.3461474930.value": "tcp,22,22,10.0.0.0/16",
```
Is this a bug or am I not doing this the right way? Let me know if you need specific information.

**Comment by dtserekhman-starz** [comment]
Running into the same problem. Any timeline on this issue being resolved?

**Comment by kevinpgrant** [comment]
same here, my terraform config

```
setting {
  namespace = "aws:autoscaling:launchconfiguration"
  name      = "SSHSourceRestriction"
  value     = "tcp,22,22,${var.jump_security_group_id}"
}
```

terraform plan|apply behaves incorrectly on second and subsequent runs

```
    setting.1224657411.name:      "SSHSourceRestriction" => ""
    setting.1224657411.namespace: "aws:autoscaling:launchconfiguration" => ""
    setting.1224657411.resource:  "" => ""
    setting.1224657411.value:     "tcp,22,22,null" => ""

    setting.2392760962.name:      "" => "SSHSourceRestriction"
    setting.2392760962.namespace: "" => "aws:autoscaling:launchconfiguration"
    setting.2392760962.resource:  "" => ""
    setting.2392760962.value:     "" => "tcp,22,22,sg-1234abcd"
```

tested on TF 0.9.3 and 0.9.4

**Comment by pmacdougall** [comment]
I ran into this issue too.  For me it was spacing around my commas in `"tcp,22,22,XXX.XXX.XXX.XXX/32"`.  I originally had spaces after my commas like @sanjay-varanasi does.

The AWS API gives the data back without spaces, so terraform thinks there's a change.

Not sure what the issue is with @kevinpgrant since there's no spaces there.  Might be different formatting for a security group vs CIDR.

**Comment by danohalloran-starz** [comment]
May I inquire why this issue was closed without a resolution?

**Comment by beanaroo** [comment]
@danohalloran-starz Terraform 0.10 splits providers into separate repositories. Hashibot has been migrating provider specific issues from this repo.

**Comment by DrFunk-n-stein** [comment]
This is a beanstalk issue. Found out some weeks ago, that the aws API seems to accept values that are stored differently there. On apply, those values will be reapplied because they seem to be different (which they are not). 

Setting the values differently, solved it for me - like ordering of subnets: 

```
  setting {
    namespace = "aws:ec2:vpc"
    name      = "Subnets"
    value     = "${join(",", sort(var.private_subnets))}"
  }
```

There are some other values, where you have to remove whitespaces in the values to prevent re-application: 

```
 setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "SSHSourceRestriction"
    value     = "tcp,22,22,${var.some_var}" # <- no whitespaces
  }
```

All other reapplied settings can come from settings, which are not suitable for the selected load balancer type. E.g. all settings of the `aws:elbv2:loadbalancer` namespace will be reapplied if a classic loadbalancer is selected (so, only settings of `aws:elb:loadbalancer` will be suitable for this).
