### ISSUE TITLE
openstack_lb_loadbalancer_v2: "provider" attribute fails validation because of namespace collision with "Provider"

### ISSUE THREAD

**Issue by rcreasey** [hashicorp/terraform#12237]
```
resource "openstack_lb_loadbalancer_v2" "hero_edge" {
  region        = "${var.region}"
  vip_subnet_id = "${var.vip_subnet_id}"
  provider      = "a10networks_ext"
}
```

Upon attempting to plan:
```
» terraform plan xx-98
2 error(s) occurred:

* module web: provider alias must be defined by the module or a parent: a10networks_ext
```

Obviously, this isn't referring to the `provider` attribute listed here:
https://www.terraform.io/docs/providers/openstack/r/lb_loadbalancer_v2.html

And instead is referring to the Provider during validation:
https://github.com/hashicorp/terraform/blob/f2c16b7ba2b01b233623097e479825efe1ead3c8/config/module/validate_provider_alias.go#L69-L71

### Terraform Version
Terraform v0.8.7

### Affected Resource
- openstack_lb_loadbalancer_v2

### Terraform Configuration Files
```
resource "openstack_lb_loadbalancer_v2" "hero_edge" {
  region        = "${var.region}"
  vip_subnet_id = "${var.vip_subnet_id}"
  provider      = "a10networks_ext"
}
```

### Debug Output
https://gist.github.com/rcreasey/f79c160cd14a3c1f5110567efb4070d1

### Expected Behavior
This "provider" attribute should be applied to the resource and not validated as a "Provider" alias.

### Actual Behavior
What actually happened?

### Steps to Reproduce
1. Define a `openstack_lb_loadbalancer_v2` resource and specify the `provider` attribute.
2. Attempt to run `terraform plan`

### Important Factoids
This seems to be a failure in the validation code of Terraform, and not related to any specific Openstack API.

**Comment by jtopjian** [comment]
@rcreasey Good catch. I always wondered if there would be a conflict and just assumed it was tested in the past. 

Any suggestions for an alternative name? `lb_provider` or `loadbalancer_provider` ?

**Comment by rcreasey** [comment]
Yeah, either of those should suffice.

**Comment by rcreasey** [comment]
Also, while we're at it, any chance we could get `vip_subnet_id` to take the subnet `name` instead of/in addition to the `guid`?

**Comment by jtopjian** [comment]
That change is a bit more difficult. Using the UUID ensures uniqueness since there can be multiple subnets with the same canonical name. 

If you're defining the subnet with Terraform, it's very easy to pass the ID to the load balancer. However, if you're using a predefined subnet, I can see how hard-coding the UUID is cumbersome. In this case, a subnet data source would be the best solution. Let me know if this is the situation you're in and I can look at building a subnet data source. :)

**Comment by rcreasey** [comment]
Yeah, I realized how hard it would be after making that comment (and thus deleted it ;).

The subnet data source would indeed be welcome.  I'm using pre-defined networks/subnets for 10+ regions, which does become a pain.

Either way, I'm more blocked by this provider bug and would rather just get that addressed before making feature requests ;)

**Comment by jtopjian** [comment]
Ask and ye shall receive :)

Feel free to test it out if you're familiar with building Terraform from source. Otherwise, it should be merged in the next few days.

**Comment by rcreasey** [comment]
<3 

Will do.  I'll reply here/there if I find anything that needs tweaks.

Thanks for the quick turnaround!
