### ISSUE TITLE
aws_api_gateway_integration resources not getting updated properly.

### ISSUE THREAD

**Issue by naikajah** [hashicorp/terraform#12233]
### Terraform Version
 Terraform v8.7

### Affected Resource(s)
aws_api_gateway_integration

### Terraform Configuration 
My terraform configuration for aws_api_gateway_integration

```
resource "aws_api_gateway_integration" "testMockGET" {
  rest_api_id             = "${aws_api_gateway_rest_api.test.id}"
  resource_id             = "${aws_api_gateway_resource.testMock.id}"
  type                    = "MOCK"
  uri                     = "/test"
  http_method             = "${aws_api_gateway_method.testGET.http_method}"
}
```
### Expected Behavior
After the first plan and apply created the resource in AWS. The subsequent plan and apply shouldn't modify the resource unless there is any change in the resource definition.

### Actual Behavior
After the first plan and apply creates the resource properly all the subsequent plan shows that there is an update even though there are none and apply updates the URI parameter with the same value again and again.

```
~ module.TEST.aws_api_gateway_integration.testMockGET
 uri: "" => "/test"
```
This is then leading to https://github.com/hashicorp/terraform/issues/9877

### Steps to Reproduce

1. terraform plan original definition
2. terraform apply original definition
3. terraform plan/apply

After looking at the repo, I see that for api_gateway_integration resource we have same method which is resourceAwsApiGatewayIntegrationCreate where as for other resources e.g. api_gateway_method we have an resourceAwsApiGatewayMethodUpdate which takes care of checking if the value has changed.
 
Create: resourceAwsApiGatewayIntegrationCreate,
Update: resourceAwsApiGatewayIntegrationCreate,

Shouldn't there be an Update: resourceAwsApiGatewayIntegrationUpdate for Integration resource that checks for hasChanged().
could this be a problem here?

**Comment by stack72** [comment]
Closed via #13249
