### ISSUE TITLE
azurerm support disk encryption 

### ISSUE THREAD

**Issue by razsha** [hashicorp/terraform#12259]
Hi, 

Do you plan to add disk encryption support in the next Terraform version to azurerm provider? 

Thanks, 
Raz.

**Comment by stack72** [comment]
Hi @razsha 

thanks for the feature request here - please can you link us to some documentation that shows how to configure disk encryption?

thanks

Paul

**Comment by razsha** [comment]
Hi @stack72 

https://github.com/Azure/azure-sdk-for-go/blob/ecf40e315d5ab0ca6d7b3b7f7fbb5c1577814813/arm/disk/models.go#L117

thanks,
Raz.

**Comment by razsha** [comment]
?

**Comment by StephenWeatherford** [comment]
I'm working on this.  Thanks for bringing it to our attention.

**Comment by tomasquith** [comment]
+1

**Comment by tomasquith** [comment]
Is this using SSE for the underlying storage as a whole or encrypting each disk individually?

**Comment by StephenWeatherford** [comment]
@tomasquith SSE encryption is already supported in terraform.  This is about adding encryption_settings properties to VM OS disks and managed disks to support OS-level encryption (https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption).
