### ISSUE TITLE
Issue Cross Compiling Provider

### ISSUE THREAD

**Issue by brianantonelli** [hashicorp/terraform#12254]
I'm having an issue with a provider I'm working on - https://github.com/Cox-Automotive/terraform-provider-alks..

I'm developing it on OSX, if I build the provider using this command: `go build -v -o terraform-provider-alks .` and then run `terraform plan` using this provider everything works as expected. 

I have a Travis job setup to cross-compile for the various OSes, and when I run try to use one of the Travis compiled binaries I get a plugin versioning error. I encounter this same error when building the binaries on my Mac when I set `GOOS` and `GOARCH`. 

For example, here's my build command to generate the binary for OSX: `GOOS=darwin GOARCH=arm64 go build -v -o terraform-provider-alks .` It compiles fine; however, when I try to use the provider I get the same plugin versioning error:

```
🍔  terraform plan
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 3, Ours: 2
```

Why does it generate a valid binary without `GOOS` and `GOARCH` but then fail when I supply those values for my OS? I've tried this with Terraform `0.8.6` and `0.8.7`..

**Comment by apparentlymart** [comment]
Hi @brianantonelli! Sorry things aren't working as expected here.

The version it's talking about is the protocol used by plugins to talk to the main Terraform process. This version comes from [the plugin code](https://github.com/hashicorp/terraform/blob/96884ec42d5ccccda6529604eaa7f941728555c9/plugin/serve.go#L22), so I doubt that it's the cross-compiling that's the issue but rather that somehow you have your Terraform versions mismatched between the host where you're compiling and the host where you're trying to run the resulting plugin binaries.

Plugin version 3 was adopted with `0.9.0-beta1`, so it seems that you've compiled the plugin from `master` where we're currently tracking towards the `0.9.0` release. If you get Travis to instead build from Terraform's `0.8.7` tag then I think you'll get a working result.

**Comment by brianantonelli** [comment]
Thanks for following up, @apparentlymart. I'm reproducing this error when building and running on the same machine - 2014 Macbook Pro with running 10.12.2 with go1.7.5 and Terraform 0.8.7.

If I build without supplying `GOOS` or `GOARCH` I'm able to run the the plugin fine. Here's my build command: 
`go build -v -o terraform-provider-alks .`

If I run build and specify `GOOS` and `GOARCH` for Darwin AMD64 I get the plugin version error I showed above. Here's my build command: 
`GOOS=darwin  GOARCH=amd64 go build -v -o terraform-provider-alks .`

**Comment by apparentlymart** [comment]
Hi again @brianantonelli! This is a strange issue...

My next guess is that maybe you have some stuff cached in your `GOPATH` from an earlier build of Terraform and so somehow you're ending up linking to a stale compiled package. Does the issue persist if you empty out the `$GOPATH/pkg` dir? (or, if you prefer something less drastic, the `darwin_amd64/github.com/hashicorp/terraform` directory and the one corresponding to your plugin's package.)

**Comment by brianantonelli** [comment]
You were absolutely right, @apparentlymart! I updated the project to use Govend and viola Travis is building the plugins perfectly.

Thanks again!
