### ISSUE TITLE
aws_autoscaling_lifecycle_hook and initial_lifecycle_hook don't work with create_before_destroy

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#12264]
I'm using the `create_before_destroy` trick [described here](https://groups.google.com/forum/#!msg/terraform-tool/7Gdhv1OAc80/iNQ93riiLwAJ) to create an ASG that will automatically redeploy changes every time you change something the launch configuration (e.g. the AMI ID). However, instead of relying on ELB health checks, I'm trying to use lifecycle hooks. 

The idea is that each time the new ASG is created and the instances are coming up, something has to to "complete" the lifecycle hook before those instances show up as "In Service". That something could be, for example, a user data script on each instance that does some smoke tests. 

Unfortunately, whether I use an `initial_lifecycle_hook` or an `aws_autoscaling_lifecycle_hook`, it doesn't seem to work properly with `create_before_destroy`.

### Terraform Version

Terraform v0.8.7

### Affected Resource(s)

- aws_autoscaling_group
- aws_autoscaling_lifecycle_hook

### Terraform Configuration Files

(The code below shows both lifecycle hooks I tried)

```hcl
resource "aws_autoscaling_group" "asg" {
  name = "${aws_launch_configuration.lc.name}"
  launch_configuration = "${aws_launch_configuration.lc.name}"
  availability_zones = ["us-east-1a", "us-east-1b", "us-east-1c"]

  min_size = 2
  max_size = 10
  desired_capacity = 2

  initial_lifecycle_hook {    
    name = "smoke-test-1"   
    default_result = "ABANDON"    
    heartbeat_timeout = 300   
    lifecycle_transition = "autoscaling:EC2_INSTANCE_LAUNCHING"   
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_launch_configuration" "lc" {
  name_prefix = "example"
  image_id = "ami-abcd1234"
  instance_type = "t2.micro"
  user_data = "file("smoke-test.sh")"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_lifecycle_hook" "smoke_test" {
  name = "smoke-test-2"
  autoscaling_group_name = "${aws_autoscaling_group.asg.name}"
  default_result = "ABANDON"
  heartbeat_timeout = 300
  lifecycle_transition = "autoscaling:EC2_INSTANCE_LAUNCHING"
}
```

### Expected Behavior

Every time I change something in the launch configuration and run `terraform apply`, I expect the following to happen:

1. A new ASG is created.
1. The lifecycle hook fires on each of the instances in the new ASG, putting the instance in wait state.
1. As my instances boot, the user data script performs some smoke tests, and if everything looks good, completes the lifecycle hook, putting them in "In Service" state.
1. When all instances are in "In Service" state, the old ASG is deleted.

### Actual Behavior

If I use an `initial_lifecycle_hook`, it fires the very first time the ASG is created, which is what I expect. However, on each redeploy, even though a new ASG is created each time, it never fires again.

If I use an `aws_autoscaling_lifecycle_hook`, it never fires at all, either on the initial creation or any redeploys.

### Steps to Reproduce

1. `terraform apply`
1. Change something in the launch configuration (e.g. the AMI ID)
1. `terraform apply`

**Comment by vikas027** [comment]
I am seeing this in 0.9.1 as well :(

**Comment by kuberkaul** [comment]
seeing the same .

**Comment by niroliyanage** [comment]
I added a `aws_autoscaling_lifecycle_hook` after the `initial_lifecycle_hook` and it seems to work even with deploys and redeploys
