### ISSUE TITLE
Documentation Request - Add examples for Python and Ruby

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform#12271]
### Terraform Version
0.8.7

###  Resource(s)
- [external](https://www.terraform.io/docs/providers/external/data_source.html)

It would be great if you can add some examples to use `ruby` and `python` as well, similar to `Processing JSON in shell scripts`

**Comment by stack72** [comment]
Hi @vikas027 

Thanks for the request here - this resource is a generic resource for executing scripts. The JSON example was just to demonstrate what can be done - we won't be able to start adding other language examples as it would be difficult to understand what we should and shouldn't support

I am pretty sure you can find some examples of Processing JSON in ruby and python on StackOverflow

Thanks

Paul

**Comment by vikas027** [comment]
@stack72 Yeah, I can find tons of examples elsewhere and I can make things work out. But IMHO documentation should at least have a couple of lines (to refer as a starting point) of how/what to expect input (from Terraform code) in Ruby, Python or any popular language.

For example, I am very good in bash and can code in Ruby as well, but I didn't know that I can do something like `JSON.parse(STDIN.read)` in ruby. This is just a thought coming from people with rich infra background but are moderately skilled developers. Thanks.
