### ISSUE TITLE
export function_name in aws_lambda_function resource

### ISSUE THREAD

**Issue by gpetras** [hashicorp/terraform#12286]
This is a simple request to enhance the aws_lambda_function resource to export the function name.

We often find ourselves hard-coding the Lambda function name in other resource declarations (eg in ```aws_cloudwatch_metric_alarm```, ```aws_cloudwatch_log_group```, etc), and it would be nice if we could refer to the aws_lambda_function resource directly. That would also have the effect of creating a dependency which would help when we do terraform apply and destroy.

### Terraform Version
0.8.7

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lambda_function

### Current functionality
```hcl
resource "aws_lambda_function" "my-lambda" {
  filename         = "function.zip"
  function_name    = "my-lambda-function-name"
  role             = "${aws_iam_role.my-lambda.arn}"
  handler          = "index.handler"
  runtime          = "nodejs4.3"
  timeout          = "3"
  source_code_hash = "${base64sha256("function.zip")}"
}

resource "aws_cloudwatch_log_group" "my-lambda" {
  name              = "/aws/lambda/my-lambda-function-name"
  retention_in_days = "30"
}
```

### Desired functionality
```hcl
resource "aws_lambda_function" "my-lambda" {
  filename         = "function.zip"
  function_name    = "my-lambda-function-name"
  role             = "${aws_iam_role.my-lambda.arn}"
  handler          = "index.handler"
  runtime          = "nodejs4.3"
  timeout          = "3"
  source_code_hash = "${base64sha256("function.zip")}"
}

resource "aws_cloudwatch_log_group" "my-lambda" {
  name              = "/aws/lambda/${aws_lambda_function.my-lambda.function_name}"
  retention_in_days = "30"
}
```

### Expected Behavior
I should be able to reference the function_name attribute, eg ```${aws_lambda_function.my-lambda.function_name}```.

### Actual Behavior
I have to use a hard-coded string for the function_name, eg ```my-lambda-function-name```.

**Comment by stack72** [comment]
Hi @gpetras 

Any parameter that can be passed to the creation of a resource, can also be used as a reference in another resource. therefore, function_name is already available to use

Did you get an error when trying to reference it?

Paul

**Comment by gpetras** [comment]
Well let's just chalk that up to Monday morning and leave it at that! :) I don't recall the specific error I saw, but I'll take your word for it. Thanks for responding @stack72!

**Comment by stack72** [comment]
@gpetras hey these things happen on Mondays ;) Let me know if there is any issue

Paul

**Comment by pmoghaddam** [comment]
The issue is not knowing the name to use, but that it makes it harder to create the appropriate dependency graph.

For example `aws_lambda_permission` requires `function_name`. If you just put in the string name, it does not properly wait for the Lambda function to be created first before creating this permission. So you get an error that the Lambda does not exist. Subsequent apply will work though.

If the name was available easily, rather than needing to do e.g.
```
${element(split(":", aws_lambda_function.lambda.arn), 6)}
```
or providing an explicit `depends_on` attribute, it'd make it cleaner.
