### ISSUE TITLE
Allow import of aws_route_table_association

### ISSUE THREAD

**Issue by GuiSim** [hashicorp/terraform#12280]
### Terraform Version
v0.8.7

### Affected Resource(s)
- aws_route_table_association

Currently if you run `terraform import` on a `aws_route_table_association` you'll get an error:
```
* import module.X.aws_route_table_association.Y (id: rtbassoc-1234f171): resource aws_route_table_association doesn't support import
``` 

Allowing route table associations to be imported would be really useful. Right now, I can do it by manually editing the state file but it is an error prone process.

You can get the `id` of a route table association through 
```
aws ec2 describe-route-tables --route-table-ids rtb-123436a4
``` 

They follow the format `rtbassoc-XXXXX`.

Thanks!

**Comment by aqt01** [comment]
When is this expected to be fixed?

**Comment by jonigl** [comment]
@aqt01  I'm sure you found the solution already but, perhaps others with the same question could arrive here so, this is the solution to import aws_route_table_association:

`terraform import aws_route_table_association.your-rt-assoc-name subnet-id/rtb-id`

Enjoy :)
