### ISSUE TITLE
Expose DIR as a variable for Terraform

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1229]
Having following architecture:
```
.
├── 00-dns-stack
│   ├── main.tf
│   └── variables.tf
```

and `local-exec` provisioner in the `main.tf`:

```ruby
resource "aws_route53_record" "vpn" {
  zone_id = "${var.aws_hosted_zone_id}"
  name = "${var.name_prefix}vpn.${var.dns_domain}"
  type = "A"
  ttl = "60"
  records = ["${aws_instance.vpn.public_ip}"]

  provisioner "local-exec" {
    command = "echo 'export VPN_HOSTNAME=${aws_route53_record.vpn.name}' > ./env.sh"
  }
}
```

and running all that via 

```
terraform apply -state=00-dns-stack/terraform.tfstate 00-dns-stack
```

it's effectively impossible to know where are `*.tf` files that I'm running, where's the directory to which I may want to place some other files like ENV variables because it's [executing that code directly via either `/bin/sh` or `cmd`](https://github.com/hashicorp/terraform/blob/b3fa3811f5dc16b5014b95dea56126bf53474bfd/builtin/provisioners/local-exec/resource_provisioner.go#L45-46) = things like `$(dirname $0)` are useless in that context.

How about exposing that as a variable under a special namespace? e.g. `${terraform.dir}`?

The example would then become:

```ruby
...
  provisioner "local-exec" {
    command = "echo 'export VPN_HOSTNAME=${aws_route53_record.vpn.name}' > ${terraform.dir}/env.sh"
  }
...
```

**Comment by mitchellh** [comment]
These are all available: https://terraform.io/docs/configuration/interpolation.html

See "path information"

**Comment by radeksimko** [comment]
Ah, I'm idiot... RTFM Radek! :smiley:  Sorry!
