### ISSUE TITLE
aws_security_group_rule created but terraform times out request when cidr_block count > 1

### ISSUE THREAD

**Issue by in4mer** [hashicorp/terraform#12292]
### Terraform Version
```
% tf -version
Terraform v0.8.7
```

### Affected Resource(s)
- aws_security_group
- aws_security_group_rule

### Terraform Configuration Files
```hcl
variable "office_IPs" {
  type = "list"
  default = [ "1.2.3.4/32", "2.3.4.5/29" ]
}

resource "aws_security_group" "sg-rule-test-sg" {
  vpc_id = "${aws_vpc.main.id}"

  tags {
    Name        = "sg-rule-test-sg"
    description = "delete at will; this is just a test"
    source      = "terraform"
    tf_source   = "sg-rule-test"
  }
}

resource "aws_security_group_rule" "sg-rule-test-sgr0" {
  type        = "ingress"
  from_port   = "22"
  to_port     = "22"
  protocol    = "tcp"
  cidr_blocks = "${var.office_IPs}"

  security_group_id = "${aws_security_group.sg-rule-test-sg.id}"
}

resource "aws_vpc" "main" {
  tags = { Name = "sg-rule-test-vpc", tf_source = "sg-rule-test", comment = "delete at will, this is just a test" }
  cidr_block = "172.31.255.0/24"
}
```

### Debug Output
https://gist.github.com/in4mer/33cec45e79499827d33acc1644ec4e9c

### Panic Output
No panic from terraform.  Devops, on the other hand..

### Expected Behavior
`terraform apply` should have reported success after creating aws_security_group_rule with attachment to the aws_security_group in question.

### Actual Behavior
`terraform apply` calls for the creation of a multi-cidr_block aws_security_group_rule, and then reports a timeout waiting for its creation.  The creation actually happens (if you watch in the console), and attaches.  Terraform has no idea.

subsequent `terraform apply` calls then throw errors, because an identical aws_security_group_rule already exists and is attached to the SG!  Because the creation call was actually successful, terraform was just apparently unable to recognize that the creation request returned properly.  This reported timeout in the face of a successful API call creates an unrecoverable state desync.  Subsequent runs will all fail until the offending rule is removed from the HCL.  Attempting to remove and re-create the offending SG will cause the same timeout/error combination as the bug is re-encountered on aws_security_group_rule creation.

This is *not* a desynch bug related to prior versions of terraform not properly saving/recognizing state.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. wait for reported timeout
3. As you wait, observe the aws_security_group in the aws console to verify that the aws_security_group_rule has been properly created and attached to the SG (it does so immediately, every time).
4. After timeout, attempt to converge again by running `terraform apply`
5. Observe resulting error while trying to support an actual business.
6. self.defenestrate()

### Important Factoids
No important factoids about the accounts or configuration, but it seems *clear* there are some obviously deficient unit tests, if not outright missing unit tests.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- I can't find anything that references this behavior directly.  Surprisingly.

**Comment by in4mer** [comment]
For anyone wondering, there *is* a workaround for this:

Separate each cidr_blocks list element into its own aws_security_group_rule entry.  So if you have five entries in a list intended for cidr_blocks, you must instead create five aws_security_group_rule entries.  In an effort to not go completely crazy, I recommend leaving the IP addresses in a single list, and copy-pasting each aws_security_group_rule with a single incrementing reference to the original list.

Gosh, too bad aws_security_group_rule doesn't take count, isn't it?

**Comment by ewbankkit** [comment]
Looks like this was fixed with https://github.com/hashicorp/terraform/pull/12765.
