### ISSUE TITLE
Creation of multiple aws_elb randomly timeout

### ISSUE THREAD

**Issue by ChristopheSchmitz** [hashicorp/terraform#12290]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.8.7

### Affected Resource(s)
aws_elb

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
I have the following in a module. I am calling about 16 time the module. The likelihood and number of timeout error message increase with the number of time I call the module.

```hcl
resource aws_elb test {
  name = "${var.name}"
  internal = true
  subnets = ["${var.subnet_list}"]
  cross_zone_load_balancing = true
  //security_groups = [] // FIXME
  listener {
    instance_port = 8080
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
}
```

### Expected Behavior
All the elb should be created

### Actual Behavior
If I try to create too many elb by the call of my module, I start to get some timeout.
```
* aws_elb.test: Failure adding ELB subnets: timeout while waiting for state to become 'success' (timeout: 1m0s)
* aws_elb.test: Failure adding ELB subnets: timeout while waiting for state to become 'success' (timeout: 1m0s)
* aws_elb.test: Failure adding ELB subnets: timeout while waiting for state to become 'success' (timeout: 1m0s)
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Maybe there is a way to increase the timeout?

**Comment by snowsky** [comment]
I couldn't reproduce this issue.
