### ISSUE TITLE
provider/rabbitmq: ressource rabbitmq_user with no tags lead to a terraform crash

### ISSUE THREAD

**Issue by sbadia** [hashicorp/terraform#12296]
Hi there,

I want to create a rabbitmq user without tags (which is perfectly valid), but it seems is not possible with rabbitmq terraform provider.

### Terraform Version

`Terraform v0.8.7`

### Affected Resource(s)

- `rabbitmq_user`

### Terraform Configuration Files

```hcl
provider "rabbitmq" {
  endpoint = "http://172.17.0.2:15672/"
  username = "guest"
  password = "guest"
}

resource "rabbitmq_user" "empty" {
  name = "empty"
  password = "ytpme"
  tags = [""]
}
```

### Panic Output
* <https://gist.github.com/sbadia/f27043ba3830a63f061f139bfc3db54f#file-terraform_crash_20170228-log>

### Expected Behavior
Create rabbitmq users without tags.

### Actual Behavior
Create a user without tags lead to a terraform crash.

### Steps to Reproduce
1. Setup a new rabbitmq server <https://gist.github.com/sbadia/f27043ba3830a63f061f139bfc3db54f#file-rabbitmq_setup-txt>
2. Test with an empty array <https://gist.github.com/sbadia/f27043ba3830a63f061f139bfc3db54f#file-terraform_empty_array-txt>

```hcl
resource "rabbitmq_user" "empty" {
  name = "empty"
  password = "ytpme"
  tags = []
}
```

3.  Test with an empty value <https://gist.github.com/sbadia/f27043ba3830a63f061f139bfc3db54f#file-terraform_empty_values-txt>

```hcl
resource "rabbitmq_user" "empty" {
  name = "empty"
  password = "ytpme"
  tags = [""]
}
```

4.  Test without tag argument <https://gist.github.com/sbadia/f27043ba3830a63f061f139bfc3db54f#file-terraform_no_tags-txt>

```hcl
resource "rabbitmq_user" "empty" {
  name = "empty"
  password = "ytpme"
}
```

### Important Factoids

Thanks in advance :)

**Comment by snowsky** [comment]
oh, just saw that tags is a required attribute and the code doesn't check if it is empty or not. I'll put up a PR to fix it.
