### ISSUE TITLE
Output with concat inconsistent with empty list

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#12295]
This is a dumbed down config, so please don't focus on the specific resource types. Essentially, I have a module that creates two sets of resources and outputs the list of the resource IDs combined together using `concat(...)`. As long as both lists of IDs contain elements, the output behaves correctly. If one of the lists is empty, then on that particular `apply` the output is empty/omitted. On a subsequent apply, the output is what I would expect.

### Terraform Version
`Terraform v0.8.7`

### Affected Resource(s)
I believe this is a core issue, not affecting specific resource types.

### Terraform Configuration Files
Full config is at https://gist.github.com/clstokes/cc7197626c18ed2905e2b14c2cb8162c.

### Output
Output is at https://gist.github.com/clstokes/cc7197626c18ed2905e2b14c2cb8162c#file-zoutput-log.

### Expected Behavior
I expect the `sg` output to always be populated.

### Actual Behavior
If I change one of the module inputs to result in one of the resource lists to be a list with zero entities, the `sg` output is empty/omitted during the run that changed the list. On subsequent runs, it's as expected.

### Steps to Reproduce
1. `terraform apply`
1. Observe that the `sg` output is populated.
1. Change `count_internal` to `0` on [line 8](https://gist.github.com/clstokes/cc7197626c18ed2905e2b14c2cb8162c#file-main-tf-L8).
1. `terraform apply`
1. Observe that the `sg` output is omitted.
1. `terraform apply` again without changing any config
1. Observe that the `sg` output is populated and returned in the output.

**Comment by mildwonkey** [comment]
Hi! Sorry for the long silence on this issue :) 

In terraform v0.12, an empty list will be displayed by `output`. I believe this addresses your issue.

The only case where no output appears at all is if the value is `null`:

```hcl
variable "list1" {
  type = list(string)
  default = []
}
variable "list2" {
  type = list(string)
  default = [""]
}
variable "list3" {
  type = list(string)
  default = null
}

output "list1" {
  value = var.list1
}
output "list2" {
  value = var.list2
}
output "list3" {
  value = var.list3
}
```

```
$ terraform output
list1 = []
list2 = [
  "",
]
```

I am going to close this, but please don't hesitate to open a new issue if you come across any unexpected behavior in terraform 0.12. Thanks!
