### ISSUE TITLE
Reading tfvars config should not prevent interactive prompt

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1230]
Example:

```
.
├── sample.tf
└── terraform.tfvars
```

**`sample.tf`**
```ruby
variable "aws_region" {
  description = "AWS region"
}

variable "cidr_block" {
  description = "CIDR block for VPC"
}

provider "aws" {
  region = "${var.aws_region}"
  access_key = ""
  secret_key = ""
}

resource "aws_vpc" "default" {
  cidr_block = "${var.cidr_block}"
}
```

**`terraform.tfvars`**
```
cidr_block="10.10.0.0/16"
```

----------

**Expected behavior**: Prompt for `aws_region`
**Current behaviour**:
```
terraform apply
```
```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * Required variable not set: aws_region
  * 1 error(s) occurred:

* 1 error(s) occurred:

* Not a valid region: ${var.aws_region}
```

**Comment by mitchellh** [comment]
This might actually be fixed in my branch already. i'll assign this to myself since I ran into this and I think I fixed it.

**Comment by radeksimko** [comment]
Great. Also, there's an inconsistent behaviour between `plan` and `plan`/`destroy`.
`plan` never gives prompt and just expects the variables to be provided.

Is this a feature or a bug which should be submitted separately?

**Comment by pikeas** [comment]
Related? #1899

**Comment by radeksimko** [comment]
@pikeas I think those are two separate things.
`tfvars` & prompt and generally any prompt (with or without tfvars) for `plan`

**Comment by jen20** [comment]
I just verified that this is fixed on the `master` branch, so I'm going to close this issue for now.

**Comment by radeksimko** [comment]
@jen20 agreed, I just tested out my original example and it is fixed.

**Comment by jmehnle** [comment]
This is still happening for me with Terraform 0.6.14:

```
$ terraform -version
Terraform v0.6.14

$ terraform plan
var.aws_access_key
  AWS access key

  Enter a value: ^C
Error configuring: Error asking for aws_access_key: interrupted

$ terraform plan -var-file terraform.tfvars
Error configuring: 1 error(s) occurred:

* 1:3: unknown variable accessed: var.aws_access_key in:

${var.aws_access_key}
```

**Comment by chids** [comment]
Can confirm this is still happening with `v0.6.15`.

**Comment by radeksimko** [comment]
@chids I think the original issue was different to what @jmehnle mentions above. Can one of you two (or both) open a new issue involving relevant `*.tf` files, sequence of commands + potential `tfvars` files?

Thanks.
