### ISSUE TITLE
Support for EBS elastic volume

### ISSUE THREAD

**Issue by rkulagowski** [hashicorp/terraform#12302]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.8.7

### Affected Resource(s)
aws_ebs_volume

### Expected Behavior
Now that Amazon supports changing a volume on-the-fly (without destroying it)
https://aws.amazon.com/blogs/aws/amazon-ebs-update-new-elastic-volumes-change-everything/

it would be useful to add support to terraform by specifying in the aws_ebs_volume declarations that we want a migrate rather than destroy -> create.

### Actual Behavior
Changing from gp2 to sc1 shows that terraform was going to force a new resource (and therefore destroy the existing data) rather than modifying in place.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

terraform plan:

```
-/+ aws_ebs_volume.SS02T03QDOC02_Data
    availability_zone: "us-east-1d" => "us-east-1d"
    encrypted:         "true" => "true"
    iops:              "" => "<computed>"
    kms_key_id:        "arn:aws:kms:us-east-1:cut:key/cut" => "<computed>"
    size:              "1500" => "1500"
    snapshot_id:       "snap-removed" => "snap-removed"
    type:              "gp2" => "sc1" (forces new resource)
```

**Comment by stack72** [comment]
Hi @rkulagowski 

Thanks for opening the issue here - I am glad to be able to say this is already supported and will be available for Terraform 0.8.8 later this week

Hope this helps

Paul
