### ISSUE TITLE
Unable to create dependency in module to another module or resource

### ISSUE THREAD

**Issue by crmadhu20** [hashicorp/terraform#12301]
Hi Team

   Am using terraform 0.8.7 version and am having issues in creating dependency  inside the module,
depends_on to a module or resource is not supported which makes us not use modules because we have dependencies.

Kindly fix this issue or give us a work around until a permanent fix

Thanks
Madhu

**Comment by mitchellh** [comment]
Hi, please expand on this and use the template provided when creating an issue (please create a new issue, and follow the template). Thank you!
