### ISSUE TITLE
aws_redshift_parameter_group always reports as needing modification

### ISSUE THREAD

**Issue by jklukas** [hashicorp/terraform#12310]
### Terraform Version
Terraform v0.8.7

### Affected Resource(s)
- aws_redshift_cluster
- aws_redshift_parameter_group

### Terraform Configuration Files
```hcl
resource "aws_redshift_parameter_group" "redshift-parameter-group" {
  name = "redshift-parameter-group"
  family = "redshift-1.0"
  parameter {
    name = "datestyle"
    value = "ISO, MDY"
  }
  parameter {
    name = "enable_user_activity_logging"
    value = true
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

^ That page returns a 500 at the moment (assuming due to AWS outage).

### Expected Behavior
After running `terraform apply`, a subsequent run of `terraform plan` should indicate no changes needed.

### Actual Behavior
A subsequent `terraform plan` indicates a need to modify the configuration:

```
~ aws_redshift_parameter_group.terraform-example
    parameter.1108401317.name:  "" => "enable_user_activity_logging"
    parameter.1108401317.value: "" => "1"
    parameter.1221875064.name:  "datestyle" => "datestyle"
    parameter.1221875064.value: "iso, mdy" => "ISO, MDY"
    parameter.484080973.name:   "enable_user_activity_logging" => ""
    parameter.484080973.value:  "true" => ""
```

It looks like the parameters are modeled as a set and the hash depends on both the name and the value. The value `true` in terraform resolves to `1` and is accepted by Redshift, but Redshift reports back a string "true", which has a different hash. 

Likewise, the string "ISO, MDY" is accepted by Redshift, but it reports back a lowercased version which has a different hash.

If I change the values to their normalized forms, everything stabilizes and it no longer tries to modify the parameter group on every run.

I had originally assumed this problem was due to the ordering being nondeterministic, since the order of parameters gets all jumbled in the `plan` output. It was difficult to figure out that normalizing the parameter values would fix things due to that jumbling.

Should the hash function only consider the name?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

### Important Factoids
N/A

### References
N/A

**Comment by huydinhle** [comment]
@stack72  is that okie If I work on this?

**Comment by stack72** [comment]
@huyanhvn please feel free :)

**Comment by huyanhvn** [comment]
@huydinhle Paul probably meant you, not me :)

**Comment by huydinhle** [comment]
yay! ty
