### ISSUE TITLE
provider/openstack: Apply error when flavor's RAM greater than 65535

### ISSUE THREAD

**Issue by Jim-01** [hashicorp/terraform#12322]
### Terraform Version
v0.8.6

### Affected Resource(s)
openstack_compute_instance_v2

### Terraform Configuration Files
resource "openstack_compute_instance_v2" "basic" {
  name = "basic"
  image_id = "ad091b52-742f-469e-8f3c-fd81cadf0743"
  **flavor_name** = "e1.8xlarge"
  key_pair = "my_key_pair_name"
  security_groups = ["default"]

  network {
    name = "my_network"
  }
}

### Debug Output
* openstack_compute_instance_v2.basic: json: cannot unmarshal number 1.048576e+06 into Go value of type int

### Panic Output
N/A

### Steps to Reproduce
Create a flavor with RAM equals 1048576 MB, then apply the resource openstack_compute_instance_v2.

### Important Factoids
There is no problem with v0.7.0

### References
N/A

**Comment by jtopjian** [comment]
@Jim-01 Thanks for reporting this one. It's a frustrating one, so I'm sorry that you ran into it.

This has already been reported in #10130. There's a link to the upstream Gophercloud discussion about the bug, which hopefully will be resolved soon.

I'm going to close this issue, but do let me know if you have any questions.
