### ISSUE TITLE
Support for EC2 termination protection option

### ISSUE THREAD

**Issue by jmreicha** [hashicorp/terraform#1233]
I was wondering if it would be possible to add termination protection to the aws_instance resource?

I saw this referenced briefly in https://github.com/hashicorp/terraform/issues/28 but figured I would open another issue to track it separately.

**Comment by jaxxstorm** [comment]
+1 I have to set this manually at the moment, it's a pain :)

**Comment by ketzacoatl** [comment]
+1

**Comment by kalefranz** [comment]
+1
