### ISSUE TITLE
Elastic volume not working

### ISSUE THREAD

**Issue by adespain** [hashicorp/terraform#12346]
I posted this in a closed issue, so I put it here in case no one sees the other one...
I am still getting (forces new resource) when trying to increase a volume size, am I doing something wrong? I am using terraform v0.8.7. I changed the size from 10 to 12 and this is what the terraform plan output is:

-/+ aws_ebs_volume.ebs_home
availability_zone: "us-west-2a" => "us-west-2a"
encrypted: "true" => "true"
iops: "" => ""
kms_key_id: "xxx" => "xxx"
size: "10" => "12" (forces new resource)
snapshot_id: "" => ""
type: "gp2" => "gp2"

-/+ aws_volume_attachment.att_home
device_name: "/dev/xvdc" => "/dev/xvdc"
force_detach: "" => ""
instance_id: "i-08d75faa0b4457571" => "i-08d75faa0b4457571"
skip_destroy: "" => ""
volume_id: "vol-084aa2abd8d34121f" => "${aws_ebs_volume.ebs_home.id}" (forces new resource)

**Comment by stack72** [comment]
Hi @adespain 

This will only be part of terraform 0.8.8 - which hasn't been released yet

Thanks

Paul

**Comment by adespain** [comment]
Thanks @stack72
