### ISSUE TITLE
aws_network_acl errors when destroyed subnet_ids are removed

### ISSUE THREAD

**Issue by kreisys** [hashicorp/terraform#12353]
### Terraform Version
```
bash-3.2$ terraform -v
Terraform v0.8.7
```
### Affected Resource(s)
- aws_network_acl

### Terraform Configuration Files
I distilled it to this:
```hcl
variable "subnet_count" {
  default = 3
}

variable "cidr_block" {
  default = "10.0.0.0/16"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "vpc" {
  cidr_block = "${var.cidr_block}"
}

resource "aws_subnet" "subnet" {
  count             = "${var.subnet_count}"
  cidr_block        = "${cidrsubnet(var.cidr_block, 8, count.index)}"
  vpc_id            = "${aws_vpc.vpc.id}"
  availability_zone = "us-east-1a"
}

resource "aws_network_acl" "acl" {
  vpc_id     = "${aws_vpc.vpc.id}"
  subnet_ids = ["${aws_subnet.subnet.*.id}"]
}
```

### Debug Output
https://gist.github.com/kreisys/109befa5517a3d2d9e9972effa8c93ac

### Expected Behavior
Reducing the subnet count should not produce an error.

### Actual Behavior
Reducing the subnet count does produce an error.

### Steps to Reproduce
In a directory with the .tf file I provided run:
1. `terraform apply`
2. `terraform apply -var 'subnet_count=1'`

**Comment by snowsky** [comment]
Looks like the function findNetworkAclAssociation returned an error code.

**Comment by snowsky** [comment]
Before this function findNetworkAclAssociation runs, the subnets have been deleted so there is nothing returned and it broke the run.

**Comment by kreisys** [comment]
That's what it looks like. Deleting a subnet automatically removes it from the network acl. I worked around it by creating a separate (identical) acl for each subnet and adding a lifecycle clause which ignores changes to subnet_ids. It works well but it's convoluted.

**Comment by snowsky** [comment]
It failed at [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_network_acl.go#L287) after destroyed 2 subnets and it is still trying to find those deleted subnets.
