### ISSUE TITLE
Add support for provisioners to modules

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1240]
It is possible to use provisioners **inside** the module's code, but in case of `local-exec`, I'd personally discourage people from doing so (depending on what they're trying to do obviously).

I think it's hard to guess for the module's author what platform that local system will be etc. etc.

I can imagine the implementation could be as simple as this:

``` ruby
module "my_rds_instance" {
  source = "github.com/terraform-community-modules/tf_aws_rds"

  rds_instance_name = "${var.rds_instance_name}"
  rds_allocated_storage = "${var.rds_allocated_storage}"
  rds_engine_type = "${var.rds_engine_type}"
  rds_engine_version = "${var.rds_engine_version}"
  database_name = "${var.database_name}"
  database_user = "${var.database_user}"
  database_password = "${var.database_password}"
  rds_security_group_id = "${var.rds_security_group_id}"
  db_parameter_group = "${var.db_parameter_group}"

  provisioner "local-exec" {
    command = "echo 'export DB_HOST=http://${self.instance_endpoint}' > ./env/db-host.sh"
  }
}
```

**Comment by joescii** [comment]
+1

**Comment by kaelumania** [comment]
+1

**Comment by wr0ngway** [comment]
+1

**Comment by catsby** [comment]
Interesting idea, I wonder, do you think `null_resource` is a viable alternative here?

- https://www.terraform.io/docs/provisioners/null_resource.html

Or the `template_file`? 

- https://www.terraform.io/docs/providers/template/d/file.html

**Comment by mitchellh** [comment]
I agree with @catsby that the null resource + `depends_on` referencing modules (new in 0.8) is the way to go here.

The biggest complication here is: how do we know when a module is _new_? Do we just do it the first time a module completely applies? What if resources are added/removed to a module? Do we do it whenever dependent resources in the module recreate? etc.

I'm not saying those are unsolvable problems by any means, but I think we have a ways to go in core land before we can look into this (such as splitting provisioners out into their own graph nodes). In the mean time, there is a great workaround with `null_resource` depending on a module or triggered by module outputs.

**Comment by aleclarson** [comment]
Is there documentation for `null_resource` triggering when a module is created (not sure if that's the correct terminology here). I'm trying to `remote_exec` on an Openstack resource that's created in a module.

```tf
module "server" {
  source="./openstack"
}

resource "null_resource" "something" {
  triggers {
    # What goes here?
  }
  provisioner "remote_exec" {
    inline = [
      "echo Hello world"
    ]
  }
}
```
