### ISSUE TITLE
[DOC] In google_project's page, there are two references to project_id variable, one optional and one required

### ISSUE THREAD

**Issue by tpoindessous** [hashicorp/terraform#12408]
### Terraform Version

https://www.terraform.io/docs/providers/google/r/google_project.html

### Affected Resource(s)
documentation of google project.

### Expected Behavior
What should have happened?

### Actual Behavior
In https://www.terraform.io/docs/providers/google/r/google_project.html, there are two references to projet_id variable. One is optional, and one is required.

**Comment by stack72** [comment]
Hi @tpoindessous 

Thanks for pointing out the issue here - I have just updated the docs and pushed to the website

Thanks

Paul
