### ISSUE TITLE
Output interpolation errors are being silently dropped

### ISSUE THREAD

**Issue by LegNeato** [hashicorp/terraform#12403]
### Terraform Version
`0.8.8`

### Affected Resource(s)
* `output`, when it isn't used as an input (instead used with `terraform output`).

### Debug Output
`2017/03/02 23:04:27 [WARN] Output interpolation "aws_codedeploy_deployment_group" failed: Resource 'foo' does not have attribute 'name' for variable 'foo.name'
`

### Expected Behavior
I should be warned the `output` is discarded, or maybe it should even error out.

### Actual Behavior
Output was silently discarded and I am unable to query with `terraform output`. Had to run with `TF_LOG=1` to see what was going on.

### Config

```
output "info" {
  value = "${map(
    "group", "${aws_codedeploy_deployment_group.foo.name}",
  )}"
}
```

### Steps to Reproduce
1. Create an output with an invalid value
2. Make sure it is not the input to anything
3. See it doesn't show up in `terraform output`
4. See no warning or error is displayed

**Comment by mitchellh** [comment]
Dup of #9080. Thanks!
