### ISSUE TITLE
openstack_compute_instance_v2, fixed_ip_v4 - destroy/create could use a wait/sleep

### ISSUE THREAD

**Issue by delias-** [hashicorp/terraform#12415]
When triggering a destroy/create of an openstack_compute_instance_v2 resource that uses a fixed_ip_v4 address, the create sometimes fails because it happens too soon after the destruction -- openstack has not yet completely free'd up the IP address after the destruction.

The workaround is just waiting a few seconds (or however long it takes openstack to catch up) and re-run the terraform apply to successfully create the instances.

I have not been able to find anything like this, but is there some sort of hook that can force terraform to wait after the destruction and before the creation of something relying on the same fixed_ip_v4 that was just destroyed?

### Terraform Version
Terraform v0.8.5

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2
- fixed_ip_v4

### Terraform Configuration Files
```hcl
provider "openstack" {
  auth_url    = "${var.keystone}"
  token       = "${var.token}"
  tenant_id   = "${var.tenant}"
  insecure    = false
}

resource "openstack_compute_instance_v2" "test1_qa_001_srv01" {
    region        = "dev"
    name          = "test1-qa-001-srv01"

    flavor_name   = "m4.4xlarge"
    image_name    = "centos7.2"

    network {
      name        = "dev-internal-net"
      fixed_ip_v4 = "10.56.185.97"
    }

}
```

You can manually re-produce this by just doing a terraform destroy or taint of a handful of instances like the above, and then running the terraform apply. 

We expect all instances to be destroyed and created.

Actual behavior is some amount of the instances fail to be created because their ipv4 addresses have not yet been made available by openstack because openstack is still processing things in the background to free up the IP address. Waiting a few seconds and re-running terraform apply is successful.

**Comment by delias-** [comment]
`stop_before_destroy` might remedy this, actually. Will give it a test.

**Comment by jtopjian** [comment]
@delias- Looks like we're typing at the same time :)

Let me know how `stop_before_destroy` works. Another option is to configure the fixed ip through an `openstack_networking_port_v2` resource as those better handle states for networking.
