### ISSUE TITLE
Terraform Vault provider panic for non existing secret

### ISSUE THREAD

**Issue by atrepca** [hashicorp/terraform#12412]
### Terraform Version
`Terraform v0.8.8`

### Affected Resource(s)
- vault-provider

### Terraform Configuration Files
```
provider "vault" {
  address = "https://vault.server.name:8200"
}

data "vault_generic_secret" "dummy-secret" {
  path = "secret/devops/dummy-path/root"
}
```

### Debug Output
https://gist.github.com/atrepca/47fce3cf0672cfd439a1297fcfda1d2a

### Expected Behavior
Terraform should error out pointing to where the error is.

### Actual Behavior
Terraform crashed with `* data.vault_generic_secret.dummy-secret: unexpected EOF`.

### Steps to Reproduce
`terraform plan` for the above HCL code, pointing to a valid Vault server.

**Comment by stack72** [comment]
Closed via #14435
