### ISSUE TITLE
aws/rds: Add support for SecondaryAvailabilityZone

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1242]
Having an RDS instance with `MultiAZ` deployment, AWS by default chooses the secondary AZ for the standby instance randomly.

It is possible though to pick a specific secondary AZ via the API:

https://github.com/awslabs/aws-sdk-go/blob/440f9da54cf714e7c27b5b4ffa789793a5fbd658/gen/rds/rds.go#L907

**Comment by ketzacoatl** [comment]
+1

**Comment by stack72** [comment]
@radeksimko so I've been having a look at this. The `SecondaryAvailabilityZone` is only available in the result of CRUD actions. It cannot actually be set via the SDK or the cli interfaces

I don't think this is a valid enhancement although I *would* have loved it to be

Thoughts?

**Comment by radeksimko** [comment]
@stack72 You're right, I was also just checking API docs to see if it's not just SDK bug, but it's apparently a feature:
http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

In fact after re-thinking this - AZs may change across deployments and accounts and pinning to a specific one doesn't make as much sense to me.

Whatever your view is, it's not supported by the API, so if anyone wants that, they'll first need to ask Amazon.
