### ISSUE TITLE
provider/fastly Header deletion causing panic

### ISSUE THREAD

**Issue by travertischio** [hashicorp/terraform#12428]
### Terraform Version
Both `0.8.7` and `0.8.8`

### Affected Resource(s)
- fastly_service_v1

### Terraform Configuration Files
```hcl
variable "fastly_api_key" {
  description = "Fastly API key"
}

provider "fastly" {
  api_key = "${var.fastly_api_key}"
}

resource "fastly_service_v1" "content_api_cache" {
  name = "Test API"

  domain {
    name = "thiserroris.notadomain.com"
  }

  backend {
    name             = "Publisher API"
    address          = "thiserroris.notadomain.com"
    port             = 80
    auto_loadbalance = true
    shield           = "iad-va-us"
  }

  header {
    name          = "Remove API version from URL"
    type          = "request"
    action        = "regex"
    destination   = "url"
    source        = "req.url"
    regex         = "^/api/v1/(.*)"
    substitution  = "/api/\\1"
    ignore_if_set = false
    priority      = 10
  }

  gzip {
    name          = "File extensions and content types"
    extensions    = ["css", "js", "html", "eot", "ico", "otf", "ttf", "json"]
    content_types = ["text/html", "application/x-javascript", "text/css", "application/javascript", "text/javascript", "application/json", "application/vnd.ms-fontobject", "application/x-font-opentype", "application/x-font-truetype", "application/x-font-ttf", "application/xml", "font/eot", "font/opentype", "font/otf", "image/svg+xml", "image/vnd.microsoft.icon", "text/plain", "text/xml"]
  }

  force_destroy = true
}
```

### Panic Output
https://gist.github.com/travertischio/125d77cd1f3aa693b7c1d1db50a33dc0

### Expected Behavior
Removing an entire request header from a fastly resource should have successfully removed the header and left the rest of the fastly resource without error.

### Actual Behavior
Terraform crashed while attempting to plan the header removal.
It looks to have tried to calculate a value on the now empty header object.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
With a fastly api key
1. `terraform apply`
2. Remove header (lines 24 - 34 of file)
3. `terraform plan`

**Comment by travertischio** [comment]
This no longer seems to be an issue in `0.9.2`

**Comment by grubernaut** [comment]
Hi @travertischio, thanks for the issue! 

Going to close this as it looks to be no longer affecting you. Feel free to respond or open a new issue if the problem persists. Thanks again!
