### ISSUE TITLE
Missing Google resource: Target SSL Proxy

### ISSUE THREAD

**Issue by maikzumstrull** [hashicorp/terraform#12422]
There is a resource on Google Cloud Platform called a [Target SSL Proxy](https://cloud.google.com/compute/docs/reference/latest/targetSslProxies/insert). It seems Terraform currently cannot create/manage these proxies.

Please add an appropriate resource, probably `google_compute_target_ssl_proxy`.

**Comment by pquerna** [comment]
They have also added TCP Proxies (in alpha):
https://cloud.google.com/compute/docs/load-balancing/tcp-ssl/tcp-proxy

So if someone is in there, a `google_compute_target_tcp_proxy` would be helpful!
