### ISSUE TITLE
Terraform should fail when interpolating nonexistent template vars in output variable

### ISSUE THREAD

**Issue by bspaans** [hashicorp/terraform#12420]
### Terraform Version

0.8.8

### Affected Resource(s)
- data template_file
- output variables
- probably more resources that depend on the output variable

### Terraform Configuration Files

in `main.tf`

```
module "test" {
  source = "module1/"
}

module "test2" {
  source = "module2/"
  input_var = "${module.test.my_output}"
}
```

in `module1/test.tf`

```
data "template_file" "tpl" {
  template = "whatever"
  vars = {
  }
}

output "my_output" {
  value = "${data.template_file.tpl.vars.doesntexist}"
}
```

in `module2/test.tf`

```
variable "input_var" { }

data "template_file" "tpl2" {
  template = "$${OtherVariable}"
  vars = {
    OtherVariable = "test"
    Variable = "${var.input_var}"
  }
}
```

### Expected Behavior
Referencing the nonexistent variable in the output variable should have failed with an error.

### Actual Behavior
Apply fails with: `* data.template_file.tpl2: failed to render : 1:3: unknown variable accessed: OtherVariable`

Note that it's failing on the "wrong" variable, which caused some head-scratching.

### Steps to Reproduce
1. `terraform get`
1. `terraform apply`

**Comment by jbardin** [comment]
Related to #12403. Once outputs can produce errors, this may take care of itself.

**Comment by ketzacoatl** [comment]
Bump, silent failures like this lead to really bad problems down the pipeline.

**Comment by jbardin** [comment]
Thanks @ketzacoatl, this also should have been closed.
The next release will have even more type information, and can present an error even earlier.

You would see something along the lines of:

```
Error: Missing map element

  on module1/main.tf line 9, in output "my_output":
   9:   value = data.template_file.tpl.vars.doesntexist
    |----------------
    | data.template_file.tpl.vars is map of string with 0 elements

This map does not have an element with the key "doesntexist".
```
