### ISSUE TITLE
Problems with cross account peering (inside same region)

### ISSUE THREAD

**Issue by mao65fi** [hashicorp/terraform#12441]
Hi.

Cannot get the peering working like i this example. Tried with v.0.8.8.
https://www.terraform.io/docs/providers/aws/r/vpc_peering_accepter.html

Seems that there a multiple issues:
- the values for vpc_id and peer_vpc_id are interchanged if you compare them with the AWS CLI parameters. I.e. Terraforms vpc_id is AWS CLI's peer_vpc_id and vice versa.

- data "aws_caller_identity" always seem to return the current account's ID, you cannot use provider with that.

- the accepter completes without error, but the peering is not actually accepted.

**Comment by ewbankkit** [comment]
@mao65fi

Terraform's `vpc_id` and `peer_vpc_id` attributes reflects which "side" of the peering connection is being managed:
* For the requester the [`aws_vpc_peering`](https://www.terraform.io/docs/providers/aws/r/vpc_peering.html) resource is used and `vpc_id` refers to the requesting VPC, `peer_vpc_id` refers to the accepting VPC
* For the accepter (in a cross-account peering) the [`aws_vpc_peering_connection_accepter`](https://www.terraform.io/docs/providers/aws/r/vpc_peering_accepter.html) resource is used and now `vpc_id` refers to the accepting VPC, `peer_vpc_id` refers to the requesting VPC

With the AWS CLI:
* The requester uses the [`ec2 create-vpc-peering-connection`](http://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpc-peering-connection.html) call, specifying `--vpc-id` and `--peer-vpc-id` matching the Terraform `aws_vpc_peering` resource
* The receiver has to use the [`ec2 accept-vpc-peering-connection`](http://docs.aws.amazon.com/cli/latest/reference/ec2/accept-vpc-peering-connection.html) call, specifying `--vpc-peering-connection-id` - returned from `ec2 create-vpc-peering-connection`, NOT the VPC IDs

I admit the documentation is slightly unclear in that where it says `// Requester's credentials.` and `// Accepter's credentials.`, you should use the various attributes of the [AWS provider](https://www.terraform.io/docs/providers/aws/index.html) to specify `profile`, `access_key`, `secret_key` etc. for the different requester and accepter accounts. Copying and pasting the example as-is will lead to 2 providers with the same underlying identity and hence a "same-account", not cross-account peering 😄. Please open a PR with any documentation changes you feel would clarify this.

If you attempt to use the `aws_vpc_peering_connection_resource` with a same-account VPC peering you should get an error like
```
* aws_vpc_peering_connection_accepter.peer: 1 error(s) occurred:

* aws_vpc_peering_connection_accepter.peer: aws_vpc_peering_connection_accepter can only adopt into management cross-account VPC peering connections
```
on `terraform apply`.
Could you please retry once the providers are configured for different accounts.

**Comment by FransUrbo** [comment]
After a lot of tries, I got cross-account peering working. Well, mostly. I can't setup the routes properly.

Have a look at: https://github.com/hashicorp/terraform/issues/12448
