### ISSUE TITLE
Terraform will not build VPNs.

### ISSUE THREAD

**Issue by magnusthorne** [hashicorp/terraform#12440]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.8.8  The problem has existed since 0.7

### Affected Resource(s)
Please list the resources as a list, for example:
aws_vpn_connection

### Terraform Configuration Files
```hcl
resource "aws_vpn_connection" "name-removed" {
    vpn_gateway_id = "${aws_vpn_gateway.name-removed.id}"
    customer_gateway_id = "${aws_customer_gateway.name-removed.id}"
    type = "ipsec.1"
    static_routes_only = false

    tags {
        Name = "name-removed"
    }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Create a VPN in Terraform.  Delete the VPN manually.  Run Terraform apply again.  I expect it to create the VPN.  

### Actual Behavior
It doesn't build a VPN.  I must wait until AWS removes the deleted VPN from the console to run the apply again.

### Steps to Reproduce
Create a VPN in Terraform.  Delete the VPN manually.  Run Terraform apply again. 

### Important Factoids
AWS VPN

### References
None

**Comment by clstokes** [comment]
This appears to be the same issue as in https://github.com/hashicorp/terraform/issues/7859 where Terraform is not checking the `State` of the VPN connection.

Here's a full config w/ steps to reproduce:

1. https://gist.github.com/clstokes/08fa7579eb6614f7767c3997e4209292
1. `terraform apply` - create the environment
1. `aws ec2 delete-vpn-connection --vpn-connection-id $(terraform output aws_vpn_connection_id)` - will delete the VPN connection
1. `aws ec2 describe-vpn-connections` - will show connection as `"State": "deleted"`
1. `terraform plan` - will show no changes needed. Should show that VPN connection must be re-created.
1. `terraform destroy -force` - clean up once done.
