### ISSUE TITLE
Terraform 0.8.8 crashed

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform#12446]
I just perform the normal `terraform plan` command and it crashed. The last time is ok, but this time is not.

### Terraform Version
Terraform v0.8.8

### Panic Output
you can check crash log here. [https://gist.github.com/hanks/ab880b41a5a4d7a73666b0abcebf3b50](https://gist.github.com/hanks/ab880b41a5a4d7a73666b0abcebf3b50)

**Comment by stack72** [comment]
Hi @hanks 

Sorry for the issue you are having here - in order to try and help us recreate it to bug fix, please can you post your terraform config (minus any secrets)

Thanks

Paul
