### ISSUE TITLE
Add support for network instances/multiple subnets in aws_instances

### ISSUE THREAD

**Issue by jaxxstorm** [hashicorp/terraform#1244]
If you're launch some kind of network AMI with multiple interfaces, you probably want to put them in multiple subnets with an interface for each subnet. Currently, this isn't possible as you can't create network interfaces using terraform

**Comment by ketzacoatl** [comment]
+1

**Comment by bgeesaman** [comment]
+1

**Comment by ketzacoatl** [comment]
@bgeesaman, sharing the code you have doing that be a valuable contribution to the community, would you be able to spin that off as a module in the future?

**Comment by bgeesaman** [comment]
@ketzacoatl, I'm afraid I'm not sure what your asking.  Can you clarify what code you're referring to and what you mean by spinning that off as a module? I'm afraid I have zero go language experience if that's what you mean.

**Comment by ketzacoatl** [comment]
@bgeesaman, sorry.. I don't mean to hijack the ticket, I just meant to point out the functionality you described above would be a great [Terraform module](https://terraform.io/docs/modules/index.html).

**Comment by matthewrees** [comment]
+1

**Comment by justnom** [comment]
If it helps I have fixed support for AWS network interfaces in PR #2232. This has been tested in production and works with each interface in a different subnet.

If you use Docker, I have an image built which uses my changes: https://hub.docker.com/u/justnom/terraform

If you want to use it just as you do with the `terraform` binary you could add the following alias:
```
alias terraform='sudo docker run --rm -it -v $PWD:/wrk -v /home/<YOUR_USER_HERE>/.aws:/root/.aws:ro -w /wrk justnom/terraform'
```

**Comment by ErikEvenson** [comment]
Being able to add a second interface is important for cases where you would like to have management commands arrive via a private network interface and other traffic on another network interface.  +1

**Comment by zzzuzik** [comment]
+1

**Comment by catsby** [comment]
Hey Friends –

This issue is quite old and I _believe_ now covered by Terraform.

- we introduced `aws_network_interface` https://www.terraform.io/docs/providers/aws/r/network_interface.html 
- we introduced `aws_route_table` support for instance id, network interface id, et. al

Thanks!
