### ISSUE TITLE
No RSS feed on the download page

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#12458]
It would be extremely useful/helpful if there's an RSS feed on the download page (https://www.terraform.io/downloads.html). That way I can get instant notice of a new release..

**Comment by apparentlymart** [comment]
Hi @FransUrbo!

This isn't exactly what you're looking for, but note that you can get an Atom feed of the releases as tracked by Github here:
https://github.com/hashicorp/terraform/releases.atom

A release is usually created on Github for each stable release, though not for betas and release candidates.

**Comment by FransUrbo** [comment]
I can live with that, thanx!

Any chance to have that information added to the Downloads page?

**Comment by stack72** [comment]
Hi @FransUrbo 

Right now, the HashiCorp Releases Service features a full [JSON API](https://www.hashicorp.com/blog/hashicorp-and-fastly.html#json-api) which provides machine-parsable version information.

I believe this will work for you?

Paul

**Comment by FransUrbo** [comment]
Nah, to complicated. I wanted it in my mailbox, like everything else (like that message about the API).

But please put that part on the Download page as well.

**Comment by rrueth** [comment]
I subscribe to the releases.atom feed for Terraform and the various Terraform providers.  It's very helpful to be alerted to new releases. The downside is that once I see that a new release is out, I need to navigate to the CHANGELOG to find out what changes are in the latest release. It would be very helpful if the changes could also be posted with the release.  Then, I could see everything in one place.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
