### ISSUE TITLE
Terraform Crash when removing aws autoscaling lifecycle hooks

### ISSUE THREAD

**Issue by patricklecuyer** [hashicorp/terraform#12454]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_autoscaling_group

### Panic Output
https://gist.github.com/patricklecuyer/79393967a7bae365d49cd6a39284269c

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an autoscaling group with initial lifecycle hooks
2. terraform apply
3. remove lifecycle hooks
4. terraform applu

**Comment by jbardin** [comment]
Hi @patricklecuyer,

What version of Terraform are you using? This should be fixes in all current releases.

**Comment by patricklecuyer** [comment]
You're right, I thought I was running the latest release, but I was running 0.8.6.  Retested with 0.8.8 and it works.  Closing issue.
