### ISSUE TITLE
Crash while trying to plan RDS/MySql example

### ISSUE THREAD

**Issue by githublemming** [hashicorp/terraform#12451]
Hi there,

I've provided in the link to Gist the code that I was trying to run to get the exception. This was taken straight from the documentation.

Leading up too this I had been trying to get RDS and MySql to play nicely with no luck in another file. I could define the MySql provider, but when I tried to add in a _database, _user, or _grant I was getting EOF errors.

```
resource "aws_db_instance" "default" {
  allocated_storage    = 10
  engine               = "mysql"
  engine_version       = "${var.engine_version}"
  instance_class       = "${var.instance_class}"
  name                 = "${var.dtap}-${var.platform}-${var.name}"
  username             = "${var.master_username}"
  password             = "${var.master_password}"
  db_subnet_group_name = "${var.rds_subnet_group}"
  parameter_group_name = "${var.parameter_group_name}"
}

provider "mysql" {
  endpoint = "${aws_db_instance.default.endpoint}"
  username = "${var.master_username}"
  password = "${var.master_password}"
}

resource "mysql_database" "app" {
  name = "${var.db_name}"
}
```
The **unexpected EOF** is vague as to where the problem is, and as there is a heavy use of variables, I decided to go back to basics and try to get the example from the docs working. Which is when I got the exception.

### Terraform Version
v0.8.8
OS X 10.12.3

### Affected Resource(s)
provider : aws
resource : aws_db_instance
provider : mysql
resource : mysql_database

### Panic Output
https://gist.github.com/githublemming/61f4e7cdb2830d65ca1ccf2a99d0b026

### Expected Behavior
A plan should have been created

### Actual Behavior
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Repeatability
I've done a plan 3 or 4 times and always gets the crash report.

### Steps to Reproduce
I've included in Gist the file that I got the exception against.

*terraform plan*

**Comment by stack72** [comment]
hi @githublemming 

Thanks for the report of the issue here - this specific panic has been fixed (in #12391), but we have found the cause of the issue to be a more indepth problem

A new issue has been opened to track the progress on it - please track it to find out it's progress #12393

Thanks

Paul
