### ISSUE TITLE
aws_route53_record.internal: diffs didn't match during apply.

### ISSUE THREAD

**Issue by stevenayers** [hashicorp/terraform#12467]
### Terraform Version
Terraform v0.8.6 & v0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_record
- aws_route53_zone

### Terraform Configuration Files
```hcl
# AWS_ROUTE53_ZONE definition
resource "aws_route53_zone" "internal" {
  name   = "abcdef.internal"
  vpc_id = "${aws_vpc.default.id}"
}

output "internal_zone_id" {
  value = "${aws_route53_zone.internal.id}"
}

# AWS_REOUTE53_RECORD definition
resource "aws_route53_record" "internal" {
  zone_id = "${var.internal_zone_id}"
  name = "${var.server_type}.${var.internal_zone_name}"
  type = "A"
  ttl = "86400"
  records = ["${aws_eip.ec2.private_ip}"]
}

```

### Debug Output
https://gist.github.com/Stevea37/018aaafcd0da999cb97ac87a0352c64d

### Expected Behavior
Should have built out 3 ec2 instances

### Actual Behavior
Built out the three ec2 instances, then failed right at the end.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` OR `terraform destroy --force; terraform apply`

**Comment by Stevea37** [comment]
I have updated Terraform to v0.8.8 and I still get the same error.
