### ISSUE TITLE
Support for EC2 detailed monitoring option

### ISSUE THREAD

**Issue by jmreicha** [hashicorp/terraform#1246]
Found another option that AWS folks might find useful when creating aws instances.

**Comment by joshgarnett** [comment]
+1, http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html we just need to add the Monitoring tag to the api request

**Comment by dwradcliffe** [comment]
I see that the PR was merged and released, but it's not working for me. I'm attempting to modify existing instances. `apply` shows it modifying the instances and reports success but the instances don't change. The next plan shows the same changes needed (correctly).

**Comment by catsby** [comment]
Hey @dwradcliffe – the issue you report here was fixed in https://github.com/hashicorp/terraform/pull/2794
