### ISSUE TITLE
Support batch of requests

### ISSUE THREAD

**Issue by Pryz** [hashicorp/terraform#12469]
Hello,

In order to avoid hitting API rate limits, Terraform should send requests per batch when the API allows it.

For example, the resource [aws_cloudwatch_metric_alarm](https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html) uses [DescribeAlarms](https://godoc.org/github.com/aws/aws-sdk-go/service/cloudwatch#CloudWatch.DescribeAlarms) which is waiting for a list of alarms to retrieve. 

Currently, if you have 300 CloudWatch alarms (because you are heavily using ASG), Terraform will try to run 300 times DescribeAlarms and you will hit the AWS rate limit for this call.

Of course there is some workarounds : 
1. Decrease "-parallelism" : make things way slower
2. Ask AWS to increase your rate limit : this process can take time
3. Increase max_retries of the AWS provider : Terraform will retry and retry and retry again until it works. Make things way slower too

Also, those are workarounds and Terraform is not fully leveraging the API.

Could it be possible to gather all the aws_cloudwatch_metric_alarm in a "pool"/"batch" before sending the request ?

I'm taking CloudWatch as an example here, multiple API calls allow to request multiple "resources" at a time.

### Terraform Version
0.8.8

### Affected Resource(s)
*

**Comment by Pryz** [comment]
Any thought here ? :)

**Comment by clstokes** [comment]
`aws_security_group_rule` would benefit from this too.

**Comment by apparentlymart** [comment]
Hi all! Thanks for opening this.

There's already #7388 with some discussion about this idea, so I'm going to close this one to consolidate the discussion over there.
