### ISSUE TITLE
Unable to create dependency in module to another module or resource

### ISSUE THREAD

**Issue by crmadhu20** [hashicorp/terraform#12466]
Hi there,

### Terraform Version
0.8.7

### Affected Resource(s)
terraform modules

I created a module for aws vpc

Am unable to create a depends_on on the module

Terraform doesn't support depends_on in the module

### Expected Behavior
What should have happened?
The depends_oon supports only in resources currently
### Actual Behavior
What actually happened?
if we use that in module it fails saying depends_on not a valid command

**Comment by FransUrbo** [comment]
If I understand it, you have two modules: `module1` and `module2` and `module2` depend on `module1`.

To make sure that `module2` isn't built first, "import" a value from `module1`:

```
module "module1" {
    source = "./module1"
}

module "module2" {
    source = "./module2"
    samevar = "${module.module1.somevar}"
}
```

Then "export" (i.e., "output") that from module1:

./module1/outputs.tf
```
output "somevar" {
  value = "nothing"
}
```

and "import" it into module2:

./module2/variables.tf
```
variable "somevar" {}
```

**Comment by crmadhu20** [comment]
Hi Frans

  Thanks for your reply, I saw your reply and i can understand that you are asking me to pass the output from module1 as input to module2. If i do this am not sure it will wait for module 1 creation like depends_on works

**Comment by FransUrbo** [comment]
It should. Because if the export from module1 is a variable in turn, like

```
output "somevar" {
  value = "${some.thing.value}"
}
```

then module1 needs to be finished first, so that that variable will be known. It _might_ not work if you're exporting a static, but it should if you export a variable..

Try it and see if that helps.

**Comment by crmadhu20** [comment]
Hi FransUrbo

   Thanks for your help in this, I will try this and let you know. Sorry for the late response

Madhu

**Comment by ketzacoatl** [comment]
Should this be closed in favor of #10462?

**Comment by akhilesh0** [comment]
+1

**Comment by apparentlymart** [comment]
Indeed @ketzacoatl, this does seem to be the same as what's being discussed in #10462, so I'm going to close this one as a duplicate. Thanks for pointing that out!

**Comment by sebastianwthh** [comment]
> If I understand it, you have two modules: `module1` and `module2` and `module2` depend on `module1`.
> 
> To make sure that `module2` isn't built first, "import" a value from `module1`:
> 
> ```
> module "module1" {
>     source = "./module1"
> }
> 
> module "module2" {
>     source = "./module2"
>     samevar = "${module.module1.somevar}"
> }
> ```
> 
> Then "export" (i.e., "output") that from module1:
> 
> ./module1/outputs.tf
> 
> ```
> output "somevar" {
>   value = "nothing"
> }
> ```
> 
> and "import" it into module2:
> 
> ./module2/variables.tf
> 
> ```
> variable "somevar" {}
> ```

In line 7 of the code example is "samevar" supposed to be "somevar"? I tried this solution, but I found resources in module2 that weren't dependent on anything still did not wait for the completion of module1 before starting.
