### ISSUE TITLE
Terraform crashed In DB security Group

### ISSUE THREAD

**Issue by ranjitshinde91** [hashicorp/terraform#1247]
When in aws_db_security_group resource ingress is defined like 
ingress {
        cidr = ["${aws_vpc.demo-vpc.cidr_block}"]
    }
Terraform crashes.

If i give value like :
ingress {
        cidr = "${aws_vpc.demo-vpc.cidr_block}"
    }
It works fine.
I guess there should be validation for cidr input

**Comment by catsby** [comment]
Thank you for submitting your crasher, I'm sorry you ran into this. 
Here's a full configuration that reproduces this:

```javascript
provider "aws" {
  region="us-west-2"
}

resource "aws_db_security_group" "default" {
    name = "rds_sg"
    description = "RDS default security group"

    ingress {
        cidr = ["${aws_vpc.foo.cidr_block}"]
    }
}

resource "aws_vpc" "foo" {
  cidr_block = "10.1.0.0/16"
  enable_dns_hostnames = true
}
```

I believe this is a core bug:

```console 
Refreshing Terraform state prior to plan...


Error running plan: 1 error(s) occurred:

* 1 error(s) occurred:

* unexpected EOF
panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
```

cc @phinze

**Comment by phinze** [comment]
Yep this is a `helper/schema` bug - that should be triggering a validation error but it's somehow making it through.

We should be catching it here:

https://github.com/hashicorp/terraform/blob/90058a6c48e4f0a892a7e58a540a751f3ca36f78/helper/schema/schema.go#L1066-L1071

But we're not. I bet it has something to do with the fact that `ingress` is a sub-Resource so we're not appropriately recursing. We'll get this sorted! :+1:

**Comment by mitchellh** [comment]
This is all fixed up!
