### ISSUE TITLE
Cannot "go get" terraform

### ISSUE THREAD

**Issue by elricsfate** [hashicorp/terraform#12470]
### Terraform Version
I'm running the vagrant dev environment for Terraform

### Affected Resource(s)
 
N/A

### Terraform Configuration Files
N/A

### Debug Output
root@terraform:/terraform-provider-vultr# go get github.com/hashicorp/terraform
package context: unrecognized import path "context" (import path does not begin with hostname)

### Panic Output
N/A

### Expected Behavior
Terraform and dependeicies should have been grabbed.

### Actual Behavior
The following error 

```
root@terraform:/terraform-provider-vultr# go get github.com/hashicorp/terraform
package context: unrecognized import path "context" (import path does not begin with hostname)
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Clone terraform git. 
2. vagrant up
3. Installed golang. 
4.  go get github.com/hashicorp/terraform

### Important Factoids
Running in terraform dev container.

**Comment by apparentlymart** [comment]
Hi @elricsfate!

I think you may not be using a new enough version of Go. I forget what version `context` was added in but it is a recent addition to the standard library. Terraform is now primarily targeting Go 1.8.

**Comment by apparentlymart** [comment]
Oh, I see now that you said you are using the Vagrant setup. I don't use that myself but I guess this means we need a newer Go in there.

**Comment by elricsfate** [comment]
Closing this because apparently you are supposed to be connecting via "vagrant ssh" (I'm unfamiliar with vagrant) and I was using docker. I will test after I manage to connect.
