### ISSUE TITLE
Terraform 0.8.8 does not play well with Cylance A/V

### ISSUE THREAD

**Issue by Jaff** [hashicorp/terraform#12474]
### Terraform Version
0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
not related

### Terraform Configuration Files
```hcl
Not related
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Expected plan

### Actual Behavior
Crash report:
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x4cbad8a, 0x21)
	/opt/go/src/runtime/panic.go:596 +0x95 fp=0x7fff5fbff3a0 sp=0x7fff5fbff380
runtime.goenvs()
	/opt/go/src/runtime/os_darwin.go:108 +0xa0 fp=0x7fff5fbff3d0 sp=0x7fff5fbff3a0
runtime.schedinit()
	/opt/go/src/runtime/proc.go:486 +0xa1 fp=0x7fff5fbff410 sp=0x7fff5fbff3d0
runtime.rt0_go(0x7fff5fbff448, 0x8, 0x7fff5fbff448, 0x0, 0x0, 0x8, 0x7fff5fbff698, 0x7fff5fbff6a8, 0x7fff5fbff6ad, 0x7fff5fbff6b9, ...)
	/opt/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7fff5fbff418 sp=0x7fff5fbff410

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
Our infrastructure relies on "tf" wrapper script that provides working directory and dependant variables. 

### Important Factoids
Cylance anti-virus has been implicated in crash of go-lang 1.8:
https://github.com/junegunn/fzf/issues/849

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by Jaff** [comment]
Changing Cylance policy to execute-only per-machine fixes this.

**Comment by arohter** [comment]
https://github.com/golang/go/issues/18171

**Comment by jbardin** [comment]
Hi @Jaff,

Sorry, but there's not much we can do to stop Cylance from interfering with executables on your system.

**Comment by jamiseichenauer** [comment]
This is most likely a compatibility issue with CylancePROTECT Memory Protection. If you have Memory Protection disabled you will not encounter it. If you have Memory Protection enabled please ask your Cylance administrator to try adding the following Memory Protection exclusions:
/usr/local/go/bin/go
/usr/local/go/pkg/tool/darwin_amd64/compile
/usr/local/go/pkg/tool/darwin_amd64/link

**Comment by alotofnoodles** [comment]
@jamiseichenauer 

I tried this approach without any luck. I installed go via homebrew and my go executable is on `/usr/local/go` and the others executable are in : 

`/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64/link `  
`/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64/compile`

**Comment by jamiseichenauer** [comment]
@alotofnoodles Can you use dtrace (iosnoop, execsnoop) to see what other executables are being invoked? Most likely additional exclusions are required in this case.

**Comment by jamiseichenauer** [comment]
In my testing I added an exclusion for /usr/local/go/pkg/tool/darwin_amd64/asm and it allowed me to run make

**Comment by odupuy** [comment]
Similar issue here with 0.9.2. 
Mac OS Sierra 10.12.3 with Cylance  1.2.1418.609
I will try to have my Cylance administrator do something...

terraform --version
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x5954109, 0x21)
	/opt/go/src/runtime/panic.go:596 +0x95 fp=0x7fff5fbff300 sp=0x7fff5fbff2e0
runtime.goenvs()
	/opt/go/src/runtime/os_darwin.go:108 +0xa0 fp=0x7fff5fbff330 sp=0x7fff5fbff300
runtime.schedinit()
	/opt/go/src/runtime/proc.go:486 +0xa1 fp=0x7fff5fbff370 sp=0x7fff5fbff330
runtime.rt0_go(0x7fff5fbff3a8, 0x2, 0x7fff5fbff3a8, 0x0, 0x0, 0x2, 0x7fff5fbff5b8, 0x7fff5fbff5c2, 0x0, 0x7fff5fbff5cc, ...)
	/opt/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7fff5fbff378 sp=0x7fff5fbff370

**Comment by jamiseichenauer** [comment]
Please point your Cylance administrator to the following:
https://support.cylance.com/hc/en-us/articles/115004085328-Using-CylancePROTECT-with-GoLang
Requires a Cylance support login

**Comment by jamiseichenauer** [comment]
You can also help your Cylance admin by running pwd and provide them with the full path e.g. 
/usr/local/bin/terraform/terraform
/usr/local/Cellar/terraform/0.9.1_1/bin/terraform
etc.
