### ISSUE TITLE
detach aws vpn gateway from vpc

### ISSUE THREAD

**Issue by himanshubshah** [hashicorp/terraform#12473]
Hi, 

as per [documentation](https://www.terraform.io/docs/providers/aws/r/vpn_gateway_attachment.html) resource (aws_vpn_gateway_attachment) can be used to detach vpc from gateway. 

> Provides a Virtual Private Gateway attachment resource, allowing for an existing hardware VPN gateway to be attached and/or **_detached_** from a VPC.

I tried below with no luck. Can someone give me working sample to detach VPC from gateway? 

`resource "aws_vpn_gateway_attachment" "vpc_detach" {
  vpc_id         = ""
  vpn_gateway_id = "vgw-yyyyy"
}`

**Comment by stack72** [comment]
Hi @himanshubshah 

Thanks for opening the issue here - if the vpn gateway wasn't attached to the vpc_id using the `aws_vpn_gateway_attachment` then you cannot explicitly detach it. 

The usual way to attach would be as follows:

```
resource "aws_vpc" "network" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_vpn_gateway" "vpn" {
  tags {
    Name = "example-vpn-gateway"
  }
}

resource "aws_vpn_gateway_attachment" "vpn_attachment" {
  vpc_id = "${aws_vpc.network.id}"
  vpn_gateway_id = "${aws_vpn_gateway.vpn.id}"
}
``` 

To then detach, you would remove the following block from your terraform config:

```
resource "aws_vpn_gateway_attachment" "vpn_attachment" {
  vpc_id = "${aws_vpc.network.id}"
  vpn_gateway_id = "${aws_vpn_gateway.vpn.id}"
}
```

That would then cause Terraform to delete the attachment as it will no longer be managed

Hopefully this helps?

Paul

**Comment by himanshubshah** [comment]
Hi @stack72 

Thank you for responding. That makes sense, if attachment was created with terraform script. 
However, does terraform support or has any future plan to support [detach-vpn=gateway](http://docs.aws.amazon.com/cli/latest/reference/ec2/detach-vpn-gateway.html) aws cli command?

**Comment by stack72** [comment]
Hi @himanshubshah 

The detachment is baked into the `aws_vpn_gateway_attachment` - so the delete actually called that detach-vpn method

If you mean will terraform support a detach specific resource, then i have to say I am not sure. Please feel free to open a PR with it and we can review it - i don't think it's in our current plans

Paul
