### ISSUE TITLE
Modules and variables not working

### ISSUE THREAD

**Issue by draganavr** [hashicorp/terraform#12479]
Hi there, 
in advance any help would be appreciated.

##The problem is mixing modules and variables.

I have the following directory/files stucture:

```bash

.
├── main.tf
├── modules
│   └── resource_group
│       ├── main.tf
│       └── vars.tf
├── terraform.tfvars
└── vars.tf

```

## Configuration files

**./main.tf**
```bash

provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}
module "rsg" {
  source = "./modules/resource_group"
  name = "${var.env}"
  location = "${var.location}"
}

```

**./vars.tf**

```bash

variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}

variable "env" {}
variable "location" {}

```

**./terraform.tfvars**

```bash

env = "development"
location = "East US"

```
**./modules/resource_group/main.tf**

```bash

resource "azurerm_resource_group" "test" {
  name     = "${var.env}"
  location = "${var.location}"

  tags {
    environment = "${var.env}"
  }
}

```

**./modules/resource_group/vars.tf**

```bash

variable "env" {}
variable "location" {}


```

### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- azurerm_resource_group

Might be for other related too

### Debug Output

Error loading Terraform: module root: module rsg: name is not a valid parameter

Error loading Terraform: module root: module rsg: required variable env not set

### Expected Behavior
Launch an resource group in Azure.

### Actual Behavior
Does not read variables from terraform.tfvars file.
When I assign them to the resource parameters staticaly it works.
Also I would like to add complain about "module root: module rsg: name is not a valid parameter", why is not recognised as parameter.

### Steps to Reproduce

1. terraform get -update
Get: file:///./modules/resource_group (update)
Error loading Terraform: module root: module rsg: name is not a valid parameter

Then I added 'variable "name" {}' to ./modules/resource_group/vars.tf as recommended on some of the issues that I searched. 

2. terraform get -update
Get: file:///./modules/resource_group (update)
Error loading Terraform: module root: module rsg: required variable env not set

### Important Factoids
Azure Resource Manager

### References

**Comment by draganavr** [comment]
## Update
### Terraform Version
I've tried older versions of terraform and its the same.

**Comment by draganavr** [comment]
## Reproduce
Apologies for the long post.

### Single file no modules (WORKING)

Structure:
```bash
├── main.tf
├── terraform.tfvars
└── vars.tf
```

**./main.tf**
```bash
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}
resource "azurerm_resource_group" "testit" {
  name = "${var.env}"
  location = "${var.location}"
  tags {
    organization = "${var.org}"
    environmet = "${var.env}"
  }
}
```

**./vars.tf**
```basg
variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}

variable "env" {}
variable "org" {}
variable "location" {}
```
**./terraform.tf.var**
```bash
env = "development"
org = "tftests"
location = "Central US"
```

**terraform plan**
```bash
...
+ azurerm_resource_group.testit
    location:          "centralus"
    name:              "development"
    tags.%:            "2"
    tags.environmet:   "development"
    tags.organization: "tstests"
Plan: 1 to add, 0 to change, 0 to destroy.
```

### Set up a Module
```bash
├── main.tf
├── modules
│   └── resource_group
│       ├── main.tf
│       └── vars.tf
├── terraform.tfvars
└── vars.tf
```


**./main.tf**
```bash
module "test123" {
  name = "${var.env}"
  location = "${var.location}"
  tags {
    organization = "${var.org}"
    environmet = "${var.env}"
  }
}
```
**./vars.tf**
remains same

**./terraform.tfvars
remains same

**./modules/resource_group/main.tf**
```bash
resource "azurerm_resource_group" "testit" {
  name = "${var.env}"
  location = "${var.location}"
  tags {
    organization = "${var.org}"
    environmet = "${var.env}"
  }
}
```

**./modules/resource_group/vars.tf**
```bash
variable "env" {}
variable "org" {}
variable "location" {}
```

**terraform get**
Get: file:///terraform1/modules/resource_group
Error loading Terraform: module root: module test: **name** is not a valid parameter

Add 'variable "name" {}' in ./modules/resource_group/vars.tf and then run

**terraform get**
Get: file:///terraform1/modules/resource_group
Error loading Terraform: module root: module test: **tags** is not a valid parameter

Add 'variable "tags" {}' in ./modules/resource_group/vars.tf and then run

**terraform get**
Get: file:///terraform1/modules/resource_group
Error loading Terraform: module root: module test: required variable **org** not set

### Working Example
I was struggling and end up butchered version of it. Had to remove tags parameter and env and org variables.

```bash
./main.tf
module "test" {
  source = "./modules/resource_group/"
  name = "${var.name}"
  location = "${var.location}"
}

./vars.tf
variable "location" {}
variable "name" {}

./terraform.tfvars
name = "tfTST"
location = "Central US"

./modules/resource_group/main.tf
resource "azurerm_resource_group" "testit" {
  name = "${var.name}"
  location = "${var.location}"
}

./modules/resource_group/vars.tf
variable "location" {}
variable "name" {}

terraform get -update
Get: file:///terraform1/modules/resource_group (update)

terraform plan
...
 module.test.azurerm_resource_group.testit
    location: "centralus"
    name:     "tfTST"
    tags.%:   "<computed>"
Plan: 1 to add, 0 to change, 0 to destroy.

```

**Comment by jbardin** [comment]
Hi @draganavr,

It looks like you're not declaring all the variable you need for inputs to your modules, or you're not matching the correct variable names. 

In your first example you have a variable named `env` in the module, but you are attempting to assign the variable `name` from the root module. 

In you second example, you've are also trying to assign a `tags` variable, but there is no `tags` variable declared. There is a `tags` field in the `azurerm_resource_group`, but that isn't a module input.

When using modules, remember that variable are the "inputs" to the module, and the only way to pass in information.

**Comment by vammy55** [comment]
> Hi there,
> in advance any help would be appreciated.
> 
> ##The problem is mixing modules and variables.
> 
> I have the following directory/files stucture:
> 
> ```shell
> .
> ├── main.tf
> ├── modules
> │   └── resource_group
> │       ├── main.tf
> │       └── vars.tf
> ├── terraform.tfvars
> └── vars.tf
> ```
> 
> ## Configuration files
> **./main.tf**
> 
> ```shell
> provider "azurerm" {
>   subscription_id = "${var.subscription_id}"
>   client_id       = "${var.client_id}"
>   client_secret   = "${var.client_secret}"
>   tenant_id       = "${var.tenant_id}"
> }
> module "rsg" {
>   source = "./modules/resource_group"
>   name = "${var.env}"
>   location = "${var.location}"
> }
> ```
> 
> **./vars.tf**
> 
> ```shell
> variable "subscription_id" {}
> variable "client_id" {}
> variable "client_secret" {}
> variable "tenant_id" {}
> 
> variable "env" {}
> variable "location" {}
> ```
> 
> **./terraform.tfvars**
> 
> ```shell
> env = "development"
> location = "East US"
> ```
> 
> **./modules/resource_group/main.tf**
> 
> ```shell
> resource "azurerm_resource_group" "test" {
>   name     = "${var.env}"
>   location = "${var.location}"
> 
>   tags {
>     environment = "${var.env}"
>   }
> }
> ```
> 
> **./modules/resource_group/vars.tf**
> 
> ```shell
> variable "env" {}
> variable "location" {}
> ```
> 
> ### Terraform Version
> Terraform v0.8.8
> 
> ### Affected Resource(s)
> * azurerm_resource_group
> 
> Might be for other related too
> 
> ### Debug Output
> Error loading Terraform: module root: module rsg: name is not a valid parameter
> 
> Error loading Terraform: module root: module rsg: required variable env not set
> 
> ### Expected Behavior
> Launch an resource group in Azure.
> 
> ### Actual Behavior
> Does not read variables from terraform.tfvars file.
> When I assign them to the resource parameters staticaly it works.
> Also I would like to add complain about "module root: module rsg: name is not a valid parameter", why is not recognised as parameter.
> 
> ### Steps to Reproduce
> 1. terraform get -update
>    Get: file:///./modules/resource_group (update)
>    Error loading Terraform: module root: module rsg: name is not a valid parameter
> 
> Then I added 'variable "name" {}' to ./modules/resource_group/vars.tf as recommended on some of the issues that I searched.
> 
> 1. terraform get -update
>    Get: file:///./modules/resource_group (update)
>    Error loading Terraform: module root: module rsg: required variable env not set
> 
> ### Important Factoids
> Azure Resource Manager
> 
> ### References

Hi

I am having a similar issue mentioned above.Is there any solution?
