### ISSUE TITLE
VPC Databases

### ISSUE THREAD

**Issue by jwaldrip** [hashicorp/terraform#1248]
I am trying to provision my AWS with a VPC and I get an error that I cannot associate a non-vpc database to a vpc. How do I associate my database with the vpc?

* Error creating DB Instance: InvalidParameterCombination: VPC Security Groups cannot be associated with non-VPC DB Instances.

```
resource "aws_db_instance" "default" {
    identifier = "brandfolder-rds"
    allocated_storage = 10
    iops = 1500
    engine = "postgres"
    engine_version = "9.4.1"
    instance_class = "db.r3.xlarge"
    port = 5432
    username = "..."
    password = "..."
    backup_window = "05:00-8:30"
    maintenance_window = "Sat:09:30-Sat:22:00"
    vpc_security_group_ids = ["${aws_security_group.brandfolder-rds.id}"]
    final_snapshot_identifier = "brandfolder-rds.db.snapshot"
    backup_retention_period = 30
    multi_az = true
}

```

**Comment by catsby** [comment]
Hey @jwaldrip – looks like you need a `db_subnet_group`:

- http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

> **DBSubnetGroupName**
> A DB subnet group to associate with this DB instance.
> If there is no DB subnet group, then it is a non-VPC DB instance.

You can set one up with Terraform: 

- https://terraform.io/docs/providers/aws/r/db_subnet_group.html

**Comment by jwaldrip** [comment]
Worked, thank you

**Comment by saulshanabrook** [comment]
Is it possible to create a VPC database in only one AZ?

**Comment by saulshanabrook** [comment]
[The answer is no](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.html#Overview.RDSVPC.Create).

> Your VPC must have at least one subnet in at least two of the Availability Zones in the region where you want to deploy your DB instance. A subnet is a segment of a VPC's IP address range that you can specify and that lets you group instances based on your security and operational needs.
