### ISSUE TITLE
provider/ns1/record Requires multiple answers arguments instead of a list of answers

### ISSUE THREAD

**Issue by jmeunier28** [hashicorp/terraform#12485]
### Terraform Version
`Terraform v0.8.8`

### Affected Resource(s)
- ns1_record

### Terraform Configuration Files
```hcl
provider "ns1" {
  apikey = "${var.ns1_apikey}"
}

resource "ns1_record" "www" {
  zone              = "${var.ns1_zone}"
  domain            = "www.${var.ns1_zone}"
  type              = "A"
  ttl               = 60
  use_client_subnet = "false"

  answers = {
    answer = ["192.168.0.1", "192.168.0.2"]
  }

}
```

### Debug Output
`https://gist.github.com/jmeunier28/e73a9a2381cf83b1c4e8fa322aa00d9d`

### Expected Behavior
Expected that a record could be created with multiple answers

### Actual Behavior
```Errors: 

* ns1_record.www: answers.0.answer must be a single value, not a list

```

##### Code that actually produces the expected result:

```
resource "ns1_record" "www" {
  zone              = "${var.ns1_zone}"
  domain            = "www.${var.ns1_zone}"
  type              = "A"
  ttl               = 60
  use_client_subnet = "false"

  answers = {
    answer = "192.168.0.1"
  }

   answers = {
     answer = "192.168.0.2"
   }
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by stack72** [comment]
Closed via #13786

**Comment by mccartney** [comment]
So what's the actual answer? I fail to see the suggestion for better syntax in #13786 over the multiple `answers={ answer = "" }` nodes.

**Comment by mccartney** [comment]
Related https://github.com/terraform-providers/terraform-provider-ns1/issues/52
