### ISSUE TITLE
forces new resource when count.index part of variable would not have changed

### ISSUE THREAD

**Issue by NetworkDan** [hashicorp/terraform#12499]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.8.7

### Affected Resource(s)
Please list the resources as a list, for example:
-  aws_route_table_association

Seems to effect any resource that looks for * variable that has been appended to, so the original count.index's are unchanged and only more are added. making the variable longer.

### Terraform Configuration Files
```hcl
resource "aws_route_table_association" "internal_rta" {
  count          = "${var.vpc_number_of_azs}"
  subnet_id      = "${element(aws_subnet.internal_subnet.*.id, count.index)}"
  route_table_id = "${element(aws_route_table.internal_rt.*.id, count.index)}"
}
```

### Debug Output
Debug Not supplied - This is not preventing Terraform working, but it is destroying resources for no reason

Plan output:
```hcl
-/+ aws_route_table_association.internal_rta.0
    route_table_id: "rtb-19b0127e" => "${element(aws_route_table.internal_rt.*.id, count.index)}"
    subnet_id:      "subnet-4db4a33b" => "${element(aws_subnet.internal_subnet.*.id, count.index)}" (forces new resource)

-/+ aws_route_table_association.internal_rta.1
    route_table_id: "rtb-1ab0127d" => "${element(aws_route_table.internal_rt.*.id, count.index)}"
    subnet_id:      "subnet-28471570" => "${element(aws_subnet.internal_subnet.*.id, count.index)}" (forces new resource)

+ aws_route_table_association.internal_rta.2
    route_table_id: "${element(aws_route_table.internal_rt.*.id, count.index)}"
    subnet_id:      "${element(aws_subnet.internal_subnet.*.id, count.index)}"
```

subnet-4db4a33b & subnet-28471570 are not changed and are still count.index 0 & 1 within "aws_subnet.internal_subnet.*.id"

I have created infrastructure over 2 availability zones, and now trying to plan/apply again but spreading over 3 availability zones, I would expect Terraform for build the new resources without effecting the already build infrastructure in the existing AZs. Looks like it believes the existing subnet IDs have changed as its not resolving "aws_subnet.internal_subnet.*.id" into its count items. 

The first two count items in "aws_subnet.internal_subnet.*.id" are unchanged but terraform sees the whole variable changed as a third count has been added.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Built VPC with subnet and route-table across 2 AZs
2. The amend Terraform to build over 3 AZs and plan

### Important Factoids
none

### References
none

**Comment by mitchellh** [comment]
This is related to #3449. And I actually think there is another issue floating around that talks about knowing count.index at plan time when it uses a variable... Will close for 3449 though.
