### ISSUE TITLE
aws_cloudwatch_log_metric_filter: add metric_transformation attributes

### ISSUE THREAD

**Issue by ivanlei** [hashicorp/terraform#12493]
to create an `aws_cloudwatch_metric_alarm`, a `metric_name` and `namespace` are necessary. 

these are unexposed attributes in the `metric_transformation` block of an `aws_cloudwatch_log_metric_filter`.

this is fairly confusing because using `aws_cloudwatch_log_metric_filter.id` as `aws_cloudwatch_metric_alarm.metric_name` creates an alarm, but that alarm never fires.

```hcl
resource "aws_cloudwatch_log_metric_filter" "fungo" {
  name = "this_filter_name_is_not_useful"

  metric_transformation {
    name = "this_name_is_needed_to_create_an_alaram"
    namespace = "this_namespace_is_needed_to_create_an_alarm"
  }
}

resource "aws_cloudwatch_metric_alarm" "mungo" {
    alarm_name = "be_careful_setting_metric_name"
    
    # using the id of the aws_cloudwatch_log_metric_filter as metric_name
    # will cause alarm to never fire
    # metric_name = "${aws_cloudwatch_log_metric_filter.fungo.id}" #wrong

    # must use the name of the aws_cloudwatch_log_metric_filter.metric_transformation
    metric_name = "this_name_is_needed_to_create_an_alaram" #right

    # while not confusing, it would be nice if this were an attribute of
    # aws_cloudwatch_log_metric_filter to reduce chance of typo/mistake
    namespace = "this_namespace_is_needed_to_create_an_alarm"
}
```

**Comment by stack72** [comment]
Hi @ivanlei 

Can you describe the behaviour you believe should happen here? I am not quite able to get the context from the issue above

Hopefully you can help

Thanks

Paul

**Comment by stack72** [comment]
ok I think I see, you want to expose the `name` and `namespace` from the metric_transformation block so that it can be used in `aws_cloudwatch_log_metric_filter`?

**Comment by ivanlei** [comment]
@stack72 yes that is what i want
