### ISSUE TITLE
intermittent "No valid credential sources found for AWS Provider" error

### ISSUE THREAD

**Issue by FlorinAndrei** [hashicorp/terraform#12508]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
everything

### Terraform Configuration Files
I'll provide these if necessary.

### Actual Behavior
https://gist.github.com/FlorinAndrei/aa4cb6a677da1f8b0ffa92b10e5d06c8

### Important Factoids
Happens intermittently. The number of errors occurred varies from one run to the next. Typically about half a dozen. Once in a blue moon there are no errors and the plan command actually works.

**Comment by FlorinAndrei** [comment]
The only change I could think of was:

I have a module called `static_cluster` where I've used `aws_instance` without defining any block devices - just relying on defaults. Now I've added `root_block_device` but for now the settings in there are also the defaults, so no change should happen. I've tested it on another environment, and indeed no changes were predicted by `terraform plan`.

But now going back to the env I'm working on, I get this fluctuating error all the time.

Not sure if this is indeed the cause. Perhaps it's unrelated.

**Comment by FlorinAndrei** [comment]
`terraform plan -destroy` works just fine on same environment.

**Comment by FlorinAndrei** [comment]
The error disappears if I add the `-parallelism=4` option to `terraform plan`. Looks like there's some kind of rate limiting or parallelism limits now in place at AWS.

**Comment by mitchellh** [comment]
Potentially being rate limited on the auth itself? I'm not really sure here if you could provide [minimal] configs to reproduce this it'd be helpful to run it ourselves and see.

**Comment by FlorinAndrei** [comment]
Here is the TF env with the modules:

[no_valid_credential_sources.tar.gz](https://github.com/hashicorp/terraform/files/832099/no_valid_credential_sources.tar.gz)

The sensitive info has been redacted.

**Comment by FlorinAndrei** [comment]
Things I should probably mention:
- all my AWS creds are in `~/.aws/*` and are the same ones used by the AWS CLI, by Boto, etc
- the AWS creds only have the default profile, pointing at `us-west-2`
- I'm testing with an AWS IAM account that has the `AdministratorAccess` policy, so as to remove any doubt that this is a policy issue

**Comment by karlgoldstein** [comment]
I am running into the same intermittent error with 0.9.1.  Also disappears if I use `-parallelism=4` option.

**Comment by jszwedko** [comment]
👍 we've been fighting this for a while. https://github.com/hashicorp/terraform/issues/6222 is related

**Comment by jszwedko** [comment]
Actually, may be different if static credentials are being used here. We rely on the EC2 metadata endpoint to supply the credentials.

**Comment by FlorinAndrei** [comment]
I haven't seen this issue much recently, but it was intermittent to begin with.

**Comment by m00ki3** [comment]
I see it everytime I try to add a "aws_route53_record" resource...it's maddening.
If I remove the "aws_route53_record" resource, the plan runs, if I add it back in, I get the "No valid credential sources found for AWS Provider" error. 
My profile has AdministratorAccess as well, so nothing hinky there.

**Comment by kkarimi** [comment]
Had this issue today when there was spelling mistakes in the AWS credential file, fixing that made the error go away. The error message confused me so that might need to be more specific.

**Comment by apparentlymart** [comment]
This issue has been migrated to terraform-providers/terraform-provider-aws#590 as part of separating the providers into their own repositories. Please post any further comments over there! Thanks.
