### ISSUE TITLE
Variable Interpolation for a Map or List

### ISSUE THREAD

**Issue by ptarpan** [hashicorp/terraform#12502]
Hi Terraform Support,

I have read several articles on this but do not have a solution yet. My question is: how can I extract the value of a particular element from a list or a map?  See the below Terraform config for a use case. FYI, I have tried changing the variable type to `map` but still receive an error. Because the `route_table_id` must be a single value, what is the best way to define the `rtb-ids` variable and extract a single value as required?   

### Terraform Version
v0.8.7 

### Affected Resource(s)
- aws_route

### Terraform Configuration
```hcl
variable "rtb-ids" {
    description = "Route Table IDs."
    type        = "list"
    default     = {
        private = ["rtb-id1","rtb-id2","rtb-id3"]
        public  = ["rtb-id4","rtb-id5","rtb-id6"]
    }
}

resource "aws_route" "r" {
    route_table_id            = "${element(var.rtb-id, 0)}"
    destination_cidr_block    = "1.1.1.0/24"
    vpc_peering_connection_id = "${aws_vpc_peering_connection.pc.id}"
}
```

### Debug Output
'rtb-ids' has a default value which is not of type 'list' (got 'map').

### Expected Behavior
Terraform should get pick and return the first element "rtb-id1" from the first key "private". 

### Actual Behavior
Terraform throws a syntax error. 

### Steps to Reproduce
1. Create a VPC peering connection in AWS. 

2. Run `terraform apply` using the config above.

**Comment by ptarpan** [comment]
I managed to do the following but don't believe this is ideal because I'm planning on modularizing this variable and there will be many more routing tables of type `private` and `public` in several other AWS accounts. 

```
variable "priv-rtb-ids" {
    description = "Private Route Table IDs."
    type        = "list"
    default     = ["rtb-id1","rtb-id2","rtb-id3"]
}

resource "aws_route" "r" {
    route_table_id            = "${element(var.priv-rtb-id, 0)}"
    destination_cidr_block    = "1.1.1.0/24"
    vpc_peering_connection_id = "${aws_vpc_peering_connection.pc.id}"
}

``` 

### Debug Output 
```
aws_route.r
    destination_cidr_block:     "1.1.1.0/24"
    destination_prefix_list_id: "<computed>"
    gateway_id:                 "<computed>"
    instance_id:                "<computed>"
    instance_owner_id:          "<computed>"
    nat_gateway_id:             "<computed>"
    network_interface_id:       "<computed>"
    origin:                     "<computed>"
    route_table_id:             "rtb-id1"
    state:                      "<computed>"
    vpc_peering_connection_id:  "pcx-id12345"
```

**Comment by richerve** [comment]
@ptarpan Terraform is informing you of the error:
`'rtb-ids' has a default value which is not of type 'list' (got 'map').`

In your original variable declaration type must be "map" and not "list" and then you can do something like: `"${var.rtb-ids["private"]}` to obtain the list from the "private" key on the map

**Comment by mitchellh** [comment]
Thanks @richerve
