### ISSUE TITLE
provider/fastly Update docs on website for response object

### ISSUE THREAD

**Issue by travertischio** [hashicorp/terraform#12500]
In #12032 support for the fastly `response_object` was added. This was part of the release for [v0.8.8](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#088-march-2-2017).
I can confirm that the response object is recognized in v`0.8.8`, however, the PR linked above included documentation for the website that has not been published.

**Comment by stack72** [comment]
Hi @travertischio 

This is now on the [site](https://www.terraform.io/docs/providers/fastly/r/service_v1.html#response_object)

Thanks

Paul
