### ISSUE TITLE
provider/google/storage: support for bucket CORS policy

### ISSUE THREAD

**Issue by renchap** [hashicorp/terraform#12519]
There is currently no way to set a Google Cloud Storage CORS policy on a bucket.

It is set using the `cors[]` attribute on a Bucket object: https://cloud.google.com/storage/docs/json_api/v1/buckets

Implementation could be similar to the AWS S3 Bucket resource:

```hcl
resource "google_storage_bucket" "image-store" {
  name     = "image-store-bucket"
  location = "EU"
  cors_rule {
        response_headers = ["*"]
        allowed_methods = ["PUT","POST"]
        allower_origins = ["https://gcs-website-test.hashicorp.com"]
        response_headers = ["ETag"]
        max_age_seconds = 3000
  }
}
```

**Comment by AVVS** [comment]
It has a tad different params:

```
    "origin": Array<string>,
    "responseHeader": Array<string>,
    "method": Array<string>,
    "maxAgeSeconds": int64
```

However, this would be superb to have, too, otherwise its manual labour :(

**Comment by kolpav** [comment]
Just starting with terraform and first thing I tried to do is not supported :smile: would be really nice to have it. Please consider adding it.
For anyone searching for temp. solution you can do
```json
// cors-json-file.json
[
    {
      "origin": ["*"],
      "responseHeader": ["Content-Type"],
      "method": ["GET", "HEAD"],
      "maxAgeSeconds": 3600
    }
]
```
```
gsutil cors set cors-json-file.json gs://<your-bucket-name>
gsutil cors get gs://<your-bucket-name>
```

**Comment by danawillow** [comment]
Fixed in https://github.com/hashicorp/terraform/pull/14695
