### ISSUE TITLE
aws_s3_bucket region ignored, provider region takes precedence

### ISSUE THREAD

**Issue by mzraly** [hashicorp/terraform#12512]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- aws_s3_bucket

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_s3_bucket" "res_s3_bucket" {
  bucket = "tf-bucket-region-issue"
  region = "us-east-1"
}
```

### Debug Output
https://gist.github.com/mzraly/6c4cbdd2f8016c0526bd3b18b7a43a01

### Panic Output
None

### Expected Behavior
Documentation at https://www.terraform.io/docs/providers/aws/r/s3_bucket.html suggests that by specifying the region in an aws_s3_bucket resource that bucket will be created in that region.  In the example above, we expected the bucket to be created in us-east-1.

### Actual Behavior
The bucket is created in the region specified by the provider, us-west-2.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
None

### References
None I am aware of.

**Comment by Ninir** [comment]
Hi @mzraly 

`us-east-1` is - historically - a special region. 

To create a bucket in the `us-east-1` region, you need to specify the provider explicitly omitting the region, as in:

```tf
provider "aws" {
	region = "us-west-2"
}

provider "aws" {
	alias  = "useast"
	region = "us-east-1"
}

resource "aws_s3_bucket" "bucket" {
	provider = "aws.useast" # Set this and remove the region argument
	bucket   = "my-bucket"
}
```

The issue is that you can't set the region when the target is us-east-1, since it is an exception on the AWS side (Error returned is: `InvalidLocationConstraint: The specified location-constraint is not valid`).

Does it help?

**Comment by mzraly** [comment]
Hi @Ninir,

Thanks for explaining the reason behind the failure.  Up to you guys how much you want to expose or mask underlying provider inconsistencies, but if you don't mask them then please document them.

**Comment by facundovictor** [comment]
@mzraly Note: for importing buckets from different regions you may also need to pass provider in the import argument to match the bucket provider (Ex: `-provider=aws.useast`).

See: https://github.com/hashicorp/terraform/issues/13750#issuecomment-295281815

**Comment by davidjeddy** [comment]
Want to note that is your `apply` a second time, the `us-east-1` region value IS applied. Even without a custom provider.
