### ISSUE TITLE
aws_s3_bucket_policy marked as modified on every apply regardless of changes

### ISSUE THREAD

**Issue by kerin** [hashicorp/terraform#12524]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- aws_s3_bucket_policy

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket_policy" "source" {
    bucket = "${aws_s3_bucket.source.id}"
    policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "DenyIncorrectEncryptionHeaderInSource",
      "Effect": "Deny",
      "Action": "s3:PutObject",
      "Resource": "${aws_s3_bucket.source.arn}/*",
      "Principal": "*",
      "Condition": {
        "StringNotEquals": {
          "s3:x-amz-server-side-encryption": "AES256"
        }
      }
    },
    {
      "Sid": "DenyUnEncryptedObjectUploadsInSource",
      "Effect": "Deny",
      "Action": "s3:PutObject",
      "Resource": "${aws_s3_bucket.source.arn}/*",
      "Principal": "*",
      "Condition": {
        "Null": {
          "s3:x-amz-server-side-encryption": true
        }
      }
    }
  ]
}
EOF
}
```

### Debug Output
https://gist.github.com/kerin/c27c23765dc0366147961b49059788c3

### Expected Behavior
Terraform should not see modifications to unchanged resources.

### Actual Behavior
Terraform thinks there's a modification to be applied on each `plan` or `apply`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. Observe planned changes to bucket policy
3. `terraform apply`
4. `terraform plan`
5. Observe that Terraform plans to apply the same modification again.

### Important Factoids
None of these attempts to work around the issue have had any effect:
- Removing all linebreaks and spaces from the policy document
- Using a separate JSON document via `$file()`
- Replacing references to resource ARNs with static values

**Comment by bdashrad** [comment]
Try defining the policy with `aws_iam_policy_document`. I've found this is usually the result of formatting.

**Comment by kevinburke** [comment]
> Try defining the policy with aws_iam_policy_document. I've found this is usually the result of formatting.

Can you explain further? If so it seems like we should open a separate issue for that; a policy that is consistently generating a different file in AWS than the one specified.

**Comment by bdashrad** [comment]
If you are parsing in json as a policy, terraform is not formatting it. When you run a plan, terraform takes the policy from the AWS api and compares it to what you have. AWS sometimes formats the JSON, so if the policy you are creating has different formatting, terraform will show that it needs to be changed. If you use the [aws_iam_policy_document data source](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html), it renders the JSON in the same format as AWS, and you're less likely to see errors.

**Comment by ju2wheels** [comment]
@bdashrad That wont help here. In my case, my policy uses principals and you cannot create an actual aws_iam_policy_document using the policy and using aws_iam_policy_document data source results in the same issue @kerin reported.
