### ISSUE TITLE
EBS Optimization for Master and Core Instance Groups

### ISSUE THREAD

**Issue by anthcor** [hashicorp/terraform#12534]
Hi there,

It would be great for a developer to say `master_ebs_optimized = true` or something of that sort when creating EMR Clusters for large jobs which require you to optimize your master and core instance groups, while necessarily creating another instance group for a task(s). Refer #11411.

### Terraform Version
```sh
> terraform -v
Terraform v0.8.8
```

### Affected Resource(s)
- [aws_emr_cluster](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_emr_cluster.go)
  - [aws_sdk_go/emr](https://github.com/aws/aws-sdk-go/tree/master/service/emr)

### Terraform Configuration Files
```hcl
resource "aws_emr_cluster" "my-test-cluster" {
  name          = "my-test-cluster"
  release_label = "emr-5.3.1"
  applications  = ["Hadoop", "HBase"]

  termination_protection = false
  keep_job_flow_alive_when_no_steps = true

  ec2_attributes {
    subnet_id                         = "subnet-88888888"
    emr_managed_master_security_group = "sg-88888888"
    emr_managed_slave_security_group  = "sg-88888888"
    instance_profile                  = "arn:aws:iam::<your-id>:instance-profile/EMR_EC2_DefaultRole"
    key_name                          = "key-name"
  }

  master_instance_type = "m4.large"
  master_ebs_optimized = true
  core_instance_type   = "m4.large"
  core_ebs_optimized = true
  core_instance_count  = 2

  service_role = "arn:aws:iam::<your-id>:role/EMR_DefaultRole"
}
```

**Comment by emalloy** [comment]
It would also be nice to have the option to specify the `root_block_device` and or `ebs_block_device` as part of `ec2_attributes` for the emr cluster itself. Currently there is no way to provision storage for the Master and Core Instance Groups. One can add a Task instance group but this storage, (by default) doesn't get used by hdfs.
