### ISSUE TITLE
resource data.aws_db_instance does not return address

### ISSUE THREAD

**Issue by dmatthis-sm** [hashicorp/terraform#12543]
This may be more of a feature request but currently data.aws_db_instance does not pull back the address for the RDS resource.

You can pull the information from aws cli
`aws rds describe-db-instances`
Wil show the endpoint with port and address. But currently the data resource in Terraform only returns a port option 

I would like to see something like "db_address" to complement "db_port"

example:
`
data "aws_db_instance" "mydb" {
  db_instance_identifier = "mydb"
}

return:
data.aws_db_instance.mydb.db_address
data.aws_db_instance.mydb.db_port
`

Note:
`resource "aws_db_instance" "mydb"` already returns "aws_db_instance.mydb.address" but this is not helpful if you don't manage the db instance with terraform.

**Comment by stack72** [comment]
Closed via #12623
