### ISSUE TITLE
AWS Customer Gateways.

### ISSUE THREAD

**Issue by magnusthorne** [hashicorp/terraform#12548]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.8.8

### Affected Resource(s)
aws_customer_gateway

### Terraform Configuration Files
```hcl
resource "aws_customer_gateway" "usw2-removed1" {
    bgp_asn = 65000
    ip_address = "1.1.1.1"
    type = "ipsec.1"
    tags {
        Name = "usw2-removed1"
    }
}

resource "aws_customer_gateway" "usw2-removed2" {
    bgp_asn = 65000
    ip_address = "1.1.1.1"
    type = "ipsec.1"
    tags {
        Name = "usw2-removed2"
    }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Give the error "Duplicate BGP ASN exists for the given IP in another customer gateway"

### Actual Behavior
It checked that the IP address existed and didn't check for a duplicate.  Now, I can't remove the second entry, because "IncorrectState: The customer gateway is in use. " which is correct.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
Build two identical customer gateways.  Delete the duplicate.

**Comment by stack72** [comment]
Hi @magnusthorne 

Thanks for the issue here - I am really glad to say that I *just* fixed this exact bug today :) 

https://github.com/hashicorp/terraform/pull/12501

Hope this is ok? It will be part of Terraform 0.8.9

Paul
