### ISSUE TITLE
Can't build current master - undefined sort.Slice

### ISSUE THREAD

**Issue by myoung34** [hashicorp/terraform#12556]
### Terraform Version
origin/master as of b0deb7736b6a0dd8cff45a3eb5a2ba1996894eff fails

### Affected Resource(s)
core

### Expected Behavior
`make dev` succeed

### Actual Behavior
`make dev` fails with

```
make dev
==> Checking that code complies with gofmt requirements...
go generate $(go list ./... | grep -v /terraform/vendor/)
2017/03/09 06:01:20 Generated command/internal_plugin_list.go
==> Removing old directory...
==> Building...
Number of parallel builds: 3

-->    darwin/amd64: github.com/hashicorp/terraform

1 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/hashicorp/terraform/terraform
terraform/context.go:670: undefined: sort.Slice


==> Results:
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `git co origin/master && git fetch && git reset --hard origin/master`
1. `make dev`

### References
- https://github.com/hashicorp/terraform/commit/3e0af2abbb

**Comment by Ninir** [comment]
@jbardin @mitchellh Do you think a fix could be landed to master for that? :/
thanks!

**Comment by mitchellh** [comment]
You need to be using Go 1.8. We only support the latest version of Go on master at any given time.

**Comment by Ninir** [comment]
Ok so I will update the README.md for that :) thanks!

**Comment by mitchellh** [comment]
Yes, thank you!
