### ISSUE TITLE
Add support for DynamoDB attribute type - Boolean

### ISSUE THREAD

**Issue by tarakan12** [hashicorp/terraform#12569]
Attribute type does not support boolean at the moment

### Affected Resource(s)
- aws_dynamodb_table

### References
- http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html

**Comment by Ninir** [comment]
Hi @tarakan12 

As far as I checked, you can only set `BOOL`, `SS`, `BS`, `L`, `M`, `NS`, `NULL` for attributes that are not related to primary / range keys. 
Missing attribute types can be set when putting an item to the DB, but not on the required schema. Also found this (https://forums.aws.amazon.com/thread.jspa?messageID=613970) which exposes the idea.

However, I do think this would have sense for a DynamoDB item data source for instance! :)
