### ISSUE TITLE
source_dest_check not applying properly

### ISSUE THREAD

**Issue by anveo** [hashicorp/terraform#1256]
I appear to be having this problem with `v0.3.7`. I have 3 instances total, two do not specify a `source_dest_check` and one I'm setting it as false. The `.tfstate` shows all instances are `false` (documentation says default is True) and AWS console shows all created as `True`.

This may be similar to #229.

**Comment by jaxxstorm** [comment]
@anveo, I had the same problem, this is fixed in latest built from git. Build from source if you need it to work.

**Comment by catsby** [comment]
Thanks for reporting @anveo , and thanks for checking @jaxxstorm :smile: 

I'm going to close this, let me know if you're still seeing it.
