### ISSUE TITLE
Not able to pass resource local vars to data/template 

### ISSUE THREAD

**Issue by Daviey** [hashicorp/terraform#12573]
I'd like to be able to pass local context values from a resource definition into a data/template for rendering.

The two specific examples are:

- implicit resource "name" already being available without redefining, such as:
  - var.name, in data/template
  - self.name, in the resource itself (such as adding a Name tag to the instance)
- local vars available to rendering, such as domain_name

I understand that data is already rendered before the aws_instance resource stanza is reached, so it isn't contextually possible at the moment.

This is similar to #2167, but I don't think it is reasonable to rely on 'count' and link to a map.  It seems cleaner to be able to define these values within the resource itself.

### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- aws_instance
- core
- data

### Terraform Configuration Files
I would expect to be able to do this  (comments added to help explain):
```hcl
data "template_file" "user_data" {
  template = <<EOF
#cloud-config
hostname: $var.name   // <----------- resource name provided by default
fqdn: "${format("%s.%s", var.name, var.domain_name)}"   // <---- both variables provided from context
EOF
}

data "template_cloudinit_config" "user_data" {
  gzip          = false
  base64_encode = false

  part {
    filename     = "user-data.txt"
    content_type = "text/cloud-config"
    content      = "${data.template_file.user_data.rendered}"
  }
}

resource "aws_instance" "patient-drum" {
  ami                         = "ami-XXXX"
  ...
  var.domain_name = "example.org"  // <-- redefine var.domain_name for this context 
  user_data = "${data.template_file.user_data.rendered}

  tags {
    "Name" = self.name // <---------------- resource name == "patient-drum" from above
  }
}
```

But instead I need to do it like this (repeating the values multiple times, and a hacky replace line:
```hcl
data "template_file" "user_data" {
  template = <<EOF
#cloud-config
hostname: #HOSTNAME
fqdn: #FQDN
EOF
}

data "template_cloudinit_config" "user_data" {
  gzip          = false
  base64_encode = false

  part {
    filename     = "user-data.txt"
    content_type = "text/cloud-config"
    content      = "${data.template_file.user_data.rendered}"
  }
}

resource "aws_instance" "patient-drum" {
  ami                         = "ami-XXXX"
  ...

  user_data = "${replace(replace(data.template_file.user_data.rendered, "#HOSTNAME", "patient-drum"), "#FQDN", "patient-drum.example.org")}"

  tags {
    "Name" = "patient-drum"
  }
}
```

### References
-  #2167 , very similar issue

**Comment by apparentlymart** [comment]
Hi @Daviey! Sorry for the long silence here.

As @aries-strato said, the `vars` map is the way to pass data into the template. Here is an equivalent of that example using the new Terraform 0.12 syntax conventions:

```hcl
data "template_file" "webserverdeploy" {
  template = file("${path.module}/webconfig.cfg")

  vars {
    db_ip       = aws_db_instance.database1.address
    db_user     = var.db_user
    db_password = var.db_password
  }
}
```

Terraform 0.12 also includes a new [`templatefile` function](https://www.terraform.io/docs/configuration/functions/templatefile.html) that incorporates the template rendering into the language itself, avoiding the need for the separate data source:

```hcl
data "template_cloudinit_config" "user_data" {
  gzip          = false
  base64_encode = false

  part {
    filename     = "user-data.txt"
    content_type = "text/cloud-config"
    content = templatefile("${path.module}/cloud_config.tmpl", {
      name        = var.name
      domain_name = var.domain_name
    })
  }
}
```

If you don't have your template in a separate file then you don't actually need either of these mechanisms: you can just inline the template directly in the configuration, because Terraform language strings support the template language natively:

```hcl
data "template_cloudinit_config" "user_data" {
  gzip          = false
  base64_encode = false

  part {
    filename     = "user-data.txt"
    content_type = "text/cloud-config"
    content      = <<-EOT
      #cloud-config
      hostname: ${jsonencode(var.name)}
      fqdn: ${jsonencode(format("%s.%s", var.name, var.domain_name))}
    EOT
  }
}
```

If you'd rather not have the template source inside the `data` block, you can factor it out into a [Local Value](https://www.terraform.io/docs/configuration/locals.html) instead.
