### ISSUE TITLE
Terraform failed to find out the duplicate Openstack security group rule when planning to add new rule

### ISSUE THREAD

**Issue by insidepacket** [hashicorp/terraform#12579]
Terraform version 0.8.7. We are using Openstack+NSXv plugin+VMware NSX 

[insidepacket@terraform1 SecurityGroupAdvance]$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.
 
openstack_networking_secgroup_v2.sg_db: Refreshing state... (ID: 505b6e3c-ed88-4747-a838-e413d0056777)
openstack_networking_secgroup_v2.sg_web: Refreshing state... (ID: 6c6a894c-ab2f-478a-a333-f538948128f6)
openstack_networking_secgroup_v2.sg_app: Refreshing state... (ID: b8839fe2-4599-48f6-b08b-14ab2507e669)
openstack_networking_secgroup_rule_v2.sg_db_rule_1: Refreshing state... (ID: ee6a5726-ad34-49d9-a0d2-642e46864818)
openstack_networking_secgroup_rule_v2.sg_app_rule_1: Refreshing state... (ID: e6e12394-fcf5-4991-8f8d-b160243e4ebf)
openstack_networking_secgroup_rule_v2.sg_web_rule_1: Refreshing state... (ID: cfed936f-cbb6-4865-bdde-dbc080628405)
openstack_networking_secgroup_rule_v2.sg_web_rule_2: Refreshing state... (ID: 8e1dcfb9-f2db-4ea1-98bf-a03be55eab02)
openstack_networking_secgroup_rule_v2.sg_app_rule_2: Refreshing state... (ID: 8d912d77-b4b4-475e-a858-dcd5209b0849)
openstack_networking_secgroup_rule_v2.sg_db_rule_2: Refreshing state... (ID: f2fafe73-0cee-4bcf-a114-80f599cd3fec)
openstack_networking_secgroup_rule_v2.sg_web_rule_3: Refreshing state... (ID: fb4f2240-cd93-4d1c-9565-c5b7cfc6e6d5)
openstack_networking_secgroup_rule_v2.sg_app_rule_3: Refreshing state... (ID: c400ad9d-d667-420b-9a98-03d3952facd5)
openstack_networking_secgroup_rule_v2.sg_web_rule_4: Refreshing state... (ID: deb39d06-251e-42cb-b345-c2c5d8d8c42a)
 
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.
 
Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.
 
+ openstack_networking_secgroup_rule_v2.sg_app_rule_4
    direction:         "ingress"
    ethertype:         "IPv4"
    port_range_max:    "22"
    port_range_min:    "22"
    protocol:          "tcp"
    remote_group_id:   "505b6e3c-ed88-4747-a838-e413d0056777"
    remote_ip_prefix:  "<computed>"
    security_group_id: "b8839fe2-4599-48f6-b08b-14ab2507e669"
    tenant_id:         "2b8d09cb778346a4ae70c16ee65a5c69"
 
 
Plan: 1 to add, 0 to change, 0 to destroy.
 
 
 
[insidepacket@terraform1 SecurityGroupAdvance]$ terraform apply
openstack_networking_secgroup_v2.sg_db: Refreshing state... (ID: 505b6e3c-ed88-4747-a838-e413d0056777)
openstack_networking_secgroup_v2.sg_app: Refreshing state... (ID: b8839fe2-4599-48f6-b08b-14ab2507e669)
openstack_networking_secgroup_v2.sg_web: Refreshing state... (ID: 6c6a894c-ab2f-478a-a333-f538948128f6)
openstack_networking_secgroup_rule_v2.sg_db_rule_1: Refreshing state... (ID: ee6a5726-ad34-49d9-a0d2-642e46864818)
openstack_networking_secgroup_rule_v2.sg_db_rule_2: Refreshing state... (ID: f2fafe73-0cee-4bcf-a114-80f599cd3fec)
openstack_networking_secgroup_rule_v2.sg_web_rule_1: Refreshing state... (ID: cfed936f-cbb6-4865-bdde-dbc080628405)
openstack_networking_secgroup_rule_v2.sg_app_rule_1: Refreshing state... (ID: e6e12394-fcf5-4991-8f8d-b160243e4ebf)
openstack_networking_secgroup_rule_v2.sg_app_rule_2: Refreshing state... (ID: 8d912d77-b4b4-475e-a858-dcd5209b0849)
openstack_networking_secgroup_rule_v2.sg_web_rule_2: Refreshing state... (ID: 8e1dcfb9-f2db-4ea1-98bf-a03be55eab02)
openstack_networking_secgroup_rule_v2.sg_app_rule_3: Refreshing state... (ID: c400ad9d-d667-420b-9a98-03d3952facd5)
openstack_networking_secgroup_rule_v2.sg_web_rule_3: Refreshing state... (ID: fb4f2240-cd93-4d1c-9565-c5b7cfc6e6d5)
openstack_networking_secgroup_rule_v2.sg_web_rule_4: Refreshing state... (ID: deb39d06-251e-42cb-b345-c2c5d8d8c42a)
openstack_networking_secgroup_rule_v2.sg_app_rule_4: Creating...
  direction:         "" => "ingress"
  ethertype:         "" => "IPv4"
  port_range_max:    "" => "22"
  port_range_min:    "" => "22"
  protocol:          "" => "tcp"
  remote_group_id:   "" => "505b6e3c-ed88-4747-a838-e413d0056777"
  remote_ip_prefix:  "" => "<computed>"
  security_group_id: "" => "b8839fe2-4599-48f6-b08b-14ab2507e669"
  tenant_id:         "" => "2b8d09cb778346a4ae70c16ee65a5c69"
Error applying plan:
 
1 error(s) occurred:
 
* **openstack_networking_secgroup_rule_v2.sg_app_rule_4: Expected HTTP response code [201 202] when accessing [POST http://token.ops.com.au:9696/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is c400ad9d-d667-420b-9a98-03d3952facd5.", "type": "SecurityGroupRuleExists", "detail": ""}}**
 
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure..

Maybe we need a new feature than a bug

**Comment by jtopjian** [comment]
@insidepacket Is this the same issue you are having that you reported here?

https://github.com/hashicorp/terraform/issues/7519#issuecomment-285250777

You mentioned that this is human error and that the existing security rule already exists. If so you need to import the existing rule using the `terraform import` command:

https://www.terraform.io/docs/import/index.html

You can see how to import security group rules at the bottom of the documentation here:

https://www.terraform.io/docs/providers/openstack/r/networking_secgroup_rule_v2.html

But if you don't believe this is human error, can you provide a little more information, such as the entire Terraform configuration you're using as well as the output of:

```shell
$ neutron security-group-rule-list b8839fe2-4599-48f6-b08b-14ab2507e669
```

Thanks,
Joe

**Comment by insidepacket** [comment]
Hi, sorry for the confusion. Let me explain in detail.

Our environment is VIO environment.

My user case is:

Step 1:  I created 3 security groups and firewall rules via Terraform using the template below:

provider "openstack" {
  user_name = "${var.openstack_user_name}"
  password = "${var.openstack_password}"
  tenant_name = "tenant1"
  auth_url = "http://keystone.opsx.com.au:5000/v3"
  domain_name = "domain1"
}

resource "openstack_networking_secgroup_v2" "sg_web" {
  name = "sg_web"
  description = "Terraform security web group"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
}

resource "openstack_networking_secgroup_v2" "sg_app" {
  name = "sg_app"
  description = "Terraform security app group"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
}

resource "openstack_networking_secgroup_v2" "sg_db" {
  name = "sg_db"
  description = "Terraform security db group"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
}

resource "openstack_networking_secgroup_rule_v2" "sg_web_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 80
  port_range_max = 80
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = ["openstack_networking_secgroup_v2.sg_web"]

}

resource "openstack_networking_secgroup_rule_v2" "sg_web_rule_2" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 443
  port_range_max = 443
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_web",
      "openstack_networking_secgroup_rule_v2.sg_web_rule_1"
  ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_web_rule_3" {
  direction = "egress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 443
  port_range_max = 443
  remote_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_web",
      "openstack_networking_secgroup_v2.sg_app",
      "openstack_networking_secgroup_rule_v2.sg_web_rule_2"
  ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_web_rule_4" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_ip_prefix = "8.8.8.8/32"
  security_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = ["openstack_networking_secgroup_rule_v2.sg_web_rule_3"]

}


resource "openstack_networking_secgroup_rule_v2" "sg_app_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 443
  port_range_max = 443
  remote_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_app",
      "openstack_networking_secgroup_v2.sg_web"
    ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_app_rule_2" {
  direction = "egress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 7443
  port_range_max = 7443
  remote_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_app",
      "openstack_networking_secgroup_v2.sg_db",
      "openstack_networking_secgroup_rule_v2.sg_app_rule_1"
    ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_app_rule_3" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_rule_v2.sg_app_rule_2"
    ]
}


resource "openstack_networking_secgroup_rule_v2" "sg_db_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 7443
  port_range_max = 7443
  remote_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_app"
  ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_db_rule_2" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_rule_v2.sg_db_rule_1"
  ]
}

All works well in Step 1.

Step 2: Add another rule sg_app_rule_4 in security group **sg_app**. The template is as below:

provider "openstack" {
  user_name = "${var.openstack_user_name}"
  password = "${var.openstack_password}"
  tenant_name = "tenant1"
  auth_url = "http://keystone.opsx.com.au:5000/v3"
  domain_name = "domain1"
}


resource "openstack_networking_secgroup_v2" "sg_web" {
  name = "sg_web"
  description = "Terraform security web group"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
}

resource "openstack_networking_secgroup_v2" "sg_app" {
  name = "sg_app"
  description = "Terraform security app group"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
}

resource "openstack_networking_secgroup_v2" "sg_db" {
  name = "sg_db"
  description = "Terraform security db group"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
}

resource "openstack_networking_secgroup_rule_v2" "sg_web_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 80
  port_range_max = 80
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = ["openstack_networking_secgroup_v2.sg_web"]

}

resource "openstack_networking_secgroup_rule_v2" "sg_web_rule_2" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 443
  port_range_max = 443
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_web",
      "openstack_networking_secgroup_rule_v2.sg_web_rule_1"
  ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_web_rule_3" {
  direction = "egress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 443
  port_range_max = 443
  remote_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_web",
      "openstack_networking_secgroup_v2.sg_app",
      "openstack_networking_secgroup_rule_v2.sg_web_rule_2"
  ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_web_rule_4" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_ip_prefix = "8.8.8.8/32"
  security_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = ["openstack_networking_secgroup_rule_v2.sg_web_rule_3"]

}


resource "openstack_networking_secgroup_rule_v2" "sg_app_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 443
  port_range_max = 443
  remote_group_id = "${openstack_networking_secgroup_v2.sg_web.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_app",
      "openstack_networking_secgroup_v2.sg_web"
    ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_app_rule_2" {
  direction = "egress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 7443
  port_range_max = 7443
  remote_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_app",
      "openstack_networking_secgroup_v2.sg_db",
      "openstack_networking_secgroup_rule_v2.sg_app_rule_1"
    ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_app_rule_3" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_rule_v2.sg_app_rule_2"
    ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_app_rule_4" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_rule_v2.sg_app_rule_3"
    ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_db_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 7443
  port_range_max = 7443
  remote_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_v2.sg_app"
  ]
}

resource "openstack_networking_secgroup_rule_v2" "sg_db_rule_2" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_group_id = "${openstack_networking_secgroup_v2.sg_app.id}"
  security_group_id = "${openstack_networking_secgroup_v2.sg_db.id}"
  tenant_id ="2b8d09cb778346a4ae70c16ee65a5c69"
  depends_on = [
      "openstack_networking_secgroup_rule_v2.sg_db_rule_1"
  ]
}

You can see that the newly added rule sg_app_rule_4 is to allow the same data flows as the existing rule sg_app_rule_3.

In Terraform planning, we can't see any issue:
_terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but
will not be persisted to local or remote state storage.
 
openstack_networking_secgroup_v2.sg_db: Refreshing state... (ID: 505b6e3c-ed88-4747-a838-e413d0056777)
openstack_networking_secgroup_v2.sg_web: Refreshing state... (ID: 6c6a894c-ab2f-478a-a333-f538948128f6)
openstack_networking_secgroup_v2.sg_app: Refreshing state... (ID: b8839fe2-4599-48f6-b08b-14ab2507e669)
openstack_networking_secgroup_rule_v2.sg_db_rule_1: Refreshing state... (ID: ee6a5726-ad34-49d9-a0d2-642e46864818)
openstack_networking_secgroup_rule_v2.sg_app_rule_1: Refreshing state... (ID: e6e12394-fcf5-4991-8f8d-b160243e4ebf)
openstack_networking_secgroup_rule_v2.sg_web_rule_1: Refreshing state... (ID: cfed936f-cbb6-4865-bdde-dbc080628405)
openstack_networking_secgroup_rule_v2.sg_web_rule_2: Refreshing state... (ID: 8e1dcfb9-f2db-4ea1-98bf-a03be55eab02)
openstack_networking_secgroup_rule_v2.sg_app_rule_2: Refreshing state... (ID: 8d912d77-b4b4-475e-a858-dcd5209b0849)
openstack_networking_secgroup_rule_v2.sg_db_rule_2: Refreshing state... (ID: f2fafe73-0cee-4bcf-a114-80f599cd3fec)
openstack_networking_secgroup_rule_v2.sg_web_rule_3: Refreshing state... (ID: fb4f2240-cd93-4d1c-9565-c5b7cfc6e6d5)
openstack_networking_secgroup_rule_v2.sg_app_rule_3: Refreshing state... (ID: c400ad9d-d667-420b-9a98-03d3952facd5)
openstack_networking_secgroup_rule_v2.sg_web_rule_4: Refreshing state... (ID: deb39d06-251e-42cb-b345-c2c5d8d8c42a)
 
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.
 
Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.
 
+ openstack_networking_secgroup_rule_v2.sg_app_rule_4
    direction:         "ingress"
    ethertype:         "IPv4"
    port_range_max:    "22"
    port_range_min:    "22"
    protocol:          "tcp"
    remote_group_id:   "505b6e3c-ed88-4747-a838-e413d0056777"
    remote_ip_prefix:  "<computed>"
    security_group_id: "b8839fe2-4599-48f6-b08b-14ab2507e669"
    tenant_id:         "2b8d09cb778346a4ae70c16ee65a5c69"
 
 
Plan: 1 to add, 0 to change, 0 to destroy._

However, when we apply the update, we see the error below:

**openstack_networking_secgroup_rule_v2.sg_app_rule_4: Expected HTTP response code [201 202] when accessing [POST http://token.opsx.com.au:9696/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is c400ad9d-d667-420b-9a98-03d3952facd5.", "type": "SecurityGroupRuleExists", "detail": ""}}**

The way how VIO works make the situation worse: when we have error like the above, all rules (in my case rule1, 2 and 3) of secuirty group "sg_app" are deleted from VMWare NSX although we still have the rules in Openstack. We have to delete the impacted security group from OpenStack and recreated  security group from scratch.

Yes. Adding duplicate rule is a human error. However, it often happens as we have big environment: over 2k security groups and  some security groups have a few of hundreds rules.

Can Terraform help to check if there is any duplicate rule or not when we perform Terraform planning so that we can avoid the security group restoration trouble?

**Comment by jtopjian** [comment]
Thank you for explaining this in detail! This really helps.

From what I can tell, this is a bug with VIO and not OpenStack/Neutron. Creating a security group rule with the same details of another rule but in a different group is possible in non-VIO OpenStack. 

Here's the test I ran to confirm this:

Step 1:

```hcl
resource "openstack_networking_secgroup_v2" "secgroup_1" {
  name = "secgroup_1"
  description = "My neutron security group"
}

resource "openstack_networking_secgroup_v2" "secgroup_2" {
  name = "secgroup_2"
  description = "My second neutron security group"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_1_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup_1.id}"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_1_rule_2" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 23
  port_range_max = 23
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup_1.id}"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_2_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 80
  port_range_max = 80
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup_2.id}"
}
```

Step 2:

```
resource "openstack_networking_secgroup_v2" "secgroup_1" {
  name = "secgroup_1"
  description = "My neutron security group"
}

resource "openstack_networking_secgroup_v2" "secgroup_2" {
  name = "secgroup_2"
  description = "My second neutron security group"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_1_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup_1.id}"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_1_rule_2" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 23
  port_range_max = 23
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup_1.id}"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_2_rule_1" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 80
  port_range_max = 80
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup_2.id}"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_2_rule_2" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "tcp"
  port_range_min = 22
  port_range_max = 22
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.secgroup_2.id}"
}
```

Everything worked as expected.

Unfortunately I don't have an immediate solution since I'm not familiar with VIO.

Maybe a good first step for you to further troubleshoot this is to reproduce this using either the `openstack` or `neutron` command line tools:

```shell
$ neutron security-group-create sg_web
$ neutron security-group-create sg_db
$ neutron security-group-create sg_app
$ neutron security-group-rule-create ...
...
```

Is this problem reproducible on the command line? If so, I would file a bug with VIO. If it's _not_ reproducible, then run the above commands with the `--debug` option, post them to a gist, remove any sensitive information, and let me know the link to the gist. I can take a look at the JSON requests and responses to see what's different between the command-line and Terraform.

IMO, the suggestion about having Terraform handle duplicate rules isn't the best solution for this. If Terraform would do this, it would be allowing you to create a very different environment than what is actually deployed in reality. And now that I know the details, I don't think this is human error at all. This functionality _should_ be possible, but at the moment it looks like VIO isn't allowing it.

Hope that helps,
Joe

**Comment by jtopjian** [comment]
OK, yes, I see you had that in your original example - I apologize for missing that.

This is standard behavior. You can't have the same rule in a security group twice. I don't believe Terraform can do much about this. It's really more of an issue of rule management. If you have a large amount of security group rules to maintain, I would suggest keeping them in some type of database or configuration management system. Then somehow interpolate the data into your Terraform configurations.

I'm going to close this issue, but please let me know if you have any questions.
