### ISSUE TITLE
How to debug terraform while development

### ISSUE THREAD

**Issue by justanshulsharma** [hashicorp/terraform#1257]
Is there any tutorial for debugging terraform while development ?

**Comment by mitchellh** [comment]
TF_LOG=1 and using `log` judiciously. Additionally, a lot of our debugging is based on writing acceptance tests and/or unit tests. If you have a more specific case I can give you a better example.

**Comment by justanshulsharma** [comment]
@mitchellh like in ruby we can use pry at places we wanna debug, i wanna know about something like that.

**Comment by catsby** [comment]
`TF_LOG=1` will cause any `log.Printf()` statements to be dumped to standard out. 
I don't believe Go has anything like Pry where we can intercept program execution and step through things, unfortunately. 

For iterations, you'll have to `make dev` a lot, unless you write an acceptance test first, then you can just run that and your just that code will recompiled and ran:

- https://github.com/hashicorp/terraform#acceptance-tests

**Comment by srinarayanant** [comment]
I dont see any of my log.Printf in the terraform logs , any pointer , I have set TF_LOG=1 , to TRACE etc but dont see the log statements
