### ISSUE TITLE
Referencing a module ARN inside a policy document

### ISSUE THREAD

**Issue by AnudeepReddyJ21** [hashicorp/terraform#12574]
Hi,

Not sure if this is a silly question, but here is what I have done. I have created an sqs queue using a module. 

module.sqs_module.aws_sqs_queue.duo-sqs-queue-without-dead: Creating...
arn: "" => "<computed>"
content_based_deduplication: "" => "false"
delay_seconds: "" => "0"
fifo_queue: "" => "false"
max_message_size: "" => "262144"
message_retention_seconds:   "" => "345600"
name: "" => "duo"
policy: "" => "<computed>"
receive_wait_time_seconds:   "" => "0"
visibility_timeout_seconds:  "" => "30"
module.sqs_module.aws_sqs_queue.duo-sqs-queue-without-dead: Creation complete

Now I am trying to create an IAM policy that gives access to this queue in a different config file. 

resource "aws_iam_policy" "sqs-resource-access" {
    name        = "sqs-resource-access"
    path        = "/"
    description = "Full access to SQS queues"
    policy      = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1472143765000",
      "Effect": "Allow",
      "Action": [
        "sqs:*"
      ],
      "Resource": [
        "${module.sqs_module.aws_sqs_queue.duo-sqs-queue-without-dead.arn}"
      ]
    }
  ]
}
POLICY
}

Error: * resource 'aws_iam_policy.sqs-resource-access' config: unknown module referenced: sqs_module

Is it possible to reference the module attribute like this?

Thanks,
Anudeep

**Comment by vikas027** [comment]
@AnudeepReddyJ21  Pls look [here](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for writing good posts on GitHub :)

What you are looking can be easily be done using [template_file](https://www.terraform.io/docs/providers/template/d/file.html).

Cheers.

**Comment by AnudeepReddyJ21** [comment]
Hi Vikas,

Thanks for your suggestion. I will look into it. And sorry about the issue format.

Anudeep
