### ISSUE TITLE
Feature Request: Google Bigtable provider

### ISSUE THREAD

**Issue by dasch** [hashicorp/terraform#12581]
When managing a Google Cloud project, it would be nice if Terraform was able to create and update Bigtable instances and tables.

**Comment by horsey** [comment]
Has Google provided a Golang API to manage Bigtable instances?  It appears not yet. 
[https://godoc.org/cloud.google.com/go](url)

**Comment by dasch** [comment]
@horsey there's a package here: https://godoc.org/cloud.google.com/go/bigtable

**Comment by danawillow** [comment]
Hey @dasch and anyone else subscribing to this: we have a PR in progress for this at https://github.com/terraform-providers/terraform-provider-google/pull/130. Is the functionality there enough for you with regards to Instances? The client library for Bigtable is different from the rest of our resources, and it doesn't have all the functionality we're used to (the biggest missing feature seems to be the ability to update anything). At this point we can either leave it as-is and try to get them to add more support in the client library, or ask them to expose their REST API (plus the corresponding autogenerated library). It would be good to have some customer data to back up whichever we ask them for, so if what's there is not quite sufficient, I'd love specifics on what would be needed to make it work.

**Comment by dasch** [comment]
@danawillow I'm not sure if the client library exposes it (the gcloud CLI tool does), but we would like to be able to set an instance as either DEVELOPMENT or PRODUCTION. The former is _much_ cheaper and really the only way to have cost-effective developer environments. A DEVELOPER instance can be upgraded to PRODUCTION but not the other way around.

We'd also love the ability to set up tables, although that is a secondary concern.

**Comment by garye** [comment]
Instance can be added easily to the client library - I'll post here when it's in.

**Comment by garye** [comment]
@danawillow @dasch You can now specify an `InstanceType` when creating an instance.

https://github.com/GoogleCloudPlatform/google-cloud-go/commit/7a4ba9f439fbc50061834a4063b57cf7222ba83f

**Comment by danawillow** [comment]
Thanks @garye!
