### ISSUE TITLE
Enable Connection Draining for AWS Amazon Load Balancer

### ISSUE THREAD

**Issue by RuslanHamidullin** [hashicorp/terraform#1258]
Hey Guys,

Is it possible to enable "Connection Draining" for AWS Amazon Load Balancer via Terraform?
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/config-conn-drain.html

Thanks :beers:

**Comment by catsby** [comment]
A promising pull request was opened for this https://github.com/hashicorp/terraform/pull/1502

**Comment by phinze** [comment]
This is released in 0.5!

**Comment by RuslanHamidullin** [comment]
Perfect :+1:
