### ISSUE TITLE
Race condition in multiple Scaleway IP creation

### ISSUE THREAD

**Issue by zarbis** [hashicorp/terraform#12608]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- scaleway_ip

### Terraform Configuration Files
```hcl
resource "scaleway_ip" "public_ip" {
  count = "5"
}
```

### Debug Output
https://gist.github.com/zarbis/cf530e2451b5c11a428d920526672d35

### Expected Behavior
Five Scaleway IPs created.

### Actual Behavior
Only one random IP created. Index of successful IP changes every time.
While `terraform apply -parallelism=1` always gives expected behavior.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by nicolai86** [comment]
I'll take a look later today. Thank you for the bug report!

**Comment by nicolai86** [comment]
I've looked into this and it looks like a Scaleway API issue. The issue goes away once I put a mutex in place. I've raised the issue in the official SDK and will provide an hack which limits concurrency inside the Scaleway Provider for this specific case…

**Comment by nicolai86** [comment]
closing as it has been fixed /w #12707
