### ISSUE TITLE
vsphere_virtual_machine resource, terraform doesnt record to state the second disk details

### ISSUE THREAD

**Issue by sizgiyaev** [hashicorp/terraform#12606]
Hi,

I need to deploy the vsphere machine with 2 virtual disks. After the machine is actually deployed and both disks are created the the tfstate doesn't include the details for the second disk but only for the one that deployed from template. So, anytime i run terraform plan , it thinks it needs to add the second disk to the machine even if the disk is in place. Maybe i do something wrong ? 

### Terraform Version
0.8.8

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files
```
resource "vsphere_virtual_machine" "srv" {
  datacenter = "datacenter1"
  cluster    = "cluster1"

  count = 3

  name = "${upper(format("srv-%s", format("%02d", count.index + 1)))}"

  folder = "folder1"
  vcpu   = 2
  memory = 4096

  network_interface {
    label = "vm_network1"
  }

  disk {
    datastore = "vm_datastore1"
    bootable  = "true"
    template = "vm_template"
  }

  disk {
    datastore = "vm_datastore1"
    size      = 100

    name = "${format("%s_2", upper(format("srv-%s", format("%02d", count.index + 1))))}"

    type            = "thin"
    controller_type = "scsi"
    bootable        = "false"
  }

  skip_customization = "true"
}
```

**Comment by sizgiyaev** [comment]
Nobody suffered from this issue? So maybe i'm doing something wrong?

**Comment by sizgiyaev** [comment]
Is there a plan to fix this issue?

**Comment by glennmcallister** [comment]
I'm running into exactly this problem right now in 0.9.4, and man is it frustrating. We want to deploy VMs with a small disk for the operating system, and a secondary disk for data. 

I'm working around the problem right now by using 

```
lifecycle {
  ignore_changes = [
    "disk"
  ]
}
```

But that is in no way satisfying.

**Comment by sizgiyaev** [comment]
I also use the same workaround :(
