### ISSUE TITLE
terraform: Crash when planning tainted DDB table in a submodule (in InstanceState.MergeDiff)

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform#12600]
### Terraform Version

Terraform v0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_dynamodb_table

### Terraform Configuration Files

I can share if needed, but this is huge and sensible, so I'd rather not.
Those are very simple DDB tables
```hcl
resource "aws_dynamodb_table" "items_table" {
  name           = "${var.items_table_name}"
  read_capacity  = "${var.items_read_capacity}"
  write_capacity = "${var.items_write_capacity}"
  hash_key       = "id"

  attribute {
    name = "id"
    type = "S"
  }

  attribute {
    name = "platform.xid"
    type = "S"
  }

  attribute {
    name = "xtype"
    type = "S"
  }

  global_secondary_index {
    name               = "platform.xid-index"
    hash_key           = "platform.xid"
    range_key          = "xtype"
    read_capacity      = "${var.xid_index_read_capacity}"
    write_capacity     = "${var.items_write_capacity}"
    projection_type    = "KEYS_ONLY"
  }
}

resource "aws_dynamodb_table" "streams_table" {
  name           = "${var.streams_table_name}"
  read_capacity  = "${var.streams_read_capacity}"
  write_capacity = "${var.streams_write_capacity}"
  hash_key       = "partition_id"
  range_key      = "item_id"

  attribute {
    name = "partition_id"
    type = "S"
  }

  attribute {
    name = "item_id"
    type = "S"
  }

  attribute {
    name = "timestamp.item_id"
    type = "S"
  }

  local_secondary_index {
    name      = "stream_timeline-index"
    range_key = "timestamp.item_id"

    projection_type    = "INCLUDE"
    non_key_attributes = ["timestamp", "stream_id"]
  }
}
```

The only specific thing is that those tables are defined 2 modules deep, and I tainted them using:
`terraform taint -module=mymodule.mysubmodule aws_dynamodb_table.streams_table`

### Debug Output

https://gist.github.com/lra/a2d2b1759ac294f0eed21b2b5ef462cb

### Panic Output

https://gist.github.com/lra/9082621101d891cfe5435b495a16355e

### Expected Behavior

`terraform plan` should not crash after tainting those DDB tables.

### Actual Behavior

`terraform plan` crashes

### Steps to Reproduce

1. taint those DDB tables, e.g. `terraform taint -module=bigtime.bigtime-qa_chai aws_dynamodb_table.items_table`
1. `terraform plan`

### Important Factoids

EC2 classic + tight ACLs.

**Comment by lra** [comment]
Not a blocker as a quick fix for me was to delete the tables and remove them from the tfstate file.

**Comment by mildwonkey** [comment]
The codepath in this stack trace is no longer used by terraform v0.12, so I am going to close this issue. Please don't hesitate to open a new issue if you see any odd behavior in 0.12. Thank you!
