### ISSUE TITLE
Error when changing .tf file for more AWS instances of existing resource

### ISSUE THREAD

**Issue by Falx** [hashicorp/terraform#1261]
My initial infrastructure had a resource called datapool with just 1 instance of type t2.small.
I changed the count to 3 and re-planned and apply-ed it.
This is the error i got:

```sh
Error applying plan:

1 error(s) occurred:

* 2 error(s) occurred:

* aws_instance.datapool.0: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* aws_instance.datapool.1: diffs didn't match during apply. This is a bug with Terraform and should be reported.

```

**Comment by catsby** [comment]
Hey @Falx, is this on 0.3.7 or the latest `master`? 
Do you have a bare-minmum config that can reproduce this issue? 
If you can share one, omitting any secrets of course, that would be helpful.

**Comment by Falx** [comment]
Hi @catsby, I am on v0.4.0-dev.
I am sorry, I tried reproducing it, but I don't seem to be able to  :-1:

**Comment by mitchellh** [comment]
Please let us know if you're able to reproduce. We haven't been able to. Thanks!
