### ISSUE TITLE
[feature] Changing TTL for digitalocean_record

### ISSUE THREAD

**Issue by scalp42** [hashicorp/terraform#12631]
Hi folks,

I was wondering if there was a way to change the TTL for a DO record in a domain ?

Cheers!

**Comment by scalp42** [comment]
Appears to be a limitation on the API side: https://www.digitalocean.com/community/questions/lower-ttl-value-on-dns-records?answer=34000

**Comment by pinepain** [comment]
Hi, It seems to be that there is TTL field in API now - https://developers.digitalocean.com/documentation/v2/#domain-records (which already available in godo tool - https://github.com/digitalocean/godo/blob/master/domains.go).

**Comment by pinepain** [comment]
Bump @scalp42, should the issue be re-opened or new issue reported?

**Comment by scalp42** [comment]
@pinepain thanks for the heads up!

Re-opening I guess for a feature maybe but my go skills are limited to be able to contribute.
