### ISSUE TITLE
Using maps in count throws circular dependency

### ISSUE THREAD

**Issue by beanaroo** [hashicorp/terraform#12630]
### Terraform Version
`0.8.8`

### Affected Resource(s)
Please list the resources as a list, for example:
- AWS Security group rule
- core

#### environment.tf
```hcl
module "preview_api-nodejs" {
    source                   = "../modules/infrastructure_modules/api-nodejs"
....
    vpc                      = {
        vpc_id                = "${module.preview_vpc.vpc_id}"
        cidr                 = "${var.vpc["cidr"]}"
        Subnets              = "${join(",", module.preview_vpc.private_subnets)}"
        ELBSubnets           = "${join(",", module.preview_vpc.public_subnets)}"
        AssociatePublicIp    = "${var.nodejs_api_vpc["AssociatePublicIp"]}"
		ssh_allowed          = "${var.security["ssh_enabled"] == "true" ? 1 : 0}"
        ssh_allowed_cidrs    = "${join(",", concat(list(var.vpc["control_vpc_cidr"]), split(",",var.security["ssh_whitelist"])))}"
    }
....
}
```
#### ../modules/infrastructure_modules/api-nodejs
```hcl
....
resource "aws_security_group_rule" "ec2_allow_ssh" {
    count             = "${var.vpc["ssh_allowed"]}" 
    type              = "ingress"

    from_port         = 22
    to_port           = 22
    protocol          = "tcp"
    cidr_blocks       = ["${split(",", var.vpc["ssh_allowed_cidrs"])}"]

    security_group_id = "${aws_security_group.nodejs_ec2.id}"
}
....
````
Results in:
```
Errors:

  * 1 error(s) occurred:

* Cycle: module.preview_vpc.aws_subnet.public (destroy), module.preview_vpc.aws_subnet.public, module.preview_vpc.output.public_subnets, module.preview_ics-api-nodejs.var.vpc, module.preview_ics-api-nodejs.aws_security_group_rule.ec2_allow_ssh (destroy), module.preview_vpc.aws_subnet.private (destroy), module.preview_vpc.aws_subnet.private, module.preview_vpc.output.private_subnets
```

When we hardcode `count` to `1` or `0`. It works.
`count = "${"true" == "true" ? 1 : 0}"` works too.

The work(hack)around suggested by a contributor [here](https://github.com/hashicorp/terraform/issues/12570#issuecomment-286003715) works but also only for string values.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by beanaroo** [comment]
On Terraform 0.9.0-dev, instead of a cycle error, I get a `value of 'count' cannot be computed` for the above configuration.

**Comment by beanaroo** [comment]
I think I understand the issue now.

The maps I try to pass all contain values computed from other resources. So count cannot be computed because the map is incomplete.

If I am correct and if this is not a real issue, please feel free to close this report.

**Comment by jbardin** [comment]
@beanaroo,

Yes, that sounds correct. 

We do hope to improve the support for transferring interpolated values through module boundaries, but we can close this particular issue for now.
