### ISSUE TITLE
Unable to remove vars

### ISSUE THREAD

**Issue by Vampouille** [hashicorp/terraform#12643]
I remove some variables from my stack.tf file but terraform was unable to remove those variables on rancher: a terraform apply always show differences about variables count : 

```
rancher_stack.georchestra-apache-nas: Modifying...
  environment.%:            "6" => "1"
  ...
  ...
```

Additional infos :

Terraform version : v0.8.6
Affected Resource : rancher
Config : 
```
resource "rancher_stack" "georchestra-apache-nas" {
  name            = "georchestra-apache-nas"
  environment_id  = "${var.environment_id}"
  catalog_id      = "georchestra:georchestra-apache-nas:3"
  start_on_create = true
  finish_upgrade  = true

  environment {
    "VOLUME_ID" = "apache_nas_data"
  }
}
```

### Expected Behavior
It should remove extra vars

### Actual Behavior
Nothing is changed

### Steps to Reproduce
1. remove vars 
2. `terraform apply`

**Comment by raphink** [comment]
This is linked to the way Rancher works. It is not possible to remove past variables using the Rancher web interface either.

**Comment by raphink** [comment]
Opened https://github.com/rancher/rancher/issues/8152
