### ISSUE TITLE
[aws] route53 zone times out even though zone is created

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/terraform#12666]
### Terraform Version
0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_zone

### Terraform Configuration Files
```hcl
resource "aws_route53_zone" "website_io" {
  name    = "website.io"
  force_destroy = "false"

  tags {
    Env = "dev"
  }
}
```

### Panic Output
aws_route53_zone.website_io: timeout while waiting for state to become 'INSYNC' (timeout: 10m0s)

### Expected Behavior
Simple R53 zone should have been applied. 

### Actual Behavior
R53 zone was applied when checking the AWS console but Terraform was stuck waiting on the resource.

### Steps to Reproduce
1. `terraform plan`
1. `terraform apply`

**Comment by chiragrr** [comment]
Seeing the same issue.

**Comment by Jeiwan** [comment]
Possibly an AWS issue: https://status.aws.amazon.com/ 

```
4:44 PM PDT We are investigating slow propagation of DNS edits to the Route 53 DNS servers. This does not impact queries to existing DNS records.
5:11 PM PDT We continue to investigate slow propagation of DNS edits to the Route 53 DNS servers. This does not impact queries to existing DNS records.
6:34 PM PDT We have identified root cause of the slow propagation of DNS edits to the Route 53 DNS servers and are working towards recovery. This does not impact queries to existing DNS records.
7:40 PM PDT We continue to experience slow propagation times and continue to work towards full recovery. This does not impact queries to existing DNS records.
```

**Comment by dhawal55** [comment]
I'm facing the same issue. What's up with Amazon, first S3 and now Route53. It's broken for last 9 hrs and no ETA on a fix.

**Comment by vikas027** [comment]
Yeah, Route53 is down for new records (what they claim to say). Atm I cannot even delete/add records using AWS Console

**Comment by sheldonkwok** [comment]
Bummer wish I saw that status page earlier.

**Comment by stack72** [comment]
Hi all

Looks like this is an AWS issue not a terraform issue - sorry for the issue here. If you still see the same behaviour when they clear the problem, please do comment and we can reopen the issue

Thanks

Paul

**Comment by ravibhure** [comment]
I have the similar issue today for multiple times in aws Oregon,

```
1 error(s) occurred:

* aws_route53_zone.private_zone: timeout while waiting for state to become 'INSYNC' (last state: 'PENDING', timeout: 10m0s)

```

Route53 status shows healthy in all region on aws status page.

When checked on route53 dashboard, I had more than 100+ number of zones and I deleted almost half of them fixed my issue.
