### ISSUE TITLE
Cannot destroy instance when reclaim_instance is enabled in Openstack Nova.

### ISSUE THREAD

**Issue by cloudrkt** [hashicorp/terraform#12674]
Hi,

I cannot destroy an instance created on Openstack when the status is soft_deleted. Can terraform force delete an instance?

### Terraform Version

Terraform v0.8.8

### Affected Resource(s)
- openstack instance 

### Terraform Configuration Files
```hcl

resource "openstack_compute_floatingip_v2" "terraform" {
  pool       = "${var.pool}"
  depends_on = ["openstack_networking_router_interface_v2.terraform"]
}

resource "openstack_compute_keypair_v2" "terraform" {
  name       = "terraform"
  public_key = "${file("${var.ssh_key_file}.pub")}"
}

resource "openstack_networking_network_v2" "terraform" {
  name           = "terraform"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "terraform" {
  name            = "terraform"
  network_id      = "${openstack_networking_network_v2.terraform.id}"
  cidr            = "10.0.0.0/24"
  ip_version      = 4
  dns_nameservers = ["8.8.8.8", "8.8.4.4"]
}

resource "openstack_networking_router_v2" "terraform" {
  name             = "terraform"
  admin_state_up   = "true"
  external_gateway = "${var.default_public_gateway_id}"
}

resource "openstack_networking_router_interface_v2" "terraform" {
  router_id = "${openstack_networking_router_v2.terraform.id}"
  subnet_id = "${openstack_networking_subnet_v2.terraform.id}"
}

resource "openstack_compute_secgroup_v2" "terraform" {
  name        = "terraform"
  description = "Security group for the Terraform example instances"
}

resource "openstack_compute_instance_v2" "terraform" {
  availability_zone = "NL1"
  name              = "terraform"
  image_name        = "${var.image}"
  flavor_name       = "${var.flavor}"
  key_pair          = "${openstack_compute_keypair_v2.terraform.name}"
  security_groups   = ["${openstack_compute_secgroup_v2.terraform.name}"]
  floating_ip       = "${openstack_compute_floatingip_v2.terraform.address}"

  network {
    uuid = "${openstack_networking_network_v2.terraform.id}"
  }
}
```

### Debug Output

https://gist.github.com/cloudrkt/4ecf84692f79ffa71120b4037eeb6db5

### Expected Behavior
Should delete the instance when using terraform destroy

### Actual Behavior
Error message when deleting instance

```
 Unexpected state 'SOFT_DELETED', wanted target 'DELETED'.
```
### Steps to Reproduce

On an Openstack Cloud with soft_delete enabled 

1. `terraform apply`
2. `terraform destroy`

### Important Factoids
- Standard openstack provider
- reclaim_instance_interval enabled in etc/nova/nova.conf

### References
- Issue supposed to be fixed in: #5104

**Comment by jtopjian** [comment]
Hi there,

Actually, this problem was never fixed in #5104, so this is still a known open issue. I personally haven't looked into this because, AFAIK, soft deletion was something that was only enabled for a few releases and was quickly removed. Maybe I'm wrong about that? But due to that, other more widespread features and bugs have taken precedence, which is unfortunate for this case.

I'm going to close this issue in favor of #5104. I'll see if I can get some time to revisit this soon, though.

Thanks,
Joe

**Comment by cloudrkt** [comment]
@jtopjian The feature is still there in the latest release (Openstack Ocata - released on 2017-02-22).

**Comment by jtopjian** [comment]
@cloudrkt hm. Yeah, I can grep for the keywords `reclaim_instance_interval` and `SOFT_DELETED` in the Nova code, but I can find no documentation about this feature? That's frustrating. :/

Anyway, you are correct - this most certainly still is around. Thank you for clarifying that. :)
