### ISSUE TITLE
`outputs` from irrelevant modules generated in state file

### ISSUE THREAD

**Issue by eyalzek** [hashicorp/terraform#12683]
### Terraform Version
v0.8.8

Our infrastructure is represented by modules, where each environment is configured as a separate module with a separate state file, a folder holding `modules` and a folder holding `submodules`. The `modules` are used by all environments (which are modules of their own) and the `submodules` are used by the `modules` themselves (creating a nested module structure). example folder structure:

```
terraform
├── submodules
│   ├── foo.tf
├── modules
│   ├── one.tf
│   ├── two.tf
│   ├── three.tf
│   └── four.tf
├── dev.tf
├── dev.tfstate
├── staging.tf
├── staging.tfstate
├── production.tf
└── production.tfstate
```

example content of files (I'm redacting most of the content since it seems irrelevant, let me know if anything is needed)

top-level module file (dev/staging/production):

```
module "dev" {
    source = "./modules"
    environment = "dev"
    region = "eu-central-1"
}
```

modules file (from the `modules` folder):

```
resource "aws_security_group" "one" {
    ......
}

module "one" {
    source = "../submodules"
    .....
}
```

submodule file (from the `submodules` folder):

```
resource "aws_instance" "foo" {
    ....

    provisioner "chef"  {
        ....
    }
}

output "server_ids" {
    value = ["${aws_instance.foo.*.id}"]
}
```

A problem that has always existed (since I've started using terraform, around v0.6.2 or so until now), is that even though our modules are separated and each of them is using a separate state file, every `output` that's configured anywhere in the configuration (be it the top level module or a nested one), is generating an entry for each environment in EACH of the state files.

For example, inside the `dev.tfstate` file I would see something like the following:

```
        {
            "path": [
                "root",
                "production"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        },
        {
            "path": [
                "root",
                "production",
                "one"
            ],
            "outputs": {
                "server_ids": {
                    "sensitive": false,
                    "type": "list",
                    "value": []
                }
            },
            "resources": {},
            "depends_on": []
        },
        {
            "path": [
                "root",
                "production",
                "two"
            ],
            "outputs": {
                "server_ids": {
                    "sensitive": false,
                    "type": "list",
                    "value": []
                }
            },
            "resources": {},
            "depends_on": []
        },
        {
            "path": [
                "root",
                "staging",
                "one"
            ],
            "outputs": {
                "server_ids": {
                    "sensitive": false,
                    "type": "list",
                    "value": []
                }
            },
            "resources": {},
            "depends_on": []
        }
```

our configuration code base is obviously bigger than the examples I've given above, so we are talking about ~2000 lines of irrelevant outputs in each state file (where a full state file is about ~9000 lines).
These lines are generated with every operation that manipulates the state file, if I'll remove them manually they'll just re-appear next time I apply something. This is very annoying, especially since our state files are version controlled by git and the amount of diff created from a simple operation is unbelievable.

For reference, an example operation would be similar to the following commands:

```
terraform apply -state=dev.tfstate -target=module.dev

terraform apply -state=dev.tfstate -target=module.dev.aws_security_group.one

terraform apply -state=dev.tfstate -target=module.dev.module.one
```

**Comment by apparentlymart** [comment]
Hi @eyalzek! Sorry this isn't working as expected.

I think the problem here is that you have all of the environment `.tf` files in the same directory. A module in Terraform is an entire directory of files, not just one file. If you move each of those environment configuration files into its own directory and apply it from there you should see them truly separated as you wanted.

It looks like you are trying to use `-target` to apply each environment separately even though from Terraform's perspective they are all in one module. If you use a separate directory for each then this will no longer be necessary since each directory will stand alone as a root module with its own configuration and state.

**Comment by eyalzek** [comment]
Thanks for the quick reply! Would you consider it a bug though or should we just consider structuring our configuration as you suggested?

**Comment by eyalzek** [comment]
Just tested this and have a follow up question; currently I have a `terraform.tfvars` file and `main.tf` file (holding default variable definitions) at the top-level `terraform` directory which works well. I attempted creating a directory `staging` and put the `staging.tf` & `staging.tfstate` files in their and got the following when running a plan:

```
terraform plan -state=staging/staging.tfstate -target=module.staging.module.one
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: 
```

I'm running this command from inside the `terraform` directory where the `tfvars` & `main.tf` files are and according to the docs the vars should be read. I copied both `terraform.tfvars` & `main.tf` to the `staging` directory and the result was the same. Changing into the `staging` directory and running:

`terraform plan -state=staging.tfstate -target=module.staging.module.one` 

does work!

Problems I have with this:
- `main.tf` (default variables) needs to be copied to each environment directory even though the content is exactly the same.
- `terraform.tfvars` needs to be copied
I can possibly move the default variables from `tfvars` to the `main.tf` file, but in which case I would commit values which are user-specific and that doesn't make much sense.
- I cannot run commands anymore from the `terraform` directory, but have to change into the environment folder instead - this is a minor inconvenience

**Comment by apparentlymart** [comment]
Some options for sharing configuration values between modules:

* Export them as outputs of another module that you can instantiate in each environment. This is the most ideal way, but sadly won't work if you are using the values in places where only variables are allowed, such as `count`. (This will improve in future versions.)
* Symlink your tfvars and variable config files from another location into each environment directory. This works on Unix-ish systems but might not work on Windows.

**Comment by eyalzek** [comment]
Ok thanks for the info. I think we would go with a `main.tf` holding the actual defaults for each environment, then commit and then ignore a `terraform.tfvars` holding a dummy value for things that actually needs to change among users. On that note, our state file name can be changed back to `terraform.tfvars`, saving us some typing when performing operation :+1: 
Should we close this issue or is that something that you'd want to be changed?

**Comment by apparentlymart** [comment]
Sorry I lost track of this discussion back in March 2017, but it sounds like you found a working approach here, so I'm going to close this out.

On a somewhat related note, Terraform 0.12.0 now stores only the root module outputs in the persisted state, so although having all of the configuration files in the one directory rather than one directory per environment was the problem here, with Terraform 0.12.0 the state wouldn't have been so large.
