### ISSUE TITLE
Terraform should be able to generate wrapped vault secret-ids for servers

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#12687]
Terraform all versions. Hashicorp Vault 0.6+

Terraform<->Vault is missing a fundamental feature which would allow vault AppRole authentication to work.

AppRole authentication in Vault is provided so that a server, or apps running on a server are able to authenticate itself to Vault and procure secrets.

In order to work, the authentication login step requires two bits of information - a role_id and a secret_id. Vault best practice describes how you generate a role_id, and might commit this into configuration management (e.g. Packer+Ansible => AMI) , whereas the secret_id should be supplied to the final app if possible.

It also suggests that for maximum security, the secret_id when requested should be response-wrapped using the Vault cubbyhole backend, which basically means that only one entity is able to decrypt it. If the target/server decrypts it then all is well. If a bad actor decrypts it first, then the target/server cannot decrypt it, and can raise an alert about doing so. 

All this presents a lovely case for an integration step between terraform and vaults AppRole, so that prior to spinning up an aws_instance resource, terraform requests a wrapped secret-id from Vault's AppRole API, passes the wrapped secret-id into user-data, and then the resultant ec2 instance spinning up can unwrap the secret, and get whatever secrets it needs. 

However this functionality is missing. Could we have it please?

All that would be needed is a new data resource called something like vault_approle_wrapped_secret:

```
data "vault_approle_secret_id" "jenkins" {
    role_id="1234-123456-1234-1234"
    wrapped="true"
    ttl="60s"
}
```

Then in a corresponding userdata cloud-init template (or equivalent), this can be referred to easily:

```
SECRET_ID_WRAPPED_TOKEN=${data.vault_approle_secret_id.jenkins}
```

et Voila - the instance spins up, gets the role_id from its AMI (ansible), get the wrapped token_id from user-data and does the following (probably in a bash startup script)

```
1. authenticates to vault with unwraponly:password to allow it to unwrap wrapped secrets.
2. unwraps the SECRET_ID_WRAPPED_TOKEN to yield a SECRET_ID
3. re-authenticates to vault using the role_id and the secret_id
4. pulls whichever secrets it needs out of vault.
```

**Comment by i-sam** [comment]
+1 need something to do things like this: 
`vault write auth/aws-ec2/role/test-vault bound_iam_role_arn=arn:aws:iam::<account_number>:role/test_vault policies=test ttl=10s`

**Comment by jsoriano** [comment]
I have started to try to do this by modifying the `vault_generic_secret` data source to support write commands and `wrapTTL` option (see my -not fully working- code [here](https://github.com/hashicorp/terraform/compare/master...jsoriano:vault-secret-id-wrapping?expand=1)) and the main problem I see is that every time you request a wrapped token you obviously are going to receive a different response, and this is the only thing terraform is going to see to keep its state, so the state will change on every run.
I don't know how to make data that changes on every run fit with terraform state. Any thoughts about this?

**Comment by jsoriano** [comment]
In reply to myself, indeed the data seems to be only requested if the request using it changes, so my code works as expected for example with this:

```
data "vault_generic_secret" "wrapped_secret_id" {
  path = "auth/approle/role/testrole/secret-id"
  command = "write"
  wrap_ttl = "30s"
}

resource "digitalocean_droplet" "vault-test-1" {
  image  = "ubuntu-14-04-x64"
  name   = "vault-test-1"
  region = "ams3"
  size   = "512mb"
  ssh_keys = ["..."]

  provisioner "file" {
    content = "${data.vault_generic_secret.wrapped_secret_id.wrap_information["token"]}"
    destination = "/var/vault-token"
  }
}
```
