### ISSUE TITLE
Terraform not pulling GIT url, treating it like a file path instead.

### ISSUE THREAD

**Issue by lanmalkieri** [hashicorp/terraform#12696]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
Module Source

### Terraform Configuration Files
```hcl
module "networking" {
  source = "git@bitbucket.org:REDACTED/terraform-modules.git//networking?ref=networking-1.0.0"
  vpc_cidr = "${var.vpc_cidr}"
  env = "${var.env}"
  azs = "${var.azs}"
  azs_short = "${var.azs_short}"
  vpc_link_ids = "${var.vpc_link_ids}"
  acct_number = "${var.acct_number}"
  enable_ops_sgs = "${var.enable_ops_sgs}"
  enable_pentaho = "${var.enable_pentaho}"
  pcx_ids = "${var.pcx_ids}"
  ops_cidrs = "${var.ops_cidrs}"
  pcx_count = "${var.pcx_count}"
}
```

### Debug Output
Running terraform get I see that it tries to pull a file, and not a repository. 

root@terraform1c [OPS]:/srv/terraform/accounts/ra/us-west-2/networking > /usr/local/bin/terraform get
Get: file:///srv/terraform/accounts/ra/us-west-2/networking/git@bitbucket.org:REDACTED/terraform-modules.git?ref=networking-1.0.0
Error loading Terraform: Error downloading modules: error downloading 'file:///srv/terraform/accounts/ra/us-west-2/networking/git@bitbucket.org:REDACTED/terraform-modules.git?ref=networking-1.0.0': source path error: stat /srv/terraform/accounts/ra/us-west-2/networking/git@bitbucket.org:REDACTED/terraform-modules.git: no such file or directory

### Expected Behavior
I expect that it should source a git repo.

### Actual Behavior
It tries to source a file.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. using this main.tf run terraform get

**Comment by lanmalkieri** [comment]
Additionally, updating the source to specify ssh and git as I've seen a few people do I get a name resolution error. 

```hcl
module "networking" {
  source = "git::ssh://git@bitbucket.org:REDACTED/terraform-modules.git//networking?ref=networking-1.0.0"
  vpc_cidr = "${var.vpc_cidr}"
  env = "${var.env}"
  azs = "${var.azs}"
  azs_short = "${var.azs_short}"
  vpc_link_ids = "${var.vpc_link_ids}"
  acct_number = "${var.acct_number}"
  enable_ops_sgs = "${var.enable_ops_sgs}"
  enable_pentaho = "${var.enable_pentaho}"
  pcx_ids = "${var.pcx_ids}"
  ops_cidrs = "${var.ops_cidrs}"
  pcx_count = "${var.pcx_count}"
}
```
Get: git::ssh://git@bitbucket.org:REDACTED/terraform-modules.git?ref=networking-1.0.0 (update)
Error loading Terraform: Error downloading modules: error downloading 'ssh://git@bitbucket.org:REDACTED/terraform-modules.git?ref=networking-1.0.0': /usr/bin/git exited with 128: Cloning into '.terraform/modules/4a9a416ce574ce90eda215bcc40e6759'...
ssh: Could not resolve hostname bitbucket.org:REDACTED: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rocketspacer** [comment]
Was this fixed?

**Comment by rajcheval** [comment]
I am facing the exact same issue while trying to access module in private bitbucket repo.

**Comment by Jyoti492** [comment]
Is it fixed ?? I am facing the same issue while downloading from Azure DevOps private repo
