### ISSUE TITLE
Terraform Remote command Reads keys from datasource.

### ISSUE THREAD

**Issue by nckslvrmn** [hashicorp/terraform#12692]
Hello. Im not sure if I'm missing something here, but both the terraform_remote_state data source and the AWS provider can be passed AWS key pairs. This is great because we can store keys in vault and pass the to the providers.

We cant however, do the same thing for the terraform remote command. From what i can tell the terraform remote command when using s3 must read AWS key pairs from the credentials files or the environment variables.

Is there any way the terraform remote command can read from the aws provider or a vault datasource for those keys?

Im using terraform 0.8.8

**Comment by nckslvrmn** [comment]
This is solved by terraform 0.9.x's remote backend concept. Cant wait to see the backend config have interpolation support so I can really unify the keys I use but this would be a separate request.

**Comment by apparentlymart** [comment]
Hi @nckslvrmn! Sorry for the long silence here.

As I think you saw back in 2017, the S3 backend now supports the same authentication options that the AWS provider does, and in fact shares the same authentication code with the AWS provider. Therefore I think this has met your request, and so I'm going to close this out. Sorry we missed updating this before!
