### ISSUE TITLE
"Optional" fields not supported at the provider level. 

### ISSUE THREAD

**Issue by paddyforan** [hashicorp/terraform#12736]
When a provider's field is marked as removed, I'd expect Terraform to know not to prompt users for input on it, especially if the file is marked as optional. But in #12729, it appears that users are being prompted for input on a removed, optional field.

**Comment by yusufkarhoo** [comment]
yep, can't manage any google cloud resources!

**Comment by jbardin** [comment]
@paddyforan, I think I see the difference here. All other uses of `Removed` are in resources, this is the only one that is at a provider level. 

Turns out that that schema.Provider doesn't `Optional`.

**Comment by paddyforan** [comment]
So is Removed not supported at the provider level? If not, is there a technical or UX reason it can't be? I guess the better question is: do we consider Removed not preventing Terraform from prompting for input a bug, or do we just consider Optional not preventing Terraform from prompting for input a bug? (Or both, I suppose?)

**Comment by jbardin** [comment]
No, `Removed` technically is working just fine.

`Optional` is not working, so it will always prompt, or if there was a default, it would fail to validate.
