### ISSUE TITLE
build: consul tests failing on 0.9.0 tag and master

### ISSUE THREAD

**Issue by cblecker** [hashicorp/terraform#12731]
https://github.com/Homebrew/homebrew-core/pull/11116#issuecomment-286823544

I've also tried using a clean Vagrant box, and running `make test` results in the `github.com/hashicorp/terraform/builtin/providers/consul` test failing.

**Comment by stack72** [comment]
@cblecker thanks for raising the issue - we will look into this

Thanks

Paul

**Comment by cblecker** [comment]
It appears that https://github.com/hashicorp/terraform/pull/12733 (https://github.com/hashicorp/terraform/commit/a4ba2b27fd1398fdf0022ef1748eb0caf9078ab2) fixed this issue. I'm patching it into https://github.com/Homebrew/homebrew-core/pull/11116 so that the homebrew version can build.

**Comment by stack72** [comment]
Closed via #12733
