### ISSUE TITLE
Terraform Apply Fails on SSM_Document creation when SSM Doc type is set to Automation

### ISSUE THREAD

**Issue by tyjonesAncestry** [hashicorp/terraform#12746]
Hi there,

### Terraform Version
Terraform v0.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ssm_document

### Terraform Configuration Files
```hcl
data "aws_caller_identity" "current" {}

data "aws_region" "current" {
  current = true
}

resource "aws_ssm_document" "autotest" {
  name          = "REDACTED"
  document_type = "Automation"

  content = <<DOC
REDACTED
DOC
}
```

### Debug Output
https://gist.github.com/tyjonesAncestry/e40f599cd16415e5a3e90e3ec3e383fd

### Panic Output
https://gist.github.com/tyjonesAncestry/c2e7cffcd39ca6dfa2435f2a74a74a80

### Expected Behavior
My SSM Automation Document should have been created with Terraform.

### Actual Behavior
Terraform loses it's mind with an EOF error, but the resource somehow still gets created in my AWS console. However, it breaks all subsequent runs of terraform.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an SSM Document of type "Automation"
2. Run terraform plan
3. Plan looks good.
4. Run terraform apply.
5. Terraform crashes.

### Important Factoids
SSM Document creation works flawlessly as long as the document_type filed is set to "Command"

**Comment by tyjonesAncestry** [comment]
Nil Pointer exception is being thrown on line 208 of https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_ssm_document.go

param["description"] = *dp.Description appears to be getting a nil value from the resourceAwsSsmDocumentRead function.

Maybe the AWS API is returning a different value for SSM Command Docs vs SSM Automation Docs?

**Comment by tyjonesAncestry** [comment]
We have a fix that we're internally testing right now. Once we've confirmed the fix is in place we'll open up a PR with the code fix.

**Comment by stack72** [comment]
@tyjonesAncestry sorry for the issue here - <3 for looking at opening a PR for this

**Comment by dcjohnson** [comment]
Should be fixed with with this pr. https://github.com/hashicorp/terraform/pull/12891

**Comment by stack72** [comment]
Closed via £12981
