### ISSUE TITLE
Terraform 0.9.0 regression

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform#12742]
I just updated Terraform from v0.8.8 to v0.9.0 and I think that I have found a regression in `module` behavior. The original code that I was having issues with is quite large, but I think that I have managed to produce a minimum working example, which I have pushed to a separate repository to make it easier to reproduce. The code can be found at https://github.com/joshuaspence/terraform-0.9.0-regression.

On Terraform 0.8.8 running `terraform plan` runs fine, but in Terraform 0.9.0 I get the following error:

```
Error asking for user input: 1 error(s) occurred:

* module.vpc.module.jumphost.var.vpc_zone_identifier: strconv.ParseInt: parsing "${var.availability_zones_count}": invalid syntax
```

**Comment by ryansch** [comment]
I just hit this with the same relationships as in @joshuaspence's regression repo.
