### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ndarilek** [hashicorp/terraform#1276]
github.com\hashicorp\terraform (download)
github.com\hashicorp\consul (download)
github.com\hashicorp\errwrap (download)
github.com\hashicorp\go-checkpoint (download)
github.com\hashicorp\go-multierror (download)
github.com\hashicorp\hcl (download)
github.com\mitchellh\copystructure (download)
github.com\mitchellh\reflectwalk (download)
github.com\mitchellh\mapstructure (download)
github.com\mitchellh\cli (download)
github.com\mitchellh\colorstring (download)
github.com\mitchellh\go-homedir (download)
github.com\hashicorp\yamux (download)
github.com\mitchellh\osext (download)
github.com\mitchellh\panicwrap (download)
github.com\mitchellh\prefixedio (download)
github.com\hashicorp\atlas-go (download)
github.com\hashicorp\aws-sdk-go (download)
github.com\vaughan0\go-ini (download)
github.com\pearkes\cloudflare (download)
github.com\xanzy\go-cloudstack (download)
github.com\pearkes\digitalocean (download)
github.com\imdario\mergo (download)
github.com\soniah\dnsmadeeasy (download)
github.com\pearkes\dnsimple (download)
code.google.com\p\google-api-go-client (download)
golang.org\x\net (download)
golang.org\x\oauth2 (download)
google.golang.org\cloud (download)
code.google.com\p\go-uuid (download)
github.com\cyberdelia\heroku-go (download)
github.com\pearkes\mailgun (download)
golang.org\x\crypto (download)
github.com\armon\circbuf (download)
github.com\mitchellh\go-linereader (download)
github.com/hashicorp/terraform/config
# github.com/hashicorp/terraform/config
expr.y:20[c:\users\nolan\go\src\github.com\hashicorp\terraform\config\y.go:14]: undefined: Interpolation
expr.y:23[c:\users\nolan\go\src\github.com\hashicorp\terraform\config\y.go:17]: undefined: Interpolation

**Comment by catsby** [comment]
`y.go` is a weird remnant that shouldn't be there. Can you try removing it?

**Comment by ndarilek** [comment]
That did it. Thanks!
