### ISSUE TITLE
Cannot use envs with s3 backend for state

### ISSUE THREAD

**Issue by sysadmiral** [hashicorp/terraform#12768]
### Terraform Version
Terraform v0.9.0

### Affected Resource(s)
- Remote Backends
- State Environments

### Terraform Configuration Files
https://gist.github.com/sysadmiral/eb8b75124c44090d76884875f7431913

### Debug Output
https://gist.github.com/sysadmiral/39a2d06f1a59e6f46bb05645efc39530

### Expected Behavior
State Environments is usable with Remote Backends

### Actual Behavior
Once remote state is enable `terraform env` subcommands return `named states not supported` or similar.

### Steps to Reproduce
* Copy the config files
* Change profile in backend_config to a valid named profile
* Change client in terraform.tfvars to a valid named profile (${var.client} is used to set the profile in the aws provider)
* `terraform init -backend-config=backend_config` to setup remote state
* `terraform env list` to list environments

(since terraform init can be run at any time you can try the other way and setup envs first and do the init - the envs are created, remote state is initialized but you can't switch env or list envs)

**Comment by jeffawang** [comment]
This feature would unblock my usage of environments, since I don't run a supported backend at the moment.

Perhaps more frustratingly, I found zero indication of this blocked interaction in the [Environments](https://www.terraform.io/docs/state/environments.html) or [Backend](https://www.terraform.io/docs/backends/types/s3.html) documentation, and I didn't find out until I actually tried it in the CLI. I think some indication that it's not supported would go a long way for people who already use S3 and would like the concept of environments (ie: me).

In addition, the ability to interpolate `${terraform.env}` and/or variables into the backend configuration might be useful for me.

**Comment by tom-schultz** [comment]
+1

S3 is a nearly zero-effort backend for anyone running in AWS. I would really like to see it treated as a first-class citizen when changes and new features are being implemented for backends.

**Comment by moofish32** [comment]
@sysadmiral  - if you remove this line https://gist.github.com/sysadmiral/eb8b75124c44090d76884875f7431913#file-terraform-tf-L3

And make backend-config

```
backend = "s3"
client  = "foo"
service = "bar"
region  = "eu-west-1"
bucket  = "foo-terraform-control"
key     = "bar/dev"
encrypt = "true"
profile = "foo"
```
Do envs now work? For me this is working and allowing me to explore `env` features.

I don't have client and service but other than that our configs are functionally the same and this works: 

```bash
$>terraform env list                                                                                                        
  default
* dev
```

I am not sure I understand why this is marked `enhancement` though? Perhaps there is more under the code that I missed.

**Comment by oyerli** [comment]
+1 - We cannot use environments due to this.

**Comment by oyerli** [comment]
@moofish32 - When you remove the `backend "s3" {}` line, you are using the local storage not S3.
That's why it seems to be working.

**Comment by moofish32** [comment]
@oyerli -- you are correct, I was little quick in the reply

**Comment by eredi93** [comment]
+1

**Comment by daniel-ro** [comment]
@jbardin thank you for implementing it so quickly!
@mitchellh can we expect this change to be released soon as a new app version (0.9.2 or something)
Would be helpful, as it blocks our usage of the new "named state" feature (which was so missing till v0.9, and it's awesome)

**Comment by mitchellh** [comment]
@daniel-ro It'll be part of 0.9.2 which is likely next week.

**Comment by tom-schultz** [comment]
As always, you guys rock.

**Comment by jeffawang** [comment]
I'm very pleased with the turnaround time. Thanks!
