### ISSUE TITLE
Adding/removing subnets from aws_alb provider forces a new resource 

### ISSUE THREAD

**Issue by maxblaze** [hashicorp/terraform#12764]
### Terraform Version
Terraform v0.9.0

### Affected Resource(s)
- aws_alb

### Terraform Configuration Files
Current configuration:
```hcl
resource "aws_alb" "service_name" {
  name            = "service_name"
  internal        = false
  security_groups = ["sg-xxxxxx9"]
  subnets         = ["subnet-xxxxxx0", "subnet-xxxxxxx6"]
}
```

Attempting to apply change:
```hcl
resource "aws_alb" "service_name" {
  name            = "service_name"
  internal        = false
  security_groups = ["sg-xxxxxx9"]
  subnets         = ["subnet-xxxxxx0", "subnet-xxxxxxx6", "subnet-xxxxxx9"]
}
```

### Expected Behavior
The subnet should be added or removed from the existing ALB. This is the behavior allowed in the AWS console.

### Actual Behavior
The existing ALB is destroyed and a new ALB is created with the specified subnets:
```
    subnets.#:                  "2" => "3" (forces new resource)
    subnets.1089807508:         "subnet-xxxxxxx0" => "subnet-xxxxxxx0"
    subnets.4016814805:         "subnet-xxxxxxx6" => "subnet-xxxxxxx6"
    subnets.538262740:          "" => "subnet-xxxxxxx9" (forces new resource)
```

### Steps to Reproduce
1. Create an ALB resource with 2 subnets specified
2. Remove one of the subnets and apply the change

**Comment by jcam** [comment]
I'm seeing this as well. The aws cli allows this via the "aws elbv2 set-subnets" command.

**Comment by stack72** [comment]
Hi All

Working on making this change right now

Paul

**Comment by jcam** [comment]
Yay! Thank you!
Could probably knock out setipaddresstype at the same time as you do setsubnets if you have time, the functionality for both look similar to your update to support setsecuritygroups a few months back.

**Comment by stack72** [comment]
Hi @jcam 

What is the issue you want solved?

P.

**Comment by jcam** [comment]
I personally am interested in the subnets fix, I just happened to notice when i was researching it that you also had an open feature request in the same code areas: https://github.com/hashicorp/terraform/issues/11429

**Comment by stack72** [comment]
Ah nice spot - i'll handle that in a follow up PR 

I just finished the work for the subnets change :)
