### ISSUE TITLE
terraform remote config does not work in 0.9

### ISSUE THREAD

**Issue by ArmandGrillet** [hashicorp/terraform#12762]
Hi there,

I have started using Terraform v0.8.8  two days ago, wrote a README using the `terraform remote config` command for my colleagues. They tried to follow it today and this specific command returns an output showing that the command does not exist.

### Terraform Version
The issue is with Terraform v0.9 that apparently does not include the `remote` command anymore. My colleagues used brew to install Terraform and thus got the latest version, something that was not my case (I was still running v0.8.8 on my computer).

### What can be solved
The current output is kinda useless:
```
$ terraform remote config -backend=s3 -backend-config="bucket=myBucket" -backend-config="key=myKey" -backend-config="region=myRegion"
Usage: terraform [--version] [--help] <command> [args]

The available commands for execution are listed below.
The most common, useful commands are shown first, followed by
less common or more advanced commands. If you're just getting
started with Terraform, stick with the common commands. For the
other commands, please read the help and docs before usage.

Common commands:
    apply              Builds or changes infrastructure
    console            Interactive console for Terraform interpolations
    destroy            Destroy Terraform-managed infrastructure
    env                Environment management
    fmt                Rewrites config files to canonical format
    force-unlock       Manually unlock the terraform state
    get                Download and install modules for the configuration
    graph              Create a visual graph of Terraform resources
    import             Import existing infrastructure into Terraform
    init               Initialize a new or existing Terraform configuration
    output             Read an output from a state file
    plan               Generate and show an execution plan
    push               Upload this Terraform module to Atlas to run
    refresh            Update local state file against real resources
    show               Inspect Terraform state or plan
    taint              Manually mark a resource for recreation
    untaint            Manually unmark a resource as tainted
    validate           Validates the Terraform files
    version            Prints the Terraform version

All other commands:
    debug              Debug output management (experimental)
    state              Advanced state management
```
You were supporting a command in 0.8 and you are not in 0.9, that is perfectly fine but I would expect an output telling me with which command to use instead.

**Comment by maxblaze** [comment]
It's in the release notes:
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#090-march-15-2017

https://github.com/hashicorp/terraform/pull/11286

**Comment by mitchellh** [comment]
Thanks @maxblaze :)

**Comment by mabushey** [comment]
Can I downgrade to .8 to create an s3 backend, and then upgrade back to .9?

**Comment by emvaldes** [comment]
I understand the hashicorp guys working in terraform enforcing their changes in the Mexican-stand mindset of Their-Way-Or-The-Highway.
Now, how can we call terraform within CodeBuild and let terraform use the s3 as the remote config?
The initial idea of using: "terraform remote config -backend=s3 ..." is awesome!
So, how the HashiCorp gurus propose we do this? I do not personally care for Consul and its baggage. Any ideas super-gurus?

**Comment by jokerbea** [comment]
I am also experiencing the same issue. Will this be fixed?

**Comment by alejandrox1** [comment]
For anyone landing here: https://www.terraform.io/upgrade-guides/0-9.html#remote-state
