### ISSUE TITLE
Error when using a data resource as input for a provider

### ISSUE THREAD

**Issue by MattiasGees** [hashicorp/terraform#12775]
### Terraform Version
v0.9.0

### Affected Resource(s)
- data.terraform_remote_state
- provider.mysql

### Terraform Configuration Files
```hcl
variable "aws_region" {
  default = "eu-west-1"
}

provider "aws" {
  region = "${var.aws_region}"
}

data "terraform_remote_state" "static" {
  backend = "s3"

  config {
    bucket = "terraform-state"
    key    = "static/main"
    region = "${var.aws_region}"
  }
}

provider "mysql" {
  endpoint = "127.0.0.1:3306"
  username = "root"
  password = "${data.terraform_remote_state.static.aurora_root_password}"
}
```

### Expected Behavior
I can use a data resource for input into a provider

### Actual Behavior
At this moment I am getting an error on when the provider tries to login.

I export my root password in my remote state in an encrypted s3 bucket. I try to retrieve that password and use it in my mysql provider to login. I get the error that I don't set my password correctly.

```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.static: Refreshing state...
Error running plan: 1 error(s) occurred:

* provider.mysql: Received #1045 error from MySQL server: "Access denied for user 'root'@'10.11.0.133' (using password: NO)"
```

### Steps to Reproduce
Have an running mysql server locally or through ssh tunnel  + already have a remote state
1. `terraform plan`

### References
This looks really similar to https://github.com/hashicorp/terraform/issues/2751

**Comment by mcanevet** [comment]
I think this is related to https://github.com/hashicorp/terraform/issues/11264

**Comment by MattiasGees** [comment]
That is indeed possible. Just tried it with `-input=false` and now it works.

**Comment by apparentlymart** [comment]
This does indeed look the same as #11264. Sorry about the confusing result here! I'm going to close this one just to consolidate the discussion over in that other issue.
