### ISSUE TITLE
-var-file does not import files from another folder

### ISSUE THREAD

**Issue by johnt337** [hashicorp/terraform#12771]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

`Terraform v0.8.8` and `Terraform v0.9.0`

### Affected Resource(s)
Please list the resources as a list:
- template_file
- null_resource
- local-exec

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

- render.tf
```hcl
data "template_file" "user-data" {
  template               = "${ file("${ path.module }/ignition.yaml.tpl") }"
  vars {
    var_volume_path      = "${ var.demo_instance["var_volume_path"] }"
    data_volume_path     = "${ var.demo_instance["data_volume_path"] }"
}

resource "null_resource" "generator" {
  triggers {
    template             = "${ md5(data.template_file.user-data.rendered) }"
  }

  provisioner "local-exec" {
    command              = "echo '${ data.template_file.user-data.rendered }' > ${ path.module }/ignition.yaml"
  }
}
```

- demo_vars.tf.json (abbreviated for relevance)
```json
{
  "variable": {
    "demo_instance":{
      "type":"map",
      "default":{
        "var_volume_path":"/dev/xvdd",
        "data_volume_path":"/dev/xvde"
      }
    }
  }
}
```

- ignition.yaml.tpl (abbreviated for relevance)
```yaml
---
ignition:
storage:
  disks:
  - device: "${var_volume_path}"
    wipe_table: true
    partitions:
    - label: varlibdocker
      number: 1
      start: 0
      size: 0
  - device: "${data_volume_path}"
    wipe_table: true
    partitions:
    - label: data
      number: 1
      start: 0
      size: 0
  filesystems:
  - mount:
      device: "${var_volume_path}1"
      format: ext4
      create:
        force: true
        options:
        - "-L"
        - VARLIBDOCKER
  - mount:
      device: "${data_volume_path}1"
      format: ext4
      create:
        force: true
        options:
        - "-L"
        - DATA
```
### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

Will add after creating the ticket to associate the issue number.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

When `-var-file=/path/to/file/demo_vars.tf.json` is passed to `terraform plan` or `apply`
It should find the file and load the variables.

```bash
$ make pre-render-ignition-yaml
# this it to avoid fuze failing because we have TF vars defined for paths in the file
cd infrastructure/templates/userdata && terraform apply -var-file=/Users/johnt/jvm-profiling-demo/infrastructure/demo_vars.tf.json
data.template_file.user-data: Refreshing state...
null_resource.generator: Refreshing state... (ID: 7562233543287676521)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

data_volume_path = /dev/xvde
file = /Users/johnt/jvm-profiling-demo/infrastructure/templates/userdata/ignition.yaml
var_volume_path = /dev/xvdd
```

### Actual Behavior
What actually happened?

It fails to load the files and returns:

```bash
$ make pre-render-ignition-yaml
# this it to avoid fuze failing because we have TF vars defined for paths in the file
cd infrastructure/templates/userdata && terraform apply -var-file=/Users/johnt/jvm-profiling-demo/infrastructure/demo_vars.tf.json
module root: 3 error(s) occurred:

* output 'var_volume_path': unknown variable referenced: 'demo_instance'. define it with 'variable' blocks
* resource 'data.template_file.user-data' config: unknown variable referenced: 'demo_instance'. define it with 'variable' blocks
* output 'data_volume_path': unknown variable referenced: 'demo_instance'. define it with 'variable' blocks
make: *** [pre-render-ignition-yaml] Error 1
```
I can see the file exist at the location I am specifying:

```bash
$ ls -l /Users/johnt/jvm-profiling-demo/infrastructure/demo_vars.tf.json
-rw------- 1 johnt staff 839 Mar 14 19:58 /Users/johnt/jvm-profiling-demo/infrastructure/demo_vars.tf.json
```

I know the vars file has the correct format since it loads fine if I copy it to the local directory
where terraform is running from.

```bash
$ cp infrastructure/demo_vars.tf.json infrastructure/templates/userdata/
$ make pre-render-ignition-yaml
# this it to avoid fuze failing because we have TF vars defined for paths in the file
cd infrastructure/templates/userdata && terraform apply -var-file=/Users/johnt/jvm-profiling-demo/infrastructure/demo_vars.tf.json
data.template_file.user-data: Refreshing state...
null_resource.generator: Refreshing state... (ID: 7562233543287676521)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

data_volume_path = /dev/xvde
file = /Users/johnt/jvm-profiling-demo/infrastructure/templates/userdata/ignition.yaml
var_volume_path = /dev/xvdd
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Create the folders: `mkdir -p $PWD/jvm-profiling-demo/infrastructure/templates/userdata`
2. Copy the file snippets into their respective places: `vim $PWD/jvm-profiling-demo/demo_vars.tf.json`, `vim $PWD/jvm-profiling-demo/infrastructure/templates/userdata/render.tf`, & `vim $PWD/jvm-profiling-demo/infrastructure/templates/userdata/ignition.yaml.tpl`
3. Change to the userdata folder: `cd $PWD/jvm-profiling-demo/infrastructure/templates/userdata`
4. `terraform apply -var-file=<your_path>/jvm-profiling-demo/infrastructure/demo_vars.tf.json`
5. Copy the vars file to the same folder as the terraform file: `cp <your_path>/jvm-profiling-demo/infrastructure/demo_vars.tf.json <your_path>/jvm-profiling-demo/infrastructure/templates/userdata`
6. Re-run terraform apply: `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

- I am running this with a Makefile wrapper, however if I run it without the wrapper the same results are exhibited.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here?

N/A

**Comment by johnt337** [comment]
Trace - https://gist.github.com/johnt337/92e5794f3008c85354c6e0bc58a36d1f

**Comment by jbardin** [comment]
Hi @johnt337,

Sorry about the confusion here. The file `demo_vars.tf.json` isn't a vars file, it's part of your configuration which happens to be in json, and must reside in the same directory. A vars file can't declare new variables in your config, it can only assign values to existing variables. 

The equivalent vars file in json would look like:

```
{
  "foo": {
    "var_volume_path": "/dev/xvdd",
    "data_volume_path": "/dev/xvde"
  }
}
```

Or in HCL

```
"foo" {
  var_volume_path  = "/dev/xvdd"
  data_volume_path = "/dev/xvde"
}
```

**Comment by johnt337** [comment]
OK so if I treat it as a module import I should be able to work around this correct?
