### ISSUE TITLE
-var-file documentation is wrong about default

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#1280]
The docs on -var-file=... say:

"If "terraform.tfvars" is present, it will be automatically loaded if this flag is not specified."

However, it appears that terraform.tfvars is always loaded, even if -var-file is supplied.

This is in version 0.3.7.

**Comment by radeksimko** [comment]
I think it should be fixed in the documentation, but the functionality should remain as is - autoloading all the files makes sense to me.

**Comment by mitchellh** [comment]
Fixed docs. Thanks.
