### ISSUE TITLE
provider/circonus: Change check fields from TypeSet to TypeList

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#12808]
The main reason for this change is the following test failure:

```
=== RUN   TestAccCirconusCheckCloudWatch_basic
--- FAIL: TestAccCirconusCheckCloudWatch_basic (3.22s)
    testing.go:268: Step 0 error: Check failed: Check 5/191 error: circonus_check.rds_metrics: Attribute 'cloudwatch.1637274235.dimmensions.%' not found
```

but generally speaking if there's `TypeSet` which is limited to max. 1 item there's (almost) never a reason to keep it as set as there's nothin to sort - no benefit from the hash.

Such change will require state migration also, because some users may already have existing resources in the state under a hash and we'll need to migrate to the new schema (i.e. TypeList, idx = `0`).

cc @sean-

**Comment by sean-** [comment]
@radeksimko I'm working on fixing this test so that it passes testing in TC.  Yesterday we added this to TC, fixing the TC checks is next.

FWIW, the reason for the `TypeSet` here is schema enforcement on arbitrary attributes.  I didn't use a list because the key/value pairs shouldn't have a set order, therefore a `TypeSet` was used.

**Comment by radeksimko** [comment]
@sean- I believe you can enforce schema in `TypeList` too - it allows you to specify `Elem` exactly the same way as `TypeSet` does. The only difference is that you have numerical zero-based indexes, instead of `Set` function calculating the hash/index.

See [this example](https://github.com/hashicorp/terraform/blob/3ac05a539bc4d02b1925e0704d0714d2e8723bcc/builtin/providers/aws/data_source_aws_alb_listener.go#L39-L54).

> because the key/value pairs shouldn't have a set order

that would be the right decision under normal circumstances - all the reasoning you mentioned makes sense, but if there's ever going to be max. of 1 item, there is nothing to sort and therefore no reason to deal with ordering.
