### ISSUE TITLE
AWS Network ACLs Issue Version 0.9.0

### ISSUE THREAD

**Issue by mqasim1983** [hashicorp/terraform#12809]
Hi there,

Network ACLS not working with above-mentioned version and perfectly works fine with Terraform v0.8.8

**It may be due to the following added in version 0.9.0**
provider/aws: Add support for IPv6 to aws_security_group_rule (#12645)
provider/aws: Add IPv6 Support to aws_route_table (#12640)
provider/aws: Add support for IPv6 to aws_network_acl_rule (#12644)
provider/aws: Add support for IPv6 to aws_default_route_table (#12642)
provider/aws: Add support for IPv6 to aws_network_acl (#12641)
provider/aws: Add support for IPv6 in aws_route (#12639)
provider/aws: Add support for IPv6 to aws_security_group (#12655)

### Affected Resource(s)

- aws_network_acl

### Sample Config perfectly working with 0.8.8 and not with 0.9.0

    resource "aws_network_acl" "worker" {
    vpc_id = "${var.vpc_id}"
    subnet_ids = ["${aws_subnet.worker.*.id}"]

    ingress {
      protocol   = -1
      rule_no    = 100
      action     = "allow"
      cidr_block = "0.0.0.0/0"
      from_port  = 0
      to_port    = 0
    }

    egress {
      protocol   = -1
      rule_no    = 100
      action     = "allow"
      cidr_block = "0.0.0.0/0"
      from_port  = 0
      to_port    = 0
    }

    tags {
        Name = "${var.name} Worker Network ACL"
    }
}

### Terraform Apply Sample

* aws_network_acl.xxxx: Error creating ingress entry: InvalidParameterValue: CIDR block  is malformed
	status code: 400, request id: xxxxxxxxxxxxx
* module.network-us-east-1.aws_network_acl.public: 1 error(s) occurred:

**Comment by stack72** [comment]
Hi @mqasim1983 

Apologies for this error - we believe this has been fixed as part of #12735 and will be going out as part of Terraform 0.9.1 - coming soom:tm: to a browser near you!

Thanks

Paul

**Comment by mqasim1983** [comment]
Thanks
