### ISSUE TITLE
User input variables ignored

### ISSUE THREAD

**Issue by mgood** [hashicorp/terraform#1282]
Variables from the user input do not appear to be applied to the config prior to validation, so a validation error is still reported:

```
$ terraform apply
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value: ap-northeast-1

There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * provider.aws: "region": required field is not set
```

A similar issue #736 was previously reported and fixed where the user was not even asked for input. I can verify that the intended behavior was working in version 0.3.7, but now with the current master I get the error above.

This might be related to other config issues like #1186 and #1142 where configuration within a module is not being recognized.

**Comment by mitchellh** [comment]
Confirmed. Looking at it now.

**Comment by mgood** [comment]
Thanks, that worked.
