### ISSUE TITLE
Terraform does not handle 404 on Azure Resource Group.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#12826]
### Terraform Version
v0.8.6

### Affected Resource(s)
- azurerm_resource_group

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "main" {
  name     = "retrytest"
  location = "westus"
}
```

### Output
```
network-azure $ terraform apply
module.vpc.azurerm_resource_group.main: Creating...
  location: "" => "westus"
  name:     "" => "vpc-foundation"
  tags.%:   "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* azurerm_resource_group.main: Error reading resource group: ResourceGroupNotFound (404) - Resource group 'vpc-foundation' could not be found.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
network-azure $
```

### Expected Behavior
Terraform should treat the 404 as a transient error and backoff and retry.

### Actual Behavior
apply failed.

### Steps to Reproduce
Error only happens sporadically. Repeat the below until you experience the error.
1. `terraform apply && terraform destroy -force`

**Comment by steakfest** [comment]
I'm seeing similar behavior with one of my own TF templates.

**Comment by camilhord** [comment]
Same behavior with different resources, like azurerm_sql_server or azurerm_sql_firewall_rule.This is happening in 0.9.6

**Comment by camilhord** [comment]
Same behavior with different resources, like azurerm_sql_server or azurerm_sql_firewall_rule. And, it's happening in 0.9.6. Isn't this the same as https://github.com/hashicorp/terraform/issues/9214?

**Comment by gcmalloc** [comment]
I can reproduce this with terraform `v0.10.7` and azurerm provider `0.2.2`, The error I have is:

```
* azurerm_availability_set.availability_set: compute.AvailabilitySetsClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '<redacted>' could not be found."
```
But the resource was already created before.

The output of `terraform providers` gives me:

```
.
├── provider.azurerm ~> 0.2.2
└── provider.template
```
Any idea why this may happen again ?

**Comment by ziurjam** [comment]
I am having the same issue. Any ideas?

**Comment by granadacoder** [comment]
Future readers.

I had accidentally copied/pasted my 

resource "azurerm_resource_group" "myTag" {
}

so it was in my .tf file TWICE.

That is not the issue itself.

But I ~~think~~ this somehow corrupted my

terraform.tfstate
and
terraform.tfstate.backup 

files.

So I deleted both of those files (the tfstate ones)........and reran my script.  (Obviously i removed my accidental (second copy of) "azurerm_resource_group" )

No 404 errors !

**Comment by rifaterdemsahin** [comment]
@granadacoder thanks. After deletion, it started working. Doing immutable infrastructures don't need this state files. I guess they can cause more harm than good?

**Comment by tombuildsstuff** [comment]
@rifaterdemsahin I've commented on the other issue, but the State file's required within Terraform to track what's provisioned, else it's not possible to know what's been provisioned/track changes.
