### ISSUE TITLE
provider/aws aws_network_acl resource incorrectly handling default IPv6 ingress/egress rules

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform#12831]
```
terraform -v
Terraform v0.9.1-dev (14e07b136e087150233352e05d2322d0cda22e6e)
```
The `aws_network_acl` is incorrectly handling default IPv6 ingress/egress rules.

Quoting [the AWS documentation](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_ACLs.html#default-network-acl):
*If you create a VPC with an IPv6 CIDR block or if you associate an IPv6 CIDR block with your existing VPC, we automatically add rules that allow all IPv6 traffic to flow in and out of your subnet.*

The corresponding IPv4 default rule (rule number 32767) is removed from `ingress` and `egress` counts and state but the IPv6 default rule (rule number 32768) is not.

**Comment by stack72** [comment]
Closed via #12835
