### ISSUE TITLE
Terraform 0.9.0 panic using NS1 provider

### ISSUE THREAD

**Issue by kian** [hashicorp/terraform#12833]
Hello,

I'm attempting to use the new NS1 provider with Terraform 0.9.0 but the process crashes.

```
panic: runtime error: integer divide by zero
```

### Terraform Version

```
$ terraform --version
Terraform v0.9.0
```

### Affected Resource(s)

 - `ns1_zone`

May affect other resources too but I can't create the zone initially, so not sure.

### Terraform Configuration Files

**foo.tf:**
```hcl
provider "ns1" {
  apikey   = "${var.ns1_apikey}"
  endpoint = "${var.ns1_endpoint}"
}

resource "ns1_zone" "placelocaldevcom" {
  zone    = "placelocaldev.com"
  ttl     = 3600
  refresh = 3600
  retry   = 600
  expiry  = 604800
  nx_ttl  = 3600
}
```

**terraform.tfvars:**

```
ns1_apikey = "<redacted>"
```

**variables.tf**
```
variable "ns1_apikey" {}

variable "ns1_endpoint" {
  type    = "string"
  default = "https://api.nsone.net/v1"
}
```

### Debug Output

Created with `export TF_LOG=DEBUG; export TF_LOG_PATH=/tmp/tf-debug.log`.

https://gist.github.com/kian/6491f1b27dffb6e16137703e1febe43b

### Panic Output

`crash.log` contents: https://gist.github.com/kian/1fca5151447a3afef7f15dc861edc5f8

### Expected Behavior

The zone exists, so I'd expect a no-op but anything other than a crash.

### Actual Behavior

Crash.

### Steps to Reproduce

1. `terraform apply`

### Misc

Happy to help test patches.

**Comment by kian** [comment]
A bit more information... I was curious if this was the result of trying to manage/create a zone that already exists in NS1 (but not Terraform), however it seems using a completely new zone still results in crash.  Here's a simplified example:

```
resource "ns1_zone" "foobar" {
  zone    = "foobar.com"
  ttl     = 3600
  refresh = 3600
  retry   = 600
  expiry  = 604800
  nx_ttl  = 3600
}

resource "ns1_record" "example" {
  zone   = "foobar.com"
  domain = "example.foobar.com."
  type   = "A"
  answers = {
    answer = "173.193.36.54"
  }
}
```

**Comment by pashap** [comment]
@kian thanks for posting this, i somehow never implemented any checks around the ns1 api key. I believe that PR fixes this. But please lmk if its still a problem
