### ISSUE TITLE
Feature-request: state file containing creation date/time

### ISSUE THREAD

**Issue by MansM** [hashicorp/terraform#12848]
I would like to see in the state file for a resource the creation date/time.

This so I can query my resources to find old instances and have them redeployed.

**Comment by mitchellh** [comment]
We've talked about this before (and agreed) so I believe that there is an enhancement request for this. We actually talked about taking it one step further and exposing it as an interpolation too so that resources can use this!

**Comment by red8888** [comment]
I just created an issue related to this: https://github.com/hashicorp/terraform/issues/18366

Sorry didn't see this first. So its been over a year and I didn't see anything in the docs about this, was that enhancement not rolled out? In my issue what im looking for is something similar to how in cloudformation you can do describe-stack and get the creation time of a whole stack
