### ISSUE TITLE
Data source not ready when consumed in a provider block

### ISSUE THREAD

**Issue by mobrien** [hashicorp/terraform#12841]
### Terraform Version
Using version 0.9.1

### Affected Resource(s)
* provider
* terraform_remote_state

### Terraform Configuration Files
```hcl
data "terraform_remote_state" "accepter" {
    backend = "local"
    config {
        path = "../../central/terraform.tfstate"
    }
}

data "terraform_remote_state" "requester" {
    backend = "local"
    config {
        path = "../../staging/terraform.tfstate"
    }
}

provider "aws" {
    # alias      = "accepter"
    access_key = "${data.terraform_remote_state.accepter.key}"
    secret_key = "${data.terraform_remote_state.accepter.secret}"
    # access_key = "....."
    # secret_key = "....."
    region     = "us-east-1"
}

data "aws_vpc" "accepter" {
    # provider = "aws.accepter"
    id = "${data.terraform_remote_state.accepter.vpc}"
}

```

### Debug Output
Error refreshing state: 1 error(s) occurred:

* data.aws_vpc.accepter: 1 error(s) occurred:

* data.aws_vpc.accepter: data.aws_vpc.accepter: InvalidVpcID.NotFound: The vpc ID 'vpc-967321f0' does not exist
	status code: 400, request id: 9e406ad1-360d-4fc0-8ad7-63b8720dbfb6

### Expected Behavior
Expect to be able to read the aws_vpc using a provider with key and secret from a local remote data source. The remote data source contains the terraform.tfstate from an account creation on another account that output a "key" and "secret" into the state file. We want to consume these fields in the script above.

### Actual Behavior
Fails when reading: data.terraform_remote_state.accepter.key, but works when the key and secret are hard coded in the provider block.

### Steps to Reproduce
1. `terraform apply`

To make it work, hard code credentials.

### Important Factoids
It seems the data source is not ready when the provider is parsed. If I output the key and secret from the data source, they are output correctly.

**Comment by apparentlymart** [comment]
Hi @mobrien! Sorry this isn't working as expected.

Could you try running `terraform apply` with the additional argument `-input=false` and see if that makes it work? If so, you've likely hit the same bug as described in #11264, and that argument is the workaround for the moment until we find a proper solution.

**Comment by mobrien** [comment]
Yes, that workaround works. I had to remove the terraform.tfstate to get it to fail the 2nd time.

What does -input=false do, and is it safe to use in other use cases?

So the work around works and 0.9.1 still has the issue.

My test case provokes it easily and consistently.

Interestingly, this may manifest in occasionally getting incorrect data sources which depending on the timing may make a run fail. Very hard to debug that.

**Comment by apparentlymart** [comment]
I wrote some more details on this in #11264, but to summarize: for exposition reasons, Terraform has a feature where it will prompt interactively for config values on providers to allow new users to succeed with basic configurations that lack full provider configs, but this mechanism fails if the provider config is dynamic.

`-input=false` disables this mechanism. This is safe since it just replaces the interactive prompts with validation error messages. The most likely solution to this bug is to simply act as if this argument is present whenever dynamic provider config is used.

I'm going to close this issue to consolidate discussion in the other one. Thanks for reporting this!
