### ISSUE TITLE
Terraform Unable to Read State Files

### ISSUE THREAD

**Issue by ptarpan** [hashicorp/terraform#12857]
It appears that Terraform is unable to read a (newly created or existing) state file, hence causing major problems when updating a resource. Typically, we use a Makefile to deploy but the same result is being produced when invoking the Terraform binary directly. I am providing an example below, let me know if you need more info to troubleshoot. 

### Terraform Version
v0.8.8.

### Affected Resource(s)
- VPC

### Makefile Example 
``` 
STATE_DIR = _state

# Clean terraform modules
clean:
	rm -rf ./.terraform

# Check if the required variables have been passed
.check-env:
	@if test "$(REGION)" = "" ; then echo "REGION not set"; exit 1; fi
	@if test "$(ENV)" = "" ; then echo "ENV not set"; exit 1; fi
	@if test "$(ENV_TYPE)" = "" ; then echo "ENV_TYPE not set"; exit 1; fi
	@if test "$(OWNER)" = "" ; then echo "OWNER not set"; exit 1; fi

plan: .check-env
	terraform get
	terraform plan -state=$(STATE_DIR)/$${REGION}-$${ENV}-$${ENV_TYPE}.tfstate \
		-var region="$${REGION}" -var env="$${ENV}" -var env-type="$${ENV_TYPE}" -var owner="$${OWNER}" \
		$${ARGS}

# Deploy resources. ARGS is an env. variable
apply: .check-env
	terraform get
	terraform apply -state=$(STATE_DIR)/$${REGION}-$${ENV}-$${ENV_TYPE}.tfstate \
		-var region="$${REGION}" -var env="$${ENV}" -var env-type="$${ENV_TYPE}" -var owner="$${OWNER}" \
		$${ARGS}

# Destroy resources. ARGS is an env. variable
destroy: .check-env
	terraform get
	terraform destroy -state=$(STATE_DIR)/$${REGION}-$${ENV}-$${ENV_TYPE}.tfstate \
		-var region="$${REGION}" -var env="$${ENV}" -var env-type="$${ENV_TYPE}" -var owner="$${OWNER}" \
		$${ARGS}
```

### Terraform Configuration File
```hcl
variable "region" {}
variable "env" {}
variable "env-type" {}

# Shared VPC
module "vpc-shared" {
  source              = "github.com/terraform-community-modules/tf_aws_vpc"
  name                = "${var.env}-${var.env-type}"
  cidr                = "172.31.96.0/20" 
  private_subnets     = ["172.31.104.0/23","172.31.106.0/23","172.31.108.0/23"]
  public_subnets      = ["172.31.96.0/23","172.31.98.0/23","172.31.100.0/23"]  
  availability_zones  = ["us-west-2a","us-west-2b","us-west-2c"]
}
```

### Debug Output
When invoking the Terraform binary directly, here is the error that gets thrown: 
"Error reading local state: Decoding state file version failed: invalid character 'f' in literal true (expecting 'r')." 
When using a Makefile, Terraform says that a new VPC will get created every time we "plan" like its starting from scratch and ignoring the State file. 

### Expected Behavior
A VPC should be created/updated.

### Actual Behavior
In the first "apply" the VPC gets created but if anything is updated in the module, the above error is produced. 

### Steps to Reproduce
Invoke the Terraform binary directly by running the following commands:
1. `terraform plan -target=module.vpc-shared`
2. `terraform apply -target=module.vpc-shared` 
3. `terraform plan -target=module.vpc-shared`  

Or use the Makefile above and call the `plan` target first then an `apply` then a `plan` like so: 

`ENV=test ENV_TYPE=test OWNER=admin REGION=us-west-2 ARGS='-target=module.vpc-shared' make plan`
`ENV=test ENV_TYPE=test OWNER=admin REGION=us-west-2 ARGS='-target=module.vpc-shared' make apply`
`ENV=test ENV_TYPE=test OWNER=admin REGION=us-west-2 ARGS='-target=module.vpc-shared' make plan`

**Comment by jbardin** [comment]
Hi @ptarpan,

That error is from Terraform attempting to read an invalid state file, probably in the default location of `./terraform.tfstate`, and probably starting with the characters `tf`. Removing the invalid file will fix the problem. I'm unable to replicate the creation of this file from your script here, so it may be an artifact from a previous mis-typed command, or another piece of a script or Makefile. 

Terraform 0.9 will no longer check the default state location when when a state path is provided, so the invalid file wouldn't effect the latest version.

**Comment by riponbanik** [comment]
I am still finding it in windows. Terraform version 0.9.6

terraform plan -out c:\temp\output.tfstate
terraform plan -state c:\temp\output.tfplan
Error loading state: Decoding state file version failed: invalid character 'f' in literal true (expecting 'r')

**Comment by apparentlymart** [comment]
Hi @riponbanik,

It looks like things are backwards in your command line there... you've passed a `.tfstate` file for plan output and a `.tfplan` file as a state. In normal use it should not be necessary to use the `-state` argument to `plan`. Instead the workflow looks like this:

```
terraform plan -out=c:\temp\output.tfplan
terraform apply c:\temp\output.tfplan
```

If it still seems like things are not working correctly, please open a new issue since this seems to be a different problem than the one reported here.

**Comment by riponbanik** [comment]
I have actually both .tfplan and. tfstate as extension for output but result is the same.  Looks like some formating issue in windows,  will open a new issue.
