### ISSUE TITLE
State environments not working in 0.9.1

### ISSUE THREAD

**Issue by jamtur01** [hashicorp/terraform#12853]
### Terraform Version

0.9.1

### Affected Resource(s)

state environments.

### Expected Behavior

When I run `terraform env list` I expect to see the `default` environment listed.

I have no other state environments created.

State environment creation is also not working using `terraform env new test`

### Actual Behavior

1. Listing.

```
$ terraform env list 
named states not supported
```

2. Creating.

```
terraform env new test
named states not supported
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform env list`

**Comment by oyerli** [comment]
Which backend do you use for the state storage?

**Comment by pmyjavec** [comment]
I'm seeing this behaviour using the `S3` backend.

**Comment by fbrnc** [comment]
I can confirm the same behaviour with the Artifactory backend.

**Comment by sbutler** [comment]
Confirming with the S3 backend. No previous remote state was used, nor local state imported.

**Comment by jamtur01** [comment]
The S3 backend also.

**Comment by tom-schultz** [comment]
If you dig through the code you will see that Consul appears to be the only remte backend supporting environments.

**Comment by sysadmiral** [comment]
I think this is the same issue I have raised here: #12768

**Comment by pmyjavec** [comment]
@tom-schultz, I expected this might be the case as soon as I saw the error, although I didn't have time to investigate. 

It's a shame that this wasn't mentioned in the docs or the announcement, if it turns out this is simply a currently "unsupported" feature.

**Comment by jbardin** [comment]
Hi Everyone,

Sorry this isn't as clear as it could be in the docs yet. I think the supported backends may have only been mentioned in the release announcement. 

I'm going to close as as this is the expected behavior, and there is already an issue open for supporting named states in S3.

**Comment by jamtur01** [comment]
Are the docs going to be updated? That would seem to be pretty critical.

**Comment by tomstockton** [comment]
> Are the docs going to be updated? That would seem to be pretty critical.

Agree, just ran into this issue.  Would be nice to have known from the docs that it wasn't going to work.

**Comment by aholbreich** [comment]
@jbardin any chance to enable it for gce?
