### ISSUE TITLE
Documentation on backends/types/s3 not up to date?

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#12874]
https://www.terraform.io/docs/backends/types/s3.html

This mentions terraform remote state with no notice of deprecation. I was trying to upgrade from 0.8 to 0.9 and it's very unclear what is and isn't deprecated from there.

Same here:
https://www.terraform.io/docs/providers/terraform/d/remote_state.html

It'd be good to have a notice on there at least.

**Comment by mitchellh** [comment]
That resource isn't deprecated and is still a way to access remote state (which is a section of remote backends). This is correct and up to date!
