### ISSUE TITLE
aws/provider: Add support for OpsWorks

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1287]
http://aws.amazon.com/opsworks/details/

Some people may prefer to build their infrastructure using the higher level approach and I think that Terraform should respect that and help with that task.

http://docs.aws.amazon.com/cli/latest/reference/opsworks/index.html

It may be overly complicated to support custom layers, but Terraform could at least initially support the predefined layers:

> **Application Layers**: Ruby on Rails, PHP, Node.js, Java, and Nginx
> **Data Layers**: MySQL and Memcached
> **Utility Layers**: Ganglia and HAProxy

**Comment by phinze** [comment]
Hey there - we're consolidating Requests for AWS API Coverage over in the spreadsheet linked at #28 - head over there to record your username on what you'd like us to prioritize next!
