### ISSUE TITLE
aws_iam_role_policy "name": required field is not set

### ISSUE THREAD

**Issue by n1tr0g** [hashicorp/terraform#12876]
Hi there,

### Terraform Version
terraform -v
Terraform v0.9.0

### Affected Resource(s)
- aws_iam_role_policy

### Terraform Configuration Files
```hcl
resource "aws_iam_role_policy" "s3ServerPolicy" {
  name_prefix = "${var.hostname}"
  policy      = "${data.aws_iam_policy_document.S3BackupAccess.json}"
  role        = "${aws_iam_role.role.id}"
}
```

### Debug Output
https://gist.github.com/n1tr0g/5314fe2bda5c70c043f98a88ba9c1e06

### Expected Behavior
When trying to run `terraform plan` I was expecting that the plan will show the policy creation, however I get a unexpected error.

### Actual Behavior
I get the following error:

```
* module.server.aws_iam_role_policy.s3ServerPolicy: "name": required field is not set
* module.server.aws_iam_role_policy.s3ServerPolicy: : invalid or unknown key: name_prefix
```

Based on the [documentation](https://www.terraform.io/docs/providers/aws/r/iam_role_policy.html) `name` and `name_prefix` is optional, however the error implies that `name` is required and `name_prefix` is invalid.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Running on MAC OS

**Comment by stack72** [comment]
Hi @n1tr0g 

The work for name_prefix was not added until [0.9.1](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#091-march-17-2017) I'm afraid

Therefore, to take advantage of this feature, you will need to upgrade 

Sorry for the confusion here

Paul
