### ISSUE TITLE
Documentation for AWS_SQS_QUEUE_POLICY typo

### ISSUE THREAD

**Issue by ryno75** [hashicorp/terraform#12885]
### Terraform Version
Latest/Any

### Affected Resource(s)
Please list the resources as a list, for example:
- documenation for aws_sqs_queue_policy https://www.terraform.io/docs/providers/aws/r/sqs_queue_policy.html

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Documentation should read:
`queue_url - (Required) The URL of the SQS Queue to which to attach the policy`

### Actual Behavior
Documentation has typo (SNS instead of SQS):
`queue_url - (Required) The URL of the SNS Queue to which to attach the policy`

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
N/A

**Comment by stack72** [comment]
Closed via #12886
