### ISSUE TITLE
Include auto scale settings for Azure VM scale sets

### ISSUE THREAD

**Issue by tonipepperoniuk** [hashicorp/terraform#12889]
Would it be possible to include support for Azure VM auto scale rules in Terraform? I'm able to deploy scale sets but it would be excellent to be able to set autoscale rules using Terraform. I've seen this mentioned a couple of times with regards to App Gateway but I'd like to request general support for autoscale settings.

**Comment by stack72** [comment]
Hi @tonipepperoniuk 

Thanks for the request here - could you link us to some documentation from Azure on what you need added or describe what you think the UX would be for it?

This would help us get it planned

thanks

Paul

**Comment by tonipepperoniuk** [comment]
Thanks for the quick response Paul. There is Azure documentation [here](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-windows-autoscale?toc=%2fazure%2fmonitoring-and-diagnostics%2ftoc.json) describing autoscale using ARM templates. Looking at the Terraform scale set documentation, I can't see any option to set autoscale rules. It would be really useful to be able to set rules based on different metrics such as CPU utilisation.

Thanks
Anthony

**Comment by stack72** [comment]
Do you think a resource of it's own would be useful for this?

i.e. azurerm_virtual_machine_scale_set_rule

And then you could specify multiple rules as multiple resources?

**Comment by tonipepperoniuk** [comment]
That sounds like a really good idea! I had to think for a moment as I've only started using Terraform today but I'm pretty sure that would be really useful. Would you specify the scale set in such a resource and then apply the rule?

**Comment by stack72** [comment]
I think you would specify them as different resources but  the link would be the scaleset id

I'll have a look as to what we can do for this

**Comment by tonipepperoniuk** [comment]
Thanks Paul! Really appreciate it.

**Comment by StephenWeatherford** [comment]
@whiskeyjay is working on this.
