### ISSUE TITLE
Feature Request: add support for policyfiles to chef_node resource of chef provider

### ISSUE THREAD

**Issue by jugatsu** [hashicorp/terraform#12893]
It would be great if `chef_node` resource of `chef` provider also supports policyfiles arguments.
By comprasion, `chef` provisioner supports `policy_name` and `policy_group` arguments.

**Comment by navaati** [comment]
Yes please.
At the moment we provide the node attributes via the user data, but that mean that if we want to change the attributes for a node that trashes the user data, and hence provoke the re-creation of the machine.

We would like to create and manage the node with terraform and have the client connect to the chef-server to find a premade node with the right attributes, but we use policyfile.

Maybe we can put the policyname and policygroup in the normal attributes…

**Comment by navaati** [comment]
Ok, so I investigated a little bit and the problem is that the https://github.com/go-chef/chef library the provider uses does not support policies. I'm opening an issue to them.

**Comment by jugatsu** [comment]
https://github.com/go-chef/chef/issues/91
