### ISSUE TITLE
Variable interpolation doesnt work in provider

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#12890]
terraform 0.8.7

If I try and use variable interpolation in any resource provider attribute. ie:

```
data "aws_vpc" "me" {
    provider = "aws.${var.account_alias}"

    tags {
        Name = "me_vpc"
    }
}
```

This should work, however instead I get:

```
module dummy: provider alias must be defined by the module or a parent: aws.${var.account_alias}
```

(The resource is part of a module, which is why I am parameterising the provider...)

**Comment by snowsky** [comment]
@gtmtech could you please provide more contexts? I am not sure if I understand it correct.

**Comment by mitchellh** [comment]
Correct, the provider alias cannot contain interpolations currently. There is another issue tracking this but this is not allowed. We'll button up the validation.
