### ISSUE TITLE
Terraform 0.8.8+ now fails if role does not have ec2:ReplaceIamInstanceProfileAssociation

### ISSUE THREAD

**Issue by JPaulchell** [hashicorp/terraform#12898]
### Terraform Version
0.8.8 or greater

### Affected Resource(s)
-aws_instance

### Debug Output
status code: 403, request id: 02319da3-6e31-4fc3-b9db-7d1d66177193
* aws_instance.xxxx_yyyy.3: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 

### Expected Behavior
Versions 0.8.7 and earlier properly provisioned the EC2 instance with the provided IAM Role (iam_instance_profile).

### Actual Behavior
Terraform fails with code 403, unauthorized, since the role we are executing with is not granted the permission ec2:ReplaceIamInstanceProfileAssociation.  Previous to 0.8.8 we did not require this permission to assign an IAM role at provision.

### Steps to Reproduce
Easily reproduced:
1.  `create role with Deny on permission ec2:ReplaceIamInstanceProfileAssociation`
2. `terraform apply`

### Important Factoids
none

### References
none known

**Comment by rgs1** [comment]
just bumped into this with `0.9.0` as well -- looks like `ec2:ReplaceIamInstanceProfileAssociation` is being called even when it would be a no-op (i.e.: the right IAM role is already set).

**Comment by pantocrator27** [comment]
@JPaulchell I just ran into this issue as well ....

**Comment by danabr** [comment]
Seems to have been introduced with https://github.com/hashicorp/terraform/pull/11862.

**Comment by roolo** [comment]
This happens to me even when I create new resources. It seems to me creates the machine and then it tries to replace the roles.

**Comment by pantocrator27** [comment]
I would expect *maybe* the appropriate behavior would be to use the API call associated with ec2:ReplaceIamInstanceProfileAssociation so that the IAM role can be changed without instance replacement.  If that does not work, then Terraform should actually replace the instance and provision a new one with the correct IAM role.

**Comment by stack72** [comment]
Hi @JPaulchell 

Are you trying to create a new instance, make a change to an instance or is this happening on a plan of an existing setup?

Paul

**Comment by JPaulchell** [comment]
@stack72 - We were trying to create new instances (to stand up our Hashi Consul stack).  These are new EC2 instances - not changes to existing.  With this fatal error we can't even test changes to existing.
Deletion / Termination works fine.

**Comment by stack72** [comment]
Thanks for the help here @JPaulchell 

I just opened a PR that will fix this up when creating new instances! Found the issue :)

P.

**Comment by JPaulchell** [comment]
@stack72 Thanks.  Much appreciate the rapid triage and turn around!

**Comment by pantocrator27** [comment]
I am not sure this PR addresses this comment: https://github.com/hashicorp/terraform/issues/12898#issuecomment-288107529

**Comment by stack72** [comment]
@pantocrator27 we do not replace the instance anymore - we change the IAM role in place

**Comment by pantocrator27** [comment]
@stack72 what would be the harm in introspecting the AWS error if there is one for people that do not have permissions on ec2:ReplaceIamInstanceProfileAssociation and falling back on the previous behavior of instance replacement?  I feel that this only gets us half-way there ...

**Comment by roolo** [comment]
It would be really nice to have some kind of switch, no matter if in blueprint or in terminal with for example in-place change as default.
