### ISSUE TITLE
AWS VPC returns disassociated IPv6 CIDR block

### ISSUE THREAD

**Issue by steveh** [hashicorp/terraform#12895]
### Terraform Version
Terraform v0.9.1

### Affected Resource(s)
- aws_vpc

### Terraform Configuration Files
```hcl
resource "aws_vpc" "main" {
  assign_generated_ipv6_cidr_block = true
}

resource "aws_subnet" "public" {
  ipv6_cidr_block = "${cidrsubnet(aws_vpc.main.ipv6_cidr_block, 8, 1)}"
}
```

### Debug Output
`aws ec2 describe-vpcs`

```json
       {
            "VpcId": "vpc-123",
            "Ipv6CidrBlockAssociationSet": [
                {
                    "Ipv6CidrBlock": "2406:dead:beef:1e00::/56",
                    "AssociationId": "vpc-cidr-assoc-123",
                    "Ipv6CidrBlockState": {
                        "State": "disassociated"
                    }
                },
                {
                    "Ipv6CidrBlock": "2406:dead:beef:6b00::/56",
                    "AssociationId": "vpc-cidr-assoc-456",
                    "Ipv6CidrBlockState": {
                        "State": "associated"
                    }
                }
            ],
        },
```

### Expected Behavior
Terraform exports the first associated Ipv6CidrBlockAssociation as `aws_vpc.main.ipv6_cidr_block`.

### Actual Behavior
Terraform exports the first Ipv6CidrBlockAssociation to the subnet, which is disassociated and unusable.

### Steps to Reproduce
1. Associate a VPC with an IPv6 CIDR block
2. Disassociated that CIDR block
3. Associate a VPC with another IPv6 CIDR block (you'll get a different one, I think)

### Important Factoids
1. I originally associated and then disassociated the CIDR outside of Terraform.

**Comment by stack72** [comment]
Hi @steveh 

Thanks for the bug report here - nice find - PR incoming! Just running the tests

Paul
