### ISSUE TITLE
AWS CodeBuild Crash

### ISSUE THREAD

**Issue by AlexLast** [hashicorp/terraform#12914]
### Terraform Version
Terraform v0.9.0

### Affected Resource(s)
- aws_codebuild_project

### Terraform Configuration Files
I've removed some environment variables and other identifying parts

```hcl
provider "aws" {
  region = "${var.region}"
}

resource "aws_codebuild_project" "xyz_pipeline" {
  name          = "${var.pipeline_name}_xyz_pipeline"
  description   = "Pipeline to deploy XYZ"
  build_timeout = "45"
  service_role  = "${aws_iam_role.xyz_pipeline_role.arn}"

  source {
    type     = "GITHUB"
    location = "https://github.com/org/repo.git"

    auth {
      type     = "OAUTH"
      resource = "AWS CodeBuild"
    }
  }

  environment {
    compute_type = "BUILD_GENERAL1_SMALL"
    image        = "ubuntu:16.04"
    type         = "LINUX_CONTAINER"
  }

  artifacts {
    type = "NO_ARTIFACTS"
  }
}
```

### Debug Output
Removed identifying information
https://gist.github.com/AlexLast/32fcfa280eb898d83f5884bd00fc7b5a

### Panic Output
Removed identifying information
https://gist.github.com/AlexLast/2999ce487d14076e6e87c74454f58dfe

### Expected Behavior
The terraform created resources should be destroyed

### Actual Behavior
Nothing was destroyed and the crash occurred 

### Steps to Reproduce
1. `terraform destroy`

### Important Factoids
When creating a new CodeBuild project you can plan or destroy afterwards no problem, it seems the crash only occurs after running at least 1 build with the project and trying to destroy or plan after that.

**Comment by stack72** [comment]
Hi @AlexLast 

thanks for reporting this - I have just opened a PR that will fix this. Sorry if it has caused you some issues

Paul
