### ISSUE TITLE
config in json format (config.tf.json) does not work

### ISSUE THREAD

**Issue by jcortega** [hashicorp/terraform#12919]
### Terraform Version
Terraform v0.9.1

### Affected Resource(s)
- terraform config

### Terraform Configuration Files
```json
{
    "terraform": {
        "backend": {
            "s3": {
                "bucket": "jerome-dev",
                "key": "terraform-backend/1/1/tfstate",
                "region": "us-west-2",
                "lock_table": "DynamoDBTABLE"
            }
        }
    }
}
```

### Expected Behavior
s3 as backend should work

### Actual Behavior
- defaults to local backend instead of s3
- equivalent HCL form works

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create config.tf.json
2. `terraform init`
3. `terraform apply`

**Comment by mitchellh** [comment]
It works if you wrap the value of "terraform" and "backend" in array brackets `[`.

This is still a bug, but just noting you can get it to work now.

```
{
    "terraform": [{
        "backend": [{
            "s3": {
                "bucket": "jerome-dev",
                "key": "terraform-backend/1/1/tfstate",
                "region": "us-west-2",
                "lock_table": "DynamoDBTABLE"
            }
        }]
    }]
}
```
