### ISSUE TITLE
Propose s3 object data source

### ISSUE THREAD

**Issue by eredi93** [hashicorp/terraform#12926]
i need to access s3 objects json contents within my scripts, i store artefacts in s3.
i propose an s3 object data resource that parses the json content and makes it accessible in my terraform scripts, i'm currently using the external data source but having a data source would make it much nicer.

**Comment by apparentlymart** [comment]
Hi! Thanks for this request.

There is already a data source for retrieving S3 objects:
https://www.terraform.io/docs/providers/aws/d/s3_bucket_object.html

But it doesn't have a way to decide JSON yet. This sort of thing is currently a bit hard for Terraform to do because it wants to know the types of data during validation and JSON structure won't be known until the data is fetched.

With that said, I agree this would be useful and I would like to find a good way to make it work.

**Comment by eredi93** [comment]
we could have an argument `data_type` and accept `text` or `json` with the text data_type it would have the current behaviour if is set json it would try to parse it once fetched and fail if the format does not match.
unfortunately my golang/tf-plugins knowledge is not great and i don't really know if this is even possible. hopefully, I get some time to play around with them soon 😅

**Comment by eredi93** [comment]
i saw that [jsonencode](https://www.terraform.io/docs/configuration/interpolation.html#jsonencode_item_) exists, could be enough to have a `jsondecode` function to solve my problem

**Comment by gnarea** [comment]
I'm using an [external data source](https://www.terraform.io/docs/providers/external/data_source.html) as a workaround:

```hcl
data "external" "secrets" {
  program =
    ["aws", "s3", "cp", "s3://bucket-name/object.json", "-"]
}
```

**Comment by eredi93** [comment]
for the moment i'm using that too. but we are assuming that the awscli is installed on the host.
Is a dirty hack that i'd love to avoid

**Comment by apparentlymart** [comment]
Hmmm... doesn't that `external` data resource just do the same thing as [the `s3_bucket_object` data source](https://www.terraform.io/docs/providers/aws/d/s3_bucket_object.html) I mentioned above? I thought the main request here was the ability to decode the result from JSON and get at the structure within, which is the part that presents technical challenges today.

**Comment by eredi93** [comment]
i need to access data with in the json object, that work around works when it does not with the the s3_bucket_object data source

**Comment by apparentlymart** [comment]
Oh, clever! You're using the fact that the external data source itself expects JSON to parse it.

That's a cool workaround. Note, though, that the external data source only supports objects with string keys, so it'll fail if you have a complex, mixed data structure.
