### ISSUE TITLE
Pagerduty provider does not support email management rules

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/terraform#12925]
On the `pagerduty_service_integration` when choosing the `generic_email_inbound_integration` integration type, there is no option to configure the email management rules so it defaults to "Open a new incident for each trigger email" which results in noisy pagers.

![](http://drops.articulate.com/xHPp/2zXtiiiH+)

**Comment by lisat059** [comment]
Hi! I'm on the Support team at PagerDuty. If you select the option `Create and resolve incidents based on custom rules`, you can create custom rules for triggering and resolving events. We also have this Knowledge Base article that might help you: https://support.pagerduty.com/hc/en-us/articles/202830400-Trigger-and-resolve-alerts-with-email-management-rules. If you have any questions, or additional feedback, feel free to email support@pagerduty.com. Cheers!

**Comment by fromonesrc** [comment]
Hi @lisat059 thanks for the info. I can (and do) handle that via the UI but would like to automate that in Terraform.

**Comment by lisat059** [comment]
@fromonesrc I will go ahead and file a feature request for you! If you have any additional feedback, feel free to email support@pagerduty.com. :)

**Comment by heimweh** [comment]
Hi @lisat059, 

I started working on this but noticed that this feature is only documented in the v1 API reference and it hasn't been implemented in the client library yet. The Terraform provider is using the v2 API. Are there any differences between v1 & v2 for the email management part?

**Comment by iancward** [comment]
I'm not sure if this is the right place or if another issue would be reasonable, but it appears that Terraform does not have the ability to manage event rules for API-based integrations. We have a few rules that allow us to map inbound alert priority to PagerDuty's incident priority, and we'd like to manage this via terraform, mainly so that we don't forget that it's there (the configuration is not exactly blatant in the UI).

**Comment by quaeritate** [comment]
> Hi @lisat059,
> 
> I started working on this but noticed that this feature is only documented in the v1 API reference and it hasn't been implemented in the client library yet. The Terraform provider is using the v2 API. Are there any differences between v1 & v2 for the email management part?

The v2 API can do the custom email management now.
