### ISSUE TITLE
Terraform 0.8.8 fails when iam_instance_profile used

### ISSUE THREAD

**Issue by sbatchu0108** [hashicorp/terraform#12927]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
- aws_instance

### Debug Output
status code: 403, request id: 7a205582-0850-4fa1-8ed3-fe3c111d58c4
* aws_instance.xxxx_xxxx: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message:

### Expected Behavior
New ec2 instance must be launched with the specifed iam role.

### Actual Behavior
ec2 instance was created but errors triggered 
aws_instance.xxxxx: Still creating... (30s elapsed)
Error applying plan:
status code: 403, request id: 7a205582-0850-4fa1-8ed3-fe3c111d58c4
* aws_instance.xxxx_xxxx: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message:

### Steps to Reproduce
1. Create a role with readonly access to aws resources and access to s3 to read and write operations on the s3 bucket.
2. In aws_instance resource add " iam_instance_profile = "${var.InstanceProfile}""
3. Terraform plan output "Plan: 1 to add, 0 to change, 0 to destroy."
4. Terraform apply: Throws an error but ec2 instance was created with specified role.

### Important Factoids
none

### References
none

**Comment by stack72** [comment]
Hi @sbatchu0108 

i have just opened a PR that fixes this issue :) Sorry for nay issues it has caused you :(

Paul

**Comment by sbatchu0108** [comment]
Thanks @stack72
