### ISSUE TITLE
failure removing existing data source due to count

### ISSUE THREAD

**Issue by dmrzzz** [hashicorp/terraform#12935]
### Terraform Version
Terraform v0.9.1

### Affected Resource(s)
- data "aws_vpc_peering_connection"

### Terraform Configuration Files
prep/main.tf:
```hcl
provider "aws" {
  region = "us-east-2"
}

# create two VPCs and a peering connection

resource "aws_vpc" "vpc1" {
  cidr_block = "192.168.1.0/24"
}

resource "aws_vpc" "vpc2" {
  cidr_block = "192.168.2.0/24"
}

resource "aws_vpc_peering_connection" "pcx" {
  vpc_id      = "${aws_vpc.vpc1.id}"
  peer_vpc_id = "${aws_vpc.vpc2.id}"
  auto_accept = true
}

output "vpc1_id" {
  value = "${aws_vpc.vpc1.id}"
}

output "pcx_id" {
  value = "${aws_vpc_peering_connection.pcx.id}"
}
```

test/main.tf:
```hcl
variable "vpc1_id" {}

variable "pcx_ids" {
  type        = "list"
  description = "Optional list of existing VPC Peering Connections (e.g. pcx-abcd1234) to use in routing tables"
  default     = []
}

provider "aws" {
  region = "us-east-2"
}

# look up VPC

data "aws_vpc" "vpc" {
  id = "${var.vpc1_id}"
}

# create Route Table

resource "aws_route_table" "rtb" {
  vpc_id = "${data.aws_vpc.vpc.id}"
}

# routes for VPC Peering Connections (if any)

data "aws_vpc_peering_connection" "pcx" {
  count = "${length(var.pcx_ids)}"
  id    = "${var.pcx_ids[count.index]}"
}

resource "aws_route" "pcx" {
  count                     = "${length(var.pcx_ids)}"
  route_table_id            = "${aws_route_table.rtb.id}"
  vpc_peering_connection_id = "${data.aws_vpc_peering_connection.pcx.*.id[count.index]}"

  # pick whichever CIDR block (requester or accepter) isn't _our_ CIDR block
  destination_cidr_block = "${replace(data.aws_vpc_peering_connection.pcx.*.peer_cidr_block[count.index], data.aws_vpc.vpc.cidr_block, data.aws_vpc_peering_connection.pcx.*.cidr_block[count.index])}"
}

output "route_table_id" {
  value = "${aws_route_table.rtb.id}"
}
```

### Steps to Reproduce

1. Deploy `prep` to create two VPCs and a peering connection, and note the output IDs.

       cd prep
       terraform apply
       cd ..

2. Deploy `test` as is (with the default `pcx_ids = []`), supplying `vpc1_id` from step 1:

       cd test
       terraform apply -var 'vpc1_id = vpc-2350ec4a'

   result: new route table, no routes yet

3. Deploy `test` again, this time also supplying the pcx_id from step 1:

       terraform apply -var 'vpc1_id = vpc-2350ec4a' -var 'pcx_ids=["pcx-fe22cc97"]'

   result: added a route

4. Finally, deploy `test` again _without_ the pcx_id:

       terraform apply -var 'vpc1_id = vpc-2350ec4a'

### Expected Behavior

Should remove the route added in step 3.

### Actual Behavior
```
dmrz@golbez:~/aws/dmrz-test/pcx_bug/test$ terraform apply -var 'vpc1_id = vpc-2350ec4a'
data.aws_vpc.vpc: Refreshing state...
aws_route_table.rtb: Refreshing state... (ID: rtb-3592155c)
Error refreshing state: 1 error(s) occurred:

* data.aws_vpc_peering_connection.pcx: At column 14, line 1: list "var.pcx_ids" does not have any elements so cannot determine type. in:

${var.pcx_ids[count.index]}
```

Even though the data source is no longer called for (because count=0 again), terraform still tries to interpolate its other parameters.

### Workaround

Manually removing the offending data source's existing state causes the operation to succeed:

    terraform state rm data.aws_vpc_peering_connection.pcx
    terraform apply -var 'vpc1_id = vpc-2350ec4a'

**Comment by ewbankkit** [comment]
Same problem in TF 0.9.2.

**Comment by ewbankkit** [comment]
I think this may be the same underlying issue as in #13828.

**Comment by apparentlymart** [comment]
Hi @dmrzzz! Sorry for the problem here, and for the long silence.

I think @ewbankkit is correct that this is the same root cause as #13828. We now have a fix for this in master, so if one of you is comfortable with building a Terraform binary from the latest master branch and able to give this a test to confirm it fixed that'd be awesome! Otherwise, we can hold off and test after the next release.

**Comment by ewbankkit** [comment]
@apparentlymart I have verified that a very similar case to this one that wasn't working before merging #13828 is now working, but I'll let @dmrzzz verify and close this issue.

**Comment by dmrzzz** [comment]
Sorry for the long delay; I've confirmed that this now works fine in the latest TF 0.9.11.  Thanks for the fix!
