### ISSUE TITLE
Terraform State Locking Issues in 0.9.0

### ISSUE THREAD

**Issue by emoshaya-cognito** [hashicorp/terraform#12963]
Hi all,

We've been using [Terragrunt ](https://github.com/gruntwork-io/terragrunt)for a while now to manage state locking. Unfortunately, Terragrunt is not compatible with 0.9.0. Therefore, we now want to deprecate use of Terragrunt and migrate to 0.9.0 which fully supports state locking. However, we've noticed a few discrepancies and missing features available in the Terragrunt tool and missing in 0.9.0 Terraform. Please could you advise if these features will be available in future releases and if so, are their any timelines?

The configuration I had in place was for the following:

**S3 Backend for States and DynamoDB for State Locking**

- In Terragrunt, if the S3 bucket or DynamoDB table is missing, then Terragrunt would create them for you based on the configuration specified. This is missing in Terraform 0.9.0
- In Terragrunt, if you ran a Terragrunt apply, it will poll the dynamoDB table for the lock and will retry based on the value assigned in "max_lock_retries: (Optional) The maximum number of times to retry acquiring a lock. Terragrunt waits 10 seconds between retries. Default: 360 retries (one hour)."

- However, in Terraform 0.9.0 it doesn't retry or poll for lock to be released. Instead you get the following error:

`Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed
    status code: 400, request id: LTCHNG5G8U10REB2A6DV39LO6BVV4KQNSO5AEMVJF66Q9ASUAAJG
Lock Info:
  ID:        a4728cc3-303d-4987-af4a-25a54e954907
  Path:      ce-cog-test-tfstates/devops-terraform/cog.test.tfstate
  Operation: OperationTypePlan
  Who:       josh@magpie
  Version:   0.9.1
  Created:   2017-03-22 13:19:29.60094345 +0000 UTC
  Info:`

This is potentially a blocker for our CI builds as we have multiple CI builds running simultaneously at any given day and having the build just retrying to acquire the lock is a must to avoid failing builds.

**Comment by cultavix** [comment]
I've not seen this for myself, but we are in the same situation. We def. need it to retry and be able to customise that because we also use TF on a CI for testing/deployment.

**Comment by jbardin** [comment]
Ho @emoshaya-cognito,

FYI, the next release of terraform will have a `-lock-timeout` on applicable commands, which will have terraform poll the lock for at least the duration of the timeout.

**Comment by ashtttt** [comment]
There seems to be an issue with -lock-timeout. If we provide a timeout value, terraform is waiting to acquire the lock for the provided time duration. But when it acquires the lock,  it is not using the latest state file that was pushed by the previous person/process who had the lock before.

**Comment by jbardin** [comment]
@ashtttt,

I assuming you're using the S3 backend? If so, I have a feeling this is caused by S3's eventual consistency. This is something we should consider though, I'll open an issue to keep track of it.

**Comment by ashtttt** [comment]
Thanks @jbardin 

Yes, I am using S3 backend. Even I thought its could be S3's eventual consistency issue. But, what ever the issue, it is doing the damage as its not making the change on latest state file.
