### ISSUE TITLE
config/module: Crashing when trying to output to a variable in Tree.Validate

### ISSUE THREAD

**Issue by tty01** [hashicorp/terraform#12964]
Terraform version: 0.9.0

Gist: https://gist.github.com/tty01/afb6f9ff8f738c43497bfd87e90b9e82

My Terraform config is as follows:

MODULE EC2:

```hcl
variable "vpcsecgroups" {}
variable "tag" { default = "Terraform deployed node" }
variable "key_name" {}
variable "subnetid" {}
variable "count" { default = 1 }
variable "instance_type" { default = "m4.large" }

resource "aws_instance" "terraform" {
  ami = "ami-f4cc1de2"
  key_name = "${var.key_name}"
  instance_type = "${var.instance_type}"
  vpc_security_group_ids = ["${var.vpcsecgroups}"]
  subnet_id = "${var.subnetid}"
  count = "${var.count}"
  tags {
    Name = "${var.tag}-${count.index}"
  }
}
```

TESTAPP MAIN.TF:

```hcl
variable "count" { default = 2 }
variable "aws_region" { default = "us-east-1" }
variable "vpcsecgroups" {  default = "value" }
variable "tag" { default = "Terraform Deployed" }
variable "key_name" { default = "value" }
variable "subnetid" { default = "value" }


provider "aws" {
  assume_role {
    role_arn = "value"
    session_name = "TERRAFORM"
  }
    region = "${var.aws_region}"
}

module "terraformnode" {
  source = "../../modules/ec2"
  vpcsecgroups = "${var.vpcsecgroups}"
  key_name = "${var.key_name}"
  subnetid = "${var.subnetid}"
  count = "${var.count}"
}

output "ip" { value = "${module.terraform.*.public_ip}" }
```

I am probably going about this wrong, but i am attempting to output the public_ip's of the multiple aws instances. The output line under main.tf it is causing a crash.log. Also if someone can point me in the right direction of being able to output the public IP from the multiple nodes via output, i would greatly appreciate it. I have scoured the net and any of the suggestions ive tried doesnt work for me. Thanks

**Comment by dr3s** [comment]
I had a crash when I did something similar.  I had to wrap it in an array [ ] and then access it with element function

**Comment by tty01** [comment]
Can you give me a example of your approach?

**Comment by freimer** [comment]
```
output "aws_s3_bucket.fw_bootstrap_bucket.id" {
  value = "${list(aws_s3_bucket.fw_bootstrap_bucket.*.id)}"
}
```

**Comment by tty01** [comment]
Thanks!

**Comment by mildwonkey** [comment]
This codepath was removed in terraform 0.12, so I am going to close this issue. Please don't hesitate to open a new issue if you see any odd behavior in terraform 0.12. Thanks!
