### ISSUE TITLE
terraform_remote_state w/ Atlas backend ignores 404s.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#12976]
### Terraform Version
v0.9.1

### Affected Resource(s)
- terraform_remote_state, specifically the Atlas backend

The http backend is not affected by this.

### Terraform Configuration Files
```hcl
data "terraform_remote_state" "main" {
  backend = "atlas"

  config {
    name = "DOES_NOT_EXIST/DOES_NOT_EXIST"
  }
}

output "my_val" {
  value = "${data.terraform_remote_state.main.my_val}"
}

output "test" {
  value = "test"
}
```

### Output
https://gist.github.com/clstokes/7a1940d7d4c08aca370469c89c040b89

### Expected Behavior
Terraform should error that the remote state does not exist.

### Actual Behavior
Terraform completes successfully.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by teamterraform** [comment]
The `atlas` backend in Terraform no longer exists, replaced with the `remote` backend and Terraform Cloud, so we're going to close this out now.
