### ISSUE TITLE
newrelic_alert_condition - `condition_scope` must be `application` or `instance`

### ISSUE THREAD

**Issue by matthewcanty** [hashicorp/terraform#12972]
### Terraform Version
`0.9.1`

### Affected Resource(s)
Please list the resources as a list, for example:
- newrelic_alert_condition

### Terraform Configuration Files
```hcl
data "newrelic_application" "app" {
  name = "My.Web.Api"
}

resource "newrelic_alert_policy" "foo" {
  name = "foo"
}

resource "newrelic_alert_condition" "foo" {
  policy_id = "${newrelic_alert_policy.foo.id}"

  name        = "foo"
  type        = "apm_app_metric"
  entities    = ["${data.newrelic_application.app.id}"]
  metric      = "apdex"
  runbook_url = "https://www.example.com"

  term {
    duration      = 5
    operator      = "below"
    priority      = "critical"
    threshold     = "0.75"
    time_function = "all"
  }
}
```

### Debug Output
https://gist.github.com/matthewcanty/acbdc5b8247376b8b6803ea733b607d9

### Expected Behavior
An alert policy should have been created with conditions on My.Web.Api. 

### Actual Behavior
An alert policy is created, including notification channel but no condition is made.

### Steps to Reproduce
`terraform apply`

### Important Factoids
My configuration is lifted from https://www.terraform.io/docs/providers/newrelic/d/application.html only I've replaced the app name with one which is valid.

**Comment by grubernaut** [comment]
Hello @matthewcanty, thanks for the issue! 
It looks like the newrelic API either changed, or there is an upstream difference between the go-sdk we use and the newrelic API. I searched the New Relic documentation thoroughly, and I couldn't find any hints to what `condition_scope` is, unfortunately. Paging @paultyng for any thoughts.

**Comment by matthewcanty** [comment]
https://docs.newrelic.com/docs/alerts/new-relic-alerts/configuring-alert-policies/scope-alert-thresholds-specific-instances

Only reference to the property I can find is here.

**Comment by paultyng** [comment]
I'll try to take a look later today, their admin API is pretty lacking in documentation, looks like maybe we can just at least default it to `application` for now maybe?

**Comment by grubernaut** [comment]
@paultyng that'd be okay with me, if we're sure that `instance` isn't used for anything. Want to make that change in the SDK, and we'll update the vendor?

**Comment by paultyng** [comment]
Weirdly that field does show up in their API explorer, with zero documentation around it.

Let me contact their support and ask whats up.

**Comment by grubernaut** [comment]
@paultyng awesome, that'd be best ❤️ thanks!

**Comment by paultyng** [comment]
Per New Relic support:

> After doing a bit of investigation, it looks like your account is enrolled in a few of our new features, specifically ["JVM Instance-based alerting"](https://docs.newrelic.com/docs/alerts/new-relic-alerts/configuring-alert-policies/scope-alert-thresholds-specific-instances#api).
>This is the reason why this account is expecting the `condition_scope` value. Because of having the feature enabled to select JVM instance or application, you will need to pass in one additional `key:value` pair to the condition payload to specify whether you would like violations scoped to the application or an individual JVM. This means you need to add the `condition_scope` to the condition object and pass it the value of either application or instance.

So I'll get this added to the SDK library as an `omitempty` and we can update the vendor and fix it.

**Comment by paultyng** [comment]
Same link as above, but at least an explanation as to why its only sometimes an issue.

**Comment by grubernaut** [comment]
Ah that's awesome, thanks for digging into that!

**Comment by paultyng** [comment]
PR submitted on #13158 that works with this field now.
