### ISSUE TITLE
Azure: provider throws error with credentials provided via env-vars

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform#12977]
### Terraform Version
v0.9.1

### Affected Resource(s)
- provider "azurerm"

### Terraform Configuration Files
```hcl
provider "azurerm" {
  subscription_id            = "00000000-0000-0000-0000-000000000000"
  client_id                  = "00000000-0000-0000-0000-000000000000"
  client_secret              = "00000000-0000-0000-0000-000000000000"
  tenant_id                  = "00000000-0000-0000-0000-000000000000"
  skip_provider_registration = "true"
}

resource "azurerm_resource_group" "tectonic_cluster" {
  location = "northeurope"
  name     = "cred-test-group"
}
```

```shell
export ARM_SUBSCRIPTION_ID="00000000-0000-0000-0000-000000000000"
export ARM_CLIENT_ID="00000000-0000-0000-0000-000000000000"
export ARM_CLIENT_SECRET="00000000-0000-0000-0000-000000000000"
export ARM_TENANT_ID="00000000-0000-0000-0000-000000000000"
```
### Debug Output
With credentials hard-coded in provider block:
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ azurerm_resource_group.tectonic_cluster
    location: "northeurope"
    name:     "cred-test-group"
    tags.%:   "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.
```

Without hard-coded credentials (but exported from env-vars):
```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error running plan: 1 error(s) occurred:

* provider.azurerm: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: autorest#WithErrorUnlessStatusCode: POST https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47%0D/oauth2/token?api-version=1.0 failed with 400 Bad Request: StatusCode=400
```

### Expected Behavior
Terraform runs successfully with supplied credentials regardless if provided from env-vars or inlined as provider attributes.

### Actual Behavior
Terraform behaves differently when same credentials are provided in-line or through env-vars. 
Same credentials which work correctly when set on provider cause an error when supplied through env-vars.

### Steps to Reproduce
Export credentials through environment variables like shown above.
Run terraform on above-provided template once with credentials parameters set and once without them.
1. `terraform plan`

**Comment by pmcatominey** [comment]
Hi @alexsomesan,

I'll try and reproduce this, seems odd since the automated tests and myself both use the environment variables to source the credentials.

Just to confirm the credentials you've provided there are just placeholders?

**Comment by alexsomesan** [comment]
Thanks, @pmcatominey 
I might be doing something wrong, since I'm new to Azure. Either way I'd appreciate some info on how to run with external credentials.

**Comment by tombuildsstuff** [comment]
Hi @alexsomesan

I'm not sure from your reply if the credentials posted above are real or just placeholders. Just in-case they're not: I've updated the description to use `00000000-0000-0000-0000-000000000000` instead - you might also want to cycle the Client ID / Client Secret within Azure.

Taking a quick look at the error you've posted it looks like there's a carriage return character (`%0D`) at the end of the Subscription ID:

```
POST https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47%0D/oauth2/token?api-version=1.0 failed with 400 Bad Request: StatusCode=400
```

Given you're setting these values via Environment Variables - can you confirm if the output of `env` includes any blank lines after the Subscription ID? For example:

```
$ env
...
HOME=/Users/...
foo=bar

...
```

Thanks!

cc @pmcatominey

**Comment by alexsomesan** [comment]
Hi Tom,

They are not real credentials. Those are fake UUIDs that I've generated for
the sake of this example.
Sorry for the newline. Must have been a typo when filling this issue.
In the real ones I use there is no newline at the end of the subscription
ID.
