### ISSUE TITLE
Ability to add multiple databases per on AWS RDS instance

### ISSUE THREAD

**Issue by RuslanHamidullin** [hashicorp/terraform#1298]
Hey Guys,

Is it possible  to add multiple databases per on AWS RDS instance?

Thanks :beers:

**Comment by ketzacoatl** [comment]
+1

**Comment by catsby** [comment]
Is this achievable through Amazon's RDS API? The [Create Database Instance][1] endpoint only seems to allow a single name. 

Can you accomplish this with a provisioner that runs after creation, and uses a SQL connection?

[1]: http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

**Comment by RuslanHamidullin** [comment]
@catsby yeah, looks like it's not possible via RDS Api.
Only via PSQL cli command.
Also, looks like access to RDS in restricted by AWS VPC.
hmm, not sure if it's possible as PSQL cli command should be runned from VPC (Instance so on).

**Comment by RuslanHamidullin** [comment]
Ahh looks PSQL cli is possible, I needed to correct Security Group

**Comment by catsby** [comment]
Thanks for following up. I'm going to close this for now, as I don't know that we can provide this at the configuration level. Thanks!

**Comment by ringods** [comment]
Here are pending pull requests for:

* MySQL provider: #3122
* PostgreSQL provider: #3653 

Using these providers, you will be able to create additional databases.

**Comment by apparentlymart** [comment]
Seconding what @ringods said. I'm currently using the MySQL provider from #3122 in production (using [our custom Terraform distro](https://github.com/saymedia/terraform-plus)) for this exact use-case: for each of our environments we make a RDS instance to contain the various databases for our low-volume internal admin tools, like Rundeck and Grafana.

So we use `aws_rds_instance` without a database name to create an empty MySQL server, and then use `mysql_database` once for each of the tools to create a separate database for each.
