### ISSUE TITLE
RDS Aurora Cross-Region replication for encrypted cluster failing

### ISSUE THREAD

**Issue by asadhu** [hashicorp/terraform#12985]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v0.9.1_1

### Affected Resource(s)
RDS Cross-Region Cluster replication

### Terraform Configuration Files
```hcl
resource "aws_rds_cluster" "replica-west" {
  cluster_identifier      = "aurora-replica-cluster-demo"
  replication_source_identifier = "arn:aws:rds:us-east-1:*:cluster:aurora-cluster"
  #"${aws_rds_cluster.default-east.id}"
  availability_zones      = ["us-west-2a"]
  backup_retention_period = 5
  preferred_backup_window = "07:00-09:00"
  storage_encrypted       = "true"
  kms_key_id              = "arn:aws:kms:us-east-1:*:key/[key_name]"
  db_cluster_parameter_group_name = "default.aurora5.6"
  #source-region           = "us-east-1"
}

```

### Debug Output
* aws_rds_cluster.replica-west: InvalidParameterCombination: Source cluster arn:aws:rds:us-east-1:*:cluster:aurora-cluster is encrypted; pre-signed URL has to be specified
	status code: 400

### Expected Behavior
What should have happened?

I have an AWS RDS Aurora Cluster in US East and am trying to create a Cross-Region Cluster on the west. The Replica Cluster should have been created.

### Actual Behavior
What actually happened?

The East Cluster is encrypted and requires kms_key_id and source_region/presigned_url. 'source-region/presigned_url' is not supported in Terraform 0.9.1_1.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Aurora.Replication.CrossRegion.html

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by asadhu** [comment]
@grubernaut is there any timeline when we can have this feature on terraform? Or do I need to create a new issue with AWS? would need to be directed to the repository though!!

**Comment by twofivetechnology** [comment]
looks like issue is the SourceRegion is not being specified in the creatOpts in the event that replication_source_identifier is in another region and is encrypted.

Would it be acceptable to submit a PR that infers the region of the replication_source_identifier (by parsing the ARN provided) and sets SourceRegion in the createOpts?

**Comment by asadhu** [comment]
@twofivetechnology that seems like a good solution, cross region KMS keys... not sure how to manage that. But if that works it would be great!!

**Comment by jude-pieries** [comment]
I confirm that sourceregion needs to be added to "aws_rds_cluster" to get around the encrypted error " cluster:aurora-cluster is encrypted; pre-signed URL has to be specified status code: 400" for encrypted cross region replicas.  

I managed recreate the issue with the New-rdsdbcluster in powershell , adding the -sourceregion resolved the issue. 

New-RDSDBCluster -SourceRegion $var_source_Region  -Region $var_des_Region  -DBClusterIdentifier  $var_des_DBClusterIdentifier  -ReplicationSourceIdentifier $var_source_ReplicationSourceIdentifier -KmsKeyId $var_des_KmsKeyId -StorageEncrypted $var_des_StorageEncrypted  -DBSubnetGroupName $var_des_DBSubnetGroupName -DBClusterParameterGroupName $var_des_DBClusterParameterGroupName -Engine $var_des_Engine  -Port $var_des_Port
