### ISSUE TITLE
aws_alb_listener_rule resource should not be able to accept multiple values in the condition object

### ISSUE THREAD

**Issue by jflammia** [hashicorp/terraform#12983]
Using the aws_alb_listener_rule, the argument 'condition' with field 'path-pattern' is documented as accepting a list for the 'values'.  However, AWS does not allow this.

[AWS Documentation](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#listener-rules)

> Rule Conditions
> 
> **Each rule condition can have one path pattern**. You can create multiple rules, each with a different path pattern, in order to route requests to different target groups based on the URLs in the requests. If the URL in a request matches a path pattern in a listener rule exactly, the request is routed using that rule; otherwise, the request is routed using the default rule.

From my Terraform configuration file:

```
resource "aws_alb_listener_rule" "jenkins" {
  listener_arn = "${aws_alb_listener.https.arn}"
  priority     = 100

  action {
    type             = "forward"
    target_group_arn = "${module.jenkins.alb_target_group_arn}"
  }

  condition {
    field  = "path-pattern"
    values = ["/jenkins", "/jenkins/*"]
  }
}

resource "aws_alb_listener_rule" "artifactory" {
  listener_arn = "${aws_alb_listener.https.arn}"
  priority     = 101

  action {
    type             = "forward"
    target_group_arn = "${module.artifactory.alb_target_group_arn}"
  }

  condition {
    field  = "path-pattern"
    values = ["/artifactory", "/artifactory/*"]
  }
}
```

Response after running 'terraform apply':
```
Error applying plan:

2 error(s) occurred:

* module.utils.aws_alb_listener_rule.artifactory: 1 error(s) occurred:

* aws_alb_listener_rule.artifactory: Error modifying ALB Listener Rule: ValidationError: The 'path-pattern' field contains too many values; the limit is '1'
	status code: 400, request id: 3c1caee3-0f37-11e7-aca5-6ba0d22bd4d1
* module.utils.aws_alb_listener_rule.jenkins: 1 error(s) occurred:

* aws_alb_listener_rule.jenkins: Error modifying ALB Listener Rule: ValidationError: The 'path-pattern' field contains too many values; the limit is '1'
	status code: 400, request id: 3c1caeca-0f37-11e7-9c22-29da514a138b

```

This occurs using Terraform 0.9.1

**Comment by dpanchal-visuallease** [comment]
Actually it does support, I tried with TF version terraform_0.12.19_linux_amd64/terraform and it worked fine.
