### ISSUE TITLE
Update Checkpoint API version for terraform

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/terraform#12995]
It sounds like the checkpoint API hasn't been updated recently to reflect the newer version of terraform available.

See https://checkpoint-api.hashicorp.com/v1/check/terraform

It should point to either v0.9.1 or v0.9.0

**Comment by stack72** [comment]
Hi @ColinHebert 

Apologies - this has been added now

I can see it in checkpoint

Paul
