### ISSUE TITLE
Issue with assigning variable from file

### ISSUE THREAD

**Issue by MangalickMitra** [hashicorp/terraform#12997]
This issue was seemingly resolved in previous releases but still able to reproduce. There are quite e few bug ids that report this same problem

**File Configuration**

**<secret.tfvars>**
access_key = "AccessKeyHere"
secret_key = "SecretKeyHere"
region = "ap-south-1"

**<instance.tf>**
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
  insecure   = true
}

resource "aws_instance" "Nirvana2" {
  ami = "ami-8f8afde0"
  instance_type = "t2.micro"
  tags {
    Name = "Nirvana2"
  }
}

**Version**
v0.9.1

**Command** : 
1. terraform plan -var-file=secret.tfvars

2. terraform plan

**Expected Behaviour**
Plan executes successfully

**Actual Behaviour**
`provider.aws: 1:3: unknown variable accessed: var.secret_key in:

${var.secret_key}
`

**Comment by tombuildsstuff** [comment]
Hi @MangalickMitra 

Taking a look at the code posted above, there's no [definitions for the variables](https://www.terraform.io/docs/configuration/variables.html) which are specified in the `secrets.tfvars` file (and used in the `instances.tf` file).

Each variable needs a matching definition (which can optionally include a description / default value / data type etc.) - which allows variables used in code to be specified either through Variable Files, or interactively through the Command Line.

For example - when adding definitions for each of the variables into either the `instances.tf` file (or any other `*.tf` file) - the code you've posted above works as expected:

```
variable "access_key" {}
variable "secret_key" {}
variable "region" {}

...
```

Can you confirm if adding the definitions solves your issue? :)

Thanks!

**Comment by MangalickMitra** [comment]
Adding the definition, solves the issue. Thanks. Just started with Terraform. That part wasn't mentioned in the docs.

**Comment by catsby** [comment]
Thanks for reporting resolution here 😄
