### ISSUE TITLE
aws_security_group rule already exists error

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#1299]
When adding an Allow All egress rule on a security group that already has an allow all egress rule results in an error.  Seems like it should not be an error since the system is already in the desired state. Perhaps we should update our model of the local state to reflect that the rule already exists, rather than cause an error.

"Error authorizing security group egress rules: the specified rule "peer: 0.0.0.0/0, ALL, ALLOW" already exists"

Terraform v0.4.0-dev (28ecdacdf9e76ef3679a0c85aff14a06e8586e9c)

**Comment by c4milo** [comment]
I'm running into this as well. v0.5.0-dev

**Comment by catsby** [comment]
Is this existing rule external to Terraform, or does it exist in your configuration already?

**Comment by c4milo** [comment]
External to Terraform, it seems they are added by AWS by default when the security group is created. I fixed my problem by removing the rule in my Terraform configuration file.

**Comment by catsby** [comment]
Proposing #1765 as a fix to this

**Comment by franklinwise** [comment]
Awesome! Thanks @catsby
