### ISSUE TITLE
aws_security_group already exists error

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#1300]
When a security group already exists in a VPC, but Terraform local state doesn't reflect this, perhaps because the group wasn't fully created because of an egress rule already existing on creation (see #1299), it results in an error. Seems like it should not be an error since the system is already in the desired state. Perhaps we should update our model of the local state to reflect that the security group already exists, rather than cause an error

 `Error creating Security Group: The security group 'jump' already exists for VPC 'xxx-xxxxxxx'`

Terraform v0.4.0-dev (28ecdac)

**Comment by franklinwise** [comment]
Terraform v0.4.0-dev (28ecdac)

**Comment by mitchellh** [comment]
dup #1299

**Comment by zhonglingyi** [comment]
createVm[ERROR],Security group default already exists for project 41d5a9426e4549bba21051d887323605 ?why?
