### ISSUE TITLE
bug resource aws_vpc and DNS

### ISSUE THREAD

**Issue by kendawg2** [hashicorp/terraform#1301]
There are two DNS related fields in aws_vpc.   "enable_dns_support" and "enable_dns_hostnames".   If both set to 'True' an error is thrown at apply time.

* 1 error(s) occurred:

* Fields for multiple attribute types specified: enableDnsHostnames, enableDnsSupport

However if either is set, no error occurs, but setting "enable_dns_support" does not in fact enable DNS support in the VPC.   Setting "enable_dns_hostnames" enables both.  Presumably because DNS support is the default.   

This was a recent change, and suspect it was an artifact of the new underlying API changes.   

The workaround appears to be to simply use "enable_dns_hostnames" only.    

This will be confusing since AWS documentation clearly states that BOTH need to be enabled.   The error is not obvious.

**Comment by willmcg** [comment]
Looks like the same issue as #1283.

**Comment by phinze** [comment]
Ah I see the bug here; we're just reusing a request object improperly. Fixing...

**Comment by kendawg2** [comment]
@willmcg yes it does appear the the same error anyway and the config does have both set to true.

**Comment by kendawg2** [comment]
@phinze Thanks

**Comment by willmcg** [comment]
@phinze Thanks!  Just verified that it works with my larger configuration.
