### ISSUE TITLE
Can not declare providers in modules when root has provider of same type

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#13027]
### Terraform Version

Terraform v0.9.1

### Affected Resource(s)

N/A

### Terraform Configuration Files
```hcl
# ./main.tf
provider "aws" {
  region = "us-east-1"
}

module "module_us_west_1" {
  source = "./module"
  region = "us-west-1"
}

# ./module/main.tf
variable "region" {
  description = "AWS region for provider"
}

provider "aws" {
  region = "${var.region}"
}

resource "aws_cloudwatch_log_group" "rds_os" {
  name = "FOO"
  retention_in_days = 30
}
```

### Debug Output

https://gist.github.com/49d939e853feab8cbea3a81c0395f354

### Panic Output

N/A

### Expected Behavior

The FOO AWS log group would be created in us-west-1

### Actual Behavior

The FOO AWS log group was created in us-east-1 (the parent provider)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This does the expected thing if the provider is not declared in `./main.tf`.

### References

N/A

**Comment by timurb** [comment]
Does it work if you reference the provider inside module by alias?
https://www.terraform.io/docs/configuration/resources.html#multiple-provider-instances

This is not actually a solution to this issue but could probably be used as a workaround.

**Comment by jbardin** [comment]
This is fixed in master, as the provider inheritance behavior has been updated.
