### ISSUE TITLE
Seperate automatically included .tfvars for different environments?

### ISSUE THREAD

**Issue by atyndall** [hashicorp/terraform#13029]
Currently, if a `terraform.tfvars` file is present in the current directory, Terraform automatically loads it to populate variables.

With respect to the new environments feature, we have two environments, `staging` and `production` configured. It would be nice if terraform could automatically load perhaps `staging.tfvars`/`production.tfvars` (or something similar) automatically depending on the environment selected, as they contain different configuration. Right now we manually use `-var-file`, which is a pain.

As far as I could see this isn't possible with the current version?

**Comment by RichardN** [comment]
I think this is the same feature request as https://github.com/hashicorp/terraform/issues/12845

**Comment by atyndall** [comment]
Yep, looks to be a duplicate, thanks!
