### ISSUE TITLE
aws_security_group - referencing an existing security group in ingress rule causes an attempt to create it twice

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#1302]
Referencing an existing Security Group by it's ID causes an attempt to create it twice as shown below.  When the "nat" security group is being created, it references the "jump" security group id, consequently i attempts to create the existing group again instead of using the existing group. (Related issue #1300)

## Error Message

```
aws_security_group.nat: Error: 1 error(s) occurred:
* Error creating Security Group: The security group 'jump' already exists for VPC 'vpc-xxxxxxx'
aws_instance.chef: Error: 1 error(s) occurred:
```

## Context

 % terraform apply                                                                                                                           
... (clipped)
**aws_security_group.jump: Refreshing state... (ID: sg-6beed20e)**
... (clipped)
aws_security_group.**nat**: Creating...
  description:                                   "" => "A jump nat server"
  egress.#:                                      "" => "<computed>"
  ingress.#:                                     "" => "2"
  ingress.1580127170.cidr_blocks.#:              "" => "0"
  ingress.1580127170.from_port:                  "" => "-1"
  ingress.1580127170.protocol:                   "" => "-1"
  ingress.1580127170.security_groups.#:          "" => "1"
  ingress.1580127170.security_groups.2451903536: "" => "sg-74eed211"
  ingress.1580127170.self:                       "" => "0"
  ingress.1580127170.to_port:                    "" => "-1"
  ingress.3078754527.cidr_blocks.#:              "" => "0"
  ingress.3078754527.from_port:                  "" => "22"
  ingress.3078754527.protocol:                   "" => "tcp"
  ingress.3078754527.security_groups.#:          "" => "1"
  ingress.3078754527.security_groups.1805085839: "" => **"sg-6beed20e"**
  ingress.3078754527.self:                       "" => "0"
  ingress.3078754527.to_port:                    "" => "22"
  name:                                          "" => "jump"
  owner_id:                                      "" => "<computed>"
...

Terraform v0.4.0-dev (28ecdac)

**Comment by catsby** [comment]
Hello – do you have a sample configuration (with secrets excluded) that demonstrates this? Thanks!

**Comment by catsby** [comment]
I attempted to reproduce this but was unable to with the following configuration:

```javascript
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "tf-sg-test" {
  cidr_block = "10.1.0.0/16"
  tags {
    Name = "tf-sg-test"
  }
}

resource "aws_security_group" "tf-sg-1" {
  name = "tf-sg-1"
  description = "tf-sg-1"
  vpc_id = "${aws_vpc.tf-sg-test.id}"

  ingress {
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    self = true
  }

  tags {
    Name = "tf-sg-1"
  }
}

resource "aws_security_group" "tf-sg-2" {
  name = "tf-sg-2"
  description = "tf-sg-2"
  vpc_id = "${aws_vpc.tf-sg-test.id}"

  ingress {
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    self = true
    security_groups = ["${aws_security_group.tf-sg-1.id}"]
  }

  tags {
    Name = "tf-sg-2"
  }
}
```

Am I capturing the configuration you're describing?

**Comment by pmoust** [comment]
The sg reference should be two-way. I.e. Tf-sg-1 should have tf-sg-2 in its
ingress list.

**Comment by pmoust** [comment]
Hm. Sorry I thought I was commenting on another sg reference issue my team
had opened.

**Comment by catsby** [comment]
@pmoust so, does my config model the scenario, or not ? I'm confused :smile:

**Comment by franklinwise** [comment]
If you run terraform apply on this directory below, you should reproduce the problem:

https://github.com/kraveio/chef/tree/master/up

**Comment by franklinwise** [comment]
@catsby - were you able to reproduce using the the directory?

**Comment by franklinwise** [comment]
@catsby - following up

**Comment by franklinwise** [comment]
too many 80hr weeks, the name property was duplicated on my side, would be helpful if there was more error information about the conflicting instances.
