### ISSUE TITLE
s3 remote state still broken for multiple users

### ISSUE THREAD

**Issue by in4mer** [hashicorp/terraform#13032]
### Terraform Version
0.9.1

### Affected Resource(s)
s3 remote state backend

### Terraform Configuration Files
```
No configs necessary
```

### Debug Output
No debug output necessary

### Panic Output
No panic

### Expected Behavior
* I expect the s3 remote state plugin to be able to handle an arbitrarily named file that contains the AWS profile information referenced by a reserved environment variable.
* I expect the s3 remote state plugin to be able to handle an arbitrarily named profile referenced by a reserved environment variable.

### Actual Behavior
* any attempt to use a non-standard filename through the shared_credentials_file variable in the provider does exactly the opposite; upon export of remote state, the shared_credentials_file is *hardcoded* into the remote state itself, thereby requiring *any* user of the remote state to have their credentials stored in that remote state/globally defined absolute-pathed filename.
* interpolation is verboten within the backend config block, even if the variables are provided via TF_VAR_* environment variables.  This seems undesirable; that is the entire point of environment variables.

### Steps to Reproduce
This is a design problem.

### Important Factoids
Not everyone can store **ALL** their AWS credentials within a single [default] filename, nor would everyone want to!  Each shell has a specific environmental context that is specific to that shell, and it's malleable for a reason.  Multiple accounts/customers/profiles/&c should not bear the risk of collision just because nobody can come up with a better idea than ~/.aws/credentials and no other way to re-define that default file.  Or the profile to look up within that file.

Storing static filename references within the remote state specified in S3 is actually wrong.  The remote state is already implicitly defined in looking for the remote state in the first place.  The state is included in the S3 connection to download that remote state.  Further specifying the remote state within the file metadata is at best redundant.

### References
I'm sure there are tons; the "AWS credentials in S3 tickets" are all about this problem, just a different facet of it.

### My suggestion:
Allow another way to access environment variables explicitly, so you don't have to go through the early graph dance, and you can **store those environment variable references within the remote state in S3**  Don't give them defaults, don't give them anything.  Let it fail if they aren't defined properly, please.

Please don't tear into me too hard for pointing out what someone might not want to hear.  This seems terribly obviously broken to me, and it's impacting my workflow and use of this tool, and I'm surprised it's still an issue.

**Comment by bruceharrison1984** [comment]
I second this. We currently are stuck on 0.8.8 until this is fixed since we currently use environmental variables in the filename when declaring remote state via the command line 'remote' option. We are also using S3 as our remote backend.

**Comment by joestump** [comment]
We create our TF state file's name from environment variables per application/environment. [This suggestion](https://github.com/hashicorp/terraform/issues/13022#issuecomment-294262392) worked for me.

**Comment by knope** [comment]
also stuck on 0.8.8 without the ability to interpolate backend.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
