### ISSUE TITLE
Terraform 0.9.1 security group CIDR validation error

### ISSUE THREAD

**Issue by xuwang** [hashicorp/terraform#13034]
### Terraform Version

```
$ terraform version
Terraform v0.9.1
```

### Affected Resource(s)
- aws_security_group

### Terraform Configuration Files

```hcl
variable "kube_service_cidr" {
    default = "10.32.0.0/24"
}
variable "vpc_id" {
    default = "vpc-123dc356"
}

resource "aws_security_group" "kubernetes"  {
  name = "test-kubernetes"
  vpc_id = "${var.vpc_id}"
  lifecycle { create_before_destroy = true }

  ingress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = [
      "${var.kube_service_cidr}",
      "${data.template_file.test.rendered}" 
    ]
  }
}

data "template_file" "test" {
  template = "$${cidr}"

  vars {
    cidr = "10.240.0.0/16"
  }
}
```
### Debug Output

Can produce if needed.

### Expected Behavior

CIDR block with addresses from both data source and vars should be valid. 

### Actual Behavior

Got parser error.

### Steps to Reproduce

Save the above code as cidr-test.tf, then run apply:

```
$ ls -l /tmp/test
total 8
-rw-r--r--  1 xuwang  wheel  535 Mar 23 19:48 cidr-test.tf
$ export AWS_REGION=us-west-2
MBPSF:test $ terraform plan
1 error(s) occurred:

* aws_security_group.kubernetes: "ingress.0.cidr_blocks.0" must contain a valid CIDR, got error parsing: invalid CIDR address: ${var.kube_service_cidr}
```
### Important Factoids

If I comment out either `"${data.template_file.test.rendered}"`  or `"${var.kube_service_cidr}"`, the terraform plan will run successfully.  It seems they cannot be mixed. 

A CIDR block list in security group  with  address range from another data source, e.g. "${data.terraform_remote_state.vpc.cluster_vpc_cidr}" and address range defined by terraform variables has been working until  0.9.0.

### References

Might be related to this:
- https://github.com/hashicorp/terraform/pull/12765

**Comment by jeffbehl** [comment]
Same issue.  Works fine unter .8.7 but no go on .9.1
```
2 error(s) occurred:

* module.global_security_groups.aws_security_group.all_public_address_space: "ingress.0.cidr_blocks.0" must contain a valid CIDR, got error parsing: invalid CIDR address: ${
            concat(
              module.public_address_space.cidr_data_centers,
              module.public_address_space.cidr_corp_offices
            )
         }
* module.global_security_groups.aws_security_group.all_public_address_space: "ingress.0.cidr_blocks.1" must contain a valid CIDR, got error parsing: invalid CIDR address: ${formatlist("%s/32",var.nat_gateway_public_ips)}
```

**Comment by number5** [comment]
I have the same error. And also the code I have errors when refreshing passed in 0.9.0

**Comment by kiwiholmberg** [comment]
I see the same error. Works in 0.9.0, but not in 0.9.1.

**Comment by florent-babylon** [comment]
Similar looking error here:
```
resource "aws_security_group" "dev-area-checker-rds_sg" {
  name        = "dev-area-checker-rds_sg"
  description = "dev-area-checker-rds_sg"
  vpc_id      = "vpc-xxxxxx"
  tags { Name = "dev-area-checker-rds_sg" }

  # MySQL port
  ingress {
    from_port   = 3306
    to_port     = 3306
    protocol    = "tcp"
    cidr_blocks = [
        "${var.internal-network}/32",
        "${aws_instance.dev-app1.public_ip}/32",
        "${aws_instance.dev-app2.public_ip}/32",
    ]
    self        = true
  }

  # outbound internet access
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

Returns:
```* aws_security_group.dev-area-checker-rds_sg: "ingress.0.cidr_blocks.0" must contain a valid CIDR, got error parsing: invalid CIDR address: ${var.internal-network}/32```

Works on 0.9.0

Seems to be a duplicate of #12892

**Comment by grubernaut** [comment]
Hey folks, thanks for the issue! 

Closing for now as this is a duplicate of #12892, thanks!
