### ISSUE TITLE
aws vpc destroy fails with unmap public addresses before detaching gateway 

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#1303]
upon attempting to destroy an aws vpc setup I get the following error:

`Network vpc-d440fdb1 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.`

Seems like destroying should just work.  Perhaps unmapping public addresses needs to happen at the beginning of destroy?

Terraform v0.4.0-dev (28ecdac)

**Comment by kendawg2** [comment]
@franklinwise if you look at #1189 you will see some discussion about this.   I was having a similar issue, and what I did was add a depends_on = ["aws_internet_gateway.gw"] to the instance that was getting an elastic IP and the problem went away.  (of course .gw will be whatever you called it).

**Comment by kendawg2** [comment]
@mitchellh perhaps an implied dependency of the internet gateway for anything getting a public IP/Elastic IP might be in order.  For me, the only time this happens is when I use an Elastic IP.  All other instances that get a public IP have no issues.   Also, if I run a destroy a second time, it finished the destroy properly.

**Comment by catsby** [comment]
Hey @kendawg2 , thanks for reporting this. Do you have an example config I can use? Please omit any secrets.

**Comment by catsby** [comment]
Reproduced with the [config example here in 1189](https://github.com/hashicorp/terraform/pull/1189#issuecomment-78569222). 

I'm seeing if I can add error handling to Internet Gateway as a bandaid, but the current solution is the explicit `depends_on` as mentioned.

**Comment by catsby** [comment]
I merged a fix for this in #1325

**Comment by franklinwise** [comment]
Awesome! Thanks @mitchellh & @catsby
