### ISSUE TITLE
SSM_DOCUMENT does not update document

### ISSUE THREAD

**Issue by sgurunathan1951** [hashicorp/terraform#13033]
Hi,

aws_ssm_document does not update the content of the document. And it doesn't create a new version either. Can you please let me know how can I do that?

### Terraform Version
terraform version
Terraform v0.9.1

### Affected Resource(s)
- aws_ssm_document

### Expected Behavior
Content of the ssm document updated.

### Actual Behavior
Content not getting updated.

Regards,

sgurunathan1951

**Comment by stack72** [comment]
Hi @sgurunathan1951 

Thanks for opening the issue here - we are already tracking this request at #12007 - please follow that issue for updates

So I am going to close this as a duplicate

Thanks

Paul
