### ISSUE TITLE
Add option to aws_ami data source to avoid always refreshing

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform#13044]
When rolling out new instances I've been using the `aws_ami` data source to grab the current Ubuntu xenial release:
```hcl
data "aws_ami" "ubuntu" {
  most_recent = true
  owners = ["099720109477"]

  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"]
  }
}
```

Today I revisited one of those configs.  It looks like the `aws_ami` data source is always refreshed:
```sh
$ terraform-0.9.1 plan -target=aws_instance.test_runner
...
aws_iam_role.test_runner: Refreshing state... (ID: test_runner-node-role)
data.aws_ami.ubuntu: Refreshing state...
aws_iam_instance_profile.test_runner: Refreshing state... (ID: test_runner-profile)
aws_instance.test_runner: Refreshing state... (ID: i-0390e658b305068bc)
...
-/+ aws_instance.test_runner
    ami:                                       "ami-a58d0dc5" => "ami-7ac6491a" (forces new resource)
```
I just need to add a security group, so it's kind of a bummer that this will recreate the instance.

It'd be nice if the data source could remember the initial AMI ID, and only refresh if tainted - similar to the random id module.  I'd be happy to set a lifecycle option on the data source to pick this behavior.

### Terraform Version
Terraform v0.9.1

**Comment by apparentlymart** [comment]
Hi @rvandegrift!

Currently, as you've seen, data resources do not retain state from one run to the next but rather assume that you want to re-fetch the latest data on each run. This is the most fundamental difference between a `resource` block and a `data` block.

With that said, your use-case here is a valid one so we can think about ways to support it better. In the mean time one workaround would be to use [the `ignore_changes` lifecycle argument](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) on the `aws_instance` to make it not recreate the instance when the AMI changes. You could then `terraform taint` the instance to force it to get recreated when you know the AMI has changed.

**Comment by ebekker** [comment]
Just published a module to the TF registry that implements cached AMI behavior: https://registry.terraform.io/modules/ebekker/cached-ami/aws/1.0.0

**Comment by ebekker** [comment]
Yes, it does need PowerShell Core, I have tested it out on one Linux configuration (CentOS 7) but in theory it should work anywhere that `pwsh` runs..  I wanted a tool that worked across different platforms which is why I wrote the external pieces in PowerShell, but if you prefer to use some other tool for the local cache management, you can adapt the [source code](https://github.com/ebekker/terraform-aws-cached-ami/blob/master/main.tf) to your needs.
