### ISSUE TITLE
Update the terraform 0.9.x configuration block documentation to include the supports of backend 

### ISSUE THREAD

**Issue by adilnaimi** [hashicorp/terraform#13064]
This issue is related to documentation update to include 0.9.x support of `backed` in terraform configuration block.

The Issue opened based on  discussion in https://github.com/hashicorp/terraform/issues/12780#issuecomment-289157871

### Terraform Version
Terraform v0.9.1

### Affected Resource(s)
Terraform configuration documentation needs update, the configuration block now is supporting the `backed` in addition to `required_version`

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.9.1"
  backend          "s3"             {}
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The configuration documentation needs to be updated to include the support of `backend`
```hcl
terraform {
  required_version = ">= 0.9.1"
  backend          "s3"             {}
}
```

### Actual Behavior
The documentation https://www.terraform.io/docs/configuration/terraform.html mentions that currently only `required_version` is allowed withing the configuration block
```hcl
terraform {
  required_version = ">= 0.9.1"
}
```

### References
https://github.com/hashicorp/terraform/issues/12780#issuecomment-289161326

**Comment by adilnaimi** [comment]
I think this is linked to same issue opened here https://github.com/hashicorp/terraform/issues/7597#issuecomment-290150548

**Comment by nfagerlund** [comment]
I think the modern version of https://www.terraform.io/docs/configuration/terraform.html has the necessary info!
