### ISSUE TITLE
Cloudflare record throwing Invalid dns record identifier

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#13068]
Terraform 0.9.1, recently upgraded from 0.8 to the new backend system to the new backend system (I was using an s3 remote state before).

I have the following record:

```hcl
resource "cloudflare_record" "uploads-db" {
	domain = "example.com"
	name = "uploads-db"
	type = "CNAME"
	value = "${aws_db_instance.uploads-db.address}"
	proxied = false
}
```

I've had this record for a while, but now after the upgrade every time I do `terraform plan`, I get the following error:

```
Error refreshing state: 1 error(s) occurred:
2017/03/25 17:22:34 [DEBUG] plugin: terraform: local-exec-provisioner (internal) 2017/03/25 17:22:34 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/03/25 17:22:34 [DEBUG] plugin: terraform: aws-provider (internal) 2017/03/25 17:22:34 [DEBUG] plugin: waiting for all plugin processes to complete...

* cloudflare_record.uploads-db: cloudflare_record.uploads-db: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1002,\"message\":\"Invalid dns record identifier\"}],\"messages\":[],\"result\":null}"
```

I tried deleting and even tainting the record, but it *always* gives me that error, rendering terraform completely unusable :(

**Comment by obierlaire** [comment]
I'm using older versions of terraform (v0.8.8 and v0.8.4) and I'm facing the exact same issue since this morning.

**Comment by jleclanche** [comment]
I suspect what's happening is somehow, the tfstate got out of sync with the cloudflare upstream. Debugging this is very annoying because the HTTP request log is not available from cloudflare-go, so I'm left guessing what actually is happening and why.

This is super super bad though, a single bad cloudflare record is corrupting the entire terraform state (hundreds of machines/S3 buckets/domains/etc) with no way to recover. That really shouldn't be possible.

**Comment by jleclanche** [comment]
BTW, as suspected this is fixed by deleting the record from terraform.

I think there's a possibility that you would reproduce this by creating a record with terraform, then deleting it upstream, then running a refresh plan again.

But really, this situation should fail more gracefully than that. A bad plugin can take the whole infrastructure down with no obvious recourse to end users.

**Comment by jleclanche** [comment]
I successfully reproduced this by deleting, upstream, a cloudflare record that I created with terraform then running terraform plan.

**Comment by andersla** [comment]
I also reproduced.
I think Cloudflare module should continue without error if record does not exist.

**Comment by andersla** [comment]
And possibly also continue without error if record already exists on apply.

**Comment by jychen7** [comment]
I meet this today too.

my work around is edit the state file to use new dns record identifier (which can be found in cloudflare api response) and increase the `serial` manually
