### ISSUE TITLE
remote-exec fails to exit on GCE

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#13071]
Creating a separate issue from #12859.

When running `remote-exec` on a Google Compute Engine instance, the last command never exits thus leaves Terraform in a broken state.

````
provisioner "remote-exec" {
      inline = [
            "sudo rm -f /root/.ssh/authorized_keys",
            "rm -f /home/ubuntu/.ssh/authorized_keys",
            "sudo rm -f /root/.zcompdump*",
            "rm -f /home/ubuntu/.zcompdump*",
            "sudo rm -f /home/justin/.zcompdump*",
            "sudo rm -f /home/node/.zcompdump*",
            "sudo /var/log/clean-logs.bash"
      ]
      connection {
            type = "ssh"
            user = "ubuntu",
            private_key = "${file("~/.ssh/google_compute_engine")}"
      }
}
````

When I ssh into the instance, I can see the command `sudo /var/log/clean-logs.bash` is stalled.

![c04bb7cc-117a-11e7-9eee-e1f07ae880ac](https://cloud.githubusercontent.com/assets/523312/24327130/aa750a54-117d-11e7-9743-1dfbfd0f01a1.png)

Running the same exact command  on the instance directly as the same ubuntu user `sudo /var/log/clean-logs.bash` runs and exits successfully with `exit code 0`.

**Comment by snowsky** [comment]
curious... why it is zsh in bash file?

**Comment by nodesocket** [comment]
Good question? All users use `zsh` and running `oh-my-zsh`. Could this be the issue?

**Comment by nodesocket** [comment]
Argg nevermind. `clean-logs.bash` got changed and `exec "$SHELL" -l` added to the bottom.

**Comment by nodesocket** [comment]
@snowsky curious is there a timeout _(max run-time for `remote-exec`)_?

**Comment by snowsky** [comment]
No, it will last forever for now, but it is a good enhancement to add. +1
