### ISSUE TITLE
dns create a record fails with: Error updating DNS record: dns: domain must be fully qualified

### ISSUE THREAD

**Issue by niekosau** [hashicorp/terraform#13095]
Hi,

i'm trying to update dns via provider/dns, but it fails with error:
```
* dns_a_record_set.www: Error updating DNS record: dns: domain must be fully qualified
```

terraform version:
```
v0.9.1
```

Affected resources
```
dns
```

configuration
```
provider "dns" {
  update {
    server = "10.5.253.230"
    key_name = "terraform"
    key_algorithm = "hmac-md5"
    key_secret = "xxxxxxxxxxxxxxxx"
  }
}

resource "dns_a_record_set" "www" {
  zone = "terr.lamoda.tech."
  name = "www"
  addresses = ["10.5.253.230"]
}
```
steps to reproduce:
```
terraform apply
```

Debug log:
[debug.log.zip](https://github.com/hashicorp/terraform/files/872797/debug.log.zip)

**Comment by kristjanelias** [comment]
@niekosau could you please try adding a "." to the end of your key name in the provider definition.
No need to change the key name in DNS conf.

So the provider would look like:
```
provider "dns" {
  update {
    server = "10.5.253.230"
    key_name = "terraform."
    key_algorithm = "hmac-md5"
    key_secret = "xxxxxxxxxxxxxxxx"
  }
}
```

Does this help you?

**Comment by niekosau** [comment]
Hi @kristjanelias,

yes, this did the trick.

**Comment by satyamguharoy** [comment]
Hi @kristjanelias,

I am getting an error while creating a record: _Error updating DNS record: 5_
Here is my tf configuration:

provider "dns" {
  update {
    server = "x.x.x.x"
  }
}

resource "dns_a_record_set" "test" {
  zone = "mysub.mydomain.com."
  name = "my-test"

  addresses = ["y.y.y.y"]
}

**Comment by kristjanelias** [comment]
Hi @satyamguharoy,

Is your DNS server set up to allow record changes without authentication?
If not you need a key defined that allows changes from the required network.

Also plase check the logs in your dns server.

**Comment by michalmedvecky** [comment]
This is undocumented and very confusing.

Also, `key_name` is documented as "Optional" (https://www.terraform.io/docs/providers/dns/index.html) but is mandatory.
