### ISSUE TITLE
what does "-backend=true" in terraform init (missing docs?)

### ISSUE THREAD

**Issue by martin-flaregames** [hashicorp/terraform#13115]
I'm creating a remote state using a S3 bucket (no migration from 0.8.x), this seems to work without problems but I fail to understand the meaning of the `-backend=true` parameter in `terraform init`. 

The result of creating the remote state **seems** to be the same, no matter if I specify the parameter or not.

Both the cli help and the online documentation state:

> -backend=true        Configure the backend for this environment.

But it is not clear what happens when the parameter is missing or set to `false`

### Terraform Version
`Terraform v0.9.1`

### Affected Resource(s)
- cli documentation  `terraform init --help`
- online documentation at https://www.terraform.io/docs/commands/init.html
- my brain

### Terraform Configuration Files
my project file is quite simple, but the terraform configuration boils down to this:
```hcl
variable "aws_access_key" {} # terraform.tfvars
variable "aws_secret_key" {} # terraform.tfvars
variable "aws_region" {} # terraform.tfvars

provider "aws" { access_key = "${var.aws_access_key}" secret_key = "${var.aws_secret_key}" region = "${var.aws_region}"}

terraform {
  backend "s3" {
    bucket = "flaregames-tfstate-devops"
    key = "remote-test/terraform.tfstate"
    region = "us-east-1"
  }
}
```
The same result is achieved by executing
```
terraform init -backend-config="access_key=XXXXXXXXXXXXXXXXXXXX" -backend-config="secret_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```
or
```
terraform init -backend=true -backend-config="access_key=XXXXXXXXXXXXXXXXXXXX" -backend-config="secret_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```
and then execute
```
terraform plan
terraform apply
```
to create the remote state in S3.

### Expected Behavior
The user (me) should know that `-backend=true` does

### Actual Behavior
The user cannot find out what the parameter does either by reading the www docs or the cli help.

**Comment by ankitforcode** [comment]
https://github.com/hashicorp/terraform/pull/16589
