### ISSUE TITLE
build: Travis not picking up vet errors

### ISSUE THREAD

**Issue by cblecker** [hashicorp/terraform#13122]
It seems that Travis isn't picking up vet errors:
- https://github.com/hashicorp/terraform/pull/12839
- https://github.com/hashicorp/terraform/pull/13121

Both of these were discovered on my local machine by just pulling down an updated master and running `make vet`. I'm not sure if this is intended, but it doesn't seem so.

**Comment by jbardin** [comment]
This is really strange. It's as if travis is running an old version of the vet tool, but it's supplied with the Go toolchain, so I'm not sure what could be going on.

Will have to investigate further.

**Comment by JamesBelchamber** [comment]
#13983 Is another example

**Comment by cblecker** [comment]
@jbardin @stack72 @phinze @mitchellh:
I know that Homebrew isn't an official Hashicorp supported method for distributing Terraform, but it is used by many.. these vet errors however are really a thorn in the side of getting new releases into Homebrew as they don't end up passing tests (which are used to verify that the binary versions Homebrew generates are safe for distribution).

Is it possible to get some priority on figuring out what is going on with Travis that it's consistently not picking up vet errors? Thank you!

**Comment by JamesBelchamber** [comment]
I think it's worth noting that these are tests that are failing,

**Comment by jbardin** [comment]
@cblecker,

Sorry that this is adversely affecting Homebrew, and it's certainly not our intention. We run the tests locally ourselves fairly often, but they sometimes still do slip past when people rely on the Travis tests to run the full suite. 

I spent some time on this, but we may need to see if we can get a response from someone at Travis-CI, as this points to a strange issue in their packaged go toolchain. I've also tried to force rebuilding the go tools in the .travis file, but that didn't seem to help either.

**Comment by cblecker** [comment]
I actually think I was able to track at least part of this down @jbardin, and it doesn't seem to be something specific to Travis.

Steps to reproduce:
- Checkout current master, and run `vagrant up` to start the Vagrant box using go1.8.1
- Once the Vagrant box is running, ssh into it
- Checkout v0.9.4, which has known vet issues (the ones fixed in #14001)
- Run `make vet`. This should run clean, despite there being actual vet issues.
- Run `make test` to run the unit test suite. The test suite should pass as there were no unit test issues in v0.9.4
- Run `make vet` again. This time, and with no code changes, the vet errors will be detected.

The quick fix to get Travis working again was to rearrange the order of the testing (as was done in https://github.com/hashicorp/terraform/pull/14010). I opened up a second PR to test this in https://github.com/hashicorp/terraform/pull/14011 and Travis successfully picked up the vet issues.

So! I'm not exactly sure which part of running the unit test is making this, but I'm guessing the `go test -i` part is installing a dependency.

**Comment by jbardin** [comment]
That's strange, because `go test -i` just runs `go install` on the deps, no source is actually added or changed, plus it's just an optimization because we run tests in batches and don't need to recompile every time 😕 .

I'd like to get vet to fail early again if we can, but this works for now, thanks @cblecker!
