### ISSUE TITLE
Security Groups do not allow ICMP

### ISSUE THREAD

**Issue by wazoo** [hashicorp/terraform#1313]
I was trying to create a security group with the following configuration:

```
ingress {
  protocol = "icmp"
  security_groups = ["${aws_security_group.sgr_test_nodes.id}"]
}
```
and I get the following error:
```
Errors:

  * 'aws_security_group.sgr_test_nodes' error: ingress.2.from_port: required field is not set
  * 'aws_security_group.sgr_test_nodes' error: ingress.2.to_port: required field is not set
```
While I understand why this error is happening, ICMP doesn't really have a port and if you try to specify one you get this error from amazon:

```
Error applying plan:

1 error(s) occurred:

* Error revoking security group ingress rules: ICMP code (65535) out of range (InvalidParameterValue)
```
Is there a specific way to configure ICMP?  From looking at [resource_aws_security_group.go](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_security_group.go) it didn't look that way so this may be a feature request, maybe a rule type or something so that way we could accomplish the ability to do "all tcp" or whatever without having to specify ports.

**Comment by rhiann0n** [comment]
The Terraform Resource for security groups with the AWS provider does allow ICMP, but I'm researching if complex custom rules can be added without writing a plugin or modifying source code.  Haven't found a solution to that, but hopefully HashiCorp will consider this a feature request?

Please allow Custom ICMP rules? (Its even tricky with the AWS CLI.)

Here is an example I found randomly online that should help you, @wazoo:
https://github.com/cransom/tf_aws_sg/blob/master/sg_vpn/main.tf

Hope that helps.

Rhiannon Portwood
Senior Operations Engineer
www.messagesystems.com
twitter @MessageSystems

**Comment by ltcdnunez** [comment]
I think I just sorted this out. As it happens, Amazon uses the same interface for CloudFormation and there is some documentation on how to use ICMP. The `from_port` is the ICMP type number and the `to_port` is the ICMP code (which does not exist for may types and should be either 0 or -1 in that case). See the [Amazon CloudFormation Documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html) for details. And here are the [ICMP types/codes](http://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml).

Here's an example of how to allow inbound echo requests:

```
ingress {
  protocol = 200
  cidr_block = "10.0.1.0/24"
  protocol = "icmp"
  from_port = 8
  to_port = 0
}
```

**Comment by catsby** [comment]
> The from_port is the ICMP type number and the to_port is the ICMP code 

That's... disappointing to hear... Network ACLs have an explicit `icmp_type` and `icmp_type` code parameter. I came here expecting I needed to add those here, but sadness...

Sounds like the solution for this issue then is to document this on the [Security Group][1] and [Security Group Rules][2] docs, agreed? 

[1]: https://terraform.io/docs/providers/aws/r/security_group.html
[2]: https://terraform.io/docs/providers/aws/r/security_group_rule.html

**Comment by ltcdnunez** [comment]
@catsby I discovered after this that the Network ACL rules break when attempting to use this because of exactly what you're saying about the `icmp_type` and `icmp_code` parameters. It looks like you submitted a pull request to fix this for issue #2148, however.

To be clear, ICMP works fine when creating Security Group Rules if you do what I described before, but not in Network ACL in terraform v0.51.0 (and presumably lower). This does appear to mirror the AWS API for Security Group Rules.

**Comment by seanknox** [comment]
For those out there who want to allow incoming ICMP echo ("ping") from any source via a security group, this does the trick:

```
  ingress {
    from_port = 8
    to_port = 0
    protocol = "icmp"
    cidr_blocks = ["0.0.0.0/0"]
  }
```

**Comment by stack72** [comment]
The [documentation](https://www.terraform.io/docs/providers/aws/r/security_group.html) has been updated to reflect ICMP. I am going to close this issue. If you feel that the documentation is not as clear as it can be, please let us know

Thanks

Paul
