### ISSUE TITLE
Bash script isn't interrpreted correctly in "EXTERNAL DATA SOURCE" provider

### ISSUE THREAD

**Issue by jflammia** [hashicorp/terraform#13136]
Attempting to use a Bash script to pull in AWS's CloudFront IP addresses for whitelisting.

Running Terraform v0.9.2

Here is the relevant code:
```
data "external" "cloudfront_ip_addresses" {
  program = ["bash", "${path.module}/scripts/get_cloudfront_ips.sh"]
}
```

get_cloudfront_ips.sh script:
```
#!/bin/sh

wget -qO- https://ip-ranges.amazonaws.com/ip-ranges.json | jq '.prefixes[] | select(.service=="CLOUDFRONT") | .ip_prefix' | sort -V -t '/' -k 1 | jq --slurp
```

I can execute this script from my shell and get the expected output.  However, when Terraform executes it (during `terraform get -update=true && terraform plan`), I get the following output:
```
Error refreshing state: 1 error(s) occurred:

* module.utils.data.external.cloudfront_ip_addresses: 1 error(s) occurred:

* module.utils.data.external.cloudfront_ip_addresses: data.external.cloudfront_ip_addresses: failed to execute "bash": jq - commandline JSON processor [version 1.5-1-a5b5cbe]
Usage: jq [options] <jq filter> [file...]

	jq is a tool for processing JSON inputs, applying the
	given filter to its JSON text inputs and producing the
	filter's results as JSON on standard output.
	The simplest filter is ., which is the identity filter,
	copying jq's input to its output unmodified (except for
	formatting).
	For more advanced filters see the jq(1) manpage ("man jq")
	and/or https://stedolan.github.io/jq

	Some of the options include:
	 -c		compact instead of pretty-printed output;
	 -n		use `null` as the single input value;
	 -e		set the exit status code based on the output;
	 -s		read (slurp) all inputs into an array; apply filter to it;
	 -r		output raw strings, not JSON texts;
	 -R		read raw strings, not JSON texts;
	 -C		colorize JSON;
	 -M		monochrome (don't colorize JSON);
	 -S		sort keys of objects on output;
	 --tab	use tabs for indentation;
	 --arg a v	set variable $a to value <v>;
	 --argjson a v	set variable $a to JSON value <v>;
	 --slurpfile a f	set variable $a to an array of JSON texts read from <f>;
	See the manpage for more options.
```

As a check, I manually execute the script the Terraform got:
`bash /home/example-user/Code/example-terraform-live/providers/aws/us-east-2/utils/.terraform/modules/fc93bbf9263a507eb15135a69c13cc04/aws/environments/utilities/scripts/get_cloudfront_ips.sh`

This produces the correct results.

At this point, I'm not sure if I did something wrong or there is an issue with Terraform but I'm leaning towards the latter.

**Comment by jflammia** [comment]
This is a duplicate of #12249

**Comment by shellshock1953** [comment]
@jflammia can`t understand, why this question is duplicate to #12249?
I have similar problem:

```
data "external" "test" {
  program = [ "jq" ]
  query {
    test = "test"
  }
}
output "external" {
  value = "${data.external.test.result}"
}
```
Same result, seems that jq did not get any data.
All I need to proceed query (test="test") with jq (it would be desirable not to use bash, jq can handle stdin/stdout).

**Comment by jflammia** [comment]
@shellshock1953 See the comment I left on #12249 which explains why I closed this issue in favor of that one.
