### ISSUE TITLE
terraform init reconfigures backend every time

### ISSUE THREAD

**Issue by drieselliott** [hashicorp/terraform#13149]
Hi there,

### Terraform Version
0.9.2

### Affected Resource(s)
- Terraform core - init command

### Terraform Configuration Files
```hcl
terraform {
  required_version = "0.9.2"

  backend "s3" {
  }
}
```

### Expected Behavior
Terraform init detects that I have already reconfigured my backend to use S3 and doesn't do it on every run.

### Actual Behavior
```
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.
```

### Steps to Reproduce
1. Run Terraform init
```
REGION="eu-west-1"

terraform init \
    -get=true \
    -input=false \
    -force-copy \
    -backend=true \
    -backend-config "bucket=some-bucket" \
    -backend-config "key=system-development" \
    -backend-config "region=$REGION"
```
2. Terraform init states that the back-end is successfully reconfigured
3. Run Terraform init again (same command as in step 1)
4. Terraform init again states that the back-end was reconfigured

### Important Factoids
I'm running Terraform as part of a CI/CD pipeline. For this reason Terraform init is run every time we run any Terraform command to make sure that the state is set-up correctly. In our CI/CD pipeline we also don't know whether an environment already exists up front.

**Comment by manuwelakanade** [comment]
Facing the same issue

**Comment by jbardin** [comment]
@manuwelakanade,

While I am able to reproduce an issue that prevents re-initializing a backend after removing the lock_table argument, I can't seem to reproduce your issue specifically. See issue #13215

If there is an `ID` value in the Lock Info, it mush be coming from somewhere. Are you certain you're looking at the right table, in the right region for the stale lock?

**Comment by jing-emma** [comment]
@manuwelakanade @jbardin 
I got the same issue. Although terraform failed to acquire a state lock, it still applied the infra change. I got "Apply complete! Resources: 4 added, 0 changed, 0 destroyed." after the error message shown below. 

Error locking destination state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed
	status code: 400, request id: JEFSL5N7HBRN4NTSG3V6306DU3VV4KQNSO5AEMVJF66Q9ASUAAJG
Lock Info:
  ID:        21f4af9f-ad30-e2fe-031f-dc7df12ee90e
  Path:      XXXX/XX.tfstate
  Operation: migration
  Who:       XXXXX
  Version:   0.9.2
  Created:   2017-04-06 19:02:37.095196416 +0000 UTC
  Info:      source state
Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.

...
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

**Comment by jbardin** [comment]
@jing-emma,

Can you provide the complete command you used in that execution? It looks like a stale lock from `init` migration, but _any_ lock should have prevented Terraform from applying.

**Comment by jing-emma** [comment]
Thanks @jbardin 
These are the command that I used. 

terraform init \
    -backend=true \
    -backend-config "bucket=tfState-$account" \
    -backend-config "key=$stack.tfstate" \
    -backend-config "region=$region"

terraform apply \
    -var stackName=$stack \
    -var accountId=$account \
    -var runtime=$runtime \
    -var color=$color
And In my terraform file I have 
terraform {
  backend "s3" {
    lock_table="terraform_locks"
  }
}

I found that it always detected that my Backend configuration changed and ask me "Do you want to copy the state from S3?", but actually I didn't change my backend config. 
If I answer no, I didn't see the lock issue and have the infra change applied successfully. But if I say yes, I always got the lock issue. 


Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.


Do you want to copy the state from "s3"?
  Would you like to copy the state from your prior backend "s3" to the
  newly configured "s3" backend? If you're reconfiguring the same backend,
  answering "yes" or "no" shouldn't make a difference. Please answer exactly
  "yes" or "no".

  Enter a value: no

**Comment by jbardin** [comment]
@jing-emma,

Maybe I'm misunderstanding here, but are you saying that terraform reported that lock error _during apply_, then proceeded to complete the apply? 

If the lock error was only during `init`, then that is fixed in the next release. If `apply` somehow managed to bypass the lock, that is more concerning.

**Comment by jing-emma** [comment]
@jbardin 
since I run terraform init and apply together in a script, I was not sure which command threw lock error. Now I am sure that the error is thrown by init. apply works fine. Thanks

**Comment by hussfelt** [comment]
+1 on this issue

**Comment by funkydorian** [comment]
+1 on that issue as well
