### ISSUE TITLE
AWS resource SSM parameter store

### ISSUE THREAD

**Issue by eredi93** [hashicorp/terraform#13142]
I saw that the SSM document is available https://www.terraform.io/docs/providers/aws/r/ssm_document.html, I was wondering if anyone is working on the SSM parameter store resource. i'd love to start manage them with terraform.

**Comment by nathanielks** [comment]
Duplicate: https://github.com/hashicorp/terraform/issues/11433

**Comment by ozbillwang** [comment]
Should be closed. This resource has been added in release v0.9.7
