### ISSUE TITLE
aws_alb_target_group stickiness value not being refreshed/updated when changed outside terraform

### ISSUE THREAD

**Issue by rbm-aalsaleh** [hashicorp/terraform#13167]
If you update the stickiness value to false in aws console/api, terraform does not see that it has been changed when running plan/apply.

### Terraform Version
I am using terraform 0.9.1 as it's the latest available via brew, however I downloaded 0.9.2 and had the same results.

```
~/Downloads/terraform -v
Terraform v0.9.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_alb_target_group

### Terraform Configuration Files
```hcl
resource "aws_alb_target_group" "vmm-alb" {
  lifecycle {
    create_before_destroy = true
  }
  name     = "${var.stack_name}"
  port     = 8000
  protocol = "HTTP"
  vpc_id   = "${var.vpc-id}"
  health_check {
    healthy_threshold   = 2
    unhealthy_threshold = 2
    timeout             = 3
    path                = "/status.html"
    interval            = 30
  }
  stickiness {
    type = "lb_cookie"
    enabled = true
  }
}.
```

### Debug Output
* output of api call describing target group parameters https://gist.github.com/rbm-aalsaleh/e355d703565f30ebf117b49e9b9adb13
* output of terraform plan https://gist.github.com/rbm-aalsaleh/37997e8eb20cd62a7bce5c1eac8c132b

### Expected Behavior
stickiness policy change should be detected

### Actual Behavior
Terraform saw no changes

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` to bring up the resource
2. change stickiness policy in aws console or api
3. `terraform plan/apply` terraform detects no changes so it is not reverted

### Important Factoids
- s3 remote backend

**Comment by stack72** [comment]
Hi @rbm-aalsaleh 

Thanks for the issue report here - I have just opened a PR that will fix the issue! Really got catch with this one

Paul

**Comment by rbm-aalsaleh** [comment]
Great! thanks!
