### ISSUE TITLE
Support EC2 Instance Tag on Creation

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform#13173]
Per https://aws.amazon.com/blogs/aws/new-tag-ec2-instances-ebs-volumes-on-creation/ quoted below and go-aws-sdk 1.8.4 being upgraded in #13152, it will soon be possible to have EC2/EBS tagging done on resource creation. It would be fantastic to have this supported in Terraform! A pain point for us right now is root EBS volume tagging, which this should theoretically solve.

> You now have the ability to specify tags for EC2 instances and EBS volumes as part of the API call that creates the resources (if the call creates both instances and volumes, you can specify distinct tags for the instance and for each volume). The resource creation and the tagging are performed atomically; both must succeed in order for the operation (RunInstances, CreateVolume, and other functions that create resources) to succeed. You no longer need to build tagging scripts that run after instances or volumes have been created.

### Affected Resource(s)

- aws_instance

### Expected Behavior

The Terraform aws_instance resource configuration supports the new tag on creation behavior.

**Comment by stack72** [comment]
Hi @bflad 

I am currently implementing this - it will be part of Terraform 0.9.3 hopefully :)

Paul

**Comment by existancenext** [comment]
Any progress on this enhancement?

**Comment by majormoses** [comment]
@stack72 I don't suppose this would not support root volumes on launch configs would it?
