### ISSUE TITLE
built in unit conversion ability

### ISSUE THREAD

**Issue by wazoo** [hashicorp/terraform#1317]
It would be cool to have a feature to be able to convert units in shorthand, as such:

```
resource "aws_db_parameter_group" "test" {
    name = "test"
    family = "mysql5.6"
    description = "RDS default parameter group"
    parameter {
      name = "read_rnd_buffer_size"
      value = "${in_bytes("1MB")}"
      apply_method  = "pending-reboot"
    }
}
```
This is kinda minor but it would save time from having to convert back and forth for sizes of disks and things. (so I could do like in_gb("4T") for an EBS volume or something).

**Comment by phinze** [comment]
Thanks for this idea! We'd definitely consider a PR along these lines, but I'm going to close this issue for now to indicate that no core team members are likely to pick up this work anytime soon.
