### ISSUE TITLE
Allow configurable `keyEnvPrefix`

### ISSUE THREAD

**Issue by voltechs** [hashicorp/terraform#13184]
### Terraform Version
0.9.2

### Affected Resource(s)
remote state backend (s3)

### Terraform Configuration Files
```hcl
terraform {
	required_version = ">= 0.9.2"
	backend "s3" {
		bucket = "platform-infrastructure"
		key = "environments/alpha/master.tfstate"
		region = "us-west-2"
	}
}
```

### Expected Behavior
I expect not to be forced into some hand-held path by a tool (terraform) for advanced users (anybody who uses terraform).

Read: let me configure `keyEnvPrefix`. I've already created my own bucket, and nested my environment files under `/environments/{environment}/master.tfstate`

### Actual Behavior
My states are stored and pulled from `platform-infrastructure/env:/alpha/environments/alpha/master.tfstate

The first `alpha` originating from terraform env, and the second `alpha` comes from my own (legacy) namespacing. (We're migrating from self-managed environments to TF managed)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Try to use terraform with an S3 backend

**Comment by gmetzker** [comment]
I agree.  This would be nice if there was more flexibility with how this key prefix works when using multiple environments.
