### ISSUE TITLE
Feature Request: Support Runtime Configurator

### ISSUE THREAD

**Issue by hienle-hps** [hashicorp/terraform#13189]
Are there any plans to support  GCP's hierarchical key-value store [Runtime Configurator](https://cloud.google.com/deployment-manager/runtime-configurator/) or is it lower priority since Consul can provide the same functionality?

**Comment by danawillow** [comment]
Hey @hienle-hps, no immediate plans (at least on my end) but feel free to send a PR if it's something you'd like to see sooner :)

**Comment by paddyforan** [comment]
Just wanted to chime in on this that the priority is _entirely_ independent of whether HashiCorp offers an alternative solution; our philosophy is that you should be able to use our tools with the tools that work best for you, regardless of who makes them. The low priority is just based on the number of user requests we see for it; that being said, if a bunch of people 👍 this issue or something looking for that resource, its priority would get bumped. We just only have so many hours. :)
