### ISSUE TITLE
aws_security_group: no way to specify "no ingress"/"no egress"

### ISSUE THREAD

**Issue by astewart-consensus** [hashicorp/terraform#13181]
If an aws_security_group is defined with one or more ingress rules, then terraform will make sure that those rules, and only those rules, are defined on the security group, and if (for example) somebody (either manually or through an old terraform config) adds a rule that shouldn't be there, terraform will remove it the next time it is run.  (This is expected, and desirable)

However, if a security group is defined with *no* ingress rules, terraform does not actually enforce this, and instead leaves any existing rules untouched.  As far as I can tell, there is therefore no way to tell terraform "this group should have no ingress rules, and you should remove any that are currently there".

(The same appears to be true for egress rules, if no egress rules are defined in the TF config)

This is a substantial problem, because it also means it is not possible to remove existing rules (even if they were previously created by terraform) if the result would be an empty list.  It is also not possible to ensure that a security group which is not supposed to have any rules does in fact not allow access it's not supposed to.

### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
- aws_security_group

### Terraform Configuration Files
```hcl
provider "aws" {
    region = "${var.aws_region}"
}

resource "aws_security_group" "test" {
  name        = "test_sg"
  description = "Test security group (with no ingress rules)"
  vpc_id      = "${var.vpc_id}"
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

### Expected Behavior
TF should remove any ingress rules previously present on the resource

### Actual Behavior
TF leaves existing rules untouched, even though they're not in the TF config

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Manually add an ingress rule to the security group
3. `terraform apply`
4. Note that no changes were made and the manual change persists.

**Comment by crielly** [comment]
Am also experiencing this and it's obviously a big problem.

**Comment by deftflux** [comment]
My pull request https://github.com/hashicorp/terraform/pull/14332 would fix this.  If an `aws_security_group_rules` resource is defined with no ingress and/or egress rules, it will enforce that.

**Comment by matteomazza91** [comment]
is there a regression for this?

```
Terraform v0.12.6
+ provider.aws v2.33.0
```
