### ISSUE TITLE
Add path style method option to s3 backend

### ISSUE THREAD

**Issue by mcanevet** [hashicorp/terraform#13194]
Hello,

We have an s3-like service powered by minio. When I configure the remote store using the s3 backend, it tries to use S3's Virtual-Hosted Style Method and, as we do not have a wildcard pointing to our s3 service, it does not work.
S3 also support Path Style method, it would be great to have an option in Terrfaform's S3 backend so that we can configure it like that :

```hcl
terraform {
  backend "s3" {
    bucket   = "my_bucket"
    key      = "foo/terraform.tfstate"
    endpoint = "https://s3.example.com"
    profile  = "my_profile"
    region   = "us-east-1"
    use_path_request_style = true
  }
}
```

so that it generates a request `https://s3.example.com/my_bucket/foo/terraform.tfstate` instead of `https://my_bucket.s3.example.com/foo/terraform.tfstate`.

Thanks

**Comment by stffabi** [comment]
The option `force_path_style` has been added with fb6b349e580b1cbb9053c09f97f8424d63d0716f

**Comment by mcanevet** [comment]
Thanks
