### ISSUE TITLE
Feature Request : Exception in Terraform Destroy

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform#13192]
It would be great if we can some optional exceptions while running `terraform destroy` on a module. My use case: 
I have Jenkins Module which backs/restore to a specified bucket/object in S3. Since this bucket/object is unique, I am also creating it thru the module itself. Now, if I destroy the module it also destroys the buckets as well.

**Comment by apparentlymart** [comment]
Hi @vikas027! Thanks for this feature request

I think we would likely implement this as a facet of what was requested in #2253, which might come as part of #4149. Given a generic exclusion mechanism I think we would get destroy exclusion "for free", so I'm going to close this one and just consider this part of the scope of one of the others here.

**Comment by vikas027** [comment]
Thanks @apparentlymart 👍
