### ISSUE TITLE
Configurable timeouts for google_container_cluster

### ISSUE THREAD

**Issue by Stono** [hashicorp/terraform#13198]
### Terraform Version
- 0.8.7

### Affected Resource(s)
- google_container_cluster

### Detail
Hi; as we have quite a complicated cluster; it can take a while to do a "node_version" update, this is because kubernetes moves things around without downtime whilst upgrading our multiple underlying VMs in sequence.

As a result, this operation can take around 15 minutes, and the timeouts for this resource appear to be locked at 10m; resulting in an error.

Please could we have configurable timeouts for this resource?

```
timeouts {
  create = "10m"
  update = "20m"
}
```

**Comment by sovanesyan** [comment]
How does this look? #13203

**Comment by Stono** [comment]
@sovanesyan that is some epic response time.  Looks good
