### ISSUE TITLE
Google provider API error with Zone

### ISSUE THREAD

**Issue by luhkevin** [hashicorp/terraform#13219]
### Terraform Version
Terraform v0.8.6

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "google" {
  credentials = "${file("${var.credentials_file_path}")}"
  project = "${var.project_name}"
  region = "${var.region}"
}

resource "google_compute_instance" "launch-test" {
  count = 1
  name = "${var.instance_name}"
  machine_type = "${var.machine_type}"
  zone = "${var.region}"

  disk {
    image = "${var.disk_image}" // the operating system (and Linux flavour) that your machine will run
    size = 80
  }
 
  metadata {
    ssh-keys = "${var.ssh_username}:${file("${var.public_key_path}")}"
  }

  create_timeout = 15

  network_interface {
    network = "default"
    access_config {
      // Ephemeral IP - leaving this block empty will generate a new external IP and assign it to the machine
    }
  }

  // docker auth
  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      user        = "${var.ssh_username}"
      private_key = "${file("${var.private_key_path}")}"
      agent       = false
    }

    inline = [
      "mkdir -p /home/${var.ssh_username}/.docker"
    ]
  }

  provisioner "file" {
    source = "${var.docker_credentials_file_path}"
    destination = "/home/${var.ssh_username}/.docker/config.json"

    connection {
      type        = "ssh"
      user        = "${var.ssh_username}"
      private_key = "${file("${var.private_key_path}")}"
      agent       = false
    }
  }

  provisioner "file" {
    source = "${var.parent_exec_script_dir}/${var.local_exec_script_dir}"
    destination = "/tmp"

    connection {
      type        = "ssh"
      user        = "${var.ssh_username}"
      private_key = "${file("${var.private_key_path}")}"
      agent       = false
    }
  }

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      user        = "${var.ssh_username}"
      private_key = "${file("${var.private_key_path}")}"
      agent       = false
    }

    inline = [
      "chmod +x /tmp/${var.local_exec_script_dir}/${var.exec_script}",
      "/tmp/${var.local_exec_script_dir}/${var.exec_script} ${var.exec_args}"
    ]
  }
}
```

### Debug Output
I will post the actual debug output if I'm able to reproduce it. For now, here is the terraform output: https://gist.github.com/luhkevin/0972e83ff427a91ede5a7da5562fa432

I managed to reproduce it, here's the gist (It's quite long):
https://gist.github.com/luhkevin/34a2619d05f0d36761a68bd1030082b8

### Expected Behavior
Terraform should have gotten the list of zones correctly

### Actual Behavior
This works correctly most of the time (75%-ish, so far). But the other times, Terraform errors out and prints:
```
google_compute_instance.launch-test: Error loading zone 'us-west1-b': Get https://www.googleapis.com/compute/v1/projects/my-project-id/zones/us-west1-b?alt=json: stream error: stream ID 1; PROTOCOL_ERROR
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
I just ran the standard command: `terraform apply -state=terraform.tfstate -state-out=terraform.tfstate ./terraform`

**Comment by luhkevin** [comment]
EDIT: I've managed to reproduce this with debug logging on, and I've updated the above with another gist.

**Comment by paddyforan** [comment]
Hi @luhkevin! Sorry for the trouble, and thanks for opening an issue. Gonna try to get to the bottom of this, so sorry for the late response.

What is your `region` variable set to?

**Comment by luhkevin** [comment]
No problem. I was able to fashion a workaround simply by retrying the terraform request. I suspect it might even be an issue in the Go SDK for google cloud...

My `region` is set to `us-west1-b`

**Comment by wendorf** [comment]
I'm also getting a lot of this stream errors, which is making it very hard to get a successful run. The stream errors are happening on refresh (I think), which is causing my state file to not get updated correctly and a subsequent run fails because it finds resources with the names it is trying to create now (that it created in the previous run) and fails.
