### ISSUE TITLE
aws_alb_target_group_attachment errors out when multiple instance id's used

### ISSUE THREAD

**Issue by sbatchu0108** [hashicorp/terraform#13224]
Hi there,

### Terraform Version
`Terraform v0.8.8`

### Affected Resource(s)
- aws_alb_target_group_attachment

### Debug Output
1 error(s) occurred:

* aws_alb_target_group_attachment.xxxx-xxx: Error registering targets with target group: ValidationError: An instance ID must be specified
	status code: 400, request id: 6916e0d0-1585-11e7-a88b-a33f890c099b

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior
Alb target group should be attached with the newly created instances.

### Actual Behavior
Unable to register instances:
module.vault-elb.aws_alb_target_group_attachment.hcvault-dev: Creating...
  port:             "" => "80"
  target_group_arn: "" => "arn:aws:elasticloadbalancing:us-east-1:xxxxxx:targetgroup/xxxx-xxxx/acxxxxxxx"
  target_id:        "" => "<computed>"
module.consul-agent.null_resource.dummy_dependency: Creating...
  triggers.%:             "" => "1"
  triggers.dependency_id: "" => "i-xxxxxx,i-xxxxxx,i-xxxxx"
module.consul-agent.null_resource.dummy_dependency: Creation complete
 ValidationError: An instance ID must be specified
	status code: 400, request id: 6916e0d0-1585-11e7-a88b-a33f890c099b

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create Main.tf with 3 modules sections where first module section creates consul server based on the count.
2. Second module section depends on the first module to be executed then creates the consul agent servers based on the count.
3. Third module depends on second module output and then creates alb and targetgroup which attaches the instance id's from the second module output to the target groups.

**Comment by sbatchu0108** [comment]
@grubernaut Is there any ETA when this issue will be addressed ?

**Comment by grubernaut** [comment]
Hi @sbatchu0108, thanks for the issue. 

As far as I know, nobody internally has started working on this issue, and we don't have an ETA.

As maintainers we tag opened issues so they are easier to find in the future, but that doesn't necessarily mean work has begun on fixing the issue. While it is not our intention to leave issues open for an extended period of time, there are only a few maintainers working on the Terraform project, we currently have over 1700 open issues to tackle, and can't work on all of them at once.  We would gladly accept a PR for this issue in the meantime, but definitely appreciate patience while we work on this. Thanks! ❤️
