### ISSUE TITLE
aws_elb does not create listeners on Eucalyptus if *_protocol is http and not HTTP

### ISSUE THREAD

**Issue by zvainio** [hashicorp/terraform#13235]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
- aws_elb

### Terraform Configuration Files
```hcl
resource "aws_elb" "demo" {
  name = "${var.tf_prefix}elb"

  # The same availability zone as our instance
  availability_zones = ["${aws_instance.demo.availability_zone}"]
  # The instance is registered automatically
  instances = ["${aws_instance.demo.id}"]
  #
  cross_zone_load_balancing = true
  idle_timeout = 300
  connection_draining_timeout = 0

  listener {
    instance_port = 80
    instance_protocol = "HTTP"
    lb_port = 80
    lb_protocol = "HTTP"
  }

  tags {
    name = "${var.tf_prefix}elb-tag"
  }
}
```

### Logs
terraform plan
+ aws_elb.demo
    availability_zones.#:                   "<computed>"
    connection_draining:                    "false"
    connection_draining_timeout:            "0"
    cross_zone_load_balancing:              "true"
    dns_name:                               "<computed>"
    health_check.#:                         "1"
    health_check.0.healthy_threshold:       "2"
    health_check.0.interval:                "10"
    health_check.0.target:                  "TCP:80"
    health_check.0.timeout:                 "3"
    health_check.0.unhealthy_threshold:     "5"
    idle_timeout:                           "300"
    instances.#:                            "<computed>"
    internal:                               "<computed>"
    listener.#:                             "1"
    listener.3057123346.instance_port:      "80"
    listener.3057123346.instance_protocol:  "http"
    listener.3057123346.lb_port:            "80"
    listener.3057123346.lb_protocol:        "http"
    listener.3057123346.ssl_certificate_id: ""
    name:                                   "TVTF-elb"
    security_groups.#:                      "<computed>"
    source_security_group:                  "<computed>"
    source_security_group_id:               "<computed>"
    subnets.#:                              "<computed>"
    tags.%:                                 "1"
    tags.name:                              "TVTF-elb-tag"
    zone_id:                                "<computed>"

terraform apply

aws_elb.demo: Creating...
  availability_zones.#:                   "" => "1"
  availability_zones.2812906845:          "" => "es-ka-eu-dev_1"
  connection_draining:                    "" => "false"
  connection_draining_timeout:            "" => "0"
  cross_zone_load_balancing:              "" => "true"
  dns_name:                               "" => "<computed>"
  health_check.#:                         "" => "1"
  health_check.0.healthy_threshold:       "" => "2"
  health_check.0.interval:                "" => "10"
  health_check.0.target:                  "" => "TCP:80"
  health_check.0.timeout:                 "" => "3"
  health_check.0.unhealthy_threshold:     "" => "5"
  idle_timeout:                           "" => "300"
  instances.#:                            "" => "1"
  instances.1726855370:                   "" => "i-a38638d1"
  internal:                               "" => "<computed>"
  listener.#:                             "" => "1"
  listener.3057123346.instance_port:      "" => "80"
  listener.3057123346.instance_protocol:  "" => "http"
  listener.3057123346.lb_port:            "" => "80"
  listener.3057123346.lb_protocol:        "" => "http"
  listener.3057123346.ssl_certificate_id: "" => ""
  name:                                   "" => "TVTF-elb"
  security_groups.#:                      "" => "<computed>"
  source_security_group:                  "" => "<computed>"
  source_security_group_id:               "" => "<computed>"
  subnets.#:                              "" => "<computed>"
  tags.%:                                 "" => "1"
  tags.name:                              "" => "TVTF-elb-tag"
  zone_id:                                "" => "<computed>"
aws_elb.demo: Creation complete (ID: TVTF-elb)

terraform show
aws_elb.demo:
  id = TVTF-elb
  access_logs.# = 0
  availability_zones.# = 1
  availability_zones.2812906845 = es-ka-eu-dev_1
  connection_draining = false
  connection_draining_timeout = 0
  cross_zone_load_balancing = true
  dns_name = TVTF-elb-000858508220.lb.es-ka-eu-dev.eecloud.nsn-net.net
  health_check.# = 1
  health_check.0.healthy_threshold = 2
  health_check.0.interval = 10
  health_check.0.target = TCP:80
  health_check.0.timeout = 3
  health_check.0.unhealthy_threshold = 5
  idle_timeout = 300
  instances.# = 1
  instances.1726855370 = i-a38638d1
  internal = false
  listener.# = 0
  name = TVTF-elb
  security_groups.# = 0
  source_security_group = 000308098323/euca-internal-000858508220-TVTF-elb
  subnets.# = 0
  tags.% = 1
  tags.name = TVTF-elb-tag
  zone_id =

### Expected Behavior
Listerner should be created

### Actual Behavior
Listener was missing

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This is HPE Helion Eucalyptus version 4.4.
EC2 classic ELB is in use
All the examples instance_protocol = "http" and lb_protocol = "http" but this does not work on Eucalyptus.  Should use upper case HTTP instead.

**Comment by catsby** [comment]
Hello there! Using “AWS-like" platforms like Eucalyptus with the Terraform AWS provider is not officially supported. We try to build the AWS provider in such a way that it's possible to configure it to work, but we don't pro-actively run the automated acceptance tests against these other platforms. 

We have no plans to make Terraform explicitly or intentionally _not_ work with Eucalyptus or other AWS-like platforms, but we can't guarantee compatibility either.
