### ISSUE TITLE
Support Google Cloud Functions

### ISSUE THREAD

**Issue by pilwon** [hashicorp/terraform#13233]
Please support [Google Cloud Functions](https://cloud.google.com/functions/), ideally something similar to [aws_lambda_function](https://www.terraform.io/docs/providers/aws/r/lambda_function.html) resource.

**Comment by nodesocket** [comment]
👍 

This is just a thought on perhaps a schema:

```
resource "google_compute_function" "foobar" {
    name = "foobar"
    region = "us-central-1"
    memory = "256"
    timeout = 60
    trigger = "http"

    source {
       zip_file = "~/foobar.zip"
       storage_bucket = "gs://myfunctionstorage/foobar"
       function = "helloWorld"
    }
}
````

**Comment by paddyforan** [comment]
Hi! We would _love_ to support Cloud Functions, and it's definitely something we'd like to get to. Just to set expectations appropriately, however, as far as I know none of the GCP provider maintainers has this on their immediate radars as far as next things to work on. Pull requests and user interest (most helpfully expressed by 👍ing the issue, not posting +1 comments) do move things up our priority queues, but we only have so many hours in the day, so sometimes things take time.

**Comment by milieuChris** [comment]
We will likely take a stab at a toss away version of this functionality. Our struggle is with the differences between walled gardens when it comes to writing APIs using functions on the top three cloud platforms. No matter what though we consider this important for both developer and operations workflows and pipelines. We are new to using the Hashicorp ecosystem though, so no promises! Only that we will share whatever we come up with when/if we start using it internally.
