### ISSUE TITLE
Support for external_id and session_name in s3 backend assume_role

### ISSUE THREAD

**Issue by bjornrog** [hashicorp/terraform#13234]
We need support for external_id in the s3 backend, so we can use the same credentials as for the aws provider.

I have looked at the code and it seems to be a very simple fix, as the AWS auth mechanism used by the backend is the same as for the aws provider.

I have written a working version, but was not able to branch (ERROR: Permission to hashicorp/terraform.git denied to ...).

**Comment by tombuildsstuff** [comment]
Hi @bjornrog 

Thanks for both reporting and taking a look into this :)

> I have written a working version, but was not able to branch (ERROR: Permission to hashicorp/terraform.git denied to ...).

We're using Forks to allow contributors to propose changes to Terraform via Pull Requests - which means that (most) contributors don't have direct push access to this repository (which is the error you're seeing here).

It appears that you haven't created a Fork yet, so [there's some more information available here](https://help.github.com/articles/fork-a-repo/) - but essentially you can create a Fork by pressing the "fork" button in the top right of this page. Once the fork exists, you can add it to your local Terraform clone by using the following commands:

```
git remote add bjornrog git@github.com:bjornrog/terraform.git
```

At this point you should be able to push the changes to your Fork via:

```
git push bjornrog <branchname>
```

Once that's done - you can then open a Pull Request :)

Thanks!

**Comment by tombuildsstuff** [comment]
Hi @bjornrog 

Thanks for both reporting and taking a look into this :)

> I have written a working version, but was not able to branch (ERROR: Permission to hashicorp/terraform.git denied to ...).

We're using Forks to allow contributors to propose changes to Terraform via Pull Requests - which means that (most) contributors don't have direct push access to this repository (which is the error you're seeing here).

It appears that you haven't created a Fork yet, so [there's some more information available here](https://help.github.com/articles/fork-a-repo/) - but essentially you can create a Fork by pressing the "fork" button in the top right of this page. Once the fork exists, you can add it to your local Terraform clone by using the following commands:

```
git remote add bjornrog git@github.com:bjornrog/terraform.git
```

At this point you should be able to push the changes to your Fork via:

```
git push bjornrog <branchname>
```

Once that's done - you can then open a Pull Request :)

Thanks!
