### ISSUE TITLE
Terraform plan fails when enabling streams on an existing table and using the stream_arn

### ISSUE THREAD

**Issue by drieselliott** [hashicorp/terraform#13245]
Hi there,

### Terraform Version
0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_dynamodb_table
- aws_lambda_event_source_mapping

This might be an issue in how Terraform core handles its planning logic.

### Terraform Configuration Files
Initial script:

```hcl
resource "aws_dynamodb_table" "table" {
  name = "table"
  read_capacity = 1
  write_capacity = 1
  hash_key = "hash"

  attribute {
    name = "hash"
    type = "S"
  }
}
```

After adding Lambda function:
```hcl
resource "aws_dynamodb_table" "table" {
  name = "table"
  read_capacity = 1
  write_capacity = 1
  hash_key = "hash"
  stream_enabled = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "hash"
    type = "S"
  }
}

resource "aws_lambda_function" "function" {
# Contents of Lambda function are not relevant
}

resource "aws_lambda_event_source_mapping" "stream_mapping" {
  event_source_arn = "${aws_dynamodb_table.table.stream_arn}"
  function_name = "${aws_lambda_function.function.arn}"
  starting_position = "LATEST"
  batch_size = 250
  enabled = true
}
```

### Expected Behavior

* Enable streams on an existing table
* Linked the stream to a lambda function
* Run 'terraform plan'
* Plan shows enabling streams on the table and adding the stream

### Actual Behavior

When we run 'terraform plan' we see the error "property aws_dynamodb_table.table.stream_arn does not exist". It seems to me that Terraform is looking at its state file and not finding the stream_arn on the table, since streams were not enabled in the past and therefore it fails.

### Steps to Reproduce

* Create script like in initial set-up above
* Run 'terraform apply' to set up the table
* Update the script to the second script posted above (taking into account that the above is not a fully working example in order to limit the content to the important parts)
* Run 'terraform plan'
* The planning will fail

**Comment by miguelgrinberg** [comment]
I experienced this as well. In case it helps anyone, it seems the `stream_arn` property of the dynamodb table works fine when the streaming was enabled beforehand, so a simple workaround is to only enable the streaming on the table and run terraform with that, then add the lambda event source mapping in a second pass.
