### ISSUE TITLE
provider/aws Support Analytics Configurations for S3 Buckets

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform#13246]
AWS has recently announced some support for additional analytics and metrics for S3 buckets: https://aws.amazon.com/blogs/aws/s3-storage-management-update-analytics-object-tagging-inventory-and-metrics/

In order to support the above, the implementation in the AWS API is with methods like `GetBucketAnalyticsConfiguration` and `PutBucketAnalyticsConfiguration` which were added in go-aws-sdk 1.5.11.

### Affected Resource(s)

- aws_s3_bucket (but likely a new resource)

### Expected Behavior

Terraform configuration should support enabling and managing AWS S3 analytics configurations.

### References

* http://docs.aws.amazon.com/AmazonS3/latest/dev/analytics-storage-class.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.GetBucketAnalyticsConfiguration
* https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.PutBucketAnalyticsConfiguration
* https://github.com/aws/aws-sdk-go/commit/b4916cc32444fcca7ff773d1279b9c556c9cca10

**Comment by bflad** [comment]
Per https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/, migrating this to terraform-providers/terraform-provider-aws#5

**Comment by stack72** [comment]
Thanks for this @bflad :)
