### ISSUE TITLE
azurerm_template_deployment parameters from acs-engine generated parameters file

### ISSUE THREAD

**Issue by Globegitter** [hashicorp/terraform#13241]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform version: 0.9.2  6365269541c8e3150ebe638a5c555e1424071417+CHANGES
Go runtime version: go1.8

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_template_deployment

### Terraform Configuration Files
```hcl
resource "azurerm_template_deployment" "test" {
  name                = "${var.cluster_name}"
  resource_group_name = "${var.resource_group_name}"

  template_body = "${file(azuredeploy.json)}"
  parameters = "${file(azuredeploy.parameters.json)}"
  deployment_mode = "Incremental"
  depends_on      = ["null_resource.run_acs_engine"]
}
```

### Debug Output
```
1 error(s) occurred:

* azurerm_template_deployment.test: parameters: should be a map
```

### Expected Behavior
Terraform should have created that deployment

### Actual Behavior
It failed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Download the files from: https://gist.github.com/Globegitter/4ea17f9ed24ebdb38ce0a725fde01795
2. `terraform apply`

### Important Factoids
I am using [acs-engine](https://github.com/Azure/acs-engine) to create the template file as shown in this article: http://danielrhoades.com/2017/03/20/docker-azure-terra/

When I manually converted the `azuredeploy.parameters.json` into a map because it seemd to have issues with `agentpool1Count = 1` (maybe because it is an int?), once I removed that and the template used it started creating with the deployment.

**Comment by dash042** [comment]
parameters_body = "${file(azuredeploy.parameters.json)}"
should work... but does not since the typical parameters.json contains 

1. $schema
2. contentVersion
3. parameters {

deleting these first 3 lines (and the last "}" ) fixes this issue... is there a better way?
