### ISSUE TITLE
Add support for TreatMissingData attribute on aws_cloudwatch_metric_alarm 

### ISSUE THREAD

**Issue by tjwallace** [hashicorp/terraform#13253]
### Terraform Version
0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

Latest AWS API docs [here](http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html)

**Comment by radeksimko** [comment]
Hey @tjwallace 
thank you for opening the issue.

I will close this one as duplicate in favour of https://github.com/hashicorp/terraform/issues/13263 which has a bit more correct description (in terms of affected resources). I hope you don't mind.
