### ISSUE TITLE
Support EC2 Run Commands / System Manager

### ISSUE THREAD

**Issue by dguisinger** [hashicorp/terraform#13271]
I was reading this new blog post from AWS on how to run commands on your EC2 instances without having to keep a bastion server / environment around.

This looks like a great direction to go for issuing commands to servers or groups of servers via Terraform, but it appears Terraform doesn't support this feature at the moment.

I've included a link to the blog article for specifics below:

[Replacing a Bastion Host with Amazon EC2 Systems Manager](https://aws.amazon.com/blogs/mt/replacing-a-bastion-host-with-amazon-ec2-systems-manager/?sc_channel=sm&sc_campaign=management_tools_blog&sc_publisher=tw_go&sc_content=blog_post&sc_country=global&sc_geo=global&sc_outcome=aware&adbsc=social_blogs_20170331_71234036&adbid=847910835716411393&adbpl=tw&adbpr=66780587)

**Comment by yusuf-cochinwala** [comment]
It will be great to see this as a new resource soon ....

**Comment by stack72** [comment]
Hi @dguisinger 

Thanks for raising the enhancement request :) Luckily, we already have support for AWS SSM in Terraform

You can check it out here :) https://www.terraform.io/docs/providers/aws/r/ssm_document.html#

Paul
