### ISSUE TITLE
Error applying plan: diffs didn't match during apply

### ISSUE THREAD

**Issue by jmreicha** [hashicorp/terraform#1327]
Not sure if this issue has been raised elsewhere. 

I am experiencing the following issue when attempt to run a `terraform apply` on an AWS (EC2 and route 53) resource that has already ben created.

```
Error applying plan:

aws_route53_record.<node>: diffs didn't match during apply. This is a bug with the resource provider, please report a bug.
```

It seems to rebuild the server correctly but the DNS record doesn't update correctly, I have to run the `terraform apply` command a second time to "sync" everything up correctly.

**Comment by ryanuber** [comment]
I've also seen this recently, but it is always transient and not reproducible. @jmreicha do you have a repro case for this? If so, a gist would be great!

**Comment by mitchellh** [comment]
Yeah, adding to @ryanuber with specifics:

1. Config
2. State
3. Repro steps

would be wonderful. Please omit or scrub private details, we can fill in our own keys and such.

**Comment by jmreicha** [comment]
Sure, I'll get a gist put together here.

**Comment by jmreicha** [comment]
Here is the gist, there was a lot of cut and paste so hopefully I didn't screw it up too bad.

https://gist.github.com/jmreicha/2adcf57ae63d37e6213a

Let me know if you need any more details.

**Comment by nathanleiby** [comment]
Likewise have seen this and would be happy to look into reproducing, if you need additional info. Thanks!

**Comment by catsby** [comment]
https://github.com/hashicorp/terraform/issues/1404 is a possibly similar/related Route 53 issue involving diffs not matching

**Comment by mitchellh** [comment]
This should be fixed in the latest version. Please let us know if it isn't.
