### ISSUE TITLE
Doc Update: EMR_CLUSTER_GROUP

### ISSUE THREAD

**Issue by gposton** [hashicorp/terraform#13272]
The example in the EMR cluster group here: https://www.terraform.io/docs/providers/aws/r/emr_instance_group.html

...needs to be updated.

The resource name is: aws_emr_cluster_instance_group
It should be: aws_emr_instance_group

**Comment by tombuildsstuff** [comment]
Hi @gposton 

Thanks for reporting this - I'm taking a look at this now :)

Thanks!
