### ISSUE TITLE
Allow specifying attachment-type resources inline of their parent

### ISSUE THREAD

**Issue by jleclanche** [hashicorp/terraform#13276]
I imagine this must have been talked about before but I can't find an issue about it. We're happy users of terraform but it is just *so damn verbose*.

For example, configuring an amazon application load balancer requires creation of:
* An `aws_alb` resource with two or more inline `aws_subnet`s
* An `aws_alb_listener`, which is attached to the ALB
* An `aws_alb_target_group`
* At least two `aws_alb_target_group_attachment` resources which are attached to their target_group and target the EC2 instance.

This could be simplified a lot if the `aws_alb_target_group_attachment` resources could be specified inline of their target group. For example:

```hcl
resource "aws_alb_target_group" "example" {
	name = "test-target-group"
	port = 443
	protocol = "HTTPS"
	vpc_id = "${aws_vpc.primary.id}"

	stickiness {
		type = "lb_cookie"
		enabled = true
	}

	health_check {
		interval = 30
		path = "/"
		protocol = "HTTPS"
		healthy_threshold = 5
		unhealthy_threshold = 2
	}

	attachments = [
		resource "aws_alb_target_group_attachment" "example_01" {
			target_id = "${aws_instance.example_01.id}"
			port = 443
		}
		resource "aws_alb_target_group_attachment" "example_02" {
			target_id = "${aws_instance.example_02.id}"
			port = 443
		}
	]
}
```

Similar pattern can be applied pretty much everywhere. AWS security groups, IAM policy attachments, github repositories...

Logically, this is simpler and easier to follow and it doesn't necessarily break backwards compatibility (you could specify it both inline or separately).

**Comment by jleclanche** [comment]
I know this is slightly OT but I'm going to take the opportunity to mention a related problem I don't see talked about that much: I'd really like to see improvements made on terraform's verbosity and logical management in general. A medium-size infrastructure quickly ends up devolving into dozens of .tf files, in a single directory (impossible to split into multiple directories without creating modules for each), with a massive `terraform plan` command every time you want to change a tag on a random resource [I know about --target]. And it becomes very hard to justify adding new resources to terraform when they're easier to deal with from the provider's UI.

I think this is becoming more relevant as terraform is gaining support for loads of new providers and resources every release. It's now really attractive to look at terraform as a versioned backup of the infrastructure, but adding a new resource has great costs: Learning the new module and its properties, learning how they map to what you already have, slower plans, and potentially the forward-cost of wanting to have all matching upstream resources in terraform (which means that what used to take one button click now takes editing and organizing the terraform resource, applying it or dealing with a slow and cumbersome import).

The dream: Being able to add a resource through the upstream provider's UI and back it up into terraform afterwards. "Dump" a new provider's existing resources to a terraform file (+ state), change some settings, reorganize it into different folders/files, run a plan which by default only refreshes what terraform locally detects has changed (rather than force a refresh everywhere), then apply.
Do some more changes upstream, upgrade terraform which features new resources, run `terraform resync`, have terraform write all the new resources and such to local files. Rinse and repeat.

**Comment by grubernaut** [comment]
Hello again @jleclanche! 👋 

The second comment brings up a fairly common growing pain with using Terraform. After a while, it quickly becomes less efficient to add new resources to Terraform, as the time cost from hitting `refresh` on every resource quickly sprawls out of control. A fairly common upgrade path, that works extremely well, is to use multiple terraform statefiles, partitioned to the user's comfort-level. 

For example, I've seen users who use a separate statefile per module, and I've seen users use a separate statefile per individual resource. It all depends on the users comfort level with their CI pipeline, and how far they wish to split apart their resources.

This is a fairly easy milestone to achieve via the `terraform_remote_state` resource (https://www.terraform.io/docs/providers/terraform/d/remote_state.html). The end result of using this workflow, is that a single change is now much more isolated to a small subset of resources in state, and risk can be minimized to your liking. This also solves the issue stated earlier, that adding a new module takes on a large amount of risk, and longer plans. Adding a new statefile, and importing an upstream statefile allows for faster plans, and faster iterations while learning the new resource. It also allows for a full `terraform destroy` during development, without adversely effecting any upstream resources. 

I'm more than happy to discuss these concerns further, as well as solicit community involvement, however the discussion is fairly off-topic for the original issue presented. If you wish to discuss further, we'd be more than happy to answer any questions on our [public mailing list](https://groups.google.com/forum/#!forum/terraform-tool). Thanks! ❤️
