### ISSUE TITLE
ignition_file with source but without verification = malformed hash specifier

### ISSUE THREAD

**Issue by jangrewe** [hashicorp/terraform#13285]
### Terraform Version
0.9.2

### Affected Resource(s)
- ignition_file

### Terraform Configuration Files
```hcl
data "ignition_file" "kubectl" {
    filesystem = "root"
    path = "/opt/bin/kubectl"
    mode = "0755"
    source {
        source = "https://storage.googleapis.com/kubernetes-release/release/v${var.k8s_version}/bin/linux/amd64/kubectl"
    }
}
```

### Expected Behavior
The file gets downloaded, *not* verified, and written to the specified path.

### Actual Behavior
```
Error refreshing state: 1 error(s) occurred:

* module.kubernetes.data.ignition_file.kubectl: 1 error(s) occurred:

* module.kubernetes.data.ignition_file.kubectl: data.ignition_file.kubectl: malformed hash specifier
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
The docs specify that `verification` is optional.

**Comment by jangrewe** [comment]
Probably a job for @mcuadros ;-)

**Comment by mcuadros** [comment]
From the documentation:
>  When using http, it is advisable to use the verification option to ensure the contents haven’t been modified.

Actually is mandatory, I will update the documentation.

**Comment by maikzumstrull** [comment]
It's not mandatory in Ignition or Container Linux Config Transpiler, and arguably not really necessary when downloading over https (not plain http).
