### ISSUE TITLE
Feature request. Interpolations in terraform {} configuration block.

### ISSUE THREAD

**Issue by DenisBY** [hashicorp/terraform#13289]
It would be very useful to have support of variables in terraform {} configuration block.
In my case I use one state to manage many ECS Services. They are mostly the same but with few differences like name(engine), priority, etc. and of course I have these services on different environments, like DEV or PROD.
I know that I can use empty `terraform { backend “s3” {} }` and then use `-backend-config` in command line to provide values, but It would be nice to provide values for variable only once.

### Terraform Version
`Terraform v0.9.2`

### Affected Resource(s)
```
terraform {backend "s3" {}}
```
### Terraform Configuration Files
```hcl
terraform {
    backend "s3" {
        bucket = "tag-terraform-states"
        key = "ecs-service/${var.env_name}/${var.engine}/${var.prio}/terraform.tfstate"
        region = "${var.region}"
    }
}
```

### Expected Behavior
Variables are interpolated to values

### Actual Behavior
`terraform.backend: configuration cannot contain interpolations`

### Steps to Reproduce
`terraform plan`

**Comment by jbardin** [comment]
@DenisBY 

Thanks for opening the issue. We are tracking this in a duplicate here: #13022.
