### ISSUE TITLE
Terraform cannot handle state SOFT_DELETED in Openstack Nova. 

### ISSUE THREAD

**Issue by cloudrkt** [hashicorp/terraform#13282]
Hi,

I cannot terraform destroy an instance that was created on Openstack when the status is SOFT_DELETED. The Openstack cloud we use has reclaim_instance_interval enabled so the status of a freshly destoyed instance is not DELETED but SOFT_DELETED.  Can terraform handle this case as well?

### Terraform Version

Terraform v0.9.2

### Affected Resource(s)
- openstack instance

### Terraform Configuration Files
```hcl

resource "openstack_compute_floatingip_v2" "terraform" {
  pool       = "${var.pool}"
  depends_on = ["openstack_networking_router_interface_v2.terraform"]
}

resource "openstack_compute_keypair_v2" "terraform" {
  name       = "terraform"
  public_key = "${file("${var.ssh_key_file}.pub")}"
}

resource "openstack_networking_network_v2" "terraform" {
  name           = "terraform"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "terraform" {
  name            = "terraform"
  network_id      = "${openstack_networking_network_v2.terraform.id}"
  cidr            = "10.0.0.0/24"
  ip_version      = 4
  dns_nameservers = ["8.8.8.8", "8.8.4.4"]
}

resource "openstack_networking_router_v2" "terraform" {
  name             = "terraform"
  admin_state_up   = "true"
  external_gateway = "${var.default_public_gateway_id}"
}

resource "openstack_networking_router_interface_v2" "terraform" {
  router_id = "${openstack_networking_router_v2.terraform.id}"
  subnet_id = "${openstack_networking_subnet_v2.terraform.id}"
}

resource "openstack_compute_secgroup_v2" "terraform" {
  name        = "terraform"
  description = "Security group for the Terraform example instances"
}

resource "openstack_compute_instance_v2" "terraform" {
  availability_zone = "NL1"
  name              = "terraform"
  image_name        = "${var.image}"
  flavor_name       = "${var.flavor}"
  key_pair          = "${openstack_compute_keypair_v2.terraform.name}"
  security_groups   = ["${openstack_compute_secgroup_v2.terraform.name}"]
  floating_ip       = "${openstack_compute_floatingip_v2.terraform.address}"

  network {
    uuid = "${openstack_networking_network_v2.terraform.id}"
  }
}
```

### Debug Output

https://gist.github.com/cloudrkt/4ecf84692f79ffa71120b4037eeb6db5

note: This is output from terraform 0.8.8 but the error is the same as 0.9.2.

### Expected Behavior
Terraform should handle the state SOFT_DELETED as well when using terraform destroy

### Actual Behavior
Error message when deleting instance

```
 Unexpected state 'SOFT_DELETED', wanted target 'DELETED'.
```
### Steps to Reproduce

On an Openstack Cloud with soft_delete enabled 

1. `terraform apply`
2. `terraform destroy`

### Important Factoids
- Standard openstack provider
- reclaim_instance_interval enabled in etc/nova/nova.conf

### References
- Issue tackled in: #5104 and #12674 but not the SOFT_DELETED case.

**Comment by jtopjian** [comment]
@cloudrkt Ah, thanks for reporting this. I'll have some time to fix this up in the next day or so.

**Comment by jtopjian** [comment]
@cloudrkt https://github.com/hashicorp/terraform/pull/12689 added support for `force_delete` which circumvents the soft delete configuration in OpenStack. So at the moment, you can configure your instances with `force_delete = true` and they will be destroyed correctly, _but_ you will not be able to reclaim them out of band of Terraform.

If I add `SOFT_DELETED` to the list of acceptable delete states, then Terraform will successfully "destroy" the instance, you won't have to use `force_delete`, the instance will be `SOFT_DELETED` allowing you to reclaim it, but reclaiming will be done out of band of Terraform and since there is no way of importing instances into Terraform state yet, you won't be able to use that instance in Terraform again.

Does that make sense? I just want to make sure the behavior is clear so we get this one resolved this time :)

**Comment by cloudrkt** [comment]
@jtopjian Sounds OK. Our OpenStack installation uses this to prevent admins shooting themselves in the foot. If Terraform can handle the soft delete state then their instances will be in a restorable state afterwards. This should not be the concern Terraform imho.

**Comment by jtopjian** [comment]
👍 

I'll get a patch in this evening :)
