### ISSUE TITLE
aws_s3_bucket resource should validate bucket name during plan command

### ISSUE THREAD

**Issue by randomvoids** [hashicorp/terraform#13298]
bucket names can only contain lowercase alphanumeric characters and hyphens. This gets past the plan command  and causes the apply command to fail.

I'm using Terraform v0.9.2

**Comment by bdashrad** [comment]
in us-east-1 you can also use underscores, to make it more confusing.

**Comment by randomvoids** [comment]
I just tried to create one in us-east-1 with underscores via the aws console and wasn't allowed to. It looks like they may have blocked it for all new buckets now in that region too.

**Comment by catsby** [comment]
While we can add name validation, unfortunately we couldn't exclude underscores because there are current, existing buckets that contains them.
