### ISSUE TITLE
State ID's truncated on 0.9.0+

### ISSUE THREAD

**Issue by bdashrad** [hashicorp/terraform#13292]
Prior to 0.9.0, the entire state id was outputted by the AWS provider (I'm not sure about others, because this is the only one I use). It is now truncated, most of the time rendering it completely useless for finding the resource you want.  

## Example:
```
aws_s3_bucket.company-balancers: Refreshing state... (ID: company-balancers)
aws_s3_bucket.company-dummy-lambdas: Refreshing state... (ID: company-d...-lambdas)
aws_cloudformation_stack.network: Refreshing state... (ID: arn:aws:c...bc261799)
```

I see in the changelog for 0.9.0 state ID was added to all refresh/plan/destroy output. In #12261 it there was discussion to truncate state IDs longer than 20 characters, which makes it useless for finding resources on AWS, for example.

It would be beneficial to restore previous behavior, make truncation optional behind a flag, or at the very least add a flag to not truncate output.

### Terraform Version
0.9.0+

**Comment by apparentlymart** [comment]
@mitchellh it looks like this change was made at your request, so this decision is one for you to make. :grinning:

**Comment by mitchellh** [comment]
/cc @radeksimko 

I'm not against reverting this or making the truncation threshold much higher.

**Comment by radeksimko** [comment]
> which makes it useless for finding resources on AWS, for example.

Unfortunately IDs differ in usual length quite significantly amongst resources. I'm happy to bump it though. Looking at some examples I think KMS ARN has more or less the same length every time - e.g. `arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab` (75 chars).

So shall we bump the limit from 20 to say 80?

While I agree some IDs appearing in `plan`/`apply` output may not be as useful, you can still use `terraform show` to display all the attributes unshortened (including IDs) - that's just FYI - before we address this problem.

**Comment by mitchellh** [comment]
@radeksimko Yeah I think it'll just take some human twiddling until we find the right balance of truncation. I'm comfortable moving to 80, let's do that. :)
