### ISSUE TITLE
Fix typo in documentation

### ISSUE THREAD

**Issue by pradeepbhadani** [hashicorp/terraform#13294]
Fix "respository" word to "repository" in followinf documents:

https://www.terraform.io/docs/providers/bitbucket/r/default_reviewers.html
https://www.terraform.io/docs/providers/bitbucket/r/hook.html
https://www.terraform.io/docs/providers/bitbucket/r/repository.html

**Comment by pradeepbhadani** [comment]
PR created : https://github.com/hashicorp/terraform/pull/13295

**Comment by grubernaut** [comment]
Fixed in #13295
