### ISSUE TITLE
Terraform doesn't wait long enough to destroy a CloudFront distribution

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform#13309]
### Terraform Version

Terraform 0.9.2

### Affected Resource(s)

- aws_cloudfront_distribution

### Terraform Configuration Files

Any CloudFront distribution will do.

### Expected Behavior

When you run `terraform destroy`, Terraform waits until the CloudFront distribution has been destroyed, and exits cleanly.

### Actual Behavior

Terraform times out after 40 minutes. Remarkably, CloudFront can take longer than that to undeploy, so you get this error:

```
module.cloudfront.aws_cloudfront_distribution.cdn: Still destroying... (ID: E3MIX3RP7LV8ZY, 39m30s elapsed)
module.cloudfront.aws_cloudfront_distribution.cdn: Still destroying... (ID: E3MIX3RP7LV8ZY, 39m40s elapsed)
module.cloudfront.aws_cloudfront_distribution.cdn: Still destroying... (ID: E3MIX3RP7LV8ZY, 39m50s elapsed)
module.cloudfront.aws_cloudfront_distribution.cdn: Still destroying... (ID: E3MIX3RP7LV8ZY, 40m0s elapsed)
Error applying plan:

1 error(s) occurred:

* module.cloudfront.aws_cloudfront_distribution.cdn (destroy): 1 error(s) occurred:

* aws_cloudfront_distribution.cdn: timeout while waiting for state to become 'Deployed' (last state: 'InProgress', timeout: 40m0s)
```

The solution, sadly, is probably to crank up the timeout to something like 90 minutes to be safe.

### Steps to Reproduce

1. `terraform apply`
1. `terraform destroy`

**Comment by xavivars** [comment]
Doesn't #13319 handles only deployment, and not deletion?

**Comment by radeksimko** [comment]
@xavivars Good spot - do you mind sending a similar PR?

**Comment by xavivars** [comment]
Actually, it seems it does. I misread the name of the methods, looking it more carefully, it's used in the delete part.

However, I faced a problem that it timedout, way before than 70 minutes. But I'm not sure how that could happen.

**Comment by radeksimko** [comment]
We'd welcome an issue if you have a config and/or debug log to share. Happy to bump it further if we see evidence it needs to be bumped.

Also we have [a GPG key](https://keybase.io/hashicorp) you may use for encrypting the config and/or debug log if it contains anything sensitive.
