### ISSUE TITLE
AWS: Dependency bug: OpsWorks dependency broken when changing IAM role

### ISSUE THREAD

**Issue by u2mejc** [hashicorp/terraform#13305]
### Terraform Version
```bash
$ terraform -v
Terraform v0.9.2
```

### Affected Resource(s)
- AWS_OPSWORKS_STACK

### Terraform Configuration Files
```hcl
resource "aws_opsworks_stack" "stack" {
  name                          = "${var.stack_name}"
  region                        = "${var.region}"
  service_role_arn              = "${aws_iam_role.opsworks_service_role.arn}"
  default_instance_profile_arn  = "${aws_iam_instance_profile.opsworks_instance_profile.arn}"
  vpc_id                        = "${var.vpc_id}"
  default_subnet_id             = "${var.opsworks_stack_subnet}"
  configuration_manager_version = "12"
  default_os                    = "Ubuntu 16.04 LTS"
  agent_version                 = "LATEST"
  use_opsworks_security_groups  = false
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
- Expected immutable service_role_arn will force new resource when planning.
- Applying would destroy the stack first, then destroy or rename the role it depends on before recreating the stack

### Actual Behavior
- Terraform allows the IAM role name / path to be modified, then fails when it attempts to update the immutable service_role_arn.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
- Deleting (or renaming) the stack's roll will render the stack unable to delete it's self as it's failing to check in with depending resources in AWS. If the name space isn't available again, you will have a chicken and egg issue with a stuck stack that required AWS support to resolve.

### References
n/a

**Comment by stack72** [comment]
Hi @u2mejc 

Thanks for the report here - you are indeed correct :(

From the [docs](http://docs.aws.amazon.com/cli/latest/reference/opsworks/update-stack.html)

```
--service-role-arn (string)

Do not use this parameter. You cannot update a stack's service role.
```

I will get this updated today and it will be part of 0.9.3

Paul

**Comment by u2mejc** [comment]
Smoking fast, thank you @stack72 !!!
