### ISSUE TITLE
AzureRM provider crash when importing local network gateways

### ISSUE THREAD

**Issue by whiskeyjay** [hashicorp/terraform#13301]
Reported by @partamonov in #9198, since the cause of the import command crash is very likely different from the OP's issue in #9198, I'm creating this separate issue to make it clearer.

The plug-in crashes if "localNetworkGateways" is not found in the id parameter. The fix is to verify the parameter before proceeding.

Also the "import" example in the documentation is wrong, "localNetworkGateways" should be case sensitive. The current example actually causes the plugin to crash due to the bug.

PR for the fix is here: #13261 provider/azurerm: Fixing crash when importing Local Network Gateways

**Comment by grubernaut** [comment]
Fixed in #13261
