### ISSUE TITLE
Not able to change iops field of existing aws_ebs_volume resource

### ISSUE THREAD

**Issue by prabhjot018** [hashicorp/terraform#13318]
Hi there,

### Terraform Version
8.0.7

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ebs_volume

### Expected Behavior
When we change iops field of exisiting ebs, terraform should change the iops of the specific ebs

### Actual Behavior
On changing iops field of ebs volume, On running terraform apply it is destroying existing ebs volumes and creating new ebs volumes with new iops. I am able to change existing ebs volume iops using aws console but not through terraform 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `Change iops of aws_ebs_volume resource`
2 terraform plan 
3 terraform apply

Thanks,
Prabhjot

**Comment by stack72** [comment]
Hi @prabhjot018 

This was added in a later release of Terraform than you are running - you seem to be running 0.8.7, ability to resize EBS volumes was added in 0.8.8 on March 2nd

If you upgrade and still find issues, then please do let me know

Thanks

Paul
