### ISSUE TITLE
Feature request: aws provider - data source for RDS snapshots

### ISSUE THREAD

**Issue by jurajseffer** [hashicorp/terraform#13320]
There is no way to get the latest snapshot for RDS instances using a data source. This is useful for being able to spin up an RDS cluster always from the latest snapshot instead of hard coding the identifier.

**Comment by Seraf** [comment]
Hello,

There're already issues/pr for this usecase :

https://github.com/hashicorp/terraform/issues/10287
https://github.com/hashicorp/terraform/pull/10291

**Comment by stack72** [comment]
Closed via #10291
