### ISSUE TITLE
Documentation on terraform remote -name flag 

### ISSUE THREAD

**Issue by dublx** [hashicorp/terraform#1332]
Hi,
It's not very clear in the docs that the `-name` flag of `terraform remote` should be in the `'<username>/<name>'` format.
The online documentation doesn't specify this format should be used and the output'ed error `malformed name '<flag value>'` is not very clear either.

**Comment by nevir** [comment]
To make matters worse, the error gives a malformed example too:

```
> terraform remote config -backend-config="name=foo"
malformed name 'foo'

If the error message above mentions requiring or modifying configuration
options, these are set using the `-backend-config` flag. Example:
-backend-config="name=foo" to set the `name` configuration
```

**Comment by phinze** [comment]
Thanks for the report, and sorry for the confusion. We'll get these docs cleaned up.

**Comment by mitchellh** [comment]
I made the error messge a lot clearer. This should be fixed.
