### ISSUE TITLE
Can't destroy a module without optional field being set at time of creation

### ISSUE THREAD

**Issue by selslack** [hashicorp/terraform#13328]
Hello!

### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_address
- google_compute_global_address
- google_compute_instance

Maybe others with optional fields defaulting to something computed.

### Expected Behavior
Resources created by that module are destroyed.

### Actual Behavior
Error `"project": required field is not set`.

### Steps to Reproduce
1. Create a module with GCE resources listed above without optional field `project` set
1. `terraform apply`
1. Remove that module from definition
1. `terraform plan`

**Comment by danawillow** [comment]
Hey @selslack, are you setting the project in the provider config? That's still required: https://www.terraform.io/docs/providers/google/index.html. If you are and you're still getting errors, can you post a sample config? Right now I don't think I have enough information to really debug what's going on.

**Comment by selslack** [comment]
@danawillow will try to make minimal reproduction config later this week.

**Comment by danawillow** [comment]
Hey @selslack, were you able to come up with a repro config?
