### ISSUE TITLE
Failure to lookup AMI ID when count>1

### ISSUE THREAD

**Issue by mikkoc** [hashicorp/terraform#1333]
Snippet:

```
resource "aws_instance" "tsuru-app" {
  count = 3
  ami = "${lookup(var.amis, var.region)}"
  instance_type = "t2.medium"
  subnet_id = "${aws_subnet.private1.id}"
  security_groups = ["${aws_security_group.default.id}"]
  key_name = "${aws_key_pair.deployer.key_name}"
  user_data = "${file(\"cloud-config/app.yml\")}"
  tags = {
    Name = "tsuru-app-${count.index}"
  }
}
```

```
variable "region"     { 
  description = "AWS region"
  default     = "eu-west-1"
}
/* Ubuntu 14.04 amis by region */
variable "amis" {
  description = "Base AMI to launch the instances with"
  default = {
    eu-west-1 = "ami-234ecc54"
    eu-central-1 = "ami-9a380b87"
  }
}
```
Instance tsuru-app-0 is created without error, with the correct AMI.
The other two instances creation fails with:
`Error launching source instance: Invalid id: "${lookup(var.amis, var.region)}" (expecting "ami-...") (InvalidAMIID.Malformed)`

Terraform version 0.3.7

Error: https://gist.github.com/mikkoc/f4789b80c2652d2847c5

**Comment by mikkoc** [comment]
Note that re-executing the command worked, so it might not be easily reproducible.

**Comment by phinze** [comment]
This should be long since fixed. Feel free to follow up if you see this on the latest Terraform version! :+1:
