### ISSUE TITLE
vsphere: Cannot assign a hostname and use DHCP for DNS

### ISSUE THREAD

**Issue by joshmullis** [hashicorp/terraform#13346]
### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- vsphere_virtual_machine

### Snippet from "https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html":

domain - (Optional) A FQDN for the virtual machine; defaults to "vsphere.local"
dns_servers - (Optional) List of DNS servers for the virtual network adapter; defaults to 8.8.8.8, 8.8.4.4

### Problem description
Hello,

I would like to propose the removal of the defaults above.

Due to these, there is no way to set the hostname AND use DHCP to get DNS info.
So if we want to set the hostname, we are forced to use these defaults.

Thanks
-josh

**Comment by lvlie** [comment]
+1
This does not look like a sane default in an internal (walled) network and should be something like "unmanaged" or "dhcp", or this should be an option. Right now the only option is to either specify the correct internal DNS servers or to set skip_customization to true; but this only works when you can get the hostname/domainname and DNS from DHCP/DNS, or set it via a remote-exec, for example.

**Comment by jkodroff** [comment]
+1
This is a bummer and requires some extra work, but it's not blocking my ability to use Terraform.

**Comment by mrlesmithjr** [comment]
I would definitely be in favor of this. This a huge pain from an end-to-end automation perspective. Not show stopping but....
