### ISSUE TITLE
Feature request: rand()

### ISSUE THREAD

**Issue by notjames** [hashicorp/terraform#13350]
Wondering how feasible it would be to implement a rand[om]() function for TF. How I'd like to use it is:

Sometimes I have need of implementing a single instance of something in my infrastructure in my AZs rather than having one per AZ. Instead of manually picking the AZ in which I want to implement whatever it is, it would be nice to use a random() function that can take `min, max` as arguments and return a value inclusively from the arguments passed IE

`random(0,3)` would [randomly] return 1 on one invocation.
`random(0,3)` would [randomly] return 3 on another invocation.
etc

This would allow singleton instances to be randomly placed in my AZs rather than defaulting to putting them in the first AZ in the list because 0 is easy, which would make that AZ heavy in instances when that may not be desirable.

```
variable "my_azs" { type = "list" }

resource "aws_instance" "foo"
{
   availablility_zone = "${element(var.my_azs, random(0, count(var.my_azs)))}"
   ...
} 
```

**Comment by apparentlymart** [comment]
Hi @notjames!

Have you seen [the `random_shuffle` resource](https://www.terraform.io/docs/providers/random/r/shuffle.html)? It was implemented with this use-case in mind.

The docs for the `random` provider give sums details as to why this is a resource rather than just a function.

**Comment by notjames** [comment]
Nope. This is the first time I've seen this. This will work nicely! Thank you!

**Comment by ranvijayj** [comment]
Hi,

I am using element

```
resource "aws_instance" "instance" {
  count = "${var.count}"

  ami                    = "${var.ami}"
  instance_type          = "${var.instance_type}"
  user_data              = "${var.user_data}"

subnet_id = "${element(var.subnet_id, count.index)}"
I have 3 subnets and it works pretty fine....
```

Random provider not working for me..

Can I randomize the subnet_id line? So that subnet Ids for instances are not chosen serially?

**Comment by ranvijayj** [comment]
@apparentlymart
