### ISSUE TITLE
provider/google: Add ability to create backend bucket for Cloud CDN

### ISSUE THREAD

**Issue by premist** [hashicorp/terraform#13355]
Google Cloud CDN allows [configuring Cloud CDN with GCS bucket](https://cloud.google.com/cdn/docs/using-cdn#enableupdate). We currently configure this part manually since Terraform Google provider doesn't have this option, but it'll be helpful to have this managed through Terraform.

**Comment by ctavan** [comment]
Duplicate of #12505 ?

**Comment by premist** [comment]
Hi @ctavan, I just checked an issue you've linked to and confirmed that this issue is duplicate. I tried to search for possible duplicate issues but seems like I missed it! 😅 

Closing this issue.
