### ISSUE TITLE
Use more recent version of govmomi

### ISSUE THREAD

**Issue by caseyaedwards** [hashicorp/terraform#13366]
### Terraform Version
Terraform v0.9.3-dev

### Affected Resource(s)
- vsphere_virtual_machine

### Expected Behavior
vSphere provider works and creates a VM that has a network adapter which has a label with a slash in the name.

### Actual Behavior
Fails saying unable to find network since the version of govmomi being used splits across forward slashes and only returns the last section.  This means if you have a network label with a slash in it such as IP/CIDR, it will only return the CIDR.

### Steps to Reproduce
It's easiest to use govc directly since it will produce the same outcome as Terraform.  Here's an example between working and nonworking versions.

govc version
govc 0.13.0
govc vm.network.change -net "v123 4.5.6.7/28" -vm "somevm.domain.com" ethernet-0
govc: network 'v123 4.5.6.7/28' not found
 
govc version
govc 0.14.0
govc vm.network.change -net "v123 4.5.6.7/28" -vm "somevm.domain.com" ethernet-0
(no output, completed successfully)

### Important Factoids
Using slashes in network labels

### References
- GH-8584 (May be related, not 100% sure)
- https://github.com/vmware/govmomi/issues/592

**Comment by Defilan** [comment]
I am seeing this exact same issue with our vSphere 6.5 environment. We have network labels that have a "/" in the name, and it won't work with the included version of govc. 

Thanks for posting this, caseyaedwards!

**Comment by madrover** [comment]
I believe I've found the same issue with folders.
I'll try to upgrade the library to the latest and create a PR

**Comment by caseyaedwards** [comment]
Sorry, I think I made a mistake.  I patched govmomi myself with a crappy fix; regex matching the way we name our vswitches: #.#.#.#/## (basically ipaddr / cidr) and then manually piecing it back together if it matches.  Then I forgot that I did that and rebuilt govc/terraform thinking that it was fixed because I was building off of govmomi 0.14.  I will upload my patched version of govmomi.  I believe this will fix your issue @Defilan although you may need to adjust the regex slightly to match your vswitch naming scheme.  I don't think it will fix your issue though @madrover since the regex needs to be specific enough to not match anything except the final object.

From looking at the govmomi source I don't think there's an easy way to fix this since it does a simple path.split or a strings.split on '/'.  I don't know Go very well though so I'm hoping I'm wrong and that there's an easy way to fix it.  I'll look into opening a more detailed ticket in the govmomi repo with my findings.

**Comment by caseyaedwards** [comment]
Not super happy with this fix but it works for us:
https://github.com/caseyaedwards/govmomi/commit/6b1622582ba798e1cb834937b41de73b93f049f7
