### ISSUE TITLE
Slow executable response on windows 10

### ISSUE THREAD

**Issue by harkamals** [hashicorp/terraform#13364]
### Terraform Version
v0.9.2 on Windows 10

### Affected Resource(s)
terraform.exe

### Debug Output
C:\GCTI\workspace\terraform-modules>terraform.exe version
2017/04/05 18:23:19 [INFO] Terraform version: 0.9.2  6365269541c8e3150ebe638a5c555e1424071417+CHANGES
2017/04/05 18:23:19 [INFO] Go runtime version: go1.8
2017/04/05 18:23:19 [INFO] CLI args: []string{"C:\\GCTI\\Software\\Python27\\terraform.exe", "version"}
2017/04/05 18:23:19 [DEBUG] Attempting to open CLI config file: C:\Users\1473085\AppData\Roaming\terraform.rc
2017/04/05 18:23:19 [INFO] CLI command args: []string{"version"}
Terraform v0.9.2

2017/04/05 18:23:19 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=windows&signature=5fcad35e-8df8-8ca2-31a8-de1e01d90ed9&version=0.9.2: dial tcp: lookup checkpoint-api.hashicorp.com: no such host
2017/04/05 18:23:19 [DEBUG] plugin: waiting for all plugin processes to complete...

### Expected Behavior
Almost immediate, quick output

### Actual Behavior
Takes 40 seconds for terraform to show anything on screen.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
terraform.exe version
terraform.exe plan

**Comment by apparentlymart** [comment]
Hi @harkamals! Sorry for the problems here.

Terraform here is trying to check if there's a new version available using the Hashicorp "checkpoint" server. It seems like the environment where you're running Terraform has a firewall rule preventing access to this endpoint.

The simplest solution is probably to just disable Terraform's attempt to check for upgrades. You can do that by creating or editing the "CLI config file" mentioned in the log output there (`C:\Users\1473085\AppData\Roaming\terraform.rc` in your case) and add the following setting:

```
disable_checkpoint = true
```

This used to be documented but I wasn't able to quickly find the reference for this so it seems like perhaps the documentation for this setting have been lost at some point. Let's consider this ticket to represent the restoration of docs for this setting and an additional log line in the output that references those docs.

**Comment by harkamals** [comment]
Hi, I disabled checkpoint, still no luck. It takes roughly 40 seconds to show any output on screen.
http_proxy and https_proxy environment variables are set as well.

terraform.exe version
2017/04/06 12:30:49 [INFO] Terraform version: 0.9.2  6365269541c8e3150ebe638a5c555e1424071417+CHANGES
2017/04/06 12:30:49 [INFO] Go runtime version: go1.8
2017/04/06 12:30:49 [INFO] CLI args: []string{"C:\\GCTI\\Software\\Python27\\terraform.exe", "version"}
2017/04/06 12:30:49 [DEBUG] Attempting to open CLI config file: C:\Users\<username>\AppData\Roaming\terraform.rc
2017/04/06 12:30:49 [INFO] Checkpoint disabled. Not running.
2017/04/06 12:30:49 [INFO] CLI command args: []string{"version"}
2017/04/06 12:30:49 [DEBUG] plugin: waiting for all plugin processes to complete...
Terraform v0.9.2

**Comment by apparentlymart** [comment]
Thanks for testing @harkamals. I guess the checkpoint warning must have been a red herring. I've re-classified this as a bug so we can spend some time trying to repro it, though I don't have a Windows machine handy today so I'll have to put this on the back-burner for the moment. :confounded:

**Comment by jbardin** [comment]
Hi @harkamals,

You can see by the logs that the entire program run was under 1 second, so something is delaying the initial execution of the program. 

These types of issues are often the result of security software running on your system. Is there anything you could disable, or add the binary to a whitelist to test? 

You can also try setting the environment variable`TF_FORK=0`, which will bypass starting terraform as a child process.

**Comment by harkamals** [comment]
Thank you. After adding TF_FORK parameter, I noticed:
terraform.exe appear in task manager after 20-25 seconds, perhaps something blocking it (like a/v)
terraform.exe appear twice in task manager and completes in about 15-20 seconds

**Comment by bclodius** [comment]
@apparentlymart I faced this same issue on Ubuntu 1404 which isn't having internet access (without proxy).

When I added below to ```~/.terraformrc``` it fixed the issue for me.

```
disable_checkpoint = true
```

**Comment by apparentlymart** [comment]
Thanks for the context, @bclodius. In this case it seems like something a bit different is going on with Windows in particular, but it's good to get confirmation that disabling checkpoint can fix it when it's a firewall or other networking issue. :+1:

**Comment by harkamals** [comment]
I've tried this on home computer running windows 10 and it works just fine.
Work computer is probably hardened OS and exhibits this issue - shall I ask for antivirus exclusion, and what shall I say for reasoning. Why an exception is required :)
Thanks.

**Comment by apparentlymart** [comment]
@harkamals it's hard to guess what might be restricted for you here but what seems most likely to me is the way Terraform's core process communicates with the plugins. On Windows a TCP socket on localhost is used as the communication channel, and this might be being intercepted by a local firewall on your machine which prevents the handshake from proceeding.

I'm honestly not sure what to suggest here, since I assume that just allowing arbitrary processes to listen on localhost would be too liberal for your situation. The range of ports used by Terraform for this purpose by default is pretty broad, and I don't think Terraform currently provides a way to customize that.

**Comment by apparentlymart** [comment]
Since this problem seems to be localized to a weird interaction between a software firewall and Terraform's plugin architecture, it doesn't seem that there's anything we can do about this right now, so I'm going to close this.

If others are having this problem, the best recommendation I can make is to try to make an exception in the firewall so that Terraform is able to listen on ports on localhost and that Terraform's child processes are able to connect to those ports.

Sorry that there isn't a smoother solution here. :confounded:

**Comment by alevinetx** [comment]
For anyone coming to this looking for the same problem on Windows 7.

I couldn't find anything in Symantec Endpoint to open these localhost controls.

However, (running cygwin), creating the ~/.terraformrc and adding the "disable_checkpoint"  worked wonderfully.

**Comment by SpencerBrown** [comment]
For anyone coming to this issue on Windows 10. I found that I was connected to a Windows domain that was no longer operative. Even though I was logged in with a local account, somehow this was causing the local server for the providers listening on "localhost" to have a 10-15 second delay, probably somewhere in DNS resolution.

Removing my connection to that domain fixed the slow terraform issue for me.
