### ISSUE TITLE
aws_security_group_rule from data source gets added to/removed from aws_security_group on alternating runs

### ISSUE THREAD

**Issue by jangrewe** [hashicorp/terraform#13370]
### Terraform Version
0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_security_group
- aws_security_group_rule

### Terraform Configuration Files
```hcl

resource "aws_security_group" "kubernetes" {
  vpc_id = "${var.vpc_id}"
  name = "kubernetes"

  ingress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    self = true
  }
[...]
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags {
    Name = "kubernetes"
    KubernetesCluster = "${var.cluster_name}"
  }
}

data "aws_security_group" "k8s-elb-ingress" {
  filter {
    name   = "group-name"
    values = ["k8s-elb-*"]
  }
  filter {
    name = "tag:KubernetesCluster"
    values = ["${var.cluster_name}"]
  }
}

resource "aws_security_group_rule" "k8s-elb-ingress-to-instances" {
  count             = "${length(data.aws_security_group.k8s-elb-ingress.*.id)}"
  type              = "ingress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = "${aws_security_group.kubernetes.id}"

  source_security_group_id = "${element(data.aws_security_group.k8s-elb-ingress.*.id, count.index)}"
}

```

Kubernetes creates an ELB and a Security Group for that ELB, and then adds that newly created Security Group as an Ingress rule to the existing Security Group (created by Terraform) that contain the Kubernetes instances (if it is tagged with the same value for `KubernetesCluster` as the instances). To keep Terraform from removing that Ingress rule, i'm using a data source to find the ID of that Security Group automatically created by Kubernetes, and add it as an Ingress rule to the existing Security Group in the plan.

### Expected Behavior
The SG that was automatically created by Kubernetes is selected via the data source and used in the SG Rule that gets appended to the `kubernetes` SG. If the Rule already exists, Terraform detect no changes, otherwise (which should never happen anyways) TF should add it.

### Actual Behavior
* On the first run, the Rule that adds the SG from the data source gets created and appended to the SG `kubernetes`.
* On the second run, the SG `kubernetes` gets modified and the Rule for the SG from the data source gets removed again.
* Subsequent runs keep alternating betweens those two actions

First run:
```
module.kubernetes.aws_security_group_rule.k8s-elb-ingress-to-instances: Creating...
  from_port:                "" => "0"
  protocol:                 "" => "-1"
  security_group_id:        "" => "sg-d417caad"
  self:                     "" => "false"
  source_security_group_id: "" => "sg-0dd87974"
  to_port:                  "" => "0"
  type:                     "" => "ingress"
```

Second run:
```
module.kubernetes.aws_security_group.kubernetes: Modifying... (ID: sg-d417caad)
[...]
  ingress.3320787337.security_groups.1127690469: "sg-0dd87974" => ""
[...]
```
### Steps to Reproduce
1. `terraform apply`

**Comment by jangrewe** [comment]
This seems to be a duplicate of #11011 and #8129, so not an issue with using the data source, but rather having both inline rules and aws_security_group_rules.

**Comment by SanchitBansal** [comment]
@jangrewe I have the same use case and tried to implement it using your solution, but my cluster is having multiple ELBs in same cluster which results in expected error "multiple Security Groups matched; use additional constraints to reduce matches to a single Security Group". So just curious to know the way you are handling it, or you are having just one ELB per Kubernetes cluster?

**Comment by jangrewe** [comment]
@SanchitBansal Yes, i have only 1 ELB per cluster, used for an Ingress.

**Comment by SanchitBansal** [comment]
How can we manage multiple ELBs per cluster, any idea?
