### ISSUE TITLE
GCE Provider: New forwarding rule after calculation

### ISSUE THREAD

**Issue by ldelossa** [hashicorp/terraform#13375]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
❯ terraform09 -v
Terraform v0.9.1

Your version of Terraform is out of date! The latest version
is 0.9.2. You can update by downloading from www.terraform.io
```

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_global_forwarding_rule

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Create Global Forwarding Rules
resource "google_compute_global_forwarding_rule" "moosive-grafana" {
  name = "moosive-grafana"
  target = "${google_compute_target_http_proxy.moosive-grafana.self_link}"
  port_range = "80"
  ip_address = "${google_compute_global_address.moosive-grafana.self_link}"
}
resource "google_compute_global_forwarding_rule" "moosive-prometheus" {
  name = "moosive-prometheus"
  target = "${google_compute_target_http_proxy.moosive-prometheus.self_link}"
  port_range = "80"
  ip_address = "${google_compute_global_address.moosive-prometheus.self_link}"
}
resource "google_compute_global_forwarding_rule" "moosive-consul" {
  name = "moosive-consul"
  target = "${google_compute_target_http_proxy.moosive-consul.self_link}"
  port_range = "80"
  ip_address = "${google_compute_global_address.moosive-consul.self_link}"
}
```

### Debug Output
I only need to run ```terraform plan``` to produce the issue:

```
Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

-/+ google_compute_global_forwarding_rule.moosive-consul
    ip_address:  "35.186.193.55" => "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/addresses/moosive-consul" (forces new resource)
    ip_protocol: "TCP" => "<computed>"
    name:        "moosive-consul" => "moosive-consul"
    port_range:  "80" => "80"
    self_link:   "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/forwardingRules/moosive-consul" => "<computed>"
    target:      "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/targetHttpProxies/moosive-consul" => "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/targetHttpProxies/moosive-consul"

-/+ google_compute_global_forwarding_rule.moosive-grafana
    ip_address:  "35.186.242.67" => "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/addresses/moosive-grafana" (forces new resource)
    ip_protocol: "TCP" => "<computed>"
    name:        "moosive-grafana" => "moosive-grafana"
    port_range:  "80" => "80"
    self_link:   "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/forwardingRules/moosive-grafana" => "<computed>"
    target:      "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/targetHttpProxies/moosive-grafana" => "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/targetHttpProxies/moosive-grafana"

-/+ google_compute_global_forwarding_rule.moosive-prometheus
    ip_address:  "35.186.255.223" => "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/addresses/moosive-prometheus" (forces new resource)
    ip_protocol: "TCP" => "<computed>"
    name:        "moosive-prometheus" => "moosive-prometheus"
    port_range:  "80" => "80"
    self_link:   "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/forwardingRules/moosive-prometheus" => "<computed>"
    target:      "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/targetHttpProxies/moosive-prometheus" => "https://www.googleapis.com/compute/v1/projects/vimeo-logs/global/targetHttpProxies/moosive-prometheus"


Plan: 3 to add, 0 to change, 3 to destroy.
```

### Expected Behavior
The above output happens AFTER the successful push of the resources to google cloud. Once we revaluate their existence in "terraform plan" terraform does not understand that the computed IP address in the statefile is actually the address of the self_link it's evaluating. I.E. that self_link that's in the plan output has already been computed into an IP address during the initial and immediately former run of Terraform. 

### Actual Behavior
Terraform wants to reevaluate the self_link to compute the "already-computed" ip address. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create fowarding rules which target a google_compute_global_address object
2. Terraform apply this into existence
3. Terraform plan; should show the above plan output which wants to reevaluate the self link to obtain the current IP address. 

Unfortunately I believe this behavior will cause a network blip everytime we want to use terraform to make subsequent changes to our infrastructure.

**Comment by ldelossa** [comment]
Just saw #5232

I can close this ticket unless to leave it up for discussion on whether self_link should be accepted if it causes this issue which could cause network disruption to users unaware.

**Comment by paddycarver** [comment]
I just opened #14020 to try and make the docs clearer on this subject. Ideally, we'd accept a `self_link` to and be able to Do The Right Thing regardless, but unfortunately, we have some higher priority stuff at the moment to work on. We would certainly accept and review PRs that added that functionality, however!

Thanks for reporting the issue, and sorry for the problems. I'm glad you got things working again.
