### ISSUE TITLE
aws_iam_policy_attachment resource inconsistent behavior

### ISSUE THREAD

**Issue by anosulchik** [hashicorp/terraform#13381]
Hi there,

I've noticed the following issue with aws_iam_policy_attachment. There's aws_iam_policy.s3_policy that needs to be attached to both IAM user and IAM role. In case it's done with two aws_iam_policy_attachment resources like it's shown below then terraform applies it to only one IAM entity either IAM user or role:

```
resource "aws_iam_policy_attachment" "attachment-user" {
  name = "es-${var.environment_name}-slowlogs-s3-policy-attachment"
  users = [ "${var.iam_user}" ]
  policy_arn = "${aws_iam_policy.s3_policy.arn}"
  depends_on = [ "aws_iam_policy.s3_policy" ]
}

resource "aws_iam_policy_attachment" "attachment-role" {
  name = "es-${var.environment_name}-slowlogs-s3-policy-attachment"
  roles = ["${aws_iam_role.role.id}"]
  policy_arn = "${aws_iam_policy.s3_policy.arn}"
  depends_on = [ "aws_iam_policy.s3_policy" ]
}
```

Every next terraform run it tries to change it:

```
~ module.slowlogs.aws_iam_policy_attachment.attachment-role
    roles.#:          "0" => "1"
    roles.4019121838: "" => "es-production-slowlogs-cleaner"

~ module.slowlogs.aws_iam_policy_attachment.attachment-user
    users.#:          "0" => "1"
    users.1041521866: "" => "es-production-cloud-aws-user"
```

This can be fixed by using one aws_iam_policy_attachment resource in the following configuration:

```
resource "aws_iam_policy_attachment" "attachment" {
  name = "es-${var.environment_name}-slowlogs-s3-policy-attachment"
  users = [ "${var.iam_user}" ]
  roles = ["${aws_iam_role.role.id}"]
  policy_arn = "${aws_iam_policy.s3_policy.arn}"
  depends_on = [ "aws_iam_policy.s3_policy" ]
}
```

At the same time case with two aws_iam_policy_attachment mentioned before doesn't look right -- I believe terraform should either apply policy to both user and role at once or fail with error.

```
➜  elasticsearch git:(master) ✗ terraform --version
Terraform v0.8.8
```

Thank you.

**Comment by notpeter** [comment]
I think this behavior is at least documented if not intuitive. From [iam_policy_attachment docs](https://www.terraform.io/docs/providers/aws/r/iam_policy_attachment.html):

>NOTE: The aws_iam_policy_attachment resource is only meant to be used once for each managed policy. All of the users/roles/groups that a single policy is being attached to should be declared by a single aws_iam_policy_attachment resource.
