### ISSUE TITLE
Splat doesn't work properly

### ISSUE THREAD

**Issue by slikk66** [hashicorp/terraform#13397]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
# terraform -v
Terraform v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_elasticache_cluster (at least)

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.  (think it does)

### Expected Behavior
create output of multiple cache nodes using splat:
```
output "memcached_ha_endpoints" {
  value = ["${aws_elasticache_cluster.memcached_ha.cache_nodes.*.address}"]
}
```

Try to read in these addresses for DNS:
```
resource "aws_route53_record" "memcached_ha" {

  count   = "${var.cache_engine == "memcached_ha" ? "${var.cache_ha_node_count}" : 0}"

  zone_id = "${aws_route53_zone.dns_internal_zone.zone_id}"
  name    = "${format("memcached-%03d.%s", count.index+1, "${var.internal_dns_tld}")}"
  type    = "CNAME"
  ttl     = "300"
  records = ["${var.memcached_ha_endpoints[count.index]}"]
}
```

### Actual Behavior
```
Error running plan: 1 error(s) occurred:

* module.dns.module.dns_internal.aws_route53_record.memcached_ha: 1 error(s) occurred:

* module.dns.module.dns_internal.aws_route53_record.memcached_ha[1]: index 1 out of range for list var.memcached_ha_endpoints (max 1) in:

${var.memcached_ha_endpoints[count.index]}
```

However, if you define the outputs using hardcoded indexes, it works:
```
output "memcached_ha_endpoints" {
  value = [
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.0.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.1.address}"
  ]
}
```

**Comment by slikk66** [comment]
OK - thanks for the quick response.  As a workaround, even though we have a variable "cache_ha_node_count" which creates the cluster with the requested number of nodes, I was able to do this instead (handling up to 10 nodes) which doesn't cause any error and still allows us to adjust the value as needed:

Hopefully this helps someone else out!

```
# due to terraform issue of splat not working as expected, we can't use "*"
# https://github.com/hashicorp/terraform/issues/13397
output "memcached_ha_endpoints" {
  value = [
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.0.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.1.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.2.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.3.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.4.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.5.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.6.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.7.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.8.address}",
    "${aws_elasticache_cluster.memcached_ha.cache_nodes.9.address}"
  ]
}
```

**Comment by WolverineFan** [comment]
@apparentlymart If I defined such an output, is there any way to reference it within the current module?  `module.this` and `module.self` don't work.  Searching the docs hasn't revealed any examples...

```hcl
output "memcached_ha_endpoints" {
  value = "${aws_elasticache_cluster.memcached_ha.cache_node_endpoints}"
}

resource "aws_route53_record" "memcached_ha" {

  count   = "${var.cache_engine == "memcached_ha" ? "${var.cache_ha_node_count}" : 0}"

  zone_id = "${aws_route53_zone.dns_internal_zone.zone_id}"
  name    = "${format("memcached-%03d.%s", count.index+1, "${var.internal_dns_tld}")}"
  type    = "CNAME"
  ttl     = "300"
  records = ["${module.self.memcached_ha_endpoints[count.index]}"]
}
```

**Comment by apparentlymart** [comment]
Sorry that my last comment was unclear: I wasn't suggesting that the example I showed would work today, but rather that this is a potential thing that could be implemented to address the issue here without heavy changes to Terraform core.

The workaround in the original message that opened this issue is what needs to be done today.

**Comment by bflad** [comment]
Ah ha! Just ran into this today. Would love to see the new `cache_node_endpoints` attribute available. 👍
