### ISSUE TITLE
No method to ignore changes in DynamoDB GSI

### ISSUE THREAD

**Issue by cypai** [hashicorp/terraform#13393]
### Terraform Version
$ terraform -v
Terraform v0.8.8

### Affected Resource(s)
- aws_dynamodb_table

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "FooBar" {
    name = "FooBar"
    read_capacity = 10
    write_capacity = 10
    hash_key = "foo-id"
    attribute {
        name = "foo-id"
        type = "S"
    }
    attribute {
        name = "bar-id"
        type = "N"
    }
    global_secondary_index {
        name = "bar-index"
        hash_key = "bar-id"
        read_capacity = 10
        write_capacity = 10
        projection_type = "ALL"
    }
    lifecycle {
        ignore_changes = ["read_capacity", "write_capacity"]
    }
}
```

### References
- #5617 

We would like to ignore read/write capacity for the GSI as well, but this configuration only ignores the read/write capacity of the top-level table. We weren't able to find any usable workaround, since we can't interpolate variables in the lifecycle, and wildcards are not supported.

Technically we could hardcode the randomly generated number like ```ignore_changes = ["global_secondary_index.3291674533.read_capacity"]```, but that's obviously a terrible solution since it would change every time we make a change.

**Comment by mcwqy9** [comment]
Running into this as well, with no known workaround. 

`ignore_changes = ["global_secondary_index.3291674533.read_capacity"]` is indeed terrible, but doesn't even work. If the capacity changes on the actual resource, then the computed hash on the actual resource changes also.

**Comment by mcwqy9** [comment]
I may have some time soon to work on this. I've done some golang in the past, but this would be my first contribution to this project. Can anyone suggest what might need to be done, at a high level? Would a good approach be to remove a GSI's capacity from the hash function that determines the number in `"global_secondary_index.3291674533.read_capacity"`? That would make that number stable through capacity changes, and allow an ignore to be hardcoded.
