### ISSUE TITLE
Feature Request: support for ALB host-based routing support [AWS]

### ISSUE THREAD

**Issue by bentterp** [hashicorp/terraform#13409]
https://aws.amazon.com/blogs/aws/new-host-based-routing-support-for-aws-application-load-balancers/

I believe this goes into the condition block of the aws_alb_listener_rule ressoure where field should be extended to having two possible values: either "path-pattern" or "host-header". We also need to be able to have both, somehow. Making it into a list seems logical but breaks backwards compatibility.

**Comment by Puneeth-n** [comment]
@bentterp  you beat me to it on creating the issue :))))

**Comment by Zordrak** [comment]
:+1:

**Comment by sbeasey** [comment]
yes, please add ALB Host based routing ASAP!

**Comment by stack72** [comment]
Hi @bentterp 

I am told that host based routing already works in Terraform. I am going to close this out - please do let me know if it doesn't work as expected

Thanks

Paul

**Comment by bentterp** [comment]
Documentation has been updated:
> Condition Blocks (for default_condition) support the following:
> 
> field - (Required) The name of the field. Must be one of path-pattern for path based routing or host-header for host based routing.
> values - (Required) The path patterns to match. A maximum of 1 can be defined.

But I can't find anything about this in the Release Notes..... when was this implemented?

When I search the repo for the string "host-header" using Github's web-interface (https://github.com/hashicorp/terraform/search?utf8=%E2%9C%93&q=host-header&type=), the only hit I get is for the documentation page: https://github.com/hashicorp/terraform/blob/ebc89e94264dafd629d1570946b548cb1f0d0df5/website/source/docs/providers/aws/r/alb_listener_rule.html.markdown

**Comment by bentterp** [comment]
@stack72 Please consider re-opening this issue as the code doesn't seem to have been written, only the documentation was updated.

Regards,
  Bent

**Comment by stack72** [comment]
Hi @bentterp 

There doesn't need to be any code written for this AFAICT - someone has already created an issue to let us know that it works but that we needed to update our documentation

https://github.com/hashicorp/terraform/pull/13623

Thanks

Paul

**Comment by Puneeth-n** [comment]
@bentterp only the sdk needed to be updated for it to work.
