### ISSUE TITLE
google_dns_managed_zone doesn't support import

### ISSUE THREAD

**Issue by hpio** [hashicorp/terraform#13416]
Feature request to support import on the google_dns_managed_zone resource 😄

**Terraform Version**

Terraform v0.9.2

**Affected Resource(s)**

google_dns_managed_zone

**Expected Behavior**

Should import an existing DNS zone.

**Actual Behavior**

Generates an error: resource google_dns_managed_zone doesn't support import

**Steps to Reproduce**

run terraform import resource google_dns_managed_zone.foo

**Comment by hpio** [comment]
Happy to try and pick this up if someone can point me where to start?

**Comment by paddyforan** [comment]
I'd love to see a PR for this, if you're willing to give it a shot! #13270 just added import for a few other resources, so it may be a good thing to model your PR after.

If not, we'll get to it, it just hasn't hit the top of our priority list yet.

**Comment by paddycarver** [comment]
@JDiPierro did some great work in adding this in #13824, which just got merged, so I'm going to close this out now. Thanks!
