### ISSUE TITLE
AWS Firehose Documentation has a mistake

### ISSUE THREAD

**Issue by wonderphil** [hashicorp/terraform#13434]
The following file has a mistake:

terraform/website/source/docs/providers/aws/r/kinesis_firehose_delivery_stream.html.markdown

advanced_options is
advanced_options {
    "rest.action.multi.allow_explicit_index" = true
  }

but sinces its a key pair should it not be:

advanced_options {
    "rest.action.multi.allow_explicit_index" = "true"
  }

I have tested with "true" and works, otherwise if true, it actually sets it to false

**Comment by stack72** [comment]
Hi @wonderphil 

Thanks for the report here - do you mean `elasticsearch_domain` rather than `kinesis_firehose_delivery_stream `?

Thanks

Paul

**Comment by wonderphil** [comment]
Sorry Paul yes, dont know why I done that
