### ISSUE TITLE
Referencing ARM deployment outputs before the deployment has finished gives an error

### ISSUE THREAD

**Issue by StephenWeatherford** [hashicorp/terraform#13437]
### Terraform Version
Terraform v0.9.3-dev (9f23779933474ac1e83679f47057b85c9071bee7+CHANGES)

### Affected Resource(s)
- azurerm_template_deployment

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "test" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
}
 
resource "azurerm_storage_account" "test" {
  name     = "${var.stgaccount_name}"
  location = "${var.location}"
  account_type = "Standard_LRS"
  resource_group_name = "${var.resource_group_name}"
 
  depends_on = ["azurerm_template_deployment.test"]
  tags {
      metadata = "${azurerm_template_deployment.test.outputs.outputValue}"
  }
}
 
resource "azurerm_template_deployment" "test" {
  name                = "test"
  resource_group_name = "${azurerm_resource_group.test.name}"
 
  template_body = <<DEPLOY
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "outputs":{
    "outputValue":{
      "type":"string",
      "value" : "Output Value"
    }
  },
  "resources": [
  ]
}
DEPLOY
 
  deployment_mode = "Incremental"
}
```

### Debug Output
https://gist.github.com/StephenWeatherford/bd52df7438b646916db3ee4a40ed2f4e

### Expected Behavior
The plan should succeed.

### Actual Behavior
* azurerm_storage_account.test: 1 error(s) occurred:
 
* azurerm_storage_account.test: Resource 'azurerm_template_deployment.test' does not have attribute 'outputs.outputValue' for variable 'azurerm_template_deployment.test.outputs.outputValue'

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
If you remove the output reference, apply, add back the reference and re-apply, it works.

### References
I've broken this off from #7353, as originally reported by @bpoland.

**Comment by StephenWeatherford** [comment]
I'm guessing the way to fix this would be to parse the deployment template in order to originally populate the outputs map before it's deployed.  Right now it's populated only afterwards.

**Comment by StephenWeatherford** [comment]
@dpoland, Here's a work-around:  Define a module for your template, then output the desired values from the module.

Example:  Create the following files, then run "terraform get && terraform apply":

**file ./module/template.tf:**
```tcl
variable "resource_group_name" {
}

output "outputValue" {
    value = "${azurerm_template_deployment.test.outputs.outputValue}"
}
 
resource "azurerm_template_deployment" "test" {
  name                = "test"
  resource_group_name = "${var.resource_group_name}"
 
  template_body = <<DEPLOY
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "outputs":{
    "outputValue":{
      "type":"string",
      "value" : "Output Value"
    }
  },
  "resources": [
  ]
}
DEPLOY
 
  deployment_mode = "Incremental"
}
```

**file ./test.tf**
```tcl
variable "resource_group_name" {
  default = <>
}
 
variable "location" {
  default = "westus"
}
 
variable "stgaccount_name" {
  default = <>
}
 
resource "azurerm_resource_group" "test" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
}
 
resource "azurerm_storage_account" "test" {
  name                = "${var.stgaccount_name}"
  location            = "${var.location}"
  account_type        = "Standard_LRS"
  resource_group_name = "${var.resource_group_name}"
 
  tags {
    metadata = "${module.template.outputValue}" // References the module output
  }
}
 
module "template" { // Consumes the module
    source = "./module"
    resource_group_name = "${var.resource_group_name}"
}
```

**Comment by bpoland** [comment]
Ok, thanks for the help.

**Comment by tombuildsstuff** [comment]
Hey @bpoland 

Just to add to @StephenWeatherford's comments - we'd recommend accessing outputs via `outputs["outputValue"]` rather than by `outputs.outputValue`. Using the file `./module/template.tf` example from Stephen's comment this would become:

```
variable "resource_group_name" {
}

output "outputValue" {
    value = "${azurerm_template_deployment.test.outputs["outputValue"]}"
}
 
resource "azurerm_template_deployment" "test" {
  name                = "test"
  resource_group_name = "${var.resource_group_name}"
 
  template_body = <<DEPLOY
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "outputs":{
    "outputValue":{
      "type":"string",
      "value" : "Output Value"
    }
  },
  "resources": [
  ]
}
DEPLOY
 
  deployment_mode = "Incremental"
}
```

The Documentation has been updated to use this syntax - would it be possible for you to take another look to see if this solves your issue? :)

Thanks!

**Comment by bpoland** [comment]
Aha, yes using the `outputs["outputValue"]` syntax works for me -- thanks for following up!
