### ISSUE TITLE
MalformedPolicyDocument: Policy document should not specify a principal.

### ISSUE THREAD

**Issue by amitsaha** [hashicorp/terraform#13449]
### Terraform Version

Terraform v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_iam_role_policy

### Terraform Configuration Files
```hcl
data "aws_iam_policy_document" "trust-assume-role-policy" {
  statement {

   actions = ["sts:AssumeRole"]

   principals {
     type        = "Service"
     identifiers = ["ec2.amazonaws.com"]
   }   

   principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::<account-id>:root"]
   }   
  }
}

resource "aws_iam_role_policy" "TrustUser" {
  name   = "TrustUser"
  role   = "SomeRole"
  policy = "${data.aws_iam_policy_document.trust-assume-role-policy.json}"
}

```
### Expected Behavior

IAM Role updated with policy

### Actual Behavior

```
MalformedPolicyDocument: Policy document should not specify a principal.
```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan1
2. `terraform apply`

### Important Factoids

EC2 classic

### References

- GH-53

**Comment by amitsaha** [comment]
@tombuildsstuff is this actually an issue? If so, is there a workaround? Thank you.

**Comment by eric-aldinger** [comment]
This is a documentationissue. Include your principals in an identifiers array.
```
data "aws_iam_policy_document" "report_ami_principals"{
  statement {
    actions =  ["sts:AssumeRole"],
    principals {
      type = "Service"
      identifiers = [
        "ec2.amazonaws.com",
        "events.amazonaws.com",
        "logs.us-west-1.amazonaws.com",
        "logs.us-west-2.amazonaws.com",
        "logs.us-east-1.amazonaws.com",
        "logs.us-east-2.amazonaws.com",
        "rds.amazonaws.com",
        "s3.amazonaws.com",
        "monitoring.rds.amazonaws.com",
      ]
    }
  }
}

```

**Comment by amitsaha** [comment]
Thanks @eric-aldinger . However, as you can see I am trying to specifying a second identifier which is of type `AWS` in addition to the EC2 service. 

Not sure how that will work?

**Comment by apparentlymart** [comment]
Hi @amitsaha,

I must admit to being a little rusty on IAM, but I think it's not valid to specify principals here because you're defining a *role* policy, and so the principal for it is *implied* to be the role itself.

The policy you're trying to apply here would give any principal holding the "SomeRole" role access to call `sts:AssumeRole`. Possibly what you actually wanted to do here was give the EC2 service and your root account access to *assume* this role, so they can gain the privileges associated with the role, in which case that is expressed a bit differently:

```hcl
data "aws_iam_policy_document" "trust-assume-role-policy" {
  # ... the same as in your example ...
}

resource "aws_iam_role" "some_role" {
  name = "SomeRole"
  assume_role_policy = "${data.aws_iam_policy_document.trust-assume-role-policy.json}"
}
```

There are two different types of policy associated with a role. The *assume role policy* defines which principals are able to obtain temporary credentials to act as this role (via the `sts:AssumeRole` action). The *role policy* defines what actions are permitted when *using* those temporary credentials. The `aws_iam_role_policy` resource you used in your example is for the latter type of policy, so I expect you *will* want to have at least one of these (otherwise the role would have no access) but the actions you'd include here would be for the target API your EC2 instances will be calling, not for `sts` itself.

So with that said, I think the behavior you got here is expected, though admittedly confusing. Terraform here is just exposing the raw data model of IAM, which itself is rather complex/confusing. Given that, I'm going to close this.

**Comment by amitsaha** [comment]
Thanks @apparentlymart - i will try your suggestion.

**Comment by IrfanAnsari** [comment]
@eric-aldinger I am exactly doing what you have suggested and its generating following JSON for the policy

`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "EnableIAMUserPermissions",
      "Effect": "Allow",
      "Action": "kms:*",
      "Resource": "*",
      "Principal": {
        "AWS": "arn:aws:iam::<accountid>:root"
      }
    },
    {
      "Sid": "AllowServicesUseOfTheKey",
      "Effect": "Allow",
      "Action": [
        "kms:GenerateDataKey*",
        "kms:Encrypt",
        "kms:DescribeKey"
      ],
      "Resource": "*",
      "Principal": {
        "Service": [
          "s3.amazonaws.com",
          "cloudtrail.amazonaws.com"
        ]
      }
    }
  ]
`   

and getting the same error 

`* aws_iam_policy.kms_key: Error creating IAM policy kms_key_policy: MalformedPolicyDocument: Policy document should not specify a principal.
	status code: 400, request id: 5a505304-6f15-11e8-a9da-69e8f5e0f4cd`

Any idea? Has anyone got it working?

**Comment by mauriziod** [comment]
The trust relationships must be added to aws_iam_role resource using assume_role_policy parameter. Using your example:
```
data "aws_iam_policy_document" "trust-assume-role-policy" {
  statement {

   actions = ["sts:AssumeRole"]

   principals {
     type        = "Service"
     identifiers = ["ec2.amazonaws.com"]
   }   

   principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::<account-id>:root"]
   }   
  }
}

resource "aws_iam_role" "test_role" {
  name               = "instance_role"
  assume_role_policy = "${data.aws_iam_policy_document.trust-assume-role-policy.json}"
}
```

**Comment by svunnam3** [comment]
Hi , 

I am trying to create AWSBackupIAMRole . Following is the code and error message. Can someone please assist

![image](https://user-images.githubusercontent.com/47794239/64642786-1aa89600-d3dd-11e9-85bf-8484e63f3231.png)

AWSTemplateFormatVersion: "2010-09-09"
Description: "Backup Plan template for thin backups"
Resources:
  AWSBackupIAMRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSBackupAdminPolicy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - backup.amazonaws.com
              Action:
                - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AWSBakupSnapshots
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ec2:CreateTags
                Resource: arn:aws:ec2:*::snapshot/*
              - Effect: Allow
                Action:
                  - ec2:CreateSnapshot
                  - ec2:DeleteSnapshot
                Resource:
                  - arn:aws:ec2:*::snapshot/*
                  - arn:aws:ec2:*:*:volume/*
              - Effect: Allow
                Action:
                  - ec2:DescribeVolumes
                  - ec2:DescribeSnapshots
                Resource: '*'
              - Effect: Allow
                Action:
                  - tag:GetResources
                  - tag:TagResources
                  - tag:UntagResources
                  - tag:getTagKeys
                  - tag:getTagValues
                Resource: '*'
  AWSBackupIAMProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref 'AWSBackupIAMRole'            
  
  BackupVaultWithThinBackups:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: "BackupVaultWithThinBackups"

  BackupPlanWithThinBackups:
    Type: "AWS::Backup::BackupPlan"
    Properties:
      BackupPlan:
        BackupPlanName: "BackupPlanWithThinBackups"
        BackupPlanRule:
          -
            RuleName: "RuleForDailyBackups"
            TargetBackupVault: !Ref BackupVaultWithThinBackups
            ScheduleExpression: "cron(0 * ? * * *)"
            Lifecycle:
              DeleteAfterDays: 1
    DependsOn: BackupVaultWithThinBackups

  TagBasedBackupSelection:
    Type: "AWS::Backup::BackupSelection"
    Properties:
      BackupSelection:
        SelectionName: "TagBasedBackupSelection"
        IamRoleArn: !GetAtt AWSBackupIAMRole.Arn
        ListOfTags:
         -
           ConditionType: "STRINGEQUALS"
           ConditionKey: "backup"
           ConditionValue: "thinbackup"
      BackupPlanId: !Ref BackupPlanWithThinBackups
    DependsOn: BackupPlanWithThinBackups
