### ISSUE TITLE
openstack_compute_volume_attach_v2 handles nonexistent resource incorrectly

### ISSUE THREAD

**Issue by michalmedvecky** [hashicorp/terraform#13452]
### Terraform Version

Terraform v0.9.0-dev (89acb5811a25e59e6a9d55cf5a2429846e3b5982+CHANGES)

### Problem description

When you correctly create volume_attach within existing resources, and then the resource disappears from openstack (deleted externally), another terraform apply should re-create it, but actually it does not.

### Affected Resource(s)

openstack_compute_volume_attach_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_volume_attach_v2" "attach_backups" {
  instance_id = "${openstack_compute_instance_v2.galera-node.0.id}"
  volume_id = "${openstack_blockstorage_volume_v2.sec-mariadb-backups.id}"
}
```

### Actual Behavior
```
openstack_compute_volume_attach_v2.attach_backups: Refreshing state... (ID: 7c807b05-1226-4650-92af-1bca68648000/368951b4-a003-4525-93ee-1595b6034c38)
Error refreshing state: 1 error(s) occurred:

* openstack_compute_volume_attach_v2.attach_backups: openstack_compute_volume_attach_v2.attach_backups: Resource not found
```

### Steps to Reproduce
1. create instance, volume, and attachment
2. `terraform apply`
3. delete attachment (or instance, or blockdevice, or everything) in openstack
4. `terraform apply`

**Comment by jtopjian** [comment]
@michalmedvecky Thanks for the report. Have you tried this since #13342 was merged? If not it will be in the next release. That _should_ fix this problem.
