### ISSUE TITLE
DNS record with values conatining whitespaces is set incorrectly

### ISSUE THREAD

**Issue by hpio** [hashicorp/terraform#13463]
Hi,
I've been trying to set a DNS record using **google_dns_record_set** resource for a while and still not able to get it to work
 
### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- google_dns_record_set

### Terraform Configuration Files
```
resource "google_dns_record_set" "spf" {
    managed_zone = "${google_dns_managed_zone.example-com.name}"
    name = "spf.example.com."
    type = "TXT"
    ttl = "300"
    rrdatas = ["v=spf1 ip4:111.111.111.111 include:backoff.email-example.com -all"]
}
```

### Expected Behavior
**TXT** record is added with value ```"v=spf1 ip4:111.111.111.111 include:backoff.email-example.com -all"```

### Actual Behavior
**TXT** record is added with value ```"v=spf1" "ip4:111.111.111.111" "include:backoff.email-example.com" "-all"``` and in that form it's not passing SPF validation

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by j0sh3rs** [comment]
+1 -- Still seeing this issue v0.9.4.  Attempting to escape the spaces inside the quoted rrdata fails Terraform's internal checks.
```
Failed to load root config module: Error parsing /Users/joshua.simmonds/Documents/gitlab/ops/terraform-public-dns/ops/global/test.tf: At 59:65: illegal char escape
```
Is there a known workaround for this problem?

**Comment by paddycarver** [comment]
Sorry for the delay in addressing this, and the problems!

Using the [API Explorer](https://developers.google.com/apis-explorer/#p/dns/v1/dns.changes.create), I've recreated this problem, and think I have a workaround.

The behaviour of splitting on spaces and quoting each chunk comes from the API, not Terraform.

The following request worked for me:

```
POST https://www.googleapis.com/dns/v1/projects/<MYPROJECT>/managedZones/<MYZONE>/changes?key=<APIKEY>
{
 "additions": [
  {
   "kind": "dns#resourceRecordSet",
   "name": "tf-test.<MYZONE>.",
   "type": "TXT",
   "rrdatas": [
    "\"v=spf1 ip4:111.111.111.111 include:backoff.email-example.com -all\""
   ],
   "ttl": 300
  }
 ]
}
```

Yielding:

```
200 OK
{
 "kind": "dns#change",
 "additions": [
  {
   "kind": "dns#resourceRecordSet",
   "name": "tf-test.<MYZONE>.",
   "type": "TXT",
   "ttl": 300,
   "rrdatas": [
    "\"v=spf1 ip4:111.111.111.111 include:backoff.email-example.com -all\""
   ]
  }
 ],
 "startTime": "2017-05-18T20:12:40.364Z",
 "id": "24",
 "status": "pending"
}
```

Based on that, I figured setting the config like so would work:

```hcl
resource "google_dns_record_set" "spf" {
    managed_zone = "<MYZONE>"
    name = "spf.<MYZONE>."
    type = "TXT"
    ttl = "300"
    rrdatas = ["\"v=spf1 ip4:111.111.111.111 include:backoff.email-example.com -all\""]
}
```

And trying it out, it looks like that works fine for me. So the solution is to put the entire thing in double quotes, and you need to escape the double quotes for HCL's sake.

I'm going to close this out, but if that solution doesn't work for you (for whatever reason) or you'd like to continue discussing this, feel free to just comment again, and we can reopen the issue.

**Comment by j0sh3rs** [comment]
@paddycarver Thanks so much for looking into this. I'll give this a try. Glad to know it's an api problem! Does Terraform provide feedback to providers that could produce a fix for this in their api?

**Comment by paddycarver** [comment]
@danawillow works for Google, and sometimes offers feedback to the teams when Terraform runs into problems. I sometimes raise issues on the [public issue tracker](https://issuetracker.google.com) for GCP. :) I've created [an issue](https://issuetracker.google.com/issues/62037975), but I don't have any special inside track that isn't already available to everyone else. :)
