### ISSUE TITLE
'forces new resource' on unchanged item when changing count from 1 to N

### ISSUE THREAD

**Issue by ahl** [hashicorp/terraform#13472]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

reproduced on:
stock 0.9.2
and
Terraform v0.9.3-dev (df5dfb10c8276aff74a3062c95246dd7ad8fa033+CHANGES)

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_nat_gateway

(but I doubt it's unique to that resource)

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-west-2"
}

variable "availability-zones" {
  default = ["us-west-2a", "us-west-2b", "us-west-2c"]
}

resource "aws_nat_gateway" "nat-gateway" {
  count = 1

  allocation_id = "eipalloc-XXXXXXX"
  subnet_id = "${element(aws_subnet.pub-subnet.*.id, count.index)}"
}

resource "aws_subnet" "pub-subnet" {
  count = 1 # <=== changing this to 2 causes nat-gateway above to be recreated

  vpc_id = "vpc-XXXXXXX"  cidr_block = "172.16.0.0/22"
  map_public_ip_on_launch = true

  availability_zone = "${var.availability-zones[count.index]}"
                         
  tags {                 
    Name = "${format("svc-%s-%s", "public", var.availability-zones[count.index]) }"       
  }                      
}                        
```

### Expected Behavior
Shouldn't re-create identical resource...

### Actual Behavior
... but it did.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. change 1 -> 2
2. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @ahl! Sorry things didn't work as expected here.

You are correct that this is not unique to this resource, and is in fact a general problem with using `element` with the splat syntax, as discussed in #3449.

This has been an issue for a while and we've been gradually working towards addressing it via a set of core changes. There's still some more work to do here though, so sadly there isn't a great workaround right now though there are some non-ideal ideas in the comments on that other issue.

I'm going to close this one just to consolidate the discussion over in #3449. Thanks for taking the time to file this issue!
