### ISSUE TITLE
map() should accept a single list as an argument

### ISSUE THREAD

**Issue by in4mer** [hashicorp/terraform#13476]
### Terraform Version
0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- core

### Expected Behavior
map() should be able to accept even-numbered lists as a single argument, and return a map to those value pairs

### Actual Behavior
Map claims to have gotten a single value, and says it can only create maps with pairs of values.

**Comment by apparentlymart** [comment]
Hi @in4mer! Sorry for the long silence here.

In Terraform v0.12, the function syntax was extended to support [list expansion](https://www.terraform.io/docs/configuration/expressions.html#expanding-function-arguments). That general feature can be used to meet the use-case you described here:

```
map(var.any_list...)
```

**Comment by in4mer** [comment]
Awesome, ty!

On a side note, I've stopped submitting bug reports for TF due to one person's abrasive censorship policies and attitude.  It's been very pleasant interacting with you, and I wish you well.
