### ISSUE TITLE
Enhance aws_s3_bucket lifecycle to support tag filter.

### ISSUE THREAD

**Issue by djrichar** [hashicorp/terraform#13473]
please enhance s3 bucket lifecycle to support the new tags filter

### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket

### Suggested Terraform Configuration
```hcl
resource "aws_s3_bucket" "bucketname" {
  bucket = "bucketname"
  lifecycle_rule {
    id      = "delete 30 days when tag DELETE = 30"
    prefix  = ""
    tags    = { 
      DELETE = 30
    }
    enabled = true

    expiration {
      days = 30
    }
  }
```

### Expected Behavior
What should have happened?
s3 bucket should have a lifecycle that deletes all objects with a tage 'DELETE' and value '30'

### Actual Behavior
What actually happened?
NOT SUPPORTED

### References
see http://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html#intro-lifecycle-rules-filter  for documentation

**Comment by bdashrad** [comment]
There are more complications with this being unsupported as well, like if you have a lifecycle rule that uses tags on the bucket, and one in the terraform config that is the same, other than the tags, it will silently overwrite it. (#12830)
