### ISSUE TITLE
Terraform remote state does not update if output-only changes are made

### ISSUE THREAD

**Issue by mindlace** [hashicorp/terraform#13477]
### Terraform Version
Terraform 0.9.2
### Affected Resource(s)
- terraform_remote_state 

### Expected Behavior
Changing outputs (only) and performing `terraform apply` updates remote state with new outputs

### Actual Behavior
Nothing, remote state unchanged, even though new outputs are shown in console.

### Steps to Reproduce

1. add a variable to output without changing anything else
2. `terraform apply`
3. observe the remote state has not changed

### Important Factoids
Using terraform s3 backend, if it matters.

**Comment by mindlace** [comment]
nevermind, pebcak

**Comment by roccato** [comment]
Out of curiosity what did you mess up? I'm hitting the same issue

**Comment by mindlace** [comment]
As I recall it was just that I was not in the environment I meant to be in,
and needed to do `terraform env select <someenv>` and then it worked.

Either that or it was that `terraform_remote_state` requires you pass in
`environment="${terraform.env}"` in order for terraform to read the state
for that environment, and I didn't have that in the remote state stanzas,
so it was always reading state from "default".

Hope that helps,

~ethan

**Comment by vliao-semios** [comment]
Came across this issue today. 

main.tf:
```
```
