### ISSUE TITLE
Nested map value incorrectly rendered as single-element list containing the map value

### ISSUE THREAD

**Issue by in4mer** [hashicorp/terraform#13479]
### Terraform Version
0.9.2

### Affected Resource(s)
- core

### Terraform Configuration Files
```
variable "tags_by_role" {
  type = "map"
  default = {
    app = { this.is.a.tag = "true" }
    db  = { another.tag   = "stuff"
            still.more    = "crap" }
  }
}

output "straight_out" {
  value = "${var.tags_by_role["app"]}"
}
```

### Expected Behavior
Subscript reference to this map key should return the correct map, not the correct map encapsulated in a single-element list.

### Actual Behavior
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

straight_out = [
    {
        this.is.a.tag = true
    }
]
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
- nested hash

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/hashicorp/terraform/issues/13440
- https://github.com/hashicorp/terraform/issues/13347

**Comment by apparentlymart** [comment]
Hi @in4mer! Thanks for reporting this.

This is the same root problem as described in #11115, which I've verified is fixed in master ready for the forthcoming v0.12.0 release, and so I'm going to close this out.

Thanks again for reporting it, and sorry for the delay in fixing it.
