### ISSUE TITLE
AWS AMI Instance Output With Elastic IP Shows Incorrect Public IP

### ISSUE THREAD

**Issue by eric-aldinger** [hashicorp/terraform#13475]
### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
- aws_instance
- aws_eip

I think this is the interplay between these two resource types

### Terraform Configuration Files
```
resource "aws_eip" "reporting" {
  vpc                       = true
  instance               = "${aws_instance.pentaho_reporting.id}"
  associate_with_private_ip = "${var.ami_eip_private_ip}"
  depends_on =["aws_instance.reporting"]
}

resource "aws_instance" "reporting" {
  ami                               = "${var.analytics_ami_id}"
  availability_zone           = "${var.az_target}"
  instance_type               = "${var.analytics-ami-instance-type}"
  monitoring                     = true
  key_name                     = "${var.rpt-deploy-key-name}"
  user_data                      = "${file("../scripts/provision-pentaho-ba.sh")}"
  subnet_id                       = "${data.aws_subnet.subnet_primary.id}"
  vpc_security_group_ids       = [ "${data.aws_security_group.reporting_database.id}",
                                                    "${data.aws_security_group.reporting_primary.id}" ]
  private_ip                        = "${var.ami_eip_private_ip}"
  iam_instance_profile       = "${var.report_profile_name}"
  tags {
    Name                            = "pentaho analytics ami"
    os                                  = "ubuntu xenial"
    virtualization                  = "hvm"
    RootDeviceType           = "ebs"
    block_device_mappings_specified = "true"
    source                          = "packer"
    version                         = "${var.version}"
    ami_version                 = "${var.ami_version}"
    creation_date               = "${timestamp()}"
    provisioner                    = "Terraform"
    comments                     = "image used to build clusters with all the setup complete for a single node"
 }
 lifecycle {
   ignore_changes = ["tags.creation_date"]
  }
}
```

### Debug Output
https://gist.github.com/eric-aldinger/fd9f4962144687a5de0dcb0302651a60

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
This is my desired behavior. The public ip of the aws instance resource should match the associated eip. If an eip is associated with the instance it should change the instance resources public ip.  The public ip should not change if I rerun the terraform apply subsequent times with no changes. This would make state idempotent.
elastic_ip = 52.39.63.29
private ip = 204.15.5.28
public ip = 52.39.63.29

### Actual Behavior
The public ip of the aws instance resource shows the calculated public ip instead of the associated eip.  Subsequent terraform apply runs pick up the public ip change based on the application of the eip resource. This makes state non-idempotent. 

### Steps to Reproduce
1. Include an instance with a private ip and an eip with associate_with_private_ip set to the ip of the instance. 
2. `terraform apply`
3. Make no changes
4. `terraform apply`

**Comment by rdonkin** [comment]
One workaround is to refer to `aws_eip.my-server.public_ip` which gives the Elastic IP address.
