### ISSUE TITLE
aws_elb listener creation soft fails when protocol is TCP and you specify HTTPS cert.

### ISSUE THREAD

**Issue by sprutner** [hashicorp/terraform#13480]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.9.2
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_elb

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
    listener {
        instance_port         = 8200
        instance_protocol  = "tcp"
        lb_port                    = 443
        lb_protocol             = "tcp"
        ssl_certificate_id    = "${aws_iam_server_certificate.vault_cert.arn}"

    }
-------------
    listener {
        instance_port         = 8200
        instance_protocol  = "https"
        lb_port                    = 443
        lb_protocol             = "https"
        ssl_certificate_id    = "${aws_iam_server_certificate.vault_cert.arn}"

    }
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Creation of a listener at port 443 to port 8200 with SSL cert installed

### Actual Behavior
Terraform applies successfully, but no listener appears.
The problem is because it needs to be HTTPS not TCP. I changed it to HTTPS and everything worked fine. TF should catch that TCP is not valid if you are using  ssl_certificate_id

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `Apply the following config to ELB`
2. `Revel in fact that it magically didn't appear`
3. `Try to create it yourself and then realize there is an HTTPS option`
4. `Change protocol to HTTPS and now it magically works :)`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by majormoses** [comment]
@sprutner any chance you could increase the logging verbosity (https://www.terraform.io/docs/internals/debugging.html), try running again, and post a gist? The reason I ask is that based on a quick investigation it does not appear that should be a valid parameter combination. AWS api should be returning a 400 with "InvalidParameterCombination".  We should definitely catch any 400s and if we are somehow swallowing it then we need to fix that. If we are not getting a 400 from aws then this needs to be addressed in their api. That being said we can maybe put in some logic to try to warn users when they try to do this or at least make it very clear in the documentation. 

Some related documentation:
- http://docs.aws.amazon.com/elasticloadbalancing/2012-06-01/APIReference/API_CreateLoadBalancerListeners.html
- http://docs.aws.amazon.com/elasticloadbalancing/2012-06-01/APIReference/CommonErrors.html
