### ISSUE TITLE
`aws_iam_role` Missing from new website

### ISSUE THREAD

**Issue by matthew-lowe-izettle** [hashicorp/terraform#13498]
[aws_iam_role](https://www.terraform.io/docs/providers/aws/r/iam_role_policy.html) is no longer visible from https://www.terraform.io/docs/providers/aws/.

**Comment by tombuildsstuff** [comment]
Hi @matthew-lowe-izettle 

Thanks for reporting this, I've [updated the website to add the link back in the sidebar](https://www.terraform.io/docs/providers/aws/r/iam_role.html) - so I'm going to close this issue :)

Thanks!
