### ISSUE TITLE
Dead link intro/index.html

### ISSUE THREAD

**Issue by bh9** [hashicorp/terraform#13500]
https://github.com/hashicorp/terraform/blob/master/website/source/docs/index.html.markdown mentions a getting started guide but the link points to intro/index.html which doesn't exist anymore, the link should probably be updated

**Comment by tombuildsstuff** [comment]
Hi @bh9 

Thanks for reporting this issue.

Some background: we generate the Terraform website from the Markdown files in this repository. This means that the `*.markdown` files present in this repository are configured to be viewed once rendered through Middleman, either on [the main Terraform website](https://terraform.io/docs/index.html) or [locally via the Docker image](http://localhost:4567/docs/index.html).

When viewing these files in the GitHub UI - GitHub includes the branch information in the URL (e.g. `/hashicorp/terraform/blob..`) - and doesn't transform the URL's in the Markdown to account for this, which means the links don't work.

Instead we'd recommend viewing the documentation on either [Terraform.io](https://terraform.io/docs/index.html) or using the Docker image, [for which there's documentation available here](https://github.com/hashicorp/terraform/tree/master/website).

Apologies there's not a lot we can do here - it's a limitation on GitHub's end :(

Thanks!
