### ISSUE TITLE
provider/openstack: Port updates broken following #11949

### ISSUE THREAD

**Issue by fatmcgav** [hashicorp/terraform#13531]
It would appear that the Gophercloud vendor updates as part of PR #11949 has broken port updates. 

When attempting to update a port security group list now, the request is failing.

>2017/04/11 10:49:08 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/11 10:49:08 [DEBUG] OpenStack Request Options: {
2017/04/11 10:49:08 [DEBUG] plugin: terraform:   "port": {
2017/04/11 10:49:08 [DEBUG] plugin: terraform:     "allowed_address_pairs": null,
2017/04/11 10:49:08 [DEBUG] plugin: terraform:     "security_groups": [
2017/04/11 10:49:08 [DEBUG] plugin: terraform:       "115ebfa2-d112-42b6-8880-b57fe22b09bc"
2017/04/11 10:49:08 [DEBUG] plugin: terraform:     ]
2017/04/11 10:49:08 [DEBUG] plugin: terraform:   }
2017/04/11 10:49:08 [DEBUG] plugin: terraform: }
2017/04/11 10:49:09 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/11 10:49:09 [DEBUG] OpenStack Response Body: {
2017/04/11 10:49:09 [DEBUG] plugin: terraform:   "ErrorCode": "500",
2017/04/11 10:49:09 [DEBUG] plugin: terraform:   "ErrorMessage": "An internal server error occurred at your requested service. You should try to send the request again.detail: An error of service. (REQ_006945487)",
2017/04/11 10:49:09 [DEBUG] plugin: terraform:   "MessageID": "E500",
2017/04/11 10:49:09 [DEBUG] plugin: terraform:   "ServerID": "uk-1a_197"
2017/04/11 10:49:09 [DEBUG] plugin: terraform: }

### Terraform Version
`Terraform v0.9.3-dev`

### Affected Resource(s)
Please list the resources as a list, for example:
- `openstack_networking_port_v2`

### Terraform Configuration Files
```hcl
~ module.instance.openstack_networking_port_v2.instance_port.0
    security_group_ids.#:          "0" => "1"
    security_group_ids.1501801958: "" => "115ebfa2-d112-42b6-8880-b57fe22b09bc"
```

### Expected Behavior
Port should be updated

### Actual Behavior
Request fails

### References
- https://github.com/gophercloud/gophercloud/issues/226

**Comment by fatmcgav** [comment]
@jtopjian I've just pushed https://github.com/fatmcgav/terraform/commit/2994bd141e6abff89c9fa35ed150dc37dd3b0538. Thoughts on suitability before I raise as a PR?

**Comment by jtopjian** [comment]
@fatmcgav Thanks for the report. Are you able to provide the initial Terraform configuration and modified configuration that is triggering this error?

**Comment by fatmcgav** [comment]
@jtopjian This is the resource.

`var.security_groups` defaults to `[]`, but can also be a list of security group UUIDs.

```hcl
# Create instance port
resource "openstack_networking_port_v2" "instance_port" {
  count              = "${var.count * length(split(",", lookup(var.common, "azs")))}"
  region             = "${lookup(var.common, "region")}"
  name               = "${lookup(var.common, "project")}_server_port_${replace("${lookup(var.common, "region")}${element(split(",", lookup(var.common, "azs")), count.index)}", "/^\\w+-/","")}_${var.server_role}_${format(var.count_format, floor(count.index / 2)+1)}"
  network_id         = "${element(split(",", lookup(var.networks, "${lookup(var.common, "project")}_network_${replace("${lookup(var.common, "region")}${element(split(",", lookup(var.common, "azs")), count.index)}", "/^\\w+-/","")}_${var.network_zone}")), 0)}"
  security_group_ids = ["${distinct(list(element(var.security_groups, count.index), element(var.security_groups, count.index+2), element(var.security_groups, count.index+4)))}"]
  admin_state_up     = "true"
  value_specs        = {
    availability_zone = "${element(split(",", lookup(var.common, "razs")), count.index)}"
  }
}
```

The plan above and corresponding log shows a failure example, which works with the commit reference above applied :)

**Comment by jtopjian** [comment]
OK, so to clarify: you are performing a `terraform apply` which creates a port that does not have `security_group_ids` set and then you modify the configuration which sets `security_group_ids`, run `terraform apply` again, and that's when the error happens?

**Comment by fatmcgav** [comment]
Yep, that's the flow...

**Comment by jtopjian** [comment]
While trying to reproduce the issue, I saw that security groups were occasionally failing to delete due to a 409 error being thrown. I'm not sure if this is the cause of what you're seeing, though.

Another thing I noticed is that if no security groups are specified on a port, Neutron will apply the "default" security group. If you later add a security group to `security_group_ids`, the default security group will be removed and the new group will be applied. Perhaps your OpenStack environment is preventing the deletion of the default group?

I have a commit [here](https://github.com/jtopjian/terraform/commit/1a1c2117b464628bb889a8c0994bd7c82ea4542c) which handles the 409 error. As well, it includes a test case for the scenario you're describing:

1. Create a port with no security groups
2. Add a security group
3. Remove that security group

Notice in the test case how Step 1 is checking for a count of 1 even though no groups are defined -- this is the default group that gets added.

Also notice in Step 3 how you have to explicitly set `security_group_ids` to `[]`. This is because the attribute is "Computed" and just removing the line from the configuration won't actually remove it from the state.

Without the above 409 patch and the explicit `security_group_ids = []`, I was unable to get the test case to pass, even with your patch in #13546. 

Can you take a look at that commit and see if the areas it covers might be the core cause of the error you're seeing? If it's not, we'll have to dig a bit more into your cloud configuration.

**Comment by fatmcgav** [comment]
@jtopjian 

I think possibly the focus needn't be on security groups specifically, but on general port updates. 

E.g., I just tried changing the port name, and had the same failure. This is on a fresh build from master, with your commit applied.
Plan result
```hcl
~ openstack_networking_port_v2.packer_test_instance_3
    name: "packer_test_instance_3" => "packer_test_instance_3_port"
```

And debug log:
> 2017/04/11 21:17:20 [DEBUG] apply: openstack_networking_port_v2.packer_test_instance_3: executing Apply
openstack_networking_port_v2.packer_test_instance_3: Modifying... (ID: 935ef435-9587-41a6-a3b7-0b57c69d5167)
  name: "packer_test_instance_3" => "packer_test_instance_3_port"
2017/04/11 21:17:20 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/11 21:17:20 [DEBUG] Updating Port 935ef435-9587-41a6-a3b7-0b57c69d5167 with options: {Name:packer_test_instance_3_port AdminStateUp:<nil> FixedIPs:<nil> DeviceID: DeviceOwner: SecurityGroups:[] AllowedAddressPairs:[]}
2017/04/11 21:17:20 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/11 21:17:20 [DEBUG] OpenStackRequest URL: PUT https://networking.uk-1.cloud.global.fujitsu.com/v2.0/ports/935ef435-9587-41a6-a3b7-0b57c69d5167
2017/04/11 21:17:20 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/11 21:17:20 [DEBUG] OpenStackRequest Options: {
2017/04/11 21:17:20 [DEBUG] plugin: terraform:   "port": {
2017/04/11 21:17:20 [DEBUG] plugin: terraform:     "allowed_address_pairs": null,
2017/04/11 21:17:20 [DEBUG] plugin: terraform:     "name": "packer_test_instance_3_port",
2017/04/11 21:17:20 [DEBUG] plugin: terraform:     "security_groups": null
2017/04/11 21:17:20 [DEBUG] plugin: terraform:   }
2017/04/11 21:17:20 [DEBUG] plugin: terraform: }
2017/04/11 21:17:21 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/11 21:17:21 [DEBUG] OpenStack Response Body: {
2017/04/11 21:17:21 [DEBUG] plugin: terraform:   "ErrorCode": "500",
2017/04/11 21:17:21 [DEBUG] plugin: terraform:   "ErrorMessage": "An internal server error occurred at your requested service. You should try to send the request again.detail: An error of service. (REQ_007923344)",
2017/04/11 21:17:21 [DEBUG] plugin: terraform:   "MessageID": "E500",
2017/04/11 21:17:21 [DEBUG] plugin: terraform:   "ServerID": "uk-1a_198"
2017/04/11 21:17:21 [DEBUG] plugin: terraform: }

As you can see in the request body, it's got a `null` value for both `security_groups` and `allowed_address_pairs`. The <0.9.0 behaviour was to omit those fields if they were empty, however now they've got a `null` value which is causing the server to reject the request. 

Thoughts?

**Comment by fatmcgav** [comment]
Just had another thought... If providing empty `[]` values isn't the right option, then is it worth overloading the [`ToPortUpdateMap`](https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/ports/requests.go#L127-L129) func in Terraform to delete the `null` keys if present?

**Comment by jtopjian** [comment]
> As you can see in the request body, it's got a null value for both security_groups and allowed_address_pairs. The <0.9.0 behaviour was to omit those fields if they were empty, however now they've got a null value which is causing the server to reject the request.

Are you positive that is what's causing the problems? If so, then I think that might be an issue with the cloud you're using.

The Network API accepts null values for both `allowed_address_pairs` and `security_groups`. The Gophercloud PR and issue describes how and why this is correct behavior.

**Comment by fatmcgav** [comment]
As positive as I can be... In that by removing them from the request body, the request works... 

It's certainly possible it's a cloud specific issue, as there's lots of other 'non-standard' tweaks... 

Are you able to confirm that the above request, with `null` values for `security_groups` and `allowed_address_pairs` works on a vanilla openstack installation?

**Comment by jtopjian** [comment]
> Are you able to confirm that the above request, with null values for security_groups and allowed_address_pairs works on a vanilla openstack installation?

Yes - works for me. 

I edited the comment above, but I did notice that `allowed_address_pairs` was sending `null` when it should have been `[]`.  So you were definitely correct with your patch, but it does seem like this might be another vendor-specific modification made. Which is fine, but just makes things very frustrating to troubleshoot.

I've rolled your patch into this branch, which also takes care of the 409 issue:

https://github.com/jtopjian/terraform/tree/openstack-port-update-fixes

I need to do a full acceptance test run on it before submitting it, but if you want to see if everything works on your end, go for it. :)

**Comment by jtopjian** [comment]
All tests pass, so if you give the OK on your side, we're good to go :)

**Comment by fatmcgav** [comment]
@jtopjian Just gave your branch a whirl, and looks to work as I'd expect.. :) 

> 2017/04/12 09:46:52 [DEBUG] apply: openstack_networking_port_v2.packer_test_instance_3: executing Apply
  name: "packer_test_instance_3" => "packer_test_instance_3_port"
2017/04/12 09:46:52 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/12 09:46:52 [DEBUG] Updating Port 935ef435-9587-41a6-a3b7-0b57c69d5167 with options: {Name:packer_test_instance_3_port AdminStateUp:<nil> FixedIPs:<nil> DeviceID: DeviceOwner: SecurityGroups:[69ae7594-d808-49f7-8e12-da3f56fd034e] AllowedAddressPairs:[]}
2017/04/12 09:46:52 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/12 09:46:52 [DEBUG] OpenStack Request URL: PUT https://networking.uk-1.cloud.global.fujitsu.com/v2.0/ports/935ef435-9587-41a6-a3b7-0b57c69d5167
2017/04/12 09:46:52 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/12 09:46:52 [DEBUG] OpenStack Request Options: {
2017/04/12 09:46:52 [DEBUG] plugin: terraform:   "port": {
2017/04/12 09:46:52 [DEBUG] plugin: terraform:     "allowed_address_pairs": [],
2017/04/12 09:46:52 [DEBUG] plugin: terraform:     "name": "packer_test_instance_3_port",
2017/04/12 09:46:52 [DEBUG] plugin: terraform:     "security_groups": [
2017/04/12 09:46:52 [DEBUG] plugin: terraform:       "69ae7594-d808-49f7-8e12-da3f56fd034e"
2017/04/12 09:46:52 [DEBUG] plugin: terraform:     ]
2017/04/12 09:46:52 [DEBUG] plugin: terraform:   }
2017/04/12 09:46:52 [DEBUG] plugin: terraform: }

So happy to close my PR in preference of urs :)
