### ISSUE TITLE
Provide minimal provisioning features

### ISSUE THREAD

**Issue by 7heo** [hashicorp/terraform#1354]
### Overview
I open this ticket to propose to implement bare minimal provisioning features in terraform. Before rejecting the idea mentally, please take the time to read what follows. My suggestion is motivated by a use case we encountered, and could have many benefits at a very acceptable cost (note the "minimal" keyword).

### Some background
In a short meeting with our team today, we tried to review the various existing tools for provisioning. There are plenty of them, all different, and so, we went for a feature matrix. Here is an excerpt of it:

<table>
  <tr>
    <th></th>
    <th colspan=2>Resource Provisioning</th>
    <th colspan=2>Service Provisioning</th>
  </tr>
  <tr>
    <th></th>
    <th>Infrastructure Setup</th>
    <th>SCM Setup</th>
    <th>Container Setup</th>
    <th>Service Setup</th>
  </tr>
  <tr>
    <th>Terraform</th>
    <td>✓</td>
    <td>Via remote-exec provider</td>
    <td>✗</td>
    <td>✗</td>
  </tr>
  <tr>
    <th>Chef</th>
    <td>✗</td>
    <td>✗</td>
    <td>✓</td>
    <td>✓</td>
  </tr>
  <tr>
    <th>...</th>
    <td>...</td>
    <td>...</td>
    <td>...</td>
    <td>...</td>
  </tr>
</table>

As @phinze confirmed on IRC:
> we see many folks using remote-exec to do stuff like kick off a bootstrapping script [...] where remote-exec is basically just a "handoff" to a [configuration management tool].

That can work, with some very small shell glue (a few lines), but shell brings in a major problem. Read on.

### Problem to address
At the time I am submitting this ticket, it is possible, as aforementioned, with some very minimal shell glue, to use terraform to completely generate a VM on many cloud providers, and "bootstrap" a SCM on it to do the service provisioning.

However, terraform is meant to use a declarative language, and the `remote-exec` provisioner uses an imperative language (shell). For example:

```PHP
provider "google" {
    account_file = "service_account_credentials.json.secret"
    project = "project"
    region = "europe-west1-b"
}

variable "RPU" {
    description = "Resource Provisioning User"
}

resource "google_compute_instance" "default" {
    name = "gce-vm-0"
    machine_type = "f1-micro"
    zone = "europe-west1-b"

    disk {
        image = "debian-7-wheezy-v20140814"
    }

    network_interface {
        network = "default"
        access_config {
            #Ephemeral IP
        }
    }

    provisioner "remote-exec" {
        connection {
            user = "${var.RPU}"
            key_file = "~/.ssh/id_rsa"
        }
        inline = [
        "$pkg_mgr install $scm $rcs",
        "curl http://cloud.provider.internal/api/some/data >> folder/file",
        "$rcs get protocol://repository",
        "$scm apply"
        ]
    }

    metadata {
        sshKeys = "${var.RPU}:${file(\"~/.ssh/id_rsa.pub\")}"
    }

    service_account {
        scopes = ["userinfo-email", "compute-ro", "storage-ro"]
    }
}
```
As you can see in this example, most of the file's syntax is declarative. However, there are four lines that aren't. They are using imperative syntax, and their order is meaningful. For a tool whose purpose is to describe your infrastructure and apply it, that is less than ideal. And yes, you can put those four lines in a script, but that is just hiding the issue, not solving it.

### Proposed solution
What I propose is to implement a *strictly minimal* set of resources:
- Bare package management (updating cache and installing packages)
- Downloading utilities (via $rcs and curl) optional destination (if not provided, the file goes in the remote user directory, with the name it had on the source).
- Software Configuration Management execution, which will always be executed last.

### What benefits does that grant?
First and foremost, with those new resources, it will be possible to prepare a newly created VM so it executes a SCM with the needed information, without a single line of imperative script.

But secondarily, it makes it possible for users to perform rudimentary setups without needing to have recourse to SCMs. Example: create a VM, install nginx, php-fpm. That would provide a pre-configured development/testing host with ssh, right out-of-the-box.

----

So I am proposing to implement that myself, and I would really like to see that merged in master for version 0.5. Feedback and suggestions welcome.

**Comment by mitchellh** [comment]
Thanks for the issue. I'll attempt to hit upon everything, but if I miss something let me know. I have no intention of skirting around anything.

Regarding imperative vs declarative: I disagree with your assessment. Shells on machines are inherently imperative. Tools like Chef, Puppet mask that from you (you're just pushing it one level deeper), and Terraform isn't meant to replace those. We sit outside the "resource" level and we view a provisioner (actually, the set of all provisioners) as an atomic unit: if any part of that unit fails, the entire resource is tainted and restarted. 

We have plans to make this more granular in the future (marking a single provisioner as "idempotent" for example would let us know we can just re-execute that step if it didn't complete, and the continue from there). This will help a lot, but is an optimization, not strictly necessary.

I'm very opinionated about keeping machine-local things such as packages outside of Terraform. It will very quickly turn Terraform into a much more complex tool, regardless of its a good idea or not. From the perspective of iterating on Terraform over time, it would overburden us when there is a strong workaround.

What I am open to is bringing in first class support for Chef/Puppet/etc. so that Terraform handles potentially installing and then running it for you. I think this would lower the barrier enough that you can continue to use best of breed SCM tools, and with the aforementioned plans to eventually mark things "idempotent", I think the pair together would make things pretty interesting.

That is all to say: I value your feedback but even if this is a good idea I am going to say no for now. My personal opinion is that this isn't necessary in Terraform even in the long run and that it would be better to closely integrate with existing SCMs. 

I hope this is satisfactory, and I welcome any discussion.

**Comment by 7heo** [comment]
Thanks @mitchellh to have taken the time to answer that issue with so much detail.

I will try to answer all you reacted on, the best I can:

I don't get what assessment you disagree with, but that's not really important, as I believe we want the same thing (direct handover from terraform to an SCM) in the end; we just are expressing it differently. However please feel free to explicit what assessment you disagree with, so I can understand better ;)

Regarding the fact that shells are imperative (yes, that's totally true) and that SCMs hide that from the user (true too); it's the whole point of my ticket:

Imperative syntax makes the order relevant. Declarative syntax makes the order irrelevant, basically delegating the choice of such order to the programmer of the tool, instead of the user of the tool. That has two advantages: first, it makes any problem regarding order relative to the tool, and therefore, solved for everyone at once. Second, it makes the programmer of the tool in charge of the order, instead of the user. And statistically, the programmer of the tool has less chances of doing human error than the user of the said tool.

Maybe I'm missing more advantages, but I feel that those are the main ones. All the SCMs are providing exactly that (in addition to having your Container and Service setup written in a versioned code repository and executed by a very fast machine, instead of existing only in your brain and being executed by your slow hands).

I totally understand why you're reticent to allow machine-relative and OS-relative tasks in terraform, as it will indeed increase the complexity of the tool by orders of magnitude in the long run. However, unless you provide statically-compiled (no dependencies) binaries for all existing SCMs, getting terraform to handover to any SCM means "installing packages". Whether that package installation facility is exposed to the terraform user is another question entirely, but it would be needed nevertheless.

If I got anything wrong, please tell me; but I believe that what I proposed (excepted exposing the facilities to the end user) is the easiest way to, to quote you: "closely integrate with existing SCMs".

So, to rephrase my proposition in your terms: please let me closely integrate existing SCMs in terraform. That is exactly my intention. However, if you feel that there is a better way to do so than the way I am proposing to do it; I will strongly consider it instead, as I want my PRs to have the best chances to be merged ;)

I, too, am welcome to any discussion.

**Comment by mitchellh** [comment]
I agree with your last point: integrating SCMs more closely into Terraform is our idea. Re: your concern about installation: yes, we've taken both stances in other projects of both knowing how to auto-install the SCM as well as not. We've found it easier to start to defer installation to the user (via remote-exec or some other method) but we do have experience doing both. I'm not sure what the correct solution is yet.

**Comment by 7heo** [comment]
My opinion on the correct solution (ofc ymmv):

1. Probe what package management system is there (not too hard to do, rather reliable, since UNIX-like systems heavily rely on package management).
2. Write a list of commands used for each known package management system (probably mostly "add" or "install", and "update" - pretty easy to do, and totally reliable, once you've figured out which package management you have).
3. Find a way to install the right packages, for the system at hand (the REAL difficulty is here, as package names might change from distribution to distribution, even for those which use the same package management system). So yeah, we/I have to solve *that* one reliably.
4. First time the package management is called (behind the scenes, it seems), trigger an update.
5. First time a feature depending on a package is called, install the needed package.

So yeah. Solving this problem mainly depends on the third item. I have my idea how to solve the problem, but while very reliable, it might be tricky with some systems (not all package management systems offer to list packages offering a given file at a given path).

More on that as I progress.
