### ISSUE TITLE
provider/fastly Name the Fastly user in the Fastly UI during terraform changes

### ISSUE THREAD

**Issue by travertischio** [hashicorp/terraform#13550]
Currently when making changes to Fastly caches with Terraform there is no user identified as the one who made the change in Fastly's UI. Is there a way to name this user in Terraform?

![fastly ui](https://cloud.githubusercontent.com/assets/1479130/23922207/d5b040c0-08d7-11e7-8322-ff9a408b72a2.png)

**Comment by philg1** [comment]
@travertischio This should be resolved if you use an API Token instead of an API key to authenticate. The token is credential that is owned by a user. Thus the audit log will be able to attribute events to that user.

**Comment by stack72** [comment]
Hi @travertischio 

Is this able to be closed because of the info above?

Thanks

Paul

**Comment by travertischio** [comment]
Hey @stack72,

That information is helpful, but I don't believe that Terraform currently supports the use of the API token for the fastly provider:
`provider.fastly: : invalid or unknown key: api_token`

I would say at this point this issue's request is more accurately to add support for token-based authentication through Terraform with the Fastly provider.
