### ISSUE TITLE
terraform creating GCE vm doesn't support multi nic configuration.

### ISSUE THREAD

**Issue by gandhams** [hashicorp/terraform#13564]
Hi, Any possibility this issue has been fixed. I verified that multiple nics (each nic in different networks) can be added to the same vm using the cli.

gcloud alpha compute instances create pavm-ssaha-swap-1 --can-ip-forward --network-interface subnet=mgmt-subnet --network-interface subnet=data1-subnet --network-interface subnet=data2-subnet --machine-type=n1-standard-2 --image pavm-guestos-feature-image --zone=us-west1-a --tags=pa-vm

**Comment by joelcollin** [comment]
@grubernaut, is it really a bug though? As much as I would love to be able to create multiple NICs through terraform, this is provided through the "alpha" set of commands that are not meant to be available to the general public.

**Comment by grubernaut** [comment]
@joelcollin, I'm not 100% familiar with the GCE environment, simply saw "This isn't working". I'll leave for @paddycarver to correctly triage. Thanks!

**Comment by joelcollin** [comment]
@grubernaut, no big deal, hence my comment.

For reference, Paul Nash's comment in this thread: https://groups.google.com/forum/#!topic/gce-discussion/hdcuQqdPHXo

**Comment by gandhams** [comment]
The GCE Deployment Manager allows the resource creation to use specific api.
eg.

resources:
- name: vm-instance
  type: compute.v1.instance <--- this can point to alpha/beta version and still be able to deploy.
  properties: <SNIPPED>

CLI also supports referring to alpha api.

gcloud alpha compute instances create pavm-ssaha-swap-1 --can-ip-forward --network-interface subnet=mgmt-subnet --network-interface subnet=data1-subnet --network-interface subnet=data2-subnet --machine-type=n1-standard-2 --image pavm-guestos-feature-image --zone=us-west1-a --tags=pa-vm

It would be great if there an option in terraform to be able to do similar config and test the deployments. I would have to fall back to GCE templates than using terraform because of this reason.

**Comment by gandhams** [comment]
https://cloud.google.com/deployment-manager/docs/step-by-step-guide/create-a-template

**Comment by danawillow** [comment]
Hey @gandhams! Right now Terraform doesn't support alpha/beta features for GCP due to some current technical limitations around calling multiple versions of the same API. However, this is a big priority for us and it's something we're planning on tackling soon (this summer). I'll fix the labeling on this issue and leave it open for now (and I'm going to remove @paddycarver from the assignee field since it's not something he can take action on yet). Hopefully in a few months we'll be able to swing back around to this. Thanks for the FR!

**Comment by funkydorian** [comment]
Hi!

Any progress on that?

**Comment by danawillow** [comment]
Hi @funkydorian, this support was added a while ago, and we document it as working: https://www.terraform.io/docs/providers/google/r/compute_instance.html#network_interface. Are you having issues with multi-nic support?

**Comment by Epiclemonaid** [comment]
yes @danawillow  this is the config we are using & here is the error

```  network_interface {
    subnetwork = "gcp-db"

    access_config {
      // Ephemeral IP
    }
  }


  network_interface {
    subnetwork = "gcp-cassandra"

    access_config {
      // Ephemeral IP
    }
  }
```

error: 

```
Error: Error applying plan:

3 error(s) occurred:

* module.usctr-prod-cassandra01.google_compute_instance.cassandra: 1 error(s) occurred:

* google_compute_instance.cassandra: Networks must be distinct for NICs attached to a VM.

* module.usctr-prod-cassandra02.google_compute_instance.cassandra: 1 error(s) occurred:

* google_compute_instance.cassandra: Networks must be distinct for NICs attached to a VM.

* module.usctr-prod-cassandra03.google_compute_instance.cassandra: 1 error(s) occurred:

* google_compute_instance.cassandra: Networks must be distinct for NICs attached to a VM.
```

terrafrom version & gcp 

Terraform v0.11.8
+ provider.google v1.20.0
+ provider.tls v1.2.0

Your version of Terraform is out of date! The latest version
is 0.11.11. You can update by downloading from www.terraform.io/downloads.html

**Comment by danawillow** [comment]
Hi @Epiclemonaid, take a look at the multi nic troubleshooting guide: https://cloud.google.com/vpc/docs/create-use-multiple-interfaces#i_am_not_able_to_create_vm_with_multiple_interfaces
