### ISSUE TITLE
Can't assign ipv6_cidr_block to aws_vpc

### ISSUE THREAD

**Issue by neilhwatson** [hashicorp/terraform#13561]
### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
aws_vpc

### Terraform Configuration Files
```hcl
resource "aws_vpc" "vpc-ae12d8c7" {
   cidr_block           = "172.31.0.0/16"
   #ipv6_cidr_block      = "2600:1f11:d5a:axxx:/56"
   #ipv6_association_id  = "vpc-cidr-assoc-2bfa3942"
   enable_dns_hostnames = true
   enable_dns_support   = true
   instance_tenancy     = "default"
}

```

### Expected Behavior
This vpc was imported with terraform import and now must be duplicated in terraform policy as above.

### Actual Behavior

    terraform plan
    ....
    "ipv6_cidr_block": this field cannot be set

If I remove the ipv6_cidr_block then plan reports that the existing vpc will be deleted and new on created. I assume getting a new ipv6 block. So it seems impossible to import a vpc with an ipv6 block.

**Comment by stack72** [comment]
Hi @neilhwatson 

This is actually the case with Amazon - you can only tell them to assign an IPv6 CIDR block - you cannot  tell them which CIDR block to assign I am afraid

You can have a look at their [docs](http://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpc.html) on it

Sorry for this

Paul
