### ISSUE TITLE
Modules without names are ignored

### ISSUE THREAD

**Issue by JDiPierro** [hashicorp/terraform#13575]
### Terraform Version
0.9.1

### Affected Resource(s)
Terraform Core: Modules

### Terraform Configuration Files
```hcl
module {
  source = "../modules/foobar"
}
```

### Expected Behavior

An error telling me that the module definition is invalid.

### Actual Behavior

Plans run successfully, completely ignoring the module without a name.

### Steps to Reproduce
1. `terraform plan`

**Comment by grubernaut** [comment]
Hi @JDiPierro, thanks for the issue!

For clarification: Is this a regression, and did this work in previous releases?

**Comment by JDiPierro** [comment]
I'm not certain to be honest. I was working in terraform pre-coffee this morning and I accidentally forgot to give a module a name. I was perplexed when my plan was showing no pending changes. It struck me as odd behavior to not call that out as an error so I opened a ticket :)
