### ISSUE TITLE
VPC requirement for Internet Gateway in AWS

### ISSUE THREAD

**Issue by davebotelho** [hashicorp/terraform#13587]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

[cloud-user@ip-10-114-128-113 aws]$ terraform -v
Terraform v0.8.4

Your version of Terraform is out of date! The latest version
is 0.9.2. You can update by downloading from www.terraform.io

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_elb

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "aws_elb" "api-clb" {
  name               = "api-${var.stack-name}"
  #availability_zones = ["${var.availability_zones}"]
  subnets = ["${var.subnet_id}"]

  listener {
    instance_port     = 8443
    instance_protocol = "tcp"
    lb_port           = 8443
    lb_protocol       = "tcp"
  }

  health_check {
    healthy_threshold   = 10
    unhealthy_threshold = 2
    timeout             = 5
    target              = "TCP:8443"
    interval            = 30
  }

  instances                   = ["${aws_instance.master-servers.*.id}"]
  cross_zone_load_balancing   = false
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400

  tags {
    Name = "api-${var.stack-name}"
  }

  depends_on = ["aws_instance.master-servers"]
}

# Create router classic load balancer
resource "aws_elb" "router-clb" {
  name               = "router-${var.stack-name}"
  #availability_zones = ["${var.availability_zones}"]
  subnets = ["${var.subnet_id}"]

  listener {
    instance_port     = 80
    instance_protocol = "tcp"
    lb_port           = 80
    lb_protocol       = "tcp"
  }

  listener {
    instance_port      = 443
    instance_protocol  = "tcp"
    lb_port            = 443
    lb_protocol        = "tcp"
  }

  health_check {
    healthy_threshold   = 10
    unhealthy_threshold = 2
    timeout             = 5
    target              = "TCP:80"
    interval            = 30
  }

  instances                   = ["${aws_instance.infra-servers.*.id}"]
  cross_zone_load_balancing   = false
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400

  tags {
    Name = "router-${var.stack-name}"
  }

  depends_on = ["aws_instance.infra-servers"]
}

### Debug Output
Error applying plan:

2 error(s) occurred:

* aws_elb.api-clb: InvalidSubnet: VPC vpc-fc297e9a has no internet gateway
        status code: 400, request id: 4d6f2fdc-1f95-11e7-bf75-fdd77f89b221
* aws_elb.router-clb: InvalidSubnet: VPC vpc-fc297e9a has no internet gateway
        status code: 400, request id: 4dbe1348-1f95-11e7-ae1c-87c517547dd0

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?  Creation of our AWS ELB

### Actual Behavior
What actually happened?  Error out that it requires the VPC internet gateway be defined for a VPC but we have a private VPC extention of our internal DC that isn't going to be public such that there is no internet gateway

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? Building Classic ELB and Route53 CNAMEs within a private VPC extension of our DC that is not going to be publicly available.

I'm wondering if this is a hard requirement for us to create ELB's and why?

**Comment by ajlanghorn** [comment]
@davebotelho 

Hello! If I've read this correctly, you want to create an ELB which is internally addressed and only accessible to other services in your physical data centre. If that's the case, you'll want to [tell Terraform that you need an internal ELB](https://www.terraform.io/docs/providers/aws/r/elb.html#internal) by adding the `internal` parameter to the ELB instantiation with a value of `true`.

I think, in doing so, you'll end up without a hard dependency on an internet gateway, but you'll still need some way of connecting to your VPC from on-premise, such as Direct Connect.

Give that a go, and see if it helps.

(PS: you should probably upgrade your version of Terraform. 0.9.3 is out now.)

**Comment by davebotelho** [comment]
Thanks Andrew, I just figured that out and tested it.  Worked like a charm!

**Comment by ajlanghorn** [comment]
@davebotelho Awesome; glad I could help! If all works, it would be great if you could close this issue out :)
