### ISSUE TITLE
Feature Request: attribute "ipv6_cidr_block" from resource "aws_subnet"

### ISSUE THREAD

**Issue by sandnabba** [hashicorp/terraform#13595]
Hi!

I'm trying to assign static IPv6 addresses to multiple hosts in multiple subnets.
It would help a lot if the IPv6 block was available through an attribute, since now you have to build some custom solution.

The "ipv6_cidr_block" is already available as an attribute in the state file. 

### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
- aws_subnet

### Terraform Configuration Files
```hcl
resource "aws_instance" "instance_name" {
    count = "${length(var.subnets)}"
    ami = "${var.ami}"
    instance_type = "${var.instance_type}"
    ipv6_addresses = ["${replace("${element(data.aws_subnet.selected.*.ipv6_cidr_block, count.index)}", "/64", count.index +1)}"]
    subnet_id = "${var.subnets[count.index]}"
}
data "aws_subnet" "selected" {
  count = "${length(var.subnets)}"
  id = "${var.subnets[count.index]}"
}

```

### Expected Behavior
```
module.my_module.aws_instance.instance_name.0
    ami:                         "ami-af0462c3"
    ....
    ipv6_addresses.0:            "aaaa:bbbb:cccc:dddd::1"
```

### Actual Behavior
```
* module.my_module.aws_instance.instance_name[1]: Resource 'data.aws_subnet.selected' does not have attribute 'ipv6_cidr_block' for variable 'data.aws_subnet.selected.*.ipv6_cidr_block'
```
### Steps to Reproduce
1. `terraform apply`

### Other
The ipv6_addresses syntax would be a lot better if the "cidrhost()" function had IPv6 support.

**Comment by stack72** [comment]
Hi @sandnabba 

I am adding the ability to get the IPv6 CIDR block from the data source as we speak

Paul
