### ISSUE TITLE
ALB's no longer allow you to define the priority

### ISSUE THREAD

**Issue by symonds** [hashicorp/terraform#13591]
Unable to define alb_listener_rule priorities in AWS.

### Terraform Version
v0.9.2

### Affected Resource(s)
alb_listener_rule

### Steps to Reproduce
1. set priority to any unused value except the next available
2. terraform apply
3. next available priority is used instead of set value

**Comment by stack72** [comment]
Hi @symonds 

Sorry for the issue you are facing here - hopefully it isn't causing too many pain points. I'd like to try and help fix this for you - please can you give me a little more detail about what you are facing? We, currently, have acceptance tests that show this works as expected so I am confused

Thanks

Paul

**Comment by symonds** [comment]
Hi @stack72 

I think this is related to the new ALBs (https://aws.amazon.com/about-aws/whats-new/2017/04/elastic-load-balancing-adds-support-for-host-based-routing-and-increased-rules-on-its-application-load-balancer/)

Example resource:
```
resource "aws_alb_listener_rule" "alb_rule_external" {
  depends_on   = ["aws_alb_target_group.alb_target_external"]
  count        = "1"
  listener_arn = "${var.alb_external}"
  priority     = "9"

  action {
    type             = "forward"
    target_group_arn = "${aws_alb_target_group.alb_target_external.id}"
  }

  condition {
    field  = "path-pattern"
    values = ["/${var.svc_code}/*"]
  }
}
```

This should put the resource the alb with a listener priority of 9, however, if there are currently no services with a priority > 4 it will be put in position 4 silently.

This was causing the issue where, because the creation order is random, resource would collide

```
17:24:27 * aws_alb_listener_rule.alb_rule_external: Error creating ALB Listener Rule: PriorityInUse: Priority '4' is currently in use
```
Even though no other resource was set to priority 4

I have worked round this issue by setting the priorities to >100

This does mean that every run terraform attempts to move the listener to the 100th position, but it silently fails so we have the following on every plan:

```
11:01:23 ~ module.svc_<snip>.aws_alb_listener_rule.alb_rule_internal
11:01:23     priority: "6" => "106"

11:01:23 Plan: 0 to add, 51 to change, 0 to destroy.
```

Which is it does every apply but does mean we can continue.

```
11:01:31 module.svc_<snip>.aws_alb_listener_rule.alb_rule_internal: Modifying... 
11:01:31   priority: "6" => "106"
```

**Comment by symonds** [comment]
In 0.9.4 the state file now records that the move has happened (even though it hasn't) and TF no longer attempts to change the priority on every run.

It might be worth dropping the priority option?
