### ISSUE TITLE
terraform apply errors not returning non-zero exit code

### ISSUE THREAD

**Issue by danmandle** [hashicorp/terraform#13598]
Found [this ticket](https://github.com/hashicorp/terraform/issues/11302), but it was closed. Opening a new one.

### Terraform Version
v0.9.2

### Affected Resource(s)
- aws_ecs_service.service

### Terraform Configuration Files
N/A

### Debug Output
https://gist.github.com/danmandle/c135f824c5829067952db29b7a44a62e

### Expected Behavior
When the error occurred, it should return a non-zero exit code

### Actual Behavior
It returned a `0` exit code

### Steps to Reproduce

    echo "Running Terraform..."
    terraform plan
    
    echo "Running Terraform apply..."
    terraform apply

### Important Factoids
This is being executed in a Jenkins Pipeline. When the error occurs, it returns a 0 exit code which allows the Jenkins Pipeline to proceed.

Also posted on StackExchange: http://devops.stackexchange.com/questions/871/terraform-apply-exit-code-on-error

### References
- [GH-11302](https://github.com/hashicorp/terraform/issues/11302)

**Comment by danmandle** [comment]
Turns out this was not a real issue. My apologies. At the end of that shell script, it did an echo which is what was returning the non-zero status code. After I took that out, it worked as expected.

**Comment by jayudhandha** [comment]
@danmandle I am facing the same issue. Can you please give me the brief about the solution.
I tried `echo` at the last line of my shell script, It gives me 0 when terraform fails or gives error.

**Comment by danmandle** [comment]
I removed the `echo`

**Comment by davidaparicio** [comment]
You need to use && in order to keep a exit code != 0
or a bash sequence like
``` terraform plan 
RETVAL=$?
[ ${RETVAL} -eq 0 ] && terraform apply || RETVAL=1
return ${RETVAL}
