### ISSUE TITLE
Cannot create ipv6 route to internet gateway in vpc

### ISSUE THREAD

**Issue by philipl** [hashicorp/terraform#13599]
For public subnets, ipv6 traffic should be routed through the same internet gateway as ipv4 traffic. (the ipv6 egress-only gateway is for private subnets). Terraform will fail to crate route entries for this scenario. They can be created fine using the console or aws api.

### Terraform Version
0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route

### Terraform Configuration Files
```hcl
resource "aws_route" "public_ipv6_igw_route" {                                                                                                                                                            
    route_table_id = "${aws_route_table.public_route_table.id}"
    destination_ipv6_cidr_block = "::/0"
    gateway_id = "${aws_internet_gateway.internet_gateway.id}"
}
```

### Debug Output
https://gist.github.com/philipl/cbe27b036dcb23a55e07096173851633

### Expected Behavior
Route table entry is created

### Actual Behavior
Creation fails with error

### Steps to Reproduce
1. `terraform apply`

**Comment by stack72** [comment]
Hi @philipl 

Apologies you are hitting this issue. For IPv6, you need to use a different type of Internet Gateway. The example on this [page](https://www.terraform.io/docs/providers/aws/r/route.html#example-ipv6-usage-) shows what is needed

Please let me know if this doesn't help

Thanks

Paul

**Comment by philipl** [comment]
Hi @stack72 

The AWS documentation is confusing, but the egress_only gateway should not be used for public subnets. It only replaces the NAT gateway for private subnets.

See: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Internet_Gateway.html

So you need to be able to route ipv6 to the regular igw.
