### ISSUE TITLE
Please provide version specific documentation at terraform.io/docs/

### ISSUE THREAD

**Issue by kkrusedp** [hashicorp/terraform#13609]
Hi there,

Please incorporate version specific documentation.   Follow the working examples of apache/php/puppet etc who release version specific documentation.   This would be more useful for legacy stuff and easing lesser experienced people to terraform.

**Comment by tombuildsstuff** [comment]
Hi @kkrusedp 

Thanks for opening this issue - totally agree this'd be a great feature.

Versioned Documentation has previously been requested in #12941. So that we don't have multiple issues open tracking the same request - I'm going to close this issue in favour of that one :)

Thanks!

**Comment by kkrusedp** [comment]
Yes thanks for pointing out. I tried to locate an existing issue here and could not so apologies for the dupe.
