### ISSUE TITLE
String interpolations when specifying required_version

### ISSUE THREAD

**Issue by ajlanghorn** [hashicorp/terraform#13603]
Hello,

I've just started working on a team with a repository which has a `.terraform-version` file in, which is consumed by [`tfenv`](https://github.com/kamatama41/tfenv). `tfenv` works in a very similar fashion to tools such as `rbenv`, in that it wraps installation and management of a particular version of Terraform.

I refactored a bit of our code base to make use of `required_version` in the `terraform` block, as per [the docs](https://www.terraform.io/docs/configuration/terraform.html), but wanted to read in the value from the `.terraform-version` file, which just contains the version:

```
$ cat .terraform-version
0.9.3
```

Unfortunately, it seems the `required_version` parameter doesn't accept string interpolations, so I can't read the version in using:

```
terraform {
   required_version = "${file(".terraform-version")}"
}
```

Is there a reason `required_version` doesn't accept string interpolations?

Cheers,

Andrew

**Comment by jbardin** [comment]
Hi @ajlanghorn,

This is working as intended or now. The terraform config is leaded very early on, before any interpolation is done. 

We can track the feature request with an existing issue at #13022

**Comment by mhowell-ims** [comment]
I'm trying to do the same thing, with the same result.
