### ISSUE TITLE
Feature request: support for Google IAM policies on PubSub topics

### ISSUE THREAD

**Issue by pdecat** [hashicorp/terraform#13602]
Hi, I would love to see the addition of a `google_pubsub_topic_iam_policy` resource to manage IAM policies on PubSub topics:

Following is an example of what this would look like setting an IAM policy on a pubsub topic:

```
resource "google_service_account" "publisher" {
  account_id   = "publisher"
  display_name = "Publisher"
}

resource "google_pubsub_topic" "default" {
  name = "default-topic"
}

data "google_iam_policy" "topic_publisher" {
  binding {
    role = "roles/pubsub.publisher"

    members = [
      "serviceAccount:${google_service_account.publisher.email}",
    ]
  }
}

# THE FOLLOWING RESOURCE DOES NOT EXIST YET!
resource "google_pubsub_topic_iam_policy" "default_topic_publisher" {
  target      = "${google_pubsub_topic.default.name}"
  policy_data = "${data.google_iam_policy.topic_publisher.policy_data}"
}
```

PS: If this feature request is accepted, should I open other issues for the other resources I am willing to see support? Or should this issue be renamed and updated to track everything in one place?

**Comment by evmin** [comment]
+1 Pubsub and Bigquery are probably the most needed resources. Cheers.
