### ISSUE TITLE
Bug Report: terraform plan for a specific resource failed, while terraform plan still works

### ISSUE THREAD

**Issue by moudixtc** [hashicorp/terraform#13601]
Hi there,

Basically I have two terraform configuration environments A and B. Config A generates the output, which is being used by a module. Config B uses the module, and I run into the following issue. The overall `terraform plan` works just fine and it gets the output successfully, but if I just want to do a plan for that output, it failed. 

### Terraform Version
v0.9.2

### Affected Resource(s)
- terraform_remote_state data source

### Terraform Configuration Files
Here is my terraform_remote_state data source.
```hcl
data "terraform_remote_state" "infrastructure" {
  backend = "s3"

  config {
    bucket = "some_bucket"
    key    = "some_key"
    region = "som_region"
  }
}
```

This is where the data source is being used
```hcl
resource "aws_iam_instance_profile" "management_instance" {
  name_prefix = "${var.name}-instance-profile-"
  roles       = [
    "${concat(list(data.terraform_remote_state.infrastructure.management_ec2_role_name), var.management_instance_additional_roles)}"]
}
```

Here is the output declaration in the data source
```hcl
output "management_ec2_role_name" {
  value = "${aws_iam_role.management_ec2.name}"
}
```

### Expected Behavior
When running `terraform plan`, it successfully get the data, as you can see in the following block **roles.650338719: "ManagementInstanceEC2-00ddab3f13543675cc2ec4f86c"**. Therefore, I think if I do a more specific plan, it should work too. 

```
$ terraform plan
+ module.vpc.aws_iam_instance_profile.management_instance
    arn:             "<computed>"
    create_date:     "<computed>"
    name:            "<computed>"
    name_prefix:     "some-name-prefix"
    path:            "/"
    roles.#:         "1"
    roles.650338719: "ManagementInstanceEC2-00ddab3f13543675cc2ec4f86c"
    unique_id:       "<computed>"

Other plan details omitted here
```

### Actual Behavior
However, when running the more specific plan command:
`terraform plan -target=module.vpc.aws_iam_instance_profile.management_instance`
I got the following error:
```
$ terraform plan -target=module.vpc.aws_iam_instance_profile.management_instance
Error running plan: 1 error(s) occurred:

* module.vpc.aws_iam_instance_profile.management_instance: 1 error(s) occurred:

* module.vpc.aws_iam_instance_profile.management_instance: Resource 'data.terraform_remote_state.infrastructure' does not have attribute 'management_ec2_role_name' for variable 'data.terraform_remote_state.infrastructure.management_ec2_role_name'
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform plan -target=<SPECIFIC_RESOURCE>`

**Comment by cyrilgdn** [comment]
I think it's the same that #13330 ?

**Comment by moudixtc** [comment]
Yeah it looks like the same issue
