### ISSUE TITLE
Documentation page of data source aws_iam_role

### ISSUE THREAD

**Issue by GuiSim** [hashicorp/terraform#13613]
There seems to be an issue with the documentation of this data_source. See this page: 
https://www.terraform.io/docs/providers/aws/d/iam_role.html

This error is displayed at the top of the page
> layout: "aws" page_title: AWS: aws_iam_role sidebar_current: docs-aws-datasource-iam-role description: |-

The sidebar is not available on this page.

Thanks!

**Comment by tombuildsstuff** [comment]
Hi @GuiSim 

Thanks for reporting this - I've opened #13613 which fixes this :)

Thanks!
