### ISSUE TITLE
Additional properties for google_storage_bucket_object

### ISSUE THREAD

**Issue by ksperling** [hashicorp/terraform#13616]
Hi,

it would be great to have support for
- cache_control
- content_disposition
- content_encoding
- content_language
- content_type
- storage_class

analogous to s3_bucket_object.

These look to be directly supported by the Cloud Storage JSON api: https://cloud.google.com/storage/docs/json_api/v1/objects/insert (for some reason contentType is not listed in that table, but it is shown as writable in https://cloud.google.com/storage/docs/json_api/v1/objects#resource)

### Terraform Version

0.9.3

### Affected Resource(s)
- google_storage_bucket_object

**Comment by AVVS** [comment]
Would be great to have this!
