### ISSUE TITLE
module.db.aws_db_subnet_group.db_subnet_group: "name": required field is not set

### ISSUE THREAD

**Issue by dgolja** [hashicorp/terraform#13619]
Hi there,

### Terraform Version
terraform -v
Terraform v0.9.2

### Affected Resource(s)
- aws_db_subnet_group

### Terraform Configuration Files
```hcl
resource "aws_db_subnet_group" "db_subnet_group" {
  name_prefix = "something"

  subnet_ids = ...
  tags {
     ...
  }
}
```

### Expected Behavior
When trying to run `terraform plan` I was expecting that the plan will show the aws_db_subnet_group creation, however I get a unexpected error.

### Actual Behavior
I get the following error:

```
* module.db.aws_db_subnet_group.db_subnet_group: "name": required field is not set
* module.db.aws_db_subnet_group.db_subnet_group: : invalid or unknown key: name_prefix
```

Based on the [documentation](https://www.terraform.io/docs/providers/aws/r/db_subnet_group.html) `name` and `name_prefix` are optional, however the error implies that `name` is required and `name_prefix` is invalid.

### Steps to Reproduce
1. `terraform plan`

**Comment by grubernaut** [comment]
Hi @dgolja, thanks for the issue! 

It looks like this was added in https://github.com/hashicorp/terraform/pull/13232, and was released in Terraform v0.9.3 on Wednesday. Updating to the new version of Terraform should solve this issue for you. Thanks!
