### ISSUE TITLE
Openstack provider should have a region argument

### ISSUE THREAD

**Issue by mcanevet** [hashicorp/terraform#13625]
Currently we have to either use the `OS_REGION_NAME` environment variable or pass `region` to every OpenStack resource.
It would be nive to have a `region` parameter to the `openstack` provider that defaults to `OS_REGION_NAME`.

**Comment by jtopjian** [comment]
@mcanevet Agreed. It can be cumbersome to tag each resource with a region. Internally, there's a good reason for doing it this way (the region is specified upon each client creation), but from a UX perspective, cumbersome.

Adding a `region` parameter to the provider could be used to globally set all resources of that provider with the specified region, but there's probably going to be some caveats by introducing a "global" setting:

1. The provider `region` won't use `OS_REGION_NAME` ever.
2. If the provider `region` was specified, each resource will use that setting and not `OS_REGION_NAME` if `OS_REGION_NAME` is set.
3. If the resource `region` was set in the Terraform config, it will override the provider.

Thoughts?

**Comment by mcanevet** [comment]
@jtopjian I think we could default to `OS_REGION_NAME`, imagine this manifest:

```terraform
# The default provider will use OS_REGION_NAME environment variable as region
provider "openstack" {
  user_name   = "admin"
  tenant_name = "admin"
  password    = "pwd"
  auth_url    = "http://myauthurl:5000/v2.0"
}

# The additional  provider will use "Honolulu" as region
provider "openstack" {
  user_name   = "admin"
  tenant_name = "admin"
  password    = "pwd"
  auth_url    = "http://myauthurl:5000/v2.0"
  alias       = "honolulu"
  region      = "Honolulu"
}

# This resource will use OS_REGION_NAME as region
resource "openstack_compute_instance_v2" "test-server" {
  # ...
}

# This resource will use "Honolulu" as region
resource "openstack_compute_instance_v2" "test-server_2" {
  provider = "openstack.honolulu"
  # ...
}

# This resource will use "Kahoolawe" as region
resource "openstack_compute_instance_v2" "test-server_3" {
  region = "Kahoolawe"
  # ...
}
```

or the other way around:

```terraform
# The default provider will use "Maui" as region
provider "openstack" {
  user_name   = "admin"
  tenant_name = "admin"
  password    = "pwd"
  auth_url    = "http://myauthurl:5000/v2.0"
  region      = "Maui"
}

# The additional provider will use OS_REGION_NAME environment variable as region
provider "openstack" {
  user_name   = "admin"
  tenant_name = "admin"
  password    = "pwd"
  auth_url    = "http://myauthurl:5000/v2.0"
  alias       = "honolulu"
}

# This resource will use "Maui" as region
resource "openstack_compute_instance_v2" "test-server" {
  # ...
}

# This resource will use OS_REGION_NAME environment variable as region
resource "openstack_compute_instance_v2" "test-server_2" {
  provider = "openstack.honolulu"
  # ...
}

# This resource will use "Kahoolawe" as region
resource "openstack_compute_instance_v2" "test-server_3" {
  region = "Kahoolawe"
  # ...
}
```

What do you think about that?

**Comment by jtopjian** [comment]
@mcanevet Yep, I totally get that it would work and your examples are clear and understandable. My concern is helping the user not get themselves tangled in a mix of explicit vs implicit settings.

The way I see it, having a single provider configuration use `OS_REGION_NAME` is no different than current behavior. The benefit of setting a provider-level region is to make it easy to use multiple providers in a single configuration without having to set `region` on each resource (I think you and I are on the same page about this already). So any failure scenario is going to be related to multi-region/cloud scenarios. 

Let's use the "other way around" example above. A user sets `OS_REGION_NAME` to `honolulu` and they successfully deploy to Maui, Honolulu, and Kahoolawe. Then the user begins doing some other work and sources an `openrc` file for Maui. Later, they want to deploy a new server to Honolulu, so they add it to the `main.tf` file and `apply`, but they forgot to change `OS_REGION_NAME` to `honolulu`. Not only would the new server be deployed to Maui, but all resources that use `OS_REGION_NAME` would be destroyed and recreated in Maui.

Now, this isn't new behavior. This can already happen when any change to `OS_REGION_NAME` is made. The difference is that we must now assume the user is working in multiple clouds.

So the debate for me is, would I rather have a user upset that:

* They must explicitly define "region" in a provider?
* They accidentally destroyed an entire region?

And I totally get that if the above scenario happened, the fault would be on the user. But could I have done something to help them better understand how to not get themselves in that situation?

**Comment by mcanevet** [comment]
@jtopjian don't we have the same problem with any other provider that defaults to environment variable? For example with the `aws` provider, one can use the `profile` parameter and the `AWS_*` environment variables.

**Comment by jtopjian** [comment]
Kind of. To me, the cause of concern is that all resources already support a `region` attribute. So a better comparison would be any provider attribute which each resource also shares.

Is there a use-case that you have in mind that would make this feature moot if it didn't support `OS_REGION_NAME`? 

To be clear, I fully support the idea of provider-level region. I always wondered why this wasn't supported from the beginning. And I'm not opposed to adding provider-level `OS_REGION_NAME` support in the future if feedback shows the safety is too restrictive. But I need to consider how this feature can best be safely introduced first.

**Comment by mcanevet** [comment]
We are not using environment variable as it may have some dangerous behavior if you don't set it properly (deploying stuffs in the wrong cloud). Instead, we store our credentials in [pass](https://www.passwordstore.org) using the [pass provider](https://github.com/hashicorp/terraform/pull/11381) and hardcode the credential path in our manifests:
```terraform
data "pass_password" "openstack" {
  path = "path/to/password"
}

provider "openstack" {
  auth_url    = "${data.pass_password.openstack.data["auth_url"]}"
  tenant_name = "${data.pass_password.openstack.data["tenant_name"]}"
  user_name   = "${data.pass_password.openstack.data["user_name"]}"
  password    = "${data.pass_password.openstack.data["password"]}"
}
```
With this setup there is no risk of not using the proper cloud, but as we don't use environment variable, `OS_REGION_NAME` is not set and thus we have to specify `region` for every resource, which is not very convenient.

**Comment by jtopjian** [comment]
Thanks for the notes! I will have some time in the coming days to work on this. :)

**Comment by jtopjian** [comment]
Just a quick update: My schedule got derailed and I haven't had time to work on this. I hope to get back to this soon, though.

**Comment by mcanevet** [comment]
@jtopjian any news about this issue?

**Comment by jtopjian** [comment]
@mcanevet Yes :)

Please see #14738. Would you be able to test this out and let me know your thoughts?
