### ISSUE TITLE
aws_cloudtrail always reports modification when using a kms alias

### ISSUE THREAD

**Issue by wr0ngway** [hashicorp/terraform#13632]
### Terraform Version

Terraform v0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudtrail

### Terraform Configuration Files
```hcl
resource "aws_kms_key" "logs" {
  description = "KMS Key used for log encryption"
  enable_key_rotation = true
}

resource "aws_kms_alias" "auditlog" {
    name = "alias/auditlog"
    target_key_id = "${aws_kms_key.logs.key_id}"
}

resource "aws_s3_bucket" "logs" {
  bucket = "mylogbucket"
  acl = "log-delivery-write"
}

resource "aws_cloudtrail" "auditlog" {
  name = "auditlog"
  s3_bucket_name = "${aws_s3_bucket.logs.bucket}"
  s3_key_prefix = "auditlog"
  include_global_service_events = true
  is_multi_region_trail = true
  enable_logging = true
  enable_log_file_validation = true
  kms_key_id = "${aws_kms_alias.auditlog.arn}"
}

```

### Expected Behavior

Plan should be clean without changes

### Actual Behavior

Plan always report a modification
```
~ aws_cloudtrail.auditlog
    kms_key_id: "arn:aws:kms:us-east-1:1234567890:key/www-xxx-yyy-zzz" => "arn:aws:kms:us-east-1:1234567890:alias/auditlog"

```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by bclodius** [comment]
@wr0ngway If you change ```kms_key_id = "${aws_kms_alias.auditlog.arn}"``` to ```kms_key_id = "${aws_kms_key.logs.arn}"``` would that fix the issue? I believe the input here needs  to always be a kms key arn which is different than the kms key alias arn.

**Comment by josh-padnick** [comment]
I'm experiencing the exact issue as described by @wr0ngway, and we have the following code as you suggest in your follow-up:

```hcl
 kms_key_id = "${aws_kms_key.cloudtrail.arn}"
```

I'm assuming this is a Terraform bug since I saw [similar issues](https://github.com/hashicorp/terraform/issues/9119) with other Terraform resources.

**Comment by bclodius** [comment]
@josh-padnick I cannot reproduce using Terraform 0.9.6.  What version are you using??

**Comment by josh-padnick** [comment]
@bclodius Sorry I didn't specify. I'm on 0.9.8. You should also note that I'm invoking this CloudTrail code through a Terraform Module. Finally, here's my Terraform code (without the accompanying resources created in the module):

```hcl
resource "aws_cloudtrail" "cloudtrail" {
  name = "${var.cloudtrail_trail_name}"
  s3_bucket_name = "${var.s3_bucket_name}"
  is_multi_region_trail = "${var.is_multi_region_trail}"
  include_global_service_events = true
  enable_logging = "${var.enable_cloudtrail}"
  enable_log_file_validation = true
  kms_key_id = "${aws_kms_key.cloudtrail.arn}"

  depends_on = ["aws_s3_bucket.cloudtrail_with_logs_archived", "aws_s3_bucket.cloudtrail_with_logs_not_archived"]
}
```
