### ISSUE TITLE
[regression] providers/aws: Setting MaxFrameRate on ElasticTranscoderPreset breaks fixed frame rate

### ISSUE THREAD

**Issue by svanzoest** [hashicorp/terraform#13638]
@catsby #13422  broke #9847 and undid #11340, I can no longer set a preset with a fixed frame rate in 0.9.3, this was the reason the default was removed in the first place.

I now get:
```
* aws_elastictranscoder_preset.proxy: Error creating Elastic Transcoder Preset: ValidationException: When you specify a value for MaxFrameRate, you must also specify 'FrameRate':'Auto'. Either change the value of FrameRate or remove the MaxFrameRate object, and resubmit the request.
    status code: 400, request id: 8cf3908f-207e-11e7-84a3-01d702018b22
```

**Comment by catsby** [comment]
Sorry for the trouble here @svanzoest ! I admit I'm not very familiar with Elastic Transcoder, and made a mistake here.

Hopefully I understand your situation correct; you're setting `frame_rate` to something that is _not_ `auto`, and you are omitting `max_frame_rate`, correct? 

Terraform clearly isn't handling reading the default MaxFrameRate correctly, thus our test `TestAccAWSElasticTranscoderPreset_basic` was failing. I suppose I'm confused on when to set `max_frame_rate`, it seems you can only set this property if `frame_rate` is `auto`? I didn't feel that the AWS docs said that explicitly, but I feel like that' what we're getting.

**Comment by svanzoest** [comment]
> Hopefully I understand your situation correct; you're setting frame_rate to something that is not auto, and you are omitting max_frame_rate, correct?
Correct. Just for reference I am setting the FrameRate to`29.97` forcing a consistent FrameRate among all transcodings done using this preset regardless of the FrameRate of the input. Since the FrameRate is not `auto`, you should not set MaxFrameRate at all. The default of 30 only applies when you set the FrameRate to `auto`, but do not specify a `MaxFrameRate`.

> So, MaxFrameRate only applies when you assume the frame rate from the media file, but want to make sure you do not have a high frame rate.

Exactly.

> Terraform clearly isn't handling reading the default MaxFrameRate correctly, thus our test TestAccAWSElasticTranscoderPreset_basic was failing. I suppose I'm confused on when to set max_frame_rate, it seems you can only set this property if frame_rate is auto? I didn't feel that the AWS docs said that explicitly, but I feel like that' what we're getting.

Yes, that is it and if you read the docs carefully, it states that as well. MaxFrameRate only applies to `auto` FrameRate.

> If you want to preserve the frame rate of the input file and use it for the output file, specify `auto`.
> If you specify `auto` for FrameRate, Elastic Transcoder uses the frame rate of the input video for the frame rate of the output video, up to the maximum frame rate. If you do not specify a MaxFrameRate, Elastic Transcoder will use a default of 30.
