### ISSUE TITLE
Terraform AWS Postgres RDS upgrade 

### ISSUE THREAD

**Issue by devtakh** [hashicorp/terraform#13640]
Hi,

I am trying to upgrade a postgres RDS from t2.micro to t2.medium in AWS. My terraform plan says that it will be upgraded. When applied, it says it is upgraded but it was never upgraded. 
I am using: Terraform v0.9.2
Below are the output snippets of plan and apply

terraform plan:
-----------------
Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ module.xxxxxxx
    instance_class: "db.t2.micro" => "db.t2.medium"

Terraform apply:
------------------
module.XXXXX: Modifying... (ID: mobileaaedge)
  instance_class: "db.t2.micro" => "db.t2.medium"
module.XXXXX: Still modifying... (ID: mobileaaedge, 10s elapsed)
module.XXXXX: Still modifying... (ID: mobileaaedge, 20s elapsed)
module.XXXXX: Still modifying... (ID: mobileaaedge, 30s elapsed)
module.XXXXX: Modifications complete (ID: mobileaaedge)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

terraform plan:
-----------------
Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ module.xxxxxxx
    instance_class: "db.t2.micro" => "db.t2.medium"

**Comment by stack72** [comment]
Hi @devtakh 

Sorry for the issue you are facing here - please can you tell me if you are setting the flat 

```
apply_immediately = true
```

as part of your terraform config? Without this flag, you are telling RDS to wait till the next maintenance window to perform the change. 

Paul

**Comment by devtakh** [comment]
Thank you Paul. That is it. I never realized that.

**Comment by stack72** [comment]
@devtakh no worries at all :)
