### ISSUE TITLE
Aliyun provider access_key/secret_key could not set in .tf file but could use by env export

### ISSUE THREAD

**Issue by regardfs** [hashicorp/terraform#13657]
Hi there

### Terraform Version
Terraform v0.9.3

### Affected Resource(s)
provider "alicloud" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}

### Terraform Configuration Files
```
provider "alicloud" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}
```

### Debug Output
Error running plan: 1 error(s) occurred:
provider.alicloud: Aliyun API Error: RequestId: BFF3D6EA-8191-4753-80EC-5A43CC6A2D4F Status Code: 404 Code: InvalidAccessKeyId.NotFound Message: Specified access key is not found.

terraform plan could pass when use access_key/secret_key set by env export :

> export ALICLOUD_ACCESS_KEY="blahblah"
export ALICLOUD_SECRET_KEY="blahblah"

but when config in main.tf, it report a error of Specified access key is not found.

**Comment by elaijuh** [comment]
not quite related, but found it interesting that if i define `access_key` and `secret_key` as empty string for aws provider, it works. but for alicloud, it fails wo `terraform plan`

**Comment by xiaozhu36** [comment]
Hello @regardfs 

Alicloud provider have token the test for access key before release, and we didn't found above case. 
According to your error requestId, I have queried the request log and the log shows the access key you sent is invaild and it doesn't exist in the alicloud access key system. So I think that you may specify an error access key in the main.tf, and I can give you the following suggestion:
1. please ensure you own the specified access key and it is valid;
2. if terraform plan could pass when use access_key/secret_key set by env export, please confirm env and main.tf have the same access key value.
3. if above suggestions are ok, please send me your main.tf to help me to locate the error reason as quickly as possible.

In addition, Alicloud provider has a separate open source repository: https://github.com/alibaba/terraform-provider , and if you have any question about alicloud provier, please put issues to it, and I will give you solution as soon as possible. Thanks.

Regards,
Guimin

**Comment by regardfs** [comment]
@xiaozhu36 ， thanks I just use this repo and works fine

**Comment by regardfs** [comment]
@elaijuh thanks all the same

**Comment by regardfs** [comment]
Final：Use this: `https://github.com/alibaba/terraform-provider`  to solve my problem
