### ISSUE TITLE
Can't update existing resources with new EBS block device settings

### ISSUE THREAD

**Issue by chrisferry** [hashicorp/terraform#1367]
When running a plan with new 0.4.0 I get the following output:
~ module.inf-consul.aws_launch_configuration.launch_config
    ebs_optimized:            "" => "0"
    ephemeral_block_device.#: "" => "<computed>"
    root_block_device.#:      "" => "<computed>"

I'm not specifying a block device in the launch_config.

When I try to apply I receive:
* 1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* doesn't support update

**Comment by jwaldrip** [comment]
Can you post your configuration for that resource.

**Comment by phinze** [comment]
Looking into this now. Will try to repro from here, but a config would definitely be helpful!

**Comment by chrisferry** [comment]
Config here: https://gist.github.com/chrisferry/f74d57c091f712afef36

**Comment by phinze** [comment]
Reproduced locally with a pretty minimal config.

```js
resource "aws_launch_configuration" "bar" {
   name = "dontupdatemebro"
   image_id = "ami-21f78e11"
   instance_type = "t1.micro"
   user_data = "foobar-user-data-change"
}
```

Digging in for root issue now.

**Comment by chrisferry** [comment]
@phinze This fixes the issue.  Thx
