### ISSUE TITLE
Custom Terraform name as environment variable

### ISSUE THREAD

**Issue by mytototo** [hashicorp/terraform#13683]
Hi,

I'm currently working on a simple wrapper for Terraform CLI. The goal is to simplify some processes and workflows for a few use cases (locks, states, etc). 

Basically if I want to override or customize the Terraform CLI I need to fork it. Even just if I need to rename Terraform with the name of the command-line wrapper for a better understanding for end-users. 

My suggestion (which can work for the other products of the HashiCorp ecosystem) is to set the module name (e.g. `Terraform`) and slug (e.g. `terraform`) as environment variables. This way, the wrapper do not need to override the built-in Terraform CLI just for wording. This allows a better workflow for custom tools built on top of Terraform. 

What do you think?

**Comment by grubernaut** [comment]
Hi @mytototo, thanks for the issue! 

Currently at this time, we have no plans to expose the module name and/or slug as environment variables. I believe this can fully be done via environment variables inside the wrapper for the Terraform CLI, however. Being as such, I don't believe we will be implementing this feature in the future, and currently don't have any plans to do so. Happy to discuss this further, if need be! Thanks!
