### ISSUE TITLE
minor documentation update on api_gateway_usage_plan

### ISSUE THREAD

**Issue by sebosp** [hashicorp/terraform#13692]
The following file terraform/website/source/docs/providers/aws/r/api_gateway_usage_plan.html.markdown

Has title:
```markdown
# aws\_api\_usage\_plan
```
The correct title should be:
```markdown
# aws\_gateway\_api\_usage\_plan
```

**Comment by sebosp** [comment]
The same applies to terraform/website/source/docs/providers/aws/r/api_gateway_usage_plan_key.html.markdown 
it is also missing the "_gateway" in the title.

**Comment by stack72** [comment]
Hi @sebosp 

Thanks for noticing the issue - I have just opened a PR to fix this and will push it to the site asap

Paul
