### ISSUE TITLE
Custom ICMP Codes and Types within Security Groups

### ISSUE THREAD

**Issue by rhiann0n** [hashicorp/terraform#1372]
Please add custom ICMP types and codes to security group options.

Example
Ingress ICMP traceroute from 0.0.0.0/0
Ingress ICMP echorequest from 0.0.0.0/0
Ingress ICMP echo-reply from 0.0.0.0/0
Ingress ICMP Destination Unreachable from 0.0.0.0/0
Ingress ICMP Time Exceeded from 0.0.0.0/0
Ingress ICMP Parameter Problem: Bad header from 0.0.0.0/0

I saw what looked like the scaffolding for the logic of icmp_code and icmp_types in the source code but I'm not sure that its been implemented yet.

It is allowable through AWS CLI.

Also, here is a good reference:
http://www.nthelp.com/icmp.html

Please and thank you.

**Comment by dmangot** [comment]
This is necessary for Path MTU discovery in Security Groups.   
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html

**Comment by phinze** [comment]
Hey folks, ICMP type number goes in `from_port` according to the AWS docs.

Just tested and this works AOK:

```tf
resource "aws_security_group" "foo" {
  ingress {
    protocol  = "icmp"
    from_port = 30     # traceroute
    to_port   = 0
  }
}
```

Pushing a docs update momentarily to clarify this. :+1:

**Comment by rhiann0n** [comment]
Yay!  Thank you!
