### ISSUE TITLE
Feature Request: Capability to attach multiple instances to aws_elb_attachment

### ISSUE THREAD

**Issue by universalvishwa** [hashicorp/terraform#13721]
Hi,

It would be great if you can add the capability to attach multiple instances for aws_elb_attachment resource.
https://www.terraform.io/docs/providers/aws/r/elb_attachment.html

Currently, I have to manually duplicate the code snippet for each instance attachment because I have no way of using a loop. It's a very simple request.

Hope to see it available in future updates.

Thank you,
Vishwa

**Comment by grubernaut** [comment]
Hi @universalvishwa, thanks for the issue!

As a quick question before we start looking into adding this enhancement, can you use `count` inside of the `elb_attachment` resource? I was able to get a fully working example, as shown below: 

```
# main.tf
provider "aws" {
  region = "us-west-2"
}

resource "aws_elb" "foo" {
  availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]

  listener {
    instance_port     = 8000
    instance_protocol = "http"
    lb_port           = 80
    lb_protocol       = "http"
  }
}

resource "aws_instance" "foo" {
  ami           = "ami-043a5034"
  instance_type = "t1.micro"
  tags {
    Name = "jake-testing"
  }
}

resource "aws_instance" "bar" {
  ami           = "ami-043a5034"
  instance_type = "t1.micro"
  tags {
    Name = "jake-testing"
  }
}

module "attachment" {
  source = "./attach"
  attachment_count = 2
  instance_ids = ["${aws_instance.foo.id}", "${aws_instance.bar.id}"]
  elb_id = "${aws_elb.foo.id}"
}
```

```
# attach/vars.tf
variable "instance_ids" {
  type = "list"
}

variable "attachment_count" { }

variable "elb_id" { }
```

```
# attach/main.tf
resource "aws_elb_attachment" "foo" {
  count = "${var.attachment_count}"
  elb = "${var.elb_id}"
  instance = "${var.instance_ids[count.index]}"
}
```

Would this potentially solve the issue you're having? Thanks!

**Comment by universalvishwa** [comment]
Hi,

I'm trying to use it after creating two aws_instance resources. I'm on terraform 0.8.7 though. Can that be the issue?

The below code snippet doesn't work...
```
resource "aws_elb_attachment" "foo" {
	count = 2 
	elb      = "${var.foo_elb}"
	instance = "${aws_instance.foo_server.[count.index].id}"
}
```

Thank you
Vishwa

**Comment by grubernaut** [comment]
Hi @universalvishwa, 

The variable that you index via `count` needs to be a list variable. Notice how in the example above, the variable `instance_ids` is a list:
```
variable "instance_ids" {
  type = "list"
}
```
And we populate that variable by creating a list here: 
```
  instance_ids = ["${aws_instance.foo.id}", "${aws_instance.bar.id}"]
```

You can also create a list without a module by using the `list` interpolation function like so:
```
instance_ids = "${list("${aws_instance.foo.id}", "${aws_instance.bar.id}")}"
```
You could also index the provided list via `count` all in a single Terraform file, but I'd strongly recommend using the `module` route.
```
resource "aws_instance" "foo" {
  ami           = "ami-043a5034"
  instance_type = "t1.micro"
  tags {
    Name = "jake-testing"
  }
}

resource "aws_instance" "bar" {
  ami           = "ami-043a5034"
  instance_type = "t1.micro"
  tags {
    Name = "jake-testing"
  }
}

resource "aws_elb_attachment" "foo" {
  count = 2
  elb = "${aws_elb.foo.id}"
  instance = "${element(list("${aws_instance.foo.id}", "${aws_instance.bar.id}"), count.index)}"
}
```

**Comment by universalvishwa** [comment]
I'm trying to use the aws_instance resource like this.... For some resources terraform support that structure in my experience. (e.g. in VPC subnets)

```
resource "aws_instance" "foo" {
	count = 2
	ami           = "ami-043a5034"
	instance_type = "t1.micro"
}

resource "aws_elb_attachment" "foo" {
	count = 2 
	elb      = "${var.foo_elb}"
	instance = ["${aws_instance.foo.*.id}"]
}

```
The idea is to use the outcome of a resource like this to be attached to the load balancer.

Your suggesstion is acceptable for as a work around.
What if I have to attache 20 instances? Then, the line
`instance = "${element(list("${aws_instance.foo.id}", "${aws_instance.bar.id}"), count.index)}"`
will be very long and certainly inefficient....

My intention was not to report as a issue. I was just giving feedback so that you terraform can improve. :-)

Thank you
Vishwa

**Comment by saurabh-hirani** [comment]
@universalvishwa your problem statement is that you want to attach unique instances - if your terraform resource creation for each instance is foo, bar, etc - you are treating your infra as pets (as opposed to cattle (see http://cloudscaling.com/blog/cloud-computing/the-history-of-pets-vs-cattle/) and this is going to happen. If your instances can be autoscaled - then you could probably do this - https://github.com/hashicorp/terraform/tree/master/examples/aws-asg But I understand that for certain cases - one cannot get around the problem. I have myself got into such situations. 

But I felt that @grubernaut went above and beyond to help you. Your statement of - "I was just giving feedback so that you terraform can improve" was in poor taste. There is no "you terraform" -  terraform is an open source project and the community is doing an awesome job of adding features, solving problems and answering questions.

**Comment by xird** [comment]
I had the same exact problem while migrating a legacy system (yes, consisting of pets) to Terraform. This was the first search hit that I found, but the actual answer to the question is still missing... So, here goes:

```
resource "aws_instance" "foo" {
	count = 2
	ami           = "ami-043a5034"
	instance_type = "t1.micro"
}

resource "aws_elb_attachment" "foo" {
	count = 2 
	elb      = "${var.foo_elb}"
	instance = "${element(aws_instance.foo.*, count.index)}"
}
```
