### ISSUE TITLE
Produce plan in file in JSON or some other easily parsable format

### ISSUE THREAD

**Issue by timurb** [hashicorp/terraform#13738]
It would be nice to have Terraform outputting the plan not only as Golang marshal structure but in a way that could be easily parsed in other languages -- like JSON. Reading back this plan is not needed for me although someone might want that too.

The idea is to use this machine-readable plan for something like writing unit-like tests. At the moment I had to compose a library to parse the STDOUT output of `terraform plan` but I don't trust it the same way I'd trust plain JSON produced by Terraform.

A similar output produced by `terraform apply` or `terraform show` might also be helpful but for sure not as much as this one -- I can use `terraform output` instead.

**Comment by walterdolce** [comment]
+1 to this. Though I think an equivalent tool as `chefspec` is for Chef should exist for Terraform really as this is something which is directly tied to the tool (and the language is built upon).

**Comment by apparentlymart** [comment]
Hi @timurb! Thanks for this suggestion.

Having the plan output be readable by external software is a request that comes up from time to time, and in the long run we would love to make this possible. However, right now Terraform's changing quite frequently and the plan is a central component of Terraform's architecture that tends to need to change often as we change the internal architecture, and so we're not ready to commit to a stable JSON format for plans.

Therefore we've decided to postpone adding more JSON output until Terraform's internal architecture is stabilized (as we get closer to 1.0) and we can more confidently commit to a JSON structure that won't need to be broken by future releases.

For now "parsing" the human-oriented output as you are already doing is a reasonable workaround, but of course the UI output is not considered a compatibility constraint so you should expect your code to need to evolve for future Terraform releases. (This would, for now, be true of any JSON plan output too.)

I'm going to close this for now, but we will revisit this issue further down the road. Thanks again for this request!

**Comment by pvcon13** [comment]
Changing the parsing is no problem, but using JSON would make it much easier. In the case of a restful endpoint in front of Terraform (which I am doing), I would not have to parse at all, just return whatever JSON payload you return from plan, apply, show, etc. Right nbow I have to parse to create that JSON restful return payload.

**Comment by eswdd** [comment]
I believe this is now possible using a combination of ```terraform plan -out <plan-output-file>``` and ```terraform show -json <plan-output-file>```
