### ISSUE TITLE
[OpenStack] Problem with networking service: No suitable endpoint could be found in the service catalog.

### ISSUE THREAD

**Issue by allomov** [hashicorp/terraform#1374]
Hey, all.

Trying out new OpenStack provider I met the following error. When I try run `terraform apply` command I get following error output:
```
→ terraform apply -var-file terraform.tfvars
openstack_networking_network_v2.private-network: Creating...
  name:   "" => "private-network"
  region: "" => "RegionOne"
openstack_networking_network_v2.private-network: Error: 1 error(s) occurred:

* Error creating OpenStack networking client: No suitable endpoint could be found in the service catalog.
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error creating OpenStack networking client: No suitable endpoint could be found in the service catalog.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
Here is description of OpenStack configuration:
```
keystone 0.10.1
glance 0.14.0
nova 2.19.0
neutron 2.3.8
cinder 1.1.0
swift 2.3.0
```
I tried to set `auth_url` equaled to `OS_AUTH_URL` variable from [this doc](http://docs.openstack.org/juno/install-guide/install/apt/content/keystone-client-environment-scripts.html). I tested it with admin user with the same results.

**Comment by jtopjian** [comment]
Is it possible for you to share sanitized versions of the tf file you're using as well as the output of the command:

keystone catalog

**Comment by allomov** [comment]
@jtopjian thank you for answer. This was my fault. I put wrong region: `RegionOne` instead of `regionOne`. 

Hope error messages will be more informative in future :)
