### ISSUE TITLE
Add support for session_persistence in openstack_lb_pool_v1

### ISSUE THREAD

**Issue by gionn** [hashicorp/terraform#13741]
Add support for `session_persistence` field (e.g.: `SOURCE_IP`) in resource `openstack_lb_pool_v1`

https://wiki.openstack.org/wiki/Neutron/LBaaS/API

**Comment by jtopjian** [comment]
@gionn Are you sure LBaaS v1 pools support `session_persistence`? The docs you link to only show it for vips. In addition, I'm unable to see a `session_persistence` in the http requests.

I might be wrong about this, though.

**Comment by gionn** [comment]
I am not an openstack API expert, but I was looking for the `lb_method` attribute that I set in `openstack_lb_pool_v1` resource, and then looking a way to pass the `session_persistence` field of API.

Looking at the docs `openstack_lb_vip_v1`, only now I noticed the `persistence` block, that is probably what I was looking for, will try adding it.

The openstack GUI was a little misleding, it shows an unique drop-down for choosing among ROUND_ROBIN, LEAST_CONNECTIONS and SOURCE_IP.

Thanks!

**Comment by jtopjian** [comment]
> Looking at the docs openstack_lb_vip_v1, only now I noticed the persistence block, that is probably what I was looking for, I will try adding it.

Yep, I think that's what you're looking for.

I'm going to close this issue, but if it turns out it's not what you were looking for or have any other questions, let me know :)
