### ISSUE TITLE
terraoform doesn't resolve private ip within VPN

### ISSUE THREAD

**Issue by sarojabnet** [hashicorp/terraform#13740]
Hi when I'm trying to spin up private ip only instances within our vgw, cgw, vpn configuration on AWS, after spinning up instance terraform can't ssh right away, so I need to break that operation and when I try to do ssh using private ip I can.  Not sure why terraform can't resolve the private ip before finishing creating the resource.

But when I tried to use public ip, it works,that may be because public dns is in aws i guess.

 if anyone has similar issues, if you could shed some light that would be great.

Thanks

**Comment by sarojabnet** [comment]
I have increased the trace to get more error log output, 

2017/04/18 14:41:06 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2017/04/18 14:41:06 connection error: dial tcp xx.xxxx.xx: i/o timeout
2017/04/18 14:41:06 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2017/04/18 14:41:06 Retryable error: dial tcp xx.xx.xx.xx:22: i/o timeout
2017/04/18 14:41:06 [DEBUG] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "aws_instance.mysql-cluster-inst3"
2017/04/18 14:41:10 [DEBUG] root: eval: *terraform.EvalIf
2017/04/18 14:41:10 [DEBUG] root: eval: *terraform.EvalWriteState
2017/04/18 14:41:10 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/04/18 14:41:10 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/04/18 14:41:10 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* timeout
2017/04/18 14:41:10 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

**Comment by mengesb** [comment]
All of my connections for my infra stuff use private_ip connectivity; are you sure you're not blocked by routing or access lists? If not that, perhaps SSH agent or password-enabled keys?

```hcl
  connection {
    host        = "${self.private_ip}"
    user        = "${var.instance_defs["user"]}"
    private_key = "${file("${var.instance["key_path"]}")}"
  }
```

**Comment by sarojabnet** [comment]
Yes I did use this in my connection block but the problem here is it does create instance but terraform never be able to do ssh into private ip right away after the instance is created.
But it works fine if I use public ip, 
wondering if this has to do with our bastion/jumpbox configuration.

**Comment by mengesb** [comment]
If you have a bastion host, then you need to use those structures provided... https://www.terraform.io/docs/provisioners/connection.html

I'd ensure that you have proper access to/from/through your bastion, as you indeed state that you do. You don't have a trace here; however I've setup bastion host connectivity in the same manner above without issue.

```hcl
  connection {
    bastion_host = "${aws_route53_record.chef-server-ext.fqdn}"
    host         = "${self.private_ip}"
    user         = "${var.instance_defs["user"]}"
    private_key  = "${file("${var.instance["key_path"]}")}"
    timeout      = "2m"
  }
```

In the above case, I rely on the ssh agent to transit me through my bastion host

**Comment by sarojabnet** [comment]
Thanks let me try that.
