### ISSUE TITLE
Issue: AWS aurora cluster keeps recreating in every terraform run

### ISSUE THREAD

**Issue by universalvishwa** [hashicorp/terraform#13751]
Hi there,

I have a aurora cluster deployment. Whenever I do terraform plan/apply even without any modifications to my .tf files, terraform attempts to recreate. The affected parameter is 'password'.

I'm using terraform 0.8.7.

The code snippet is as follows. 
```
resource "aws_rds_cluster" "foo-aurora-cluster" {
    cluster_identifier      = "foo-cluster"
    database_name           = "foo-db"
    master_username         = "admin"
    master_password         = "Admin@123"

    db_subnet_group_name    = "${aws_db_subnet_group.foo.name}"
    vpc_security_group_ids  = ["${var.foo_sg}"]
    availability_zones      = ["${var.availability_zones}"]

    tags = {
        Name        = "foo-DBCluster"
    }    
}

resource "aws_rds_cluster_instance" "foo-aurora-instances" {
    count                   = 2

    identifier              = "db-${count.index}"
    cluster_identifier      = "foo-id"
    instance_class          = "t2.db.small"
    db_subnet_group_name    = "${aws_db_subnet_group.foo.name}"

    tags = {
        Name        = "foo-DB-${count.index}"
    }    
}
```
Thank you,
Vishwa

**Comment by stack72** [comment]
Hi @universalvishwa 

Thanks for raising an issue with us. Please can you post the output of the terraform plan so we can try and identify what error you are seeing?

Thanks

Paul

**Comment by apparentlymart** [comment]
Hi @universalvishwa,

Unfortunately without some example plan output it's hard for us to guess what might be going on here.

I'm going to close this now, but if you are able to share some plan output illustrating the problem please let us know, and I'll be happy to reopen this to dig in some more.

Thanks!
