### ISSUE TITLE
terraform crash in destroy

### ISSUE THREAD

**Issue by mengesb** [hashicorp/terraform#13753]
### Terraform Version
0.9.3

### Affected Resource(s)
- core

### Terraform Configuration Files
plan is extremely large and sensitive.. hard to sanitize

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x15b1586]

goroutine 14489 [running]:
github.com/hashicorp/terraform/terraform.(*State).sort(0x0)
	/private/tmp/terraform-20170412-58701-xi9h2i/terraform-0.9.3/src/github.com/hashicorp/terraform/terraform/state.go:745 +0x26
github.com/hashicorp/terraform/terraform.WriteState(0x0, 0x833f700, 0xc4201d24d0, 0x1038a75, 0xc42224dcf0)
	/private/tmp/terraform-20170412-58701-xi9h2i/terraform-0.9.3/src/github.com/hashicorp/terraform/terraform/state.go:2024 +0x40
github.com/hashicorp/terraform/state/remote.(*State).PersistState(0xc420fc7960, 0x0, 0x0)
	/private/tmp/terraform-20170412-58701-xi9h2i/terraform-0.9.3/src/github.com/hashicorp/terraform/state/remote/state.go:58 +0x79
github.com/hashicorp/terraform/backend/local.(*Local).opApply(0xc420fe8be0, 0x83651c0, 0xc4213ca040, 0xc4205d8a50, 0xc420f22300)
	/private/tmp/terraform-20170412-58701-xi9h2i/terraform-0.9.3/src/github.com/hashicorp/terraform/backend/local/backend_apply.go:141 +0x5eb
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opApply)-fm(0x83651c0, 0xc4213ca040, 0xc4205d8a50, 0xc420f22300)
	/private/tmp/terraform-20170412-58701-xi9h2i/terraform-0.9.3/src/github.com/hashicorp/terraform/backend/local/backend.go:226 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc420fe8be0, 0xc421476870, 0xc421476860, 0x83651c0, 0xc4213ca040, 0xc4205d8a50, 0xc420f22300)
	/private/tmp/terraform-20170412-58701-xi9h2i/terraform-0.9.3/src/github.com/hashicorp/terraform/backend/local/backend.go:246 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/private/tmp/terraform-20170412-58701-xi9h2i/terraform-0.9.3/src/github.com/hashicorp/terraform/backend/local/backend.go:247 +0x192
```

### Debug Output
N/A

### Panic Output
10M file difficult to share and contains sensitive information. limited sharing would be preferred to debug if there's not something immediately above that can be spotted.

### Expected Behavior
destroyed resources

### Actual Behavior
crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy -var-file=kesha.tfvars`

### Important Factoids
Very large and complex plan with a lot of resource relationships

### References

**Comment by mengesb** [comment]
I think I found the source in my configuration. I had a lot of `null_resource` items with triggers and destroy provisioners. I'm thinking that the graph had a hard time computing the relationships there. If that wasn't enough, I had `remote-exec` provisioners in there, so if the mix of triggers + remote-exec + destroy provisioners = bad panic, then perhaps there's some debugging I can provide on a limited basis. Unfortunately the plan cannot be shared directly on github.com though

**Comment by jbardin** [comment]
@mengesb,

Thanks for filing the issue. This particular crash has been fixed in master, but that doesn't necessarily mean that there isn't still a problem. IIRC the only place this could have crashed is while building the graph, which probably means a dependency cycle somewhere during destroy. 

I'll close this since the crash isn't useful, but feel free to open file a new issue if you can determine what the underlying error was.
