### ISSUE TITLE
Undefined AWSClient when try to create basic plugin for builtin AWS provider

### ISSUE THREAD

**Issue by ranga543** [hashicorp/terraform#13762]
Also tried importing "github.com/hashicorp/terraform/builtin/providers/aws" but it's giving some other issues realted to Request Inputs.
```go
package aws

import (
	"log"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/hashicorp/terraform/helper/schema"
)

func dataSourceAwsS3Bucket() *schema.Resource {
	return &schema.Resource{
		Read: dataSourceAwsS3BucketRead,

		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
			},
			"exist": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
}

func dataSourceAwsS3BucketRead(d *schema.ResourceData, meta interface{}) error {
	conn := meta.(*AWSClient).S3()

	log.Printf("[DEBUG] Reading S3 Buckets.")
	d.SetId(time.Now().UTC().String())

	request := &s3.HeadBucketInput{}
	request.Bucket = aws.String(d.Get("name").(string))

	log.Printf("[DEBUG] S3 Bucket request options: %#v", *request)

	resp, err := conn.HeadBucket(request)
	if err != nil {
		d.Set("exist", "0")
	}

	d.Set("exist", "1")

	return nil
}
```

**Comment by catsby** [comment]
Hey @ranga543 – can you detail what you're trying to build here? I'm not sure what you mean by "create basic plugin", from the source you've shown it looks like you're building a new Data Source for AWS S3 Buckets. 

If that were the case, instead of `conn := meta.(*AWSClient).S3()` you would want `conn := meta.(*AWSClient).s3conn`. 

If you can expand on what you're trying to build here, we'll try to help/explain best we can 😄

**Comment by ranga543** [comment]
Yes, I'm trying to create data source plugin outside of terraform.
my gopath would be $GOPATH\github.com\ranga543\terraform-aws-s3-bucket

**Comment by catsby** [comment]
Thanks for clarifying! Unfortunately writing custom Resources or DataSource isn't directly supported at this time. I can't say we have any plans to allow it in the future, that I'm aware of. Terraform does support building your own entire Provider as a separate plugin, from another `$GOPATH`, but not an individual resource of an existing Provider. 

The process for creating a new data source or resource for an existing Provider would be like so:
- clone the HashiCorp Terraform git repository (typically to your go path: `$GOPATH\github.com\hashicorp\terraform`)
- create the data source file (`$GOPATH\github.com\hashicorp\terraform\builtin\providers\aws\data_source_aws_s3_bucket.go`)
- Add this new data source to the `DataSourcesMap` in [builtin\providers\aws\provider.go](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/provider.go#L161)
- develop your data source as you've done above

Once that's done and working, if you'd like, you can fork the repository here on GitHub, and send a pull request for review!

If you'd rather not contribute it back that's fine as well, so long as it complies with the license ([Mozilla Public License 2.0](https://github.com/hashicorp/terraform/blob/master/LICENSE)) however from there you'll need to compile the AWS Provider binary yourself. You can do this by running the following command from the root of the Terraform project:

    $ make plugin-dev PLUGIN=provider-aws

This will compile the AWS Provider, including your new data source, and install the resulting binary in your `$GOPATH\bin`.
