### ISSUE TITLE
Importing routes & ACL rules

### ISSUE THREAD

**Issue by AMMullan** [hashicorp/terraform#13779]
I'm trying to import existing infrastructure but am not sure how to import ACL Rules and Routes for AWS.

### Terraform Version
v0.8.8

### Affected Resource(s)
- aws_route
- aws_network_acl_rule

Would just like to know if you can import these or you just have to apply and force it to overwrite the existing items?

**Comment by grubernaut** [comment]
Hi @AMMullan,

We currently do not support importing these two resources. Is it okay to treat this as a feature request for these resources? Thanks!

**Comment by AMMullan** [comment]
Hi @grubernaut,

Yep, that'd be great. Not 100% sure if/how this is going to be achievable but if you guys can do it it'd be amazing.

**Comment by flickerfly** [comment]
This would be great to get out of situations like this bug where terraform doesn't get that it succeeded and then can't try again because the route already exists. It becomes a looping problem. 

https://github.com/terraform-providers/terraform-provider-aws/issues/338
