### ISSUE TITLE
intermittent s3 state send failure: tls: oversized record received

### ISSUE THREAD

**Issue by mildwonkey** [hashicorp/terraform#13780]
### Overview
This is either a bug report or a feature request. I have yet to reproduce the state send failure, but - given that I have seen at least one other issue around state send failures, and I was unable to save the 'lost' state - some kind of retry or local cache may be helpful. 
If this is possible and I just missed it I will gleefully accept an RTFM.

### Terraform Version
0.9.3

### Affected Resource(s)
remote state backend - s3

### Terraform Configuration Files
```hcl
terraform {
  required_version = "0.9.3"

  backend "s3" {
    bucket     = "redacted"
    region     = "us-west-2"
    encrypt    = "true"
    lock_table = "redacted"
  }
}
```
The s3 key is provided as part of the init command: `terraform init -backend-config "key=foobar/terraform.tfstate"`

### Output
```
Releasing state lock. This may take a few moments...
Failed to save state: Failed to upload state: RequestError: send request failed
caused by: Put https://redacted.s3-us-west-2.amazonaws.com/foobar/terraform.tfstate: tls: oversized record received with length 20037
```

### Expected Behavior
Terraform state pushes to the remote backend OR provides a path for retries on failure.

### Actual Behavior
State was not saved and the changes being pushed (one vm and volume created) were lost. (I believe `terraform import` would have been the workaround?) 

### Steps to Reproduce
This is the first time I saw this issue, a subsequent apply/state upload worked as expected. This is possibly 95% a feature request for retries/caching state.

### References
- GH-10779 for reference

**Comment by jbardin** [comment]
Hi @mildwonkey,

Thanks for opening the issue! It think this should be addressed as a bug, since terraform should have recorded the state in a backup file.

**Comment by mildwonkey** [comment]
Thanks! Though until I/someone can reproduce the error I would fully believe that that backup state *was* available and we just didn't find it or understand how to restore (all I know for sure is that nothing new was in .terraform/). 
If there's documentation on this, I'd be grateful for the link. I didn't find anything but that doesn't mean it isn't there.
