### ISSUE TITLE
Allow specifying an execute command for remote-exec provisioner

### ISSUE THREAD

**Issue by nickelser** [hashicorp/terraform#138]
It would be really helpful if one could specify the command that actually calls the shell scripts for the remote-exec provisioner, much like http://www.packer.io/docs/provisioners/shell.html.

As a small side enhancement, it would be extremely helpful for debugging if stdout/err was output to the user for debugging when provisioning.

**Comment by phinze** [comment]
With #2097 we added support for arbitrary shebang lines. :+1:
