### ISSUE TITLE
Enhancement Request: Support Active Tracing (X-Ray) for AWS Lambda

### ISSUE THREAD

**Issue by davidski** [hashicorp/terraform#13801]
### Terraform Version
Terraform 0.9.3

### Affected Resource(s)
- aws_lambda_function

### Important Factoids
AWS just released active tracing (X-Ray integration) for Lambda functions. This is implemented via a `TracingConfig` stanza on the `CreateFunction` and `UpdateFunction` API calls. Documentation on the data structure is located at http://docs.aws.amazon.com/lambda/latest/dg/API_TracingConfig.html with details on the general integration at http://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html.

Thanks!

**Comment by stack72** [comment]
Hi @davidski,

Just to let you know, this is still not available in the AWS Go SDK so we are going to struggle adding this until it appears there

Paul

**Comment by justinsoliz** [comment]
@stack72 
I noticed that this was available in the nodejs sdk. I'm not familiar with the GO sdk but this seems like it might be available. 

http://docs.aws.amazon.com/sdk-for-go/api/service/lambda/#CreateFunctionInput
https://github.com/aws/aws-sdk-go/blob/master/service/lambda/api.go#L3434-L3525

**Comment by stack72** [comment]
@justinsoliz on it ;)

**Comment by jonnyshaw89** [comment]
Any update on this feature?

**Comment by marksailes** [comment]
Also really interested in this feature.

**Comment by thomascollett** [comment]
+1
We are deploying lambdas with Terraform and enabling x-ray manually at the moment. Would be great to have support for it.
