### ISSUE TITLE
Unable to destroy logentries_logset and logentries_log that have already been deleted

### ISSUE THREAD

**Issue by fillup** [hashicorp/terraform#13805]
### Terraform Version
v0.9.3

### Affected Resource(s)
- logentries_logset
- logentries_log

### Terraform Configuration Files
```hcl
variable "logentries_account_key" {}

provider "logentries" {
  account_key = "${var.logentries_account_key}"
}

resource "logentries_logset" "logset" {
  name = "testing-terraform-destroy"
}

resource "logentries_log" "log" {
  logset_id = "${logentries_logset.logset.id}"
  name = "test-log"
  source = "token"
}
```

### Debug Output
https://gist.github.com/fillup/f57874134bd4031790200e2edcbb2c5f

### Expected Behavior
Terraform should determine resource is already in desired state (destroyed) and complete destroy successfully. 

### Actual Behavior
Destroy fails with error that resource cannot be found. 

### Steps to Reproduce
1. `terraform apply`
2. Log into logentries and delete either the log or logset that was just created
3. `terraform destroy` - Watch for failure

### Important Factoids
I discovered this problem because a destroy on a larger set of resources failed part way through, but after destroying the logentries set and then on subsequent runs of destroy it would fail because it could not find the log set. 

### References
GH-5876 looks really similar although for a different resource.

**Comment by stack72** [comment]
Hi @fillup

Apologies for the error here - this has been resolved (in the linked PR) and will be part of Terraform 0.9.4

Thanks

Paul

**Comment by fillup** [comment]
Wow, that was fast, thank you!
