### ISSUE TITLE
Azurerm azurerm_virtual_machine_extension hangs indefinitely if VM has no Internet access

### ISSUE THREAD

**Issue by clangaxon** [hashicorp/terraform#13804]
If the NSG on the VM blocks Internet access, azurerm_virtual_machine_extension custom script creation/update will hang Terraform indefinitely. If you then manually open access on the NSG, Terraform will then complete within 30 seconds or so.  I suspect this is a limitation of the WALinuxAgent / Azure, which appears to be trying to push some status to random blob storage accounts.

This can be duplicated with this security_rule:

 ```
 security_rule {
    name = "Internet_Block"
    priority = 100
    direction = "Outbound"
    access = "Deny"
    protocol = "*"
    source_port_range = "*"
    destination_port_range = "*"
    source_address_prefix = "*"
    destination_address_prefix = "Internet"
  }
```

and a azurerm_virtual_machine_extension:

```
resource "azurerm_virtual_machine_extension" "vm_script" {
  name = "some_name"
  location = "some_location"
  resource_group_name = "some_resource_group"
  virtual_machine_name = "some_name"
  publisher = "Microsoft.Azure.Extensions"
  type = "CustomScript"
  type_handler_version = "2.0"
  auto_upgrade_minor_version = "true"

  settings = <<EOF
{
  "fileUris": [ "https://getmy/script" ],
  "commandToExecute": "./script"
}
EOF
}
```

Letting it run for quite some time, and then editing the NSG to allow outbound access:

> module.lmem.azurerm_virtual_machine_extension.vm_script.1: Still creating... (10s elapsed)
> ...
> ...
> module.lmem.azurerm_virtual_machine_extension.vm_script.1: Still creating... (1h16m30s elapsed)
> module.lmem.azurerm_virtual_machine_extension.vm_script.1: Creation complete (ID: /subscriptions/xxx/extensions/yyy)
> 
> Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

**Comment by tombuildsstuff** [comment]
Hi @clangaxon 

Thanks for raising this.

> If the NSG on the VM blocks Internet access, azurerm_virtual_machine_extension custom script creation/update will hang Terraform indefinitely. If you then manually open access on the NSG, Terraform will then complete within 30 seconds or so. I suspect this is a limitation of the WALinuxAgent / Azure, which appears to be trying to push some status to random blob storage accounts.

As you've identified, unfortunately this is an issue at Azure's end, so I don't believe there's a lot we can do to avoid this. Whilst it's possible to set a timeout for a specific resource within Terraform itself, Terraform is just polling the Azure API, which handles the interaction between the Azure host and the VM - which means timing out Terraform wouldn't necessarily stop the script.

It might be worth [filing an issue on the Custom Script Extension Repository](https://github.com/Azure/custom-script-extension-linux) about this, to see if there's anything they could do to fail earlier?

> "fileUris": [ "https://getmy/script" ],

Out of interest, is the File URL you're trying to obtain also on the internet, or internal? That may help the Custom Script Extension team work out where a timeout could be added?

Apologies that we can't be more help here - but I'm going to close this issue in the interim

**Comment by clangaxon** [comment]
Tom,

Perfectly understandable. Thanks for looking at this - we will pursue it with Microsoft.

The file URL is accessible to the VM - as I said, the extension actually runs perfectly - Terraform just isn't aware of it. :(

**Comment by wvxvw** [comment]
@clangaxon Did you have any response from MS?  I think, we are seeing the same issue here.  Somehow, we only experience this problem with Terraform though (we previously had a Python script using `azure-sdk` to do deployment).
