### ISSUE TITLE
Add support for encrypted cross region RDS read replicas

### ISSUE THREAD

**Issue by vamsirede** [hashicorp/terraform#13814]
AWS now supports Read Replicas of Encrypted Database Instances across Regions.

https://aws.amazon.com/about-aws/whats-new/2017/01/amazon-rds-now-supports-read-replicas-of-encrypted-database-instances-across-regions/

**Comment by bclodius** [comment]
@vamsirede I think this is WIP here: https://github.com/hashicorp/terraform/pull/11803

**Comment by vamsirede** [comment]
@bclodius your are correct
