### ISSUE TITLE
Feature request: Export arn as atrtribute for resource aws_cloudfront_distribution

### ISSUE THREAD

**Issue by fillup** [hashicorp/terraform#13816]
Currently the `aws_cloudfront_distribution` resource exports the distribution `id` in format of `EDFDVBD632BHDS5`, but it would be really helpful to have the full ARN in format `arn:aws:cloudfront::1234567890:distribution/EDFDVBD632BHDS5` for use in other resources like `aws_iam_user_policy` to specify the single resource. 

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudfront_distribution

### Example:
I'd like to be able to use this like:

```hcl
resource "aws_cloudfront_distribution" "ui" {
 //...
}
resource "aws_iam_user_policy" "ci_cf" {
  name = "CF"
  user = "${var.username}"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "cloudfront:CreateInvalidation"
      ],
      "Resource": [
        "${aws_cloudfront_distribution.ui.arn}"
      ]
    }
  ]
}
EOF
}
```

**Comment by Ninir** [comment]
Hi @fillup 

Thanks for reporting this. Even if this is not part of the documentation yet, the ARN is exported, so you should be able to use `aws_cloudfront_distribution.ui.arn`.

Could you try and tell us if it's ok?

Will open a PR for that.

Thanks!
