### ISSUE TITLE
NAT gateway creation fails with error Error waiting for NAT Gateway to become available

### ISSUE THREAD

**Issue by ctippur** [hashicorp/terraform#13836]
Hello,
Terraform version: v0.9.2

I am having trouble creating nat gateway. I am following the tf defined here
https://github.com/pk4media/terraform.aws_nat_gateway/blob/master/main.tf

The first time, the apply fails with

`* aws_nat_gateway.nat.1: Error waiting for NAT Gateway (nat-0a6ac67cb96eaaaaa) to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)
module.app_server.aws_nat_gateway.nat[0]: 1 error(s) occurred:
aws_nat_gateway.nat.0: Error waiting for NAT Gateway (nat-0f57fc95740de49c4) to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)`

In subsequent runs, the failure seem to be:

`
2017/04/20 20:29:49 [DEBUG] plugin: terraform:     <natGatewaySet>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:         <item>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <subnetId>subnet-f6681555</subnetId>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <failureCode>Resource.AlreadyAssociated</failureCode>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <natGatewayAddressSet>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:                 <item>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:                     <networkInterfaceId>eni-3d332315</networkInterfaceId>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:                     <allocationId>eipalloc-b43fa68e</allocationId>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:                     <privateIp>10.0.1.10</privateIp>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:                 </item>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             </natGatewayAddressSet>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <deleteTime>2017-04-21T03:27:58.735Z</deleteTime>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <createTime>2017-04-21T03:26:05.416Z</createTime>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <vpcId>VPC</vpcId>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <natGatewayId>nat-fsfdsgfsfdgs</natGatewayId>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <state>failed</state>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:             <failureMessage>Elastic IP address [eipalloc-a43fa58y] is already associated</failureMessage>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:         </item>
2017/04/20 20:29:49 [DEBUG] plugin: terraform:     </natGatewaySet>
2017/04/20 20:29:49 [DEBUG] plugin: terraform: </DescribeNatGatewaysResponse>
`

Plan:

`-/+ module.app_server.aws_nat_gateway.nat.0 (deposed)
    allocation_id:        "old" => "new"
    network_interface_id: "eni-5be4f273" => "<computed>"
    private_ip:           "redacred" => "<computed>"
    public_ip:            "redacted" => "<computed>"
    subnet_id:            "old" => "new" (forces new resource)

-/+ module.app_server.aws_nat_gateway.nat.1 (deposed)
    allocation_id:        "old" => "new"
    network_interface_id: "old" => "<computed>"
    private_ip:           "redacted" => "<computed>"
    public_ip:            "redacted" => "<computed>"
    subnet_id:            "subnet-bf7be7f6" => "subnet-75db4c3c" (forces new resource)

+ module.app_server.aws_route_table.nat.0
    route.#:                                     "1"
    route.~2781612442.cidr_block:                "0.0.0.0/0"
    route.~2781612442.egress_only_gateway_id:    ""
    route.~2781612442.gateway_id:                ""
    route.~2781612442.instance_id:               ""
    route.~2781612442.ipv6_cidr_block:           ""
    route.~2781612442.nat_gateway_id:            "${element(aws_nat_gateway.nat.*.id, count.index)}"
    route.~2781612442.network_interface_id:      ""
    route.~2781612442.vpc_peering_connection_id: ""
    tags.%:                                      "3"
    tags.Environment:                            "sbx"
    tags.Name:                                   "sbxpubroute"
    tags.Service:                                "nat"
    vpc_id:                                      "vpc-redacred"

~ module.app_server.aws_route_table.nat.1
    route.3881485174.cidr_block:                 "0.0.0.0/0" => ""
    route.3881485174.egress_only_gateway_id:     "" => ""
    route.3881485174.gateway_id:                 "" => ""
    route.3881485174.instance_id:                "" => ""
    route.3881485174.ipv6_cidr_block:            "" => ""
    route.3881485174.nat_gateway_id:             "nat-redaced" => ""
    route.3881485174.network_interface_id:       "" => ""
    route.3881485174.vpc_peering_connection_id:  "" => ""
    route.~2781612442.cidr_block:                "" => "0.0.0.0/0"
    route.~2781612442.egress_only_gateway_id:    "" => ""
    route.~2781612442.gateway_id:                "" => ""
    route.~2781612442.instance_id:               "" => ""
    route.~2781612442.ipv6_cidr_block:           "" => ""
    route.~2781612442.nat_gateway_id:            "" => "${element(aws_nat_gateway.nat.*.id, count.index)}"
2017/04/20 20:36:49 [DEBUG] plugin: /usr/local/Cellar/terraform/0.9.2/bin/terraform: plugin process exited
    route.~2781612442.network_interface_id:      "" => ""
    route.~2781612442.vpc_peering_connection_id: "" => ""

`

**Comment by ctippur** [comment]
Any pointers on this?

**Comment by Quantisan** [comment]
I'm seeing the same error when creating a pub + priv VPC on AWS.

```
Error applying plan:

1 error(s) occurred:

* aws_nat_gateway.2a_gateway: 1 error(s) occurred:

* aws_nat_gateway.2a_gateway: Error waiting for NAT Gateway (nat-09c0fe5136a0bea8e) to become available: unexpected state 'failed', wanted target 'available'. last error: %!s(<nil>)
```

**Comment by wirkmood** [comment]
Do you find a solution?
I have the same problem and I don't know how to fix this issue.

Thank you

**Comment by WayneYe** [comment]
+1
buzzed by this issue!

**Comment by ritwik-singh-yash** [comment]
This issue still persists.
Any resolution to this???

**Comment by hutger** [comment]
Still persists... 
Terraform v0.11.3
+ provider.aws v1.10.0

**Comment by xomikronx** [comment]
Any help would be appreciated here.  Haven't changed anything on my.  Stopped working.

here's my config: 
`resource "aws_nat_gateway" "ngw" {
  allocation_id = "${aws_eip.eip_name.id}"
  subnet_id     = "${aws_subnet.subnet-a.id}"

  tags {
    Name = "nat gateway"
  }
}`

Any help appreciated.

**Comment by charlesarnaudo** [comment]
Still persisting, Terraform 11.3

**Comment by ritwik-singh-yash** [comment]
http://blog.kaliloudiaby.com/index.php/terraform-to-provision-vpc-on-aws-amazon-web-services/
this should be helpful and hopefully it will resolve most of the issues.

**Comment by KnoxKnot** [comment]
The issue is that the NAT is not being assigned an Elastic IP. In my case I omitted the $ in the value for the allocation_id. @ritwik-singh-yash article will solve the issue.

**Comment by sudosingh** [comment]
@knoxknot I tried omitting the $ but the error still persists, any solution

**Comment by knoxknot** [comment]
@sudosingh. My comment above meant that my error was that I missed appending the $ prefix against the allocation_id value. But once I caught that and fixed it my issue was resolved. Although I majorly still write terraform codes with versions less than .12 Could you please be kind to share you error log.
