### ISSUE TITLE
Refreshing many AWS security groups is very slow

### ISSUE THREAD

**Issue by jvns** [hashicorp/terraform#13837]
I have ~300 security groups and ~1400 rules that I want to manage in one Terraform state file. Refreshing all of them for a `terraform plan` takes a very long time (on the order of 10 minutes), presumably because it's making separate AWS API calls for every single one.

It would be dramatically faster (a few seconds instead of many minutes) if, instead of making many `DescribeSecurityGroups` calls (one per security group that needs refreshing), if Terraform could make a single `DescribeSecurityGroups` call, download all the security group definitions, and then just use that response to refresh all the SGs that need refreshing.

**question**: Are there any examples of reusing the results of API calls in Terraform right now to refresh multiple resources at a time?

### Terraform Version

0.9.2

### Affected Resource(s)

- aws_security_group
- aws_security_group_rule

**Comment by grubernaut** [comment]
Related to: #7388

**Comment by deftflux** [comment]
My pull request https://github.com/hashicorp/terraform/pull/14332 improves this to some extent.  Instead of a separate API call for each individual rule, there is only be one per security group.  Obviously, however, there is still room for improvement.
