### ISSUE TITLE
The path used to open plugin seems to be mangled in Windows

### ISSUE THREAD

**Issue by craiganderson-53546** [hashicorp/terraform#13849]
I am a Terraform noob, and just installed Terraform v0.9.3 on Windows 7.  I am trying to use a new provider from Oracle for there IaaS Bare Metal Cloud.  I compiled the plugin and am using the test.tf file Oracle provided to test my installation.  My problem seems to be opening the plugin and therefore pretty generic.  I set TF_LOG=TRACE and did 'terraform plan'.  I see in the output that it automatically discovers my plugin correctly...

```
C:\Users\canderson\Documents\go\src\github.com\oracle\terraform\test>terraform plan
2017/04/21 09:21:19 [INFO] Terraform version: 0.9.3  1601af7a076fd03fe940455db7fd01dfa747c795
2017/04/21 09:21:19 [INFO] Go runtime version: go1.8
2017/04/21 09:21:19 [INFO] CLI args: []string{"C:\\Terraform\\terraform.exe", "plan"}
2017/04/21 09:21:19 [DEBUG] Discovered plugin: baremetal-opc = C:\Users\canderson\Documents\go\src\github.com\oracle\terraform\test\terraform-provider-baremetal-opc
```

It then parses the test.tf file correctly (at least I see no errors).  But when it starts the plugin it doubles up the `\` characters in the path and says it cannot find the file...

```
2017/04/21 09:21:19 [DEBUG] plugin: starting plugin: C:\Users\canderson\Documents\go\src\github.com\oracle\terraform\test\terraform-provider-baremetal-opc []string{"C:\\Users\\canderson\\Documents\\go\\src\\github.com\\oracle\\terraform\\test\\terraform-provider-baremetal-opc"}
2017/04/21 09:21:19 [ERROR] root: eval: *terraform.EvalInitProvider, err: exec: "C:\\Users\\canderson\\Documents\\go\\src\\github.com\\oracle\\terraform\\test\\terraform-provider-baremetal-opc": file does not exist
```

Even though I can cut & paste the path and list it...

```
C:\Users\canderson\Documents\go\src\github.com\oracle\terraform\test>dir C:\Users\canderson\Documents\go\src\github.com\oracle\terraform\test\terraform-provider-baremetal-opc
 Volume in drive C has no label.
 Volume Serial Number is 0469-C7BC

 Directory of C:\Users\canderson\Documents\go\src\github.com\oracle\terraform\test

04/20/2017  04:18 PM        16,107,520 terraform-provider-baremetal-opc
               1 File(s)     16,107,520 bytes
               0 Dir(s)  35,971,784,704 bytes free
```

and the dir of the mangled path fails.  Is there a parameter I can use to influence how Terraform treats Windows' paths?

**Comment by craiganderson-53546** [comment]
I also see this same behavior when trying to use %APPDATA%\terraform.rc, meaning that none of the formats I normally used in other products that are used in both Linux and Windows work.

**Comment by craiganderson-53546** [comment]
(Not sure what I did to close this issue.  That was an accident)

**Comment by jbardin** [comment]
Hi @craiganderson-53546,

The double backslash (`\\`) in the log output is just the formatting used to explicitly differentiate escape characters, which you will also notice in the first `terraform.exe` execution. The exec path which is printed only contains single `\` characters.

What do you mean when you try to use `%APPDATA%\terraform.rc`, that it effects plugins or that terraform can't load `terraform.rc`, and what "formats" are you referring to?

The paths looks correct, so I'm not sure what the problem could be. I'll try to reproduce it on my side.

**Comment by craiganderson-53546** [comment]
The formats I refer to are the ways of expressing a Windows path in software that is designed to work both in Linux and Windows.  Sometimes you have to use forward slashes instead of the Windows' back slashes or double up the back slashes.  It depends upon the coding style and approach the developer uses.

The point is I can cut & paste the path given in 'starting plugin:' and do a directory search successfully on it, but not the 'string[]' value.  The fact that it says the file does not exist tells me it is using the string[] to open the plugin file.

Before I knew Terraform would automatically discover plugins, I set up a terraform.rc file per the instructions.  It contained the following:

`providers {
    opc = "c:\Users\canderson\Documents\go\src\terraform-provider-baremetal\terraform-provider-baremetal-opc"
}
`

But the debug output would always say things like...

`2017/04/21 09:03:47 [DEBUG] Attempting to open CLI config file: C:\Users\canderson\AppData\Roaming\terraform.rc
...[snip]
2017/04/21 09:03:47 [DEBUG] plugin: waiting for all plugin processes to complete...
or asking for user input: 1 error(s) occurred:
provider.opc: exec: "c:\\Users\\canderson\\Documents\\go\\src\\terraform-provider-baremetal\\terraform-provider-baremetal-opc": file does not exist`

Again with the ' \\ '

**Comment by jbardin** [comment]
Thanks, I see what you mean by the format now.

The extra `\` backslashes in the log output are simply how we choose to print the value, which is a quoted string matching how it would appear in the source. If the string value contained 2 backslashes, those log lines should show `\\\\`. 

From what I can see, I think the problem is that Windows requires the executable to have a `.exe` extension, but your provider binary only has the name `terraform-provider-baremetal-opc`. When Windows looks for the binary to execute, it's not finding that name with the `.exe` extension, so it returns the "file does not exist" error.

**Comment by craiganderson-53546** [comment]
You are correct, renaming the plugin with .exe extension did resolve the issue.  Thank you!

**Comment by achoudhari10** [comment]
hello @jbardin ,
good analysis of yours , renaming the file extension to .exe worked .
Thank you for your sugestion.
