### ISSUE TITLE
Error with git/ssh on windows in 0.8.7

### ISSUE THREAD

**Issue by afrasso** [hashicorp/terraform#13848]
I'm getting an error when I attempt to download a terraform module via git/ssh on Windows.

Here is my terraform script:

```
variable "environment" {}
variable "instance_type" {}
variable "instance_count" {}

variable "security_type" {
  default = "internal"
}

variable "instance_dns_zone" {
  default = "morch"
}

variable "dns_zone" {
  default = "morch"
}

variable "server_class_name" {
  default = "skudata"
}

variable "team_contact" {
  default = "teamemail@mycompany.com"
}

variable "enable_alarm" {
  default = "0"
}

provider "aws" {
  region = "eu-west-1"
  profile = "merchantorchestration"
}

module "instance" {
  source = "git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git//instance?ref=release/2.0"

  instance_count = "${var.instance_count}"
  instance_type = "${var.instance_type}"
  environment = "${var.environment}"
  server_class_name = "${var.server_class_name}"
  dns_zone = "${var.instance_dns_zone}"
  team_contact = "${var.team_contact}"
  user_data = "${file("user-data.yaml")}"
}

module "alarms" {
  source = "git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git//alarms?ref=release/2.0"
  instance_count = "${var.instance_count * var.enable_alarm}"
  instances = "${module.instance.instances}"
  environment = "${var.environment}"
  server_class_name = "${var.server_class_name}"
}

module "skudata-elb" {
  source = "git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git//loadbalancer?ref=release/2.0"
  port = 12000
  dns_zone = "${var.dns_zone}"
  application = "skudata"
  instances = "${module.instance.instances}"
  environment = "${var.environment}"
  security_type = "${var.security_type}"
  team_contact = "${var.team_contact}"
}

module "skudata-dns" {
  source = "git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git//applicationdns?ref=release/2.0"
  application = "${module.skudata-elb.application}"
}
```

On 0.8.6, the download works successfully:

```
C:\infrastructure>terraform_0.8.6_windows_amd64.exe get
2017/04/21 10:38:24 [INFO] Terraform version: 0.8.6  df4bcf64828598a25bd41f00470b2ab3a66f3169
2017/04/21 10:38:24 [INFO] CLI args: []string{"C:\\terraform\\terraform_0.8.6_windows_amd64.exe", "get"}
2017/04/21 10:38:24 [DEBUG] Attempting to open CLI config file: C:\Users\afrasso\AppData\Roaming\terraform.rc
2017/04/21 10:38:24 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
Get: git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git?ref=release/2.0
Get: git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git?ref=release/2.0
Get: git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git?ref=release/2.0
Get: git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git?ref=release/2.0
Get: file://C:/infrastructure/.terraform/modules/c13f956ed06ea3df3cd4ffba50e5a9bf/network
Get: file://C:/infrastructure/.terraform/modules/c13f956ed06ea3df3cd4ffba50e5a9bf/naming
Get: file://C:/infrastructure/.terraform/modules/ade77d570c2f102e053c175986ec6565/naming
Get: file://C:/infrastructure/.terraform/modules/bc2d20d9874031d11b3e9780b072306d/network
Get: file://C:/infrastructure/.terraform/modules/bc2d20d9874031d11b3e9780b072306d/naming
2017/04/21 10:38:28 [DEBUG] New state was assigned lineage "9a76ed6a-d514-4e6e-a163-632ff6060e9d"
2017/04/21 10:38:28 [DEBUG] plugin: waiting for all plugin processes to complete...
```

However, on 0.8.7, the download fails:

```
C:\infrastructure>terraform_0.8.7_windows_amd64.exe get
2017/04/21 10:38:01 [INFO] Terraform version: 0.8.7  c1df88ac4633b61b83802bbb10c343c20d3035b5
2017/04/21 10:38:01 [INFO] CLI args: []string{"C:\\terraform\\terraform_0.8.7_windows_amd64.exe", "get"}
2017/04/21 10:38:01 [DEBUG] Attempting to open CLI config file: C:\Users\afrasso\AppData\Roaming\terraform.rc
2017/04/21 10:38:01 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
Get: git::ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git?ref=release/2.0
2017/04/21 10:38:02 [DEBUG] plugin: waiting for all plugin processes to complete...
Error loading Terraform: Error downloading modules: error downloading 'ssh://git@mygitrepo.net:7999/rigl/terraform-modules.git?ref=release/2.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\c13f956ed06ea3df3cd4ffba50e5a
9bf'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I can clone git repositories using ssh normally, so I don't think the problem is actually with SSH. Is there anything that changed in 0.8.7 regarding git/ssh?

Thanks.

**Comment by afrasso** [comment]
I've discovered a workaround. It seems the issue might be related to my machine setup. I have the following environment variables set:

```
HOMEDRIVE=U:
HOMEPATH=\
```

I copied my .ssh directory from C:\Users\afrasso\.ssh to U:\.ssh, which resolves the issue in terraform. It seems that when I do a git clone, the keys in the C:\Users\afrasso\.ssh directory are used, but when I use terraform it uses the keys in U:\.ssh

**Comment by apparentlymart** [comment]
Hi @afrasso! Sorry things didn't work out as expected here.

This seems pretty strange, since internally Terraform is basically just running `git clone ...` here.

One difference I notice from reading the code is that Terraform sets the `GIT_SSH_COMMAND` environment variable to just `ssh`, which is _usually_ the default but perhaps you have that overridden on your machine?

This seems like a plausible explanation for this issue because in 0.8.7 we upgraded the underlying go-getter library and the upgrade included [the commit where it started setting `GIT_SSH_COMMAND`](https://github.com/hashicorp/go-getter/commit/cf014db4dae74ade39b4e7cc5551612298cf3578).

There were [quite a few `go-getter` changes](https://github.com/hashicorp/go-getter/compare/2fbd997432e72fe36060c8f07ec1eaf98d098177...c3d66e76678dce180a7b452653472f949aedfbcd) in this release, so if that isn't it then I'll dig in some more to see if any of the others look plausible.

**Comment by cintiadr** [comment]
I have a somehow related problem. 

When running `terraform get` in CI, I wanted to override `GIT_SSH` (or `GIT_SSH_COMMAND`) so it can use a key located somewhere else in the filesystem. 

Is this possible with terraform?

**Comment by paddycarver** [comment]
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, or continue to have the problem described, please feel free to reply to this issue and we'll reopen it. Thanks!

**Comment by a-yiorgos** [comment]
With terraform version 0.10.8 if you use GIT_SSH_COMMAND instead of GIT_SSH I am able to use a script that executes ssh with the proper private key and do what is expected.
