### ISSUE TITLE
Values of provider "aws" superseded by ~/.aws/credentials when doing terraform init

### ISSUE THREAD

**Issue by ArmandGrillet** [hashicorp/terraform#13857]
### Terraform Version
Terraform v0.9.3

### Affected Resource(s)
provider "aws"

### Terraform Configuration Files
The main configuration file:
```hcl
terraform {
  backend "s3" {
    bucket = "hey"
    key    = "you"
    region = "us-east-1"
  }
}

variable "access_key" {
  description = "AWS access key"
}

output "access_key" {
    value = "${var.access_key}"
}

variable "secret_key" {
  description = "AWS secret key"
}

output "secret_key" {
    value = "${var.secret_key}"
}

variable "region" {
  default = "us-west-2"
}

provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}
```

`terraform.tfvars`:

```
access_key="MYKEY"
secret_key="MYSECRETKEY"
```

### Expected Behavior
Doing `terraform init` and `terraform apply` works and uses the values of `provider "aws"`.

### Actual behavior

When doing `terraform init`:
```
Downloading modules (if any)...
Get: file://path/I/dont/want/to/share
Get: file://path/I/dont/want/to/share
Initializing the backend...
Error configuring the backend "s3": No valid credential sources found for AWS Provider.
```

To fix the issue I have followed [the documentation](https://www.terraform.io/docs/providers/aws/#shared-credentials-file), put my AWS credentials in `$HOME/.aws/credentials` and emptied `terraform.tfvars`. `terraform init` then works.

I have then done `terraform apply` and it asks for the variables:
```
$ terraform apply
var.access_key
  AWS access key

  Enter a value: 
```

I would expect both `init` and `apply` to use the values of the provider "aws" that uses `terraform.tfvars` but it appears that the initialization always uses the AWS credentials. Is it expected? 

Can it be fixed without creating a second file containing the same variables (something stated [in the doc](https://www.terraform.io/docs/providers/aws/#shared-credentials-file) using the parameter `shared_credentials_file`)?

**Comment by jbardin** [comment]
Hi @ArmandGrillet,

Sorry this isn't working as expected. The backend does not use the provider configuration, they are intended to be separate.

We have an open feature request at #13022 for early interpolation for the terraform block, which would allow you to use this configuration.
