### ISSUE TITLE
Terraform Destroy AWS SPOT Fleet did not terminates AWS instances.

### ISSUE THREAD

**Issue by abhishekamralkar** [hashicorp/terraform#13859]
### Terraform Version

0.9.3

### Affected Resource(s)
-- AWS SPOT Fleet

```terraform destroy```

### Expected Behavior
Terraform destroy cancel SPOT Fleet request in AWS but instance keep running. 

### Actual Behavior
What actually happened?
Ideally instance should get terminates too as SPOT Fleet request get cancel.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy`

**Comment by stack72** [comment]
Hi @abhishekamralkar 

Thanks for reporting this bug - sorry it is causing you issues! Can you post your terraform config (minus any secrets) or tell me if you are setting the following:

```
terminate_instances_with_expiration = true
```

We have spot_fleet_request acceptance tests that run nightly and that scale down the instances when the request is cancelled / expires

Thanks

Paul

**Comment by abhishekamralkar** [comment]
@stack72 closing this issue it was my config error.

**Comment by blockjon** [comment]
What is the solution?

**Comment by haokanga** [comment]
@blockjon set `terminate_instances_with_expiration = true` will work

**Comment by totomz** [comment]
I thiknk this bug should be reopened.

`TerminateInstancesWithExpiration` indicates whether running Spot Instances are terminated when the Spot Fleet request expires, as per [AWS Docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html)

Also, [Terraform docs for iam_fleet_role](https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html#iam_fleet_role) describe the correct behaviour: spot instances should be terminated if the fleet request is cancelled (which is  happening with `terraform destroy`) **or**  when the Spot fleet request expires, *if you set terminateInstancesWithExpiration.*
