### ISSUE TITLE
Feature request: allow defining environment variables for local-exec provisioner

### ISSUE THREAD

**Issue by dasch** [hashicorp/terraform#13860]
It would be beneficial to be able to set environment variables that should be defined in the context that a `local-exec` provisioner is executed in, e.g.

```hcl
provisioner "local-exec" {
  env {
    NAME = "John"
  }

  command = "echo $NAME"
}
```

A lot of programs accept parameters in the form of environment variables.

**Comment by eeichinger** [comment]
great stuff - this also helps keeping secrets out of the terraform log output by passing them as env variables instead exec-ing a rendered script!

**Comment by rberlind** [comment]
Another related idea would be to allow the shell started by the local-exec provisioner to access existing environment variables.  So, if I had an environment variable  MYVAR, I could refer to it in the command string with $MYVAR.  Or is this already possible?  I tried doing it and found that my existing environment variables were not read.
