### ISSUE TITLE
Error in using chomp with file

### ISSUE THREAD

**Issue by cheburakshu** [hashicorp/terraform#13870]
Hi .. I am using versing 0.9.2.

I get error when I use chomp with file.

Is there a way to get around this?

```
* module.key_pair.var.key_name: 1:3: unknown function called: chomp in:

${chomp(file("init/fingerprint.txt"))}

```

**Comment by cheburakshu** [comment]
Think chomp doesn't have scope when passed into a module. Worked around by writing the file without a newline and taking chomp  out for this to work

**Comment by apparentlymart** [comment]
Hi @cheburakshu!

This function was added in version 0.9.3, so this should work as expected if you upgrade. Sorry for this not being clearer!
