### ISSUE TITLE
documentation for s3 backend doesn't make clear all differences from legacy backend remote state

### ISSUE THREAD

**Issue by jmahowald** [hashicorp/terraform#13881]
The documentation for switching from legacy remote configuration
https://www.terraform.io/docs/backends/legacy-0-8.html

and 
https://www.terraform.io/docs/backends/types/s3.html

Should probably indicate that the location for the state 

e.g. prior to 9.0 I would generate a data entry for the remote state based off the key given

```
data "terraform_remote_state" "vpc_layer" {
  backend="s3"
  config { 
    bucket = "terraform.qa-blue.myorg.com"
    key = "basevpc/terraform.tfstate"
    region = "us-west-1" }
} 
```

but it should now include a prefix with `env:<envname>`

```
data "terraform_remote_state" "vpc_layer" {
  backend="s3"
  config { 
    bucket = "terraform.qa-blue.myorg.com"
    key = "env:/default/basevpc/terraform.tfstate"
    region = "us-west-1" }
} 
```

**Comment by mildwonkey** [comment]
Hi, I'm going to close this issue since it's referencing documentation from terraform v0.9. If you still have an issue with the current version of terraform, please open a new github issue. Thanks!
