### ISSUE TITLE
Unable to Create Cloudwatch Metric/Alarm in Route53 Healthcheck

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform#13895]
### Terraform Version
`0.9.1` and `0.9.3`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_health_check
- aws_cloudwatch_metric_alarm

### Terraform Configuration Files
```hcl
resource "aws_route53_health_check" "health_check" {
  fqdn                  = "${var.name}-${var.environment_short}.${var.domain_name}"
  port                  = "${var.https_port}"
  type                  = "HTTPS"
  resource_path         = "/login"
  failure_threshold     = "3"
  request_interval      = "30"
  cloudwatch_alarm_name = "${var.name}-${var.environment_short}.${var.domain_name}"
  cloudwatch_alarm_region = "ap-southeast-2"
}

resource "aws_cloudwatch_metric_alarm" "alarm" {
  depends_on          = ["aws_route53_health_check.health_check"]
  alarm_name          = "${var.name}-${var.environment_short}.${var.domain_name}"
  comparison_operator = "LessThanOrEqualToThreshold"
  evaluation_periods  = "2"
  metric_name         = "AppHealthCheck"
  namespace           = "AWS/Route53"
  period              = "60"
  statistic           = "Minimum"
  threshold           = "0"
  alarm_description   = "This metric monitors application"

  dimensions = {
    HealthCheckId = "${aws_route53_health_check.health_check.id}"
  }
}
```

### Expected Behavior
Alarm should have been created and visible in Route53 Healthcheck

### Actual Behavior

- Health check was created fine
- Alarm got created but is in `INSUFFICIENT DATA` state and was not linked to Route53 Healthcheck
![2017-04-24_18-58-08](https://cloud.githubusercontent.com/assets/6998650/25330078/af5f7552-2921-11e7-9c52-02ca86e425fc.png)

### Steps to Reproduce
run `terraform apply` after copying the above `.tf` file

### References
- [PR-8319](https://github.com/hashicorp/terraform/pull/8319)
- GH-7830

**Comment by mwpeterson** [comment]
On `0.9.3`.

I had to remove `cloudwatch_alarm_name` and `cloudwatch_alarm_region` from the `aws_route53_health_check` resource to get the alarm to connect to the health check. It felt backwards. The HealthCheckId dimension was enough to wire them together.

**Comment by vikas027** [comment]
@mwpeterson Can you pls share your code? I am now on Terraform v0.9.3, also removed `cloudwatch_alarm_name` and `cloudwatch_alarm_region` from `aws_route53_health_check.health_check` resource, but still, alarm is not linked to Route53 Health check :( 

![2017-04-25_19-05-05](https://cloud.githubusercontent.com/assets/6998650/25377184/2cf15760-29ea-11e7-9be7-f6abb6c3bad6.png)

**Comment by grayaii** [comment]
So, basically there is no way to create a cloudwatch alarm for the route 53 health check?
I assume this is not the same cloudwatch alarm that the health check is using to determine the overall healthyness/unhealthiness?
![alarms](https://user-images.githubusercontent.com/847072/36559236-58cff924-17db-11e8-8455-f08a75a5e35d.jpg)

**Comment by bflad** [comment]
@grayaii it may be possible, but this may be related to which region the CloudWatch alarm is created in, please see the discussion on the open issue: https://github.com/terraform-providers/terraform-provider-aws/issues/712 -- I'm going to lock this issue to consolidate discussion to the open issue.
