### ISSUE TITLE
Refreshing the state of azurerm_redis_cache resource

### ISSUE THREAD

**Issue by horsey** [hashicorp/terraform#13896]
### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
azurerm_redis_cache

### Terraform Configuration Files
```hcl
resource "azurerm_redis_cache" "redis" {
    name                = "redis0"
    location            = "East US"
    resource_group_name = "${azurerm_resource_group.production.name}"
    capacity            = 1
    family              = "C"
    sku_name            = "Standard"
    enable_non_ssl_port = false

    redis_configuration {
        maxclients = "1000"
    }
    tags {
        role = "redis"
        environment = "production"
    }

 }
```

### Debug Output
https://gist.github.com/horsey/d135a0646e6d4cd1bcbe1355092f19ee

### Panic Output
None

### Expected Behavior
redis0 resource should be re-created when converged with `terraform apply`.

### Actual Behavior
`terraform apply` throws an error linked in the gist above. 

### Steps to Reproduce
1. Converge the azurerm_redis_cache resource mentioned above
2. `terraform apply`
3. Delete the resource from the Azure portal manually.
4. `terraform apply`

### Important Factoids
The set of steps done on a azurerm_virtual_machine resource recreates the virtual machine.  Is it okay to expect the similar behaviour?

### References
None.

**Comment by horsey** [comment]
@tombuildsstuff I am not very sure if this is bug or an issue, but how do I get out of the situation I put my self in? I need to re-create the resource.

**Comment by tombuildsstuff** [comment]
Hi @horsey 

Thanks for raising this issue.

> I am not very sure if this is bug or an issue, but how do I get out of the situation I put my self in? I need to re-create the resource.

Apologies about this - that's a bug, and I've opened PR #13899 to fix this issue.

In the interim you can force a recreation of the resource [via the `taint` command](https://www.terraform.io/docs/commands/taint.html) on the next Plan/Apply, like so:

```
terraform taint azurerm_redis_cache.redis
```

If that doesn't work (seeing as it's been deleted manually anyway) - you can manually delete it via the `state rm` command:
```
terraform state rm azurerm_redis_cache.redis
```

Hopefully that should allow you to proceed until #13899 is merged? :)

Thanks!
