### ISSUE TITLE
Request for Google Cloud Datastore backend type

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#13894]
Would it be possible to use [Google Cloud Datastore](https://cloud.google.com/datastore/) as a new [backend type](https://www.terraform.io/docs/backends/types/index.html)? I believe it could support **locking** and **versioning** as well.

**Comment by sl1pm4t** [comment]
Why specifically datastore ? 
BTW, a PR for a Google centric backend has been submittedin #15592 that works against Google Cloud Storage.
It supports locking, and could potentially be made to support versioning considering Google Cloud Storage supports [versioning](https://cloud.google.com/storage/docs/object-versioning).
