### ISSUE TITLE
Remote-exec provisioner retries script upload indefinitely

### ISSUE THREAD

**Issue by vtorhonen** [hashicorp/terraform#13901]
### Terraform Version

Terraform v0.9.3

### Affected Resource(s)

Any resource using `remote-exec` provisioner.

### Terraform Configuration Files
```hcl
resource "null_resource" "foo" {
  connection {
    host = "localhost"
    port = "2222"
    user = "someuser"
    password = "somepassword"
  }
  provisioner "remote-exec" {
    inline = [ "uptime" ]
  }
}
```

### Debug Output

https://gist.github.com/vtorhonen/789c647aa5a925e997452724c91fcf34

After entering retry loop CTRL+C was pressed and the run was stopped. Redacted most of the identical "Failed to upload script" error lines from the log.

### Panic Output

None.

### Expected Behavior

Terraform `remote-exec` provisioner runs commands defined in [`inline` parameter](https://www.terraform.io/docs/provisioners/remote-exec.html#inline). These commands are combined into a single script, which by default is transferred to the target server at `/tmp/terraform_<random string>.sh`.

Terraform should either exit after the script upload failed, or it should use exponential backoff for retry attempts.

### Actual Behavior

Terraform tries to re-upload the file until the [provisioner timeout](https://www.terraform.io/docs/provisioners/connection.html#timeout) is reached. By default this is 5 minutes.

Retrying causes heavy CPU load. After two minutes of running Terraform and transforming my Macbook into a jet engine `top -o cpu` looks like this:

```
PID    COMMAND      %CPU  TIME     #TH   #WQ  #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS            %CPU_ME %CPU_OTHRS UID  FAULTS    COW      MSGSENT    MSGRECV
2016   terraform    149.9 03:04.01 15/1  0    47    14M    0B     0B     2013  2014  running  *0[1]             0.00000 0.00000    501  8808      78       41         19
2014   terraform    77.6  01:33.52 18/1  0    56    14M    0B     0B     2013  2013  running  *0[1]             0.00000 0.00000    501  10195     149      47         22
2013   terraform    48.1  00:59.07 11/2  0    35    7928K  0B     0B     2013  93168 running  *0[1]             0.00000 0.00000    501  7293      185      61         20
```

### Steps to Reproduce

1. Create a test server. I used a Vagrant test box with a test account.
2. Fill all empty space in `/tmp` on the test server.
3. Prepare `main.tf` with the correct credentials.
4. Run `terraform apply`.

### Important Factoids

Backoff is already mentioned in [resource_provisoner.go#L237](https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/remote-exec/resource_provisioner.go#L237) as a TODO comment:

> // retryFunc is used to retry a function for a given duration
> // TODO: this should probably backoff too

### References

None.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. If you are still experiencing this issue in Terraform v0.13, please open a new issue and fill out the template.
Thanks!
