### ISSUE TITLE
Migrating the states from 0.7.13 to 0.9.3 and using env

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#13904]
Hi,

I am upgrading from `0.7.13` to `0.9.3` for 10 environments. Lets say the environments are named `one` `two` `three` .. `ten`. The backend used is `s3`. Earlier, for each environment, backend statefile was set as `one.tfstate` `two.tfstate` and so on.. . in the `s3` bucket `tf-state` I see that `terraform env new one` for example will create a new `one` environment key under `env:` in s3 and store the states under `one`.

What is the recommended way of migrating the old state backends to the new ones and make use of the new `environments` feature.

**Comment by catsby** [comment]
Hey @Puneeth-n –

We've written some about this in a recent blog post:

- https://www.hashicorp.com/blog/terraform-0-9/#backends

Specifically, you should check out "Upgrading to Terraform v0.9":

- https://www.terraform.io/upgrade-guides/0-9.html?_ga=1.133821575.8692819.1487341845

And "Backend & Legacy Remote State"

- https://www.terraform.io/docs/backends/legacy-0-8.html

I _believe_ your questions are answered and guidance given there, but please let me know if after digesting those if you still have questions. Good luck and please let me know!

**Comment by Puneeth-n** [comment]
@catsby Thanks for the links but somehow I am missing something. Below I summarize how I go about it.

I want to migrate `alpha` environment from `old-s3bucket` to `new-s3bucket`. I have configured the 

1. I have pulled the old state using terraform-0.7.13 and backed it up outside the terraform config directory.
2. I created a new config to store the migrated states to the new s3 bucket `new-s3bucket`
3. I removed the `tfstate` file in `.terraform/terraform.tfstate`
4. `terraform env new alpha` => `Created and switched to environment "alpha"!`
5. `cp ../alpha.tfstate .terraform/terraform.tfstate`
6. `terraform init` => 
```
Terraform has detected that you're attempting to configure a new backend.
At the same time, legacy remote state configuration was found. Terraform will
first configure the new backend, and then ask if you'd like to migrate
your remote state to the new backend.


key
  The path to the state file inside the bucket

  Enter a value: alpha.tfstate

region
  The region of the S3 bucket.

  Enter a value: eu-west-1

Do you want to copy the legacy remote state from "s3"?
  Terraform can copy the existing state in your legacy remote state
  backend to your newly configured backend. Please answer "yes" or "no".

  Enter a value: yes

Do you want to copy state from "s3" to "s3"?
  Pre-existing state was found in "s3" while migrating to "s3". No existing
  state was found in "s3". Do you want to copy the state from "s3" to
  "s3"? Enter "yes" to copy and "no" to start with an empty state.

  Enter a value: yes
```

At this point I see `alpha.tfstate` in the root of my new bucket `new-s3bucket` which is a replica from the `old-s3bucket`. 

7. `terraform plan` => shows me that all the resources need to be created!!!!

**Comment by Puneeth-n** [comment]
@catsby Finally got it working. I see that the states are not stored anymore in `.terraform/terraform.tfstate` and now `terraform` interacts directly with the backend when configured. 

My old setup in `0.7.13`:

```
old-s3bucket
    |__one.tfstate (A single terraform statefile for the whole environment)
    |__two.tfstate
    |__three.tfstate
    :
```

with the new terraform environment and backend 0.9.3
```

new-s3bucket:
    |__env:/one/main.tfstate
    |__env:/two/main.tfstate
    |__env:/three/main.tfstate
    |__env:/four/main.tfstate
    :
```

Before I had parameterized the `s3 key` since `terraform environment` was not yet available.

**Comment by catsby** [comment]
@Puneeth-n Awesome, I'm glad you got it sorted. I hope the documentation was useful, and I appreciate you following up. I apologize for the hassle you had there
