### ISSUE TITLE
EC2 Wait

### ISSUE THREAD

**Issue by mqasim1983** [hashicorp/terraform#13915]
Hi there,

Is it possible to add wait feature launching ec2 instances.

**Story**
I have ElasticSearch Cluster running with 6 ec2 instances, I have updated the AMI and now it will update all the instances with new AMI (delete the old one and launch the new one with new AMI).
If I have wait feature while launching ec2 instance I can launch every instance after 10 to 15 minutes, every instance that is launch will be added in the cluster and have time to sync the data.

```
resource "aws_instance" "ec2" {
     ami = "${var.ami}"
     instance_type = "${var.instance_type}"
     subnet_id = "${element(split(",", var.subnet_id), count.index)}"
     count             = "${var.count}"
     iam_instance_profile = "${var.iam_instance_profile}"
     key_name = "${var.key_name}"
     vpc_security_group_ids = ["${split(",", var.vpc_security_group_ids)}"]
     monitoring = "${var.monitoring}"
     tags {
     Name = "${var.tags_name}-${element(split(",", var.availability_zone), count.index)}-${count.index}"
      Roles = "${var.tags_role}"
     }
     root_block_device {
      volume_size = "30"
     }

     lifecycle {
       create_before_destroy = true
       }

}
```

I tried adding local provisioner and it did not worked.

```
    provisioner "local-exec" {
    command = "sleep 600"
}
```

Any good suggestion? I need to update my cluster with new AMI's

**Comment by catsby** [comment]
Hey @mqasim1983  - 

I believe you have a couple of options here, some more ideal than others from a technical standpoint, and they may involve a few steps

1) I _believe_ the sleep behavior you’re looking for can be achieved via the `remote-exec` provisioner, not the `local-exec`. I may be mistaken though

2) I think duplicating `resource "aws_instance" "ec2"` to `resource "aws_instance" "ec2-next”` (naming is hard) would allow you to provision new instances in an identical configuration, but with the new AMI. Once those are up and synchronized, you can completely remove the old `resource "aws_instance" "ec2”`

3) This is more steps, but probably better long term: Modify your configuration to use an AutoScaling Group and Launch Configurations. Assuming your instances were managed by an ASG and their configuration specified in a Launch Configuration, you could achieve the same effect of # 2 above but with a more streamlined approach. First, update the Launch Configuration with the new AMI, and update the ASG double the desired count. Assuming the ASG is setup with a termination policy of “oldest launch configuration”, once the new instances are up and you believe they are sync’d, you can then reduce the desired count in the ASG. That will begin terminating the old instances that are using the old launch configuration. 

For # 3, I’ve posted an example configuration here: https://gist.github.com/catsby/ef64cc8f465752fa9adfc7d85659d781

Unfortunately Terraform doesn’t yet have a native solution for rolling deploys like this. It’s a feature we’d like to add, but we don’t have a cross-cloud solution for it at this time, and our cloud specific implementations are dependent on what their API allows. Here, AWS doesn’t expose a rolling options for us directly. 

Hopefully this helps!

**Comment by mqasim1983** [comment]
Thanks a lot, @catsby
