### ISSUE TITLE
A aws_api_gateway_usage_plan will not remain associated with aws_api_gateway_deployment when updated

### ISSUE THREAD

**Issue by joshdk** [hashicorp/terraform#13928]
### Terraform Version
[0.9.3](https://releases.hashicorp.com/terraform/0.9.3/)

### Affected Resources
- [aws_api_gateway_deployment](https://www.terraform.io/docs/providers/aws/r/api_gateway_deployment.html)
- [aws_api_gateway_usage_plan](https://www.terraform.io/docs/providers/aws/r/api_gateway_usage_plan.html)

#### API Gateway boilerplate

```hcl
resource "aws_api_gateway_rest_api" "api" {
  name = "Test API"
}

resource "aws_api_gateway_method" "api_method" {
  rest_api_id   = "${aws_api_gateway_rest_api.api.id}"
  resource_id   = "${aws_api_gateway_rest_api.api.root_resource_id}"
  http_method   = "GET"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "api_integration" {
  rest_api_id = "${aws_api_gateway_rest_api.api.id}"
  resource_id = "${aws_api_gateway_rest_api.api.root_resource_id}"
  http_method = "${aws_api_gateway_method.api_method.http_method}"

  type = "MOCK"
}
```

#### API Gateway deployment and usage plan

```hcl
resource "aws_api_gateway_deployment" "api_deployment" {
  rest_api_id = "${aws_api_gateway_rest_api.api.id}"
  stage_name  = "development"

  depends_on = [
    "aws_api_gateway_integration.api_integration",
  ]

  variables = {
    deploy_timestamp = "${timestamp()}"
  }
}

resource "aws_api_gateway_usage_plan" "api_usage" {
  name        = "My usage plan"
  description = "Unlimited usage plan"

  api_stages {
    api_id = "${aws_api_gateway_rest_api.api.id}"
    stage  = "${aws_api_gateway_deployment.api_deployment.stage_name}"
  }
}
```

### Debug Output
[joshdk/5002e96f954e89b4d720af9c4e799cdb](https://gist.github.com/joshdk/5002e96f954e89b4d720af9c4e799cdb)

### Expected Behavior
When the `aws_api_gateway_deployment` resource is updated, the `aws_api_gateway_usage_plan` resource should continue to be associated with the original api/stage.

### Actual Behavior
After the initial run of `terraform apply`, when the `aws_api_gateway_deployment` resource [is updated](https://gist.github.com/joshdk/5002e96f954e89b4d720af9c4e799cdb#file-step-2-first-reapply-L23), the `aws_api_gateway_usage_plan` resource no longer associated with any api/stage. When the `aws_api_gateway_deployment` resource [is updated again](https://gist.github.com/joshdk/5002e96f954e89b4d720af9c4e799cdb#file-step-3-second-reapply-L29), the `aws_api_gateway_usage_plan` resource [is once again associated with the original api/stage](https://gist.github.com/joshdk/5002e96f954e89b4d720af9c4e799cdb#file-step-3-second-reapply-L38-L39). This two-state cycle will continue indefinitely as long as you keep running `terraform apply`

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`
3. `terraform apply` 😄 

### References
Observed behavior is almost identical to [hashicorp/terraform #9376](https://github.com/hashicorp/terraform/issues/9376), but utilizes a newer resource type.

**Comment by sd-charris** [comment]
Any workarounds identified for this issue?

**Comment by sd-charris** [comment]
I was able to work around this buy using a bash script and provisioner for now..
`
resource "aws_api_gateway_usage_plan" "apigateway_usageplan" {
  depends_on = ["aws_api_gateway_deployment.apigateway_deployment"]
  name = "Sample API Usage Plan"

  api_stages {
    api_id = "${aws_api_gateway_rest_api.apigateway.id}"
    stage  = "${aws_api_gateway_deployment.apigateway_deployment.stage_name}"
  }
}


resource "null_resource" "apigateway_usageplan" {
  depends_on = ["aws_api_gateway_deployment.apigateway_deployment", "aws_api_gateway_usage_plan.apigateway_usageplan"]
  triggers {
    key = "${uuid()}"
  }
  provisioner "local-exec" {
    command = <<EOT
    AWS_ACCESS_KEY_ID=${var.terraform_aws_access_keyId}
    AWS_SECRET_ACCESS_KEY=${var.terraform_aws_secret_keyId} 
    aws apigateway update-usage-plan --usage-plan-id ${aws_api_gateway_usage_plan.apigateway_usageplan.id} --patch-operations '[{"op":"add","path":"/apiStages","value":"${aws_api_gateway_rest_api.apigateway.id}:0_0"}]' || echo "Stage already exists"
    EOT
  }
}


resource "null_resource" "apigateway_usageplan_key" {
  depends_on = ["aws_api_gateway_deployment.apigateway_deployment", "aws_api_gateway_usage_plan.apigateway_usageplan", "null_resource.apigateway_usageplan"]
  triggers {
    key = "${uuid()}"
  }
  provisioner "local-exec" {
    command = <<EOT
    AWS_ACCESS_KEY_ID=${var.terraform_aws_access_keyId}
    AWS_SECRET_ACCESS_KEY=${var.terraform_aws_secret_keyId} 
    aws apigateway delete-usage-plan-key --usage-plan-id ${aws_api_gateway_usage_plan.apigateway_usageplan.id} --key-id ${aws_api_gateway_api_key.apigateway_api_key.id} || echo "No usage plan exists"
    aws apigateway create-usage-plan-key --usage-plan-id ${aws_api_gateway_usage_plan.apigateway_usageplan.id} --key-type "API_KEY" --key-id ${aws_api_gateway_api_key.apigateway_api_key.id} --region us-west-2
    EOT
  }
}
`

**Comment by sd-charris** [comment]
I was able to work around this issue for now by calling the aws cli directly via null_resource provisioner commands..  Hope this helps anyone encountering the issue until its fixed.

```
resource "aws_api_gateway_usage_plan" "apigateway_usageplan" {
  depends_on = ["aws_api_gateway_deployment.apigateway_deployment"]
  name = "Sample API Usage Plan"

  api_stages {
    api_id = "${aws_api_gateway_rest_api.apigateway.id}"
    stage  = "${aws_api_gateway_deployment.apigateway_deployment.stage_name}"
  }
}


resource "null_resource" "apigateway_usageplan" {
  depends_on = ["aws_api_gateway_deployment.apigateway_deployment", "aws_api_gateway_usage_plan.apigateway_usageplan"]
  triggers {
    key = "${uuid()}"
  }
  provisioner "local-exec" {
    command = <<EOT
    AWS_ACCESS_KEY_ID=${var.terraform_aws_access_keyId}
    AWS_SECRET_ACCESS_KEY=${var.terraform_aws_secret_keyId} 
    aws apigateway update-usage-plan --usage-plan-id ${aws_api_gateway_usage_plan.apigateway_usageplan.id} --patch-operations '[{"op":"add","path":"/apiStages","value":"${aws_api_gateway_rest_api.apigateway.id}:${var.stage_name}"}]' || echo "Stage already exists"
    EOT
  }
}


resource "null_resource" "apigateway_usageplan_key" {
  depends_on = ["aws_api_gateway_deployment.apigateway_deployment", "aws_api_gateway_usage_plan.apigateway_usageplan", "null_resource.apigateway_usageplan"]
  triggers {
    key = "${uuid()}"
  }
  provisioner "local-exec" {
    command = <<EOT
    AWS_ACCESS_KEY_ID=${var.terraform_aws_access_keyId}
    AWS_SECRET_ACCESS_KEY=${var.terraform_aws_secret_keyId} 
    aws apigateway delete-usage-plan-key --usage-plan-id ${aws_api_gateway_usage_plan.apigateway_usageplan.id} --key-id ${aws_api_gateway_api_key.apigateway_api_key.id} || echo "No usage plan exists"
    aws apigateway create-usage-plan-key --usage-plan-id ${aws_api_gateway_usage_plan.apigateway_usageplan.id} --key-type "API_KEY" --key-id ${aws_api_gateway_api_key.apigateway_api_key.id} --region us-west-2
    EOT
  }
}
```

**Comment by alessandroben** [comment]
Any news about it? Actually to being able to deploy always new version of Lambda into the API Gateway Deployment Stage I have to re-create it every time... this is quite expensive in terms of time and also reliability because between two Infrastructure Releases API would be unavailable with Forbidden error returned by the missing association between Usage Plan and API Key.

**Comment by wieslawmlynarski** [comment]
Hi,
So I am facing the same problem right now, not only with the usage plan, but also "aws_api_gateway_method_settings".
So what I think happens is that when the stage gets deleted, it also removes assigned "usage plan"
and "settings".
I am trying out now to use a null resource like this
```
 resource "null_resource" "api_deployment" {
  depends_on = [
  ]
  triggers {
    uuid = "${uuid()}"
  }

  provisioner "local-exec" {
    command = <<EOF
      aws apigateway create-deployment --rest-api-id ${rest_api_id} --stage-name ${var.env}
    EOF
  }
}
```

This just deploys the gateway and dose not delete the stage.
By now testing multiple times apply does not the side effects.

**Comment by KristofferSmedlund** [comment]
Has anyone figured out a solution to this yet? My solution is as follows:

`
resource "aws_api_gateway_usage_plan" "myusageplan" {
  name = "usageplan"
  api_stages {
    api_id = "${aws_api_gateway_rest_api.myplan.id}"
    stage = "${aws_api_gateway_deployment.test.stage_name}"
  }
  description = "${var.versionAPIDep}"
}
`
I control when to deploy the api using a variable on the aws_api_gateway_deployment - when updating that variable the API is deployed. 
I added that variable as a description on the usage plan, so when the variable is updated (i.e the API is re-deployed) the usage plan stays the same.

**Comment by wieslawmlynarski** [comment]
> Has anyone figured out a real solution to this yet?
> I have sort of a hack but probably the best solution in this thread yet..
> My solution is as follows:
> 
> ```
> resource "aws_api_gateway_usage_plan" "myusageplan" {
>   name = "usageplan"
>   api_stages {
>     api_id = "${aws_api_gateway_rest_api.myplan.id}"
>     stage = "${aws_api_gateway_deployment.test.stage_name}"
>   }
>   description = "${var.versionAPIDep}"
> }
> ```
> I control when to deploy the api using a variable on the aws_api_gateway_deployment - when updating that variable the API is deployed.
> I added that variable as a description on the usage plan, so when the variable is updated (i.e the API is re-deployed) the usage plan stays the same.
> 
> This solution also keeps the aws_api_gateway_method_settings from disappearing somehow

Are you sure it creates new deployment? I did not test that my self. I just see from the code
[Patch operations](https://github.com/terraform-providers/terraform-provider-aws/blob/bb30267b73270b899f7826a0ca93622756844535/aws/resource_aws_api_gateway_deployment.go#L143) That it only updates the description.
So if you add a new resource to your api gateway will it get populated to the stage?

**Comment by apparentlymart** [comment]
Hi all,

Since the AWS provider is no longer developed in this repository, this issue was migrated to terraform-providers/terraform-provider-aws#714. Please continue the discussion over there in order to keep the log consolidated.
