### ISSUE TITLE
backend consul problem with address flag

### ISSUE THREAD

**Issue by kennyg** [hashicorp/terraform#1392]
with v0.3 I used to upload the state with:

terraform remote -backend=consul -address=consulhost:8500 -path=release_engineering/terraform/terraform-docker

now with v0.4 and the new remote config command:
terraform remote config -backend='consul' -address='consulhost:8500' -path='release_engineering/terraform/terraform-docker'

I get an error with the help text:
Error parsing CLI flags: flag provided but not defined: -address

**Comment by hairmare** [comment]
I just ran into this as well. You need to specify the ``-address`` flag as follows.

```
-backend-config="address= consulhost:8500"
```

**Comment by kennyg** [comment]
I tried what @hairmare suggested and the remote command didn't recognize the -path argument. I added -backend-config='path=release_engineering/terraform/terraform-docker' and it errors with:
Error initilizing remote state: <nil>
It seems I should migrate the 0.3 remote consul state to local storage before upgrading to 0.4 and setting up the remote config.

**Comment by phinze** [comment]
Thanks for the report @kennyg - @mitchellh can you pick this up in your remote-state issue sweep?

**Comment by mitchellh** [comment]
Fixed
