### ISSUE TITLE
Feature Request: Support Azure User Logins

### ISSUE THREAD

**Issue by cmelanson** [hashicorp/terraform#13939]
Currently the AzureRM provider only supports authenticating using a Service Principal. This is problematic for organizations which want to be able to audit who performed an operation, as users essentially need to share an account.

The Azure command line utilities allow you to login by running "az login" which instructs the user to to go https://aka.ms/devicelogin with a code and authenticate to Azure AD (and potentially an on-premise ADFS/SAML provider).

I am requesting that Terraform be able to read the Azure CLI tokens, or implement a process similar to "az login", and be able to use those credentials instead of being forced to use a Service Principal.

Thank you,
Corey Melanson

**Comment by Starefossen** [comment]
This is just what I need for my situation!
