### ISSUE TITLE
Deleteing an ASG in the console and then running terraform can break.

### ISSUE THREAD

**Issue by bobtfish** [hashicorp/terraform#1393]
If you delete an ASG which had previously been created by terraform in the console, and then try to delete it with terraform, then terraform doesn't pay attention to the current state before trying to drain the ASG:

    terraform_remote_state.vpc: Refreshing state... (ID: 2015-04-05 09:49:55.922430917 +0000 UTC)
    module.kubernates.aws_launch_configuration.kubernates-master: Refreshing state... (ID: terraform-4aBoZdYf5dPuY2uzNJMN5_D15OM=)
    module.kubernates.aws_launch_configuration.kubernates-node: Refreshing state... (ID: terraform-MLIiQ2t6ts2E2SnPRQjI8H8bK-Y=)
    module.kubernates.aws_autoscaling_group.kubernates-master: Refreshing state... (ID: kubernates-master)
    module.kubernates.aws_autoscaling_group.kubernates-node: Refreshing state... (ID: kubernates-node)
    module.kubernates.aws_launch_configuration.kubernates-node: Destroying...
    module.kubernates.aws_launch_configuration.kubernates-master: Destroying...
    module.kubernates.aws_autoscaling_group.kubernates-master: Destroying...
    module.kubernates.aws_autoscaling_group.kubernates-node: Destroying...
    Error applying plan:

    1 error(s) occurred:

    * 2 error(s) occurred:

    * Error setting capacity to zero to drain: The AutoScaling group may not be modified while it is pending delete
    * Error setting capacity to zero to drain: The AutoScaling group may not be modified while it is pending delete

**Comment by catsby** [comment]
Curious, this sounds like a timing issue. It sounds like you deleted it in the console, and then also deleted it in Terraform, if for nothing else but to remove it from the state, is that correct?

Assuming that, it's likely a timing issue. The ASG was probably in mid-drain or delete when we issued the API call. If that's the case, then we need to simply tolerate that situation better, correct? E.g., if the state is "delete in progress", either poll and wait for it to disappear, or simply remove it from the state and carry on, correct?

Thanks for opening the issue!

**Comment by bobtfish** [comment]
Yes, thanks! Your description is exactly what I believe is happening, and either of the fixes you propose would work for me.

**Comment by catsby** [comment]
Hey @bobtfish – the error is coming from here:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_autoscaling_group.go#L350

We try to tell the ASG to drain, but it's already being deleted, so it's marked as "unmodifiable" essentially. Because you _know_ that's happening, since you issued the command in the console, I'm hesitant to add code to poll here. For updating the local state, a `terraform refresh` is sufficient to remove the ASG, once it's actually deleted.

**Comment by catsby** [comment]
We discussed this briefly and decided against adding additional code here. Let me know if you have compelling reasons for us to reconsider.

Thanks for opening the issue!
