### ISSUE TITLE
Feature request: Ability to configure S3 buckets based on variables

### ISSUE THREAD

**Issue by zenitraM** [hashicorp/terraform#13938]
We want to create a module to be able to reuse some specifics about the way we create S3 buckets.
However, there is no way to programatically define the existence of resource object fields (even just https://github.com/hashicorp/terraform/issues/7034 could work at a certain extent) to be able to, for example, toggle on and off the replication policy of a bucket depending on an input variable:

```
resource "aws_s3_bucket" "bucket" {
  provider = "aws.central"
  bucket   = "tf-test-bucket-12345"
  acl      = "private"
  region   = "eu-central-1"

  versioning {
    enabled = true
  }

  replication_configuration {
    count = "${var.replication_enabled == "true" ? 1 : 0}" # this could be an option but will not work
    role = "${aws_iam_role.replication.arn}"

    rules {
      id     = "foobar"
      prefix = "foo"
      status = "Enabled"

      destination {
        bucket        = "${aws_s3_bucket.destination.arn}"
        storage_class = "STANDARD"
      }
    }
  }
}
```
or add multiple rules depending on an input array.

A way to solve this could be to add a different attachment resources for configurations applied to S3 buckets, i.e: `aws_s3_replication_configuration` - they are, after all, a [separate API](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTreplication.html).

Same applies to lifecycle policies and logging, for example - you cannot modularize a bucket conditionally having them without making separate modules for buckets with/without them.

**Comment by gnsallman** [comment]
+1

**Comment by craigknott** [comment]
+1

**Comment by nandac** [comment]
+1
