### ISSUE TITLE
Feature Request: Include AWS Cloudtrail ReadWriteType

### ISSUE THREAD

**Issue by nwalke** [hashicorp/terraform#13949]
### Affected Resource
- aws_cloudtrail

### Use Case
I don't care about read events in some accounts, only write events.

[The AWS Go SDK provides ReadWriteType](https://github.com/aws/aws-sdk-go/blob/master/models/apis/cloudtrail/2013-11-01/api-2.json#L402) for Cloudtrail trails, it'd be nice to configure that in Terraform.

**Comment by stack72** [comment]
FYI, this relates to this http://docs.aws.amazon.com/cli/latest/reference/cloudtrail/put-event-selectors.html
