### ISSUE TITLE
Terraform fails to notice when a Consul catalog entry has been removed

### ISSUE THREAD

**Issue by blalor** [hashicorp/terraform#13944]
### Terraform Version

Terraform v0.9.3

### Affected Resource(s)

- consul_catalog_entry

### Terraform Configuration Files

```hcl
provider "consul" {}

resource "consul_catalog_entry" "redis" {
    node = "redis"
    address = "127.0.0.2"
    
    service = {
        name = "my-redis"
        port = "6379"
        tags = ["master"]
    }
}
```

### Debug Output

Log for 2nd `terraform apply`: [apply.log.txt](https://github.com/hashicorp/terraform/files/956136/apply.log.txt)

Console output:

```
$ TF_LOG=TRACE TF_LOG_PATH=apply.log.txt terraform apply
consul_catalog_entry.redis: Refreshing state... (ID: redis-127.0.0.2-[my-redis])

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Expected Behavior

Terraform should have noticed that the catalog entry was missing and recreated.

### Actual Behavior

Nuttin', honey.

### Steps to Reproduce

0. `consul agent -dev` in terminal 0
1. `terraform apply` in terminal 1
2. confirm service registered: `curl -sfS localhost:8500/v1/catalog/service/my-redis`
3. stop consul agent in terminal 0
4. `consul agent -dev` in terminal 0 (restarting it)
5. confirm service missing: `curl -sfS localhost:8500/v1/catalog/service/my-redis`
6. `terraform apply` in terminal 1
7. confirm service still missing: `curl -sfS localhost:8500/v1/catalog/service/my-redis`

**Comment by horalstvo** [comment]
We are also affected by this.
