### ISSUE TITLE
Deleting route53 zones in the console can break terraform runs

### ISSUE THREAD

**Issue by bobtfish** [hashicorp/terraform#1395]
I created a hosted zone with a record in it with terraform, then went to the console and removed it (expecting terraform to recreate it), however I now get this output:

    aws_route53_zone.mesos: Refreshing state... (ID: Z3LNYFRQELU092)
    module.mesos.dns.aws_route53_zone.mesos: Refreshing state... (ID: ZMSQHHTU9HS8B)
    Error refreshing state: 2 error(s) occurred:

    * The specified hosted zone does not exist.
    * 1 error(s) occurred:

    * 1 error(s) occurred:

    * 1 error(s) occurred:

     * The specified hosted zone does not exist.

**Comment by catsby** [comment]
I believe this is a duplicate of #1383, and should also be fixed by #1384. Does that sound right?

**Comment by bobtfish** [comment]
Yep, sounds right! I'm going to close this and I'll update to master and retry, thanks!
