### ISSUE TITLE
Crash: refreshing state on a Route53 record resource causes a Go panic

### ISSUE THREAD

**Issue by ixmatus** [hashicorp/terraform#13958]
### Terraform Version
```shell
$ terraform --version
Terraform v0.9.3
```

### Affected Resource(s)
- Route53

### Terraform Configuration Files
I'd have to get permission to release our configuration files.

### Debug Output
I'd have to get permission to release this information.

### Panic Output
https://gist.github.com/ixmatus/f9a14b48d8e9cfef44c3c5cf40965546

### Expected Behavior
I expected `terraform plan` to update its state and give me a new plan for some changes I made to security groups.

### Actual Behavior
It began updating its state and panicked.

### Steps to Reproduce
1. `terraform apply` a fresh configuration that creates a record within a public hosted Route53 zone
2. `terraform plan` (or `apply`)

### Important Factoids
Nothing unusual.

**Comment by jbardin** [comment]
Hi @ixmatus,

Thanks for the bug report!
This bug was recently fixed, and will be included in the next terraform point release.

**Comment by ixmatus** [comment]
@jbardin thanks!
