### ISSUE TITLE
Feature Request: Local File Resource

### ISSUE THREAD

**Issue by gargath** [hashicorp/terraform#13968]
As part of a terraform project to create a Kubernetes Cluster, I have the requirement to render out some templates like `kubeconfig` to the machine executing terraform.

Currently the only way to do this seems to be to use a `null_resource` with `local-exec` provisioner, running something like `echo ${template.rendered} > rendered_file`.
This is clunky and requires the use of a provisioner otherwise absent from my project.

The alternative I am currently using is to create an `aws_s3_bucket_object` instead and manually downloading that post-apply:

```
data "template_file" "kubeconfig" {
  template = "${file("template/kubeconfig")}"

  vars {
    cluster_name   = "${var.cluster_name}"
  }
}

resource "aws_s3_bucket_object" "kubeconfig" {
  bucket       = "my_bucket"
  key          = "${var.cluster_name}/kubeconfig"
  content      = "${data.template_file.kubeconfig.rendered}"
}

output "kubeconfig" {
  value = "kubeconfig uploaded to s3://my_bkcuet/${var.cluster_name}/kubeconfig"
}
```

It would be great if Terraform provided a `local_file` resource that worked similar to `aws_s3_bucket_object`, but simply wrote the contents to a local path instead.

**Comment by dominik-lekse** [comment]
You can check out the file provisioner (https://www.terraform.io/docs/provisioners/file.html) with content argument.

**Comment by dominik-lekse** [comment]
Since I am also researching on this functionality, it will be part of the upcoming Terraform release (see https://github.com/hashicorp/terraform/pull/12757).

**Comment by gargath** [comment]
To be clear, I am _not_ looking for the `file` provisioner.
For one thing it's a provisioner, requiring another resource to run against and for another, I do not think it can write files to the _local_ machine, i.e. the machine running terraform.

**Comment by dasch** [comment]
@gargath https://github.com/hashicorp/terraform/pull/12757 implements `localfile`, which sounds like what you're after.

**Comment by gargath** [comment]
@dasch, @dominik-lekse  Yes, sorry, must've missed that. Closing this and watching #12757 instead. Thanks for pointing it out.
