### ISSUE TITLE
data resource for aws_acm_certificate doesn't support filters

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform#13963]
### Terraform Version
0.9.3

### Affected Resource(s)
- aws_acm_certificate

### Terraform Configuration Files
```hcl
# query AWS Certificate Manager for the SSL Cert's ARN
data "aws_acm_certificate" "san_cert" {
  domain = "${var.san_cert_domain}"
  filter {
    name = ""tag:Environment"
    values = ["${var.environment}"]
  }
}
```

### Expected Behavior
terraform returns the data for the certificate tagged for the particular environment

### Actual Behavior
terraform stated that filter is not recognized

### Steps to Reproduce
set `environment` to match a tag associated to a ssl certificate that has already been imported into AWS Cert Manager. then `terraform apply`

**Comment by stack72** [comment]
Hi @haidangwa 

Thanks for the feature request here. unfortunately, the AWS SDK only allows us to retrieve certificates by either ARN or status'

* http://docs.aws.amazon.com/cli/latest/reference/acm/describe-certificate.html - allows filtering by ARN
* http://docs.aws.amazon.com/cli/latest/reference/acm/list-certificates.html - allows filtering by status'

Sorry about this - but this is something that AWS would need to support before we can

Thanks

Paul
