### ISSUE TITLE
Terraform does not pick up out of band Google CloudSQL instance tier changes

### ISSUE THREAD

**Issue by pdecat** [hashicorp/terraform#13969]
### Terraform Version

```
# terraform -v
Terraform v0.9.3
```

### Affected Resource(s)

- google_sql_database_instance

### Terraform Configuration Files

```hcl
provider "google" {
  credentials = "${file("account.json")}"
  project     = "myproject"
  region      = "europe-west1"
}

resource "google_sql_database_instance" "master" {
  name = "cloudsql-master"

  region = "europe-west1"

  database_version = "MYSQL_5_7"

  settings {
    location_preference {
      zone = "europe-west1-b"
    }

    tier              = "db-n1-standard-2"
    activation_policy = "ALWAYS"

    disk_type       = "PD_SSD"
    disk_size       = "10"
    disk_autoresize = "true"

    backup_configuration {
      binary_log_enabled = "true"
      enabled            = "true"
      start_time         = "12:00"
    }
  }
}
```

### Expected Behavior

After the instance was created with the above HCL configuration and its tier upgraded to `db-n1-standard-4` through the Google Cloud console or gcloud CLI,
a `terraform plan` should pick up the out of band change:

```
~ google_sql_database_instance.master
    settings.0.tier: "db-n1-standard-4" => "db-n1-standard-2"

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

The terraform plan does not pick up the out of band change:

```
# terraform plan -target google_sql_database_instance.master
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_sql_database_instance.master: Refreshing state... (ID: cloudsql-master)
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

### Steps to Reproduce

1. create a CloudSQL instance with the HCL conf provided above.
2. upgrade the instance's tier to `db-n1-standard-4` through the Google Cloud console or gcloud CLI.
3. run `terraform plan` on the same HCL configuration.

### Note

Updating the HCL configuration above to match the actual CloudSQL tier `db-n1-standard-4` shows the same symptom: the plan does not detect the out of band change and predicts an update to the instance's tier:

```
# terraform plan -target google_sql_database_instance.master
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_sql_database_instance.master: Refreshing state... (ID: cloudsql-master)
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ google_sql_database_instance.master
    settings.0.tier: "db-n1-standard-2" => "db-n1-standard-4"


Plan: 0 to add, 1 to change, 0 to destoy.
```

**Comment by pdecat** [comment]
Workaround:

1. `terraform state pull > terraform.tfstate.tmp`
2. patch state
3. `terraform state push terraform.tfstate.tmp`

**Comment by rileykarson** [comment]
This issue might be bigger than just "tier" changes - I had "disk_autoresize" fail to update as well when I changed it, to see if another value in the "settings" block updated properly.

When inspecting the Read method of the resource, it looks like the Set method of the schema is called with expected values, but these values are not updating properly. If I use a new object with only the tier field set, I can see it updating "terraform plan" as expected. When I copy every key/value pair into my new object, it suddenly fails to update again.
