### ISSUE TITLE
aws_route not setting name field

### ISSUE THREAD

**Issue by cmcornejocrespo** [hashicorp/terraform#13984]
### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
aws_route

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "${var.aws_region}"
}
...
# Grant the VPC internet access on its main route table
resource "aws_route" "internet_access" {
  name                   ="aws_route-MY-RANDOM-NAME"
  route_table_id         = "${aws_vpc.demo.main_route_table_id}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${aws_internet_gateway.demo.id}"
}
```

### Debug Output
* aws_route.internet_access: : invalid or unknown key: name

### Expected Behavior
It should have created a name for the aws route entry
### Actual Behavior
invalid or unknown key: name

### Steps to Reproduce
1. `terraform apply`
2. Inpect the console output

**Comment by catsby** [comment]
Hey @cmcornejocrespo – the `aws_route` resource does not have a `name` attribute. The resource does not include one, and the API does not provide any `name` attribute that I can see here: [
AWS Documentation » Amazon EC2 » API Reference » Actions » CreateRoute
](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRoute.html)

Are you seeing other documentation that suggest this is possible? 

- https://www.terraform.io/docs/providers/aws/r/route.html

**Comment by cmcornejocrespo** [comment]
Hi @catsby, thanks for the quick response.
I was under that impression, thanks!
