### ISSUE TITLE
Terraform apply failed to scale down number of instances for an azurerm_virtual_machine_scale_set 

### ISSUE THREAD

**Issue by matthewbrahms** [hashicorp/terraform#13997]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.9.3

### Affected Resource(s)
- azurerm_virtual_machine_scale_set

### Terraform Configuration Files
```hcl

# Resource Group
variable "location" {
  default = "South Central US"
}

# CS-specific
variable "environment" {
  default = "cs-hackathon"
}

# Rancher-specific
variable "rancher_master_count" {
  default = 2
}

variable "rancher_worker_count" {
  default = 4
}
```

### Debug Output
Typical panic with message asking to submit crash.log file

### Panic Output
https://gist.github.com/matthewbrahms/1475f67ff34965d26bf65175185a0f43

### Expected Behavior
Was sizing the Azure VM Scale Set from 4 servers to 3 servers. Changed the variable in the variables.tf file and then "terraform plan" it and it showed correctly.

```
variable "rancher_worker_count" {
  default = 3
}
```
### Actual Behavior
Ran the "terraform apply" command and it paniced.

### Steps to Reproduce
1. Decrement the number of desired scaleset servers by one.
2. terraform plan
3. terraform apply

### Important Factoids
Running from newest version of MacOS.

**Comment by tombuildsstuff** [comment]
Hi @matthewbrahms

Thanks for reporting this issue :)

Looking at the crash log - I believe this crash has been fixed in Terraform 0.9.4 which was released yesterday. Would it be possible for you to upgrade and confirm if this has been fixed?

Thanks :)

**Comment by matthewbrahms** [comment]
@tombuildsstuff Thanks, Tom...it works when going to 0.9.4!

**Comment by tombuildsstuff** [comment]
@matthewbrahms awesome - thanks for letting us know :)
