### ISSUE TITLE
Creation of aws_dms_replication_instance resource exits with ResourceNotReady after 10 minutes

### ISSUE THREAD

**Issue by dmariassy** [hashicorp/terraform#13996]
### Terraform Version
0.8.8.

### Affected Resource(s)
- aws_dms_replication_instance

### Terraform Configuration Files
```hcl
resource "aws_dms_replication_instance" "dms_replication_instance" {
  
  allocated_storage            = "50"
  apply_immediately            = "true"
  auto_minor_version_upgrade   = "true"
  kms_key_arn                  = "${aws_kms_key.kms_key.arn}"
  multi_az                     = true
  preferred_maintenance_window = "sun:10:30-sun:14:30"
  publicly_accessible          = "false"
  replication_instance_class   = "dms.t2.micro"
  replication_instance_id      = "${var.team}-${var.project}-${var.replication_task}-instance-${element(split("-", var.region), 1)}-${var.environment}"
  replication_subnet_group_id  = "${aws_dms_replication_subnet_group.dms_replication_subnet_group.replication_subnet_group_id}"

  tags {
    Name = "${var.team}-${var.project}-${var.replication_task}-${element(split("-", var.region), 1)}-${var.environment}"
    Environment = "${var.environment}"
    Terraform = "true"
  }

  vpc_security_group_ids = ["${aws_security_group.security_group.id}"]

}
```

### Expected Behavior
Successful creation of the resource and the execution of subsequent provisioning tasks.

### Actual Behavior
Terraform exits:
- without provisioning the remaining resources 
- without updating the state file with the created replication instance's data (even though this is partially available at this point).
Due to the out-of-sync state file, the next plan will assume that the replication instance has not yet been created in the real world, will attempt to create it, which will yield a "conflicting names" error.

### References
- GH-12206

**Comment by atrepca** [comment]
Had the same issue and found a workaround: set `multi_az = false` which will provision the replication instance in less than 10 minutes, enable multi_az via the AWS console, then set `multi_az = true` in Terraform too.
