### ISSUE TITLE
Outputs aren't updated on failed provisioner

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#13993]
### Terraform Version
Terraform v0.9.4-dev (381adca0af66650da71729a206c1f882e38cc9c4+CHANGES)

### Affected Resource(s)
- core?

### Step to Reproduce

Start with

```hcl
output "foo" {
  value = "bar"
}
```

Run `terraform plan` and `terraform apply`. Run `terraform output` to get the output.

Update config to:

```hcl
output "foo" {
  value = "new bar"
}

resource "null_resource" "foo" {
  provisioner "local-exec" {
    inline = [
      "exit 1",
    ]
  }
}
```

Run `terraform apply`. Command fails (as expected). But run `terraform output` - it still outputs "bar" instead of "new bar".

Now, I know _why_ this is happening. I don't think outputs are saved to the state until the very end of an apply. However, it's misleading when you are doing this:

```hcl
resource "aws_instance" "example" {
  count = 5
  # ...

  provisioner "remote-exec" { ... }
}

output "ips" {
  value = ["${aws_instance.example.*.public_ip}"]
}
```

Because if you make a change to the provisioner, it all fails, but the outputs will contain the _old_ IP addresses.

I'll admit it's a very strange use case, but it cost me a few hours today of debugging before I realized that Terraform was giving me the wrong IPs 😦 .

**Comment by apparentlymart** [comment]
I definitely saw this before too... another one under the heading of "outputs get updated too late". :(

There's a collection of issues around this with the same root cause, but I'm on my phone right now so can't easily dig them up. I will try to circle back here and link these together once I get back to my computer.
