### ISSUE TITLE
Rackspace: Authentication failed

### ISSUE THREAD

**Issue by eugenetaranov** [hashicorp/terraform#13998]
Hi,

rackspace authentication fails with no additional details. Username/password are working 100% as confirmed by using supernova and gophercloud. Can you please look?

Version:
Terraform v0.9.4-dev (1024976cdf36f70b4887a7b3c7926d7be62cf93b)

```hcl
provider "openstack" {
  user_name   = ""
  tenant_name = ""
  password    = ""
  auth_url    = "https://identity.api.rackspacecloud.com/v2.0/"
}

resource "openstack_blockstorage_volume_v2" "vol_test" {
  region      = "LON"
  name        = "vol_test"
  size        = 3
}
```

### Expected Behavior
Output build plan

### Actual Behavior
```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

2017/04/26 18:25:11 [ERROR] root: eval: *terraform.EvalConfigProvider, err: Authentication failed
2017/04/26 18:25:11 [ERROR] root: eval: *terraform.EvalSequence, err: Authentication failed
2017/04/26 18:25:11 [ERROR] root: eval: *terraform.EvalOpFilter, err: Authentication failed
2017/04/26 18:25:11 [ERROR] root: eval: *terraform.EvalSequence, err: Authentication failed
2017/04/26 18:25:11 [TRACE] [walkPlan] Exiting eval tree: provider.openstack
2017/04/26 18:25:11 [DEBUG] dag/walk: upstream errored, not walking "openstack_blockstorage_volume_v2.vol_test"
Error running plan: 1 error(s) occurred:

* provider.openstack: Authentication failed
```

### Steps to Reproduce
`terraform plan`

### Important Factoids
Rackspace

Thanks

**Comment by jtopjian** [comment]
Hello,

Just a heads up that the OpenStack provider is not officially supported on Rackspace clouds. There are some notes [here](https://www.terraform.io/docs/providers/openstack/index.html#rackspace-compatibility) on past success, but it's possible that something has changed.

You might be able to see the cause of authentication failure by enabling the OpenStack debugging output:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

Feel free to add the scrubbed output to a gist and I'd be happy to look it over. 

> Username/password are working 100% as confirmed by using supernova and gophercloud

When you say Gophercloud, do you mean the older `rackspace/gophercloud` repository or the newer `gophercloud/gophercloud` repo?

**Comment by eugenetaranov** [comment]
Hello @jtopjian ,

here is the gist attached https://gist.github.com/eugenetaranov/8e63d0af024f974ef9c3c88cc652f322

By gophercloud I mean rackspace/gophercloud.

Thanks

**Comment by jtopjian** [comment]
@eugenetaranov Thanks.

`rackspace/gophercloud` is no longer used. It's quite possible that a lot of the stuff that made that version of Gophercloud work with Rackspace was removed in the newer `gophercloud/gophercloud`.

From reviewing the logs you posted, it doesn't look like you're specifying a username or password:

```
2017/04/26 19:19:59 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/04/26 19:19:59 [DEBUG] OpenStack Request Body: {
2017/04/26 19:19:59 [DEBUG] plugin: terraform:   "auth": {
2017/04/26 19:19:59 [DEBUG] plugin: terraform:     "passwordCredentials": {
2017/04/26 19:19:59 [DEBUG] plugin: terraform:       "password": "",
2017/04/26 19:19:59 [DEBUG] plugin: terraform:       "username": ""
2017/04/26 19:19:59 [DEBUG] plugin: terraform:     }
2017/04/26 19:19:59 [DEBUG] plugin: terraform:   }
2017/04/26 19:19:59 [DEBUG] plugin: terraform: }
```

Can you confirm if you are specifying a username/password and you just removed them from the gist?

**Comment by eugenetaranov** [comment]
@jtopjian sorry, I had to mark it better :) yes, they were not empty, I cleaned up afterwards.

Thanks for the pointing out at gophercloud/gophercloud.
I have tried it just now, looks like they do not accept APIKey in gophercloud.AuthOptions but with Password I am getting "Authentication failed". So it might be related .. or I am using wrong options https://gist.github.com/eugenetaranov/2b0dddea8639559f4def47f9673c2db3

**Comment by jtopjian** [comment]
@eugenetaranov No worries - I just wanted to make sure :)

When you're specifying a password, are you using the API Key for the value? If so, can you try specifying your Rackspace password? Unfortunately I'm not sure exactly which password you should use, but if you have _some_ type of password that is different than an API key, give that a shot.

**Comment by eugenetaranov** [comment]
@jtopjian I have got new user provisioned and its credentials worked just fine (username and password, not an api key), I am not sure whether it was api key or password for the old user.

Thank you very much for your help, I think it can be closed now.

**Comment by jtopjian** [comment]
@eugenetaranov That's awesome news. Thank you as well for working through this. It's good to know that the OpenStack provider still works with Rackspace to a certain extent 😄
