### ISSUE TITLE
Feature Request: Terraform version requirements in configuration files

### ISSUE THREAD

**Issue by solarce** [hashicorp/terraform#1400]
I'm starting to work on updating the [terraform community modules](https://github.com/terraform-community-modules/) to take advantage of the new [split function](http://www.terraform.io/docs/configuration/interpolation.html#split_delim_string_), but this will leave users on older versions unable to use the latest versions of these modules.

Being able to put some kind of version constraint as a comment in the configuration file could be useful, as new functions are added in newer versions.

I'm going to do my best to call out the version requirement in the documentation but an additional safeguard would also help.

**Comment by radeksimko** [comment]
Good idea :+1: , that would be helpful especially in these early days when the API is still changing rapidly, although it goes a bit against the whole Golang-concept which forces all developers to "live on the edge" (as you cannot specify versions in `import "github.com/..."`).

I wouldn't want to see people freezing everything forever and complaining about old bugs that have been fixed x releases after. Also I believe that most of the changes are/should be backward-compatible (unless these are bugfixes).

Forcing everyone to live on the edge has the advantage that community will give feedback early, which is important. I understand that not everyone (especially in enterprise corporations) wants to live on the edge though.

**Comment by radeksimko** [comment]
In fact these are two different problems

1. using new version of Terraform on older codebase
2. using older version of Terraform on new codebase

(2) should be definitely addressed, but I'd be careful about (1) as mentioned above.

**Comment by neurogenesis** [comment]
:+1:

There are also more practical reasons for specifying versions. The main one is to ensure that all engineers working against the same terraform configuration files are forced to use a minimum version of terraform. I'm guessing state files include data format / API version (similar to vagrant configuration files).

**Comment by gtmtech** [comment]
:+1:   yes I'd like to see this as we are constantly upgrading across a medium size team and wanting to avert problems caused by bugs in earlier versions

**Comment by aerickson** [comment]
This would be a great feature. Please add it.

**Comment by mitchellh** [comment]
Done in PR #10080 :D

**Comment by solarce** [comment]
@mitchellh thank you! this is awesome to see happen
