### ISSUE TITLE
aws_ebs_volume Tags not working/removed by aws_instance resource

### ISSUE THREAD

**Issue by eriksw** [hashicorp/terraform#14003]
After upgrading to Terraform 0.9.4, terraform removed the Name tags I had on some aws_ebs_volume resources.

### Terraform Version
0.9.4

### Affected Resource(s)
- aws_instance
- aws_ebs_volume

### Terraform Configuration Files
```hcl
resource "aws_instance" "cyanite-cassandra" {
  count         = "${var.cyanite-cassandra-count}"
  ami           = "${data.aws_ami.ubuntu-xenial.id}"
  instance_type = "t2.medium"

  # ebs_optimized          = true
  subnet_id = "${element(aws_subnet.private.*.id, count.index)}"

  vpc_security_group_ids = [
    "${aws_security_group.cyanite-cassandra.id}",
  ]

  iam_instance_profile = "${aws_iam_instance_profile.cyanite-cassandra.name}"
  user_data            = "${element(data.template_cloudinit_config.cyanite-cassandra.*.rendered, count.index)}"
  key_name             = "${aws_key_pair.default.key_name}"

  tags {
    Name = "${format("cyanite-cassandra-%d", count.index + 1)}"
    fqdn = "${format("cyanite-cassandra-%d.%s", count.index + 1, aws_route53_zone.beach.name)}"
  }

  lifecycle {
    ignore_changes = [
      "ami",
      "user_data",
    ]
  }
}

resource "aws_ebs_volume" "cyanite-cassandra-data" {
  count             = "${var.cyanite-cassandra-count}"
  availability_zone = "${element(aws_subnet.private.*.availability_zone, count.index)}"
  size              = 200
  encrypted         = true
  type              = "gp2"

  tags {
    Name = "${format("cyanite-cassandra-%d data", count.index + 1)}"
  }
}

resource "aws_volume_attachment" "cyanite-cassandra-data" {
  count       = "${var.cyanite-cassandra-count}"
  device_name = "/dev/xvdf"
  volume_id   = "${element(aws_ebs_volume.cyanite-cassandra-data.*.id, count.index)}"
  instance_id = "${element(aws_instance.cyanite-cassandra.*.id, count.index)}"

  lifecycle {
    # Needed to work around terraform weirdness. When replacing an instance, taint the particular attachment too.
    ignore_changes = [
      "instance_id",
      "volume_id",
    ]
  }
}
```

### Expected Behavior
Terraform should have left the Name tags on the ebs_volumes in place.

If the Name tag is missing from the volume, `terraform plan` should generate a plan to add it.

### Actual Behavior
Terraform removed the Name tags on the ebs_volumes.
(This showed as being part of the aws_instance resource, not the aws_ebs_volume resource.)

Running `terraform plan` generates an empty plan even though the EBS volumes no longer have a Name tag.

### References

Possibly related to #13945

**Comment by eriksw** [comment]
I do have a trace log of the `terraform apply` where it removed the tags from the volumes, but this should be easy to replicate in a toy scenario.

**Comment by eriksw** [comment]
Discovery:

After reverting to terraform 0.9.3 (and rolling back the state file), running 'terraform plan' still doesn't generate a plan to restore the Name tag on the aws_ebs_volume.

**Comment by stack72** [comment]
Hi @eriksw 

I have found the issue here and am fixing this as we speak :)

Paul
