### ISSUE TITLE
Support backup settings for Premium azurerm_redis_cache

### ISSUE THREAD

**Issue by cberner** [hashicorp/terraform#14016]
### Terraform Version
0.9.3

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_redis_cache

### Feature Request
I would like to be able to use the data persistence offered by Premium tier Azure Redis Cache. However, this is not available via Terraform. I have included some relevant documentation from the Azure reference pages.

### References
- https://docs.microsoft.com/en-us/rest/api/redis/redis#Redis_Create See "rdb-backup-enabled", "rdb-storage-connection-string", and "rdb-backup-frequency" settings.
- https://docs.microsoft.com/en-us/azure/redis-cache/cache-how-to-premium-persistence

**Comment by tombuildsstuff** [comment]
Hi @cberner 

Thanks for opening this issue.

I've taken a quick look and unfortunately it's not available in the Azure SDK at present - so I've [opened an issue on the Azure SDK for Go repository](https://github.com/Azure/azure-sdk-for-go/issues/598) - so that we can support this in the future :)

Thanks! :)

**Comment by tombuildsstuff** [comment]
:wave: @cberner

Just to provide an update about this issue: [I've heard back from the Azure Redis team](https://github.com/Azure/azure-sdk-for-go/issues/598#issuecomment-306939803) - apparently it's possible to configure Redis Backups using keys in the `redis_configuration` section:

```
It is intended to be possible via the 'redisConfiguration' property of the redis cache:

See the note on https://docs.microsoft.com/en-us/rest/api/redis/redis

"Few possible keys: rdb-backup-enabled,rdb-storage-connection-string,rdb-backup-frequency,maxmemory-delta,maxmemory-policy,notify-keyspace-events,maxmemory-samples,slowlog-log-slower-than,slowlog-max-len,list-max-ziplist-entries,list-max-ziplist-value,hash-max-ziplist-entries,hash-max-ziplist-value,set-max-intset-entries,zset-max-ziplist-entries,zset-max-ziplist-value etc."
```

Currently, each field in the Redis Configuration is [listed explicitly in Terraform](https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resource_arm_redis_cache.go#L80) - so this will need a code change in Terraform to support this, but it looks like this should be relatively quick to add :)

Thanks!

**Comment by cberner** [comment]
👍
