### ISSUE TITLE
Incorrect Argument Reference section in docs for the Docker provider

### ISSUE THREAD

**Issue by dublx** [hashicorp/terraform#1402]
Hi,
In https://www.terraform.io/docs/providers/docker/r/image.html the Example usage block has the `image` property but the Argument Reference section below it says `name` is required. 
Shouldn't it be `image - (Required) The name of the Docker image, including any tags.` instead? 

Tks!

**Comment by phinze** [comment]
@dublx thanks for this!

The docs are actually stored [in this repository](https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/docker/r/image.html.markdown). Are you interested in heading over there and making the edit yourself and submitting a PR?

You can actually do the whole flow from within the GitHub web interface nowadays.

If not I'm happy to pick up the tweak. Let me know!

**Comment by dublx** [comment]
Cool, I'll get that one thru.

**Comment by dublx** [comment]
PR on the way.
