### ISSUE TITLE
Proposal: a way to share data transformations

### ISSUE THREAD

**Issue by dasch** [hashicorp/terraform#14026]
I sometimes need to transform the outputs from one or more resources into a single value, and oftentimes I need to access that value in different places. For example:

```hcl
resource "a" {
  # ...
}

resource "b" {
  # ...
}

resource "c" {
  something = "http://${a.host}:${b.port}/yada/yada.json"
}

resource "d" {
  # This is duplicate...
  something = "http://${a.host}:${b.port}/yada/yada.json"
}
```

It would be great to be able to define shared values (I know `variable` is already taken, although `input` might have been a more fitting name for that construct.)

How about something like this?

```hcl
resource "let" "url" {
  value = "http://${a.host}:${b.port}/yada/yada.json"
}

resource "c" {
  something = "${let.url.value}"
}

resource "d" {
  something = "${let.url.value}"
}

**Comment by catsby** [comment]
Hey @dasch if I understand correctly, an inline template should work for you here:

```hcl
resource "a" {
  # ...
}

resource "b" {
  # ...
}

data "template_file" "init" {
  template = "http://$${host}:$${port}/yada/yada.json"

  vars {
    host = "${a.host}"
    port = "${b.port}"
  }
}

resource "d" {
  something = "${data.template_file.init.rendered}"
}
```

Let me know if that helps!

- https://www.terraform.io/docs/providers/template/d/file.html#inline-templates

**Comment by dasch** [comment]
Ah, didn't know about that. Thanks!
