### ISSUE TITLE
cloudstack_firewall fails with json: unmarshal error

### ISSUE THREAD

**Issue by samzehnder** [hashicorp/terraform#14044]
Hi there,

I run in an error when using the cloudstack_firewall ressource. The configuration is applied correctly but it seems like terraform fails to parse the state and fails with the error:

Error refreshing state: 1 error(s) occurred:
* cloudstack_firewall.default: cloudstack_firewall.default: json: cannot unmarshal string into Go struct field FirewallRule.startport of type int

### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
- cloudstack_firewall

### Terraform Configuration Files
```hcl
provider "cloudstack" {
  # PROD
  api_url = "ommited"
  api_key = "ommited"
  secret_key = "ommited"
  http_get_only = true
  timeout = 3600
}

resource "cloudstack_firewall" "default" {
  ip_address_id = "6be820f2-3e34-40da-9de8-0f323b4a4a89"
  rule {
    cidr_list = ["195.8.198.0/23"]
    protocol  = "tcp"
    ports     = ["80", "22", "443"]
  }
}
```

### Debug Output
not much more than this:
cloudstack_firewall.default: Refreshing state... (ID: 6be820f2-3e34-40da-9de8-0f323b4a4a89)
2017/04/27 18:32:02 [ERROR] root: eval: *terraform.EvalRefresh, err: cloudstack_firewall.default: json: cannot unmarshal string into Go struct field FirewallRule.startport of type int
2017/04/27 18:32:02 [ERROR] root: eval: *terraform.EvalSequence, err: cloudstack_firewall.default: json: cannot unmarshal string into Go struct field FirewallRule.startport of type int
2017/04/27 18:32:02 [TRACE] [walkRefresh] Exiting eval tree: cloudstack_firewall.default
2017/04/27 18:32:02 [DEBUG] dag/walk: upstream errored, not walking "provider.cloudstack (close)"
Error refreshing state: 1 error(s) occurred:

2017/04/27 18:32:02 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/04/27 18:32:02 [DEBUG] plugin: terraform: cloudstack-provider (internal) 2017/04/27 18:32:02 [DEBUG] plugin: waiting for all plugin processes to complete...
* cloudstack_firewall.default: cloudstack_firewall.default: json: cannot unmarshal string into Go struct field FirewallRule.startport of type int
2017/04/27 18:32:02 [DEBUG] plugin: /usr/local/bin/terraform: plugin process exited

### Expected Behavior
Firewallrules are applied, state is updated and can be processed further by terraform

### Actual Behavior
Firewallrules are applied, state cannot be read by further terraform plan/apply runs

### Steps to Reproduce
1. `terraform apply` => error occurs
2. `terraform plan` => error occurs

**Comment by samzehnder** [comment]
here's the statefile: https://gist.github.com/samzehnder/7d2f2c79b4b6afe7d4101eebe47bb1ed

**Comment by svanharmelen** [comment]
@samzehnder I noticed you already supplied a patch to the `go-cloudstack` package and that you already found out this is due to an API change wit CloudStack that happened quite a while ago. I'll have a look at your suggested fix and if that works out we'll update the dependency here as well.

Thanks and I'll get back to you shortly!
