### ISSUE TITLE
Support import of resource type google_storage_bucket

### ISSUE THREAD

**Issue by ryan-mf** [hashicorp/terraform#14047]
### Terraform Version
v0.9.3

### Affected Resource(s)
google_storage_bucket

### Debug Output
Not relevant, but the simple output is:
```Error importing: 1 error(s) occurred:

* google_storage_bucket.<name> (import id: <name>-<name>-corp): import google_storage_bucket.<name>-data (id: <name>-<name>-corp): resource google_storage_bucket doesn't support import
```

### Expected Behavior
Terraform imports the existing resource.

### Actual Behavior
Terraform said it doesn't support importing resource type google_storage_bucket

### Steps to Reproduce
1. `terraform import google_storage_bucket.<name>-data <name>-<name>-corp`
2. See output

**Comment by danawillow** [comment]
Fixed in https://github.com/hashicorp/terraform/pull/14455.
