### ISSUE TITLE
creating aws_instance with tags fails in GovCloud (0.9.4 regression)

### ISSUE THREAD

**Issue by dsw2127** [hashicorp/terraform#14049]
### Terraform Version
0.9.4

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
```
resource "aws_instance" "instance" {
  ami                         = "${var.ami}"
  key_name                    = "${var.key_name}"
  instance_type               = "t2.medium"
  vpc_security_group_ids      = ["${var.security_group_id}"]
  subnet_id                   = "${var.subnet_id}"
  associate_public_ip_address = "true"

  ebs_block_device {
    device_name           = "/dev/sda1"
    volume_size           = "15"
    delete_on_termination = "true"
  }

  ebs_block_device {
    device_name           = "/dev/sdz"
    volume_type           = "gp2"
    volume_size           = "15"
    delete_on_termination = "true"
  }

  tags {
    Name = "ami builder instance"
  }
}
```

### Expected Behavior
Instance launched with tags applied afterwards, as occurred in Terraform 0.9.3

### Actual Behavior
```
Error applying plan:



1 error(s) occurred:



* aws_instance.instance: 1 error(s) occurred:



* aws_instance.instance: Error launching source instance: UnsupportedOperation: Specifying tags during instance launch is not supported in this region.

	status code: 400, request id: f5aa3123-ec4e-4815-8325-d0ba76706740
```

### Steps to Reproduce
Specify an `aws_instance` with `tags` in region `us-gov-west-1` and apply.

### References
Tags were changed to be created on launch by https://github.com/hashicorp/terraform/pull/13945 . However, as noted in https://aws.amazon.com/blogs/aws/new-tag-ec2-instances-ebs-volumes-on-creation/ (at the bottom) this is not available in GovCloud or Beijing.

**Comment by catsby** [comment]
Hey @dsw2127 sorry for the hassle here, we're patching this in https://github.com/hashicorp/terraform/pull/14055 and should get this straightened out soon!

**Comment by rokka-n** [comment]
Looks like it's fixed in 0.9.5

**Comment by stack72** [comment]
Thanks for letting me know @rokka-n

**Comment by dsw2127** [comment]
Thanks for fixing @stack72! I upgraded to 0.9.5 when it came out, and it indeed resolves the issue.

**Comment by stack72** [comment]
excellent! sorry for the hassles here
