### ISSUE TITLE
Route53 resource : InvalidSignatureException

### ISSUE THREAD

**Issue by Iouns** [hashicorp/terraform#1405]
Hello,

Since Terraform 0.4.0, I have some issue with an aws resource.
Following code works on 0.3.7 and not on 0.4.0 :
<pre><code>
resource "aws_route53_record" "main" {
  zone_id = "/hostedzone/XXXXXXXXXXX"
  name = "${var.hostname}.${var.domain_name}"
  type = "CNAME"
  ttl = "60"
  records = ["myrecord.tld."]
}
</code></pre>

On 0.3.7 I have following result :
<pre><code>
aws_route53_record.main: Creating...
  name:               "" => "mynode.tld"
  records.#:          "" => "1"
  records.1545658242: "" => "myrecord.tld."
  ttl:                "" => "60"
  type:               "" => "CNAME"
  zone_id:            "" => "/hostedzone/XXXXXXXX"
aws_route53_record.main: Creation complete
</code></pre>

On 0.4.0 I have :
<pre><code>
* <?xml version="1.0"?>
<InvalidSignatureException>
  <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/2013-04-01/hostedzone/hostedzone/XXXXXXXXXXX

host:route53.amazonaws.com
user-agent:aws-go

host;user-agent
##SHA1##'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
##TIMESTAMP##
20150407/us-east-1/route53/aws4_request
##SHA1##'
</Message>
</InvalidSignatureException>
</code></pre>

Other resources (VPC, instances, eip, security groups... ) are working fine.

Regards,

**Comment by Iouns** [comment]
It seems not related to aws-sdk-go as stated on this report : https://github.com/awslabs/aws-sdk-go/issues/186

**Comment by catsby** [comment]
Hey @Iouns thanks for reporting this. I'm taking a look now. I suspect it has to do with `/hostedzone/XXXXXXXXXXX` as your `zone_id`, which we should be cleaning up, but maybe we aren't here. I'm investigating. 

For what it's worth, Terraform 0.4.0 does not use awslabs/aws-sdk-go, but a fork we made for stability while the awslabs folks refactored upstream. We're in the process of migrating back.

**Comment by catsby** [comment]
In my prelim dig, it seems `/hostedzone/` is in fact at fault here. Can you confirm that removing that prefix from the `zone_id` fixes it for you?

I'll look into automatically scrubbing that, which I _thought_ we were doing..

**Comment by catsby** [comment]
This should be fixed in #1415

**Comment by Iouns** [comment]
Hello @catsby,

You're right, it works when I remove /hostedzone/.

    aws_route53_record.main: Creation complete

I now understand why I got "/2013-04-01/hostedzone/hostedzone/XXXXXXXXXXX"

Thank you.

**Comment by catsby** [comment]
Great, thanks for following up! 
As I mentioned, I believe #1415 fixes this, and should be merged into `master` sometime today.
Thanks!
