### ISSUE TITLE
Add support for singlePlacementGroup on azurerm_virtual_machine_scale_sets

### ISSUE THREAD

**Issue by cberner** [hashicorp/terraform#14058]
### Terraform Version
0.9.3

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_machine_scale_sets

### Feature Request
Please add support for the singlePlacementGroup option, which is necessary when creating large Scale Sets. See here for documentation: https://docs.microsoft.com/en-us/rest/api/virtualmachinescalesets/create-or-update-a-set

**Comment by StephenWeatherford** [comment]
@cberner, I can implement this.
