### ISSUE TITLE
Website FR: Add Search Bar to terraform.io

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform#14053]
This is pretty common on websites these days, but there isn't one on terraform.io (or any of the other hashicorp projects, from what I can tell). Would be nice to have.

@sethvargo I've been told you may already have some thoughts here.

**Comment by sethvargo** [comment]
Hey @danawillow 

It's actually in progress https://github.com/hashicorp/terraform/pull/13067. We are working on both a sidebar search and a global search. It's unlikely it'll be a "search bar", but we are iterating on some designs internally that all the static sites will get once it's ready!

**Comment by danawillow** [comment]
Sounds great, thanks!
