### ISSUE TITLE
 Error creating launch configuration: ValidationError: on ec2 instance profile and security groups when passes as varaibles

### ISSUE THREAD

**Issue by sreeramsanjay** [hashicorp/terraform#14063]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- dnsimple_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by tombuildsstuff** [comment]
Hi @sreeramsanjay

Thanks for opening this issue.

So that we can investigate this further, would it be possible to post the Terraform Configuration (minus any secrets) that you're using?

Thanks!

**Comment by sreeramsanjay** [comment]
we noticed issue with aws launch_configuration resource, whenever we tried to pass the ec2 instance profile and security groups,terrafrom apply is failing with below validation errors.
* aws_launch_configuration.master_lc: Error creating launch configuration: ValidationError: The security group '{var.mgmt_security_group_id}' does not exist in default VPC 'vpc-163c1170'
* aws_launch_configuration.master_lc: Error creating launch configuration: ValidationError: Invalid IamInstanceProfile: {var.master_ec2_instance_profile}

We do not see any issue when we passed it as direct values. 

details:
https://github.com/sreeramsanjay/dcos.git
go to ./ms_build 
it has main.tf
all supported modules for main.tf on ./master
# terraform -v
Terraform v0.9.4

List of resource:
security groups
ec2 instance profile, iam role,iam policy
elastic load balancer 
launch configurations
Auto scaling group

**Comment by tomelliff** [comment]
Lines 24-26 (https://github.com/sreeramsanjay/dcos/blob/master/ms_build/main.tf#L24) are missing the `$` to start the interpolation syntax so it's being evaluated as a string literal. Instead they should look like:
```hcl
  dcos_master_security_group_id = "${module.security_groups.dcos_master_security_group_id}"
  mgmt_security_group_id = "${var.mgmt_security_group_id}"
  dcos_master_ec2_instance_profile = "${module.ec2_profile.dcos_master_ec2_instance_profile}"
```
