### ISSUE TITLE
Add support for IAM Database Authentication

### ISSUE THREAD

**Issue by gazoakley** [hashicorp/terraform#14069]
AWS recently added a feature to allow connections to Aurora/MySQL RDS instances using IAM roles:

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

This allows applications to connect without specific credentials. There's a new `EnableIAMDatabaseAuthentication` parameter that can be specified when creating/updating Aurora clusters/MySQL instances, and an `IAMDatabaseAuthenticationEnabled` attribute in response to querying clusters/instances. Support for these could be added to the `aws_rds_cluster` and `aws_db_instance` resources.

**Comment by gazoakley** [comment]
I'm currently working on this in a branch here: https://github.com/gazoakley/terraform/tree/iam-database-authentication-enabled

**Comment by gazoakley** [comment]
PR is #14092

**Comment by grubernaut** [comment]
Closed via: #14092
