### ISSUE TITLE
Add support for Softlayer

### ISSUE THREAD

**Issue by bendodd** [hashicorp/terraform#1406]
Are there any plans to support Softlayer?

**Comment by athak** [comment]
+1 for this

**Comment by miu-zsolt** [comment]
+1

**Comment by rarruda** [comment]
+1

**Comment by matheusrossato** [comment]
+1

**Comment by cloudify** [comment]
+1

**Comment by apparentlymart** [comment]
* [SoftLayer API docs](http://developer.softlayer.com/reference/softlayerapi)
* [Go client for the API](https://github.com/maximilien/softlayer-go) (not sure how comprehensive it is)

It looks like SoftLayer has quite a few resources. For those who have added +1 to this issue: is there a small set of resources from SoftLayer that would be a good start for basic SoftLayer support? I don't know SoftLayer at all, but usually new providers start with one or two key resource types and then grow over time depending on contributor interest.

**Comment by aardestani** [comment]
As a start I recommend doing Softlayer Managers

http://softlayer-api-python-client.readthedocs.org/en/latest/api/client/#managers

**Comment by jaisingh** [comment]
+1

**Comment by sudorandom** [comment]
Here's my efforts to generate a client for the SoftLayer API for go: https://github.com/sudorandom/softlayer-go

It's nowhere close to where I would consider finished but it does have the ability to generate go types for all SoftLayer types. It seems to be usable for simple cases at the very least.

**Comment by axltxl** [comment]
+1

**Comment by ckelner** [comment]
Wanted to provide some info here.  There is https://github.com/hashicorp/terraform/pull/2554 which then turned into: https://github.com/finn-no/terraform-provider-softlayer -- now TheWeatherCompany (parent company for The Weather Channel [weather.com], Weather Underground [wunderground.com], and WSI [http://www.wsi.com/]) is starting to work this effort very very soon, progress can be followed here: https://github.com/TheWeatherCompany/terraform/tree/feature/softlayer

**Comment by therealjessesanford** [comment]
I would also love to see this.

**Comment by ckelner** [comment]
We're working on it over at https://github.com/theweathercompany/terraform/tree/feature/softlayer and making progress.  @danielcbright will be making a PR very soon!

**Comment by wakwanza** [comment]
+1

**Comment by danielcbright** [comment]
PR created: https://github.com/hashicorp/terraform/pull/4327 - right now it's waiting on https://github.com/maximilien/softlayer-go/pull/84 changes to be made as it's currently a dependency. I'll update as progress is made.

**Comment by JulienChampseix** [comment]
any update ?

**Comment by danielcbright** [comment]
All checks are now passing for the initial PR https://github.com/hashicorp/terraform/pull/4327

**Comment by JulienChampseix** [comment]
@daniel-bryant-uk have you some news about the validation of this PR ?

**Comment by daniel-bryant-uk** [comment]
Hey @JulienChampseix, I think you've tagged the wrong Daniel - You want @danielcbright :-)

**Comment by danielcbright** [comment]
Thanks @daniel-bryant-uk :)

@JulienChampseix at this point I think the more people who can test and comment on the existing PR the better, the open PR is here https://github.com/hashicorp/terraform/pull/4327. Please let me know of any bugs/issues you find. The other thing of note is that this is going to be a community supported provider for Hashicorp, based on @mitchellh 's blog post earlier this year: https://www.hashicorp.com/blog/terraform-improve.html.

I think once the base provider is pulled in, which currently adds support for `virtual_guest` and `dns` within SoftLayer, it's going to pave the way for future additions we've already made.

**Comment by chulkilee** [comment]
softlayer provider is added to 0.6.16. Let's close it; open new issues for more features

**Comment by jen20** [comment]
:+1: - Softlayer is in 0.6.16.
