### ISSUE TITLE
Add support for bootDiagnostics on azurerm_virtual_machine_scale_sets

### ISSUE THREAD

**Issue by vicki-c** [hashicorp/terraform#14060]
### Terraform Version
0.9.3

### Affected Resource(s)
azurerm_virtual_machine_scale_sets

### Feature Request
Please add support for the bootDiagnostics option for Scale Sets, similar to [azurerm_virtual_machine](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#boot_diagnostics). See here for documentation: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-faq#troubleshooting

**Comment by tombuildsstuff** [comment]
Hi @vicki-c 

Thanks for requesting this feature.

We partially support Boot Diagnostics at the moment - however it's limited to a storage account specified by Azure. [There's an issue open tracking adding the functionality to specify a custom storage account](https://github.com/Azure/azure-rest-api-specs/issues/835) - which I've pinged Microsoft for an update on, once that's resolved we can add support for this :)

Thanks!
