### ISSUE TITLE
Feature Req: Provider azurerm add subnet_id parameter to azurerm_container_service resource

### ISSUE THREAD

**Issue by kpeder** [hashicorp/terraform#14062]
For instance, the CLI and ARM templates allow targeted deployments of ACS to a specific managed resource group / vnet / subnet.

This specification is set via the 'vnetSubnetId': parameter in both ARM template and the Azure CLI.

“vnetSubnetId”: “/subscriptions/REPLACE_WITH_SUBSCRIPTION_ID/resourceGroups/REPLACE_WITH_RESOURCE_GROUP_NAME/providers/Microsoft.Network/virtualNetworks/REPLACE_WITH_VNET_NAME/subnets/mySubnetName”

Exposure of this parameter allows specification of a private cluster in the template instead of requiring the CLI or json template specification to deploy.

**Comment by tombuildsstuff** [comment]
Hi @kpeder 

Taking a quick look into this - currently this field isn't exposed in the Azure SDK for Go, however I've [opened an issue to request it's added](https://github.com/Azure/azure-rest-api-specs/issues/1172) on the repository the SDK is generated from. Once this has been added to the SDK, we can look at adding support for this :)

**Comment by kpeder** [comment]
Thanks @tombuildsstuff 

Please note that there are other templated resources, such as the HDInsight clusters (deplyable via CLI) that have the same parameter available for configuration. One workaround to this issue is to deploy the cluster via a resource template, and with the appropriate parameters set in the json file.
