### ISSUE TITLE
Cannot create ASG in EC2 Classic

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#1410]
Attempting to creating an ASG in EC2 Classic results in the following error message:

```
* Error creating Autoscaling Group: AssociatePublicIpAddress field can not be specified without a subnet id
```

Looks like we're not properly omitting that field from the request struct when it does not apply, causing AWS API validation to complain.

**Comment by phinze** [comment]
Example config that generates this error:

```js
provider "aws" {
  region = "us-east-1"
}

module "ami" {
  source = "github.com/terraform-community-modules/tf_aws_ubuntu_ami"
  region = "us-east-1"
  distribution = "trusty"
  architecture = "amd64"
  virttype = "hvm"
  storagetype = "instance-store"
}

resource "aws_launch_configuration" "web" {
  image_id = "${module.ami.ami_id}"
  instance_type = "t1.micro"
}

resource "aws_autoscaling_group" "web" {
  name = "web-asg"
  launch_configuration = "${aws_launch_configuration.web.name}"
  min_size = 1
  max_size = 1
  availability_zones = ["us-east-1a"]
}
```

**Comment by keeth** [comment]
I am seeing this error, using v0.6.11 - is it possible there was a regression?

Here's my config:

```
resource "aws_autoscaling_group" "main" {
  availability_zones = ["us-west-2a"]
  name = "my-asg"
  min_size = "1"
  max_size = "2"
  desired_capacity = "1"
  launch_configuration = "terraform-lhqypkobrrgxhaqije7go5ugdu"

  tag {
    key = "Name"
    value = "my-asg"
    propagate_at_launch = true
  }
}
```

**Comment by phinze** [comment]
Hi @keeth, I just re-ran the above config with 0.6.11 in a Classic region and confirmed it's working.

If you can reliably reproduce this on the latest Terraform version (0.6.12), can you file a fresh issue? Make sure and let us know if `us-west-2` is an EC2 Classic region in your account. :ok_hand:
