### ISSUE TITLE
Docs refer to non-existent "name" parameter in S3 bucket parameters

### ISSUE THREAD

**Issue by alexwlchan** [hashicorp/terraform#14110]
Quoting from the argument reference for the [aws_s3_bucket resource](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) (emphasis mine):

> `bucket_prefix` - (Optional, Forces new resource) Creates a unique bucket name beginning with the specified prefix. **Conflicts with `name`.**

There is no `name` parameter on an aws_s3_bucket resource – should this refer to `bucket` instead?

**Comment by catsby** [comment]
Whoops 😱 yes I think that should refer to `bucket`

**Comment by alexwlchan** [comment]
@catsby PR incoming.

**Comment by alexwlchan** [comment]
Too slow, past!Alex. Fixed in df777566f9486e965642438b1d678867c8c18cc2.

**Comment by catsby** [comment]
haha thanks @alexwlchan sorry, I just sniped it when I saw it :D deployed to https://www.terraform.io/docs/providers/aws/r/s3_bucket.html
