### ISSUE TITLE
RDS ModifyOptionGroup

### ISSUE THREAD

**Issue by vincentdasari** [hashicorp/terraform#14129]
Hi there,

I'm trying to add a tag to an existing OptionGroup and terraform throws out the following error- "Error modifying DB Option Group: InvalidParameterValue: At least one option must be added, modified, or removed."

I'm guessing that ModifyOptionGroup does not have the ability to add a tag for an existing option group and the same options or configuration for create option group has been added.

Affected resources-
aws_db_option_group

**Comment by gazoakley** [comment]
The existing code checks if there are options to add/remove here:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_option_group.go#L265

`ModifyOptionGroup` is called without tag changes (it doesn't support modifying tags - that's done later presumably through AddTagsToResource/RemoveTagsFromResource):

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_option_group.go#L274

The above could probably just be wrapped in a condition so we can skip to calling `setTagsRDS` if there's nothing to do

**Comment by stack72** [comment]
Hi @vincentdasari 

Thanks for the bug report here - we think this may have expected an issue in Terraform core - we are looking into this right now

Thanks

Paul
