### ISSUE TITLE
elastic_beanstalk_environment `wait_for_ready_timeout` documentation wrong

### ISSUE THREAD

**Issue by archgrove** [hashicorp/terraform#14148]
### Version
0.9.3

### Affected Resource(s)
AWS elastic_beanstalk_environment

### Description
Commit https://github.com/hashicorp/terraform/commit/cd79471ecbad41b8bb9e70cc5e8e47b210cc3f32 (for PR https://github.com/hashicorp/terraform/pull/13359) altered the default `wait_for_ready_timeout` on EB instances from 10 to 20 minutes, but did not update the documentation to reflect this.

I've two solutions:

1) A trivial PR at that corrects the documentation: https://github.com/hashicorp/terraform/pull/14149
2) Revert `cd79471ecbad41b8bb9e70cc5e8e47b210cc3f32`: As it stands, it'll cause everyone using the default timeout to have an unexpected change in their next `plan`. The change was done in reference to https://github.com/hashicorp/terraform/pull/13359, and fixes a test failure to due (I assume) overrunning EB waits, but seems like a blunt instrument. I've not looked in detail, so it might well be the most sensible thing to do, but the knock-on effect to end users is a bit sad. However, it might be too late, as this went out in 0.9.3?

**Comment by radeksimko** [comment]
Fixed via #14149

I'll make sure to think about graceful migration paths next time.
Sorry if it caused any inconvenience.
