### ISSUE TITLE
Add Collaborators to Heroku Provider

### ISSUE THREAD

**Issue by woodhull** [hashicorp/terraform#1414]
We're currently using a ruby script to add/remove Heroku collaborators to heroku applications after the terraform apply run completes. It would be nice to have the ability to modify the list of collaborators on a per application basis through terraform. 

https://devcenter.heroku.com/articles/platform-api-reference#collaborator

**Comment by phinze** [comment]
Going to close this issue since it hasn't seen any activity in a long time, but we'd happily accept a PR for functionality like this!
