### ISSUE TITLE
ASG Tag Name

### ISSUE THREAD

**Issue by mqasim1983** [hashicorp/terraform#14146]
Hi there,
 
Is it possible to have the tag name in of each instance different?
I have the following configuration

    resource "aws_autoscaling_group" "asg" {
      vpc_zone_identifier  = ["${split(",", var.subnet_id)}"]
      availability_zones   = ["${split(",", var.availability_zone)}"]
      name                 = "${var.tags_name}-ASG"
      max_size             = "${var.asg_max_size}"
     min_size             = "${var.asg_min_size}"
     desired_capacity     = "${var.asg_desired_capacity}"
     force_delete         = "${var.asg_force_delete}"
     launch_configuration = "${aws_launch_configuration.lc.name}"
     target_group_arns    = ["${var.aws_loadbalancer_arn}"]
     load_balancers       = ["${var.aws_elb_name_mysql}"]
     enabled_metrics = ["GroupInServiceInstances", "GroupMaxSize", "GroupMinSize", "GroupTerminatingInstances", "GroupStandbyInstances", "GroupTotalInstances", "GroupDesiredCapacity", "GroupPendingInstances"]
      lifecycle {
      ignore_changes = ["desired_capacity","target_group_arns","load_balancers"]
       create_before_destroy = true
      }

      tag {
       key                 = "Name"
       value               = "${var.tags_name}"
       propagate_at_launch = "true"
      }
    }

So is it possible when each instance is in ASG it will have the TAG name example Manager-us-east-1a-1 and second one Manager-us-east-1b-2 and so on?
if not is there any better solution to it?

Thanks

**Comment by coen-hyde** [comment]
Hi @mqasim1983. You can do that directly with ASG's. But you could setup a launch notification that is sent to an AWS Lambda. From there you can update the instance tag to include whatever you want. Sequential numbering will probably be a bit hard as you'll have to lookup the last increment and apply locking (to prevent allocating the same number twice it two machines boot at the same time). But you could just append the instance id to the tag set via the ASG for a unique name tag.

**Comment by mqasim1983** [comment]
Hi, Thanks @coen-hyde for the reply, yes the best option is to use instance id.
