### ISSUE TITLE
Feature Request: command line control of output variable visibility

### ISSUE THREAD

**Issue by pll** [hashicorp/terraform#14159]
I'd like to control the verbosity of terraform in general, and output vars specifically (I'd also like some means of controlling the order of output vars as well).

Most tools have a --verbose option and/or a --debug option. Terraform has neither.

I would also like some way of marking certain output vars as more or less important, and make this controllable via the command line as well.  I'm thinking of something like this, but I'm sure there's a better way...

    output "foo" {
       type = "debug"
       value = "bar"
    }
    output "important_foo" {
      type = "info"
       value = "something_important"
    }
Then, theoretically, you could choose which vars you see at run-time:
`terraform apply --var-level=debug` or `terraform apply --var-level=info`

Would love to hear some thoughts on this, and discuss it a bit more. I'd be happy for now if there were just some way to force the output order to one of my own choosing (e.g. just print them out in the order they're listed in the .tf file.)

Thanks.
--
Paul

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. 

This is a really interesting idea however and while we don't have plans to tackle it ourselves any time soon, if there's an interested community member out there who stumbles on this issue and wants to consider tackling it, we'd welcome a new enhancement request with a proposal we can discuss. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
