### ISSUE TITLE
inconsistent count interpolation

### ISSUE THREAD

**Issue by DoctorVin** [hashicorp/terraform#1416]
Built terraform from source on OS X, version: Terraform v0.4.0-dev (f8a699f3d888e7c697daa947728d52552378a20e)

I'm finding that count.index is being set inconsistently in plans and applies.
```
resource "aws_instance" "web" {
	count = "3"
        ...
        tags {
		Name = "Web-${count.index}"
		Serial = "${count.index}"
	}
}
```

I expected 3 instances with name tags "Web-0", "Web-1", "Web-2", and serial 0, 1, 2, but intermittently I get multiple Web-1's or Web-2's. The serial tag always matches the name tag. You don't need to apply to see this behavior, repeated plans will demonstrate it.

**Comment by phinze** [comment]
Hi @DoctorVin, thanks for the report.

I made some attempts to reproduce, but no luck over here.

My Config:

```js
resource "aws_instance" "web" {
  ami = "ami-7f89a64f"
  instance_type = "t1.micro"
  count = "3"
  tags {
    Name = "Web-${count.index}"
    Serial = "${count.index}"
  }
}
```

My test runs:

```sh
$ terraform plan | grep -E 'Name|Serial'
    tags.Name:                "" => "Web-0"
    tags.Serial:              "" => "0"
    tags.Name:                "" => "Web-1"
    tags.Serial:              "" => "1"
    tags.Name:                "" => "Web-2"
    tags.Serial:              "" => "2"
$ terraform plan | grep -E 'Name|Serial' | shasum
b2c86c12f3a2f2b414920f30973ea3654d605c37  -
$ for i in {0..1000}; do terraform plan | grep -E 'Name|Serial' | shasum >> /tmp/outputs; done; cat /tmp/outputs | uniq -c
1001 b2c86c12f3a2f2b414920f30973ea3654d605c37  -
```

So AFAICT I'm getting consistent output over here. Can you share a bit more detail to help me reproduce?

**Comment by DoctorVin** [comment]
I did manage to find my problem. It's mostly a new guy mistake, but there is the potential for some race-condition weirdness in here, so I put together a Gist that shows the problem in my hands.

https://gist.github.com/12c3c845452baa968025.git

Thanks again, @phinze!
