### ISSUE TITLE
Warn on large directory before uploading to Terraform Cloud for remote operations

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#14181]
If there are large files in the working directory when performing a `terraform push`, the push can appear to stall if the upload is taking a long time. Large uploads are not the typical use case for a `terraform push` and it's not always apparent what is being uploaded so it would be nice to provide a warning to the user when the upload is larger than a certain size (10MB?). This will help reduce troubleshooting and support requests for Terraform Enterprise.

**Comment by apparentlymart** [comment]
Hi @clstokes!

The `terraform push` command is no longer used after the EOL of Atlas, but similar behaviors apply to the new "remote" backend which is in a preview state in the v0.11.10 release as I write this, so I've relabeled this as an enhancement for that backend.

**Comment by pkolyvas** [comment]
We are hopeful that the `.terraformignore` feature released in `0.12.17` will help address requests like these: https://www.terraform.io/docs/backends/types/remote.html#excluding-files-from-upload-with-terraformignore
