### ISSUE TITLE
provider/aws: add description to IAM roles

### ISSUE THREAD

**Issue by bacoboy** [hashicorp/terraform#14198]
IAM roles have a description that can be set using the CLI `update-role-description` IAM subcommand or via the [go AWS SDK](https://godoc.org/github.com/aws/aws-sdk-go/service/iam#IAM.UpdateRoleDescription).

This is a request to add a `description` attribute to [`aws_iam_role` resource](https://www.terraform.io/docs/providers/aws/r/iam_role.html) which will call this function.

I did a quick search thru the current issue/feature list and didn't see this so sorry if a dupe.

**Comment by blaltarriba** [comment]
+1

**Comment by bacoboy** [comment]
Wow that was fast!  Thanks @minamijoyo.  Will look for it in next release...

**Comment by minamijoyo** [comment]
@bacoboy I'm happy to help 😄
