### ISSUE TITLE
Default security group rule not being removed after error

### ISSUE THREAD

**Issue by CarlInglisBJSS** [hashicorp/terraform#14201]
### Terraform Version
0.9.2

### Affected Resource(s)
aws_security_group
aws_security_group_rule

### Expected Behavior
Default security group rule should been removed

### Actual Behavior
Rule is not removed.

### What happened
We built a new environment and had errors:

```
09:15:08 Error applying plan:
09:15:08 
09:15:08 5 error(s) occurred:
09:15:08 
09:15:08 * aws_security_group.jasper_testing_proxy_sg: 1 error(s) occurred:
09:15:08 
09:15:08 * aws_security_group.jasper_testing_proxy_sg: timeout while waiting for state to become 'success' (timeout: 2m0s)
09:15:08 * aws_subnet.elb_subnets[2]: 1 error(s) occurred:
09:15:08 
09:15:08 * aws_subnet.elb_subnets.2: timeout while waiting for state to become 'success' (timeout: 2m0s)
09:15:08 * aws_db_instance.main-rds-instance: 1 error(s) occurred:
09:15:08 
09:15:08 * aws_db_instance.main-rds-instance: Error creating DB Instance: InvalidParameterCombination: The Parameter Group dev05-main-rds-param-group with DBParameterGroupFamily mariadb10.0 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily mariadb10.1
09:15:08 	status code: 400, request id: 4cf33888-2fdf-11e7-a19e-27ec36174137
09:15:08 * aws_security_group.openif_prw_elb_sg: 1 error(s) occurred:
09:15:08 
09:15:08 * aws_security_group.openif_prw_elb_sg: timeout while waiting for state to become 'success' (timeout: 2m0s)
09:15:08 * aws_security_group.frontend_elc_proxy_sg: 1 error(s) occurred:
09:15:08 
09:15:08 * aws_security_group.frontend_elc_proxy_sg: timeout while waiting for state to become 'success' (timeout: 2m0s)
09:15:08 
09:15:08 Terraform does not automatically rollback in the face of errors.
09:15:08 Instead, your Terraform state file has been partially updated with
09:15:08 any resources that successfully completed. Please address the error
09:15:08 above and apply again to incrementally change your infrastructure.
09:15:08 ERROR: Terraform apply failed with exit code 1
```

The error is understandable and we fixed it and re-applied. When we subsequently ran our AWSpec tests we found some unexpected security group rules in the three groups mentioned above (one example below):

```
                "aws_security_group.frontend_elc_proxy_sg": {
                    "type": "aws_security_group",
                    "depends_on": [
                        "aws_vpc.vpc"
                    ],
                    "primary": {
                        "id": "sg-87d4a4fe",
                        "attributes": {
                            "description": "Allows access from the blue/green stacks to the Frontend ElastiCache",
                            "egress.#": "1",
                            "egress.482069346.cidr_blocks.#": "1",
                            "egress.482069346.cidr_blocks.0": "0.0.0.0/0",
                            "egress.482069346.from_port": "0",
                            "egress.482069346.ipv6_cidr_blocks.#": "0",
                            "egress.482069346.prefix_list_ids.#": "0",
                            "egress.482069346.protocol": "-1",
                            "egress.482069346.security_groups.#": "0",
                            "egress.482069346.self": "false",
                            "egress.482069346.to_port": "0",
                            "id": "sg-87d4a4fe",
                            "ingress.#": "0",
                            "name": "dev05-frontend-elc-proxy-sg",
                            "owner_id": "054631451206",
                            "tags.%": "2",
                            "tags.Environment": "dev05",
                            "tags.Name": "dev05-frontend-elc-proxy-sg",
                            "vpc_id": "vpc-9a4ab9fd"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                },
```

These rules do not exist in our code, however when we reapply the code they do not get removed. 

It's a bit of an edge case, I realise, however it's concerning that the default rule is silently ignored.

**Comment by grubernaut** [comment]
Hey @CarlInglisBJSS, thanks for the issue! 

This is an extension of a more common/popular issue where aws security group rules are overwritten when combining rules from both the `aws_security_group` resource and the `aws_security_group_rule` resource. 

The `aws_security_group` resource is able to hold a firm contract on _all_ of the rules listed inside of that resource, and is able to iterate through the entire set of rules attached to a security group resource, removing and adding rules as needed. 

In contrast, the `aws_security_group_rule` resource has a much more limited scope, and can only add security group rules to a security group. Internally, the `aws_security_group_rule` resource simply iterates through the list of security group rules for a security group, and adds the target rule if it doesn't exist. The resource has no contextual knowledge of the entirety of rules that should or should not be attached to that security group. 

Thus, we are left with the following: If you require full control over your security group, use inline rules attached to the `aws_security_group` resource. Or, if you're spreading the creation of security group rules out over multiple modules or remote states, use the `aws_security_group_rule` resource. 

We've discussed internally the ability to give a full state-level context to the `aws_security_group_rule` resource, such that every resource will be able to create a full definition of the explicit rules that should be and should not be attached to a security group, but it would be a future enhancement that we haven't planned yet. 

Going to close for now, but happy to discuss further if need be. Thanks!

**Comment by grubernaut** [comment]
Hey @CarlInglisBJSS, realized I may not have fully explained how this directly relates to your issue here. 

When we create an `aws_security_group` resource we enter a retry function until the resource is created. Once it's created, we remove the default security group rule, to avoid any unwarranted confusion. However, in your case, we hit a timeout during the resource creation, and were unable to remove the default security group rule. 

The above description of the differences between the aws_security_group resource and the aws_security_group_rule resource should add some color as to why the default security group rule wasn't removed, but I thought I should add a quick description of why the default security group rule was there to begin with. Hope this helps!

**Comment by CarlInglisBJSS** [comment]
Hi @grubernaut,

The concern wasn't that the rule was left behind, we worked out how that happened. 

The concern was that the rule existed in TFSTATE, but not in our TF, and TF didn't attempt to remove it, or to complain about it.

**Comment by grubernaut** [comment]
@CarlInglisBJSS, ah I'm sorry I misread your issue! 

So to clarify: 
- Terraform statefile listed the aws_security_group_rule resource
- Terraform configuration did not contain this resource
- Terraform did not attempt to resolve the diff between configuration and statefile

And the resource still existed in AWS? (Assuming, yes, as it was found via running the AWS Spec tests). 

Re-opening as there is still an issue.

**Comment by CarlInglisBJSS** [comment]
Hi @grubernaut No worries - sometimes I'm not as clear as I'd like to be. :)

Yup, you are correct.

**Comment by grubernaut** [comment]
Awesome! @CarlInglisBJSS, is the `aws_security_group` resource for the effected security group in your configuration? Or are you suggesting the `aws_security_group_rule` resource is not in your configuration but exists in state?

**Comment by CarlInglisBJSS** [comment]
The rule resource is in state but not in our config. The group resource is in our config.
