### ISSUE TITLE
Allow Lookup of AMIs by tag

### ISSUE THREAD

**Issue by woodhull** [hashicorp/terraform#1420]
In our application, we build AMIs using packer. Those AMIs are tagged by type and in various other ways. 

In terraform, we'd always like to apply the newest AMI that has been generated as part of the plan. 

To make that work currently we've wrapped terraform in a ruby script that retrieves the current list of AMIs for a particular tag, finds the latest one and then passes the AMI ID to terraform as a variable. 

We're fine with the current feature-set since we've written this work around but it would be more elegant if this was a built-in part of terraform, and other users might want to do the same thing.

**Comment by gtrevg** [comment]
I was just wondering the same thing as I'm starting down the packer / terraform path for building out AWS clusters.  Any recommendations from Hashicorp on the best way to do this would be appreciated.

Thanks!

**Comment by Rh1N0** [comment]
As an option you can store newest AMI id to consul server and use consul_key as a part of your plan (https://www.terraform.io/docs/providers/consul/r/keys.html)

**Comment by stack72** [comment]
Hi all

this has been covered in 0.7 thanks to the new data_source work

https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/aws/d/ami.html.markdown

Paul
