### ISSUE TITLE
Datasource aws_vpc_peering_connection unable to retrieve the peering connection.

### ISSUE THREAD

**Issue by naikajah** [hashicorp/terraform#14212]
Hi there,

### Terraform Version
Terraform v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- datasource aws_vpc_peering_connection

### Terraform Configuration Files
```hcl
data "aws_vpc_peering_connection" "mgmtpcx" {
  vpc_id          = "${var.requester_vpc_id}"
  peer_vpc_id = "${var.accepter_vpc_id}"
} 
```
or
```
data "aws_vpc_peering_connection" "mgmtpcx" {
  cidr_block    = "${var.requester_cidr_block }"
  peer_vpc_id = "${var.accepter_vpc_id}"
}
```

### Expected Behavior
Datasource should have picked the VPC peering connection in the accepter's AWS account to be used by aws_vpc_peering_connection_accepter to accept it. 
I can see from the AWS console that there is a peering connection waiting for approval.

### Actual Behavior
no matching VPC peering connection found

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

I am running terraform plan from the accepter's AWS account which happens to be a different account than requester's AWS account. Even if I use requester's cidr_block it gives the same error.
Anything that I am missing here?

**Comment by ewbankkit** [comment]
@naikajah You're on the right track.
In the **accepter**'s account, `vpc_id`/`cidr_block` will be the **requester**'s VPC ID/CIDR block and `peer_vpc_id` will be the **accepter**'s VPC ID. I think that in addition you will need to specify [`owner_id`](https://www.terraform.io/docs/providers/aws/d/vpc_peering_connection.html#owner_id) as the **requester**'s AWS account ID.

**Comment by naikajah** [comment]
@ewbankkit Thanks for the information. So I tried putting in the owner_id of the requester AWS account and it did the trick so below is my final code
```
data "aws_vpc_peering_connection" "mgmtpcx" {
  count         = "${length(var.peering_cidr_blocks)}"
  cidr_block    = "${element(var.peering_cidr_blocks,count.index)}"
  owner_id      = "${var.dev_account_id}"
  peer_vpc_id   = "${var.mgmt["vpc_id"]}"
  peer_owner_id = "${var.account_id}"
  status        = "pending-acceptance"
} 
```

which is then used by accepter as:
```
resource "aws_vpc_peering_connection_accepter" "mgmt_peer_acceptor" {
  count                     = "${length(var.dev_peering_cidr_blocks)}"
  vpc_peering_connection_id = "${element(data.aws_vpc_peering_connection.mgmtpcx.*.id,count.index)}"
  auto_accept               = true

  tags {
    "Side"        = "Accepter"
  }
}
```

So I guess there is some documentation issue with the data source as the link 
https://www.terraform.io/docs/providers/aws/d/vpc_peering_connection.html#status

have **owner_id - (Optional)** which should be Required because unless I specify the owner_id I can't use the datasource for peering connection.
@mitchellh

**Comment by ewbankkit** [comment]
@naikajah The `owner_id` parameter is marked as **Optional** in the docs as it's not required by the underlying AWS _DescribeVpcPeeringConnections_ API and it defaults to the account ID of the caller - The accepter in your case.
PRs are always accepted for documentation clarifications 😄 .
