### ISSUE TITLE
Importing an aws_route53_record resource crashes if ID is not properly constructed

### ISSUE THREAD

**Issue by matthoey-okta** [hashicorp/terraform#14217]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v0.9.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```terraform import aws_route53_record.main ZONEID_record```
Note something like "_A" is missing from the end of the ID.

### Debug Output
https://gist.github.com/matthoey-okta/a81151555c147d5f4a6c8930746ceb81

### Panic Output
https://gist.github.com/matthoey-okta/75058630a81e2d3ba734266cc42baa9d

### Expected Behavior
Error that the format of the ID is not acceptable.

### Actual Behavior
TERRAFORM CRASH

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import aws_route53_record.main ZONEID_record`
Note something like "_A" is missing from the end of the ID.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by matthoey-okta** [comment]
I'd add that the fields separated by the _ in the ID is not immediately obvious what they are. Perhaps providing a few more examples like CNAME and A records or explaining them would help?

**Comment by stack72** [comment]
Hi @matthoey-okta 

Apologies this is causing you pain - I have just opened a PR that includes a fix to the panic but also documents what an ID actually is

e.g.

```
oute53 Records can be imported using ID of the record. The ID is made up as ZONEID_RECORDNAME_TYPE_SET-IDENTIFIER

e.g.

```
Z4KAPRWWNC7JR_dev.example.com_NS_dev
```

In this example, `Z4KAPRWWNC7JR` is the ZoneID, `dev.example.com` is the Record Name, `NS` is the Type and `dev` is the Set Identifier.
Only the Set Identifier is actually optional in the ID
```

Hope this helps

Paul

**Comment by matthoey-okta** [comment]
Thanks!
