### ISSUE TITLE
Syntax errors in provisioners are ignored if no tfstate is present

### ISSUE THREAD

**Issue by lyptt** [hashicorp/terraform#1423]
When running `terraform apply` for the first time, if there are any syntax errors in the provisioners of a resource, those provisioners are simply skipped over. Subsequent `terraform apply`s properly fail when encountering syntax errors.

Here's an example resource that should help in replicating the issue:

```
resource "aws_instance" "myinstance" {
  ami = "${var.ami_myinstance}"
  instance_type = "${var.instance_type}"
  tags {
    Name = "myinstance"
  }

  provisioner "remote-exec" {
    inline = [
      "pwd"
      "pwd"
    ]
  }
}
```

**Comment by mitchellh** [comment]
I can't reproduce this, I think it was fixed at some point I suppose, but your config above always gives me a syntax error now!
