### ISSUE TITLE
azurerm - Terraform wants to recreate VM when attaching existing managed data disk

### ISSUE THREAD

**Issue by marratj** [hashicorp/terraform#14268]
### Terraform Version
0.9.4

### Affected Resource(s)
azurerm_virtual_machine
azurerm_managed_disk

### Terraform Configuration Files
resource "azurerm_managed_disk" "db1appdisk2" {
  name                 = "db1appdisk2"
  location             = "${azurerm_resource_group.testdemo.location}"
  resource_group_name  = "${azurerm_resource_group.testdemo.name}"
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = "127"
}

resource "azurerm_virtual_machine" "db1" {
  name                  = "db1"
  location              = "${azurerm_resource_group.testdemo.location}"
  resource_group_name   = "${azurerm_resource_group.testdemo.name}"
  network_interface_ids = ["${azurerm_network_interface.db1nic1.id}"]
  vm_size               = "Standard_DS1_v2"

...

  storage_data_disk {
    name            = "${azurerm_managed_disk.db1appdisk2.name}"
    managed_disk_id = "${azurerm_managed_disk.db1appdisk2.id}"
    create_option   = "Attach"
    lun             = 1
    disk_size_gb    = "${azurerm_managed_disk.db1appdisk2.disk_size_gb}"
  }
}

### Expected Behavior
Existing Managed disk gets attached to VM without recreating the VM.

### Actual Behavior
The VM gets destroyed and recreated from scratch.

When adding a Managed Disk with the "Empty" option however, it works as expected -> here the VM just gets reconfigured, not recreated.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1 `terraform plan`
2. `terraform apply`

**Comment by meherk** [comment]
Any update on this?

**Comment by meher1993** [comment]
Any update on this?
