### ISSUE TITLE
Unable to create AWS IAM policy with single Principal key

### ISSUE THREAD

**Issue by alexwlchan** [hashicorp/terraform#14274]
I couldn’t find an existing bug for this. I might be misunderstanding something about how IAM works – right now I’m not entirely sure what the cause of my problem is, but either way this seemed like it might be a bug.

### Terraform version

```console
$ terraform -version
Terraform v0.9.4
```

### What I'm trying to do

I’m using the Amazon Elasticsearch service. I’ve set up an ES domain, and in the console I create an access policy using the template "Allow access to the domain from specific IP(s)". That produces a policy which looks like this:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Condition": {
        "IpAddress": {"aws:SourceIp": ["1.2.3.4"]}
      },
      "Resource": "arn:aws:es:eu-west-1:123456789:domain/name_of_domain/*"
    }
  ]
}
```

I’d like to replicate this policy in Terraform. My difficulty is getting the `Principal` key right – I’m going to ignore the other keys for now, as I can replicate them successfully.

I put together the following HCL:

```hcl
data "aws_iam_policy_document" "all_access" {
  statement {
    actions   = ["*"]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = ["*"]
    }
  }
}
```

### Expected behaviour

This produces a Principal key that matches the policy provided by Amazon, i.e.

```json
"Principal": {"AWS": "*"}
```

### Actual behaviour

It produces the following JSON:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*",
      "Principal": "*"
    }
  ]
}
```

Notice that Principal is `"*"`, rather than a dictionary.

### A second attempt

If I add a second principal to the HCL:

```hcl
data "aws_iam_policy_document" "all_access" {
  statement {
    actions   = ["*"]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = ["*"]
    }

    principals {
      type        = "Service"
      identifiers = ["firehose.amazonaws.com"]
    }
  }
}
```

I get a map in the Principal field, but I’ve had to add an extra principal that I might not care about:

```json

  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*",
      "Principal": {
        "AWS": "*",
        "Service": "firehose.amazonaws.com"
      }
    }
  ]
}
```

### The crux of it

I’m not fully versed in how AWS Principals work, and so perhaps `"Principal": "*"` is equivalent to `"Principal": {"AWS": "*"}` and I don't realise.

If not, Terraform's behaviour seems a little inconsistent depending on how many principals are declared – and how am I supposed to construct a dict-style Principal that has a single key?

**Comment by catsby** [comment]
Hello -

According to the AWS documentation on Princapals, these two are equivalent: 

```
"Principal": "*"
```
```
"Principal" : { "AWS" : "*" }
```

Those both amount to "Everyone (anonymous users)" here:

- http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Principal
