### ISSUE TITLE
String is not interpolated for resource provider alias

### ISSUE THREAD

**Issue by scriptjs** [hashicorp/terraform#14273]
The provider cannot be interpolated from an expression to look up the appropriate provider alias.

### Terraform Version
0.9.4

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_images_image_v2

### Terraform Configuration Files
```hcl
variable openstack_tenants {
  default = [
    "openstack.aliased_tenant_0",
    "openstack.aliased_tenant_1"
  ]
}
variable name {}
variable local_file_path {}
variable name {}

provider "openstack" {}
provider "openstack" {
  alias = "aliased_tenant_0"
  tenant_name = "aliased_tenant"
}
provider "openstack" {
  alias = "aliased_tenant_1"
  tenant_name = "another_tenant"
}

resource "openstack_images_image_v2" "tenant_images" {
  provider = "${element(var.openstack_tenants, count.index)}"
  name = "${var.name}"
  local_file_path = "${var.local_file_path}"
  container_format = "bare"
  disk_format = "qcow2"
  visibility = "private"
  min_ram_mb = "384"
  min_disk_gb = "8"
  region = "${var.region}"
  count = "${length(var.openstack_tenants)}"
}
```
### Expected Behavior
Interpret the expression to produce the provider alias in the resource to enable execution of the loop.

### Actual Behavior
Throws an error:
```
Error asking for user input: 1 error(s) occurred:

* openstack_images_image_v2.tenant_images: provider ${element(var.openstack_tenants, count.index)} couldn't be found
```
### Steps to Reproduce
1. `terraform plan`

NOTE: This works when provider in the resource is set to what ought to be interpolated ie. provider = "openstack.aliased_tenant_0" but does not work when an expression is used that ought to be first evaluated.   "openstack.aliased_tenant_0" and "openstack.aliased_tenant_1" are contrived in the above example so as not to leak identities of tenants on the private cloud.

**Comment by apparentlymart** [comment]
Hi @scriptjs!

At present this is an intentional limitation due to the fact that providers need to be known very early on in Terraform's lifecycle, before interpolation is possible. This might change in future, but there are no immediate plans for this.

The existing issue #3656 is already covering this request, so I'm going to close this one just to consolidate the discussion over there.
