### ISSUE TITLE
aws_db_option_group - OEM_AGENT

### ISSUE THREAD

**Issue by itunesnosignup** [hashicorp/terraform#14284]
Hi,
I am using the following snippet:
option {
    option_name = "OEM_AGENT"
vpc_security_group_memberships=["abc"]
port = "xxx"
  option_settings {
              name  = "OMS_PORT"
              value = "xxx"}
            option_settings {
              name  = "OMS_HOST"
              value = "xxx"}
            option_settings {
              name  = "AGENT_REGISTRATION_PASSWORD"
              value = "xxx"}

Terraform apply says:
OEM_AGENT option requires a version number. Valid versions are 12.1.0.4.v1,12.1.0.5.v1

I add 
version = "12.1.0.5.v1"

and I get:
option.4: invalid or unknown key: version

option_settings {
              name  = "version"
              value = "12.1.0.5.v1"}
also produces an error:
Error modifying DB Option Group: InvalidParameterValue: We do not support setting: version for OEM_AGENT

**Comment by itunesnosignup** [comment]
The JSON output for this variable is:
                    "OptionVersion": "12.1.0.5.v1",

**Comment by paddycarver** [comment]
Have you tried using `AGENT_VERSION` as the name? That's what I'd guess, based on the [AWS docs](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Oracle.Options.OEMAgent.html).

**Comment by itunesnosignup** [comment]
Hi,
Yes I tried that - same error:
invalid or unknown key: agent_version
and
invalid or unknown key: AGENT_VERSION
