### ISSUE TITLE
aws_ebs_volume tags are not set anymore

### ISSUE THREAD

**Issue by michelvocks** [hashicorp/terraform#14310]
### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
aws_ebs_volume

### Terraform Configuration Files
```hcl
resource "aws_volume_attachment" "ebs_att" {
  device_name  = "/dev/xvdf"
  volume_id    = "${aws_ebs_volume.ebs_volume.id}"
  instance_id  = "${aws_instance.my_ec2_instance.id}"
  force_detach = true
}

resource "aws_instance" "my_ec2_instance" {
  ami                    = "${var.ami["app"]}"
  instance_type          = "${var.instance_type}"
  subnet_id              = "${var.sn["app_a"]}"
  vpc_security_group_ids = ["${aws_security_group.my_sg.id}"]
  availability_zone      = "${var.az_names["az_a"]}"

  root_block_device {
    volume_type           = "gp2"
    volume_size           = 20
    delete_on_termination = true
  }
}

resource "aws_ebs_volume" "ebs_volume" {
  size              = 100
  availability_zone = "${var.az_names["az_a"]}"
  type              = "gp2"
  tags              = "${merge(var.aws_tags, map("Name", "my_ebs_volume"))}"

  lifecycle {
    prevent_destroy = false
  }
}

variable "aws_tags" {
  default = {
    topic             = "my_topic"
    stage             = "dev"
  }
}
```

### Debug Output
```
~ aws_instance.my_ec2_instance
    volume_tags.%:                 "2" => "0"
    volume_tags.Name:              "my_ebs_volume" => ""
    volume_tags.stage:             "dev" => ""
    volume_tags.topic:             "my_topic" => ""
```

### Expected Behavior
Tags should be set to aws_ebs_volume.

### Actual Behavior
Tags are not set to aws_ebs_volume. If tags are present, they will be destroyed. 
Output also looks odd. It shows 'aws_instance' as output but actually removes tags from aws_ebs_volume.

### Steps to Reproduce
terraform apply (maybe with old version for example 0.9.1)
terraform apply (with new version 0.9.4)

### Important Factoids
No.

### References
No.

**Comment by michaelsauter** [comment]
I experience the same issue on 0.9.4.

Output:

```
Path: terraform.tfplan

~ aws_instance.foo.0
    volume_tags.%:    "2" => "0"
    volume_tags.Env:  "abc" => ""
    volume_tags.Name: "xyz-1" => ""

~ aws_instance.foo.1
    volume_tags.%:    "2" => "0"
    volume_tags.Env:  "abc" => ""
    volume_tags.Name: "xyz-2" => ""

~ aws_instance.foo.2
    volume_tags.%:    "2" => "0"
    volume_tags.Env:  "abc" => ""
    volume_tags.Name: "xyz-3" => ""


Plan: 0 to add, 3 to change, 0 to destroy.
```

I have 3 instances, each with 3 volumes and 3 volume attachments. If I apply the change, then run again, it tries to modify other tags. It always changes, it never "stops".

**Comment by stack72** [comment]
Hi @michelvocks 

I just released terraform 0.9.5 which will solve this issue for you - apologies for the regression. Please can you let me know if all is ok now?

thanks

Paul

**Comment by danbell** [comment]
Terraform 0.9.5 solved it for me!

**Comment by michaelsauter** [comment]
@stack72 Thanks for looking into this so quickly. 0.9.5 solved it for me too.

**Comment by stack72** [comment]
great news! thanks so much for confirming :)
