### ISSUE TITLE
GitHub team membership fails to add administrator as team maintainer

### ISSUE THREAD

**Issue by davidalger** [hashicorp/terraform#14323]
### Terraform Version
v0.9.4

### Affected Resource(s)
- github_team_membership

### Terraform Configuration Files
```hcl
resource "github_team" "bug1" {
  name        = "Bug Test"
  privacy     = "closed"
}

resource "github_team_membership" "bug1-davidalger" {
  team_id  = "${github_team.bug1.id}"
  username = "davidalger"
  role     = "maintainer"
}
```

### Expected Behavior
The team is created and the user assigned successfully per the following plan output:

```
+ github_team.bug1
    name:    "Bug Test"
    privacy: "closed"

+ github_team_membership.bug1-davidalger
    role:     "maintainer"
    team_id:  "${github_team.bug1.id}"
    username: "davidalger"
```

### Actual Behavior
The following error message is output when running the plan:

```
Error applying plan:

1 error(s) occurred:

* github_team_membership.bug1-davidalger: 1 error(s) occurred:

* github_team_membership.bug1-davidalger: PUT https://api.github.com/teams/2355584/memberships/davidalger: 422 User is already an admin of this organization, so they can't be promoted to a team maintainer. [{Resource:TeamMember Field:user Code:already_org_admin Message:}]
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
- The user 'davidalger' in the example above is an administrator of the GitHub organization
- Commenting out `role` input on `github_team_membership.bug1-davidalger` allows the plan to apply successfully, but running plan immediately following then shows an imminent change:

```
-/+ github_team_membership.bug1-davidalger
    role:     "maintainer" => "member" (forces new resource)
    team_id:  "2355584" => "2355584"
    username: "davidalger" => "davidalger"
```

**Comment by damacus** [comment]
The really nice thing about the API in this case too, is it'll allow you to add it as a member. It then changes that user to a maintainer in the background. So on subsequent runs it wants to change it back to member.

**Comment by damacus** [comment]
I've raised a ticket with github support for this one. I'll post here any updates.
