### ISSUE TITLE
Deleting DigitalOcean droplets fails for terraform destroy

### ISSUE THREAD

**Issue by aknuds1** [hashicorp/terraform#14329]
### Terraform Version
0.9.4

### Affected Resource(s)
- digitalocean_droplet

### Terraform Configuration Files
[Tectonic Installer Terraform config for DigitalOcean](https://github.com/aknuds1/tectonic-installer/tree/e4cd2ae4028c3b409d39ff45faa8346d5e084b83/platforms/digitalocean)

### Debug Output
[Debug log gist](https://gist.github.com/aknuds1/7ea46bd557f5ed11c36cedd8760f74f5)

### Expected Behavior
I am trying to delete my DigitalOcean droplets created with Terraform, via `terraform destroy`.

### Actual Behavior
Terraform bails with an error per droplet it's trying to delete: `digitalocean_droplet.etcd_node.0: Error deleting droplet: invalid character 'S' looking for beginning of value`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Clone the [Tectonic Installer repository](https://github.com/aknuds1/tectonic-installer/commit/e4cd2ae4028c3b409d39ff45faa8346d5e084b83) into `$GOPATH/src/github.com/coreos/tectonic-installer`
2. Install Yarn
3. Create DigitalOcean droplets: `PLATFORM=digitalocean make apply`
4. Delete DigitalOcean droplets: `PLATFORM=digitalocean make destroy`

**Comment by aknuds1** [comment]
I think what's happening is that DigitalOcean is receiving maintenance currently, and the API is down as a result. Terraform is probably not parsing the error it's getting back from DigitalOcean API properly.

**Comment by aknuds1** [comment]
I've checked and the API returns status code 503 when trying to delete a droplet, along with the error message "Server Error", which probably causes the exception in Terraform: `invalid character 'S' looking for beginning of value`.

**Comment by Noah-Huppert** [comment]
For future Googlers:  
I encountered this error while I was trying to resize a `digitalocean_droplet` and I gave it an invalid size.

I was attempting to resize from `size = "512mb"` to `size = "2048mb"`, turns out the api uses `size = "2gb"` instead, I just assumed it kept using mb.

**Comment by Noah-Huppert** [comment]
Ok this is actually a bug I believe, terraform fails to resize my droplet every time, even if I have the correct size.
