### ISSUE TITLE
Make terraform version available in provider code

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#1433]
Talking with @sparkprime on IRC, who was working on setting a reasonable User-Agent for the google cloud provider's HTTP client, we realized that there's no easy way for plugins to get at the `main.Version` and `main.GitCommit` constants.

That is, unless I'm missing something.

@mitchellh how do you think we could move the version data somewhere that plugins could see it?

**Comment by sparkprime** [comment]
I'm keen on getting that User-Agent in ASAP so we can start looking at usage metrics.

**Comment by sparkprime** [comment]
@mitchellh what do you think?

**Comment by sparkprime** [comment]
After discussion on IRC we decided to proceed with no version number in the useragent for now  https://github.com/hashicorp/terraform/pull/1547

**Comment by phinze** [comment]
`terraform.Version` is a thing now!
