### ISSUE TITLE
Feature Request: Provide Setting to disable remote output when using provisioners

### ISSUE THREAD

**Issue by aaronmell** [hashicorp/terraform#14331]
So for example, I am running a script via inline that requires me to pass in a username and password. However, the remote-exec outputs the inline command it is running that contains the password as an argument. 

A sensitive_input flag added to provisioners should suppress the input being passed so it doesn't end up in a log file.

**Comment by pkolyvas** [comment]
I am hopeful that the collection of features being released in Terraform `0.14` under the banner of sensitive values  coupled with #26611 will mean some expression of this desire is now possible. 

Discuss post about sensitive values: https://discuss.hashicorp.com/t/terraform-0-14-suppressing-variable-values-in-cli-output/15758/2
