### ISSUE TITLE
Upgrade Kubernetes client library -> k8s.io/client-go

### ISSUE THREAD

**Issue by ctavan** [hashicorp/terraform#14347]
@radeksimko in https://github.com/hashicorp/terraform/issues/14227#issuecomment-299886452 you've mentioned that you are planning to upgrade to `1.6.x` Kubernetes client library.

I gave it a shot yesterday and tried to upgrade the vendored Kubernetes libs using

```
govendor fetch k8s.io/kubernetes/...@v1.6.2
```

however it appears to me that a lot of the stuff that was still included in `k8s.io/kubernetes/...@v1.5.3` has been moved to the standalone client library [`k8s.io/client-go`](https://godoc.org/k8s.io/client-go).  E.g. `k8s.io/kubernetes/pkg/client/restclient` seems to have moved to [`k8s.io/client-go/rest`](https://godoc.org/k8s.io/client-go/rest)

For some weird reason I'm unable to vendor `client-go` though.

I've tried

```
govendor fetch k8s.io/client-go/...@v2.0.0
```

which completes with 0-exit-code and without any error message but doesn't put anything to `vendor/` and also doesn't update `vendor/vendor.json`.

Have you already been working on this? Any hints on how I could successfully vendor the new client? I'd be happy to migrate some of the existing code to the updated libraries, but I'm just stuck not being able to vendor the new client…

I hope that by upgrading the client we would also solve some issues around Google Container Engine that arose recently when the way `gcloud` configures container cluster credentials was changed, see https://github.com/kubernetes/kubernetes/issues/30617 and https://github.com/kubernetes/kubernetes/pull/41653

**Comment by radeksimko** [comment]
Hi @ctavan 
thank you for your interest in working on this.

At this point in time I'd like hold off on any K8S API/SDK upgrades and discussions/debugging around it until we deliver all stable (v1) resources. We already have users which are on older versions of K8S wanting to use Terraform and I don't want those users to be forced to upgrade K8S just to use a certain resource.

I can't provide any timelines for when this will be done, but the good news is that there isn't many left - `Pod` is in review process, I have `Service` nearly done, currently working on `ReplicationController`. Next up will be `ServiceAccount` and `HorizontalPodAutoscaler`.

The best way to help us getting there would be to start from the end of the list - i.e. `HorizontalPodAutoscaler`. That way we can avoid stamping on each other's toes.

Thank you for the patience and understanding. 😉

**Comment by ctavan** [comment]
@radeksimko thanks for the quick reply! The roadmap makes sense!

I can't promise that I'll find the time working on resources where I don't have personal interest in using them (unfortunately `HorizontalPodAutoscaler` currently is among those resources) but I'll post a brief notice here in case I will start working on it.

I will close this issue for now. Since there's a clear roadmap for the Kubernetes provider I don't see much use in keeping this issue open for now.
