### ISSUE TITLE
Can't ssh-connect to newly created instance with a key_name

### ISSUE THREAD

**Issue by MarounMaroun** [hashicorp/terraform#14348]
### Terraform Version
v0.9.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_key_pair

### Terraform Configuration Files
```hcl
resource "aws_instance" "web" {
  subnet_id = "${aws_subnet.main.id}"
  vpc_security_group_ids = ["${aws_security_group.allow_all.id}"]
  ami = "${var.aws_ami}"
  instance_type = "t2.nano"
  key_name = "${aws_key_pair.auth.id}"
  tags {
    "Name" = "instance1"
  }
}

resource "aws_key_pair" "auth" {
  key_name   = "Terraform key"
  public_key = "${file("/tmp/tf_temp/key.pub")}"
}
```

### Debug Output
`terraform apply` returns success, nothing interesting in the debug log.

### Expected Behavior
I expect to successfully ssh-connect to the instance

### Actual Behavior
I can't ssh-connect to the newly created instance, and asked to enter the password:

```
ssh username@address -i key
address's password:
```

After running `ssh` with `-v`, I get:
```
debug1: Skipping ssh-dss key example@com - not in PubkeyAcceptedKeyTypes
```

I tried to add `PubkeyAcceptedKeyTypes=+ssh-dss` to the ssh config file, but that didn't help.

**Comment by wzalazar** [comment]
I have the same issue.

**Comment by AndresPineros** [comment]
It seems like Terraform is completely broken here. I've bent backwards trying to get this to work, but I the only success I've had is with a connection{} block with a private key defined, which sucks.

**Comment by MarounMaroun** [comment]
Can someone please update on this?

**Comment by leriel** [comment]
I just had this issue, but in my case it was because of the AMI i was using. Depending on the AMI, you may be required to use different username. I was using coreos AMI as per https://github.com/terraform-providers/terraform-provider-aws/blob/master/examples/ecs-alb/main.tf#L65 and trying to log in with `root`, which failed.

Similar is with ECS AMIs which for example tell you to login as ec2-user.

When i used username matching AMI, i was able to ssh into instance

Please note: ec2 console/connect dialog will *always* say root@ipaddress, regardless if you can actually log in as root.

**Comment by abarax** [comment]
I am also having this issue. I get "Too many authentication failures Authentication failed."

But I see no reason this should not be working.

**Comment by leriel** [comment]
@abarax what AMI ID are you using? maybe i'll be able to help

**Comment by daniilyar** [comment]
Reproduces for me on latest Terraform 0.11.3. I create 5 instances with same key pair name and security groups with Terraform, all in same subnet and one or two of these instances will not allow you to SSH in with a proper key after created. If you drop instances and create them again, the other one or two becomes inaccessible via SSH, but on each re-creation I can't achive all instances to be accessible. 

I am absolutely sure that it is not SSH key issue and not AWS networking or security groups issue. It is something with Terraform.

In my case, I use Terraform to create instances with key pair that was created manually and is not managed by Terraform. I will try to make the key pair managed by Terraform and see what happens

**Comment by leriel** [comment]
@daniilyar sounds like they all are also using same AMI and same `user_data`, but i'll ask just to make sure.

**Comment by daniilyar** [comment]
@leriel , yes, same AMI and empty (default) user_data for all

**Comment by daniilyar** [comment]
I will try to make some minimalistic example for reproducing

**Comment by oniabifo** [comment]
Has anyone been able to fix this issue please? i ran bash ~/terraform.sh apply and everything worked fine until it wanted to ssh into the system. 

It returned with an error
 **"1 error(s) occurred:

* aws_instance.web: 1 error(s) occurred:

* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain"**

Also tried ssh directly into the system, and it returned a broken pipe error

**Comment by aug70** [comment]
Came across same problem. Switching from Ubuntu 18(ami-14c5486b) to Ubuntu 16(ami-13be557e) worked for me too.

**Comment by sudhishkr** [comment]
Hitting the same issue with `ami-43a15f3e` which is Ubuntu 16.

Looking through the AWS Console, i see the key-pair associated with the EC2 instance - but I can't get into that instance.

When I try to launch a new instance from the same ami, with the same key-pair - I am able to SSH.

**Comment by sudhishkr** [comment]
@aug70 / @robax - `ami-13be557e` i seem to be hitting the same problem still. is there any other image that you have tried and is working?

@robax - Also what was the root-cause that makes you tell it was not terraform?

**Comment by robax** [comment]
@sudhishkr We're having success with `ami-f3211396` and `ami-f11a2894` (both Ubuntu 18, I can't find the IDs you mentioned). Maybe there is an issue with Terraform's `aws_key_pair` (I never got it to work), but using a connection block on a null resource is working for our use case so we are happy.

**Comment by saucec0de** [comment]
The following has worked for me.
I have added in my client the following line (~/.ssh/config):
`IPQoS throughput`

Also, before you go on changing the config file, you can test the setting like this:
`ssh -o IPQoS=throughput ...` 

NOTE: original reference was taken from here: https://communities.vmware.com/thread/590825
