### ISSUE TITLE
ebs_block_device change in aws_launch_configuration isn't seen as a change

### ISSUE THREAD

**Issue by kureci** [hashicorp/terraform#14350]
### Terraform Version
v0.8.2

### Affected Resource(s)
- aws_launch_configuration

### Expected Behavior
Terraform should see change in `aws_launch_configuration` in plan, and apply accordingly.

### Actual Behavior
Terraform doesn't see any change and therefore `ebs_block_device` change doesn't get applied.

### Steps to Reproduce
1. Set one or more `ebs_bock_device` in `aws_launch_configuration`
2. Plan and apply the change - you will end up with launch configuration that will have EBS block devices mapped
3. Remove `ebs_block_device` from launch configuration
4. Do a terraform plan - terraform says 'No change'

**Comment by catsby** [comment]
Hello @kureci – I'm sorry to say that this is a documented limitation of Terraform at the moment:

> NOTE: Changes to *_block_device configuration of existing resources cannot currently be detected by Terraform. After updating to block device configuration, resource recreation can be manually triggered by using the taint command

- https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

At this time, you need to manually `taint` the affected `aws_launch_configuration`
