### ISSUE TITLE
Cannot specify "-1" for all protocols aws_network_acl resource

### ISSUE THREAD

**Issue by neduma** [hashicorp/terraform#1435]
Cannot specify "-1" for all protocols in aws_network_acl resource configuration.

```javascript
  ingress = {
    rule_no = 200
    action = "allow"
    from_port   = "0"
    to_port     = "0"
    protocol    = "-1"
    cidr_block = "${var.public_subnet_cidr}"
  }
```

$ terrafrom plan -
no problems found.

$ terrraform apply

Got
* Invalid Protocol -1 for rule map[string]interface {}{"from_port":0, "to_port":0, "rule_no":100, "action":"allow", "protocol":"-1", "cidr_block":"17.0.0.0/8"}

**Comment by vitalis** [comment]
:+1:
