### ISSUE TITLE
Feature request: Kubernetes storage_class resource

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#14358]
StorageClass would be a great addition to the existing [Kubernetes resources](https://github.com/hashicorp/terraform/tree/master/builtin/providers/kubernetes).

### References

- [StorageClass docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storageclasses)

**Comment by radeksimko** [comment]
Hi @devth 
thanks for the interest in `kubernetes_storage_class`. It is something that is on my K8S todo list, but pretty much at the very end of it as it reached v1 in the recent K8S update (`1.6.0`).

We're currently pinned to `1.5.3` and intend to keep it that way until we cover all `v1` resources for that version.

I recently posted full explanation on why [here](https://github.com/hashicorp/terraform/issues/14347#issuecomment-300428233).
