### ISSUE TITLE
ComputedWhen doesn't work.

### ISSUE THREAD

**Issue by EvanKrall** [hashicorp/terraform#1436]
Per the docs on [schema.Schema](http://godoc.org/github.com/hashicorp/terraform/helper/schema#Schema).

Apparently you were aware of this already, but I couldn't find an issue about it.

**Comment by mitchellh** [comment]
We've decided not to implement this for now, we should just remove it from the schema. Sorry about misguiding you.

**Comment by roosmaa** [comment]
@mitchellh wouldn't implementing ComputedWhen actually solve #2694 ? As far as I understand the ECS TaskDefinition issue, then the ECS Service resource has no way of knowing that the ARN changed, and there is no way to invalidate the ARN when the `container_definitions` field changes for the TaskDefinition.

`ComputedWhen=["container_definitions"]` would probably be the way to fix ECS Service not picking up TaskDefinition changes, no?
