### ISSUE TITLE
Terraform attempting to dissociate the ipv6_cidr_block on aws_subnet

### ISSUE THREAD

**Issue by brianwallace** [hashicorp/terraform#14361]
It appears that terraform v0.9.4 is attempting to dissociate the `ipv6_cidr_block` on `aws_subnet` resources. According to the [docs](https://www.terraform.io/docs/providers/aws/r/subnet.html), `ipv6_cidr_block` is an optional field.  It should remain the Amazon provided ipv6 block.

`aws_subnet` resource:
```
resource "aws_subnet" "public" {
  vpc_id = "${aws_vpc.main.id}"
  availability_zone = "${element(split(",", var.azs), count.index)}"
  tags {
    Name = "${var.environment}-public${count.index}"
    Environment = "${var.environment}"
    KubernetesCluster = "${var.KubernetesCluster}"
  }
  map_public_ip_on_launch = true
  assign_ipv6_address_on_creation = true
  count = 3
  cidr_block = "${element(split(",", var.az_subnets), count.index)}"
}
```

Output of `terraform plan -out=tf.plan`:
```
~ module.template.aws_subnet.public.0
    ipv6_cidr_block: "2600:1f14:490:902::/64" => ""

~ module.template.aws_subnet.public.1
    ipv6_cidr_block: "2600:1f14:490:900::/64" => ""

~ module.template.aws_subnet.public.2
    ipv6_cidr_block: "2600:1f14:490:901::/64" => ""


Plan: 1 to add, 3 to change, 0 to destroy.
```

### Terraform Version
```
> terraform version
Terraform v0.9.4
```

### Affected Resource(s)
- aws_subnet

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
See above.

### Debug Output
None

### Panic Output
None

### Expected Behavior
Terraform should not try to remove the Amazon provided ipv6 cidr block -- it should remain.

### Actual Behavior
Instead of keeping the Amazon provided ipv6 cidr block, it tries to remove the entry.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an `aws_subnet` with the `assign_ipv6_address_on_creation = true` option.
2. `terraform plan -out=tf.plan`
3. `terraform apply tf.plan`

**Comment by catsby** [comment]
It seems `ipv6_cidr_block` needs to be `Computed` as well. It's not clear to me yet if it should only be computed if `assign_ipv6_address_on_creation` is true though, thoughts @stack72 ?

**Comment by stack72** [comment]
Hi @brianwallace 

Sorry for the issue here, I am trying to recreate this. I have used a very similar config to what you have created:

```
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "foo" {
	cidr_block = "10.10.0.0/16"
	assign_generated_ipv6_cidr_block = true
}

resource "aws_subnet" "foo" {
	cidr_block = "10.10.1.0/24"
	vpc_id = "${aws_vpc.foo.id}"
	map_public_ip_on_launch = true
	assign_ipv6_address_on_creation = true
}

```

When i ran this initially, I was able to get the following error:

```
Error applying plan:

1 error(s) occurred:

* aws_subnet.foo: 1 error(s) occurred:

* aws_subnet.foo: InvalidParameterValue: Invalid value 'true' for assign-ipv6-address-on-creation. Cannot set assign-ipv6-address-on-creation to true unless the subnet (subnet-3494ca53) has an IPv6 CIDR block associated with it.
	status code: 400, request id: 7080084c-46bd-4bed-90ad-4cea41c97ae1
```

Does this mean that you initially created the subnet, then manually added the IPv6 CIDR Block?

Paul

**Comment by brianwallace** [comment]
@stack72 Yes, I think you are right as I don't ever recall setting an IPv6 CIDR block in TF.  I think the subnet was created via TF, but then IPv6 addresses were manually enabled and AWS assigned a default CIDR block.
