### ISSUE TITLE
AWS DynamoDB partition key attribute type not tracked after creation

### ISSUE THREAD

**Issue by coingraham** [hashicorp/terraform#14374]
After creating a dynamodb table with a partition key, changing the attribute type doesn't cause an update.  The attribute type is ignored.

### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
aws_dynamodb_table

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "basic_hash_dynamodb_table" {
  name            = "test"
  hash_key        = "hash_id"
  read_capacity   = "5"
  write_capacity  = "5"

  # This is the Required Hash Key definition used above
  attribute {
    name          = "hash_id"
    type          = "N"  # Change this to "S" or "B" or "XXXXX" after creation
  }
}
```

### Expected Behavior
Terraform should notice the change in attribute type and rebuild the table.

### Actual Behavior
Nothing.  Terraform ignores the changes and let's the config conflict with the state.

### Steps to Reproduce

terraform apply (deploy the dynamodb table)
edit attribute type
terraform plan/apply (no changes seen)

**Comment by erickt** [comment]
I ran into this too. It appears that all changes to a dynamodb table aren't being saved to the statefile. I'm pretty sure this worked back in 0.8.x, but I haven't had time to confirm.
