### ISSUE TITLE
associate_public_ip_address forcing new resource when instance powered off

### ISSUE THREAD

**Issue by AlexLast** [hashicorp/terraform#14397]
### Terraform Version
```Terraform v0.9.5```

### Affected Resource(s)
- aws_instance

### Expected Behavior
- No resources were changed, a new resource should not be forced

### Actual Behavior
- A new resource is forced on apply

```associate_public_ip_address:       "false" => "true" (forces new resource)```

### Steps to Reproduce
1.  Create an AWS instance with associate_public_ip_address set to true
2. Stop said instance (in our case it's a bastion we want powered off)
3. terraform plan/apply
4. New EC2 instance resource will be forced

### Important Factoids
We want to have our bastion instance powered off when not in use, having this new resource forced creates a new instance any time the bastion is powered off and a change is made elsewhere. Can the instance status be checked to make sure it's running before this resource is forced? Thanks!

**Comment by LHCGreg** [comment]
I get the same behavior on 0.9.3.
