### ISSUE TITLE
aws_lambda_function source_code_hash is broken

### ISSUE THREAD

**Issue by lyptt** [hashicorp/terraform#14395]
### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
- aws_lambda_function

### Terraform Configuration Files
```hcl
variable "abc_archive_path" {}
variable "abc_archive_checksum" {}

resource "aws_lambda_function" "abc" {
  count = "${var.deploy_dev ? 1 : 0}"
  filename         = "${var.abc_archive_path}"
  function_name    = "abc"
  role             = "${aws_iam_role.middleware.arn}"
  handler          = "index.abc"
  source_code_hash = "${var.abc_archive_checksum}"
  runtime          = "nodejs6.10"
  timeout = 30
}
```

### Debug Output
```
# First terraform apply
aws_lambda_function.abc Modifying... (ID: abc)
  filename:         "/var/folders/yq/rv3z2hhn18l2l4k3963zcbn40000gp/T/abc_0.0.1_1494510308.zip" => "/var/folders/yq/rv3z2hhn18l2l4k3963zcbn40000gp/T/abc_0.0.1_1494510451.zip"
  source_code_hash: "VZJMp7u3ZC2ooo5P4b0iuikMW9ZoPHvdhnoWBgrSFdI=" => "axN4nkPlSFY0Uz3hamXYup00xMl1hYi2ZYBUNfgOsRU="

# Second terraform apply
aws_lambda_function.abc: Modifying... (ID: abc)
  filename:         "/var/folders/yq/rv3z2hhn18l2l4k3963zcbn40000gp/T/abc_0.0.1_1494510451.zip" => "/var/folders/yq/rv3z2hhn18l2l4k3963zcbn40000gp/T/abc_0.0.1_1494510733.zip"
  source_code_hash: "bA4cAbOegEg8c1Z8vWQrIAoRNKhbL0Sepy2Re+qHKOo=" => "axN4nkPlSFY0Uz3hamXYup00xMl1hYi2ZYBUNfgOsRU="
```

### Expected Behavior
What should have happened?
The tfstate should be updated with the correct hash, so that when I apply twice, the second apply does not perform any changes to the lambda function.

### Actual Behavior
What actually happened?
Every time I apply it changes the lambda function, the output shows that there's a brand new source hash every time, even though the hash is supposed to always the same. The tfstate is clearly not updating, and is being ignored when diffing the archive.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` - notice the checksum is recognised as being different
2. `terraform apply` - notice the checksum is still recognised as being different, even though the checksum value remains the same as the last apply

**Comment by bclodius** [comment]
@lyptt how are you computing the ```source_code_hash```?

It must be the sha256 hash.  I use this pattern which works flawless for me.  Before using this I would get diffs for doing anything else manually.

```
resource "archive_file" "lambda_archive" {
  source_file = "some_file.py"
  output_path = "/tmp/some_file.zip"
  type        = "zip"
}

resource "aws_lambda_function" "my_lambda_function" {
...
  filename         = "/tmp/some_file.zip"
  source_code_hash = "${archive_file.lambda_archive.output_base64sha256}"
...
}
```

**Comment by lyptt** [comment]
@bclodius I compute the hash externally from a python script as a base64 encoded SHA256 hash of my package version, as I only want to update the function when the version number changes.

**Comment by lyptt** [comment]
One thing to note here is the hash reported in the logs is always inconsistent to the tfstate - the tfstate's hash is completely ignored and it seems that terraform instead generates a hash and ignores my hash entirely, not persisting it to tfstate at all.

**Comment by lyptt** [comment]
Seems like checksums are an AWS concept (unclear from the terraform docs), so this is most likely an AWS edge case. The ability to prevent uploading unchanged lambda code can be achieved by not changing the filename. #themoreyouknow

**Comment by bclodius** [comment]
@lyptt You can try my example above to see if that fixes your issue.  I used to manually compute the sha256 as well but always had "inconsistencies".

I got the idea from https://github.com/hashicorp/terraform/issues/8501

**Comment by hsienchiaolee** [comment]
I am having the same issue on 0.9.8 where `source_hash_code` is not updated after applying changes. One notable thing is that when I first deployed the Lambdas, I did not specify the `source_code_hash`. I added it after the lambdas has been created. Here is an example of my code:
```
data "aws_s3_bucket_object" "package" {
  bucket = "${var.s3_bucket_name}"
  key    = "lambda-packages/python-package.zip"
}

resource "aws_lambda_function" "redshift-import" {
  ...
  runtime = "python2.7"
  s3_bucket = "${var.s3_bucket_name}"
  s3_key = "lambda-packages/python-package.zip"
  source_code_hash = "${data.aws_s3_bucket_object.package.etag}"
  ...
```
