### ISSUE TITLE
Support overwriting all variables in Terraform push

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#14406]
Terraform currently pushes _new_ variables to Terraform Enterprise as a part of `terraform push`. Individual variables can be _updated_, but must be specified with `-overwrite=<var>`.

Terraform should support overriding _all_ variables in a single push with a single option - e.g. `terraform push -overwrite-all`.

**Comment by teamterraform** [comment]
The `terraform push` feature no longer exists in current versions of Terraform, replaced by other Terraform Cloud functionality and with remote operations, so we're going to close this out now.
