### ISSUE TITLE
DB option groups with a failed IAM-related option apply do not detect missing options in subsqeuent plan

### ISSUE THREAD

**Issue by mattzimmerman** [hashicorp/terraform#14417]
### Terraform Version
0.9.4

### Affected Resource(s)
- aws_db_option_group

### Terraform Configuration Files
```hcl
resource "aws_db_option_group" "sql-server-options" {
  name = "sql-server-${var.environment}-options"
  option_group_description = "SQL Server backup options"
  engine_name = "${var.db-engine}"
  major_engine_version = "${var.db-major-engine-version}"
  option {
    option_name = "SQLSERVER_BACKUP_RESTORE"
      option_settings {
        name = "IAM_ROLE_ARN"
        value = "${aws_iam_role.sql-server.arn}"
      }
  }
}

resource "aws_iam_instance_profile" "sql-server" {
  name = "sql-server.${var.namespace}"
  role = "${aws_iam_role.sql-server.id}"
}

resource "aws_iam_role" "sql-server" {
  name = "sql-server.${var.namespace}"
  path = "/"
  assume_role_policy = <removed for brevity
}

resource "aws_iam_role_policy" "sql-server-backup" {
  name = "sql-server-backup.${var.namespace}"
  role = "${aws_iam_role.sql-server.id}"
  policy = <removed for brevity>
}
```

### Description
DB option groups with a failed option apply (I frequently see this on SQL Server DB option groups with an option that includes an IAM role for backing up/restoring to/from S3 buckets). 

Terraform successfully creates my new IAM role, immediately applies that as part of an option to the `aws_db_option_group`, but then that apply fails because the IAM resource isn't available from the AWS API yet. 

As an aside, it would be nice if terraform apply could wait for the role to become available before attempting to use it in a `aws_db_option_group` (but that is easy to work around by creating it and tracking the IAM role used for the option group in another terraform run prior to creating the option group).

However, when the Terraform run fails in this way (due to the newly-created IAM role and eventual consistency):

```
Error applying plan:
1 error(s) occurred:
* aws_db_option_group.sql-server-backup-options: 1 error(s) occurred:
* aws_db_option_group.sql-server-backup-options: Error modifying DB Option Group: InvalidParameterValue: IAM role ARN value is invalid or does not include the required permissions for: SQLSERVER_BACKUP_RESTORE
status code: 400, request id: d11b2c48-3426-11e7-977c-ddb68cb08401
```

I noticed that Terraform has lost track of the state of the option it was adding. Subsequent plan/apply attempts do not detect any changes, and the option group that is created from the initial run never actually gets the option added to it.

**Comment by hnarayan-2607** [comment]
I'm also facing the very same issue.

**Comment by srhopkins** [comment]
I haven't figured out a workaround; I was hoping a `depends_on = ["aws_iam_role_policy.restore"]` in the `aws_db_option_group` resource might work but it does not. Currently I am running a `-target` apply on the role and policy prior to the full run so the role stays in the same state file as the rest of the module.

**Comment by smastrorocco** [comment]
+1
