### ISSUE TITLE
Applying Security Group changes to aws_instance should update, not destroy/recreate

### ISSUE THREAD

**Issue by bloo** [hashicorp/terraform#14416]
### Terraform Version

0.9.4

### Affected Resource(s)

- aws_instance
- aws_security_group

### Expected Behavior

Altering aws_security_group definitions should recreate those, then update the aws_instances that were attached to them.

It looks like you can update instances via the AWS API:

http://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-attribute.html

### Actual Behavior

AWS instances are destroyed and recreated, instead of updated in place.

**Comment by grubernaut** [comment]
Hey @bloo, thanks for the issue!

Do you have an example configuration that can reproduce the issue? Thanks!

**Comment by bloo** [comment]
Thanks @grubernaut - below is a simple terraform that contains 2 `aws_security_group`s and 1 `aws_instance`. The instance references only 1 of the `security_groups` to start.

1. `terraform apply` - creates all 3 resources
2. uncomment line 13: `#"access-https"`
3. `terraform apply` - should update `aws_instance` in place, but instead destroys and recreates it.

```
provider "aws" {
  access_key = "???"
  secret_key = "???"
  region     = "us-east-1"
}

resource "aws_instance" "dummy" {
  ami               = "ami-6d1c2007"
  instance_type     = "t2.micro"
  availability_zone = "us-east-1a"
  security_groups = [
    "access-http",
    #"access-https"
  ]
}

resource "aws_security_group" "access-https" {
  name = "access-https"
  ingress {
    from_port = 443
    to_port = 443
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "access-http" {
  name = "access-http"
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

**Comment by bloo** [comment]
Hi @grubernaut - just wondering if there's anything more I can contribute to this?

**Comment by grubernaut** [comment]
Hey @bloo, extremely sorry, but I haven't had a chance to look at this issue yet. I'll attempt to dive in tomorrow!

**Comment by rfletcher** [comment]
@bloo Your example defines an EC2 Classic instance. In EC2 Classic, an instance's security groups can only be set at launch time. They can't be modified. That *is* possible for VPC instances though, and Terraform behaves as you expect there.

The EC2 Classic limitation is indicated (though subtly) by the AWS documentation you've linked in the original report (emphasis mine):

> --groups (list)
> 
> **[EC2-VPC]** Changes the security groups of the instance. You must specify at least one security
group, even if it's just the default security group for the VPC. You must specify the security group ID, not the security group name.

I don't think there's a Terraform bug here.

**Comment by bloo** [comment]
@rfletcher to clarify, I should use the 2nd parameter, not the first one - and it'll allocate a non-classic EC2 instance?

> `security_groups` - The associated security groups.
> `vpc_security_group_ids` - The associated security groups in non-default VPC

**Comment by rfletcher** [comment]
That's how you'll set any security groups once it is in VPC, but to launch it in VPC you need to specify the subnet. See the `subnet_id` param.

**Comment by bloo** [comment]
@rfletcher thanks for the clarification!

**Comment by grubernaut** [comment]
Thanks for the response here @rfletcher! :smile:
