### ISSUE TITLE
[OpenStack] region should not be required

### ISSUE THREAD

**Issue by bpo** [hashicorp/terraform#1441]
Trying out the OpenStack provider, this seemed a bit confusing to me. The `region` field is required for several resources in the OS provider, e.g. this will fail validation:

    resource "openstack_compute_instance_v2" "test-server" {
      name = "tf-test"
      image_id = "${var.imageid}"
      flavor_name = "m1.small"
      key_pair = "${var.keypair}"
      #region = ""
    }

I would have expected this value to just default to the empty string. Region specification (and/or the env variable OS_REGION_NAME) is not required by OpenStack or most clients - including nova.

The workaround if you don't have a region is just to uncomment the last line in the config and set the region field to an empty string explicitly on all resources.

**Comment by mitchellh** [comment]
Fixed by #1490
