### ISSUE TITLE
provisioner/chef: infinite loop

### ISSUE THREAD

**Issue by profiesto** [hashicorp/terraform#14422]
I am trying to provision an EC2 instance and let Chef configure the instance. The chef client is installed and configured by Terraform Chef provisioner. When I provide the chef client options with very little interval like say one minute and with a splay of one minute, Terraform provisions the instance, but the Chef provisioner goes into infinite loop (it keeps on running every minute) and the Terraform process never ends. Is the interval for chef client so less that Terraform cannot get the completed signal from Chef provisioner. I know that this is not a good interval to run chef client but I need to run this with that specific interval.

This is what I am using:
Terraform v0.9.4

```
resource "aws_instance" "instance" {
	ami = "${ami}"
	instance_type = "${var.instance_type}"
	subnet_id = "${var.subnet}"
	root_block_device {
		volume_type = "gp2"
		volume_size = "40"
	}
	vpc_security_group_ids = ["${var.sg}"]
	tags = {
		Name = "ec2-instance"
	}
	key_name = "awskey"

	provisioner "chef" {
		server_url = "${var.chef_server_url}"
		user_name = "${var.chef_user_name}"
		user_key = "${file("./artifacts/chef_cert.pem")}"
		node_name = "${aws_instance.instance.id}"
		fetch_chef_certificates = true
		**client_options = ["interval 60", "splay 30"]**
		recreate_client = true
		environment = "demo"
		run_list = ["role[chef-role]"]
		connection {
			host = "${aws_instance.instance.private_ip}"
			user = "centos"
			type = "ssh"
			private_key = "${file("./artifacts/key.pem")}"
			agent = false
		}
	}
}
```

**Comment by joemillerr** [comment]
I'm getting what looks like a loop in the chef provisioner as well using OpenStack. Below is a log block that spits out every 10 seconds.   The machine provision and connection before this step are both successful.

`openstack_compute_instance_v2.test: Still creating... (7m10s elapsed)
2017/05/16 12:59:25 [DEBUG] dag/walk: vertex "provisioner.chef (close)", waiting for: "openstack_compute_instance_v2.test"
2017/05/16 12:59:25 [DEBUG] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "openstack_compute_instance_v2.test"
2017/05/16 12:59:25 [DEBUG] dag/walk: vertex "provider.openstack (close)", waiting for: "openstack_compute_instance_v2.test"
2017/05/16 12:59:25 [DEBUG] dag/walk: vertex "root", waiting for: "provisioner.chef (close)"
2017/05/16 12:59:30 [DEBUG] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "openstack_compute_instance_v2.test"
2017/05/16 12:59:30 [DEBUG] dag/walk: vertex "root", waiting for: "provisioner.chef (close)"
2017/05/16 12:59:30 [DEBUG] dag/walk: vertex "provider.openstack (close)", waiting for: "openstack_compute_instance_v2.test"
2017/05/16 12:59:30 [DEBUG] dag/walk: vertex "provisioner.chef (close)", waiting for: "openstack_compute_instance_v2.test"
openstack_compute_instance_v2.test: Still creating... (7m20s elapsed)`

**Comment by svanharmelen** [comment]
@profiesto can you provide the client logs? You can log to file by setting `log_to_file = true` in the provisioner block (https://www.terraform.io/docs/provisioners/chef.html#log_to_file-boolean)

@joemillerr the "loop" you see in the TF logs do not indicate an infinite loop. It just shows still waiting for the provisioner to finish. If you believe you have the same problem, then please also provide the client logs...

**Comment by joemillerr** [comment]
Opened a new issue @svanharmelen

**Comment by svanharmelen** [comment]
@profiesto can you provide the client logs? You can log to file by setting `log_to_file = true` in the provisioner block (https://www.terraform.io/docs/provisioners/chef.html#log_to_file-boolean)

**Comment by paddycarver** [comment]
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, or continue to have the problem described, please feel free to reply to this issue and we'll reopen it. Thanks!

**Comment by ikari7789** [comment]
@paddycarver I think I may be experiencing this issue. I'll be able to provide some logs next Monday, but basically it was showing the progress of the Chef provision until about half-way through, and then just kept repeating `Still creating...`. I manually logged into the new VM and could confirm that the Chef client was still running without any issue. I believe the Chef client eventually failed, but yet Terraform still sits there in this forever loop waiting for some kind of completion.

**Comment by paddycarver** [comment]
Hi @ikari7789! Sorry you're having this problem. :( Any update on logs?

**Comment by vinoddevopscloud99** [comment]
I am also  still facing this issue.
