### ISSUE TITLE
provider/openstack device_type and disk_bus is missing from block_device

### ISSUE THREAD

**Issue by JorisAndrade** [hashicorp/terraform#14436]
Hi,

According to [openstack documentation](https://docs.openstack.org/developer/nova/block_device_mapping.html) with block_device you can set device_type and disk_bus but you can't define them using terraform [see there](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_compute_instance_v2.go#L207)

Could you please add it ?

Thanks in advance,

**Comment by jtopjian** [comment]
@JorisAndrade Yes, this should be possible. It first needs added to Gophercloud, though (the OpenStack Go library that Terraform uses). I will look into this, but just a heads up that it might take a few weeks.

**Comment by daoudiahmed** [comment]
@jtopjian 
Hello, I want to be able to create a virtual machine on CloudWatt (Openstack) via terraform. I have problems. I am on windows, my version of terraform is 0.9.5, my key pem is in the same folders as my files deploy.tf, provider.tf, variables.tf

Now I am told that * openstack_compute_instance_v2.web.1: Error creating OpenStack server: Expected
  HTTP response code [201 202] when accessing [POST https: //compute.fr1.cloudwatt
.com / v2 / ************* I hide my personal information here ********************* / servers], purpose Got 407 instead

  Would you have a concrete, complete and accurate exampwe of creation of VM on Openstack going through Terraform?

Thank you.

Ahmed DAOUDI.

**Comment by jtopjian** [comment]
@daoudiahmed Thanks for reporting this, but this seems to be an altogether separate issue than what is being discussed here. I recommend opening a new issue to discuss further.
