### ISSUE TITLE
Heroku domain exports invalid CNAME

### ISSUE THREAD

**Issue by arr-dev** [hashicorp/terraform#14434]
Hi there,

Heroku domain resource seems to export invalid CNAME, 
making it generate invalid DNS configuration which prevents automated certificates being issued.

I'd be willing to submit a PR to fix this.

### Terraform Version
Terraform v0.9.4

### Affected Resource(s)
- `heroku_domain`

### Terraform Configuration Files
```hcl
resource "heroku_domain" "www" {
  app      = "${heroku_app.labs.name}"
  hostname = "www.example.com"
}

output "cname" {
  value = "${heroku_domain.www.cname}"
}
```

### Expected Behavior
Exported attribute `heroku_domain.www.cname` should have the CNAME value set from [API](https://devcenter.heroku.com/articles/platform-api-reference#domain-info) 

### Actual Behavior
Exported attribute `heroku_domain.www.cname` is hardcoded in code to [APP.herokuapp.com](https://github.com/hashicorp/terraform/blob/5b085f4c44d7998eeb55004add966ecc73b54738/builtin/providers/heroku/resource_heroku_domain.go#L84)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
According to Heroku docs, using this CNAME will prevent certificates from being issued.
https://devcenter.heroku.com/articles/automated-certificate-management#verification-errors

**Comment by catsby** [comment]
I opened #14443 to address this before I noticed you mentioned you planned to fix it

**Comment by arr-dev** [comment]
No worries, thanks for fixing it.
