### ISSUE TITLE
Targeted aws_db_instance destruction does not respect explicit timeout settings

### ISSUE THREAD

**Issue by mattzimmerman** [hashicorp/terraform#14444]
### Terraform Version
0.9.4

### Affected Resource(s)
- aws_db_instance

### Terraform Configuration Files
```hcl
resource "aws_db_instance" "anonymizer-database" {
  identifier = "db-anonymizer"
  publicly_accessible = false
  instance_class = "${var.qa-db-instance-type}"
  storage_type = "${var.db-storage-type}"
  storage_encrypted = "${var.db-storage-encrypted}"
  
  engine = "${var.db-engine}"
  engine_version = "${var.db-major-engine-version}"
  allocated_storage = "${var.db-storage-limit}"
  username = "${var.rds-username}"
  password = "${var.rds-password}"

  license_model = "${var.db-license-model}"
  multi_az = "${var.db-multi-az}"
  backup_retention_period = "${var.db-backup-rentention-period}"

  skip_final_snapshot = true
  copy_tags_to_snapshot = true
  apply_immediately = "${var.db-apply-immediately}"

  vpc_security_group_ids = ["${aws_security_group.sql-server-anonymizer.id}"]
  db_subnet_group_name = "${data.terraform_remote_state.domain.persistence-subnet-group}"
  
  option_group_name = "${aws_db_option_group.sql-server-anonymizer-options.name}"

  timeouts {
    create = "45m"
    delete = "45m"
    update = "90m"
  }
}
```

### Debug Output
```
aws_db_instance.anonymizer-database: Destroying... (ID: db-anonymizer)
aws_db_instance.anonymizer-database: Still destroying... (ID: db-anonymizer, 10s elapsed)
...
aws_db_instance.anonymizer-database: Still destroying... (ID: db-anonymizer, 20m0s elapsed)
Error applying plan:
1 error(s) occurred:
* aws_db_instance.anonymizer-database (destroy): 1 error(s) occurred:
* aws_db_instance.anonymizer-database: timeout while waiting for resource to be gone (last state: 'deleting', timeout: 20m0s)
```

### Expected Behavior
`aws_db_instance` resource destruction should have waited 45 minutes before failing the terraform destroy run due to explicit timeout settings in the `aws_db_instance`.

### Actual Behavior
`aws_db_instance`destruction failed after a 20 minute timeout.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`terraform destroy -target="aws_db_instance.anonymizer-database" -input=false  -refresh=true -force`

**Comment by catsby** [comment]
Thanks @mattzimmerman I'll look into this. It may be related / fixed with #14396

**Comment by catsby** [comment]
This was finally addressed in https://github.com/terraform-providers/terraform-provider-aws/pull/949, thanks!

**Comment by Nareshkg** [comment]
Is this issue fixed? I have noticed the same error while destroying the oracle rds instance. the timeout was set for 4hrs for create/delete/update however the rds instance deletion timed out at 2hrs time..
