### ISSUE TITLE
Bug report: data output type is unknown

### ISSUE THREAD

**Issue by moudixtc** [hashicorp/terraform#14446]
Hi there,

The type of the output from the remote state data source is unknown

### Terraform Version
v0.9.5

### Affected Resource(s)
- terraform_remote_state data source

### Terraform Configuration Files
Here is my terraform_remote_state data source.
```hcl
data "terraform_remote_state" "infrastructure" {
  backend = "s3"

  config {
    bucket = "some_bucket"
    key    = "some_key"
    region = "som_region"
  }
}
```

This is where the data source is being used
```hcl
resource "aws_iam_instance_profile" "management_instance" {
  name_prefix = "${var.name}-instance-profile-"
  role = "${var.management_default_instance_role == "true" ? data.terraform_remote_state.infrastructure.management_ec2_role_name : var.management_instance_role}"
}
```

Here is the output declaration in the data source
```hcl
output "management_ec2_role_name" {
  value = "${aws_iam_role.management_ec2.name}"
}
```

### Expected Behavior
It should recognize the output type as a string. Previous versions work

### Actual Behavior
However, it's not able to recognize the type of the data source output, and there is no option in output to specify the type.

```
$ terraform plan
1 error(s) occurred:

* module.vpc.aws_iam_instance_profile.management_instance: 1 error(s) occurred:

* module.vpc.aws_iam_instance_profile.management_instance: At column 3, line 1: true and false expression types must match; have type unknown and type string in:

${var.management_default_instance_role ? data.terraform_remote_state.infrastructure.management_ec2_role_name : var.management_instance_role}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by danielnbarbosa** [comment]
I'm seeing the same thing, and not using a data source, just a resource attribute:
`kms_key_id              = "${var.papi_rds_storage_encrypted ? aws_kms_key.papi_rds.arn : ""}"`

here's my `terraform plan` output:

```
* module.named_common.aws_db_instance.papi: 1 error(s) occurred:

* module.named_common.aws_db_instance.papi: At column 3, line 1: true and false expression types must match; have type unknown and type string in:

${var.papi_rds_storage_encrypted ? aws_kms_key.papi_rds.arn : ""}
```

**Comment by apparentlymart** [comment]
Hi @moudixtc and @danielnbarbosa! Sorry for this regression.

I think this is the same issue that was discussed in #14399, which has now been fixed in master. The fix will be included in the next release. For now, please see that issue for a couple different workarounds to get around this problem until the next release is out.
