### ISSUE TITLE
resource google_sql_user doesn't support import

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#14440]
### Terraform Version

v0.9.5

### Affected Resource(s)

- google_sql_user

### Expected Behavior

`google_sql_user` resource type should support import.

**Comment by paddycarver** [comment]
Hi! Thanks for opening an issue. It looks like #14457 is making good headway on this. This comment is mostly to link the two and offer context for why I'm unassigning myself. :)

**Comment by danawillow** [comment]
Fixed in #14457

**Comment by devth** [comment]
Upgraded to 0.9.6 and tried this today. Error:

```
* import google_sql_user.mysql result: staging-mysql-us-central1-m/app: google_sql_user.mysql Error reading SQL User "app" in instance "staging-mysql-us-central1-m": googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```

I'm an Owner on the project so authz shouldn't be an issue.

**Comment by danawillow** [comment]
@devth can you open a new issue with more details? (debug logs would be a good start)

**Comment by devth** [comment]
@danawillow ok I opened https://github.com/hashicorp/terraform/issues/14998

Let me know if you need more info. Full logs are hard to provide as I need to scrub them all, but I can if necessary.
