### ISSUE TITLE
Changing root_block_device.volume_size forces new resource (aws_instance)

### ISSUE THREAD

**Issue by cweagans** [hashicorp/terraform#14445]
### Terraform Version
v0.9.5

### Affected Resource(s)
- aws_instance

#### Before:
```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"]
}

resource "aws_instance" "test_instance" {
  ami = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags {
    Name = "cweagans-test-instance"
  }
}
```

#### After:
```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"]
}

resource "aws_instance" "test_instance" {
  ami = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags {
    Name = "cweagans-test-instance"
  }

  root_block_device {
    volume_size = "100"
  }
}
```

### Expected Behavior
Root volume should have been resized from the default 8GB to 100GB without deleting the instance in the process.

### Actual Behavior
The instance was deleted and recreated.

### Steps to Reproduce
`terraform apply` the first config above, change config to the second one, and `terraform apply` again.

**Comment by majormoses** [comment]
As far as I know aws does not support such, at best we might be able to shutdown the instance resize the root ebs volume and spin it back up...This is dangerous road to go down...IMHO terraform should attempt to do this. To me this is exactly how I would expect it to work. I would recommend using Auto Scaling groups (even if you only have 1 machine and do not use any scale policies) as you can update this for NEW instances so you could bring up a new instance validate it works and terminate the old one.

**Comment by cweagans** [comment]
I'm able to resize an EBS volume without killing the instance through the AWS console. It doesn't resize the actual filesystem inside the volume of course, but the volume resize definitely works.

**Comment by majormoses** [comment]
interesting maybe my knowledge is out of date on this matter, you used to have to at least stop the vm first. Is that not true?

**Comment by stack72** [comment]
Hi @cweagans 

So I have spent some time investigating this and have been able to find the following:

* AWS **does not** support modifying root block device

<img width="513" alt="screen shot 2017-05-15 at 18 57 54" src="https://cloud.githubusercontent.com/assets/227823/26066699/71bd0900-39a0-11e7-96fc-8ebdb34ade3e.png">

* AWS does support changing the ebs volumes that can be attached

<img width="489" alt="screen shot 2017-05-15 at 18 58 51" src="https://cloud.githubusercontent.com/assets/227823/26066736/8e820112-39a0-11e7-93e7-3423a9bc9750.png">

Unfortunately, this is something outside of the control of Terraform so I am going to close this out - please let me know if there are any other questions

Thanks

Paul

**Comment by majormoses** [comment]
@stack72 I am able to do this so I do not believe that is correct:

![image](https://cloud.githubusercontent.com/assets/3145127/26067031/a53e45e4-394d-11e7-8b79-a4654c87e5f1.png)

![image](https://cloud.githubusercontent.com/assets/3145127/26067048/b4641012-394d-11e7-8092-aed52f98f75f.png)

![image](https://cloud.githubusercontent.com/assets/3145127/26067056/bf7e9670-394d-11e7-8891-4647b6500f7a.png)

**Comment by cweagans** [comment]
I'm seeing the same behavior as @majormoses. I'm able to modify the root EBS volume of a running instance without shutting it down.

Let's say that you *do* have to shut down an instance first to resize the volume, though. Would it not be better behavior to stop the machine, resize the volume, and then bring it back up without *destroying* the machine?

**Comment by majormoses** [comment]
> Let's say that you do have to shut down an instance first to resize the volume, though. Would it not be better behavior to stop the machine, resize the volume, and then bring it back up without destroying the machine?

Personally I am not comfortable with a modification like this as it requires too much context and  orchestration to do safely. I am more comfortable understanding the impact of destroy/recreate as this puts the operator (reviewer of plan before an apply) in a defensive/pessimistic stance to review and reject the plan which is healthy in these scenarios. Terraform should not concern itself with what is running on the box which is something that is important when deciding if a box can be safely restarted. Especially when you consider that it would not be the equivalent of asking the OS to shut down nicely (closing applications etc) it would be a hard reboot and could cause issues. I might be willing to make a flag that defaults to false to say do unsafe modifications but I don't think this is a good stance to take in general.

**Comment by cweagans** [comment]
> Especially when you consider that it would not be the equivalent of asking the OS to shut down nicely (closing applications etc) it would be a hard reboot and could cause issues.

That's fair. I hadn't thought about that.

They can be hot-resized as far as I can see, so that's probably the better path forward here anyway.

**Comment by majormoses** [comment]
> That's fair. I hadn't thought about that.

Yup that is why I prefer taking a more pessimistic approach, people (myself included) tend to forget about the operational complexities in the moment. 

> They can be hot-resized as far as I can see, so that's probably the better path forward here anyway.

Looks to be the case from the UI, if we can this via api I am all for it.

**Comment by majormoses** [comment]
@stack72 it seems possible and indeed is a new feature so we were both using outdated knowledge: https://aws.amazon.com/blogs/aws/amazon-ebs-update-new-elastic-volumes-change-everything/

**Comment by majormoses** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/considerations.html

> In some cases, your volume needs to be detached or the instance stopped for modification to proceed.

So it might still be an unsafe operation, more investigation is definitely required before implementing this. I worry about our error handling of this situation.

**Comment by majormoses** [comment]
@stack72 can we re-open for discussion it looks like its a new feature potentially available.

**Comment by majormoses** [comment]
@stack72 thanks for re-opening, I am not 100% sure we should do this as I pointed out here: https://github.com/hashicorp/terraform/issues/14445#issuecomment-301648116 its still somewhat dangerous but maybe we can make it an option to allow it? What do you think?

**Comment by daniilyar** [comment]
@stack72 , as a DevOps-as-a-service company, we have a lot of experience with Terraform and AWS, so our experience may help with the investigation and taking the proper decision.

Long story short:
1. For Linux instances AWS supports increasing root volume safely without re-attaching it, but *only for new-generation instances* (which are already >70%+ of the current AWS instances amount and keeps increasing).
2. For Windows instances AWS supports increasing root volume safely without re-attaching it for any instance type.

So, I believe that the proper fix for this one is to teach Terraform AWS provider to understand if it provisions the old generation instance or not. If it provisions the new-generation one, then it can modify volume in-place, otherwise the volume should be reattached on a stopped instance.

See more details at https://aws.amazon.com/premiumsupport/knowledge-center/expand-root-ebs-linux/ and https://aws.amazon.com/premiumsupport/knowledge-center/expand-ebs-root-volume-windows/

Please tell me if that helps and how else we can help here.
I proposed something already at https://github.com/terraform-providers/terraform-provider-aws/issues/768#issuecomment-403218026, so referencing it here for easier navigation

**Comment by daniilyar** [comment]
Not sure I understand why my comment unassigned @stack72 from the issue. I didn't want to do so :)

**Comment by majormoses** [comment]
@daniilyar not sure why it was unassigned  but the issue has been closed and migrated to the aws providers repo as part of the big split. Any comments should be made there.
