### ISSUE TITLE
provider/google-cloud add queue-scaling support to `autoscaling_policy` in resource `google_compute_autoscaler`

### ISSUE THREAD

**Issue by bmabey** [hashicorp/terraform#14453]
Google Cloud has an alpha feature for autoscaling based on a queue-based workload. Could the `google_compute_autoscaler` resource be updated so that the `autoscaling_policy` includes the relevant parameters for queue-based autoscaling?

Here are the docs for the new queue-based scaling feature:
https://cloud.google.com/compute/docs/autoscaler/scaling-queue-based

**Comment by danawillow** [comment]
Hi @bmabey, thanks for the FR! Right now Terraform doesn't support alpha/beta APIs due to some technical limitations, but we're planning on resolving those within the next few months. In the meantime, leaving this open so others can 👍  the issue if that's something they'd like to see as well.

**Comment by bmabey** [comment]
Thanks @danawillow. Is there an issue around the alpha/beta support you could point me to?

**Comment by danawillow** [comment]
There is now: https://github.com/hashicorp/terraform/issues/14742
