### ISSUE TITLE
Bitbucket Data Source?

### ISSUE THREAD

**Issue by saitheexplorer** [hashicorp/terraform#14458]
Hey all - new to Terraform, really liking it so far! Thanks for building a such a great tool.

I saw that there is a Bitbucket provider to manage webhooks, but the repositories must specified. I'm still learning TF, so please correct me if I'm wrong, but if we add a BB data source of all the repositories, I'd be able to loop through those repositories and set webhooks / default reviewers, right?

If so, I can take a stab at implementing this data source.

**Comment by grubernaut** [comment]
Hey @saitheexplorer, thanks for the issue! It looks like the resources in the bitbucket provider only require the repository name, and not the fully evaluated repository information. It might be worth trying to use a pre-created repositories name. 
However, adding a data source for a bitbucket repository would be helpful in a lot of other cases and would be a great addition if you still wished to tackle this one. Thanks!
