### ISSUE TITLE
Resource 'aws_ami_from_instance.manage-ami' does not have attribute 'id' for variable 'aws_ami_from_instance.manage-ami.id'

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform#14450]
### Terraform Version
0.9.5

### Affected Resource(s)
- aws_ami_from_instance

### Terraform Configuration Files
```
resource "aws_ami_from_instance" "manage-ami" {
  # since the name of the AMI includes a timestamp, this lifecycle rule prevents
  # the resource from being included for every time execution of apply/plan.
  lifecycle {
    ignore_changes = true
  }

  depends_on         = ["null_resource.bootstrap_frontend"]
  name               = "manage-${var.manage_version}-${lower(var.environment)}-${replace(timestamp(), ":", "")}"
  source_instance_id = "${aws_instance.frontends.id}"
}

resource "aws_launch_configuration" "manage" {
  depends_on                  = ["aws_ami_from_instance.manage-ami"]
  name                        = "launch configuration"
  image_id                    = "${aws_ami_from_instance.manage-ami.id}"
  instance_type               = "${var.aws_instance_type["frontend"]}"
  iam_instance_profile        = "sentinel"
  key_name                    = "${var.ssh_key_name}"
  security_groups             = ["sg-000000"]
  associate_public_ip_address = false
}
```

### Expected Behavior
The resource aws_ami_from_instance.manage-ami created a new AMI, so the AMI ID should be exported and usable by other resources.

### Actual Behavior
```
Error running plan: 1 error(s) occurred:

* aws_launch_configuration.manage: 1 error(s) occurred:

* aws_launch_configuration.manage: Resource 'aws_ami_from_instance.manage-ami' does not have attribute 'id' for variable 'aws_ami_from_instance.manage-ami.id'
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @haidangwa! Sorry this didn't work properly.

I think this is the same issue being discussed in #5185. In that issue, people reported that the problem went away after re-running `terraform apply` again. Is that true for you too, or is it persistent no matter how many times you apply?

**Comment by haidangwa** [comment]
@apparentlymart Re-running `terraform apply` makes no difference.

**Comment by haidangwa** [comment]
Since we use remote state (S3 backend), I ran `terraform state pull` after I'd already run `terraform destroy` and found this:
