### ISSUE TITLE
AWS provider configuration not available in delete module

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#1447]
Simliar to https://github.com/hashicorp/terraform/issues/1380#issuecomment-91244154

## Steps
* Create a `main.tf` that declares and configures the `aws` provider.
* Add a module (declares only aws resources, not the provider)
* `terraform apply` - everything is created
* Remove the module from `main.tf`
* Run `terraform plan`

Result:
```
 $GOPATH/bin/terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * provider.aws: "region": required field is not set
```

Tested using the following:
```
$GOPATH/bin/terraform --version
Terraform v0.4.1-dev (c0196d948d942a32a46fb9ef203076d3be134e4d)
```

**Comment by mitchellh** [comment]
Should be fixed!

**Comment by nekinie** [comment]
I'm seeing this exact issue in v0.6.9-dev

**Comment by jaygorrell** [comment]
Is there already an open version of this bug? It seems to be happening again, if it was ever fixed.

**Comment by apeeters** [comment]
The bug seems to resurface in TF 0.7.

**Comment by hazim1093** [comment]
as @apeeters  pointed out, we're facing the same bug again after upgrade to TF 0.7. 
We're using nested modules and while destroying them, terraform asks to enter value for region

**Comment by pmoust** [comment]
Experiencing the same in TF v0.7.3

**Comment by mewm** [comment]
I experienced this suddenly today. I'm not sure exactly what did it, but after nuking .terraform folder and running `terraform get` my plan could execute
