### ISSUE TITLE
GitLab provider enhancements

### ISSUE THREAD

**Issue by hauleth** [hashicorp/terraform#14471]
Currently there is only project management and hooks management it would be to provide more GitLab resources:

- [x] [Deploy keys](https://docs.gitlab.com/ce/api/deploy_keys.html#deploy-keys)
- [x] [Groups](https://docs.gitlab.com/ce/api/groups.html)
- [ ] [Build variables](https://docs.gitlab.com/ce/api/build_variables.html#create-variable)
- [ ] [Labels](https://docs.gitlab.com/ce/api/labels.html#create-a-new-label)
- [ ] [Boards](https://docs.gitlab.com/ce/api/boards.html#new-board-list)

Ref:

- #13898

**Comment by jugatsu** [comment]
It would be great to have `user` resource too.
