### ISSUE TITLE
Question about internal work with AWS API

### ISSUE THREAD

**Issue by andrey-iliyov** [hashicorp/terraform#14482]
### Terraform Version
Terraform v0.9.x

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "test_instance_record" {
  ...
count = 9
  ...
}
```

### Additional info.
Hi guys.
Can you please explain little bit about internal work of terraform?

If i will use provider AWS: aws_instance for creating clusters with "count" more then 2. So it will be a one request( request_id) to "AWS API" for creating all instances of cluster? Or it will be a separated requests to "AWS API" for creating each instance of cluster?
Thanks for info!

**Comment by grubernaut** [comment]
Hey @andrey-iliyov, thanks for the issue! 

Currently, Terraform makes a separate AWS API request (also happens for other providers as well) for each resource. Internally within the resource graph that Terraform builds, the `count` meta parameter folds each resource into a separate resource, thus requiring a separate API request for each resource. Terraform will often parallelize these requests where possible though.
We're planning on enhancing this functionality though, and allowing batch-requests to happen for similar resources, as the current approach definitely has an upper bound on efficiency. 
Hope this answers your question! Just to note, as well that the [community mailing list](https://www.terraform.io/community.html) may offer different solutions in the future. Thanks!

**Comment by andrey-iliyov** [comment]
Hi @grubernaut , thanks for your answer!
It will be a good idea to send "instance create requests" in one AWS API request.
Here the official answer from AWS support:

```hcl
You should send request about new instance resources in one API request. After that we can guaranty that all resources will be created on different hardware equipment.
```

So this is important when we creating cluster!

Jake, For adding this posibility, should i create the "issue". Or we already have the "issue"?
Thanks!

**Comment by grubernaut** [comment]
Hey @andrey-iliyov, the core enhancement issue is already opened here: https://github.com/hashicorp/terraform/issues/7388. 

I agree this is an incredibly important, and very useful addition to Terraform. I'll bring this issue up internally again and start pushing for planning this addition. Thanks!
