### ISSUE TITLE
terraform env select usage message misleading

### ISSUE THREAD

**Issue by jrandall** [hashicorp/terraform#14499]
When `terraform env select` is run on an environment name that does not exist, it reports an error:

```
$ terraform env select nonexistant

Environment "nonexistant" doesn't exist!

You can create this environment with the "-new" option.
```
The error message refers to a `"-new" option` which does not exist. The error message should probably say `"new" subcommand` instead.

Source line: https://github.com/hashicorp/terraform/blob/c6ad44de10af0e54864a17d742ca725f2068fb47/command/env_command.go#L60

**Comment by grubernaut** [comment]
Hey @jrandall, thanks for the issue! 

Looks like this was fixed in #14009, and should be released in Terraform `v0.9.5`.
