### ISSUE TITLE
Feature request - add -update flag for init command

### ISSUE THREAD

**Issue by antonosmond** [hashicorp/terraform#14506]
With backends and the `init` command, the recommended approach to prepare for a terraform run is now to use `terraform init` which initialises the backend, pulls any modules etc etc.
This has been great and I'm really glad the remote config issues have been resolved with backends. I did however get caught out by something today - I was referencing a module using the path to that module in GitHub e.g.
```
module "network" {
  source = "github.com/antonosmond/terraform-modules//network"
  ...
}
```
I made changes to the module and wanted to re-run `terraform apply`. Because I knew I had updated the module I ran `terraform init` first. 

My expectations were that the local copy of the module would be updated, but this didn't happen. I then found that `terraform get` has the same behaviour - it doesn't update modules by default. It does however have an `-update` flag which can be used to tell terraform to update the modules, even if they've already been downloaded.
I think it would make sense for the `init` command to have the same flag so we can avoid having to run both `terraform init` and `terraform get -update`.

**Comment by antonosmond** [comment]
I've opened a PR with this change: https://github.com/hashicorp/terraform/pull/14514
It's my 1st PR to terraform so if there's anything you need me to change, please let me know 😃

**Comment by apparentlymart** [comment]
Hi @antonosmond! Sorry for the long silence here.

It looks like we did eventually get this done over in #15267. I see that you and @fatmcgav both worked on PRs, and I'm sorry for that conflict! Since this has been long resolved, I'm going to close this out. Sorry I missed this issue when merging that PR earlier.
