### ISSUE TITLE
Kubernetes provider should allow setting config_path via KUBECONFIG env variable

### ISSUE THREAD

**Issue by ashishth09** [hashicorp/terraform#14505]
To be consistent with K8s way of setting the config - https://kubernetes.io/docs/tasks/administer-cluster/share-configuration/, I think we should change the _KUBE_CONFIG_ to  _KUBECONFIG_  [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/kubernetes/provider.go#L66)

I don't have any problem as such with current variable just that I frequently use KUBECONFIG to work with my cluster and think using same environment variable  as k8s would  provide  a better experience with the provider :smiley:

**Comment by radeksimko** [comment]
You're absolutely right @ashishth09 

I wish you came up with that suggestion in my initial K8S PR 😄  - I was wondering if there any standardized ENV vars and I couldn't find any at that time.

See https://github.com/hashicorp/terraform/pull/14889 which is addressing this.
