### ISSUE TITLE
Changing root_block_device in aws_launch_configuration results in no planned change

### ISSUE THREAD

**Issue by jurajseffer** [hashicorp/terraform#14503]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
aws_launch_configuration

### Terraform Configuration Files
```hcl
resource "aws_launch_configuration" "logstash" {
  ...
  lifecycle {
    create_before_destroy = true
  }
  root_block_device {
    volume_type           = "gp2"
    volume_size           = 100
    delete_on_termination = true
  }
}
```

### Expected Behavior
Changing the volume_size, volume_type etc should result in change being planned for the launch configuration.

### Actual Behavior
No change is planned. This happens also once the entire `root_block_device` block is removed.

**Comment by stack72** [comment]
Hi @jurajseffer 

I just opened a PR that fixes this issue

Thanks

Paul
