### ISSUE TITLE
aws_network_acl: ICMP parameters

### ISSUE THREAD

**Issue by pearkes** [hashicorp/terraform#1451]
We need to accept `icmpTypeCode` when specifying the ICMP protocol on network ACLs.

> ICMP protocol: The ICMP type and code. Required if specifying ICMP for the protocol.

http://docs.aws.amazon.com/cli/latest/reference/ec2/create-network-acl-entry.html

**Comment by pearkes** [comment]
Dupe of #1372, closing.

**Comment by dmangot** [comment]
https://github.com/hashicorp/terraform/issues/1372 referred to security groups, not aws_network_acl.   The use cases are not necessarily equivalent.   You wouldn't apply ICMP:Destination Unreachable to internet bound traffic because the Internet Gateway will limit to 1500 byte MTU anyway.
