### ISSUE TITLE
aws_config_config_rule input_parameters for AWS Managed Config Rules

### ISSUE THREAD

**Issue by eric-nord** [hashicorp/terraform#14518]
### Terraform Version
0.9.5

### Affected Resource(s)
- aws_config_config_rule

### Terraform Configuration Files
It is noted that input_parameter is only valid if source.owner is CUSTOM_LAMBDA.
As several AWS Managed Config Rules need params to function, it would be nice to be abled to add input_parameters to AWS MANAGED Config Rules like this:

```module "common_port_restriction_audit" {
	name ="common-port-restriction-enabled"
	source ="./aws-managed-config-rules"
	owner = "AWS"
	source_identifier ="RESTRICTED_INCOMING_TRAFFIC"
	input_parameters = <<EOF
{
	"smtp": 23
}
EOF
```

### Expected Behavior
add input_parameters for AWS Managed Config Rules. For instance
http://docs.aws.amazon.com/config/latest/developerguide/required-tags.html

### Actual Behavior
input_parameters is only valid if source.owner is CUSTOM_LAMBDA.

**Comment by Andrew-Poloni** [comment]
I have the same issue, thank you for opening this. :)

**Comment by Andrew-Poloni** [comment]
One workaround I've found is to create the AWS Config Managed rules via their AWS-supplied CloudFormation templates and have Terraform manage the templates for you and pass the parameters to the Config rules as parameters to the CF templates.

**Comment by pauljbrice** [comment]
Utilizing the input_parameters property for rule 'Properties' works for AWS Managed rules as long as the json is 'string' based.

Example:

```
resource "aws_config_config_rule" "managed-rule-01" {
  name = "REQUIRED_TAGS"

  #Convert this to a list later
  input_parameters = "{\"tag1Key\": \"Name\",\"tag2Key\": \"Description\",\"tag3Key\": \"BudgetCode\",\"tag4Key\": \"Owner\"}"

  source {
    owner             = "AWS"
    source_identifier = "REQUIRED_TAGS"
  }
}
```

**Comment by qafro1** [comment]
Regarding 
#Convert this to a list later
  input_parameters = "{\"tag1Key\": \"Name\",\"tag2Key\": \"Description\",\"tag3Key\": \"BudgetCode\",\"tag4Key\": \"Owner\"}"

Which one is the 'tag1value' from the input_parameters?
