### ISSUE TITLE
aws_eip diffs didn't match during apply

### ISSUE THREAD

**Issue by marvinnodora** [hashicorp/terraform#14512]
### Terraform Version
```
$ terraform -v
Terraform v0.9.5
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_eip

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_availability_zones" "zones" {
  state = "available"
}

resource "aws_instance" "primary" {
  ami               = "ami-af62d0cb"
  instance_type     = "t2.micro"
  availability_zone = "${element(data.aws_availability_zones.zones.names, count.index)}"
  count             = 1
}

resource "aws_instance" "failover" {
  ami               = "ami-af62d0cb"
  instance_type     = "t2.micro"
  availability_zone = "${element(aws_instance.primary.*.availability_zone, count.index)}"
  count             = "${aws_instance.primary.count}"
}

resource "aws_eip" "primary-eip" {
  count    = "${aws_instance.primary.count}"
  instance = "${element(aws_instance.primary.*.id, count.index)}"
}

resource "aws_eip" "failover-eip" {
  count    = "${aws_instance.failover.count}"
  instance = "${element(aws_instance.failover.*.id, count.index)}"
}
```

### Debug Output
https://gist.github.com/marvinnodora/af1a4d3532f6bd6c579774b4dff01169. For a more complete debug output, please reproduce this consistently reproducible issue instead as the full debug output seems to contain sensitive information.

### Panic Output
Terraform did not crash

### Expected Behavior
After an initial `terraform apply` of the config above and increasing the count to `2`, the subsequent `terraform plan` should result in 4 resources to add - 2 EIPs and and 2 instances and `terraform apply` should succeed.

### Actual Behavior
Instead, a plan of `Plan: 4 to add, 2 to change, 0 to destroy.` is shown and `terraform apply` fails as shown in the debug output.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
1. Change the argument `count` to `2`
1. `terraform apply`

### Important Factoids
Existing AWS infrastructure is being imported which requires 2 identical instances residing in the same availability zone, EIPs associated to each instance. 

### References
None

**Comment by NeuralSandwich** [comment]
+1

Terraform appears to be failing to notice aws_eip are do not exist.

**Comment by jbardin** [comment]
The eip resource appears to have since been updated to prevent getting into this state.
If you still have a reproduction case with the current versions of terraform and the aws provider, please feel free to open an updated issue against the terraform-aws-provider.
