### ISSUE TITLE
Cannot create aws_security group with both IPv4 and IPV6 open egress

### ISSUE THREAD

**Issue by ondrap** [hashicorp/terraform#14522]
This happens on Terraform v0.9.5.

Affected resources: aws_security_grup

```hcl
resource "aws_security_group" "test" {
  ingress {
      from_port = 22
      to_port = 22
      protocol = "6"
      cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks  = ["0.0.0.0/0"]
  }
  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    ipv6_cidr_blocks  = ["::/0"]
  }
  tags {
      Name = "test"
  }
}
```

### Debug Output
https://gist.github.com/ondrap/888e2dcc0018dcd9f99990eb5a0af1cb

Normal output:
https://gist.github.com/ondrap/660d1f8b14960f6772ce38b364819d4f

### Expected Behavior

Create a security group with open egress rules for 0.0.0.0/0 and ::/0 (both IPv4 and IPv6).

### Actual Behavior

It crashed. When I remove the IPv6 rule, it gets created correctly. When I `terraform apply` this rule again, the IPv6 egress gets removed.

It seems to me that it has something to do with the default; when no egress rule is used, an open IPv6 egress rule is created (I do have IPv6 enabled on the VPC and subnets).

### Steps to Reproduce

1. `terraform apply`

### References
 
I looked into #14382 where it is suggested to use the `ipv6_cidr_blocks` for IPv4 addresses and it doesn't work for me.

**Comment by stack72** [comment]
output:

```
* aws_security_group.test: Error authorizing security group egress rules: InvalidPermission.Duplicate: the specified rule "peer: ::/0, ALL, ALLOW" already exists
	status code: 400, request id: 03df8e5a-9fbe-4bc6-b922-9f80e89b2306
```

**Comment by ravenbyron** [comment]
I think this is related to default egress rules and maybe this code https://github.com/hashicorp/terraform/pull/1765 needing to be updated for ipv6...

This is just a guess as I just ran into the same issues, only happens on the initial run...

**Comment by shepdelacreme** [comment]
I'm experiencing the same issue on Terraform v0.9.6. Can recreate by just creating an empty security group in a VPC with IPv6 enabled.

```
resource "aws_security_group" "sg" {
  description = "testing"
  name = "test-test"
  vpc_id = "vpc-110011f4"
}
```

This SG should have no rules but if you check it does retain its default IPv6 egress rule. When trying to add the default IPv6 egress rule with a `aws_security_group_rule` resource you will get an error.

```
* aws_security_group_rule.sg_ipv6_cidr_rules.0: [WARN] A duplicate Security Group rule was found on (sg-xx363a95). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: ::/0, ALL, ALLOW" already exists
```

**Comment by stack72** [comment]
Hi all

I am currently working on a PR to fix this up right now

Thanks

Paul
