### ISSUE TITLE
Bug Message - when executing - Mismatch reason: diff RequiresNew; old: false, new: true

### ISSUE THREAD

**Issue by nestorbolivar** [hashicorp/terraform#14532]
### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
aws_instance

### Debug Output
https://gist.github.com/nestorbolivar/702e26f64817cde36ef1eb81f55eb29c.js

**Comment by apparentlymart** [comment]
Hi @nestorbolivar! Thanks for reporting this.

This seems to be the same as #13332, so I'm going to close this just to consolidate over there.
