### ISSUE TITLE
Apply no longer changing outputs

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#14541]
### Terraform Version
0.9.5

### Affected Resource(s)
- core

### Steps to Reproduce

Start with the following configuration:

```hcl
resource "null_resource" "example" {
  count = "1"
}

output "ids" {
  value = "${null_resource.example.id}"
}
```

Run `terraform apply` then `terraform output`:

```
$ terraform apply
# ...

$ terraform output
ids = 2302421808094106274
```

Change the configuration count to 2:

```diff
diff --git a/main.tf b/main.tf
index 0d1e36a..1ecbd05 100644
--- a/main.tf
+++ b/main.tf
@@ -1,5 +1,5 @@
 resource "null_resource" "example" {
-  count = "1"
+  count = "2"
 }
```

Execute `terraform apply`:

```text
$ terraform apply
null_resource.example: Refreshing state... (ID: 7370651337247051840)
null_resource.example.1: Creating...
null_resource.example.1: Creation complete (ID: 8269220107186649402)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path:

Outputs:

ids = 7370651337247051840
```

**Issue 1** - Previous versions of Terraform returned no outputs in this scenario `null_resource.example.id` should not be resolvable, since we now have a list of `null_resource.example`. Instead it's "caching" the value.

Run `terraform output`:

```text
$ terraform output
ids = 7370651337247051840
```

**Issue 2** - Previous versions of Terraform returned an error here instead. Here is the _previous error_ (note that there's no error now, which is another regression or undocumented change):

```text
The state file either has no outputs defined, or all the defined
outputs are empty. Please define an output in your configuration
with the `output` keyword and run `terraform refresh` for it to
become available. If you are using interpolation, please verify
the interpolated value is not empty. You can use the
`terraform console` command to assist.
```

Now run `terraform refresh`:

```
$ terraform refresh
null_resource.example.0: Refreshing state... (ID: 7370651337247051840)
null_resource.example.1: Refreshing state... (ID: 8269220107186649402)
```

Now run `terraform output` and observe the error is now present again.

```
$ terraform output
The state file either has no outputs defined, or all the defined
outputs are empty. Please define an output in your configuration
with the `output` keyword and run `terraform refresh` for it to
become available. If you are using interpolation, please verify
the interpolated value is not empty. You can use the
`terraform console` command to assist.
```

### Important Factoids
This is a blocker for training.

**Comment by sethvargo** [comment]
Potentially relayed to #13993, #13555, or #9080

**Comment by josephholsten** [comment]
@sethvargo is there a version that worked correctly?


Is the correct behavior: "Previous versions of Terraform returned no outputs in this scenario null_resource.example.id should not be resolvable, since we now have a list of null_resource.example" and to always show the error?

**Comment by jbardin** [comment]
I think we can close this as resolved. Since interpolation errors in outputs are now fatal, there's no way to have a successful apply with the incorrect output value written to the state.
