### ISSUE TITLE
volume tags with aws_launch_configuration

### ISSUE THREAD

**Issue by sidhurana** [hashicorp/terraform#14558]
Hi.

Terraform version : v0.9.2

Would like to know how can i add tags to ebs volumes created by aws launch configurations resource ?

Regards,
Sudhir

**Comment by stack72** [comment]
Hi @sidhurana 

Thanks for raising the question here - unfortunately, the API call that Terraform uses to do this is not available yet for launch configuration. Therefore, you would need to raise a feature request with AWS for this 

Thanks

Paul

**Comment by sidhurana** [comment]
Thanks Paul.
