### ISSUE TITLE
Circonus Rule Sets in .tfstate (whitespaces are not url-encoded)

### ISSUE THREAD

**Issue by zaharcan** [hashicorp/terraform#14552]
Hi there,

There is a problem with **circonus_rule_set** import mechanism (whitespaces handling).
Once you import any Circonus Rule Set that has whitespaces in Check Name or Metric Name you will not be able to successfully perform ```terraform plan```. You'll get **"Invalid rule set CID"**.

My workaround was to manually edit **.tfstate** files and replace whitespaces with ```%20``` under following paths:
- modules:resources:circonus_rule_set.XXX:primary:id
- modules:resources:circonus_rule_set.XXX:primary:attributes:id

### Terraform Version
0.9.5

### Affected Resource(s)
- circonus_rule_set

### Terraform import command
```hcl
terraform import circonus_rule_set.123456_My_Metric_Name "/rule_set/123456_My%20Metric%20Name"
terraform plan
```

**Comment by sean-** [comment]
@zaharcan can you see if the attached PR works for your use case?

**Comment by sean-** [comment]
This has been fixed in terraform-providers/terraform-provider-circonus#1 and this issue can be closed.
