### ISSUE TITLE
aws_alb_listener_rule doesn't import listener arn

### ISSUE THREAD

**Issue by dannyhw** [hashicorp/terraform#14568]
After successfully importing a listener rule I check the state and there is no listener arn even though this is required in the listener_rule config.

```
$ terraform state show aws_alb_listener_rule.CH-EU-PROD-MEDIAPOOL-LB-443-1
id                        = arn:aws:elasticloadbalancing:eu-central-...
action.#                  = 1
action.0.target_group_arn = arn:aws:elasticloadbalancing:eu-central-...
action.0.type             = forward
arn                       = arn:aws:elasticloadbalancing:eu-central-...
condition.#               = 1
condition.0.field         = path-pattern
condition.0.values.#      = 1
condition.0.values.0      = /mediapool/*
priority                  = 1
```
_I removed some of the information from the output however I kept all the fields that were returned._

I'm running Terraform v0.9.5 on ubuntu 14.04.

To reproduce just import an existing listener rule using 

` terraform import aws_alb_listener_rule.some_name some_arn`

**Comment by isurfbecause** [comment]
Same with `Terraform v0.9.6` on mac osx

**Comment by grubernaut** [comment]
After looking into this, this is currently not possible with Terraform without some changes to the upstream SDK. The `DescribeRules` API request only returns the current rule's arn, and not the `listener_arn` associated with the rule.
