### ISSUE TITLE
S3 Remote backend uses cli profile setting and not aws provider

### ISSUE THREAD

**Issue by aleybovich** [hashicorp/terraform#14566]
I am running terraform v 0.9.4. Looks like remote backend is using cli profile credentials (defined in ~/.aws/credentials with AWS_PROFILE set) for accessing S3 and DynamoDB instead of aws provider (like all other terraform constructs do). I consider it a bug as this behavior is different from how all other elements of terraform work (they all use aws provider). It's quite an inconvenient dependency as my cli is configured for a different aws account from the one terraform runs on and I would love to avoid having to switch AWS_PROFILE when running terraform. Are there plans to put the backend auth behavior in line with all other elements? 

Thank you

**Comment by jbardin** [comment]
Hi @aleybovich,

While the backend doesn't (and can't for various reasons) use the separate provider block from the config, the backend clients use the same code from the provider to authenticate and access aws resources. 

Can you share an example of your configuration that's not working as intended?

**Comment by aleybovich** [comment]
My ~/.aws/credentials file has two profiles defined:
```[profile1]
access_key=profile1_access_key
secret_key=profile1_secret_key
[profile2]
access_key=profile2_access_key
secret_key=profile2_secret_key```

In environment the variable defined as:
`AWS_PROFILE = profile1 `

So any CLI command will use `profile1` credentials and corresponding profile1 account.

In terraforms.tf I create aws provider using profile2 credentials:
```
provider "aws" {
    access_key = "profile2_access_key"
    secret_key = "profile2_secret_key"
}
```
So terraforms will create resources in account associated with profile2.

But, when I add the backend state resource:
```
terraform {
    backend "s3" {
        bucket 		= "state-bucket"
        key 		        = "terraform.tfstate"
        region 		= "us-east-1"
        encrypt		= "true"
        lock_table 	= "terraform-statelock"
    }
}
```
It tries to access `state-bucket` S3 bucket using `profile1` credentials, which obviously fails, as the bucket is created in the account associated with profile2. After I change `AWS_PROFILE` environment variable to 'profile2' it starts working. That alone tells me that the backend is using the credentials defined in the shell environment, not the aws provider that all other TF resources use.

**Comment by jbardin** [comment]
@aleybovich, the backend does not use the provider configuration. Have you tried setting the `profile`, or `access_key` and `secret_key` for the backend?

**Comment by allandrick** [comment]
@aleybovich you can and should probably always be explicitly specifying the profile, access_key and secret_key for the backend (or use shared_credentials_file and profile and role_arn if required) so that there is never any doubt.

**Comment by aleybovich** [comment]
@allandrick - specifying profile=search in the backend definition doesn't do anything. I still have to explicitly set AWS_PROFILE=search for the backend to work. Any ideas why?

**Comment by aleybovich** [comment]
Ok, I tried again and it works when I just specify `profile=search` in backend->S3 settings. Thank you all for your help!
