### ISSUE TITLE
unable to display the datasource after "terraform plan"

### ISSUE THREAD

**Issue by zhaojie-xu** [hashicorp/terraform#14569]
I'm using Terraform 0.9.4. I encounter the problem as below.
When I'm providing the datasource for terraform,I want to display the query result of datasource  by command "terraform plan" ,but there is no display after this command.Could you tell me some methods or configurations so that the query result of datasource can be displayed after the "terraform plan"?

**Comment by pkolyvas** [comment]
I believe that the work released in 0.13 and further expanded upon in 0.14 might get your what you want/need. 

Additionally, due to the age of this ticket, I'm going to close this enhancement issue out.
