### ISSUE TITLE
Problem with Launch Configuration name as ASG Tag value?

### ISSUE THREAD

**Issue by dayer4b** [hashicorp/terraform#14583]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
`v0.9.4`

### Affected Resource(s)
* aws_autoscaling_group
* aws_launch_configuration

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_group" "asg" {
  availability_zones = ["${aws_subnet.main.*.availability_zone}"]

  vpc_zone_identifier = ["${aws_subnet.main.*.id}"]

  name                      = "${var.app_name}-${var.app_env}"
  max_size                  = "${var.asg_max_size}"
  min_size                  = "${var.asg_min_size}"
  desired_capacity          = "${var.asg_desired_capacity}"

  load_balancers            = ["${aws_elb.elb.name}"]

  launch_configuration      = "${aws_launch_configuration.lc.name}"

  tag {
    key                 = "LaunchConfiguration"
    value               = "${aws_launch_configuration.lc.name}"
    propagate_at_launch = true
  }

  tag {
    key                 = "Name"
    value               = "${var.app_name}-${var.app_env}"
    propagate_at_launch = true
  }

  tag {
    key                 = "Application"
    value               = "${var.app_name}"
    propagate_at_launch = true
  }

  tag {
    key                 = "Environment"
    value               = "${var.app_env}"
    propagate_at_launch = true
  }

  tag {
    key                 = "Generator"
    value               = "Terraform"
    propagate_at_launch = true
  }

}

resource "aws_launch_configuration" "lc" {
  name          = "${var.app_name}-${var.app_env}-${data.aws_ami.ami.id}-${uuid()}"
  image_id      = "${data.aws_ami.ami.id}"
  instance_type = "t2.micro"

  root_block_device = {
    delete_on_termination = true
  }


  lifecycle = {
    create_before_destroy = true
  }

  iam_instance_profile = "${aws_iam_instance_profile.app_profile.name}"

}


resource "aws_iam_instance_profile" "app_profile" {
  name  = "${var.app_name}-${var.app_env}-profile"
  role  = "${aws_iam_role.app_role.name}"
}

resource "aws_iam_role" "app_role" {
  name = "${var.app_name}-${var.app_env}-role"
  path = "/"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Principal": {
               "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow",
            "Sid": ""
        }
    ]
}
EOF
}


resource "aws_iam_role_policy" "app_policy" {
  name = "${var.app_name}-${var.app_env}-policy"
  role = "${aws_iam_role.app_role.id}"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}









data "aws_ami" "ami" {
  most_recent = true
  owners = ["self"]

}

output "ami_name" {
  value = "${data.aws_ami.ami.name}"
}
```

### Debug Output
https://gist.github.com/dayer4b/39332a82b2f9fad926e84c83d6753a0f

### Expected Behavior
A new Launch Configuration should have been created and the Autoscaling Group should have been updated to 1) use the new LC and 2) add the new LaunchConfiguration tag

### Actual Behavior
Terraform seemed to create a new Launch Configuration but errored out shortly after with the attached debug message.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
The Launch Configuration name uses a generated UUID and that name is added to a Tag in the autoscaling group.  I suspect this is the cause of the problem.  When I removed the Tag, things worked fine.

**Comment by jbardin** [comment]
Hi @dayer4b,

The issue here is that you're using the `uuid()` interpolation function in the name of the `aws_launch_configuration`, so the name will change on every invocation of the function.

This normally would show up as a diff on ever terraform invocation, but since you're referencing the name in the tag value, it shows up as the value changing between the plan and apply phases. 

If you really want to use `uuid()` in the name, you must add `name` to the resource's `ignore_changes`. You should also then reference the LC by the `id` attribute in the tag value, rather than the `name`, to prevent  it from being recalculated.
