### ISSUE TITLE
Authenticating with AWS using shared_credentials_file

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#14581]
What is the correct syntax for authenticating with AWS using a custom `.ini` credential file? Up until this point I've been using the Google provider which uses `${file()}`, however the Terraform documentation for AWS looks to accept a string path for `shared_credentials_file`. Is that correct?

Here is what I am currently trying:

````
provider "aws" {
    region = "us-west-2"
    shared_credentials_file = "./aws-dev-auth.ini"
    profile = "default"
}
````

The file `aws-dev-auth.ini` sits in the base directory along with all Terraform configs.

**Comment by nodesocket** [comment]
Further digging, the problem seems to be related to using the `s3` backend. In order for it to work, I have to manually add `access_key` and `secret_key` to the `backend` block. Terraform does not seem to be inheriting credentials from the `provider` block.

```
terraform {
    backend "s3" {
        bucket = "dev-terraform-state"
        key = "terraform.tfstate"
        region = "us-west-2"
        access_key = "XXXXXXXXXXXXXX"  // required
        secret_key = "YYYYYYYYYYYYYYYYYYYY" // required
    }
}
```
This obviously is not desired, is there a way to have these credentials for the backend inheritited from the provider?

**Comment by nodesocket** [comment]
👍  would be awesome if `backend.s3` can inherit the following from `provider.aws`:

    region
    shared_credentials_file
    profile

Just curious, can I do the following as a work around?

    shared_credentials_file = "${provider.aws.shared_credentials_file}"
    profile = "${provider.aws.region}"
    region = "${provider.aws.region}"

**Comment by allandrick** [comment]
@nodesocket you can specify the shared_credentials_file, profile and even role_arn (if you're using assume role) in the terraform backend s3 configuration.

Some people don't store their tfstate in the same accounts as they are terraforming on, for example...
