### ISSUE TITLE
Impossible to loop in lambda_function inside aws_s3_bucket_notification

### ISSUE THREAD

**Issue by JulesDT** [hashicorp/terraform#14589]
### Terraform Version
Terraform v0.9.4
### Affected Resource(s)
- aws_s3_bucket_notification

### Terraform Configuration Files
Two different syntax tested (first one valid doing the somehow expected behavior but not the wanted behavior, second one being the one we want that doesn't exist)
1. First Syntax

```hcl
resource "aws_s3_bucket_notification" "bucket-notification-loop" {
  count  = "${length(var.lambdas_list)}"
  bucket = "${data.terraform_remote_state.s3.bucket_id}"

  lambda_function {
    lambda_function_arn = "${element(aws_lambda_function.create-lambdas.*.arn, count.index)}"
    events              = ["s3:ObjectCreated:*"]
    filter_prefix       = "${var.lambdas_prefix_list[element(aws_lambda_function.create-lambdas.*.id, count.index)]}"
  }
}
```

2. Second Syntax
```hcl
resource "aws_s3_bucket_notification" "bucket-notification-loop" {
  bucket = "${data.terraform_remote_state.s3.bucket_id}"

  lambda_function {
    count  = "${length(var.lambdas_list)}"
    lambda_function_arn = "${element(aws_lambda_function.create-lambdas.*.arn, count.index)}"
    events              = ["s3:ObjectCreated:*"]
    filter_prefix       = "${var.lambdas_prefix_list[element(aws_lambda_function.create-lambdas.*.id, count.index)]}"
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I would expect each lambda to be added to the bucket notification.

### Actual Behavior
Actually, because `aws_s3_bucket_notification` is unique for each bucket, each loop iteration rewrites the iteration before.
The second syntax just says that `count` is an unknown parameter for `lambda_function`.

### Steps to Reproduce
1. `terraform apply --parallelism=1`

### Important Factoids
`account-admin` role is used so everything should be fine

### References
- Issue https://github.com/hashicorp/terraform/issues/11536 is talking about something similar but yet different

Thanks for the help, I am still available for precisions if necessary

**Comment by jonaf** [comment]
I have exactly this use-case but for a separate purpose: I have a Cloudfront distribution, in which I need about 30 different path patterns with identical caching behavior. I would like to be able to simply say `count = 30` and iterate over a `var` that is a list of my path patterns. Instead, it looks like I'm going to have to handroll all of these, resulting in an extremely long and confusing Terraform configuration.

Are there any possible workarounds at this time?

**Comment by apparentlymart** [comment]
Hi @JulesDT! Sorry for the long silence here.

This issue is covering the same use-case as #7034, which we've now resolved due to a new feature in master ready for the forthcoming v0.12.0 release. I left a comment over there showing how the new feature can be used.

Thanks for reporting this, and sorry again for the delay in responding.
