### ISSUE TITLE
azurerm_network_interface doesn't support import

### ISSUE THREAD

**Issue by HighwayofLife** [hashicorp/terraform#14591]
azurerm_network_interface doesn't support import, despite [documentation](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html#import) stating otherwise.

### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
- azurerm_network_interface

### Debug Output
https://gist.github.com/HighwayofLife/a145ce404723b23f4083336c5c8ff139

### Expected Behavior
Azure network interface resource should be imported.

### Actual Behavior
```terraform import azurerm_network_interface.test /subscriptions/<redacted>/resourceGroups/<redacted>/providers/microsoft.network/networkInterfaces/jenkinsmaster314
azurerm_network_interface.test: Importing from ID "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/microsoft.network/networkInterfaces/jenkinsmaster314"...
Error importing: 1 error(s) occurred:

* azurerm_network_interface.test (import id: /subscriptions/<redacted>/resourceGroups/<redacted>/providers/microsoft.network/networkInterfaces/jenkinsmaster314): import azurerm_network_interface.test (id: /subscriptions/<redacted>/resourceGroups/<redacted>/providers/microsoft.network/networkInterfaces/jenkinsmaster314): resource azurerm_network_interface doesn't support import
```

### Steps to Reproduce
1. `terraform import azurerm_network_interface.test /subscriptions/xxxxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MyResourceGroup/providers/microsoft.network/networkInterfaces/mynetworkinterface`

**Comment by nbering** [comment]
Still an issue in v0.9.6. Something happened and I lost resources from my terraform state, trying to figure out how to reconstruct a network interface. Recreating is not an option.
