### ISSUE TITLE
fastly dictionary support

### ISSUE THREAD

**Issue by jasonkuhrt** [hashicorp/terraform#14592]
As far as I can tell [terraform fastly plugin](https://www.terraform.io/docs/providers/fastly/r/service_v1.html) does not currently support [fastly dictionaries](https://docs.fastly.com/api/config#dictionary). This is a particularly important feature because if you create fastly dictionaries in VCL directly you lose [the ability to modify their values with the api](https://docs.fastly.com/guides/edge-dictionaries/about-edge-dictionaries#limitations-and-considerations).

**Comment by nicolasbelanger** [comment]
+1

**Comment by rlunardelli** [comment]
+1
