### ISSUE TITLE
Reproducible crash in 0.4.1 when refreshing tfstate for a single RDS instance

### ISSUE THREAD

**Issue by DanielRussell** [hashicorp/terraform#1460]
[gist of full crash log](https://gist.github.com/DanielRussell/e6d37ce2aaed35a7a025)

Command line:

```
terraform plan \
  -var='top_dir=/Users/dpr/project/tedconf/infrastructure' \
  -out=/Users/dpr/project/tedconf/infrastructure/data/terraform/rds/wordpress/terraform.tfplan \
  -var-file=/Users/dpr/project/tedconf/infrastructure/data/terraform/terraform.tfvars
```

The above command line worked with 0.3.6 and 0.3.7; I skipped 0.4.0.

FWIW, I initially created this RDS instance in the AWS Console, and then "backported" it into terraform by hand. I created the first `terraform.tfstate` file by examining a `terraform.tfstate` for an RDS instance that had been created by terraform, changing a few items (ID, etc), then letting terraform fill in the rest.  I believe I originally created the `terraform.tfstate` file with 0.3.6.

**Comment by mitchellh** [comment]
Fixed. Thanks! Yeah, this should be able to be worked around. Sorry about that.

**Comment by DanielRussell** [comment]
TYVM!
