### ISSUE TITLE
aws_launch_configuration module does not seem to have a metadata attribute to specify CloudFormation::init capability to install software on an instance. 

### ISSUE THREAD

**Issue by vinayvenkat** [hashicorp/terraform#14607]
Hi there,

### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
aws_launch_configuration 

### Debug Output

N/A

### Panic Output
N/A

### Expected Behavior

The AWS CloudFormation Template framework has a provision as show below:

```
"Type" : "AWS::AutoScaling::LaunchConfiguration",
      "DependsOn" : [ "VPC", "InternetGateway" ],
      "Metadata" : {
        "Comment" : "Install a simple application",
        "AWS::CloudFormation::Init" : {
          "config" : {
            "packages" : {
              "yum" : {
                "httpd" : []
              }
            },

            "files" : {
              "/var/www/html/index.html" : {
```

What should have happened?

I was expecting a similar capability to express the installation of various software on instances using terraform. However, I do not see this field or capability. Can someone please help / assist? 

I see the userdata field but that is used for a whole different purpose. 
Thanks.
- Vinay

**Comment by vinayvenkat** [comment]
Not sure why this was closed. I still don't think this is supported.

**Comment by so0k** [comment]
it was migrated... see the referenced issue
