### ISSUE TITLE
Ability to specify storage class for s3 backend

### ISSUE THREAD

**Issue by martinssipenko** [hashicorp/terraform#14615]
Hi,

Would you think it would make sense to implement the ability to specify the storage class for objects for s3 backend?

I propose adding an optional `storage_class` variable to already existing configuration variables. The default value would be `STANDARD`. Possible values would be `STANDARD` and `STANDARD_IA`.

If you think this would be appropriate, I'm happy to send a Pull Request.

**Comment by danieladams456** [comment]
This is probably just as easily done with a lifecycle policy on your state bucket.  Move all previous versions to Standard-IA.  Also given the size of the state files, it probably amounts to a few cents a year.
