### ISSUE TITLE
[Bug report] - Panic after terraform refresh

### ISSUE THREAD

**Issue by gappaa** [hashicorp/terraform#14617]
### Terraform Version
Terraform v0.9.6-dev (dd2bc1edbd6050de717ae11dfd7dbb5d2264d84c+CHANGES)

### Affected Resource(s)
- openstack

### Terraform Configuration Files
```
# openstack_compute_instance_v2.tf
provider openstack credentials # can't show this
```
```
# openstack_networking_network_v2.tf
data "openstack_networking_network_v2" "networking_elements" {
        provider = "openstack.basic"
        region = "XXXX"
}

output "networking_elements_ouput" {
        value = <<EOF
"${data.openstack_networking_network_v2.networking_elements.id}"
EOF
}
```
```
# openstack_images_image_v2.tf (end of the file with cat -e)
data "openstack_images_image_v2" "openstack_image_disk_format" {$
  provider = "openstack.basic"$
  region = "XXXX"$
  name = "Archlinux"$
  sort_key = "disk_format"$
  visibility = "private"  $
}$
$
output "openstack_image_disk_format" {$
  value = "${data.openstack_images_image_v2.openstack_image_disk_format.id}"$
}$
```

### Debug Output
[Stack trace](https://gist.github.com/gappaa/8d0ed0107e8bafcfe066bc16448289d7)

### Panic Output
I can't pass the crash.log for the moment. There are some confidential informations.

### Expected Behavior
Print an error (the region is not the right region to use)

### Actual Behavior
Segfault

### Steps to Reproduce
1. `OS_DEBUG=1 TF_LOG=DEBUG terraform apply`
2. `OS_DEBUG=1 TF_LOG=DEBUG terraform refresh`

### Important Factoids
Running on classic OpenStack.

**Comment by jtopjian** [comment]
@gappaa Thanks for reporting this. 

In the debug output, you should see a GET request to the image service. Can you run the following and report the output?

```shell
$ token=$(openstack token issue -c id -f value)
$ curl -s -H "X-Auth-Token:$token" http://YOUR_HOST:9292/v2/images?name=Archlinux&sort_dir=asc&sort_key=disk_format&status=active&visibility=private | python -mjson.tool

**Comment by gappaa** [comment]
I have recreate the image because it was deleted and the `curl` give this :
```
{
    "images": [
        {
            "status": "active",
            "name": "Archlinux",
            "tags": [],
            "container_format": "bare",
            "created_at": "2017-05-18T16:02:28Z",
            "size": 504365056,
            "disk_format": "iso",
            "updated_at": "2017-05-18T16:03:10Z",
            "visibility": "private",
            "locations": [
                {
                    "url": "rbd://df692315-22a3-4921-83f5-2cdea694b594/images/bd9e7bd3-3ea6-477a-89b6-bef0a129c465/snap",
                    "metadata": {}
                }
            ],
            "self": "/v2/images/bd9e7bd3-3ea6-477a-89b6-bef0a129c465",
            "min_disk": 0,
            "protected": false,
            "id": "bd9e7bd3-3ea6-477a-89b6-bef0a129c465",
            "file": "/v2/images/bd9e7bd3-3ea6-477a-89b6-bef0a129c465/file",
            "checksum": "6492568efbd7f5c876eeb3a3133bb819",
            "owner": "3ca82ba8531844098e8bfdeacc7a312d",
            "direct_url": "rbd://df692315-22a3-4921-83f5-2cdea694b594/images/bd9e7bd3-3ea6-477a-89b6-bef0a129c465/snap",
            "min_ram": 0,
            "schema": "/v2/schemas/image"
        }
    ],
    "schema": "/v2/schemas/images",
    "first": "/v2/images?sort_dir=asc&sort_key=disk_format&status=active&name=Archlinux&visibility=private"
}
```

**Comment by jtopjian** [comment]
Thanks!

Just to confirm: you're able to curl the same URL that is crashing in Terraform?

**Comment by gappaa** [comment]
Terraform make these GET before the crash : 
*`URL/images?name=Archlinux&owner=3ca82ba8531844098e8bfdeacc7a312d&sort_dir=asc&sort_key=name&status=active&visibility=private`
*`URL/v2/images?name=Archlinux&sort_dir=asc&sort_key=disk_format&status=active&visibility=private` 

I try these GET with `curl` and it's give the right result.

**Comment by jtopjian** [comment]
Thanks! This will be a fun one to try to resolve 😄 I'll look into this and see what I can do.

**Comment by gappaa** [comment]
Good luck and have fun :stuck_out_tongue_winking_eye:

Do not hesitate if you want more informations :wink:

**Comment by jtopjian** [comment]
@gappaa Quick question: I notice you're specifying a region. The exact same type of crash was reported a few days ago (https://github.com/hashicorp/terraform/issues/14538) and it was due to specifying a wrong region. Can you double-check if the region you're using is correct?

**Comment by gappaa** [comment]
@jtopjian I check my region and indeed it's incorrect

**Comment by jtopjian** [comment]
@gappaa So is everything working now?

**Comment by gappaa** [comment]
Yes. Thanks you for your patience.

**Comment by jtopjian** [comment]
No problem at all! Let me know if you run into any more issues :)
