### ISSUE TITLE
Data sources are always destroyed

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#14625]
### Terraform Version
0.9.5

### Affected Resource(s)
- core

### Terraform Configuration Files
```hcl
data "aws_availability_zones" "available" {}
```

### Expected Behavior
`terraform destroy` should report no resources destroyed.

### Actual Behavior
`terraform destroy` always "destroys" the data source

### Steps to Reproduce
1. `terraform destroy`
1. `terraform destroy` again

**Comment by matschaffer** [comment]
Same as https://github.com/hashicorp/terraform/issues/14605 - probably worth closing one or the other.

**Comment by grubernaut** [comment]
Closing, dupe of #14605. Thanks Seth.

**Comment by sethvargo** [comment]
@grubernaut I edited your comment to link to the end of the chain to reduce future clicks 😄
