### ISSUE TITLE
aws - Re-use resources created with modules across different environments

### ISSUE THREAD

**Issue by nsushain** [hashicorp/terraform#14638]
Hello,

I have four different environments with set variables which rely on modules to create resources end-end infrastructure from VPC, subnets, security groups, instances and ELB. The problem Im facing is how can I re-use for example VPC created on QA environment into subnets created in DEV environment without any changes to modules. Is there a way I could run the module but not create the VPC and use the existing VPC, that will need to have a ignore_resource like option when running from different env? Also I am aware of the `terraform_remote_state` feature which can pull resources from state files from different env, but I assume that would render my modules useless (have to maintain two sets of modules). I've followed the best-practices structure in the terraform docs for multi-env. 

Any suggestions or help regarding this is greatly appreciated.

**Comment by Puneeth-n** [comment]
@nsushain I think you are looking for something like [this](https://github.com/antonbabenko/terraform-aws-devops/tree/master/projects)
