### ISSUE TITLE
Feature request: allow specification of health checker regions in aws_route53_health_check

### ISSUE THREAD

**Issue by danieladams456** [hashicorp/terraform#14637]
I checked the current git code and issues list and am not seeing anything for limiting the regions where health checkers are located.

This is needed for when we have geo-location restrictions.  Health checks seem to work as is due to the fact [that failures have to be consecutive](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-determining-health-of-endpoints.html), but having half of the checkers reporting down all the time seems to lead to a higher risk of having unnecessary failovers.

http://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHealthCheck.html

**Comment by stack72** [comment]
This requires the version of the go-sdk to be upgraded first

I am just working on that part now

**Comment by igoratencompass** [comment]
Also needed to prevent being unnecessary bombarded by health checks from high number of regions by default: 

```
If you don't specify any regions, Amazon Route 53 health checkers automatically performs checks from all of the regions that are listed under Valid Values.

Valid Values: us-east-1 | us-west-1 | us-west-2 | eu-west-1 | ap-southeast-1 | ap-southeast-2 | ap-northeast-1 | sa-east-1 
```

**Comment by CpuID** [comment]
+1, would be advantageous to have this :) had to apply it manually to some health checks today outside of TF
