### ISSUE TITLE
aws_autoscaling_group and aws_autoscaling_notification separation causes no notifications on the initial instance launch.

### ISSUE THREAD

**Issue by wv-cfromm** [hashicorp/terraform#14641]
Seems to be a flaw in AWS API more than terraform, but it would be great if there was a solution.  aws_autoscaling_group and aws_autoscaling_notification as separate functions causes no notifications on the initial instance launch.

In my particular use case, I have a lambda function that needs to act on the servers that have spun up from ASG.  The notification is never sent for the initially launched instances.  Any way to fix?

**Comment by stack72** [comment]
Hi @wv-cfromm 

Please can you post your configuration for this? I have managed to get launch notifications for new ASG instances

Thanks

Paul

**Comment by wv-cfromm** [comment]
I was able to determine that notifications will work on the initial launch, if wait_for_capacity_timeout ="0".  This seems to be a requirement.  I was not able to get initial launch notifications until I set wait_for_capacity_timeout ="0".  This is fine for my needs.  I'd recommend adding this to the aws_autoscaling_notifications documentation.

**Comment by rumenvasilev** [comment]
We're seeing the same bug. Observed in 0.9.6 and 0.9.8. Didn't have this problem with 0.9.5.

**Comment by mrcrch** [comment]
The only available workaround is that posted by @cfromm1911 ?
