### ISSUE TITLE
format interpolation is not functioning correctly with count.index in template_file

### ISSUE THREAD

**Issue by DantheHalMan** [hashicorp/terraform#14645]
### Terraform Version
Terraform v0.9.1

### Affected Resource(s)
- data "template_file"

### Terraform Configuration Files
```hcl
data "template_file" "user_data_windows" {
    count = "2"
    template = "${file("scripts/windows/system_config.ps1")}"
	vars {
		secret_password = "${var.secret_password}"
                hostname = "${format("windows-%01d", count.index + 1)}"
	}
}
```

### Expected Behavior
Based on the count, each aws_instance resource will execute a unique powershell command to rename the hostname in the user_data.

Below is the powershell command:

```hcl
Rename-Computer -NewName ${hostname} -force
```
With the count of two, the expected user_data should look like this:

resource aws_instance 1:
```hcl
Rename-Computer -NewName windows-01 -force
```
resource aws_instance 2:
```hcl
Rename-Computer -NewName windows-02 -force
```

### Actual Behavior
The format interpolation does not function all, resulting all of the resource aws_instance to run the same user_data

```hcl
Rename-Computer -NewName windows-01 -force
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Format interpolation with count.index function as expected in other parameters (IE Name tagging)

**Comment by mildwonkey** [comment]
This is fixed in terraform 0.12!

```hcl
data "template_file" "user_data_windows" {
  count    = "2"
  template = "${file("system_config.ps1")}"
  vars = {
    secret_password = "sekret"
    hostname        = "${format("windows-%01d", count.index + 1)}"
  }
}

output "templates" {
  value = data.template_file.user_data_windows.*.rendered
}
```

```
Outputs:

templates = [
  "Rename-Computer -NewName windows-1 -force\n",
  "Rename-Computer -NewName windows-2 -force\n",
]
```

There is also a new built-in function, [`templatefile`](https://www.terraform.io/docs/configuration/functions/templatefile.html), which can be used in place of the `template` provider to render a template file.
