### ISSUE TITLE
Chef Provisioner never starts/waiting for OpenStack Provider? 

### ISSUE THREAD

**Issue by joemillerr** [hashicorp/terraform#14640]
### Terraform Version
v0.9.5

### Affected Resource(s)
- openstack_compute_instance_v2
- provisioner chef

### Terraform Configuration Files
```hcl
provider "openstack" {
  user_name   = "user"
  tenant_name = "development"
  password    = "password"
  auth_url    = "https://openstackurl:5000/v2.0"
}
resource "openstack_compute_instance_v2" "test" {
  name            = "test"
  image_name      = "Ubuntu"
  flavor_name     = "medium"
  security_groups = ["default"]
  network {
    name = "network1"
  }
  provisioner "chef" {
    connection {
      type     = "ssh"
      user     = "admin"
      password = "password"
    }
    environment     = "test"
    run_list        = ["cookbook::recipe"]
    node_name       = "test"
    server_url      = "https://api.chef.io/organizations/test"
    recreate_client = true
    user_name       = "user"
    user_key        = "${file("/Users/user/.chef/user.pem")}"
    version         = "12.14.89"
    log_to_file     = true
  }
}
```

### Debug Output
Terraform doesn't ever error out.  I killed the process manually after a few cycles. Debug log below anonymized:
https://gist.github.com/joemillerr/11e48a13667e435cb2aa125e39778140

### Expected Behavior
Chef should run.

### Actual Behavior
1 . Machine was built in OpenStack successfully
2.  ssh connection seems to have worked
3.  stuck on what looks to be the very beginning of chef provision. 

 Potentially hung waiting for sudo? logs don't really help me all that much.  Not getting any Chef logs

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I'm running OpenStack 9.1

**Comment by joemillerr** [comment]
@svanharmelen

**Comment by svanharmelen** [comment]
@joemillerr see this line in your debug log:

```
2017/05/18 09:56:19 [DEBUG] plugin: terraform: chef-provisioner (internal) 2017/05/18 09:56:19 starting remote command: sudo curl -LO https://www.chef.io/chef/install.sh
openstack_compute_instance_v2.chef-test (chef): [sudo] password for admin:
```

So the provisioner is trying to make a `sudo` call, but the user you are connecting with, is requires to enter his/her password to use `sudo`. So it now sits there waiting until you enter the password, which will of course never happen.

So you should either make sure the `sudoers` file is configured in such a way that the user you are using does not have to enter his/her password (`:NOPASSWD ALL`) or you should prevent the use of `sudo` by setting `prevent_sudo = true` in the provisioner config.

Of course in the latter case the user you are connecting with should have enough rights to do everything without `sudo`.

**Comment by joemillerr** [comment]
Thanks @svanharmelen .  I should have caught that.  Is there a way to pass a sudo password through? My SSH connection is with an account that has sudo access just not passwordless sudo. I would prefer to not give it passwordless if I don't have to since it will be baked into the image.  Thanks again

**Comment by svanharmelen** [comment]
@joemillerr no, unfortunately there is now way to pass through a password somehow...

**Comment by joemillerr** [comment]
@svanharmelen Ok no worries, I'll get my image updated and give this a shot.  I really appreciate the help.

**Comment by svanharmelen** [comment]
No problem @joemillerr! I'll close this issue for now, feel free to reopen it if needed...
