### ISSUE TITLE
can't set different hostname with vsphere provider

### ISSUE THREAD

**Issue by jeroenjacobs1205** [hashicorp/terraform#14659]
### Terraform Version
0.9.3

### Affected Resource(s)
Please list the resources as a list, for example:
- vsphere_virtual_machine

I have particular use-case where the hostname needs to be configured differently from the vm name. I thought this was possible with customizations, seems not...

Snippet:

```
resource "vsphere_virtual_machine" "dns_instance" {

  count = "${var.count}"
  name = "${var.environment}-${var.name}-${format("%03d", count.index+1)}"
  domain = "${var.dns_domain}"
	dns_servers = "${split(",", var.dns_servers)}"
	dns_suffixes = "${split(",", var.dns_suffixes)}"

  vcpu   = "${var.vcpu}"
  memory = "${var.memory}"

  network_interface {
    label = "${var.vm_network}"
    ipv4_address = "${element(split(",", var.ips),count.index)}"
    ipv4_gateway = "${var.gateway}"
    ipv4_prefix_length = "${element(split("/",var.cidr),1)}"
  }

  disk {
    template = "${var.vm_template}"
    datastore = "${var.vm_datastore}"
    type = "thin"
  }

  custom_configuration_parameters = {
    role = "${var.role}"
    hostname = "${var.name}-${format("%03d", count.index+1)}"
  }

}
```

As you can see, the vm name in vsphere contains the environment in it's name. However, this should not be present in /etc/hostname.

I was hoping I could override this with the custom_configuration_parameters section, but "hostname" gets ignored.

I can barely find information which variables are valid within custom_configuration_parameters. I assume "hostname" is the correct one, but I'm not sure. 

PS: Maybe the TF documentation should contain some info about the most trivial variables that are valid custom configuration parameters. It's just plain guesswork at the moment...

**Comment by ewypych** [comment]
Hello!

In the VM struct there is only one name variable, and as you can see in this section fo the code:
```
identity_options = &types.CustomizationLinuxPrep{
				HostName: &types.CustomizationFixedName{
					Name: strings.Split(vm.name, ".")[0],
				},
				Domain:     vm.domain,
				TimeZone:   vm.timeZone,
				HwClockUTC: types.NewBool(true),
```
hostname in this case has the same value as vm.name. Of course govmomi client allows to set another value and use another variable:

```
type CustomizationLinuxPrep struct {
	CustomizationIdentitySettings

	HostName   BaseCustomizationName `xml:"hostName,typeattr"`
	Domain     string                `xml:"domain"`
	TimeZone   string                `xml:"timeZone,omitempty"`
	HwClockUTC *bool                 `xml:"hwClockUTC"`
}
```

It is just needed to implement that. I will try to do it as soon as possible, 'cause I assume it will be very useful for many people. :) But if anyone could do it earlier it would be great.
