### ISSUE TITLE
Not all Lightsail regions are currently supported  

### ISSUE THREAD

**Issue by gsaslis** [hashicorp/terraform#14668]
Hi there,

It seems `terraform` has some explicit checks about the regions lightsail supports? I cannot currently create an instance in `eu-west-1`, etc. 
Rather I get an error message that only `us-east-1*` AZs are supported.

### Terraform Version
0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lightsail_instance

### Terraform Configuration Files
```hcl
resource "aws_lightsail_instance" "promo_site" {
  name              = "promosite"
  availability_zone = "eu-west-1a"
  blueprint_id      = "joomla_3_6_5"
  bundle_id         = "nano_1_0"
  key_pair_name     = "some_key"
}
```

### Expected Behavior
Lightsail instance should have been created

### Actual Behavior
`The given Availability Zone is invalid. It must be one of us-east-1a,us-east-1b,us-east-1c,us-east-1d,us-east-1e`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Just run `terraform apply` on the above resource.

### Important Factoids
Amazon just announced support for other availability zones a couple of days ago: https://aws.amazon.com/about-aws/whats-new/2017/05/amazon-lightsail-now-available-in-5-additional-europe-us-aws-regions/
(I was hoping no changes would be necessary to terraform to support the extra regions)

### References
Turns out #14621 was: 
a. incomplete (i should also have updated all the other `lightsail_*` resources that seem to have the same warning
b. probably premature, since terraform doesn't seem to support the new regions / AZs, even though AWS does

**Comment by grubernaut** [comment]
Hey @gsaslis, thanks for the issue!

Unfortunately though, this looks like it's actually an AWS issue, and not a Terraform issue. We support the `eu-west-1` region, and availability zones. However, the AWS API is what is returning the `Availability Zone is invalid` error. 

HTTP Response from the AWS API
```
2017/05/19 11:22:52 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/19 11:22:52 [DEBUG] [aws-sdk-go] DEBUG: Response lightsail/CreateInstances Details:
2017/05/19 11:22:52 [DEBUG] plugin: terraform: ---[ RESPONSE ]--------------------------------------
2017/05/19 11:22:52 [DEBUG] plugin: terraform: HTTP/1.1 400 Bad Request
2017/05/19 11:22:52 [DEBUG] plugin: terraform: Connection: close
2017/05/19 11:22:52 [DEBUG] plugin: terraform: Content-Length: 172
2017/05/19 11:22:52 [DEBUG] plugin: terraform: Content-Type: application/x-amz-json-1.1
2017/05/19 11:22:52 [DEBUG] plugin: terraform: Date: Fri, 19 May 2017 15:22:32 GMT
2017/05/19 11:22:52 [DEBUG] plugin: terraform: Server: Server
2017/05/19 11:22:52 [DEBUG] plugin: terraform: X-Amzn-Requestid: fa5f80b8-3ca6-11e7-b2fd-4d0a8d484fd6
2017/05/19 11:22:52 [DEBUG] plugin: terraform:
2017/05/19 11:22:52 [DEBUG] plugin: terraform:
2017/05/19 11:22:52 [DEBUG] plugin: terraform: -----------------------------------------------------
2017/05/19 11:22:52 [DEBUG] plugin: terraform: aws-provider (internal) 2017/05/19 11:22:52 [DEBUG] [aws-sdk-go] {"__type":"InvalidInputException","code":"InvalidParams","message":"The given Availability Zone is invalid. It must be one of us-east-1b,us-east-1c,us-east-1d,us-east-1e."}
```

I'll open a support issue with AWS to attempt to resolve this. Thanks!

**Comment by grubernaut** [comment]
Opened: https://github.com/aws/aws-sdk-go/issues/1285, in the SDK for more information. Thanks again!
