### ISSUE TITLE
Terraform restarts node when applying default `resize_disk` value `true`

### ISSUE THREAD

**Issue by nikoren** [hashicorp/terraform#14687]
Hi, I'm trying to upgrade terraform from 0.7 to 0.9.3 , 
Once I switch to new version terraform identifies that there is no `resize_disk` value in my current state:

```
~ digitalocean_droplet.stage-share-xxxx.1
    resize_disk: "" => "true"
```

- according to [documentation (https://www.terraform.io/docs/providers/do/r/droplet.html#resize_disk)  - this setting controls wether to __allow__ or not disk increase, I couldn't see any possible impact by applying this change.

- When I try to apply the change , the node is restarted, and in digital_ocean console I can see the following history:

```
Event	Initiated	Execution	Time
Power On	1 hour ago	6 seconds
Resize	2 hours ago	17 minutes 19 seconds
Power Off	2 hours ago	11 seconds
Create	1 month ago	20 seconds
```

- I think terraform tries to go and resize the disk to same size which involves node restart even though no changes were done in configuration. 

- I believe terraform should not restart node and only update state in scenario when  actual `disk` wasn't changed or maybe documentation should be more clear about the fact that node gets restarted when no changes were made to `disk` configuration.

**Comment by andrewsomething** [comment]
This looks like an unintended consequence of the change introduced in #13007

**Comment by danrabinowitz** [comment]
I submitted a PR to fix this: https://github.com/terraform-providers/terraform-provider-digitalocean/pull/49
