### ISSUE TITLE
Using AWS account id in principal of aws_lambda_permission resource causes recreation during every apply

### ISSUE THREAD

**Issue by delphyne** [hashicorp/terraform#14682]
### Terraform Version
0.8.8

### Affected Resource(s)
- aws_lambda_permission

### Terraform Configuration Files
```hcl
var "aws_account_id" {
    default="1234567890"
}

module "swf-trigger" {
  // nothing interesting in here, just creates a lambda and has outputs for function_name and arn
}

resource "aws_lambda_permission" "invoke_function_privileges" {
  function_name = "${module.swf-trigger.lambda_name}"
  action = "lambda:InvokeFunction"
  principal = "${var.aws_account_id}"
  statement_id = "ABoringSidName"
}
```

### Debug Output
Details of debug log are sensitive.  Let me know if there is a part of it you need that will be helpful.

### Panic Output
No panic.

### Expected Behavior
After initial `terraform apply`, no changes are necessary because the value of `var.aws_account_id` is unchanged.

### Actual Behavior
Every `terraform plan` results in the following output:

```diff
-/+ aws_lambda_permission.invoke_function_privileges
    action:        "lambda:InvokeFunction" => "lambda:InvokeFunction"
    function_name: "start-swf-workflow" => "start-swf-workflow"
    principal:     "" => "1234567890" (forces new resource)
    statement_id:  "ABoringSidName" => "ABoringSidName"
```

Note: it says the principal is changing from the empty string to the account id.

Every `terraform apply` results in the deletion of the statement from the policy and recreation:
```
aws_lambda_permission.invoke_function_privileges: Destroying...
aws_lambda_permission.invoke_function_privileges: Destruction complete
aws_lambda_permission.invoke_function_privileges: Creating...
  action:        "" => "lambda:InvokeFunction"
  function_name: "" => "start-swf-workflow"
  principal:     "" => "1234567890"
  statement_id:  "" => "ABoringSidName"
aws_lambda_permission.invoke_function_privileges: Creation complete
```

### Steps to Reproduce
1. `terraform apply`
1. `terraform plan`

### Important Factoids
The lambda in question has another statement in the policy already.

### References
None.

### Workaround
add a lifecycle block with `ignore_changes=["principal"]`

**Comment by bclodius** [comment]
@delphyne can you try with terraform 0.9.4+?  I contributed a similar fix for remote account IAM roles and that may fix your issue.

**Comment by delphyne** [comment]
We're about to upgrade to 0.9.x, I'll give it a shot when we do and report back.
