### ISSUE TITLE
terraform fmt could have a mode that does stronger canonicalization

### ISSUE THREAD

**Issue by glasser** [hashicorp/terraform#14689]
There are some stylistic choices you can make with HCL that have no semantic effect (to my knowledge).  Some of the more obvious ones to me are whether or not to quote keys, and whether or not to use an `=` for single-key nested blocks:

```
"resource" "foo" "bar" {
  "x" = {
    "y" = "z"
  }
}
```

vs
```
resource foo bar {
  x {
    y = "z"
  }
}
```

While I appreciate that the default `terraform fmt` is mostly about whitespace, it would be nice if there was a stronger form (kinda like `gofmt -s`) that canonicalized choices like this without having to think about them.  (Preferably to the minimalist version.)  Because my project looks tacky with random selections of quoted vs not, but I'd rather not try to enforce a rule on my team that can't be automatically fixed.

This behavior is current as of Terraform 0.9.5.

**Comment by mildwonkey** [comment]
Hello!
I am going to close this issue, as it relates to an older version of both terraform and HCL. Please feel free to open a new issue or feature request if you have a request for Terraform 0.12.X. Thank you!
