### ISSUE TITLE
[scaleway provider] scaleway_volume_attachment does not get destroyed and thus can't migrate from C2S to C2M

### ISSUE THREAD

**Issue by polymeris** [hashicorp/terraform#14686]
### Terraform Version
v0.9.5

### Affected Resource(s)
- scaleway_volume_attachment
- scaleway_server

#### C2S

```json
{
	"provider": {
		"scaleway": {
			"region": "par1"
		}
	},
	"resource": {
		"scaleway_volume": {
			"data": {
				"name": "test-data",
				"size_in_gb": 25,
				"type": "l_ssd"
			}
		},
		"scaleway_volume_attachment": {
			"data": {
				"server": "${scaleway_server.host.id}",
				"volume": "${scaleway_volume.data.id}"
			}
		},
		"scaleway_server": {
			"host": {
				"name": "test",
				"type": "C2S",
				"image": "d0c50b37-f0f5-4924-97b0-1fd40c457efe"
			}
		},
		"scaleway_ip": {
			"ip": {
				"server": "${scaleway_server.host.id}"
			}
		}
	}
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

0. Create the above file
1. `terraform apply`
2. Edit the file, change the type from C2S to C2M
3. `terraform apply`

### Expected Behavior

- A new C2M server gets created
- It is attached to the existing "test-data" volume
- Reserved IP is associated with it
- Both the original C2S server and its main volume get destroyed.

### Actual Behavior
```
[...]
Error applying plan:

1 error(s) occurred:

* scaleway_volume_attachment.data (destroy): 1 error(s) occurred:

* scaleway_volume_attachment.data: timeout while waiting for state to become 'success' (timeout: 5m0s)
[...]
```

**None** of the resources (server, volumes, volume_attachments, ips) get destroyed.

I suspect the issue is with the server not being stopped before trying to detach the volume. (EDIT: maybe not, manually stopping the server does not help)

### Edit: logs

https://gist.github.com/polymeris/4b74548ee854709ff12a2ea185c1fbce

**Comment by nicolai86** [comment]
Thank you for the bug report, @polymeris .

In this case the best we can probably do is to increase the timeout.
To change volumes on a scaleway server the server needs to be stopped, and to stop a server all data is transfered from the attached volumes. there are some cases in the scaleway community forum where this apparently took more than [24 hours](https://community.online.net/t/shut-down-c1-more-than-an-hour-ago-still-transferring-data/3405).

From your logs I can see that terraform only waited 5 minutes which is far too short. I'll look into this.

**Comment by polymeris** [comment]
Is that just for "baremetal" servers?

I tried stopping the server manually before `terraform apply` and still get the same issue, btw.
