### ISSUE TITLE
[scaleway provider] duplicate volume creation when declaring system volume

### ISSUE THREAD

**Issue by polymeris** [hashicorp/terraform#14699]
Looking for a way to use terraform to vertically scale on scaleway (keep a volume, change the server specs).

### Terraform Version
v0.9.5

### Affected Resource(s)
- scaleway_server
- scaleway_volume

### Terraform Configuration Files
``` json
{
  "provider": {
    "scaleway": {
      "region": "par1"
    }
  },
  "resource": {
    "scaleway_volume": {
      "data": {
        "name": "test-data",
        "size_in_gb": 50,
        "type": "l_ssd"
      }
    },
    "scaleway_volume_attachment": {
      "data": {
        "server": "${scaleway_server.host.id}",
        "volume": "${scaleway_volume.data.id}"
      }
    },
    "scaleway_server": {
      "host": {
        "name": "test",
        "type": "VC1M",
        "image": "d0c50b37-f0f5-4924-97b0-1fd40c457efe",
        "volume": {
          "size_in_gb": 50,
          "type": "l_ssd"
        }
      }
    },
    "scaleway_ip": {
      "ip": {
        "server": "${scaleway_server.host.id}"
      }
    }
  }
}
```

### Expected Behavior
2 volumes should be created:
- The system volume
- An additional 50 gb volume labeled "test-data"

### Actual Behavior
Three 50 gb volumes get created:
- System volume ("x86_64-docker-latest-2016-10-24_15:48")
- "test-50"
- "test-data"

Since the max storage per VC1M instance is 100gb, this causes `terraform apply` to fail.

### Steps to Reproduce
With the above config:
1. `terraform apply`

### References
The system volume option is not documented in the docs. I am basing the config on the example in PR #9695

**Comment by nicolai86** [comment]
thanks for reporting this, @polymeris .

This is actually expected behaviour as every server has a System Volume, which can not be modified like this. The `volume` attribute on a `scaleway_server` resource was meant to allow volumes bound to the live time of the server. 

To my best knowledge modifying the System Volume would require you to build your own image, which is much more involved and outside the scope of terraform. Packer would probably be a better place for this.

**Comment by polymeris** [comment]
Thanks, Nicolai.

What's the proper configuration to create a 50gb system volume + one additional 50gb volume, then?

If I leave out `scaleway_server.volume` is still get an error:

```
* scaleway_server.host: StatusCode: 400, Type: invalid_request_error, APIMessage: The total volume size of VC1M instance
s must be between 51GB and 100GB
```

#### tf.json

``` json
{
  "provider": {
    "scaleway": {
      "region": "par1"
    }
  },
  "resource": {
    "scaleway_volume": {
      "data": {
        "name": "test-data",
        "size_in_gb": 50,
        "type": "l_ssd"
      }
    },
    "scaleway_volume_attachment": {
      "data": {
        "server": "${scaleway_server.host.id}",
        "volume": "${scaleway_volume.data.id}"
      }
    },
    "scaleway_server": {
      "host": {
        "name": "test",
        "type": "VC1M",
        "image": "d0c50b37-f0f5-4924-97b0-1fd40c457efe"
      }
    },
    "scaleway_ip": {
      "ip": {
        "server": "${scaleway_server.host.id}"
      }
    }
  }
}
```

**Comment by nicolai86** [comment]
The same issue was discussed in #9254 if I'm not mistaken.

**Comment by polymeris** [comment]
Yes, that is supposedly solved by #9695, though, which indicates an explicit `scaleway_server.volume` should be used -- that's why I tried that at first. I understand it's a scaleway API quirk, though, and possible not something you want to solve.

**Comment by nicolai86** [comment]
@polymeris hiding this would be a tough sell as terraform would create extra resources you did not request.

If you want to use a volume not bound to the server lifetime we need to enhance volume to also work with an id to an existing volume..

Would that be a good solution?

**Comment by polymeris** [comment]
Yes, that should work.
