### ISSUE TITLE
EntityTooLarge: Your proposed upload exceeds the maximum allowed size

### ISSUE THREAD

**Issue by dragan** [hashicorp/terraform#14693]
When using the `aws_s3_bucket_object` resource, I'm not able to upload large files. However, using the aws cli, I am without any changes to the bucket policy.

### Terraform Version

v0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket_object

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket_object" "monolith_development_0_0_2" {
  bucket  = "${aws_s3_bucket.my_bucket.bucket}"
  key     = "path/to/large/file.bin"
  source = "${format("%s/path/to/large/file.bin", path.cwd)}"
}
```

### Debug Output

https://gist.github.com/dragan/bd658a64fe8db87fb880410ed7b190a1

### Expected Behavior

Upload the file

### Actual Behavior

```
Error applying plan:

1 error(s) occurred:

* aws_s3_bucket_object.monolith_development_0_0_2: Error putting object in S3 bucket (concur-faraday-integration-backup): EntityTooLarge: Your proposed upload exceeds the maximum allowed size
        status code: 400, request id: F9D925AB9BA31A72

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce

1. `terraform plan -out=plan.bin`
2. `terraform apply plan.bin`

### Important Factoids

None

### References

Not that I know of

**Comment by bclodius** [comment]
@dragan how large is the file? Larger than 5GB?

**Comment by dragan** [comment]
@bclodius Yes, the files I tried were larger than 5GB. One was around 7GB and the other's around 20GB.

**Comment by bclodius** [comment]
@dragan Currently terraform using generic put object api which can only support up to 5GB.  I'll take a look at a possible PR for multipart upload but it may be some time and may not be welcome...

**Comment by apparentlymart** [comment]
Hi @bclodius,

If you have the time and motivation, a change to support multi-part upload when the `source` argument is used seems like a reasonable one to make.

Doing this for the `content` argument feels on more shaky ground since I wouldn't want to encourage people to load multi-gigabyte files into memory to populate that attribute.

**Comment by bclodius** [comment]
@apparentlymart Thanks for the suggestion.  I'll work on this!

**Comment by bclodius** [comment]
@apparentlymart I've started to take a stab at this; don't think i'll be able to finish it but will give it a try over the next few days.

**Comment by bclodius** [comment]
@apparentlymart I will not be able to work on this

**Comment by apparentlymart** [comment]
Thanks for letting me know, @bclodius! I expect this is not something the Terraform team at Hashicorp will get to in the near future, but I'll leave this open for now in case someone else wishes to work on it.
