### ISSUE TITLE
Terraform JSON key is ignored

### ISSUE THREAD

**Issue by thegranddesign** [hashicorp/terraform#14702]
### Terraform Version
0.9.1

### Affected Resource(s)
State Backends

### Description
When attempting to configure remote backends using JSON syntax, it appears that the `terraform` key is ignored.  No error is thrown.

### Example Configuration

```json
{
  "terraform": {
    "backend": {
      "s3": {
        "bucket": "mybucket",
        "key":    "terraform/terraform.tfstate",
        "region": "my_region"
      }
    }
  }
}
```

^^^ This does not work

```hcl
terraform {
  backend "s3" {
    bucket = "mybucket",
    key    = "terraform/terraform.tfstate",
    region = "my_region"
  }
}
```

^^^ This does

**Comment by thegranddesign** [comment]
It appears that this is similar to #13037.

This syntax works:

```json
{
  "terraform": {
    "backend": [
      {
        "s3": {
          "bucket": "mybucket",
          "key":    "terraform/terraform.tfstate",
          "region": "my_region"
        }
      }
    ]
  }
}
```

Do any of the maintainers know when the fix will be in for these sorts of issues?

**Comment by apparentlymart** [comment]
Hi @thegranddesign! Sorry for more JSON weirdness.

We are starting to plan some work on configuration, which should include making the JSON processing more robust. Still early days on that planning, but this is still on our radar.

**Comment by thegranddesign** [comment]
Ok I'll close the
