### ISSUE TITLE
Terraform dumps DEBUG output on ctrl-c

### ISSUE THREAD

**Issue by kojiromike** [hashicorp/terraform#14732]
### Terraform Version
0.9.5

When terraform receives a SIGINT, it starts dumping a lot of DEBUG messages to the terminal before exiting. While that information could be useful to someone trying to debug a problem, ctrl-c is not a problem - it is just a user asking terraform to stop. For the user not trying to debug, the noise level obscures useful information on the terminal, and gives the unnecessarily scary impression that something has gone wrong.

**Comment by kmoe** [comment]
I don't think this happens any more.
