### ISSUE TITLE
Separate credentials for S3 backend and actual terraform

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#14730]
Terraform: 0.9.5

Is it possible to provide a separate pair of credentials for S3 backend and separate credentials for terraforming the environment?

Use case:
I have a multi account setup and I want to store all the states from all the sub accounts in the Master account's S3 bucket.

**Comment by jbardin** [comment]
Hi @Puneeth-n,

That should work, the backend configuration and the provider configuration are independent, and you can provide different credentials in both.

Do you have an example configuration that isn't working?

**Comment by Puneeth-n** [comment]
@jbardin aaah I see that `Terraform init` was reading from the `awscli` config and so was never asking my credentials. Thanks for the help!
