### ISSUE TITLE
Terraform 0.4.1 no longer detecting SSH key in AWS during plan run

### ISSUE THREAD

**Issue by ascendantlogic** [hashicorp/terraform#1474]
After upgrading to 0.4.0 and attempting to use the new `aws_db_instance` resource and seeing a huge crash, I upgraded to 0.4.1. Once I did that I was not presented with a stacktrace, but rather a message claiming that my "blackbird-us-west-2" key was not present (and it is). 

[Here is a gist containing the output of the 0.4.0 and 0.4.1 runs](https://gist.github.com/ascendantlogic/c6ce7c2db1890f508bea)

Here is the resource in question:

```
resource "aws_key_pair" "blackbird" {
  key_name = "blackbird-${var.region}"
  public_key = "${var.ssh_key}"
}
```

Here are the variable values in my `us-west-2.tfvars` file

```
region = "us-west-2"
...
ssh_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDblah blah blah this value didn't change between runs"
```

And finally here is a screenshot of the Key Pairs in us-west-2 AWS console:
![image](https://cloud.githubusercontent.com/assets/60331/7081811/796c3f68-df16-11e4-8abe-0cfabb445748.png)

**Comment by catsby** [comment]
Thanks for writing in @ascendantlogic – I'm having trouble reproducing this though, can you provide some more info?

Which resources are referencing the key pair in question? Can you share the config for them (care to redact secrets of course).

Thanks!

**Comment by ascendantlogic** [comment]
@catsby essentially all AWS instances I'm spinning up minus my NAT boxes. Do you need all resources to be exhaustive? There's no secrets since I've got everything templated in variables, they're just spread out across multiple files. Here's an instance of one:

```
resource "aws_instance" "production_api3" {
  ami = "${lookup(var.base_amis, var.region)}"
  instance_type = "${var.api_instance_size}"
  availability_zone = "${var.region}c"
  subnet_id = "${aws_subnet.az3_private.id}"
  security_groups = ["${aws_security_group.default.id}", "${aws_security_group.api.id}"]
  key_name = "${aws_key_pair.blackbird.key_name}"

  tags = {
    Name = "production-api-3"
    Role = "api"
    Environment = "production"
  }
}
```

**Comment by ascendantlogic** [comment]
@catsby do you need more from me?

**Comment by catsby** [comment]
Probably not, thanks! 
I'll see about reproducing

**Comment by ascendantlogic** [comment]
Looks like the error goes away in 0.4.2. [Here is a gist showing it working properly in 0.4.2 and still erroring in 0.4.1](https://gist.github.com/ascendantlogic/a85f2a0004e210c7f6c6).

**Comment by ascendantlogic** [comment]
@catsby is under the impression [this pull request](https://github.com/hashicorp/terraform/pull/1487) may have inadvertently fixed my issue. I'm going to close this assuming it is indeed fixed.

**Comment by catsby** [comment]
Thanks! Please re-open if you hit it again
