### ISSUE TITLE
Feature request: minimum version declarations

### ISSUE THREAD

**Issue by MikeSchuette** [hashicorp/terraform#14744]
Some of my projects are stuck on older versions of Terraform.  This makes it difficult to discern whether any terraform modules found on Github / etc are compatible with my project.  If that code were able to declare "requires 1.0" for example, then a graceful error message could be displayed on older versions instead of a volley of interpolation syntax errors.

**Comment by radeksimko** [comment]
Hi,
there's already way to specify version constraints, see relevant documentation at https://www.terraform.io/docs/configuration/terraform.html#specifying-a-required-terraform-version

As mentioned there it will work with modules too.
