### ISSUE TITLE
Apply aws_route to multiple peering connections

### ISSUE THREAD

**Issue by ctippur** [hashicorp/terraform#14740]
Hello,

I have 3 vps's - A, B, C

I need bi directional connection from A to B and B to C

When I get to B which is common between the peering connections, I seem to have hit a issue. If I have B - A before B-> C, B -> C route gets deleted.

For example
```
resource "aws_route" "r" {
  route_table_id            = "rtb-4fbb3ac4"
  destination_cidr_block    = "10.0.1.0/22"
  vpc_peering_connection_id = "pcx-45ff3dc1"
}

resource "aws_route" "r" {
  route_table_id            = "rtb-4fbb3ac4"
  destination_cidr_block    = "10.0.2.0/22"
  vpc_peering_connection_id = "pcx-45dd4ca2"
}
```
The connection to  10.0.2.0/22 trumps over 10.0.1.0/22. Wondering if this is a known issue or something that I am doing wrong.
Appreciate any input.

- S

**Comment by ctippur** [comment]
Any updates on this pls?

**Comment by ctippur** [comment]
I need to add more information to this.

Here is the structure:
```
├── modules
│   └── vpc_stg
│       ├── main.tf
│       ├── outputs.tf
│       └── variables.tf
│   ├── app_server
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   ├── user_data.sh
│   │   └── variables.tf
└── stg
    ├── main.tf
    ├── notes
    ├── outputs.tf
    ├── terraform.tfstate.backup
    ├── terraform.tfvars
    └── variables.tf
```
I am creating a aws_route_table resource in app_server which creates a route table for 2 subnets. I am trying to access this in vpc_stg and trying to add routes to that via:
```
resource "aws_route" "new2prod" {
  count = 2
  route_table_id = "${element(var.route_table_nat_id, count.index)}"
  destination_cidr_block = "10.0.0.0/16"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.prod.id}"
}

resource "aws_route" "new2dev" {
  count = 2
  route_table_id = "${element(var.route_table_nat_id, count.index)}"
  destination_cidr_block = "172.31.0.0/16"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.peer.id}"
}
```
These routes are not getting added. Appreciate any help.

- S

**Comment by ctippur** [comment]
I see a similar reference here https://github.com/hashicorp/terraform/pull/3548
Not sure how to implement this.

**Comment by ctippur** [comment]
Any updates on this please?

**Comment by Puneeth-n** [comment]
@ctippur can you share the `aws_route_table` resource in `app_server` module?
