### ISSUE TITLE
Documentation is missing for aws_elb_attachment.count property

### ISSUE THREAD

**Issue by aleybovich** [hashicorp/terraform#14755]
aws_elb_attachment resource has a property `count` which is not mentioned in the documentation in TF 0.9.4 That property is very useful, please add it to the documentation

**Comment by stack72** [comment]
Hi @aleybovich 

So, `count` is actually a meta parameter available to *all resources*. It isn't specifically for `aws_elb_attachment`. You can find a full list of the meta parameters [here](https://www.terraform.io/docs/configuration/resources.html#meta-parameters) 

Hope this helps?

Paul
