### ISSUE TITLE
Terraform is creating duplicate resources every time I apply

### ISSUE THREAD

**Issue by lyptt** [hashicorp/terraform#14751]
### Terraform Version
0.9.5

### Affected Resource(s)
- aws_api_gateway_rest_api
- aws_api_gateway_deployment
- aws_api_gateway_integration
- aws_api_gateway_method
- aws_api_gateway_method_response
- aws_iam_role

### Terraform Configuration Files
[terraform.zip (gpg encrypted)](https://github.com/hashicorp/terraform/files/1021661/terraform.zip)

### Debug Output
https://gist.github.com/lyptt/30ef45f4083b0c2e56cc7ed84b3bb87a

### Expected Behavior
Terraform should have properly diffed the infrastructure, and applied changes to the existing infrastructure.

### Actual Behavior
Terraform attempts to create everything completely from scratch, and fails due to duplicate IAM roles.

### Important Factoids
This project uses modules as each environment is pretty much identical apart from differing environment configuration. I do not use any additional arguments other than 'apply'. Required varables are provided via environment variables (`TF_VAR_XXX`).

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`terraform apply`

**Comment by lyptt** [comment]
It seems to be the case that when a resource conflict occurs (the IAM roles in my case), Terraform will ignore certain resource types previously saved in its state and attempt to recreate those resources from scratch. In my particular project only the Lambda function was not ignored.

**Comment by apparentlymart** [comment]
Hi @lyptt! Sorry for this weird behavior.

Are you able to share (possibly-redacted) output from `terraform plan` also? Since Terraform seems to think it needs to recreate these resources, it suggests that they aren't in the state by the time the plan is made, which could either be a bug in the previous apply (not recording the state of new resource properly) or an issue during the "refresh" step that happens in `terraform apply`, where Terraform updates its state to match the "real world" before making the plan. If the latter is true, we should see log lines in the plan output for refreshing those resources.

**Comment by lyptt** [comment]
Hey @apparentlymart, thanks for getting back to me.

Unfortunately I don't have a record of the plan log (I've switched to CloudFormation for now), however from memory I remember it was essentially identical to the apply log. It wanted to create all of the resources again.

The underlying cause of the fault was definitely my doing - I didn't do a proper cleanup of the IAM roles so a collision occurred during the apply. The key issue here though is that it's creating duplicate resources even though those already exist in the tfstate after a conflict failure occurs.

If you need any copies of my tfstate, they're all in my git history, so I'm happy to upload those.

I should note that after fixing the conflict issue, I got further issues with terraform creating duplicates when only changing my lambda's filename parameter incrementally for each module instance. Instead of just updating the lambda function's code, it would recreate the API Gateway and ignore the one it had created before.

Is there some strangeness potentially with modules and the API Gateway resource?
