### ISSUE TITLE
Terraform plan removes dynamic variable values from state file

### ISSUE THREAD

**Issue by rcostanzo** [hashicorp/terraform#1476]
I'm on 0.4.0 (I tried to test on 0.4.1 but https://github.com/hashicorp/terraform/issues/1466 prevented me). When I run terraform plan, my state file is updated and any dynamic output variable values are lost. This makes terraform output of those values not work afterwards.

Test resource file:
```
resource "aws_vpc" "extole" {
    cidr_block = "10.1.0.0"
    instance_tenancy = "default"
    enable_dns_support = true
    enable_dns_hostnames = true
}

output "vpc_id" {
    value = "${aws_vpc.extole.id}"
}
```

Pre-plan tfstate snippet:
```
{
    "version": 1,
    "serial": 44,
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {
                "vpc_id": "vpc-a50856c0"
            },
```

Post-plan tfstate snippet:
```
{
    "version": 1,
    "serial": 45,
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {
            },
```

**Comment by phinze** [comment]
Hi there, sorry for the trouble. I think this is a dup of #1369, which is high on our list of bugs to squash. Stay tuned over on that thread for the fix. :+1:
