### ISSUE TITLE
docs incomplete for aws_codepipeline resource

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#14762]
[The docs for `aws_codepipeline`](https://www.terraform.io/docs/providers/aws/r/codepipeline.html) seem to be missing some attributes.

In particular, the content of the `action` nested block within `state` is not documented, and neither is its nested `configuration` block. The latter seems to be a general map sent to AWS verbatim, so for that we probably need to dig up the relevant AWS API docs so we can include a link to explain what is valid in there.

**Comment by celkins** [comment]
The `encryption_key` block within the `artifact_store` is similarly incomplete, e.g.,

```hcl
artifact_store {
  location = "${aws_s3_bucket.foo.bucket}"
  type     = "S3"

  encryption_key {
    id   = "${aws_kms_key.foo.arn}"
    type = "KMS"
  }
}
```
