### ISSUE TITLE
local_file resource should have modes, not set executable bit by default

### ISSUE THREAD

**Issue by kojiromike** [hashicorp/terraform#14768]
### Terraform Version
0.9.5

### Affected Resource(s)
- local_file

### Terraform Configuration Files
```hcl
resource "local_file" "foo" {
  content = "contents"
  filename = "foo.txt"
}
```

My umask here is 0022

### Expected Behavior
A file should have been created with mode `-rw-r--r--`.

### Actual Behavior
A file was created with mode `-rwxr-xr-x`.

### Humble Opinions
While I would prefer the option of providing a specific mode in tf configuration, I think Terraform should fallback to supporting the standard behavior of `open`, which would result in the file not being executable.

**Comment by Lasering** [comment]
The local file should have an attribute to set the mode of the file.
