### ISSUE TITLE
0.4.1 terraform: aws_elb resource does not recognize a list of subnets returned by the split function

### ISSUE THREAD

**Issue by alexintel** [hashicorp/terraform#1477]
aws_elb resource does not recognize a "list" of subnets returned by the split function.
works:
...
subnets = ["subnet-xxx","subnet-yyy"] 
...

does not work:
...
subnets = "${split(",", var.elb_subnets)}"
...

where var.elb_subnets is defined in variables.tf as:

variable "elb_subnets" {
  description = "ELB subnets to use."
  default = "subnet-xxx,subnet-yyy"
}

**Comment by chrisferry** [comment]
Try this:   
subnets         = ["${split(",", var.subnet_azs)}"]

**Comment by alexintel** [comment]
Confirmed to work. Thanks :)
