### ISSUE TITLE
Race condition aws_db_instance

### ISSUE THREAD

**Issue by MichalMankowski** [hashicorp/terraform#14786]
### Terraform Version
Terraform v0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_db_instance
- aws_db_subnet_group

### Output
```
* aws_db_instance.default: Error creating DB Instance: DBSubnetGroupNotFoundFault: DBSubnetGroup 'testing' not found.
        status code: 404, request id: c3bedc5c-4061-11e7-bbeb-8b50b26793c4
```

### Expected Behavior
aws_db_instance should have wait longer for aws_db_subnet_group.

### Actual Behavior
aws_db_instance are trying to create database before aws_db_subnet_group creation is done. If I re-run apply I see that aws_db_subnet_group creation is done and there is no longer error for aws_db_instance.

### Steps to Reproduce
1.Use aws_db_instance and aws_db_subnet_group in module.
2.Apply on environment.

**Comment by stack72** [comment]
Hi @MichalMankowski 

Please can you post your terraform config - minus any secrets so that can try and replicate this?

Thanks

Paul

**Comment by danhopkins** [comment]
Just to confirm, we're seeing the same effect

**Comment by catsby** [comment]
We need to see example configuration that reproduces this to dig in. The way the graph works should prevent this, but if the configuration is not referencing things by interpolation there can be races. 

We have an acceptance test [TestAccAWSDBInstance_subnetGroup](https://github.com/hashicorp/terraform/blob/f-sweeper/builtin/providers/aws/resource_aws_db_instance_test.go#L121) that runs nightly and is passing, that demonstrates both resources used together. 

If anyone has a config that reproduces this we'll take a look!

**Comment by legomanaustralia** [comment]
For anyone that stumbled across this i managed to replicate this by entering the db_subnet_group_name using a string vs interpolation which resulted in the plan/graph not being calculated correctly.
e.g 
  db_subnet_group_name = "main" vs 
  db_subnet_group_name = aws_db_subnet_group.token-db-subnet-group.name
