### ISSUE TITLE
azurerm_sql_elasticpool Example Usage code fails

### ISSUE THREAD

**Issue by holmesb** [hashicorp/terraform#14785]
### Terraform Version
v0.9.5

### Affected Resource(s)
azurerm_sql_elasticpool

### Terraform Configuration Files
[Example Usage code](https://www.terraform.io/docs/providers/azurerm/r/sql_elasticpool.html):
```resource "azurerm_resource_group" "test" {
  name = "test"
  location = "West US"
}

resource "azurerm_sql_server" "test" {
    name = "test"
    resource_group_name = "${azurerm_resource_group.test.name}"
    location = "West US"
    version = "12.0"
    administrator_login = "4dm1n157r470r"
    administrator_login_password = "4-v3ry-53cr37-p455w0rd"
}

resource "azurerm_sql_elasticpool" "test" {
    name = "test"
    resource_group_name = "${azurerm_resource_group.test.name}"
    location = "West US"
    server_name = "${azurerm_sql_server.test.name}"
    edition = "Basic"
    dtu = 100
    db_min_dtu = 0
    db_max_dtu = 5
    pool_size = 5000
}
```

### Expected Behavior
SQL Elastic pool is created 

### Actual Behavior
Running Example Usage code gives:
"invalid or unknown key: db_max_dtu"
"invalid or unknown key: db_min_dtu"

After removing these two attributes, get 
```
Error applying plan:

1 error(s) occurred:

* azurerm_sql_server.test: 1 error(s) occurred:

* azurerm_sql_server.test: Error creating SQL Server: PUT https://management.azure.com/subscriptions/4689b617-acad-40dc-a40f-77a442339589/resourceGroups/test_resource_group/providers/Microsoft.Sql/servers/test?api-version=2014-04-01-preview giving up after 5 attempts

Terraform does not automatically rollback in the face of errors...
```

And then on second attempt:
```
Error applying plan:

1 error(s) occurred:

* azurerm_sql_server.test: 1 error(s) occurred:

* azurerm_sql_server.test: Error creating SQL Server: 40647 (404) - Subscription '4689b617-acad-40dc-a40f-77a442339589' does not have the server 'test'.

Terraform does not automatically rollback in the face of errors..
```

### Steps to Reproduce
Run Example Usage code

**Comment by stack72** [comment]
Hi @holmesb 

Apologies for this - I have just opened a PR that fixes the example - the params were named incorrectly - it will make it's way to the website within the next 10 minutes

Sorry again

Paul

**Comment by holmesb** [comment]
Still fails.  This issue is not closed.  Per my original post: "After removing these two attributes, get error..."

**Comment by holmesb** [comment]
Yes still fails (which is prob why you've reopened).  After changing the two attributes to:
db_dtu_min = 0
db_dtu_max = 5
get the same errors in my original post above "After removing these two attributes, get error..."
