### ISSUE TITLE
Unable to specify data disks for azurerm_virtual_machine_scale_set in storage profile section

### ISSUE THREAD

**Issue by atld** [hashicorp/terraform#14791]
### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
* azurerm_virtual_machine_scale_set

### Expected Behavior
It seems there should be a way to specify data disks when creating a virtual machine scale set. 
In [Azure VM scale sets documentation](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-attached-disks) it is described that it can be defined in dataDisks section in the storageProfile in the [ARM template](https://github.com/chagarw/MDPP/blob/master/101-vmss-os-data/azuredeploy.json), but as per [Terraform VMSS documentation](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_sets.html), only storage_profile_os_disk is supported.

**Comment by stack72** [comment]
Hi @atld 

This is only recently added to terraform via #13717 and will be released in Terraform 0.9.6

Thanks

Paul
