### ISSUE TITLE
google_container_cluster  node_config argument is not documented.

### ISSUE THREAD

**Issue by danisla** [hashicorp/terraform#14799]
The structure and arguments for the `node_config` is missing in the documentation.

Affected resources:

- [`google_container_cluster`](https://www.terraform.io/docs/providers/google/r/container_cluster.html#node_config)
- [`google_container_node_pool`](https://www.terraform.io/docs/providers/google/r/container_node_pool.html)

Found the possible arguments in the source here: https://github.com/hashicorp/terraform/blob/v0.9.5/builtin/providers/google/resource_container_cluster.go#L207

**Comment by danawillow** [comment]
Hey @danisla, which parameters are missing? I see all of them in the documentation for `google_container_cluster` at https://www.terraform.io/docs/providers/google/r/container_cluster.html. Node pools currently don't have support for NodeConfig (there's an open PR for it at https://github.com/hashicorp/terraform/pull/12811)
