### ISSUE TITLE
Terraform import of Amazon SG

### ISSUE THREAD

**Issue by devilmind** [hashicorp/terraform#14828]
Hi All,

### Terraform Version
I'm using a terraform 0.9.5 version

### Affected Resource(s)
- aws_security_group

I need to manage the SG changes on Amazon AWS using terraform.
My goal is to import a state of the existing SG in a file and create a terraform template from it, so when I need to update some SG Rule I can only change a terraform template and plan and apply it.

I'm implemented a bash script that using the Amazon CLI to retive a list of security group ids in a file.
The script will loop on the list and runs a terraform import command for each security group id in the list and write the output in the same file as you can see on below.

> ...
> while read sg_line; do
> 
> sg_id=$(cut -d ">" -f 1 <<< "$sg_line" | sed -e 's/ //g')
> sg_name=$(cut -d ">" -f 2 <<< "$sg_line" | sed -e 's/ //g'| sed -e 's/\./-/g')
> 
> 
> bind_name="aws_security_group.$sg_name"
> 
> terraform import -lock=true -state=terraform_imported_state.tfstate $bind_name $sg_id
> 
> done
> ...

If I run the batch command more then once, I'm observed that the file generated is always different (the list of ID is always the same).

To be more specific I observed that if a SG has many rules, terraform import will not generate the state file  mantaining the same order of those in a tfstate file so , after implemented a template from the first one state file, when I run a plan, I see always there are change to make instead I'm expecting that no changes need to be done if the template reflect the state correctly.

In that way It's not possible to me manage the rules in automatic way.

Can you help me on this?

Regards,

Antonio

**Comment by devilmind** [comment]
Someone can help me here? I'm stuck!
Thanks in advance

Antonio

**Comment by stack72** [comment]
Hi @devilmind 

Apologies for not getting back to you sooner - as you can see, we have a *lot* of traffic on this issue list. As much as possible, we try to keep the issue list for bugs and feature requests only. I would suggest that the best place to help with something like this would be in one of our community channels

https://www.terraform.io/community.html

Thanks

Paul

**Comment by devilmind** [comment]
Hi @stack72 , thanks for the answer!
I have followed the community link just to raise this issue.
What I have missed to do here? Can you help me to found the right way to hilight that?
I really don't know if this could be considered an issue or not.

Thanks in advance.

Antonio
