### ISSUE TITLE
idea: simple_resource for transformations and iterating

### ISSUE THREAD

**Issue by cemo** [hashicorp/terraform#14822]
I am not sure this is already available or not but I came a situation where I would like use it.

I would like to create a variable by iterating. For example, I have a CIDR like `10.0.0.0/24` and I need first 6 ip in this range. There is already an interpolation function like `cidrhost` but it creates only a single ip.

```
resource "simple_resource" "example" {
  count = 6
  value = "${cidrhost(var.cidr, count.index)}"
}

output example{
   value = "${ join(",", output_resource.example.*.value) }"
}

```

What do you think?

**Comment by cemo** [comment]
```
data "template_file" "example" {
  count    = "6"
  template = "${cidrhost("10.0.0.0/8", count.index )}"
}

output "example" {
  value = "${join(",", data.template_file.web_init.*.rendered)}"
}
```

I have accomplished my task but this is really not intuitive. I will leave it open until verifying my approach.

**Comment by jbardin** [comment]
Hi @cemo,

It looks like you've found the solution! The `template_file` and sometimes `null_resource` are the tools we use for this sort of problem.

**Comment by cemo** [comment]
And this is the other one for the purpose for future references:

```
resource "null_resource" "example" {
  count    = "6"
  triggers {
    a = "${cidrhost("10.0.0.0/8", count.index )}"
  }
}

output "example" {
  value = "${join(",", null_resource.example.*.triggers.a)}"
}
```
