### ISSUE TITLE
provider/aws: aws_db_instance does not wait correctly for replicate_source_db

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/terraform#14849]
### Terraform Version
v0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_db_instance

### Terraform Configuration Files
```hcl
resource "aws_db_instance" "primary" {

}

resource "aws_db_instance" "replica" {
  replicate_source_db = "${aws_db_instance.primary.name}"
}
```

### Expected Behavior
The replica resource should wait for the primary to be created and then create the replica resource. 

### Actual Behavior
The replica waits for the primary resource but executes too quickly before it has finished creating and fails because it can't find the primary instance. If plan and apply are run again, it completes successfully.

### Steps to Reproduce
1. `terraform plan`
1. `terraform apply`
1. `terraform plan`
1. `terraform apply`

**Comment by catsby** [comment]
Hey @sheldonkwok do you by chance have any output you could share from this? We have acceptance tests that run nightly to cover this and they're passing at the moment. We do have code that polls an `aws_db_instance` and doesn't move on until the operation is successful within a default of 40 minutes, so the database should be up. Of course there could be some eventual consistency issues with any given run, but they are mostly rare and our polling code should cover it. 

I did notice that in the example above you're using `aws_db_instance.primary.name` as the value for `replicate_source_db`. For the replicate source, you need to use the `identifier`: 

```
resource "aws_db_instance" "replica" {
  replicate_source_db = "${aws_db_instance.primary.identifier}"
}
```

In the even that the above snippet isn't just a typo, can you try that out and let me know?

**Comment by sheldonkwok** [comment]
Hi @catsby, I just tried it out with Terraform 0.9.6 and it worked fine. The previous `.name` was just a typo in the issue.

**Comment by catsby** [comment]
Typo aside, it's odd to work in 0.9.6 and not in 0.9.5. I don't believe much has changed there, but I haven't looked at the polling code. Let me know if you hit this again, for now I'll close this issue

**Comment by sheldonkwok** [comment]
@catsby just reproduced it.

```
module.dbmod.aws_db_instance.foo: Still creating... (15m30s elapsed)
module.dbmod.aws_db_instance.foo: Creation complete (ID: fooID)
Error applying plan:

1 error(s) occurred:

* module.dbmod.aws_db_instance.foo_replica: 1 error(s) occurred:

* aws_db_instance.foo_replica: Error creating DB Instance: DBInstanceNotFound: The source instance could not be found: fooID
        status code: 404, request id: requestID
```
