### ISSUE TITLE
Unexpected/Undesirable ListObjects Requirement for Remote State data sources

### ISSUE THREAD

**Issue by Zordrak** [hashicorp/terraform#14867]
Version: 0.9.6

data.terraform_remote_state

One of our remote state accesses now hits 403 Access Denied. This is because the bucket policy for the remote bucket allows only GetObject on the specific state file for the user trying to access it. 

It seems https://github.com/hashicorp/terraform/pull/14680 has now introduced a new requirement for ListObjects on the bucket as part of a check as to whether the file exists or not so as to create a lock or not.

We are not, however, using a locking mechanism, and the bucket can potentially contain sensitive data the originating user does not need to be aware of. We are also not using environments or environment targets. We only wish for terraform to be given an explicit bucket and key name for the storage of the remote data source state file, and for it to access it if it exists, and error if it does not.

Is it possible for the "exists" check for a remote state data source to use a separate function that only checks accessibility of the target?

Otherwise in the least we could do with some documentation on the precise change in permission requirements for remote state so that we can redesign our bucket management to segregate states if the ListObjects permission cannot be avoided?

Some Slack chatter about the matter:

```
zordrak [6:19 PM] 
Awooga. Major bug in 0.9.6. I have no idea how, I'm looking into changes introduced to checksum s3 stored remote state, but a remote state call to an s3 bucket in a different AWS account is returning 403 Access Denied. Same run, same parameters on all versions from 0.9.2 to 0.9.5 work just fine

chicagobuss [6:27 PM] 
yikes good catch

zordrak [6:27 PM] 
My latest theory is it's actually that remote state now needs more s3 permissions than just GET on the object

[6:27] 
cause our bucket policy is least-privilege

[6:28] 
unfortunately i crashed by browser trying to load the full jenkins console log with TRACE logging enabled :slightly_smiling_face:

chicagobuss [6:29 PM] 
two bugs in one

zordrak [6:30 PM] 
going again with DEBUG

[6:31] 
firing up the super-awesome kibana dashboard for cloudtrail logs

[6:34] 
bingo

[6:34] 
 ```17:30:04 2017/05/26 17:30:02 [DEBUG] plugin: terraform: terraform-provider (internal) 2017/05/26 17:30:02 [DEBUG] [aws-sdk-go] DEBUG: Response s3/ListObjects Details:
17:30:04 2017/05/26 17:30:02 [DEBUG] plugin: terraform: ---[ RESPONSE ]--------------------------------------
17:30:04 2017/05/26 17:30:02 [DEBUG] plugin: terraform: HTTP/1.1 403 Forbidden```

[6:34] 
So not bug, but undocumented change requiring more permissions (edited)

glasser [7:07 PM] 
oh yeah I know what change that is

[7:07] 
it was the fix to a force unlock bug

[7:08] 
https://github.com/hashicorp/terraform/pull/14680
GitHub
Check that a named state in s3 doesn't exist before acquiring a lock by jbardin · Pull Request #14680 · hashicorp/terraform
In order to force-unlock a named state, we have to fetch that state first. Don't attempt to acquire a lock if we know the state already exists in s3. Fixes #14666
 

[7:08] 
was the set of permissions required actually documented anywhere @zordrak ? (edited)

zordrak [7:09 PM] 
No probably not.. wouldn't hurt for that to go on the backlog

[7:09] 
i think it's probably just easy to presume it only needs to read the state file it's directed to, and so far that's been the case

[7:11] 
Wish my go-fu was better, keep trying to find where the exists check actually initiates a ListObjects and not seeing it

[7:12] 
Wanted to work it out so as to find out if List is the only new permission, and also what scope is needed for List

[7:16] 
ugh i see it now

[7:16] 
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 112)         existing, err := b.States()

[7:18] 
Does make me question whether we really need to list the objects in the bucket to do an exist check on a single object with a known key

zordrak [7:25 PM] 
The more I look at this, the less sense it makes

[7:25] 
 ```9f5cf2b105 (James Bardin 2017-03-21 13:43:31 -0400  17) const (
fa4dc01cf4 (James Bardin 2017-03-22 16:33:41 -0400  18)         // This will be used as directory name, the odd looking colon is simply to
fa4dc01cf4 (James Bardin 2017-03-22 16:33:41 -0400  19)         // reduce the chance of name conflicts with existing objects.
4980fa20e7 (James Bardin 2017-03-22 15:52:55 -0400  20)         keyEnvPrefix = "env:"
9f5cf2b105 (James Bardin 2017-03-21 13:43:31 -0400  21) )
9f5cf2b105 (James Bardin 2017-03-21 13:43:31 -0400  22) 
9f5cf2b105 (James Bardin 2017-03-21 13:43:31 -0400  23) func (b *Backend) States() ([]string, error) {
fa4dc01cf4 (James Bardin 2017-03-22 16:33:41 -0400  24)         params := &s3.ListObjectsInput{
fa4dc01cf4 (James Bardin 2017-03-22 16:33:41 -0400  25)                 Bucket: &b.bucketName,
fa4dc01cf4 (James Bardin 2017-03-22 16:33:41 -0400  26)                 Prefix: aws.String(keyEnvPrefix + "/"),
fa4dc01cf4 (James Bardin 2017-03-22 16:33:41 -0400  27)         }
```

[7:25] 
 ```b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 112)         existing, err := b.States()
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 113)         if err != nil {
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 114)                 return nil, err
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 115)         }
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 116) 
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 117)         exists := false
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 118)         for _, s := range existing {
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 119)                 if s == name {
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 120)                         exists = true
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 121)                         break
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 122)                 }
b279b1abb5 (James Bardin 2017-05-19 14:40:59 -0400 123)         }
```

[7:26] 
Do a ListObjects on the whole bucket, filter on objects where the key prefix is `env:/`

[7:27] 
exists == true if the state name matches one of the results (edited)

[7:29] 
But I'm trying to reference a specific state file (as a reference remote state, not a backend), with a specific key name, with no 'env:/' prefix in a remote bucket that I may or may not have List access to depending on the sensitivity of other data in that bucket

[7:29] 
@glasser This making any sense to you?

glasser [7:33 PM] 
I think what's going on is that the existing generic "remote backend" interface has two methods

[7:34] 
@zordrak a "list the states" method and a "get one state" method.  And the former doesn't require locking and the latter does

[7:34] 
the bug I reported was that force-unlock didn't work because basically every operation started with "take out a lock" (in case it needed to create the state from not existing), even force-unlock where that's clearly problematic

[7:35] 
i think definitely he could have added a "does state exist (no lock)" operation to the interface but it seemed simpler to use the pre-existing method?

zordrak [7:37 PM] 
I guess I don't quite see how that States() function would even tell you if the state exists or not, with it having a hardcoded key space

[7:39] 
Well.. I guess I'll open a bug with what I know, but will have to stick with 0.9.5 for now
```

**Comment by glasser** [comment]
One note: all the stuff in #14680 could be gated behind a check that the state name isn't the default (like it was before the PR), which would at least mean that you only need the ListObjects permission if you're using environments. I'm not sure if that's actually a great idea or not though, since the original bug probably would have been caught earlier if there wasn't a special conditional for default state name...

**Comment by glasser** [comment]
As a workaround — if you really aren't using environments, then you don't leak anything by giving permissions to List `env:/*`  ...
