### ISSUE TITLE
google_container_node_pool does not allow me to configure the node attributes

### ISSUE THREAD

**Issue by xcalibre0** [hashicorp/terraform#14866]
The GKE container clusters support using node pools as the primary means to have heterogeneous nodes in the cluster.

Terraform has a command to create a node pool for a cluster: "google_container_node_pool.  However, the documentation for that command does NOT allow me to set the machine type for the node pool.  This seems like an over sight since making specific adjustments for the machines used in the pool is the primary reason for the command's existence.

I have tried to just guess at parameters, trying both "node_config" and "machine_type".  I also looked at the trunk source code and found only the parameters for google_container_node_pool that are in the documentation.

### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
google_container_node_pool

### Debug Output
* google_container_node_pool.lms_node_pool: : invalid or unknown key: node_config
or
* google_container_node_pool.lms_node_pool: : invalid or unknown key: machine_type

### Expected Behavior
I would expect that the command for making google node pools would let me define the machine parameters for the nodes in the pool

**Comment by xcalibre0** [comment]
text from gclouds documentation of their node pool creation command:

> gcloud container node-pools create NAME --zone ZONE --cluster CLUSTER
> Optional flags:
> 
> --machine-type: The Google Compute Engine machine type (e.g. n1-standard-1) to use for instances in this container cluster. If unspecified, the default machine type is n1-standard-1.
> --num-nodes: Specifies the number of nodes to create in the container cluster. Default is 3. Your Cloud Platform Console project must have enough quota for the number of nodes, as well as sufficient route quota.
> --disk-size: Size in GB for node VM boot disks. Defaults to 100GB.
> --enable-cloud-endpoints: Automatically enable Google Cloud Endpoints to take advantage of API management features. Enabled by default, use --no-enable-cloud-endpoints to disable.
> --image-type IMAGE_TYPE: The image type to use for the node pool. Image Type specifies the base OS that the nodes in the node pool will run on. If an image type is specified, that will be assigned to the node pool and all future upgrades will use the specified image type. If it is not specified the server will pick the default image type.
> 
> The default image type and the list of valid image types are available using the following command.
> 
> gcloud container get-server-config
> --scopes SCOPE,[SCOPE,...]: Specifies scopes for the node instances. The project's default service account is used. Examples:
> 
> gcloud container node-pools create example-cluster \
>     --scopes https://www.googleapis.com/auth/devstorage.read_only
> 
> gcloud container node-pools create example-cluster \
>     --scopes bigquery,storage-rw,compute-ro
> Multiple SCOPEs can specified, separated by commas. The scopes necessary for the cluster to function properly (compute-rw, storage-ro), are always added, even if not explicitly specified.
> 
> SCOPE can be either the full URI of the scope or an alias. Available aliases are:

**Comment by xcalibre0** [comment]
I'm not sure to what degree it matters if it's an enhancement or a defect, but just to be clear; the command serves no actual purpose, it will run without crashing and create an irrelevant construct in gcloud, sure; but, if the requirement was to implement the command then i would consider this a defect as the command has no function.  Consider it a no-op.

**Comment by vapapav** [comment]
I was also confused by this and would like it fixed. For reference, Google's API documentation does include a NodeConfig object as part of the NodePool object, so it just seems as if this isn't being propagated and exposed in the Terraform APIs:

[https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters.nodePools#NodePool](url)

**Comment by vapapav** [comment]
More specifically, it looks like lines 83-86 of [resource_container_node_pool.go](https://github.com/hashicorp/terraform/blob/4e6dcb3a3e3a91f512c6afa7a726913f03b3fbd9/builtin/providers/google/resource_container_node_pool.go) need to be expanded to include a nodeConfig object.

Is this the sort of thing that the community fixes (I might be inclined to give it a try, though I know neither Go nor Terraform particularly well), or is it better to get it on the roadmap of the core hashicorp team?

**Comment by danawillow** [comment]
Hi @xcalibre0 and @vapapav, there's an open PR for this: https://github.com/hashicorp/terraform/pull/12811. I'm checking with the author to see how they're doing with my comments, otherwise I'll take it over and fix it.

@vapapav- yes, this is definitely something the community could fix! However, I'd recommend probably not attempting this one since it already has a fix out for review.

**Comment by vapapav** [comment]
Thanks Dana! No rush for me, but I appreciate your work on this.
