### ISSUE TITLE
terraform prompts several times to enter a provider.aws.region

### ISSUE THREAD

**Issue by viveknangal** [hashicorp/terraform#14876]
Hi All

I'm facing an issue whenever i change the name of a module , & run terraform command it prompts me for a  "provider.aws.region" input , though the same has been provided in the tfvars file.

### Terraform Version
MAC OS - Terraform v0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_vpc
- aws_subnet

### Terraform Configuration Files
I'm using the modules for aws_vpc & aws_subnet , invoking them in my application specific state
files .Following is the directory structure 

.
├── apps
│   └── website
│       ├── env
│       │   ├── staging.tf
│       │   ├── terraform.tfstate
│       │   └── terraform.tfstate.backup
│       └── main.tf
└── modules
    ├── ec2
    │   ├── main.tf
    │   └── variables.tf
    ├── subnet
    │   ├── main.tf
    │   └── variables.tf
    ├── terraform.tfvars
    └── vpc
        ├── main.tf
        └── variables.tf

```

```
### Expected Behavior
Terraform plan & output should run seamlessly without prompting for a "region" input whenever i change the name of my module

### Actual Behavior
What actually happened?
`provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Default: us-east-1
  Enter a value:`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

**Comment by bclodius** [comment]
@viveknangal To work around this you have two options.

1. Set `AWS_DEFAULT_REGION` environment variable
2. Ensure that provider blocks explicitly define the `region` attribute.
