### ISSUE TITLE
Error in AWS ElasticTranscoder content_config_permissions doc rendering

### ISSUE THREAD

**Issue by michaelhelmick** [hashicorp/terraform#14870]
### Expected Behavior
The `content_config_permissions` list should render as a list not in a paragraph.

### Actual Behavior
![screenshot 2017-05-26 16 48 47](https://cloud.githubusercontent.com/assets/352270/26512172/6181b5cc-4233-11e7-88d4-0882be37f191.png)

### Steps to Reproduce
View https://www.terraform.io/docs/providers/aws/r/elastic_transcoder_pipeline.html

What's strange is the markdown file seems to be valid.

**Comment by tombuildsstuff** [comment]
Hi @michaelhelmick 

Thanks for raising this issue :)

I've opened PR #14919 which includes a fix for this - it was missing an empty line needed to infer it's a list, rather than a continuation of the line above.

Thanks!
