### ISSUE TITLE
AWS - S3 Link in aws_lambda_function

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform#14877]
### Terraform Version
0.9.5

### Affected Resource(s)
- [aws_lambda_function](https://www.terraform.io/docs/providers/aws/r/lambda_function.html)

### Question
Is there an option to provide an S3 Link (URL) in [aws_lambda_function](https://www.terraform.io/docs/providers/aws/r/lambda_function.html) resource? I couldn't find this in the current documentation.

### Alternative / Work-around
One can use `s3_bucket` and `s3_key`

**Comment by Techbrunch** [comment]
Why would you want to use a link instead of the combination of the bucket and key ?

**Comment by tombuildsstuff** [comment]
Hi @vikas027

Not that I can see currently - do you have a use-case for when this would be preferable over using the bucket and key?

Thanks!

**Comment by vikas027** [comment]
Hello @tombuildsstuff ,

I was looking to create some public lambda deployment packages to help out for my friends (who are using terraform). It would be convenient for them to pick my packages.

Cheers.

**Comment by Techbrunch** [comment]
@vikas027 You can still do that using a bucket and a key.

**Comment by vikas027** [comment]
Yes, I can and I am doing that way. It is just a matter of convenience.
