### ISSUE TITLE
AWS cloudwatch log group tag update issues

### ISSUE THREAD

**Issue by johnthedev97** [hashicorp/terraform#14885]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.9.7-dev (60b162de45ee4af26882ed805ad6d4f03c3929b9)

### Affected Resource(s)
- aws_cloudwatch_log_group

### Terraform Configuration Files\
The gist below has the config file at each steps and commands I used
https://gist.github.com/johnthedev97/4b6237ebcaef6199ee892c156b918108

### Debug Output
https://gist.github.com/johnthedev97/4b6237ebcaef6199ee892c156b918108

### Panic Output
NA

### Expected Behavior
After the second terraform apply (Line# 48 in gist), the list-tags at line# 63 should not have the tag "Tag1" since it was removed
After the third terraform apply (Line# 82 in gist) should update the value of 'Tag2" from "" => "Two"

### Actual Behavior
After first apply, "Tag1" was not removed. see output of list tags
Second apply never completed

### Steps to Reproduce
The gist has the commands and files I used in each step

**Comment by johnthedev97** [comment]
I have created a PR with possible fix as well - https://github.com/hashicorp/terraform/pull/14886

**Comment by johnthedev97** [comment]
Here is a gist of run of the same tests after fix https://gist.github.com/johnthedev97/17c22380ea3dc0110579cbba6c145c32

**Comment by stack72** [comment]
Closed via #14886
