### ISSUE TITLE
Meta Issue: Migrate to upstream awslabs/aws-sdk-go

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#1488]
This is a meta issue to track our migration of AWS resources to the upstream version of `aws-sdk-go` at https://github.com/awslabs/aws-sdk-go. 

If anyone would like to contribute, see my previous PRs (linked below) for examples of the general work to be done in each PR. To aid us here, there are upstream versions of `tags.go` and `structure.go`, with the `_sdk` prefix. In them are the `awslabs` version of the methods contained in the originals, so `tagsToMap` becomes `tagsToMapSDK`, etc. 

| Resource | PR | Merged |
| ---- |---- |---- | 
 autoscaling group | #1513 | ✓
db instance | #1510  | ✓
db parameter group | #1510  | ✓
db security group | #1510  | ✓
db subnet group | #1510  | ✓
eip | https://github.com/hashicorp/terraform/pull/1408 | ✓
elb | #1532 | ✓
instance |#1558 | ✓
internet gateway | https://github.com/hashicorp/terraform/pull/1407 | ✓
key pair | https://github.com/hashicorp/terraform/pull/1397 | ✓
launch configuration | #1553 | ✓
main route table association | #1489 | ✓
network acl | #1509 | ✓
network_interface | https://github.com/hashicorp/terraform/pull/1411 | ✓
route53 record  | #1519 | ✓
route53 zone | #1519 | ✓
route table | #1489 |  ✓
route table association | #1489 | ✓
s3 bucket | #1520  |  ✓
security group | https://github.com/hashicorp/terraform/pull/1446 | ✓
subnet | https://github.com/hashicorp/terraform/pull/1398 | ✓
vpc | https://github.com/hashicorp/terraform/pull/1486 | ✓
vpc peering connection | #1522 | ✓
vpn gateway | #1531  | ✓

Questions? 
Missing something? 
Ask and I'm here to help :smile:

**Comment by fromonesrc** [comment]
@catsby I'm trying to take a shot at converting the instance resource but hitting errors like

```
builtin/providers/aws/resource_aws_instance.go:322: undefined: "github.com/awslabs/aws-sdk-go/service/ec2".RunInstancesRequest
builtin/providers/aws/resource_aws_instance.go:359: undefined: "github.com/awslabs/aws-sdk-go/aws".Integer
builtin/providers/aws/resource_aws_instance.go:799: undefined: "github.com/awslabs/aws-sdk-go/aws".StringValue
```

Could you help point me in the right direction?

**Comment by fromonesrc** [comment]
Figured it out... it helps if I use the correct methods :smile:

**Comment by fromonesrc** [comment]
@catsby just in case you were waiting for me on the instance conversion, I moved on to route53 and haven't come back to instance yet, feel free to bring that over

**Comment by catsby** [comment]
No worries, I'm doing Instance today and then we'll be done!

**Comment by catsby** [comment]
Everything is merged!
