### ISSUE TITLE
Terraform 0.9.6 crash on OSX

### ISSUE THREAD

**Issue by weitzj** [hashicorp/terraform#14904]
### Terraform Version

Terraform v0.9.6
16.5.0 Darwin Kernel Version 16.5.0 (OSX 10.12.4)

### Affected Resource(s)

- scaleway_waitForServerState

The whole Terraform process crashes in `dag/walk`

### Debug Output

https://gist.github.com/weitzj/c5339fe349078f68f3ee371c1481240f

### Expected Behavior
Terraform should have waited until Scaleway server is created

### Actual Behavior
What actually happened?
Terraform crashed while waiting for Scaleway to create Server.

On Terraform v0.9.5 this crash does not happen to me.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by nicolai86** [comment]
Thank you for reporting this, @weitzj. Do you happen to have a minimal terraform file that reproduces this crash reliably?

**Comment by weitzj** [comment]
This crash occurs really with a stock Scaleway server. Talking to support, there were no free VC1L servers available in Paris any more, but the website and the api let me still create a server.

Starting the server failed on the Scaleway side, since it could not be allocated.

**Comment by nicolai86** [comment]
Thanks for the clarification. I'll check if there's a way to validate that a server can actually be allocated. In any case terraform should not crash, so I'll look into it.
