### ISSUE TITLE
Terraform is trying to delete resources where it doesn't make sense

### ISSUE THREAD

**Issue by Techbrunch** [hashicorp/terraform#14902]
### Terraform Version

0.9.5

### Affected Resource(s)

- data.terraform_remote_state
- data.aws_acm_certificate
- data.template_file

### Terraform Configuration Files

```hcl
data "terraform_remote_state" "master_state" {
  backend = "s3"

  config {
    bucket = "${var.tf_s3_bucket}"
    key    = "${var.master_state_file}"
    region = "${var.region}"
  }
}

data "aws_acm_certificate" "certificate" {
  domain   = "${var.subdomain}.issue.com"
  statuses = ["ISSUED"]
}

data "template_file" "lambda_s3_to_loggly" {
  template = "${file("${path.module}/policies/lambda_s3_to_loggly.json.tpl")}"
  vars {
    bucket_name = "plop-${var.environment}-loadbalancer-logs"
    key_prefix = "AWSLogs/*"
  }
}
```

### Debug Output

```
data.terraform_remote_state.master_state: Refreshing state...
data.template_file.lambda_s3_to_loggly: Refreshing state...
data.aws_acm_certificate.certificate: Refreshing state...
data.terraform_remote_state.master_state: Destroying... (ID: 2017-05-29 09:03:34.545598086 +0000 UTC)
data.terraform_remote_state.master_state: Destruction complete
module.iam_role.data.template_file.lambda_s3_to_loggly: Destroying... (ID: cb4c623ff64c8463775c137df8355ea24207e1ac9e9529bd54dd99afb79b3845)
module.iam_role.data.template_file.lambda_s3_to_loggly: Destruction complete
data.aws_acm_certificate.certificate: Destroying... (ID: 2017-05-29 09:03:34.463138149 +0000 UTC)
data.aws_acm_certificate.certificate: Destruction complete
```

### Expected Behavior

Those resources should not be deleted, there is nothing to delete.

### Actual Behavior

Everytime I run destroy I it says that those resources are deleted.

**Comment by catsby** [comment]
Hey @Techbrunch the `destroying` and `destruction` here are referring to the entry in the state file. When you apply the above, each of those data sources gets stored in the state file. Indeed there is nothing to delete, but it's shared terminology in the graph when removing both a resource or a data source. 

Sorry for the confusion!

**Comment by Techbrunch** [comment]
@catsby Is there another issue that aim to make that more clear ? I can imagine that if someone has a lot of data source it can become pretty hard to really see what is changing.
