### ISSUE TITLE
Azure VMSS documentation corrections

### ISSUE THREAD

**Issue by atld** [hashicorp/terraform#14906]
### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
* azurerm_virtual_machine_scale_set

### Terraform Configuration Files
```hcl
storage_profile_os_disk {
    name              = "myosdisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
```

### Expected Behavior
In case managed disks are used in Azure VMSS resource, name in storage_profile_os_disk must be set to blank. The example for managed disks in [documentation](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_sets.html) should reflect this. Name should be blank in example.

### Actual Behavior
With above example, Terraform drops following error:
```hcl
* azurerm_virtual_machine_scale_set.playout-vmss: [ERROR] Conflict between `name` and `managed_disk_type` on `storage_profile_os_disk` (please set name to blank)
```

Additionally, there is a bug in [documentation](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_sets.html):
in [lun](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_sets.html#lun) section, there is extra _Premium_LRS._ which I think should belong to managed_disk_type section.

**Comment by tombuildsstuff** [comment]
Hi @atld 

Thanks for reporting these issues :)

PR #14915 has been merged which solves the documentation bugs raised here - so I'm going to close this issue. I've also opened issue #14932 to make the `name` field Optional, rather than Required - so it doesn't need to be set to an empty string for a managed disk.

Thanks! :)
