### ISSUE TITLE
Moving count>1 resources in the list should not recreate them

### ISSUE THREAD

**Issue by mildred** [hashicorp/terraform#14918]
### Terraform Version
0.9.3

### Affected Resource(s)
Tested with aws_ecr_repository but this is a generic issue

### Terraform Configuration Files
```hcl
resource "aws_ecr_repository" "client-registry" {
  name  = "client-${element(compact(split(",", var.containers_list)), count.index)}"
  count = "${length(compact(split(",", var.containers_list)))}"
}

variable "containers_list" {
  description = "list of repository short names to include in infrastructure"
}
```
### Test Scenario

- Apply with `containers_list=hello`
- It works
- Plan with `containers_list=hello2,hello`
- Apply, it doesn't work

### Expected Behavior

- Plan should not recreate the hello repository
- Apply should work in any case

More generally, when a resource changes its position in a list, it should be detected as such (the resource name changes from `aws_ecr_repository.client-registry.0` to `aws_ecr_repository.client-registry.1` in that case) and the resource should not be recreated.

### Actual Behavior

- Plan will try to delete the hello container and recreate it because its position in the list has changed

    ```
    deploy_1            | -/+ aws_ecr_repository.client-registry.0
    deploy_1            |     arn:            "arn:aws:ecr:eu-west-1:095348363195:repository/client-regeneration-ronstring-staging-hamadr-hello" => "<computed>"
    deploy_1            |     name:           "client-regeneration-ronstring-staging-hamadr-hello" => "client-regeneration-ronstring-staging-hamadr-hello2" (forces new resource)
    deploy_1            |     registry_id:    "095348363195" => "<computed>"
    deploy_1            |     repository_url: "095348363195.dkr.ecr.eu-west-1.amazonaws.com/client-regeneration-ronstring-staging-hamadr-hello" => "<computed>"
    deploy_1            | 
    deploy_1            | + aws_ecr_repository.client-registry.1
    deploy_1            |     arn:            "<computed>"
    deploy_1            |     name:           "client-regeneration-ronstring-staging-hamadr-hello"
    deploy_1            |     registry_id:    "<computed>"
    deploy_1            |     repository_url: "<computed>"
    ```

- Apply doesn't work anyway because it will try to create the hello repository before destroying the old one

    ```
    deploy_1            | Error applying plan:
    deploy_1            | 
    deploy_1            | 1 error(s) occurred:
    deploy_1            | 
    deploy_1            | * aws_ecr_repository.client-registry[1]: 1 error(s) occurred:
    deploy_1            | 
    deploy_1            | * aws_ecr_repository.client-registry.1: RepositoryAlreadyExistsException: The repository with name 'client-regeneration-ronstring-staging-hamadr-hello' already exists in the registry with id '095348363195'
    deploy_1            |     status code: 400, request id: 52fdbaee-444d-11e7-a19d-1b9a72d10010
    ```

**Comment by debu99** [comment]
same problem, how to skip if repo is already exist?

**Comment by apparentlymart** [comment]
Hi @mildred, @debu99. Sorry things aren't working as expected here.

This is the same issue being discussed in #10850. I responded over there with our best idea of how we might address this problem in future, though we need to do some more design work before we could start implementing this. In the mean time, I'm going to close this issue to consolidate the discussion over there.

Thanks for reporting this!
