### ISSUE TITLE
Misleading error when `final_snapshot_identifier` is set, and `skip_final_snapshot = true`

### ISSUE THREAD

**Issue by rockholla** [hashicorp/terraform#14913]
I'm on `v0.9.4`

I was temporarily trying to disable final snapshots on an rds instance resource when running into this error:

```
* module.customizations.aws_db_instance.garden[0]: : invalid or unknown key: skip_final_shapshot
```

Here's the resource block that triggers the error:

```
resource "aws_db_instance" "garden" {
  count                     = 2
  allocated_storage         = 10
  storage_type              = "gp2"
  engine                    = "mariadb"
  instance_class            = "db.t2.micro"
  identifier                = "${var.garden}-${count.index}"
  username                  = "root"
  password                  = "**********"
  final_snapshot_identifier = "${var.garden}-${count.index}-final"
  skip_final_shapshot       = true
}
```

I finally just tried removing `final_snapshot_identifier` from my config and all was well, but the error seems to suggest that the `skip_final_snapshot` is simply an invalid field for the resource.  Seems reasonable to assume both fields could be set and terraform just makes appropriate decisions internally about what to do, e.g. if `skip_final_snapshot` is set to true, just ignore whatever the value in `final_snapshot_identifier`.

Related issue: https://github.com/hashicorp/terraform/issues/5417

**Comment by rockholla** [comment]
#5417

**Comment by stack72** [comment]
Hi @rockholla 

Apologies for the error here - this is due to a spelling mistake:

```
skip_final_shapshot
```

should be

```
skip_final_snapshot
```

Hope this helps

Paul

**Comment by rockholla** [comment]
thanks @stack72, completely missed that.
