### ISSUE TITLE
Inconsistent output format vs resource addressing

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform#14924]
### Terraform Version
v0.9.6

### Affected Resource(s)
Core

### Terraform Configuration Files
```hcl
resource "azurerm_sql_firewall_rule" "firewall" {
    count = "${length(var.firewall_rules)}"
    name = "${lookup(var.firewall_rules[count.index], "label")}"
    resource_group_name = "${var.resource_group}"
    server_name = "${azurerm_sql_server.sql.name}"
    start_ip_address = "${lookup(var.firewall_rules[count.index], "start")}"
    end_ip_address = "${lookup(var.firewall_rules[count.index], "end")}"
}
```

### Debug Output
```
+ module.sql.azurerm_sql_firewall_rule.firewall.1
    end_ip_address:      "255.255.255.255"
    name:                "Open to the world"
    resource_group_name: "blah-dev"
    server_name:         "blah-dev"
    start_ip_address:    "0.0.0.0"
```

### Expected Behavior
Resource name should be `azurerm_sql_firewall_rule.firewall[1]`

### Actual Behavior
Resource name is `azurerm_sql_firewall_rule.firewall.1`

### Important Factoids
I ran into this when using `state mv`, to transfer resources from repeated blocks into a list. In most cases the output from terraform plan is in the same resource addressing format required for input to move.

However when working with lists the output formats are different.

I imagine this is probably quite difficult to safely change at this point, but I wanted to report it anyway.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @glenjamin!

Indeed unfortunately there are still several inconsistencies in how resource instances are identified in the UI, stemming from the fact that the resource address syntax was added relatively recently compared to many long-standing features like the plan output.

Would definitely like to fix these inconsistencies, though!

**Comment by apparentlymart** [comment]
Hi @glenjamin! Sorry for the long silence here.

We actually tweaked this in the plan output several versions ago but I forgot that there was an issue open for it. :confounded: 

The plan rendering has been revamped in master for the forthcoming v0.12.0 release, but this new rendering retains the standard resource address syntax in spite of the fact that other elements are changed around it:

```
Terraform will perform the following actions:

  # null_resource.a[1] will be created
  + resource "null_resource" "a" {
      + id = (known after apply)
    }

  # null_resource.b[1] will be created
  + resource "null_resource" "b" {
      + id       = (known after apply)
      + triggers = (known after apply)
    }
```

Thanks for pointing this out, and sorry I forgot to update this issue before!
