### ISSUE TITLE
Missing required plan information support for Azure Marketplace images in azurerm_virtual_machine_scale_set

### ISSUE THREAD

**Issue by atld** [hashicorp/terraform#14926]
### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
* azurerm_virtual_machine_scale_set

### Terraform Configuration Files
```hcl
...
resource "azurerm_virtual_machine_scale_set" "worker-vmss" {
  name                = "worker-vmss"
  location            = "West Europe"
  resource_group_name = "${azurerm_resource_group.psqldemo-rg.name}"
  upgrade_policy_mode = "Manual"

  plan {
    name = "docker-ce"
    product = "docker-ce"
    publisher = "docker"
  }
...
```
### Expected Behavior
According to[ virtualMachineScaleSets template reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachinescalesets), for Azure marketplace images, [Plan](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#plan) section should be supported in azurerm_virtual_machine_scale_set resource, similarly like for azurerm_virtual_machine resource type. 

### Actual Behavior
During VMSS creation, in case there is no plan section, Terraform drops the following error:
```hcl
* azurerm_virtual_machine_scale_set.worker-vmss: 1 error(s) occurred:

* azurerm_virtual_machine_scale_set.worker-vmss: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="VMMarketplaceInvalidInput" Message="Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is worker-vmss_worker-vmss_0_OsDisk_1_97a2010334f9449baad0f65c9a6351e9."
```

If I define plan section, I got following error:
```hcl
1 error(s) occurred:

* azurerm_virtual_machine_scale_set.worker-vmss: : invalid or unknown key: plan
```

**Comment by laurentgrangeau** [comment]
I have the same problem when using azurerm_virtual_machine and docker-ee

**Comment by atld** [comment]
Do you have an estimation when this can be implemented? Currently as a workaround I use [template deployment](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html), but this is not ideal, because Terraform does not know about the individual resources created by Azure using a deployment template as mentioned in notes. Thanks.
