### ISSUE TITLE
Ability to lock resource from accidental (*Human error* ?) restart/destruction

### ISSUE THREAD

**Issue by dellelce** [hashicorp/terraform#14933]
Enhancement "suggestion".

### Terraform Version

Any version, it would be great if backported to 0.9.1

### Affected Resource(s)

Any resource that can be modified (restarted/changed) and affect service

### Debug Output

Not applicable.

### Panic Output

Panic N/A.

### Expected Behavior

Object is *NOT* destroyed/restarted but an error message "saying resource locked (or custom message saved in state??) says that the resource is locked.

### Actual Behavior

Current behaviour: object is destroyed/changed.

### Steps to Reproduce

1. `terraform apply`

Indeed any "terraform apply" will cause the issue ;)

### Important Factoids

Human error can cause damage a simple "resource production lock" could save plenty of time.

### References

Couldn't find any, hopefully I didn't miss it...

**Comment by tombuildsstuff** [comment]
Hi @dellelce 

Thanks for opening this issue :)

There's a [`prevent_destroy` variable on the `lifestyle` block which will prevent resource deletion](https://www.terraform.io/docs/configuration/resources.html#prevent_destroy), however that won't cover resources being restarted. For example:

```
resource "azurerm_resource_group" "foo" {
  name = "foo"
  location = "bar"

  lifecycle {
    prevent_destroy = true
  }
}
```

Attempting to run `terraform destroy` then fails with the following error message:

```
$ terraform destroy
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

azurerm_resource_group.foo: Refreshing state... (ID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/foo)
Error running plan: 1 error(s) occurred:

* azurerm_resource_group.foo: azurerm_resource_group.foo: the plan would destroy this resource, but it currently has lifecycle.prevent_destroy set to true. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or adjust the scope of the plan using the -target flag.
```

It's also possible to use [the `-parallelism` and `-target` command line arguments](https://www.terraform.io/docs/commands/apply.html) to throttle/target specific operations.

Would you mind checking whether the `prevent_destroy` option would be a good fit for this scenario? :)

Thanks!

**Comment by tombuildsstuff** [comment]
Hey @dellelce 

Have you had a chance to look into this yet?

Thanks!

**Comment by tombuildsstuff** [comment]
Hey @dellelce 

I'm going to close this issue for the moment since we've not heard back - however if this is still an issue please let us know and we'll reopen this and take a look :)

Thanks!
