### ISSUE TITLE
Conditional input variable into module

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#14948]
Is it possible to have an optional variable passed into a module?

For example:

```
variable "aws_vpc_cidr" {
    default = ""
}
```

Module definition:

```
module "google_firewall_base" {
    source = "../../providers/google/firewall"
}
```

Then:

```
resource "google_compute_firewall" "srv_https" {
    name = "srv-https"
    network = "default"

    allow {
        protocol = "tcp"
        ports = ["443"]
    }

    source_ranges = [
        "${var.aws_vpc_cidr}"
    ]

    target_tags = ["web"]
}
```

Currently this is breaking because `source_ranges` cannot be empty. Is there a way to say if empty, skip?

The entire point is I wish to reuse the module but optionally pass in `aws_vpc_cidr`.

**Comment by apparentlymart** [comment]
Hi @nodesocket!

It looks like what's needed here is for the list _itself_ to be empty when the variable isn't set. In that case, the following might do the trick:

```hcl
resource "google_compute_firewall" "srv_https" {
    name = "srv-https"
    network = "default"

    allow {
        protocol = "tcp"
        ports = ["443"]
    }

    source_ranges = "${compact(list(var.aws_vpc_cidr))}"

    target_tags = ["web"]
}
```

The `compact` function takes a list and returns a new list with all of the empty-string elements removed, which should result in `source_ranges` being set to an empty list when the variable value is the empty string.

**Comment by nodesocket** [comment]
@apparentlymart perfect `"${compact(list(...))}"` worked fantastic.
