### ISSUE TITLE
Destroy using the OpenStack provider fails to destroy security groups

### ISSUE THREAD

**Issue by cvvs** [hashicorp/terraform#1494]
It appears that the OpenStack provider attempts to destroy the security groups before the instances are destroyed, which is not allowed by OpenStack, and causes a failure during the destroy.

	* Error deleting OpenStack Neutron Subnet: Expected HTTP response code [202 204] when accessing [DELETE https://region.example.com:9696/v2.0/subnets/da04e0ae-6ec8-4268-b592-b44283f3ca1a], but got 409 instead
	{"NeutronError": {"message": "Unable to complete operation on subnet da04e0ae-6ec8-4268-b592-b44283f3ca1a. One or more ports have an IP allocation from this subnet.", "type": "SubnetInUse", "detail": ""}}

**Comment by jtopjian** [comment]
The instance and security group will be destroyed in the right order as long as you reference the security group in the instance like so:

```
...
security_groups = ["default", "${openstack_compute_secgroup_v2.mysecgroup.name}"]
...
```

The error message indicates that a Neutron subnet is attempting to be deleted... in this case, I don't think there's a "natural" way to define the relationship between the two. Can you try setting an explicit `depends_on` on the security group? That might straighten the order out.

**Comment by cvvs** [comment]
That was it.  I was referencing the security groups by name using a string value, not by interpolation.

This was a layer 8 error.

**Comment by muraliKrishnaBandari** [comment]
openstack_compute_secgroup_v2.mysecgroup.name, what is the meaning of this. Is this default to same kind of erros. I am same kind of problem. could you guys help me in this.

Thanks

**Comment by cvvs** [comment]
Post the relevant configuration.

**Comment by muraliKrishnaBandari** [comment]
heat resource-show list mgmt_subnet
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Property               | Value                                                                                                                                            |
+------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| attributes             | {                                                                                                                                                |
|                        |   "name": "list-mgmt_subnet-amlbakop77nm",                                                                                                       |
|                        |   "enable_dhcp": false,                                                                                                                          |
|                        |   "network_id": "4e201a36-fae3-4206-b22c-471f03237fe3",                                                                                          |
|                        |   "tenant_id": "52291c413b37497d90444af327882d12",                                                                                               |
|                        |   "dns_nameservers": [],                                                                                                                         |
|                        |   "ipv6_ra_mode": null,                                                                                                                          |
|                        |   "allocation_pools": [                                                                                                                          |
|                        |     {                                                                                                                                            |
|                        |       "start": "10.0.0.2",                                                                                                                       |
|                        |       "end": "10.0.0.254"                                                                                                                        |
|                        |     }                                                                                                                                            |
|                        |   ],                                                                                                                                             |
|                        |   "host_routes": [],                                                                                                                             |
|                        |   "ipv6_address_mode": null,                                                                                                                     |
|                        |   "ip_version": 4,                                                                                                                               |
|                        |   "gateway_ip": "10.0.0.1",                                                                                                                      |
|                        |   "cidr": "10.0.0.0/24",                                                                                                                         |
|                        |   "id": "d46e09d0-71e0-411d-a584-6262ded12397",                                                                                                  |
|                        |   "subnetpool_id": null                                                                                                                          |
|                        | }                                                                                                                                                |
| description            |                                                                                                                                                  |
| links                  | http://172.30.76.45:8004/v1/52291c413b37497d90444af327882d12/stacks/list/c39cb6b6-3d49-49f9-9db0-d1b9007861af/resources/mgmt_subnet (self)       |
|                        | http://172.30.76.45:8004/v1/52291c413b37497d90444af327882d12/stacks/list/c39cb6b6-3d49-49f9-9db0-d1b9007861af (stack)                            |
| logical_resource_id    | mgmt_subnet                                                                                                                                      |
| physical_resource_id   | d46e09d0-71e0-411d-a584-6262ded12397                                                                                                             |
| required_by            | newt_pair                                                                                                                                        |
|                        | mgmt_instance                                                                                                                                    |
| resource_name          | mgmt_subnet                                                                                                                                      |
| resource_status        | DELETE_FAILED                                                                                                                                    |
| resource_status_reason | Conflict: Unable to complete operation on subnet d46e09d0-71e0-411d-a584-6262ded12397. One or more ports have an IP allocation from this subnet. |
| resource_type          | OS::Neutron::Subnet                                                                                                                              |
| updated_time           | 2016-06-17T00:52:36Z

**Comment by muraliKrishnaBandari** [comment]
This is the issue. I am using default security group.

  security_groups: ["default"]

**Comment by muraliKrishnaBandari** [comment]
The issue is the heat stack-delete is failed. Could you help me in this issue. i am having hard time to find the issue.

**Comment by cvvs** [comment]
This is a completely different problem and has nothing to do with security groups. Your problem is here:

    One or more ports have an IP allocation from this subnet. 

You have an IP address allocated and you're trying to delete the subnet.

**Comment by jtopjian** [comment]
@muraliKrishnaBandari Is this Terraform-related? Terraform doesn't have support for Heat.

**Comment by muraliKrishnaBandari** [comment]
mgmt_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: '10.0.0.0/24'
      gateway_ip: '10.0.0.1'
      enable_dhcp: False
      network_id: { get_resource: mgmt_net }
mgmt_net:
    type: OS::Neutron::Net
    properties:
      name: { list_join: [ '-', [ { get_param: 'OS::stack_name' }, mgmt-net ]] }
Any suggestion to heat stack to resolve this issue. My mgmt_net and mgmt_subnet are above

**Comment by muraliKrishnaBandari** [comment]
@jtopjian  I am not sure about Terraform openstack.

**Comment by cvvs** [comment]
This has exactly nothing to do with Terraform and is not at all relevant to this bug. I suggest you seek out help from https://bugs.launchpad.net/heat. I will not be responding further.

**Comment by muraliKrishnaBandari** [comment]
Thanks though
