### ISSUE TITLE
File provision throwing error (winRM connection)

### ISSUE THREAD

**Issue by gangadhar01a** [hashicorp/terraform#14953]
I have a terraform template which provision a windows VM and then copy the file from local machine to the provisioned VM using winRM connection, 

"resource "azurerm_virtual_machine" "transfer" {
  name                  = "terraform2"
  location              = "East US"
  resource_group_name   = "nmsu3"
  vm_size               = "Standard_DS1_v2"
  network_interface_ids = ["${azurerm_network_interface.transfernic.id}"]

  storage_os_disk {
    name          = "terraform-osdisk"
    image_uri     = "XX"
    vhd_uri       = "XX"   
    os_type       = "windows"
    create_option = "FromImage"
  }

  os_profile {
    computer_name  = "nmsu6789"
    admin_username = "ganga201"
    admin_password = "XX"
  }

provisioner "file" {
  source      = "/home/parallels/Desktop/puppet.conf"
  destination = "C:/ProgramData/PuppetLabs/puppet/etc/puppet.conf"

  connection {
    type     = "winrm"
    user     = "ganga201"
    password = "XX"
  }
}
}

The VM has been created but terraform unable to execute the "file" provision, it throwing the below error
"Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine.transfer: 1 error(s) occurred:

* unknown error Post http://:5985/wsman: dial tcp :5985: getsockopt: connection refused"

I am assuming terraform will establish a connection to provisioned VM on port 5985 and execute the "file" provisioner.

**Comment by PetrPCZ** [comment]
Hi, do you have listening port on the host? You can also try winrm quickconfig command. It seems that your host is not even accepting the connection.

**Comment by gangadhar01a** [comment]
Hi @PetrPCZ 

I have opened the port using the below azure resource

"resource "azurerm_network_security_rule" "test" {
  name                        = "test123"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "*"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = "nmsu3"
  network_security_group_name = "${azurerm_network_security_group.test.name}"
}  "

I believe the above resource will open the ports required for "winrm" connection, still I am facing the same issue.

"1 error(s) occurred:

* azurerm_virtual_machine.transfer: 1 error(s) occurred:

* unknown error Post http://:5985/wsman: dial tcp :5985: getsockopt: connection refused"


And how I can use winrm quickconfig command within terraform plan without having winrm connection established? Any example will be helpful to proceed further.

Thanks.

**Comment by PetrPCZ** [comment]
Hi, I just meant to run 'winrm quickconfig' in Powershell on your machine. I think your Windows where are you connecting does not even have allowed the service itself. Just my opinion, but you have to first allow it manually.

**Comment by gangadhar01a** [comment]
@PetrPCZ 
Here what I did

step 1:) I have created a custom image using packer in Azure. I have opened ports 5986 and 5985.
step 2;) I used the custom image to provision a VM through terraform, once the VM available I have logged on it and checked the following things

==============================================
**Get-Service winrm**

Output:
Status   Name               DisplayName
------   ----               -----------
Running  winrm              Windows Remote Management (WS-Manag...

==============================================
**winrm qc**
Output:
"WinRM is not set up to allow remote access to this machine for management.
The following changes must be made:
 
Set the WinRM service type to delayed auto start.
Start the WinRM service.
Create a WinRM listener on HTTP://* to accept WS-Man requests to any IP on this
machine.
 
Make these changes [y/n]?"
===============================================
**Netstat -an** 
(this command shows the ports 5986 and 5985 are open to use)

===============================================
**terraform template:**
provisioner "remote-exec" {
   
    connection {
    type     = "winrm"
    user     = "ganga201"
    password = "Ganesha.1234"
    https        = false
    insecure     = true
    }
    
    inline = [
    "puppet agent -t"
    ]
  }

In this scenario, I tried to execute the above command (puppet agent -t)after VM provisioned, this results in following error

Output:
"1 error(s) occurred:

* azurerm_virtual_machine.transfer: 1 error(s) occurred:

* timeout"

This means terraform unable to execute the Powershell command after VM has been provisioned successfully, though the ports are open and winrm service is running (I suspect the "winrm qc" output). I am still learning the way WinRM exactly works, I believe  I need to have a custom image which will have a winrm configuration set-up the way terraform required.

Appreciate if you can help me to configure the Winrm through packer so that I can run required commands after provision using Terraform.

Thanks.

**Comment by PetrPCZ** [comment]
Hello again. 
I am currently in the same situation. I have my custom image of Windows, with allowed WinRM - quickconfig and firewall openings. Unfortunately, we got to the situation, where the service is running (you don't have connection refused anymore, but timeout). I had this problem for few days as well, but because I am also using a bastion as a Jump server I have decided to switch to SSH. I was not able to find a way how to make WinRM working for Terraform (but if you try to deploy with Vagrant and same image I am almost certain that this image (with winrm quickconfig) will work.) Therefore I suspect we are missing something in Terraform, not the image. 

Anyway... 
If you want to fix this problem really fast and don't want to bother with WinRM I do recommend you to install SSHD. [Win32OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH) I currently use this daemon with Win2012 and Terraform and everything is working just fine without any extra hacking. Also the installation is easily scriptable. Good luck.

**Comment by gangadhar01a** [comment]
Hi @PetrPCZ ,

I have fixed the WinRM issue, now I am able to execute the "Powershell" commands through "Terraform". I have noticed that if we provision VM through "Terraform" on "Azure" the ports "5985" and "5986" are not open by default and "WinRM" will be in running status but not configured to accept the connection.

Therefore, I have used packer to open the required ports and configured WinRM using the following script

"winrm quickconfig -q
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
Start-Service WinRM
set-service WinRM -StartupType Automatic
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled false"

and in "Terraform" template I have updated the "winRM" connection with "host" attribute 

"
connection {
type     = "winrm"
    user     = "XXXX"
    password = "XXXX"
    host     = "40.20.30.123"
}
"

**Comment by chris1248** [comment]
Terraform has nothing about this in their sucky documentation
