### ISSUE TITLE
alb_target_group_arn invalid for resource autoscaling_attachment

### ISSUE THREAD

**Issue by igaskin-gpsw** [hashicorp/terraform#14951]
According to the to [documentation](https://www.terraform.io/docs/providers/aws/r/autoscaling_attachment.html) for the _aws_autoscaling_attachment_  resource the "elb" argument is optional, and the argument "alb_target_group_arn" is available.  When running `terraform apply` I get the error that the "elb" arguement is **required** and that the argument "alb_target_group_arn" is invalid.

```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_autoscaling_attachment.default: "elb": required field is not set
  * aws_autoscaling_attachment.default: : invalid or unknown key: alb_target_group_arn
```

### Terraform Version
```
$ terraform --version
Terraform v0.8.8

Your version of Terraform is out of date! The latest version
is 0.9.6. You can update by downloading from www.terraform.io
```

### Affected Resource(s)
- [aws_autoscaling_attachment](https://www.terraform.io/docs/providers/aws/r/autoscaling_attachment.html)

### Terraform Configuration Files

```
# Create a new ALB Target Group attachment
resource "aws_autoscaling_attachment" "default" {
  autoscaling_group_name = "${aws_autoscaling_group.default.id}"
  alb_target_group_arn   = "${aws_alb_target_group.default.arn}"
}
```

### Expected Behavior
Running `terraform apply` should attach the target group to the autoscaling group

### Actual Behavior
Fantastic failure

**Comment by grubernaut** [comment]
Hey @igaskin-gpsw, thanks for the issue! 

It appears you're using Terraform `v0.8.8`, while the `alb_target_group_arn` parameter wasn't added until `v0.9.6`. This change also allowed the `elb` parameter was also changed from `Required` to `Optional`. The commit for these changes is listed [here](https://github.com/hashicorp/terraform/commit/e87b2d30c4bda0c4e3fb5cb9c08521136a71e849).

The docs on the website currently only show the latest released version of Terraform, thus the difference between documentation and the version of Terraform that you're using. We have future plans to have versioned documentation, but until such time documentation can be viewed by checking out the `v0.8.8` tag of Terraform, entering the `website` directory, and running `make website`. 

If you require setting the `alb_target_group_arn` parameter for the Autoscaling Attachment, updating to Terraform `v0.9.6` should do the trick. Please let us know if you have any further questions or concerns. Thanks again!
