### ISSUE TITLE
Can't update mysql_instance engine_version

### ISSUE THREAD

**Issue by Techbrunch** [hashicorp/terraform#14965]
### Terraform Version

- 0.9.5

### Affected Resource(s)

- aws_db_instance

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "mysql_instance" {
  allocated_storage         = 10
  storage_type              = "standard"
  engine                    = "mysql"
  engine_version            = "5.6.35
  [...]
}
```

### Debug Output

```
~ module.mysql_rds.aws_db_instance.mysql_instance
    engine_version: "5.6.19a" => "5.6.35"
Plan: 0 to add, 1 to change, 0 to destroy.

module.mysql_rds.aws_db_instance.mysql_instance: Modifying... (ID: acc-database)
  engine_version: "5.6.19a" => "5.6.35"
module.mysql_rds.aws_db_instance.mysql_instance: Still modifying... (ID: acc-database, 10s elapsed)
module.mysql_rds.aws_db_instance.mysql_instance: Still modifying... (ID: acc-database, 20s elapsed)
module.mysql_rds.aws_db_instance.mysql_instance: Still modifying... (ID: acc-database, 30s elapsed)
module.mysql_rds.aws_db_instance.mysql_instance: Modifications complete (ID: acc-database)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Expected Behavior

The engine version should be updated.

### Actual Behavior

Nothing is updated and doing a new plan will detect the change again.

### Steps to Reproduce

1. Create an `aws_db_instance`
2. Change the `engine_version`

### References

Could be related to even though in my case there is no error.

- GH-14531

**Comment by catsby** [comment]
Hello there – are you using `apply_immediately` in your configuration? 

- https://www.terraform.io/docs/providers/aws/r/db_instance.html

Does anything show in the web console that suggests a change will be applied next maintenance window?

**Comment by Techbrunch** [comment]
@catsby This was indeed the issue, maybe terraform could display a warning when there is a pending maintenance using `describe-pending-maintenance-actions` ?

**Comment by majormoses** [comment]
Ya I have run into this before as well, definitely would be helpful to give a bit more info when there are pending changes.
