### ISSUE TITLE
allow fetching domain_name from aws_route53_zone

### ISSUE THREAD

**Issue by xenoterracide** [hashicorp/terraform#14977]
```
data "aws_route53_zone" "AwsZone" {
  name = "z.xenoterracide.com."
}
```

name ends in a dot, but if you want to use this with cloudfront

```
resource "aws_cloudfront_distribution" "Nexus" {
  origin {
    origin_id = "nexus"
    domain_name = "x.${data.aws_route53_zone.AwsZone.name}"
    custom_origin_config {
      http_port = 8081,
      https_port = 443,
      origin_protocol_policy = "http-only"
      origin_ssl_protocols = [
        "TLSv1.2"]
    }
  }
```

you'd get an error

```

* aws_cloudfront_distribution.Nexus: 1 error(s) occurred:

* aws_cloudfront_distribution.Nexus: InvalidArgument: The parameter origin name must be a domain name.
	status code: 400, request id: b0b9274b-4658-11e7-8b01-0768c67e3d06
```

suggesting that you add the ability to request a `.domain_name` from the zone that trims the trailing `.`

**Comment by akumria** [comment]
I wonder if PR https://github.com/hashicorp/terraform/pull/8517 addresses the problem?

I find it out that the zone name ends with a period ('.') though.

**Comment by xenoterracide** [comment]
it probably would, though I'm unsure if it's safe to remove the trailing . when interacting with route53, but maybe it works. I do know removing the trailing dot  on a read back would fix my problem.

**Comment by bflad** [comment]
Less than ideal, but I have worked around this via: `replace(data.aws_route53_zone.EXAMPLE.name, "/\\.$$/", "")`
