### ISSUE TITLE
terraform get creates absolute target symlinks to disk based modules

### ISSUE THREAD

**Issue by silvermy** [hashicorp/terraform#14974]
### Terraform Version
0.9.6

### Desired Behavior
terraform get should create relatives target symlinks in the .terraform file (where possible) - this will make the terraform directory with embedded .terraform cache portable.

### Steps to Reproduce
1. `terraform get`

**Comment by bcg62** [comment]
without this it is painful for using terraform inside vagrant/docker. If i mount/share my project the symlinks are absolute to my host machine and mean nothing inside my test environment.

**Comment by bcg62** [comment]
#9639

**Comment by nick4fake** [comment]
This is also an issue with virtualbox shared folders for docker machine

**Comment by mauricios** [comment]
I'm facing this issue with the terraform docker image, when mounting volumes inside the Docker container the symlinked modules are not found.

**Comment by apparentlymart** [comment]
In the next major version we plan to not create these symlinks at all and instead refer directly to the module's path relative to its caller. This is changing as part of a general effort to make the module paths more intelligible so that it's easier to understand what's going on when they appear in error messages, but I'm glad to hear that this change will be helpful for other reasons too.

**Comment by mortalius** [comment]
@nick4fake for virtualbox and shared folders on windows this could be workarounded by fixing vbox param, see https://serverfault.com/questions/345341/cant-create-symlinks-in-virtualbox-shared-folders/367839#367839
and then starting Virtualbox as Administrator

**Comment by shaiguitar** [comment]
:+1: for a fix for this (relative paths)

**Comment by apparentlymart** [comment]
The change I mentioned above is merged into the master branch now and was included in the v0.12-alpha1 release. It will also be included in the forthcoming final release. Thanks all!
