### ISSUE TITLE
Terraform destroy openstack resources crash

### ISSUE THREAD

**Issue by wjun** [hashicorp/terraform#14979]
### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
openstack resources

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

```

### Debug Output
The corresponding cluster.tfstate file is available at: https://gist.github.com/wjun/e2b106d13d458f1dc3bbf1743dc88239

### Panic Output
crash.log is available at: https://gist.github.com/wjun/82d8c17376d1fe95cbf83c1da83dce60

### Expected Behavior
All openstack resources are deleted

### Actual Behavior
Terraform delete crashes

**Comment by jtopjian** [comment]
@wjun Thanks for reporting this. It looks like you're running into a known issue.

In the `network` block of your `openstack_compute_instance_v2` resource(s), can you try using _both_ the `name` and `uuid` of the network? That's the known workaround at this time. Let me know if that helps.

**Comment by wjun** [comment]
@jtopjian Thanks for the information. Do you know if the known issue is always reproducible or occasional? In our cases, only in certain environments, we will meet terraform crash issue, and in some environments, terrafrom destroy work well.

**Comment by jtopjian** [comment]
@wjun The workaround is safe to do no matter the environment. The issue happens in environments that do not support the `os-tenant-networks` Nova API call. You can verify this by running:

```shell
$ nova tenant-network-list
```

If you get an error or some type of bad output, then you'll most likely see the issue you've reported.

**Comment by wjun** [comment]
@jtopjian the nova command above runs correctly in the terraform crash environment, is there an issue id for that known issue so I can get more details? Thanks.

**Comment by jtopjian** [comment]
That's interesting...

Yes, there are two issues to look at:

* https://github.com/hashicorp/terraform/issues/5293 is the long-running issue that has documented that `os-tenant-networks` needs to go away at some point.
* https://github.com/hashicorp/terraform/issues/14574 is a recent change that was made to account for bad responses from `os-tenant-networks`. I would be curious to know if you see this same issue in Terraform 0.9.5 or 0.9.4. If those versions work, then the patch to fix this issue is what is causing your crash.

**Comment by wjun** [comment]
I met this crash issue in an older version first and then I upgraded terraform to the latest version but the crash issue still exists. From crash.log, it seems to me the graph construction somehow crashes?

**Comment by jtopjian** [comment]
OK, so it's not a regression bug. That's good news.

From the crash log, it looks like this is where the crash is happening:

```
panic: interface conversion: pagination.Page is nil, not tenantnetworks.NetworkPage
```

There are a few `Internal Server Error` messages before that.

Do you have access to the server api logs? Maybe there's a better indication of why the crash happened there.

Another option is to run with `OS_DEBUG=1` set:

```shell
$ TF_LOG=DEBUG OS_DEBUG=1 terraform apply
```

It looks like you're launching a large number of instances, too. Does this still happen if you drop the number down to, say, 5?

**Comment by wjun** [comment]
Thanks @jtopjian After I restart neutron server, the terraform crash went away, though terraform destroy hang there. I will close the issue for now, and reopen if we can reproduce while openstack servers are running correctly.

**Comment by jtopjian** [comment]
@wjun Sounds good. Do let me know if you need any further help. :)
