### ISSUE TITLE
Can't get AWS instance id to associate EIP with.

### ISSUE THREAD

**Issue by fog1985** [hashicorp/terraform#14981]
Hi guys,

I parsed Google and what I found is to get AWS instance_id it is enough to use the construction as follow:
"${aws_instance.test_terraform.id}"

But whenever I try to use it this way I get an error as follow:
* aws_instance.test_terraform: aws_instance.test_terraform: self reference not allowed: "aws_instance.test_terraform.id"

Doesn't matter if I try to save it into a variable or use from resource "aws_eip_association".
Always get this error.

But this way of doing that stuff even described here:
https://www.terraform.io/docs/providers/aws/r/eip_association.html

Can anyone help me please with this and whet I am doing wrong?

Regards,
Taras.

**Comment by stack72** [comment]
Hi @fog1985 

Please can you post your terraform config (minus any secrets) and we can try and help you with what you want to do

Thanks

Paul

**Comment by fog1985** [comment]
Hi @stack72 
I have just reviewed my config and found very simple but not very obvious error. :)
I tried to associate EIP inside of instance creation block.
Just moved it outside and everything works as expected.

Sorry to disturb you.

Regards,
Taras.

**Comment by stack72** [comment]
Nothing to apologise for @fog1985 :)

Glad you got it working

Paul

**Comment by stelang** [comment]
@fog1985 thanks for posting this!
