### ISSUE TITLE
AWS S3 Bucket policy for multiple account not playing well with Cloudtrail. ( InsufficientS3BucketPolicyException)

### ISSUE THREAD

**Issue by p0bailey** [hashicorp/terraform#14989]
Hello there,

I do have 6 AWS accounts and I would like to set a S3 bucket to collect the cloudtrail logs from all of them. For this matter I have created in the account 1 a bucket with a policy to allow cloudtrails from other accounts to push logs into it (see below). And from account 2 to 6 I'm able to create CloudTrails pointing to my bucket in account 1. Until this points everything works as expected, however when I try to create a Trail on the account 1 (the same where I do have the S3 bucket) I get this error back.

"InsufficientS3BucketPolicyException: Incorrect S3 bucket policy is detected for bucket: stack-trail-collector" 

The odd thing is when I run again Terraform the Trail seems to be created as you can see below. This might be a time-out issue whether the trail tries to lookup whether can use that bucket. 

```
 terraform apply 
aws_cloudtrail.AuditingTrail: Refreshing state... (ID: Trail)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

This happens only on the account 1, where I'm running the bucket.

I really  can't get my head around. Any help would be really appreciated.

Phillip

### Terraform Version
Terraform v0.9.6

### Affected Resource(s)

- S3
- Cloudtrail

### Terraform Configuration Files
Code to create the trail

```hcl
resource "aws_cloudtrail" "AuditingTrail" {
  name                                        =  "mainTrail"
  s3_bucket_name                      = "stack-trail-collector"
  include_global_service_events = true
  is_multi_region_trail                  = true
}
```

Code to create the S3 Bucket
```hcl
resource "aws_s3_bucket" "cloudtrailS3" {
    bucket = "${var.cloudtrailS3bucket}"
    region = "${var.cloudtrailS3region}"
    policy = "${file("${path.module}/policy.json")}"
}
```
S3 policy file.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSCloudTrailAclCheck",
            "Effect": "Allow",
            "Principal": {
                "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:GetBucketAcl",
            "Resource": "arn:aws:s3:::stack-trail-collector"
        },
        {
            "Sid": "AWSCloudTrailWrite",
            "Effect": "Allow",
            "Principal": {
                "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": [
                "arn:aws:s3:::stack-trail-collector/AWSLogs/ACCOUNT1/*",
                "arn:aws:s3:::stack-trail-collector/AWSLogs/ACCOUNT2/*",
                "arn:aws:s3:::stack-trail-collector/AWSLogs/ACCOUNT3/*",
                "arn:aws:s3:::stack-trail-collector/AWSLogs/ACCOUNT4/*",
                "arn:aws:s3:::stack-trail-collector/AWSLogs/ACCOUNT5/*",
                "arn:aws:s3:::stack-trail-collector/AWSLogs/ACCOUNT6/*"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        }
    ]
}
```

### Debug Output

```
Error applying plan:

1 error(s) occurred:

* aws_cloudtrail.AuditingTrail: 1 error(s) occurred:

* aws_cloudtrail.AuditingTrail: InsufficientS3BucketPolicyException: Incorrect S3 bucket policy is detected for bucket: stack-trail-collector
	status code: 400, request id: 9acbaa3b-46d0-11e7-949a-7f18c0615b3c

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior

should  create the cloudtrail without " InsufficientS3BucketPolicyException: Incorrect S3 bucket policy is"

**Comment by p0bailey** [comment]
An update on the matter.

Just because I had some doubts whether Terraform was passing the Json policy document incorrectly formatted I copy pasted the bucket policy directly into the AWS UI taking the sample code from the example below and adding the relevant endpoints such bucket name and accounts. 

http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-set-bucket-policy-for-multiple-accounts.html

I'm still getting the same error.

```

terraform apply 
aws_cloudtrail.AuditingTrail: Creating...
  arn:                           "" => "<computed>"
  enable_log_file_validation:    "" => "false"
  enable_logging:                "" => "true"
  home_region:                   "" => "<computed>"
  include_global_service_events: "" => "true"
  is_multi_region_trail:         "" => "true"
  name:                          "" => "Trail"
  s3_bucket_name:                "" => "stack-trail-collector"
Error applying plan:

1 error(s) occurred:

* aws_cloudtrail.AuditingTrail: 1 error(s) occurred:

* aws_cloudtrail.AuditingTrail: InsufficientS3BucketPolicyException: Incorrect S3 bucket policy is detected for bucket: stack-trail-collector
	status code: 400, request id: 109ed259-4771-11e7-b907-c99a2025a5af

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Whenever I do run terraform apply again seems the resource has been already created from the previous run.

```
terraform apply 
aws_cloudtrail.AuditingTrail: Refreshing state... (ID: Trail)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by p0bailey** [comment]
Update.

I recall last year building the same stack with **Cloudformation** and everything worked seamlessly.

**Comment by p0bailey** [comment]
Update, 

whenever i use lower lower case characters `name  =  "maintrail"` the trail gets executed and applied correctly. Whenever I use  camel case as  `name  =  "mainTrail"`  Terraform fails.

**Good!**
```hcl
resource "aws_cloudtrail" "AuditingTrail" {
  name                                        =  "maintrail"
  s3_bucket_name                      = "stack-trail-collector"
  include_global_service_events = true
  is_multi_region_trail                  = true
}
```

**Bad!**
```hcl
resource "aws_cloudtrail" "AuditingTrail" {
  name                                        =  "mainTrail"
  s3_bucket_name                      = "stack-trail-collector"
  include_global_service_events = true
  is_multi_region_trail                  = true
}

**Comment by JoshuaEdwards1991** [comment]
Add this to your cloudtrail resource

depends_on = ["aws_s3_bucket. cloudtrailS3"]

**Comment by mardinyadegar** [comment]
I have the same exact use case as the original poster. This is still an issue. I am doing exactly what is specified by JoshuaEdwards and it does not make a difference. I even tried creating a policy resource and referencing the policy resource instead of the bucket for the `depends_on` makes no difference.

**Comment by mardinyadegar** [comment]
I ended up getting it fixed. For me, the issue was that I did not have a `*` on the end of the arn for the policy. Adding depends_on and referencing the policy worked for me.
