### ISSUE TITLE
resource google_sql_user import fails in 0.9.6 with multiple projects and providers

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#14998]
### Terraform Version

v0.9.6

### Affected Resource(s)

- google_sql_user

### Expected Behavior

`google_sql_user` resource type should support import on specific projects.

### Actual Behavior

When I plan, Terraform correctly shows that it should create the `google_sql_user` resource in the correct project, `foo` (this is a separate project than the one that the service account belongs to, but the service account has access to `foo` as well):

```
+ google_sql_user.mysql
    host:     "cloudsqlproxy~%"
    instance: "mysql-us-central1-m"
    name:     "mysql"
    password: "<sensitive>"
    project:  "foo"
```

When I try to run the corresponding import:

```
terraform import google_sql_user.mysql mysql-us-central1-m/mysql
```

With debug logs, it shows that the API request is actually being made against the main provider project instead of the project that the resource exists in.

Then I noticed `terraform import` has a `-provider` flag. I used this to specify the provider for the corresponding project:

```
terraform import -provider="foo.google_sql.us-central1" \
  google_sql_user.mysql mysql-us-central1-m/mysql
```

This errors with:

```
provider foo.google_sql.us-central1 couldn't be found
```

even though the current working directory contains a file `gcp.tf.json` which contains:

```
   "provider": {
      "google": {
         "alias": "foo.google_sql.us-central1",
         "project": "foo",
         "region": "us-central1"
      }
   },
```

and I have verified that my multi-provider / multi-project configuration has worked to create GCP Projects and resources under the correct projects.

**Comment by danawillow** [comment]
@rileykarson want to take a look at this?

**Comment by rileykarson** [comment]
Hi @devth! 

It looks like the `-provider` flag on `terraform import` expects the argument to have a value of `TYPE.ALIAS`, like the `aws.eu` alias in [their example](https://www.terraform.io/docs/commands/import.html#provider-provider).

Could you try running this command and let me know if it works?

    terraform import -provider="google.foo.google_sql.us-central1" \
      google_sql_user.mysql mysql-us-central1-m/mysql`

**Comment by devth** [comment]
Hi @rileykarson, thanks for the tip. That was indeed the problem. However, after importing the resource, when I run `plan`, Terraform is unable to fetch the state for the imported sql user. It gives the error:

```bash
* google_sql_user.mysql: google_sql_user.mysql: Error reading SQL User "mysql" in instance "foo": googleapi: Error 403: The client is not authorized to make this request., notAuthorized
```

This typically means it's trying to make the request against my top level GCP project that the service account belongs to (as opposed to the `foo` project which was created by that service account). 

Inspecting state seems to confirm this:

```
terraform state list | grep sql_user | xargs -n1 terraform state show

id       = foo/mysql
host     = %
instance = mysql-us-central1-m 
name     = mysql
```

**Comment by rileykarson** [comment]
After importing a google_sql_user with `-provider="google.foo"` and then running `terraform plan` I get the same error when using this config:
```hcl
resource "google_sql_user" "user" {
	name = "tf-user"
	instance = "${google_sql_database_instance.instance.name}"
	host = "google.com"
	password = "hunter2"
}
```
With a provider field added to the resource;

```hcl
resource "google_sql_user" "user" {
	provider = "google.foo"
	name = "tf-user"
	instance = "${google_sql_database_instance.instance.name}"
	host = "google.com"
	password = "hunter2"
}
```

`terraform plan` works as expected. If you don't have one set, could you try adding this provider field to your resource and then running `terraform plan`?
```hcl
	provider = "google.foo"
```
As far as I can tell, `terraform state show` doesn't show project or provider information.

**Comment by devth** [comment]
Same error when specifying the provider.

I've never had to explicitly set the provider for my other resources because the provider is set at the top of the file for every set of resources. I have several `.tf.json` files in my config dir - one for each provider.

**Comment by rileykarson** [comment]
Hi @devth,
I haven't been able to reproduce your issue; resources without a provider field set have the same error as yours, but once I set the `provider` field, they work as expected.

Are you able to make a minimal config to reproduce the error?

**Comment by devth** [comment]
Thanks @rileykarson. I will try to make a repro.
