### ISSUE TITLE
Add Resource create_only feature - Resource.lifecycle.create_only

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#1499]
One of my biggest fears using terraform is accidentally deleting a database or other canonical datastore due to a simple change that causes the resource to get destroyed and recreated.  Would be very helpful to add a key to the resource.lifecycle of create_only, such that terraform will not delete these resources under any condition (or without some extra user interaction or extra confirmation).

```
resource "aws_instance" "my_db" {
    ami = "ami-123456"
    instance_type = "m1.small"
    lifecycle {
        create_only = true #prevent terraform from ever deleting this resource without some extra steps
    }
}

**Comment by radeksimko** [comment]
:+1:

**Comment by knuckolls** [comment]
:+1:

**Comment by phinze** [comment]
Yep totally - this is something we've talked about internally. This is definitely a feature we'll do - probably for 0.5.

**Comment by matthewford** [comment]
:+1:

**Comment by radeksimko** [comment]
Shall we close this now since #1566 has been merged? :)

**Comment by phinze** [comment]
Yep, done with prevent_destroy. :ok_woman:

**Comment by franklinwise** [comment]
Awesome!! @phinze
