### ISSUE TITLE
openstack_networking_secgroup_rule_v2 ignores protcol integers

### ISSUE THREAD

**Issue by craneworks** [hashicorp/terraform#14993]
The module openstack_networking_secgroup_rule_v2 is not working when given an integer as protocol.
The openstack python client is using this because sometimes your openstack is too old for using specific protocol names like vrrp. Instead you are going to enter the protocol id 112 on the cli.
According to the openstack security group rule manpage valid values are 0-255.

```
openstack security group rule create -h
[...]
  --protocol <protocol>
                        IP protocol (ah, dccp, egp, esp, gre, icmp, igmp,
                        ipv6-encap, ipv6-frag, ipv6-icmp, ipv6-nonxt,
                        ipv6-opts, ipv6-route, ospf, pgm, rsvp, sctp, tcp,
                        udp, udplite, vrrp and integer representations
                        [0-255]; default: tcp)
[...]
````

### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
openstack_networking_secgroup_rule_v2

### Terraform Configuration Files
```
provider "openstack" {
}
resource "openstack_networking_secgroup_v2" "vrrp" {
  name        = "vrrp-debug"
  description = "vrrp security group"
  delete_default_rules = "true"
}
resource "openstack_networking_secgroup_rule_v2" "vrrp" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = 112
  security_group_id = "${openstack_networking_secgroup_v2.vrrp.id}"
}
```

### Debug Output
https://gist.github.com/anonymous/37182230b6db58cfb4824981daed1972

### Expected Behavior
I expect to have a rule with a protocol as integer.

```
$ openstack security group show vrrp-debug
[...]
direction='ingress', ethertype='IPv4', id='7b72ccf6-08e2-4360-90d6-f657ac7978e3', protocol='112', remote_ip_prefix='0.0.0.0/0'
[...]
````

### Actual Behavior
Instead I get a rule without a specific protocol

```
$ openstack security group show vrrp-debug
[...]
direction='ingress', ethertype='IPv4', id='e463dc0f-8783-458d-96ee-49297c1a134a'
[...]
````

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jtopjian** [comment]
@craneworks This was just implemented in #14917 and will be available in the next version :)

If you'd like to compile the latest code from source to give any feedback / verify, it'd be very much appreciated!

I'm going to close this issue, though. Let me know if you have any questions.
