### ISSUE TITLE
Upgrade a GKE cluster from single zone to multi zone without recreating it

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#15004]
This is somewhat related to #15002

The `gcloud` CLI [provides a way](https://cloud.google.com/container-engine/docs/clusters/operations#update_a_running_cluster_to_multi_zone) to convert a single-zone cluster to multizone.

In Terraform perhaps adding zones to `additional_zones` could use this API to non-destructively add a zone to the cluster. /cc @danawillow

**Comment by danawillow** [comment]
FYI this was fixed in https://github.com/terraform-providers/terraform-provider-google/pull/152

**Comment by devth** [comment]
@danawillow awesome thanks!
