### ISSUE TITLE
CodePipeline's run_order option needs documentation

### ISSUE THREAD

**Issue by erickt** [hashicorp/terraform#15001]
Hello! I saw that terraform supports CodePipeline's [run_order](https://github.com/hashicorp/terraform/blob/23b41ad7646410fe1d5cdf03854d12cc3eaf467a/builtin/providers/aws/resource_aws_codepipeline.go#L344), but it's not [documented](https://github.com/hashicorp/terraform/blob/23b41ad7646410fe1d5cdf03854d12cc3eaf467a/website/source/docs/providers/aws/r/codepipeline.markdown).

**Comment by tombuildsstuff** [comment]
Hi @erickt 

Thanks for opening this issue :)

I've opened PR #15016 which documents the `action` block - containing the `run_order`

Thanks!
