### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by kshtsk** [hashicorp/terraform#15018]
Terraform 0.9.6 fails randomly with 'Resource not found' when running with OVH OpenStack.
Log excerpt https://gist.github.com/kshtsk/5c932062958e4ed5d54133214006fb2b

**Comment by jtopjian** [comment]
@kshtsk Is the problem resolved if you run `apply` again?

Do you see any further information if you do:

```shell
$ TF_LOG=DEBUG OS_DEBUG=1 terraform apply
```

**Comment by kshtsk** [comment]
The issue hard to reproduce, @jtopjian thanks for the point, OS_DEBUG=1 helps, but still can't post the log. Seems like the issue is that between successful volume creations it is really disappeared on openstack side. That's happens usually under high pressure.
