### ISSUE TITLE
Error when the Resource string contains "${}"

### ISSUE THREAD

**Issue by zhujian0805** [hashicorp/terraform#15011]
Hi there,

### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
Please list the resources as a list, for example:
aws_iam_policy

### Terraform Configuration Files
```
resource "aws_iam_policy" "self-manage-iam" {
    name        = "self-manage-iam"
    path        = "/"
    description = ""
    policy      = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iam:*LoginProfile",
        "iam:*AccessKey*",
        "iam:*SSHPublicKey*"
      ],
      "Resource": "arn:aws-cn:iam::XXXXXXXXXXXX:user/${aws:username}"
    },
    {
      "Effect": "Allow",
      "Action": [
        "iam:ListAttachedUserPolicies",
        "iam:ListGroupsForUser"
      ],
      "Resource": "arn:aws-cn:iam::XXXXXXXXXXXX:user/${aws:username}"
    },
    {
      "Effect": "Allow",
      "Action": [
        "iam:ListAccount*",
        "iam:GetAccountSummary",
        "iam:GetAccountPasswordPolicy",
        "iam:ListUsers"
      ],
      "Resource": "*"
    }
  ]
}
POLICY
}
```

###Problem:
terraform validate
Error loading files Error loading /tmp/11/iamp.tf: Error reading config for aws_iam_policy[self-manage-iam]: parse error at 11:59: expected "}" but found ":"

**Comment by tombuildsstuff** [comment]
Hi @zhujian0805 

Thanks for opening this issue :)

We use the syntax `${variable}` in Terraform to determine which variables need to be interpolated - as such to use this as a literal string you'll need to escape this with a double $ - there's more details in [this document](https://www.terraform.io/docs/configuration/interpolation.html)

As such - if you change this to the following line(s):
```
"Resource": "arn:aws-cn:iam::XXXXXXXXXXXX:user/${aws:username}"
```

to:
```
"Resource": "arn:aws-cn:iam::XXXXXXXXXXXX:user/$${aws:username}"
```

this won't attempt to interpolate the string and should work as expected - would you be able to confirm if this solves the issue? :)

Thanks!

**Comment by zhujian0805** [comment]
This is working as expected. Thanks a lot for the reply.
