### ISSUE TITLE
Add cpu_platform to google_compute_instance resource 

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#15038]
Google Compute Engine just released ([blog post](https://cloudplatform.googleblog.com/2017/05/Compute-Engine-updates-bring-Skylake-GA-Extended-Memory-and-more-VM-flexibility.html), [technical doc](https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform)) a new feature which allows you specify the cpu platform when creating VM instances. This allow you to provision the newest Skylake cpus.

Therefore I suggest adding a new string option to the `google_compute_instance` resource called `cpu_platform`.

**Comment by rileykarson** [comment]
Linking to the general alpha/beta issue: #14742.
