### ISSUE TITLE
Support for route53 private hosted zones

### ISSUE THREAD

**Issue by gposton** [hashicorp/terraform#1503]
When creating a new hosted zone using 'aws_route53_zone'
I would like to expose the boolean value for making a zone private 
so that I can create 'internal' DNS records.  

This is useful for backend services that aren't publicly exposed.

http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-creating.html
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html

**Comment by johnrengelman** [comment]
I've got a branch we're I'm starting to add some support for this, I'll have a PR up today for some discussion.

It's actually a bit more complex then exposing the boolean, because you have to associate the hosted zone to a VPC in order to create a private one. Additionally, you can associate/disassociate multiple VPCs.

**Comment by Rigdon** [comment]
:+1:  Yes please.

**Comment by dpetzold** [comment]
:+1:

**Comment by pcraciunoiu** [comment]
:+1:

**Comment by maguec** [comment]
:+1:

**Comment by anthonymetzler** [comment]
![Image of Ben Stiller](http://i.imgur.com/tJdvMfN.jpg)

**Comment by mqarty** [comment]
:+1:

**Comment by jmerson** [comment]
Please please please.

**Comment by RowleyCC** [comment]
![image](https://cloud.githubusercontent.com/assets/10815152/7211510/4cc0dd66-e510-11e4-9722-f5f1a0d8d121.png)

**Comment by sheats** [comment]
:+1:

**Comment by andreijs** [comment]
:+1:

**Comment by mzupan** [comment]
:+1:

**Comment by patbos** [comment]
:+1:

**Comment by jedi4ever** [comment]
:+1:

**Comment by Seraf** [comment]
:+1:

**Comment by brockoffdev** [comment]
:+1:

**Comment by michaelgrosser** [comment]
:+1:

**Comment by catsby** [comment]
This was added in #1526, which I just merged.
