### ISSUE TITLE
Error output missing newline

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#15031]
TF version 0.9.6.

This is a complex deployment, so it's unlikely that I'll be able to put together a simple TF file for reproduction.

I'm running a plan with some variables missing:

    $ terraform plan

    1 error(s) occurred:

    * module root:
      module bar.root: module instances: required variable "vpc_id" not setmodule baz.root: module baz-instance: required variable "vpc_id" not set

The above isn't a bad paste - the two errors were output exactly like that.

Expected:

    module bar.root: module instances: required variable "vpc_id" not set
    module baz.root: module baz-instance: required variable "vpc_id" not set

**Comment by apparentlymart** [comment]
Hi @pikeas! Sorry for the long silence here.

The error message rendering has been entirely reworked in master for inclusion in the forthcoming Terraform v0.12.0 release, so the particular message you saw here is now a multi-line message with a source code snippet. That'll indirectly repair the rendering problem you reported here, so I'm going to close this out.

Thanks for reporting this, and sorry again for the late response.
