### ISSUE TITLE
Getting Information from Deployed Server

### ISSUE THREAD

**Issue by knpwrs** [hashicorp/terraform#15044]
What is the most effective way to get information from a deployed server to use in Terraform? For instance, right now in order to get Docker Swarm join tokens I'm doing the following:

```tf
data "external" "swarm_join_token" {
  program = ["./get-join-tokens.sh"]
  query = {
    host = "${digitalocean_droplet.docker_swarm_manager.ipv4_address}"
  }
}
```

`get-join-tokens.sh` contains the following:

```sh
#!/usr/bin/env bash

# Exit if any of the intermediate steps fail
set -e

# Extract input variables
eval "$(jq -r '@sh "HOST=\(.host)"')"

# Get worker join token
WORKER=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$HOST docker swarm join-token worker -q)
MANAGER=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$HOST docker swarm join-token manager -q)

# Pass back a JSON object
jq -n --arg worker $WORKER --arg manager $MANAGER '{"worker":$worker,"manager":$manager}'
```

And then later to use the tokens:

```tf
  provisioner "remote-exec" {
    inline = [
      "docker swarm join --token ${data.external.swarm_join_token.result.worker} ${digitalocean_droplet.docker_swarm_manager.ipv4_address_private}:2377"
    ]
  }
```

This works but it feels janky. The ssh key needs to be added to the system agent in order for this to work where as the `remote_exec` provisioner appears to be able to just access the machine. Is there a better way to go about getting the tokens?

**Comment by stack72** [comment]
Hi @knpwrs 

Apologies for not getting back to you sooner - as you can see, we have a *lot* of traffic on this issue list. As much as possible, we try to keep the issue list for bugs and feature requests only. I would suggest that the best place to help with something like this would be in one of our community channels

https://www.terraform.io/community.html

Thanks

Paul

**Comment by mkingbe** [comment]
@knpwrs did you manage to find a better way as I have same issue, i receive a ssh connection error?
