### ISSUE TITLE
Provide better default scheduling behaviour for Google Cloud preemptible instances in Instance Templates

### ISSUE THREAD

**Issue by danielcompton** [hashicorp/terraform#15055]
### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance_template

### Terraform Configuration Files
```hcl
resource "google_compute_instance_template" "instance_template" {
  name_prefix = "my-dev-template-"
  description = "template description"

  tags = ["dev"]

  instance_description = "desc "
  machine_type         = "n1-standard-1"
  can_ip_forward       = false

  scheduling {
    preemptible       = true
  }

  // Create a new boot disk from an image
  disk {
    source_image = "debian-cloud/debian-8"
    auto_delete  = true
    boot         = true
  }

  network_interface {
    network = "default"
  }

  service_account {
    scopes = ["sql-admin", "servicecontrol", "service-management", "logging-write", "monitoring-write", "trace-append", "devstorage-rw"]
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Log output
https://gist.github.com/danielcompton/6f29b9ae9e0507be2a1c81849a234591

### Expected Behavior
The instance template using a preemptible VM should have been created.

### Actual Behavior
I got an error 

```
Error 400: Invalid value for field 'resource.properties.scheduling.preemptible': 'true'. Scheduling must have preemptible be false when AutomaticRestart is true., invalid
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This is happening because `scheduling.automatic_restart` defaults to true, which is useful and matches the behaviour for standard instances, but isn't a valid option for preemptible instances. This may also apply to standard compute instances, but I haven't checked.

A few possible options I can see would be to remove the automatic_restart default entirely and let it be computed, use DefaultFunc, or maybe something else.

I also noticed that the base `automatic_restart` value causes resources to be deleted and then recreated if you have specified `scheduling.automatic_restart`, as it defaults to true, which is then treated as a change to the resource. Providing an explicit false for both of them works, but then you get warnings about using a deprecated attribute.

**Comment by danawillow** [comment]
Wait, I'm a bit confused about the issue here. Why can't you just set 'false' on `scheduling.automatic_restart`?

**Comment by danielcompton** [comment]
Yep, setting `scheduling.automatic_restart` false is the workaround here. What I'm saying is that the default behaviour for preemptible instances is broken, as `scheduling.automatic_restart` defaults to an invalid setting.

I can see two possible fixes for this:

1. Add a snippet of documentation to https://www.terraform.io/docs/providers/google/r/compute_instance_template.html#preemptible stating that you need to also set `scheduling.automatic_restart` to false.
2. Update the code so that the default value for `scheduling.automatic_restart` is true unless the instance is preemptible, and then make the default value false.

***

My second note "I also noticed that the base ..." is a separate issue that I'll bring up in another issue. I can see how it was confusing here.

**Comment by danawillow** [comment]
Ah, that makes sense. There isn't a way in Terraform to have a schema default rely on the value of a different property, but I think setting computed to true and just using the server-provided default seems reasonable (we'd have to be careful about not breaking existing configs though)
