### ISSUE TITLE
Provide an optional default value to the 'lookup' function.

### ISSUE THREAD

**Issue by gposton** [hashicorp/terraform#1505]
A user can provide an optional default value to the lookup function so that when the key is not found in the mapping, the default value is used.

For example, given the following mapping:

    subnet_index = {
      "prod" = "10"
    }

and the following resource:

    resource "aws_subnet" "main-private" {
      vpc_id = "${aws_vpc.main.id}"
      availability_zone = "${lookup(var.availability_zones, count.index)}"
      cidr_block = "10.0.${count.index+lookup(var.subnet_index, var.environment, "50")}.0/24"
      count = 3
      tags {
        Name = "wyoming-private"
      }
    }

when the environment is 'prod', the IP ranges created will be:
- 10.0.10.0/24
- 10.0.11.0/24
- 10.0.12.0/24

and for all other environments the IP ranges created will be:
- 10.0.50.0/24
- 10.0.51.0/24
- 10.0.52.0/24

In my particular use case we have some long lived environments (dev, test, stage, and prod), but we also want to support dev's having the ability to use the same templates to buildout 'on demand' environments in their own AWS accounts.

I can imagine that this request would facilitate a lot of other use cases as well.

**Comment by phinze** [comment]
This is a good suggestion! Rolling this in with #2312. It's a bit newer but I think it accomplishes the same goal as this suggestion with a slightly different approach that's more likely to be the one we take in the final implementation.
