### ISSUE TITLE
Filtering aws_acm_certificate by type

### ISSUE THREAD

**Issue by vntarasov** [hashicorp/terraform#15063]
In case there are multiple acm certificates with the same domain name, it must be possible to configure 
which one to use by specifying required certificate type.

### Terraform Version
v0.9.6

### Affected Resource(s)
- aws_acm_certificate

### Desired Terraform Configuration
```hcl
data "aws_acm_certificate" "test" {
  domain = "test.com"
  types = ["IMPORTED"]
}
```

### Expected Behavior
Developer specifies an array of types in the datasource, and terraform only considers certificates that match.

### Actual Behavior
Terraform returns a "multiple certificates for domain <domain> found" error.

### Steps to Reproduce
1. Have two certificates in acm for the same domain name, one imported and one issued by acm.
2. `terraform plan`

### Related issues
- GH-12650 - in case there are multiple certificates with the same domain name...
- GH-12111 - more than one cert present with equal domain names...

**Comment by catsby** [comment]
Implemented in #15063
