### ISSUE TITLE
DNSMadeEasy SRV Records Fail with 400 Error

### ISSUE THREAD

**Issue by delianides** [hashicorp/terraform#1506]
Trying to automate an etcd cluster with DNS Discovery so terraform creates each individual EC2 instances and then maps an A name record to DME followed by the SRV record. But when terraform tries to create the SRV record, I get the following error on Terraform 0.4.2:

```
dme_record.etcd1_srv: Creating...
2015/04/13 10:55:13 [DEBUG] apply: dme_record.etcd1_srv: executing Apply
  domainid: "" => "1729181"
  name:     "" => "_etcd-server._tcp"
  port:     "" => "2380"
  priority: "" => "10"
2015/04/13 10:55:13 terraform-provider-dme: 2015/04/13 10:55:13 [INFO] Creating record for domainid: 1729181
2015/04/13 10:55:13 terraform-provider-dme: 2015/04/13 10:55:13 [DEBUG] record create configuration: map[string]interface {}{"name":"_etcd-server._tcp", "type":"SRV", "ttl":300, "value":"ip-172-16-210-173", "priority":10, "weight":20, "port":2380}
  ttl:      "" => "300"
  type:     "" => "SRV"
  value:    "" => "ip-172-16-210-173"
  weight:   "" => "20"
2015/04/13 10:55:13 [DEBUG] root: eval: *terraform.EvalWriteState
2015/04/13 10:55:13 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2015/04/13 10:55:13 [DEBUG] root: eval: *terraform.EvalIf
2015/04/13 10:55:13 [DEBUG] root: eval: *terraform.EvalWriteDiff
2015/04/13 10:55:13 [DEBUG] root: eval: *terraform.EvalIf
2015/04/13 10:55:13 [DEBUG] root: eval: *terraform.EvalWriteState
2015/04/13 10:55:13 [DEBUG] root: eval: *terraform.EvalApplyPost
2015/04/13 10:55:13 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* Failed to create record: Error creating record: API Error: 400 Bad Request
2015/04/13 10:55:13 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
```

A sample of the .tf file looks like:

```
resource "aws_instance" "etcd0" {
  ami = "${module.coreos.ami_id}"
  instance_type = "t2.micro"
  key_name = "${var.key_name}"
  availability_zone = "us-east-1e"
  subnet_id = "subnet-c6tf0ef"
  user_data = "${file("etcd.yml")}"
  key_name = "key-0412"
  tags {
    Name = "etcd0"
  }
}

resource "dme_record" "etcd0" {
  domainid = "1729181"
  # to map the CoreOS instance hostname into etcd for discovery purposes. 
  name = "ip-${replace(aws_instance.etcd0.private_ip,".","-")}"
  type = "A"
  value = "${aws_instance.etcd0.private_ip}"
  ttl = "300"
}

resource "dme_record" "etcd0srv" {
  depends_on = ["aws_instance.etcd0", "dme_record.etcd0" ]
  domainid = "1729181"
  name = "_etcd-server._tcp"
  type = "SRV"
  priority = 10
  value = "${dme_record.etcd0.name}"
  weight = 20
  port = 2380
  ttl = 1000
}
```

I'm still troubleshooting but wanted to post and see if anyone else had seen this?

**Comment by delianides** [comment]
@soniah

**Comment by soniah** [comment]
Ack.

@delianides I won't get to look at this until the weekend; in the meantime it would help me a bit if you could provide a wireshark dump - I use ```host 208.94.147.116``` for the sandbox; you'd have to find the ip for prod. (From __readme.md__ at https://github.com/soniah/terraform-provider-dme).

**Comment by delianides** [comment]
@soniah I'm not sure what you mean by a wireshark dump. But I did get this working. I had to add `depends_on` to the block for the ec2 instance and the dme A name record. Like the following:

```
resource "dme_record" "etcd2srv" {
  depends_on = ["aws_instance.etcd2","dme_record.etcd2", "dme_record.etcd1srv"]
  domainid = "1729320"
  name = "_etcd-server._tcp"
  type = "SRV"
  value = "${dme_record.etcd2.name}"
  priority = 10
  weight = 20
  port = 2380
  ttl = 300
}
```

The only thing I did differently was to have terraform create each SRV record one at a time. I'm not sure why that would affect the DME API.

**Comment by rlister** [comment]
Same issue here with terraform 0.5.2, except does not work even with populated `depends_on` array. (I'm doing the same thing: etcd2 service discovery with SRV records).

**Comment by soniah** [comment]
Thanks @rlister for reporting this. I've had a death in my family, so I won't be able to look at this for at least a month.

**Comment by delianides** [comment]
@rlister I wrote this to use etcd discovery service. Using it now to bootstrap etcd and kubernetes.

https://github.com/delianides/terraform-provider-etcd

**Comment by rlister** [comment]
@delianides Nice. I'm also looking for sane ways to maintain content in etcd (for example, config files).

**Comment by delianides** [comment]
Getting and setting keys will be next. But discovery was nessesary for right now.

**Comment by catsby** [comment]
Hey Friends – we haven't heard much on this issue for some time, I'm going to assume this is resolved. If you're still hitting this, please re-open this issue. Thanks!
