### ISSUE TITLE
Crash while attmepting to setup aws_default_vpc to get around the having to get aws support to understand what I need them to do. 

### ISSUE THREAD

**Issue by gulfie** [hashicorp/terraform#15065]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

Just getting started, trying to work around the 'aws default vpc' issue, aws support isn't as helpful as would be nice.   I ended up running across a crashing bug. 

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Just downloaded : 
x@desk6:~/tmp_teraform/work/book/vpc.tmp$  date ; terraform -v
Sun Jun  4 23:24:00 PDT 2017
Terraform v0.9.6

### Affected Resource(s)
Please list the resources as a list, for example:

aws_default_vpc

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

x@desk6:~/tmp_teraform/work/book/vpc.tmp$ cat gulfie_crash_1.tf 
provider "aws" { 
	region = "us-east-1"
}
resource "aws_default_vpc" "default" { 
	tags { 
		Name = "Default VPC"
	}
}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/gulfie/18925ca19713e30feaf264ef682ead92

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

https://gist.github.com/gulfie/9beeef329858daa4003ab2efcd9dc65a

### Expected Behavior
What should have happened?

Not crashed?   Accepted a new definition for which default VPC I'd like to get working with things? 

### Actual Behavior
What actually happened?

crashed. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

That's it. 

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

An older aws account I guess, with _not_ the correct default vpc setup. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

None that I am aware of.

**Comment by stack72** [comment]
Hi @gulfie 

Thanks for raising an issue with us here - please can you describe a little more about how your environment is working. It seems to be as though you do not have a default VPC in the region that you are trying to run terraform on

Are you trying to get Terraform to create a new default VPC for you?

Paul

**Comment by gulfie** [comment]
On Mon, Jun 05, 2017 at 02:12:50AM -0700, Paul Stack wrote:
> Hi @gulfie 
> 
> Thanks for raising an issue with us here - please can you describe a little more about how your environment is working. It seems to be as though you do not have a default VPC in the region that you are trying to run terraform on
> 
> Are you trying to get Terraform to create a new default VPC for you?

	That was the hope.  It didn't work out.  Now i'm going through the dance of getting aws support to rebuild / replace the vpc.  

	I was hoping that by ether manually providing a default, or possibly specifying a different one that it would be okay.  I ran out of gumption after the first try. 

	Good luck with it. 
	
-g

**Comment by stack72** [comment]
Hi @gulfie 

Unfortunately, this *does not* create the default VPC - this is currently in our docs

```
The aws_default_vpc behaves differently from normal resources, in that Terraform does not create this resource, but instead "adopts" it into management.
```

Apologies for this. You should not have had a crash - so I have fixed that :)

Paul
