### ISSUE TITLE
Crash while trying to apply config for HPE Oneview

### ISSUE THREAD

**Issue by przemolb** [hashicorp/terraform#15074]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
oneview_icsp_server  (HPE Oneview provider)

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

provider "oneview" {
  ov_username   = "user"
  ov_password   = "pass"
  ov_endpoint   = "https://oneview-test.some.domain/"
  ov_sslverify  = false
  ov_apiversion = 200
}

resource "oneview_server_profile_template" "default" {
  name = "terraform-test-server-profile-template"
  enclosure_group = "EG-LAB"
  server_hardware_type = "BL460c Gen8 2"
}

resource "oneview_server_profile" "default" {
  name = "terraform-test-server-profile"
  hardware_name = "PENUK2HLAB001, bay 9"
  hw_filter = [ "position = 9" ]
  template = "${oneview_server_profile_template.default.name}"
  type = "ServerProfileTemplateV5"
  power_state = "on"
}

resource "oneview_icsp_server" "default" {
  ilo_ip = "x.x.x.x"
  user_name = "some_user"
  password = "some_pass"
  serial_number = "${oneview_server_profile.default.serial_number}"
  build_plans = ["terraform-rhel-7.2-x64-scripted-install"]
}
```

### Debug Output
https://gist.github.com/przemolb/f8510e7590ac1b91ca6f8b124844f942

### Panic Output
https://gist.github.com/przemolb/7debb7b85e2bfd6405c3b1b1e944d0b3

### Expected Behavior
It should create a server in an ICSP.

### Actual Behavior
Terraform crashes

### Steps to Reproduce
1. `terraform apply`

**Comment by stack72** [comment]
Hi @przemolb 

Thanks for opening the issue here - sorry this is causing you some problems. Unfortunately, this is not a provider that we support. This means that you will have to raise an issue on their [issue tracker](https://github.com/HewlettPackard/terraform-provider-oneview) so that they can fix this

Sorry about this

Paul
