### ISSUE TITLE
Interpolation allows non-existent properties to be set on a resource

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#1507]
I was updating some documentation and came across a configuration that didn't seem correct:
https://www.terraform.io/docs/providers/aws/r/route53_zone.html
```
resource "aws_route53_zone" "main" {
  name = "example.com"
}

resource "aws_route53_zone" "dev {
  name = "dev.example.com"
  parent_route53_zone = "${aws_route53_zone.main.zone_id}"
}
```

The `parent_route53_zone` doesn't exist in the schema for the route53_zone resource, but this configuration doesn't throw an error. 

However, if you change the value of the property from an interpolated value to a static value `parent_route53_zone = "test"`, then you will get an error during evaluation of the configuration (which is what should be expected).

**Comment by mitchellh** [comment]
Yeah that is really weird. Tagged.
