### ISSUE TITLE
Add capability to search through providers and data sources in documentation sidebar

### ISSUE THREAD

**Issue by Gufran** [hashicorp/terraform#15076]
Like many other people I use the live documentation as a reference book when writing terraform code. My workflow comprises of so many <kbd>ctrl</kbd>+<kbd>f</kbd> to find my way through the docs. It works and serves the purpose well but it is also mildly inconvenient.  
Would it be possible to add a little text box in the sidebar that can filter through the items? It doesn't have to search through entire documentation, just filtering on current page would be equally helpful.

I would've made this change in a pull request but I am as good with html and css as a 3 years old with crayons.

**Comment by stack72** [comment]
Hi @Gufran 

thanks for opening the issue here - I can assure you that this is being worked on as we speak :) The documentation will get a little bit of love soon:tm:

Keep your eyes peeled for it 

Paul

**Comment by Gufran** [comment]
I'm glad to report that what was promised has been delivered with https://github.com/hashicorp/terraform-website/commit/dcbaf175b20ae87044b0d4c8391b1bf70bd48f4a#diff-f942bbc31968a1f7c069391104b56fcd
I'm sorry I doubted you @stack72
