### ISSUE TITLE
Docs for `aws_kinesis_stream` suggest id and name outputs are the same

### ISSUE THREAD

**Issue by thattommyhall** [hashicorp/terraform#15081]
### Terraform Version
Terraform v0.9.6

### Affected Resource(s)
Docs for `aws_kinesis_stream` 

### Issue 
The docs suggest `name` and `id` outputs are the same but this is not the case, `id` seems to be the ARN whereas `name` is the short name

**Comment by stack72** [comment]
Hi @thattommyhall 

Thanks for spotting this - just opened a PR that will fix this. As soon as it's green, I will push to the docs site

Paul
