### ISSUE TITLE
DNS provider bug. DNS should not fail when record does not exist.

### ISSUE THREAD

**Issue by vmindru** [hashicorp/terraform#15088]
terraform should not fail when the record does not exist, it should create the record instead. 

### Terraform Version

Terraform v0.9.6

### Affected Resource(s)

dns_a_record_set

### Terraform Configuration Files

```
[vmindru@vmutil test]$ cat dns.tf 
provider "dns" {
  update {
    server        = "${ var.dnsmaster }"
    key_name      = "${ var.dnskey }."
    key_algorithm = "hmac-md5"
    key_secret    = "${ var.dnskeysecret }"
  }
}
[vmindru@vmutil test]$ cat dns-zone.tf 
resource "dns_a_record_set" "www" {
  zone = "zone.com."
  name = "test2"
  addresses = [ "127.0.0.1" ]
  ttl = 30
}
[vmindru@vmutil test]$ 
```

### Debug Output

trucnated 

```

dns_a_record_set.www - *terraform.NodeRefreshableManagedResourceInstance
2017/06/05 13:04:43 [DEBUG] dag/walk: added new vertex: "dns_a_record_set.www"
2017/06/05 13:04:43 [DEBUG] dag/walk: walking "dns_a_record_set.www"
2017/06/05 13:04:43 [DEBUG] vertex 'root.dns_a_record_set.www': walking
2017/06/05 13:04:43 [DEBUG] vertex 'root.dns_a_record_set.www': evaluating
2017/06/05 13:04:43 [TRACE] [walkRefresh] Entering eval tree: dns_a_record_set.www
2017/06/05 13:04:43 [DEBUG] root: eval: *terraform.EvalSequence
2017/06/05 13:04:43 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/06/05 13:04:43 [DEBUG] root: eval: *terraform.EvalReadState
2017/06/05 13:04:43 [DEBUG] root: eval: *terraform.EvalRefresh
2017/06/05 13:04:44 [ERROR] root: eval: *terraform.EvalRefresh, err: dns_a_record_set.www: Error querying DNS record: 3
2017/06/05 13:04:44 [ERROR] root: eval: *terraform.EvalSequence, err: dns_a_record_set.www: Error querying DNS record: 3
Error refreshing state: 1 error(s) occurred:
2017/06/05 13:04:44 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/06/05 13:04:44 [DEBUG] plugin: terraform: dns-provider (internal) 2017/06/05 13:04:44 [DEBUG] plugin: waiting for all plugin processes to complete...

* dns_a_record_set.www: 1 error(s) occurred:

* dns_a_record_set.www: dns_a_record_set.www: Error querying DNS record: 3

```

### Expected Behavior

if DNS record does not exist the zone should be created hence it does not exist. 

### Actual Behavior

terraform end's with an error 

### Steps to Reproduce
 `terraform apply`

### Important Factoids

With my limited go understanding, I think the hole problem is that terraform fail's based on the logic: "
fail on any RCode Value except 0" 
This is behaviour is not correct, RCode 3 is a normal error that means that the queried record does not exist. 

http://www.tcpipguide.com/free/t_DNSMessageHeaderandQuestionSectionFormat.htm

**Comment by vmindru** [comment]
bump

**Comment by apparentlymart** [comment]
Hi @vmindru! Thanks for reporting this.

At present the DNS provider is primarily community-driven, which means we rely primarily on interested community members to improve it. We'd be happy to review a change here, but we won't be able to work on this ourselves for the foreseeable future.

Also, it may help to reopen this issue in [the now-separated DNS provider repository](https://github.com/terraform-providers/terraform-provider-dns). Eventually all provider issues will be automatically migrated, but migrating it now may make it more visible to potential contributors.
