### ISSUE TITLE
resource google_sql_database_instance doesn't support import

### ISSUE THREAD

**Issue by devth** [hashicorp/terraform#15087]
### Terraform Version

`0.9.6`

### Affected Resource(s)

- google_sql_database_instance

### Expected Behavior

`google_sql_database_instance` supports import.

### References

- Related issue for google_sql_user https://github.com/hashicorp/terraform/issues/14440

**Comment by paddycarver** [comment]
Hi! Thanks for the enhancement request. Normally, adding import to resources is pretty straightforward. However, in this case, we're blocked blocked on #15201. :(
