### ISSUE TITLE
TERRAFORM CRASH when giving two interrupts

### ISSUE THREAD

**Issue by niravradia** [hashicorp/terraform#15080]
While creating an Autoscaling group, I realized I had mentioned wrong AMI. So I pressed Ctrl+C twice. The the following error was shown on console:

`module.asg.aws_autoscaling_group.backend_service_asg: Still creating... (5m40s elapsed)
^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
stopping apply operation...
^CTwo interrupts received. Exiting immediately. Note that data
loss may have occurred.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x3ea72bc]

goroutine 4022 [running]:
github.com/hashicorp/terraform/command.(*UiHook).PreApply(0xc4204fc820, 0xc42079c500, 0xc420581ae0, 0x0, 0x20, 0xc4207e9ca0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/hook_ui.go:65 +0xac
github.com/hashicorp/terraform/terraform.(*EvalApplyPre).Eval.func1(0x79fc0e0, 0xc4204fc820, 0xc420da9490, 0xc42045ae40, 0xc420581b1c)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_apply.go:118 +0x4f
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).Hook(0xc4207d75e0, 0xc4207e9ca0, 0xc420a25890, 0x2f)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:61 +0x6c
github.com/hashicorp/terraform/terraform.(*EvalApplyPre).Eval(0xc4207e9b40, 0x79fdb60, 0xc4207d75e0, 0x2, 0x2, 0xc420902d18, 0x8)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_apply.go:119 +0xe0
github.com/hashicorp/terraform/terraform.EvalRaw(0x79cac40, 0xc4207e9b40, 0x79fdb60, 0xc4207d75e0, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc4207e9b80, 0x79fdb60, 0xc4207d75e0, 0x2, 0x2, 0xc420902c18, 0x8)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0xc1
github.com/hashicorp/terraform/terraform.EvalRaw(0x79cb580, 0xc4207e9b80, 0x79fdb60, 0xc4207d75e0, 0x2f, 0x0, 0x0, 0x2f)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalOpFilter).Eval(0xc420a25710, 0x79fdb60, 0xc4207d75e0, 0x2, 0x2, 0xc420902c10, 0x8)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_filter_operation.go:37 +0x4c
github.com/hashicorp/terraform/terraform.EvalRaw(0x79cb340, 0xc420a25710, 0x79fdb60, 0xc4207d75e0, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc4207e9a00, 0x79fdb60, 0xc4207d75e0, 0x2, 0x2, 0xc420902b58, 0x8)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0xc1
github.com/hashicorp/terraform/terraform.EvalRaw(0x79cb580, 0xc4207e9a00, 0x79fdb60, 0xc4207d75e0, 0x460d0e0, 0xc420902b50, 0x43746e0, 0xc420902b60)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x175
github.com/hashicorp/terraform/terraform.Eval(0x79cb580, 0xc4207e9a00, 0x79fdb60, 0xc4207d75e0, 0xc4207e9a00, 0x79cb580, 0xc4207e9a00, 0x200000003)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x482b0e0, 0xc4207bf7c0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xd4d
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc42031a620, 0x482b0e0, 0xc4207bf7c0, 0xc4207bfb80)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x392
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0x9ca

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
`
crash.log:
https://gist.github.com/niravradia/414afab6c12eb17c568867a95f1dc579

### Terraform Version
Terraform version: 0.9.4  277bbf65d1141207dbb30485bf124b1dba08f80f

### Expected Behavior
It should have exited normally.

### Actual Behavior
TERRAFORM CRASH

### Steps to Reproduce
`terraform apply`
Press Ctrl+C twice

**Comment by jbardin** [comment]
Hi @niravradia,

Thanks for the report. This crash was fixed by #14088 in a previous release of terraform.
