### ISSUE TITLE
Question about volume tags.

### ISSUE THREAD

**Issue by youssefNM** [hashicorp/terraform#15089]
### Terraform Version
0.9.6

### Question 
is there a way to tag volumes using `volume_tags` with instances that are running in ecs clusters? 
it seems `volume_tags` only works with `aws_instance` resource.
I searched in the docs and couldn't find such thing, it will be useful to have `volume_tags` for `aws_autoscaling_group` resource.

**Comment by stack72** [comment]
Hi @youssefNM 

You can certainly use them for aws_instances that are created individually as part of an ECS cluster but AWS does not support using volume_tagging  in AutoScaling Groups right now

Paul

**Comment by youssefNM** [comment]
thank you for your reply.
