### ISSUE TITLE
aws_api_gateway_method_settings doesn't seem to work

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#15119]
Terraform `0.9.5`

```
resource "aws_api_gateway_method_settings" "s" {
  rest_api_id = "${aws_api_gateway_rest_api.test.id}"
  stage_name  = "${aws_api_gateway_stage.test.stage_name}"
  method_path = "${aws_api_gateway_resource.test.path_part}/${aws_api_gateway_method.test.http_method}"

  settings {
    metrics_enabled = true
    logging_level   = "INFO"
  }
}
```

This configuration doesn't seem to work for me. After terraforming, in the `aws console` under `stage`, I cannot see the settings enabled under the `path`'s `method` type

**Comment by Puneeth-n** [comment]
Closing this issue as it was a configuration problem.

**Comment by dlubom** [comment]
Hello @Puneeth-n, I have the same problem, how You resolve it?

**Comment by Puneeth-n** [comment]
@dlubom I don't remember exactly the anyore but  you need to depend on the deployment first and then also give APIG IAM permissions.

**Comment by Vic-L** [comment]
I changed `method_path` to `*/*` and it works. Probably something to do with the combination of `path_part` and `http_method`. Maybe a slash somewhere.

I will just stick to `*/*` for my use case. Will dig further when I have time.
