### ISSUE TITLE
Perform "consul leave" or shutdown routine when node is destroyed

### ISSUE THREAD

**Issue by rvangundy** [hashicorp/terraform#1511]
On destroying a node running consul, it would be nice if that node could run ```consul leave``` prior to being removed. In my particular case this is to maintain a healthy infrastructure state on Atlas when a node has been deliberately destroyed. In particular I'm deploying to AWS, but I'm sure it applies to other providers.

An approach that would be consistent with Terraform might be to set a "consul=true" parameter on an instance in Terraform. If a consul provider has been configured, this would provide a path for the Terraform routine to pull a consul node out of the pool prior to destroying it.

Of course there might be more complex tasks requiring a more sophisticated "shutdown" routine that might also be referenced by an instance, similar to referencing a "provisioner".

**Comment by Kosta-Github** [comment]
what about introducing the concept of an `unprovisioner` or `cleaner`?

**Comment by mitchellh** [comment]
Thats the plan! We have another issue for this (from many months back) that we haven't yet implemented. Closing as dup. Sorry I can't find the issue but I know 100% its still open since its a major feature we have planned.
