### ISSUE TITLE
Feature Request - DigitalOcean firewall resource

### ISSUE THREAD

**Issue by lfarnell** [hashicorp/terraform#15124]
### Terraform Version
0.9.6

### New Resource
- digitalocean_firewall

### Terraform Sample Configuration Example
```hcl
resource "digitalocean_firewall" "http" {
  name = "firewall-1"

  inbound_rule {
    protocol = "tcp"
    ports = "80"
  }

  outbound_rule {
    protocol = "tcp"
    ports = "80"
  }

  droplet_ids = ["${digitalocean_droplet.web.id}"]
}
```

With the new release of firewalls, it would be awesome to include this in Terraform. These objects contain many levels, so I wasn't sure how to express absolutely everything in a flat structure and was hoping to get a discussion going to flush it out

- [PR Release](https://blog.digitalocean.com/cloud-firewalls-secure-droplets-by-default/)
- [Developer Docs](https://developers.digitalocean.com/documentation/v2/#firewalls)

**Comment by keinohguchi** [comment]
I've created a PR for this feature, to get a ball rolling:

https://github.com/hashicorp/terraform/pull/15142

I've done a couple of firewall testing with my github repo below:

https://github.com/keinohguchi/do-in-action

Here is a deny all sample(open TCP/22, HTTP/80, UDP/53):

https://github.com/keinohguchi/do-in-action/blob/master/firewalls/both/000-deny-all/main.tf

and the allow all (Open everything):

https://github.com/keinohguchi/do-in-action/blob/master/firewalls/both/999-allow-all/main.tf

Cheers!

**Comment by keinohguchi** [comment]
Updated the PR to include the doc, as requested by @stack72.  It would be super cool if I can get review on it!

Cheers,

**Comment by keinohguchi** [comment]
Moved to the new provider structure, as in:

https://github.com/terraform-providers/terraform-provider-digitalocean/pull/1

Love this new strucutre, faster build, especially big win for developers, like us!

Thanks so much, team terraform!

**Comment by stack72** [comment]
@keinohguchi you rock! I was going to look at moving that for you this week :)
