### ISSUE TITLE
RabbitMQ Provider: Types Ignored

### ISSUE THREAD

**Issue by jamescarr** [hashicorp/terraform#15129]
### Terraform Version
`0.9.5`

### Affected Resource(s)
- `rabbitmq_policy`

### Terraform Configuration Files
Note that this requires two plugins to be enabled.

```
rabbitmq-plugins enable --offline rabbitmq_consistent_hash_exchange rabbitmq_sharding
```

```hcl
resource "rabbitmq_policy" "sharded-queue" {
  provider = "rabbitmq.rabbit1"
  name  = "sharded-queue-policy"
  vhost = "${rabbitmq_permissions.guest.vhost}"

  policy {
    pattern  = "^${rabbitmq_queue.sharded-queue.name}$"
    priority = 0
    apply_to = "queues"

    definition {
      shards-per-node = 2
      routing-key = "foo.bar.baz"
    }
  }
}

```

### Expected Behavior
Policy is created.

### Actual Behavior
400 bad request, policy is not created.

### Steps to Reproduce
I have a demo project at https://github.com/jamescarr/rabbitmq-terraform-demo for this, it'll bring a cluster up with the correct plugins enabled. Do a `make plan` and `make apply`. Then uncomment https://github.com/jamescarr/rabbitmq-terraform-demo/blob/master/terraform/auto-sharded-queue.tf#L37-L52 and run `make plan && make apply` again.

### Important Factoids
The underlying API is very strict about expecting an int, however it seems that under the hood terraform is coercing ints to strings.

I actually reproduced the same error by creating the policy via the management console and defining the type as a `string` instead of `int`.

**Comment by jtopjian** [comment]
@jamescarr Is this the same as #10186?

**Comment by jamescarr** [comment]
@jtopjian indeed... I'll close and add more details there. I have some ideas on possible solutions.

**Comment by dmportella** [comment]
Do you mean like this: https://www.terraform.io/docs/providers/aws/r/iam_policy.html

```
resource "aws_iam_policy" "policy" {
  name        = "test_policy"
  path        = "/"
  description = "My test policy"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```
