### ISSUE TITLE
RDS resources with passwords always get destroyed / rebuilt

### ISSUE THREAD

**Issue by slajax** [hashicorp/terraform#15144]
The same issue described in #689 is back in < 0.9.6 - confirmed the same issue in 0.9.3 as well based on the comment at the end of the previous issue.

**Comment by djandruczyk** [comment]
This still happens in 0.9.8
-/+ aws_db_instance.my_special_db_dev (tainted)
    password:                          "<sensitive>" => "<sensitive>" (attribute changed)

**Comment by ricardclau** [comment]
Same problem here! 

Also, maybe unrelated but we are seeing an identifier name change is forcing a new resource. I digged through the issues list and apparently this was sorted out in #6080 but is apparently back

Perhaps the SDK did something nasty lately?
