### ISSUE TITLE
Azure virtual machine interfaces are not being created and attached in the order they are defined within the main.tf script

### ISSUE THREAD

**Issue by kblackstone** [hashicorp/terraform#15153]
### Terraform Version
0.9.6

### Affected Resource(s)
- azurerm_network_interface
- azurerm_virtual_machine

### Terraform Configuration Files
https://www.dropbox.com/s/q4pnvy0bs2812vk/main.tf?dl=0

### Expected Behavior
The interfaces should be consistently created and attached in the following order: management, untrust, trust as defined within the main.tf script.

### Actual Behavior
Terraform plan is showing they will be attached in this order: management, trust, untrust. This is the actual order they get attached in on the virtual machine when launched via terraform apply, which is incorrect. The attachment order is inconsistent. On one run of terraform plan/apply it may create in the right order, on another run of terraform plan/apply it will be in the incorrect order. The first interface is ok due to primary_network_interface_id. I have screen shots of desired.

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

**Comment by pearcec** [comment]
The first step we need to take is to determine if the ordering of the list is getting changed in terraform or in the go-sdk.
