### ISSUE TITLE
provider/google : update vendor Google Cloud API, for support of Labels

### ISSUE THREAD

**Issue by tpoindessous** [hashicorp/terraform#15169]
Hi

in relation with #3546, can you, please, update vendor Google Cloud API ?

the new version adds support for Labels.

I'm working on a new datasource for snapshot, and I would like to begin support for finding Snapshot by providing labels.

Thanks in advance !

Thomas

**Comment by maurofaccenda** [comment]
We also need that

**Comment by ryancurrah** [comment]
Labels would a great addition!

**Comment by tpoindessous** [comment]
I think there is an error in current vendor Google compute-gen.go ( https://github.com/google/google-api-go-client/issues/208 )

Maybe we should wait for this bug to be corrected before updating terraform.

**Comment by tpoindessous** [comment]
It was not a bug, it's a fix for another bug :)

Now, we need to use this function (https://godoc.org/google.golang.org/api/googleapi#Bool) to set Scheduling:AutomaticRestart

The update will break 2 resources 

builtin/providers/google/resource_compute_instance.go:646: cannot use val.(bool) (type bool) as type *bool in assignment
builtin/providers/google/resource_compute_instance.go:984: cannot use val.(bool) (type bool) as type *bool in assignment
builtin/providers/google/resource_compute_instance_template.go:522: cannot use v.(bool) (type bool) as type *bool in assignment
builtin/providers/google/resource_compute_instance_template.go:540: cannot use vp.(bool) (type bool) as type *bool in assignment
builtin/providers/google/resource_compute_instance_template.go:689: cannot use scheduling.AutomaticRestart (type *bool) as type bool in return argument
