### ISSUE TITLE
block_device doesn't allow naming of device 'ex: /dev/vdb', must use deprecated volume block

### ISSUE THREAD

**Issue by josecasillas** [hashicorp/terraform#15171]
### Terraform Version
0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2 (block_device and volume blocks)
- openstack_compute_volume_attach_v2

### Terraform Configuration Files
```hcl
# Prepare volumes for the db servers.
resource "openstack_blockstorage_volume_v2" "volume" {
  name        = "mongo ${count.index + 1}"
  description = "MongoDB Data"
  size        = 2000
  count       = 2
}

# Provision a MongoDB replica set, including 1 arbiter.
resource "openstack_compute_instance_v2" "mongo" {
  name            = "MongoDB Server ${count.index + 1}"
  image_id        = "${var.image_centos_7_2}"
  flavor_id       = "${var.m1_medium}"
  key_pair        = "${var.key_pair}"
  security_groups = ["default"]
  count           = 2

  network {
    name = "${var.network}"
  }

 # This works
  volume {
    volume_id             = "${element(openstack_blockstorage_volume_v2.volume.*.id, count.index)}"
    device                = "/dev/vdb"
  }

  # Bootstrap with common configuration, including formatting and mounting XFS volume at /dev/vdb
  provisioner "remote-exec" {
      ....
  }
}

# Doesn't seem to be working, so using deprecated volume block in resource for now...
resource "openstack_compute_volume_attach_v2" "attached" {
  instance_id = "${element(openstack_compute_instance_v2.mongo.*.id, count.index)}"
  volume_id = "${element(openstack_blockstorage_volume_v2.volume.*.id, count.index)}"
  device    = "/dev/vdb"
}
```

### Expected Behavior
Without the volume block above, I'd expect the volumes to be mounted at /dev/vdb.  I did not see them mounted at all.  Also worried that the provisioner might run before the volume is attached, which would break the build.
Using the block_devices block, I cannot specify the device name, so resorted to the deprecated volume block, which works as expected.

### Steps to Reproduce
1. `terraform apply`

### Requests:
1. Add 'device' or 'device_name' field support to block_devices before removing support for volume block.  
2. Perhaps include example of how to use openstack_compute_volume_attach_v2 with 'count' and how it should behave with respect to resource provisioning blocks.

**Comment by sebastien-prudhomme** [comment]
Hi,

What i use since volume has been deprecated:

```hcl
data "openstack_images_image_v2" "main" {
  name = "${var.instance_image_name}"
}

resource "openstack_compute_instance_v2" "main" {
  count       = "${var.count}"
  flavor_name = "${var.instance_flavor_name}"
  image_id    = "${data.openstack_images_image_v2.main.id}"
  name        = "rancher-${var.name}-${count.index + 1}"

  network {
    port = "${element(openstack_networking_port_v2.main.*.id, count.index)}"
  }

  user_data = "${element(data.template_cloudinit_config.main.*.rendered, count.index)}"

  block_device {
    uuid             = "${data.openstack_images_image_v2.main.id}"
    source_type      = "image"
    destination_type = "local"
    boot_index       = "0"
  }

  block_device {
    uuid             = "${element(openstack_blockstorage_volume_v2.main.*.id, count.index)}"
    source_type      = "volume"
    destination_type = "volume"
    boot_index       = "-1"
  }
```

You need to declare the block device for the image first (will use /dev/vda) then the block device fir your volume (will use /dev/vdb).

I also have to wait for /dev/vdb in my cloud-init script before formatting:

```sh
while [ ! -b /dev/vdb ]; do sleep 1; done
```

**Comment by josecasillas** [comment]
Thank you Sebastien!
Until I added this block:
  block_device {
    uuid             = "${data.openstack_images_image_v2.main.id}"
    source_type      = "image"
    destination_type = "local"
    boot_index       = "0"
  }

I kept getting the error:
* openstack_compute_instance_v2.nomad_workers[2]: 1 error(s) occurred:

* openstack_compute_instance_v2.nomad_workers.2: Error creating OpenStack server: Invalid request due to incorrect syntax or missing required parameters.

Perhaps a better error message can be provided in this case?  It is not intuitive.

**Comment by jtopjian** [comment]
@josecasillas I definitely sympathize with the limitations `block_device`. Unfortunately not being able to specify a device name is inherent to OpenStack itself.

Specifying a device name is possible with the dedicated volume attach resource, but it's very dependent on the underlying OpenStack environment and might not always be the correct device.

With regard to the vague error message, agreed. This is something that can be worked on. One way to get around this for now is to do:

```shell
$ TF_LOG=DEBUG OS_DEBUG=1 terraform apply
```

`OS_DEBUG` will print all traffic between Terraform and the OpenStack cloud, including error messages returned from the server.

**Comment by josecasillas** [comment]
Excellent, thanks!

**Comment by jtopjian** [comment]
@josecasillas no problem at all

@sebastien-prudhomme Also, thank you very much for the helpful pointer. :)
