### ISSUE TITLE
Feature Request: Kubernetes Cluster Role Binding Provider

### ISSUE THREAD

**Issue by micahhausler** [hashicorp/terraform#15194]
When a Kubernetes cluster is created, as of 1.6, there are numerous RBAC `ClusterRole` objects that are bootstrapped in with specific permission sets. When provisioning a new cluster with Terraform, it would be really great to bootstrap a cluster with a terraform defined `ClusterRoleBinding` so I could specify users or ServiceAccounts that I want to have certain permissions. 

I'd be willing to take a cut at this, but I wanted to get the feature request out there first.

**Comment by radeksimko** [comment]
As mentioned in https://github.com/terraform-providers/terraform-provider-kubernetes/pull/1#issuecomment-307940033 there are no plans on supporting alpha/beta resources at this point.

Do you mind closing this issue to prevent going into stale mode and reopening it (or the PR) when it reaches v1?

Thanks.

**Comment by costimuraru** [comment]
RBAC has been moved to v1. What's the plan here?

**Comment by hiranya1** [comment]
Does terraform has Kubernates ClusterRole support?
