### ISSUE TITLE
Feature Request: Port Security support in OpenStack

### ISSUE THREAD

**Issue by jshore1296** [hashicorp/terraform#15197]
Disabling port security is useful for virtual IPs, deploying a devstack environment inside OpenStack and putting floating IPs on nested instances, and other such activities.  I am able to work around this by using allowed address pairs on ports, but that does become more tedious if I want to open up an entire network.

Thanks!

**Comment by jtopjian** [comment]
I've been working on getting this in place for a few months now. It's definitely on the roadmap. :)

**Comment by jshore1296** [comment]
Awesome!  Thanks for the quick update.
