### ISSUE TITLE
Feature Request: Specify count for storage_data_disk

### ISSUE THREAD

**Issue by ripclawffb** [hashicorp/terraform#15202]
This is more of a feature request. It would be nice to have the ability to specify how many data disks a VM can have with a count parameter. For example, you want to use the same module for dev and production, but you need to specify a different number of disks for each environment.

Affected Resource(s)
azurerm_virtual_machine

Expected Behavior
Specify a count for storage_data_disk.

Actual Behavior
An error is given saying count is not a recognized parameter when specified under storage_data_disk.

**Comment by stack72** [comment]
Retagging this as core/enhancement as count is currently only supported on top level resources

**Comment by omame** [comment]
The alternative is to create the `azurerm_managed_disk` resources separately, which supports `count`, but then the problem becomes attaching them to the virtual machine resource: you have two counters of which only one (`count`) is looping.

For example:

```
resource "azurerm_managed_disk" "blah" {
  count             = "${var.storage_disk_count}"
  name              = "${format("datadisk-blah%02d", count.index + 1}"
  storage_account_type = "Premium_LRS"
  create_option     = "Empty"
  disk_size_gb      = "1023"
  location = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
}

resource "azurerm_virtual_machine" "blah" {
  count                         = "${var.vm_count}"
[...]
  storage_os_disk {
    ?
```

Does anyone have a solution to this?

**Comment by codyja** [comment]
I would love to see this too. Data disk isn't required always, but sometimes it is needed.

**Comment by apparentlymart** [comment]
Hi all!

It seems like this is a more specific example of the general idea in #7034, so I'm going to close this to consolidate the discussion over there. We're starting to look at configuration language improvements right now and this is one of the things on our list to try to solve, though we don't have specific details yet since things are still quite early. Will post some more details in that other issue when we have them.

**Comment by SumanGitHub** [comment]
**Multiple disks with multiple VMs:** azurerm_managed_disk  && storage_data_disk 
VM 1 -- > web1-datadisk1,web1-datadisk2
VM 2 - > web2-datadisk1,web2-datadisk2

resource azurerm_managed_disk main-rg__web-datadisk1 {
  count                = "${var.vm_count}"
  name                 = "${var.environment}-web${count.index + 1}-data-1"
  location             = "${var.location}"
  resource_group_name  = "${azurerm_resource_group.main-rg.name}"
  storage_account_type = "StandardSSD_LRS"
  create_option        = "Empty"
  disk_size_gb         = "150"
}

resource azurerm_managed_disk main-rg__web-datadisk2 {
  count                = "${var.vm_count}"
  name                 = "${var.environment}-web${count.index + 1}-data-2"
  location             = "${var.location}"
  resource_group_name  = "${azurerm_resource_group.main-rg.name}"
  storage_account_type = "StandardSSD_LRS"
  create_option        = "Empty"
  disk_size_gb         = "150"
}


resource azurerm_virtual_machine main-rg__web {

storage_data_disk {
    name            = "${element(azurerm_managed_disk.main-rg__web-datadisk1.*.name, count.index)}"
    managed_disk_id =  "${element(azurerm_managed_disk.main-rg__web-datadisk1.*.id, count.index)}" 
    lun             = 0
    create_option   = "Attach"
    disk_size_gb    =  "${element(azurerm_managed_disk.main-rg__web-datadisk1.*.disk_size_gb, count.index)}" 
  }

storage_data_disk {
    name            = "${element(azurerm_managed_disk.main-rg__web-datadisk2.*.name, count.index)}" 
    managed_disk_id =  "${element(azurerm_managed_disk.main-rg__web-datadisk2.*.id, count.index)}" 
    lun             = 1
    create_option   = "Attach"
    disk_size_gb    =  "${element(azurerm_managed_disk.main-rg__web-datadisk2.*.disk_size_gb, count.index)}" 
  }

}
