### ISSUE TITLE
Infinite loop when connecting for provisionning

### ISSUE THREAD

**Issue by mildred** [hashicorp/terraform#15219]
### Terraform Version
0.9.6

### Affected Resource(s)
aws_instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "coreos" {
  count = "${var.size}"
  ...

  lifecycle {
    create_before_destroy = true
    ignore_changes        = ["ami", "user_data"]
  }

  connection {
    user        = "core"
    private_key = "${file("${path.module}/${var.aws_ssh_admin_key_file}")}"
  }

  provisioner "remote-exec" {
    inline = "/home/core/bin/nomad leave"
    when   = "destroy"
  }
}
```

### Actual Behavior

When reducing the number of nodes (size variable) terraform loop and never terminates while outputting the following messages:

```
aws_instance.coreos.3 (remote-exec): Connecting to remote host via SSH...
aws_instance.coreos.3 (remote-exec):   Host:
aws_instance.coreos.3 (remote-exec):   User: core
aws_instance.coreos.3 (remote-exec):   Password: false
aws_instance.coreos.3 (remote-exec):   Private key: true
aws_instance.coreos.3 (remote-exec):   SSH Agent: false
```

**Comment by byrnedo** [comment]
Also getting this in 0.9.7: Infinite loop when destroying instance with a destroy provisioner.

**Comment by byrnedo** [comment]
Confirmed on 0.9.11 as well.

**Comment by byrnedo** [comment]
@mildred Do you use any workaround for this?

**Comment by mildred** [comment]
The workaround was to remove the provisionner and instead script the same actions before running terraform.

**Comment by jarrodjackson** [comment]
I can confirm this on 0.10.0
I added a file provisioner stanza to my terraform config:
```
# Terraform installation dependencies
  provisioner "remote-exec" {
    inline = [
      "sudo apt-get install -y curl",
      "sudo apt-get install -y unzip"
    ]
  }
```
I ran `terraform taint aws_instance.bootstrap` to mark the resource for destruction.
Plan:
```
-/+ aws_instance.bootstrap (tainted) (new resource required)
      ami:                               "ami-db3bdda3" => "ami-db3bdda3"
...
Plan: 1 to add, 0 to change, 1 to destroy.
```

Apply:
```
aws_instance.bootstrap: Provisioning with 'remote-exec'...
aws_instance.bootstrap (remote-exec): Connecting to remote host via SSH...
aws_instance.bootstrap (remote-exec):   Host: 35.166.33.238
aws_instance.bootstrap (remote-exec):   User: root
aws_instance.bootstrap (remote-exec):   Password: false
aws_instance.bootstrap (remote-exec):   Private key: false
aws_instance.bootstrap (remote-exec):   SSH Agent: true
```

**Comment by jarrodjackson** [comment]
In my case, this was caused by not including a connection block on the remote-exec provisioner stanza. Adding it resolved the issue:

```
  # Terraform installation dependencies
  provisioner "remote-exec" {
    inline = [
      "sudo apt-get install -y curl",
      "sudo apt-get install -y unzip"
    ]
    connection {
      user = "ubuntu"
      private_key = "${file("bootstrap")}"
    }
  }
```
Perhaps this is caused by the ssh private key interpolating oddly or missing the connection block altogether?

**Comment by OverlyExcessive** [comment]
I have the same scenario using the Google provider. I'm trying to provision a machine to install Vault and I have set a null resource to detect certificate changes and trigger a reload of the Vault configuration, but it seems that the null resource block remote exec connection is getting stuck in a connection loop. This is my config:

```
resource "google_compute_instance" "vault" {
  name         = "vault-${random_pet.server.id}"
  ...

  connection {
    type        = "ssh"
    user        = "${var.ssh_user}"
    private_key = "${file("${var.ssh_key}")}"
  }

  provisioner "file" {
    source      = "./vault-cfg.hcl"
    destination = "/home/${var.ssh_user}/vault-cfg.hcl"
  }

  provisioner "file" {
    source      = "./certs/"
    destination = "/home/${var.ssh_user}"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo mkdir -p /etc/vault && sudo mkdir /etc/certs",
      "sudo apt-get install unzip",
      "curl -O https://releases.hashicorp.com/vault/0.8.2/vault_0.8.2_linux_amd64.zip",
      "unzip vault_0.8.2_linux_amd64.zip",
      "sudo mv vault /usr/local/bin && sudo mv *.crt /etc/certs && sudo mv *.key /etc/certs && sudo mv *.hcl /etc/vault",
      "sudo setcap cap_ipc_lock=+ep $(readlink -f $(which vault))",
    ]
  }
}

resource "null_resource" "vault-cfg" {
  depends_on = ["google_compute_instance.vault"]

  # If the Vault certs are updated 
  triggers = {
    vault_ca  = "${sha256(file("./certs/vault.crt"))}"
    vault_key = "${sha256(file("./certs/vault.key"))}"
  }

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      user        = "${var.ssh_user}"
      private_key = "${file("${var.ssh_key}")}"
    }

    inline = [
      "pkill -signal SIGHUP vault"
    ]
  }
}
```

**Comment by chrislong** [comment]
I see this behavior with terraform 0.11.10, also with an aws_instance. remote-exec provisioners that run on creation work fine, but one that runs on destroy fails due to empty Host. I worked around it by adding `host` to my `connection` block for the resource (`host = "${self.public_ip}"`).

**Comment by alekc** [comment]
v0.12.18 is affected as well. When connection block is not used, cli reports that it has connected successfully, but then fails to exit even if criteria (inside inline arg) is met. 
Setting explicit connection parameters fixes this behaviour.

**Comment by jbardin** [comment]
Hello,

Since the `host` field is not required to be explicitly set, and provisioners cannot depend on a setting to be supplied from the provider, this empty host issues should not longer he relevant. The connection block for destroy provisioners also cannot reference anything other than the resource itself, which will prevent any graph cycles. 

Any related problems should be filed as new issues. 

Thanks!
