### ISSUE TITLE
GoogleCloud - uppercase location forces bucket recreation

### ISSUE THREAD

**Issue by qgadrian** [hashicorp/terraform#15218]
### Terraform Version
`terraform 0.9.8`

### Affected Resource(s)
- google_storage_bucket

### Terraform Configuration Files
```hcl
resource "google_storage_bucket" "stuff-bucket" {
  name            = "${var.PROJECT_NAME}-stuff-bucket"
  location        = "${var.REGION}"
  storage_class   = "REGIONAL"
}
```

### Debug Output
```
-/+ google_storage_bucket.stuff-bucket
    force_destroy: "false" => "false"
    location:      "EUROPE-WEST1" => "europe-west1" (forces new resource)
    name:          "my-project-stuff-bucket" => "my-project-stuff-bucket"
    self_link:     "https://www.googleapis.com/storage/v1/b/my-project-stuff-bucket" => "<computed>"
    storage_class: "REGIONAL" => "REGIONAL"
    url:           "gs://my-project-stuff-bucket" => "<computed>"
```

### Expected Behavior
Uppercase the location to avoid bucket recreation.

### Actual Behavior
Every `terraform apply` forces new resource.

### Steps to Reproduce
1. `terraform apply`

### References
- Issue #7044 references similar problem in Digital Ocean

**Comment by qgadrian** [comment]
The problem was motivated because reusing project name.

Anyway, workaround this issue can be done with:

```
resource "google_storage_bucket" "my-project-stuff-bucket" {
  name            = "my-project-stuff-bucket"
  location        = "${upper(var.REGION)}"
  storage_class   = "REGIONAL"
}
```

Is still interesting converting always to uppercase in this resource?

**Comment by shilov** [comment]
I've solved this the same way you did but I agree, the current behavior isn't ideal. TF will accept the region regardless of casing but if your value was lowercase then TF will consider it tainted upon next run. Part of the issue here is inconsistent behavior on Google's part, i.e. none of the other resources require the zone to be uppercased.
