### ISSUE TITLE
can not create database using mysql_database resource, dial tcp: missing address

### ISSUE THREAD

**Issue by brunoleite** [hashicorp/terraform#15249]
Hi there,

I am trying to create an RDS instance with MySQL as a provider. I would like to create a different user to access the database. The error that I am getting is:

* module.myapp_rds_module.provider.mysql: dial tcp: missing address

### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_db_instance
- mysql provider
- mysql_user

### Terraform Configuration Files
```hcl
variable "db_root_username" {}
variable "db_root_password" {}
variable "db_dbname" {}
variable "db_username" {}
variable "db_password" {}

resource "aws_db_instance" "myapp_db" {
  allocated_storage      = "5"
  storage_type           = "gp2"
  engine                 = "mysql"
  engine_version         = "5.6.29"
  instance_class         = "db.t2.micro"
  name                   = "${var.db_dbname}"
  username               = "${var.db_root_username}"
  password               = "${var.db_root_password}"
  port                   = "3306"
  multi_az               = false
  publicly_accessible    = true
  skip_final_snapshot    = true
  vpc_security_group_ids = ["${aws_security_group.myapp_security_group_db.id}"]
}

provider "mysql" {
  endpoint = "${aws_db_instance.myapp_db.endpoint}"
  username = "${aws_db_instance.myapp_db.username}"
  password = "${aws_db_instance.myapp_db.password}"
}

resource "mysql_user" "myapp_db_user" {
  user = "${var.db_username}"
  host = "${aws_db_instance.myapp_db.endpoint}"
  password = "${var.db_password}"
}

resource "aws_security_group" "myapp_security_group_db" {
  name = "myapp-security-group-db"

  ingress {
    from_port   = "3306"
    to_port     = "3306"
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output
https://gist.github.com/brunoleite/266ee138bb985a815c33137d8dfdf44d

### Panic Output
None as terraform doesn't crash but stops execution

### Expected Behavior
The database should have been created by the database provider.

### Actual Behavior
Terraform exists with the following error:

```
Error running plan: 1 error(s) occurred:

* module.myapp_rds_module.provider.mysql: dial tcp: missing address
```

### Steps to Reproduce
1. `terraform apply`

### References
I've found those issues:
https://github.com/hashicorp/terraform/issues/8009
https://github.com/hashicorp/terraform/pull/12391

### Note
I've changed some values here and on the log to avoid secret leak.

**Comment by apparentlymart** [comment]
Hi @brunoleite! Sorry this didn't work as expected.

My reply to #8009 applies here too: it's necessary to create your `aws_db_instance` in isolation first, so that Terraform can then know the settings for the `mysql` provider:

```
terraform plan -target="aws_db_instance.myapp_db" -out=tfplan
terraform apply tfplan
terraform plan -out=tfplan
terraform apply tfplan
```

In the longer term we will do something like #4149 to help smooth this, by having Terraform automatically handle these two separate steps. For now though, the above workaround is needed when spinning up a multi-layer stack for the first time. It should not be needed once the stack is already running and is being _updated_ by Terraform.

Since we already have #4149 representing the longer-term change, I'm going to close this just to consolidate discussion over there. Thanks for filing this issue, and again sorry Terraform isn't currently able to handle this situation smoothly.

**Comment by patkar** [comment]
@apparentlymart Should this needed workaround be reflected in the documentation? https://www.terraform.io/docs/providers/mysql/index.html

**Comment by pryorda** [comment]
Yeah, this work around is def not a solution. This should be opened. https://github.com/hashicorp/terraform/issues/4149 has more information around this
