### ISSUE TITLE
core: Early provider discovery causing debug output to show up

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#15245]
This was introduced in https://github.com/hashicorp/terraform/pull/15208, 
https://github.com/hashicorp/terraform/commit/8364383c359a6b738a436d1b7745ccdce178df47 specifically.

We have moved the discovery down to `init()` in `commands.go` and because `init()` runs before `main()` and because the logging configuration happens in `main()` - which is too late - it's causing the following debug output to show up for every command as logs go to stderr by default, e.g.

```
$ terraform version
2017/06/10 11:43:22 [DEBUG] Detected home directory from env var: /Users/radeksimko
Terraform v0.10.0-dev (5ef8341d21e1aaba9135ec41c2e28c985b0c4062)
```

I'm frankly not sure what's the best solution - either we could remove that log message or move around either discovery or logging setup or some parts of it.

**Comment by apparentlymart** [comment]
This was fixed in #15262.
