### ISSUE TITLE
terraform get fails on windows

### ISSUE THREAD

**Issue by johnjelinek** [hashicorp/terraform#1524]
I have a local module. It fails to `get` in Windows (same dir works in OSX).
```
PS Z:\Projects\deploy> terraform get
Get: file://Z:/Projects/deploy/module/aws
Error loading Terraform: Error downloading modules: error downloading module 'file://Z:/Projects/deploy/module/aws': symlink Z:\Projects\deploy\module\aws .terraform\modules\5e3d0c231414c948c2b95083ba05b181: Incorrect function.
```

**Comment by mitchellh** [comment]
I'm guessing this is because of some weirdness with symlinks and Windows. It will take me a bit to get debugging on this since I don't have a WIndows machine readily available, but I've tagged it.

**Comment by johnjelinek** [comment]
Would you like a vagrant box of windows to debug with?

**Comment by mitchellh** [comment]
Heh, yeah that'd help. Since switching computers I lost all my old ones. Feel free to email me directly with it to avoid licensing issues if there are any (assuming its a trial though).

**Comment by johnjelinek** [comment]
Sent

**Comment by Rh1N0** [comment]
Was having same issue on Win8.1 and Win10 Preview. Currently checked it on Windows 10 (build 10049). ```terraform get``` works only if run as Administrator.

**Comment by johnjelinek** [comment]
Oh, for what it's worth, I am running Windows server tech preview.



—

**Comment by Rh1N0** [comment]
@johnjelinek, try to play with security policies. 
Quote from http://ss64.com/nt/mklink.html:
```By default, only Administrators can create symbolic links. The security setting 'Create symbolic links' can be granted at: Configuration\Windows Settings\Security Settings\Local Policies\User Rights Assignment\```

**Comment by johnjelinek** [comment]
I was running terraform from a powershell window ran as administrator.



—

**Comment by Rh1N0** [comment]
Anyhow, issue not in terraform itself, but in mklink and Windows in general =)

**Comment by james-s-nduka** [comment]
Any updates to this?

I am receiving the following;

symlink C:\Users\tgj342\Documents\GitLab_Projects\terraform-vpc-example\elb .terraform\modules\39022fb611f4cd7e0b1760e476e62a8f: A required privilege is not held by the client.

I receive this even whilst running the powershell console as admin.

**Comment by CruzanCaramele** [comment]
I was trying the tutorail on terraform from the road to modern ops and got the same error when i ran "terraform get" as well.


hp (master) rtmo-terraform $ terraform get
Get: file://c:/Users/hp/Desktop/rtmo-terraform/ssh_keys
←[31mError loading Terraform: Error downloading modules: error downloading modul
e 'file://c:/Users/hp/Desktop/rtmo-terraform/ssh_keys': symlink c:\Users\hp\Desk
top\rtmo-terraform\ssh_keys .terraform\modules\8dd2973ab8baa4b37c826862fd07247b:
 A required privilege is not held by the client.←[0m←[0m

**Comment by phinze** [comment]
Hey folks, sorry about the trouble here!

Just ran through `rtmo-terraform` on Windows 8.1 from an Administrator powershell and `terraform get` worked successfully for me.

From the evidence so far, it seems that running an "administrator shell" is insufficient here, the current user actually has to _be_ and administrator or have the symbolic privilege.

Example instructions on how to grang the symbolic linking right to users: https://stackoverflow.com/questions/23217460/how-to-create-soft-symbolic-link-using-java-nio-files

**Comment by phinze** [comment]
Going to be optimistic here and call this closed with the above solution. If anybody still has issues feel free to chime in!

**Comment by vlam-trulia** [comment]
I'm afraid I'm still getting the error in Windows 7 (Professional) SP1, even when I Run as Administrator and/or give my user the "Create Symbolic Links" privilege. The same error happens whether I use Powershell or Git Bash.

```

vlam@XXXXX ~/api/terraform-local (master)
$ terraform get -update
Get: file://c:/Users/vlam/api/terraform_modules/consul_shared (update)
←[31mError loading Terraform: Error downloading modules: error downloading 'file
://c:/Users/vlam/api/terraform_modules/consul_shared': symlink c:\Users
\vlam\api\terraform_modules\consul_shared .terraform\modules\854b3d70f0
4b8d44f5199272bb0bb27c: A required privilege is not held by the client.←[0m←[0m
```
Let me know if there is any additional info I can provide to help debug the issue.

**Comment by CruzanCaramele** [comment]
the way i resolved this on windows 7 is as follows : 
Start > run > regedit >  "HKEY_CURRENT_USER > Software > Microsoft > Windows NT > CurrentVersion > AppCompatFlags > Layers" (If there isn't a Layers folder, you'll have to create one*)

Right click Layers, select New -> String Value. Set the Name of your new String Value to the full path to command prompt. (i.e. "C:\Windows\System32\cmd.exe" without quotes)

Right click the new String Value and click "Modify...". Set the "Value data" to "RUNASADMIN" without quotes.

Now whenever you start command prompt it will be forced to run as Admin with all privilages required and allows you to run terraform-get command successfully

**Comment by eirslett** [comment]
I get this problem when running terraform inside vagrant (linux guest) on a windows host, with the terraform files synced between them.
Isn't it possible to implement terraform's module system without symlinks?

**Comment by chothia** [comment]
I ran into this same issue on Windows 10 with Cygwin Bash on ConEmu. Posting this in case it helps anyone.

As the comments above indicate, it's an issue with Windows needing administrative rights. I simply right clicked my ConEmu tab, clicked "Restart or duplicate" and then "Restart as Admin".

**Comment by rorychatt** [comment]
I am seeing the same issue on my Windows 10 _work_ machine, but not my home one.

```
Error loading Terraform: Error downloading modules: error downloading 'file://C:/Repositories/Terraform/terraform-boilerplate-azure/aus_east_prod/.terraform/modules/0af6a0fe22049190faad742824790295/azure/network/virtual_network': failed to run mklink .terraform\modules\715a5f3508e77d2b96996e5f413b2c78 C:\Repositories\Terraform\terraform-boilerplate-azure\aus_east_prod\.terraform\modules\0af6a0fe22049190faad742824790295\azure\network\virtual_network: exit status 1 "Local NTFS volumes are required to complete the operation.\r\n"
```
Ironically, I can run the above mklink command in the same window and have it work successfully.

```
C:\Repositories\Terraform\terraform-boilerplate-azure\aus_east_prod>mklink .terraform\modules\715a5f3508e77d2b96996e5f413b2c78 C:\Repositories\Terraform\terraform-boilerplate-azure\aus_east_prod\.terraform\modules\0af6a0fe22049190faad742824790295\azure\
symbolic link created for .terraform\modules\715a5f3508e77d2b96996e5f413b2c78 <<===>> C:\Repositories\Terraform\terraform-boilerplate-azure\aus_east_prod\.terraform\modules\0af6a0fe22049190faad742824790295\azure\
```

Smells like the terraform get function isn't honouring the elevated access of the command prompt in Windows.

Might be group policy. Posting incase anybody has encountered similar and above fix not work (not great practice to force cmd prompt through registry key  to always run as admin. That's like running every script as sudo =( ).

Will just run on a Vagrant box as a workaround.
