### ISSUE TITLE
Feature: google_service_account_keys

### ISSUE THREAD

**Issue by mattes** [hashicorp/terraform#15240]
Is someone working on a `resource` that handles keys for service accounts?

https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts.keys

**Comment by michaelahern** [comment]
I've started to work on one -- still need to add docs and tests before submitting a pull req.

https://github.com/michaelahern/terraform/commit/46a6ad551b893b0a1e5722ae5dcdad776009d774

**Comment by mattes** [comment]
@michaelahern did you get a chance to update docs and tests? anything I can help with?

**Comment by mattes** [comment]
@michaelahern is there anything I can help with?
