### ISSUE TITLE
Ability to create multiple stacks using the same root module

### ISSUE THREAD

**Issue by abansal85** [hashicorp/terraform#15269]
Hello guys, 

I am using terraform to spin up docker swarm clusters. We have a requirement where any dev should be able to create their own docker cluster ( for dev environment purposes ). Is there a way in terraform where using the same root module ( we can create multiple docker clusters, keep in mind we can't use "count"). 
Really appreciate the help.

**Comment by cemo** [comment]
I can not get exactly your question but as far as I can understood, you can use a module multiple times as [this](https://www.terraform.io/docs/modules/usage.html#multiple-instances-of-a-module). You can also create a github repository for your module and let others to use it.

**Comment by abansal85** [comment]
lets say we have 3 devs ( devA, devaB, devC) in the team and i have a module like 

module "consul" {
  source  = "modules/docker-swarm"
  servers = 3
}

So when "devA" run "terraform apply" for the above module, it will pass in the value of 3 for servers and run whatever is defined in modules/docker-swarm folder ( lets say it creates 3 virtual machine docker cluster). devA can commit its .tfstate file in repo. Now when devB pull the .tfstate file, and try to run "terraform apply" for the above module NOTHING will happen. Is there a way We can reuse my above code so that devB ..devN  can create ( 3 Virtual machine cluster ) as our devs feel like by passing in some variable or something ?
