### ISSUE TITLE
aws route 53 alias entry cannot be created

### ISSUE THREAD

**Issue by Ferparishuertas** [hashicorp/terraform#15295]
Elb alias not working. can you help me?

resource "aws_route53_record" "pre_backoffice" {
  zone_id = "${var.route53_zone_id}"
  name    = "pre.backoffice.papitopapote.es"
  type    = "A"

  alias {
    name                   = "${module.elb.module_elb_dns_name}"
    zone_id                = "${module.elb.module_elb_zone_id}"
    evaluate_target_health = true
  }
}

1 error(s) occurred:

* aws_route53_record.pre_backoffice: 1 error(s) occurred:

* aws_route53_record.pre_backoffice: [ERR]: Error building changeset: InvalidInput: Invalid XML ; cvc-maxLength-valid: Value 'papito-backoffice-elb-elb-233329122.eu-west-1.elb.amazonaws.com' with length = '63' is not facet-valid with respect to maxLength '32' for type 'ResourceId'.
	status code: 400, request id: 724ce1c9-5164-11e7-b3e9-55ec37340ae4

**Comment by bclodius** [comment]
@Ferparishuertas please ensure that `zone_id = "${module.elb.module_elb_zone_id}"` is actually the zone_id of your elb.  A similar mistake was happening on this issue: https://github.com/hashicorp/terraform/issues/8844

**Comment by Ferparishuertas** [comment]
Thanks. Reviewed and fixed!
