### ISSUE TITLE
No documentation for "element" function

### ISSUE THREAD

**Issue by jtopper** [hashicorp/terraform#1530]
#554 added support for a new "element" function, but this isn't documented on the website.  I think I know how it's used, but I've thus far been unable to describe it with any clarity.  If nobody else picks up this issue in the meantime, I'll come back to this and submit a PR for the docs when it's clearer in my head.

**Comment by jtopper** [comment]
Actually, this is documented on https://terraform.io/docs/configuration/interpolation.html - I was expecting to find this described on https://terraform.io/docs/configuration/resources.html in the section that discusses use of `count`. It perhaps warrants a mention or a link there.

**Comment by phinze** [comment]
Thanks for reporting this!

The website is stored right in this repo so if you like you can [head over to the page in question](https://github.com/hashicorp/terraform/blob/master/website/source/docs/configuration/resources.html.md), click the edit button, and draft up a change. GitHub's improvements of late have made that flow pretty easy.

If you'd prefer we take on the docs though, one of us will pick it up for ya. :+1:

**Comment by phinze** [comment]
The `element()` function is all documented nowadays. :+1:
