### ISSUE TITLE
Incorrect number of resources during plan

### ISSUE THREAD

**Issue by antonbabenko** [hashicorp/terraform#15315]
### Terraform Version
Terraform 0.9.8

### Expected Behavior
`terraform plan` listed 76 resources to add and 1 to destroy, which is correct.

### Actual Behavior
As the last line it showed:
`Plan: 152 to add, 0 to change, 1 to destroy.`

The number of resources has doubled.

### Important Factoids
One resource which should have been destroyed was `random_pet` (not sure if it is related).

**Comment by bclodius** [comment]
@antonbabenko I noticed a similar issue in 0.9.8.  1 resource was being added but it showed 2 consistently.

**Comment by apparentlymart** [comment]
Thanks for reporting this @antonbabenko!

This is the same issue as #14905, which we're aiming to get fixed before the next release. We've done enough digging into it to know that it's just a cosmetic bug though, so while I understand that it is disconcerting it is safe to disregard it and proceed with other Terraform commands.
