### ISSUE TITLE
cidrhost performing incorrect operations in IPv6

### ISSUE THREAD

**Issue by mlosapio** [hashicorp/terraform#15321]
The library which `cidrhost` relies on is performing incorrect operations on IPv6 addresses. 

Example: 

My IPv6 CIDR for the VPC: 
So aws_vpc.ops-dev.ipv6_cidr_block = `2600:1f18:4704:1600::/56`

The code in terraform:

in my subnet:
 `   ipv6_cidr_block         = "${cidrsubnet(aws_vpc.ops-dev.ipv6_cidr_block, 8, 0)}"`

in my aws_instance:
`    ipv6_addresses         = ["${cidrhost(aws_subnet.subnet-1.ipv6_cidr_block, 5)}"]`

This is the computed value terraform attempts to instantiate - which obviously fails because its (way) outside the subnet CIDR.
`    ipv6_addresses.0:                                  "2600:1f1d:4704:1600::"`

This is completely wrong. 

When applying the patch I submitted on the issue in the remote library: 
https://github.com/apparentlymart/go-cidr/issues/4

The correct IP address is specified: 
`    ipv6_addresses.0:                                  "2600:1f18:4704:1600::5"`

This is a pretty high-profile issue as the function is presently completely incompatible with ipv6.

**Comment by apparentlymart** [comment]
Thanks for reporting this, and for submitting that fix to go-cidr, @mlosapio.

#15326 upgrades the vendored copy of the library to get your fix.

**Comment by apparentlymart** [comment]
Looks like I forgot to close this! This was merged and included in 0.10.0-beta1.

Thanks again, @mlosapio!
