### ISSUE TITLE
terraform destroy won't detach policy and delete automatically 

### ISSUE THREAD

**Issue by debu99** [hashicorp/terraform#15336]
aws_iam_role.ecs_host_role: DeleteConflict: Cannot delete entity, must detach all policies first.
	status code: 409, request id: afd9328e-54ff-11e7-8cb3

**Comment by stack72** [comment]
Hi @debu99 

This was solved with https://github.com/terraform-providers/terraform-provider-aws/pull/890 and will be released as part of Terraform 0.10.0 :)

Thanks

Paul
