### ISSUE TITLE
Invalid IAM Instance Profile name

### ISSUE THREAD

**Issue by aleybovich** [hashicorp/terraform#15341]
I have created an instance role and profile as following:

```
resource "aws_iam_role" "code-deploy-ec2-instance-profile" {
    name               = "code-deploy-ec2-instance-profile"
    path               = "/"
    assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}
```
```
resource "aws_iam_policy" "code-deploy-ec2-permissions" {
    name        = "code-deploy-ec2-permissions"
    path        = "/"
    description = "Policy for EC2 instances where Code Deploy would deploy the code"
    policy      = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:Get*",
        "s3:List*"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::nibr-useast1-as-search-code-deploy-dev/*"
      ]
    }
  ]
}
POLICY
}
```
```
resource "aws_iam_role_policy_attachment" "code-deploy-ec2-permissions-policy-attachment" {
    policy_arn = "${aws_iam_policy.code-deploy-ec2-permissions.arn}"
    role      = "${aws_iam_role.code-deploy-ec2-instance-profile.name}"
}
```
```
resource "aws_iam_instance_profile" "search-api-instance-profile" {
  name  = "search-api-instance-profile"
  role = "code-deploy-ec2-instance-profile" # The role is created in infrastructure template
}
```

Now, I add an EC2 instance:
```
resource "aws_instance" "search-api" {
  ... other params ...
  iam_instance_profile   = "${aws_iam_instance_profile.search-api-instance-profile.name}" 
}
```
And I get the floowing error:
```
* aws_instance.search-api.1: InvalidParameterValue: Value (search-api-instance-profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
        status code: 400, request id: XXX
```

Now, if I go check the role `code-deploy-ec2-instance-profile` in teh console, I see that it's Instrance Profile ARN is empty (but if i create an EC2 role via the AWS console it shows a valid ARN). 

Any ideas if it's a bug or am I doing something wrong?

**Comment by aleybovich** [comment]
By the way, I am able to successfully change an existing EC2 instance's IAM Role to search-api-instance-profile manually via AWS console, so it's a valid instance profile. Must be a bug in terraform

**Comment by aleybovich** [comment]
It started working, I must have missed smth originally. Closing as not an issue

**Comment by jsravn** [comment]
This happened to me as well. There seems to be some race condition for newly created profiles. When I wait a short period and rerun the terraform it succeeds.

**Comment by jsravn** [comment]
@aleybovich I think you should reopen this.

**Comment by captainpete** [comment]
seeing same issue, @jsravn thanks for work-around

**Comment by ramkama** [comment]
@aleybovich - I'm facing the same issue. You have to reopen the case as suggested by @jsravn

**Comment by spanktar** [comment]
@aleybovich +1 to reopen as I just hit this as well.

**Comment by aleybovich** [comment]
I'm no longer able to reproduce after I took down my whole envo and rebuilt. You guys need to reopen with your steps to reproduce

**Comment by spanktar** [comment]
This is an intermittent error, where something that relies on IAM later in the cycle (usually immediately) cannot find the IAM resource. This is probably Amazon internal delay in actually making the resource available everywhere although the resource has been successfully created to Terraform.  In my case, a simple re-run of Terraform got me past this. I hit it every now and then and now recognize it so I know what to do.

Suggested remedies: resources that require IAM resources specifically check that they are available before creation? Terraform will have marked them as created, but they may not be ready yet, so maybe a double-check is in order?  This only seems to happen with Instance Profiles.

**Comment by stutefish** [comment]
I get the same behavior - rerun terra and it goes away.

**Comment by realflash** [comment]
I think this is probably #838

**Comment by edmundcraske** [comment]
Just seen this as well.

**Comment by gvirtuoso** [comment]
I get the same behavior, but with Ansible... so I waited for a couple minutes.. run again... and OK! No more issues!... as @spanktar said... I think that is an AWS internal delay!

**Comment by labkey-ians** [comment]
Seeing this too.

**Comment by six0h** [comment]
Also ran into this.

**Comment by milankubin** [comment]
seeing this as well..This also seems to happen apparently on change, not just on create!

```
aws_iam_instance_profile.instance_profile: Destruction complete after 1s
aws_iam_instance_profile.instance_profile: Creating...
  arn:         "" => "<computed>"
  create_date: "" => "<computed>"
  name:        "" => "salome_production_instance_profile"
  path:        "" => "/"
  role:        "" => "salome_production_instance_role"
  roles.#:     "" => "<computed>"
  unique_id:   "" => "<computed>"
aws_iam_instance_profile.instance_profile: Creation complete after 1s (ID: salome_production_instance_profile)
aws_instance.web: Modifying... (ID: i-0a00a20f1d589fc0f)
  iam_instance_profile:              "test_profile" => "salome_production_instance_profile"
  vpc_security_group_ids.#:          "0" => "2"
  vpc_security_group_ids.3440854232: "" => "sg-b559b1df"
  vpc_security_group_ids.745367653:  "" => "sg-1304e479"

Error: Error applying plan:

1 error(s) occurred:

* aws_instance.web: 1 error(s) occurred:

* aws_instance.web: InvalidParameterValue: Value (salome_production_instance_profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
	status code: 400, request id: f67f36f8-a337-421d-bc3d-805e8ccf203a
```

Second run all ok!

**Comment by macropin** [comment]
Seeing this as well. Looks like a race.

**Comment by spanktar** [comment]
@apparentlymart Petition to re-open?

**Comment by kristinepetrosyan** [comment]
Seeing this again with 
Terraform v0.11.1
+ provider.aws v1.6.0

**Comment by milankubin** [comment]
@six0h Are you getting the same error with ansible ? (InvalidParameterValue) 

Quick google found this thread at AWS.  
https://forums.aws.amazon.com/thread.jspa?messageID=593651

According to AWS there is a hardcoded 2min delay for creating instance profiles, yet if you look at my example Terraform is reporting

> aws_iam_instance_profile.instance_profile: Creation complete after 1s

**Comment by LucaFilipozzi** [comment]
Also encountering this bug.

**Comment by tsalisbury** [comment]
Me also.

**Comment by rodrigodiez** [comment]
Me also

**Comment by tiagoantoniovb** [comment]
I've been facing it about two hours and it still does not work...

**Comment by danilogomesbr** [comment]
I've been facing it about two hours and it still does not work...

**Comment by spanktar** [comment]
Here's a horrifying hack I used somewhere else to deal with bad timing issues.  Maybe this would help in this scenario as well, adjust resource types to suit your needs:

```hcl
resource "aws_appautoscaling_policy" "ecs_asp_up_eap" {

  name               = "tweedle"
  resource_id        = "service/beetle"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  step_scaling_policy_configuration {
    adjustment_type         = "ChangeInCapacity"
    cooldown                = 60
    metric_aggregation_type = "Maximum"

    step_adjustment {
      metric_interval_lower_bound = 0
      scaling_adjustment          = 3
    }
  }

  depends_on = ["null_resource.timer"]
}

resource "null_resource" "timer" {

  provisioner "local-exec" {
    command = "sleep 9"
  }

  triggers {
    trigger = "${aws_appautoscaling_target.ecs_asp_target_eap.resource_id}"
  }
}
```

**Comment by enm10k** [comment]
I have the same issue.
In my case, IAM role created by terraform have no instance profile arn and it was the cause of error.

**Comment by Martinsos** [comment]
Just to confirm the suspicion, I am not using terraform but am instead using javascript sdk in nodejs to first create the Instance Profile and then to associate it with the instance, and I get the same problem -> if I try to do association with instance immediately after, it will say Instance Profile does not yet exist. However, if I do it somewhat later, it will work.
Is seems like instance profile is visible in IAM, but is not yet visible in EC2.
Conclusion: this is delay on the AWS side as few people suggested.
Unfortunately I have not found a way to query AWS to find out when association is visible through EC2, so I just repeatedly try to do the association until it does not succeed.

**Comment by bflad** [comment]
Hi folks, as suggested above and noted in the [AWS IAM documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_general.html#troubleshoot_general_eventual-consistency), you are running against the eventual consistency nature of the IAM service.

In [v1.7.1 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#171-january-19-2018) (specifically PR https://github.com/terraform-providers/terraform-provider-aws/pull/3055), we now appropriately retry for up to a minute on this particular condition of associating or re-associating IAM instance profiles with EC2 instances, which should cover the most common scenarios. We will adjust that retry period if necessary based on feedback.

Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading your AWS provider.

PS: If something is still wrong after that upgrade, I would highly suggest opening a new issue in the provider repository: https://github.com/terraform-providers/terraform-provider-aws

**Comment by Arun-Trichy** [comment]
I am facing this issue even in the latest terraform Docker Image, when trying to create instance by attaching it to existing IAM Instance Profile. Even tried hitting thrice, got the same error.

> aws_instance.node.1: Error launching source instance: InvalidParameterValue: Value (kubernetes-aik8s-master) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name

When I try listing the IAM role via AWS CLI, it lists it and also visible via console.

**Comment by mildwonkey** [comment]
Hi all,

New issues with the terraform aws provider should be opened in the [aws provider repository](https://github.com/terraform-providers/terraform-provider-aws).

Because this closed issue is generating notifications for subscribers, I am going to lock it and encourage anyone experiencing issues with the aws provider to open tickets [there](https://github.com/terraform-providers/terraform-provider-aws).

Please continue to open issues here for any other terraform issues you encounter, and thanks!
