### ISSUE TITLE
Map/List support for Consul_Keys

### ISSUE THREAD

**Issue by wv-cfromm** [hashicorp/terraform#15356]
My project is a self-serve build/compile/deploy on immutable servers.  In numerous places, I have a need for complex structures as variables, such as a structure to hold ip/port manifest for binding and security group creation.  Maps/Lists (or nesting both) works fine as cli vars or tfvars, but Consul KV retrieved with data.consul_keys is all String.  This is rough because I need Consul to carry my vars from other apps into TF.

Am I missing something? Is there some way to interpret KV as other than String?

If this needs to be a feature request, I believe there is a number of approaches.  Interpreting Consul KV as other than string is one, such as storing HCL in Consul .  It might be better to enhance the various interpolation functions to support accepting a single string input.  For example, map function only works when supplied key/value, key/value, etc.   However, the map function could accept a single string that includes a map structure. Same goes for List, etc. Or separate function that cast a string into map, list, etc assuming standard map/list/etc syntax.  Or what about accepting HCL/JSON as input?

**Comment by Jamie-BitFlight** [comment]
You can store values to keys as json in consul (even using jsonencode in terraform).
And when you want to read the json from consul, you should be able to use a template to render it to a list or a map.

The variable structure:
https://www.terraform.io/intro/getting-started/variables.html

Details on jsonencoding, splitting, and joining, text into lists and maps.
https://www.terraform.io/docs/configuration/interpolation.html

**Comment by wv-cfromm** [comment]
Thanks.  However, not really a solution.  In a complicated app, using templates to jury rig every value is worse than rough.  data.consul_keys.var should have the same capabilities as -var on CLI.

**Comment by danastasia** [comment]
I am dealing with this right now.  I am trying to store a TF variable map that is a list of AWS Tags.  I can get the JSON into Consul but can't read it back out

**Comment by apparentlymart** [comment]
Hi everyone!

Please note that this issue has moved over to terraform-providers/terraform-provider-consul#15 as part of splitting the Consul provider out into its own repository. Let's keep discussing this request over there, so that the discussion doesn't get lost.

**Comment by samtwilliams-emis** [comment]
> I am dealing with this right now. I am trying to store a TF variable map that is a list of AWS Tags. I can get the JSON into Consul but can't read it back out

Hi did you ever find a solution to this?

**Comment by danastasia** [comment]
No, I was never able to solve this.
