### ISSUE TITLE
support for AWS DynamoDB Accelerator (DAX)

### ISSUE THREAD

**Issue by assaflavie** [hashicorp/terraform#15363]
It's reached general availability: http://www.allthingsdistributed.com/2017/06/amazon-dynamodb-accelerator-dax.html

**Comment by stack72** [comment]
Hi @assaflavie 

This enhancement has been requested here already - https://github.com/terraform-providers/terraform-provider-aws/issues/936

I am going to close this out as a duplicate. Please use the linked issue for all updates :)

Thanks

Paul
