### ISSUE TITLE
Unhelpful error messages with terraform_remote_state

### ISSUE THREAD

**Issue by darrensony** [hashicorp/terraform#15377]
Referencing data.terraform_remote_state.X.Y when there's any issues at all with the remote state always return the error "error loading the remote state: named states not supported"

HTTP 404 -> "named states not supported"

Remote State contains a Remote State Reference that is 404 -> "named states not supported"

This makes it v. hard to diagnose what the real problem is.

### Terraform Version
0.9.8

### Expected Behavior
An error message that tells me what is actually wrong.

### Actual Behavior
"named states not supported"

**Comment by apparentlymart** [comment]
Hi @darrensony! Sorry this error message is so unhelpful.

Would you mind sharing a snippet of your `terraform_remote_state` configuration block, so we can see which backend you're using and how it's configured?

**Comment by darrensony** [comment]
Hi. Using the HTTP backend.

In my local directory:

```
data "terraform_remote_state" "parent_infra_account" {
  backend = "http"
  config = {
    skip_cert_verification = "true"
    address = "https://example.com/hydra/ns/kamaji/tfstate/prod16/@/infra/account"
  }
}
```

The problem seems to be related to following terraform_remote_state resources in that remote state, and parsing the terraform_remote_state resources in there, etc...

For example, the remote state file above has (heavilly edited)

```
{
"version": 3,
"terraform_version": "0.7.0",
"serial": 29,
"modules": [
  {
    "path": [ "root" ],
    "resources": {
        "terraform_remote_state.xref_account_dns_master": {
            "type": "terraform_remote_state",
             "primary": {
                "id": "2016-04-07 21:30:33.331553777 +0000 UTC",
                 "attributes": {
                   "backend": "http",
                    "config.%": "2",
                     "config.address": "https://example.com/hydra/ns/kamaji/tfstate/admin16/@/archetypes/account/dns-master",
                       "config.skip_cert_verification": "true",
                        "id": "2016-04-07 21:30:33.331553777 +0000 UTC"
                   }
             }
      }
  }}}
```

This resource seems to be the cause of the error:

terraform_remote_state.xref_account_dns_master: terraform_remote_state.xref_account_dns_master: error loading the remote state: named states not supported

However, I verified that Terraform is not trying to retrieve the https://example.com/hydra/ns/kamaji/tfstate/admin16/@/archetypes/account/dns-master link; it just seems to be barfing on the resource itself.

**Comment by apparentlymart** [comment]
Thanks for the additional info @darrensony! We'll take a look at this soon.

**Comment by darrensony** [comment]
Verified that it's barfing on tfstate resources named "terraform_remote_state.SOMENAME," which were put in the state file by Terraform 0.6 or early 0.7 versions.

If I (manually) edit the config file to either (A) delete the resource, or (B) add "data." to the start of the key, it works.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. There have been many changes to the underlying code since this was opened. If you are still experiencing an issue with terraform v0.13, please open a new issue and fill out the template.
Thanks!
