### ISSUE TITLE
Environments do not isolate from backend changes

### ISSUE THREAD

**Issue by betabandido** [hashicorp/terraform#15381]
### Terraform Version
Terraform v0.9.8

### Issue description
We are trying to use multiple environments (prod, test, dev) for a given infrastructure. While the production and testing environments should keep their state in S3, there is no need to keep the development environment remotely. So, the idea was to keep the state locally stored.

We use a template solution to auto-generate a `main.tf` file with the proper backend configuration (i.e., remote for prod and test; local for dev).

But, we are running into a series of issues with this approach. Specifically, it seems that backend configuration is not isolated across terraform environments. Is this intended?

The following steps reproduce the issues that we are facing:

1. `terraform env new dev`
2. `terraform env new prod`
3. `terraform env select dev`
4. generate `main.tf` with local backend
5. `terraform init`
6. `terraform apply`
7. `terraform env select prod`
8. generate `main.tf` with remote backend
9. `terraform init`

When attempting to run the last step, terraform detects a backend configuration change and displays the following message:

```
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.


Do you want to copy the state from "s3"?
  Would you like to copy the state from your prior backend "s3" to the
  newly configured "local" backend? If you're reconfiguring the same backend,
  answering "yes" or "no" shouldn't make a difference. Please answer exactly
  "yes" or "no".
```

This message is certainly strange, as the newly configured backend is actually remote and not local as the message suggests.

In any case, the real issue is why environments cannot fully isolate from backend changes.

The generated `main.tf` files are listed next:

Local:
```
provider "aws" {
  profile = "myprofile"
  region  = "myregion"
}

terraform {
  backend "local" {}
}
```

Remote:
```
provider "aws" {
  profile = "myprofile"
  region  = "myregion"
}

terraform {
  backend "s3" {
    bucket  = "mybucket"
    key     = "state.tfstate"
    profile = "myprofile"
    region  = "myregion"
  }
}
```

**Comment by jbardin** [comment]
Hi @betabandido,

This can be a little confusing. The term "environment" is quite overloaded, and we're actually renaming the feature to "workspaces" to avoid some of this confusion and avoid some conflicting definitions within the enterprise products. 

In short, "workspaces" (nee environments) are a _feature_ of backend.  Since workspaces only exist within a backend, there is no way practical way to decouple the two. However, we do plan to improve the `init` workflow, to try and allow more flexibility for users. For now you may be able to use the `-reconfigure` option, which will re-evaluate the configuration while avoiding state migrations.

**Comment by jbardin** [comment]
I forgot to mention, there is a typo in that particular state migration message, revering the "to" and "from" types. That is being taken care of already in another issue. Thanks!

**Comment by betabandido** [comment]
Oh, that makes sense :)

I will have a look at `-reconfigure` option. Thanks!
