### ISSUE TITLE
terraform v0.9.6 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by woody3549** [hashicorp/terraform#15382]
2017/06/23 14:40:23 [INFO] Terraform version: 0.9.6  85e0979c6af6a15345c9131e4478ba712bb3c21d
2017/06/23 14:40:23 [INFO] Go runtime version: go1.8
2017/06/23 14:40:23 [INFO] CLI args: []string{"/usr/local/bin/tf0.9.6/terraform", "plan"}
2017/06/23 14:40:23 [DEBUG] Detected home directory from env var: /home/boris
2017/06/23 14:40:23 [DEBUG] Detected home directory from env var: /home/boris
2017/06/23 14:40:23 [DEBUG] Attempting to open CLI config file: /home/boris/.terraformrc
2017/06/23 14:40:23 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/06/23 14:40:23 [INFO] CLI command args: []string{"plan"}
2017/06/23 14:40:23 [DEBUG] Detected home directory from env var: /home/boris
2017/06/23 14:40:23 [DEBUG] command: loading backend config file: /home/boris/workspace/bitbucket/terraform/datadog-sandbox.terraform/morea-demo/datadog-sandbox/eu-west-1/default
2017/06/23 14:40:23 [TRACE] Preserving existing state lineage "50dc897c-768b-4428-87f0-ccf6bf473350"
2017/06/23 14:40:23 [TRACE] Preserving existing state lineage "50dc897c-768b-4428-87f0-ccf6bf473350"
2017/06/23 14:40:23 [INFO] Building AWS region structure
2017/06/23 14:40:23 [INFO] Building AWS auth structure
2017/06/23 14:40:24 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2017/06/23 14:40:24 [INFO] AWS Auth provider used: "EnvProvider"
2017/06/23 14:40:24 [INFO] Initializing DeviceFarm SDK connection
2017/06/23 14:40:25 [DEBUG] Trying to get account ID via iam:GetUser
2017/06/23 14:40:25 [DEBUG] Getting account ID via iam:GetUser failed: AccessDenied: User: arn:aws:sts::612688033368:assumed-role/iam.terraform.states.rw/AWS-CLI-session-1498221497 is not authorized to perform: iam:GetUser on resource: arn:aws:sts::612688033368:assumed-role/iam.terraform.states.rw/AWS-CLI-session-1498221497
        status code: 403, request id: 223e35f8-5811-11e7-8204-5b90bfb7c502
2017/06/23 14:40:25 [DEBUG] Trying to get account ID via sts:GetCallerIdentity
2017/06/23 14:40:26 [WARN] Unable to get supported EC2 platforms: UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: b0c2a4d8-367e-47db-8d70-2f25e1990c6b
2017/06/23 14:40:26 [INFO] command: backend initialized: *s3.Backend
2017/06/23 14:40:26 [INFO] command: backend *s3.Backend is not enhanced, wrapping in local
2017/06/23 14:40:26 [INFO] backend/local: starting Plan operation
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x3af5caa]

goroutine 630 [running]:
github.com/hashicorp/terraform/backend/remote-state/s3.(*RemoteClient).Get(0xc4202e8230, 0x11, 0x11, 0x18)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/remote-state/s3/client.go:64 +0x11a
github.com/hashicorp/terraform/state/remote.(*State).RefreshState(0xc4207ad2e0, 0x40eed2, 0xc420553ac0)
        /opt/gopath/src/github.com/hashicorp/terraform/state/remote/state.go:33 +0x37
github.com/hashicorp/terraform/state.(*BackupState).RefreshState(0xc4207c1140, 0x5221db5, 0x7)
        /opt/gopath/src/github.com/hashicorp/terraform/state/backup.go:21 +0x33
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc42094c500, 0xc4202de6e0, 0x2, 0x2, 0x3, 0xc420553ac0, 0x2)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_local.go:31 +0x97
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc42094c500, 0x7c92880, 0xc4200124d0, 0xc4202de6e0, 0xc42082bfb0)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:57 +0x22f
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opPlan)-fm(0x7c92880, 0xc4200124d0, 0xc4202de6e0, 0xc42082bfb0)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:243 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc42094c500, 0xc420554070, 0xc420554060, 0x7c92880, 0xc4200124d0, 0xc4202de6e0, 0xc42082bfb0)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:265 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:266 +0x192

**Comment by jbardin** [comment]
Hi @woody3549,

Thanks for filing the issue. This is fixed in the current releases of Terraform.

**Comment by woody3549** [comment]
Hi,

I really need to use version 0.9.6 as we found some issues with 0.9.8
What can I do ?

Thanks

**Comment by jbardin** [comment]
@woody3549,

Sorry you're having an issue here. If you can run without the state locking features, removing the dynamodb table from the config should suffice.

You may also be able to find an invalid LockID entry in your dynamo table and remove it, allowing the new state file to be accessed. 

If you know the step required to replicate this situation, I may be better able to help you work around it in the meantime.
