### ISSUE TITLE
environment in terraform_remote_state has no effect

### ISSUE THREAD

**Issue by aep** [hashicorp/terraform#15396]
**Terraform v0.9.8-dev**

the path fetched from s3 does not change with the "environment" key used in terraform_remote_state.
so there is no way to fetch remote state from an env not "default", except by adding /env:/dev/ explicitly to  "key"

it would also make alot of sense if the environment used to fetch remote state actually matched the _current_ environment set with "terraform environment"
 
```hcl
data "terraform_remote_state" "foundation" {
    backend = "s3"
    config {
        bucket      = "tfstate.<mydomain>"
        key         = "foundation.tfstate"
        region      = "eu-central-1"
        encrypt     = true
        kms_key_id  = "<foo>"
        environment = "dev"
    }
}
```
```
2017/06/26 11:10:55 [DEBUG] plugin: terraform: terraform-provider (internal) 2017/06/26 11:10:55 [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
2017/06/26 11:10:55 [DEBUG] plugin: terraform: ---[ REQUEST POST-SIGN ]-----------------------------
2017/06/26 11:10:55 [DEBUG] plugin: terraform: GET /tfstate.<mydomain>/foundation.tfstate HTTP/1.1
[...]
2017/06/26 11:10:55 [DEBUG] plugin: terraform: ---[ RESPONSE ]--------------------------------------
2017/06/26 11:10:55 [DEBUG] plugin: terraform: HTTP/1.1 404 Not Found
```

**Comment by jamisonhyatt** [comment]
`environment` doesn't go inside the `config` block, but at the same level as backend and config.  It works fine for me in Terraform v0.9.9

**Comment by jbardin** [comment]
Yes, `environment` is a parameter for `terraform_remote_state`, not the config.
