### ISSUE TITLE
RDS DB Creation from recent DB-Snapshot

### ISSUE THREAD

**Issue by arupandit** [hashicorp/terraform#15397]
# PROVIDER ISSUES

**PLEASE NOTE:** Terraform has split out the builtin Providers into their own repositories. For any Provider issues, please open all issues and pull requests in the corresponding repository. An index of supported Providers can be found here:

- https://github.com/terraform-providers

All other issues (that appear to affect multiple or all providers) may be an issue with Terraform's core, and should be opened here. 

------

Hi there,

I'm trying to create a DB from an existing snapshot (the most recent one)  however it throws error. I'm using terraform 0.9.8 version.
Could somebody help me to fix this error.

### Terraform Version
Terraform 0.9.8 version.

### Terraform Configuration Files

provider "aws" {
  region = "${var.region}"
}

terraform {
  backend "s3" {
    bucket     = "bucket=dev-terraform-state"
    key        = "key=dev/dev2/terraform.tfstate"
    region     = "eu-west-1"
  }
}

RDS DB SUBNET GROUPS

resource "aws_db_subnet_group" "dev_db_subnet_group" {
  name = "${var.project}-${var.env}-dev-db-subnet-group"
  description = "dev SQLServer RDS Subnet Group"
  subnet_ids = [ "${var.data_subnet_id}", "${var.data_replica_subnet_id}" ]
  tags {
    Name = "${var.project}-${var.env}-dev-db-subnet-group"
  }
}

resource "aws_security_group" "dev_db_access" {
  name= "${var.project}-${var.env}-dev-db-access"
  vpc_id = "${var.back_vpc_id}"
  description = "Allow SQLServer inbound access"
  ingress {
    from_port = 1433
    to_port = 1433
    protocol = "tcp"
    cidr_blocks = [ "0.0.0.0/0" ]
  }
  egress {
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = [ "0.0.0.0/0" ]
  }
}

RDS DB INSTANCES
resource "aws_db_instance" "dev_db" {
  identifier           = "${var.project}-${var.env}"
  skip_final_snapshot  = false
  final_snapshot_identifier = "${var.project}-${var.env}-snapshot"
  allocated_storage    = 200
  snapshot_identifier  = "${data.aws_db_snapshot.devdb_snapshot.id}"
  engine               = "sqlserver-se"
  engine_version       = "11.00.6020.0.v1"
  instance_class       = "db.m3.large"
  license_model        = "license-included"
  username             = "${var.db_user}"
  password             = "${var.db_password}"
  storage_encrypted    = true
  vpc_security_group_ids = [ "${aws_security_group.dev_db_access.id}" ]
  db_subnet_group_name = "${aws_db_subnet_group.dev_db_subnet_group.name}"

}

data "aws_db_snapshot" "devdb_snapshot" {
    most_recent = true
    db_instance_identifier = "${aws_db_instance.dev_db.identifier}"  
}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
N/A

### Expected Behavior
It should have created a database from the snapshot

### Actual Behavior
What actually happened?

terraform plan

var.db_password
  Enter a value: 
var.env
  Enter a value: 

Error asking for user input: 1 error(s) occurred:
* Cycle: data.aws_db_snapshot.devdb_snapshot, aws_db_instance. dev_db

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by bclodius** [comment]
@arupandit Terraform is complaining because you've created a cyclical dependency.

In trying to create your RDS instance you have asked Terraform to use the snapshot from `"${data.aws_db_snapshot.devdb_snapshot.id}"` BUT at the same time you've asked referenced snapshot id to come from the RDS you are trying to create.

I think `data "aws_db_snapshot" "devdb_snapshot"` should be pointing to some other RDS that already exists; but I am unsure on your exact setup/details.

**Comment by arupandit** [comment]
@bclodius I will explain my requirement - My RDS instance should create a snapshot while destroying and use the latest snapshot to create a database. This is why I have have put this dependency but its not working.

How can I resolve this dependency? I don't want to hard code any value in data otherwise I have to change my terraform script for all the environments which I don't want to do.

**Comment by arupandit** [comment]
@bclodius Even when I change this to something else, it doesn't return the desired results.

https://www.terraform.io/docs/providers/aws/d/db_snapshot.html
what terraform says and it doesn't return any of them.
db_instance_identifier - (Optional) Returns the list of snapshots created by the specific db_instance

what I have changed:-
data "aws_db_snapshot" "devdb_snapshot" {
    most_recent = true
    db_instance_identifier = "project-dev"	
}

The result
1 error(s) occurred:
* aws_db_instance.dev_db: 1 error(s) occurred:
* aws_db_instance.dev_db: Error creating DB Instance: DBSnapshotNotFound: DBSnapshot not found: project-dev
	status code: 404

**Comment by arupandit** [comment]
@bclodius If I comment this- Everything works but this is not what I want. I want database from snapshot.

snapshot_identifier = "${data.aws_db_snapshot.devdb_snapshot.id}"

**Comment by bclodius** [comment]
@arupandit The db snapshot won't exist until the database had already existed and a snapshot of it was created.

**Comment by arupandit** [comment]
@bclodius The database already existed and created snapshot copies.

if I run only this piece, it works and creates a state file with all the information.

data "aws_db_snapshot" "devdb_snapshot" {
most_recent = true
db_instance_identifier = "project-dev"
}

but if I run all the piece together it fails to do so.
