### ISSUE TITLE
AWS asg launch configuration can't change if you modify user-data

### ISSUE THREAD

**Issue by debu99** [hashicorp/terraform#15406]
I changed user-data then it returns error, I have to delete ASG and ASG config manually

* aws_launch_configuration.ecs1_asg_config: 1 error(s) occurred:

* aws_launch_configuration.ecs1_asg_config: Error creating launch configuration: AlreadyExists: Launch Configuration by this name already exists - A launch configuration already exists with the name ECS1 tf_ecs1_example
	status code: 400, request id: 9067f370-5b37-11e7-8192-5947095da082
* aws_launch_configuration.ecs3_asg_config: 1 error(s) occurred:

**Comment by bclodius** [comment]
@debu99 can you share more details on your config for the `aws_launch_configuration` resource?

We're able to have dynamic LC's that trigger new ASG's by leveraging the following pattern.

```
resource "aws_launch_configuration" "some-lc" {
    ...
    name_prefix          = "my-lc-"
    ...
}

resource "aws_autoscaling_group" "some-asg" {
    ...
    name                      = "asg-${aws_launch_configuration.some-lc.name}"
    ...
}
```

**Comment by debu99** [comment]
I think the problem is when found there is changes in user-data, terraform need to establish new resource, but it seems it didn't delete old ones, so the same name make the new resource setup failed

user_data:                   "55994cf2b1432e8301a2e1bc8cadc16d1f5ddf9c" => "ffd6c5dd9069711627aa38288bbe3d98a6ccd0c3" (forces new resource)


resource "aws_launch_configuration" "ecs1_asg_config" {
    name = "ECS1 ${var.ecs1_cluster_name}"
    image_id = "${lookup(var.amis, var.aws_region)}"
    instance_type = "${var.instance_type}"
    security_groups = ["${aws_security_group.sg_ecs_instance.id}"]
    iam_instance_profile = "${aws_iam_instance_profile.ecs_instance_profile.name}"
    key_name = "${var.ssh_key_name}"
    associate_public_ip_address = true
    user_data = "${data.template_file.userdata1.rendered}"
    lifecycle {
      create_before_destroy = true
    }
}

resource "aws_autoscaling_group" "ecs1-cluster-asg" {
    name = "ECS1 ${var.ecs1_cluster_name}"
    launch_configuration = "${aws_launch_configuration.ecs1_asg_config.name}"
    vpc_zone_identifier = ["${aws_subnet.sub_pub.*.id}"]
    availability_zones = ["${var.availability_zone}"]
    min_size = "${var.autoscale_min}"
    max_size = "${var.autoscale_max}"
    desired_capacity = "${var.autoscale_desired}"
    load_balancers = ["${aws_elb.ecs1_elb_example.name}"]
    health_check_type = "ELB"  
    tag {
      key = "Name"
      value = "ecs1-asg-example"
      propagate_at_launch = true
    }
}

data "template_file" "userdata1" {
  template = "${file("./user-data/ecs_userdata.sh.tpl")}"
  vars {
    cluster_name_of_ecs = "${var.ecs1_cluster_name}"
  }
}

ecs_userdata.sh.tpl (From datadog)
-------------------------
#!/bin/bash
cluster="${cluster_name_of_ecs}"
task_def="dd-agent-task"
echo ECS_CLUSTER=$cluster >> /etc/ecs/ecs.config
start ecs
yum install -y aws-cli jq
instance_arn=$(curl -s http://localhost:51678/v1/metadata \
  | jq -r '. | .ContainerInstanceArn' | awk -F/ '{print $NF}' )
az=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
region=$${az:0:$${#az} - 1}
echo "
cluster=$cluster
az=$az
region=$region
aws ecs start-task --cluster $cluster --task-definition $task_def \
  --container-instances $instance_arn --region $region" \>/tmp/awslog.txt >> /etc/rc.local

**Comment by debu99** [comment]
try to delete create_before_destroy = true part, but still can't recreate resource automatically, new error occurred as below:


* aws_launch_configuration.ecs1_asg_config: ResourceInUse: Cannot delete launch configuration ECS1 tf_ecs1_example because it is attached to AutoScalingGroup ECS1 tf_ecs1_example
	status code: 400, request id: f86325cf-5bcd-11e7-a347-03a31eee5790
* aws_launch_configuration.ecs3_asg_config (destroy): 1 error(s) occurred:

**Comment by sanjay-cc** [comment]
Getting this error with terraform
