### ISSUE TITLE
Terraform aws rds cluster aurora with multi-az flag

### ISSUE THREAD

**Issue by awscodedeploy** [hashicorp/terraform#15409]
Hi Team,

I am using terraform to provision aws rds aurora cluster using aws rds cluster and cluster instance terraform aws rds resources, with multi-az option, but unfortunately, both of these terraform aws resources  does not support multi-az flag.

Could someone from the group experts can help us in same, i.e. to create aws rds aurora cluster with multi az option.

Do let me know if anything is required from my side in same.

Thanks in advance

**Comment by stack72** [comment]
Hi @awscodedeploy 

Thanks for opening the issue. I am going to direct you to our community pages: https://www.terraform.io/community.html

You will be able to find more help in one of these locations. We try to keep the issue list only for bugs / feature requests

Thanks

Paul
