### ISSUE TITLE
Feature request: Named state support for Azure

### ISSUE THREAD

**Issue by ryanl-ee** [hashicorp/terraform#15411]
Hi all,
Wanted to put a request for named state support in Azure in writing. Currently we can't use Terraform Environments together with the Azure Remote State Backend. Trying to create a new environment yields this error message: `named states not supported`.

I found a merged PR that adds this functionality to S3, if that helps: https://github.com/hashicorp/terraform/pull/12987

Thanks for reading!

**Comment by r7vme** [comment]
We also would like to see workspaces support in AzureRM backend. Thanks

**Comment by tombuildsstuff** [comment]
Hey @ryanl-ee @r7vme 

Support for this was added recently and [is available via the `azurerm` backend](https://www.terraform.io/docs/backends/types/azurerm.html).

Thanks!

**Comment by r7vme** [comment]
Thanks @tombuildsstuff. Looks like i misunderstood description. We want namespaces support in AzureRM. Created new issue for that. https://github.com/hashicorp/terraform/issues/16530
