### ISSUE TITLE
error: plan state and ContextOpts state are not equal

### ISSUE THREAD

**Issue by FlorinAndrei** [hashicorp/terraform#15433]
### Terraform Version
```
$ terraform -v
Terraform v0.9.10
```

### Terraform Configuration Files
```
$ git diff
 [blah blah]
 # Network
 #--------------------------------------------------------------
 foobar = CENSORED
-jenkins_ips = ["172.31.20.156/32", "172.31.26.214/32"]
+jenkins_ips = ["172.31.20.156/32", "172.31.26.214/32", "172.31.49.0/24"]
```

I can provide config files if needed. That's just the change that triggered the error. This is the security group for an EC2 instance.

Should be noted that previous state was created with terraform 0.9.8. I added the new IP block and upgraded to 0.9.10 simultaneously. Not sure if that matters.

It's annoying that Terraform hates downgrading so much. It's impossible to go back to old versions.

### Debug Output
```
Path: plan

-/+ module.rmq_allow_ssh_from_jenkins.aws_security_group_rule.allow_ssh_from_ip_list
    cidr_blocks.#:            "2" => "3" (forces new resource)
    cidr_blocks.0:            "172.31.20.156/32" => "172.31.20.156/32"
    cidr_blocks.1:            "172.31.26.214/32" => "172.31.26.214/32"
    cidr_blocks.2:            "" => "172.31.49.0/24" (forces new resource)
    from_port:                "22" => "22"
    protocol:                 "tcp" => "tcp"
    security_group_id:        "sg-23d3dd58" => "sg-23d3dd58"
    self:                     "false" => "false"
    source_security_group_id: "" => "<computed>"
    to_port:                  "22" => "22"
    type:                     "ingress" => "ingress"

-/+ module.api_allow_ssh_from_jenkins.aws_security_group_rule.allow_ssh_from_ip_list
    cidr_blocks.#:            "2" => "3" (forces new resource)
    cidr_blocks.0:            "172.31.20.156/32" => "172.31.20.156/32"
    cidr_blocks.1:            "172.31.26.214/32" => "172.31.26.214/32"
    cidr_blocks.2:            "" => "172.31.49.0/24" (forces new resource)
    from_port:                "22" => "22"
    protocol:                 "tcp" => "tcp"
    security_group_id:        "sg-50d2dc2b" => "sg-50d2dc2b"
    self:                     "false" => "false"
    source_security_group_id: "" => "<computed>"
    to_port:                  "22" => "22"
    type:                     "ingress" => "ingress"

-/+ module.web_allow_ssh_from_jenkins.aws_security_group_rule.allow_ssh_from_ip_list
    cidr_blocks.#:            "2" => "3" (forces new resource)
    cidr_blocks.0:            "172.31.20.156/32" => "172.31.20.156/32"
    cidr_blocks.1:            "172.31.26.214/32" => "172.31.26.214/32"
    cidr_blocks.2:            "" => "172.31.49.0/24" (forces new resource)
    from_port:                "22" => "22"
    protocol:                 "tcp" => "tcp"
    security_group_id:        "sg-88d7d9f3" => "sg-88d7d9f3"
    self:                     "false" => "false"
    source_security_group_id: "" => "<computed>"
    to_port:                  "22" => "22"
    type:                     "ingress" => "ingress"


Plan: 3 to add, 0 to change, 3 to destroy.
$ terraform apply plan
plan state and ContextOpts state are not equal
```

I can do more tests if needed.

### Expected Behavior
Just add the new IP block to the security group.

### Actual Behavior
error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `add new IP block to variable`
2. upgrade from 0.9.8 to 0.9.10 (not sure if that actually matters)
3. `terraform plan -var-file=global_terraform.tfvars -out=plan`
4. `terraform apply plan`

**Comment by FlorinAndrei** [comment]
BTW, for now I've fixed that security group manually, so testing might be tricky, but I can do it if you need me to run tests.

**Comment by jbardin** [comment]
Hi @FlorinAndrei,

Thanks for filing the issue! Before I dive in here, can you tell me what backend you were using (i.e. is the state local, in s3, consul, etc.)?

**Comment by jbardin** [comment]
For the record so far, I've been able to make a plan summary that matches exactly the output here, but apply works without error. I've also tried this with an s3 backend, while upgrading from 0.9.8->0.9.10, and with multiple runs in an attempt to rule out non-determinism.

@FlorinAndrei, let me know if you can reproduce this at all. If it's at all possible to share even a redacted state file, that might help too. Thanks!

**Comment by rfletcher** [comment]
Seeing the same error with 0.9.10. Definitely was not present in 0.9.9 prior to upgrading, and 0.9.9 is still working now that've downgraded. (I edited the state file to allow the downgrade.)

In my case I'm using the s3 backend, and was trying to add some aws_route53_record resources.
I'm using the s3 backend.

I can't provide any further details right this moment, but I'll check back in when I can and try to provide some sample code if no one else has.

**Comment by slillibri** [comment]
I am seeing the same errors with 0.9.10. I am using the s3 backend, and was trying to apply a destroy plan. The original apply was run also with 0.9.10.

```
{
    "version": 3,
    "terraform_version": "0.9.10",
    "serial": 249,
    "lineage": "668194e9-f7f5-4a4b-8a83-bf530df3acf1",
    "modules": [
```

What is interesting to me is that the destroy plan returns
```Plan: 1 to add, 0 to change, 51 to destroy.```
but it shows 52 resources to destroy. The apply run failed so 1 instance is tainted. Let me know if I can add any further detail.

**Comment by FlorinAndrei** [comment]
Redacted files: [tf-issue.zip](https://github.com/hashicorp/terraform/files/1116680/tf-issue.zip)

S3 backend, locking with DynamoDB.

It happened yesterday every time I attempted to add that new IP block to the SG. Eventually I added the block manually - I needed the change and could not wait for Terraform to get fixed. I can't test it now since the change is in. If you absolutely need me to test it, I can schedule a downtime since this is not production (but it is a heavily used QA env).

**Comment by apparentlymart** [comment]
Hi all! Sorry again for this regression.

We have an explanation for the problem now, and plan to release a fix on Monday when more of the team is around to test and support the release.

In the mean time we recommend staying on 0.9.9, especially if you are not using the "atlas" backend, since 0.9.10 has no additional benefit for other backends.

The issue is unfortunately a rather subtle quirk of how state is serialized in the plan (via Go's gob encoding) vs in the standalone state file (as JSON), causing slight differences that are erroneously being detected as problematic here. (To be specific, some numbers are `int` in one case and `float` in the other, with the same value.)

**Comment by analytically** [comment]
+1, seeing this as well

**Comment by milosradovanovic** [comment]
same here

**Comment by zimbatm** [comment]
Is it possible to revert a state that has already been upgraded to 0.9.10? After reverting back to 0.9.9 I'm getting:

```
Terraform doesn't allow running any operations against a state
that was written by a future Terraform version. The state is
reporting it is written by Terraform '0.9.10'.
```

**Comment by andersha** [comment]
You can change the version in the tfstate file. If you you some sort of backend you need to handle it there. We have a hash of the tfstate in a DynamoDB and had to fix it there as well.

**Comment by zimbatm** [comment]
Actually terraform keeps the old state around: `terraform state push -force terraform.tfstate.backup`

**Comment by RyanAtCNG** [comment]
We're seeing this issue with TFE w/ terraform 0.9.10.  We've managed to work around it for the time being by applying changes from our laptops by doing an apply WITHOUT a plan file.  If the plan is saved to a file, it will cause this error when applying.

**Comment by jbardin** [comment]
Hi Everyone,

Sorry for the inconvenience here. This issue is taken care of in the 0.9.11 release.

I'll add the details here, so they are a little easier to find, since this fix isn't in the master branch:

The fix in this case was to demote the error noted here to a logged error. Any errors reported by the act of saving and refreshing the state should be sufficient to indicate a problem, so the extra check isn't strictly necessary and was disabled. 

The error was intended as a final sanity check to make sure everything saved as expected, and should not have been encountered except by a failure of the backend to reproduce the stated just saved. What happened was that in some cases data had been introduced into the state that was altered by the serialization process, which caused the state to appear as not equal, even though said data was not relevant to the apply process.

**Comment by zimbatm** [comment]
@jbardin do you have a link to the fixing commit for posterity's sake?

**Comment by FlorinAndrei** [comment]
Works for me now. Thanks!
