### ISSUE TITLE
TF Plan is showing "2 to add" despite only one resource being created

### ISSUE THREAD

**Issue by mechastorm** [hashicorp/terraform#15436]
### Terraform Version
v0.9.8

### Terraform Plan
```
+ aws_route53_record.mycache
    fqdn:               "<computed>"
    name:               "mycache.internal"
    records.#:          "1"
    records.3561556081: "mycache.ng.0001.usw2.cache.amazonaws.com"
    ttl:                "60"
    type:               "CNAME"
    zone_id:            "ABCDEF"

Plan: 2 to add, 0 to change, 0 to destroy.

```

### Expected Behavior
The plan summary should just say "1 to add, 0 to change, 0 to destroy"

### Actual Behavior
The plan summary says "2 to add, 0 to change, 0 to destroy"

### Steps to Reproduce
Try an AWS resource - ie. route53. 

Can't verify if it affects on other providers.

### Important Factoids
Seems to double up the number.

When I created 3 resources (db, sg and an ec2 instance) it reports it will create 6 instead of 3

**Comment by jbardin** [comment]
Hi @mechastorm,

Thanks for filing the issue. We're tracking this in issue #14905.
