### ISSUE TITLE
AWS Route53 Request Rejected

### ISSUE THREAD

**Issue by KatherineAlbany** [hashicorp/terraform#1543]
When creating multiple route53 records in aws I receive the following error response:

"The request was rejected because Route 53 was still processing a prior request"

After discussion on IRC this was considered a bug and that terraform should account for the slow Route53 API and wait/retry instead of failing.

**Comment by catsby** [comment]
Thanks @KatherineAlbany , I'll take a look. You're talking about multiple `aws_route53_record` resources in the config, right? As opposed to a single one with many `records`, correct?

**Comment by KatherineAlbany** [comment]
Correct, multiple aws_route53_record resources.

**Comment by catsby** [comment]
Thanks @KatherineAlbany – I'll try and look at this today, but I can't promise it 😕

**Comment by catsby** [comment]
Hey @KatherineAlbany – I apologize for the delay here :frowning: 

I just tried to reproduce this but with no success. I used the following configuration file:

```javascript
provider "aws" {
  region="us-west-2"
}

resource "aws_route53_zone" "primary" {
   name = "tftesting.com"
}

resource "aws_route53_record" "default" {
    zone_id = "${aws_route53_zone.primary.id}"
    name = "www.ctshryock.com"
    type = "A"
    ttl = "30"
    records = ["127.0.0.1"]
}

resource "aws_route53_record" "other" {
    zone_id = "${aws_route53_zone.primary.id}"
    name = "testing"
    type = "A"
    ttl = "30"
    records = ["127.0.0.3"]
}

resource "aws_route53_record" "xub" {
    zone_id = "${aws_route53_zone.primary.id}"
    name = "xub"
    type = "A"
    ttl = "30"
    records = ["127.0.0.9"]
}

resource "aws_route53_record" "othersub" {
    zone_id = "${aws_route53_zone.primary.id}"
    name = "othersub"
    type = "A"
    ttl = "30"
    records = ["127.0.0.19"]
}

```

[This commit](https://github.com/hashicorp/terraform/commit/49e6c8fd) was added in v0.4.0 which _should_ address things like you report, however, v0.4.0 came out prior to opening of this issue. Do you recall if you were on 0.3.7?

**Comment by KatherineAlbany** [comment]
Thank you for looking into this catsby,

We are currently using 0.4.2 and have not noticed this error occurring any longer, it looks like that commit may have addressed this issue.

We are currently suffering with hitting the AWS rate limits, but although the symptoms appear similar to this issue, I don't believe they are related.

Thanks again, I'll close this issue.

**Comment by catsby** [comment]
Hey @KatherineAlbany – thanks for following up. 
v0.4.2 should have had some improvements there, and v0.5.0 should have even more. We've migrated to the official AWS SDK library (https://github.com/awslabs/aws-sdk-go), which has additional throttling and backoff functionality, which should help with some of the rate limit issues people run into. v0.5.0 should be out in the next few days.

Let me know if you're still hitting them after that, and thanks again!
