### ISSUE TITLE
Looping AWS Resource and getting Outputs in maps

### ISSUE THREAD

**Issue by urmail2ss** [hashicorp/terraform#15432]
Hi Guys,
I am trying to create the aws resource in looping. I want know how to get the output of this resource in map. 

```
resource "aws_s3_bucket" "app_buckets" {
  count  = "${length(var.app_s3_buckets)}"
  bucket = "${lookup(var.app_s3_buckets, element(keys(var.app_s3_buckets), count.index))}"
  acl    = "private"
  tags {
      Name = "${lookup(var.app_s3_buckets, element(keys(var.app_s3_buckets), count.index))}"
      Environment = "${var.env}"
  }
}
```

I am **looking of outputs like in below format**?  Can you please let me know is it doable or please let me know the alternate for same (other than hard code values). Reason for asking this I have depended resource needs to be create like IAM policies for all this buckets. 

```
output "s3_app_buckets_arn_map" {
  value = "${
    map(
      aws_s3_bucket.app_buckets.*.id, aws_s3_bucket.app_buckets.*.arn
    )
    }"
}
```

Thanks,
Shan

# PROVIDER ISSUES

**PLEASE NOTE:** Terraform has split out the builtin Providers into their own repositories. For any Provider issues, please open all issues and pull requests in the corresponding repository. An index of supported Providers can be found here:

- https://github.com/terraform-providers

All other issues (that appear to affect multiple or all providers) may be an issue with Terraform's core, and should be opened here. 

------

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by pselle** [comment]
Hello @urmail2ss! A lot of time has passed on this issue, and I hope you found some guidance elsewhere! I'm going to close this, as we use GitHub issues for tracking bugs and enhancements rather than for questions.

We suggest that folks use our [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
