### ISSUE TITLE
helper/schema: Crash on v0.9.8 to v0.9.10 in ConfigFieldReader.readMap

### ISSUE THREAD

**Issue by jarro2783** [hashicorp/terraform#15442]
Terraform plan crashes for me. I don't really know how much information you would like to debug this. My code is quite large, and the crash log has some things I would like to redact if I post the whole thing. So I have posted some of it near the crash. Just let me know if you want more and I will provide as much as I can.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

0.9.8 to 0.9.10 (I haven't verified on any older versions)

### Panic log
```
2017/06/30 16:41:28 [TRACE] [walkRefresh] Exiting eval tree: module.logging.aws_security_group.shipper
2017/06/30 16:41:28 [DEBUG] dag/walk: walking "module.logging.module.logstash_shipper_asg.var.security_groups"
2017/06/30 16:41:28 [DEBUG] vertex 'root.module.logging.module.logstash_shipper_asg.var.security_groups': walking
2017/06/30 16:41:28 [DEBUG] vertex 'root.module.logging.module.logstash_shipper_asg.var.security_groups': evaluating
2017/06/30 16:41:28 [DEBUG] root.logging: eval: *terraform.EvalSequence
2017/06/30 16:41:28 [DEBUG] root.logging: eval: *terraform.EvalInterpolate
2017/06/30 16:41:28 [TRACE] [walkRefresh] Entering eval tree: module.logging.module.logstash_shipper_asg.var.security_groups
2017/06/30 16:41:28 [DEBUG] root.logging: eval: *terraform.EvalGetProvider
2017/06/30 16:41:28 [DEBUG] root.logging: eval: *terraform.EvalValidateResource
2017/06/30 16:41:28 [DEBUG] root.logging: eval: *terraform.EvalReadState
2017/06/30 16:41:28 [DEBUG] root.logging: eval: *terraform.EvalDiff
2017/06/30 16:41:28 [DEBUG] plugin: terraform: panic: interface conversion: interface {} is string, not map[string]interface {}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out terraform.tfplan -var-file terraform.tfvars -var-file ../terraform.tfvars templates`

**Comment by stack72** [comment]
Hi @jarro2783 

apologies for the crash, please can you include the full panic log and your Terraform config (minus secrets) we can try and identify the problem?

Thanks

Paul

**Comment by jarro2783** [comment]
Sure I can do that. I'll get it done as soon as I can, it will probably take a while to put together.

My configuration is quite large, having several modules in it. Would you like me to try to minimise it if I can, or will you be able to track it down even with a lot of resources?

**Comment by jarro2783** [comment]
Turns out I was able to reproduce it on a tiny amount of code: https://gist.github.com/jarro2783/715fd9a71f1b535ffe788e579447eabd

It seems to be the `merge` that does it. Although I've used that in other places and it has worked.

It also crashes when `var.common_tags` is empty, or not even passed to the `merge` function.

**Comment by jbardin** [comment]
Hi @jarro2783,

Thanks for the reproduction!
While this should definitely _not_ crash, this is related to an error in the configuration:

    tags        = ["${merge(map("role", "crash_lb"), var.common_tags)}"]

`tags` expects a mapping of key values, but here you are putting the results if the `merge` in square brackets (`[]`), which makes it a single element in a list. For some reason the interpolation is causing this to slip through the validation step, which panics later on when the expected types don't match.

**Comment by jbardin** [comment]
This crashes without the interpolation function, so it seems to be a remnant of the eliding the `[]` in some cases:

```
data "template_file" "foo" {
	vars = ["${var.tag}"]
}


variable "tag" {
	default = {
		foo = "bar"
	}
}
```

**Comment by jarro2783** [comment]
Ah right, thanks for spotting that. In fact in all the other places I've done this it is without the `[]`.

**Comment by CodeFarmer** [comment]
I was just about to report a very similar crash where having multiple tags clauses in a list (seemingly legal), one of which is an interpolated var ("${var.common_tags}" or similar), reliably crashes TF. But I suspect they are the same underlying issue.

resource "aws_instance" "ecs_host" {

  ami           = "ami-809f84e6"
  instance_type = "t2.micro"
  
  tags = [
    "${var.common_tags}",
    {
    Owner         = "blahblahblah"
    }]

}
