### ISSUE TITLE
Push a versioned "latest" terraform docker image to the docker hub

### ISSUE THREAD

**Issue by dvishniakov** [hashicorp/terraform#15445]
https://hub.docker.com/r/hashicorp/terraform/tags/ currently contains versioned tags (... 0.9.8, 0.9.9) except for the latest (0.9.10)
Please also push a versioned images along with the "latest" so it could be pinned in automation scripts. 

hashicorp/terraform:0.9.9
hashicorp/terraform:latest # it's 0.9.10 inside
hashicorp/terraform:0.9.10 # missing

As we see in the changelogs, "latest" version sometimes introduces bugs and ideally there should be an option to opt out.

Thanks!

**Comment by abitrolly** [comment]
There is now `latest` tag that was uploaded together with 0.10.7. Is it what you request?

**Comment by dvishniakov** [comment]
@abitrolly yes, it seems like now there is a corresponding versioned image pushed along with "latest". I'm closing this issue.
