### ISSUE TITLE
Feature Request: Allow common or "create once" resources in modules

### ISSUE THREAD

**Issue by FutureSharks** [hashicorp/terraform#15459]
It would be great if we could have resources in modules that are common to all instances of the module or are considered "create_once". These resources are then created on the first instance of the module and re-used by subsequent instances of the module.

For example: You have a module to create a cluster, you need many clusters, all cluster masters require an IAM role and with the same policy.

modules/cluster/master.tf:

```
resource "aws_iam_instance_profile" "cluster_masters" {
  create_once = true
  name        = "cluster_masters"
  role        = "${aws_iam_role.cluster_masters.name}"
}

resource "aws_iam_role" "cluster_masters" {
  create_once          = true
  name             = "cluster_masters"
  assume_role_policy = "${data.aws_iam_policy_document.cluster_assume_role_policy.json}"
}

resource "aws_launch_configuration" "cluster_master" {
  name_prefix         = "${var.cluster_name}-master-"
  iam_instance_profile = "${aws_iam_instance_profile.cluster_masters.arn}"
}
```

Currently we have 3 solution for this problem, none of which are great:
1. Modules just create many duplicate resources even though they are all the same and could be shrared. e.g. IAM instance profiles, IAM roles, IAM policies, S3 buckets, subnets, VPCs etc.
2. We create `<module_name>_base.tf` for each module and put shared resources in this file. This file exists in the root, not in the module directory. Then we pass attributes from these resources into module definitions.
3. We also have a custom Terraform wrapper tool to achieve this.

**Comment by jbardin** [comment]
Hi @FutureSharks,

Thanks for opening the issue.

 While this is an interesting idea, it goes against the way modules are intended to be used. Each module namespace is independent, creating all the resources defined therein. 

The [remote state data source](https://www.terraform.io/docs/providers/terraform/index.html) is another way you could create a single resource and share it across multiple configurations, as are other data sources that can lookup existing resources.

We do have plans to improve the configuration language around this use case in future releases. Improving the flexibility and syntax in this area may smooth the task of creating shared resources at higher levels and passing them into all modules that need to reference the resources.
