### ISSUE TITLE
terraform plan -target=x not working?

### ISSUE THREAD

**Issue by Dogers** [hashicorp/terraform#15450]
On https://www.terraform.io/docs/commands/plan.html, it appears to be saying that running `terraform plan -target=aws_instance.something` should cause only that single instance and any supporting items to be brought online. Doing so does not, it simply says the environment is up to date, despite it being empty from a previous `destroy`. `apply` does the same thing - nothing!

Is this the correct interpretation of what `-target=` should be doing? This is happening in 0.9.10.

**Comment by apparentlymart** [comment]
Hi @Dogers! Sorry this isn't working as expected.

The most common cause of this issue is some sort of typo in the given resource address. For example, spelling the name wrong, or forgetting to include a `module.foo.` prefix to address something in a child module.

Are you sure the address you are entering matches something in your config?

**Comment by Dogers** [comment]
Believe so - if I type in gibberish it'll come back saying item not found. I'll try a full apply tomorrow to get the exact name out of the state file then retry with that..

I'm correct in that it should be provided as `-target=module.modulename.aws_instance.instancename` ?

**Comment by Dogers** [comment]
Must have just been a Friday afternoon issue - appears to be all working as expected now!? :)

If I get the name wrong, it does actually just say everything is up to date, but if the format is wrong then it comes back with the error, so I must have typo'ed somewhere. Sorry!

**Comment by apparentlymart** [comment]
Sorry for this confusing behavior, @Dogers. In future it'd be good to do a check here to see if the given target matches any resources at all, and produce an error on that case. That way it could more easily be distinguished from the situation where some resources matched but they had nothing to update.

**Comment by espoelstra** [comment]
`terraform state list` is a great way to see all the modules that are available as targets for `terraform plan -target=module.name`.
