### ISSUE TITLE
Docker run doesn't map to localhost

### ISSUE THREAD

**Issue by w3apps** [hashicorp/terraform#15456]
### Terraform Version
Terraform v0.9.8

### Terraform Configuration Files
```hcl
provider "aws" {
  access_key = ""
  secret_key = ""
  region     = ""
}

resource "aws_instance" "my-instance" {
  ami               = "ami-7d50491b"
  availability_zone = ""
  instance_type     = "t2.small"
  security_groups   = [""]
  key_name          = ""

  connection {
    user        = "ec2-user"
    private_key = ""
  }

  provisioner "remote-exec" {
    inline = [
      # install and start docker
      "sudo yum -y install docker",
      "sudo service docker start",
      "sudo docker run -d -p 80:80 nginx"
    ]
  }
}
```

### Expected Behavior
SSH'ing in the new instance and running `curl 127.0.0.1:80` should return the response from NGINX.

### Actual Behavior
If I SSH in the new instance and I run `curl 127.0.0.1:80` I get `curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused`.
If I run `docker restart <process-id>` and I run `curl` again everything is fine.
Also running `netstat -tulpn | grep "80"` before restarting the docker process doesn't return anything, running it after the restart it shows the docker process listing on port 80. However running `docker restart` inside the terraform config doesn't help.
If I remove the `docker run` part from the config and do it manually on the server everything is fine.
It seems that there is a problem on how terraform executes the `remote-exec` command which prevents docker from mapping to localhost. If I curl the public IP everything is fine, it's just the localhost that's not working

### Steps to Reproduce
1. `terraform apply`

As a side note, I'm running terrafrom from OSX.

**Comment by apparentlymart** [comment]
Hi @w3apps! Sorry this didn't work out as expected.

Unfortunately it's hard to guess what's going on here with the information given. Was there any interesting output from the `remote-exec` provisioner during the apply command? Normally this provisioner will print any stdout or stderr items to the console, and so there may be a clue there as to what failed.

If I had to make a guess, it'd be that there is some delay after `sudo service docker start` returns before the docker daemon is actually up and running, and so the subsequent `docker run` immediately afterward is failing. But that is _just_ a guess, and indeed it could be any number of things going on here.

If you're able to provide some or all of the output from `terraform apply` I think that would go a long way getting to the bottom of this.

**Comment by w3apps** [comment]
Hi @apparentlymart 
Thanks for the response. There's nothing failing, `docker run` works as expected. If I run `docker ps` on the machine it shows the process. It's even accessible via the machine public IP, so the port get exposed correctly.
However after digging a bit more I realised it's just that there are some differences between terraform's ssh and me ssh'ing manually in the machine. In terraform's case the docker process doesn't get bind to localhost/127.0.0.1.
A workaround for this is to setup a custom docker network and assign a specific IP to the process, though this won't fix the problem of not binding to localhost but you can have an exact IP if you need to talk to the docker process locally (as I do).
Also @apparentlymart this should be easily replicable with the information and terraform config above.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
