### ISSUE TITLE
distribution: update homebrew formula for 0.4.2

### ISSUE THREAD

**Issue by neurogenesis** [hashicorp/terraform#1546]
looks like there's a homebrew formula for 0.4.1, it should be updated for the latest 0.4.2 release.

**Comment by radeksimko** [comment]
This belongs to the [Homebrew project](https://github.com/Homebrew/homebrew), not here, I'm afraid.
btw. Pull requests are usually quite welcomed in Homebrew too. :wink:

**Comment by arubis** [comment]
Also note that Brew Cask (http://caskroom.io/) is typically more on the ball about Terraform releases :)

**Comment by neurogenesis** [comment]
@phinze ... re: terraform on homebrew, i noticed you had submitted 0.4.1. i was going to update it there but it looked like it might not be trivial, given all of the go dependency revisions specified in there.

**Comment by mitchellh** [comment]
@radeksimko is correct. Please report this with homebrew. We don't maintain that release channel currently. Thanks.
