### ISSUE TITLE
JSON plan fails with "provider" must be followed by a name

### ISSUE THREAD

**Issue by kickin6** [hashicorp/terraform#15466]
### Terraform Version
Terraform v0.9.11

### Terraform JSON Configuration Files
```json
{
  "provider": [
    {
      "google": [
        {
          "credentials": "mycreds",
          "project": "myproject",
          "region": "us-west1"
        }
      ]
    }
  ],
  "resource": [...]
}
```

### Debug Output
`Failed to load root config module: Error loading ./plan.json.tf: -: "provider" must be followed by a name`

### Expected Behavior
```
No changes. Infrastructure is up-to-date.
```

### Actual Behavior
Error message
`Failed to load root config module: Error loading ./plan.json.tf: -: "provider" must be followed by a name`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @kickin6! Sorry this didn't work as expected, and for the delay in getting back to you.

We've been working for the last few months on a large change to the configuration language implementation in Terraform, which included an overhaul of the JSON syntax handling. I'm happy to report that when I tried the configuration example you gave (having removed the `resources` property just to make it valid), the Terraform v0.12.0-alpha1 release was able to parse it as expected and install the `google` provider:

```
$ terraform init

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.google: version = "~> 1.19"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

This fix is in `master` and will be included in the eventual v0.12.0 final release, and so I'm going to close out this issue. Thanks again for reporting it, and again sorry for the delay in replying.
