### ISSUE TITLE
aws ecs placement_strategy can't use multiply strategy

### ISSUE THREAD

**Issue by debu99** [hashicorp/terraform#15487]
placement_strategy =  [
        {
            "field": "instanceId",
            "type": "spread"
        },    
        {
            "field": "memory",
            "type": "binpack"
        },
        {
            "field": "cpu",
            "type": "binpack"
        }
    ]

Failed to load root config module: Error parsing /Users/tester/terraform/ecs/api/3Clusters/ecs_only_1_cluster.tf: At 116:20: illegal char

http://docs.aws.amazon.com/zh_cn/AmazonECS/latest/developerguide/task-placement-strategies.html

**Comment by stack72** [comment]
Hi @debu99 

The issue isn't because of the code, it's because you are using JSON

the config should look as follows:

```
resource "aws_ecs_service" "mongo" {
  name = "mongodb"
  ..........
  placement_strategy {
  	  field = "instanceId"
	  type = "spread"
  }

placement_strategy {
  	  field = "memory"
	  type = "binpack"
  }

placement_strategy {
  	  field = "cpu"
	  type = "binpack"
  }
}
```

That will then work

Paul
