### ISSUE TITLE
Enhancement - Allow versioned Provisioner script from git for remote-exec

### ISSUE THREAD

**Issue by kcrouch** [hashicorp/terraform#15505]
The remote-exec Provisioner allows the user to specify a script to run, but seems to only allow a local path.  As the documentation mentions, "This is a path (relative or absolute) to a local script").  It would be fabulous to allow a versioned file in git much like a module source allows. 

The use case for this is we have a "live" git repo that is basically just variables used by terragrunt to call versioned modules in a separate "modules" git repo.  Keeping provisioning scripts in the "modules" repo and just dropping a reference to them by git tag in the "live" repo variables helps keep the code DRY and prevents changes to the provisioner scripts from having unintended side-effects.  In our use case, the provisioning scripts aren't doing application-specific things, but rather bootstrapping puppet, so keeping them DRY and out of "live" makes the most sense.

This seems to be related to #230 and #683, although it is hopefully as easy as "borrowing" a little functionality that is already in Modules for Provisioners.

Thanks to everyone who contributes to this project and community.

**Comment by pkolyvas** [comment]
Hey @kcrouch! Sorry it's taken me long to get around to commenting on this. 

I'm doing a clean-up of older issues that haven't gained traction and which also don't coincide with our current focus and longer term plans. While provisioners, as a whole, aren't a top priority for the team, when some time is available to focus on them we're going to use that attention for some long-standing defects. 

Being available, and listening to our broad community is the main way we develop and set priorities. We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform, your use cases, and your needs as a practitioner.
