### ISSUE TITLE
Bash on Ubuntu on Windows 10 - Cannot create Lambda function

### ISSUE THREAD

**Issue by jonjohnston** [hashicorp/terraform#15512]
# PROVIDER ISSUES

**PLEASE NOTE:** Terraform has split out the builtin Providers into their own repositories. For any Provider issues, please open all issues and pull requests in the corresponding repository. An index of supported Providers can be found here:

- https://github.com/terraform-providers

All other issues (that appear to affect multiple or all providers) may be an issue with Terraform's core, and should be opened here. 

------

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Terraform Configuration Files
```hcl
provider "aws" {
        region = "${var.region}"
        profile = "${var.newaccount}"
}

#Create Lambda Function
data "template_file" "lambdafunction" {
        template = "${file("startscout2.py")}"

        vars {
                region = "${var.region}"
                instance = "${aws_instance.scout2instance.id}"
        }
        depends_on = ["aws_instance.scout2instance"]
}

resource "null_resource" "lambda_make" {
        provisioner "local-exec" {
                command = "echo \"${data.template_file.lambdafunction.rendered}\" > ${var.pythonfile}"
        }
        depends_on = ["aws_instance.scout2instance"]
}

data "archive_file" "lambda_zip" {
        type = "zip"
        source_file = "${var.pythonfile}"
        output_path = "${var.lambdafile}"
        depends_on = ["null_resource.lambda_make"]
}

resource "aws_lambda_function" "startscout" {
        filename = "${var.lambdafile}"
        source_code_hash = "${data.archive_file.lambda_zip.output_base64sha256}"
        function_name = "Scout2_Start"
        role = "${aws_iam_role.lambdarole.arn}"
        description = "Start Scout2 on schedule"
        handler = "lambda_function.lambda_handler"
        runtime = "python2.7"
}

resource "aws_cloudwatch_event_rule" "scout2lambdarun" {
        name = "Scout2Run"
        description = "Starts Scout"
        schedule_expression = "cron(14 14 * * ? *)"
}

resource "aws_cloudwatch_event_target" "scout2lambdatarget" {
        rule = "${aws_cloudwatch_event_rule.scout2lambdarun.name}"
        target_id = "Scout2Start"
        arn = "${aws_lambda_function.startscout.arn}"
}

resource "aws_lambda_permission" "allow_cloudwatch" {
        statement_id = "AllowExecutionofFunction"
        action = "lambda:InvokeFunction"
        function_name = "${aws_lambda_function.startscout.function_name}"
        principal = "events.amazonaws.com"
        source_arn = "${aws_cloudwatch_event_rule.scout2lambdarun.arn}"
}

### Expected Behavior
What should have happened?
A lambda function should have been created and a scheduled task

### Actual Behavior
What actually happened?
All but lambda function was created and the terraform waits 10-15minutes waiting for the Creating Function to finish but it never created it.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. execute from Bash on Ubuntu on Windows 10 shell
2. `terraform apply`

This works from other linux shells.

**Comment by apparentlymart** [comment]
Hi @jonjohnston! Sorry this isn't working as expected.

We are not currently actively supporting running the Linux version of Terraform under the "Bash on Ubuntu on Windows" layer, since there is a native version of Terraform for Windows. If possible, I would suggest trying the native build, to see if the problem still occurs there.

I must admit I don't know why this particular feature would not work in the Linux syscall emulation, but at least if we can see the same bug occur in the native build that will eliminate some complexity and make it more likely that we can debug it.

**Comment by paddycarver** [comment]
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, please feel free to reply to this issue and we'll reopen it. Thanks!
