### ISSUE TITLE
AWS Provider alias declaration

### ISSUE THREAD

**Issue by daaru00** [hashicorp/terraform#15515]
I can't declare and use an AWS provider alias with different region inside a module.

### Terraform Version
v0.9.11

### Terraform Configuration Files
on root level
```hcl
provider "aws" {
    region              = "${var.region}" // eu-west-1
    access_key          = "${var.aws_access_key}"
    secret_key          = "${var.aws_secret_key}"
    allowed_account_ids = [ "${var.account_id}"]

    assume_role {
        role_arn = "arn:aws:iam::${var.account_id}:role/OrganizationAccountAccessRole"
    }
}

provider "aws" {
    alias = "global"
    region = "us-west-1"
}
```
I tried to follow the documentation https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances but I receiving en error:
`No valid credential sources found for AWS Provider.`

So, I duplicate the configuration:
```hcl
provider "aws" {
    region              = "${var.region}" // eu-west-1
    access_key          = "${var.aws_access_key}"
    secret_key          = "${var.aws_secret_key}"
    allowed_account_ids = [ "${var.account_id}"]

    assume_role {
        role_arn = "arn:aws:iam::${var.account_id}:role/OrganizationAccountAccessRole"
    }
}

provider "aws" {
    alias = "global"
    region = "us-west-1"

    access_key          = "${var.aws_access_key}"
    secret_key          = "${var.aws_secret_key}"
    allowed_account_ids = [ "${var.account_id}"]

    assume_role {
        role_arn = "arn:aws:iam::${var.account_id}:role/OrganizationAccountAccessRole"
    }
}
```

### Expected Behavior
In module level I using:
```hcl
resource "aws_route53_health_check" "health_check_ssl" {
  provider = "aws.global"
  cloudwatch_alarm_name = "${aws_cloudwatch_metric_alarm.health_check_alarm_ssl.alarm_name}"
  cloudwatch_alarm_region  = "us-east-1"
  ...
}

resource "aws_cloudwatch_metric_alarm" "health_check_alarm_ssl" {
  provider = "aws.global"
  ....
}
```
I expected **aws_cloudwatch_metric_alarm** use **us-west-1** region

### Actual Behavior
I receiving an error:
`Creating metric alarm failed: ValidationError: Invalid region eu-west-1 specified. Only us-west-1 is supported.`
Seems it's still using "aws" provider instead of "aws.global" alias

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

**Comment by kazeshini178** [comment]
As part of this would it be possible to not require that all fields need to be supplied?
If I have two providers and the only thing I need changed is the region I should only supply the region as in the first code block above.

Or would this need to be a seperate issue?

**Comment by apparentlymart** [comment]
The provider inheritance behavior for child modules was changed in 0.11 to make this sort of usage possible and more predictable. Prior to 0.11 the behavior was rather tricky with aliases.

There is [an overview of the changes](https://www.terraform.io/upgrade-guides/0-11.html#interactions-between-providers-and-modules) in the 0.11 upgrade guide and a more comprehensive description of the new model in [_Providers within Modules_](https://www.terraform.io/docs/modules/usage.html#providers-within-modules).
