### ISSUE TITLE
Feature Requests for terraform workflow

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#15527]
Terraform 0.9.8

I run terraform under my own wrapper script, which provides functionality above/beyond terraform when working in team based scenarios. Until recently for example this provided a locking mechanism for remote statefiles to prevent concurrent terraform executions - however terraform now has this functionality as first class support. 

However using TF for 2 years, I also have the following functionality in the wrapper script which would be useful if terraform supported natively. 

1. Mandate min/max allowed terraform version. When working in teams, if someone upgraded their own terraform and applied some changes, terraform would update the state schema, and then others were forced to upgrade, perhaps prematurely - mandating min/max terraform versions allows for correct-time upgrades of terraform

2. Convert directory hierarchy into single directory. As mentioned in other posts, I find directory hierarchy useful to layout terraform resources as I prefer the one-file-per-resource approach to laying out resources for ease of naming and finding. As terraform doesnt support import or directories, it cant do this forcing you down having multiple resources per file, or millions of files in a single directory, both of which make it awkward to find stuff. 

3. Use environment/workspace directory isolation. Terraform recently supports workspaces, but everything is still run fro m a single directory. I believe (not tested) this prevents concurrent terraforms. The wrapper script I have uses environments/workspaces but prepares different temp directories with the codebase in for each one - thus ensuring that I can concurrently run multiple environment/workspace runs at the same time, without the built-in .terraform temp directory being overwritten

4. Refuse to apply planfiles which are too old. My wrapper script refuses to apply a plan file which is over 5 minutes old (or user-configurable), as it is likely to be out-of-date

5. Remove plan files after theyve been applied - (whether successfully or failed) - Once a plan has been applied cleanup so that it isnt mistakenly applied twice.

6. Force people to use a separate plan, apply workflow, and dont allow them to directly apply without checking whats going to happen first. (too dangerous and often results in destruction of resources). 

7. Be able to assume a role (in aws) first, before doing the subsequent assume-role remote-state - currently terraform still lacks the ability to use chained roles - which is how best practice security often works (so you dont have terraform "god" roles)

Thought I'd mention these, as from experience these really help smooth over the process, and also prevent team-based mistakes happening. A lot of these would be easy to implement within terraform itself.

Other workflows include only having terraform run by CI engines etc. - but some of the above also apply to those workflows

**Comment by kmoe** [comment]
Thanks. You'll be pleased to see that in the intervening years we've implemented at least one of these requests: https://developer.hashicorp.com/terraform/language/settings#specifying-a-required-terraform-version

If you're still interested in the other items, please open each one as a separate issue, checking first for similar issues.
