### ISSUE TITLE
No change forces new resource if variable comes from map

### ISSUE THREAD

**Issue by yangmillstheory** [hashicorp/terraform#15539]
## Terraform Version
```
福 ~/c/a/t/prod (e2e5cee)|public-api✓
±  [i]: terraform -v
Terraform v0.9.11
```
### Terraform Configuration Files
Here's a vim diff; the working copy in the feature branch is on the right, and `master` is on the left:

![image](https://user-images.githubusercontent.com/2729079/28128641-408114f4-66e5-11e7-93fe-49b920489393.png)

### Debug Output
```
-/+ module.email_service.aws_alb_listener_rule.service_v2_host_routing_https
    action.#:                  "1" => "1"
    action.0.target_group_arn: "arn:aws:elasticloadbalancing:us-west-2:565206905967:targetgroup/email-service/c0433fd1bbcdbca6" => "arn:aws:elasticloadbalancing:us-west-2:565206905967:targetgroup/email-service/c0433fd1bbcdbca6"
    action.0.type:             "forward" => "forward"
    arn:                       "arn:aws:elasticloadbalancing:us-west-2:565206905967:listener-rule/app/shared-internal-alb/9fda79ea4ccc9070/9f79acd79221e281/c26c020f040d425b" => "<computed>"
    condition.#:               "1" => "1"
    condition.0.field:         "host-header" => "host-header"
    condition.0.values.#:      "1" => "1"
    condition.0.values.0:      "email-service.arivale.com" => "email-service.arivale.com"
    listener_arn:              "arn:aws:elasticloadbalancing:us-west-2:565206905967:listener/app/shared-internal-alb/9fda79ea4ccc9070/9f79acd79221e281" => "arn:aws:elasticloadbalancing:us-west-2:565206905967:listener/app/shared-internal-alb/9fda79ea4ccc9070/e707db28495cf72e" (forces new resource)
    priority:                  "23" => "23"
```

Note that all the resource values are the same.

### Expected Behavior
No infrastructure changes.

### Actual Behavior
Force recreation.

**Comment by bitbrain** [comment]
This is similar to the issue I reported https://github.com/hashicorp/terraform/issues/15534 where no infrastructure is changed but different syntax/notation causes recreation.

**Comment by yangmillstheory** [comment]
OK, maintainers can feel free to close this if it's a duplicate.

For the record, I got around this by duplicating the block and using `count`.

**Comment by bitbrain** [comment]
I also realised that your listener arn changed:
arn:aws:elasticloadbalancing:us-west-2:565206905967:listener/app/shared-internal-alb/9fda79ea4ccc9070/**9f79acd79221e281**
arn:aws:elasticloadbalancing:us-west-2:565206905967:listener/app/shared-internal-alb/9fda79ea4ccc9070/**e707db28495cf72e**

which possibly causes the re-creation.

**Comment by yangmillstheory** [comment]
🤦‍♂️ 

Let me recheck that this isn't my fault.

**Comment by yangmillstheory** [comment]
Yep, my fault!
