### ISSUE TITLE
Forcing unlock on remote (consul) state

### ISSUE THREAD

**Issue by sherabi** [hashicorp/terraform#15545]
------

### Terraform Version
Terraform v0.9.11.

### Terraform Configuration Files
```hcl
terraform {
  backend "consul" {
    address = "consulnp-uswest2.domain.com"
    path    = "terraform_states/dev_architecture"
    scheme  = "https"
    access_token = "xxxxxx-xxxx-xxx-xxx-xxxx"
    lock = true
  }
}
```

### Debug Output
Error releasing the state lock!

Error message: consul lock was lost

Terraform acquires a lock when accessing your state to prevent others
running Terraform to potentially modify the state at the same time. An
error occurred while releasing this lock. This could mean that the lock
did or did not release properly. If the lock didn't release properly,
Terraform may not be able to run future commands since it'll appear as if
the lock is held.

In this scenario, please call the "force-unlock" command to unlock the
state manually. This is a very dangerous operation since if it is done
erroneously it could result in two people modifying state at the same time.
Only call this command if you're certain that the unlock above failed and
that no one else is holding a lock.

1 error(s) occurred:

* Error releasing the state lock. Please see the longer error message above.

### Panic Output
2017/07/13 10:48:23 [INFO] Terraform version: 0.9.11  
2017/07/13 10:48:23 [INFO] Go runtime version: go1.8.3
2017/07/13 10:48:23 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.9.11/bin/terraform", "force-unlock", "1bbd99c9-36c6-1e7f-9d8d-1c3ff1045189"}
2017/07/13 10:48:23 [DEBUG] Detected home directory from env var: /Users/stopiwal
2017/07/13 10:48:23 [DEBUG] Detected home directory from env var: /Users/stopiwal
2017/07/13 10:48:23 [DEBUG] Attempting to open CLI config file: /Users/stopiwal/.terraformrc
2017/07/13 10:48:23 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/07/13 10:48:23 [DEBUG] Detected home directory from env var: /Users/stopiwal
2017/07/13 10:48:23 [INFO] CLI command args: []string{"force-unlock", "1bbd99c9-36c6-1e7f-9d8d-1c3ff1045189"}
2017/07/13 10:48:23 [DEBUG] command: loading backend config file: /Users/stopiwal/code/terraform-blueprints/mdm-architecture/dev
2017/07/13 10:48:23 [TRACE] Preserving existing state lineage "bd7906a5-947f-4ca8-94fa-d97956c52a51"
2017/07/13 10:48:23 [TRACE] Preserving existing state lineage "bd7906a5-947f-4ca8-94fa-d97956c52a51"
2017/07/13 10:48:23 [INFO] command: backend initialized: *consul.Backend
2017/07/13 10:48:23 [INFO] command: backend *consul.Backend is not enhanced, wrapping in local
2017/07/13 10:48:30 [TRACE] Preserving existing state lineage "df88d449-a1cf-4ed2-b789-7b56e1ded132"
2017/07/13 10:48:30 [TRACE] Preserving existing state lineage "df88d449-a1cf-4ed2-b789-7b56e1ded132"
2017/07/13 10:48:35 [DEBUG] command: asking for input: "Do you really want to force-unlock?"
2017/07/13 10:50:04 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: close of closed channel

goroutine 1 [running]:
github.com/hashicorp/terraform/backend/remote-state/consul.(*RemoteClient).unlock(0xc420856240, 0x7fff5fbff926, 0x24, 0x5d4eba0, 0xc420a75901)
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/backend/remote-state/consul/client.go:321 +0x36d
github.com/hashicorp/terraform/backend/remote-state/consul.(*RemoteClient).Unlock(0xc420856240, 0x7fff5fbff926, 0x24, 0x0, 0x0)
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/backend/remote-state/consul/client.go:315 +0xa3
github.com/hashicorp/terraform/state/remote.(*State).Unlock(0xc420845ad0, 0x7fff5fbff926, 0x24, 0x0, 0x0)
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/state/remote/state.go:97 +0xc7
github.com/hashicorp/terraform/state.(*BackupState).Unlock(0xc420a2b500, 0x7fff5fbff926, 0x24, 0x3, 0x0)
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/state/backup.go:60 +0x48
github.com/hashicorp/terraform/command.(*UnlockCommand).Run(0xc4203ce480, 0xc42000e140, 0x1, 0x1, 0xc42047a7f0)
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/command/unlock.go:99 +0x51c
github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc4200d4240, 0xc420528930, 0xc42066bcd0, 0x1)
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/vendor/github.com/mitchellh/cli/cli.go:154 +0x1a8
main.wrappedMain(0x0)
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/main.go:192 +0xb82
main.realMain(0x0)
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/main.go:95 +0xbb
main.main()
	/private/tmp/terraform-20170703-39795-y04kw2/terraform-0.9.11/src/github.com/hashicorp/terraform/main.go:31 +0x38

### Expected Behavior
Lock should release without issues

### Actual Behavior
Crashed when lock was forced to be released

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan` -> Error releasing the state lock!

Error message: consul lock was lost

2. `terraform force-unlock 1bbd99c9-36c6-1e7f-9d8d-1c3ff1045189`

### Important Factoids
NOPE

### References
Could not find one

**Comment by sherabi** [comment]
The issue was resolved by increasing the idle timeout on the ELB fronting our consul cluster.

Terraform should keep the connection active to consul by sending some ping/pong so that ELB wont assume the connection as idle.

**Comment by jbardin** [comment]
@sherabi,

Thanks for the info here. I think you've shed some light on what other user's may be doing that is causing them to drop consul locks. While terraform does continually update the consul session, the KV request to watch the lock is a long blocking request, and out of terraform's control. 

The force-unlock command doesn't really apply to consul, so we should probably fix up that message wording a bit.

The crash seen here, as well as the susceptibility to an LB/proxy dropping the connection should be fixed in the next major release.
