### ISSUE TITLE
AWS>SNS>lambda>SMTP>notification

### ISSUE THREAD

**Issue by Madhusudhan-Yerragudi** [hashicorp/terraform#15551]
Hi ..
I have created an alarm on the RDS and set the alarm with SNS, SNS was set up with target as aws lambda and I am using a script to collect the data from SNS and trigger a mail through my gmail. But its not working. Can any one help me on this.
Thanks,
Madhusudhan

**Comment by stack72** [comment]
Hi @Madhusudhan-Yerragudi 

Apologies you are not getting the behaviour you are expecting. I would suggest that you visit one of the places on our [community](https://www.terraform.io/community.html) page as there will be users who do this type of thing more often

GitHub issues tend to not be looked at outside of bugs or feature enhancements

Sorry to not be more help

Paul
