### ISSUE TITLE
Pre-Provisioner

### ISSUE THREAD

**Issue by sjwl** [hashicorp/terraform#15558]
Would like the ability to run a `local-exec` provisioner within the configuration block of a resource, _before_ the resource creation is started.

My use case is to run a duplicate IP test by using `local-exec` ping to an IP will be used to create a bare metal machine resource, and fail the pipeline should the ping actually get a response.

The current workaround is to use `null_resource`, unfortunately it only works on _brand new_ deployments.  A partial deployment where the machine is already running, and adding the `null_resource` will cause the `null_resource` to run the test, and of course since the machine is already running the test will result in a false positive as the ping will detect a response.

**Comment by pkolyvas** [comment]
Hey @sjwl, I'm doing a cleanup of older issues. This feels, very strongly, like it's a within the family of partial or progressive apply, so I'm going to close this against #4149. 

We're not yet tackling #4149, but I am adding to the (unquestionable?) body of evidence for this need. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
