### ISSUE TITLE
Custom Providers failing to import on Windows

### ISSUE THREAD

**Issue by quaeritate** [hashicorp/terraform#15578]
Custom providers with Terraform on Windows are not able to be imported. I can use the same custom provider on Ubuntu and OSX.

Sample Error Message

```
Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* cidr (any version)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/windows_amd64
```
In this example I used in an effort to force it to load the provider.
`terraform init -plugin-dir ./plugins -verify-plugins=false`

I also forced terraform to be not able to get the aws module to confirm it was then getting the module from the location I was providing.
```
Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* aws (any version)
* cidr (any version)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/windows_amd64
```

Before this more in depth testing I tired putting the module in the following places:
* The root directory of the project
* <project_root>\terraform.d\plugins\windows_amd64
* %userprofile%\appdata\roaming\terraform.d\plugins\windows_amd64

On Ubuntu and OSX I just placed the compiled binary in the root of the project.

### Terraform Version
Terraform v0.10.0-beta2-dev

### Provider(s) I am compiling
https://github.com/moofish32/terraform-provider-cidr
Please note there is a naming problem in this project that prevents go get from working correctly.

I also tried with this provider as a test with the same result. This provider needed a little fixing to compile as well.
https://github.com/palmertime/terraform-provider-virtualbox

**Comment by apparentlymart** [comment]
Hi @quaeritate! Sorry for this issue, and thanks for reporting it.

It looks like there's a bug in the code that parses the filenames of provider plugins, where the `.exe` extension was being included in the version number. We didn't catch this because for the official releases the filenames have an extra segment for the plugin protocol version, which isn't included on locally-built plugins. Thus for your `cidr` provider it's being understood as being either a plugin called `cidr.exe` or a plugin called `cidr` whose version number is something like `0.0.1.exe`, depending on how exactly you have the file named.

I have a fix which I'm finishing up now. We'll get it merged before the next release. Thanks again for trying this out and reporting this bug!

**Comment by quaeritate** [comment]
Hi @apparentlymart 

Thanks for the speedy response. I can confirm that renaming the file allows the plugin to be imported
`terraform-provider-cidr_v0.1_x4.exe`

I did need to have the _x4 as well to get it to work. Looking forward to the next release.

**Comment by Gentyk** [comment]
You can also it read in https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
