### ISSUE TITLE
Additional private ip addresses for aws_instance

### ISSUE THREAD

**Issue by btsteve** [hashicorp/terraform#1557]
Could you please expose adding additional ip addresses to an instance at creation time. This is supported via the api. Instances can have a different number of private ip addresses per ENI. For example I need 10 private ip addresses on an newly created instance. I should be able to add them with out having to attach another ENI if the instance size allows. 

See Last Example:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html

ENI Limits:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html

**Comment by davidblewett** [comment]
+1. This is useful to have a stable IP That can be used to coordinate current PostgreSQL master, for instance.

**Comment by marekrogala** [comment]
:+1: would be really helpful

**Comment by PurrBiscuit** [comment]
:+1:

**Comment by iceycake** [comment]
+1 on this feature.

**Comment by lussier** [comment]
+1, I currently rely on scripts on the side to achieve that result.

**Comment by Shruti29** [comment]
+1 on this. Badly needed

**Comment by attenda-pjaquenoud** [comment]
+1 please please

**Comment by kamaltherocky** [comment]
+1

**Comment by opticpow** [comment]
+1

**Comment by Armand1989** [comment]
+1 This would be very helpful.

**Comment by lbernail** [comment]
+1, it would great and avoid using workarounds (local-exec script to add secondary IP for instance)

**Comment by lisfo4ka** [comment]
+1

**Comment by pmuller** [comment]
One more +1. :)

**Comment by ChrisFernandez** [comment]
and yet one more +1

**Comment by Purple90** [comment]
+1

**Comment by apparentlymart** [comment]
Hi @btsteve and everyone else who has plus-oned this issue! Thanks for this feature request, and sorry for letting it sit ignored for so long.

While we'd love to support this, we (the Terraform team) don't have any short-term plans to implement this ourselves. We're trying to prune stale feature requests (that aren't likely to be addressed soon) by closing them.

If anyone is still interested in having Terraform support this, we would gladly review a pull request.
