### ISSUE TITLE
allow hidden .tf.json somehow

### ISSUE THREAD

**Issue by dradetsky** [hashicorp/terraform#15580]
I submitted a pr #15452 because, for reasons described in the pr, I want terraform to pick up hidden .tf.json files.

Nobody's taken any notice of this pr (not sure why), but I'm wondering if there's some reason why it wouldn't be acceptable, or other changes that would make it acceptable. For example, I could conceivably add a command-line flag which would guard consumption of hidden files (perhaps it could take a glob or regexp arg to perform arbitrary input file restrictions), so that existing setups which have hidden files for whatever reason are not affected.

**Comment by jbardin** [comment]
Hi @dradetsky,

I responded in the PR itself, but if you have any other questions feel free to use this issue, as it makes for an easier interface.

**Comment by dradetsky** [comment]
>>> Sorry about the lack of response here

No big deal. FWIW, if you had immediately stuck some tags on it, I'd have thought, "Okay, somebody has noticed this, but as I would have expected, they have more urgent priorities" and probably would have been less annoyed by the fact that nobody responded very quickly. But maybe you guys don't like just tag stuff like that, I dunno.

>>> adding an exception to load a particular hidden file creates some non-obvious behavior

Just in case I didn't express myself well, I don't want to load a particular file `.foobar.tf.json`, I want to disable the filtering out of hidden files. As I say, this could involve a new flag `-allow-hidden` or something (although I haven't actually figured out how to add a flag). So in theory, it wouldn't change the behavior of terraform for anyone who hadn't explicitly requested such a change.

Thanks for the github tips btw.

**Comment by jbardin** [comment]
Admittedly we do tend to fall behind on triaging PRs, which should hopefully change as we better implement tooling to handle the amount of incoming requests we have coming from github.

Yes, I understand the request to load the hidden files, and it could be behind a flag to prevent effecting existing users. I would like to wait until we release some of the HCL and configuration cleanup we have planned. A better workflow might naturally fall out of that before we commit to something that amounts to only a partial solution for a workaround. 

Thanks!
-James
