### ISSUE TITLE
the file provisioner doesn't support ~/foo

### ISSUE THREAD

**Issue by failshell** [hashicorp/terraform#1559]
The file provisioner doesn't seem to understand the ~ path.

With the following config:

~~~ text
  provisioner "file" {
    source = "~/bar"
    destination = "~/bar"
  }
~~~

I get the folllowing error:

~~~ text
* stat ~/bar: no such file or directory
* 1 error(s) occurred:
~~~

I'm guessing something like [1339](https://github.com/hashicorp/terraform/pull/1338) is needed.

**Comment by phinze** [comment]
Thanks for the report - we'll get this looked at - shouldn't be too bad.

**Comment by arubis** [comment]
I've been working around this by specifying absolute paths (including in accompanying usage documentation), but would love to see this improvement!

**Comment by mitchellh** [comment]
We added this feature to `remote-exec` so it shouldn't be hard to do for `file`. Will do!
