### ISSUE TITLE
Terraform count seems to be off

### ISSUE THREAD

**Issue by sysadmiral** [hashicorp/terraform#15602]
I'll add more information later today but whenever I run `terraform plan` it seems to count double the number of changes that will actually happen.

For example, if three resources are to be added in the changes summary at the end of the run it will say   `Plan: 6 to add,...`.

```bash
$ terraform version
Terraform v0.9.11
```

**Comment by jbardin** [comment]
Hi @sysadmiral,

Thanks for reporting the issue!
This was tracked from #14905, fixed in #15344, and will be in the 0.10 release.
