### ISSUE TITLE
List Variabe

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#1561]
Maybe I'm not reading the docs correctly, however, it would be help to be able to define a list of let's say cidr blocks as a variable so that the variable could then be passed to a security group.  Is this possible now? 

```
variable "allow_ips" {
   default = ["22.22.22.22/32", "11,11,11,11/32"]
}

resource "aws_security_group" "mygroup"{
....
  ingress {
  ...
  cidr_blocks = "${var.allow_ips}"
  }
}
```

**Comment by mitchellh** [comment]
This isn't allowed. Please use `split/join`, which are documented in the interpolation section. Sorry! There is another issue for this: #1212

**Comment by franklinwise** [comment]
Thanks @mitchellh
