### ISSUE TITLE
Separated Authentication for Module Sources

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#15614]
(This was split out of #1439, to capture one of the use-cases discussed there.)

----

Currently all of the information for requesting a module gets packed into the source string, which cannot be parameterized:

```hcl
module "foo" {
  source = "github.com/hashicorp/example"
}
```

Some of [the supported module sources](https://www.terraform.io/docs/modules/sources.html) support or require authentication. For example, private repositories on GitHub, Bitbucket, and other VCS hosts require user credentials to access. Currently such credentials must be packed into the source string:

```hcl
module "private-infra" {
  source = "git::https://MACHINE-USER:MACHINE-PASS@github.com/org/privatemodules//modules/foo"
}
```

This is problematic for at least two reasons:
* A secret is embedded in a place where it can't easily be detected and redacted, causing it to get checked into version control, printed in log output, etc.
* It can't easily be changed so that different users can each authenticate as themselves to the repository. Either every user must share the same credentials (which violates sensible security policy) or each user must tweak the configuration somehow before applying, e.g. in wrapper scripts.

In all other cases we generally recommend that per-user credentials be provided via environment variables, since that way they can easily be kept out of config, plans and state, and users can use general third-party tools to securely manage their credentials in the environment.

Putting credentials in the environment is not always ideal, since it can cause problems if e.g. different credentials are required to access different resources in the same repository or if Terraform is running an untrustworthy program as a provisioner or external data source. Therefore it's also desirable to also be able to place credentials in a file that lives _outside_ of the main configuration, ideally allowing credentials to be shared between many separate Terraform configurations so they don't need to be spread over many files on disk.

---

Such a solution might generalize well as a new solution to more easily manage credentials for _providers_, to solve similar problems for those; today in more complex cases people end up passing credentials in Terraform variables, but it's undesirable to use variables for per-user things since they get embedded in plans and are hard to use in automation scenarios, so it would be nice to have a separation between provider _settings_ and provider _credentials_ to get similar benefits as described above. The focus of this issue is on module sources in particular but if we can find a general solution then all the better.

**Comment by pll** [comment]
+1 !

This would be a huge boost to our automation!  Currently, we have to parse our terraform module references with a python wrapper to get this functionality, which is sub-optimal! Very happy see more discussion on this issue!

**Comment by ljsommer** [comment]
Yeah this is a big deal, being able to authenticate against a secured repository is pretty necessary.

**Comment by fstuck37** [comment]
+1
Would really like to see this too.
-Fred

**Comment by apparentlymart** [comment]
Hi all!

We're still thinking about how best to approach this, since the needs of each different module source type are different.

---

Git presents an interesting challenge because of its decentralized nature. A single "git credential" across all repositories isn't appropriate because each git server has its own separate authentication mechanism, but it's also not really right to have each _module block_ have its own credentials because in practice many modules will come from the same source and should thus share a set of credentials across all of them.

During my research, I've studied how Git handles credentials _in theory_. I'm curious as to whether anyone has tried using Git's built in credentials store mechanisms and thus whether they can share some pros and cons of that approach from their practical experience.

For example, using [the local file credentials store](https://git-scm.com/docs/git-credential-store) allows a centrally-maintained repository of credentials for different hostnames which can then be used both when running `git` directly _and_ when Terraform runs `git` as part of module installation. _In principle_ it feels "right" to maintain the per-user credentials in a central place on their system rather than setting it separately for each Terraform configuration, but I'm sure that in practice there are some disadvantages to that approach that I'd love to hear more about to inform our direction here.

It looks like for those on Mac OS X or Windows there are alternative credentials implementations that use the secure credential storage provided by the OS, which can get a similar result without storing the credentials in cleartext on disk. (See [_Credential Storage_](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) in the Git Book for more info.)

---

We've also been recently presented with this problem when extending our Terraform Registry support to allow non-public registries that require authentication. This presents similar challenges as git where it's not sufficient to have a single credential set for all modules (they may be coming from _different_ registries) but often many modules share the _same_ credentials.

We ended up taking a similar approach to Git of maintaining a configuration table that maps each hostname to some credentials in a file outside of the main configuration, again with the idea that each user will have zero or one sets of credentials for each host that should span across _all_ configurations.

In our experiments with that so far we've found it to work pretty well, which was the main reason why I was curious as to whether anyone had real-world experience trying to adopt a similar approach with git itself.

**Comment by ayarmoluk17** [comment]
Just wanted to add that authenticating to private repo on github works just fine for us with git credentials stored in keychain on macOs. Terrafrom version 0.10.8

```
# .gitconfig
...
[credential]
	helper = osxkeychain
	useHttpPath = true
...
```
```
# main.tf
module "example" {
  source = "github.com/privaterepo/terraform-modules//subdir/module"
}
```

**Comment by gordonbondon** [comment]
Just wanted to add that authenticating to private repo on github works just fine for us with git credentials stored in keychain on macOs. Terrafrom version 0.10.8

```
# .gitconfig
...
[credential]
	helper = osxkeychain
	useHttpPath = true
...
```
```
# main.tf
module "example" {
  source = "github.com/privaterepo/terraform-modules//subdir/module"
}
```

**Comment by apparentlymart** [comment]
Hi all,

As you may have seen, we released Terraform v0.11.0 yesterday with support for authenticating to private module _registries_ (using Terraform's own registry protocol) via credentials either provided statically in a configuration file or using git-style credentials helpers (though we haven't yet written any such credentials helpers; these should follow later as use-cases emerge.)

We'd also done some more experimentation along the lines of what @gordonbondon reported here and came to the conclusion that it is better to make use of git's existing credentials mechanisms -- which can then be configured once on your system and used across _all_ git-related software -- rather than to invent something proprietary for Terraform.

Therefore we're planning to document on the module sources page how to configure credentials for each source type that supports credentials, such that they are managed outside the Terraform configuration altogether. The OS X keychain itself is of course not appropriate for automation on a remote server, but other credential stores that fetch credentials from locations such as environment variables, specialized secure credential stores like [HashiCorp Vault](https://www.vaultproject.io/), etc are possible and more automation-appropriate.

For those who are already inserting credentials directly into the Terraform config using wrapper scripts, presumably their risk profile tolerates credentials being stored temporarily on local disk and so using git's built-in file-based credential helper (simply called `store`) with a temporary file generated by the wrapper script should be equivalent, from a security standpoint, to rewriting the Terraform configuration files.

**Comment by pixelicous** [comment]
@apparentlymart What is the latest update on this matter?

**Comment by pixelicous** [comment]
What about local interpolations in source?? Without using git

**Comment by trinitronx** [comment]
This problem, combined with docker/for-mac#410 means that `ssh-agent` based auth for private `git` repo sources is broken when using `hashicorp/terraform:0.11.3` docker image on OSX.

In my team's chosen tools & workflow, this set of problems makes using this image unworkable (death by 1000 paper cuts style).  Yes, I have tried to convince them to use `docker-machine`, but they refuse because it's more complicated due to separate VM & need to mount socket twice to get it into the "container-in-vm".

Basically, they want to use OSX native docker-for-mac, which doesn't support `SSH_AUTH_SOCK` socket volume mounts due to the osxfs bug above.  Because of minimalist CI build slaves, we must use a docker image containing `terraform`, wrapping terraform things in `Makefile` targets that bootstrap terraform via docker image.  Needing it to work both in CI and on developer laptops is a must, but this set of requirements & problems makes the setup impossible.  The other workaround was to use `HTTPS` protocol git repos, but this does not work due to Terraform's interpolation syntax being not supported in `module`'s `source` argument.

**Comment by bencoughlan** [comment]
RE: What about local interpolations in source?? Without using git @pixelicous  

Any update on this? Would be super handy to have, as I'm trying to give users the option to spin up services on various platforms, i.e. the "source module" will be fundamentally different for AWS vs VMware, but the item requires the same variables in both cases, the variable "$platform" would decide if it hit's the AWS utility or the VMware, or GCP, azure, whatever... 

i.e. 
module "rabbit_cluster" {
  source              = "../../../modules/rabbit_cluster/${var.platform}"
  data_disk_size      = "${var.data_disk_size}"
  root_disk_size      = "${var.root_disk_size}"
}

Cheers, 
Ben

**Comment by akvadrako** [comment]
It would also be nice if you could override the *source* path outside the tf file.

**Comment by pixelicous** [comment]
@bencoughlan @akvadrako 

I think we can forget about it, there were a couple of issues opened in the past where the terraform staff replied and said its going to change too many things under the hood.
They prefer to find all sort of "creative" solutions to a problem which is a symptom, the root cause is actually a bad design of the software, thus changing it now would cost them too much.
Unfortunately i don't see any other provisioning software that is going to come and replace it any time soon.

So you end up with terraform files that do all sorts of hacks + wrapper script to get the desired state...

**Comment by ziggythehamster** [comment]
Kind of a goofy workaround to this for some people might be to mirror releases/branches/tags/whatever to S3 and control access with S3 ACLs and then use S3 URLs instead of git URLs. This of course fails completely if you need two sets of S3 credentials besides what is in the `AWS_*` variables.

**Comment by h3adache** [comment]
Being able to use variables in `module.source` would help with ci/cd.
You can export an environment variable in gitlab for the ci token

```
TF_VAR_ci_job_token: ${CI_JOB_TOKEN}
```

But I cannot use it atm because I can't use the variable in my `module.source`

**Comment by apparentlymart** [comment]
Hi all,

Further to my last comment, we've since documented the authentication mechanisms for each source that has them on [the Module Sources page](https://www.terraform.io/docs/modules/sources.html). This includes links to relevant documentation for how to set up credentials using the native mechanisms for each source, so that you don't need to do anything Terraform-specific at all.

Setting these up in a Terraform-agnostic way means you're also configuring for any other program that uses the same source. For example, if you configure Git Credentials Storage on your system then it'll work for Terraform, for direct executions of `git clone`,, for other similar tools that run Git like `npm`, `go get`, etc.

We don't think Terraform-specific reinventions of these well-documented mechanisms are a good idea because in previous situations where Terraform has deviated from usual patterns it's tended to cause confusion and problems in the long term; we'd always rather follow an existing convention where it's possible to do so, so that you can easily integrate Terraform into an environment that's using similar tools for other reasons.

It is true that some of these source types have credentials mechanisms that are less convenient to set up than others. In some cases that's _necessary_ complexity due to the decentralized nature of the protocol, but in other cases you may wish to take feedback to the upstream project's development team so that any streamlining of that workflow can benefit all users of that system, not just Terraform users.

Since we have now completed the documentation for how to authenticate to each of the module sources, I'm going to close this out. If you have feedback on anything that is unclear or not specific enough in that documentation, please feel free to open a new issue or pull request about it and we can improve the documentation iteratively.
