### ISSUE TITLE
self doesn't work in aws_security_group

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#1562]
It's necessary in AWS to all members of a group to talk to each other, thus the following would be helpful; it's currently an error.

```
	ingress {
		from_port = 9300
		to_port = 9300
		protocol = "tcp"
		security_groups = ["${self.id}"]
	}
```

```
* resource 'aws_security_group.elasticsearch_master' config: cannot contain self-reference self.id
```

**Comment by mitchellh** [comment]
You can only use `self` in provisioners currently. Sorry!

**Comment by u2mejc** [comment]
This is difficult to search when jogging your memory and this issue comes up still, the answer is to use the `self` argument today: https://www.terraform.io/docs/providers/aws/r/security_group_rule.html#self
