### ISSUE TITLE
Failed to load root config module

### ISSUE THREAD

**Issue by ss6851** [hashicorp/terraform#15621]
I am using `Terraform v0.9.11`. I want to work with the existing infrastructure on AWS. For that I am using ` terraform import`.  I tried to find the existing solution and implemented the method suggested in `Docs` and the following link: 
`https://github.com/hashicorp/terraform/issues/15608`
After importing the resources from AWS, I made necessary changes in my configuration file as follows:
```
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region="${var.region}"
 }

resource "aws_instance" "windows"{
  ami = "ami-1f18367f"
  instance_type = "t2.micro"
  associate_public_ip_address= true
  availability_zone= us-west-1b
  disable_api_termination= false
  ebs_block_device= 0
  ebs_optimized= false
  ephemeral_block_device= 0
  iam_instance_profile= 
  id= i-0a7bbdea0a0ea5e08
  instance_state= "running"
  instance_type= t2.micro
  ipv6_addresses= 0
  key_name= test
  monitoring= false
  network_interface= 0
  network_interface_id= eni-84697f84
  primary_network_interface_id= eni-84697f84
  private_dns= ip-172-31-1-95.us-west-1.compute.internal
  private_ip= 172.31.1.95
  public_dns= ec2-54-219-138-62.us-west-1.compute.amazonaws.com
  public_ip= 54.219.138.62
  root_block_device= 1
  root_block_device.0.delete_on_termination= true
  root_block_device.0.iops= 100
  root_block_device.0.volume_size= 30
  root_block_device.0.volume_type= gp2
  security_groups= 0
  source_dest_check= true
  subnet_id= subnet-fd0648a5
  tags= 0
  tenancy= default
  volume_tags= 0
  vpc_security_group_ids= 1
  vpc_security_group_ids.1607628289= sg-47f00f21
 }
```
After making the above necessary changes in the configuration file, I see the following error when I try to run `terraform plan -destroy`:
```Failed to load root config module: Error parsing /path/to/dir/windows.tf: At 11:22  Unknown token: 11:22 IDENT us-west-1b```
I tried googling the solution, but couldn't find anything related. Can somebody help?

**Comment by apparentlymart** [comment]
Hi @ss6851! Sorry this didn't work as expected.

The problem here is that this is not correct syntax for configuration, in a few different ways:

---

Strings within the configuration need to be quoted. For example:

```hcl
  instance_type= "t2.micro"
```

---

Some of the attributes here are expressed as nested block structures in configuration. For example, for `root_block_device`:

```hcl
  root_block_device {
    delete_on_termination = true
    iops                  = 100
    volume_size           = 30
    volume_type           = "gp2"
  }
```

---

Some of the attributes are lists. For example, `vpc_security_group_ids`:

```
  vpc_security_group_ids = ["sg-47f00f21"]
```

---

The documentation describes the expected values for each attribute. You should also omit attributes that are listed under "Attributes" in the docs, since these are decided by the API itself rather than by config.

If you're importing a number of different resources that are related to one another, note also that it's best to replace certain hard-coded ids with interpolation expressions so that Terraform can understand the dependencies between the resources.

**Comment by ss6851** [comment]
Thank you very much for providing the detailed answer. Can you please do a little more and provide a link to `Attributes` in Docs.

**Comment by apparentlymart** [comment]
Each resource has its own docs, but since your question was about `aws_instance` you can find its docs here:
https://www.terraform.io/docs/providers/aws/r/instance.html

**Comment by ss6851** [comment]
Thank you very much for the quick reply. I have made the necessary changes in the configuration file as follows:
```
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region="${var.region}"
 }

resource "aws_instance" "windows"{
  ami = "ami-1f18367f"
  instance_type = "t2.micro"
  associate_public_ip_address= true
  disable_api_termination= false
  ebs_block_device= 0
  ebs_optimized= false
  ephemeral_block_device= 0
  instance_state= "running"
  ipv6_addresses= 0
  monitoring= false
  network_interface= 0
  root_block_device= 1
  root_block_device {
    delete_on_termination= true
    iops= 100
    volume_size= 30
    volume_type= "gp2"
  }
  source_dest_check= true
  tags= 0
  tenancy= "default"
  volume_tags= 0
 }
```
It's still not working when I execute `terraform plan -destroy` and throws the following error:
```
Failed to load root config module: Error loading /home/sukhpreet/Downloads/tform/windows.tf: Error reading config for aws_instance[windows]: At 20:21: root.root_block_device: unknown type *ast.ObjectType
```

**Comment by apparentlymart** [comment]
The `root_block_device = 1` line is not valid, since this argument does not expect a number.

**Comment by ss6851** [comment]
Wow! Thank you very much for the reply and being patient with me. I made the above changes in the configuration file and executed the command `terraform plan -destroy`; it gave the following error:
```
7 error(s) occurred:

* aws_instance.windows: "instance_state": this field cannot be set
* aws_instance.windows: "network_interface": conflicts with associate_public_ip_address (true)
* aws_instance.windows: ebs_block_device: should be a list
* aws_instance.windows: ephemeral_block_device: should be a list
* aws_instance.windows: ipv6_addresses: should be a list
* aws_instance.windows: tags: should be a map
* aws_instance.windows: volume_tags: should be a map
```
I removed all the parameters that were mentioned in the above errors, and now my configuration looks like the following:
```
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region="${var.region}"
 }

resource "aws_instance" "windows"{
  ami = "ami-1f18367f"
  instance_type = "t2.micro"
  associate_public_ip_address= true
  disable_api_termination= false
  ebs_optimized= false
  monitoring= false
  root_block_device {
    delete_on_termination= true
    iops= 100
    volume_size= 30
    volume_type= "gp2"
  }
  source_dest_check= true
  tenancy= "default"
  
 }
```
Now when I execute `terraform plan -destroy` it still treats the instance as orphan and plans to destroy it as displayed in the following output:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_instance.windows: Refreshing state... (ID: i-0a7bbdea0a0ea5e08)
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

- aws_instance.windows


Plan: 0 to add, 0 to change, 1 to destroy.
```

**Comment by apparentlymart** [comment]
Hi @ss6851,

I'm not sure I follow what's going on here. You mentioned that you ran `terraform plan -destroy`, which causes Terraform to make a plan to destroy all resources that exist in the current state, ignoring the configuration. So the plan output you saw here is expected.

If you want to see a normal _update_ plan, showing differences between configuration and current state, you can just run `terraform plan` with no arguments.

After importing a resource it's likely that the configuration won't exactly match the state on your first try, so you will probably see Terraform detect some changes. You can use the plan output as a guide to update the configuration so it matches, at which point the plan should be empty (no changes required).

**Comment by ss6851** [comment]
Hi Matt!

It worked! Thank you very much for your patience and help.
