### ISSUE TITLE
Does Terraform v0.7.13 support terraform state rm <module.resource>?

### ISSUE THREAD

**Issue by dsalazar-carecloud** [hashicorp/terraform#15625]
I'm sorry for the potentially dumb question but I just wanted to know if my outdated terraform version 0.7.13, i know i know, supports the removal of the state of a specific resource?  I just want to determine if the complete removal of the whole state is because of the version that I am using or because of user error?  I pretty much ran `terraform state rm module.resource` and poof I'm back to 0 state.

**Comment by jbardin** [comment]
Hi @dsalazar-carecloud,

You're correct that it should work as you expect, and while your release is quite old, I don't see any obvious changes to that code since then.

Are you sure you didn't execute 'terraform state rm` without any arguments at one point? Do you have an example that I can use to reproduce the issue?

**Comment by dsalazar-carecloud** [comment]
Good morning @jbardin.  Thank you for your response.  Unfortunately I can only confirm the command that I ran.  It was against an amazon host generated as a result of an aws_instance combined with the count parameter.  I wanted to start swapping out cluster nodes little by little.  I know it's not much to go with but it's all I've got.  Fortunately I was able to mitigate the blown away state by doing the diff between a backup and current state.

**Comment by jbardin** [comment]
Thanks for following up.

Without a reproduction, and since 0.7 is no longer supported, all I can is that it should have worked as intended. There's not much else we can do here, but if you encounter this again feel free to post here, or file a new issue referencing a newer Terraform version.
