### ISSUE TITLE
concat doesn't work as expected when calling a custom module

### ISSUE THREAD

**Issue by tanhaa** [hashicorp/terraform#15627]
### Terraform Version
0.9.11

### Terraform Configuration Files
I'm using a custom module for EC2 instance which expects a variable named: "ec2_security_groups" (a list) and passes it on to "vpc_security_group_ids" 

This works:
```hcl
variable "security_groups" {
    default = ["sg-321c56ad"]
}

module "search_ec2_instance" {
  source                  = "git-repo"
  app_name                = "${var.app_name}"
  env                     = "${var.env}"
  product                 = "${var.product}"
  role                    = "${var.role}"
  ec2_cortex_tags         = "${var.cortex_tags}"
  ec2_number_of_instances = "${var.es_number_of_nodes}"
  ec2_instance_type       = "${var.instance_type}"
  ec2_subnets             = "${var.subnets}"
  ec2_security_groups     = "${var.security_groups}"
  ec2_volume_size         = 20
}
```

while this does not where I define a security group and want to concat it to the list I'm sending to my module:

```hcl
resource "aws_security_group" "search_es" {
    name = "search_es"
    vpc_id = "${var.vpc_id}"
}

module "search_ec2_instance" {
  source                  = "git-repo"
  app_name                = "${var.app_name}"
  env                     = "${var.env}"
  product                 = "${var.product}"
  role                    = "${var.role}"
  ec2_cortex_tags         = "${var.cortex_tags}"
  ec2_number_of_instances = "${var.es_number_of_nodes}"
  ec2_instance_type       = "${var.instance_type}"
  ec2_subnets             = "${var.subnets}"
  ec2_security_groups     = "${concat(var.security_groups, list(aws_security_group.search_es.id))}"
  ec2_volume_size         = 20
}
```

### Expected Behavior
For concat to pass a concatenated list to the module.  Similar to what it does in the console:
```
> concat(var.security_groups, list(aws_security_group.search_es.id))
[
  sg-321c56ad,
  sg-9d3f3aed
]
>
```

### Actual Behavior
```
 $ terraform plan
1 error(s) occurred:

* module.search_ec2_instance.aws_instance.ec2_instance: vpc_security_group_ids: should be a list
```

**Comment by dberuben** [comment]
👍

**Comment by apparentlymart** [comment]
Hi @tanhaa! Sorry for the strange behavior here.

When you ran `terraform plan` here, was the `aws_security_group.search_es` resource being created for the first time, or did it already exist?

I ask this because Terraform has some special behaviors to deal with values it doesn't know yet, such as the id of a resource that hasn't yet been created, and I suspect that this bug may be an error in that special handling causing the value to be misinterpreted as not being a list.

**Comment by tanhaa** [comment]
the security group had already ran and existed beforehand, the state should have had the id of the security group.  That's why I was able to run the commands in a console to see if they worked fine.  I have tried many different ways, but I always get the same error.  Some of the ways I have tried that result in the same error are: 
`${concat(var.security_groups, (aws_security_group.search_es.id))}`
`["${concat(var.security_groups, list(aws_security_group.search_es.id))}"]` 

These didn't work either.  Note that security group has been created while I kept running into these errors.

**Comment by apparentlymart** [comment]
@tanhaa looking again at your config, I notice that your `security_groups` variable doesn't have `type` specified, which means it'd default to expecting a single string value (or any other value that can convert to a string).

Do you see any difference in behavior if you explicitly mark the variable as a list?

```hcl
variable "security_groups" {
  type    = "list"
  default = ["sg-321c56ad"]
}
```

In future we hope to phase out this need to explicitly specify the type and have Terraform infer it, but for various reasons today Terraform isn't always able to do that inference, and so this declaration helps the validator understand the variable types.

**Comment by tanhaa** [comment]
I have already tried that as well.  Explicitly defining the type generates the same error. 

Note that this works: 
```
 ec2_security_groups     = "${var.security_groups}"
```
```
variable "security_groups" {
    default = ["sg-321c56ad", "sg-9d3f3aed"] 
}
```

As you can see, i didn't explicitly say anything about this variable being a "list" and it worked.

**Comment by tanhaa** [comment]
just doing a followup, this problem still exists with version 0.10.3

**Comment by apparentlymart** [comment]
Hi @tanhaa! Sorry for the long silence here.

This issue has the same root cause as #12263, which has now been addressed in `master` in preparation for the forthcoming v0.12.0 release, and so I'm going to close this out.

Thanks for reporting it, and thanks for your patience while we figured out what was going on here.
