### ISSUE TITLE
S3 backend with multiple statefiles does not work correctly

### ISSUE THREAD

**Issue by bitbrain** [hashicorp/terraform#15648]
### Terraform Version
`Terraform v0.9.10`

### Terraform Configuration Files
**application-a bucket tfvars**
```hcl
bucket = "my-bucket"
key = "my/path/test1/terraform.tfstate"
encrypt = true
dynamodb_table = "my-table"
region = "eu-west-1"
```
**application-b bucket tfvars**
```hcl
bucket = "my-bucket"
key = "my/path/test2/terraform.tfstate"
encrypt = true
dynamodb_table = "my-table"
region = "eu-west-1"
```
**main.tf**
```hcl
terraform {
  backend "s3" {}
}

provider "aws" {
  region = "eu-west-1"
}
```

### Debug Output

For app-a:
```
Initializing the backend...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.
```

For app-b:
```
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.

Error inspecting state in "s3": NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: <id>, host id: <id>

Prior to changing backends, Terraform inspects the source and destination
states to determine what kind of migration steps need to be taken, if any.
Terraform failed to load the states. The data in both the source and the
destination remain unmodified. Please resolve the above error and try again.
```

### Expected Behavior
Both states should get persisted correctly.

### Actual Behavior
Only the first state can be accessed. The second state file throws the error shown.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `cd /app-a && terraform init ---backend-config="s3.tfvars" && terraform apply`
1. `cd /app-b && terraform init ---backend-config="s3.tfvars" && terraform apply`

### Important Factoids
I have created the bucket in AWS and also the DynamoDB table. After the first app gets initialised via S3 it creates the statefile correctly in the bucket under the given path and also creates a DynamoDB lock entry in the table.

When running against the same bucket (but different path) it fails. Interesting is that according to the error message the "backend" config has changed, however the bucket can not be found (so how does Terraform know that something has changed? The error message is misleading.)

**Comment by bitbrain** [comment]
**UPDATE**

When I answer "no" explicitly it seems to work:
```
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.


Do you want to copy the state from "s3"?
  Would you like to copy the state from your prior backend "s3" to the
  newly configured "s3" backend? If you're reconfiguring the same backend,
  answering "yes" or "no" shouldn't make a difference. Please answer exactly
  "yes" or "no".

  Enter a value: no



Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.
```
This really seems like a bug to me. At least the documentation/output doesn't give any hint what is wrong.

**Comment by nbering** [comment]
This is one set of configuration files being used for two deployments with state stored in the same backend?

Have you seen `terraform env` (renamed `terraform workspace in v0.10.x)?

It allows you to do this without re-initializing your backend each time you switch. It maintains a separate state for each env/workspace which is great for copies of the same infrastructure when doing dev/test/prod.

If the states need to be decoupled from one-another, I would probably setup the infrastructure as a submodule and reference it from two different root configurations that have separate backend configs. The last thing you want to do is accidentally over-write one config with the other when running `terraform init` to switch backends. It's fixable if you have versioning turned on in the s3 bucket, but still painful.

**Comment by jbardin** [comment]
Hi @bitbrain,

Sorry this is tripping you up, I'm not sure exactly what we're seeing here yet.

The message `Backend configuration changed!` means that the current directory has already been initialized with a different backend configuration. This contradicts your reproduction steps, so there might be some detail we're missing. 

Terraform "remembers" important configuration values in it's `.terraform/` directory located in the directory being initialized. The `init` command is always tied to the directory from which it is run. We may make this more flexible in the future, but currently you "initialize" your working working directory, and run all other command from within that directory. Is it possible that you have an old `.terraform/` directory in one of the config directories that is pointing to a bucket that no longer exists?

Can you try to reproduce this from a clean configuration in new, empty directories?

**Comment by bitbrain** [comment]
@jbardin correctly, it is definitely related to the .terraform/terraform.tfstate file which is kept locally, even when having a S3 backend. I don't have a problem with how it works (it works fine for me after knowing this), however the message is quite confusing. It fails to find the bucket when answering "y" on the initialization question, however "n" will make things work. (which I still find very confusing, so I would like to see at least a more clear message output by terraform)

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. The documentation has been updated since this was opened so this may not be relevant nowadays.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
