### ISSUE TITLE
S3 backend prefixes environment to key instead of suffixing

### ISSUE THREAD

**Issue by tyrsius** [hashicorp/terraform#15654]
### Terraform Version
Terraform v0.9.11

### Terraform Configuration Files
```hcl
terraform {
    backend "s3" {
      bucket = "s3Bucket"
      key    = "s3Key"
      region = "us-west-2"
    }
}
```

### Expected Behavior
Remote state should be stored in `{s3Bucket}/{s3Key}/{environment}`

### Actual Behavior
Remote state is stored in `env:/{environment}/{s3key}`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform env new {_anything_}`

### Important Factoids
Terraform handles the environment and s3 backend `key` in the wrong order. The docs say this for `key`

>key - (Required) The path to the state file inside the bucket.

When using environments the key is not respected, and instead files are stored in the bucket under `env:/{environment}/{s3key}`. The literal "env:" (yes, with a colon) is confusing enough, but the fact that the key is the *last* thing used is just wrong. The `key` property is useful for isoloting multiple applications/configurations in a single bucket, but when using environments everyone shares the "env:" folder as well as as the environment folder. *This breaks isolation across applications/configurations*.

If this is the intended behavior and not a bug, which I hope it is, then I would like to request a method for actually specifying the backend key that is used at the root.

**Comment by jbardin** [comment]
Hi @tyrsius,

We have a duplicate open at #15358 if you want to see some of the history on the subject.
The `workspace_key_prefix` functionality is taken care of, but there are a couple minor doc updates still pending.
