### ISSUE TITLE
How to store and reuse interpolation results?

### ISSUE THREAD

**Issue by anshprat** [hashicorp/terraform#15668]
### Terraform version
>tf --version
Terraform v0.9.11

### Terraform Configuration Files
```
resource "aws_ebs_volume" "instance_system_volume" {
  count = "${length(var.extra_ebs_volumes) * var.count_instances }"

  type = "${lookup(var.extra_ebs_volume_type,lookup(var.tag_disk_location,var.extra_ebs_volumes[count.index % length(var.extra_ebs_volumes)]),"standard")}"
  availability_zone = "${element(aws_instance.myorg_instance.*.availability_zone, count.index / length(var.extra_ebs_volumes))}"

  size = "${floor(lookup(merge(var.default_ebs_vol_sizes,var.ebs_vol_sizes),
    var.tag_disk_location[var.extra_ebs_volumes[count.index % length(var.extra_ebs_volumes)]]))}"

  tags = "${merge(var.tags_basic, var.tags_extra,
    map("Name", format("%s", lower("${replace(var.tags_extra["Name"], "i_count",
      format("%02d", (count.index / length(var.extra_ebs_volumes)) + 1))}${var.txt_delimiter}
      ${var.extra_ebs_volumes[count.index % length(var.extra_ebs_volumes)]}${var.txt_delimiter}
      ${lookup(var.tag_disk_location,var.extra_ebs_volumes[count.index % length(var.extra_ebs_volumes)])}")),
    "tag_disk_location",lookup(var.tag_disk_location,var.extra_ebs_volumes[count.index % length(var.extra_ebs_volumes)])),
    map("tag_monthly_cost", "${1.0 * lookup(merge(var.default_ebs_vol_sizes,var.ebs_vol_sizes),
      var.tag_disk_location[var.extra_ebs_volumes[count.index % length(var.extra_ebs_volumes)]]) * lookup(var.ebs_cost,
      lookup(var.extra_ebs_volume_type,
        lookup(var.tag_disk_location,var.extra_ebs_volumes[count.index % length(var.extra_ebs_volumes)]),"standard"))}")
    )
      }"
  lifecycle {
    ignore_changes = ["availability_zone"]
  }
}
```

Hi,

 How do I store and reuse terraform interpolation result within resources that do not expose them as output? Inability to use self reference further adds on to this issue. 

example: In aws_ebs_volume , I am calculating my volume size using:

  size = "${lookup(merge(var.default_ebs_vol_sizes,var.ebs_vol_sizes),     var.tag_disk_location[var.extra_ebs_volumes[count.index % length(var.extra_ebs_volumes)]])}"   

Now I need to reuse the same size for calculating the cost tags in  the same resource as well as in corresponding ec2 resource (in same local module).  

How do I do this without copy pasting the entire formula?  

 PS: I have come across this use case in multiple scenarios, so the  above is just one of the use cases where I need to reuse the  interpolated results. Getting the interpolated result using the  corresponding data source is one way out in this particular scenario but looking for a  more straight forward solution and generic solution.

**Comment by apparentlymart** [comment]
Hi @anshprat!

Right now there isn't a convenient way to do what you describe here. There are some workarounds described in the comments of #4084.

In the near future this will be possible using the feature being added in #15449. Development on that didn't complete in time before the 0.10.0 feature freeze but it should be included in an upcoming version soon.

Since we already have #4084 open discussing this problem and #15449 for the proposed solution, I'm going to close this just to consolidate the discussion there. Thanks for this question/suggestion!

**Comment by anshprat** [comment]
alright, thanks!
