### ISSUE TITLE
Proposal: New lifecycle option abandon_on_destroy

### ISSUE THREAD

**Issue by maikzumstrull** [hashicorp/terraform#15672]
I'm currently trying to model the following workflow with Terraform:

1. Create Ignition config
2. Assign random unique filename to config
3. Upload Ignition config to a storage bucket with that name
4. Reference configs from an instance template
5. Create a managed instance group from this template
6. Created instances use the Ignition config from 1. to initialize

This works in a fairly obvious way using ignition_config, random_id, google_storage_bucket_object, and so on. When making any changes to the config, Terraform will also reliably assign a new random ID, store the new config in a new object, create a new template, and update the managed instance group.

What I don't like is that Terraform will also immediately delete the old config from the storage bucket - even though there could be, at this point, still instances and instance groups referencing that config, due to the asynchronous nature of managed instance groups.

I think a good option for addressing this usecase would be to add a new `lifecycle` option to the core resource definition in Terraform: `abandon_on_destroy` The semantics for this would be that whenever Terraform wants to apply a plan that deletes this resource, Terraform would remove the resource from the state, but not actually delete it on the cloud provider.

The purpose of this ticket is mainly to collect some feedback on the idea. If this seems like something that would potentially be accepted, one of our developers could prepare a pull request. Of course, if you just want to go ahead and implement this, that would be very okay as well.

If it doesn't seem like something you would want in the codebase, could you point me to some documentation for other ways to model resources one wants Terraform to create and update, but never reap? `prevent_destroy` is not quite right because it will error out, when I want it to just move on and make a new one next to the old one.

**Comment by Puneeth-n** [comment]
Might be related to the issue #15485

**Comment by maikzumstrull** [comment]
Oh, yes, these seem near duplicates. I was looking for similar requests, but apparently not hard enough. Thanks @Puneeth-n!

**Comment by Puneeth-n** [comment]
I had to implement something quick for a project which made use of AWS step functions which does not have an update functionality. So the step functions are deleted and new ones created when there is a change (which is not desired for our use case). I wanted Terraform to "just" forget the old state machine and create a new one. This involved me modifying the terraform code to create a dummy "Update" function hook for step function which basically told terraform that the "step function in question does not exist"

**Comment by jbardin** [comment]
Hi @maikzumstrull,

Thanks for filing the issue. 
I'm going to close in to track the feature in #15485.
