### ISSUE TITLE
workspace new -state fails lineage check for remote state

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#15674]
The lineage and serial checks have become more strict, but the `-state` flag for `workspace new` now gets caught when trying to push an existing state.

The workaround for now is to create a new workspace, then use `state push -force` to put the desired state in place.

**Comment by fatgit** [comment]
@jbardin 
`terraform state push -force s3.tfstate` 

> Failed to write state: incompatible state lineage; given 9dec780b-2b5a-402c-acc9-f97eab09a152 but want 64281297-ade7-4206-a940-546534a25f1c

Anyway, to push my tfstate, I had to change "lineage" manually  to the one that was created in the new workspace in empty tfstate

**Comment by jbardin** [comment]
@fatgit 

Thanks for following up. I verified this with 0.9.11, but yes, it looks like that workaround hits the same lineage check now too.
