### ISSUE TITLE
add urlencode function

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform#15675]
### Terraform Version
0.9.11

### Proposal

I'm currently wiring up a bunch of different cloud service thingies with terraform, parts of this involve configuring one service to go ping a webhook in another service.

In particular I need to pass the name of a slack channel encoded into a URL, so a `urlencode` function would be very helpful for interpolating valid URLs

### References
Looks like someone sent in a PR once, but changed their mind: https://github.com/hashicorp/terraform/pull/6278

**Comment by apparentlymart** [comment]
This seems reasonable to me. Thanks for the suggestion, @glenjamin!

There are a few different interpretations of `urlencode` out there across different languages/libraries:

1. Escape everything except alphanumerics, dashes and underscores, so a value can be included into any arbitrary part of the URL and taken entirely literally
2. Only escape characters that are not valid _at all_ in URLs, leaving things like slashes alone.
3. Compromises between the two that take care of only a subset of the specially-significant characters.

I think from your use-case that you want interpretation 1 here. Is that right? This seems like the most generally-useful interpretation, so I'd be happy to let this interpretation take the simple `urlencode` name, and assume that if we get a use-case for other variants we'll use some sort of suffix to differentiate.

**Comment by darkowlzz** [comment]
I would like to work on this issue and learn about contributing to terraform.
