### ISSUE TITLE
Automatic IP assignments based on DNS.

### ISSUE THREAD

**Issue by carlcomsys** [hashicorp/terraform#15676]
Hello team,

I have noticed that terraform does not have a way to identify that an IP has been used unless if the count is more than 1, for instance, If I ask terrfaorm to create 3 VMs, it knows to select the next count of IP it assumes to be available, so it could do something like this, 10.xxx.yyy.11, then 10.xxx.yyy.12, but If I specified that I wanted one VM created in my main.tf file, and then specify same info in another main.tf file, it will create same IP assignment even though that IP has been assigned to another hostname.

I will need a way for Terraform to check if the Ip is available withing the subnet and or gateway before proceeding to assign IPs.

Thanks.

Obinna

**Comment by jbardin** [comment]
Hi @carlcomsys,

Currently there's is no generic method for terraform to know if an IP allocated within a provider has been assigned to another resource in that provider. If the addresses aren't an allocated resource, then it becomes even more difficult to track. DNS can't be used to track address assignments, because address assignments themselves don't have DNS records. Do you want to lookup DNS record sets to see what addresses they contain?

Most of the time you would structure your configuration such that you would know which IP address is being assigned to which host. If multiple configurations are using the same block of addresses, they need to share that information through modules. 

If you provide an example configuration for the provider you're using we may be able to give more advice.

**Comment by nbering** [comment]
Sounds like a case for Dynamic IP addresses to me. If there isn't a need for each machine to have a specific IP, then just let the DHCP server decide what IP that machine will have. Most - if not all - of  the VM providers will give the IP address back to you in the properties of the resource to use elsewhere for populating DNS records, etc.

Alternatively, something has to populate those DNS records to begin with, could you just populate a list in a .tfvars with the IP addresses used for the deployment from your master list?

**Comment by carlcomsys** [comment]
Hello,
I am deploying ephemeral nodes at garious stages/environment in chef automate work flow, and there are certain blocks of IPs that wqs assigned to each work flow stage based on non prod and prod environment within my organization.
now If I manually list IPd available in a subnet in the tvars file, how doee terreform know of any ip listed therein has been utilized and is no linger qvailable, how does it know when it is available when a VM has been destroyed?


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Nicholas Bering <notifications@github.com> Date: 8/1/17  8:50 AM  (GMT-06:00) To: hashicorp/terraform <terraform@noreply.github.com> Cc: carlcomsys <obicarl@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [hashicorp/terraform] Automatic IP assignments based on DNS.
  (#15676) 
Sounds like a case for Dynamic IP addresses to me. If there isn't a need for each machine to have a specific IP, then just let the DHCP server decide what IP that machine will have. Most - if not all - of  the VM providers will give the IP address back to you in the properties of the resource to use elsewhere for populating DNS records, etc.
Alternatively, something has to populate those DNS records to begin with, could you just populate a list in a .tfvars with the IP addresses used for the deployment from your master list?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hashicorp/terraform","title":"hashicorp/terraform","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hashicorp/terraform"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nbering in #15676: Sounds like a case for Dynamic IP addresses to me. If there isn't a need for each machine to have a specific IP, then just let the DHCP server decide what IP that machine will have. Most - if not all - of  the VM providers will give the IP address back to you in the properties of the resource to use elsewhere for populating DNS records, etc.\r\n\r\nAlternatively, something has to populate those DNS records to begin with, could you just populate a list in a .tfvars with the IP addresses used for the deployment from your master list?"}],"action":{"name":"View Issue","url":"https://github.com/hashicorp/terraform/issues/15676#issuecomment-319375583"}}}

**Comment by nbering** [comment]
Sounds like your IP management system needs to be overhauled a little to support dynamic assignments without assigning a reserved IP. But that aside, you could write yourself a little data provider to fetch an available IP over [HTTP](https://www.terraform.io/docs/providers/http/data_source.html) or some other protocol with the [External Data Source](https://www.terraform.io/docs/providers/external/data_source.html) for an arbitrary program. The only problem you may encounter with this is giving the IP back. I remember following a thread about [Destroy Provisioners](https://github.com/hashicorp/terraform/pull/11329), though I never tested them myself to know if it'll help you. If they do work, you could use a destroy provisioner to make a request to whatever IP management endpoint your write to give back the IP on destroy.

Good luck!

**Comment by carlcomsys** [comment]
Thanks alot Nicholas will try this.
Obinna Okpokwasili 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Nicholas Bering <notifications@github.com> Date: 8/3/17  4:12 PM  (GMT-06:00) To: hashicorp/terraform <terraform@noreply.github.com> Cc: carlcomsys <obicarl@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [hashicorp/terraform] Automatic IP assignments based on DNS.
  (#15676) 
Sounds like your IP management system needs to be overhauled a little to support dynamic assignments without assigning a reserved IP. But that aside, you could write yourself a little data provider to fetch an available IP over HTTP or some other protocol with the External Data Source for an arbitrary program. The only problem you may encounter with this is giving the IP back. I remember following a thread about Destroy Provisioners, though I never tested them myself to know if it'll help you. If they do work, you could use a destroy provisioner to make a request to whatever IP management endpoint your write to give back the IP on destroy.
Good luck!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hashicorp/terraform","title":"hashicorp/terraform","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hashicorp/terraform"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nbering in #15676: Sounds like your IP management system needs to be overhauled a little to support dynamic assignments without assigning a reserved IP. But that aside, you could write yourself a little data provider to fetch an available IP over [HTTP](https://www.terraform.io/docs/providers/http/data_source.html) or some other protocol with the [External Data Source](https://www.terraform.io/docs/providers/external/data_source.html) for an arbitrary program. The only problem you may encounter with this is giving the IP back. I remember following a thread about [Destroy Provisioners](https://github.com/hashicorp/terraform/pull/11329), though I never tested them myself to know if it'll help you. If they do work, you could use a destroy provisioner to make a request to whatever IP management endpoint your write to give back the IP on destroy.\r\n\r\nGood luck!"}],"action":{"name":"View Issue","url":"https://github.com/hashicorp/terraform/issues/15676#issuecomment-320091570"}}}

**Comment by jbardin** [comment]
Closing, as this is not something Terraform is intended to solve.
