### ISSUE TITLE
get -update doesn't update from non-master branches

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#1568]
I'm using git remote modules (hosted in a private repo on GitHub) and specifying a branch other than master. However, it seems when using a branch other than master, modules are not updated when I run `get -update`. If modules are pulled from `master`, then they're updated fine.

Using `v0.4.2`...

# Steps to reproduce
1. Create module *module1* in repo *repo-modules*.
1. Create project *project1* in repo *repo-main*, that uses *module1*.
1. In *project1*, run `get` and `plan` to see changes you expect.
1. Create changes to *module1* on branch *branch1*.
1. Update your source URL to use *branch1* with `?ref=branch1`.
1. In *project1*, run `get -update` and `plan`. Your should *not* see the changes you expect.

If it matters the source URL I'm using is in the form `git::ssh://git@github.com/org/repo-modules.git//module1?ref=branch1`.

*Updated with Terraform version.*

**Comment by radeksimko** [comment]
I don't see this being problem in case of git tags used as versions as these will not likely ever be updated. In fact, you can't actually update a tag in any clean way, it's just a pointer to git hash which won't be pointing anywhere else unless you `push --force` such change (correct me if I'm wrong).

In case of real branches, it is an issue though.

**Comment by rradecki** [comment]
+1
We want also to use branches other than master and I think that this functionality should be implemented.  When is it going to be done?

**Comment by ermikowy** [comment]
+1

**Comment by pmilewsk** [comment]
+1

**Comment by amaczuga** [comment]
please do fix this

**Comment by sszwed** [comment]
+1

**Comment by rradecki** [comment]
Is there any ETA for this issue?

**Comment by elblivion** [comment]
+1

**Comment by bennycornelissen** [comment]
+1

**Comment by djvdorp** [comment]
+1

**Comment by mitchellh** [comment]
Working on this now

**Comment by mitchellh** [comment]
Fix is in PR, will be fixed in the next release of TF

**Comment by djvdorp** [comment]
@mitchellh great, thanks for your work, very much appreciated! When is the next release of TF scheduled?
