### ISSUE TITLE
Cannot copy file with provisioner. Key not read

### ISSUE THREAD

**Issue by Ferparishuertas** [hashicorp/terraform#15690]
I am trying to copy a file inside an aws ec2 user-data and the following errors raises

Failed to read key " MIIEowIBAAKCAQEAi8p4tF6jk/Kvq5g1H0V02Ule8KBBJ4jPsOoUZuLcQV07LBS1WZkx6PIGPjuJ\r\n8jXbWR6p/1gFQxxbSyn9ij0BAYH/SSIyljpsMH36DxTa+aaMdohlUcanh7W0fmRmQenfOxAsrxIb\r\ngU97iPcXaakcoyMcFuvsD6jm+1B/rbJgzfGQiaRxZPgIMWgGla+Ool1T8HBQrPwm3TNAMQBOLDB/\r\nFyjFfQIsFpqXBxS............
no key found

```hcl
  provisioner "file" {
    source      = "templates/mongodb-org-3.0.repo"
    destination = "/etc/yum.repos.d/mongodb-org-3.0.repo"

    connection {
    type     = "ssh"
    user     = "ec2-user"
    private_key = "${file("templates/wealth.pem")}"
    agent = true
  }
  }
```

**Comment by radeksimko** [comment]
Hi @Ferparishuertas 
I hope the you pasted is just example (one off key) - otherwise I'd recommend you to rotate the key - even if you only exposed part of it.

It looks like your private key should be encoded as [PEM](https://en.wikipedia.org/wiki/Privacy-enhanced_Electronic_Mail) but it doesn't have the appropriate header per specification, e.g. `-----BEGIN RSA PRIVATE KEY-----` hence it's treated as invalid.

Were you ever able to use this key elsewhere?

**Comment by Ferparishuertas** [comment]
Yes im able to use it. It has got begin rsa... but i tries several ways etc
with no luck.. 1 try was without header

**Comment by Ferparishuertas** [comment]
Any clue advise to be able to go forward?

**Comment by radeksimko** [comment]
Hi @Ferparishuertas 
It's unfortunate this involves such a sensitive data like private key. Can you try `ssh-keygen` a brand new one-off key and try with that one instead and if it doesn't work share such one-off key with us?

Generally having more context & details and full sequence of steps (including how you generated the key) would be incredibly helpful. I was unable to reproduce the error so I can't provide any further help without further details.

**Comment by Ferparishuertas** [comment]
It was my mistake... .some holidays give me a clear path

Thanks and sorry

**Comment by radeksimko** [comment]
Thanks for the followup.
I'm glad you were able to resolve the problem at the end. 🙂

**Comment by narendrasingh15** [comment]
@Ferparishuertas, Can you Please clarify what fixed the issue? I am facing a similar error while using file provisioner.
