### ISSUE TITLE
terraform init not working

### ISSUE THREAD

**Issue by armpogart** [hashicorp/terraform#15703]
### Terraform Version
0.9.11

### Terraform Configuration Files
```hcl
// Configure the Google Cloud provider
provider "google" {
  credentials = "${file("account.json")}"
  project     = "effio-openshift"
  region      = "us-central1"
}

// Create new instance
resource "google_compute_instance" "default" {
  name          = "test"
  machine_type  = "n1-standard-1"
  zone          = "us-central1-a"

  boot_disk {
    initialize_params {
      image     = "centos-7"
    }
  }

  // Local SSD disk
  scratch_dick {
  }

  network_interface {
    network     = "default"

    access_config {
      // Ephemeral IP
    }
  }
}
```

### Debug Output
```sh
2017/08/03 04:03:06 [INFO] Terraform version: 0.9.11  efca455c35d0d218a9bfee835a8ec3ef8d4d1c8c
2017/08/03 04:03:06 [INFO] Go runtime version: go1.8
2017/08/03 04:03:06 [INFO] CLI args: []string{"/home/user/terraform/terraform", "init"}
2017/08/03 04:03:06 [DEBUG] Detected home directory from env var: /home/user
2017/08/03 04:03:06 [DEBUG] Detected home directory from env var: /home/user
2017/08/03 04:03:06 [DEBUG] Attempting to open CLI config file: /home/user/.terraformrc
2017/08/03 04:03:06 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/08/03 04:03:06 [INFO] CLI command args: []string{"init"}
2017/08/03 04:03:06 [DEBUG] Detected home directory from env var: /home/user
2017/08/03 04:03:06 [DEBUG] command: loading backend config file: /home/user/terraform-configs
2017/08/03 04:03:06 [DEBUG] command: no data state file found for backend config
2017/08/03 04:03:06 [DEBUG] New state was assigned lineage "eb2e8ea3-6417-441d-8a63-9669956cb66d"
2017/08/03 04:03:06 [INFO] command: backend initialized: <nil>
2017/08/03 04:03:06 [INFO] command: backend <nil> is not enhanced, wrapping in local

2017/08/03 04:03:06 [DEBUG] plugin: waiting for all plugin processes to complete...
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.
```

### Expected Behavior
`terraform init` to create statefile

### Actual Behavior
Nothing happens

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

### Important Factoids
Using terraform on Bash on Ubuntu on Windows. Also tried example aws config from intro with the same results.

### References
There were multiple issues with Bash on Ubuntu on Windows, but as far as I see it's working for everybody with Windows Creator's Update, so I don't see reason that it must not even initialize.

**Comment by armpogart** [comment]
Updating to v0.10.0 doesn't help

**Comment by jbardin** [comment]
Hi @armpogart,

I'm not sure exactly what you're seeing here. The `terraform init` command doesn't create a state file, it initializes the backend config, and since 0.10.0 it fetches and installs the required providers. 

If that is your complete config, there is nothing that is expected to happen.

What is happening for other's that you're not seeing?

**Comment by armpogart** [comment]
Hi @jbardin 

Yeah, sorry for not stating the problem correctly. It actually doesn't initialize anything and fetch the provider. It simply doesn't anything and the only output I see is the mentioned one. On the contrary with Windows binary (without Ubuntu bash shell), when I run in the same folder with the same config it does initialize the backend and fetched the provider.

As you can see from output it doesn't fetch the provider and doesn't initialize anything as the output in that case is a little bit different.

**Comment by armpogart** [comment]
Hmm...
Also after trying another way, I noticed following.
If the .tf config is in Bash on Ubuntu on Windows filesystem (i.e. my user home directory for example), the issue is there (the mentioned one).
But if I copy the .tf file to some folder on windows mount (e.g. /mnt/d/somefolder) and run `terraform init` there again from Bash on Ubuntu on Windows - everything works.

I guess it's something related to the filesystem. I don't know exactly what file system windows creates for it's Ubuntu (or emulates one), but it turns out terraform doesn't work only there, so it's not something related to how Windows translates syscalls internally if I'm stating it correctly.

**Comment by jbardin** [comment]
Hi @armpogart,

You are using terraform v0.9.11, and the config you have has no backend or modules. There's simply nothing for terraform to do. 

Are you running the config with a different version of terraform in the second case?

**Comment by armpogart** [comment]
I've tried the same config with the version v0.10.0, also tried with backend, it simply doesn't do anything. The same config works from windows shell with windows version (0.10.0).

**Comment by jbardin** [comment]
@armpogart, If that's the case, can you put the config in a clean directory, and provide the debug logs from running `init` with 0.10.0? Thanks.

**Comment by armpogart** [comment]
@jbardin Strangely after I tried to create new folder, created .cf file copy-pasting the contents from the previous one, and running terraform init - everything worked))
Unfortunately I have deleted the old folder, so can't exactly tell what was the difference.
I will close this issue until experiencing the same again, sorry and thank you for your time and great product.
