### ISSUE TITLE
Incompatible state lineage error when migrating to remote backends with workspaces

### ISSUE THREAD

**Issue by synthdnb** [hashicorp/terraform#15712]
### Terraform Version
Terraform v0.10.0

### Steps to Reproduce
1. `terraform init` (with local backend)
1. Create empty test.tf file.
1. `terraform workspace new prod`
1. `terraform apply`
1. Configure backend in test.tf file. Mine was
```
terraform {
  backend "s3" {
    bucket  = "bucket-name"
    key     = "test01.tfstate"
    region  = "ap-northeast-1"
    encrypt = "true"
  }
}
```
1. `terraform init`, and `yes` causes lineage error
```
Enter a value: yes

Error migrating the workspace "prod" from "local" to "s3":

Error copying state from "local" to "s3": incompatible state lineage; given b9400e57-116e-4069-af31-2ff127e6aaaf but want 91fe953d-d1fc-48e4-965f-d4949c45c12b

The state in "local" remains intact and unmodified. Please resolve the
error above and try again.

Terraform copies workspaces in alphabetical order. Any workspaces
alphabetically earlier than this one have been copied. Any workspaces
later than this haven't been modified in the destination. No workspaces
in the source state have been modified.

Please resolve the error above and run the initialization command again.
This will attempt to copy (with permission) all workspaces again.
```

This error occurs even if I use consul backend, so it seems that this is not backend-specific issue.

**Comment by jbardin** [comment]
Hi @synthdnb,

Sorry you're hitting this issue. This is the same issue being tracked here #15674, which wasn't uncovered in time for the code freeze. 

We will have  fix for this in the next minor release.
