### ISSUE TITLE
terraform refresh on AWS EC2 instances is missing data

### ISSUE THREAD

**Issue by stepanstipl** [hashicorp/terraform#1571]
When running terraform refresh on AWS EC2 instance resources, terraform won't refresh all data. In my case I've got **ami**, **ephemeral_block_device.#** and **instance_type** missing. All of these should be easily obtainable from AWS api, or is there any reason for this behaviour?

My use case is to try to get rid of necessity of tfstate file -> use simple script that would generate bare tfstate file with instance ids and then populate additional info using `terraform refresh`.

````
$diff terraform.tfstate.original terraform.tfstate                                                                                                                                                                                      (master|✚3…) 0
3c3
<     "serial": 2,
---
>     "serial": 3,
18d17
<                             "ami": "ami-b1cf19c6",
22d20
<                             "ephemeral_block_device.#": "0",
24d21
<                             "instance_type": "m1.small",
50d46
<                             "ami": "ami-b1cf19c6",
54d49
<                             "ephemeral_block_device.#": "0",
56d50
<                             "instance_type": "m1.small",
````

Btw. this would be awesome functionality - store terraform ids for example as AWS tag and being able to do refresh without tfstate file at all.

````
$terraform --version
Terraform v0.4.2
````

**Comment by rismoney** [comment]
> My use case is to try to get rid of necessity of tfstate file
:+100:
