### ISSUE TITLE
Removing HEREDOC idents

### ISSUE THREAD

**Issue by axelabs** [hashicorp/terraform#15724]
I'm trying to use HEREDOC syntax with Terraform v0.10.0 specifically with hopes of the hanging indents being removed as outlined in this [HCL commit](https://github.com/hashicorp/hcl/pull/91/commits).  Terraform seems to recognize the <<-HEREDOC syntax, but only find the terminator and does not strip the indent from inside.  Have the HCL changes been fully incorporated to my version?

**Comment by tombuildsstuff** [comment]
Hey @axelabs 

Thanks for opening this issue :)

> Have the HCL changes been fully incorporated to my version?

Which version of Terraform are you using? Changes merged into the HCL Repository are pulled in fairly frequently - and from what I can see this is in Terraform 0.10

Would it be possible to see the Terraform configuration (or a reproducible sample configuration) which you're having issues with?

Thanks!
