### ISSUE TITLE
terraform import ignores remote state and creates a new local state file

### ISSUE THREAD

**Issue by mattoberle** [hashicorp/terraform#15735]
The `terraform import` command creates a local `terraform.tfstate` or `terraform.tfstate.d` rather than acting on a configured remote state. I'm not 100% sure if this is a change in behavior or if this has always been the case- but it is a behavior that I have not noticed until v10.0. This behavior causes an issue when trying to import additional resources into an existing remote state.

I did a little more digging into closed issues and I see this here:
https://github.com/hashicorp/terraform/issues/11835

It seems that this is the expected behavior now, although the `terraform import` documentation does not describe the workflow for importing resources into a remote state. The terraform documentation for `terraform state push` suggests that the command should rarely be used, and is not part of the regular workflow:
https://www.terraform.io/docs/commands/state/push.html

### Terraform Version
Terraform v0.10.0

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    region = "us-east-1"
    bucket = "foo"
    key = "terraform.tfstate"
  }
}
resource "aws_s3_bucket" "bar" { 
  bucket = "bar"                                    
}
```
### Expected Behavior
I would expect executing this...
```bash
terraform init
terraform import aws_s3_bucket.bar bar
```
... to update the remote state file `s3://foo/terraform.tfstate` (the same behavior that `terraform state` commands follow).

### Actual Behavior
Executing this...
```bash
terraform init
terraform import aws_s3_bucket.bar bar
```
... creates a local `terraform.tfstate` file with the import (the remote state is unchanged).

At the moment my workflow for working around this is:
```bash
terraform state pull > terraform.tfstate
terraform import aws_s3_bucket.bar bar
terraform state push
```

**Comment by jbardin** [comment]
Hi @mattoberle,

Thanks for filing the issue and example.

Due to the incremental workflow of importing resources, and the relative infrequency that it should be used, import has been limited to working on local state only. This gives a little more flexibility around copying and backing up the state. The workaround you've present is how it's intended to be used at the moment. 

As the import process is improved, we will look into allowing importing directly into remote state.

**Comment by bentterp** [comment]
If this is the intended workflow, the please update the documentation of the import command to reflect this.

@mattoberle Thank you very much for not only reporting the issue but also hand-feeding the workaround to me.

**Comment by thiagocaiubi** [comment]
@jbardin Does `state rm` and `state mv` in the same scenario?
https://github.com/hashicorp/terraform/issues/15746

**Comment by jbardin** [comment]
Hi @bentterp,

Yes, if we can't get this implemented soon, the workflow above should be added to the command examples. 

Hi @thiagocaiubi,

This particular issue is unrelated to the `state` commands, but the same process can be used to move state between files. Also, even though the linked issue is closed, because there's no way to address a remote state file, moving resource _into_ a remote state would require the same workflow anyway.

**Comment by thiagocaiubi** [comment]
Hi @jbardin, thanks for terraform and your quick response. I can see you closed the other issue, thanks!

Terraform import is helpful to users migrating their infrastructure from another tool to terraform (my case). Hope people don't mess too much their state applying this workaround.

**Comment by holybit** [comment]
Just to be clear prior to `Terraform v0.10.0` import imported directly to remote state and has for as long as I can remember. This new behavior of importing to a local state file should be dully noted under `BACKWARDS INCOMPATIBILITIES / NOTES`.

**Comment by jbardin** [comment]
@holybit,

Thanks for pointing that out. I was recalling an old conversation about the import workflow, and assumed that was still the case (the online docs were incorrect, but they were incorrect in the same way as the `state` docs, so I didn't trust them).

I confirmed that this was operating on remote state through the 0.9 releases. There was no planned change in behavior for import for the 0.10, so this is indeed a bug.

**Comment by RobAWilkinson** [comment]
Great change, previously I was commenting out the backend section, rerruning `tf init` making tweaks as necessary and then final uncommenting the backend and repeating my imports.
Currently I run an import, comment out the backend section, and `terraform state push` when everything is correct.
