### ISSUE TITLE
validate not using terraform.tfvars as source

### ISSUE THREAD

**Issue by cehoffman** [hashicorp/terraform#15733]
### Terraform Version

0.10.0

### Terraform Configuration Files

**terraform.tf**

```hcl
variable "rsg" {
  description = "Will fail validate even though specified in terraform.tfvars"
  type        = "string"
}
```

**terraform.tfvars**

```hcl
rsg = "test"
```

### Debug Output

https://gist.github.com/cehoffman/4bf483b75989d01fdbd9a5a75c1f44c1

### Expected Behavior

Validate should pass since the variable is defined in `terraform.tfvars`.

### Actual Behavior

Validate step fails with unspecified variable while plan works.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform validate`

### Important Factoids

Nothing

### References
#13872

**Comment by mungi** [comment]
This issue is the same in v0.10.1.

`terraform validate` does not automatically load terraform.tfvars file.

I had to use `terraform validate  -var-file=terraform.tfvars`

>  -var-file=foo         Set variables in the Terraform configuration from a file. 
                    If "terraform.tfvars" is present, *it will be automatically loaded* if this flag is not specified.

**Comment by miketruty** [comment]
This issue is the same in v0.10.2.

This will get fixed soon? Unfortunately, I'm referencing this in a tutorial.

**Comment by billythekid1** [comment]
I am facing the same issue with v0.10.3
[ec2-user@ip-172-31-26-83 code]$ terraform plan
1 error(s) occurred:

* module root:
    module sg_group_module: required variable "security_group_name" not set
    module sg_group_module: required variable "vpc_id" not set
    module sg_group_module: required variable "source_cidr_block" no

**Comment by miketruty** [comment]
I updated to v0.10.5 and problem is resolved!

**Comment by dev-drprasad** [comment]
I am facing the same issue with v0.10.7
