### ISSUE TITLE
consul backend path with trailing / causes issues

### ISSUE THREAD

**Issue by Evertvz** [hashicorp/terraform#15747]
### Terraform Version
Terraform v0.10.0

### Terraform Configuration Files
```hcl
terraform {
  backend "consul" {
    address = "consulbackend:8500"
    path    = "terraform_state/prod-myapp-euir1/"
    access_token = "12345"
    lock = true
  }
}
```

### Expected Behavior
Terraform should have informed the user not to end paths with /

### Actual Behavior
Terraform stored the state in the path with /. Consul recognises this as a directory and refuses to show the content.
Terraform had problems with the state locking when there was a trailing /

### Steps to Reproduce
Put a trailing / in your consul backend path and apply. The lock issue can already been seen during init.
1. `terraform apply`

### Important Factoids
Terraform had issues migrating from the path with / to one without /.
It also had problems migrating from a file state to the consul backend with /.

To achieve each, I deleted all state files and initialised from scratch.

**Comment by edevil** [comment]
Stepped on this same issue with Terraform 0.12.24.
