### ISSUE TITLE
Problems during upgrade to 0.10.0

### ISSUE THREAD

**Issue by dinapappor** [hashicorp/terraform#15740]
# PROVIDER ISSUES

**PLEASE NOTE:** Terraform has split out the builtin Providers into their own repositories. For any Provider issues, please open all issues and pull requests in the corresponding repository. An index of supported Providers can be found here:

- https://github.com/terraform-providers

All other issues (that appear to affect multiple or all providers) may be an issue with Terraform's core, and should be opened here. 

------

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
`terraform init` should download provider plugins.

### Actual Behavior
When something is based on a module `terraform init` will **not** download the required provider plugins. Running `terraform init` in a dir where the "service" is not based on a module produces the expected behaviour.

Making a new "service" based on the same module and running `terraform init` works.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Upgrade from `0.9.11` to `0.10.0`
2. Go into to a "service" created with `0.9.11` which is based on a module.
3. Run `terraform init` in attempt to download required provider plugins 

### Workaround
Copying `.terraform/plugins/*` from other directory to a service created with `0.9.11` based on a module into `.terraform/plugins` makes terraform commands work again.

### Important Factoids
Running FreeBSD 11.1 with version `0.10.0` of terraform.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by apparentlymart** [comment]
Hi @dinapappor! Sorry this didn't work.

I am not sure I fully understand what steps you followed here; I'm not sure what is meant by "service" and "based on a module" in this context.

Would you mind sharing some more precise steps for what you were doing here (feel free to redacted any sensitive URLs/etc) so we can better understand what is going on here? Thanks!

**Comment by dinapappor** [comment]
Hi, perhaps I am using the wrong terminology.

For instance if I had previously done this with the old version of terraform `0.9.11`:

```
module "microservice" {
  source            = "/path/to/microservice"

  environment       = "staging"
  availability_zone = "c"
  region            = "us-east-1"
  project_name      = "notifier"
  instance_type     = "t2.micro"
  key_name          = "keyname"
}
```

And then after the upgrade to `0.10.0` would try to alter or just run `terraform plan` it would complain about missing providers which were aws and terraform providers. It would then tell me I needed to run `terraform init` in order to pull down those two providers.

When doing so it would not download them. 

If I were to source the same module in an entirely new project/service/workspace (what is the correct terminology here?) it would do the correct thing, which is downloading the two providers (terraform and aws).

But not when using it with a project that were created with `0.9.11` (or earlier as well I guess).

**Comment by apparentlymart** [comment]
Hi @dinapappor,

Thanks for the additional detail here!

It's very interesting that this issue seems to happen only for configurations that were previously used with 0.9. Generally-speaking the only artifact that should be sensitive to upgrading is the state, since the data within it needs to survive between runs; I wonder if there are possibly some resources in your state that refer to providers that are not currently present in configuration, in which case Terraform would need to install the providers in order to _destroy_ these leftover resources.

When you tried to run `terraform init` on your existing config, did this produce an error or did it appear to succeed but not actually install the providers? If you can share the output from running `terraform init` (redacting any sensitive info) that'd help me understand what steps are being run, which are not, whether any are failing, etc.

**Comment by dinapappor** [comment]
@apparentlymart I can replicate this tomorrow. But from memory it would give me a red error message about resources not being being found. It did **not** even show output about providers being downloaded as would be expected.

**Comment by apparentlymart** [comment]
Thanks @dinapappor. I don't have any leads yet so I'll wait until tomorrow to see if you can get the exact error message.

**Comment by paddycarver** [comment]
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, or continue to have the problem described, please feel free to reply to this issue and we'll reopen it. Thanks!
