### ISSUE TITLE
provider version constraint with interpolation causes panic

### ISSUE THREAD

**Issue by blalor** [hashicorp/terraform#15742]
### Terraform Version

`Terraform v0.10.0`

### Terraform Configuration Files

```hcl
provider "aws" {
    version = "${var.provider_version}"
}
```

### Debug Output

[crash.log.txt](https://github.com/hashicorp/terraform/files/1203045/crash.log.txt)

### Panic Output

See debug output above.

### Expected Behavior

A user-friendly error should have been displayed indicating that the version constraint is invalid.  Eventually it would be great to be able to specify provider versions via a variable, so that they can be defined consistently across modules.

### Actual Behavior

Panic on `terraform plan`.

### Steps to Reproduce

1. `terraform plan`

**Comment by apparentlymart** [comment]
Thanks for reporting this, @blalor.

Indeed this should be a proper error message, rather than a panic. There is supposed to be some earlier code that validates the config before we reach this point, but evidently it's not getting run for some reason and so I imagine this crash would apply for _any_ invalid version constraint string.

---

As an aside, this message in your log is surprising to me:

```
2017/08/06 07:59:26 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
```

This file is supposed to be created by` terraform init` so that Terraform can "remember" which plugins it selected during the initialization phase. The fact that this file didn't exist should've triggered an error prompting you to run `terraform init` to create it, so it seems that there's two different strange things going on here.

**Comment by blalor** [comment]
I actually hadn't run `terraform init` in this project. :-)  I was trying to refactor some existing code, so `init` had already been run.  In fact, if I run `terraform init` with the exact config contents above in an otherwise-empty directory I get:

```
Error getting plugins: module root: 1 error(s) occurred:

* provider.aws: invalid version constraint "${var.provider_version}": Malformed constraint: ${var.provider_version}
```

Removing the `version = "…"` line and running `terraform init` does work, and the lock file is created.

If I then add the `version` line back and run `terraform plan`, the panic comes back.

**Comment by MikeMcMahon** [comment]
interpolation appears to work on all provider attributes except for the version attribute.

**Comment by hopkinsth** [comment]
Just wanted to add second (or third) voice to this w/log: this panic does seem to happen for any bad version constraint, given, e.g.

```tf
provider "aws" {
  region = "us-east-1"
  version = "~1.3"
}
```
...you might get a crash log like the one attached: [crash.log](https://github.com/hashicorp/terraform/files/1492691/crash.log)

Not a huge problem, of course. The panic makes the intended effect but contradicts the all-caps warnings.

**Comment by apparentlymart** [comment]
Thanks for the updates here everyone, and sorry for the silence.

Based on what @blalor reported, it sounds like the code that deals with checking that all the constraints are met when running any command _other than_ `terraform init` is not correctly running the validation step.

`terraform init` itself is catching it, but if you skip running `terraform init` for some reason then the intent is for Terraform to tell you that you need to run it, which requires loading the configuration to compare to what was present at the most recent `terraform init` call. That load to do the check must be missing a validation pass, which then causes a crash when it tries to compare the version constraints against what was expected.

Probably some things are just happening in the wrong order here. I'll take a look and find the right place to insert the required validation check here so we can produce the expected error message in all cases.
