### ISSUE TITLE
Terraform plan -destroy miscount 0.9.11

### ISSUE THREAD

**Issue by miketruty** [hashicorp/terraform#15752]
Not sure who's issue.  Looks like a common-code issue to me.

### Terraform Version

0.9.11

### Debug Output

https://gist.github.com/miketruty/3ba7962c8144a1df4a213b1ae3899d19#file-plan-destroy-miscount

### Expected Behavior

Plan: 0 to add, 0 to change, 34 to destroy.

### Actual Behavior

Plan: 0 to add, 0 to change, 32 to destroy.

### Steps to Reproduce

I have a configuration.  Just apply.

### Important Factoids

Maybe plan -destroy doesn't get a lot of love.

**Comment by jbardin** [comment]
Hi @miketruty,

Thanks for filing the issue! It looks like everything is OK, and the 2 extra "resource" are data source. 
We have an issue open for that here #14048.

Best,
James
