### ISSUE TITLE
chef provisioner times out connecting over ssh

### ISSUE THREAD

**Issue by robertlabrie** [hashicorp/terraform#15753]
Terraform 0.10.0

Out of no where, a TF file I've used over and over to destroy/build a lab just up and throws the error below. I can SSH to the instance with `centos@10.x.x.x` but terraform just prints this mess for 6 minutes and gives up. 

As I write this the only thing I can think of that's changed is I upgraded to MacOS latest from OSX Sierra so maybe they broke something? I'm trying again with agent = false and it's doing the same thing.

Anyone have any ideas?

```
  connection {
    agent = true
    bastion_host = "bastion.example.com"
    bastion_user = "rolabrie"
    type = "ssh"
    user = "centos"
  }
```
aws_instance.tyk_simple (chef): Using configured bastion host...
aws_instance.tyk_simple (chef):   Host: bastion.example.com
aws_instance.tyk_simple (chef):   User: rolabrie
aws_instance.tyk_simple (chef):   Password: false
aws_instance.tyk_simple (chef):   Private key: false
aws_instance.tyk_simple (chef):   SSH Agent: true
Error applying plan:

1 error(s) occurred:

* aws_instance.tyk_simple: 1 error(s) occurred:

* Error connecting to bastion: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by jbardin** [comment]
Hi @robertlabrie,

Sorry you're having an issue with this. Is it possible your agent isn't running, or doesn't have the correct keys loaded? Does `ssh-add -l` provide the expected output?

**Comment by robertlabrie** [comment]
Nope, it wasn't. I've literally never had to pay attention to that before, but running `ssh-add` did it. So now for all eternity, anyone who googles this error message is going to find my year 1 intern mistake.

Thanks @jbardin for helping, all good now!
