### ISSUE TITLE
Store user in state

### ISSUE THREAD

**Issue by raphink** [hashicorp/terraform#15766]
It would be very useful to store the user in the Terraform state (the way it's done in the lock infos) in order to find out who was responsible for applying a state.

**Comment by pkolyvas** [comment]
Hi @raphink,

Thanks for your suggestion. I'm going to refer to a slightly newer ticket that has more discussion. I do think there's some interest around use cases like the one you describe but if we were to prioritize it (and we're not at the moment) a more flexible "additional metadata".

I'll refer to the more general #17430 and close this one out.
