### ISSUE TITLE
`terraform validate` does not load `*.auto.tfvars` files.

### ISSUE THREAD

**Issue by dmikalova** [hashicorp/terraform#15764]
### Terraform Version
Terraform v0.10.0

### Terraform Configuration Files
main.tf
```hcl
variable "test" {}
```

main.auto.tfvars
```
test = "test"
```

### Actual Behavior
`terraform validate` returns `* Required variable not set: test`
`terraform plan` returns `No changes. Infrastructure is up-to-date.` as expected.

### Expected Behavior
I expect that `terraform validate` would pick up on anything matching `*.auto.tfvars`.

### References
The feature as described in the 0.10.0 changelog is `Files in the config directory ending in .auto.tfvars are now loaded automatically...`, which implies that the validate command should pick up on these. My guess is that the validate command was overlooked, but maybe this behavior is intentional?

The documentation does match the behavior, although validate isn't explicitly excluded.
https://www.terraform.io/intro/getting-started/variables.html
https://www.terraform.io/docs/commands/apply.html
https://www.terraform.io/docs/commands/validate.html

**Comment by jbardin** [comment]
Hi @dmikalova,

Thanks for filing the issue. 
I'm going to combine this with #15733, so we can take care of them at in the same fix.
