### ISSUE TITLE
Variable visible anywhere

### ISSUE THREAD

**Issue by danielpintilie** [hashicorp/terraform#15765]
Hello,

How can I access a variable terraform file from anywhere? Let's say for example that I have two terraform scripts in differents folders. A.tf in folder A and B.tf in folder B and both these scripts use the same variable.tf file. How can I make it visible for both scripts? One method would be to put varaible.tf in each folder. Is there another way around? A better way?

Thank you!

**Comment by apparentlymart** [comment]
Hi @danielpintilie!

The intent of modules is to create separate namespaces, so making things that are shared between them is not supported.

However, there is a pattern which can achieve a similar result: make a new module whose only content is a set of outputs:

```hcl
output "shared_thing_example" {
  value = "abc123"
}
```

Then you can instantiate this module from both your `A` module and your `B` module to get access to this value:

```hcl
module "shared_things" {
  source = "../shared-things"
}
```

With that instantiation, you can then access the value with an interpolation sequence like `${module.shared_things.shared_thing_example}`.

**Comment by danielpintilie** [comment]
Thank you!
