### ISSUE TITLE
Allow Setting CORS Settings on s3 buckets

### ISSUE THREAD

**Issue by woodhull** [hashicorp/terraform#1577]
It should be possible to specify the CORS rules on an AWS S3 bucket created through terraform:
http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

This is really one part of a larger bug: s3 buckets have a multitude of properties relating to logging, permissions and the like that terraform currently does not know anything about.

**Comment by clstokes** [comment]
Relevant to https://github.com/hashicorp/terraform/issues/28.

**Comment by catsby** [comment]
API docs for this are here: 

- http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTcors.html 

I imagine each CORS rule would be a sub resource, a bit like this:

```javascript
resource "aws_s3_bucket" "b" {
    [...]
    cors_rule {
        allow_headers = ["*"]
        allow_methods = ["GET","POST",...]
        ...
     }
}
```

Seem right?

**Comment by woodhull** [comment]
Yes, that looks right to me @catsby

**Comment by phinze** [comment]
Hey there - we're consolidating Requests for AWS API Coverage over in the spreadsheet linked at #28 - head over there to record your username on what you'd like us to prioritize next! (This would be `s3.{Get,Put}BucketCors` I believe.)

**Comment by aserour** [comment]
it is called allowed_headers , allowed_origins, ...
