### ISSUE TITLE
Resource with aliased provider uses unaliased when provider block is removed

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#15778]
(This was originally discussed in terraform-providers/terraform-provider-aws#898.)

----

Given a configuration like this:

```hcl
provider "aws" {
    region = "us-west-2"
}

variable "test_bucket" { }

provider "aws" {
    region = "us-east-1"
    alias = "us-east-1-provider"
}

resource "aws_s3_bucket" "mybucket" {
    provider = "aws.us-east-1-provider"
    bucket = "${var.test_bucket}"
}

resource "aws_s3_bucket_object" "myobject" {
    provider   = "aws.us-east-1-provider"
    key        = "tmp-terraform-s3-bug-test"
    bucket     = "${aws_s3_bucket.mybucket.bucket}"
    content    = "test"
}
```

When applied, Terraform sees the `provider` meta-arguments in the `resource` blocks and so creates the S3 objects in the `us-east-1` region.

If the user then removes the `aws.us-east-1-provider` configuration along with the two resources and tries to make a new plan, Terraform erroneously tries to refresh the existing S3 resources using the _default_ (un-aliased) `aws` provider, pointing at `us-west-2`:

```
Error refreshing state: 1 error(s) occurred:

* aws_s3_bucket.mybucket: aws_s3_bucket.mybucket: error reading S3 bucket "my-tmp-test-deleteme": BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region
	status code: 301, request id: , host id: 
```

In the case of S3, this produces an error because the S3 bucket namespace is global and so the API can detect and report that the wrong region is being used.

For most other AWS services, the namespace is region-local and so Terraform would likely see a generic "Not Found" error in this case. The usual consequence of _that_ is to drop the object from the state altogether, causing Terraform to forget about the resource and leave it dangling.

---

Since there's no safe thing we can do without the provider configuration here, this should be an error detected and reported by core during refresh:

```
aws_s3_bucket_object.myobject: cannot refresh because configuration for provider "aws.us-east-1-provider" has been removed; re-create the provider configuration and then re-run this command to proceed
```

This is _not_ an ideal user experience, but it is _safe_. To continue, the user must re-create the provider configuration (e.g. recovering it from version control history) and then re-run the command. At that point, Terraform should detect that these resources are no longer in config and plan to destroy them. After they are destroyed, the provider block can then be safely removed.

Elsewhere we've discussed the possibility of retaining certain aspects of the provider configuration in state, but that is a bigger issue with many implications that should ideally not block a solution to _this_ issue.

**Comment by jbardin** [comment]
This is no longer the case in master. 
Though aliased provider are now being created implicitly with an empty config, so we should decide if that is acceptable before 0.11
