### ISSUE TITLE
set or pass undefined value (null value) in the "environment.tfvars" file

### ISSUE THREAD

**Issue by BijeshSamson11** [hashicorp/terraform#15786]
Hi,
I face an issue with terraform. I have several environments in Azure, some are having load balacers and some are not having load balancers. I made a very generic code for VM deployment, which will automatically add the VM's to load balancer backend pool when VM's are provisioned.
But using same code when I need to deploy VM's whichh are not using load balancer, I need to manually comment out (#load_balancer_backend_address_pools_ids) in main.tf file. Is there any way how to set or pass undefined value (null value) in the "environment.tfvars" file against "backend_pool_ids" , so that I don't need to change the "Main.tf" file everytime?

Following option I tried, but doesn't help me. Any help greatly appreciated

**main.ft file contains following**

resource "azurerm_network_interface" "nic" {
	name = "${var.nicname}${count.index +1}"
	location = "${var.location}"
	resource_group_name = "${var.azurerm_resource_group}"
	count = "${var.count}"
	ip_configuration {
	name = "ipconfig${count.index}"
	subnet_id = "${var.subnet_id}"
	private_ip_address_allocation = "Dynamic"
	load_balancer_backend_address_pools_ids = ["${var.backend_pool_ids}"]
}

**variable.tf file contains following**

variable "backend_pool_ids" {}

**environment.tfvars file contains following**

backend_pool_ids = ""

**Terraform command to run:-**

terraform apply -var-file "example.tfvars"

**Comment by apparentlymart** [comment]
Hi @BijeshSamson11,

It looks like in this case this attribute is expecting a list, so the "null value" here would perhaps be the empty list. With some adjustments, I think this can work...

Change `main.tf` to refer directly to the variable, without wrapping it in `[ ]` brackets:

```hcl
resource "azurerm_network_interface" "nic" {
  name = "${var.nicname}${count.index +1}"
  location = "${var.location}"
  resource_group_name = "${var.azurerm_resource_group}"
  count = "${var.count}"
  ip_configuration {
    name = "ipconfig${count.index}"
    subnet_id = "${var.subnet_id}"
    private_ip_address_allocation = "Dynamic"
    load_balancer_backend_address_pools_ids = "${var.backend_pool_ids}"
  }
}
```

Change variable declaration to require a list:

```hcl
variable "backend_pool_ids" {
  type = "list"
}
```

Then set an empty list in your `environment.tfvars` file:

```hcl
backend_pool_ids = []
```

Would this approach work for you?

**Comment by BijeshSamson11** [comment]
Hi Martin,
This approach very well works for me. Thank you so much.
I have to put the LB backend config as **[**fully qualified azure resource Id**]** in tfvars file.
Appreciating your prompt help....

Thanks,
Bijesh
