### ISSUE TITLE
S3 backend consistency check ineffective due to eventually consistent DynamoDB MD5 read

### ISSUE THREAD

**Issue by smphhh** [hashicorp/terraform#15795]
### Terraform Version
Terraform v0.10.0

### Expected Behavior
Using S3 backend, `terraform plan` immediately after `terraform init` (such as in a CI script) produces a valid plan. 

### Actual Behavior
The plan is produced for the state preceding the init and is thus invalid, applying the plan results in an error referring to state serials.

### Important Factoids
I think this due to S3 eventual consistency, which should be addressed by the DynamoDB state hash check, but the check is defeated by (ironically) not using a strongly consistent read to get the expected hash from DynamoDB [here](https://github.com/hashicorp/terraform/blob/master/backend/remote-state/s3/client.go#L240). See the DynamoDB GetItem documentation [here](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html#DDB-GetItem-request-ConsistentRead).

**Comment by smphhh** [comment]
Looks like my actual problem had nothing to do with consistency but was instead caused by terraform plan unexpectedly modifying state when called with a previously generated plan.

The DynamoDB read should still be strongly consistent though so I'll leave this open.

**Comment by jbardin** [comment]
This will be fixed in the upcoming 0.11.0 release.
