### ISSUE TITLE
aws: Inform user better about security_groups/vpc_security_group_ids

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1581]
The deprecation has been introduced via https://github.com/hashicorp/terraform/pull/1539 - 2 days ago.

It took me quite a while to find out why my security groups are not being attached and it would help a lot to actually print out a UI warning (visible without `TF_LOG=1`) instead of just logging it.

I thought I would send a PR but I'm not sure about how to get the `UiHook` down in the resource code or how to solve it differently... :disappointed:

**Comment by phinze** [comment]
Ah this is a good point. The design of providers does not allow them to do arbitrary UI output. I think I have an idea about how to solve this though. Stay tuned, but tagged as "UX bug" in the meantime.

**Comment by phinze** [comment]
Following up on a few old issues. This is still something we can do a better job of supporting. The Idea I talked about back in April was implementing a resource-level validation function that had access to the full set of attributes so it would have context to be able to make comparisons between multiple fields and yield warnings or errors based on them. That's still on my list, I'll follow up on this issue when that core feature is available.

**Comment by mitchellh** [comment]
We haven't gotten any bugs related to this and the change was over a year ago now so I think its safe to say we can close this and people figured it out. :)
