### ISSUE TITLE
Provisioner remote-exec copying of scripts improvements

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#15821]
Instead of the provisioner `remote-exec.scripts` transferring scripts into the root of `/tmp` using `terraform_{{id}}` files, I suggest Terraform should create a base hidden directory `/tmp/.terraform` and copy scripts into that directory using {{uuid}} as the filename.

    Example:

     /tmp/.terraform
        ├── aa677f2d-2acf-4059-8b2f-a8e01f5d2b42
        ├── d2fea41a-fcd5-44cb-ba1f-a9dd9e8f369d
        └── e1ae489e-c8f7-4ac1-b080-8d8b69d91f81

This has the positive side effect that Terraform can now purge scripts after completing by just `rm -rf /tmp/.terraform`, which currently does not occur. Currently, `remote-exec.scripts` leaves script file orphans in `/tmp`.

```
# /tmp
-rwxrwxrwx 1 ubuntu ubuntu    0 Aug 17 01:57 terraform_362181116.sh
-rwxrwxrwx 1 ubuntu ubuntu    0 Aug 17 01:57 terraform_868697658.sh
```

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. While provisioners, as a whole, aren’t a top priority for the team, when some time is available to focus on them we’re going to use that attention to tackle some long-standing defects.

We are also thinking about how to evolve provisioning for many of our community’s use cases but have yet to take a firm decision on the direction that work will take.

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
