### ISSUE TITLE
segmentation violation on terraform plan

### ISSUE THREAD

**Issue by vectorhacker** [hashicorp/terraform#15833]
Terraform v0.10.1

[crash.log.txt](https://github.com/hashicorp/terraform/files/1229228/crash.log.txt)

**Comment by apparentlymart** [comment]
Hi @vectorhacker! Sorry for this crash and thank you for reporting it.

I think this is the same issue that was fixed in the 0.10.2 release we did this morning. Could you give it a try and see if the problem remains?

**Comment by jbardin** [comment]
Yes, this specific panic is fixed in 0.10.2.

Thanks!

**Comment by vectorhacker** [comment]
Thanks for responding guys! The panic was resolved after upgrading to 0.10.2
