### ISSUE TITLE
Using ${path.module} triggers resource change between users

### ISSUE THREAD

**Issue by stuffandthings** [hashicorp/terraform#15842]
Hi,

When two different users collaborating with Terraform run `terraform apply`, existing resources are marked for change due to file paths differing since we're using absolute paths (which are present in the `tfstate` file.

We've tried using relative paths, but since we're running `terraform apply` from a different directory the file is not found. For context, here's what our directory structure looks like:
```
├── environments
│   ├── production
│   │   ├── production.tf
│   │   └── terraform.tfvars
│   └── staging
│       ├── staging.tf
│       └── terraform.tfvars
└── modules
    └── lambda
        ├── lambda.tf
        └── placeholder.zip
```

### Terraform Version
Terraform v0.10.0

### Terraform Configuration Files
```hcl
resource "aws_lambda_function" "dope_lambda" {
  filename      = "${path.module}/placeholder.zip"
  function_name = "${var.function_name}"
  description   = "${var.description}"
  handler       = "${var.handler}"
  runtime       = "${var.runtime}"
  role          = "${aws_iam_role.lambda_executor_role.arn}"
}
```

### Expected Behavior
It would be nice to be able to specify that a change in the `filename` should not trigger a change to our resource.

It would probably be a little better to actually just ignore the `${path.module}` expansion. I understand this would be problematic if we changed our modules directory structure...

We're passing in a placeholder file to instantiate the lambda, and then using a code pipeline to deploy our actual lambda code.

### Actual Behavior
Lets assume we have two users, `alice` and `bob`. If `alice` had already run `terraform apply` and our `dope_lambda` function was successfully running and `bob` came along and run some non-relevant terraform changes our `dope_lambda` would be marked for change because the `filename` would differ:
```
filename = /Users/alice/terraform/modules/lambda/placeholder.zip => /Users/bob/terraform/modules/lambda/placeholder.zip
```

### Steps to Reproduce
1. Create a lambda resource, giving an absolute `filename` using `${path.module}`
2. Let user A run `terraform apply`
3. Make no changes, and let user B run `terraform plan`
4. The lambda resource will be marked for change

**Comment by neerfri** [comment]
See #7613

**Comment by stuffandthings** [comment]
thanks!
