### ISSUE TITLE
license scan link shows "not found"

### ISSUE THREAD

**Issue by gliptak** [hashicorp/terraform#15853]
The [license scan link](https://app.fossa.io/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fhashicorp%2Fterraform?ref=badge_large) on the bottom of the [README](https://github.com/hashicorp/terraform/blame/master/README.md#L166) links to a page showing:

```
Not Found
Either this page does not exist or you do not have permission access to it
```

Consider setting those results read by all.

Thanks

**Comment by simplytunde** [comment]
looks like license view requires account creation. should be made readable to the public

**Comment by apparentlymart** [comment]
Hi @gliptak, @simplytunde! Sorry for this broken link, and thanks for pointing it out.

The license scanning is still a work in progress as of this writing, and we're working with the vendor to finish this up. The licence scan results should indeed be public and once we're done with the setup we'll find a way to make that be true.

**Comment by pkolyvas** [comment]
I believe this issue is no longer relevant. Closing.
