### ISSUE TITLE
Before destroy hook

### ISSUE THREAD

**Issue by eugen0329** [hashicorp/terraform#15858]
#### Description
It would be great to have a feature to execute a provisioner before a server instance is destroyed to have graceful shutdown.

#### Use case
Say, I have a queue events handler which one should be upgraded to a new instance kind:

```
resource "aws_instance" "consumer" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.nano"
}

# replacing with

resource "aws_instance" "consumer" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.small"
}
```

After planning and applying changes terraform should replace it by removing the old instance and creating a new one. So as not to corrupt something that a worker currently working on I go to the server, send USR1 signal to tell my worker to stop accept new messages, then I wait until all jobs are done and after that I safely replace my old instance.

The first thing that occurred to me about how the feature could be implemented is:
```
lifecycle {
  before_destroy { 
    provisioner "remote-exec" {
       inline = [ "echo 'ABANDON SHIP!!'" ]
    }
  }
}
```

**Comment by nbering** [comment]
There actually is (or was) a feature for this last I checked, though I haven't tried it myself.

https://github.com/hashicorp/terraform/issues/386

This was closed with a merged PR that added soemthing like this:

```
provisioner "remote-exec" {
    ...
    when = "destroy"
}
```

**Comment by eugen0329** [comment]
Yeah, it looks exactly like what I was looking for. Tanks @nbering!
