### ISSUE TITLE
Orchestrate Packer builds with Terraform

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#1586]
The addition of remote modules in Terraform 0.4 adds some exciting possibilities for handoffs between Terraform configurations at different stages in a workflow.

It seems that the existing conventional workflow for packer vs. terraform is to have packer run and produce artifacts, and then feed those artifacts into terraform either as variables or via the Atlas provider.

With remote modules, this process could be turned on its head as follows:

* Add a packer provider to terraform that provides a resource type whose configuration is a packer template, and whose output is the artifact information resulting from the packer build.
* For each project, define its build process as a terraform configuration containing one or more packer build resources.
* After applying the build configuration with terraform, publish the resulting state as a remote module.
* The *deployment* terraform configuration then consumes that remote module to locate the artifacts, making the artifact information available for use in other resources, like setting the AMI for an ec2_instance.

I would concede that a packer build makes a pretty odd terraform resource, since it doesn't converge on a fixed state but rather produces a new set of artifacts for each run. External tooling would be responsible for understanding what should trigger the build configuration to be re-applied, and thus what triggers the creation of new artifacts.

However, I think it's pretty compelling to think of the entire build and deploy process as being a tree of chained terraform states, with the "leafier" nodes being applied more often. This would streamline orchestration tooling by requiring it to understand only two concepts: terraform configurations and terraform states.

While Atlas has packer builds/artifacts as a first-class concept and that smooths over the gap between packer and terraform, I expect this generalized approach would be easier to model with more generic orchestration tools like Jenkins. (Produce the tfstate file as a Jenkins build artifact, and downstream jobs consume the latest tfstate as a remote module.)

**Comment by phinze** [comment]
This is a really interesting idea. You're right that the FSM-iness of remote packer builds does make it conceptually tricky, but there's definitely some potential for cool solutions here.

Tagged as `thinking` to let this percolate a bit.

**Comment by maxenglander** [comment]
:+1:

**Comment by apparentlymart** [comment]
Having let this idea percolate a bit myself I think I've concluded that rather than integrating Packer into Terraform it makes more sense to reimagine Packer as a graph-oriented builder like Terraform, perhaps something like I described in #2789. I think Terraform's functionality is a superset of Packer's aside from some lacking provider support, and it will only become more comparable as the rest of the AWS API features get fleshed out.

**Comment by phinze** [comment]
>  rather than integrating Packer into Terraform it makes more sense to reimagine Packer as a graph-oriented builder like Terraform

Having participated in discussions about the long term direction of Packer w/ Mitchell et. al., I do believe that's the likely direction we are headed in.

**Comment by apparentlymart** [comment]
Given the comment from @phinze above I'm going to close this and let #2789 represent a slightly-wonky take on the "packer using graphs" idea.
