### ISSUE TITLE
invalid or unknown key: origin_keepalive_timeout

### ISSUE THREAD

**Issue by micemuni** [hashicorp/terraform#15864]
We are using terraform to create AWS resources and now we want to set origin_keepalive_timeout and origin_read_timeout value 60 for both. 
but i am getting error. 

Errors: * aws_cloudfront_distribution.cdn-distribution: origin.0.custom_origin_config.0: invalid or unknown key: origin_read_timeout 
* aws_cloudfront_distribution.cdn-distribution: origin.0.custom_origin_config.0: invalid or unknown key: origin_keepalive_timeout 
* aws_cloudfront_distribution.cdn-distribution: origin.1.custom_origin_config.0: invalid or unknown key: origin_keepalive_timeout 
* aws_cloudfront_distribution.cdn-distribution: origin.1.custom_origin_config.0: invalid or unknown key: origin_read_timeout

Terraform version 0.8.8 

Code 

origin {
    origin_id   = "${var.origin_id}"
    domain_name = "${var.domain_name}"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "http-only"
      origin_ssl_protocols   = ["TLSv1", "TLSv1.1", "TLSv1.2"]
	  origin_keepalive_timeout	= 60
	  origin_read_timeout		= 60
    }
  }

**Comment by tombuildsstuff** [comment]
Hey @micemuni 

Thanks for opening this issue :)

From what I can see [this property was only added in Terraform v0.9.5](https://github.com/hashicorp/terraform/pull/13367) - would it be possible to confirm if upgrading to the latest version of Terraform solves this issue?

Thanks!

**Comment by micemuni** [comment]
yes, its working post upgrade the version terraform. Thank you
