### ISSUE TITLE
Add switch to disable import config check

### ISSUE THREAD

**Issue by jzbruno** [hashicorp/terraform#15875]
### Terraform Version
>= 0.10.0

### Actual Behavior

Hello,

We have built up a bunch of tools that generate terraform config for our existing environment. They do this by first getting a list of resource IDs and then running the import command. The config is then generated from the state file.

The latest update to disallow import without matching config will require us to re-write these tools.

Can we add a command line switch to disable the import config check, please?

### Steps to Reproduce

Use `terraform import` with a resource that does not have a config block defined.

**Comment by pkolyvas** [comment]
PR was merged. Closing. Thanks @jzbruno for the contribution.
