### ISSUE TITLE
Feature Request: Please Add an Open Source Redis and Redis Enterprise Provides

### ISSUE THREAD

**Issue by cihanb** [hashicorp/terraform#15879]
Redis is one of the most popular in-memory databases. We have a number of customers asking for Redis and Redis-Enterprise Cloud services support in Terraform?
redis open source details: [http://redis.io](http://redis.io)
redis enterprise cloud details: [https://redislabs.com/resources/documentation/redis-cloud-documentation/](https://redislabs.com/resources/documentation/redis-cloud-documentation)

**Comment by pkolyvas** [comment]
HI @cihanb, 

As per #19607, Redis Labs and existing Redis communities are the place to start for a Redis provider. The Terraform Open Source team here is provider agnostic. 

At the current time HashiCorp doesn't have any plans to release an official provider for Redis. 

Short of that there's always the [community provider](https://www.terraform.io/docs/providers/type/community-index.html) approach. Should someone be willing to take up the cause, we have some great documentation around [extending Terraform](https://www.terraform.io/docs/extend/index.html).
