### ISSUE TITLE
Unable to pass map() produced nested map with "dynamic" value as argument

### ISSUE THREAD

**Issue by modax** [hashicorp/terraform#15915]
Hi,

I see a weird bug when passing interpolated nested map in a list as an argument to `archive_file` `source`. It actually works in some cases, but does not in others. It is hard to explain so I give examples below.

NOTE: I strongly believe this is core bug, `archive_file` is just a convenient enough provider to expose it.

Does not work:

```hcl
data "template_file" "foo" {
  template = "foo"
}

data "archive_file" "test" {
  type = "zip"
  output_path = "foo.zip"

  source = [ "${map(
    "content", "data",
    "filename", "${data.template_file.foo.template}"
  )}"
 ]
}
```
Error:

```
2 error(s) occurred:

* data.archive_file.test: "source.0.content": required field is not set
* data.archive_file.test: "source.0.filename": required field is not set
```

But these actually work:

1. No `map` function call works

```hcl
data "template_file" "foo" {
  template = "foo"
}

data "archive_file" "test" {
  type = "zip"
  output_path = "foo.zip"

  source = [
    {
      "content" = "data"
      "filename" = "${data.template_file.foo.template}"
    }
  ]
}
```
2. No reference to `${data.template_file.foo.template}` works as well

```hcl
data "archive_file" "test" {
  type = "zip"
  output_path = "foo.zip"

  source = [ "${map(
    "content", "data",
    "filename", "foo"
  )}"
 ]
}
```

3. Replaced with `var.foo` works as well:

```hcl
variable "foo" { default = "foo" }

data "archive_file" "test" {
  type = "zip"
  output_path = "foo.zip"

  source = [ "${map(
    "content", "data",
    "filename", "${var.foo}"
  )}"
 ]
}
```

Tested with:

Terraform v0.9.9
Terraform v0.10.2

on Linux x64.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by modax** [comment]
By the way, I have hit this bug while trying to dynamically construct list of files via `source`. I.e. number of source files and filenames come from variables and some values of source (mostly `content`) are rendered via `template_file`.

**Comment by apparentlymart** [comment]
Hi @modax! Sorry this doesn't work as expected.

At this time, it is not possible to dynamically produce child blocks in this way. This is being discussed over in #7034, and is something we're planning to address (though not necessarily with the syntax/approach offered in that issue) as part of a set of forthcoming improvements to the configuration language.

I'm going to close this just to keep a consolidated discussion in #7034. Thanks for reporting this!
