### ISSUE TITLE
Terraform required_version not checked for init

### ISSUE THREAD

**Issue by nbering** [hashicorp/terraform#15917]
### Terraform Version
0.9.11, 0.10.0

### Terraform Configuration Files
Also tested with constraint as "~> 0.11" and terraform v0.10.0.
```hcl
terraform {
  required_version = "~> 0.10"
  backend "s3" {
    bucket         = "****"
    key            = "projectname/terraform.tfstate"
    region         = "ca-central-1"
    dynamodb_table = "****"
  }
}
```

### Expected Behavior
Should halt init execution with terraform 0.9.11 because the terraform required version constraint is not satisfied.

### Actual Behavior
Continues init operation anyway.

Terraform plan fails as expected.

### Steps to Reproduce
1. Apply version constraint to terraform config.
2. Run `terraform init`.

### Important Factoids
This is more of a concern for future-proofing configuration to protect against changes that break older versions mangling or losing state than anything else. As the init command increases in complexity so too does the likelihood that a configuration would need to be protected from init operations by older or newer versions.

**Comment by apparentlymart** [comment]
Hi @nbering! Sorry for this oversight.

Agreed that this should be checked during `terraform init`, in addition to the other places it's checked.

**Comment by nbering** [comment]
@apparentlymart No need to apologize, no harm done. Just figured it was an oversight as you said. Thanks for looking at it.
