### ISSUE TITLE
HCL Conditional always requires true and false variables exist

### ISSUE THREAD

**Issue by dtzar** [hashicorp/terraform#15912]
### Terraform Version
10.2

### Terraform Configuration Files
```hcl
module "tf-azurerm-vnet" {
  source   = "../tf-azurerm-vnet"
  prefix   = "conditional"
  location = "${var.location}"
}

resource "azurerm_resource_group" "azlb" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
  tags     = "${var.tags}"
}

resource "azurerm_lb" "azlb" {
  name                      = "${var.prefix}-lb"  
  resource_group_name       = "${azurerm_resource_group.azlb.name}"
  location                  = "${var.location}"
  frontend_ip_configuration {
    name                 = "FrontEndIPConfiguration"
    public_ip_address_id = "${var.create_publicip == "1" ? azurerm_public_ip.azlb.id : "" }"
    subnet_id            = "${var.create_publicip == "1" ? "" : module.tf-azurerm-vnet.azurerm_subnet_ids[0] }"
    private_ip_address_allocation = "${var.create_publicip == "1" ? "dynamic" : "dynamic" }"
  }
}

resource "azurerm_public_ip" "azlb" {
  count                        = "${var.create_publicip}"
  name                         = "${var.prefix}-publicIP"
  location                     = "${var.location}"
  resource_group_name          = "${azurerm_resource_group.azlb.name}"
  public_ip_address_allocation = "${var.public_ip_address_allocation}"
}
```

### Expected Behavior
If the `create_publicip` variable is set to `0` then the conditional HCL should not need to evaluate whether azurerm_public_ip.azlb.id exists or not since it is not going to be set/used with that condition.  `terraform plan` or `terraform apply` should work.

### Actual Behavior
Terraform complains that the azurerm_public_ip.azlb.id doesn't exist - because it doesn't exist due to the desire to not create that resource as noted by the ` count                        = "${var.create_publicip}"`  

The exact error terraform outputs is the following:
```
Error running plan: 1 error(s) occurred:
* azurerm_lb.azlb: 1 error(s) occurred:
* azurerm_lb.azlb: Resource 'azurerm_public_ip.azlb' not found for variable 'azurerm_public_ip.azlb.id'
```

### Steps to Reproduce
0. Setup [Azure provider credentials / ENV variables](https://www.terraform.io/docs/providers/azurerm/index.html)  Note:  This problem has _nothing_ to do with the Azure provider - this is just the sample where it is used to reproduce below. 
1. `git clone https://github.com/dtzar/terraform-provider-azurerm.git -b conditional`
2. `cd /examples/conditional-flow`
3. `terraform init`
4. `terraform get`
5. `terraform plan`

### References
None that I could find.

**Comment by apparentlymart** [comment]
Hi @dtzar! Sorry for this limitation.

This issue is already tracked as #15605, and upstream in hashicorp/hil#50. We're planning to fix this as part of a set of language fixes and improvements in the near future, since there are a number of issues that trace back to some details of how the language is implemented and so require some lower-level changes.

The other two issues above contain some details and workarounds within the current constraints. I'm going to close this issue just to consolidate the discussion in those existing issues. Thanks for reporting this!
