### ISSUE TITLE
Terraform should clean clients for chef vault

### ISSUE THREAD

**Issue by joerg** [hashicorp/terraform#15921]
When provisioning a server with chef and using chef-vaults it happens that if you destroy and recreate a server the vault is not updated and the new machine can not read/decrypt the vault.

### Terraform Version
 0.10.2

### Expected Behavior
Vaults should be encrypted for new client.

### Actual Behavior
The old chef client gets deleted [1] from the server but the vault stays encrypted for the old client.
This is tricky. There are options to to delete unknown clients (--clean in [2]) and such, but should terraform potentially clean access for clients that it does not actually touch?
We have this problem here from time to time whenever we try to recreate resources for testing restores and such and it is quite annoying.

[1] https://github.com/hashicorp/terraform/blob/0c69e466496e86b23e0024889d01efa074b75035/builtin/provisioners/chef/resource_provisioner.go#L527
[2] https://github.com/hashicorp/terraform/blob/0c69e466496e86b23e0024889d01efa074b75035/builtin/provisioners/chef/resource_provisioner.go#L563

**Comment by supergicko** [comment]
@radeksimko fyi: i created a pr for this issue #16357
