### ISSUE TITLE
Adding different metadata to modules

### ISSUE THREAD

**Issue by joe-boyce** [hashicorp/terraform#15922]
Hi there,

Is there an easy way to make use of modules but add additional values for cases where something additional is required? for example adding different metadata to instances/clusters

**Use case**

I have the following example resource:

```
resource "google_compute_instance" "instance" {
  project       = "${var.project_name}"
  count         = "${var.count}"
  name          = "${element(var.name, count.index)}-${element(var.zones, count.index)}-${count.index + 1}"
  zone          = "${element(var.zones, count.index)}"
  machine_type  = "${element(var.type, count.index)}"
  can_ip_forward = "${var.ipforward}"
  
  tags          = ["${var.tags}"]
  
  disk {
    image       = "${element(var.disk_image, count.index)}"
    size        = "${element(var.disk_size, count.index)}"
    auto_delete = "${element(var.disk_autodelete, count.index)}"
  }
  
  network_interface {
    subnetwork_project = "${var.subnetwork_project}"
    subnetwork  = "${var.subnetwork}"
    address     = "${var.address}"
  access_config {
      // Ephemeral IP
    }
  }
  
  service_account {
    email  = "${var.serviceaccount}"
    scopes = "${var.serviceaccount_scopes}"
  }
  
  metadata {
    startup-script-url = "${var.startup_script_url}"
  }
}
```

Used as module it looks like this:

```
module "foobar_cluster" {
    source = "../../../../../global/modules/instance"
    project_name = "*project*"
    name = ["name"]
    count = "${var.count}"
    zones = ["us-central1-a", "us-central1-b", "us-central1-c"]
    type = ["g1-small"]
    disk_image = ["someimage"]
    disk_size = ["50"]
    subnetwork = "somenetwork"
    serviceaccount = "serviceaccount"
    serviceaccount_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
    startup_script_url = "gs://bucket/${module.startup_script.name}"
}
```

Along with the startup-script-url I would also like to pass more metadata but it will change from instance to instance/cluster to cluster, for example we have teams who don't wish to pass any metadata VS teams who wish to pass metadata such as:

secrets-bucket = foo
deploy-bucket = bar

Is there anyway of handling this? or is it a case of having different modules created each time with the keys set each time

Thanks,

Joe

**Comment by apparentlymart** [comment]
Hi @joe-boyce,

Since `metadata` is defined as a map, I think it may work to pass the metadata into your module as a variable:

```
variable "instance_metadata" {
  type = "map"
  default = {}
}

resource "google_compute_instance" "instance" {
  # ...

  metadata = "${merge(var.instance_metadata, map("startup-script-url", var.startup_script_url))}"
}
```

Unfortunately at this time, for legacy reasons, Terraform has some quirks with passing maps and a rather-inconvenient syntax for _using_ them; these are things we're aware of and are planning to address soon.

**Comment by joe-boyce** [comment]
Thanks Martin appreciate the quick response, that seems to be working well!
