### ISSUE TITLE
plugins use too much disk space

### ISSUE THREAD

**Issue by jsravn** [hashicorp/terraform#15949]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please try upgrading because your issue may have already been fixed.

`Terraform v0.10.2`

### Terraform Configuration Files
```hcl
provider "aws" {
  region  = "${var.region}"
  version = "~> 0.1"
}
```

### Expected Behavior
What should have happened?

Disk space shouldn't be so large.

### Actual Behavior
What actually happened?

From having a single provider (aws), disk usage is 180M from the plugins local to the project.

```
[james:...rraform/plugins/linux_amd64]$ ls -lh
total 178M
-rwxr-xr-x 1 james james 162 Aug 22 13:41 lock.json
-rwxr-xr-x 1 james james 87M Aug 17 15:09 terraform-provider-aws_v0.1.4_x4
-rwxr-xr-x 1 james james 91M Aug 17 15:09 terraform-provider-terraform_v0.1.0_x4
```

This is exacerbated with many terraform projects (we break up into several projects to make dev/management easier). Each project adds its own 180M of binary plugins. Prior to this the terraform binaries were shared.

I'm not sure this was a great design idea. I think we need a mechanism of sharing plugin binaries.

**Comment by jbardin** [comment]
Hi @jsravn,

Thanks for opening the issue. The decision to split out all providers was not taken lightly, and provides many benefits, which we feel will far outweigh the drawbacks in the future. While we did combine the binaries for a few releases, the process did nock look sustainable in the long run. 

While the automatic installation of binaries will download a separate copy for each configuration, you can certainly share plugins between projects, by either using the the `-plugin-dir` option to the `init` command, or the global `~/.terraform.d/plugins/` directory. 

It does appear that the released provider binaries are at least 30% larger than they should be though. We'll check on on the release process to make sure they are better optimized for their next releases.

**Comment by jsravn** [comment]
@jbardin Okay thanks, I was unaware of the plugin-dir. It'd be nice if this was automatic (eg downloads/caches into some global location), but I'm happy with setting this flag for now. Cheers!

**Comment by jbardin** [comment]
Great!

We updated the release process as well, so future provider releases will be stripped with the same options as the `terraform` release.

**Comment by tmccombs** [comment]
Would it be feasible to have some kind of caching mechanism by default so that if multiple terraform projects use the same provider the plugin is automatically shared between them by default? (maybe putting the plugin in ~/.terraform.d/plugins by default?)

**Comment by teamterraform** [comment]
@tmccombs: 

I think you are looking for the [Provider Plugin Cache](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache)

**Comment by tmccombs** [comment]
thanks!
