### ISSUE TITLE
Conditionals in resources configuration

### ISSUE THREAD

**Issue by patrick91** [hashicorp/terraform#15974]
It is possible to have conditional configurations for resource options?
I'm trying to have a lambda@edge function associated to a cloudfront distribution, 
the only issue I have is that I want the function the be associated only on a single
environment. Is this currently possible?

```
resource "aws_cloudfront_distribution" "s3_distribution" {
  # this should be optional:  
  lambda_function_association { ... }
}
```

**Comment by apparentlymart** [comment]
Hi @patrick91!

I think what you're looking to do here is the same as for #15986. In which case, sadly it is not currently possible, but is something we are planning to support as part of some configuration language improvements we're currently designing.

We'll be posting more updates in #15986 once we have a concrete proposal to discuss. In the mean time, others have worked around this by duplicating the entire resource and using conditional `count` to activate either one or the other; I know this is not an ideal solution by any means, but it gives a way to express what you need to express here until this is better supported.

Thanks for this question! I'm going to close this now just to keep this discussion consolidated. Stay tuned to the other issue for more updates.

**Comment by patrick91** [comment]
@apparentlymart thanks! I didn't find that issue, sorry :)

PS. if anyone needs it, I'm assigning the lambda function to all the distributions and checking the distribution id inside the lambda function, not ideal but works :)
