### ISSUE TITLE
Failed to load backend

### ISSUE THREAD

**Issue by chothia** [hashicorp/terraform#15986]
Hi there,

I recently upgraded my terraform version from 0.9.1 to 0.10.3 and everything was working fine before.

Whenever I run a terraform command (i.e. terraform plan) I get this error

```
Error configuring the backend "s3": No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

Any idea what the issue is? I am running the 64 bit Windows version using cygwin. When I run the same code base on my Mac laptop (0.10.3), everything works fine.

The backend config looks like:

```
terraform {
  backend "s3" {
    bucket  = "bucket"
    key     = "pathTo/terraform.tfstate"
    region  = "us-west-2"
    encrypt = "true"
  }
}
```

**Comment by jbardin** [comment]
Hi @chothia,

Sorry, I'm not sure what could be happening here. Seeing how the configuration isn't being shown as changed, and there are no credentials or profile shown in the config, the credentials must have been picked up automatically from the environment. Were you using the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables, or were you loading a default profile from the aws credentials file?

**Comment by chothia** [comment]
Hi @jbardin,

Thanks for the reply. We have a few different configuration files (.tf) and they each have the same backend configuration as above.

Some of them use the default profile from the AWS credentials file (~/.aws/credentials, where the home directory is the cygdrive directory) and others use the named profile which I set via the AWS_PROFILE environment variable. However, in both named and default profile cases, I get the error described above.

I also took a look at https://github.com/hashicorp/terraform/issues/13589 and I some solutions said to edit the terraform.tfstate file and to add the profile there. I tried that as well, but it didn't work.

Thanks again for your help, and let me know if I can try anything else.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
