### ISSUE TITLE
Can't use locals in resource count

### ISSUE THREAD

**Issue by sl1pm4t** [hashicorp/terraform#15987]
Hi there,

Thanks for the very useful `locals` feature.
Currently it's not possible to use a `local` variable in a `count` attribute:

### Terraform Version
v0.10.3

### Terraform Configuration Files
```hcl
locals {
  echolist = ["one", "two", "three"]
}

resource "null_resource" "echo" {
  count = "${length(local.echolist)}"

  provisioner "local-exec" {
    command = "echo ${element(local.echolist, count.index)}"
  }
}
```

### Expected Behavior
Terraform should try to create 3 instances of the `null_resource.echo` resource.

### Actual Behavior
Terraform outputs this error:
```
1 error(s) occurred:

* module root: 1 error(s) occurred:

* Internal error. Unknown type in count var in null_resource.echo: *config.LocalVariable
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @sl1pm4t! Sorry for the oversight here, and thanks for reporting this.

I think the miss here was not dealing with the special additional validation that exists for this field due to how "early" the count is dealt with. I'll take a look.

**Comment by sl1pm4t** [comment]
Wow quick work @apparentlymart - thanks!
