### ISSUE TITLE
Destroy tries to destroy "data" type resources

### ISSUE THREAD

**Issue by gvasquez-waypoint** [hashicorp/terraform#15996]
destroy command lists the "data" related resources as possible items to delete.

### Terraform Version
Terraform v0.10.2

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_db_parameter_group" "mysql-sonar" {
  name   = "mysql-sonar"
  family = "mysql5.6"

  parameter {
    name  = "max_allowed_packet"
    value = "268435456"
  }
}

data "aws_vpc" "devops" {
  tags {
    Name = "DevOps"
  }
}

data "aws_subnet_ids" "devops-subnet" {
  vpc_id = "${data.aws_vpc.devops.id}"
}

resource "aws_db_subnet_group" "sonarqube" {
  name       = "sonarqube"
  subnet_ids = ["subnet-456", "subnet-123"]

  tags {
    Name = "Sonar subnet group"
  }
}

resource "aws_db_instance" "sonarqube" {
  allocated_storage         = 5
  storage_type              = "gp2"
  engine                    = "mysql"
  engine_version            = "5.6.27"
  instance_class            = "db.t2.micro"
  name                      = "sonar"
  username                  = "root"
  password                  = "mypass"
  parameter_group_name      = "mysql-sonar"
  publicly_accessible       = "true"
  identifier                = "sonarqube"
  final_snapshot_identifier = "sonarqube"
  skip_final_snapshot       = "true"
  backup_window             = "05:00-06:00"
  backup_retention_period   = "7"
  availability_zone         = "us-east-1b"
  multi_az                  = "false"
  db_subnet_group_name      = "${aws_db_subnet_group.sonarqube.id}"
}

```

### Debug Output
Full debug output can be obtained by running Terraform with the environment variable `TF_LOG=trace`. Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.

Debug output may contain sensitive information. Please review it before posting publicly, and if you are concerned feel free to encrypt the files using the HashiCorp security public key.

### Crash Output
If the console output indicates that Terraform crashed, please share a link to a GitHub Gist containing the output of the `crash.log` file.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
terraform destroy
data.aws_vpc.devops: Refreshing state...
data.aws_subnet_ids.devops-subnet: Refreshing state...

The Terraform destroy plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning.
Resources shown in red will be destroyed.

  - data.aws_vpc.devops

  - data.aws_subnet_ids.devops-subnet

Do you really want to destroy?
  Terraform will delete all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

**Comment by apparentlymart** [comment]
Hi @gvasquez-waypoint! Sorry for this confusion behavior.

This bug was actually just fixed as part of #15884, so this should be included in the next release. Thanks for reporting it!
