### ISSUE TITLE
Pessimistic version constraint for plugins

### ISSUE THREAD

**Issue by grv87** [hashicorp/terraform#16005]
I propose to add additional version constraints for plugins, especially pessimistic.
The same way as in Bundler etc.:
```
provider "aws" {
  version = "~> 0.1"
}
```

**Comment by nbering** [comment]
Already implemented.
[Provider Versions](https://www.terraform.io/docs/configuration/providers.html#provider-versions)

**Comment by grv87** [comment]
Thanks for the links!

I tried the same, but somehow got an error and decided they were not implemented yet.
Sorry for the disturbance.
