### ISSUE TITLE
0.10.3 - Remote state lock release error, every apply

### ISSUE THREAD

**Issue by samirageb** [hashicorp/terraform#16012]
This behavior appears to have started with terraform 10.3 and the only workaround I have atm is to disable state locking.

### Terraform Version
0.10.3
go runtime 1.9

### Affected Resource(s)
- azurerm_resource_group
- anything azure really, this this is tied to remote state

### Terraform Configuration Files
```hcl
variable "rg_name"                      { }
variable "location"                     { }

# Remote state data source, no interpolations allowed
terraform {
  backend "azurerm" {
    key = "***.terraform.tfstate"
    storage_account_name = "***"
    container_name       = "terraform-state"
  }
}

# Configure TF provider: Microsoft Azure
provider "azurerm" {
  version         = "~> 0.1"
  subscription_id = "***"
  client_id       = "***"
  client_secret   = "***"
  tenant_id       = "***"
}

resource "azurerm_resource_group" "bug_eastus" {
  name     = "${var.rg_name}"
  location = "${var.location}"
}
```

### Debug Output
[Terraform Init Output](https://gist.github.com/samirageb/01ae95a16c5342e8b47c6d9781fcb818)

[Terraform Apply Output](https://gist.github.com/samirageb/d31c2e4414d72f8ba2f80bfbb79a7027)

### Expected Behavior
Command returns upon completion

### Actual Behavior
-Azure Rg successfully gets provisioned
-Lease on remote .tfstate Azure blob still shows 'leased', and must be manually broken

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
-I have confirmed this happens regardless of Azure storage account encryption at rest
-Appending a `-lock=false` to all terraform commands is the current workaround
-The repro steps were conducted on a fresh directory, with no .terraform folder created, or existing remote state file.
-Eventually this issue results in a .errorstate, which CAN be succesfully pushed if I manually delete the blob lease on the .tfstate blob

### References
Originally posted [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/303) but told this behavior is part of TF core.

**Comment by attachmentgenie** [comment]
we see this behavior too using terraform 0.10.3 and azure plugin terraform-provider-azurerm_v0.1.5_x4

**Comment by tombuildsstuff** [comment]
Hey @samirageb @attachmentgenie

Thanks for reporting this issue - I've taken a look into this and opened PR #16015 which includes a fix for this issue.

Thanks!
