### ISSUE TITLE
Bundled providers fail with "new or changed plugin executable"

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform#16017]
I've built a Docker image with bundled provider plugins in to allow our CI pipeline to run faster without having to download the provider at every single run and to avoid having to run a `terraform init` on every folder that I wish to run `terraform validate` on (used for some super basic linting along with `terraform fmt`).

This seems to work nicely locally running the Docker image but for some reason I'm getting:
```
Error: 1 error(s) occurred:

* provider.aws: new or changed plugin executable
```
when I run it in my CI pipeline (using Gitlab CI) and I can't quite work out what's causing it because I don't really understand what the error is complaining about.

For reference the Docker image is built with the following Dockerfile (we're also using the AWS CLI in some places so this gets bundled in along with make):
```Dockerfile
FROM golang:alpine AS terraform-bundler-build

RUN apk --no-cache add git unzip && \
    go get -d -v github.com/hashicorp/terraform && \
    go install ./src/github.com/hashicorp/terraform/tools/terraform-bundle

COPY terraform-bundle.hcl .

RUN terraform-bundle package terraform-bundle.hcl && \
    mkdir -p terraform-bundle && \
    unzip -d terraform-bundle terraform_*.zip

####################

FROM python:alpine

COPY company-root-ca-cert.crt /usr/local/share/ca-certificates/company-root-ca-cert.crt

RUN apk add --no-cache ca-certificates git make && \
    pip install awscli && \
    update-ca-certificates

COPY --from=terraform-bundler-build /go/terraform-bundle/* /usr/local/bin/
```

The terraform-bundle.hcl looks like:
```
terraform {
  version = "0.10.3"
}

providers {
  aws        = ["~> 0.1.0"]
  postgresql = ["~> 0.1.0"]
  random     = ["~> 0.1.0"]
  template   = ["~> 0.1.0"]
}
```
Running `ls -la /usr/local/bin | grep terraform` inside the container both locally and inside Gitlab CI shows the providers are all in the same directory as the Terraform binary (they were all unzipped to /usr/local/bin in the first stage of the Dockerfile):
```
-rwxrwxr-x    1 root     root      53293024 Sep  4 15:14 terraform
-rwxr-xr-x    1 root     root      91025500 Sep  4 15:14 terraform-provider-aws_v0.1.4_x4
-rwxr-xr-x    1 root     root      18291026 Sep  4 15:14 terraform-provider-postgresql_v0.1.0_x4
-rwxr-xr-x    1 root     root      17232129 Sep  4 15:14 terraform-provider-random_v0.1.0_x4
-rwxr-xr-x    1 root     root      17311776 Sep  4 15:14 terraform-provider-template_v0.1.1_x4
```

I appreciate that this is probably caused by Gitlab CI somewhere but I can't see how or why this error is being thrown at all so a pointer in that direction will probably be enough to help me solve it.

**Comment by apparentlymart** [comment]
Hi @tomelliff! Sorry for this confusing result.

I think what is going on here is that although the bundle tool avoids re-downloading the providers, it doesn't deal with other steps that `terraform init` does, one of which is to select an available plugin executable to meet each provider requirement in the configuration and remember what was selected in a local lock file.

The intent of this mechanism is to ensure that the selected plugins can only change with an explicit `terraform init`; if the system state looks different than when `init` was run (or, in your case, if `init` was never run) then Terraform produces this error to encourage you to run `terraform init` again.

Terraform checks for an environment variable called `TF_SKIP_PROVIDER_VERIFY` which you can set to `1` to bypass this behavior and have it just accept any binary it finds that meets the version constraints. This mechanism is there primarily for provider developers (so they don't have to re-`init` each time they make a new build of a provider) but I think it should get you the behavior you want here too.

Currently `terraform validate` is not really designed to run in an un-initialized state and so it may run into other problems, separate from the provider lock. The proposal in #15895 is aimed at making `terraform validate` a good solution for these quick static-validation use-cases, including making it work (possibly with some validations disabled, as necessary) when the working directory is not initialized or not all of the required plugins are available.

**Comment by tomelliff** [comment]
Hi Martin, thanks for getting back to me.

Yeah I'd clicked last night that the only difference was that in the CI pipeline I had a freshly un-init'ed workspace so it was probably that. Running the validate command with `TF_SKIP_PROVIDER_VERIFY=1` seems to work fine so thanks for that.

**Comment by Nmishin** [comment]
I saw an error like this, and "terraform providers" show me:
`terraform providers 
 .
├── module.accuiprod 
│      ├── provider.consul 
│      ├── provider.external (from state) 
│      ├── provider.google 
│      ├── provider.null 
│      └── provider.template 
└── module.accuistage     
       ├── provider.consul     
       ├── provider.google     
       ├── provider.null     
       └── provider.template`

seems I can fix this strange behavior, by added terraform_version.tf.json file with specifying providers versions.

**Comment by Nmishin** [comment]
After specifying providers versions:
```
terraform providers
.
├── provider.external 1.0.0
├── module.accuiprod
│   ├── provider.consul
│   ├── provider.external (from state)
│   ├── provider.google
│   ├── provider.null
│   └── provider.template
└── module.accuistage
    ├── provider.consul
    ├── provider.google
    ├── provider.null
    └── provider.template
```
