### ISSUE TITLE
New Provider: G Suite

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/terraform#16013]
There is a Github provider which allows to configure permissions. Very useful! I am looking to manage permissions on [G Suite](https://gsuite.google.com) in a similar way and it doesn't look there's a provider for it. What do you think about implementing a provider for that? Has it been discussed?

**Comment by JensRantil** [comment]
Oh, here's documentation for API: https://developers.google.com/admin-sdk/directory/

**Comment by morgante** [comment]
Here is one: https://github.com/DeviaVir/terraform-provider-gsuite

**Comment by paultyng** [comment]
Closing, as there are a couple community ones that exist for this.
