### ISSUE TITLE
provider/aws: Add "aws_security_group" -> ingress -> owner_id

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1602]
http://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-ingress.html -> `--group-owner (string)`
https://github.com/awslabs/aws-sdk-go/blob/9f2cef45db969a146efb8b6808de438d8d4268b8/service/ec2/api.go#L7003

It is possible to define account ID of the source security group and Terraform already supports similar field in [`aws_db_security_group`](https://www.terraform.io/docs/providers/aws/r/db_security_group.html).

**Comment by catsby** [comment]
Hey @radeksimko – we don't actually set that field in the `AuthorizeSecurityGroupIngressInput`; we only set the `GroupID` and the slice of `IPPermissions`.

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_security_group.go#L453

We do however split the `id` of each security group based on `/` here:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/structure.go#L76

so if your security group id is `someotheruser/sg-12345`, we should then correctly set the owner id. I _believe_ that effectively gets you what you're requesting, albeit it not documented :frowning: 

Does that get you what you need? Or am I off? I'll be honest that I'm not as familiar with the DB Security Groups

**Comment by radeksimko** [comment]
That's actually quite a nice implementation... :+1: it just needs documenting then.

**Comment by josephholsten** [comment]
should this doc just be added to https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/aws/r/security_group.html.markdown? or are there other places it needs to be added?
