### ISSUE TITLE
Support AWS Network Load Balancers (NLB)

### ISSUE THREAD

**Issue by itsdalmo** [hashicorp/terraform#16047]
AWS has just released Network Load Balancers (NLB). Seems to use the same API as Application Load Balancers, but it would take some work to add support for this in Terraform?

See:
https://aws.amazon.com/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/
http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateLoadBalancer.html

**Comment by itsdalmo** [comment]
https://github.com/terraform-providers/terraform-provider-aws/issues/1618 <- Issue in the correct place.

**Comment by MicahRamos** [comment]
Why was this issue closed? Does Terraform already support NLB?

**Comment by mechastorm** [comment]
The issue is already being covered in the provider specific repo https://github.com/terraform-providers/terraform-provider-aws/issues/1618
