### ISSUE TITLE
Possible regression where Terraform loses track of resources from v0.10.0 → v0.10.1 in custom provider

### ISSUE THREAD

**Issue by eripa** [hashicorp/terraform#16043]
I'm sorry for the sparse information, but as of now the provider is developed in-house and not available to the public, yet.  Let me know if I can provide more details

### Terraform Version

Terraform v0.10.4

### Expected Behavior

The created resource (which still works fine) should be added to `terraform.tfstate` to be tracked by Terraform

### Actual Behavior

After object creation the state file is left empty, causing Terraform to want to recreate the resource on each run, and any dependent resources to fail (when referring to variables/fields).

### Steps to Reproduce

Update `github.com/hashicorp/terraform` dependency from `v0.10.0` to `v0.10.1` and try and create a resource using `terraform init && terraform apply`

Downgrading the dependency back to v0.10.0 makes it work again. v0.10.2 and up also fails.

### Important Factoids

The provider is developed with inspiration from the `aws` provider. After object creation the provider will run resourceUpdate and resourceRead to make sure to populate all fields.

At the end of the resourceRead, right before exiting the provider, the `d *schema.ResourceData` object contains all the data that it's supposed to (including the valid ID of the resource).

**Comment by jbardin** [comment]
Hi @eripa,

Unfortunately there's not much we can do here without some data to work with.

There were very few changes in 0.10.1, and should have mostly minor issues from 0.10.0. Can you bisect the history and find the exact commit that breaks?

Can you find a way to replicate the issue with a minimal provider implementation which you can release, i.e. something like a `null_resource` ?

**Comment by eripa** [comment]
Thanks for the quick reply @jbardin!

I've been running the bisect, and this is the commit that I've ended up with: ca68723c91d6cf70bef5db9343dd23edfa28f5cb

I'm not well versed in the internals, but as I mentioned earlier it seems like the resourcedata is lost somewhere after my provider returns.

If the above commit doesn't help I'll see if I can try and build something that reproduces it.

**Comment by jbardin** [comment]
@eripa,

Thanks, that was also the only commit I could find in that area, but I'm not sure how that changes anything for you. I'll have to think on this for a bit, but let me know if you come up with a way to reproduce the issue. 

There are actually very few providers using this code at the moment, so there could be a latent bug that hasn't surfaced. Unless you actually need some later changes in helper/schema, you're not losing out on anything by sticking to 0.10.0 in the provider's dependencies, as providers themselves don't directly depend on any of the terraform internals.

**Comment by eripa** [comment]
Thanks again. I have reverted the dependency back to v0.10.0 for now, so it's no hurry.

I'll see if I can trigger it in a generic way tomorrow.

**Comment by jbardin** [comment]
If it helps, I tested a couple providers (notably the AWS provider) with the most recent core changes, and I couldn't get anything to break in this manner. I would try to look for some difference in the way you're using the helper/schema package.

**Comment by paddycarver** [comment]
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, or continue to have the problem described, please feel free to reply to this issue and we'll reopen it. Thanks!
