### ISSUE TITLE
hcl parser escape behavior is broken (regression), cannot use variables or functions with content that requires escaping 

### ISSUE THREAD

**Issue by mrproper** [hashicorp/terraform#16046]
### Terraform Version
v0.10.4

### Terraform Configuration Files
```hcl

variable "uris" { "default" = "/v1/foo/\\d+/bar" }
```

### Expected Behavior

when using an escaped backslash, i expect the escaped backslash to be escaped in the resource application

### Actual Behavior
it turns the escaped backslash into a literal:

`\\`

Rather than

`\`

It would be nice to also have a raw interpolated delimiter in HCL
ie:
`variable "uris" { "default" = '/v1/foo/\d+/bar' } `

### Steps to Reproduce
Add a string in a resource that has an escaped backslash, apply it to anything.

### References
- #6359

**Comment by mrproper** [comment]
I have just found out if i do the following it works just fine:
`
variable "uris" { "default" = <<EOF
/v1/foo/\d+/barEOF
}
`

But this is obviously not ideal

**Comment by apparentlymart** [comment]
Hi @mrproper! Sorry this isn't working properly.

This is strange because nothing has changed in HCL or HIL for quite a while. You mentioned in the summary that this seems like a regression; could you share the most recent version number you were using where this worked? That could help narrow down what has changed here.

**Comment by mrproper** [comment]
Oh perhaps i should have been a bit more clear...it LOOKS like a regression in the fact that #6359 has it as solved in a previous release.
I have tested this more thoroughly now, it looks like i've been mistaken.
The resource i was using was a kong provider, it seems that that module doesnt url encode the field that im putting a regex in.

So when terraform plan outputs what its going to do, it SHOWS the value being double slashed, but that is only on the display.
Using this example:
`resource "local_file" "foo" {
  #content  = "/v1/foo/bar"
  content  = "/v1/foo/\\d+/bar"
  filename = "/tmp/foo.txt"
}
`
a plan shows the change from the original content to the new content being:
`
Terraform will perform the following actions:

-/+ local_file.foo (new resource required)
      id:       "549e54d9f1d9ebb64da276f17b3434ece09bed82" => <computed>
      content:  "/v1/foo/bar" => "/v1/foo/\\d+/bar"
      filename: "/tmp/foo.txt" => "/tmp/foo.txt"


Plan: 1 to add, 0 to change, 1 to destroy.
`
which seems to show that the content its going to change it to looks like a literal string with a double slash but it does not in the end result.
