### ISSUE TITLE
unknown function called: contains

### ISSUE THREAD

**Issue by avijitcgit** [hashicorp/terraform#16053]
Hi,

I am getting error while trying to use "contains" function as described at "https://www.terraform.io/docs/configuration/interpolation.html#contains-list-element-"

Error:
unknown function called: contains

Terraform version:
Terraform v0.9.3

**Comment by apparentlymart** [comment]
Hi @avijitcgit! Sorry that isn't working as expected.

Could you please share the portion of your configuration that refers to this function? That may help us to understand why this is happening.

**Comment by apparentlymart** [comment]
Actually, looking at your message again I see that you are using Terraform v0.9.3.

The `contains` function was added in v0.10.0, so it's necessary to upgrade Terraform to use this function.

**Comment by avijitcgit** [comment]
variable "s3_backup_zone" {
  type = "list"
  default = ["us-west-1","us-east-1"]
}

variable "aws_info" {
  type = "map"
  default {
    region = "us-west-1"
  }
}
resource "aws_efs_file_system" "backup_file_system" {
    count = "${contains(var.s3_backup_zone, var.aws_info["region"]) ? 0 : 1}"
    performance_mode = "generalPurpose"
    tags {
    Owner       = "Test"
    Name        = "Test-efs"
  }

**Comment by avijitcgit** [comment]
Got it.
Thanks for the info.

**Comment by apparentlymart** [comment]
Sorry I didn't catch the version thing on the first read! We have plans to add better version annotations to the docs in future to help make these things more obvious.

I think this is explained now so I'm going to close this, though indeed please let me know if you have other questions here.
