### ISSUE TITLE
Multi-region lambda inconsistency in creation and deletion

### ISSUE THREAD

**Issue by jonathan-kosgei** [hashicorp/terraform#16062]
I have the following module

```
variable "region" {
    description = "Region to deploy to."
}

variable "access_key" {
    description = "access_key."
}

variable "secret_key" {
    description = "secret_key"
}

variable "role" {
    description = "role"
}

variable "s3_file" {
    description = "s3_file"
}

provider "aws" {
    region = "${var.region}"
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
}
resource "aws_lambda_function" "function" {
  s3_bucket        = "function-zip"
  s3_key           = "${var.s3_file}"
  function_name    = "function"
  role             = "${var.role}"
  handler          = "function"
  runtime          = "python2.7"
  publish          = "true"
}
```

Which I'm calling multiple times, for each AWS region with
```
module "us-east-1" {
    source = "./modules/multi-region"
    region = "us-east-1"
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
    role       = "${aws_iam_role.lambda-role.arn}"
    s3_file    = "${aws_s3_bucket_object.function.id}"
}
module "us-east-2" {
    source = "./modules/multi-region"
    region = "us-east-2"
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
    role       = "${aws_iam_role.lambda-role.arn}"
    s3_file    = "${aws_s3_bucket_object.function.id}"
}
...10 more
```

The problem is on every single `terraform apply` run a minimum of 3 regions will claim the function already exists, I've confirmed via the console and via cli that in fact the function does not exist in those regions. However this happens consistently.

On `terraform destroy` I get several errors stating the function does not exist (in regions where I'm positive it exists) i.e. logged into the cli and tested the function in that region.

To clarify on the above, it seems destroy deletes the function first, then gives an error claiming it does not exist.

This is highly unusual behavior, I'm on Terraform v0.10.4.

How are you guys handling deploying multi regional lambda functions?

More Info:
Got this on my latest destroy
```
* module.eu-west-1.aws_lambda_function.function (destroy): 1 error(s) occurred:

* aws_lambda_function.function: Error deleting Lambda Function: ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:552237261114:function:function
	status code: 404, request id: 7b9b20d5-9655-11e7-a388-43269b57d99e
```
yet terraform show, gives
```
module.us-east-1.aws_lambda_function.function:
  id =  function
  arn = arn:aws:lambda:us-east-1::function:function
  dead_letter_config.# = 0
  description = 
  environment.# = 0
  function_name = function
  handler = function
  invoke_arn = arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1::function:function/invocations
  kms_key_arn = 
  last_modified = 2017-09-10T17:49:49.869+0000
  memory_size = 128
  publish = true
  qualified_arn = arn:aws:lambda:us-east-1::function:function:49
  role = arn:aws:iam:::role/lambda-role
  runtime = python2.7
  s3_bucket = function-zip
  s3_key = function.zip
  source_code_hash = dPbViJMzvThGRKg5P7O7SPlbNUlu5bQnzFqBtUJvXHI=
  tags.% = 0
  timeout = 3
  tracing_config.# = 1
  tracing_config.0.mode = PassThrough
  version = 49
  vpc_config.# = 0

```

**Comment by apparentlymart** [comment]
Hi @jonathan-kosgei! Sorry this isn't working as expected.

Do you have a `provider "aws"` block in the root module? At the moment, settings from the root module will override settings from a child module, so if the root module says `region = "us-west-2"` then that region will be used for all child modules.

We're aware of this weird behavior and planning to address this in the near future; we can't change it until a major release since it would be a breaking change for anyone depending on the prior behavior.

In the mean time, we usually recommend as a workaround to make the root module not contain _any_ AWS provider settings and to move any AWS resources that are in the root module into a single new child module, thus leaving you with no root configuration and then a separate configuration for each child module.

**Comment by jonathan-kosgei** [comment]
@apparentlymart I'm using all 13 regions when I run this and the lambda function gets created in 10 of the 13 regions, with 3 of the regions reporting false positives

**Comment by jonathan-kosgei** [comment]
#16173
