### ISSUE TITLE
terraform init commands is not downloading the tfstate file

### ISSUE THREAD

**Issue by micemuni** [hashicorp/terraform#16073]
Hi All,
When i am doing terraform init commands, TF is not downloading the tfstate ( s3 bucket located ) to local.
Also i am not able to see the terraform backend-config file inside the .terraform folder. 

I am using terraform 0.10.4 version 

++++++++++++++++++++++++++++++++++++
Outputs: 

$ terraform --version
Terraform v0.10.4

$ terraform init \
> -lock="true" \
> -backend-config="bucket=$TF_STATE_BUCKET" \
> -backend-config="key=$TF_STATE_KEY" \
> -backend-config="dynamodb_table=$TF_LOCK_TABLE" \
> -backend-config="region=$AWS_REGION" \
> -backend-config="profile=$AWS_PROFILE" \
> -backend-config="encrypt=true" \
> .
Downloading modules...
Get: git::ssh://XXXXXXXXXXXXXXXXX/add/tf-vpc.git?ref=1.0.1
Get: git::ssh://XXXXXXXXXXXXXXXXX/add/tf-ec-redis.git?ref=1.1.3
Get: git::ssh://XXXXXXXXXXXXXXXXX/add/tf-rds-pg.git?ref=1.3.0

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (0.1.4)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 0.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ ll -al .terraform/
total 8
drwxr-xr-x 1 XXXXX 1049089 0 Sep 12 18:10 modules/
drwxr-xr-x 1 XXXXX 1049089 0 Sep 12 18:10 plugins/

In present location TF will take the backup of the s3-tfstate file, but it's not downloading. 

Please let me know how to fix this issue.

**Comment by jbardin** [comment]
Hi @micemuni,

Terraform doesn't download the state file during `init`. All the remote state backends operate on the state file remotely. 

If for some reason you want a copy of the remote state file, you can use the `state`command to fetch it:

    terraform state pull > terraform.tfstate

**Comment by micemuni** [comment]
If i run the TF refresh commands, TF is not getting the tfstate file, its creating the Empty or non-existent state file.

+++++++++++++++++++++++++++++++++++++++++
$ terraform refresh
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.

Outputs:

dev_private_zone_name = XXXXXXXX.local
private_zone_name = XXXXXXX.local

+++++++++++++++++++++++++++++++++++++++++

**Comment by micemuni** [comment]
Why TF is creating the empty tfstate file, actually TF should use tfstate file which i have in s3 bukcet. 

-$ terraform init \
    -lock="true"
    -backend-config="bucket=$TF_STATE_BUCKET"
    -backend-config="key=$TF_STATE_KEY"
    -backend-config="dynamodb_table=$TF_LOCK_TABLE"
    -backend-config="region=$AWS_REGION"
    -backend-config="profile=$AWS_PROFILE"
    -backend-config="encrypt=true"

$ terraform refresh
**Empty or non-existent state file.**

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.

Outputs:
dev_private_zone_name = XXXXXXXXXX.local
private_zone_name = XXXXXXXXXX.local

**Comment by bhchew** [comment]
you might miss out the below.

Having the same issue and discovered it just a silly mistake while developing using local state... 

```
provider "aws" {
   region = "${var.aws_region}"
}

terraform {
  required_version = ">=0.9.2"
  backend "s3" { }
}
```
