### ISSUE TITLE
tfstate file does not have EC2 tags after applying a plan, tags are in tfstate after refresh

### ISSUE THREAD

**Issue by jonhatalla** [hashicorp/terraform#1608]
After creating an aws ec2 box with tags, those tags do not appear in the state file.  However after running ```terraform refresh```, the tags appear in the tfstate file.

We are using our state file to list information about the various boxes provisioned by Terraform.  We would like to use the tags we assign to the boxes to logically group them.  This is how we stumbled upon this.  
Here is a sample snippet of our tf file that creates a simple aws instance.

````javascript
resource "aws_instance" "testbox" {
  ami = "${var.aws_ubuntu_ami}"
  instance_type = "t2.micro"
  key_name = "${var.bootstrap_keypair}"
  count = "1"
  tags {
      Name        = "testtagbox"
      Environment = "${var.environment}"
      Type        = "test"
      Provisioned = "Terraform"
      Configured  = "Ansible"
  }
  subnet_id = "${aws_subnet.public.id}"
  associate_public_ip_address = true
}
````

1. To duplicate, create a simple aws_instance and assign tags to it.
1. run ```terraform apply``` command to create the instance
1. Check the tfstate file for any of the tags that were set on the ec2 instance (are not present on 0.4.2)
1. run ```terraform refresh``` command
1. The tfstate file is now up to date with the tags present

Here is gist showing the before refresh and after refresh states of the ec2 instance.
https://gist.github.com/jonhatalla/e85b36b5a89e7a5faeb2

````javascript
"attributes": {
                            "ami": "ami-e4b68a8c",
                            ....
                            "tags.#": "5",
                            "tags.Configured": "Ansible",
                            "tags.Environment": "test",
                            "tags.Name": "testtagbox",
                            "tags.Provisioned": "Terraform",
                            "tags.Type": "test",
                            "tenancy": "default"
                        }
````

**Comment by catsby** [comment]
Hey @jonhatalla , thanks for reporting this! 
I actually fixed this last week, it currently works as expected on the `master` branch and will go out with v0.5.0 in the next few weeks. 

Thanks again!
