### ISSUE TITLE
Why TF is creating the empty tfstate file, 

### ISSUE THREAD

**Issue by micemuni** [hashicorp/terraform#16086]
Hi there,
If i run the TF refresh commands, TF is not getting the tfstate file, its creating the Empty or non-existent state file.

### Terraform Version
$ terraform -v
Terraform v0.10.4

### Terraform Configuration Files

$ terraform init \

    -lock="true"
    -backend-config="bucket=$TF_STATE_BUCKET"
    -backend-config="key=$TF_STATE_KEY"
    -backend-config="dynamodb_table=$TF_LOCK_TABLE"
    -backend-config="region=$AWS_REGION"
    -backend-config="profile=$AWS_PROFILE"
    -backend-config="encrypt=true" 

$ terraform refresh
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.

Outputs:

dev_private_zone_name = XXXXXXXX.local
private_zone_name = XXXXXXX.local

### Debug Output
 Even if i passed values directly, its creating empty tfstate file. 

### Expected Behavior
TF will refer the s3 bucket tfstate file.

### Actual Behavior
While terrafrom plan commands
TF is creating all resources newly because tfstate file is empty.

**Comment by jbardin** [comment]
Hi @micemuni,

I'm not sure what could be going on in here.
Can you provide the backend config, and the trace logs from running `init` or `refresh`?

**Comment by micemuni** [comment]
Fixed the issue, In my case i need to convert the existing tfstate file, so i have pasted the tfstate file and renamed file name to terraform.tfstate. Then its working and terraform refresh command refreshing the state file.
