### ISSUE TITLE
`self` in Module Declaration causes crash

### ISSUE THREAD

**Issue by pearkes** [hashicorp/terraform#1609]
Given a module declaration like this:

```
module "foo" {
    source = "./bar"
    name  = "pearkes"
    foobar = "${self.name}-2"
}
```

Terraform crashes on:

```
terraform plan -module-depth=-1
```

Log: https://gist.github.com/pearkes/6910ff43d8a1350986ef

**Comment by mitchellh** [comment]
Thanks, fixed in the attached PR. Self variables don't quite work that (though I'd like them to one day). For now, they simply aren't allowed in modules.
