### ISSUE TITLE
Better message wording on removing multiple resources from the state

### ISSUE THREAD

**Issue by vladgolubev** [hashicorp/terraform#16109]
### Terraform Version

`0.10.5`

### Expected Behavior

Message indicating I removed several, not 1 resource from the state. Like `4 items removal successful.`

### Actual Behavior
When I run `terraform state rm a b c d` I see the message:

`Item removal successful.`

However I removed 4 resources.

**Comment by apparentlymart** [comment]
Good idea, @vladgolubev! Thanks for pointing that out.
