### ISSUE TITLE
modify/attach/detach secururity group on vpc instance

### ISSUE THREAD

**Issue by alekseymykhailov** [hashicorp/terraform#1611]
Currently terraform "forces new resource" (redeploys instance) in case of security group modification on instance which is deployed in VPC. But AWS VPC allows to modify security groups and Instance relationship  without downtime.

**Comment by catsby** [comment]
Hey @alekseymykhailov – yes, this is a limitation in v0.4.2. #1539 was opened to add support for a `vpc_security_group_ids` to allow you to specify security group ids in your VPC without doing a force new, however on further review it seems while we don't destroy the resource, we also don't update the security group ids :frowning: 

Thanks for opening this; I'm looking into fixing things now

**Comment by mzupan** [comment]
I'd be willing to test a fix once released.. just ran into this right now

**Comment by mzupan** [comment]
@catsby not sure if I'm using it wrong but using that branch it still wants a new resource if I add a security group to a VPC instance that's already created

```
    security_groups.#:          "1" => "2" (forces new resource)
    security_groups.2538377088: "" => "sg-8f5b17eb" (forces new resource)
    security_groups.3329033720: "sg-f6347892" => "sg-f6347892" (forces new resource)
    subnet_id:                  "subnet-c8a13791" => "subnet-c8a13791"
```

```
mike-zupan:aws mzupan$ ~/go/bin/terraform -v
Terraform v0.5.0-dev (e79c5f19188ad2e9668aa16501186a6a252a9897)
```

```
	security_groups = [
		"${aws_security_group.internal-default.id}",
		"${aws_security_group.internal-rabbitmq.id}"
	]
```

I had default.id in there and trying to add rabbitmq.id

**Comment by catsby** [comment]
@mzupan I should have clarified: that branch will "fix" the issue if you're using VPC and the `vpc_security_group_ids` Instance attribute that was introduced in #1539

**Comment by mzupan** [comment]
@catsby thanks! worked great
