### ISSUE TITLE
Assets Destroyed with Terrform Apply after Terraform import performed

### ISSUE THREAD

**Issue by t5unamie** [hashicorp/terraform#16119]
Hi there,

Security Group destroyed with Terrform Apply after Terraform import performed. 

### Terraform Version
Terraform v0.9.9

### Terraform Configuration Files
```hcl
# https://www.terraform.io/docs/providers/aws/r/security_group.html

resource "aws_security_group" "allow-all-inside_vpc" {
  name        = "allow-all-inside_vpc"
  description = "allow-all-inside_vpc"
  vpc_id      = "vpc-1234567"
  tags {
    Name = "allow-all-inside_vpc"
  }
}

resource "aws_security_group_rule" "allow-all-inside_vpc" {
  type              = "ingress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  cidr_blocks = [ "x.x.x.x/8", "x.x.x.x/12", "x.x.x.x/32", "x.x.x.x/32", "x.x.x.x/32", "x.x.x.x/32", "x.x.x.x/32", "x.x.x.x/23" ]
  security_group_id = "sg-123456"
  self              = "false"
}

resource "aws_security_group_rule" "allow-all-inside_vpc-1" {
  type              = "ingress"
  from_port         = 443
  to_port           = 443
  protocol          = "tcp"
  cidr_blocks       =  [ "x.x.x.x/32" ]
  security_group_id = "sg-123456"
  self              = "false"
}

resource "aws_security_group_rule" "allow-all-inside_vpc-2" {
  type              = "egress"
  from_port         = 0
  to_port           = 65535
  protocol          = "tcp"
  cidr_blocks       =  [ "0.0.0.0/0" ]
  security_group_id = "sg-123456"
  self              = "false"
}
```

### Debug Output
https://gist.github.com/t5unamie/08bb72172382fb822d0556bdff3f994b

### Expected Behavior
What should have happened?
The command should have just indicated no changes. As I am bringing states that I created from terraform import under terraform apply control.

"terraform plan -var-file="./environment.tfvars"

should have just given me 
### Actual Behavior
What actually happened?
It states and does destroy the asset and tries to rebuild them. I need them to just take control. As the Security groups are used by live systems and can't be deleted.
### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
terraform get
terraform init
terraform plan \
     -var-file="./environment.tfvars"

**Comment by t5unamie** [comment]
This is the state file I am trying to import.
```
{
"version": 3,
"terraform_version": "0.9.9",
"serial": 0,
"lineage": "xxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxx",
"modules": [
{
"path": [
"root"
],
"outputs": {},
"resources": {
"aws_security_group.allow-all-inside_vpc": {
"type": "aws_security_group",
"depends_on": [],
"primary": {
"id": "sg-12345678",
"attributes": {
"description": "allow-all-inside_vpc",
"egress.#": "1",
"egress.1403647648.cidr_blocks.#": "1",
"egress.1403647648.cidr_blocks.0": "0.0.0.0/0",
"egress.1403647648.from_port": "0",
"egress.1403647648.ipv6_cidr_blocks.#": "0",
"egress.1403647648.prefix_list_ids.#": "0",
"egress.1403647648.protocol": "tcp",
"egress.1403647648.security_groups.#": "0",
"egress.1403647648.self": "false",
"egress.1403647648.to_port": "65535",
"id": "sg-12345678",
"ingress.#": "2",
"ingress.1033006632.cidr_blocks.#": "1",
"ingress.1033006632.cidr_blocks.0": "x.x.x.x/32",
"ingress.1033006632.from_port": "443",
"ingress.1033006632.ipv6_cidr_blocks.#": "0",
"ingress.1033006632.protocol": "tcp",
"ingress.1033006632.security_groups.#": "0",
"ingress.1033006632.self": "false",
"ingress.1033006632.to_port": "443",
"ingress.3232374524.cidr_blocks.#": "8",
"ingress.3232374524.cidr_blocks.0": "x.x.x.x/8",
"ingress.3232374524.cidr_blocks.1": "x.x.x.x/12",
"ingress.3232374524.cidr_blocks.2": "x.x.x.x/32",
"ingress.3232374524.cidr_blocks.3": "x.x.x.x/32",
"ingress.3232374524.cidr_blocks.4": "x.x.x.x./32",
"ingress.3232374524.cidr_blocks.5": "x.x.x.x/32",
"ingress.3232374524.cidr_blocks.6": "x.x.x.x/32",
"ingress.3232374524.cidr_blocks.7": "x.x.x.x/23",
"ingress.3232374524.from_port": "0",
"ingress.3232374524.ipv6_cidr_blocks.#": "0",
"ingress.3232374524.protocol": "-1",
"ingress.3232374524.security_groups.#": "0",
"ingress.3232374524.self": "false",
"ingress.3232374524.to_port": "0",
"name": "allow-all-inside_vpc",
"owner_id": "123456789123456",
"tags.%": "1",
"tags.Name": "allow-all-inside_vpc",
"vpc_id": "vpc-0000001"
},
"meta": {},
"tainted": false
},
"deposed": [],
"provider": "aws"
},
"aws_security_group_rule.allow-all-inside_vpc": {
"type": "aws_security_group_rule",
"depends_on": [],
"primary": {
"id": "sgrule-000000001",
"attributes": {
"cidr_blocks.#": "8",
"cidr_blocks.0": "x.x.x.x/8",
"cidr_blocks.1": "x.x.x.x/12",
"cidr_blocks.2": "x.x.x.x/32",
"cidr_blocks.3": "x.x.x.x/32",
"cidr_blocks.4": "x.x.x.x/32",
"cidr_blocks.5": "x.x.x.x/32",
"cidr_blocks.6": "x.x.x.x/32",
"cidr_blocks.7": "x.x.x.x/23",
"from_port": "0",
"id": "sgrule-000000001",
"ipv6_cidr_blocks.#": "0",
"prefix_list_ids.#": "0",
"protocol": "-1",
"security_group_id": "sg-123456",
"self": "false",
"to_port": "0",
"type": "ingress"
},
"meta": {
"schema_version": "2"
},
"tainted": false
},
"deposed": [],
"provider": "aws"
},
"aws_security_group_rule.allow-all-inside_vpc-1": {
"type": "aws_security_group_rule",
"depends_on": [],
"primary": {
"id": "sgrule-000000002",
"attributes": {
"cidr_blocks.#": "1",
"cidr_blocks.0": "x.x.x.x/32",
"from_port": "443",
"id": "sgrule-000000002",
"ipv6_cidr_blocks.#": "0",
"prefix_list_ids.#": "0",
"protocol": "tcp",
"security_group_id": "sg-123456",
"self": "false",
"to_port": "443",
"type": "ingress"
},
"meta": {
"schema_version": "2"
},
"tainted": false
},
"deposed": [],
"provider": "aws"
},
"aws_security_group_rule.allow-all-inside_vpc-2": {
"type": "aws_security_group_rule",
"depends_on": [],
"primary": {
"id": "sgrule-000000003",
"attributes": {
"cidr_blocks.#": "1",
"cidr_blocks.0": "0.0.0.0/0",
"from_port": "0",
"id": "sgrule-000000002",
"ipv6_cidr_blocks.#": "0",
"prefix_list_ids.#": "0",
"protocol": "tcp",
"security_group_id": "sg-123456",
"self": "false",
"to_port": "65535",
"type": "egress"
},
"meta": {
"schema_version": "2"
},
"tainted": false
},
"deposed": [],
"provider": "aws"
}
},
"depends_on": []
}
]
}
```

**Comment by t5unamie** [comment]
Terraform state show

```
id                                    = sg-123456
description                           = allow-all-inside_vpc
egress.#                              = 1
egress.1403647648.cidr_blocks.#       = 1
egress.1403647648.cidr_blocks.0       = 0.0.0.0/0
egress.1403647648.from_port           = 0
egress.1403647648.ipv6_cidr_blocks.#  = 0
egress.1403647648.prefix_list_ids.#   = 0
egress.1403647648.protocol            = tcp
egress.1403647648.security_groups.#   = 0
egress.1403647648.self                = false
egress.1403647648.to_port             = 65535
ingress.#                             = 2
ingress.1033006632.cidr_blocks.#      = 1
ingress.1033006632.cidr_blocks.0      = x.x.x.x/32
ingress.1033006632.from_port          = 443
ingress.1033006632.ipv6_cidr_blocks.# = 0
ingress.1033006632.protocol           = tcp
ingress.1033006632.security_groups.#  = 0
ingress.1033006632.self               = false
ingress.1033006632.to_port            = 443
ingress.3232374524.cidr_blocks.#      = 8
ingress.3232374524.cidr_blocks.0      = x.x.x.x/8
ingress.3232374524.cidr_blocks.1      = x.x.x.x/12
ingress.3232374524.cidr_blocks.2      = x.x.x.x/32
ingress.3232374524.cidr_blocks.3      = x.x.x.x/32
ingress.3232374524.cidr_blocks.4      = x.x.x.x/32
ingress.3232374524.cidr_blocks.5      = x.x.x.x/32
ingress.3232374524.cidr_blocks.6      = x.x.x.x/32
ingress.3232374524.cidr_blocks.7      = x.x.x.x/23
ingress.3232374524.from_port          = 0
ingress.3232374524.ipv6_cidr_blocks.# = 0
ingress.3232374524.protocol           = -1
ingress.3232374524.security_groups.#  = 0
ingress.3232374524.self               = false
ingress.3232374524.to_port            = 0
name                                  = allow-all-inside_vpc
owner_id                              = 12345671234567
tags.%                                = 1
tags.Name                             = allow-all-inside_vpc
vpc_id                                = vpc-1234567
```

**Comment by nbering** [comment]
Sorry to hear you're having difficulties with Terraform Import.

In future it would be great if you could put the debug output in a [gist](gist.github.com), and link to it, so that other users don't need to scroll through several pages of text to get to the comments.

This type of issue comes up from time-to-time. Importing resources adds them to the state file, but does not add configuration for the resource. So when you run apply, Terraform sees a resource in state that does not exist in configuration, so it takes action to destroy it.

In general, I recommend always running `terraform plan` before `terraform apply`, so that you know what it's going to do. It's pretty easy to accidentally delete a resource with Terraform if you don't check what it's going to do.

As for adding configuration, that needs to be done manually as Terraform cannot infer what file you'd put it in, or even what values are intended vs. incidental, linked to other resources, etc. I usually import the resource, and then keep editing the config until the plan says it won't change anything, or that the changes are benign enough that I'm willing to let Terraform take over just for the sake of consistency.

I believe there is still an open issues around for letting Terraform create a configuration based on the state of an imported resource, but I couldn't find it with a quick search.

**Comment by apparentlymart** [comment]
Hi @t5unamie! I'm sorry that import behaves in this way right now.

As @nbering noted, at this time `terraform import` only makes a record of the resource in Terraform's state, and requires that you manually write configuration for it. Unfortunately in version 0.9.9 there is no protection against forgetting to do this; in 0.10.0 this was changed so that `terraform import` won't proceed unless a configuration block is already present, to prevent this situation from arising.

Further improvements to the import system are planned, including automatic creation of configuration. This is not something we are working on in the short term since we need to spend some time to design and prototype the new system. We'll have more to share once some initial investigation has been done.

**Comment by t5unamie** [comment]
Hi There, if you refer to the information above. I manually created the configuration.

I don't understand why this keeps getting mentioned. The configuration matchs the state precisely.

Thats why I raised the bug.

**Comment by apparentlymart** [comment]
Hi @t5unamie. Sorry for the misunderstanding.

Are you able to share the `terraform import ...` commands you ran prior to seeing this behavior? Having those steps will hopefully allow us to reproduce what you saw to understand why it's happening.

**Comment by apparentlymart** [comment]
I wasn't able to reproduce using some locally-created resources, so I went back to trying to figure out what's going on from the log. What follows are some notes from that investigation, mainly just for my own reference.

We can see in the log where the graph is being constructed that the `ConfigTransformer` seems to be finding no resource configurations at all:

```
2017/09/19 15:29:31 [TRACE] ConfigTransformer: Starting for path: []
2017/09/19 15:29:31 [TRACE] Graph after step *terraform.ConfigTransformer:

2017/09/19 15:29:31 [TRACE] Graph after step *terraform.OutputTransformer:

2017/09/19 15:29:31 [TRACE] Graph after step *terraform.OrphanResourceTransformer:

aws_security_group.allow-all-inside_vpc - *terraform.NodeAbstractResource
aws_security_group_rule.allow-all-inside_vpc - *terraform.NodeAbstractResource
aws_security_group_rule.allow-all-inside_vpc-1 - *terraform.NodeAbstractResource
aws_security_group_rule.allow-all-inside_vpc-2 - *terraform.NodeAbstractResource
```

Instead, these resources are being inserted as "orphans", which is how Terraform represents resources that it finds in state but not in configuration.

At the end of graph construction, the full graph is as follows:

![graph](https://user-images.githubusercontent.com/20180/30662720-f0800c40-9dfc-11e7-853d-7382cc8a46a2.gif)

This is the graph we'd expect for a plan that wants to destroy all the resources. Unfortunately Terraform doesn't produce detailed logs about the configuration parsing step, so it's not clear yet _why_ the configuration for these resources is not being found.

**Comment by apparentlymart** [comment]
@t5unamie I can see in this graph that your config includes some `variable` blocks and a `provider "aws"` block that _are_ being found and included, so this suggests that Terraform isn't _entirely_ failing to read the configuration, but that certain resources are not being seen.

Unfortunately since Terraform doesn't produce detailed logs during configuration parsing I can't infer anything more about the contents of your configuration just from the log. Are the `resource` blocks you shared in your initial report in a separate `.tf` file from the `variable` and `provider` blocks? Are they all in the same directory? If you're able to share a little more detail about how many files you have and what they are named that may give a clue as to why Terraform is only seeing _part_ of the configuration here.

**Comment by t5unamie** [comment]
@apparentlymart 
Every other resource your seeing is in other .tf files.

IE. the provider block is in a separate tf file, The Variables are in a separate TF file and the remote state config are in a separate tf file.

The configuration for the security group is shown above and in a seperate tf file. I put them in seperate TF files so I could easily copy/symlink them around for use in other things.

IE all my AWS scripts all need the AWS provider block so I just symlink it into the folder which needs it.


Is there any other flag or anything I can do to demonstrate the issue?
If I put everything into one tf file and test that. Would that help you?

**Comment by apparentlymart** [comment]
Hi @t5unamie,

If you are able to try it all in one file that may well be informative. I'm wondering if, for some reason, Terraform is unable to find/read that particular file, though at this time I don't have a theory on _why_ that would be the case.

Regarding that graph, it was produced mostly-manually using the output of this form in the log file:

```
2017/09/19 15:29:33 [TRACE] Graph after step *terraform.RootTransformer:

aws_security_group.allow-all-inside_vpc (orphan) - *terraform.NodePlannableResourceOrphan
  provider.aws - *terraform.NodeApplyableProvider
aws_security_group_rule.allow-all-inside_vpc (orphan) - *terraform.NodePlannableResourceOrphan
  provider.aws - *terraform.NodeApplyableProvider
aws_security_group_rule.allow-all-inside_vpc-1 (orphan) - *terraform.NodePlannableResourceOrphan
  provider.aws - *terraform.NodeApplyableProvider
aws_security_group_rule.allow-all-inside_vpc-2 (orphan) - *terraform.NodePlannableResourceOrphan
  provider.aws - *terraform.NodeApplyableProvider
meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  aws_security_group.allow-all-inside_vpc (orphan) - *terraform.NodePlannableResourceOrphan
  aws_security_group_rule.allow-all-inside_vpc (orphan) - *terraform.NodePlannableResourceOrphan
  aws_security_group_rule.allow-all-inside_vpc-1 (orphan) - *terraform.NodePlannableResourceOrphan
  aws_security_group_rule.allow-all-inside_vpc-2 (orphan) - *terraform.NodePlannableResourceOrphan
  provider.aws - *terraform.NodeApplyableProvider
  var.CostGroup - *terraform.NodeRootVariable
  var.aws_bucket - *terraform.NodeRootVariable
  var.aws_profile - *terraform.NodeRootVariable
  var.aws_region - *terraform.NodeRootVariable
  var.env - *terraform.NodeRootVariable
  var.project - *terraform.NodeRootVariable
  var.vpc_env - *terraform.NodeRootVariable
provider.aws - *terraform.NodeApplyableProvider
  var.aws_profile - *terraform.NodeRootVariable
  var.aws_region - *terraform.NodeRootVariable
provider.aws (close) - *terraform.graphNodeCloseProvider
  aws_security_group.allow-all-inside_vpc (orphan) - *terraform.NodePlannableResourceOrphan
  aws_security_group_rule.allow-all-inside_vpc (orphan) - *terraform.NodePlannableResourceOrphan
  aws_security_group_rule.allow-all-inside_vpc-1 (orphan) - *terraform.NodePlannableResourceOrphan
  aws_security_group_rule.allow-all-inside_vpc-2 (orphan) - *terraform.NodePlannableResourceOrphan
  provider.aws - *terraform.NodeApplyableProvider
root - terraform.graphNodeRoot
  meta.count-boundary (count boundary fixup) - *terraform.NodeCountBoundary
  provider.aws (close) - *terraform.graphNodeCloseProvider
var.CostGroup - *terraform.NodeRootVariable
var.aws_bucket - *terraform.NodeRootVariable
var.aws_profile - *terraform.NodeRootVariable
var.aws_region - *terraform.NodeRootVariable
var.env - *terraform.NodeRootVariable
var.project - *terraform.NodeRootVariable
var.vpc_env - *terraform.NodeRootVariable
```

The unindented entries here each represent a graph node and the indented entries represent dependency edges between the nodes. I reshaped that into a [graphviz](http://www.graphviz.org/) file so I could see the graph shape more clearly.

**Comment by paddycarver** [comment]
Hi there! This issue has gone for a while without response from the opener, so I'm going to close it in an effort to keep the issue tracker clean and easy to find the issues that need our maintainers' attention. If you feel this was closed in error, or continue to have the problem described, please feel free to reply to this issue and we'll reopen it. Thanks!
