### ISSUE TITLE
New provider discussion: Skeddly

### ISSUE THREAD

**Issue by apeeters** [hashicorp/terraform#16116]
As a user of both Terraform and [Skeddly](https://www.skeddly.com/), I would love a provider for the latter. This is an issue to track interest of other potential users.

Some use cases:
- Create and EC2 instance and specify backup schedules
- Create an EC2 instance and specify start/stop schedules

API: http://docs.skeddly.com/

**Comment by pkolyvas** [comment]
Hi folks! As Terraform Open Source is now separate from Providers, I'm working on cleaning up our issue list by closing down open issues that no longer pertain directly to this repository.

The best place to start with a proposed provider is with Skeddly themselves or the Skeddly community. 

The provider development program [documentation is here](https://www.terraform.io/guides/terraform-provider-development-program.html).

HashiCorp isn't able to officially kick-off and create every provider, but we will always welcome new provider contributions from our community.
