### ISSUE TITLE
Terraform crashes on "terraform get" when pulling a new tag from a repository

### ISSUE THREAD

**Issue by skenmy** [hashicorp/terraform#16135]
### Terraform Version
Terraform v0.10.6

### Terraform Configuration Files
https://www.dropbox.com/s/k3k4b9hi7330klo/tfbug.tar.gz.gpg?dl=0
Encrypted using the HashiCorp public key

### Debug Output
Available as `console.output.log` in the tarball above

### Crash Output
Available as `crash.log` in the tarball above

### Expected Behavior
Modules should download

### Actual Behavior
Terraform crashed

### Steps to Reproduce
1. Update source version tag in module
2. `terraform get -update=true`

### Important Factoids
Module is being imported from a remote repo. 

### References
N/A

**Comment by skenmy** [comment]
For a little context - in the `base_network` module in `main.tf` inside one of the local modules, I updated the source from `source = "git@github.com:org/repo//base_network?ref=v0.1.0-alpha"` to `source = "git@github.com:org/repo//base_network?ref=v0.1.1-alpha"`

The remote module is verified as working.

**Comment by skenmy** [comment]
Found the source of the issue:

```bash
$ brew switch terraform 0.10.5
Cleaning /usr/local/Cellar/terraform/0.10.0
Cleaning /usr/local/Cellar/terraform/0.10.2
Cleaning /usr/local/Cellar/terraform/0.10.3
Cleaning /usr/local/Cellar/terraform/0.10.4
Cleaning /usr/local/Cellar/terraform/0.10.5
Cleaning /usr/local/Cellar/terraform/0.10.6
2 links created for /usr/local/Cellar/terraform/0.10.5

$ terraform get -update=true
Get: file:///Users/paul/Project/1234567-aws-123456789012-Live-Production/eu-central-1 (update)
Get: file:///Users/paul/Project/1234567-aws-123456789012-Live-Production/eu-west-1 (update)
Get: git::ssh://git@github.com/org/repo (update)
Error loading modules: error downloading 'ssh://git@github.com/org/repo': /usr/local/bin/git exited with 1: From ssh://github.com/org/repo
   b34c764..813b8a4  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
	iam/main.tf
Please commit your changes or stash them before you merge.
Aborting
Updating b34c764..813b8a4
```
Looks like the locally cached module under `modules` became modified somehow.

In addition - I found the following, after `rm -rf .terraform` in the root module:

```bash
$ terraform init -get=true -upgrade=true
Upgrading modules...
Get: file:///Users/paul/Project/1234567-aws-123456789012-Live-Production/eu-central-1 (update)
Get: file:///Users/paul/Project/1234567-aws-123456789012-Live-Production/eu-west-1 (update)
Get: git::ssh://git@github.com/org/repo2 (update)
Get: git::ssh://git@github.com/org/repo?ref=v0.1.1-alpha (update)
Error downloading modules: Error loading modules: module base_network: open .terraform/modules/eed93336955ac9feb02fb28bfcc80f44/base_network: no such file or directory
```

Turns out that `org/repo` had been moved. Thus Git was following the redirect, but no directory called `base_network` was in the new repo. I am unsure which of these two issues is the cause of the crash.

After rectifying these issues, v0.10.6 runs cleanly.

**Comment by jbardin** [comment]
Closed via 16161
