### ISSUE TITLE
changing ssl_certificate_id on ELB doesn't update

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#1613]
Was unable to get an ssl_cerficate_id change to happen.

Context: already up and running ELBs with certificates, then tried to change the ssl_certificate_id.

Plan says they will change, but running apply seems to have no affect.

Version 0.4.2.

**Comment by ryanking** [comment]
Seem to be having the same problem when adding a listener to an ELB.

**Comment by mitchellh** [comment]
This should be fixed just today! Good timing. :)
