### ISSUE TITLE
Text overflow issue with registry.terraform.io

### ISSUE THREAD

**Issue by vladgolubev** [hashicorp/terraform#16132]
Hi, 

not sure this is the best place to report, but didn't find a dedicated repo for the registry.

Here is the URL: https://registry.terraform.io/browse?offset=9&provider=aws

And here is the issue

![image](https://user-images.githubusercontent.com/3817380/30637133-27432ae8-9e00-11e7-9dc4-9bdcca29dd21.png)

Screen size: macbook 15, but looks off even on 27"

**Comment by banks** [comment]
Thanks for the report!

This is now fixed.
