### ISSUE TITLE
Add time provider.

### ISSUE THREAD

**Issue by james-lawrence** [hashicorp/terraform#16146]
Terraform v0.10.3

related to https://github.com/hashicorp/terraform/issues/494.

basically trying to generate a timestamp, but the default format doesn't work. currently using variable and the date command on the cli to get around this.
```
terraform apply -var=timestamp=$(date '+%Y-%m-%d.%s')
```
thinking something along the lines of the random provider but for time would be grand.
it would:

1) regenerate a timestamp each time the keeper changes.
2) provider attributes like unix, and different common formats.
3) have a way to customize the time format explicitly.
```
resource "time" "default" {
  keepers = {
    ami_id = "keepme"
  }
}
```

**Comment by jlucktay** [comment]
+1 for this. We put kill date tags onto resources in our AWS R&D labs to help keep things tidy, so being able to evaluate `today+7 days` somehow would be very nice!

**Comment by tonglil** [comment]
Currently using the `timestamp()` interpolation, but what I really need is the ability to modify it (trying to create `aws_autoscaling_schedule` with a start time of "now").

**Comment by omeid** [comment]
effectively timestamp could accept an optional format modifier as a parameter, so you can do things like `timestamp( "+%Y-%m-%d.%s")`, and same for `timeadd(time, duration, format) `.

**Comment by bflad** [comment]
Hi folks 👋 As a side project, I have experimentally created the following: https://github.com/bflad/terraform-provider-time

It supports a few things in the initial release of a `time_static` resource:

- Saving the resource creation or configurable timestamp
- Expiration timestamp or configurations (e.g. expire in X days or Y months) for resource rotation

The former should cover some of the cases above when combined with the [`formatdate()` function](https://www.terraform.io/docs/configuration/functions/formatdate.html) and the [`timeadd()` function](https://www.terraform.io/docs/configuration/functions/timeadd.html). The latter seems like it could unlock some interesting use cases, such as potentially triggering workflows on a cadence.

Please give it a shot! I have not experimented with it in real world configurations yet (beyond acceptance testing just the resource itself), so please be mindful that there could be some very rough edges initially, especially with the expiration rotation.

**Comment by bflad** [comment]
This experimental provider (v0.2.0) now supports three separate resources:

- [`time_offset` Resource](https://github.com/bflad/terraform-provider-time/blob/master/website/docs/r/offset.html.markdown): For saving an offset time
- [`time_rotating` Resource](https://github.com/bflad/terraform-provider-time/blob/master/website/docs/r/rotating.html.markdown): For triggering recreation on a cadence
- [`time_static` Resource](https://github.com/bflad/terraform-provider-time/blob/master/website/docs/r/static.html.markdown): For saving a static time

Hope this helps. 🚀

**Comment by bflad** [comment]
Hi again 👋 The [Terraform Time Provider](https://www.terraform.io/docs/providers/time/) is now available for usage via `terraform init`. For any future feature requests or bug reports with that functionality, please [open a GitHub issue in its dedicated issue tracker](https://github.com/hashicorp/terraform-provider-time/issues/new/choose). Thanks!
