### ISSUE TITLE
Consul remote state backend to support setting a datacenter

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#1614]
It would be convenient for the Consul remote state backend to support setting the datacenter name on the client it creates. This would be consistent with the other places where Terraform interacts with Consul.

**Comment by justinclayton** [comment]
+1. This is a real issue for us because we often get inconsistent results as to where the state is being written to or read from. This makes it unreliable as a source of truth.

**Comment by JoeOrtiz** [comment]
Has there been any updates on this?

This is needed as for the above reasons, makes it very difficult to keep the source.

**Comment by guidob** [comment]
Is there a workaround for this? This will block our adoption of storing state in Consul...

**Comment by guidob** [comment]
```go
diff --git a/state/remote/consul.go b/state/remote/consul.go
index 8ac686f..0db6e29 100644
--- a/state/remote/consul.go
+++ b/state/remote/consul.go
@@ -24,6 +24,9 @@ func consulFactory(conf map[string]string) (Client, error) {
        if scheme, ok := conf["scheme"]; ok && scheme != "" {
                config.Scheme = scheme
        }
+       if datacenter, ok := conf["datacenter"]; ok && datacenter != "" {
+               config.Datacenter = datacenter
+       }
        if auth, ok := conf["http_auth"]; ok && auth != "" {
                var username, password string
                if strings.Contains(auth, ":") {
```

This will actually do it, it seems.
