### ISSUE TITLE
Specify variable inputs to module via a file

### ISSUE THREAD

**Issue by jlcalbre** [hashicorp/terraform#16143]
When using a module, I'd like to be able to point to a file (a specific .tfvars file maybe) that contains the values I want to pass to my module, rather than having to list them out individually every time I use the module.  This would allow me to quickly and efficiently switch/change configurations that I am deploying.

**Comment by pkolyvas** [comment]
I'm going to close this issue based on engagement and age. I do wonder if we've found a halfway solution for you with the addition of the `module_variable_optional_attrs` in Terraform `0.14.` [changelog](https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md)

We don't have any plans in the foreseeable future to tackle this issue as presented. We do appreciate you taking the time to share your request with us.
