### ISSUE TITLE
Feature Request: "ws" alias for "workspace" command

### ISSUE THREAD

**Issue by brycematheson** [hashicorp/terraform#16156]
As a feature request, I'd like to request that a `ws` alias be created for the `workspace` command. I understand that the `env` command has been/is being deprecated, however, I find it much more convenient to type:

`terraform env list` or `terraform env select`

As opposed to:

`terraform workspace list` or `terraform workspace select`.

For the sake of brevity, I have continued using the `env` command and will continue to, until it is finally deprecated from Terraform.

Alternatively, if an alias were created for `workspace`, I would happily employ the following:

`terraform ws list` or `terraform ws select`

Thank you

**Comment by grimm26** [comment]
`alias tfws="terraform workspace"` and now the command is even shorter :)

**Comment by brycematheson** [comment]
Easy enough. Thanks!

**Comment by apparentlymart** [comment]
Hi @brycematheson!

I'm glad you were able to get something reasonable using shell aliases. It might also be interesting to know that we're planning to add shell tab completion in future; some helpers to support this were recently added to the supporting library [`cli`](https://github.com/mitchellh/cli) but we've not yet had the time to implement the relevant hooks to make it work; once we do, it should work to type `terraform wo<TAB> se<TAB>` to autocomplete `terraform workspace select`.
