### ISSUE TITLE
Feature Request: Add oVirt/RHEV Provider

### ISSUE THREAD

**Issue by LukeFlynn** [hashicorp/terraform#16150]
I've recently begun moving away from ESXi/vSphere to oVirt (upstream of Red Hat Enterprise Virtualization). I've been wanting to get into Terraform and can't find any functional providers at this time. I think it would be super cool to see this as a native provider in Terraform!

**Comment by dyasny** [comment]
I can definitely test it if an RPM is made available. Actually, submitting backy2 to pip would also solve this

**Comment by QuentinMoss** [comment]
@LukeFlynn Do you know if this got any traction? Did you figure out another solution?

**Comment by apparentlymart** [comment]
Hi @LukeFlynn! Thanks for this request.

In the short term we (the Terraform team at HashiCorp) have no plans to develop a provider for oVirt in-house, and we have no oVirt expertise on the team currently. If some members of the oVirt community are interested in developing a provider, we'd love to work with them to bring it into the fray via [the provider development program](https://www.terraform.io/guides/terraform-provider-development-program.html), which is the way to bring a new provider into the set that is tested by and distributed by HashiCorp.

We are also planning to, in the medium term, extend the provider auto-installation mechanism to support third-party providers that are not distributed via the HashiCorp releases infrastructure, so that community developers can maintain a provider themselves as an alternative to the official program.

**Comment by jboero** [comment]
Hi @LukeFlynn thanks for your interest.
I myself am a big fan of OVirt and have recently joined Hashicorp.  I'm happy to take this on a but I can see it's already been started.  There is a partially built shell that I can sort out a bit here:  https://github.com/chriscowley/terraform-provider-ovirt

Have you done anything in the meantime since this post?  I know things have changed a bit lately with the 4.2 release.

**Comment by gageorsburn** [comment]
An oVirt provider would be awesome. I'd love to help out.

**Comment by funixz** [comment]
+! for an oVirt / RHV provider!!

**Comment by IcedGoblin** [comment]
Another +1 for an oVirt / RHV provider please! We have implemented our first oVirt cluster and are about to run a trial or Terraform Enterprise targeting vSphere but are very keen to include oVirt in that testing if possible. Happy to help as much as I can, probably can't help too much with the development but can assist with testing.

**Comment by mgoldboi** [comment]
Has anyone looked at this implementation already? 
https://github.com/EMSL-MSC/terraform-provider-ovirt

**Comment by holmesb** [comment]
+1 oVirt will get more traction since Citrix crippled the free edition of Xenserver.  Be good to see a Terraform provider.

**Comment by QuentinMoss** [comment]
@jboero The people have spoken!

**Comment by jboero** [comment]
Sorry I've been MIA but just attempted https://github.com/EMSL-MSC/terraform-provider-ovirt and can vouch that it works!

Thanks to PNL and @Maigard for publishing that.  I have experimented with the provider and it takes a bit of versioning but it comes out beatifully.  Steps to get it working currently:

As per Ken's notes, you'll need the following, with caveats:
```
$ go get github.com/EMSL-MSC/terraform-provider-ovirt
$ mkdir ~/.terraform.d/plugins
$ cp $GOPATH/bin/terraform-provider-ovirt ~/.terraform.d/plugins
```

Note with Terraform MASTER currently at 1.11.x, the build fails for me on t.Helper() in testing added to Terraform 8 months ago.  My solution for this was to revert the local Terraform to tag 1.10.x:

```
$ go get github.com/EMSL-MSC/terraform-provider-ovirt
$ mkdir ~/.terraform.d/plugins
$ cp $GOPATH/bin/terraform-provider-ovirt ~/.terraform.d/plugins
```

Then if you've used self-signed certs, make sure your engine CA is registered locally or the API will fail on unknown CA. On EL/Fedora:

```
wget http://${ENGINEFQDN}/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA
sudo cp $RESULT /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust extract
```

You should now be able to terraform {plan,apply}.  Happy days!  I'll see if we can get this registered and supported on the public registry.

Thanks

**Comment by jboero** [comment]
Note this provider uses API v3 which will be deprecated but works for now in 4.2.  I'll try to upgrade it to 4.x.

**Comment by helloIAmPau** [comment]
:+1:

**Comment by imjoey** [comment]
Hi all, I just commited a PR to github.com/EMSL-MSC/terraform-provider-ovirt, which utilizes the golang sdk for ovirt-engine v4.x to re-implement the existing codes. Now the `terraform apply` and `terraform destroy` is fully supported, and `terraform update` is partially supported. Go to https://github.com/EMSL-MSC/terraform-provider-ovirt/pull/5 for details.

**Comment by imjoey** [comment]
hi @Maigard, it seems that [EMSL-MSC/terraform-provider-ovirt](https://github.com/EMSL-MSC/terraform-provider-ovirt) is not actively maintained. You could see [sinokylin/terraform-provider-ovirt](https://github.com/sinokylin/terraform-provider-ovirt) for latest implementation of terraform oVirt provider. 

hi all, While it's still unstable and under heavy development, issues and pull requests are always welcome.

**Comment by funixz** [comment]
any updates on this?

**Comment by imjoey** [comment]
> any updates on this?

Not yet. You could try the unofficial [imjoey/terraform-provider-ovirt](https://github.com/imjoey/terraform-provider-ovirt) , which is still under development. Any feedbacks are appreciated. Thanks.

**Comment by rgolangh** [comment]
I'm considering incubating @Maigard  @imjoey work under ovirt organization. Its good to see there is a lot of interest around it, and I hope this would translate into contributions.

If there is a preference to have it under terraform and not under ovirt please explain, and lets discuss it.

**Comment by rgolangh** [comment]
@Maigard and @imjoey if that's ok with you, in order to proceed I'd like to sync this with you:
1. I'll upload the code - while preserving history(!), to https://github.com/ovirt/terraform-provider-ovirt
2. make sure you the Authors file is updated and correct
3. update the licence to apache 2 license
4. comment a redirection notice from your forks to ovirt

**Comment by imjoey** [comment]
> @Maigard and @imjoey if that's ok with you, in order to proceed I'd like to sync this with you:
> 
> 1. I'll upload the code - while preserving history(!), to https://github.com/ovirt/terraform-provider-ovirt
> 2. make sure you the Authors file is updated and correct
> 3. update the licence to apache 2 license
> 4. comment a redirection notice from your forks to ovirt

Hi @rgolangh @Maigard , how about leveraging the Github **Transfer** [[1]] functionality to move the repo under oVirt organization? The main benefit, I think, is that besides the git commits history,  it could also be able to keep the history of issues, pull-requests and etc for us. What's your insights on that?

If so, as I have no rights to create a new repo under oVirt organization, perhaps current repo could be transferred to you @rgolangh first, and you proceed to transfer it to oVirt organization. The whole process would be very much like the transfer of ovirt-engine-sdk-go repo previously.

[1]: https://help.github.com/en/articles/transferring-a-repository

**Comment by rgolangh** [comment]
There will be a permission thing with ovirt organization. So you can transfer to me and I'll transfer to ovirt.

I'm still interested in @Maigard voice.

**Comment by rgolangh** [comment]
Happy to announce that the provider has moved under [oVirt](https://github.com/oVirt) organization
and can be found at https://github.com/oVirt/terraform-provider-ovirt

**Comment by Maigard** [comment]
Sorry I didn't get back to you. I had to ask our legal department about it and it ended up getting dropped. The only thing we need is to make sure is to make sure there is documentation that the earlier contributions are made under the original license (so there is no patent license granted by Battelle). Other than that, I am happy someone is going to continue development. My job duties changed just as I released it and I couldn't keep doing development. I can make a note that active development has moved to the oVirt fork.

**Comment by rgolangh** [comment]
@Maigard In the new [license ](https://github.com/oVirt/terraform-provider-ovirt/LICENSE) Battelle and the original license appear at the end, and its mentioned that it was forked from this organization -  please have a look.

**Comment by Maigard** [comment]
It looks good. I noted the development change in my repo.

**Comment by pkolyvas** [comment]
Closing this issue out. Thanks to all for helping bring the oVirt provider into the world and maintaining it.
