### ISSUE TITLE
Run time error:invalid memory address while running tests on resources

### ISSUE THREAD

**Issue by scshitole** [hashicorp/terraform#16162]
Hello Team,
Getting run time error while running the tests, this was not seen on 0.8.1 when I was running on my Mac, however now when I moved to 0.10.7 I tried running the tests and I am getting this error

BIGIP_HOST=10.192.74.73 BIGIP_USER=admin BIGIP_PASSWORD=admin make testacc
/bin/sh: 1: [[: not found
/bin/sh: 1: 10.192.74.73: not found
/bin/sh: 1: -z admin: not found
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
=== RUN   TestProvider
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
2017/09/22 23:25:12 Resource schema
--- PASS: TestProvider (0.00s)
=== RUN   TestBigipLtmIRule_create
--- PASS: TestBigipLtmIRule_create (0.37s)
=== RUN   TestBigipLtmIRule_import
--- FAIL: TestBigipLtmIRule_import (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x9ff287]

goroutine 228 [running]:
testing.tRunner.func1(0xc4203fc690)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0xb09980, 0xff4650)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.testResource(0xc420015140, 0x11, 0x0, 0xc42017e240, 0x8f, 0xc4202f1c80, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/work/src/github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing.go:737 +0x37
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.testStepImportState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/work/src/github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing_import_state.go:30 +0x1452
github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource.Test(0xfc69a0, 0xc4203fc690, 0x0, 0xc420043350, 0xc4201b9260, 0x0, 0x0, 0xc04128, 0xc42020ce70, 0x1, ...)
	/home/ubuntu/work/src/github.com/terraform-provider-f5/vendor/github.com/hashicorp/terraform/helper/resource/testing.go:440 +0x535
github.com/terraform-provider-f5/bigip.TestBigipLtmIRule_import(0xc4203fc690)
	/home/ubuntu/work/src/github.com/terraform-provider-f5/bigip/resource_bigip_ltm_irule_test.go:42 +0x241
testing.tRunner(0xc4203fc690, 0xc03c10)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/terraform-provider-f5/bigip	0.388s
Makefile:75: recipe for target 'testacc' failed
make: *** [testacc] Error 1
ubuntu@ubuntu-xenial:~/work/src/github.com/terraform-provider-f5$ 

ubuntu@ubuntu-xenial:~/work/src/github.com/terraform-provider-f5$ terraform --version
Terraform v0.10.7-dev

ubuntu@ubuntu-xenial:~/work/src/github.com/terraform-provider-f5$ 

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

If your issue relates to a specific Terraform provider, please open it in the provider's own repository. The index of providers is at https://github.com/terraform-providers .

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please try upgrading because your issue may have already been fixed.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and
# share a link to the ZIP file. For security, you can also encrypt the
# files using our GPG public key.
```

### Debug Output
Full debug output can be obtained by running Terraform with the environment variable `TF_LOG=trace`. Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.

Debug output may contain sensitive information. Please review it before posting publicly, and if you are concerned feel free to encrypt the files using the HashiCorp security public key.

### Crash Output
If the console output indicates that Terraform crashed, please share a link to a GitHub Gist containing the output of the `crash.log` file.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Important Factoids
Are there anything atypical about your situation that we should know? For example: is Terraform running in a wrapper script or in a CI system? Are you passing any unusual command line options or environment variables to opt-in to non-default behavior?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #6017

**Comment by scshitole** [comment]
With Vendor using terraform 8.0 this is not seen and the tests are moving ahead without any issue
SJC-ML-SHITOLE:bigip shitole$ BIGIP_HOST=10.0.1.79 BIGIP_USER=admin BIGIP_PASSWORD=admin make testacc
make: *** No rule to make target `testacc'.  Stop.
SJC-ML-SHITOLE:bigip shitole$ 
SJC-ML-SHITOLE:bigip shitole$ BIGIP_HOST=10.0.1.79 BIGIP_USER=admin BIGIP_PASSWORD=admin make testacc
make: *** No rule to make target `testacc'.  Stop.
SJC-ML-SHITOLE:bigip shitole$ pwd
/Users/shitole/dev/src/github.com/terraform-provider-bigip/bigip
SJC-ML-SHITOLE:bigip shitole$ cd ..
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ BIGIP_HOST=10.0.1.79 BIGIP_USER=admin BIGIP_PASSWORD=admin make testacc
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
=== RUN   TestProvider
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
2017/09/30 18:08:32 Resource schema
--- PASS: TestProvider (0.00s)
=== RUN   TestBigipLtmIRule_create
--- PASS: TestBigipLtmIRule_create (0.46s)
=== RUN   TestBigipLtmIRule_import
--- PASS: TestBigipLtmIRule_import (3.98s)
=== RUN   TestBigipLtmMonitor_create
--- PASS: TestBigipLtmMonitor_create (4.07s)
=== RUN   TestBigipLtmMonitor_import
--- PASS: TestBigipLtmMonitor_import (4.01s)
=== RUN   TestBigipLtmNode_create
--- PASS: TestBigipLtmNode_create (3.99s)
=== RUN   TestBigipLtmNode_import
--- PASS: TestBigipLtmNode_import (3.97s)
=== RUN   TestBigipLtmPolicy_create
--- FAIL: TestBigipLtmPolicy_create (0.00s)
	testing.go:264: Step 0 error: Configuration is invalid.
		
		Warnings: []string(nil)
		
		Errors: []string{"bigip_ltm_policy.test-policy: rule.0.condition.0: invalid or unknown key: httpUri", "bigip_ltm_policy.test-policy: rule.0.condition.0: invalid or unknown key: startsWith", "bigip_ltm_policy.test-policy: rule.0.condition.1: invalid or unknown key: httpMethod"}
=== RUN   TestBigipLtmPolicy_import
--- FAIL: TestBigipLtmPolicy_import (0.00s)
	testing.go:264: Step 0 error: Configuration is invalid.
		
		Warnings: []string(nil)
		
		Errors: []string{"bigip_ltm_policy.test-policy: rule.0.condition.0: invalid or unknown key: httpUri", "bigip_ltm_policy.test-policy: rule.0.condition.0: invalid or unknown key: startsWith", "bigip_ltm_policy.test-policy: rule.0.condition.1: invalid or unknown key: httpMethod"}
=== RUN   TestBigipLtmPool_create
--- PASS: TestBigipLtmPool_create (3.96s)
=== RUN   TestBigipLtmPool_import
--- PASS: TestBigipLtmPool_import (3.99s)
=== RUN   TestBigipLtmVA_create
--- PASS: TestBigipLtmVA_create (3.97s)
=== RUN   TestBigipLtmVA_import
--- PASS: TestBigipLtmVA_import (0.47s)
=== RUN   TestBigipLtmVS_create
--- FAIL: TestBigipLtmVS_create (0.00s)
	testing.go:264: Step 0 error: Configuration is invalid.
		
		Warnings: []string(nil)
		
		Errors: []string{"bigip_ltm_policy.test-policy: rule.0.condition.0: invalid or unknown key: httpUri", "bigip_ltm_policy.test-policy: rule.0.condition.0: invalid or unknown key: startsWith", "bigip_ltm_policy.test-policy: rule.0.condition.1: invalid or unknown key: httpMethod"}
=== RUN   TestBigipLtmVS_import
--- FAIL: TestBigipLtmVS_import (0.00s)
	testing.go:264: Step 0 error: Configuration is invalid.
		
		Warnings: []string(nil)
		
		Errors: []string{"bigip_ltm_policy.test-policy: rule.0.condition.0: invalid or unknown key: httpUri", "bigip_ltm_policy.test-policy: rule.0.condition.0: invalid or unknown key: startsWith", "bigip_ltm_policy.test-policy: rule.0.condition.1: invalid or unknown key: httpMethod"}
=== RUN   TestValidStringValue
--- PASS: TestValidStringValue (0.00s)
=== RUN   TestInvalidStringValue
--- PASS: TestInvalidStringValue (0.00s)
=== RUN   TestF5NameString
--- PASS: TestF5NameString (0.00s)
=== RUN   TestF5NameSet
--- PASS: TestF5NameSet (0.00s)
=== RUN   TestF5NameList
--- PASS: TestF5NameList (0.00s)
FAIL
exit status 1
FAIL	github.com/terraform-provider-bigip/bigip	33.008s
make: *** [testacc] Error 1
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ terraform --version
Terraform v0.10.6

SJC-ML-SHITOLE:terraform-provider-bigip shitole$ pwd
/Users/shitole/dev/src/github.com/terraform-provider-bigip
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ ls
1				launch_bigip.f5bigipmstbt10G	launch_bigip.snmptraps
CHANGES.md			launch_bigip.fastL4		launch_bigip.syslog
LICENSE				launch_bigip.fasthttp		launch_bigip.tcp-lan-profile
Makefile			launch_bigip.http2		launch_bigip.tf
README.md			launch_bigip.httpcompression	launch_bigip.vlan
bigip				launch_bigip.iapp		launch_bigip_tcp_wan_profile
crash.log			launch_bigip.iapp2		main.go
iapp.json			launch_bigip.irule		myirule.tcl
launch_bigip.asm1		launch_bigip.lic		statefile
launch_bigip.back		launch_bigip.master		terraform-provider-bigip
launch_bigip.back1		launch_bigip.ntpdns		terraform.tfstate
launch_bigip.datagroup		launch_bigip.oneConnect		terraform.tfstate.backup
launch_bigip.device		launch_bigip.provision		test.tfstate
launch_bigip.devicegroup	launch_bigip.route		vendor
launch_bigip.devicename		launch_bigip.selfipvlan		zoo.json
launch_bigip.dns		launch_bigip.snmp		~
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ cd vendor/github.com/hashicorp/terraform/terraform/
SJC-ML-SHITOLE:terraform shitole$ ls
context.go				node_root_variable.go
context_components.go			path.go
context_import.go			plan.go
debug.go				resource.go
diff.go					resource_address.go
edge_destroy.go				resource_provider.go
eval.go					resource_provider_mock.go
eval_apply.go				resource_provisioner.go
eval_check_prevent_destroy.go		resource_provisioner_mock.go
eval_context.go				semantics.go
eval_context_builtin.go			shadow.go
eval_context_mock.go			shadow_components.go
eval_count.go				shadow_context.go
eval_count_boundary.go			shadow_resource_provider.go
eval_count_computed.go			shadow_resource_provisioner.go
eval_diff.go				state.go
eval_error.go				state_add.go
eval_filter.go				state_filter.go
eval_filter_operation.go		state_upgrade_v1_to_v2.go
eval_if.go				state_upgrade_v2_to_v3.go
eval_import_state.go			state_v1.go
eval_interpolate.go			transform.go
eval_noop.go				transform_attach_config_provider.go
eval_output.go				transform_attach_config_resource.go
eval_provider.go			transform_attach_state.go
eval_provisioner.go			transform_config.go
eval_read_data.go			transform_config_flat.go
eval_refresh.go				transform_config_old.go
eval_resource.go			transform_count_boundary.go
eval_sequence.go			transform_deposed.go
eval_state.go				transform_destroy.go
eval_validate.go			transform_destroy_cbd.go
eval_variable.go			transform_destroy_edge.go
evaltree_provider.go			transform_diff.go
graph.go				transform_expand.go
graph_builder.go			transform_flatten.go
graph_builder_apply.go			transform_import_provider.go
graph_builder_destroy_plan.go		transform_import_state.go
graph_builder_import.go			transform_module_destroy_old.go
graph_builder_plan.go			transform_module_variable.go
graph_config_node.go			transform_noop.go
graph_config_node_module.go		transform_orphan.go
graph_config_node_output.go		transform_orphan_count.go
graph_config_node_provider.go		transform_orphan_output.go
graph_config_node_resource.go		transform_orphan_resource.go
graph_config_node_type.go		transform_output.go
graph_config_node_variable.go		transform_output_orphan.go
graph_dot.go				transform_provider.go
graph_interface_subgraph.go		transform_provider_disable.go
graph_walk.go				transform_provider_old.go
graph_walk_context.go			transform_provisioner.go
graph_walk_operation.go			transform_proxy.go
graphnodeconfigtype_string.go		transform_reference.go
hook.go					transform_resource.go
hook_mock.go				transform_resource_count.go
hook_stop.go				transform_root.go
instancetype.go				transform_state.go
instancetype_string.go			transform_targets.go
interpolate.go				transform_transitive_reduction.go
node_count_boundary.go			transform_variable.go
node_module_destroy.go			transform_vertex.go
node_module_variable.go			ui_input.go
node_output.go				ui_input_mock.go
node_output_orphan.go			ui_input_prefix.go
node_provider.go			ui_output.go
node_provider_abstract.go		ui_output_callback.go
node_provider_disabled.go		ui_output_mock.go
node_resource_abstract.go		ui_output_provisioner.go
node_resource_apply.go			util.go
node_resource_destroy.go		variables.go
node_resource_plan.go			version.go
node_resource_plan_destroy.go		version_required.go
node_resource_plan_instance.go		walkoperation_string.go
node_resource_plan_orphan.go
SJC-ML-SHITOLE:terraform shitole$ ls *version*
version.go		version_required.go
SJC-ML-SHITOLE:terraform shitole$ vi version.go
SJC-ML-SHITOLE:terraform shitole$ grep 'terraform version' | version.go
-bash: version.go: command not found
^C
SJC-ML-SHITOLE:terraform shitole$ cat version.go
package terraform

import (
	"fmt"

	"github.com/hashicorp/go-version"
)

// The main version number that is being run at the moment.
const Version = "0.8.0"

// A pre-release marker for the version. If this is "" (empty string)
// then it means that it is a final release. Otherwise, this is a pre-release
// such as "dev" (in development), "beta", "rc1", etc.
const VersionPrerelease = "dev"

// SemVersion is an instance of version.Version. This has the secondary
// benefit of verifying during tests and init time that our version is a
// proper semantic version, which should always be the case.
var SemVersion = version.Must(version.NewVersion(Version))

// VersionHeader is the header name used to send the current terraform version
// in http requests.
const VersionHeader = "Terraform-Version"

func VersionString() string {
	if VersionPrerelease != "" {
		return fmt.Sprintf("%s-%s", Version, VersionPrerelease)
	}
	return Version
}
SJC-ML-SHITOLE:terraform shitole$

**Comment by danieldreier** [comment]
@scshitole I'm going to close this, because it looks to me like you were testing a resource that no longer is stored in this GitHub repository. After 0.12, providers were moved to their own github repositories.
