### ISSUE TITLE
Terraform does not recognize the new AWS Region

### ISSUE THREAD

**Issue by varun7447** [hashicorp/terraform#16195]
Terraform does not recognize the new AWS Region ap-south-1 in the TF file under /tmp i see this

variable "nat_ami_map" {
  type = "map"

  default = {
    ap-northeast-1 = "ami-10dfc877"
    ap-northeast-2 = "ami-1a1bc474"
    ap-southeast-1 = "ami-36af2055"
    ap-southeast-2 = "ami-1e91817d"
    eu-central-1 = "ami-9ebe18f1"
    eu-west-1 = "ami-3a849f5c"
    eu-west-2 = "ami-21120445"
    us-east-1 = "ami-d4c5efc2"
    us-east-2 = "ami-f27b5a97"
    us-gov-west-1 = "ami-c39610a2"
    us-west-1 = "ami-b87f53d8"
    us-west-2 = "ami-8bfce8f2"
  }
}

### Terraform Version
Terraform v0.10.6
```

### Crash Output

* aws_instance.nat: 1 error(s) occurred:

* aws_instance.nat: lookup: lookup failed to find 'ap-south-1' in:

${lookup(var.nat_ami_map, var.region)}

**Comment by muresan** [comment]
Because there is no `ap-south-1` key in the map ?

**Comment by jbardin** [comment]
Hi @varun7447,

The AWS provider supports the `ap-south-1` region. It just appears that you haven't defined that key in your own configuration.

**Comment by varun7447** [comment]
I guess the issue with some other tool that I am currently using. We can
close the issue.
