### ISSUE TITLE
Marking v0.10.6 as a GitHub release

### ISSUE THREAD

**Issue by ljfranklin** [hashicorp/terraform#16201]
We have a bit of automation that pulls down the latest Terraform when a new release pops up on GitHub. Looks like the latest v0.10.6 tag didn't get marked as an official release and doesn't appear when hitting `https://api.github.com/repos/hashicorp/terraform/releases`. Could someone click the button to mark this tag as a release?

Thanks!

**Comment by matt40k** [comment]
Poke - @jbardin @apparentlymart

**Comment by jbardin** [comment]
Though a little late, this was marked along with today's release.
