### ISSUE TITLE
AWS instance is always recreated

### ISSUE THREAD

**Issue by Junkern** [hashicorp/terraform#16235]
I am currently playing around with terraform (with the goal of migrating the infrastructure)

Version:
`Terraform v0.10.6`

I noticed that no matter what I do, my `aws_instance` resources gets recreated. Here is the resource (I got rid of `Tags` and `key_name` arguments):

```
resource "aws_instance" "my_instance" {
  ami = "ami-xxxxxx"
  instance_type = "t2.micro"
  subnet_id = "${module.some_subnet_module.id}"

  security_groups = ["${module.bastion_host_module.inbound_traffic}"]
}
```

When I change a value of a resource not connected to the instance (e.g. the `port` of a `aws_alb_target_group`), `terraform plan` shows me, that `my_instance` has to be created anew:

```
id:                           "i-34g88jg39fgfsfggdfg" => <computed> (forces new resource)
      ami:                          "ami-xxxxxx" => "ami-xxxxxx"
      associate_public_ip_address:  "false" => <computed>
      availability_zone:            "eu-west-1b" => <computed>
      ebs_block_device.#:           "0" => <computed>
      ephemeral_block_device.#:     "0" => <computed>
      instance_state:               "running" => <computed>
      instance_type:                "t2.micro" => "t2.micro"
      ipv6_address_count:           "" => <computed>
      ipv6_addresses.#:             "0" => <computed>
      network_interface.#:          "0" => <computed>
      network_interface_id:         "eni-bbad4185" => <computed>
      placement_group:              "" => <computed>
      primary_network_interface_id: "eni-bbad4185" => <computed>
      private_dns:                  "ip-10-0-10-20.eu-west-1.compute.internal" => <computed>
      private_ip:                   "10.0.10.20" => <computed>
      public_dns:                   "" => <computed>
      public_ip:                    "" => <computed>
      root_block_device.#:          "1" => <computed>
      security_groups.#:            "0" => "1" (forces new resource)
      security_groups.64855703:     "" => "sg-r834gwdg" (forces new resource)
      source_dest_check:            "true" => "true"
      subnet_id:                    "subnet-23g823g" => "subnet-23g823g"
      tags.%:                       "0" => "0"
      tenancy:                      "default" => <computed>
      volume_tags.%:                "0" => <computed>
      vpc_security_group_ids.#:     "1" => <computed>
```

What throws me off is the assigning of new security groups and a new instance_id. I did not change anything in the security groups or in the `my_instance` resource  at all. 

Is this expected behaviour (if so, I couldn't find anything in the docs :/ ) or does it have something to do with dependencies on the two modules I am using?

**Comment by Junkern** [comment]
I found the culprit: I have to use `vpc_security_group_ids` instead of `security_groups` (thanks to this issue https://github.com/hashicorp/terraform/issues/7853).

**Comment by JasonOliverEmaze** [comment]
@Junkern  did you ever get a resolution o this, as  I am hitting the same problem (also using vpc_security_group_ids)?

**Comment by Junkern** [comment]
As stated above, I think my solution was to use `vpc_security_group_ids`, it worked for me. @JasonOliverEmaze 

I think it also depends on your terraform version and what kind of VPC setup you use (take a look at the comments of this issue https://github.com/hashicorp/terraform/issues/7853)

**Comment by akumlehn** [comment]
@JasonOliverEmaze I can confirm the fix also worked for me. I am deploying instances into a VPC, and noticed the corresponding note in the docs on aws_instance.[security_groups](https://www.terraform.io/docs/providers/aws/r/instance.html#security_groups) only after a lot of try and error:
```
NOTE: If you are creating Instances in a VPC, use vpc_security_group_ids instead.
```

**Comment by saggy6210** [comment]
I was also getting same issue as below:
`-/+ aws_instance.app (new resource required)
      id:                                        "i-0606021b047d26efd" => <computed> (forces new resource)
      ami:                                       "ami-0aaa3a0f6876b748c" => "ami-0aaa3a0f6876b748c"
      arn:                                       "arn:aws:ec2:us-east-1:456603727821:instance/i-0606021b047d26efd" => <computed>
      associate_public_ip_address:               "true" => "false" (forces new resource)`

resolved by changing "associate_public_ip_address" value from "false" to "true"  
terraform code:
`associate_public_ip_address = "true"`

Is it mandatory to provide this value to "true" to avoid this issue?
