### ISSUE TITLE
cycle reported when using resource attribute interpolation in local-exec destroy provisioner

### ISSUE THREAD

**Issue by jantman** [hashicorp/terraform#16237]
I have a relatively simple configuration that contains an `aws_instance` with a `local-exec` provisioner with `when=destroy` to cleanly shut down services and unmount an EBS Volume (that's attached via userdata). The provisioner command includes an interpolation of the aws_instance's ``public_ip`` attribute. However, an apply that replaces the instance (i.e. a user-data change) reports a cycle. The cycle disappears if I remove the provisioner or remove the interpolation from the command.

For... reasons... my use case isn't really a candidate for a remote-exec destroy provisioner.

### Terraform Version

0.10.6

### Terraform Configuration Files

https://github.com/jantman/tf-vol-attachment-cycle

### Debug Output

See https://github.com/jantman/tf-vol-attachment-cycle

* [with provisioner](https://github.com/jantman/tf-vol-attachment-cycle/blob/master/with_local_exec.txt) (failure)
* [without provisioner](https://github.com/jantman/tf-vol-attachment-cycle/blob/master/without_local_exec.txt) (success)
* [without interpolation](https://github.com/jantman/tf-vol-attachment-cycle/blob/master/without_interpolation.txt) (success)

### Expected Behavior

One of:

1. (preferred) When userdata changes, terraform should replace the `aws_instance` as planned, without a "phantom" cycle. This is a __destroy__ provisioner, so it should know the instance's _current_ attributes (just like a connection block would).
2. (less bad than current) Terraform __plan__ fails with an error along the lines of "Resource attribute interpolations are not permitted in provisioners for that resource".

### Actual Behavior

```
Error applying plan:

1 error(s) occurred:

* Cycle: aws_instance.ecs-instance (destroy), aws_instance.ecs-instance
```

### Steps to Reproduce

1. ``git clone https://github.com/jantman/tf-vol-attachment-cycle.git``
2. Export AWS credentials and ``AWS_REGION``.
3. ``SUBNET_ID=<subnet-XXX> ./run.sh``

**Comment by jantman** [comment]
Note that when I found it today, I _really_ thought this was a dupe of #2957. However it doesn't seem to be, as the [workaround](https://github.com/hashicorp/terraform/issues/2957#issuecomment-270049972) of setting ``skip_destroy = "true"`` on the ``aws_volume_attachment`` doesn't seem to work... the cycle still shows up exactly as before.

**Comment by jantman** [comment]
@jbardin Just a heads up that I figured out today that this issue is much simpler than I'd originally thought... it has nothing to do with the EBS Volume or Volume Attachment. It seems that the cycle shows up any time I try to interpolate a resource attribute in its own destroy-time local-exec provisioner.

**Comment by jbardin** [comment]
@jantman: Thanks for narrowing down the scope for me.
I'll see what we can do about breaking that cycle, as I agree it seems like it should be able to work.

**Comment by robax** [comment]
+1 running into this on Terraform v0.11.7. I can also confirm @jantman 's synopsis. It's worth mentioning that you might have to change `skip_destroy = "true"` in the actual TF state file for a workaround.

**Comment by kingsquirrel152** [comment]
I _think_ I just hit this in an unrelated issue. In my case the provisioner was embedded in an aws_instance. I found that instead of referencing the parent resource directly ie through `aws_instance.[name].[value]` --> You can reference `self.[value]` which forces terraform to look at the current instance instead of the projected future one.

Seems to only work in provisioners:
https://www.terraform.io/docs/configuration/interpolation.html#attributes-of-your-own-resource

Hope this helps someone.
