### ISSUE TITLE
aws_nat_gateway not supporting tags

### ISSUE THREAD

**Issue by whiskeyjimbo** [hashicorp/terraform#16241]
### Terraform Version
Terraform v0.10.7

### Terraform Configuration Files
```
resource "aws_nat_gateway" "nat_gw" {
  provider      = "aws.va"
  allocation_id = "${aws_eip.nat_eip.id}"
  subnet_id     = "${aws_subnet.public.0.id}"
  depends_on    = ["aws_internet_gateway.igw"]

  #tags = "${merge(var.default_tags, map(
  #      "Name", "ngw-main-priv",
  #      "Management", "Terraform"
  #))}"
  tags {
    Name = "gw NAT"
  }
}
```

### Expected Behavior
Expected Behavior: Nat Gateway Accepts tag values and applies to resource.
Nat Gateway supports tagging per docs (https://www.terraform.io/docs/providers/aws/r/nat_gateway.html) and per AWS (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html)

### Actual Behavior
received error:
aws_nat_gateway.nat_gw: : invalid or unknown key: tags

### Steps to Reproduce
1. Add aws_nat_gateway resource to conifig
2. Add tags.
3. terraform plan/apply

**Comment by ewbankkit** [comment]
Addressed in https://github.com/terraform-providers/terraform-provider-aws/pull/1625.
Released in [version 1.0.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#100-september-27-2017) of the AWS provider.
