### ISSUE TITLE
Terraform state rm - deletes everything

### ISSUE THREAD

**Issue by kjhosein** [hashicorp/terraform#16240]
### Terraform Version
0.9.11

### Expected Behavior
I wouldn't have imagined that `terraform state rm` without arguments would delete all of the resources in the `terraform.tfstate` file. I think this should be treated as an erroneous command by the user.

### Actual Behavior
TF removed all of the resource in the `terraform.tfstate` file. 
If remote state is configured, it'll also sync the now bare tfstate up to the remote location.

### Steps to Reproduce
`terraform state rm`

**Comment by jbardin** [comment]
Thanks for filing the issue.

This is fixed in current releases by #15479.

**Comment by alwaysastudent** [comment]
How to remove all ?

**Comment by padamczewski** [comment]
@alwaysastudent:
`terraform state rm ""` as per [this comment](https://github.com/hashicorp/terraform/pull/15479)

**Comment by rivernews** [comment]
@padamczewski 
Unfortunately when I run `terraform state rm ""`, I got the following error:

```
Error: Variable name required

  on  line 1:
  (source code not available)

Must begin with a variable name.
```

I'm on terraform 0.12.6 by the way.
