### ISSUE TITLE
aws_instance: resource name can't contain dash "-"

### ISSUE THREAD

**Issue by koooge** [hashicorp/terraform#16264]
Hi there, I encountered Error when I named ec2 instance "-foo".

### Terraform Version
Terraform v0.10.7

### Terraform Configuration Files
```hcl
resource "aws_instance" "-foo" {
...
}
```

### Debug Output
Full debug output can be obtained by running Terraform with the environment variable `TF_LOG=trace`. Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.

Debug output may contain sensitive information. Please review it before posting publicly, and if you are concerned feel free to encrypt the files using the HashiCorp security public key.

### Crash Output
```
* aws_instance.-foo: -foo: resource name can only contain letters, numbers, dashes, and underscores.
```

### Expected Behavior
Above error message shows to allow resource name can contain dash,
but "-foo" occurred an error.
("foo" and "f-oo" is OK.)

### Actual Behavior
error occured

**Comment by arshdeeptinna** [comment]
I believe all modules, providers and resources are bound to follow the following regex which do not allow "-" as the first character.
```// NameRegexp is the regular expression that all names (modules, providers,
// resources, etc.) must follow.
var NameRegexp = regexp.MustCompile(`(?i)\A[A-Z0-9_][A-Z0-9\-\_]*\z`)
```

Not sure if we even want "_" as first character either
