### ISSUE TITLE
My First Terraform Script

### ISSUE THREAD

**Issue by cpatte7372** [hashicorp/terraform#16279]
Hello Community,

I'm running my first terraform script. The script is set to create a resource group Azure. I following the document from the link https://blogs.msdn.microsoft.com/eugene/2016/11/03/creating-azure-resources-with-terraform/

When I execute the script I get the following error message:

```
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.azurerm: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".

error satisfying plugin requirements
```

I'm running TerraForm v0.10.7

Can someone please let me know where I'm going wrong?

Cheers

cpatte7372

**Comment by davidbegin** [comment]
You need to run `terraform init` before you run `terraform plan` or `terraform apply`.

That blog post just omitted that part.

**Comment by cpatte7372** [comment]
Hi David

Thanks for getting back to me

I actually ran the terraform init and that was successful. However, I still get the error. After a bit of research I ran the command terraform plan and I get the following error:

Error running plan: 1 error(s) occurred:

* provider.azurerm: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '96210bxxxxxxxxxx-647bf9xxxxxxx' with object id '96210b50-xxxxxxxxxbf9496954' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/ad93ecxxxxxxxxxeaa6a8726a7'."


Any thoughts?

Cheers

**Comment by davidbegin** [comment]
I am not too familiar with Azure credentials, but this looks like an issue with allowing terraform access to your Azure account.

I would reread over that blog post section: **Setting up Terraform Access to Azure**

**Comment by tombuildsstuff** [comment]
Hey @cpatte7372 

Thanks for opening this issue :)

There's two ways of authenticating to Azure from Terraform, either by [using your Azure CLI credentials](https://www.terraform.io/docs/providers/azurerm/authenticating_via_azure_cli.html) (which we recommend when running locally) - or [by using a Service Principal](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html) (which we recommend for shared environments).

The article you've linked too makes use a Service Principal (which has been available for longer) - however I'd suggest using the Azure CLI to authenticate instead (if you've got it installed) - if you have, would it be possible to take a look and see if this helps?

Thanks!

**Comment by cpatte7372** [comment]
Hi guys,

I fixed the terraform plan issue. I successfully have authenticated.. but I'm still getting the following problem when I try to run the script:

Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.azurerm: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".

error satisfying plugin requirements

The command terraform init is successful, but the problem persist.. I think its something very simple that I'm missing.

**Comment by cpatte7372** [comment]
Thanks guys,

I got it to work by executing terraform plan in folder in where the script was without specifying the actual folder and then I ran terraform apply.

Cheers

Carlton

**Comment by tombuildsstuff** [comment]
Hey @cpatte7372 

Awesome - glad to hear this is working for you :)

Given I believe this issue is fixed I'm going to close this issue for the moment - however please feel free to re-open it if I'm mistaken / you're still having issues.

Thanks!
