### ISSUE TITLE
Remote state output

### ISSUE THREAD

**Issue by bitbrain** [hashicorp/terraform#16277]
The [existing ](https://www.terraform.io/docs/commands/output.html) `terraform output` command allows to retrieve outputs from Terraform state files. When using a remote backend such as S3 I would like to do something like this:
```
terraform output \
-backend=s3
-backend-path=/my/s3/path/terraform.tfstate
my-output
```
Right now this is possible by initialising Terraform for one backend and then call `terraform output my-output` and then switch to another backend. Is this easier by using workspaces or is this not intended to get implemented anytime soon?

**Comment by jbardin** [comment]
Hi @bitbrain,

Workspaces may help you here, as it essentially provides "named" states. The states however, must all reside in the same backend for that to work. Using remote state data sources to get the values you want may be a good option too.

**Comment by mildwonkey** [comment]
[`terraform remote state`](https://www.terraform.io/docs/providers/terraform/d/remote_state.html) is indeed the correct option for pulling output from other statefiles. I am going to close this issue, but if `terraform_remote_state` is insufficient for your needs, please open a new feature request with additional information regarding your use case. Thanks!
