### ISSUE TITLE
Error creating list with concat

### ISSUE THREAD

**Issue by robinbowes** [hashicorp/terraform#16276]
The real problem I'm trying to solve here is creating a list of maps from multiple sources so I can DRY my AWS Elastic Beanstalk environment modules.

The `aws_elasticbeanstalk_environment` resource is configured like this:

```hcl
resource "aws_elastic_beanstalk_environment" "foo" {
  name                = "foo"
  application         = "foo_app"
  cname_prefix        = "foo"
  solution_stack_name = "64bit Amazon Linux 2017.03 v2.5.0 running PHP 7.1"
  tier                = "WebServer"

  setting = [
    {
      namespace = "aws:autoscaling:asg"
      name      = "Availability Zones"
      value     = "Any"
    },
    {
      namespace = "aws:autoscaling:asg"
      name      = "Cooldown"
      value     = "360"
    },
    {
      namespace = "aws:autoscaling:asg"
      name      = "MaxSize"
      value     = "${var.asg_max_size}"
    },

    # plus many more maps
  ]
}
```
I'm trying to generate the settings list from multiple parts so I can minimise the amount of repeated code.

I'm using `locals` to create the lists and, during initial testing, this seemed to work OK:

```hcl
locals {
  common_settings = [
    {
      namespace = "aws:autoscaling:asg"
      name      = "Availability Zones"
      value     = "Any"
    },
    {
      namespace = "aws:autoscaling:asg"
      name      = "Cooldown"
      value     = "360"
    },
  ]

  app_settings = [
    {
      namespace = "aws:autoscaling:asg"
      name      = "MaxSize"
      value     = "6"
    },
    {
      namespace = "aws:autoscaling:asg"
      name      = "MinSize"
      value     = "2"
    },
  ]
}
resource "aws_elastic_beanstalk_environment" "foo" {
  name                = "foo"
  application         = "foo_app"
  cname_prefix        = "foo"
  solution_stack_name = "64bit Amazon Linux 2017.03 v2.5.0 running PHP 7.1"
  tier                = "WebServer"
  setting             = "${concat(local.common_settings, local.specific_settings)}"
}
```
However, if I try and use values derived from other resources in the `locals` sections, it fails.

See the example below.

### Terraform Version
Terraform v0.10.7

### Terraform Configuration Files
https://gist.github.com/robinbowes/bde1c56585df284f924ee81b46a6061e

### Debug Output
https://gist.github.com/robinbowes/5af7a23b1e007c7af3a8327acca49b7d

### Crash Output
n/a

### Expected Behavior
Plan should complete successfully

### Actual Behavior
An error is reported:
```
* aws_elastic_beanstalk_environment.foo: setting: should be a list
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Important Factoids
Commenting out this map fragment fixes the error:
```
    {
      namespace = "aws:autoscaling:launchconfiguration"
      name      = "IamInstanceProfile"
      value     = "${aws_iam_instance_profile.instance.name}"
    },
```
### References
- #15911 is related to similar functionality

**Comment by apparentlymart** [comment]
Hi @robinbowes!

Nested blocks within configuration are not the same as lists of maps, since they support homogenous element types. As a consequence, this sort of dynamic creation of blocks is not currently possible.

This general problem is being discussed over in #7034, and there is some discussion in there around current ideas on how best to address this.

I'm going to close this issue to consolidate the discussion over there. Thanks for reporting this!
