### ISSUE TITLE
error when destroying a vpc

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#1628]
I consistently get this error when trying to destroy a VPC:

* Network vpc-xxxxxxxx has some mapped public address(es). Please unmap those public address(es) before detaching the gateway. (DependencyViolation)

When that happens I'm left in a state where I basically have to go through and delete everything by hand.

I know destroying a VPC is probably rare, but its useful during the initial setup (create vpc, add some things, destroy, add some more things, apply, etc.).

**Comment by bitglue** [comment]
What are the addresses still in the VPC? Do they relate to something else in your Terraform configuration?

**Comment by ryanking** [comment]
Sorry but I don't have the VPC sitting around anymore. I know there were some elastic IPs in there, but there were some other mappings too.

**Comment by phinze** [comment]
@ryanking Sorry you hit this - I've been in the same situation and it's super frustrating to have to go and clean up everything manually.

I think we might be able to file this under one of the existing bugs to keep things consolidated. Was the VPC defined in a module?

Tagged in the meantime.

**Comment by ryanking** [comment]
It was not defined in a module.

**Comment by arubis** [comment]
I run into this pretty much every time I do a destroy with my current setup.

**Comment by saulshanabrook** [comment]
Same I also hit this every time I destroy. 

![3](https://cloud.githubusercontent.com/assets/1186124/7556209/90bf298c-f735-11e4-861c-54b7ad37a2d0.png)

**Comment by catsby** [comment]
Can anyone contribute a configuration that reproduces this and omits any secrets? 
I'd like to debug and try and patch if possible.

**Comment by mikeyhill** [comment]
I just had this happen and it occurs maybe 1 out of 4 destructions, but I haven't been able to determine the cause.  I have my VPC provisioned in a module and when this does occur Terraform freezes up on a EIP destruction.  So-far I've been lucky that all the resources were destroyed aside from a stray launch config that seems to linger around.  I'll see if I can replicate this consistently and send my config (it's pretty large so is there something specific you need?)

**Comment by mikeyhill** [comment]
Actually just noticed it happened again while I was typing this but froze up in a different place (aws_vpc.main-vpc: Destruction complete) and left two launch configs behind.

**Comment by saulshanabrook** [comment]
@catsby I will isolate a configuration later today.

**Comment by catsby** [comment]
@saulshanabrook thanks! It's likely a eventual consistency thing with AWS waiting on this or that to shut down in order to destroy. Something else gets a head of itself in deleting and errors out.

We can either instruct people to use `depends_on`, or try a more graceful polling approach. Depends on the situation
