### ISSUE TITLE
Segfault trying to do anything with 64bit exe

### ISSUE THREAD

**Issue by ch3pjw** [hashicorp/terraform#16298]
### Terraform Version
v0.10.7

### Terraform Configuration Files
None

### Debug Output
None

### Crash Output
`zsh: segmentation fault  terraform --version`

### Expected Behavior
Not died in a giant firey segfault!

### Actual Behavior / Reproduction
I downloaded the [latest 64bit terraform exe](https://www.terraform.io/downloads.html), put it in a dir on my `PATH` and then ran `terraform --version`. This resulted in a segfault. 32 bit version works fine. I'm running 64bit Linux Mint:
```
uname -a
Linux hostname 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tombuildsstuff** [comment]
@ch3pjw just to ensure I understand how to tag this issue correctly - are you referring to using the 64-bit Windows binary within Linux Mint via the Windows Subsystem for Linux; or using the 64-bit Linux binary on Linux Mint?

Thanks!

**Comment by ch3pjw** [comment]
Ah, sorry. I just mean the regular Linux 64 bit executable. I wasn't sure how to provide any better diagnostics other than that it segfaulted.

**Comment by ch3pjw** [comment]
I've investigated this further and I think something was wrong with my binary - a fresh download today appears to be working fine. Sorry to have wasted your time!

**Comment by tombuildsstuff** [comment]
@ch3pjw no worries - glad to hear this is now working for you :)
