### ISSUE TITLE
Allow forwarding of SSH Agent to remote-exec target

### ISSUE THREAD

**Issue by arubis** [hashicorp/terraform#1630]
The `remote-exec` provisioner knows how to use local ssh-agent to authenticate to its target machine, but doesn't currently allow forwarding of the agent's credentials to that target.

### Desired behavior:
given that:
  - terraform is run as a user with ssh-agent running;
  - a github-authorized key is added to said ssh-agent;
  - ~/.ssh/config allows agent fowarding;
  - the SSH server on the provisioned resource allows ssh-agent forwarding;
  - the login user on the provisioned resource does _not_ have a github-authorized SSH key;

then:
```
resource "service" "instance" {
  provisioner "remote-exec" {
    connection {
      agent = true
      # some-option-to-allow-agent-forwarding[default:false] = true
    }

    inline = [
      "git clone git@github.com:user/private-repo.git /clone/target"
    ]
  }
}
```
should clone from private-repo.

I am not Golang-savvy; however, https://godoc.org/golang.org/x/crypto/ssh/agent documents funcs ForwardToAgent and ForwardToRemote, which suggests to me that this functionality is available in crypto/ssh/agent.

**Comment by phinze** [comment]
Thanks for the detailed report and the link, @arubis!

I'm working in the area this week so I should be able to pick this up.

**Comment by radeksimko** [comment]
I actually think the forwarding should just work out of the box, I'm not sure whether there are any negative security consequences, but it's just the default behaviour of most SSH clients, so I believe there's no need for extra options like `agent = true`.

**Comment by neerfri** [comment]
@radeksimko as far as I know this is not the default behavior of most SSH clients.
The reason is that this is a HUGE attack surface and a user should know that they are opening this attack surface.

You can see a few links that speak about this:
http://blog.hypergeometric.com/2012/02/22/ssh-dos-and-donts/
http://blog.lyte.id.au/2012/03/19/ssh-agent-forwarding-is-a-bug/
http://www.informit.com/articles/article.aspx?p=602977&seqNum=3

**Comment by radeksimko** [comment]
@neerfri Ah, my apologies, you're right. People actually have to set `ForwardAgent` to `yes` in case of unix ssh client.

**Comment by radeksimko** [comment]
but to be fair, as long as you enabled forwarding for a particular hostname, you're just forwarding **all keys** that are currently in your agent.

**Comment by phinze** [comment]
Terraform 0.6.0 has SSH Bastion support and SSH Agent forwarding support!

After discussing internally we decided that given Terraform's use case in a specific domain (as opposed to the generalized nature of the ssh client itself), it is worth the UX benefit to enable both agent authentication and agent forwarding by default when the associated environment variable is available at runtime.

Users concerned about the security implications of this can include `agent = false` in their configs to opt out of the behavior.

**Comment by nelsonenzo** [comment]
I'm using Terraform 0.6.3 and I am not finding agent forwarding to work.

```sh
### Local osx machine ~/.ssh/config
Host *
  ForwardAgent yes
```

```sh
### connection block in my plan
    provisioner "remote-exec" {
      inline = ["/bin/bash ~/bootstrap.sh"]
      connection {
                agent = true
                user = "ubuntu"
      }
    }
```
It fails a git pull in the bootstrap.  But if I ssh onto the machine it created, doing nothing special:
```
ubuntu@ip-123-45-67-225:~$ ssh -T git@github.com
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Hi company/repo! You've successfully authenticated, but GitHub does not provide shell access.
```
