### ISSUE TITLE
"terraform fmt" is slow

### ISSUE THREAD

**Issue by kevinburke** [hashicorp/terraform#16316]
Running "terraform fmt" on a 50 line Terraform file I have with maybe 20 declarations is extremely slow:

```
$ time terraform fmt terraform.tfvars
terraform fmt terraform.tfvars  0.08s user 0.08s system 7% cpu 2.269 total
```

There's nothing significant or unusual about the file in question. I am wondering why it is so slow to format? It makes it impractical to reformat files when you save a file, because it's so slow.

I'm wondering if it's doing anything obviously silly like make a network call, or perform an `O(n^2)` operation on the file in question? Maybe there is a quick win somewhere that can improve the performance by a lot.

**Comment by apparentlymart** [comment]
Hi @kevinburke! This is indeed strange. Sorry it's being so slow!

Given how little time it's spending actually holding the CPU, I share your suspicion that this is an inadvertent network call. The most likely culprit is the [Checkpoint](https://www.terraform.io/docs/commands/index.html#upgrade-and-security-bulletin-checks) service that's used to check if there's a new version of Terraform available; there's no good reason why we should be doing that on `terraform fmt`, but maybe that's the bug...

If you happen to still have your test case handy, a quick way to verify this would be to try it again with checkpoint disabled, like this:

```
$ CHECKPOINT_DISABLE=1 time terraform fmt terraform.tfvars
```

If that makes it significantly faster, then that's almost certainly our culprit and we can look at skipping this call for "trivial" actions like `fmt`, where the time taken to do this lookup will almost certainly be longer than the main operation. (It's supposed to run in the background while other things are going on, but that assumes that the "other things" take longer than the lookup, of course.)

**Comment by kevinburke** [comment]
hmmm, nope

```
$ time CHECKPOINT_DISABLE=1 terraform fmt terraform.tfvars
CHECKPOINT_DISABLE=1 terraform fmt terraform.tfvars  0.06s user 0.11s system 7% cpu 2.376 total
```

**Comment by kevinburke** [comment]
I periodically recompile Go from tip. I would be surprised if that was an issue, though it may be an issue.

**Comment by kevinburke** [comment]
Ah, the slowdown was because I compiled terraform with the race detector. (I contribute to the go project and am interested in finding edge cases in Go software and software I use). Still, this slowdown is very noticeable.

```
0s kevin at warthog in ~/src/...
± (ads-3*) $ time ~/bin/terraform fmt dev/terraform.tfvars
~/bin/terraform fmt dev/terraform.tfvars  0.02s user 0.02s system 52% cpu 0.085 total
```
Without the race detector:
```
0s kevin at warthog in ~/src/...
± (ads-3*) $ time ~/bin/terraform fmt dev/terraform.tfvars
~/bin/terraform fmt dev/terraform.tfvars  0.09s user 0.07s system 7% cpu 2.164 total
```

**Comment by kevinburke** [comment]
Apparently a 20x slowdown is within the bounds of acceptable performance, so I'm closing.

See also golang/go#22244.
