### ISSUE TITLE
Bug: leading whitespace causes aws_iam_policy to incorrectly report valid JSON policies as invalid

### ISSUE THREAD

**Issue by MikeSchuette** [hashicorp/terraform#16319]
### Terraform Version
0.10.7, 0.9.11

### Terraform Configuration Files
```hcl
resource "aws_iam_policy" "nodes_sqs_policy" {
    name        = "nodes_sqs_policy"
    description = "nodes SQS"
    policy = <<EOF
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "sqs:GetQueueAttributes"
          ],
          "Resource": [
            "arn:aws:sqs:us-east-1:123123123:myapp-dev-us-east-1*"
          ]
        }
      ]
    }
EOF
}
```

### Expected Behavior
The policy was applied

### Actual Behavior
```
1 error(s) occurred:

* aws_iam_policy.nodes_sqs_policy: "policy" contains an invalid JSON policy
```

### Important Factoids
Removing the whitespace before the first character in the policy allows it to be applied:
```hcl
data "template_file" "nodes_iam_sqs" {
    name        = "nodes_sqs_policy"
    description = "nodes SQS"
    policy = <<EOF
{
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "sqs:GetQueueAttributes"
          ],
          "Resource": [
            "arn:aws:sqs:us-east-1:123123123:myapp-dev-us-east-1*"
          ]
        }
      ]
    }
EOF
}
```

According to [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt), "Insignificant whitespace is allowed before or after any of the six structural characters."

### References
#11906 is where the JSON validation was applied.

**Comment by MikeSchuette** [comment]
Aaand this is in the wrong repo.

**Comment by jlyons18** [comment]
just ran into this issue, thanks

**Comment by woodcockjosh** [comment]
lame. Can we please fix? Thanks

**Comment by MikeSchuette** [comment]
The AWS provider has moved out of the main terraform repo, and along with it this bug: https://github.com/terraform-providers/terraform-provider-aws/issues/1873

**Comment by JoeyGarcia** [comment]
I had the same problem and got it fixed by removing all the spaces before the left curly brace that is immediately after the <<EOF, that curly brace should be on it's own line and position 0.
