### ISSUE TITLE
module-output for data elements?

### ISSUE THREAD

**Issue by jerger** [hashicorp/terraform#16323]
Hi,

is there a way to define inline policy data as module-output?

```
data "template_file" "key_management_policy" {
  template = "${file("${path.module}/resources/key_policy.json")}"
}

output "key_management_policy" {
  value = "${template_file.key_management_policy.rendered}"
}
```

Used tf-version: v0.10.7

BR, jerger

**Comment by apparentlymart** [comment]
Hi @jerger!

This should work, but note that when interpolating a data source result you need to use the `data.` prefix:

```hcl
output "key_management_policy" {
  value = "${data.template_file.key_management_policy.rendered}"
}
```

**Comment by jerger** [comment]
Hi @apparentlymart 

thanx for your answer. I tried this out but unfortunately got:

`Error getting plugins: module root: module '...': key_management_policy is not a valid output for module ...`

Is there a difference between data elements and other elements?

**Comment by apparentlymart** [comment]
Hi @jerger,

There is currently a limitation where any errors in resolving an output don't get displayed, as a side-effect of how outputs are handled internally. There is a fix for this coming soon, but in the mean time it can be helpful to try the same interpolation inside a placeholder resource to see if it's able to run without errors. For example:

```hcl
resource "null_resource" "placeholder" {
  triggers = {
    "value": "${data.template_file.key_management_policy.rendered}"
  }
}
```

If you add the above and apply it, you should either get a successful result with the rendered template result in that value, or some sort of error evaluating that expression. If an error is produced, it will hopefully give a clue as to what's going on here.

I don't know, based on what I can see here, why such an expression would fail, but trying this will at least help to understand the nature of this bug, and whether it's an issue we already know about or not.

**Comment by jerger** [comment]
Hi @apparentlymart,

you're right. I tested here (https://github.com/DomainDrivenArchitecture/meetup-sandbox/tree/master/terraform-example/data-output) and the transport through modules output is working fine :-)

Thanks for your assistence :-)
