### ISSUE TITLE
website: various stale docs about provider plugins

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#16325]
Since the core/provider split, some details changed about how provider plugins are developed and distributed. While we updated _some_ of the docs to reflect this, there are still some leftover stale things to update. Including (but not limited to):

* [ ] [_Writing Custom Providers_](https://www.terraform.io/guides/writing-custom-terraform-providers.html) doesn't mention that you need to put the built plugin somewhere that `terraform init` will find it, and that you need to run `terraform init` (or override the provider lock using the `TF_SKIP_PROVIDER_VERIFY` environment variable) each time the binary changes.
* [ ] We have some extensive docs on [internal plugins](https://www.terraform.io/docs/internals/internal-plugins.html) that are primarily concerned with the upgrade path to Terraform 0.7. While internal plugins are still used for provisioners, they are far less important than they were prior to 0.10 so we may consider eliminating these docs altogether.
* [ ]  We have a generic section on [developing plugins](https://www.terraform.io/docs/plugins/index.html) which duplicates a lot of the content of [_Writing Custom Providers_](https://www.terraform.io/guides/writing-custom-terraform-providers.html), and so over time the two have drifted and are now inconsistent. We should consider reducing or eliminating the former in favor of the latter. (The former is, in principle, also applicable to provisioner development; in practice, it focuses mainly on provider development, and is thus quite redundant.)
* [ ] We have a section [Installing a Plugin](https://www.terraform.io/docs/plugins/basics.html#installing-a-plugin) which seems to be aimed at plugin _users_ rather than plugin _developers_, but yet it's in a section that is otherwise mainly concerned with plugin development. In the doc updates for 0.10 we also added [a user-facing guide to third-party plugins](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins), which seems to now make the earlier section redundant.

There are probably other things of this type too. When working on these updates, we should take some time to look around for other mentions of related information that may also have become stale.

**Comment by clebio** [comment]
At least the first item seems to be covered in the current docs for Writing Custom Providers

**Comment by apparentlymart** [comment]
Hi @clebio! Thanks for the ping on this... this issue is old and the docs I was referring to here have since all been reorganized into the larger [Extending Terraform](https://www.terraform.io/docs/extend/) section, so indeed I think this issue is now redundant and I'll close it. If there are any issues in the new docs then we can discuss them via separate issues, since the structure of the docs is now quite different than it was when I wrote this issue anyway.
