### ISSUE TITLE
Terraform issue when trying to deploy VM to Azure

### ISSUE THREAD

**Issue by joda10** [hashicorp/terraform#16358]
Hi people,

I've been having an issue trying to build out an environment with terraform. The issue is all is running ok until it comes to the VM creation where it bombs out.

I'm using terraform to build an environment in Azure. All work if I do this manually but with terraform is a no go. But only the VM part.

I have attached all the info needed can anyone help with this issue.

Thanks

J

### Terraform Version
Terraform v0.10.7

### Terraform Configuration Files
Link to terraform config file:

https://www.dropbox.com/sh/xrf5a5uiwfdo6cf/AABOoZKdeZDqrsOQKQOVqS-0a?dl=0

### Debug Output
Link to terraform Trace file:

https://www.dropbox.com/sh/xrf5a5uiwfdo6cf/AABOoZKdeZDqrsOQKQOVqS-0a?dl=0

### Crash Output
Link to console output:

https://www.dropbox.com/sh/xrf5a5uiwfdo6cf/AABOoZKdeZDqrsOQKQOVqS-0a?dl=0

### Expected Behavior
The environment built with the VM in it.

### Actual Behavior
bombs out on the VM creation.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Important Factoids
Running from Windows 10 with bash CLI

### References
None

**Comment by tombuildsstuff** [comment]
Hi @joda10 

Thanks for opening this issue :)

Taking a look at the files you've provided - the error message that Terraform's outputting says that the VM Size / SKU you're trying to provision (`Standard_DS1_v2`) isn't available in the `uksouth` region.

> * azurerm_virtual_machine.test: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="SkuNotAvailable" Message="The requested size for resource '/subscriptions/0000-0000-0000-0000-000000000000/resourceGroups/SBN-RG-VM/providers/Microsoft.Compute/virtualMachines/sbnacctvm01' is currently not available in location 'UK South' zones '' for subscription 'a9ae3abb-308c-4d3a-bc71-7810b7ae5913'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details."

From what I recall, this VM Size has been deprecated and is only available to existing customers / quotas. As such would you be able to try this using another VM size, such as `Standard_F2` and see if that solves your issue?

Thanks!

**Comment by joda10** [comment]
Hey tombuildsstuff,

I have this resolved now as my subscription in the Azure UK South (London) didn't have these VMs available. I have spoken to Microsoft and these are now available in my subscription.

Thanks

J
