### ISSUE TITLE
workspace_key_prefix contains more than one folder

### ISSUE THREAD

**Issue by dpavlov-smartling** [hashicorp/terraform#16383]
Hello, 

Seems like terraform isn't able to handle **workspace_key_prefix** which contains more than one word like:
**workspace_key_prefix = "rds-test/rds-logs-download"**
Actually it is able to create workspace and put terraform state file into needed path, but doesn't show it when you execute:
terraform workspace list

Initial task is to put state files of all workspaces inside sub-folder into main bucket like /BUCKET/SUB-folder1/SUB-folder2/WORKSPACE-NAME/terraform.tfstate, so I have used following backend configuratin:
```
terraform {
  backend "s3" {
    bucket               = "XXXXXX-terraform"
    key                  = "rds-logs-download.tfstate"
    region               = "us-east-1"
    workspace_key_prefix = "rds-test/rds-logs-download" 
  }
}

```
### Expected Behavior
According to documentation at https://www.terraform.io/docs/backends/types/s3.html#key path should be following:
XXXXXX-terraform/rds-test/rds-logs-download/<WORKSPACE_NAME>/rds-logs-download.tfstate
### Actual Behavior
```
terraform workspace new test2
Created and switched to workspace "test2"!

terraform workspace list
  default

terraform workspace new test3
Created and switched to workspace "test3"!

terraform workspace list
  default
```

While it DOES create structure inside S3 backet:
aws s3 ls XXXXXXXXX-terraform/rds-test/rds-logs-download/test
                           PRE test2/
                           PRE test3/

### Steps to Reproduce
Just try to use backend as was provided above and create few workspaces.

terraform version
Terraform v0.10.7

**Comment by completenovice** [comment]
This is affecting us too, it is stopping us rolling out workspaces to our teams as it is not clear on which workspace a user is on.

**Comment by xatnys** [comment]
Also affecting us.

**Comment by mbowiewilson** [comment]
I'm still having this problem with v0.11.3

**Comment by redbaron** [comment]
@mbowiewilson , @jbardin I can confirm that with TF 0.11.3 this is still not solved. `terraform workspace select <name>` doesn't find  workspace

**Comment by jbardin** [comment]
@mbowiewilson: If you can a reproducible case, please feel free to open a new about and we can look into it. Thanks!

**Comment by redbaron** [comment]
@jbardin IMHO it is better to have this issue reopened as problem described here is not solved. My reproducible test case is like for like with one reported here , with slight variation to actual values used:

```
terraform {
  backend "s3" {
    bucket = "XXXX-terraform" 
    key = "pubweb.tfstate"
    region = "eu-west-2"
    workspace_key_prefix = "pubweb/env:"
  }
}
```

**Comment by jbardin** [comment]
@redbaron,

While the issue may look superficially similar, I'd rather have a new issue open if the underlying cause if different.

Can you provide the steps required to reproduce an issue with your configuration? What you have here should work as expected. Using your configuration:

```
$ tf init
Terraform has been successfully initialized!
...
$ tf workspace list
* default

$ tf workspace new foo
Created and switched to workspace "foo"!

$ tf workspace new bar
Created and switched to workspace "bar"!

$ tf workspace list
  default
* bar
  foo
```

**Comment by bakaie** [comment]
did not see this issues I did some updates on the one as well:

https://github.com/hashicorp/terraform/issues/17508

found a work around for now.  If you place a path in the key field it works.  So based on the example you have above.

```
terraform {
  backend "s3" {
    bucket               = "XXXXXX-terraform"
    key                  = "rds-logs-download.tfstate"
    region               = "us-east-1"
    workspace_key_prefix = "rds-test/rds-logs-download" 
  }
}

```

if you change to the following:

```
terraform {
  backend "s3" {
    bucket               = "rds-test/rds-logs-download/XXXXXX-terraform"
    key                  = "rds-logs-download.tfstate"
    region               = "us-east-1"
  }
}

```
it will store things in env:/rds-test/rds-logs-download/xxxxxx-terraform in the s3 bucket.  

I will be using this for now until the prefix is working.
