### ISSUE TITLE
Bug: Cannot use keys containing hyphens in TypeSet.

### ISSUE THREAD

**Issue by tpounds** [hashicorp/terraform#1641]
It appears you cannot use keys containing hyphens inside of a TypeSet. It appears this behavior is a result of some logic introduced in 83c760fc to include item hashcodes within the key.

https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L820
https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L835

I suspect the s/-/~/ magic exists because the hash function signature returns a signed integer.

```go
Set: func(v interface{}) int {
   return -1234
},
```

I've provided a minimum example that can reproduce the behavior.

main.tf:
```
resource "foo_resource" "myFoo" {
   myTypeSet = {
      key-with-hyphens = "baz"
   }
}
```

foo_resource.go:
```go
"myTypeSet": &schema.Schema{
	Type:     schema.TypeSet,
	Optional: true,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"key-with-hyphens": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
			},
		},
	},
}
```

terraform apply stdout:
```
foo_resource.myFoo: Creating...
  myTypeSet.#:                   "0" => "1"
  myTypeSet.0.key~with~hyphens:  "" => ""
```

**Comment by tpounds** [comment]
FWIW, it looks like the internal helper hashcode String function enforces non-negative integers. This was enforced by commit a5040ecc.

https://github.com/hashicorp/terraform/blob/master/helper/hashcode/hashcode.go#L14

If changing existing hash functions is not an option I think enforcing non-negative hashcodes would be a backwards compatible code change. All bets are off for any hashcodes stored in local state.

**Comment by mitchellh** [comment]
The schema you entered is not valid: it is missing the hash function. I'm assuming this is an oversight. But anyways, I still don't see the problem here? We make sure the hash is positive (if its negative we multiple by -1, effectively). How does this affect things?

**Comment by tpounds** [comment]
Oops. It's definitely an oversight. I copied the schema from some code and redacted a lot of internal stuff for the bug report. After looking at the code a bit more I couldn't trace how the hashcodes are related and eventually added to the set keys. What I observe is that any key that contains a '-' is eventually replaced by the '~' per lines in schema.go@820/835 and it looks like this behavior was deliberately done by design. Unfortunately, I'm not familiar enough with the code to know what the intended behavior is supposed to be. I'll dig a bit further to see if I can find out what is happening in more detail.

**Comment by mitchellh** [comment]
Got it, I have a feeling I know what you're getting at now. Thanks for the clarification!

**Comment by tpounds** [comment]
I've submitted a pull request that mitigates the issue for arbitrary keys containing hyphens. Let me know if you see any issues with it.
