### ISSUE TITLE
ASG run command on boot

### ISSUE THREAD

**Issue by mzupan** [hashicorp/terraform#1643]
In cloud formation we do something like

```
"UserData" : {
          "Fn::Base64" : {
            "Fn::Join" : ["",[
              "#!/bin/bash -ex","\n",
              "NAME=1-api-batch-01","\n",
              "ROLE=role[api-batch]","\n",
              "aws s3 cp s3://", {"Fn::FindInMap":["EnvMap", {"Ref":"Environment"}, "ChefBucketName"] }, "/chef/chef_bootstrap.sh /tmp/chef_bootstrap.sh","\n",
              "chmod 700 /tmp/chef_bootstrap.sh","\n",
              "/tmp/chef_bootstrap.sh $NAME $ROLE","\n",
              "rm /tmp/chef_bootstrap.sh","\n",
              ""
              ] ]
          }
        }
```

I'm wondering if there is a way to do something in terraform to create an autoscale group that will run a set of commands once the instance starts up. 

Or just have to bake it into the loaded AMI?

**Comment by radeksimko** [comment]
User-data is an AWS-specific feature and you should be able to pass any user-data via `aws_launch_configuration.*.user_data`

See docs: https://www.terraform.io/docs/providers/aws/r/launch_config.html#user_data
