### ISSUE TITLE
Support the count parameter for modules

### ISSUE THREAD

**Issue by AndrewFarley** [hashicorp/terraform#16436]
Ref: https://github.com/hashicorp/terraform/issues/953

Wanted, to re-bring this issue to light, with the new module registry this concept is more than ever becoming extremely important.  Is this on the roadmap or can we get it on the roadmap?

**Comment by apparentlymart** [comment]
Hi @AndrewFarley,

This is not something that had fallen into the dark :grinning: it's just something that needs a lot of work to be done before it can be achieved. Early parts of that work are underway. We'll get to count for modules once the foundational work has been completed to enable it.

**Comment by AndrewFarley** [comment]
Alright, just no visibility (that I can tell) into that fact.  Thanks, eager for the feature.  Cheers!
