### ISSUE TITLE
Missing doc for provider.version constraint

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform#16465]
On `terraform init`, it is suggested to specify the constraint `version = "~> 1.0"` but I can't find any documentation about the constraint format.

I'm not sure what `~> 1.0` means, and how to specify a minimum version, a maximum version or a specific version myself.

**Comment by salimane** [comment]
any update on this ?

**Comment by nbering** [comment]
https://www.terraform.io/docs/configuration/providers.html#provider-versions

**Comment by lra** [comment]
It does not explain the format: What `version = "~> 1.0"` means? What is allowed to write?

**Comment by nbering** [comment]
You're right, it isn't documented in the same place. It is  the same specification as the Terraform block's version constraint parameter.

https://www.terraform.io/docs/configuration/terraform.html#specifying-a-required-terraform-version

**Comment by lra** [comment]
I see, thanks!

Would you accept a PR to at least add a pointer to this doc?

**Comment by pkolyvas** [comment]
It looks like the pages/sections in question are now pointing to each other. If you do feel it's unclear, I can re-open and we would absolutely accept a PR. Thanks to everyone here for their contribution.
