### ISSUE TITLE
AWS Autoscaling Group & Launch Configuration ordering error

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#1648]
I've been running into problems making changes to an AWS Launch Configuration. 
Very similar to https://github.com/hashicorp/terraform/issues/532 and according to https://github.com/hashicorp/terraform/commit/09f5935993d05c11b589b8fcdd709d833463dde3 I should set `create_before_destroy = true`.

Setting that lifecycle value allows changes to the Launch Configuration to work, but it prevents setting up a new environment from a clean slate. Since there isn't an existing Launch Configuration, Terraform seems to end up in a cycle dependency.

**Comment by phinze** [comment]
We're working on making improvements around the cycle detection error messaging, so this is definitely a confusing state to be in right now. But the fact is that you can introduce legitimate cycles when you add `create_before_destroy` to a resource that has non-CBD dependencies.

If you add CBD to the chain of resources depended on by your launch configuration, does that sort the cycle for you?

**Comment by johnrengelman** [comment]
I had tried that, but it didn't seem to help at the time. Not at a point where I can go back and try it again either.

**Comment by phinze** [comment]
> Setting that lifecycle value allows changes to the Launch Configuration to work, but it prevents setting up a new environment from a clean slate. Since there isn't an existing Launch Configuration, Terraform seems to end up in a cycle dependency.

@johnrengelman having trouble coming up with a repro case here, do you think you might be able to give an example of the configs you're working with when you encounter this problem?

**Comment by johnrengelman** [comment]
The sample here: https://github.com/hashicorp/terraform/issues/1637#issuecomment-95590544 is what was doing it for me.

Having the `create_before_destroy` only worked if the LC was already existing. When it was deleted, I couldn't create a brand new one.

**Comment by mitchellh** [comment]
I'm going to say this is fixed or a dup of #1109 depending on what it is describing? If not, please let me know.
