### ISSUE TITLE
Changing `path` of Consul Key requires 2 applies

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#1649]
I'm using Consul to store AMI ids for Launch Configurations. The key path in Consul contains the version of the AMI we've built. We we update to a new version, we change the path for the `consul_keys` in Terraform. Running `terraform apply` will recreate the `consul_keys` resource, but not update the Launch Configuration that is using the value. A second `terraform apply` is required.

I tried adding a `depends_on` but that didn't make a difference.

```
resource "consul_keys" "kibana_ami" {
  key {
    name = "ami_id"
    path = "amis/kibana/4.0.2-5/us-east-1"
  }
}

resource "aws_launch_configuration" "kibana_conf" {
  lifecycle {
    create_before_destroy = true
  }
  depends_on = ["consul_keys.kibana_ami"]
  image_id = "${consul_keys.kibana_ami.var.ami_id}"
  instance_type = "m3.medium"
  key_name = "peoplenet-load"
  root_block_device {
    volume_type = "gp2"
    volume_size = 8
  }

  associate_public_ip_address = true
}
```

**Comment by phinze** [comment]
I believe this is still and issue, and I believe it's the same issue that affects atlas_artifacts. I'm going to dig into this soon. Adding the `core` label as I think it has to do with TypeMap computed variable references generally.

**Comment by mitchellh** [comment]
@phinze @johnrengelman Is this fixed/addressed at all with data sources?

**Comment by mitchellh** [comment]
Confirmed data sources does fix this.
