### ISSUE TITLE
Terraform Provisioner Spams SSH When Key is Bad

### ISSUE THREAD

**Issue by davefreitag** [hashicorp/terraform#16497]
Using a third party provider (IBM). We're using a destroy provisioner to make an SSH connection on destroy to do some cleanup. The definition looks like this. 

```
resource "ibm_compute_vm_instance" "manager" {
    hostname                 = "davemgr"
    domain                   = "ibmcloud.com"
 ... (There are other parameters, skipping to save space)

    # On destroy commands
    provisioner "remote-exec" {
        when = "destroy"
        on_failure = "continue"
        inline = [
          "sudo /var/ibm/d4ic/infrakit.sh group/workers destroy; sudo /var/ibm/d4ic/infrakit.sh group/managers destroy"
        ]
        connection {
          type        = "ssh"
          user        = "docker"
          private_key = "${var.private_key}"
        }
    }
}
```

I accidentally provided our destroy provisioner with a bad SSH key. When it came time to do a terraform destroy, the destroy provisioner couldn't access the machine to run its final command. (As expected, this was my fault).

It didn't give up after 4 or 5 failed attempts, though. It attempted the SSH connection continuously for 5 minutes. Ultimately it tried to connect over 14,000 times before giving up. I've uploaded the terraform destroy log, as well as the auth log from the server in question (in case you want to see what it looks like)

[destroy.txt](https://github.com/hashicorp/terraform/files/1427624/destroy.txt)
[auth.txt](https://github.com/hashicorp/terraform/files/1427625/auth.txt)

This resulted in a couple of network alerts. It was user error on my part since I was ultimately responsible for providing the key, but I'd like to be able to avoid this behavior altogether (even if I do screw up the private key).

We're using an older version of terraform (0.9.8) in this case, but I can recreate with newer versions as well.  Checking the documentation for provisioners, there doesn't seem to be a way to throttle SSH. The closest thing available is the `timeout` parameter, which just specifies the overall connection timeframe. It would be nice if we could specify a max number of attempts, or number of seconds  between attempts. That way we're not just pounding SSH.

**Comment by jbardin** [comment]
Hi @davefreitag,

This should have been mitigated by #15772, but you mention that you can recreate this with newer versions. What behavior did you see with the current release?

**Comment by jbardin** [comment]
Closing for now. Feel free to response again if there it is still an open issue.
