### ISSUE TITLE
`terraform graph [some saved plan]` graphs the resource tree, not the plan

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#1650]
`terraform graph [a saved plan]` and `terraform graph` output the same graph. For example, create a simple configuration:

```
resource "aws_security_group" "test" {
    name = "test"
    description = "does nothing."
}
```

Apply it. Now add another resource:

```
resource "aws_security_group" "test" {
    name = "test"
    description = "does nothing."
}

resource "aws_security_group" "test2" {
    name = "test2"
    description = "does nothing."
}
```

Save the plan:

``` console
$ awsudo -u phil terraform plan -out plan
Refreshing Terraform state prior to plan...
[...]
Path: plan

+ aws_security_group.test2
    description: "" => "does nothing."
    egress.#:    "" => "<computed>"
    name:        "" => "test2"
    owner_id:    "" => "<computed>"
    vpc_id:      "" => "<computed>"
```

Now graph the plan:

``` console
$ terraform graph plan 
digraph {
    compound = true;
    "root" [shape=circle];
    "root" -> "aws_security_group.test";
    "root" -> "aws_security_group.test2";
    "aws_security_group.test" [
        label="aws_security_group.test"
        shape=box
    ];
    "aws_security_group.test2" [
        label="aws_security_group.test2"
        shape=box
    ];
    "provider.aws" [
        label="provider.aws"
        shape=diamond
    ];
}
```

Note that the graph in no way reflects the plan which is to create only `test2` (because `test` already exists). Running just `terraform graph` outputs an identical graph (though sometimes the statements are in a different order).

You can also get similar effects by creating a situation where the plan should be deleting something. Say we apply the configuration that creates just `test`, then we remove `test` from the configuration so now the configuration is empty, and the plan is to delete `test`. Run `terraform plan -out plan`, then `terraform graph plan`, and you get an empty graph. No indication of the plan to delete anything at all.

**Comment by bitglue** [comment]
For posterity, @phinze tells me #1661 might address this problem, so when it lands I'll re-test.

**Comment by phinze** [comment]
Looks like #1661 won't do it quite yet - will probably not be able to repair this functionality for 0.5 so I'll update the docs for now and we'll get it back in soon.

**Comment by phinze** [comment]
Reviewing some old issues. This is still valid. The `terraform graph` code needs some love. I have a few branches floating around with spikes of ideas. Will circle back around to this at some point. :+1:

**Comment by apparentlymart** [comment]
Thanks for opening this many moons ago, @bitglue.

As far as I can tell, this got fixed as part of the graph builder refactoring that happened in Terraform 0.8.

I followed the steps you described by starting with a config with one resource, applying it, and then planning the addition of a second resource. For my tests I used a `null_resource`.

After adding the second resource to config and before applying it, `terraform graph` produces the following complete graph:

![graph from `terraform graph`](https://cloud.githubusercontent.com/assets/20180/24678945/6c0fa906-1941-11e7-9a97-8eb4aced8cca.gif)

I then made a plan with `terraform plan -out=tfplan`, which produced the following output:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.foo: Refreshing state... (ID: 8865618240041627456)
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: tfplan

+ null_resource.bar


Plan: 1 to add, 0 to change, 0 to destroy.
```

Finally, I ran `terraform graph tfplan` to look at the plan graph:

![graph from `terraform graph tfplan`](https://cloud.githubusercontent.com/assets/20180/24679001/a8af9fd8-1941-11e7-89d1-fb1bece8c78c.gif)

Aside from the weirdness of exposing the `meta.count-boundary` implementation detail, this seems to now be working as expected, showing only the relationships for the nodes that will be visited when applying this plan.

Thanks again for opening this @bitglue, and sorry it took so long to follow up on this!
