### ISSUE TITLE
Document the IAM permissions necessary to access the S3 backend

### ISSUE THREAD

**Issue by kevinburkeotto** [hashicorp/terraform#16504]
I'm creating an AWS user to automatically plan/apply from a remote environment. It would be nice to know which AWS permissions are necessary to use the S3 Backend, preferably on this page: https://www.terraform.io/docs/backends/types/s3.html

**Comment by matthewfischer** [comment]
I'm in the midst of trying to guess this now and it's taking quite some time. So any info or docs on this would help.

**Comment by navaati** [comment]
For my fellow googling people, this set of permissions seems to work:

```hcl
statement {
  actions   = ["s3:*"]
  resources = ["arn:aws:s3:::<mybucket>"]
}

statement {
  actions = ["s3:GetObject", "s3:PutObject"]

  resources = [
    "arn:aws:s3:::<mybucket>/<mystatekey>",
  ]
}
```

More documentation would be welcome to further refine the `"s3:*"` rigths on the bucket though.
