### ISSUE TITLE
Terraform apply output variables [feature request]

### ISSUE THREAD

**Issue by kobymeir** [hashicorp/terraform#16515]
I would like to suggest a new feature `-output=path` to redirect to file or possibly completely hide the output variables which are printed out when `terraform apply` command has finished.

The idea behind it is that some of the data which is printed out in the output variables is *sensitive* like AWS keys, RDS password and so on, and i don't want it to be shown or written out to a file.
I'm running the terraform apply from the CI system and i don't want it to printout all the sensitive data to the build output but keep it private, on the other hand i do want to printout the changed that were made during the apply command.

If someone has an alternative approach to hiding that data, i'm happy to hear.

**Comment by apparentlymart** [comment]
Hi @kobymeir!

Terraform supports an argument `sensitive` for an output, which prevents it from being shown in the clear in the console output:

```hcl
output "example" {
  value     = "..."
  sensitive = true
}
```

This can be set optionally for each output so you can have a mixture of both sensitive and safe outputs.

I think this will achieve your goals here, though please let me know if I've missed something!

---

For running Terraform in a CI system you may find our guide [_Running Terraform in Automation_](https://www.terraform.io/guides/running-terraform-in-automation.html) useful. It's not directly about your question here but contains some other tips about suggested ways to run Terraform in non-interactive automation environments.

**Comment by kobymeir** [comment]
@apparentlymart that will work for me.
Also thanks for the automation reference link
