### ISSUE TITLE
Legacy VPC network is unsupported, but still supported by Google

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#16510]
Issues in the provider repos don't seem to get any traction, so posting a link here

https://github.com/terraform-providers/terraform-provider-google/issues/609

**Comment by apparentlymart** [comment]
Hi @JorritSalverda,

I'm sorry for your problem with the Google Provider and for the delay in response to that issue.

Unfortunately, the team that works on the Google Provider does not monitor this repository, so opening duplicate issues here will not change the level of attention that a provider issue gets. This repository is monitored only by the team working on Terraform Core.
