### ISSUE TITLE
Terraform.tfstate is not updating in AWS S3 bucket (Reopened)

### ISSUE THREAD

**Issue by joda10** [hashicorp/terraform#16538]
Hi jbardin,

Recap #16495 you closed this issue but this doesn't answer the question to the issue:

You can see the backend documentation here: https://www.terraform.io/docs/backends/index.html
And the S3 documentation with examples here: https://www.terraform.io/docs/backends/types/s3.html

So I've had a looked at the above web sites and I'm already using the example config which I used to setup the .tfstate file on the S3 bucket. Then I have used the S3 rmote state as follows:
```
data "terraform_remote_state" "trss" {
  backend = "s3"

  config {
    bucket     = "${var.s3bucket}"
    key        = "trss/terraform.tfstate"
    region     = "${var.region}"
    encrypt    = true
  }
}
```
So reading the terraform site I'm no closer to the answer, am I missing something here, please show me an example as the above site is not giving me the answer.

**Comment by Chili-Man** [comment]
@joda10  per the documentation (https://www.terraform.io/docs/backends/types/s3.html), to actually make use of the S3 bucket for remote state and not as a data source, you need to have a backend configuration like this:

```hcl
terraform {
  backend "s3" {
    bucket  = "yourBucketNameHere"
    key       = "trss/terraform.tfstate"
    region   = "us-east-1"
    encrypt  =  true
  }
}
```

In the example above, you are using that remote state as a data source, which is read only.

**Comment by joda10** [comment]
Hi Chili-Man,

So its sounds like I need to use both in order for this to work... I will test and come back you you.

**Comment by joda10** [comment]
OK I have this working now. Thanks
