### ISSUE TITLE
Windows Defender detects Trojan:Win32/Fuerboos.A!cl in 0.10.8 win32 release

### ISSUE THREAD

**Issue by codewaffle** [hashicorp/terraform#16539]
### Terraform Version
0.10.8

### Terraform Configuration Files
not applicable

### Debug Output
image: 
![Defender output](https://i.imgur.com/1YK3Gzk.png)

### Expected Behavior
Terraform works with up-to-date, default Defender settings on Windows 10

### Actual Behavior
Defender deletes file immediately

### Steps to Reproduce
Download win32 zip release of 0.10.8 while Defender is enabled

### Important Factoids
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063

md5sum of downloaded file (after disabling Defender)
c53e51d73f9ed527b52379c05263bd99 *terraform_0.10.8_windows_386.zip

**Comment by codewaffle** [comment]
I see that 0.10.8 is not marked as 'released' (or have any other information) in the GitHub releases tab - I initially followed the download link from terraform.io, which points to 0.10.8.

The 64-bit release of 0.10.8 and both releases of 0.10.7 do not trigger my AV.

**Comment by apparentlymart** [comment]
Hi @codewaffle! Sorry for this alert.

I confirmed that your md5sum result matches the verified archive of the same name from the official releases server. (I verified that I have the right archive using [the official HashiCorp signing key](https://www.hashicorp.com/security#checksum-verification)).

Unfortunately this sort of detection is not an exact science, and so false positives are possible. Indeed, I see lots of similar reports across other open source projects from some initial research, some of which are also written in Go. It's possible that one of [the changes between v0.10.7 and v0.10.8](https://github.com/hashicorp/terraform/compare/v0.10.7...v0.10.8) has inadvertently introduced a pattern that matches a signature that Windows Defender is looking for.

Unfortunately there are lots of changes in this release so it's not clear exactly what the cause might be. We will investigate further, but in the mean time I suggest using the 64-bit release in preference to the 32-bit release for Windows.

**Comment by apparentlymart** [comment]
Hello again @codewaffle,

We have been able to reproduce the same threat warning from Windows Defender Anti-virus with the previously-verified official 0.10.8 build for `windows_386`. Based on our internal investigation, we believe that this is a false positive signature match. For additional confirmation, we have submitted the file to Windows Defender Security Intelligence for analysis. I will update this issue once we receive feedback from one of their analysts.

**Comment by apparentlymart** [comment]
The team at Windows Defender Security Intelligence got back to us today and confirmed that the file in question is malware-free.

Unfortunately since our releases are immutable once published we cannot re-issue this release to attempt to address the false positive, but we will investigate ways to check for problems of this type in our release process so that we can detect such problems before a release.
