### ISSUE TITLE
`self.attr` doesn't seem to work with AWS provider

### ISSUE THREAD

**Issue by morcmarc** [hashicorp/terraform#1653]
Hey,

I've got the following in my terraform config:

```terraform
provisioner "remote-exec" {
    inline = [
      "echo ${self.private_ip} > /tmp/server-addr",
      "echo ${aws_instance.server.0.private_ip} > /tmp/consul-join-addr",
    ]
}
```

The documentation indicates that I should be able to use `self.private_ip` within a provisioner block yet I keep getting the following error:

```
Error reading provisioners for aws_instance[server]: self.private_ip: resource variables must be three parts: type.name.attr in:
```

Any ideas? Is it caused by [this](https://github.com/hashicorp/terraform/blob/master/config/interpolate.go#L166) line?

Note: haven't tried providers other than AWS

**Comment by mitchellh** [comment]
I haven't been able to reproduce this. My only theory is that you're running an old version of Terraform. Can you verify it is latest?

**Comment by morcmarc** [comment]
You were right, had a conflict with homebrew and I had been using 0.3.7. It is all working now. Thanks!
