### ISSUE TITLE
Filtering and mapping operations on lists

### ISSUE THREAD

**Issue by betabandido** [hashicorp/terraform#16550]
I want to create a module that allows users to create multiple resources based on an input configuration.  The module must create one resource for each item in the input variable, and then one resource (of another type) for each item in the input variable that has a set of arguments defined.

The following snippet tries to capture these requirements:

```hcl
variable "input" {
  type = "list"
  default = [
    { name = "item1" },
    {
      name = "item2"
      args = {
        arg1 = "i2a1"
        arg2 = "i2a2"
      }
    },
    { name = "item3" },
    {
      name = "item4"
      args = {
        arg1 = "i4a1"
        arg2 = "i4a2"
      }
    }
  ]
}

# as many resources as items exist in the list (4 in the example)
resource "null_resource" "resourceA" {
  count = "${length(var.input)}"
  trigger {
    name = "${var.input.name[count.index]}"
  }
}

# as many resources as items contain "args" (2 in the example)
resource "null_resource" "resourceB" {
  count = "<count>"
  trigger {
    name = "${var.input.name[<idx>]}"
  }
}
```

With the available string interpolation functions it does not seem possible to either compute the count field for `resourceB` or a way to index `var.input.name` using `count.index`.

Is there any way to do so?

Assuming it is not possible, I believe having methods that apply a function to each element in a list (i.e., filtering or mapping operations) might solve these types of problems.

For instance, computing how many `resourceB` are needed could be achieved as follows:

```hcl
length(compact(transform(var.input, x => contains(keys(x), "args"))))
```

This expression first applies `contains(keys(x), "args")` to each element of the list, effectively returning the following intermediate list:

```hcl
[false, true, false, true]
```

Then, assuming `compact` discards `false` elements, the proposed expression would compute the correct number of `resourceB` needed (which is 2).

Are there any plans to add these types of methods? Doing so would make Terraform much more powerful, especially when creating reusable and generic modules.

**Comment by apparentlymart** [comment]
Hi @betabandido,

A feature for this is coming in the work-in-progress configuration language revamp. The currently planned syntax is like this:

```hcl
  # NOT YET IMPLEMENTED: details may change before release
  count = length([for x in var.input: x if contains(keys(x), "args")])
```

More details on this feature are described in [its specification](https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/spec.md#for-expressions), though that spec is subject to change before release.

**Comment by betabandido** [comment]
Oh, it is great to know a revamp is on the works. Will this new revision include support for multiple levels of nesting in maps and lists (e.g., `aMap["key1"]["key2"]["key3"]`)?

**Comment by apparentlymart** [comment]
Yes, that is fixed too.

**Comment by cemo** [comment]
@apparentlymart is this considered for 0.12?

**Comment by briceburg** [comment]
I have a possible workaround that uses the `matchkeys` interpolation function. Below is an example that filters a list of maps that contain a certain value (`office`) for a certain attribute (`type`);

```
locals {
  trusted_sources = [
   {
      cidr = "255.255.255.255/32"
      desc = "test office 2"
      type = "office"
    },
    {
       cidr = "255.255.255.254/32"
      desc = "test office 1"
      type = "office"
    },
    {
      cidr = "255.255.255.253/32"
      desc = "test vpn"
      type = "vpn"
    },
  ]
}

data "null_data_source" "test" {
  count = "${length(local.trusted_sources)}"
  inputs = {
    type = "${ lookup(local.trusted_sources[count.index], "type", "") }"
    cidr = "${ lookup(local.trusted_sources[count.index], "cidr", "") }"
    desc = "${ lookup(local.trusted_sources[count.index], "desc", "") }"
  }
}

output "offices" {
  value = "${ matchkeys(data.null_data_source.test.*.outputs, data.null_data_source.test.*.outputs.type, list("office"))}"
}
```

this returns 

```
Outputs:

offices = [
    {
        cidr = 255.255.255.255/32,
        desc = test office 2,
        type = office
    },
    {
        cidr = 255.255.255.254/32,
        desc = test office 1,
        type = office
    }
]
```

I'm not sure if there's a more efficient means to do this that does not require the null data source... Ideally we could use splatting against the  `trusted_sources` local variable in matchkeys

**Comment by sobsam** [comment]
Does this code works? Its not working for me.

**Comment by sonijenk** [comment]
@briceburg :I am surprised the code works. The above code doesnt work for me.

**Comment by sonijenk** [comment]
Error reading config for null_data_source[test]: Invalid dot index found: 'var.local.trusted_sources'. Values in maps and lists can be referenced using square bracket indexing, like: 'var.mymap["key"]' or 'var.mylist[1]'. in:

${ lookup(var.local.trusted_sources[count.index], "type"," ") }

Using terraform 0.9.11

**Comment by apparentlymart** [comment]
#16597 is covering similar ground as this one. Since I already posted some more detailed comments over there, I'm going to elect to close _this_ one in this case, even though it's the older one, just to consolidate discussion into one place.

There's some additional discussion in this issue that boils down to the lack of support for complex nested data structures as variables and outputs in Terraform 0.11 and prior. That too will be addressed [in the next major release](https://www.hashicorp.com/blog/terraform-0-1-2-preview), but the article on it hasn't been posted yet at the time I write this. (It'll be the one titled "Rich types in module inputs and outputs" in the list there.)
