### ISSUE TITLE
support ARNs with names

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#16561]
I'm getting mixed behaviours from backend and from provider (in this case AWS).

apparently AWS provider does support the arn to be the alias name, but both backend and data fail if you use the name alias, and only work with the account id number.

### Terraform Version
 terraform --version
Terraform v0.10.8

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    bucket   = "statetest"
    role_arn = "arn:aws:iam::0123456789:role/OrganizationAccountAccessRole"
    acl      = "private"
    key      = "test.tfstate"
    region   = "eu-west-2"
  }
}

provider "aws" {
  region = "eu-west-2"

  assume_role {
    role_arn     = "arn:aws:iam::MY-ACCOUNT-NAME:role/OrganizationAccountAccessRole"
    session_name = "test"
  }
}

data "terraform_remote_state" "tfstate" {
  backend = "s3"

  config {
    bucket   = "statetest"
    role_arn = "arn:aws:iam::0123456789:role/OrganizationAccountAccessRole"
    key      = "test.tfstate"
    region   = "eu-west-2"
  }
}
```

### Debug Output
```
Initializing the backend...

Error configuring the backend "s3": The role "arn:aws:iam::MY-ACCOUNT-NAME:role/OrganizationAccountAccessRole" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

### Expected Behavior
Support ARN with names

### Actual Behavior
only accepts number id

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. There have been many changes to the s3 backend since this was opened. 

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
