### ISSUE TITLE
Feature Request: Terraform Enterprise 2 Provider

### ISSUE THREAD

**Issue by rorychatterton** [hashicorp/terraform#16563]
Hi there,

It would be awesome if as part of the Terraform Enterprise 2 release, there was a provider that mapped to the API that provided more than just Artifacts.

In particular, I could see Terraform being used to:

- Generate Workspaces
- Generate Team Access / Groups
- Attach Policies
- Attach Variables

It would then allow us to track configuration drift management across the entire platform, and manage accordingly.

If this is not on the road-map, can you please advise and we can start working on a community version?

**Comment by apparentlymart** [comment]
Hi @rorychatt,

This is planned, but we are intentionally waiting until after the Terraform Enterprise v2 beta period since its API is not yet fully complete or guaranteed stable.

**Comment by rorychatt** [comment]
Awesome, thanks dude

**Comment by paultyng** [comment]
This now exists: https://github.com/terraform-providers/terraform-provider-tfe
