### ISSUE TITLE
Terraform crash on S3 bucket import

### ISSUE THREAD

**Issue by nwalke** [hashicorp/terraform#16574]
### Terraform Version
0.10.8 (did the same on 0.10.7)

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket" "database_wal_segments" {
  bucket = "${var.database_wal_segments_bucket_name}"
  acl = "private"

  tags {
    Name = "${var.database_wal_segments_bucket_name}"
    terraform = "true"
  }
}
```

### Debug Output
https://gist.github.com/nwalke/1630d5cfb65d64eed4def3eaf43a8e7f

### Crash Output
Quite a lot of info in there I'd like to not share with the world.  If needed I can spend some time stripping it down.

### Expected Behavior
The bucket should have imported.

### Actual Behavior
Terraform crashed.

### Steps to Reproduce
1. `terraform import module.mymodule.aws_s3_bucket.database_wal_segments mybucket`

### Important Factoids
We do assume a role with the AWS provider.

I'll open a separate ticket to the AWS provider about why the bucket wasn't successfully imported, but figured I should file this one so that Terraform core could be updated to catch instances like this.

**Comment by apparentlymart** [comment]
Hi @nwalke! Sorry for this crash, and thanks for reporting it.

Given the location of the crash in the stack trace, this does indeed seem like an AWS provider bug. As far as I can tell the way Terraform Core handled this is as we would expect (show the panic and then shut down gracefully) so I don't think there's actually any core changes to make here and so I'm going to close this. Please let me know if there was a specific core change you had in mind when you opened this.

**Comment by nwalke** [comment]
Ah, okay.  Was unaware this is how I should expect core to behave.  Sorry for the extra noise.
