### ISSUE TITLE
 Introduce since tag for declaring feature availability in the TF documentation

### ISSUE THREAD

**Issue by przemos** [hashicorp/terraform#16578]
Hi,

it would be enormously helpful to have kind of @since tag available next to particular terraform feature in the documentation so that a potential user knows whether or not they can use it.
It can be started any time, does not require intermediate retrofitting of existing doc it seems and brings nice ROI. What do you think

**Comment by mildwonkey** [comment]
We've been working on labeling existing docs with the supported terraform version, and there's already an issue open for the larger "versioned docs" enhancement, so I am going to close this as a duplicate. Thanks!
