### ISSUE TITLE
terraform plan ignores keyboard interrupt, requires a kill -9 to exit before running the entire plan

### ISSUE THREAD

**Issue by devonbleak** [hashicorp/terraform#16571]
Expected behavior:
Sending keyboard interrupt (ctrl-c) exits a `terraform plan` fairly immediately

Actual behavior:
Sending keyboard interrupt does nothing

Probably related to the new TF_LOG environment variable instead of sending a keyboard interrupt to enable debug logs, but if I want to exit a long-running plan I have to ctrl-z to STOP the process and then kill -9 it.  I can maybe see this being desirable for `terraform apply` but for a `terraform plan` there shouldn't be any harm in being able to exit early.

**Comment by apparentlymart** [comment]
Hi @devonbleak! Sorry for this strange behavior.

You're right that in general it shouldn't be harmful to abort a plan. I suspect this is just an artifact of the fact that a lot of code is shared between the two cases.

When you interrupt a `terraform plan` run, does it produce any output? Terraform usually prints a message saying that it is working on shutting down and that you can interrupt a second time to force it, but it sounds like that's not happening as expected in your case.

**Comment by devonbleak** [comment]
Not seeing any output when I ctrl-c and it continues on its merry way refreshing all of the resources.

Tried enabling trace logs but it scrolls by too fast to capture anything - I can upload if you want them.

I did get it to bail out on the SIGINT when it got delivered before/while it was initializing the backend, but beyond that it seems to just get ignored.

**Comment by bohdanyurov-gl** [comment]
Still affects 0.12.2
