### ISSUE TITLE
Terraform reinitialization fails with a conflicting backend configuration even when backend configuration is explicitly skipped

### ISSUE THREAD

**Issue by jbolla** [hashicorp/terraform#16593]
### Terraform Version
Terraform v0.10.8

### Terraform Configuration Files
```hcl
backend-init.tf:
terraform {
  backend "http" {
    address = "some_url"
    update_method = "PUT"
  }

example.tf:
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

terraform {
  backend "http" {
    address = "some_other_url"
    update_method = "PUT"
  }
}

provider "oci" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid = "${var.user_ocid}"
  fingerprint = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region = "${var.region}"
}

resource "oci_core_virtual_network" "vcn1" {
  cidr_block = "10.0.0.0/16"
  dns_label = "vnc1"
  compartment_id = "${var.compartment_ocid}"
  display_name = "vnc1"
}

}
```

### Debug Output
Backend reinitialization required. Please run "terraform init".
Reason: Backend configuration changed for "http"
....

### Expected Behavior
Terraform initialization succeeds and ignores the new backend configuration

### Actual Behavior
Terraform initialization fails

### Steps to Reproduce
1. Supply a config with a terraform backend configured.
2. Run terraform init to configure the backend.
3. Supply a full terraform config with a different backend configuration.
4. run terraform init -backend=false

### Important Factoids
The atypical piece is the two phase init of terraform and the changed backend configuration which should be ignored due to the -backend=false flag.

**Comment by mildwonkey** [comment]
Hello! I've merged a fix for this which will be in the next release (0.12.19). Please open a new GH issue if you see any problems with it after the release. Thank you!
