### ISSUE TITLE
New way of overriding provider does not seem to work (0.11-beta1)

### ISSUE THREAD

**Issue by modax** [hashicorp/terraform#16607]
Hi,

I'm following instructions at https://github.com/hashicorp/terraform/blob/master/website/upgrade-guides/0-11.html.markdown#interactions-between-providers-and-modules but provider override in the module does not seem to work.

By the way, you have a syntax errors (in `providers` map) in the example on that page.

### Terraform Version

Terraform v0.11.0
+ provider.aws v1.2.0

0.11-beta1

### Terraform Configuration Files

main.tf

```hcl
provider "aws" {
  region = "eu-west-1"
}

provider "aws" {
  alias = "central"
  region = "eu-central-1"
}

module "central" {
  source = "./child"
  providers = {
    "aws" = "aws.central"
  }
}
```
child/main.tf
```hcl
resource "aws_cloudwatch_log_group" "foo" {
  name = "foo"
}
```

### Expected Behavior

CloudWatch Logs group is created in `eu-central-1` region.

### Actual Behavior

Logs groups gets created in eu-west-1 region.

`terraform providers`
```
.
├── provider.aws
├── provider.aws.central
└── module.central
    └── provider.aws (inherited)
```

I don't know what `terraform providers` should be there, but it feels wrong: `(inherited)` part.

### Steps to Reproduce

```
terraform init
terraform apply
```

If you cannot reproduce, I can provide more info. Just ask

**Comment by jbardin** [comment]
Hi @modax: thanks for testing things out!

Currently, in order for a provider to be passed in via the `providers` map, the module needs to declare that provider as a placeholder. So adding `provider "aws" {}` to the module should suffice. 

We're in the process of clarifying the documentation, and possibly updating the behavior for the next incremental release.

**Comment by modax** [comment]
@jbardin: yes, I can confirm that it helps.

```

 But then provider never inherits

**Comment by jbardin** [comment]
Thanks for the update. 

Yes, we're leaning toward being more explicit in the configuration, so a module would sort of require providers that it wants configuration for, similar to a variable declaration. This way you can tell more easily what providers your module resources will use, rather than trying to deduce the provider from the inheritance model.

**Comment by jbardin** [comment]
The updated the example in the guide. We'll follow up with more documentation for the final release.

Thanks!
