### ISSUE TITLE
module outputs available despite depends_on a failed resource

### ISSUE THREAD

**Issue by gberche-orange** [hashicorp/terraform#16609]
I'm trying to use output variables with ``depends_on`` as a mean to externally assert the proper creation of resources, i.e. I assume that if an output dependent onto a resource is available (in the tfstate), then the resource was properly created. This is surprisingly not the case.

https://www.terraform.io/docs/configuration/outputs.html mentions

> depends_on (list of strings) - Explicit dependencies that this output has. These dependencies will be created before this output value is processed.

### Terraform Version

```
$ terraform -v
Terraform v0.10.9-dev
+ provider.local v1.0.0

```
### Terraform Configuration Files
```json
{
  "module": {
    "my-module": {
      "source": "modules/mymodule"
    }
  },
  "output": {
    "3456": {
      "value": "${module.my-module.status}"
    }
  }
}
```

modules/my-module/afile.tf:
```hcl

resource "local_file" "foo" {
  content     = "foo!"
  filename = "/tmp/non-writeable/file"
}

output "status" {
  value = "success"
  depends_on= ["local_file.foo"]
}
```

### Expected Behavior

Expected outputs to be omitted/missing when depending (through `depends_on`) on a failed resource

### Actual Behavior

Output present when depending (through `depends_on`) on a failed resource

### Steps to Reproduce

```sh
mkdir /tmp/non-writeable/
chmod -w /tmp/non-writeable/
```

```
$ terraform init
$ terraform apply
[...]
1 error(s) occurred:
* module.my-module.local_file.foo: 1 error(s) occurred:
* local_file.foo: open /tmp/non-writeable/file: permission denied
```

```
$ cat terraform.tfstate 
[...]
           "outputs": {
                "3456": {
                    "sensitive": false,
                    "type": "string",
                    "value": "success"
                }
            },
```

### workaround

have the output actually interpolate one of the field from the expected dependent resource: in this case outputs are missing if the interpolated resource is missing

```hcl
output "status" {
  value = "${local_file.foo.filename}}"
  #depends_on= ["local_file.foo"] #no effect
}
```
This however prevents use of the convience list of dependencies in ``depends_on``

**Comment by jbardin** [comment]
Hi @gberche-orange,

Unfortunately, this isn't really something that `depends_on` can do. All the `depends_on` field does in is assert that the dependencies are evaluated first. It doesn't provide any sort of conditional evaluation.

I'm not quite sure I understand what you're intending to do with the output, but it's possible that you're looking for a feature like null_resource triggers:  https://www.terraform.io/docs/provisioners/null_resource.html

**Comment by gberche-orange** [comment]
thanks @jbardin for your prompt response and your clarifying help. 

> I'm not quite sure I understand what you're intending to do with the output, but it's possible that you're looking for a feature like null_resource triggers: https://www.terraform.io/docs/provisioners/null_resource.html

I was trying to see if tf state outputs could be used as a contract for communicating success/failure of resources creation. 

Some more background: I'm trying to invoke terraform from a CI/CD pipeline, there terraform specs include multiple modules invocations. My CI/CD glue code hasn't yet access to the terraform command output and status code, and is instead merely able to observe the resulting tfstate. I was trying to avoid parsing the whole TF state file to assert proper resource execution, and merely rely on dependent outputs presence to infer resources creation status.

Thanks for pointing me to the provisionners and null_resource direction, might indeed be a way forward for my use-case.

**Comment by gberche-orange** [comment]
Closing. Thanks for the support. May be documentation could be refined as a follow up if more people get confused like I did.
