### ISSUE TITLE
If process running terraform crashes then state file doesn't have the correct info.

### ISSUE THREAD

**Issue by ashishth09** [hashicorp/terraform#16615]
Sometimes when we run  terraform in a container and it crashes (may be power went off or such things) the state file is not udpated and we loose the info as to what was ordered. If the persistence could be run in some separate thread at regular interval then it could minimize this. 
At the minimum if we could persist the id of the resource when it gets created the first time in `create` operation then it would help a lot.
There is definitely more to it but I just wanted to open up this for discussion. Are there any best practices folks follow to overcome this? and so on.

**Comment by jbardin** [comment]
Hi @ashishth09,

Thanks for opening the issue. We're tracking this already at #14487
