### ISSUE TITLE
HTTP Basic Auth for Terraform remote config with Consul

### ISSUE THREAD

**Issue by salizzar** [hashicorp/terraform#1663]
Hi guys,

Terraform is able to use HTTP Basic Auth to store state file with Consul on `terraform remote config`? I not found any support while reading the source code.

Thank you.

**Comment by phinze** [comment]
Looks like this isn't supported today, but the Go client supports it so it'd be pretty simple to add. Tagged!

**Comment by zonzamas** [comment]
:+1:  to this enhancement!!

**Comment by mrcrilly** [comment]
How we get this on the HTTP remote configuration too? That would be very helpful for me.
