### ISSUE TITLE
Specify custom providers

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#16636]
Hi,

I am planning to upgrade to Terraform `0.10.8` and with all the provider split up and stuff, I was wondering how to configure custom providers.

For example: I have made some changes to `aws` provider very specific to our organization. Is there a way to point to this specific version.

**Comment by apparentlymart** [comment]
Hi @Puneeth-n!

Currently the auto-install mechanism only supports the plugins on `releases.hashicorp.com`, but Terraform does still check for already-existing plugins installed locally and will use any it finds.

In your existing setup you are presumably installing a `terraform-provider-aws` binary on your system somewhere. You should be able to do the same in 0.10.8 too. We usually recommend putting it in the same directory as the `terraform` binary itself.

If you wish, you can name the file using the new version-aware naming scheme `terraform-provider-aws_v1.2.0`, which has two advantages:

* Version constraints in the configuration will work as they would for the "official" binary. (You may wish to add a dash-separate suffix to distinguish your local versions from the upstream versions, to make it explicit that the local modifications are required.)
* You can have multiple versions installed at once, by placing them side-by-side in the same directory. The version constraints mechanism will then select the newest one that matches, or attempt to download from `releases.hashicorp.com` if no local plugin matches.

We are planning to support installation of plugins from other sources in a future version.

**Comment by Puneeth-n** [comment]
@apparentlymart Thanks again for the detailed info :) So I am planning to upgrade from `0.9.11` to `0.10.8` Currently, we have our own binary of `terraform 0.9.11` which has all the plugin built in. so I guess before terraforming, I'll need to as a prerequisite, download our custom aws provider implementation to the plugin dir. Thanks a lot again! Cheers!

**Comment by apparentlymart** [comment]
Yes, the _internal plugins_ mechanism is no longer supported for providers from 0.10.0, because it's not compatible with the module versioning system. It will be necessary to build each provider separately, as you said.

I'm going to close this, because it sounds like you have what you need here. Good luck with the upgrade! :grinning:
