### ISSUE TITLE
Terraform crash w/ invalid commandline args

### ISSUE THREAD

**Issue by kiesel** [hashicorp/terraform#16642]
Hi there,

### Terraform Version
    $ terraform --version
    Terraform v0.10.8

### Terraform Configuration Files
Crash occurs independent from configuration.

### Crash Output
Invoking terraform via:

    $ terraform "state show"

leads to:

https://gist.github.com/kiesel/a4adf4490ce88f492444116b181fd47c

### Expected Behavior
Terraform should've said one of:

* unknown command
* missing argument

### Actual Behavior
Crash, see log.

### Steps to Reproduce
1. `terraform "state show"`

The crash does not occur, when invoking via

    $ terraform state

or

    $ terraform invalidcommand

**Comment by minamijoyo** [comment]
@kiesel Thank you for reporting issue. It seems like a bug in the `mitchellh/cli` used by Terraform. I've opened an issue as https://github.com/mitchellh/cli/issues/68 .

**Comment by mitchellh** [comment]
This is fixed up stream. @jbardin please update the `mitchellh/cli` vendor and you should be good to go and then can close thise.

**Comment by kiesel** [comment]
@minamijoyo thank you for your time to find a minimal reproduce case for this issue.

I feel this was extraordinary feedback / bug handling (even though the severity is actually quite low in this case:)). Thank you!
