### ISSUE TITLE
use self variables in module definition

### ISSUE THREAD

**Issue by moosilauke18** [hashicorp/terraform#1667]
Basically I am using modules to define a cluster with each in a different availability zone.  One of the variables I define is the availability_zones that is used in the module.  I also use the variable subnet_id which I have set per availability zone.  The problem is, it I need to send the correct subnet_id based on what availability_zone set is.  How can I do that.  

Here's the module:

```
module "us-east-1c" {
    source = "./cluster"
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
    coreos = "${lookup(var.coreos, var.region)}"
   
    region = "us-east-1"
    vpc_id = "${lookup(var.vpc_id, var.region)}"

    # Here lies the problem
    subnet_id = "${lookup(var.subnet_id, var.availability_zones)}"
    availability_zones = "us-east-1c"
}
```

I can get past this, by using `subnet_id = "${var.subnet_id.us-east-1c}"` but I'd prefer if I only had to change the variables in one location.  Is this possible currently?  I was thinking of doing something like self.availability_zones.

Thanks!!

**Comment by phinze** [comment]
Off the top of my head I can't think of a way to do this today - tagged as an enhancement for now and if I can think of a trick that makes this nicer given the current feature set I'll follow up!

**Comment by mitchellh** [comment]
There have been other issues about this. Its unlikely we'll ever be able to really do this given the current architecture. It'd be a nice to have but I don't see a way to get it done in any near or mid-term release (3, 6, 9 months). I'm going to close at "wontfix" for now. Maybe we can swing back one day.

**Comment by emyller** [comment]
@mitchellh Did anything change that would allow us to have this feature nowadays?

**Comment by NorseGaud** [comment]
Any updates on this feature? This is crucial for dryness of code.,
