### ISSUE TITLE
Pin specific version of Terraform

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#16679]
Hello. I'd like to propose a new feature to pin a specific version of Terraform in the config:

````
terraform {
    version: "0.11.0"
}
````

If this attribute is set, upon running any commands, Terraform checks the current version against this value. If the values don't match, an error is shown.

**Comment by nbering** [comment]
This feature already exists. Here's the documentation for it:

https://www.terraform.io/docs/configuration/terraform.html

**Comment by nodesocket** [comment]
Oops sorry. Thanks for the link.

**Comment by nbering** [comment]
No problem. Consider it a compliment that the team thought your idea was so great that they built it before you suggested it. 😃
