### ISSUE TITLE
failed: lookup: lookup() may only be used with flat maps, this map contains elements of type map

### ISSUE THREAD

**Issue by nitinnagpalbe** [hashicorp/terraform#16674]
Hi there,

### Terraform Version
Terraform v0.10.8

### Terraform Configuration Files
```hcl
ami.tf

variable "virtualization_type" {
  default = "hvm"
}

data "aws_ami" "base_ami" {
  most_recent      = true
  filter {
    name   = "name"
    values = ["*xyz*"]
  }
  filter {
    name   = "architecture"
    values = ["x86_64"]
  }
  filter {
   name = "virtualization-type"
   values = ["${var.virtualization_type}"]
  }
}

output "base_ami_id" { value = "${data.aws_ami.base_ami.image_id}" }
output "ebs_snapshot_id_app" { value = "${lookup(lookup(data.aws_ami.base_ami.block_device_mappings[0], "ebs"), "snapshot_id")}" }
output "ebs_snapshot_id_log" { value = "${lookup(lookup(data.aws_ami.base_ami.block_device_mappings[1], "ebs"), "snapshot_id")}" }

---------
Sample output of data.aws_ami.base_ami.block_device_mappings

ebs_device_mapping = [
    {
        device_name = /dev/sdb,
        ebs = map[volume_type:gp2 iops:0 volume_size:10 snapshot_id:snap-044f24a76c1d3326b encrypted:0 delete_on_termination:0],
        no_device = ,
        virtual_name =
    },
    {
        device_name = /dev/sdc,
        ebs = map[volume_size:10 volume_type:gp2 iops:0 snapshot_id:snap-0cb650f9d8d0e8a13 encrypted:0 delete_on_termination:0],
        no_device = ,
        virtual_name =
    },
    {
        device_name = /dev/xvda,
        ebs = map[delete_on_termination:1 snapshot_id:snap-01e7880be65e3b75f encrypted:0 volume_size:40 volume_type:standard iops:0],
        no_device = ,
        virtual_name =
    }
]
```

### Debug Output
2017/11/16 16:07:19 [WARN] Output interpolation "ebs_snapshot_id_app" failed: At column 3, line 1: lookup: argument 1 should be type map, got type string in:

${lookup(lookup(data.aws_ami.base_ami_vols.block_device_mappings[0], "ebs"), "snapshot_id")}
2017/11/16 16:07:19 [TRACE] root: eval: terraform.EvalNoop
2017/11/16 16:07:19 [TRACE] [walkApply] Exiting eval tree: output.ebs_snapshot_id_app
2017/11/16 16:07:19 [DEBUG] Interpolating computed list element attribute block_device_mappings (3)
2017/11/16 16:07:19 [WARN] Output interpolation "ebs_snapshot_id_log" failed: At column 3, line 1: lookup: argument 1 should be type map, got type string in:

${lookup(lookup(data.aws_ami.base_ami_vols.block_device_mappings[0], "ebs"), "snapshot_id")}
2017/11/16 16:07:19 [TRACE] root: eval: terraform.EvalNoop
2017/11/16 16:07:19 [WARN] Output interpolation "ebs_device_mapping" failed: lookup: lookup() may only be used with flat maps, this map contains elements of type map in:

${lookup(data.aws_ami.base_ami_vols.block_device_mappings[0],"ebs")}

### Expected Behavior
It should output the snapshot_id

### Actual Behavior
It fails silently without printing the snapshot_id

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Important Factoids
The AMI have attached ebs block devices other than root device

How can this value be accessed if this functionality is not yet supported, Is there any workaround?

**Comment by apparentlymart** [comment]
Hi @nitinnagpalbe! Sorry for the confusing behavior here.

In the current generation of the configuration language, the way to write what you wanted to express here is as follows:

```hcl
output "ebs_snapshot_id_app" {
  value = "${data.aws_ami.base_ami.block_device_mappings.0.ebs.snapshot_id}"
}
output "ebs_snapshot_id_log" {
  value = "${data.aws_ami.base_ami.block_device_mappings.1.ebs.snapshot_id}"
}
```

In general Terraform's support for complex structures like this has some limitations today. We are currently working on integrating a revamped configuration language parser that should address many of these limitations. Once that's integrated, the syntax for this will be more intuitive:

```hcl
# NOT YET IMPLEMENTED - details may change before release

output "ebs_snapshot_id_app" {
  value = data.aws_ami.base_ami.block_device_mappings[0].ebs.snapshot_id
}
output "ebs_snapshot_id_log" {
  value = data.aws_ami.base_ami.block_device_mappings[1].ebs.snapshot_id
}
```

**Comment by nitinnagpalbe** [comment]
Hi @apparentlymart! Thanks for your response.

I had tried the method you mentioned above but that also prints the count of block_device_mappings and not the expected snapshot_id. Below are two examples

```
# For AMI with root vol only
output "base_ami_id" { value = "${data.aws_ami.base_ami.image_id}" }
output "block_device_mappings" {
  value = "${data.aws_ami.base_ami.block_device_mappings}"
}

output "ebs_snapshot_id_app" {
  value = "${data.aws_ami.base_ami.block_device_mappings.0.ebs.snapshot_id}"
}
output "ebs_snapshot_id_log" {
  value = "${data.aws_ami.base_ami.block_device_mappings.1.ebs.snapshot_id}"
}
# OUTPUT
base_ami_id = ami-981f94e2
block_device_mappings = [
    {
        device_name = /dev/xvda,
        ebs = map[volume_type:standard delete_on_termination:1 encrypted:0 volume_size:40 snapshot_id:snap-08aa39503e87a61b9 iops:0],
        no_device = ,
        virtual_name =
    }
]
ebs_snapshot_id_app = 1
ebs_snapshot_id_log = 1
```

```
# For AMI with root + 2 ebs vols
output "base_ami_id_test" { value = "${data.aws_ami.base_ami_new.image_id}" }
output "block_device_mappings" {
  value = "${data.aws_ami.base_ami_new.block_device_mappings}"
}
output "ebs_snapshot_id_app" {
  value = "${data.aws_ami.base_ami_new.block_device_mappings.0.ebs.snapshot_id}"
}
output "ebs_snapshot_id_log" {
  value = "${data.aws_ami.base_ami_new.block_device_mappings.1.ebs.snapshot_id}"
}
output "ebs_snapshot_id_log_device_name" {
  value = "${data.aws_ami.base_ami_new.block_device_mappings.1.ebs.device_name}"
}
# OUTPUT
base_ami_id_test = ami-1af2ca7a
block_device_mappings = [
    {
        device_name = /dev/xvda,
        ebs = map[volume_size:10 delete_on_termination:1 encrypted:0 iops:0 volume_type:standard snapshot_id:snap-083b3300a58b18284],
        no_device = ,
        virtual_name =
    },
    {
        device_name = /dev/sdb,
        ebs = map[encrypted:0 iops:0 volume_size:30 snapshot_id:snap-0ffda7a8670a5673e volume_type:standard delete_on_termination:1],
        no_device = ,
        virtual_name =
    },
    {
        device_name = /dev/sdf,
        ebs = map[iops:0 encrypted:0 volume_size:50 snapshot_id:snap-029fee7930ab4609f delete_on_termination:1 volume_type:standard],
        no_device = ,
        virtual_name =
    }
]
ebs_snapshot_id_app = 3
ebs_snapshot_id_log = 3
ebs_snapshot_id_log_device_name = 3
```

**Comment by noamcore** [comment]
So until now we can't do something like that `digitalocean_kubernetes_cluster.main.node_pool.*.["nodes"]`, right?

**Comment by mildwonkey** [comment]
Terraform 0.12 is released, and includes enhancements that resolve this issue! 

In this specific case, `block_device_mappings` is a set, not a list, so martin's suggestion needs a little help to work. You can coerce terraform to treat it like a list with the `tolist` function:

```hcl
output "ebs_snapshot_id_app" {
  value = tolist(data.aws_ami.base_ami.block_device_mappings)[0].ebs.snapshot_id
}
```

If you run into any issues using terraform 0.12, please open a new issue. Thanks!
