### ISSUE TITLE
It'd better that the ternary operator doesn't evaluate the expression in impossible part

### ISSUE THREAD

**Issue by ckyoog** [hashicorp/terraform#16680]
I've been tortured by this issue for months, although I workaround each one eventually. I think it'd better be improved from terraform side, then I won't need to do extra workaround and write those ugly and unreadable code any more.

Consider such snippet of code
```
variable "a_list" {
  type = "list"
  default = []
}
data "template_file" "test" {
  template = "$${text}"
  vars {
    text = "${length(var.a_list) > 0 ? element(var.a_list, 0) : ""}"
  }
}
```
Terraform will fail on this code because `element()` doesn't like empty list. But you know what, that is why I didn't write it like `text = ${element(var.a_list, 0)}"` in the first place. I do understand that `element()` will go wrong on empty list, so I add the condition just to wish it won't be called when list is empty, but obviously I was wrong, it will be evaluated always.

So I think the way ternary operator works is not good enough. When list `a_list` is empty, the ternary operation will never run into the first part, it will return `""`. That means It is unnecessary to bother to evaluate the first part which is already determined to be impossible.

<br/>

Another example (pseudo code)
```
list = ["pear", "orange", "peach", "banana"]
text = "${contains(list, "apple") ? index(list, "apple") : 0)}"
```
Likewise, I know `index()` will go wrong if the element doesn't exist in the list, so that's why I didn't write `text = "${index(list, "apple")}"` in the first place. But same, even I put the `index()` in the ternary operation, it will be evaluated anyway regardless of the condition.

### Terraform Version
0.9.x - 0.10.x, they all have the issue. I guess <0.9 also have

**Comment by apparentlymart** [comment]
Hi @ckyoog! Sorry for this unfortunate behavior.

I think you are describing here the same issue covered by #15605, so I'm going to close this to consolidate the discussion over there. Work to fix this is in progress and will come in a future release.

**Comment by ckyoog** [comment]
No @apparentlymart , no need to be sorry, honestly. Terraform is awesome. You guys are great and brilliant.

Maybe my opening looks a little inpatient, but I am not complaining, just want to show some emergency so that you guys will take it seriously ;)  In fact,  I want to make some contributions, but the only thing I can do is to use it and find issues. Hope it gets better and better.
