### ISSUE TITLE
Q: does Terraform intend to use `id` or `object_type_id` for a resource? 

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#16703]
I am finding this to be confusing: does Terraform intend to use `id` or `object_type_id` for a resource?

For example, `aws_internet_gateway.main.id` - https://www.terraform.io/docs/providers/aws/r/internet_gateway.html - versus `route_table.main.route_table_id` - https://www.terraform.io/docs/providers/aws/r/route.html

Why does Terraform choose one over the other, internally? Are there reasons to use both, or should resource (and module) authors settle on one to keep consistency?

**Comment by awilkins** [comment]
`route_table_id` there is an input - the ID of the route table to apply the route to. Routes themselves have no ID. The resource outputs the attribute but it doesn't belong to that resource.

AFAICT all the resources that emit an ID that is their own call it `id`.

**Comment by ketzacoatl** [comment]
Ah yes, that is a great point. I see my confusion now.. https://www.terraform.io/docs/providers/aws/r/route_table.html uses `id`, and `aws_route` is (technically speaking) referring to another resource when using `route_table_id`. Thanks!
