### ISSUE TITLE
Invalid link in Resources documentation

### ISSUE THREAD

**Issue by alexaandru** [hashicorp/terraform#16719]
On https://www.terraform.io/docs/configuration/resources.html under Meta-Parameters - provider section there is a link to https://www.terraform.io/docs/configuration/resources.html#multi-provider-instances but that target does not exist. Another target however with the same name exists: https://www.terraform.io/docs/configuration/resources.html#multiple-provider-instances - notice the `multi` vs `multiple` typo in the link.

Cheers!

**Comment by erran** [comment]
Looks like this can be closed after merging https://github.com/hashicorp/terraform/pull/16720.

**Comment by alexaandru** [comment]
Indeed, thank you :)
