### ISSUE TITLE
Differing terraform plans

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/terraform#16716]
Hi guys,

I have come across an issue today whereby when I run `terraform plan` from my local machine, Terraform does not predict any change to the infrastructure (this is the expected state). But when I run the same from a TeamCity build agent it does predict many changes.

The state file is being stored in S3. The only differences I can see are the `serial` and `lineage` parameters in my local `./.terraform/terraform.tfstate` and TeamCity agent's `./.terraform/terraform.tfstate` files. Terraform has the same version on both machines.

What am I missing?

Thank you.

### Terraform Version
```Terraform v0.10.8```

### Expected Behavior
Same `terraform plan` output on both machines: my local machine and a TeamCity build agent.

### Actual Behavior
Unexpected changes are pulled by Terraform when ran from the TeamCity build agent.

### Steps to Reproduce
Not sure.

**Comment by jbardin** [comment]
Hi @walterdolce,

The `.terraform/terraform.tfstate` file has nothing to so with the state, and hopefully we can extract that config from a "state" data structure in a future release.

Can you show an example of the diff you're getting in TC? 
Do you have any resources that depends on something local, like config files, or maybe even the time?

**Comment by walterdolce** [comment]
Hey @jbardin , thank you for coming back to me on this so quickly!

Nothing depends on something local or on the time. The diff Terraform detects in the TC instance is something like the following:
```
-/+ aws_instance.ec2_cron_runner (new resource required)
      id:                                        "<current-instance-id>" => <computed> (forces new resource)
      # data data data..
      root_block_device.0.volume_type:           "standard" => <computed> (forces new resource)
```

Now, if you're wondering what goes into the root block device volume type variable, it's just an empty value defined in a map:
```
variable "ec2_instances" {
  type = "map"
  default = {
    instance_type_cron_runner = "t2.micro"
    instance_type_cron_runner_volume_type = ""
    instance_type_cron_runner_volume_size = "8"
  }
}
```

This has always been empty. But the question remains as to why on my local machine Terraform doesn't detect changes (which is correct..).

There are no config files. Everything that Terraform and the infrastructure in question needs is in the repository.

**Comment by walterdolce** [comment]
@jbardin FYI - my local machine is a macOS. The TC agent is running on a Debian box.

**Comment by walterdolce** [comment]
@jbardin further update:

Please see the Terraform provider versions below.

From my machine:
```
ls .terraform/plugins/darwin_amd64/

lock.json                             
terraform-provider-aws_v0.1.3_x4      
terraform-provider-template_v0.1.1_x4
```

From the TC agent server (Debian box):
```
ls .terraform/plugins/linux_amd64

lock.json  
terraform-provider-aws_v1.3.0_x4  
terraform-provider-template_v1.0.0_x4
```

**Comment by walterdolce** [comment]
@jbardin looks like the culprit was in the different versions of providers in the machines. By aligning the provider versions in the TC agent stopped the issue (detecting an infrastructure change) from happening.

Thanks!
