### ISSUE TITLE
Terraform can't find iam module from registry after version update

### ISSUE THREAD

**Issue by ReallSlimmShady** [hashicorp/terraform#16717]
I updated the terraform version to 0.11.0 and terraform can't find iam lambda module from the registry.

`Error loading modules: module "registry.terraform.io/terraform/iam/lambda" not found`

### Terraform Version
0.11.0

### Debug Output
2017/11/20 10:42:32 [DEBUG] matched "terraform/iam/lambda" version  for 
2017/11/20 10:42:32 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2017/11/20 10:42:33 [DEBUG] fetching module versions from "https://registry.terraform.io/v1/modules/terraform/iam/lambda/versions"
2017/11/20 10:42:33 [DEBUG] plugin: waiting for all plugin processes to complete...
Error loading modules: module "registry.terraform.io/terraform/iam/lambda" not found

### Steps to Reproduce
1. `terraform init`

Note that I reverted to an older version and it works (0.10.7). I'm not sure what's happening.

**Comment by jbardin** [comment]
Hi @ReallSlimmShady,

There is no "terraform/iam/lambda" module. 
Is this a module referenced from another module in the registry, or is it something you created locally?

**Comment by ReallSlimmShady** [comment]
It's referencing a module in the registry. Specifically, the `iam/lambda` module

**Comment by jbardin** [comment]
@ReallSlimmShady,

Sorry, I'm not sure what module you're referencing. Can you provide a link?

**Comment by ReallSlimmShady** [comment]
Sorry it seems it's mistaking my local module and trying to look for it in the registry..

**Comment by ReallSlimmShady** [comment]
I have a module in the folder `terraform/iam/lambda` and i am using it in the main.tf life so: 

```
module "iam_lambda" {
  source = "terraform/iam/lambda"

  aws_resource_prefix = "${var.aws_resource_prefix}"
}
```

And i am getting the following error:

```
- module.iam_lambda
2017/11/20 13:29:54 [TRACE] "terraform/iam/lambda" is a registry module
2017/11/20 13:29:54 [INFO] no matching version for "terraform/iam/lambda"<>, no versions found

```

it thinks it's a registry module..

**Comment by jbardin** [comment]
Relative paths need to start with `./` or `../` to indicate that they are local paths.
See this section in the upgrade guide: https://www.terraform.io/upgrade-guides/0-11.html#relative-paths-in-module-source

**Comment by ReallSlimmShady** [comment]
Ah. Thanks!
