### ISSUE TITLE
Upgrade to 0.11.0 broke our "version" variables passed into modules

### ISSUE THREAD

**Issue by jwinter** [hashicorp/terraform#16711]
We specified a `version` variable into modules that we use for tagging the application version, not for the new version module constraint (https://www.terraform.io/docs/modules/usage.html#module-versions). When running terraform init after upgrading to 0.11.0 we get the following error:
```
$ terraform init
Initializing modules...
- module.dds-staging
- module.dds-staging.data-service-asg

Initializing the backend...
Error getting plugins: module root: module dds-staging: required variable "version" not set
  module dds-staging.root: module data-service-asg: required variable "version" not set
```
I believe this is due to a collision between using a version variable and the new version module constraint. https://www.terraform.io/docs/modules/usage.html#module-versions

**Comment by jbardin** [comment]
Hi @jwinter,

Sorry this collision caused an issue for you. This change is noted under `BACKWARDS INCOMPATIBILITIES` in the 0.11 changelog.
