### ISSUE TITLE
terraform taint asks for backend reinitialization

### ISSUE THREAD

**Issue by seyeda** [hashicorp/terraform#16723]
I upgraded to version 0.11.0 and now terraform taint command does not work.
The remote state is configured successfully in s3:
```
terraform init -input=false \
    -backend-config=...
    -get=true \
    ./modules
```
Then I need to taint a resources in a nested module using:
`terraform taint -module=moduel1.ecs aws_ecs_service.resource1`
But this gives me an error:
> Backend reinitialization required. Please run "terraform init".
> Reason: Unsetting the previously set backend "s3"
> 
> The "backend" is the interface that Terraform uses to store state,
> perform operations, etc. If this message is showing up, it means that the
> Terraform configuration you're using is using a custom configuration for
> the Terraform backend.
> 
> Changes to backend configurations require reinitialization. This allows
> Terraform to setup the new configuration, copy existing state, etc. This is
> only done during "terraform init". Please run that command now then try again.
> 
> If the change reason above is incorrect, please verify your configuration
> hasn't changed and try again. At this point, no changes to your existing
> Failed to load backend: Initialization required. Please see the error message above.

It used to work properly in .9

**Comment by apparentlymart** [comment]
Hi @seyeda! Sorry this isn't working as expected.

Could you possibly paste the contents of the `.terraform/terraform.tfstate` file here, as they exist just before running `terraform taint ...`? In spite of the name of this file it is no longer the actual state file and is rather just Terraform's record of where the state file is, so it will contain some S3-specific settings that you should redact; the main thing I want to see is whether the backend configuration is present in there at all, though it'd be also useful if you can check if all of the settings you passed with `-backend-config` are present and have the correct values in there.

If you are able to share it, it would be most useful to see the log resulting from running that taint command with the `TF_LOG=trace` environment variable set. Please create a [gist](https://gist.github.com/) of it and link to it here, if you're able. This log contains some diagnostics about the initialization of the backend that may help to understand why Terraform is not finding the backend configuration.

**Comment by seyeda** [comment]
thanks @apparentlymart for your reply. Here is what i see in `.terraform/terraform.tfstate`:
```
{
    "version": 3,
    "serial": 1,
    "lineage": "...",
    "backend": {
        "type": "s3",
        "config": {
            "bucket": "my_bucket_name",
            "key": "path_to_state_file",
            "profile": "my_aws_profile",
            "region": "us-west-2"
        },
        "hash": 9345827190033900985
    },
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```
I suppose this means backend is correctly configured.
When I run terraform with TF_LOG=trace, it shows these messages:

> 2017/11/21 04:21:49 [DEBUG] command: loading backend config file: /root
> 2017/11/21 04:21:49 [INFO] command: backend config not found, returning nil: /root
> 2017/11/21 04:21:49 [INFO] command: no config, returning nil

so apparently, it cannot find the backend config but I don't know why.

**Comment by jbardin** [comment]
@seyeda,

You are running `init` on directory other than the working directory with the `./modules` argument, however you're running `taint` using the config in your current directory. You either need to work within your config directory (which would be preferred), or add a matching backend config to your working directory.

We are tracking this issue here: https://github.com/hashicorp/terraform/issues/15447

**Comment by seyeda** [comment]
thank you @jbardin . I fixed it by running `init` in `./modules` but surprisingly, this was working fine in 0.9. +1 to adding `path` input to `taint`
