### ISSUE TITLE
Terraform crashes while using custom written provider

### ISSUE THREAD

**Issue by rakesh568** [hashicorp/terraform#16725]
### Terraform Version

```
Terraform v0.11.0
+ provider.aviatrix (unversioned)

```

#### .terraformrc file
```hcl
providers {
  "aviatrix" = "$GOPATH/bin/terraform-provider-aviatrix"
}

```
A sample terraform configuration file can be found with terraform provider linked in ``Steps to Reproduce`` section.

### Crash Output

https://gist.github.com/rakesh568/7776d2d8b1a6f1c1d11e1f726cba0157

### Steps to Reproduce

1. Install aviatrix terraform provider. [Link](https://github.com/AviatrixSystems/terraform-provider-aviatrix)
1. `terraform init`
2. `terraform apply`
3. Terraform crashes with crash.log generated in current directory.

### Important Factoids

This was working with an older terraform version(don't remember exact version), but it started crashing after upgrading to latest version.

Also after upgrading terraform, it is taking around a minute(before it used to take few seconds) to run ``terraform plan`` and ``terraform apply``.

**Comment by jbardin** [comment]
Hi @rakesh568,

This is a crash in the provider itself, and not something we can fix from within terraform.

**Comment by rakesh568** [comment]
It doesn't look it's because of my changes.
I got this Terraform crash output on trying ``teraform apply``. I have already added crash.log as gist [here](https://gist.github.com/rakesh568/7776d2d8b1a6f1c1d11e1f726cba0157).

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
