### ISSUE TITLE
Output variables populated from `data.external` data sources are never populated causing errors

### ISSUE THREAD

**Issue by JBirdVegas** [hashicorp/terraform#16728]
After upgrading to 0.11 we started having deployments fail.

When the result of an external data source is used to populate an output variable terraform fails.

### Terraform Version
```$ terraform --version
Terraform v0.11.0
+ provider.external v1.0.0
+ provider.null v1.0.0
```

### Terraform Configuration Files
Simplest example I could come up with to illustrate the problem.  Note if you move the python code to it's own file the result will be the same.  The external datasource will not be executed but the output's depending on the datasource will fail validation.
https://gist.github.com/JBirdVegas/9e508d2ce4266fd7c242c3f080f5368f

### Debug Output
https://gist.github.com/JBirdVegas/97d8fc110a353c6db6b199eae655714b

### Expected Behavior
Output variable should be populated after external datasource can be evaluated

### Actual Behavior
Terraform appears to attempt to validate the output variable before evaluating the external datasource that should be a parent module

### Steps to Reproduce
```
$ terraform init
$ terraform plan
```

### Important Factoids
Seems like this kinda thing should have first turned into a warning before terraform started breaking deployments with no way of going back to a previously working version of terraform.

Edit:
Reported remedies do not work for this provider.  Example adding the following the the script provided

```
output "result_of_python_test" {
  value = "${join("", data.external.test_python.result.*.status)}"
}
output "result_of_python_test_2" {
  value = "${join("", data.external.test_python.*.result.*.status)}"
}
output "result_of_python_test_3" {
  value = "${join("", data.external.test_python.*.result.status)}"
}
```

will return these errors:

```
Error: Error running plan: 3 error(s) occurred:

* output.result_of_python_test_2: Resource 'data.external.test_python' does not have attribute 'result.*.status' for variable 'data.external.test_python.*.result.*.status'
* output.result_of_python_test: Resource 'data.external.test_python' does not have attribute 'result.*.status' for variable 'data.external.test_python.result.*.status'
* output.result_of_python_test_3: Resource 'data.external.test_python' does not have attribute 'result.status' for variable 'data.external.test_python.*.result.status'

```

**Comment by jbardin** [comment]
Hi @JBirdVegas,

While this particular instance would have been hidden by the silent output errors, this is a slightly different case as it wouldn't be valid anywhere in the config. The `depends_on` in the data source is forcing it to not be evaluated in time for the interpolation. 

We're tracking that issue in #11806.
