### ISSUE TITLE
Cannot override child providers if aws region is set in Terraform 0.11.0

### ISSUE THREAD

**Issue by erickt** [hashicorp/terraform#16721]
I'm running into an issue with [Kubernetes Kops](https://github.com/kubernetes/kops/issues/386#issuecomment-345845303), where it generates terraform files with a bundled aws provider. I used to be able to place this in a submodule and override the aws profile in a supermodule, but this no longer works in Terraform 0.11.0. I've reduced this code down to a simple example below.

### Terraform Version

```
terraform -v
Terraform v0.11.0
+ provider.aws v1.3.1
```

### Terraform Configuration Files

`parent/main.tf`:

```hcl
provider "aws" {
    profile = "some_profile"
    region = "us-west-2"
}

module "child" {
    source = "child"
    providers = {
        "aws" = "aws"
    }
}
```

`parent/child/main.tf`:

```hcl
provider "aws" {
    // NOTE: Comment this out and it works
    region = "us-west-2"
}

resource "aws_iam_user" "foo" { name = "foo" }
```

### Output

This produces this error message:

```
% terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.child.provider.aws: No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider
```

If you comment out the `region` in the child module, it works.

### References

This may be a duplicate of #16683 or #16612.

**Comment by jbardin** [comment]
Hi @erickt,

Sorry about he confusion here, this is quite different from the old behavior in some cases.

Inheritance can no longer override anything. If you want to pass in a provider configuration to a module, that module's provider config must be empty as you've shown in your example. This allows both the parent module to specify _exactly_ what provider the child module will use, and allows a child module a way to declare a provider and not have it overridden.

The first issue you referenced is working as expected, and we're improving the documentation to better match that. The latter issue is an improvement that will be be in an upcoming release, where the empty provider block will be optional when passing in a provider from the parent.

**Comment by jbardin** [comment]
Closing this for now, since we are already tracking the related issues.
