### ISSUE TITLE
local variables broken in v0.11.0 - resource variables must be three parts: TYPE.NAME.ATTR

### ISSUE THREAD

**Issue by tburt11** [hashicorp/terraform#16730]
Problem is exhibited with all defined local variables.

### Terraform Version
v0.11.0

### Terraform Configuration Files

From the terraform documentation for local variables:

```# Define the common tags for all resources
locals {
  common_tags = {
    Component   = "awesome-app"
    Environment = "production"
  }
}

# Create a resource that blends the common tags with instance-specific tags.
resource "aws_instance" "server" {
  ami           = "ami-123456"
  instance_type = "t2.micro"

  tags = "${merge(
    local.common_tags,
    map(
      "Name", "awesome-app-server",
      "Role", "server"
    )
  )}"
}

```

### Expected Behavior

Terraform has been successfully initialized!

### Actual Behavior

```# terraform11 init
Error loading configuration: Error loading /tmp/local2/main.tf: Error reading config for aws_instance[server]: local.common_tags: resource variables must be three parts: TYPE.NAME.ATTR in:

${merge(
    local.common_tags,
    map(
      "Name", "awesome-app-server",
      "Role", "server"
    )
  )}
```
### Steps to Reproduce

Create a .tf file with the above example lines and run terraform init

**Comment by jbardin** [comment]
Hi @tburt11,

Are you certain that this is the exact config you used to reproduce the issue? Using that config exactly as written doesn't produce any errors for me.

**Comment by tburt11** [comment]
@jbardin Hmm...  I installed the v0.11.0 on a fresh macbook, and it works OK.
Must be something in my working environment.  I will do further testing next week.
Thanks!

**Comment by tburt11** [comment]
Closing - User Error..

**Comment by repl-chris** [comment]
did you ever figure out what the issue was?  I am seeing this same thing and can't figure it out...

**Comment by pixelicous** [comment]
@tburt11 What was the issue?

**Comment by sureshgoli81** [comment]
I observed this exact error message when accidentally using a terraform binary older than 0.10.3 (0.9.11, in my case) on a configuration which used locals in resource definitions. /cc @pixelicous @repl-chris @tburt11

**Comment by pixelicous** [comment]
@sureshgoli81 thx, it was the same issue here..

**Comment by bflad** [comment]
FYI in case you didn't know, you can add a [required Terraform version configuration](https://www.terraform.io/docs/configuration/terraform.html#specifying-a-required-terraform-version) to ensure you're always running against a version you expect, e.g.
```
terraform {
  required_version = ">= 0.10.3"
}
```

**Comment by trixpan** [comment]
For those asking: The issue also happens if the user accidentally uses `locals.whatever_key_of_your_choice` instead of `local.whatever_key_of_your_choice`

(note the extraneous **S**)

**Comment by CGavrila** [comment]
I had this error because I forgot to properly reference the field I wanted.

This failed:
```
records = ["${aws_alb.my_alb}"]
```

This worked:
```
records = ["${aws_alb.my_alb.dns_name}"]
```
