### ISSUE TITLE
Provider Values with special characters, are getting Re-Interpolated within Modules.

### ISSUE THREAD

**Issue by jmeisner3** [hashicorp/terraform#16745]
### Terraform Version
```
Terraform v0.10.8
```

### Terraform Configuration Files
main.tfvars.json
```json
{
     "user": "test",
     "password": "asdf${eret"
}
```

main.tf
```hcl
variable "username" {
  description = "Account username"
}
variable "password" {
  description = "Account password"
}

provider "any" {
  version = "1.0.0"
  user = "${var.username}"
  password = "${var.password}"
}

module "some" {
  source = "./module"
}
```

module/main.tf
```hcl
resource "any_resource" "resource_name"{
  some = "property"
}
```

### Expected Behavior
The provider credentials passed in, within a var, should be not re-interpolated.

### Actual Behavior
A module that uses the provider will complain about expecting `}` and finding the end of string.

### Steps to Reproduce
Difficult to reproduce, but could be easier to see with a pass through provider. Its the `${` in the value of the password that is throwing things off. I tried escaping with `$${` but that ultimately means the credentials are not passed in correctly, and I get an auth error.

### Important Factoids
Using a custom provider, which uses randomly generated, expiring passwords.

**Comment by apparentlymart** [comment]
Hi @jmeisner3! Sorry for the confusing behavior here.

It would be helpful if you could share the full text of the error message, ideally with the full log output produced by `TF_LOG=trace` (pasted in a [gist](https://gist.github.com/), since it's likely to be long), so we can get a better sense of where inside Terraform this error is coming from. My _suspicion_ is that the parsing of the `tfvars` file _itself_ is where the error is coming from, but more detailed output is necessary to confirm that.

**Comment by igoratencompass** [comment]
Have similar issue with passing aws provider version as variable:

```
provider = {
  access_key = "xxx"
  secret_key = "yyy"
  region     = "ap-southeast-2"
  version    = "~> 1.60"
}

provider "aws" {
    access_key = "${var.provider["access_key"]}"
    secret_key = "${var.provider["secret_key"]}"
    region     = "${var.provider["region"]}"
    version    = "${var.provider["version"]}"
}
```

then get the error:

```
The value "${var.provider[\"version\"]}" given for provider.aws is not a valid
version constraint.
```

when running `terraform plan` presumably because of the special characters. How do I properly escape those?

**Comment by mildwonkey** [comment]
Hi all! It seems like we have two issues here. The former is likely a problem in the tfvars file. As for the latter: this is a misleading error. Terraform does not allow variables in the provider version attribute.
The error message is clearer in terraform 0.12:

```
$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Variables not allowed

  on main.tf line 18, in provider "aws":
  18:   version     = var.aws_provider["version"]

Variables may not be used here.
```

I'm going to close this issue - thanks!
