### ISSUE TITLE
Missing documentation for parent_route53_zone key.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform#1675]
I can't seem find documentation for `parent_route53_zone`, even though it is shown in one of the examples at https://www.terraform.io/docs/providers/aws/r/route53_zone.html

**Comment by johnrengelman** [comment]
I believe that documentation is wrong. There's nothing like that in the AWS documentation AFAIK and I don't see anything in the code either that handles that property.

**Comment by apparentlymart** [comment]
I believe this was left over from an example that was taken from issue #305. It has never actually existed in a released version of Terraform.

**Comment by johnrengelman** [comment]
This has now been cleaned up and removed since v.0.5.0
