### ISSUE TITLE
terraform provider version constraint not working

### ISSUE THREAD

**Issue by salimane** [hashicorp/terraform#16765]
Even tough I specified a version of the aws provider , terraform always download the latest version of the provider.

### Terraform Version
```
± terraform version                                                                                                                                                                                            
Terraform v0.10.8
```

### Terraform Configuration Files
```hcl
provider "aws" {
  region  = "${var.aws_region}"
  version = "1.1.0"
}
```

### Expected Behavior
```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.1.0)...
```

### Actual Behavior
```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.3.1)...
```
### Steps to Reproduce
1. rm -rf .terraform
2. `terraform init`

**Comment by tombuildsstuff** [comment]
hey @salimane

Thanks for opening this issue

Whilst I believe you may have uncovered an issue that the Version Validation should have picked up (@jbardin can confirm for sure) - you should be able to target this version using the `~> ` prefix [as described in the Provider Version documentation](https://www.terraform.io/docs/configuration/providers.html#provider-versions) - as shown below:

```
provider "aws" {
  region  = "${var.aws_region}"
  version = "~> 1.1.0"
}
```

Thanks!

**Comment by salimane** [comment]
@tombuildsstuff  it still doesn't work for patches. Consider the following : 
```hcl
provider "aws" {
  region  = "${var.aws_region}"
  version = "~> 1.3.0"
}
```

What I really want is to use the `1.3.0` tag, but terraform still downloads the tag `1.3.1`. This is problematic because the tag `1.3.1` has a bug.

Thanks

**Comment by jbardin** [comment]
HI,

You should be able to specify the exact version, either as `"=1.3.0"` or just `"1.3.0"`. 

@salimane, can you show the full log output from the `init ` command where you're getting the incorrect version?

**Comment by salimane** [comment]
@jbardin I just tried "=1.3.0" or just "1.3.0" and it works. the following was downloading "1.3.1"

```hcl
provider "aws" {
  region  = "${var.aws_region}"
  version = "~> 1.1"
}
```
 and it's actually right..

I will close this
