### ISSUE TITLE
Terraform not honoring the local state lock file

### ISSUE THREAD

**Issue by ashishth09** [hashicorp/terraform#16786]
Hi, I bumped into a issue mentioned in https://groups.google.com/forum/#!msg/terraform-tool/-09wjjyx6Hk/KoDb-BLCAgAJ. Could you please help?

In essence if the `terraform apply` process is cancelled abruptly for example the terminal in which it runs is simply closed then lock file `.terraform.tfstate.lock.info` is not cleaned up. Next time if one issues `terraform apply` then it continues to work without any problem in acquiring locks even though a lock file from previous process already exists in the filesystem.

**Comment by ashishth09** [comment]
I had a quick glance in the code. Looks like it is not about the presence of the lock file at all. If there is a another live process executing at https://github.com/hashicorp/terraform/blob/master/state/local_lock_unix.go#L12 it will fail to acquire the lock if not it goes ahead and acquires it.

Going by the above code looks like locking will work over the NFS as well and that would explain the scenario mentioned in the google group link above.

**Comment by jbardin** [comment]
Hi @ashishth09,

Yes, the `.info` file only stored the lock metadata, and isn't related to the actual locking mechanism. The lock itself is done through the filesystem. The lock should work over NFS, but I would test your configuration to make sure.
