### ISSUE TITLE
Terraform backend inconsistency: s3 vs artifactory throws invalid or unknown key

### ISSUE THREAD

**Issue by jgensler8** [hashicorp/terraform#16783]
### Terraform Version

Replicated with:
* v0.10.4
* v0.11.0

### Terraform Configuration Files

`backend.tf`

```hcl
backend {
  s3 {
  }
}
```

`properties.tfvars`

```properties
NTP_SERVERS="1234"
//...
bucket="somes3bucket"
```

`deployer.py` (using [python-terraform](https://github.com/beelit94/python-terraform))

```
t.init(terraform_module, backend_config=[properties_file, secrets_file], capture_output=False)
```

### Debug Output

```
build	28-Nov-2017 11:24:53	Initializing the backend...
error	28-Nov-2017 11:24:53	Error configuring the backend "s3": 68 error(s) occurred:
error	28-Nov-2017 11:24:53	
error	28-Nov-2017 11:24:53	* : invalid or unknown key: NTP_SERVERS
...
many more
...
error	28-Nov-2017 11:24:53	* : invalid or unknown key: REQUIRES_DASHBOARD
error	28-Nov-2017 11:24:53	WARNING:python_terraform:error: None
build	28-Nov-2017 11:24:53	Failed running 'terraform init'
```

### Crash Output

None

### Expected Behavior

Like the Artifactory backend, we should be able to provide more than enough information to create the `backend` for our Terraform remote state.

### Actual Behavior

The `s3` backend throws errors for keys that are not used whereas the `artifactory` backend does not. The s3 provider is provided with all necessary configuration.

### Steps to Reproduce

```
terraform init --backend-config=path/to/somefile-with-extra-backend-configuration.tfvars
```

### Important Factoids

I think the issues has to do with the s3 backend defined in the [`terraform/backend/remote-state-s3` package](https://github.com/hashicorp/terraform/tree/master/backend/remote-state/s3) whereas the artifactory provider is defined in the [`terraform/state/remote` package](https://github.com/hashicorp/terraform/tree/master/state/remote).

### References

None Found

**Comment by jbardin** [comment]
Hi @jgensler8,

This is the expected behavior now, as the new remote state backends use a strict schema for their configuration. The config file is meant to be applied directly to the backend config, and it's not expected to try and extract the possible keys from a general bucket of variables like what might be in a tfvars file.

**Comment by jgensler8** [comment]
@jbardin,

Thanks for this information. Our team will configure our deployment logic to configure the s3 backend with only the necessary variables!
