### ISSUE TITLE
Feature Request: AWS Fargate

### ISSUE THREAD

**Issue by danieladams456** [hashicorp/terraform#16790]
### Terraform Version
Terraform v0.11.0

We would like to use the new [LaunchType parameter](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-launchType) on the ECS run-task API to launch Fargate containers without having to manage EC2 instances.

https://aws.amazon.com/blogs/aws/aws-fargate

**Comment by jbardin** [comment]
Hi @danieladams456,

This is an AWS provider feature, for which someone has already submitted an issue: https://github.com/terraform-providers/terraform-provider-aws/issues/2471

Thanks!

**Comment by danieladams456** [comment]
Ah, thanks.  Forgot providers had split out for a moment.

**Comment by jbardin** [comment]
No problem. We usually just transfer them over, but this one was already there ;)
