### ISSUE TITLE
AWS Cloudwatch alarm terraform

### ISSUE THREAD

**Issue by rapullur** [hashicorp/terraform#16795]
Hello everyone. I need some help in setting up the cloudwatch alarm with lambda sns using terraform. I already have a lambda function created manually in AWS console. The goal is to create cloudwatch alarm code with alarm actions pointing to lambda and sns and attach to all existing (78 Ec2 instances). I have tried creating a code as below which is leading to terraform crash unfortunately.

```
resource "aws_cloudwatch_metric_alarm" "statusCheckFailed" {
  alarm_name = "statusCheckFailed"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods = "1"
  metric_name = "StatusCheckFailed_System"
  namespace = "AWS/EC2"
  period = "120"
  statistic = "Maximum"
  threshold = "1"
  insufficient_data_actions = []
  dimensions {
    instance_id = "${aws_instance.test-ec2.id}"
    alarm_actions = 2
    alarm_actions = "arn:aws:sns:us-east-1:848676982977:ckc-preprod-lambda-ec2stopstart"
    alarm_actions = "arn:aws:automate:us-east-1:ec2:recover"
    alarm_description = "statusCheckFailed"
    actions_enabled = "true"
  }
}
```

Please help!! This is an urgent task.

**Comment by tombuildsstuff** [comment]
@rapullur is it possible to post the crash log that you're seeing so that we can investigate this further? I believe this is a separate issue/crash from #16788?

Thanks!

**Comment by rapullur** [comment]
Thanks for the response. Please see below for the crash output error ,The crash log has been referred in #16788

**Comment by tombuildsstuff** [comment]
@rapullur thanks for getting back to me - in that case I'm going to close this in favour of #16788 (since the crash log's there)

Thanks!

**Comment by rapullur** [comment]
Thank you. Please go ahead.
