### ISSUE TITLE
Terraform Crashed using terraform environment

### ISSUE THREAD

**Issue by gkasera** [hashicorp/terraform#16792]
We are getting terraform crash while running terraform plan, Attached is the crash.log for the same.
[crash.log](https://github.com/hashicorp/terraform/files/1515945/crash.log)

**Comment by CrankyDragon** [comment]
From the looks of it, you're using terraform 0.8.4 and the current version of terraform is 0.11.0. I'd suggest upgrading terraform to see if this is still a problem as a first step. You can find instructions on how to upgrade terraform here:
https://www.terraform.io/upgrade-guides/0-11.html
