### ISSUE TITLE
does taint support TF modules?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#1680]
I have in a `main.tf`, an instance of a module:

```
module "cleaders" {
    source = "../leaders"
    ...
}
```

And I want to _taint_ that module, so I run tf taint:

```
ᐅ tf taint module.cleaders
The module root has no resources. There is nothing to taint.
```

I see talk of which resource to target in a module in taint's docs https://terraform.io/docs/commands/taint.html, but I am unable to figure out how to taint a module (from root) so that the entire module is rm'd on the next apply.

**Comment by arubis** [comment]
You can taint resources within modules:

`terraform taint -module=cleaders resource.designator`

Ie. I often use `terraform taint -module=salt_master aws_instance.salt_master` to reprovision my configuration management servers.

**Comment by ketzacoatl** [comment]
thanks @arubis! I have used your confirmation to update the docs a tiny bit.

**Comment by ajmath** [comment]
What about tainting an object nested two modules deep?
