### ISSUE TITLE
Remove attribute from state

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#16809]
Hi,

I am implementing a feature and want to know if terraform has an in-built method to remove attribute from the state file?

I know there is `resource.TestCheckNoResourceAttr` for testing

But I was wondering if an attribute is set in the statefile and is no longer needed, how do I remove it from the state file

**Comment by gordonbondon** [comment]
Hi @Puneeth-n ! Were you able to solve this? I'm actually looking how to do the same but can't find a solution.

**Comment by Puneeth-n** [comment]
@gordonbondon  Yes. we need to write a migration function I guess. Check this out for example: 


https://github.com/terraform-providers/terraform-provider-aws/blob/502adf379da81926e8f32ab077d6b0d1437dc9ee/aws/resource_aws_codebuild_project_migrate.go#L11-L36

**Comment by gordonbondon** [comment]
Thanks!
