### ISSUE TITLE
Specify provider download path in terraform init

### ISSUE THREAD

**Issue by MCyprien** [hashicorp/terraform#16815]
Hi all,

I'm trying to set a path to download the provider plugin as we don't have access to internet in my project. We use artifactory to handle our binaries. Is there a way to tell terraform to get plugins at another url?

### Terraform Version
```
0.11.1
```

### Terraform Configuration Files
```hcl
provider "aws" {
     "plugin_url" = "https://my.custom.url"
}
```

### Debug Output
```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.5.0)...

...
```

### Expected Behavior
```
Initializing provider plugins...
- Checking for available provider plugins on https://my.custom.url...
- Downloading plugin for provider "aws" (1.5.0)...

...
```

### Steps to Reproduce
```
1. `terraform init`
```

**Comment by nbering** [comment]
You might benefit from using [terraform-bundle](https://github.com/hashicorp/terraform/tree/master/tools/terraform-bundle), which is a separate utility used to make a bundle of all the plugins you need in advance, in then you can use the `-plugin-dir` argument of `terraform init` to tell Terraform where your bundle is.

**Comment by jbardin** [comment]
Hi @MCyprien,

While we do have plans to eventually support custom provider sources in some manner, the `terraform-bundle` tool is the recommended way to collect all your providers in a single archive. This was designed specifically for customers running terraform with no direct internet connection.

It's also completely possible to do this manually if you want, by downloading the required providers and storing them in the config directory under `./terraform.d/plugins/OS_ARCH/`, `~/.terraform.d/plugins/OS_ARCH/`, or locating them via the `-plugin-dir` option.

**Comment by TheTimBecker** [comment]
@jbardin is this still the case? We are using Terraform in our CI/CD pipeline, so we would have to bundle the plugins in the Docker image that runs Terraform. This isn't an issue except that plugins are updated so frequently we'd have to rebuild the image constantly. We'd like to use our artifact repository as a plugin mirror so our builds can always access the most recent plugin versions.
