### ISSUE TITLE
Commenting out to destroy modules fails since 0.11.0

### ISSUE THREAD

**Issue by sublee** [hashicorp/terraform#16825]
Since `0.11.0`, and also on `0.11.1`, I cannot destroy my resource by commenting out, but it works on `0.10.8` as well.

### Terraform Version

```
Terraform v0.11.1
+ provider.aws v1.5.0
```

### Terraform Configuration Files

The below config can be created as well.  They make just one EC2 instance.

```hcl
# mytest/terraform.tf
provider "aws" {
  region = "ap-northeast-1"
}
```
```hcl
# mytest/main.tf
module "test_ec2" {
  source        = "../lib/simple-ec2
  num_instances = 1
  region        = "ap-northeast-1"
}
```
```hcl
# lib/simple-ec2/main.tf
variable "num_instances" {}
variable "region" {}

resource "aws_instance" "simple_ec2" {
  count         = "${var.num_instances}"
  ami           = "ami-bec974d8"
  instance_type = "t2.micro"
}
```

### Expected Behavior

I commented out `mytest/main.tf` to deactivate it.  And I tried to run `plan` then `apply`.  It should destroy the EC2 instance clearly.

### Actual Behavior

It fails with a strange error:
 
```
Error: Error asking for user input: 1 error(s) occurred:

* module.test_ec2.aws_instance.simple_ec2: configuration for module.test_ec2.provider.aws is not present; a provider configuration block is required for all operations
```

### Steps to Reproduce

1. `cd mytest/`
2. `terraform init`
3. `terraform plan -out terraform.tfplan`
4. `terraform apply terraform.tfplan` - Now you got an EC2 instance.
5. `echo > main.tf` - Remove the `module.test_ec2`.
6. `terraform plan -out terraform.tfplan` - You got the error!

**Comment by jaxzin** [comment]
I'm hitting this too. @sublee any info on how you got around this?

**Comment by sublee** [comment]
@jaxzin It was my fault.  Since `0.11.0`, a module except root modules cannot define `provider` itself.  It should be passed from the root module.  You can get the notice at https://www.terraform.io/upgrade-guides/0-11.html#interactions-between-providers-and-modules.

When I found a compact reproducing code, I closed this issue and opened a new one: https://github.com/hashicorp/terraform/issues/16826.  This issue and the reply from @jbardin will help you.  I hope you fix your problem also.
