### ISSUE TITLE
Unable to do condition

### ISSUE THREAD

**Issue by MaximF** [hashicorp/terraform#16841]
Hi there!

### Issue explanation
I'm trying to do condition and provision server in a public or a private subnet depending on variable, but getting `literal not terminated` error.

I'm following this documentation: https://www.terraform.io/docs/configuration/interpolation.html#conditionals

### Terraform Version
```
Terraform v0.11.1
+ provider.aws v1.5.0
```

### Terraform Configuration Files
Here is a part of a module
```hcl
subnet_id = "${var.vpc_subnet_type == "private" ? "${lookup(var.**vpc_subnet_private**, element(split(",", lookup(var.azs, var.aws_region)), count.index) )}" : "${lookup(var.**vpc_subnet_public**, element(split(",", lookup(var.azs, var.aws_region)), count.index) )}"}
```
Without extrapolation it would look like the following:
```hcl
subnet_id = "${var.vpc_subnet_type == "private" ? "subnet-XXXXXXXX" : "subnet-YYYYYYYY"}
```

Whenever I call this module I set a variable `vpc_subnet_type = "private"`

### Crash Output
```
# terraform init
Error downloading modules: Error loading modules: module reputation_server: Error parsing .terraform/modules/<hash>/tomcat.tf: At 32:262: literal not terminated
```

### Expected Behavior
Terraform should be able to assign a proper subnet 

### Actual Behavior
It fails to parse an expression

Appreciate any help! Thanks!

**Comment by jbardin** [comment]
Hi @MaximF 

It's looks like both your interpolation strings for `subnet_id` are missing the closing `"`.

**Comment by MaximF** [comment]
@jbardin 
Thank you, just figured it out!

**Comment by Bharath1313** [comment]
Hi 
Am getting Error running fmt: In ec2.tf: At 5:2: literal not terminated

my ec2.tf file looks like

      1 provider "aws" {
      2   access_key = "${var.access_key}"
      3   secret_key = "${var.secret_key"
      4   region     = "${var.region}"
      5 }
      6
      7 resource "aws_instance" "myfirstinst" {
      8   ami           = "${lookup(var.ami, var.region)}"
      9   instance_type = "t2.micro"
     10   key_name      = "testkey"
     11 }
     12
     13 resource "aws_eip" "staticip" {
     14   instance = "${aws_instance.myfirstinst.id}"
     15   vpc = "true"
     16 }
~
I created a variable file for this, that is variable.tf. output of this file is 

      1 variable "access_key" {
      2   description = "AWS access key"
      3 }
      4
      5 variable "secret_key" {
      6   description = "AWS secret key"
      7 }
      8
      9 variable "region" {
     10   description = "setting up AWS deafult region"
     11   default     = "ap-south-1"
     12 }
     13
     14 variable "region_list" {
     15   description = "availability zones"
     16   default     = ["ap-south-1a", "ap-south-1b"]
     17 }
     18
     19 variable "ami" {
     20   type = "map"
     21
     22   default = {
     23     ap-south-1     = "ami-e60e5a89"
     24     ap-southeast-1 = "ami-e2adf99e"
     25   }
     26
     27   description = " the AMI to use "
     28 }
~
~
~

My terraform version is 

Terraform v0.11.5
+ provider.aws v1.13.0

could you please anyone help me out this. 

Thank you
