### ISSUE TITLE
Missing documentation for terraform_remote_state resource.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform#1684]
This is a great resource to have! My `terraform.tfvars` was getting out of control.

**Comment by c4milo** [comment]
@mitchellh, I noticed the local backend is only used for internal development purposes. I think it would be really useful for small teams that do not want to handle all the infrastructure in one state file, neither in a remote store.

**Comment by c4milo** [comment]
Closed by 56e92f7f021900dd030a0175018a4b66142752f7

**Comment by progrium** [comment]
For anybody else looking and found this issue, the local backend reference is here:
https://github.com/hashicorp/terraform/blob/a2014fc846d2761f4ea18198b6c6207314c509fd/state/remote/remote.go#L44

And yes, I agree, I'd love to have this to refer to other local state files.

**Comment by c4milo** [comment]
FWIW, I started using modules instead, since you can refer to local modules too. But, I hit a wall with https://github.com/hashicorp/terraform/issues/1997

**Comment by progrium** [comment]
Yeah, honestly I don't like modules for this use case. You have to boilerplate all the input/output variables and there's tons of weird dependency resolution issues.

**Comment by c4milo** [comment]
Yeah, I have similar feelings. But, having multiple state files is kind of meh some times.
