### ISSUE TITLE
[Question] How to convert string to list or map

### ISSUE THREAD

**Issue by LanceNero** [hashicorp/terraform#16868]
Hi there,

### Terraform Version
```
Terraform v0.10.7
```

### Question
  I have a json string, like this:
```json
{
    "key1":"value1",
    "key2":["value2-1","value2-2"],
    "key3":[{ "subkey1":"subvalue1"},{"subkey2","subvalue2"},{"....":"...."}]
}
```
  I can get the key/value pair , but how to convert json string to list or map  ?
  Currently, I can convert a string to a list, using the split method, but is there a better way?
  And how to convert string to map?   

  Thanks for any help!

**Comment by LanceNero** [comment]
Hi @apparentlymart 
   I have a string , like this :
   ```json
       {"key1":"value1","key2":"value2"}
   ``` 
   Do you have solution for this scenario?  
  Please help me, Thanks

**Comment by apparentlymart** [comment]
Hi @LanceNero,

At the moment there is no built-in way to decode a JSON string. There is some discussion about this in #10363, including information about our plans here.

In the mean time, it is necessary to pass data into Terraform some other way, such as generating a `.tfvars` file containing your value to access it via an input variable.

**Comment by LanceNero** [comment]
Hi @apparentlymart 
  Ok, got it
  Thanks your reply

**Comment by realAndyLuo** [comment]
in my code, I use External data source to convert a string to map. e.g: for string like  {"key1":"value1","key2":"value2"}
```
data "external" "converer" {
  program = ["echo", "${var.str}"]
}

output "value1" {
  value = "${(lookup(data.external.converter.result, "key1")}"
}
```
The output would then be "value1".

**Comment by timduly4** [comment]
@oulydna is spot on, but I thought I would correct a few typos:

```
data "external" "converter" {
  program = ["echo", "${var.str}"]
}

output "value1" {
  value = "${lookup(data.external.converter.result, "key1")}"
}
```
If I saved someone 3 minutes, it's worth it 🎉

**Comment by kism3t** [comment]
@timduly4 And @oulydna I get the error in powershell 

`* data.external.converter: 1 error(s) occurred:

* data.external.converter: data.external.converter: can't find external program "echo"`

**Comment by timduly4** [comment]
@kism3t this indicates that you don't have `echo` on your machine-- are you on Windows? If so, you'll need to find the Windows equivalent...

**Comment by kism3t** [comment]
I run on windows within poweshell. There I have echo command.
