### ISSUE TITLE
Can't build Terraform due to hcldec and stringer related error

### ISSUE THREAD

**Issue by xiaozhu36** [hashicorp/terraform#16887]
I cloned terraform on master and want to develop new backend, but when I building terraform got  the following error:

    $ make
    ==> Checking that code complies with gofmt requirements...
    go generate ./...
    2017/12/11 09:48:21 Generated command/internal_plugin_list.go
    stringer: checking package: decoder_spec.go:4:2: could not import github.com/hashicorp/hcl2/hcldec (reading export data: /Users/heguimin/Projects/go/pkg/darwin_amd64/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcldec.a: invalid encoding format in export data: got 'v'; want 'c' or 'd')
    config/configschema/schema.go:80: running "stringer": exit status 1
    stringer: checking package: diagnostics.go:4:2: could not import bytes (reading export data: /usr/local/go/pkg/darwin_amd64/bytes.a: invalid encoding format in export data: got 'v'; want 'c' or 'd')
    tfdiags/diagnostic.go:11: running "stringer": exit status 1
    make: *** [generate] Error 1

I've tried:

- installing it with `go get github.com/hashicorp/hcl2/hcldec`
- installing it with `go get -u golang.org/x/tools/cmd/stringer`
- using terraform v0.11.0 and v0.10.8 with the same result
- using make OR make dev results in the same error

What am I doing wrong?

Go version 1.9.2
macOS 10.12.3
make 3.81

**Comment by jbardin** [comment]
Hi @xiaozhu36,

You still seem to have some old build artifacts in there. Try just installing terrafrom itself, which should rebuild any outdated packages as well.

**Comment by xiaozhu36** [comment]
@jbardin thanks for your suggestion, it's my local directory permission issue when I build new package.
