### ISSUE TITLE
Dev installation instruction are not complete

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/terraform#1688]
Hello.

I wanted to install the project locally, But I get an error:

```
>(6)[{..}rc/github.com/hashicorp/terraform](master) make test
go generate ./...
config/lang/ast/ast.go:44: running "stringer": exec: "stringer": executable file not found in $PATH
helper/schema/resource_data_get_source.go:3: running "stringer": exec: "stringer": executable file not found in $PATH
terraform/graph_config_node_type.go:3: running "stringer": exec: "stringer": executable file not found in $PATH
make: *** [generate] Error 1
```

I had to run manually:

```
go get -u github.com/zimmski/tavor
cd $GOPATH/src/github.com/zimmski/tavor
make
```

Then I fixed my `PATH` to add `$GOPATH/bin` in it.

I don't really know what should be fixed (the go code, or the readme..., that's why I can't open a PR)

**Comment by apparentlymart** [comment]
I believe the instructions should've told you to put ``$GOPATH/bin`` in your path earlier on. "stringer" is installed in ``$GOPATH/bin`` by the dependency-installation step.

**Comment by lyrixx** [comment]
> I believe the instructions should've told you to put $GOPATH/bin in your path earlier on.

I agree with you on this topic.

> "stringer" is installed in $GOPATH/bin by the dependency-installation step.

I don't understand what I did ;) So I'm closing this issue. Sorry for the noise.

**Comment by knewter** [comment]
For what it's worth, @lyrixx this helped me a lot.  Thanks :)  I ran into the same issue.

**Comment by raulney** [comment]
@lyrixx Thanks a lot! Worked like a charm.

**Comment by smpeters** [comment]
This still seems to be a manual process.

**Comment by hardys** [comment]
+1 I also had to install the stringer dep manually to get make dev to work, thanks for the information!

**Comment by caiges** [comment]
@hardys `make tools` will pull down those particular dependencies.
