### ISSUE TITLE
Output variable does not work 

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/terraform#1689]
I'm still following your intro documentation, and the steps in https://www.terraform.io/intro/getting-started/outputs.html
does not work.

Because the previous step did not work with 0.4.2, I'm using `Terraform v0.5.0-dev (3d367794e93ce56fb7f6f29f2e5035ea62c6e0d3)`

```
>(6)[{..}s/infrastructure/terraform/config](elasticsearch *+) cat elasticsearch.tf 
provider "aws" {
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
    region = "${var.region}"
}

resource "aws_instance" "elasticsearch" {
    ami = "ami-e92c419e"
    instance_type = "t1.micro"
    provisioner "local-exec" {
        command = "echo ${aws_instance.elasticsearch.public_ip} > file.txt"
    }
}

resource "aws_eip" "ip" {
    instance = "${aws_instance.elasticsearch.id}"
}

output "ip" {
    value = "${aws_eip.ip.public_ip}"
}
>(6)[{..}s/infrastructure/terraform/config](elasticsearch *+) terraform apply
aws_instance.elasticsearch: Refreshing state... (ID: i-2db39ecb)
aws_eip.ip: Creating...
  allocation_id:  "" => "<computed>"
  association_id: "" => "<computed>"
  domain:         "" => "<computed>"
  instance:       "" => "i-2db39ecb"
  private_ip:     "" => "<computed>"
  public_ip:      "" => "<computed>"
aws_eip.ip: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
>(6)[{..}s/infrastructure/terraform/config](elasticsearch *+) terraform output ip
The state file has no outputs defined. Define an output
in your configuration with the `output` directive and re-run
`terraform apply` for it to become available.
```

As you can see:

1. The output of `terraform apply` is not as expected
1. The command `terraform output` does not work

(It's the third bug I met during the tutorial. I really like your tooling (consul + packer + serf), this is why I try to continue to learn about TF. But actually, it's not very encouraging) 

**Note**: `Apply complete! Resources: 1 added, 0 changed, 0 destroyed.` seems also wrong because the EIP is already created and attached....

**Comment by mitchellh** [comment]
Hm, I just ran this with master and everything worked properly. If you can reproduce this please let me know but I think it must've been fixed at some point.

**Comment by let4be** [comment]
Same problem here and exactly the same error...

**Comment by valentin69** [comment]
Same here.
`terraform --version
Terraform v0.9.2`
`output "swarm_manager_1_public_ip" {
  value = "${aws_instance.swarm-manager.0.public_ip}"
}
`
`terraform output
The state file either has no outputs defined, or all the defined
outputs are empty. Please define an output in your configuration
with the `output` keyword and run `terraform refresh` for it to
become available. If you are using interpolation, please verify
the interpolated value is not empty. You can use the 
`terraform console` command to assist.`
