### ISSUE TITLE
Plugins installation path and delete issue

### ISSUE THREAD

**Issue by githubvick** [hashicorp/terraform#16899]
### Terraform Version

v0.11.1
```
...
```

### Terraform Configuration Files

```hcl
...
```

I had upgraded from version 0.9. I've been using Terraform with automation through  Jenkins where environments would be created and destroyed.

After each automation iteration, the terraform config files would be deleted and checked out from SCM repo.

After installation of 0.11.1, I had to run "terraform init" command and it downloaded the azurerm plugin in .terraform/plugins/linux_amd64/terraform-provider-azurerm_v0.3.3_x4 folder which has the config files and not in the home directory as mentioned here https://www.terraform.io/docs/configuration/providers.html#third-party-plugins

Now when Jenkins tries to delete the repo to checkout again, it complains that it is not able to delete the above plugin probably due to a file lock.

Why the plugins are installed inside of the working directory and not in the home directory ? Is it possible to install the plugin in a different folder during init so that automation is possible? 

Thanks,

### Expected Behavior

Plugins to be installed in the HOME directory
### Actual Behavior

Plugins installed in the working directory

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/596

**Comment by jbardin** [comment]
Hi @githubvick,

Sorry this is posing a problem for you. I'm not sure what would be locking the above file, other than if it was still in use by the running process, but even then linux doesn't enforce file locking and allows unlinking of files being executed. Perhaps it's a mounted volume issue?

The `.terraform/plugins/` directory is where terraform stores the automatically installed plugins. You can certainly store your plugins in your HOME directory as shown in the linked documentation, in the `~/.terraform.d/plugins` directory, by configuring the `plugin_cache_dir` directory, or via the [`-plugin-dir` init flag](https://www.terraform.io/docs/commands/init.html#plugin-installation) which will can be used to prevent automatic installation entirely.

**Comment by githubvick** [comment]
hi @jbardin , thx for your response.

Actually, it is not a file lock, but when Jenkins tries to clean up, it cleans up using git remove command, and it sees there is a new directory .terraform created for installing plugins which is untracked and it is not able to remove it.

git status
# Untracked files:
#       .terraform/

I tried adding export plugin_cache_dir="$HOME/.terraform.d/plugin-cache" in /etc/profile and used 

1)  terraform init from the home directory - it gave this message

Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.

2) **sudo** terraform init from the directory where the Azure tf file reside.

Still it installs on the path "/var/lib/jenkins/workspace/Myservices/04-Execute-Testcases/terraform/azure/.terraform/plugins/linux_amd64/terraform-provider-azurerm_v0.3.3_x4"

and not on $HOME directory.

**Comment by jbardin** [comment]
@githubvick,

The `.terraform` directory is not related only to plugins, and should generally just be ignored in git which should solve the issue here. Even when the plugins aren't stored there, terraform needs to maintain other information related initialization of the config. 

I'm not sure why in (1) you're running `terraform init` in the $HOME directory; you need run that command in the config directory you're initializing. And in (2), `sudo` changes the user, and hence changes the $HOME directory. (you generally do not want to run terraform as root, and there shouldn't be any reason to).

**Comment by ckyoog** [comment]
Hi @githubvick,

You can use environment variable [TF_DATA_DIR](https://www.terraform.io/docs/configuration/environment-variables.html#tf_data_dir) to change the location of dir `.terraform/`

**Comment by jbardin** [comment]
Hi,

I'm closing this for now, as it seems that things are working as expected.
