### ISSUE TITLE
.terraform/plugin_path is not deleted when I run `terraform init` again without -plugin-dir

### ISSUE THREAD

**Issue by ckyoog** [hashicorp/terraform#16904]
I used to run `terraform init` without any options. 

Today, to do some test, I run `terraform init` with option `-plugin-dir /path/to/a/separated/plugin/dir` (and then run plan and apply). After It's done, I delete that separated plugin dir, and re-run `terraform init` without any options again, the init process passed without any problems. But when I run `terraform plan`, it throws an error.

```
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

5 error(s) occurred:

* provider.template: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
* provider.external: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
* provider.null: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
* provider.archive: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
* provider.aws: no suitable version installed
  version requirements: "1.2.0"
  versions installed: none

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".


Error: error satisfying plugin requirements
```
Then I went to check the dir `.terraform/plugins/`, I found each plugin I need is there, looks fine to me. But I noticed the file `.terraform/plugin_path` is still there, not deleted. I know it was created when I was running `terraform init` with option `-plugin-dir ...`. I thought it will be deleted after I re-init without the `-plugin-dir` option, but obviously I was wrong, it's still there.

I guess the plan goes wrong just because this file is still there. So I delete it by myself, and run `terraform plan` again. This time, it succeeds.

So I'm wondering if it is right the file `.terraform/plugin_path` is not deleted when I run `terraform init` again without `-plugin-dir`.

### Terraform Version
0.11.1

**Comment by 321kranthikumar** [comment]
Hello , 
Have solved this issue ?

**Comment by apparentlymart** [comment]
Hi @ckyoog!

It is intentional that `terraform init` won't undo a previous `-plugin-dir` since running that command again applies _additonal_ changes, rather than undoing things previously done.

However, in the 0.11.2 release we added the ability to unset the plugin dirs by passing an explicit empty value to the argument:

```
$ terraform init -plugin-dir=""
```

**Comment by ckyoog** [comment]
Hi @apparentlymart 

Yes, I've read your discussions in that PR, and learned the idea behind the changes. It gives us an option to unset plugin dirs while keeping the safety of re-init. Nice!

Thanks for letting me know, and thank you all.
