### ISSUE TITLE
Worspace support in the gcs backend (feature request)

### ISSUE THREAD

**Issue by benbro** [hashicorp/terraform#16911]
### Terraform Version
Terraform v0.11.1

### Expected Behavior
Being able to use workspaces with the gcs backend.
gcs and s3 have very similar api and functionality so it should work.

### Actual Behavior
Not supported

**Comment by jbardin** [comment]
Hi @benbro,

Can you provide more details about what you were seeing when you tried this? The `gcs` backend was recently added, which means it nows supports locking and workspaces.

**Comment by benbro** [comment]
I didn't try it but the [docs](https://www.terraform.io/docs/state/workspaces.html) doesn't list gcs in supported backends.

I can't find the word workspace in the [gcs code](https://github.com/hashicorp/terraform/tree/master/backend/remote-state/gcs).

**Comment by jbardin** [comment]
Thanks, it looks like the documentation was missed in the update.

**Comment by benbro** [comment]
The gcs backend page in the docs should probably get info about workspaces too:
https://www.terraform.io/docs/backends/types/gcs.html

Similar to the S3 docs:
https://www.terraform.io/docs/backends/types/s3.html#key

**Comment by tlvenn** [comment]
@jbardin I am confused, looking at the backend code for gcs on master, there is indeed no support to handle workspace at the moment.

**Comment by jbardin** [comment]
Hi @tlvenn,

Remote state backends handle workspaces by implementing the [`backend.Backend`](https://github.com/hashicorp/terraform/blob/master/backend/backend.go) interface, which the `gcsBackend` does (specifically in the file https://github.com/hashicorp/terraform/blob/master/backend/remote-state/gcs/backend_state.go).

**Comment by tlvenn** [comment]
Thanks for the clarification, i guess the difference in case of S3 is that a workspace suffix can be provided while in GCS you cant but both supports the feature.
