### ISSUE TITLE
Telefonica Open Cloud Terraform Provider

### ISSUE THREAD

**Issue by niuzhenguo** [hashicorp/terraform#16924]
Hi there, we have created a provider for [Telefonica Open Cloud](https://www.cloud.telefonica.com/en/open-cloud/). I'm wondering if this can get merged to be a provider with terraform mainstream?

Here is the provider
https://github.com/huawei-clouds/terraform-provider-telefonicaopencloud

**Comment by paultyng** [comment]
Closing as this is now a verified provider: https://www.terraform.io/docs/providers/telefonicaopencloud/index.html
