### ISSUE TITLE
Quick Start | Modules | Consul

### ISSUE THREAD

**Issue by arukaen** [hashicorp/terraform#1693]
I am having an issue while trying to follow the [modules](https://www.terraform.io/intro/getting-started/modules.html) section of the quick start guide. 

consul.tf:
```
module "consul" {
    source = "github.com/hashicorp/consul/terraform/aws"

    key_name = "${var.key_name}"
    key_path = "${var.key_path}"
    region = "${var.region}"
    servers = "3"
}
```

terraform.tfvars:
```
access_key = "my access key"
secret_key = "my secret key"
key_name = "my key name"
key_path = "~/.ssh/"
```

I ran terraform get and it grabbed the module just fine. But when I run ```terraform plan``` I get the following error:
```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * provider.aws: "region": required field is not set
```

Up until this point everything was working just great.

**Comment by phinze** [comment]
Hi @arukaen, sorry for the confusion here.

Consul's Terraform module does not have a `provider` declaration, and instead relies on either a top-level provider config blog or environment variables. My personal preference is to use environment variables, but either will do.

You can find details on that here: https://www.terraform.io/docs/providers/aws/index.html

Let me know if this helps point you in the right direction!

(I'll tag this and leave open so we can see about making that section of the quick start guide clearer.)

**Comment by arukaen** [comment]
@phinze Hey thanks for the help! That worked perfectly.
