### ISSUE TITLE
Interpolation Functions for IPv6 CIDR Blocks and Addresses

### ISSUE THREAD

**Issue by naftulikay** [hashicorp/terraform#16942]
### Terraform Version

```
$ terraform -version
Terraform v0.11.1
+ provider.aws v1.5.0
+ provider.template v0.1.1
```

---

This is a feature request. I am designing networks in AWS and I'd like to provide reverse IPv6 DNS support, but in order to do this, I must be able to get all nibbles (hexadecimal digits) out of an IPv6 CIDR block and out of arbitrary IPv6 IP addresses. I need to basically do something like this:

```
resource "aws_route53_zone" "reverse_ipv6" {
  name = "${join(reverse(ipv6digits("${aws_vpc.default.ipv6_cidr_block}")), ".")}.ip6.arpa"
  # ...
}
```

The difficulty here is that I need to be able to expand a CIDR block like `3731:54:65fe:2::a7/54` into a series of nibbles:

```
 3731005465fe000200000000000000a7
```

Then to reverse this series and interpose periods between each nibble:

```
7.a.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.0.0.e.f.5.6.4.5.0.0.1.3.7.3
````

Then finally to append `.ip6.arpa` at the end.

We'd need new Terraform interpolation functions to accomplish this.

**Comment by apparentlymart** [comment]
Hi @naftulikay! Thanks for this feature request.

I suppose this request is the IPv6 equivalent of #9404, which is about helper functions to turn IP addresses and CIDR block addresses into `.in-addr.arpa.` names for IPv4 reverse-DNS purposes.

Given that there seems to be little reason to wrangle IPv6 nibbles directly _other than_ generating reverse-DNS records (please correct me if I'm wrong!) it seems most ideal to me if we could find a way to define a single function, in similar vein to the `cidr...` family of functions, that takes an IPv4 or IPv6 address or CIDR block and does _all_ the work to produce what's needed for a standards-compliant reverse-DNS lookup, ready to be passed directly into resources like `dns_ptr_record` or `aws_route53_record`.

With that said, the IPv4 model for this is definitely more complex than the IPv6 model (requiring special handling when a range splits somewhere other than an octet boundary) so it may not be possible to reach this ideal. Still, I think it'd be worthwhile to try by unifying the discussion over in #9404 to see if we can define something that would work for both cases.

With that said, I'm going to close this issue to consolidate and then post your request here into #9404 so we can try to design the feature holistically. Thanks for the feature request!
