### ISSUE TITLE
Error retreiving EIP from AWS on v0.4.2

### ISSUE THREAD

**Issue by geofffranks** [hashicorp/terraform#1696]
When I try to do a terraform refresh of an already deployed AWS VPC, using binaries built off of the v0.4.2 tag (or later commits), I get the following error:

{code}
Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

Error retrieving EIP: InvalidParameterValue: Invalid value '' for PublicIp. Not a valid IPv4 address.
{code}

However, if I use the released v0.4.2 binaries, this problem does not occur. Am I doing something stupid? I'm trying to get the rep-built terraform to work, so I can test out the f-aws-security-group-rule-resource branch.

**Comment by jstremick** [comment]
@geofffranks , I ran into this while implementing #1468 and resolved it on the related PR. I believe the switch to the official AWS SDK caused this. The goamz library would ignore empty values provided to requests but aws-sdk-go prefers that those values be omitted instead.

**Comment by wazoo** [comment]
This bug still exists as of 0.5.0-dev 3d367794e93ce56fb7f6f29f2e5035ea62c6e0d3

**Comment by wazoo** [comment]
Updated to 764bdbcac9a3286887d69c49dd66223f5b0f4409 in master and this is fixed.

**Comment by geofffranks** [comment]
Confirmed fixed on my end too, thanks!
