### ISSUE TITLE
 Terraform modules, mega-repos, and the TF Registry

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#16979]
I thought this was better to ask on the mailing list, though maybe it is better to bring it to the devs directly, I am not sure.. 

I have a single git repo with a bunch of TF modules in it. The modules work well together in small groups, and together create the various types of stacks we deploy. Recently, I have been working to improve the release process for the repo, primarily to address a few UX issues for devs and users of the modules. While I'd prefer to distribute the modules through the official public Terraform Registry, the Registry imposes the repo naming scheme and one-repo-per-module requirements our mega-repo does not live up to. I like the workflow of the one repo, and do not want to break-up the modules into a bunch of individual git repos (it's worked well for us so far). In reviewing other ways of distributing and versioning modules, the git/repo-based methods are not ideal in that TF will do a single repo clone/checkout for each module, which in our case means 100 copies of the mega-repo if you have 100 instances of the modules in use in the project (some do).

This leads me to a few questions about the registry:

* Is there an official Hashicorp position _against_ mega-repos for modules like this?
* Does the Terraform Registry plan to avoid/block support for mega-repos, or to allow for their use on the Terraform platform?
* Would the Registry be open to providing an API for us to register/publish a new module that is just a URL to the actual archive file? This concept of redirecting to the real URL of the archive seems to already be deeply embedded in the Registry and its spec/implementation, and so adding this API would allow (for example) a user's CI system to store modules on S3 but publish them through the TF Registry.

This also leads me to questions that are more about module dependencies and discovery:

So far, for the life of this mega-repo, we've simply placed the git repo down next to our client project (and more recently inside the project), and then referenced/sourced the modules by file-system path. We used git subtrees to manage the module repo per-project, and to get project-wide versioning for the upstream modules. In this case, when one of the modules used other modules, they would simply reference the dependencies with `source = "../module"` and such. This worked rather well when using subtrees, but still had a few annoyances. Either way, TF would discover all the modules and their dependents just fine. This also appeared to work when I tested sourcing modules from git/hub directly, Terraform would find the dependent modules and source them correctly. Though as previously mentioned, sourcing modules from a mega-repo over git means that Terraform will checkout many copies of the repo (which makes sense). So this leads me to a few questions:

    Does Terraform have any plan or interest in supporting sourcing modules from mega repos, or otherwise improving the UX here? for example the case where modules are sourced from git?
    How is the module discovery expected to work if not using the filesystem URLs? EG, if I have modules on an HTTP server, or S3, or github, how will Terraform attempt to find and retrieve the dependent modules? How are versions resolved?
    For example, if I have a module that I've published on some S3 URL, there are version numbers included in URL, but Terraform probably doesn't understand them, and so what would I put in the `source` when a module has a dependency on one of the other modules in the mega repo?

Thanks for reading along, your feedback is welcome!

Original post: https://groups.google.com/forum/#!topic/terraform-tool/eiM2NBGN9jw

**Comment by banks** [comment]
Hi @ketzacoatl 

As you thought it is best to keep questions/discussions like this on the mailing list so good call posting there - I've replied over there and I'll close this out to keep the thread in one place.
