### ISSUE TITLE
Unable to createa a GKE cluster - Google Cloud

### ISSUE THREAD

**Issue by koalalorenzo** [hashicorp/terraform#16981]
### Terraform Version
```
Terraform v0.11.1
+ provider.google v1.2.0
+ provider.random v1.0.0
```

### Terraform Configuration Files

```hcl

resource "google_container_cluster" "the_cluster" {
  name               = "the-cluster-${random_string.the_cluster_id.result}"
  zone               = "europe-west1-c"
  min_master_version = "1.8.4-gke.1"
  initial_node_count = 1

  logging_service    = "none"
  monitoring_service = "none"

  maintenance_policy {
    daily_maintenance_window {
      start_time = "03:00"
    }
  }

  addons_config {
    http_load_balancing {
      disabled = true
    }
  }

  node_config {
    disk_size_gb = "32"
    image_type   = "COS"
    machine_type = "n1-standard-2"
    preemptible  = false

    labels {
      pool    = "default-pool"
      cluster = "the-cluster"
    }
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

*Note*: The error happens also when creating a `google_container_node_pool`

### Expected Behavior

The cluster is created within 15-30 minutes

### Actual Behavior

Error from Google API:  `All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 1 have registered. Cluster may be unhealthy.`

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

Running on the latest version of macOS (High Sierra)

**Comment by koalalorenzo** [comment]
The error reported is:
```
* google_container_cluster.the_cluster: Error waiting for creating GKE cluster: All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 1 have registered. Cluster may be unhealthy.
```

**Comment by tombuildsstuff** [comment]
hey @koalalorenzo 

Thanks for opening this issue

Since you've already opened an issue about this on the main Google Provider Repository - rather than migrate this issue over there I'm going to close this issue in favour of that one; where this can be looked into.

Thanks!

**Comment by empikls** [comment]
Hi ! 

I have the same problem :

Error: Error waiting for creating GKE cluster: All cluster resources were brought up, but the cluster API is reporting that: only 0 nodes out of 1 have registered; this is likely due to Nodes failing to start correctly; try re-creating the cluster or contact support if that doesn't work.
