### ISSUE TITLE
Make boolean a valid variable type option

### ISSUE THREAD

**Issue by spacez320** [hashicorp/terraform#16984]
### Terraform Version

```
Terraform v0.11.1
```

### Terraform Configuration Files

```hcl
# What is currently possible:
variable "is_internal_only" {
  description = "Whether or not this resources exists internally."
  default = true
  type = "string"
}

# What would be better:

variable "is_internal_only" {
  description = "Whether or not this resources exists internally."
  default = true
  type = "boolean"
}
```

### Expected Behavior

Having a boolean type available for variables seems to make sense, since you can pass a real boolean in HCL.

Thanks for looking. Happy holidays!

**Comment by ColinHebert** [comment]
See https://github.com/hashicorp/terraform/issues/6254

**Comment by spacez320** [comment]
Thanks, I'll follow there.
