### ISSUE TITLE
Feature Request: Blocking Updates to AWS Instances

### ISSUE THREAD

**Issue by jwaldrip** [hashicorp/terraform#1698]
In order to maintain consensus in my etcd cluster, it would be great if updates to user-data would block on each instance where "count" was provided.

**Comment by mitchellh** [comment]
What do you mean "block" ?

**Comment by jwaldrip** [comment]
Would like to see an instance destroyed and recreated one by one of rather than all at once.

**Comment by mitchellh** [comment]
Ah, yes, yes. Okay.

**Comment by knuckolls** [comment]
@phinze and I discussed how this could possibly be implemented just yesterday. I need this as well so a PR will be incoming soonish.

**Comment by sheldonh** [comment]
@knuckolls Any word? This would make managing a production Consul cluster with Terraform... less scary. :-)

**Comment by sheldonh** [comment]
@mitchellh Could you remove waiting-response, to prevent this issue being overlooked?

**Comment by knuckolls** [comment]
@sheldonh This feature is still on my radar, but it hasn't gotten prioritized like we initially discussed. It's forthcoming, like most things i suppose, but I'm not currently actively developing it.

**Comment by sheldonh** [comment]
@knuckolls Understood. Actually, a first glance was a bit disheartening. It turns out that this isn't so useful to me without the ability to spread instances across availability zones. When you discussed how you imagined this working, did you capture any notes?

**Comment by catsby** [comment]
Hello, following up here to see if any of those included found a solution they could share. I'm not sure I know this to be a Terraform concern, but I'm willing to hear more for sure. A rolling restart/create/destroy setup or option doesn't sound unreasonable. 

I'm curious too, does the `lifecycle` block help at all here?

```javascript
lifecycle {
  create_before_destroy = true
}
```

Documentation here: https://terraform.io/docs/configuration/resources.html

**Comment by catsby** [comment]
Closing for now; if the `lifecycle` block I suggest above doesn't do the trick, let me know!
