### ISSUE TITLE
S3 backend should use AWS_REGION as well as AWS_DEFAULT_REGION

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#16990]
It is common practice to use the `AWS_REGION` environment variable to configure the AWS CLI, and indeed the AWS Terraform provider. However, the S3 backend only checks `AWS_DEFAULT_REGION` and does not fall back on `AWS_REGION`: https://github.com/hashicorp/terraform/blob/master/backend/remote-state/s3/backend.go#L44

**Comment by bflad** [comment]
This was fixed with the release of 0.12.0 awhile ago. 👍
