### ISSUE TITLE
Targeting doesn't work for resources with dashes in the name

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#1699]
Our [resource address regexp](https://github.com/hashicorp/terraform/blob/56d7012c4955b15e86706371727dc87466d58b71/terraform/resource_address.go#L78-L87) is using `\w` to match resource names, which [does not include dashes](https://github.com/google/re2/blob/a96b464d60b54917cd3db069b32c8b792b7c6bd3/doc/syntax.txt#L167).

This means that users trying to address resources that have dashes get "Problem parsing address" errors. They don't deserve that!

**Comment by johnrengelman** [comment]
Oh thank god. I thought this was just me and didn't dig into it more.
