### ISSUE TITLE
aws_eip resource missing support for tags

### ISSUE THREAD

**Issue by whereisaaron** [hashicorp/terraform#16993]
### Terraform Version

```
Terraform v0.11.1
+ provider.aws v1.6.0
```

### Terraform Configuration Files

```hcl
resource "aws_eip" "example" {
  vpc      = true
  instance = "i1234567890abcdef"

  tags {
    Name = "EIP for my favourite instance
  }
}
```

### Expected Behavior

EIP created and and tags added

### Actual Behavior

Error: aws_eip.example: : invalid or unknown key: tags

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

Tested in us-east-2 region

### References

Couldn't find any existing issue covering the lack of support for tags on EIP resources. [Manual page for aws_eip resource](https://www.terraform.io/docs/providers/aws/r/eip.html) supports finding that 'tags' is not supported.

**Comment by arnoldokoth** [comment]
Hey @whereisaaron According to this post, this feature was released nine days ago >> https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-virtual-private-cloud-vpc-now-allows-customers-to-tag-their-elastic-ip-addresses/ Not sure whether the latest version of the terraform AWS provider already supports it.

**Comment by whereisaaron** [comment]
Thanks @arnoldokoth  I didn't realize EIP tags were that new, but either way, be great to add support for them. I've been waiting so long for EIP tags (and SG rule descriptions), I want to use them immediately! :-)

v0.6.0 is the latest version of the AWS provider, but that was 12 days ago, so no chance they could be included. And I guess my feature request is best posted over on the provider repo.

**Comment by whereisaaron** [comment]
I've moved this issue over to the [AWS provider repo](https://github.com/terraform-providers/terraform-provider-aws/issues/2805), so I'll close it here.

terraform-providers/terraform-provider-aws#2805

**Comment by arnoldokoth** [comment]
Haha, yeah @whereisaaron We've waited for that feature for too long! :-)

Moving it over to the provider repo makes perfect sense.

**Comment by whereisaaron** [comment]
@arnoldokoth - EIP tags are going to be in the next AWS provider release in the New Year.

terraform-providers/terraform-provider-aws#2768

**Comment by arnoldokoth** [comment]
@whereisaaron Awesome! Thanks.

**Comment by BlaineBradbury** [comment]
Support for search by tags is needed as well, so that we can find and re-attach eips to things like private VPN instances, etc.  I encountered this today when realizing the data source aws_eip does not support the tags block:

RE: "invalid or unknown key: tags" from:

data "aws_eip" "get_eip" {
  tags = {
     "mytag_name" = "mytag_value"
  }
}
output "eip_output" { value = "${data.aws_eip.get_eip.id}" }

**Comment by MaximF** [comment]
@BlaineBradbury, I created a separate ticket for that: #17361
