### ISSUE TITLE
Provisioner Local-Exec Issue

### ISSUE THREAD

**Issue by catz423** [hashicorp/terraform#17012]
Terraform v0.11.1

Running the below local-exec Provisioner (a powershell script that registers VMs to Azure Automation DSC).

provisioner "local-exec" {
        command = "../DSC/OnboardVM.ps1 -AzureVMRGName \"${azurerm_resource_group.vm.name}\" -computerName \"${var.vm_hostname}${count.index}\" -NodeConfig \"FileResource.locahost\""
        interpreter = ["PowerShell", "-Command"]
    }

This is contained within my "azurerm_virtual_machine" resource.

I am receiving this error when initating an apply:

Error running command '../DSC/OnboardVM.ps1 -AzureVMRGName "TFTest_MGMT_App_RG" -computerName "TFTestVM1" -NodeConfig "FileResource.locahost"': exit status 1. Output: ../DSC/OnboardVM.ps1 : The term '../DSC/OnboardVM.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I already verified I can run this as a standalone command from the same path as where the terraform apply is taking place.

thanks for any help

**Comment by dicko2** [comment]
I'm have the same issue, but just trying to do a simple command like "pwd", on openstack windows instances.

2 error(s) occurred: 
* openstack_compute_instance_v2.WebServer[0]: Error running command 'pwd': exec: "powershell": executable file not found in $PATH. Output:  
* openstack_compute_instance_v2.WebServer[1]: Error running command 'pwd': exec: "powershell": executable file not found in $PATH. Output:  

I think this issue should be reopned
