### ISSUE TITLE
Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance "MySQL"

### ISSUE THREAD

**Issue by phelun** [hashicorp/terraform#17013]
Having issue with creating a DB instance. I have looked through related issues, made respective changes still no luck . 

My configuration as below 

### Terraform Version
```
Terraform v0.10.7
```

### Terraform Configuration block
```hcl
resource "aws_security_group" "RDS" {
  name = "sg_rds"
  description = "Use by/for DB instances"
  vpc_id = "${aws_vpc.vpcld_01.id}"

  ingress {
    from_port       = 3306
    to_port         = 3306
    protocol        = "tcp"
    security_groups = ["${aws_security_group.public.id}", "${aws_security_group.private.id}"]
  }
}

resource "aws_db_instance" "db" {
   allocated_storage»= 10
   engine» » = "mysql"
   engine_version» = "5.6.27"
   instance_class» = "db.t1.micro" 
   storage_type = "gp2"
   name» » » = "dbname"
   username» » = "dbuser"
   password» » = "dbpassword"
   db_subnet_group_name  = "${aws_db_subnet_group.rds_subnetgroup.name}"
   vpc_security_group_ids = ["${aws_security_group.RDS.id}"]
 }

```

### Crash Output
1 error(s) occurred:

* aws_db_instance.db: 1 error(s) occurred:

* aws_db_instance.db: Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t1.micro, Engine=mysql, EngineVersion=5.6.27, LicenseModel=general-public-license. For supported combinations of instance class and database engine version, see the documentation.
        status code: 400, request id: 9760ca49-17e0-45be-9664-d5d1feba1176

**Comment by arnoldokoth** [comment]
@phelun Well, going through the docs, I couldn't find `db.t1.micro` listed under MySQL RDS. Either it is not supported while using MySQL or it was discontinued. Could you try using a `db.t2.micro` that is the current generation? Reference here >> https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html

**Comment by phelun** [comment]
@arnoldokoth thanks, thanks fixed it.
