### ISSUE TITLE
terraform will not close the rpc client when EvalCloseProvider eval !

### ISSUE THREAD

**Issue by polefishu** [hashicorp/terraform#17023]
BUG at 
https://github.com/hashicorp/terraform/blob/4700a86ee6f29e80a3f3f55b93e90e804d261fdf/terraform/eval_context_builtin.go#L119

### Terraform Version

```
Terraform v0.11.2-dev
```

### Terraform Configuration Files

```hcl
resource "alicloud_security_group_rule" "allow_http_22" {
  type = "ingress"
  ip_protocol = "tcp"
  nic_type = "intranet"
  policy = "accept"
  port_range = "22/22"
  priority = 1
  security_group_id = "${alicloud_security_group.group.id}"
  cidr_ip = "0.0.0.0/0"
}

resource "alicloud_security_group" "group" {
  name = "hi"
  description = "New security group"
}

provider "alicloud" {
  access_key = ""
  secret_key = ""
  region     = "${var.region}"
}


variable "region" {
  default = "cn-beijing"
}

output "ecs_ids" {
  value = "${join(",", alicloud_security_group.group.id)}"
}

```
### Expected Behavior

the ctx.ProviderCache is map[provider.alicloud:0xc4201460f0], and the var n is provider.alicloud
### Actual Behavior

the ctx.ProviderCache is map[provider.alicloud:0xc4201460f0], and the var n is alicloud

map "ctx.ProviderCache" didn't have key "alicloud", please fixed it.

**Comment by jbardin** [comment]
Hi @polefishu,

Thanks for finding this. This probably slipped through because closing the RPC client effects very few users. What this actually causing an issue for you, or did you happen upon this by accident?

**Comment by polefishu** [comment]
I find this just by accident when learning terraform. 😀
