### ISSUE TITLE
False "invalid characters in heredoc anchor" error

### ISSUE THREAD

**Issue by davidham** [hashicorp/terraform#17039]
### Terraform Version

```
$ terraform -v
Terraform v0.11.1
+ provider.aws v1.5.0
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
  version = "~> 1.5"
}

module "redis_cluster" {

  source = "../../../../modules/data-stores/redis-cluster"

  environment = "staging"
  node_type = "cache.t2.micro"
  num_cache_nodes = "1"
  parameter_group_name = "default.redis3.2"

  # staging private subnets
  subnets = ["subnet-XXXXXXXX", "subnet-XXXXXXXX"]
  # staging vpc
  vpc_id = "vpc-6a6c3e0c"
  security_group_ids = ["sg-XXXXXXXX", "sg-XXXXXXXX"]
}
```

### Debug Output

[Output gist](https://gist.github.com/davidham/2f12be9426348f713b8bf50fe6f4b131)

### Expected Behavior

I expected `terraform plan` to run as it usually does.

### Actual Behavior

I got `Error: Failed to load root config module: Error loading modules: module redis_cluster: Error parsing .terraform/modules/e26d0fa33d168022e17af33137e69943/main.tf: At 8:3: invalid characters in heredoc anchor`.

### Additional Context

The error is at the `source` line for the `redis-cluster` module. Terraform thinks the second hyphen is a heredoc delimiter, but obviously the line is just a 1 line string.

**Comment by ksasmal** [comment]
What was the solution ? I am receiving same error .
