### ISSUE TITLE
terraform destroy does not return 

### ISSUE THREAD

**Issue by horsey** [hashicorp/terraform#17053]
### Terraform Version

```
Terraform v0.11.1
+ provider.azurerm v0.2.2
+ provider.random v1.1.0
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output
None

### Expected Behavior
Should return successfully once the resources on AzureRM are destroyed. 

### Actual Behavior
```terraform destroy```   goes into a loop destroying the virtual network: 
```
module.network.azurerm_virtual_network.vnet: Still destroying... (ID: /subscriptions/733ee852-97a2-4f09-8633-...Microsoft.Network/virtualNetworks/test, 8m50s elapsed)
module.network.azurerm_virtual_network.vnet: Still destroying... (ID: /subscriptions/733ee852-97a2-4f09-8633-...Microsoft.Network/virtualNetworks/test, 9m0s elapsed)
module.network.azurerm_virtual_network.vnet: Still destroying... (ID: /subscriptions/733ee852-97a2-4f09-8633-...Microsoft.Network/virtualNetworks/test, 9m10s elapsed)
module.network.azurerm_virtual_network.vnet: Still destroying... (ID: /subscriptions/733ee852-97a2-4f09-8633-...Microsoft.Network/virtualNetworks/test, 9m20s elapsed)
module.network.azurerm_virtual_network.vnet: Still destroying... (ID: /subscriptions/733ee852-97a2-4f09-8633-...Microsoft.Network/virtualNetworks/test, 9m30s elapsed)
module.network.azurerm_virtual_network.vnet: Still destroying... (ID: /subscriptions/733ee852-97a2-4f09-8633-...Microsoft.Network/virtualNetworks/test, 9m40s elapsed)
module.network.azurerm_virtual_network.vnet: Still destroying... (ID: /subscriptions/733ee852-97a2-4f09-8633-...Microsoft.Network/virtualNetworks/test, 9m50s elapsed)
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform destroy`

**Comment by tombuildsstuff** [comment]
Hi @horsey 

Thanks for opening this issue

Would it be possible to upgrade to the latest version of the AzureRM Provider (currently v`1.0.0`) and see if that fixes this issue? From what I recall we had a deadlock issue which was fixed late last year which should be fixed in this version.

Thanks!

**Comment by horsey** [comment]
Hello @tombuildsstuff 
How do I specify the version? This does not seem to be working: 

```
provider "azurerm" {
  version = "1.0.0"
}

```

**Comment by horsey** [comment]
@tombuildsstuff 

Looks like a few modules that I am using refer to an old version of azurerm - thus causing a conflict.

**Comment by horsey** [comment]
@tombuildsstuff, works after bumping the version to v1.0.0.

Thanks.
