### ISSUE TITLE
panic: Malformed constraint in provider

### ISSUE THREAD

**Issue by scalp42** [hashicorp/terraform#17073]
### Terraform Version
```
> terraform -v                                                                                                                                                             
Terraform v0.11.1
+ provider.aws v1.6.0
```

### Terraform Configuration Files

```main.tf```:

```hcl
provider "aws" {
  version = "${var.aws_provider_version}"
  shared_credentials_file = "~/.aws/creds"
  profile = "default"
  region = "us-west-2"
}
```

`variables.tf`:

```
variable "aws_provider_version" {
  type = "string"
  default = "~> 1.6"
}
```

### Crash Output
https://gist.github.com/scalp42/a1696fea81f0a422b34ad8596db2c508

### Expected Behavior

Should have just interpolated within the `aws` provider.

### Actual Behavior

Crashed.

### Steps to Reproduce
`terraform plan`

### Additional Context
Nothing specific.

Thanks!

**Comment by scalp42** [comment]
I think it's just the `~>` as we tested without and it works fine.

**Comment by jbardin** [comment]
Hi @scalp42,

Sorry about the panic, this is better validated so we will get an error rather than a panic in the latest release.

Version interpolation is not supported in providers: see https://www.terraform.io/docs/configuration/providers.html#interpolation

**Comment by scalp42** [comment]
Thanks for follow up @jbardin! 💅
