### ISSUE TITLE
[Aws] resource do not use resouce id as default name

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/terraform#1707]
I have many issues with the current (3d367794e93ce56fb7f6f29f2e5035ea62c6e0d3) implementation of resource.

I have the following config:

```
resource "aws_vpc" "sl_main" {
    cidr_block = "10.0.0.0/16"
}
```
If I apply directly this configuration, I end up with my VPC. But the name is empty.

![screenshot2](https://cloud.githubusercontent.com/assets/408368/7371211/9e8a22b2-edbf-11e4-95c2-6902c4d9d821.png)

**1/** I think you could set the name I choose, in this case `sl_main`.

**2/** So I try to do the following:

```
resource "aws_vpc" "sl_main" {
    cidr_block = "10.0.0.0/16"
    tags {
        Name = "${self.id}"
    }
}
```

but It does not work, same for `self.name` etc etc. I got the same error:

```
* resource 'aws_vpc.sl_main' config: cannot contain self-reference self.id
```

**Comment by mitchellh** [comment]
This is all working as intended. We don't set any tags by default (because you didn't request any), and `self` currently only works within provisioners (as documented). Sorry for the unexpected behavior, but it is all working as docced.
