### ISSUE TITLE
S3 backend fails to find workspace if workspace name is substring of workspace key prefix

### ISSUE THREAD

**Issue by ljfranklin** [hashicorp/terraform#17083]
### Terraform Version

```
Terraform v0.11.2
+ provider.aws v1.6.0
```

Works as expected with v0.11.1.

### Issue

Create a workspace called `env-1` with a workspace prefix of `env`. The statefile will be located at `s3://YOUR_BUCKET/env/env-1/terraform.tfstate`. Running `terraform workspace list` should show `env-1` but it only shows `default`.

### Steps to Reproduce

1. Upload empty statefile to `s3://YOUR_BUCKET/env/env-1/terraform.tfstate`.
2. Create `backend.tf` with type `s3`, `workspace_key_prefix: env`, `key: terraform.tfstate`
3. `terraform init`
4. `terraform workspace list`
5. Verify that workspace `env-1` is not listed

### References

[This line](https://github.com/hashicorp/terraform/blob/f78fe3c01e494e4eaff25627f8748902751b0d6b/backend/remote-state/s3/backend_state.go#L56) looks to be the culprit. The intent was probably to have `SplitAfter` return at most 2 items but in this situation it returns 3 parts. Using `SplitAfterN` instead might just fix it.

**Comment by ljfranklin** [comment]
cc @jbardin who merged the original workspace prefix PR

**Comment by joshshand** [comment]
nice work @ljfranklin & team - just compiled 0.11.3-dev and ran with no issues. 
Ran into this problem just before and panicked when I only saw a single workspace!!
Thanks 👍
