### ISSUE TITLE
Feature request: Support local state files with workspaces

### ISSUE THREAD

**Issue by cchildress** [hashicorp/terraform#17093]
Has anyone brought up the idea of getting workspaces to work with the local state backend?

I think we could have Terraform just use the workspace name in the filename for the state file and it would work.

Something like `terraform.tfstate.foo` or `terraform.bar.tfstate` would work and it wouldn't be too complex of a change to just search for a local file based on the current workspace context.

**Comment by apparentlymart** [comment]
Hi @cchildress!

The `local` backend already has support for workspaces, creating state files in a subdirectory of the working directory. Did you see an error when you tried this?

**Comment by cchildress** [comment]
No, I didn't expect it to work. The Workspaces [doc](https://www.terraform.io/docs/state/workspaces.html) doesn't list local in the backends.

I'll give it a shot and make a doc PR.

**Comment by apparentlymart** [comment]
Ahh, that does indeed seem like an oversight in the docs. I expect that's a result of the fact that in the early stages of the design of the backends feature the "local" backend was somewhat special and not really presented as a backend at all, but in the mean time it's been [separately documented as a backend](https://www.terraform.io/docs/backends/types/local.html).

Sorry for this oversight!

**Comment by cchildress** [comment]
@apparentlymart 
Hey, sorry this took so long for a one line change.
I opened PR #17245 to close this out.
