### ISSUE TITLE
tfvars not working

### ISSUE THREAD

**Issue by karel1980** [hashicorp/terraform#17106]
I'm unable to work with tfvars files. I am quite new to terraform, maybe I just misread the documentation.
Using terraform 0.11.2, here's what I did:

--- hello.tf ---

    output "myoutput" {
      value="${var.somevar}"
    }
    
 --- terraform.tfvars ---

    somevar = "somevalue"

Whenever I run terraform plan/apply (with or without -var-file=terraform.tfvars) I get an error:

    Error: output 'myoutput': unknown variable referenced: 'somevar'; define it with a 'variable' block

Expected outcome: terraform.tfvars should be loaded automatically, and `var.somevar` should be interpolated in the output

**Comment by huseyinham** [comment]
From that small bit of information, you need to put `variable somevar {}` at the top of the hello.tf file. It will pick it up then. That is what is meant by 'variable block'. Here is a link: https://www.terraform.io/intro/getting-started/variables.html

**Comment by jbardin** [comment]
Hi @karel1980,

Yes, you need to declare the variable in your configuration as well. The tfvars files only supply the values, they can't declare variables.

**Comment by karel1980** [comment]
Thanks @huseyinham @jbardin Thanks. I somehow failed to put the relevant bits of information together.
