### ISSUE TITLE
Something broke between v0.11.1 and v0.11.2

### ISSUE THREAD

**Issue by ctlajoie** [hashicorp/terraform#17117]
Apologies for the ambiguous title, but bear with me. I am experiencing an issue where if I modify AWS security groups, I do not get correct results. However this issue does not have anything to do with the AWS provider. In fact, I used `git bisect` between v0.11.1 and v0.11.2 and I narrowed the bug down to a commit (45439d0ac3c74d19c2939b7836290572c37f0809). 

I made a change to the security groups of an instance. There are currently 4 security groups on this instance, and I am deleting one of them. With v0.11.1, here is the output I get from `terraform plan`:
```
Terraform will perform the following actions:
  ~ aws_instance.caldav
      vpc_security_group_ids.#:          "4" => "3"
      vpc_security_group_ids.1759756461: "sg-34d9be48" => "sg-34d9be48"
      vpc_security_group_ids.2194812518: "sg-2b8aed57" => ""
      vpc_security_group_ids.3121774038: "sg-6660601a" => "sg-6660601a"
      vpc_security_group_ids.832156646:  "sg-dcbebfa0" => "sg-dcbebfa0"
Plan: 0 to add, 1 to change, 0 to destroy.
```
The above output is from terraform v0.11.1. If I apply those changes, everything works as expected.

Now, here is what happens in terraform v0.11.2
```
Terraform will perform the following actions:

  ~ aws_instance.caldav
      vpc_security_group_ids.#:          "4" => "3"
      vpc_security_group_ids.2194812518: "sg-2b8aed57" => ""


Plan: 0 to add, 1 to change, 0 to destroy.
```

The issue is not just cosmetic, either. When I attempt to apply those changes using terraform v0.11.2, I get this:
```
Terraform will perform the following actions:

  ~ aws_instance.caldav
      vpc_security_group_ids.#:          "4" => "3"
      vpc_security_group_ids.2194812518: "sg-2b8aed57" => ""


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_instance.caldav: Modifying... (ID: i-0af7d833400a10d24)
  vpc_security_group_ids.#:          "4" => "3"
  vpc_security_group_ids.2194812518: "sg-2b8aed57" => ""

Error: Error applying plan:

1 error(s) occurred:

* aws_instance.caldav: 1 error(s) occurred:

* aws_instance.caldav: InvalidParameterCombination: No attributes specified.
	status code: 400, request id: fcae2509-f5d6-4b22-86e7-55ab29323ff6

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Here you can find my terraform debug log: https://gist.github.com/ctlajoie/edc43efd97a7314aba5a1c4e035d719a

**Comment by apparentlymart** [comment]
Hi @ctlajoie! Sorry for this apparent regression, and thanks for reporting it.

It looks like the commit you found belongs to #16780, which changed some details of how diffs are handled with the goal of fixing a bug with `ignore_changes`. @jbardin, since you reviewed that PR, do you have an idea of what's going on here?

**Comment by ctlajoie** [comment]
I am able to reproduce this issue consistently on two VPCs that I manage with terraform (I use seperate directories of .tf files for each VPC). I attempted to reproduce the issue with a new test VPC that I created with terraform (with new empty terraform state file as well). Interestingly I was *not* able to reproduce the issue in the new VPC. 

If the problem turns out to be difficult to debug due to inability to reproduce, I can provide you with more information, but I will have to send the .tf and .tfstate files to you guys directly. I don't want them out on the internet and publicly accessible.

**Comment by jbardin** [comment]
Hi @ctlajoie, can you provide your configuration for aws_instance.caldav? 

Thanks!

**Comment by ctlajoie** [comment]
Here is just the block for aws_instance.caldav

```hcl
resource "aws_instance" "caldav" {
  instance_type = "t2.medium"
  ami           = "${var.centosbase-ami}"
  subnet_id     = "${element(aws_subnet.subnets.*.id, local.caldav_subnet_index)}"
  key_name      = "mainkey"
  iam_instance_profile = "baseinstprofile"
  vpc_security_group_ids = [
    "${aws_security_group.sg_linux.id}",
    "${aws_security_group.sg_consul.id}",
    "${aws_security_group.sg_caldav.id}",
  ]
  user_data = "${data.template_file.tpl_caldav_initscript.rendered}"

  disable_api_termination = true

  ebs_block_device {
    device_name = "/dev/xvdb"
    volume_type = "gp2"
    volume_size = 100
  }

  tags {
    Name = "caldav"
    os = "linux"
    az = "${element(aws_subnet.subnets.*.availability_zone, local.caldav_subnet_index)}"
  }

  lifecycle {
    ignore_changes = ["ami"]
  }
}
```

**Comment by jbardin** [comment]
While the new diff is precise, and probably technically correct, the providers aren't expected to deal with reconstituting partial attributes as needed. While we might be able to handle this in helper/schema (I haven't thought it through), core needs to remain compatible with existing provider releases, so that's not an option for a patch release.

Unfortunately it looks like the test in PR #16780 isn't really checking what it said it was. That's my fault for not verifying that the test actually fails without the patch, and the accompanying changes to the related test should have been a clue. 

I think we can restrict the partial diff behavior to happen only when ignoring a specific key, but if this gets too hairy we should probably just revert that PR and postpone it for a major release.

**Comment by ctlajoie** [comment]
@jbardin Any idea why I would not be able to reproduce the issue when I start from scratch? What combination of conditions causes the issue?

**Comment by jbardin** [comment]
@ctlajoie, I'm not sure offhand, but it might come to me once I have a good test for this. It's probably a difference you can see in the state file though. You also may need to use the same versions of the provider you originally used to get to the same state.
