### ISSUE TITLE
Outputs which no longer exist in the configuration linger forever

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#1714]
If I had to guess, as a consequence of #1369.

Start with a simple configuration:

```
output "foo" {
    value = "bar"
}
```

Run `terraform apply` and you will see:

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

  foo = bar
```

Now truncate the configuration to be an empty file. `terraform apply` again. The output, despite no longer existing in the configuration, still exists in the output:

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

  foo = bar
```

I'd expect no outputs, since none are declared in the configuration.

**Comment by radeksimko** [comment]
:+1:
