### ISSUE TITLE
Add "rolling" update lifecycle with "healthcheck" provisioner.

### ISSUE THREAD

**Issue by jzampieron** [hashicorp/terraform#17157]
### Terraform Version

```
v0.11.1
```

### Expected Behavior

Resources are destroyed one-by-one and then recreated one-by-one in a rolling update fashion. 

Continuing to the next resource in the set can optionally be controlled by a "readiness" or "healthcheck" provisioner in some fashion.

This essentially overrides the parallelism flag for a particular resource on "update" operations.

### Actual Behavior

All resources are destroyed and created I.A.W. the parallelism setting in batches.

### Steps to Reproduce

Modify any resource with a count > 1.

### Additional Context

This is vital for being able to enhance existing operational systems in a non-destructive fashion.

### References

- #17142

**Comment by jbardin** [comment]
Hi @jzampieron,

Thanks for filing the issue. I believe this is the same idea as requested in #16200.

**Comment by jzampieron** [comment]
Agreed. It is a similar issue, perhaps identified in a different way.

**Comment by jbardin** [comment]
@jzampieron, Thanks for confirming to make sure we're on the same page. I'm closing this to track the feature in one place for now.

Thanks!
