### ISSUE TITLE
Provider for new Hetzner Cloud

### ISSUE THREAD

**Issue by byrnedo** [hashicorp/terraform#17167]
So Hetzner have now got a cloud offering. Would we be seeing this as a provider in Terraform? 

### Additional Context
Hetzner is AFAIK quite a large and successful hosting company within Europe.

### References
https://www.hetzner.com/cloud?country=gb

https://docs.hetzner.cloud/

**Comment by pstadler** [comment]
This was just released: https://github.com/hetznercloud/terraform-provider-hcloud

**Comment by byrnedo** [comment]
@pstadler nice!!

**Comment by kabudu** [comment]
You can also check out this project which was primarily built to spin up a kubernetes cluster in Hetzner Cloud: https://github.com/xetys/hetzner-kube

**Comment by tombuildsstuff** [comment]
👋 hey all!

As @pstadler has mentioned, [a Terraform Provider is now available for Hetzner Cloud here](https://github.com/hetznercloud/terraform-provider-hcloud) - which is listed [on Terraform's Community Providers Page](https://www.terraform.io/docs/providers/type/community-index.html).

Thanks!

**Comment by pstadler** [comment]
@tombuildsstuff just wondering whether there's a way to install community providers w/o having to fetch and place them manually?

**Comment by tombuildsstuff** [comment]
> @tombuildsstuff just wondering whether there's a way to install community providers w/o having to fetch and place them manually?

@pstadler not at this time, however we're planning on improving the UX in the future.

**Comment by ringods** [comment]
@tombuildsstuff I discussed this topic with your colleague @kikitux during the last Belgium Hashicorp Meetup last week. If the Terraform Registry is the way to go, fine. If you might end up supporting third-party download sites, please make the protocol in such a way that static sites (Github Pages, Netlify) can be used to host releases.

This is one of the best design decisions taken by the Kubernetes Helm Charts community:
https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md#create-a-chart-repository
