### ISSUE TITLE
Deprecated terraform_remote_state environment key not working

### ISSUE THREAD

**Issue by negz** [hashicorp/terraform#17189]
### Terraform Version
```
terraform -v
Terraform v0.11.2
+ provider.aws v1.2.0
+ provider.google v1.3.0
+ provider.ignition v1.0.0
+ provider.local v1.0.0
+ provider.random v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.0.0
```

### Terraform Configuration Files
```hcl
data "terraform_remote_state" "etcd" {
  backend     = "gcs"
  environment = "${var.etcd_cluster_name}" // Synonymous with workspace.

  config {
    project = "REDACTED"
    bucket  = "terraform-state"
    prefix  = "terraform/etcd"
  }
}
```

### Error Output
```
* module.control.var.etcd_tls_client_private_key_pem: Resource 'data.terraform_remote_state.etcd' does not have attribute 'tls_client_private_key_pem' for variable 'data.terraform_remote_state.etcd.tls_client_private_key_pem'
```

### Additional Context
I recently updated from Terraform 0.11.1 to 0.11.2, which contains my PR below that deprecates the `terraform_remote_state` `environment` key in favor of `workspace`. Everything works as expected if I use the new `workspace` key, but if I use the deprecated `environment` key I get the deprecation warning as expected, and then the `does not have attribute` failure above.

https://github.com/hashicorp/terraform/pull/16558/files#diff-5bb530affc03447353d6a5daeee76f9cR94
```go
// environment is deprecated in favour of workspace.
// If both keys are set workspace should win.
name := d.Get("environment").(string)
if ws, ok := d.GetOk("workspace"); ok {
	name = ws.(string)
}
state, err := b.State(name)
```
It seems like this is the offending code, but it's not obvious to me why it's not working as I had expected. This is pretty low impact - I'm mostly curious as to why it's happening. Given it's a deprecated key that is broken it might make sense to just roll forward and remove it.

### References
- #16558

**Comment by negz** [comment]
Aha - my coworker just mentioned the issue is probably that `workspace` has a default value, so the `GetOk` will return that default value, even if it's not explicitly set.

**Comment by mr-olson** [comment]
This affects all backends apparently - I ran into this in S3 backend today, using tf .11.2 and aws 1.6

This is an ugly bug, the environment parameter was completely deprecated in a point release, causing a regression without any warning or transition period. That doesn't seem to have been the intention from the release notes or the source issue https://github.com/hashicorp/terraform/pull/16558

**Comment by negz** [comment]
@mr-olson Updated to reflect that this isn't limited to GCS.

You're correct that the intention was to deprecate the key gracefully. Apologies for the breaking change. :(

**Comment by mr-olson** [comment]
Is there any intention to fix this regression? This causes a flag-day upgrade from .11.1 or before to .11.2 or later for remote state users, having to transition all of my terraform users to the latest version and having to update all templates' remote state data elements' environment/workspace property concurrently.

.11.1 and prior do not understand "workspace" in the context of remote state.

.11.2 and later do not understand "environment" in the context of remote state.

I would prefer to transition gracefully, but can plan for a simultaneous jump if necessary.
