### ISSUE TITLE
Website documentation is outdated wrt github repo

### ISSUE THREAD

**Issue by marco-m** [hashicorp/terraform#17187]
hello,
https://www.terraform.io/docs/providers/terraform/d/remote_state.html still mentions "environment", while https://github.com/hashicorp/terraform/blob/master/website/docs/providers/terraform/d/remote_state.html.md correctly mentions "workspace" (change made 2017-12-05)

**Comment by hussfelt** [comment]
I saw this today as well, still an issue.
How outdated is this docs really? It's been 6 months since the change!

**Comment by marco-m** [comment]
@jbardin ?

**Comment by apparentlymart** [comment]
I have a feeling that the website deploy is still pulling the docs for this provider from [the old separate repository](https://github.com/terraform-providers/terraform-provider-terraform), rather than the copy of it now integrated into the main Terraform codebase. :confounded:

**Comment by marco-m** [comment]
This would explain it.

**Comment by marco-m** [comment]
@apparentlymart do you know if this is still the case / who we could poke ? Thanks!

**Comment by apparentlymart** [comment]
Hi @marco-m!

This was fixed in hashicorp/terraform-website#538. Thanks for pointing it out, and sorry we forgot to close this out after it was fixed.

**Comment by marco-m** [comment]
Thank you @apparentlymart !
