### ISSUE TITLE
expired (but refreshed) AWS session token - terraform.tfstate not pushed to S3

### ISSUE THREAD

**Issue by timecast** [hashicorp/terraform#17180]
Hi,
seems to be an inconsistent behaviour on TF when using AWS session tokens.
If a token expires during a session you can still renew the token and for normal API access this renewed token is being used. But this does not work for tfstate files in S3.

What happens:
* create a session token and write to AWS credentials file (validity 60 mins)
* tfstate configured to use S3 backend and init was successfully done before
* you wait ...
* the session token will have a remaining lifetime of 5 mins and start an apply or destroy. during the session the token expires and you refresh the token in a separate terminal
* apply or destroy continues but will fail in the end with following error:

```
Failed to save state: failed to upload state: ExpiredToken: The provided token has expired.
	status code: 400, request id: 593F2112F64A6BEC, host id: ....

Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate
```

### Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.6.0
+ provider.null v1.0.0
```
### Expected Behavior
terraform should use the refreshed session token as well for S3 backend operations.

### Actual Behavior
seems that refreshed token are being used to access AWS API - but not for pushing the tfstate file to S3

### Steps to Reproduce
see above

**Comment by jbardin** [comment]
Hi @timecast,

Can you show how you're configuring the backend, and how the credentials are being located?
Does this same behavior happen with the aws provider?

**Comment by timecast** [comment]
Hi @jbardin,
credentials are in ~/.aws/credentials and look like:
```
[my-aws-access]
region = eu-west-1
aws_access_key_id = DEADBEEF
aws_secret_access_key = SUPERSECRETKEY
aws_session_token = SUPERLONGSESSIONTOKEN==
expiration = YYYY-MM-DDTHH:MM:SSZ
```
we run terraform like this:
```
AWS_PROFILE=my-aws-access terraform plan
```

backend config is done like this:
```
AWS_PROFILE=my-aws-access terraform init -backend-config ./terraform-s3-backend.init
```
with terraform-s3-backend.init:
```
region  = "eu-west-1"
bucket  = "somebucket"
key     = "somedirectory/myterraform.tfstate"
encrypt = true
```
We only work with AWS - so yes it happens with aws provider.

Cheers

**Comment by jbardin** [comment]
Hi @timecast,

Thanks for the update. 
The backend uses the same client code as the provider itself, so the authentication should behave the same. I'm going to move this over to the aws provider repo, since any possible fix will need to come from there.
