### ISSUE TITLE
Artifactory remote backend - failed state upload - connection reset by peer (timeouts)

### ISSUE THREAD

**Issue by azhurbilo** [hashicorp/terraform#17182]
### Terraform Version

```
Terraform v0.11.0
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "= 0.11.0"

  backend "artifactory" {
    # username = "***"
    # password = "***"
    # subpath  = "***"
    url = "https://***.jfrog.io/***"

    repo = "terraform-local"
  }
}
```

### Crash Output

```
net/http: HTTP/1.x transport connection broken: write tcp ****:49748->****:443: write: connection reset by peer


Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate
```

### Expected Behavior

state pushed successfully

### Actual Behavior

push failed

### Steps to Reproduce

1. try push state behind proxy/firewall which configured to close connections after 5 min for example if "terraform apply" takes more than 5 min

### Additional Context

In our case we use AWS Nat Gateway to send state to Artifactory
seems NAT Gateway has 5 min timeouts https://forums.aws.amazon.com/post!reply.jspa?messageID=731118
but upstream artifactory lib doesn't set correct timeouts
https://github.com/lusis/go-artifactory/issues/9

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
