### ISSUE TITLE
SecurityGroup plan output contains unchanged rules

### ISSUE THREAD

**Issue by chrisferry** [hashicorp/terraform#1719]
I'm constantly adding a port here or port there to my security group stacks.
The output is never cut and dry.  It's always filled with rules that aren't changing.
Makes me sweat bullets before applying.
See below:

~ aws_security_group.use1-inf
    ingress.#:                                    "16" => "17"
    ingress.1156944017.cidr_blocks.#:             "1" => "1"
    ingress.1156944017.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.1156944017.from_port:                 "8300" => "8300"
    ingress.1156944017.protocol:                  "tcp" => "tcp"
    ingress.1156944017.security_groups.#:         "0" => "0"
    ingress.1156944017.self:                      "0" => "0"
    ingress.1156944017.to_port:                   "8302" => "8302"
    ingress.1283062817.cidr_blocks.#:             "1" => "1"
    ingress.1283062817.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.1283062817.from_port:                 "8600" => "8600"
    ingress.1283062817.protocol:                  "udp" => "udp"
    ingress.1283062817.security_groups.#:         "0" => "0"
    ingress.1283062817.self:                      "0" => "0"
    ingress.1283062817.to_port:                   "8600" => "8600"
    ingress.1554318189.cidr_blocks.#:             "1" => "1"
    ingress.1554318189.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.1554318189.from_port:                 "7002" => "7002"
    ingress.1554318189.protocol:                  "tcp" => "tcp"
    ingress.1554318189.security_groups.#:         "0" => "0"
    ingress.1554318189.self:                      "0" => "0"
    ingress.1554318189.to_port:                   "7002" => "7002"
    ingress.1653617659.cidr_blocks.#:             "0" => "0"
    ingress.1653617659.from_port:                 "22" => "22"
    ingress.1653617659.protocol:                  "tcp" => "tcp"
    ingress.1653617659.security_groups.#:         "1" => "1"
    ingress.1653617659.security_groups.435530925: "sg-e994088d" => "sg-e994088d"
    ingress.1653617659.self:                      "0" => "0"
    ingress.1653617659.to_port:                   "22" => "22"
    ingress.2776169082.cidr_blocks.#:             "0" => "7"
    ingress.2776169082.cidr_blocks.0:             "" => "10.1.169.18/32"
    ingress.2776169082.cidr_blocks.1:             "" => "10.246.10.28/32"
    ingress.2776169082.cidr_blocks.2:             "" => "10.144.212.0/22"
    ingress.2776169082.cidr_blocks.3:             "" => "10.144.10.0/23"
    ingress.2776169082.cidr_blocks.4:             "" => "10.145.0.0/16"
    ingress.2776169082.cidr_blocks.5:             "" => "10.160.4.0/22"
    ingress.2776169082.cidr_blocks.6:             "" => "10.165.120.0/21"
    ingress.2776169082.from_port:                 "" => "80"
    ingress.2776169082.protocol:                  "" => "tcp"
    ingress.2776169082.security_groups.#:         "0" => "0"
    ingress.2776169082.self:                      "" => "0"
    ingress.2776169082.to_port:                   "" => "80"
    ingress.3010030872.cidr_blocks.#:             "1" => "1"
    ingress.3010030872.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.3010030872.from_port:                 "8300" => "8300"
    ingress.3010030872.protocol:                  "udp" => "udp"
    ingress.3010030872.security_groups.#:         "0" => "0"
    ingress.3010030872.self:                      "0" => "0"
    ingress.3010030872.to_port:                   "8302" => "8302"
    ingress.305373375.cidr_blocks.#:              "1" => "1"
    ingress.305373375.cidr_blocks.0:              "172.20.0.0/20" => "172.20.0.0/20"
    ingress.305373375.from_port:                  "9300" => "9300"
    ingress.305373375.protocol:                   "tcp" => "tcp"
    ingress.305373375.security_groups.#:          "0" => "0"
    ingress.305373375.self:                       "0" => "0"
    ingress.305373375.to_port:                    "9400" => "9400"
    ingress.3152347560.cidr_blocks.#:             "1" => "1"
    ingress.3152347560.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.3152347560.from_port:                 "8600" => "8600"
    ingress.3152347560.protocol:                  "tcp" => "tcp"
    ingress.3152347560.security_groups.#:         "0" => "0"
    ingress.3152347560.self:                      "0" => "0"
    ingress.3152347560.to_port:                   "8600" => "8600"
    ingress.3377973165.cidr_blocks.#:             "1" => "1"
    ingress.3377973165.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.3377973165.from_port:                 "5959" => "5959"
    ingress.3377973165.protocol:                  "tcp" => "tcp"
    ingress.3377973165.security_groups.#:         "0" => "0"
    ingress.3377973165.self:                      "0" => "0"
    ingress.3377973165.to_port:                   "5959" => "5959"
    ingress.3580615284.cidr_blocks.#:             "1" => "1"
    ingress.3580615284.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.3580615284.from_port:                 "8400" => "8400"
    ingress.3580615284.protocol:                  "tcp" => "tcp"
    ingress.3580615284.security_groups.#:         "0" => "0"
    ingress.3580615284.self:                      "0" => "0"
    ingress.3580615284.to_port:                   "8400" => "8400"
    ingress.3794581402.cidr_blocks.#:             "1" => "1"
    ingress.3794581402.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.3794581402.from_port:                 "8500" => "8500"
    ingress.3794581402.protocol:                  "tcp" => "tcp"
    ingress.3794581402.security_groups.#:         "0" => "0"
    ingress.3794581402.self:                      "0" => "0"
    ingress.3794581402.to_port:                   "8500" => "8500"
    ingress.3955283681.cidr_blocks.#:             "1" => "1"
    ingress.3955283681.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.3955283681.from_port:                 "6379" => "6379"
    ingress.3955283681.protocol:                  "tcp" => "tcp"
    ingress.3955283681.security_groups.#:         "0" => "0"
    ingress.3955283681.self:                      "0" => "0"
    ingress.3955283681.to_port:                   "6379" => "6379"
    ingress.4018051094.cidr_blocks.#:             "1" => "1"
    ingress.4018051094.cidr_blocks.0:             "172.20.0.0/20" => "172.20.0.0/20"
    ingress.4018051094.from_port:                 "2003" => "2003"
    ingress.4018051094.protocol:                  "tcp" => "tcp"
    ingress.4018051094.security_groups.#:         "0" => "0"
    ingress.4018051094.self:                      "0" => "0"
    ingress.4018051094.to_port:                   "2004" => "2004"
    ingress.417490335.cidr_blocks.#:              "1" => "1"
    ingress.417490335.cidr_blocks.0:              "172.20.0.0/20" => "172.20.0.0/20"
    ingress.417490335.from_port:                  "2003" => "2003"
    ingress.417490335.protocol:                   "udp" => "udp"
    ingress.417490335.security_groups.#:          "0" => "0"
    ingress.417490335.self:                       "0" => "0"
    ingress.417490335.to_port:                    "2004" => "2004"
    ingress.561856002.cidr_blocks.#:              "1" => "1"
    ingress.561856002.cidr_blocks.0:              "172.20.0.0/20" => "172.20.0.0/20"
    ingress.561856002.from_port:                  "9200" => "9200"
    ingress.561856002.protocol:                   "tcp" => "tcp"
    ingress.561856002.security_groups.#:          "0" => "0"
    ingress.561856002.self:                       "0" => "0"
    ingress.561856002.to_port:                    "9200" => "9200"
    ingress.586622973.cidr_blocks.#:              "1" => "1"
    ingress.586622973.cidr_blocks.0:              "172.20.0.0/20" => "172.20.0.0/20"
    ingress.586622973.from_port:                  "8400" => "8400"
    ingress.586622973.protocol:                   "udp" => "udp"
    ingress.586622973.security_groups.#:          "0" => "0"
    ingress.586622973.self:                       "0" => "0"
    ingress.586622973.to_port:                    "8400" => "8400"
    ingress.628273628.cidr_blocks.#:              "7" => "7"
    ingress.628273628.cidr_blocks.0:              "10.1.169.18/32" => "10.1.169.18/32"
    ingress.628273628.cidr_blocks.1:              "10.246.10.28/32" => "10.246.10.28/32"
    ingress.628273628.cidr_blocks.2:              "10.144.212.0/22" => "10.144.212.0/22"
    ingress.628273628.cidr_blocks.3:              "10.144.10.0/23" => "10.144.10.0/23"
    ingress.628273628.cidr_blocks.4:              "10.145.0.0/16" => "10.145.0.0/16"
    ingress.628273628.cidr_blocks.5:              "10.160.4.0/22" => "10.160.4.0/22"
    ingress.628273628.cidr_blocks.6:              "10.165.120.0/21" => "10.165.120.0/21"
    ingress.628273628.from_port:                  "443" => "443"
    ingress.628273628.protocol:                   "tcp" => "tcp"
    ingress.628273628.security_groups.#:          "0" => "0"
    ingress.628273628.self:                       "0" => "0"
    ingress.628273628.to_port:                    "443" => "443"

The only thing actually changed is this:
    ingress.#:                                    "16" => "17"
    ingress.2776169082.cidr_blocks.#:             "0" => "7"
    ingress.2776169082.cidr_blocks.0:             "" => "10.1.169.18/32"
    ingress.2776169082.cidr_blocks.1:             "" => "10.246.10.28/32"
    ingress.2776169082.cidr_blocks.2:             "" => "10.144.212.0/22"
    ingress.2776169082.cidr_blocks.3:             "" => "10.144.10.0/23"
    ingress.2776169082.cidr_blocks.4:             "" => "10.145.0.0/16"
    ingress.2776169082.cidr_blocks.5:             "" => "10.160.4.0/22"
    ingress.2776169082.cidr_blocks.6:             "" => "10.165.120.0/21"
    ingress.2776169082.from_port:                 "" => "80"
    ingress.2776169082.protocol:                  "" => "tcp"
    ingress.2776169082.security_groups.#:         "0" => "0"
    ingress.2776169082.self:                      "" => "0"
    ingress.2776169082.to_port:                   "" => "80"

So why is the output so busy?

**Comment by mitchellh** [comment]
This is because this is a set, and by adding elements or changing ports you're changing the hash code (which is that crazy number). We have plans to add real typing to the core, when we do that this sort of thing should become easier. Until then, its not incorrect, just verbose.
