### ISSUE TITLE
Unable to pass an empty list to a module

### ISSUE THREAD

**Issue by svend** [hashicorp/terraform#1720]
I am using a string variable combined with split() pass lists to a module. The empty string splits to an array containing an empty string, so there is no way for the user of the module to specify an empty list.

[This](https://github.com/terraform-community-modules/tf_aws_nat/blob/2f8ba62636a5b413250f7952f44159a426933631/main.tf#L15) is similar to what I am doing.

**Comment by mitchellh** [comment]
Going to close this as a dup of #2240. I know thats newer, but there is activity there as well as work being done to fix it.

**Comment by svend** [comment]
That appears to be a different issue. #2240 was about split on a string that does not contain a delimiter returning a string instead of an array.

My issue is that split on an empty string returns an one item array containing an empty string. I need a way to pass an empty list into a module.

```
output "length" {
        value = "${length(split(",", ""))}"
}
```

```
terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

  length = 1
```

**Comment by radeksimko** [comment]
@svend I believe https://github.com/hashicorp/terraform/pull/2973 is solving that problem.

**Comment by svend** [comment]
@radeksimko Thanks, I'll watch that PR.

**Comment by jmehnle** [comment]
@mitchellh, this should not be closed, since it's not a duplicate of #2240 as @svend points out.

**Comment by maxrothman** [comment]
This bug seems to have re-appeared in v0.8.5. Can it be re-opened?

**Comment by maxrothman** [comment]
Ping @mitchellh @radeksimko

**Comment by apparentlymart** [comment]
@maxrothman given how old this issue is, it seems unlikely that exactly this problem has arisen again, but I don't doubt that something similar could have arisen.

Would you mind opening a new issue with some details on what you're seeing? Some up-to-date repro steps against v0.8.5 would make it more likely that someone on the Terraform team would be able to track down and fix the issue you're seeing.

**Comment by beanaroo** [comment]
I have opened a possibly relevant issue.

**Comment by maxrothman** [comment]
FWIW the resolution of the original PR was to encourage users to use the [`compact` interpolation function](https://www.terraform.io/docs/configuration/interpolation.html#compact_list_), and that otherwise, this was intended behavior.

**Comment by beanaroo** [comment]
Thank you, @maxrothman!

**Comment by bam0382** [comment]
The other thing is `[""]` is a length of 1 while `[]` is a length of 0.
