### ISSUE TITLE
terraform does not create lock during `terraform import`

### ISSUE THREAD

**Issue by dev-dull** [hashicorp/terraform#17202]
### Terraform Version
tested `11.1` with vsphere v1.2.0
tested `11.2` with digitalocean v0.1.3 

### Expected Behavior
Because `terraform import val1 val2` will update the tfstate file, the command should create and hold a lock until the import is complete, my concern being that two processes could try to update the state at the same time if one of them is not checking for a lock.

### Actual Behavior
The terraform.tfstate is being updated without any locking being performed during an import.

### Steps to Reproduce
found while doing:
`terraform import module.bounce01.vsphere_virtual_machine.vm "/CoSentry Midlands/vm/eint1v-bounce01"`

confirmed with:
`terraform import digitalocean_droplet.web 12345678`

### Additional Context
vsphere provider with an HTTP (PyTerraBackTYL + Git) backend. 
DigitalOcean provider using local disk for backend.

**Comment by mildwonkey** [comment]
This should be fixed in v0.13, so I am going to close this. If you are still seeing this problem in terraform v0.13, please open a new issue and fill out the template.
Thanks!
