### ISSUE TITLE
Error reading state: State version 3 not supported, please update.

### ISSUE THREAD

**Issue by segfaultnyc** [hashicorp/terraform#17210]
### Terraform Version

```
terraform -v
Terraform v0.11.2

1. Terraform init -backend=true -backend-config=key=my_key  \
                                                      -backend-config=bucket=my_bucket \
                                                       -backend-config=region-my_region
2. Terraform apply

Initialization is a success and connects to s3 , may main.tf has: 

 terraform { 
        backend "s3" {}
}
The apply is also a success but when I run : terraform output VAR_NAME , I get 
   Error reading state: State version 3 not supported, please update
...
```

### Terraform Configuration Files

```hcl
"version": 3,
    "terraform_version": "0.11.2",
    "serial": 1,
    "lineage": "b656e8bb-dd3c-48e7-b960-77725a120dee",
    "modules": [
        {
            "path": [
                "root"
            ],
Notice how s3 is not in the backend config and basically the whole backend config sections is missing. The file exists in s3 which is the confusing part.
```

### Crash Output

"Error reading state: State version 3 not supported, please update."

### Expected Behavior

I run "terraform output VAR_NAME" and should give me back the var value in the state file. Instead it errors out stating "State version 3 not supported"

### Actual Behavior

Received "Error reading state: State version 3 not supported, please update." When trying to get output value from state file.

### Steps to Reproduce

1.   Terraform apply -input=false  -auto-approve

**Comment by jbardin** [comment]
Hi @segfaultnyc,

Are you running these commands from different environments?

You must be executing a different terraform binary, because the state version has been 3 for a very long time. That error message also looks old, as that text is not present in any recent releases. 

Please check the version of terraform where you're running the output command.

**Comment by jbardin** [comment]
Closing as the current version of Terraform cannot produce this output.
