### ISSUE TITLE
many instances of a module (git) download from git each time

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#17226]
Terraform 0.11.1

I have a submodule which I instantiate several times e.g.:

```
module "foo_a" {
    source  = "git::ssh://git@bitbucket.org/mycompany/ha_asg.git"
}

module "foo_b" {
    source  = "git::ssh://git@bitbucket.org/mycompany/ha_asg.git"
}

module "foo_c" {
    source  = "git::ssh://git@bitbucket.org/mycompany/ha_asg.git"
}
```

Disappointingly when I run terraform init, this is very slow because for each of foo_a, foo_b, foo_c, etc. - terraform downloads the whole git source again. Can't it instead work out that it needs that source once, and download it once? 

I run a terraform init on each terraform command, so the slowness is exacerbated a bit. 

Thanks!

**Comment by leftathome** [comment]
If you are using CI and make heavy use of modules, this adds a lot of time to each deploy.  (Even if you do cache `WORKING_DIRECTORY/.terraform/modules`, which can sometimes present its own set of problems...)

**Comment by apparentlymart** [comment]
Hi @gtmtech! Thanks for reporting this.

This seems to be the same thing being discussed over in #11435, so I'm going to close this just to consolidate the discussion over there.
