### ISSUE TITLE
integrate terraform in Go code

### ISSUE THREAD

**Issue by runzexia** [hashicorp/terraform#17236]
Hi :
I would like to integrate terraform in my Go code. What do you recommend for implementation in general? 
Any help would be really appreciated.

**Comment by jbardin** [comment]
Hi @runzexia,

If you're asking about using terraform as a library, Terraform right now is not aimed to be used as such. It is open source, and you are perfectly free to use it as a library, but we do not guarantee the stability of any internal APIs.

If you're looking to write a provider, the documentation of [Writing Custom Providers](https://www.terraform.io/guides/writing-custom-terraform-providers.html) is a good place to start, as well as taking a look at some of the smaller providers already available.

**Comment by runzexia** [comment]
I‘m making cross-cloud PaaS framework, using terraform to manage resources is a good choice.But if I communicate directly with the CLT, it will be more complicated.So i want to integrate terraform in my Go code

**Comment by jbardin** [comment]
The recommended way to automate terraform is to run it through the CLI. There is no stable API for terraform other than the plugin interfaces, so while integrating it as a library is possible, it's not recommended.
