### ISSUE TITLE
Error Creating Autoscaling Scheduled Action

### ISSUE THREAD

**Issue by asaldalop** [hashicorp/terraform#17238]
### Terraform Version

```
Terraform v0.11.1
provider.aws v1.8.0
```

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "my_asg" {
  availability_zones        = ["us-east-1a"]
  name                      = "my-asg"
  launch_configuration      = "${aws_launch_configuration.my_lc.name}"
  termination_policies      = ["OldestInstance", "OldestLaunchConfiguration", "Default"]
  desired_capacity          = "${var.desired_capacity}"
  min_size                  = "${var.min_size}"
  max_size                  = "${var.max_size}"
  wait_for_capacity_timeout = "0"
  
  lifecycle {
    create_before_destroy = true
  }

  tag {
    key                 = "Name"
    value               = "my-asg"
    propagate_at_launch = true
  }
}

resource "aws_autoscaling_schedule" "daily_increment" {
  scheduled_action_name  = "daily-increment"
  min_size               = "${var.min_size}"
  max_size               = "${var.max_size}"
  desired_capacity       = "${var.desired_capacity + 1}"
  recurrence             = "0 8 * * 1-5"
  autoscaling_group_name = "${aws_autoscaling_group.my_asg.name}"
}
```

### Debug Output

* aws_autoscaling_schedule.daily_increment: Error Creating Autoscaling Scheduled Action: ValidationError: AutoScalingGroup name not found - null
	status code: 400, request id: 8bad7758-05b9-11e8-90f0-19064ec11da8

### Expected Behavior

With this configuration should be created a new schedule for an existing Auto Scaling Group
### Actual Behavior

Although I tried to use name and ARN in `autoscaling_group_name` inside `aws_autoscaling_schedule` resource it seems that cannot create a new schedule action for the autoscaling group.

### References

The only reference I found is this -> https://github.com/hashicorp/terraform/issues/5900

**Comment by conorgil** [comment]
I just ran into this same exact problem. Did you close this because you fixed it somehow? What worked for you?
