### ISSUE TITLE
AWS ECS cluster creation API is missing attributes

### ISSUE THREAD

**Issue by harshi93** [hashicorp/terraform#17242]
### Terraform Version

```
0.11.2
```

### Terraform Configuration Files

```hcl
resource "aws_ecs_cluster" "foo" {
  name = "white-hart"
}
```
I haven't actually ran the code, but i believe even though the code will work. It will be useless, the reason being, I have been operating with AWS ECS quite extensively at console level and in my experience if you don't define number of container instances, there will be no containers to run the services moreover there are no option to define following attributes which comprise critical components of an ECS cluster definition

1) Provisioning Model
2) Instance Type
3) Number of Instances
4) EBS Storage
5) Key Pair (Needed to communicate with EC2 Instance)
6) VPC
7) CIDR Block
8) Subnets
9) Security Groups 
10) Security Group Inbound Rules
- CIDR Block 
- Port
11) Container Instance IAM Role

I request you to look into it. And update the documentation 

Also, If there are behind the scenes configuration and assumptions, it would be really helpful if you  could update the website with the same

**Comment by harshi93** [comment]
Additionally, I would like to bring it to your notice that even if you create a cluster there is no way you can add an instance to the cluster externally. I was looking into cloudformation and found out that eventhough your cluster creation api is similar to cloudformation api for creating cluster. Cloudformation does provides a function called "join" to support joining of instances launched separately

**Comment by endofcake** [comment]
You join to the cluster by adding this to userdata:
```
#!/bin/bash
echo ECS_CLUSTER=your_cluster_name >> /etc/ecs/ecs.config
```
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html

The attributes that you mention are not properties of the ECS cluster
