### ISSUE TITLE
RDS: Error creating DB Subnet Group: DBSubnetGroupDoesNotCoverEnoughAZs:

### ISSUE THREAD

**Issue by abacao** [hashicorp/terraform#17257]
Hello,

Running terraform for windows 64 within Bash for Windows 10 (Ubuntu 16.04)
I have download terraform 0.11.2 (but this is what i get)

`terraform -v
Terraform v0.11.1
+ provider.aws v1.8.0
+ provider.null v1.0.0`

I'm using the following code:
>resource "aws_db_subnet_group" "default" {
>  name = "main-subnet-grp_${var.environment}"
>
>  subnet_ids = [
 >   "${aws_subnet.private.id}",
 >   "${aws_subnet.public.id}",
 > ]
>}

Sometimes I get a error when running the 1st apply

> Error: Error applying plan:
>1 error(s) occurred:
>* aws_db_subnet_group.default: 1 error(s) occurred:
>* aws_db_subnet_group.default: Error creating DB Subnet Group: >DBSubnetGroupDoesNotCoverEnoughAZs: DB Subnet Group doesn't meet availability zone coverage >requirement. Please add subnets to cover at least 2 availability zones. Current coverage: 1
>        status code: 400, request id: 2f13befd-1627-4c62-aa8c-bffa591323d1

To correct this what I do is simply destroy and apply again. Sometimes it passes, sometimes I have to repeat.

What am I missing here?

**Comment by tonygyerr** [comment]
@abacao was getting the same error and no longer get it.  My code is referenced below:

/*
 database subnet private
*/

resource "aws_subnet" "db_subnet_prv" {
  count                   = "${var.amount_private_db_subnets}" 
  cidr_block              = "${cidrsubnet(var.base_cidr_prv, ceil(log(var.max_subnets_prv, var.newbits_prv)), (var.netnum_private_db + count.index))}"
  vpc_id                  = "${aws_vpc.app-nonprd-east-vpc.id}"
  availability_zone       = "${data.aws_availability_zones.main.names[count.index]}"
  map_public_ip_on_launch = false

  tags {
    Name = "${var.tags["Name"]}-db-prv-${count.index}-subnet"
  }
}


resource "aws_db_subnet_group" "userdb_subnet_group" {
  name                    = "userdb_subnet_group"
  description             = "user db subnet group"
  subnet_ids              = ["${aws_subnet.db_subnet_prv.*.id}"]
}



/*
 availability zones data template
*/
data "aws_availability_zones" "main" {}


/*
 variables
*/

variable "tags" {
  type        = "map"
  description = "optional tags"

  default = {
    Name       = "app-nonprd"
    Owner      = "cloudops@forthewin.com"
    CostCenter = "N/A"
    vpc        = "app-nonprd-east-vpc"
    env        = "nonprd"
    project    = "app"
  }
}

variable "base_cidr" {
  description = "cidr for vpc" #this variable is utilized in the locals.tf
  type        = "string"
  default     = "10.0.0.0/16"
}

variable "max_subnets" {
  description = "Maximum number of subnets which can be created for CIDR blocks calculation. Default to length of `names` argument"
  default     = "12"
}

variable "netnum_private_db" {
  type    = "string"
  default = "9"
}

variable "amount_private_db_subnets" {
  type    = "string"
  default = "3"
}
