### ISSUE TITLE
Terraform crash on "terraform refresh"

### ISSUE THREAD

**Issue by chan-alex** [hashicorp/terraform#17276]
#### Terraform version ####
terraform --version
Terraform v0.11.2
+ provider.aws v1.8.0

#### Command output ####
terraform refresh
aws_ebs_volume.caevolume: Refreshing state... (ID: vol-0602d584b6aa1c10d)
aws_security_group.XXXXXXX: Refreshing state... (ID: sg-XXXX)
aws_subnet.subnetXXXXXX Refreshing state... (ID: subnet-65017402)
aws_security_group.XXXX: Refreshing state... (ID: sg-XXXXX)
aws_security_group.XXXX: Refreshing state... (ID: sg-XXXXX)
aws_instance.cae: Refreshing state... (ID: i-084bd86142XXXXX)
aws_volume_attachment.ebs_att: Refreshing state... (ID: vai-7385XXXX)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x174a2a2]

goroutine 1322 [running]:
github.com/hashicorp/terraform/terraform.(*State).Lock(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:95 +0x22
github.com/hashicorp/terraform/terraform.(*State).SameLineage(0x0, 0xc4203a1620, 0xc4203cdd00)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:628 +0x34
github.com/hashicorp/terraform/state/remote.(*State).WriteState(0xc4203cdd10, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/state/remote/state.go:37 +0x10a
github.com/hashicorp/terraform/backend/local.(*Local).opRefresh(0xc4208fe000, 0x4ab7ac0, 0xc420012098, 0xc42013b680, 0xc4203cd500)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_refresh.go:115 +0x465
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opRefresh)-fm(0x4ab7ac0, 0xc420012098, 0xc42013b680, 0xc4203cd500)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:230 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc4208fe000, 0xc42041b730, 0xc42041b720, 0x4ab7ac0, 0xc420012098, 0xc42013b680, 0xc4203cd500)
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:254 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:251 +0x18a

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

This is the crash.log file:

[crash.log](https://github.com/hashicorp/terraform/files/1695283/crash.log)

**Comment by jbardin** [comment]
Thanks for filing the issue.
This is fixed in the current release.
