### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by rexzhen** [hashicorp/terraform#17271]
### Terraform Version

```
Terraform v0.11.2
+ provider.aws v1.8.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
...
```

### Actual Behavior

 terraform refresh -var-file="tfvars/dev.tfvars"

got 

data.aws_ecs_task_definition.pancho_task_definition: Refreshing state...
Releasing state lock. This may take a few moments...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x174a2a2]

goroutine 109 [running]:
github.com/hashicorp/terraform/terraform.(*State).Lock(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:95 +0x22
github.com/hashicorp/terraform/terraform.(*State).SameLineage(0x0, 0xc4207b45a0, 0xc4207fa800)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/state.go:628 +0x34
github.com/hashicorp/terraform/state/remote.(*State).WriteState(0xc4207fa8a0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/state/remote/state.go:37 +0x10a
github.com/hashicorp/terraform/backend/local.(*Local).opRefresh(0xc4207d4210, 0x4ab7ac0, 0xc420014088, 0xc4207f4e40, 0xc4207fa870)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend_refresh.go:115 +0x465
github.com/hashicorp/terraform/backend/local.(*Local).(github.com/hashicorp/terraform/backend/local.opRefresh)-fm(0x4ab7ac0, 0xc420014088, 0xc4207f4e40, 0xc4207fa870)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:230 +0x52
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc4207d4210, 0xc4202ef070, 0xc4202ef060, 0x4ab7ac0, 0xc420014088, 0xc4207f4e40, 0xc4207fa870)
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:254 +0x9a
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
	/opt/gopath/src/github.com/hashicorp/terraform/backend/local/backend.go:251 +0x18a

**Comment by jbardin** [comment]
Thanks for filing the issue!

This is fixed in the latest release.
