### ISSUE TITLE
aws_instance.example: Error launching source instance: AuthFailure: AWS was not able to validate the provided access credentials 	status code: 401, request id: fdf5b8cd-bd67-4c0c-a430-1e551735fb19

### ISSUE THREAD

**Issue by saumik8763** [hashicorp/terraform#17273]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by jbardin** [comment]
Hi @saumik8763,

This looks like it has something to so with the aws provider, but you haven't included any information about the issue. 

If have have more information, we can re-open in the aws provider repo.
