### ISSUE TITLE
do not destroy vpc elb while changing security group association

### ISSUE THREAD

**Issue by alekseymykhailov** [hashicorp/terraform#1728]
association or disassociating security group on VPC ELB should not destroy it. AWS allows to do this on existent ELB

**Comment by catsby** [comment]
Hello – do you have an example configuration (with any secrets omitted) that demonstrates this? Unless I'm misunderstanding the issue you're reporting, changing a security group on an ELB should not destroy the resource: 

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elb.go#L61-L69

**Comment by alekseymykhailov** [comment]
``` 
resource "aws_elb" "test_elb" {
        name      = "test_elb"
        instances = ["${aws_instance.web.*.id}"]
        subnets   = ["${aws_subnet.dev_web_us-east-1c.id}"]
        security_groups = [ 
                 "${aws_security_group.dev_web.id}",
                 "${aws_security_group.dev_vpn.id}"
        ]
        listener {
	        instance_port = 80
	        instance_protocol = "http"
	        lb_port = 80
	        lb_protocol = "http"
        }
        health_check {
                healthy_threshold = 2
                unhealthy_threshold = 2
                timeout = 3
                target = "HTTP:80/"
                interval = 15
  	}

}
```

if I remove security group from array `security_groups` ,  ``terraform plan``  say:

```
    security_groups.#:                           "2" => "1" (forces new resource)
    security_groups.158865267:                   "sg-XXXX" => "sg-XXX" (forces new resource)
```

and destroy/create new elb resource on ``apply``

**Comment by catsby** [comment]
My apologies, it seems I was checking this on the `master` branch, which recently received a pull request to make these changes in-place, instead of forcing a new resource:

- [provider/aws: update elb security groups in-place](https://github.com/hashicorp/terraform/pull/1662)

The good news is that this will be out in the next release, which I believe is just around the corner! 

Sorry for the trouble.

**Comment by alekseymykhailov** [comment]
Sorry, didn't see that

thank you!
