### ISSUE TITLE
windows 10 terraform init cannot import modules

### ISSUE THREAD

**Issue by sdnshakya** [hashicorp/terraform#17281]
Hi,

I recently updated my OS from windows 7 to 10 pro at my work. My scripts work fine everywhere except for on my laptop.
I get the following error

` Error downloading modules: Error loading modules: error downloading 'file://c:/path/to/modules
': failed to run mklink .terraform\modules\b571284e9ec052dbb3f56e5cee0f6674 C:\path\to\modules: exit status 1 "The system cannot find the path specified.\r\n"`

When i checked, the files are available in the given path but still doesn;t work. I saw previous issues where terraform init was an issue with the windows previlege to run the symblink, so I even tried using the command prompt as an administrator, it still doesn't work.

**Comment by rorychatt** [comment]
I've had this issue in the past.

In my case, the org which I worked had the following registry key set, causing powershell/bash to reload the home path to H:\ on each new process/app instantiation.

Have a look to see whether ```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\AutoRun``` is set.

**Comment by sdnshakya** [comment]
It is set. Do I need to remove/delete it?

**Comment by rorychatt** [comment]
Correct. That said - your organisation is likely applying this setting with Group Policy, meaning it will probably come back soon after deletion.

Best to raise a ticket with your end user computing team to find out why and get you exempt from the policy.

It's normally the result of some sort of legacy app where it doesn't know how to honor a home path environment var. 

With that in mind, you should be OK to close this ticket as it is not a Terraform issue,.

**Comment by sdnshakya** [comment]
Thank you @rorychatt !
