### ISSUE TITLE
aborting a long running terraform apply operation results in empty state file

### ISSUE THREAD

**Issue by matti** [hashicorp/terraform#17282]
### Terraform Version
```
0.11.3
```

### Terraform Configuration Files
```hcl
module "testing" {
  source = "github.com/matti/terraform-google-kubernetes-engine"

  settings = {
    region_name            = "europe-west1"
    zone_amount            = 1
    cluster_name           = "tf-testing"
    gke_min_master_version = "1.8.6-gke.0"
  }
}

# ------------ nodepool
locals {
  node_pool_common_settings = {
    cluster_name = "${module.testing.cluster_name}"
    cluster_zone = "${module.testing.cluster_zone}"

    machine_type = "n1-highcpu-4"
  }

  node_pool_default_settings = {
    name       = "default"
    node_count = 1
  }

  node_pool_scaling_settings = {
    name = "scaling"

    autoscaling_min_node_count = 0
    autoscaling_max_node_count = 3
  }
}

module "testing_node_pool" {
  source = "github.com/matti/terraform-google-kubernetes-node-pool"

  settings = "${merge(local.node_pool_common_settings, local.node_pool_default_settings)}"
}

module "testing_node_pool_autoscale" {
  source = "github.com/matti/terraform-google-kubernetes-node-pool"

  settings = "${merge(local.node_pool_common_settings, local.node_pool_scaling_settings)}"
}

```

### Debug Output
I've made a repository that can be used to repro, it also contains trace: https://github.com/matti/terraform-repro-abort-empties-state

### Expected Behavior
When the operation runs extremely long (and prob won't complete) I've hit `^C` that prints out "Please wait for Terraform to exit or data loss may occur." - then after waiting some more I'm hitting `^C` again. I don't think that the state file should not be empty after this.

### Actual Behavior
State file is empty. Needs to restore from the backup.

### Steps to Reproduce

I've made a repository that can be used to repro: https://github.com/matti/terraform-repro-abort-empties-state

This happens after the `google_container_cluster` and `google_container_node_pool` has been created. To repro this (100% success rate in my ~7 tests):

1. Apply and wait for cluster and node pool to be created
2. Change the number of nodes in google_container_node_pool or add a new node_pool
3. Run apply again and let it run for couple of minutes and then ^C that forcefully.
4. The state file is empty

Faster alternative:
1. Apply and wait, hit ^C, hit ^C
2. State file is empty, backup contains the initial state

### References
- https://github.com/terraform-providers/terraform-provider-google/issues/982#issuecomment-363251879
- https://github.com/hashicorp/terraform/issues/17066

**Comment by jbardin** [comment]
Hi @matti,

Thanks for the reproduction case. Unfortunately I'm not able to reproduce this locally, and I'm not able to get your example to run correctly yet (though that is probably just inexperience with this provider on my part). The Google provider shouldn't be able to do anything specific on its own to cause the state to be empty, but my initial attempts at recreating this with a test provider never truncate the state to 0 bytes. 

While I wrangle with my test account credentials, could you let me know what you mean by an "empty" state file? Does the state file contain a basic JSON structure but with no resource data, or is it completely empty file containing 0 bytes?

**Comment by matti** [comment]
Completely empty containing 0 bytes.
