### ISSUE TITLE
Locking For etcd Backend

### ISSUE THREAD

**Issue by samcgardner** [hashicorp/terraform#17299]
As of etcd 3.2 (https://coreos.com/blog/etcd-3.2-announcement) etcd now supports distributed locking. This means that a lock implementation for Terraform's etcd backend is now feasible. Given that locking for state is quite important, is this a feature you'd be interested in? I'm happy to provide a PR.

**Comment by jbardin** [comment]
Hi @samcgardner,

Thanks for filing the issue.

The legacy `etcd` remote state in terraform, isn't really capable of supporting locks at all, but we do have a new `etcdv3` backend for the newer versions of etcd. 

However, I do see that the `etcdv3` backend is missing from the site docs, we we'll get that up and running ASAP. 

Thanks!

**Comment by samcgardner** [comment]
Hi James, thanks for getting back to me! It might be worth updating the page at https://www.terraform.io/docs/backends/types/etcd.html to say that it's legacy and doesn't use more recent versions of etcd in that case.
