### ISSUE TITLE
Encryption at Rest for DynamoDB

### ISSUE THREAD

**Issue by sailesm** [hashicorp/terraform#17308]
Encryption at Rest for DynamoDB was made available in a number of regions yesterday.

It would be great to have support for this in Terraform.

https://aws.amazon.com/blogs/aws/new-encryption-at-rest-for-dynamodb/

Thanks

**Comment by ewbankkit** [comment]
Duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/3298.
