### ISSUE TITLE
Manta backend does not create path and lock fails

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#17314]
The [Manta backend](https://www.terraform.io/docs/backends/types/manta.html) does not create the state path as described in the [docs](https://www.terraform.io/docs/backends/types/manta.html#path) and the state lock fails every time if the lock file does not exist.

### Terraform Version
```
tf-manta-state $ terraform version -v
Terraform v0.11.3
+ provider.triton v0.4.1
```

### Terraform Configuration Files
```hcl
terraform {
  backend "manta" {
    path       = "terraform-modules/state-test"
    objectName = "terraform.tfstate"
  }
}

resource "triton_firewall_rule" "block" {
  rule        = "FROM any TO all vms ALLOW tcp PORT 22"
  enabled     = false
}
```

### Regular Output
https://gist.github.com/clstokes/1759ee75a1e0ced2243f917a9ceeeddc

### Expected Behavior
1. Expect the Manta backend to create the path in the backend definition.
1. Expect the Manta backend to successfully lock on each apply, destroy, etc.

### Actual Behavior
1. Terraform fails if the path doesn't already exist.
1. Terraform fails if the tflock file doesn't exist (which would mean it's locked?)

### Steps to Reproduce
1. terraform init
1. terraform apply
    - apply should fail with DirectoryDoesNotExist error
1. _create the path_
1. terraform apply
    - apply should fail with ResourceNotFound error

**Comment by sean-** [comment]
CC @stack72
