### ISSUE TITLE
CHECKPOINT_DISABLE Is Ignored For Plugin Downloads

### ISSUE THREAD

**Issue by gwellington** [hashicorp/terraform#17310]
### Terraform Version

```
0.10.8 
```

### Expected Behavior

When the `CHECKPOINT_DISABLE` flag is set, Terraform should not attempt to reach out to Hashicorp provided services in an attempt to validate plugins/providers when the repository has already been initialized. 

### Actual Behavior

Terraform still attempts to download checksums to validate providers/plugins from `releases.hashicorp.com` and produces this error: Error installing provider "terraform": error fetching checksums: Get https://releases.hashicorp.com/terraform-provider-terraform/1.0.2/terraform-provider-terraform_1.0.2_SHA256SUMS: EOF.

### Steps to Reproduce

CHECKPOINT_DISABLE=1 terraform init

### Additional Context

In this case, it leaves a hard dependency on `releases.hashicorp.com` being accessible for Terraform runs to occur -- such as the case of Fastly having connectivity issues on 2/9/2018 causing subsequent terraform runs to fail.

**Comment by jbardin** [comment]
Hi @gwellington,

The `CHECKPOINT_DISABLE` variable is specifically only for the checkpoint function, as some users prefer not to run it for various reasons. It's not intended to prevent access to other external resources.

That said, the plugin discovery process is designed to be able to work in, and is often used in networks without any external internet access, and does not try to fetch plugins that are already locally available if the configuration constraints are satisfied. 

Can you provide a sample configuration which exhibits this behavior with a current terraform release?

**Comment by gwellington** [comment]
Hey @jbardin 

For this particular issue, we encountered the  problem with Terraform Enterprise (TFE) upon init.  For various reason, we do not bundle the plugins with the "Tools" in TFE and rely on Terraform to pull down the providers as necessary.  

In this case, Hashicorp experienced service degradation due to issues between AWS and Fastly which prevented 'releases.hashicorp.com' from being hit which effectively took our environment down for 20 hours or so.  It would have been nice to disable the external dependecy on
