### ISSUE TITLE
How to extract data from a list of maps

### ISSUE THREAD

**Issue by daveadams** [hashicorp/terraform#17315]
I'm guessing this is a duplicate in some sense, but I'm not sure how to search for exactly the issue I am having with the interpolation language, and perhaps this is more relevant since it relates to attributes of an official provider's resources.

I was very pleased to see the aws_acm_certificate and aws_acm_certificate_validation resources added to the AWS provider in version 1.9. Now in seeking to implement this, I can make it work fine with a single DNS name on the certificate, as per the example at https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html.

That example works great, but as you can see, the aws_acm_certificate resource has a domain_validation_options output that is a list of maps, and the resource that creates a DNS record to allow DNS validation hardcodes ".0" to index the first element in those single-element lists in the example.

My use case requires using subject alternative names, and that in turn requires multiple DNS records, and the `domain_validation_options` property on the `aws_acm_certificate` resource is complicated. Here's some example code:

    resource "aws_acm_certificate" "cert" {
      domain_name = "myname.example.com"
      subject_alternative_names = [
        "my-alt-name.example.com",
        "my-other-name.example.com",
      ]
      validation_method = "DNS"
    }

    output "validation-options" {
      value = "${aws_acm_certificate.cert.domain_validation_options}"
    }

This results in this output:

    validation-options = [
        {
            domain_name = myname.example.com,
            resource_record_name = _8b1eece1bd9eb24c465d20ee5e902e34.myname.example.com.,
            resource_record_type = CNAME,
            resource_record_value = _7fcc0e9fce650cfc93cf84e9b3afa0a8.acm-validations.aws.
        },
        {
            domain_name = my-alt-name.example.com,
            resource_record_name = _117f0bed1655685f817791a0d446fbaf.my-alt-name.example.com.,
            resource_record_type = CNAME,
            resource_record_value = _eae8c229110499e4c535fde67c6cd8c0.acm-validations.aws.
        },
        {
            domain_name = my-other-name.example.com,
            resource_record_name = _456f43b3eacb2496165b136bda0f47db.my-other-name.example.com.,
            resource_record_type = CNAME,
            resource_record_value = _61efde25808a9a12bbd24ac29ca0308c.acm-validations.aws.
        }
    ]

Fair enough. But then I am stuck at how to create those three records. My first instinct is to treat this property like a multi-instance resource, and do something like:

    resource "aws_route53_record" "cert_validation" {
      count = "${length(aws_acm_certificate.cert.domain_validation_options)}"
      name    = "${element(aws_acm_certificate.cert.domain_validation_options.*.resource_record_name, count.index)}"
      type    = "${element(aws_acm_certificate.cert.domain_validation_options.*.resource_record_type, count.index)}"
      records = ["${element(aws_acm_certificate.cert.domain_validation_options.*.resource_record_value, count.index)}"]
      zone_id = "${data.aws_route53_zone.zone.id}"
      ttl     = 300
    }

But that gives me an error: "value of 'count' cannot be computed"

If I tweak things around or even hardcode "count" to the correct value, then I get errors like: "Resource 'aws_acm_certificate.cert' does not have attribute 'domain_validation_options.*.resource_record_type'".

I've tried using locals as interstitial calculators, but I can't figure out how to get, say, an array of just the `resource_record_name` values, given the `domain_validation_options` structure.

I've tried to find a way using just a hardcoded list of maps in locals, but I cannot seem to find a way to extract the values in such a way that would allow me to solve the problem above. I'm guessing this may be a gap in the interpolation language. But in the meantime, any workaround suggestions are appreciated, as well.

**Comment by daveadams** [comment]
And, I'm running into the same problem with `aws_vpc_endpoint` resources, which have a `dns_entry` attribute that is structured as a list of maps. I need to create records that point to all the `dns_name` keys in each map, but there's no way to pull those out into a list that I can find.

**Comment by mlebbink** [comment]
I think you could use the following code:

`resource "aws_route53_record" "cert_validation" {
  count   = "${length(aws_acm_certificate.cert.domain_validation_options)}"
  name    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_name")}"
  type    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_type")}"
  records = ["${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_value")}"]
  zone_id = "${data.aws_route53_zone.zone.id}"
  ttl     = 300
}`

**Comment by daveadams** [comment]
Great. You are right. I'm not sure what I did wrong before that caused a count failure, but it's working when I use your example code. So thanks.

**Comment by jurajseffer** [comment]
I seem to have tricked it by interpolating input `subject_alternative_names` rather than output `domain_validation_options`, using `count = "${length(aws_acm_certificate.cert.subject_alternative_names)+1}"`. Plus one is to correct for missing `domain_name ` value. This worked when no previous certificate existed.

**Comment by agomezvidalee** [comment]
same error, despite I tried   depends_on = ["aws_acm_certificate.cert"]. I have to apply " terraform apply -target aws_acm_certificate.cert, and then do terraform apply" as daveadams commented before
