### ISSUE TITLE
terraform force-unlock explodes in ParseInt

### ISSUE THREAD

**Issue by matti** [hashicorp/terraform#17328]
Terraform v0.11.3

backend with gcs
```
terraform {
  backend "gcs" {
    bucket = "my-terraform" 
    prefix = "kontena_platform"
  }
}
```

if the lock is stale..
```
Error: Error locking state: Error acquiring the state lock: writing "gs://my-terraform/kontena_platform/dolan.tflock" failed: googleapi: Error 412: Precondition Failed, conditionNotMet
Lock Info:
  ID:        c0f204fa-5887-e159-04f8-329a90cb072a
  Path:
  Operation: OperationTypeApply
  Who:       mpa@mx.local
  Version:   0.11.3
  Created:   2018-02-11 17:33:29.330612 +0000 UTC
  Info:
```
..then force-unlock  doesn't work

```
$ terraform force-unlock -force c0f204fa-5887-e159-04f8-329a90cb072a
Failed to unlock state: strconv.ParseInt: parsing "c0f204fa-5887-e159-04f8-329a90cb072a": invalid syntax
```

**Comment by cristianrgreco** [comment]
Same problem here with Terraform v0.11.3, GCS back-end.

**Comment by jackzampolin** [comment]
Are there any troubleshooting steps here?

**Comment by jbardin** [comment]
Hi @jackzampolin,

What are you attempting to troubleshoot? This issue was closed a while ago.

**Comment by jackzampolin** [comment]
I was able to manually delete the state lock file. Sorry for the noise here 🙊

**Comment by xortim** [comment]
I can confirm the same problem with GCS backend.

`Failed to unlock state: strconv.ParseInt: parsing "[ID]": invalid syntax`

**Comment by jackzampolin** [comment]
@xortim Looks like they have this fixed in master. You can manually delete your lockfile to get around this issue.
