### ISSUE TITLE
How to join instance tag and instance IP in one line

### ISSUE THREAD

**Issue by dragan979** [hashicorp/terraform#17332]
Hi all,

I'm usingTerraform v0.11.3 and want to get output for multiple instances in 

name1:ip address
name2:ip address
name3:ip adress
-------------

i want to join these outputs 
`output "ip" {
    value = "${aws_instance.example.*.public_ip}"
}

output "tag" {
    value = "${aws_instance.example.*.tags.Name}"
}
`

i created below but getting
 name1,
   -,
 ip address
 

 `output "ime" {
   value = ["${aws_instance.example.*.tags.Name}","${aws_instance.example.*.public_ip}"]
}`

**Comment by mildwonkey** [comment]
Take a look at "formatlist".

Here's an untested example (based on something similar I've had to do):

{code}
output "ime" {
  value = "${
      formatlist(
        "%s:%s",
        aws_instance.example.*.tags.Name,
        aws_instance.example.*.public_ip4
      )
    }"
}
{code}
