### ISSUE TITLE
Issue destroying EMR on AWS

### ISSUE THREAD

**Issue by miloup** [hashicorp/terraform#17330]
Hi,

Many of us in many company are facing an issue while trying to destroy an EMR infrastructure on AWS.
The Terraform folder has an **emr-requirements.tf** file which contains Security-Groups, Security-Configuration,...etc. and an **emr.tf** file which creates the cluster using the configuration is the **emr-requirements.tf**

When running "_terraform apply_", the infrastructure is successfully created, but when running "_terraform destroy_", it seems that Terraform does not wait for the EMR cluster to terminate before destroying the remaining resources which leads to a failure (timeout) due to their dependencies to this cluster. The only way to have a clean "destroy" is by making sure that the EMR cluster is terminated (by checking on the AWS console for instance), then run "_terraform destroy_" again. Now, all the remaining resources are destroyed.

Would you please fix this bug?

Thanks

**Comment by catsby** [comment]
Hello @miloup – 

When you mention "The Terraform Folder", are you referring to a folder in github.com/hashicorp/terraform or github.com/terraform-providers/terraform-provider-aws ? If so, could you please provide a direct link? I'm not seeing it.

If you're referring to a folder internal to your company, then I must say that this certainly sounds like an issue in the terraform configuration files themselves, and not in Terraform or the EMR resource(s). 

Terraform relies on interpolation between resources to create the dependency graph. If this is not constructed correctly, there could be issues like the one you describe. If you can share a configuration that reproduces the reported issues (either without exposing any secret information, or by redacting it), we can investigate further.

**Comment by miloup** [comment]
@catsby 
Quick update. I split the destroy into the following:
```
terraform destroy -target "aws_emr_cluster.emr-cluster" -force
terraform destroy -force
```

the output of the first destroy command is as follow:
```
Warning: aws_iam_instance_profile.emr_profile: "roles": [DEPRECATED] Use `role` instead. Only a single role can be passed to an IAM Instance Profile

aws_security_group.emr_slave_sg: Refreshing state... (ID: sg-xxxxx)
aws_iam_role.iam_emr_profile_role: Refreshing state... (ID: XXXXXXXXXXXX)
aws_emr_security_configuration.emr_security_configuration: Refreshing state... (ID: XXXXXXXXXXXX)
aws_security_group.emr_master_sg: Refreshing state... (ID: sg-xxxxx)
aws_security_group.emr_service_access: Refreshing state... (ID: sg-xxxxx)
aws_iam_role.iam_emr_service_role: Refreshing state... (ID: XXXXXXXXXXXX)
aws_iam_instance_profile.emr_profile: Refreshing state... (ID: XXXXXXXXXXXX)
aws_emr_cluster.emr-cluster: Refreshing state... (ID: j-XXXXXXXXXX)
null_resource.master_hostname: Destroying... (ID: XXXXXXXXXXXX)
null_resource.emrfs: Destroying... (ID: XXXXXXXXXXX)
null_resource.master_hostname: Destruction complete after 0s
null_resource.emrfs: Destruction complete after 0s
aws_emr_cluster.emr-cluster: Destroying... (ID: j-XXXXXXXXXX)
aws_emr_cluster.emr-cluster: Destruction complete after 0s

Destroy complete! Resources: 3 destroyed.
```
The EMR destruction takes more than 20min, whereas terraform says that the destruction is complete after 0s. Sounds like that's what is causing problem.

Thanks

**Comment by miloup** [comment]
One more thing. The attached terraform files create a DynamoDB table for EMR consistent view using the emr-config.json file. After running _terraform destroy_, this table does not go away.
