### ISSUE TITLE
resource aws_acm_certificate doesn't work with modules

### ISSUE THREAD

**Issue by aduzsardi** [hashicorp/terraform#17333]
### Terraform Version

```
Terraform v0.11.3
+ provider.aws v1.8.0
```

##### modules/acm/main.tf
```hcl
resource "aws_acm_certificate" "cert" {
  domain_name = "mydomain.com"
  subject_alternative_names = ["*.mydomain.com"]
  validation_method = "DNS"
}
```
##### main.tf
```hcl
provider "aws" {
  region = "eu-central-1"
}

module "test" {
  source = "./modules/acm"
}
```

### Debug Output

[tfdebug.txt](https://github.com/hashicorp/terraform/files/1720059/tfdebug.txt)

### Expected Behavior

Create acm certificate request
### Actual Behavior

```
$ terraform plan

Error: module.test.aws_acm_certificate.cert: Provider doesn't support resource: aws_acm_certificate
```
### Steps to Reproduce

* create a terraform module with aws_acm_certificate resource
* in root module instantiate the acm module `terraform init` & `terraform plan`

### Additional Context

Running `terraform init` && `terrafrom plan` && `terraform apply` in *./modules/acm/* does create the certificate req

**Comment by aduzsardi** [comment]
you are right , i was using an older version of the aws provider
thank you , worked with
```hcl
$ terraform version
Terraform v0.11.3
+ provider.aws v1.9.0
```

**Comment by catsby** [comment]
Glad to hear! Let us know if there's anything else we can help with 😄
