### ISSUE TITLE
How to apply "Name" tag to a default security group?

### ISSUE THREAD

**Issue by MaximF** [hashicorp/terraform#17343]
Hi there,

I'm trying to assign a "Name" tag to a default security group upon VPC creation.

I was thinking about two different approaches:
1. Use aws_vpc resource. That resource doesn't have any options to assign a tag to the security group, while it could be assigned to VPC itself.
2. Use aws_security_group resource. Provide it an ID of the default security group created with aws_vpc earlier and apply a tag to it. While trying to do that, I realize that aws_security_group creates new Security Groups, and doesn't modify pre-existing ones.
And also, when it is applied towards default SG, it returns the following error message:
> aws_security_group.default: Error creating Security Group: InvalidParameterValue: Cannot use reserved security group name: default

I don't see other approaches that would modify the default Security Group.
Could someone give an advice what could be done here?

If none of the existing tools allow doing that, we could file a feature request for aws_vpc resource.

Thank you,
Maxim

**Comment by bflad** [comment]
Hi @MaximF! 👋  We actually have a special resource, [`aws_default_security_group`](https://www.terraform.io/docs/providers/aws/r/default_security_group.html) for managing a VPC default security group. It supports a `tags` argument for your use case. Please be sure to read all the documentation, as by default it will remove rules.

**Comment by MaximF** [comment]
Thank you @bflad! That was really helpful and is exactly what I was looking for! 👍 😄
