### ISSUE TITLE
capture cloudformation resources in terraform

### ISSUE THREAD

**Issue by msuravarapu** [hashicorp/terraform#17341]
<!--
Hi there,

creating an snstopic with email protocol is not supported in Terraform.
so i invoked a cloud formation stack from Terraform and was able to successfully create a sns topic with email protocol.
How do i capture the snstopic ARN created by CF template in the terraform outputs ?

**Comment by bflad** [comment]
@msuravarapu can you please elaborate on this issue?

**Comment by msuravarapu** [comment]
I created terraform code which invokes

**Comment by msuravarapu** [comment]
i found the solution
