### ISSUE TITLE
AWS --- aws_network_acl -- subnet_id

### ISSUE THREAD

**Issue by rainmanh** [hashicorp/terraform#1735]
Hi
using AWS as a privisioner and for the aws_network_acl resource I am trying to associated multiple subnet_id but it does not seem to work, I just get crashes.

subnet_id = ["${var.resource.1}","${var.resource.1}"]

It only seems to work for one:

subnet_id = "${var.resource.1}"

Maybe I am using the wrong syntax for it?

thanks!

**Comment by catsby** [comment]
Hey @rainmanh – `subnet_id` is a single entity here; it doesn't accept an array/multiple subnets:

- https://terraform.io/docs/providers/aws/r/network_acl.html

Have you been able to do this elsewhere, with AWS Console or otherwise?

**Comment by catsby** [comment]
(closing for now, as this is working as documented and according to the AWS API)

**Comment by gonzaloordas** [comment]
Hi
yes, you can do that with the console. you can have several subnet associations per ACL.

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_ACLs.html

Associating a Subnet with a Network ACL

To apply the rules of a network ACL to a particular subnet, you must associate the subnet with the network ACL. You can associate a network ACL with multiple subnets; however, a subnet can be associated with only one network ACL. Any subnet not associated with a particular ACL is associated with the default network ACL by default.

**Comment by catsby** [comment]
Hello – I just merged #1931 which provides support for multiple subnet ids, and will go out in the next release.

**Comment by rainmanh** [comment]
thanks guy!!
