### ISSUE TITLE
Interpolation doesn't work for derived resources

### ISSUE THREAD

**Issue by hyperius** [hashicorp/terraform#17368]
It looks like there is interpolation bug introduced in v0.11.3.

I have the module with a couple EC2 instances count of which is provided to module as variable.
Also I have a bunch of EBS, EBS attachments and other stuff which relies on count of EC2 instances.

There is no errors when ```terraform plan -out=file``` executed, but ```terraform apply file``` fails with following error:
```
$ terraform apply file

Error: Error applying plan:

2 error(s) occurred:

* module.sentry.aws_volume_attachment.web_docker: Error reading aws_instance.web count: cannot parse "${var.instance_web_count}" as an integer
* module.sentry.aws_volume_attachment.web_data: Error reading aws_instance.web count: cannot parse "${var.instance_web_count}" as an integer

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

### Terraform Version
```
$ terraform -v
Terraform v0.11.3
+ provider.aws v1.9.0
+ provider.consul v1.0.0
```

### Terraform Configuration Files
Module call
```hcl
module "sentry" {
  source = "git::ssh://git@bitbucket.org/my/shiny-module.git?ref=master"
...

  instance_web_count      = 1
...
}
```
Module code
```hcl
variable "instance_web_count"      { default = 2 }

resource "aws_instance" "web" {
  ...
  count                   = "${var.instance_web_count}"
  ...
}

resource "aws_ebs_volume" "web_docker" {
  count             = "${aws_instance.web.count}"
  ...
}

resource "aws_ebs_volume" "web_data" {
  count             = "${aws_instance.web.count}"
  ...
}

resource "aws_volume_attachment" "web_docker" {
  count = "${aws_instance.web.count}"

  device_name = "/dev/xvdb"

  volume_id   = "${element(aws_ebs_volume.web_docker.*.id, count.index)}"
  instance_id = "${element(aws_instance.web.*.id, count.index)}"
}

resource "aws_volume_attachment" "web_data" {
  count = "${aws_instance.web.count}"

  device_name = "/dev/xvdc"

  volume_id   = "${element(aws_ebs_volume.web_data.*.id, count.index)}"
  instance_id = "${element(aws_instance.web.*.id, count.index)}"
}

```

### Debug Output
https://pastebin.com/EwE2eTp3

### Expected Behavior
Resources created

### Actual Behavior
```terraform apply``` fails with error

### Steps to Reproduce
1. Create initial resources
2. Add derived resources to configuration
3. terraform plan
4. terraform apply

### References
Perhaps the same issue as #17351

**Comment by hyperius** [comment]
any updates here?

**Comment by jbardin** [comment]
Hi @hyperiusm,

Sorry about the lack of feedback here. There was more discussion in 17462, but I have got a working reproduction case now. It requires a saved plan, and an existing resource with an interpolated count.

A minimal test case here starts with the config:

```
variable "instance_web_count" {
  default = 1
}

resource "null_resource" "test" {
  count = "${var.instance_web_count}"
}

#resource "null_resource" "dependent" {
#  count = "${null_resource.test.count}"
#}
```

 - `terraform apply`
 - uncomment the "dependent" resource
 - `terraform plan -out plan.out`
 - `terraform apply plan.out`
