### ISSUE TITLE
terraform plan is giving below error

### ISSUE THREAD

**Issue by mkaja** [hashicorp/terraform#17366]
I am running latest terraform version 

# terraform -v

```
Terraform v0.11.3
+ provider.aws v1.9.0
```

 # terraform refresh

```
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.

data.terraform_remote_state.infrastructure: Refreshing state...
data.aws_caller_identity.current: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* module.vpc.data.terraform_remote_state.infrastructure: 1 error(s) occurred:

* module.vpc.data.terraform_remote_state.infrastructure: data.terraform_remote_state.infrastructure: error loading the remote state: AccessDenied: Access Denied
	status code: 403, request id: 2F36EB86E9725943, host id: nNUuFGZnDn7SU7XsnFkRed3BPo8+pIx9meSTyBXYZ04HCmUXKUt/tij6031wpAegjJuTd9jsRck=
 --------------------
```

```
terraform init
Initializing modules...
- module.vpc
- module.vpc.vpc
- module.vpc.public_subnet
- module.vpc.bastion
- module.vpc.nat
- module.vpc.private_subnet
- module.vpc.vpc_endpoint_s3
Terraform has detected you're unconfiguring your previously set "s3" backend.
Do you want to copy existing state to the new backend?
  Pre-existing state was found while migrating the previous "s3" backend to the
  newly configured "local" backend. No existing state was found in the newly
  configured "local" backend. Do you want to copy this state to the new "local"
  backend? Enter "yes" to copy and "no" to start with an empty state.

  Enter a value: yes



Successfully unset the backend "s3". Terraform will now operate locally.

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.9"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by jbardin** [comment]
Hi @mkaja,

Can you provide some more information about the problem your having here? 

The error shows that you don't have permission to access the "infrastructure" remote state. Can you provide the configuration, and how you're setting the credentials for the provider?

**Comment by mkaja** [comment]
@jbardin we have 2 accounts in aws(non prod and prod ) and whenever we create in prod account after upgrading to TF 0.9 to 0.10 or latest version -we are getting the s3 access denied error. but i can access the s3 buckets in cli.

maint.tf

provider "aws" {
  region = "us-east-1"
  profile = "prod"
}

terraform {
  required_version = "~> 0.11"

  # Modify the configuration accordingly
  backend "s3" {
      bucket = "bucketname"
      encrypt = "true"
      key     = "infrastructure_states/us-east-1/vpc/terraform.tfstate"
      region  = "us-east-1"
    }
  }



data "terraform_remote_state" "infrastructure_prod" {
backend = "s3"

config {
bucket = "bucketname"
key    = "infrastructure_states/us-east-1/infrastructure-prod/terraform.tfstate"
region = "us-east-1"
}
}

**Comment by mkaja** [comment]
$ terraform -v
Terraform v0.11.3

 
$ terraform init
Initializing modules...
- module.vpc
  Getting source "git::https://git/terraform//aws//modules//vpc-base"
- module.vpc.vpc
  Getting source "../network/vpc"
- module.vpc.public_subnet
  Getting source "../network/public_subnet"
- module.vpc.bastion
  Getting source "../network/bastion"
- module.vpc.nat
  Getting source "../network/nat"
- module.vpc.private_subnet
  Getting source "../network/private_subnet"
- module.vpc.vpc_endpoint_s3
  Getting source "../network/vpc_endpoint"

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.9.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.9"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ terraform get -update
- module.vpc
  Updating source "git::https://github. terraform//aws//modules//vpc-base"
- module.vpc.vpc
  Updating source "../network/vpc"
- module.vpc.public_subnet
  Updating source "../network/public_subnet"
- module.vpc.bastion
  Updating source "../network/bastion"
- module.vpc.nat
  Updating source "../network/nat"
- module.vpc.private_subnet
  Updating source "../network/private_subnet"
- module.vpc.vpc_endpoint_s3
  Updating source "../network/vpc_endpoint"
 $ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.infrastructure_prod: Refreshing state...
data.terraform_remote_state.infrastructure: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.vpc.module.nat.output.nat_gateway_eips_cidr: At column 1, line 1: output of an HIL expression must be a string, or a single list (argument 1 is TypeList) in:

${aws_nat_gateway.nat.*.public_ip}/32

**Comment by mkaja** [comment]
any update on this ?

**Comment by jbardin** [comment]
Hi @mkaja,

I'm looking at this right now, but I'm a bit confused by the info here.
I'm not sure what the `init` and `get` (`init` does the `get` for you by the way) output are supposed to be showing. The final error here is also different than the one in the original post. 

My guess for the first issue is that you're not providing the proper profile to `data.terraform_remote_state.infrastructure_prod`. 

The last error looks unrelated, but you would need to provide the associated config in order to confirm.

**Comment by mkaja** [comment]
@jbardin I just looked at main.tf and i have the correct profile.
  profile = "prod"

provider "aws" {
  region = "us-east-1"
  profile = "prod"
}

terraform {
  required_version = "~> 0.11"

  # Modify the configuration accordingly
  backend "s3" {
      bucket = "bucket-name"
      encrypt = "true"
      key     = "infrastructure_states/us-east-1/sas-presto-vpc/terraform.tfstate"
      region  = "us-east-1"
    }
  }



data "terraform_remote_state" "infrastructure_prod" {
backend = "s3"

config {
bucket = "bucket-name"
key    = "infrastructure_states/us-east-1/infrastructure-prod/terraform.tfstate"
region = "us-east-1"
}
}

**Comment by jbardin** [comment]
@mkaja,

You're setting the profile for the aws provider, but that has no effect on the terraform provider. Inside the `config` block you should be passing `profile = "prod"`.

**Comment by mkaja** [comment]
@jbardin I added that inside config block and got same error 

code

config {
bucket = "science-at-scale-np-perm-space"
key    = "infrastructure_states/us-east-1/infrastructure-prod/terraform.tfstate"
region = "us-east-1"
  profile = "prod"
}

terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.infrastructure_prod: Refreshing state...
data.terraform_remote_state.infrastructure: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.vpc.module.nat.output.nat_gateway_eips_cidr: At column 1, line 1: output of an HIL expression must be a string, or a single list (argument 1 is TypeList) in:

${aws_nat_gateway.nat.*.public_ip}/32

**Comment by mkaja** [comment]
our nat.tf module is like this 
#--------------------------------------------------------------
# This module creates all resources necessary for NAT
#--------------------------------------------------------------

variable "name" {
  default = "nat"
}
variable "azs" {
  type = "list"
}
variable "public_subnet_ids" {
  type = "list"
}

resource "aws_eip" "nat" {
  vpc   = true

  count = "${length(var.azs)}"
  # Comment out count to only have 1 NAT

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_nat_gateway" "nat" {
  allocation_id = "${element(aws_eip.nat.*.id, count.index)}"
  subnet_id     = "${element(var.public_subnet_ids, count.index)}"

  count         = "${length(var.azs)}"
  # Comment out count to only have 1 NAT

  lifecycle {
    create_before_destroy = true
  }
}

output "nat_gateway_ids" {
  value = [
    "${aws_nat_gateway.nat.*.id}"]
}
output "nat_gateway_eips" {
  value = [
    "${aws_nat_gateway.nat.*.public_ip}"]
}
output "nat_gateway_eips_cidr" {
  value = [
    "${aws_nat_gateway.nat.*.public_ip}/32"]
}

**Comment by mkaja** [comment]
@jbardin after removing /23 in "${aws_nat_gateway.nat.*.public_ip}/32"] I was able to run plan successfully- but eventhough i mention profile=prod in main.tf its trying to deploy in my aws default profile which is non prod it used to work with 0.9 and 0.10 version - do we need to change anything in 0.11?

plan output 
Plan: 44 to add, 0 to change, 0 to destroy. 
from main.tf

provider "aws" {
  region = "us-east-1"
  profile = "prod"
}

**Comment by jbardin** [comment]
@mkaja,

This sounds like another unrelated issue.

Providers are handled differently in 0.11.x, but without a complete example I can't say for sure if that's the problem. You can reference the [Upgrade Guide](https://www.terraform.io/upgrade-guides/0-11.html) if you have questions about that. 

Another possibility is that you have some environment variables set overriding the configured credentials. 

I'm going to close this issue, as we're quite far off the original topic here, and this isn't a general support channel. If you do have a complete example where you can't get the correct provider credentials to be used, please feel free to open an new issue.

**Comment by mkaja** [comment]
Thanks @jbardin I gave the credentials access and secret (instead of having profile which takes from ~/.aws/credentials) and was able to apply- thanks  again

**Comment by kiranthrive** [comment]
Thanks !!! It woked for me @mkaja
