### ISSUE TITLE
join() swapping results on each run

### ISSUE THREAD

**Issue by bhechinger** [hashicorp/terraform#17360]
### Terraform Version

```
Terraform v0.11.3
+ provider.aws v1.9.0
+ provider.null v1.0.0
```

### Terraform Configuration Files

```hcl
  setting {
    namespace = "aws:ec2:vpc"
    name      = "Subnets"
    value     = "${join(",", module.Network.application_subnets)}"
  }

  setting {
    namespace = "aws:ec2:vpc"
    name      = "ELBSubnets"
    value     = "${join(",", module.Network.public_subnets)}"
  }
```
I just realized the contents of the Network module might be helpful.

From terraform.tfvars:
```
public_subnets = ["192.168.10.16/28", "192.168.10.32/28"]
application_subnets = ["192.168.10.48/28", "192.168.10.64/28"]
```

From the Network module:
```hcl
resource "aws_subnet" "public" {
  vpc_id                  = "${aws_vpc.VPC.id}"
  count                   = "${local.subnet_count}"
  cidr_block              = "${element(var.public_subnets, count.index)}"
  availability_zone       = "${element(var.az_list, count.index)}"
  map_public_ip_on_launch = true

  tags {
    Name        = "public-${element(var.az_list, count.index)}"
    Environment = "${var.application}"
  }
}

resource "aws_subnet" "application" {
  vpc_id                  = "${aws_vpc.VPC.id}"
  count                   = "${local.subnet_count}"
  cidr_block              = "${element(var.application_subnets, count.index)}"
  availability_zone       = "${element(var.az_list, count.index)}"
  map_public_ip_on_launch = false

  tags {
    Name        = "application-${element(var.az_list, count.index)}"
    Environment = "${var.application}"
  }
}

output "public_subnets" {
  value = "${aws_subnet.public.*.id}"
}

output "application_subnets" {
  value = "${aws_subnet.application.*.id}"
}
```
### Debug Output

https://gist.github.com/bhechinger/038f088c2a44929bcbc4586a0f30c011

### Expected Behavior

Nothing. There should be no changes.

### Actual Behavior

On every `terraform apply` run it wants to swap the order of the subnets

```
      setting.2372289383.name:      "ELBSubnets" => "ELBSubnets"
      setting.2372289383.namespace: "aws:ec2:vpc" => "aws:ec2:vpc"
      setting.2372289383.resource:  "" => ""
      setting.2372289383.value:     "subnet-004b7664,subnet-45f0bd18" => "subnet-45f0bd18,subnet-004b7664"
      setting.968195987.name:       "Subnets" => "Subnets"
      setting.968195987.namespace:  "aws:ec2:vpc" => "aws:ec2:vpc"
      setting.968195987.resource:   "" => ""
      setting.968195987.value:      "subnet-65506d01,subnet-8afbb6d7" => "subnet-8afbb6d7,subnet-65506d01"
```

### Steps to Reproduce

Run `terraform apply` multiple times.

**Comment by apparentlymart** [comment]
Hi @bhechinger!

This looks like a situation where the underlying API is altering the input to normalize it, and then returning the same data in a different form. Usually we are able to give Terraform special knowledge about these situations so it can ignore diffs, but this particular example is hard because the `setting` block is generic and so our usual mechanisms for normalizing diffs won't apply here.

I'm going to have our bot move this into the AWS provider repository since it seems to relate specifically to this resource. The team that works on the AWS provider may have some other ideas about how to address this.

**Comment by bhechinger** [comment]
I just "solved" it by running the variable through sort() first. Not sure I love that solution, but it works. :)

```hcl
  setting {
    namespace = "aws:ec2:vpc"
    name      = "Subnets"
    value     = "${join(",", sort(module.Network.application_subnets))}"
  }
```

**Comment by apparentlymart** [comment]
If the underlying API is also sorting it then I suppose that makes sense... agreed that it's not ideal, but I'm glad you found a workaround at least. :confounded:

**Comment by bhechinger** [comment]
I hope the provider team can figure something out. It now no longer re-sorts the subnets but something else is triggering a change that I need to track down. This is annoying.
