### ISSUE TITLE
Re-Using Resources AWS

### ISSUE THREAD

**Issue by rainmanh** [hashicorp/terraform#1736]
Hi

Using AWS as a provisioner and creating a VPC by default we get a Routing Table and an ACL
Any possibility of using all those without the need of creating some new resources??

I can see in the tfstate file the ID for the newly created resources but I am not sure we can use them?

Any tips/help?

thanks!!

**Comment by phinze** [comment]
Going over some old issues here.

These can be referenced as attributes on the vpc:

```tf
resource "aws_vpc" "foo" {
  cidr_block = "10.0.0.0/16"
}

output "route_table_id" {
  value = "${aws_vpc.foo.main_route_table_id}"
}

output "acl_id" {
  value = "${aws_vpc.foo.default_network_acl_id}"
}
```
