### ISSUE TITLE
Automatic download of a developed 3rd party plugin

### ISSUE THREAD

**Issue by andersla** [hashicorp/terraform#17379]
If I develop a plugin that currently not is included in the Terraform supported plugin 
, would it be possible to import it from an url where I provid pre-compiled versions of the plugin? For example an url pointing to a root dir with same structure as the supported plugins, e.g. https://releases.hashicorp.com/terraform-provider-cloudflare/
For example an url in the provider{ ... } block of configuration

**Comment by jbardin** [comment]
Hi @andersla,

Thanks for filing the issue. This is definitely something we're considering for a future release.

**Comment by apparentlymart** [comment]
Hi @andersla!

There's an existing issue #15997 about this topic, so I'm going to close this one just to consolidate the discussion over there. As @jbardin mentioned, we are planning to address this in a future release.
