### ISSUE TITLE
invalid value "terraform.tfvars" for flag -var-file-default: Error parsing terraform.tfvars: At 1:22: nested object expected: LBRACE got: ASSIGN

### ISSUE THREAD

**Issue by amrendo** [hashicorp/terraform#17375]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by apparentlymart** [comment]
Hi @amrendo!

It doesn't seem like there's any content in the issue here. In order that we can understand what you're seeing, please edit the opening comment on this issue and complete the sections as indicated in the template.
