### ISSUE TITLE
Dynamic Block maps?

### ISSUE THREAD

**Issue by ThomasVdBerge** [hashicorp/terraform#17391]
Hey All,

I was wondering if it is possible to use dynamic maps in certain resources (See example below)

### Terraform Version

```
Terraform v0.11.3
+ provider.aws v1.9.0
```

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_integration" "method_integration" {
  rest_api_id                         = "${var.api_id}"
  resource_id                       = "${var.parent_id}"
  http_method                     = "${aws_api_gateway_method.method.http_method}"
  integration_http_method = "${var.http_method}"
  type                                   = "HTTP"
  uri                                      = "${var.full_path}"
  passthrough_behavior     = "WHEN_NO_TEMPLATES"

  request_parameters {
    integration.request.path.taskId        = "method.request.path.taskId"
  }
}
```

What I would like to do:

```hcl
resource "aws_api_gateway_integration" "method_integration" {
  rest_api_id                         = "${var.api_id}"
  resource_id                       = "${var.parent_id}"
  http_method                     = "${aws_api_gateway_method.method.http_method}"
  integration_http_method = "${var.http_method}"
  type                                   = "HTTP"
  uri                                      = "${var.full_path}"
  passthrough_behavior     = "WHEN_NO_TEMPLATES"

  request_parameters {
    integration.request.path."${var.parameter}"        = "method.request.path.${var.parameter}"
  }
}
```

### Expected Behavior
Resource is added

### Actual Behavior
Error: Error loading modules: module method_options: Error parsing .terraform/modules/f5c172043019525be9dd03881ecb153e/main.tf: At 31:56: nested object expected: LBRACE got: ASSIGN

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
I am trying to create an API Gateway in an as much as possible modular form. Being able to dynamically manipulate the request_parameters would be great

**Comment by apparentlymart** [comment]
Hi @ThomasVdBerge!

We're currently working on integrating an improved configuration language parser and interpreter that allows (among other changes) dynamic keys in map arguments. Since `request_parameters` is actually a map rather than a nested block (i.e. its keys are free-form, rather than fixed in schema) this argument should automatically get this ability once we've released that change.

```hcl
# NOT YET IMPLEMENTED and may change before release
  request_parameters = {
    "integration.request.path.${var.parameter}" = "method.request.path.${var.parameter}"
  }
```

This is the current focus of the Terraform team at HashiCorp and will be included in a forthcoming major release.

**Comment by apparentlymart** [comment]
Hi again, @ThomasVdBerge!

I'm pleased to report that support for what I described earlier has now been merged to master in preparation for the forthcoming v0.12.0 release. The syntax I described will work in that new release, and I've verified similar configurations already in the v0.12.0-alpha1 prerelease build.
