### ISSUE TITLE
Terraform init, apply, plan not respecting state in s3

### ISSUE THREAD

**Issue by fewknow** [hashicorp/terraform#17410]
### Terraform Version

```
sflint@mac017 devops.infra.nexpose (develop)$ terraform -v
Terraform v0.11.1
+ provider.aws v1.9.0
+ provider.template v1.0.0

```

### Terraform Configuration Files

```hcl
# Providers

provider "aws" {
  region = "${data.terraform_remote_state.config.default_region}"
  profile = "${data.terraform_remote_state.config.run_env}"
}

# Backend

terraform {
  required_version = ">=0.11.0"

  backend "s3" {
   bucket = "cv-terraform-backend"
   key = "nexpose/terraform.tfstate"
   region = "us-east-1"


   dynamodb_table = "cv-terraform-state"
   workspace_key_prefix = "terraform-state"

 }
}

### Terraform linked projects ###

data "terraform_remote_state" "config" {
  backend = "s3"
  config {
    bucket = "cv-terraform-backend"
    key    = "terraform-state/${var.workspace}-config/config/terraform.tfstate"
    region = "us-east-1"
  }
}

```

### Debug Output

terraform init
https://gist.github.com/fewknow/9abf50a157a3c4ba8ba9d7c6f44e1b13

terraform show
https://gist.github.com/fewknow/3cee89e676747585d83ef3be1f50758d

### Expected Behavior

Nothing
### Actual Behavior

After running terraform init there is no local state file that is being built.  Then when I run terraform plan the aws_instance is trying to be recreated.  I can see the tf.state in the s3 bucket.  The `terraform show` is accurate.

```data.terraform_remote_state.config: Refreshing state...
data.template_file.setup_nexpose: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_instance.nexpose
      id:                                <computed>
      ami:                               "ami-27e8ca5d"
      associate_public_ip_address:       <computed>
      availability_zone:                 <computed>
      ebs_block_device.#:                <computed>
      ephemeral_block_device.#:          <computed>
      iam_instance_profile:              "nexpose_scanner"
      instance_state:                    <computed>
      instance_type:                     "m3.xlarge"
      ipv6_address_count:                <computed>
      ipv6_addresses.#:                  <computed>
      key_name:                          "terraform"
      network_interface.#:               <computed>
      network_interface_id:              <computed>
      placement_group:                   <computed>
      primary_network_interface_id:      <computed>
      private_dns:                       <computed>
      private_ip:                        <computed>
      public_dns:                        <computed>
      public_ip:                         <computed>
      root_block_device.#:               <computed>
      security_groups.#:                 <computed>
      source_dest_check:                 "true"
      subnet_id:                         "subnet-29299f06"
      tags.%:                            "5"
      tags.Name:                         "nexpose-0"
      tags.env:                          "dev"
      tags.os:                           "centos"
      tags.os_family:                    "linux"
      tags.service_name:                 "nexpose"
      tenancy:                           <computed>
      user_data:                         "c98c5d4d6aa5897e618a9c528c649ee12a2b8e0b"
      volume_tags.%:                     <computed>
      vpc_security_group_ids.#:          "2"
      vpc_security_group_ids.2443771858: "sg-b68b8bc3"
      vpc_security_group_ids.907840317:  "sg-818a8af4"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
```
### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. sflint@mac017 devops.infra.nexpose (develop)$ develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
Already up to date.
Switch your terraform workspace if needed
  `default`
 `* development-nexpose`
3. `terraform apply --var 'workspace=development'`

### Additional Context

This is happening for every terraform project I have currently.  I picked this one because it is just one instance.  I have checked s3 and the state files are available.  I am not sure why terraform show works but the apply doesn't?  
### References

Thanks you so much!!!!

**Comment by fewknow** [comment]
I have done some more investigation and it seems that when I do a terraform init I am getting the initial state from my versions s3 bucket 

```{
    "version": 3,
    **"serial": 1,**
    "lineage": "bd8016f6-3283-4a89-98e1-c22f6b9c0eb4",
    "backend": {
        "type": "s3",
        "config": {
            "bucket": "cv-terraform-backend",
            "dynamodb_table": "cv-terraform-state",
            "key": "nexpose/terraform.tfstate",
            "region": "us-east-1",
            "workspace_key_prefix": "terraform-state"
        },
        "hash": 10709064970045708229
    },
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```

You can see it is serial: 1, but the current versions is serial: 
```"version": 3,
    "terraform_version": "0.11.1",
    **"serial": 12,**
    "lineage": "1f536f44-2dd4-44e1-a952-6498f4c36083",
    "modules": [```

How do you configure terraform to know to get latest s3 version on terraform init?   Seems the show works for this but init does not?

**Comment by jbardin** [comment]
Hi @fewknow,

I think we have a few issues being confused here. Your state with `"serial": 1` is not your remote state -- it looks like the internal file that terraform uses to store it's configuration. You can use the command `terraform state pull` to see your actual working state.

I see you have `workspace_key_prefix` set, but you're passing in `workspace` as a variable, and trying to munge the workspace path in the remote state. You should generally use the same workspace mechanism for a remote state as you are for for the backend state. 

The `init` command doesn't "get" a state, it's just setting up the stored config, fetching plugins and modules. It does offer to migrate states of it detects a change in the backend configuration, but that's all.

I'm still unsure as to what you're seeing. Can you try running terraform version 0.11.3, there have been some changes to the s3 since 0.11.1 which may help clarify the situation.

**Comment by fewknow** [comment]
@jbardin the `serial:1` is not a remote state but the actual backend state for that file.  I am not having issues with the remote state or how it is constructed.  Not sure if I followed the correct pattern but I have only 1 remote state for every(20+) projects so I don't have to remember what remote state something lives in.  I can just reference this one `config` remote state.  ${data.terraform_remote_state.config.<<anything needed>>}  and because my different environments have different configs I needed a way to specify the environment.  For this I just pass in a **variable** called `workspace` and its only purpose is to set the correct remote_state config. 

If there is a better way of doing this I would love to know how to reconfigure my remote state so I don't have to pass in a variable at all but it would key off the workspace on its own as I do have the terraform workspace set to `development-<project>` 

As for this issue I did figure out what the problem is, but I still think it is a bug in the aws_provider.   I was setting up concourseci using bosh and it had me set some ENV variables for the AWS key and AWS secret.  This in return was over ridding my settings in the provider.
```
provider "aws" {
  region = "${data.terraform_remote_state.config.default_region}"
  profile = "${data.terraform_remote_state.config.run_env}"
}
``` 
This seems to be incorrect. If I am saying there is a `profile` to be used that should be checked first, then ENV variables.

Thoughts?   Thanks

**Comment by jbardin** [comment]
Yes! There's a way to directly access workspaces through the remote state datasource without having to know the exact path of the state file. If you want to match the current active workspace, set the `workspace` attribute like so:

```
data "terraform_remote_state" "config" {
  backend = "s3"
  workspace = "${terraform.workspace}"
  ...
```

As for the aws provider config, the aws sdk always checks environment variables first. 

It sounds like everything is under control here now, but if there's still an issue, feel free to reply to reopen this.
