### ISSUE TITLE
request-canceled-and-instance-running for the instance created with terraform

### ISSUE THREAD

**Issue by mulakkalfaizal** [hashicorp/terraform#17429]
### Terraform Version
Terraform v0.11.1

```
...
```

### Terraform Configuration Files
resource "aws_spot_instance_request" "test-1" {
  ami           = "${var.default-ami}"
  spot_price    = "${var.generic-spot-price}"
  instance_type = "${var.generic-type}"
  spot_type	= "${var.generic-spot-type}"
  availability_zone = "${var.generic-av-zone}"
  vpc_security_group_ids = [ "${var.generic-sg}", "${aws_security_group.test-1.id}" ]
  wait_for_fulfillment = true
  subnet_id	= "${var.generic-subnet}"
  tags {
    service-env = "${var.generic-env}"
    Name = "test-1"
    service-name = "test"
  }
  provisioner "local-exec" {
  command = "sleep ${var.wait-time}"
  }
}

resource "aws_eip" "test-1" {
  instance = "${aws_spot_instance_request.test-1.spot_instance_id}"
  vpc      = true
  depends_on = ["aws_spot_instance_request.test-1"]
}

resource "aws_security_group" "test-1" {
  name = "test-1"
  vpc_id = "${var.generic-vpc}"
}

### Expected Behavior

Terrafrom should either give a option to specify the "valid_until" for "aws_spot_instance_request" like "aws_spot_fleet_request" or increase the default request valid date to 1 year from the date of creation.

### Actual Behavior

Currently there is no option to specify the request validity time or date. So it is taking the default time of 7 days. After 7 days the request is getting cancelled and the instance is still running. So when i run the "terraform apply" its trying to create a new resource .

### Steps to Reproduce

1) Create a instance with the above snippet and wait for 7 days , the request will get cancelled and the server will be still running.

2) run terrafrom apply

3) terraform will try to create the server again which is already running.

**Comment by liron-recon** [comment]
This issue still exist in 1.32.0
