### ISSUE TITLE
Error loading modules

### ISSUE THREAD

**Issue by sunilkumarmohanty** [hashicorp/terraform#17435]
Hi, 
### Terraform Version
0.11.3

I have recently upgraded to terraform v 0.11.3 from 0.10.0. 
When I run `terraform init` and I am using module located at path `modules/level1/level2`, I get error 

`Error downloading modules: Error loading modules: module "modules/level1/level2" not found`

I have found this error to come only for certain folder names in level2 like alias, dlq, deployment. It seems to work for other folder names

This issue was not present in v 0.10.0.

p.s I had deleted .terraform folder before running terraform init

**Comment by jbardin** [comment]
Hi @sunilkumarmohanty,

Relative paths need to start with `./` or `../`. See the [v0.11 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-11.html#relative-paths-in-module-source)
