### ISSUE TITLE
Error connecting to Docker swarm

### ISSUE THREAD

**Issue by jwthomp** [hashicorp/terraform#1743]
I am able to successfully connect to the Docker daemon on a remote server, but when I point at the Swarm manager port I get the following error:

Errors:

  * 1 error(s) occurred:

* Error pinging Docker server: Get https://X.X.X.X:2376/_ping: tls: oversized record received with length 20527

I have verified that the Swarm manager is up and running on port 2376.

Anything I can test, verify, or provide information on?

Thank you!

**Comment by mitchellh** [comment]
@jwaldrip That error means that we're attempting to connect via TLS but the server isn't listening with a valid TLS server. Please configure the endpoint to not be TLS.

**Comment by jwthomp** [comment]
Great, thank you.
