### ISSUE TITLE
SSH timeout while running remote_exec on AWS instance

### ISSUE THREAD

**Issue by sriman-biarca** [hashicorp/terraform#17444]
### Terraform Version

```
$ terraform --version
Terraform v0.11.3
+ provider.aws v1.9.0

```

### Terraform Configuration Files

```hcl
resource "aws_instance" "web" {

  ami           = "ami-xxxxx"
  instance_type = "t2.micro"
  availability_zone = "us-east-1a"

  tags {
    Name = "ubuntu-16"
  }

  connection {
    type     = "ssh"
    user     = "xxx"
    agent = false
    private_key = "${file("/home/xxx/.ssh/id_rsa")}"
    timeout = "10m"
  }

  provisioner "remote-exec" {
    inline = [
      "echo 'hi' >> test.txt",
      "echo 'hi' >> /tmp/test.txt",
    ]
  }
}

```

### Expected Behavior

Should create files on the newly created aws instance
### Actual Behavior

aws_instance.web (remote-exec):   SSH Agent: false
aws_instance.web: Still creating... (10m20s elapsed)
aws_instance.web (remote-exec): Connecting to remote host via SSH...
aws_instance.web (remote-exec):   Host: 34.224.82.118
aws_instance.web (remote-exec):   User: xxx
aws_instance.web (remote-exec):   Password: false
aws_instance.web (remote-exec):   Private key: true
aws_instance.web (remote-exec):   SSH Agent: false
aws_instance.web: Still creating... (10m30s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* aws_instance.web: 1 error(s) occurred:

* timeout

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by apparentlymart** [comment]
Hi @sriman-biarca!

A common cause of this sort of issue is incorrect security group settings or SSH keys. Are you able to log into the instance manually using the `ssh` command with the same IP address, username, and SSH key?

**Comment by sriman-biarca** [comment]
Actually, In GCP we will provide public key in meta_data, Here in case of AWS, how to pass public key to AWS instance at the time of creation?

**Comment by sriman-biarca** [comment]
Hi @apparentlymart ,
Unable to login to that instance, 

$ ssh -i ~/.ssh/id_rsa xxx@34.229.94.173
Permission denied (publickey).

How to add public key to the newly created instance.

**Comment by sriman-biarca** [comment]
Yes... done. User changed to "ubuntu"

**Comment by notapatch** [comment]
[If anyone is having this problem Amazon has a great document covering ssh-ing into ec2 instances.](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html)
