### ISSUE TITLE
aws_alb_listener_rule - Can't leave priority field blank even though documentation says it's optional

### ISSUE THREAD

**Issue by TheSimpleZ** [hashicorp/terraform#17445]
### Terraform Version

```
Terraform v0.11.3
```

### Terraform Configuration Files

```hcl
resource "aws_alb_listener_rule" "host_based_routing" {
  listener_arn = "${var.alb_arn}"
  priority = 99 //Can't remove this

  action {
    type             = "forward"
    target_group_arn = "${aws_alb_target_group.service-tg.arn}"
  }

  condition {
    field  = "host-header"
    values = ["${var.service_url}"]
  }
}
```

### Expected Behavior

As in the documentation:

![image](https://user-images.githubusercontent.com/2884929/36723386-625f9124-1bb0-11e8-81c5-9d28eea2d2bf.png)

### Actual Behavior

`terraform apply` fails with:

`Error: module.SomeService.aws_alb_listener_rule.host_based_routing: "priority": required field is not set`

### Steps to Reproduce

define the above resource without the priority field set
`terraform init`
`terraform apply`

### Additional Context
I am trying to create the above resource as a part of a bigger infrastructure. So there is more code than shown here. Other than that, nothing unusual.

**Comment by bflad** [comment]
@TheSimpleZ while the documentation does not note it, the enhancement to make `priority` optional for `aws_alb_listener_rule` was introduced in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018), released a few days ago. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by TheSimpleZ** [comment]
That explains it. Thanks! 😄

**Comment by bflad** [comment]
I'm going to close this issue out to keep the repository clean, but please don't hesitate to let us know here or in the provider repository if you have any further issues.
