### ISSUE TITLE
Document that Swift authentication isn't supported in the Swift backend

### ISSUE THREAD

**Issue by fribeiro1** [hashicorp/terraform#17458]
### Terraform Version
0.11.3.

### Terraform Configuration Files
NA

### Debug Output
NA

### Crash Output
NA

### Expected Behavior
The documentation mentions that OpenStack Swift authentication, which is still used by many OpenStack users, isn't supported, but only Keystone v2 and v3.

### Actual Behavior
The documentation doesn't mention that OpenStack Swift authentication isn't supported.

### Steps to Reproduce
NA

### Additional Context
NA

### References
NA

**Comment by jtopjian** [comment]
@fribeiro1 I just came across this issue.

It's very possible to add support for Swift / non-Keystone authentication. I can provide the patch if you would be able to test this out (I don't have access to such an environment at the moment).

**Comment by fribeiro1** [comment]
@jtopjian I very much volunteer to test that for you, let me know when the patch is available.

**Comment by jtopjian** [comment]
@fribeiro1 Will do!

I'm going to wait until #18671 is merged and then add the swift auth on top of that.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity - it looks like the root issue has been fixed. However if there is still a problem in terraform v0.13, please open a new issue and fill out the template.
Thanks!

**Comment by kayrus** [comment]
@fribeiro1 `swauth` support was added within #23510

**Comment by fribeiro1** [comment]
Great, thanks!

---
Fernando Ribeiro
