### ISSUE TITLE
Terraform fmt adds a trailing comma after the last item on a list

### ISSUE THREAD

**Issue by katgironpe** [hashicorp/terraform#17471]
### Terraform Version

```
v0.11.3
```

### Terraform Configuration Files

```hcl
data "aws_iam_policy_document" "logs" {
  statement {
    effect = "Allow"

    actions = [
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]

    resources = [
      "arn:aws:logs:*:*:*",
    ]
  }
}

```

### Expected Behavior

The `terraform fmt` command should not add a trailing comma for the last item in a list. 

### Actual Behavior

The `terraform fmt` command adds a trailing comma for the last item in the list.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1.  Copy these lines of code on a file like `test.tf`:

  ```hcl
data "aws_iam_policy_document" "logs" {
  statement {
    effect = "Allow"

    actions = [
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:PutLogEvents"
    ]

    resources = [
      "arn:aws:logs:*:*:*",
    ]
  }
}
```

2. `terraform fmt`

### Additional Context

From my perspective of good code, that comma shouldn't be there unless there is something I am not aware of. 

### References

Related but not quite:

- #13025

**Comment by antonio-osorio** [comment]
@katgironpe 

> The main advantages are that it makes multi-line lists easier to edit and that it reduces clutter in diffs.

https://stackoverflow.com/a/11597911

**Comment by katgironpe** [comment]
It seems like a trivial one. Lists are always easy to edit. The diff part... I get it. Closing given this seems to have been decided to be a feature.
