### ISSUE TITLE
Terraform Module Issue

### ISSUE THREAD

**Issue by jitgswm** [hashicorp/terraform#17487]
Kindly help me out,I got stuck in module using input values in terraform
Below is the example code.

$ cat main.tf 
module "Test" {
source = "/home/jeetu/project/codes"
name = "${var.env}"
count = "${var.count}"
instancetype = "${var.instancetype}"
}

Apart from main.tf file, I have vars.tf & terraform.tfvars

$ cat vars.tf 

variable "env" {}

variable "count" {}

variable "instancetype" {}

$ cat terraform.tfvar

env = "development"

count = "2"

instancetype = "t2.micro"

when I run $ terraform init command it gives the error

Error : name is not a valid argument

Error : count is not a valid argument
Error : instancetype is not a valid argument

Thanks in advance.

### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by erran** [comment]
@jitgswm what is the content in `source = "/home/jeetu/project/codes"`? It looks like you haven't declared your variables in that module.

When using a module the structure is that you have a directory containing the module configuration (including declaring required variables). You have only declared root module variables based on what you added here.

You want something like this:

```
ecarey@BFS-MBP-4964 ~/r/issue-17487> tree
.            
├── main.tf                   
└── my-module
    └── vars.tf                             

1 directory, 2 files                                                         
```

```hcl
# main.tf                             
module "test" { 
  source = "./my-module"
                                                                         
  count = "2"                                                                  
  instancetype = "t2.micro"                                  
  name = "development"                               
}                                   
```

```hcl
# my-module/vars.tf
variable "name" {}
variable "count" {}
variable "instancetype" {}
```

**Comment by jbardin** [comment]
Hi @jitgswm,

I'm going to close this out since there hasn't been any feedback.
If you have an example of an ongoing problem, feel free to reply here and we can review the situation.

**Comment by Audace** [comment]
Having the same issue when initializing a module and then trying to add variables after.
