### ISSUE TITLE
AWS Cognito : Resource Server - New Feature

### ISSUE THREAD

**Issue by mdinuth** [hashicorp/terraform#17495]
**Feature Request**
Terraform currently doesn't support AWS Cognito User Pool Resource Server configurations. 
(AWS Cognito User Pool > (Left Panel) App Integration > Resource servers)
> **aws_cognito_user_pool_resource_server** 

Is it still under development? When will it be in production?

**Comment by ldenman** [comment]
I hobbled together a gist to at least help get someone started on this:

https://gist.github.com/ldenman/3a45312d68ff569aff21a03c199790fc#file-resource_aws_cognito_user_pool_resource_server-go

With the gist, only name, identifier, and user pool id are supported. More work is needed to support scopes.
