### ISSUE TITLE
Folder structure and provider issues when using backends

### ISSUE THREAD

**Issue by pixelicous** [hashicorp/terraform#17498]
Hi,

We have just decided on a folder structure for terraform deployment.
In a nutshell we have a few directories on the same folder root.
1. Resource folders themselves
2. Provider credentials
3. Configuration in tfvars
```
root
\-resources
        \prod
            \network
               -provider.tf
               -main.tf
               -vars.tf
               -output.tf
             \computer
               -provider.tf
               -main.tf
               -vars.tf
               -output.tf
\-provider
             \prod
                -credentials.tfvars
\-configuration
             \prod
                 -network-prod-location1.tfvars
                 -network-prod-location2.tfvars
```

The reason we did this was to split state file per application per region.
We can pass resources or modules directly through the .TF files of each folder, it would be the same idea.
We cannot have one tf file externally of all those folders and then call what we want because this will create a state file for all those resources together.

### Terraform Version
```
**Terraform v0.11.3**
```

### Terraform Configuration Files
```
terraform {
  backend "azurerm" {    
  }
}
```

We execute using the following partial backend configuration:
```
terraform init -backend-config="storage_account_name=sa_name" -backend-config="container_name=cont_name" -backend-config="key=state_file_name" -backend-config="access_key=access_key" -upgrade
```

### Crash Output
```
Pre-existing state was found while migrating the previous "azurerm" backend to the
  newly configured "azurerm" backend. An existing non-empty state already exists in
  the new backend. The two states have been saved to temporary files that will be
  removed after responding to this query.

  Previous (type "azurerm"): C:\Users\-I~1\AppData\Local\Temp\terraform251989279\1-azurerm.tfstate
  New      (type "azurerm"): C:\Users\I~1\AppData\Local\Temp\terraform251989279\2-azurerm.tfstate
```

### Expected Behavior
We have a wrapper script that goes to the right resource folder and adds the correct tfvars file

We use backends as well, with different blob name for his state, for example:
resource-environment-location.tfvars
The problem is that if we execute the same resource folder with same backend/provider but with different tfvars file, we get a message saying that our state file in the temp directory exists already.

1. How can we avoid this situation? This doesn't happen with local state file
2. Another question - we currently duplicate the provider.tf file and the backend resource across all resources that we create, is there another way to do it that doesn't involve symbolic links?
3. The idea of using one folder with differing variables is the concept of a module.. it wouldn't matter much if i create the resources in the root of my resource or call a module that will create the resources , the action would be the same in terms of the backends. So how do can i reuse that folder with different variables? i want to reduce blast radius and split to many state files as possible.

It seems like the temp folder state file has different lineage and the .terraform folder has a tfstate file as well, where the backend config is overwritten everything. why do we have this file if the state file is in storage backend???

**Comment by pixelicous** [comment]
Is this related to #14066 or #13552 maybe?

"-reconfigure" did the trick but i am still not sure that is the way to go..
According to #14066 i see they ARE actually using root folder with provider/backend and calling to sub folders, but this will implement too much junk in the state.

Would really be helpful to receive some insights! Thanks :)

**Comment by jbardin** [comment]
Hi @pixelicous,

Sorry, I'm not quite sure what you're doing here exactly, but maybe some details about how Terraform handles backends would help alleviate the confusion. 

Terraform always stores its internal configuration from `init` relative to the current working directory. This currently includes the default location and metadata for modules and plugins, as well as the last known backend configuration. If you run `init` in a directory with a different backend config from the previous execution, terraform will detect this as a change and attempt to migrate the state.

If it helps, think of the working directory as always containing a single logical configuration tree. It should contain the root level configuration, importing the desired modules and set the corresponding variables. 

If you want different state files in the same backend, using the same configuration, then I would suggest using [workspaces](https://www.terraform.io/docs/state/workspaces.html), as they are fundamentally just named states. 

If you want to treat the configuration as being dynamic, then you might consider cloning the desired config into a temporary location and starting fresh each time, which is how a lot of systems handle automating terraform. You may find some useful tips in the [Running Terraform in Automation](https://www.terraform.io/guides/running-terraform-in-automation.html) guide.

**Comment by pixelicous** [comment]
Hi @jbardin 

Thanks for the response, was a good read. After posting the issue I read a bit and managed to understand the fact that the backend has  its own state in ".terraform", that is why I managed to solve it with "-reconfigure".

I think it is a bit hard to connect these dots as someone coming from a local state use. 
I thought that by using a backend, it will just place the state file somewhere else, i didn't think terraform will use another state locally to tie both together.
Using partial configuration i already provide all the necessary details to connect to that remote storage and fetch the state, why not keep everything there and read at execution time?
This seems logical to me because if you change the backend config keyfile location (state) between executions. that means there is some sort of global difference between the states that should be treated as such (portrayed through the states).

Regarding the structure I would love to be pointed at a best practice structure, are there any examples to be found to show what you suggest or how it is safe/recommended way to work? from what i saw for aws it wasnt scaleable enough and the state file would be huge.
We are trying to abstract as little as we can and use as much of terraform and not wrappers or aiding tools 
[]((https://github.com/hashicorp/best-practices/tree/master/terraform/providers/aws)

In the beginning we used to have one provider/backend in the top root folder and have a main.tf file be rebuilt by a wrapper to interpolate the module source and name but then each folder needed different variables and also it was harder to differentiate between core infrastructure and resources of that region or environment, depends what you were targeting.

Copying the folder to a side location as you suggested isn't something i thought of, so basically just copy that file aside, add a default provider.tf and backend and execute? this means that i need to keep the .terraform folder and basically have a duplicate of the whole infrastructure, it will be like the terraform folder structure as a duplicate.. i think this can lead to config drift if somebody changes only one side and executes..
if i only keep them temporarily that approach and my first both promote a method where those temp files written aside will be gone on next execution. if somebody changes your code, it's hard to compare the new folder structure with what you have in the state file because it just doesn't exist anymore.

We also wanted to represent the region of the infrastructure but to avoid duplication of resources, so the region is represented by a TFVARS file, if we had both region and environment as sub folders that would have meant a lot duplication (or symlinks).

This makes much sense:
1. you get provider version per resource (in case a terraform version specifically breaks a flow)
2. everything has its own state file and own var files, very simple to track, you put a resource, quickly assign vars in tfvars and then you forget about it
3. easy to target what to deploy
4. we wanted to split the core infrastructure from resources, but still have them on the same folder path, as far as we tried, any other way it means having some sort of hosting root folder with tf files executing those folders, but it should create a bloated state file.. we couldn't find a way to accomplish this otherwise
5. the ability to choose wheter to layout the resources directly in that folder or call other modules
6. balance between simplicity, not writing twice much, dynamic, and not to abstract too much with the wrapper

The article you sent me is informative, i will look into workspaces, i actually read this doc before but forgot about its existence.

**Comment by pixelicous** [comment]
@jbardin i tested the workspaces, i thought this will deal with the backend as well but apparently not, so i was left at the same spot but now the backend is still angry with me and the state filenames have suffixes :)
I think using workspaces i understood my mistake, i used the wrapper to interpolate the name of the state blob the was saved remotely, which is what the workspaces do basically for all i see.
[The docs for azurerm backend state:](https://www.terraform.io/docs/backends/types/azurerm.html)
```
key   = "prod.terraform.tfstate"
```
Which is basically what i'm doing, so if you change that prod to a different string, the backend will ask what to do, copy/merge.
The whole point of using a partial configuration and overriding that parameter is to achieve such multi environment scenarios
I think my longer reply above can help understand what we tried to achieve.. 

I guess my three options are:
1. keep passing different partial configs to backend, each to support different region and environment and use -reconfigure for the backend (i am not sure of any ways this cant hurt me, no exprt)
2. remove my flow that aggregates the different location interpolation let the workspace do the renaming.
3. change the whole structure :(

**Comment by jbardin** [comment]
Hi @pixelicous,

It sounds like you have your options sorted out here, so I'm going to close this out for now, but feel free to respond here if I missed something.

Either 1 or 2 should work just fine, and if you are starting "fresh" each run, then the `-reconfigure` part isn't really a concern.
