### ISSUE TITLE
How to not create certain resources in a specific workspace?

### ISSUE THREAD

**Issue by jonathan-kosgei** [hashicorp/terraform#17492]
Is it possible to skip creating a resource depending on the workspace?

For example; Not creating route53 records if in the test workspace?

**Comment by jbardin** [comment]
Hi @jonathan-kosgei,

You can see an example of creating conditional resources under the [conditionals section](https://www.terraform.io/docs/configuration/interpolation.html#conditionals) in documentation. You may also want to check out the [relevant section in the 0.11 upgrade guide](https://www.terraform.io/upgrade-guides/0-11.html#referencing-attributes-from-resources-with-count-0) which covers the current limitations of referencing conditional resources.
