### ISSUE TITLE
Initializing module from git fetches the whole repository

### ISSUE THREAD

**Issue by pixelicous** [hashicorp/terraform#17503]
Hi,

We are using TFS with GIT as version control, we create a repository with terraform/modules under the root folder. Our modules reside in that folder.
To target specific folder we are using double slashes to state the subfolder we are after (as shown below)

### Terraform Version
```
Terraform v0.11.3
```

### Terraform Configuration Files
```
module "webapp_internal" {
  source = "git::https://our_tfs_server/somecollection/someteam/_git/somerepo//terraform/modules/azure/somemodule"
  name = "just a name"
  location = "${var.location}"
}
```

### Expected Behavior
Terraform will download only the specific module folder directly to .terraform
      

### Actual Behavior
I noticed that even though i target a very specific sub folder in GIT, i get the whole repository downloaded, but terraform actually uses only the relevant folder, why is it doing this?

To target specific folder we are using double slashes to state the subfolder we are after

**Comment by jbardin** [comment]
Hi @pixelicous,

This is rather unfortunate behavior that we have to maintain, at least for the near term. While the isolation of modules was intended to work as you've shown here, it turns out far too many users broke the logical isolation and would often reference resource _outside_ of the module via relative paths, either by importing submodules like `source = "../../submodule"`, or loading files into the config like `"${file(../../filename)}"`.

**Comment by pixelicous** [comment]
Hi @jbardin 
Just curious though, then what came before what? If it was never possible and modules would work only in that manner of isolation, people couldn't break the rule as "../../" wouldn't work for them..

 So the only option now is to make a repo specifically for modules (and get everything all the time in each .terraform), or to break each module to a repository?

i think a good option would be to provide some sort of attribute for the module resource that would trigger this behavior or as parameter during execution, i think with a helper property to the module it will help be more dynamic, if people would want to use that "feature" for a specific module that broke

**Comment by jbardin** [comment]
The behavior is a side effect of the internal module storage implementation. While this wasn't intended or documented, it follows from remote modules being handled in the same manner as local modules. 

Yes, most users create VCS repos specifically for configuration (the enterprise workflows basically require this), and the [Module Registry](https://registry.terraform.io/) encourages a single repo per module.

**Comment by pixelicous** [comment]
@jbardin thx

**Comment by pixelicous** [comment]
@jbardin 
i got a question.. i used the file function in the following manner: `template_body = "${file("some.json")}"`
It didn't find the file, nor dir using " ./ " prefix.. then i found #hashicorp/terraform/issues/5213 
This confuses me with your answer.. it doesn't seem like it is possible to load files that way..

**Comment by jbardin** [comment]
@pixelicous, Sorry, I'm afraid I don't understand the question. If you want to load a file in a module, using a path relative to that module, you need to use the special `path.module` value.  See the [`file` function docs](https://www.terraform.io/docs/configuration/interpolation.html#file-path-)

**Comment by moxli** [comment]
@jbardin 
Hi, could I kindly ask you to reconsider adding a "feature" which implements a workflow like this.
I am basically forced to use one repository for my terraform modules used in multiple projects because of enterprise reasons....

As @pixelicous pointed out the optimal workflow would be to just pull the modules like this:
`source = "git::https://bitbucket.org/whatever/testing//cluster"`

I understand that the "terraform way" is to have a repo for each module like with the public modules in the registry but this is not possible in my case.

**Comment by pixelicous** [comment]
@moxli we actually have one repository for all modules and we reference specific folder for the module, it still downloads the whole respository, but uses only one folder, i don't find a good enough reason but ok. ♿️

**Comment by moxli** [comment]
@pixelicous thats weird it doesn't work like that for me, do you mind sharing your "setup"?
How is each moduled downloaded/how does the source path look like? How is the git repository structured?

**Comment by jbardin** [comment]
@moxli,

While it may be possible to instruct the downloader to configure a particular sparse checkout for a module, a lot of users expect the entire repository to be available via relative paths from the module. While we don't encourage this pattern, there are enough customers using that we intend to support it for the foreseeable future.

One feature that might be possible and can significantly reduce download size is to use a shallow clone for `git::` urls, which is an open at #10703

**Comment by fantapop** [comment]
Our mono repo loves this feature :-)
