### ISSUE TITLE
terraform crashed when trying to import azurerm application gateway

### ISSUE THREAD

**Issue by avnsiva** [hashicorp/terraform#17500]
### Terraform Version
Terraform v0.11.2
+ provider.azurerm v1.2.0
### Terraform Configuration Files
[https://gist.github.com/avnsiva/4b1f9763736f5bbfcbc35831e9cef4d5](https://gist.github.com/avnsiva/4b1f9763736f5bbfcbc35831e9cef4d5)

**Comment by avnsiva** [comment]
When tryng to import an existing app gateway configuration into terraform, it crashed with a crash.log file. I have attached the log file after masking the subscriptionid and certificate data in it. Pls advice if this is a bug or anything wrong with my terraform alone

**Comment by jbardin** [comment]
Hi @avnsiva, 

The link in your issue seems to be a large blob of javascript and html. Can you post the plain text of the log file and configuration?

**Comment by apparentlymart** [comment]
I think that was just the "embed code" version of the gist. The normal gist page is here:
https://gist.github.com/avnsiva/4b1f9763736f5bbfcbc35831e9cef4d5

**Comment by apparentlymart** [comment]
The stack trace in the log suggests that this panic is in the azurerm provider, so I'm going to have our bot move the issue over there.
