### ISSUE TITLE
User key is not uploaded

### ISSUE THREAD

**Issue by prandelicious** [hashicorp/terraform#17515]
### Terraform Version
```
Terraform v0.11.3
+ provider.aws v1.10.0
```
### Terraform Configuration Files
```hcl
provider "aws" { }

resource "aws_instance" "test" {
  ami = "ami-xxxxxxxx"
  instance_type = "t2.micro"
  vpc_security_group_ids = ["sg-xxxxxxx"]
  subnet_id = "subnet-xxxxxx"
  key_name = "Test"
  tags {
    Name = "test"
  }

  provisioner "chef" {
    server_url      = "https://<chef server url>"
    user_name       = "user"
    user_key        = "${file("~/.chef/user.pem")}"
    node_name       = "test"
    run_list        = ["role[app]"]
    on_failure      = "continue"
    recreate_client = true
    version         = "12.16.42"
    fetch_chef_certificates = false
    ssl_verify_mode = ":verify_none"
    environment = "test"
    client_options = [
      "verbose_logging = true"
    ]
  }

  connection {
    type         = "ssh"
    user         = "ssh-user"
    private_key  = "${file("../keys/ssh-user.pem")}"
    bastion_host = "1.1.1.1"
  }
}
```
### Debug Output
https://gist.github.com/prandelicious/068e50524f67fceda12d75322c7f0997

### Expected Behavior
The `user.pem` file defined in `user_key` should have been copied to `/etc/chef/user.pem` on the remote machine/target node.

### Actual Behavior
1. The file `/etc/chef/user.pem` is missing on the remote machine/target node.
2. The file `/etc/chef/client.pem` is missing on the remote machine/target node. 

### Steps to Reproduce
`terraform apply`

### Other Information
I tried copying the `user.pem` file from `~/.chef/user.pem` to the directory where `main.tf` is located but the behavior is still the same.

**Comment by jbardin** [comment]
Hi @prandelicious,

It looks like the provisioner code is designed to clean up the user key file after execution, so I wouldn't expect `/etc/chef/user.pem` to exist after provisioning. 

As for the `/etc/chef/client.pem` file, the logs indicate that the `create client` command exited with status `100`, and the provisioner exited with an error.  I'm not really familiar with chef, but the chef server or client logs may provide more information as to why the command failed.

**Comment by prandelicious** [comment]
Thanks @jbardin for pointing me in the right direction.

**Comment by jbardin** [comment]
It looks like you're connecting as `ssh-user`, telling chef to use the username `user` and trying to write the log output to `/home/ec2-user`. Are these really all different usernames?

**Comment by prandelicious** [comment]
I found the problem yesterday. It was caused by an incorrect `server_url` value. I inadvertently configured it as **https://chef-server.opsworks-cm.io** instead of **https://chef-server.opsworks-cm.io/organizations/default**. Thank you, @jbardin for your time!
