### ISSUE TITLE
Error loading modules from a single repository

### ISSUE THREAD

**Issue by Puneeth-n** [hashicorp/terraform#17529]
```
Terraform version 0.10.8
```

We started opensourcing some modules and decided to host them all in a single repository. However, Our build server has errors fetching the modules from GitHub. However, when hosted in separate repos, they work fine.

```
Error downloading modules: Error loading modules: module ct-backend-internal-alb: No Terraform configuration files found in directory: .terraform/modules/f0a7db608787c289fd71f36df6c7dacb
```
[Module repo](https://github.com/comtravo/terraform-aws-modules)

**Comment by jbardin** [comment]
Hi @Puneeth-n,

Can you provide some configuration showing how you're using the modules? 
The error indicates that the source for your `ct-backend-internal-alb` module points to a location with no terraform configuration files.

**Comment by Puneeth-n** [comment]
@jbardin Thanks for the reply. Strangely, It could only be reproduced on the Jenkins server but not on my workstation. Well, the only thing that I can think of is EFS. Jenkins uses EFS for workspace and it might be that there is a write delay to the NFS.

Anyways, here is the config:
```hcl

data "template_file" "currency-definition" {
  template = "${file("${path.module}/templates/apig/currency.tpl")}"

  vars {
    environment = "${var.ct_environment_name}"
  }
}

module "get-currency-rates" {
  source = "github.com/comtravo/terraform-aws-modules//terraform-aws-api-gateway"

  name        = "currency-${var.ct_environment_name}"
  stage       = "${var.ct_environment_name}"
  definition  = "${data.template_file.currency-definition.rendered}"
  domain_name = "${var.production_env ? "foo.bar.com" : "foo-stage.bar.com"}"
}
```

**Comment by jbardin** [comment]
Thanks for the extra info. Is the jenkins server re-using the same working directory, or does it start fresh every time?
Is it using the same version of Terraform?

The only thing I can think of offhand is that there's an old symlink or old reference to another module in the local cache.

**Comment by Puneeth-n** [comment]
@jbardin Jenkins is reusing the workspace. Everywhere it is Terraform `0.10.8`. When we fetch modules from GitHub AFAIK they are not symlinked right? They go in to separate directories in the `.terraform` folder

**Comment by jbardin** [comment]
Yes, remote modules are saved in a local directory, but submodules can be symlinked. The paths for modules have also evolved over time, so there is probably some stale data in there.

Since the module storage has changed since 0.10.8, and we are planning on cleaning it up even further for the next major release, this is most likely solved already.
