### ISSUE TITLE
Package Structure: Crazy dependencies and no guidance on dependencies to start plugin dev

### ISSUE THREAD

**Issue by nbering** [hashicorp/terraform#17523]
I was working on updating the vendor dependencies for a provider I'm working on. [nbering/terraform-provider-ansible](https://github.com/nbering/terraform-provider-ansible/)

In tracing down package dependencies to try and update or prune them from the list based on what I had originally copied from another provider, I found that I had a dependency on the Golang AWS SDK.

My provider makes literally no API calls, being a "logical" provider like Random, or Template. So... it seemed odd to need all these:

```
 github.com/aws/aws-sdk-go/aws
 github.com/aws/aws-sdk-go/aws/awserr
 github.com/aws/aws-sdk-go/aws/awsutil
 github.com/aws/aws-sdk-go/aws/client
 github.com/aws/aws-sdk-go/aws/client/metadata
 github.com/aws/aws-sdk-go/aws/corehandlers
 github.com/aws/aws-sdk-go/aws/credentials
 github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
 github.com/aws/aws-sdk-go/aws/credentials/endpointcreds
 github.com/aws/aws-sdk-go/aws/credentials/stscreds
 github.com/aws/aws-sdk-go/aws/defaults
 github.com/aws/aws-sdk-go/aws/ec2metadata
 github.com/aws/aws-sdk-go/aws/endpoints
 github.com/aws/aws-sdk-go/aws/request
 github.com/aws/aws-sdk-go/aws/session
 github.com/aws/aws-sdk-go/aws/signer/v4
 github.com/aws/aws-sdk-go/internal/shareddefaults
 github.com/aws/aws-sdk-go/private/protocol
 github.com/aws/aws-sdk-go/private/protocol/query
 github.com/aws/aws-sdk-go/private/protocol/query/queryutil
 github.com/aws/aws-sdk-go/private/protocol/rest
 github.com/aws/aws-sdk-go/private/protocol/restxml
 github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
 github.com/aws/aws-sdk-go/service/s3
 github.com/aws/aws-sdk-go/service/sts
```

So I removed them and tried building. That showed me the dependency for the AWS SDK came from `github.com/hashicorp/go-getter`. I looked into that out of curiosity and that led me to see that this was a dependency because of Terraform's plugin discovery feature.

But this is for a plugin *server*, not a client. There's only two reasons I can see that these packages are needed for me to build.

1. The plugin client is needed for acceptance tests (I haven't checked this, just a guess).
2. Govendor pulls in the `github.com/hashicorp/terraform/plugin/client.go` just because it's in the plugin package, and go wants to build it because it's there.

Either way... it seems odd that I'd need the AWS SDK vendored just to build a plugin that makes no API calls. Maybe something could be done to tweak the terraform plugin package to reduce the dependencies downstream without sacrificing any functionality?

Maybe I've installed my packages wrong... which leads me to another (maybe more concrete question). Can we get some developer guidance on how to select the minimum vendor dependencies to get started building a plugin? Preferably a list that would be maintained and updated version-to-version?

**Comment by jbardin** [comment]
Hi @nbering,

Sorry about he confusion here, but this is the expected dependency tree for terraform.

The `go-getter` package is used in both plugin discovery and the module loader, which are both in turn imported into the core terraform package.

The plugin may not need to ever directly use anything from the aws package, but the dependencies need to be there if order to compile the program. If they're not used, they are not going to be linked into the final binary.

We are thinking about splitting out some of the plugin helpers into separate packages, and are working to improve the plugin protocol, both of which may have the benefit of lightening the dependencies required fro plugins. We are also hoping to move to a better performing dependency manager once one is available,  but in the meantime it's best to just let govendor do what it needs to do.

**Comment by nbering** [comment]
Thanks, @jbardin. Still learning to use the tools, and I think I originally copied the dependencies from another provider. That's why I wasn't sure.

Would you be interested in a PR for documentation on installing the vendor dependencies under the plugin development guide?

**Comment by jbardin** [comment]
Thanks for the offer! I would hold off on the documentation at the moment, as we already have some plans in progress to help with enablement which will include more extensive documentation.
