### ISSUE TITLE
Feature Request: Target dependencies on a "apply -target" command

### ISSUE THREAD

**Issue by jdonofrio728** [hashicorp/terraform#17534]
Hello,

Perhaps I'm dreaming here, but I would like to see something like this added to terraform apply:
```
$: terraform apply -target <resource> -with-deps
```
With the intended affect to only target a certain resource, AND all dependencies of that resource. This would make it easier to do things like rolling deployments of ec2 resources with persistent data ebs-volumes.

**Comment by jbardin** [comment]
Hi @jdonofrio728,

This is how `-target` should already work.  Do you have an example configuration of usage in mind where this doesn't do what you expect?

**Comment by jbardin** [comment]
Hi @jdonofrio728,

Thanks for the update. I understand what you're looking for now, yes `-target` is intended to include a specific resource an _its_ dependencies, and exclude anything that is dependent on the targeted resource. The idea is to make the minimal possible graph that can be applied for the targeted resource, and no more. 

With an expanded definition of `-target`, a user couldn't fix a problem where a resource needs to be updated separately from its dependents. While we could theoretically add yet another mode (e.g. `-target-with-dependents`), I think we first need to figure out why you need to use `-target` to begin with. 

The `-target` option is really just intended to fix problems, and work around situations where the complete graph can't be applied at once, which is usually a bug or a shortcoming of a provider or resource. It is not meant as a normal mode of operation. In general, a well-formed config should be applied in full after every change.

**Comment by jdonofrio728** [comment]
Ah yes, I think I had some misunderstanding especially with my use of dependencies.

Essentially what I am trying to do is to simulate a rolling deploy for ec2 instances. In my case, I have 3 to 10 ec2 instances, each with an attached ebs volume with all of its data. If I just use -target for the ec2 instance, then the new instance will come up without its ebs volume. What I would like to be able to do is also be able to target the resources dependent on the ec2 instance, which would include the ebs volume and a few other parts.

Right now I am working around this by specifying -target multiple times, but that is a little inconvenient :)

**Comment by jbardin** [comment]
Thanks for following up.

Terraform isn't meant to handle partial updates in the general case, so `-target` is provided to workaround the instances where the entire config can't be applied at once. If something like this is going to come to fruition, I think it would most likely be in the form of a new resource lifecycle. The idea of having a "rolling update" lifecycle is covered in some other issues (e.g. #16378).

As for this particular request, `-target` is working as expected, so I'm going to close this our for now.
