### ISSUE TITLE
random_shuffle only returns the first item in the list

### ISSUE THREAD

**Issue by prandelicious** [hashicorp/terraform#17549]
### Terraform Version
```
Terraform v0.11.3
+ provider.aws v1.11.0
+ provider.random v1.1.0
```

### Terraform Configuration Files
```hcl
resource "random_shuffle" "az2" {
  input = ["us-east-2a", "us-east-2b", "us-east-2c"]
  result_count = 1
}

output "random_value" {
  value = "${random_shuffle.az2.result}"
}
```

### Debug Output
First run
```
random_value = [
    us-east-2a
]
```
Second run
```
random_value = [
    us-east-2a
]
```
Third run
```
random_value = [
    us-east-2a
]
```
### Expected Behavior
Provide random item from list

### Actual Behavior
It's only providing the first item in the list

### Steps to Reproduce
`terraform apply`

### Additional Context
I'm running Terraform inside a WSL environment on Windows 10 (Fall Creators Updated):
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

**Comment by jbardin** [comment]
Hi @prandelicious,

This is the correct behavior for the random provider. In order for Terraform to work, any "randomness" must be deterministic. The resource will shuffle the inputs again, only when there is a change to the resource itself.

**Comment by prandelicious** [comment]
I tried using `random_shuffle` again:
```hcl
variable "private_subnets" {
  default = ["subnet-A", "subnet-B"]
}

resource "random_shuffle" "az" {
  input = ["${var.private_subnets}"]
  result_count = 1
}

module "server" {
  source = "./modules/aws-ec2"
  instance_count = 3
  name = "${var.env}-server"
  stack = "server"
  role = "server"
  ami = "${lookup(var.aws_amis, var.aws_region, "")}"
  instance_type = "t2.micro"
  subnet_id = "${random_shuffle.az.result[0]}"
  vpc_security_group_ids = ["${var.security_groups}"]
}
```
The expected output is that it will select either _subnet-A_ or _subnet-B_ when it creates the EC2 instance but it's always selecting the first item in the list which is _subnet-A_.

**Comment by jbardin** [comment]
@pradeepbhadani,

Yes, this is the same case. Terraform simply cannot work if resources evaluate differently every time. Until the arguments to `random_shuffle.az` change, it will still be the same resource, which means that `random_shuffle.az.result[0]` will always be the same result.

Try playing with a random resource by itself, and see what happens

```
resource "random_shuffle" "list" {
  input = ["A", "B", "C", "D", "E"]
}
```

It will apply a single time, then nothing will change un subsequent calls to plan or apply until the arguments change.

**Comment by philtong** [comment]
@pradeepbhadani,

There is another way to assign a random subnet per ec2, but if you have to use random_shuffle, this may help - by using modulo (%)

- change this
      result_count = 1
  To the appropriate number, or use length() to get the correct count

- change this:
      subnet_id = "${random_shuffle.az.result[0]}" 
  To
      subnet_id = "${ random_shuffle.az.result[ count.index % length( random_shuffle.aw.results) ] }"

That is assuming you have "count' defined.

#################
Another way to get a list of subnet_id and use % to get a random index out of that subnet_id list, by doing:

    subnet_id      = "${ tolist(.  data.aws_subnet_ids.frontend.ids. )[ count.index % length( data.aws_subnet_ids.frontend.ids) ]}"    

Note that tolist is Terraform 0.12 and later, data.aws_subnet_ids.frontend.ids is defined to get a list of subnet ID based on tag 'Tier'.  So it would be something like this:

### vpc info
data "aws_vpc" "default" {
    filter{
        name = "tag:Name"
        values = ["must_match_whatever_you_have"]
    }
}

data "aws_subnet_ids" "selected" {
  vpc_id = "${data.aws_vpc.default.id}"
}

data "aws_subnet_ids" "frontend" {
  vpc_id = "${data.aws_subnet_ids.selected.vpc_id}"
  tags = {
    Tier = "FrontEnd"
  }
}

# ec2
resource "aws_instance" "Frontend-instance" {
    count         = "4"
    ami           = "ami-xyz"
    instance_type = "t2.micro"
    subnet_id      = "${ tolist(data.aws_subnet_ids.frontend.ids)[ count.index % length( data.aws_subnet_ids.frontend.ids) ]}"    
  tags = {
          Name = "FrontEnd-${count.index + 1}"
  }
}
