### ISSUE TITLE
Unable to add a file in S3 using terraform

### ISSUE THREAD

**Issue by ShubhasisMathur** [hashicorp/terraform#17554]
Hello Team,

I have facing one issue. Whenever I am trying to add a file in S3 in the same .tf file, the error comes that S3 bucket doesnt exist. However If I apply the below tf file again, it works. 
So my requirement is that the below file should work such that it creates the bucket and so also add the file in the same bucket. RIght now its not doing it for the first time  have to re apply to insert the file.'

Below is the file:

 #1. Populating account details
provider "aws" {
  access_key = "XXXXXXXXX"
  secret_key = "XXXXXXXXX"
  region     = "us-east-1"
}

#2. CReation of Bucket "shubhasisterraform"
resource "aws_s3_bucket" "b" {
  bucket = "shubhasisterraform"
  acl    = "private"
  tags {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

#3. adding of file accountdetails in S3 bucket(shubhasisterraform)
resource "aws_s3_bucket_object" "bucket" {
  bucket = "shubhasisterraform"
  key    = "new_object_key"
  source = "/root/S3/accountdetails"
  etag   = "${md5(file("/root/S3/accountdetails"))}"
}

**Comment by jbardin** [comment]
Hi @ShubhasisMathur,

In order for terraform to know that the bucket must be created before the object, you must somehow reference the bucket from that object. For example, your resource might look like

```
resource "aws_s3_bucket_object" "bucket" {
  bucket = "${aws_s3_bucket.b.id}"
  key = "new_object_key"
  source = "/root/S3/accountdetails"
  etag = "${md5(file("/root/S3/accountdetails"))}"
}
```

**Comment by Aliabbask08** [comment]
@jbardin thanks:)
