### ISSUE TITLE
terraform fmt should support 4 spaces ident

### ISSUE THREAD

**Issue by rafilkmp3** [hashicorp/terraform#17573]
Terraform fmt is a great tool to format and ident the code, but this must support choose the ident size like 2 4 spaces or tabs

### Terraform Version

```
Terraform v0.11.3
...
```

**Comment by bflad** [comment]
Hi @rafilkmp3, thanks for submitting this request!

I believe the inspiration (and for the most part implementation) of `terraform fmt` is based on the Go language tool [`go fmt`](https://golang.org/cmd/gofmt/), which is very opinionated about formatting Go code. On the [Go blog](https://blog.golang.org/go-fmt-your-code), they go through some of the reasoning why the opinionated nature is important. Many of these ideas would apply to Terraform configuration as well, which might explain why configurable indentation is not supported or desired at the current time.

**Comment by apparentlymart** [comment]
Hi @rafilkmp3! Thanks for this feature request.

The main goal of `terraform fmt` is to choose a consistent set of formatting rules to achieve consistency between Terraform modules. It's therefore against its purpose to be configurable, and we don't intend to add further options to it.

The intent here is similar to the Go community's `gofmt`. In [the Go Proverbs](https://talks.golang.org/2015/gofmt-en.slide#26), this is expressed as "Gofmt's style is no one's favorite, yet gofmt is everyone's favorite". Most of us have preferences that conflict with at least one of the "rules" encoded in `terraform fmt`, but we believe that consistency is more important than flexibility here, allowing modules to be shared and individuals to move between teams without needing to adapt to a new local style.

This can also allow, for example, an out-of-the-box good experience with a text editor integration that runs `terraform fmt` automatically on save, and will allow us to build features that generate or modify configuration, such as #15608.

The choices made in `terraform fmt` may evolve over time as the configuration language changes and best-practices emerge, but the goal is for it to always have exactly one set of rules per Terraform version.

I hope that helps to clarify the intent here. For more context, please see the very similar issue opened against the Go formatter: golang/go#16256.
