### ISSUE TITLE
How to get/access resource name in custom provider.

### ISSUE THREAD

**Issue by Arjun4545** [hashicorp/terraform#17579]
suppose i have
resource "abc-type" "network-name" {
     description = "check network"
}
so how will i get **network-name** value in code(provider.go file).

**Comment by apparentlymart** [comment]
Hi @Arjun4545,

The name you refer to is something that is significant only within the module where the resource is declared, and not something that provider code may use. Instead, provider developers should include attributes for all of the resources they need, allowing the user to select a reasonable module-namespaced logical name for the resource separately from the often-globally-scoped name that will be used with the remote API:

```hcl
resource "abc_network" "main" {
  name        = "globally-unique-network-name"
  description = "check network"
}
```

These two concerns are intentionally separated to allow users to refactor their Terraform configurations without unexpected changes to remote data.

**Comment by Arjun4545** [comment]
Thanks **apparentlymart** for your immediate response.
