### ISSUE TITLE
Lifecycle sub block request: 'change-silently'

### ISSUE THREAD

**Issue by kieferrj** [hashicorp/terraform#17577]
### Terraform Version
```
0.10.7
```

### Terraform Configuration Files

```hcl
resource "aws_rds_cluster" "pd-aurora-cluster" {
  ...
  final_snapshot_identifier = "${var.environment_name}-${var.aurora_cluster_name}-${replace(timestamp(), ":", "")}"
```
### Desired Behavior
I Would like to be able to drop a "lifecycle { change-silently = [ "final_snapshot_identifier" ] }" in my aurora module so that I dont always have the following change in my plan.out:

```
  ~ module.pardot3ue1_aurora_rds.aws_rds_cluster.pd-aurora-cluster
      final_snapshot_identifier:                 "acme3-aurora57-2018-03-13T191435Z" => "acme3-aurora57-2018-03-14T033559Z"
```

**Comment by apparentlymart** [comment]
Hi @kieferrj! Thanks for this feature request.

This idea feels similar but not exactly the same as `ignore_changes`. I guess here what you want to see is for Terraform to simply hide the diff from the output but apply it anyway? This is a little in conflict with Terraform's principles, to be honest. We make a point of always being very explicit about what Terraform would do.

There's also a practical question here: what should Terraform do if the _only_ change to be made is to update a `change_silently` attribute? In that case Terraform would need to explain that there's a change to be made without being able to state what the change is, which feels a little strange.

I'd like to see if there's a way to achieve your goals here using the existing `ignore_changes` feature. Could you share a little more detail about your use-case? From what you've shared here the effect would seem to be that when you delete a cluster its final snapshot would be named after the time it was most recently updated, which feels a little strange to me but I'm sure there's some additional context here I don't see. `ignore_changes` would instead cause the snapshot to be named after the time the resource was _created_, which should still be unique-ish and properly ordered but maybe not unique enough for your purposes?

**Comment by kieferrj** [comment]
Greetings @apparentlymart . Ive been reading your PRs for years I feel like. Its an honor.

Anyway, this would mate perfectly with any attribute that elicits change and is employing the "timestamp()" function.

My current example:

```
~ module.zabbixdb.aws_rds_cluster.pd-aurora-cluster
     final_snapshot_identifier:         "zabbixdb-2018-04-06T171804Z" => "zabbixdb-2018-04-06T181335Z"
```

Otherwise, I guess I dont really want to use that timestamp function...

**Comment by mildwonkey** [comment]
Thanks for sharing your use case, @kieferrj !
At this time we are going to close this request; while your use-case is valid it does not appear to be a feature that other users are interested in (we look for 👍on the original comment), and it's not compelling enough to overcome the difficulties and potential downsides.

Thank you for opening this feature request, and please don't let this one unsatisfying response stop you from opening more in the future!
