### ISSUE TITLE
Errors should report file/module names and/or line numbers where possible

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#1758]
I'm almost embarrased to say, but some of my TF code has me stumped atm, and I'm realizing the majority of the problem is that I have _no idea_ what TF is actually referring to in my code.

```
ᐅ tfp -module-depth=1 
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * provider.aws: "access_key": required field is not set
  * provider.aws: "secret_key": required field is not set
  * provider.aws: "region": required field is not set
```

Grep is your friend right? This should be easy to debug you say.. 

```
ᐅ         grep -R secret ./       
./terraform.tfvars:secret_key = "FOOBAR"
./terraform.tfvars:consul_secret_key = "FOOBAR=="
./asg.tf:    secret_key = "${var.secret_key}"
./asg.tf:    consul_secret_key = "${var.consul_secret_key}"
./asg.tf:    secret_key = "${var.secret_key}"
./.terraform/modules/7206d8f30df8a8f26276fb9d0f6ac24e/terraform.tfvars:# Update these with AWS key id/secret
./.terraform/modules/7206d8f30df8a8f26276fb9d0f6ac24e/terraform.tfvars:#secret_key = "FOOBAR"
./.terraform/modules/7206d8f30df8a8f26276fb9d0f6ac24e/terraform.tfvars:#consul_secret_key = "FOOBAR=="
./.terraform/modules/7206d8f30df8a8f26276fb9d0f6ac24e/providers.tf:    secret_key = "${var.secret_key}"
./.terraform/modules/7206d8f30df8a8f26276fb9d0f6ac24e/variables.tf:variable "secret_key" {
./.terraform/modules/7206d8f30df8a8f26276fb9d0f6ac24e/variables.tf:    description = "AWS key secret"
./.terraform/modules/7206d8f30df8a8f26276fb9d0f6ac24e/variables.tf:variable "consul_secret_key" {
./.terraform/modules/7206d8f30df8a8f26276fb9d0f6ac24e/main.tf:#    secret_key = "${var.secret_key}"
./.terraform/modules/ea621125d274b1a478ff64ff0a781085/providers.tf:    secret_key = "${var.secret_key}"
./.terraform/modules/ea621125d274b1a478ff64ff0a781085/variables.tf:variable "secret_key" {
./.terraform/modules/ea621125d274b1a478ff64ff0a781085/variables.tf:    description = "AWS key secret"
./providers.tf:    secret_key = "${var.secret_key}"
./variables.tf:variable "consul_secret_key" {
./variables.tf:variable "secret_key" {}
```

While I have the names of the variables to grep for, TF isn't telling me which module it is in, the file it is processing, or line number, so it's much more difficult to debug.

**Comment by ketzacoatl** [comment]
Poking at my source some, I can see that if my code is incorrectly using a module, the module will bark at me.

```
Errors:

  * module root: module foo-cluster-b: required variable access_key not set
  * provider.aws: "access_key": required field is not set
  * provider.aws: "secret_key": required field is not set
  * provider.aws: "region": required field is not set
```

So there is an implicit assumption in the errors above that we are in the root, which is confusing.

**Comment by mitchellh** [comment]
I agree we should do this.

**Comment by phanect** [comment]
+1

My infrastructure is not so large and I can search it manually, but that's hassle.
I can find it faster if this is implemented.

**Comment by mitchellh** [comment]
We've started doing this in some errors, but its going to have to be an incremental process as we go error by error... going to close this since waiting until it is 100% done could be effectively forever and its been a year and error messages are improving. Note that the required var error message hasn't changed yet. :)

**Comment by ketzacoatl** [comment]
@mitchellh I agree it doesn't make sense to keep this open until there is 100% coverage for all errors, but doesn't it make sense to address the errors for modules and required vars (or, at least keep this open until that's updated)?

**Comment by cristim** [comment]
I'd like to help with this if I can.

@mitchellh do you have an example on how this was done for some of the errors so I can inspire from it?

**Comment by mitchellh** [comment]
Hey @cristim, there are actually some errors in `config` that emit the file info. Basically if you look at HCL (the config language we use), the AST generated contains positional information. We need to thread that through or use that directly when we show an error.

**Comment by saurabh-hirani** [comment]
Having line numbers against errors would be very useful as currently it is very cumbersome to track down individual errors one by one. IDE integrated linters can use the line number info to jump to errors and speed up the error fixing process.

**Comment by npc-adrian** [comment]
+1 for line numbers

**Comment by martinkoch-geniebelt** [comment]
+1 for file name, _path_ and line number. Getting something like `Error: resource 'aws_ecs_service.main' config: unknown variable referenced: ...` is not useful when I have 10s of ecs services and I'm trying to do a rename of a variable and have (apparently) forgotten an instance somewhere.

**Comment by hbd** [comment]
To the Terraform team: what would it take to help make line numbers a thing? I'd like to help with this effort.

**Comment by Dominik-K** [comment]
Line numbers will be [part of version 0.12](https://github.com/hashicorp/terraform/issues/16665#issuecomment-434129897)
