### ISSUE TITLE
Interpolation fails on S3 bucket policy

### ISSUE THREAD

**Issue by dkheyman** [hashicorp/terraform#17593]
### Terraform Version

```
v0.11.3
```

### Terraform Configuration Files

```
s3_default_bucket_policy.json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSCloudTrailAclCheck20150319",
            "Effect": "Allow",
            "Principal": {"Service": "cloudtrail.amazonaws.com"},
            "Action": "s3:GetBucketAcl",
            "Resource": "arn:aws:s3:::${var.cloudtrail_bucket_id}"
        },
        {
            "Sid": "AWSCloudTrailWrite20150319",
            "Effect": "Allow",
            "Principal": {"Service": "cloudtrail.amazonaws.com"},
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::${var.cloudtrail_bucket_id}/logs/*",
            "Condition": {"StringEquals": {"s3:x-amz-acl": "bucket-owner-full-control"}}
        }
    ]
}

The above is a policy JSON file, that is then invoked in the S3 module like so:

resource "aws_s3_bucket" "s3_bucket" {
    region  = "${var.aws_region}"
    bucket  = "${var.s3_bucket_name}"
    acl     = "${var.s3_bucket_acl}"

    # Set S3 Bucket Policy 
    policy = "${file("${path.module}/${var.s3_bucket_policy}")}"

The variables.tf contains the following variable:
variable "s3_bucket_policy" {
    type = "string"
    default = "s3_default_bucket_policy.json"
    description = "The policy document (via file) to apply to the bucket."
}
variable "cloudtrail_bucket_id" {
    description = "The name of the Cloudtrail bucket to which to send logs for S3"
    default     = "mvc-test-logs"
}
```

### Expected Behavior
 ~ module.test_s3_bucket.aws_s3_bucket.s3_bucket
      policy:                                                                                                "" => "{\r\n    \"Version\": \"2012-10-17\",\r\n    \"Statement\": [\r\n        {\r\n            \"Sid\": \"AWSCloudTrailAclCheck20150319\",\r\n            \"Effect\": \"Allow\",\r\n            \"Principal\": {\"Service\": \"cloudtrail.amazonaws.com\"},\r\n            \"Action\": \"s3:GetBucketAcl\",\r\n            \"Resource\": \"arn:aws:s3:::mvc-test-logs\"\r\n        },\r\n        {\r\n            \"Sid\": \"AWSCloudTrailWrite20150319\",\r\n            \"Effect\": \"Allow\",\r\n            \"Principal\": {\"Service\": \"cloudtrail.amazonaws.com\"},\r\n            \"Action\": \"s3:PutObject\",\r\n            \"Resource\": \"arn:aws:s3:::mvc-test-logs/logs/*\",\r\n            \"Condition\": {\"StringEquals\": {\"s3:x-amz-acl\": \"bucket-owner-full-control\"}}\r\n        }\r\n    ]\r\n}"

### Actual Behavior
 ~ module.test_s3_bucket.aws_s3_bucket.s3_bucket
      policy:                                                                                                "" => "{\r\n    \"Version\": \"2012-10-17\",\r\n    \"Statement\": [\r\n        {\r\n            \"Sid\": \"AWSCloudTrailAclCheck20150319\",\r\n            \"Effect\": \"Allow\",\r\n            \"Principal\": {\"Service\": \"cloudtrail.amazonaws.com\"},\r\n            \"Action\": \"s3:GetBucketAcl\",\r\n            \"Resource\": \"arn:aws:s3:::${var.cloudtrail_bucket_id}\"\r\n        },\r\n        {\r\n            \"Sid\": \"AWSCloudTrailWrite20150319\",\r\n            \"Effect\": \"Allow\",\r\n            \"Principal\": {\"Service\": \"cloudtrail.amazonaws.com\"},\r\n            \"Action\": \"s3:PutObject\",\r\n            \"Resource\": \"arn:aws:s3:::${var.cloudtrail_bucket_id}/logs/*\",\r\n            \"Condition\": {\"StringEquals\": {\"s3:x-amz-acl\": \"bucket-owner-full-control\"}}\r\n        }\r\n    ]\r\n}"

### Additional Context
The S3 module is created via referencing it in an environment implementation of the module. The variables.tf, and the s3 resource.tf are in the same directory. Interpolation works in a similar way for IAM policy, but not for this S3 bucket policy. Any help would be appreciated.

**Comment by nbering** [comment]
File contents are not interpolated. You are looking for this:

[Resource: template_file](https://www.terraform.io/docs/providers/template/d/file.html)

**Comment by jbardin** [comment]
Closing for now, as this appears to be answered.
