### ISSUE TITLE
Order of returned scopes in GCE different to input config

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#1759]
I am trying out a fix that uses a set instead of a list for the scopes.  However it is blocked because the StateFunc doesn't work for sets.

**Comment by sparkprime** [comment]
Test case:

deploy this, then run plan and it will ForceNew

provider "google" {
    account_file = "../service_account_key.json"
    project = "abiding-truth-649"
    region = "us-central1"
}

resource "google_compute_instance" "test-scopes" {
    name = "test-scopes"
    machine_type = "g1-small"
    zone = "us-central1-a"

    disk {
        image = "debian-7-wheezy-v20140814"
    }

    service_account {
        scopes = [ "logging-write", "storage-full", "compute-rw", "datastore" ]
    }

    network_interface {
        network = "default"
        access_config { }
    }
}

**Comment by sparkprime** [comment]
Workaround: put the scopes in alphabetical order in your config.

**Comment by phinze** [comment]
@sparkprime check out the linked PR - based on that unit test passing, it looks to me like the `StateFunc` is getting called for nested sets.

Let me know if there's something different about your use case that the unit test isn't reproducing.

**Comment by sparkprime** [comment]
So my evidence to the contrary is in the referenced commit I added a line to log the scopes coming out, and they don't get canonicalized:

+			log.Printf("[INFO] using scope '%s'", v.(string))

yields 

2015/04/30 16:39:48 terraform-provider-google: 2015/04/30 16:39:48 [INFO] using scope 'datastore'
2015/04/30 16:39:48 terraform-provider-google: 2015/04/30 16:39:48 [INFO] using scope 'compute-rw'
2015/04/30 16:39:48 terraform-provider-google: 2015/04/30 16:39:48 [INFO] using scope 'storage-full'
2015/04/30 16:39:48 terraform-provider-google: 2015/04/30 16:39:48 [INFO] using scope 'logging-write'

Which is not acceptable input to the API (it needs the full URL).

**Comment by sparkprime** [comment]
Oh, I just noticed by looking at the diff that the old code called canonicalize explicitly at that time...  Should that not be necessary?

**Comment by sparkprime** [comment]
I suppose I was assuming that it was being called as the config comes in, to lower it to a less readable but more true representation.  But equally valid is to keep the config in its original form and only convert it when it really needs to match the reality, i.e. when you're doing diffs.
