### ISSUE TITLE
Terraform attempts to delete old resource before updating dependencies

### ISSUE THREAD

**Issue by omeid** [hashicorp/terraform#17614]
Hello,

Consider the following simple infra:

```hcl

resource "db_instance" "db" {
  name = "baes_b"
  engine = "postgres"
}

resource "engine_instance" "engine" {
  db_id = "${db_instance.db.id}"
}
```

If we change `db.engine` and it forces a new resource, terraform attempts to delete the old `db` before changing `instance` to point to the newly created db, this of course, fails, because the provider (aws in this case, for example) won't allow deleting a resource that has live dependencies (instance.engine, in this case).

Terraform should behave more smartly in this regard.

Current work around is to copy the db resource with a new name, point instance.engine to new copy of the resource, apply, remove old, apply, rename to original. Tedious and error prone, but gets the job done.

**Comment by jbardin** [comment]
Hi @omeid,

Sorry for the confusion here, but this is the expected order of operations for Terraform.
Terraform itself can't know if there are any other dependencies between resources imposed by the  provider. In cases where a resource must always exist, it's required to add a `lifecycle` block indicating that the resource must be created before the destroying an existing resource.

```
lifecycle {
  create_before_destroy = true
}
```

If you have an specific resource in mind that requires `create_before_destroy` but doesn't document it, we can certainly open up an issue with the appropriate provider.

**Comment by omeid** [comment]
Hello @jbardin 

Thanks for your reply.

I don't understand why terraform can't know about a dependency that it manages? in fact, it even plans for updating said dependency already.

In the case of our example, terraform knows that `engine` depends on `db` and plans to update `engine` after recreating `db` but it disregards this dependency in the process of re-creating `db` and attempts to remove it before pointing `engine` to the newly created db. 


The current steps seems to be

1. create new resource
2. delete old resource                              `<--- problematic step`
3. update resource dependencies

I think the correct steps would be:
1. create new resource
2. update resource dependencies
3. delete old resource


unless I am missing something very obvious. :)

**Comment by jbardin** [comment]
Hi @omeid,

The reasoning is that the first order you state is the most common, and most efficient required order of operations for resource replacement, and we provide the `create_before_destroy` lifecycle for the cases where the second order is desired. In the few cases where certain combinations of resources require `create_before_destroy`, it should be documented in the provider docs. 

In future terraform versions, providers may be able to provide hints about certain computed fields to trigger the lifecycle automatically, but that of course can't infer when that ordering is required by other externalities of your infrastructure.

**Comment by omeid** [comment]
Just to make sure I understand things correctly, does `create_before_destroy` should force the second flow (that is, update dependencies before deleting the old resource)?

**Comment by jbardin** [comment]
Yes, that is the idea behind `create_before_destroy`.

**Comment by omeid** [comment]
Right, the exact resource that I had the problem with are `aws_db_subnet_group` and `aws_db_instance`. I will try with `create_before_destroy` and will close this issue accordingly.

Thanks for the follow up!
