### ISSUE TITLE
aws_route53_zone import: AccessDenied

### ISSUE THREAD

**Issue by hryamzik** [hashicorp/terraform#17611]
### Terraform Version

```
v0.11.3
```

### Configuration

```
resource "aws_route53_zone" "test-com-public" {
    name       = "test.com"
    comment    = "HostedZone created by Route53 Registrar"

    tags {
    }
}
```

### Output

```
$ terraform import aws_route53_zone.test-com-public SOMEZONEID
aws_route53_zone.test-com-public: Importing from ID "SOMEZONEID"...
aws_route53_zone.test-com-public: Import complete!
  Imported aws_route53_zone (ID: SOMEZONEID)
aws_route53_zone.test-com-public: Refreshing state... (ID: SOMEZONEID)

Error: aws_route53_zone.test-com-public (import id: SOMEZONEID): 1 error(s) occurred:

* import aws_route53_zone.test-com-public result: SOMEZONEID: aws_route53_zone.test-com-public: AccessDenied: User: arn:aws:iam::111111111111:user/email@email.com is not authorized to access this resource
	status code: 403, request id: SOMEID
```

I can't post trace log due to amount of data I have to strip. I get this error on account with multiple roles. [`terraforming r53z --tfstate`](https://github.com/dtan4/terraforming) works fine.

**Comment by l0renzor** [comment]
Hi,
I've encountered the same behavior on the version 11.11

Error: Error refreshing state: 1 error(s) occurred:

* aws_route53_zone.internal_zone: 1 error(s) occurred:

* aws_route53_zone.internal_zone: aws_route53_zone.internal_zone: error getting Route53 Hosted Zone (AAAAAAAAAAAAAA): AccessDenied: User: arn:aws:iam::1111111111111:user/name.lastname is not authorized to access this resource
        status code: 403, request id: 0e1691f3-1f47-11e9-a68f-65bae6df7e6b
