### ISSUE TITLE
0.11.4 import does not remove lock with backend

### ISSUE THREAD

**Issue by roarmstrong** [hashicorp/terraform#17624]
### Terraform Version

```
Terraform v0.11.4
+ provider.aws v1.11.0
```

### Terraform Configuration Files

Have also tried with an aws_instance resource.
```hcl
terraform {
  required_version = ">= 0.11.3"

  backend "s3" {
    bucket = "terraform-lock-testing"
    key = "lock-test-stack/"
    encrypt = true
    region = "ap-southeast-2"
    dynamodb_table = "terraform"
  }
}

resource "aws_cloudwatch_log_group" "docker" {
 name              = "/var/log/docker"
}

provider "aws" {
  region = "ap-southeast-2"
}
```

### Debug Output

https://gist.github.com/roarmstrong/d2b74af155f29d5a98b99174e68f0c50

### Expected Behavior

After `terraform import` is run successfully the DynamoDB table should not contain a LockID Item. `terraform plan` should succeed. 
### Actual Behavior

`terraform plan` encounters the following error `Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed` and the DynamoDB table contains a lockID item.
### Steps to Reproduce
1. `terraform init`
2. `terraform import aws_cloudwatch_log_group.docker /var/log/docker`
3. `terraform plan`

This appears to still work as expected with version 0.11.3.

**Comment by ThisGuyCodes** [comment]
I am encountering this issue as well, exactly as described

**Comment by jbardin** [comment]
Hi @roarmstrong,

Sorry this is causing a problem for you, and thanks for filing the issue.
It turns out the some improved lock handling in the primary operations adversely effected the import command. We'll plan to have a fix for his out as soon as we can.

**Comment by eschwartz** [comment]
I don't think this is provider specific. I've haven't been able to import _anything_ with terraform v0.11.8. I've tried AWS security groups, ECR repositories, IAM roles...
