### ISSUE TITLE
Remote tfstate backup in git

### ISSUE THREAD

**Issue by AntonTumasov** [hashicorp/terraform#17628]
### Terraform Version

```
v0.11.3
```

### Issue
Then we use remote backend (ETCD) for tfstate during `terraform apply` we are facing the problem with not getting any history or text backup of tfstate. Therefore I think there is a very obvious step to undertake, use some kind of post-hook for `apply` command which is gonna be pushing tfstate not only in ETCD but also in git. What would you recommend to do in this situation, do we have to create our own solution or you will have already done some work on it in future releases?
Thank you ahead!

**Comment by pkolyvas** [comment]
I'm doing a clean-up of older enhancement requests that haven't gained traction but also don't coincide with our current focus and longer terms plans.

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform, your use cases, and your needs as a practitioner.
