### ISSUE TITLE
Unable to download terraform provider config

### ISSUE THREAD

**Issue by sg21210** [hashicorp/terraform#17623]
Hi, I'm having network issue when I download terraform files including terraform.exe, plugins for aws providers and so on. Any files from releases.hashicorp.com cannot be downloaded well.
(Note: my average download rate is 22KB/s, it takes 10+ minutes to get terraform.exe / aws plugin)

### Terraform Version
v0.11.4
- AWS v1.11.0

### Crash Output
```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.11.0)...

Error installing provider "aws": stream error: stream ID 9; PROTOCOL_ERROR.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/windows_amd64
```

### Steps to Reproduce
1. `terraform init`

### Additional Context
I'm in South Korea. When I tried same procedure in US region with an instance in AWS, it had no problem at all. However here, I'm having that kind of trouble. It seems a regional issue.
Of course, I'm going to check any local issue here, but I'm just asking here also to check for your side.

**Comment by jbardin** [comment]
Hi @sg21210,

Sorry you're having an issue with this. Is the problem happen from within your own networks, or is this on aws instances in the `ap-northeast-2` region?

Unless it's a transient problem with some Fastly edge nodes (in which case it should resolve itself), this sounds like a misconfigured proxy of some sort. Do you have a proxy configured at all?

Since this is an HTTP2 error, you can also try working around it by setting the environment variable `GODEBUG=http2client=0`, or if you want to try and debug the issue further, you can set `GODEBUG=http2debug=1` to see exactly what is happening when you get the `PROTOCOL_ERROR`.

**Comment by sg21210** [comment]
It happens in my networks, not on the instances in `ap-northeast-2` region. (Maybe my message in Additional Context made you confused. That's just one of the way I tried for another network environment I have.)

I set the environment variable but I couldn't see any log after `terraform init`. I think the reason is that it takes too long to see the debug/error result (as I mentioned before, it takes 10+ minutes). The major issue occurs in performing these steps,
`- Checking for available provider plugins on https://releases.hashicorp.com...`
`- Downloading plugin for provider "aws" (1.11.0)...`
Days ago, I couldn't see any delay between those steps. However, now I can see it takes a few seconds on the Checking step, and many minutes on the Downloading step. 

I can try a workaround solution by setting `plugin_cache_dir`, but it is not perfect solution so I'm asking here. My colleagues also have these issue, and the network team here couldn't notice any problem yet. I'll keep track this problem and let you know if it was caused by our local issue.

**Comment by jbardin** [comment]
Sorry, I forgot to mention that along with the `GODEBUG=http2debug=1`, you will ned to set `TF_LOG=trace` in order to prevent the output from being filtered. 

Does it still fail if you set `GODEBUG=http2client=0`? If so, there should be a different error message, since the stream `PROTOCOL_ERROR` is only for http2.

**Comment by sg21210** [comment]
It currently works, after some **minutes**. The environmental variables showed me a bunch of logs like `Transport received DATA stream=19 ...` one by one slowly.
I suspect the low speed to download it. Isn't it related to the protocol error? I'm checking the time to manually download the file from https://releases.hashicorp.com/terraform-provider-aws/1.11.0/terraform-provider-aws_1.11.0_windows_amd64.zip, and it was around 10~20KB/s when I saw the error above. Now the speed is around 30KB/s. I couldn't check the `GODEBUG=http2client=0` option because it works with/without the option both.

**Comment by jbardin** [comment]
The only way the slow download should cause a PROTOCOL_ERROR is if there is a problem with the remote server. 

Are you saying that the download speed is the same with http1.1 and http2?
Is the speed the same for if you use another http client, like curl?

We have had one other report of slow downloads in South Korea, though I don't think they found a root cause there either. 

In the meantime, you can make use if the [Provider Plugin Cache](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache), or you can manually supply the plugin binaries with the `-plugin-dir` option.  We also provide a tool to fetch providers once to bundle them together here: https://github.com/hashicorp/terraform/tree/master/tools/terraform-bundle

**Comment by sg21210** [comment]
The speed above is with Chrome, and now I attach more results using curl.
Note that the data in each row represents a single trial under the condition. (I just concatenated them)
Long story short, they are not same but all are slow. I noticed some strange points here so I asked ISP to check this. 

The unit of the speed is Byte/second
**http1.1**
```
λ curl -O https://releases.hashicorp.com/terraform-provider-aws/1.11.0/terraform-provider-aws_1.11.0_windows_amd64.zip -0 --http1.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2 15.4M    2  325k    0     0   8004      0  0:33:47  0:00:41  0:33:06 12425^C
  6 15.4M    6 1040k    0     0  26833      0  0:10:04  0:00:39  0:09:25 21088^C
  7^C5.4M    7 1181k    0     0  31798      0  0:08:30  0:00:38  0:07:52 26766
  5 15.4M    5  858k    0     0   9674      0  0:27:57  0:01:30  0:26:27  4792^C
```

**http2**
```
λ curl -O https://releases.hashicorp.com/terraform-provider-aws/1.11.0/terraform-provider-aws_1.11.0_windows_amd64.zip -0 --http2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 24 15.4M   24 3822k    0     0  57234      0  0:04:43  0:01:08  0:03:35 63211^C
  1 15.4M    1  303k    0     0   7619      0  0:35:30  0:00:40  0:34:50  8620^C
 23 15.4M   23 3703k    0     0  22359      0  0:12:05  0:02:49  0:09:16 14755
 18 15.4M   18 3006k    0     0  66838      0  0:04:02  0:00:46  0:03:16 32750^C
```

**http2 without HTTP/1.1 upgrade**
```
λ curl -O https://releases.hashicorp.com/terraform-provider-aws/1.11.0/terraform-provider-aws_1.11.0_windows_amd64.zip -0 --http2-prior-knowledge
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 15.4M    1  197k    0     0   4535      0  0:59:39  0:00:44  0:58:55  6093^C
  6 15.4M    6  970k    0     0  27668      0  0:09:46  0:00:35  0:09:11 25838^C
  4 15.4M    4  661k    0     0  36710      0  0:07:22  0:00:18  0:07:04 23590^C
  1 15.4M    1  309k    0     0  11032      0  0:24:31  0:00:28  0:24:03 15235^C
```
Although every time spent is different, but you can see that the download speed is fluctuating. It also has high speed at first and rapidly decrease after a few seconds.

I know the `plugin_cache_dir` option, but the bundle is new to me. Thank you for your suggestion, but I'm just trying to solve the problem itself instead of using the workaround solution :)

**Comment by sg21210** [comment]
@jbardin , the ISP provider here noticed the problem and resolved it by changing the router path for international use. Now everything is okay and fast enough. Thank you so much for your help.

**Comment by jbardin** [comment]
@sg21210, Glad you found a resolution!
Thanks for following up

**Comment by calshankar** [comment]
@sg21210, I'm having the exact same issue. Can you let me know what exactly was the ISP resolution to the problem so that I can fwd the same to my ISP. Thank you

**Comment by sg21210** [comment]
@calshankar The speed had fluctuated very much, like from very low speed to normal (but slow) speed. That is 'the point' that I suspected at that time. You might sense it from those average speed above. 
I asked the providers to check if the low speed and fluctuation still occurs in their backbone switch, and then they found the problem and got a solution for it.
