### ISSUE TITLE
Issue: Terraform doesn't wait on resource values that were passed and creation before deploying module

### ISSUE THREAD

**Issue by pixelicous** [hashicorp/terraform#17633]
### Terraform Version
```
Terraform v0.11.4
+ provider.azurerm v1.3.0
```

### Terraform Configuration Files
```
module "TenantOnBoard" {
  var1 = "value1"
  var2 = "value2"
  rg_one_name         = "${azurerm_resource_group.rg_one.name}"
  rg_two_name      = "${azurerm_resource_group.rg_two.name}"

  providers = {
    "azurerm"            = "azurerm"
    "azurerm.justaname" = "azurerm.justaname"
  }
}


resource "azurerm_resource_group" "rg_one" {
  name     = "${local.name_prefix}-rg"
  location = "${var.location}"
}

resource "azurerm_resource_group" "rg_two" {
  provider = "azurerm.justaname"
  name     = "${local.name_prefix_other}-rg"
  location = "${var.location}"

}

data "azurerm_resource_group" "rg_one" {
  name = "${var.rg_one_name}"
}

data "azurerm_resource_group" "rg_two" {
  provider = "azurerm.operations"
  name     = "${var.rg_two_name}"
}

```

### Expected Behavior
The module will wait till creation of resources and then the data stream will not fail in the module.

### Actual Behavior
The resource groups are about to be created but aren't actually because terraform fails too quickly.

### Steps to Reproduce
Use a root folder and a module, pass the names of the resource groups created in the root folder ot the sub modules.

### Additional Context
If i had a way to make the module "depend" on those resources, it might have been avoided
The reason why i am doing this is that i need some resources in the same resource group to wait for others to finish, but only once all the resources inside that module finish..

**Comment by jbardin** [comment]
Hi @pixelicous,

Can you show what the structure of the modules is here?  Are the data sources shown above actually located in another module file?

Resources "depend" on others by referencing them in some way. If the variables `var.rg_one_name` and `var.rg_two_name` are referencing the actual resource groups (which it looks like they might be), then the data sources should not be read until the resources are created. Note that having a data source for a resource already in your configuration is unusual, since you can directly reference the resource itself.

If the interpolation strings are all correct, then we need to know what you mean by terraform "fails too quickly". What is the error output, and if possible, can we get the debug logs from the execution as well?

**Comment by pixelicous** [comment]
I fixed the module string, it wasn't existed. Up till the data sources it is a main.tf file in a root folder, below it are data sources inside a subfolder (Which is the module that is called above them).

What you described is what im doing, these data sources shouldnt be read until resource groups are created. i solved this by using the resource_Group resource AGAIN inside that subfolder.

What i mean by fails too quickly is that the terraform starts applying,  you see in the output that it is trying to create those resource groups, then 2seconds after the message of creating those resource groups it fails on the data sources, saying that it couldn't find those resource groups.
It shouldn't even get to the datasources because i put the resource groups names as a variable ot the module, to make it wait for those resources to finish. i will need to re-do this change on my envrionment so i can paste you debug logs.. i think i will only get to it in two days..

I understand i can just reference those resources, but how can i reference the resources that are created in the root folder from a sub module? isn't it the other way around?

**Comment by pixelicous** [comment]
@jbardin doesn't look like a provider problem, it gets into the module before it needs to and thus fails. I managed to overcome this in a different manner. Wish i had time to investigate what happened here.

Thanks for your support!
