### ISSUE TITLE
State file not saved when using s3 backend

### ISSUE THREAD

**Issue by lleszczu** [hashicorp/terraform#17644]
### Terraform Version

```
$ terraform -v
Terraform v0.11.3
+ provider.aws v1.11.0
+ provider.vault v1.0.0
```

### Terraform Configuration Files

```hcl
terraform {
  backend "s3" {
  }
}
```

### Debug Output

```
$ rm -rf .terraform

$ terraform init --force-copy -backend-config="key=<edited>/terraform.tfstate" -backend-config="region=eu-central-1" -backend-config="<edited>"

...
2018/03/20 16:47:09 [DEBUG] [aws-sdk-go] DEBUG: Request s3/GetObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET <edited>/terraform.tfstate HTTP/1.1
Host: <edited>.s3.eu-central-1.amazonaws.com
Accept-Encoding: gzip


-----------------------------------------------------
2018/03/20 16:47:09 [DEBUG] [aws-sdk-go] DEBUG: Response s3/GetObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 12901 << (this is correct size of remote state file)
Accept-Ranges: bytes
Content-Type: application/json
Date: Tue, 20 Mar 2018 15:47:10 GMT
Etag: "71a67122b192d5831f3873ecdf9f3708"
Last-Modified: Tue, 20 Mar 2018 15:10:25 GMT
Server: AmazonS3

...
```

### Expected Behavior

Local .terraform/terraform.tfstate in sync with remote file hosted on s3.

### Actual Behavior

Local .terraform/terraform.tfstate is empty
```
{
    "version": 3,
    "serial": 1,
    "lineage": "115e3fee-5b40-4721-a836-ed704468e780",
    "backend": {
        "type": "s3",
        "config": {
            "bucket": "<edited>",
            "key": "<edited>",
            "region": "eu-central-1"
        },
        "hash": 9342540184645803264
    },
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```

Key, region and bucket are correct, because I can run `terraform state pull` and it show correct state file. Unfortunately it still does not save it locally.

**Comment by jbardin** [comment]
Hi @lleszczu,

Thanks for filing the issue. 

The file `.terraform/terraform.tfstate` is unrelated to data stored in the remote state, and is used to store some internal configuration data. It only uses the state structure for various legacy reasons, and should never contain any of your resource information. 

Since you say `terraform state pull` shows the correct data, I'm going to assume everything is working correctly!

**Comment by lleszczu** [comment]
There had to be some issue with remote state file. After wiping environment and redeploying it all started working correctly.
