### ISSUE TITLE
Feature request: provisioner/local-exec  allow passing query

### ISSUE THREAD

**Issue by Flowman** [hashicorp/terraform#17669]
It would be beneficial to be able to set query variables similarly to data external query.

```hcl
provisioner "local-exec" {
  command = "test.py"

  query {
    name = "John"
  }
}
```
So inside the python file we can access the query variables. I have tired to use the new environment variable but the os.environ.get() does not pick them up.

**Comment by pkolyvas** [comment]
I'm doing a clean-up of older issues that haven't gained traction but also don't coincide with some of our current focus. While provisioners, as a whole, aren't a top priority for the team, when some time is available to focus on them we're going to use that attention for some long-standing defects.

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform, the use cases, and needs of our practitioners.
