### ISSUE TITLE
azurerm_storage_table was idempotent in 0.11.3 but supposedly not in 0.11.4

### ISSUE THREAD

**Issue by RichardSlater** [hashicorp/terraform#17660]
### Terraform Version
```
Terraform v0.11.4
+ provider.azurerm v1.3.0
```

### Terraform Configuration Files
MCVE:
```hcl
terraform {
  backend "azurerm" {
    resource_group_name  = "chatbot-170-tfstate-rg"
    storage_account_name = "chatbot170tfstatestor"
    container_name       = "tfstate"
    key                  = "terraform.tfstate"
  }
}

resource "azurerm_resource_group" "dev" {
  name     = "amido-uks-cb170-rg-bot-dev"
  location = "UK South"

resource "azurerm_storage_account" "dev" {
  name                     = "amidoukscb170"
  resource_group_name      = "${azurerm_resource_group.dev.name}"
  location                 = "${azurerm_resource_group.dev.location}"
  account_tier             = "Standard"
  account_replication_type = "GRS"
  enable_blob_encryption   = "true"

  tags {
    environment = "Development"
  }
}

resource "azurerm_storage_table" "dev" {
  name                 = "development"
  resource_group_name  = "${azurerm_resource_group.dev.name}"
  storage_account_name = "${azurerm_storage_account.dev.name}"
}
```

### Debug Output
> `$env:TF_LOG="trace"`
>  `tf apply --auto-approve 2>&1 | Out-File .\tf-log.log`

[Log File](https://github.com/RichardSlater/chatbot-170-infrastructure/blob/master/tf-log.log.gpg)
Encrypted for Hashicorp Security and signed with my [Public Key](https://keybase.io/richardslater/pgp_keys.asc?fingerprint=a6da3db0942b2d021b75f6da973ec875a6e40b5a)

### Expected Behavior
`terraform apply` completes as expected

### Actual Behavior
```
Error: Error applying plan:

1 error(s) occurred:

* module.dev.module.uksouth.azurerm_storage_table.dev: 1 error(s) occurred:

* azurerm_storage_table.dev: Error creating table "development" in storage account "amidoukscb170": storage: service returned error: StatusCode=409, ErrorCode=TableAlreadyExists, ErrorMessage=The table specified already exists.
RequestId:4fb86a90-a002-000a-3928-c11a35000000
Time:2018-03-21T15:23:31.1865693Z, RequestInitiated=Wed, 21 Mar 2018 15:23:30 GMT, RequestId=4fb86a90-a002-000a-3928-c11a35000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
```

### Steps to Reproduce
1. `terraform init`
2. `terraform get`
3. `terraform apply`

### Additional Context
Confirmed both on Windows (Localhost) and Ubuntu 14 (Shippable). Slightly irritatingly now I have upgraded to 0.11.4 I can't downgrade my state file to 0.11.3.

### References
None observed.

**Comment by jbardin** [comment]
Hi @RichardSlater,

Sorry you're having an issue here.
Are you certain that the only difference is terraform 0.11.4 vs 0.11.3, or was the azure provider updated as well?

**Comment by RichardSlater** [comment]
Let me check, I'm going to have to kill off my state and try the old version.

**Comment by jbardin** [comment]
Thanks. 
For the record, I'm not aware of any provider resources that allow creation when they already exist. This almost always requires explicitly importing a resource into the state, so that may have been considered a bug in the `azurerm_storage_table` resource.

**Comment by RichardSlater** [comment]
```
Terraform v0.11.3
+ provider.azurerm v1.3.0
```

Looks to me like the `azurerm` provider is the same across both Terraform-v0.11.3 and Terraform-v0.11.4.

**Comment by RichardSlater** [comment]
I assume this is related: terraform-providers/terraform-provider-azurerm#1003

It's possible that I have incorrectly attributed this to Terraform rather than the `azurerm` provider.

**Comment by jbardin** [comment]
Hi @RichardSlater,

Running your config directly doesn't reproduce the issue for me. If you're saying that the `azurerm_storage_table` already exists before applying the configuration, then this is the expected failure and I'm not sure how it would have worked previously.

**Comment by RichardSlater** [comment]
That's strange let me extract it out to a separate repository, I've been able to repro it consistently.  Seems I'm not the only one, given the final comment in terraform-providers/terraform-provider-azurerm#1003.

**Comment by RichardSlater** [comment]
# Terraform 0.11.3
**Prerequisites: Terraform 0.11.3 installed**

```
> git clone git@github.com:RichardSlater/terraform-0.11.4-azurerm-idempotence.git
> cd terraform-0.11.4-azurerm-idempotence
> git checkout 0.11.3
> terraform init
> terraform apply
< Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
> terraform apply
< Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
> terraform destroy
< Destroy complete! Resources: 3 destroyed.
```

# Terraform 0.11.4
**Prerequisites: Terraform 0.11.4 installed**

```
> git clone git@github.com:RichardSlater/terraform-0.11.4-azurerm-idempotence.git
> cd terraform-0.11.4-azurerm-idempotence
> git checkout 0.11.4
> terraform init
> terraform apply
< Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
> terraform apply
< Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
> terraform destroy
< Destroy complete! Resources: 3 destroyed.
```

Well that's odd... going to add Key Vault back in to see if that has an effect.

**Comment by RichardSlater** [comment]
Yeah, no idea why I can't reproduce it within the test repo, I'll try the original repo tomorrow.

**Comment by RichardSlater** [comment]
Having deleted the state and all of the resources in my diagnostic steps I can no longer reproduce this issue, have upgraded to Terraform 0.11.5 and everything is running well.

**Comment by pixelicous** [comment]
Im having the same problem, different state file every time i launch, even removed the .terraform folder..

**Comment by RichardSlater** [comment]
Are you using remote state or pure local state?

**Comment by pixelicous** [comment]
im using backends and workspaces
