### ISSUE TITLE
Terraform keeps destroying even if it cant

### ISSUE THREAD

**Issue by povils** [hashicorp/terraform#17662]
Terraform version ```v0.11.4```
For example when I have managed security group which is attached manually to not managed security group and I try to ```terraform destroy```, terraform keeps trying to destroy it, but of course, it can't. But the problem is that I don't want to wait 10 minutes.

**Comment by jbardin** [comment]
Hi @povils,

This sounds like an issue with a particular provider. Terraform itself doesn't know how long a particular resource will take to destroy, so it can only keep waiting until a predetermined timeout. If the provider is continuing to delete the resource, it may not have enough information to know it can't succeed, or the remote API properly report the failure. 

If you have a specific resource in mind, I would file the issue with the appropriate provider, along with a sample configuration and output you received.
