### ISSUE TITLE
"Terraform Destroy" destroys 0 objects on Azure

### ISSUE THREAD

**Issue by cofonseca** [hashicorp/terraform#17664]
### Terraform Version

```
Terraform v0.11.4
provider.azurerm v1.3.0
```

### Terraform Configuration Files

main.tf:

```hcl
resource "azurerm_resource_group" "rg_eh" {
  name     = "bpcEventHubPOC"
  location = "East US"
}

resource "azurerm_eventhub_namespace" "eh_ns" {
  name                = "bpcEventHubNamespace"
  location            = "${azurerm_resource_group.rg_eh.location}"
  resource_group_name = "${azurerm_resource_group.rg_eh.name}"
  sku                 = "Standard"
  capacity            = 1
  depends_on          = ["azurerm_resource_group.rg_eh"]
}

resource "azurerm_eventhub" "eh" {
  name                = "bpcEventHub"
  namespace_name      = "${azurerm_eventhub_namespace.eh_ns.name}"
  resource_group_name = "${azurerm_resource_group.rg_eh.name}"
  partition_count     = 2
  message_retention   = 1
  depends_on          = ["azurerm_eventhub_namespace.eh_ns"]
}

```

I also have a variables.tf to define my variables, terraform.tfvars containing my variable data, and provider.tf with the usual Azure connection info. There's nothing else to my config aside from what's been posted here.

### Debug Output
https://pastebin.com/sdMk7RfD

### Expected Behavior
Terraform should destroy the resources that it created.

### Actual Behavior
Terraform removes the resources from the state file, but does not delete them in Azure.

### Steps to Reproduce
1. Terraform Plan
2. Terraform Apply
3. Terraform Plan -Destroy
4. Terraform Destroy

### Additional Context
I am trying to build a very simple environment in Azure, consisting of a single resource group, and an event hub. Terraform Plan and Terraform Apply run perfectly fine. The resources are created in ~90 seconds and I can see everything in the Azure GUI.

When I attempt to destroy these resources, the resources are removed from the tfstate file, but are not removed from Azure. There are no errors.

Terraform Plan -Destroy returns the following output: "No changes. Infrastructure is up-to-date."

Terraform Destroy normally returns a list of items it plans to destroy, but doesn't return anything. After entering "yes" to confirm, Terraform Destroy returns the following output: Destroy complete! Resources: 0 destroyed.

After running the destroy, nothing has been removed from Azure, but all resources are removed from the .tfstate file. I have to remove the resources manually from Azure.

Additionally, if I run a Terraform Refresh immediately after running Terraform Apply, it removes everything from the tfstate file.

The following screenshot shows the apply, plan, and destroy output: http://prntscr.com/iugz26

**Comment by jbardin** [comment]
Hi @cofonseca,

If you're using local state on windows, it's likely that this has nothing to do with azure, and you're running into #17620.

**Comment by cofonseca** [comment]
Hi @jbardin,

Thanks for the quick reply!

I am indeed using local state on Windows 10. #17620 does sound similar to what I'm experiencing, but appears to be closed. I'm assuming that change has not yet been brought into Production. Any suggestions on how I could work around this for now?

**Comment by jbardin** [comment]
I'm planning on getting a patch release out shortly, in the meantime you could try `-lock=false`, since the issue is caused by how windows handles file locking.

**Comment by cofonseca** [comment]
@jbardin that worked perfectly. Looking forward to the release. Thank you very much for your assistance!
