### ISSUE TITLE
symlink error during terraform get

### ISSUE THREAD

**Issue by piusranjan** [hashicorp/terraform#17689]
### Terraform Version
0.11.5.
0.9.8

```
...
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "eu-west-1"
}

module "vpc" {
  source = "../../"

  name = "simple-example"

  cidr = "10.0.0.0/16"

  azs             = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true

  tags = {
    Owner       = "user"
    Environment = "dev"
  }
}
...
```

### Actual Behavior

when I am running terraform get in below folder , I am getting error
/home/vagrant/streams/learning/tfm/lab/terraform-aws-vpc/examples/simple-vpc

Error: Error loading modules: error downloading 'file:///home/vagrant/streams/learning/tfm/lab/terraform-aws-vpc': symlink /home/vagrant/streams/learning/tfm/lab/terraform-aws-vpc .terraform/modules/a083b5b9dd7e90361acfae606df96064: protocol error

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `cloned https://github.com/terraform-aws-modules/terraform-aws-vpc
2. `cd terraform-aws-vpc/examples/simple-vpc
3. terraform Run  get

**Comment by jbardin** [comment]
Hi @piusranjan,

Sorry you're having an issue here. The config you've provided doesn't contain the module source that is causing the issue. 

Can you provide the source string of the module that is causing the error, and its actual location?
If you could also provide the logs from `terraform init` as well? (you generally don't need to ever use `terraform get`)

**Comment by jbardin** [comment]
Hi @piusranjan,

Sorry, I might have missed the edits last time, but I see the source of the module in question now.

Running `terraform init` from the `examples/simple-vpc` directory works correctly for me. 
I'm not sure what could be causing the error, but you could try removing the `.terraform` directory before running `init` as well.

If that still doesn't solve the issue, the debug logs would probably be the nest step to troubleshoot this.

**Comment by piusranjan** [comment]
Thanks a lot for your help. It is now working. I am new to  Terraform . My source attribute   was not correct.

**Comment by piusranjan** [comment]
Hi @jbardin ,

I am again facing the issue .I am getting below error.

[vagrant@vagrantbox simple-vpc]$ terraform init
Initializing modules...
- module.vpc
Error downloading modules: Error loading modules: host registry.terraform.io does not provide Terraform modules



provider "aws" {
  region = "eu-west-1"
}

module "vpc" {


  source  = "terraform-aws-modules/vpc/aws"

  name = "simple-example"

  cidr = "10.0.0.0/16"

  azs             = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true

  tags = {
    Owner       = "user"
    Environment = "dev"
  }
}

**Comment by piusranjan** [comment]
Below is the log 

2018/04/03 14:42:40 [TRACE] module source: "terraform-aws-modules/vpc/aws"
2018/04/03 14:42:40 [TRACE] "terraform-aws-modules/vpc/aws" is a registry module
2018/04/03 14:42:40 [INFO] no matching version for "terraform-aws-modules/vpc/aws"<1.9.1>, no versions found
2018/04/03 14:42:40 [DEBUG] matched "terraform-aws-modules/vpc/aws" version  for 1.9.1
2018/04/03 14:42:40 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2018/04/03 14:42:40 [WARN] Failed to request discovery document: Get https://registry.terraform.io/.well-known/terraform.json: proxyconnect tcp: tls: oversized record received with length 20527
2018/04/03 14:42:40 [DEBUG] plugin: waiting for all plugin processes to complete...
2018/04/03 14:52:45 [INFO] Terraform version: 0.11.5  342c529aa58d824f2f2ed1f6ec6118059876aad0
2018/04/03 14:52:45 [INFO] Go runtime version: go1.10
2018/04/03 14:52:45 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2018/04/03 14:52:45 [DEBUG] Attempting to open CLI config file: /home/vagrant/.terraformrc
2018/04/03 14:52:45 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/04/03 14:52:45 [INFO] CLI command args: []string{"init"}
2018/04/03 14:52:45 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=linux&signature=414e4ff5-e776-cb80-bf7c-3e6e005146ae&version=0.11.5: proxyconnect tcp: tls: oversized record received with length 20527
2018/04/03 14:52:45 [DEBUG] command: loading backend config file: /home/vagrant/streams/learning/tfm/lab/terraform-aws-vpc/examples/simple-vpc
2018/04/03 14:52:45 [TRACE] module source: "terraform-aws-modules/vpc/aws"
2018/04/03 14:52:45 [TRACE] "terraform-aws-modules/vpc/aws" is a registry module
2018/04/03 14:52:45 [INFO] no matching version for "terraform-aws-modules/vpc/aws"<1.9.1>, no versions found
2018/04/03 14:52:45 [DEBUG] matched "terraform-aws-modules/vpc/aws" version  for 1.9.1
2018/04/03 14:52:45 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2018/04/03 14:52:45 [WARN] Failed to request discovery document: Get https://registry.terraform.io/.well-known/terraform.json: proxyconnect tcp: tls: oversized record received with length 20527
2018/04/03 14:52:45 [DEBUG] plugin: waiting for all plugin processes to complete..

**Comment by piusranjan** [comment]
I am stuck now .

**Comment by jbardin** [comment]
Hi @piusranjan,

You error is `proxyconnect tcp: tls: oversized record received with length 20527`.
It looks like you have a proxy incorrectly configured for your environment, preventing terraform from communicating with the registry.

**Comment by piusranjan** [comment]
@jbardin ,
below  is working for me.  Had it been the issue with proxy , it would not have worked .
wget  https://releases.hashicorp.com/terraform-provider-aws/

Thanks,
Pius

**Comment by piusranjan** [comment]
This is also working :
wget  https://registry.terraform.io/.well-known/terraform.json

**Comment by piusranjan** [comment]
@jbardin  do  I need to do some other configuration setting ?

**Comment by jbardin** [comment]
Hi @piusranjan,

Do you have HTTP_PROXY or HTTPS_PROXY (upper or lowercase) set in your environment?
A `tls: oversized record` is usually when a server returns an HTTP response during a TLS handshake.

**Comment by piusranjan** [comment]
Yes it set.  Even , I unset it , i am getting same error. And strangely  it worked once last week.

**Comment by jbardin** [comment]
Yes, _which_ are set? Do you by chance have `https_proxy` pointing to an http server?

It's a bit strange you would get a proxy error if you unset all the proxy variables. Do you have a captive portal on your network?

This is still probably a plain text response to the TLS handshake, which should be easy to see in a network trace. Since the response should not be anywhere near `20527` bytes, and all requests return the same number of bytes, I'm guessing that it's some sort of proxy error or authentication page.

Since this isn't really an issue that Terraform can solve, and GitHub issues are not a general support channel, I'm gong to close this out for now. If it turns out to be something that terraform should handle, we can revisit the situation.
