### ISSUE TITLE
Interpolation and referencing should allow char escaping

### ISSUE THREAD

**Issue by Binternet** [hashicorp/terraform#17688]
### Terraform Version

```
0.11.5
```

### Terraform Configuration Files

```hcl
resource "aws_iam_user_policy" "my-policy-name" {
    name   = "my-policy-name"
    user   = "${aws_iam_user.firstname.lastname.name}"
    policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      ...
      "Action": [
        "codedeploy:*"
      ],
      "Resource": "*"
    },
    {
     ...
    }
  ]
}
POLICY
}
```

### Crash Output

Error: resource 'aws_iam_user_policy.firstname.lastname' config: unknown resource 'aws_iam_user.firstname' referenced in variable aws_iam_user.firstname.lastname.name
### Expected Behavior

It should be referencing a user id that contains a `dot` in its name/id.
### Actual Behavior

Broken reference for a resource name.

**Comment by Binternet** [comment]
#9145

**Comment by Binternet** [comment]
I see its closed at https://github.com/hashicorp/terraform/issues/9145

**Comment by jbardin** [comment]
Hi @Binternet,

Looks like you found the correct issue here. It isn't that you need to escape the `.` in interpolation, it's that individual identifiers can't contain a `.`. 

We're working on an overhaul of the configuration layer at the moment, so this should be more clear in a future versions, with better errors to diagnose issues in the configuration.
