### ISSUE TITLE
apply succeeds even with "Error parsing JSON: invalid character '$' looking for beginning of value" with template for template_body of azurerm_template_deployment

### ISSUE THREAD

**Issue by puttagunta** [hashicorp/terraform#17684]
### Terraform Configuration Files

> scheduler-template/main.tf
> ```
> data "template_file" "init" {
>   template = "${file("${path.module}/scheduler-arm-template.tpl")}"
> 
>   vars {
>     sch-name             = "${var.sch-name}"
>     sch-targetResourceId = "${var.sch-targetResourceId}"
>   }
> }
> 
> ```
> scheduler-template/variables.tf
> ```
> variable "sch-name" {}
> variable "sch-targetResourceId" {}
> ```
> scheduler-template/outputs.tf
> ```
> output "sch-rendered" {
>   value = "${data.template_file.init.rendered}"
> }
> ```

> **Usage**
> ```
> module "scheduler-template" {
>   source               = "../../modules/scheduler-template"
>   sch-name             = "shutdown-computevm-${azurerm_virtual_machine.config.name}"
>   sch-targetResourceId = "${azurerm_virtual_machine.config.id}"
> }
> 
> resource "azurerm_template_deployment" "scheduler" {
>   name                = "${azurerm_virtual_machine.config.name}-sch"
>   resource_group_name = "${var.resource_group_name}"
>   template_body       = "${module.scheduler-template.sch-rendered}"
>   deployment_mode = "Incremental"
> }
> ```

### Debug Output

> output in the terraform.tfstate
\"template_body\": "{\"$schema\":\"https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"resources\":[{\"apiVersion\":\"2016-05-15\",\"location\":\"eastus2\",\"name\":\"shutdown-computevm-sree3-xxx-vm\",\"properties\":{\"dailyRecurrence\":{\"time\":\"1900\"},\"notificationSettings\":{\"status\":\"Disabled\",\"timeInMinutes\":30},\"provisioningState\":\"Succeeded\",\"status\":\"Enabled\",\"targetResourceId\":\"/subscriptions/ce99575f-feda-4aeb-927c-f22b7e07c6d4/resourceGroups/sree3/providers/Microsoft.Compute/virtualMachines/sree3-xxx-vm\",\"taskType\":\"ComputeVmShutdownTask\",\"timeZoneId\":\"Eastern Standard Time\"},\"scale\":null,\"type\":\"microsoft.devtestlab/schedules\"}]}"

> gists for plan and apply
> Plan
> https://gist.github.com/puttagunta/fe158c3392401d7e8ad92d50843c6e59
> Apply
> https://gist.github.com/puttagunta/34f03dc0e31d13b53699182b51058a24

### Expected Behavior
If it is a legitimate error 

> terraform apply

 should fail and 

> terraform plan

should also fail with a valid error message

### Actual Behavior
Plan is successfully generated with the following message
> Plan: 2 to add, 0 to change, 0 to destroy.
with no clue that there was an error unless, we take a look at the output for that specific resource, which has the following error
>  template_body: "Error parsing JSON: invalid character '$' looking for beginning of value"
The apply succeeds with all green and the corresponding resource also gets created, with the error in the output of the resource in the console as in the plan.

### Steps to Reproduce
do 
> terraform plan ...
> terraform apply ...

### References
#5462

**Comment by apparentlymart** [comment]
Hi @puttagunta! Sorry for this issue and thanks for reporting it.

This seems to be an issue in the `azurerm` provider in particular, in its `normalizeJson` helper function: https://github.com/terraform-providers/terraform-provider-azurerm/blob/ee0156b6c92ab0ac3212246ae75a8a6171eac3c1/azurerm/resource_arm_template_deployment.go#L253-L264

Therefore I'm going to have our bot move this issue over the repository for that provider. Thanks again for reporting this.

**Comment by puttagunta** [comment]
Ah! I should've reported there, but, somehow thought it is generic. 😊
________________________________

**Comment by apparentlymart** [comment]
No worries @puttagunta! It's not always easy to tell. (I had to go read the source code myself to decide!)
