### ISSUE TITLE
StackOverflowException from remote-exec uploading a file

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform#17693]
Using a Terraform remote-exec provisioner to execute a PowerShell script that uploads a file to an S3 bucket from a Windows 2008 R2 server fails with a `StackOverflowException`. However, running the same script on the server works fine. Whether the script fails during remote-exec depends on the upload size. Running the PowerShell script on the server, files from 0-500MB work fine (largest I've tested). Running from Terraform remote-exec provisioner, the script fails for files 17MB or larger. (NOTE: I've tried uploading using both AWS Tools and AWS CLI. Both produce memory errors.) [Issue also posted at terraform-providers/terraform-provider-aws#3889]

### Terraform Version
Terraform 0.11.5

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "windows" {
  count                       = "1"
  ami                         = "ami-e935fc94" #base win 2008 R2 datacenter
  instance_type               = "t2.micro"

  connection {
    type     = "winrm"
    user     = "<username>"
    password = "<password>"
    timeout  = "30m"
  }

  provisioner "file" {
    source      = "windows/check_build.ps1"
    destination = "C:\\scripts\\check_build.ps1"
  }

  provisioner "remote-exec" {
    inline = [
      "powershell.exe -File C:\\scripts\\check_build.ps1"
    ]
  }
}
```
check_build.ps1:
```ps1
$f = new-object System.IO.FileStream C:\Temp\test.dat, Create, ReadWrite
$f.SetLength(40MB) #if this is reduced to 14MB, it works
$f.Close()
Write-Host (Get-Date -UFormat "%Y/%m/%d %T")
Write-S3Object -BucketName "mybucket" -Folder "C:\Temp" -KeyPrefix "20180322" -SearchPattern "*.dat"
```

### Debug Output
Note: The exact time that the upload took place is shown in output. Script displays the time right before upload. Nothing interesting happens in the debug log at that time.  
```
aws_instance.windows (remote-exec): 2018/03/22 15:10:50
aws_instance.windows (remote-exec): Process is terminated due to StackOverflowException.
```
[Debug gist](https://gist.github.com/YakDriver/8b9e7d3bf31a2f0ab76425d05144f626)

### Expected Behavior
The script launched by the remote-exec provisioner should upload the file to the S3 bucket.

### Actual Behavior
```
aws_instance.windows (remote-exec): Process is terminated due to StackOverflowException.
```
(NOTE: If I use the aws cli in the check_build.ps1 instead of AWS Tools, I get a stack trace with the error `MemoryError`.)
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by YakDriver** [comment]
Hey @jbardin, 

You are absolutely right. It took a minute to figure out a way around this but I did using userdata to install the hotfix and then reboot before opening WinRM for the remote-exec. I give all the details  [here](https://stackoverflow.com/questions/49435628/powershell-stackoverflowexception-from-terraform-runs-fine-locally/49583831#49583831) if anyone else is looking for a workaround.

**Comment by jbardin** [comment]
Thanks for the follow up @YakDriver!
