### ISSUE TITLE
terraform init does not fail when -backend-config fails

### ISSUE THREAD

**Issue by DrStrangepork** [hashicorp/terraform#17709]
### Terraform Version
```
Discovered with 0.11.3, verified condition not fixed in 0.11.5
```

### Terraform Configuration Files
None

### Debug Output
```
terraform init -get=true -input=false -no-color -backend-config=bucket=bucket-terraform-state -backend-config=region=eu-west-1 -backend-config=key=s3-buckets.tfstate
2018/03/28 11:04:41 [INFO] Terraform version: 0.11.5
2018/03/28 11:04:41 [INFO] Go runtime version: go1.10
2018/03/28 11:04:41 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.5/bin/terraform", "init", "-get=true", "-input=false", "-no-color", "-backend-config=bucket=bucket-terraform-state", "-backend-config=region=eu-west-1", "-backend-config=key=s3-buckets.tfstate"}
2018/03/28 11:04:41 [DEBUG] Attempting to open CLI config file: /Users/n0304144/.terraformrc
2018/03/28 11:04:41 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/03/28 11:04:41 [INFO] CLI command args: []string{"init", "-get=true", "-input=false", "-no-color", "-backend-config=bucket=bucket-terraform-state", "-backend-config=region=eu-west-1", "-backend-config=key=s3-buckets.tfstate"}
2018/03/28 11:04:41 [DEBUG] command: loading backend config file: /Users/Me/project/s3-buckets
2018/03/28 11:04:41 [INFO] command: empty terraform config, returning nil
2018/03/28 11:04:41 [DEBUG] command: no data state file found for backend config
2018/03/28 11:04:41 [DEBUG] New state was assigned lineage "364d7a06-be2a-7c8b-5669-727395f51ba3"
2018/03/28 11:04:41 [INFO] command: backend initialized: <nil>
2018/03/28 11:04:41 [DEBUG] checking for provider in "."
2018/03/28 11:04:41 [DEBUG] checking for provider in "/usr/local/Cellar/terraform/0.11.5/bin"
2018/03/28 11:04:41 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2018/03/28 11:04:41 [DEBUG] found provider "terraform-provider-aws_v1.12.0_x4"
2018/03/28 11:04:41 [DEBUG] found provider "terraform-provider-template_v1.0.0_x4"
2018/03/28 11:04:41 [DEBUG] found valid plugin: "aws", "1.12.0", "/Users/Me/project/s3-buckets/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.12.0_x4"
2018/03/28 11:04:41 [DEBUG] found valid plugin: "template", "1.0.0", "/Users/Me/project/s3-buckets/.terraform/plugins/darwin_amd64/terraform-provider-template_v1.0.0_x4"
2018/03/28 11:04:41 [DEBUG] checking for provisioner in "."
2018/03/28 11:04:41 [DEBUG] checking for provisioner in "/usr/local/Cellar/terraform/0.11.5/bin"
2018/03/28 11:04:41 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2018/03/28 11:04:41 [INFO] command: backend <nil> is not enhanced, wrapping in local
2018/03/28 11:04:41 [DEBUG] checking for provider in "."
2018/03/28 11:04:41 [DEBUG] checking for provider in "/usr/local/Cellar/terraform/0.11.5/bin"
2018/03/28 11:04:41 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2018/03/28 11:04:41 [DEBUG] found provider "terraform-provider-aws_v1.12.0_x4"
2018/03/28 11:04:41 [DEBUG] found provider "terraform-provider-template_v1.0.0_x4"
2018/03/28 11:04:41 [DEBUG] found valid plugin: "template", "1.0.0", "/Users/Me/project/s3-buckets/.terraform/plugins/darwin_amd64/terraform-provider-template_v1.0.0_x4"
2018/03/28 11:04:41 [DEBUG] found valid plugin: "aws", "1.12.0", "/Users/Me/project/s3-buckets/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.12.0_x4"
2018/03/28 11:04:41 [DEBUG] plugin requirements: "template"=""
2018/03/28 11:04:41 [DEBUG] plugin requirements: "aws"="~> 1.6"

Initializing provider plugins...
2018/03/28 11:04:41 [DEBUG] checking for provider in "."
2018/03/28 11:04:41 [DEBUG] checking for provider in "/usr/local/Cellar/terraform/0.11.5/bin"
2018/03/28 11:04:41 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2018/03/28 11:04:41 [DEBUG] found provider "terraform-provider-aws_v1.12.0_x4"
2018/03/28 11:04:41 [DEBUG] found provider "terraform-provider-template_v1.0.0_x4"
2018/03/28 11:04:41 [DEBUG] found valid plugin: "template", "1.0.0", "/Users/Me/project/s3-buckets/.terraform/plugins/darwin_amd64/terraform-provider-template_v1.0.0_x4"
2018/03/28 11:04:41 [DEBUG] found valid plugin: "aws", "1.12.0", "/Users/Me/project/s3-buckets/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.12.0_x4"
2018/03/28 11:04:41 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2018/03/28 11:04:41 [DEBUG] found provider "terraform-provider-aws_v1.12.0_x4"
2018/03/28 11:04:41 [DEBUG] found provider "terraform-provider-template_v1.0.0_x4"

2018/03/28 11:04:41 [DEBUG] plugin: waiting for all plugin processes to complete...
```

### Expected Behavior
The tfstate file DOES exist but downloading fails. I am running `terraform init` with an explicit `-backend-config` option, so I would expect terraform either to fail if the state file cannot be obtained or at least to report that the state file was not found, if the default action is to ignore and continue.

### Actual Behavior
```
aws s3 cp s3://lm-emea-dev-terraform-state/s3-buckets.tfstate .
download failed: s3://lm-emea-dev-terraform-state/s3-buckets.tfstate to ./s3-buckets.tfstate An error occurred (InvalidArgument) when calling the GetObject operation: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4. You can enable AWS Signature Version 4 by running the command: 
aws configure set s3.signature_version s3v4
```

### Steps to Reproduce
When the state file s3-buckets.tfstate is saved with AWS:KMS encryption
```
terraform init -get=true -input=false -no-color -backend-config=bucket=bucket-terraform-state -backend-config=region=eu-west-1 -backend-config=key=s3-buckets.tfstate
```

**Comment by jbardin** [comment]
Hi @DrStrangepork,

Sorry you're having an issue with this, but I'm not quite sure what the issue is yet, as `-backend-config fails` can't really fail in this way, since it's just passing values into the config. The `File doesn't exist, but doesn't need to. Ignoring` is correct, but not really relevant to backend configuration. There must be a config file, since you can't run `init` without one, are there any attributes in the backend config at all? Do you need to set `encrypt = true` for your s3 configuration?

If I understand correctly, you're expecting an error from `init`, but since configuring a backend during `init` doesn't download the state file, there is no way for the client to know if the state is accessible until you run a command that requires state access.

**Comment by jbardin** [comment]
If there is no `.terraform` directory, then the debug output indicating that the stored backend config is not there would be expected.

Sorry, but I'm still unclear as to what the original issue is. You said in the first post that "The tfstate file DOES exist but downloading fails". Can you provide the error from terraform indicating what the failure was?

I tried some combinations with remote state using `aws:kms` and I haven't gotten it to fail, with `init` or subsequent `plan` or `apply`

**Comment by DrStrangepork** [comment]
There was no error message, and that fact is the cause for this issue.

The debug output above is the resulting output from attempting to use the backend config for a tfstate file with `aws:kms` encryption in place but with
```
[default]
s3 =
    signature_version = s3v4
```
NOT configured in the the `~/.aws/config` file. Adding that configuration to the `~/.aws/config` file caused the same backend config to work as expected.

**Comment by jbardin** [comment]
Is there an error from terraform for `plan` or `apply`? If there is no error from terraform at any point, I'm not sure what it is we can do.

The only error shown above is from the `aws` cli, but terraform does not use the `aws` cli.

**Comment by DrStrangepork** [comment]
I'm not sure what I'm not communicating. The problem is the fact that the backend config - the tfstate file on the s3 bucket - is encrypted with `aws:kms` encryption. In this case, terraform will find the backend config but cannot read it. However, terraform considers the backend config to be missing:
```
[INFO] command: empty terraform config, returning nil
[DEBUG] command: no data state file found for backend config
```
It would be more accurate to report that there was an error/problem with downloading the config rather than reporting that there is no backend config.

**Comment by jbardin** [comment]
The latter DEBUG message is perfectly normal, and expected when initializing a new config. However, the former means terraform is not locating a `terraform` configuration block. What do the `terraform` and `backend` blocks looks like in your configuration, and where are they located? 

If there is no backend config however, I'm not sure how you're having problems with the encryption method failing, since in that case it would not attempt to save to the s3 backend at all.

**Comment by DrStrangepork** [comment]
Closing this issue, as we have migrated to Artifactory as a backend, in part because of this issue
