### ISSUE TITLE
Suggestion: Removing an old bash / zsh completion

### ISSUE THREAD

**Issue by ryosan-470** [hashicorp/terraform#17702]
Hi, all. I usually use Terraform on my terminal and I like zsh completions.  My zsh configuration contains a [terraform plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/terraform) in oh-my-zsh, but because that plugin is so old it does not fully complement the recent terraform commands. (eg. `teraform workspace`)
First, I thought that I would like ti contribute to the oh-my-zsh, but I did it would be better to rewrite Terraform's completion settings. I found out that the completions was generated automatically. 
Therefore, by deleting the old configuration file, I think that users who use supplemental functions can use the latest complementary function without being confused.
Since I have already created the PR, please review it if you agree. 

PR: #17527

**Comment by jbardin** [comment]
Sounds reasonable. Merged!
