### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by majkelcc** [hashicorp/terraform#17715]
### Terraform Version

```
Terraform v0.11.5
+ provider.aws v1.12.0
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

https://gist.github.com/majkelcc/579736ffe449fdc15fe3ea8d953837d9

**Comment by JPablomr** [comment]
I'm having this problem as well. Seems to be related to NLBs somehow. 

Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.12.0
+ provider.softlayer (unversioned)
+ provider.template v1.0.0
```
Crash Output
https://gist.github.com/JPablomr/0d68d6dea3a970f188f5fb95a2821cfa
