### ISSUE TITLE
Elastic Beanstalk Environment Tag "Name" should not be editable

### ISSUE THREAD

**Issue by DemonR** [hashicorp/terraform#17712]
According to Elastic Beanstalk documentation, "Name" is one of the default tags and can't be edited. However if the "Name" tag is set in the terraform script, it will still try to apply the change.

### Terraform Version
```
$ terraform -v
Terraform v0.11.5
```

### Terraform Configuration Files

```hcl
resource "aws_elastic_beanstalk_environment" "xxxxxxx_env" {
  name                = "${var.service_name}-${var.environment}"
  application         = "${aws_elastic_beanstalk_application.xxxxxxx.name}"
  solution_stack_name = "64bit Amazon Linux 2017.09 v2.6.4 running Python 3.6"
  tier                = "Worker"
  tags {
    Environment = "${var.environment}"
    Name        = "New Tag Name"
  }
}
```
# Scenarios:
### Expected Behavior
"Name" tag is not applied, or report an error

### Actual Behavior
Elastic Beanstalk:
>2018-03-27 16:38:00 UTC-0700 | ERROR | Environment tag update failed.
-- | -- | --
2018-03-27 16:37:59 UTC-0700 | ERROR | Service:AmazonCloudFormation, Message:No updates are to be performed.
2018-03-27 16:37:59 UTC-0700 | INFO | Starting environment tag update.

Terraform:
```Error: Error applying plan:

1 error(s) occurred:

* module.xxxxxxx.aws_elastic_beanstalk_environment.xxxxxxx_env: 1 error(s) occurred:

* aws_elastic_beanstalk_environment.xxxxxxx_env: Error waiting for Elastic Beanstalk Environment (e-xxxxx) to become ready: 2 error(s) occurred:

* 2018-03-27 23:37:59.698 +0000 UTC (e-xxxxx) : Service:AmazonCloudFormation, Message:No updates are to be performed.
* 2018-03-27 23:38:00.297 +0000 UTC (e-xxxxx) : Environment tag update failed.
```

## 2. if "Name" tag is present, and there is other change to the Elastic Beanstalk environment 
(in this case changing health monitoring from basic to enhanced)

### Expected Behavior
"Name" tag is not applied, or report an error

### Actual Behavior
Elastic Beanstalk throws the same error as before:

> 2018-03-28 10:19:35 UTC-0700 | ERROR | Environment tag update failed.
-- | -- | --
2018-03-28 10:19:34 UTC-0700 | ERROR | Service:AmazonCloudFormation, Message:No updates are to be performed.
2018-03-28 10:19:34 UTC-0700 | INFO | Starting environment tag update.

But terraform reports the tag is updated:

```  tags.Name:                    "" => "New Tag Name"```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by jamie-wearsafe** [comment]
Here is how I strip out items from lists.

For example: If you have a Tag Map for Elastic Beanstalk and it includes Name as one of the keys.
You can strip it out.

```hcl
## Beanstalk Applications can't have a Name tag in their tags list. 
locals {
  keys       = "${keys(module.bs_label.tags)}"
  name_index = "${index(local.keys, "Name")}"

  keys_before   = "${slice(local.keys, 0, local.name_index)}"
  keys_after    = "${slice(local.keys, local.name_index + 1, length(local.keys))}"
  values        = "${values(module.bs_label.tags)}"
  values_before = "${slice(local.values, 0, local.name_index)}"
  values_after  = "${slice(local.values, local.name_index + 1, length(local.values))}"

  tags = "${zipmap(concat(local.keys_before, local.keys_after), concat(local.values_before, local.values_after))}"
}
```
