### ISSUE TITLE
remote-exec seems not working with Windows 2012 R2 box

### ISSUE THREAD

**Issue by kaluznyt** [hashicorp/terraform#17728]
### Terraform Version

```
C:\WINDOWS\system32>terraform -v
Terraform v0.11.5
```

### Terraform Configuration Files

```hcl
  provisioner "remote-exec" {
    connection = {
      type     = "winrm"
      user     = "admin"
      password = "admin"
      agent    = "false"
      insecure = "true"
    }

    inline = [
      "echo ${element(var.machine_names, count.index)} > C:/salt/conf/minion_id",
      "echo ${var.salt_master_ip} ${var.salt_master_host} >> %SYSTEMROOT%/system32/drivers/etc/hosts",
      "net stop salt-minion",
      "net start salt-minion",
      "powershell -Command \"&{Rename-Computer -NewName ${element(var.machine_names, count.index)} -Restart}\"",
      "netsh interface ip set address Ethernet0 static ${element(var.machine_private_ips,count.index)} ${var.vsphere_private_network_netmask} ${var.vsphere_private_network_gateway} 1",
    ]
  }
...
```

### Expected Behavior

Provisioner commands should be applied to the target machine.

### Actual Behavior

```
vsphere_virtual_machine.environment_virtual_machines: Still creating... (50s elapsed)
vsphere_virtual_machine.environment_virtual_machines: Still creating... (1m0s elapsed)
vsphere_virtual_machine.environment_virtual_machines: Still creating... (1m10s elapsed)
vsphere_virtual_machine.environment_virtual_machines: Provisioning with 'remote-exec'...
vsphere_virtual_machine.environment_virtual_machines (remote-exec): Connecting to remote host via WinRM...
vsphere_virtual_machine.environment_virtual_machines (remote-exec):   Host: 192.168.77.45
vsphere_virtual_machine.environment_virtual_machines (remote-exec):   Port: 5985
vsphere_virtual_machine.environment_virtual_machines (remote-exec):   User: admin
vsphere_virtual_machine.environment_virtual_machines (remote-exec):   Password: true
vsphere_virtual_machine.environment_virtual_machines (remote-exec):   HTTPS: false
vsphere_virtual_machine.environment_virtual_machines (remote-exec):   Insecure: false
vsphere_virtual_machine.environment_virtual_machines (remote-exec):   CACert: false
vsphere_virtual_machine.environment_virtual_machines (remote-exec): Connected!
vsphere_virtual_machine.environment_virtual_machines: Creation complete after 1m17s (ID: 564d543b-a2f1-9706-8ec2-f325f1aca5bf)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Seems that everything went correctly, but actually the provisioners doesn't seem to be executed. 
The 'Connected!' messages seems to occur while box is still doing something - being in the following "Getting Ready" state, which I believe isn't ok as the machine is basically restarted after a couple of seconds:
![image](https://user-images.githubusercontent.com/572605/38091690-2f7a7416-335e-11e8-99dc-d8eb5f4f1893.png)

### Steps to Reproduce

terraform apply

Remark - it has worked in the past..

**Comment by kaluznyt** [comment]
I re run the init at some point and then provisioner was run (that's a bit weird, as I think it shouldn't at this point, and not as expected, but screenshot below), I believe it's some timing issue, as the windows are sysprep'ped so on first run it take longer and reboot.  Perhaps provisioner run the exec - it can obtain the connection, but then system is restarted and provisioner just report success..

![image](https://user-images.githubusercontent.com/572605/38093784-dfc69f16-3363-11e8-95a1-b38a5533ab14.png)

**Comment by kaluznyt** [comment]
Does it wait a particular amount of time until running the provisioner or just wait for connection to be available ? As it seems its always around 1 minute. 

And if I remove a tfstate file and then run terraform apply again then it works, as the disk/os is already initiated by last run so it doesn't take so long, and doesn't need to reboot itself.

**Comment by kaluznyt** [comment]
Hi @jbardin , 

Thanks for the response. 

> Are your provisioners in the instance blocks directly, or are they being run from a separate resource?

Not sure, these are in a resource "vsphere_virtual_machine" block, however, it has "count" property, as this is run for a collection of machines like:

```
resource "vsphere_virtual_machine" "environment_virtual_machines" {
  count = "${length(var.machine_names)}"
  name  = "${element(var.machine_names,count.index)}"
  ...
  provisioner "remote-exec" {
      connection = {
        type     = "winrm"
        user     = "admin"
        password = "admin"
        agent    = false
        insecure = true
      }
    inline = [
       ...
   ]}
```

For the debugging, I'll provide the information, however first need to find info on how to enable it, if you could provide which debugging exactly would help (url/command) then I'll be grateful. 

Tomasz

**Comment by kaluznyt** [comment]
Ok - I have a debug log, but I guess this line is say what had happened:

2018-04-03T08:29:06.784+0100 [DEBUG] plugin.terraform.exe: remote-exec-provisioner (internal) 2018/04/03 08:29:06 [WARN] Failed to upload empty follow up script: Error uploading file to $env:TEMP\winrmcp-f4a56b00-b81e-4c9e-53cd-f65a646b1a07.tmp: Couldn't create shell: unknown error Post http://192.168.77.45:5985/wsman: read tcp 10.212.134.200:49331->192.168.77.45:5985: wsarecv: An existing connection was forcibly closed by the remote host.

Full debug log is here [https://gist.github.com/kaluznyt/a8b08823386221f581441077c2263b31](url)

**Comment by kaluznyt** [comment]
![2018-04-03_08-29-09](https://user-images.githubusercontent.com/572605/38236343-c77b72fe-371b-11e8-99fc-305984fa121c.png)
![2018-04-03_08-29-22](https://user-images.githubusercontent.com/572605/38236347-c94ba126-371b-11e8-94c2-f2f6331880bd.png)

**Comment by kaluznyt** [comment]
This is what initially happens. Then the machine is basically there on ESXi, but I can un-register it, leaving just the disk. Then after I run terraform again with the same configuration, it already have this disk with 'os initialized' so it takes less time/reboots to start it and then it seems working. 

![2018-04-03_10-09-32](https://user-images.githubusercontent.com/572605/38240423-776d8552-3727-11e8-8ed1-a0209eade736.png)


However, it obviously doesn't help with anything. 

Normally the process is:
1. Clone the OS disk (disk was created with Packer) and sysprepped, so it can be cloned - but initially it takes a bit more to start/initialize OS (this is when issue seem occurring).
(if disk is already there in a destination location it does nothing, that's why it works for a second time, so the 'initialized' disk is there, it attaches it and OS starts quickly so it can execute the commands)
2. Run terraform apply - that creates the machine using the cloned disk as OS disk.

**Comment by kaluznyt** [comment]
> Terraform doesn't yet have a way to re-run only a provisioner, so I'm also not sure what you saw when you re-ran terraform and it re-ran the provisioner.

Seems that it's exactly what happens when I run the 'tf apply' after I remove the machines, but the disks are still there (I use attach=true). That make sense, as it does what it need to and on a second run, when disks are already initialized properly it can execute the powershell commands. So basically now I did it (unregistered the machines at esxi) and it workaround the issue, however it's not the kind of automation that's expected :)

**Comment by kaluznyt** [comment]
Interesting thing is, that it works fine with windows 2012 r2 with updates installed  as per following:

For me basically that's fine, as I'm going to use updated windows disk template.

![image](https://user-images.githubusercontent.com/572605/38297866-a21da98c-37ed-11e8-9df4-397d733fa48e.png)

**Comment by kaluznyt** [comment]
Again encountering that issue, in short provisioner doesn't run as it triggers while the machine is still being created. 

Is there any way to use a null_resource to trigger provisioning for the machines that were provisioned earlier ? Like to ensure the order between the two:

1. machines are provisioned - and provisioning is completed
2. run the provisioners for the machine 

Thanks for any hints.

**Comment by kaluznyt** [comment]
I figured out how to run these provisioners as another step which works for me as a workaround but isn't ideal:

```
resource "vsphere_virtual_machine" "environment_virtual_machines" {
    count = "${length(var.machine_names)}"

    ...

    provisioner "remote-exec" {
    ...
    }
}

resource "null_resource" "environment_virtual_machines" {
  count = "${length(var.machine_names)}"

   provisioner "remote-exec" {
    connection = {
      # host     = "${element(vsphere_virtual_machine.environment_virtual_machines.*.adapter_type, count.index)}"
      host     = "${vsphere_virtual_machine.environment_virtual_machines.default_ip_address}"
      type     = "winrm"
     ...
    }
}
     inline = [
    ...
    ]

}


```

**Comment by lmayorga1980** [comment]
I am having the same behavior on `0.12.9`

```
Error: Upload failed: Error uploading file to $env:TEMP\winrmcp-e73a219b-6318-477e-4d54-82b3798aa068.tmp: Couldn't create shell: unknown error Post https://10.82.132.58:5986/wsman: read tcp 10.51.115.46:49793->10.82.132.58:5986: read: connection reset by peer
```

**Comment by bill-rich** [comment]
We've got another example of this issue over in terraform-providers/terraform-provider-vsphere#1061 along with some additional examples and debug logs.

**Comment by VickyWinner** [comment]
> We've got another example of this issue over in [hashicorp/terraform-provider-vsphere#1061](https://github.com/hashicorp/terraform-provider-vsphere/issues/1061) along with some additional examples and debug logs.

Applies to Windows 2016 too.

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

For this particular issue, I want to note that we made a lot of Windows-specific improvements in 0.13.x, including multiple `remote-exec` fixes. I am hopeful that if you try again in 0.14.x you will find this works better. 

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
