### ISSUE TITLE
terraform lock is still acquired after 'terraform import'

### ISSUE THREAD

**Issue by sg21210** [hashicorp/terraform#17723]
Hi,
I'm having trouble with 'terraform import' command. It says that I successfully imported the resource, but after that, I can see the lock is still acquired. 

### Terraform Version
* v0.11.4
* provider.aws v1.13.0

### Expected Behavior
Successfully do the next terraform commands.

### Actual Behavior
```
Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed
        status code: 400, request id: PCFGL92OU8NL52P5PFIVHRU48JVV4KQNSO5AEMVJF66Q9ASUAAJG
Lock Info:
  ID:        042c6f1d-44e4-239c-312f-42573e581495
  ....
```

### Steps to Reproduce
1. Create a terraform module. 
    - In my case, it has its terraform backend in `S3`.
2. The module refers resources in another folder.
    - In my case, the resource was `aws_sqs_queue`
3. Run `terraform import`
    - In my case,  `terraform import module.sqs-queue-name.aws_sqs_queue.sqs https://SQSURL`
4. Try another terraform commands. then you'll see it is locked.

### Additional Context
It doesn't matter if the previous (locking) command succeeded or not. I can see the lock error message after running the same command, which results in an error of having same resource name.

**Comment by jbardin** [comment]
Hi @sg21210,

Thanks for filing the issue. This was fixes in v0.11.5 by  #17645
