### ISSUE TITLE
Conditional operator returns unknown when the unchosen expression is unknown

### ISSUE THREAD

**Issue by jayanderson** [hashicorp/terraform#17720]
The main goal is to modify an existing resource to add a random suffix to resources used for testing. Adding this suffix causes resource recreation even though the ultimate string forcing the recreation is unchanged.

### Terraform Version
```
terraform -v
Terraform v0.11.5
+ provider.aws v1.12.0
+ provider.local v1.1.0
+ provider.random v1.1.0
```

### Terraform Configuration Files
While the below are using a local file resource this applies to other resources and was originally seen with a `aws_s3_bucket` resource.

Step 1:
```hcl
variable "testing" {
  default = "false"
}

provider "aws" {
  region = "us-east-1"
}

resource "local_file" "file" {
  content = "stuff"
  filename = "${path.module}/test${var.testing == "true" ? "test" : ""}.txt"
}
```

Step 2:
Add the `random_id` resource and swap out the static test string for the generated string.
```hcl
variable "testing" {
  default = "false"
}

provider "aws" {
  region = "us-east-1"
}

resource "random_id" "suffix" {
  byte_length = 8
}

resource "local_file" "file" {
  content = "stuff"
  filename = "${path.module}/test${var.testing == "true" ? "${random_id.suffix.hex}" : ""}.txt"
}
```

### Debug Output
https://gist.github.com/jayanderson/321e8dc8aaffa793ebc6839ceb60093f

### Crash Output
N/A

### Expected Behavior
The resource should not be recreated.

### Actual Behavior
The resource is recreated.

### Steps to Reproduce
1. `terraform apply` with step 1 terraform code from above
2. Modify code to look like step 2 terraform code from above
3. `terraform plan`

Output:
```
> tf plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

local_file.file: Refreshing state... (ID: 5eee38381388b6f30efdd5c5c6f067dbf32c0bb3)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ local_file.file (new resource required)
      id:          "5eee38381388b6f30efdd5c5c6f067dbf32c0bb3" => <computed> (forces new resource)
      content:     "stuff" => "stuff"
      filename:    "/Users/jaanderson/git/cloud/tf_s3_bucket/bug/test.txt" => "${path.module}/test${var.testing == \"true\" ? \"${random_id.suffix.hex}\" : \"\"}.txt" (forces new resource)

  + random_id.suffix
      id:          <computed>
      b64:         <computed>
      b64_std:     <computed>
      b64_url:     <computed>
      byte_length: "8"
      dec:         <computed>
      hex:         <computed>


Plan: 2 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### Workaround
I was able to find a workaround to avoid recreating the resource by going through an intermediate step. Instead we add an intermediate step between steps 1 and 2 which we apply:
```hcl
variable "testing" {
  default = "false"
}

provider "aws" {
  region = "us-east-1"
}

resource "random_id" "suffix" {
  byte_length = 8
}

resource "local_file" "file" {
  content = "stuff"
  filename = "${path.module}/test${var.testing == "true" ? "test" : ""}.txt"
}
```

This is only creating the `random_id` resource. After this switch to the step 2 terraform code and run terraform plan:

```
> tf plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

random_id.suffix: Refreshing state... (ID: 19Gb4FahiUY)
local_file.file: Refreshing state... (ID: 5eee38381388b6f30efdd5c5c6f067dbf32c0bb3)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Additional Context
N/A

### References
N/A

**Comment by teamterraform** [comment]
Hi @jayanderson! Sorry for the long silence here.

As you saw, in Terraform 0.11 if any operand used with an operator were unknown then the result was always unknown, regardless of whether that operand would normally be used as part of evaluating the expression. That also applied to arguments to functions, with similar consequences.

Terraform 0.12 now tracks unknown values more precisely, and in particular will only return an unknown value from a conditional if either the condition value itself is unknown or if the selected result is unknown. All other operators and many functions can now also produce results in the presence of unknown values, as long as the result does not depend on the value that is unknown.
