### ISSUE TITLE
Feature Request: terraform output --json-key-value

### ISSUE THREAD

**Issue by genevieve** [hashicorp/terraform#17731]
Hello!

Out of curiosity, are there any plans to have terraform output spit out json that is just key:value pairs without the additional properties of an output?

Follow-up question: If there are no plans, would you be willing to accept a PR for that functionality? (Given we come up with a better flag than `--json-key-value`.)

Thanks!
Gen

PS. If there is a better location for reaching out to y'all outside of github issues, I am happy to relocate this question.

**Comment by mildwonkey** [comment]
Hi @genevieve !
Indeed, as briandbecker commented, you can use `terraform output -json` and pipe the output through your preferred tool to get just the keys and values.

Here's an example using `jq`, though I am by no means an expert:
```
terraform output -json | jq '. | to_entries[] | {"key": .key, "value": .value.value}'
{
  "key": "pets",
  "value": [
    "linus-bold-bonefish",
    "linus-touching-treefrog",
    "linus-poetic-camel"
  ]
}
{
  "key": "pets-list",
  "value": [
    "Pet: linus-bold-bonefish",
    "Pet: linus-touching-treefrog",
    "Pet: linus-poetic-camel"
  ]
}
```

I am going to close this feature request, as that is our preferred method of parsing outputs. If you find that this is insufficient for your use case, please open a new feature request with any additional supporting information or reasoning. Thank you!
