### ISSUE TITLE
Terraform fails when applying an aws_autoscaling_group with the same name as deposed

### ISSUE THREAD

**Issue by dotanrs** [hashicorp/terraform#17762]
I have a terraform script that launches an autoscaling group (among other things)

When I did terraform apply, it tried to create an ASG but failed due to a timeout. Terraform did not delete the ASG it created (because it doesn't roll back on failures) and I saw in the state file that the new ASG is noted under 'deposed' (as expected)

Problem was, when I re-applied terraform it failed with:

> Error creating AutoScaling Group: AlreadyExists: AutoScalingGroup by this name already exists

My tf file, abbreviated:

```
resource "aws_launch_configuration" "blah" {
  name_prefix          = "${local.instance-name}-"
  image_id             = "${data.aws_ami.blah.id}"
  instance_type        = "r3.8xlarge"
  spot_price           = "1.33"
  user_data            = "${local.user-data}"
  security_groups      = ["${aws_security_group.blah.id}"]
  key_name             = "${var.ssh-key}"
  iam_instance_profile = "${aws_iam_instance_profile.instance_profile.id}"
  ephemeral_block_device = [{
    device_name = "/dev/xvdb"
    virtual_name = "ephemeral0"
  },{
    device_name = "/dev/xvdc"
    virtual_name = "ephemeral1"
  }]

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "blah" {
  name                      = "${aws_launch_configuration.blah.name}"
  max_size                  = "${var.instance-count}"
  min_size                  = "1"
  desired_capacity          = "${var.instance-count}"
  wait_for_elb_capacity     = "1"
  force_delete              = true
  health_check_type         = "ELB"
  health_check_grace_period = "1200"
  wait_for_capacity_timeout = "1m"
  target_group_arns         = ["${aws_alb_target_group.blah.arn}"]
  launch_configuration      = "${aws_launch_configuration.blah.name}"
  vpc_zone_identifier       = ["${data.aws_subnet_ids.private_subnets.ids}"]
  depends_on                = ["aws_launch_configuration.blah"]

  tag {
    key                 = "Name"
    value               = "${local.instance-name}"
    propagate_at_launch = "true"
  }

  lifecycle {
    create_before_destroy = true
  }
}
```
I would expect that terraform would delete the deposed ASG before creating a new one 

terraform version: 0.11.5

**Comment by jbardin** [comment]
Hi @dotanrs,

You mention that it's he ASG that's failing, but have only provided the `aws_launch_configuration` configuration block.

Since the ASG has a deposed instance, I assume that you still have `create_before_destroy = true` in that resource as well. I assume that since AWS returns the error `AlreadyExists: AutoScalingGroup by this name already exists`, that you can't set the `name` value along with `create_before_destroy`. Is that the case in your configuration?

**Comment by dotanrs** [comment]
Sorry about that, added the correct block.

`you can't set the name value along with create_before_destroy` - not sure what you mean by this. I can change the name each time but I'm looking for a more robust solution

**Comment by jbardin** [comment]
Forgive me if I'm missing something, since I don't know the details for all the providers' resources, but isn't `name_prefix` the solution you would be looking for? If AWS can only allow one ASG with a given name, then you can't "create before destroy" without creating multiples instance of the same ASG.

**Comment by jbardin** [comment]
The older ASG is "deposed" as far as terraform is concerned, but that concept only exists in terraform -- in AWS it is still a  perfectly valid ASG that has yet to be destroyed.

**Comment by dotanrs** [comment]
I understand, but since terraform knows this I think it should delete it before launching the new one, despite the `create_before_destroy` attribute

**Comment by jbardin** [comment]
Hi @dotanrs, I understand where you're coming from, but that's not a safe assumption that terraform can make. The "deposed" instance is still part of the create-before-destroy lifecycle, and still needs to be handled as such -- destroying the deposed instance first would violate the explicit configuration set by the user. 

When a user puts `create_before_destroy` into the configuration, they are relying on terraform to _always_ create a new instance before destroying the old one. Part of this contract is to fail when the resource cannot be replaced in this order, which indicates a problem in either the configuration or the infrastructure that needs to be remedied. 

Also, during execution terraform actually doesn't know what is preventing the resource from being created. The provider _may_ know, but in most situations it still must rely on the remote API to validate the overall state of its resources. The only known information to return to the user is that creating the new instance failed and the resulting error. 

Terraform in this case is working as intended, by ensuring that there is _always_ an instance of `aws_autoscaling_group` available.

**Comment by smastrorocco** [comment]
We are seeing odd behavior with this as well.  If for any reason the new ASG fails for timeout, the next run fails saying an asg with the specified name already exists, with use of `name_prefix`.  Then if that failed asg is manually cleaned up, Terraform will continue, deploy the new asg, then begin disposing that ID, leaving zero asg's running and a successful terraform deployment.

```
...
module.app.aws_autoscaling_group.asg: Still creating... (6m10s elapsed)
module.app.aws_autoscaling_group.asg: Still creating... (6m20s elapsed)
module.app.aws_autoscaling_group.asg: Still creating... (6m30s elapsed)
module.app.aws_autoscaling_group.asg: Still creating... (6m40s elapsed)
module.app.aws_autoscaling_group.asg: Still creating... (6m50s elapsed)
module.app.aws_autoscaling_group.asg: Still creating... (7m0s elapsed)
module.app.aws_autoscaling_group.asg: Still creating... (7m10s elapsed)
module.app.aws_autoscaling_group.asg: Still creating... (7m20s elapsed)
module.app.aws_autoscaling_group.asg: Still creating... (7m30s elapsed)
module.app.aws_autoscaling_group.asg: Creation complete after 7m31s (ID: my-asg20180803153910234900000001)
module.app.aws_autoscaling_group.asg.deposed: Destroying... (ID: my-asg20180803153910234900000001)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 10s elapsed)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 20s elapsed)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 30s elapsed)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 40s elapsed)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 50s elapsed)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 1m0s elapsed)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 1m10s elapsed)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 1m20s elapsed)
module.app.aws_autoscaling_group.asg (deposed #0): Still destroying... (ID: my-asg20180803153910234900000001, 1m30s elapsed)
module.app.aws_autoscaling_group.asg.deposed: Destruction complete after 1m30s
module.app.aws_launch_configuration.launch_configuration.deposed: Destroying... (ID: my-asg20180802215410154400000001)
module.app.aws_launch_configuration.launch_configuration.deposed: Destruction complete after 1s
Apply complete! Resources: 1 added, 1 changed, 2 destroyed.
```

**Comment by schommer21** [comment]
I'm seeing the same behavior as @smastrorocco, the first retry fails saying the ASG already exists, and with the second retry both ASGs destroyed. The third run creates the new ASG and everything finally comes together. We're running v0.9.6

**Comment by ivan-vinitskyy** [comment]
I'm experiencing the same issue and it's a serious one.  Terraform kills both ASGs, creating an outage.

**Comment by jbardin** [comment]
Hi All,

Sorry there's still some confusion here (and the delay, it's hard to monitor closed issues), but from the descriptions provided, terraform is operating as expected. If a resource is marked as `create_before_destroy`, terraform must honor that (see my previous comment for more detail).

@smastrorocco, if `name_prefix` isn't creating unique names, then that is an issue that should be opened up with the aws provider. 

What this comes down to though, when using `create_before_destroy`, there can't be any attributes that must be unique across resources. Since the particulars of this varies between providers and individual resources, any common use cases would need to be documented there.

**Comment by sampyakurel** [comment]
Hello,
I am getting the following error while trying to run Terraform with 3 docker images. It works with 2 images but fails when I add the 3rd image.
`* aws_autoscaling_group.asg_app: Resource 'aws_launch_configuration.lc_app' not found for variable 'aws_launch_configuration.lc_app.name'
* aws_launch_configuration.lc_app: expected length of user_data to be in the range (1 - 16384), got {
  "ignition": {`

This is how my terraform looks like:
`name = "asg-app - ${aws_launch_configuration.lc_app.name}"
  max_size = 2
  min_size = 1
  wait_for_elb_capacity = 0
  desired_capacity = 1
  wait_for_capacity_timeout = "10m"
  launch_configuration = "${aws_launch_configuration.lc_app.id}"
  vpc_zone_identifier = ["${var.subnets}"]

  tag {
    key = "Name"
    value = "${var.env_prefix}${var.shortname}"
    propagate_at_launch = true
  }
  tag {
    key = "Environment"
    value = "${var.environment}"
    propagate_at_launch = true
  }
  tag {
    key = "created-by"
    value = "${var.created_by}"
    propagate_at_launch = true
  }
}

resource "aws_launch_configuration" "lc_app" {
  name = "${var.env_prefix}${var.shortname}-lc"
  image_id = "xxx"
  key_name = "xxx"
  instance_type = "${var.instance_type}"
  iam_instance_profile = "${aws_iam_instance_profile.server.name}"
  associate_public_ip_address = true
  security_groups = ["${var.security_groups}"]
  user_data = "${element(data.ct_config.service.*.rendered, count.index)}"
  lifecycle {
    create_before_destroy = true
  }
  ebs_block_device {
    device_name = "/dev/xvdf"
    volume_size = 100
    volume_type = "gp2"
    delete_on_termination = true
  }`

Any idea folks?

**Comment by Darshannraval** [comment]
Hi All,

I am trying to launch ASG. It launches as well but it is not launching an instance.
Below is the code:

resource "aws_launch_configuration" "darshan" {
  image_id      = "ami-076e276d85f524150"
  instance_type = "t2.micro"
  security_groups = ["WEBSG"]
   lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "worker"

 {
  name = "${aws_launch_configuration.worker.name}-asg"
  launch_configuration = "${aws_launch_configuration.worker.name}"
   vpc_zone_identifier       = ["subnet-29e61773", "subnet-ba8ad0f2"]
  min_size             = 2
 # desired_capacity     = 5
  max_size             = 5
  health_check_type    = "EC2"
  default_cooldown = 300
    wait_for_capacity_timeout = "1m"

  lifecycle {
    create_before_destroy = true
  }
![tf3](https://user-images.githubusercontent.com/35019331/50573096-4ce80980-0df3-11e9-9a93-392ae8bfc277.PNG)

}

**Comment by Darshannraval** [comment]
Hi All,

I am trying to create ASG and launch configuration. It  is creating as well. However for some reason it is not launching an instance.
Below is the code and screenshot.


resource "aws_launch_configuration" "worker" {
  image_id      = "ami-076e276d85f524150"
  instance_type = "t2.micro"
  security_groups = ["WEBSG"]
   lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "worker"

 {
  name = "${aws_launch_configuration.worker.name}-asg"
  launch_configuration = "${aws_launch_configuration.worker.name}"
   vpc_zone_identifier       = ["subnet-29e61773", "subnet-ba8ad0f2"]
  min_size             = 2
 # desired_capacity     = 5
  max_size             = 5
  health_check_type    = "EC2"
  default_cooldown = 300
    wait_for_capacity_timeout = "1m"

  lifecycle {
    create_before_destroy = true
  }
}
![tf3](https://user-images.githubusercontent.com/35019331/50573115-a94b2900-0df3-11e9-8fe4-e63c9e382cc7.PNG)

**Comment by aggallim** [comment]
> I'm seeing the same behavior as @smastrorocco, the first retry fails saying the ASG already exists, and with the second retry both ASGs destroyed. The third run creates the new ASG and everything finally comes together. We're running v0.9.6

I'm getting the same, tf 0.11.1 and provider 1.18. Did anyone find an appropriate solution to this? Using name_prefix to make a unique value makes the LC and ASG re-create every time its ran, which isnt ideal.
