### ISSUE TITLE
Error running fmt: In ec2.tf: At 5:2: literal not terminated

### ISSUE THREAD

**Issue by Bharath1313** [hashicorp/terraform#17778]
Hi
Am getting Error running fmt: In ec2.tf: At 5:2: literal not terminatedm when i run terraform plan or fmt.

my ec2.tf file looks like

1 provider "aws" {
2 access_key = "${var.access_key}"
3 secret_key = "${var.secret_key"
4 region = "${var.region}"
5 }
6
7 resource "aws_instance" "myfirstinst" {
8 ami = "${lookup(var.ami, var.region)}"
9 instance_type = "t2.micro"
10 key_name = "testkey"
11 }
12
13 resource "aws_eip" "staticip" {
14 instance = "${aws_instance.myfirstinst.id}"
15 vpc = "true"
16 }
~
I created a variable file for this, that is variable.tf. output of this file is

1 variable "access_key" {
2 description = "AWS access key"
3 }
4
5 variable "secret_key" {
6 description = "AWS secret key"
7 }
8
9 variable "region" {
10 description = "setting up AWS deafult region"
11 default = "ap-south-1"
12 }
13
14 variable "region_list" {
15 description = "availability zones"
16 default = ["ap-south-1a", "ap-south-1b"]
17 }
18
19 variable "ami" {
20 type = "map"
21
22 default = {
23 ap-south-1 = "ami-e60e5a89"
24 ap-southeast-1 = "ami-e2adf99e"
25 }
26
27 description = " the AMI to use "
28 }
~
~
~

My terraform version is

Terraform v0.11.5

provider.aws v1.13.0
could you please anyone help me out this.

Thank you

**Comment by jbardin** [comment]
Hi @Bharath1313,

You're missing a `}` on line 3. It should be  `secret_key = "${var.secret_key}"

**Comment by Bharath1313** [comment]
Awesome, :) :+1: thank you soo much.. may i know what it mean error 5:2,? actually it points out in line 3.

**Comment by jbardin** [comment]
@Bharath1313: it looks like its pointing out the end of the outer block for the error location.
A new configuration layer is in the works already, so at some point we will have better all-around error messages.
