### ISSUE TITLE
Variables in ASG lifecycle block can't be parsed as booleans

### ISSUE THREAD

**Issue by dotanrs** [hashicorp/terraform#17775]
I have an autoscaling group for which I defined a `create_before_destroy` parameter in the `lifecycle` block. It seems like I can't put the value of this parameter in a variable, because I get this error:

> cannot parse 'create_before_destroy' as bool: strconv.ParseBool: parsing "${var.create-before-destroy}": invalid syntax

This also happens if I wrap the variable with `{format("%t÷", .. )}`

The problem doesn't happen outside the lifecycle block. I can e.g. switch the value of `force_delete` to a variable and it will work fine.

Related: [1017](https://github.com/hashicorp/terraform/pull/1017) which discusses the same problem ocuring in variables in general. Seems like the solution wasn't fully implemented.

My ASG:
```
resource "aws_autoscaling_group" "blah" {
  name                      = "${aws_launch_configuration.blah.name}2"
  max_size                  = "${var.instance-count}"
  min_size                  = "1"
  desired_capacity          = "${var.instance-count}"
  wait_for_elb_capacity     = "1"
  force_delete              = true
  health_check_type         = "ELB"
  health_check_grace_period = "1200"
  wait_for_capacity_timeout = "25s"
  target_group_arns         = ["${aws_alb_target_group.blah.arn}"]
  launch_configuration      = "${aws_launch_configuration.blah.name}"
  vpc_zone_identifier       = ["${data.aws_subnet_ids.private_subnets.ids}"]
  depends_on                = ["aws_launch_configuration.blah"]

  tag {
    key                 = "Name"
    value               = "${local.instance-name}"
    propagate_at_launch = "true"
  }

  lifecycle {
    create_before_destroy = "${var.create-before-destroy}"
  }
}
```
I tried a few options for the variable, each with/out the format function:
```
variable "create-before-destroy-a" {
	default = true
}
variable "create-before-destroy-b" {
	default = "true"
}
variable "create-before-destroy-c" {
	default = 1
}
```

terraform version: 0.11.5

**Comment by jbardin** [comment]
Hi,

Lifecycle attributes cannot be interpolated. See #3116 for some more discussion, but in general those values need to be static.
