### ISSUE TITLE
Failed to load backend: Error loading backend config: Error parsing 

### ISSUE THREAD

**Issue by scrubs1979** [hashicorp/terraform#17784]
Hello!

So I tried to spin up an EC2 instance using Terraform on my Mac(which is running Sierra and Terraform  0.11.5) but keep getting a few errors:

Command: terraform plan
Error: Error parsing /Users/*****/terraform/aws.tf: At 1:11: illegal char

Command: terraform show
Error: Failed to load backend: Error loading backend config: Error parsing /Users/******/terraform/aws.tf: At 1:11: illegal char

Here is what my file looks like:

provider "aws" {
    region = "us-east-1"
    access_key = "*************"
    secret_key = "*********************"
}

resource "aws_key_pair" "nick-key" {
  key_name = "nick-key"
  public_key =  "ssh-rsa ********************************************"
}

resource "aws_instance" "web" {
    ami = "ami-1853ac65"
    instance_type = "t2.micro"
    key_name = "${aws_key_pair.nick-key.key_name}"

I put * in place of the real information used in the file in case anyone was wondering. Any help would be greatly appreciated!! Thank you in advance!

**Comment by scrubs1979** [comment]
Also, this is the tutorial I was using to do this project but feel like he left crucial steps out and thats maybe why I'm having issues? 

https://www.youtube.com/watch?v=mQ9QDESqZ9o

**Comment by jbardin** [comment]
Hi @scrubs1979,

Sorry you're having an issue here, but I can't tell from the example you've provided exactly what the problem is. The error indicates that you have an illegal character at line1, col 11. You may have cut&pasted something different into your config than what is shown here, maybe unicode quotes like `‟ ”`, or a non-printable character of some sort. 

Make sure you're using a proper text editor and that the characters are exactly what you think they are.

**Comment by scrubs1979** [comment]
Thank you for responding! I will review my code again, but I feel like I typed everything verbatim according to the tutorial. I created the file in the command line. Maybe I should do it in Atom and manually save to the terraform dir?

**Comment by jbardin** [comment]
Yes, open them in an editor like atom and see what it looks like before saving. 
Make sure it's saved as valid utf-8. Try also using `terraform fmt`, though it should give the exact same error in this case, because the file cannot be loaded at all.
