### ISSUE TITLE
Terraform init does not initialize GCS backend

### ISSUE THREAD

**Issue by kaifresh** [hashicorp/terraform#17795]
### Terraform Version

```
Terraform v0.11.5
```

### Terraform Configuration Files

```hcl

# My project & credentials are in a provider block elsewhere
terraform {
  backend "gcs" {
    bucket = "terraform-production-remotestatestorage" 
    prefix = "terraform/state"
  }
}
```

### Expected Behavior

Calling `terraform init` should have produced a notification about the backend being initalized, and a subsequent `terraform apply` should have produced a .tfstate file in my GCS bucket. 

### Actual Behavior

This information was returned from `terraform init`, notably missing any reference to a backend being set up.

```
Initializing modules...
- module.leadleaders_input

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.google: version = "~> 1.9"
* provider.null: version = "~> 1.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

### Steps to Reproduce

Add the terraform backend setup info above and run `terraform init` then `terraform apply`

**Comment by jbardin** [comment]
Hi @kaifresh,

Sorry you're having an issue here, but I'm not able to reproduce a problem on my side.

The backend "initialization" process is mostly internal to terraform, so we don't produce any related output unless user intervention is required.

Are you getting an error during apply?

**Comment by kaifresh** [comment]
No there isn’t an error appearing. But also the tfstate file in the GCS bucket doesn’t have any data in it after apply

KT

**Comment by jbardin** [comment]
@kaifresh,

If you run apply a second time, is it asking to recreate the same resources?
Does `terraform state pull` show resources that you expect to be in your state?

**Comment by kaifresh** [comment]
Running `apply` a second time doesn't ask to recreate the same resources.

Running `terraform state pull` does show resources I would expect to be in state. However, I've also got a local terraform.tfstate file with this data, and remote state file that looks initialized but not containing any meaningful info

```
{
    "version": 3,
    "serial": 1,
    "lineage": "9e99c31e-8ec3-0f0e-9bbc-96c816670906",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}

```

**Comment by jbardin** [comment]
Sorry, I'm not sure what you could be doing out of the ordinary here.
I did just notice your comment in the config above `project & credentials are in a provider block elsewhere` -- provider config and backend config are completely separate, configuring one does not configure the other. Is it possible that the backend is picking up other credentials from your environment? 

If you have `backend "gcs"` in the `terraform` block in your config, it should _not_ be using local state at all, and should have errorred out if required credentials couldn't be found. Can you provide the logs from running `init` with `TF_LOG=trace`?

**Comment by kaifresh** [comment]
[terraform.log](https://github.com/hashicorp/terraform/files/1896898/terraform.log)

Just eyeballing it, there's some references to "backend" but not about GCS...

**Comment by jbardin** [comment]
The only thing I see in those logs that's related is `command: empty terraform config, returning nil`, which means that there is no `terraform`  block found in the configuration.

Are you certain that the above config is in the `leadleaders_csv_to_autopilot` directory, and in a file with a `*.tf` filename?

**Comment by jbardin** [comment]
yes, the backend config must always be in the root module.

**Comment by kaifresh** [comment]
There you go! Problem solved by putting the remote state in the root module. Thanks @jbardin you legend
