### ISSUE TITLE
terraform init unsuccessful when using s3 backend with role_arn for state

### ISSUE THREAD

**Issue by swettk** [hashicorp/terraform#17803]
### Terraform Version

```
Terraform v0.11.6
+ provider.aws v1.5.0
+ provider.random v1.1.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
terraform {
  backend "s3" {
    bucket = "terraform-state"
    key    = "terraform.tfstate"
    dynamodb_table = "terraform_locks"
    region = "us-east-1"
    role_arn = "arn:aws:iam::<ACCOUNTID>:role/terraformer"
  }
}
```

### Expected Behavior

```terraform init``` should have succeeded

### Actual Behavior

```
Error loading state:
    AccessDenied: Access Denied
        status code: 403, request id: D846FB82F8CDB9A0, host id: yJna4vPqapM0pK1Oy+ild1tggjw9je1Nkn2Unxw2k5LQSwzJUmPZXOUFhj/kLQ6vllZQTHqoYz8=

Terraform failed to load the default state from the "s3" backend.
State migration cannot occur unless the state can be loaded. Backend
modification and state migration has been aborted. The state in both the
source and the destination remain unmodified. Please resolve the
above error and try again.

```

### Steps to Reproduce

1. `main.tf with above value`
1. `terraform init`

### Additional Context

1.  terraformer user in our primary account has an Admin policy attached
2.  terraformer role in our secondary account has an Admin policy attached

**Comment by swettk** [comment]
So to import the old state the user would need access to the old state file via the old method in addition to the new location?  So in theory migrating to local state, then moving back to s3 with the role would suffice?

**Comment by swettk** [comment]
confirmed working, thanks for the kind response @jbardin !

**Comment by pdeibel** [comment]
I am running into this issue and have tried the -reconfigure option with the same result...
deibp001@WW-AM04086471 ~/repos/wdw-cast-dots-s3 (develop) $ terraform init -backend-config="bucket=terraform-wdpr-sandbox-${MY_TF_ENV}" -backend-config="key=wdw-cast/us-east-1/dots/main/${MY_TF_ENV}.tfstate" -reconfigure

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: AccessDenied: Access Denied
	status code: 403, request id: B89D907C7C618D64, host id: WDwiGLFrQxr26bGt0NPpN6Pzc1iTi8t/cFTI+JvQotERGvKYuisd9pkVtL+adSPRm0TS/iEgoYA=

**Comment by n8v** [comment]
This was the hint I needed! Running `rm -r .terraform/` to clear my local state was the breakthrough to getting going again, since we had changed the way we are using roles on this state bucket
