### ISSUE TITLE
terraform state rm always displays success message as long as you give it a "valid" resource name

### ISSUE THREAD

**Issue by kaofelix** [hashicorp/terraform#17800]
### Terraform Version

```
Terraform v0.11.5
```

### Terraform Command

```
$ terraform state rm foo.bar
1 items removed.
Item removal successful.
```
### Expected Behavior

Terraform should give me an error saying the resource does not exist. 

### Actual Behavior

Terraform says it removed 1 item successfully.

### Steps to Reproduce

In any folder, even one that does not contain state run `terraform state rm random_type.random_name`. If there's no `.` Terraform will complain:
```
$ terraform state rm foo
Error removing items from the state: Error parsing address 'foo': invalid resource address "foo"
```
but beyond that it always prints the success message.

**Comment by tdmalone** [comment]
You can also replicate this by trying to remove the same item over and over again:

```
$ terraform state rm aws_eip.foo
1 items removed.
Item removal successful.
$ terraform state rm aws_eip.foo
1 items removed.
Item removal successful.
$ terraform state rm aws_eip.foo ✔  10022  08:01:10 
1 items removed.
Item removal successful.
```

**Comment by pillarsdotnet** [comment]
Furthermore, `terraform state rm` reports success even when it fails.  Here's the log:
```
+ export TF_LOG=trace
+ terraform state rm aws_iam_role.tower
Item removal successful.
+ terraform import -no-color aws_iam_role.tower tower
aws_iam_role.tower: Import complete!
  Imported aws_iam_role (ID: tower)

Error: aws_iam_role.tower (import id: tower): Can't import aws_iam_role.tower, would collide with an existing resource.

Please remove or rename this resource before continuing.

```

The full `TF_LOG=trace` output is [here](https://gist.github.com/pillarsdotnet/ec9e909747f48f076e05498cc7d5ee3f)

**Comment by marcelloromani** [comment]
Seen this also with Terraform v0.11.10

**Comment by jgpacker** [comment]
The output was corrected. I'm using `Terraform v0.12.2`.
However, the exit code is zero, instead of one.
```shell
$ terraform state rm module.that.aws_ecs_task_definition.this_non_created_resource
Acquiring state lock. This may take a few moments...
No matching resource instances found.
Releasing state lock. This may take a few moments...
$ echo $?
0
```
Should the exit code be in the scope of this bug?
The subcommand `terraform state show` does exit with code one for the same non-existent resource.
```shell
$ terraform state show module.that.aws_ecs_task_definition.this_non_created_resource
No instance found for the given address!

This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify 
the address to reference a specific instance.
$ echo $?
1
```
