### ISSUE TITLE
Two TF modules with the same name. Documentation issue?

### ISSUE THREAD

**Issue by smileprem** [hashicorp/terraform#17819]
This could probably be a documentation issue. I see two components with the same name `google_compute_network`. Here are the URLs.

https://www.terraform.io/docs/providers/google/r/compute_network.html

https://www.terraform.io/docs/providers/google/d/datasource_compute_network.html

Which one should I use to create a VPC network in GCP?

**Comment by jbardin** [comment]
Hi @smileprem,

The first is a [resource](https://www.terraform.io/docs/configuration/resources.html) and the second is a [data source](https://www.terraform.io/docs/configuration/data-sources.html). 

You want the "resource" create a resource.

**Comment by smileprem** [comment]
Oh my goodness. I overlooked too much :(
