### ISSUE TITLE
Still getting configuration for module.x<module.y>.provider.aws is not present; a provider configuration block is required for all operations

### ISSUE THREAD

**Issue by JazminGonzalez-Rivero** [hashicorp/terraform#17817]
Hi everyone, I am running into a provider not present error after I moved a module. I looked at a few tickets to try and resolve this including https://github.com/hashicorp/terraform/issues/17365 but no luck my setup still seems to be locked (i even tried moving my module back to its original location but still getting the same error). Wanted to send this before I revert my state in S3. 

I have tired in 11.1 and 11.6

### Terraform Configuration Files

Before moving the module I did not have any explicit provider aliases. the provider used was defined in each module. 

Current setup...

I have a top level main file that I run everything from that has the following...

```
provider "aws" {
  region                  = "us-west-2"
  alias                   = "us-west-2"
  profile                 = "${var.profile}"
}

provider "aws" {
  region                  = "us-east-2"
  alias                   = "us-east-2"
  profile                 = "${var.profile}"
}

module "dev_us-west-2_setup" {
  source = "target_app_support"
  providers {
    "aws.multi" = "aws.us-west-2"
  }
  region  = "${var.region}"
  profile = "${var.profile}"
  ...
}

module "dev_elbs_us_east_2" {
  source = "target_app_support"
  region  = "us-east-2"
  providers {
    "aws.multi" = "aws.us-east-2"
  }
  profile = "${var.profile}"
...
}
```

This calls a second module that contains ...

```
provider "aws" {
  region = "${var.region}"
  alias = "multi"
}

resource "aws_elb" "sampleapp-elb" {
  count = "${length(module.accounts.all_accounts)}"
  provider = "aws.multi"
...
}
```

### Debug Output
debug logs don't look too interesting but let me know if still needed.

```
module.new_module.aws_elb.sampleapp-elb[8]: configuration for module.old_module.provider.aws is not present; a provider configuration block is required for all operations
```

### Expected Behavior
After moving the module, the resources in that module should use the new provider path.

### Actual Behavior
Although the module moves, the provider references in the resources are still pointing to the old location. 

### Steps to Reproduce
1. create a parent/child module with the child module having its own provider definition 
2. rename the module 
3. `terraform state mv module.old module.new`
4. terraform init -reconfigure
5. terraform get -update
6. terraform apply -auto-approve=false

Things I have tried:
creating a dummy old module that has a provider.
going back to the old setup
explicitly passing the providers via the aliases.

**Comment by JazminGonzalez-Rivero** [comment]
Oops user error

**Comment by jbardin** [comment]
Hi @JazminGonzalez-Rivero,

Glad you figured it out, but you did actually uncover a small bug in here!
I opened #17818 to take acre of it. Thanks!
