### ISSUE TITLE
Feature Request: Output (export) all module's resources

### ISSUE THREAD

**Issue by Binternet** [hashicorp/terraform#17820]
### Terraform Version

```
0.11.6
```

### Terraform Configuration Files

`iam` is a module which has 4 sub-modules within it.

```hcl
├── iam
│   ├── group
│   │   ├── iam-group-membership.tf
│   │   ├── iam-group-policy.tf
│   │   ├── iam-group.tf
│   │   └── variables.tf
│   ├── iam.tf
│   ├── policy
│   │   ├── iam-policy-attachment.tf
│   │   ├── iam-policy.tf
│   │   └── variables.tf
│   ├── role
│   │   ├── iam-role-policy.tf
│   │   ├── iam-role.tf
│   │   └── variables.tf
│   ├── user
│   │   ├── iam-user-policy.tf
│   │   ├── iam-user.tf
│   │   ├── outputs.tf
│   │   └── variables.tf
│   └── variables.tf
```

### Expected Behavior

After creating all the `iam users`, I need to assign a user to a policy - this happens in the `policy` module under`iam-policy-attachment.tf`:

```hcl
resource "aws_iam_policy_attachment" "my-policy-name" {
    name       = "my-policy-name"
    policy_arn = "arn..."
    groups     = []
    users      = ["${aws_iam_user.USER_HERE.name}"] <-- from the user module
    roles      = []
}
```

under `iam/user/outputs.tf` I should be able to use:
```hcl
output "users" {
  value = ["${aws_iam_user.*.name}"]
}

```
### Actual Behavior

I need to export each user's name one-by-one in a separate `output` statement per user...that's a very long and repetitive task.

**Comment by vyasknellutla** [comment]
Hi @Binternet,

I know that this is an old request, but it is now available via the following syntax:
```hcl
module "my_module" {
  source = "./my_module"
}

output "my_output" {
  value = module.my_module
}
```
```bash
my_module = {
  "output1" = "foo"
  "output2" = "bar"
}
```

Note: Tested it on terraform v0.12.24

**Comment by Binternet** [comment]
It's better late than never, thanks! ;-)
