### ISSUE TITLE
provider/aws: Add support for CloudSearch

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1786]
This will likely include more than 1 resource.

http://docs.aws.amazon.com/cli/latest/reference/cloudsearch/index.html
http://docs.aws.amazon.com/cli/latest/reference/cloudsearchdomain/index.html

**Comment by phinze** [comment]
Hey there - we're consolidating Requests for AWS API Coverage over in the spreadsheet linked at #28 - head over there to record your username on what you'd like us to prioritize next!
