### ISSUE TITLE
Terraform does not reconnect after restarting network interface

### ISSUE THREAD

**Issue by 422158** [hashicorp/terraform#17870]
Hello i am having an issue with newest versions of terraform. I have a simple module containing a VM (i am deploying on azure, but that should be irelevant). After creation of the machine I am doing a provisioning and within the provisioning I am restarting the network interface (within OS - Windows), with command
```Restart-NetAdapter```
In previous versions of terraform this was OK and terraform was able to reconnect afterwards and continue with provisioning (for example version 0.10.8 is OK with this). However, with current version i receive error as listed bellow. Not sure wheather this is bug or intention, but i suppose terraform should be able to reconnect. 

### Terraform Version

```
v 0.11.7
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

Error: Error applying plan:

1 error(s) occurred:

* module.loc-0-printer-1.module.dummy-win.azurerm_virtual_machine.spawn-vm: error executing "C:/Temp/terraform_2110697891.cmd": unknown error Post http://17.0.0.4:5985/wsman: read tcp 11.0.1.4:33722->17.0.0.4:5985: read: connection reset by peer

**Comment by 422158** [comment]
Hello guys since this issue is still prevailing I have decided to solve this with temporary workaround: 

Setting parameter on_failure to continue. This way provisioner will ignore that it has failed.
Example:
```
provisioner "remote-exec" {
    on_failure = "continue"
    inline = ["powershell.exe -file C:/remote_scripts/dhcp_to_static.ps1"]
}
```

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
