### ISSUE TITLE
Resource is marked for deletion after import

### ISSUE THREAD

**Issue by vkatsikaros** [hashicorp/terraform#17871]
### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.aws v1.14.1
```

### Terraform Configuration Files

Tree structure in a clean state
```
bug_import$ tree 
.
├── common
│   └── common.tf
└── modules
    └── common
        ├── route53.tf
        └── vars.tf
```
common/common.tf
```hcl
provider "aws" {
  region = "eu-west-2"
}

module "core" {
  source = "../modules/common"
}
```
modules/common/route53.tf
```hcl
resource "aws_route53_zone" "domain" {
  name = "${var.domain}."
}
```

modules/common/vars.tf
```hcl
variable "domain" {
  default = "example.com"
}
```

### Debug Output
https://gist.github.com/vkatsikaros/ab93af4891a63254f4d5d7413a87693c#file-0_init
https://gist.github.com/vkatsikaros/ab93af4891a63254f4d5d7413a87693c#file-1_impot
https://gist.github.com/vkatsikaros/ab93af4891a63254f4d5d7413a87693c#file-2_plan
https://gist.github.com/vkatsikaros/ab93af4891a63254f4d5d7413a87693c#file-3_cat

### Crash Output

None

### Expected Behavior
I'd expect that no actions (creations/destructions) are required.

### Actual Behavior

Actions are required after all
```
Terraform will perform the following actions:

  - aws_route53_zone.domain

  + module.core.aws_route53_zone.domain
      id:             <computed>
      comment:        "Managed by Terraform"
      force_destroy:  "false"
      name:           "example.com."
      name_servers.#: <computed>
      vpc_region:     <computed>
      zone_id:        <computed>
```

### Steps to Reproduce
1. bug_import/common$ export TF_LOG=trace
2. bug_import/common$ terraform init
3. bug_import/common$ terraform import -config ../modules/common/ aws_route53_zone.domain ZZZZZZZZZZ
4. bug_import/common$ terraform plan

### Additional Context
I am not sure if this is a terraform or an aws provider issue so I opened it here.

### References
This unresolved issue seems somehow related
- #16119

**Comment by apparentlymart** [comment]
Hi @vkatsikaros,

This is happening because you've used the `-config` argument to make Terraform consider your "core" module as the root module, and so (as we can see in the plan) it's importing as `aws_route53_zone.domain` rather than `module.core.aws_route53_zone.domain`. When you later run `plan` that overridden configuration path no longer applies.

To get the desired result, you need to import into the module-qualified address:

```
$ terraform import module.core.aws_route53_zone.domain ZZZZZZZZZZ
```

**Comment by frolickingferret445** [comment]
Is this documentation fix going to be merged in any time soon?
