### ISSUE TITLE
How to escape in data template_file

### ISSUE THREAD

**Issue by nodesocket** [hashicorp/terraform#17899]
When using `data "template_file"` I have an Apache config which also unfortunately uses the `${}` syntax which I don't want Terraform to do substitution.

I tried escaping the `$` with a backslash but Terraform is still trying to substitute.

In the template_file:

        ErrorLog "|/usr/bin/rotatelogs -t ${APACHE_LOG_DIR}/logs.error.log.%H 3600"

I tried:

     ErrorLog "|/usr/bin/rotatelogs -t \${APACHE_LOG_DIR}/logs.error.log.%H 3600"

But still getting:

    * module.api.data.template_file.apache_file: data.template_file.apache_file: failed to render : 6:42: unknown variable accessed: APACHE_LOG_DIR

**Comment by nodesocket** [comment]
Figured it out. For others, you have to use `$$` to escape interpolation.

    ErrorLog "|/usr/bin/rotatelogs -t $${APACHE_LOG_DIR}/logs.error.log.%H 3600"

**Comment by lachnerd** [comment]
does someone know how to escape '{' and '}' or even '%{{' ?
