### ISSUE TITLE
Feature request: use KMS Key Alias instead of KMS Key

### ISSUE THREAD

**Issue by harkamals** [hashicorp/terraform#17902]
### Terraform Version
0.11.3

### Expected Behavior
Allow usage of KMS KEY ALIAS for encryotion of the statefile at s3 backend. This allows for the key to be rotated and to comply with security policies.

### Actual Behavior
KMS key is to be provided, this is not a good security practice as the key cannot be rotated.

**Comment by alex-ikse** [comment]
This feature has already been integrated ... but stop working with v1.6.0
See: https://github.com/hashicorp/terraform/issues/33979

**Comment by crw** [comment]
Thanks for that update. Will close this issue, we are tracking https://github.com/hashicorp/terraform/issues/33979
