### ISSUE TITLE
Spurious var in documentation

### ISSUE THREAD

**Issue by m4rkw** [hashicorp/terraform#17903]
https://www.terraform.io/docs/configuration/interpolation.html

Either I'm missing something or the "count" variable defined at the top of the code block underneath "Using Templates with Count" is at best pointless and at worst possibly misleading.

**Comment by alexis-turpin** [comment]
The count variable in https://www.terraform.io/docs/configuration/interpolation.html#using-templates-with-count is indeed misleading.

Once PR #18245 is merged the issue should be solved.

**Comment by nfagerlund** [comment]
resolved in 20783
