### ISSUE TITLE
Feature request: extend self variables outside of provisioners and make them lazy

### ISSUE THREAD

**Issue by m4rkw** [hashicorp/terraform#17908]
Consider this template for AWS tags defined as a local:

```hcl
locals {
  tags = {
    "Name"          = "${var.aws_env}-${var.aws_region}-${var.product}-${var.service}"
    "owner"         = "${var.team}"
    "customer"      = "${var.customer}"
    "environment"   = "${var.aws_env}"
    "product"       = "${var.product}"
    "service"       = "${var.service}"
  }
```

This is similar to a tagging template that we define for our AWS resources, and can then be "inherited" by various modules built by other teams.  They simply link to this template in their workspace and the tags become available as local.tags based on the vars that define that workspace.

This is fine for some modules with only one resource, but is less than ideal for modules that define multiple resources. A good example is dynamodb tables, say a module creates two tables:

```
staging-eu-west-1-myproduct-myservice-system1
staging-eu-west-1-myproduct-myservice-system2
```

Using the tagging template as defined above both of these tables will end up with the same generic Name tag which is not ideal. This can be worked around by overriding the Name tag in the module, eg:

```hcl
tags  = "${merge(var.tags, map("Name", "${var.tags["Name"]}-system1"))}"
```

however it would be nice if this could be made simpler and be done by inference instead.

Are there any plans to extend the self variable functionality so that it works outside of provisioners?

eg

```hcl
resource "aws_dynamodb_table" "system1" {
  tags  = "${merge(var.tags, map("Name", "${var.tags["Name"]}-${self.id}"))}"
}
```

what would also be really nice would be if self variables could be defined in locals and load lazily. so in my locals.tf i could do something like:

```hcl
locals {
  tags = {
    "Name"          = "${var.aws_env}-${var.aws_region}-${var.product}-${var.service}-${self.id}"
    "owner"         = "${var.team}"
    "customer"      = "${var.customer}"
    "environment"   = "${var.aws_env}"
    "product"       = "${var.product}"
    "service"       = "${var.service}"
  }
```

and then have self.id only be evaluated when it's processed inside a resource block.

This would make it easy to create dynamic tagging templates that can be easily used by other teams without much effort.

**Comment by apparentlymart** [comment]
Hi @m4rkw! Sorry we didn't respond to this sooner.

This request seems to overlap quite a lot with the one in #3267, so I'm going to close this one just to consolidate the discussion over there.
