### ISSUE TITLE
Installing unsupported Provider from Git (Offline Mode) (windows)

### ISSUE THREAD

**Issue by jdor300** [hashicorp/terraform#17914]
Hi there,

i'm using a standalone Terraform on Windows (offline),
while installing providers to my code i need to declare the provider only if my `.exe` file (that is supported by Terraform) is in my main folder. and that works.

there are many providers that does not supported by Terraform and i can get them by cloning from their git. but i couldn't install them.. i cant find where should i put the code ... 
i saw some stuff on the internet that says i should put all the code form the git inside `Terraform.d` , but i don't have such folder.. only a `Terraform.exe` and my `main.tf`.

how can i install a provider that exists only on Git (Example : "AD provider.")

**Comment by jbardin** [comment]
Hi @jdor300,

To keep the plugin with the configuration, you can place a provider binary in the configuration directory under `terraform.d/plugins`. The global location on windows is the `terraform.d/plugins` directory beneath your user's "Application Data" directory. You can also specify the location with the `-plugin-dir` option during `init`.

See the related sections on [Configuring Providers](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins), and [Running Terraform in Automation](https://www.terraform.io/guides/running-terraform-in-automation.html#pre-installed-plugins), and the [`init` command](https://www.terraform.io/docs/commands/init.html#plugin-installation).

As for compiling the provider code, that is often dependent on the provider itself. It might be as simple as `go install`, or there may be other external dependencies that need to be met first. The provider authors may have documentation for building the provider.
