### ISSUE TITLE
Terraform remote state version is greater than Docker image version

### ISSUE THREAD

**Issue by adjavaherian** [hashicorp/terraform#17922]
It seems as if the last few CI builds that we've done here, are bumping the remote state (s3) to 

```
    "version": 3,
    "terraform_version": "0.11.7",
```

after a successful plan / apply

This is a little strange, because when I login to the container (terraform:light) directly, and create a local, minimal state with an AWS module, I see

```
    "version": 3,
    "terraform_version": "0.11.5",
```

The result is that subsequent builds cannot be applied 

```
Terraform doesn't allow running any operations against a state
deploy_1  | that was written by a future Terraform version. The state is
deploy_1  | reporting it is written by Terraform '0.11.7'
```

If I manually edit the remote state file, I can build again, but it will continue to bump it back up to latest.  Am I doing something that would upgrade the stack, somewhere between plan and apply?

### Terraform Version
0.11.5

**Comment by jbardin** [comment]
Hi @adjavaherian,

Sorry you're having an issue with this. If the docker image you have creates a state with `"terraform_version": "0.11.5"`, then that is the version of terraform in the image you have. The binaries in the docker images are the same as the separate release binaries.

Pull down the latest docker image locally.

**Comment by jbardin** [comment]
You're local `0.11.5` image can't write a remote state with version `0.11.7`. I'm not quite sure what the relationship here is between the CI builds and the local instance, but if CI is starting fresh each time, without a specifically versioned tag, it's going to be using `:latest`, which is `0.11.7`.

If you're trying to read the remote state written by the CI, then you need to use the same version or newer. If you're writing to the same remote state from both places, then you need to have the same version on each.

**Comment by adjavaherian** [comment]
Okay, thanks James, it looks like it might have been a cached container layer with 0.11.5 that was run after a container with 0.11.7 had been run on Jenkins.  👍
