### ISSUE TITLE
Allowing create and destroy before moving to the next target when running parallelism=1

### ISSUE THREAD

**Issue by marcossegovia** [hashicorp/terraform#17924]
Is there an easy way that when running `parallelism=1` terraform just destroy and create the current machine before jumping to the following target? 
This will make me able to reprovision a whole stack (the stack is serving until the current machine is chosen to be reprovisioned) and not destroying all targets at the same time when reprovision.

### Terraform Version

```
v0.11.7
```

### Expected Behavior
```
vsphere_virtual_machine.assets[0] was destroyed
vsphere_virtual_machine.assets[0] start building
vsphere_virtual_machine.assets[0] finish building
vsphere_virtual_machine.assets[1] was destroyed
vsphere_virtual_machine.assets[0] start building
vsphere_virtual_machine.assets[0] finish building
```
### Actual Behavior
```
vsphere_virtual_machine.assets[0] was destroyed
vsphere_virtual_machine.assets[1] was destroyed
vsphere_virtual_machine.assets[0] start building
vsphere_virtual_machine.assets[0] finish building
vsphere_virtual_machine.assets[1] start building
vsphere_virtual_machine.assets[1] finish building
```

### Steps to Reproduce
When trying to reprovision 2 machines by the following command: 
```
terraform apply -target="vsphere_virtual_machine.assets[0]" -target="vsphere_virtual_machine.assets[1]" -parallelism=1
```

### References
I think there were a discussion a long ago:
- #2896

**Comment by jbardin** [comment]
Hi @marcossegovia,

It sounds like you're looking for a "rolling update" feature, which we're tracking in issue #16378.

Using `-parallelism=1` is not meant to do this, as that will only allow a single resource to be updated at a time, but does not alter the dependency graph for the operations.
