### ISSUE TITLE
Feature Request: get or create resource

### ISSUE THREAD

**Issue by aiqency** [hashicorp/terraform#17932]
Continuing this [post here](https://groups.google.com/forum/#!topic/terraform-tool/2FXt2QcC4sI)

Wouldn't be great if terraform could support a type of "get or create resources" out of the box.

``` tf

resource "aws_security_group" "allow_ssh_only_sg" {
  fail_if_already_exists: false
  ...
}
```

It will make modules and inheritance much easier to deal with.
Ex:
``` tf
# GLOBAL CONFIGS
# get all security groups available in my account
module "base_security_group" {
 source = "git::https://bitbucket.org/account/my-sg-groups.git" 
 ...
}

# PER PROJECT CONFIG
resource "aws_instance" "mInstance" {
  ...
 #Pick up one
 vpc_security_group_ids = [ "${module.base_security_group.allow_ssh_only_sg_id}" ] 
}
```

Is there any reason why this is not implemented yet?

**Comment by jbardin** [comment]
Hi @aiqency,

Thanks for opening the issue.

The idea here is that terraform is solely responsible for managing the resources in the configuration. If a new resource is required, then it is added to the configuration and terraform creates it as expected. New resource should generally not be added externally if you intend to have them managed by terraform. If the resource was created by another terraform configuration, you do not want to have it included in both states.

Often, the `id` that is used to correlate the resource stored in the state cannot be determined by the configuration at all, i.e. it's a unique identifier created by the provider or remote API. In many cases, the configuration doesn't even define the uniqueness of a resource, and a hypothetical `fail_if_already_exists` would never fail, it would just create a new resource with the same attributes and a new `id`. This is why increasing `count` works without any other modification on many resources to allow Terraform to create as many instances of that resource as required.

We do offer the ability to import resources, which can be used add terraform management to existing infrastructure, or to fix issues with existing resources, but that's expected to be a rare operation compared to the overall management of the configuration.

Referencing unmanaged resources from a configuration is the intended use case for data sources. If the security groups are managed externally, you can still use them in your config from the [security_group data source](https://www.terraform.io/docs/providers/aws/d/security_group.html).
