### ISSUE TITLE
Unable to set Terraform S3 remote state(Backend)

### ISSUE THREAD

**Issue by sumsrri** [hashicorp/terraform#17938]
Hi,

Below is the code i have been trying to set remotestate and it doesnt set the terraform 
terraform {
  backend "s3" {
  bucket = "testcbsdatabucket"
  key    = "terraform.tfstate"
  region = "eu-west-2"
  encrypt    = true
}
}

Below is the error i get while terraform init.

2018/04/26 09:57:11 [INFO] command: empty terraform config, returning nil
2018/04/26 09:57:11 [DEBUG] command: no data state file found for backend config
2018/04/26 09:57:11 [DEBUG] New state was assigned lineage "e9a6b912-1d2c-1055-76d0-1df87ad3764e"
2018/04/26 09:57:11 [INFO] command: backend initialized: <nil>
2018/04/26 09:57:11 [DEBUG] checking for provider in "."

Full Trace log:

E:\New folder\TerraformPOC>cd E:\New folder\Terraform_Solarwinds\environments\Dev

E:\New folder\Terraform_Solarwinds\environments\Dev>terraform init
2018/04/26 09:57:11 [INFO] Terraform version: 0.11.4  7878d66b386e5474102b5047722c2de2b3237278
2018/04/26 09:57:11 [INFO] Go runtime version: go1.10
2018/04/26 09:57:11 [INFO] CLI args: []string{"C:\\Tools\\Build\\terraform.exe", "init"}
2018/04/26 09:57:11 [DEBUG] Attempting to open CLI config file: C:\Users\goserviceiac\AppData\Roaming\terraform.rc
2018/04/26 09:57:11 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/04/26 09:57:11 [INFO] CLI command args: []string{"init"}
2018/04/26 09:57:11 [DEBUG] command: loading backend config file: E:\New folder\Terraform_Solarwinds\environments\Dev
Initializing module2018/04/26 09:57:11 [DEBUG] fetching module from file://E:/New folder/Terraform_Solarwinds/solarwinds
2018/04/26 09:57:11 [DEBUG] fetching "file://E:/New folder/Terraform_Solarwinds/solarwinds" with key "1.solarwinds;../../solarwinds"
s...
- module.solarwinds
  Getting source "../../solarwinds"
2018/04/26 09:57:11 [DEBUG] found "file://E:/New folder/Terraform_Solarwinds/solarwinds" in ".terraform\\modules\\ef40ead972db1c67a7fa8db71e04aaab": true
- module.solarwin2018/04/26 09:57:11 [DEBUG] fetching module from file://E:/New folder/Terraform_Solarwinds/solarwinds/solarwinds_asg
2018/04/26 09:57:11 [DEBUG] fetching "file://E:/New folder/Terraform_Solarwinds/solarwinds/solarwinds_asg" with key "1.solarwinds;../../solarwinds|solarwinds_dev;./solarwinds_asg"
ds.solarwinds_dev
  Getting source "./solarwinds_asg"
2018/04/26 09:57:11 [DEBUG] found "file://E:/New folder/Terraform_Solarwinds/solarwinds/solarwinds_asg" in ".terraform\\modules\\ef5d38980fe076ced887734d297b2e80": true
- module2018/04/26 09:57:11 [DEBUG] fetching module from file://E:/New folder/Terraform_Solarwinds/solarwinds/solarwinds_dns
.2018/04/26 09:57:11 [DEBUG] fetching "file://E:/New folder/Terraform_Solarwinds/solarwinds/solarwinds_dns" with key "1.solarwinds;../../solarwinds|r53_dns_dev;./solarwinds_dns"
solarwinds.r53_dns_dev
  Getting source "./solarwinds_dns"
2018/04/26 09:57:11 [DEBUG] found "file://E:/New folder/Terraform_Solarwinds/solarwinds/solarwinds_dns" in ".terraform\\modules\\4f6ede09b9720f61565abbc3b1fa49fb": true

2018/04/26 09:57:11 [INFO] command: empty terraform config, returning nil
2018/04/26 09:57:11 [DEBUG] command: no data state file found for backend config
2018/04/26 09:57:11 [DEBUG] New state was assigned lineage "e9a6b912-1d2c-1055-76d0-1df87ad3764e"
2018/04/26 09:57:11 [INFO] command: backend initialized: <nil>
2018/04/26 09:57:11 [DEBUG] checking for provider in "."
2018/04/26 09:57:11 [DEBUG] checking for provider in "C:\\Tools\\Build"
2018/04/26 09:57:11 [DEBUG] found provider "terraform-provider-aws_v1.11.0_x4.exe"
2018/04/26 09:57:11 [DEBUG] found provider "terraform-provider-template_v1.0.0_x4.exe"
2018/04/26 09:57:11 [DEBUG] found valid plugin: "aws", "1.11.0", "C:\\Tools\\Build\\terraform-provider-aws_v1.11.0_x4.exe"
2018/04/26 09:57:11 [DEBUG] found valid plugin: "template", "1.0.0", "C:\\Tools\\Build\\terraform-provider-template_v1.0.0_x4.exe"

**Comment by sumsrri** [comment]
Could you please let me know if am missing something.

**Comment by sumsrri** [comment]
Hi,

Could you please help me on the above?

**Comment by luthes** [comment]
Forgive me if I'm missing it, but I don't see an error. A bunch of INFO/Debug messages, but no error.

**Comment by AkhterAli** [comment]
@sumsrri If you haven't run `terraform init` I'd run that first.  Also state files aren't updated until you run `terraform apply` I believe.

**Comment by sumsrri** [comment]
Hi @AkhterAli , I did Terraform init  and the trace attached is from terraform init,

I did do Terraform apply to see if state file is uploaded to S3 but it isnt.

The whole point is the terraform init should come up with backend initialized successfully and should say its configure to S3 but its coming up with *NIL*

**Comment by jbardin** [comment]
@sumsrri,

The `terraform` configuration block isn't being loaded for some reason. Are you certain that file is in the root module, with a valid filename ending in `.tf`?

**Comment by sumsrri** [comment]
HI @jbardin  below is my tf file.







provider "aws" {
version = "1.11"
#access_key = "XXXX"
#secret_key = "XXXX"
region = "${var.region}"
assume_role { 
role_arn = "arn:aws:iam::XXXX:role/AdministratorRole"
            }
}

terraform {
  backend "s3" {
bucket = "cf-templates-1bv1dc8lgchs-eu-west-2"
key = "terraform"
region = "eu-west-2"
encrypt = true
}
}

data "aws_ami" "cbs_win2012" {
  most_recent = true
  filter {
    name = "owner-id"
    values = ["XXXX"]
  }
  filter {
    name = "name"
    values = ["*WS2012R2*"]
  }
  owners = ["XXXX"]
}

resource "aws_instance" "server" {
    count = "${var.no_of_instances}"
    ami = "ami-d60debb1"
    instance_type = "${var.ins_type}"
    vpc_security_group_ids = "${distinct(var.sec_groups)}"
    iam_instance_profile = "SecretsManagerReadWrite"
    subnet_id = "${var.subnet}"
    tags {
       BillingCode = "${var.tag_Costcentre_Projectcode}"
       Name = "${format("${var.tag_Name}%03d", count.index+10)}"
       Owner = "${var.tag_Owner}"
       AlwaysOn = "${var.tag_Schedule}"
       DataCategory = "${var.tag_role}"
       Enviroment = "${var.tag_env}"
       Hostname = "${var.tag_hsn}"
       NetworkZone = "${var.tag_zone}"
       ProjectName = "${var.tag_project}"
       Schedule = "${var.tag_Schedule}"
      }
   user_data = "${file("${var.file_name}")}"

    ebs_block_device {
     device_name =  "${var.ebs_block_device_name}"
     volume_size = "${var.ebs_block_device_volume_size}"
     volume_type = "${var.ebs_block_device_volume_type}"
    }
}

**Comment by jbardin** [comment]
@sumsrri,

I don't see anything suspect, and indeed dropping that file into the working directory will attempt to init the configured s3 backend. However, your original post showed the loading of some modules but this config has no module blocks. Can you show a complete example of your root module, and how you are running it?

**Comment by sumsrri** [comment]
[Terraform_Poc.zip](https://github.com/hashicorp/terraform/files/1965038/Terraform_Poc.zip)

Hi @jbardin,

yes i had multiple modules ealier as it wasnt working just trimmed my modules to a simple one as attached still no luck.

Thanks for looking into this.

**Comment by jbardin** [comment]
Hi @sumsrri,

Thanks for the complete example. your root module has no `terraform` configuration block.
The backend must be configured in the root of your configuration.
