### ISSUE TITLE
schemaMap.Diff does not diff TypeSet entirely

### ISSUE THREAD

**Issue by sylr** [hashicorp/terraform#17931]
Hi

Let me give you a bit of context:

 - I am using azurerm provider
 - I am not really happy about how terraform handles diffs of `security_rule`s inside `network_security_group` objects

In a few words, currently, if you happen to change a `security_rule` locally you will see a huge diff (see https://github.com/terraform-providers/terraform-provider-azurerm/issues/858#issuecomment-382340450) because the `security_rule` keys are computed against all the properties of the `map[string]*schema.Schema` leading to change of keys if you add/delete/update properties of a `security_rule`.

So I wrote a function which compute `security_rule`s keys exclusively on the keys tuple that is supposed to be unique (https://github.com/terraform-providers/terraform-provider-azurerm/pull/1152/files#diff-02a62c4182918d899d123e535c80ac12) so that `security_rule` keys does not get recomputed if not needed.

Unfortunately after I've done that `terraform plan` would not give me any diff when I change rules locally.

I believe it is because the **5th** argument of the following call to `schemaMap.diff` is set to `false`.

https://github.com/hashicorp/terraform/blob/c1bc0be7b2c990ae0d95a72e560bc814db2ce60c/helper/schema/schema.go#L424

It seems that if set to false, the underlying `schemaMap.diffSet` function will look no further than the presence/absence of keys.

Is there a reason for this to be hardcoded to `false` ? What are the implications of switching it to `true` ?

**Comment by sylr** [comment]
Yeah so after further testing it seems that setting this to true implies that everything is marked with a diff ...

**Comment by apparentlymart** [comment]
Hi @sylr! Sorry for the long silence here.

I must admit that I'm also not sure off the top of my head exactly what is going on here. However, I wanted to note that the internal representation of configuration, state and diff will be changing in the next major release of Terraform to no longer use the dot-delimited-string map representation, which will in turn lead to the diff-creation code being changed significantly.

We don't intend to actually change the behavior significantly for this release -- instead, the existing behavior will be preserved against the new internal models -- but the new representation may make it easier to adjust the behavior here in future, so we can revisit this after the release and see what changes, if any, are needed.

**Comment by sylr** [comment]
> state and diff will be changing in the next major release of Terraform to no longer use the dot-delimited-string map representation

@apparentlymart That's music to my ears. Any chance you got a timetable of that re-factorization ? I'd help to test it and give feedback.

**Comment by apparentlymart** [comment]
This project is the current focus for the team at HashiCorp, and we're planning to publish a preview release for testing as soon as it's in a workable state.

There are a lot of parts to this (this detail is actually just one small part of a larger effort), so at the moment we're not yet able to commit to a release date, but once the preview release is out we'd love help with testing it across a variety of different configurations and providers.

**Comment by teamterraform** [comment]
Closing as this is likely addressed by 0.12, but please let us know if that's incorrect.
