### ISSUE TITLE
Circular dependency when provisioner for destroy references array member for AWS

### ISSUE THREAD

**Issue by artur-fijalkowski** [hashicorp/terraform#17944]
To resolve problem with disk attachment on AWS (disk attachement cannot be destroyed when disk is mounted on OS level) I created following code:

```hcl
resource "aws_volume_attachment" "attachement_myservice" {
  count			=	"${length(var.network_myservice_subnet_ids)}"
  device_name   = "/dev/xvdg"
  volume_id     =   "${element(aws_ebs_volume.ebs_myservice.*.id, count.index)}"
  instance_id   =   "${element(aws_instance.myservice.*.id, count.index)}"

  provisioner "local-exec" {
    command = "aws ec2 stop-instances --instance-ids ${element(aws_instance.myservice.*.id, count.index)} --region ${var.region} && sleep 30"
    when = "destroy"
  }
}
```

When trying to rebuild instances (because AMI instances depend on) terraform reports circular dependency for this code. Experiment shows that the problem is with shell command - when reference `${element(aws_instance.myservice.*.id, count.index)}` is replaced with something different terraform works like a charm (production solution for me is to use AWS CLI to first find instance IDs and then use them to stop instances).

Most probably root cause is wrong interpretation of interpolation of array member when building graph for rebuild.

Problem doesn't exist when `terraform destroy` is executed - only on `terraform apply` which is expected to re-build instances.
 

### Terraform Version

```
terraform -v
Terraform v0.11.3

Your version of Terraform is out of date! The latest version
is 0.11.7. You can update by downloading from www.terraform.io/downloads.html

```

### Terraform Configuration Files

```hcl
...
```

**Comment by jbardin** [comment]
Hi @artur-fijalkowski,

Thanks for filing this.
Is it possible for you to get the debug log output when you encounter the cycle? I haven't been able to reproduce this yet, though I may have oversimplified things a bit.

Also, have you tested this with the current release? There were a few internal changes to the evaluation of destroy provisioners recently which may have indirectly fixed this.

**Comment by artur-fijalkowski** [comment]
I will try to do it. The reason I haven't yet is that this is part of bigger solution and I had no time to extract this for testing. But If you can't reproduce I have to do it anyway.

**Comment by jbardin** [comment]
A minimal test cacse for investigation

```
resource "null_resource" "a" {
  triggers = {
    "b" = "${null_resource.b.id}"
  }

  provisioner "local-exec" {
    command = "echo ${null_resource.b.id}"
    when = "destroy"
  }
}

resource "null_resource" "b" {
}
```

Tainting `null_resource.b` will trigger the cycle, because `null_resource.a` references it in its configuration as well as in the destroy provisioner.

    * Cycle: null_resource.b (destroy), null_resource.b, null_resource.a (destroy)

**Comment by jbardin** [comment]
An interesting workaround here is adding `create_before_destroy` to the affected resource.

The reason for the cycle is that the normally destroy dependencies flow in reverse. Node `a` is created before `b`, so `b` is destroyed before `a`. The problem arrises when you add a destroy provisioner, which is an action that depends the references existing, so the dependencies flow in the opposite direction of the destroy. 

So the dependencies go from:
 
![graph](https://user-images.githubusercontent.com/35067/39843085-67d3f50c-53b7-11e8-8cf4-01435658405b.png)


to:
![graph2](https://user-images.githubusercontent.com/35067/39843092-6f87102c-53b7-11e8-9a1f-94503154cc05.png)

We'll have to determine how we want to handle this after the next major release. I'm not sure if there's a good solution other than inverting the order, but at least we know it can be detected and reported fairly clearly to the user.
