### ISSUE TITLE
Allow Interpolations Inside of Variable's "default" Argument

### ISSUE THREAD

**Issue by bgshacklett** [hashicorp/terraform#17953]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
variable "image_id" {
  description = "The ID of the preferred AMI (optional)"
  type = "string"
  default = "${data.aws_ami.default_ami}"
}

...

data "aws_ami" "default_ami" {
  most_recent = true

  filter {
    name = "owner-alias"
    values = ["amazon"]
  }

  filter {
    name = "name"
    values = ["amzn-ami-hvm-*"]
  }
}
```

### Expected Behavior
The default value of the "image_id" variable should be set to the result of the "aws_ami" .

### Actual Behavior
Interpolations are not allowed as the value of the "default" argument of a Variable.
```
terraform validate
Error: variable "image_id": default may not contain interpolations
```

### Steps to Reproduce

`terraform validate`

### Use Case
As in my example configuration, this could be used to allow an AMI to be automatically selected without explicit conditional logic later on in the template.

**Comment by jbardin** [comment]
Hi @bgshacklett,

Variable default values need to be evaluated before any interpolation can be done.
Interpolating values within a module for reuse is the use case for [local values](https://www.terraform.io/docs/configuration/locals.html).

There a lot of discussion in #4084, and various other issues.
