### ISSUE TITLE
Feature request: CircleCI module in order to keep credentials updated

### ISSUE THREAD

**Issue by peleteiro** [hashicorp/terraform#17951]
I would be really nice to manage CircleCI context, environment variables and AWS credentials updated through terraform.

**Comment by janoszen** [comment]
Please vote for the required API integration here: https://circleci.com/ideas/?idea=CCI-I-545

**Comment by paultyng** [comment]
There is a [CircleCI provider](https://github.com/thiagoalessio/terraform-provider-circleci) which lets you set env vars on a project available. The additional features are probably best requested on an issue over on that repository.
