### ISSUE TITLE
Map lookup still throws missing key error when it is never called.

### ISSUE THREAD

**Issue by MaxFlanders** [hashicorp/terraform#17974]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.14.0
+ provider.null v1.0.0
```

### Terraform Configuration Files

```hcl
local_variable = ${ contains( keys(var.constants), "some_key" ) == "true" ? var.constants["some_key"] : "other_default_value" }
```

### Expected Behavior

Terraform does not throw a "key does not exist error" unless the key is actually going to be used, especially when the wrapping conditional checks for the existence of the key.

### Actual Behavior

An error is thrown:
```
* module.mod.local.: local.local_variable: key "some_key" does not exist in map var.constants in:
${ contains( keys(var.constants), "some_key" ) == "true" ? var.constants["some_key"] : "other_default_value" }
```
### Steps to Reproduce

Create a conditional local variable like above, which checks the map for a key before using the key, and run terraform.

**Comment by jbardin** [comment]
Hi @MaxFlanders,

Sorry this is causing you an issue. The index operation _does_ happen in that expression, because conditionals themselves are not short-circuiting. 

This is an enhancement we have planned, and there is an open issue at #15605
