### ISSUE TITLE
Failed to destroy when sharing values between modules

### ISSUE THREAD

**Issue by icy-arctic-fox** [hashicorp/terraform#17976]
I have a situation where I'm trying to generate and use a value (an ID) between multiple modules. But, there must be some action taken with the generated ID before it can be used. For example, generate a unique ID, and then provide that ID to another module to create the resource with the provided ID, and then the ID is safe to use. To achieve this, I use `null_resource` to create the resource, but really any other type of resource could be used. Then I use `null_data_source` (`template_file` also works) and pass the ID in and add an explicit dependency on the `null_resource`. Everything is created ok, but when the resources are destroyed, I get an error. Perhaps I'm just doing something wrong and there's a better way to achieve this.

### Terraform Version

```
Terraform v0.11.7
+ provider.null v1.0.0
+ provider.random v1.2.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

It took me a while to narrow down and produce a small example to report this. The error only occurs when there are these three modules involved. Having a parent-child relationship with two modules, or all code in one module does not reproduce the error.

```hcl
# main.tf

module "foo" {
  source = "./foo"
}

# Simulate using the ID after it has been "applied".
# Removing this still gives the error.
resource "null_resource" "foo" {
  provisioner "local-exec" {
    command = "echo ${module.foo.id}"
  }
}

output "id" {
  value = "${module.foo.id}"
}
```

```hcl
# foo/main.tf

module "bar" {
  source = "../bar"
}

# Create the resource with the given ID.
# This is simulated by just echoing the ID.
resource "null_resource" "apply" {
  provisioner "local-exec" {
    command = "echo ${module.bar.id}"
  }
}

# Workaround to ensure the resource is created before the ID is used.
data "null_data_source" "apply" {
  inputs {
    id = "${module.bar.id}"
  }
  depends_on = ["null_resource.apply"]
}

# As long as other modules depend on this output,
# the dependency graph works as needed.
output "id" {
  value = "${data.null_data_source.apply.outputs["id"]}"
}
```

```hcl
# bar/main.tf

# Simulate generating a random ID.
resource "random_id" "this" {
  byte_length = 16
}

output "id" {
  value = "${random_id.this.hex}"
}
```

### Debug Output
https://gist.github.com/icy-arctic-fox/a3c1e43731f473f994c857383fa23ced

### Expected Behavior
Resources are destroyed and no errors occur.

### Actual Behavior
An error occurs while destroying the resources. All "real" resources seem to be destroyed.

```
Error: Error applying plan:

1 error(s) occurred:

* module.foo.output.id: Resource 'data.null_data_source.apply' does not have attribute 'outputs' for variable 'data.null_data_source.apply.outputs'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

When using `template_file` instead, the error changes to `does not have attribute 'rendered'`.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform destroy`

**Comment by jbardin** [comment]
Hi @icy-arctic-fox,

Thanks for filing the issue with an excellent reproduction case!
This a known issue and will be fixed by #17942.

**Comment by icy-arctic-fox** [comment]
Awesome, glad you guys are already looking into it! I've been confused as to why this is happening and having quite the time working around something I didn't understand. Good thing you guys understand it though. Looking forward to the fix. :+1:

**Comment by jbardin** [comment]
In the meantime, if you didn't see it in the other issues, as long as the output errors isn't causing other issues you can work around them by setting `TF_WARN_OUTPUT_ERRORS=1`.

**Comment by icy-arctic-fox** [comment]
Ah, good to know. I'll try that. I've been manually ensuring things got deleted.

For a larger project I'm working on, I get the same error as #17862 when running the destroy again. `is nil, but no error was reported`. Can confirm that these issues are related to #17942
