### ISSUE TITLE
Unable to register new public module

### ISSUE THREAD

**Issue by phuonghuynh** [hashicorp/terraform#17979]
Hello,

I am unable to publish new module to https://registry.terraform.io ; see screenshot bellow. Is there anything else I could check with my Terraform Registry account?

<img width="1078" alt="screenshot at may 01 11-03-12" src="https://user-images.githubusercontent.com/705510/39463565-e2d7612e-4d42-11e8-86e9-f0668a340257.png">

**Comment by justincampbell** [comment]
@phuonghuynh Thanks for the report! Could you try again? I noticed some timeout errors around the time this issue was opened, so I'm wondering if it was an ephemeral issue.

**Comment by phuonghuynh** [comment]
@justincampbell Thanks for getting back so fast. I tried again but no luck, 503 still being happened on my site

**Comment by justincampbell** [comment]
@phuonghuynh Just wanted to let you know we've found the issue, and a fix should be implemented in the next day or so. Sorry for the delay!

**Comment by justincampbell** [comment]
@phuonghuynh The issue should now be resolved. Let us know if you encounter any other problems. Thanks!

**Comment by phuonghuynh** [comment]
@justincampbell  its working ; thanks @justincampbell ^

<img width="741" alt="screenshot at may 08 23-10-25" src="https://user-images.githubusercontent.com/705510/39769031-2fbef204-5315-11e8-9185-3ae86b81b914.png">
