### ISSUE TITLE
conditionally raise a configuration error

### ISSUE THREAD

**Issue by moali87** [hashicorp/terraform#17977]
### Terraform Version
```
0.11.7
```

### Terraform Configuration Files

```hcl
# locals.tf
locals {
  account_type = "${data.aws_caller_identity.current.account_id == "1234567890" ? "dev" : "prod" }"
  workspace_check = "${local.account_type == "dev" ? element(split("_", terraform.workspace), 0) : "prod"}"
  account_check = "${local.workspace_check == local.account_type ? 0 : 1}"
}
```

```hcl
# main.tf
resource "null_resource" "account_type_valid" {
  count = "${local.account_check}"
  // TODO: Add govcloud account to prod list
  "ERROR: The account type does not match workspace prefix. Please make sure you are on the right workspace and selecting the right saml2aws role" = true
}
```

### Debug Output
https://gist.github.com/AkhterAli/0cd6665fcc1abcc4d44b7edce47cda58

### Expected Behavior
Condition returns 0 or 1 and only throws error when needed, not always.

### Actual Behavior
Regardless of evaluation results the following error below is the result

```hcl
Error: null_resource.account_type_valid: : invalid or unknown key: ERROR: The account type does not match workspace prefix. Please make sure you are on the right workspace and selecting the right saml2aws role


exit status 1
```

### Steps to Reproduce
1.  Create code given above.
2.  Create workspace name starting with "dev_"
3.  Run `terraform plan`

### References
https://github.com/hashicorp/terraform/issues/15469

**Comment by jbardin** [comment]
Hi @AkhterAli,

Thanks for filing the issue.
If I understand correctly, you would like to ignore the configuration error if the count is 0?

In this case the configuration language is declarative, and must validate against a defined schema. While some future additions may order to some certain evaluations (i.e. conditions, for statements, etc), the config must still be valid in its entirely. 

Currently the validation happens before the count can be determined in all cases, so there no way to skip validation of the resource. In future versions, the schema will be required to even load the configuration, so there won't be any way to load a resource with invalid fields at all.

Do you have another use-case in mind, or was this strictly about trying to skip invalid resource attributes?

**Comment by AkhterAli** [comment]
@jbardin That's right, I don't want the error to evaluate if the count is 0.

What I'm trying to accomplish is this.  If the ${local.account_type} is "dev" the workspace must begin with "dev" 

I wanted to replicate this with another resource for "prod" as well but seeing how "dev" is failing regardless of evaluation I'm unable to move forward.

My use-case is to have a single terraform and separated via conditions for both development environment and production.  I just wanted to separate them via workspace names and raise errors when someone on a dev workspace is attempting to deploy to a production aws account and vice-versa.

Please let me know if you have any more questions.

**Comment by jbardin** [comment]
Thanks for following up. 
Policy enforcement is not something that we intend to provide within terraform itself, as that would need to be enforced by whatever workflow automation terraform is running in. 

However, once we have better control over conditional statements with the new configuration packages, there might be a way to accomplish something similar. I'll leave this as a possible enhancement that we can review it after the next major release.

**Comment by Jamie-BitFlight** [comment]
Hi @jbardin 
toggling incorrect_env between 0 and 1 in the code below works as @AkhterAli is expecting on my  terraform 0.11.7

```hcl
locals {
	incorrect_env = 0
}
resource "null_resource" "env_check" {
  count = "${local.incorrect_env}"
  "ERROR: You can set the environment name by typing: terraform workspace new <name>, where <name> can be dev, qa or prod" = true
}
```

@AkhterAli can you try that code above on your system too?

**Comment by jlsjonas** [comment]
@Jamie-BitFlight did you find a new workaround for terraform 0.12? This sadly doesn't seem to function anymore

**Comment by jdheyburn** [comment]
> @Jamie-BitFlight did you find a new workaround for terraform 0.12? This sadly doesn't seem to function anymore

Give this a try:
```hcl
data "assert_test" "workspace" {
    test = terraform.workspace != "default" // must return TRUE or FALSE
    throw = "default workspace is not valid in this project" // must be of type string
}
```

**Comment by threeguys** [comment]
I'm extremely new to terraform, however I had a similar case where I wanted to fail if a file did not exist:

```terraform
data "null_data_source" "lambda_code" {
    inputs = {
        file_count = tonumber(fileexists("${path.module}/${var.archive_path}") ? "1" : "fail")
        filename = "${path.module}/${var.archive_path}"
    }
}
```

There may be better ways to solve my problem specifically, however this should work for most people that need to fail based on a boolean expression.

On another note, I tried jdheyburn's suggestion and could not get it to work without needing to download more terraform files (which I'm admittedly too lazy to do).

**Comment by realrubberduckdev** [comment]
We definitely need a `raise error` or `throw error` feature.
In Terraform 0.13.2, I am using the following as a workaround.

```
data "external" "throw_error" {
    count = 1 # 0 means no error is thrown, else throw error
    program = ["powershell.exe", "throw 'An error has ocurred.'"]
}
```
