### ISSUE TITLE
`terraform workspace` fails, with exit code 0

### ISSUE THREAD

**Issue by eschwartz** [hashicorp/terraform#17989]
### Terraform Version

```
0.11.7
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

Passing an invalid command `terraform workspace` should result in an exit code > 0

### Actual Behavior

Passing an invalid command `terraform workspace` results in an exit code of 0

### Steps to Reproduce

```
$ terraform workspace create foo
> Usage: terraform workspace

  Create, change and delete Terraform workspaces.

$ echo $?
> 0
```

### Additional Context

I'm writing an automation script, and I accidentally wrote `terrafom workspace create` instead of `terraform workspace new`. But the script just kept on chugging, because the failed command exited `0`

### References

N/A

**Comment by leprechaun** [comment]
I was affected by this just now. Kind of.

I'm writing pipeline, so I was doing `plan` isntead of `apply`, and I don't use `default`, partly for this reason (I want to be explicit about which workspace).

Nothing got created (it would have been all new things, eg, `$thing-default`), nothing destroyed ... I was hoping my build would have gone red, though.

Seems PR worthy, and can't be too complicated.

**Comment by teamterraform** [comment]
Closing, as this issue is no longer applicable.
