### ISSUE TITLE
Terraform Plan doesnt work for docker version 18.03.1-ce

### ISSUE THREAD

**Issue by kasunsjc** [hashicorp/terraform#17997]
Terraform Version

Terraform v0.11.7
+ provider.docker v0.1.1

Docker version
Docker version 18.03.1-ce, build 9ee9f40

 Steps to Reproduce
Terraform code
`resource "docker_image" "image_id" {
  name = "ghost:latest"
}`

terraform init output

`[root@terraformvm module01]# terraform init

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.docker: version = "~> 0.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.`

terraform plan output

`[root@terraformvm module01]# terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.docker: Error pinging Docker server: Get http://unix.sock/_ping: dial unix /var/run/docker.sock: connect: no such file or directory` 

I have tried the same with docker version **docker-ce.x86_64 0:17.09.0.ce-1.el7.centos** and work as expected

**Comment by sandangel** [comment]
may I ask any update on this issue, I still have the same problem
