### ISSUE TITLE
Order of credentials used during init when backend is s3 is not consistent with general expectations

### ISSUE THREAD

**Issue by mallikarjuna-palle** [hashicorp/terraform#18003]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.17.0
```

### Terraform Configuration Files

```provider "aws" {
  access_key = "*"
  secret_key = "*"
  region     = "us-west-1"
}

terraform {
  backend "s3"
  {
    bucket = "malli-terraform"
    region = "us-west-1"
    key = "terraform.tfstate"
    encrypt = true
  }
}

resource "aws_vpc" "vpc1" {
  cidr_block = "10.2.0.0/16"
}
```

### Expected Behavior
The above tf config should use the credentials specified in the provider and not the credentials from the shared credentials file.

### Actual Behavior
Terraform is using the credentials from .aws/credentials file even when static credentials are supplied in provider. This is not as per the general expectation and also deviates from the [documentation of provider](https://www.terraform.io/docs/providers/aws/index.html) which specifies the following order
1. Static credentials
2. Environment variables
3. Shared credentials file
4. EC2 Role

### Steps to Reproduce
1. Save the shared credentials file with invalid key and secret.
2. Give correct credentials in config file->provider
3. Run `terraform init`
4. You will see invalid credentials error.

### References
- https://github.com/terraform-providers/terraform-provider-aws/issues/663

**Comment by jbardin** [comment]
Hi @mallikarjuna-palle,

The backend configuration is entirely independent of any provider configuration blocks, otherwise you wouldn't be able to configure them differently. Since your backend has no credentials defined, it attempts to authenticate with the shared credentials.
