### ISSUE TITLE
aws_autoscaling_group bug

### ISSUE THREAD

**Issue by rajaassaf24** [hashicorp/terraform#18022]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by jbardin** [comment]
Hi @rajaassaf24,

There doesn't seem to be anything here. Please file a new issue if this is still relevant.
Also, if this is an issue specific to AWS, you should file the issue in https://github.com/terraform-providers/terraform-provider-aws/issues
