### ISSUE TITLE
Unknown root level key error

### ISSUE THREAD

**Issue by sujith-siva** [hashicorp/terraform#18020]
Hi there,

I am trying to create a new instance using terraform code and while running the plan I got an error saying 

Credentials decrypted
done.

. $MASTER_SCRIPTS/source_terraform_plan.sh

Error: Unknown root level key: Variable

Running after script...
$ . $MASTER_SCRIPTS/post-stage.sh

set terraform provider... aws

Delete transient directories...

. $MASTER_SCRIPTS/source_credentials.sh
Delete session credentials...
removed ‘/var/lib/terraform/.provider/decrypt.CHP-RESGRP-Parpinelli-EW_19998.creds’

Delete orphaned credentials...
done.

ERROR: Job failed: exit status 1

I have created two new .tf files one for declaring my variables which is called variables.tf and the other one called web_server.tf.

-------------web_server.tf------------------------------------------------------------------------------------
resource "aws_instance" "Web_A" {
  ami                    = "ami-xxxxxxxx"
  instance_type          = "m3.medium"
  key_name               = "xxxxxxx"
  subnet_id              = "${var.subnet_public_a_1}"
  vpc_security_group_ids = ["${var.sg_rol_web}", "${var.sg_dft_windows}" , "${var.sg_rol_opsview}"]

  tags {
    Market      = "xxxx"
    Name        = "WEBP021"
    Description = " Web A"
    Owner       = "WEB;External;10"
  }

  lifecycle {
    prevent_destroy = true
  }

  root_block_device {
    volume_type = "gp2"
    volume_size = "64"
  }
}

resource "aws_volume_attachment" "ebs_vol_d" {
  device_name = "/dev/sdd"
  volume_id   = "${aws_ebs_volume.drive_d.id}"
  instance_id = "${aws_instance.Web_A.id}"
}

resource "aws_ebs_volume" "drive_d" {
  availability_zone = "eu-west-1a"
  type              = "gp2"
  size              = "20"
  encrypted         = true

  tags {
    Name = "WEBP021 D Drive"
  }
}

--------------------variables.tf --------------------------------------------------------------------------

variable "subnet_private_a_1"     {default = "subnet-45671f11" }
variable "subnet_private_b_1"     {default = "subnet-fdac7f98" }
variable "subnet_private_c_1"     {default = "subnet-a44c81d1" }
variable "subnet_public_a_1"      {default = "subnet-4fe94b7b" }
variable "subnet_public_b_1"      {default = "subnet-1fgh7f79" }
variable "subnet_public_c_1"      {default = "subnet-s23451a1" }
variable "sg_dft_windows"         {default = "sg-wqa92c9f"     }
variable "sg_rol_web"             {default = "sg-3d320b0"     }
Variable "sg_rol_opsview"		  {default = "sg-34cs693"     } 
variable "vpc_id"                 {default = "vpc-123456"    }

-----------------------------------------------------------------------------------------------------------------
please give me some assistance,

thanks 
Siva

**Comment by jbardin** [comment]
Hi @sujith-siva, the invalid symbol is `Variable`. You need to use `variable` instead.

**Comment by sujith-siva** [comment]
jbardin,

that was the issue and it worked now.
thanks for your help.

Regards
Siva
