### ISSUE TITLE
Resource 'aws_instance' not found for variable

### ISSUE THREAD

**Issue by phantomakc** [hashicorp/terraform#18044]
Hi,
I do use terraform with aws provider but I don't think this is provider issue.
### Terraform Version

```
bash-3.2$ terraform -v
Terraform v0.11.7
+ provider.aws v1.14.1
+ provider.random v1.2.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
resource "aws_instance" "mongodb-master-shard01" {
  ami                  = "${data.aws_ami.id}"
  instance_type        = "${var.mongodb_ec2_instance_type["shard"]}"
  user_data            = "${data.template_file.user_data.rendered}"
  vpc_security_group_ids = ["${aws_security_group.base.id}","${aws_security_group.ssh.id}"]
  subnet_id            = "${aws_subnet.subnet.*.id}"
  availability_zone    = "${var.aws["region"]}a"

  root_block_device {
    volume_size = 64
    volume_type = "gp2"
    delete_on_termination = true
  }

  tags {
    Name = "mongodb-master-shard01"
    Env  = "${var.env}"
  }
}

resource "aws_ebs_volume" "mongodb-master-shard01-ebs" {
  availability_zone = "${var.aws["region"]}a"
  size = "${var.size}"
  type = "${var.type}"
  tags {
    Name = "${var.env}-mongodb-master-shard01-ebs"
  }
  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_volume_attachment" "mongodb-master-shard01-ebs" {
  device_name = "/dev/sdz"
  volume_id = "${aws_ebs_volume.mongodb-master-shard01-ebs.id}"
  instance_id = "${aws_instance.mongodb-master-shard01.id}"
}
```

### Expected Behavior

I expect that the disk will be mounted to the instance.
### Actual Behavior

Error: Error running plan: 1 error(s) occurred:

* aws_volume_attachment.mongodb-master-shard01-ebs: 1 error(s) occurred:

* aws_volume_attachment.mongodb-master-shard01-ebs: Resource 'aws_instance.mongodb-master-shard01' not found for variable 'aws_instance.mongodb-master-shard01.id'
### Steps to Reproduce

terraform init
terraform plan

**Comment by joshuapmorgan** [comment]
Is that your actual Terraform configuration file? It looks as though it has invalid syntax - your interpolations that reference data sources do not include the data source name.
