### ISSUE TITLE
Provisioner Local-Exec Issue

### ISSUE THREAD

**Issue by Beczka** [hashicorp/terraform#18041]
Terraform v0.11.6

Running the below local-exec Provisioner 

```hcl
locals {
    sql_query = "${"CREATE USER xxx WITH PASSWORD='xxx'"}"
    cmd = "${local.sql_query == "" ? "" : "sqlcmd -o db.log -U ${azurerm_sql_server.server0.administrator_login} -P ${azurerm_sql_server.server0.administrator_login_password} -S ${azurerm_sql_server.server0.fully_qualified_domain_name} -d db_sample -Q \"${local.sql_query}\"" }"
}

provisioner "local-exec" {
    command = "${local.cmd}"
}
```

I am receiving this error :

 Error running command 'sqlcmd -o db.log -U dbAdministrator -P P4ssw0rd!Acme -S xxxx -d db_sample -Q "CREATE USER xxxx WITH PASSWORD=xxxx: exit status 1. Output: Sqlcmd: 'USER xxxx WITH PASSWORD='xxxx'\"': Unexpected argument. Enter '-?' for help.

When I copy this string to cmd it works seems that terraform is doing something strange with it and sqlcmd treat string after USER as additional param. Thanks for any help regarding the subject

**Comment by mildwonkey** [comment]
Hi @Beczka ,
Are you still experiencing this issue? It looks like you might need to play around with the placement of quotes around `local.sql_query`. 

(I edited your message formatting to make it easier to read.)

**Comment by mildwonkey** [comment]
I am going to close this issue, as there has not been a response. Please comment here if you would like me to re-open it!

**Comment by ashfondu** [comment]
was this ever resolved ?
