### ISSUE TITLE
init fails with example on windows 10 

### ISSUE THREAD

**Issue by davidlbyrne** [hashicorp/terraform#18046]
### Terraform Version
PS C:\Users\David\devops> terraform.exe -v
Terraform v0.11.7

```
...
```

### Terraform Configuration Files

```hcl
provider "aws" {
  access_key = "MY_ACCESS_KEY"
  secret_key = "MY SECRET_KEY"
  region     = "us-east-1"
}

resource "aws_instance" "example" {
  ami           = "ami-2757f631"
  instance_type = "t2.micro"
}
...
```

### Debug Output
https://gist.github.com/davidlbyrne/a2e4a9202226bee0f4b1685bda2a0cdd

### Expected Behavior
backend should be initialized  

### Actual Behavior
Error "At 1:1: illegal cha" 
### Steps to Reproduce

1. Download windows binary 
2. Add terraform.exe to path 
3. Create example.tf in a new folder with code provided from https://www.terraform.io/intro/getting-started/build.html
4.  Run "terraform.exe init" in the same folder as the example.tf

**Comment by jbardin** [comment]
Hi @davidlbyrne,

I suspect that you're using a text editor that didn't save the file as utf-8, or added an unnecessary utf-8 BOM at the start of the file. There should be no BOM at the start of the file, though we should probably have the `fmt` command be able to strip those out.

**Comment by davidlbyrne** [comment]
you are correct.  this can be closed.
