### ISSUE TITLE
Access Denied?

### ISSUE THREAD

**Issue by SrikanthSoma** [hashicorp/terraform#18053]
Terraform version:
=============
`0.11.7`

Terraform backend configuration location:
================================
```
terraform {
  backend "s3" {
    encrypt = true
    bucket  = "streams-test-atlantis"
    region  = "us-east-1"
    key     = "terraform.streams-test-atlantis.tfstate"
  }
}
```
Main.tf user profile:
===============

```
provider "aws" {
  region                  = "${var.region}"
  shared_credentials_file = "/Users/ssoma/.aws/credentials"
  profile                 = "ssoma-ngap-test"
}
```
My profile has AWS Administrator Access and S3 bucket don't have any bucket policy 

Terraform init running locally gives output:
===============================
```
Initializing the backend...
Error inspecting states in the "s3" backend:
    AccessDenied: Access Denied
        status code: 403, request id: 43CF10D09C304B1E, host id: 6nPFZDrM7iFd9RPfA/xe893D1l9Q70xdwKsZt6iZO+83A7/td1LMX5rGiCvOZBVCmcStpJYCN4w=
```
Expected Behaviour:
===============
terraform init should run successfully

Actual Behaviour:
==============
Access Denied

**Comment by jbardin** [comment]
Hi @SrikanthSoma,

What credentials are required for you to access the backend state? You have configured specific credentials for the provider, but none for the backend. Have you configured credentials via CLI, or are you trying to use environment variables for the backend?

**Comment by SrikanthSoma** [comment]
@jbardin My user profile has full admin access to aws which means access to that s3 backend bucket too. I configured credentials using `aws configure --profile ssoma-ngap-test` and using that profile in shared credentials isn't that be sufficient to access s3 backend? what do you mean credentials for backend?

**Comment by SrikanthSoma** [comment]
@jbardin Thank you it works
