### ISSUE TITLE
aws_main_route_table_association errors on refresh if VPC has been deleted

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#1806]
To reproduce:

- with terraform, create a VPC, a route table, and associate that route table to the VPC with `aws_main_route_table_association`
- delete the VPC through some other means, like the AWS management console
- run `terraform refresh`

You'll get an error:

```
Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* Expected to find a single main routing table for VPC: vpc-4bb6992e, but found 0
```

In this circumstance, I'd expect the state to reflect that the VPC, and thus the route table association, has been deleted. The plan should either do nothing (if we are destroying or the route table association is no longer in the configuration) or re-create the route table association (if the association is still in the configuration).

**Comment by mitchellh** [comment]
Fixed!
