### ISSUE TITLE
Ansible via local_exec does not appear to have write access to file system

### ISSUE THREAD

**Issue by egee-irl** [hashicorp/terraform#18076]
### Terraform Version
```
Terraform v0.11.7
```

### Terraform Configuration Files
```hcl
resource "null_resource" "ansible_resource" {
  provisioner "local-exec" {
    environment {
      ANSIBLE_CONFIG = "${path.module}/ansible.cfg"
    }

    working_dir = "${path.module}"
    command     = "playbook.yml"
    interpreter = ["ansible-playbook", "-vvvv"]
  }
}
```
### Expected Behavior
Ansible should be able to run a local role without file system access issues

### Actual Behavior
Ansible errors out with a Authentication or permission failure.

### Steps to Reproduce

1. Setup an Ansible playbook with a local task or role
2. Create a local_exec in Terraform that calls the Ansible playbook
3. Run `terraform init`
4. Run `terraform apply`

### Additional Context
I am able to run my Ansible playbook using the ansible-playbook cli tool without _any_ issues. As soon as I plug it into Terraform, it errors out.

I've even pointed Ansible at a wide-open folder in /tmp/ and I still see this error.

**Comment by egee-irl** [comment]
Never mind, I located the issue.

**Comment by scheung38** [comment]
Hi Brian

Could you point how to you solved it as I am trying to do the same, running Ansible in one of the AWS resources and deploy an MQTT.  I already have Terraform up and running with NLB, ASG 

And for the MQTT in my local machine from this article:

https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-the-mosquitto-mqtt-messaging-broker-on-ubuntu-16-04

so not sure how to get Ansible to deploy this MQTT inside Terraform, I guess I need to use this null resource

**Comment by egee-irl** [comment]
@scheung38 I resolved this by decoupling the deployment & provisioning steps. Instead of calling Ansible from Terraform via a null resource, our modified our CD process to run Ansible after Terraform completed. It sounds easier than it is because there was a fair amount of networking and security modifications we needed to make for this to work.

I don't recall the contents of the permission error but I believe the Terraform process had write permission restrictions and rather than trying to debug the issue, we modified our deployment process.

**Comment by scheung38** [comment]
Something like this?

```
resource "null_resource" "ansible_resource" {

  provisioner "remote-exec" {
    inline = ["echo 'Hello World'"]

    connection {
      type = "ssh"
      user = "${var.ssh_user}"
      private_key = "${file("${var.private_key_path}")}"
    }
  }

  provisioner "local-exec" {
  command = "ansible-playbook"
  }
}
```
