### ISSUE TITLE
Terraform will destroy all your managed infrastructure

### ISSUE THREAD

**Issue by coretemp** [hashicorp/terraform#18071]
This is a rather hyperbolic message:

`Terraform will destroy all your managed infrastructure, as shown above.`

Please replace it with `Terraform will destroy the infrastructure described by file <absolute path to foo.state>, as shown above.`.

Low priority.

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
