### ISSUE TITLE
Terraform does not update removed fields

### ISSUE THREAD

**Issue by Anonymous-Coward** [hashicorp/terraform#18079]
When you remove the load_balancers field from an aws autoscaling group resource, the autoscaling group's load balancers fields are not updated upon the next terraform apply. They are, however, updated, if instead of completely removing the element you just change its value to be an empty list.

### Terraform Version
aco@aco-L540:~terraform --version
Terraform v0.11.7
+ provider.aws v1.16.0
+ provider.ignition v1.0.0

### Terraform Configuration Files
Nothing relevant, IMO.

### Crash Output
(edited out what I consider not relevant.)
...
aws_autoscaling_group.abc-asg: Still modifying... (ID: abc-asg, 9m50s elapsed)
aws_autoscaling_group.abc-asg: Still modifying... (ID:abc-asg, 10m0s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* aws_autoscaling_group.abc-asg: 1 error(s) occurred:

* aws_autoscaling_group.abc-asg: Error waiting for AutoScaling Group Capacity: "abc-asg": Waiting up to 10m0s: Need exactly 6 healthy instances in ASG, have 3. Most recent activity: {
  ActivityId: "...",
  AutoScalingGroupName: "abc-asg",
  Cause: "At 2018-05-18T10:00:05Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 3 to 6.",
  Description: "Launching a new EC2 instance.  Status Reason: Cannot find Load Balancer xyz-elb. Validating load balancer configuration failed.",
  Details: "{\"Subnet ID\":\"subnet-...\",\"Availability Zone\":\"eu-central-1b\"}",
  EndTime: 2018-05-18 10:00:06 +0000 UTC,
  Progress: 100,
  StartTime: 2018-05-18 10:00:06.423 +0000 UTC,
  StatusCode: "Failed",
  StatusMessage: "Cannot find Load Balancer xyz-elb. Validating load balancer configuration failed."
}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior
The load balancers should have been removed when the modified autoscaling group configuration was encountered by terraform apply.

### Actual Behavior
The target groups were added and the load balancers were not changed.

### Steps to Reproduce
1. Create an aws autoscaling group connected to one or more classic ELBs via a .tf file.
2. Run terraform apply
3. Change the autoscaling group configuration to no longer contain the  load_balancers element, but instead add a non-empty target_group_arns element.
4. Run terraform apply again.

The load balancers are not removed, even if the target group arns are updated.

5. Now add back the load_balancers element, but with an empty list (i.e. "load_balancers = []")
6. Re-run terraform apply

The load balancers are now correctly removed from the autoscaling group.

### Additional Context
I suspect this behavior is not limited to the aws provider and the aws autoscaling group resource, and might have to do with the more generic issue of how terraform handles the update of resources. Reason for me thinking so: when I re-added the load balancers attribute in the form "load_balancers = []", and re-ran terraform apply, the load balancers were correctly removed. Which makes me suspect that terraform handles missing and empty properties differently during updates - which it should not, IMO.

### References
Could not find any.

**Comment by Anonymous-Coward** [comment]
IMO, the right way to deal with this would be to show at least a warning during terraform plan.

In any case, not touching the load balancers of the autoscaling group when they are being explicitly removed by the changes in configuration is IMO bad, since it leaves your autoscaling group in an unusable state - when aws will try to start new instances using the load configuration it will fail, because the load balancers it'd need to update are no longer existing. If a load balancer is removed completely by changes in configuration, it should at least be removed from all other resources that reference it. Otherwise terraform creates a state with resources that are unusable.

**Comment by nbering** [comment]
@Anonymous-Coward As far as I am aware, providing a warning during a plan would be a feature request. I don't think there's a way for a provider to issue warnings. I could be mistaken... I haven't looked closely at the provider API in a while.

But as for the rest of the behaviour, you'd need to file that as an issue against https://github.com/terraform-providers/terraform-provider-aws, since that is an implementation detail of the provider, and not part of Core functionality.

**Comment by Anonymous-Coward** [comment]
Created https://github.com/terraform-providers/terraform-provider-aws/issues/4596, closing this one.
