### ISSUE TITLE
resource "aws_instance"  element: element() may only be used with flat lists

### ISSUE THREAD

**Issue by simone84** [hashicorp/terraform#18074]
```
Terraform v0.11.7
+ provider.aws v1.18.0
```

```
-this is in the module:
  subnet_id = "${element(data.aws_subnet_ids.private.ids, count.index)}"

-this is in the var. file:
variable "subnet" {
  type    = "list"
  default = [""]
}

this is the main file calling the modules:
  subnet = ["${element(module.vpc.subnet, 0)}", "${element(module.vpc.subnet, 1)}"]
```

Error: Error refreshing state: 1 error(s) occurred:

* module.webserver.aws_instance.webserver: 1 error(s) occurred:

* module.webserver.aws_instance.webserver: element: element() may only be used with flat lists, this list contains elements of type list in:

${element(list("${var.subnet}"), count.index)}

Hi Everyone,

Trying to use an array with 2 subnets got from another module but keep getting this flat list error.
The only way to work around is to use data but fails at the first attempt cause the subnet maybe is not yet on the state file / temporary cache...

Can you please help me figuring out this issue?

Thanks in advance
Simone

**Comment by simone84** [comment]
this is the data added to retrieve the 2 subnet id:

data "aws_subnet_ids" "private" {
  vpc_id = "${var.vpcid}"
}

  subnet_id = "${element(data.aws_subnet_ids.private.ids, count.index)}"

**Comment by simone84** [comment]
resolved changing:

``` subnet_id = "${element(list("${var.subnet}"), count.index)}" ```

in

``` subnet_id = "${element("${var.subnet}", count.index)}" ```

**Comment by gswallow** [comment]
I did this:

  records = [ "${flatten(slice(aws_route53_zone.environment.*.name_servers, count.index, count.index + 1))}" ]
