### ISSUE TITLE
Faulty resource circular dependency detection

### ISSUE THREAD

**Issue by kozmaz87** [hashicorp/terraform#18088]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.18.0
+ provider.external v1.0.0
+ provider.null v1.0.0
+ provider.random v1.2.0
+ provider.template v1.0.0
```
### Terraform Configuration Files

```hcl
resource "null_resource" "tag_vpc" {
  depends_on = ["module.base_servers"]

  triggers {
    random_bs_number = "${uuid()}"
  }

  provisioner "local-exec" {
    command = "aws ec2 create-tags ..."
  }
}
```

And In base_servers there is a haproxy module with ASG deployment.

### Debug Output

```
* Cycle: module.location_deployment.module.base_servers.module.haproxy.random_id.unique_suffix (destroy), module.location_deployment.module.base_servers.module.haproxy.aws_launch_configuration.haproxy_lc (destroy), module.location_deployment.module.base_servers.module.haproxy.aws_autoscaling_group.haproxy_asg (destroy), module.location_deployment.null_resource.tag_vpc
```

### Expected Behavior
Replace the launch config and the ASG with the new AMI and tag the VPC once finished. ASG and LC have the create_before_destroy=true specified according to the docs: https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

### Actual Behavior
ERROR: Terraform claims there is a circular dependency, which there is not.

### Additional Context

I have a VPC tagging post-processing resource that is trying to tag the VPC with a version and set a state of deployment to be finished instead of in progress.... Now this all works well right up to the point when an update needs to be made to one of the autoscaling groups that have lifecycle{create_before_destroy=true} set. Right around then terraform seems to lose its marbles and it claims that my vpc tagging seems to be conflicting with the asg replacement, which it shouldn't and it wouldn't but Terraform seems to insist this is the case:

**Comment by jbardin** [comment]
Hi @kozmaz87,

Thanks for filing the issue. Is it possible to share a more complete example of the configuration? The snippet above doesn't really provide enough information to recreate the problem.

I have a feeling that this could be a result of #17735, but I'd like to have a concrete example to be sure.

**Comment by kozmaz87** [comment]
Yes it is possible but I will need to do it later because I need to strip down the example as much as possible to recreate the problem without divulging too much code that in the end is not mine. As soon as I will have some free time I shall get you a better example.
