### ISSUE TITLE
"terraform apply -no-color -auto-approve" status always has color in the output

### ISSUE THREAD

**Issue by joshianand** [hashicorp/terraform#18096]
### Terraform Version
Terraform v0.11.1

```
...
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior
Status should output colorless status for operation performed 

### Actual Behavior
" **^[[0;33m < ipaddress > ^[[0m              : ^[[0;32mok=3   ^[[0m ^[[0;33mchanged=2   ^[[0m unreachable=0    failed=0** "
this is the just one of the many lines with junk data for color found in the file I am trying to capture output to (You can see the color in the console as well)

### Steps to Reproduce
1) terraform plan 
2)  terraform apply -no-color -auto-approve

**Comment by joshianand** [comment]
@admin any updates for this ?

**Comment by joshianand** [comment]
cc @nsdavidson ? @smartb-pair

**Comment by mildwonkey** [comment]
Hi! This would annoy me too :) 
I will take a look at it, but just so you know I won't be able to get started before Thursday.

**Comment by mildwonkey** [comment]
Hi @joshianand,

I was unable to reproduce the issue you reported (with details of my attempt below). Perhaps you could provide some more information about the configuration you are using so I can reproduce this issue? 

This is what I tried:

**Terraform Version**
 0.11.1

**Terraform Configuration Files**

```resource "random_string" "string" {
  length = 8
}

output "o" {
  value = "${random_string.string.result}"
}
```

**Terraform Command**

`terraform apply -no-color -auto-approve > file.txt`

**Output**

```
# cat -e file.txt
random_string.string: Refreshing state... (ID: =}@d%saE)$
$
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.$
$
Outputs:$
$
o = =}@d%saE$
```

And to confirm that I see the expected output *with* color:

```
# terraform apply -auto-approve > file.txt
# cat -e file.txt
^[[0m^[[1mrandom_string.string: Refreshing state... (ID: =}@d%saE)^[[0m$
^[[0m^[[1m^[[32m$
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.^[[0m$
^[[0m^[[1m^[[32m$
Outputs:$
$
o = =}@d%saE^[[0m$
```

**Comment by joshianand** [comment]
Try something that can have change in your resources .. you can see color
at the lines where it shows ipaddress creating or destroying or when it
shows some resource was created

**Comment by mildwonkey** [comment]
@joshianand - Can you please provide an example that I can use to reproduce? I tainted the resource (so it was destroyed and recreated) and still did not see the output that you reported:

```bash
$ terraform taint random_string.string
The resource random_string.string in the module root has been marked as tainted!
$ terraform apply -no-color -auto-approve > file.txt
$ cat -e file.txt
random_string.string: Refreshing state... (ID: =}@d%saE)$
random_string.string: Destroying... (ID: =}@d%saE)$
random_string.string: Destruction complete after 0s$
random_string.string: Creating...$
  length:      "" => "8"$
  lower:       "" => "true"$
  min_lower:   "" => "0"$
  min_numeric: "" => "0"$
  min_special: "" => "0"$
  min_upper:   "" => "0"$
  number:      "" => "true"$
  result:      "" => "<computed>"$
  special:     "" => "true"$
  upper:       "" => "true"$
random_string.string: Creation complete after 0s (ID: >*!wt[dp)$
$
Apply complete! Resources: 1 added, 0 changed, 1 destroyed.$
$
Outputs:$
$
o = >*!wt[dp$
```

**Comment by joshianand** [comment]
Will provide more details once I reach work . Thanks

**Comment by joshianand** [comment]
@mildwonkey this time I am too unable to replicate it on my end.  I don't know what was causing the issue that I mentioned, sorry for the trouble. Will keep looking for this and will update this ticket if I am able to find the issue.

**Comment by joshianand** [comment]
@mildwonkey I rechecked the files, we are trying to invoke ansible commands through terrafrom files and these ansible statements with remote exec provisoner are showing with color, is there a way to handle this ?

**Comment by mildwonkey** [comment]
Ok, so the colorized output is coming out of ansible via remote exec?

I did a quick check of [the ansible documentation](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-nocolor) and there is an optional environment variable you can set to suppress the colorized output. I believe (at least in linux) you can preface the remote-exec ansible command with `ANSIBLE_NOCOLOR=true`, or export that as an environment variable via a script. 
 
Hope that helps!
