### ISSUE TITLE
terraform state pull doesn't seem to work with init that used [DIR-OR-PLAN]

### ISSUE THREAD

**Issue by kitsunde** [hashicorp/terraform#18090]
### Terraform Version

```
Terraform v0.11.7
```

### Expected Behavior

Using `terraform state pull` should be able to output the state file.

### Actual Behavior

It doesn't seem to be able to.

### Configuration File

I think this would happen with any remote backend, but This is how mine is setup:

```hcl
provider "aws" {
  region = "ap-southeast-1"
  version = "1.18"
}

terraform {
  backend "s3" {
    bucket = "mediapop-tfstate-8xfxxxo7"
    key = "terraform"
    region = "ap-southeast-1"
    dynamodb_table = "mediapop-tfstate"
  }
}
```

### Steps to Reproduce

```bash
terraform init terraform/staging
terraform plan terraform/staging
terraform state pull
```
Results in:

> Backend reinitialization required. Please run "terraform init".
Reason: Unsetting the previously set backend "s3"
>
> The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.
>
> Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.
>
> If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.

> Failed to load backend: Initialization required. Please see the error message above.

**Comment by jbardin** [comment]
Hi @kitsunde,

Terraform generally expects you to run commands from within the root of the configuration directory. Many of the cli commands weren't written with the expectation of the legacy config directory argument. We have an issue open specifically for the state command here: #17378

**Comment by VaibhavKhalane** [comment]
What are you referring to when you say configuration directory? Is it where tfbackend file is or somewhere else? I apologize if question is too silly.
