### ISSUE TITLE
`terraform show` does not work when remote state is in use

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#1810]
To reproduce:

  - Start with some configuration. Any configuration.
  - Configure remote state. For example, `terraform remote config -backend=s3 -backend-config="bucket=some_bucket" -backend-config="key=some_key"`
  - Apply the configuration.
  - Run `terraform show`.

Observed: Terraform exits with the message "No state." and status 0.

Expected: The same behavior that `terraform show` would normally have, which is to output all the resources and outputs that exist in the state file.

**Comment by hobbeswalsh** [comment]
:+1: I just ran into the same bug; I'm using the S3 backend.

**Comment by hobbeswalsh** [comment]
However, I did notice that `terraform remote pull` puts the state in the `.terraform/` directory, which is good enough for all intents and purposes.
