### ISSUE TITLE
Docs for When to use workspaces documentation conflicts with multi-environment deploy

### ISSUE THREAD

**Issue by evbo** [hashicorp/terraform#18139]
To me these two statements, taken from different parts of the docs, disagree. If I have two identical AWS accounts, one for development and one for production, should I try to implement them as separate workspaces or store their state in different backends?

From [When to use workspaces](https://github.com/hashicorp/terraform/blob/0a5059df151a1eb3253f2d73db4e42c97cf67cc4/website/docs/state/workspaces.html.md#when-to-use-multiple-workspaces) it seems they should be stored in separate backends:

> In particular, organizations commonly want to create a strong separation between multiple deployments of the same infrastructure serving different development stages (e.g. staging vs. production) or different internal teams. In this case, the backend used for each deployment often belongs to that deployment, with different credentials and access controls. Named workspaces are not a suitable isolation mechanism for this scenario.

From [Multi-environment Deploy](https://www.terraform.io/guides/running-terraform-in-automation.html#multi-environment-deployment) it seems I should use the same backend (even when "impossible"):

> Where possible, it's recommended to use a single backend configuration for all environments and use the terraform workspace command to switch between workspaces... ...In some more complex situations it is impossible to share the same backend configuration across environments. For example, the environments may exist in entirely separate accounts within the target service, and thus need to use different credentials or endpoints for the backend itself. In such situations, backend configuration settings can be overridden via the -backend-config option to terraform init.

Personally, I'm in favor of keeping separate accounts isolated and only using workspaces when prototyping a change (which could happen during development or with a production hotfix). So, I like your analogy to VCS, where a workspace is like a "branch" and the default workspace is "master" or "trunk".

Is my thinking on target? There's a SO post about this same question: https://stackoverflow.com/questions/45717688/ideal-terraform-workspace-project-structure/45729198#comment88194341_45729198

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. The documentation has been updated quite a bit since this was opened.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
