### ISSUE TITLE
State file doesn't recognize resources

### ISSUE THREAD

**Issue by pixelicous** [hashicorp/terraform#18148]
Hi,

I have a weird issue that i encountered in the past, but now i encounter it for production resources and i am a bit intimidated of running terraform apply.

I prepared a nice deployment that constructs quite a few resources in azure, after a lot of trial and erroring and making sure i get the result i am after, i went ahead to clear the state file, deleted all resources and launched terraform apply.

Resources were created and lived happily, during the next 2 months we had a tweak here and there to configuration, some of which cannot be even set with terraform.

A few days ago i went ahead and tried to add a resource to terraform and i ran a "plan" execution, it seems like the state file is completely out of sync with what azure contains. it shows like none of the resources are created and it tries to recreate everything.

To still use terraform i locked all resources, and ran apply, it did create the new resource but crashed on all the rest.

I was wondering why this has happened, how come the state file is so out of sync that it tries to create everything from scratch, and is there any option for terraform to understand which resources are created (by their name for example) and then not create them, but sync up with the fact that they are already created????

**Comment by jbardin** [comment]
Hi @pixelicous,

Sorry you're having trouble with this, but without an example it's hard to diagnose what the problem actually was. The plan output should indicate which values were forcing a resources to be recreated. 

Something you mention is changing resources, "some of which cannot be even set with terraform". Under normal operation, the only way the state can get out of sync is when resources change outside of terraform's control, so modifying managed resources directly is usually the cause if this situation.  

If a resource doesn't match terraform's configuration, terraform is going to attempt to revert the changes. If there are dependent values that require resource replacement, then you have the possibility for a chain of events that requires replacing multiple resource.

**Comment by pixelicous** [comment]
@jbardin hey, The reason why I didn't provide any HCL is because it is just generic, i am creating a resource group, keyvaults, app services, plans etc.. it isn't the object which is the problem but what action took place that completely threw the mapping between the actual resources and the state file that i do not understand. Some of those resources were not handled outside of terraform, yet terraform tries to create from scratch all of the resources, not modify or recreate due to some property change, alll the resource lines are green with a "+" sign.

I tried using terraform import and I managed to gain back some of those resources into the state file, i am having difficulties with some of the resources though but i think i just need to tweak my hcl a bit to match this sort of manual import

**Comment by jbardin** [comment]
Hi @pixelicous,

It seems like you have things under control now. There really isn't any particular reason for terraform to try and create resources that exist, other than the state was lost or corrupted. Without a way to reproduce the issue, I couldn't really hazard a guess as to what happened. If you do encounter this again, and have some order of operations that caused it, feel free to open a new issue with the information.
