### ISSUE TITLE
data azurerm_subnet failure

### ISSUE THREAD

**Issue by petit-lu** [hashicorp/terraform#18144]
### Terraform Version

```
terraform 0.11.7
```

### Terraform Configuration Files

data.tf
```hcl
data "azurerm_subnet" "mysubnet" {
  name                 = "subnet001"
  virtual_network_name = "VNET_PROD"
  resource_group_name  = "rg_net"
}
```
main.tf
```hcl
output "subnet_id" {
   value = "${data.azurerm_subnet.mysubnet.id}"
}
```

### Crash Output

**Error:** output 'subnet_id': unknown resource 'data.azurerm_subnet.mysubnet' referenced in variable data.azurerm_subnet.mysubnet.id

### Expected Behavior

Normally, we get ID of subnet in DATA.
### Actual Behavior

We get an error from module output.

### Steps to Reproduce

1. `terraform init`

### Additional Context

I tried to check with terraform console.

```
terraform console
azurerm_subnet.mysubnet.id 
//subscriptions/***...***/subnets/subnet001
```

We get correctly the information about id of this subnet.
But if I called this variable in my TF files ` "${data.azurerm_subnet.mysubnet.id}}"` is an unknow ressource.

**Comment by jbardin** [comment]
Hi @petit-lu,

The error mentions `data.azurerm_subnet.yoda_ode_lb_prd`, but that isn't present in the sample you provider here. You also have a typo in the `output` value, and you need to remove the extra closing brace: "${data.azurerm_subnet.mysubnet.id}".

Does that fix the issue?

**Comment by petit-lu** [comment]
Hi @jbardin,

Sorry I did mistake from my copy / paste.
Not fix the issue.

**Comment by jbardin** [comment]
Hi @petit-lu,

That output works correctly as you shown, so we're going to need a more complete example to work with here. The error means that `data.azurerm_subnet.mysubnet` is not found in the same module, so something is happening when loading the configuration.

**Comment by petit-lu** [comment]
Thanks. @jbardin
