### ISSUE TITLE
When will Terraform import be able to generate configurations?

### ISSUE THREAD

**Issue by shenshengkafei** [hashicorp/terraform#18140]
Hi There,

I know that the current implementation of Terraform import can only import resources into the state. Do you have any plan when you will support generating configurations as well?

Thanks!

**Comment by jbardin** [comment]
Hi @shenshengkafei,

Thanks for your interest. While we have plans to help create basic configuration from the importing of resources, there is no specific timeline for this feature. We will be better positioned to evaluate the possibilities once we have the new configuration language and libraries full integrated in terraform.
