### ISSUE TITLE
Bluescreen when low memory in Windows 10 Subsystem for Linux

### ISSUE THREAD

**Issue by mzhaase** [hashicorp/terraform#18142]
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.19.0
+ provider.template v1.0.0

### Expected Behavior
Terraform should not cause the machine to crash with a bluescreen.

### Actual Behavior
Terraform crashes the machine with a bluescreen when memory is low. Crash happens during refresh state.

### Steps to Reproduce
- Use terraform in Windows Subsystem for Linux.
- Make sure majority of RAM is already used
- Run terraform apply on a sizeable project

### Additional Context
Windows 10 1703 15063.483
Terraform running in linux subsystem: Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

Thinkpad T470, i5-6200U, 8G of RAM

This machine has never crashed outside of terraform, but 8 times so far when running terraform apply.

Looking at the minidump files, crashes happen at address:

ntoskrnl.exe+16c4c0

caused by either:
- tcpip.sys+139a4
- LXCORE.SYS+aa280

**Comment by jbardin** [comment]
Hi @mzhaase,

Sorry you're having an issue with this. WSL is not a supported target for Terraform, and in fact WSL has a number of incompatibilities that cause problems with the Go runtime and std library.

Until the upstream issues can be sorted out, we can't recommend running terraform with Windows Subsystem for Linux.
