### ISSUE TITLE
AccessDenied for cross-account access to module source in S3

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform#18152]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
# code to create the module bucket

resource "aws_s3_bucket" "release" {
  bucket = "${var.aws_account_number}-${var.bucket_name_release}"
  acl    = "${var.acl}"

  logging {
    target_bucket = "${aws_s3_bucket.log.id}"
    target_prefix = "release-log/"
  }

  versioning {
    enabled    = "${var.versioning_enabled}"
    mfa_delete = "${var.versioning_mfa_delete}"
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm     = "aws:kms"
        kms_master_key_id = "${aws_kms_key.s3_key_release.arn}"
      }
    }
  }

  tags {
    Name     = "${var.bucket_name_release}-s3"
    Solution = "${var.solution}"
    Use      = "release"
    Role     = "${var.role}"
    Client   = "${var.client}"
  }
}

data "aws_iam_policy_document" "policy_document_release" {
  policy_id = "cross-account-bucket-policy"

  statement {
    principals {
      identifiers = "${formatlist("arn:aws:iam::%s:root", var.account_ids_to_access)}"
      type        = "AWS"
    }

    actions = ["s3:*"]

    resources = [
      "arn:aws:s3:::${var.aws_account_number}-${var.bucket_name_release}/*",
      "arn:aws:s3:::${var.aws_account_number}-${var.bucket_name_release}",
    ]
  }
}

resource "aws_s3_bucket_policy" "release" {
  bucket = "${aws_s3_bucket.release.id}"
  policy = "${data.aws_iam_policy_document.policy_document_release.json}"
}

# code to access the module resource

module "ecs" {
  source = "xxxxxxxxxxxx-terraform-modules.s3.amazonaws.com/aws/ecs/0.1.0/ecs.zip"
   ...
}
```

### Expected Behavior

On terraform init, we should be able to read from the module source.
ie
  Getting source "xxxxxxxxxxxx-terraform-modules.s3.amazonaws.com/aws/ecs/0.1.0/ecs.zip"
2018/05/30 11:31:45 [DEBUG] found "s3::https://s3.amazonaws.com/xxxxxxxxxxxx-terraform-modules/aws/ecs/0.1.0/ecs.zip" in ".terraform/modules/e830d16202a793a86d33fed46cf6016a": true

### Actual Behavior

  Getting source "xxxxxxxxxxxx-terraform-modules.s3.amazonaws.com/aws/ecs/0.1.0/ecs.zip"
2018/05/31 08:51:42 [DEBUG] plugin: waiting for all plugin processes to complete...
Error downloading modules: Error loading modules: AccessDenied: Access Denied
	status code: 403

### Steps to Reproduce

terraform init
### Additional Context

It works in the account that owns the bucket, just fine, but if I add an account to the policy, the terraform init does not work for the new account.
However, if I manually run "aws s3api --list-objects --bucket xxxxxxxxxxxx-terraform-modules" from the new account I can see the objects in the bucket, so I know that the policy must be correct, it just is not working for terraform init.

**Comment by jbardin** [comment]
Hi @megan07,

Thanks for opening the issue; this does seem like it should work automatically. The code that fetches modules expects any credentials required for aws to be available in the environment. How are you providing the credentials to the `aws` cli?

**Comment by megan07** [comment]
I am setting the AWS credentials as environment variables

**Comment by megan07** [comment]
Another curious thing that I'm seeing with this is that, when I'm in the other account and trying to access a module that doesn't exist, I get the error "Error downloading modules: Error loading modules: NoSuchKey: The specified key does not exist.
    status code: 404"

It seems to me that if access was truly denied, as it says when the module does exist, I should still be getting an Access Denied error in the case that the module doesn't exist, I shouldn't be getting a NoSuchKey error if I don't have access.

So I tried that as well, to be sure, I tried to access a non-existing module in a bucket that I know I don't have access to, and sure enough, I got that Access Denied error as I was expecting.

Not sure if that helps, but as I was able to dig into it more, I noticed that and thought it could provide more direction.

Thanks!

**Comment by megan07** [comment]
So a co-worker of mine was able to figure this out.  We had been using KMS, but when he turned off encryption, it worked! So he tried AES256 and it still worked! So the issue was with KMS encryption on the bucket, the other accounts did not have access to the KMS key.
