### ISSUE TITLE
UptimeRobot provider

### ISSUE THREAD

**Issue by louy** [hashicorp/terraform#18167]
Hi all,

Thanks for all the great work!

I've just created a provider for uptimerobot (it's fairly simple) and would love to make it a community provider.

You can see it here: https://github.com/louy/terraform-provider-uptimerobot

I'm aware that I need to have a few acceptance tests and some documentation before it's ready to go, but I also wanted to make sure I'm not missing anything. [The official guide](https://www.terraform.io/docs/extend/community/contributing.html#new-provider) doesn't explain in detail what the process is for releasing a new provider so I appreciate some help. **What do I need to do to make this a community provider?**

Also please note that this is my first golang code ever, so comments/tips are more than welcome

Thanks again!

**Comment by louy** [comment]
Update: acceptance tests and docs are both there now

**Comment by colmonty** [comment]
any update on this, Terraform Team? We're keen to use this ASAP.

**Comment by mildwonkey** [comment]
Hi @louy  - I'm not sure if you have seen this yet, but there have been some great updates to the [Terraform Provider Development Program](https://www.terraform.io/guides/terraform-provider-development-program.html) documentation, including information on how to engage.

**Comment by mildwonkey** [comment]
And @colmonty, you can use a third-party provider by dropping the binary in a specific [directory](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins).

**Comment by walkafwalka** [comment]
I, too, would like to see this implemented.

**Comment by pkolyvas** [comment]
Hi folks! As Terraform Open Source is now separate from Providers, I'm working on cleaning up our issue list by closing down open issues that no longer pertain directly to this repository.

I'm glad to hear this provider is a thing. Regarding official provider status, if the [documentation here](https://www.terraform.io/guides/terraform-provider-development-program.html) isn't proving helpful, please reach out to me (contact info is on my GitHub profile page) and I'll follow up.

However you may also want to simply go the [community route](https://www.terraform.io/docs/providers/type/community-index.html). You can find the form here: https://docs.google.com/forms/d/e/1FAIpQLSeenG02tGEmz7pntIqMKlp5kY53f8AV5u88wJ_H1pJc2CmvKA/viewform#responses
