### ISSUE TITLE
Resource repeated multiple times though in Different VPCs

### ISSUE THREAD

**Issue by Binternet** [hashicorp/terraform#18178]
### Terraform Version

```
0.11.6
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

```
Error: aws_security_group.ElasticMapReduce-ServiceAccess: resource repeated multiple times

Error: aws_security_group.ElasticMapReduce-Master-Private: resource repeated multiple times

Error: aws_security_group.ElasticMapReduce-Slave-Private: resource repeated multiple times
```

### Expected Behavior

It should create security groups, with the same name but in different VPCs.

### Actual Behavior

A `resource repeated multiple times` error was thrown

### Steps to Reproduce

Create a security group with the same name but different VPC

**Comment by jbardin** [comment]
Hi @Binternet,

The `resource repeated multiple times` error is from the validation of your Terraform configuration, not from aws.  The error  is caused by having  a resource name duplicated multiple times, which isn't valid as they need to be unique identifiers.

The name (or identifier) of the resource is not related at all to the `name` field in the resource configuration. You can create multiple versions of the same resource using the `count` attribute, parameterizing them in modules, or simply by creating multiple resource blocks with different identifiers.

**Comment by Binternet** [comment]
Hey @jbardin 

I am aware of that it is an error from Terraform and not AWS, but I am pointing out about a real-usage issue:

I have several security groups, [with the same name](https://i.imgur.com/4ZhHHe5.png) **yet in different VPCs** and I cannot create them via Terraform because of this validation.

**Comment by jbardin** [comment]
Hi @Binternet,

Do you have an example of the configuration you're using? The name of the resource in Terraform has no bearing on the name of the instance in aws, so it's possible to create multiple resources with the same `name` using different identifiers in Terraform.

**Comment by Binternet** [comment]
Yup:

```
resource "aws_security_group" "ElasticMapReduce-slave" {
   name        = "ElasticMapReduce-slave"
   description = ""
   vpc_id      = "${var.vpc_production}"

// ingress / egress

}

resource "aws_security_group" "ElasticMapReduce-slave" {
    name        = "ElasticMapReduce-slave"
    description = ""
    vpc_id      = "${var.vpc_staging}"

    // ingress / egress
}
```

**Comment by jbardin** [comment]
Yes, you cannot have 2 `ElasticMapReduce-slave` resources. That is an invalid configuration, and you need to rename one of those. As mentioned earlier, the name in terraform has no bearing on the `name` in aws. 

    resource "aws_security_group" "ElasticMapReduce-slave_prod" {
    ...
    resource "aws_security_group" "ElasticMapReduce-slave_stage" {
    ..

**Comment by Binternet** [comment]
Yeah I though so, but that's -1 for terraform VS real AWS name selection ;-/

**Comment by jbardin** [comment]
Sorry, I'm not quite sure I understand, but it's also quite common to have these resource parameterized in modules as configurations grow in complexity, in which case there would only need to be a single `aws_security_group.ElasticMapReduce-slave` definition. 


```
resource "aws_security_group" "ElasticMapReduce-slave" {
  name        = "ElasticMapReduce-slave"
  description = ""
  vpc_id      = "${var.environment}"
  ...
}
```

**Comment by Binternet** [comment]
Well, i've used [terraforming](https://github.com/dtan4/terraforming) to export my current resources, and in 1 environment - say production - i have several VPCs with security groups that has the same name, i'm thinking about a way to parameterise it...
