### ISSUE TITLE
Improve docs explaining how to destroy a specific element when resource is using count

### ISSUE THREAD

**Issue by Lasering** [hashicorp/terraform#18184]
### Terraform Configuration Files
```hcl
resource "null_resource" "example" {
  count = 5
}
```
I want to destroy the third resource:
`terraform destroy target=null_resource.example[3]`

The [documentation](https://www.terraform.io/docs/commands/destroy.html) should explain how to destroy a specific instance. Only after:

1. Trying to do `terraform destroy target=null_resource.example.3`
2. Getting the error: `Error: Error asking for user input: Unexpected value for InstanceType field: "3"`
3. Googling it, landing on the source code of [resource_address](https://github.com/hashicorp/terraform/blob/master/terraform/resource_address.go#L431)

Could I find the proper syntax of brackets.

**Comment by Prernakaler** [comment]
terraform destroy -target null_resource.example[3] should work
