### ISSUE TITLE
terraform is giving provider registration error for azure

### ISSUE THREAD

**Issue by ayyappa1** [hashicorp/terraform#18180]
Hi Friends,
I am using terraform to create vpc in Azure environment.
service principle credentials is declared in the Provider Block but getting below error during terraform plan .
The refreshed state will be used to calculate this plan, but will not be persisted to local or remote state storage.
------------------------------------------------------------------------
Error: Error running plan: 1 error(s) occurred:
* provider.azurerm: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '96ea2142-599c-4e37-b80f-b569cd59c39b' with object id '96ea2142-599c-4e37-b80f-b569cd59c39b' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/df28ef54-071d-4d9c-886b-045bdffda9aa'."
ubuntu@ip-172-31-26-94:~/terraform/AZURE/vpc1$

I have carefully defined sub_id,client_id,client_secreat_id and tenet id.
**terraform file:**
provider "azurerm" {
   subscription_id = "************************"
   client_id       = "************************"
   client_secret   = "************************"
   tenant_id       = "************************"
 }
resource "azurerm_resource_group" "test" {
  name     = "acceptanceTestResourceGroup1"
  location = "South India"
}
resource "azurerm_network_security_group" "test" {
  name                = "acceptanceTestSecurityGroup1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}
resource "azurerm_virtual_network" "test" {
  name                = "virtualNetwork1"
  resource_group_name = "${azurerm_resource_group.test.name}"
  address_space       = ["10.0.0.0/16"]
  location            = "South India"
  dns_servers         = ["10.0.0.4", "10.0.0.5"]
  subnet {
    name           = "subnet1"
    address_prefix = "10.0.1.0/24"
  }
  subnet {
    name           = "subnet2"
    address_prefix = "10.0.2.0/24"
  }
  subnet {
    name           = "subnet3"
    address_prefix = "10.0.3.0/24"
    security_group = "${azurerm_network_security_group.test.id}"
  }

  tags {
    environment = "Production"
  }
}
Please let me know what would be the issue in this case.

Thanks,
Ayyappa

**Comment by nbering** [comment]
This usually means the account or service principle you are using doesn't have sufficient privileges.

**Comment by nbering** [comment]
If you already have all the providers registered on your account (for example, because you've been using the account from the portal or CLI already), the account has sufficient privileges to manage resources, and you don't want to give it permissions to manage the subscription to enable providers, you may disable provider registration (which is more or less a convenience).

https://www.terraform.io/docs/providers/azurerm/index.html#skip_provider_registration

**Comment by ayyappa1** [comment]
Thanks team ..issue has been closed.

**Comment by celaldogan** [comment]
How you solved the issue?

**Comment by celaldogan** [comment]
> Thanks team ..issue has been closed.

How did you solve the issue?
