### ISSUE TITLE
Feature request: function to lookup a DNS name and return an IP address

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform#18191]
I would love a new function to lookup a DNS name and return an IP address.

One place I can think of where this would be useful is when using the [`aws_route53_delegation_set` resource](https://www.terraform.io/docs/providers/aws/r/route53_delegation_set.html) and then making your own private label nameservers from the records that are assigned to you:

```hcl
# Incomplete + invalid config - demonstration only

resource "aws_route53_delegation_set" "main" {
  reference_name = "Main"
}

resource "aws_route53_zone" "foo" {
  name              = "example.com"
  delegation_set_id = "${aws_route53_delegation_set.main.id}"
}

resource "aws_route53_record" "nameservers" {
  count   = 4
  zone_id = "${aws_route53_zone.foo.id}"
  name    = "ns${count.index + 1}"
  type    = "A"
  ttl     = "86400"
  records = ["${nametoip(aws_route53_zone.foo.name_servers[count.index])}"]
}
```

**Comment by tdmalone** [comment]
I'm currently getting around this by using `lookup()` and providing my own map:

```variable "ns_ips" {
  "ns-513.awsdns-00.net"    = "205.251.194.1"
  "ns-1430.awsdns-50.org"   = "205.251.197.150"
  "ns-438.awsdns-54.com"    = "205.251.193.182"
  "ns-1828.awsdns-36.co.uk" = "205.251.199.36"
}```

But of course this won't be any use for additional delegation sets unless I slowly build this map up :P

**Comment by tdmalone** [comment]
I'm currently getting around this by using `lookup()` and providing my own map:

```hcl
variable "ns_ips" {
  default = {
    "ns-513.awsdns-00.net"    = "205.251.194.1"
    "ns-1430.awsdns-50.org"   = "205.251.197.150"
    "ns-438.awsdns-54.com"    = "205.251.193.182"
    "ns-1828.awsdns-36.co.uk" = "205.251.199.36"
  }
}
```

But of course this won't be any use for additional delegation sets unless I slowly build this map up :P

**Comment by tdmalone** [comment]
Thanks @apparentlymart, I didn't realise this provider existed! It should do exactly what I'm after.

**Comment by sidewinder12s** [comment]
@apparentlymart I think a lookup function to just perform a `host` lookup would still be pretty useful, even without the graph. I've got a use case where I want to provide a list of hostnames to a module, but the module actually needs to consume IP addresses. I can't think of a way to just take in hostnames and convert to IPs using a resource or datasource, unless the datasource could take a list to convert?

I could open another issue with the use case laid out if that requirement makes sense to you?

**Comment by lpgc** [comment]
+1 the only other way to do this is with a local or remote provisioner and then it is O.S dependent... could really do with a host_to_ip() function to abstract this... save messing around with data_sources that might not support the general purpose use case... given how much n/w config occurs when using TF having the ability to lookup hostnames to obtain their IP seems like a very valuable utility beyond the specific example use case above
