### ISSUE TITLE
File encoding and line separators

### ISSUE THREAD

**Issue by oscr** [hashicorp/terraform#18205]
Hi team,

I've noticed that the source code in Terraform and at least one of it's providers uses both ASCII and UTF-8 encoding. Example using `file` on Ubuntu   

    $ file terraform/*
    (...)
    terraform/semantics_test.go:                      ASCII text
    terraform/state_add.go:                           UTF-8 Unicode text

My impression is that this mix isn't compatible with the Golang language specification which states:

> Source code is Unicode text encoded in UTF-8

(source: https://golang.org/ref/spec#Source_code_representation )

Another thing that I noticed is that at least one provider mixes files with LF and CRLF line separators. It might be a good idea to add a `.gitattributes` file to enforce a standard? I would be happy to add this should this be of interest.

Regards Oscar

**Comment by apparentlymart** [comment]
Hi @oscr!

ASCII is a subset of UTF-8, so while I'm not familiar with what heuristics `file` uses to detect character encoding I'd guess that "ASCII text" here means "only contains bytes <128", which is also true for a UTF-8 file that only includes Unicode codepoints <128.

In other words, any valid ASCII text file is by definition also a valid UTF-8 file. The `file` command has to choose one to report, and so it seems to arbitrarily choose "ASCII text".

**Comment by oscr** [comment]
Hi @apparentlymart,

I actually didn't know that ASCII was a subset of UTF-8. Then this isn't an issue at all. TIL.
