### ISSUE TITLE
format plan output to be more readable

### ISSUE THREAD

**Issue by darshanime** [hashicorp/terraform#18214]
There is a project (https://github.com/coinbase/terraform-landscape) dedicated just to better format terraform's plan output.
Can some ideas be incorporated in terraform proper?

#### Before
<img src="https://raw.githubusercontent.com/coinbase/terraform-landscape/master/doc/before.png" width="65%" alt="Original Terraform plan output" />

### After
<img src="https://raw.githubusercontent.com/coinbase/terraform-landscape/master/doc/after.png" width="65%" alt="Improved Terraform plan output" />

**Comment by jbardin** [comment]
Hi @darshanime,

Thanks for the pointer to the other project. We have plans to create a better plan output, and are tracking the issue here: #15180
