### ISSUE TITLE
provider/aws: Inaccurate plan when changing route53_record

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1823]
Creating this as a separate issue from closed https://github.com/hashicorp/terraform/issues/1122 which was trying to address too many issues at once.

#### Original
```
resource "aws_route53_record" "sample" {
  zone_id = "${aws_route53_zone.primary.id}"
  name = "sample"
  type = "A"
  ttl = "30"
  records = ["127.0.0.1", "8.8.8.8"]
}
```
```
$ terraform apply # OK
```

#### Modified
```
resource "aws_route53_record" "sample" {
  zone_id = "${aws_route53_zone.primary.id}"
  name = "sample"
  type = "A"
  ttl = "30"
  records = ["127.0.0.1", "7.7.7.7"]
}
```

`terraform plan` (no mention about removing `8.8.8.8`):
```
~ aws_route53_record.sample
    records.209503049: "" => "7.7.7.7"
    records.3619153832: "127.0.0.1" => "127.0.0.1"
```

`terraform apply` (no mention about removing `8.8.8.8`):
```
aws_route53_zone.primary: Refreshing state... (ID: ***)
aws_route53_record.sample: Refreshing state... (ID: ***_sample_A)
aws_route53_record.sample: Modifying...
  records.209503049:  "" => "7.7.7.7"
  records.3619153832: "127.0.0.1" => "127.0.0.1"
aws_route53_record.sample: Modifications complete
```

**Comment by catsby** [comment]
Thanks for breaking this out @radeksimko . I'm not sure if it's a core bug, or specific to how we do Route 53 Record records :/ Maybe making them a `TypeList` instead would be more clear here? cc @phinze

**Comment by mitchellh** [comment]
This is probably just helper/schema losing the old value... this would be a core bug.

**Comment by mitchellh** [comment]
We'll take a look.

**Comment by mitchellh** [comment]
Reproduced, now trying to repro this using a helper/schema test... should be able to since I have all the state here.
