### ISSUE TITLE
Simple Provisioner Disabling Mechanism

### ISSUE THREAD

**Issue by vahnj** [hashicorp/terraform#18246]
It'd be pretty great if there was a way to disable particular provisioners in a resource - for instance, say you're installing alerting on a host, but if you have a separate workspace you don't want alerts to trigger on, being able to disable the provisioners with a flag setting instead of needing to interpolate the provisioner instructions to do nothing would be very handy for readability.

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. While provisioners, as a whole, aren’t a top priority for the team, when some time is available to focus on them we’re going to use that attention to tackle some long-standing defects. 

We are also thinking about how to evolve provisioning for many of our community’s use cases but have yet to take a firm decision on the direction that work will take. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
