### ISSUE TITLE
Feature request: centralise provider plugins

### ISSUE THREAD

**Issue by m4rkw** [hashicorp/terraform#18255]
the terraform and consul provider binaries together are around 100MB:

````
 87M	terraform-provider-aws_v1.22.0_x4
 13M	terraform-provider-consul_v1.0.0_x4
````

Storing 100MB per workspace when these files are generally the same version most of the time seems a bit wasteful. Could these be centralised, perhaps in ~/.terraform/?

**Comment by jbardin** [comment]
Hi @m4rkw,

We have multiple ways of handling this in Terraform. 
 - You can add plugins manually to the global `.terraform.d` [third part plugins directory](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins) to hold specific plugin binaries. 
 - You can use the [plugin cache](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache) as a global repository for plugins downloaded via the `init` command.
 - You can use the [`-plugin-dir` `init`](https://www.terraform.io/docs/commands/init.html#plugin-installation) flag to override the discovery mechanism and restrict terraform to known plugin binaries.
