### ISSUE TITLE
invalid or unknown key: create_before_destroy

### ISSUE THREAD

**Issue by lyrixx** [hashicorp/terraform#1828]
```
resource "aws_instance" "sl_prod_elasticsearch" {
    create_before_destroy = true
    ami = "ami-d52f47a2"
....
```

=> 

```
terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_instance.sl_prod_elasticsearch: : invalid or unknown key: create_before_destroy
```

I'm using: `Terraform v0.5.0-dev (cebcee5c638630c4792eb3ed1bccf50b560ecec6)`

BTW, the current master 47a45a6 is broken ; I can not fetch dependencies, not build it...

**Comment by mitchellh** [comment]
It has to go in a `lifecycle` block, see the syntax here: https://terraform.io/docs/configuration/resources.html

**Comment by lyrixx** [comment]
Sorry for the noise.

It should be used like that:

```
    lifecycle {
        create_before_destroy = true
    }
```
