### ISSUE TITLE
AzureRM Backend: support for snapshotting before changes are made

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/terraform#18284]
Moving this over from https://github.com/terraform-providers/terraform-provider-azurerm/issues/1098

### Terraform Version

v0.10.x +

### Additional Context
Thinking about this a little:

- I don't think there's a need for an explicit `versioning` flag, or at least it should be defaulted to `true`.
- support for Snapshotting is available in both [the current Storage SDK](https://github.com/Azure/azure-sdk-for-go/blob/v17.3.1/storage/blob.go#L281) and [the new Storage SDK](https://github.com/Azure/azure-storage-blob-go/blob/master/2017-07-29/azblob/url_blob.go) - however we're holding off migrating to the new Storage SDK (at least in the AzureRM Provider) until it's stabilised.

### References

- https://github.com/terraform-providers/terraform-provider-azurerm/issues/1098

**Comment by pmarques** [comment]
Hi @tombuildsstuff I'm implemented a simple version of snapshotting. Added an option to enable/disable auto snapshots (**enable** by default)

**Comment by pmarques** [comment]
@tombuildsstuff any updates / feedback on this?

**Comment by mjdavies** [comment]
Very interested in this!!

**Comment by arichiardi** [comment]
Interested in this as well!

**Comment by cyrilen** [comment]
very interested in that

**Comment by mildwonkey** [comment]
Hi all, thanks for your interest!

Please react to the original issue comment with 👍, which we [can and do report on](https://github.com/hashicorp/terraform/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) during prioritization. It's more effective than individual comments, which merely generate noise for people following the issue but do not help us prioritize. Thanks!

**Comment by tombuildsstuff** [comment]
@pmarques we're doing some work in the AzureRM Backend in the near future to support additional auth methods (and try to fix some of the open issues/enhancements) - as such I believe we'll be taking a look at this as a part of that process - but I'm unable to give a timeframe at this point, unfortunately.

Thanks!

**Comment by rohrerb** [comment]
+1 on this @tombuildsstuff 

cc @amcguign

**Comment by rdtechie** [comment]
What's the status on this issue? Any progress?
