### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by tonygyerr** [hashicorp/terraform#18294]
### Terraform Version

Terraform v0.11.7
+ provider.aws v1.17.0
+ provider.random v0.1.0
+ provider.template v0.1.1
```
...
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

[crash.log](https://github.com/hashicorp/terraform/files/2120317/crash.log)

### Steps to Reproduce

terraform get
terraform plan

**Comment by apparentlymart** [comment]
Hi @tonygyerr! Sorry for this crash.

I think this is the same issue as #18240, though possibly on a different example of assigning a list where a single string is expected. I'm going to close this one just to consolidate the discussion over there.
