### ISSUE TITLE
Dynamodb use server_side_encryption

### ISSUE THREAD

**Issue by ctippur** [hashicorp/terraform#18310]
### Terraform Version

```
0.11.7
```

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "user-table" {
  name           = "Testing"
  read_capacity  = 5
  write_capacity = 5
  hash_key       = "UserId"

  server_side_encryption {
    enabled = true
  }

  attribute {
    name = "UserId"
    type = "S"
  }
}
```

### Debug Output

Error: module.ddb.aws_dynamodb_table.user-table: : invalid or unknown key: server_side_encryption

### Expected Behavior

Should have gone ahead and created the table.
### Actual Behavior

got the error mentioned above
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
### References

https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#server_side_encryption

**Comment by saravanan30erd** [comment]
test
