### ISSUE TITLE
Module interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by bluehawk27** [hashicorp/terraform#18336]
### Terraform Version
```
Terraform v0.11.7
provider.aws v1.24.0
```
### Crash Output
https://gist.github.com/bluehawk27/131fd62baa401d31a744131bc0959601

### Actual Behavior
terraform apply crashes with aws_iam_role_policy_attachment.default: unexpected EOF

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by bluehawk27** [comment]
this probably just needs a nil check  `if len(rawVpcConfig) == 0 || rawVpcConfig == nil {` here. https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codebuild_project.go#L492

**Comment by apparentlymart** [comment]
Ahh yes @bluehawk27, you're right... I misread that stack trace on the first pass and thought it was a validation error.

I'm going to have our bot move this issue into the AWS provider repository, since that's where this would be fixed. Thanks for pointing that out!
