### ISSUE TITLE
True and False portions of conditionals always evaluated

### ISSUE THREAD

**Issue by rrati** [hashicorp/terraform#18340]
### Terraform Version
Terraform v0.11.5
```
...
```

### Terraform Configuration Files
locals {
  version_split = "${split(",", var.os_version)}"
  minor = "${length(local.version_split) >= 2 ? "${local.version_split[1]}" : "0"}"
}

variable os_version{
  type = "string"
  default = ""
}
```hcl
...
```

### Debug Output
https://gist.github.com/rrati/95ba6a157158a157b16982dca20cec9e

### Expected Behavior
Should have evaluated the conditional portion and then only evaluated either the true or false portion based upon the result.

### Actual Behavior
Both true and false portions of the conditional are evaluated all the time.

### Steps to Reproduce
1. Copy provided config to a .tf file
2. Run terraform apply

**Comment by mildwonkey** [comment]
Hi @rrati - 
I'm sorry you've come across this bug. It is a known issue, #15605 
I'm going to close this ticket so we can consolidate the conversation in #15605

Thank you for your report!
