### ISSUE TITLE
Feature request: SQS trigger lambda function

### ISSUE THREAD

**Issue by asimtech12** [hashicorp/terraform#18354]
AWS have recently released feature where a lambda function can be triggered by SQS message, 
We are using terraform in our project for IaC and this feature would simplify our solution.
manually we can use SQS message to trigger lambda using AWS console ::

aws console-->lambda function-->(left pane add trigger)SQS --> select your SQS queue(to listen for updates on)-->add-->save

Thanks
Asim

### Terraform Version

```
terraform version = 1.16.0
```

### References

AWS reference document 
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-lambda-function-trigger.html

https://aws.amazon.com/blogs/aws/aws-lambda-adds-amazon-simple-queue-service-to-supported-event-sources/

**Comment by drkreddy** [comment]
This is really an interesting release from AWS, for which we were waiting for long time. We are using Terraform in our project. We are in need of this feature to configure SQS as trigger point for Lambda.

Thanks
Ravindra
