### ISSUE TITLE
Azurerm VNET Address Space: "should be type string, got list" and vice-versa.

### ISSUE THREAD

**Issue by cofonseca** [hashicorp/terraform#18361]
Hello everyone. I am trying to create a module that will spin up a virtual network in Azure, as well as a couple of subnets and other related resources. I'm passing in the name, resource_group_name, location, and address_space as variables. Terraform fails to create the virtual network, stating that the address_space is type list, but it should be a string. If I make it a string instead of a list, I get the reverse error message, saying it's a string, but it should be a list.

I have a single address space formatted exactly as shown in the docs. 

### Terraform Version

```
Terraform v0.11.7
+ provider.azurerm v1.8.0
```

### Terraform Configuration Files

.tfvars file:
```
virtual_network_name = "vnet1"
region = "East US"
address_space = ["10.50.0.0/24"] (I also tried address_space = "10.50.0.0/24"
```

main.tf:
```hcl
resource "azurerm_virtual_network" "vnet" {
  name                = "${var.virtual_network_name}"
  resource_group_name = "${azurerm_resource_group.vnet.name}"
  address_space       = "${var.virtual_network_address_space}"
  location            = "${var.region}"
}
```

### Debug Output
```
2018/06/29 13:22:35 [ERROR] root: eval: *terraform.EvalTypeCheckVariable, err: variable virtual_network_address_space in module Virtualnetwork should be type string, got list
2018/06/29 13:22:35 [ERROR] root: eval: *terraform.EvalSequence, err: variable virtual_network_address_space in module Virtualnetwork should be type string, got list
2018/06/29 13:22:35 [TRACE] [walkInput] Exiting eval tree: module.Virtualnetwork.var.virtual_network_address_space
```

### Expected Behavior

When I run terraform apply, it should create a virtual network with the specified address space.

### Actual Behavior

Terraform fails to create the resource, and gives an error message that says address_space should be type string, got list. If I change it from a list to a string, I get an error message that it should be type list, got string.

### Steps to Reproduce

1. Make address_space a list (like in the example in the docs)
2. terraform plan (error)
3. Make address_space a string (no brackets, wrapped in double quotes)
4. terraform plan (error)

Any help would be greatly appreciated! Here's the example I used: https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html

**Comment by mildwonkey** [comment]
Hi @cofonseca - I wonder if you have a type mismatch somewhere in the configuration files. 

Can you share any remaining configuration files, including the definition of `address_space` ? 

Here are a few examples of things I would expect to work: 

## virtual_network_address_space is a list

```hcl
variable "virtual_network_address_space" {
   type = list
}

resource "azurerm_virtual_network" "vnet" {
  name                = "${var.virtual_network_name}"
  resource_group_name = "${azurerm_resource_group.vnet.name}"
  address_space       = "${var.virtual_network_address_space}"
  location            = "${var.region}"
}
```

terraform.tfvars:

```hcl
virtual_network_address_space = ["10.50.0.0/24"]
```

## virtual_network_address_space is a string; address_space is a list
```hcl
variable "virtual_network_address_space" {
   type = string
}

resource "azurerm_virtual_network" "vnet" {
  name                = "${var.virtual_network_name}"
  resource_group_name = "${azurerm_resource_group.vnet.name}"
  address_space       = ["${var.virtual_network_address_space}"]
  location            = "${var.region}"
}
```

terraform.tfvars:
```hcl
virtual_network_address_space = "10.50.0.0/24
```

## Error: mixing string and list
This will not work
```hcl
variable "virtual_network_address_space" {
   type = list
}

resource "azurerm_virtual_network" "vnet" {
  name                = "${var.virtual_network_name}"
  resource_group_name = "${azurerm_resource_group.vnet.name}"
  address_space       = "${var.virtual_network_address_space}"
  location            = "${var.region}"
}
```

terraform.tfvars
```hcl
virtual_network_address_space = "10.50.0.0/24"
```

This will error with ` Error: variable virtual_network_address_space should be type list, got string`

**Comment by cofonseca** [comment]
Hi @mildwonkey , 

Thanks for the detailed response! I'm a bit embarrassed to admit that it was indeed a type mismatch. I was looking at an older version of my config in a separate tab and didn't realize that the live version of my config had the wrong type!

Thank you for the help!

**Comment by ameyaagashe** [comment]
I am getting the error as

Unknown token IDENT list if I do exactly the way you described here.

**variable.tfvars**
`address_space = [ "10.97.0.0/16" ]`
**build-windows.tf**
```
variable "address_space" {
  type = list
}
resource "azurerm_virtual_network" "tf-virtual-network" {
  name                = "${var.virtual_network_name}"
  address_space       = "${var.address_space}"
  location            = "${var.Location}"
  resource_group_name = "${var.Resource_group_name}"
}
```
