### ISSUE TITLE
duplicate locals when using override

### ISSUE THREAD

**Issue by davidneudorfer** [hashicorp/terraform#18363]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

`main.tf`
```hcl
locals {
  foo = "bar"
}
```
`override.tf`
```hcl
locals {
  foo = "bar"
}
```
### Debug Output
```
2018/06/29 20:54:12 [INFO] Terraform version: 0.11.7
2018/06/29 20:54:12 [INFO] Go runtime version: go1.10.1
2018/06/29 20:54:12 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.7/bin/terraform", "plan"}
2018/06/29 20:54:12 [DEBUG] Attempting to open CLI config file: /Users/davidneudorfer/.terraformrc
2018/06/29 20:54:12 Loading CLI configuration from /Users/davidneudorfer/.terraformrc
2018/06/29 20:54:12 [INFO] CLI command args: []string{"plan"}
2018/06/29 20:54:12 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: foo: duplicate local. local value names must be unique
```

### Expected Behavior
the `local` variable `foo` in `override.tf` would override the one in `main.tf`
### Actual Behavior

Terraform claims they are duplicate.
### Steps to Reproduce
1. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @davidneudorfer! Sorry for this bug and thanks for reporting it.

I think you're describing here the same problem as #18351, so I'm going to close this one just to consolidate the discussion over there. Thanks again for reporting this!
