### ISSUE TITLE
Looks like the habitat provisioner is missing a space

### ISSUE THREAD

**Issue by skylerto** [hashicorp/terraform#18399]
https://github.com/hashicorp/terraform/blob/a50a3839460af999ffe4a4be92f4eaf6b621919b/builtin/provisioners/habitat/resource_provisioner.go#L612

This causes an error when trying to do anything with an on prem depot.

The solution `options += fmt.Sprintf(" --url %s", service.URL)` will fix this.

**Comment by mildwonkey** [comment]
Hi @skylerto  - 
Provisioners are bundled and releases with terraform, if that's what you were asking about. 

Providers are downloaded from releases.hashicorp.com during `terraform init` and there's a separate provider release process (if you are interested in providers, you can find our documentation [here](https://www.terraform.io/guides/terraform-provider-development-program.html))

**Comment by skylerto** [comment]
I had a suspicion that they were released together, that answers my question, thanks!
