### ISSUE TITLE
Support for PowerDNS set-ptr flag on A/AAAA records

### ISSUE THREAD

**Issue by jgeorgeson** [hashicorp/terraform#18396]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
resource "powerdns_record" "foobar" {
  zone    = "example.com"
  name    = "www.example.com"
  type    = "A"
  ttl     = 300
  records = ["192.168.0.11"]
}
```

### Additional Context

The PowerDNS REST API includes a boolean to automatically create PTR records when adding an A or AAAA record with an IP that is within an already configured reverse lookup zone. It'd be nice to make use of that in Terraform, so we can define a single resource.

### References

https://doc.powerdns.com/authoritative/http-api/zone.html#record

**Comment by bcorner13** [comment]
this provider seems to have been merged in with the base code as terraform-providers/terraform-provider-powerdns has been archived
