### ISSUE TITLE
Crash - " It would be immensely helpful if you could please report the crash with Terraform[1] so that we can fix this."

### ISSUE THREAD

**Issue by amaslows** [hashicorp/terraform#18409]
### Terraform Version
$ terraform --version
Terraform v0.11.7
+ provider.opc v1.1.2

```
...
```

### Terraform Configuration Files
hoping the crash log is enough to help you, no urgent issue on my end

```hcl
...
```

### Crash Output
https://gist.github.com/amaslows/169177fcda9ea13d6f93ca44f8757d65

### Expected Behavior
not crash

### Actual Behavior
crashed
### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by scross01** [comment]
I'm not seeing any errors in the crash.log, did the file get truncated uploading the Gist?

**Comment by amaslows** [comment]
Hi Stephen, yes looks like it truncated it, i'll add a second gist here and at the opc #137 -https://github.com/terraform-providers/terraform-provider-opc/issues/137

**Comment by amaslows** [comment]
actually i t is all there, just the initial view is truncated - click "This file has been truncated, but you can view the full file." - https://gist.github.com/amaslows/169177fcda9ea13d6f93ca44f8757d65/raw/7513dbf53b3f66a3cbfa7fc2a5463e17c8c74f6d/crash.log
