### ISSUE TITLE
Support MSI (like EC2 roles) authentication when using a remote backend?

### ISSUE THREAD

**Issue by stonefury** [hashicorp/terraform#18425]
I'm using an Azure server as my terraform control machine, to do my deployments.  MSI solves the authentication issue of running terraform, but I can't init the remote backend file unless I provide an explicit storage key.  

Is there a way to authenticate via MSI for terraform init when using a remote backend?

**Comment by tombuildsstuff** [comment]
This wasn't resolved by #19414, so I'm going to reopen this for the moment - but this will be in an upcoming PR in the near future

**Comment by tombuildsstuff** [comment]
Update: support for authenticating via MSI has been added in #19433 :)

**Comment by tombuildsstuff** [comment]
Closing since support for authenticating using Managed Service Identity has been added in #19433
