### ISSUE TITLE
terraform destroy error when referencing a random_id resource in a module's locals block

### ISSUE THREAD

**Issue by metmajer** [hashicorp/terraform#18424]
### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.26.0
+ provider.random v1.3.1
```

### Terraform Configuration Files
```hcl
provider "aws" {}
provider "random" {}

resource "random_id" "random" {
  byte_length = 8
}

module "aws-ec2-instance" {
  source = "github.com/metmajer/terraform-aws-ec2"

  name = "${var.name}"
  uuid = "${random_id.random.hex}"
}
```

### Debug Output

See https://gist.github.com/metmajer/11063a52fb166a1d228fe115b637da91#file-terraform-destroy-log.

### Expected Behavior

`terraform destroy` should not complain about a `nil` reference in `random_id`.

### Actual Behavior

In a newly initialized workspace, `terraform destroy` issues the following error:

```
Error: Error applying plan:

1 error(s) occurred:

* module.aws-ec2-instance.var.uuid: variable "random" is nil, but no error was reported
```

### Steps to Reproduce

1. `terraform init`
2. `terraform destroy`

### Additional Context

I could only reproduce the issue if `${random_id.random.hex}` is passed on to a module **AND** if the module references the passed-on variable in a `locals` block. See `${var.uuid}` in https://github.com/metmajer/terraform-aws-ec2/blob/master/main.tf.

If https://github.com/metmajer/terraform-aws-ec2/blob/master/main.tf was changed to https://github.com/metmajer/terraform-aws-ec2/blob/no-locals/main.tf, the error does not occur.

It appears that I needed to `rm -rf terraform.tfstate* .terraform; terraform init` before validating that the error does not occur with https://github.com/metmajer/terraform-aws-ec2/blob/no-locals/main.tf. Otherwise, the error persisted.

### References

Related issues are:
- #16190
- #7993

**Comment by metmajer** [comment]
@jbardin: is there any other information I can provide? I am wondering since this issue is currently blocking us in our project. Let me know if we can collaborate somehow!

**Comment by Constantin07** [comment]
I'm having the same issue. Is there any workaround for it meanwhile ?

**Comment by tbugfinder** [comment]
@jbardin It still fails using tf 0.11.14.

**Comment by teamterraform** [comment]
Hello,

This particular problem is no longer reproduced with Terraform 0.12. Users experiencing similar errors with 0.12 are not likely from the same root cause, and we ask that a new issue be opened in that case. 

Since there is no more planned development for 0.11, we are going to close out this issue. 

Thanks
