### ISSUE TITLE
Better errors when resources don't get created due to invalid JSON

### ISSUE THREAD

**Issue by mzhaase** [hashicorp/terraform#18429]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.26.0
+ provider.cloudflare v1.0.0
+ provider.template v1.0.0
```

```hcl
resource "aws_ecs_task_definition" "definition" {
  family                         = "abc"
  container_definitions =<<EOF
  [
    {
     "name": "abc",
     "image": "busybox:latest",
     "essential": true,
     "portMappings": [
       {
         "containerPort": 25,
         "hostPort": 25
       }
     ]
     }, # <-- invalid comma
    }
  ]
EOF
}

resource "aws_ecs_service" "service" {
  name                = "abc"
  cluster             = "my-cluster"
  task_definition     = "${aws_ecs_task_definition.definition.arn}"
  scheduling_strategy = "DAEMON"
}
```

### Expected Behavior
aws_ecs_task_definition.definition.container_definitions: invalid JSON

### Actual Behavior
aws_ecs_service.service: Resource 'aws_ecs_task_definition.definition' not found for variable 'aws_ecs_task_definition.definition.arn'

### Steps to Reproduce
1. try to apply above code

**Comment by bflad** [comment]
@apparentlymart I believe this issue is related to:
* https://github.com/hashicorp/terraform/issues/18129
* https://github.com/hashicorp/terraform/issues/16332
* https://github.com/hashicorp/terraform/issues/14333

Instead of something within the AWS provider itself.

**Comment by apparentlymart** [comment]
@bflad the symptom here is similar to those, but I assumed it was a bug that the AWS provider isn't returning its _own_ error about the JSON being invalid here. In other words, it's a bug that we're reaching the point where Terraform could return this error at all.

**Comment by apparentlymart** [comment]
Oh,  I see you're saying in one of those that the provider _is_ returning the error but Core is somehow masking the error with this other error.

In which case yes, this does seem to be the same thing as #18129.
