### ISSUE TITLE
terraform cli reported bug with "Terraform" for aws autoscaling group saying diff didnt match during apply

### ISSUE THREAD

**Issue by cn-mayank** [hashicorp/terraform#18433]
### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.26.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```
resource "aws_autoscaling_group" "node-linux-asg2" {
  availability_zones   = ["${var.core-availability-zone}"]
  name                 = "${var.cluster-name}-node-linux"
  max_size             = "${var.node-linux-asg-max-size}"
  min_size             = "${var.node-linux-asg-min-size}"
  desired_capacity     = "${var.node-linux-asg-desired-capacity}"
  force_delete         = true
  vpc_zone_identifier  = ["${aws_subnet.Nodes.id}"]
  launch_configuration = "${aws_launch_configuration.node-linux-lc.name}"

  tag {
    key                 = "Name"
    value               = "${var.cluster-name}-node-linux"
    propagate_at_launch = "true"
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Crash Output
https://gist.github.com/cn-mayank/49cb3352e37b33b6d98185ea937f3865

### Expected Behavior
Autoscaling group should have created successfully

### Actual Behavior
Terraform crashed without creating autoscaling group

### Steps to Reproduce
I used the above configuration to create auto-scaling group, then destroyed it and henceforth creating auto-scaling group even with different names was crashing with above error asking to report in github.

### Additional Context
On running the apply command again, it got created successfully. So first apply fails due to diff error, next apply didnt face this diff issue

### References
- #6017

**Comment by bflad** [comment]
Hi @cn-mayank 👋  Sorry you ran into trouble here.

Until recently, the [`aws_autoscaling_group` resource documentation](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html) did not clarify the usage of the `availability_zones` attribute to be only required for EC2-Classic. In VPC environments, the subnet IDs passed into `vpc_zone_identifier` will automatically determine the availability zones (as a subnet is inherently part of a availability zone).

To fix your situation, simply remove the `availability_zones` configuration in your resource. Hope this helps!

**Comment by cn-mayank** [comment]
Oh ok, thanks a lot @bflad for the prompt response. 
One small question, I was wondering if posted this at right place or i should have posted in the aws provider repository ?
