### ISSUE TITLE
dag/walk: vertex infinite loop on DNS failure

### ISSUE THREAD

**Issue by benoitvidis** [hashicorp/terraform#18441]
### Terraform Version

```
v0.11.7
```

### Debug Output

[https://gist.github.com/benoitvidis/5eacf39ee1ebe49c8af1161e2a83f4e0](https://gist.github.com/benoitvidis/5eacf39ee1ebe49c8af1161e2a83f4e0)

### Expected Behavior

When running a `plan` or `apply` and I get some occasional DNS response timeouts, I would expect terraform to fail and stop.

### Actual Behavior

When such timeout occurs, terraform still tries to walk through the plan, creating an infinite loop, silent by default when no TF_LOG var is set.
The only way to exit if to force exit, leaving the lock.

### Steps to Reproduce

I am getting the issue when using a hardware Palo Alto firewall, which does some DNS caching but I could reproduce it by using dnsmasq and stopping the service in the middle of the plan

**Comment by jbardin** [comment]
Hi @benoitvidis,

Thanks for filing the issue. It is up to the provider to determine if it should retry or timeout in this case. The retries here are happening within the aws provider, so we can review the timeouts particular to that provider.
