### ISSUE TITLE
[ERROR] connection error: dial tcp 54.89.109.252:22: i/o timeout

### ISSUE THREAD

**Issue by perryluopl** [hashicorp/terraform#18449]
### Terraform Version

```
 terraform -v
Terraform v0.11.7
+ provider.aws v1.27.0

```

### Terraform Configuration Files

```hcl
    connection {
    user        = "centos"
    private_key = "${file("${var.key_path}/${var.key_name}.pem")}"
  }

```

### Debug Output

[DEBUG] plugin.terraform: file-provisioner (internal) 2018/07/12 13:54:07 [ERROR] connection error: dial tcp 54.89.109.252:22: i/o timeout
[DEBUG] plugin.terraform: file-provisioner (internal) 2018/07/12 13:54:07 [WARN] retryable error: dial tcp 54.89.109.252:22: i/o timeout

[DEBUG] plugin.terraform: file-provisioner (internal) 2018/07/12 13:54:23 [ERROR] connection error: dial tcp 54.89.109.252:22: i/o timeout
plugin.terraform: file-provisioner (internal) 2018/07/12 13:54:23 [WARN] retryable error: dial tcp 54.89.109.252:22: i/o timeout

[DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* module.cloudera.aws_instance.cdh_server: timeout - last error: dial tcp 54.89.109.252:22: i/o timeout

### Expected Behavior

I got i/o time out when I terraform apply.

**Comment by AlanJebakumarFluke** [comment]
Im also getting the same error. Any suggestions to fix this?
