### ISSUE TITLE
dynamic source for modules

### ISSUE THREAD

**Issue by enxebre** [hashicorp/terraform#1846]
Is it possible or something you are planing to support a interpolation for module sources, so it would be possible to achieve a kind of "polymorphism" behaviour like:
```ruby
# Default Image provider module
...
...
output "image_id" {
    value = "the-image-id"
}
```
then in the main file:

```ruby
variable "image-provider-source" {
  description = "The module providing the source base image."
  default = "my-default-module-for-providing-the-image-id"
}

module "image-provider" {
    source = "./modules/${var.image-provider-source}"
}

# My vm resource
resource "digitalocean_droplet" "example" {
  image = "${module.image-provider.image_id}"
}
```
Otherwise only think I can think apart from hardcode the provider in the source would be to pass the choosed provider as a variable for the module and handle the different providers inside just on module
Is there any know approach for something similar?

Thanks!

**Comment by ketzacoatl** [comment]
@enxebre, have you tested this or run into an error with the above? I haven't, but looking it over, that ought to work fine.

**Comment by enxebre** [comment]
Sure I did :) and I got: "module source cannot contain interpolations"

**Comment by radeksimko** [comment]
FYI https://github.com/hashicorp/terraform/issues/1439

**Comment by mitchellh** [comment]
Discussion in #1439

**Comment by enxebre** [comment]
cool thanks!
