### ISSUE TITLE
Someway to warn on config drift but not take action on it

### ISSUE THREAD

**Issue by jw-maynard** [hashicorp/terraform#18471]
Please see the issue referenced below for background. I'm opening this issue in terraform core first because I don't know if what I'm requesting is functionality that can already be leveraged by providers and the AWS provider just does not use it or if this is something that would need to be added to core before providers could start leveraging it.

### Expected Behavior

As outlined in #16881 TF's AWS provider will not current remove SG rules that are manually added to and SG from the console when you create and SG and then create SG rules and attach them to the SG. This behavior is very helpful in allowing other systems to come in after TF and gain access to resources provisioned with TF. However, it would be helpful in managing configuration drift if Terraform had the ability to report on changes while also ignoring them. In this case a terraform plan command might report that there were SG rules that are not defined in the TF files but indicate that it will take no action to remove these rules. That way action could be taken to remove any rules that should not have been added.

### References

- #16881

**Comment by bflad** [comment]
I wonder if this issue can be closed out with the plan drift detection feature added in Terraform CLI version 0.15.4 and later?

**Comment by jw-maynard** [comment]
@bflad I think so. I did notice that running a refresh only plan in TF now shows rules that have been added outside TF. This allows them to be reviewed and either removed or absorbed into the state file as "OK"
