### ISSUE TITLE
terraform crashed

### ISSUE THREAD

**Issue by ttang2tang** [hashicorp/terraform#18489]
[crash.log](https://github.com/hashicorp/terraform/files/2207717/crash.log)

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

If your issue relates to a specific Terraform provider, please open it in the provider's own repository. The index of providers is at https://github.com/terraform-providers .
-->

### Terraform Version
2018/07/18 16:47:34 [INFO] Terraform version: 0.11.7

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by ttang2tang** [comment]
oh, it is ok, i figured out it is caused by OCI terraform provider, will 
file ticket to Oracle team.


Thanks

Tom

**Comment by mildwonkey** [comment]
Thanks Tom!
