### ISSUE TITLE
local declarations of maps will silently fail when self referencing.

### ISSUE THREAD

**Issue by kitsunde** [hashicorp/terraform#18503]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
locals {
  test = {
    value = "value"
    test  = "${local.test["value"]}"
  }
}

output "test" {
  value = "${local.test}"
}
```

### Expected Behavior

Error on the failure to initialize the map.

### Actual Behavior

It silently does nothing:

```bash
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce
1. `terraform apply`

**Comment by apparentlymart** [comment]
Thanks for pointing this out, @kitsunde!

We do indeed seem to be missing a check for self-referential locals here. We have some checks in place for self-referencing _resources_, but they don't generalize to other concepts that can reference themselves.

**Comment by Indigenuity** [comment]
What version is this expected to show up in?  I'm on `0.11.10` so obviously I still see this error, but is `0.12.0` going to have this?  It affects not just outputs but also interpolation into variables during `terraform plan`:
```
  + google_compute_instance.m1
      id:                                     <computed>
      boot_disk.#:                            "1"
      boot_disk.0.auto_delete:                "true"
      boot_disk.0.device_name:                <computed>
      boot_disk.0.disk_encryption_key_sha256: <computed>
      boot_disk.0.initialize_params.#:        "1"
      boot_disk.0.initialize_params.0.image:  "${local.m1[\"image\"]}"
...
```
