### ISSUE TITLE
Resource 'aws_iam_role.iamrole' does not have attribute 'id' for variable 'aws_iam_role.iamrole.id'

### ISSUE THREAD

**Issue by mnivedithaa** [hashicorp/terraform#18518]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```resource "aws_iam_role" "iam_nginx_container_role" {
  name  = "${var.dcname}_iam_nginx_container_role"
  count = "${signum(var.enable_nginx)}"

  assume_role_policy = <<EOF
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs-tasks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "iam_nginx_task_role_policy" {
  name  = "${var.dcname}_iam_nginx_policy_config"
  role  = "${aws_iam_role.iam_nginx_container_role.id}"
  count = "${signum(var.enable_nginx)}"

  policy = <<EOF
{
 "Version": "2012-10-17",
 "Statement":[{
      "Effect": "Allow",
      "Action": [
         "ssm:GetParameters",
         "kms:Decrypt"
      ],
      "Resource": "arn:aws:ssm:${var.aws_region}:${var.aws_account_id}:parameter/${var.dcname}_*"
 }]
}
EOF
}
```

### Debug Output
* module.nginx.aws_iam_role_policy.iam_nginx_task_role_policy: Resource 'aws_iam_role.iam_nginx_container_role' does not have attribute 'id' for variable 'aws_iam_role.iam_nginx_container_role.id'

### Expected Behavior

Role to be created, Policy to be created using id of role created

### Actual Behavior

Role got created. While trying to create policy, got error that 'id' attribute is not available. And terraform state doesn't contain the details of IAM roles that got created. Hence another terraform apply failed saying role already exists

### Steps to Reproduce

Not able to reproduce this issue. It occurred only once

### Additional Context
Although the role got created, Terraform state didn't have the details of role created

**Comment by zasibesant** [comment]
Resource 'aws_iam_role.main' does not have attribute 'name' for ... not have attribute 'id' for variable 'aws_iam_role.main.id' Terraform does not ... the occasion when it does fail, if I remove the IAM Role that was created 

[aws training in chennai](https://www.besanttechnologies.com/training-courses/cloud-computing-training/amazon-web-services-training-institute-in-chennai)
