### ISSUE TITLE
Sorry for not opening the issue correctly (#18505 ).  There is a BUG with Terraform when trying to add an Azure Automation schedule.  When I add a Frequency of 'DAY' it requires an INTERVAL  argument, but the INTERVAL argument is invalid.  Please resolve.

### ISSUE THREAD

**Issue by dmtanner16** [hashicorp/terraform#18522]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by mildwonkey** [comment]
Hi @dmtanner16!
I'm sorry that you are experiencing an issue. I will move this issue to [the provider's own GitHub repository](https://github.com/terraform-providers/terraform-provider-azurerm).
