### ISSUE TITLE
Unexpected behavior declaring multiple `aws_s3_bucket_notification` on the same bucket

### ISSUE THREAD

**Issue by alirabiee** [hashicorp/terraform#18521]
### Terraform Version
0.11.4

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket_notification" "my-bucket-trigger-1" {
  bucket = "${aws_s3_bucket.my-bucket.id}"

  lambda_function {
    lambda_function_arn = "${aws_lambda_function.my-lambda-1.arn}"
    events              = ["s3:ObjectCreated:*"]
    filter_prefix       = "blahblah"
    filter_suffix       = "blahblah"
  }
}
resource "aws_s3_bucket_notification" "my-bucket-trigger-2" {
  bucket = "${aws_s3_bucket.my-bucket.id}"

  lambda_function {
    lambda_function_arn = "${aws_lambda_function.my-lambda-2.arn}"
    events              = ["s3:ObjectCreated:*"]
    filter_prefix       = "abcd"
    filter_suffix       = "wxyz"
  }
}
```

### Debug Output
```
aws_s3_bucket_notification.my-bucket-trigger-2: Modifying... (ID: ####)
...
  lambda_function.0.filter_prefix:       "blahblah" => "abcd"
```

### Expected Behavior
It is expected that Terraform creates the two separate resource definitions, merges them, or throws a validation error.

### Actual Behavior
It considers the definition valid and tries to apply the changes. By applying, it overrides one resource definition over another, resulting some lambdas not to have the expected triggers.

**Comment by zasibesant** [comment]
The "Trigger multiple Lambda functions" example on this page: ... Configurations on the same bucket cannot share a common event type.

[aws training course](https://www.besanttechnologies.com/training-courses/cloud-computing-training/amazon-web-services-training-institute-in-chennai)
