### ISSUE TITLE
Provider doesn't support data source: template_dir

### ISSUE THREAD

**Issue by redscaresu** [hashicorp/terraform#18535]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
data "template_dir" "opt_bin_foo" {
  source_dir = "${path.module}/../data/foo"
  destination_dir = "/opt/bin/foo"
}

### Crash Output
<!--
Error: module.app1_data_1.data.template_dir.opt_bin_foo: Provider doesn't support data source: template_dir
-->

### Expected Behavior
<!--
Allow me to create a data construct for template_dir
-->

### Actual Behavior
<!--
failed because the provider does not support the data source for template_dir
-->

### Steps to Reproduce
<!--
1. `terraform init`
2. `terraform apply`
-->

### Additional Context
<!--
Hi, if there a design reason why this functionality is not already included please free to
let me know.  It would be really useful to be able to use this functionality especially in
the context coreos ignition.  I have not included the debug output because it feels
like this is simply a case of missing functionality.
-->

**Comment by mildwonkey** [comment]
Hi @redscaresu  - 

Are you looking for the `resource "template_dir"` described here  https://www.terraform.io/docs/providers/template/r/dir.html, or trying to do something different?

**Comment by redscaresu** [comment]
hi @mildwonkey thanks for picking this up.

Yes thats correct so I was hoping to do something similar to this

data "template_file" "foo_conf" {
  template = "${file("../../data/foo.tpl")}"

  vars {
    splunk_master = "${var.foo}"
  }
}

but the problem is that template_dir does not support the data type.

**Comment by mildwonkey** [comment]
Thanks for clarifying @redscaresu! I'll flag this ticket so it gets moved to the [template provider repository](https://github.com/terraform-providers/terraform-provider-template). 
Cheers!
