### ISSUE TITLE
GetSchema() Failing for Invalid Provider Schema

### ISSUE THREAD

**Issue by WalkerGriggs** [hashicorp/terraform#18544]
Hi all,

I was writing a harness which called `GetSchema()` (helper/schema/provider.go) on various providers when I noticed a bug which, according to Terraform's error handling, [should never happen for a valid schema](https://github.com/hashicorp/terraform/blob/master/helper/schema/core_schema.go#L48) .

### Expected behavior
Iterate over each provider resource and get the schema.

### Actual behavior
`provider.GetSchema(...)` panics for certain resources -- listed below -- , causing the thread to panic and exit.

```
panic: invalid Schema.Elem 4; need *Schema or *Resource

goroutine 1 [running]:
github.com/hashicorp/terraform/helper/schema.schemaMap.CoreConfigSchema(0xc4203c8630, 0xc420222b60)
    /Users/walker.griggs/go/src/github.com/hashicorp/terraform/helper/schema/core_schema.go:49 +0x3ab
github.com/hashicorp/terraform/helper/schema.(*Resource).CoreConfigSchema(0xc4203c4b60, 0xc4204f1ce0)
    /Users/walker.griggs/go/src/github.com/hashicorp/terraform/helper/schema/core_schema.go:154 +0x2e
github.com/hashicorp/terraform/helper/schema.(*Provider).GetSchema(0xc420254380, 0xc42023f470, 0x0, 0x54bdb98, 0x0)
    /Users/walker.griggs/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:196 +0xf4
main.getSchema(0x38f6e60, 0xc420254380, 0xc4203b93a0, 0x1, 0x1)
    /Users/walker.griggs/go/src/playground/at-2018-06-21-121017/snippet.go:46 +0xdc
main.getSingleSchema(0x38f6e60, 0xc420254380, 0x370c01f, 0x1a)
    /Users/walker.griggs/go/src/playground/at-2018-06-21-121017/snippet.go:40 +0x80
main.GenerateProviderSchema()
    /Users/walker.griggs/go/src/playground/at-2018-06-21-121017/snippet.go:23 +0x89
main.main()
    /Users/walker.griggs/go/src/playground/at-2018-06-21-121017/snippet.go:57 +0x20
exit status 2
```

Of course, this is stemming from CoreConfigSchema(), but the reason I'm raising this issue is
because of the comment on line [48](https://github.com/hashicorp/terraform/blob/master/helper/schema/core_schema.go#L48)

> // Should never happen for a valid schema

### Steps to reproduce

The code path I'm following is to call the provider => iterate over provider resources => `GetSchema()`for each resource. I could get the schema for all resources at once, but, for the sake of debugging, I'm recovering from each panic and logging the resource which caused the schema error.

```go
package main

import (
    "log"

    "github.com/hashicorp/terraform/terraform"

    "github.com/terraform-providers/terraform-provider-aws/aws"
    //"github.com/terraform-providers/terraform-provider-google/google"
)

// GenerateProviderSchema is the entrypoint for provider schema generation. In an
// ideal world, it takes in the provider name/version and returns the provider
// schema. For the sake of this demo, it doesn't return anything.
func GenerateProviderSchema() {
    p := aws.Provider()

    // Iterate over each provider resource. As opposed to requesting the
    // schema for all resources at once, for the sake of this demo we're
    // generating the schema individually. This way, we're able to catch any
    // panics should the SchemaRequest error out.
    for _, resource := range p.Resources() {
        getSingleSchema(p, resource.Name)
    }

}

// getSingleSchema takes in the provider object and the resource name, and, in an
// ideal world, returns the schema for that resource. If a ProviderSchemaRequest
// fails, the panic is caught so the application can continue to the next resource.
//
// Remove the deferred error handler to see the underlying error.
func getSingleSchema(p terraform.ResourceProvider, resource string) {
    defer func() {
        if r := recover(); r != nil {
            log.Println("SchemaRequest failed with", resource)
        }
    }()

    getSchema(p, []string{resource})
}

// getSchema takes in the provider and a list of resources. Ideally, this would
// return the schema.
func getSchema(provider terraform.ResourceProvider, resourceTypes []string) {
    _, err := provider.GetSchema(&terraform.ProviderSchemaRequest{
        ResourceTypes: resourceTypes,
        DataSources:   make([]string, 0),
    })

    if err != nil {
        log.Fatal(err)
    }
}

func main() {
    GenerateProviderSchema()
}
```
I've also tried the comparable code path over RPC with `plugin.ResourceProvider` types, which ends in the same result. While this behavior can be handled locally, host panics over RPC are difficult to handle.

### Steps to Triage

I altered the CoreConfigSchema switch to print the invalid schema element type. Of all the failing resources from the Google and AWS providers, the invalid element was always a `TypeString` (ValueType).

```go
/* from CoreConfigSchema(), helper/schema/core_schema.go */
        if schema.Elem == nil {
            ret.Attributes[name] = schema.coreConfigSchemaAttribute()
            continue
        }
        switch t := schema.Elem.(type) {
        case *Schema:
            ret.Attributes[name] = schema.coreConfigSchemaAttribute()
        case *Resource:
            ret.BlockTypes[name] = schema.coreConfigSchemaBlock()
        default:
            // Should never happen for a valid schema
            panic(fmt.Errorf("invalid Schema.Elem %#v; need *Schema or *Resource. Instead found %s", schema.Elem, t))
        }
```

`panic: invalid Schema.Elem 4; need *Schema or *Resource. Instead found TypeString`

I identified all resources and their specific attributes with invalid schema.

#### For Google (1.16.2):
| Type | Name | Attribute |
|---|---|---|
| resource | google_bigquery_table | labels |
| resource | google_compute_instance | metadata |
| resource | google_compute_instance_from_template | metadata |
| resource | google_pubsub_subscription | attributes |
| resource | google_compute_project_metadata | metadata |
| resource | google_container_node_pool | labels |
| resource | google_dataproc_cluster | labels |
| resource | google_container_cluster | labels |
| resource | google_bigquery_dataset | labels |
| data source | google_container_cluster | resource_labels |
| data source | google_storage_object_signed_url | extension_headers |

#### From AWS (1.29.0)
| Type | Name | Attribute |
|---|---|---|
| resource | aws_kms_grant | encryption_context_equals |
| data source | aws_lambda_function | variables |

#### From Azure
- None...

Interestingly, every example I found was a schema of type map with elements of type string. An example of this 'invalid' schema is the `google_compute_instance`'s labels attribute in Google 1.16.2.

```go
            "labels": &schema.Schema{
                Type:     schema.TypeMap,
                Optional: true,
                Elem:     schema.TypeString,
                // Should be 
                // Elem:     &schema.Schema{Type: schema.TypeString},  
            }
```

Another example of 'invalid' nested schema is in `aws_kms_grant`'s contraints attribute in AWS 1.29.0

```go
    "constraints": {
        Type:     schema.TypeSet,
        Set:      resourceKmsGrantConstraintsHash,
        Optional: true,
        ForceNew: true,
        Elem: &schema.Resource{
            Schema: map[string]*schema.Schema{
                "encryption_context_equals": {
                    Type:     schema.TypeMap,
                    Optional: true,
                    ForceNew: true,
                    Elem:     schema.TypeString,
                    // Should be 
                    // Elem:     &schema.Schema{Type: schema.TypeString},  
                },
                "encryption_context_subset": {
                    Type:     schema.TypeMap,
                    Optional: true,
                    ForceNew: true,
                    Elem:     schema.TypeString,
                    // Should be 
                    // Elem:     &schema.Schema{Type: schema.TypeString},  
                },
            },
        },
    },
```

The proposed solution is two fold
1) Update the provider internal validation with the missing error condition (type map with string elements)

2) Create an interface for the schema element field which both Schema and Resource implement to replace the current empty interface.

```go
// The following fields are only set for a TypeList, TypeSet, or TypeMap.  
//  
// Elem represents the element type. For a TypeMap, it must be a *Schema  
// with a Type of TypeString, otherwise it may be either a *Schema or a  
// *Resource. If it is *Schema, the element type is just a simple value.  
// If it is *Resource, the element type is a complex structure,  
// potentially with its own lifecycle.  

// Current
Elem interface{}

// Proposed
// Elem Element
```

As for what the common functionality between the two types are, I'd be interested to hear your thoughts.

**Comment by bflad** [comment]
Hi @WalkerGriggs! 👋  Thanks for writing this in. I will let someone much more knowledgeable about the provider validation chime in about fixing it, but just wanted to note that I we submitted and merged the fixes for the AWS provider in https://github.com/terraform-providers/terraform-provider-aws/pull/5350, which will release in version 1.30.0 of the provider. 👍

**Comment by WalkerGriggs** [comment]
@bflad You work fast! Stay tuned on provider validation, but, with those changes, 1.30.0 is passing 🎉.

**Comment by apparentlymart** [comment]
Hi @WalkerGriggs,

The `GetSchema` method here was added as part of an initial attempt to support the new HCL features via an opt-in feature flag in a 0.11 release, but we found that the complexity of implementing that was far greater than initially expected and change plans. Unfortunately that means that this implementation of `GetSchema` was essentially abandoned, and so we didn't get around to a full round of testing to find bugs like these.

In the mean time, some providers have upgraded their vendored provider SDK for other reasons and ended up having the `GetSchema` method available, but we don't currently consider it a supported interface because Terraform Core itself isn't using it.

[The forthcoming 0.12 release](https://www.hashicorp.com/blog/terraform-0-1-2-preview) will include a new provider protocol that will include a well-tested and officially-supported equivalent to this `GetSchema` function that should be robust against all of the strange variant schema definitions that have emerged in providers over the years. We are also planning to add a CLI command to retrieve the schema for a provider in a machine-readable form to avoid the need to use Terraform as a Go library (which it is not designed to be) but that's a stretch goal that might not arrive in time for the first v0.12.0 release.

**Comment by WalkerGriggs** [comment]
Hi @apparentlymart 

In that case, this issue can be closed.

On a side note, Is there a specific code path for the new schema gen in the v0.12-dev branch you're referring to?

**Comment by apparentlymart** [comment]
The new protocol isn't yet finalized, and in particular the provider SDK part of it is in progress as I write this. If you're watching the `v0.12-dev` branch you should see some changes coming in the `helper/schema` package, which'll implement the new provider RPC protocol and also see updates to the `CoreConfigSchema` method as we get closer to release.

Thanks for reporting this! We'll be sure this issue is handled in `helper/schema` before the 0.12 final release.
