### ISSUE TITLE
Add terraform version to user-agent in http remote state

### ISSUE THREAD

**Issue by repl-david-winiarski** [hashicorp/terraform#18547]
### Terraform Version

```
Latest version
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

I would expect terraform to identify which version is attempting to access the remote state file from the http backend.
### Actual Behavior

The regular Go user agent is displayed instead of a terraform specific one.

**Comment by pkolyvas** [comment]
I'm doing a clean-up of older issues that haven't gained traction but also don't coincide with some of our current focus. This issue had its associated PR closed during the 0.12 release window and so I'm just finishing the related work. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform, the use cases, and needs of our practitioners.
