### ISSUE TITLE
Provide some mechanism to pull custom plugins during "terraform init"

### ISSUE THREAD

**Issue by rayterrill** [hashicorp/terraform#18559]
### Terraform Version
```
All?
```
Can we provide some mechanism to "pull" custom plugins during "terraform init"? We have a couple of custom terraform plugins to provide functionality not covered in existing Terraform plugins (specifically things on the Windows Active Directory domain side of things). Because Terraform utilizes a per-directory "cache" of Terraform modules, having to manually copy the exe's into the right spot for each directory becomes a pain, especially when onboarding new people to Terraform and having to explain why some plugins come down automatically and others must be manually copied into the directory.

Perhaps some kind of flag to "terraform init" specifying a URL that would allow terraform to find the plugins it needs? Maybe it only uses this custom provider URL if it can't find a plugin the "normal" way (lower order of precedence)?

Something like:
```
terraform init --custom-provider-URL https://internalrepo.mydomain.com
```

**Comment by apparentlymart** [comment]
Hi @rayterrill!

This seems to be covering a similar set of use-cases as  #15252, so I'm going to close this one just to consolidate discussion over there.

Design work has begun on some of the items I discussed in that other issue, and a means to install providers from locations other than `releases.hashicorp.com` will definitely be coming in a future release.

**Comment by rayterrill** [comment]
Sounds good. Sorry, I was sure there had to be a similar issue but I couldn’t find one. Thanks!
