### ISSUE TITLE
TF Plan : connection is shut down

### ISSUE THREAD

**Issue by mm-dsiip** [hashicorp/terraform#18567]
### Terraform Version
0.10.8 and 0.11.7
AWS Module 1.29.0

```
...
```

### Terraform Configuration Files
```hcl
resource "aws_lb" "drupal" {
  name = "${data.consul_keys.ck.var.project_name}-${var.install_name}-drupal"
  internal = true
  security_groups = ["${aws_security_group.drupal-alb.id}"]
  tags {
    env = "${var.env}"
    resource-name = "${data.consul_keys.ck.var.project_name}"
    BillingBusinessApp = "${data.consul_keys.ck.var.billing_business_app}"
    Name = "${data.consul_keys.ck.var.project_name}-${var.install_name}-drupal"
  }
  subnets = ["${data.terraform_remote_state.network.aws_subnet_dataapp}"]
}
```

### Crash Output
http://tferdinand.net/PRIVATE/ted/TF_crash_log.txt

### Expected Behavior
Plan displays

### Actual Behavior
Crash

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by acloudiator** [comment]
> This issue has been automatically migrated to [terraform-providers/terraform-provider-aws#5384](https://github.com/terraform-providers/terraform-provider-aws/issues/5384) because it looks like an issue with that provider. If you believe this is _not_ an issue with the provider, please reply to [terraform-providers/terraform-provider-aws#5384](https://github.com/terraform-providers/terraform-provider-aws/issues/5384).

It's not only with aws proviver, it's with other provider as well, like `linode`
