### ISSUE TITLE
terraform get isn't compatible with git ssh

### ISSUE THREAD

**Issue by wutianchen** [hashicorp/terraform#18566]
I want to load module from gitlab through ssh.
I have configured ssh correctly so that "git push" with ssh works

module is constructed with the following code

```
module "elasticsearch_security_group" {
  source = "git::ssh://git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-security-group.git"
  name = "elasticsearch_security_group"
  vpc_id = "${var.vpc_id}"
  ingress_cidr_blocks = ["0.0.0.0/0"]
  create = "true"
}
```

but "terraform get " doesn't work with git ssh

```
2018/07/30 13:40:38 [INFO] Terraform version: 0.11.7  41e50bd32a8825a84535e353c3674af8ce799161
2018/07/30 13:40:38 [INFO] Go runtime version: go1.10.1
2018/07/30 13:40:38 [INFO] CLI args: []string{"/usr/local/bin/terraform", "get", "--update=true"}
2018/07/30 13:40:38 [DEBUG] Attempting to open CLI config file: /home/ec2-user/.terraformrc
2018/07/30 13:40:38 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/07/30 13:40:38 [INFO] CLI command args: []string{"get", "--update=true"}
- module.elasticsearch_security_group
  Updating source "git::ssh://git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-security-group.git"
2018/07/30 13:40:38 [TRACE] module source: "git::ssh://git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-security-                                       group.git"
2018/07/30 13:40:38 [TRACE] detected module source "git::ssh://git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-s                                       ecurity-group.git"
2018/07/30 13:40:38 [DEBUG] fetching module from git::ssh://git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-secu                                       rity-group.git
2018/07/30 13:40:38 [DEBUG] fetching "git::ssh://git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-security-group.                                       git" with key "1.elasticsearch_security_group;git::ssh://git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-securit                                       y-group.git"
2018/07/30 13:40:38 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=386&os                                       =linux&signature=1876a657-05db-8573-ee03-ee17a78287f6&version=0.11.7: Forbidden
2018/07/30 13:40:38 [DEBUG] plugin: waiting for all plugin processes to complete...
Error loading modules: error downloading 'ssh://git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-security-group.g                                       it': /usr/bin/git exited with 128: Cloning into '.terraform/modules/31a9f10a7ca5618dcd541d5e2c188286'...
ssh: Could not resolve hostname ssh.git.tech.rz.cb.de:Username: No address associated with hostname
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Did I miss something here ?

**Comment by chris-david-taylor** [comment]
I am also seeing this issue (will post details shortly). The suggested fix still results in the same error.

**Comment by chris-david-taylor** [comment]
I'm using Terraform 0.11.7 and Git 1.8.31 on CentOS 7.  In my setup, I have a plain git server, password less over ssh.  I've tried using a number of variations, starting from "Generic Git"

Going by the documentation, this basic example should work, but I'm getting "/usr/bin/git exited with 128:",
fatal: '/modules.git' does not appear to be a git repositry.

source = "git::ssh://git@git-server.test.lan/modules.git"

Regular 'git clone' works fine. @mildwonkey

**Comment by leafnunes** [comment]
For those having issues, and if you happen to be relying on the `GIT_SSH` environment variable to use a wrapper script that sets configuration paths for ssh (and possibly ssh agent settings for keys), try setting `GIT_SSH_COMMAND` instead.

**Comment by apparentlymart** [comment]
Hi @wutianchen! Sorry for the long silence here.

We got to the bottom of this a while ago, but apparently we missed this issue when posting updates. The problem is that the module source format supports both URL-like addresses (with `ssh://` at the front and a slash introducing the path) and `scp`-like addresses (without a URL scheme prefix and with colon introducing the path), but you can't mix parts of both syntaxes at once because a colon in the URL-like form introduces a port number.

```hcl
  # URL-like
  source = "git::ssh://git@ssh.git.tech.rz.cb.de/Username/tf-module-aws-security-group.git"

  # scp-like
  source = "git::git@ssh.git.tech.rz.cb.de:Username/tf-module-aws-security-group.git"
```

There were some fixes in subsequent versions of Terraform to improve the robustness of parsing the scp-like form, so if you wish to use that form it'd be best to upgrade to the latest version of Terraform first.
