### ISSUE TITLE
Provider "aws" not available for installation.

### ISSUE THREAD

**Issue by sureshoao** [hashicorp/terraform#18575]
terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "aws" not available for installation.

A provider named "aws" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

**Comment by apparentlymart** [comment]
Hi @sureshoao! Sorry this didn't work.

This error message suggests that Terraform encountered an error that looked like a "not found" or "forbidden" error when accessing `releases.hashicorp.com`. Is it possible that there is a proxy or "captive portal" gateway in your environment that may be interfering with the request to the server, returning an error that Terraform might confuse as a "not found"?

If possible, please run this command again with the environment variable `TF_LOG=trace` set and share the result via [gist](https://gist.github.com/). The detailed trace log will hopefully give some more details about what Terraform tried to do access here and what error was returned when it did so.
