### ISSUE TITLE
How to pass wildcard google_compute_region_instance_groups

### ISSUE THREAD

**Issue by shankarkc** [hashicorp/terraform#18572]
### Terraform Version
```
terraform -v
Terraform v0.11.7
+ provider.google v1.16.2
+ provider.random v1.3.1
+ provider.template v1.0.0```
```
When we create  backend with specific instance groups listed as below it works fine.
```

resource "google_compute_region_backend_service" "cluster-ch-backend" {
  project          = "${var.project_name}"
  name             = "${var.cluster_name}-ch-backend"
  region           = "${var.region}"
  protocol         = "TCP"
  timeout_sec      = 10
  session_affinity = "NONE"
  backend =   [
                  { group = "${google_compute_region_instance_group_manager.ch_host_rigm.0.instance_group}" },
                  { group = "${google_compute_region_instance_group_manager.ch_host_rigm.1.instance_group}" },
                  { group = "${google_compute_region_instance_group_manager.ch_host_rigm.2.instance_group}" }
              ]

  health_checks = ["${google_compute_health_check.ch-hc.self_link}"]
  depends_on = ["google_compute_health_check.ch-hc", "google_compute_region_instance_group_manager.ch_host_rigm"]
  lifecycle {
    create_before_destroy = true
  }
}
```
In above case google_compute_region_instance_group_manager.ch_host_rigm.*.instance_group is dynamic based on user inputs. There might be one group or many groups. So to make it generic i need to use wildcard group array. So I modified code as below 
```

data "google_compute_region_instance_group" "data_source" {
  count                = "${length(keys(var.ch_node_type_count))}"
    self_link = "${element(google_compute_region_instance_group_manager.ch_host_rigm.*.instance_group,count.index)}"
}

resource "google_compute_region_backend_service" "cluster-ch-backend" {
  project          = "${var.project_name}"
  name             = "${var.cluster_name}-ch-backend"
  region           = "${var.region}"
  protocol         = "TCP"
  timeout_sec      = 10
  session_affinity = "NONE"

backend =   [
                "${data.google_compute_region_instance_group.data_source.*.self_link}"
            ]

  health_checks = ["${google_compute_health_check.ch-hc.self_link}"]
  depends_on = ["google_compute_health_check.ch-hc", "google_compute_region_instance_group_manager.ch_host_rigm"]
  lifecycle {
    create_before_destroy = true
  }
}
```

With above change i get error
```
Error: Error running plan: 3 error(s) occurred:

* google_compute_region_backend_service.cluster-ch-backend: backend.0: expected object, got string
* google_compute_region_backend_service.cluster-ch-backend: backend.1: expected object, got string
* google_compute_region_backend_service.cluster-ch-backend: backend.2: expected object, got string
```
With self_link supplied why terraform complaining that it needs object? How can i make the provision code generic to with with multiple google_compute_region_instance_groups?

**Comment by mildwonkey** [comment]
I'm basing this only on the files you've shared, and not any knowledge of the Google provider, but it looks like you are missing `group =` in your second `backend` block. 

Based on that specific syntax, you may not be able to achieve what you are aiming for until the [terraform 0.12 release](https://www.hashicorp.com/blog/terraform-0-1-2-preview)

I'm on my phone right now, but I will try to come up with an alternative example when I'm back at a desk!

**Comment by shankarkc** [comment]
@mildwonkey  thanks a lot for your inputs. I am eagerly waiting for 0.12 release. When can we expect 0.12? can you please let us know ETA for 0.12 ?

**Comment by shankarkc** [comment]
Can we at least get some beta version of this release to help us now?

**Comment by mildwonkey** [comment]
There will be a beta release, but it is not ready yet and I do not have a firm timeline for that, either. Sorry I can't give you a more definitive answer.

**Comment by teamterraform** [comment]
Hello!

Terraform 0.12.0 was released with the feature described above on May 22, so we're going to close this out now. If you have any follow-up questions about the feature, please feel free to start a topic on [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks!
