### ISSUE TITLE
terraform crashes at plan (not apply) with the opentelekomified openstack module

### ISSUE THREAD

**Issue by deknos** [hashicorp/terraform#18590]
```
$ terraform -v
Terraform v0.11.7
+ provider.openstack v1.7.0
```

### Terraform Configuration Files
my configuration files are in http://gbks.net/tf.zip (about 20kb size) without credentials of course :>
i use the opentelekom cloud plugin. i am not entirely sure if this is the right bugtracker or if i should go to opentelekomcloud plugin..

### Debug Output
after terraform init ; the call for terraform apply fails, the tracelogs for it are in http://gbks.net/tracelogs.zip

### Crash Output
crash.log is in the aforementioned http://gbks.net/tf.zip 

### Expected Behavior
i know that the configuration works. i did it at one time.

### Actual Behavior
crash
### Steps to Reproduce
0. use my config and have correct credentials for OTC
1. `terraform init`
2. `terraform apply`
3. crash comes.

### Additional Context
I use the opentelekomcloud

**Comment by deknos** [comment]
it crashes on plan! not apply

**Comment by mildwonkey** [comment]
Hi @deknos! I'm sorry you're having this problem. I will flag this issue so it gets moved to the opentelekomcloud provider repository.
