### ISSUE TITLE
Error finding Root Device Name for AMI

### ISSUE THREAD

**Issue by williamzoop** [hashicorp/terraform#18599]
### Terraform Version

```

...
Terraform v0.11.7

```

### Terraform Configuration Files

```hcl
...
resource "aws_launch_configuration" "zoopusers-lc" {
  name = "zoopusers-${var.environment}-${var.zoopusers_ami}"

  image_id = "${var.zoopusers_ami}"

  instance_type        = "${var.zoopusers_instance_type}"
  iam_instance_profile = "${var.zoopusers_instance_profile}"

  security_groups = [
    "${aws_security_group.zoopusers.id}",
    "${var.sg_ssh}",
    "${var.sg_services}",
  ]

  lifecycle {
    create_before_destroy = true
  }

  root_block_device {
    volume_type = "gp2"
    volume_size = "30"
  }
}

```

### Actual Behavior

[WARN] Error finding Root Device Name for AMI

**Comment by williamzoop** [comment]
This error starts when using AMI with large Identifiers. I have a pipeline creating one AMI with packer and using it as variable to terraform.
The strange thing is If I run in sequence terraform again, it works.

**Comment by blckct** [comment]
Probably issue with eventual consistency, try adding a short wait in the pipeline.
