### ISSUE TITLE
Terraform depends on multiple resources

### ISSUE THREAD

**Issue by rifaterdemsahin** [hashicorp/terraform#18598]
I do have an order and using _depends on._
A > B> C > D
A: Resource group ( **trn_stg_servicesv4** )
B: Network security group ( has depends on A )
C: App Service plan ( has depends on B )
D: App Service ( has depends on C )

Getting this error when I am trying to recreate resources from scratch 

* azurerm_app_service.esb: azurerm_app_service.esb: Error making Read request on AzureRM App Service Configuration "trnstgesb": web.AppsClient#GetConfiguration: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group '**trn_stg_servicesv4**' could not be found."

> Is there a way to declare multiple dependencies? Do we need that?

**Comment by mildwonkey** [comment]
Hi @rifaterdemsahin ,

`depends_on` takes a list of strings, so you can have multiple dependencies (documentation [here](https://www.terraform.io/docs/configuration/resources.html#depends_on)): 

```
depends_on = [ "azurerm_thing_1", "azure_rm_thing2" ] 
```

I'm not sure if that will answer your question - if it does not, please share more of you terraform configuration so we can take a look.
Thanks!

**Comment by rifaterdemsahin** [comment]
thanks mate

**Comment by mildwonkey** [comment]
I can close it for you, thanks for following up!
