### ISSUE TITLE
Error parsing .netrc file: "keyword expected; got method." when Heroku CLI is present

### ISSUE THREAD

**Issue by davidpelfree** [hashicorp/terraform#18610]
### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.30.0
```

### Terraform Configuration Files
```hcl
provider "aws" {
  access_key = "AWS_KEY"
  secret_key = "AWS_SECRET"
  region     = "us-east-1"
}

resource "aws_instance" "example" {
  ami           = "ami-2757f631"
  instance_type = "t2.micro"
}
```

### Debug Output
https://gist.github.com/davidpelfree/daf5d9288f90493f0008184bd0949d01#file-terraform-failure-with-heroku-cli

### Crash Output
N/A

### Expected Behavior
Parser of ".netrc" file should ignore unknown line starting with the command "method", which was created by Heroku CLI.

### Actual Behavior
Error message: 
```
Error installing provider "aws": Error parsing netrc file at "/home/userName/.netrc": line 4: keyword expected; got method.
```

### Steps to Reproduce
Add a line containing "method interactive" somewhere inside existing .netrc file.
See my .netrc file in the above gist link, in the comments. 

### Additional Context
Looks like this is because a too strict ".netrc" file parser library you use.

**Comment by apparentlymart** [comment]
Hi @davidpelfree! Sorry for this annoying behavior and thanks for reporting it.

It looks like the upstream library already has an issue for this in bgentry/go-netrc#1, including a comment from another Terraform user hitting the same problem you described here. I'm going to try to follow up on this upstream to see what path we might take to address this.

Thanks again for reporting this!

**Comment by bgentry** [comment]
Unless they are using the old, unsupported, outdated `hk` Heroku client, then it's not relevant to bgentry/go-netrc. The current Heroku CLI is here, which may be a useful place to start digging and/or report the issue: https://github.com/heroku/cli

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity and age.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
