### ISSUE TITLE
Feature request: Define separate tfstate files in code

### ISSUE THREAD

**Issue by natzert** [hashicorp/terraform#18628]
### Terraform Version
```
Any
```

### Terraform Configuration Files
```hcl
terraform {
  required_version = "0.11.7"
  backend "gcs" {
    bucket  = "tf-state"
    path    = "${var.environment}/terraform.tfstate"
    project = "my-project"
    credentials = "/local/path/to/credentials/${var.environment}.json"
  }
}
```

### Expected Behavior
It should be possible to define separate tfstate files in code. As far as I understand it, we cannot have a templated backend configuration like my code sample above because the interpolation engine is started after the backend is initialized. I believe workspaces would be ok but that is not enforceable in code.

It would be nice if we could take the risk out of the equation by either moving the interpolation engine forward in the startup procedure or by allowing workspaces to be defined in hcl.

### Actual Behavior
Without this ability, the only other way to do it (without using 3rd party tools) is to duplicate code.

**Comment by mildwonkey** [comment]
hi @natzert!
Thank you for the well-written feature request. This is something that has been requested several times, so I'm going to close this issue in favor of #13022 - please feel free to add your 👍 there! 
Thanks again!
