### ISSUE TITLE
Referencing another map 

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform#18622]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.30.0
```

### Terraform Configuration Files

```hcl
variable "common_map" {
  type        = "map"
  description = "used by other maps"
  default     = {}
}

variable "map1" {
  type        = "map"
  description = "map1"
  default     = {}
}

variable "map2" {
  type        = "map"
  description = "map2"
  default     = {}
}

common_map = {
    "value1" = "some value"
}
map1= "${var.common_map}"
map2= "${var.common_map}"

```

### Expected Behavior

The map1 and map2 should each be equal to common_map

### Actual Behavior

Terraform complains that map1 is a map, not a string

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

It is possible that the quotes are mistake, I tried other ways like map1={${var.common_map}} but nothing works.

**Comment by mildwonkey** [comment]
Hi @schollii! 

I'm sorry you've come across this issue - thank you for providing such a good example for reproduction. Terraform's type system (in versions 0.11 and earlier) is a but simplified. 

I believe your issue will be addressed when terraform 0.12 is released - [here's the blog post](https://www.hashicorp.com/blog/terraform-0-12-rich-value-types) detailing improvements to the type system.

Having said that, I had some luck with maps and locals that I hope might help your use case. In the example below, I assigned the value of `common_map` to a local variable: 

### main.tf
```hcl
variable "common_map" {
  type        = "map"
  description = "used by other maps"
  default     = {}
}

variable "map1" {
  type        = "map"
  description = "map1"
  default     = {}
}


locals {
  map2 = "{$var.common_map}"
}

output "map" {
  value = "${local.map2}"
}
```

### terraform.tfvars
```hcl
common_map = {
    "value1" = "some value"
}
```

### output
```bash
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

map = {$var.common_map}
```

I hope this helps!

**Comment by schollii** [comment]
OK thanks for the quick response, much appreciated. The creation of an output makes this less than ideal and would change other things. I will wait for 0.12. Meanwhile I have changed the .tf to use one map instead of 2 separate maps.

**Comment by mildwonkey** [comment]
Great schollii! 

The output was just to prove that it worked; you could use the local variable in place of your variable `map2`.
