### ISSUE TITLE
Terraform Registry error referencing wrong version in example URL link (adds extra `v` to SemVer)

### ISSUE THREAD

**Issue by rms1000watt** [hashicorp/terraform#18636]
## Steps to Reproduce

1. Go to: https://registry.terraform.io/modules/rms1000watt/serverless-tf/aws/0.2.4
2. Click: Examples > hello-world-go
3. Observe: Source URL (which looks like: github.com/rms1000watt/terraform-aws-serverless-tf/tree/v0.2.4/examples/hello-world-go)

Notice the SemVer in the url contains a `v` although the actual version tag is `0.2.4`

## Actual vs. Expected

Actual:

```
github.com/rms1000watt/terraform-aws-serverless-tf/tree/v0.2.4/examples/hello-world-go
```

Expected:

```
github.com/rms1000watt/terraform-aws-serverless-tf/tree/0.2.4/examples/hello-world-go
```

## Demo

![terraform-registry-version-bug](https://user-images.githubusercontent.com/11354884/43858297-812c093a-9b02-11e8-8abd-6377421f97fc.gif)

**Comment by apparentlymart** [comment]
Thanks for reporting this, @rms1000watt!

Indeed the registry tries to normalize the version tags here to support both forms but perhaps it's not keeping enough information around to generate the correct link URL here. We'll pass this on to the registry team to see what we can do about it.

In the mean time, probably best to stick with the `vX.Y.Z` form of tags, which is the canonical form the registry is expecting.

**Comment by apparentlymart** [comment]
Indeed it is intended that both work, and they do both work in the sense that the module can be imported, but probably they are getting normalized on import and then the normalized form being used to create that link, causing the broken behavior you saw. We'll see what the registry team has to say about this once they get to look!

**Comment by justincampbell** [comment]
This should now be fixed for new module versions published! Versions before the fix (~February 2019) may need to be resynced by the module owner for the links to become valid again.
