### ISSUE TITLE
why does this module fail to find the aws_instance

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#1863]
I feel like I might be overlooking a simple mistake, but I've been over this again and again and I am still getting confusing behavior.

Here is a simplifed version of the code I'm working with..

In one source file...
```
# salt master instance
resource "aws_instance" "master" {
    ...
}
```

..and in another file:

```
# defines an ASG with some other stuff for us
module "cluster-a" {
    ...
    user_data = <<END_USER_DATA
...
salt:
  minion:
    master: ${aws_instance.master.private_dns}
...
END_USER_DATA
```

This fails:

```
* Resource 'aws_instance.master' not found for variable 'aws_instance.master.private_dns'
```

If I drop the reference to the `aws_instance.master` resource, the error goes away and the salt master instance is first in the build plan. `tf graph` shows the instance near last, while the cluster is first. Is this spin off from #1178 or un-related?

While debugging, I found that I could put in a reference to another resource in the same file as the `aws_instance.master` resource, and the module was happy with that reference.

This made me curious.. could I add another instance with a reference to the `aws_instance.master`? I added:

```
resource "aws_instance" "foo" {
    key_name = "${aws_instance.master.private_dns}"
    ami = "${var.ami}"
    associate_public_ip_address = true
    instance_type = "t2.small"
    availability_zone = "${aws_subnet.mgmt-a.availability_zone}"
    security_groups = ["${aws_security_group.salt-master.id}"]
    subnet_id = "${aws_subnet.mgmt-a.id}"
} 
```

and `tf plan` is fine and happy with that reference, but not when provided to the module. I tested that with and without `depends_on = "aws_instance.master"`.

I first ran into the error with `0.4.x`, so I upgrade to `0.5.x`, but the problem persists.

**Comment by mitchellh** [comment]
Well, at least the error existed with 0.4.x. I've tagged it so we can look at it.

**Comment by ketzacoatl** [comment]
In case I was not clear, the error pasted above is from `0.5.x`. Either way, let me know if more information or testing it helpful!

**Comment by ketzacoatl** [comment]
This may be a duplicate of #1916, I will test to confirm. And the last comment above on versions was incorrrect (sorry!)

**Comment by mitchellh** [comment]
This is a dup of #1916 and its fixed

**Comment by ketzacoatl** [comment]
confirmed here too, sorry for the delayed reply!
