### ISSUE TITLE
Provide a terraform inspect command

### ISSUE THREAD

**Issue by chamilad** [hashicorp/terraform#18691]
### Current Terraform Version
```
Terraform v0.11.7
```

### Use-cases
External tools may require to analyze Terraform modules for inputs, outputs, module calls, and providers both in human and machine readable formats.

### Attempted Solutions
I have tried to parse `variable \"` declarations in a module, however this can be easily broken if certain conventions are not followed during module development. And the approach is rigid because (e.g.) when I want the provider information, I'm faced with another set of text file processing. This can be easily done by the Terraform CLI with the information it has.

### Proposal
Provide a `terraform inspect <folder>` functionality simliar to how Packer operates with it's [`inspect` command](https://www.packer.io/docs/commands/inspect.html).

This should output the following.
1. Variables. A `-v` flag could produce more information such as descriptions, default values, types etc.
2. Outputs. Same behaviour with a `-v` flag
3. Module calls 
4. Providers used

**Comment by mildwonkey** [comment]
Hi @chamilad !
In Terraform 0.12, you can use `terraform show -json` to inspect a plan or statefile, and [`terraform-config-inspect`](https://github.com/hashicorp/terraform-config-inspect) to inspect the contents of your terraform configuration files.

I am going to close this issue, but if you find these options insufficient for your needs please open a new feature request with any additional support information that shows why these do not meet your needs. Thank you!

**Comment by chamilad** [comment]
Thanks @mildwonkey ! IIUC `terraform config-inspect` does this trick.
