### ISSUE TITLE
Prompting for values even if default is defined

### ISSUE THREAD

**Issue by umeshksingla** [hashicorp/terraform#18702]
### Current Terraform Version

```
0.11.6
```

### Feature
Prompting for values even if default is defined. This will help to modify the values if the default is not right in your case but majority of cases. Right now, if a default value is present, there is no way of knowing if the option (ie variable) is configurable or not.

### Use-cases

Something like:

```
ssh_keyname:
    Enter a value (Press return to keep the default value of "mykey"):
```

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. 

We don't currently have any plans to change the interactive UX of input variables at this time, but we'll keep our eyes and ears open for other intersecting requests. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
