### ISSUE TITLE
Scaleway: the "scaleway_volume_attachment" takes forever 

### ISSUE THREAD

**Issue by vitaliy-zinchenko** [hashicorp/terraform#18709]
**Terraform Version**
terraform -v:

Terraform v0.11.7
+ provider.scaleway v1.5.1

**Affected Resource(s)**
scaleway_volume_attachment

**Terraform Configuration Files**

provider "scaleway" {
  organization = ""
  token        = ""
  region       = "ams1"
}

resource "scaleway_ip" "ip" {
  server = "${scaleway_server.test.id}"
}

resource "scaleway_server" "test" {
  name  = "test"
  image = "ca9a9340-92e8-4c5f-8ae1-423466f7ef30"
  type  = "C2S"
}

resource "scaleway_volume" "test" {
  name       = "test"
  size_in_gb = 50
  type       = "l_ssd"
}

resource "scaleway_volume_attachment" "test" {
  server = "${scaleway_server.test.id}"
  volume = "${scaleway_volume.test.id}"
}

**Debug Output**
https://gist.github.com/vitaliy-zinchenko/95d19dc8cfe797d5ca73ec5f79899b8c

**Expected Behavior**
I would expect to have a running server that got 1 additional volume assigned.
And server back to srunning state.

**Actual Behavior**
Server is stopped and the Terraform attaching volume forever.

/cc @nicolai86

**Comment by nicolai86** [comment]
Thanks for the bug report. I think This is fixed in #87 - but the branch is missing an approval from second reviewer. I’d be super happy if you’d try out the branch and see if it fixes this issue.

**Comment by nicolai86** [comment]
@vitaliy-zinchenko please open the issue on terraform-providers/terraform-provider-scaleway.

**Comment by vitaliy-zinchenko** [comment]
@nicolai86 created ticket: https://github.com/terraform-providers/terraform-provider-scaleway/issues/89

**Comment by mildwonkey** [comment]
I am going to close this issue since it was moved to the scaleway provider. Thanks!
