### ISSUE TITLE
Terraform should indicate which changes are impossible

### ISSUE THREAD

**Issue by inferiorhumanorgans** [hashicorp/terraform#1870]
Playing around with security groups a bit last night, and I guess there's no API for changing the name or description of a SG.  However if you change the description of an SG and run the plan and apply actions everything goes through without a hitch implying that it's possible to change the description.

**Comment by phinze** [comment]
Thanks for the report. We do have a mechanism for handling attributes that cannot be updated - Terraform sees changes to these attributes as forcing a recreate of the resource. So it was just an oversight not to turn that flag on for SG descriptions. Attached PR will fix that. :+1:
