### ISSUE TITLE
When count = 0, create minimal referenceable metadata

### ISSUE THREAD

**Issue by johnbarney** [hashicorp/terraform#18705]
### Current Terraform Version

```
0.11.7
```

### Use-cases

In the case where a resource or data block has a "count" of 0, I would like to call length() on that resource or data block and have it return 0.

```hcl
locals {
  peer_enabled = "${var.vpc_peer == "" ? 0 : 1}"
}

data "aws_vpc" "vpc_peer" {
  count = "${local.peer_enabled}"
  id    = "${var.vpc_peer}"
}

data "aws_route_tables" "peer_route_tables" {
  count  = "${local.peer_enabled}"
  vpc_id = "${var.vpc_peer}"
}

resource "aws_vpc_peering_connection" "vpc_peering_connection" {
  count       = "${local.peer_enabled}"
  peer_vpc_id = "${var.vpc_peer}"
  vpc_id      = "${aws_vpc.vpc.id}"
  auto_accept = true

  tags {
    Name = "VPC Peering generated by Terraform"
  }
}

resource "aws_route" "peer_to" {
  count                     = "${local.peer_enabled ? 0 : length(local.aws_azs)}"
  route_table_id            = "${aws_route_table.private_route.*.id[count.index]}"
  destination_cidr_block    = "${data.aws_vpc.vpc_peer.cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.vpc_peering_connection.id}"
}

resource "aws_route" "peer_from" {
  count                     = "${length(data.aws_route_tables.peer_route_tables.id)}"
  route_table_id            = "${data.aws_route_tables.peer_route_tables.*.id[count.index]}"
  destination_cidr_block    = "${aws_vpc.vpc.cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.vpc_peering_connection.id}"

  #depends_on = ["aws_vpc_peering_connection.vpc_peering_connection"]
}
```

In the case above, if the variable of vpc_peer is not set the aws_route.peer_from will not be able to compute the number of resources to be created.

### Attempted Solutions

The commented out "depends_on" was an attempt to solve this issue.

### Proposal

Allow resources and data blocks to create enough metadata to be referenced even when the count is 0.

### References

N/A

**Comment by johnbarney** [comment]
That makes sense, and it's great to hear we are getting 'for each' and better handling of nested lists soon! I went through so many permutations trying to make this code work that it doesn't surprise me that I made a mistake in the code I posted.

My reason for asking for the feature is due to my perceived violation of least surprise. When I do:

```ruby
list = []
```

in Ruby or Python will result in an array object with a count of 0.

I understand that to some extent the concept of least surprise is subjective. If you guys decide the feature doesn't fit the vision for the tool, then that's good enough for me.

I'll try your recommendation above and I believe that should work for my needs. I do not expect the list of peers to change often.

Thanks!
John

**Comment by apparentlymart** [comment]
Hi @johnbarney,

I think the subtlety in your case here is that the result here is a _list of lists_ rather than a single list. Building on your Python example:

```
# simulating count = 1 as Terraform 0.11 interprets it
>>> l = ["rtb-abc123", "rtb-def456"]
>>> len(l)
2
>>> l[0]
'rtb-abc123'

# simulating count = 1 as Terraform 0.12 will interpret it
>>> l = [["rtb-abc123", "rtb-def456"]]
>>> len(l)
1
>>> l[0]
['rtb-abc123', 'rtb-def456']
>>> l[0][0]
'rtb-abc123'

# simulating count = 0 as both Terraform 0.11 and 0.12 interpret it
>>> l = []
>>> len(l)
0
>>> l[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

I think the "surprising" part of the behavior here is that Terraform 0.11 treats `count = 1` as a special case, making it not produce a list at all. Terraform 0.12 will address that by making `count = 1` produce a list with one element. A single object (non-list) will be produced only if `count` isn't present _at all_, thus allowing you to write the sort of conditional you're doing here without needing to contend with that `count = 1` special case.

**Comment by jbardin** [comment]
Closing as we now have the ability to properly evaluate these expressions, and also have the option of `for_each` for resources.

Thanks!
