### ISSUE TITLE
Issue using main.tf at top level to manage infra

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/terraform#18716]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
I hava an example project with this structure:

devel
  ├── data-storage
  ├── services
           └── backend-app
                      └── rabbitmq

inside rabbimq dir:

main.tf (rabbitmq dir)
module "name" {
  source = "git::http://url/modulename?ref=v1.1.0"
  ...
  vsphere_user           = "${var.vsphere_vcenter_usr}"
  vsphere_pwd           = "${var.vsphere_vcenter_pwd}"
  ...
}

vars.tf (rabbitmq dir)
variable "vsphere_vcenter_usr" {}
variable "vsphere_vcenter_pwd" {}

Module code:
main.tf (modulename)
...
resource "vsphere_virtual_machine" "vm" {
...
password         = "${var.vsphere_pwd}"
user                 = "${var.vsphere_user}"
...
}

vars.tf (modulename)
...
variable "vsphere_user" {
  description = "vSphere user name"
}
variable "vsphere_pwd" {
  description = "vSphere password"
}
...

I tried an infra configuration, adding main.tf at devel level directory to
see if I can run devel infra grouping resources in a "super" main.tf.

main.tf (devel dir)
module "project_dev" {
  source = "./services/backend-app/rabbitmq"
}

```

### Expected Behavior

terraform init
  should work without issue using variables definitions in vars.tf (rabbitmq dir) and vars.tf (modulename)

terraform plan -var-file=secrets.tfvars
  should work whitout issue using variables declaration in secrets.tfvars

### Actual Behavior

running terraform init at devel directory I get:

Error: module "project_dev": missing required argument "vsphere_vcenter_usr"
Error: module "project_dev": missing required argument "vsphere_vcenter_pwd"

terraform init works if setting default values for every variables in vars.tf (rabbitmq dir)
  variable "vsphere_vcenter_usr" {default=""}
  variable "vsphere_vcenter_pwd" {default=""}

but also using default values as above, running
   terraform plan -var-file=secrets.tfvars
does not read variables from -var-file, using defaults and returning invalid credentials connecting to the provider.

### Steps to Reproduce

At devel directory run:

1. terraform init 
2. terraform apply -var-file=secrets.tfvar

**Comment by mildwonkey** [comment]
It looks like you need to explicitly pass we variables to your module in the source block :

```hcl
module "project_dev" {
  source = "./services/backend-app/rabbitmq"
   vsphere_vcenter_pwd = ${var. vsphere_vcenter_pwd} 
 ... 
}
```[

**Comment by Roxyrob** [comment]
Yes, but this solution is inflexible as it isn't possible to compose with "super" main.tf different scenarios using modules mechanism without to go "inside" each apps and centralizing/duplicating code in "super" main.tf

**Comment by mildwonkey** [comment]
I think I see where you're going; I'm going to try and rephrase your request - let me know if I've got it right or not, please!

You would like to use modules with terraform, and want terraform to automatically pull values from `terraform.tfvars` (or wherever your variables are) into your modules without needing to explicitly pass those variables from `main.tf` to the module? 

So, from your example above, terraform would automatically pull `vsphere_vcenter_pwd` from `secrets.tfvar` even though you didn't include the variable in the module block.

Did I get that right? (and I definitely see the appeal)

**Comment by Roxyrob** [comment]
Yes, I explain better...

I already use modules in the "normal way". As you can see base playbook (rabbitmq: main.tf + vars.tf) uses a module (modulename: main.tf + vars.tf). Here I declared variables and I can run terraform init/plan/apply on rebbitmq directory passing a secrets file without problem.

After some coding, resources of the infrastructure grew, so the need to testing a different way, using a main.tf to magane some (or all) the resources using a single main.tf (a kind of includes inside a super main.tf). I read following post:

https://github.com/hashicorp/terraform/issues/8404

where @apparentlymart show a solution for a similar problem. I thought with something like that it'll be possible, using module mechanism as explained. I did not find other mechanisms to terraform plan/destroy many resource at once (at least without running scripts or running single terreform commmands for every subdirectory of each single resource).

terraform executed in devel directory does not pull "vsphere_vcenter_pwd" from secrets.tfvar.

(Also the need to define default values for variables to avoid error seems an issue)

**Comment by mildwonkey** [comment]
I'm going to close this issue in favor of #18391 and/or #15818 , both of which address variables for modules and have longer discussions. Please add your 👍 to those issues!
