### ISSUE TITLE
Add a "Good first issue" label 

### ISSUE THREAD

**Issue by ms4720** [hashicorp/terraform#18749]
### Current Terraform Version

```
...
```

### Proposal

tag issues that would be a good place to start as "Good first issue" or something similar to make it easier to get people involved.

**Comment by vishleshpatel** [comment]
I have been looking at issues in the repo. This - "good first issue" or "help wanted" - both are really great labels to have. It would be nice to see them in terraform.

**Comment by pselle** [comment]
This label now exists! 

https://github.com/hashicorp/terraform/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Of course, it'll be more useful once we improve on triaging issues into that label, but we've got the first step! Thanks for advocating for this change @ms4720
