### ISSUE TITLE
Crash with AWS EIP resource

### ISSUE THREAD

**Issue by jasonkeene** [hashicorp/terraform#1876]
I was going through the [getting started guide](https://www.terraform.io/intro/getting-started/dependencies.html) with AWS and started getting crashes when I added the elastic IP resource:

https://gist.github.com/jasonkeene/bad3cd7b5b616cfcf40c

I thought it might be permissions issue so I gave the IAM user admin rights, destroy -> plan -> apply and it still crashed.

Also, not sure why stack trace has /Users/mitchellh/... paths.

**Comment by catsby** [comment]
Thanks for reporting this @jasonkeene – I'm taking a look now

**Comment by catsby** [comment]
Going to fold this into #1666

**Comment by catsby** [comment]
Maybe not... they may be different. Still looking

**Comment by catsby** [comment]
Talked with @jasonkeene and confirmed that this is fixed in 0.5.0, so closing this. Thanks again!
