### ISSUE TITLE
User_data not working while creating instances

### ISSUE THREAD

**Issue by Chrisjerry9618** [hashicorp/terraform#18772]
Hi, 

I am trying to add user_data to my instance, which involves in adding httpd and java packages during the machine creation. 

But it is not happening.

**Comment by asvinours** [comment]
Hi,

Could you provide more information on how you did the setup for your user data in the terraform template?
Did you look at the cloud init log file in the EC2 instance after the boot? (/var/log/cloud-init-output.log)


Thanks,
