### ISSUE TITLE
Terraform plan doesn't pick up resource from state

### ISSUE THREAD

**Issue by moxli** [hashicorp/terraform#18780]
### Terraform Version
```
Terraform v0.11.8
+ provider.external v1.0.0
+ provider.google v1.17.1
+ provider.kubernetes v1.2.0
+ provider.mysql v1.1.0
```

### Terraform Configuration Files

I don't think this issue has anything to do with the .tf files.

```hcl
module "cloud-sql" {
  source = "../../modules/gcloud/cloud-sql-instance"

  name             = "${var.prefix}-mysql"
  region           = "${var.region}"
  tier             = "${var.db_tier}"
  disk_size        = "${var.db_disk_size}"
  flags            = "${var.mysql_flags}"
  maintenance_day  = "${var.maintenance_day_master}"
  maintenance_hour = "${var.maintenance_hour_master}"
}

module "cloud-sql-failover" {
  source = "../../modules/gcloud/cloud-sql-instance"

  name             = "${var.prefix}-mysql-failover"
  region           = "${var.region}"
  tier             = "${var.db_tier}"
  disk_size        = "${var.db_disk_size}"
  flags            = "${var.mysql_flags}"
  maintenance_day  = "${var.maintenance_day_failover}"
  maintenance_hour = "${var.maintenance_hour_failover}"

  failover_node        = true
  master_instance_name = "${module.cloud-sql.name}"
}
```

### Debug Output
What would be the best way to sent you a gpg encrypted debug file?

### Expected Behavior
Terraform reads the state file properly and doesn't create new resources.

### Actual Behavior
Terraform plan shows creation of two new database instances even though they already exist in the cloud and in state.

### Additional Context
How this all happenend:

I have had a infrastructure  that I put inside a module (doccreator) to streamline deployment of multiple environments. Because one environment (testing) was already setup I had to manually move the entries inside our remote state file to the new module path like so:
```
terraform state mv kubernetes_namespace.namespaces module.doccreator.kubernetes_namespace.namespaces
```
I did that to all resources including the databases.

terraform state list shows the following:
```
module.doccreator.module.cloud-sql-failover.google_sql_database_instance.mysql
module.doccreator.module.cloud-sql.google_sql_database_instance.mysql
```
terraform plan shows the following:
```
google_sql_database_instance.mysql: Refreshing state... (ID: pre-prd-mysql-failover)
google_sql_database_instance.mysql: Refreshing state... (ID: pre-prd-mysql)
...
 + module.doccreator.module.cloud-sql-failover.google_sql_database_instance.mysql
  + module.doccreator.module.cloud-sql.google_sql_database_instance.mysql
```
Terraform tries to recreate the database instances without even noticing that they already exist.

I already tried deleting the entries from state using terraform state rm and importing the instances from google cloud with import however plan / apply still does not pick them up.
```
 terraform show | grep google_sql
module.doccreator.cloud-sql.google_sql_database_instance.mysql:
module.doccreator.cloud-sql-failover.google_sql_database_instance.mysql:
```

I don't know what will happen if I run terraform apply, but I can't test that against this infrastructure right now.

**Comment by mildwonkey** [comment]
Hi @moxli, I'm sorry you've run into this problem. Hopefully we can help you figure out why terraform is trying to create something that appears to be in state.  

It's easiest if you can send the debug file as a gist, scrubbing any sensitive information. I'd also like some more information about your backend configuration and the exact commands you are running for terraform plan/apply.

**Comment by moxli** [comment]
@mildwonkey 
Thanks for your answer. I will try to scrub the infos from the debug output.
Do you need debug or trace log level? 

My backend config looks like this:
```hcl
terraform {
  backend gcs {
    bucket = "cs-terraform-state"
    prefix = "doccreator-pre-prd"
    # explicitly configured to an invalid encryption key so that storing the
    # state will fail if terraform was initialized without setting the encryption
    # key
    encryption_key = "dummy"
  }
}
```
I use googles cloud key service to store the encryption key for the state.

Init:
```
terraform init -backend-config="encryption_key=$(sops -d --extract '["terraform-state-gcs-encryption-key"]' passwords.json)"
```

Plan/apply run as usual with no extra parameters.

**Comment by renaldrozario** [comment]
We are facing the same issue with consul as the remote state. Really running nuts around without no solution. Any help would be much appreciate and will be beneficial for wider audience.

https://github.com/hashicorp/terraform/issues/18939

**Comment by autotune** [comment]
I was able to replicate this with the following simple config on version 0.11.0:

cloudsql.tf:

`resource "google_sql_database_instance" "master" {
  name = "master-instance-1"

  settings {
    tier = "db-f1-micro"
  }
}

resource "google_sql_database" "users" {
  name      = "users-db"
  instance  = "${google_sql_database_instance.master.name}"
}`

backend.tf:
`
terraform {
  backend gcs {
    bucket = "foo"
    prefix = "bar"
  }
}`

looks like the apply tries to run every time even if no changes.

**Comment by moxli** [comment]
I think I am facing a similar problem on another project.
I have two database instances up and running(one leader/master with one failover attached to it). Both database instances are created from the same terraform module.

I am trying to update the db_tier of both instances. To achieve this I have added a variable called db_tier which is set to 'db-n1-standard-2'.

I think this picture sums up the problem quite well:

![screenshot from 2019-02-26 15-30-23](https://user-images.githubusercontent.com/26149616/53420874-e8a18a80-39dc-11e9-838d-92fbd9fa2390.png)

Terraform can apparently update the failover database instance but it does not pick up leader instance from state correctly.

If I try to execute the apply it tries to delete the database instance 'module.fsl.module.cloud-sql.google_sql_database_instance.mysql' which fails because it's not possible to delete a leader instance which has a failover attached to it. I would probably try to recreate the database after the deletion which is also not acceptable because the name of a deleted database instance can not be reused for ~7 days. 

**This means that the plan / apply output is actually incorrect**. It does not represent what Terraform actually does afterwards.

`Plan: 1 to add, 2 to change, 0 to destroy.
`
This could be a fundamental problem and is really dangerous.

I am not sure if both problems have something todo with each other or if I should open a new issue with the google provider for the 1st one?

**Comment by exNewbie** [comment]
I have a similar issue. 
```
$ terraform -version
Terraform v0.11.13
+ provider.aws v2.2.0
```

I manually added a rule to Network ACLs
![image](https://user-images.githubusercontent.com/14102056/54475839-0fb3e500-4842-11e9-87a9-944d32eac1ba.png)

Running **_show_**, it detects that change
```
$ terraform show | grep  1194
  ingress.2715061438.from_port = 1194
  ingress.2715061438.to_port = 1194
```

However, running **_plan_** or **_apply_** returns "No changes. Infrastructure is up-to-date."

**Comment by saidmasoud** [comment]
Hello,

Not sure if 0.11 is still being supported or not with the release of 0.12, but we have also encountered this issue with version 0.11.14. We addressed it by removing the resources from the state store, them importing them back in.

**Comment by laur1s** [comment]
Hello,

I've encountered the same bug in Terraform v0.12.24 and v0.12.26. I can see the resource in s3 state file:
`{
  "version": 4,
  "terraform_version": "0.12.24",
  "serial": 1,
  "lineage": "xxxxx",
  "outputs": {},
  "resources": [
    {
      "module": "module.s3",
      "mode": "managed",
      "type": "aws_kms_alias",
      "name": "s3",
      "provider": "provider.aws",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:kms:eu-central-1:xxxxx",
            "id": "alias/dev/s3",
            "name": "alias/dev/s3",
            "name_prefix": null,
            "target_key_arn": "arn:aws:kms:eu-central-1:xxxxx",
            "target_key_id": "xxxxx"
          },
          "private": "xxxxxx",
          "dependencies": [
            "module.s3.aws_kms_key.s3"
          ]
        }
      ]
    },`

However, terraform wants to create the whole module:

`
n execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.s3.aws_s3_bucket.xxx will be created
  + resource "aws_s3_bucket" "xxx" {
`

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.

**Comment by wsams** [comment]
For what it's worth @danieldreier , I ran into this exact same problem with 0.14.1 and 0.14.10.

**Comment by wsams** [comment]
> For what it's worth @danieldreier , I ran into this exact same problem with 0.14.1 and 0.14.10.

I should also say that half of my team gets the correct plan output, and the other half (including Atlantis) sees the resources being created. We spent the entire day today trying to figure this out with no luck.

If I run `terraform state list` or `terraform state show $address` I see the same resources that the people with correct plan output see.
