### ISSUE TITLE
Better error message when authentication with Service Account Credentials fails

### ISSUE THREAD

**Issue by MaxBinnewies** [hashicorp/terraform#18796]
Hi,

I am new to Terraform. To get started I just tried to deploy a simple Compute Engine with the help of a tutorial. I got stuck for hours on a misleading error message. The actual problem turned out to be a stupid copy+paste error of mine that prevented the credentials from being read. I was hoping that the error message can be improved.

These are my scripts:

```
# Specify the provider (GCP, AWS, Azure)
provider "google" {
#credentials = "terraform-account.json"
project = "agile-producer-187500"
region = "australia-southeast1"
}
```

```
	# Create a new instance
resource "google_compute_instance" "ubuntu-xenial" {
   name = "ubuntu-xenial"
   machine_type = "f1-micro"
   zone = "australia-southeast1-b"
   boot_disk {
      initialize_params {
      image = "ubuntu-1604-lts"
   }
}
network_interface {
   network = "default"
   access_config {}
}
service_account {
   scopes = ["userinfo-email", "compute-ro", "storage-ro"]
   }
}
```

And I got this error message:
```
google_compute_instance.ubuntu-xenial: Error loading zone 'australia-southeast1-b': googleapi: Error 403: Required 'compute.zones.get' permission for 'projects/agile-producer-187500/zones/australia-southeast1-b', forbidden
```

as you can see "Credentials" is actually commented out due to a mix-up in copying from the tutorial, but I didn't realise that and spent hours chasing a non-existing permissions issue relating to zones in GCP. I think the error message is very misleading here, as I assumed authentication with GCP had worked fine as I was getting a GCP error message relating to the project.
Can you introduce a specific error message when authentication with GCP through the service account credentials fails?

I assume this is a terraform issue rather than a provider issue, because the provider couldn't even be contacted due to the lack of auth. 

### Current Terraform Version

```
Terraform v0.11.8
+ provider.google v1.17.1
```

### Use-cases

Anytime, anything with authentication to the cloud vendor fails.
The credentials accidentally commented out might be rare, but users might just forget to put them in in the first place.

### Proposal

Return a more appropriate error message that informs the user that authentication with credentials has failed.

**Comment by pkolyvas** [comment]
I'm going to close this issue based on age and community engagement. 

I do think Terraform has a fine line to walk here where we're agnostic to the issues related to how/why a given provider is authorized. Of course it's easy to pass off the issue to say "well Google should have have better API messages." The reality is probably somewhere in between. Providing clear, actionable feedback is paramount to success and I'm sorry this caused such a time sink.

I'll keep an eye out for more use cases like this and appreciate you take the time to share your insight with us. We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
