### ISSUE TITLE
uuid() generates UUID with incorrect version fields

### ISSUE THREAD

**Issue by jonjhallettuob** [hashicorp/terraform#18808]
### Terraform Version

```
Terraform v0.11.8
+ provider.aws v1.35.0
```
### Terraform Configuration Files

main.tf:
```
output "uuid" {
  value = "${uuid()}"
}
```
### Expected Behavior

Terraform should output a RFC 4122 v4 UUID, as documented.

>uuid() - Returns a UUID string in RFC 4122 v4 format. This string will change with every invocation of the function, so in order to prevent diffs on every plan & apply, it must be used with the ignore_changes lifecycle attribute.

### Actual Behavior

Terraform outputs a UUID which doesn't encode the correct RFC 4122 v4 version information, for example,

```
$ terraform.exe apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

uuid = 198f0843-9765-a55e-6858-47db8a789ef3
```

In the example, the `time_hi_and_version` field is `a`. It should be `4`. The top two bits of the `clock_seq_hi_and_reserved` field are also incorrect.

### Steps to Reproduce

`terraform apply`

**Comment by saravanan30erd** [comment]
@mildwonkey I ll work on this issue.

**Comment by saravanan30erd** [comment]
@mildwonkey looks like we are using `hashicorp/go-uuid` to generate uuids and it is not intended to be RFC compliant, so we need to either create new func with RFC compliant(v4) or just update the documentation. I am happy to work on both cases, please share your thoughts?

**Comment by mildwonkey** [comment]
@saravanan30erd: great catch, thank you. I checked with the rest of the core team and we feel that updating the documentation is the correct step (at least at this time). `hashicorp/go-uuid` is heavily used in tools such as vault and we'd prefer to avoid modifying it.

**Comment by saravanan30erd** [comment]
@mildwonkey thanks, submitted my first PR.

**Comment by jonjhallettuob** [comment]
For what my opinion is worth, updating the documentation looks like a proportionate, pragmatic fix for this issue.
