### ISSUE TITLE
Increase transparency for issue #953

### ISSUE THREAD

**Issue by aneagoe** [hashicorp/terraform#18809]
There's little over a year without any update on issue #953 
The issue doesn't seem to be assigned to anyone and there's no apparent progress on this. It was also locked, so commenting on it is disabled. It would be great if someone could try to give a few updates every now and then so people know what to expect and have a better understanding on how things are prioritized.

**Comment by mildwonkey** [comment]
Hi @aneagoe,

I'm sorry that there's been silence on that particular issue; it's difficult to keep up with all of these issues and their duplicates! The terraform core team has been heads down working on the [0.12 release](https://www.hashicorp.com/blog/terraform-0-1-2-preview) which sets a foundation for counts in modules (it will not be in the initial release). 

We're trying hard to be open and communicative and again, I'm sorry for that. 

I do recommend keeping an eye on the terraform blog, where we cover many of the 0.12 changes, and we will communicate more about that release and the issues it will resolve once we have more information.
