### ISSUE TITLE
Terraform 0.12 version

### ISSUE THREAD

**Issue by kolxd** [hashicorp/terraform#18839]
Hello,

I was wondering when will the 0.12 version be available (even beta). I went through all the blog posts and I am really thrilled about the new capabilities of HCL. In one of these posts, a release date for the end of summer was specified but it somehow got delayed. 
Do you have any information about when this new version will be available?

Thank you!

**Comment by mildwonkey** [comment]
Hi @kolxd,
Unfortunately we (still) do not have a firm release date at this time - any updates will be posted to the blog. 
I'm sorry I couldn't give you a more specific answer; we'd love to be able to promise a timeline but the changes are a huge undertaking and taking longer than expected.
Cheers!

**Comment by 007** [comment]
Is there any way to track the status of 0.12 beyond the 100% opaque "watch for a blog post"? Something like a milestone, or a tag that needs to have its tickets resolved?

**Comment by nvtkaszpir** [comment]
Just check this url from time to time https://github.com/hashicorp/terraform/milestone/5

**Comment by bohdanyurov-gl** [comment]
For anyone tracking this issue: v0.12.0-beta2 has been released!
https://github.com/hashicorp/terraform/releases/tag/v0.12.0-beta2

**Comment by bohdanyurov-gl** [comment]
@007, @kolxd  Terraform 012 has been released:
https://www.hashicorp.com/blog/announcing-terraform-0-12
