### ISSUE TITLE
Documentation vs actual discrepancy - data vs resource for aws_rds_cluster

### ISSUE THREAD

**Issue by TheBeege** [hashicorp/terraform#18847]
### Terraform Version
```
>terraform version
Terraform v0.11.8
+ provider.aws v1.35.0

```

### Terraform Configuration Files
```hcl
data "aws_rds_cluster" "db" {
  cluster_identifier = "db"
}

resource "aws_lambda_function" "func" {
  function_name = "func"
  handler       = "index.handler"
  role          = "${aws_iam_role.role.arn}"
  runtime       = "nodejs8.10"

  filename         = "lambda_functions/function.zip"
  source_code_hash = "${base64sha256(file("lambda_functions/function.zip"))}"

  environment {
    variables = {
      DATABASE_HOST     = "${data.aws_rds_cluster.db.endpoint}"
      DATABASE_SCHEMA   = "${data.aws_rds_cluster.db.database_name}"
      DATABASE_SSM_PATH = "/db"
    }
  }
}
```

### Expected Behavior
Per documentation, expected database name to be substituted without issue.
Per https://www.terraform.io/docs/providers/aws/d/rds_cluster.html, "See the RDS Cluster Resource for details on the returned attributes - they are identical."

### Actual Behavior
Terraform does not recognize `database_name` as an attribute: 
```
aws_lambda_function.func: Resource 'data.aws_rds_cluster.db' does not have attribute 'database_name' for variable 'data.aws_rds_cluster.db.database_name'
```

### Steps to Reproduce
1. Create RDS MySQL Aurora cluster in AWS console
2. Create Terraform data item for cluster
3. Reference database_name on data item within another resource

**Comment by TheBeege** [comment]
Sorry, my mistake. The database was created without a database name being set, so there is no attributed for Terraform to read.

**Comment by kenorb** [comment]
I've got the same error on `destroy`, but my database doesn't exist at all.

```
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error(s) occurred:

* local.environment_json: local.environment_json: Resource 'aws_rds_cluster.myproject_database' does not have attribute 'database_name' for variable 'aws_rds_cluster.myproject_database.database_name'
```

**Comment by TheBeege** [comment]
@kenorb You have some local defined called `environment_json` there's referencing the database name. Try commenting that out before calling destroy
