### ISSUE TITLE
Typo in terraform zsh autocompletion page

### ISSUE THREAD

**Issue by bfarayev** [hashicorp/terraform#18867]
Double hyphens should be used in these two commands in zsh-completion page:
https://github.com/hashicorp/terraform/tree/master/contrib/zsh-completion

Commands should be:

```
terraform --install-autocomplete
terraform --uninstall-autocomplete
```

instead of 
```
terraform -install-autocomplete
terraform -uninstall-autocomplete
```

**Comment by mildwonkey** [comment]
Hi @bfarayev!
These commands work as written on my system - we're using the golang [`flag`](https://golang.org/pkg/flag/) package. Are you getting an error?

**Comment by bfarayev** [comment]
@mildwonkey you're right. it's working as expected with install-autocomplete flag. In fact, I'm getting expected behavior with one and two hyphens 

```
  ~  terraform -install-autocomplete
  ~  terraform -install-autocomplete
Error executing CLI: 1 error(s) occurred:

* already installed in /Users/bakhtiyar/.zshrc
```

This is fine as it's already installed after the first command. Trying now with double hyphens:

```
  ~  terraform -uninstall-autocomplete
  ~  terraform --install-autocomplete
  ~  terraform --install-autocomplete
Error executing CLI: 1 error(s) occurred:

* already installed in /Users/bakhtiyar/.zshrc
```

Issue can be closed as there's no change needed
