### ISSUE TITLE
Empty lists being encoded as JSON object

### ISSUE THREAD

**Issue by com6056** [hashicorp/terraform#18865]
Terraform version: 0.11.3

I am trying to create some JSON from 2 lists as such:
```
value = "${jsonencode(map("foo", var.foo, "bar", var.bar))}"
```

The default values are just empty lists:
```
variable "foo" {
  type    = "list"
  default = []
}

variable "bar" {
  type    = "list"
  default = []
}
```

If I don't define them and let them be the default, the resulting JSON doesn't have empty lists, but rather empty objects:
```
{\"foo\":{},\"bar\":{}}
```

**Comment by apparentlymart** [comment]
Hi @com6056! Sorry for this weird behavior, and thanks for reporting it.

We've recently been working on some significant changes to the configuration language engine within Terraform and so I checked this against the v0.12.0-alpha2 prerelease build to see how things have changed:

```hcl
variable "foo" {
  type    = "list"
  default = []
}

variable "bar" {
  type    = "list"
  default = []
}

output "x" {
  value = "${jsonencode(map("foo", var.foo, "bar", var.bar))}"
}
```

This now appears to work as expected:

```
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

x = {"bar":[],"foo":[]}
```

This fix is in the master branch and ready to be included in the forthcoming v0.12.0 release, so I'm going to close this out. Thanks again for reporting this!
