### ISSUE TITLE
git clone over SSH fails for modules hosted in Azure Repos

### ISSUE THREAD

**Issue by rlacherksu** [hashicorp/terraform#18869]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
module "sql_server" {
  source = "git::ssh://git@ssh.dev.azure.com:v3/rlacher/Test/Test"
}
```

### Debug Output

[Gist](https://gist.github.com/rlacherksu/d13249695029f3cbee30a10445e59918)

### Expected Behavior

Clone remote Azure Repos repository.

### Actual Behavior

Clone failed.

### Steps to Reproduce

1. `terraform init`

### Additional Context

Terraform is running in the Azure Cloud Shell in this example. Also tested with local Ubuntu 16.04 installation on the same Terraform version.

I'm able to successfully clone the repo using the same URL with `git clone` on both systems. 

### References

- #18566
- #18541

**Comment by rlacherksu** [comment]
Any idea when this will be addressed? We’d like to use Azure Devops with Terraform but this has been a major blocker.

**Comment by tbondal** [comment]
We are also struggling with this
Tested with Terraform v0.11.10 on both windows 10 and MacOS 10.14

**Comment by paultyng** [comment]
I believe this code just wraps [go-getter](https://github.com/hashicorp/go-getter) which is just executing `git` behind the scenes. Going to try to simulate this myself and see where the problem is (url format, go-getter, Terraform, etc.).

**Comment by tbondal** [comment]
I just tested and it works for me as well- unfortunately I did not think about trying this... (changing : to /)

Thanks!

//tbondal

**Comment by rlacherksu** [comment]
Worked for me as well! Thank you very much.

**Comment by psandhu79** [comment]
Is there an example of this usage in azure-pipelines.yml
