### ISSUE TITLE
Provider aliases not inheriting attributes from parent

### ISSUE THREAD

**Issue by c6fc** [hashicorp/terraform#18872]
### Terraform Version

```
Terraform v0.11.8
+ provider.aws v1.36.0
```

### Terraform Configuration Files

```hcl
variable access_key {}
variable secret_key {}

provider "aws" {
	access_key = "${var.access_key}"
	secret_key = "${var.secret_key}"
	region     = "us-west-2"
}

provider "aws" {
	alias  = "west_1"
	region = "us-west-1"
}

resource "aws_vpc" "west_2" {
	cidr_block = "10.204.0.0/16"
}

resource "aws_vpc" "west_1" {
	provider = "aws.west_1"
	cidr_block = "10.203.0.0/16"
}
```

### Expected Behavior
Expected 'access_key' and 'secret_key' from 'aws' provider to be inherited by the 'aws.west_1' alias, as inferred by the documentation here: https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances

### Actual Behavior
aws_vpc.west_2 was created with the credentials supplied in the variables, while aws_vpc.west_1 was created using credentials derived from .aws/credentials default account.

### Steps to Reproduce

1. Populate the auth variables for the above config file
2. Populate .aws/credentials [default] profile with alternate account credentials
3. `terraform init`
4. `terraform apply`
5. Observe that both VPCs are created successfully, but only aws_vpc.west_2 is created in the specified account.

**Comment by mildwonkey** [comment]
Hi @c6fc !
Thanks for opening this, and I'm sorry for any confusion. The behavior is expected - a provider alias will not inherit anything from another provider - so I'll label this as a documentation issue.

**Comment by tmccombs** [comment]
Maybe this should be a feature request to have a way for one provider to inherit from another? 

I'd like to be able to create a provider for a different aws region without having to copy all of the other configuration from my default aws provider.

Perhaps something like:

```
provider  "aws" {
  alias = "west"
  inherits_from = "aws"
  region = "us-west-2"
}

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. We've since updated the module documentation to go into depth on provider configuration inheritance.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
