### ISSUE TITLE
provider.random: no suitable version installed when using uuid()

### ISSUE THREAD

**Issue by ophintor** [hashicorp/terraform#18882]
Version 0.11.8

I don't have any random resources in my terraform files but since I added the following code I get the error below:

**new code**
```
resource "null_resource" "build_node_modules" {
  triggers {
    rebuild_again_please = "${uuid()}"
  }
...
}
```
**error**
```
1 error(s) occurred:

* provider.random: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
```

I've run a terraform init and tried to download all providers but error persists.

I fixed it by adding a simple random resource:

```
resource "random_pet" "rebuild_again_please" {}
```

I believe when using only `uuid()` without any other random resource, terraform does not detect that it needs to download the random provider.

**Comment by mildwonkey** [comment]
Hi @ophintor !

I'm sorry you ran into this. I tried to reproduce it using just the configuration below and it worked fine, so I'm not sure where the message about random was coming from. 

```hcl
resource "null_resource" "build_node_modules" {
  triggers {
    rebuild_again_please = "${uuid()}"
  }
}```

Were there any additional terraform configuration files in the working directory you could share?

**Comment by ophintor** [comment]
There are a bunch of other files, which all together make a module. Not sure if being part of a module would have any influence? I'll paste the file that was giving me the error if that helps:

Note --> I tried also `timestamp()` with the same result. Again, adding a random resource fixed it.

```
resource "random_pet" "rebuild_again_please" {}

resource "null_resource" "build_node_modules" {
  triggers {
    rebuild_again_please = "${timestamp()}"
  }

  provisioner "local-exec" {
    command     = "npm install aws4 request request-promise-native"
    working_dir = "${path.module}/${var.component}_src"

    environment {
      PATH = "/usr/bin:/usr/local/bin"
    }
  }
}

data "null_data_source" "zip_source" {
  inputs {
    filename = "${substr("${path.module}/${var.component}_src", length(path.cwd) + 1, -1)}"
  }
}

data "null_data_source" "zip_output" {
  inputs {
    filename = "${substr("${path.module}/${var.component}_zip/lambda.zip", length(path.cwd) + 1, -1)}"
  }
}

data "archive_file" "lambda_code" {
  type        = "zip"
  source_dir  = "${data.null_data_source.zip_source.outputs.filename}"
  output_path = "${data.null_data_source.zip_output.outputs.filename}"
  depends_on  = ["null_resource.build_node_modules"]
}

resource "aws_lambda_function" "reporting_service" {
  filename         = "${data.archive_file.lambda_code.output_path}"
  function_name    = "${var.component}_function_${terraform.workspace}"
  description      = "Service Finder ${replace(var.component,"_"," ")}"
  role             = "${aws_iam_role.assume_role_lambda.arn}"
  handler          = "${var.handler}"
  source_code_hash = "${data.archive_file.lambda_code.output_base64sha256}"
  runtime          = "nodejs8.10"
  timeout          = 10

  lifecycle {
    ignore_changes = ["last_modified"]
  }

  environment {
    variables = {
      ELASTICSEARCH_ENDPOINT = "${var.elasticsearch_endpoint}"
    }
  }
}

resource "aws_lambda_permission" "allow_api_gateway_query_events" {
  statement_id  = "AllowQueryandReceiveEventsAPIInvoke"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.reporting_service.arn}"
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_api_gateway_deployment.reporting_service.execution_arn}/*"
}
```

**Comment by mildwonkey** [comment]
interesting; I added the "empty" null resource and still didn't get an error, and in my case terraform does download the `random` provider on `init`. 

What's the output of `terraform version` (while you're getting that error)? Is the random provider installed?

**Comment by ophintor** [comment]
Ok apologies - After some troubleshooting I figured it was my own mistake.

So I have a script that takes various parameters and creates different environments in AWS using terraform. The script is able to juggle between different workspaces. The problem was that I was running `init` _before_ changing to the workspace I was about to update so that was it... Once I put my init _after_ the `terraform workspace select` everything worked fine without need for the `random_pet` :-)

Thanks for your help!
