### ISSUE TITLE
`terraform refresh` fails before state refresh because of errors caused by cached state

### ISSUE THREAD

**Issue by awilkins** [hashicorp/terraform#18891]
### Terraform Version

```
$ terraform version
Terraform v0.11.7
+ provider.aws v1.19.0
+ provider.external v1.0.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

* Create a simple config that has a string variable output with a remote state backing
* Run this
* Create a config that has a module with a string variable input
* Add a data block for the remote state output from the top config
* Populate the input in the module with the string output
* Plan is happy
* Change the output and input variable to a list
* Plan refuses to run with 

```
module.mymodule.var.input_var: variable input_var in module mymodule should be type list, got string
```

* `terraform refresh` also fails with the same output

You are now stuck - you can't update the remote state your input depends on, because the error from the wrong kind of **cached** remote state your input depends on sinks your plan validation before the refresh happens.

Workaround : 

* Change config to pass a literal list to the module variable
* Do `terraform refresh`
* Put the input variable back
* Plan succeeds

(I'm not sure where the cached remote state is kept... is it in `/tmp` somewhere because I trashed all my `.terraform` folders and this didn't resolve it).

### Expected Behavior

`terraform refresh` always refreshes remote states in `data` blocks even if the rest of the plan (that depends on those data blocks) fails.

### Actual Behavior

Plan fails before remote states are refreshed because of cached remote state.

**Comment by mildwonkey** [comment]
Hi @awilkins -
I'm sorry you've run into this! Do you have an example config you can share so we can reproduce this?

**Comment by awilkins** [comment]
Please see

https://github.com/awilkins/terraform-bug-18891

**Comment by mildwonkey** [comment]
I am so sorry that this got lost and I did not respond _forever_ ago. I downloaded your reproduction repository - thank you! - and was able to confirm that terraform can handle this situation in v0.13 with no difficulty:


```
Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  ~ do_something = "String 1" -> [
      + "list 1",
      + "list 2",
    ]
```

My apologies.
