### ISSUE TITLE
azurerm_lb_rule can't create load_distribution "Client IP and Protocol"

### ISSUE THREAD

**Issue by torstenstern** [hashicorp/terraform#18919]
Hi there,

i will deply in Azure an Standard Loadbalancer with load_distribution = "Client IP and Protocol".
But i am getting everytime this error below

* azurerm_lb_rule.Public: Error Creating/Updating LoadBalancer network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"InvalidJson","message":"Error converting value \"Client IP and Protocol\" to type 'Microsoft.WindowsAzure.Networking.Nrp.Frontend.Contract.Csm.Public.LoadDistribution'. Path 'properties.loadBalancingRules[0].properties.loadDistribution', line 1, position 2110."}]

This is the code in Terrafrom:

Create the Load Balancing Rules
resource "azurerm_lb_rule" "Private" {
  resource_group_name            = "${azurerm_resource_group.rgmain.name}"
  loadbalancer_id                      = "${azurerm_lb.lb1.id}"
  name                                       = "${var.intlbrule_name}"
  protocol                                  = "${var.intlbrule_protocol}"
  frontend_port                         = "${var.intlbrule_frontport}"
  backend_port                          = "${var.intlbrule_backport}"
  frontend_ip_configuration_name = "${var.intlbrule_name}"
    backend_address_pool_id         = "${azurerm_lb_backend_address_pool.Trust.id}"
    probe_id                                 = "${azurerm_lb_probe.lb1.id}"
    load_distribution                    = "Client IP and Protocol"
    enable_floating_ip                 = true
  }

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.10.0
+ provider.null v1.0.0
+ provider.random v2.0.0

**Comment by giuliov** [comment]
> load_distribution - (Optional) Specifies the load balancing distribution type to be used by the Load Balancer. Possible values are: Default – The load balancer is configured to use a 5 tuple hash to map traffic to available servers. SourceIP – The load balancer is configured to use a 2 tuple hash to map traffic to available servers. SourceIPProtocol – The load balancer is configured to use a 3 tuple hash to map traffic to available servers. Also known as Session Persistence, where the options are called None, Client IP and Client IP and Protocol respectively.

**Comment by giuliov** [comment]
Have you tried `SourceIPProtocol`?
From the doc page this looks to be the equivalent value.
> load_distribution - (Optional) Specifies the load balancing distribution type to be used by the Load Balancer. Possible values are: Default – The load balancer is configured to use a 5 tuple hash to map traffic to available servers. SourceIP – The load balancer is configured to use a 2 tuple hash to map traffic to available servers. SourceIPProtocol – The load balancer is configured to use a 3 tuple hash to map traffic to available servers. Also known as Session Persistence, where the options are called None, Client IP and Client IP and Protocol respectively.

**Comment by torstenstern** [comment]
No i didnt, but i will test it and provide you an feedback if this works

**Comment by torstenstern** [comment]
Thanks for help.
it works with the value SourceIPProtocol.
