### ISSUE TITLE
${var.something} fails to interpret properly when used right after https://

### ISSUE THREAD

**Issue by aking1012** [hashicorp/terraform#18929]
### Terraform Version
```
Terraform v0.11.8
+ provider.aws v1.36.0
```

### Terraform Configuration Files
```hcl
  provisioner "remote-exec" {
    inline = [
      "git clone https://${var.oath_token_git}:x-oauth-basic@github.com/some_entity/some_repo.git",
```

### Expected Behavior
`git clone https://${var.oath_token_git}:x-oauth-basic@github.com/some_entity/some_repo.git`  
Should work and download the repo.  

```
  provisioner "remote-exec" {
    inline = [
      "puppet apply",
      "consul join ${aws_instance.web.private_ip}",
```
is noted as working in the documentation.  

### Actual Behavior
`git clone https://${var.oath_token_git}:x-oauth-basic@github.com/some_entity/some_repo.git`  
doesn't work and download the repo, but if I paste my oauth token in the remote-exec inline line, it works just fine.  It's failing to parse that as a variable.  

### Steps to Reproduce
Try to use a variable in a url similar to the stated git line.

### Additional Context
Nothing abnormal.  Standalone.

### References
None

**Comment by mildwonkey** [comment]
Hi @aking1012!  Sorry for the long silence on this issue. Terraform's handling of interpolated variables has been changed in Terraform 0.12: variables are immediately parsed by HCL when the configuration is loaded, so this (buggy!) scenario is no longer possible.

If you see any other problems after upgrading to terraform 0.12, please open a new GitHub issue. Thank you!
