### ISSUE TITLE
'count' cannot be computed for resource within module based on list of interpolated values

### ISSUE THREAD

**Issue by sgsiebers** [hashicorp/terraform#18923]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

I have a root module where I'm creating New Relic alert channels to be reused across multiple modules:
```hcl

## main.tf

variable api_key {
    type = "string"
}

provider "newrelic"{
    api_key = "${var.api_key}"
}

resource "newrelic_alert_channel" "SomeEmail" {
    name = "Some Email"
    type = "email"
    configuration = {
        recipients              = "some_email@domain.com"
        include_json_attachment = "true"
    }
}
 
resource "newrelic_alert_channel" "SomeEmail2" {
    name = "Some Email2"
    type = "email"
    configuration = {
        recipients              = "some_email2@domain.com"
        include_json_attachment = "true"
    }
} 
 
module "MyModuleInstance" {
    api_key = "${var.api_key}"
    channelIds = ["${newrelic_alert_channel.SomeEmail.id}","${newrelic_alert_channel.SomeEmail2.id}"]
    source = "./MyModule"
}

```

I need to pass the newrelic_alert_channel resource ID's into a several different modules that will create alert policies and tie them to these channels by ID:

```hcl

### MyModule/main.tf
variable api_key {
    type = "string"
    default = ""
}

variable channelIds{
    type = "list"
    default = []
}

provider "newrelic" {
    api_key = "${var.api_key}"
}

resource "newrelic_alert_policy" "TestPolicy" {
    name = "My Alert Policy"
    incident_preference = "PER_POLICY"
}

resource "newrelic_alert_policy_channel" "TestPolicyChannel" {
   count = "${length(var.channelIds)}"
   policy_id  = "${newrelic_alert_policy.TestPolicy.id}"
   channel_id = "${var.channelIds[count.index]}"
}
```

### Debug Output
https://gist.github.com/sgsiebers/932c6afaab82239142942b6de3000b2d

### Crash Output
None

### Expected Behavior

When I pass a list of known fixed size to a module, it should be able to use the length of that list as a count variable on a resource within the module.

### Actual Behavior

Instead I get the following error:

```
Error: Error running plan: 1 error(s) occurred:

* module.MyModuleInstance.newrelic_alert_policy_channel.TestPolicyChannel: newrelic_alert_policy_channel.TestPolicyChannel: value of 'count' cannot be computed
```

Oddly enough, if I change the module instantiation to not use interpolated values within the channel ID list variable, and instead hard code some random numbers, it works just fine.  

```hcl
## main.tf
...
module "MyModuleInstance" {
    api_key = "${var.api_key}"
    channelIds = ["123", "456"]
    source = "./MyModule"
}
```

This tells me that passing a list to the module shouldn't be a problem as it's perfectly able to use the list length to determine the resource count value.  Likewise, I can pass the interpolated channel IDs in the list along with a length variable to use for the count value, and everything works just fine.  So it doesn't appear to be having a problem interpolating the alert channel resource IDs in the root module and creating the channel ID list. Yet when I use the combination of interpolated values in a list, and compute resource count off the list length, it errors out on me.

### Steps to Reproduce
Setup code as above
```
.
├── main.tf
└── MyModule
          └── main.tf

terraform init
terraform apply -var 'api_key=foo'
```

### Additional Context
None

### References
None

**Comment by osterman** [comment]
@radeksimko this is certainly one of the most annoying issues with terraform. 

- https://github.com/hashicorp/terraform/issues/13980
- https://github.com/hashicorp/terraform/issues/10857
- https://github.com/hashicorp/terraform/issues/12570
- https://github.com/hashicorp/terraform/issues/17048

We run into it so often and get asked the question so often that we wrote up a summary of it aand how to fix it. 
- https://docs.cloudposse.com/faq/terraform-value-of-count-cannot-be-computed/

What I'd like to see in future versions of terraform are multi-phased `apply` workflows. For now, we tend to use a `Makefile` to orchestrate the process and workaround the issue using `terraform apply -target=module...`

**Comment by apparentlymart** [comment]
Hi @sgsiebers! Sorry for this annoying issue, and for this late response.

As @osterman pointed out, this is the same problem as being discussed over in #12570. We've made some progress on it during the v0.12.0 development cycle, but there is still some further work to do as you can see in my comment over there.

I'm going to close this one just to consolidate the discussion over in #12570. Thanks for reporting this!

**Comment by Bharathkumarraju** [comment]
Is terraform latest version supports count for modules?
