### ISSUE TITLE
terraform init - Access Denied - Incorrect user profile getting selected

### ISSUE THREAD

**Issue by dragonknight88** [hashicorp/terraform#18930]
Trying to use S3 backend for tf project. 

`terraform.tf` - tf config
```
terraform {
    required_version = "= 0.11.8"
    backend "s3" {
        bucket = "terraform-remote-state-storage-s3"
        dynamodb_table = "terraform-state-lock-dynamo"
        region = "us-east-1"
        key = "terraform.tfstate"
        workspace_key_prefix = "testing_project"
    }
}
```

If I `terraform init` on system with multiple profiles this is failing to pick profile set in `AWS_PROFILE` env profile. 

How does one make sure expected user profile is being configured for terraform init in such scenario?
I am running it on jenkins CI pipeline.

**Comment by mildwonkey** [comment]
hi @dragonknight88!

You can specify the `profile` right in the backend block, according to [the documentation](https://www.terraform.io/docs/backends/types/s3.html#configuration-variables). That also allows you to specify which credentials file to use, if necessary, and a handful of other options.

You export the AWS credentials themselves as environment variables.

Cheers!

**Comment by dragonknight88** [comment]
Resolved the issue. Tf was picking up on env vars for another account on the shared build system.
