### ISSUE TITLE
Terraform(ver 0.11) not creating remote state file in consul

### ISSUE THREAD

**Issue by Prabhakar-cg** [hashicorp/terraform#18939]
I have been using terraform 0.8.6 for a while and consul for storing remote state file where everything is working fine. 

iam using cli for creating state file in consul(working version 0.8.6)
terraform remote config -backend=consul -backend-config=scheme=https -backend-config="address=192.168.1.1" -backend-config="path=consul/remote/path"

Recently i have upgraded terraform to 0.11.4 where iam not able create a state file in consul. i could see in terraform 0.11.x version remote command has been replaced with **init** command.

cli command used to create the consul remote state(version 0.11.4)
terraform init -backend-config="address=192.168.1.1" -backend-config="path=consul/remote/state" -backend-config="scheme=https"

After executing the following command i could see only terraform is initialized but unfortunately there is no state file is created in consul.

Debug trace out put shows:
waiting for all plugin process to complete.

**Comment by jbardin** [comment]
Hi @Prabhakar-cg,

Sorry about the confusion here. The `init` command doesn't create a state file, it only sets up t he local configuration, modules, and plugins. It is expected that no state would be created at this point.

**Comment by Raviadonis** [comment]
@jbardin I too face the same issue. We took the reference from the below link.
[https://www.terraform.io/docs/backends/config.html](url)
the terraform backend init should create a `terraform.tfstate` file but in my case it is not. Even though key-value arguments are specified as `-backend-config="address=x.x.x.x"`
Any help would be much appreciated!

**Comment by jbardin** [comment]
@Prabhakar-cg,

The lack of a state file after `init` in itself is not a problem. What is the actual problem, or error you're encountering?

**Comment by renaldrozario** [comment]
@jbardin  How does terraform backend work in 0.11.4?  Is it different from 0.8.6?

**Comment by jbardin** [comment]
@renaldrozario, the configuration and `init` process is obviously different, but the remote state storage works roughly the same. Without any sort of problem statement, or error output, there's not much advice I can give besides trying it out first. (There are a lot of changes since the 0.8 releases, so the backend config itself might be inconsequential)

**Comment by renaldrozario** [comment]
@jbardin  Please see a similar issue posted. I am not the only one who is facing this issue.

https://github.com/hashicorp/terraform/issues/18780
