### ISSUE TITLE
Terraform cannot init remote s3 storage - invalid S3 Credentials

### ISSUE THREAD

**Issue by rhysjtevans** [hashicorp/terraform#18945]
Does terraform leverage the provider.tf file for credentials or does it have to use ~/.aws/credentials?

### Terraform Version
Terraform v0.11.8
+ provider.aws v1.37.0

### Terraform Configuration Files
One file - 
```
provider "aws" {
  access_key = "###########"
  secret_key = "###########"
  region     = "eu-west-1"
}


terraform {
  backend "s3" {
    bucket  = BucketNAME
    key     = "env/terraform.tfstate"
    region  = "eu-west-1"
    encrypt = true
  }
}
```

### Debug Output
https://gist.github.com/rhysjtevans/5085fc1fd9937b120ef630a9df23dc61

### Expected Behavior
Init with remote s3 storage to store the state file

### Actual Behavior
Does not init.

### Steps to Reproduce
Please list the full steps required to reproduce the issue:
1. `terraform init`

**Comment by bennycornelissen** [comment]
If I’m not mistaken, the remote state config will not take the credentials from the provider block. So you either need to specify the credentials _again_ in the backend block, or (and I prefer this approach) use environment variables instead and remove the AWS credentials from the code altogether.

See https://www.terraform.io/docs/backends/types/s3.html

**Comment by rhysjtevans** [comment]
Thanks @bennycornelissen! I did not realise you had to specify them again. Would be nice if terraform used the single provider reference. I can totally see why they are separate though.
