### ISSUE TITLE
destroy does not support -state option

### ISSUE THREAD

**Issue by elialgranti** [hashicorp/terraform#18942]
### Terraform Version

```
Terraform v0.11.8
+ provider.aws v1.37.0
...
```

### Terraform Configuration Files

```hcl
...
```

### Debug Output

terraform destroy -state=.\ci\architecture\dev.terraform.tfstate  .\ci\architecture\development\
2018/09/26 15:34:46 [INFO] Terraform version: 0.11.8  7a5c1d221ac209bbac66947c369815cd9ca70ed5
2018/09/26 15:34:46 [INFO] Go runtime version: go1.10.1
2018/09/26 15:34:46 [INFO] CLI args: []string{"C:\\Programs\\terraform.exe", "destroy", "-state=", ".\\ci\\architecture\\dev.terraform.tfstate", ".\\ci\\architecture\\development\\"}
2018/09/26 15:34:46 [DEBUG] Attempting to open CLI config file: C:\Users\ealgranti\AppData\Roaming\terraform.rc
2018/09/26 15:34:46 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/09/26 15:34:46 [INFO] CLI command args: []string{"destroy", "-state=", ".\\ci\\architecture\\dev.terraform.tfstate", ".\\ci\\architecture\\development\\"}
2018/09/26 15:34:46 [DEBUG] plugin: waiting for all plugin processes to complete...
Too many command line arguments. Configuration path expected.

### Expected Behavior

Terraform should destroy the  environment using the specified tfstate file.
### Actual Behavior

Terraform outputs error:  Too many command line arguments. Configuration path expected.

### Steps to Reproduce

Just run terraform destroy with -state option

### Additional Context

Note: I successfully destroyed the infrastructure by copying the tfstate file to the default location. Creation and update of the infrastructure works as expected with -state option.

**Comment by renaldrozario** [comment]
@elialgranti  Please advise if you were able to create remote state files ?? we are trying with version 0.11.4 and remote state file fails to consul KV store.

Issue is referenced below:
https://github.com/hashicorp/terraform/issues/18939

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. There have been many updates and fixes since this was originally opened.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
