### ISSUE TITLE
Terraform crash during `terraform plan`, after 0.4.2 to 0.5.0 upgrade

### ISSUE THREAD

**Issue by ncraike** [hashicorp/terraform#1895]
I experienced this crash the first time I ran `terraform plan` after upgrading from 0.4.2 to 0.5.0. I had an existing config and tfstate file from when I was running 0.4.2.

crash.log will be attached shortly.

I'm not sure if I can easily provide the config and state, as that may provide confidential details of my employer's project. I might be able provide it with, eg the name of the project and client replaced with other strings, but I'm not sure how helpful that will be.

**Comment by ncraike** [comment]
Okay, my `crash.log` is 421K. I'm not sure how to attach this to the issue. It's too long as the issue body or a comment. Any suggestions?

**Comment by ncraike** [comment]
I've created a gist for my crash.log: https://gist.github.com/ncraike/2587c0c37b95e82c3816

**Comment by radeksimko** [comment]
Thanks for reporting this.

It looks like there's no name server coming from the Route53 delegation set at `builtin/providers/aws/resource_aws_route53_zone.go:101`.

It may be the case for private zones which were AFAIK introduced between `0.4.2` and `0.5.0`.

It would help if you could provide a reduced config (without any secrets), so we can replicate the error or at least the part with Route53 records/zones.

**Comment by radeksimko** [comment]
Actually, there is no support for private zones yet. :confused: 
I'd be interested to see what's the configuration for your `aws_route53_zone.private_zone`.

**Comment by ncraike** [comment]
Er, actually this may be caused by me being too clever for my own good.

Although 0.4.2 didn't _support_ private zones, I discovered that if you created a private zone manually and then… erm, modified the .tfstate file to include the private zone and its ID (using a public zone Terraform _had_ created as reference), Terraform would actually seem to handle that fine: it would be aware of the zone, and would consider it satisfying the `aws_route53_zone` block in my config, and would even add new DNS records to the private zone as per `aws_route53_record` blocks in my config.

This was a workaround I was using while waiting for #1526, it did seem to work pre-0.5.0. But if it now seems to be the source of the crash, I'll find another solution (either not managing private zones or staying with 0.4.2, until #1526 is released) _and_ I'll stop bugging you with my thoroughly deserved crashes.

I'm not at work at the moment (I'm in Australia, timezone UTC+10), but in the next couple workdays I'll try to test if removing the private zones avoids the crash in 0.5.0. If that doesn't help, I'll work on getting a minimal/sanitised config up.

**Comment by radeksimko** [comment]
@ncraike Thanks for the explanation. It now makes more sense and I believe this is actually fixed here https://github.com/hashicorp/terraform/pull/1526/files#diff-1dcfb2ca470a52c3ca236aeb96439f68R124

If you want, you may help testing #1526 by building Terraform from that branch temporarily and see if it works for you.

I'm closing this in favour of #1526 , reopen if you think it's a separate issue.
