### ISSUE TITLE
AWS VPN PSK is saved with \n and space characters in the terraform state

### ISSUE THREAD

**Issue by tkoeck** [hashicorp/terraform#18971]
Hi there,

we have a connection like

aws_vpn_connection.blubb 

and we have set a PSK with 64 character length

(for instance like this one "586f235d9c9b12e5cc8c8dc0c38b6ac4f577ececaa8e2da9b728bbda7c02e390" - obviously this is a generated and not the real one)

For some reason Terraform saves the key in the state file in the format

"\n        586f235d9c9b12e5cc8c8dc0c38b6ac4f577ececaa8e2da9b728bbda7c02e390\n      "

- Terraform deploys the PSK on AWS without the extra characters so it works on the VPN Gateway side
- Terraform wants to recreate the VPN connection every time it I use 'terraform apply'

That's no fun because every time the VPN connection is created two new public IPs are generated. Looks to me like a bug? Is Terraform not able to use 64 character long PSK? 

The documentation says it should work

https://www.terraform.io/docs/providers/aws/r/vpn_connection.html#tunnel1_preshared_key

### Terraform Version

Terraform v0.11.8

**Comment by calebgosnell** [comment]
I can confirm the same with
Terraform v0.11.7
provider.aws v1.40.0
module terraform-aws-vpn-gateway v1.5.0 

I had success with a 46 char PSK but not with a 58 char.
