### ISSUE TITLE
templates in user_data always cause a rebuild

### ISSUE THREAD

**Issue by jwaldrip** [hashicorp/terraform#1898]
When using templates for user-data, it seems to cause a change every time I build. Is there anyway to do a sha on the output of the template to tell the statefile that the output is unchanged?

**Comment by phinze** [comment]
Hey @jwaldrip - thanks for the report. As it happens, I already had a WIP addressing this very issue. Just pushed and we'll get it reviewed and landed soon.

**Comment by jwaldrip** [comment]
@phinze thanks!
