### ISSUE TITLE
RDS Deletion Protection

### ISSUE THREAD

**Issue by nomeelnoj** [hashicorp/terraform#18985]
### Current Terraform Version

```
Terraform v0.11.8
```

### Use-cases

Some companies have trigger happy users, and it would be nice to protect against them by being able to turn on deletion protection for RDS
### Attempted Solutions

None
### Proposal

Allow terraform users to enable deletion protection.  If using terraform to also delete the instance, there could be a "force" command or a user prompt to verify if deletion protection is turned on.  If force is true or the user accepts, terraform could turn off deletion protection before destroying.  This option is available in the CLI with `modify-db-instance [--deletion-protection | --no-deletion-protection]`

**Comment by kevlened** [comment]
I believe `prevent_destroy` [under the `lifecycle` meta-parameter](https://www.terraform.io/docs/configuration/resources.html#prevent_destroy) should prevent deletion. To override it, use a ternary operator on a variable you pass into the configuration.

**Comment by bflad** [comment]
Support for the new `deletion_protection` argument was handled in the AWS provider via:
* `aws_db_instance`: https://github.com/terraform-providers/terraform-provider-aws/pull/6011
* `aws_rds_cluster`: https://github.com/terraform-providers/terraform-provider-aws/pull/6010

Which were both released yesterday with [version 1.39.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1390-october-03-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
