### ISSUE TITLE
Question: Renaming a resource

### ISSUE THREAD

**Issue by pixelicous** [hashicorp/terraform#18988]
Hi,

How does one go about renaming a logical name for a resource in an HCL file?
Once i do that, my terraform configuration doesn't want to execute anymore.
It cannot find the old resource and doesn't understand what is that new resource

**Comment by bennycornelissen** [comment]
Hi @pixelicous, 

can you share some example code of your specific situation? Looking at what you're describing I wouldn't expect Terraform to not execute. Instead when renaming a resource (for instance renaming `aws_instance.foo` to `aws_instance.bar`), I would expect Terraform to create a plan where `aws_instance.foo` gets destroyed (if it exists), and a new `aws_instance.bar` is created. If it does anything other than that, the issue may be in your code, so it would be nice if you could share that.

**Comment by pixelicous** [comment]
The HCL is long and is part of a more complex file (I will try to do this with a basic file and update)

I didn't mean that the resource name doesn't change, the terraform name changes. 
How is one suppose to change the logical naming in the HCL file if it goes out of sync forcing a new resource?

I want to try and error again to see what exactly is the message that i get

**Comment by hipyhop** [comment]
Try `terraform state mv <old_name> <new_name>`

    terraform state mv aws_iam_policy_attachment.grafana_cloudwatch_policy_attach aws_iam_policy_attachment.grafana_cloudwatch_attach

**Comment by mildwonkey** [comment]
I'm going to close this issue, as @hipyhop provided an accurate answer, but please re-open or open a new issue if necessary pixelicous!
