### ISSUE TITLE
Sensitive output bug (or its a feature?)

### ISSUE THREAD

**Issue by kvolkovich-sc** [hashicorp/terraform#18999]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
output "service_principal_password_value" {
  sensitive = true
  value     = "${azurerm_azuread_service_principal_password.sp_1.value}"
}
```

### Expected Behavior

When I run `terraform init`, I expect to get:

```
...
Terraform has been successfully initialized!
Terraform output
service_principal_password_value = <sensitive>
```

### Actual Behavior

When I run `terraform init`, I got a real value like:

```
...
Terraform has been successfully initialized!
Terraform output
service_principal_password_value = asdlGajdf33432
```

Is it a bug or I just missed something in documentation?

**Comment by mildwonkey** [comment]
Hi @kvolkovich-sc , thank you for reporting this! It's certainly not expected behavior according to the [output documentation](https://www.terraform.io/docs/configuration/outputs.html#sensitive-outputs), so I will label this as a bug!

**Comment by kvolkovich-sc** [comment]
Looks like my mistake.

Sorry. I found an issue. Its in our automation scripts. `terraform output` were called after `terraform inti`
