### ISSUE TITLE
Output of `terraform plan` on Windows is not colored

### ISSUE THREAD

**Issue by grv87** [hashicorp/terraform#1900]
Output of `terraform plan` on Windows is not colored. The comment says that
```
Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.
```
But I can't see any green, yellow or red colors.

I use [Console](http://sourceforge.net/projects/console/), it shows colors, e.g. with `git`. But not with `terraform`.

**Comment by mitchellh** [comment]
We disable colors on Windows until we have a good solution on Windows for properly deetecting whether the console supports it. We don't change the output for Windows but I'm going to pass and say thats okay for now. Sorry!
