### ISSUE TITLE
Data source count cannot reference variable

### ISSUE THREAD

**Issue by lordnynex** [hashicorp/terraform#19008]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
/*
 * Load AWS Plugin
 */
provider "aws" {
  region = "us-east-1"
  version = "~> 1.35.0"
}

/*
 * Variables
 */
variable "networks" {
  type = "list"
  default = [
    "foo",
    "bar",
    "baz"
  ]
  description = "VPC Short names"
}

variable "domain" {
  type = "string"
  default = "example.com"
  description = "Domain name for tag lookups"
}

/*
 * Data lookup for VPC's
 * Use these variables to find VPC's with tags looking like
 *   - Name: foo.example.com
 *   - Name: bar.example.com
 *   - Name: baz.example.com
 */
data "aws_vpc" "network_vpcs" {
  count = "${length(networks)}"
  tags {
    Name    = "${var.networks[count.index]}.${var.domain}"
  }
}

/*
 * Output VPC ID's
 */
output "network_vpc_ids" {
  value = "${data.aws_vpc.network_vpcs.*.id}"
}
```

### Debug Output

[Debug output gist](https://gist.github.com/lordnynex/5dc5a3434119bc77d7136445621a6b49)

### Crash Output

N/A

### Expected Behavior

I would expect I can use `count` to lookup multiple VPC's

### Actual Behavior

`Error: data.aws_vpc.network_vpcs: resource count can't reference variable: networks`

### Steps to Reproduce

`terraform init`

### Additional Context

N/A

### References

- #14143 (I'm not sure if this is still relevant?)

**Comment by hipyhop** [comment]
```  count = "${length(networks)}"```
should be
```   count = "${length(var.networks)}"```

**Comment by lordnynex** [comment]
Wow I'm an idiot. Thank you @hipyhop!
