### ISSUE TITLE
Additional Security Group Ingress Rule Flapping on a aws_security_group output.

### ISSUE THREAD

**Issue by ganeshk254** [hashicorp/terraform#19024]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-2"
}

## ==========================
## DATA
## ==========================
data "aws_vpc" "cluster_vpc" {
  cidr_block = "172.31.0.0/16"
}

## ==========================
## RESOURCES
## ==========================
resource "aws_security_group" "workbench" {
  name_prefix = "test-"
  vpc_id = "${data.aws_vpc.cluster_vpc.id}"
  description = "Security Group for cluster"

  ingress {
    from_port = 22
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  lifecycle {
    create_before_destroy = true
  }

}

resource "aws_security_group_rule" "test_custom" {
  type              = "ingress"
  from_port         = 22333
  to_port           = 22333
  protocol          = "tcp"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = "${aws_security_group.workbench.id}"
}
```

### Expected Behavior

When `terraform plan` is applied on a just applied plan, it should be no-op.
### Actual Behavior

The additional ingress rule `test_custom` gets removed and added alternatively. But there is always a removal/addition of this rule.
```
Terraform will perform the following actions:
  ~ aws_security_group.workbench
      ingress.#:                             "2" => "1"
      ingress.2541437006.cidr_blocks.#:      "1" => "1"
      ingress.2541437006.cidr_blocks.0:      "0.0.0.0/0" => "0.0.0.0/0"
      ingress.2541437006.description:        "" => ""
      ingress.2541437006.from_port:          "22" => "22"
      ingress.2541437006.ipv6_cidr_blocks.#: "0" => "0"
      ingress.2541437006.prefix_list_ids.#:  "0" => "0"
      ingress.2541437006.protocol:           "tcp" => "tcp"
      ingress.2541437006.security_groups.#:  "0" => "0"
      ingress.2541437006.self:               "false" => "false"
      ingress.2541437006.to_port:            "22" => "22"
      ingress.631493796.cidr_blocks.#:       "1" => "0"
      ingress.631493796.cidr_blocks.0:       "0.0.0.0/0" => ""
      ingress.631493796.description:         "" => ""
      ingress.631493796.from_port:           "22333" => "0"
      ingress.631493796.ipv6_cidr_blocks.#:  "0" => "0"
      ingress.631493796.prefix_list_ids.#:   "0" => "0"
      ingress.631493796.protocol:            "tcp" => ""
      ingress.631493796.security_groups.#:   "0" => "0"
      ingress.631493796.self:                "false" => "false"
      ingress.631493796.to_port:             "22333" => "0"
```
### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

### Additional Context
* Same thing happens to me when I use the `workbench_security_group` as a module and add the custom ingress rule on the module output.
* Tried searching for any issue already filed on it, couldn't find anything relevant.Sorry if this is a dup.

**Comment by bennycornelissen** [comment]
I've ran into this issue shortly after the `security_group_rule` became available in Terraform (long time ago). The issue is that you're defining a resource `security_group` that contains 1 rule. So according to Terraform, the amount of ingress rules for this security group should be 1. But obviously, because of the `security_group_rule.test_custom`, there are 2. 

If you move the ingress rule for port 22 to a dedicated `security_group_rule` resource, you should have no issues, since according to Terraform, it shouldn't be concerned with any ingresses for the `security_group` resource. It should just make sure it's there. The rules in the security group will be managed by the individual `security_group_rule` resources. Code-wise it is cleaner than what you have now, and the flapping should be gone. 😄

**Comment by ganeshk254** [comment]
Thank you @bennycornelissen , that makes sense. 

The above code was a sample of a bigger module. I wanted to deliver the standard infrastructure rules as a single resource as adding a resource for each rule will increase the refresh time. I will go with your suggestion.

**Comment by mildwonkey** [comment]
This appears to be resolved, so I'm going to close it, but please comment here if this doesn't work for you!
