### ISSUE TITLE
Cross resource lifecycle tunning

### ISSUE THREAD

**Issue by odormond** [hashicorp/terraform#19023]
### Current Terraform Version
```
Terraform v0.11.7
```

### Use-cases

I'm trying to use an aws_instance hosting nginx as a reverse-proxy for both short lived HTTPS requests and long lived TCP streams, specifically beanstalkd streams and an elastic-IP to reach it from the internet. The aws_instance has its lifecycle configured to `create_before_destroy` to minimize downtime.

Whenever the nginx hosted instance is replaced the beanstalk clients get stuck because the TCP connection is never closed (from their point of view). This seems to happens because the new instance is created, then the EIP is moved to it and finally the old instance is destroyed but it cannot send packet to the outside anymore as it doesn't have a public IP anymore.

Of course, setting the `create_before_destroy` to `false` fixes the problem but the downtime increases noticeably.

### Proposal

Add a lifecycle attribute `destroy_before_modify_dependencies` either as a boolean or a list of resource name that shouldn't be modified before destroying this one.

**Comment by pkolyvas** [comment]
I'm doing a clean-up of older issues that haven't gained traction but also don't coincide more directly with our current areas of focus. 

We are also thinking about how to evolve resource and module lifecycle (in general) for many of our community's use cases, but have yet to take a firm decision on the direction. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
