### ISSUE TITLE
allow running provisioners before and after a change is applied

### ISSUE THREAD

**Issue by pschiffe** [hashicorp/terraform#19030]
### Current Terraform Version
```
Terraform v0.11.8
```

### Use-cases
For example - Resize aws instance with Terraform. Running instance must be stopped before changing size, so steps are: stop instance, change size, start instance. Terraform can change size, but currently cannot stop and start existing instance (or I didn't find how).

### Proposal
For example - Allow running provisioners before and after the change is applied, with `when = "before_change"` or `when = "after_change"`.

Sorry if this was already discussed, or if there exists alternative solution - please let me know.

**Comment by pkolyvas** [comment]
I'm doing a clean-up of older issues that haven't gained traction but also don't coincide with some of our current focus. While provisioners, as a whole, aren't a top priority for the team, when some time is available to focus on them we're going to use that attention to tackle some long-standing defects. 

We are also thinking about how to evolve provisioning for many of community's use cases, but have yet to take a firm decision on the direction. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform, present and future.
