### ISSUE TITLE
terraform destroy fails with ASG-based infra 

### ISSUE THREAD

**Issue by julienlavergne** [hashicorp/terraform#1903]
Hello,

I systematically encounter the same error: try to destroy an infra with autoscaling groups resources.

I updated to the last release: 0.5.0

I do the following:

```
$ terraform plan; # -> good
$ terraform apply; # -> good
$ terraform plan -destroy -out=destroy.tfplan; # -> failed

the ouput is the following: 

> Error running plan: no roots found
```

I always got this error when my plans have autoscaling group resources.

Any idea? 

Thx

**Comment by nonflet** [comment]
+1.Problem occurs then i'm trying to create new group of servers with security groups and elb , for example.

Anything based on creation/deleting terraform infrastructure giving this error. Plan on old terraform giving "OK".Apply - "OK"
Only new terraforms affected or deleting old.

Errors:

  * no roots found

I even found the part of code, giving this problem : https://github.com/hashicorp/terraform/blob/master/dag/dag.go

But cann't understand how to fix it :)

**Comment by julienlavergne** [comment]
Some new cool features to support aws resources but some regressions about infra management;

**Comment by phinze** [comment]
I'm getting the same error on a `plan` - hoping the issues are related. Looking into it now.

**Comment by phinze** [comment]
@julienlavergne @nonflet - OK! I landed a fix for the expression of this that I was able to reproduce.

Do you think you could give master another shot in your environments and let me know if the error goes away?

**Comment by julienlavergne** [comment]
Paul 

Thx for trying to fix this issue. 

First i encountered this issue with another simple plan with route53 resources. It's another case to try to fix.

Your fix is committed on the master? 


Julien

**Comment by mitchellh** [comment]
@julienlavergne It is

**Comment by julienlavergne** [comment]
Thx Mitchell

I should build it


Julien

**Comment by julienlavergne** [comment]
@mitchellh I built the last dev version and tested for route53 provisioning zones/records (not yet for ASG).

I confirm that this bug which existed for Route53 wipeout resources is no longer.

Thx

**Comment by catsby** [comment]
Thanks for following up @julienlavergne – I'm going to close this for now then, please re-open if you think there's still an issue here.
