### ISSUE TITLE
Taint doesn't respect create_before_destroy

### ISSUE THREAD

**Issue by rubbish** [hashicorp/terraform#1904]
Hey all, I noticed this morning that after tainting a resource that had a `lifecycle { create_before_destroy = true }`, it didn't seem to create the new resource before destroying the old. 

Is this the intended behavior?

**Comment by mitchellh** [comment]
This is intended indeed. A tainted resource is unlike a normal resource scheduled for destroy. I think this requires some thinking of how we want to handle this. I don't think we should reorder taints...

**Comment by phinze** [comment]
Consolidating with #2910, which is newer but has more detail.
