### ISSUE TITLE
Terraform EC2 Import error- user_data is changing. 

### ISSUE THREAD

**Issue by manjitsingh664** [hashicorp/terraform#19046]
I have a critical service running in EC2 instance. I want to bring it under Terraform control. I imported the aws instance with terraform import command. But whenever I run terraform plan, its asking to destroy and create a new instance as user_data is changed. The instance was launched manually with user_data. I cant shut down or destroy and recreate the instance. Is there any way to import the aws instance without touching the user_data. 
My main aim to manage the security groups and rules attached to instance with terraform. I dont have to modify other parameters like user_data. So please suggest a way to import the instance.

**Comment by Victorion** [comment]
You can ignore some changes if you don't need them
```hcl
lifecycle {
        ignore_changes = [
            "user_data"
        ]
    }
```

**Comment by mildwonkey** [comment]
@manjitsingh664 - it's hard to advise without seeing your configuration, but @Victorion 's suggestion is sound. Either remove `user_data` from your terraform configuration altogether or set the lifecycle as suggested above.

**Comment by manjitsingh664** [comment]
@Victorion @mildwonkey - Thanks for the answer..It works.
