### ISSUE TITLE
 MissingParameter: The request must contain the parameter InstanceId

### ISSUE THREAD

**Issue by jedi4ever** [hashicorp/terraform#1905]
This occurred when I created a NAT instance of the wrong type.
fi. hvm image  was not supported on t1.micro

In tfstate there was an instance with instanceId "" , so it could not continue.

**Comment by timothykimball** [comment]
I am having this problem if I Ctrl-C out of a terraform script at a certain point and then attempt to destroy:

terraform destroy
aws_instance.app: Refreshing state... (ID: )
cloudflare_record.dns: Refreshing state... (ID: 287002525)
Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* MissingParameter: The request must contain the parameter InstanceId


If I log into AWS, I can see the instance that was created by terraform is there. Just no way to destroy it?

**Comment by mitchellh** [comment]
Fixed in above PR. 

@timothykimball That sounds really bad, but I tried a few times and couldn't get this to reproduce (unless I ctrl-C twice, which explicitly warns me data loss will occur). You can do it with a single ctrl-C?

**Comment by timothykimball** [comment]
@mitchellh - Pleased to meet you! Great product btw. What is the best way for me to contribute?

I have attempted to reproduce and you are correct - I was hitting Ctrl-C twice (slap my hand). Apologies.
