### ISSUE TITLE
Update documentation for steps to compile on Windows 

### ISSUE THREAD

**Issue by justdan96** [hashicorp/terraform#19057]
Since Go 0.11 removed the path length issues on Windows there are no longer any requirements to build Terraform on Linux specifically. 

I propose the documentation is updated to guide Windows users on how to compile Terraform on Windows. The following steps worked for me:
 
1. Install Go 0.11.1 from https://golang.org/dl/ - the filename is go1.11.1.windows-amd64.msi

2. Install the older version of the Ruby Dev Kit from https://rubyinstaller.org/downloads/ - the file name is DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe

3. Download the ZIP utility from GNUWIN32 from https://sourceforge.net/projects/gnuwin32/files/zip/3.0/ - filenames are zip-3.0-bin.zip and zip-3.0-dep.zip

4. Extract the downloaded ZIPs into the .\mingw\ folder where the Dev kit was installed. 

5. Open a command prompt, run devkitvars.bat from the Dev kit folder. 

6. Run the usual make commands to compile Terraform. 

What do people think, does this proposal make sense?

**Comment by mildwonkey** [comment]
This is pretty outdated - the current version of terraform can be built on windows - so I am going to close this . thanks!
