### ISSUE TITLE
[Feature] Provision on resource update

### ISSUE THREAD

**Issue by Xopherus** [hashicorp/terraform#19078]
### Current Terraform Version

```
terraform 0.11
```

### Use-cases

I'm running Nomad in AWS with the servers and clients in separate auto-scaling groups. If I update the version of Nomad, a new AMI is built. To deploy that new version to production I need to go through two phases. This process is actually pretty similar to the one outlined in [terraform-aws-nomad](https://github.com/hashicorp/terraform-aws-nomad/tree/master/modules/nomad-cluster#how-do-you-roll-out-updates) repository. 

1. `terraform apply` to update the auto-scaling group with a new launch configuration that specifies the ASG to use the new AMI.
2. Run a script which rolls out the update to the nomad cluster. It increases the auto-scaling group size by 1, waits for that instance to join the nomad cluster, and then decreases the auto-scaling group size by 1 to terminate an older node (one that uses the previous launch configuration). Repeats until all of the older nodes are replaced by new ones.

What I'm proposing is a mechanism for terraform to trigger the deployment script automatically - specifically when the auto-scaling group resource is updated. Other resources can be created and modified, but unless the auto-scaling group is updated there's simply no need to trigger a deploy, because the AMI has not changed. 

### Attempted Solutions

The deploy script that I've written is able to forcefully kill nomad clients even if the AMI has not changed between deployments. It's a workable solution, though it's pretty expensive no-op. There's a couple alternatives I've been thinking about that should work:

* Update the deploy script to use [DescribeAutoScalingGroup](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DescribeAutoScalingGroups.html) to fetch all of the instances in the group and compare their launch configuration with the one attached to the AutoScalingGroup. Only requires 1 AWS call to do so. Admittedly this is actually my preferred solution, but I still wanted to open this issue to see if anyone else had a use-case for what I'm proposing.
* Output the launch configuration name in terraform, use `terraform output` to pass that into the deployment script. Have the script compare the launch configurations of the EC2 instances currently running to the one that terraform outputs. If they are equal, do nothing. Not as good as the previous option.

**Comment by mildwonkey** [comment]
Good call - I will close this as a duplicate. @Xopherus  - if you haven't already, please go add a 👍 to #19030! 
Thank you!
