### ISSUE TITLE
Can't apply tags to aws_db_instance

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#1908]
Trying to apply tags to an RDS instance and I'm getting this error:

```
* InvalidParameterValue: Invalid resource name:  arn:aws:rds:us-east-1:AIDAJDGLPYCDOTN7Q7BXG:db:dev-security-user
```

It appears that the `buildRDSARN` method is incorrectly constructing the ARN for the RDS instance. It's using the IAM `UserID` instead of the Account ID.

**Comment by radeksimko** [comment]
I actually hit this issue elsewhere, when reusing the ARN helper that @catsby built for RDS.

Here's how I solved it for ECS:
https://github.com/hashicorp/terraform/pull/1803/files#diff-047ff2782c4a593ae27a5b9bd8ad998fR289

I wonder what was the original motivation behind taking UserID, @catsby ?

**Comment by johnrengelman** [comment]
Awesome! I was struggling to figure out how to get the account ID.

**Comment by catsby** [comment]
Probably just a simple mistake on my part. I'm curious though why it worked previously though, are you using a IAM credentials, and perhaps I wasn't?

**Comment by johnrengelman** [comment]
I'm guessing that's the case.
