### ISSUE TITLE
Templates don't work in second-level modules - "unflattenable node: provider.template (disabled) *terraform.graphNodeDisabledProvider"

### ISSUE THREAD

**Issue by jc-asdf** [hashicorp/terraform#1913]
Templates don't work in modules loaded from modules.  Inside the base scope, or in an included module, they work fine, but if a module includes another module, I get

unflattenable node: provider.template (disabled) *terraform.graphNodeDisabledProvider

Example:

main.tf:

    module "first_test" {
      source = "modules/first"
    }

modules/first/main.tf:

    module "second_test" {
      source = "../second"
    }

modules/second/main.tf:

    resource "template_file" "template_test" {
      filename = "test.tpl"
    }

modules/second/test.tpl:

    asdf

When running terraform plan on the above, it errors out.  If I include "second" directly from the base level, it works fine.

Unfortunately I'm not sure where to look in terms of diagnosing this problem.

**Comment by mitchellh** [comment]
Eh, I know exactly what this is. I'll fix this for 0.5.1

**Comment by jc-asdf** [comment]
Thanks! Let me know if you need any additional data.

**Comment by mitchellh** [comment]
This was fixed by @phinze!
