### ISSUE TITLE
Required provider arguments set by environment variables not honored in v0.12-alpha1

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#19139]
### Terraform Version

```
Terraform v0.12.0-alpha1
+ provider.aws v1.40.0-5-g4f24bc8b7
```

(also affects other providers that use `EnvDefaultFunc`)

### Expected Behavior

Some providers have arguments within their provider configuration schemas that are marked as being "required" but can alternatively be satisfied from a particular environment variable.

When such environment variables are set, Terraform should treat that the same way as if the value was assigned in a `provider` block in the configuration.

The `region` argument in `provider "aws"` is an example of this: if an `AWS_DEFAULT_REGION` environment variable is set then Terraform behaves as if its value were assigned to `region`, relaxing the usual requirement that it be set inside the `provider "aws"` block.

### Actual Behavior

In v0.12.0-alpha1 this mechanism is not functioning correctly because the validation for the argument being required is incorrectly performed before the environment variables have been checked. Therefore Terraform will prompt for interactive input for these arguments or produce an error about them not being set, even if the relevant environment variable is set.

This does not apply to _all_ settings that come from environment variables. Those that apply as default values for arguments marked in the schema as _optional_ are working as expected, since the initial validation pass accepts that they are absent and allows the dynamic default to be applied.

In particular, this does not apply to AWS credentials because the `access_key` and `secret_key` arguments are both optional and the provider logic itself -- rather than the plugin SDK -- implements the multi-level credentials source behavior.

### Steps to Reproduce

Write a Terraform configuration that contains AWS resources but either omits the `provider "aws"` block entirely or provides no value for the `region` argument.

When running `terraform apply`, Terraform will prompt for a region even if the `AWS_DEFAULT_REGION` environment variable is set.

### Workaround

To work around this for v0.12-alpha1 testing, temporarily set the relevant settings explicitly in configuration rather than relying on environment variables.

**Comment by ravitandonrt** [comment]
Ref count +1 (From OCI provider)

None of the environment variables that override the default values seem to get honored either, discernible impact on variables that are used by `file` as it results in file not found.
