### ISSUE TITLE
"unsupported msgpack code 0xc4" when applying a saved plan file

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#19147]
### Terraform Version
```
Terraform v0.12.0-alpha1
```

### Expected Behavior

When creating a saved plan file with `terraform plan -out=tfplan`, it should be possible to later apply it with `terraform apply tfplan`, as long as no other changes have been made in the mean time.

### Actual Behavior

It seems that sometimes when applying a saved plan file Terraform v0.12-alpha1 will produce the following error:

```
Error: Invalid plan file

Invalid value for variable "zoo_enabled" recorded in plan file: unsupported msgpack code 0xc4.
```

### Steps to Reproduce
We have not yet narrowed down a reliable reproduction case for this. It is possible that it was already fixed by an earlier change.

**Comment by jbardin** [comment]
Found a repro for this. Only needs a boolean variable:

```
variable "enabled" {
  default = false
}

resource "null_resource" "c" {
}
```

```
$ tf plan -out tfplan
$ tf apply tfplan

Error: Invalid plan file

Invalid value for variable "enabled" recorded in plan file: unsupported
msgpack code 0xc4.
```

**Comment by apparentlymart** [comment]
Ahh, I think I see what's going on here:

* When the variable values are encoded, they're being marshalled with an explicit type of `cty.DynamicPseudoType`, causing it to serialize as a late-bound value with the type included in the payload. (That msgpack sequence you saw is approximately `["\"bool\", false]`.
* However, when we're _decoding_ we must be trying to use [`ImpliedType`](https://godoc.org/github.com/zclconf/go-cty/cty/msgpack#ImpliedType) to _guess_ the type, rather than just again passing `cty.DynamicPseudoType` to `Unmarshal`. That doesn't work because `ImpliedType` doesn't expect to find a late-bound value.

I think the bug is here:

https://github.com/hashicorp/terraform/blob/f4cdb9945b76a134481cd214a27fc45f33e31b90/backend/local/backend_local.go#L222-L239

Rather than trying to sniff for a type and decode it, it should instead just call `dyVal.Decode(cty.DynamicPseudoType)` for symmetry with the `Encode` that happened when producing the plan in the first place.
