### ISSUE TITLE
Map helper functions:  keys(), values()

### ISSUE THREAD

**Issue by gtrevg** [hashicorp/terraform#1915]
Is there an easy way to get only the keys or values defined in a map?  For example, given:

```
variable "aws_az_subnet_map" {
  description = "The subnet id for each availability zone"
  default = {
    us-west-2a = "subnet-abcd1234"
    us-west-2b = "subnet-efab5678"
    us-west-2c = "subnet-cdef9012"
  }
}
```
It would allow you to easily just dump either the keys or values into other parts of the configuration.  

```
resource "aws_elb" "my_elb" {
	subnets = [ "${values(var.aws_az_subnet_map)}" ]
}

resource "aws_autoscaling_group" "my_autoscale_group" {
    availability_zones = [ "${keys(var.aws_az_subnet_map)}" ]
	vpc_zone_identifier = [ "${values(var.aws_az_subnet_map)}" ]
}

resource "aws_instance" "my_instance" {
	count = "${length( keys(var.aws_az_subnet_map))}"
	subnet_id = "${ element(values(var.aws_az_subnet_map)), count.index }"
}
```

This keeps one form having to maintain two variables that then must remain in sync with the correct number of items in each.

Thanks

**Comment by radeksimko** [comment]
That's actually an interesting idea. There isn't AFAIK a such built-in function yet.

**Comment by mikeyhill** [comment]
+1  this would be much more graceful than hardcoding those individual values in

**Comment by phinze** [comment]
Yep I think this would be a great idea. A PR would be welcome, or one of us core folk will try to pick it up when we can.

Worth noting that the functionality would be limited to direct variable access w/ defaults until we enhance the config language to fully support complex types. Still worth adding IMO.

**Comment by edmundcraske** [comment]
Doesn't seem like these functions are documented in the main Terraform docs yet?

**Comment by radeksimko** [comment]
@edmundcraske See https://github.com/hashicorp/terraform/commit/80365282cc98feb549689c0c5252742e7303da04 It was documented about a month ago, docs website will be updated along with the next release. 😉
