### ISSUE TITLE
perma-diffs for any Optional+Computed attribute not explicitly set in config

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#19151]
### Terraform Version
```
Terraform v0.12.0-alpha1
```

### Terraform Configuration Files
```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.1.0.0/16"

  tags = {
    Name = "main vpc"
  }
}
```

### Expected Behavior
During creation, the AWS provider will assign default values to a number of optional arguments of the `aws_vpc` resource type, such as `assign_generated_ipv6_cidr_block`, `enable_dns_support`, and `instance_tenancy`.

These attributes are declared in the schema as both `Optional` and `Computed`, which means that the configuration may optionally set it but if the config does not set it then the provider will assign a default value instead.

On subsequent plans, the default values assigned by the provider should be preserved.

### Actual Behavior
In v0.12-alpha1, these attributes are not being preserved as expected and so Terraform plans to _unset_ them in order to match the configuration:

```
  # aws_vpc.main will be updated in-place
  ~ resource "aws_vpc" "main" {
        arn                              = "arn:aws:ec2:us-west-2:1874183:vpc/vpc-0f70dddd01f92df79"
      - assign_generated_ipv6_cidr_block = false -> null
        cidr_block                       = "10.1.0.0/16"
        default_network_acl_id           = "acl-09137e7a172eb3e5a"
        default_route_table_id           = "rtb-03094e58895729970"
        default_security_group_id        = "sg-029e167fb2cc7165f"
        dhcp_options_id                  = "dopt-11ac7e74"
        enable_classiclink               = false
        enable_classiclink_dns_support   = false
        enable_dns_hostnames             = false
      - enable_dns_support               = true -> null
        id                               = "vpc-0f70dddd01f92df79"
      - instance_tenancy                 = "default" -> null
        main_route_table_id              = "rtb-03094e58895729970"
        tags                             = {
            "Name" = "main vpc"
        }
    }
```

### Workaround

If you encounter this problem while testing v0.12.0-alpha1 and wish to avoid these unnecessary changes, explicitly set these values in configuration to the default values that the provider chose. For example:

```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.1.0.0/16"

  assign_generated_ipv6_cidr_block = false
  enable_dns_support               = true
  instance_tenancy                 = "default"

  tags = {
    Name = "main vpc"
  }
}
```

**Comment by jbardin** [comment]
Fixed in master 🎉
