### ISSUE TITLE
module ordering causes template_file resource to fail?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#1916]
I am testing some of the new capabilities in Terraform v0.5.0, and now running into problems with the template_file resource. More information is here: https://groups.google.com/forum/#!topic/terraform-tool/MbEnBHMqV7E

This is so utterly simple, and I'm seeing `template_file` work when used without a module. I have also seen module ordering/dependency issues (an instance not created / deployed before the module), and so I am wondering if this is a bug / problem with module ordering/dependencies, and not really `template_file` directly.

**Comment by mitchellh** [comment]
@ketzacoatl I jus fixed this on master. Will be in 0.5.1

**Comment by ketzacoatl** [comment]
@mitchellh you are amazing! I guess I should pull/build/test `master`..

**Comment by ketzacoatl** [comment]
@mitchellh 

`make dev` is failing for me on `master`:

```
1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/hashicorp/terraform/command
/home/sandy/go/gopath/src/github.com/hashicorp/terraform/command/cli_ui.go:26: u.Ui.AskSecret undefined (type cli.Ui has no field or method AskSecret)
/home/sandy/go/gopath/src/github.com/hashicorp/terraform/command/cli_ui.go:26: not enough arguments to return

make: *** [dev] Error 1
```

is this me building the project incorrectly or an error on master?

**Comment by mitchellh** [comment]
@ketzacoatl Update deps

**Comment by chiefy** [comment]
:+1: just ran into this in 0.5.0 - looks like it's time to upgrade, thanks @mitchellh
