### ISSUE TITLE
terraform.tfvars not automatically loaded in v0.11.9

### ISSUE THREAD

**Issue by Lasering** [hashicorp/terraform#19174]
### Terraform Version
```
Terraform v0.11.9
```

### Terraform Configuration Files
`variables.tf`:
```hcl
variable "test" {}
variable "foo" {}
```

`testing.tfvars`:
```hcl
test = "test"
```

`terraform.tfvars`:
```hcl
foo = "foo"
```

### Expected Behavior
The file `terraform.tfvars` should be auto loaded as per the [documentation](https://www.terraform.io/docs/commands/apply.html#var-file-foo).

### Actual Behavior
```
terraform init
terraform apply -var-file=testing.tfvars -auto-approve
```
It asks a value for `var.foo` which should be already set by the auto loaded file `terraform.tfvars`.

### Aditional context
Works correctly for 0.11.8 it only fails on 0.11.9.

**Comment by robinkb** [comment]
I am seeing the same problem. Additionally, files named `*.auto.tfvars` are not automatically loaded either.

**Comment by svanharmelen** [comment]
That is correct @robinkb, this is the same problem as reported in #19163. I'll close this one so we can converge the discussion in issue #19163.

There is a PR with a fix, so hopefully this will be fixed and released shortly. Sorry for any inconvenience caused!
