### ISSUE TITLE
terrafom plan

### ISSUE THREAD

**Issue by charlie3620** [hashicorp/terraform#19172]
i have created all the script ready with me and i am trying to execute that terraform script so in that process i have come across the commands

1. terraform init
2. terraform plan
3. terraform apply

terraform init initialized all the modules
terraform plan asked about the inputs that are required

so my doubt is does terraform plan creates the environment in the cloud

**Comment by ryota548** [comment]
terraform plan is 'dry run'.
you can see the diff between the environment in the cloud and local.
So it isn't created one in the cloud.

**Comment by charlie3620** [comment]
Thank you for the answer now i understood
