### ISSUE TITLE
Tests are completely broken making development difficult

### ISSUE THREAD

**Issue by Skarlso** [hashicorp/terraform#19191]
Hi @jbardin.

So, your commit from 8 days ago absolutely broke the test environment.

Are there any commits happening to fixing that? Because it makes development terraform difficult as in I'm not sure what's broken. 

If such a thing is not in progress, I would gladly start investigating what's wrong.

**Comment by apparentlymart** [comment]
Hi @Skarlso,

There are some remaining tests failing after the merger of the work for the v0.12 release. Work on this is ongoing and will continue next week.

In the mean time I would suggest pausing work in the packages that have failing tests.

**Comment by Skarlso** [comment]
@apparentlymart Thank you very much for the clarification!! That makes sense now. :)

I'll wait. :)
