### ISSUE TITLE
alpha1: plan after apply shows many zero value => null changes

### ISSUE THREAD

**Issue by mitchellh** [hashicorp/terraform#19206]
### Terraform Version
```
terraform → ~/bin/terraform version
Terraform v0.12.0-dev (009534d1016cd3b1d0d911f151520b04f8db453a)
+ provider.google v1.19.1-3-g59efc8b9
+ provider.null v1.0.0-4-g0b90acb
+ provider.random v2.0.0-4-gb282401
```

### Terraform Configuration Files
Exact same configuration as https://github.com/hashicorp/terraform/issues/19152

With master (2b075bbf8e322b8e2b40b9cc4901d10c95281651) and a recompiled Google provider, that issue now applies, but the `plan` output after a clean apply does not look right.

### Debug Output
https://gist.github.com/mitchellh/fe11621e551e9a92c4eb81492bf3f9f7

(Note: I already deleted these resources and changed any keys so any sensitive values in the log are fine)

### Expected Behavior
Plan should show know changes.

### Actual Behavior
Plan showed this:
https://gist.github.com/mitchellh/3b1f8f6ab8d67569dfe3c1f9fab0f3b7

### Steps to Reproduce
Take the config above and apply, then plan.

I'm happy to verify, too.

**Comment by jbardin** [comment]
Fixed in the current release
