### ISSUE TITLE
rds instance creation from snapshot issue

### ISSUE THREAD

**Issue by Nareshkg** [hashicorp/terraform#19220]
I have created rds instance from snapshot using snapshot_identifier. However after successful creation, I have tried to remove the snapshot_identifier value 
from snapshot_identifier='<snapshot_id> to snapshot_identifier= '', which is forcing the new resource.

My requirement is to create rds instance from snapshot and remove the snapshot references after successful creation.

-/+ module.oracle.aws_db_instance.rds (new resource required)
 id: "testdev" => <computed> (forces new resource)           ----------------------->forcing new resource
 address: "testdev.amazonaws.com" => <computed>
 allocated_storage: "1600" => "1600"
 apply_immediately: "true" => "true"
 arn: "arn:aws:rds:<ARN>:db:testdev" => <computed>
 auto_minor_version_upgrade: "false" => "false"
 availability_zone: "us-east-1a" => <computed>
 backup_retention_period: "15" => "15"
 backup_window: "00:00-03:00" => "00:00-03:00"
 ca_cert_identifier: "rds-ca-2015" => <computed>
 character_set_name: "AL32UTF8" => "AL32UTF8"
 copy_tags_to_snapshot: "false" => "false"
 db_subnet_group_name: "subnet-group" => "subnet-group"
 endpoint: "<ENDPOINT>" => <computed>
 engine: "oracle-ee" => "oracle-ee"
 engine_version: "12.1.0.2.v13" => "12.1.0.2.v13"
 final_snapshot_identifier: "<FINAL_SNAPSHOT>" => "<FINAL_SNAPSHOT>"
 hosted_zone_id: "<ZONE>" => <computed>
 iam_database_authentication_enabled: "false" => "false"
 identifier: "testdev" => "testdev"
 identifier_prefix: "" => <computed>
 instance_class: "db.m4.4xlarge" => "db.m4.4xlarge"
 iops: "0" => "0"
 kms_key_id: "" => "arn:aws:kms:<ARN>" (forces new resource)           --------------> Forcing new resource
 license_model: "bring-your-own-license" => "bring-your-own-license"
 maintenance_window: "sun:05:00-sun:06:00" => "sun:05:00-sun:06:00"
 monitoring_interval: "5" => "5"
 monitoring_role_arn: "arn:aws:iam:<ARN>" => "<ARN>"
 multi_az: "false" => "false"
 name: "TESTDV" => "TESTDV"
 option_group_name: "testdev-option-group" => "testdev-option-group"
 parameter_group_name: "testdev-param-grp" => "testdev-param-grp"
 password: <sensitive> => <sensitive> (attribute changed)
 port: "1521" => "1521"
 publicly_accessible: "false" => "false"
 replicas.#: "0" => <computed>
 resource_id: "<RESOURCE_ID>" => <computed>
 skip_final_snapshot: "false" => "false"
 snapshot_identifier: "testdv-snapshot-oct292018" => "" (forces new resource) ----------------------> forcing new resource, Even if I don't remove the value it is same.
 status: "available" => <computed>
 storage_encrypted: "false" => "true" (forces new resource) ---------------------------> Forcing new resource
 storage_type: "gp2" => "gp2"
 timezone: "" => <computed>
 username: "awsdbadmin" => "awsdbadmin"
 vpc_security_group_ids.#: "1" => "1"
 vpc_security_group_ids.<id>: "<SG_ID>" => "<SG_ID>"

 ~ module.oracle.aws_route53_record.rds_route53
 records.#: "" => <computed>

Plan: 1 to add, 2 to change, 1 to destroy.

**Comment by Hmerac** [comment]
Same issue goes for me...
