### ISSUE TITLE
aws_subnet should have a aws_nework_acl associated to it

### ISSUE THREAD

**Issue by mzupan** [hashicorp/terraform#1923]
Right now you associate a subnet to a network ACL which seems backward to me. You can have multiple subnets sharing the same network ACL. This is pretty common for setting up a multi-AZ infrastructure where servers live in different subnets that live in separate AZs. 

It creates a lot of un-needed duplication to create network acl per subnet. 

I found #1735 which was closed but seems like he is asking the same thing. I'd be fine with allowing a list of subnets on the acl resource.

**Comment by catsby** [comment]
Thanks @mzupan – #1717 is for the same feature request, which I hope to work on soon. Closing this for now.

**Comment by catsby** [comment]
I opened #1931 for this

**Comment by catsby** [comment]
1931 was just merged, will go out in next release
