### ISSUE TITLE
resource_aws_db_instance

### ISSUE THREAD

**Issue by rismoney** [hashicorp/terraform#1925]
is there a way to specify the vpc for creating an RDS instance?

**Comment by AlexanderEkdahl** [comment]
```
resource "aws_db_instance" "default" {
    identifier = "db-name"
    db_subnet_group_name = "${aws_db_subnet_group.default.id}"
}

resource "aws_db_subnet_group" "default" {
    name = "main"
    description = "Main group of subnets"
    subnet_ids = ["${aws_subnet.primary.id}", "${aws_subnet.secondary.id}"]
}
```

Hope that helps!

**Comment by phinze** [comment]
Yep thanks @AlexanderEkdahl that's exactly right - you associate an RDS DB Instance with a VPC via Subnet -> DB Subnet Group.

For more information, you can check out the AWS docs here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.html
