### ISSUE TITLE
Terraform documentation needs improvement

### ISSUE THREAD

**Issue by KbLev** [hashicorp/terraform#19252]
All of the pages give you just the **bare minimum** information about everything. The most basic examples. If you want more info you have to dig github and try to find code samples there.

For example I was trying to see how to consume outputs from modules.
Just a one liner [example](https://www.terraform.io/intro/getting-started/outputs.html) on the definition. But no example on how to use the output somewhere else.

Then, I wanted to see how to do [lookups](https://www.terraform.io/docs/configuration/interpolation.html#lookup-map-key-default-).
There's not one example on lookups, at least not on the interpolations page. All functions should have their own dedicated page with a few examples at least.

The resources list one example, and usually the basic ones. And exported values are not included, though this would be really informational. For example an _azurerm_virtual_network_gateway_ can be of type VPN and ExpressRoute with very different configuration. It was nice to have two samples.

The entire Terraform documentation screams "let's just complete this with the least possible effort". Hey, less potential for errors and less updating later.

**Comment by JarredAxsen** [comment]
I also agree on the points made above. 

I will also point out under larger providers like AWS it is truly annoying to have to scroll for hours to get to the correct link on the left hand side. 

Can you please create drop downs in the navigation?

**Comment by paultyng** [comment]
I'll respond to your issues, but before that, we expect kind discourse. We accept criticism and are happy to respond, but criticism can be delivered constructively without expletives and what may feel like attacks. 

Some of these things are being address in 0.12. For example, functions are each getting their own page, here is an example for [`lookup`](https://github.com/hashicorp/terraform/blob/master/website/docs/configuration/functions/lookup.html.md).

The AWS navigation is definitely something we realize is an issue, the provider has grown so quickly we haven't had an opportunity to revisit the navigation to improve its usability (most of us are backend / Go engineers, so UI improvements are as easy to do) but its definitely something we realize is an issue and are trying to find a better solution.

If specific providers or resources are missing examples you would like, the provider repositories and documentation are separate from Terraform's core repository (and not always maintained by HashiCorp, although both the mentioned AWS and AzureRM providers are). You can open issues on those repositories or submit PRs to their website files directly:

* https://github.com/terraform-providers/terraform-provider-aws
* https://github.com/terraform-providers/terraform-provider-azurerm

**Comment by apparentlymart** [comment]
As Paul said, documentation is an ongoing effort and we will continue to improve it alongside development work.

Since this issue does not represent a discrete, actionable piece of work I'm going to close it out. This isn't meant to imply that there isn't work to do here, but that "the documentation needs to be improved" is not something that could ever be "complete" as stated. If there is specific feedback you'd like to give that isn't already covered by an issue, please do feel free to open issues or PRs in either this repository (for the general Terraform documentation) or in the provider repositories (for provider-specific documentation) and those changes will be prioritized along with other work.

Thanks!
