### ISSUE TITLE
Generated command/internal_plugin_list.go whitespace format mismatch terraform-0.11.10 go1.11

### ISSUE THREAD

**Issue by jfkw** [hashicorp/terraform#19251]
### Terraform Version

```
0.11.10
```

### Expected Behavior

In versions of terraform where `go1.11+` is required per `README` (`terraform-0.11.10` in this report), Generated `command/internal_plugin_list.go` should use new `go fmt` whitespace rules, i.e. vertically align map values.

I sympathize that vertical alignment of keys is likely a difficult thing for generated code to support.

### Actual Behavior

With `terraform-0.11.10` and `go1.11.1`, running make will generate or regenerate `command/internal_plugin_list.go` with `go1.10` map value formatting, i.e. fixed number of spaces after the `:` separator between keys and values.

Because of this, subsequent runs of `make` will required a `make fmt` step between runs:

```
$ make
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./command/internal_plugin_list.go
You can use the command: `make fmt` to reformat code.
make: *** [Makefile:85: fmtcheck] Error 1
```
```
$ make fmt
gofmt -w $(find . -name '*.go' | grep -v vendor)
```
```
$ make
(...)
```
```
$ git diff
diff --git a/command/internal_plugin_list.go b/command/internal_plugin_list.go
index 7993e9a..1dd9245 100644
--- a/command/internal_plugin_list.go
+++ b/command/internal_plugin_list.go
@@ -17,10 +17,11 @@ import (
 var InternalProviders = map[string]plugin.ProviderFunc{}

 var InternalProvisioners = map[string]plugin.ProvisionerFunc{
-       "chef":            chefprovisioner.Provisioner,
-       "file":            fileprovisioner.Provisioner,
-       "habitat":         habitatprovisioner.Provisioner,
-       "local-exec":      localexecprovisioner.Provisioner,
-       "remote-exec":     remoteexecprovisioner.Provisioner,
-       "salt-masterless": saltmasterlessprovisioner.Provisioner,
+       "chef":   chefprovisioner.Provisioner,
+       "file":   fileprovisioner.Provisioner,
+       "habitat":   habitatprovisioner.Provisioner,
+       "local-exec":   localexecprovisioner.Provisioner,
+       "remote-exec":   remoteexecprovisioner.Provisioner,
+       "salt-masterless":   saltmasterlessprovisioner.Provisioner,
+
 }
```

### Steps to Reproduce

Run make on `terraform-0.11.10` with `go1.11` or newer, then repeat.

### Additional Context

As a sanity check, I did want to confirm that the requirement for `go1.11` with `terraform-0.11.10` (per the `README`) is accurate? In `terraform-0.11.10`, there is no `go.mod` committed, it is generated on the first run to `make tools`:

```
$ make tools
go get -u github.com/kardianos/govendor
go: creating new go.mod: module github.com/hashicorp/terraform
go: copying requirements from vendor/vendor.json
```

There certainly could be other `go1.11` features besides modules that moved the requirement forward. The issue comes up in packaging, where the latest go version is not always immediately available.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity - much has changed in our build process since this was opened.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
