### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by gloriajw-devmynd** [hashicorp/terraform#19268]
* aws_autoscaling_group.asg_staging_appservers: aws_autoscaling_group.asg_staging_appservers: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.8
    Resource ID: aws_autoscaling_group.asg_staging_appservers
    Mismatch reason: attribute mismatch: availability_zones.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"vpc_zone_identifier.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.1639588218":*terraform.ResourceAttrDiff{Old:"us-gov-west-1a", New:"us-gov-west-1a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.4172509376":*terraform.ResourceAttrDiff{Old:"", New:"us-gov-west-1b", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "availability_zones.#":*terraform.ResourceAttrDiff{Old:"1", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"vpc_zone_identifier.2260470919":*terraform.ResourceAttrDiff{Old:"", New:"subnet-f03fe494", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.3653427496":*terraform.ResourceAttrDiff{Old:"subnet-8895cfff", New:"subnet-8895cfff", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "vpc_zone_identifier.#":*terraform.ResourceAttrDiff{Old:"1", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by apparentlymart** [comment]
Hi @gloriajw-devmynd! Sorry for this error.

It looks like this is the same problem as #16282, so I'm going to close this out just to consolidate the discussion over there.

We are expecting that this class of error will be addressed by the changes for the forthcoming v0.12.0 release, but we've not verified that yet. We'll post updates on #16282 once we've completed that verification.

Thanks for reporting this!

**Comment by gloriajw-devmynd** [comment]
Hi Martin, Thank you. I dicovered that removing the GPG check gets it a bit
futher in the installation, but it still fails.
Any tips you can provide would be great.
Thanks again,
Gloria

**Comment by gloriajw-devmynd** [comment]
Ah, disregard that. I filed several bugs and thought you replied to
another. In this particular case I got lucky. All dependencies were
created, and the run after this one worked without a hitch. Not sure if
others had similar results.

**Comment by apparentlymart** [comment]
Hi @gloriajw-devmynd. It is a typical symptom with this class of bug that re-running `terraform apply` makes it go away, so I'm glad to see that worked for you in this case too. We think this is because of the plan including a value that is not known until apply time; once you've run `terraform apply` once, that value has been determined and saved in the state so that it's available on the next run.

**Comment by gloriajw-devmynd** [comment]
Makes perfect sense, that's how it appeared to me when I saw the error.
Thanks for responding so quickly. Cheers!
