### ISSUE TITLE
Terraform alpha 0.12 should be 1.0-alpha2

### ISSUE THREAD

**Issue by damon-atkins** [hashicorp/terraform#19276]
### Terraform Version
```
Terraform v0.12.0-alpha2
+ provider.aws v1.40.0-6-gb23683732
+ provider.local v1.1.0-5-ga2df742
+ provider.null v1.0.0-5-gf54ff98
+ provider.random v2.0.0-5-g612dff2
+ provider.template v1.0.0-5-g317c9c9
```
### Expected Behavior
Terraform should have a major version bump. e.g. Version 1
Plugins should be sourced from Version 1 repo instead of the same place as version 0

### Actual Behavior
Alpha version should not download incompatible plugins.

Or introduce a plugin API version into the download plugin path.

**Comment by apparentlymart** [comment]
Hi @damon-atkins,

I think you are essentially reporting the same thing as #19221 here, so I'm going to close this just to consolidate discussion over there. Thanks!
