### ISSUE TITLE
JSON-oriented diffs not working consistently

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#19275]
The new diff renderer for v0.12.0 includes a heuristic for detecting whether before and after strings are both JSON-formatted and showing a JSON structural diff.

![](https://user-images.githubusercontent.com/20180/47956407-3f341600-df61-11e8-8f00-0f3f444411a7.png)

...but the heuristic seems to not be good enough right now, since it's failing to produce diffs in some cases such as IAM policy JSON, while it works okay for simpler situations.

Structural diff of IAM policies is one of the main use-cases for this heuristic, so we should figure out what's going on here and ensure that this sort of JSON gets the structural diff treatment.

**Comment by radeksimko** [comment]
I wasn't able to reproduce this exact issue, although I can confirm that JSON diff-ing isn't working quite well:

```hcl
resource "aws_iam_policy" "example" {
  name        = "example-radek"
  path        = "/"
  description = "My example policy"

  policy = <<EOF
{
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ],
  "Version": "2012-10-17"
}
EOF
}
```
applying this change:
```diff
    {
      "Action": [
        "ec2:Describe*",
+       "ec2:Create*"
      ],
```

<img width="824" alt="screen shot 2019-01-15 at 14 53 07" src="https://user-images.githubusercontent.com/287584/51188155-4b2f4300-18d5-11e9-8e71-83dd7bd1b119.png">

@apparentlymart I assume you don't have the config used in your screenshot anywhere anymore?
