### ISSUE TITLE
Env variables require default values

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#1930]
The work to allow setting Terraform variables via environment variables (#62 and #1621) is great, but it requires that variables have default values - which is *not* ideal for variables such as AWS credentials. I would expect variables passed via environment variables to not require defaults the same as if they were set in a tfvars file.

```
$ TF_VAR_aws_access_key=asdf TF_VAR_aws_secret_key=1234 terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * Required variable not set: aws_access_key
  * Required variable not set: aws_secret_key
```

**Comment by mitchellh** [comment]
Ah, this is a bug. Thanks.
