### ISSUE TITLE
Error validating backend config - terraform is not recognizing the 'name' key in the config block of terraform_remote_state

### ISSUE THREAD

**Issue by arkwebb** [hashicorp/terraform#19302]
### Terraform Version

```
[terraform](url) -v
Terraform v0.11.10
+ provider.archive v1.1.0
+ provider.google v1.19.1
+ provider.kubernetes v1.3.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```
data "terraform_remote_state" "main_state" {
  backend = "gcs"

  config {
    bucket = "${var.tf_state_project}"
    prefix = "/terraform.tfstate"
    name   = "default.tfstate"
  }
}
```

### Debug Output

[tf-errorlog.zip](https://github.com/hashicorp/terraform/files/2555197/tf-errorlog.zip)

### Expected Behavior

terraform plan should complete successfully

### Actual Behavior

After upgrading from 0.11.8 to 0.11.10, executing terraform plan returns the following error:
Error: Error refreshing state: 1 error(s) occurred:

* data.terraform_remote_state.main_state: 1 error(s) occurred:

* data.terraform_remote_state.main_state: data.terraform_remote_state.main_state: error validating backend config: 1 error(s) occurred:

* : invalid or unknown key: name

### Steps to Reproduce

1. 'terraform plan'

**Comment by spmsaj** [comment]
is there an update on this? key works with aws and azure

**Comment by aerostitch** [comment]
There's no `name` key for gcs backend configs: https://www.terraform.io/docs/backends/types/gcs.html
You'll need to use prefix as the name:
```

**Comment by teamterraform** [comment]
Since `name` is not a valid attribute for this backend configuration, this appears to be working as intended.
