### ISSUE TITLE
"diffs didn't match during apply" for aws_instance credit_specification cpu_credits

### ISSUE THREAD

**Issue by kurtwheeler** [hashicorp/terraform#19315]
### Terraform Version
```
Terraform v0.11.8
```

### Terraform Configuration Files

https://github.com/AlexsLemonade/refinebio/tree/dev/infrastructure

### Debug Output
Because this is a production deploy it is not easy to simply modify the terraform command.

### Crash Output

https://gist.github.com/kurtwheeler/dfaa53937b352bac831e1aa06223255d

### Expected Behavior
It shouldn't have crashed

### Actual Behavior
It did crash.

### Steps to Reproduce
This was caused by an automated script triggered by CircleCI. This script:
https://github.com/AlexsLemonade/refinebio/blob/dev/.circleci/remote_deploy.sh
calls this script: https://github.com/AlexsLemonade/refinebio/blob/dev/.circleci/run_terraform.sh
which ran this script:
https://github.com/AlexsLemonade/refinebio/blob/dev/infrastructure/deploy.sh
which is what actually runs terraform commands.

However this has run successfully many times and I'm not sure what was different about this one.

### Additional Context
This happened during our automated deploy process to our production stack. This is the first deploy to our production stack after modifying the process, but this has been tested about half a dozen time on our staging stack. I have rerun our deploy process and it completed successfully. I'm not sure what was different this time or when it might happen again.

**Comment by bflad** [comment]
@kurtwheeler could you also provide your AWS provider version? This may be related: https://github.com/terraform-providers/terraform-provider-aws/issues/5853

**Comment by kurtwheeler** [comment]
I have a `.terraform/plugins/linux_amd64/terraform-provider-aws_v1.31.0_x4` file so I think it's 1.31.0

**Comment by kurtwheeler** [comment]
Does anyone have any ideas of what I might be able to do to workaround this until a fix is devised? I had to redeploy prod today and I've hit this three times in a row. I can't stand my API server back up because of this so my website is down.

**Comment by kurtwheeler** [comment]
Oh wait, now I see! I will try updating my AWS provider version!

**Comment by kurtwheeler** [comment]
Updating my provider version fixed this issue. Thank!
