### ISSUE TITLE
StateFunc not applied to nested element inside a Set.

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform#19318]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
resource "google_dataproc_cluster" "accelerated_cluster" {
	name                  = "dproc-cluster-test-%s"
	region                = "us-central1"

	cluster_config {
		gce_cluster_config {
			zone = "us-central1-a"
		}

		master_config {
			accelerators {
				accelerator_type  = "nvidia-tesla-k80"
				accelerator_count = "1"
			}
		}

		worker_config {
			accelerators {
				accelerator_type  = "nvidia-tesla-k80"
				accelerator_count = "1"
			}
		}
	}
}
```

### Debug Output

n/a

### Crash Output

n/a

### Expected Behavior

StateFunc is applied, Set hash function stays the same and my canonicalized string is stored.

### Actual Behavior

https://gist.github.com/rileykarson/8cf88c12a75987830aa7575daf5ce5f1#file-gistfile1-txt

### Steps to Reproduce

```
make testacc TEST=./google TESTARGS='-run=TestAccDataprocCluster_withAccelerators'
```

(once https://github.com/terraform-providers/terraform-provider-google/pull/2411 has been merged)

### Additional Context

This was failing in the Google provider tests.

We've worked around this by only setting the shortened name in `Read`, but this behaviour _isn't great_ and means that users aren't able to use full/partial self links for GPUs - only names.

Linking to the PR we're generating from so that line #s are consistent;

[This field should have a `StateFunc` as follows](https://github.com/GoogleCloudPlatform/magic-modules/pull/688/files/4912077b9e517bf7df641b8e4f5d29e1d08b508e#diff-b8b02a5de2ba80d7861abe2b791006adR387)

```
StateFunc: NameFromSelfLinkStateFunc
```

[The wrapping method on this line should be removed](https://github.com/GoogleCloudPlatform/magic-modules/pull/688/files/4912077b9e517bf7df641b8e4f5d29e1d08b508e#diff-b8b02a5de2ba80d7861abe2b791006adR797) because the `StateFunc` replaces it.

When trying to use the StateFunc we get the error above; I suspect it has something to do with this being a nested resource inside a set inside a list.

### References

https://github.com/terraform-providers/terraform-provider-google/pull/2411

----

If you need me to make a branch where this can be repro'ed, just let me know.

**Comment by jbardin** [comment]
Hi @rileykarson,

Thanks for filing the issue. This should be covered by #19536
