### ISSUE TITLE
"panic: can't use ElementIterator on null value" with azurerm_virtual_machine

### ISSUE THREAD

**Issue by jonathansd1** [hashicorp/terraform#19320]
### Terraform Version
```
$ terraform -v
Terraform v0.12.0-alpha2
+ provider.azurerm v1.17.0-5-ga3b48ba3
```

### Terraform Configuration Files
This crash report involves a nested module. For clarity, I've pared down the templates and left the applicable code intact. The files below produce the error found further down.

Files appear as thus:
```
.
├── main.tf
├── network
│   ├── main.tf
│   └── variables.tf
└── standalone_vm
    ├── main.tf
    └── variables.tf
```
https://gist.github.com/jonathansd1/ab75ff3e90e365584685459c2aab0af4

### Debug Output
https://gist.github.com/jonathansd1/f5e547b9e7a0b2901ed4da7c8876b238

### Crash Output
https://gist.github.com/jonathansd1/ed63690862022f8c880f9cb945f5338d

### Expected Behavior
Azure VM created!

### Actual Behavior
Terraform crashes.

### Steps to Reproduce
`terraform init`
`terraform apply`

### Additional Context
As previously stated, the only other obvious "oddity" here is the use of a module nested in a module, but this shouldn't be a problem.

**Comment by jbardin** [comment]
Thanks for reporting the issue.
This one is already fixed in master.
