### ISSUE TITLE
0.12 alpha2 aws change cidr_blocks in security group wont update, produces error

### ISSUE THREAD

**Issue by alanmcg** [hashicorp/terraform#19333]
### Terraform Version

```
Terraform v0.12.0-alpha2
+ provider.aws v1.40.0-6-gb23683732
```

### Terraform Configuration Files

```resource "aws_security_group" "allow_office_ssh" {
  name        = "allow_office_stockholm_ssh"
  description = "Allow ssh inbound from stockholm office"
  vpc_id      = "${aws_vpc.operations.id}"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["81.19.176.143/32"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

```

### Expected Behavior

ip address in cidr_blocks should be updated for security group
### Actual Behavior

After apply with unchanged values, terraform correctly reports  that there are no changes to apply. After changing 1 digit in an ip address tf errors with:

Error: invalid value for "ingress.2523480797.self" in state: a bool is required

**Comment by apparentlymart** [comment]
Hi @alanmcg! Thanks for reporting this.

This seems like the same as #19215, but we're gonna leave this open for the moment to verify.

**Comment by jbardin** [comment]
Yup, this case was the same, which is now fixed in master.
Thanks!
