### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by achalupa74** [hashicorp/terraform#19344]
### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.aws v1.43.1

```

### Terraform Configuration Files
attached

### Debug Output
2018/11/10 14:05:09 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_security_group_rule.ingress_-1_sharedservices_cloud_insight_sharedservices_mixer_0_0_cloud_insight: connection is shut down
2018/11/10 14:05:09 [ERROR] root: eval: *terraform.EvalSequence, err: aws_security_group_rule.ingress_-1_sharedservices_cloud_insight_sharedservices_mixer_0_0_cloud_insight: connection is shut down
2018/11/10 14:05:09 [TRACE] [walkRefresh] Exiting eval tree: aws_security_group_rule.ingress_-1_sharedservices_cloud_insight_sharedservices_mixer_0_0_cloud_insight
2018/11/10 14:05:09 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_security_group_rule.ingress_tcp_all__sharedservices_mercury_api_elb_443_443_all: connection is shut down
2018/11/10 14:05:09 [ERROR] root: eval: *terraform.EvalSequence, err: aws_security_group_rule.ingress_tcp_all__sharedservices_mercury_api_elb_443_443_all: connection is shut down
2018/11/10 14:05:09 [TRACE] [walkRefresh] Exiting eval tree: aws_security_group_rule.ingress_tcp_all__sharedservices_mercury_api_elb_443_443_all
2018/11/10 14:05:09 [TRACE] root: eval: *terraform.EvalSequence
2018/11/10 14:05:09 [TRACE] root: eval: *terraform.EvalGetProvider
2018/11/10 14:05:09 [TRACE] root: eval: *terraform.EvalReadState
2018/11/10 14:05:09 [TRACE] root: eval: *terraform.EvalRefresh
2018/11/10 14:05:09 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_security_group_rule.ingress_tcp_release_release_sharedservices_jump_22_47001_release_eng_cidr_block: connection is shut down
2018/11/10 14:05:09 [ERROR] root: eval: *terraform.EvalSequence, err: aws_security_group_rule.ingress_tcp_release_release_sharedservices_jump_22_47001_release_eng_cidr_block: connection is shut down
2018/11/10 14:05:09 [TRACE] [walkRefresh] Exiting eval tree: aws_security_group_rule.ingress_tcp_release_release_sharedservices_jump_22_47001_release_eng_cidr_block
2018/11/10 14:05:09 [TRACE] dag/walk: upstream errored, not walking "provider.aws.sharedservices_security_rules (close)"
2018/11/10 14:05:09 [TRACE] dag/walk: upstream errored, not walking "root"
2018/11/10 14:05:10 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-11-10T14:05:10.106Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Crash Output
attached

### Expected Behavior
terraform plan should not crash

### Actual Behavior
plan has been working for a few weeks.  just started crashing out of the blue.  No changes to the TF.  plan should be returning 0 changes.

### Steps to Reproduce
1. terraform init
2. terraform plan 

[sharedservices_security_group_rules.tf.txt](https://github.com/hashicorp/terraform/files/2568487/sharedservices_security_group_rules.tf.txt)
[terraform.tfvars.txt](https://github.com/hashicorp/terraform/files/2568488/terraform.tfvars.txt)

[crash.log](https://github.com/hashicorp/terraform/files/2568484/crash.log)

**Comment by bflad** [comment]
Hi @achalupa74 👋 Sorry for the trouble here.

This crash started occurring due to a change made in version 1.43.1 of the AWS provider. We have an open issue (https://github.com/terraform-providers/terraform-provider-aws/issues/6416) and pending fix (https://github.com/terraform-providers/terraform-provider-aws/pull/6419) that will be released in the next version of the AWS provider (either 1.43.2 or 1.44.0), likely on Monday. To consolidate discussions and efforts, I'm going to close this issue in preference of the existing ones in the AWS provider. 👍 

If you're in need of an immediate workaround, you can pin your AWS provider version in your configuration via:

```hcl
provider "aws" {
  # ... potentially other configuration ...
  version = "1.43.0"
}
```

Then run `terraform init`.

For reference, matching portion of the crash log:

```
2018-11-10T14:11:57.196Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4.exe: panic: runtime error: invalid memory address or nil pointer dereference
2018-11-10T14:11:57.196Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4.exe: [signal 0xc0000005 code=0x0 addr=0x0 pc=0x23fb523]
2018-11-10T14:11:57.196Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4.exe: 
2018-11-10T14:11:57.196Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4.exe: goroutine 371 [running]:
2018-11-10T14:11:57.196Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4.exe: github.com/terraform-providers/terraform-provider-aws/aws.findRuleMatch(0xc000b36080, 0xc000b1f560, 0x5, 0x5, 0x1, 0x0)
2018-11-10T14:11:57.196Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_security_group_rule.go:433 +0x73
2018-11-10T14:11:57.196Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4.exe: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSecurityGroupRuleRead(0xc000260b60, 0x2d049a0, 0xc00021a300, 0xc000260b60, 0x0)
2018-11-10T14:11:57.196Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4.exe: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_security_group_rule.go:286 +0x604
```
