### ISSUE TITLE
Errors in `~/.terraformrc` don't propagate to the user

### ISSUE THREAD

**Issue by jacobbednarz** [hashicorp/terraform#19363]
I made a boo-boo when typing "provider" into my `~/.terraformrc` file (which I use to swap between "dev" and "stable" versions) and instead of the error message letting me know that there was an incorrect directive in the file, it said it was empty. I would have expected this to say something along the lines of "invalid terraform configuration file" and exit or similar.

### Terraform Version

```
$ terraform -v
Terraform v0.11.10
```

### Terraform Configuration Files

```hcl
# ~/.terraformrc
roviders {
  cloudflare =  "/Users/jacob/src/go/src/github.com/terraform-providers/terraform-provider-cloudflare/terraform-cloudflare-provider"
}
```

### Expected Behavior

To be able to identify the difference between an empty config (per the error message) and an invalid configuration file.

### Actual Behavior

Silently continued on after outputing a `command: empty terraform config, returning nil` message.

### Steps to Reproduce

1. Create a `~/.terraformrc` file
1. Put in the content from above
1. Expect to use custom provider per `~/.terraformrc`

### Debug output

```
2018/11/14 09:32:30 [INFO] Terraform version: 0.11.10
2018/11/14 09:32:30 [INFO] Go runtime version: go1.11.1
2018/11/14 09:32:30 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.10/bin/terraform", "plan"}
2018/11/14 09:32:30 [DEBUG] Attempting to open CLI config file: /Users/jacob/.terraformrc
2018/11/14 09:32:30 Loading CLI configuration from /Users/jacob/.terraformrc
2018/11/14 09:32:30 [INFO] CLI command args: []string{}
2018/11/14 09:32:30 [INFO] command: empty terraform config, returning nil
2018/11/14 09:32:30 [DEBUG] command: no data state file found for backend config
2018/11/14 09:32:30 [DEBUG] New state was assigned lineage "0862cb14-bc3b-2619-ae5c-cbbe225f9f4e"
2018/11/14 09:32:30 [INFO] command: backend initialized: <nil>
```

**Comment by jacobbednarz** [comment]
Thanks for the additional information @apparentlymart. This isn't a huge deal so happy to patiently wait for the language updates in 0.12 😄

**Comment by mildwonkey** [comment]
I can confirm that terraform now displays error messages from decoding the `.terraformrc` file:


Error: Error parsing /Users/kristin/.terraformrc: At 2:22: Unknown token: 2:22 IDENT notabool

Thanks for reporting this!
