### ISSUE TITLE
Adding backends destroys existing backends

### ISSUE THREAD

**Issue by yinglliu** [hashicorp/terraform#19369]
### Terraform Version

```
$ terraform -version
Terraform v0.11.10
```

### Terraform Configuration Files

```hcl

In the example/main.tf:
resource "oci_core_instance" "backend" {
  count               = "${var.backend_count}"
  availability_domain = "${var.ad}"
  compartment_id      = "${var.compartment_ocid}"
  display_name        = "backend_ad${count.index+1}"
  shape               = "${var.backend_shape}"
  subnet_id           = "${oci_core_subnet.bs.*.id[count.index]}"
}

module "load_balancer" {
  source                          = "../"
  backend_count                   = "${var.backend_count}"
  backend_ips                     = ["${oci_core_instance.backend.*.private_ip}"]
  backend_ports                   = "${var.backend_ports}"
}

In the main.tf:
resource "oci_load_balancer_backend" "this" {
  count            = "${var.backend_count}"
  load_balancer_id = "${oci_load_balancer.this.id}"
  backendset_name  = "${oci_load_balancer_backendset.this.name}"
  ip_address       = "${var.backend_ips[count.index%length(var.backend_ips)]}"
  port             = "${var.backend_ports[count.index%length(var.backend_ports)]}"
}
```

### Steps to Reproduce

1. run terraform apply

2. increase backend count from 2 to 3 and re-apply

### Expected Behavior

expected: create 2 new resources

### Actual Behavior

actual: 4 to add, 0 to change, 2 to destroy.

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  + oci_core_instance.backend[2]
      id:                                       <computed>
      availability_domain:                      ""
      boot_volume_id:                           <computed>
      compartment_id:                           ""
      create_vnic_details.#:                    <computed>
      display_name:                             "backend_ad3"
      fault_domain:                             <computed>
      freeform_tags.%:                          <computed>
      image:                                    <computed>
      ipxe_script:                              <computed>
      launch_mode:                              <computed>
      launch_options.#:                         <computed>
      metadata.%:                               "2"
      metadata.assign_public_ip:                "1"
      metadata.ssh_authorized_keys:             ""
      private_ip:                               <computed>
      public_ip:                                <computed>
      region:                                   <computed>
      shape:                                    ""
      source_details.#:                         "1"
      source_details.0.boot_volume_size_in_gbs: <computed>
      source_details.0.source_id:               ""
      source_details.0.source_type:             "image"
      state:                                    <computed>
      subnet_id:                                ""
      time_created:                             <computed>

-/+ module.load_balancer.oci_load_balancer_backend.this[0] (new resource required)
      id:                                       "" => <computed> (forces new resource)
      backendset_name:                          "bs1" => "bs1"
      backup:                                   "false" => "false"
      drain:                                    "false" => "false"
      ip_address:                               "10.xx.xx.xx" => "${var.backend_ips[count.index%length(var.backend_ips)]}" (forces new resource)
      load_balancer_id:                         "" => ""
      name:                                     "xxx" => <computed>
      offline:                                  "false" => "false"
      port:                                     "80" => "80"
      state:                                    "SUCCEEDED" => <computed>
      weight:                                   "1" => "1"

-/+ module.load_balancer.oci_load_balancer_backend.this[1] (new resource required)
      id:                                       "" => <computed> (forces new resource)
      backendset_name:                          "bs1" => "bs1"
      backup:                                   "false" => "false"
      drain:                                    "false" => "false"
      ip_address:                               "10.xx.xx.xx" => "${var.backend_ips[count.index%length(var.backend_ips)]}" (forces new resource)
      load_balancer_id:                         "" => ""
      name:                                     "xxx" => <computed>
      offline:                                  "false" => "false"
      port:                                     "80" => "80"
      state:                                    "SUCCEEDED" => <computed>
      weight:                                   "1" => "1"

  + module.load_balancer.oci_load_balancer_backend.this[2]
      id:                                       <computed>
      backendset_name:                          "bs1"
      backup:                                   "false"
      drain:                                    "false"
      ip_address:                               "${var.backend_ips[count.index%length(var.backend_ips)]}"
      load_balancer_id:                         ""
      name:                                     <computed>
      offline:                                  "false"
      port:                                     "80"
      state:                                    <computed>
      weight:                                   "1"

Plan: 4 to add, 0 to change, 2 to destroy.

**Comment by alexng-canuck** [comment]
@apparentlymart Can we reopen this issue? It seems there's a limitation with modules resulting in unnecessary destroy/create when increasing count variable is involved. This may also be related to my comment on this issue: https://github.com/hashicorp/terraform/issues/17014#issuecomment-427530091
