### ISSUE TITLE
aws_security_group docs - wrong "cidr_block" key in ALLOW ALL rule example

### ISSUE THREAD

**Issue by juniorplenty** [hashicorp/terraform#1936]
https://www.terraform.io/docs/providers/aws/r/security_group.html

The example config for the ALLOW ALL egress backfill note is:

```
egress {
  from_port = 0
  to_port = 0
  protocol = "-1"
  cidr_block = "0.0.0.0/0"
}
```

...but `cidr_block` is an unrecognized key; it should be:
```
egress {
  from_port = 0
  to_port = 0
  protocol = "-1"
  cidr_blocks = ["0.0.0.0/0"]
}
```

**Comment by phinze** [comment]
Thanks for the report - this burned me too actually. Fixing now.
