### ISSUE TITLE
Kubernetes Secrets as a Backend

### ISSUE THREAD

**Issue by dramich** [hashicorp/terraform#19371]
### Current Terraform Version
```
Terraform v0.11.10
```

### Use-cases

Using Terraform to run infrastructure that is tied to a k8s cluster. Currently etcd is supported but that bypasses k8s secrets. 

### Attempted Solutions
None yet, I haven't added the backend.

### Proposal

I am going to be implementing a k8s backend and want to upstream it. Before doing so I wanted to make sure this wasn't something that already existed or was in the pipeline. If you have more insight let me know.

**Comment by pkolyvas** [comment]
Hey this was merged and we forgot the issue opened. Thanks to you and the k8s community for all the hard work.
