### ISSUE TITLE
Habitat provisioner puts user.toml in deprecated path 

### ISSUE THREAD

**Issue by nerdbeere** [hashicorp/terraform#19394]
### Terraform Version
`Terraform v0.11.10`

### Debug Output
from journalctl:

```
hab[3580]: hab-sup(AG): The xxx service was successfully loaded
hab[3580]: hab-sup(CF): The user configuration location at /hab/svc/xxx/user.toml is deprecated, consider putting it in /hab/user/xxx/config/user.toml
[…]
hab[3580]: xxx.default(UCW): Not watching user.toml, because it is located in deprecated path (/hab/svc/xxx)
```

### Expected Behavior
`user.toml` should be uploaded to `/hab/user/xxx/config/user.toml`

### Actual Behavior
`user.toml` is uploaded to `/hab/svc/xxx/user.toml`

### References
The code that's responsible for this behavior is located here: https://github.com/hashicorp/terraform/blob/master/builtin/provisioners/habitat/resource_provisioner.go#L724 
If it's just a matter of changing that one line let me know and I will open a PR.

**Comment by epcim** [comment]
yes, pls fix
