### ISSUE TITLE
Unrecognized attribute name - resource does not expect an attribute named "count" 

### ISSUE THREAD

**Issue by antonbabenko** [hashicorp/terraform#19398]
I may be asking a bit too earlier, so please let me know and I will wait for a few weeks.

I'd like to start upgrading [terraform-aws-modules](https://github.com/terraform-aws-modules/terraform-aws-vpc/) for Terraform 0.12 and facing some issues.

### Terraform Version
Terraform0.12-alpha2

### Terraform Configuration Files
```hcl
resource "aws_subnet" "database" {
  count = "${var.create_vpc && length(var.database_subnets) > 0 ? length(var.database_subnets) : 0}"

  vpc_id            = "${local.vpc_id}"
  cidr_block        = "${var.database_subnets[count.index]}"
  availability_zone = "${element(var.azs, count.index)}"

  tags = "${merge(map("Name", format("%s-${var.database_subnet_suffix}-%s", var.name, element(var.azs, count.index))), var.tags, var.database_subnet_tags)}"
}

```

### Expected Behavior
Syntax should be modified

### Actual Behavior
```
Error: Unrecognized attribute name

  on main.tf line 38, in resource "aws_subnet" "database":
  38:   count = "${var.create_vpc && length(var.database_subnets) > 0 ? length(var.database_subnets) : 0}"

Resource type aws_subnet does not expect an attribute named "count".
```

Well, yes `count` is used. Should I replace it?

### Steps to Reproduce

`terraform 0.12upgrade -yes`

**Comment by apparentlymart** [comment]
Hi @antonbabenko! Thanks for trying this out and reporting this.

The upgrade tool is not currently in a functional state. We plan to have an initial version of it ready during the beta phase of the release, but in the alphas we just have the basic skeleton of it with none of the upgrade rules actually encoded yet.

**Comment by antonbabenko** [comment]
Thanks, Martin! I will try to use it for normal use-cases (not upgrades) and report my findings.

**Comment by apparentlymart** [comment]
Although the upgrade tool is still not complete in 0.12.0-alpha4, there is now at least enough of it there for this particular configuration to upgrade successfully:

```diff
--- upgrade-with-count.tf.orig	2018-12-17 18:06:01.969807317 -0800
+++ upgrade-with-count.tf	2018-12-17 18:06:09.313913612 -0800
@@ -1,9 +1,20 @@
 resource "aws_subnet" "database" {
-  count = "${var.create_vpc && length(var.database_subnets) > 0 ? length(var.database_subnets) : 0}"
+  count = var.create_vpc && length(var.database_subnets) > 0 ? length(var.database_subnets) : 0
 
-  vpc_id            = "${local.vpc_id}"
-  cidr_block        = "${var.database_subnets[count.index]}"
-  availability_zone = "${element(var.azs, count.index)}"
+  vpc_id            = local.vpc_id
+  cidr_block        = var.database_subnets[count.index]
+  availability_zone = element(var.azs, count.index)
 
-  tags = "${merge(map("Name", format("%s-${var.database_subnet_suffix}-%s", var.name, element(var.azs, count.index))), var.tags, var.database_subnet_tags)}"
+  tags = merge(
+    {
+      "Name" = format(
+        "%s-${var.database_subnet_suffix}-%s",
+        var.name,
+        element(var.azs, count.index),
+      )
+    },
+    var.tags,
+    var.database_subnet_tags,
+  )
 }
```

Since this particular issue is fixed, I'm going to close this out now. Thanks for reporting it!

The configuration upgrade tool still isn't really ready to use in alpha4, but we plan to get it ready to deal with all of the upgrade situations we know about in time for the beta1 release, so that'll be the best time to start trying it out with existing modules.
