### ISSUE TITLE
variables do not appear to work correctly in modules

### ISSUE THREAD

**Issue by i0n** [hashicorp/terraform#1943]
Hey. I am using terraform built from master (v0.5.1) and I seem to have hit a bug when attempting to break my configuration out into modules.

So I have an infrastructure.tf file that looks like this:

```
provider "google" {
  alias = "staging-eu"
  project = "staging-infrastructure"
  account_file = ".auth/gcloud-staging-infrastructure.json"
  region = "europe-west1"
}

provider "google" {
  alias = "production-eu"
  project = "production-infrastructure"
  account_file = ".auth/gcloud-production-infrastructure.json"
  region = "europe-west1"
}


module "staging" {
  source = "./staging"
}

module "production" {
  source = "./production"
}
```

and then inside /staging/main.tf I might have something like this:

```
resource "google_compute_network" "cluster-1" {
  provider = "google.staging-eu"
  name = "cluster-1"
  ipv4_range = "10.240.0.0/16"
}
```
Which throws an error when I run terraform plan --input=false

I have also tried:

setting a variable inside the module
passing a variable from the module
Moving the provider block into the module

Nothing seems to work. The use case is modules being provisioned with different credentials in order to separate environments (staging and production for example)

**Comment by mikeyhill** [comment]
I might not fully understand your use case (and I'm also using AWS so that may be a factor), but I'm doing something similar that is working very well.

1. Main 'build.tf' file describes a run list for all environments and pulls in modules.  
2. Each module is passed  necessary configs, including my aws keys, region etc...  
3. The modules main provision file is where I set the provider.
4. Environment unique values (like the AWS key, images to be used etc... are stored in a separate variables file and called with -var-file=path/dev.tfvars)

**Comment by i0n** [comment]
Hey. Unfortunately I have tried a separate .tfvars file and that doesn't work either. I'm guessing that it's an issue that's provider specific if this is working on AWS...

**Comment by i0n** [comment]
Also, to clarify I just tried flattening the file topology and interpolating a standard variable in the provider declaration for a google_compute_network resource, and that doesn't work either.

**Comment by i0n** [comment]
Which means that even with a flat file, if using more than one gcloud provider you have to hardcode the provider string. It will work, but lots of repetition and the resources can't be copy pasted between projects without tweaking.

**Comment by mikeyhill** [comment]
for using separate tfvars files this is something that mitchellh enlightened me about.

main-build.tf
  - variables.tf
  - envs/
      - dev.tf
      - uat.tf
      - prod.tf

your variable file contains something like this:
    variable "virt" { description = "Type of virtualization to use for instances (hvm or pv)" }
    variable "hvm_ami" { description = "Base Centos 6.6 HVM AMI for provisioning resources" }
    variable "pv_ami" { description = "Base Centos 6.6 Paravirtual AMI for provisioning resources" }
    variable "ami_file_url" { description = "File URL to grab the AMI list from" }

env/dev.tf file includes something along these lines:
    virt		= "hvm"
    hvm_ami 	= "ami-ac24d491"
    pv_ami		= "ami-a3e55e93"
    ami_file_url= "https:/z.com/current.json"

When your run terraform just include -var-file=envs/dev.tf

**Comment by mikeyhill** [comment]
Expanding on this a bit (again, this has always worked for me, not sure about google provider)

main-build.tf

    /* List of modules to include */
    
    module "bq-chef" {
      source = "./chef"
      access_key   = "${var.access_key}"
      secret_key   = "${var.secret_key}"
      region       = "${var.region}"
      az1          = "${var.az1}"
      az2          = "${var.az2}"
      env          = "${var.env}"
      vpc_id                 = "${module.bq-vpc.main-vpc-id}"
      admin_subnet_1_id      = "${module.bq-vpc.admin-subnet-1-id}"
    }

chef module (provision.tf)

    /* Variables from main-build.tf */
    variable "access_key" {}
    variable "secret_key" {}
    variable "region" {}
    variable "env" {}
    variable "admin_subnet_1_id" {}
    variable "vpc_id" {}
    variable "az1" {}
    variable "az2" {}

    /* AWS Provider */
    provider "aws" {
      access_key  = "${var.access_key}"
      secret_key  = "${var.secret_key}"
      region      = "${var.region}"
    }

    /* Go build things */

**Comment by mitchellh** [comment]
Sorry could you verify what isn't working?

One issue I see is that you don't have any default provider set.

**Comment by i0n** [comment]
Where does it mention a default provider as a requirement in the docs?

**Comment by i0n** [comment]
I've abandoned using modules for now, don't really have time to hack on this so have just reverted to flat file. Oh also btw, have you considered using godep for dependency management? I just mention it because if you checkout the v0.4.2 tag and try and build you get deps failures.

**Comment by mitchellh** [comment]
@i0n Sorry I'm not sure aliases + defaults + modules is a combination well documented yet. It is being tracked in another issue I don't have off the top of my head right now (but somewhere like page 2 titled something like "alises don't behave well with modules").

**Comment by mitchellh** [comment]
So I'm sure that issue covers it, I'll close in favor of that one so we can use that to track doc updates and any impl changes.

**Comment by i0n** [comment]
Ok cool. Btw just want to say that terraform is awesome! Looking forward to having some time to help with the bugs ;-)
