### ISSUE TITLE
Cannot check existence of an azurerm_storage_share

### ISSUE THREAD

**Issue by TamasSzerb** [hashicorp/terraform#19445]
### Terraform Version

```
Terraform v0.11.10
+ provider.azurerm v1.16.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "moo-storage" {
  name                     = "moonortheurope"
  resource_group_name      = "moo"
  location                 = "${local.location}"
  account_tier             = "Standard"
  account_replication_type = "ZRS"
}

resource "azurerm_storage_share" "moo-share" {
  name                 = "share-moo"
  resource_group_name  = "moo"
  storage_account_name = "${azurerm_storage_account.moo-storage.name}"

  quota = 500
}

```

### Crash Output
2018/11/22 19:20:05 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error refreshing state: 1 error(s) occurred:

* azurerm_storage_share.moo-share: 1 error(s) occurred:

* azurerm_storage_share.moo-share: azurerm_storage_share.moo-share: Error testing existence of share "share-moo": Head https://moonortheurope.file.core.windows.net/moo?restype=share: Unknown Host

### Expected Behavior
Check if the service up & running

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by TamasSzerb** [comment]
Could anyone check this?

**Comment by tombuildsstuff** [comment]
Closing in favour of https://github.com/terraform-providers/terraform-provider-azurerm/issues/2384
