### ISSUE TITLE
unable to define list of maps in json format for variables 

### ISSUE THREAD

**Issue by vikram-chandrakanth** [hashicorp/terraform#19454]
### Terraform Version

```
...
```

### Terraform Configuration Files ## in HCL 

"variable" "monitors_http"{
        "type"="list" ,
         "default" =[
            {
                "destination"="*:*",
                "interval"="10",
                "name"="/Common/HTTP_MON",
                "parent"="/Common/http",
                "receive"="^HTTP\\/1\\.[10]\\s[23]0[0-9]",
                "send"="GET /login HTTP/1.1\r\nHost=default\r\nConnection=Close\r\n\r\n",
                "timeout"="31"
            },
            {
                "destination"="*:*",
                "interval"="7",
                "name"="/Common/HTTP_ALIVE_HTM_80",
                "parent"="/Common/http",
                "receive"="System is Alive",
                "send"="GET /alive.htm HTTP/1.0\r\nHost=\r\nConnection=close\r\n",
                "timeout"="16"
            }
        ]
    }
variable "monitors_tcp"{
        "type"="list" ,
         "default" =[
                    {
                "interval"="5",
                "name"="/Common/MON_TCP",
                "parent"="/Common/tcp",
                "timeout"="16"
                "destination" = "*:*"
            }
        ]
}

### Terraform Configuration Files ## in JSON

{
  "variable": {
      "monitors_http": {
          "type" : "list",
           "default": [
            {
              "destination": "*:*",
              "interval": "10",
              "name": "/Common/HTTP_MON",
              "parent": "/Common/http",
              "receive": "^HTTP\\/1\\.[10]\\s[23]0[0-9]",
              "send": "GET /login HTTP/1.1\r\nHost=default\r\nConnection=Close\r\n\r\n",
              "timeout": "31"
            },
            {
              "destination": "*:*",
              "interval": "7",
              "name": "/Common/HTTP_ALIVE_HTM_80",
              "parent": "/Common/http",
              "receive": "System is Alive",
              "send": "GET /alive.htm HTTP/1.0\r\nHost=\r\nConnection=close\r\n",
              "timeout": "16"
            }
          ]
        },
      "monitors_tcp": {
            "type" : "list",
          "default": [
            {
              "destination": "*:*",
              "interval": "5",
              "name": "/Common/MON_TCP",
              "parent": "/Common/tcp",
              "timeout": "16"
            }
          ]
      }
  }
}
 
### Crash Output

 Error loading vars.tf.json: 'monitors_http' has a default value which is not of type 'list' (got 'map')

**Comment by mildwonkey** [comment]
Hi @vikram-chandrakanth !

I'm sorry you've run across this known limitation of current terraform versions. 

Terraform version 0.12 ([available in alpha now](https://releases.hashicorp.com/terraform/0.12.0-alpha2/)) will introduce [complex data types](https://www.hashicorp.com/blog/terraform-0-12-rich-value-types) for variables, such as your example list of maps.

It would be great if you downloaded the alpha to test it out yourself (and open a new ticket with any issues you see in the alpha!), but please don't use it against any real production infrastructure 😄

**Comment by karthikeayan** [comment]
What it the work around for this?

**Comment by mildwonkey** [comment]
You'll need to provide the rest of your configuration so we can see how you are using the variable before anyone can suggest a workaround. If you post your configuration - [formatted](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code), please, so it's easier to read - I'll re-open this issue.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
