### ISSUE TITLE
Issue 1519 claims to be fixed but isn't - regarding application gateway missing attributes

### ISSUE THREAD

**Issue by thomasavg** [hashicorp/terraform#19466]
[Issue 1519](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1519) asks about missing attributes in application gateway, for example host_name in httpsettings. An update was made in [issue 1576](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1576) claiming to have solved this in [issue 2054](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2054). This is not true. I can see no way to set the host name for an application gateway's httpsettings using terraform.

Please can this issue be re-looked at? Thanks

**Comment by mildwonkey** [comment]
@thomasavg - both of the issues you've referenced are in the terraform-provider-azure repository, so I will label this issue so it gets moved to the proper repository. Thanks, and sorry that you're experiencing an issue.
