### ISSUE TITLE
terraform plan come out with usage instruction rather than planning the provisioning

### ISSUE THREAD

**Issue by nicknameyu** [hashicorp/terraform#19473]
Normally, when I run `terraform init`, `terraform plan`, `terraform apply` to provision resource on Azure. Today, I got a weird thing. 
The commands are running well on my windows laptop, but on linux, it output usage instructions rather than provision the resource. 
Can anyone tell me why?

```
azadmin@AZLAPSLOG1001:~/terraform/vmprovision/windows$ terraform -version
Terraform v0.11.10
+ provider.azurerm v1.19.0

azadmin@AZLAPSLOG1001:~/terraform/vmprovision/windows$ ls
bootstrap.ps1  main.tf  terraform.tfvars  variables.tf
azadmin@AZLAPSLOG1001:~/terraform/vmprovision/windows$ terraform plan
Usage: terraform plan [options] [DIR-OR-PLAN]

  Generates an execution plan for Terraform.

  This execution plan can be reviewed prior to running apply to get a
  sense for what Terraform will do. Optionally, the plan can be saved to
  a Terraform plan file, and apply can take this plan file to execute
  this plan exactly.

  If a saved plan is passed as an argument, this command will output
  the saved plan contents. It will not modify the given plan.

Options:

  -destroy            If set, a plan will be generated to destroy all resources
                      managed by the given configuration and state.
......
```

**Comment by apparentlymart** [comment]
Hi @nicknameyu! Sorry for this strange behavior.

My guess is that there is a syntax error in your `terraform.tfvars` file. We've seen reports of this causing the behavior you saw before, and this has been fixed in master ready for inclusion in the forthcoming v0.12.0 release.

**Comment by nicknameyu** [comment]
thanks, @apparentlymart , you are correct, I missed a quote in parameter file.
