### ISSUE TITLE
Change in policy description terraform is forcing to destroy and re-create the policy

### ISSUE THREAD

**Issue by zerolaser** [hashicorp/terraform#19476]
### Terraform Version
   
``` 
Terraform v0.11.10
provider.aws v1.48.0
```
### Terraform Configuration Files
default policy i took from terraform docs.
```
resource "aws_iam_policy" "policy" {
  name        = "test_policy"
  path        = "/"
  description = "My test policy "

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```
Now if i change the description its forcing me to re-create a new one instead of update it. I'm not sure if its default aws behavior or terraform's way of doing it. 

### Expected Behavior
```
Plan: 0 to add, 1 to change, 0 to destroy.

```
### Actual Behavior
```
Plan: 1 to add, 0 to change, 1 to destroy.
```
also the docs says 
> description - (Optional, Forces new resource) Description of the IAM policy.

that implies change in description results in re-creation ?  if that's case can this be added as a new feature enchancement ?

**Comment by mildwonkey** [comment]
Hi @zerolaser!

This is an AWS SDK limitation, unfortunately there's nothing we can do about it unless AWS changes something on their end.

According to [AWS's docs](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicy.html), the policy description cannot be changed:
> The policy description is immutable. After a value is assigned, it cannot be changed.

I'm sorry you've run across this, I have personal experience with this particular headache!

**Comment by zerolaser** [comment]
There was a typo in the description in one of our modules. now unfortunately we have to force re-create them again. thanks for the update.
