### ISSUE TITLE
0.12-alpha2: crash when referencing an undeclared module call

### ISSUE THREAD

**Issue by shikloshi** [hashicorp/terraform#19483]
### Terraform Version

```
Terraform v0.12.0-alpha2
+ provider.aws v1.40.0-6-gb23683732
+ provider.random v2.0.0-5-g612dff2
```

### Terraform Configuration Files
```hcl
provider random {}

variable length {
  type = number
  default = 10
}

variable prefix {
  type = string
  default = ""
}

resource random_pet new_pet {
  prefix = var.prefix
  length = var.length
}

output pet {
  value = module.new_pet
}
```

### Crash Output

https://gist.github.com/shikloshi/1735d67ae2e9e67f9a04c99ed6401745
### Expected Behavior

Terraform should be able to apply or return a syntax error if such had happened. 
### Actual Behavior

Terraform crashed.
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context
Configuration provided is the only file exists

This started happening when I added the `output` clause.

**Comment by apparentlymart** [comment]
Hi @shikloshi! Thanks for reporting this issue.

Indeed it looks like we're missing some validation to ensure that `module "new_pet"` is declared before resolving it. We'll make sure this is fixed before final release.
