### ISSUE TITLE
Terraform config v0.12 upgrade flag in resource/testing.go

### ISSUE THREAD

**Issue by ravitandonrt** [hashicorp/terraform#19484]
### Current Terraform Version

```
2018/11/27 09:43:09 [INFO] Terraform version: 0.12.0 alpha2
2018/11/27 09:43:09 [INFO] Go runtime version: go1.11.1
```

### Use-cases

As part of the v0.12 upgrade for Terraform, some of the existing Terraform configs require to be run through an upgrade tool to match the newer HCL v2 syntax and semantics.

This brings out a bigger challenge for existing provider tests that may have hard-coded Terraform configs or config generators that may remain incompatible.

As it maybe non-trivial for existing providers to update all of their test corpus, this feature request is for an additional flag in Terraform testing framework to optionally run the upgrade tool before each test step.

If this is already on the roadmap or an alternative solution that will remediate that instead of needing to update each existing test, please share the details.

### Attempted Solutions

Right now, to uncover any issues with v0.12 all Terraform configs have to be updated manually in tests to work-around syntax issues.

For instance, this line required to add newlines: https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/database_autonomous_data_warehouse_test.go#L59

Even if newlines will be handled by parser correctly, there could be more things that are not backwards compatible and forcing an upgrade on config, like TypeSets.

### Proposal

Introduce an additional flag in ~/go/src/github.com/hashicorp/terraform/helper/resource/testing.go like `upgradeConfigIfNeeded` with default to `true` that will update the block sent to the `Config` parameter.

### References

All the issues listed below have been marked to be addressed via the config upgrade tool, but continue to impact existing tests.

https://github.com/hashicorp/terraform/issues/19325
https://github.com/hashicorp/terraform/issues/19410
https://github.com/hashicorp/terraform/issues/19407

**Comment by ravitandonrt** [comment]
An alternative, albeit an ugly one would be to run an external process to `upgrade` the configs before passing it to the test framework, it would be much better instead to have a first party upgrade support or hear your thoughts on pros and cons for supporting default upgrades in testing.

**Comment by apparentlymart** [comment]
Hi @ravitandonrt,

An approach we are considering for this is to write a tool to search a provider codebase for constants that look like they are being used as Terraform configuration snippets for tests and automatically rewrite them. We don't know yet if such a thing is practical, but we will be working on that in the near future as we finalize the plan to prepare all of the existing Terraform providers for their first 0.12-compatible releases.

We'll share more here when we have it.

**Comment by apparentlymart** [comment]
I can see that the automatic-rewrite approach won't work for cases like the one you shared there where a fragment of configuration is being constructed in isolation. Although that particular example should work without updates by final release, any automatic update tool will necessarily be a "best effort" sort of thing and it is likely that _some_ manual updates will still be required, although the tool should be able to take care of more normal cases where a named constant string is referenced as part of the `Config` expression of a test step.

It looks like the OCI provider's approach is atypical in that significant parts of the test configurations are generated dynamically by helper functions. An automatic upgrade tool will of course not be able to help with that sort of situation, but at least if the configuration is _generated_ then the function that is generating it can be updated just once for updates everywhere else.

**Comment by ravitandonrt** [comment]
If no other provider has needed this feature in the test framework to attempt upgrade the existing test TF config at runtime, I do agree we will have to change our dynamic config generators to hcl2 syntax out of box.

We are exploring alternative testing strategy to continue testing our provider for backwards compatibility with previous Terraform versions.
