### ISSUE TITLE
Add "-var-file" + "-var" support to "terraform push"

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#1950]
To be fair I don't exactly know why am I required to specify all variables at the stage of pushing modules into Atlas, but in any way and more importantly if it's really required, I believe that `-var-file` + `-var` should be supported in `terraform push`, so I don't have to specify these.

**Comment by phinze** [comment]
I believe they _are_ supported, just not documented in the `-help` - did you try specifying them?

**Comment by mitchellh** [comment]
Updated the docs, @phinze is right!

**Comment by radeksimko** [comment]
> did you try specifying them?

I thought I did... but apparently I didn't. Thanks for updating the docs.
