### ISSUE TITLE
How to pass variables to a text file? 

### ISSUE THREAD

**Issue by vishnudxb** [hashicorp/terraform#1951]
For eg:- 
I had created a text file "userdata.txt" and the content inside looks like below.

ec2_key=${var.access_key}
ec2_secret=${var.secret_key}

Now I need to use this txt file as a user data in AWS.
user_data = "${file("userdata.txt")}"   ( This one don't work) 

How I need to get the values of the variables inside the txt file ?

**Comment by mitchellh** [comment]
Take a look at the `template_file` resource
