### ISSUE TITLE
cidrsubnet function can't handle output of a resource such as aws_vpc

### ISSUE THREAD

**Issue by mikemcowie** [hashicorp/terraform#19535]
**I just tried to recreate the issue exactly as before, and this time it worked as expected after running "terraform destroy" and "terraform  plan." So I'm not sure what to think now (and it's hard for me to give you proper output because it's suddenly working as expected. So this might be a PEBKAC.** 

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.50.0

...
```

### Terraform Configuration Files

```hcl
...
data "aws_availability_zones" "azs" {}

resource "aws_vpc" "main" {
        cidr_block = "${var.cidrrange}"
        assign_generated_ipv6_cidr_block = true
}

resource "aws_subnet" "public" {
        availability_zone = "${element(data.aws_availability_zones.azs.names, count.index)}"
        count = "${length(data.aws_availability_zones.azs.names)}"
        vpc_id = "${aws_vpc.main.id}"
        cidr_block = "${cidrsubnet(var.cidrrange, 4, count.index )}"
        ipv6_cidr_block = "${cidrsubnet(aws_vpc.main.ipv6_cidr_block, 8, count.index )}"
        map_public_ip_on_launch = "true"
}

```

### Expected Behavior

Terraform reads the output of the "aws_vpc.main.ipv6_cidr_block" and assigns subnets with ipv6 /64 ranges .
### Actual Behavior

Terraform reports an invalid CIDR range for ipv6 of "" .

This happens for ipv4 too, but it's easy to pass in an ipv4 range as a variable so a non-issue. However the ipv6 block is automatically allocated.

It's also able to be worked around by commenting out the ipv6 line in the subnet, running terraform apply, then uncommenting the ipv6 line, and running terraform apply.

I also just tried to recreate the issue exactly as before, and this time it worked as expected after running "terraform destroy" and "terraform  plan." So I'm not sure what to think now (and it's hard for me to give you proper output.

**Comment by apparentlymart** [comment]
Hi @mikemcowie!

It looks like you might've hit submit too soon here and left the template unpopulated. If you could edit the original comment to fill in the requested information then we'd be happy to look more into the issue you've found here.

**Comment by mikemcowie** [comment]
Looks like this was my bad, I had an existing VPC without ipv6, and I thought I had no existing VPC.
Please close
