### ISSUE TITLE
I am using 0.10.8 version of terraform. we created SSM maintenance window with this version a while ago. I tried running same code before 2 days but i got error, please find the error. I find provider.aws version has been upgraded.we used to use version 1.48 but now it was upgraded to 1.50. we tried degrading version to 1.48 and it worked. Please advise us on this issue. Is it a bug of new version???

### ISSUE THREAD

**Issue by thrinadh238** [hashicorp/terraform#19538]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by thrinadh238** [comment]
* module.ssm.aws_ssm_maintenance_window_task.task_install_patches: 1 error(s) occurred:

* aws_ssm_maintenance_window_task.task_install_patches: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTaskWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTaskWithMaintenanceWindowInput.Name.

**Comment by apparentlymart** [comment]
Hi @thrinadh238,

The AWS provider is not developed in this repository. Please instead open an issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws), and follow the instructions in the issue template to capture all of the information required to understand the problem.

Thanks!
