### ISSUE TITLE
aws_iam_instance_profile incorrectly accepts a list of roles

### ISSUE THREAD

**Issue by robzienert** [hashicorp/terraform#1954]
The aws_iam_instance_profile resource in Terraform allows you to provide a list of roles; but the AWS documentation explicitly says that this is not possible:

"Roles per instance profiles: 1 (each instance profile can contain only 1 role)"

http://docs.aws.amazon.com/IAM/latest/UserGuide/LimitationsOnEntities.html

**Comment by mitchellh** [comment]
This is done since the API seems to hint and is designed to allow multiple, although they only allow one right now. If you want to update our docs to clarify, I'd be happy to merge. Thanks!
