### ISSUE TITLE
data.external.heptio_authenticator_aws: failed to execute "bash"

### ISSUE THREAD

**Issue by dmarkey** [hashicorp/terraform#19554]
### Terraform Version

Terraform v0.11.7
+ provider.aws v1.50.0
+ provider.external v1.0.0
+ provider.http v1.0.1
+ provider.kubernetes v1.4.0

Your version of Terraform is out of date! The latest version
is 0.11.10. You can update by downloading from www.terraform.io/downloads.html
➜  terraform-eks git:(master) ✗ 

```
...
```

### Terraform Configuration Files

all from github.com:niallmccullagh/terraform-eks

```hcl
...
```

### Expected Behavior

terraform plan -var-file=vars.tfvars should work

### Actual Behavior

Doesnt work:
Error: Error refreshing state: 2 error(s) occurred:

* module.eks.data.aws_ami.eks-worker: 1 error(s) occurred:

* module.eks.data.aws_ami.eks-worker: data.aws_ami.eks-worker: Your query returned no results. Please change your search criteria and try again.
* module.eks.data.external.heptio_authenticator_aws: 1 error(s) occurred:

* module.eks.data.external.heptio_authenticator_aws: data.external.heptio_authenticator_aws: failed to execute "bash": bash: /home/dmarkey/src/terraform-eks/.terraform/modules/d038f68ac99abd45e9d2ea52b98707e8/Authenticator.sh: No such file or directory

**Comment by dmarkey** [comment]
Also tried 0.11.10

**Comment by jbardin** [comment]
Hi @dmarkey,

This doesn't look like a Terraform issue. Your module is referencing `Authenticator.sh`, but the file in the repo is named `authenticator.sh`.
