### ISSUE TITLE
Remote-exec appeared to hang even though it had not

### ISSUE THREAD

**Issue by arewm** [hashicorp/terraform#19557]
### Terraform Version

```
Terraform v0.11.7
```

### Expected Behavior
After provisioning VMs, I run an ansible playbook within a docker image. I would expect the Terraform to continue to report back all stdout printed on the remote machine until the job completes or fails.

### Actual Behavior
At some point in the installation process, I stop getting any stdout back from the playbook and my Travis job times out. While I did not get any of the output created, I did continue to receive the regular `Still creating...` messages every 10 seconds. When I ssh onto the VM with the running playbook, I can inspect the tailed logs to see that the job proceeded past the point where it seemed to "hang". The place where it did hang should not take a long time to execute.

### Additional Context
Terraform is being run in a Travis environment (workers hosted on GCP), targeting resources deployed to AWS.

I encounter this issue intermittently, but I cannot investigate further when it happens as it is running within a Travis worker. Additionally, adding more verbose logging is not easy as this will cause the Travis job to fail due to the log being too long.

**Comment by mildwonkey** [comment]
Hi arewm, 

Can you share more details of your configuration, the machine that is running terraform, and the full output from `terraform apply`?  Hopefully that will give us enough information without requiring verbose logging.

**Comment by arewm** [comment]
All of the details that I have are in the attached Travis log. This is only the most recent occurrence of this issue.

[terraform_log.txt](https://github.com/hashicorp/terraform/files/2845775/terraform_log.txt)

**Comment by arewm** [comment]
I have figured out a way to get the debug logs from Terraform off of the Travis worker, so I can provide some more details if needed.

**Comment by arewm** [comment]
I just tried a deploy using Terraform v0.11.11, but there was no observed difference in the behavior.

**Comment by arewm** [comment]
Is it possible that the Terraform process on the remote machine times out? I just had a successful install, but the step that is timing out took ~13 minutes (so Terraform would have not have received any output for that long). I am not sure how long this step takes on the "failed" installations.

**Comment by arewm** [comment]
I started keeping track of the time it takes the job to run (and therefore the time between receiving output). My prior theory has proven to be incorrect at worst, or incomplete at best. Terraform stopped sending output for a job that took less time than one that did send output.

To additionally test this theory, I made a simple Terraform deployment that just sleeps between output: https://github.com/arewm/terraform-pause-test. A local test of this (up to 25 minutes) succeeded. I have set a cron job to run on Travis to see if 1) it is specific to Travis and 2) if it is a periodic occurrence. 

Continuing to investigate, but feel free to offer suggestions. 😄

**Comment by danieldreier** [comment]
@arewm have you run your terraform-pause-test against 0.13 or the 0.14 alphas? I'm unclear on whether this is still a valid issue.

**Comment by arewm** [comment]
@danieldreier, I have not tested this out recently. I have since changed companies and am therefore no longer running into these issues... I was never able to duplicate the issue with the `terraform-pause-test`. I assume that it might have had something to do with the Enterprise version of Travis CI that I was using... 😄 

Since _I_ cannot reproduce this, feel free to close for now.

**Comment by danieldreier** [comment]
Thanks @arewm! I hope you're still using Terraform at the new shop! I'm going to close this out, but please let me know if you run into this or any other issues in the future. I really appreciate your issue report here.
