### ISSUE TITLE
Cloudformation with count not returning template outputs

### ISSUE THREAD

**Issue by skinofstars** [hashicorp/terraform#19558]
### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.21.0
```

### Terraform Configuration Files

```hcl
resource "aws_cloudformation_stack" "example" {
  count = "2"

  name = "example-${count.index}"

  template = <<STACK
  {
    "Resources" : {
      "MyVPC": {
        "Type" : "AWS::EC2::VPC",
        "Properties" : {
          "CidrBlock" : "10.0.0.0/16",
          "Tags" : [
            {"Key": "Name", "Value": "Primary_CF_VPC"}
          ]
        }
      }
    },
    "Outputs" : {
      "VpcID" : {
        "Description": "The VPC ID",
        "Value" : { "Ref" : "MyVPC" }
      }
    }
  }
  STACK
}

output "VpcID" {
  value = "${aws_cloudformation_stack.example.*.outputs["VpcID"]}"
}
```

### Crash Output

```
* module.example.output.DefaultDNSTarget: __builtin_StringToInt: strconv.ParseInt: parsing "VpcID": invalid syntax in:

${aws_cloudformation_stack.example.*.outputs["VpcID"]}
```

**Comment by skinofstars** [comment]
Hi @apparentlymart, thanks for getting back.

The understand the reason. Unfortunately your proposed solution, to use attribute syntax, doesn't work for `aws_cloudformation_stack` (perhaps a different bug?). It results in the following

```
Error: Error running plan: 1 error(s) occurred:

* module.example.output.VpcID: Resource 'aws_cloudformation_stack.example' does not have attribute 'outputs.VpcID' for variable 'aws_cloudformation_stack.example.*.outputs.VpcID'
```

**Comment by twllight** [comment]
I'm seeing the same issue as above when using count for a cloud formation template. Is it not possible to use count?

**Comment by mildwonkey** [comment]
I'm glad to hear you found a (working) workaround! I'm going to close this issue, but please feel free to open another issue if needed.

**Comment by AleksandarTokarev** [comment]
@skinofstars i am a little bit confused on how to use your solution.
How can i use this with count in the same module ? 
I want to reference output ARN from cloudformation and set it as replication task target endpoint.

**Comment by skinofstars** [comment]
@AleksandarTokarev I believe they key aspect of this is to use `coalescelist`. As I said, this solution was provided by by someone else, so I'm not the expert on this.

Maybe you need something like the following... This assumes an `outputs` map an `ARN` list, so you can see some different ways of interacting with results.

```hcl
resource "aws_cloudformation_stack" "my_stack" {
  name  = "my_stack"
  template_body = "${file("${path.module}/my_stack.json")}"
}

locals {
  policy_arn_list = "${coalescelist(aws_iam_policy.my_stack.*.arn, list("", ""))}"
  outputs_list    = "${coalescelist(aws_cloudformation_stack.my_stack.*.outputs, list(map("VPCID", "")))}"
  map             = "${local.outputs_list[0]}"
  vpc_id          = "${lookup(local.map, "VPCID", "")}"
}

resource "aws_iam_user_policy_attachment" "my_iam_user_policy" {
  user       = "${var.iam_user_name}"
  policy_arn = "${local.policy_arn_list[0]}"
}

resource "aws_security_group" "subnet" {
  vpc_id = "${local.vpc_id}"
}

```

**Comment by AleksandarTokarev** [comment]
Hmm my problem is the same as the poster's, where i have a count with cloudformation, and i am getting multiple cloudformation templates each one with 1 output, so my question is whether it is possible to achieve this with the thing u had posted?

**Comment by antoniotamer** [comment]
@AleksandarTokarev Note that the above example is doing:   
`map             = "${local.outputs_list[0]}"`

What you can do is run the `lookup` inside your resource, though it's a little harder to read: 

`
resource aws_network_interface_sg_attachment payg_f5 {
  count             = "${aws_cloudformation_stack.payg_f5.count}"
  security_group_id = "${aws_security_group.f5.id}"

  network_interface_id = "${lookup(local.payg_outputs_list[count.index], "Bigip1subnet1Az1Interface", "")}"
}
`
