### ISSUE TITLE
Include AWS STS Endpoint Support for S3 Backend

### ISSUE THREAD

**Issue by mrtreverj** [hashicorp/terraform#19564]
Currently, STS and other service endpoints are supported for the AWS Provider, which allows users to avoid traffic to AWS services from traversing the internet.  This information may be found at the following link: https://www.terraform.io/docs/providers/aws/#sts . 

Unfortunately, the S3 Backend only supports the usage of the S3 endpoint, which would logically be sufficient for most usages.  Additionally, though, if the usage of the S3 endpoint requires the assumption of an IAM role or usage of STS, it would be greatly beneficial to ensure that this traffic utilizes the STS endpoint similar to how traffic for the standard terraform calls would.

**Comment by bflad** [comment]
Support for configuring the DynamoDB, IAM, and STS endpoints with the S3 backend has been merged via #19571 and will release with the next version of Terraform, either 0.12-alpha5 or 0.12-beta1. 👍
