### ISSUE TITLE
Output screwed with interactive dialog in console

### ISSUE THREAD

**Issue by yujunz** [hashicorp/terraform#19583]
### Terraform Version

```
Terraform v0.11.10
```

### Terraform Configuration Files

```hcl
provider "sops" {}

data "sops_file" "avindex_secret" {
  source_file = "../sops/secret.enc.json"
}
```

### Debug Output

See https://github.com/carlpett/terraform-sops/issues/4

### Expected Behavior

Pause on the interactive dialog and wait for user input to continue

### Actual Behavior

Terraform output screwed with the dialog box.

### Steps to Reproduce

1. Install the terraform sops plugin as in [README](https://github.com/carlpett/terraform-sops#install).
2. create an encrypted secret with passphrase protected PGP key.
3. `terraform init`
3. `terraform apply`

**Comment by jbardin** [comment]
Hi @yujunz,

Sorry you're having an issue with this, but it doesn't look like terraform is doing anything unexpected here. Plugins don't have control over the user UI -- they are run as a subprocess and should only respond to the defined RPC interface, and output formatted logging on stderr. 

It looks like the `go.mozilla.org/sops/decrypt` package that the provider is using expects to be able to prompt the user for input, which isn't something that providers are intended to do. All input to a provider should come through its configuration

**Comment by carlpett** [comment]
Hi @jbardin,
Understood, I'll see what I can do my end to ensure the plugin errors out if the required parameters are not set. But I was somewhat surprised that this was an "honor agreement", and that the plugin could even write to stdout like that. Is it something that could/should be suppressed?

**Comment by jbardin** [comment]
@carlpett, `go-plugin` should be preventing that already. I'm guessing whatever `sop/decrypt` is calling ends up grabbing the console device directly, rather than simply writing to stdout.

**Comment by carlpett** [comment]
That is good to hear, thanks. My suspicion is that it might actually be a gpg-agent that comes alive and does it, so completely outside Terraform and any plugins themselves.
