### ISSUE TITLE
Unexpected EOF crash

### ISSUE THREAD

**Issue by jms90h5** [hashicorp/terraform#19585]
### Terraform Version

```
Terraform v0.11.6
+ provider.ibm v0.13.0
+ provider.null v1.0.0
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

https://gist.github.com/jms90h5/71e778e3d472eae19c9e86378d2d4d39

### Steps to Reproduce

terraform init
terraform plan

**Comment by jbardin** [comment]
Hi @jms90h5,

Thanks for filing the issue. This error is coming from a provider called `terraform-provider-ibm`. This provider isn't one we can automatically transfer issues to, but it looks like their github repo is here if you'd like to file an issue: https://github.com/IBM-Cloud/terraform-provider-ibm

**Comment by jms90h5** [comment]
Hi James,

Thanks for the quick followup.  I did realize that after posting the report
and head in that direction instead.
--
Jim Sharpe
(970) 209-3810   www.sharpe.com
