### ISSUE TITLE
Can't compare to string containing a curly brace (parse error)

### ISSUE THREAD

**Issue by alewando** [hashicorp/terraform#19598]
### Terraform Version

```Terraform v0.11.10
```

### Terraform Configuration Files

```hcl
resource "null_resource" "test" {
  count = "${"foo" == "{" ? 1 : 0}"
}
```

### Debug Output

https://gist.github.com/alewando/e88ab53ddf5c6adaba0e8c8f5baf6bee

### Expected Behavior

The string compare would fail, and count would be set to 0 for this resource.

### Actual Behavior

```Error: Error parsing /tf/main.tf: At 4:2: literal not terminated```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

1. Various escaping mechanisms (`{{`, `\{`, `\\{`) have been tried without success. 
2. Including a closing curly brace in the literal does parse, but is not a viable workaround.
3. Putting the problematic literal on the other side of the comparison does not make a difference.
4. This error occurs if an unmatched curly brace appears anywhere in the literal, not just as the lone character.

### References

I was unable to find any existing issues that reference this specific problem. Plenty of material referencing the escaping of dollar signs, but nothing I could find in regards to a lone curly brace.

**Comment by jbardin** [comment]
Hi @alewando,

Thanks for filing the issue. I verified that the new parse in the next version already handles this correctly.

**Comment by alewando** [comment]
By 'next version', you mean 0.12? The version that the website says "will not be released until later this summer"? Do you know of any workaround that could make this parsable until then?

**Comment by jbardin** [comment]
@alewando,

Sorry, 0.12 should be out before the summer (the website is in the process of being updated). 

You should be able to just remove the brace literal string from the conditional expression, which is where it's being parsed incorrectly. For example:

```
locals {
  lbrace = "{"
  num = "${"foo" == local.lbrace ? 1 : 0}"
}

resource "null_resource" "test" {
  count = "${local.num}"
}
```
