### ISSUE TITLE
cross-terraform project variable/resource references

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/terraform#1961]
We have a two-step infrastructure setup.

First we setup the whole infrastructure, next we provide values to our Consul cluster for this infrastructure to use.

This second step requires an active VPN connection to the infrastructure VPC (which is set-up, and automatically started in the first step).

The current solution we are working on is having a `null_resource` resource with a `local-exec` provisioner which sleeps until it can ping the private IP of one of the machines (requiring the user to start the VPN client during this time).

This works (I assume, still implementing), but it feels like a hack.

Instead, I'd like to split up the whole setup in two steps, allowing you to run the "configuration" step independent of the infrastructure-setup step.

For this to work, I'd like to do things like `${aws_instance.manager.0.private_ip}` in the second step, even though these resources where provisioned in the first step.

Is there a way (other than capturing `outputs` into temporary files) to handle this use-case?

**Comment by knuckolls** [comment]
If I understand what you're asking correctly you can collect the outputs of your first module and inject them as inputs to your second module.

**Comment by mitchellh** [comment]
See "delegation and teamwork" here: https://terraform.io/docs/state/remote.html
