### ISSUE TITLE
Editing a resource which is created through a module

### ISSUE THREAD

**Issue by gauravrautela** [hashicorp/terraform#19621]
I have lots of common modules that I use in my infrastructure. I have been running into a problem lately which I am going to **simplify** and explain.

_one code snippet_

> module "ec2-instance" {
>   source  = "../common-modules/ec2-instance/"
>   aws_instance="monitoring"
>   region="ap-south-1"
>   subnets=["subnet-1234as"]
>   ami_id="ami-34a4c05b"
>   instance_type="t2.medium"
>   instance_count=1
>   security_group= "sg-c36ab3"
> }
> 

I am using the module (**../common-modules/ec2-instance/**) used in the snippet, in ten different places.

Now, In one of the ten usages (ec2 instances), I want to add a tag but not others, i.e _I do not want to edit my module source code_ as it will mess up other 9 places where I have called the module.

Could you please help me how can I achieve this?

**Comment by apparentlymart** [comment]
Hi @gauravrautela,

Unfortunately what you are describing here is not possible. The module's configuration is the authority for what settings are present on the EC2 instances within it.

The only way to get there is to edit the module to add a new _optional_ variable to accept the tags:

```
variable "tags" {
  type    = "map"
  default = {}
}
```

Adding this will not affect any of the existing calls. You can then use this map to set the tags on the resource(s) in the module, and update the one call that needs tags to set a non-empty value for that variable.
