### ISSUE TITLE
Terraform apply failed due to mismatch time

### ISSUE THREAD

**Issue by joonhwa** [hashicorp/terraform#19622]
### Terraform Version
```
hashicorp/terraform:0.11.10
```

### Terraform Configuration Files

```
module.ecs_singapore.network.aws_nat_gateway.main: Still creating... (20s elapsed)
module.ecs_singapore.aws_alb.main: Still creating... (20s elapsed)
module.ecs_singapore.network.aws_nat_gateway.main: Still creating... (8h0m7s elapsed) <<<============= Time went wrong here
module.ecs_singapore.aws_alb.main: Still creating... (8h0m8s elapsed) 
Failed to save state: failed to upload state: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
	status code: 403, request id: 0B0026E03C66248C, host id: n4DuSL4lWCUY0uXCLecwNtOyszV/Pr6ucFMZYxr4TjMuPWNHz2UYtuziy5dysFpJncWdwss1XTo=


Error releasing the state lock!

Error message: failed to retrieve lock info: InvalidSignatureException: Signature not yet current: 20181206T223022Z is still later than 20181206T144544Z (20181206T143044Z + 15 min.)
	status code: 400, request id: G5CBO6G31177HOF9IB22HKEQDBVV4KQNSO5AEMVJF66Q9ASUAAJG

Terraform acquires a lock when accessing your state to prevent others
running Terraform to potentially modify the state at the same time. An
error occurred while releasing this lock. This could mean that the lock
did or did not release properly. If the lock didn't release properly,
Terraform may not be able to run future commands since it'll appear as if
the lock is held.
```

### Expected Behavior
Continue to wait for resource to be created then move on to other resource

### Actual Behavior
Operation failed with an error message stating mismatch time.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
2. `terraform apply`

### Additional Context
I am running this with terraform's docker image from my CI pipeline using gitlab-ci. I kind of suspect some kind of time drift somewhere? I have tried setting timezone and installing NTP and synching the timezone. I verified that the time and TZ has changed from the default UTC to my local timezone GMT+8. However, the error still occurs. 

I am kind of confused if this is a terraform issue or docker issue or both?
Any help will be greatly appreciated.

**Comment by joonhwa** [comment]
Thanks alot for the detailed explanation @apparentlymart 

The root cause for me is an incorrect time setting in my ESXi host. That wrong time is being synched to all the VM running in it, which resulted in this issue. Everything work fine once i set it back to the right UTC time.

**Comment by apparentlymart** [comment]
Thanks for following up, @joonhwa! I'm glad you found the answer. Since this wasn't a Terraform issue, I'm going to close this out.
