### ISSUE TITLE
0.12alpha-4  code upgrade fails on HEREDOC

### ISSUE THREAD

**Issue by jverhoeks** [hashicorp/terraform#19638]
### Terraform Version
```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
+ provider.aws v1.40.0-6-gb23683732-dev
```

### Terraform Configuration Files
```hcl
// additional policy for the task to access dynamodb
resource "aws_iam_role_policy" "ecs_task_allow_dynamodb_demo" {
  name = "ecs-allow-dynamodb-demo"
  role = "${module.ecs_task.task_iam_role_id}"

  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ListAndDescribe",
            "Effect": "Allow",
            "Action": [
                "dynamodb:List*",
                "dynamodb:DescribeReservedCapacity*",
                "dynamodb:DescribeLimits",
                "dynamodb:DescribeTimeToLive"
            ],
            "Resource": "*"
        },
        {
            "Sid": "SpecificTable",
            "Effect": "Allow",
            "Action": [
                "dynamodb:BatchGet*",
                "dynamodb:DescribeStream",
                "dynamodb:DescribeTable",
                "dynamodb:Get*",
                "dynamodb:Query",
                "dynamodb:Scan",
                "dynamodb:BatchWrite*",
                "dynamodb:CreateTable",
                "dynamodb:Delete*",
                "dynamodb:Update*",
                "dynamodb:PutItem"
            ],
            "Resource": "${aws_dynamodb_table.basic-dynamodb-table.arn}"
        }
    ]
}
EOF
}
```

### Debug Output
no output

### Crash Output
https://gist.github.com/jverhoeks/524a3222af0f8b0f08581c400817a9b1

This command will rewrite the configuration files in the given directory so
that they use the new syntax features from Terraform v0.12, and will identify
any constructs that may need to be adjusted for correct operation with
Terraform v0.12.

We recommend using this command in a clean version control work tree, so that
you can easily see the proposed changes as a diff against the latest commit.
If you have uncommited changes already present, we recommend aborting this
command and dealing with them before running this command again.

Would you like to upgrade the module in the current directory?
  Only 'yes' will be accepted to confirm.

  Enter a value: yes

-----------------------------------------------------------------------------
panic: HEREDOC not supported yet

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Expected Behavior
Upgrade code to version 0.12

### Actual Behavior
crash on heredoc while running migration

### Steps to Reproduce
any tf with a heredoc code will crash with `terraform 0.12upgrade`

**Comment by mildwonkey** [comment]
Hi @jverhoeks,
Thanks for reporting this! As the error states, the upgrade tool doesn't support HEREDOC yet, so we'll keep this issue open as a reminder.

**Comment by jverhoeks** [comment]
Thanks, what is the branch used to build 0.12alpha4? Would it be possible to compile myself?

**Comment by mildwonkey** [comment]
Yes, absolutely! We are working from the master branch.
