### ISSUE TITLE
Null resources rebuild based on misleadingly empty variables

### ISSUE THREAD

**Issue by larsxschneider** [hashicorp/terraform#19639]
Although nothing seems to have changed, Terraform detects changes in the triggers of *some* of my null resources and wants to rerun them. Terraform tells me that the variables used in the trigger have all been set to `""` (e.g. `"old1" => "" (forces new resource)`). However, if I actually apply the plan, then Terraform does not run the null resource with empty variables.

### Terraform Version

```
Terraform v0.11.10

provider "google" {
  version = "~> 1.19.1"
}

provider "null" {
  version = "~> 1.0"
}
```

### Terraform Configuration Files

```hcl
-/+ null_resource.someresource (new resource required)
      id:                    "69684775775254821" => <computed> (forces new resource)
      triggers.%:            "3" => <computed> (forces new resource)
      triggers.somevar1:     "old1" => "" (forces new resource)
      triggers.somevar2:     "old2" => "" (forces new resource)
      triggers.somevar3:     "old3" => "" (forces new resource)
```

### Debug Output

There is lots of log output but these *seem* to be the only relevant lines:

```
...
2018/12/13 13:22:29 [DEBUG] Attaching resource state to "null_resource.someresource": &terraform.ResourceState{Type:"null_resource", Dependencies:[]string{"google_compute_instance.aaa", "google_compute_instance.bbb", "google_compute_instance.ccc"}, Primary:(*terraform.InstanceState)(0xc00022c1e0), Deposed:[]*terraform.InstanceState{}, Provider:"provider.null", mu:sync.Mutex{state:0, sema:0x0}}
...
2018/12/13 13:22:30 [DEBUG] ReferenceTransformer: "null_resource.someresource" references: [google_compute_instance.aaa google_compute_instance.bbb var.bastion_key var.ccc var.ddd var.eee var.fff var.ggg]
...
```

**Comment by mildwonkey** [comment]
Hi @larsxschneider !
I'm sorry you've run across this behavior. I'd like to try and reproduce it locally. Can you add some examples of your terraform configuration files (with any sensitive data removed) so we can get a better idea of what's going on? Specifically it would help to see the `null_resource.someresource` and any resources referenced by, or referencing, the `null_resource`.

**Comment by larsxschneider** [comment]
Thanks for your quick reply @mildwonkey. I think I found the reason. This is how my `null_resource` (simplified) looks like:

```
resource "null_resource" "someresource" {
  
  triggers {
    somevar1 = "${var.somevar1}"
  }

  provisioner "local-exec" {
    command = <<EOF
      somevar1='${var.somevar1}'

      # more bash code stuff 
EOF
```

I also realized that the change that Terraform wants to do is **correct**. It's just confusing that Terraform does not show the correct new values in the plan output. In the plan output all triggers are set to `""`. Consequently **unchanged** values are shown as changed ...
```
"foo" => "" (forces new resource)
```
... and actually changed values are shown as changed but with a wrong new value ...
```
"bar" => "" (forces new resource)
```
...instead of the correct value ...
```
"bar" => <computed> (forces new resource)
```
Does this make sense to you?

**Comment by mildwonkey** [comment]
I think that makes sense - I'm not as familiar with the inner workings yet, but I believe it has to do with terraform not calculating changed values (even "obvious" ones, like your example) until apply.

You might be interested in some of the work being done on the rendering of terraform plans for 0.12 (slated for release sometime in the first quarter of next year). Here's your example after I've changed `somevar1` from `foo` to `bar` (please note that the exact format is subject to change):

```  # null_resource.someresource must be replaced
-/+ resource "null_resource" "someresource" {
      ~ id       = "1152940829336268751" -> (known after apply)
      ~ triggers = { # forces replacement
          ~ "somevar1" = "foo" -> "bar"
        }
    }```

So! I don't know that I have a satisfying suggestion for your current situation, but I'm glad that you figured out that terraform is behaving correctly, but unhelpfully. I can tell you that it should be much clearer with the next version of terraform.

**Comment by larsxschneider** [comment]
Awesome. Thanks for the feedback. I'll close that issue and wait for the new version then 👍
