### ISSUE TITLE
Cryptic Error Message: "* Couldn't find record: Record not found". 

### ISSUE THREAD

**Issue by 8interactive** [hashicorp/terraform#1963]
The set of commands is below. I came back to a deployed cluster and attempted to refresh. It would not work. My guess is that the error is related to the "cloudflare_record". I went to cloud flare and noticed that someone had deleted the DNS entry in question. I recreated it manually and re-ran the below steps. Same problem. I removed the cloudflare entry from the state file. Same problem. I then removed the cloudflare declaration from the terraform file, and I was able to recreate.

Aside - I assume this is not expected behaviour?

Regardless, I think the error is fundamentally cryptic. It should at the very least indicate what resource is broken, and (ideally) how to recover?

```
$ terraform taint cloudflare_record.dns
The resource cloudflare_record.dns in the module root has been marked as tainted!
$ terraform refresh -var 'production_password'=`cat /Volumes/TAUFOO/keys/form_app_prod.key`
cloudflare_record.dns: Refreshing state... (ID: 268382935)
aws_instance.app: Refreshing state... (ID: i-f3406317)
aws_elb.elb: Refreshing state... (ID: aire01-demo)
Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* Couldn't find record: Record not found
```

**Comment by catsby** [comment]
Hello @8interactive – sorry for the trouble there. Do you have a specific set of steps with an example configuration file that demonstrates this, that you could omit secrets from and share with me? That will help me track down any bugs. 

In the mean time, I've submitted pull request #2006 to increase the verbosity here in the error messages, I suspect it will be merged into master soon.

**Comment by mitchellh** [comment]
Closing due to lack of response
