### ISSUE TITLE
Make sure resources that use a resource are deleted first

### ISSUE THREAD

**Issue by 20k-ultra** [hashicorp/terraform#19630]
### Current Terraform Version

```
Terraform v0.11.10
```

### Use-cases

When deleting resources that other resources are currently using Terraform will hang while waiting for the resource to delete. After a certain time out period that I believe is hardcoded Terraform will then output the error saying resource 1 is using resource 2.

I would like to specify in resource 2 that when attempting to delete, Terraform must first delete a list of resources. 

### Proposal

Much like depends_on which from the docs states `These dependencies will be created before this resource.` I'd purpose a meta-parameter such as **used_by** or **destroy_first** which would destroy resources before destroying this resource.

My exact situation:

```
resource "aws_alb_target_group" "alb_target_group" {
  name     = "${var.environment}-alb-target-group-${random_id.target_group_sufix.hex}"
  port     = 443
  protocol = "HTTPS"
  vpc_id   = "${var.vpc_id}"
  target_type = "ip"

  health_check {
    path = "/"
    port = "80"
    protocol = "HTTP"
    healthy_threshold = 2
    unhealthy_threshold = 2
    interval = 5
    timeout = 4
    matcher = "200-308"
  }

}

resource "aws_alb_listener" "qriket" {
  load_balancer_arn = "${aws_alb.alb_qriket.arn}"
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "${var.ssl_policy}"
  certificate_arn   = "${var.certificate_arn}"
  depends_on        = ["aws_alb_target_group.alb_target_group"]

  default_action {
    target_group_arn = "${aws_alb_target_group.alb_target_group.arn}"
    type             = "forward"
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

I'm unable to destroy the target group because it's used by my listener so I go to console and remove it then can successfully run terraform apply.

**Comment by cflee** [comment]
I just ran into this with the latest Terraform core/AWS provider releases:

```
Terraform v0.12.18
+ provider.aws v2.43.0
```

In my case, I was trying to change an aws_alb_listener's certificate_arn and default_action.target_group_arn to some other existing certificate and target group, and remove the current certificate and target group. Terraform tried to do the two destroys before the update, so they failed since the certificate/target group are in use.

**Comment by grezar** [comment]
This is what I need.

**Comment by jbardin** [comment]
Hello all,

Sorry this slipped through the crash. Current release of terraform will correctly track destroy dependencies, as well as order them according to the original `create_before_destroy` value.

Thanks!
