### ISSUE TITLE
apply crashes on azure storage account

### ISSUE THREAD

**Issue by bytejunkie** [hashicorp/terraform#19643]
### Terraform Version

```
Terraform v0.12.0-alpha1
```

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "NexusStorage" {
  name                     = "${lower(var.CompanyName)}${lower(var.ProductName)}${lower(var.EnvironmentName)}${lower(var.EnvironmentInstance)}str"
  resource_group_name      = "${azurerm_resource_group.PlatformRG.name}"
  location                 = "west europe"
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "${lower(var.EnvironmentName)})"
  }
}
```

### Crash Output

https://gist.github.com/bytejunkie/adadf1a00b891c0f3713b2b6f76fd4af

### Expected Behavior

It should have created a storage account
### Actual Behavior

it crashed without creating anything.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Alpha installed by chocolatey on a windows 10 box.
tf file edited in vs code, crash happens in vs code terminal and in plain cmd terminal

**Comment by jbardin** [comment]
Hi @bytejunkie,

Please try this with the latest alpha release. There have been extensive changes to the provider sdk since alpha1.

**Comment by bytejunkie** [comment]
@jbardin thanks for replying. not actually sure where to get a newer version from, cant see it on the release page.

**Comment by jbardin** [comment]
@bytejunkie: the alphas are uploaded to the usual release location: https://releases.hashicorp.com/terraform/0.12.0-alpha4/

(I wouldn't expect any package managers to mirror these alpha releases; they contain only a few bundled providers, and they should not be used for anything but testing)

**Comment by bytejunkie** [comment]
understood, thanks for the link. 
im only testing. was inspired to play by a chat Nicolas did at leeds devops.
