### ISSUE TITLE
remote backend unauthorized with proper token

### ISSUE THREAD

**Issue by mark-bixler** [hashicorp/terraform#19657]
### Terraform Version

```
tf cli 0.11.10 / ptfe 0.11.10
```

### Terraform Configuration Files

```
terraform {
  required_version = "= 0.11.7"
  backend "remote" {
    hostname = "ptfe.xxxxx.xxxxx.io:443"
    organization = "myorg"
    token = "V3xxxxxxxxxxxxxxxxxgh"
    workspaces {
      name = "myworkspace"
    }
  }
}

```

### Debug Output

'''
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.

Error loading state:
    Error retrieving workspaces: unauthorized

Terraform failed to load the default state from the "remote" backend.
State migration cannot occur unless the state can be loaded. Backend
modification and state migration has been aborted. The state in both the
source and the destination remain unmodified. Please resolve the
above error and try again.
'''
### Expected Behavior

Terraform should have run init
### Actual Behavior

Above error saying unauthorized. Used proper USER token

**Comment by jbardin** [comment]
Hi @mark-bixler,

Sorry, this ins't a particularly clear error. Terraform is attempting to compare the state from the previous backend config, and perform a migration if necessary. It looks like the previous backend config is no longer valid, which results in the "unauthorized" error.

If you want to configure the backend and ignore the previous config, there is a `-reconfigure` flag to init for this purpose.

**Comment by mark-bixler** [comment]
running the -reconfigure flag is exactly what I needed. I'll close this as a non-bug. Thank you!
