### ISSUE TITLE
aws_cloudwatch_metric_alarm gives illegal char error for dimension Cache­Cluster­Id

### ISSUE THREAD

**Issue by humayunjamal** [hashicorp/terraform#19680]
### Terraform Version

```
0.11.11
```

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_metric_alarm" "redis_evictions" {
  alarm_name          = "Redis-ponka-high-evictions-tmp"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 3
  metric_name         = "Evictions"
  namespace           = "AWS/ElastiCache"
  period              = "60"
  statistic           = "Sum"
  threshold           = "20"
  alarm_description   = "This metric monitors Redis Evictions numbers"
  
  dimensions {
    Cache­Cluster­Id = "ponka-cluster"
  }
}
```

### Crash Output

Error: Error parsing main.tf At 37:10: illegal char for this line --> Cache­Cluster­Id = "ponka-cluster"
### Expected Behavior
should have accepted the dimension and created an alarm to monitor elasticcache evictions metric

### Actual Behavior
does not accept this dimension --> Cache­Cluster­Id 
### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
I have searched every where and I cant seem to find valid examples or shared code to create cloudwatch alarm to monitor a cluster evictions or any metric with dimensions mentioned above

**Comment by kenorb** [comment]
If you copied the example from [cloudwatch_metric_alarm](https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html) docs page there are some hidden special characters there. In VSCode you can turn on the special character visibility, or use Atom. It can help you find the problem.
