### ISSUE TITLE
`terraform state rm foo.bar` also removes `module.baz.foo.bar`

### ISSUE THREAD

**Issue by tomasaschan** [hashicorp/terraform#19692]
### Terraform Version
v0.11.9 (latest available on https://chocolatey.org/)

### Terraform Configuration Files
`project-root/foo.tf`
```hcl
provider "random" {}

resource "random_string" "foo" {
  length = 20
}

module "bar" {
  source = "./bar"
}
```
`project-root/bar/foo.tf`
```hcl
resource "random_string" "foo" {
  length = 20
}
```

### Debug Output
Debug output can be found [here](https://gist.github.com/tomasaschan/88a5f8906066635c6e02751d80df988d).

### Expected Behavior
I expect `terraform state rm random_string.foo` to remove the resource in the root scope, but _not_ the same-named resource in the module scope.

### Actual Behavior
`terraform state rm random_string.foo` actually removes _both_ items from the state.

### Steps to Reproduce
Setup:
1. `terraform init`
2. `terraform apply -auto-approve`

Verify preconditions:
1. `terraform state list` shows two items, `random_string.foo` and `module.bar.random_string.foo`

Execute:
1. `terraform state rm random_string.foo`

Verify incorrect behavior:
1. `terraform state list` should show one item, `module.bar.random_string.foo`, but in fact it shows nothing.
1. `terraform plan` suggests creating both resources.

**Comment by ddfreyne** [comment]
This also happens with other Terraform commands:

```
% terraform state list aws_db_instance.main
aws_db_instance.main
module.foo.aws_db_instance.main
module.bar.aws_db_instance.main
```
