### ISSUE TITLE
Terraform running on windows creates slugs incompatible with TFE

### ISSUE THREAD

**Issue by koikonom** [hashicorp/terraform#19697]
### Terraform Version
```
Terraform v0.11.11
```

### Debug Output
```❯ TF_LOG=trace terraform init
2018/12/19 13:16:31 [INFO] Terraform version: 0.11.11
2018/12/19 13:16:31 [INFO] Go runtime version: go1.11.4
2018/12/19 13:16:31 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.11/bin/terraform", "init"}
2018/12/19 13:16:31 [DEBUG] Attempting to open CLI config file: /Users/kyriakos/.terraformrc
2018/12/19 13:16:31 Loading CLI configuration from /Users/kyriakos/.terraformrc
2018/12/19 13:16:31 [INFO] CLI command args: []string{"init"}
2018/12/19 13:16:31 [DEBUG] command: loading backend config file: /Users/kyriakos/work/ptfe_cases/windows_remote_fail/lol123
Initializing modules...
2018/12/19 13:16:31 [TRACE] module source: "./modules"
- module.primarycluster
2018/12/19 13:16:31 [DEBUG] plugin: waiting for all plugin processes to complete...
Error downloading modules: Error loading modules: module primarycluster: open .terraform\modules\974ffb2e225fb642401b5c0ab9548da6: no such file or directory
```
### Expected Behavior
Terraform should finish initialising the local directory.

### Actual Behavior
It fails with the error above.

### Steps to Reproduce

* Create a small terraform configuration using modules (source of module is not relevant)
* Configure terraform to use the remote backend
* Run `terraform plan`

### Additional Context
When a user runs `terraform apply" from a windows system we pack the working directory and upload it to TFE.

Part of the slug we upload is the file `.terraform/modules/modules.json` which terraform uses to figure out where each module is located.

The problem is that since windows use a different directory separator than linux we end up with entries like these: 

```"Dir": ".terraform\\modules\\974ffb2e225fb642401b5c0ab9548da6",```

... which make perfect sense on a windows system, but if we run `terraform init` on a linux system we get:
```
Error downloading modules: Error loading modules: module primarycluster: open .terraform\modules\974ffb2e225fb642401b5c0ab9548da6: no such file or directory
```
since \ has a different meaning here.

**Comment by svanharmelen** [comment]
Thanks for opening this issue @koikonom! I just looked at the related code and noticed this this is actually already fixed in master. So the required fixes for this will be in the upcoming v0.12.0 release.

I'll close this issue, but feel free to reopen it in case you have additional concerns!
