### ISSUE TITLE
Add a cleaning option

### ISSUE THREAD

**Issue by tpoindessous** [hashicorp/terraform#19698]
### Proposal
Hi

I use Terraform with CI and I have a lot of cleaning lines like : rm -rf -- .terraform/

It would nice to have a cleaning option in Terraform : `terraform clean` 

It's a minor issue but it's Christmas !

Thanks !

**Comment by pkolyvas** [comment]
Hey @tpoindessous this isn't on our roadmap. I wish I could snap my fingers and bring you this gift, but we're not likely to tackle it. Hope you're well and thanks for the submission!
