### ISSUE TITLE
Missing aws_iam_role Documentation

### ISSUE THREAD

**Issue by jamescarr** [hashicorp/terraform#1971]
Documentation on `aws_iam_role` seems to be missing from the site. However I did find an example at https://www.terraform.io/docs/providers/aws/r/iam_instance_profile.html which I copied:

```
resource "aws_iam_role" "zk_role" {
    name = "staging_zookeeper"
    path = "/"
    policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::staging-zookeeper",
        "arn:aws:s3:::staging-zookeeper/*"
      ],
      "Effect": "Allow"
    }
  ]
}
EOF
}
```

of which `tf plan` resulted in

```
Errors:

  * aws_iam_role.zk_role: "assume_role_policy": required field is not set
  * aws_iam_role.zk_role: : invalid or unknown key: policy
```

This is on Terraform 0.5.0

**Comment by radeksimko** [comment]
This is [already fixed](https://github.com/hashicorp/terraform/pull/1935), the documentation just hasn't been released yet as it already contains unreleased features.
