### ISSUE TITLE
about depends_on from aws_rds_cluster to aws_rds_cluster_parameter_group.

### ISSUE THREAD

**Issue by fr-yokurah** [hashicorp/terraform#19717]
### Current Terraform Version
```
0.11.10
```

### Use-cases
When I upgrade rds aurora cluster from 9.6.8 to 10.5, engine version is modify only, but cluster parameter group is remoev/create.
So I configure "depends on" setting to aws_rds_cluster resource.

```
resource "aws_rds_cluster" ""cluster {
depends_on [aws_rds_cluster_parameter_group.parameter]
...
}

resource "aws_rds_cluster_parameter_group" "parameter" {
...
}
```
But aws_rds_cluster is still modify only.

### Attempted Solutions
I remove rds cluster at AMC console manually.

### Proposal
If resource A have dependency to B, when B is remove/create, A is also remove/create.

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues and will be closing this one out. If anyone stumbles onto this one and it's still a concern, please open a new ticket!

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
