### ISSUE TITLE
Add support for AWS Elasticache parameter groups

### ISSUE THREAD

**Issue by saulshanabrook** [hashicorp/terraform#1972]
It would be great to have support for creating parameter groups for elasticache in AWS. 

Currently you can set the name of the parameter group, when creating an elasticache cluster, but can't create this group.

My use case would be changing `appendonly` in redis to make it persistent.

**Comment by catsby** [comment]
Thanks @saulshanabrook – I've added this request to our "Terraform AWS Provider Coverage" doc that we're using to track requests.

- https://docs.google.com/spreadsheets/d/1yJKjLaTmkWcUS3T8TLwvXC6EBwNSpuQbIq0Y7OnMXhw/edit#gid=1149664272

**Comment by jniesen** [comment]
:+1: needed this today.
