### ISSUE TITLE
Add support for IBM Cloud Kubernetes Service

### ISSUE THREAD

**Issue by wstewartii** [hashicorp/terraform#19729]
Are there any plans to add support for softlayers managed kubernetes service?

https://www.ibm.com/cloud/container-service

**Comment by mildwonkey** [comment]
Hi @wstewartii, that's a good question! 

Are you currently using an IBM Cloud provider for terraform? This is the only one I could find: https://github.com/IBM-Cloud/terraform-provider-ibm. If you are using that one, then I'd recommend you open a github issue or feature request with them.
