### ISSUE TITLE
S3 Backend other than AWS ?

### ISSUE THREAD

**Issue by src386** [hashicorp/terraform#19733]
Scaleway recently introduced storage object with S3 api.

So I tried to use the S3 backend overriding the endpoint using ```AWS_S3_ENDPOINT=https://s3.nl-ams.scw.cloud ``` but this does not work, according to the log the token is still checked against AWS ...

Is it possible to use the S3 backend with something else than AWS ?

**Comment by src386** [comment]
Found #12377

After reading this [comment](https://github.com/hashicorp/terraform/pull/15553#issuecomment-334724247) I added:

```
skip_requesting_account_id = true
skip_credentials_validation = true
skip_get_ec2_platforms = true
skip_metadata_api_check = true
```

And now it works.

It's a workarround...

**Comment by mildwonkey** [comment]
It looks like there's some need for a 'generic' s3 backend, or at least a better workaround, so I will label this issue as a feature request. I am glad that you found a workaround!

**Comment by src386** [comment]
@aboeglin I don't use it anymore because of the price, but I used:
```
export AWS_DEFAULT_REGION='ams1'
export AWS_S3_ENDPOINT='https://s3.nl-ams.scw.cloud'
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
```
ACCES_KEY_ID is the token (I think)
SECRET_ACCESS_KEY is the key of the token (I think)

**Comment by juicemia** [comment]
@aboeglin did you ever work around that error? I'm having the same issue.

**Comment by Controlor** [comment]
@juicemia i hope you fix the problem :) 

Mixing: 

In the terraform backend ressource: 
```sh
    skip_credentials_validation = true
    skip_region_validation      = true
  ```
  
  and the env variable : 
  ```sh
 export AWS_DEFAULT_REGION='ams1'
export AWS_S3_ENDPOINT='https://s3.nl-ams.scw.cloud'
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
  ```

Works well for me

**Comment by jar-b** [comment]
As several comments above have suggested, setting the necessary `skip_*` parameters to by-pass AWS-specific authorization steps is generally the approach we make available for non-AWS S3 compatible storage providers. Our support for these providers is considered "best effort", as we only directly acceptance test against Amazon S3 when developing the S3 backend. 

Given several comments have indicated setting the `skip_` parameters resulted in successful configurations for non-AWS providers, I'm going to close this issue.
