### ISSUE TITLE
Terraform state file missing 

### ISSUE THREAD

**Issue by sriraja53** [hashicorp/terraform#19747]
### Terraform Version

Terraform v0.11.10

To store the terraform.tfstate file in remote I am using AWS s3 . 

Scenario 
I am running the terraform code via jenkins.
While running the terraform code, the Jenkins server went down and the build got aborted. While checking  state file in s3 there is no terraform.tfstate file. While running terraform apply command it will create the same environment again.

Command 
terraform init
terraform plan
terraform apply

**Comment by jimsmith** [comment]
Implement AWS S3 bucket versioning as best practice described here 
https://www.terraform.io/docs/backends/types/s3.html

**Comment by mildwonkey** [comment]
Hi @sriraja53 ,
I'm very sorry to hear that your terraform state file was lost - @jimsmith's suggestion regarding s3 bucket versioning is absolutely correct.
In the meantime, you can import your existing resources back into terraform state manually with the [`terraform import` command](https://www.terraform.io/docs/import/index.html).
