### ISSUE TITLE
Add a Cloudfront Datasource

### ISSUE THREAD

**Issue by jangolano** [hashicorp/terraform#19750]
### Current Terraform Version
Terraform v0.11.11
+ provider.aws v1.54.0

### Use-cases
It would be nice to have a Cloudfront datasource defined, so that we can pull information from existing resource and reuse.

**Comment by slapula** [comment]
I can take a shot at this. However, it may be more appropriate to open this request in https://github.com/terraform-providers/terraform-provider-aws since that is where this code will live.
