### ISSUE TITLE
TypeSet values are different after import on 0.12, fails ImportStateVerify

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform#19759]
### Terraform Version
```
Terraform 0.12alpha4 vendored into the Google provider (https://github.com/terraform-providers/terraform-provider-google/pull/2753)
```

### Terraform Configuration Files
```hcl
resource "google_compute_firewall" "default" {
  name    = "test-firewall"
  network = "${google_compute_network.default.name}"
  allow {
    protocol = "icmp"
  }
  allow {
    protocol = "tcp"
    ports    = ["80", "8080", "1000-2000"]
  }
  source_tags = ["web"]
}
resource "google_compute_network" "default" {
  name = "test-network-%s"
}
`
```

Source: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_firewall_generated_test.go#L48

### Debug Output
```
--- FAIL: TestAccComputeFirewall_firewallBasicExample (140.12s)
    testing.go:544: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) (len=6) {
         (string) (len=15) "allow.0.ports.#": (string) (len=1) "3",
         (string) (len=15) "allow.0.ports.0": (string) (len=2) "80",
         (string) (len=15) "allow.0.ports.1": (string) (len=4) "8080",
         (string) (len=15) "allow.0.ports.2": (string) (len=9) "1000-2000",
         (string) (len=16) "allow.0.protocol": (string) (len=3) "tcp",
         (string) (len=16) "allow.1.protocol": (string) (len=4) "icmp"
        }


        (map[string]string) (len=6) {
         (string) (len=16) "allow.0.protocol": (string) (len=4) "icmp",
         (string) (len=15) "allow.1.ports.#": (string) (len=1) "3",
         (string) (len=15) "allow.1.ports.0": (string) (len=2) "80",
         (string) (len=15) "allow.1.ports.1": (string) (len=4) "8080",
         (string) (len=15) "allow.1.ports.2": (string) (len=9) "1000-2000",
         (string) (len=16) "allow.1.protocol": (string) (len=3) "tcp"
        }
```

### Expected Behavior
There is no diff, `ImportStateVerify` succeeds

### Actual Behavior
See above

### Steps to Reproduce
```
make testacc TEST=./google TESTARGS='-parallel=1 -run=TestAccComputeFirewall_firewallBasicExample'
```

on https://github.com/terraform-providers/terraform-provider-google/pull/2753

### Additional Context
Running in CI + locally, I'm a Google provider maintainer, we've vendored `0.12alpha4` in our branch

I really don't expect to see `0` or `1` there- this a `TypeSet`, so I'm not sure why they aren't hashes.

### References
N/A

**Comment by apparentlymart** [comment]
Hi @rileykarson!

I can't explain everything going on here, but I suspect it using these numeric indices for the set elements is a result of Core's new approach to sets aimed at eventually addressing #6477. Although the SDK is still using the old implementation with the hash values in the keys, the shimming mechanism used in the test harness in order to preserve the old API is producing its data directly from the Core representation of sets now stored in state, converting it back to this flatmap-like representation just so the old API can continue to work.

So with that said, it looks like this is caused by a bug in that shim that isn't using a deterministic ordering when converting back to that flatmap representation.

**Comment by jbardin** [comment]
Hi @rileykarson,

This should be fixed now in the test harness, but unfortunately it's going to require updating the state values again (unless of course if these are captured during the test itself). We didn't realize the extent that provider were using the state set structure in tests, so I inserted a mechanism to recreate the old set hashes when shimming the state.

**Comment by rileykarson** [comment]
Thanks!

We weren't testing any specific set hashes, this was all through `ImportStateVerify` so the values were recorded from the first post-`Create` state, then the resource was imported into a fresh state and the values compared.

I'll track this as fixed on our side, I'll update this if we run into more issues on our next test run.

**Comment by rileykarson** [comment]
This has been fixed for us.
