### ISSUE TITLE
Resource 'aws_instance' not found for variable 'aws_instance.id'.

### ISSUE THREAD

**Issue by ackris** [hashicorp/terraform#19762]
Hi

I have started using terraform to automate AWS resource provisioning for setting up k8s cluster. I am facing an issue when trying to refer aws_instance.id from aws_eip. Here are the useful details:

```
aditya@aditya-VirtualBox:~/Desktop/terraform-states$ terraform -v
Terraform v0.11.11
+ provider.aws v1.54.0
```
**1) aws-eip.tf**
```
resource "aws_eip" "nat" {
    instance = "${aws_instance.xenial.id}"
    vpc = true
    depends_on = ["aws_internet_gateway.esya_igw"]
}
```

2) **aws_inst.tf:**
```
resource "aws_instance" "xenial" {
    ami = "${var.aws_ami}"
    instance_type = "t3.large"
    ebs_optimized = true
    monitoring = true
    count = "8"
    key_name = "${var.aws_key_name}"
    tags{
        Name = "KubeVMCluster${count.index + 1}"
    }
}
```
**Expected Behavior**: AWS EIP must be able to refer to AWS Instance. 
**Current Behavior**: We are getting this error:
```
aditya@aditya-VirtualBox:~/Desktop/terraform-states$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* aws_eip.nat: 1 error(s) occurred:

* aws_eip.nat: Resource 'aws_instance.xenial' not found for variable 'aws_instance.xenial.id'
```
I have tried to find a solution by referring to similar kind of issues in Github and elsewhere, but to no avail. According to me, I don't find anything problematic with the declarative code. 

I need help in resolving this issue. 

Regards
Aditya

**Comment by mravindrabigsofa** [comment]
Hi ,
looks like your are creating ec2 instance with count which means you need to refer to instance ids with 

 aws_instance.xenial.*.id

You need to amend your aws_eip as below 

resource "aws_eip" "nat" {
    count = "8"
    instance= "${element(aws_instance.xenial.*.id,count.index)}"
    vpc = true
   depends_on = ["aws_internet_gateway.esya_igw"]
}

**Comment by ackris** [comment]
Thanks @mravindrabigsofa

Your suggestion has solved my issue. 

Regards
Aditya
