### ISSUE TITLE
Getting terraform script of already existing gke cluster

### ISSUE THREAD

**Issue by a8uhnf** [hashicorp/terraform#19909]
I've a gke k8s cluster. Is there any way I can get terraform script of already existed k8s cluster?

What I've tried
---
I've used terraform `datasource` (something like [this](https://www.terraform.io/docs/providers/google/d/google_container_cluster.html)) to get the k8s cluster information.

From this information I've created existing cluster's terraform script. Then use `terraform plan` and `terraform apply` like [this](https://www.terraform.io/docs/providers/google/r/container_cluster.html)

But when use `terraform plan` it shows plan for create new cluster.

Also when use `terraform apply` it shows:

```
1 error(s) occurred:

* module.gke.google_container_cluster.primary: 1 error(s) occurred:

* google_container_cluster.primary: googleapi: Error 409: Already exists: projects/xxxxxxx/zones/asia-east1-a/clusters/XXXXX., alreadyExists

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by mildwonkey** [comment]
Hi @a8uhnf,
We don't have any way to automatically generate the terraform code to represent an existing resource, but you can create it manually and use `terraform import` to import the cluster into your terraform state.

Here is the [google container cluster import documentation](https://www.terraform.io/docs/providers/google/r/container_cluster.html#import).

**Comment by a8uhnf** [comment]
Thanks a lot.
