### ISSUE TITLE
0.12 alpha removes resource from state when in-place update fails

### ISSUE THREAD

**Issue by chrisst** [hashicorp/terraform#19908]
### Terraform Version

Latest build from master as of today.
```
Terraform v0.12.0-dev
```

### Debug Output
https://gist.github.com/chrisst/88d2dbe21a9eb9ca9c1431553c100dee

### Expected Behavior
As of 0.11 when an update in place failed the resource would stay in the state. I would expect 0.12 to behave the same way.

### Actual Behavior
The update to the resource fails and the error is returned as expected, but the resource is then removed from state so that a subsequent `terraform plan` attempts to create a brand new resource instead of trying to re-apply the update.

### Steps to Reproduce
Find a resource that will error when a field is updated in place, right now `google_monitoring_uptime_check_config` will fail if you attempt to update `period` right now as not updatable upstream. 

### Additional Context
Log line from the code that appears to be responsible for the removal: https://github.com/hashicorp/terraform/blob/master/terraform/eval_state.go#L223

**Comment by apparentlymart** [comment]
Thanks for reporting this, @chrisst.

I suspect we're marking the object as tainted in this case, like we would do during a create. We can test this by trying to run `terraform untaint` against it before planning again.

During early development we discussed allowing a provider to signal to core that an updated had failed in a way that taints the object in state, which it would use if the object is left in an unrecoverable state as a result of the update. We ended up postponing that to allow for some more research into the use-cases, but I think some of the code for it may still be in place causing us to incorrectly taint on some or all update failures.

**Comment by chrisst** [comment]
I saw the following get printed out in the trace output:
```
2019/01/05 14:16:07 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/01/05 14:16:07 [TRACE] <root>: eval: *terraform.EvalWriteState
```

but I was unable to untaint the resource as it's already been removed from state by the end of the `apply` command. So `terraform untaint  google_monitoring_uptime_check_config.import` returns with:
```
Error: No such resource instance

The state currently contains no resource instances whatsoever. This may occur
if the configuration has never been applied or if it has recently been
destroyed.
```

**Comment by apparentlymart** [comment]
Hi again @chrisst! Thanks for that additional context.

In your original comment you mentioned the line of code that produces a log line like the following:

```
[TRACE] EvalWriteState: removing state object for google_monitoring_uptime_check_config.import
```

...but I don't see that log line in the log output you shared. Was just wondering how you reached the conclusion that this was the offending codepath, and whether there was some more information in the log (including this log line) that you edited out?

As you've seen, all of the different `EvalWriteState` possibilities should be covered by at least one log message, so it's strange to me that there are none of these at all in the log output you shared. Assuming that's an unedited log, that suggests something pretty strange is going on, so I just want to confirm before investigating further.

Thanks again!

**Comment by chrisst** [comment]
TBH I saw that in my debug output at some point but apparently when I went to re-run this and capture the output for the bug report it was no longer present. I've re-run the same failure scenario against the latest in master just now and the resource is still removed from state but not seeing that particular log line any more.

Unfortunately my terminal has long since been purged so I don't have the original reference any more, sorry!

**Comment by chrisst** [comment]
To clarify, the provided log is partially edited; I removed some blocks that were not particularly relevant but all of it was from before the actual PATCH request. So if it helps, here's a more full console session showing the state before and the full apply call: https://gist.github.com/chrisst/6f01303024f4df7dee1e2827f2632cc3

**Comment by apparentlymart** [comment]
Thanks @chrisst! We'll have a closer look at this in the near future.
