### ISSUE TITLE
resource "" config: unknown module referenced: targets

### ISSUE THREAD

**Issue by results-may-vary** [hashicorp/terraform#19906]
### Terraform Version

```
Terraform v0.11.10
```

### Crash Output

module 'fe_ws_listener': reference to undefined module "targets"

### Expected Behavior
Targets module is accessible when running Plan, output returned and used in another module.

### Steps to Reproduce

I have two modules in the main.tf stored in the same hierarchy:
 
module "fe_ws_targetgroup" {
  source = "../../modules/targets"
  name   = "fe-ws"
  vpc_id = "${module.vpc.vpc_out}"
  load_balancer_arn="${module.alb.alb_out}"
port="XXXX"
}

module "fe_rest_listener" {
  source = "../../modules/listeners"
  load_balancer_arn="${module.alb.alb_out}"
  target_group_arn="${module.targets.tg_out}"
  port="XXXX"
}

Calling the "targets" module, everything runs ok and I can see good output during Plan:
resource "aws_lb_target_group" "fe_targets" {
  name     = "${var.name}-targetgroup"
  port     = 80
  protocol = "HTTP"
  vpc_id   = "${var.vpc_id}"
}
**output "tg_out" {
  value = "${aws_lb_target_group.fe_targets.arn}"
}**

Back to the Listener module in main, the output line above is used in the following module:

module "fe_rest_listener" {
  source = "../../modules/listeners"
  load_balancer_arn="${module.alb.alb_out}"
  **target_group_arn="${module.targets.tg_out}"**
  port="XXXX"
}

Using the output called from the "Targets", running the "Listeners" module causes error "module 'fe_rest_listener': reference to undefined module "targets"".
I have set a few output lines which are used in other modules with no issues, but this one just won't budge. What am I missing?
Thanks in advance.

**Comment by mildwonkey** [comment]
Hi @results-may-vary!

It looks like you are confusing the module _name_ with the module _source_. In the code you've shared, you don't have a module named "targets". Your modules are named "fe_ws_targetgroup" and "fe_rest_listener".

I believe this is what you're looking for:

```hcl
module "fe_rest_listener" {
     source = "../../modules/listeners"
     load_balancer_arn="${module.alb.alb_out}"
     target_group_arn="${module.fe_ws_targetgroup.tg_out}"
     port="XXXX"
}
```

Hope this helps!

**Comment by results-may-vary** [comment]
Hi @mildwonkey ,
Thanks, missed that one. Totally a "Doh!" moment.
