### ISSUE TITLE
Not able to install Kubernetes using remote-exec, facing unable to locate package kubectl issue

### ISSUE THREAD

**Issue by bhargav-b** [hashicorp/terraform#19927]
Hello team,

I am trying to create a Kubernetes cluster using terraform remote-exec on AWS. Till now, I am able to create  IGWs, Route tables ans subntes. Also I am able to create a master EC2 instance through Terraform. On this EC2 instance (assuming this as my Kubernetes master node), I am trying to install/setup Kubeadm, kubectl and all uisng "remote-exec" through my terraform script. But I am facing following issue.

aws_instance.master7: Still creating... (50s elapsed)
aws_instance.master7 (remote-exec): ERROR: This command can only be used by root.
aws_instance.master7 (remote-exec): (23) Failed writing body
aws_instance.master7 (remote-exec): /tmp/terraform_1722076684.sh: line 6: /etc/apt/sources.list.d/kubernetes.list: Permission denied

![image](https://user-images.githubusercontent.com/30067565/50740042-a0e95880-120e-11e9-91fd-e3c19d3cca99.png)

Here is my script 👍 
sudo apt-get update && sudo apt-get install -y apt-transport-https

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
sudo apt-get update
sudo apt-get install -y kubectl=1.10.0-00 kubelet=1.10.0-00 kubeadm=1.10.0-00 docker.io

Here is my Ouput:

aws_instance.master7 (remote-exec): Connected!
aws_instance.master7 (remote-exec): 0% [Working]
aws_instance.master7 (remote-exec): Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
aws_instance.master7 (remote-exec): 0% [Waiting for headers] [1 InRelease 2
aws_instance.master7 (remote-exec): Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
aws_instance.master7 (remote-exec): 0% [Waiting for headers] [1 InRelease 1
aws_instance.master7 (remote-exec): 0% [2 InRelease gpgv 247 kB] [Waiting f
aws_instance.master7 (remote-exec): 0% [Waiting for headers] [1 InRelease 1
aws_instance.master7 (remote-exec): Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
aws_instance.master7 (remote-exec): 0% [3 InRelease 2600 B/109 kB 2%] [1 In
aws_instance.master7 (remote-exec): 0% [3 InRelease 34.5 kB/109 kB 32%]
aws_instance.master7 (remote-exec): 0% [1 InRelease gpgv 107 kB] [3 InRelea
aws_instance.master7 (remote-exec): 0% [3 InRelease 50.4 kB/109 kB 46%]
aws_instance.master7 (remote-exec): Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [596 kB]
aws_instance.master7 (remote-exec): 0% [3 InRelease 99.6 kB/109 kB 91%] [4
aws_instance.master7 (remote-exec): 0% [4 Packages 23.0 kB/596 kB 4%]
aws_instance.master7 (remote-exec): 0% [3 InRelease gpgv 109 kB] [Waiting f
aws_instance.master7 (remote-exec): 0% [Waiting for headers] [4 Packages 10
aws_instance.master7 (remote-exec): Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
aws_instance.master7 (remote-exec): 0% [5 InRelease 2600 B/107 kB 2%] [4 Pa
aws_instance.master7 (remote-exec): 0% [4 Packages 272 kB/596 kB 46%]
aws_instance.master7 (remote-exec): 0% [5 InRelease gpgv 107 kB] [Waiting f
aws_instance.master7 (remote-exec): 16% [Waiting for headers] [4 Packages 4
aws_instance.master7 (remote-exec): 17% [Waiting for headers]
aws_instance.master7 (remote-exec): 17% [4 Packages store 0 B] [Waiting for
aws_instance.master7 (remote-exec): Get:6 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7532 kB]
aws_instance.master7 (remote-exec): 17% [4 Packages store 0 B] [6 Packages
aws_instance.master7 (remote-exec): 18% [6 Packages 182 kB/7532 kB 2%] [Wai
aws_instance.master7 (remote-exec): Get:7 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [248 kB]
aws_instance.master7 (remote-exec): 18% [6 Packages 194 kB/7532 kB 3%] [7 T
aws_instance.master7 (remote-exec): 20% [6 Packages 243 kB/7532 kB 3%]
aws_instance.master7 (remote-exec): 20% [7 Translation-en store 0 B] [6 Pac
aws_instance.master7 (remote-exec): 21% [6 Packages 376 kB/7532 kB 5%] [Wai
aws_instance.master7 (remote-exec): Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [411 kB]
aws_instance.master7 (remote-exec): 22% [6 Packages 566 kB/7532 kB 8%] [8 P
aws_instance.master7 (remote-exec): 25% [6 Packages 753 kB/7532 kB 10%]
aws_instance.master7 (remote-exec): 25% [8 Packages store 0 B] [6 Packages
aws_instance.master7 (remote-exec): 27% [6 Packages 1150 kB/7532 kB 15%] [W
aws_instance.master7 (remote-exec): Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [161 kB]
aws_instance.master7 (remote-exec): 29% [6 Packages 1600 kB/7532 kB 21%] [9
aws_instance.master7 (remote-exec): 30% [6 Packages 1693 kB/7532 kB 22%] [W
aws_instance.master7 (remote-exec): 30% [9 Translation-en store 0 B] [6 Pac
aws_instance.master7 (remote-exec): 33% [6 Packages 2078 kB/7532 kB 28%] [W
aws_instance.master7 (remote-exec): Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3724 B]
aws_instance.master7 (remote-exec): 39% [6 Packages 3323 kB/7532 kB 44%] [1
aws_instance.master7 (remote-exec): 39% [6 Packages 3323 kB/7532 kB 44%]
aws_instance.master7 (remote-exec): 39% [10 Packages store 0 B] [6 Packages
aws_instance.master7 (remote-exec): 39% [6 Packages 3344 kB/7532 kB 44%] [W
aws_instance.master7 (remote-exec): Get:11 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [1844 B]
aws_instance.master7 (remote-exec): 47% [6 Packages 4880 kB/7532 kB 65%] [1
aws_instance.master7 (remote-exec): 47% [6 Packages 4880 kB/7532 kB 65%]
aws_instance.master7 (remote-exec): 47% [11 Translation-en store 0 B] [6 Pa
aws_instance.master7 (remote-exec): 47% [6 Packages 4895 kB/7532 kB 65%]
aws_instance.master7 (remote-exec): 60% [Working]
aws_instance.master7 (remote-exec): 60% [6 Packages store 0 B] [Waiting for
aws_instance.master7 (remote-exec): Get:12 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en [4354 kB]
aws_instance.master7 (remote-exec): 61% [6 Packages store 0 B] [12 Translat
aws_instance.master7 (remote-exec): 82% [6 Packages store 0 B] [Waiting for
aws_instance.master7 (remote-exec): Get:13 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
aws_instance.master7 (remote-exec): 82% [6 Packages store 0 B] [13 Packages
aws_instance.master7 (remote-exec): 83% [6 Packages store 0 B]
aws_instance.master7 (remote-exec): Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
aws_instance.master7 (remote-exec): 83% [6 Packages store 0 B] [14 Translat
aws_instance.master7 (remote-exec): 83% [6 Packages store 0 B]
aws_instance.master7 (remote-exec): Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [900 kB]
aws_instance.master7 (remote-exec): 83% [6 Packages store 0 B] [15 Packages
aws_instance.master7 (remote-exec): 88% [6 Packages store 0 B] [Waiting for
aws_instance.master7 (remote-exec): Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [363 kB]
aws_instance.master7 (remote-exec): 88% [6 Packages store 0 B] [16 Translat
aws_instance.master7 (remote-exec): 89% [6 Packages store 0 B] [Waiting for
aws_instance.master7 (remote-exec): Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [717 kB]
aws_instance.master7 (remote-exec): 90% [6 Packages store 0 B] [17 Packages
aws_instance.master7 (remote-exec): 93% [6 Packages store 0 B] [Waiting for
aws_instance.master7 (remote-exec): Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [294 kB]
aws_instance.master7 (remote-exec): 93% [6 Packages store 0 B] [18 Translat
aws_instance.master7 (remote-exec): 94% [18 Translation-en 159 kB/294 kB 54
aws_instance.master7 (remote-exec): 94% [12 Translation-en store 0 B] [18 T
aws_instance.master7 (remote-exec): 95% [12 Translation-en store 0 B] [Wait
aws_instance.master7 (remote-exec): Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.6 kB]
aws_instance.master7 (remote-exec): 95% [12 Translation-en store 0 B] [19 P
aws_instance.master7 (remote-exec): 95% [12 Translation-en store 0 B] [Wait
aws_instance.master7 (remote-exec): Get:20 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8440 B]
aws_instance.master7 (remote-exec): 95% [12 Translation-en store 0 B] [Wait
aws_instance.master7 (remote-exec): Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7280 B]
aws_instance.master7 (remote-exec): 95% [12 Translation-en store 0 B] [Wait
aws_instance.master7 (remote-exec): Get:22 http://archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [4456 B]
aws_instance.master7 (remote-exec): 95% [12 Translation-en store 0 B] [Wait
aws_instance.master7 (remote-exec): 95% [Waiting for headers]
aws_instance.master7 (remote-exec): 95% [13 Packages store 0 B] [Waiting fo
aws_instance.master7 (remote-exec): 96% [Waiting for headers]
aws_instance.master7 (remote-exec): 96% [14 Translation-en store 0 B] [Wait
aws_instance.master7 (remote-exec): Get:23 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7804 B]
aws_instance.master7 (remote-exec): 96% [14 Translation-en store 0 B] [Wait
aws_instance.master7 (remote-exec): 96% [Waiting for headers]
aws_instance.master7 (remote-exec): 96% [15 Packages store 0 B] [Waiting fo
aws_instance.master7 (remote-exec): 97% [Waiting for headers]
aws_instance.master7 (remote-exec): 97% [16 Translation-en store 0 B] [Wait
aws_instance.master7 (remote-exec): 97% [Waiting for headers]
aws_instance.master7 (remote-exec): 97% [17 Packages store 0 B] [Waiting fo
aws_instance.master7 (remote-exec): Get:24 http://archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4184 B]
aws_instance.master7 (remote-exec): 97% [17 Packages store 0 B]
aws_instance.master7 (remote-exec): 97% [Working]
aws_instance.master7 (remote-exec): 97% [18 Translation-en store 0 B]
aws_instance.master7 (remote-exec): 98% [Working]
aws_instance.master7 (remote-exec): 98% [19 Packages store 0 B]
aws_instance.master7 (remote-exec): 98% [Working]
aws_instance.master7 (remote-exec): 98% [20 Translation-en store 0 B]
aws_instance.master7 (remote-exec): 98% [Working]
aws_instance.master7 (remote-exec): 98% [21 Packages store 0 B]
aws_instance.master7 (remote-exec): 99% [Working]
aws_instance.master7 (remote-exec): 99% [22 Translation-en store 0 B]
aws_instance.master7 (remote-exec): 99% [Working]
aws_instance.master7 (remote-exec): 99% [23 Packages store 0 B]
aws_instance.master7 (remote-exec): 100% [Working]
aws_instance.master7 (remote-exec): 100% [24 Translation-en store 0 B]
aws_instance.master7 (remote-exec): 100% [Working]
aws_instance.master7 (remote-exec): Fetched 16.2 MB in 4s (3469 kB/s)
aws_instance.master7 (remote-exec): Reading package lists... 0%
aws_instance.master7 (remote-exec): Reading package lists... 0%
aws_instance.master7 (remote-exec): Reading package lists... 1%
aws_instance.master7 (remote-exec): Reading package lists... 6%
aws_instance.master7 (remote-exec): Reading package lists... 6%
aws_instance.master7 (remote-exec): Reading package lists... 9%
aws_instance.master7 (remote-exec): Reading package lists... 9%
aws_instance.master7 (remote-exec): Reading package lists... 10%
aws_instance.master7 (remote-exec): Reading package lists... 10%
aws_instance.master7 (remote-exec): Reading package lists... 10%
aws_instance.master7 (remote-exec): Reading package lists... 10%
aws_instance.master7 (remote-exec): Reading package lists... 48%
aws_instance.master7 (remote-exec): Reading package lists... 48%
aws_instance.master7 (remote-exec): Reading package lists... 69%
aws_instance.master7 (remote-exec): Reading package lists... 69%
aws_instance.master7 (remote-exec): Reading package lists... 70%
aws_instance.master7 (remote-exec): Reading package lists... 70%
aws_instance.master7 (remote-exec): Reading package lists... 70%
aws_instance.master7 (remote-exec): Reading package lists... 70%
aws_instance.master7 (remote-exec): Reading package lists... 76%
aws_instance.master7 (remote-exec): Reading package lists... 76%
aws_instance.master7 (remote-exec): Reading package lists... 78%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 85%
aws_instance.master7 (remote-exec): Reading package lists... 85%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 91%
aws_instance.master7 (remote-exec): Reading package lists... 91%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 98%
aws_instance.master7 (remote-exec): Reading package lists... 98%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... Done
aws_instance.master7 (remote-exec): Reading package lists... 0%
aws_instance.master7 (remote-exec): Reading package lists... 100%
aws_instance.master7 (remote-exec): Reading package lists... Done
aws_instance.master7 (remote-exec): Building dependency tree... 0%
aws_instance.master7 (remote-exec): Building dependency tree... 0%
aws_instance.master7 (remote-exec): Building dependency tree... 50%
aws_instance.master7 (remote-exec): Building dependency tree... 50%
aws_instance.master7 (remote-exec): Building dependency tree
aws_instance.master7 (remote-exec): Reading state information... 0%
aws_instance.master7 (remote-exec): Reading state information... 6%
aws_instance.master7 (remote-exec): Reading state information... Done
aws_instance.master7 (remote-exec): The following packages will be upgraded:
aws_instance.master7 (remote-exec):   apt-transport-https
aws_instance.master7 (remote-exec): 1 upgraded, 0 newly installed, 0 to remove and 85 not upgraded.
aws_instance.master7 (remote-exec): Need to get 26.2 kB of archives.
aws_instance.master7 (remote-exec): After this operation, 1024 B of additional disk space will be used.
aws_instance.master7 (remote-exec): 0% [Working]
aws_instance.master7 (remote-exec): Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 apt-transport-https amd64 1.2.29 [26.2 kB]
aws_instance.master7 (remote-exec): 8% [1 apt-transport-https 2615 B/26.2 k
aws_instance.master7 (remote-exec): 100% [Working]
aws_instance.master7 (remote-exec): Fetched 26.2 kB in 0s (65.9 kB/s)
aws_instance.master7 (remote-exec): (Reading database ...
aws_instance.master7 (remote-exec): (Reading database ... 5%
aws_instance.master7 (remote-exec): (Reading database ... 10%
aws_instance.master7 (remote-exec): (Reading database ... 15%
aws_instance.master7 (remote-exec): (Reading database ... 20%
aws_instance.master7 (remote-exec): (Reading database ... 25%
aws_instance.master7 (remote-exec): (Reading database ... 30%
aws_instance.master7 (remote-exec): (Reading database ... 35%
aws_instance.master7 (remote-exec): (Reading database ... 40%
aws_instance.master7 (remote-exec): (Reading database ... 45%
aws_instance.master7 (remote-exec): (Reading database ... 50%
aws_instance.master7 (remote-exec): (Reading database ... 55%
aws_instance.master7 (remote-exec): (Reading database ... 60%
aws_instance.master7 (remote-exec): (Reading database ... 65%
aws_instance.master7 (remote-exec): (Reading database ... 70%
aws_instance.master7 (remote-exec): (Reading database ... 75%
aws_instance.master7 (remote-exec): (Reading database ... 80%
aws_instance.master7 (remote-exec): (Reading database ... 85%
aws_instance.master7 (remote-exec): (Reading database ... 90%
aws_instance.master7 (remote-exec): (Reading database ... 95%
aws_instance.master7 (remote-exec): (Reading database ... 100%
aws_instance.master7 (remote-exec): (Reading database ... 51284 files and directories currently installed.)
aws_instance.master7 (remote-exec): Preparing to unpack .../apt-transport-https_1.2.29_amd64.deb ...
aws_instance.master7 (remote-exec): Unpacking apt-transport-https (1.2.29) over (1.2.27) ...
aws_instance.master7 (remote-exec): Setting up apt-transport-https (1.2.29) ...
aws_instance.master7: Still creating... (50s elapsed)
aws_instance.master7 (remote-exec): ERROR: This command can only be used by root.
aws_instance.master7 (remote-exec): (23) Failed writing body
aws_instance.master7 (remote-exec): /tmp/terraform_1722076684.sh: line 6: /etc/apt/sources.list.d/kubernetes.list: Permission denied
aws_instance.master7 (remote-exec): 0% [Working]
aws_instance.master7 (remote-exec): Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
aws_instance.master7 (remote-exec): 0% [Waiting for headers] [Waiting for h
aws_instance.master7 (remote-exec): Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
aws_instance.master7 (remote-exec): 0% [Waiting for headers]
aws_instance.master7 (remote-exec): 0% [1 InRelease gpgv 247 kB] [Waiting f
aws_instance.master7 (remote-exec): 0% [Waiting for headers]
aws_instance.master7 (remote-exec): 0% [2 InRelease gpgv 107 kB] [Waiting f
aws_instance.master7 (remote-exec): Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
aws_instance.master7 (remote-exec): 0% [2 InRelease gpgv 107 kB] [Waiting f
aws_instance.master7 (remote-exec): 0% [Waiting for headers]
aws_instance.master7 (remote-exec): 0% [3 InRelease gpgv 109 kB] [Waiting f
aws_instance.master7 (remote-exec): 0% [Waiting for headers]
aws_instance.master7 (remote-exec): Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
aws_instance.master7 (remote-exec): 0% [Working]
aws_instance.master7 (remote-exec): 0% [4 InRelease gpgv 107 kB]
aws_instance.master7 (remote-exec): 20% [Working]
aws_instance.master7 (remote-exec): Reading package lists... 0%
aws_instance.master7 (remote-exec): Reading package lists... 0%
aws_instance.master7 (remote-exec): Reading package lists... 1%
aws_instance.master7 (remote-exec): Reading package lists... 6%
aws_instance.master7 (remote-exec): Reading package lists... 6%
aws_instance.master7 (remote-exec): Reading package lists... 9%
aws_instance.master7 (remote-exec): Reading package lists... 9%
aws_instance.master7 (remote-exec): Reading package lists... 10%
aws_instance.master7 (remote-exec): Reading package lists... 10%
aws_instance.master7 (remote-exec): Reading package lists... 10%
aws_instance.master7 (remote-exec): Reading package lists... 10%
aws_instance.master7 (remote-exec): Reading package lists... 48%
aws_instance.master7 (remote-exec): Reading package lists... 48%
aws_instance.master7 (remote-exec): Reading package lists... 69%
aws_instance.master7 (remote-exec): Reading package lists... 69%
aws_instance.master7 (remote-exec): Reading package lists... 70%
aws_instance.master7 (remote-exec): Reading package lists... 70%
aws_instance.master7 (remote-exec): Reading package lists... 70%
aws_instance.master7 (remote-exec): Reading package lists... 70%
aws_instance.master7 (remote-exec): Reading package lists... 76%
aws_instance.master7 (remote-exec): Reading package lists... 76%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 81%
aws_instance.master7 (remote-exec): Reading package lists... 82%
aws_instance.master7 (remote-exec): Reading package lists... 85%
aws_instance.master7 (remote-exec): Reading package lists... 85%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 87%
aws_instance.master7 (remote-exec): Reading package lists... 91%
aws_instance.master7 (remote-exec): Reading package lists... 91%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 95%
aws_instance.master7 (remote-exec): Reading package lists... 98%
aws_instance.master7 (remote-exec): Reading package lists... 98%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... 99%
aws_instance.master7 (remote-exec): Reading package lists... Done
aws_instance.master7 (remote-exec): Reading package lists... 0%
aws_instance.master7 (remote-exec): Reading package lists... 100%
aws_instance.master7 (remote-exec): Reading package lists... Done
aws_instance.master7 (remote-exec): Building dependency tree... 0%
aws_instance.master7 (remote-exec): Building dependency tree... 0%
aws_instance.master7 (remote-exec): Building dependency tree... 50%
aws_instance.master7 (remote-exec): Building dependency tree... 50%
aws_instance.master7 (remote-exec): Building dependency tree
aws_instance.master7 (remote-exec): Reading state information... 0%
aws_instance.master7 (remote-exec): Reading state information... 7%
aws_instance.master7 (remote-exec): Reading state information... Done
aws_instance.master7 (remote-exec): E: Unable to locate package kubectl
aws_instance.master7 (remote-exec): E: Unable to locate package kubelet
aws_instance.master7 (remote-exec): E: Unable to locate package kubeadm

I am facing 2 issues. I am attaching the screen shots.

![issue1](https://user-images.githubusercontent.com/30067565/50740066-40a6e680-120f-11e9-820d-7cb99cc42c35.PNG)
![issue2](https://user-images.githubusercontent.com/30067565/50740070-48668b00-120f-11e9-836a-3b17e7c868c1.PNG)

Any suggestions, would be deeply appreciated.

**Comment by mildwonkey** [comment]
Hi @bhargav-b ,
Your script needs to be run by root. Without seeing your configuration files, I'd guess you need to add `sudo` before running the script.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by bhargav-b** [comment]
Thanks for replying me. Anyways, However I have run it as a root user. However I will post the question in Community forums.

Thank you.
