### ISSUE TITLE
data.terraform_remote_state crash if remote state contains `output "config"`.

### ISSUE THREAD

**Issue by major0** [hashicorp/terraform#19945]
### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.51.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```hcl
/* Remote project which outputs some useful data to a statefile */
terraform {
  backend "s3" {
    region  = "us-west-2"
    bucket  = "terraform-remotestate"
    key     = "terraform/remote_test.tfstate"
    dynamodb_table = "terraform-statelock"
  }
}

output "config" {
  value = "${
    map(
      "key1", "Hello",
      "key2", "World"
    )
  }"
}

output "workspace" {
  value = "coffee shop"
}

output "backend" {
  value = "storage"
}
```

```hcl
data "terraform_remote_state" "s3" {
  workspace = "${terraform.workspace}"
  backend   = "s3"

  config {
    bucket = "terraform-remotestate"
    region = "us-west-1"
    key    = "terraform/remote_test.tfstate"
  }
}

locals {
  workspace = "${data.terraform_remote_state.s3.workspace}"
  backend   = "${data.terraform_remote_state.s3.backend}"
  config    = "${data.terraform_remote_state.s3.config}"
}

output "hello" {
  value = "${local.config["key1"]}"
}
```

### Crash Output

https://gist.github.com/major0/1009ee3780bff2fbeffdc11bbb7d570d

### Expected Behavior

Gracefully handle conflicting keys, warning message, something.

### Actual Behavior

Terraform sometimes crashes and, with the right code, can be convinced to reference the data in interesting ways (memory corrupt). When locking with DynamoDB the state file is left in a locked state.

### Steps to Reproduce

In the `remote` directory:
1. `terraform init`
2. `terraform refresh`

In the `local` directory:
1. `terraform init`
2. `terraform refresh`

**Comment by jbardin** [comment]
Hi @major0,

Thanks for filing the issue. The "config" attribute holds the configuration for the backend, but because outputs are added directly to the attributes of the resource, an output called `config` will collide. 

In 0.12 the outputs will be held in a separate map called `outputs`, so there no longer can be any collisions, and it's clear that you're accessing data from within an attribute of the resource.
