### ISSUE TITLE
Stage settings is alternating between being created and not being created 

### ISSUE THREAD

**Issue by DavidIndrawes2** [hashicorp/terraform#19949]
### Terraform Version

```
Terraform v0.11.11
```

### Terraform resource
```hcl
resource "aws_api_gateway_method_settings" "stage_settings" {
  rest_api_id = "${aws_api_gateway_rest_api.atf_api_gateway.id}"
  stage_name  = "${aws_api_gateway_deployment.atf_api_gateway_deployment.stage_name}"
  method_path = "*/*"

  settings {
    logging_level = "INFO"
  }

  depends_on = [
    "aws_api_gateway_deployment.atf_api_gateway_deployment"
  ]
}
```

### Expected Behavior
every time I run the terraform apply, I expect to see the stage settings on the stage.
if they were not there originally they should be added, if they were there origionally they should be kept there.

### Actual Behavior
It does alternate the stage settings creation, 
If currently the stage_setting exists, then in the next `terraform apply` it will be deleted, 
and vice verse if currently the stage_settings does not exist, then next `terraform apply` will add it.

### Steps to Reproduce
1. start with clean environment no resources
2. `terraform apply` >> will deploy the API gateway and create the stage settings
3. `terraform apply` again with redeployment for the API gateway >> then the API will be redeployed to the stage correctly except the **stage settings are not created**
4. `terraform apply` again with redeployment for the API gateway >> then the API will be redeployed to the stage correctly and the **stage settings are created**
5. `terraform apply` again with redeployment for the API gateway >> then the API will be redeployed to the stage correctly except the **stage settings are not created**
6. `terraform apply` again with redeployment for the API gateway >> then the API will be redeployed to the stage correctly and the **stage settings are created**
7. ...etc

From my understanding that the terraform plans ahead before apply and terraform sees that the stage_settings are already there so it will not try to create them but when it destroys the stage and redeploy the API again, during this redeployment it happens that the stage_settings will be deleted, the next time terraform plan will not see the stage_setting so it adds it to the list of resources to be created on the apply.
And the loop keeps going like that forever.

**Comment by mildwonkey** [comment]
Hi @DavidIndrawes2, I'm sorry to hear about this issue.
I'd like to try and identify if the problem lies in terraform core, or in the AWS provider. Could you share the output of `TF_LOG=debug terraform apply` as a gist (really from any stage but I'd definitely like to see apply from a fresh start)?

**Comment by DavidIndrawes2** [comment]
Hi @mildwonkey,

Thanks for your response.
Logs for both cases are attached
 [when settings are created](https://gist.github.com/DavidIndrawes2/925985cc0f5a6f63eaf873f8fc0baaaa) 
[when settings are deleted](https://gist.github.com/DavidIndrawes2/3403233010ac80f45cc30f6b93562e3c) 

terraform component used for this logs 

```
resource "aws_api_gateway_deployment" "atf_api_gateway_deployment" {

  rest_api_id       = "000000000"
  stage_name        = "my_stage"
  description       = ""
  stage_description = ""

  variables = {
  }
}

resource "aws_api_gateway_method_settings" "stage_settings" {
  rest_api_id = "000000000"
  stage_name  = "${aws_api_gateway_deployment.atf_api_gateway_deployment.stage_name}"
  method_path = "*/*"

  settings {
    logging_level = "INFO"
  }

  depends_on = [
    "aws_api_gateway_deployment.atf_api_gateway_deployment"
  ]
}
```

**Comment by alapto** [comment]
Hi!

Any progress on this issue? This is preventing the use of `aws_api_gateway_method_settings` with Terraform and there seems to be no workaround for this issue either.

**Comment by DavidIndrawes2** [comment]
Hi @alapto after further investigation, I found that the issue happens when you don't define explicit `aws_api_gateway_stage` block but instead you create the stage by passing a stage_name parameter to `aws_api_gateway_deployment` block.

So here is the workaround I've used at that time:

1. Create the deployment without defining a stage_name.
2. then create an explicit stage block and assign this deployment to it.
```
resource "aws_api_gateway_deployment" "test" {
  rest_api_id = "${aws_api_gateway_rest_api.tes.id}"
}

resource "aws_api_gateway_stage" "test" {
  stage_name    = "test"
  rest_api_id   = "${aws_api_gateway_rest_api.test.id}"
  deployment_id = "${aws_api_gateway_deployment.test.id}"
}
```
But I guess this work around has potential cycle issues with terraform 0.12

**Comment by alapto** [comment]
Hi @DavidIndrawes2, thank you for your support. Your solution works but unfortunately it is not usable in my case. Terraform API GW module has an another bug, where changes in resources like integration request will not initiate stage deployment.

To overcome this, I added timestamp to stage description, which then caused re-deployment every time when applying changes but this only works if used together with stage definition in `aws_api_gateway_deployment` resource. When defining the stage using `aws_api_gateway_stage` resource it will void this timestamp hack and there is no more stage re-deployment.

**Comment by DavidIndrawes2** [comment]
I would have expected it to work because the deployment_id is changing with every new deployment that forces the stage resource to update, unless the deployment id is not changing!

**Comment by alapto** [comment]
Figured out what happened and after moving the stage definition outside of `aws_api_gateway_deployment` resource, updating the description did not cause re-deployment to occur anymore.

Luckily this can be achieved by using timestamp in variables map, like below.
```
lifecycle {
    create_before_destroy = true
  }
  variables = {
    deployed_at = "${timestamp()}"
  }
```
Lifecycle configuration is also must to ensure that new deployment is created and stage pointed to that one, prior to removing the old deployment.

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

Terraform 0.12 has been available since May of 2019, and there are really significant benefits to adopting it. I know that migrating from 0.11 to versions past 0.12 can require a bit of effort, but it really is worth it, and the upgrade path is pretty well understood in the community by now. 0.14 is available and stable, and we are quickly approaching an 0.15 release.

We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
