### ISSUE TITLE
Is terraform required to rm and re-create an AWS security group if the description changes?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#1995]
```
-/+ aws_security_group.my-elb
    description:                          "Allow HTTPS to ELB" => "Allow WORLD access to HTTPS" (forces new resource)
    egress.#:                             "1" => "<computed>"
    ingress.#:                            "2" => "2"
    ...
```

It drives me a tiny bit crazy that a small edit like this to the description of an AWS resource ends up recreating the resource. I would not care, except this triggers TF to rm and recreate the dependent resources.. so I have to fight with TF to keep it from rm'ing my live instances.

Is TF required to make the changed noted above by removing the resource?

**Comment by phinze** [comment]
I am totally in the same "tiny bit crazy" camp as you, :grinning: but alas, AWS provides no API to update SG descriptions. (You'll notice you can't do it in the web console either.) I myself have given up on SG descriptions and leave the default "Manged by Terraform", and I've turned to tags to store the equivalent human-readable info.

**Comment by ketzacoatl** [comment]
Right, I was debating the value of removing the `description` field from those resources that have it.. but the option is nice for those who want it. In the end, the problem I see is this: without better guidance, newbs will walk down this route and have to fend off TF from rm'ing their instances. Does it make sense to document and official recommendation?

**Comment by phinze** [comment]
While in general I think we have to draw a line somewhere in terms of how much we consider ourselves responsible for educating users about details on upstream cloud services, I'd be willing to accept a docs PR that tried to steer users in the right direction in this case. Feel free to take a stab! :+1:

**Comment by ketzacoatl** [comment]
I will make an attempt on that PR. It is more nuanced than adding a single line or note, but I will figure it out and request feedback when I think I have it.
