### ISSUE TITLE
Provisioner Defaults

### ISSUE THREAD

**Issue by nevir** [hashicorp/terraform#1996]
It'd be nice to be able to specify defaults for provisioners (`connection` info especially).

It's annoying to have to repeat `connection { user = "ubuntu" }` everywhere when using ubuntu AMIs

**Comment by zonzamas** [comment]
:+1:

**Comment by catsby** [comment]
Hey @nevir sorry for the super long reply time (a year+ !) 
I'm going to close this however; I don't believe defaults would be helpful here, as we have no real way of knowing how many of our users actually use Ubuntu over say Amazon Linux, so a default here would just be a shot in the dark.

**Comment by joshuaspence** [comment]
I might be misunderstanding the original request, but I think that default values make sense if they can be specified, rather than hardcode into Terraform itself. For example, default values for resources can be specified in Puppet using a capital letter in the type of the resource:

```
File {
  owner => 'root',
}

File { '/foo/bar':
  # No need to specify `owner => 'root'`
}
```

**Comment by joshuaspence** [comment]
So for this specific use case, I can see this being useful:

```
default "aws_instance" {
  provisioner "remote-exec" {
    connection {
      user = "ubuntu"
    }
  }
}
```
