### ISSUE TITLE
Unexpected 403 from Consul backend when running plan

### ISSUE THREAD

**Issue by usererror** [hashicorp/terraform#19963]
### Terraform Version

```
0.11.10
```

### Terraform Configuration Files

```hcl
terraform {
  backend "consul" {
    path = "tfstate"
    gzip = true
  }
}
```

### Debug Output

The debug output in this case doesn't add much context unfortunately and wasn't worth putting into a gist:

```
... (omitting successful steps)
2019/01/10 12:56:59 [INFO] command: backend *consul.Backend is not enhanced, wrapping in local
2019/01/10 12:56:59 [INFO] backend/local: starting Plan operation

2019/01/10 12:56:59 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error locking state: Error acquiring the state lock: Unexpected response code: 403 (Permission denied)
```

### Expected Behavior

I expected that with `write` privileges on Consul's session API Terraform would be able to establish the state lock.

### Actual Behavior

Consul denies Terraform's request to acquire a session lock with a `403 (Permission denied)`.

### Steps to Reproduce

1. Create a terraform configuration that uses Consul remote state
2. Create a Consul token with the ACL policy described below
3. Use that Consul token when running `terraform plan`

### Additional Context

The workflow I am trying to facilitate is that `terraform plan` is run with a Consul token that has as limited a policy as possible, ideally not being able to modify state, only read it. This ensures some level of enforced safety when CICD runs on pull requests to the configuration. 

A more locked down, separate CICD step would have a different Consul token with higher privileges so it can run `terraform apply`.

The Consul cluster is running version 1.4.0 and is using Consul's new ACL system. When using the Master Token with the `global-management` policy Terraform is able to run.

Upon switching to a token that has the following Consul ACL policy I get the 403 error:

```hcl
key_prefix "tfstate" {
 policy = "read"
}

session "" {
  policy = "write"
}
```

### References

The docs for ACLing Consul's `session` API can be found here: https://www.consul.io/docs/agent/acl-rules.html#session-rules

**Comment by usererror** [comment]
I tried adding `write` to the same `tfstate` prefix and, magically, `terraform plan` could run again. This was unexpected so I took a peek at where Terraform actually acquires the state lock in Consul (https://github.com/hashicorp/terraform/blob/master/backend/remote-state/consul/client.go#L236) and noticed it tries to lock at $PATH/.lock. With that in mind, I replaced the blanket `write` stanza in the policy with the following more limited version and now I can create sessions again:

```hcl
key_prefix "tfstate/.lock" {
 policy = "write"
}
```

This works (that CICD step can acquire a lock but not actually modify state) and I believe things are actually working as intended. Having said that, this is unintuitive given that the Terraform docs mention only that session permissions are required when using locking with the Consul backend.

Does it sound reasonable to update the docs to reflect the above or is this too much of a niche use case?

**Comment by mildwonkey** [comment]
@usererror - your use case for minimal permissions on `plan` makes sense to me. It's reasonable to add to the documentation. Thank you for opening this, and updating it with your solution!

**Comment by usererror** [comment]
Thanks for the quick response @wildmonkey! I just opened a PR to terraform with a first take on the doc changes.

**Comment by usererror** [comment]
I'm going to close this out since the corresponding PR has been merged, thanks all!

**Comment by Nowaker** [comment]
@usererror What exactly should the session ACL look like? There's an example here at https://www.consul.io/docs/agent/acl-rules.html#session-rules but I don't understand the implications of those.

**Comment by usererror** [comment]
@Nowaker The session API is odd in that sessions are tied to actual nodes rather than the Consul cluster itself as you might expect. From the [docs](https://www.consul.io/api/session.html#create-session):

"This endpoint initializes a new session. Sessions **must be associated with a node** and may be associated with any number of checks."

The string used in the ACL examples you linked limit the nodes that the token with that policy can create sessions against. If you want to be able to create sessions against any node (effectively against the entire cluster), you should use the empty string for the `session_prefix`. I believe that this includes any Consul agent registered with the cluster.

A better pattern may be to name your actual Consul servers with a prefix, let's say `nowaker-` in this case, and then limit session creation to only those nodes like so:

```
session_prefix "" {
  policy = "read"
}

session_prefix "nowaker-" {
  policy = "write"
}
```

The best configuration is going to depend highly on how your Consul cluster and applications are setup though.
