### ISSUE TITLE
Parse Output map variables

### ISSUE THREAD

**Issue by DRAKUN** [hashicorp/terraform#19967]
### Current Terraform Version

```
Latest
```

### Use-cases

Often we work with variables whose composition is unknown.
It would be nice to have an option to parse the contents of the variables in the OUTPUT in order to know how the result is composed in MAP or list etc .....

**Comment by mildwonkey** [comment]
Hi @DRAKUN,
Thank you for opening this feature request. I think I understand _in theory_ what you are asking for, but it would help if you could add your specific use case, and any ideas you might have for the end result - for example, would you like a new CLI command that outputs the structure of a variable?

**Comment by mildwonkey** [comment]
I'm going to close this issue as there's been no response. Please feel free to open a new issue or feature request with additional information if you are still interested. Thank you!
