### ISSUE TITLE
Referencing capture groups in replace() fails with underscore

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/terraform#19970]
I am attempting to place an underscore between the border between lower and uppercase characters in a string. Terraform doesn't seem to be able to process a capture group when the group number is followed by an underscore.

### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
output "nounderscore" {
  value = "${replace("aaaAAA","/([a-z])([A-Z])/","$1$2")}"
}

output "underscore" {
  value = "${replace("aaaAAA","/([a-z])([A-Z])/","$1_$2")}"
}

output "space" {
  value = "${replace("aaaAAA","/([a-z])([A-Z])/","$1 $2")}"
}
```

### Expected Behavior
```
nounderscore = aaaAAA
space = aaa AAA
underscore = aaa_AAA
```

### Actual Behavior
The value of $1 is lost. I suspect it is being processed as `$1_`.

```
nounderscore = aaaAAA
space = aaa AAA
underscore = aaAAA
```

**Comment by jhmartin** [comment]
It looks like the following works:
```
output "underscore" {
  value = "${replace("aaaAAA","/([a-z])([A-Z])/","$${1}_$2")}"
}
```

**Comment by mildwonkey** [comment]
Thanks for updating this with the proper syntax, @jhmartin !
