### ISSUE TITLE
terraform init issue - not working 

### ISSUE THREAD

**Issue by ramgopalmanur** [hashicorp/terraform#19987]
$ terraform init
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
$ terraform validate terraform/

Error: 2 error(s) occurred:

* provider.template: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

**Comment by apparentlymart** [comment]
Hi @ramgopalmanur,

You ran `terraform init` in a directory with no configuration files, so it did not install any providers. Instead, switch to the directory containing your configuration files:

```
cd terraform
terraform init
terraform validate
```
