### ISSUE TITLE
Backport pull request https://github.com/hashicorp/terraform/pull/19951 to TF 0.11

### ISSUE THREAD

**Issue by marcelloromani** [hashicorp/terraform#19992]
### Current Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.55.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Use-cases

The S3 backend of the AWS provider suffers from intermittent timeouts, which PR https://github.com/hashicorp/terraform/pull/19951 fixes.

It would be great if this fix could be applied to 0.11 so that one wouldn't have to wait for 0.12

### Attempted Solutions

I am not aware of workarounds that provide the same fix.

### Proposal

Port https://github.com/hashicorp/terraform/pull/19951 to the lates TF 0.11 release.

### References

https://github.com/hashicorp/terraform/pull/19951

**Comment by bflad** [comment]
These fixes have been merged for release in Terraform version 0.11.14.
