### ISSUE TITLE
remote/swift: add workspace support

### ISSUE THREAD

**Issue by kayrus** [hashicorp/terraform#19993]
### Current Terraform Version

```
Terraform v0.11.11
```

### Use-cases

Multiple workspaces should be supported by the swift backend.

### Attempted Solutions

I'm using the `terraform init --backend-config container=terraform/workspace1/`, but it is not convenient.

### Proposal

https://github.com/hashicorp/terraform/blob/21d65cfa9a5f081018c4569a8be522ea3744f9a7/backend/remote-state/swift/backend_state.go file should be modified to provide this support.

**Comment by kayrus** [comment]
@mildwonkey do we have any chance to merge swift workspaces support into v0.11.x?

**Comment by rafilkmp3** [comment]
+1

**Comment by bfilipek** [comment]
Any ETA for this enhancement?

**Comment by kayrus** [comment]
workspaces are supported starting from v0.12
