### ISSUE TITLE
Clarify local backend "path" parameter behavior

### ISSUE THREAD

**Issue by shinglyu** [hashicorp/terraform#20008]
### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
# backend.tf
terraform {
  backend "local" {}
}
```

```hcl
# backend.config
path = "test.tfstate"
```

### Expected Behavior

Running `terraform init -backend-config=backend.config` follow by `terraform plan` should create a state file named `test.tfstate`, as described in the `path` in the `backend.config`.

### Actual Behavior

The state file is still created in the default filename: `.terraform/terraform.tfstate`

### Steps to Reproduce

- `terraform init -backend-config=backend.config`
- `terraform plan`

### Additional Context

Documentation: https://www.terraform.io/docs/backends/types/local.html

The content of `.terraform/terraform.tfstate`:
```
{
    "version": 3,
    "serial": 1,
    "lineage": "90f01795-a80d-38e4-6271-0d3716721a8e",
    "backend": {
        "type": "local",
        "config": {
            "path": "./test.tfstate"
        },
        "hash": 6268923742653417519
    },
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        }
    ]
}
```
Notice tha `path` is stored in the state, but it doesn't seem to affect the behavior at all. The state is still read from/write to the default `.terraform/terraform.tfstate` file.

**Comment by msanath** [comment]
I too ran into the same issue. Any solution?

**Comment by igitcode** [comment]
Running into this same issue now.

**Comment by mildwonkey** [comment]
The file created in `.terraform/terraform.tfstate` is not the state file where your created resources are tracked. Instead this is a file terraform itself uses to track the backend configuration. This file will _always_ get created; it is a terraform implementation detail. It is not the file where terraform will track resources, etc. 

This is working as designed, so I am going to close it. Thanks, and sorry for the confusion!
