### ISSUE TITLE
Can I disable key-pair?

### ISSUE THREAD

**Issue by worapojc** [hashicorp/terraform#20001]
I'm using Terraform to launch an instance on AWS. However, I cannot launch it because my company has some policy and break the launch process.

So, I try to create the instance manually on EC2 Dashboard. It needs to launch the instance without any key-pair.

How can I disable key-pair using at the launch state in Terraform?

**Comment by abiydv** [comment]
As per the [docs](https://www.terraform.io/docs/providers/aws/r/instance.html), you can skip specifying the keypair at launch.

> key_name - (Optional) The key name of the Key Pair to use for the instance; which can be managed using the aws_key_pair resource.

Do you get any errors if you don't specify the key?

**Comment by worapojc** [comment]
Thanks. It works now.
