### ISSUE TITLE
Versions 0.5.1 and 0.5.2

### ISSUE THREAD

**Issue by dgoodlad** [hashicorp/terraform#2001]
According to CHANGELOG.md

> 0.5.1 (never released)
> This version was never released since we accidentally skipped it!

but on https://www.terraform.io/downloads.html:

> Below are all available downloads for the latest version of Terraform (0.5.1).

Is 0.5.1 on terraform.io actually 0.5.2?

**Comment by radeksimko** [comment]
> Is 0.5.1 on terraform.io actually 0.5.2?

Yes, it is...
https://github.com/hashicorp/terraform/commit/4ed2c8d956d2eae83a2a3750290711ce7fa1ec76#commitcomment-11223140

Next release will hopefully have matching versions.
Feel free to reopen if it's causing you anything more than inconvenience and/or if you have any suggestion on how to fix it.
