### ISSUE TITLE
v0.12-alpha1 terraform get error parsing HCL2 syntax

### ISSUE THREAD

**Issue by SpencerBrown** [hashicorp/terraform#20024]
### Terraform Version

```
Terraform v0.12.0-alpha1
```

### Terraform Configuration Files

```hcl
variable "bar" {
  default = "foobar"
}

resource "local_file" "foo" {
  filename = "foo.bar"
  content = var.bar
}
```

### Debug Output

```text

Spencer-Brown:bug spencer$ TF_LOG=trace terraform get
2019/01/16 07:54:43 [INFO] Terraform version: 0.12.0 alpha1
2019/01/16 07:54:43 [INFO] Go runtime version: go1.11.4
2019/01/16 07:54:43 [INFO] CLI args: []string{"/Users/spencer/bin/terraform", "get"}
2019/01/16 07:54:43 [DEBUG] Attempting to open CLI config file: /Users/spencer/.terraformrc
2019/01/16 07:54:43 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/01/16 07:54:43 [INFO] CLI command args: []string{"get"}
Error loading configuration: Error parsing /Users/spencer/mongodb/tf-x509/bug/main.tf: At 7:13: Unknown token: 7:13 IDENT var.bar
```

### Expected Behavior

terraform get should not error because I have an HCL2 variable value without the "${}"

### Actual Behavior

Error loading configuration: Error parsing /Users/spencer/mongodb/tf-x509/bug/main.tf: At 7:13: Unknown token: 7:13 IDENT var.bar

### Steps to Reproduce

1. `terraform init` 
2. `terraform validate`
3. `terraform get`

### Additional Context

saw this error with alpha1, also tried with master branch of terraform, same error

**Comment by jbardin** [comment]
Hi @SpencerBrown 

Sorry for the inconvenience here. That release is a few moths out of date; the latest alpha is v0.12.0-alpha4. The bare variable syntax should work with the latest alpha and with the current master as well.

**Comment by apparentlymart** [comment]
Hi @SpencerBrown!

It does seem like something weird is going on here, since that error message looks like what we'd expect to see from the _old_ config parser (0.11 and earlier) rather than new. Perhaps there's some remnant code still calling into the old parser somewhere.

I'm going to re-open this so we can investigate further and see what's going on before we do v0.12.0 final.

**Comment by jbardin** [comment]
Sorry, that was my error parsing, `terraform get` is the issue here.
Looks like `get` is still calling the old config loader to list module sources.
