### ISSUE TITLE
Unable to run command 'terraform init' in master branch on MacOS

### ISSUE THREAD

**Issue by lrxtom2** [hashicorp/terraform#20043]
**Repro Steps:**
1. go get -v github.com/hashicorp/terrraform
2. generare config file as below:
provider "azurerm" {
      version = "1.21.0"
}
3. terraforn init

**Error Message:**
No available provider "azurerm" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    1.21.0

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.

Error: no available version is compatible with this version of Terraform

**Comment by apparentlymart** [comment]
Hi @lrxtom2,

There are currently no `azurerm` provider releases compatible with Terraform v0.12.0, which is what `master` currently represents.

If you're trying to use Terraform "for real", you should either download one  of [the official releases](https://www.terraform.io/downloads.html) or build from the `v0.11.11` tag.

If you are intending instead to try out the work-in-progress v0.12.0 release, you can either build an `azurerm` provider binary yourself from [its own repository](https://github.com/terraform-providers/terraform-provider-azurerm) or download [the latest 0.12.0 alpha build](https://releases.hashicorp.com/terraform/0.12.0-alpha4/) and take the `terraform-provider-azurerm...` file from that and place it in your `$GOPATH/bin`.

Please note that Terraform is generally not designed to be "go get"-able for normal use. Instead, we recommend using the official releases.

v0.12.0-compatible provider releases will appear shortly as we prepare to release v0.12.0-beta1.
