### ISSUE TITLE
How to create new resource(ami) from an existing AWS instance

### ISSUE THREAD

**Issue by renawebwizard** [hashicorp/terraform#20072]
### Terraform Version

```
v0.11.11
```

### Terraform Configuration Files

```
resource "aws_instance" "jenkins_instance" {
	
	ami = "ami-02fd0b06f06d93dfc"
	instance_type = "t2.micro"
	vpc_security_group_ids = ["${aws_security_group.allow_jenkins.id}"]
	tags {

		Name = "Jenkins_Server"
	}

	
}

resource "aws_ami_from_instance" "jenkins_ami" {
	
	name = "jenkins_ami"
	source_instance_id = "${aws_instance.jenkins_instance.id}"
}
...
```

### Expected Behavior

What should have happened?

I have created a aws_instance and installed jenkins on it. Did few configuration changes. Now i want to create ami from this modified instance and create new instance from this ami using terraform.

Initial instance creation was successful. But when i modify my main.tf file to create ami as below:

resource "aws_ami_from_instance" "jenkins_ami" {
	
	name = "jenkins_ami"
	source_instance_id = "${aws_instance.jenkins_instance.id}" 

Its destroying my existing instance on which i have done the changes creating a new instance and then making an AMI from that.

### Actual Behavior
I dont want to do any changes to my existing instance. I just want to create ami  from existing instance.

**Comment by DevallaSubbu** [comment]
We have created AMI based on the creation of Ec2, Adding EBS Volume(d, H O T) and custom SQL installation and other client software).

Now we would like to create a terraform script to create new Ec2 node based on existing  AMI. Could some on help on this? I'm new to terraform.
