### ISSUE TITLE
0.12 ImportStateCheck call in testStepImportState not yet updated for new state types

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform#20125]
### Terraform Version

```
# go.mod
github.com/hashicorp/terraform v0.12.0-alpha4.0.20190124012834-1592b4aa67ad
```

### Expected Behavior

Acceptance testing passes as it did previously in Terraform 0.11 or `ImportStateCheck` is removed.

### Actual Behavior

Receive error on the tin. Just filing as a tracking issue for this TODO code item. 😄 

```
--- FAIL: TestAccAWSIAMGroupPolicyAttachment_basic (9.97s)
    testing.go:568: Step 1 error: ImportStateCheck call in testStepImportState not yet updated for new state types

--- FAIL: TestAccAWSRolePolicyAttachment_basic (8.34s)
    testing.go:568: Step 1 error: ImportStateCheck call in testStepImportState not yet updated for new state types

--- FAIL: TestAccAWSUserPolicyAttachment_basic (7.59s)
    testing.go:568: Step 1 error: ImportStateCheck call in testStepImportState not yet updated for new state types

--- FAIL: TestAccAWSS3Bucket_importWithPolicy (5.60s)
    testing.go:568: Step 1 error: ImportStateCheck call in testStepImportState not yet updated for new state types
```

### Steps to Reproduce

Run any of the aforementioned acceptance tests from a 0.12 upgraded branch of the AWS provider.

**Comment by apparentlymart** [comment]
#20148 should've addressed the issue _as stated_ here, but it revealed a new problem where `ImportStateVerify` is _also_ not functioning correctly in the new SDK, so I'm going to leave this issue open for the moment to represent that remaining problem.

The remaining issue is covered by the `test` provider case `TestResourceDefaults_import`, which is currently stubbed out in the `master` branch but can be re-enabled to observe the failure:

```
--- FAIL: TestResourceDefaults_import (0.02s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=5) {
         (string) (len=12) "default_bool": (string) (len=1) "1",
         (string) (len=14) "default_string": (string) (len=14) "default string",
         (string) (len=8) "nested.#": (string) (len=1) "1",
         (string) (len=26) "nested.2826070548.optional": (string) (len=3) "val",
         (string) (len=24) "nested.2826070548.string": (string) (len=14) "default nested"
        }
```

As we can see here, it seems that previously some default values from the schema were somehow getting populated but are no longer. While at first glance it seemed like it was just populating the `Default` values from the schema, it's strange that somehow we were expecting there to be an element in that `nested` list, which would naturally default to empty, so we'll need to dig some more in the 0.11 codepath and understand what was populating that and thus what is missing in the 0.12 codepath.

**Comment by apparentlymart** [comment]
Having now re-tested these I see that I must've verified incorrectly last time, because with latest master these are now working. I was misled by a not-quite-correct test in our `test` provider and then over-generalized the problem to apply to something I was seeing in the AWS provider, but I think I actually just had the wrong SDK version vendored when I tested these last time, as a result of some careless branch-switching.
