### ISSUE TITLE
How to read the ephemeral IP of a google_compute_instance after creation?

### ISSUE THREAD

**Issue by maxenglander** [hashicorp/terraform#2012]
Hello,

I would like to allow GCE to assign ephemeral IPs to `google_compute_instance`s, and collect them after creation. It appears from the docs that the GCE provider doesn't expose the ephemeral IP of the instance, however. Is there a way to access this IP?

Thanks for your time, and for this amazing tool.

Max

**Comment by sparkprime** [comment]
Assuming you're using network_interface with an empty access_config block:

${google_compute_instance.foo.network_interface.0.access_config.0.nat_ip}

**Comment by maxenglander** [comment]
That worked perfectly, thank you!
