### ISSUE TITLE
spot fleet json output - retrieve launch specifications as json file to match aws json spec

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform#20129]
Edit: this can be deleted. I double posted this issue under the terraform aws provider repo where it belongs.
https://github.com/terraform-providers/terraform-provider-aws/issues/7346

### Current Terraform Version

```
11.11
```

### Use-cases
AWS Cli and SDK can normallay use JSON output from spot fleet specificaitions in the ec2 console.

It would be helpful for terraform to be able to output its spot fleet spec as a JSON file to be in line with current AWS ability to do this (the bottom left of the spot fleet interface in aws management console has a json button)

My use case is for cloud rendering with aws thinkbox deadline, which takes this json output as the template it will use when 3d renders are submitted.

### Attempted Solutions

None

### Proposal

providing an optional output to aws_spot_fleet_request by the name of json_output_spec
or some such would give us the ability to reference this data.

**Comment by apparentlymart** [comment]
Thanks @queglay... I will close this in preference of terraform-providers/terraform-provider-aws#7346.
