### ISSUE TITLE
Please don't tag beta release as "latest"

### ISSUE THREAD

**Issue by liger1978** [hashicorp/terraform#20134]
You have tagged a beta release (v0.11.12-beta1) as "latest".  Is this intentional?

**Comment by mildwonkey** [comment]
Hi @liger1978 ! Thank you for pointing that out. 

The `latest` tag is applied automatically by github, so we marked the beta as a "pre-release" to remove that tag and updated our release docs internally to remind ourselves of the setting.
Cheers!
