### ISSUE TITLE
add `taint` as a `state` subcommand

### ISSUE THREAD

**Issue by jhoblitt** [hashicorp/terraform#20142]
### Current Terraform Version

```
Terraform v0.11.11
```

### Proposal

At present, not all of the "state" management operations are available as a `state` sub-command, which isn't ideal in terms of "discoverability". I have been helping a co-worker learn tf and they were not aware of `taint` or what it did as it doesn't appear as a `state` sub command. Eg.,

```
Subcommands:
    list    List resources in the state
    mv      Move an item in the state
    pull    Pull current state and output to stdout
    push    Update remote state from a local state file
    rm      Remove an item from the state
    show    Show a resource in the state
```
Either adding a blurb about `taint` to the help output from `state -h` or adding a `state taint` sub-command as an aliases `taint` would probably be helpful to new-ish tf users.

(Also worth noting is that the `state` sub-command are missing some of the functionality of `taint`, such as `-lock`.   It would "feel" more consistent if all of the state related commands that modify state had similar option flags.)

**Comment by matthiasr** [comment]
I don't see `taint` as a low-level state manipulation on the same level as `mv` or `rm`. To me, it's a request to recreate a resource; that it involves changes to the state is an implementation detail.

**Comment by pkolyvas** [comment]
@matthiasr this follows our thinking as well. `taint` isn't a state management operation but rather a resource management operation. 

The output of `terraform -help` does list taint and hopefully there's still some discoverability there. I can very much appreciate the mental model we use isn't always the same one all of our community members have and am grateful for the insight. Hopefully some of these concerns can be remedied with our increase in education via our Terraform Learn guides and tracks: https://learn.hashicorp.com
