### ISSUE TITLE
Invalid Timeout structure errors when running v0.12-based providers using v0.11 cli

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20156]
### Terraform Version

```
Terraform v0.11.8
```

### Terraform Configuration Files

```hcl
resource "oci_email_sender" "test_sender" {
  #Required
  compartment_id = "${var.compartment_ocid}"
  email_address  = "${var.sender_email_address}"

  timeouts {
    create = "10m"
  }
}
```

### Debug Output

...
oci_email_sender.test_sender - *terraform.NodePlannableResourceInstance
2019-01-30T10:54:04.888-0800 [DEBUG] plugin.terraform-provider-oci: 2019/01/30 10:54:04 [ERROR] Invalid timeout structure: []map[string]interface {}
2019/01/30 10:54:04 [DEBUG] Resource state not found for "oci_dns_record.record-txt": oci_dns_record.record-txt
2019/01/30 10:54:04 [DEBUG] ReferenceTransformer: "oci_dns_record.record-txt" references: []
2019/01/30 10:54:04 [DEBUG] Resource state not found for "data.oci_email_suppressions.test_suppressions": data.oci_email_suppressions.test_suppressions
2019/01/30 10:54:04 [DEBUG] Resource state not found for "data.oci_dns_records.records": data.oci_dns_records.records
2019/01/30 10:54:04 [TRACE] Graph after step *terraform.AttachStateTransformer:

data.oci_dns_records.records - *terraform.NodePlannableResourceInstance
2019/01/30 10:54:04 [TRACE] Graph after step *terraform.TargetsTransformer:

data.oci_dns_records.records - *terraform.NodePlannableResourceInstance
2019/01/30 10:54:04 [DEBUG] ReferenceTransformer: "data.oci_dns_records.records" references: []
2019/01/30 10:54:04 [DEBUG] Interpolating computed list element attribute records (74D93920-ED26-11E3-AC10-0800200C9A66)
2019/01/30 10:54:04 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: Error running plan: 1 error(s) occurred:

* oci_email_sender.test_sender: 1 error(s) occurred:

* oci_email_sender.test_sender: [ERR] Error decoding timeout: Invalid Timeout structure found

### Expected Behavior

Running `terraform plan` should have succeeded. It succeeds when using a v0.11-based provider.

### Actual Behavior

Running `terraform plan` results in `oci_email_sender.test_sender: [ERR] Error decoding timeout: Invalid Timeout structure found` error.

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

This scenario involves v0.11 Terraform CLI that loads a provider built on top of `pluginsdk-v0.12-early2`

**Comment by apparentlymart** [comment]
It looks like this is a regression from #19286. The change there was correct, but it also needs to retain the old codepath for compatibility with Terraform 0.11, since the `timeouts` block is represented differently in the wire protocol between the two versions.
