### ISSUE TITLE
If-else interpolation not working with alb_lb_listener resource

### ISSUE THREAD

**Issue by ethicalmohit** [hashicorp/terraform#20164]
I am trying to create resource aws_lb_listener with terraform interpolation for the if-else condition. But It says me there is no change in the infrastructure. However, It has not created https listener yet on the infrastructure. Is anything missing in below code?

### Terraform Version
```
terraform -v
Terraform v0.11.11
+ provider.aws v1.57.0
+ provider.null v2.0.0
+ provider.template v2.0.0
```

### Terraform Configuration Files
alb.tf
```hcl
resource "aws_lb_listener" "https" {
  count = "${var.https_listener_enable == true ? 1 : 0}"
  load_balancer_arn = "${aws_lb.main.arn}"
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-2016-08"
  certificate_arn   = "arn:aws:iam::187416307283:server-certificate/test_cert_rab3wuqwgja25ct3n4jdj2tzu4"

  default_action {
    type = "fixed-response"

  fixed_response {
      content_type = "text/plain"
      message_body = "Nothing is here. Go Away."
      status_code  = "200"
    }
}
}
```
variable.tf
```hcl
variable "https_listener_enable" {
  default = ""
}
```

main.tf
```hcl
module "public_alb" {
  source             = "../modules/alb"
  load_balancer_name = "example-production"
  https_listener_enable = true
  security_groups            = ["${module.security_group.sg_http}"]
  load_balancer_is_internal  = false
  idle_timeout               = 60
  enable_deletion_protection = false
  enable_http2               = true
  tags                       = "${map("Environment", "production",
                "Name", "example-production",)}"
  subnets = "${module.vpc.public_subnets}"

  vpc_id = "${module.vpc.vpc_id}"
}
```
### Expected Behavior
Listener should create if the value of https_listener_enable is true.

### Actual Behavior
The resource is not creating. It is saying no infrastructure changes.

### Steps to Reproduce
```
terraform init
terraform plan -target=module.public_alb -out=/tmp/public
```

**Comment by ethicalmohit** [comment]
> Hi @ethicalmohit
> 
> Try to use the next structure:
> 
> ```
> resource "aws_lb_listener" "https" {
>   count = "${var.https_listener_enable ? 1 : 0}"
>   load_balancer_arn = "${aws_lb.main.arn}"
>   port              = "443"
>   protocol          = "HTTPS"
>   ssl_policy        = "ELBSecurityPolicy-2016-08"
>   certificate_arn   = "arn:aws:iam::187416307283:server-certificate/test_cert_rab3wuqwgja25ct3n4jdj2tzu4"
> 
>   default_action {
>     type = "fixed-response"
> 
>   fixed_response {
>       content_type = "text/plain"
>       message_body = "Nothing is here. Go Away."
>       status_code  = "200"
>     }
> }
> }
> ```
> And set the variable to (for example):
> 
> ```
> variable "https_listener_enable" {
>   default = false
> }
> ```
> And, please provide the debug output to check the issue which you got.

Yes, It is working now. Is there is a specific reason why previous structure is not working? 

Also, Debug output is very big because of the related modules. Do you still want to check anything specific?

**Comment by SebastianUA** [comment]
@ethicalmohit 

If you want to use your variant of code, I think you should try to use:
```
resource "aws_lb_listener" "https" {
  count = "${var.https_listener_enable == "true" ? 1 : 0}"
  load_balancer_arn = "${aws_lb.main.arn}"
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-2016-08"
  certificate_arn   = "arn:aws:iam::187416307283:server-certificate/test_cert_rab3wuqwgja25ct3n4jdj2tzu4"

  default_action {
    type = "fixed-response"

  fixed_response {
      content_type = "text/plain"
      message_body = "Nothing is here. Go Away."
      status_code  = "200"
    }
}
}
```

Because, you set the default value as string ;)

No, the your debug output no needed.   

PS: I have my own Terraform modules in Github. If you are interested at it, you can check/use them here: https://github.com/sebastianua/terraform
I
