### ISSUE TITLE
wrong download terraform zip filename

### ISSUE THREAD

**Issue by julienlavergne** [hashicorp/terraform#2017]
Hi,

The filename of the zip file for linux distros in download section seems to be misnamed.

The filename is the following: 
https://dl.bintray.com/mitchellh/terraform/terraform_0.5.1_linux_amd64.zip

and after extraction the version embedded is 0.5.2 ;-)

**Comment by catsby** [comment]
Hey @julienlavergne – we're aware of the issue, we made a slight slip up:

- https://github.com/hashicorp/terraform/commit/4ed2c8d956d2eae83a2a3750290711ce7fa1ec76#commitcomment-11223140

We'll get that straightened out soon with the next release :smile:
