### ISSUE TITLE
Feature request: How to guide to verify registry modules?

### ISSUE THREAD

**Issue by Jeeppler** [hashicorp/terraform#20173]
How to verify a Terraform registry module? I was unable to find any guide or information whom to contact to propose a registry module for the verification process. 

### Use Cases

This is a general feature request and applies to all modules regardless of associated provider.
However, my specific example case is the [Terraform AWS EKS](https://github.com/terraform-aws-modules/terraform-aws-eks) module. According to the [Terraform Registry statistics for the Terraform AWS EKS](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/) module, the module reached over 40_000 provisions. The module reached a high level of maturity and build a community around it. The community improves and tests the module frequently. For my understanding it fulfils all the requirements to be a verified module. 

### Attempted Solutions

Open up a [pull request](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/259) in the Terraform AWS EKS module repository. @max-rocket-internet one of the core maintainers agreed it would be nice to have the module approved an contacted @antonbabenko the maintainer of the already verified [VPC module](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/). @antonbabenko is one of the core maintainers of the [Terraform AWS Modules](https://github.com/terraform-aws-modules/) modules. Both @max-rocket-internet and @antonbabenko do not know whom to contact or how the verification process works. Meaning active and trusted members of the community are unaware of the verification process.

### Proposal

Create an official guide on how to initiate the module verification process, explain the process in the guide and provide contact information.

Another solution would be to create a foundation or organization for the Terraform Registry. This could provide a neutral platform where both community members and companies can work together. However, that would not solve the overall issue of not having a guide for the verification process. It would just make it easier for trusted community members such as @antonbabenko to verify modules without the involvement of HashiCorp employees.

### References

Pull request: [Verify AWS EKS module in Terraform Module#259](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/259)

**Comment by brant4test** [comment]
Looking forward to a verified Terraform AWS EKS module! Thanks!

**Comment by cgriggs01** [comment]
Hi @Jeeppler,

My name is Chris and I work at HashiCorp on the Partner Alliances team. Thanks for reaching out and taking the time to put together this proposal/feature request. 

We’re currently in the process of enabling Terraform providers to be uploaded in the Registry alongside modules, so we’ve paused our verification program while we do this work. That should wrap up roughly mid-year.  It seems like you have a great module, and we’re totally happy to let you know how to proceed when the program is back on!

**Comment by Jeeppler** [comment]
@brant4test does @cgriggs01response means you will *not* review the Terraform AWS EKS module in the next couple of weeks or even months, because your priorities are somewhere else?

**Comment by brant4test** [comment]
Hi @Jeeppler, I'm a user of [Terraform AWS EKS](https://github.com/terraform-aws-modules/terraform-aws-eks) module, implementing it into our stacks now. A great module!

**Comment by Jeeppler** [comment]
@brant4test I was under the impression that you work for HashiCorp. Sorry, for the miss understanding. I did not know that you are an user.

Indeed Terraform AWS EKS is a great module and we also integrate it in our stacks.

**Comment by laurapacilio** [comment]
Closing this out as we still don't have an official program for verifying modules on the registry. We'll be sure to circle back if/when one gets created - thank you!
