### ISSUE TITLE
0.12 TypeSet Expansion During Plan Inadvertently Consolidating Similar Blocks Containing Unknown Value

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform#20187]
### Terraform Version

```
github.com/hashicorp/terraform v0.12.0-alpha4.0.20190201001850-411dab1dea1a
```

### Terraform Configuration Files

```hcl
# ... other configuration ...

resource "aws_spot_fleet_request" "example" {
    # ... other configuration ...

    launch_specification {
        instance_type = "m3.large"
        ami = "ami-d0f506b0"
        key_name = "${aws_key_pair.example.key_name}"
        subnet_id = "${aws_subnet.foo.id}"
    }

    launch_specification {
        instance_type = "m3.large"
        ami = "ami-d0f506b0"
        key_name = "${aws_key_pair.example.key_name}"
        subnet_id = "${aws_subnet.bar.id}"
    }
}
```

### Debug Output

OSS TeamCity Link: https://HOSTNAME/viewLog.html?buildId=43313&buildTypeId=Aws_ProviderAws&tab=artifacts

### Expected Behavior

Configuration and acceptance testing passes as it previously did in Terraform 0.11.

### Actual Behavior

```
--- FAIL: TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList (7.44s)
    testing.go:568: Step 0 error: errors during apply:
        
        Error: Provider produced inconsistent final plan
        
        When expanding the plan for aws_spot_fleet_request.foo to include new values
        learned so far during apply, provider "aws" produced an invalid new value for
        .launch_specification: block set length changed from 1 to 2.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

### Steps to Reproduce

From an AWS provider branch that has 0.12 upgrade, e.g. `v0.12-sdk-updates-411dab1dea1a`

```
$ TF_ACC=1 go test ./aws -v -timeout 120m -parallel 20 -run=TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList
```

### Additional Context

This test will likely fail similar to #20126 / #20183 after this particular issue is fixed if its anything like the other `TestAccAWSSpotFleetRequest_`.

**Comment by jbardin** [comment]
Interestingly, this doesn't seem to be only a 0.12 issue. The diff itself is what is coalescing the set values. I'm still trying to track down what might be different with the 0.12 shimmed config that could trigger it, but there may be other related open issues if there's no difference in the diff generation code.

**Comment by jbardin** [comment]
Ah, it was actually a 0.11 bug that made it work! In some cases the interpolation strings would slip through to the provider, and in this case it was the different interpolation strings in the `subnet_id` field that let the `hashLaunchSpecification` return different values for the sets.
