### ISSUE TITLE
correct ebs lifecycle 

### ISSUE THREAD

**Issue by julienlavergne** [hashicorp/terraform#2019]
The documentation refers it about the ebs lifecycle:

from AWS_INSTANCE resource page reference:
it said "Modifying any ebs_block_device currently requires resource replacement"
it seems correct for an ebs block device managed by AWS_INSTANCE.
However I need to manage an ebs volume which doesn't have to be destroyed at each instance recreation.

Another way to manage ebs volume is to use AWS_EBS_VOLUME resource; Unfortunately it seems impossible to add the created volume with an instance;

Any idea/solution about my need?

Thx

**Comment by catsby** [comment]
Closing in favor of #2043 which seems to better convey what's missing here
