### ISSUE TITLE
azurerm backend - resource name contains invalid characters

### ISSUE THREAD

**Issue by reddare** [hashicorp/terraform#20201]
### Terraform Version

```
Terraform v0.11.11
+ provider.azurerm v1.21.0
```

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    storage_account_name  = "tstate4598"
    container_name        = "tstate"
    key                   = "terraform.tfstate"
    access_key            = "D+3dw47vnUxIh86BoJA6b+49DBMgaMOwNG4wszhGXT+UVfTjq/Xe4ozExqpi18iRDIuc4OSmRDNI3Ec9vUSVBQ=="
  }
}
```

### Debug Output

https://gist.github.com/reddare/d1c81c2d0c7c20205bb265d321d2e79c
### Crash Output

https://gist.github.com/reddare/fed8c30f85523213df7d757c8ffc2907
### Expected Behavior

Create remote backend with azure.
### Actual Behavior

Crash with `ErrorMessage=The specifed resource name contains invalid characters`.
### Steps to Reproduce

1. Create main.tf with configuration above or with this - https://gist.github.com/reddare/8cc60fd5315fc8b2da42d0f975bd181e
2. try `terraform init`
3. Or it can be done with interactive way for backend setup, same error.

**Comment by reddare** [comment]
Please close, configuration errors problem. Need to clean init to fix this.

**Comment by carlosonunez** [comment]
Hello! It turns out that this will occur if one of the following environment variables has a space or some other invalid character in its string:

```
ARM_SUBSCRIPTION_ID
ARM_TENANT_ID
ARM_CLIENT_ID
ARM_CLIENT_SECRET
```
