### ISSUE TITLE
Changing AWS region causes mixed region resource application

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform#20210]
### Terraform Version
```
0.11.7 and 0.11.11
```

### Terraform Configuration Files
```hcl
provider "aws" {
  region  = "us-east-1"
}
```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
Specifying `us-east-1` as the AWS region should cause Terraform to apply resources in `us-east-1`.

### Actual Behavior
Terraform applies some resources in the specified region `us-east-1` AND some resources in the region cached in `terraform.d` (in this case, `us-west-2`).

### Steps to Reproduce
With Terraform 0.11.7.
1. Specify AWS region as `us-west-2` in the provider.
2. `terraform init`
3. `terraform apply`, `destroy`, etc.

Later with Terraform 0.11.11
1. Update AWS provider version specified in config (also `terraform-aws-vpc` and `terraform-aws-eks` modules which were being declared) from latest during end of June 2018 to latest during end of Jan 2019.
2. Change AWS provider region to `us-east-1`.
3. `terraform init` <-- claimed it was updating provider and module versions despite no `-upgrade` by the way
4. `terraform apply` <-- applied some resources in `us-east-1` and some in `us-west-2`
5. `terraform destroy` <-- for resources in `us-east-1`, they were destroyed or there was a timeout on destroying them; for resources in `us-west-2`, Terraform claimed they were destroyed when they were actually not or there was a timeout on destroying them

### Additional Context
N/A

### References
N/A

**Comment by mschuchard** [comment]
Ok never mind about the root cause. I just discovered this actually occurred because the `profile` and `region` were both being specified in the `provider`, and the `profile` specified `us-east-1` and the `region` specified `us-west-2`, so that was why this erratic behavior occurred.

Seems now more like a bug with the provider than Terraform. Please confirm and I will migrate.

**Comment by apparentlymart** [comment]
Hi @mschuchard! That does indeed seem like a quirk in the provider that perhaps it could address with an explicit test that the profile and region agree, or similar. Please do open an issue in the AWS provider repository, so the AWS provider team can think about what is best to do here! Thanks for reporting this.

**Comment by mschuchard** [comment]
Thanks for the confirm. Migrating this to the Terraform AWS provider.
