### ISSUE TITLE
v0.12: Not calling `ResourceData.Set` on computed attributes results in an empty value in state

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20221]
### Terraform Version

```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

### Terraform Configuration Files

```hcl
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}

provider "oci" {
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region           = "${var.region}"
}

resource "oci_core_virtual_network" "vcn1" {
  cidr_block     = "10.0.0.0/16"
  compartment_id = "${var.compartment_ocid}"
  display_name   = "vcn1"
}
```

### Debug Output

Can be shared on request.

### Expected Behavior

Running apply in v0.11 will result in absence of attributes from state file where the provider doesn't call `ResourceData.Set`.

The state file looks like this. Note that `Set` isn't called for `dns_label` and `vcn_domain_name`, so those attributes are missing from the state.

```
                        "attributes": {
                            "cidr_block": "10.0.0.0/16",
                            "compartment_id": "<REDACTED>",
                            "default_dhcp_options_id": "<REDACTED>",
                            "default_route_table_id": "<REDACTED>",
                            "default_security_list_id": "<REDACTED>",
                            "defined_tags.%": "0",
                            "display_name": "vcn1",
                            "freeform_tags.%": "0",
                            "id": "<REDACTED>",
                            "state": "AVAILABLE",
                            "time_created": "2019-02-04 22:11:54.453 +0000 UTC"
                        },
```

### Actual Behavior

Running apply in v0.12 will result in empty strings being set on attributes where the provider doesn't call `ResourceData.Set`.

The state file looks like this for those values. See `dns_label` and `vcn_domain_name` below.
```
          "attributes": {
            "cidr_block": "10.0.0.0/16",
            "compartment_id": "<REDACTED>",
            "default_dhcp_options_id": "<REDACTED>",
            "default_route_table_id": "<REDACTED>",
            "default_security_list_id": "<REDACTED>",
            "defined_tags": null,
            "display_name": "vcn1",
            "dns_label": "",
            "freeform_tags": {},
            "id": "<REDACTED>",
            "state": "AVAILABLE",
            "time_created": "2019-02-04 22:04:57.771 +0000 UTC",
            "timeouts": {
              "create": null,
              "delete": null,
              "update": null
            },
            "vcn_domain_name": ""
          } 
```

Furthermore, the presence of empty string falsely implies that this is the state of the resource on the service. In reality, the service does not return any values for those attributes and so the attributes should technically be undefined in state.

### Steps to Reproduce

`terraform apply`

### Additional Context

We also have OCI provider tests that cover this scenario. (For example, see https://github.com/terraform-providers/terraform-provider-oci/blob/71a9211b95ae8a4ae4a0ebcd55c08f9f4b823181/oci/core_vcn_resource_test.go#L49 )

The tests validate that the missing attributes are also missing from the state file. This test is passing with the v0.11 plugin dependencies, but is failing with the v0.12 plugin dependencies due to the presence of empty values in state.

**Comment by jbardin** [comment]
Hi @alexng-canuck,

Have you tested this against master? That alpha release is quite out of date by now.

**Comment by jbardin** [comment]
This particular behavior should not happen with master, so I'm closing this for now. Feel free to re-open this if the issue persists.
