### ISSUE TITLE
Outputting null_data_source output as  plain maps instead of array of maps

### ISSUE THREAD

**Issue by jkkathi1** [hashicorp/terraform#20225]
### Terraform Version

```
Terraform v0.11.11
+ provider.null v2.0.0
...
```

### Terraform Configuration Files

```hcl
variable "vpc1" { type = "list"
  default = [
      "name1:ip1:az1:dedicated",
      "name2:ip2:az2:dedicated"
  ]
}

variable vpc2  { type = "list"
default = [
  "foo:10.1:east:yes",
  "bar:10.2:west:no"
]
}

data "null_data_source" "values" {
count = "${length(var.vpc1)}"
inputs =  "${
      map (
        "${element(split(":", var.vpc1[count.index]),0)}","${element(split(":", var.vpc2[count.index]),0)}"
        )
  }"
}

output  "mappings" {
    value = "${data.null_data_source.values.*.outputs}"
}
```

### Expected Behavior

```
Outputs:

mappings = [
           name1 = foo
           name2 = bar
  ]
```

### Actual Behavior

```
Outputs:

mappings = [
    {
        name1 = foo
    },
    {
        name2 = bar
    }
]
```

**Comment by jkkathi1** [comment]
Terraform version 
Terraform v0.11.11
+ provider.null v2.0.0


Expected Behavior
Outputs:

mappings = [
        name1 = foo
        name2 = bar
]

Actual Behavior

Outputs:

mappings = [
    {
        name1 = foo
    },
    {
        name2 = bar
    }
]


Why is terraform outputting the map as  array when used within null_data_source

**Comment by jkkathi1** [comment]
I am trying to use this principle in capturing the vpc ids from aws_vpc.default.*.id  and assign it to the respective vpc name  in that order .  But it errors out when trying out since triggers values are not populated  before the vpc is created .                                                                                                                                                                                                                                     * module.vpcs.local.vpc_mappings: local.vpc_mappings: Resource 'null_resource.vpc_mappings' does not have attribute 'triggers.vpc_name' for variable 'null_resource.vpc_mappings.*.triggers.vpc_name'

**Comment by gpanula** [comment]
I think you have may moved past the scope of this issue and into more of a general help with terraform territory.  I would encourage you to checkout the [Terraform Community page](https://www.terraform.io/docs/extend/community/index.html) to find some general help with using terraform.

The error

```
lookup: argument 1 should be type map, got type string .
```

is complaining you passed a string(not list) to the lookup.  Maybe the wrong variable?


Curly brackets {} signify a map
Square brackets signify a list

```
vpc_mashup_field1 = {
name1 = foo
name2 = bar
}
```

is a map.   lookup(local.vpc_mashup_field1, "name1") should return "foo"

```
vpc_mashup_field1 = [
name1 = foo
name2 = bar
]
```

would be a list. (broken in the format above) correct list format would be

```
vpc_mashup_field1 = [
"name1 = foo",
"name2 = bar"
]
````

element(local.vpc_mashup_field1, 0) would return "name1 = foo"


You can assign the vpc a name when you create it by setting the tags on it

```
resource "aws_vpc" "main" {
  cidr_block       = "10.0.0.0/16"

  tags = {
    Name = "main"
  }
}
```

You could then use the data type of [aws_vpc](https://www.terraform.io/docs/providers/aws/d/vpc.html) to retrieve the name of the vpc by looking at the tags

Something like this

```
data "aws_vpc" "selected" {
  id = "12345abc"
}

locals {
 vpc_tags = "${data.aws_vpc.selected.tags}"
vpc_name = "${lookup(local.vpc_tags, "Name")}"
}

output "vpc_name" {
 value = "${local.vpc_name}"
}
```

completely untested code... bug squashing is left as an exercise for the reader :)

**Comment by programingnotes** [comment]
@programingnotes

**Comment by jbardin** [comment]
Hi @jkkathi1,

It appears you have a handle on the original issue here, so I'm going to close this out.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
