### ISSUE TITLE
Error creating S3 bucket: InvalidArgument

### ISSUE THREAD

**Issue by sujith-siva** [hashicorp/terraform#20228]
Hi All,

I am getting an error while running the attached terraform code,the plan runs successfully but apply failing.

Error: Error applying plan:

1 error(s) occurred:

* aws_s3_bucket.backup: 1 error(s) occurred:
* aws_s3_bucket.backup: Error creating S3 bucket: InvalidArgument:
  status code: 400, request id: E6F2496DA5632908043, host id: 1xwu8Cpr8WdYTGTYUyzYNWRp8YlpsfANLZnWIOcvzPBuG+a6LFI4MuytKzMSt2QnICt1ThcIh8=

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
[Terraform-Issues.txt](https://github.com/hashicorp/terraform/files/2831489/Terraform-Issues.txt)

**Comment by abiydv** [comment]
Can you give this a shot? There was a typo in `acl = private` line of the code you attached, and also the policy block appeared to be having issues with indentation.

```
resource "aws_s3_bucket" "backup" {
   bucket = "backup.test.com" 
   acl	  = "private"
   server_side_encryption_configuration {
   	rule {
   		apply_server_side_encryption_by_default {
   			sse_algorithm = "AES256"
   		}
   	}
  }
 }

resource "aws_s3_bucket_policy" "backup_test_policy" {
  bucket = "${aws_s3_bucket.backup.id}"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "Backup-Internal-Access-Policy",
  "Statement": [
    {
      "Sid": "IPAllow",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::backup.test.com/*",
      "Condition": {
         "IpAddress": {"aws:SourceIp": "10.x.x.x/21"}
      }
    }
  ]
}
POLICY
}

resource "aws_s3_bucket_public_access_block" "public_access_block" {
	bucket = "${aws_s3_bucket.backup.id}"
	block_public_acls = true
	ignore_public_acls = true
	block_public_policy = true
	restrict_public_buckets = true
}
```

**Comment by sujith-siva** [comment]
yeah that was a spelling mistake and it worked. thanks for that. But that was my initial stumbling block now I am trying to incorporate a few more features for restricting the s3 bucket access and I am getting an error like this .

my plan went well but when I try to apply the plan it is failing .

Error: Error applying plan:

1 error(s) occurred:

* aws_s3_bucket.ind-backup: 1 error(s) occurred:

* aws_s3_bucket.ind-backup: Error putting S3 policy: MalformedPolicy: Invalid principal in policy
	status code: 400, request id: 8765644D6680, host id: du23fgrkj8ssdxFVVeeChmLqkjWSur767sh8KSjhRTwo=

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
[s3-restr-bucket.txt](https://github.com/hashicorp/terraform/files/2837185/s3-restr-bucket.txt)

**Comment by sujith-siva** [comment]
I don't know why the policy saying invalid principal?

what I am trying to achieve is use aes256 as encryption,Bucket policy should have all those policies incorporated so that right users and roles can access the s3 bucket and only from certain subnet.

thanks
