### ISSUE TITLE
Provider alias does not work properly inside module v(0.5.3)

### ISSUE THREAD

**Issue by i0n** [hashicorp/terraform#2023]
Hey all. I have only tested this with the google provider
Terraform v0.5.3-dev (0d575b75c872aa887071aa46a0dc44dcbda97888)
I also tested with 0.5.1 with the same behaviour.
main.tf
```
module "test" {
  source = "./module"
}
```

./module/main.tf
```
provider "google" {
  alias = "eu"
  project = "staging"
  account_file = "google.json"
  region = "europe-west1"
}

resource "google_compute_address" "new_ip" {
  provider = "google.eu"
  name = "new_ip"
}
```
terraform plan produces:
```
Errors:

  * 1 error(s) occurred:

* module.test: provider google.eu couldn't be found
```

If I include the provider inside the main.tf file I get the same error.
If I include the provider in both main.tf and ./module/main.tf it works.

**Comment by LeftyBC** [comment]
I'm hitting this bug as well - we've got a route53 account that's managed by a third party, so we need to have a secondary AWS provider, but can't use an aliased provider inside the module.

**Comment by tphummel** [comment]
I can reproduce this in a module using the 0.5.3 release on OSX 10.10.3. It works if I move the aliased provider block and the subsequent resources out of the module (into a `main.tf`).

**Comment by rbowlby** [comment]
Reproduced as well. Makes re-using a module in multiple regions aws regions impossible. :(

**Comment by julianalves** [comment]
Is there a solution for this problem?

**Comment by apparentlymart** [comment]
Hi @julianalves,

The problem as stated here was fixed a couple years ago. If you are seeing a similar problem, please open a new top-level issue with some more information on what you're seeing and we can work on debugging it against the latest version of Terraform.

**Comment by git-vp** [comment]
Hi apparentlymart,

I am seeing the same issue reported by @julianalves.
Our use case: we have to create ARM resources in multiple subscriptions (dev, test, sandpit) using ARM. These ARM resources like VNET are created as reusable modules, which are then referred to in in an environment where that resource is required. Therefore, specific to each subscription we have defined a provider like below:

variable "dev_subscription_id"     {}
provider "azurerm" {
  alias = "dev"
  subscription_id = "${var.dev_subscription_id}"
}

A sample module like VNET is defined as below, where the provider alias is given.
resource "azurerm_virtual_network" "vnet" {
  ....
  provider = "${var.provider}"
  ....
}

This is how the module is referenced:

module "rg" {
  source = "../../../../modules/azure/network/rg"
  ....
  provider = "azurerm.sandpit"
  .....
}

This gives the following error:
* module.vnet.azurerm_virtual_network.vnet: provider ${var.provider} couldn't be found

As mentioned in the above thread, if I include provider in each module then it doesn't give this error. Hope to have this fixed soon as it is really nasty to give provider block in each module.

Many thanks,
Venu
