### ISSUE TITLE
Crash in `aws_instance` data source when passing a list instead of an id as the `instance_id`

### ISSUE THREAD

**Issue by Maikon** [hashicorp/terraform#20231]
Hi everyone 👋 

Sharing this not necessarily because it caused us a big issue and is a must fix but more so in case there is room to improve the error message shown. The below fails when passing a list instead of a string to `instance_id`

### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.57.0
+ provider.external v1.0.0
```

### Terraform Configuration Files

```hcl
data "aws_instance" "beanstalk-ec2-instance" {
  instance_id = "${aws_elastic_beanstalk_environment.my-beanstalk.instances}"
}

output "security-group" {
  value = "${data.aws_instance.beanstalk-ec2-instance.security_groups}"
}

```

### Crash Output

https://gist.github.com/Maikon/7f7991f180d0e42a2e5a934963f80416

The key line I assume is this:
```
2019-02-05T11:27:53.519Z [DEBUG] plugin.terraform-provider-aws_v1.57.0_x4: panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
```

### Expected Behavior

Perhaps a more meaningful error? Maybe show line number and/or hints of what may have gone wrong?

### Actual Behavior

Crashes generating a quite large `crash.log`

**Comment by apparentlymart** [comment]
Hi @Maikon,

I believe this bug is already fixed in master in preparation for the forthcoming v0.12.0 release, so I'm going to label this as part of that milestone to remind us to verify it.

**Comment by jbardin** [comment]
Verified that this is correctly validated in 0.12.

```
Error: Incorrect attribute value type

  on main.tf line 13, in data "aws_instance" "beanstalk-ec2-instance":
  13:   instance_id = aws_elastic_beanstalk_environment.my-beanstalk.instances

Inappropriate value for attribute "instance_id": string required.
```

Thanks @Maikon!

**Comment by Maikon** [comment]
Awesome, thank you @jbardin!
