### ISSUE TITLE
missing schema for provider "terraform" data source terraform_remote_state

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#20245]
### Terraform Version

v0.12 (1f4d2f4c5008cbf4e2da61b65f1cb98183bc4884)

### Terraform Configuration Files

`main.tf`
```hcl
terraform {
  backend "local" {
    path = "message.tfstate"
  }
}

output "something" {
  value = "hello world"
}
```

`/referencing/main.tf`
```hcl
data "terraform_remote_state" "vpc" {
  backend = "local"
  config = {
    path = "../message.tfstate"
  }
}

output "message" {
  value = "${data.terraform_remote_state.vpc.outputs.something}"
}
```

### Expected Behavior

```
$ terraform apply && terraform show
```
to show the outputs pulled from the backend.

### Actual Behavior
```
$ terraform apply && terraform show
```
```
# data.terraform_remote_state.vpc:
# missing schema for provider "terraform" data source terraform_remote_state


Outputs:

message = "hello world"
```

### Steps to Reproduce

```
$ terraform init
$ terraform apply
$ terraform show
```

---

Thanks to @surminus for discovering this during the Terraform HackDay.

**Comment by radeksimko** [comment]
Just noting that I just saw this error in `http` provider, so this at least rules out this would be related to the `terraform` provider which is a special snowflake in the 0.12 world.

```hcl
data "http" "ipinfo" {
  url = "http://ipinfo.io/ip"
}
```

```
# data.http.ipinfo:
# missing schema for provider "http" data source http
```

### Terraform version

32f0afeffa32a86816caadf456363034869898a5

### HTTP provider version

https://github.com/terraform-providers/terraform-provider-http/tree/radeksimko/v0.12

**Comment by apparentlymart** [comment]
@radeksimko am I understanding correctly that this error is coming from `terraform show` in particular? You showed a few different commands in the writeup here so I just want to make sure; the output format there is unusual so I'm not able to quickly recognize where it's coming from.

**Comment by radeksimko** [comment]
Ah, yes - sorry for not making it clear. It's output from `terraform show`.

**Comment by apparentlymart** [comment]
Great, thanks! I'm going to relabel this as a `cli` bug then.
