### ISSUE TITLE
Missing context for blocks in locals

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#20248]
### Terraform Version

v0.12.0-dev (1f4d2f4c5008cbf4e2da61b65f1cb98183bc4884)

### Terraform Configuration Files

```hcl
locals {
  something {
    key = "value"
  }
}
```

### Expected Behavior

Full error with code snippet (filename, path, line number etc.)

### Actual Behavior

```
$ terraform validate
```
```
Error: Unexpected something block

Blocks are not allowed here.
```

### Steps to Reproduce

`terraform validate`

----

Thanks @Amygos for finding this during the Terraform HackDay.

**Comment by Narven** [comment]
Is this supposed to have been fixed?

I still have this problem after 8 months. Is it going to be fixed? Or is there any alternative to this?

Thanks

**Comment by Narven** [comment]
```bash
λ  evbook-ops/terraform/bla master ✗ terraform version
Terraform v0.12.7                                                                                                              /0.0s
λ  evbook-ops/terraform/bla master ✗ cat main.tf

locals {
  some_env {
    default    = "yes"
    staging    = "no"
    production = "maybe"
  }
}
λ  evbook-ops/terraform/bla master ✗ terraform validate

Error: Unexpected "some_env" block

  on main.tf line 4, in locals:
   4:   some_env {

Blocks are not allowed here.
```
