### ISSUE TITLE
provider/aws: Set the tags as early as possible

### ISSUE THREAD

**Issue by freeman** [hashicorp/terraform#2025]
We use IAM policies based on tags to restrict API operations.

Currently this make terraform unable to create completely a `aws_instance` because it tries to call [`ModifyInstanceAttribute`](https://github.com/hashicorp/terraform/blob/31258e06c65d85eeee2cd86131bb4cecaeba48cc/builtin/providers/aws/resource_aws_instance.go#L686) (which is one of the API operations we restrict) before associating the tags to the instance (which happens at the end of the `resourceAwsInstanceUpdate` function).

Do you see any issue with moving [this code block](https://github.com/hashicorp/terraform/blob/31258e06c65d85eeee2cd86131bb4cecaeba48cc/builtin/providers/aws/resource_aws_instance.go#L728-L732) to the beginning of the function ?

**Comment by catsby** [comment]
@freeman shouldn't be an issue, I opened #2026

**Comment by freeman** [comment]
@catsby Thanks, looks great. Did not manage to test it locally by building terraform. I'll wait for a release.
