### ISSUE TITLE
Variable interpolation in version 0.11.10.1

### ISSUE THREAD

**Issue by dsingh-uh** [hashicorp/terraform#20250]
I am using terraform container version 0.11.10.1, aws provider version 1.51.0. I have some variables in my user data as 
```
docker_image="some image"
docker pull $$docker_image
```
The double dollar syntax for interpolation was working in version 0.11.7.6 but not in the latest version. Has there been a change on how terraform is going to interpolate bash variables? Cause now terraform interprets $$docker_image as <process_id>$ docker_image

**Comment by apparentlymart** [comment]
Hi @dsingh-uh,

I think what you are seeing here is terraform-providers/terraform-provider-template#49. Please see that issue for some suggested mitigations.

**Comment by dsingh-uh** [comment]
@apparentlymart Thank you.
