### ISSUE TITLE
Azure VNet Peering Allow Gateway Transit / Use Remote Gateway order of operation error

### ISSUE THREAD

**Issue by rjbartson** [hashicorp/terraform#20298]
When applying Vnet peering  --> allow_gateway_transit     = "true" and the alternate peering --> use_remote_gateways       = "true" 
Terraform correctly applied 4 of the 6 settings but swapped the order of operation with 2. 
error - **Peering-to-Gateway cannot have UseRemoteGateways flag set to true, because corresponding remote peering has AllowGatewayTransit flag set to false.** 

Ran Terraform apply again and it correctly applied the settings without modification to the code.

**Comment by bflad** [comment]
This was accidentally migrated to the AWS provider. It looks like it should go to one of the Azure providers:
* https://github.com/terraform-providers/terraform-provider-azuread
* https://github.com/terraform-providers/terraform-provider-azurerm
* https://github.com/terraform-providers/terraform-provider-azurestack

**Comment by apparentlymart** [comment]
Oh, whoops! Autocomplete failed me this time. Thanks for letting me know, @bflad.
