### ISSUE TITLE
Output not refreshed if output template changed with remote state

### ISSUE THREAD

**Issue by UncleTawnos** [hashicorp/terraform#20306]
### Terraform Version
```
Terraform v0.11.11
```

### Expected Behavior
While changing output template and running terraform plan, terraform apply, terraform output, I expect to have output generated using changed template.

### Actual Behavior
I got output printed out from remote state (not computed locally) as there was no resource change (only a typo in template fixed - a config file for ansible provisioning module), the output was never refreshed unless I've changed a remote resource

### Steps to Reproduce
1. create any template file with data "template_file" "mytemplate"
2. create output object with value `data.template_file.mytemplate.rendered`
3. run terraform init, plan, apply
4. change anything in template body
5. run again point 3
6. your output does not change while it should
7. add anything to data object (like extra variable)
8. run everything again - now your output changed

### Additional Context
Terraform plan SHOULD validate if template file changed and store md5 hash in the state file/remote state

**Comment by jbardin** [comment]
Hi @UncleTawnos,

Data should be evaluated now, even when they are the only change, so I think what you're seeing here should be fixed in master.

Data sources however are still not picked up in a plan when there are no managed changes, so I'm not sure if that is related to what you're seeing.

**Comment by jbardin** [comment]
I've verified the above steps with both inline and file inputs.
Closing this as fixed on master.
