### ISSUE TITLE
Sublime Text 3 syntax highlighting for .tf files

### ISSUE THREAD

**Issue by alexlouden** [hashicorp/terraform#2030]
Hey guys,

I've made a quick start on Sublime Text 3 syntax highlighting for Terraform syntax - see https://github.com/alexlouden/Terraform.tmLanguage

![screenshot](https://raw.githubusercontent.com/alexlouden/Terraform.tmLanguage/master/screenshot.png)

This is the first time I've played with tmLanguage files so it's super basic for now. I'd love a hand from someone more familiar - pull requests very welcome.

Cheers,
Alex

**Comment by mitchellh** [comment]
Thanks! If you want to submit this to this repo, we'd be happy to put it in the `contrib` folder. Thanks!

**Comment by radeksimko** [comment]
It's great to see this coming! It was on my list of things to do right next to Github syntax highlighting, glad to see you jumped in!

@mitchellh I'm not sure if `contrib` is the right place, considering most Sublime Text packages exist as separate repos.

@alexlouden I can clearly [see](https://github.com/alexlouden/Terraform.tmLanguage/blob/master/Terraform.tmLanguage#L74) that it's currently Terraform specific. Is there particular disadvantage of making it generic = HCL, so people can use it for highlighting consul configs etc.?  https://github.com/hashicorp/hcl

**Comment by radeksimko** [comment]
> is there particular disadvantage of making it generic = HCL, so people can use it for highlighting consul configs etc.?

Answering my own question: Probably isn't, since we'd likely not be able to see the difference between resource parameters & provisioner etc. 

My note about separate repository remains valid though.

**Comment by mitchellh** [comment]
Got it, didn't know. Well then we'll keep it there. :)

**Comment by alexlouden** [comment]
@radeksimko No reason for it to be Terraform specific, I just haven't used consul and didn't know it used the same config. I'm happy to transfer the repo or add you as contributors - I probably won't have the time to do much more with it.

**Comment by euforia** [comment]
@alexlouden: Thx for a starting point.

I'm using terraform, consul and nomad and have been using @alexlouden repo with a few changes to make it more geared towards HCL as a whole.  The code is available here - https://github.com/euforia/HCL.tmLanguage but was wondering
if there was an "official" highlighter I should be looking at?  Didn't come across anything in my initial searches.

**Comment by radeksimko** [comment]
> if there was an "official" highlighter I should be looking at? Didn't come across anything in my initial searches.

AFAIK there isn't any "official" one if by official you mean "maintained by Hashicorp", but I'm guessing @alexlouden would be happy for you to send PRs with changes from your fork and eventually turn https://github.com/alexlouden/Terraform.tmLanguage into `alexlouden/HCL.tmLanguage` - feel free to correct me if I'm wrong.

**Comment by alexlouden** [comment]
Hey @radeksimko / @euforia - very happy to accept any pull requests and open to changing the name as long as the repo stays easy to find!

**Comment by igoratencompass** [comment]
This is awesome, thanks!
