### ISSUE TITLE
Better handling of RDS snapshot-restored instances

### ISSUE THREAD

**Issue by nomeelnoj** [hashicorp/terraform#20318]
### Current Terraform Version

```
Terraform v0.11.11
```

### Use-cases

If I want to update a password or disk space, or something that does not require the database to be rebuilt, I have to find the snapshot identifier from the instance that is there and feed it back into terraform.  Would like to not have to track this down and have to temporarily modify the code, as it causes nightmares for automation.

### Attempted Solutions

Tried to use conditionals for this but snapshot_identifier is not an available attribute for an output or an rds data source.
### Proposal

When restoring an RDS instance from a snapshot, you can feed in the `snapshot_identifier` value.  However, on subsequent runs, if a different snapshot identifier is fed in, it will try to recreate the database with that new snapshot identifier.  So, if you want to make other changes (update passwords, disk space, etc.) you need to first find the current snapshot identifier of that database and feed it back into terraform so that it will not recreate the database from a different snapshot.  It would be great if there was a way to say "fill the `snapshot_identifier` value with the current value from this database unless I explicitly feed a snapshot_identifier variable in at runtime (using -var, e.g.).

**Comment by mildwonkey** [comment]
I'm going to move this to the terraform-provider-aws repository, as it sounds like the request is for an aws-specific data source.
