### ISSUE TITLE
release files not named consistently/correctly

### ISSUE THREAD

**Issue by DonThorntonJr** [hashicorp/terraform#20321]
my automated process for updating release files from releases.hashicorp.com is failing on these folders:

under: https://releases.hashicorp.com/terraform/0.12.0-alpha3/
terraform_0.12.0-alpha3_terraform_0.12.0-alpha3_<>.zip
^^^^^^^^^^^^^^^^^^^^^^^^^ redundant
under: https://releases.hashicorp.com/terraform/0.12.0-alpha4/
terraform_0.12.0-alpha4_terraform_0.12.0-alpha4_<>.zip
^^^^^^^^^^^^^^^^^^^^^^^^^  redundant

under: https://releases.hashicorp.com/terraform/0.12.0-alpha2/
there is no sha256sum for terraform_0.12.0-alpha2_windows_amd64.zip in terraform_0.12.0-alpha2_SHA256SUMS

**Comment by apparentlymart** [comment]
Hi @DonThorntonJr,

This was also reported in #19588. Please see my reply there for more information.
