### ISSUE TITLE
remote-exec shell files prepended with sh shebang, even if there is already bash shebang

### ISSUE THREAD

**Issue by jrslv** [hashicorp/terraform#2033]
We're using remote-exec provisioner with a bunch of .sh files. They all start with bash shebang, but sh shebang is prepended in the /tmp/terraform_*.sh files on the created machines. This only happens when we're using 0.5.* versions of Terraform. It results in the scripts failing to execute.

We're facing the issue in this repository:
https://github.com/ContainerSolutions/terraform-mesos

**Comment by phinze** [comment]
Thanks @jrslv for the report and @svanharmelen - this fix will be included with 0.5.3
