### ISSUE TITLE
Terraform 0.12-alpha4 crashes when changing the peer_owner_id of an aws_vpc_peering_connection

### ISSUE THREAD

**Issue by kuteninja** [hashicorp/terraform#20331]
Using terraform 0.12-alpha4, when you create an aws_vpc_peering_connection, and then edit the .tf file to change the `peer_owner_id`, terraform crashes when doing any action (plan/apply/destroy).

As a workaround I removed the peering from the .tfstate file, removed the peering and route-table  manually on the amazon console, and then terraform was able to re-create the peering and route with the new owner.

### Terraform Version
```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

### Terraform Configuration Files
```hcl
# Create a peering connection to request side 
 resource "aws_vpc_peering_connection" "peer_account" {
   provider      = "aws"
   vpc_id        = aws_vpc.vpc.id
   peer_vpc_id   = var.vpc.peering.vpc_id 
   peer_owner_id = var.vpc.peering.owner_id
   peer_region   = var.region 

   auto_accept   = false 
   tags = {
    Side = "Requester"
    Name = "from_${var.vpc.name}_to_${var.vpc.peering.name_account}_account"
  } 
}

# Routes entry for Requester
resource "aws_route" "route_tables" {
  #count                     = 1 
  route_table_id            = aws_vpc.vpc.default_route_table_id
  destination_cidr_block    = var.vpc.peering.cidr_block
  vpc_peering_connection_id = aws_vpc_peering_connection.peer_account.id
  depends_on                = ["aws_vpc_peering_connection.peer_account"]
}
```

### Crash Output
[crash.log.gz](https://github.com/hashicorp/terraform/files/2862159/crash.log.gz)

### Expected Behavior
The expected behaviour was recreation of the peering with the new peer_owner_id as well as it's dependencies (in my case, just the route_table)

### Actual Behavior
Terraform crashes on plan/apply/destroy

### Steps to Reproduce
```
# Using the tf file included, use variables to set the peer_owner_id to any account
terraform apply
# Edit the peer_owner_id variable to any other id, and apply changes
terraform apply
# Crashes right after planning what to do
```

**Comment by jbardin** [comment]
Hi @kuteninja 

Thanks for the crash report. This is fixed in master. The alpha4 release is quite old now; if you are testing providers is recommended to use master until the beta releases are out.
