### ISSUE TITLE
aws_lb_target_group requires port, vpc_id and protocol when target_type is lambda

### ISSUE THREAD

**Issue by tlipatov** [hashicorp/terraform#20332]
### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.47.0
...
```

### Terraform Configuration Files

```hcl
resource "aws_lb_target_group" "test" {
  target_type = "lambda"
}
...
```

### Expected Behavior

Resource should be created

### Actual Behavior

Error: aws_lb_target_group.test: "port": required field is not set
Error: aws_lb_target_group.test: "protocol": required field is not set
Error: aws_lb_target_group.test: "vpc_id": required field is not set

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Documentation states that these are not required when target_type = "lambda"
AWS API also does not allow these to be set when target_type = "lambda"

ValidationError: Port cannot be specified for target groups with target type 'lambda'

**Comment by burtsdenis** [comment]
@tlipatov, Hi there!

Yesterday I faced the same issue.
Do you have a workaround for this?
According to official documentation this fields is optional.

I understand, that I can just add this fields, but it seems to be not normal behavior :)

**Comment by daniilyar** [comment]
@burtsdenis, we also experience this issue, but don't have a fix yet. As the issue is related to the AWS Terraform provider, not the core Terraform, I have opened an appropriate ticket at https://github.com/terraform-providers/terraform-provider-aws/issues/7936. Let's continue the discussion there please

**Comment by tlipatov** [comment]
Sorry for the late response.. my solution was just to make sure TF pulls down the latest AWS provider.
I'm now on + provider.aws v1.60.0

and make sure to pin it in my plans
```
provider "aws" {
  version = "~> v1.60.0" # Pin major version.
  region  = "us-east-1"
```
