### ISSUE TITLE
dms-vpc-role  not created before aws_dms_replication_instance

### ISSUE THREAD

**Issue by neovasili** [hashicorp/terraform#20346]
### Terraform Version

```
Terraform v0.11.11
```

### Terraform Configuration Files

```hcl
resource "aws_dms_replication_instance" "dynamodb-import-instance" {
	engine_version 			= "3.1.2"
	multi_az 			= "false"
	publicly_accessible 		= "false"
	replication_instance_class 	= "${ var.dms_replication_instance_type }"
	replication_instance_id 	= "${ var.replication_instance_id }"

	tags {
		description = "test"
	}
}

resource "aws_iam_role" "dms-vpc-role" {
  name = "dms-vpc-role"

  assume_role_policy = "${ data.aws_iam_policy_document.dms-vpc-role-policy.json }"
}

data "aws_iam_policy_document" "dms-vpc-role-policy" {
  statement {
    actions = [ "sts:AssumeRole" ]

    principals {
      type        = "Service"
      identifiers = [ "dms.amazonaws.com" ]
    }
  }
}
```

### Crash Output

Error: Error applying plan:

1 error(s) occurred:

* aws_dms_replication_instance.dynamodb-import-instance: 1 error(s) occurred:

* aws_dms_replication_instance.dynamodb-import-instance: error creating DMS Replication Instance: AccessDeniedFault: The IAM Role arn:aws:iam::xxxxxxxx:role/dms-vpc-role is not configured properly.
        status code: 400, request id: xxxxxxxxx

### Expected Behavior

Apply complete! Resources: X added, 0 changed, 0 destroyed.

### Actual Behavior

Fails to apply because iam role is created after dms replication instance

### Steps to Reproduce

terraform apply

### Additional context

If you perform a secondary terraform apply all changes are applied perfectly

**Comment by mildwonkey** [comment]
Hi @neovasili ,
I'm sorry you're experiencing this unexpected behavior. 

I see that there isn't an explicit dependency between the iam role and dms replication instance in your terraform configuration files, so terraform doesn't know that one needs to be created before the other.

To make this dependency explicit, add a `depends_on` statement to the dms replication instance:

```hcl
resource "aws_dms_replication_instance" "dynamodb-import-instance" {
	...
        depends_on = ["aws_iam_role.dms-vpc-role"]
}
```

I hope this helps!

**Comment by kurtmaile** [comment]
I actually experienced this too now with v11.11- that doesnt fix this unfortunately, Ive definitely go the depends_on there.  Basically if I run apply again straight after the initial fail with nothing change it works so seems there is a timing issue with the provider and the creation of the SG.

**Comment by mildwonkey** [comment]
@kurtmaile that's good to know, thank you!

I am going to move this issue to the [terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws) repository; IAM especially is knows for being eventually consistent so perhaps the provider needs to do a better job of making sure the resource is fully created (I could be entirely wrong on that though!).
