### ISSUE TITLE
Terraform crashes with terraform-provider-aws_v1.59.0

### ISSUE THREAD

**Issue by MarkAyliffe** [hashicorp/terraform#20355]
As title

### Crash Output

[crash.log](https://github.com/hashicorp/terraform/files/2868670/crash.log)

### Expected Behavior
It should work without crashing like it has for the last couple of months!
### Actual Behavior
Terraform crashes if I try terraform plan or terraform apply.

**Comment by apparentlymart** [comment]
Hi @MarkAyliffe,

This crash seems to be coming from the AWS provider code itself, so I'm going to have our bot move this issue over to the AWS provider repository.
