### ISSUE TITLE
Documentation feels incomplete for 'encrypt' configuration variable in s3 backend

### ISSUE THREAD

**Issue by mlcooper** [hashicorp/terraform#20369]
The documentation for [this](https://www.terraform.io/docs/backends/types/s3.html#encrypt) configuration variable in the s3 backend feels incomplete.  

Generally what I'd like to document is the answer to this:
- If `encrypt` is set to `true` but `kms_key_id` is omitted, then what does this setting provide?

Perhaps it isn't even directly related to having `kms_key_id` configured with the ARN of a key?  Is it a separate config entirely?

If I use an s3 bucket that on the AWS side has `SSE-S3` default encryption enabled, but the `encrypt` configuration variable is set to omitted, then the objects in the s3 bucket will still get encrypted by s3 since the default encryption configuration on the bucket is enabled.  Additionally, it appears that if `encrypt` is not configured and the s3 bucket has default configuration enabled for `SSE-S3`, Terraform will still write its remote state files to it successfully.

Setting `encrypt` to `true` does not enable the default encryption configuration for an s3 bucket that doesn't already have default encryption configured on the AWS side.

**Comment by mildwonkey** [comment]
The documentation has been updated quite a bit to expand on all these points (https://www.terraform.io/docs/backends/types/s3.html), so I am going to close this issue. If you still have questions or concerns, please open a new issue. Thanks!
