### ISSUE TITLE
v0.12: Multiline for each iteration fails on maps

### ISSUE THREAD

**Issue by lsegal** [hashicorp/terraform#20370]
The following Terraform 0.12 map iteration fails when multiline syntax is used (as per the example in [HashiCorp's Terraform 0.12 Preview blog post](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each)):

```hcl
output "example" {
  value = {
    for x in ["A", "B", "C"]:
    x => true
  }
}
```

Output:

```
Error: Missing key/value separator

  on main.tf line 3, in output "example":
   2:   value = {
   3:     for x in ["A", "B", "C"]:

Expected an equals sign ("=") to mark the beginning of the attribute value.
```

Placing the iteration on a single line works:

```hcl
output "example" {
  value = {for x in ["A", "B", "C"]:  x => true}
}
```

Output:

```hcl
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

example = {
  "A" = true
  "B" = true
  "C" = true
}
```

I would expect that multiline syntax works in the same way as it does on lists.

### Terraform Version

```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

**Comment by jbardin** [comment]
Thanks for reporting the issue. We can track this over in #20230.
