### ISSUE TITLE
v0.12: Cannot create empty maps with map() function

### ISSUE THREAD

**Issue by lsegal** [hashicorp/terraform#20372]
Terraform 0.12 does not seem to support creating empty maps using the `map()` function syntax. I would expect an equivalent method to the map literal `{}` that allows me to create an empty map with this function.

### Terraform Version

```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

### Terraform Configuration Files

```hcl
locals {
  # this works
  empty_map_literal = {}

  # I expect this to work too
  empty_map_fn = map()
}
```

### Expected Behavior

I expect that an empty map can be defined using the `map()` function.

### Actual Behavior

Terraform spits out the following error:

```
Error: Error in function call

  on main.tf line 6, in locals:
   6:   empty_map_fn = map()

Call to function "map" failed: map requires an even number of two or more
arguments, got 0.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by jbardin** [comment]
Hi @lsegal,

Thanks for reporting the issue. The `map()` function is deprecated for 0.12, and will be eventually removed. The documentation will be updated to reflect this once 0.12 is released:

```
~> **This function is deprecated.** From Terraform v0.12, the Terraform
language has built-in syntax for creating maps using the `{` and `}`
delimiters. Use the built-in syntax instead. The `map` function will be
removed in a future version of Terraform.

`map` takes an even number of arguments and returns a map whose elements
are constructed from consecutive pairs of arguments.
```
