### ISSUE TITLE
v0.12: Conditional operator fails on empty map result value

### ISSUE THREAD

**Issue by lsegal** [hashicorp/terraform#20371]
Terraform 0.12 will always pick the "true" branch of a conditional operator when literal map (`{ ... }`) syntax is used on both the true/false result values, regardless of where the literals were defined. Using `map()` does not cause the same failure.

### Terraform Configuration

```hcl
locals {
  yes = { Result = true }
}

output "example" {
  value = false ? {} : local.yes
}
```

### Actual Output

```hcl
Outputs:

example = {}
```

### Expected Output

```hcl
Outputs:                
                        
example = {             
  "Result" = true       
}                       
```

### Workaround

Using a `map()` on either branch throws off the parser and allows the conditional to function correctly. The following produces the correct `Result = true` output result:

```hcl
output "example" {
  value = false ? {} : map("Result", true)
}
```

The same goes for using a `map()` defined in a variable:

```hcl
locals {
  yes = map("Result", true)
}

output "example" {
  value = false ? {} : local.yes
}
```

Note that you cannot use `map()` on the true branch of the above example due to #20372 (`map()` cannot be used to create an empty map).

### Terraform Version

```
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
```

**Comment by jbardin** [comment]
Hi @lsegal,

Thanks for reporting the issue, this appears to be fixed in master.

The v0.12.0-alpha4 is quite old now, and a lot has changed since its release. If you're interested in testing out 0.12 features I would recommend building from master, or waiting for the the next development release which should be happening in the near future.
