### ISSUE TITLE
Missing [DIR] from "state" command(s)

### ISSUE THREAD

**Issue by walterdolce** [hashicorp/terraform#20382]
The `[DIR]` parameter found in commands like `plan`, `apply`, `destroy` and others is not present in the `state` command (and subcommands).

That breaks the "natural flow" of commands issued by an operator as one would have to 1) `cd` into the folder where the terraform files are, 2) run the command(s), 3) `cd -` back to where she/he was.

In general, I would expect the "core" command arguments to be present across all CLI commands. `[DIR]` would be one of them.

### Terraform Version
v0.11.11

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
Have a consistent UX across all Terraform commands

### Actual Behavior
`[DIR]` cannot be passed to certain commands

### Steps to Reproduce
N/A

### Additional Context
N/A

### References
N/A

**Comment by jbardin** [comment]
Hi @walterdolce,

Thanks for filing the issue. We'll track this over in #17378 for now. The recommended practice is to not use the `[DIR]` argument, because it can cause confusion when there are configuration conflicts since Terraform always relies on the current working.
