### ISSUE TITLE
Terraform doest not interpolate some combination of symbols inside template

### ISSUE THREAD

**Issue by d-averkiev** [hashicorp/terraform#20414]
Hello.
For some reason, Terraform does not interpolate some values of string variable inside a template.
### Terraform Version

```
Terraform v0.11.11
+ provider.local v1.1.0
+ provider.template v2.0.0
```

### Terraform Configuration Files

```hcl
variable foo {}

data "template_file" "test" {
  template = "interpolation-after-dash-$${foo}"
  vars {foo = "${var.foo}"}
}

resource "local_file" "test-file" {
    content     = "${data.template_file.test.rendered}"
    filename = "/tmp/test_file"
}
```
### Steps to Reproduce

1. `terraform init`
2. `terraform apply -var 'foo=108e917'`

### Expected Behavior

The local file `/tmp/test_file` having content "interpolation-after-dash-108e917"

### Actual Behavior

The local file `/tmp/test_file` having content "interpolation-after-dash-"

### Additional Context

When you set terraform `foo` variable to "1som8e9string":
`terraform apply -var 'foo=1som8e9string'`
it will work as expected.

**Comment by mildwonkey** [comment]
Hi @d-averkiev ,

I'm sorry you've come across this behavior. The problem lies in your variable, not the dash. Terraform is processing your first example variable as a number. You need to wrap it in quotes to tell terraform that you want to to treat it like a string:

`terraform apply -var 'foo="108e917"'`

**Comment by d-averkiev** [comment]
Hi @mildwonkey ,
Thank you very much for your answer, I've already added the fix to my CD pipeline.
But, just curious why Terraform so weirdly process exactly this combinations of symbols in command line arguments.
I find out exact condition where interpolation "disappears". The number **before** 'e' should be an integer and should be greater or equal to 1, the number **after** 'e' should be greater or equal to 400, the letter should be 'e' or 'E'. What so special in this combination, why it interpolates properly in any other conditions?

**Comment by mildwonkey** [comment]
I don't have a precise answer for you, but historically terraform has displayed some inconsistent handling of numbers. There's some more context in issue #15626.   
Terraform 0.12 (release date TBD) will have a much more robust type system that addresses (among other things) issues like this one. 

I'm glad you were able to work around this oddity. Cheers!

**Comment by d-averkiev** [comment]
@mildwonkey thanks again. I was trying to find similar issues... now everything clear.
