### ISSUE TITLE
Access resource with counter - Terraform

### ISSUE THREAD

**Issue by russocar** [hashicorp/terraform#20459]
### Terraform Version

```
Terraform v0.11.11
+ provider.openstack v1.15.1
```

### Terraform Configuration Files

```hcl
resource "openstack_networking_port_v2" "port-res" {
  count = 2
  
  name               = "port_${count.index}_terraform"
  network_id         = "${var.network_uuid}"
   fixed_ip {
    "subnet_id"  = "${var.subnet_uuid}"
  }
}


resource "openstack_compute_instance_v2" "testterraform-res" {
  count = 2
  
  name = "test-tmp-terraform-${count.index}"
  availability_zone = "nova"
  image_name        = "${var.image_vm}"
  flavor_id     = "${var.flavor_id}" 
 
  network {
    #port = "${format("$${openstack_networking_port_v2.port-res.*.id}", count.index)}"
	#port = "${openstack_networking_port_v2.port-res.*.id[count.index)]}"
	
	port = "${openstack_networking_port_v2.port-res.*.id[$(count.index)}]}"
  }
}
```

### Expected Behavior

I expect to access the single resource "port" created in the first block.

### Actual Behavior

With using the first line i have this output:

* module.module_VM.openstack_compute_instance_v2.testterraform-res[1]: 1 error(s) occurred:

* openstack_compute_instance_v2.testterraform-res.1: Error trying to get network information from the Network API: Could not find any matching port for port ${openstack_networking_port_v2.port-res.*.id}%!(EXTRA int=1)
* module.module_VM.openstack_compute_instance_v2.testterraform-res[0]: 1 error(s) occurred:

* openstack_compute_instance_v2.testterraform-res.0: Error trying to get network information from the Network API: Could not find any matching port for port ${openstack_networking_port_v2.port-res.*.id}%!(EXTRA int=0)

But I can print each port with output command:

output "port-1" {
  value = "${openstack_networking_port_v2.port-res.1.id}"
}

output "port-0" {
  value = "${openstack_networking_port_v2.port-res.0.id}"
}

Also commented the code for instance creation, in the state file I can see both port:

                "openstack_networking_port_v2.port-res.0": {
                    "type": "openstack_networking_port_v2",
                    "depends_on": [],
                    "primary": {
                        "id": "ba9539ed-9a0a-4c39-bcc0-5b030d77acde",
                        "attributes": {
                            "admin_state_up": "true",
                            "all_fixed_ips.#": "1",
                            "all_fixed_ips.0": "192.168.199.6",
                            "all_security_group_ids.#": "1",
                            "all_security_group_ids.1440133468": "3509063f-5251-4bd2-ad6c-28598b724fd8",
                            "all_tags.#": "0",
                            "allowed_address_pairs.#": "0",
                            "description": "",
                            "device_id": "",
                            "device_owner": "",
                            "extra_dhcp_option.#": "0",
                            "fixed_ip.#": "1",
                            "fixed_ip.0.ip_address": "",
                            "fixed_ip.0.subnet_id": "49fc9631-8f35-4700-9469-0d403e527f3f",
                            "id": "ba9539ed-9a0a-4c39-bcc0-5b030d77acde",
                            "mac_address": "fa:16:3e:70:2f:ff",
                            "name": "port_0_terraform",
                            "network_id": "a0e106bb-a06d-4b91-a52f-8959d414e181",
                            "region": "regionOne",
                            "security_group_ids.#": "1",
                            "security_group_ids.1440133468": "3509063f-5251-4bd2-ad6c-28598b724fd8",
                            "tags.#": "0",
                            "tenant_id": "855811a3f7ad44f2bc9f13d5e72f0ce9"
                        },
                        "meta": {
                            "e2bfb730-ecaa-11e6-8f88-34363bc7c4c0": {
                                "create": 600000000000,
                                "delete": 600000000000
                            }
                        },
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.openstack"
                },
                "openstack_networking_port_v2.port-res.1": {
                    "type": "openstack_networking_port_v2",
                    "depends_on": [],
                    "primary": {
                        "id": "786a0fc9-47a0-4ce8-b269-71a20d621a58",
                        "attributes": {
                            "admin_state_up": "true",
                            "all_fixed_ips.#": "1",
                            "all_fixed_ips.0": "192.168.199.13",
                            "all_security_group_ids.#": "1",
                            "all_security_group_ids.1440133468": "3509063f-5251-4bd2-ad6c-28598b724fd8",
                            "all_tags.#": "0",
                            "allowed_address_pairs.#": "0",
                            "description": "",
                            "device_id": "",
                            "device_owner": "",
                            "extra_dhcp_option.#": "0",
                            "fixed_ip.#": "1",
                            "fixed_ip.0.ip_address": "",
                            "fixed_ip.0.subnet_id": "49fc9631-8f35-4700-9469-0d403e527f3f",
                            "id": "786a0fc9-47a0-4ce8-b269-71a20d621a58",
                            "mac_address": "fa:16:3e:5c:29:32",
                            "name": "port_1_terraform",
                            "network_id": "a0e106bb-a06d-4b91-a52f-8959d414e181",
                            "region": "regionOne",
                            "security_group_ids.#": "1",
                            "security_group_ids.1440133468": "3509063f-5251-4bd2-ad6c-28598b724fd8",
                            "tags.#": "0",
                            "tenant_id": "855811a3f7ad44f2bc9f13d5e72f0ce9"
                        },
                        "meta": {
                            "e2bfb730-ecaa-11e6-8f88-34363bc7c4c0": {
                                "create": 600000000000,
                                "delete": 600000000000
                            }
                        },
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.openstack"
                }

**Comment by russocar** [comment]
I tried all of these:

#port = "${openstack_networking_port_v2.port-res.${count.index}.id}"
#port = "${format("openstack_networking_port_v2.port-res.*.id", count.index)}"
#port = "${format("$${openstack_networking_port_v2.port-res.*.id}", count.index)}"
#port = "${openstack_networking_port_v2.port-res.*.id[count.index)]}"
#port = "${openstack_networking_port_v2.port-res.id[${count.index}]}"

**Comment by apparentlymart** [comment]
Hi @russocar!

The simplest way to express that in Terraform 0.11's language is as follows:

```hcl
    port = "${openstack_networking_port_v2.port-res.*.id[count.index]}"
```

This is close to one of the things you mentioned trying but note that there's no closing parenthesis before the closing bracket in this example.

In the forthcoming Terraform 0.12 release, there will be a more intuitive way to write this:

```hcl
    port = openstack_networking_port_v2.port-res[count.index].id
```

**Comment by russocar** [comment]
Ok Thanks!
I solved also in this way:

port = "${element(openstack_networking_port_v2.port-res.*.id, count.index)}"

in fact "openstack_networking_port_v2.port-res"  is a list of port, so i thought that i could use "element" and take the single value like a pointer in an array.

TY again
