### ISSUE TITLE
count.index*32: unknown count type: 0x0

### ISSUE THREAD

**Issue by Fodoj** [hashicorp/terraform#2046]
` cidr_block = "${concat("10.0.0.", count.index*32, "/2")}"` => `count.index*32: unknown count type: 0x0`

What could be the issue here?

**Comment by phinze** [comment]
Interesting. Looks like a parsing bug. If you space out the math it works!

```
resource "aws_subnet" "foo" {
  count = "3"
  cidr_block = "${concat("10.0.0.", count.index * 32, "/2")}"
}
```

Tagged and we'll get this fixed.

**Comment by mkdev-mentor-1** [comment]
Thanks! If you need help fixing it, just point me into right direction and I will prepare PR in next few days

**Comment by Fodoj** [comment]
Thanks! If you need help fixing it, just point me into right direction and I will prepare PR in next few days

**Comment by Fodoj** [comment]
@phinze another bug:

`#{128 + count.index * 32}` => 4096

I'd like to get it fixed, should I take a look at `github.com/hashicorp/terraform/config/lang/ast`? Which other components are involved?

**Comment by Fodoj** [comment]
@mitchellh  @phinze another bug:

`#{128 + count.index * 32}` => 4096

I'd like to get it fixed, should I take a look at `github.com/hashicorp/terraform/config/lang/ast`? Which other components are involved?

**Comment by mitchellh** [comment]
@Fodoj What is the bug there? Our language doesn't do order of ops on its own (all operator precedence is the same). Wrap things in parens to get the order you want.

**Comment by Fodoj** [comment]
@mitchellh I would normally expect basic math operations to function as they always do. So that kind of operator precedence is totally unexpected and feels unusual at least.

**Comment by mitchellh** [comment]
@Fodoj If you'd like to add precedence that's fine with me, in that case

**Comment by Fodoj** [comment]
@mitchellh sure. Could you point me into required types in codebase? that's mostly related to ast code, right?

**Comment by mitchellh** [comment]
Precedence should just be the parser code, the YACC syntax (.y) in the config/lang directory.
