### ISSUE TITLE
oci_core_subnet issue

### ISSUE THREAD

**Issue by tama1214** [hashicorp/terraform#20477]
**Current Terraform Version**

Terraform v0.11.11
+ provider.oci v3.14.1

**Use-cases**
In specific VCN I want to get a list of all OCI-Subnets (subnets.cidr_block)   and corresponding them  subnets ID (subnets.id).
In accordance with the documentation on the official website 
https://www.terraform.io/docs/providers/oci/d/core_subnets.html
I must use the following script:

```
data "oci_core_subnets" "test_subnets" {
    #Required
    compartment_id = "${var.compartment_id}"
    vcn_id = "${oci_core_vcn.test_vcn.id}"

    #Optional
    display_name = "${var.subnet_display_name}"
    state = "${var.subnet_state}"
}
```
Since there are several networks in VCN, I need to create a loop (count). I used the following code:

```
data "oci_core_subnets" "test_subnets" {
    #Required
    compartment_id = "${oci_identity_compartment.test_compartment.id}"
    vcn_id = "${oci_core_vcn.test_vcn.id}"

    #Optional
    #display_name = "${var.subnet_display_name}"
    #state = "${var.subnet_state}"
}


output "Subnet_cidr_block" {
    count = "${length(var.subnet_availability_domain_ad)}"
    value = "${data.oci_core_subnets.test_subnets.subnets[count.index].cidr_block}"
}
```

 But it gives an error.

```
Error: Error loading C:\== GIT ==\===GITLAB=== Personal.Public_Cloud_Support\Oracle\Joint_Terreform_Project_Oracle_Networking\Joint_Terreform_Project_Oracle\Oracle_004_subnets_data_test.tf: Error reading config for output Subnet_cidr_block: parse error at 1:58: expected "}" but found "."
```
**Please advise what the error is and how should look like a working script to output list of subnets.cidr_block and corresponding them  subnets ID (subnets.id)?**

**Comment by mildwonkey** [comment]
Hi @tama1214 ,
The configuration you provided has a syntax error: the `output` block is missing a closing `}`. Can you confirm if this is in your actual configuration, or just a copy-paste error in the isssue? 


```
output "Subnet_cidr_block" {
    count = "${length(var.subnet_availability_domain_ad)}"
    value = "${data.oci_core_subnets.test_subnets.subnets[count.index].cidr_block}"
}
```

**Comment by tama1214** [comment]
Hi @mildwonkey , one character was lost, Sorry, I fixed the source code

**Comment by mildwonkey** [comment]
Thanks @tama1214  
There are a few problems with this configuration, the first (and biggest) being that outputs do not support count.

I'm not sure if this will get you exactly the output you are looking for, but something like this should get you closer:

```hcl
output "Subnet_cidr_block" {
  value = "${formatlist("%s", data.oci_core_subnets.test_subnets.subnets.*.cidr_block)}"
}
```

I hope this helps!

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by tama1214** [comment]
Thank you for this information @mildwonkey

**Comment by tama1214** [comment]
I found solution

```
data "oci_core_subnets" "test_subnets" {
    #Required
    compartment_id = "${data.terraform_remote_state.vcn.compartment_ocid}"
    vcn_id = "${data.terraform_remote_state.vcn.vcn_ocid}"

    #Optional
	filter {
        name = "cidr_block"
        values = ["${var.cidr_block}"]      
    }
}
```
`subnet_id = "${lookup(data.oci_core_subnets.test_subnets.subnets[0], "id")}"`

This script helps to get the subnet_ocid of a specific subnet that you specify in the filter ( values = ["${var.cidr_block}"] )
