### ISSUE TITLE
Removing ingress/egress of an applied security group does not get into the plan nor apply

### ISSUE THREAD

**Issue by stephenchu** [hashicorp/terraform#2047]
When you have a security group that already has a ingress/egress already applied (i.e. in tfstate), if you then remove any ingress/egress block for it, `terraform plan` does not show such a change in the diff, and applying it will assume noop.

This behavior contradicts with say when I remove the `tags` block entirely, the security group shows diff.

Terraform 0.5.2 was used.

```
$ cat main.tf
resource "aws_security_group" "buggy" {
  name = "Buggy"
  description = "Buggy"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

**Comment by catsby** [comment]
Folding this into #2151
