### ISSUE TITLE
Wrong line number reported when there are syntax errors.

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform#2048]
I have some big configurations files. I've noticed that whenever there is a syntax error, the reported line number is not correct. It happens consistently.

**Comment by phinze** [comment]
Yep - totally. This is definitely annoying and we'll get it fixed up.

**Comment by QuinnyPig** [comment]
#2286 has a "steps to reproduce" section if that's at all helpful for testing purposes.

**Comment by blewa** [comment]
+1 - I was super confused for an afternoon before I found this bug.

**Comment by amontalban** [comment]
:+1:

**Comment by mitchellh** [comment]
This should be fixed now with the new HCL changes.
