### ISSUE TITLE
v0.12 testing: Each argument may be set only once

### ISSUE THREAD

**Issue by jtopjian** [hashicorp/terraform#20485]
I'm running in to an odd error when testing the OpenStack Provider with Terraform v0.12:

```
=== RUN   TestAccNetworkingV2PortDataSource_basic
2019/02/26 05:16:13 [DEBUG] Test: Executing step 0
2019/02/26 05:16:13 [WARN] Skipping destroy test since there is no state.
--- FAIL: TestAccNetworkingV2PortDataSource_basic (0.01s)
    testing.go:568: Step 0 error: /tmp/tf-test214392673/main.tf:32,3-11: Attribute redefined; The argument "fixed_ip" was already set at /tmp/tf-test214392673/main.tf:28,3-11. Each argument may be set only once., and 1 other diagnostic(s)
```

The test is defined here: https://github.com/terraform-providers/terraform-provider-openstack/blob/1002ed7e69a41d10be269c31c33161c173d7a1fb/openstack/data_source_openstack_networking_port_v2_test.go

The `fixed_ip` argument is defined here: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_port_v2.go#L104-L121

I think this is being caused by two identical `fixed_ip`'s being declared, but that's possible to do with this resource via the API and since it's a `TypeList`, I would have imagined identical declarations are ok?

**Comment by jbardin** [comment]
Hi @jtopjian,

This is because `fixed_ip` is a "block" type, not an attribute. You need to remove the `=` from the `fixed_ip` lines so that each block can be added to the internal list.

**Comment by jtopjian** [comment]
@jbardin Yes, that did the trick 😄 

Thank you!
