### ISSUE TITLE
terraform id: => <computed> (forces new resource) on AWS EC2 instance

### ISSUE THREAD

**Issue by JasonOliverEmaze** [hashicorp/terraform#20492]
### Terraform Version
```
Terraform v0.11.8
+ provider.aws v1.60.0
...
```

### Terraform Configuration Files
```
  ami           = "${data.aws_ami.windows2012R2.id}"
  disable_api_termination = "true"
  instance_type = "m5.xlarge"
  subnet_id     = "${var.subnetb}"
  key_name      = "${var.key_name}"
  iam_instance_profile    = "${aws_iam_instance_profile.iamip-XXXX.id}"
  vpc_security_group_ids  = ["${aws_security_group.sg-XXXX.id}", "${aws_security_group.sg-windows-ad.id}", "${aws_security_group.sg-scom.id}", "${aws_security_group.sg-pwch.id}"]
  monitoring            = true
  private_ip            = "1.1.1.1."
  root_block_device {
      volume_size       = "80"
   }
    ebs_block_device {
      device_name       = "xvdb"
      volume_size       = "20"
      encrypted         = true
   }
  user_data             = "${file("userdata-windows.txt")}"
```

### Debug Output
```
-/+ aws_instance.ec2-XXXXX (new resource required)
      id:                                                "i-XXXXXXXXXXXX" => <computed> (forces new resource)
```

### Expected Behavior
Since I am just updating security groups I am expecting the EC2 instances to remain in-situ and not be impacted by the change.

### Actual Behavior
Instead, TerraForm is trying to force a an instance reprovision which will destroy the current configuration. 

### Steps to Reproduce
1. `terraform init`
2. `terraform plan` or `terraform apply`

### References
- #6569

**Comment by reznid01** [comment]
Just to make sure I understand... Based on your reply it means that on any changes to the tags or security group assignment the instance will be rebuilt. This doesn't make any sense.

**Comment by notzippy** [comment]
Why was this closed @JasonOliverEmaze ? I am experiencing a similar issue -
Terraform v0.11.13
+ provider.aws v2.8.0

```
      id:                           "i-04fe4903527e9ef8d" => <computed> (forces new resource)                                                                                                         
....
      security_groups.#:            "0" => "1" (forces new resource)
      security_groups.3420551258:   "" => "sg-xxxxxxxx" (forces new resource)
```
On Aws it shows there is more then one security group, not sure what the `security_groups.3420551258` represents

**Comment by soudaburger** [comment]
@notzippy the `security_groups.NNNNNNNNNN` is just an identifier for terraform assets.  That's how it tracks which security groups (in this case) exist and/or need to be modified and creates unique resources accordingly.
