### ISSUE TITLE
TypeSet Values not overwritten by d.Set with 0.12 SDK

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform#20504]
### Terraform Version

```
Running a Google provider acceptance test with 
github.com/hashicorp/terraform v0.12.0-alpha4.0.20190226230829-c2f653cf1a35 vendored.
```

`master` is in this state.

### Terraform Configuration Files

```hcl
	data "google_compute_image" "my_image" {
		family    = "debian-9"
		project = "debian-cloud"
	}

	resource "google_compute_instance" "ig_instance" {
		name = "%s-${count.index}"
		machine_type = "n1-standard-1"
		can_ip_forward = false
		zone = "us-central1-c"
		count = 2

		boot_disk {
			initialize_params {
				image = "${data.google_compute_image.my_image.self_link}"
			}
		}

		network_interface {
			network = "default"
		}
	}

	resource "google_compute_instance_group" "update" {
		description = "Terraform test instance group"
		name = "%s"
		zone = "us-central1-c"
		instances = google_compute_instance.ig_instance.*.self_link
		named_port {
			name = "http"
			port = "8080"
		}
		named_port {
			name = "https"
			port = "8443"
		}
	}
```

```hcl
	data "google_compute_image" "my_image" {
		family  = "debian-9"
		project = "debian-cloud"
	}

	resource "google_compute_instance" "ig_instance" {
		name = "%s-${count.index}"
		machine_type = "n1-standard-1"
		can_ip_forward = false
		zone = "us-central1-c"
		count = 2

		boot_disk {
			initialize_params {
				image = "${data.google_compute_image.my_image.self_link}"
			}
		}

		metadata_startup_script = "echo 'foo'"

		network_interface {
			network = "default"
		}
	}

	resource "google_compute_instance_group" "update" {
		description = "Terraform test instance group"
		name = "%s"
		zone = "us-central1-c"
		instances = ["${google_compute_instance.ig_instance.*.self_link}"]
		named_port {
			name = "http"
			port = "8080"
		}
		named_port {
			name = "https"
			port = "8443"
		}
	}
```

Followed by a destroy

### Debug Output

https://gist.github.com/rileykarson/f930c208263ff5e1396b6f0118dd36db

### Expected Behavior

Terraform sees no diff

### Actual Behavior

Terraform wrongly preserves an entry, leading to the following

```          instances.#:       "3" => "2"
          instances.0:       "FORCE_UPDATE" => "https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-x0ebd9yvgv-1"
          instances.1:       "https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-x0ebd9yvgv-1" => "https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-x0ebd9yvgv-0"
          instances.2:       "https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-x0ebd9yvgv-0" => ""
```

Possibly related, the hashes have been flattened to short values but the fields aren't matched properly.

### Steps to Reproduce
```
make testacc TEST=./google TESTARGS='-run=TestAccComputeInstanceGroup_recreatedInstances'
```

### Additional Context

Terraform can't detect when the component instances in an instance group have been updated and aren't in that group anymore. We use a CustomiseDiff to work around that, adding `FORCE_UPDATE` to the diff to force our expected behaviour. With the 0.11 SDK, this led to Terraform updating the instance group as expected.

Post-0.12 SDK Terraform performs the correct operations. But when setting new values using `d.Set`, the old value isn't overwritten. This leads to the fake value appearing in a diff.

**Comment by jbardin** [comment]
Thanks for the extra info here @rileykarson.

Again, this is a rather complex case, but I think the fundamental error is that Plan is returning something different from Apply. The plan is also taking greater liberties than it should, but the new core is accepting those for now. This will show up as a warning in the logs:

```
2019/02/28 18:58:43 [WARN] Provider "google" produced an invalid plan for google_compute_instance_group.update, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .instances: planned value cty.SetVal([]interface {}{"FORCE_UPDATE", "https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-3t864s1tg9-0", "https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-3t864s1tg9-1"}) does not match config value cty.SetVal([]interface {}{"https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-3t864s1tg9-0", "https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-3t864s1tg9-1"}) nor prior value cty.SetVal([]interface {}{"https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-3t864s1tg9-0", "https://www.googleapis.com/compute/v1/projects/hc-terraform-testing/zones/us-central1-c/instances/instancegroup-test-3t864s1tg9-1"})
```

Terraform expects what is planned to the be state that is applied. While core still tolerates some discrepancies here for backwards compatibility, the provider not following the plan is thwarted by the sdk shims in this case, which is why there's no corresponding warning for apply.

Due to inconsistencies in the legacy sdk (`helper/schema`), if there's a discrepancy in the apply value, the shims may not be able to determine if it was the fault of the provider or the legacy sdk. If the value was a set type, we have to favor the planned value which is what should have been applied.

I think from the looks of things, you may be able to continue to get away with this by switch instances to a `TypeList`. I did a quick modification of `resource_compute_instance_group.go` and ran this particular test to completion.

**Comment by rileykarson** [comment]
This should be a non-issue for us now, we'll remove the `CustomizeDiff` we`re using.
