### ISSUE TITLE
Provider Alias Token Not Respected 

### ISSUE THREAD

**Issue by darnold-harness** [hashicorp/terraform#20519]
### Terraform Version
```
Terraform v0.11.11
```

### Terraform Configuration Files
```hcl
provider "aws" {
  access_key = "${data.vault_aws_access_credentials.playground.access_key}"
  secret_key = "${data.vault_aws_access_credentials.playground.secret_key}"
  region     = "us-east-1"
  alias = "playground"
}

resource "aws_vpc_peering_connection" "vpc_platform" {
  provider = aws.playground
  peer_owner_id = "${data.terraform_remote_state.playground_account.account_id}"
  peer_vpc_id   = "${data.terraform_remote_state.platform_network.vpc_id}"
  vpc_id        = "${data.terraform_remote_state.playground_network.vpc_id}"
}
```

### Debug Output
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /Users/darnold/git/Terraform-Infrastructure/environments/AWSPlayGround/network/vpc_peering/main.tf: At 58:14: Unknown token: 58:14 IDENT aws.playground

### Expected Behavior
As per, https://www.terraform.io/docs/configuration/providers.html#selecting-alternate-providers. I'd expect this syntax to work.

### Actual Behavior
Error: Error parsing /Users/darnold/git/Terraform-Infrastructure/environments/AWSPlayGround/network/vpc_peering/main.tf: At 58:14: Unknown token: 58:14 IDENT aws.playground

**Comment by apparentlymart** [comment]
Hi @darnold-harness,

For Terraform 0.11, the provider address must be given in quotes:

```hcl
provider = "aws.playground"

```

For more information, see [the 0.11 equivalent of those docs](https://www.terraform.io/docs/configuration-0-11/providers.html#multiple-provider-instances).
