### ISSUE TITLE
-target ignored on terraform 0.11.11

### ISSUE THREAD

**Issue by DrHashi** [hashicorp/terraform#20536]
### Terraform Version
```
Terraform v0.11.11

MAC OS 10.14.3 and Ubuntu 16.04 LTS
```

### Expected Behavior

There are changes on aws_security_group.bastion but it should be ignored due to -target

terraform plan -target=aws_security_group.prometheus_sg
```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Actual Behaviour
```
terraform plan -target=aws_security_group.prometheus_sg 

  ~ aws_security_group.jump
...
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Config
```
resource "aws_security_group" "jump" {
    name        = "${var.env}-jump"
    description = "${var.env}-jump"
    vpc_id      = "${aws_vpc.vpc.id}"

    ingress {
        from_port       = 22
        to_port         = 22
        protocol        = "tcp"
        cidr_blocks     = ["${var.cidr_blocks["home"]}"]
    }


    egress {
        from_port       = 443
        to_port         = 443
        protocol        = "tcp"
        cidr_blocks     = ["0.0.0.0/0"]
    }

    egress {
        from_port       = 80
        to_port         = 80
        protocol        = "tcp"
        cidr_blocks     = ["0.0.0.0/0"]
    }

}


resource "aws_security_group" "prometheus_sg" {
    name        = "${var.env}-prometheus-sg"
    description = "${var.env}-prometheus-sg"
    vpc_id      = "${aws_vpc.vpc.id}"

    ingress {
        from_port       = 22
        to_port         = 22
        protocol        = "tcp"
        security_groups = ["${aws_security_group.jump.id}"]
        self            = false
    }

    egress {
        from_port       = 443
        to_port         = 443
        protocol        = "tcp"
        cidr_blocks     = ["0.0.0.0/0"]
    }

    egress {
        from_port       = 80
        to_port         = 80
        protocol        = "tcp"
        cidr_blocks     = ["0.0.0.0/0"]
    }


}
```
### Steps to Reproduce

1. Make changes on the cloud infrastructure manually
2. Run a plan or apply using -target
3. Changes output will include or overwrite those modified manually 

### Additional Context
I have multiple servers and security groups that are behind the bastion host but for troubleshooting purposes, I decided to whitelist another IP temporarily.

After doing a plan targeted for other changes, the changes for the bastion host got caught along with it.

**Comment by apparentlymart** [comment]
Hi @DrHashi,

Since you didn't share a configuration example I can't know for sure what happened here, but: does `aws_security_group.prometheus_sg` depend on (directly or indirectly) `aws_security_group.jump`? When you use `-target`, it is an instruction to Terraform to work on that resource instance _and any others it depends on_.

**Comment by DrHashi** [comment]
> Hi @DrHashi,
> 
> Since you didn't share a configuration example I can't know for sure what happened here, but: does `aws_security_group.prometheus_sg` depend on (directly or indirectly) `aws_security_group.jump`? When you use `-target`, it is an instruction to Terraform to work on that resource instance _and any others it depends on_.

updated

**Comment by apparentlymart** [comment]
Hi @DrHashi! Thanks for the extra information.

Indeed, what you've seen here is expected behavior. The reference to `aws_security_group.jump.id` via interpolation creates an implicit dependency because Terraform needs to create the security group before the id can be known.
