### ISSUE TITLE
userdata does not run if provisioner remote-exec is also declared

### ISSUE THREAD

**Issue by vvitayau** [hashicorp/terraform#20540]
### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.22.0
+ provider.consul v1.0.0
+ provider.template v2.1.0
```

### Terraform Configuration Files

```
resource "aws_instance" "www" {
    ami = "${lookup(var.aws_web_amis, data.consul_keys.env.var["aws_region"])}"
    availability_zone = "${element(split(" ",data.consul_keys.env.var["aws_regions"]), count.index % length(split(" ",data.consul_keys.env.var["aws_regions"])) )}"
    connection {
        agent       = false
        type        = "ssh"
        user        = "centos"
        private_key = "..."
    }
    count = 1
    instance_type = "t2.micro"
    key_name = ".."
    provisioner "file" {
        source = "./bin/www.sh"
        destination = "/tmp/www.sh"
    }
    provisioner "remote-exec" {
        inline = [
          "sudo chmod +x /tmp/www.sh"
        ]
    }
    security_groups = [ "..." ]
    subnet_id = "${element(split(" ",data.consul_keys.env.var["aws_public_subnet_ids"]), count.index % length(split(" ",data.consul_keys.env.var["aws_public_subnet_ids"])) )}"
    tags = {
        Name            = "web-${count.index}"
    }
    user_data = "sudo chmod -w /tmp/www.sh"
}
```

### Expected Behavior

```
-r-xr-xr-x. 1 centos centos 624 Mar  1 18:06 /tmp/www.sh
```

### Actual Behavior
```
-rwxr-xr-x. 1 centos centos 624 Mar  1 18:06 /tmp/www.sh
```

### Steps to Reproduce

```
terraform init
terraform apply
```

### Additional Context

Going to prefer using userdata over remote-exec because of #16031

Would prefer both work where eventually this would entail migrate to using packer to create AMI for faster setup via the remote-exec portion whereas I still require the user_data for dynamic configuration.

### References

- https://stackoverflow.com/questions/44378064/terraform-should-i-use-user-data-or-provisioner-to-bootstrap-a-resource

**Comment by jbardin** [comment]
Hi @vvitayau,

`user_data` is completely independent from provisioners, so there's not really any way they can directly influence one another. You cannot ensure that the `user-data` is executed before or after the `remote-exec`, they can even be running concurrently, but in fact the user-data is likely to run first for anything short lived. Also, I'm not sure what the ami you're using accepts, but I don't think a bare shell command like you've inserted will be executed at all, there's certain formats for the data accepted by the init system on the ami.

If you have a reproducible example that demonstrates your issue, we can see what what might be required to suit your use case.

**Comment by vvitayau** [comment]
my apologies ... it appeared the fault is our ami on AWS that did not invoke cloud-config runcmd on setup
