### ISSUE TITLE
0.12 `terraform show` and `terraform state show` fail if plugins are not in the default location

### ISSUE THREAD

**Issue by KaushikIyer16** [hashicorp/terraform#20547]
Hey,
So whenever i try to run the terraform show with the -json option followed by a path to a .tfstate/.tfplan file, it does not find the schema / gives me an error respectively.

### Terraform Version
```
Terraform v0.12.0-beta1
```

### Terraform Configuration Files

```hcl
variable "AWS_SECRET_KEY" {}
variable "AWS_ACCESS_KEY" {}

provider "aws" {
  region="us-east-1"
  access_key = var.AWS_ACCESS_KEY
  secret_key = var.AWS_SECRET_KEY
}


resource "aws_instance" "knsi_new_instance" {
  ami = "ami-011b3ccf1bd6db744"
  instance_type = "t1.micro"
  key_name = "knsi"
  tags = {
    Name= "Mark 2 KNSI Cloud"
  }
}
```
### Expected Behavior

A json representing the state or the plan
### Actual Behavior
am getting the following error for ``` terraform show -json ./projects/mk1/terraform.tfplan ```:
```
Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".
```
and the following output for ```terraform show ./projects/mk1/terraform.tfstate```:
```
# aws_instance.knsi_new_instance: 
# missing schema for provider "aws"
```
But the plan file is getting created and the apply command is working, i have also tried repeated initialisation as suggested, does not seem to work.

### Steps to Reproduce
1. create the tf configuration as mentioned above in /home/projects/mk1/mark1.tf
2. i have a plugins directory in /home/ with the dependecy ``` terraform-provider-aws_v1.60.0-dev20190216H00-dev_x4```
3. i have initialized the project with the following command:
``` terraform init -input=false -plugin-dir=./plugins/ ./projects/mk1/```
4. have run the following commands to see the json output:
```
terraform show -json ./projects/mk1/terraform.tfplan
terraform show -json ./projects/mk1/terraform.tfstate
```

**Comment by apparentlymart** [comment]
Thanks for reporting this, @KaushikIyer16.

I suspect that this command is not honoring `-plugin-dir` as expected, and so is expecting to find the plugins in the default location instead.

If so, a workaround for now would be to place the AWS provider binary in the same directory as `terraform` itself (or one of the other documented search paths), and run `terraform init` without `-plugin-dir`.

**Comment by mildwonkey** [comment]
This is also an issue in `terraform state show`
