### ISSUE TITLE
template file - data.ct_config.service - could not find expected ':'

### ISSUE THREAD

**Issue by sampcoug** [hashicorp/terraform#20559]
### Terraform Version

```
Terraform v0.11.11
+ provider.ct (unversioned)
+ provider.google v2.1.0
+ provider.null v2.1.0
+ provider.template v2.1.0

```

### Terraform Configuration Files
**main.tf**

```
  data "template_file" "ct" {
  count = "${var.count}"
  depends_on  = ["data.template_file.etcd_discovery_url"]
  template = "${file("config.tpl")}"
  vars {
    hostname = "${var.hostname}"
    shortname = "${var.shortname}"
    docker_repo = "${var.docker_repo}"
    gcp_region = "${var.region}"
    message = "${var.message}"
    etcd_discovery_url = "${file("${var.etcd_discovery_token_file_path}")}",
  }
}
data "ct_config" "service" {
  pretty_print = true
  platform = "gce"
  content      = "${data.template_file.ct.rendered}"
}

resource "null_resource" "etcd" {
  provisioner "local-exec" {
    command = "curl https://discovery.etcd.io/new?size=${var.count} > ${var.etcd_discovery_token_file_path}"
  }
}

#Create a new instance
resource "google_compute_instance" "instance1" {
  name         = "xxx"
  machine_type = "${var.machine_type}"
  zone         = "xxxx"

#boot_disk and other configs are omitted. 

  metadata_startup_script = "${element(data.ct_config.service.*.rendered, count.index)}"
} 

```

**config.tpl**

```
echo hellogoogle > /tmp/hello.txt
```

### Crash Output

Error: Error applying plan:

1 error(s) occurred:

* data.ct_config.service: data.ct_config.service: error parsing Container Linux Config: error: yaml: line 22: could not find expected ':'

### Expected Behavior

Terraform apply - should have run successfully. 

### Actual Behavior

Terraform apply - failed with error message above.

### Steps to Reproduce
1. Please render my main.tf and  config.tpl file.

**Comment by apparentlymart** [comment]
Hi @sampcoug,

This error seems to be coming from the `ct` provider. I'm not familiar with that provider, but from the context my guess is that it's expecting `content` to be valid YAML but the result of your template contains a syntax error.

If you run `terraform show` you may be able to see in the output the rendered result of `data.template_file.ct` to see what is invalid about it. If that doesn't help, you may need to ask in [the `ct` provider repository](https://github.com/coreos/terraform-provider-ct) where the provider maintainer team can hopefully help more.

**Comment by sampcoug** [comment]
@apparentlymart thank you! I ran `terraform show' and looked at the output but nothing jumped out. I will reach out to the [terraform-provider-ct](https://github.com/coreos/terraform-provider-ct/issues) for guidance.
