### ISSUE TITLE
provider/aws: Error creating ENI: InternalError: An internal error has occurred

### ISSUE THREAD

**Issue by DMNSteve** [hashicorp/terraform#2055]
Using version 0.5.1

Trying to create Elastic Network Interfaces and getting the following error.

    aws_network_interface.network-interface-nat-public-a: Creating...
      security_groups.#:          "" => "1"
      security_groups.1901574614: "" => "security-group-nat"
      subnet_id:                  "" => "subnet-05ac3a72"
    aws_network_interface.network-interface-nat-public-a: Error: 1 error(s) occurred:

    * Error creating ENI: InternalError: An internal error has occurred
    Error applying plan:

    1 error(s) occurred:

    * 1 error(s) occurred:

    * 1 error(s) occurred:

    * Error creating ENI: InternalError: An internal error has occurred

    Terraform does not automatically rollback in the face of errors.
    Instead, your Terraform state file has been partially updated with
    any resources that successfully completed. Please address the error
    above and apply again to incrementally change your infrastructure.

This is the ENI config. 

    resource "aws_network_interface" "network-interface-nat-public-a" {
      subnet_id = "${aws_subnet.subnet-public-a.id}"
      security_groups = ["${aws_security_group.security-group-nat.name}"]
    }

**Comment by DMNSteve** [comment]
And finally the log.

    aws_network_interface.dmn-network-interface-nat-public-a: Creating...
      security_groups.#:          "" => "1"
      security_groups.1942567629: "" => "security-group-nat"
    2015/05/23 22:01:56 [DEBUG] root: eval: terraform.EvalNoop
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalOpFilter
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalSequence
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalReadDiff
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalIf
    2015/05/23 22:01:56 [ERROR] root: eval: *terraform.EvalIf, err: early exit
    2015/05/23 22:01:56 [ERROR] root: eval: *terraform.EvalSequence, err: early exit
    2015/05/23 22:01:56 [ERROR] root: eval: *terraform.EvalOpFilter, err: early exit
    2015/05/23 22:01:56 [ERROR] root: eval: *terraform.EvalSequence, err: early exit
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalReadDiff
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalCompareDiff
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalGetProvider
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalReadState
    2015/05/23 22:01:56 [DEBUG] root: eval: *terraform.EvalApply
    2015/05/23 22:01:56 [DEBUG] apply: aws_network_interface.dmn-network-interface-nat-public-a: executing Apply
      subnet_id:                  "" => "subnet-05ac3a72"
    2015/05/23 22:01:56 terraform-provider-aws: 2015/05/23 22:01:56 [DEBUG] Creating network interface
    2015/05/23 22:03:04 [DEBUG] root: eval: *terraform.EvalWriteState
    2015/05/23 22:03:04 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
    2015/05/23 22:03:04 [DEBUG] root: eval: *terraform.EvalIf
    2015/05/23 22:03:04 [DEBUG] root: eval: *terraform.EvalWriteDiff
    2015/05/23 22:03:04 [DEBUG] root: eval: *terraform.EvalIf
    2015/05/23 22:03:04 [DEBUG] root: eval: *terraform.EvalWriteState
    2015/05/23 22:03:04 [DEBUG] root: eval: *terraform.EvalApplyPost
    2015/05/23 22:03:04 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

    * Error creating ENI: InternalError: An internal error has occurred
    2015/05/23 22:03:04 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

    * Error creating ENI: InternalError: An internal error has occurred
    2015/05/23 22:03:04 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

    * Error creating ENI: InternalError: An internal error has occurred
    2015/05/23 22:03:04 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

    * Error creating ENI: InternalError: An internal error has occurred
    aws_network_interface.dmn-network-interface-nat-public-a: Error: 1 error(s) occurred:

    * Error creating ENI: InternalError: An internal error has occurred
    2015/05/23 22:03:04 waiting for all plugin processes to complete...
    2015/05/23 22:03:04 [DEBUG] /vagrant/support/terraform/terraform-provider-aws: plugin process exited

**Comment by DMNSteve** [comment]
UPDATE: Works fine when specifying a private IP. Is this field required?

    resource "aws_network_interface" "network-interface-nat-public-a" {
      subnet_id = "${aws_subnet.subnet-public-a.id}"
      security_groups = ["${aws_security_group.security-group-nat.id}"]
      private_ips = ["172.32.0.254"]
      tags {
        Name = "eni-nat-public-a"
      }
    }

**Comment by mpeter** [comment]
I'm seeing the same issue. From reading the source and test cases, to me it appears that private_ips is incorrectly marked as Optional.

I'm trying to use this for AWS Nat instances. The various HA solutions out there for NAT instances typically recommend running the instance inside an auto scaling group, and attaching the network interface to the route table, rather than the instance id.

I haven't been able to make this work yet because:
- I'd prefer to not add another IP address to the attachment, i'd prefer to use the primary network address assigned to the NAT
- You can't currently setup a launch configuration to support "source_dest_check = false", like you can with an aws_instance.

**Comment by justnom** [comment]
I've fixed the issue with the empty `private_ips` and `security_groups` attirbutes for `aws_network_interface` in PR #2232.
