### ISSUE TITLE
adding provider for rage4 dns

### ISSUE THREAD

**Issue by anuaimi** [hashicorp/terraform#2056]
Can Rage4 DNS be added as a provider?  What is the policy for adding new providers?  I can probable take on the work of creating this.

```
<personal opinion>
While there are many DNS providers out there, Rage4 has a strong API, decent pricing and especially strong geo-DNS support.
</personal opinion>
```

**Comment by anuaimi** [comment]
I've started working on a generic package for Rage4 DNS (https://github.com/anuaimi/rage4).  If I get the green light, I'll also create a provider for Terraform.

**Comment by phinze** [comment]
Hi there! Generally what we do for situations like this is to have you start implementation in a separate repo. [Terraform's plugin system](http://www.terraform.io/docs/plugins/basics.html) allows separately distributed binaries to seamlessly integrate provided they show up in the `$PATH`.

If you [search for other Terraform providers](https://github.com/search?utf8=%E2%9C%93&q=terraform+provider&type=Repositories&ref=searchresults) on GitHub you can find a bunch of examples to get you started. We'll consider including as builtin any plugin that passes our code review standards and can demonstrate enough user / contributor interest such that it seems like it will remain maintainable.

Hope this helps! I'll close this issue but feel free to follow up with any further questions you may have.
