### ISSUE TITLE
[Errno 2] No such file or directory using External Data Source

### ISSUE THREAD

**Issue by JasonOliverEmaze** [hashicorp/terraform#20568]
### Terraform Version
```Terraform v0.11.11 + provider.external v1.0.0```

### Terraform Configuration Files
data "external" "script" {
  program = ["python", "${path.module}\\secret.py -id SFTP-Key -keyname private-key"]
}

output "Private Key" {
  value = "${data.external.script.result.program}"
}

### Expected Behavior
I was hoping to recieve the output of the script in the same way stdout would after running python C:\Users\oliverj\Documents\Code\github\test\secret.py -id SFTP-Key -keyname private-key

### Actual Behavior
Error: Error refreshing state: 1 error(s) occurred:

* data.external.script: 1 error(s) occurred:

* data.external.script: data.external.script: failed to execute "python": python: can't open file 'C:\Users\oliverj\Documents\Code\github\test\secret.py -id SFTP-Key -keyname private-key': [Errno 2] No such file or directory-->

### Steps to Reproduce
1. `terraform init`
2.  `terraform plan` or `terraform apply`

### Additional Context
I am able to runpython C:\Users\oliverj\Documents\Code\github\test\secret.py -id SFTP-Key -keyname private-key without issue

**Comment by apparentlymart** [comment]
Hi @JasonOliverEmaze,

The `external` data source expects each argument to be a separate element in the list, like this:

```hcl
  program = ["python", "${path.module}\secret.py", "-id", "SFTP-Key", "-keyname", "private-key"]
```

I think with your current configuration, Python is trying to treat the entire string `C:\Users\oliverj\Documents\Code\github\test\secret.py -id SFTP-Key -keyname private-key` as the script to run, which therefore doesn't work.

**Comment by JasonOliverEmaze** [comment]
Many thanks for the response @apparentlymart, very much appreciated.

I am now receiving the following error:

'''data.external.script: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.external.script: 1 error(s) occurred:

* data.external.script: data.external.script: command "python" produced invalid JSON: invalid character '-' in numeric literal'''

**Comment by noahsuresh** [comment]
failed to execute "python":  it finds the python file prints some of the values in it but still gives this error any idea about this
