### ISSUE TITLE
Call to function "lookup" failed: lookup() can only be used with flat lists.

### ISSUE THREAD

**Issue by mingfang** [hashicorp/terraform#20572]
This still doesn't work as of 0.12 beta 1.
I'm not looking for workarounds, rather an acknowledgement that this is a real problem and that it will get fixed in the future.

**Comment by mingfang** [comment]
The best hack around I come up with is something like this
```
api_groups        = contains(keys(rules.value), "api_groups") ? rules.value["api_groups"] : null
```
It works but it looks like a very expensive in CPU.

**Comment by mbrannigan** [comment]
Same problem.  Calling code:

`is_multi_az = "${lookup(var.dw_is_multi_az, var.class)}"`

referring to the following variable:
```
variable "dw_is_multi_az" {
  description = "Is instance multi-az"
  type = "map"
  default = {
    development = false
    staging = false
    production = true
  }
}
```

A workaround was to change the code to:
`is_multi_az = "${var.dw_is_multi_az[var.class]}"`

**Comment by paultyng** [comment]
Minimal repro file:

```terraform
variable "class" {
  default = "development"
}

variable "dw_is_multi_az" {
  description = "Is instance multi-az"
  type        = "map"
  default = {
    development = false
    staging     = false
    production  = true
  }
}

locals {
  # error
  lookup = lookup(var.dw_is_multi_az, var.class)
  # works
  index = var.dw_is_multi_az[var.class]
}
```

**Comment by paultyng** [comment]
`Bool` was left out: https://github.com/hashicorp/terraform/blob/8f29e2e11f0a0be0d838c1307470827239bcba2d/lang/funcs/collection.go#L688-L691
