### ISSUE TITLE
S3 backend workspaces

### ISSUE THREAD

**Issue by gpgabriel** [hashicorp/terraform#20600]
### Terraform Version

```
v0.11.11
```

### Terraform Configuration Files

```hcl
 terraform {
   backend "s3" {
     bucket = "my-terraform-states"
     region = "eu-west-2"
     key    = "my-project/state"
     workspace_key_prefix = "my-project/env/"
   }
 }
```

### Expected Behavior

After I run `terraform init` and `terraform apply` it all works as expected. If I create a new workspace by running `terraform workspace new development` I'm moved to the new workspace as expected and then I can run `terraform apply`. At this point I have 2 instances of the architecture created. If I check the s3 bucket I can see the new `my-project` folder, the `state` file (associated with the default workspace) and the `env` folder which has the `development` workspace inside. So far it all works well. If I switch to the `default` workspace and run `terraform workspace list`, I expect to get `default` and `development` as the results.

### Actual Behavior

When I run `terraform workspace list` I only get the `default` workspace even though the `development` was created and was applied. At this point I'm not able to touch the `development` workspace at all, it disappears completely from the CLI (I can still see it in the s3 bucket).

### Additional Context

I think the bug could be related to the fact that an extra space is added to the `env` folder in the s3 bucket ("env" is actually " env").

### References

- [#15358](https://github.com/hashicorp/terraform/issues/15358)

**Comment by gpgabriel** [comment]
Replacing `workspace_key_prefix = "my-project/env/"` with `workspace_key_prefix = "my-project/env"` fixes the issue.

**Comment by jbardin** [comment]
Hi @gpgabriel,

Thanks for reporting the issue. This is fixed in master, and in the next release the `workspace_key_prefix` will be rejected if it contains a leading or trailing `/`.
