### ISSUE TITLE
Trigger Fails to Fire

### ISSUE THREAD

**Issue by AndyHollings** [hashicorp/terraform#20617]
```
data "aws_ssm_document" "RunPowerShellScript_DL_files" {
  name = "AWS-RunPowerShellScript"
  document_format = "JSON"
}

resource "null_resource" "RunPowerShellScript_DL_files" {
  triggers = {
    build_number = "${timestamp()}"
  }
}

resource "aws_ssm_association" "RunPowerShellScript_DL_files" {
  name = "${data.aws_ssm_document.RunPowerShellScript_DL_files.name}"
  parameters { commands = "new-item 'c:\\posh\\dscartifacts' -itemtype directory -force -ErrorAction SilentlyContinue"}
  targets {
    key    = "InstanceIds"
    values = ["${aws_instance.bastion_main.id}"]
    }
  depends_on = ["null_resource.gbgdscartifacts", "null_resource.RunPowerShellScript_DL_files"]
}
```

**Comment by jbardin** [comment]
Hi @AndyHollings,

Can you explain what the desired behavior is, and what it is you're seeing?

Using `timestamp()` in the null_resource `triggers` is going to cause that resource to be replaced every time you run terraform, so you're never going to be able to get an empty plan. I'm not sure if that's the intent, or you're not seeing that actually happen.

**Comment by AndyHollings** [comment]
Yes I want it to trigger ever time.

I found the powershell resource on AWS did not run the powershell had a linked dependency on this resource.

Regards - Andy

**Comment by jbardin** [comment]
Hi @AndyHollings,

The `depends_on` attribute only creates a dependency on the named resource, which means that `null_resource` changes happen before `aws_ssm_association`, but it cannot trigger recreation of the resource.

What you're looking for isn't directly available, but there is an open issue to consider it as a future enhancement at #8099
