### ISSUE TITLE
Hidden folder is created as a file

### ISSUE THREAD

**Issue by orwell1984** [hashicorp/terraform#20625]
The following simple file provisioner creates `.aws` file insead of expected `.aws/credentials` folder and file:
 ```
    source      = "~/.aws/credentials"
    destination = "/home/ubuntu/.aws/credentials"
```

Contents are correctly transferred. 
Is there something special about copying hidden folders in Terraform?

**Comment by orwell1984** [comment]
Seems to be the same as https://github.com/hashicorp/terraform/issues/16330

**Comment by apparentlymart** [comment]
Yes @orwell1984, this does seem to be the same as #16330. Thanks for reporting this and for identifying the duplicate! I'm going to close this just to consolidate the discussion in the other issue.
