### ISSUE TITLE
0.12 terraform show is empty when using remote state backend

### ISSUE THREAD

**Issue by sjwl** [hashicorp/terraform#20642]
Seems the latest version has a problem with `terraform show` when using a remote state backend.

In my testing I used two types of remote state backends: Artifactory and Consul. 

I happened to have an older 0.12 version and it didn't exhibit the problem, it was compiled Feb 28th.

### Terraform Version

cloned from today
```
Terraform v0.12.0-dev
+ provider.null v2.1.0
```

### Terraform Configuration Files

```hcl
terraform {
  backend "consul" {
    address = "localhost:8500"
    scheme = "http"
    path  = "foo/bar"
  }
}

resource "null_resource" "foo" {
}
```

### Debug Output
[debug](https://gist.githubusercontent.com/sjwl/a597293384600644ff9af4376ce9ccdf/raw/edacad3fb28eec4d63d320c102f5e3f76db68e82/gistfile1.txt)

### Expected Behavior
```
terraform show
# null_resource.foo:
resource "null_resource" "foo" {
    id = "9128653108260824382"
}
```

### Actual Behavior
```
terraform show
(nothing)
```

### Steps to Reproduce
`terraform init`
`terraform apply`
`terraform show`

**Comment by mildwonkey** [comment]
@sjwl thank you for opening this issue and specifying when your last working version of terraform was  compiled - that information made this issue very easy to fix!
