### ISSUE TITLE
Issue with cyclic dependency in aws_route_table

### ISSUE THREAD

**Issue by gstamp** [hashicorp/terraform#2065]
I'm converting an existing CloudFormation template across to terraform and I've encountered a dependency cycle.  The template minus the relevant bits looks like this: 

```
resource "template_file" "nat_1_instance_template" {
        filename = "${var.nat_instance_template_file}"
        vars {
                private_route_table = "${aws_route_table.private_route_table_1.id}"
                ...
        }
}
resource "aws_instance" "nat_1_instance" {
        ...
        user_data = "${template_file.nat_1_instance_template.rendered}"
}
resource "aws_route_table" "private_route_table_1" {
        vpc_id = "${aws_vpc.vpc.id}"
        route {
                cidr_block = "0.0.0.0/0"
                instance_id = "${aws_instance.nat_1_instance.id}"
        }
        ...
}
```

As you can see there's definitely a cycle there.  The reason this wasn't an issue in the original cloudformation script however was that you could specify a route resource independently of the route table. This does not appear to be an option in terraform. Is there a workaround available for this issue? It's currently the main blocker I have to moving to terraform.

**Comment by andrewjhumphrey** [comment]
So the NAT devices are tricky little beasts.

What we want to do is add to the private route table that all instances in the private subnets use to send them via the NAT instance.  You could theoretically move that functionality into the user-data/bootstrap of the NAT boxes themselves I guess...

**Comment by johnrengelman** [comment]
Looks like we'll need to add a `route` resource to correspond to http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRoute.html

**Comment by simpsora** [comment]
:+1: to adding `route` as a resource type.

**Comment by mahileeb** [comment]
+1 for this! The lack of ability to add a route to an existing route table is all that is stopping a fully automated deployment of our environment. FYI our use case is that we have a primary VPC with our remote access server in it. We want to automate creation of test environments each in their own VPC. We need to add a route to the primary VPC route table to route over the peering connection to the newly created VPC. We then use a bastion host setup to provision the new instances via the remote access box, over the VPC peering connection to the new VPC.

**Comment by catsby** [comment]
Hey all – the `route` resource has been added recently:

- https://www.terraform.io/docs/providers/aws/r/route.html

I'm going to close this for now, please let us know if there's anything else needed here.

Thanks!
