### ISSUE TITLE
terraform show -json - not working

### ISSUE THREAD

**Issue by Aussie007** [hashicorp/terraform#20650]
Hi

Running terraform show -json does not work.

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.1.0
```

### Expected Behavior

Terraform state returned in JSON format
### Actual Behavior

Received the following:

Usage: terraform show [options] [path]
  Reads and outputs a Terraform state or plan file in a human-readable
  form. If no path is specified, the current state will be shown.

Options:

  -module-depth=n     Specifies the depth of modules to show in the output.
                      By default this is -1, which will expand all.

  -no-color           If specified, output won't contain any color.

### Steps to Reproduce

terraform show -json

**Comment by apparentlymart** [comment]
Hi @Aussie007,

This feature is not available in Terraform 0.11. It was added for Terraform 0.12.

It looks like we didn't add a note about that too the doc page, so sorry for misleading! We should add a version note to the docs to explain that there feature is new.

**Comment by Aussie007** [comment]
Hi @apparentlymart 

Thanks for the feedback and prompt response.

I'll close the ticket now.

Regards
A

**Comment by tj-recess** [comment]
> We should add a version note to the docs to explain that there feature is new.

Could we leave this issue open until documentation is updated?
