### ISSUE TITLE
0.12 file() Function usage suggests filebase64() while other functions may be more appropriate

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform#20664]
### Current Terraform Version

```
Terraform v0.12.0-beta1
```

### Description

In Terraform 0.12, the `file()` function only allows UTF-8 content to provide safety against state corruption. Prior to the introduction of the new file hashing functions in #20098, the `filebase64()` function was the only file conversion/hashing function available and the error messaging was coded to recommend it, however the recommendation can be incorrect in the following situations:

```hcl
# Terraform 0.11 Usage

resource "aws_lambda_function" "example" {
  filename         = "example.zip"
  function_name    = "example"
  handler          = "exports.example"
  role             = "${aws_iam_role.example.arn}"
  runtime          = "nodejs8.10"
  source_code_hash = "${base64sha256(file("example.zip"))}"
}

resource "aws_s3_bucket_object" "example" {
  bucket = "${aws_s3_bucket.example.id}"
  etag   = "${md5(file("example.tar.gz"))}"
  key    = "example.tar.gz"
  source = "example.tar.gz"
}
```

```
config is invalid: Error in function call: Call to function "file" failed: contents of example.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.

config is invalid: Error in function call: Call to function "file" failed: contents of example.tar.gz are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
```

The correct configuration updates here are the `filebase64sha256()` and `filemd5()` functions respectively.

### Proposal

It would be preferable to remove the explicit `filebase64()` function recommendation unless we know for certain it is the correct recommendation.

### References

- #20098

**Comment by apparentlymart** [comment]
I had a feeling this would come up. It is unfortunate, indeed.

I think the compromise I'd like to try here is to reword the message to be clearer about what we have changed: binary data can no longer be used, if a base64-encoded result is suitable then use `filebase64` instead, but note that the result will not be the same and so the value will need to be used in a different way.
