### ISSUE TITLE
Provide a way to re-create a resource based on a trigger

### ISSUE THREAD

**Issue by manfredlift** [hashicorp/terraform#20670]
I have a use-case where I would like to trigger the recreation of a resource when a value changes. This would function similarly to https://www.terraform.io/docs/provisioners/null_resource.html#triggers, but for other resources too.

Potentially, it could be a lifecycle argument as demonstrated below:
```hcl
resource "a" "a" {
  ...

  lifecycle {
    triggers = ["b.b.id"]
  }
}

resource "b" "b" {
  ...
}
```

In my use-case, I need a full re-creation (not modification in-place) of `resource "a"` when `resource "b"` is re-created. Maybe there's already a way to achieve this, but I haven't found a way?

**Comment by apparentlymart** [comment]
Hi @manfredlift! Thanks for sharing this use-case.

I think what you described here is the same idea as #8099, so I'm going to close this one just to consolidate the discussion over there.

Currently the only way to do this is to make a change to a resource-type-specific attribute that itself triggers a change.
