### ISSUE TITLE
Terraform Version Reports Wrong Version

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform#2067]
Just installed Terraform 0.5.1 with boxen

It reports as follows:

![screen shot 2015-05-25 at 15 59 11](https://cloud.githubusercontent.com/assets/227823/7798199/11c13b66-02f7-11e5-8f74-bb30108d83be.png)

On looking further, this is due to this:

https://github.com/hashicorp/terraform/commit/4ed2c8d956d2eae83a2a3750290711ce7fa1ec76

The 0.5.1 release actually is tagged in version.go as 0.5.2

**Comment by radeksimko** [comment]
Thanks for reporting, this is actually [a known](https://github.com/hashicorp/terraform/commit/4ed2c8d956d2eae83a2a3750290711ce7fa1ec76) [issue](https://github.com/hashicorp/terraform/commit/9422571ca261ba2359b5cce242c82a072bb24e04).
TL;DR `0.5.1` == `0.5.2`.
Sorry for the confusion.

This confusion will hopefully go away along with a new release. :package:
