### ISSUE TITLE
"invalid or unknown key: when" error.. when null_resource is provided with when = "destroy"

### ISSUE THREAD

**Issue by arvind008** [hashicorp/terraform#20725]
### Terraform Version

```
v0.11.11
provider.aws v2.2.0
provider.null v2.1.0

```

### Debug Output

```
invalid or unknown key: when
```
### Expected Behavior

```
Run the null_resource block
```
### Actual Behavior

```
Getting error saying unkown key "when"
```
### Additional Context

I am getting the error whn i try to do terraform apply

resource "null_resource" "key_deletion_in_local" {
  when = "destroy"
  provisioner "local-exec" {
    command = "sh modules/templates/some_script.sh"
  }
}

**Comment by apparentlymart** [comment]
Hi @arvind008!

The `when` argument belongs _inside_ the `provisioner` block:

```hcl
resource "null_resource" "key_deletion_in_local" {
  provisioner "local-exec" {
    when = "destroy"

    command = "sh modules/templates/some_script.sh"
  }
}
```

**Comment by arvind008** [comment]
ok @apparentlymart thanks for the info:-) it worked
