### ISSUE TITLE
0.12-beta1 - Remote state discrepancies

### ISSUE THREAD

**Issue by m13t** [hashicorp/terraform#20731]
### Terraform Version

```
Terraform v0.12.0-beta1
+ provider.aws v1.60.0-dev20190216h00-dev
+ provider.random v3.0.0-dev20190216h01-dev
+ provider.template v2.1.0-dev20190216h00-dev
```

### Terraform Configuration Files

```hcl
resource "aws_security_group" "this" {
	name_prefix = format("%s-", local.full_name)

	// VPC for the security group
	vpc_id = var.vpc.vpc_id

	// Description for the security group
	description = format("%s Load Balancer", local.full_name_tag)

	// Regardless of rules present, always remove
	revoke_rules_on_delete = true	

	// Custom tags
	tags = merge(var.account_info.tags, var.tags, {
		Name = local.full_name_tag
	})

	// Make sure we don't change OriginalActor tag
	lifecycle {
		create_before_destroy = true

		ignore_changes = [
			"tags[\"OriginalActor\"]"
		]
	}
}

resource "aws_security_group_rule" "egress" {
	type = "egress"

	from_port = 0
	to_port = 0

	protocol = -1

	cidr_blocks = [
		"0.0.0.0/0"
	]

	description = "Allow all outbound traffic"

	security_group_id = aws_security_group.this.id
}

resource "aws_security_group_rule" "ingress" {
	type = "ingress"

	from_port = 0
	to_port = 0

	protocol = -1

	description = format("Allow %s traffic", local.full_name)

	security_group_id = var.cluster.asg.security_group
	source_security_group_id = aws_security_group.this.id
}
```

### Debug Output

[debug.log](https://github.com/hashicorp/terraform/files/2979053/debug.log)

### Crash Output

N/A

### Expected Behavior

When running an apply on one machine, using a AWS IAM User and S3 as remote state, I would expect another user on another machine running an apply on the same code to show no changes required.

### Actual Behavior

The user who did not create the resources initially is always showing changes required, even following a successful apply, the same required changes are shown every time a subsequent plan or apply is run. However running the terraform as the original user shows no changes required.

Output plan as follows:

```
  # module.task.aws_security_group.this will be updated in-place
  ~ resource "aws_security_group" "this" {
        arn                    = "arn:aws:ec2:eu-west-2:257029124132:security-group/sg-0675e294aa312c163"
        description            = "INFRA/ATW/APP1/TFTEST Load Balancer"
        id                     = "sg-0675e294aa312c163"
        name                   = "atw-app1-tftest-20190318152031666700000001"
        name_prefix            = "atw-app1-tftest-"
        owner_id               = "000000000000"
        revoke_rules_on_delete = true
        tags                   = {
            "Account"       = "INFRA"
            "CostCode"      = "PRJ0000000"
            "Environment"   = "APP1"
            "FeatureBuild"  = "NONE"
            "Generation"    = "3"
            "LastActor"     = "Alice Jone"
            "Name"          = "INFRA/ATW/APP1/TFTEST"
            "OriginalActor" = "Bob Smith"
            "Owner"         = "ATW"
            "ProjectCode"   = "00000000"
        }
        vpc_id                 = "vpc-xxxxxxxxxxxx"

      - egress {
          - cidr_blocks = [
              - "0.0.0.0/0",
            ] -> null
          - description = "Allow all outbound traffic" -> null
          - from_port   = 0 -> null
          - protocol    = "-1" -> null
          - self        = false -> null
          - to_port     = 0 -> null
        }
      + egress {
          + cidr_blocks      = [
              + "0.0.0.0/0",
            ]
          + description      = "Allow all outbound traffic"
          + from_port        = 0
          + ipv6_cidr_blocks = []
          + prefix_list_ids  = []
          + protocol         = "-1"
          + security_groups  = []
          + self             = false
          + to_port          = 0
        }

      + ingress {
          + cidr_blocks      = [
              + "0.0.0.0/0",
            ]
          + description      = "Allow HTTP traffic"
          + from_port        = 80
          + ipv6_cidr_blocks = []
          + prefix_list_ids  = []
          + protocol         = "tcp"
          + security_groups  = []
          + self             = false
          + to_port          = 80
        }
      - ingress {
          - cidr_blocks = [
              - "0.0.0.0/0",
            ] -> null
          - description = "Allow HTTP traffic" -> null
          - from_port   = 80 -> null
          - protocol    = "tcp" -> null
          - self        = false -> null
          - to_port     = 80 -> null
        }

        timeouts {}
    }
```

### Steps to Reproduce

* As first user
    1. terraform init
    2. terraform apply
* As second user
    1. terraform init
    2. terraform apply

### Additional Context

This has been tested using Terraform Enterprise as the remote state as well as S3 remote state. We have also tested this by destroying the entire environment and the different test users being the 'initial' applier.

As you can see from the output plan, the ingress and egress rules appear to be applied directly to the `aws_security_group` resource, when in fact they are applied as separate `aws_security_group_rule` resources.

**Comment by jbardin** [comment]
Hi @m13t,

Can you verify that the configuration being run by both users matches exactly? The only reason I can see for this to happen is if one config has the rules defined in the `aws_security_group` and the other has the config shown above.

**Comment by m13t** [comment]
Hi.

Yes I can confirm this is using the exact same commit of the code. We see this on more than just the security groups though. That was just one resource example.

**Comment by jbardin** [comment]
Thanks for the update.

Taking the above config and running from 2 different locations against the same backend state yields no differences. 

The only way I can imagine getting the `+ egress {` and `+ ingress {` additions is if the config being referenced had those blocks defined within the `aws_security_group`. The fact that the `Allow all outbound traffic` description is present is good confirmation that it's defined in the config, rather than being a difference between the zero values of the block.

Is it possible that you're using modules here, and the source has somehow diverged from the local cache? The `init` command does no update modules by default, and you can use the `-upgrade` flag to pull new versions.

**Comment by m13t** [comment]
Hi

Yes we’re using modules, and this is extracted from a larger project to try keep things simple on the issue.

We did test this by checking out the code from scratch and initialising from scratch too. Even with a completely new state we saw the same problem.

There are definitely no security group rules added on the security group resource itself, we only add rules using the dedicated security group rule resource. This is mainly why I raised this as a big rather than suspect it was our code. I am happy to provide the wider project of that is of any help?

**Comment by jbardin** [comment]
Yes, I think we're going to need a more complete example here. Running the above config in isolation is going to work as expected. Can you provide access to the project modules? If not, we need to construct a reproduction that has the same overall structure.

**Comment by m13t** [comment]
Hi @jbardin,

I have took a much bigger extract from the test project we've encountered this issue on. Contains all modules and test code bar a couple of non-essential pieces.

Further details enclosed in the GPG Zip file

[20731.zip.gpg](https://github.com/hashicorp/terraform/files/2985324/20731.zip)

**Comment by jbardin** [comment]
Sorry, even with this extended example, I'm not seeing any way that the above updates could happen with the same configuration. What I ran was stripped down considerably to make it easier to setup and reason about, but still included everything related to the above `aws_security_group`.

I'm going to look into the provide itself, and see if there's any chance it's attempting to do something it shouldn't.

**Comment by m13t** [comment]
Hi @jbardin,

Thank you for taking the time to look in to it. I will see if I can get to the bottom of it too and provide a more concise concrete problem.

The problem is this only occurs when this is being run as different users (IAM user credentials), it does not happen when just doing subsequent plans as the same user. Somewhat difficult to track down.

However, given the example code provided and the output in the initial post, you can see that the expected out of security group is not right with regards to removing and re-adding those rules.

I’ll continue to investigate and post any further findings.

**Comment by jbardin** [comment]
Hi @m13t,

While I don't have a reproducible example at the moment, it looks like this is likely be the result of the provider attempting to reconcile standalone rules with those defined inline in the security group itself.

The `ingress` and `egress` rules being "computed" blocks (and `TypeSet` on top of that), is going to cause problems regardless, so I'll move this over to the aws provider so they can review how to better handle the situation.
