### ISSUE TITLE
Empty execution plan when trying to remove legacy `schema.SchemaConfigModeAttr` attribute

### ISSUE THREAD

**Issue by chrisst** [hashicorp/terraform#20743]
### Terraform Version

Running latest terraform version on master as of 3/18/2019

### Terraform Configuration Files

```hcl
resource "google_compute_instance_from_template" "tpl" {
  name           = "instance-from-template"
  zone           = "us-central1-a"

  # scheduling = [{
  #   # on_host_maintenance = "MIGRATE"
  #   automatic_restart   = true
  #   preemptible = false
  # }]
  scheduling = []

  source_instance_template = "${google_compute_instance_template.default.self_link}"

  // Override fields from instance template
  can_ip_forward = false
  labels = {
    my_key       = "my_value"
  }
}
```

### Debug Output
https://gist.github.com/chrisst/ecb3faa696965be29d07f8895585ca73

### Behavior
I'm playing around with the new `SchemaConfigModeAttr` syntax to see how it would work for Optional/Computed blocks. In 0.11 we were able to specify and empty list which would trigger an update where we reset the values to the API defaults. I was attempting to reproduce the same behavior with 0.12 syntax by defining a block during the initial create, then attempting to remove it in a subsequent update. The result was an empty execution plan that I was unable to `apply`.

### Steps to Reproduce
I'm running a custom build of the google provider with the `scheduling` attribute set as:
```
"scheduling": {
				ConfigMode: schema.SchemaConfigModeAttr,
				Type:       schema.TypeList,
				...
```
Next run a single `apply` with the full scheduling block uncommented to create the `google_compute_instance_from_template`.

Comment out the full `scheduling` block and uncomment the empty list syntax and run `plan`.

**Comment by apparentlymart** [comment]
I think this may possibly be the same as #20750, but with the actual panic message being eaten/suppressed somehow. That other issue seems to be in the diff _renderer_, and the fact that in this issue the output seems to abort right before the rendered diff would normally be shown, and that this is also related to changes to a list, makes me suspect the two are connected.

Was there a `crash.log` file written out to disk when this strange behavior occurred?

**Comment by apparentlymart** [comment]
Hi again, @chrisst!

The other issue #20750 is now fixed in the master branch and based on the behavior I saw while working on that I strongly suspect that you saw the same issue here, even though I'm not sure why the panic output wasn't visible.

If possible, could you give this another try with a `terraform` built from the master branch? I think it should work as expected with that fix in place; if not, I'll try to dig a little deeper to see what else is going on here.

**Comment by chrisst** [comment]
I didn't see a crash.log on the previous run but it looks like the latest version of master is now showing the diff as expected. Thanks!
