### ISSUE TITLE
Terraform is filtering out any provider log messages that are in JSON-format

### ISSUE THREAD

**Issue by alexng-canuck** [hashicorp/terraform#20758]
### Terraform Version

```
v0.11.7
v0.12.0-beta1
```
### Description
In the OCI provider, we log lines like this which are in JSON:

```
{"cidrBlock":"10.0.0.0/16","compartmentId":"blahblahblah","displayName":"vcn1","dnsLabel":"vcn1"}
```

Such lines are treated by the `logStderr` function as JSON and go through further processing in the go-plugin client code. See https://github.com/hashicorp/terraform/blob/50a101afbd3cabbd2ed1adce02213ae16e894f5d/vendor/github.com/hashicorp/go-plugin/client.go#L973

This extra processing is presumably for handling hclog-specific data. The problem with this logic is that it assumes all JSON-format log lines have hclog data. When the log line does not have such data (as in our case), then it is eaten up and not logged to stderr. 

### Expected Behavior

```
2019-03-18T17:39:01.378-0700 [DEBUG] plugin.terraform-provider-oci: X-Content-Sha256: UOiLJWLTRDyRlxbvWBTdds6OhOLU1stXt7xMCihxqsY=
2019-03-18T17:39:01.379-0700 [DEBUG] plugin.terraform-provider-oci: Accept-Encoding: gzip
2019-03-18T17:39:01.379-0700 [DEBUG] plugin.terraform-provider-oci: 
2019-03-18T17:39:01.379-0700 [DEBUG] plugin.terraform-provider-oci: {"cidrBlock":"10.0.0.0/16","compartmentId":"blahblahblah","displayName":"vcn1","dnsLabel":"vcn1"}
2019/03/18 17:39:01 ......
```

### Actual Behavior

The above JSON line is omitted.

### Additional Context

We rely on these log messages to return specific details about requests to OCI services. Having these messages omitted from logs introduces problems with troubleshooting and debugging customer issues.

**Comment by jbardin** [comment]
Hi @alexng-canuck,

As you can see, raw json is expected to be consumed by hclog. The textual logging convention in all providers is that every line start with a log-level tag, e.g. `[DEBUG] `. This allows filtering of the logs within terraform, and will help with the eventual planned migration to hglog to get structured logging through out terraform. 

In the meantime, I do think that go-plugin might be able to add a default output level for log lines that don't have the correct fields in the json.

**Comment by rileykarson** [comment]
This (or a related problem) is an issue for the Google provider as well; if I recall the issue, we were attempting to allow OAuth logins through the provider but Terraform swallowed the print statements directing users to a web page to perform the interactive signin required.

**Comment by jbardin** [comment]
Hi @rileykarson,

That's a slightly different issue. The provider stdout is reserved for use in the plugin protocol, and is piped through the handshake mechanism. Once we have structured logging we'll better be able to surface critical log messages to the user, but there is no solution at the moment for directly presenting UI messages from a plugin.

How best to handle that would be a separate discussion.

**Comment by kilokahn** [comment]
hey @jbardin - thanks for the quick response to the original filtering problem! In this case, the dependency was using the standard https://golang.org/pkg/net/http/httputil/#DumpRequest for logging and it was adding the newlines itself. For my understanding, I don't think you are suggesting that we change how we perform the logging, right?  If yes, do you have any timeline in mind for the fix so that this is not filtered out? Any other workaround will also be appreciated. Thanks!
