### ISSUE TITLE
Feature Request: Resources implicitly refer to their "identity" attributes

### ISSUE THREAD

**Issue by curiositycasualty** [hashicorp/terraform#20779]
### Use-cases
We've all made this mistake in terraform:
```
resource "aws_route53_zone" "internal" {
  name = "boop.int"
}

resource "aws_route53_record" "bleep_internal" {
  zone_id = "${aws_route53_zone.internal}"
  name    = "bleep.bloop.int"
  type    = "A"
  ttl     = "300"
  records = ["${aws_instance.bleep.private_ip}"]
}
```

Did you spot it? `zone_id` had a resource passed into it instead of that resource's "zone_id".
Many (if not most) AWS resources have this same pattern of one central "attribute" that define a semantic "identity" for that resource. (`vpc-id`, `instance-id`, `subnet-id`, etc.).

### Proposal
When terraform encounters a full resource passed in where a single attribute of a resource was expected, attempt to ascertain the "identity" attribute of the passed-in resource and supply that instead.

**Comment by mildwonkey** [comment]
Hi @curiositycasualty ! Thank you for submitting this feature request.

In terraform v0.12, a naked reference to a resource returns an *object* representing that resource, and we don't want to make a special-case conversion of that for a few reasons: 
* it's not compatible with terraform's principles (explicit is better than implicit)
* implicit conversion of the resource object to a string would cause surprising behavior all over. 
* Terraform only knows what the provider tells it, and there's no guarantee that  `id` is a useful reference or that terraform can "guess" the identifying attribute. 

Based on that, I am going to close this issue. I'm sorry for the unsatisfying response in this instance, and I hope that you continue to open feature requests. Thanks again!
