### ISSUE TITLE
TF 0.11.13 windows crash during init

### ISSUE THREAD

**Issue by aftabalam01** [hashicorp/terraform#20773]
Hi there,

terraform v 0.11.13 crashed during init.
2

### Terraform Version
Terraform v0.11.13
+ provider.aws v2.1.0
+ provider.template v2.1.0

```
...
```

### Terraform Configuration Files

```
...
```

### Crash Output

[terragrunt] [c:\workdir\xxxxperformance\terraform] 2019/03/20 15:46:10 Running command: terraform --version
[terragrunt] 2019/03/20 15:46:11 Reading Terragrunt config file at c:/workdir/eats-performance/terraform/terraform.tfvars
[terragrunt] 2019/03/20 15:46:11 Running command: terraform init -backend-config=region=us-west-2 -backend-config=dynamodb_table=xxxx-terraform-lock-table -backend-config=encrypt=true -backend-config=bucket=xxxxxxx-remote-state -backend-config=key=dev/terraform.tfstate
[0m[1mInitializing modules...[0m
- module.account
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc000034640, 0x12, 0x33c4180, 0xc00037e3e0, 0x1, 0xc000106830, 0xc000034700, 0x5930000, 0x0, 0x11, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc000034640, 0x12, 0x33c4180, 0xc00037e3e0, 0x1, 0xc000106830, 0xc000034720, 0x13, 0x2, 0x2, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
github.com/hashicorp/terraform/config/module.Storage.findModule(0xc000034640, 0x12, 0x33c4180, 0xc00037e3e0, 0x1, 0xc000106830, 0xc000034720, 0x13, 0x0, 0x0, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc0002e6200, 0xc0003024e0, 0xc0002e6238, 0xb28719, 0x300d660)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc0002e6200, 0xc0003024e0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
github.com/hashicorp/terraform/command.getModules(0xc000388820, 0xc0003b40f0, 0x25, 0xc0003b4b01, 0x23, 0xc0003b4b10)
        /opt/gopath/src/github.com/hashicorp/terraform/command/get.go:84 +0x127
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000388820, 0xc00009a020, 0x5, 0x6, 0xc0003150e0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/init.go:179 +0xac7
github.com/mitchellh/cli.(*CLI).Run(0xc000346500, 0xc000346500, 0xc0001b7d20, 0x1)
        /opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[terragrunt] 2019/03/20 15:46:12 Hit multiple errors:
exit status 2

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`

**Comment by apparentlymart** [comment]
Hi @aftabalam01! Sorry for this crash and thanks for reporting it.

It looks like you have hit the same issue as in #20773. You can find a workaround in the comments of that issue. I'm going to close this one just to consolidate the discussion over there.

**Comment by aftabalam01** [comment]
@apparentlymart thanks. workaround worked for me.
