### ISSUE TITLE
GCS backend support for access_token auth?

### ISSUE THREAD

**Issue by rolyv** [hashicorp/terraform#20785]
### Current Terraform Version

```
v0.11.11
```

### Use-cases
I'm using Vault with the GCP secrets backend to provide access tokens for use with the `google` terraform provider. The suggested/preferred way to supply credentials to `google` provider is via the `access_token`,  but it doesn't seem like I can use that same scheme with the `gcs` backend. It requires a json key. 

### Attempted Solutions
I tried supplying `access_token` to the gcs backend and it yelled at me that it is an `invalid or unknown key`

### Proposal
Have parity with the `google` (and/or `google-beta`) auth options, specifically support for access_tokens.

**Comment by hixichen** [comment]
Found another issue with gcs access_token.
https://github.com/hashicorp/terraform/issues/24392
