### ISSUE TITLE
Template hooks

### ISSUE THREAD

**Issue by Fodoj** [hashicorp/terraform#2078]
Currently there is no support for OpsWorks. For my use cases fastest solution would be to execute a ruby script using aws-sdk after template run. Is there a way to execute some command after each run and pass outputs to it?

**Comment by radeksimko** [comment]
> Currently there is no support for OpsWorks.

As you already probably noticed, there's a PR for this: #1892

To your last question:

> Is there a way to execute some command after each run and pass outputs to it?

Is [`local-exec` provisioner](https://www.terraform.io/docs/provisioners/local-exec.html) what you're looking for?

There's also a debate going on about "null-resource" which would effectively be very similar to `local-exec`, but wouldn't have to be attached to any specific resource = it would be a stand alone building block.

There's already an un-documented work around in https://github.com/hashicorp/terraform/issues/580#issuecomment-63877449 but the ideal goal is discussed in https://github.com/hashicorp/terraform/issues/1181

We generally track all AWS features in https://github.com/hashicorp/terraform/issues/28 and attached spreadsheet (feel free to add your upvote there) and/or related PRs so I'm closing this.

**Comment by Fodoj** [comment]
Indeed, null-resource is something I am looking for.
