### ISSUE TITLE
Module installer doesn't honor explicit build metadata in version constraint

### ISSUE THREAD

**Issue by MrStrix** [hashicorp/terraform#20814]
### Terraform Version

```
Terraform v0.11.13
```

### Terraform Configuration Files

```hcl
module "aks" {
  source  = "adfinis-forks/aks/azurerm"
  version = "=0.9.0+1.4970527"

  CLIENT_ID     = "testtest"
  CLIENT_SECRET = "testtest"
}
```

### Debug Output

https://gist.github.com/MrStrix/2d3991857fb3363d150ea5fb70172c41

### Expected Behavior

Terraform should pull the correct version as specified. (version `0.9.0+1.4970527`). It should also pull the latest release (e.g. the release with the highest version number which would be `0.9.0+1.4970527` at the time of writing) when specifying a constraint like `version = ">=0.9.0"`.

### Actual Behavior

Terraform pulls a seemingly random version of the module (version `0.9.0+0.6babc9f`)

### Steps to Reproduce

1. Create `main.tf` like described above
2. run `terraform init`

### Additional Context

The module is in the registry: https://registry.terraform.io/modules/adfinis-forks/aks/azurerm/0.9.0
and the releases are on github: https://github.com/adfinis-forks/terraform-azurerm-aks/releases

**Comment by fivemok** [comment]
Looks this is due to metadata not being checked during version comparison: [go-version/version.go:128](https://github.com/hashicorp/go-version/blob/master/version.go#L129).

**Comment by pselle** [comment]
This was closed by https://github.com/hashicorp/terraform/pull/21640
