### ISSUE TITLE
connection block diagnostics report resource as source

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#20829]
If the `diagnostic.Format` function gets an `*hcl.Diagnostic` for a missing required value in a connection block, the empty code snippet is turned into the resource block, rather than the connection block.

A missing `host` field show:

```
Error: Missing required argument

  on main.tf line 1, in resource "null_resource" "foo":
   1: resource "null_resource" "foo" {

The argument "host" is required, but no definition was found.
```

While the actual diagnostic `Source()` is:

```
&tfdiags.SourceRange{
    Filename:"main.tf",
    Start:tfdiags.SourcePos{Line:9, Column:6, Byte:171},
    End:tfdiags.SourcePos{Line:9, Column:6, Byte:171},
}
```

**Comment by mildwonkey** [comment]
Found it in [hcl2/hcl/hclsyntax](https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/structure.go#L146):
```
if attrS.Required {
	diags = append(diags, &hcl.Diagnostic{
		Severity: hcl.DiagError,
		Summary:  "Missing required argument",
		Detail:   fmt.Sprintf("The argument %q is required, but no definition was found.", attrS.Name),
		Subject:  b.MissingItemRange().Ptr(),
	})
}
```

Specifically `b.MissingItemRange().Ptr()` points to the `EndRange`
I'll see if I can convince that function to recognize when it's in an e.g. connection block and return a more appropriate source.

**Comment by radeksimko** [comment]
This might be related to https://github.com/hashicorp/hcl2/issues/93

**Comment by mildwonkey** [comment]
Yes indeed, this is a dupe, thanks!
