### ISSUE TITLE
Delete of dependent resource doesn't always honor ordering

### ISSUE THREAD

**Issue by kilokahn** [hashicorp/terraform#20823]
### Terraform Version

```
Terraform v0.11.7
```

### Terraform Configuration Files

```hcl
resource "oci_waas_certificate" "test_certificate" {
  #Required
  certificate_data = ""
  compartment_id   = "${var.compartment_ocid}"
  private_key_data = ""

  #Optional
  display_name                   = "${var.certificate_display_name}"
  is_trust_verification_disabled = true
}

resource "oci_waas_waas_policy" "test_waas_policy" {
  #Required
  compartment_id = "${var.compartment_ocid}"
  domain         = "somethingnew42.oracle.com"

  policy_config {
    #Optional
    certificate_id   = "${oci_waas_certificate.test_certificate.id}"
    is_https_enabled = true
    is_https_forced  = true
  }
}
```

### Debug Output
https://gist.github.com/kilokahn/12bd576727b59842154eb790504d04ba

### Expected Behavior

oci_waas_waas_policy.test_waas_policy should be destroyed before
oci_waas_certificate.test_certificate

### Actual Behavior

Both oci_waas_waas_policy.test_waas_policy and oci_waas_certificate.test_certificate were being destroyed simultaneously

### Steps to Reproduce

We are going to put the acceptance test where we see this behavior on our github repo soon, and you can run that to see the problem in action.

### Additional Context
We haven't seen this problem (yet) when running with a standalone .tf file. Tagging @paultyng for this

### References
https://github.com/hashicorp/terraform/issues/20196 may be related to this.

**Comment by danieldreier** [comment]
@kilokahn thank you for this issue report. We're aware of a variety of delete ordering issues, and would like to investigate and fix them. This specific issue report doesn't include reproduction steps, so there isn't a clear next step. Are you still planning on posting steps to reproduce? We're unable to investigate further without reproduction steps.

**Comment by danieldreier** [comment]
@kilokahn I'm just reviewing this ahead of our meeting, and wanted to check if you've had time to put together a reproduction case, or to verify whether this is still happening in the current terraform release. Please let me know if there's any help we can provide to come up with a reproduction case.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
