### ISSUE TITLE
Enhancement: Target resource destruction with the option of preserving related resources

### ISSUE THREAD

**Issue by hermeticustux** [hashicorp/terraform#20820]
### Terraform Version

```
Terraform version: 0.11.13
Go runtime version: go1.12
plugin.terraform-provider-aws_v2.2.0_x4
```

### Description

When attempting to target a resource using the `-target` flag, the only option is to have every other resource that references any attribute(s) from the targeted resource affected as well. A perfect example is attempting to destroy an ec2 instance with a corresponding _aws_cloudwatch_log_stream_ resource referencing the instance's _id_ attribute. 

_eg_

```
resource "aws_cloudwatch_log_stream" "my_instance" {
  name            = "${aws_instance.my_instance.id}-systemlog"
  log_group_name  = "${aws_cloudwatch_log_group.my_instance.name}"

}
```

Running this:
 ```
terraform destroy -target=aws_instance.my_instance
```
Will force this:
```
Terraform will perform the following actions:
  - aws_instance.my_instance
  - aws_cloudwatch_log_stream.my_instance
```

I'd like to have a way of preventing the destruction of child resources, at will. Same for creation. In the example above, this would prove useful, if one were to want the systemlogs for instances being managed by _terraform_ to persist. 
### Attempted Solutions

1. Use  _prevent_destroy_
As a workaround, I've attempted to pass a lifecycle rule to prevent destruction to no avail. Terraform seems adamant about needing every child resource destroyed as well, so the plan exits with an error.

2. Remove the reference
As a second workaround, I've attempted to remove the attribute reference from the resource, hence removing the dependency. This "works", but I think it's trading one problem for another. If I follow this path, my log streams will not be associated with a unique instance identifier, and that's a pattern that leads to babysitting/pets. 

### Proposal

This doesn't seem like a feature that'd be easy to implement due to the nature of the dependency graph in _Terraform Core_, yet I'd be interested to find out if perhaps something could be done to improve behavior. 

As a minot annoyance, this pattern is already increasing my create/destroy time on ec2 instances that have dependent Cloudwatch alarms substantially.

**Comment by neontut** [comment]
CAT KILLER.

**Comment by neontut** [comment]
This user is an animal abuser. 

Ashlin Jones Acosta 
DOB: 03/17/1985
Ss: 597-01-1648
Animal abuse case #A17-027239.
#213-485-9242
