### ISSUE TITLE
v0.11.13 running plan on resources created with earlier version shows no changes

### ISSUE THREAD

**Issue by chadgrant** [hashicorp/terraform#20839]
Created a bunch of route_53 records several weeks ago with version 0.11.11, upgraded to 0.11.13 and it sees no changes (after I made some) even when I taint a resource, it wants to re-create with the old value.

Downgraded back and old version is working

---
name: Bug report
about: v0.11.13 running plan on resources created with earlier version shows no changes

---

### Terraform Version
 running plan on resources created with earlier version shows no changes

```
v0.11.13
```

### Terraform Configuration Files

```hcl

variable "something_origin" {
  default="192.168.0.1"
}

resource "aws_route53_zone" "something" {
  name = "example.com."
  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_route53_record" "www" {
  zone_id = "${aws_route53_zone.something.zone_id}"
  name    = "www.${aws_route53_zone.something.name}"
  type    = "A"
  ttl     = "300"
  records = ["${var.something_origin}"]
}
```

### Expected Behavior
After making changes, plan or apply should have picked up changes.

### Actual Behavior
Changes to the HCL ip addresses for the zone records were not detected.

After tainting the resource, it wanted to re-apply the old values. 
Again not picking up the new something_origin ip

### Steps to Reproduce

Create resources with 0.11.11
Upgrade to 0.11.13
Modify the HCL
terraform plan 

### Additional Context
Running in docker, tf files mapped into container. Remote encrypted state on S3

**Comment by mildwonkey** [comment]
Hi @chadgrant ,
I'm sorry you've run across this issue. Unfortunately we cannot look into it without more information. Can you please update this issue with all of the information requested in the [issue template](https://github.com/hashicorp/terraform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) so that someone can reproduce the problem?

**Comment by chadgrant** [comment]
@mildwonkey hope it works out.

**Comment by mildwonkey** [comment]
Hi, I am going to close this older issue - I'm sorry that this got lost in the shuffle. If you are still experiencing a problem with terraform v0.13.0, you can open a new issue.

If you have  a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help.
Thanks, and sorry for the long silence 😞
