### ISSUE TITLE
terraform 0.12 remote state : Attribute name required 

### ISSUE THREAD

**Issue by riteshnanda09** [hashicorp/terraform#20835]
### Terraform Version
```
Terraform v0.12.0-beta1
+ provider.google v2.1.0
```

### Terraform Configuration Files
```hcl
terraform {
  backend "gcs" {
    bucket = "tf-state"
    prefix = "bootstrap/state"
  }
}
```

### Debug Output
```./terraform init

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.


2019/03/26 14:06:14 [TRACE] backendMigrateState: need to migrate from "gcs" to "gcs" backend config
2019/03/26 14:06:14 [TRACE] backendMigrateState: migrating "default" workspace to "default" workspace

Error: Error loading state:
    2 problems:

- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.

Terraform failed to load the default state from the "gcs" backend.
State migration cannot occur unless the state can be loaded. Backend
modification and state migration has been aborted. The state in both the
source and the destination remain unmodified. Please resolve the
above error and try again.
```

### Steps to Reproduce
1. `terraform init`

### Actual Behavior
With Terraform 0.11 it  works. 

With terraform 0.12 it gives very minimal information to what is the problem with the state file. Trying in Trace and debug mode is the same . Any way i can know which attribute it is erroring out.

**Comment by mildwonkey** [comment]
Hi @riteshnanda09 !
Thanks for reporting this issue, and I'm sorry you're experiencing it. I'd like to try and reproduce it so we can figure out what's going on!

You can run `TF_LOG=DEBUG terraform init` to get (a lot) more information from terraform. It would be helpful if you share the output of that command (as a gist, please, and remove any sensitive information), and the rest of your terraform configuration files, including the prior backend configuration. It would be great if we could come up with a "minimal" reproduction case. 

Finally, can you share the precise minor version of terraform 0.11 is working for you? The current latest is `0.11.13`.

Thanks!

**Comment by riteshnanda09** [comment]
Here is the Debug output with terraform 0.12, its small so not sharing using gist.
```
 TF_LOG=DEBUG ./terraform init
2019/03/28 09:35:38 [INFO] Terraform version: 0.12.0 beta1
2019/03/28 09:35:38 [INFO] Go runtime version: go1.11.5
2019/03/28 09:35:38 [INFO] CLI args: []string{"terraform", "init"}
2019/03/28 09:35:38 [DEBUG] Attempting to open CLI config file: .terraformrc
2019/03/28 09:35:38 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/03/28 09:35:38 [INFO] CLI command args: []string{"init"}
Initializing modules...
2019/03/28 09:35:38 [DEBUG] Module installer: begin constraint-policies
2019/03/28 09:35:38 [DEBUG] Module installer: begin pubsub

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.



Error: Error loading state:
    2 problems:

- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.

Terraform failed to load the default state from the "gcs" backend.
State migration cannot occur unless the state can be loaded. Backend
modification and state migration has been aborted. The state in both the
source and the destination remain unmodified. Please resolve the
above error and try again.
```
[Here is the gist to main.tf](https://gist.github.com/riteshnanda09/070ee14a20aa8721ab2ee27aab2cf29c.js)


This modules runs fine with version 
``` 
Terraform v0.11.10
+ provider.google v1.17.1
+ provider.random v2.1.0
```

**Comment by mildwonkey** [comment]
Thank you for the additional information, @riteshnanda09.

🤔  This looks like it might be tricky to reproduce, but I have a few ideas. This error seems to happen when the state upgrader callers one of the `addrs.Parse...` functions, which is during provider parsing:

https://github.com/hashicorp/terraform/blob/1baa1b907ef51ae752b46f8baa16c93c71b0d701/states/statefile/version3_upgrade.go#L99

Are there any `provider` blocks in the modules you call from your `main.tf`? I'd be curious to see if any of them look unusual. You can also run `terraform state pull` to manually download a copy of your statefile and peek in it for anything that looks "unusual", especially in any "provider" blocks.

I'm sorry to use such a vague term as "unusual", but hopefully we can tease out some information that will help me track down the issue. Thanks again!

**Comment by maciejdrozdzowski** [comment]
I have a similar issue with TF 0.12 and the AWS provider 1.60.0-dev20190216h00-dev.

I get 
```
Failed to refresh state: 7 problems:

- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.
```
and that's on both `plan` and `state pull`.

I looked at the logs, as per your suggestion above, and there's nothing of interest.
I looked at the state and haven't spotted anything "unusual".

I'm trying to upgrade from 0.11.11 to 0.12.

@mildwonkey would you have any other ideas? Any other place to look for potential issues?

**Comment by mildwonkey** [comment]
Hi @maciejdrozdzowski, thanks for chiming in and I'm sorry you've also run across this.

The first guess I have involves provider aliases. In versions 0.11 and earlier it was possible have a provider alias with `.`, like `mycloud-us.east.1`, but in 0.12 the alias can only have letters, numbers or hyphens: `mycloud-us-east-1`.

That's only a loose guess. If you have a terraform config file that can be used to reproduce this upgrade issue I'd love to dig in.

**Comment by maciejdrozdzowski** [comment]
@mildwonkey
I actually only have one provider of each type, without aliases

```
provider "aws" {
  version = "1.60.0-dev20190216h00-dev"

  region = "ap-southeast-2"

  assume_role {
    role_arn = "arn:aws:iam::***"
  }
}

provider "archive" {
  version = "~> 1.0"
}

provider "template" {
  version = "~> 1.0"
}
```

I cannot really share the code - too much work-specific stuff going on in there :)

**Comment by mildwonkey** [comment]
Hi @riteshnanda09  and @maciejdrozdzowski ,
Sorry for the silence on this issue. I am still trying to reproduce the problem and could use your help. 

The error message indicates that the error occurs while parsing a provider, resource or dependency address. I understand that you cannot share your entire state or configuration - I would not ask you to - but perhaps you could help me by getting the names of any resources, providers and dependencies, search for those names in both the old and new state, then share the values of the attributes you find? 

Unfortunately, since `terraform state pull` is failing you will need to get the state file directly from the backend. I am sorry that I don't have a simpler way to dig into this 😞 

If either of you are able to reproduce this issue with a simplified configuration that does not contain any sensitive information, please share it here so that I can reproduce locally. For instance @riteshnanda09 , if it is possible to isolate this error to a single module in the main.tf you've shared, and share that module (or a sanitized version which causes the same error) I can dive into it here.

Thanks, and sorry again for the odd error.

**Comment by kshpytsya** [comment]
I have encountered a similar issue (with `s3` state backend), and for me the culprit was the following `depends_on`:

```json
                 "aws_db_subnet_group.one": {
                     "type": "aws_db_subnet_group",
                     "depends_on": [
                         "aws_subnet.one",
                         "aws_subnet.one.1",
                         "aws_subnet.one.2"
                     ],
```

Once I edited it to `"depends_on": []`, the the state was successfully loaded by terraform 0.12.

If that is of any relevance, I have also manually edited the state due to reorganization of my Terraform code:

```patch
     "modules": [
         {
             "path": [
-                "root",
-                "modulename"
+                "root"
             ],
```

I.e. the `v0.11.13` state was created with all the resources defined in a `modulename` module, state was manually edited, and `v0.12` was executed with all resources defined in root module giving the hoped for:

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

All of this is done on sacrificial resources, so I can easily reproduce this should any extra investigation be needed.

**Comment by nicolasochem** [comment]
I have the same problem when doing `terraform plan`

```-----------------------------------------------------
2019/05/23 16:31:14 [DEBUG] [aws-sdk-go]
Error refreshing state: 4 problems:

- Attribute name required: Dot must be followed by attribute name.
- Attribute name required: Dot must be followed by attribute name.
- Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
- Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
```

I can't share the code but I don't know where to start looking. Can we have file and line information about this error. I will hardcode terraform 0.11 in my pipeline until shis is fixed.

**Comment by luhn** [comment]
I've encountered this as well.  I had some resources that started with a number (renamed after upgrading), which apparently don't play nicely with the state.  I manually downloaded to stated and removed the offending resources from any `depends_on` they showed up in.  It worked after this.

**Comment by apparentlymart** [comment]
Hi all!

Let's use hashicorp/terraform#21435 to discuss the ongoing issues of this type. The PR associated with _this_ issue addressed one cause of the error, but it seems like there is at least one other cause we need to investigate and fix. I asked the submitter of hashicorp/terraform#21435 to try to gather some additional info from the state file; if you have similar info to share to answer that question, that'd be very helpful in figuring out what rule is missing from the state upgrader. Thanks!

**Comment by rismoney** [comment]
Not sure if this is a separate issue:  Just trying to run init as nothing was previously flagged as on checklist...
I am using vsphere provider.

```
Error: Attribute name required

  on ..\modules\vsphere_win10\workstation.tf line 77, in resource "vsphere_virtual_machine" "wks":
  77:     ignore_changes ="wait_for_guest_net_routable","extra_config","annotation","wait_for_guest_net_timeout","power_state","clone.0.template_uuid"]
`

It looks like it doesn't like the `0` in `clone.0.template.uuid`

**Comment by maciejqantas** [comment]
@mildwonkey, apologies for ghosting you - this slipped through the cracks.
I have not attempted to resolve this again, I gave up on 0.12 for the time being and promised myself to come back to it one day.

**Comment by krishnam-ntnx** [comment]
i have same issue with 0.12 version but works fine with "tags.%" - Error: Attribute name required. 
This works fine with terrafor 0.11 version
