### ISSUE TITLE
Terraform apply/destroy just prints help

### ISSUE THREAD

**Issue by paulbygrave** [hashicorp/terraform#20836]
Working through a LinuxAcademy tutorial, I have somehow got myself in a situation after creating some modules where terraform inits fine, but any attempt to run plan/apply/destroy just results in the help statement being printed with no indication where the error lies.

I have no idea where in my code the problem is, I've visually scanned everything but would have thought the error handling would be a bit more indicative?

Full terminal print here - https://gist.github.com/paulbygrave/87d944a10c8aed07be207f41c14bf952

Any help appreciated.

**Comment by mildwonkey** [comment]
Hi @paulbygrave !
I'm sorry you've run across this issue. I can think of a few (annoying!) cases where `terraform plan` will do this without any helpful message (and I can report that terraform 0.12, currently in beta, gives much better error messages).

A common situation that's caught me up before is if there is a `.tfvars` file with a syntax error. In that case, terraform 0.11 and earlier simply prints the help message without any indication of the problem.

Running `terraform validate` or even `terraform fmt` might help narrow down the problem. You could also update this issue with the contents of your terraform configuration files so someone can take a look.

**Comment by paulbygrave** [comment]
@mildwonkey thanks for the input, I'll bear the tfvars file in mind if it happens again. Luckily I've been working exclusively in a repo so I ended up blowing the local repo away and pulling it from a previous state, lost about an hour in total but the issue didn't re-occur when following the steps. I wasn't familiar with `terraform fmt`, will look that up!

Issue can be closed as it seems an enhancement is on the way in new version.

**Comment by paulbygrave** [comment]
Meant to "close and comment" above.
