### ISSUE TITLE
Destroying a module that another module depends on via outputs, causes the depending module to also be destroyed.

### ISSUE THREAD

**Issue by bploetz** [hashicorp/terraform#20842]
### Terraform Version

```
terraform -v
Terraform v0.11.8
+ provider.aws v1.52.0
+ provider.template v1.0.0
```

I'm not sure if this is a bug or expected behavior, but this doesn't seem right to me.

I have a bunch of microservices fronted by an API Gateway. The microservices and the API Gateway all run as containers on AWS ECS. The API Gateway and each of the microservices are all Terraform modules. We configure the microservice endpoints in the API Gateway via module outputs from each of the microservice modules, which are mapped as input variables to the API Gateway module.

Here's the basic structure (unrelated stuff removed to focus on the problem at hand):

```hcl
# environments/production/api_gateway.tf
module "api_gateway" {
  source = "../../modules/aws/api_gateway"

  service_a_hostname = "${module.service_a.hostname}"
  service_b_hostname = "${module.service_b.hostname}"
  # etc....
}
```

```hcl
# environments/production/service_a.tf
module "service_a" {
  source = "../../modules/aws/service_a"
  # etc....
}
```

```hcl
# modules/aws/service_a/outputs.tf
output "hostname" {
  value = "${aws_route53_record.alias_route53_record.name}"
}
```

```hcl
# modules/aws/service_a/main.tf
resource "aws_route53_record" "alias_route53_record" {
  name = "service-a.${var.env_name}-services.mydomain.com"
  # etc....
}
```

```hcl
# modules/aws/api_gateway/main.tf
resource "aws_ecs_task_definition" "api_gateway" {
  family = "api-gateway-${var.env_name}"
  container_definitions = <<CDEF
[
  {
    "name": "api-gateway-${var.env_name}",
    "image": "${var.docker_image}",
    "essential": true,
    "memoryReservation": ${var.ecs_task_memory_reservation},
    "environment" : [
      {"name":"SERVICE_A_URI", "value":"http://${var.service_a_hostname}"},
      {"name":"SERVICE_B_URI", "value":"http://${var.service_b_hostname}"}
    ]
  }
]
CDEF
  # etc.....
}

resource "aws_ecs_service" "api_gateway" {
  name = "api-gateway-${var.env_name}"
  cluster = "${aws_ecs_cluster.api_gateway.id}"
  task_definition = "${aws_ecs_task_definition.api_gateway.arn}"

  # etc.....
}
```

```hcl
# modules/aws/api_gateway/variables.tf
variable "service_a_hostname" {
  description = "The hostname for the service-a endpoint"
}

variable "service_b_hostname" {
  description = "The hostname for the service-b endpoint"
}
```

When I "terraform apply" all of the microservices and the upstream API Gateway, everything's fine. However, let's say I destroy `service_a`. It will also destroy the API Gateway!

```
terraform plan -destroy --target=module.service_a

........yadda yadda yadda............

Terraform will perform the following actions:

  - module.api_gateway.aws_ecs_service.api_gateway           <-- API GATEWAY BEING DESTROYED!

  - module.api_gateway.aws_ecs_task_definition.api_gateway   <-- API GATEWAY BEING DESTROYED!

  - module.service_a.aws_alb.service_a

  - module.service_a.aws_alb_listener.service_a

  ......etc, the rest of service_a's resources.....

Plan: 0 to add, 0 to change, 20 to destroy.
```

So a module's output mapped as an input variable to another module causes this cascading delete.

If I change the `service_a_hostname` variable to be some static/predictable string, it does not cause the upstream API Gateway to be destroyed when I destroy service_a.

```hcl
service_a_hostname = "service-a.${var.env_name}-services.mydomain.com"
```

Then:

```
terraform plan -destroy --target=module.service_a

........yadda yadda yadda............

Terraform will perform the following actions:

  - module.service_a.aws_alb.service_a

  - module.service_a.aws_alb_listener.service_a

  ......etc, the rest of service_a's resources.....

Plan: 0 to add, 0 to change, 18 to destroy.
```

Note that it now does not destroy the upstream API Gateway module as well.

This seems backwards to me, that deleting a module that another module depends on via outputs, causes the depending module to also be destroyed. Is this the expected behavior?

**Comment by mildwonkey** [comment]
Hi @bploetz,

This is indeed expected behavior. Using `-target` to destroy a resource will destroy any and all resources that depend on the target. 
 
The [destroy)[https://www.terraform.io/docs/commands/destroy.html} documentation specifies:
> The -target flag, instead of affecting "dependencies" will instead also destroy any resources that depend on the target(s) specified.

It's also referenced in the [plan](https://www.terraform.io/docs/commands/plan.html#resource-targeting) documentation.

**Comment by bploetz** [comment]
Thanks @mildwonkey . Terraform best practices tell us to build up our infrastructure as reusable discreet components via modules, such that we can work on small isolated parts of infrastructure and limit the "blast radius" when applying changes. It's counter-intuitive that when targeting changes to a set of resources defined in a module, destroy would go outside this bubble and also destroy anything that relies on said module.

But, it is what it is, and my complaining is not going to change anything, so I will adapt. :) Thanks again.
