### ISSUE TITLE
Backend provider azurerm ARM_SAS_TOKEN not working

### ISSUE THREAD

**Issue by sladeedmonds** [hashicorp/terraform#20847]
### Terraform Version

```
Terraform v0.11.13

```

### Terraform Configuration Files

```hcl
terraform {
backend "azurerm" {
    storage_account_name = "terraformdev"
    container_name = "tfstate"
    key = "devst.terraform.state"
  }
}
```

### Expected Behavior
It is my understanding that when either the ARM_ACCESS_KEY or ARM_SAS_TOKEN environment variables are set, that variable is used to initialize the storage client and authenticate to the storage account that will store the state file.  

### Actual Behavior
If ARM_ACCESS_KEY is set via an environment variable, the backend provider works perfectly.  If I unset that variable and set the environment variable ARM_SAS_TOKEN, the backend provider fails with:

`Error configuring the backend "azurerm": resource_group_name and credentials must be provided when access_key is absent`

Also, if I try to statically set sas_token as below,

```hcl
terraform {
  backend "azurerm" {
    storage_account_name = "terraformdev"
    container_name = "tfstate"
    key = "devst.terraform.state"

    sas_token = "test"
  }
}
```

I receive back:

```
Error initializing new backend: Error configuring the backend "azurerm": 1 error(s) occurred:

* : invalid or unknown key: sas_token
```

### Steps to Reproduce
terraform init

**Comment by berney** [comment]
SAS Tokens aren't supported as auth in Terraform v0.11.
Support was added in #19440.
From the [CHANGELOG.md](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md) support is only in some v0.12.x builds, the latest being a release candidate.

**Comment by mildwonkey** [comment]
I am going to close this issue, since the feature was added later. Thanks!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
