### ISSUE TITLE
Plan failing with `Error refreshing state` when no state file exists in terraform(v0.11.13) 

### ISSUE THREAD

**Issue by Ch3ck** [hashicorp/terraform#20850]
### Terraform Version

```
$ terraform -v
Terraform v0.11.13
+ provider.aws v2.3.0
+ provider.external v1.1.0
+ provider.random v2.1.0
+ provider.template v2.1.0
$ 
```

### Terraform Configuration Files

```hcl
module "s3" {
  source = "./modules/s3"
  env = "${var.env}"
  aws_region = "${var.aws_region}"
  aws_account_number = "${var.aws_account_number}"
  project = "${var.project}"
  db_encryption_key_alias_arn = "${var.db_encryption_key_alias_arn}"
  db_encryption_key_arn = "${var.db_encryption_key_arn}"
  db_encryption_key_id = "${var.db_encryption_key_id}"
}
```

### Crash Output

```
Error: Error refreshing state: 3 error(s) occurred:
* module.customer.module.iam.module.project_dev_ses_notification_policy.data.external.domains: 1 error(s) occurred:

* module.customer.module.iam.module.project_dev_ses_notification_policy.data.external.domains: data.external.domains: failed to execute "aws": 
In function join(), invalid type for value: None, expected one of: ['array-string'], received: "null"

* module.customer.module.s3.data.external.service_account_json_s3_bucket: 1 error(s) occurred:

* module.customer.module.s3.data.external.service_account_json_s3_bucket: data.external.service_account_json_s3_bucket: failed to execute "aws": 
An error occurred (ValidationException) when calling the UpdateItem operation: The document path provided in the update expression is invalid for update

* module.customer.module.s3.data.external.s3_bucket: 1 error(s) occurred:

* module.customer.module.s3.data.external.s3_bucket: data.external.s3_bucket: failed to execute "aws": 
An error occurred (ValidationException) when calling the UpdateItem operation: The document path provided in the update expression is invalid for update
```

### Expected Behavior

I ran these same configs in a different environment and terraform worked just fine.

### Actual Behavior

```
It's somehow crashing on `terraform refresh` and `terraform plan`. However, it's a new infra provisioning. Hence no state files exist and everything should work as expected
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan` or `terraform refresh`

### Additional Context

```
I'm running everything in a terraform deployment workflow, which is basically a bunch of shell scripts with terraform commands on each line
This error looks like a Dynamo issue, but I don't know for sure if it has to do with some other modules I have configured in TF. But will like more eyes on this to be sure.
```

### References
These are similar issues I've found in relation to failing on refreshing terraform state
- #17366
- #4598
- #10917

**Comment by chuckyz** [comment]
Just had an identical situation happen while I had an internet blip when putting state into a remote consul cluster.

**Comment by Ch3ck** [comment]
@chuckyz My case is weirder, since it's new infrastructure I'm trying to provision. So no state file exists and this error pops up.

**Comment by chuckyz** [comment]
@Ch3ck this is the exact same situation I had, terraform init went perfect, but while executing a `terraform plan` my internet cut out for ~2m, I ctrl-c'd the process (only once for graceful shutdown), and sure enough the state afterwards when checked was, in-fact, empty.  `consul kv get ${state}` was just an empty string.

Here's my actual console output

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_vpc.vpc: Refreshing state...
^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
data.aws_route_tables.rts: Refreshing state...

------------------------------------------------------------------------
stopping operation...

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
Releasing state lock. This may take a few moments...
$ terraform plan
Releasing state lock. This may take a few moments...

Error: Error loading state: no state


$ terraform init

Initializing the backend...
Error refreshing state: no state
```

**Comment by slancio** [comment]
I just had the exact same thing happen where I ctrl+c'd during plan and now have the no state error message.

**Comment by apparentlymart** [comment]
Hi @Ch3ck! Sorry for this odd behavior, and for the unreadable error message.

The main parts of these error messages seem to be coming from AWS rather than Terraform, so I'm going to ask our bot to migrate this over to the AWS provider repository in the hope that the AWS provider team has a better idea of what these messages mean.

These are appearing during an initial create plan because they related to data sources, and data sources are processed on every run even if nothing else exists in the state yet.

The other comments here seem to be discussing a different problem with an entirely different error message. That message _does_ seem to be coming from Terraform itself, so if you're still seeing that `Error refreshing state: no state` problem please open a new GitHub issue for it and complete the issue template, and we'll see if we can figure out what's causing it.
