### ISSUE TITLE
Documentation seems to show incorrect path?

### ISSUE THREAD

**Issue by tolidano** [hashicorp/terraform#20862]
The directions in the README suggest that to build your own, you need to git clone terraform into $GOPATH/src/github.com/hashicorp/terraform.

But when I do that, I get the "-mod=vendor" problem (and it does nothing).

When I move the terraform folder OUT of $GOPATH (i.e. no ~/dev/go[$GOPATH]/src/github.com/hashcorp/terraform but ~/dev/go2/terraform), then everything works.

**Comment by apparentlymart** [comment]
Hi @tolidano,

Sorry that the docs are still lagging behind our move to using Go 1.11 modules mode. The scripts and makefile in the Terraform codebase now require modules mode, which can be achieved either by working outside of `GOPATH` (as you tried here) or by setting the environment variable `GO111MODULE=on` to force modules mode even inside `GOPATH`.

Once we complete the in-progress v0.12.0 release cycle we intend to spend some time cleaning up after the changes that were made during the v0.12 cycle, of which this is a key example.

**Comment by tolidano** [comment]
Sorry, a little confused - when I run make dev, will it still create the binaries? Where will it put them? Where does gox come into play? Thanks again

**Comment by apparentlymart** [comment]
`make dev` is, essentially, just an alias for `go install .`, aside from some pre-processing steps (formatting, go generate, etc.)

Therefore the `terraform` binary is written in to the directory given by the `GOBIN` environment variable, which defaults to `$GOPATH/bin` if not set. If `GOPATH` is _also_ not set, then it defaults to `~/go`.

**Comment by mildwonkey** [comment]
The build docs have been updated a number of times since this was opened, so I am going to close this stale issue. Thanks!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
