### ISSUE TITLE
[Azure] AppService overriding unspecified settings 

### ISSUE THREAD

**Issue by ahmedspiir** [hashicorp/terraform#20868]
### Terraform Version

```
v0.11.13
+ provider.azurerm v1.23.0
```

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "myapp" {
  name                = "${var.app_name}"
  location            = "${azurerm_resource_group.myapp.location}"
  resource_group_name = "${azurerm_resource_group.myapp.name}"
  app_service_plan_id = "${azurerm_app_service_plan.myapp.id}"
  https_only          = "true"

  app_settings {
    "APPINSIGHTS_INSTRUMENTATIONKEY" = "${azurerm_application_insights.myapp.instrumentation_key}"
  }

  site_config {
    always_on                 = "true"
    ftps_state                = "Disabled"
    use_32_bit_worker_process = "false"
  }
}
```

### Actual Behavior

Terraform will perform the following actions:

  ~ azurerm_app_service.myapp
      site_config.0.always_on:                 "false" => "true"
      site_config.0.default_documents.#:       "9" => "0"
      site_config.0.default_documents.0:       "Default.htm" => ""
      site_config.0.default_documents.1:       "Default.html" => ""
      site_config.0.default_documents.2:       "Default.asp" => ""
      site_config.0.default_documents.3:       "index.htm" => ""
      site_config.0.default_documents.4:       "index.html" => ""
      site_config.0.default_documents.5:       "iisstart.htm" => ""
      site_config.0.default_documents.6:       "default.aspx" => ""
      site_config.0.default_documents.7:       "index.php" => ""
      site_config.0.default_documents.8:       "hostingstart.html" => ""
      site_config.0.ftps_state:                "AllAllowed" => "Disabled"
      site_config.0.php_version:               "5.6" => ""
      site_config.0.use_32_bit_worker_process: "true" => "false"

Plan: 0 to add, 1 to change, 0 to destroy.

### Expected Behavior
So the expected behaviour is to override the specified site_config settings, and not to set everything else to be empty.
So i expected to get something like this

>  ~ azurerm_app_service.myapp
>       site_config.0.always_on:                 "false" => "true"
>       site_config.0.ftps_state:                "AllAllowed" => "Disabled"
>       site_config.0.use_32_bit_worker_process: "true" => "false"
> 

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by r0bnet** [comment]
Should be addressed here: https://github.com/terraform-providers/terraform-provider-azurerm
Faced the same issue already but not sure if that's really a bug or by design

**Comment by ahmedspiir** [comment]
Thanks @r0bnet, it's a bit weird for me, because if i didn't specify something this means that i don't want to override it.
I will post it there.
