### ISSUE TITLE
grpc: received message larger than max

### ISSUE THREAD

**Issue by mingfang** [hashicorp/terraform#20879]
I'm building a provider for Kubernetes and am getting this error 
```sh
>terraform providers schema -json

Error: Failed to retrieve schema from provider "k8s": rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4377699 vs. 4194304)
```
It looks like I'm hitting the default max here https://github.com/grpc/grpc-go/blob/3910b873d3af01925d2ab2820206eae340541df5/clientconn.go#L92

Please either increase the max or give me a cli/env option to increase it.

**Comment by mingfang** [comment]
confirm fixed

**Comment by zegl** [comment]
I'm getting this error on 0.12:

```
~/s/k/terraform (master) ./terraform version
Terraform v0.12.0
+ provider.archive v1.2.1
+ provider.aws v2.11.0
+ provider.local v1.2.1
+ provider.null v2.1.1
```

```
data.local_file.compiled_func: Refreshing state...

Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (25532983 vs. 4194304)
```

**Comment by LarsFronius** [comment]
I'm seeing the same - am wondering if it's due to me moving to the new terraform remote backend.

**Comment by apparentlymart** [comment]
Hi @zegl!

Although the symptom looks similar, it seems that you've hit a problem in a different part of Terraform than where this was originally found. Could you please open a new issue for that and include the information requested by the new issue template? That way we can hopefully figure out which subsystem is generating the error.

**Comment by pawelsocha** [comment]
@apparentlymart What about grpc provisioner? In #20906 changes only client-side.
