### ISSUE TITLE
FloatBetween helper

### ISSUE THREAD

**Issue by atsushi-ishibashi** [hashicorp/terraform#20876]
### Use-cases

To validate whether a float value exists between min and max.

### Proposal

`func FloatBetween(min, max float64) schema.SchemaValidateFunc`

**Comment by bflad** [comment]
The new `FloatBetween` validation function has been merged into the `helper/validation` package as of commit 00a76d019a3e5b4d9d040a3e28c9e0b4e56ad951. 👍
