### ISSUE TITLE
Context information is missing in some error messages

### ISSUE THREAD

**Issue by charles-at-geospock** [hashicorp/terraform#20895]
If an error occurs during the development of the module, some of the error messages do not contain any context about where there problem occurred - the file, the path to get there from the root module, etc - which forces us to include longer resource names and module names than we might otherwise.

In many error cases we see something like:

```
* module.spark_cluster.data.external.select_binaries: 1 error(s) occurred:
...
```

which is useful to determine the location of the problem.

However, in other cases, there's no contextual information that explains how the problematic module or resource was reached. See the 'Actual behaviour' section below for the unhelpful error messages.

### Terraform Version

```
Terraform v0.11.10
```

Can't see what the changes are in .12 and .13 in the changelog, to check whether this has been addressed by the intervening versions.

### Actual Behavior

Some examples of error messages that give no context as to where they're from (they could be in any one of many modules):

* `Error: module "cluster": "output_bucket_readable" is not a valid argument`
    * Might be generated by a typo or a mismerge, but finding which module named "cluster" you might have invoked badly is tedious.
* `Error: Error loading modules: module spark_zeppelin_log_log_group: not found, may need to run 'terraform init'`
    * Might be fixed by the `terraform init`, reporting how it got to that reference would really help.
* `Error: resource 'aws_emr_cluster.cluster' config: unknown module referenced: custom_jar_object`
    * When many modules have the same kind of resource (in this case an EMR) cluster, the module that's referenced might be common (in this case a JAR to use with it) and referenced with the same unhelpful name.
* `Error: Error loading modules: module spark_cluster: Error parsing .terraform/modules/f1b83ba9562ab69a7a3e6d20fb9e5358/main.tf: At 442:66: literal not terminated`
    * Whilst it's possible to expand the symlink'd file referenced to find out what it is in the tree, it isn't obvious at all how it came to that file and what it was trying to read.

### Expected Behavior

It would be useful to report the module path leading to the failure cases, to help locate what the problem is, such as messages like:

* `Error: In module.fancy_webservice, module "cluster": "output_bucket_readable" is not a valid argument`
* `Error: Error loading modules: module spark_zeppelin_log_log_group: not found whilst processing module.zeppelin_service.spark_cluster, may need to run 'terraform init'`
* `Error: In module module.zeppelin_service.spark_cluster, resource 'aws_emr_cluster.cluster' config: unknown module referenced: custom_jar_object`
* `Error: Error loading modules: module module.datascience_cluster.spark_cluster: Error parsing .terraform/modules/f1b83ba9562ab69a7a3e6d20fb9e5358/main.tf: At 442:66: literal not terminated`

### Steps to Reproduce

Test cases not supplied; examples given from output seen in the last week's development.
Test cases might be supplied; but if there is an obvious way to address this, I'd rather not put in lots of time to create them (at this second)

**Comment by mildwonkey** [comment]
Hi @charles-at-geospock !

I'm sorry you've come across this frustrating behavior. I don't think anyone will argue the statement that terraform has many unhelpful or confusing error messages. 

While this isn't immediately helpful, terraform 0.12 (currently available as a [beta release](https://www.hashicorp.com/blog/announcing-terraform-0-1-2-beta1)), includes many enhancements to error messages, including more reliable (and useful) source locations.

Here's an example error message - the specifics may change before the 0.12 general release, but it should give you an idea of what you can expect from 0.12: 

```
Error: Missing required argument

  on connection.tf line 11, in resource "random_id" "id":
  11: resource "random_id" "id" {

The argument "byte_length" is required, but no definition was found.
```

If you are interested, you can download the 0.12 beta and give it a try! Keep in mind that it _is_ beta; please do not use the beta release with actual production infrastructure. We'd love to hear what you think about the changes, and to hear if you find other cases where the error messages are not clear so we can work on improving.
