### ISSUE TITLE
In DataSource - Calculating length of list without verifying condition

### ISSUE THREAD

**Issue by neeleshg** [hashicorp/terraform#20894]
### Terraform Version
```
Terraform v0.11.11
+ provider.aws v2.4.0
+ provider.template v2.1.0
```
Also tried with 
```
Terraform v0.11.13
+ provider.aws v2.4.0
+ provider.template v2.1.0
```
### Terraform Configuration Files
```hcl
data "aws_instances" "selected" {
  count = "${var.enable_ebs_snapshot == true ? 1 : 0}"
  instance_tags = {
    Name = "abc-test"
  }
}

data "aws_ebs_volume" "ebs_volume_xvdc" {
 depends_on = ["data.aws_instances.selected"]
  count = "${var.enable_ebs_snapshot == false ? 0 : length(data.aws_instances.selected.ids)}"
  filter {
    name   = "attachment.instance-id"
    values = ["${element(data.aws_instances.selected.ids,count.index)}"]
  }

  filter {
    name   = "attachment.device"
    values = ["/dev/xvdc"]
  }
}

```

### Debug Output
Error: Error refreshing state: 1 error(s) occurred:

* data.aws_ebs_volume.ebs_volume_xvdc: data.aws_ebs_volume.ebs_volume_xvdc: value of 'count' cannot be computed

### Expected Behavior
Ideally when `var.enable_ebs_snapshot == false` It should not calculate length of `data.aws_instances.selected.ids`. It should set count as 0. As there are no instances in data.aws_instances.selected it should ignore the lenght or set count as 0.

### Actual Behavior
Terraform is throwing error saying value of 'count' cannot be computed.

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by mildwonkey** [comment]
Hi @neeleshg, thank you for opening this issue and I'm sorry you've come across this behavior.
This is a well-known limitation of terraform versions 0.11 and earlier.  It's being tracked in #15605.

Terraform 0.12 (currently in beta) includes enhancements to conditional statements.

I will close this in favor of #15605.
