### ISSUE TITLE
"ignore_changes" ignoring creation of tag

### ISSUE THREAD

**Issue by svaranasi-traderev** [hashicorp/terraform#20900]
I created a few AWS Cloudtrail trails yesterday using Terraform. I then decided to add 3 new tags to our trails, one of which is a "CreatedDate" tag that draws its value from `timestamp()`. The documentation for this interpolation function mentions that it must be used with ignore_changes in order for it to not trigger diffs on every plan/apply. So I went ahead and put in an ignore_changes block for that specific tag.

However, what ends up happening is that Terraform never even _creates_ the CreatedDate tag although it reports a count change in the plan _and_ the apply stages. See **Actual Behavior** below.

To test, I also hit `terraform apply` as well and can confirm that the "CreatedDate" tag is _not_ created.

I was expecting that it would create the tag _once_ and ignore it thereafter. Is this expected behaviour? If yes, is there a workaround that will allow me to create these tags once?

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.3.0
```

### Terraform Configuration Files

```hcl
locals {
  timestamp = "${timestamp()}"
  timestamp_sanitized = "${replace("${local.timestamp}", "/[T].*$|[-]/", "")}"

}
resource "aws_cloudtrail" "cloudtrail_trail" {
  name                          = "${data.aws_iam_account_alias.current.account_alias}-aws-cloudtrail"
  s3_bucket_name                = "${var.cloudtrail_bucket_name}"
  enable_logging                = "true"
  enable_log_file_validation    = "true"
  include_global_service_events = "true"
  is_multi_region_trail         = "true"

  tags {
    "Name"                = "Account-Wide Trail"
    "automation" = "Terraform"
    "Account"             = "${data.aws_iam_account_alias.current.account_alias}"
    "LineOfBusiness"      = "blabla"
    "Owner"               = "ops"
    "CreatedDate"         = "${local.timestamp_sanitized}"
  }

  lifecycle {
    ignore_changes = ["tags.CreatedDate"]
  }

}
```

### Expected Behavior
I expect Terraform to create the new "CreatedDate" tag as well, along with "LineOfBusiness" and "Owner" tags, because when I say "ignore_changes", I expect it to ignore changes and not ignore the creation as well.
```
Terraform will perform the following actions:

  ~ aws_cloudtrail.cloudtrail_trail
      tags.%:              "3" => "6"
      tags.CreatedDate:    "" => "20190402"
      tags.LineOfBusiness: "" => "blabla"
      tags.Owner:          "" => "ops"
```

### Actual Behavior
```
Terraform will perform the following actions:

  ~ aws_cloudtrail.cloudtrail_trail
      tags.%:              "3" => "6"
      tags.LineOfBusiness: "" => "traderev"
      tags.Owner:          "" => "ops"


Plan: 0 to add, 1 to change, 0 to destroy.
```
### Steps to Reproduce
-> Create a cloudtrail trail resource with a few existing tags. 
-> Plan and apply.
-> Add new tags to the trail resource block. 
-> Add "ignore_changes" block to one of the tags.
-> Plan and/or apply.
-> The tag with "ignore_changes" will not be created.

### Additional Context

To add, this seems to work as expected when attempting to create a _new_ trail:

```
Terraform will perform the following actions:

  + aws_cloudtrail.cloudtrail_trail
      id:                            <computed>
      arn:                           <computed>
      enable_log_file_validation:    "true"
      enable_logging:                "true"
      home_region:                   <computed>
      include_global_service_events: "true"
      is_multi_region_trail:         "true"
      is_organization_trail:         "false"
      name:                          "blabla-prod-aws-cloudtrail"
      s3_bucket_name:                "blabla-global-cloudtrail-bucket"
      tags.%:                        "6"
      tags.Account:                  "blabla-prod"
      tags.CreatedDate:              "20190402"
      tags.LineOfBusiness:           "blabla"
      tags.Name:                     "Account-Wide Trail"
      tags.Owner:                    "ops"
      tags.traderev:automation:      "Terraform"


Plan: 1 to add, 0 to change, 0 to destroy.
```
Help!

**Comment by CharanBR** [comment]
Hello,

I have the same issue as well with AzureRM provider.

Thanks,
Charan

**Comment by teamterraform** [comment]
Hi @svaranasi-traderev,

Unfortunately Terraform 0.11 and earlier cannot support ignoring a specific member of a collection; ignoring whole attributes (the entire `tags` map, in this case) is the best it can do.

This situation is improved in recent versions of Terraform. If you are able to upgrade to the latest 0.12 release you should find that this will now work, albeit with some slightly different syntax:

```hcl
resource "aws_cloudtrail" "cloudtrail_trail" {
  name                          = "${data.aws_iam_account_alias.current.account_alias}-aws-cloudtrail"
  s3_bucket_name                = "${var.cloudtrail_bucket_name}"
  enable_logging                = "true"
  enable_log_file_validation    = "true"
  include_global_service_events = "true"
  is_multi_region_trail         = "true"

  tags {
    "Name"                = "Account-Wide Trail"
    "automation" = "Terraform"
    "Account"             = "${data.aws_iam_account_alias.current.account_alias}"
    "LineOfBusiness"      = "blabla"
    "Owner"               = "ops"
    "CreatedDate"         = "${local.timestamp_sanitized}"
  }

  lifecycle {
    ignore_changes = [
      tags.CreatedDate,
    ]
  }
}
```

There are some subtleties to this which are described in more detail in [the documentation for `ignore_changes` in Terraform 0.12](https://www.terraform.io/docs/configuration/resources.html#ignore_changes).

Terraform 0.11 is now in maintenance mode only, so unfortunately it will never see any improvements to its existing `ignore_changes` behavior. Since this was already added in Terraform 0.12, we're going to close this out. If you run into other `ignore_changes` problems after upgrading to the latest version of Terraform, please report them in a new issue since the new implementation of `ignore_changes` is very different and so we'll need to re-capture updated debug log information etc in order to troubleshoot. Thanks!

**Comment by CharanBR** [comment]
I figured out my issue. Somewhere in the terraform documention, it said when timestamp() function is used, terraform plan ignores it and shows us as changes being applied but when you do the terraform apply it doesn't.

Also, below format worked for me for ignoring a specific tag.
```
  lifecycle {
    ignore_changes = [
      tags["CreatedDate'],
    ]
  }
```
