### ISSUE TITLE
Proper Terraform JSON syntax

### ISSUE THREAD

**Issue by mdallman2570** [hashicorp/terraform#2090]
Is it possible to create a script that makes it easy to add Terraform instances?  I tried to create one that outputs a JSON file that uses a JSON array.

{ 

"resource": 
    {"aws_instance": [
        {"Web1": {"ami": "ami-e7527ed7", "instance_type": "t2.micro", "subnet_id": "subnet-xxxxx", "count": 1}},
        {"Web3": {"ami": "ami-e7527ed7", "instance_type": "t2.micro", "subnet_id": "subnet-xxxxxx", "count": 1}}, 
        {"Web2": {"ami": "ami-e7527ed7", "instance_type": "t2.micro", "subnet_id": "subnet-xxxxx", "count": 1}}
        ]
    }
}

 but it doesn't appear as though Terraform likes arrays (or perhaps i'm just creating the array wrong.  I have no problem parsing it as a JSON, but Terraform gives these errors: 

Errors:

  * module root: 1 error(s) occurred:

* aws_instance.: resource repeated multiple times
  * aws_instance.: "instance_type": required field is not set
  * aws_instance.: "ami": required field is not set
  * aws_instance.: : invalid or unknown key: Web1
  * aws_instance.: "ami": required field is not set
  * aws_instance.: "instance_type": required field is not set
  * aws_instance.: : invalid or unknown key: Web3
  * aws_instance.: "ami": required field is not set
  * aws_instance.: "instance_type": required field is not set
  * aws_instance.: : invalid or unknown key: Web2

And when I try to create it like the example does (Multiple "resources" keys without an array) my output is always over written because JSON can't have two keys that are the same. 

In addition, i've also tried to start the file with an array and just have multiple "resources" blocks, but it doesn't like that either.
 Any ideas?

**Comment by sparkprime** [comment]
Does this work:

    {
        "resource": {
            "aws_instance": {
                "Web1": {"ami": ...},
                "Web2": {"ami": ...},
                "Web3": {"ami": ...}
            }
        }
    }

**Comment by mdallman2570** [comment]
Yep, wow.  I could have sworn I tried that variation, but i guess not.  Thanks!
