### ISSUE TITLE
hash merge causes crash with 0.12upgrade

### ISSUE THREAD

**Issue by mutt13y** [hashicorp/terraform#20917]
### Terraform Version

```
Terraform v0.12.0-beta1
+ provider.aws v1.60.0-dev20190216h00-dev
+ provider.random v2.1.0
```

### Terraform Configuration Files

```hcl
variable "aws_region" {
  description = "AWS region to launch servers."
  default     = "eu-central-1"
}

variable "tags" {
  description = "Tags for each component"
  type        = "map"

  default = {
    environment = "corp"
    team        = "IT"
    method      = "terraform"
    repo        = "Some repo"
  }
}
provider "aws" {
  region = "${var.aws_region}"
}
resource "aws_vpc" "corp" {
  cidr_block           = "${var.vpc_cidr}"
  enable_dns_hostnames = true

  tags = "${merge(var.tags, { Name = "corp-vpc" })}"
}
```

### Debug Output

https://gist.github.com/mutt13y/cf5b05cbe516fa3f67ee7c6605ceb399

### Crash Output
panic: upgradeExpr on unsupported type <nil>

goroutine 1 [running]:
github.com/hashicorp/terraform/configs/configupgrade.upgradeExpr(0x0, 0x0, 0xc0002851b2, 0x6, 0x1, 0xc00028a690, 0xc000aa2e00, 0x1, 0x1, 0x2357120, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_expr.go:587 +0x5646
github.com/hashicorp/terraform/configs/configupgrade.upgradeExpr(0x2596fa0, 0xc00032eeb0, 0xc0002851b2, 0x6, 0x1, 0xc00028a690, 0xc000135670, 0x4, 0x40, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_expr.go:60 +0x40e6
github.com/hashicorp/terraform/configs/configupgrade.upgradeExpr(0x24408e0, 0xc000ac3140, 0xc0002851b2, 0x6, 0x1, 0xc00028a690, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_expr.go:38 +0x55bf
github.com/hashicorp/terraform/configs/configupgrade.normalAttributeRule.func1(0x24408e0, 0xc000ac3140, 0x0, 0x68, 0x5, 0x3, 0xc0003bb698, 0x4)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_body.go:33 +0x59
github.com/hashicorp/terraform/configs/configupgrade.attributeRule.func1(0xc000135340, 0xc0003bb7e0, 0xc, 0xc000ac30e0, 0xc000706a08, 0x1, 0xc0003bb698)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_body.go:249 +0x145
github.com/hashicorp/terraform/configs/configupgrade.upgradeBlockBody(0xc0002851b2, 0x6, 0xc0003bb7e0, 0xc, 0xc000135340, 0xc0004c3300, 0x3, 0x4, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_native.go:462 +0xb51
github.com/hashicorp/terraform/configs/configupgrade.(*Upgrader).upgradeNativeSyntaxResource(0xc0006f7710, 0xc0002851b2, 0x6, 0xc000135340, 0x4d, 0xc0003bb611, 0x7, 0xc0003bb5f9, 0x4, 0xc000ac2ea0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_native.go:339 +0x832
github.com/hashicorp/terraform/configs/configupgrade.(*Upgrader).upgradeNativeSyntaxFile(0xc0006f7710, 0xc0002851b2, 0x6, 0xc0001dc000, 0x9e, 0x29e, 0xc00028a690, 0x0, 0x0, 0x280, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade_native.go:108 +0x890
github.com/hashicorp/terraform/configs/configupgrade.(*Upgrader).Upgrade(0xc0006f7710, 0xc0004b6ff0, 0xc000230190, 0x3, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/configupgrade/upgrade.go:101 +0x49c
github.com/hashicorp/terraform/command.(*ZeroTwelveUpgradeCommand).Run(0xc0004d0300, 0xc00000a070, 0x0, 0x0, 0xc0002a23e0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/012_config_upgrade.go:152 +0x829
github.com/mitchellh/cli.(*CLI).Run(0xc00028f040, 0xc00028f040, 0xc000427d20, 0x1)
	/opt/gopath/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x207
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb37
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xb7
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x2e

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Expected Behavior
files are upgraded to 0.12 syntax
```
tags = merge(var.tags, { Name = "corp-vpc" })
```
### Actual Behavior
Crash

### Steps to Reproduce
Install AWS plugin in .terraform/plugins
terraform 0.12upgrade 

### Additional Context

if you remove the line
```
tags = "${merge(var.tags, { Name = "corp igw" })}"
```
there is no crash and the files are converted

**Comment by mildwonkey** [comment]
Hi @mutt13y ! I am sorry for the crash, thank you for reporting it and including a reproducible configuration.

**Comment by mildwonkey** [comment]
Hi @mutt13y! 
It appears that your terraform configuration is not quite correct and should not work as written in terraform 0.11. The correct syntax for merging maps is:

```hcl
resource "aws_vpc" "corp" {
  cidr_block           = "${var.vpc_cidr}"
  enable_dns_hostnames = true

  tags = "${merge(var.tags, map("Name", "corp-vpc"))}"
}
```

I will submit a PR since this definitely should not cause a crash (thanks again!) but you will also need to fix your configuration. 

Please let me know if this doesn't match your experience - if you were using that syntax successfully, or if you found a terraform doc that suggested that syntax would work, I'd love to hear about it.

**Comment by mutt13y** [comment]
Hi @mildwonkey,
Sigh, you are correct. Like the code my brain is between 0.11 and 0.12
Thanks for your help. I ended up just commenting the offending lines and then manually rewriting in 0.12 syntax.

**Comment by mildwonkey** [comment]
> Like the code my brain is between 0.11 and 0.12

Welcome to the club! It's crazy here 😀
