### ISSUE TITLE
Error: Error applying plan:

### ISSUE THREAD

**Issue by Dabbeeru** [hashicorp/terraform#20913]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
* [Google](https://github.com/terraform-providers/terraform-provider-aws)
* [Oracle](https://github.com/terraform-providers/terraform-provider-oci)
* [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

**Comment by jbardin** [comment]
There doesn't seem to be anything here. If you are reporting a bug, feel free to open a new issue and fill out the provided template.
