### ISSUE TITLE
Some valid resource addresses not accepted by -target

### ISSUE THREAD

**Issue by patricklucas** [hashicorp/terraform#2091]
If I have an aws_instance resource named `foo-bar-1`, I cannot target it with `terraform plan` or `terraform apply`:

```
$ terraform plan -target aws_instance.foo-bar-1
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * Problem parsing address: "aws_instance.foo-bar-1"
```

However, if I named the resource `foo_bar_1`, it works fine.

Since hyphenated resource names are valid, I would expect `-target` to accept them.

**Comment by phinze** [comment]
Thanks for the report. This is already fixed in master via #1763 - will come out with v0.5.3 soon!
