### ISSUE TITLE
 RDS Cluster cannot be deleted

### ISSUE THREAD

**Issue by sriraja53** [hashicorp/terraform#20929]
Hi there,

I am creating RDS global cluster using Terraform  `aws_rds_global_cluster` resource.
Reference :  https://www.terraform.io/docs/providers/aws/r/rds_global_cluster.html

I am able to create RDS global cluster without any issue but while destroying the RDS global cluster I am facing below issue.

Error : 
aws_rds_cluster.secondary: RDS Cluster cannot be deleted: InvalidDBClusterStateFault: This cluster is a part of a global cluster, please remove it from globalcluster first

After waiting some time (10 mins) rerunning the terraform destroy command it will delete the cluster without any issue.

### Terraform Version
Terraform v0.11.10
provider.aws: version = "~> 1.54"

### Configuration

```
provider "aws" {
  alias  = "primary"
  region = "us-east-2"
}

provider "aws" {
  alias  = "secondary"
  region = "us-west-2"
}

resource "aws_rds_global_cluster" "example" {
  provider = "aws.primary"

  global_cluster_identifier = "example"
}

resource "aws_rds_cluster" "primary" {
  provider = "aws.primary"

  # ... other configuration ...
  engine_mode               = "global"
  global_cluster_identifier = "${aws_rds_global_cluster.example.id}"
}

resource "aws_rds_cluster_instance" "primary" {
  provider = "aws.primary"

  # ... other configuration ...
  cluster_identifier = "${aws_rds_cluster.primary.id}"
}

resource "aws_rds_cluster" "secondary" {
  depends_on = ["aws_rds_cluster_instance.primary"]
  provider   = "aws.secondary"

  # ... other configuration ...
  engine_mode               = "global"
  global_cluster_identifier = "${aws_rds_global_cluster.example.id}"
}

resource "aws_rds_cluster_instance" "secondary" {
  provider = "aws.secondary"

  # ... other configuration ...
  cluster_identifier = "${aws_rds_cluster.secondary.id}"
}
```

**Comment by encryptblockr** [comment]
@sriraja53 
you mind sharing your terraform configuration for launching the global cluster as me and others are having issues?

since this requires launching resources in 2 regions..how did you accomplish that?
how did terraform able to launch the resources in the 2 regions? did you set a default region when running terraform?

Your configuration file will be great, you can redact any sensitive information or replace rela values with fake values. Will really appreciate it.

Thanks

**Comment by sriraja53** [comment]
@encryptblockr  I used the same configuration as mentioned the Terraform documentation.
https://www.terraform.io/docs/providers/aws/r/rds_global_cluster.html

how did terraform able to launch the resources in the 2 regions? 
I used same credentials with different region as below

```
###This is for primary region 
provider "aws" {
  alias  = "primary"
  region = "us-east-2"
}

###This is for dr region 
provider "aws" {
  alias  = "secondary"
  region = "us-west-2"
}
```

**Comment by encryptblockr** [comment]
got it to work myself after several hours of battling
thanks for your reply though
