### ISSUE TITLE
Lambda Versioning

### ISSUE THREAD

**Issue by CherryRam** [hashicorp/terraform#20926]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
* [Google](https://github.com/terraform-providers/terraform-provider-aws)
* [Oracle](https://github.com/terraform-providers/terraform-provider-oci)
* [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

**Comment by CherryRam** [comment]
We are getting the following error while recreating aws lambda function with an updated code. We have used "publish=true" for versioning. Even the source_code_hash value is being changed with every update.

aws_lambda_function.<Function_Name>: Error creating Lambda function: ResourceConflictException: Function already exist: <Function_Name>
        status code: 409, request id: xxxxx-xxxx-xxxx-xxxx-xxxxxxxx

Please suggest.

**Comment by apparentlymart** [comment]
Hi @CherryRam!

I'm not sure what exactly happened with this comment but it seems like you found the links to the other provider repositories. The problem you are asking about is an AWS-specific one, so please ask about it in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws), being sure to fully fill out the issue template used in that repository.

Thanks!
