### ISSUE TITLE
format function preserves double quotes in string passed through -var flag terraform 0.12-beta1 

### ISSUE THREAD

**Issue by balan2010** [hashicorp/terraform#20947]
Hi there,

when terraform variable is set via --var flag in command line, format function in resource block seems to preserve double quotes, which ends up in validation error

```
TestInfraProject 2019-04-06T23:11:52+11:00 command.go:53: Running command terraform with args [apply -input=false -lock=false -auto-approve -var system_owner="infra" --var project_base_id="balanterratest" -var org_prefix="gcptest" -var org_id="xxxxx" -var application_name="terratest-infra-test" -var support_team_email="txxx" -var default_billing_account="xxxxx" -no-color]
TestInfraProject 2019-04-06T23:11:54+11:00 command.go:121:

TestInfraProject 2019-04-06T23:11:54+11:00 command.go:121: Error: "\"gcptest\"-\"balanterratest\"" project_id must be 6 to 30 with lowercase letters, digits, hyphens and start with a letter. Trailing hyphens are prohibited.

TestInfraProject 2019-04-06T23:11:54+11:00 command.go:121:
TestInfraProject 2019-04-06T23:11:54+11:00 command.go:121:   on .terraform/modules/project/gcp/projectcreation/main.tf line 6, in resource "google_project" "project":
TestInfraProject 2019-04-06T23:11:54+11:00 command.go:121:    6: resource "google_project" "project" {
TestInfraProject 2019-04-06T23:11:54+11:00 command.go:121:
TestInfraProject 2019-04-06T23:11:54+11:00 command.go:121:
TestInfraProject 2019-04-06T23:11:54+11:00 retry.go:77: Returning due to fatal error: FatalError{Underlying: exit status 1}
```

vars are set for below resource

```
resource "google_project" "project" {
  name            = format("%s-%s", var.org_prefix, var.project_base_id)
  project_id      = format("%s-%s", var.org_prefix, var.project_base_id)
  org_id          = var.org_id
  billing_account = var.project_billing_id
  labels          = var.project_labels

}
```

It works fine when vars are set via terraform.tfvars. Issue seems to happen only when using -vars flag in command line

**Comment by apparentlymart** [comment]
Hi @balan2010,

How exactly the command line is interpreted will depend on what operating system you are running Terraform under, but the most predictable way to use `-var` is to quote its entire parameter, not just the variable value part:

`-var "system_owner=infra"`

Terraform cannot control how the shell interprets the command line, but it will use what the shell passes it verbatim. As you've seen, using a `.tfvars` file is a good way to bypass the uncertainty of shell parsing and instead provide values in Terraform's own syntax.

**Comment by apparentlymart** [comment]
Hi again @balan2010!

Since we didn't hear back from you, I'm going to close this out in the hope that my previous comment helped you find a working solution.

If you have any follow-up questions, please ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are generally monitored only by our few core maintainers.
