### ISSUE TITLE
Providers file is ignored when module reference is removed

### ISSUE THREAD

**Issue by alexlouden** [hashicorp/terraform#2096]
This is with Terraform v0.5.2

I have a `providers.tf` file:
```ini
provider "aws" {
    access_key = "access"
    secret_key = "secret"
    region = "us-west-2"
}
```

And a generated `terraform.tf.json` file:
```json
{
  "module": {
    "mymodule": { 
      "source": "./mymodule",
      ...
    }
  }
}
```

When I run `terraform plan`, I get the expected output:

```bash
❯ terraform plan
Refreshing Terraform state prior to plan...

module.mymodule.aws_security_group.sg: Refreshing state... (ID: sg-xxx)
...
+ module.mymodule
    3 resource(s)
```

And `terraform apply` runs:

```bash
❯ terraform apply
module.mymodule.aws_security_group.sg: Refreshing state... (ID: sg-xxx)
...
```

But when I re-generate the `terraform.tf.json` file to remove the module (e.g. destroying a staging environment):
```json
{
  "module": {}
}
```

the `terraform plan` command fails with errors:
```bash
❯ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * module.mymodule.provider.aws: "region": required field is not set
  * module.mymodule.provider.aws: "access_key": required field is not set
  * module.mymodule.provider.aws: "secret_key": required field is not set
```

and `terraform apply` asks for the provider details, whereas it was happy for them to be supplied via the `providers.tf` file before.

```bash
❯ terraform apply           
provider.aws.access_key
  The access key for API operations. You can retrieve this
  from the 'Security & Credentials' section of the AWS console.

  Enter a value: 
```

Looks like the `providers.tf` file is being ignored? Am I doing something wrong or unexpected, or is this a bug?

**Comment by phinze** [comment]
Good report, @alexlouden! :heart: 

This is a bug - to express it in TF core terminology: it looks like provider inheritance isn't working on orphaned modules. We'll get this fixed up.
