### ISSUE TITLE
Create 3 instance and attach a newly created security group .

### ISSUE THREAD

**Issue by prabhinmp** [hashicorp/terraform#20964]
Hi all,
I need to create 3 new ec2 instances , one security group having the private IP of all the 3 newly created instances and attach to the 3 instances.

Can somebody help to achieve this.

Is this possible

**Comment by Deichindianer** [comment]
Hey man,

So I've written up two ways depending on your use case, the first is when you don't care about the amount of security group rules in the security group ([see sg limits](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#security-groups)).

**First option**
```sh
provider "aws" {}

data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

data "aws_vpc" "default" {
  default = true
}

resource "aws_instance" "instances" {
  count         = 3
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"
}

resource "aws_security_group" "sg" {
  name        = "allow-everything-prv-instances"
  description = "This is using the default VPC you probably should not do that in prod "
  vpc_id      = "${data.aws_vpc.default.id}"
}

resource "aws_security_group_rule" "allow_all" {
  count             = "${length(aws_instance.instances.*.id)}"
  type              = "ingress"
  from_port         = 0                                                                   # what port range is needed?
  to_port           = 65535                                                               # what port range is needed?
  protocol          = "tcp"
  cidr_blocks       = ["${element(aws_instance.instances.*.private_ip, count.index)}/32"]
  security_group_id = "${aws_security_group.sg.id}"
}
```

The second option sacrifices readability for less rules.

```sh
# removed the bits that don't change

resource "aws_security_group_rule" "allow_all" {
  type              = "ingress"
  from_port         = 0                                                               # what port range is needed?
  to_port           = 65535                                                           # what port range is needed?
  protocol          = "tcp"
  cidr_blocks       = ["${formatlist("%s/32", aws_instance.instances.*.private_ip)}"]
  security_group_id = "${aws_security_group.sg.id}"
}
```

**Comment by prabhinmp** [comment]
Thanks, man for the code. let me run and test

**Comment by Deichindianer** [comment]
Think this can be closed now unless @prabhinmp you have some question left? 

@mildwonkey Not sure how things are done around here with closing questions :)

**Comment by apparentlymart** [comment]
We generally use GitHub issues for tracking bugs and enhancements rather than for questions. It looks like you've figured out an answer in this case, which is great! For the future though, it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are often monitored only by our few core maintainers.

Thanks!

**Comment by prabhinmp** [comment]
thanks, it worked for me
