### ISSUE TITLE
Support for non-sh shebang in remote-exec script

### ISSUE THREAD

**Issue by alexlouden** [hashicorp/terraform#2097]
In terraform 0.4 I set up a `remote-exec` script that had a shebang: `#!/bin/bash` and the script ran fine.

In terraform v0.5.2 a new shebang `#!/bin/sh` is being injected ([here](https://github.com/hashicorp/terraform/blob/b3fa3811f5dc16b5014b95dea56126bf53474bfd/builtin/provisioners/remote-exec/resource_provisioner.go#L20)) into the top of the script, so now it looks like this (and the script fails to run):

```bash
#!/bin/sh
#!/bin/bash
...
```

Could you please support using a shebang other than `#!/bin/sh`? Ideally detect if we've got a shebang set and don't override it?

**Comment by svanharmelen** [comment]
@alexlouden thanks for reporting! This one is actually a known issue which is already fixed in master and will be in the next release. See PR #2041 for details about the fix...

**Comment by alexlouden** [comment]
Great, thanks!
