### ISSUE TITLE
Snap installation: terraform does not look for the correct .terraformrc path

### ISSUE THREAD

**Issue by Ecno92** [hashicorp/terraform#20979]
It seems like terraform is looking for the wrong location when it is looking for the .terraformrc file. 
According to the documentation it should look for the file in the home directory, but in my case it is looking for the file in the snap directory.
See debug info for more information. 

### Terraform Version
0.11.11  

~/.terraformrc

```hcl
credentials "app.terraform.io" {
  token = "xxxx.atlasv1.xxxx"
}
```
~/Projects/tf-test/terraform.tf
```hcl
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "yourorg"

    workspaces {
      name = "tf-test"
    }
  }
}
```

### Debug Output
```
user@pc:~/Projects/tf-test$ TF_LOG=trace terraform init
2019/04/10 16:21:01 [INFO] Terraform version: 0.11.11  
2019/04/10 16:21:01 [INFO] Go runtime version: go1.11
2019/04/10 16:21:01 [INFO] CLI args: []string{"/snap/terraform/216/bin/terraform", "init"}
2019/04/10 16:21:01 [DEBUG] Attempting to open CLI config file: /home/user/snap/terraform/216/.terraformrc
2019/04/10 16:21:01 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/04/10 16:21:01 [INFO] CLI command args: []string{"init"}
2019/04/10 16:21:01 [DEBUG] command: loading backend config file: /home/user/Projects/tf-test
2019/04/10 16:21:01 [DEBUG] command: no data state file found for backend config
2019/04/10 16:21:01 [DEBUG] New state was assigned lineage "..."
2019/04/10 16:21:01 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json

Initializing the backend...
2019/04/10 16:21:01 [DEBUG] Retrieve version constraints for service tfe.v2 and product terraform

2019/04/10 16:21:02 [DEBUG] plugin: waiting for all plugin processes to complete...
Error configuring the backend "remote": required token could not be found
...
```

### Expected Behavior
I expect that backend configuration will succeed with the set token.

### Actual Behavior
Remote token is not found in the configuration file.

### Steps to Reproduce
1. install terraform using snap
2. configure your CLI token (terraform enterprise) according documentation
3. configure a backend in your project according documentation.
4. run terraform init.

**Comment by mildwonkey** [comment]
Hi @Ecno92,
I'm sorry you are experiencing this odd behavior. HashiCorp doesn't provide a snap package for terraform, so I'm not sure how we can help - I'm not sure how a packaged version could look for `.terraformrc`  in the wrong location without modifying the source. It is interesting to note that it's looking in the `snap` _user's_ home directory:
```
Attempting to open CLI config file: /home/user/snap/terraform/216/.terraformrc
```

Since you are a Terraform Enterprise customer, I recommend that you contact the Enterprise support team in your usual way to discuss possible solutions and/or workarounds.

**Comment by Ecno92** [comment]
@mildwonkey 

I got a little bit confused as the ``snap info`` command reveals the following contact information:
**contact**:   https://github.com/hashicorp/terraform/issues

However it seems like another person is the publisher. I will contact this person to ask for assistance. 
Let me know if there are possibilities to follow up in this issue or whether you want to close it. 

Regarding workaround it is fairly simple. Changing the snap installation for a regular installation on Ubuntu resolves the issue.

**Comment by mildwonkey** [comment]
There's not anything for the terraform team to do in this case, so I will close this ticket. Thank you very much for updating it with your findings - this is helpful information for others.
