### ISSUE TITLE
Support GCS as a Terraform Module Source

### ISSUE THREAD

**Issue by SubatomicHero** [hashicorp/terraform#20987]
### Current Terraform Version
```
Terraform v0.11.13
```

### Use-cases
Terraform currently supports S3 as a Module Source. We only use GCP so want to be able to use GCS as a Module Source

### Attempted Solutions
A workaround I am currently using is to use Google Storage Interoperability. This provides AWS keys used for API calls to a S3 like protocol. Doing this I:
- Created the keys
- Exported the keys as environment variables
- Use S3 as a module source e.g.
```terraform
module "my_module" {
  source = "s3::https://storage.googleapis.com/modules-bucket/awesome-module.tar.gz"
}
``` 

### Proposal
Ideally this solution should work as such:
1. `source = "gcs::https://storage.googleapis.com/modules-bucket/awesome-module.tar.gz"`
2. Under the hood, Terraform uses a service account to authenticate

### References
None

**Comment by davewongillies** [comment]
I've raised https://github.com/hashicorp/terraform/pull/21254 to support this

**Comment by mildwonkey** [comment]
#21254 was merged and will be included in the next  terraform release 🎉
