### ISSUE TITLE
'number' is not a valid type

### ISSUE THREAD

**Issue by peterromfeldhk** [hashicorp/terraform#20997]
### Terraform Version
```
Terraform v0.11.11
+ provider.aws v1.43.2

```

### Terraform Configuration Files
```hcl
variable "es-volume-size" {
  type = "number"
}
```

```
## tried both
# es-volume-size = 35
es-volume-size = "35"
```

### Debug Output
```
2019/04/12 11:39:16 [INFO] Terraform version: 0.11.11
2019/04/12 11:39:16 [INFO] Go runtime version: go1.11.4
2019/04/12 11:39:16 [INFO] CLI args: []string{"/nix/store/7p1k5vdqawjq4bjq513qcs7qcx6ykrav-terraform-0.11.11-bin/bin/terraform", "apply", "-var-file=stg.tfvars"}
2019/04/12 11:39:16 [DEBUG] Attempting to open CLI config file: /Users/peter/.terraformrc
2019/04/12 11:39:16 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/04/12 11:39:16 [INFO] CLI command args: []string{"apply", "-var-file=stg.tfvars"}
2019/04/12 11:39:16 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: Error loading /SOME_PATH/backend/variables.tf: Variable 'es-volume-size' type must be one of [string, map, list] - 'number' is not a valid type
```

### Expected Behavior
https://www.terraform.io/docs/configuration/variables.html#number

### Actual Behavior
Variable 'es-volume-size' type must be one of [string, map, list] - 'number' is not a valid type

### Steps to Reproduce
```
variable "es-volume-size" {
  type = "number"
}
```

**Comment by apparentlymart** [comment]
Hi @peterromfeldhk,

The documentation you referred to here is for Terraform 0.12. Terraform 0.11 does indeed only have the smaller set if types listed. Numbers are usually represented by passing a string containing decimal digits, which Terraform will convert automatically where necessary.

**Comment by peterromfeldhk** [comment]
i changed it to string for now, seems to still work fine. Just found the link at the top of the page for 0.11
