### ISSUE TITLE
v0.12 testing: GetOkExists acting differently

### ISSUE THREAD

**Issue by jtopjian** [hashicorp/terraform#21007]
Hello,

I noticed a change in how `d.GetOkExists` is working.

We use `GetOkExists` in a handful of places for when we want to make sure the user has explicitly set something in their configuration. An example of this is when the argument is boolean, but the default value of the API is `true` when the argument is not sent in the request body:

* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_network_v2.go#L144-L148
* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_network_v2.go#L225-L232

The goal of the above block of code is to only send `port_security_enabled` if the user explicitly defined it in their configuration. Otherwise, the argument is not sent and the default behavior of the API service is used (in this case, port security is `true`).

However, when testing with the latest v0.12 code, this behavior has changed and `port_security_enabled` is being detected regardless of if it's in the configuration or not.

Test output can be found here: https://logs.openlabtesting.org/logs/59/559/40ee40788b613f07ec5d801b884983aaca5f8ed6/check/terraform-provider-openstack-acceptance-test/892ab73/ in the `job-output.txt.gz` file:

```
=== RUN   TestAccNetworkingV2PortIDsDataSource_basic
```

You can see from the API requests and responses, `port_security_enabled` is being sent as `false` when that field used to not be sent at all.

**Comment by jtopjian** [comment]
My amateur sleuthing shows that this behavior changed at commit 5f52aba3aeefd92ebeb9256aad1744d1d3e9ed3f. I'm not sure if that's the root cause or not, though, but tests pass using the commit prior to 5f52aba3aeefd92ebeb9256aad1744d1d3e9ed3f.

**Comment by jbardin** [comment]
Hi @jtopjian,

Is the case of the default value being `true` the only one you've encountered? 
The fact that this worked before the commit you referenced makes me think that `helper/schema` was abusing its own internal data schemes to sneak that information through, which means I might be able to replicate the same situation to restore the old behavior.

**Comment by jbardin** [comment]
Hi @jtopjian,

OK, I found the behavior without `Default` value set, which seems to replicate the issue with `port_security_enabled`. This seems to conflict with how computed sets are handled in `helper/schema` as seen in #20958, but these sort of inconsistencies in the legacy SDK are what we're aiming to fix.

**Comment by jtopjian** [comment]
@jbardin Thank you for the info and for the update. 

> I found the behavior without Default value set

This makes sense to me as we normally would not specify a default value (since for booleans, the default value would be false, anyway). Perhaps that's just laziness on our part. But there were also one or two times in the past when we retrofitted behavior and intentionally did not set a default value because we didn't want deployed states to change (which could trigger a chain of diffs).

> Is the case of the default value being true the only one you've encountered?

We also have some occurrences of `GetOkExists` that use string and int and I was just about to run some tests on these, but it sounds like you've found the root cause that triggered this change?

**Comment by jbardin** [comment]
My first test (before cleaning out a bunch of other test code) wasn't seeing this, so I thought you might have meant a `Default` value in the schema originally. Yes, setting a Default of `false` isn't useful, and you can't have a default+computed value. 

I assume any fix here will work for other primitives, I only mention it because of the seemingly conflicting behavior of set values.

**Comment by jtopjian** [comment]
> I assume any fix here will work for other primitives, I only mention it because of the seemingly conflicting behavior of set values.

Ah. I can confirm we only use `GetOkExists` on primitives. For Sets and Lets, we check the length to determine if something has been set in the config.
