### ISSUE TITLE
v0.12.0-beta1 - empty state file created in default workspace_key_prefix (env:)

### ISSUE THREAD

**Issue by mixmatch** [hashicorp/terraform#21000]
### Terraform Version

```
v0.12.0-beta1
```

### Terraform Configuration Files

```hcl
NA
```

### Debug Output

[terraform.log](https://gist.github.com/mixmatch/a38cc348f5cc7be8c6cee074c94d0748) (Sanitized values in [], truncated after reported issue)

### Expected Behavior

tfstate file created in [s3_bucket]/[workspace_key_prefix]/[workspace]

### Actual Behavior

empty tfstate file created in [s3_bucket]/env:/[workspace] 
actual tfstate file created in [s3_bucket]/[workspace_key_prefix]/[workspace] 

### Steps to Reproduce

```
export TF_INPUT=0
export TF_IN_AUTOMATION=1
export TF_LOG=WARN
export TF_LOG_PATH=~/terraform.log
terraform init \
    -backend-config "bucket=${InfraS3Bucket}" \
    -backend-config "region=${AWS::Region}" \
    -backend-config "key=main.tfstate" \
    -backend-config "workspace_key_prefix=terraform-state" \
    -backend-config "dynamodb_table=automation-${EnvironmentName}-ops-tf-state-lock"
terraform workspace select ${EnvironmentName} || terraform workspace new ${EnvironmentName}
terraform plan -out=tfplan -refresh=true -detailed-exitcode -lock=true -lock-timeout=30s
terraform apply -auto-approve -lock=true -lock-timeout=30s tfplan
```

### Additional Context

Example empty state file:
```
{
  "version": 4,
  "terraform_version": "0.12.0",
  "serial": 0,
  "lineage": "60581b49-c3fe-affd-7da0-fbb02c09c58c",
  "outputs": {},
  "resources": []
}
```

**Comment by mixmatch** [comment]
I reviewed my config and It looks to be due my terraform_remote_state data source. Once I added _workspace_key_prefix_ to the config the issue resolved:
```
data "terraform_remote_state" "state" {
  backend = "s3"
  workspace = terraform.workspace
  config = {
    bucket = "infra-${terraform.workspace}-${var.aws_region[terraform.workspace]}-${var.aws_account_id[terraform.workspace]}"
    key    = "main.tfstate"
    region = var.aws_region[terraform.workspace]
    workspace_key_prefix = "terraform-state" # added to resolve
  }
}
```

**Comment by mildwonkey** [comment]
I'm happy to hear you found a solution, and thank you for updating this issue with what you've found.
