### ISSUE TITLE
0.12.0-beta1 - 0.12upgrade drops inline comments

### ISSUE THREAD

**Issue by rifelpet** [hashicorp/terraform#21005]
### Terraform Version
```
Terraform v0.12.0-beta1
+ provider.null v2.1.0
```

### Terraform Configuration Files
```hcl
resource "null_resource" "foo" {
  # Changes to any instance of the cluster requires re-provisioning
  triggers = {
    foo = "bar" # this is a comment
  }
}
```

### Debug Output

https://gist.github.com/rifelpet/35040fee5fac4d8dc05db9d85cf5fb61

### Expected Behavior

`# this is a comment` is preserved in the upgraded .tf file. In this sample case, the file should be identical to the original file.

### Actual Behavior

`# this is a comment` was dropped from the upgraded .tf file:
```hcl
resource "null_resource" "foo" {
  # Changes to any instance of the cluster requires re-provisioning
  triggers = {
    foo = "bar"
  }
}
```

### Steps to Reproduce
```
terraform init
terraform 0.12upgrade
```

**Comment by apparentlymart** [comment]
Thanks, @rifelpet!

Indeed, the tool is supposed to preserve all the comments it found in the input, but it looks like it's missing a case here. We'll fix that up before final release.
