### ISSUE TITLE
version mismatch for downloads on website

### ISSUE THREAD

**Issue by smaftoul** [hashicorp/terraform#2101]
On https://www.terraform.io/downloads.html, the linux version link points to "https://dl.bintray.com/mitchellh/terraform/terraform_0.5.1_linux_amd64.zip", this zip contains version 0.5.2. The same applies for OSX. I didn't tested other versions.

**Comment by zxjinn** [comment]
I think the answer you're looking for is: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#051-never-released
and https://github.com/hashicorp/terraform/commit/4ed2c8d956d2eae83a2a3750290711ce7fa1ec76

**Comment by catsby** [comment]
Closing; we had a mishap (linked above) and we'll get it straightened out for 0.5.3
