### ISSUE TITLE
Need a Parser for (.tf) file and the terraform schema files. 

### ISSUE THREAD

**Issue by rvsingh011** [hashicorp/terraform#21020]
Request - 
I want a parser to parse the .tf files and the resource/data source schemas as well. 

Use Case-
I am trying to produce a machine readable output like JSON. Why I want a resource schema parser is because our (.tf) file only contains the key, value. It does not have any information about the type of variables, which the resource/data source schema has. So what we want to do is, combine information from both the parser and get more verbose metadata. So there are 2 steps involved.
1) get a (.tf) file parser. Related Github issue is #18269
2) get a resource parser.

**Comment by rvsingh011** [comment]
@mildwonkey Thanks for such a fast reply. I tried doing the same and ended up with no specific version found for the providers. I know you have tested it with a dummy provider but major cloud vendor provider are still not available for this version of terraform (0.12.beta).   
Is there any means I can directly parse the files without a terraform installation. Mostly all solution depends upon the terraform cli for such parsing. We need a kind of program that can do that and does not rely on the terraform installation.

**Comment by mildwonkey** [comment]
It depends on what providers you are using. There are a few providers that already support 0.12, and instructions on installing them in the 0.12 annoucement blog post: https://www.hashicorp.com/blog/announcing-terraform-0-1-2-beta1.

We expect to release the next beta candidate soon, along with a number of compatible provider releases.

`terraform-config-inspect` does not require the terraform cli but also does not support provider schemas;  the use-cases and design of a tool to inspect provider schemas without running terraform is interesting and will take more thought.

**Comment by rvsingh011** [comment]
I found a solution to the same by parsing the file using a library 
```https://github.com/hashicorp/hcl```

The following code can take a (.tf) file and output the JSON.

```
FileContent, err := ioutil.ReadFile("new.tf") // just pass the file name
	if err != nil {
		fmt.Print(err)
	}
	var out interface{}
	FileContentString := string(FileContent) // convert content to a 'string'
	err = hcl.Decode(&out, FileContentString)
	fmt.Println(out)

	outData, err := json.Marshal(out)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	jsonStr := string(outData)
	fmt.Println("The JSON data is:")
	fmt.Println(jsonStr) 
```
I need such a parser for resource_schemas/datasource_schemas because then we can know what all fields will be reuired in provisioning the resource. 
The case is - user provide a resource_scehema file and we output a json with fields required to provision that resource.

**Comment by mildwonkey** [comment]
I'm going to close this issue; terraform's json output and the terraform-config-inspect cli/library are the proper methods for parsing terraform files. If you find that these tools are insufficient for your use case, please open a new feature request with detailed information about your use-case. Thank you!
