### ISSUE TITLE
"template_file" not passing variables to "user_data"

### ISSUE THREAD

**Issue by mark-bixler** [hashicorp/terraform#21030]
### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.6.0
+ provider.null v2.1.1
+ provider.template v2.1.1
```

### Terraform Configuration Files

main.tf (snippet)
```hcl
data "template_file" "user_data" {
  template = "${file("./modules/asg/user_data.tpl")}"
  vars {
    ssmDomainJoin   = "${var.ssm-domain-join}"
    ssmServerBuild  = "${var.ssm-server-build}"
    ssmIisSetup     = "${var.ssm-iis-setup}"
  }
}
```
Powershell script (snippet)
```
<powershell>
switch($runCount) {
0 {
#Increment the RunCount
Set-ItemProperty -Path $Path -Name RunCount -Value 1
#Run SSM Policy Document
Set-DefaultAWSRegion -Region us-east-1 
Set-Variable -name instance_id -value (Invoke-Restmethod -uri http://169.254.169.254/latest/meta-data/instance-id) 
New-SSMAssociation -Name $ssmDomainJoin -Target @{Key="instanceids";Values=@($instance_id)}
</powershell>
```

### Expected Behavior

Variable should be passed to user_data. 

### Actual Behavior
Only literal string `$ssmDomainJoin` passed.
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by lfarnell** [comment]
with the following code I was able to see the rendered output of the template:

```hcl
variable "ssm-domain-join" {
    type = "string"
    default = "hello"
}

variable "ssm-server-build" {
    type = "string"
    default = "hello"
}

variable "ssm-iis-setup" {
    type = "string"
    default = "hello"
}

data "template_file" "user_data" {
  template = "${file("./user_data.tpl")}"
  vars {
    ssmDomainJoin   = "${var.ssm-domain-join}"
    ssmServerBuild  = "${var.ssm-server-build}"
    ssmIisSetup     = "${var.ssm-iis-setup}"
  }
}

output "file" {
    value = "${data.template_file.user_data.rendered}"
}
```
@mark-bixler I are you consuming the rendered template output? I know this has bitten me in the past

**Comment by mark-bixler** [comment]
Thanks for testing that.

I'm calling the user_data in my launch template:

```
resource "aws_launch_template" "lt" {
  user_data                 = "${base64encode(data.template_file.user_data.rendered)}"
}
```

Am I missing something simple here? Most likely!

**Comment by apparentlymart** [comment]
Hi @mark-bixler!

The syntax for template interpolation is to use `${ ... }`, not just `$`. So for anything you'd like `template_file` to replace, you'll need to add those braces. For example:

```
switch($runCount) {
0 {
#Increment the RunCount
Set-ItemProperty -Path $Path -Name RunCount -Value 1
#Run SSM Policy Document
Set-DefaultAWSRegion -Region us-east-1 
Set-Variable -name instance_id -value (Invoke-Restmethod -uri http://169.254.169.254/latest/meta-data/instance-id) 
New-SSMAssociation -Name ${ssmDomainJoin} -Target @{Key="instanceids";Values=@($instance_id)}
```

Depending on the format of that `ssmDomainJoin` string you may need to do some sort of escaping or quoting of it to cause PowerShell to interpret it literally.

**Comment by mark-bixler** [comment]
ah! I thought `${ ... }` was just for bash and not powershell. So it's for both?

**Comment by mark-bixler** [comment]
Well that worked! using braces it is. I will close this out. Thanks!

**Comment by apparentlymart** [comment]
I'm glad it worked out!

In this case, `${ ... }` is for neither bash nor PowerShell: it's for Terraform's template language. You're using a Terraform template to generate a PowerShell script, so the result of this template then contains more variables that are for PowerShell to evaluate, such as `$instance_id`.
