### ISSUE TITLE
Crash: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davidjeddy** [hashicorp/terraform#21044]
### Terraform Version
Armor-VIII:~/Projects/dje/ConnecHub$ tf -v
Terraform v0.11.13
+ provider.aws v2.4.

### Terraform Configuration Files
Nothing special.

### Crash Output
https://gist.github.com/davidjeddy/8fc2381f5c728098eb02866b7fa43364

### Expected Behavior
'plan' should complete successfully.

### Actual Behavior
crash :(

### Steps to Reproduce
`terraform plan --out ./out.plan -var-file=.env`

### Additional Context
Had just updated ~/.terraformrc token

### References
n/a

**Comment by mildwonkey** [comment]
The underlying code has changed quite a bit since this was opened, so I am going to close this issue. If you are still seeing problems in terraform v0.13, please open a new issue and fill out the template.
Thanks!
