### ISSUE TITLE
Feature Request: Azure Budget

### ISSUE THREAD

**Issue by yeswps** [hashicorp/terraform#21050]
### Current Terraform Version

```
Terraform v0.11.13
+ provider.azurerm v1.25.0
+ provider.template v2.1.1
```

### Use-cases

Part of automation requires creating Azure Resource Group with budget enabled

### Attempted Solutions

Currently using ARM template to deploy budget, however, when use terraform destroy, the deployed budget won't be removed.

### Proposal

To have native support for Azure budget in terraform

### References

ARM template
https://github.com/Azure/azure-quickstart-templates/tree/master/create-budget
API reference:
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Consumption/2018-10-01/budgets
Using Azure Budget to monitor a subscription consumption
http://teknews.cloud/using-azure-budget-to-monitor-a-subscription-consumption/

**Comment by yeswps** [comment]
One additional issue, once the budget is been deployed via ARM template. We cannot change parameters, such as budget amount or threshold or contact email. The consequent deployment will fail with following error:

{ "statusCode": "BadRequest", "serviceRequestId": "", "statusMessage": "{"error":{"code":"400","message":"There are changes made to Budget . Please get the latest budget to avoid overwrite. (Request ID: )"}}" }

**Comment by prabhakarreddy1234** [comment]
@yeswps  Have you found solution for this `BadRequest` issue. Even it's occuring without making any changes to the budget ARM.  Budget ARM fails 2nd time always.

https://stackoverflow.com/questions/56774004/azure-budget-arm-template-doesnt-work-2nd-time

**Comment by yeswps** [comment]
@prabhakarreddy1234 
The feature is been requested here:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/2677

An alternative solution would be:
https://community.gruntwork.io/t/creating-aws-resources-not-supported-by-terraform/128
However, I have no tried to go down this approach, as it will tie to a specific language.
