### ISSUE TITLE
Better syntax for template variables

### ISSUE THREAD

**Issue by 7heo** [hashicorp/terraform#2105]
The current syntax for the template variables (`${variable}`) works well, but is too likely to cause collisions with other languages (such as shell script). Given [the way it behaves with undeclared/incorrect variables][1], it is even more problematic. I am aware that [there probably is a better template language coming][2], but I open this issue in case this very simple language is kept, as I think it should be slightly modified:

I propose that instead of `${variable}`, terraform uses `${tf.variable}`. And then, it should only parse strings starting with `${tf.`, to avoid problems.

I believe the fix to this issue to be very simple, and I believe that this issue is a serious one. I will try to come up with a pull request to solve this asap.

[1]: https://github.com/hashicorp/terraform/issues/2104
[2]: https://github.com/hashicorp/terraform/issues/1845#issuecomment-101898829

**Comment by mitchellh** [comment]
This is an interesting idea but we're not going to break that much compatbility at this point in Terraform's life. We're stuck with the decision we made for the future going forward. Thanks!

**Comment by 7heo** [comment]
@mitchellh Wow, thanks for reacting so fast. I was going to close the issue anyway, since I just discovered that, according to [the doc'][1]:

> You can escape expansion with double dollar signs: `$${foo}` will be rendered as a literal `${foo}`.

Sorry for the noise.

[1]: https://www.terraform.io/docs/configuration/interpolation.html
