### ISSUE TITLE
S3 backend/ Failed to save state: Failed request:

### ISSUE THREAD

**Issue by Shazzberry** [hashicorp/terraform#21067]
### Overview
Hey everyone, I apologize in advance if this is sparse of needed information or badly submitted, this is my first GH issue but I have been advised this is the place to come to. If I am missing something simple, or overlooked a doc I will happily RTFM. Thanks in advance for the help

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v1.56.0
+ provider.template v2.1.0
+ provider.vault v1.7.0

```

### Terraform Configuration Files

```hcl
...
```

### Debug Output
There is a lot of sensitive data in the file so I am will provide upon request.

### Crash Output
```
Failed to save state: Failed request: Value for key "terraform/management" is too large (530996 > 524288 bytes)


Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate
```

### Expected Behavior
It should have updated the statefile

### Actual Behavior
I was creating service accounts in AWS so it created those but did not update the statefile.

### Additional Context
We did some research but only found size issues with using consul but not S3 (linked below)

### References
https://github.com/hashicorp/consul/issues/3358

**Comment by pselle** [comment]
@Shazzberry Thanks for reaching out! For this issue, you might get better feedback on one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers and is used for tracking bugs and enhancements to Terraform.

That said, your error (without seeing more of the config and output) looks like you might be using the local backend, rather than s3, but I could be off!

**Comment by mildwonkey** [comment]
Hi @Shazzberry!
I completely understand not wanting to share sensitive information, and we would not ask you to.

There are a few things that would be helpful for us to debug this issue (again, removing any sensitive information). 

The _best_ would be a simplified example configuration that allows us to reproduce this issue. 

* Your backend configuration (the `terraform` block)
* The relevant section of the trace log (`TF_LOG=trace terraform apply`), with sensitive information redacted
* The relevant configuration and value for key `terraform/management`, and the information for that key out of the `errored.tfstate` file (I suspect that's entirely sensitive, so please _don't_ share that if so)

Thanks, and I'm sorry you've experienced this issue!

**Comment by Shazzberry** [comment]
Thank you guys for the help! So after investigating back into the files after @pselle 's comment, I found that an assumption was made since our other backends were S3 that this one was as well. I found however that it was not and WAS IN FACT consul. So, yeah. Problem solved.

Really appreciate the response, I apologize for taking up your time. We're all good now :)
