### ISSUE TITLE
OpenStack  Provider Coverage

### ISSUE THREAD

**Issue by joelhandwell** [hashicorp/terraform#2106]
@pearkes would it be worth doing that creating similar spreadsheet as in [AWS Provider Coverage](https://github.com/hashicorp/terraform/issues/28) ?
OpenStack has comparably large variety of APIs as one of AWS, and they are rapidly growing in number over time. 
Spreadsheet could be based on something like this: http://developer.openstack.org/api-ref.html

**Comment by jtopjian** [comment]
I've started a spreadsheet here:

https://docs.google.com/spreadsheets/d/1HR9u2nzaHPPIdQna7B0A2nvv8MfHj8_NAA3ZIVZVxoA/edit#gid=0

It's simplistic and a bit opinionated in that I excluded a lot of actions that were "GET" only -- actions that were one-time commands or actions that did not generate a "tangible" resource.

**Comment by joelhandwell** [comment]
@jtopjian great!

**Comment by stack72** [comment]
Going to close this issue - we closed the AWS one since we found it difficult to keep it up to date

Paul
