### ISSUE TITLE
provisioner on tainted null_resource not called when destroyed

### ISSUE THREAD

**Issue by llamahunter** [hashicorp/terraform#21061]
### Terraform Version

```
Terraform v0.11.13
```

### Terraform Configuration Files

```hcl
resource "null_resource" "command" {
  provisioner "local-exec" {

    command = "do-something-on-apply"
  }

  provisioner "local-exec" {
    when = "destroy"
    command = "do-something-on-destroy"
  }
}
```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
Tainted null_resource calls its destroy provisioner on destroy.

### Actual Behavior
Destroy provisioner is skipped, leaving underlying resources in a funky state

### Steps to Reproduce
1. create resource
2. taint resource
3. destroy resource

### Additional Context
It's very important that destroy provisioners are called on tainted resources.  The docs already say that they need to be safe to be called multiple times, and so they should be able to deal with cleaning up tainted states.  As it is now, there is no easy way to rollback from a bad deploy when using null_resource provisioners.

**Comment by mildwonkey** [comment]
Hi @llamahunter !
I am sorry that you've come across this issue. We've been tracking a few related problems with destroy provisioners in #13549 (you can see in [this comment](https://github.com/hashicorp/terraform/issues/13549#issuecomment-293627472) that the issue with tainted resources is included), so I will close this issue in favor of that one.

I recommend that you react to the original issue (#13549 ) comment with 👍, which will help us during prioritization, and also be the best place for you to watch for updates.
