### ISSUE TITLE
terraform destroy has unnecessary dependencies on files

### ISSUE THREAD

**Issue by 7heo** [hashicorp/terraform#2108]
When executing `terraform destroy` on a tf file that contains a reference to a template, the destroy operation fails if the template is missing; even if the template isn't necessary for the destroy operation to succeed.

The correct behavior would be: terraform probes whenever a resource compilation is needed for the required operation, and then does not require unnecessary resources (the template is computed and sent via metadata in my case; and I believe that metadata isn't required to destroy an instance).

**Comment by phinze** [comment]
Totally agree. I think this should apply to inputs too - no reason to ask for variables to be populated when everything's slated for destruction.

**Comment by mitchellh** [comment]
This no longer happens with Terraform 0.8.
