### ISSUE TITLE
Include selected workspace in terraform plan output

### ISSUE THREAD

**Issue by alkalinecoffee** [hashicorp/terraform#21095]
### Current Terraform Version

```
Terraform v0.11.13
```

### Use-cases

We use a canary/blue-green deployment strategy.  Historically, our terraform environments are divided up between `blue` and `green` stacks, each having their own state file/root module.

Before making a change, we run `tf plan` and share the output with team members for a 👍 before applying.  By having different modules, it's clear as to which stack we're making changes:

```
Terraform will perform the following actions:

  ~ module.production_use1_green.module.asg.aws_autoscaling_group.autoscaling_group
      load_balancers.#:          "0" => "1"
      load_balancers.1491020339: "" => "prometheus-prod-elb"
```

We are now switching over to workspaces, where `blue` and `green` stacks use a single module.  Now our plans look like:

```
Terraform will perform the following actions:

  ~ module.prod_west.module.asg.aws_autoscaling_group.autoscaling_group
      load_balancers.#:          "0" => "1"
      load_balancers.1491020339: "" => "prometheus-prod-elb"
```

With workspaces, it is no longer clear which workspace we're running this plan in.

The workspace only appears when `terraform apply` is run, not `plan`.

### Proposal

It would be most excellent if the workspace was shown in the plan output, loud and clear, ie:

```
Terraform will perform the following actions:

Selected workspace: green

  ~ module.prod_west.module.asg.aws_autoscaling_group.autoscaling_group
      load_balancers.#:          "0" => "1"
      load_balancers.1491020339: "" => "prometheus-prod-elb"
```

**Comment by mildwonkey** [comment]
Hi @alkalinecoffee , thank you for submitting this feature request! I am going to close this in favor of #16459, which covers adding the workspace in plan, apply and destroy.

Please add a 👍to the original issue in #16459; we use those during prioritization.

**Comment by alkalinecoffee** [comment]
@mildwonkey looks good, thanks for pointing to the issue :+1:
