### ISSUE TITLE
formatlist does not work with list(string) variable

### ISSUE THREAD

**Issue by eriksw** [hashicorp/terraform#21119]
### Terraform Version

```
Terraform v0.12.0-beta2
```

### Terraform Configuration Files

```hcl
variable "bar" {
  type    = list(string)
  default = ["foo", "bar"]
}

locals {
  formatted_list = formatlist("%s/", var.bar)
}
```

### Expected Behavior

The local should contain a list of strings equivalent to `["foo/", "bar/"]`

### Actual Behavior

    Error: Error in function call

      on main.tf line 7, in locals:
       7:   formatted_list = formatlist("%s/", var.bar)

    Call to function "formatlist" failed: panic in function implementation: value
    is not known
    goroutine 30 [running]:
    runtime/debug.Stack(0x1, 0xc0004d87d0, 0xc0001ff748)
        /opt/go/src/runtime/debug/stack.go:24 +0xa7
    github.com/zclconf/go-cty/cty/function.errorForPanic(0x23691a0, 0x29f9160,
    0x29f9160, 0x38a4e80)
        /opt/gopath/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190320224746-fd76348b9329/cty/function/error.go:44
    +0x26
    github.com/zclconf/go-cty/cty/function.Function.Call.func1(0xc0001ffc30,
    0xc0001ffc50)
        /opt/gopath/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190320224746-fd76348b9329/cty/function/function.go:239
    +0x85
    panic(0x23691a0, 0x29f9160)
        /opt/go/src/runtime/panic.go:513 +0x1b9
    github.com/zclconf/go-cty/cty.Value.LengthInt(0x2a18160, 0xc0002c2f80,
    0x2418e60, 0x38a4e80, 0x1)
        /opt/gopath/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190320224746-fd76348b9329/cty/value_ops.go:848
    +0x267
    github.com/zclconf/go-cty/cty/function/stdlib.glob..func16(0xc0004b1060, 0x1,
    0x2, 0x2a18160, 0xc00011c0b0, 0xc00011c0b0, 0x0, 0x0, 0x0, 0x100bfe8, ...)
        /opt/gopath/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190320224746-fd76348b9329/cty/function/stdlib/format.go:87
    +0xbaa
    github.com/zclconf/go-cty/cty/function.Function.Call(0xc000099aa0,
    0xc0004b1040, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20190320224746-fd76348b9329/cty/function/function.go:243
    +0x2b5
    github.com/hashicorp/hcl2/hcl/hclsyntax.(*FunctionCallExpr).Value(0xc00020e0f0,
    0xc0004d2e60, 0x0, 0xc000201400, 0x1, 0x1, 0x0, 0x0, 0x0)
        /opt/gopath/pkg/mod/github.com/hashicorp/hcl2@v0.0.0-20190416162332-2c5a4b7d729a/hcl/hclsyntax/expression.go:385
    +0x12aa
    github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0004d86e0, 0x2a16e60,
    0xc00020e0f0, 0x2a18120, 0x38a5498, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/lang/eval.go:95 +0x1c3
    github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc0004c09c0,
    0x2a16e60, 0xc00020e0f0, 0x2a18120, 0x38a5498, 0x0, 0x0, 0x0, 0x2768468,
    0xc00050d6c8, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_context_builtin.go:284
    +0x1e5
    github.com/hashicorp/terraform/terraform.(*EvalLocal).Eval(0xc0004d2800,
    0x2a269c0, 0xc0004c09c0, 0x2, 0x2, 0x2222a24, 0x2466be0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval_local.go:43
    +0x672
    github.com/hashicorp/terraform/terraform.EvalRaw(0x2a00580, 0xc0004d2800,
    0x2a269c0, 0xc0004c09c0, 0x23f3b00, 0x375c005, 0x23691a0, 0xc0002c3cc0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:57 +0x167
    github.com/hashicorp/terraform/terraform.Eval(0x2a00580, 0xc0004d2800,
    0x2a269c0, 0xc0004c09c0, 0xc0004d2800, 0x2a00580, 0xc0004d2800, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/eval.go:35 +0x4d
    github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x255b2c0,
    0xc0001da420, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:90 +0x10d1
    github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0004da300,
    0x255b2c0, 0xc0001da420, 0xc0004b0dc0)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:392 +0x373
    created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:314 +0x9d2
    .

### Steps to Reproduce

1. Empty environment with tf code above as `main.tf`
2. `terraform init`
3. `terraform plan`

**Comment by apaulus** [comment]
I can confirm this, too. Really annoying ;)

**Comment by apaulus** [comment]
You can use a for loop as workaround for now:
```
locals {
  formatted_list = [ for x in var.bar:
    "${x.value}/"
  ]
}
```

**Comment by apparentlymart** [comment]
Thanks for reporting this, @eriksw!

This one seems to just be a missing input check in the function implementation, so we'll fix this up. Thanks again!

**Comment by bushong1** [comment]
The workaround i've been using is
```
formatted_list = formatlist("foo %s", concat(var.bar,[]))
```

**Comment by apparentlymart** [comment]
The fix for this bug is in [release candidate 1](https://releases.hashicorp.com/terraform/0.12.0-rc1/), and I would suggest that anyone who is doing 0.12 testing should switch over to that and away from either of the betas in order to be testing with the latest fixes. Thanks!

**Comment by bushong1** [comment]
Whaaaaat? How did I miss this. Thanks!
