### ISSUE TITLE
backend/s3: Support credential_process argument

### ISSUE THREAD

**Issue by llamahunter** [hashicorp/terraform#21120]
### Terraform Version
v0.11.13

### Terraform Configuration Files
unimportant... but using backend s3 configuration, where aws config uses credential_process

### Crash Output

Initializing the backend...

Error configuring the backend "s3": NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Please update the configuration in your Terraform files to fix this error
then run this command again.

### Expected Behavior
AWS config with credential_process should work

### Actual Behavior
aws-sdk-go in terraform core too old (< v1.16.0)

### Steps to Reproduce
set up an s3 backend with a ~/.aws/config specifying a credential_process for the profile

### Additional Context
This appears to be *already fixed* in the v0.11 branch.  We just need a v0.11.14 release.

### References
- hashicorp/terraform@102c78c
- https://github.com/terraform-providers/terraform-provider-aws/issues/6913

**Comment by llamahunter** [comment]
Was this fixed by https://github.com/hashicorp/terraform/releases/tag/v0.11.14?

**Comment by lorengordon** [comment]
It would seem so, according to what is vendored!

* https://github.com/hashicorp/terraform/blob/v0.11.14/vendor/github.com/aws/aws-sdk-go/aws/version.go

**Comment by apparentlymart** [comment]
Hi @llamahunter,

We have an upgrade AWS SDK. I'm not familiar enough with the AWS SDK releases to know if that was sufficient to get what you wanted here, but it sounds like you had previously checked that the necessary code was on the `v0.11` branch, in which case that code is now indeed in the v0.11.14 release.

I'm not familiar with the `credential_process` feature so I don't know how to verify whether it's working... if you still have whatever setup you used to see it _not_ working when you originally filed this and are able to verify that it's now fixed, that'd be much appreciated!

**Comment by llamahunter** [comment]
Yes, I verified that aws credential_process works with the latest release 0.11.14 when using s3 backend configuration.
