### ISSUE TITLE
0.11.13 crash during apply

### ISSUE THREAD

**Issue by btobolaski** [hashicorp/terraform#21128]
### Terraform Version

0.11.13

### Crash Output
https://gist.github.com/btobolaski/fb9ab9c599d82ba402487ff1f73aa4cf

### Expected Behavior
Resources should be created

### Actual Behavior

terraform crashed

### Steps to Reproduce
 
Unable to reproduce

**Comment by apparentlymart** [comment]
Hi @btobolaski,

This crash seems to actually be in the AWS provider, so I'm going to ask our bot to migrate this issue over to the AWS provider's own repository. Thanks!
