### ISSUE TITLE
Documentation for `concat` is missing from 0.12

### ISSUE THREAD

**Issue by bentterp** [hashicorp/terraform#21141]
### Terraform Version

```
Terraform v0.12.0-beta2
```

### Terraform Configuration Files

```distinct(list1,list2)
...
```

### Additional Context

The code is still there and works as intended, it's just the documentation which didn't make it. I'll submit a pull request ASAP.

**Comment by mildwonkey** [comment]
Hi @bentterp !
Thank you for reporting this issue - entirely coincidentally, I found the same thing earlier today and just merged a [PR with this documentation](https://github.com/hashicorp/terraform/pull/21112/files#diff-a8adf520b5260c1d58083d44f312d839) included, so it will show up next time the website is deployed.
Thanks again!
