### ISSUE TITLE
Renaming a data source in the state file turns it into a resource

### ISSUE THREAD

**Issue by matthoey-okta** [hashicorp/terraform#21149]
### Terraform Version
```
terraform --version
Terraform v0.11.13
+ provider.aws v2.5.0
+ provider.template v2.1.0
```

### Terraform Configuration Files

```hcl
# from data.tf
data "aws_ami" "ami" {
  most_recent = true
  owners      = ["self"]

  filter {
    name   = "name"
    values = ["${var.ami_string}"]
  }
}

# main.tf calling that ami
resource "aws_launch_configuration" "asg_cluster" {
  name_prefix          = "${local.asg_cluster_name}${var.extra_name}-"
  image_id             = "${data.aws_ami.ami.id}"
  instance_type        = "${var.instance_type}"
  ebs_optimized        = "true"
...
}
```

### Debug Output

I will try to setup a smaller scale example with no PII before I upload.
### Expected Behavior
Shows no changes

### Actual Behavior
Wants to destroy objects and if applied will destroy real objects.

### Steps to Reproduce
1. Not sure if this is module based or not, but make a module (this example has a launch configuration and an AMI) with a data source.
2. In your environment where you instantiate the module, terraform apply. Add some string to the name to change like `module "changeme_launch_config"`.
3. After successful apply, do a terraform state mv and remove the `changeme_` from the path in the state file. At that point, the state file will no longer recognize the ami as a data source but rather as a resource.
4. Match your environment to remove the `changeme_`.
5. Run a terraform plan to see it wants to destroy the AMI.
6. Actually applying the config will actually destroy the AMI itself.

Note this is more than just AMIs, but any data source you rename. Renaming just the resources but not the data sources works. Removing the data sources before or after the move works. Renaming the data sources back to their original names does not work.

### Additional Context
I have not tried using pure terraform for this, but have used custom makefile's and terragrunt.

**Comment by jbardin** [comment]
Hi @matthoey-okta,

Thanks for filing the issue. This was previously reported in #18978.
The next release will contain the updated state commands.
