### ISSUE TITLE
Error: Error parsing /home/username/vpc_resources.tf: object expected closing RBRACE got: EOF

### ISSUE THREAD

**Issue by sudlo** [hashicorp/terraform#21154]
I have a script when i use the command terraform ini, this the error message 

```
sudlo@ubuntu:~$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error parsing /home/sudlo/vpc_resources.tf: object expected closing RBRACE got: EOF

```
this is the code , 

```
locals {
  public_cidr_blocks = [
    "172.20.1.0/24",
    "172.20.2.0/24",
    "172.20.3.0/24",
    "172.20.4.0/24",
    "172.20.5.0/24",
    "172.20.6.0/24",
    "172.20.7.0/24",
    "172.20.8.0/24",
  ]

resource "aws_vpc" "main_vpc" {
  cidr_block           = "172.20.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
  instance_tenancy     = "default"

  tags {
    Name = "main_vpc"
   }
 }
} 

resource "aws_route53_zone" "vpc_internal_zone" {
  name          = "local.vpc"
  comment       = "Internal zone"
  vpc {
    vpc_id        = "${aws_vpc.main_vpc.id}"
  }
  force_destroy = true
}


resource "aws_vpc_dhcp_options" "dhcp_options" {
  domain_name         = "${aws_route53_zone.vpc_internal_zone.name}"
  domain_name_servers = ["AmazonProvidedDNS"]

  tags {
    Name = "main_vpc_dhcp_options"
  }
}

resource "aws_vpc_dhcp_options_association" "dhcp_options_association" {
  vpc_id          = "${aws_vpc.main_vpc.id}"
  dhcp_options_id = "${aws_vpc_dhcp_options.dhcp_options.id}"
}

resource "aws_internet_gateway" "public" {
  vpc_id = "${aws_vpc.main_vpc.id}"
}

resource "aws_route_table" "public" {
  vpc_id = "${aws_vpc.main_vpc.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.public.id}"
  }

  tags {
    "Name" = "public"
  }
}

resource "aws_subnet" "public" {
  count                   = "${length(data.aws_availability_zones.available.names)}"
  vpc_id                  = "${aws_vpc.main_vpc.id}"
  cidr_block              = "${element(local.public_cidr_blocks, count.index)}"
  availability_zone       = "${element(data.aws_availability_zones.available.names, count.index)}"
  map_public_ip_on_launch = true

  tags {
    "Name" = "public ${element(data.aws_availability_zones.available.names, count.index)}"
  }
}

resource "aws_route_table_association" "public" {
  count          = "${length(data.aws_availability_zones.available.names)}"
  route_table_id = "${aws_route_table.public.id}"
  subnet_id      = "${element(aws_subnet.public.*.id, count.index)}"
}

resource "aws_eip" "nat_gateway" {
  count = "${length(data.aws_availability_zones.available.names)}"
  vpc   = true
}

resource "aws_nat_gateway" "nat_gateway" {
  count         = "${length(data.aws_availability_zones.available.names)}"
  allocation_id = "${element(aws_eip.nat_gateway.*.id, count.index)}"
  subnet_id     = "${element(aws_subnet.public.*.id, count.index)}"

  tags {
    "Name" = "NAT ${element(data.aws_availability_zones.available.names, count.index)}"
  }
}

```

**Comment by fm0l** [comment]
What terraform version are you using?

By the way, i think the problem is the fact that you are defining a resource inside a local variable block.
Maybe try change it to something like that:

`locals {
  public_cidr_blocks = [
    "172.20.1.0/24",
    "172.20.2.0/24",
    "172.20.3.0/24",
    "172.20.4.0/24",
    "172.20.5.0/24",
    "172.20.6.0/24",
    "172.20.7.0/24",
    "172.20.8.0/24",
  ]
} 

resource "aws_vpc" "main_vpc" {
  cidr_block           = "172.20.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
  instance_tenancy     = "default"

  tags {
    Name = "main_vpc"
   }
 }
[...]
`

**Comment by sudlo** [comment]
> 
> 
> What terraform version are you using?
> 
> By the way, i think the problem is the fact that you are defining a resource inside a local variable block.
> Maybe try change it to something like that:
> 
> ```
> locals {
>   public_cidr_blocks = [
>     "172.20.1.0/24",
>     "172.20.2.0/24",
>     "172.20.3.0/24",
>     "172.20.4.0/24",
>     "172.20.5.0/24",
>     "172.20.6.0/24",
>     "172.20.7.0/24",
>     "172.20.8.0/24",
>   ]
> } 
> 
> resource "aws_vpc" "main_vpc" {
>   cidr_block           = "172.20.0.0/16"
>   enable_dns_hostnames = true
>   enable_dns_support   = true
>   instance_tenancy     = "default"
> 
>   tags {
>     Name = "main_vpc"
>    }
>  }
> [...]```
> ```

the version of terraform is v0.11.13

**Comment by fm0l** [comment]
Did you try changing the config as suggested?

Thanks

**Comment by sudlo** [comment]
> 
> 
> What terraform version are you using?
> 
> By the way, i think the problem is the fact that you are defining a resource inside a local variable block.
> Maybe try change it to something like that:
> 
> ```
> locals {
>   public_cidr_blocks = [
>     "172.20.1.0/24",
>     "172.20.2.0/24",
>     "172.20.3.0/24",
>     "172.20.4.0/24",
>     "172.20.5.0/24",
>     "172.20.6.0/24",
>     "172.20.7.0/24",
>     "172.20.8.0/24",
>   ]
> } 
> 
> resource "aws_vpc" "main_vpc" {
>   cidr_block           = "172.20.0.0/16"
>   enable_dns_hostnames = true
>   enable_dns_support   = true
>   instance_tenancy     = "default"
> 
>   tags {
>     Name = "main_vpc"
>    }
>  }
> [...]```
> ```
the version of terraform is v0.11.13
