### ISSUE TITLE
Module Source : SSH private keys for git(hub) don't work 

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#2116]
I'm not clear how to cause the module to use SSH with private keys rather than HTTPS.

#1220

the following tries causes a username and password login, rather than using private SSH keys. 
```

module "consul" {
    source = "git::http://hashicorp.com/foo.git"
}

```
Error loading Terraform: Error downloading modules: module download not supported for scheme 'ssh'

ssh://github.com/user/repo//mymodule

and 

git::github.com/user/repo//mymodule

and 

git::ssh://github.com/user/repo//module

and 

git::git@github.com:user/repo//module

**Comment by phinze** [comment]
Sorry for the confusion! Here's the correct syntax:

```
module "ami" {
  source = "git::ssh://git@github.com/terraform-community-modules/tf_aws_ubuntu_ami.git"
  region = "eu-central-1"
  distribution = "trusty"
  architecture = "amd64"
  virttype = "hvm"
  storagetype = "instance-store"
}

output "ami" {
  value = "${module.ami.ami_id}"
}
```

I'll add this example to the docs to make it clearer. :+1:

**Comment by franklinwise** [comment]
thanks @phinze
