### ISSUE TITLE
Error when using percentage sign (%) in conditional expression after v0.12 upgrade

### ISSUE THREAD

**Issue by joakimhellum-in** [hashicorp/terraform#21167]
### Terraform Version

```
Terraform v0.12.0-beta2
```

### Terraform Configuration Files

```hcl
locals {
  percent_sign = "%"
  is_percent = local.percent_sign == "%" ? true : false
}
```

### Expected Behavior

```sh
$terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

is_percent = true
```

### Actual Behavior

```sh
$terraform apply

Error: Invalid character

  on main.tf line 4, in locals:
   4:
   5:

This character is not used within the language.


Error: Unterminated template string

  on main.tf line 4, in locals:
   4:
   5:

No closing marker was found for the string.


Error: Invalid character

  on main.tf line 5, in locals:
   5:
   6:

This character is not used within the language.

...
```

### Steps to Reproduce

```sh
terraform init
terraform apply
```
### Additional Context

This works with Terraform v0.11
I don't understand if this is expected behavior in v0.12.
Many thanks for your feedback

### References

Reference to the error:
```
Error: Unterminated template string
```
I expected `%{` to begin template string, but not `%`.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @joakimhellum-in!

Indeed this isn't expected behavior. I expect the problem here is that the parser is seeing the `%` marker and expecting it to introduce a template directive sequence with `%{`, but that's not correct. Instead, `%` should be interpreted as a literal unless it is followed immediately by `{`.

As an aside: were the source lines shown in the error output really blank as you quoted them here? I can't tell how the line numbers in the error messages correspond with the lines in the configuration you showed, but it's weird to me to see it say "in locals" in the source location header but then not show any part of the locals block in the source snippet underneath. :thinking:

**Comment by joakimhellum-in** [comment]
>  As an aside: were the source lines shown in the error output really blank as you quoted them here?

Yes, they were blank, it's the first time I've seen this:


<details>
 <summary>Show complete Terraform configuration</summary>

```hcl
locals {
  percent_sign = "%"
  is_percent   = (local.percent_sign == "%" ? true : false)
}
 
output "is_percent" {
  value = local.is_percent
}
```
</details>

<details>
 <summary>Click here to show complete output</summary>

```
terraform apply

Error: Invalid character

  on main.tf line 3, in locals:
   3:
   4:

This character is not used within the language.


Error: Unterminated template string

  on main.tf line 3, in locals:
   3:
   4:

No closing marker was found for the string.


Error: Invalid character

  on main.tf line 4, in locals:
   4:
   5:

This character is not used within the language.


Error: Invalid character

  on main.tf line 5, in locals:
   5:
   6:

This character is not used within the language.


Error: Invalid character

  on main.tf line 6, in locals:
   6:
   7:

This character is not used within the language.


Error: Invalid character

  on main.tf line 7, in locals:
   7:
   8:

This character is not used within the language.


Error: Invalid character

  on main.tf line 8, in locals:
   8:
   9:

This character is not used within the language.


Error: Invalid character

  on main.tf line 9, in locals:
   9:

This character is not used within the language.
```
</details>

![image](https://user-images.githubusercontent.com/34519450/57000603-bff06980-6bb4-11e9-8ef4-9036eac0a3d4.png)

**Comment by apparentlymart** [comment]
Thanks for the extra context on the error messages... very strange!

If we can reproduce that at the same time as fixing the parse error then maybe we'll fix them both together, but otherwise we'll focus on the parse error for this issue.

**Comment by apparentlymart** [comment]
This is an HCL scanner bug, so I've opened hashicorp/hcl2#102 to represent it and capture what I've learned so far. We'll continue digging into this and see what can be done to resolve it.
