### ISSUE TITLE
terreform init not working in 0.11.13 anymore

### ISSUE THREAD

**Issue by nielssiebert** [hashicorp/terraform#21160]
using aws
Terraform v0.11.13 on **win10Pro**
+ provider.aws v2.8.0
+ provider.random v2.1.1
+ provider.template v2.1.1

**Since I use 0.11.13 instead of 0.11.11
I get the following on terraform init:**

$terraform init
Initializing modules...
- module.infrastructure
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc0003ad2a0, 0x12, 0x33c4180, 0xc0003fc0c0, 0x1, 0xc00040a3c0, 0xc0002bf920, 0x7fc0d40, 0x0, 0x28, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc0003ad2a0, 0x12, 0x33c4180, 0xc0003fc0c0, 0x1, 0xc00040a3c0, 0xc0002bf950, 0x2a, 0x2, 0x2, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
github.com/hashicorp/terraform/config/module.Storage.findModule(0xc0003ad2a0, 0x12, 0x33c4180, 0xc0003fc0c0, 0x1, 0xc00040a3c0, 0xc0002bf950, 0x2a, 0x0, 0x0, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc000106800, 0xc0003e91a0, 0xc000106838, 0xb28719, 0x300d660)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc000106800, 0xc0003e91a0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
github.com/hashicorp/terraform/command.getModules(0xc0003fb1e0, 0xc0003b3500, 0x56, 0xc0002be201, 0x23, 0xc0002be150)
        /opt/gopath/src/github.com/hashicorp/terraform/command/get.go:84 +0x127
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0003fb1e0, 0xc000004450, 0x0, 0x0, 0xc0002cb730)
        /opt/gopath/src/github.com/hashicorp/terraform/command/init.go:179 +0xac7
github.com/mitchellh/cli.(*CLI).Run(0xc0003e2140, 0xc0003e2140, 0xc0001b3d20, 0x1)
        /opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[crash.log](https://github.com/hashicorp/terraform/files/3137031/crash.log)
[crash.log](https://github.com/hashicorp/terraform/files/3137035/crash.log)

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

crash.log:

2019/05/02 09:19:35 [INFO] Terraform version: 0.11.13  
2019/05/02 09:19:35 [INFO] Go runtime version: go1.11.5
2019/05/02 09:19:35 [INFO] CLI args: []string{"c:\\windows\\system32\\terraform.exe", "init"}
2019/05/02 09:19:35 [DEBUG] Attempting to open CLI config file: C:\Users\secret\AppData\Roaming\terraform.rc
2019/05/02 09:19:35 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/05/02 09:19:35 [INFO] CLI command args: []string{"init"}
2019/05/02 09:19:35 [DEBUG] command: loading backend config file: C:\Users\secret\Documents\git\gevelop\product-information-service\terraform\services
2019/05/02 09:19:35 [TRACE] module source: "../modules/infrastructure"
2019/05/02 09:19:35 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc0002dd460, 0x12, 0x33c4180, 0xc0003ec120, 0x1, 0xc000329260, 0xc000036870, 0x78f0d40, 0x0, 0x28, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc0002dd460, 0x12, 0x33c4180, 0xc0003ec120, 0x1, 0xc000329260, 0xc0000368a0, 0x2a, 0x2, 0x2, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
github.com/hashicorp/terraform/config/module.Storage.findModule(0xc0002dd460, 0x12, 0x33c4180, 0xc0003ec120, 0x1, 0xc000329260, 0xc0000368a0, 0x2a, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc0002d6680, 0xc0001e80c0, 0xc0002d66b8, 0xb28719, 0x300d660)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc0002d6680, 0xc0001e80c0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
github.com/hashicorp/terraform/command.getModules(0xc0003eaea0, 0xc0003b3500, 0x56, 0xc0003c4301, 0x23, 0xc0003c42d0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/get.go:84 +0x127
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc0003eaea0, 0xc000004450, 0x0, 0x0, 0xc0002c1710)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:179 +0xac7
github.com/mitchellh/cli.(*CLI).Run(0xc0003da140, 0xc0003da140, 0xc0001b1d20, 0x1)
	/opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35

**Comment by pselle** [comment]
Hi @nielssiebert, to better understand the issue & make it easier to reproduce for anyone else would you mind sharing more details about your configuration, for example, linking to a gist of the config (with any secrets, if applicable, removed)

**Comment by syed9569a** [comment]
I am also having the same issue

**Comment by albuquerquezman** [comment]
I am also having the same issue:
2019/05/01 17:04:35 [INFO] Terraform version: 0.11.13  
2019/05/01 17:04:35 [INFO] Go runtime version: go1.11.5
2019/05/01 17:04:35 [INFO] CLI args: []string{"C:\\terraform\\terraform.exe", "init"}
2019/05/01 17:04:35 [DEBUG] Attempting to open CLI config file: C:\Users\dan\AppData\Roaming\terraform.rc
2019/05/01 17:04:35 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/05/01 17:04:35 [INFO] CLI command args: []string{"init"}
2019/05/01 17:04:35 [DEBUG] command: loading backend config file: D:\Source\DevOps.InfraAutomation\terraform\kronos\prod
2019/05/01 17:04:35 [TRACE] module source: "./app-module/"
2019/05/01 17:04:35 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc000319d40, 0x12, 0x33c4180, 0xc000364420, 0x1, 0xc0003d8b70, 0xc000319d80, 0x1a06a0, 0x0, 0x11, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc000319d40, 0x12, 0x33c4180, 0xc000364420, 0x1, 0xc0003d8b70, 0xc000319da0, 0x13, 0x2, 0x2, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
github.com/hashicorp/terraform/config/module.Storage.findModule(0xc000319d40, 0x12, 0x33c4180, 0xc000364420, 0x1, 0xc0003d8b70, 0xc000319da0, 0x13, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc00011b280, 0xc0003638c0, 0xc00011b2b8, 0xb28719, 0x300d660)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc00011b280, 0xc0003638c0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
github.com/hashicorp/terraform/command.getModules(0xc00036c4e0, 0xc0000ff980, 0x36, 0xc00039c101, 0x23, 0xc00039c180)
	/opt/gopath/src/github.com/hashicorp/terraform/command/get.go:84 +0x127
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc00036c4e0, 0xc00006c3f0, 0x0, 0x0, 0xc000305160)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:179 +0xac7
github.com/mitchellh/cli.(*CLI).Run(0xc000338500, 0xc000338500, 0xc0001c5d20, 0x1)
	/opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35

**Comment by nielssiebert** [comment]
got it fixed by deleting .terraform-folder in my terraform-project.

**Comment by albuquerquezman** [comment]
That work for me also!

**Comment by fprovencher** [comment]
Similar issue here:
2019/05/08 14:13:35 [INFO] Terraform version: 0.11.13
2019/05/08 14:13:35 [INFO] Go runtime version: go1.11.5
2019/05/08 14:13:35 [INFO] CLI args: []string{"C:\\repos\\fast\\bin\\terraform.exe", "plan"}
2019/05/08 14:13:35 [DEBUG] Attempting to open CLI config file: C:\Users\Owner\AppData\Roaming\terraform.rc
2019/05/08 14:13:35 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/05/08 14:13:35 [INFO] CLI command args: []string{"plan"}
2019/05/08 14:13:35 [TRACE] module source: "..\\..\\..\\modules\\SDK-1.20.0\\basic\\minimal_cluster"
2019/05/08 14:13:35 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc00030e140, 0x12, 0x33c4180, 0xc0003edf80, 0x0, 0xc000227760, 0xc00003c340, 0x1b0d40, 0x0, 0x39, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc00030e140, 0x12, 0x33c4180, 0xc0003edf80, 0x0, 0xc000227760, 0xc00003c380, 0x3b, 0x2, 0x2, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
github.com/hashicorp/terraform/config/module.Storage.findModule(0xc00030e140, 0x12, 0x33c4180, 0xc0003edf80, 0x0, 0xc000227760, 0xc00003c380, 0x3b, 0x0, 0x0, ...)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc000134100, 0xc0003bf920, 0xc000134138, 0xb28719, 0x300d660)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc000134100, 0xc0003bf920, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
github.com/hashicorp/terraform/command.(*Meta).Module(0xc0004151e0, 0xc00036ce80, 0x33, 0x0, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/command/meta_new.go:57 +0xc2
github.com/hashicorp/terraform/command.(*PlanCommand).Run(0xc0004151e0, 0xc0003edfc0, 0x2, 0x2, 0xc000323700)
        /opt/gopath/src/github.com/hashicorp/terraform/command/plan.go:77 +0xaf1
github.com/mitchellh/cli.(*CLI).Run(0xc000400140, 0xc000400140, 0xc0001dfd20, 0x1)
        /opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
main.wrappedMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
main.realMain(0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
main.main()
        /opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35

Terraform v0.11.13
+ provider.aws v2.8.0
+ provider.random v2.1.2
+ provider.template v2.1.2

Following the comments above, I went and deleted the .terraform/modules folder only which allowed me to work around the problem (got asked to run a terraform init to regenerate the modules files).

**Comment by apparentlymart** [comment]
Hi all! Sorry for this crash.

There is a bug in a file format upgrading codepath in Terraform 0.11.13 which is causing this crash.

The forthcoming 0.11.14 release will fix it, but in the mean time the workaround is to delete the `.terraform/modules` directory and then re-run `terraform init` to repopulate it. That will create the `modules.json` manifest in the new format, bypassing the buggy upgrade codepath.

**Comment by teamterraform** [comment]
Hello again!

As @apparentlymart mentioned, this was fixed in the later v0.11.14 release, so we're going to close this out now. Sorry for the crash, and thanks for reporting it.
