### ISSUE TITLE
Set an existing IAM role to an instance at spinup

### ISSUE THREAD

**Issue by zeninfinity** [hashicorp/terraform#2119]
New to terraform.  Love it so far.

I need to attach an existing IAM Role to an instance at spinup but I cannot find the correct syntax.  Can someone give me some insight on how to accomplish this?

Thanks,

ZZ

**Comment by zeninfinity** [comment]
Found it after some digging:

  iam_instance_profile = "Role_Name"

**Comment by tobiadeniji** [comment]
thanks for that @zeninfinity. Works for me.
