### ISSUE TITLE
Delete protection disabled by default for RDS Instances

### ISSUE THREAD

**Issue by gladosguru911** [hashicorp/terraform#21200]
deletion_protection - (Optional) If the DB instance should have deletion protection enabled. The database can't be deleted when this value is set to true. The default is false. 

This should be set to "true" by default to prevent deletion from trigger happy users.

**Comment by mildwonkey** [comment]
hi @gladosguru911 - I believe that you are asking for an enhancement to the rds instances created by `terraform-provider-aws`, so I will migrate this issue to the aws provider repository. If I have the wrong provider please comment here and I will fix that!
