### ISSUE TITLE
aws_acm_certificate with subject_alternative_names not maintaining order

### ISSUE THREAD

**Issue by giridharmp** [hashicorp/terraform#21229]
I am creating an AWS ACM certificate with the below terraform code:

resource "aws_acm_certificate" "alb_certificate" {
  domain_name               = "${var.subdomain}"
  validation_method         = "DNS"

  subject_alternative_names = ["api.example.com","kib.example.com","gra.example.com","pro.example.com","proapp.example.com","prom.example.com","promfro.example.com","dash.example.com","pgad.example.com"]
}

When we used to look into the issued certificate, in the additional names section, the above order in subject_alternative_names used to be maintained. But suddenly when we tried recently, the order is not being maintained and the names are getting used randomly. Because of this, when we refresh or want to update any other resource, a new certificate is always getting issued.

But the terraform plan is showing as below:
aws_acm_certificate.alb_certificate: Creating...
  arn:                         "" => "<computed>"
  domain_name:                 "" => "np"
  domain_validation_options.#: "" => "<computed>"
  subject_alternative_names.#: "" => "9"
  subject_alternative_names.0: "" => "api.example.com"
  subject_alternative_names.1: "" => "kib.example.com"
  subject_alternative_names.2: "" => "gra.example.com"
  subject_alternative_names.3: "" => "pro.example.com"
  subject_alternative_names.4: "" => "proapp.example.com"
  subject_alternative_names.5: "" => "prom.example.com"
  subject_alternative_names.6: "" => "promfro.example.com"
  subject_alternative_names.7: "" => "dash.example.com"
  subject_alternative_names.8: "" => "pgad.example.com"
  validation_emails.#:         "" => "<computed>"
  validation_method:           "" => "DNS"

**Comment by giridharmp** [comment]
CONTINUING....

but the order in "Additional names" in the certificate is as follows:
promfro.example.com, 
api.example.com, 
prom.example.com, 
proapp.example.com, 
pro.example.com, 
kib.example.com, 
dash.example.com, 
gra.example.com, 
pgad.example.com

The order in which the subject alternative names are mentioned need to be maintained.

**Comment by avestalea** [comment]
Me too - but only in ap-southeast-2 region

**Comment by axw-pivorra** [comment]
Same issue on us-east-1 for us!
