### ISSUE TITLE
Cannot parse custom provider with arguments (v0.12-beta2)

### ISSUE THREAD

**Issue by anasinnyk** [hashicorp/terraform#21248]
### Terraform Version

```
Terraform v0.12.0-beta2
+ provider.onepassword (unversioned)
```

### Terraform Configuration Files

```hcl
provider "onepassword" {
  email      = "your@email.here"
  password   = "super-master-password-here"
  secret_key = "secret-key-from-pdf-document"
}

resource "onepassword_vault" "vault" {
  name = "new"
}
```

### Debug Output

https://gist.github.com/anasinnyk/ece95ee6641f0dd40e18b97937670877

### Crash Output

none

### Expected Behavior

Plan successful

### Actual Behavior

Plan error
```
Error: exit status 1

  on main.tf line 1, in provider "onepassword":
   1: provider "onepassword" {
```

### Steps to Reproduce

1.  setup custom provider https://github.com/anasinnyk/terraform-provider-1password/releases/tag/0.2.0 (as example)
2. `terraform init`
3. `terraform plan`

### Additional Context

When I removed all provider arguments and use environment variables plan pass. 
Maybe `schema.EnvDefaultFunc` not working correct for terraform 0.12?

**Comment by apparentlymart** [comment]
Hi @anasinnyk! Sorry for this strange behavior.

Not being familiar with this provider means I don't have a lot to work with here, but from reading the source code I understood that the provider is performing its operations by downloading and launching a 1password CLI program distributed by AgileBits, and so I assume the `exit status 1` here is referring to that program returning non-successful status?

Have you determined already that this error is being returned from [the `SignIn` method](https://github.com/anasinnyk/terraform-provider-1password/blob/master/onepassword/provider.go#L210), where the values from the `provider` block arguments are being used? From the trace log I see that it's coming from the provider `Configure` operation, which is where the client would be instantiated, so I think that makes sense.

It may help to gather some more information, such as by generating some logs from that `SignIn` method (using the Go `log` package) to see what is populated in the `o.Subdomain`, `o.Email`, and `o.SecretKey` fields, and whether they match what you expect here. If those values contain something surprising then that'd be a good clue for us to figure out where that surprising value is coming from.

**Comment by anasinnyk** [comment]
@apparentlymart yeh you are right. Sorry. All works as expected.
