### ISSUE TITLE
Zone outages

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#2125]
Does Terraform allow continued infrastructure modification in the event of an availability zone outage?

I would expect there would need to be some commandline flag to ignore all resources (do not read / modify them) in a given zone.  However I'm not sure what the current thinking is on this.

**Comment by radeksimko** [comment]
I like this idea, although it may not be easy to implement across different providers.

**Comment by sparkprime** [comment]
A per region thing would be easier then (kill entire providers + attached resources).  That could definitely be done before the providers.

Do zonal outages actually occur in practice?

**Comment by sparkprime** [comment]
Well, they do: https://status.cloud.google.com/incident/compute/15056

However this was not the kind of outage where the API stopped working to the extent that calling that API would have confused Terraform, and therefore the proposed feature would not have been useful in that case.

**Comment by mitchellh** [comment]
This can be achieved with `-target` and laying out in a specific way (module per AZ for example). 

I think in the future targeting syntax will just become more advanced and this will become easier.
