### ISSUE TITLE
Terraform OCI Crash 

### ISSUE THREAD

**Issue by rakeshcknair** [hashicorp/terraform#21255]
[root@ip-172-16-24-176 PHX_DR_OD]# ./terraform --version
Terraform v0.11.13
+ provider.oci v3.0.0

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
* oci_core_dhcp_options.p-d-exacs-backup: 1 error(s) occurred:

* oci_core_dhcp_options.p-d-exacs-backup: oci_core_dhcp_options.p-d-exacs-backup: connection is shut down

**Comment by ravitandonrt** [comment]
@rakeshcknair - Can you add more details in the issue at: https://github.com/terraform-providers/terraform-provider-oci/issues/766
