### ISSUE TITLE
strconv.ParseInt panic when reading a float value into an `int`

### ISSUE THREAD

**Issue by chrisst** [hashicorp/terraform#21272]
### Terraform Version
```
2019/05/10 10:53:41 [INFO] Terraform version: 0.12.0 rc1
2019/05/10 10:53:41 [INFO] Go runtime version: go1.12.1
+ provider.google 2.7.0 (unreleased)
```

### Terraform Configuration Files
```hcl
resource "google_compute_backend_service" "go_clicks" {
  name          = "go-clicks"
  description   = "backend service for go-clicks from different clusters"
  health_checks = ["fake_self_link_for_github_issue"]

  load_balancing_scheme = "EXTERNAL"
  protocol = "HTTP"

  timeout_sec = 30.02

  backend {
    max_rate = 99999
    balancing_mode = "RATE"
  }
}
```

### Debug Output
https://gist.github.com/chrisst/1a500d9a40dbbaab2d1b540ea4a69a51

### Crash Output
https://gist.github.com/chrisst/a7100eb4dbe8ecf581c4157f03ebf6b1

### Expected Behavior
Terraform should throw a type validation error rather than panicking 

### Actual Behavior
panic: Error reading level config: strconv.ParseInt: parsing "30.02": invalid syntax

### Steps to Reproduce
1. Set a float value for a field defined as an integer
2. Terraform plan

### Additional Context
I confirmed this bug exists with Terraform 0.11 and a provider version running a pre 0.12 sdk as well (google-provider 2.4.1).

### References
May be related to https://github.com/hashicorp/terraform/issues/18121 however this doesn't require any migrations in order to repro. 
Could be the root cause of https://github.com/terraform-providers/terraform-provider-google/issues/3590

**Comment by oxlay** [comment]
> May be related to #18121
I'm not sure it's related, this other issue was really specific to `parsing "74D93920-ED26-11E3-AC10-0800200C9A66"`, which is a magic string in the code:
https://github.com/terraform-providers/terraform-provider-aws/blob/e1db8ae599a353d0063cdb2b57d964aa7a49e5ea/vendor/github.com/hashicorp/hil/convert.go#L14
