### ISSUE TITLE
0.11.13 init with -backend-config outside of current directory not loading config

### ISSUE THREAD

**Issue by adamdavis40208** [hashicorp/terraform#21288]
### Terraform Version
0.11.13

### Terraform Configuration Files
```
 …/code/gcp_init pwd                                                                       
/Users/r625040/Documents/code/gcp_init
 …/code/gcp_init  ls                                            
backend.tf              
 …/code/gcp_init cat backend.tf                                      
terraform {
 backend "gcs" {
   bucket  = "x25-terraform-admin-terraform-admin-state"
   prefix  = "terraform/state"
   project = "x25-terraform-admin"
 }
```

### Debug Output
(This is being ran from /Users/r625040/Documents/gcp, a different folder than where the backend-config file is) 
```
terraform init -backend-config=/Users/r625040/Documents/code/gcp_init/backend.tf         ✔
2019/05/13 14:34:37 [WARN] Invalid log level: "1". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR]
2019/05/13 14:34:37 [INFO] Terraform version: 0.11.13
2019/05/13 14:34:37 [INFO] Go runtime version: go1.12
2019/05/13 14:34:37 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.13/bin/terraform", "init", "-backend-config=/Users/r625040/Documents/code/gcp_init/backend.tf"}
2019/05/13 14:34:37 [DEBUG] Attempting to open CLI config file: /Users/r625040/.terraformrc
2019/05/13 14:34:37 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/05/13 14:34:37 [INFO] CLI command args: []string{"init", "-backend-config=/Users/r625040/Documents/code/gcp_init/backend.tf"}
2019/05/13 14:34:37 [DEBUG] command: loading backend config file: /Users/r625040/Documents/gcp
2019/05/13 14:34:37 [INFO] command: empty terraform config, returning nil
2019/05/13 14:34:37 [DEBUG] command: no data state file found for backend config
```

### Expected Behavior
-backend-config=PATH should load that file, however it's searching the current directory 

### Actual Behavior
Terraform is checking the current dir for the backend-config

### Steps to Reproduce
1. Create a backend config in a different folder
2. Try to `init -backend-config=/PATH` that file

**Comment by jbardin** [comment]
Hi @adamdavis40208,

Sorry about the confusion here. The argument to '-backend-config=PATH` is not an HCL `.tf` file, rather it's a list of key-value pairs, similar to tfvars. You must declare the backend in the primary configuration, and then you can parameterize this by providing the particular backend configuration through the `-backend-config` file rather than declaring each individual parameter on the command line.  

You can see the [Partial Configuration](https://www.terraform.io/docs/backends/config.html#partial-configuration) section of the backend docs for more information and examples.

**Comment by adamdavis40208** [comment]
>File: A configuration file may be specified via the init command line. To specify a file, use the -backend-config=PATH option when running terraform init

So the documentation is just invalid, and the File section of the page you linked is out of date?

Command-line key/value pairs is the next section, which is fine, the documentation just threw me for a bit.

**Comment by jbardin** [comment]
Nope, the file section is correct, but I agree it's a bit confusing at first since it's essentially a different format. A little further down there's a description of what a that file can contain

> A backend configuration file has the contents of the backend block as top-level attributes, without the need to wrap it in another terraform or backend block:
>
>     address = "demo.consul.io"
>     path    = "example_app/terraform_state"
>     scheme  = "https"
