### ISSUE TITLE
*.auto.tfvars file not being read

### ISSUE THREAD

**Issue by designermonkey** [hashicorp/terraform#21303]
### Terraform Version

```
Terraform v0.11.13
+ provider.ansible v1.0.0
```

### Terraform Configuration Files

in digitalocean.auto.tfvars

```hcl
variable "ssh_fingerprint" {
  type = "string"
  description = "The MD5 fingerprint of the SSH key for droplet operations"
  default = "hash"
}
```

in nodes_managers.tf

```hcl
resource "digitalocean_droplet" "man01" {
  image = "ubuntu-18-04-x64"
  name = "man01"
  region = "lon1"
  size = "2gb"
  private_networking = true

  ssh_keys = [
      "${var.ssh_fingerprint}"
  ]
}

```

### Debug Output
TF_LOG=trace terraform init
2019/05/14 17:50:19 [INFO] Terraform version: 0.11.13  
2019/05/14 17:50:19 [INFO] Go runtime version: go1.12
2019/05/14 17:50:19 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.13/bin/terraform", "init"}
2019/05/14 17:50:19 [DEBUG] Attempting to open CLI config file: /Users/john/.terraformrc
2019/05/14 17:50:19 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/05/14 17:50:19 [INFO] CLI command args: []string{"init"}
2019/05/14 17:50:19 [DEBUG] command: loading backend config file: /Users/john/Projects/operations/terraform/ops
2019/05/14 17:50:19 [INFO] command: empty terraform config, returning nil
2019/05/14 17:50:19 [DEBUG] command: no data state file found for backend config
2019/05/14 17:50:19 [DEBUG] New state was assigned lineage "49c5e8e6-4b11-75fd-9078-636a9b4d82d7"
2019/05/14 17:50:19 [INFO] command: backend initialized: <nil>
2019/05/14 17:50:19 [DEBUG] checking for provider in "."
2019/05/14 17:50:19 [DEBUG] checking for provider in "/usr/local/Cellar/terraform/0.11.13/bin"
2019/05/14 17:50:19 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2019/05/14 17:50:19 [DEBUG] found provider "terraform-provider-ansible_v1.0.0"
2019/05/14 17:50:19 [DEBUG] found valid plugin: "ansible", "1.0.0", "/Users/john/Projects/operations/terraform/ops/.terraform/plugins/darwin_amd64/terraform-provider-ansible_v1.0.0"
2019/05/14 17:50:19 [DEBUG] checking for provisioner in "."
2019/05/14 17:50:19 [DEBUG] checking for provisioner in "/usr/local/Cellar/terraform/0.11.13/bin"
2019/05/14 17:50:19 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"

Error: resource 'digitalocean_droplet.man01' config: unknown variable referenced: 'ssh_fingerprint'; define it with a 'variable' block
2019/05/14 17:50:19 [INFO] command: backend <nil> is not enhanced, wrapping in local

2019/05/14 17:50:19 [ERROR] 1 problems:

- resource 'digitalocean_droplet.man01' config: unknown variable referenced: 'ssh_fingerprint'; define it with a 'variable' block
2019/05/14 17:50:19 [DEBUG] plugin: waiting for all plugin processes to complete...
```

### Expected Behavior

I thought that it would read the file and provide the default value.

### Actual Behavior

Unknown variable error.

**Comment by apparentlymart** [comment]
Hi @designermonkey,

The correct syntax for a `.tfvars` file is just a variable assignment, like this:

```hcl
ssh_fingerprint = "any value"
```

A variable _declaration_ belongs in a `.tf` file, and conventionally in the `variables.tf` file in particular. If you don't intend to override the default value, you don't need a `.tfvars` file at all.

**Comment by designermonkey** [comment]
Ahhhhh, ok. Is that something I missed in the docs? Would you point me to it? I find them a little confusing for a first timer :)

**Comment by apparentlymart** [comment]
I can see that [the documentation for Terraform v0.11](https://www.terraform.io/docs/configuration-0-11/variables.html) is not so clear about declaration vs. assignment.

[The equivalent documentation for the forthcoming v0.12 release](https://www.terraform.io/docs/configuration/variables.html) was rewritten and reorganized, and I hope it's now clearer about this distinction. The exact syntax described on that page is not compatible with Terraform 0.11, but the information about "Assigning Values to Root Module Variables" is broadly true for Terraform 0.11 too.

**Comment by designermonkey** [comment]
I've been reading the wrong docs though too lol. Thanks for your time.
