### ISSUE TITLE
feature request: update aws_instance resource to support declaring Shutdown behavior

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#2130]
AWS instances can be configured to either stop or terminate when they shutdown. I do not see this documented https://terraform.io/docs/providers/aws/r/instance.html. The antithesis to this is supporting the termination protection flag. Thanks for considering!

**Comment by catsby** [comment]
Hey @ketzacoatl thanks for writing in. 
Are you suggesting a `stopped` state, but still visible / tracked in Terraform, or `stop` as a "destroyed" state, such that we'll run `Delete` in TF, which will actually stop the instance, and then TF will remove it from state? 

At first pass that seems like we'd be leaving resources dangling (maybe not a big deal to some), with no way to re-connect Terraform to that instance. Running `plan` would then want to create a new instance. 

Is that the behavior you're thinking of? If there are others, please mention them and we'll think about things here. 

Thanks!

**Comment by catsby** [comment]
I may have introduced confusion here by implying some kind of state management here (`running` vs. `stopped`). Re-reading and discussing, I think you simply meant the `InstanceInitiatedShutdownBehavior` property in the API for running an instance (documented [here][1]). Is that correct? 

Additionally, termination protection was recently added to the project in https://github.com/hashicorp/terraform/pull/1988 , which will be included in the next release of Terraform (should be in the next week or so).

[1]: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html

**Comment by ketzacoatl** [comment]
Hi @catsby, yes, I am referring to the `InstanceInitiatedShutdownBehavior` property in the API. I could have been more clear with a link to docs, sorry.

Thank you also for the reference to the support for termination protection, I see similar functionality also in the `lifecycle` docs and will try to make use of it.

As for this feature with the Shutdown behavior, if I guess if the instance is stopped, TF could ignore it, but might need to update/refresh state if the user starts the instance back up (out of band from TF). Similarly, if the instance is set to terminate on shutdown, and a fresh would show it as gone, and by default would try to re-create it. For the use cases I have, I would combine this with a conditional that allowed me to control when the new instance was re-created.

**Comment by pschultz** [comment]
We also want support for this option in Terraform, and would expect Terraform to re-create instances that have been terminated between two runs.

We're exploring the use of Terraform for our build process. During the build, we want Terraform to launch a number of build slaves and configure them to poweroff after N minutes (AWS would then terminate them). If during those N minutes another build is triggered, the slaves already exist and the provisioner resets the poweroff timer.

**Comment by tamsky** [comment]
> We ... would expect Terraform to re-create instances that have been terminated between two runs.

+1 to simply exposing the `InstanceInitiatedShutdownBehavior` API element, and treating missing resources like any other.

**Comment by stack72** [comment]
@catsby / @jen20 / @phinze this can be closed. This is already in place

**Comment by phinze** [comment]
My favorite kind of notification. :heart: @stack72
