### ISSUE TITLE
how to use count.index with the template_file resource?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#2132]
I created a `template_file` resource like so:

```
resource "template_file" "foobar" {
    filename = "templates/init-foobar.tpl"
    vars {
       name = "${var.env}"
       count = "${count.index}"
       master = "${aws_instance.master.private_ip}"
    }
}
```

I then use this template for `user_data` in an `aws_instance` resource using `count`, and the expectation is for the count index associated with the instance resource to be included (if by magick) in the context provided when rendering the template. In other words, for each `aws_instance` we create with `count`, we have `count.index` we can pass to `template_file.foo.rendered` in some way, maybe?

**Comment by arothian** [comment]
Take a look at the comments in https://github.com/hashicorp/terraform/issues/1893. It has a good example of generating unique user_data per aws_instance when you are using count. Perhaps the documentation for template_file could be expended to include this common use case, as it wasn't initially obvious how to do this for me either.

**Comment by ketzacoatl** [comment]
Good recommendation @arothian, I have created #2140 for just that.
