### ISSUE TITLE
Terraform Crashed. Error indicated to send log.

### ISSUE THREAD

**Issue by kansberry** [hashicorp/terraform#21337]
Terraform v0.11.13

Ran Terraform script through Concourse on the 8th. When I went to run today, received the following below, so attaching the crash.log file here.

Please let me know if you find something. Really need to apply and update to our environment.

Thanks.

[crash.log](https://github.com/hashicorp/terraform/files/3188233/crash.log)

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by apparentlymart** [comment]
Hi @kansberry! Sorry for this crash, and thanks for reporting it.

The stack trace in this output is the following:

```
panic: runtime error: index out of range

goroutine 652 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm.flattenApplicationGatewayAuthenticationCertificates(0xc0002b8e80, 0xc0002f1b90, 0x5, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_application_gateway.go:1276 +0x55b
github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmApplicationGatewayRead(0xc0002f1b90, 0x2677a80, 0xc000798000, 0xc0002f1b90, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_application_gateway.go:1113 +0x683
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc0005d1570, 0xc0003ab7c0, 0x2677a80, 0xc000798000, 0xc00051a250, 0x4c3901, 0x22aaa00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x160
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc000c8e8c0, 0xc0003ab770, 0xc0003ab7c0, 0xc00007a380, 0xc000ea2b88, 0x7faf9d66ed80)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc00043bb00, 0xc00088be30, 0xc00088bf50, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
reflect.Value.call(0xc000137560, 0xc00000cdb8, 0x13, 0x26af6e5, 0x4, 0xc000ea2f18, 0x3, 0x3, 0xc0006adb40, 0xc0012f3500, ...)
	/opt/goenv/versions/1.11.5/src/reflect/value.go:447 +0x454
reflect.Value.Call(0xc000137560, 0xc00000cdb8, 0x13, 0xc000557f18, 0x3, 0x3, 0x0, 0x0, 0x1000000010000)
	/opt/goenv/versions/1.11.5/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc000142040, 0xc0007fc0f0, 0xc000b9a2d0, 0xc000b9a360, 0xc0003e6a80, 0xc00096d9c0, 0x22aa9c0, 0xc00088be30, 0x16, 0x22aaa00, ...)
	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
	/opt/goenv/versions/1.11.5/src/net/rpc/server.go:481 +0x47e
```

This tells me that the crash is actually in the Azure provider rather than in Terraform Core, so I'm going to request for our GitHub bot to move this issue over into the Azure provider repository.

**Comment by kansberry** [comment]
I just attempted to use the latest azurerm provider, and still the same results. Attaching the crash.log for that run. My instinct is that may have something to do with using the new application gateway redirects within more than one AG? See the index out of range and prior runs I only had one gateway redirecting https traffic to http. Now have two.

[crash.log](https://github.com/hashicorp/terraform/files/3188392/crash.log)
