### ISSUE TITLE
terraform provisioner for Puppet

### ISSUE THREAD

**Issue by Prabhakar-cg** [hashicorp/terraform#21335]
Hi There,

i am using terrafom version 0.11.6 for the providers like AWS & Openstack.

Now i am using puppet as my configuration management tool for application automation. So is there any way to use puppet as my provisioner during terraform activity. 

i could see that currently terraform has provisioners for salt & chef [https://www.terraform.io/docs/provisioners/chef.html]. can someone advise how to get a provisioner for puppet as well.

**Comment by apparentlymart** [comment]
Hi @Prabhakar-cg,

Currently the only way to run Puppet would be to use the generic `remote-exec` provisioner to launch it. However, there is a Puppet provisioner in #18851 waiting to be merged once the v0.12.0 release's feature freeze is ended, so it should be included in one of the forthcoming v0.12.x releases.

**Comment by Prabhakar-cg** [comment]
@apparentlymart thanks for the response:).

that's really nice to hear about the puppet provisioner and i hope it will support puppet-masterless concept as well.

**Comment by apparentlymart** [comment]
It was a third-party contribution and I'm not familiar enough with Puppet myself to know that, but even if the first PR does not I expect we'd accept a pull request to add it later, once the first PR is merged.
