### ISSUE TITLE
Call to function "slice" failed: invalid start index: value must be known.

### ISSUE THREAD

**Issue by cyrus-mc** [hashicorp/terraform#21338]
Currently working on migrating all my modules to version 0.12. Ran into this issue which worked under 0.11.x.

```
› terraform -v
Terraform v0.12.0-beta2
+ provider.aws v2.10.0
+ provider.template v2.1.2

```

### Terraform Configuration Files

```hcl
locals {
  attributes = [
    {
      name = var.range_key
      type = var.range_key_type
    },
    {
      name = var.hash_key
      type = var.hash_key_type
    },
    var.attributes
  ]

  /* if range_key not specified, remove from attributes list */
  from_index       = length(var.range_key) > 0 ? 0 : 1
  attributes_final = slice(local.attributes, local.from_index, length(local.attributes))
}

```

Basically this code block was used to set the attributes on a dynamodb table. If a range key was specified it was included in the attributes, if not, the slice operation simply removed the first element in local.attributes

When I run this in 0.12 I get:

```
   invalid start index: value must be known.
```

If replace local.from_index with 0 it works. So to me it appears an order of operations thing in which terraform is trying to evaluate the slice operation before calculating the from_index.

### Expected Behavior

My expectation (and how it worked in 0.11) was that local.from_index either evaluated to 0 or 1 based on the presence of a supplied range_key. That would then slice the array accordingly.

### Actual Behavior

Results in the error noted above.

**Comment by apparentlymart** [comment]
Thanks for reporting this, @cyrus-mc!

Indeed, this should work, and should cause the result of the function to be an unknown value.

I can see the cause of the bug in the code here:
https://github.com/hashicorp/terraform/blob/11cf8fd6bee989016e8ec1c70b4b47e5445f3693/lang/funcs/collection.go#L1087-L1090

This `sliceIndexes` function expects the start and end indices to already be known, so this function needs to check first that both of them are known and return a suitable placeholder type in this case. We'll get that fixed up. Thanks again for reporting!

**Comment by cyrus-mc** [comment]
@apparentlymart 

No worries. I was able to work around it as follows

```hcl
locals {
  attribute_hash_key = [
    {
      name = var.hash_key
      type = var.hash_key_type
    }
  ]

  attribute_range_key = [
    {
      name = var.range_key
      type = var.range_key_type
    }
  ]

  /* if range_key is specified, concat that with attributes list */
  attributes_hash_key = concat(local.attribute_hash_key, var.attributes)
  attributes_final = (length(var.range_key) > 0 ? concat(local.attribute_range_key, local.attributes_hash_key) :
                                                  local.attributes_hash_key)

```
