### ISSUE TITLE
Elevator Music

### ISSUE THREAD

**Issue by MaxProvin** [hashicorp/terraform#21331]
### Current Terraform Version
```
Terraform v0.11.13
```

### Use-cases
- Make terraform great again
- Boring deployment wait periods could be improved by playing some monotonous elevator music

**Comment by apparentlymart** [comment]
Hi @MaxProvin!

Thanks for this feature request! We're busy working on the next release right now, but if you or anyone else in the community has the time and motivation to work on elevator music we'd love to review a PR! :wink: 

Seriously, though: we released Terraform v0.11.14 today. Terraform v0.12 is coming in a week or two. We know it's been longer than expected, and believe me that the many people who have been working on it would _love_ to be finished with it too!
