### ISSUE TITLE
ignore_changes example in docs doesn't work

### ISSUE THREAD

**Issue by kabo** [hashicorp/terraform#21342]
### Terraform Version
```
$ terraform --version
Terraform v0.11.13
+ provider.aws v2.10.0
```

### Terraform Configuration Files
```hcl
resource "aws_subnet" "dev_internal_c" {
  vpc_id            = "${var.vpc_dev_id}"
  cidr_block        = "xxx"
  availability_zone = "eu-west-1c"
  tags = "${merge(
    local.common_tags,
    map("Name", "DEV-INTERNAL-1C")
  )}"
  lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      tags,
    ]
  }
}

```

### Crash Output
```
$ terraform apply

Error: Error parsing setup.tf: At 11:7: unexpected token while parsing list: IDENT
```

### Expected Behavior
I expected it to run, but ignoring any changes to the tags of this resource.

### Actual Behavior
It exited with an error.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
The `lifecycle` block is copy-pasted directly from the docs
https://www.terraform.io/docs/configuration/resources.html#ignore_changes

**Comment by kabo** [comment]
Ah, quotes seems to fix it.

```hcl
ignore_changes = [ "tags" ]
```

**Comment by jbardin** [comment]
Hi @kabo,

Sorry about the confusion. You're looking at the 0.12 docs but using 0.11. There's a link to the older docs at the top of that page: https://www.terraform.io/docs/configuration-0-11/resources.html#ignore_changes

The old config language required a string for that field.

**Comment by kabo** [comment]
Oh wow (!)
I bet you were discussing in what order to release stuff and someone was like "let's release the docs first, check that it's all good, then release the new version", and someone else was like "but what if someone is reading the docs with breaking changes and doesn't have access to the new binary?", and the first guy's like "oh come on, that's not gonna happen".

:D
