### ISSUE TITLE
Inappropriate value for attribute "non_key_attributes": list of string

### ISSUE THREAD

**Issue by cyrus-mc** [hashicorp/terraform#21340]
For starters, I am not sure if this is a bug or just me not knowing the new syntax as well as I should.

When trying to use dynamic blocks to configure GSI on a dynamoDB table get the above error. The value for non_key_attributes is a list of strings.

If I use a simple for_each (with no transformation) I get this error. If I use a transformation which simply sets the value (no actual transformation) it works.

```
› terraform -v
Terraform v0.12.0-beta2
+ provider.aws v2.10.0
```

### Terraform Configuration Files

This code block results in the error noted.

```hcl
  dynamic "global_secondary_index" {
    for_each = var.global_secondary_index

    content {
      name               = global_secondary_index.value.name
      hash_key           = global_secondary_index.value.hash_key
      projection_type    = global_secondary_index.value.projection_type
      range_key          = lookup(global_secondary_index.value, "range_key", "null")
      non_key_attributes = lookup(global_secondary_index.value, "non_key_attributes", "null")
      //non_key_attributes = global_secondary_index.value.non_key_attributes
      read_capacity      = lookup(global_secondary_index.value, "read_capacity", "null")
      write_capacity     = lookup(global_secondary_index.value, "write_capacity", "null")
    }
  }
```

If I modify to the following, I do not receive the error

```hcl  
  dynamic "global_secondary_index" {
   
    for_each = [ for gsi in var.global_secondary_index: {
                   hash_key = gsi.hash_key
                   name     = gsi.name
                   non_key_attributes = lookup(gsi, "non_key_attributes", null)
                   projection_type = gsi.projection_type
                   range_key = lookup(gsi, "range_key", null)
                   read_capacity = lookup(gsi, "read_capacity", null)
                   write_capacity = lookup(gsi, "write_capacity", null) }
                ]

    content {
      name                        = global_secondary_index.value.name
      hash_key                 = global_secondary_index.value.hash_key
      projection_type      = global_secondary_index.value.projection_type
      range_key               = global_secondary_index.value,.range_key
      non_key_attributes = global_secondary_index.value.non_key_attributes
      read_capacity        = global_secondary_index.value.read_capacity
      write_capacity       = global_secondary_index.value,.write_capacity
    }
  }

```
### Expected Behaviour

I would expect the first code block to work as it (at least to me) appears equivalent to the second. Since I am not doing any transformations I should not have to use the second form.

**Comment by cyrus-mc** [comment]
Forgot to add the what the input looks like

```hcl
  global_secondary_index = [
    {
      name            = "OrgIdIndex"
      hash_key        = "posterOrgId"
      projection_type = "ALL"
      read_capacity   = 5
      write_capacity  = 5
    },
    {
      name               = "PostingExpiryIndex"
      hash_key           = "postingEndDate"
      range_key          = "postingEndTime"
      projection_type    = "INCLUDE"
      non_key_attributes = [ "loadId", "posting" ]
      read_capacity      = 5
      write_capacity     = 5
    }
  ]
```

**Comment by apparentlymart** [comment]
Thanks for reporting this, @cyrus-mc!

I think the problem Terraform is detecting here is that in your first example the default values for `range_key` and `non_key_attributes` are both the string `"null"` rather than the keyword `null`, so it's reporting that a string can't be converted into a list of strings.

I think if you remove the quotes around `null` then you'll get the same effect as in the second example, where the nulls were not quoted.

By the way, there is now a [release candidate 1](https://www.hashicorp.com/blog/releasing-terraform-0-12-0-rc1) of Terraform v0.12.0, in case you'd like to upgrade. Several fixes found during the beta2 period are included in that release.

**Comment by cyrus-mc** [comment]
@apparentlymart 

Yep. That was it. Thanks for the quick response.
