### ISSUE TITLE
Can't download modules via git ssh with port

### ISSUE THREAD

**Issue by namutaka** [hashicorp/terraform#21372]
### Terraform Version

```
% terraform -v
Terraform v0.12.0-rc1
+ provider.aws v2.11.0
```

### Terraform Configuration Files

```hcl
module "sample" {
  # Use port 3789
  source = "git::ssh://git@my.example.com:3789/sample/terraform-modules.git"
}
```

### Debug Output

https://gist.github.com/namutaka/ac31a0623a3f568f577a6a6a734324f6

### Expected Behavior

Success download modules.

### Actual Behavior

Failed to download module.

### Steps to Reproduce

1. `terraform init`

### Additional Context

I think specified port in URL is not work in downloading. 
I tried to specify a port in .ssh/config instead in URL. It was success to download.

```
# ~/.ssh/config
Host my.example.com
  Port 3789
```

```hcl
module "sample" {
  source = "git::ssh://git@my.example.com/sample/terraform-modules.git"
}
```

**Comment by llomgui** [comment]
Fixed: https://github.com/hashicorp/terraform/issues/21257

**Comment by namutaka** [comment]
Thank you!! I'll wait for 0.12 release.
