### ISSUE TITLE
0.12 "dynamic" blocs fail with empty iterator

### ISSUE THREAD

**Issue by xlz-jgoutin** [hashicorp/terraform#21373]
### Terraform Version
```
Terraform v0.12.0-rc1
```

### Terraform Configuration Files

This is based on the [dynamic block example](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) from the 0.12 documentation:
```hcl
variable "service_ports" {
  type = list(number)
  default = []
}

resource "aws_security_group" "example" {
  name = "example"

  dynamic "ingress" {
    for_each = var.service_ports
    content {
      from_port = ingress.value
      to_port   = ingress.value
      protocol  = "tcp"
    }
  }
}
```

### Actual Behavior

If `var.service_ports` is an empty list, Terraform fail and return the following error:

```
Error: Unsupported block type

  on aws.tf line 9, in resource "aws_security_group" "example":
   9:   dynamic "ingress" {

Blocks of type "ingress" are not expected here.
```

### Expected Behavior

If `var.service_ports` is an empty list, Terraform should not generate any `ingress` block in the security group and continue successfully instead of failing.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` (This will use the default empty list for `var.service_ports`).

**Comment by jbardin** [comment]
Hi @xlz-jgoutin,

Thanks for pointing that out. That example needs to be updated for now, because the AWS provider has been modified to use attribute syntax for the `ingress` and `egress` values.

**Comment by jbardin** [comment]
Hi @xlz-jgoutin,

Thanks filing the issue! Sorry, I initially misunderstood the issue, that syntax does work in this case, but you are correct that does fail only with the empty collection.

**Comment by hasheddan** [comment]
@jbardin @xlz-jgoutin I am interested in helping out here! Is this a change that we definitely want to make, or is it potentially a feature to fail on an empty collection?
