### ISSUE TITLE
Local backend workspace_dir argument not documented

### ISSUE THREAD

**Issue by nccurry** [hashicorp/terraform#21391]
### Current Terraform Version

```
Terraform v0.11.14
```

### Use-cases

Specify the ```path``` configuration for the ```local``` backend when using workspaces to determine where the terraform.tfstate.d directory is placed on the local filesystem.

I would like to be able to specify something like

```
terraform {
  backend "local" {
   path: "/path/to/directory"
 }
}
```
or
```
terraform {
  backend "local" {
    workspace_dir_path = "/path/to/directory"
  }
}
```

And when applying a plan inside a non-default workspace the state is stored in 
```
/path/to/directory/terraform.tfstate.d/<workspace>/...
```

### Attempted Solutions

Trying to supply a directory as backend path:

The following terraform plan
```
terraform {
  backend "local" {
    path = "./state"
  }
}

resource "local_file" "foo" {
    content     = "${terraform.workspace}"
    filename = "${path.module}/${var.name}"
}
```

when executing the following

```
$ terraform init
$ terraform workspace new one
$ terraform apply -var "name=one"
$ terraform workspace new two
$ terraform apply -var "name=two"
```
results in following directory structure
```
$ tree
.
├── main.tf
├── one
├── state
├── terraform.tfstate.d
│   ├── one
│   └── two
├── two
└── vars.tf
```
Where the file state contains the state for the second terraform apply ```terraform apply -var "name=two"``` which has overwritten the state for the first terraform apply ```terraform apply -var "name=one"```.

Alternately trying to supply a backend path based on the workspace:

```
terraform {
  backend "local" {
  }
}

resource "local_file" "foo" {
    content     = "${terraform.workspace}"
    filename = "${path.module}/${var.name}"
}
```
```
$ terraform init -backend-config='path=./state/one'
$ terraform workspace new one
$ terraform apply -var "name=one"
$ terraform init -backend-config='path=./state/two'
$ terraform workspace new two
$ terraform apply -var "name=two"
```
Results in terraform asking to migrate the state from the file ```./state/one``` to ```./state/two```.

Finally if we don't specify the path value at all, terraform defaults to using the working directory
```
terraform {
  backend "local" {
  }
}

resource "local_file" "foo" {
    content     = "${terraform.workspace}"
    filename = "${path.module}/${var.name}"
}
```
```
$ terraform init
$ terraform workspace new one
$ terraform apply -var "name=one"
$ terraform workspace new two
$ terraform apply -var "name=two"
```
```
$ tree
.
├── main.tf
├── one
├── terraform.tfstate.d
│   ├── one
│   │   └── terraform.tfstate
│   └── two
│       └── terraform.tfstate
├── two
└── vars.tf
```

### Proposal

What would be ideal is if it would be possible to supply the root directory for the terraform.tfstate.d directory in the backend configuration.

```
terraform {
  backend "local" {
    path = "/path/to/terraform.tfstate"
    workspace_dir_path = "/path/to/directory"
  }
}
```

**Comment by apparentlymart** [comment]
Hi @nccurry!

I'm not sure why it's missing from the documentation, but the local backend already has a `workspace_dir` argument that should control where Terraform looks to find non-default workspaces.

If that works for you, then we can use this issue to represent the task of updating the documentation.

**Comment by nccurry** [comment]
@apparentlymart Awesome! That had the intended effect:

```
terraform {
  backend "local" {
    workspace_dir = "./state"
  }
}

resource "local_file" "foo" {
    content     = "${terraform.workspace}"
    filename = "${path.module}/${var.name}"
}
```
```
$ terraform init
$ terraform workspace new one
$ terraform apply -var "name=one"
$ terraform workspace new two
$ terraform apply -var "name=two"
```

```
$ tree
.
├── main.tf
├── one
├── state
│   ├── one
│   │   └── terraform.tfstate
│   └── two
│       └── terraform.tfstate
├── two
└── vars.tf
```
