### ISSUE TITLE
Alternate Provider Docs may be incorrect.

### ISSUE THREAD

**Issue by rohrerb** [hashicorp/terraform#21406]
I believe that docs are incorrect. > https://www.terraform.io/docs/configuration/providers.html#referring-to-alternate-providers

If you use the provider reference without double quotes you receive a error. The docs specifically say that you don't need to quote.   Should the docs change?

Error:
```
Unknown token: 17:14 IDENT azurerm.global
```

Example:
```
provider "azurerm" {
     subscription_id = "7d559a72-xxxx-xxxx-xxxx-5ca5b14a25e7"
}
 
provider "azurerm" {
  alias = "global"
  subscription_id = "b28c25e6-xxxx-xxxx-xxxx-41a60e4a9b20"
 
}
 
resource "azurerm_resource_group" "azurerm_prov_1" {
  name     = "azurerm_prov_1"
  location = "westus"
}
 
resource "azurerm_resource_group" "azurerm_prov_2" {
  provider = azurerm.global
  name     = "azurerm_prov_2"
  location = "westus2"
}
 
data "azurerm_resource_group" "azurerm_prov_1" {
  name = "${azurerm_resource_group.azurerm_prov_1.name}"
}
 
data "azurerm_resource_group" "azurerm_prov_2" {
  name = "${azurerm_resource_group.azurerm_prov_2.name}"
}

```

**Comment by jbardin** [comment]
Hi @rohrerb,

Sorry about the confusion, that error looks like you're running Terraform 0.11 or earlier. The docs you linked to are for 0.12. There's a link at the top of the page to ole old documentation: https://www.terraform.io/docs/configuration-0-11/providers.html
