### ISSUE TITLE
Panic on plan after upgrade to 0.12

### ISSUE THREAD

**Issue by infonaut** [hashicorp/terraform#21407]
### Terraform Version

```
Terraform v0.12.0
+ provider.aws v2.10.0
+ provider.template v2.1.2
```

### Debug Output

Encrypted gist: https://gist.github.com/infonaut/b83d841911f9f1c5c0434f10136c430d

### Crash Output

Encrypted gist: https://gist.github.com/infonaut/3b490542e6e1237429d4a3ed2b377ed0

### Actual Behavior
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1ab148e]

goroutine 2399 [running]:
github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).References(0xc000c40410, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/terraform/node_resource_abstract.go:241 +0xae
github.com/hashicorp/terraform/terraform.NewReferenceMap(0xc00178f400, 0x231, 0x231, 0x231)
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/terraform/transform_reference.go:402 +0x24a
github.com/hashicorp/terraform/terraform.(*ReferenceTransformer).Transform(0x3c7e578, 0xc001f6fc70, 0x14, 0x0)
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/terraform/transform_reference.go:73 +0x71
github.com/hashicorp/terraform/terraform.(*BasicGraphBuilder).Build(0xc00098fce0, 0x0, 0x0, 0x0, 0x3c5e920, 0xc001dcfd10, 0x10e2760, 0xc0000d0000)
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/terraform/graph_builder.go:50 +0x477
github.com/hashicorp/terraform/terraform.(*PlanGraphBuilder).Build(0xc00292ddc0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x24e86a0, 0xc0013d4f00)
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/terraform/graph_builder_plan.go:65 +0xbc
github.com/hashicorp/terraform/terraform.(*Context).Graph(0xc000190000, 0x2854703, 0xc001dcfd66, 0xc000190000, 0xc00029cce0, 0x3c7e578, 0xc001822480)
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/terraform/context.go:292 +0x1b8
github.com/hashicorp/terraform/terraform.(*Context).Plan(0xc000190000, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/terraform/context.go:546 +0x566
github.com/hashicorp/terraform/backend/local.(*Local).opPlan.func2(0xc001478b40, 0xc000190000, 0xc0000c37c0, 0xc00250e740)
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:105 +0x83
created by github.com/hashicorp/terraform/backend/local.(*Local).opPlan
	/private/tmp/terraform-20190523-61862-1w2ypr9/terraform-0.12.0/src/github.com/hashicorp/terraform/backend/local/backend_plan.go:102 +0x4af
```

Does not appear to be a provider issue.

**Comment by mildwonkey** [comment]
Hey @infonaut ! I *think* you have the honor of reporting the first 0.12.0 crash - THANK YOU for the report 😁 (and I am sorry that it happened!)

I need a little more information to start looking at this - can you please include your terraform configuration files (or at least enough for us to reproduce the issue locally)? 

I presume that this is encrypted with the public `security@hashicorp.com` key; please speak up if I am mistaken.

Thanks again, and I'm sorry you ran into this crash!

**Comment by infonaut** [comment]
Hi. I shall take that badge of honour ;)

Yes it's they key from keybase.


[files.zip](https://github.com/hashicorp/terraform/files/3212843/files.zip)

**Comment by mildwonkey** [comment]
Thanks for the additional information @infonaut!
Did you use `terraform 0.12upgrade` to upgrade these modules? I noticed a few things that (I think) suggested they were upgraded manually but I could be mistaken.

**Comment by infonaut** [comment]
Hi @mildwonkey  They were upgraded with 0.12upgrade. A few things had to be done by hand. For example, a flatten on a list of security groups inside a list of security groups.

**Comment by invidian** [comment]
[crash.zip](https://github.com/hashicorp/terraform/files/3218797/crash.zip)

It seems that I also hit this issue. I uploaded state file, which allows to reproduce the crash if you run `terraform destroy`.

**Comment by apparentlymart** [comment]
I think hashicorp/terraform#21445 is a fix for this.

**Comment by nauxliu** [comment]
Will this be fixed in v0.12.1?  we were bitten by this too.

**Comment by mildwonkey** [comment]
@nauxliu and @infonaut:
I believe this is fixed by #21445, but this is a particularly difficult situation to reproduce. If either of you would like to test the fix immediately - and this is entirely up to you - you could build terraform from master. Again, I will leave that up to you; the fix will be included in v0.12.1.

**Comment by nauxliu** [comment]
@mildwonkey I tried a build from the master，this crash is gone, But now I'm running into another crash #21396

**Comment by mildwonkey** [comment]
Thanks, I really appreciate your help testing that @nauxliu! 

I'll close this issue, and we will get to work on the next one :)

**Comment by infonaut** [comment]
Salute to you @nauxliu that was a quick build and test!

@mildwonkey for me however this build worked and did not cause a crash.

Thanks!
