### ISSUE TITLE
Upgrade to 0.12 forces change in tag names

### ISSUE THREAD

**Issue by jheadley** [hashicorp/terraform#21413]
### Terraform Version

```
Terraform v0.12.0
+ provider.aws v2.11.0
```

### Terraform Configuration Files

This used to be valid but now as part of the upgrade the quotes must be removed or you will get the error "Argument names must not be quoted". However, if you remove the quotes around the tag's name, you will get the error "An argument or block definition is required here".  This is forcing tag names to be changed that are perfectly valid at AWS. If you have other automated processes or reports looking at specific tag names. This can cascade into a substantial task.

So this:
```hcl
tags {
  "3rd.party" = "value"
}
```
Must be changed to something like this:
```hcl
tags {
  third-party = "value"
}
```

Is there any way of escaping quotes or allowing single quotes so that tag names do not need to be changed?

**Comment by jbardin** [comment]
Hi @jheadley,

Thanks for reporting this. Do you have an example of the resource that this?
The schema for `tags` attributes is usually a simple map, so you should be able to quote the keys as you described initially. I think the issue might be that you are using the block syntax for the `tags` attribute. 

You can try using:

```
tags = {
  "3rd.party" = "value"
}
```

If that's the issue, the `0.12upgrade` tool should have already fixed up the syntax, so an example config may be useful here.

**Comment by jheadley** [comment]
Ok, here's one example.
```hcl
resource "aws_db_instance" "db-prod" {
  identifier              = "db-prod"
  allocated_storage       = 100
  storage_type            = "io1"
  storage_encrypted       = true
  engine                  = "mysql"
  engine_version          = "5.7"
  instance_class          = "db.t2.large"
  name                    = "name"
  username                = "the_user"
  password                = ""
  port                    = 3306
  publicly_accessible     = false
  availability_zone       = "${var.availability_zones["zone6"]}"
  security_group_names    = []
  vpc_security_group_ids  = ["${var.sgs["some_text"]}"]
  db_subnet_group_name    = "default-vpc"
  parameter_group_name    = "default.mysql5.7"
  multi_az                = true
  backup_retention_period = 7
  backup_window           = "${var.backup_window}"
  maintenance_window      = "${var.maintenance_window}"
  iops                    = 1000
  monitoring_interval     = 60
  skip_final_snapshot     = true
  auto_minor_version_upgrade = true
  apply_immediately       = false
  allow_major_version_upgrade = true

  tags {
    "workload-type" = "production"
    "3rd.party" = "vendorName"
  }
}
```

**Comment by jbardin** [comment]
Thanks for the config @jheadley,

Running the `0.12upgrade` command on that correctly rewrites the tags to 

```
  tags = {
    "workload-type" = "production"
    "3rd.party"     = "vendorName"
  }
```

**Comment by jheadley** [comment]
We had already done the upgrade command prior to us experiencing those errors and it made a number of changes. Regardless, I went and made the change manually to all of our tags sections and can run terraform init successfully now. Thank you @jbardin for the help.

**Comment by edgan** [comment]
I am having the same issue, and nothing seems to be resolving it. I have tried adding more spaces before equals, in the style that 0.12upgrade does, and it doesn't help.

```  tags {
    Name = "${local.component_cluster_role}-${format("%02d", count.index + 1)}.${var.env}.${var.region}.${var.cloud_provider}.${var.root_domain}"
    account = "${var.account}"
    cluster = "${var.cluster}"
    component = "${var.component}"
    env = "${var.env}"
    host_id = "${format("%02d", count.index + 1)}"
    "kubernetes.io/cluster/frodo" = "owned"
    oscodename = "${lookup(var.oscodenames, count.index)}"
    region = "${var.region}"
    role = "${var.role}"
  }
```

```Error: Invalid argument name

  on modules/kube-frodo-master/main.tf line 34, in resource "aws_instance" "instances":
  34:     "kubernetes.io/cluster/frodo" = "owned"

Argument names must not be quoted.
```

```
  tags {
    Name = "${local.component_cluster_role}-${format("%02d", count.index + 1)}.${var.env}.${var.region}.${var.cloud_provider}.${var.root_domain}"
    account = "${var.account}"
    cluster = "${var.cluster}"
    component = "${var.component}"
    env = "${var.env}"
    host_id = "${format("%02d", count.index + 1)}"
    kubernetes.io/cluster/frodo = "owned"
    oscodename = "${lookup(var.oscodenames, count.index)}"
    region = "${var.region}"
    role = "${var.role}"
  }
```

```
Error: Argument or block definition required

On modules/kube-frodo-master/main.tf line 34: An argument or block definition
is required here. To set an argument, use the equals sign "=" to introduce the
argument value.
```

**Comment by edgan** [comment]
I figured it out. The trick was to isolate the module code to a new directory. Be sure to include a provider like below. Remove the quotes attribute name, temporarily. Run terraform init to verify it is in a happy state. Then run terraform 0.12upgrade to convert it for you. Then put the attribute name back with quotes.

The problem seems to be there are three different syntax modes. The quoting is only aloud in the third mode.

1. pre 0.12
2. post 0.12 but pre conversion, a hybrid mode
3. post 0.12 and post conversion.

```
provider "aws" {
  profile = "dev"
  region = "${var.region}"
}
```
