### ISSUE TITLE
v0.12: Terraform Version Check Ignored depending on location

### ISSUE THREAD

**Issue by bernadinm** [hashicorp/terraform#21420]
When using terraform v0.12, it fails to perform the check depending if the condition lives in the main.tf or any other *.tf

### Terraform Version

```bash
$ terraform -v
Terraform v0.12.0

```

### Terraform Configuration Files

```hcl
$ cat meta.tf
terraform {
 required_version = "> 0.12.0"
}
```

```hcl
$ cat main.tf
#terraform {
#  required_version = "< 0.12.0"
#}

output "a.b.c_unsupported" {
  value = "1.2.3"
}
```

### Actual Behavior

```hcl
terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid output name

  on main.tf line 9, in output "a.b.c_unsupported":
   9: output "a.b.c_unsupported" {

A name must start with a letter and may contain only letters, digits,
underscores, and dashes.
```

### Expected Behavior

```hcl
terraform init

Error: Unsupported Terraform Core version

This configuration does not support Terraform version 0.12.0. To proceed,
either choose another supported Terraform version or update the root module's
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
```

### Steps to Reproduce

1. `terraform init`

**Comment by bernadinm** [comment]
Observed an odd behavior that if you remove the meta.tf and have a main.tf it works around the issue.

### Terraform Configuration Files

```hcl
$ rm meta.tf

$ cat main.tf
terraform {
  required_version = "< 0.12.0"
}

output "a.b.c_unsupported" {
  value = "1.2.3"
}
```

### Actual Behavior
```hcl

terraform init
Error: Unsupported Terraform Core version

This configuration does not support Terraform version 0.12.0. To proceed,
either choose another supported Terraform version or update the root module's
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
```

**Comment by bernadinm** [comment]
Unfortunately, this trick above doesn't work with nested modules.

**Comment by apparentlymart** [comment]
Hi @bernadinm!

In your first example you showed a version constraint of `> 0.12.0`. Was that intentional? Based on everything else you've shown here, it looks like you were trying to write a version constraint to _exclude_ Terraform 0.12.0 and later.

**Comment by bernadinm** [comment]
That's correct. These templates are versioned controlled and we wanted to
ensure the proper version of terraform was applied until the new templates
we're migrated to.

**Comment by apparentlymart** [comment]
Thanks for the clarification. In that case, shouldn't the version constraint in your `meta.tf` actually be `< 0.12.0`, to match with what you added to `main.tf` in the later example?

**Comment by bernadinm** [comment]
Thanks for the catch. You are correct. However regardless of the condition, it still ignores the required_version check. Here is a single command to help repo:

```bash
mkdir -p /tmp/repo/module

echo > /tmp/repo/module/main.tf <<EOF
terraform {
  required_version = "< 0.12.0"
}

output "a.b.c_unsupported" {
  value = "1.2.3"
}
EOF

echo > /tmp/repo/main.tf <<EOF
module "test" {
source = "./module"
}
EOF

cd /tmp/repo/
terraform init
```

**Comment by apparentlymart** [comment]
Thanks!

The Terraform version constraint handling tries its best to ignore errors during loading so that it can detect this situation, but it seems like it's not trying quite hard enough to deal with it here. I suspect it's handling the check on a per-file basis rather than on a whole-module basis, and so it only works if the error is in the same file as the version constraint; instead, it should visit all of the files _first_ to sniff for version constraints, and only then move on to actually trying to load them fully.

**Comment by bernadinm** [comment]
It looks like it is even ignoring the `required_version` even if it's within the same module. You can see this here as well with this example:

```bash
mkdir -p /tmp/repo/module

cat > /tmp/repo/module/main.tf <<EOF
terraform {
  required_version = "< 0.12.0"
}

output "a.b.c_unsupported" {
  value = "1.2.3"
}
EOF

cat > /tmp/repo/main.tf <<EOF
terraform {
  required_version = "< 0.12.0"
}

module "test" {
source = "./module"
}
EOF

cd /tmp/repo/
terraform init
```

### Actual Output

```hcl
$ terraform init
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid output name

  on module/main.tf line 5, in output "a.b.c_unsupported":
   5: output "a.b.c_unsupported" {

A name must start with a letter and may contain only letters, digits,
underscores, and dashes.
```
```bash
$ terraform -v
Terraform v0.12.0

```

**Comment by sudoforge** [comment]
To add to this, the pessimistic constraint operator behavior seems to have changed from:

```
"~> 0.11" == ">= 0.11, < 0.12"

to

"~> 0.11" == ">= 0.11, <= 0.12"
```

☝️ this is problematic and an undocumented (as far as i can tell) breaking change from pre-0.12.

---

## 0.12 Implicit (with pessimistic operator)

```
→ tf version
Terraform v0.12.0


→ cat main.tf
terraform {
  required_version = "~> 0.11"
}

output "foo" {
  value = "we shouldn't see this when using terraform 0.12.0"
}


→ tf init

Initializing the backend...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

/tmp/main
→ tf apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

foo = we shouldn't see this when using terraform 0.12.0
```

## 0.12 Explicit (without pessimistic operator)

```
→ cat main.tf
terraform {
  required_version = ">= 0.11, < 0.12"
}

output "foo" {
  value = "we shouldn't see this when using terraform 0.12.0"
}


→ tf init

Error: Unsupported Terraform Core version

This configuration does not support Terraform version 0.12.0. To proceed,
either choose another supported Terraform version or update the root module's
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
```

**Comment by apparentlymart** [comment]
Hi @sudoforge!

Thanks for reporting that, but it seems like a separate problem, so could you please open a new issue for it? Terraform uses [an upstream library](https://github.com/hashicorp/go-version) to handle those, so it's possible that it had an undocumented behavior change that we inherited, but the solution to that will be independent of fixing the handling of the `required_version` attribute.

**Comment by sudoforge** [comment]
@apparentlymart You're absolutely right. My apologies, I had several different tabs open with various issues and must have gotten my wires crossed.

**Comment by Misio942** [comment]
good afternoon, I solve the problem by adding to require_version = "<= 0.12.19"

**Comment by scardena** [comment]
In my case it worked by adding
`required_version = ">= 0.12.14"` (I had installed Terraform v0.12.24)

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity, and it looks like the questions have been answered. The underlying code paths have changed for terraform v0.13, so if you still see an issue when using the latest version of terraform, please open a new issue.

Thanks!
