### ISSUE TITLE
Init migration on backend gcs from 0.11.14 to 0.12.0 fails

### ISSUE THREAD

**Issue by invidian** [hashicorp/terraform#21427]
### Terraform Version

```
Terraform v0.12.0
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "= 0.12.0"

  backend "gcs" {
    #project  = "foo"
    bucket  = "foo"
    prefix  = "foo"
  }
}
```

### Crash Output

```
$ terraform init

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.



Error: "project": [REMOVED] Please remove this attribute. It is not used since the backend no longer creates the bucket if it does not yet exist
```
### Expected Behavior

`terraform init` should give user clear information about what needs to be done to proceed with migration in this case. It should suggest removing `project` parameter from `gsc` backend and running with `-reconfigure` flag.

### Actual Behavior

Terraform init fails and instruction how to proceed is unclear.

### Steps to Reproduce

1. Create `main.tf` with following content:
```hcl
terraform {
  required_version = "= 0.11.14"

  backend "gcs" {
    project = "foo"
    bucket = "foo"
    prefix = "foo"
  }
}
```

2. Initialize with Terraform 0.11.14:
```sh
terraform init
```

3. Upgrade to `0.12.0`:
```sh
terraform 0.12upgrade
```

4. Remove created `versions.tf` and modify `main.tf` to have `required_version = "= 0.12.0"` line
```sh
rm versions.tf
sed -i 's/0.11.14/0.12.0/g' main.tf
```

5. Run `terraform init` with Terraform 0.12.0
```sh
terraform init
```

### Additional Context

I've tried migrating my existing project from 0.11.4 to 0.12.0. When I run `terraform init` for the first time, it complained, that `project` parameter has been removed, however, it does not tell which `project` parameter exactly has been removed.

Anyway, from source, I found that this is a change in `gsc` backend, so I commented out the parameter, however Terraform was still complaining.

### Workaround

It seems that workaround for this issue is to run:
```
terraform init -reconfigure
```
which Terraform suggested me when I removed both `region` and `project` parameters from Terraform source.

EDIT: I moved the workaround to separated section, so it's easier to find for people affected by this.

**Comment by remm** [comment]
any updates here? l

**Comment by moonkid196** [comment]
I did what was suggested here to work around the problem (running with -reconfigure) and I guess it completely overwrote my state, as "terraform plan" now shows that it's going to try to create all of my resources again. I guess I'll have to go re-import them back into the new state. This is very much still broken, since the normal commands do not recognize when you update your config, resulting in dramatic actions, like -reconfigure, which is clearly also undesirable. Luckily I only had 22 resources

**Comment by larsha** [comment]
Any updates here? As I understand, `terraform init -reconfigure` will rewrite state completely. But do I always need to re-import all my resources again as @moonkid196 saying?

**Comment by Markbnj** [comment]
FYI we were able to work past this by doing the following:
- Edit our main .tf files to remove the `project` attribute from the `backend` and `terraform_remote_state` declarations
- Edit the terraform.tfstate and default.tfstate files in our remote state bucket to remove the `project` attribute from the `terraform_remote_state` resource declaration.
After this we were able to run `terraform init --upgrade` and work through a bunch of other syntax changes from 0.11.x to 0.12.8 and ultimately get to a clean plan without reimporting anything.

**Comment by larsha** [comment]
I managed to get this working by just removing the `.terraform` folder.

**Comment by hoenirvili** [comment]
I'm experiencing the same behavior, I'm using ```Terraform v0.12.21```. If I run with v0.11 it works. I tried any fix suggested above without any luck.

**Comment by mildwonkey** [comment]
I am going to close this as a stale issue. If you are still experiencing a problem with terraform v0.13, please open a new one!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
