### ISSUE TITLE
Coalesce and coalescelist behaviour

### ISSUE THREAD

**Issue by alex-goncharov** [hashicorp/terraform#21431]
### Current Terraform Version
```
$ terraform -v
Terraform v0.12.0
```

### Use-cases
This relates to https://github.com/hashicorp/terraform/issues/20982

I get the idea and it makes sense, however there many use cases in terraform-aws-modules/terraform-aws... modules that look like this:

```hcl
locals {
 default_list = []
 default_string = ""

 str = coalesce(..., default_string)
 lst = coalescelist(..., default_list)
```
}

### Attempted Solutions

The workaround is to check all params for emptiness or use some sort of a marker as a last parameter, which quite kills the purpose of the function. 

### Proposal

Function should use last parameter as a default value. Something like lookup() does.

### References
https://github.com/hashicorp/terraform/issues/20982

**Comment by apparentlymart** [comment]
Thanks for reporting this, @alex-goncharov!

I also found this one during testing -- probably of the very same modules you were testing -- and opened #21370 about it. Using the last parameter as a default is a possibility we're considering; you can see over in the other issue that we have some concerns about it being a little too implicit, but so far there's no other candidate solution, so we'll take that option if we can't find something else that is more explicit.

Thanks again for reporting this! I'm going to close this now just to consolidate over in #21370.
