### ISSUE TITLE
terraform show planfile without -json is incomplete in v0.12.0

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#21446]
The plan rendering from `terraform plan` was updated to the new structural diff format in v0.12.0, but the corresponding codepath in `terraform show` (not in JSON mode) was not updated, so it's using a much-reduced version of the old codepath that only shows the top-level actions, and not individual attribute diffs.

To reproduce:
* Run `terraform plan -out=tfplan` to produce a saved plan file
* Run `terraform show tfplan`

If the plan contained any create or update actions, notice that they only have the headline of the action and not any details about the individual attributes.

**Comment by dayglojesus** [comment]
The addition of the `-json` flag is invaluable, but being able to produce human-readable output from a plan file is critical for the toolchain we use. There appear to be a couple of similar open issues surrounding this regression from `0.11.x`. Here is what I have found:
- #21966
- #21949

**Comment by dcalhoun** [comment]
I agree with @dayglojesus. With my team's process, the inability to see human-readable details of what is changing means we are "flying blind" when reviewing a plan and applying it. Unfortunately `0.12.x` is unusable for us without this issue being addressed first.

@apparentlymart are there any plans to prioritize this? If not, is there a specific location in the code you could point to where one might contribute a fix? Thanks.

**Comment by mrparkers** [comment]
Just want to chime in here and say that this is the only issue preventing the company I work for from switching to Terraform 0.12.  Echoing what @dcalhoun mentioned, I'd love to help contribute a fix if someone could point me in the right direction.

**Comment by apparentlymart** [comment]
This was fixed in #23292. The fix should be included in the next minor release.
