### ISSUE TITLE
Count is not working in module 

### ISSUE THREAD

**Issue by armugharaj** [hashicorp/terraform#21466]
### Terraform Version

```
Terraform v0.12.0
+ provider.openstack v1.19.0
```

### Terraform Configuration Files

```hcl
provider "openstack" {
  user_name   = "${var.openstack_user_name}"
  tenant_name = "${var.openstack_tenant_name}"
  password    = "${var.openstack_password}"
  auth_url    = "${var.openstack_auth_url}"
  insecure    = "${var.openstack_insecure}"
}

resource "openstack_blockstorage_volume_v2" "system" {
  count = "${var.vm_count}"
  region = "RegionOne"
  name  = "${var.instance_name}"
  size = "${var.os_size}"
  image_id = "${var.os_image}"
}

resource "openstack_blockstorage_volume_v2" "volumes" {
  count = "${var.vm_count}"
  name  = "${var.instance_name}"
  size = "${var.add_vol_size}"
}

resource "openstack_compute_instance_v2" "instance_created" {
  count = "${var.vm_count}"
  name = "${var.instance_name}"
  availability_zone = "${element(split(",",var.openstack_availability_zones), vm_count.index)}"
  flavor_name = "${var.openstack_flavor}"
  key_pair = "${var.openstack_keypair}"
  security_groups = ["${var.security_group_name}"]

  block_device {
    uuid                  = "${openstack_blockstorage_volume_v2.system.*.id[vm_count.index]}"
    source_type           = "volume"
    destination_type      = "volume"
    boot_index            = 0
    delete_on_termination = false
  }
```

**Comment by apparentlymart** [comment]
Hi @armugharaj!

It looks like the issue template for this is only partially filled out: we have your Terraform version and your configuration files, but no information about what you tried, what you were expecting, and what actually happened. Please edit the original issue comment to add in that additional information, and then we'll try to reproduce your steps and see what's going on.

Thanks!

**Comment by armugharaj** [comment]
Hi @apparentlymart 
Thanks for the reply 
I wanted to use the module with openstack_blockstorage_volume_v2 by Adding Three volume (on demand basis :-
1. root /dev/vda
2. data /dev/vdb
3. data /dev/vdc

In my dev environment,  I needed only /dev/vda and /dev/vdb only. In this case , Currently i am deleting the module openstack_blockstorage_volume_v2  and than running terrafrom apply which is manual and repeat task.

Please suggest which configuration changes and up gradation is required ? 
so that i don't need to delete in module file

**Comment by armugharaj** [comment]
Hello Team,
Any update ? 
in module if one volume to be attached but in module Two volume resource is defined , how to skip it ?
Any if condition can help on this situation ?

**Comment by armugharaj** [comment]
Hello Team,

Any update ?

**Comment by RyanJarv** [comment]
I don't believe terraform supports count on modules, here's an open ticket on it.

https://github.com/hashicorp/terraform/issues/953

**Comment by apparentlymart** [comment]
As @RyanJarv noted, `count` is a resource-specific idea and isn't available for whole modules.

If you need to have different infrastructure in different environments then the way to represent that in Terraform is to have a separate configuration for each environment. You can still put the common elements in modules to avoid duplicating the parts that are the same, but the easiest way to represent differences between environments is to use a separate root module for each that directly describes what should exist in that environment.
