### ISSUE TITLE
Override not working with ignore_changes

### ISSUE THREAD

**Issue by randomswdev** [hashicorp/terraform#21474]
### Terraform Version
```
Terraform v0.12.0
```

### Terraform Configuration Files
A file main.tf containing:
```hcl
resource "gitlab_project" "project" {
    name = "Test name"
    description = "Test description"
}
```
An override file main_override.tf containing:
```hcl
resource "gitlab_project" "project" {
    description = "Test description extended"
    lifecycle {
        ignore_changes = all
    }
}
```

### Expected Behavior

-  I execute `terraform apply` just having in the current folder the main.tf file
-  I add the main_override.tf file in the same folder and execute again `terraform apply`

At the time of the second apply, Terraform should report that no action is needed, because I'm changing the description but I'm also adding an "ignore all" lifecycle directive.

### Actual Behavior
Terraform changes the project description, ignoring the lifecycle definition in the override file.

**Comment by ourway** [comment]
Any updates on this bug?

**Comment by kylelee24** [comment]
I have tested today and `ignore_changes = all` doesn't seem to be working. I'm on version `0.13.5`. 

```
  lifecycle {
    ignore_changes = all
  }
```

**Comment by kmoe** [comment]
Confirmed that this is a bug specifically with `ignore_changes = all`: any other `ignore_changes` value will override successfully.
