### ISSUE TITLE
Unable to provide list values on command line

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform#21492]
### Terraform Version

```
v0.12.0
```

### Terraform Configuration Files

```hcl
resource "aws_route53_zone" "z" {
  name     = var.dns_subdomain

  dynamic "vpc" {
    for_each = var.vpc_associations
    content {
      vpc_id = vpc.value
    }
  }

  comment = var.comment
}
```

### Expected Behavior
```
# aws_route53_zone.z will be created
  + resource "aws_route53_zone" "z" {
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "junk.com."
      + name_servers  = (known after apply)
      + vpc_id        = (known after apply)
      + vpc_region    = (known after apply)
      + zone_id       = (known after apply)

      + vpc {
          + vpc_id     = "vpc-11223344"
          + vpc_region = (known after apply)
        }
      + vpc {
          + vpc_id     = "vpc-22334455"
          + vpc_region = (known after apply)
        }
    }
```

### Actual Behavior
```
> $ terraform plan -var='vpc_associations=["vpc-11223344","vpc-22334455"]' -var dns_subdomain=junk.com.                                                                                                   
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

Error: Invalid dynamic for_each value

  on main.tf line 11, in resource "aws_route53_zone" "z":
  11:     for_each = var.vpc_associations
    |----------------
    | var.vpc_associations is "[\"vpc-11223344\",\"vpc-22334455\"]"

Cannot use a string value in for_each. An iterable collection is required.
```
### Steps to Reproduce
seen above

### Additional Context
I'm supplying the variable value on the command line per the example at https://www.terraform.io/docs/configuration/variables.html#variables-on-the-command-line

The appropriate behavior happens when I code the value into the terraform config rather than providing on the command line.

**Comment by apparentlymart** [comment]
Hi @grimm26! Sorry for this confusing behavior.

Terraform decides how to parse the strings provided on the command line (and in environment variables) based on the declared type of the variable. In order to pass a list of strings, you must set `type = list(string)` in the `variable "vpc_associations"` block so Terraform knows that it's not just a plain string.

There's more information on this special behavior later in the documentation, under [Complex-typed Values](https://www.terraform.io/docs/configuration/variables.html#complex-typed-values).

**Comment by grimm26** [comment]
I thought that setting the default value for the variable to [] in this case implied that like in 0.11
