### ISSUE TITLE
Backend issue when passing config through cli, tf v0.12

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform#21504]
### Terraform Version
0.12.0

### Terraform Configuration Files
```
terraform {
  required_version = "~> 0.12.0"

  backend "remote" { }
}
```

backend-test.file
```
workspaces = [{ name = "ceng-test" }]
hostname     = "app.terraform.io"
organization = "org_name"
```

### Crash Output

When I run `terraform init -backend-config=backend-test.file` I get the following error;
```
on main.tf line 4, in terraform:
   4:   backend "remote" {

Either workspace "name" or "prefix" is required.
```
### Expected Behavior
I would expect to work and initial just like in the previous version of terraform.

### Actual Behavior
It doesn't initial as it fails.

May I find out how to pass the backend-config file through the CLI and what it should look like?

**Comment by mildwonkey** [comment]
Hi @marcincuber !
Sorry for this confusing behavior. I believe the problem is in your `workspaces` syntax. According to the latest [remote backend documentation](https://www.terraform.io/docs/backends/types/remote.html#example-configuration) I believe it should look like this: 

```
workspaces { name = "ceng-test" }`
```

**Comment by marcincuber** [comment]
@mildwonkey This works as expected. Thanks for the solution. I created a PR just to give an extra example within the docs. 

The syntax have changed slightly with 0.12.0 release and it no longer follows .tfvars format.
