### ISSUE TITLE
Issues for aws_lb_listener_rule to control and iterate multiple conditions

### ISSUE THREAD

**Issue by damaya** [hashicorp/terraform#21500]
Hi there, 

when using the aws_lb_listener_rule resource, we should be able to control when to add multiple conditions and use some kind of logic validation for adding multiple or single conditions.

**Comment by mauricios** [comment]
I think the Terraform way to deal with this is to create a new resource `aws_lb_listener_rule_condition` to attach conditions to rules.

**Comment by mauricios** [comment]
@damaya I this this issue should be moved to th AWS provider https://github.com/terraform-providers/terraform-provider-aws
