### ISSUE TITLE
Better error messages from validation

### ISSUE THREAD

**Issue by hden** [hashicorp/terraform#21501]
### Current Terraform Version
```
v0.12.0
```

### Use-cases
Currently running `terraform validate` will print error such as

Plain text
```
Error: Missing required argument

The argument "region" is required, but was not set.
```

JSON
```json
{
  "valid": false,
  "error_count": 1,
  "warning_count": 0,
  "diagnostics": [
    {
      "severity": "error",
      "summary": "Missing required argument",
      "detail": "The argument \"region\" is required, but was not set."
    }
  ]
}
```

But it currently does not tell us where is the error and how to fix it.

### Proposal
It would be much useful if we could actually help the user to fix the problem.

JSON
```json
{
  "valid": false,
  "error_count": 1,
  "warning_count": 0,
  "diagnostics": [
    {
      "severity": "error",
      "summary": "Missing required argument",
      "module": "foobar",
      "path": "/file/path.tf",
      "line": 19,
      "column": 45,
      "message": "The argument \"region\" is required, but was not set."
    }
  ]
}
```

### Reference
https://elm-lang.org/blog/compiler-errors-for-humans

**Comment by jackphilippi** [comment]
+1. Currently encountering this problem with zero idea of its source

**Comment by jackphilippi** [comment]
> +1. Currently encountering this problem with zero idea of its source

Setting `AWS_DEFAULT_REGION` in environment variables solved my issue. https://github.com/hashicorp/terraform/issues/21408
