### ISSUE TITLE
Incorrect documentation about types in variable blocks

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#21521]
Terraform 0.11.13

In the documentation on https://www.terraform.io/docs/configuration/variables.html it is stated

```
The type argument in a variable block allows you to restrict the type of value that will be accepted as the value for a variable. If no type constraint is set then a value of any type is accepted.

While type constraints are optional, we recommend specifying them; they serve as easy reminders for users of the module, and allow Terraform to return a helpful error message if the wrong type is used.

Type constraints are created from a mixture of type keywords and type constructors. The supported type keywords are:

string
number
bool
```

This is not true, because when creating a variable like this, terraform errors saying bool is not a valid type:

```
variable "foo" {
    type = "bool"
    default = "false"
}
```

**Comment by apparentlymart** [comment]
Hi @gtmtech!

The documentation you are referring to here is for Terraform 0.12. Since you are using Terraform 0.11, you should refer instead to [the equivalent docs for Terraform 0.11](https://www.terraform.io/docs/configuration-0-11/variables.html#type).

**Comment by gtmtech** [comment]
haha wonderful, thanks @apparentlymart
