### ISSUE TITLE
0.12 for_each loop index

### ISSUE THREAD

**Issue by den-is** [hashicorp/terraform#21533]
I'm running tf 0.12.0 with vsphere provider

I'm trying to create VM with arbitrary number of disks using dynamic_blocks and for_each.

I need to pass to VM disks with distinct file names. so i'm autogenerating part of the disk-name, but can't distinguish disk if for example i've asked to create 2+ additional disks.
if there is way to know element index in the current loop iteration?

```hcl
  dynamic "disk" {
    for_each = var.secondary_disks
    iterator = "secondary_disk"
    content {
      label = format(
        "%v-%02d.%v_0_secondary_%d",
        var.hostname_prefix,
        count.index + 1,
        var.domain,
        I.NEED.ITER.INDEX.HERE.OR.SOMETHING.SIMILAR
      )
      size = secondary_disk.value
    }
  }
```

**Comment by cmanzi-cs** [comment]
I ran into a similar situation recently, afaik there isn't a way to do this with `dynamic`s right now. I 'worked around' this by simply adding an `index` to each element in the list I was iterating over (i.e. `secondary_disk.index`). Not great, but it works...

**Comment by den-is** [comment]
@cmanzi-cs 
yeah, I'm thinking about this solution as last resort option, coz it is very error-prone.
I've tried to do something with `for` to mutate original list/map to automatically include indexes, but without luck. Neither was able to imagine anything with `zipmap` function.

Frustrating

**Comment by apparentlymart** [comment]
Hi @den-is,

If `var.secondary_disks` is a list value then `secondary_disk.key` would be an index already, so you could write it like this:

```hcl
  dynamic "disk" {
    for_each = var.secondary_disks
    iterator = "secondary_disk"
    content {
      label = format(
        "%v-%02d.%v_0_secondary_%d",
        var.hostname_prefix,
        count.index + 1,
        var.domain,
        secondary_disk.key,
      )
      size = secondary_disk.value
    }
  }
```

If the `for_each` expression produces a map or set then an iteration index isn't available, to make it explicit that those collection types aren't in a defined order. However, in the case of a map you can use the `key` attribute on the iterator to get the element key string, which could serve a similar purpose.

If you are iterating over a set then the elements of the set have no identifier other than themselves, so you'd need to use a `for` expression to explicitly define how to derive a useful identifier for each element.

**Comment by den-is** [comment]
@apparentlymart 

WOW !!!!
It worked for me. Just for future readers don't forget to set `unit_number` too.
that was super helpful ! Standing ovations! :D
I think your comment is very missing part of documentation.
I vote for adding it in full to the docs, but maybe with additional examples.

`map` - fine, we know what it is. But what is `set` in terraform ?
Closing this issue.

**Comment by apparentlymart** [comment]
The various complex type kinds in Terraform, including set types. are described in the section [Complex Types](https://www.terraform.io/docs/configuration/types.html#complex-types). This is using "set" in [the mathematical sense of the word](https://en.wikipedia.org/wiki/Set_(mathematics)).
