### ISSUE TITLE
Terraform Azure backend container not getting created

### ISSUE THREAD

**Issue by mamoorkhan** [hashicorp/terraform#21531]
### Terraform Version

```
Terraform v0.12.0
+ provider.azurerm v1.28.0
+ provider.random v2.1.2
```

### Terraform Configuration Files

```
terraform {
  backend "azurerm" {
    storage_account_name = "devopsterraformstorage"
    container_name       = "[container_name]"
    key                  = "[tfstate_key]"
    resource_group_name  = "[resource_group]"
    subscription_id      = "[subscription_id]"
    client_id            = "[client_id]"
    client_secret        = "[client_secret]"
    tenant_id            = "[tenant_id]"
  }
}

provider "azurerm" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "=1.28.0"

  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}
```

### Debug Output

[Debug Output](https://gist.github.com/mamoorkhan/b0f37e1fb5de140455df5c332ab70228)

### Expected Behavior

Should create a new blob and store the state in there.

### Actual Behavior

It gave an error with the debug output attached

### Steps to Reproduce

1. `terraform init -input=false`
2. `terraform plan -input=false`
3. `terraform apply -input=false -auto-approve`

### Additional Context

I am running terraform with the [script attached here](https://gist.github.com/mamoorkhan/1a5a02fc34f3f3c9df064ea5d08cea0f) in Azure DevOps Release pipeline task Azure PowerShell Task (Preview v4)

The script and terraform execution works, when the container is already created for it's backend

**Comment by jbardin** [comment]
Hi @mamoorkhan,

Sorry about the confusion here, but this is the expected behavior. Backends no not create their own resources, because terraform would not be able to fully manage them.
