### ISSUE TITLE
Terraform doesn't output colour with Ansible in local-exec

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform#21556]
### Current Terraform Version

```
v0.11.13
```

### Use-cases

Currently its very hard to read ansible output when provisioning within terraform because all the colours are removed.  This also makes it difficult to detect warnings and errors at times.

### Proposal

It would be great to enable ansible output colour in the shell by default when being used in a local or remote exec.

**Comment by queglay** [comment]
Is it possible to achieve any workaround for this ability?

**Comment by nickkadams** [comment]
My workaround
```  provisioner "local-exec" {
    command = "ANSIBLE_FORCE_COLOR=1 ansible-playbook --ssh-extra-args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -u ${var.ssh_user} --private-key ${var.shared_key_path} -i ansible/inventory ansible/playbook.yml"
  }```

**Comment by queglay** [comment]
Fantastic!  Thanks @nickkadams!
