### ISSUE TITLE
feature request: use provisioners on their own

### ISSUE THREAD

**Issue by rimusz** [hashicorp/terraform#2156]
Would be nice to have a feature to run provisioners like file, local-exec, remote-exec on their own
after deployed infrastructure.

What I mean terraform does only sets up infrastructure, but afterwards we need to run some scripts on remote machines e.g. updating things. So for that bash scripts need to be written which gets IP addresses of machines, ssh to machines and etc.

It would be cool to have separate .tf files to run provisioners on already deployed infrastructure.

**Comment by radeksimko** [comment]
Hi, there's an existing issue which tracks this:
https://github.com/hashicorp/terraform/issues/1181

Feel free to reopen if you believe it's not quite what you mean.
