### ISSUE TITLE
0.12 bug cognito user pool resource

### ISSUE THREAD

**Issue by omarelsaid** [hashicorp/terraform#21561]
I have an existing resource of type aws_cognito_user_pool in my AWS account deployed via Terraform.

I recently upgraded to Terraform 0.12 together with aws.provider version upgraded to 2.13.

After that I wanted to make some changes to this resource, but everytime I do I get the following error:

Error: Error updating Cognito User pool: InvalidParameterException: Please use TemporaryPasswordValidityDays instead of UnusedAccountValidityDays
        status code: 400, request id: 51e07ff5-6b87-44f3-a173-540b95732ceb

Please let me know if you need any more information as this is a complete blocker for me, as I can't downgrade terraform versions with ease, these resources already exist in AWS and I already tried (and failed) to import existing AWS resources into terraform state.

Also just to note there doesn't seem to be an attribute on the aws_cognito_user_pool that corresponds to the new TemporaryPasswordValidityDays parameter that is expected, I can only find unused_account_validity_days under the admin_create_user_config config block. I also haven't specified this config param explicitly, I've left it to specify the default

Thanks! :)

**Comment by omarelsaid** [comment]
Also just to note there doesn't seem to be an attribute on the aws_cognito_user_pool that corresponds to the new TemporaryPasswordValidityDays parameter that is expected, I can only find unused_account_validity_days under the admin_create_user_config config block

**Comment by mildwonkey** [comment]
Hi @omarelsaid , 
We do usually need more information, but in this case it looks like there is a relevant issue already open in [terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws): [#8827](https://github.com/terraform-providers/terraform-provider-aws/issues/8827 )

I will close this issue in favor of that one, and I recommend you add a 👍 to that issue.
