### ISSUE TITLE
backend "gcs" doesn't treat credentials attribte

### ISSUE THREAD

**Issue by minherz** [hashicorp/terraform#21562]
### Terraform Version

```
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 0.12.0. You can update by downloading from www.terraform.io/downloads.html
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.11"
  backend "gcs" {
      credentials = "/etc/credentials/acme-terra-form-e4c9eba7464b.json"
      bucket  = "acme-terraform-states"
      prefix  = "getting-started/state"
    }
}

provider "google" {
  credentials = "${file("/etc/credentials/acme-terra-form-e4c9eba7464b.json")}"
  project = "acme-terra-form"
  region = "us-central1"
  version = "~> 2.7"
}
```

### Debug Output

[Output in gist](https://gist.github.com/minherz/ed59b2bac559ae8b66e1ccefd087f524)

### Crash Output

None

### Expected Behavior

Terraform should either succeed to initialize or fail due an insufficient permissions of the _service account_ `acme-terra-form` and not the error that is reported.

### Actual Behavior

Terraform tries to initialize GCS backend using default account of the logged-in user and not the credentials that were provided using `credentials` attribute of the backend.

### Steps to Reproduce

1. `terraform init`

### Additional Context

I run terraform from a work machine with `gcloud CLI` installed. The user account has access to Google Cloud and is able to access GCS buckets. For example, the following command succeeds:
```
$> gsutil ls gs://acme-terraform-states/
```

I have changed the real account prefix with "`acme`".

If I setup the path that is defined in the `credentials` attribute as `GOOGLE_APPLICATION_CREDENTIALS` environment variable, I get the expected behaviour.

**Comment by awinograd** [comment]
```
Terraform v0.12.12
+ provider.google v2.18.1
```

I've just started checking out terraform today. I'm hitting this issue and cannot move forward with my project because I get the following error when trying to authenticate the backend with the `credentials` property

```
Error: storage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/a
ccounts/docs/application-default-credentials for more information.
```

I'd rather not set `DEFAULT_APPLICATION_CREDENTIALS` to workaround this due to other complications that arise

**Comment by mboogerd** [comment]
I'm experiencing the same problem. `credentials` attribute value seems ignored, gcs module just attempts to get authorised using the default service account.

```
Terraform version: 0.12.25
provider.google v3.22
```

**Comment by timeyr** [comment]
This is still an issue in 0.12.29.

A workaround is to set the `GOOGLE_APPLICATION_CREDENTIALS` env var pointing to the credential file.

**Comment by upodroid** [comment]
I tried to repro this bug and it doesn't exist as of 0.12.29

```
provider "google" {
 project = "REDACTED"
 credentials = "/Users/REDACTED/Downloads/key.json"
}

terraform {
  backend "gcs" {
    bucket = "REDACTED"
    prefix = "repro-21562"
    credentials = "/Users/REDACTED/Downloads/key.json"
  }
}

data "google_compute_regions" "available" {
}
```

I enabled Audit Logging on GCS to see which identity is reading default.tfstate and creating/deleting default.tflock. It is the service account defined in the key.
