### ISSUE TITLE
Not able to connect to private ec2 instance from jump server (bastion) using terraform

### ISSUE THREAD

**Issue by ajoysinhactc** [hashicorp/terraform#21585]
Hi,

**My Goal**

> I will execute a shell script on private ec2 instance  ( Created using Terraform ) through Terraform via Bastion server

**InfraStructure**

> one private ec2 inatance
> one Bastion server

I have used following null_resource to connect bastion server and from there ssh into private instance by setting up agent=true

```
### Update the instnaces by installing newrelic agent using remote-exec

resource "null_resource" "copy_file_newrelic_v_10" {
 
  count = "${length(aws_instance.bastion.*.ami)}"

  triggers = {
    cluster_instance_ids = "${join(",", aws_instance.bastion.*.id)}"
  }

  connection {
    host = "${element(aws_instance.bastion.*.public_ip, count.index)}"
    user = "ec2-user"
    private_key = "${file("C:/keys/nvirginia-key-pair-ajoy.pem")}"
	agent = "true"
  }
  
  provisioner "remote-exec" {
    inline = [
      "ssh ec2-user@172.31.2.250" 
    ]
  }
}

```

I am able to create connection successfully to Bastion server. but connection from bastion server to private instance ### _ssh ec2-user@172.31.2.250 failed

**problem**

> Not able to setup ssh agent using terraform . Permission denied (publickey).

**Error**
>null_resource.copy_file_newrelic_v_10: Provisioning with 'remote-exec'...
null_resource.copy_file_newrelic_v_10 (remote-exec): Connecting to remote host via SSH...
null_resource.copy_file_newrelic_v_10 (remote-exec):   Host: 3.88.22.187
null_resource.copy_file_newrelic_v_10 (remote-exec):   User: ec2-user
null_resource.copy_file_newrelic_v_10 (remote-exec):   Password: false
null_resource.copy_file_newrelic_v_10 (remote-exec):   Private key: true
null_resource.copy_file_newrelic_v_10 (remote-exec):   SSH Agent: true
null_resource.copy_file_newrelic_v_10 (remote-exec):   Checking Host Key: false
null_resource.copy_file_newrelic_v_10 (remote-exec): Connected!
data.aws_ecs_task_definition.multichannelwebapp: Refreshing state...
data.aws_ecs_task_definition.adminmanagerapp: Refreshing state...
data.aws_ecs_task_definition.usermanagerapp: Refreshing state...
null_resource.copy_file_newrelic_v_10 (remote-exec): Permission denied (publickey).
null_resource.copy_file_newrelic_v_10: Still creating... (10s elapsed)
>

Note : I am working on windows machine, and using putty i am able to login into bastion server and from there able to ssh into private server by setting up "Allow Agent Forwarding". Keys used are same in both server.

### If it is working through putty, why it is not working using Terraform. am i doing any mistake

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
