### ISSUE TITLE
`terraform init` detects that the configuration specified for the backend has changed, even though it hasn't.

### ISSUE THREAD

**Issue by uipo78** [hashicorp/terraform#21580]
### Terraform Version

```
terraform v0.12.0
```

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.29.0"
}

provider "azuread" {
  version = "~> 0.3"
}

provider helm {
  version = "~> 0.9"
}

provider kubernetes {
  version = "~> 1.7"
}

provider null {
  version = "~> 2.1"
}

provider random {
  version = "~> 2.1"
}

provider tls {
  version = "~> 2.0"
}


terraform {
  backend "azurerm" {
    storage_account_name = "<fixed_storage_account_name>"
    container_name       = "<fixed_container_name>"
    key                  = "<fixed_key>.tfstate"
  }
}
```

### Debug Output

https://gist.github.com/uipo78/31fec41f649a6bff60eb1b8d06808e9f

### Expected Behavior

Having called `terraform init` twice, it should detect no changes to the configuration specified for the backend in the second call.

### Actual Behavior

`terraform init` detects changes to the configuration specified for the backend in the second call, despite having changed nothing.

### Steps to Reproduce

Run `terraform init` twice in a row.

### Additional Context

We run most `terraform` commands in a Makefile at the moment (with the `ARM_ACCESS_KEY` ran right before `terraform [...]`).

**Comment by jbardin** [comment]
Thanks for filing the issue @uipo78!

This is fixed by #21439, and will be in the next release.
