### ISSUE TITLE
Terraform 0.12 Invalid Reference on init

### ISSUE THREAD

**Issue by tebriel** [hashicorp/terraform#21593]
### Terraform Version

```
Terraform v0.12.1
+ provider.aws v2.13.0
+ provider.datadog v1.9.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
large project, unsure of any specific configuration related to this bug
```

### Crash Output

`TF_LOG=TRACE` output

https://gist.github.com/tebriel/cbf05903d872fcdeabd035e4d3c46942

### Expected Behavior

It should've refreshed the state and prepared me for a 0.12.1 upgrade

### Actual Behavior

It said: 
> Error refreshing state: Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.

### Steps to Reproduce

*On Terraform 0.11.14*
1.  `terraform init`
2.  `terraform plan`
3.  `terraform apply`
4.  `terraform 0.12checklist` _no recommended changes_

*On Terraform 0.12.1*
1.  `terraform init`
> Error refreshing state: Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.

### Additional Context
I have a `-backend-config` passed to `terraform init` which specifies `access_key` and `secret_key` in a `awskeys.tfvars` file. For the aws provider:

```hcl
provider "aws" {
  region     = "us-east-1"
  version    = ">= 2.11"
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
}
```

For the backend
```hcl
terraform {
  backend "s3" {
    bucket = "tf-remote-state.pindrop.io"
    key    = "chrisbot/tf-state"
    region = "us-east-1"
  }
}
```

**Comment by apparentlymart** [comment]
Hi @tebriel! Sorry this didn't work out.

It sounds like there is something in your latest state snapshot that the state version upgrade process didn't catch and fix. To get to the bottom of that, I think we'll need some information from your state in this case.

Unfortunately since it is `terraform init` that is failing here, accessing the state via Terraform itself is unlikely to work. If possible, could you download the latest state snapshot for this workspace directly from the S3 bucket and look inside it?

What I'm particularly interested to see to start is the values of any `depends_on` properties in there. I'm expecting to see that at least one of them will contain an unusual address form that the upgrade process isn't correctly handling. If you could gather up all of the `depends_on` lists you see in the state and share them here, we can see if anything listed there is unexpected and then, if so, see what the next step might be.

It's not necessary to share the entire state file. The `depends_on` is the most likely place for us to find resource addresses as indicated in the error message, though if we don't find something there I may have some other ideas for things to look at in the state file.

Thanks, and sorry again for this unexpected error.

**Comment by tebriel** [comment]
@apparentlymart Thanks for your help, here's all the depends_on in the tf state file. https://gist.github.com/tebriel/cbf05903d872fcdeabd035e4d3c46942#file-depends_on-json

**Comment by apparentlymart** [comment]
Hi @tebriel! Thanks for that additional context.

From reviewing your list of dependencies, the one that stuck out to me as concerning is `aws_api_gateway_method_response.200`.

Terraform 0.12 now requires resource names to be valid identifiers in the language, which means that they cannot start with digits. (This is a consequence of making resources behave as object values: references to them are now just normal attribute access expressions, whereas in 0.11 they were a special case with some different parsing rules.)

However, the `terraform 0.12checklist` command should've caught this before you upgraded and given some steps to rename it before upgrading:

> `resource "aws_api_gateway_method_response" "200"` has a name that is not a valid identifier.
>
> In Terraform 0.12, resource names must start with a letter. To fix this, rename the resource in the configuration and then use `terraform state mv` to mirror that name change in the state.

I'm not sure why `0.12checklist` didn't flag this as expected. :thinking: Fortunately, it sounds like you've not yet successfully run an `apply` with 0.12 so it's still safe to return to Terraform 0.11.14 to complete the renaming of this resource to something starting with a letter.

The fuller instructions for that would be:

* Make sure that any coworkers working on this configuration know not to make any other changes while you are making this change; it requires coordinating a configuration change with .
* Change the name in the configuration to something else. For the sake of this example, I'll use `"status200"`.
* Run `terraform state mv aws_api_gateway_method_response.200 aws_api_gateway_method_response.status200` to apply the same renaming to the state.
* Run `terraform apply` to verify that no further changes are proposed and thus the configuration and state are consistent.

In a different issue we saw that apparently sometimes running `terraform state mv` followed by a `terraform apply` for some reason don't update existing `depends_on` entries in the state. Hopefully the above will be sufficient to unblock you, but if you still run into problems I'd suggest checking the state to see if any references to the old name `aws_api_gateway_method_response.200` remain. The easiest path forward if so might be to just edit the state directly to reflect the new name; we are still looking into whether we can make that automatic in more cases, but given how small this update is you may wish to apply the fix manually to avoid being blocked on that longer investigation.

**Comment by tebriel** [comment]
@apparentlymart oh! So, back when 0.12.0 came out, I fixed this particular problem, applied, and got things working by renaming that to `aws_api_gateway_method_response.OK`. Sounds like the state didn't update??

**Comment by tebriel** [comment]
confirmed that modifying the tf-state json to replace `.200` with `.OK` fixed my problem, I dunno if there's any more support I can provide to you for this bug, let me know or close if not!

**Comment by apparentlymart** [comment]
Ahh okay! So you've hit the thing I was touching on in my last paragraph where `depends_on` didn't get updated along with the rest of the changes in the state. :confounded: 

In that case, the fastest path forward here would be to manually edit the state to replace that reference from `aws_api_gateway_method_response.200` to `aws_api_gateway_method_response.OK`, and then Terraform should be able to initialize.

**Comment by apparentlymart** [comment]
Aha! Our comments collided.

I'm glad to hear that updating the state directly worked. Feel free to close this then, since the issue I was referring to is being tracked already by #21435.

**Comment by rayterrill** [comment]
I just had to do the same thing for exactly the same reason - modify saved state because of a "200" resource entry in my "depends_on" section. This note saved me a bunch of time! :)
