### ISSUE TITLE
0.12upgrade converts boolean expression incorrectly

### ISSUE THREAD

**Issue by antonbabenko** [hashicorp/terraform#21592]
### Terraform Version

Terraform 0.12

### Terraform Configuration Files

```hcl
variable "create_vpc" {}
variable "public_subnets" { type = "list" }
variable "one_nat_gateway_per_az" {}

resource "aws_subnet" "public" {
  count = "${var.create_vpc && (! var.one_nat_gateway_per_az || length(var.public_subnets) > 0) ? length(var.public_subnets) : 0}"

  vpc_id = "..."
  cidr_block = "${element(concat(var.public_subnets, list("")), count.index)}"
  availability_zone = "..."
}

```

### Expected Behavior

`count` should keep second expression in brackets (as a single expression). Now it splits into two and makes this expression incorrect.

```hcl
variable "create_vpc" {
}

variable "public_subnets" {
  type = list(string)
}

variable "one_nat_gateway_per_az" {
}

resource "aws_subnet" "public" {
  count = var.create_vpc && (false == var.one_nat_gateway_per_az || length(var.public_subnets) > 0) ? length(var.public_subnets) : 0

  vpc_id            = "..."
  cidr_block        = element(concat(var.public_subnets, [""]), count.index)
  availability_zone = "..."
}
```

### Actual Behavior

```hcl
variable "create_vpc" {
}

variable "public_subnets" {
  type = list(string)
}

variable "one_nat_gateway_per_az" {
}

resource "aws_subnet" "public" {
  count = var.create_vpc && false == var.one_nat_gateway_per_az || length(var.public_subnets) > 0 ? length(var.public_subnets) : 0

  vpc_id            = "..."
  cidr_block        = element(concat(var.public_subnets, [""]), count.index)
  availability_zone = "..."
}
```

### Steps to Reproduce

`terraform 0.12upgrade`

### References

https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/275

**Comment by apparentlymart** [comment]
Thanks for reporting this, @antonbabenko!

I think this is a result of the unusual way HIL (Terraform's former expression language) represents the `!` operator: it turns it into a binary `==` operator with one of the operands set to `false`. I remember we have some logic in there to deal with the similar situation with the arithmetic negation operator `-` (which HIL interprets as `0 - value`) but presumably missed a similar rule for the boolean inverse.

**Comment by teamterraform** [comment]
Hi @antonbabenko! Thanks for reporting this.

Since `terraform 0.12upgrade` has been in use for several months now, we've decided that we're going to freeze its current behavior just because that way everyone who is following the upgrade guide to move from 0.11 will be starting from the same baseline.

We might still make some changes to the command in exceptional circumstances like crashes, but for this particular issue it seems to have occurred rarely enough in practice that we're going to accept it as unfortunate but leave it in place.

Thanks again for reporting it.
