### ISSUE TITLE
v0.12, backend "azurerm", init: "blob.azure.com" - not able to connect: "no such host"

### ISSUE THREAD

**Issue by lwillek** [hashicorp/terraform#21595]
Hi there,

not sure if this is a bug or just wrong configuration. Please help by trying to reproduce the behave. My main system is a CentOS Linux release 7.6.1810, but I was able to reproduce the same behave on macOS 10.14.15.

I use azurerm as backend, and this is not working anymore with the following config with v0.12., but works perfectly fine with v0.11.14.

Steps to reproduce:

* Create a service principal, according to this documentation: https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html
* Then create a storage account and container, in order to enable to store the remote state.
* Make sure the following environment variables are set:
```
ARM_ENDPOINT=https://management.azure.com
ARM_ENVIRONMENT=public
ARM_TENANT_ID=00000000-0000-0000-0000-000000000000
ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
ARM_CLIENT_ID=00000000-0000-0000-0000-000000000000
ARM_CLIENT_SECRET=00000000-0000-0000-0000-000000000000
ARM_ACCESS_KEY=****long...key****==
```

* configure providers:
```
$ cat providers.tf
provider "azurerm" {
  version = "~> 1.29"
}
terraform {
  backend "azurerm" {
    storage_account_name = "tfstore***...***"
    container_name       = "test"
    resource_group_name  = "RG_Terraform"
    key                  = "terraform.tfstate"
  }
}
provider "random" {
  version = "~> 2.1"
}
provider "template" {
  version = "~> 2.1"
}
```
Expected Behave: 
```
$ ~/bin/terraform/0.11.14/terraform init 
Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working...
```
Current, non working behave with v0.12:
```
$ ~/bin/terraform/0.12.0/terraform init
Initializing the backend...

Error refreshing state: Get https://tfstore***...***.blob.azure.com/test/terraform.tfstate: dial tcp: lookup tfstore***...***.blob.azure.com on 8.8.8.8:53: no such host
```
or a very similar error: (this is with macOS 10.14.15 and no existing .terraform folder)
```
Error: Failed to get migrated workspaces: Get https://tfstore***...***.blob.azure.com/test?comp=list&prefix=terraform.tfstateenv%3A&restype=container: dial tcp: lookup tfstore***...***.blob.azure.com on 8.8.8.8:53: no such host
```

My guess: The domain `blob.azure.com` is not valid. Primary blob service endpoint
is `https://tfstore***...***.blob.core.windows.net` and not `https://tfstore***...***.blob.azure.com` Maybe this is causing the behave.

**Comment by lwillek** [comment]
I found something, with debug output enabled, v0.12.1:
```
Initializing the backend...
2019/06/04 23:47:47 [DEBUG] Loading Environment from Endpoint "https://management.azure.com"
```
This line was missing in the debug output of v0.11.14

After removing the environment variable, everything is fine (v0.12.1)
```
$ unset ARM_ENDPOINT
$ terraform init
...
2019/06/04 23:54:03 [DEBUG] Loading Environment "public"
...
```
However, I do not understand why I observed this behave. I thought the environment variable ARM_ENDPOINT is only setting the  Azure Resource Manager API Endpoint for Azure Stack. Seems since v.0.12, also other information as the storage endpoint suffix are obtained from there. 

Still unclear to me if this is a bug or a feature, or the variable ARM_ENDPOINT is set wrong in my environment.

**Comment by tombuildsstuff** [comment]
@lwillek as you've mentioned the `ARM_ENDPOINT` environment variable only needs to be set when using a Custom Azure Environment (e.g. Azure Stack) - this is not supported for one of the main environments (e.g. Public, China, Germany, US Gov). Since this behaviour is intentional ([and the documentation calls out this should only be used for Azure Stack](https://www.terraform.io/docs/backends/types/azurerm.html#endpoint) I'm going to close this issue for the moment.

Thanks!
