### ISSUE TITLE
TestCheckResourceAttr reporting error on nested field

### ISSUE THREAD

**Issue by kevinkirkup** [hashicorp/terraform#21618]
### Terraform Version

```
% terraform -v
Terraform v0.12.1
```

### Terraform Configuration Files

```hcl
  nat_config {
    enabled = true

    mappings {
      native_cidr = "192.168.0.0/24"
    }

    mappings {
      native_cidr = "192.200.0.0/16"
    }
  }
```

### Debug Output

```
pureport_aws_connection.main:
  ...
  name = AwsDirectConnectNatMappingTest
  nat_config.# = 1
  nat_config.0.blocks.# = 2
  nat_config.0.blocks.0 = 100.78.0.0/16
  nat_config.0.blocks.1 = 100.79.0.0/16
  nat_config.0.enabled = true
  nat_config.0.mappings.# = 2
  nat_config.0.mappings.0.nat_cidr = 100.78.0.0/24
  nat_config.0.mappings.0.native_cidr = 192.168.0.0/24
  nat_config.0.mappings.1.nat_cidr = 100.79.0.0/16
  nat_config.0.mappings.1.native_cidr = 192.200.0.0/16
  nat_config.0.pnat_cidr = 100.78.255.240/28
  network_href = /networks/network-EhlpJLhAcHMOmY75J91H3g
  peering_type = PRIVATE
  speed = 100
```

But test reports failure:
```
--- FAIL: TestAWSConnection_nat_mappings (152.58s)
    testing.go:568: Step 0 error: Check failed: Check 5/10 error: pureport_aws_connection.main: Attribute 'nat_config.0.mappings.0.native_cidr' not found
FAIL
```

From Acceptance Tests:
```
Check: resource.ComposeTestCheckFunc(
	testAccCheckResourceAWSConnection(resourceName, &instance),
	resource.TestCheckResourceAttrPtr(resourceName, "id", &instance.Id),
	resource.TestCheckResourceAttr(resourceName, "name", "AwsDirectConnectNatMappingTest"),
	resource.TestCheckResourceAttr(resourceName, "nat_config.0.enabled", "true"),
	resource.TestCheckResourceAttr(resourceName, "nat_config.0.mappings.0.native_cidr", "192.168.0.0/24"),
	resource.TestCheckResourceAttrSet(resourceName, "nat_config.0.mappings.0.nat_cidr"),
	resource.TestCheckResourceAttr(resourceName, "nat_config.0.mappings.1.native_cidr", "192.200.0.0/16"),
	resource.TestCheckResourceAttrSet(resourceName, "nat_config.0.mappings.1.nat_cidr"),
	resource.TestCheckResourceAttrSet(resourceName, "nat_config.0.pnat_cidr"),
	resource.TestCheckResourceAttrSet(resourceName, "nat_config.0.blocks"),
),
```

### Expected Behavior

It should not fail.

### Actual Behavior

The test function reports an error.

**Comment by jbardin** [comment]
Hi @kevinkirkup,

Looking at the schema in the linked repository, `mappings` is a `TypeSet`, which is an unordered data structure, and is not directly addressable. Unfortunately there is no helper for verifying individual set value at the moment, and it looks like most providers insert the hash addressed directly, which in this case I think would look like:

    resource.TestCheckResourceAttr(resourceName, "nat_config.0.mappings.1699062720.native_cidr", "192.168.0.0/24")

Improving this will be part of the ongoing work with the new provider SDK.

**Comment by kevinkirkup** [comment]
I'm OK with that, I guess, but then why does the terraform debug output listed above us the `0`, `1`, index notation?

**Comment by jbardin** [comment]
Terraform core uses a new strong type system, and stores the state in an entirely different format. For the provider tests, we have to shim the new state back into the format expected by legacy SDK. Since the shims can't determine what values the provider would use for the hash, it gives them ordinal indexes, which are parsed identically by the old code. We chose to display the state in this way to make it more familiar to provider developers, rather than to display the new typed values or a possibly schema-less json.
