### ISSUE TITLE
Blank terraform.tfvars required

### ISSUE THREAD

**Issue by alexclifford** [hashicorp/terraform#2161]
I have set environment variables for region, access key, and secret key and have a variables.tf file with some defaults but when I run `terraform plan` I get prompted for values for my variables, even though they have defaults. If I create a blank terraform.tfvars file and run again it works without prompting for the values. Can I achieve this functionality without a blank terraform.tfvars file?

**Comment by phinze** [comment]
@alexclifford in fact I think this bug may be in the other direction - I'm surprised that input is not still requested when the blanek `tfvars` file is present.

You can tell terraform to avoid asking for input with the `-input=false` flag or the `TF_INPUT=false` env var.

Going to leave this open as a bug so we can get the `tfvars` behavior made consistent.

**Comment by mitchellh** [comment]
Reproduced. This is pretty weird. Going to look into it.
