### ISSUE TITLE
Azure getting started tutorial: outdated syntax for "tags"

### ISSUE THREAD

**Issue by sjpb** [hashicorp/terraform#21614]
### Terraform Version

```
v0.12.0
```

### Terraform Configuration Files

Config file as per tutorial here: https://learn.hashicorp.com/terraform/azure/change_az

```hcl
resource "azurerm_resource_group" "rg" {
    name     = "myTFResourceGroup"
    location = "eastus"

    tags {
        environment = "TF sandbox"
    }
}
```

### Expected Behavior

Tag should have been created.

### Actual Behavior

```
Error: Unsupported block type

  on main.tf line 8, in resource "azurerm_resource_group" "rg":
   8:     tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

tf version is from Azure cloud shell, as suggested in above tutorial. Appears the tutorial was written for an older version and correct syntax should be `tags = ...`

**Comment by camalloy** [comment]
Had this same issue, if you look at the error message it gives a hint, just need to add a '=' after tags, they must have updated the syntax. 

resource "azurerm_resource_group" "rg" {
    name     = "myTFResourceGroup"
    location = "eastus"

    tags = {
        environment = "TF sandbox"
    }
}
