### ISSUE TITLE
Azure getting started tutorial: Provider version incompatible with Azure shell TF version

### ISSUE THREAD

**Issue by sjpb** [hashicorp/terraform#21613]
### Terraform Version

```
v0.12.0
```

### Terraform Configuration Files

```hcl
provider "azurerm" {
    version = "=1.20.0"
}
```

### Expected Behavior

Getting started docs at https://learn.hashicorp.com/terraform/azure/configure_az#providers suggest pinning version as above.

Should install azure provider.

### Actual Behavior

```
Provider "azurerm" v1.20.0 is not compatible with Terraform 0.12.0.

Provider version 1.27.0 is the earliest compatible version. Select it with
the following version constraint:

        version = "~> 1.27"

Terraform checked all of the plugin versions matching the given constraint:
    =1.20.0

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.

Error: no provider exists with the given name
Error: incompatible provider version
```

### Steps to Reproduce

Follow tutorial linked above:
- use Azure cloud shell (which has terraform 0.12.0 as above)
- create config as above
- `terraform init`

**Comment by bgarcial** [comment]
I am using the 1.28.0 provider. https://www.terraform.io/docs/providers/azurerm/index.html and I am not getting this error, maybe is highly probably tha the 0.12. terraform version does not backward compatible with old azure providers versions  ... (?)
c.c @apparentlymart and @mildwonkey

**Comment by mildwonkey** [comment]
This page doesn't exist anymore, and I know it's been updated (probably multiple times!) since this issue was reported, so I am going to close it. Thank you!
