### ISSUE TITLE
`terraform apply <planfile>` fails, when `terraform apply` succeeds

### ISSUE THREAD

**Issue by simoncocking** [hashicorp/terraform#21624]
### Terraform Version

```
Terraform v0.12.1
+ provider.aws v2.13.0
+ provider.external v1.1.2
+ provider.template v2.1.2
```

### Terraform Configuration Files

See this [zip file](https://www.dropbox.com/s/sqveigal3e8fl7r/terraform-apply-fail.zip.pgp) encrypted with your GPG key.

### Debug Output

Traces for both `terraform plan` and `terraform apply` phases are in the above zip file, as is the generated plan file (which contains our Terraform code).

### Expected Behavior

The plan should have been applied without error.

### Actual Behavior

Many instances of the following errors:
```
Error: Resource node has no configuration attached

The graph node for
module.dwh.module.legal_status_table.data.template_file.to_s3 has no
configuration attached to it. This suggests a bug in Terraform's apply graph
builder; please report it!
```
and
```
Error: orphan resource module.dwh.module.f_term_info_table.aws_glue_trigger.on_demand still has a non-empty state after apply; this is a bug in Terraform
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -out=staging.tfplan`
3. `terraform apply staging.tfplan`

Note that when omitting the `plan` phase and allowing `terraform apply` to calculate the plan itself, the `apply` succeeds without error.

**Comment by simonbirtles** [comment]
I am also having the same issue on the same version. When using a plan file (cli or PTFE) the apply fails as described. When applying without a plan file, the run successfully completes (cli).

**Comment by simonbirtles** [comment]
0.12.2 Same issue - Error: orphan resource module.xxxxxxx.module.ddi.data.solidserver_dns_zone_list.reverse_zone still has a non-empty state after apply; this is a bug in Terraform

**Comment by simonbirtles** [comment]
0.12.3 issue persists.

**Comment by alexpekurovsky** [comment]
Just sharing my 3 days debugging story. I had also huge list of 
```Error: orphan resource ... still has a non-empty state after apply; this is a bug in Terraform```

My problem was that couple of resources in the module had:
```
lifecycle {
    ignore_changes = ["metadata.0.labels"]
}
```
This was done for Terraform 0.11, as it couldn't parse some labels (with dots or slashes). Terraform 0.12 successfully parses labels, so this block is not needed. However exactly this block causes problems. Removing the block fixed an apply planfile.

This is definitely a bug, I had to remove all resources and add one after another to find the issue
