### ISSUE TITLE
How to give a single security group for an aws instance ?

### ISSUE THREAD

**Issue by vishnudxb** [hashicorp/terraform#2164]
I need to assign an existing security group to the aws instance. If you are using ''aws_instance"  it should only supports  security_groups ( ie multiple security groups ).  So how to give an existing security group for an aws instance ?

**Comment by radeksimko** [comment]
Hi,
[`aws_instance.security_groups`](https://www.terraform.io/docs/providers/aws/r/instance.html#security_groups) supports **a list** of security groups. See the linked docs.

### Example

```ruby
resource "aws_instance" "web" {
    ami = "ami-1234"
    instance_type = "m1.small"
    security_groups = [
        "${aws_security_group.first.id}",
        "${aws_security_group.second.id}"
    ]
    tags {
        Name = "HelloWorld"
    }
}
```

**Comment by asimataurora** [comment]
@radeksimko `security_groups` list requires `name` instead of `id`.

**Comment by andrewjkeith** [comment]
@asimataurora using the Group ID worked for me

**Comment by suryaval** [comment]
```resource "aws_instance" "mongodb" {
    ami = "ami-0f9cf087c1f27d9b1"
    instance_type = "t2.medium"
    security_groups = [ "sg-07ef9418bd7d280d1" ]
    tags = {
        Name = "mongodb"
        Owner = "suryaval"
        Env = "dev"
    }
}
```
> \* aws_instance.mongodb: Error launching instance, possible mismatch of Security Group IDs and Names. See AWS Instance docs here: https://terraform.io/docs/providers/aws/r/instance.html.

After i modified the security_groups to its name, it started working

```
resource "aws_instance" "mongodb" {
    ami = "ami-0f9cf087c1f27d9b1"
    instance_type = "t2.medium"
    security_groups = [ "openToAll" ]
    tags = {
        Name = "mongodb"
        Owner = "suvallab"
        Env = "dev"
    }
}
```

**Comment by dibyajyotiron** [comment]
The doc is wrong, not even unclear. It says: 
`security_groups - (Optional, EC2-Classic and default VPC only) A list of security group names (EC2-Classic) or IDs (default VPC) to associate with.`
But it should actually take group name, not ids.
#Please update docs.
