### ISSUE TITLE
Update for #953: count for modules

### ISSUE THREAD

**Issue by pauldraper** [hashicorp/terraform#21643]
Bumping this in case it was forgotten.

Of the [top 10](https://github.com/hashicorp/terraform/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) issues, #953 is 2nd oldest and the only that's been locked.

Almost 4 ago, comment was "we'll get this supported." Locking comment almost 2 years ago was "I need to ask for everyone's patience while we figure this out."

In light of recent significant changes including an HCL upgrade, is there anything anyone figured out that could be added to the issue?

**Comment by apparentlymart** [comment]
Hi @pauldraper,

The 0.12 release was part of the work. There is still more work to do, though. We will post updates on the other issue when there is something material to say about it.

Thanks!

**Comment by pauldraper** [comment]
Thanks, sounds like it's not forgotten!
