### ISSUE TITLE
Creating GCP project in terraform

### ISSUE THREAD

**Issue by hitesh1907nayyar** [hashicorp/terraform#21644]
Hi There,

I am having issue in creating a kubernetes cluster on a new google account. The script i am running is mentioned below:

provider "google" {
  credentials = "${file("softwarization-243008-c23b7c7c52a5.json")}"
  region = "${var.gcp_region}"
  zone    = "${var.gcp_zone}"
}

resource "google_compute_route" "gcp_route" {
  name        = "${var.customer-name}-network-route"
  project     = "${var.gcp_project}"
  dest_range  = "0.0.0.0/0"
  network     = "${google_compute_network.gcp_vpc.name}"
  next_hop_gateway = "default-internet-gateway"
}

resource "google_compute_network" "gcp_vpc" {
  name                    = "${var.customer-name}-network"
  project                 = "${var.gcp_project}"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "gcp_subnet" {
  name                     = "${var.customer-name}-subnetwork"
  region                  = "${var.gcp_region}"
  project                 = "${var.gcp_project}"
  ip_cidr_range            = "10.127.0.0/20"
  network                  = "${google_compute_network.gcp_vpc.name}"
  private_ip_google_access = true
}

resource "google_container_node_pool" "kubernetes-cluster-node-pool" {
  name       = "${var.customer-name}-${var.gcp_cluster-name}-nodes"
  project    = "${var.gcp_project}"
  cluster    = "${google_container_cluster.kubernetes-cluster.name}"
  location   = "${var.gcp_zone}"
  node_count = "${var.gcp_min_size}"

  node_config {
    machine_type = "${var.gcp_instance-type}"
    
    oauth_scopes = [
      "compute-rw",
      "storage-full",
      "pubsub",
      "logging-write",
      "service-control",
      "service-management",
      "monitoring",
	  "bigquery",
	  "cloud-platform",
	  "cloud-source-repos",
	  "cloud-source-repos-ro",
	  "datastore",
	  "service-control",
	  "service-management",
	  "taskqueue"
    ]

    labels {
      for = "ReferenceArchitecture"
    }

    tags = ["softwarization", "${var.customer-name}"]
  }

  autoscaling {
    min_node_count = "${var.gcp_desired_capacity}"
    max_node_count = "${var.gcp_max_size}"
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }
}

data "google_container_engine_versions" "uswest1a" {
  location           = "us-west1-a"
  project = "softwarization-net"
  version_prefix = "1.11."
}

resource "google_container_cluster" "kubernetes-cluster" {
  name               = "${var.customer-name}-${var.gcp_cluster-name}"
  project            = "${var.gcp_project}"
  location           = "${var.gcp_zone}"
  remove_default_node_pool = true
  initial_node_count = 1
  
  network            = "${google_compute_network.gcp_vpc.name}"
  subnetwork         = "${google_compute_subnetwork.gcp_subnet.name}"

  enable_legacy_abac = true
  
  node_locations = [
    "${var.gcp_add_zone}",
  ]
}

This script is running in the previously configured google cloud account but not running in the new configured google account. I am getting the below error:

1 error(s) occurred:

* google_compute_network.gcp_vpc: 1 error(s) occurred:

* google_compute_network.gcp_vpc: Error creating Network: googleapi: Error 403: Access Not Configured. Compute Engine API has not been used in project 1025373632116 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1025373632116 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

Even though i have enabled compute engine API. In addition to this adding the  dump logs.

Please help.
[terraform.log](https://github.com/hashicorp/terraform/files/3265421/terraform.log)

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's better to use [the Google provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

If this is an actual bug, please open an issue in the google provider repository. Thanks!
