### ISSUE TITLE
Azure getting started example uses deprecated attribute

### ISSUE THREAD

**Issue by bgarcial** [hashicorp/terraform#21664]
### Terraform Version

```
⟩ terraform version 
Terraform v0.12.1

[I] 

...
```

### Terraform Configuration Files

When I try to create the Public IP resource of this way:

```
# Create public IP
resource "azurerm_public_ip" "publicip" {
  name                         = "${var.resource_prefix}TFPublicIP"
  location                     = "${var.location}"
  resource_group_name          = "${azurerm_resource_group.rg.name}"
  public_ip_address_allocation = "dynamic" deprecated 
}
...
```
Terraform says 
```
⟩ terraform apply

Warning: "public_ip_address_allocation": [DEPRECATED] this property has been deprecated in favor of `allocation_method` to better match the api

  on main.tf line 64, in resource "azurerm_public_ip" "publicip":
  64: resource "azurerm_public_ip" "publicip" {
```
I've changed the resource configuration to

```
# Create public IP
resource "azurerm_public_ip" "publicip" {
  name                         = "${var.resource_prefix}TFPublicIP"
  location                     = "${var.location}"
  resource_group_name          = "${azurerm_resource_group.rg.name}"
  # public_ip_address_allocation = "dynamic" deprecated
  allocation_method = "Dynamic"
}
```
And it's works

The idea here is that the [Azure Getting Started documentation](https://learn.hashicorp.com/terraform/azure/dependencies_az#complete-configuration) will be updated

**Comment by hrai** [comment]
Is this still and issue? Looks like the doco has been updated. 

https://learn.hashicorp.com/terraform/azure/dependencies_az#complete-configuration

![image](https://user-images.githubusercontent.com/4055444/86323157-a7c81e80-bc7f-11ea-92f0-8413d130d8de.png)

**Comment by mildwonkey** [comment]
I am going to close this as a stale issue, the learn guide has had many updates since this was opened. Thanks for reporting it!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
