### ISSUE TITLE
Terraform crash when setting  root_block_device attribute while launching new instance

### ISSUE THREAD

**Issue by ranjitshinde91** [hashicorp/terraform#2166]
Hi, 
I am wriintig script to launh instance in aws.
Below is the template:

```javascript
resource "aws_instance" "demoInstance" {
    ami = "${lookup(var.amis, "demoInstance")}"
    instance_type = "t2.micro"
    key_name ="my-key"
    subnet_id="${aws_subnet.PublicSubnet1.id}"
    source_dest_check = "false"
    root_block_device = ["default"]
    security_groups = ["${aws_security_group.jumpboxSG.id}"]
    tags {
        Name = "jumpbox"
    }
}
```

When i run terrrafom plan, it gets crashed.
Can you please tell me how to change root block device attributes?

Below are the crash.log file contents:

**EDIT by @catsby, formatting and moved crash log to gist:** https://gist.github.com/catsby/ac27d20ef561c713f73d

**Comment by catsby** [comment]
Hello @ranjitshinde91 – `root_block_device` expects a block of configuration. The details of which are outlined here:

- https://terraform.io/docs/providers/aws/r/instance.html#block-devices

And explained in AWS Documentation ion Block Device Mapping:

- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html


An example would be like this:

```
  root_block_device = {
    device_name = "/dev/xvdj"
    volume_size = "200"
    delete_on_termination = false
    volume_type = "gp2"
  }
```


All that said, if you're looking for simply the "default", I think it's safe to omit the `root_block_device` entirely in your example. 

Hope that helps!

**Comment by catsby** [comment]
@phinze Anything we can do here so this kind of thing (`string` used instead of a `map`) should error, not crash?

**Comment by phinze** [comment]
Yeah the fact that it crashes is definitely a bug. We can leave this open until we address.

**Comment by ranjitshinde91** [comment]
@catsby : Thanks is works !

**Comment by catsby** [comment]
@radeksimko great to hear! Let us know if there's anything else. Until then, we'll leave this open until we can address the underlying bug that causes a crash instead of an error.

Thanks for writing in!

**Comment by radeksimko** [comment]
@catsby you meant @ranjitshinde91 I guess? :smiley:

**Comment by catsby** [comment]
@radeksimko haha, yes, sorry! :smile:
