### ISSUE TITLE
"getting started - azure" example does not work with terraform 0.12

### ISSUE THREAD

**Issue by bgarcial** [hashicorp/terraform#21673]
### Terraform (and AzureRM Provider) Version

```
⟩ terraform -v
Terraform v0.12.1

```
### Affected Resource(s)

* Network and compute modules

### Terraform Configuration Files

I am using[ the Getting Stated Azure guideline, and I want to create a compute and a network modules](https://learn.hashicorp.com/terraform/azure/modules_az) of this way:

- Azure RM Network Module to create a vnet and subnet.
- Azure RM Compute Module to create a Linux vm.

```hcl
# Use the network module to create a vnet and subnet
module "network" {
    source              = "Azure/network/azurerm"
    version             = "2.0.0"
    location            = "${var.location}"
    resource_group_name = "${azurerm_resource_group.rg.name}"
    address_space       = "10.0.0.0/16"
    subnet_names        = ["mySubnet"]
    subnet_prefixes     = ["10.0.1.0/24"]
}

# Use the compute module to create the VM
module "compute" {
    source            = "Azure/compute/azurerm"
    version           = "1.2.0"
    location          = "${var.location}"
    vnet_subnet_id    = "${element(module.network.vnet_subnets, 0)}"
    admin_username    = "plankton"
    admin_password    = "Password1234!"
    remote_port       = "22"
    vm_os_simple      = "UbuntuServer"
    vm_size           = "${lookup(var.vm_size, var.environment)}"
    public_ip_dns     = ["zzdns"]
}
```

### Debug Output
But when I apply terraform init I get this:

```
⟩ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "random" v1.3.1 is not compatible with Terraform 0.12.1.

Provider version 2.1.0 is the earliest compatible version. Select it with 
the following version constraint:

	version = "~> 2.1"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.0

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.


No provider "azurerm" plugins meet the constraint "=2.0.0,>= 1.1.0".

The version constraint is derived from the "version" argument within the
provider "azurerm" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.


Error: incompatible provider version



Error: no suitable version is available


[I] 

```

### Expected Behavior

I expect that the modules version being downloaded and its works with the terraform 0.12.1 version, allowing initialize the provider plugins and initialize terraform itsef 

### Actual Behavior

Looks like `azurerm` provider is not compatible with 0.12.1 terraform version in order to  download and initialize the plugins providers and modules itself.

### Steps to Reproduce

- Please follow [this small part of the guide](https://learn.hashicorp.com/terraform/azure/modules_az) 

I am not using any provider explicitly, but when I add 

```
provider "azurerm" {
  version = "=2.0.0"
}
```
I get that output indicated previously. 

Even if I am using `1.28.0` azure provider version I get the same output.

It is a current error related with the azure provider version or does the modules causing some problem here? 

### References

- [Announcement: Upcoming Changes in Version 2.0 of the Azure Provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2807)

- [Plugin installer doesn't filter by protocol version during installation ("Incompatible API version with plugin")](https://github.com/hashicorp/terraform/issues/19221) 

- [Provider incompatible with terraform 0.12.x](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2686)

**Comment by mildwonkey** [comment]
Hi @bgarcial!
I've labeled this issue so we can let the folks who run the Getting Started guides know that this specific example only works with terraform 0.11.


To work around this, or at least understand why this error is occurring: 

The `"compute"` module is the one that's pinning the `random` provider version: https://github.com/Azure/terraform-azurerm-compute/blob/d9a2e38e884eb936d54d400c9fb13e6075ce6896/main.tf

And as you've already found out, that version of `random` is not compatible with terraform 0.12. You may want to open a GH Issue with the module developer, or fork the repository and modify the pinned version - it's possible that other changes are required to make the module compatible with 0.12, however.

**Comment by bgarcial** [comment]
Hi @mildwonkey 
Thanks for the answer, and for labeling the issue.
Does this mean that if I want to work with modules like computer or network do I should use only the terraform 0.11.?

I wrote an issue here in the module developer repository. https://github.com/Azure/terraform-azurerm-compute/issues/104

Thanks

**Comment by mildwonkey** [comment]
_In general_ I can't answer that question for you - it's up to the module developer, or up to you if you want to upgrade the module yourself. 

Having said that, I _suspect_ if you want to work through the current getting started guides exactly as written, you will have an easier time with terraform 0.11. I can't make any promises about that, though; I don't know if that's true for all of the getting started guides or not 🤷‍♀ 

I'm sorry I don't have a definitive answer for you.

**Comment by Swif2er** [comment]
In case anyone will be getting same issue using terraform 0.12 while working through the guide, you can do as @mildwonkey suggested: 
> fork the repository and modify the pinned version

You would want to change 'random' provider version in main.tf of a 'compute' module as below.
```
provider "random" {
  version = ">= 1.0"
}
```
Then, update your main.tf with:
```
provider "random" {
    version = ">= 2.1"
}
```
and update 'compute' module part to use forked and updated version:
```
module "compute" {
    source            = "./terraform-azurerm-compute"
    #version           = "1.2.1"
...
```

That worked for me.

**Comment by jamalikake** [comment]
Thanks @Swif2er , it worked for me and modified the main.tf as below


provider "azurerm" {
    subscription_id = "${var.SubscriptionId}"
    client_id = "${var.ClientID}"
    client_secret = "${var.ClientSecret}"
    tenant_id = "${var.TenantID}"
}

provider "random" {
    version = ">= 2.1"
}

variable "environment" {
    type = "string"
    default = "Dev"
}


variable "resourcegroupname" {
  default = "myterraformrg"
}

variable "location" {

    default = "westus"
  
}

variable "tags" {
    type = "map"
    default = {
        Environment = "Terraform GS"
        Dept = "Engineering"
  }
}

variable "sku" {
  type="map"
  default = {
     southindia ="16.04-LTS"
     westus ="18.04-LTS"
  }
}

resource "azurerm_resource_gruop" "rg" {

    name = "${var.resourcegroupname}"
    location = "${var.location}"
}

module "network" {
  source = "Azure/network/azurerm"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_gruop.rg.name}"
  address_space = "10.0.0.0/16"
  subnet_names= ["MySubnet"]
  subnet_prefixes = ["10.0.1.0/24"]
}

module "compute" {
  #source = "./terraform-azurerm-compute"
  #source = "./.terraform/modules/compute/Azure-terraform-azurerm-compute-a1ea390"
  source = "Azure/compute/azurerm"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_gruop.rg.name}"
  vnet_subnet_id = "${element(module.network.vnet_subnets, 0)}"
  admin_username = "TestUser"
  admin_password = "asdfgasdfg!1"
  remote_port = "22"
  vm_os_profile = "UbuntuServer"
  vm_size = "${lookup(var.vm_size, var.environment)}"
  public_ip_dns = ["zzdns"]  
}

**Comment by mildwonkey** [comment]
This issue has been opened with the education team, so I am going to close it. Thanks!
