### ISSUE TITLE
Support OAuth Token for authenticating on GCS Backend same way the terraform-google-provider does

### ISSUE THREAD

**Issue by primeroz** [hashicorp/terraform#21680]
### Current Terraform Version

0.11.13

### Use-cases
We use Vault to generate dynamic GCP Secrets to then run terraform. 

We would like to use the OAuth token rather than the json private key for all the good reasons stated [here](https://www.vaultproject.io/docs/secrets/gcp/index.html#service-account-keys-quota-limits) but currently we can't because while the terraform google provider support using the token , see [here](https://www.terraform.io/docs/providers/google/provider_reference.html#access_token-1) and the option to expose it as an environment variable, the backend does not.

I did raise a case to the terraform provider first without understanding that the backend is actually part of core

### Attempted Solutions
None really since the backend only work with `credentials.json`

### References

- https://github.com/terraform-providers/terraform-provider-google/issues/3821

**Comment by emilymye** [comment]
@paddycarver moved from https://github.com/terraform-providers/terraform-provider-google/issues/3821

**Comment by luis-silva** [comment]
@emilymye I took the liberty of adding this PR as I have a similar use case and quite need the functionality. Can you review it?

**Comment by luis-silva** [comment]
@paddycarver @emilymye @mildwonkey Anyone happy to do a quick review of the PR associated with this issue? It's pretty straight forward.
