### ISSUE TITLE
connection block not validated if not present

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#21690]
When using a provisioner that requires a connection to the remote host, a missing `connection` block is not validated at all, causing the provisioner to repeatedly attempt and fail to connect.

```
resource "null_resource" "vm" {
  provisioner "remote-exec" {
    inline = [
      "echo ok",
    ]
  }
}
```

Log:
```
null_resource.vm (remote-exec): Connecting to remote host via SSH...
null_resource.vm (remote-exec):   Host:
```

The `host` field is always required, and the configuration should fail during validation.

**Comment by LKaemmerling** [comment]
We have more complaints about this, would it be possible to fix this? Is there something we can do?
