### ISSUE TITLE
error when executing the validate cmd in terraform for creating apache server

### ISSUE THREAD

**Issue by chowdamramana** [hashicorp/terraform#21712]
![Capture](https://user-images.githubusercontent.com/50665358/59425039-c5b3ae80-8df2-11e9-863a-a67582308fa7.PNG)
![error](https://user-images.githubusercontent.com/50665358/59425040-c5b3ae80-8df2-11e9-9916-3cf8d255d779.PNG)
it asking me ahost ,why do i give to that.provide any terraform file for create apache server in aws provider

**Comment by jbardin** [comment]
Hi @chowdamramana,

Sorry this wasn't as clear as it could be. The error is correct, the `host` argument is required now for provisioner connections. https://www.terraform.io/upgrade-guides/0-12.html#default-settings-in-connection-blocks
