### ISSUE TITLE
Set custom security policy on AWS ELB

### ISSUE THREAD

**Issue by nwalke** [hashicorp/terraform#2171]
Is there a way to set a custom security policy on an ELB?  I didn't see any mention of it in the documentation. 

https://www.terraform.io/docs/providers/aws/r/elb.html

If not, it would be nice to have.

**Comment by phinze** [comment]
Hi @tubaguy50035 -  perhaps you were looking for the [`security_groups` attribute](https://www.terraform.io/docs/providers/aws/r/elb.html#security_groups)?

Let me know if you meant something else.

**Comment by tubaguy50035** [comment]
Yeah, I should have elaborated a bit more.  We need to disable TLSv1 for some compliance things, so in order to do that I need to set a custom security policy for my HTTPS listener cipher.

**Comment by phinze** [comment]
Ah gotchya - like this:

https://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_SetLoadBalancerPoliciesOfListener.html

We don't support that yet - tagging as a feature request and we'll get this looked at!

**Comment by tubaguy50035** [comment]
Correct.  Along with this:
https://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_CreateLoadBalancerPolicy.html

Thanks!

**Comment by robzienert** [comment]
+1 this would be a great feature.

**Comment by bruno** [comment]
Definitely interested in this particular feature too, it's a must with compliance like PCI-DSS when SSLv3 will soon be banned from the allowed protocols, etc.

**Comment by bruno** [comment]
I am by no means a `golang` expert, so please take this comment with a pinch of salt, it seems that from reading https://github.com/aws/aws-sdk-go/blob/master/service/elb/api.go it seems that adding policies is supported by the SDK ...

**Comment by nwalke** [comment]
The API is not the problem, just need to wait until someone implements it in Terraform.

**Comment by bruno** [comment]
I realise that. I was just being proactive and doing some research and making sure that it was just a terraform side implementation issue. 



—

**Comment by ryanking** [comment]
This is likely a duplicate of #1226.

**Comment by fpmosley** [comment]
A pull request has been created to add a new resource in the AWS provider that will set a custom security policy on the ELB. #5637

**Comment by catsby** [comment]
Closing as a duplicate of #1226, and as @ryanking mentioned it looks like this is implemented in #5637!
