### ISSUE TITLE
Module Source Git SSH Simplification

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#2172]
As referenced here: #2116  

Perhaps consider making the SSH with Git path simpler?  It currently is as follows:

```
module "ami" {
  source = "git::ssh://git@github.com/terraform-community-modules/tf_aws_ubuntu_ami.git"
}
```

Perhaps instead, or additionally, we could use the following, which is the 'normal' command line syntax for using SSH at github (.git is optional).

```
git@github.com:user/repo

git@github.com:user/repo//subfolder
```

berkshelf.com also has some simple options in their git / github section.

**Comment by phinze** [comment]
This is still a good idea I think! Refiled in the now-shared upstream library.
