### ISSUE TITLE
Terraform plan/apply shows user_data being added but the script doesn't run

### ISSUE THREAD

**Issue by yum-dev** [hashicorp/terraform#21725]
I'm facing an issue with my terraform script. Terraform plan/apply shows user_data being added but the script doesn't run. I just want to mount an ebs to my ec2. 

Following is the terraform script:
```hcl

provider "aws" {
  access_key = "AAAAAAA"
  secret_key = "AAAAAAA"
  region     = "us-east-1"
}

resource "aws_volume_attachment" "tf_disaster_recovery_attachment" {
    device_name = "/dev/xvdf"
    volume_id = "${aws_ebs_volume.tf_disaster_recovery_ebs.id}"
    instance_id = "${aws_instance.dr_cicd.id}"
}

resource "aws_placement_group" "tf_disaster_recovery_pg" {
  name     = "tf_disaster_recovery_pg"
  strategy = "spread"
}

 

resource "aws_instance" "dr_cicd" {
  ami           = "ami-024a64a6685d05041"
  instance_type = "t2.micro"
  key_name = "tf_disaster_recovery_key"
  subnet_id = "subnet-0b564040942b6d1b2"
  security_groups = ["sg-b0ac1cc6", "sg-07c9db266e9741861", "sg-1954ae63", "sg-0cd9132d8b3697dff"]
  user_data = "${file("attach_vol.sh")}"
  placement_group = "${aws_placement_group.tf_disaster_recovery_pg.name}"


  provisioner "local-exec" {
    command = "echo ${aws_instance.dr_cicd.private_ip} > ip_address.txt"
  }

  tags = {
    Name = "tf_disaster_recovery"
  }
}

resource "aws_ebs_volume" "tf_disaster_recovery_ebs" {
    availability_zone = "${aws_instance.dr_cicd.availability_zone}"
    size = 5
    type = "gp2"
}

resource "aws_key_pair" "tf_disaster_recovery_key" {
  key_name   = "tf_disaster_recovery_key"
  public_key = "${file("mykey.pub")}"
}
```

Following is the shell script. 

```
#! /bin/bash

sudo mkfs.ext4 /dev/xvdf
sudo mount /dev/xvdf /opt
sudo echo '/dev/xvdf /opt  ext4  defaults  0 0' >> /etc/fstab
```

Terraform Version:

```
$ terraform -v
Terraform v0.12.1
+ provider.aws v2.15.0

Your version of Terraform is out of date! The latest version is 0.12.2. You can update by downloading from www.terraform.io/downloads.html
```

**Comment by mildwonkey** [comment]
Hi @yum-dev !
To start, I want to reassure you that I edited your comment to fix the code blocks, I did not change any content.

At a glance, your config looks like it should work. Are you certain that the user data script isn't running, as opposed to it running unsuccessfully? For example, have you tried connecting to the VM you've created and checking the appropriate logs (here's some more info from the [aws documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html))?

**Comment by yum-dev** [comment]
> Hi @yum-dev !
> To start, I want to reassure you that I edited your comment to fix the code blocks, I did not change any content.
> 
> At a glance, your config looks like it should work. Are you certain that the user data script isn't running, as opposed to it running unsuccessfully? For example, have you tried connecting to the VM you've created and checking the appropriate logs (here's some more info from the [aws documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html))?

Hey @mildwonkey ,
I added the following in my user-data shell script 
`#! /bin/bash -xe

exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
  mkfs.ext4 /dev/xvdf
  mount /dev/xvdf /opt
  echo "/dev/xvdf /opt  ext4  defaults  0 0" >> /etc/fstab
  echo "Hello from user-data!"
`

And got the following output:
`ubuntu@ip-10-122-95-12:~$ sudo lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0    0 89.4M  1 loop /snap/core/6818
loop1     7:1    0   18M  1 loop /snap/amazon-ssm-agent/1335
xvda    202:0    0    8G  0 disk 
└─xvda1 202:1    0    8G  0 part /
xvdf    202:80   0    5G  0 disk 
ubuntu@ip-10-122-95-12:~$ 
ubuntu@ip-10-122-95-12:~$ 
ubuntu@ip-10-122-95-12:~$ 
ubuntu@ip-10-122-95-12:~$ 
ubuntu@ip-10-122-95-12:~$ 
ubuntu@ip-10-122-95-12:~$ sudo cat /var/log/
amazon/                auth.log               cloud-init-output.log  dist-upgrade/          journal/               landscape/             lxd/                   tallylog               user-data.log          
apt/                   btmp                   cloud-init.log         dpkg.log               kern.log               lastlog                syslog                 unattended-upgrades/   wtmp                   
ubuntu@ip-10-122-95-12:~$ sudo cat /var/log/
amazon/                auth.log               cloud-init-output.log  dist-upgrade/          journal/               landscape/             lxd/                   tallylog               user-data.log          
apt/                   btmp                   cloud-init.log         dpkg.log               kern.log               lastlog                syslog                 unattended-upgrades/   wtmp                   
ubuntu@ip-10-122-95-12:~$ sudo cat /var/log/user-data.log 
+ mkfs.ext4 /dev/xvdf
mke2fs 1.44.1 (24-Mar-2018)
The file /dev/xvdf does not exist and no size was specified.
ubuntu@ip-10-122-95-12:~$ 
`

Also, how did you change the formatting for the code blocks?

**Comment by mildwonkey** [comment]
Thanks for the update! The good news is now you know that your user-data is running. Unfortunately, I can't help you debug the script itself as it's not a terraform problem. 
I'm going to close this issue, but if you run into any bugs with terraform please open a new issue.
