### ISSUE TITLE
oci vcn_id output is date

### ISSUE THREAD

**Issue by brandonprasnicki** [hashicorp/terraform#21720]
data "oci_core_vcns" "my_vcns" {
    #Required
    compartment_id = "${var.compartment_ocid}"
    display_name ="VCN"
}
creating subnet with this:
  vcn_id = "${data.oci_core_vcns.my_vcns.id}"

plan shows this:
vcn_id:                                                              "" => "2019-06-13 18:52:54.6707884 +0000 UTC"

error says I don't have access to that id, but it is because it is date and not ID.

if it is in same module/run, this works fine:
 vcn_id         = "${oci_core_virtual_network.VCN.id}"
Terraform v0.11.13
+ provider.local v1.2.2
+ provider.null v2.1.2
+ provider.oci v3.28.2
+ provider.template v2.1.2

**Comment by brandonprasnicki** [comment]
or I guess not plan but apply...

**Comment by mildwonkey** [comment]
Hi @brandonprasnicki ! 
This is very odd. My first thought was that this is a problem in the provider, but I'm not positive - I took a look at the provider code and everything looked correct. Can you include the debug output from your plan (in a gist, please)? I'm really not sure if that will show us anything useful, but I don't have access to oci to reproduce the issue myself. If nothing appears amiss in the debug log, I can move this to the provider repository.

**Comment by brandonprasnicki** [comment]
[terraform.txt](https://github.com/hashicorp/terraform/files/3290839/terraform.txt)

[vcn.tf.txt](https://github.com/hashicorp/terraform/files/3290843/vcn.tf.txt)
[tf1.txt](https://github.com/hashicorp/terraform/files/3290846/tf1.txt)

I gotta be doing something wrong with the data section for oci_core_vcns.  It's interesting when I add oci_core_vcn during the apply it shows output, not sure why that is/isn't.

**Comment by mildwonkey** [comment]
Thanks for the additional information @brandonprasnicki, this is very helpful. 

Your original issue comment and your attached code vary a bit, so I want to start by making sure I'm looking at the right config.

This is the only vcns in your attached config, and it's missing the optional `display_name` attribute that you included in the issue comment (I don't know if that makes a difference in this case, just noting the difference):

```hcl
data "oci_core_vcns" "inspyrus_vcns" {
    #Required
    compartment_id = "${var.compartment_ocid}"
}
```

It might be interesting to try [other exported attributes](https://www.terraform.io/docs/providers/oci/d/core_vcns.html#attributes-reference) as outputs so we can see if all the attributes are incorrect, or just the `id`:

```hcl
output "networks" {
  value = "${data.oci_core_vcns.inspyrus_vcns.virtual_networks}" 
}
```

Note that in terraform 0.12 you can output the entire data source:

```hcl
output "everthing" {
  value = data.oci_core_vcns.inspyrus_vcns 
}
```

**Comment by brandonprasnicki** [comment]
I don't think oci is supported in 12 yet?  Or it wasn't a few weeks back...

Yeah it's different because I'm trying to isolate and try different things.  When I try other attributes I get empty or errors.

output "virtual_networks" {
  value = ["${data.oci_core_vcns.test_vcns.virtual_networks}"]
}
produces output:

virtual_networks = []

If I try data.oci_core_vcns.test_vcns.cidr_block, or some other attribute, it says that data.oci_core_vcns.test_vcns.cidr_block does not have attribute for variable data.oci_core_vcns.test_vcns.cidr_block... 

I may be very well confused because when I look at https://www.terraform.io/docs/providers/oci/d/core_vcns.html I am not sure the difference when it says:
Attributes Reference
The following attributes are exported:

virtual_networks - The list of virtual_networks.
» Vcn Reference
The following attributes are exported:

but I'm not sure how to reference appropriately these things sometimes.

**Comment by brandonprasnicki** [comment]
Also shouldn't data oci_core_vcns produce a list?  Everytime I try to reference .0. or [0] it says it's a string.  Maybe it's that smart if there is only 1 value, or again I am doing something stupid.

**Comment by mildwonkey** [comment]
Ah, good point about the list. You should be able to reference attributes with `[0]` or `*`:

```hcl
output "networks" {
  value = "${data.oci_core_vcns.inspyrus_vcns.*.virtual_networks}" 
}
```

If that's not working, I'd guess this is more likely an issue in the provider and move it to their repository.

**Comment by mildwonkey** [comment]
Oh! I found this in a [comment](https://github.com/terraform-providers/terraform-provider-oci/issues/550#issuecomment-403540930) in the oci repository:

```vcn_id         = "${lookup(data.oci_core_vcns.core.virtual_networks[0],"id")}"```

**Comment by brandonprasnicki** [comment]
OK I did try a lookup before too, and I got this similar error.
* data.oci_core_vcn.test_vcn: At column 59, line 1: list "data.oci_core_vcns.inspyrus_vcns.virtual_networks" does not have any elements so cannot determine type. in:

${lookup(data.oci_core_vcns.inspyrus_vcns.virtual_networks[0],"id")}
This:
output "networks" {
  value = "${data.oci_core_vcns.inspyrus_vcns.*.virtual_networks}" 
}
produces empty list.  I think there is something wrong with this data source in oci?  Any word on oci support in 12 eta?
networks = [
    [
    ]
]

**Comment by mildwonkey** [comment]
I'm sorry that didn't help. I will label this so it gets moved to the oci repository. That's also where you could ask about 0.12 support, though according to their [GitHub Releases](https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.27.0) page it's been supported since v3.27.0.
