### ISSUE TITLE
remote_state config type error

### ISSUE THREAD

**Issue by PsyonixBarrett** [hashicorp/terraform#21738]
### Terraform Version

```
Terraform v0.12.2
+ provider.google v2.8.0
+ provider.kubernetes v1.7.0
```

### Terraform Configuration Files

```hcl
data "terraform_remote_state" "remote_state" {
  backend = "gcs"

  config {
    bucket = "my-bucket"
    prefix = "/terraform-state"
  }
}
```

### Expected Behavior

`terraform plan` should result in standard output without errors.

### Actual Behavior

An error occurs...
```
Error: Unsupported block type

  on backend.tf line 11, in data "terraform_remote_state" "online-services":
  11:   config {

Blocks of type "config" are not expected here. Did you mean to define argument
"config"? If so, use the equals sign to assign it a value.
```

### Additional Context

This is using a gcs bucket for the backend.

**Comment by jbardin** [comment]
Hi @PsyonixBarrett,

It look s like you haven't completed the [0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html) on this configuration. Attributes and blocks are now better differentiate in the config language (https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks), and the `0.12upgrade` tool will automatically rewrite this configuration for you.

**Comment by PsyonixBarrett** [comment]
Thanks @jbardin - but I did try to run the upgrade with using the `config` as an attribute instead of a block. That results in the following error...
```
Error: Invalid backend configuration

  on backend.tf line 11, in data "terraform_remote_state" "remote_state":
  11:   config = {
  12:     bucket = "my-bucket"
  13:     prefix = "/terraform-state/my/prefix"
  14:     name   = "default.tfstate"
  15:   }

The given configuration is not valid for backend "gcs": unexpected attribute
"name".
```

**Comment by jbardin** [comment]
@PayscaleNateW, The `name` attribute wasn't in the original example, but there error appears to be correct and it isn't a valid attribute for a `gcs` backend. You should be able to just remove that from the config.

**Comment by PsyonixBarrett** [comment]
Duh, just realized that. I should have read the error message more closely! Thanks

**Comment by MilanDasek** [comment]
I am sorry I have the same problem


```
data "terraform_remote_state" "aws_dynamodb_table" {
  backend = "s3"
  
  config {
    bucket = "infrastructure"
    key = "terraform/staging/terraform.tfstate"    
    region = "eu-west-1"
  }
}

output "aws_dynamodb_table_y" {
  value = [
    "${data.terraform_remote_state.aws_dynamodb_table.outputs.aws_dynamodb_table}", 

  ]
}
```

receiving

```Error: Unsupported block type

  on output.tf line 5, in data "terraform_remote_state" "aws_dynamodb_table":
   5:   config {

Blocks of type "config" are not expected here. Did you mean to define argument
"config"? If so, use the equals sign to assign it a value.```

I think it is correct according to this: https://www.terraform.io/docs/backends/types/s3.html

Please advise.
