### ISSUE TITLE
Problem with invalid output on terraform remote state

### ISSUE THREAD

**Issue by xocasdashdash** [hashicorp/terraform#21740]
### Terraform Version

```
Terraform v0.11.14
```
### Crash Output
panic: Unknown: <invalid reflect.Value> invalid Prefix public_ips.rsyslog

goroutine 12655 [running]:
github.com/hashicorp/terraform/builtin/providers/terraform.flatten(0xc000906a80, 0xc000886580, 0x12, 0x2153080, 0xc00001e360, 0x94)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:48 +0x508
github.com/hashicorp/terraform/builtin/providers/terraform.flattenMap(0xc000906a80, 0xc00094ff90, 0xa, 0x215e0c0, 0xc0009c66f0, 0x15)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:65 +0x418
github.com/hashicorp/terraform/builtin/providers/terraform.flatten(0xc000906a80, 0xc00094ff90, 0xa, 0x215e0c0, 0xc0009c66f0, 0x15)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:42 +0x38c
github.com/hashicorp/terraform/builtin/providers/terraform.remoteStateFlatten(0xc000dbb740, 0xc000dbb740)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/builtin/providers/terraform/flatten.go:21 +0xac
github.com/hashicorp/terraform/builtin/providers/terraform.dataSourceRemoteStateRead(0xc000ac6070, 0x0, 0x0, 0xc000ac6070, 0x0)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/builtin/providers/terraform/data_source_state.go:520 +0xc63
github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc000eae5b0, 0xc000899380, 0x0, 0x0, 0xc0005bbc28, 0x1, 0x4)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:290 +0x88
github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc000eae620, 0xc000784e60, 0xc000899380, 0x0, 0xbf396934cb2925b0, 0x73d5a86b)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:426 +0x17f
github.com/hashicorp/terraform/terraform.(*EvalReadDataApply).Eval(0xc000977a60, 0x272dc60, 0xc00060aa90, 0x2, 0x2, 0x23d2203, 0x4)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/terraform/eval_read_data.go:122 +0x144
github.com/hashicorp/terraform/terraform.EvalRaw(0x26e2d40, 0xc000977a60, 0x272dc60, 0xc00060aa90, 0x0, 0x0, 0x0, 0x0)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000977a80, 0x272dc60, 0xc00060aa90, 0x2, 0x2, 0x23d2203, 0x4)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:14 +0x9c
github.com/hashicorp/terraform/terraform.EvalRaw(0x26e2e40, 0xc000977a80, 0x272dc60, 0xc00060aa90, 0x2151940, 0x331f625, 0x20d5760, 0xc000532120)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x11a
github.com/hashicorp/terraform/terraform.Eval(0x26e2e40, 0xc000977a80, 0x272dc60, 0xc00060aa90, 0xc000977a80, 0x26e2e40, 0xc000977a80, 0xc000b0bdb0)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/terraform/eval.go:34 +0x4d
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x233c420, 0xc0000d85f8, 0x0, 0x0)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/terraform/graph.go:126 +0xbc2
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000c5b490, 0x233c420, 0xc0000d85f8, 0xc000290cc0)
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x33b
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/Users/joaquin.fernandez/go/src/github.com/hashicorp/terraform/dag/walk.go:310 +0xa4f
### Expected Behavior

It should not crash.

### Actual Behavior

It crashes. 
### Steps to Reproduce

I'm not really sure how (pretty sure a coworker is using tf 0.11.11) but somehow a list output in one tfstate ended up with a nil value, this meant that anything that depended on that state crashed badly. This issue is very similar to this one: https://github.com/terraform-providers/terraform-provider-terraform/issues/5 but as the code has migrated back to the terraform binary it hasn't been addressed.

### Additional Context
It would be a much easily debuggable issue if it "paniced" with a little bit more information, i had to recompile tf to add some more information to the panic.

Also it would be even better if the switch case [here](https://github.com/hashicorp/terraform/blob/v0.11.14/builtin/providers/terraform/flatten.go#L27-L50) would handle the reflect.Invalid value, I'm not really sure how it ended up on the remote state.

### References
https://github.com/hashicorp/terraform/issues/20663
https://github.com/terraform-providers/terraform-provider-terraform/issues/5

**Comment by xocasdashdash** [comment]
Issues #21832 and #21835 are related to this issue.

**Comment by jbardin** [comment]
To avoid confusion for anyone following the links back here, `21832` and `21835` are quite different, and the crashes originate in code that is not shared with this version of terraform. 

@xocasdashdash, Without the remote state and configuration, we may not be able to offer much advice on how to work around the issue. It may be worth looking at migrating to 0.12, which cannot be effected in the same way, and may provide more insight into what is not working in your situation.

**Comment by danieldreier** [comment]
@xocasdashdash I'm going to close this issue, because we are no longer shipping 0.11 releases and @jbardin has explained why this cannot happen on 0.12 and later, so no other resolution is possible.
