### ISSUE TITLE
Error: Resource node has no configuration attached

### ISSUE THREAD

**Issue by nickmhankins** [hashicorp/terraform#21757]
### Terraform Version
Terraform v0.12.2

### Debug Output
I have the trace output but would prefer not to post it here - even encrypted.  It contains a lot of sensitive information.  Is there an email address @hashicorp I can send it to instead?

### Expected Behavior
Successful plan should have applied

### Actual Behavior
Received error message for seemingly every resource in every module:

Error: Resource node has no configuration attached

The graph node for
module.aas_resources.module.aas_vm_avzone_creation.azurerm_virtual_machine_extension.oms_extension[0]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

Error: Resource node has no configuration attached

The graph node for
module.hana_resources.module.hana_vm_avzone_creation.azurerm_virtual_machine_data_disk_attachment.disk_attachments[7]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

Error: Resource node has no configuration attached

The graph node for
module.ci_resources.module.ci_vm_avzone_creation.azurerm_network_interface.nic[0]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

Error: Resource node has no configuration attached

The graph node for
module.ci_resources.module.ci_vm_avzone_creation.azurerm_virtual_machine_data_disk_attachment.disk_attachments[3]
has no configuration attached to it. This suggests a bug in Terraform's apply
graph builder; please report it!

### Steps to Reproduce
terraform init
terraform plan
terraform apply

### Additional Context
We have around 4 layers of modules so it's hard to post a code snippet to describe the problem.  The plan comes back green and it looks like everything it wants to create is what it should be creating.  Everything worked as it should under TF 0.11.14, we are working through 0.12 changes so we can utilize the new version.

### Workaround
I was able to workaround the issue by not using an output file from `terraform plan` and just doing an apply.  Unfortunately that is not going to work for us because our pipeline automation doesn't work that way.

**Comment by word** [comment]
I came across a similar issue and it was due to an input variable having a wrong type set.  It was:

```
variable "example" {                                                                                                                                                                    
  type  = "boolean"
}
```

changed it to:

```
variable "example" {                                                                                                                                                                    
  type  = bool
}
```

without the quotes.  Not sure if that's the same issue but I had the exact same symptoms.  I'd review your input types first as per: https://www.terraform.io/docs/configuration/variables.html

**Comment by word** [comment]
I can reproduce this reliably by specifying invalid type in 0.12.3:

```
variable "vpc_cidr" {
  type = invalidtype
}
```

plan works, apply with plan file fails:
```
<SNIP>
error: shared-services: Error: orphan resource module.es-srv-vpc.module.vpc.aws_route.nat still has a non-empty state after apply; this is a bug in Terraform
error: shared-services:
error: shared-services:
error: shared-services:
error: shared-services: Error: orphan resource module.es-srv-vpc.module.vpc.aws_internet_gateway.igw still has a non-empty state after apply; this is a bug in Terraform
error: shared-services:
error: shared-services:
error: shared-services:
<SNIP>
```

Apply without a plan file seems to work.  This should error during plan and display a sensible  message.

**Comment by dyegoe** [comment]
I don't know what exactly the steps that I did but I got the same errors and the same workaround worked for me.

**Comment by Esya** [comment]
We've had the same issue here after upgrading to 0.12 - and the problem was that we defined the same attribute twice on the same ressource :

```
resource "aws_alb_target_group" "instance_tg" {
  target_type = "ip"
  name        = "admin-${var.env_name}-tg"
  protocol    = "HTTP"
  port        = "80"
  vpc_id      = "${var.vpc_id}"

  health_check {
    path = "/"
  }
  target_type = "ip"

}
```
We removed the extra "target_type" and it works again

**Comment by sarneaud** [comment]
I've produced it in 0.12 with a duplicate `locals` section.

**Comment by dyegoe** [comment]
@sarneaud nice tip. Just to clarify, did you write your `locals` in one terraform and in a module (that you did)?

**Comment by sarneaud** [comment]
No, I have multiple `locals` in multiple modules and files and it's normally not a problem.  As a part of some refactoring, one got duplicated verbatim.

It looks like a lot of mistakes like this are showing up as "no configuration attached" errors during `apply` in 0.12.  Unfortunately, it can be pretty hard to debug.
