### ISSUE TITLE
provisioner/chef: OS detection should not be based on connection type

### ISSUE THREAD

**Issue by partamonov** [hashicorp/terraform#2175]
Now Chef provisioner behaviour is based on connection type. I'd suggest to add OS option and do not rely on connection type.
1. This will be consistent behaviour with all other resources
2. This will prevent from making special firewall holes only for this resource, as in my case I use packer for AMI creation with SSH and do not want to have one resource using winrm.

**Comment by svanharmelen** [comment]
Guess now with [this](http://t.co/j38uhyGy8U) in the pipeline theres' one more reason to want this... I'll have a look at this shortly.

**Comment by svanharmelen** [comment]
@partamonov don't know if you are able to build Terraform locally yourself, but PR #2483 should enable your use case. Would be cool if you could confirm it works for you so w can close this issue.

**Comment by svanharmelen** [comment]
Fixed by #2483

**Comment by partamonov** [comment]
@svanharmelen  I will, not sure if today, but definitely will check it
