### ISSUE TITLE
error on tf validate with GCS remote state defined

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform#21761]
When credentials (real or fake) are not present, `terraform validate` seems to bomb out when a gcs remote state is defined.

We noticed this because before, we used to do something like this to validate files in CI:
```
terraform validate -check-variables=false "$m" && echo "√ $m"
```

After switching our stuff over for 0.12, and running `terraform init -backend=false` before validate, we were getting the error observed below.

### Terraform Version
```
Terraform v0.12.2
```

### Terraform Configuration Files
```hcl
provider "google" {
  project = var.project
  version = ">= 2.8"
}

terraform {
  backend "gcs" {
    bucket = "foo"
    prefix = "state/bar"
  }
}

data "terraform_remote_state" "meta" {
  backend = "gcs"

  config = {
    bucket = "test2"
    prefix = "state/meta"
  }
}
```

### Debug Output
https://gist.github.com/wyardley/7d9a756c900ea58411a1a76402428e14

### Expected Behavior
```
# terraform init -backend=false
# terraform validate
Success! The configuration is valid.
```

### Actual Behavior
```
# terraform init -backend=false
# terraform validate
Error: storage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```
### References

**Comment by vanstee** [comment]
This is also a problem for referencing remote state using the s3 backend.

```
$ terraform validate

Error: The role "arn:aws:iam::***:role/***" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid
```

**Comment by graemedavidson** [comment]
Also facing the assume role issue. +1 for fix please!

**Comment by teamterraform** [comment]
Hi folks! Sorry for the confusing behavior here. I believe you can workaround this bug by running `terraform validate` in a directory where `terraform init` has run successfully.

I am going to add a bit of context to this particular issue that might help. Here is some of the output from `terraform validate --help`:

```
  Validation requires an initialized working directory with any referenced
  plugins and modules installed. To initialize a working directory for
  validation without accessing any configured remote backend, use:
      terraform init -backend=false
```

Terraform needs an initialized configuration directory in order to run `validate`. In the first example, `terraform init` exits with the same error. If you update your configuration so that `terraform init` is successful, `terraform validate` should also work.

As the help output states, you _can_ run ` terraform init -backend=false`, but `validate` does not appear to be taking that into account.

**Comment by ktham** [comment]
@teamterraform  I'm running into pretty much the same issue. 

My workspaces that contain a `terraform_remote_state` data resource cannot pass terraform validate even after `terraform init -backend=false` has been run

For workspaces that have this defined
```
data "terraform_remote_state" "x" {
  backend = "remote"

  config = {
    organization = "my_org"

    workspaces = {
      name = "my_workspace"
    }
  }
}

```

I see this error:

```
➜  terraform init -backend=false
Initializing modules...
- common_tags in ../../terraform_modules/utils/tagger/common_tags
- tagger in ../../terraform_modules/utils/tagger

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.28.1...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
➜ terraform validate

Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.
```

**Comment by ktham** [comment]
After entering in fake creds to the CLI Config File, I see that `terraform validate` is attempting to pull in the remote state!!!!! 😱 :

Is there a way to disable that behavior? This seems to be a regression with 0.12. This did not happen in 0.11. We ran into this problem as we were upgrading from 0.11 to 0.12

```
Error: Failed to read organization entitlements

  on legacy-prd-tf-remote-state.tf line 1, in data "terraform_remote_state" "prd":
   1: data "terraform_remote_state" "prd" {

The "remote" backend encountered an unexpected error while reading the
organization settings: unauthorized.
```

**Comment by selslack** [comment]
Still a bug in 0.12.23.

**Comment by bendrucker** [comment]
I've opened a PR that should fix this, please 👍 that if you'd like to see this fixed!

https://github.com/hashicorp/terraform/pull/24887
