### ISSUE TITLE
Trying to assign a variable to source block in aws_codebuild_project resource

### ISSUE THREAD

**Issue by hmnp** [hashicorp/terraform#21784]
### Terraform Version

```

terraform -v
Terraform v0.12.2
+ provider.aws v2.15.0

```

### Terraform Configuration Files

```hcl

# main.tf
variable "project_source" {
  type = object({
    type                = string
    location            = string
    buildspec           = string
    report_build_status = bool
  })
}

resource "aws_codebuild_project" "this" {
  name         = var.project_name
  service_role = aws_iam_role.project_role.arn

  artifacts {
    type = "NO_ARTIFACTS"
  }

  environment {
    compute_type    = var.environment_compute_type
    image           = var.environment_image
    type            = var.environment_type
    privileged_mode = var.environment_privileged_mode
  }

  source = var.project_source

}

# example.tfvars

project_source = {
  type                = "NO_SOURCE"
  buildspec           = <<EOF
version: 0.2

phases:
  build:
    commands:
      - docker run hello-world
EOF
}

```

### Debug Output

```hcl

Error: Insufficient source blocks

  on  line 0:
  (source code not available)

At least 1 "source" blocks are required.


Error: Unsupported argument

  on src/project.tf line 47, in resource "aws_codebuild_project" "this":
  47:   source = var.project_source

An argument named "source" is not expected here. Did you mean to define a
block of type "source"?

```

### Actual Behavior

The expected result should be the creation of the resource.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -var-file example.tfvars`
3. `terraform apply`

### Additional Context

In the version `v0.11.14`, similar code was working well. The difference, besides the syntax, was the variable. It looked something like this:

```hcl

variable "project_source" {
  type        = "map"
  default     = {
    type = "NO_SOURCE"

    buildspec = <<EOF
version: 0.2

phases:
  build:
    commands:
      - docker run hello-world
EOF
  }
}

```

I'd then assign the variable to the `source` block and it worked. When I first used the same code in `v0.12.2`, I got a similar error message as I get now.

What am I doing wrong?

Cheers.
Hugo

**Comment by mildwonkey** [comment]
Hi @hmnp! I'm sorry you've experienced this confusing change in behavior.

`source` is a block, not an attribute, so it does not use `=` for assignment. Terraform 0.11 was more permissive - frequently unintentionally - about  `=` type assignment for blocks (likewise in 0.11 you could frequently omit `=` in cases where it is now required by 0.12).

You can use the following syntax (adding in the remaining fields) to use the `project_source` variable in the `source` block. It does require a few more lines of code: 

```
  source {
    type = var.project_source.type
    ... etc
  }
```

**Comment by mildwonkey** [comment]
I was also reminded that `terraform 0.12upgrade` would handle this as a `dynamic` block and print something like this (which you could simplify somewhat):

```
  dynamic "source" {
    for_each = var.project_source
    content {
      # TF-UPGRADE-TODO: The automatic upgrade tool can't predict
      # which keys might be set in maps assigned here, so it has
      # produced a comprehensive set here. Consider simplifying
      # this after confirming which keys can be set in practice.

      buildspec           = lookup(source.value, "buildspec", null)
      git_clone_depth     = lookup(source.value, "git_clone_depth", null)
      insecure_ssl        = lookup(source.value, "insecure_ssl", null)
      location            = lookup(source.value, "location", null)
      report_build_status = lookup(source.value, "report_build_status", null)
      type                = source.value.type

      dynamic "auth" {
        for_each = lookup(source.value, "auth", [])
        content {
          resource = lookup(auth.value, "resource", null)
          type     = auth.value.type
        }
      }
    }
  }
```

**Comment by hmnp** [comment]
Hi @mildwonkey and thank you for your response.

The reason why I was using a variable in 0.11 was because the `source` (and the `artifacts`) blocks can have different values. For example, sometimes I'd need to add a `buildspec` file, sometimes not.

I've tried to use the `dynamic` block but wasn't successful, maybe because I was doing it wrong.

I'll try your example

Cheers.
Hugo

**Comment by apparentlymart** [comment]
Hi @hmnp,

The special `dynamic` block is useful when the number of blocks of a given type must vary based on an expression, but if you know you always need exactly one block and it's only the contents of the block that vary then there's no need to use it: a normal static block definition will do just fine.

However, the `content` of the `dynamic` block in @mildwonkey's example (from `terraform 0.12upgrade`) serves as an example of what you might put inside that block in order to cover all of the arguments inside. The upgrade tool populates every known argument in the current schema, but you can reduce that based on module-specific knowledge about which subset of the arguments can be set in practice.

```hcl
  source {
      type                = var.project_source.type
      buildspec           = lookup(var.project_source, "buildspec", null)
      git_clone_depth     = lookup(var.project_source, "git_clone_depth", null)
      insecure_ssl        = lookup(var.project_source, "insecure_ssl", null)
      location            = lookup(var.project_source, "location", null)
      report_build_status = lookup(var.project_source, "report_build_status", null)

      # If you want to write an the "auth" block here, you can either use a "dynamic"
      # block (if the number of sub-blocks is decided by a list in the var.project_source
      # object) or again just write a single static "auth" block.
  }
```

**Comment by hmnp** [comment]
Hi @apparentlymart,

Thanks for your response.

I was having some issues to run the upgraded version but, after re-downloading the code and run the `0.12upgrade` tool, it worked successfully.

I've a question, when you say "normal static block definition", do you mean something like:

```hcl
  source {
      type                = var.project_source.type
      buildspec           = var.buildspec
      git_clone_depth     = var.git_clone_depth
      insecure_ssl        = var.insecure_ssl
      location            = var.location
      report_build_status = var.report_build_status
  }
```

Cheers.

**Comment by hmnp** [comment]
Thanks for the help
