### ISSUE TITLE
GCP / The custom metadata 'sshKeys' blocks project-wide SSH keys

### ISSUE THREAD

**Issue by mldmld68** [hashicorp/terraform#21797]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
* [Google](https://github.com/terraform-providers/terraform-provider-google)
* [Oracle](https://github.com/terraform-providers/terraform-provider-oci)
* [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

**Comment by mildwonkey** [comment]
I am going to close this, as there's no content in the issue comment. If you are experiencing an issue or have a feature request, please open a new issue and fill out the requested information.
