### ISSUE TITLE
Update in terraform output documentation required (-module deprecated) 

### ISSUE THREAD

**Issue by NickMetz** [hashicorp/terraform#21799]
### Terraform Version

```
0.12.2
```

### Terraform Configuration Files

```hcl
Project root
├── main.tf
├── variables.tf
└── versions.tf

Module root
├── main.tf
├── variables.tf
└── outputs.tf
```

### Expected Behavior

If `terraform output -module` option is no longer supported since terraform 0.12 we should add a deprecated notification in documentation:

https://www.terraform.io/docs/commands/output.html

> -module=module_name - The module path which has needed output. By default this is the root path. Other modules can be specified by a period-separated list. Example: "foo" would reference the module "foo" but "foo.bar" would reference the "bar" module in the "foo" module. 

### Actual Behavior

```
terraform output -module=network

Error: Unsupported option

The -module option is no longer supported since Terraform 0.12, because now
only root outputs are persisted in the state.
```

Also see comment from @smifun in #1940  

### Steps to Reproduce
1. Build a Module with output
2. Run ` terraform output -module=${module_name}` in project root

**Comment by jonseymour** [comment]
--module hasn't been deprecated (implying that the function is works, but is no longer supported). It has actually been completely withdrawn. There is a difference. One doesn't break, the other does.

**Comment by teamterraform** [comment]
Closing this - thanks again for the documentation PR @NickMetz !
