### ISSUE TITLE
Print AWS request information to debug log

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#2179]
Back in `goamz` days the debug log could be used to ensure the proper data was going over the wire to AWS. As we switched to `aws-sdk-go`, all of the struct members are now pointers, which makes the debug output basically just a bunch of memory addresses.

```
[DEBUG] ELB create configuration: &elb.CreateLoadBalancerInput{AvailabilityZones:[]*string{(*string)(0xc208d85fc0), (*string)(0xc208d85fd0), (*string)(0xc208d85fe0), (*string)(0xc208d85ff0)}...
```

We should figure out how to get these structs to print to the log nicely and make a sweep of the AWS provider.

**Comment by clstokes** [comment]
Perhaps related to #2875?

**Comment by phinze** [comment]
This was actually just related to https://github.com/aws/aws-sdk-go/pull/299 and our using it to get pretty request / response information into the debug log. We do this now for AWS resources.

Specific instances of cryptic error messaging are good to track as individudal cases.
