### ISSUE TITLE
Feature Request:  AWS Ignore Tag Ammendments

### ISSUE THREAD

**Issue by DMNSteve** [hashicorp/terraform#2180]
Currently, our instances create EC2 tags on bootstrapping to easily be able to identify the version of our infrastructure they are running.

On the next apply, these tags get deleted as they were not created by terraform.
```
~ aws_instance.instance-datastore
    tags.#:          "2" => "1"
    tags.puppet: "182" => ""
```

Would anybody else would find this useful, or is there is a better solution to this?

**Comment by phinze** [comment]
Going to consider this covered by the forthcoming `ignore_changes` feature in #2018. Feel free to chime in if you disagree! :+1:

**Comment by emoshaya-cognito** [comment]
We are using a Jenkins plugin to deploy a service onto AWS instances and created/update 'VERSION' tag for the instance(s). Unfortunately, Terraform deletes this tag unless there's a way to ignore it. Is there a way to ignore just a single tag, e.g. 'VERSION' as opposed to ignoring all tags? I'd really appreciate a response.

Thanks
