### ISSUE TITLE
Bug with required_version in Terraform 12

### ISSUE THREAD

**Issue by jmgreg31** [hashicorp/terraform#21824]
### Description

There appears to be a bug with how required_version is working.  The format for variable blocks changed in version 12 in that the type constraint no longer needs to be quoted.  If you are using a version <0.12.0, the debug output will not hit the required version block, but cause a confusing error on the variable definition.
   
### Terraform Version

```
Tested Both:
Terraform v0.10.8
Terraform v0.11.8
```

### Terraform Configuration Files

`main.tf`
```hcl
terraform {
  backend "s3" {}
  required_version = "> 0.12.0"
}
```
`variables.tf`
```hcl
variable alias {
  description = "Aliases, or CNAMES, for the distribution"
  type        = list
  default     = []
}
```

### Debug Output

```
Error: Error parsing /$HOME/terraform/variables.tf: At 3:17: Unknown token: 3:17 IDENT list
```

### Expected Behavior

Should show output for required version

### Actual Behavior

Error
### Steps to Reproduce

1. `terraform init`

**Comment by mildwonkey** [comment]
Hi @jmgreg31 ! 

It's expected that terraform 0.11.X and earlier cannot parse the new 0.12 syntax. If you update your `variables.tf` file to adhere to 0.11 syntax (by putting quotes around `"list"`), you will see the expected output:

```
$ terraform init

Error: The currently running version of Terraform doesn't meet the
version requirements explicitly specified by the configuration.
Please use the required version or update the configuration.
Note that version requirements are usually set for a reason, so
we recommend verifying with whoever set the version requirements
prior to making any manual changes.

  Module: root
  Required version: > 0.12.0
  Current version: 0.11.13
```

Note that terraform 0.12 is largely backwards-compatible, so while the quotes around `"list"` are not necessary, they are allowed in 0.12.

**Comment by jmgreg31** [comment]
@mildwonkey I can close this issue if it is expected behavior, but I'm still curious about the use case of required_version then.  If terraform 0.11.X and earlier can't parse the new 0.12 syntax, which I can understand, how can we enforce a user to use v0.12.0 or greater unless they are already using that version?

**Comment by mildwonkey** [comment]
In either case, the user is forced to use the terraform version specified in the `required_version` block. 

In your example, the configuration can be written in a way that both 0.11 and 0.12 can parse, and therefor the user gets an _explicit_ error message telling them which version of terraform is required - that's the error message I shared in my earlier comment.

If the configuration cannot be written in a backwards-compatible way, the user is _implicitly_ forced to upgrade terraform to 0.12 in order to parse the config files, at which point they will get a more precise error message if their terraform version does not match the constraints.

**Comment by jmgreg31** [comment]
@mildwonkey I understand what you mean.  This example was very basic, but the reality is I am using the new syntax (for, for-each) which is not backwards compatible.  For a use case where a module is being used and a user may have no context for which version is needed, the error output could be very misleading.  I was hoping to solve this by using required_version, but looks like this is just not possible between these major releases.  Thanks for the responses.
