### ISSUE TITLE
Expose resource ARN for AWS API Gateway Stage

### ISSUE THREAD

**Issue by chendilv** [hashicorp/terraform#21823]
### Current Terraform Version
```
Terraform v0.12.2
```

### Use-cases
A WAF WebACL can be associated with an API Gateway Stage. This is supported by terraform already : https://www.terraform.io/docs/providers/aws/r/wafregional_web_acl_association.html
However, terraform does not provide a way to access the resource arn for a API Gateway Stage : https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html
(The execution Arn is something different - the API Gateway Stage Arn will have the format arn:aws:apigateway:{region}::/restapis/{api_id}/stages/{stage_name})

### Proposal
Add an attribute called 'arn' to aws_api_gateway_stage that exposes the resource arn of the API Gateway stage.

### References
Closest related GitHub issue : https://github.com/terraform-providers/terraform-provider-aws/issues/6441

Related Terraform docs :
https://www.terraform.io/docs/providers/aws/r/wafregional_web_acl_association.html
https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html

**Comment by dedoussis** [comment]
This should be moved to the [aws provider](https://github.com/terraform-providers/terraform-provider-aws) repo.

**Comment by chendilv** [comment]
Agreed.
Issue opened in aws provider repo : https://github.com/terraform-providers/terraform-provider-aws/issues/9071
