### ISSUE TITLE
Error: timeout - last error: Can't parse this key and certs: Unable to read certificates

### ISSUE THREAD

**Issue by ARivoliRam** [hashicorp/terraform#21839]
Hi there,

I am using vsphere provider to connect and provision the VM. All works well till OS customization. After  it starts with provisioners I started getting errors  . I am trying to provision Windows Server 2016. 

Connecting using WINRM as below .

connection {
        host     = "${vsphere_virtual_machine.vm.default_ip_address}"
        type     = "winrm"
        https    = "false"
        insecure = "true"
        cacert   = "false"
        timeout  = "10m"
      }

using file provisioner trying to copy file to remote newly provisioned server as below. even with any other provisioner I am getting same error "Error: timeout - last error: Can't parse this key and certs: Unable to read certificates"

provisioner "file"{
  source      = "files/"
  destination = "C:/temp/files"
}

2019-06-21T14:45:16.409+0100 [DEBUG] plugin.terraform.exe: file-provisioner (internal) 2019/06/21 14:45:16 [INFO] sleeping for 20s
2019/06/21 14:45:25 [WARN] Errors while provisioning vsphere_virtual_machine.vm with "file", so aborting
2019/06/21 14:45:25 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: 1 error occurred:
	* timeout - last error: Can't parse this key and certs: Unable to read certificates
Error: timeout - last error: Can't parse this key and certs: Unable to read certificates

**Comment by bill-rich** [comment]
Moving this issue back to core. It looks like this is an issue with the key and certs being used with the provisioner.
