### ISSUE TITLE
Documentation - every data source link to real resource

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#21833]
All current documentation

Many google referral links, as well as other methods of finding terraform docs tend to link to the datasources rather than the real resources.

Can each datasource have a link at the top to the corresponding resource and, can each resource that has it, have a link to the corresponding datasource?

The menu nav is so big now, and it has even been collapsed recently because its so big that its created a needless three extra clicks in places to find the resource page if youre unhappily viewing the datasource page instead. 

Strikes me this would be a big win for such a small addition

Expected behaviour (eg on this page as example https://www.terraform.io/docs/providers/google/d/datasource_compute_network.html)

# google_compute_network (datasource)
(For the resource _click here_)

**Comment by mildwonkey** [comment]
This is a lovely suggestion, but it's not anything we can fix in terraform. Each provider maintains their own documentation, so you would need to open an issue with the provider you are using (google, in this case) to request this feature. Thanks!
