### ISSUE TITLE
[bug] check of required_version happens after module resolution

### ISSUE THREAD

**Issue by ryandeivert** [hashicorp/terraform#21844]
### Terraform Version

```
0.12.2
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12.0"
}

module "test" {
  source = "modules/foo_bar_test_modules"  // implicitly relative path
}
```

### Debug Output

```
$ terraform init
Initializing modules...
Downloading modules/foo_bar_test_modules for test...

Error: Module not found

The module address "modules/foo_bar_test_modules" could not be resolved.

If you intended this as a path relative to the current module, use
"./modules/foo_bar_test_modules" instead. The "./" prefix indicates that the
address is a relative filesystem path.


Error: Module not found

The module address "modules/foo_bar_test_modules" could not be resolved.

If you intended this as a path relative to the current module, use
"./modules/foo_bar_test_modules" instead. The "./" prefix indicates that the
address is a relative filesystem path.
```

### Expected Behavior

The `terraform` required_version check occurs and gracefully fails with message like:

```
$ terraform init
Initializing modules...
- test in modules/tf_alert_merger_iam

Error: Unsupported Terraform Core version

This configuration does not support Terraform version 0.12.2. To proceed,
either choose another supported Terraform version or update the root module's
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
```

### Actual Behavior

The output in the `Debug` section above.

### Steps to Reproduce

Add the hcl code above to a `main.tf`, then:
1. `terraform init`
2. `terraform apply`

**Comment by mildwonkey** [comment]
Hi @ryandeivert !

This is by deliberate design. `terraform init` attempts to load the full configuration, including modules, before parsing the config and returning errors so that it can report multiple errors at once. If your modules loaded successfully, you would have seen the expected error (along with any others).

**Comment by ryandeivert** [comment]
thanks for the clarification @mildwonkey :) my main concern is that even if the "loading" of the modules succeeded, the required_version would still stop it dead in its tracks. so, why would you want to go through the hassle of going further if we can just do that check and terminate early... gracefully, of course..? it seems like a misguided design, imo

**Comment by phinze** [comment]
Hi @ryandeivert - As @mildwonkey explained, we elected to go with the "report all errors" vs "fail fast" tradeoff here. Sorry to hear that you disagree with the design, but it is indeed working as we intended, so I'm going to close this issue.
