### ISSUE TITLE
Panic in LengthInt() for the actual value of the Nested List

### ISSUE THREAD

**Issue by afedorch** [hashicorp/terraform#21849]
### Terraform Version

```
12.2
```

### Terraform Configuration Files

The problem exists for the resources with the `optional` `computed` nested lists. As an example of the user scenario:
There is resource `R` that has polymorphic behavior: 
- user can specify `optional` attribute `A` and provide the values for the `optional` `computed` nested list attribute `L`
- user can specify `optional` attribute `B` and there is no attribute `L` for this configuration

For the case `B` there is no attribute `L` in the user's configuration and no value is set in `setData` (setting any value except `nil`/`empty list` will result in an unexpected diff). The `planned` value for attribute `L` is known for this case while the `actual` value is not: https://github.com/hashicorp/terraform/blob/master/plans/objchange/compatible.go#L87

Trying to get the length of the `actual` value for the attribute `L` will result in `panic` due to unknown value:
github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty.Value.LengthInt(0x14d96a0, 0xc0000fac40, 0x12477c0, 0x16806e0, 0x0)
	/go/src/github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty/value_ops.go:871 +

```
if !val.IsKnown() {
	panic("value is not known")
}
```

### Expected Behavior

Similar to `NestingSet` allow unknown values for the `NestingList`:
https://github.com/hashicorp/terraform/commit/0b2cc6298b8adbdaf698c8ce764a476c08bd3061

Adding `!actualV.IsKnown()` to https://github.com/hashicorp/terraform/blob/master/plans/objchange/compatible.go#L87

### Steps to Reproduce

Test case for compatible_test.go to reproduce the problem:
https://github.com/hashicorp/terraform/blob/master/plans/objchange/compatible_test.go#L1137
```
		{
			&configschema.Block{
				BlockTypes: map[string]*configschema.NestedBlock{
					"block": {
						Nesting: configschema.NestingList,
						Block: configschema.Block{
							Attributes: map[string]*configschema.Attribute{
								"foo": {
									Type:     cty.String,
									Required: true,
								},
							},
						},
					},
				},
			},
			cty.ObjectVal(map[string]cty.Value{
				"block": cty.EmptyObjectVal,
			}),
			cty.ObjectVal(map[string]cty.Value{
				"block": cty.UnknownVal(cty.List(cty.Object(map[string]cty.Type{
					"foo": cty.String,
				}))),
			}),
			nil,
		},
```
### References

https://github.com/hashicorp/terraform/commit/0b2cc6298b8adbdaf698c8ce764a476c08bd3061

**Comment by jbardin** [comment]
Thanks for the detailed issue @afedorch!

Do you have an example of how you got an unknown list block in the first place? It's not something that was intended to be possible, but like the other PR mentions, we've made concessions to work with the legacy SDK. I think your suggestion if likely the correct solution, but I want to make sure we understand how these values are coming to be.
