### ISSUE TITLE
Terraform not working for docker

### ISSUE THREAD

**Issue by houami** [hashicorp/terraform#21862]
```
docker version                                                                         
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
terraform version                                                                      
Terraform v0.12.2
```

cat main.tf                                                                      
```
resource "docker_image" "image_id" {
  name = "ghost:latest"
}
```

**Error:**

> terraform init                                                                              

```
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

No available provider "docker" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.


Error: no available version is compatible with this version of Terraform
```

**Comment by phinze** [comment]
Hi there - the Docker provider just needs to release w/ 0.12 support for it to show up. You can track the relevant conversation here: https://github.com/terraform-providers/terraform-provider-docker/issues/144

**Comment by houami** [comment]
As of now what is the workaround?

**Comment by phinze** [comment]
You have a few options for workarounds. One would be to continue to use v0.11.x until the new version of the Docker provider is released. The other would be to [compile the Docker provider](https://github.com/terraform-providers/terraform-provider-docker#developing-the-provider) yourself from its master branch and then follow the [instructions for third-party plugins](https://www.terraform.io/docs/configuration/providers.html#third-party-plugins) to install it.

**Comment by houami** [comment]
HI Paul,
Do you mean I have to use lower version of terraform or the docker?

- Vignesh

**Comment by phinze** [comment]
Hi Vignesh - If you're looking to workaround by downgrading, you'd need to use a 0.11.x version of Terraform.

**Comment by houami** [comment]
Sure Paul, Thanks!!

**Comment by phinze** [comment]
Version looks good! Does `terraform init` download the Docker provider now? If you're still getting an error message can you share it?

**Comment by houami** [comment]
*terraform init*
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com.
..
- Downloading plugin for provider "docker" (1.2.0)...

The following providers do not have any version constraints in
configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain
breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.docker: version = "~> 1.2"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to
see
any changes that are required for your infrastructure. All Terraform
commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget,
other
commands will detect it and remind you to do so if necessary.
$ t*erraform apply*

Error: Error running plan: 1 error(s) occurred:

* provider.docker: Error pinging Docker server: Got permission denied while
trying to connect to the Docker daemon socket at
unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/_ping:
dial unix /var/run/docker.sock: connect: permission denied


$* terraform plan*
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.docker: Error pinging Docker server: Got permission denied while
trying to connect to the Docker daemon socket at
unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/_ping:
dial unix /var/run/docker.sock: connect: permission denied

**Comment by houami** [comment]
I have solved the above error, but this is the error now

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

docker_image.image_id: Creating...
  latest: "" => "<computed>"
  name:   "" => "ghost:latest"

Error: Error applying plan:

1 error(s) occurred:

* docker_image.image_id: 1 error(s) occurred:

* docker_image.image_id: Unable to read Docker image into resource: Unable
to list Docker images: Error response from daemon: client version 1.39 is
too new. Maximum supported API version is 1.38

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by phinze** [comment]
Hi again Vignesh - these are error messages coming from the Docker client now, so we're beyond the scope of the functionality of Terraform. I'd recommend searching around for the error message or looking for help in our [community](https://community.hashicorp.com/). The hint from the error message is that you might need to upgrade your version of Docker, but I think from the Terraform layer we're in the clear!
