### ISSUE TITLE
terraform show, does not work properly for v0.12

### ISSUE THREAD

**Issue by marcb1** [hashicorp/terraform#21864]
When I make the following change to HCL:
```diff
 resource "google_compute_address" "apt-repo-1" {
-  name         = "apt-repo-1"
+  name         = "apt-repo-2"
   address_type = "INTERNAL"
   project      = "${var.project}"
```

I then run `terraform plan`
```
terraform plan -target=google_compute_address.apt-repo-1 -out=plan_file
# google_compute_address.apt-repo-1 must be replaced                                                                 
-/+ resource "google_compute_address" "apt-repo-1" {
      ~ address            = "10.56.28.116" -> (known after apply)
        address_type       = "INTERNAL"
      ~ name               = "apt-repo-1" -> "apt-repo-2" # forces replacement
      + network_tier       = (known after apply)       
```

I expect `terraform show` to show the same diff output as `terraform plan`. However it only displays the resource name (this behavior has changed between TF 0.11 and TF 0.12)
```
terraform show plan_file 
-/+ google_compute_address.apt-repo-1 (new resource required)
```

We have some automation that relies on this behavior. Is there a plan to change `terraform show` to display the full output from the plan file?

**Comment by phinze** [comment]
Hi Marc - check out [`terraform show -json`](https://www.terraform.io/docs/commands/show.html#json-output) which should have all the information you might need for automation purposes - hopefully in an easier to use format than the former plaintext output!

**Comment by marcb1** [comment]
@phinze `terraform show -json` shows the entire state file and not just the changed resource, so I'm not sure how to parse it

**Comment by phinze** [comment]
Aha! My mistake - I thought you could get a plan representation with the changes represented. Let's reopen this then so we can track this need to get the plan changes from `terraform show`. 👍

**Comment by marcb1** [comment]
awesome, thanks!

**Comment by phinze** [comment]
Ok I've gotten a chance to test this now and I can now confirm it definitely works on plans, you just have to specify the plan file as an argument. Check out the example below.

```hcl
# main.tf
resource "random_pet" "test" {}
```

```
❯ terraform -version
Terraform v0.12.3
+ provider.random v2.1.2
```

```
❯ terraform plan -out=plan.tfplan
```

```
❯ terraform show -json plan.tfplan
{"format_version":"0.1","terraform_version":"0.12.3","planned_values":{"root_module":{"resources":[{"address":"random_pet.test","mode":"managed","type":"random_pet","name":"test","p
rovider_name":"random","schema_version":0,"values":{"keepers":null,"length":2,"prefix":null,"separator":"-"}}]}},"resource_changes":[{"address":"random_pet.test","mode":"managed","t
ype":"random_pet","name":"test","provider_name":"random","change":{"actions":["create"],"before":null,"after":{"keepers":null,"length":2,"prefix":null,"separator":"-"},"after_unknow
n":{"id":true}}}],"configuration":{"root_module":{"resources":[{"address":"random_pet.test","mode":"managed","type":"random_pet","name":"test","provider_config_key":"random","schema
_version":0}]}}}
```

I think with this you should be good to go!
