### ISSUE TITLE
Error while initializing daemon

### ISSUE THREAD

**Issue by neuashish** [hashicorp/terraform#21870]
After installing Terraform Enterprise in GCP on Ubuntu machine I get an error bringing up the browser https://(IP):8800/initializing?redirect=/

My source image  "ubuntu-os-cloud/ubuntu-1604-lts"
![save_tfe_erroe](https://user-images.githubusercontent.com/50904911/60081286-21fdc300-974f-11e9-8c46-45517071269d.png)

**Comment by phinze** [comment]
Hi Ashish - Since this is a Terraform Enterprise issue, can you report this as a support ticket? Our support team will help you get to the bottom of this. I'll close this issue so you can continue the conversation with them.
