### ISSUE TITLE
Updating to 0.12.3 resulting in RPC Errors

### ISSUE THREAD

**Issue by J-Hunter-Hawke** [hashicorp/terraform#21880]
I have recently updated Terraform to version 0.12.3 and followed the guideline instructions at the following link:
https://www.terraform.io/upgrade-guides/0-12.html

After fixing my syntax, running a terraform init and plan results in a repeated series of the following errors:
Error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>

Error: rpc error: code = Canceled desc = context canceled

Could anyone shed some light on what may be causing this issue and how I could possibly troubleshoot it?

**Comment by jbardin** [comment]
Hi @J-Hunter-Hawke,

Can you provide a sample configuration, and which providers you're using?
If possible, the output of the trace level log would help greatly in determining which providers may not be working correctly, or what the actual error might be.

**Comment by J-Hunter-Hawke** [comment]
Hi @jbardin,

Thank you for offering help.

Here is a relevant excerpt from the trace level log:
`2019/06/28 08:18:39 [TRACE] dag/walk: visiting "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4"
2019/06/28 08:18:39 [TRACE] vertex "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4": starting visit (*terraform.NodePlannableResourceInstance)
2019/06/28 08:18:39 [ERROR] module.prometheus_backgroundtask.module.security_group_base_rules: eval: *terraform.EvalReadState, err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>
2019/06/28 08:18:39 [ERROR] module.prometheus_backgroundtask.module.security_group_base_rules: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>
2019/06/28 08:18:39 [TRACE] [walkPlan] Exiting eval tree: module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress3
2019/06/28 08:18:39 [TRACE] vertex "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress3": visit complete
2019/06/28 08:18:39 [TRACE] vertex "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress3": dynamic subgraph encountered errors
2019/06/28 08:18:39 [TRACE] vertex "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress3": visit complete
2019/06/28 08:18:39 [TRACE] vertex "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4": evaluating
2019/06/28 08:18:39 [TRACE] [walkPlan] Entering eval tree: module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4
2019/06/28 08:18:39 [TRACE] module.prometheus_backgroundtask.module.security_group_base_rules: eval: *terraform.EvalSequence
2019/06/28 08:18:39 [TRACE] module.prometheus_backgroundtask.module.security_group_base_rules: eval: *terraform.EvalGetProvider
2019/06/28 08:18:39 [TRACE] module.prometheus_backgroundtask.module.security_group_base_rules: eval: *terraform.EvalReadState
2019/06/28 08:18:39 [TRACE] EvalReadState: reading state for module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4
2019/06/28 08:18:39 [TRACE] UpgradeResourceState: schema version of module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4 is still 2; calling provider "aws" for any other minor fixups
2019/06/28 08:18:39 [TRACE] GRPCProvider: UpgradeResourceState
2019/06/28 08:18:39 [ERROR] module.prometheus_backgroundtask.module.security_group_base_rules: eval: *terraform.EvalReadState, err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>
2019/06/28 08:18:39 [ERROR] module.prometheus_backgroundtask.module.security_group_base_rules: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>
2019/06/28 08:18:39 [TRACE] [walkPlan] Exiting eval tree: module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4
2019/06/28 08:18:39 [TRACE] vertex "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4": visit complete
2019/06/28 08:18:39 [TRACE] vertex "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4": dynamic subgraph encountered errors
2019/06/28 08:18:39 [TRACE] vertex "module.prometheus_backgroundtask.module.security_group_base_rules.aws_security_group_rule.ingress4": visit complete
2019/06/28 08:18:39 [TRACE] dag/walk: upstream of "provider.aws (close)" errored, so skipping
2019/06/28 08:18:39 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/06/28 08:18:39 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019/06/28 08:18:39 [INFO] backend/local: plan operation completed`


Here is an example configuration from the terraform module that is referencing:
`data "aws_iam_account_alias" "current" {
}

data "aws_region" "current" {
}

data "aws_security_group" "selected" {
  id = var.security_group_id
}

data "aws_vpc" "selected" {
  id = data.aws_security_group.selected.vpc_id
}

data "terraform_remote_state" "current" {
  backend = "s3"

  # IMPORTANT: THIS ASSUMES THE PATH TO THE TF STATE FILE IN S3 IS CONSISTENT!
  # IF YOU CHANGE THE WAY WE STORE STATE FILES, THIS CODE WILL HAVE TO BE UPDATED AS WELL!
  config = {
    bucket = "${data.aws_iam_account_alias.current.account_alias}-terraformstate-01"
    key    = "${data.aws_iam_account_alias.current.account_alias}/terraform.tfstate"
    region = data.aws_region.current.name
  }

  defaults = {
    openvpn_security_group_id = ""
  }
}

locals {
  icmp_cidr_block = var.public_facing == "false" ? data.aws_vpc.selected.cidr_block : "0.0.0.0/0"
}

# No restriction on egress traffic.  (Revisit this later.)
resource "aws_security_group_rule" "egress1" {
  type              = "egress"
  from_port         = 0
  to_port           = 65535
  protocol          = "all"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = var.security_group_id
  description       = "Base egress rule managed by TF"

  lifecycle {
    create_before_destroy = true
  }
}

# Allow useful/necessary ICMP traffic (www.shouldiblockicmp.com)
# Echo Reply aka Ping
resource "aws_security_group_rule" "ingress1" {
  type      = "ingress"
  from_port = 0 # ICMP Type
  to_port   = 0 # ICMP Code
  protocol  = "icmp"

  cidr_blocks       = [local.icmp_cidr_block]
  security_group_id = var.security_group_id
  description       = "Base ICMP rule managed by TF"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_security_group_rule" "openvpn" {
  count                    = data.terraform_remote_state.current.outputs.openvpn_security_group_id != "" && var.allow_openvpn == "true" ? 1 : 0
  type                     = "ingress"
  from_port                = 0
  to_port                  = 65535
  protocol                 = "all"
  source_security_group_id = data.terraform_remote_state.current.outputs.openvpn_security_group_id
  security_group_id        = var.security_group_id
  description              = "Base OpenVPN rule managed by TF"

  lifecycle {
    create_before_destroy = true
  }
}
` 

And here is a copy of our profiders.tf:
`provider "archive" {
  # Specify a version to stop terraform init from throwing a warning.
  version = "~> 1.2.2"
}

provider "aws" {
  # We need at least version 1.43.2 because we use the newer syntax for VPC flow logs
  # and security group rules.
  version = "~> 2.11.0"

  region = var.aws_region

  # This will guard against running Terraform code in the wrong AWS account, which will have disasterous consequences.
  allowed_account_ids = [var.aws_account_num]
}

provider "null" {
  # Specify a version to stop terraform init from throwing a warning.
  version = "~> 2.1.2"
}

provider "random" {
  # Specify a version to stop terraform init from throwing a warning.
  version = "~> 2.1.2"
}

provider "template" {
  # Specify a version to stop terraform init from throwing a warning.
  version = "~> 2.1.2"
}
`

Thank you for helping me with this issue. If you would like more information or examples, I would be more than happy to upload.

**Comment by jbardin** [comment]
Thanks @J-Hunter-Hawke, I'm not exactly sure what's happening here yet. These log snippets don't contain the information about starting the plugins I would need (it would be great to get the complete log if possible). There's something going wrong in the plugin execution, though they seem to be running long enough to get to the state upgrade step during Plan. Can you try some example configurations and see if you can narrow down the behavior to a single provider and reduced configuration? Does it only happen with your current state, or does the problem persist if you start for an empty state?

**Comment by J-Hunter-Hawke** [comment]
Thanks for getting back to me, @jbardin. I've been working to whittle down our configuration today and found the problem provider to be "aws." After updating, it looks like everything now works. I'm sorry if I wasted your time when there was such a simple solution. Thank you for your help.
