### ISSUE TITLE
Feature Request : Module versioning for S3 source

### ISSUE THREAD

**Issue by davzucky** [hashicorp/terraform#21891]
### Use-case
Versioned Module source has been added in Terraform for some of the sources #15613 as a solution of using interpolation for module source.

I need to have the ability to use a version using S3 backed. The idea is to use a source that looks like that :
"s3::https://s3-ap-southeast-1.amazonaws.com/my_bucket/modules/my_module.${var.my_module_version}.zip"

The ability to use version exist for git, terraform server, but not for GitHub or S3

### Attempted Solutions
I tried a different pattern, however, because we cannot use string interpolation for module source, none of them worked.

The only solution I found is:

- Use module source from the local file system, with static relative path
- Having a script that downloads any module required from S3 locally using the expected version

This is working, that I find is working, however, it involves a pre-script to run which is not managed by terraform.

### Proposal
The proposal would be to use a string pattern when we use the module source of type S3 and have a version. 

``` terraform
module "my_module" {
     source = "s3::https://s3-ap-southeast-1.amazonaws.com/my_bucket/modules/my_module.${var.my_module_version}.zip"
     version = "0.1.0"
}
```
This would fetch https://s3-ap-southeast-1.amazonaws.com/my_bucket/modules/my_module.**0.1.0**.zip

The same idea could be used for local or https source

### References
#15613
#1439

**Comment by rkst** [comment]
@davzucky Hi - we're not currently looking at making sources specific to cloud vendors at this time. We're going to close this out for now but if we get enough interest from the community we can re-evaluate.

**Comment by davzucky** [comment]
@rkst Thank you for your reply. I understand that you don't want to make a source for cloud vendor specific.
What about HTTP ?
