### ISSUE TITLE
terraform 0.11.10 version modules reading terraform remote state from module having v0.12.2

### ISSUE THREAD

**Issue by lauraaraviciute** [hashicorp/terraform#21897]
Hi, 

Probably not a bug just need more clarification on compatibility in terms of reading remote state files between v0.11.10 and 0.12+ . 

We currently have a module A in v0.11.10 where we need to read a terraform_remote_state file from a different module B. We want to upgrade module B to version 0.12.2 but module A has been breaking due to this. We cannot move module A to v0.12.2 yet and don't see a workaround whereby we would not need to read the remote state file yet. 

When trying to read a remote state file from module B, when running terraform plan on module A we get the following error : 

```
data.terraform_remote_state.sns: data.terraform_remote_state.sns: Terraform 0.11.10 does not support state version 4, please update.
``` 

From the documentation, we had assumed that we could have just utilised the **outputs** marker when reading from the remote state file but that gives an error also indicating that it cannot find "outputs.x" from the remote state file. 

Upgrading module A to 0.11.14 has gotten rid of the very first error and seems to be running correctly, although I was still weary on wether we should be using the **outputs** parameter to access the data, but even with v0.11.14, using the outputs parameter breaks as per my last comment - whereby it cannot find it. 

I guess my question is regarding how we move module B to version v0.12.2 without having to move module A and what is the least amount of work that will cover us within module A for this move to take place. 
Is moving module A to v0.11.14 sufficient? Do we also need to use outputs? What are the recommended steps? Or is this error message relating to something different? 

### Steps to Reproduce

1. Module A : Create a module in v0.11.10
2. Module B : Create a different module in v0.12.2 with some outputs
3. Create a terraform_remote_state data block in module A, referencing module B's remote state. 
4. Try to access some output from module B's terraform remote state within module A with outputs parameter and with no output parameter. (ie. "${data.terraform_remote_state.sns.aws_account}" "${data.terraform_remote_state.sns.outputs.aws_account}" 
5. Run terraform init on module A
6. Run terraform plan on module A

**Comment by rkst** [comment]
@lauraaraviciute Hi - you'll likely need to have the module upgraded to 0.12+, just out of interest what are the reasons you can't upgrade Module A to 0.12+, is it a dependency that needs 0.11?

Could you show the outputs from Module B and where you are using them in Module A (the 0.11.14 version) just so we can check there aren't any issues with the config that we can see? Also the error message from 0.11.14 would be really helpful.

**Comment by lauraaraviciute** [comment]
Hi @rkst after further discussions we've decided that we'll upgrade module A to 0.12+ . 
So final question would be regarding module A (v.0.12+) being able to read a state file of version 0.11.10? As we hope to upgrade module A first and then move onto module B, but just hoping there are no breaks in that space of time. 

There are no error messages from v0.11.14 , its just a config we've been playing with that gets rids of the initial: 
```
data.terraform_remote_state.sns: data.terraform_remote_state.sns: Terraform 0.11.10 does not support state version 4, please update.
```
Module A is still on v0.11.10 originally. 

Thanks for the quick response.

**Comment by jbardin** [comment]
Hi @lauraaraviciute,

Yes, if you want to try and use a 0.12 remote state with 0.11, it does require 0.11.14. That is a feature provided on a "best effort" basis, and may not work in all cases, especially if new features of 0.12 are used in the state outputs.

It looks like you have a handle on the upgrade process, and it will certainly be smoother if you can upgrade all the modules, in order.
