### ISSUE TITLE
Documentation missing for using for loops in JSON syntax

### ISSUE THREAD

**Issue by geofffranks** [hashicorp/terraform#21899]
Would it be possible to add documentation to https://www.terraform.io/docs/configuration/syntax-json.html explaining how to use the new for + for-each syntax provided in v0.12?

I'm trying to figure out how to do the equivalent of this:

```
module "my-module" {
  source                  = "../my-module"
  map_roles = [
    for role in local.map_roles:
    {
      role_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${role.role}"
      username = lower(role.role)
      group    = role.group
    }
  ]
}
```

**Comment by rameshjanjyam** [comment]
I am trying to achieve something similar and don't see related details in doc. Is it even possible to do this in json syntax?  I tried several diff ways but no luck

**Comment by apparentlymart** [comment]
Hi @geofffranks! Sorry for the slow response here.

I'm not sure how the JSON syntax documentation looked at the time you opened this, but today it includes a section [Expression Mapping](https://www.terraform.io/docs/configuration/syntax-json.html#expression-mapping) which describes how the JSON decoder understands JSON values in contexts where an expression is expected, which is the case for module arguments like your `map_roles`.

Writing complicated expressions like the one you showed in JSON is possible but not very elegant. Typically we recommend using JSON only for simple configurations generated automatically by software, but if you have a strong reason to write this in JSON then you can translate it using the interpolation syntax described in the documentation:

```json
{
  "map_roles": "${ [ for role in local.map_roles : { role_arn = \"arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${role.role}\", username = lower(role.role), group = role.group } ] }"
}
```
