### ISSUE TITLE
terraform plan is throwing error "Error: Unsupported block type" for tags and vars attributes with terraform 0.12.3 version

### ISSUE THREAD

**Issue by surajmuthreja** [hashicorp/terraform#21912]
### Terraform Version
Terraform v0.12.3

### Terraform Configuration Files

# Create a resource group in each region
resource "azurerm_resource_group" "versa_rg" {
    count    = "${length(var.location)}"
	name     = "${var.resource_group}-${1+count.index}"
    location = "${element(var.location, count.index)}"

    tags {
        environment = "TestRG"
    }
}

data "template_file" "user_data_test" {
  template = "${file("test.sh")}"
  
  vars {
	sshkey = "${var.ssh_key}"
  }
}

### Expected Behavior

These template files are working fine on Terraform v0.11.8. 
It should work seamlessly on latest version also.

### Actual Behavior

These template files are working fine on Terraform version v0.11.8.
When trying on v0.12.3, it is throwing error. Looks like parameters syntax changed.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

**Comment by rkst** [comment]
@surajmuthreja Hi - this is one for running through the upgrade tool again with `terraform 0.12upgrade`.
