### ISSUE TITLE
Provider "aws" v1.60.0 is not compatible with Terraform 0.12.3.

### ISSUE THREAD

**Issue by keanesf** [hashicorp/terraform#21927]
Provider "aws" v1.60.0 is not compatible with Terraform 0.12.3.

Provider version 2.7.0 is the earliest compatible version. Select it with 
the following version constraint:

	version = "~> 2.7"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.24

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.

Error: incompatible provider version

**Comment by ajayk** [comment]
@keanesf  you need to update the aws provider to minimum 2.7 to use with tf 0.12.3  , You can close the issue as this is a expected 
https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html

**Comment by phinze** [comment]
Thanks for answering @ajayk! That is indeed the correct answer - upgrading the AWS provider will allow it to be used with 0.12.x.
