### ISSUE TITLE
Inconsistent state locking messages

### ISSUE THREAD

**Issue by stealthllama** [hashicorp/terraform#21928]
### Terraform Version

```
Terraform v0.11.13
```

### Expected Behavior

"`Acquiring state lock. This may take a few moments...`"  and "`Releasing state lock. This may take a few moments...`" strings should be displayed consistently on `terraform` command output to indicate that state locking is working as expected when utilizing supported remote backends.

### Actual Behavior

***S3 backend:***  Works as expected.  Both messages are displayed.

***AzureRM backend:*** Only the "`Acquiring...`" message is displayed.

***GCS backend:*** Neither message is displayed.

### Steps to Reproduce

Configure a remote backend and reference it in a plan.  Run a `terraform plan`, `terraform apply`, or `terraform destroy` command.

**Comment by pkolyvas** [comment]
It looks like the backend locking messages are now unified here: https://github.com/hashicorp/terraform/blob/master/command/clistate/state.go

I'm going to close this one out. If it's in error, please re-open.
