### ISSUE TITLE
Freeform string names failing in blocks when using 0.12.x

### ISSUE THREAD

**Issue by u2mejc** [hashicorp/terraform#21920]
### Terraform Version

```
Terraform v0.12.3
+ provider.aws v2.15.0
```

### Terraform Configuration Files

```hcl
resource "aws_vpc" "test_vpc" {
  cidr_block = "10.0.0.0/16"

  tags {
    Name                                       = "test_vpc"
    kubernetes.io/cluster/test-vpc.example.com = "shared"
  }
}
```

### Expected Behavior

This works in 0.11.14, and also excepts quotes. I would expect this to work in 0.12.3 and except any valid string that the provider accepts.

### Actual Behavior

Terraform 0.11.x: works as expected
Terraform 0.12.3:
```
# terraform validate

Error: Argument or block definition required

  on vpc.tf line 70, in resource "aws_vpc" "test_vpc":
  70:     kubernetes.io/cluster/test-vpc.example.com = "shared"

An argument or block definition is required here. To set an argument, use the
equals sign "=" to introduce the argument value.

# terraform validate

Error: Invalid argument name

  on vpc.tf line 70, in resource "aws_vpc" "test_vpc":
  70:     "kubernetes.io/cluster/test-vpc.example.com" = "shared"

Argument names must not be quoted.
```
### Steps to Reproduce

1. `terraform apply`

**Comment by jbardin** [comment]
Hi @u2mejc,

The first error is the one you needs to be concerned with, the second is caused by the first.
```
An argument or block definition is required here. To set an argument, use the
equals sign "=" to introduce the argument value.
```

Tags is a map, so you need to use `tags = {`

**Comment by u2mejc** [comment]
@jbardin You've closed this prematurely, can you please reopen. Can you please reopen, observe that I was demonstrated to failure cases.

**Comment by jbardin** [comment]
@u2mejc, Quoted keys are only valid for maps, and once you change the configuration for  `tags` to a map, you will be able to quote the key to prevent the ambiguity with a reference. The configuration should look like:

```
resource "aws_vpc" "test_vpc" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name                                       = "test_vpc"
    "kubernetes.io/cluster/test-vpc.example.com" = "shared"
  }
}
```

**Comment by u2mejc** [comment]
Thank you for clarifying! 👍
