### ISSUE TITLE
Bitbucket source broken 

### ISSUE THREAD

**Issue by mackoftrack** [hashicorp/terraform#21938]
All of a sudden today my modules that live in Bitbucket repos broke. I'm 99.9% sure that it's due to the removal of their 1.0 apis: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/ 

https://api.bitbucket.org/1.0/repositories/ returns:
 
```javascript
{
  "type": "error",
  "error": {
    "message": "Resource removed",
    "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the 
      deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"
  }
}
```

Terraform is trying to hit that API here:

https://github.com/hashicorp/terraform/blob/805ae28876c3fe047cd0d6ad4f478c21d55802dd/vendor/github.com/hashicorp/go-getter/detect_bitbucket.go#L38

This is a **major** problem as I can't apply anything. I've tried switching to the generic git source syntax and that does not work either.
### Terraform Version
```
Terraform v0.11.13
```
 
### Terraform Configuration Files

```hcl
module "foo" {
  source = "bitbucket.org/example/my-repo-name"
  ...
}
```

### Debug Output

```
Error downloading modules: Error loading modules: module foo: unknown BitBucket SCM type:
```

### Expected Behavior

Module gets initialized per https://www.terraform.io/docs/modules/sources.html#bitbucket
### Actual Behavior

Module initialization fails. 
### Steps to Reproduce

1. `terraform init` 
### Additional Context

Today is the first time I've hit this issue however. This should be an easy fix, as the 2.0 API repository API is unchanged from what I can tell. So the endpoint just needs to be updated. I'd file a PR, but I'm at work and don't really have time at the moment.

**Comment by phinze** [comment]
Hi @mackoftrack - thanks for the report - it does look on first glance like it's tripping over that deprecation. We'll dig into this and follow up.

**Comment by bflad** [comment]
I believe this has been fixed upstream in go-getter (https://github.com/hashicorp/go-getter/pull/189), but a release of that library has not been cut yet.

**Comment by mackoftrack** [comment]
Suggestions for a workaround? It seems that when I switch to the generic git syntax it does in fact clone the module into .terraform/ but terraform is still throwing an error, preventing me from plan and apply

**Comment by mackoftrack** [comment]
Sorry to bump this, but I'm just wondering what I can do to work around this until the next release happens.

**Comment by phinze** [comment]
Hi @mackoftrack - we expect to be cutting a release in the next week or so, but in the meantime you're welcome to build from the master branch by [following these instructions](https://github.com/hashicorp/terraform#developing-terraform).
