### ISSUE TITLE
aws_api_gateway_domain_name: add support for securityPolicy to configure TLS protocol version

### ISSUE THREAD

**Issue by ra-hardy** [hashicorp/terraform#21944]
On June 20, AWS added support for configuring the minimum TLS version associated with a custom domain - https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-api-gateway-adds-configurable-transport-layer-security-version-custom-domains/

domainname:create has a securityPolicy field to specify this - https://docs.aws.amazon.com/apigateway/api-reference/link-relation/domainname-create/

domainname:update has a securityPolicy field to change it - https://docs.aws.amazon.com/apigateway/api-reference/link-relation/domainname-update/

Could this be added to aws_api_gateway_domain_name ?

**Comment by egee-irl** [comment]
Also interested in this :+1:
