### ISSUE TITLE
Terraform keeps asking to add and remove instances in ELB

### ISSUE THREAD

**Issue by avasant21** [hashicorp/terraform#21952]
Terraform will perform the following actions:

```
  ~ aws_elb.wmic-elb-external
      instances.#:          "2" => "1"
      instances.1719252275: "i-02847e8265cd6e434" => ""
      instances.1941172443: "i-007c8954c0046ffcc" => "i-007c8954c0046ffcc"

  ~ aws_elb.wmic-elb-internal
      instances.#:          "2" => "1"
      instances.1673228886: "i-05e501af81c30714e" => ""
      instances.3467839941: "i-055f670ab3fd9c933" => "i-055f670ab3fd9c933"
```

When I applied and executing a plan it not wanting to add in them. If I again run, it is wanting to remove them. Happening for the same instances(i-02847e8265cd6e434 & i-05e501af81c30714e) in both the ELBs. 

After Apply

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_elb_attachment.wmic-elb-attach-engx-2
      id:                 <computed>
      elb:                "wmic-rnd-elb-external-56-sec"
      instance:           "i-02847e8265cd6e434"

  + aws_elb_attachment.wmic-elb-attach-ingx-2
      id:                 <computed>
      elb:                "wmic-rnd-elb-internal-56-sec"
      instance:           "i-05e501af81c30714e"
```

**Comment by phinze** [comment]
Hi @avasant21 - can you share the Terraform configuration that is giving you this behavior?

Based on the error messages you showed it looks like you might have two different resources "fighting" over the list of instances in the ELB.

That is most likely happening because you're specifying the `instances` parameter on your `aws_elb` resource and also specifying and `aws_elb_attachment` resource. See the ["Note" on top of the aws_elb docs page](https://www.terraform.io/docs/providers/aws/r/elb.html) for details on why that combo won't work.

**Comment by avasant21** [comment]
HI @phinze - Thanks for your help here.

The tf files had multiple attach actions and I had to verify and remove them. Now it is perfect and stable.
Below is the graphical view of the same. Collected it before the correction

[admin@terraform]$ sudo /opt/terraform_0.11.7/terraform graph | grep aws_elb
                "[root] aws_elb.wmic-elb-external" [label = "aws_elb.wmic-elb-external", shape = "box"]
                "[root] aws_elb.wmic-elb-internal" [label = "aws_elb.wmic-elb-internal", shape = "box"]
                "[root] aws_elb_attachment.wmic-elb-attach-engx-1" [label = "aws_elb_attachment.wmic-elb-attach-engx-1", shape = "box"]
                "[root] aws_elb_attachment.wmic-elb-attach-engx-2" [label = "aws_elb_attachment.wmic-elb-attach-engx-2", shape = "box"]
                "[root] aws_elb_attachment.wmic-elb-attach-ingx-1" [label = "aws_elb_attachment.wmic-elb-attach-ingx-1", shape = "box"]
                "[root] aws_elb_attachment.wmic-elb-attach-ingx-2" [label = "aws_elb_attachment.wmic-elb-attach-ingx-2", shape = "box"]
                "[root] data.aws_elb_service_account.elb-service-account" [label = "data.aws_elb_service_account.elb-service-account", shape = "box"]
                "[root] aws_elb.wmic-elb-external" -> "[root] aws_instance.wmic-ec2-engx-1"
                "[root] aws_elb.wmic-elb-external" -> "[root] aws_s3_bucket_policy.wmic-allow-elb-service-account"
                "[root] aws_elb.wmic-elb-external" -> "[root] data.aws_security_group.wmic-sg-elb-external"
                "[root] aws_elb.wmic-elb-external" -> "[root] data.aws_subnet.wmic-sub-public-B"
                "[root] aws_elb.wmic-elb-internal" -> "[root] aws_instance.wmic-ec2-ingx-1"
                "[root] aws_elb.wmic-elb-internal" -> "[root] aws_s3_bucket_policy.wmic-allow-elb-service-account"
                "[root] aws_elb.wmic-elb-internal" -> "[root] data.aws_security_group.wmic-sg-elb-internal"
                "[root] aws_elb.wmic-elb-internal" -> "[root] data.aws_subnet.wmic-sub-public-B"
                "[root] aws_elb_attachment.wmic-elb-attach-engx-1" -> "[root] aws_elb.wmic-elb-external"
                "[root] aws_elb_attachment.wmic-elb-attach-engx-2" -> "[root] aws_elb.wmic-elb-external"
                "[root] aws_elb_attachment.wmic-elb-attach-engx-2" -> "[root] aws_instance.wmic-ec2-engx-2"
                "[root] aws_elb_attachment.wmic-elb-attach-ingx-1" -> "[root] aws_elb.wmic-elb-internal"
                "[root] aws_elb_attachment.wmic-elb-attach-ingx-2" -> "[root] aws_elb.wmic-elb-internal"
                "[root] aws_elb_attachment.wmic-elb-attach-ingx-2" -> "[root] aws_instance.wmic-ec2-ingx-2"
                "[root] aws_lb_ssl_negotiation_policy.wmic-elb-external-cipher" -> "[root] aws_elb.wmic-elb-external"
                "[root] aws_route53_record.wmic-r53-record-ec2-elb" -> "[root] aws_elb.wmic-elb-external"
                "[root] aws_route53_record.wmic-r53-record-ec2-ilb" -> "[root] aws_elb.wmic-elb-internal"
                "[root] data.aws_elb_service_account.elb-service-account" -> "[root] provider.aws"
                "[root] data.aws_iam_policy_document.s3-common-log-bucket-policy" -> "[root] data.aws_elb_service_account.elb-service-account"
                "[root] meta.count-boundary (count boundary fixup)" -> "[root] aws_elb_attachment.wmic-elb-attach-engx-1"
                "[root] meta.count-boundary (count boundary fixup)" -> "[root] aws_elb_attachment.wmic-elb-attach-engx-2"
                "[root] meta.count-boundary (count boundary fixup)" -> "[root] aws_elb_attachment.wmic-elb-attach-ingx-1"
                "[root] meta.count-boundary (count boundary fixup)" -> "[root] aws_elb_attachment.wmic-elb-attach-ingx-2"
                "[root] provider.aws (close)" -> "[root] aws_elb_attachment.wmic-elb-attach-engx-1"
                "[root] provider.aws (close)" -> "[root] aws_elb_attachment.wmic-elb-attach-engx-2"
                "[root] provider.aws (close)" -> "[root] aws_elb_attachment.wmic-elb-attach-ingx-1"
                "[root] provider.aws (close)" -> "[root] aws_elb_attachment.wmic-elb-attach-ingx-2"
