### ISSUE TITLE
Different proxy for different resources types.

### ISSUE THREAD

**Issue by udayanverma** [hashicorp/terraform#21951]
Hi there,

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

In many scenarios we use multiple proxies.  Specific to AWS, Azure, other CSPs and rest of the word (i.e. On Prem). Fixing single proxy at HTTP(S)_PROXY bounds us to use only one of the proxy at a time. There scenarios where there is a need to route traffic thru different proxies. How to allow specific resource type to utilize a specific proxy.  To give a simple example we use one specific proxy for using AWS but we whitelist the S3 buckets belonging to Corp. For automation of S3 bucket creation a different proxy is configured. Now we want to use specific Proxy for S3 but allow rest to use different proxy.  Pl let me know if you need more information around this. Endpoint has not been helpful as there is no route for endpoint could be configured as the automation runs from the onprem behind the firewall and proxy.

Regards
udayan

**Comment by pkolyvas** [comment]
I'm doing a clean-up of older issues that haven't gained traction but also don't coincide with some of our current focus. Between the age of the issue and the activity on it, don't think we have enough data to back keeping this issue open. Multiple proxies does sound like an interesting problem, but not one Terraform is designed for at the moment. That's unlikely to change in the near future within Core. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform, the use cases, and needs of our practitioners.
