### ISSUE TITLE
Terraform 12 map with different output types breaks terraform 11

### ISSUE THREAD

**Issue by ImDevinC** [hashicorp/terraform#21969]
### Terraform Version

```
terraform -v
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 0.12.3. You can update by downloading from www.terraform.io/downloads.html
```
```
terraform -v
Terraform v0.12.3
```

### Terraform Configuration Files

*Terraform 12 Config*
```hcl
output "var" {
  value = {
    test_one = "7"
    test_two = 7
  }
}

terraform {
  required_version = ">= 0.12"
}
```
*Terraform 11 Config*
```hcl
terraform {
  required_verion = "=0.11.14"
}

data "terraform_remote_state" "test_project" {
  backend = "local"
  config = {
    path = "../terraform.tfstate"
  }
}

output "var" {
  value = "${data.terraform_remote_state.test_project.var["test_two"]}"
}
```

### Debug Output

https://gist.github.com/ImDevinC/13520a727f93823f2d4a2c96a4209f5d
### Crash Output

https://gist.github.com/ImDevinC/080a674b168fbdba4d01896dd8b69264
### Expected Behavior

State should be read properly, or if this is not supported, terraform 12 should not allow the state to be written in this manner.
### Actual Behavior

Terraform crashes
### Steps to Reproduce
1. Setup terraform 12 state
1. `terraform init`
1. `terraform apply`
1. Create subdirectory and setup terraform 11 state
1. Switch to terraform 11
1. `terraform init`
1. `terraform apply`

**Comment by mildwonkey** [comment]
Hi @ImDevinC ! I'm sorry you've experienced this crash.

Terraform 0.12 has many features that 0.11 is not able to parse, and terraform 0.11 is not expected to be able to read 0.12 statefiles that take advantage of those features, such as your example here. The panic is very unfortunate, but as we are not planning any more 0.11 releases, we won't be fixing it and I am going to close this issue.
Thank you, and I am sorry for the unsatisfying response.
