### ISSUE TITLE
Oracle OCI lifecycle ignore_changes db_home db_version

### ISSUE THREAD

**Issue by matthewdw** [hashicorp/terraform#21972]
# Versions

Terraform v0.12.3
provider.oci v3.31.0

# Summary

I don't think this is provider specific, so posting here.

When creating an `oci_database_db_system` you initialise it with `db_version = "18.0.0.0"` but the output (and state) records it with the exact version (`18.6.0.0.190416` in my case).  Therefore upon the next `terraform apply` I am prompted to destroy and create the object.

I am attempting to use *lifecycle > ignore* changes but due to the nested objects I cannot find a working method to do this in v0.12.3.  #21433 seems related.  [#767](https://github.com/terraform-providers/terraform-provider-oci/issues/767) seems to provide a working solution for v0.11.13 but this errors with *Dot must be followed by attribute name* in v0.12.

# TF

Here is the configuration without the lifecycle code.

```
resource "oci_database_db_system" "testdb" {
    
    #Required
    availability_domain = "sxPz:UK-LONDON-1-AD-1"
    compartment_id = var.compartment_id    
	database_edition = "ENTERPRISE_EDITION"
    db_home {
        #Required
        database {
            #Required
            admin_password = "uGgtGy#hejQdj4#2"
            
            db_name = "testdb"
            db_workload = "OLTP"
            pdb_name = "testpdb"
        }

        #Optional
		db_version = "18.0.0.0"	
    }
		
    hostname = "testdb"
    shape = "VM.Standard2.1"
	ssh_public_keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQBkpsEOnXIvOcjOjLr4ANRDETurkL5gvqjCW+JGlexif917HYHiwkewXzZi1D6Ic2ihnNJ7GSrdLA1D84hpN5er1eSgEO+XF+zepapoQxQv/WGF+o0RvjOH7Rw0248+fMRTn2MwqUw3DJvWfB/k2bbO3jBWTDUw1l7hHGd4HYaQ+9uN85Jr0XIQUuB7ty0OdVRG1kXfzcYWpi0008R5U8uLn5tg5DxuhvXJ8W72MMEKeKhmp0V3/WpCXMpHXT/VpyJoZl59f09oRwyGh5mvUIELKQwydkaoeiFpdmrB9Si1E4YqgsLkmp3qehFMwvgedIi8CIRB/wIczX4RiQehTOZd"]
    subnet_id = oci_core_subnet.Public_Subnet_sxPz_UK-LONDON-1-AD-1.id
       
    data_storage_size_in_gb = "256"
	license_model = "BRING_YOUR_OWN_LICENSE"    
    node_count = "1"
}
```

This lifecycle block worked in v0.11.13 per [#767](https://github.com/terraform-providers/terraform-provider-oci/issues/767).
```
  lifecycle {
    ignore_changes  = ["db_home.0.db_version",]
  }
```

This lifecycle works in v0.12.3 but would also ignore attributes that I don't specifically want to ignore.

```
 lifecycle {
    ignore_changes = [        
      db_home,
    ]
  }
```

**Comment by phinze** [comment]
Hi @matthewdw - I think this should ignore the field you want:

```tf
  lifecycle {
    ignore_changes = [        
      db_home[db_version],
    ]
  }
```

Let us know if this works for you!

**Comment by matthewdw** [comment]
Thank you for the suggestion but that results in the following error.

```
Error: Invalid expression

  on db.tf line 33, in resource "oci_database_db_system" "testdb":
  33:       db_home[db_version],

A single static variable reference is required: only attribute access and
indexing with constant keys. No calculations, function calls, template
expressions, etc are allowed here.
```

And putting `"db_version"` in quotes results in it wanting to destroy/create.

**Comment by jbardin** [comment]
Hi @matthewdw,

Thanks for filing the issue! The expected syntax should be

    ignore_changes = [db_home[0].db_version].

I've confirmed this can still fail in some cases, where the path returned by the plugin can appear to match but still evaluates as unequal. There's not really any workaround at the moment, but we should have a fix in an upcoming release.

You should not need `ignore_changes` in this situation however, as the provider should not be attempting to alter the configuration value stored in the state. That isn't something we can fix in terraform and should be reported as a bug in the provider.

**Comment by matthewdw** [comment]
> Hi @matthewdw,
> 
> Thanks for filing the issue! The expected syntax should be
> 
> ```
> ignore_changes = [db_home[0].db_version]
> ```
> 
Hi @jbardin,

Thanks, just tried your suggested syntax -

```
lifecycle {
      ignore_changes = [db_home[0].db_version]
    }
```
It does not generate an error but it just ignores the ignore request and tries to destroy/create the db_system object still.

I've reported the issue to the provider under terraform-providers/terraform-provider-oci#814.  I think there are two issues here.  One is that I still can't seem to find any working syntax to ignore the db_version change (I think this is a Terraform issue) and the second is that the provider is changing the db_version (this is a provider issue).

**Comment by jbardin** [comment]
@matthewdw,

As mentioned above, the indexed address `db_home[0].db_version` can still fail for `depends_on`, and should be fixed in an upcoming release. The syntax is correct, but there is an error in the address handling.
