### ISSUE TITLE
list of maps for multiple json files defined in the template_file

### ISSUE THREAD

**Issue by mansinga1** [hashicorp/terraform#21980]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)
* [Azure](https://github.com/terraform-providers/terraform-provider-azurerm)
* [Google](https://github.com/terraform-providers/terraform-provider-google)
* [Oracle](https://github.com/terraform-providers/terraform-provider-oci)
* [Kubernetes](https://github.com/terraform-providers/terraform-provider-kubernetes)

See the [terraform-providers](https://github.com/terraform-providers) GitHub organization for many others.

**Comment by phinze** [comment]
Hi @mansinga1, Given that the content of this issue looks like a snippet of our new issue template, it looks like perhaps you didn't finish writing your issue before submitting. I'm going to close this for now and if you'd like follow up with more information we can reopen.
