### ISSUE TITLE
Misleading error message - diffs not equal

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#2199]
Got the following error message when creating a new aws_instance.  The problem turned out to be an incorrect security group id (blank) and not a bug in terraform.  I've gotten bitten by this a couple of times and I think it may be good to offer a different message.

```
* aws_instance ... diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

maybe something like:

```
Diffs didn't match during apply. This can happen if there's a empty security group id, or other empty value where one is expected. Or, this could be a bug in Terraform.
```

or maybe showing what values differ, would be very helpful.

**Comment by phinze** [comment]
Hi @franklinwise - thanks for the report.

> The problem turned out to be an incorrect security group id (blank) and not a bug in terraform.

The "diffs didn't match" error is a safety check that occurs relatively late in processing. It's our goal to improve error reporting to the point that an end user of Terraform never has to see that message. So in your case - the blank security group ID should have generated a specific error pointing you to the problem long before the "diffs didn't match" triggers.

Can you show me some config that demonstrates the empty security_group_id problem and we can get that scenario taken care of?

**Comment by mitchellh** [comment]
Closing due to lack of response, but please do respond if you come around to it.
