### ISSUE TITLE
`aws_s3_bucket_object` should accept http url as the source

### ISSUE THREAD

**Issue by ppatel03** [hashicorp/terraform#21990]
I have following terraform code set up to upload to s3 from http url

`
resource "aws_s3_bucket_object" "code_upload_to_s3" {
  bucket = "hulu-ads-${var.aws_region}-${var.aws_environment}-release-lambda"
  key = "my-service-0.0.0-SNAPSHOT.jar"
  source = "https://gofile.io/something.jar"
  etag   = "${base64sha256(file(https://gofile.io/something.jar"))}"
}
`

It works if I have pointed my source to a local directory but fails when I point to an http endpoint.
Please let me know

**Comment by mildwonkey** [comment]
Hi @ppatel03,
According to the [`aws_s3_bucket_object`](https://www.terraform.io/docs/providers/aws/r/s3_bucket_object.html#source) documentation, the `source` attribute only works with a path to a file. 
I will label this issue as an enhancement and move it to the `terraform-provider-aws` repository
