### ISSUE TITLE
kubernetes_service not supported in 0.12

### ISSUE THREAD

**Issue by k7faq** [hashicorp/terraform#22013]
Why the change in code to prevent this working package from executing? Why do the docs on terraform.io site not function? How much harder can we  make this for people to learn?

### Version info

```
    Terraform v0.12.3
    + provider.kubernetes v1.8.0
```

### Debug Output

```
Error: Unsupported block type

  on main.tf line 28, in resource "kubernetes_service" "nginx":
  28:     selector {

Blocks of type "selector" are not expected here. Did you mean to define
argument "selector"? If so, use the equals sign to assign it a value.
```

### Expected Behavior

Terraform Plan would have succeeded and included a section similar to:

```
<snip>
  + kubernetes_service.nginx
      id:                                          <computed>
      load_balancer_ingress.#:                     <computed>
      metadata.#:                                  "1"
      metadata.0.generation:                       <computed>
      metadata.0.name:                             "nginx-example"
<snip>
```

### Actual Behavior

Terraform reported an error, see above.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Terraform 0.11.13 using the same steps, `terraform init` followed by `terraform plan` succeeds with no errors.

### References

https://www.terraform.io/docs/providers/kubernetes/guides/getting-started.html

**Comment by llomgui** [comment]
Hey,

Try `selector = {}`

Documentation is not updated yet. Feel free to open a pull request.
