### ISSUE TITLE
aws_launch_configuration root_device 0.12

### ISSUE THREAD

**Issue by bacon-spec** [hashicorp/terraform#22016]
### Terraform Version

```
0.12.3
```

### Terraform Configuration Files

terraform init and terraform plan seem to have different behaviour for the following

```
resource "aws_launch_configuration" "default" {
  name_prefix          = "im-${var.env}-${var.name}-"
  image_id             = var.ami
  instance_type        = var.instance_type
  key_name             = var.openssh_key
  security_groups      = ["${module.sg.sg_id}"]
  ebs_optimized        = var.instance_ebs_opt
  iam_instance_profile = module.iam_instance_role.id
  root_block_device {
    var.root_disk
  }

  lifecycle {
    create_before_destroy = true
  }
}
```
the above code works with a terraform plan but terraform init expects the root device to be 

```
root_block_device = var.root_disk
```

### Expected Behavior
plan and init to act the same

### Actual Behavior
init and plan expect different config

**Comment by jbardin** [comment]
Hi @bacon-spec,

Neither of those forms look correct, and I suspect that what you're seeing is just that `init` only parses enough of the configuration to determine what modules and providers are needed, so the invalid assignment is ignored. 

You haven't shown what `var.root_disk` is, but if it's something containing the parameters for `root_block_device`, you will need to assign those individually within the block.
