### ISSUE TITLE
[docs?] SSH fails to use gpg-agent, `ssh_agent = true` and `host` must be specified

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#22030]
### Terraform Version

```
Terraform v0.12.4-dev
```

### Terraform Configuration Files

Something that'll use SSH to connect with private key on an OpenPGP card, or a configuration that otherwise uses gpg-agent.

```hcl
provisioner "remote-exec" {
}
```

### Expected Behavior
Connects.

### Actual Behavior
```
- timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

### Steps to Reproduce
1. Use `gpg-agent` with `enable-ssh-support`
2. Attempt to use an SSH-using provisioner

### ~Workaround / non- (to me) obvious solution~

This appeared at first to work:

```hcl
connection {
  agent = false
  host = self.whatever_provider_calls_it # (but is required to be specified)
}
```

in that the error went away and I had only a different error; but having solved the other, it's back now, though with `attempted methods [none]` - i.e. no `publickey` . So I'm not sure if it was a coincidence entirely, or if this only intermittently works around it, or what. Not 100% though. (Still fiddling..)

**Comment by OJFord** [comment]
Okay:
```hcl
connection {
  agent = true
  host = self.ip
}
```

_does_ work. Which seems sort of obvious now (certainly makes much more sense than `agent = false`) - but I'm not sure why it needed to be explicit.

Docs say:

> [`agent`](https://www.terraform.io/docs/provisioners/connection.html#agent) - Set to false to disable [...]

which to me implies it'll be tried by default. Perhaps this is just a docs error, and it should be clearer that it needs to be enabled if not using provider defaults?

**Comment by jbardin** [comment]
Hi @OJFord,

Sorry about the confusion here. The `host` attribute is required for any provisioner to connect remotely, noted in the upgrade guide here: https://www.terraform.io/upgrade-guides/0-12.html#default-settings-in-connection-blocks

If you forgot the connection block however, it is not detected and validated. We're tracking that issue here: #21690

**Comment by OJFord** [comment]
Thanks @jbardin - should `agent` be defaulting to `true` though?

i.e. should
```hcl
connection {
  host = self.ip
}
```

work?

If not, I'd suggest that the docs could be clearer:
> `host` must be specified. One of `agent`[, ...] must be specified as `true`, or configured as appropriate.

```hcl
type = "agent"
```
would make that clearer, but I suppose that ship's sailed!

**Comment by jbardin** [comment]
Yes, `agent` should default to `true`. The problem with your config wasn't the agent, it was the missing `host` value.  The minimum required `connection` block is

```
connection {
  host = self.ip
}
```
