### ISSUE TITLE
atlas_artifact includes region when referencing it via id attribute

### ISSUE THREAD

**Issue by gposton** [hashicorp/terraform#2203]
I updated packer to push the ami via a post processor...

    "post-processors": [
      {
        "type"          : "atlas",
        "token"         : "{{user `atlas_token`}}",
        "artifact"      : "{{user `atlas_user`}}/esm-web",
        "artifact_type" : "aws.ami",
        "metadata" : {
          "created_at" : "{{timestamp}}"
        }
      }
    ]

...but when I reference the artifact in terraform, it gives me the region too (not just the ami_id).

    * Error creating launch configuration: ValidationError: AMI us-west-2:ami-cdd3edfd is invalid: Invalid id: "us-west-2:ami-cdd3edfd" (expecting "ami-...")
	status code: 400, request id: [6f50fd13-098f-11e5-be14-1d9251b689a8]

Here's my relevant terraform code

    variable "build" {
      description = "The build number of the atlas artifact (AMI) to deploy"
      default     = "latest"
    }

    resource "atlas_artifact" "ami" {
      name  = "${var.atlas_username}/esm-web"
      type  = "aws.ami"
      build = "${var.build}"
    }

    resource "aws_launch_configuration" "launch_config" {
      image_id      = "${atlas_artifact.ami.id}"
      instance_type = "${var.instance_size}"
      key_name      = "ClearCareWyoming"
      iam_instance_profile = "${aws_iam_instance_profile.profile.id}"
      security_groups    = ["${aws_security_group.esm-web.id}"]
      lifecycle {
        create_before_destroy = true
      }
    }

I got around this by updating terraform with the following snippet to parse out just the ami id

    image_id      = "${element(split(\":\", atlas_artifact.ami.id), 1)}"

There's a workaround here, so I wouldn't mark this as critical, but definitely not ideal.

**Comment by gposton** [comment]
I uploaded a new artifact via packer and am now getting the following error:

    Error refreshing state: 1 error(s) occurred:

    * 1 error(s) occurred:

    * Got 2 results for 'glennposton/esm-web', only one is allowed

As you can see, atlas_artifact.ami.build == 'latest'.  Not sure what I'm doing wrong here.

**Comment by phinze** [comment]
@gposton the `id` field in this case is prefixed so that terraform can properly store it in the state.

The plain AMI ID is actually stored under `metadata_full`, so a proper reference would look like this:

```
resource "aws_launch_configuration" "launch_config" {
  image_id = "${atlas_artifact.ami.metadata_full.region-us-west-2}"
  // ...
}
```

Seems like the TF docs could use an update here to make this clearer. Leaving this open for us to handle that.

In the meantime you can check out https://github.com/hashicorp/atlas-examples for a bunch of working config that interacts with Atlas.

**Comment by phinze** [comment]
@gposton on your second question - can you email support? We'll help you get that sorted out.

**Comment by phinze** [comment]
( @gposton I believe you've been in conversation with HashiCorp support now, so I'm going to close this issue - feel free to follow up if you believe it should be reopened )

**Comment by d4v3y0rk** [comment]
why was this closed before the documentation was updated?
>Leaving this open for us to handle that.
