### ISSUE TITLE
Heredocs cannot be used in arrays

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#22031]
### Terraform Version

```
Terraform v0.12.4-dev
```

### Terraform Configuration Files

```hcl
    inline = [<<END_OF_LONG_CMD
      # ...
END_OF_LONG_CMD
    ]
```

(It's not significant that `<<` is on the same line as array open, happens on separate too.)

### Expected Behavior
```hcl
    inline = ["      # ..."]
```

### Actual Behavior

> Error: Invalid template interpolation value: Cannot include the given value in a string template: string required.

### Steps to Reproduce
1. Use heredoc in an array

### References
It appears to have been valid syntax in previous versions: #10947

**Comment by apparentlymart** [comment]
Hi @OJFord! Thanks for reporting this.

The error message here doesn't really match with the problem as reported. That could very well just be a bug in the error reporting, but just to make sure: in your _real_ configuration that this was based on, do you have any `${ ... }` sequences inside that heredoc that might be returning something other than a string? That's the usual cause of that particular error message.

**Comment by OJFord** [comment]
@apparentlymart  Agh! Yes. Sorry; thanks. One of the times a `${data.local_file.file.content}` appeared it was missing the `.content`.

I often do that; still took me ages to spot 🤦‍♂. Many thanks.

**Comment by apparentlymart** [comment]
Thanks for following up, @OJFord!

Did the full error message give enough context to identify what part of the source code the problem belonged to? I know we still have some cases where the error messages don't include the part of the output where it lists out the types of each value referenced in the expression... was this one of those cases?

(If it were working as expected, it should've pointed out just beneath the source code snippet that `data.local_file.file` is an object.)

**Comment by OJFord** [comment]
@apparentlymart No, there wasn't a source code snippet at all.

Just a list of (two at first, then just this one when I thought I'd fixed the other, but it came back) errors:
```
- Error: ...
```
