### ISSUE TITLE
Error: Provider produced inconsistent final plan in 0.12.3

### ISSUE THREAD

**Issue by plar** [hashicorp/terraform#22048]
### Terraform Version

```
$ terraform version
Terraform v0.12.3
+ provider.aws v2.19.0
+ provider.template v2.1.2
```
### Debug Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_lb.nlb to include new values learned so far
during apply, provider "aws" produced an invalid new value for
.subnet_mapping: block set length changed from 1 to 2.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.*
```

### Expected Behavior

`aws_lb.nlb` resource should be created with list of `subnet_mapping` during first time `terraform apply` itself.

### Actual Behavior

`aws_lb.nlb` resource is getting created with list of `subnet_mapping` during second time `terraform apply` only and getting error output (shared in debug output) during first time apply.

### Steps to Reproduce

You can find a simple project to reproduce this bug here https://github.com/plar/terraform_dynamic_bug

### References

- Provider produced inconsistent final plan while dynamic block generation #21157

**Comment by illwiz** [comment]
I experience this bug using the latest version:
```
Terraform v0.12.5
+ provider.aws v2.19.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```
```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_autoscaling_group.api_asg to include new
values learned so far during apply, provider "aws" produced an invalid new
value for .availability_zones: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Doesn't happen on the second run, only the first time i setup my aws infrastructure

**Comment by teamterraform** [comment]
Hi @illwiz , I'm sorry you're experiencing an issue.

The error you supplied (and the resource in question) are both different from the ones in this issue. Please open a new issue in the [provider's issue tracker](https://github.com/terraform-providers/terraform-provider-aws) as suggested by the error.
