### ISSUE TITLE
aws_alb_listener_rule resource does not support multiple values in the condition object

### ISSUE THREAD

**Issue by ViachaslauKabak** [hashicorp/terraform#22053]
Could you please revert https://github.com/hashicorp/terraform/issues/12983 cause of AWS support multiple values

**Comment by tgadiev** [comment]
Looks like related to https://github.com/terraform-providers/terraform-provider-aws/issues/8126

**Comment by jbardin** [comment]
This does not appear to be related to Terraform core, and is up to the provider to implement. Since there is already a linked issue, I'm going to close this so it can be tracked in one place.
