### ISSUE TITLE
Incorrect execution plan for resource using count

### ISSUE THREAD

**Issue by sbwise01** [hashicorp/terraform#22061]
### Terraform Version
```
Terraform v0.12.4
+ provider.aws v2.19.0
```

### Terraform Configuration Files
```
provider "aws" {
  region  = "us-east-1"
}

variable "users" {
  default = ["brad", "bob", "alice", "joe"]
}

resource "aws_iam_user" "read_only_users" {	
  count = "${length(var.users)}"	
  name  = "${var.users[count.index]}"	
  path  = "/"	
}
```

### Plan and Apply Output (from 2nd step)
```
$ terraform plan -out plan.out
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_iam_user.read_only_users[2]: Refreshing state... [id=alice]
aws_iam_user.read_only_users[3]: Refreshing state... [id=joe]
aws_iam_user.read_only_users[1]: Refreshing state... [id=bob]
aws_iam_user.read_only_users[0]: Refreshing state... [id=brad]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  # aws_iam_user.read_only_users[1] will be updated in-place
  ~ resource "aws_iam_user" "read_only_users" {
        arn           = "arn:aws:iam::REDACTED:user/bob"
        force_destroy = false
        id            = "bob"
      ~ name          = "bob" -> "alice"
        path          = "/"
        tags          = {}
        unique_id     = "REDACTED"
    }

  # aws_iam_user.read_only_users[2] will be updated in-place
  ~ resource "aws_iam_user" "read_only_users" {
        arn           = "arn:aws:iam::REDACTED:user/alice"
        force_destroy = false
        id            = "alice"
      ~ name          = "alice" -> "joe"
        path          = "/"
        tags          = {}
        unique_id     = "REDACTED"
    }

  # aws_iam_user.read_only_users[3] will be destroyed
  - resource "aws_iam_user" "read_only_users" {
      - arn           = "arn:aws:iam::REDACTED:user/joe" -> null
      - force_destroy = false -> null
      - id            = "joe" -> null
      - name          = "joe" -> null
      - path          = "/" -> null
      - tags          = {} -> null
      - unique_id     = "REDACTED" -> null
    }

Plan: 0 to add, 2 to change, 1 to destroy.

------------------------------------------------------------------------

This plan was saved to: plan.out

To perform exactly these actions, run the following command to apply:
    terraform apply "plan.out"

$ terraform apply plan.out
aws_iam_user.read_only_users[3]: Destroying... [id=joe]
aws_iam_user.read_only_users[2]: Modifying... [id=alice]
aws_iam_user.read_only_users[1]: Modifying... [id=bob]
aws_iam_user.read_only_users[3]: Destruction complete after 0s

Error: Error updating IAM User bob: EntityAlreadyExists: User with name alice already exists.
	status code: 409, request id: REDACTED

  on main.tf line 9, in resource "aws_iam_user" "read_only_users":
   9: resource "aws_iam_user" "read_only_users" {



Error: Error updating IAM User alice: EntityAlreadyExists: User with name joe already exists.
	status code: 409, request id: REDACTED

  on main.tf line 9, in resource "aws_iam_user" "read_only_users":
   9: resource "aws_iam_user" "read_only_users" {


$
```

### Expected Behavior
The single aws_iam_user resource for username bob is destroyed

### Actual Behavior
- Attempts to delete a different aws_iam_user resource than declared 
- Attempts to change 2 other aws_iam_user resources that have no declared changes
- Apply errors out with resource management conflicts

### Steps to Reproduce
1. `Plan and apply the Terraform Configuration Files`
2. `Remove the list item "bob" from the list variable users and plan and apply the change`

**Comment by jbardin** [comment]
Hi @sbwise01,

The behavior you have here is expected, due to removing a value from the middle of the list of names. The not only are you removing `bob`, but you are changing the indices of  `alice` and  `joe`.

The error you're encountering has to do with the resources requiring uniqueness and being update-able. This presents a situation where `bob` is changed to `alice`, before `alice` is changed to `joe`. The solution would be to only change the fewest number of list indices in the config, i.e. use:

    ["brad", "joe", "alice"]

which should result in the correct ordering by doing the deletion first. 

Now that we have 0.12 out, the final solution for this is in progress and should be available to try out soon. Once `for_each` on resources has been implemented, individual instances will also be indexable as a map rather than a list. You can watch issue #17179, which we are using to track the feature.

**Comment by sbwise01** [comment]
Thank you for providing that other issue link to watch, it is nice to know there is a plan to address the underlying need.

I disagree however that the behavior I described is expected because `index` is not a definable attribute of the underlying resource.  As used in this discussion, `index` is part of the implementation of state and the logic to match the existing state with the declared resources.

As describe in the procedure, I start with 4 resources in the state, and change the declaration to 3 resources in the state.  The bug is that the underlying logic to calculate the change plan is incorrectly matching the declaration of those resources to the state describing those resources that already exist, presumable because the matching logic is assuming that the order the resources are declared in is an important aspect of matching declared resources to existing state.

**Comment by clebio** [comment]
I believe the underlying problem -- Terraform lists not having a meaningful (or addressable) index -- is what caused the issue that I encountered with the Github provider. Linking here for an additional data point:
https://github.com/terraform-providers/terraform-provider-github/issues/245
