### ISSUE TITLE
Conditionally use if a key is present under a map otherwise use default value

### ISSUE THREAD

**Issue by udayanms** [hashicorp/terraform#22064]
### Current Terraform Version

```
...
```

### Proposal

Usually other languages has feature ifdefined(var.key) to check if the variable is defined.

### References

Something like is present in many languages e.g. 
if (typeof variable !== 'undefined')

**Comment by mildwonkey** [comment]
The [`lookup()`](https://www.terraform.io/docs/configuration/functions/lookup.html) function supports this:

```
lookup(map, key, default)
```

**Comment by jurgenweber** [comment]
how about nested maps?

```  access_points     = {
    marketing       = {
      posix_user    = {
        gid         = "1000"
        uid         = "1000"
        secondary_gids = "0755"
        },
        creation_info = {
          gid         = "1000"
          uid         = "1000"
          permissions = "0755"
      }
    }
    truman          = {
      posix_user    = {
        gid         = "1000"
        uid         = "1000"
        permissions = "0755"
      }
    }
  }
```

```
    creation_info {
      owner_gid     = lookup(var.access_points[each.key], "creation_info", null) == null ? null : lookup(var.access_points[each.key]["creation_info"], "gid", null)
      owner_uid     = lookup(var.access_points[each.key], "creation_info", null) == null ? null : lookup(var.access_points[each.key]["creation_info"], "uid", null)
      permissions   = lookup(var.access_points[each.key], "creation_info", null) == null ? null : lookup(var.access_points[each.key]["creation_info"], "permissions", null)
    }
```

I am trying to test for 'creation_info' before I attempt to use keys in 'creation_info'. I keep getting errors doing this.

**Comment by dec5e** [comment]
The only option I've found to get a binary result with `lookup` looks ugly:
```terraform
key_exists = lookup(map, key, default) != default
```

Is there a better way?

**Comment by jurgenweber** [comment]
not that I know of.

**Comment by jan-philippkappmeier-tomtom** [comment]
It can be done like this:

    if contains(keys(map), key)

**Comment by badsector3** [comment]
I  have problem like this:
```
dynamic` "vpc" {
    for_each  = each.value["vpc_id"] != null ? [{
      vpc_id  = each.value["vpc_id"]
    }] : []

    content {
      vpc_id  = vpc.value["vpc_id"]
    }
  }
```

I  need  to generate  the vpc block only  if vpc_id is part  of the map
It  works  fine if I specify:

`vpc_id = null `

or

`vpc_id  = module.vpc.vpc_id`

otherwise if vpc_id is missing it will thow error:

```
  16:     for_each  = each.value["vpc_id"] != null ? [{
    |----------------
    | each.value is object with 2 attributes

The given key does not identify an element in this collection value.
```

It  works but I  need to have  the vpc_id = null

**Comment by lonegunmanb** [comment]
Another approach could be:

```hcl
key_exists = can(map[key])

**Comment by looselytyped** [comment]
If the intent is to lookup a value in a map and return a default, maybe try `try`?

```
key_exists = try(map[key], "some default")
```

Reference: https://www.terraform.io/language/functions/try

**Comment by sergiovega-opti** [comment]
This should work:

```
contains(keys(var.map), "key_value")
```

**Comment by frankliucode** [comment]
I use "contains" to check key existence, then assign variable conditionally, 

Here is an example, 

`  duration  = contains(keys(var.durations), "WriteThroughput") ? var.durations["WriteThroughput"] : var.duration
`

**Comment by udayanms** [comment]
lookup is helpful in case of map.. I was looking for a construct to check if the object is declared I used "try" for now.
