### ISSUE TITLE
0.12.4 does not accept relative path to local module

### ISSUE THREAD

**Issue by chris-vest** [hashicorp/terraform#22073]
### Terraform Version
```
Terraform v0.12.4
+ provider.aws v2.19.0
+ provider.vault v2.1.0
```

### Terraform Configuration Files
I am using a local module, which is configured via a relative path:
```hcl
module "potwars-sit" {
  source = "../../../modules/rds-vault"

  engine                  = "mysql"
  ...
  instance_class          = "db.t3.medium"
}
```

### Debug Output
```bash
$ terraform init

Initializing modules...
- potwars-sit in 

Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../modules: no such file or
directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.


Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../modules: no such file or
directory


Error: Failed to read module directory

Module directory  does not exist or cannot be read.
```

### Expected Behavior
Terraform is initiated, and am then able to run a plan.

### Actual Behavior
Terraform is unable to find the module at the relative path.

### Steps to Reproduce
1. Create a module and reference it using a relative path
2. Run `terraform init`

### Additional Context
Using the exact same configuration, I was able to run the `terraform init` with Terraform version 0.12.3

**Comment by mildwonkey** [comment]
Hi @chris-vest , I'm sorry you are experiencing this unexpected behavior.

The error is coming from a different module then the one you've shared: `potwars-sit`. Is that module called by your `potwars` module? 

I am unable to reproduce this issue using just a relative module path:

```
$ cat main.tf
module "foo" {
  source = "../../../modules"
}

$ terraform init
Initializing modules...
- foo in ../../../modules
```

If you can share the rest of your configuration, or (better yet) a simplified reproduction case, we can dig into this issue. Thanks!

**Comment by chris-vest** [comment]
@mildwonkey Sorry, I posted the output from when I had tried to change the module name to force a new `init`. I'll try again tomorrow with the 'official' 0.12.4 binary instead of the one I built from the 0.12.4 code release and update you.

**Comment by sashokbg** [comment]
I have the same problem here

`module "s3-sql-bucket" {
  source = "./modules/bucket"
  name = "sql"
  env = "developpement"
}`

And I have a folder relative to where I am running terraform called modules with a bucket.tf inside it :(

`
Initializing modules...
- s3-sql-bucket in 

Error: Unreadable module directory

Unable to evaluate directory symlink: lstat modules/bucket: no such file or
directory
`

**Comment by chris-vest** [comment]
@mildwonkey This seems to work now, whereas before (i.e. Terraform 0.10.x) I was using `./../../../modules`, that now needs to be `../../../modules`.
