### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by tamalsaha** [hashicorp/terraform#22085]
We are working on a project that depends on both terraform and terraform-provider for Azure. We are using Go modules and the latest version of these repos as dependency.

```
	github.com/hashicorp/terraform v0.12.4
	github.com/terraform-providers/terraform-provider-azurerm v1.31.0
```

But we are getting the following error, when we try to compile:

```
# github.com/terraform-providers/terraform-provider-azurerm/azurerm
vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/config.go:351:38: too many arguments in call to c.GetAuthorizationToken
	have (autorest.Sender, *adal.OAuthConfig, string)
	want (*adal.OAuthConfig, string)
vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/config.go:358:43: too many arguments in call to c.GetAuthorizationToken
	have (autorest.Sender, *adal.OAuthConfig, string)
	want (*adal.OAuthConfig, string)
vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/config.go:365:46: too many arguments in call to c.GetAuthorizationToken
	have (autorest.Sender, *adal.OAuthConfig, string)
	want (*adal.OAuthConfig, string)
```

The problem is that hashicorp/terraform project is using anold version of Azure go-sdk and helper. A commit like https://github.com/kubeform/terraform/commit/5d6b3a5caaf2ec5a7a14d8912a89249137fbbfa3 should fix the issue. But `go mod tidy` seem to update lot of dependencies. Can you please update the dependencies to the following versions?

```
github.com/Azure/go-autorest/autorest v0.5.0
github.com/Azure/azure-sdk-for-go v31.1.0+incompatible
github.com/hashicorp/go-azure-helpers v0.5.0
```

**Comment by tamalsaha** [comment]
cc: @tombuildsstuff

xref: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3638

**Comment by tamalsaha** [comment]
I have opened a pr https://github.com/hashicorp/terraform/pull/22087 . All the tests are passing!

**Comment by apparentlymart** [comment]
Hi @tamalsaha!

We don't consider the Go packages in this repository and in provider codebases to be a public interface for other codebases to call. The only supported way to run Terraform core logic is by running the `terraform` executable and the only supported way to interact with a provider is to start it up as a child process plugin and communicate with its plugin protocol interface. Both of these interfaces are ones that we aim to minimize breaking changes to and will communicate loudly in respective changelogs about breaking changes to them, whereas we tend to change the Go package APIs within all of these codebases often and without any external communication.

With that said, we are totally fine with upgrading the vendored provider dependencies to latest as long as the relevant provider team (the Azure provider team in this case) can review and ensure it won't have any problematic effects on the backend code it's supporting. If that implicitly helps you with your work then we don't tend to impose any _technical_ blockers on embedding parts of Terraform in your codebase, but in doing so you're assuming a (very likely) risk that your codebase will be broken by other updates in the future.

If someone from the Azure provider team can verify that your PR does not hurt the `azure` backend's behavior and identify any enhancements that upgrade might implicitly enable (so we can record them in the CHANGELOG) then it'd be fine to merge your PR, with the caveats I described above.

**Comment by tamalsaha** [comment]
Dependencies have been updated in master. Thanks!
