### ISSUE TITLE
S3 Bucket resource doesn't expose information required for using Route 53 Alias records

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#2208]
When configuring an Alias records for a S3 static website, the S3 bucket resource doesn't expose the correct information to configure the record.

Currently, the S3 bucket resource exposes `website_endpoint` but this is not the correct value to pass to the `alias.name` option when configuring a Route53 Alias for S3 (http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values.html#resource-record-sets-values-alias)

According (and verified) to the Amazon documentation, the value for an S3 alias should be `s3-website-<region>.amazonaws.com`, *not* the full web site endpoint (so basically, the website endpoint minus the bucket name)

```
provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "foo" {
  bucket = "foo.test.com"
  acl = "public-read"
  policy = "${file("policy.json")}"
  website {
    index_document = "index.html"
  }
}

resource "aws_route53_record" "foo" {
  zone_id = "some zone"
  name = "foo.test.com"
  type = "A"
  alias {
    name = "s3-website-us-east-1.amazonaws.com" //Not exposed on S3 Bucket resource
    zone_id = "${aws_s3_bucket.versions.hosted_zone_id}"
    evaluate_target_health = true
  }
}
```

This value should also be exposed on the S3 resource so it can be used.

**Comment by stack72** [comment]
@phinze I think this one is also now taken care of ^^

**Comment by radeksimko** [comment]
Agreed, this can be closed now. Thanks for the reminder @stack72
