### ISSUE TITLE
TF_VAR_* available on terraform destroy

### ISSUE THREAD

**Issue by enxebre** [hashicorp/terraform#2209]
When running terraform destroy TF_VAR_* environment variables seems to be not available so shell promp asking cloud credentials and variables with no default value so I need to do something like:

```
    terraform destroy -var "do_token=${TF_VAR_do_token}" \
      -var "key_file=${TF_VAR_key_file}" \
      -var "region=${TF_VAR_region}"
```
I wonder if there is a reason for the variables not being available on destroy

**Comment by phinze** [comment]
Thanks for the report - that's definitely odd. We'll get this fixed up.

**Comment by mitchellh** [comment]
I just tested this locally and couldn't reproduce it. The variables are available. Can you test with the latest master and report back if you're still seeing this?
