### ISSUE TITLE
Feature request: taint multiple addresses at once

### ISSUE THREAD

**Issue by matthiasr** [hashicorp/terraform#22117]
### Current Terraform Version

```
$ terraform -v
Terraform v0.12.4
+ provider.aws v2.19.0
+ provider.external v1.2.0
```

### Use-cases

Sometimes I need to rebuild multiple specific resources. Specifically, we use `terraform taint` as the regular way of rebuilding instances in questionable states, or to apply changes on lifecycle-ignored fields in a controlled manner.

### Attempted Solutions

This works:

```bash
for cluster in foo bar baz;
do
  terraform taint aws_instance.mysql-$instance[0]
done
```

but it is very slow because it aquires the lock, updates the state, and then releases the lock separately for each item.

### Proposal

I would propose a straightforward extension of the `terraform taint` syntax to allow multiple addresses to be specified at once:

```
terraform taint aws_instance.mysql-foo[0] aws_instance.mysql-bar[0] aws_instance.mysql-baz[1]
```

This could then be done with a single update to the state (and acquisition of the lock).

This wasn't possible with the 0.11 taint syntax, but now it is.

### References

This is related but orthogonal to #16651.

**Comment by fnickels** [comment]
Would be nicer to just do:
```
terraform taint aws_instance.mysql-foo[*]
```
but not currently supported.

**Comment by pselle** [comment]
This is absolutely still a valid request, however I am closing it to consolidate it with https://github.com/hashicorp/terraform/issues/1768 as the overarching issue to track this work.
