### ISSUE TITLE
Terraform crashing on "plan" command

### ISSUE THREAD

**Issue by mailgajender** [hashicorp/terraform#22150]
### Terraform Version

Terraform v0.12.5
+ provider.aws v2.20.0

### Terraform Configuration Files ##################

!!!!!!!!!! Below is the part of the module i am using to enable route propagation to virtual private gateway, whenever i give input to create a VGW.When virtual gateway is involved and the propagating_vgws id is available, terraform is working fine . In cases where there is no VPG created, and the propagating_vgws should be null, terraform is crashing !!!!!!!!!!!

resource "aws_default_route_table" "this" {
default_route_table_id = aws_vpc.this.default_route_table_id
propagating_vgws = [var.**VPG_enable** == "yes" ? aws_vpn_gateway.this[0].id : **null**]

tags = merge(
var.tags,
{
"Name" = format(
"%s-%s-%s-rtable",
var.account_type,
var.team_name,
var.environment,
)
},
)
}
[crash.log](https://github.com/hashicorp/terraform/files/3412691/crash.log)

-----

### Expected Behavior

It shouldn't crash

### Actual Behavior

It crashes

### Steps to Reproduce

terraform init
terraform plan

**Comment by teamterraform** [comment]
Hi @mailgajender!

This seems to be a similar problem as in #22147, so we're going to close this one to consolidate the discussion over there. Thanks for reporting this!
