### ISSUE TITLE
nesteed loop

### ISSUE THREAD

**Issue by zdogan** [hashicorp/terraform#22177]
### Current Terraform Version

```
...
```

**Comment by teamterraform** [comment]
Hello, to better understand this issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - full output (stdout + stderr) from terraform commands you ran (minus any secrets)
 - [debug log](https://github.com/hashicorp/terraform/blob/master/website/source/docs/internals/debugging.html.md#debugging-terraform) from terraform commands you ran (minus any secrets)

Thanks.

**Comment by teamterraform** [comment]
Duplicate of https://github.com/hashicorp/terraform/issues/22178
