### ISSUE TITLE
Error: InvalidAMIID.Malformed

### ISSUE THREAD

**Issue by Damarla499** [hashicorp/terraform#22172]
Hi,

i am trying to launch new instance in us-east-1 , that is ami-id: ami-07ea7ce67253d4337. But unfortunately i am getting this error

Error: InvalidAMIID.Malformed: Invalid id: "{var.ami_id}" (expecting "ami-...")
        status code: 400, request id: 02696e49-6f66-4ed1-9968-8b1b3db6bc10

can you help me please ?

**Comment by Damarla499** [comment]
this instance/AMI is available in us-east-1 and i am able to do it by manually.

**Comment by teamterraform** [comment]
Hello @Damarla499. Could you please post a more detailed configuration? Based on what you provided my best guess is it seems you have forgotten the dollar sign `$` before the curly braces which triggers terraform's string interpolation:
```
{var.ami_id}
```
VS
```
${var.ami_id}
```

The former will not be interpolated.

**Comment by Damarla499** [comment]
yes, that's solved problem.Thank you.
