### ISSUE TITLE
`terraform import ...` fails when all resources use the "google-beta" provider (as opposed to "google")

### ISSUE THREAD

**Issue by cpick** [hashicorp/terraform#22170]
### Terraform Version

```
$ terraform -v
Terraform v0.12.5
+ provider.google-beta v2.11.0
```

### Terraform Configuration Files

```hcl
variable "project_id" {
}

terraform {
  required_version = "~> 0.12"
}

provider "google-beta" {
  version = "~> 2.8"
  project = var.project_id
}

resource "google_storage_bucket" "test" {
  provider = "google-beta"
  name     = "foo-bar-baz-test"
}
```

### Debug Output

https://gist.github.com/cpick/3d338a934a55a73cafbb7e8ed8c4b5a1

### Expected Behavior

`terraform import ...` should succeed even if all resources are using the "google-beta" provider (as opposed to the "google" provider).

### Actual Behavior

```
$ terraform import google_storage_bucket.test foo-bar-baz-test

Error: unknown provider "google"
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -var="project_id=${PROJECT_ID}"`
3. `terraform import google_storage_bucket.test foo-bar-baz-test`

### Additional Context

If at least one resource is created using the "google" provider (as opposed to "google-beta") and `terraform init` is re-run then subsequent `terraform import ...` commands succeed.  The problem only exists if there are no resources managed by the "google" provider.

**Comment by teamterraform** [comment]
Hello @cpick, when importing, terraform will use its default provider name inference, in your example `google_storage_bucket` it will infer the provider as `google`. To override this behavior please use the `-provider`flag, this has been documented specifically for the google and google-beta providers [here](https://www.terraform.io/docs/providers/google/provider_versions.html#importing-resources-with-google-beta).

I'm going to close this issue, however if the issue persists please reach back out to this thread.

**Comment by nauris-sadovskis** [comment]
@cpik - I had the same issue when running `terraform apply` using `google-beta` provider. 

The workaround is to add `google` provider alongside `google-beta` provider.

```hcl
provider "google" {
  project = "my-project"
  region  = "my-region"
  version = "2.12.0"
}
```

@teamterraform hopefully this is helpful

**Comment by cpick** [comment]
@nauris-sadovskis thanks for confirming that you're also able to reproduce this issue.
That's also the same workaround I've been using to avoid this bug.
