### ISSUE TITLE
create cloudsearch service using terraform

### ISSUE THREAD

**Issue by venkatkriish** [hashicorp/terraform#22176]

**Comment by teamterraform** [comment]
Hello @venkatkriish, were you referring to [AWS CloudSearch](https://aws.amazon.com/cloudsearch/)?  Typically speaking resource requests belong in the [provider repository](https://github.com/terraform-providers/terraform-provider-aws). We do our best to track community demand for these types of requests. In this case we have an open issue you can [upvote](https://github.com/terraform-providers/terraform-provider-aws/issues/7833).

I will be closing this issue in favor of the one linked, thank you for your community feedback.
