### ISSUE TITLE
Terraform Crashed when destroying aws environment

### ISSUE THREAD

**Issue by jonhatalla** [hashicorp/terraform#2218]
Built up a full production VPC with terraform, did my work, tore it down.  On the delete action, this happened

```
* connection is shut down
panic: runtime error: invalid memory address or nil pointer dereference
2015/06/03 14:05:12 terraform-provider-aws: [signal 0xb code=0x1 addr=0x10 pc=0x1330f6]
```

full output:
https://gist.github.com/jonhatalla/ee1c5e71d0513f72c642

**Comment by mitchellh** [comment]
This crash is unfortunately coming from inside the official AWS Go library. Can you report this upstream to them please? I took a look at where the stack frame is in our code and I don't _think_ we're causing this.
