### ISSUE TITLE
Terraform fmt - is there any scope for tailoring it?

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#22183]
Terraform fmt does lots of things I consider making code harder to read

example: variables.tf from:

```
variable "access_var1"    { type = "string" }
variable "access_var2"    { type = "string" }
variable "access_var3"    { type = "string" }
variable "common_config"  { type = "map" }
variable "input_var1"     { type = "string" }
```

to

```
variable "access_var1" {
    type = "string"
}

variable "access_var2" {
    type = "string"
}

variable "access_var3" {
    type = "string"
}

variable "common_config" {
    type = "map"
}

variable "input_var1" {
    type = "string"
}
```

etc. - first one - easy to read, easy to see types, easy to diff, all probably fits on a single page
last one , wordy verbose, too many lines, difficult to diff and frequently goes off the page. 

Is it possible to switch on different features of terraform fmt to tailor what it does? Some of the decisions it makes are questionable. 

Thanks!

**Comment by pselle** [comment]
Hi @gtmtech!

`fmt` does not currently support granular configuration, or defining an alternative style, and the following is a reason why:

> Other Terraform commands that generate Terraform configuration will produce configuration files that conform to the style imposed by terraform fmt, so using this style in your own files will ensure consistency.

The response above is meant to answer your question, but are you requesting this as a feature?

**Comment by pselle** [comment]
On further research and reflection, I'll close this question, and the larger "can I customize how `fmt` works?" is responded to in this comment: https://github.com/hashicorp/terraform/issues/20910#issuecomment-495675395 and can be the place for any further discussion (or closure, if a firm decision is made).
