### ISSUE TITLE
Crash on apply and plan

### ISSUE THREAD

**Issue by jalseth** [hashicorp/terraform#22196]
### Terraform Version
```
Terraform v0.12.5
+ provider.google v2.11.0
+ provider.google-beta v2.11.0
+ provider.random v2.1.2
```

### Crash Output
https://gist.github.com/jalseth/2caf70cb4c0c274bedbf52ec9f29f3a2

### Expected Behavior
No crash

### Actual Behavior
Crash

### Steps to Reproduce
`terraform apply` or `terraform plan`

### Additional Context
This infrastructure was initially set up using Terraform 0.11 and the configs were updated with `terraform 0.12upgrade`. Running this on a fresh project in GCP ~~does not crash~~ does not crash on the first apply, but crashes on the second apply/plan.

I removed the local terraform cache with `rm -r .terraform`, ran `terraform init`, then `terraform plan` again and the issue persists.

**Update:** On the fresh GCP project the first apply was successful, but subsequent apply/plan crashes in the same manner.

**Comment by teamterraform** [comment]
Hello, to better understand this issue & make it easier to reproduce for anyone else would you mind sharing more details? e.g.

 - configuration information (minus any secrets)

Thanks.

**Comment by jalseth** [comment]
Sanitized and uploaded the configs to https://github.com/jalseth/tf_issue20190724

**Comment by jalseth** [comment]
Any updates on this?

**Comment by jbardin** [comment]
Closed by #22690

**Comment by jalseth** [comment]
Hi, https://github.com/hashicorp/terraform/pull/22690 did not fix my issue. I built Terraform with your changes and the issue persists. New crash log: https://gist.github.com/jalseth/486c62440408227d118d8e4b18f50c2c

**Comment by jbardin** [comment]
Hi @jalseth,

This change is only relevant to the plugin SDK. You would need to rebuild the google provider with the master branch of terraform.
