### ISSUE TITLE
Variable of type (any) or without type

### ISSUE THREAD

**Issue by udayanms** [hashicorp/terraform#22208]
### Current Terraform Version

0.12.5
```
...
```

### Use-cases

Cloud has many JSOn structures based on resource type. It becomes very difficult to test and define different structures. esp when its a multi cloud environment. e.g. Iam policies, VPC structures, SCP policies. they can go as complex as possible. And cloud provider may change the structure any moment frequently. It has been possible in earlier languages and should be possible to let be there a JSON type which does on restrain from exact definition as long as there is a wel formed structure. This shall ease the cloud implementation .

**Comment by teamterraform** [comment]
Hi @udayanms! Terraform supports dynamic types, and "any" types of a sort (although it is not a type itself). More information is available here: https://www.terraform.io/docs/configuration/types.html#dynamic-types-the-quot-any-quot-constraint

**Comment by udayanms** [comment]
I am trying about Complex objects which holds Lists of Maps of List of Maps and strings ....
e.g. 
  vpc_conf = {
     name = "MyDemo"
     cidr = "10.11.0.0/16"
     subnets = [
                {
                  cidr = "10.11.2.0/24"
                  name = "MyDemoSubnet1"
                },
                {
                  cidr = "10.11.3.0/24"
                  name = "MyDemoSubnet2"
                }
     ]
   }
}
