### ISSUE TITLE
Import a resource if already exist

### ISSUE THREAD

**Issue by mprenditore** [hashicorp/terraform#22206]
### Current Terraform Version
```
0.12.3
```

### Use-cases
In case there are multiple tf scripts that share some resources or a resource is already present because manually created, being able to import the resource in the tfstate file if already exist.

#### shared resources:
-  created a separated "common" tf script with a separate tfstate flle that manages the resources and exports some outputs
- added a `data` resource that load from the "common" tfstate file the outputs

But that means I've to run 2 different `terraform apply` in order to do it, and `terraform plan` on the script that has the ***data*** resource will fail till the "common" tf script is executed and exported the tfstate.

#### already created resources:
- manually import the resource via `terraform import`

That means I've to manually import it every time I want to use something already created.

### Proposal
It will be useful to have an option in resource like `import_if_exist` that before applying the state will import the resource in the tfstate file.

~~~
resource "resource_x" "name" {
  name = "resource_x_name"
  import_if_exist = true
}
~~~

EDIT: added another issue found with the current implementation

**Comment by teamterraform** [comment]
Hello @mprenditore, we recognize the situation that you've experience and appreciate the feedback. However, currently it is a design that infrastructure created outside of Terraform be imported first. We do recognize though that the user experience and education of that principle can be communicated better and will be looking to improve that experience in the future. A proposal within the [AWS provider](https://github.com/terraform-providers/terraform-provider-aws/issues/9223) details how we might accomplish that. I will be closing this issue, but thank you sincerely for your time and feedback.

**Comment by mprenditore** [comment]
Thank you for the link about that opened issue.
I perfectly understand your design principle, in fact I'm not asking to change it, but to have an option to override it when needed because that can simplify the management and speed up CI/CD a lot, especially in complex cases.

As it's pointed in the linked issue, I'm not the only one that would like to discuss about that, so I think that closing this thread that could be a starting point for a discussion between all other contributors and evaluate other points of view.

Anyways, thank you for your reply.

Happy provisioning
