### ISSUE TITLE
yamldecode drops trailing zeroes from strings that resemble decimals

### ISSUE THREAD

**Issue by jacknagel** [hashicorp/terraform#22223]
### Terraform Version
```
Terraform v0.12.5
```

### Expected Behavior
I have a version number in a YAML manifest. I want to extract and use it in my terraform configuration. I expect the following:

```
$ terraform console
> yamldecode("version: '1.0'")
{
  "version" = "1.0"
}
```

### Actual Behavior
What actually happens is:

```
> yamldecode("version: '1.0'")
{
  "version" = "1"
}
> yamldecode("version: '1.00'")
{
  "version" = "1"
}
```

Decimal-looking strings not ending in zero parse correctly:

```
> yamldecode("version: '1.01'")
{
  "version" = "1.01"
}
```

**Comment by teamterraform** [comment]
Thanks for reporting this @jacknagel and I'm sorry you've come across this.

The `yamldecode` function comes directly from [`go-cty-yaml`](https://github.com/zclconf/go-cty-yaml). I will open an issue in that repository and keep this one open as a reminder to update terraform's version of `go-cty-yaml` when fixed.

**Comment by teamterraform** [comment]
https://github.com/zclconf/go-cty-yaml/issues/5

**Comment by cspargo** [comment]
Is this the same issue? it drops leading zeros from a string that looks like a number

```
> yamldecode("version: '003'")
{
  "version" = "3"
}
```
