### ISSUE TITLE
Creation and deletion fails for Subnet with VPC which has different CIDR

### ISSUE THREAD

**Issue by udayanms** [hashicorp/terraform#22229]
Hi there,

Each provider has it's own repository, and issues should be opened there not on the main Terraform repository.

Here are some of the most common:

* [AWS](https://github.com/terraform-providers/terraform-provider-aws)

*Desired State file: path DesiredState/vpc/

*file:main.tf
locals {
  vpc_conf = {
     name = "MyDemo"
     create_vpc = false
     cidr = "10.11.0.0/16"
     secondary_cidr_blocks = ["10.12.0.0/16","10.13.0.0/16"]
     subnets = [
                {
                  cidr = "10.11.2.0/24"
                  tags = {
                    Name    = "MyDemoSubnet1"
                    purpose = "TF Automation"
                  }
                },
                {
                  cidr = "10.12.2.0/24"
                  tags = {
                    Name    = "MyDemoSubnet2"
                    purpose = "TF Automation"
                  }
                },
                {
                  cidr = "10.13.3.0/24"
                  tags = {
                    Name    = "MyDemoSubnet3"
                    purpose = "TF Automation"
                  }
                }
     ]
   } 
}

module "demo_vpc" {
  source      = "Modules/vpc"
  default_conf = var.default_conf
  vpc_conf     = local.vpc_conf
}

*Modules: Modules/vpc
*main.tf

resource "aws_vpc" "vpc" {
  count      = var.vpc_conf.create_vpc ? 1 : 0
  cidr_block = var.vpc_conf.cidr

  tags = {
    EonId       = var.default_conf.eon_id
    Environment = var.default_conf.environment
    Name        = var.vpc_conf.name
  }

}

resource "aws_vpc_ipv4_cidr_block_association" "associated_cidr" {
  count = var.vpc_conf.create_vpc && length(var.vpc_conf.secondary_cidr_blocks) > 0 ? length(var.vpc_conf.secondary_cidr_blocks) : 0

  vpc_id = aws_vpc.vpc[0].id

  cidr_block = var.vpc_conf.secondary_cidr_blocks[count.index]
}

resource "aws_subnet" "prodsubnet" {
  count      = var.vpc_conf.create_vpc && length(var.vpc_conf.subnets) > 0 ? length(var.vpc_conf.subnets) :0
  vpc_id     = aws_vpc.vpc[0].id
  cidr_block = var.vpc_conf.subnets[count.index].cidr
  tags =  var.vpc_conf.subnets[count.index].tags
}

*Output for terraform apply

module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_vpc.vpc[0]: Refr                             eshing state... [id=vpc-0a12d242c9b9b3bb3]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[1]: Refreshing state... [id=subnet-02f679fb3bcbb184d]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[2]: Refreshing state... [id=subnet-093d9d5300e9ae588]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[0]: Refreshing state... [id=subnet-0f9a847d5086dcb9b]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_vpc_ipv4_cidr_bl                             ock_association.associated_cidr[0]: Refreshing state... [id=vpc-cidr-assoc-044bc                             3367867a2540]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_vpc_ipv4_cidr_bl                             ock_association.associated_cidr[1]: Refreshing state... [id=vpc-cidr-assoc-007bd                             bddf0eaccbdf]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prods                             ubnet[0] will be destroyed
  - resource "aws_subnet" "prodsubnet" {
      - arn                             = "arn:aws:ec2:us-east-1:517734223592:su                             bnet/subnet-0f9a847d5086dcb9b" -> null
      - assign_ipv6_address_on_creation = false -> null
      - availability_zone               = "us-east-1e" -> null
      - availability_zone_id            = "use1-az3" -> null
      - cidr_block                      = "10.11.2.0/24" -> null
      - id                              = "subnet-0f9a847d5086dcb9b" -> null
      - map_public_ip_on_launch         = false -> null
      - owner_id                        = "517734223592" -> null
      - tags                            = {
          - "Name"    = "MyDemoSubnet1"
          - "purpose" = "TF Automation"
        } -> null
      - vpc_id                          = "vpc-0a12d242c9b9b3bb3" -> null
    }

  # module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prods                             ubnet[1] will be destroyed
  - resource "aws_subnet" "prodsubnet" {
      - arn                             = "arn:aws:ec2:us-east-1:517734223592:su                             bnet/subnet-02f679fb3bcbb184d" -> null
      - assign_ipv6_address_on_creation = false -> null
      - availability_zone               = "us-east-1e" -> null
      - availability_zone_id            = "use1-az3" -> null
      - cidr_block                      = "10.12.2.0/24" -> null
      - id                              = "subnet-02f679fb3bcbb184d" -> null
      - map_public_ip_on_launch         = false -> null
      - owner_id                        = "517734223592" -> null
      - tags                            = {
          - "Name"    = "MyDemoSubnet2"
          - "purpose" = "TF Automation"
        } -> null
      - vpc_id                          = "vpc-0a12d242c9b9b3bb3" -> null
    }

  # module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prods                             ubnet[2] will be destroyed
  - resource "aws_subnet" "prodsubnet" {
      - arn                             = "arn:aws:ec2:us-east-1:517734223592:su                             bnet/subnet-093d9d5300e9ae588" -> null
      - assign_ipv6_address_on_creation = false -> null
      - availability_zone               = "us-east-1e" -> null
      - availability_zone_id            = "use1-az3" -> null
      - cidr_block                      = "10.13.3.0/24" -> null
      - id                              = "subnet-093d9d5300e9ae588" -> null
      - map_public_ip_on_launch         = false -> null
      - owner_id                        = "517734223592" -> null
      - tags                            = {
          - "Name"    = "MyDemoSubnet3"
          - "purpose" = "TF Automation"
        } -> null
      - vpc_id                          = "vpc-0a12d242c9b9b3bb3" -> null
    }

  # module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_vpc.vpc[0] w                             ill be destroyed
  - resource "aws_vpc" "vpc" {
      - arn                              = "arn:aws:ec2:us-east-1:517734223592:v                             pc/vpc-0a12d242c9b9b3bb3" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.11.0.0/16" -> null
      - default_network_acl_id           = "acl-048c6d2a8ceb3f4ea" -> null
      - default_route_table_id           = "rtb-0f9b24faf8d7f4222" -> null
      - default_security_group_id        = "sg-0619148ca4db286fc" -> null
      - dhcp_options_id                  = "dopt-a9d2d6d2" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-0a12d242c9b9b3bb3" -> null
      - instance_tenancy                 = "default" -> null
      - main_route_table_id              = "rtb-0f9b24faf8d7f4222" -> null
      - owner_id                         = "517734223592" -> null
      - tags                             = {
          - "Environment" = "Development"
          - "EonId"       = "71120"
          - "Name"        = "MyDemo"
        } -> null
    }

  # module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_vpc_ipv4_cid                             r_block_association.associated_cidr[0] will be destroyed
  - resource "aws_vpc_ipv4_cidr_block_association" "associated_cidr" {
      - cidr_block = "10.12.0.0/16" -> null
      - id         = "vpc-cidr-assoc-044bc3367867a2540" -> null
      - vpc_id     = "vpc-0a12d242c9b9b3bb3" -> null
    }

  # module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_vpc_ipv4_cid                             r_block_association.associated_cidr[1] will be destroyed
  - resource "aws_vpc_ipv4_cidr_block_association" "associated_cidr" {
      - cidr_block = "10.13.0.0/16" -> null
      - id         = "vpc-cidr-assoc-007bdbddf0eaccbdf" -> null
      - vpc_id     = "vpc-0a12d242c9b9b3bb3" -> null
    }

Plan: 0 to add, 0 to change, 6 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[1]: Destroying... [id=subnet-02f679fb3bcbb184d]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[2]: Destroying... [id=subnet-093d9d5300e9ae588]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_vpc_ipv4_cidr_bl                             ock_association.associated_cidr[1]: Destroying... [id=vpc-cidr-assoc-007bdbddf0e                             accbdf]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[0]: Destroying... [id=subnet-0f9a847d5086dcb9b]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_vpc_ipv4_cidr_bl                             ock_association.associated_cidr[0]: Destroying... [id=vpc-cidr-assoc-044bc336786                             7a2540]
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[2]: Destruction complete after 0s
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[1]: Destruction complete after 0s
module.create_us-east-1_vpc.module.call_vpc.module.demo_vpc.aws_subnet.prodsubne                             t[0]: Destruction complete after 0s

*Error: Error deleting VPC IPv4 CIDR block association: InvalidCidrBlock.InUse: T                             he vpc vpc-0a12d242c9b9b3bb3 currently has a subnet within CIDR block 10.12.0.0/                             16
        status code: 400, request id: 97b10c2e-25e8-40d5-9847-785b969ce9db

*Error: Error deleting VPC IPv4 CIDR block association: InvalidCidrBlock.InUse: T                             he vpc vpc-0a12d242c9b9b3bb3 currently has a subnet within CIDR block 10.13.0.0/                             16
        status code: 400, request id: 158310a0-26ad-43bb-afe0-1f140e78df3d

**Comment by udayanms** [comment]
I even tried to split the modules into VPC and Subnet assuming it would add a delay. Same problem appeared at the time of creation as subnet CIDR I used were from the additional subnet.

**Comment by udayanms** [comment]
The moment i changed the Subnet CIDR within the VPC CIDR. It went smooth.

**Comment by teamterraform** [comment]
Hello @udayanms, it's unclear from your issue if this is a crash, a bug, or a feature request for Terraform. The original issue is formatted in a way that is difficult to read, so if you could clarify what you're looking for here, that will help us prioritize this issue. Thanks.

**Comment by udayanms** [comment]
My issue as is with the Provider. 

When there are multiple CIDRs associated with the VPC and atleast one Subnets associated with each of the CIDR. The provider should wait for Subnet Deletion before trying to delete the VPC. as it fails because Subnets are getting deleted and it fails to delete the VPC leaving VPC unhandled. On the similar not when Subnets are getting created the provider should wait before secondary CIDRs are attached properly before trying to create Subnet as it fails for not not finding the secondary CIDRs if there is any subnet to be created under those CIDRs

Its an issue with Provider. There should be a delay/wait/delayed verification added.

**Comment by mafrosis** [comment]
@udayanms Issues with the AWS provider should be posted on their repo:

https://github.com/terraform-providers/terraform-provider-aws

Try to include only the smallest amount of code necessary to recreate your issue. Format your code using ``` blocks, as seen in [Github markdown](https://guides.github.com/features/mastering-markdown/).
