### ISSUE TITLE
Issue referencing modules when using remote backend and windows shells

### ISSUE THREAD

**Issue by conorcasey** [hashicorp/terraform#22234]
Summary
When referencing git sub-directories in module sources while leveraging a remote backend and running this off a windows shell (example powershell, cmd.exe) the sub-directory portion of the git url does not appear to translate the folder structure correctly causing the plan to fail. 

### Terraform Version
0.11.14

### Terraform Configuration Files
Sample module reference:-

```hcl
module "windowsvm" {                                                                        
     source = "git::https://<sampleGITserver>/project/modules//vSphere/Windows"     
                                                                                                                               
     vmname = "testvm01"
     ipaddress = "10.10.10.10"
                     : 
 } 
```

### Debug Output
```
C:> terraform plan
            : 
            : 

Waiting for the plan to start...

Terraform v0.11.14

Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
2019/07/29 15:41:44 [DEBUG] Using modified User-Agent: Terraform/0.11.14 PTFE/e78dde7
Initializing modules...
- module.windowsvm
Error downloading modules: Error loading modules: module windowsvm: open .terraform/modules/6fce348a238a953d3382c6072be1808c/vSphere\Windows: no such file or directory

C:>
```

### Expected Behavior
Plan should complete successfully. This process is successful if the remote backend configuration is removed and state is saved to my desktop.

### Actual Behavior
The plan fails because the full path to the module is not valid. You can see from the output above, the backslash in "vSphere\Windows" should have been converted to a forwardslash "vSphere/Windows" but it is not. When run on a linux/unix shell this is not an issue.

### Steps to Reproduce
- Configure a workspace on Terraform Enterprise
- Write a short terraform config that references this TFE workspace as its remote backend
- Create a simple module to do something (in my case provision a windows vm on vSphere
- Push this module to a sub-folder/directory on a git repo
- Try referencing the module in that subfolder using double slash syntax ("//") as outlined here - https://www.terraform.io/docs/modules/sources.html#modules-in-package-sub-directories
- Run terraform init on a windows cmd.exe or powershell shell
- Run terraform plan on a windows cmd.exe or powershell shell

### Additional Context
I have already reviewed this issue with Terraform technical support who confirmed they can reproduce it and encouraged me to report the issue

### References
Hashicorp support request (17574)

**Comment by teamterraform** [comment]
Thank you for reporting this @conorcasey ! Just so you know, I've edited your comment only to update the styling; I did not change the content.

---

The (very) short version of this bug is that terraform is storing windows-style paths in the manifest.json file, but PTFE runs on linux-based machines.

**Comment by dedamico** [comment]
A bit more info - on 0.12.x the error is different but I'm presuming the underlying cause will be the same:

Terraform v0.12.6
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
2019/08/01 20:28:08 [DEBUG] Using modified User-Agent: Terraform/0.12.6 TFE/db38518
Initializing modules...
Downloading git::https://github.com/dedamico/17574.git for servers...

Error: Failed to download module

Could not download module "servers" (main.tf:12) source code from
"git::https://github.com/dedamico/17574.git": error downloading
'https://github.com/dedamico/17574.git': /usr/bin/git exited with 128: fatal:
Not a git repository (or any of the parent directories): .git



Error: Failed to download module

Could not download module "servers" (main.tf:12) source code from
"git::https://github.com/dedamico/17574.git": error downloading
'https://github.com/dedamico/17574.git': /usr/bin/git exited with 128: fatal:
Not a git repository (or any of the parent directories): .git



Also, the modules.json in 0.12.x looks like so:

{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"1.servers;git::https://github.com/dedamico/17574.git//subdir1/subdir2","Source":"git::https://github.com/dedamico/17574.git//subdir1/subdir2","Dir":".terraform/modules/5e31bd453c61e7791fe14a2f7834f05e"},{"Key":"servers","Source":"git::https://github.com/dedamico/17574.git//subdir1/subdir2","Dir":".terraform\\modules\\servers\\subdir1\\subdir2"}]}

**Comment by conorcasey** [comment]
This is great information, thanks guys!

**Comment by srviljoen** [comment]
Having the same issue with Terraform v0.12.9 + Terraform Cloud + Windows cmd.exe

```
Terraform v0.12.9
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
2019/10/04 09:46:51 [DEBUG] Using modified User-Agent: Terraform/0.12.9 TFC/51146a6042
Initializing modules...
Downloading git::ssh://git@scm.neosventures.com/aws/mod_amadeus_vpc.git for vpc...

Error: Failed to download module

Could not download module "vpc" (main.tf:2) source code from
"git::ssh://git@scm.neosventures.com/aws/mod_amadeus_vpc.git": error
downloading 'ssh://git@scm.neosventures.com/aws/mod_amadeus_vpc.git':
/usr/bin/git exited with 128: fatal: not a git repository (or any of the
parent directories): .git

Error: Failed to download module

Could not download module "vpc" (main.tf:2) source code from
"git::ssh://git@scm.neosventures.com/aws/mod_amadeus_vpc.git": error
downloading 'ssh://git@scm.neosventures.com/aws/mod_amadeus_vpc.git':
/usr/bin/git exited with 128: fatal: not a git repository (or any of the
parent directories): .git
```

Is there any workaround\solution to this as most of our admins run Windows laptops and being forced to choose between using the TF cloud backend or using modules is not optimal.

Thanks.

**Comment by srviljoen** [comment]
Having the same issue with Terraform v0.12.9 + Terraform Cloud + Windows cmd.exe

Terraform v0.12.9
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
2019/10/04 09:46:51 [DEBUG] Using modified User-Agent: Terraform/0.12.9 TFC/51146a6042
Initializing modules...
Downloading git::ssh://git@scm.neosventures.com/aws/mod_xxxxxx_vpc.git for vpc...

Error: Failed to download module

Could not download module "vpc" (main.tf:2) source code from
"git::ssh://git@scm.neosventures.com/aws/mod_xxxxxx_vpc.git": error
downloading 'ssh://git@scm.neosventures.com/aws/mod_xxxxxx_vpc.git':
/usr/bin/git exited with 128: fatal: not a git repository (or any of the
parent directories): .git

Error: Failed to download module

Could not download module "vpc" (main.tf:2) source code from
"git::ssh://git@scm.neosventures.com/aws/mod_xxxxxx_vpc.git": error
downloading 'ssh://git@scm.neosventures.com/aws/mod_xxxxxx_vpc.git':
/usr/bin/git exited with 128: fatal: not a git repository (or any of the
parent directories): .git
Is there any workaround\solution to this as most of our admins run Windows laptops and being forced to choose between using the TF cloud backend or using modules is not optimal.

Thanks.

**Comment by dedamico** [comment]
@srviljoen thanks for confirming the behavior on your side.  The workaround for this scenario is to use a Linux subsystem on Windows for running Terraform with the remote backend.  

Two examples of this are:

- Git Bash
- WSL (https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by CyanMass45** [comment]
Using Terraform v0.12.10 and also getting this exact issue but not able to use workaround as I use a bunch of local-exec powershell blocks, which on linux subsystems gives: 

exec: "Powershell": executable file not found in $PATH. Output:

I've also tried installing powershell core for linux but still getting failures (also haven't found a way to call pwsh in linux). Had to revert back to using Azure blob as backend. Any idea when this will be resolved?

**Comment by mikemikemotorbike** [comment]
Has anyone been able to test the workaround?  I have both bitbash and WSL installed and I have the same behavior

**Comment by danieldreier** [comment]
I want to apologize for the slow response time on this issue, and also let you know that I am bulk-closing all issues exclusively reported against Terraform 0.11.x, including this issue, because we are no longer investigating issues reported against Terraform 0.11.x. In most cases, when we try to reproduce issues reported against 0.11, we either can't reproduce them anymore, or the reporter has moved on, so we believe we can better support the Terraform user community by prioritizing more recent issues.

We have made a lot of Windows-related improvements during 0.13.x, so I am very curious if you're still running into this in a newer Terraform version. If so, please let us know! We have made a significant effort in the last year to stay on top of bug reports; we have triaged almost all new bug reports within 1-2 weeks for 6+ months now. If you are still experiencing this problem, please submit a new bug report with a reproduction case that works on 0.14.x, link this old issue for context, and we will triage it.
