### ISSUE TITLE
Terraform evaluating template control in a regular string

### ISSUE THREAD

**Issue by nocode99** [hashicorp/terraform#22246]
### Terraform Version

0.12.3

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_route53_record" "txt_record" {
  zone_id = "${local.zone_id}"
  name    = "domain.com"
  type    = "TXT"
  ttl     = 300

  records = [
    "v=spf1 a mx include:mktomail.com exists:%{i}._spf.mta.salesforce.com ~all",
  ]
}
```

### Expected Behavior
Terraform should be able to add the record as the string within the quotes.

### Actual Behavior
It's evaluating the `%{i}` in the string.

```
Error: Invalid template control keyword

  on txt_records.tf line 9, in resource "aws_route53_record" "txt_record":
   9:     "v=spf1 a mx include:mktomail.com exists:%{i}._spf.mta.salesforce.com ~all",

"i" is not a valid template control keyword. Did you mean "if"?
```

### Steps to Reproduce

1. `terraform init`

### Additional Context
This did not happen in `0.11.x`

### Workaround

For now, I have set a lifecycle policy to ignore, but obviously, this isn't a long term solution.

**Comment by teamterraform** [comment]
Hi @nocode99 !

It looks like you haven't run [`terraform 0.12upgrade`]() on your configuration yet. If you run that, you will see that it updates your record slightly to escape the `%{i}`:

```
  records = [
    "v=spf1 a mx include:mktomail.com exists:%%{i}._spf.mta.salesforce.com ~all",
  ]
```

The [Terraform 0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html) recommends running [`terraform 0.12upgrade`](https://www.terraform.io/docs/commands/0.12upgrade.html) before running commands in terraform 0.12. It will help catch syntax changes like this one.
