### ISSUE TITLE
Merge function returns null if any value in any of merged maps is null

### ISSUE THREAD

**Issue by forgieee** [hashicorp/terraform#22251]
### Terraform Version

```
Terraform v0.12.4
```

### Terraform Configuration Files
```hcl
output "merge" {
  value = [
    merge(
      { val1 = "hello" },
      # For "val2" I used value, returned by ternary from this issue, because direct "null" is handled correctly
      # https://github.com/hashicorp/terraform/issues/22250 
      { val2 = false ? chunklist([],2) : [], val3 = "hello" }
    )
  ]
}
```

### Debug Output
https://gist.github.com/forgieee/50f4b4fa6ff456b3ebe3153f5b5bc8e9

### Expected Behavior
output "merge" returns:
```hcl
[
  {
    val1 = "hello",
    val2 = [],
    val3 = "hello"
  }
]
```
Actually "val2" would not return [] because of this issue #22250. So, possibly, solving #22250  will make this one impossible to happen.

### Actual Behavior
merge function returns null (or whatever this beast is)
```
forgie@forgie-VirtualBox ~/git/terraform/test_inter $ terraform apply 

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

merge = [
  null,
]
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
VirtualBox Version 6.0.4 r128413 (Qt5.6.2)
LinuxMint 18.3
Bash

### References
- #22250

**Comment by teamterraform** [comment]
Hi @forgieee ! Much like #22250 , this is fixed in master (which will be terraform 0.12.6):

```
# terraform version
Terraform v0.12.5-60-g447fe6298 (447fe629865a81fa139ef7fa7f6115e744053d7d)
# terraform apply --auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

merge = [
  {
    "val1" = "hello"
    "val2" = []
    "val3" = "hello"
  },
]
```

Thank you!
