### ISSUE TITLE
Dashes in IAM user name broken with S3 backend

### ISSUE THREAD

**Issue by jeffb4** [hashicorp/terraform#22257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.5
+ provider.aws v2.21.1
```

### Affected Resource(s)

* aws_iam_user

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12.0"

  required_providers {
    aws        = "~> 2.21"
  }
  backend "s3" {}
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_user" "dash_test" {
  name          = "dash-test"
  force_destroy = true
  path          = "/"
}
```

### Debug Output

(redacted) debug output with dashes in username https://gist.github.com/jeffb4/f0fccab91495597b622b2097163c881b

(redacted) debug output without dashes in username https://gist.github.com/jeffb4/ab932903779a2758e72aaea151f98f72

### Expected Behavior

User should have been created with a dash in name. This behavior works perfectly fine when the backend is not S3

### Actual Behavior

![image](https://user-images.githubusercontent.com/3298329/62145924-90372780-b2b1-11e9-855e-5b839967c0d3.png)

user is not in "None" for Groups

![image](https://user-images.githubusercontent.com/3298329/62145984-a9d86f00-b2b1-11e9-8c11-a5c1bbce0a07.png)

user shows "Entity not found" in IAM console

### Steps to Reproduce

1. Create tf file as above
2. Configure state backend with `terraform init -backend-config`
3. `terraform apply`

### Important Factoids

Using AWS SSO for an assumed role for runs

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/9550

**Comment by gdavison** [comment]
It looks like this has been resolved in the AWS Provider.

I'm going to close this issue. If you're still seeing this problem, please create a new issue
