### ISSUE TITLE
fileexists should not error if evaluating a directory

### ISSUE THREAD

**Issue by asvoboda** [hashicorp/terraform#22260]
A terraform run fails with an error if you ask it to check `fileexists` on a directory. I think it would be more friendly to not bail out, and instead tell you that a directory is in fact not a file.

### Terraform Version
terraform 0.12.3

### Terraform Configuration Files

```
$ terraform console
> fileexists(".")

>
Error: Error in function call

  on <console-input> line 1:
  (source code not available)

Call to function "fileexists" failed: . is not a regular file, but
"drwxr-xr-x".
```

### Expected Behavior
fileexists should return a bool instead of an error:

```
$ terraform console
> fileexists(".")
false
```

### Actual Behavior
fileexists returns an error

**Comment by teamterraform** [comment]
Hi @asvoboda 
Could you please be more specific about your use case? e.g. share more specific configuration with a provider in use? It would really help to understand what you're trying to achieve.

Would it help if we introduced a new function, which checks whether a directory exists (e.g. `direxists`)? Then we can avoid the ambiguity and still provide the functionality you're asking for.

**Comment by asvoboda** [comment]
Sure thing, I want to achieve a workflow where we can provide some config file on disk and merge that with some sane defaults specified in terraform. Here is a simplified example:

```hcl
variable "projects_file" {
  default     = ""
  type        = string
}

locals {
  projects_path = "${path.root}/arbitrary/nested/path/${var.projects_file}"
  projects_from_file = fileexists(local.projects_path) ? file(local.projects_path) : []
  projects           = distinct(compact(concat(local.projects_from_file, var.projects)))
}
```

So if a user doesn't specify anything in `var.projects_file`, the input to `fileexists` is a directory, which causes an evaluation error instead of just returning false. Having a new function like `direxists` doesn't really get around this issue.

One possible workaround would be to use an empty file and specify that value as the default value for the input variable instead of an empty string.

**Comment by asvoboda** [comment]
Hi @teamterraform, let me know if I should provide additional information here.

Currently, we're just avoiding this issue by not using fileexists or providing a user defined option, since erroring out instead of returning false doesn't really work nicely.

**Comment by teamterraform** [comment]
Hi @asvoboda! Sorry for the long silence.

It sounds like the desired behavior is to read the projects file only if one is provided by the user. Would something like this work for you instead?

```hcl
variable "projects_file" {
  type    = string
  default = null # still optional, but will be null if not set by the caller
}

locals {
  projects_from_file = var.projects_file != null ? [file("${path.root}/path/${var.projects_file}")] : []
  projects           = distinct(compact(concat(local.projects_from_file, var.projects)
}
```

In most cases we'd lean towards only providing `variable "projects"` and letting the calling module be responsible for loading those values from a file if appropriate, but we're assuming that the files in this case are fundamental enough to your particular architecture that it's helpful to make it a first-class feature of the module.

**Comment by asvoboda** [comment]
Thanks for the response. I've since come up with a similar workaround. The root of the issue is really that I expected a function "fileexists" to respond true/false rather than true/error. Feel free to close out this issue and the related PR.
