### ISSUE TITLE
GZip Compression/Decom and Base64 Enc/Dec on Plan Output File corrupts it

### ISSUE THREAD

**Issue by glakshmeepathi** [hashicorp/terraform#22285]
We compress the plan output and decompress it later.

GZip Compression and Base64 Encode on Plan Output File corrupts it.
After decompressing and applying it causes the following error : 
"gob: encoded unsigned integer out of range"

Please let me know what is the way to go about this ?

**Comment by teamterraform** [comment]
Hi, @glakshmeepathi. Please could you provide some more details so we can reproduce the issue:

 - Terraform version
 - configuration file for minimal reproduction case
 - the exact commands you ran, and their output

**Comment by glakshmeepathi** [comment]
@teamterraform 
Thanks for the reply. I will get back with the details.
Before that I would like to know if plan output can be mapped to any standard charset encoding ?

**Comment by teamterraform** [comment]
The plan output is designed to be easily human-readable in a terminal, and is subject to change. The planfile itself is in a format intended to be consumed by terraform, not the same as the output you see on the command line. The internals are subject to change and not guaranteed to be parsable by anything other than terraform.

You can write the plan to a file, and use `terraform show -json $PLANFILE` to save the plan in a json which might be easier to work with.

**Comment by glakshmeepathi** [comment]
A follow up question for additional knowledge : 
i)  Can the result of `terraform show -json $PLANFILE` be stored in a file ?
ii) If so, can this json to given as input to terraform apply instead of the binary file ?

To the original question : 
Terraform Version : 0.11.7
Commands Run : 
`terraform plan  -input=false -out=plan.tfplan -refresh=true -no-color`
`terraform apply -input=false -auto-approve -no-color plan.tfplan`

**Apologies. Actually there is no issue in Terraform.**

We compress and save this plan.tfplan and then later decompress and use it.
At the time of compressing, we converted this binary plan file to `String` Java datatype which encoded/decoded this binary file in UTF-8 which altered the contents. The mistake here is binary file is treated as text file. So the fix is to treat the file purely as binary (`byte[]` Java equivalent) and `encodeBase64String(byte[])`

**Comment by teamterraform** [comment]
Good questions!
Yes, you can store the result of `terraform show -json $planfile`. There isn't an `-out` option but you can just redirect stdout: `terraform show -json $planfile > plan.json`
No, you cannot pass the json file back to `terraform apply`. The json plan cannot be round-tripped back into terraform's binary planfile format.

If you have any feature requests for the json output (or, of course, anything else related to terraform!) please open a new issue. Cheers!
