### ISSUE TITLE
Can not create a brew formula for 0.5.3

### ISSUE THREAD

**Issue by actionjack** [hashicorp/terraform#2228]
Hi there,
I'm trying to create an updated [terraform brew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/terraform.rb) for `0.5.3` 

but I am getting the following error:

```
state/remote/s3.go:10:2: cannot find package "github.com/awslabs/aws-sdk-go/aws/awserr" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/awslabs/aws-sdk-go/aws/awserr (from $GOROOT)
	/private/tmp/terraform20150604-79584-783fs2/terraform-0.5.3/src/github.com/awslabs/aws-sdk-go/aws/awserr (from $GOPATH)
couldn't understand kern.osversion `14.3.0'
```

I believe it relates to PR #2216  which means I can no longer build 0.5.3 from source due to the fact that Amazon has renamed its repo from https://github.com/aws/aws-sdk-go to https://github.com/aws/aws-sdk-go

@actionjack and @dhilton

**Comment by mitchellh** [comment]
You can use the Godeps JSON we have in the deps folder to reproduce the dependencies and build from there.

**Comment by dhilton** [comment]
I'm afraid I don't follow - the 0.5.3 release makes use of the github.com/awslabs/aws-sdk-go which now redirects to the aws organisation as the repo has moved. This causes pain in the released code, as the library isn't installed in the correct place for Terraform, so the aws provider complains that it can't find the dependencies. 

So, even if we change the formula (which we have) to the deps given in the v0-5-3.json the tests fail as the linked library doesn't exist, thanks to the awslabs -> aws repo move. 

Are we missing another way of handling the repo move?

**Comment by phinze** [comment]
@dhilton ah so the `go_resource` helper ends up following the redirect and cloning to `$GOPATH/src/github.com/aws/aws-sdk-go` anyways?

The SHA from the release has the old imports - so I believe it should be a matter of just figuring out how to get `go_resource` to clone to the proper path.

**Comment by dhilton** [comment]
Yes - have recreated the `go_resource` and so far all seems well https://github.com/Homebrew/homebrew/pull/40408
