### ISSUE TITLE
Cannot import when using toset and for_each unless quotes are escaped

### ISSUE THREAD

**Issue by charlieoleary** [hashicorp/terraform#22286]
### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.21.1
```

### Terraform Configuration Files

```hcl
variable "users" {
  type = list(string)
  default = [
    "user1",
    "user2"
  ]
}

resource "aws_iam_user" "user" {
  for_each = toset(var.users)
  name     = "${each.key}"
}

resource "aws_iam_user_group_membership" "membership" {
  for_each = toset(var.users)
  user     = "${each.key}"

  groups = ["SomeGroupName"]
}
```

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

Resources are created as `aws_iam_user.user["user1"]`, so I should be able to run `terraform import aws_iam_user.user["user1"] user1` and have that user imported.

### Actual Behavior

Instead, I receive the error --

```
Error: Index value required

  on <import-address> line 1:
   1: aws_iam_user.user[user1]

Index brackets must contain either a literal number or a literal string.

For information on valid syntax, see:
https://www.terraform.io/docs/internals/resource-addressing.html
```

Running the same command as `terraform import aws_iam_user.user[\"user1\"] user1` works as expected.

### Steps to Reproduce

`terraform init`
`terraform import aws_iam_user.user["user1"] user1`
<Returns an error stating a literal number or literal string must be used.>
`terraform import aws_iam_user.user[\"user\"] user1`
<Works, assuming a valid IAM user is provided.>

**Comment by teamterraform** [comment]
Hi @charlieoleary !
Most shells strip the double quotes from the value before Terraform can evaluate it - there isn't much Terraform can do about it.
Depending on your shell, you may be able to wrap the entire resource in single quotes to avoid this:
```terraform import 'aws_iam_user.user["user1"]' user1```

Since there is no action we can take, I am going to close this issue. Thank you!

**Comment by hbuckle** [comment]
I'm not so certain this is a shell issue, wrapping the resource id in single quotes doesn't work in powershell

```powershell
terraform import 'azurerm_subnet.subnet["AzureFirewallSubnet"]' "/subscriptions/xxx/resourceGroups/cbuk-core-testoce-network-uksouth/providers/Microsoft.Network/virtualNetworks/xxx/subnets/AzureFirewallSubnet"

Error: Index value required

  on <import-address> line 1:
   1: azurerm_subnet.subnet[AzureFirewallSubnet]

Index brackets must contain either a literal number or a literal string.
For information on valid syntax, see:

https://www.terraform.io/docs/internals/resource-addressing.html
```

**Comment by devblackops** [comment]
Same issue for me in PowerShell. What would be the correct syntax to use in this situation?

```
terraform import 'azurerm_role_assignment.owners["Foo-Group"]' /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleAssignments/00000000-0000-0000-0000-000000000000

Error: Index value required

  on <import-address> line 1:
   1: azurerm_role_assignment.owners[Foo-Group]
```

Can you please update the docs for the [import](https://www.terraform.io/docs/import/usage.html) command to address importing resources that use `for_each`?

**Comment by hbuckle** [comment]
@devblackops - it works if you escape the double quotes `\"` but we shouldn't have to do that as the single quoted string should pass them through untouched.
@teamterraform - I also see the same behaviour when using `Start-Process`, which wouldn't use a shell at all.
