### ISSUE TITLE
Error launching source instance: AuthFailure: AWS was not able to validate the provided access credentials         status code: 401, request id: e2ebce2b-0e37-4fcb-8893-73fe552d5a89

### ISSUE THREAD

**Issue by Dhaamodharan** [hashicorp/terraform#22282]
Hi All,

I have created a simple terraform file to launch an ec2 instance. But when I apply the plan, its throwing the mentioned error. My .tf file for reference.
-----------------------------------------
provider "aws" {
  access_key = "xxxxxxxxxxxx"
  secret_key = "xxxxxxxxxxxxx"
  region = "us-east-1"
  version = "~> 2.21"
  skip_credentials_validation = true
  skip_requesting_account_id = true
}

resource "aws_instance" "test-cisinstance" {
  ami= "ami-0ad82a384c06c911e"
  instance_type="t2.micro"
  tags= {
  Name="Terra-Instance"
  }
}

**Comment by teamterraform** [comment]
Hi, @Dhaamodharan. From the error message you received, it looks like AWS thinks your access credentials are invalid. You may want to check that these credentials are valid (e.g. by performing another operation with the AWS CLI) or generate new ones.

This is not a problem with Terraform Core, so I'm going to close this issue. If you think there is a bug in the AWS provider, please raise an issue there. https://github.com/terraform-providers/terraform-provider-aws

**Comment by akeva22** [comment]
Is there anyway this issue can be looked into. I am having the same problem.  First I changed platforms entirely by switching from windows to linux.. windows in a nightmare in itself. Went to Linux.. everything was created with the AC i provided but then all of a sudden they did not work. I generated new ones and those did not work either.

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.
