### ISSUE TITLE
0.12 ternary with multiple booleans and no parentheses fails

### ISSUE THREAD

**Issue by geofffranks** [hashicorp/terraform#22296]
### Terraform Version

```
0.12.5
```

### Terraform Configuration Files

```hcl
resource "aws_lb_target_group" "docker" {
  count = var.ssl_cert == "" ? 0 : 1
  name = lower(
    "${var.env_name}-docker-tg",
  )
  port     = 443
  protocol = "HTTPS"
  vpc_id   = data.aws_vpc.docker[0].id

  health_check {
    protocol            = "HTTPS"
    port                = "443"
    path                = "/v2/"
    timeout             = 5
    interval            = 10
    unhealthy_threshold = 2
    healthy_threshold   = 2
  }

  tags = var.tags
}

resource "aws_cloudwatch_metric_alarm" "docker-lb" {
  count = var.ssl_cert != "" && var.alarm_queue_arn != "" ? 1 : 0
  alarm_name = "${aws_lb_target_group.docker[count.index].name}-backend-count"
  alarm_actions = [ var.alarm_queue_arn ]
  insufficient_data_actions = [ var.alarm_queue_arn ]
  ok_actions    = [ var.alarm_queue_arn ]

  metric_name = "HealthyHostCount"
  comparison_operator = "LessThanOrEqualToOperator"
  threshold = var.lb_healthy_host_threshold
  period = 15
  evaluation_periods = 2

  tags = var.tags
}
```

### Expected Behavior

The count for aws_sns_topic.docker should have been computed to either 0 or 1 based on the boolean logic.

### Actual Behavior

Got this error:

```
Error: Invalid count argument

  on ../pcf-tf-modules/docker/lb.tf line 95, in resource "aws_cloudwatch_metric_alarm" "docker-lb":
  95:   count = var.ssl_cert != "" && var.alarm_queue_arn != "" ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

### Steps to Reproduce

Using the included config, run a terraform plan against AWS.

### Additional Context

If I shorten the ternary to either of the two conditions, it works correctly. Terraform does not seem to allow a multi-condition ternary with `&&` unless you wrap it all in parentheses. 

These all work:

```
count = (var.ssl_cert != "" && var.alarm_queue_arn != "") ? 1 : 0
count = var.ssl_cert != "" ? 1 : 0
count = var.alarm_queue_arn != "" ? 1 : 0
```

But this does not:

```
count = var.ssl_cert != "" && var.alarm_queue_arn != "" ? 1 : 0
```

**Comment by geofffranks** [comment]
I'm now running into the following case not working either in our preprod environment, while simultaneously working for our dev environment. Maybe it was working in dev after i had tried each variable independently and something got cached?

```
count = (var.ssl_cert != "" && var.alarm_queue_arn != "") ? 1 : 0
```

**Comment by nbering** [comment]
The error message explains what's going on:

> The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

Count can't depend on dynamic values, because it needs to resolve before the resource graph is built, so that it will know how many resources to build the graph with.

**Comment by nbering** [comment]
If this is the root module, you're probably ok since both values come from `var`. But if you're using this as a submodule, and those values are fed in from other resources, that would be the problem.

**Comment by geofffranks** [comment]
Yes, thank you. I forgot that the alarm_queue_arn was in fact computed in a top level module.
