### ISSUE TITLE
Unable to "state mv" to a for_each resource

### ISSUE THREAD

**Issue by jkburges** [hashicorp/terraform#22301]
It doesn't seem possible to migrate existing code to use `for_each` without having to destroy/create resources.

### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.22.0
```

### Expected Behaviour

I should be able to move a resource to a `for_each` name to avoid having to destroy/create it.

### Actual Behaviour

Trying to `state mv` an existing (non for_each) resource, e.g.:

```
$ terraform state mv aws_instance.web-bar 'aws_instance.web["bar"]'
Move "aws_instance.web-bar" to "aws_instance.web[\"bar\"]"

Error: Invalid target address

Cannot move to aws_instance.web["bar"]: aws_instance.web does not exist in the
current state.
```

### Terraform Configuration Files

Version 1:

```hcl
provider "aws" {
  region = "us-west-2"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web-bar" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "bar"
  }
}

resource "aws_instance" "web-foo" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "foo"
  }
}
```

Version 2 (converting to `for_each` format):

```hcl
provider "aws" {
  region = "us-west-2"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

variable "instance_names" {
  default = [
    "foo",
    "bar"
  ]
}

resource "aws_instance" "web" {
  for_each      = toset(var.instance_names)
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = each.value
  }
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` # with <version 1 from above>
3. `terraform plan` # with <version 2 from above>

At this point, we have some destroys and creates for EC2 instances:

```
  # aws_instance.web["bar"] will be created
  + resource "aws_instance" "web" {
  <snip>

  # aws_instance.web["foo"] will be created
  + resource "aws_instance" "web" {
  <snip>

  # aws_instance.web-bar will be destroyed
  - resource "aws_instance" "web-bar" {
  <snip>

  # aws_instance.web-foo will be destroyed
  - resource "aws_instance" "web-foo" {
  <snip>

Plan: 2 to add, 0 to change, 2 to destroy.
```

So, we try to do a `terraform state mv` as above, to avoid the planned changes.

**Comment by teamterraform** [comment]
Thank you for reporting this bug @jkburges !

We get an interesting different error when wrapping the resource in single quotes:

```
# terraform state mv random_pet.zoo[0] 'random_pet.for_each_zoo["linus"]'
Move "random_pet.zoo[0]" to "random_pet.for_each_zoo[\"linus\"]"

Error: Invalid target address

Cannot move to random_pet.for_each_zoo["linus"]: random_pet.for_each_zoo does
not exist in the current state.
```

Here is a configuration one can use to reproduce this without creating resources that cost money - just comment out the `for_each` resource for the first apply:

```
variable "list" {
  default = ["linus", "cheetarah", "li-shou"]
}

resource random_pet "zoo" {
  count = 3
  prefix = var.list[count.index]
}

// comment this out for the first apply, then try to state mv
resource random_pet "for_each_zoo" {
  for_each = toset(var.list)
  prefix = each.key
}
``` 

This might be a red herring, but it's worth looking at [addrs.ParseTargetStr](https://github.com/hashicorp/terraform/blob/master/addrs/parse_target.go#L143) to make sure `addrs` properly parses `random_pet.for_each_zoo["linus"]`

**Comment by Tenzer** [comment]
I think there are more problems around this than just rename resources in the state file. From what I've seen you can't remove resources in the state file either, and it's not possible to `terraform import` any resource you want to manage with `for_each`.

Here's the output I get when I try to remove a resource from a state:
```bash
$ terraform state rm github_team_repository.developers["babaganush"]

Error: Index value required

  on  line 1:
  (source code not available)

Index brackets must contain either a literal number or a literal string.
```

**Comment by teamterraform** [comment]
Hi @tenzer! I think you are running into something different - how different shells escape quotes. 
If you are using bash, wrapping the resource in a single quotes will help (using the same code example from above):

```
terraform state rm 'random_pet.for_each_zoo["cheetarah"]'
Removed random_pet.for_each_zoo["cheetarah"]
Successfully removed 1 resource instance(s).
```

**Comment by Tenzer** [comment]
Oh, that's interesting. I tried `random_pet.for_each_zoo[cheetarah]` and `random_pet.for_each_zoo.cheetarah` but didn't think to wrap the entire identifier.

I wonder if that's something that can be detected by Terraform so it can provide more helpful information? That probably belongs in another bug report though.

**Comment by jkburges** [comment]
Hi @teamterraform,

> We get an interesting different error when wrapping the resource in single quotes:

I am using single quotes, also - but your error looks the same to me apart from the names?

Your example differs from mine (aside from the resource type) in that you've used `count = n` whereas in mine, I've explicitly defined multiple instances of the resource (this is required in my "real" code due to different configuration between each resource instance).

**Comment by michalschott** [comment]
```terraform-1.12.6 state mv module.XXX.github_repository_collaborator.admin 'module.XXX.github_repository_collaborator.admin["michalschott"]'

Error: Invalid target address

Cannot move module.street-manager-api.github_repository_collaborator.admin to
<invalid>..: the target must also be a whole resource.```

**Comment by haodeon** [comment]
I am able to move resources within my state file, converting from count to for_each.

```
$ terraform state mv "azurerm_storage_container.infinity[1]" 'azurerm_storage_container.infinity["backups"]'
Move "azurerm_storage_container.infinity[1]" to "azurerm_storage_container.infinity[\"backups\"]"
Successfully moved 1 object(s).
```

**Comment by jkburges** [comment]
> I am able to move resources within my state file, converting from count to for_each.

I think this is a different scenario to what I describe. I am trying to move two explicitly/separately defined resources to a `for_each`. Same as with https://github.com/hashicorp/terraform/issues/22301#issuecomment-517898647

**Comment by devblackops** [comment]
> Hi @Tenzer! I think you are running into something different - how different shells escape quotes.
> If you are using bash, wrapping the resource in a single quotes will help (using the same code example from above):
> 
> ```
> terraform state rm 'random_pet.for_each_zoo["cheetarah"]'
> Removed random_pet.for_each_zoo["cheetarah"]
> Successfully removed 1 resource instance(s).
> ```

When importing state, wrapping with single quotes isn't working with PowerShell. Escaping the double quotes with a backtick (how you'd normally escape things in pwsh) also doesn't work. 

What would be the correct syntax in that scenario?

```
terraform import 'azurerm_role_assignment.owners["foo-group"]' /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleAssignments/00000000-0000-0000-0000-000000000000

Error: Index value required

  on <import-address> line 1:
   1: azurerm_role_assignment.owners[foo-group]

Index brackets must contain either a literal number or a literal string.
For information on valid syntax, see:


terraform import 'azurerm_role_assignment.owners[`"foo-group`"]' /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleAssignments/00000000-0000-0000-0000-000000000000

Error: Index value required

  on <import-address> line 1:
   1: azurerm_role_assignment.owners[foo-group]
```

**Comment by bflad** [comment]
@devblackops you might want to give the following syntax a try with PowerShell (since it requires extra escaping):

```
terraform import 'azurerm_role_assignment.owners[\"foo-group\"]' /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleAssignments/00000000-0000-0000-0000-000000000000
```

The documentation will be updated shortly to reflect this: https://github.com/hashicorp/terraform/pull/22318

For any further questions, it might be best to open a topic on [the community forum](https://discuss.hashicorp.com/c/terraform-core) so this bug report can stay on topic. 👍

**Comment by bastiandg** [comment]
Related Issue: https://github.com/hashicorp/terraform/issues/22375

There seems to be an oddity when using lists with only one element, as in the initial example. This doesn't happen when there are multiple list elements (see https://github.com/hashicorp/terraform/issues/22375#issuecomment-520382778). I posted a dirty workaround for that in the related issue (https://github.com/hashicorp/terraform/issues/22375#issuecomment-521648814). It adds the missing index with `jq`.

**Comment by pdecat** [comment]
I'm facing the `Invalid target address` error reported in https://github.com/hashicorp/terraform/issues/22301#issuecomment-517686705 where the target resource _does not exist in the current state_, e.g.:

```
# terraform state mv -state terraform.tfstate 'module.pagerduty_team1.pagerduty_escalation_policy.bh' 'module.pagerduty.pagerduty_escalation_policy.bh["team1"]'
Move "module.pagerduty_team1.pagerduty_escalation_policy.bh" to "module.pagerduty.pagerduty_escalation_policy.bh[\"team1\"]"

Error: Invalid target address

Cannot move to module.pagerduty.pagerduty_escalation_policy.bh["team1"]:
module.pagerduty.pagerduty_escalation_policy.bh does not exist in the current
state.
```

Apparently, this is intentional:

> If we're moving to an address without an index then that suggests the user's intent is to establish both the resource and the instance at the same time (since the address covers both), but if there's an index in the target then the resource must already exist.

https://github.com/hashicorp/terraform/blob/c9d62bb2f67279754718c564c035a706aa916129/command/state_mv.go#L296

Is there any hope to get that changed, e.g. create the target resource with an index in the state even if it is the first instance at that resource address?

For context, this prevents me from performing a large refactoring (> 400 resources) when moving from resources definitions using `count` to resource definitions using `for_each`. A work-around is to do `terraform state rm $SRC` and `terraform import $DST $ID` for the first item but that only works for resources supporting import and takes much more time than a simple `state mv` as remote API calls are involved.

**Comment by tmccombs** [comment]
> If we're moving to an address without an index then that suggests the user's intent is to establish both the resource and the instance at the same time (since the address covers both)

that means for count you can just leave the index off for the first one. But for a for_each there isn't any way to do this, since there is no "first" item.

**Comment by cha7ri** [comment]
We are currently refactoring some modules to use for_each instead of count, and we are facing the same issue:
`state mv 'aws_subnet.public_az_a[1]' 'aws_subnet.subnets["public_1_az_a"]'`:

```
Move "aws_subnet.public_az_a[1]" to "aws_subnet.subnets[\"public_1_az_a\"]"

Error: Invalid target address

Cannot move to aws_subnet.subnets["public_1_az_a"]: aws_subnet.subnets does
not exist in the current state.```
@teamterraform Any update on this issue, It make it really difficult to upgrade to TF 0.12 and to refactor the code.

**Comment by psalaberria002** [comment]
Just bumped into this one :(

**Comment by morgante** [comment]
This is a major issue which basically blocks migrating to `for_each` for existing resources. Can we get an idea of how to workaround this?

**Comment by tmccombs** [comment]
The best workaround I've been able to find is @pdecat's hack of manually editing the state to add the resource object with an empty "instances"

**Comment by bastiandg** [comment]
@morgante  I posted a workaround in the related issue #22375 .

Here is the current version of the script we are using to handle such cases. It uses `jq` to add the missing index, which you provide as the second parameter.

```bash
# Example call: cat state.tfstate | ./move-single-element-tf012.sh "module.k8s.google_container_node_pool.pool" "pool1" > newstate.tfstate

resource_id="$1"
index_key="$2"
module="$(cut -d '.' -f2 <<< "$resource_id" )"
resource_type="$(cut -d '.' -f3 <<< "$resource_id" )"
resource_name="$(cut -d '.' -f4 <<< "$resource_id" )"

jq -M ".resources[
		.resources | map(.type == \"${resource_type}\" and .module == \"module.${module}\" and .name == \"$resource_name\") | index(true)
	].instances[0] +=
	{\"index_key\": \"$index_key\"}" < /dev/stdin
```

As we are only using resources from modules it only works with resources located in modules. But it should be easy enough to make it work for other structures as well.

**Comment by morganchristiansson** [comment]
Another workaround is to add a dummy element to for_each and run `terraform apply -target 'aws_subnet.subnets["dummy"]'`

This creates a aws_subnet.subnets[] resource and terraform `state mv now` works

**Comment by pexaorj** [comment]
Same here:

```
terraform state list
aws_iam_user.api-users["api-test"]

terraform state rm 'aws_iam_user.api-users["test"]'
Removed aws_iam_user.api-users["test"]
Successfully removed 1 resource instance(s).

terraform import  'aws_iam_user.api-users["test"]'
The import command expects two arguments.
Usage: terraform import [options] ADDR ID

terraform import aws_iam_user.api-users["api-test"]
The import command expects two arguments.
Usage: terraform import [options] ADDR ID

```

Terraform file:

```
variable "api_user_names" {
  description = "Map api-name users"
  default = {
    api-test                 = "api-test"
  }
}

resource "aws_iam_user" "api-users" {
  for_each = var.api_user_names
  name     = each.value
}
```

So it is possible to create users and delete from state, but if I need to import then, it's impossible, causing a lot of problems.

```
terraform -v
Terraform v0.12.13
+ provider.aws v2.34.0

```

**Comment by tabacco** [comment]
> Another workaround is to add a dummy element to for_each and run `terraform apply -target 'aws_subnet.subnets["dummy"]'`
> 
> This creates a aws_subnet.subnets[] resource and terraform `state mv` now works

This is definitely the easiest workaround that doesn't involve editing the state directly and doesn't destroy the resource.

**Comment by MetricMike** [comment]
You can also move the entire collection:
```terraform
terraform state list
aws_route53_record.ipv4["dev"]
aws_route53_record.ipv4["test"]

terraform state mv aws_route53_record.ipv4 aws_route53_record.ipv6

terraform state list
aws_route53_record.ipv6["dev"]
aws_route53_record.ipv6["test"]
```

**Comment by tmccombs** [comment]
Assuming you are moving a for_each collection and not an individual item, or a count collection.

**Comment by taylorludwig** [comment]
Was able to find a somewhat simple workaround for going from a `count` to `for_each` in different modules. 

Takes two `mv` steps. 

First, as @MetricMike suggested, move the whole collection (works even though its from `count`'s integer key to `for_each` string key) 

`terraform state mv 'resource.collection_name' 'module.example.resource.collection_name'`

Then, move each integer index to the string index (notice it's already in the desired module, just the wrong key) 

`terraform state mv 'module.example.resource.collection_name[0]'  'module.example.resource.collection_name["first"]`

`terraform state mv 'module.example.resource.collection_name[1]'  'module.example.resource.collection_name["second"]`

**Comment by dantman** [comment]
Same problem. This makes converting a bunch of individual imported CloudFlare dns entries into a simple for_each a pain.
