### ISSUE TITLE
terraform plan is giving below error

### ISSUE THREAD

**Issue by pavan430** [hashicorp/terraform#22303]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by pavan430** [comment]
Hi ,
I have created one (main.tf) file to create a docker image. When i tried to execute terrafrom plan it throws below error

Error: Error initializing Docker client: protocol not available

Operation system:Windows10

**Comment by mavogel** [comment]
@pavan430 I'd need more input about your current version of the docker provider and terraform in the issue https://github.com/terraform-providers/terraform-provider-docker/issues/171
