### ISSUE TITLE
Can we import a resource which is created with a module than a static resource definition

### ISSUE THREAD

**Issue by udayanms** [hashicorp/terraform#22302]
### Current Terraform Version

```
0.12.5
```

### Use-cases

```
VPCX10 $ cat VPCX10.tf
locals {
  vpc_conf = {
     name = "MyDemo"
     create_vpc = true
     cidr = "10.11.0.0/16"
     secondary_cidr_blocks = ["10.12.0.0/16","10.13.0.0/16", "10.14.0.0/16"]
     subnets = [
                {
                  cidr = "10.11.1.0/24"
                  tags = {
                    Name    = "MyDemoSubnet1"
                    purpose = "TF Automation"
                  }
                },
                {
                  cidr = "10.12.1.0/24"
                  tags = {
                    Name    = "MyDemoSubnet2"
                    purpose = "TF Automation"
                  }
                },
                {
                  cidr = "10.13.1.0/24"
                  tags = {
                    Name    = "MyDemoSubnet3"
                    purpose = "TF Automation"
                  }
                },
                {
                  cidr = "10.14.1.0/24"
                  tags = {
                    Name    = "MyDemoSubnet3"
                    purpose = "TF Automation"
                  }
                }
     ]
   }
}

module "VPCX10" {
  source      = "../../../../../../src/AWS/modules/network/vpc"
  params       = var.params
  vpc_conf     = local.vpc_conf
}
```
module just created the VPC resource as per the specs. 

### Attempted Solutions

I tried to import the vpc 
```
tf import aws_vpc.VPCX10 vpc-0f97d5cxxxxxxxxxxd7c2

Output
Error: resource address "aws_vpc.VPCX10" does not exist in the configuration.

Before importing this resource, please create its configuration in the root module. For example:

resource "aws_vpc" "VPCX10" {
  # (resource arguments)
}
```

### Proposal

There should be a way to import a file like this than uploading a static definition. Because we want to define all the module in a standard form. To make matter worst this vpc folder is under
/masteraccount/ou1/account1/network/vpc/vpcx10 and the TF apply is performed at "account1" level.

**Comment by teamterraform** [comment]
Hello! :robot: 

Here is the documentation for importing a resource into a module: https://www.terraform.io/docs/commands/import.html#example-import-to-module

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by udayanms** [comment]
My bad, but somehow I feel the team is in a hurry of closing the ticket without reading it. I am not sure if information provided was incomplete. but the feature I raised is genuine case and not a consolidation. I have read all your documentation of the features and even some books around terraform and to my sorrow your documentation level is very primitive and does not cover all possibility. Most likely we go used to documentation of AWS and Azure online. but your rating for documentation is 3 out of 10. But I can offer you something. I can help you enhance your documentation if that is possible someway?
