### ISSUE TITLE
terraform resource for_each accepts list and crashes

### ISSUE THREAD

**Issue by akamoto** [hashicorp/terraform#22310]
### Terraform Version
```
~/go/src/tf_crash_for_each $ tf -v
Terraform v0.12.6
+ provider.datadog v2.1.0
```

### Terraform Configuration Files
```hcl
locals {
    a = [ "a", "b" ]
}
resource "datadog" "foo" {
    for_each = local.a
    name = each.key
}
```

### Debug Output
I guess the bug will be relatively obvious to you guys, let me know if the debug is required.
### Expected Behavior
tell me you will not accept lists

### Actual Behavior
panics with:
panic: not a string

### Steps to Reproduce
terraform init
terraform plan

### Additional Context
since I am currently unaware of a possibility to reduce a map (deleting keys/entries from it), I created a helper list, and ran for_each on it. That did not fly. ("panic: not a string")
I assume terraform is trying to assign null to "${each.value}".
Now I use
```for_each = zipmap(local.helper_list, local.helper_list)```
and access the actual values via local.<map>.[each.key].
That works, but maybe I should just use count :)

**Comment by teamterraform** [comment]
Hi @akamoto ! I am sorry you've experienced this bug.
We have a fix for this problem in master, which will be included in the next release. I've included the new output below:

```
Error: Invalid for_each argument

  on main.tf line 5, in resource "datadog" "foo":
   5:     for_each = local.a

The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type tuple.
```

I am going to close this issue. Thanks, and sorry again!

**Comment by dpiddockcmp** [comment]
Hi @akamoto 
You could use the built in function to convert the list (or tuple) to a set:
`for_each = toset(local.helper_list)`
