### ISSUE TITLE
terraform crash during init

### ISSUE THREAD

**Issue by smartpcr** [hashicorp/terraform#22315]
terraform version: 0.11.13

crash.log:
2019/08/02 13:57:06 [INFO] Terraform version: 0.11.13  
2019/08/02 13:57:06 [INFO] Go runtime version: go1.11.5
2019/08/02 13:57:06 [INFO] CLI args: []string{"C:\\ProgramData\\chocolatey\\lib\\terraform\\tools\\terraform.exe", "init"}
2019/08/02 13:57:06 [DEBUG] Attempting to open CLI config file: C:\Users\xiaodoli\AppData\Roaming\terraform.rc
2019/08/02 13:57:06 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/08/02 13:57:06 [INFO] CLI command args: []string{"init"}
2019/08/02 13:57:06 [DEBUG] command: loading backend config file: C:\work\github\aks-bootstrap\scripts\terraform\azure-simple
2019/08/02 13:57:06 [TRACE] module source: "github.com/Microsoft/bedrock/cluster/azure/provider"
2019/08/02 13:57:06 [DEBUG] plugin: waiting for all plugin processes to complete...
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/hashicorp/terraform/config/module.Storage.loadManifest(0xc0000388c0, 0x12, 0x33c4180, 0xc000372320, 0x1, 0xc000224800, 0xc00003c540, 0x5ff0000, 0x0, 0x3c, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:110 +0x487
github.com/hashicorp/terraform/config/module.Storage.moduleDir(0xc0000388c0, 0x12, 0x33c4180, 0xc000372320, 0x1, 0xc000224800, 0xc00003c580, 0x3e, 0x2, 0x2, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:185 +0x64
github.com/hashicorp/terraform/config/module.Storage.findModule(0xc0000388c0, 0x12, 0x33c4180, 0xc000372320, 0x1, 0xc000224800, 0xc00003c580, 0x3e, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/storage.go:258 +0x91
github.com/hashicorp/terraform/config/module.(*Tree).getChildren(0xc0003c2200, 0xc0003cc5d0, 0xc0003c2238, 0xb28719, 0x300d660)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:234 +0x155e
github.com/hashicorp/terraform/config/module.(*Tree).Load(0xc0003c2200, 0xc0003cc5d0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/config/module/tree.go:178 +0xa5
github.com/hashicorp/terraform/command.getModules(0xc00037a9c0, 0xc00003dcc0, 0x3b, 0xc0003d4201, 0x23, 0xc0003d4240)
	/opt/gopath/src/github.com/hashicorp/terraform/command/get.go:84 +0x127
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc00037a9c0, 0xc000004430, 0x0, 0x0, 0xc0003050b0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:179 +0xac7
github.com/mitchellh/cli.(*CLI).Run(0xc000338500, 0xc000338500, 0xc0001b9d20, 0x1)
	/opt/gopath/pkg/mod/github.com/mitchellh/cli@v0.0.0-20171129193617-33edc47170b5/cli.go:255 +0x20e
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb55
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xbe
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x35

**Comment by apparentlymart** [comment]
Hi @smartpcr! Sorry for this crash and thanks for reporting it.

This issue was fixed in a later version of Terraform. If you upgrade to 0.11.14 you should no longer see this crash.

Alternatively, if you delete the `.terraform` directory and let `terraform init` recreate it than that too should avoid the crash; it arises due to a bug in handling a legacy format of one of the files in the `.terraform` directory.
