### ISSUE TITLE
Terraform v0.12.6 consuming 100% of CPU and using also a lot of memory (maybe related with null.provider?)

### ISSUE THREAD

**Issue by carcuevas** [hashicorp/terraform#22325]
Hi there,

Not sure if this it should be here or part or for the null provider, I am not sure exactly what it is failing... I have  coded a new project for doing a IP blacklist and after a rule for the ELB WAF, recently I had to add about 5000 IP ranges until some development was done in some part of our INFRA, of course it took some time but everything was working as expected; then from my home computer I added a few more IPs, and when going back to my working pc I have to reduce the list of 5000 ip ranges to about 10 ip ranges is when the problem started, so when doing either:

``` 
terraform apply
```

or 

```
terraform  plan
```

the system get completely frozen, but  before it froze I could see that it was using 157% of CPU (4 cores machine)and almost 5GB of RAM, I needed to restart my machine after a few minutes.

### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.22.0
+ provider.null v2.1.2
```

### Terraform Configuration Files

**We are using S3 Remote states** working properly 

So as variables.tf I had something like  this, just between the to variable lists I had something like 5000 ip ranges

```

variable "my_blacklist_ips" {
  description = "The list of just some concrete ips"
  default = [
    "ddd.eee.fff.ggg/32",    
    "rrr.nnn.eee.iii/32"
  ]
}

variable "isp_ranges_blacklisted" {
  description = "Different ip ranges"
  default = [
    "xxx.xxxx.xxx.xxx/xx",
    "aaa.bbb.ccc.ddd/xx",
    "zzz.zzz.zzz.zzz/xx"
  ]
  
}




```

in the main.tf

```
## I get both list together
locals {
  
  all_ip_ranges = concat(var.my_blacklist_ips, var.isp_ranges_blacklisted)

}



### For transforming the ip_ranges_blacklisted list into the format needed for the resource
### Maybe this is lame, but I did not know another way to do it, and maybe it's the reason of the problem
resource "null_resource" "finished_list" {
    count = length(local.all_ip_ranges)
    triggers = {
      type = "IPV4"
      value = element(local.all_ip_ranges, count.index)      
    }
}

###                  Creation of the ipset


resource "aws_wafregional_ipset" "blacklist" {
  name = "my_list"
  
  dynamic "ip_set_descriptor" {
    for_each = null_resource.finished_list[*].triggers
  
    content {
      type = ip_set_descriptor.value.type
      value = ip_set_descriptor.value.value
      }

   }

}


###                  Creation of the waf rule

resource "aws_wafregional_rule" "wafrule" {
  depends_on  = ["aws_wafregional_ipset.blacklist"]
  name        = "my_bl_rule"
  metric_name = "mymetricwaf"

  predicate {
    data_id = aws_wafregional_ipset.blacklist.id
    negated = false
    type    = "IPMatch"
  }
}

```

### Debug Output
unfortunatelly I cannot give more debuging a the moment since I had to open the service for the 5000ips, so I have to edit manually the state file from the S3 and remove manually majority of the ip ranges so it could work.

### Crash Output
No output was shown at all, just I was waiting for nearly 15 minutes and nothing was shown, and my computer was completely frozen, all resources were taken by terraform process 

### Expected Behavior
It should update the list of IP ranges, and change from about 5000 to something like 10

### Actual Behavior
Just taking all resources from the computer where terraform is executed and not doing anything in more than 15min.

### Steps to Reproduce
Just to create a big list of ip, like 5000 and then in another computer reduce the list to maybe 10-20 ip adresses and try to apply the config. (important to use the tfstate remotely in S3)

**Comment by teamterraform** [comment]
Hi @carcuevas!
I am sorry you ran into this unfortunate behavior. Terraform's performance with a large number of resources is [a known issue](https://github.com/hashicorp/terraform/issues/16375) and something that we continue to improve on.

If you haven't tried, with this many resources you may be able to speed things up considerably with a higher `-parallelism setting`, since the fastest this could possibly complete with the default  (10) is 500*fastest_resource_type. 

I am going to close this issue in favor of #16375. If changing the `-parallelism` setting to something higher is effective, it would help if you dropped a note here or (preferably) #16375.

Thank you!

**Comment by carcuevas** [comment]
Thanks very much
