### ISSUE TITLE
Splat expression ([*]) may not be used here.

### ISSUE THREAD

**Issue by grodzik** [hashicorp/terraform#22331]
### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.22.0
```

### Terraform Configuration Files

https://gist.github.com/grodzik/7976bf40580c8521e3553e5cd09939dd

### Crash Output

2019/08/05 15:04:13 [INFO] Terraform version: 0.12.6
2019/08/05 15:04:13 [INFO] Go runtime version: go1.12.4
2019/08/05 15:04:13 [INFO] CLI args: []string{"/home/grodzik/.local/src/tfenv/versions/0.12.6/terraform", "plan"}
2019/08/05 15:04:13 [DEBUG] Attempting to open CLI config file: /home/grodzik/.terraformrc
2019/08/05 15:04:13 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/08/05 15:04:13 [INFO] CLI command args: []string{"plan"}

Error: Attribute name required

  on main.tf line 99, in resource "aws_batch_compute_environment" "sample":
  99:     ignore_changes        = ["compute_resources[*].desired_vcpus"]

Splat expressions ([*]) may not be used here.

### Expected Behavior

Should work.

### Actual Behavior

Fails to even refresh the state, or even do initial setup (terraform init) on clean directory (with only main.tf file)

### Steps to Reproduce

`terraform init` on clean project (first run) is sufficient, otherwise `terraform plan`

### Additional Context

This code works with Terraform 0.12.4, stopped working with Terraform 0.12.5. Example code is actually from Terraform AWS docs, with additional lifecycle block. Content of the ignore_changes block is main issue here.

**Comment by grodzik** [comment]
Just to confirm that it's not working with 0.12.5:
```
>_ terraform version
Terraform v0.12.5
+ provider.aws v2.22.0

Your version of Terraform is out of date! The latest version
is 0.12.6. You can update by downloading from www.terraform.io/downloads.html
/tmp/aa 0.47s
>_ TF_LOG=trace tfp
2019/08/05 15:18:38 [INFO] Terraform version: 0.12.5
2019/08/05 15:18:38 [INFO] Go runtime version: go1.12.4
2019/08/05 15:18:38 [INFO] CLI args: []string{"/home/grodzik/.local/src/tfenv/versions/0.12.5/terraform", "plan"}
2019/08/05 15:18:38 [DEBUG] Attempting to open CLI config file: /home/grodzik/.terraformrc
2019/08/05 15:18:38 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/08/05 15:18:38 [INFO] CLI command args: []string{"plan"}

Error: Attribute name required

  on main.tf line 99, in resource "aws_batch_compute_environment" "sample":
  99:     ignore_changes        = ["compute_resources[*].desired_vcpus"]

Splat expressions ([*]) may not be used here.

zsh: exit 1     TF_LOG=trace terraform plan
```

**Comment by teamterraform** [comment]
Hi @grodzik,
The [`ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations) documentation explains that only _literal_ values can be used; splat is not allowed here as described. 

You can work around this with your given configuration by referring to a specific instance of compute_resources:

```
ignore_changes        = ["compute_resources[0].desired_vcpus"]
```

If you add additional `compute_resources`, you will need to add each one to that list.

**Comment by grodzik** [comment]
So why this worked before 0.12.5?
