### ISSUE TITLE
Panic when using for and for_each iterating through list(map(string))

### ISSUE THREAD

**Issue by jvelasquezjs** [hashicorp/terraform#22347]
### Terraform Version

```
terraform -v
Terraform v0.12.6
+ provider.aws v2.22.0
```

### Terraform Configuration Files

my _module_ in `./module

```hcl
variable "zone_id" {
  description = "The id of the zone to create records in."
}

variable "records_list" {
  description = "List records. Each record is a map formed by `name`, `record` and `ttl` optionally."
  type        = list(map(string))

  default = [
    {
      "name"   = "example"
      "record" = "1.2.3.4"
    },
  ]
}

variable "records_count" {
  description = "Number of records to create, has to be set to the number of records in the records_list."
  default     = 0
}

resource "aws_route53_record" "record" {
  # for_each = var.records_list

  for_each = [for r in var.records_list : {
    r_name   = lookup(r, "name", null)
    r_type   = lookup(r, "type", "CNAME")
    r_ttl    = lookup(r, "ttl", 60)
    r_record = lookup(r, "record", null)
  }]

  zone_id = var.zone_id
  name    = each.value.r_name
  type    = each.value.r_type
  ttl     = each.value.r_ttl
  records = each.value.r_record
}
```

_using the module_

```hcl
resource "aws_route53_zone" "test" {
  name = "nowhere.example.co.uk"
}

module "test" {
  source        = "./module"
  zone_id       = aws_route53_zone.test.id
  records_count = 1

  records_list = [
    {
      "name"   = "aaa"
      "type"   = "CNAME"
      "record" = "bbb.nowhere.example.co.uk"
    },
  ]
}

```

### Crash Output

https://gist.github.com/jvelasquezjs/262fdb16e7d18e1272c424e8d08fa18c

### Expected Behavior

Not to panic...

### Actual Behavior

Panic due to string not expected

### Steps to Reproduce

terraform init
AWS_DEFAULT_REGION=eu-west-1 terraform plan

**Comment by wata727** [comment]
This looks like the same issue as https://github.com/hashicorp/terraform/issues/22305.

**Comment by pselle** [comment]
@wata727 is correct! This is fixed in master and will be released in 0.12.7 of Terraform (and I'll leave this open until that is out, and have self-assigned to do so).

To work around this, ensure that you are passing a _set_ and not a _list_ (which Terraform is interpreting as a tuple) to `for_each` using the `toset()` function.

Thank you for the report!

**Comment by pselle** [comment]
Terraform 0.12.7 (with this fix) is now released! https://github.com/hashicorp/terraform/blob/v0.12.7/CHANGELOG.md

**Comment by sc250024** [comment]
@pselle I have a very similar example to @jvelasquezjs (with the `lookup` function and everything) and I'm using Terraform v0.12.7, but for some reason, I'm getting this error:

```
The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type tuple.
```

Can we not pass in a `list(map(string))` type variable? How would you modify @jvelasquezjs 's example in the `aws_route53_record` to make it a set?

**Comment by sc250024** [comment]
Actually I found a solution for my above comment here: https://github.com/hashicorp/terraform/issues/22610#issuecomment-525382343. However, I'm not sure why `map(map(string))` is fine, but this example of `list(map(string))` somehow breaks it.

**Comment by t5unamie** [comment]
@sc250024  can you post the working example. Messing around with different options is not ver clear to me which code change worked for the original example.

**Comment by sc250024** [comment]
@t5unamie Yep. I was using it to make a module for GitLab repositories.

**vars.tf**
```hcl
variable "branch_protection_map" {
  default = {
    master = {
      merge_access_level = "developer"
      push_access_level  = "maintainer"
    }
  }
  description = "Map of branch / access-level mappings to protected branches."
  type        = map(map(string))
}
```

**main.tf**
```hcl
resource "gitlab_branch_protection" "this" {
  for_each = var.branch_protection_map

  project            = gitlab_project.this.id
  branch             = each.key
  merge_access_level = lookup(each.value, "merge_access_level", "developer")
  push_access_level  = lookup(each.value, "push_access_level", "maintainer")
}
```

I guess Terraform needs a `key` as in the `each.key` part. Hopefully that works for you.

**Comment by t5unamie** [comment]
@sc250024  thanks
