### ISSUE TITLE
Cache for state

### ISSUE THREAD

**Issue by tushar00jain** [hashicorp/terraform#22344]
### Current Terraform Version

```
Terraform v0.12.5
```

### Use-cases

Making the execution of certain commands faster

### Proposal

The following commands could use the cached state, perhaps if we want to refer terraform state outside of terraform for example with ansible

These commands would make it much faster to get the outputs and the state faster if the `-cache` argument is specified. If the cache file is present, these commands will use the cached file to get their output, however if the cache is not present, they will operate as normal but also create a cache file in the process.

```bash
terraform state pull -cache
terraform output -cahce
```

**Comment by pkolyvas** [comment]
I'm doing a clean-up of older issues that haven't gained traction but also don't coincide with some of our current focus. The idea is definitely interesting and I have many questions (ex. is this an in-memory cache you're asking for?). That said, we're unlikely to tackle it anytime in the foreseeable future. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform, the use cases, and needs of our practitioners.
