### ISSUE TITLE
cidrhost: incorrect negative calculations for ipv6

### ISSUE THREAD

**Issue by jackivanov** [hashicorp/terraform#22352]
I'm trying to calculate the last usable host within a subnet

`cidrhost("10.200.0.0/16", -2)` returns the right value - `10.100.255.254`
`cidrhost("fd9d:bc11:4020::/64", -2)` returns `::2` which is wrong

### Terraform Version

```
Terraform v0.12.6
```

**Comment by wata727** [comment]
I have been submitted a patch to the library that seems to be causing this problem. https://github.com/apparentlymart/go-cidr/pull/16
