### ISSUE TITLE
terraform fmt add spaces after %

### ISSUE THREAD

**Issue by d-helios** [hashicorp/terraform#22356]
terraform fmt command insert space (" ") character in inline template

### Terraform Version
```
Terraform v0.12.6
```

### Terraform Configuration Files
```hcl
variable "IN" {
  default = [[
    "a",
    "b",
    ],
    ["c",
      "d"
  ]]
}

locals {
  OUT = join(";", [for i in var.IN : "start_${index(var.IN, i)},${join(",", i)},next_%{if index(var.IN, i) + 1 != length(var.IN)}${index(var.IN, i) + 1}%{else}END%{endif}"])

}

output "default" {
  value = local.OUT
}
```

### Expected Behavior
terraform fmt doesn't insert any additional character in inline templates (string)

### Actual Behavior
```
~/t/awef > cp main.tf /tmp/
~/t/awef > terraform fmt
main.tf
~/t/awef > diff /tmp/main.tf main.tf
12c12
<   OUT = join(";", [for i in var.IN : "start_${index(var.IN, i)},${join(",", i)},next_%{if index(var.IN, i) + 1 != length(var.IN)}${index(var.IN, i) + 1}%{else}END%{endif}"])
---
>   OUT = join(";", [for i in var.IN : "start_${index(var.IN, i)},${join(",", i)},next_%{if index(var.IN, i) + 1 != length(var.IN)}${index(var.IN, i) + 1} %{else}END%{endif}"])
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `cp main.tf /tmp/main.tf`
3. `terraform fmt`
4. `diff /tmp/main.tf main.tf`
--

**Comment by wata727** [comment]
I got a minimal reproduction code like the following:

```hcl
variable "foo" {
  default = "foo"
}

foo = "%{if true}${var.foo}%{endif}"
```

And I created the PR to HCL repository https://github.com/hashicorp/hcl2/pull/125
Maybe it fixes the issue.

**Comment by apparentlymart** [comment]
(Reopening because the change in the HCL repository can't fix this until it's vendored into this repository.)
