### ISSUE TITLE
request: Update aws/aws-sdk-go to 1.22.0

### ISSUE THREAD

**Issue by 007** [hashicorp/terraform#22363]
### Terraform Version

```
Terraform v0.12.6
```

### Expected Behavior
Order of precedence for AWS credentials follows CLI precedence

### Actual Behavior
Upstream change made `AWS_PROFILE` override `AWS_*_KEY` behavior

### Steps to Reproduce

I can't reproduce this directly, but I know that this will bite someone who expects AWS CLI precedence. I believe setting `AWS_PROFILE=nonexistent` and having `AWS_*_KEY` values set to valid key+secret will show the behavior.

### Additional Context
This may affect [terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws) too, but I haven't investigated which version of `aws-sdk-go` it is using.

### References

#22253 changed the behavior by pulling the then-current `aws-sdk-go@1.21.7`, the newest upstream release is [`aws-sdk-go@1.22.0`](https://github.com/aws/aws-sdk-go/releases/tag/v1.22.0) which changes the precedence back (closer) to CLI order.

**Comment by teamterraform** [comment]
Hi @007,

Thanks for filing this.
Core actually depends on the AWS provider, so as to ensure that the client behavior matches. 
Once the AWS provider is updated, we can pull the new dependencies from there.

**Comment by bflad** [comment]
It appears this may have been resolved awhile ago -- the AWS Go SDK dependency on master is v1.25.3 and will soon be updated to v1.30.12. If there are still lingering issues on the latest version of the Terraform CLI, please do not hesitate to open a new issue and we will take a fresh look. 👍
