### ISSUE TITLE
Wrong IP Addr/FQDN from vRa given to Chef provisioner

### ISSUE THREAD

**Issue by mcascone** [hashicorp/terraform#22360]
### Terraform Version

```
Terraform v0.11.14
+ provider.vra7 v0.2.0
```

### Terraform Configuration Files

Create the VM in vRA, capture the FQDN. Then pass it to the Chef provisioner:
```hcl
resource "vra7_deployment" "TF-Deploy" {
  ...
  resource_configuration  {
      vSphere_Machine_1.name = ""
    }

  provisioner "chef" {
      connection {
        host = "${self.resource_configuration.vSphere_Machine_1.name}"
        type = "winrm"
        ...
      }
```

### Debug Output

https://gist.github.com/mcascone/563ef81094fc503abfbd369d68a9813d

### Expected Behavior

Chef uses the FQDN captured by Terraform in its provisioning.

### Actual Behavior

Chef gets some other IP/FQDN and provisions the wrong machine:
```
Outputs:

machine-names = [
    MTPCTSCID141
]
run_list =
>
> knife node show terraform-chef-test-1
Node Name:   terraform-chef-test-1
Environment: _default
FQDN:        MTPCTSCID423.consilio.com
IP:          10.12.235.83
Run List:
Roles:
Recipes:
Platform:    windows 6.3.9600
Tags:
```
### Steps to Reproduce

the usual plan-apply flow.
### Additional Context

none
### References

I also posted this issue on the vRA provider repo - I don't know where the issue is root-caused.

- https://github.com/terraform-providers/terraform-provider-vra7/issues/25

**Comment by mcascone** [comment]
One thing i have noticed is that it used to take several retries before connecting successfully - and it connected to the correct machine. Now, it's connecting immediately, but to the wrong machine.

There appears to be no gap between getting the info and sending it to chef, so how does it change?
```
2019-08-06T12:20:40.191-0500 [DEBUG] plugin.terraform-provider-vra7_v0.2.0_x4.exe: {4096 1 10.12.235.61 50 vSphere MTPCTSCID141  2019-08-07
T17:08:48.643Z ENG_Business_Group_A MTP_Test_Kitchen_Windows_v01 ENG_MTP_Rez_A Virtual 37f58946-39bc-4196-9061-466306a7f460 2019-08-07T17:0
8:48.643Z vSphere_Machine_1 true true true true true true true true true true true true}
2019/08/06 12:20:40 [TRACE] root: eval: *terraform.EvalWriteState
2019/08/06 12:20:40 [TRACE] root: eval: *terraform.EvalApplyProvisioners
vra7_deployment.T2019-08-06T12:20:40.209-0500 [DEBUG] plugin.terraform.exe: chef-provisioner (internal) 2019/08/06 12:20:40 [DEBUG] connect
Fing to remote shell using WinRM
-Deploy: Provisioning with 'chef'...
vra7_deployment.TF-Deploy (chef): Connecting to remote host via WinRM...
vra7_deployment.TF-Deploy (chef):   Host: MTPCTSCID141
vra7_deployment.TF-Deploy (chef):   Port: 5985
vra7_deployment.TF-Deploy (chef):   User: engineering
vra7_deployment.TF-Deploy (chef):   Password: true
vra7_deployment.TF-Deploy (chef):   HTTPS: false
vra7_deployment.TF-Deploy (chef):   Insecure: true
vra7_deployment.TF-Deploy (chef):   NTLM: false
vra7_deployment.TF-Deploy (chef):   CACert: false
vra2019-08-06T12:20:40.382-0500 [DEBUG] plugin.terraform.exe: chef-provisioner (internal) 2019/08/06 12:20:40 [DEBUG] Uploading file to 'C:
/Temp/ChefClient.ps1'
7_deployment.TF-Deploy (chef): Connected!
```

**Comment by mcascone** [comment]
i believe I've gotten around this for now by using the IP instead of the FQDN to pass to the chef provisioner.

**Comment by teamterraform** [comment]
Hi @mcascone,

It sounds like this is an issue with the caching of dns responses, not with the data that terraform is passing to the provisioner. I'm going to close this one out for now, but go ahead and add any more info here if it does turn out that terraform is somehow passing the incorrect data.

Thanks
