### ISSUE TITLE
Help with Index & List Logic

### ISSUE THREAD

**Issue by rohrerb** [hashicorp/terraform#22370]
### Terraform Version
```
Terraform v0.12.6
+ provider.azurerm v1.32.1

```

### Terraform Configuration Files
https://gist.github.com/rohrerb/4490f3a63baab12fa6f428646128260e

Create a folder for the modules and then a folder `called resource_group`, place a main.tf with the following:
```
variable "names" {
  description = "List of resource groups to create"
  type = "list"
}

variable "azure_location" {
  description = "Location in which to deploy resources"
}

resource "azurerm_resource_group" "rg" {
  count    = "${length(var.names)}"
  name     = "${var.names[count.index]}"
  location = "${var.azure_location}"
}
```
At the root, place a `main.tf` with the following:
```
module "rgs" {
  source              = "./modules/resource_group"
  names                = ["rg-0","rg-1","rg-2"]
  azure_location      = "eastus"
}
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
3. You will see that three resource groups were applied. 
4. Remove `rg-2` from the list and run a plan.
5. Terraform wants to replace rg-1 with rg-2 and destroy rg-2.  
```
  # module.rgs.azurerm_resource_group.rg[1] must be replaced
-/+ resource "azurerm_resource_group" "rg" {
      ~ id       = "/subscriptions/7d559a72-xxxx-xxxx-xxxx-5ca5b14a25e7/resourceGroups/rg-1" -> (known after apply)
        location = "eastus"
      ~ name     = "rg-1" -> "rg-2" # forces replacement
      ~ tags     = {} -> (known after apply)
    }

  # module.rgs.azurerm_resource_group.rg[2] will be destroyed
  - resource "azurerm_resource_group" "rg" {
      - id       = "/subscriptions/7d559a72-xxxx-xxxx-xxxx-5ca5b14a25e7/resourceGroups/rg-2" -> null
      - location = "eastus" -> null
      - name     = "rg-2" -> null
      - tags     = {} -> null
    }
```

Makes complete sense that this is happening, however how can we have terraform not do this without having main.tf have three instances of the RG module by changing names ([]) to name (string).   Fingers crossed for some v12 magic!

**Comment by teamterraform** [comment]
Hello! :robot: 

We use GitHub issues for tracking bugs and enhancements rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by rohrerb** [comment]
https://discuss.hashicorp.com/t/help-with-index-list-logic/2278
