### ISSUE TITLE
remote-exec provisioner w/SSH fails to obtain Host/IP when creating Windows resource on vSphere

### ISSUE THREAD

**Issue by mijit** [hashicorp/terraform#2237]
I'm successfully creating Windows resources on an internal vSphere cluster. However, when I try to use SSH to provision, Terraform is not picking up the IP of the resource it just created. Example:

    PS> terraform apply
    vsphere_virtual_machine.app01: Creating...
      cpus:          "" => "4"
      datacenter:    "" => "DC1"
      folder:        "" => "Test Folder"
      host:          "" => "Dev Host"
      image:         "" => "Templates/MyTemplate"
      ip_address:    "" => "<computed>"
      linked_clone:  "" => "0"
      memory:        "" => "2048"
      name:          "" => "APP01"
      power_on:      "" => "1"
    vsphere_virtual_machine.app01: Provisioning with 'remote-exec'...
    vsphere_virtual_machine.app01 (remote-exec): Connecting to remote host via SSH...
    vsphere_virtual_machine.app01 (remote-exec):   Host:
    vsphere_virtual_machine.app01 (remote-exec):   User: Administrator
    vsphere_virtual_machine.app01 (remote-exec):   Password: true
    vsphere_virtual_machine.app01 (remote-exec):   Private key: false
    vsphere_virtual_machine.app01 (remote-exec):   SSH Agent: false
    vsphere_virtual_machine.app01 (remote-exec): Connecting to remote host via SSH...
    vsphere_virtual_machine.app01 (remote-exec):   Host:
    vsphere_virtual_machine.app01 (remote-exec):   User: Administrator
    vsphere_virtual_machine.app01 (remote-exec):   Password: true
    vsphere_virtual_machine.app01 (remote-exec):   Private key: false
    vsphere_virtual_machine.app01 (remote-exec):   SSH Agent: false

    ...repeat above until timeout...

    vsphere_virtual_machine.app01: Error: 1 error(s) occurred:

    * dial tcp :22: ConnectEx tcp: The requested address is not valid in its context.

The resource is created and I can log into it via console *and* SSH from the command line, but Terraform appears to not know its IP (note the empty "Host:" lines.) Note that I need to connect via IP in this case since DNS is not yet available.

Here is the connection and remote-exec block:

    connection {
        user = "Administrator"
        password = "${var.admin_password}"
    }
    provisioner "remote-exec" {
        inline = ["hostname"]
    }

Is Terraform capable of provisioning Windows resources with SSH? I've tried WinRM, but that has its own issues for my particular use case (it requires insecure settings and is too particular about AD/DNS for my needs.) I prefer to get SSH working. How can I go about troubleshooting this problem?

Thanks,
Michael

**Comment by svanharmelen** [comment]
You need to set the host parameter in you connection block to a variable pointing to the exported IP address.

So something like: `host = "${vsphere_virtual_machine.app01.ip_address}"`

**Comment by mijit** [comment]
Perfect, thanks! That works for me.

The docs say the default host value should be provided by the provider, so I'll assume the provider code is not doing something it should be, and will open an issue there.
