### ISSUE TITLE
CredentialRequiresARNError: credential type source_profile requires role_arn

### ISSUE THREAD

**Issue by scalp42** [hashicorp/terraform#22377]
As asked by @bflad in https://github.com/terraform-providers/terraform-provider-aws/issues/9617#issuecomment-519116122

aws-sdk-go needs to be bumped for the S3 remote state to work.

Thanks!

**Comment by jbardin** [comment]
Hi @scalp42,

This should be taken care of by #22381. Thanks!

**Comment by scalp42** [comment]
@jbardin we're still seeing the issue with `0.12.8`.

Do you know if it made it?

**Comment by scalp42** [comment]
Looks like reverting to Terraform `0.12.5` works again.
