### ISSUE TITLE
Multiple providers fail on refresh: Insufficient items for attribute

### ISSUE THREAD

**Issue by mzhaase** [hashicorp/terraform#22387]
All terraform versions since 0.12 suffer from a bug across providers where some resources refresh fail with 

`Error: insufficient items for attribute `

This has not been addressed for more than a month and makes upgrading to terraform 0.12 impossible for a lot of people.

Here are some example issues:

https://github.com/terraform-providers/terraform-provider-aws/issues/8982

https://github.com/terraform-providers/terraform-provider-aws/issues/9048

https://github.com/terraform-providers/terraform-provider-google/issues/4169

**Comment by rileykarson** [comment]
See https://github.com/terraform-providers/terraform-provider-google/issues/4169#issuecomment-520044805 for a breakdown in the Google provider.
