### ISSUE TITLE
Terraform Registry Pagination bug

### ISSUE THREAD

**Issue by bgelens** [hashicorp/terraform#22380]
I was implementing the pagination logic client side in a [PowerShell module](https://github.com/bgelens/TerraformRegistry) when I noticed there is a pagination error. The returned offset in the meta is not updated over 115.

![image](https://user-images.githubusercontent.com/10071039/62655488-6097b780-b962-11e9-8474-51acae1eba17.png)

As you can see, the returned meta is the same for offset 100 and 115 and it will be the same no matter how much I increase the offset

![image](https://user-images.githubusercontent.com/10071039/62655560-8cb33880-b962-11e9-9b1e-151275839ae7.png)

According to the [docs](https://www.terraform.io/docs/registry/api.html#pagination) and through observation by limiting the scope of the query by adding Namespace / Provider to the route, the returned meta should not contain a next_offset property when there is no more data to be retrieved.

Sorry if I posted this in the wrong repo. Unsure where to post it elsewhere

**Comment by xiaozhu36** [comment]
I also happened the same issue:  the  `NEXT` button does not work in the page : https://registry.terraform.io/browse/modules?offset=109&provider=aws and why the registry only show at most 109 modules
Even if I use curl https://registry.terraform.io/v1/modules?limit=100&offset=200&provider=aws and the results also same as the previous.

**Comment by paultyng** [comment]
Confirming this is a bug in the registry code base. The offset was misinterpreted as a page size in one of the code paths, a bug fix should be forthcoming.
