### ISSUE TITLE
Split on a single value should still return a list

### ISSUE THREAD

**Issue by mahileeb** [hashicorp/terraform#2240]
Currently calling split on a string with no delimiter returns a unmodified string. So the following fails

```
${formatlist("aws_instance.%s.id", split(",", "demo-rest-elb"))}
```

as split does not return a single element list to formatlist

**Comment by arr-dev** [comment]
:+1:

**Comment by zoltrain** [comment]
:+1: you have to put a separator at the end to get around it, but then you have a empty string floating around which isn't ideal.

**Comment by phinze** [comment]
Yep, just hit this myself when working on a config. Working on a fix now.

**Comment by mitchellh** [comment]
Going to assign this to you  @phinze since I think you have this.
