### ISSUE TITLE
Ignore changes is not working

### ISSUE THREAD

**Issue by SirWayne** [hashicorp/terraform#22412]
After the upgrade from terraform 0.11.x to 0.12.6 the ignore changes is not working anymore.
Before the upgrade it works fine. Currently we have a default ssl certifacte for the deployment. After the deployment we change the certifacte manually. After the next deployment the ssl certifacte is changed to the default one.

### Terraform Version
0.12.6

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "AppGateway" {
  ssl_certificate {
    name     = var.ssl_certificate_name
    data     = var.ssl_certificate_file
    password = var.ssl_certificate_password
  }

  lifecycle {
    ignore_changes = [
      ssl_certificate
    ]
  }
}
```

### Expected Behavior
Certifacte should not changed

### Actual Behavior
Certifacte is changed

**Comment by teamterraform** [comment]
Hi @SirWayne,

Ignoring a top-level attribute like `ssl_certificate` is expected to work, and that case shouldn't have changed from 0.11. It is possible you could share the output, as well as the logs from running `terraform plan`?

**Comment by SirWayne** [comment]
It's confusing, i see for `terraform plan` no changes for the ssl certficate and no diff. Maybe it's a issue in the mircrosoft terraform provider.

**Comment by jbardin** [comment]
Thanks @SirWayne,

If there is no plan or diff, it sounds like Terraform is working as expected. We'll close this out here and track the provider issue.

**Comment by SirWayne** [comment]
@jbardin did try the syntax, but then i see diffs.

```
  lifecycle {
    ignore_changes = [
      "ssl_certificate"
    ]
  }
```

Addtional i can try 

```
```
  lifecycle {
    ignore_changes = [
      ssl_certificate["data"]
    ]
  }
```
