### ISSUE TITLE
crash on `plan` when removing v11 remote state from v12 workspace

### ISSUE THREAD

**Issue by trr-aaronchu** [hashicorp/terraform#22419]
### Terraform Version

```
Terraform v0.12.6
+ provider.external v1.2.0
+ provider.google v2.12.0
+ provider.google-beta v2.12.0
```

### Terraform Configuration Files

```hcl
# removed the remote state shown here
data "terraform_remote_state" "pagerduty-REDACTED" {
  backend = "s3"

  config = {
    bucket     = "REDACTED"
    key        = "encrypted/configs/terraform/state/main/REDACTED.tfstate"
    region     = "us-east-1"
    role_arn   = "REDACTED"
    kms_key_id = "REDACTED"
    encrypt    = true
  }
}
```

### Expected Behavior
should have just ignored the remote state, as it was no longer defined.

### Actual Behavior
crashed

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
Found this while trying to get rid of this error, and noticed that I didn't need the remote state anyway:
`err: rpc error: code = Unavailable desc = transport is closing` 

[crash_files.tar.gz](https://github.com/hashicorp/terraform/files/3488048/crash_files.tar.gz)

**Comment by teamterraform** [comment]
Hi @trr-aaronchu,

I'm not sure I understand where the remote state comes into play here.
From the logs, it appears that this is a crash in the google provider. If that's the only relevant part of the provided files, we can move the issue to the google provider repo.

**Comment by trr-aaronchu** [comment]
sure, thanks for checking it out. It was just that the crash did not happen before removing the remote state. However, the `err: rpc error: code = Unavailable desc = transport is closing` errors were happening even with the remote state in there.
