### ISSUE TITLE
provider/dme: no error, but record not updated

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/terraform#2241]
Whenever an AWS instance gets destroyed/created, the attached DME DNS record is updated to the new public IP. However, I've noticed that the new IP does not show up in the DME control panel and the old (non-existing) IP is still listed.

Terraform does not produce any errors and happily returns the new IP in the `dme_record` attributes.

**Comment by mitchellh** [comment]
Can you please report this upstream to github.com/soniah/dnsmadeeasy ?

I checked locally and it looks like the API client just isn't making the change!
