### ISSUE TITLE
DDoS protection plan unable to be modified or deleted after creation

### ISSUE THREAD

**Issue by mashbynz** [hashicorp/terraform#22421]
### Terraform Version
Terraform v0.12.5
```
provider "azurerm" {
  version = "1.28"
}
```

### Affected Resource(s)

* `DDoS Protection Plan`

### Terraform Configuration Files

The "name" and "tags" parameters are supplied by the Terraform Label module by Cloudposse: https://github.com/cloudposse/terraform-terraform-label

```
resource "azurerm_network_ddos_protection_plan" "default" {
  name                = module.ddos_label.id
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
  tags                = module.ddos_label.tags
}
```

### Expected Behavior
DDoS Protection Plan should have been deleted

### Actual Behavior
DDOS Protection Plan was not deleted

### Steps to Reproduce

1. `terraform apply`
terraform plan output shows resource to be deleted:
```
  # module.ase_vnet.azurerm_network_ddos_protection_plan.default will be destroyed
  - resource "azurerm_network_ddos_protection_plan" "default" {
      - id                  = "/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/prodsharedservices2-rg/providers/Microsoft.Network/ddosProtectionPlans/prodsharedservices2-ddos" -> null
      - location            = "australiasoutheast" -> null
      - resource_group_name = "prodsharedservices2-rg" -> null
      - tags                = {} -> null
    }
```

Error message received:
```
Error: Error deleting DDoS Protection Plan "" (Resource Group "prodsharedservices2-rg"): network.DdosProtectionPlansClient#Delete: Failure sending request: StatusCode=400  -- Original Error: Code="UnsupportedResourceOperation" Message="The resource type 'ddosProtectionPlans' does not support this operation."
```

**Comment by soydantaylor** [comment]
I was able to reproduce this

**Comment by mashbynz** [comment]
> 
> 
> I was able to reproduce this

This also applies to any resources the DDoS protection plan is associated with i.e. after it is associated with a VNet the VNet/subnets/NSGs/Route Tables/Public IPs etc. are unable to be modified at all
