### ISSUE TITLE
New Provider Creation - Help needed

### ISSUE THREAD

**Issue by adi658** [hashicorp/terraform#22435]
Hello Team,

I am new to writing your own providers in terraform. I have one doubt here.

I have been following this link
https://www.terraform.io/docs/extend/writing-custom-providers.html

In main.tf they have only mentioned 
```
resource "example_server" "my-server" {
  address = "1.2.3.4"
}
```
whereas, if we see providers like azure, aws, etc. there is a provider block defined. 

My question here is... Is it ok to skip the provider block? If yes, how does it work? If no, then how is it working. Can someone please guide me through this

**Comment by teamterraform** [comment]
Hello @adi658, for most real world use cases you will want to configure a provider block. However it is not technically required. All resources/datasources for actual providers will carry a provider name prefix such as `aws_vpc`. The provider is defaulted/inferred from that to `aws`. Terraform will download the latest release of the provider, and assuming the provider has no required provider level config, then in theory terraform can operate without every explicitly parsing a provider block.

This however is not the recommended practice, there are things such as regions and credentials that you should explicitly configure, its also better to pin at least a major release of a provider, so you can avoid breaking changes until you are ready. More information on that can be found [here](https://www.terraform.io/docs/configuration/providers.html).

In the future please consult the [development mailing list](https://groups.google.com/forum/#!forum/terraform-developers) for development questions. We also have a [discourse](https://discuss.hashicorp.com/) for practitioner questions, there may be a discourse for development questions in the future as well. Thank you for all your time and contributions.
