### ISSUE TITLE
Support manually triggered create_before_destroy resource replacement

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#2245]
Currently the way to manually trigger resource replacement is `terraform taint`, but the the internal mechanics of the "tainted" concept are such that the destroys of these nodes are not affected by the `create_before_destroy` option.

We should do one of the following:
- Respect CBD for tainted nodes
- Provide some other mechanism for manual replacement that can respect CBD

Pinging @mitchellh for thoughts on whether there would be any problem including tainted nodes in the CBD transform.

**Comment by phinze** [comment]
This is coming out of the last two comments in #502

**Comment by nevir** [comment]
I think your comment over there can help guide:

> The "tainted" concept indicates "this resource cannot perform the service required of it" - it's used by Terraform internally for failure scenarios like when provisioners error out.

That'd seem to indicate to me that you want a second mechanism

Maybe a `terraform apply --refresh aws_instance.foo.* --refresh aws_thinger.abc123`

**Comment by kcormier** [comment]
Is there any update on this?

**Comment by brandonhilkert** [comment]
I'd love to be able to use this without changing a resource attribute. Any thoughts on whether this is something that might be implemented?

**Comment by Mongey** [comment]
> Respect CBD for tainted nodes

:pray:
