### ISSUE TITLE
Creating resources with for_each loop should show error instead of panic crash if `for_each` given a list instead of `set`

### ISSUE THREAD

**Issue by alxkolm** [hashicorp/terraform#22463]
### Terraform Version

```
Terraform v0.12.6
+ provider.rabbitmq v1.1.0
```

### Terraform Configuration Files
```hcl
provider "rabbitmq" {
  endpoint = "http://example.com"
  username = "username"
  password = "123"
}


resource "rabbitmq_queue" "queues" {
  for_each = ["a", "b"]

  name  = each.value
  vhost = "/"

  settings {
    durable     = true
    auto_delete = false
  }
}


```

### Debug Output
https://gist.github.com/alxkolm/d7c80e3c286e0d070ba21320a524d4d2
### Crash Output
https://gist.github.com/alxkolm/7c6d1e6d082f7f1576b0452809972b70
### Expected Behavior
At least, terraform should show error that value passed to `for_each` argument should be `set` not a `list`

### Actual Behavior
Terraform is crashed with panic.

### Steps to Reproduce
```
terraform init
terraform plan
```
### Additional Context
Nothing special

**Comment by pselle** [comment]
@alxkolm This has been fixed in master, and we're leaving https://github.com/hashicorp/terraform/issues/22347 open until it has been released, but this will be fixed on 0.12.7.
