### ISSUE TITLE
Shorten the terraform plan output to only changes

### ISSUE THREAD

**Issue by katlimruiz** [hashicorp/terraform#22479]
When doing the `terraform plan` command, a switch can be added to minify the output.

Today:
```
  # module.stg.azurerm_app_service.myaps will be updated in-place
  ~ resource "azurerm_app_service" "myaps" {
        app_service_plan_id            = "/subscriptions/xxxx/myaps"
      ~ app_settings                   = {
            "APPINSIGHTS_INSTRUMENTATIONKEY" = "xxx"
            "ASPNETCORE_ENVIRONMENT"         = "Staging"
          - "MSDEPLOY_RENAME_LOCKED_FILES"   = "1" -> null
            "WEBSITE_RUN_FROM_PACKAGE"       = "0"
        }
        client_affinity_enabled        = true
        client_cert_enabled            = false
        default_site_hostname          = "myaps.azurewebsites.net"
        enabled                        = true
        https_only                     = false
```
Proposed:
```
  # module.stg.azurerm_app_service.myaps will be updated in-place
  ~ resource "azurerm_app_service" "myaps" {
      ~ app_settings                   = {
          - "MSDEPLOY_RENAME_LOCKED_FILES"   = "1" -> null
        }
```

**Comment by rudolphjacksonm** [comment]
We would like to see this feature as well. Currently the default output of `azurerm_kubernetes_cluster` shows the credentials for the clusterAdmin. This attribute doesn't change, nor do we ever want this displayed in our pipelines, as that's a massive security vulnerability. Anyone could modify their kubeconfig, paste the creds in there, and  immediately have admin access to the cluster.

I'm not sure if that persists in the state as well but just thought that's worth mentioning.

**Comment by temujin9** [comment]
Duplicates #21639, which has WIP in #22458.

**Comment by buec011** [comment]
> Duplicates #21639, which has WIP in #22458.

And it looks like  #21639 duplicates #10507

**Comment by scottb-isp** [comment]
let's get this in there, man! Try making a change to AWS ElasticBeanstalk and you get 5000 lines of things with only 1 or 2 differences, very hard to use `terraform plan` to assess impact of a change.

**Comment by surendarkaniops** [comment]
when using data "archive_file" resource for huge number files, jenkins job also got stuck due to output

**Comment by apparentlymart** [comment]
Hi all!

What was requested here has been the behavior of `terraform plan` for quite some time now, so I'm going to close this. Unfortunately it was long enough ago that I don't recall which version it was changed in, but the relevant PR was https://github.com/hashicorp/terraform/pull/26187.

Thanks for suggesting this and sorry we missed it while closing out after the change!
