### ISSUE TITLE
bug: (severe) multi-line comment block not parsed correctly

### ISSUE THREAD

**Issue by neurogenesis** [hashicorp/terraform#2248]
With terraform version 0.5.3, we just ran into an issue where a multi-line block comment with /* ... */ was parsed incorrectly, resulting in the planned removal of a number of AWS resources (everything following that block).

The following was near the top of the configuration file:

```
...
## managed policies not yet supported
/*
resource "aws_iam_policy" "ec2-bootstrap-cloudinit" {
  name = "ec2-bootstrap-cloudinit"
  path = "/"
  description = "Policy for system provisioning via cloud-init (access to bootstrap S3 bucket)"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject"
      ],
      "Resource": [
        "arn:aws:s3:::xxx-bootstrap/*"
      ]
    }
  ]
}
EOF
}
*/
...
```

Our best guess is that the parser may have incorrectly processed the "<<EOF" directive, commenting out the rest of the file. What's odd is that this didn't seem to generate an invalid configuration file syntax.

Commenting each line with "#" instead avoids the problem.

We also noticed that EIPs are released when destroyed (instead of disassociated and kept in the local pool). This could be problematic for 3rd-party white-listed public IPs, since there's no way to re-associate a public IP once it's been released back to AWS. If it were disassociated in stead of released, customers would have the option of re-associating the same IP in the event of an accidental resource removal. I'll file a separate feature request for that.

**Comment by mitchellh** [comment]
The issue is that you have a nested `/*` in there (from the IAM policy). So the comment resulted to the end of the file. I'm not sure how other comment-able languages handle this. Let me compile some C and find out. :)

**Comment by neurogenesis** [comment]
Ah, so quote parsing isn't togged off while reading quoted strings. Makes sense. Hoping that the fix isn't to use backticks / escape characters inside quotes. We should be able to read files or in-line blocks that are more or less copies from AWS policy generators or CF templates.

**Comment by sparkprime** [comment]
A */ in a string should not terminate the comment.

**Comment by mitchellh** [comment]
Okay, I've confirmed that C allows (but warns) when a block comment starts within a comment, even within a string:

```
what → gcc main.c 
main.c:3:21: warning: '/*' within block comment [-Wcomment]
    char *foo = "bar/*";
                    ^
1 warning generated.
```

And if you end a comment in a string, it actually ends:

```
what → gcc main.c
main.c:3:23: warning: missing terminating '"' character [-Winvalid-pp-token]
    char *foo = "bar*/";
                      ^
main.c:3:23: error: expected expression
1 warning and 1 error generated.
```

We'll copy this behavior upstream.

**Comment by mitchellh** [comment]
Copied C's behavior here: https://github.com/hashicorp/hcl/commit/681623f4e1a4b71474d0ba62c6296a938f7576fc

**Comment by mitchellh** [comment]
Also fixed an issue where multi-line comments were terminated with EOF, that should be a syntax error: https://github.com/hashicorp/hcl/commit/54864211433d45cb780682431585b3e573b49e4a
