### ISSUE TITLE
Terraform 0.11.* failed before resolve implicit dependencies

### ISSUE THREAD

**Issue by Nmishin** [hashicorp/terraform#22483]
### Terraform Version
```
Terraform v0.11.7
+ provider.consul v1.0.0
+ provider.external v1.0.0
+ provider.google v1.12.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0
+ provider.vault v1.1.0
```
Also terraform v0.11.14 was tested.

### Terraform Configuration Files
```
# Vault ACL policy 
#
resource "vault_policy" "vault-auth" {
    name        = "vault-auth"
    policy      = <<_EOT
        path "secret/approle-acl/*" {
            capabilities = ["read", "list"]
        }
        path "auth/approle/role/*" {
            capabilities = ["update"]
        }
    _EOT
}

resource "vault_generic_secret" "approle-vault-auth" {
    path        = "auth/approle/role/vault-auth"
    data_json   = <<_EOT
        {
            "bind_secret_id":   false,
            "bound_cidr_list":  "127.0.0.0/24",
            "policies":         "${vault_policy.vault-auth.name}",
            "period":           1200
        }
    _EOT
}

data "vault_generic_secret" "vault-auth-approle-id" {
    path = "${vault_generic_secret.approle-vault-auth.path}/role-id"
}

resource "consul_keys" "vault-auth-approle-id" {
    key {
        path    = "vault-auth/vault-approle-id"
        value   = "${lookup(data.vault_generic_secret.vault-auth-approle-id.data, "role_id")}"
        delete  = "true"
    }
}
```

### Debug Output
```
Error: Error refreshing state: 1 error(s) occurred:

module.app_roles.data.vault_generic_secret.vault-auth-approle-id: 1 error(s) occurred:

module.app_roles.data.vault_generic_secret.vault-auth-approle-id: data.vault_generic_secret.vault-auth-approle-id: No secret found at "auth/approle/role/vault-auth/role-id"
```

### Expected Behavior
Terraform generate policy and approle in Vault, read it and copy approle-id to the Consul

### Actual Behavior
Terraform fails in "refresh" step

### Steps to Reproduce
Login to Vault and disable approle auth method:
vault auth disable approle
terraform init
terraform apply
Terraform will fail.
Login to Vault and enable approle auth method:
vault auth enable approle
terraform apply
terraform must execute "resource "vault_policy" "vault-auth"" but don't do this and fails.
terraform 0.9.4 works as expected

### Additional Context
We used this piece of code with Terraform 0.9.4 and it works as expected.
Add explicit dependencies helps:
```
data "vault_generic_secret" "vault-auth-approle-id" {
    depends_on = ["vault_policy.vault-auth"]
    path = "${vault_generic_secret.approle-vault-auth.path}/role-id"
}
```

**Comment by jbardin** [comment]
Hi @Nmishin,

I'm not familiar with the current internals of the vault provider, but the usual case in situations like these is that while the resource was technically created, there may be some eventual consistency that can cause an immediate read from a data source fail. This is something he provider usually has to try and remedy, if it's possible at all.

There however is usually no reason to use a data source for a resource that is already in the configuration. Is there a particular reason you have a `vault_generic_secret` data source when you can reference the resource directly?

**Comment by Nmishin** [comment]
Hi @jbardin,

Thank you for your answer, I tried to investigate this and seems the main issue here - resource "vault_policy" "vault-auth" was triggered and added to the terraform state as "done", but in reality did nothing.

We use `vault_generic_secret` because we want to create implicit dependencies here. 

I found a "workaround" for this - need to delete this resource from terraform state and it will be triggered one more time:

`terraform state rm vault_policy.vault-auth`

**Comment by jbardin** [comment]
Thanks for the follow up @hashicorp/community 

It sounds like something went wrong in the vault provider (or vault), and the resource was recorded in state even though creation failed. I'm not sure what you mean by "implicit dependencies", as the dependencies are still there, it just requires a more complex process to get the values.

If this is something that can be replicated, I would suggest opening an issue with the vault provider.

Thanks!
