### ISSUE TITLE
FinalDBSnapshotIdentifier invalid format prevents destroy

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/terraform#2250]
```
* InvalidParameterValue: The parameter FinalDBSnapshotIdentifier is not a valid identifier.
Identifiers must begin with a letter; must contain only ASCII letters, digits,
and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
```

I indeed used underscores. However, it seems I'm stuck now and can't destroy this resource anymore. I changed both the `*.tf` file, and the `*.tfstate` file, but the error persists.

The name I used was `database_backup_terraform_destroy`. I changed the underscores with dashes, but still no go. I also tried just a single worded name, but I can't seem to get the destroy through.

*edit* this might be due to the tfstate being stored in Atlas. I think this was switched from git-based to being a remote state repo, so that might cause my changes not to be picked up.

Question remains, should this restriction be enforced on creation instead of deletion?

**Comment by phinze** [comment]
Arg yeah these delayed validations are tough. This inspired me to add the schema validation support to be able to implement a check like this. PR incoming. :grinning:
