### ISSUE TITLE
No output form aws_lb

### ISSUE THREAD

**Issue by natasha-par98** [hashicorp/terraform#22503]
### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.23.0

```

### Terraform Configuration Files

main.tf
```hcl
resource "aws_security_group" "alb-security-group" {
  name        = "alb-security-group"
  vpc_id = var.vpc_id

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_lb" "alb" {
  security_groups = [aws_security_group.alb-security-group.id]
  subnets = var.alb_subnets
}

resource "aws_lb_target_group" "alb-target-group" {
  name     = "alb-target-group"
  port     = 80
  protocol = "HTTP"
  vpc_id   = var.vpc_id
  stickiness {
    type = "lb_cookie"
    cookie_duration = 1200
  }

  health_check {
    path = "/check"
    port = 80
  }
}

resource "aws_lb_listener" "application-load-balancer-listener-http" {
  load_balancer_arn = aws_lb.alb.arn
  port              = "80"
  protocol          = "HTTP"

  default_action {
    target_group_arn = aws_lb_target_group.alb-target-group.arn
    type             = "forward"
  }
}
```

outputs.tf

```hcl
output "alb_id" {
  value = aws_lb.alb.id
}
output "alb-security-group_id" {
  value = aws_security_group.alb-security-group.id
}
output "alb-target-group_arn" {
  value = aws_lb_target_group.alb-target-group.arn
}
```

### Expected Behavior

The module supposed to output three values:
aws_lb.alb.id
aws_security_group.alb-security-group.id
aws_lb_target_group.alb-target-group.arn

### Actual Behavior

The module creates an application load balancer without any errors, I log in to the AWS console and can confirm that everything has been created and working fine but the module outputs nothing.

**Comment by jbardin** [comment]
Hi @natasha-par98,

Can you share how you are using the above module, and how you are referencing the outputs? It seems unlikely that 3 separate resources are all failing to evaluate in the outputs, so I'm not sure what behavior you're actually seeing.

Thanks

**Comment by natasha-ntsh** [comment]
https://github.com/natasha-ntsh/test.git

**Comment by jbardin** [comment]
Thanks for the extra configuration @natasha-par98, but I don't see where you are referencing the outputs of the module in the configuration. Can you show an example of what is not working?

**Comment by natasha-ntsh** [comment]
Are you saying that I have to reference to an output in order to make a module outputting anything?

**Comment by jbardin** [comment]
Thanks for the walkthrough @natasha-ntsh,

It looks like the issue is that the `alb` module has no outputs, which is why you don't see any outputs when that module is applied. The remote state referencing that module confirms that those outputs don't exist.

You must define the outputs you want to reference remotely in the root module.

From [Output Values](https://www.terraform.io/docs/configuration/outputs.html)

> Output values are like the return values of a Terraform module, and have several uses:
> 
> - A child module can use outputs to expose a subset of its resource attributes to a parent module.
> - A root module can use outputs to print certain values in the CLI output after running terraform apply.
> - When using remote state, root module outputs can be accessed by other configurations via a terraform_remote_state data source.

**Comment by natasha-ntsh** [comment]
https://github.com/natasha-ntsh/test/blob/master/modules/alb/outputs.tf

The outputs are defined the same way in every module but only the elb doesn't return anything.

**Comment by jbardin** [comment]
That is not the what you're referencing in the remote state. The example above created the state from `live_envs/stage/alb` which has no outputs.

**Comment by natasha-ntsh** [comment]
How could I not see this... Thanks a lot!
