### ISSUE TITLE
azurerm backend state and service principle scope issue  

### ISSUE THREAD

**Issue by qmarc** [hashicorp/terraform#22521]
### Terraform Version
```
Terraform v0.12.6
provider.azurerm v1.32.1
```

### Terraform Configuration Files
```hcl
backend "azurerm" {
  subscription_id      = "<ARM_SUBSCRIPTION_ID>"
  resource_group_name  = "terraform-state-rg"
  storage_account_name = "tfstatestorage"
  key                  = "azure/stg/terraform.tfstate"
  container_name       = "<my-container-name>"
}
```

### Expected Behavior
Using a pre-created service principle which is applied at the Storage Account's Container level with the `Storage Blob Data Contributor` Role applied the Service Principle should be able to read/write/delete blobs in the Container.

### Actual Behavior
An error is thrown in the azurerm backend:
```
Error: Error inspecting states in the "azurerm" backend:
    Error retrieving keys for Storage Account "tfstatestorage": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<ARM_CLIENT_ID>' with object id '<OBJECT_ID>' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/<ARM_SUBSCRIPTION_ID>/resourceGroups/terraform-state-rg/providers/Microsoft.Storage/storageAccounts/tfstatestorage' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
 It appears that in the [arm_client.go](https://github.com/hashicorp/terraform/blob/master/backend/remote-state/azure/arm_client.go#L136) codebase there is a lookup of the Storage Account Keys, however if you use sas token instead it jumps out of that function `getBlobClient()` earlier. It seems incorrect that a Service Principle scoped for accessibility at the Container level should need to access the Storage Account Keys which provides _total access_.

Is this a bug?

**Comment by haodeon** [comment]
In my testing terraform does not support Azure AD authenticated blob storage access. The role "Storage Blob Data Contributor" leverages the new Azure AD method of accessing blob storage.

The minimum role required is "Reader & Data Access" which allows for the retrieving of keys.

**Comment by qmarc** [comment]
Thanks for your response @haodeon for now the approach we have decided to go with is to create a [custom role](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/roles-permissions-security#limiting-access-to-monitoring-related-storage-accounts) which provides access to the keys and read-only access to the storage account after obtaining it. We then apply that Role to the Service Principle.

Being as this appears to be more of an Azure limitation/expectation rather than with the Terraform module I am going to close this one.
