### ISSUE TITLE
Crash when passing module output to for_each in module input via set(string)

### ISSUE THREAD

**Issue by matalo33** [hashicorp/terraform#22528]
### Terraform Version
```
Terraform v0.12.6
```

### Terraform Configuration Files

main.tf
```hcl
module "module1" {
  source = "./module1"
}

module "module2" {
  source = "./module2"

  some_strings = [
    module.module1.a_string,
  ]
}
```

module1/main.tf
```hcl
resource "null_resource" "null" {}

output "a_string" {
  value = null_resource.null.id
}
```

module2/main.tf
```hcl
variable "some_strings" {
  type = set(string)
}

resource "null_resource" "null" {
  for_each = var.some_strings
}
```

### Crash Output
https://gist.github.com/matalo33/b536b4644f84d0cea1beb5ee2f901a09

### Expected Behavior
This reproduces a bug we experienced in another project. The output of a newly instantiated module is being passed via a set to a for_each in another module. We expected the resource to be created as expected.

### Actual Behavior
terraform crash

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by m-wynn** [comment]
I have this issue simply with:
```
resource "null_resource" "null" {
  for_each = [
    "string1",
    "string2",
  ]
  name = "${each}something"
}
```

**Comment by carcuevas** [comment]
I can confirm that still present in 0.12.7...  Thanks guys for looking a it ;-)

**Comment by pselle** [comment]
Hello! This is fixed testing on the latest version of Terraform (0.12.20); relying on the output of another module in your `for_each` argument _will_ result in an error that you are relying on some unknown values, and will need to use `-target` to apply module.module1 before you can complete a `terraform apply`. Thank you for the report!
