### ISSUE TITLE
Crash on `panic: not a string`

### ISSUE THREAD

**Issue by yujunz** [hashicorp/terraform#22529]
### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.24.0
```

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "~> 2.0"
  region  = "us-east-1"
}

locals {
  s3_buckets = [
    "aws-us-east-1"
  ]
}

data "aws_s3_bucket" "this" {
  for_each = local.s3_buckets
  bucket   = each.value
}

data "aws_iam_policy_document" "s3-buckets-fullaccess-policy" {
  statement {
    actions = ["s3:*"]
    resources = concat(
      data.aws_s3_bucket.*.arn,
      formatlist("%s/*", data.aws_s3_bucket.*.arn)
    )
  }
}
```

### Crash Output

https://gist.github.com/yujunz/2da9465bdba65bd8b46da096bc93b736

### Expected Behavior

Prompt for syntax error on `      data.aws_s3_bucket.*.arn,`

### Actual Behavior

Crashed

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by teamterraform** [comment]
This looks like a known issue https://github.com/hashicorp/terraform/issues/22305, which is fixed in master and will go out in the 0.12.7 release of Terraform. Thank you for the report!
