### ISSUE TITLE
Support for configuring http backend using environment variables

### ISSUE THREAD

**Issue by jbloxsome** [hashicorp/terraform#22527]
### Current Terraform Version

```
Terraform v0.12.3

Your version of Terraform is out of date! The latest version
is 0.12.6. You can update by downloading from www.terraform.io/downloads.html

```

### Use-cases

Currently, when using an http remote backend, users must configure access details in code i.e
```
terraform {
  backend "http" {
    address = "http://myrest.api.com/foo"
    lock_address = "http://myrest.api.com/foo"
    unlock_address = "http://myrest.api.com/foo"
    username = "user"
    password = "secret"
  }
}
```
Support for environment variable configuration would allow users to remove sensitive information 
such as passwords from the HCL code.
### Proposal

Add support for configuring access to an http remote backend using environment variables e.g.

HTTP_BACKEND_URL
HTTP_BACKEND_USERNAME
HTTP_BACKEND_PASSWORD

**Comment by nicholasklick** [comment]
@pkolyvas This can be closed I assume since it was resolved by https://github.com/hashicorp/terraform/pull/25439

**Comment by pkolyvas** [comment]
Thanks @nicholasklick !
