### ISSUE TITLE
Add "else" support in for loop

### ISSUE THREAD

**Issue by splashx** [hashicorp/terraform#22533]
### Current Terraform Version
```
$ terraform -v
Terraform v0.12.6
```

### Use-cases

I have the following for loop:

```hcl2
....
  metadata = "merge(
                  var.some_metadata,
                  {
                    for key, value in var.some_metadata : key => "${value},leader"
                    if key == "groups" && count.index == 0 && var.cluster
                  },
                  {
                    for key, value in var.some_metadata : key => "${value},follower"
                    if key == "groups" && count.index > 0 && var.cluster
                  }
                )"
```

When `var.cluster == true`, I would like to append `,leader` if it's first object (think VM) - and the other objects to have `,follower` appended - all that done to the `metadata` key `groups`.

### Attempted Solutions

No attempted solution since `else if` statement is not supported nor mentioned in the the docs.

### Proposal

It would be great if that block could be written as:

```hcl2
....
  metadata = "merge(
                  var.some_metadata,
                  {
                    for key, value in var.some_metadata : key => "${value},leader"
                    if key == "groups" && count.index == 0 && var.cluster
                    else : key => "${value},follower"
                    if  key == "groups" && count.index > 0 && var.cluster
                  }
                )"
```

This syntax could also pave the way for a `else` only situation (where the last `if` would simply be omitted).

### References

None

**Comment by teamterraform** [comment]
Hi @splashx! Thanks for sharing this use-case.

It looks like your goal here is to choose between two possible results depending on some condition, but in either case to produce a value. If so, the existing conditional operator could do it:

```
{
  for key, value in var.some_metadata : key => "${value},${count.index > 0 ? "follower", "leader"}"
  if key == "groups" && var.cluster
}
```

What we did here is split the condition you gave into two separate parts: the conditions that choose whether an element should be generated _at all_ belong in the `if` clause, while the conditions that choose between the two different outcomes belong in the conditional part of the result value expression.

The `if` clause on a `for` expression exists to allow you to selectively exclude certain input elements from being considered. In situations where you want to produce an output element in any case but the value of that element varies by some condition, a conditional expression is sufficient.

Does that address the use-case you were trying to meet here? If we misunderstood what you were trying to achieve, please let us know! Thanks again for sharing the use-case.

**Comment by splashx** [comment]
Hey there.

Yes, that would work also - but only because I have two conditional states (`== 0 ` and `>0`) - if there would be a third condition, we would not be able to solve it with ternary. 

I'm closing this as "if / else" per se can be handled as you wrote. 

Cheers!
