### ISSUE TITLE
Accept variables in lifecycle attributes

### ISSUE THREAD

**Issue by gtirloni** [hashicorp/terraform#22546]
### Use-cases

The end goal is to allow us to programmatically override a list of attributes that should be ignored. 

For instance, an AutoScaling Group is defined with a Launch Configuration that ignores changes to the image_id attribute. Later, during a proper maintenance window, we want to tell the aws_launch_configuration resource that the ignore_changes list should be empty (so it picks up the image_id change).

### Attempted Solutions

```hcl
variable "ignore_ami_changes" {
  description = "If AMI changes should be ignored"
  type        = bool
  default     = true
}

resource "aws_launch_configuration" "default" {
  lifecycle {
     ignore_changes = var.ignore_ami_changes ? [image_id] : []
  }
}
```

The error:

```
Error: Invalid expression
on main.tf line 14, in resource "aws_launch_configuration" "default":
14:     ignore_changes = local.ignore_ami_changes
A static list expression is required.
```

### Proposal

Allow lifecycle attributes to accept variables (interpolation)

### References

- #3116 (closed for comments since May 2017)

**Comment by teamterraform** [comment]
Hi @gtirloni!

As you saw, this use-case is already covered by #3116, so we're going to close this one. As noted in the other one, it was locked because all of the required information about the problem to be solved has already been gathered and so no further discussion is necessary.
