### ISSUE TITLE
`terraform import ...` fails when all resources use the "google-beta" provider (as opposed to "google") even with `-provider=google-beta`

### ISSUE THREAD

**Issue by cpick** [hashicorp/terraform#22564]
### Terraform Version

```
$ terraform -v
Terraform v0.12.6
+ provider.google-beta v2.13.0
```

### Terraform Configuration Files

```hcl
variable "project_id" {
}

terraform {
  required_version = "~> 0.12"
}

provider "google-beta" {
  version = "~> 2.8"
  project = var.project_id
}

resource "google_storage_bucket" "test" {
  provider = "google-beta"
  name     = "foo-bar-baz-test"
}
```

### Debug Output

https://gist.github.com/cpick/163f3519b4fe4e89035ced78ff3987aa

### Expected Behavior

`terraform import -provider=google-beta ...` should succeed even if all resources are using the "google-beta" provider (as opposed to the "google" provider).

### Actual Behavior

```sh
$ terraform import -provider=google-beta google_storage_bucket.test foo-bar-baz-test
google_storage_bucket.test: Importing from ID "foo-bar-baz-test"...
google_storage_bucket.test: Import prepared!
  Prepared google_storage_bucket for import
google_storage_bucket.test: Refreshing state... [id=foo-bar-baz-test]

Error: unknown provider "google"
```

### Additional Context

If at least one resource is created using the "google" provider (as opposed to "google-beta") and `terraform init` is re-run then subsequent `terraform import ...` commands succeed. The problem only exists if there are no resources managed by the "google" provider.

### References

- #22170 I previously reported this issue and got the helpful suggestion to try `-provider=google-beta`.  Unfortunately, while that does allow the import to proceed a bit further, a similar error is hit later on as demonstrated by the example in this ticket.  There was also at least one other user ( @nauris-sadovskis ) who is also affected.  Unfortunately, that ticket was locked by hashibot before the revised reproduction steps could be investigated so I've opened this new issue.

**Comment by mildwonkey** [comment]
Hi ! This was fixed in #22855, which will be in the next terraform release (likely not before 2 weeks from now). If you want to verify the fix now, you can build terraform from master. Thanks for reporting this!
