### ISSUE TITLE
aws' region don't seem to work well with module output

### ISSUE THREAD

**Issue by aerostitch** [hashicorp/terraform#2256]
Hi,

I was testing the modules output to setup my credentials and it seems that unlike the access_key and secret_key attributes, the region attribute don't accept module output as input.
I keep having:
```
$ terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* 1 error(s) occurred:

* Not a valid region: ${module.common.default_region}
```

part of the current folder loading the module:
```
module "common" {
  source = "../00-common/"
}
provider "aws" {
  access_key = "${module.common.access_key}"
  secret_key = "${module.common.secret_key}"
  region     = "${module.common.default_region}"
}
```

Content of my common module:
```
output "access_key" {
  value = "POTATO"
}
output "secret_key" {
  value = "BANANA"
}
output "default_region" {
  value = "us-east-1"
}
```

If I just replace the line:
```region     = "${module.common.default_region}" ```
by
```region = "us-east-1"```
it works well.

I tried to ```terraform get -u``` and to remove the entire .terraform folder before ```terraform get```. Checking the terraform module in this folder, it has the output defined, so I don't get it.

It looks almost like the module output was not loaded before reaching the ValidateRegion function in builtin/providers/aws/config.go

Terraform version 0.5.2.

Is it expected?

Thanks
Joseph

**Comment by mitchellh** [comment]
This is fixed now
