### ISSUE TITLE
Allow --target to accept module path without a resource

### ISSUE THREAD

**Issue by tyd** [hashicorp/terraform#22570]
### Current Terraform Version

```
Terraform v0.12.6
```

### Use-cases

I think it would be useful to be able to use ```--target``` to specify a module and then have all resources under that module filtered for plan/apply. 

### Attempted Solutions

```terraform plan --target=moduleName```

### Proposal

The documentation for [resource addressing ](https://www.terraform.io/docs/internals/resource-addressing.html) already includes modules as follows:

```[module path][resource spec]```

My proposal is to make the second part for ```[resource spec]``` optional so it will work with only a module path:

```[module path]```

### References

https://github.com/hashicorp/terraform/issues/2182 might accomplish the same thing if it gets implemented.

**Comment by teamterraform** [comment]
Hi @tyd!

As described on the Resource Addressing docs page, the syntax for addressing a module is to prefix its name with `module.`, so the correct way to write your example there would be as follows:

```
terraform plan --target=module.moduleName
```

This `module.` prefix is how Terraform can tell the difference between a module address and a resource address. If you use that prefix, you should hopefully find that this already works as you wanted. Please give that a try and let us know! Thanks.

**Comment by tyd** [comment]
@teamterraform that works! Thanks, totally missed in the docs that you can use it this way.
