### ISSUE TITLE
aws_security_group change causes destroy create cycle

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#2257]
I don't understand why changing the number of security groups causes the machine to get destroy and rebuilt?

```
  security_groups.#:                         "2" => "3" (forces new resource)
    security_groups.2071441191:                "" => "sg-a77d9dc3" (forces new resource)
    security_groups.2192028676:                "sg-0838d86c" => "sg-0838d86c" (forces new resource)
    security_groups.4056170280:                "sg-a17d9dc5" => "sg-a17d9dc5" (forces new resource)
```

**Comment by phinze** [comment]
Hey there - sorry for the confusion. Security group updating is only supported in VPC (this is an AWS limitation), and the `security_groups` attribute . If you switch to using [`vpc_security_group_ids`](https://terraform.io/docs/providers/aws/r/instance.html#vpc_security_group_ids) you'll get the behavior you expect.
