### ISSUE TITLE
for_each causes terraform crash when creating null_resource 

### ISSUE THREAD

**Issue by muroj** [hashicorp/terraform#22580]
# Terraform Version
```
Terraform v0.12.7
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
variable "subnet_id" {
    description = "IP Subnet specified in CIDR notation (e.g. 10.20.102.0/24) "
}

locals {
  guest_ips = [for i in range(1,255) : cidrhost(var.subnet_id, i)]
}

resource "null_resource" "guest_ips" {
    #for_each = toset(
    #    [for i in range(1,255) : cidrhost("var.subnet_id", i)]
    #)

    for_each = toset(local.guest_ips)

    triggers = {
      all_guest_ips = each.value
    }
}
```

Calling module:
```hcl
module "subnet_1" {
    source = "../../../../soltest-terraform-modules/modules/network/ip_range"
    subnet_id = "10.20.102.0/24"
}
```

### Crash Output

https://gist.github.com/muroj/35b5d7ca81cdf96fe81f37e4773f4013

### Expected Behavior

A null resource for each IP should have been created. 

### Actual Behavior

terraform crashes

### Steps to Reproduce

1. `terraform init`
2. `terraform plan/apply`

### References

Similar to #22560

**Comment by muroj** [comment]
Turns out I can accomplish the same (dynamic resource creation) using `count` instead of `for_each`.  

For example:

main.tf
```hcl
 
variable "subnet_id" {
    description = "IP Subnet specified in CIDR notation (e.g. 10.20.102.0/24) "
}
variable "host_range" {
    description = "A list specifying the available IPs"
    type = "list"
}

locals {
  guest_ips = [for i in var.host_range : cidrhost(var.subnet_id, i)]
}

resource "null_resource" "guest_ips" {

    triggers = {
      all_guest_ips = element(local.guest_ips, count.index)
    }

    count = length(local.guest_ips)
}
```

Here is the calling module:
```hcl
module "subnet_1" {
    source = "../../../../soltest-terraform-modules/modules/libvirt/network/ip_range"
    subnet_id = "10.20.102.0/24"
    host_range = flatten([range(1,5), range(11,15)])
}
```

I usually do not own an entire subnet, and must share it amongst other teams (not ideal, of course). This approach allows me to specify exactly which hosts are available in a given subnet.

**Comment by jcmaasb** [comment]
Hi @muroj 

In your case, i think it´s acomplise with this code:

```hcl
variable "subnet_id" {
  description = "IP Subnet specified in CIDR notation (e.g. 10.20.102.0/24) "
  default     = "10.20.102.0/24"
}

locals {
  guest_ips = { for i in range(1, 255) : cidrhost(var.subnet_id, i) => i... }
}

resource "null_resource" "guest_ips" {
  for_each = local.guest_ips

  triggers = {
    all_guest_ips = each.key
  }
}
```

I have some issues with for_each in resources, and i dont understant how its works.
I'm waiting for the response from the Terraform Team to know how to use lists and maps with "for_each" correctly.

**Comment by jcmaasb** [comment]
Hi @pselle
Thanks for your quick reply!!
