### ISSUE TITLE
Changing to zero dynamically-generally blocks does not cause existing block objects to be destroyed

### ISSUE THREAD

**Issue by rhuesken** [hashicorp/terraform#22605]
### Current Terraform Version

```
$ terraform --version
Terraform v0.12.7
+ provider.oci v3.39.0
```

### Use-cases

On some resources, optional blocks may be specified. Using dynamic blocks, the blocks are created when needed (see also https://github.com/hashicorp/terraform/issues/19853). However, setting the condition to create the block to false again, does not trigger terraform to clear the optional block. This is what I would expect / like to see in terraform.

### Attempted Solutions

https://github.com/hashicorp/terraform/issues/19853

**Comment by rhuesken** [comment]
Hi,

I experience this behavior e.g. with the OCI provider, when managing the ssl_configuration of the resource "oci_load_balancer_backend_set" 

  dynamic "ssl_configuration" { 
    # Only create an ssl_configuration block in case a certificate has been provided
    for_each = var.LB-SETS[count.index].backend_cert == "" ? [] : [1]
    content {
      #Required
      certificate_name = var.LB-SETS[count.index].backend_cert

      #Optional
      verify_peer_certificate = var.LB-SETS[count.index].bs_verify_peer
      verify_depth            = var.LB-SETS[count.index].bs_verify_depth

    }
  } 

In case a certificate has been provided,  var.LB-SETS[count.index].backend_cert != "" and a single ssl_configuration block will be created. Once I set the variable  var.LB-SETS[count.index].backend_cert to an empty string, no ssl_configuration block will be created anymore. 

So far so good, but I'd expect terraform (or the provider) to detect that change and to remove the ssl_configuration from the resource. This does not happen, however: the terraform plan returns with "No changes"...

Can you please indicate if my expectation is correct, and if so, this should be considered a terraform or a provider issue?

**Comment by jbardin** [comment]
Thanks for extra information @rhuesken.

This is a known consequence of how some providers configured their resources, often relying on undefined behavior in older versions of terraform.

This block is defined as both optional and computed in the schema, so when a value already exists in the state, removing it from the config will leave the existing value as it may have been computed. There could be a couple workarounds for this, but they will require changes in the provider, and understanding of how this block is intended to be used internally.
