### ISSUE TITLE
S3 backend: Support policy ARNs argument for assume role configuration

### ISSUE THREAD

**Issue by timoguin** [hashicorp/terraform#22601]
The `assume_role` configuration block for the S3 backend supports passing in a scoped down policy for the role session via the `assume_role_policy` argument.

In addition to the `Policy` parameter that passes a single inline policy, the STS API also supports a `PolicyArns` parameter that allows passing up to 10 policy ARNs for the role session.

I propose adding an `assume_role_policy_arns` argument to both the S3 backend and the Terraform remote state data source. This would allow more flexibility in scoping down role sessions.

The existing support for passing a JSON string provides no validation and swallows errors with a generic `AccessDenied`, so it can be difficult to debug if issues are actually due to permissions or if there is a simple syntax/validation issue with the passed policy. Alternately, specifying policy ARNs allows that policy validation to happen in another context.

References:
- https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
- https://aws.amazon.com/blogs/security/create-fine-grained-session-permissions-using-iam-managed-policies/

**Comment by bflad** [comment]
Support for this enhancement has been merged for the S3 Backend and will release with version 0.13.0-beta2 of Terraform.
