### ISSUE TITLE
vars on command line can get interpreted as scientific notation and discarded if too large

### ISSUE THREAD

**Issue by sjmh** [hashicorp/terraform#22639]
### Terraform Version
```
Terraform v0.11.14
```

### Terraform Configuration Files

```hcl

variable "gitcommit" {
  type = "string"
}

resource "aws_s3_bucket_object" "object" {
  bucket = "testtfbug"
  key    = "${var.gitcommit}"
  source = "/tmp/foo"
  etag   = "${filemd5("/tmp/foo")}"
}

```

### Expected Behavior
Execute the above terraform with:

`terraform apply -var "gitcommit=08e30503"`

An S3 object should be created with the name '08e30503'

### Actual Behavior

Terraform errors with:

```
Error: aws_s3_bucket_object.object: key must not be empty
```

If you do not include the '-var' on the command line and instead wait for terraform to prompt you for the variable, it works.

```
# terraform apply

var.gitcommit
  Enter a value: 08e30503


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_s3_bucket_object.object
      id:                     <computed>
      acl:                    "private"
      bucket:                 "testtfbug"
      content_type:           <computed>
      etag:                   "0d599f0ec05c3bda8c3b8a68c32a1b47"
      key:                    "08e30503"
      server_side_encryption: <computed>
      source:                 "/tmp/foo"
      storage_class:          <computed>
      version_id:             <computed>


Plan: 1 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce

Use configs above and give a large number in scientific notation for the variable via the command line.

### Additional Context

We run into this because we use git commit tags for tagging docker containers that we are uploading in a Jenkins job.  When the commit is ##e#####, the terraform fails to tag the container properly and uploads it with a blank tag.

**Comment by teamterraform** [comment]
Hi @sjmh! Sorry for this strange behavior, and thanks for reporting it.

This bug was already fixed as part of Terraform v0.12.0, so we're going to close this out. The previous discussion of this bug was in #17396 and #19406. Thanks!
