### ISSUE TITLE
Can't use "." in object type key names

### ISSUE THREAD

**Issue by taylora433** [hashicorp/terraform#22681]
### Terraform Version

```
0.12.7
```

### Terraform Configuration Files

```hcl
variable "some_variable" {
  type = map(object({
    variable.1.thing = object({
      variable.list = list(string)
    })
  }))
}

output "output" {
  value = var.some_variable
}
```
Using the following provided variables:
```hcl
some_variable = {
  "variable.1.thing" = {
    "variable.list" = [
      "item1"
    ]
  }
}
```

### Expected Behavior

The variable `some_variable` should have been output and the apply run successfully.
### Actual Behavior

```Error: Invalid type specification

  on main.tf line 3, in variable "some_variable":
   2:
   3:     variable.1.thing = object({
   4:
   5:
   6:

Object constructor map keys must be attribute names.
```
### Steps to Reproduce

1. terraform apply -var-file `file`
Where file contains the variables listed above

**Comment by teamterraform** [comment]
Hi @taylora433,

This is correct, attribute names must be valid identifiers, which means they cannot contain the `.` operator. Types must also be declared statically, which means the attributes cannot be interpolated from other values. 

While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by taylora433** [comment]
Apologies for not being clear as this is my first raised issue. I'd like to be able to provide literal strings as keys, the ability to supply `variable.1.thing` as a literal and not an interpolated value.

**Comment by taylora433** [comment]
The usecase for this is supplying a map that will be turned into a yaml file, the keys in this yaml file have the special character '.' that terraform uses for interpolation, so its currently not possible to set the keys of the object to be those literals.

**Comment by teamterraform** [comment]
@taylora433,

No problem, I wasn't sure which you meant so I provided both answers.
Object attributes must be valid identifiers, and cannot contain the `.` character. If value types are consistent, you can do this with maps rather than objects since map keys can be arbitrary strings.

**Comment by taylora433** [comment]
Yes, but this wouldn't be possible for my use case. I want to represent a yaml document with this object, so it could contain possibly complex structures. This is why I wanted to use an object for this case, since it can't just be a `map(string)`.

The yaml document could represent something like:
```
some.configuration.block:
  a-list-value:
    - value1
    - value2
  a-string-value: value
```

I'd like to be able to represent this as an object:

```
variable "some_variable" {
  type = map(object({
    some.configuration.block = object({
      a-list-value = list(string)
      a-string-value = string
    })
  }))
}

And the actual variable:
some_variable = {
  "some.configuration.block" = {
    "a-list-value" = [
      "value1",
      "value2"
    ],
   "a-string-value": "value"
  }
}
```

This way I can call the new yamlencode method on `var.some_variable` and get a valid yaml document.
