### ISSUE TITLE
Gitlab VCS Integration Permissions [docs]

### ISSUE THREAD

**Issue by v6** [hashicorp/terraform#22709]
### Proposal

I'd like to see the permissions needed for Terraform Enterprise's GitLab VCS integration listed here, because it will take less time to integrate with customers who take a "least privilege" approach to information security: 

https://www.terraform.io/docs/cloud/vcs/gitlab-com.html

If someone can point me to the source code for this documentation, I could make a pull request myself.

**Comment by teamterraform** [comment]
Hi @v6,

In the footer of all pages on `terraform.io` you can find an "Edit This Page" link which leads to the repository where that particular documentation page is maintained.

**Comment by kskewes** [comment]
Sorry if I am posting in the wrong place. I believe it relates to OP's question.

It would be good to clarify why `master` (`maintainer` in gitlab.com) permission is required.
The docs state:

> Important: The account you use for connecting Terraform Cloud must have admin (master) access to any shared repositories of Terraform configurations, since creating webhooks requires admin permissions.

Following least privilege principle, would an alternative be to use a lower permission level and provide documentation on how to create a `Webhook` manually similar to the SSH Key docs?
The automatically created webhook could be created by users if Terraform Cloud provides the dynamic URL & secret during the setup flow.

Related, Gitlab `Project` scoped API Tokens are not yet available for gitlab.com - tracking epic: https://gitlab.com/groups/gitlab-org/-/epics/2587

**Comment by mildwonkey** [comment]
That information is now included on the doc page, so I am going to close this issue. IF you have any further questions, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. Thanks!
