### ISSUE TITLE
aws_autoscaling_group - throw an error when you define a tag twice

### ISSUE THREAD

**Issue by jjshoe** [hashicorp/terraform#2270]
https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html

If you do a tag twice, and tell it to propagate in one, and not the other, you get random results in how the group is actually made. Should probably detect and error on this

**Comment by stack72** [comment]
Hi @jjshoe 

My apologies this has taken so long to get to :( We have quite a backlog. I have been testing this this morning and have found the following. Using this config:

```
resource "aws_launch_configuration" "foobar" {
  image_id = "ami-21f78e11"
  instance_type = "t1.micro"
}

resource "aws_autoscaling_group" "bar" {
  availability_zones = ["us-west-2a"]
  desired_capacity = 0
  max_size = 0
  min_size = 0
  launch_configuration = "${aws_launch_configuration.foobar.name}"

  tag {
          key = "test"
          value = "test"
          propagate_at_launch = true
  }

  tag {
          key = "test"
          value = "test"
          propagate_at_launch = false
  }
}
```

When i apply this config, I do not get any errors. I do see in the AWS console, that the last of the tags specified was added:

<img width="1045" alt="screen shot 2016-07-26 at 11 59 46" src="https://cloud.githubusercontent.com/assets/227823/17135593/7a8c0716-5328-11e6-9c87-89b3a5c565cd.png">

When i `terraform show`, I can see there is only 1 set of tags in the state (as only 1 set has been added to AWS and then read back from AWS):

```
% terraform show
aws_autoscaling_group.bar:
  id = tf-asg-ruduntgi3bhbhdt5cgh5bysyeu
  availability_zones.# = 1
  availability_zones.2487133097 = us-west-2a
  default_cooldown = 300
  desired_capacity = 0
  force_delete = false
  health_check_grace_period = 300
  health_check_type = EC2
  launch_configuration = terraform-iracf7rribbtdaqi63vrz2wsma
  load_balancers.# = 0
  max_size = 0
  metrics_granularity = 1Minute
  min_size = 0
  name = tf-asg-ruduntgi3bhbhdt5cgh5bysyeu
  placement_group =
  protect_from_scale_in = false
  tag.# = 1
  tag.3389926597.key = test
  tag.3389926597.propagate_at_launch = false
  tag.3389926597.value = test
  termination_policies.# = 0
  vpc_zone_identifier.# = 1
  vpc_zone_identifier.0 =
  wait_for_capacity_timeout = 10m
```

should I change the order of the tags to be as follows:

```
resource "aws_launch_configuration" "foobar" {
  image_id = "ami-21f78e11"
  instance_type = "t1.micro"
}

resource "aws_autoscaling_group" "bar" {
  availability_zones = ["us-west-2a"]
  desired_capacity = 0
  max_size = 0
  min_size = 0
  launch_configuration = "${aws_launch_configuration.foobar.name}"

  tag {
          key = "test"
          value = "test"
          propagate_at_launch = false      
  }

  tag {
          key = "test"
          value = "test"
          propagate_at_launch = true
  }
}

```

and then terraform apply, I can see that the AWS console hasn't been updated:

<img width="1045" alt="screen shot 2016-07-26 at 11 59 46" src="https://cloud.githubusercontent.com/assets/227823/17135693/f09c1144-5328-11e6-8cd1-e511168eaefa.png">

Is this the behaviour you are experiencing?

**Comment by jjshoe** [comment]
Yes

**Comment by radeksimko** [comment]
For validating the config during plan we'll first need to implement validation support for sets. (just to explain the reason behind adding `core` tag)

**Comment by apparentlymart** [comment]
@radeksimko, I intentionally let the bot migrate this because `CustomizeDiff` exists to let this validation be done if the provider team wants to.
