### ISSUE TITLE
path.module returning absolute paths

### ISSUE THREAD

**Issue by 007** [hashicorp/terraform#22708]
### Terraform Version

```
Terraform v0.12.5
+ provider.aws v2.15.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2
```

Can't update to 0.12.8 without coordinating with all other devs. That's a separate problem...

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "function_def" {
  filename      = "${path.module}/build/lambda.zip"
  function_name = var.lambda_name
```

### Debug Output

Too sensitive / too much, can isolate if required.

### Expected Behavior

State file should store relative path to lambda file. (`../modules/lambda/reschedule/build/lambda.zip`)

### Actual Behavior

State file is storing absolute path to lambda file. (`/Users/OTHERUSER/src/BRANCH/operations/tf/env-staging/.terraform/modules/CRAZY-HASH/build/lambda.zip`)

```
  # module.reschedule.aws_lambda_function.function_def will be updated in-place
  ~ resource "aws_lambda_function" "function_def" {
        arn                            = "arn:aws:lambda:us-west-2:ACCOUNTID:function:reschedule"
      ~ filename                       = "/Users/OTHERUSER/src/BRANCH/operations/tf/env-staging/.terraform/modules/CRAZY-HASH/build/lambda.zip" -> "../modules/lambda/reschedule/build/lambda.zip"
```

### Steps to Reproduce

- Make a lambda with a `path.module` relative path for the file.
- Use module from another directory.
- Have `user1` run `apply` and complete succesfully
- Have `user2` run `plan`

### References

- #21438
- #7927
- #8204
- #7613

**Comment by jbardin** [comment]
Hi @007,

Sorry this is making the upgrade more difficult. From your description the current behavior is what you want. The `path.module` value in 0.12 is the relative path from the root module, and once you have upgraded the paths should all be identical across different systems. 

If you need an absolute path similar to the 0.11 format, there is the `abspath` function. Note that this absolute path to the module in 0.12 still may not match because of differences in the module storage.

**Comment by 007** [comment]
@jbardin I think you missed `Terraform v0.12.5` - this is using 0.12 already, and still broken.

**Comment by jbardin** [comment]
Hi @007, the 0.12 output above shows a new value of `"../modules/lambda/reschedule/build/lambda.zip"`, which is a relative path.  The existing absolute path you're seeing is most likely from an earlier version of terraform.

Just to ensure that the resource wasn't attempting to alter the path internally, I also created a lambda function using `path.module` and confirmed the relative path is stored in the state.

Are you seeing this after applying with 0.12, or is this during the upgrade process?

**Comment by 007** [comment]
We upgraded everything to 0.12 a while ago. This function was deployed since then, probably with 0.12.4, and it's still showing as an absolute path for another dev's machine when I'm deploying on 0.12.5.

**Comment by jbardin** [comment]
The new path for this resource is a relative path as expected, and `path.module` is designed to now only return a relative path. The `/CRAZY-HASH/` path segment in the example path also implies that this state was created from 0.11. 

Can you show how the modules is configured, and have there been any recent configuration changes to the module at all? Can you apply these changes and see if there is still a diff after the `filename` is updated?

**Comment by 007** [comment]
There isn't a diff now, after the module is applied to reflect the updated relative-path.

How can the state be in 0.11 form when the transition to 0.12 - including removing all of the `"${var.foo}" -> var.foo` changes and updating the full state - happend in July? Is this user error, where we somehow missed a module during the full apply? Or does it not update state if it's only the path and not the underlying content that changed?
