### ISSUE TITLE
Github Actions has new syntax

### ISSUE THREAD

**Issue by mbevc1** [hashicorp/terraform#22715]
### Current Terraform Version

```
n/a
...
```

### Use-cases

Using TF workflows in Github Actions.

### Attempted Solutions

Tried to find website code for those pages here, but only docs are generated here?

### Proposal

Either you should add new synatx or move that content to GH and enable people to submit PRs for new GitHub fetatures.

**Comment by kmoe** [comment]
Thanks for raising this, @mbevc1.

Assuming this refers to the [GitHub Actions section of the Terraform documentation](https://www.terraform.io/docs/github-actions/index.html), you can find the source code repository for the website by clicking the "Edit this page" link at the bottom of the page.

The website source code can be found at https://github.com/hashicorp/terraform-website, and we welcome PRs!

I'm going to close this issue as it looks like Terraform is working as expected, but please open a new one if you think there's a bug here.
