### ISSUE TITLE
Failed to instantiate provider "azure" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### ISSUE THREAD

**Issue by ralle214** [hashicorp/terraform#22716]
### Terraform Version

``Terraform v0.12.8
+ provider.azure v0.1.1
+ provider.azurerm v1.33.1
...
```

### Terraform Configuration Files
<!--
Paste the relevant parts of your Terraform configuration between the ``` marks below.

For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file. For security, you can also encrypt the files using our GPG public key.
-->

```hcl
...
```
/* Configure Azure Provider and declare all the Variables that will be used in Terraform configurations */
provider "azurerm" {
 subscription_id         = "xxxxx-xxxxx-xxxxx-xxxxxx"
 client_id                    = "xxxxx-xxxxx-xxxxx-xxxxxx"
 client_secret              = "${var.client_id}"
 tenant_id                   = "xxxxx-xxxxx-xxxxxx-xxxxxx"
}

**Comment by mildwonkey** [comment]
Hi @ralle214 ,
This message indicates that you are using a version of the azure provider that is not compatible with terraform 0.12. Please upgrade the provider. You can run `terraform init -upgrade` to get the latest version of all providers (and modules) in your configuration, or pin the azure provider version to a newer version.

**Comment by ralle214** [comment]
I have the latest version# terraform -v 
Terraform v0.12.8
+provider.azure v0.1.1
+provider.azurerm v1.33.1

**Comment by ralle214** [comment]
> Hi @ralle214 ,
> This message indicates that you are using a version of the azure provider that is not compatible with terraform 0.12. Please upgrade the provider. You can run terraform init -upgrade to get the latest version of all providers (and modules) in your configuration, or pin the azure provider version to a newer version.

**Comment by ralle214** [comment]
> Hi @ralle214 ,
> This message indicates that you are using a version of the azure provider that is not compatible with terraform 0.12. Please upgrade the provider. You can run terraform init -upgrade to get the latest version of all providers (and modules) in your configuration, or pin the azure provider version to a newer version.
I have the latest versions > terraform -v 
Terraform v0.12.8
+ provider.azure v0.1.1
+ provider.azurerm v1.33.1

**Comment by ralle214** [comment]
Can you verify the correct format for service principal (client_secret) password?  The Azure Portal client_secret password is not the same format:
 "password": "0000-0000-0000-0000-000000000000",

**Comment by mildwonkey** [comment]
If the latest azure provider is giving you that error message, please open an issue in the azure provider repository, although I believe that `azure` has been replaced by `azurerm` and is no longer being supported.

**Comment by mildwonkey** [comment]
Sorry, I meant to include some supporting information:

https://www.terraform.io/docs/providers/azure/index.html
https://github.com/terraform-providers/terraform-provider-azure-classic (archived)

Azurerm provider: https://github.com/terraform-providers/terraform-provider-azurerm
