### ISSUE TITLE
Terraform 0.12 import does not pass variable to child module if default value exists.

### ISSUE THREAD

**Issue by runecalico** [hashicorp/terraform#22721]
We are migrating to Terraform 12 from Terraform 11, so we have a number of deployments still using Terraform 11, we have an in-house module which we use to lookup information (ip lists, names of things etc) that is still coded as "terraform 11" so we could avoid having to maintain two modules, one for TF 11 and one for TF 12.

The module works fine in a plan/apply in TF12, however it does not work on an import. This unfortunately is something we just realized.

here is the TF12 error on import ..
```
  on .terraform\modules\azure_lookups\main.tf line 1180, in locals:
1180:   SubscriptionName                         = "${lookup(local.SubscriptionNameUsingFullName , lower(replace(var.subscription_name, var.regex_replace_chars, "")))}"
    |----------------
    | local.SubscriptionNameUsingFullName is object with 16 attributes

Invalid value for "inputMap" parameter: the given object has no attribute "".
```

### Terraform Version

```
Terraform v0.12.7
+ provider.azurerm v1.33.1
```

### Terraform Configuration Files

```hcl
The module declaration (which works)
module "azure_lookups" {
  source = "https://xxxx.xx.xx.xx:443/artifactory/xxxx-maven-releases/com/xxxx/xxxx/terraform/azure_lookups-module/0.0.0/azure_lookups-module-0.0.0.zip"

  subscription_name = "xxx-xx-xx-xx"
  azure_region      = "eastus2"
}

The part of the module which has the errror (works using terraform 0.11.14 import)
 SubscriptionName                         = "${lookup(local.SubscriptionNameUsingFullName , lower(replace(var.subscription_name, var.regex_replace_chars, "")))}"

```

### Expected Behavior

The import was successful (it used to work in Terraform 11)

### Actual Behavior

The import fails

### Steps to Reproduce

1. `terraform init`
2. `terraform import azurerm_resource_group.fzcu-trafrm-li-npd-rgp-05 /subscriptions/xxxxx-xxxx-xxx-xxx-xxx/resourceGroups/fzcu-trafrm-li-npd-rgp-05`

**Comment by runecalico** [comment]
I would hazard a guess that the lookup itself "is not working", if I set the default value on the lookup it will no longer error out... however the lookup itself doesn't work (it fails to lookup the value and so uses the default).

**Comment by runecalico** [comment]
I have identified the root cause of this issue. In at least MY case, when using terraform import with a var file and modules, if the module variable has a default value... it uses that default value and not the value in the module resource.
I removed the default value (from the module variable) and now the import works and the module looks to be generating output etc.

Should I re-open this or something on the actual issue, which seems to be that when using terraform import with a module (using a var file might also factor in) that has a default value the default value is used instead of the value provided in the module resource declaration.

**Comment by runecalico** [comment]
Debug output from terraform import with module when it has default value set, and one where the module doesn't have the default value set.
<script src="https://gist.github.com/runecalico/1e53eb83ec7ec6bf011623c8b5e7933e.js"></script>

**Comment by runecalico** [comment]
This behaviour still exists in 0.12.9.
If I try to import a resource created by a module (for example an azurerm_app_service_plan), the import will fail because the input variables to the module will not be passed to the module if the module has default values for that input variable. Commenting out the defaults (in the child module) allows the values to be passed to the module and the import succeeds.

**Comment by movergan** [comment]
Just encountered into this issue. Was able to workaround it manually specifying username and password in .terraform/<module>/providers.tf for provider "vsphere" after `terraform init`. But I need to import 50+ VMs, and it's 50+ manual modifications.

**Comment by kyrogue** [comment]
Can confirm this exists in 0.12.16.
This happens when a child module uses a variable that has defined a default value.
When we try to pass in a variable to overwrite that value using --var-files in my case, the value will not be overridden. Rather the default value will be used.

**Comment by omazin** [comment]
Reproduced the same issue using 0.12.17. Not able to override default values when importing resources.

**Comment by jbergknoff-rival** [comment]
I've also encountered this on several occasions.

Often the resources causing the refresh trouble are unrelated to the resource being imported. One workaround that I've found effective in those situations is to just hide the TF definitions for the resources causing trouble (e.g. rename the file `.tf -> .tf.backup`), do the import, and then reintroduce them.

**Comment by zhiqiangchine2x** [comment]
Still happening in terraform v0.12.24

**Comment by kyrogue** [comment]
Not yet fixed in terraform v0.12.24

**Comment by watsh-rajneesh** [comment]
+1 seeing this issue in v0.12.24

**Comment by jfharden** [comment]
Also in 0.12.25

**Comment by billmoritz** [comment]
The issue exists in v0.12.26 and I've verified @jbergknoff-rival's work around got the import to work.

**Comment by jbardin** [comment]
Hello,

I have confirmed this now works in the next v0.15 release.

Thanks!
