### ISSUE TITLE
aws_elasticache_cluster doesn't document `cache_nodes`

### ISSUE THREAD

**Issue by nevir** [hashicorp/terraform#2272]
It's tough to use `aws_elasticache_cluster` right now, since it doesn't expose the endpoint hostname for nodes in the cluster (maybe via an `endpoint` or `endpoints` attribute?)

**Comment by nevir** [comment]
Oh, it does expose `cache_nodes`; just not documented!

**Comment by juniorplenty** [comment]
@navir Nb: https://github.com/hashicorp/terraform/issues/2051 (That is still an issue in 1.5.2/3, even though it's closed in GH)

**Comment by nevir** [comment]
ah, fun :(

**Comment by mikeyhill** [comment]
Trying to create a Redis cluster with 2 nodes I get:

    Error creating Elasticache: InvalidParameterValue: Cannot create a Redis cluster with a NumCacheNodes parameter greater than 1.
	status code: 400,

However the cluster is created fine.

---

I'm currently on the latest master (dd24b58bf3a9e172950eea13aade593d2b249dc2), however not sure which version that is - TF seems to be reporting version 0.6.0 for some unknown reason.

**Comment by radeksimko** [comment]
Thanks for the report.
See #2332

**Comment by AnudeepReddyJ21** [comment]
Hi, 

I am trying to create a redis cluster with two cache nodes and terraform gives this error

"Error creating Elasticache: InvalidParameterValue: Cannot create a Redis cluster with a NumCacheNodes parameter greater than 1."

Is this a limitation? I was able to create Memcache Cluster with two nodes.

Thanks,

Anudeep
