### ISSUE TITLE
Terraform 0.12upgrade function doesn't handle dots in metadata names

### ISSUE THREAD

**Issue by anas-domesticus** [hashicorp/terraform#22757]
Hello,

When performing an automatic code upgrade from .11 to .12, the 0.12upgrade feature does not insert quotes around metadata names. If these names contain dots, this breaks in version 0.12 whereas it was accepted in 0.11.
```
resource "openstack_compute_instance_v2" "public_cloud_vm" {
  name      = "UKRSC${var.vm_role}-${var.env_name}${format("%02d", count.index + 1)}"
  region    = "LON"
  image_id  = var.rs_image_id
  flavor_id = var.rs_flavor_id

  key_pair = var.rs_keypair
  metadata = {
    com.rackspace.mycloud.tags.0 = var.vm_role
    build_config                 = var.build_metadata
  }
```
Should become
```
resource "openstack_compute_instance_v2" "public_cloud_vm" {
  name      = "UKRSC${var.vm_role}-${var.env_name}${format("%02d", count.index + 1)}"
  region    = "LON"
  image_id  = var.rs_image_id
  flavor_id = var.rs_flavor_id

  key_pair = var.rs_keypair
  metadata = {
    "com.rackspace.mycloud.tags.0" = var.vm_role # <--- HERE
    "build_config"                 = var.build_metadata
  }
```

### Terraform Version
Terraform v0.12.8

```
...
```

### Terraform Configuration Files
Above....

```hcl
...
```

### Expected Behavior
Quotes should be added around the relevant metadata names

### Actual Behavior
No code change, code then validates fine in newer version of TF but will not plan or apply

### Steps to Reproduce
terraform 0.12upgrade
terraform plan
Error!

**Comment by apparentlymart** [comment]
Hi @anas-domesticus! Thanks for reporting this and sorry for the lack of response. I think we had quite a lot of feedback about this command, including some duplicates, and so I'm not sure if this ended up fixed via some other issue or not.

The `terraform 0.12upgrade` command was removed from Terraform in the v0.13 release, having served its purpose, so at this point whatever its behavior is will be its final behavior; v0.12 is obsolete and we're not planning any further v0.12 releases aside from high-priority changes such as security issues.

For that reason, I'm going to close this. Thanks again for reporting it!
