### ISSUE TITLE
Atlas and Terraform doesn't return AMI ID correctly

### ISSUE THREAD

**Issue by highlyunavailable** [hashicorp/terraform#2277]
I'm not sure if I'm doing this wrong or if this is some sort of issue, but I've got the following config:

```
provider "atlas" {
    token = "${var.atlas_token}"
}

resource "atlas_artifact" "thingie" {
    name = "highlyunavailable/thingie"
    type = "aws.ami"
    build = "latest"
}

resource "aws_launch_configuration" "thingie" {
    name = "thingie"
    image_id = "${atlas_artifact.thingie.id}"
    instance_type = "t2.medium"
}
```

Running `terraform plan` results in:

```
+ aws_launch_configuration.thingie
    associate_public_ip_address: "" => "0"
    ebs_block_device.#:          "" => "<computed>"
    ebs_optimized:               "" => "<computed>"
    image_id:                    "" => "us-west-2:ami-33211903"
    instance_type:               "" => "t2.medium"
    key_name:                    "" => "<computed>"
    name:                        "" => "thingie"
    root_block_device.#:         "" => "<computed>"
```

Note `image_id:                    "" => "us-west-2:ami-33211903"` - this is very much incorrect and should just be `ami-33211903`. I created the image off of a packer template - that's how it got into Atlas.

**Comment by phinze** [comment]
@highlyunavailable sorry for the confusion here, you need to reach into the metadata to get the AMI ID off the artifact, like this: `${atlas_artifact.thingie.metadata_full.region-us-west-2}`

The docs are actually fixed on master, we just need a website deploy.

Let me know if that works for you! :+1:

**Comment by highlyunavailable** [comment]
Aha, yeah, I just discovered that. Thanks.

**Comment by enxebre** [comment]
This is my workaround for getting the id dynamically regarding the region:
  ami = "${replace(atlas_artifact.mesos-master.id, concat(var.region, ":"), "")}"
