### ISSUE TITLE
Sensitive undeclared variables are output to the Terraform Cloud console during runs as warnings

### ISSUE THREAD

**Issue by e30chris** [hashicorp/terraform#22782]
### Summary

Configuring Terraform Cloud to use a "sensitive" variable, if the variable is not declared in the Terraform code, the contents of the "sensitive - write only" variable are output to the Terraform Cloud Web Console as a warning.

### Terraform Version

```
0.12.8
```

### Debug Output

```
Terraform v0.12.8
Configuring remote state backend...
Initializing Terraform configuration...
2019/09/12 18:30:18 [DEBUG] Using modified User-Agent: Terraform/0.12.8 TFC/4aeade9300

Warning: Value for undeclared variable

  on /terraform/FoundationLayer/terraform.tfvars line 1:
   1: GOOGLE_CLOUD_KEYFILE_JSON = "{\n  \"type\": \"service_account\",\n

<sensitive clip>

The root module does not declare a variable named "GOOGLE_CLOUD_KEYFILE_JSON".

To use this value, add a "variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.
```

### Expected Behavior

If a variable has been marked as "Sensitive - write only", it will never be read-able as output on any web console page but may appear in an error log, following the promise made in the documentation.

_"Marking a variable as sensitive prevents anybody (including you) from viewing its value in Terraform Cloud's UI or API."_ 

[sensitive-values doc](https://www.terraform.io/docs/cloud/workspaces/variables.html#sensitive-values)

### Actual Behavior

If the `A_SECRET_KEY_FILE` is set to "sensitive - write only" as a variable in the Terraform Cloud Workspace, if the variable is not declared in the Terraform code being executed by Terraform Cloud, the contents of the "sensitive - write only" variable are output to the web console.

### Steps to Reproduce

  * Create a Terraform Cloud Workspace
  * Connect to a VCS with Terraform code
  * Add a `Terraform Variable` to the Cloud Workspace
    * `key` = `A_SECRET_KEY_FILE`
    * `value` = `THIS SHOULD BE WRITE ONLY AND NEVER WRITTEN TO A WEB PAGE OR ERROR FILE` 
  * Mark the `Terraform Variable` as `sensitive`
  * Verify that the variable `A_SECRET_KEY_FILE` _is not declared in the Terraform code_
  * Queue the plan
  * View the console output
  * Verify that `THIS SHOULD BE WRITE ONLY AND NEVER WRITTEN TO A WEB PAGE OR ERROR FILE` is written out to, and displayed on the web console

**Comment by e30chris** [comment]
Thanks for the great response @teamterraform !  I did try to use the GCP Service Account JSON as an environment variable but when adding the JSON key file I received an error from the Terraform Cloud UI that stated "environment values must not be multiple lines".  I can file a bug for that separately if that is not the expected behavior.

**Comment by teamterraform** [comment]
Hi @e30chris! Sorry for the slow response here.

If the Terraform Cloud UI is rejecting multi-line values then at least for _this_ situation it would hopefully work to remove all of the newlines from the JSON, because newline characters in JSON are not meaningful content anyway and so can be eliminated without changing the meaning of the value.

We're not sure if there are other situations where existing providers expect multi-line strings as environment variables. If so, it would be good for Terraform Cloud to support that in order to allow for such situations, but usually environment variables are used for single primitive-typed values rather than data structures, so we suspect that the Google Cloud provider is an outlier here.

**Comment by danieldreier** [comment]
Many thanks to @kmfk for https://github.com/hashicorp/terraform/pull/23293 which should resolve this!
