### ISSUE TITLE
Add additional protocols for ACL's and Security Groups

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#2278]
ESP and AH cause an error.

    * Invalid Protocol ESP for rule map[string]interface {}{"icmp_type":0, "icmp_code":0, "from_port":0, "to_port":65535, "rule_no":810, "action":"allow", "protocol":"ESP", "cidr_block":"0.0.0.0/0"}

I checked out the code and am not sure where the protocol numbers (https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml) are coming from so couldn't update it.

**Comment by phinze** [comment]
Hi @mikeyhill - looks like we have a mapping here if you wanted to take a stab at adding the ones you need:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/network_acl_entry.go#L72-L81
