### ISSUE TITLE
Terraform cloud local-exec provisioner does not support software installation via apt

### ISSUE THREAD

**Issue by swetli** [hashicorp/terraform#22788]
### Terraform Version

```
Terraform v0.12.8
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
resource "null_resource" "echo" {
  provisioner "local-exec" {
    command = "id"
  }  
  provisioner "local-exec" {
    command = "apt-get install jq || /bin/true"
  }
   provisioner "local-exec" {
    command = "sudo apt-get install jq || /bin/true"
  }     
}
```

### Debug Output

```
Terraform v0.12.8
Initializing plugins and modules...
2019/09/13 09:48:00 [DEBUG] Using modified User-Agent: Terraform/0.12.8 TFC/d8986333a4
null_resource.echo[0]: Creating...
null_resource.echo[0]: Provisioning with 'local-exec'...
null_resource.echo[0] (local-exec): Executing: ["/bin/sh" "-c" "id"]
null_resource.echo[0] (local-exec): uid=500(terraform) gid=1001(terraform) groups=1001(terraform)
null_resource.echo[0]: Provisioning with 'local-exec'...
null_resource.echo[0] (local-exec): Executing: ["/bin/sh" "-c" "apt-get install jq || /bin/true"]
null_resource.echo[0] (local-exec): E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
null_resource.echo[0] (local-exec): E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
null_resource.echo[0]: Provisioning with 'local-exec'...
null_resource.echo[0] (local-exec): Executing: ["/bin/sh" "-c" "sudo apt-get install jq || /bin/true"]
null_resource.echo[0] (local-exec): sudo: unable to stat /etc/sudoers: No such file or directory
null_resource.echo[0] (local-exec): sudo: no valid sudoers sources found, quitting
null_resource.echo[0] (local-exec): sudo: unable to initialize policy plugin
null_resource.echo[0]: Creation complete after 0s [id=8930720051832908419]
```
### Expected Behavior
sudo apt-get install or apt-get install should work in terraform cloud using local-exec provisioner.

### Actual Behavior
According to the official documentation, installation  of software should be possible in terraform cloud (https://www.terraform.io/docs/cloud/run/install-software.html) using local-exec provisioner. Either apt-get install or sudo apt-get install should work, however as can be seen - both fail.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by jeffb4** [comment]
@swetli what host environment was this being run in? (Ubuntu server, Debian server, container, etc)

**Comment by mildwonkey** [comment]
Hi @swetli , thank you for reporting this! 

I've passed the issue along to the team that manages Terraform Cloud. They are working on updating the documentation; `sudo` is only allowed for Terraform Enterprise users, not the general Terraform Cloud users.

I will leave this ticket open until the documentation is updated. Thanks again!

**Comment by swetli** [comment]
Hi @jeffb4,

This has been run on whatever distribution Hashicorp had selected for their terraform-cloud platform. At the time of posting this issue the distribution in question is: Ubuntu 18.04.3 LTS.

**Comment by kahootali** [comment]
@swetli  Any update or workaround on this?

**Comment by mildwonkey** [comment]
The relevant docs have been updated, so I am going to close this issue. Thanks!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
