### ISSUE TITLE
Terraform init does not work in hashicorp image

### ISSUE THREAD

**Issue by rifaterdemsahin** [hashicorp/terraform#22808]
**Command i am running**

docker run -it terraform1 init -from-module=git::ssh://git@github.com/gruntwork-io/terragrunt-infrastructure-modules-example.git?ref=v0.0.1

**Error I am getting**
root@ubuntu-s-4vcpu-8gb-nyc1-01:~# docker run -it terraform1 init -from-module=git::ssh://git@github.com/gruntwork-io/te
rragrunt-infrastructure-modules-example.git?ref=v0.0.1
Copying configuration from "git::ssh://git@github.com/gruntwork-io/terragrunt-infrastructure-modules-example.git?ref=v0.
0.1"...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Error copying source module: error downloading 'ssh://git@github.com/gruntwork-io/terragrunt-infrastructure-modules-exam
ple.git?ref=v0.0.1': /usr/bin/git exited with 128: Cloning into '/tmp/tf286308751/module'...
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

root@ubuntu-s-4vcpu-8gb-nyc1-01:~# docker run -it terraform1 init -from-module=git::ssh://git@github.com/gruntwork-io/te
rragrunt-infrastructure-modules-example.git?ref=v0.0.1
root@ubuntu-s-4vcpu-8gb-nyc1-01:~/terraformcheck# docker run -it terraform1 init -from-module=git::ssh://git@github.com/
gruntwork-io/terragrunt-infrastructure-modules-example.git?ref=v0.0.1
Copying configuration from "git::ssh://git@github.com/gruntwork-io/terragrunt-infrastructure-modules-example.git?ref=v0.
0.1"...
The authenticity of host 'github.com (140.82.114.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Error copying source module: error downloading 'ssh://git@github.com/gruntwork-io/terragrunt-infrastructure-modules-exam
ple.git?ref=v0.0.1': /usr/bin/git exited with 128: Cloning into '/tmp/tf150828533/module'...
Warning: Permanently added 'github.com,140.82.114.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

root@ubuntu-s-4vcpu-8gb-nyc1-01:~/terraformcheck#

**My Dockerfile**
root@ubuntu-s-4vcpu-8gb-nyc1-01:~/terraformcheck# cat Dockerfile
FROM hashicorp/terraform:0.11.14 AS main
root@ubuntu-s-4vcpu-8gb-nyc1-01:~/terraformcheck#

**Comment by rifaterdemsahin** [comment]
also other terraform image did not work as well

root@ubuntu-s-4vcpu-8gb-nyc1-01:~/x# docker run -i -t hashicorp/terraform:light init -from-module=git:://ssh://github.co
m/terraform-provider-aws/tree/master/examples/alexa
Copying configuration from "git:://ssh://github.com/terraform-provider-aws/tree/master/examples/alexa"...

Error: Can't populate non-empty directory

The target directory . is not empty, so it cannot be initialized with the
-from-module=... option.

root@ubuntu-s-4vcpu-8gb-nyc1-01:~/x#
root@ubuntu-s-4vcpu-8gb-nyc1-01:~/x# ls
root@ubuntu-s-4vcpu-8gb-nyc1-01:~/x#

**Comment by kmoe** [comment]
Hello @rifaterdemsahin. The `hashicorp/terraform` Docker images are maintained at https://github.com/hashicorp/docker-hub-images - you may want to search for a similar issue here and open an issue or pull request. Please make sure your issue text is formatted using [GitHub markdown](https://guides.github.com/features/mastering-markdown/) so it's easy for maintainers to read.

Closing as this is not a Terraform Core issue.
