### ISSUE TITLE
Crash during plan migrating to 0.12

### ISSUE THREAD

**Issue by Tirke** [hashicorp/terraform#22813]
### Terraform Version

```
Terraform version: 0.12.8  
```

### Terraform Configuration Files

Module outputting IAM policy
```hcl
output "invoke-function" {
  value = jsonencode({
    Version   = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = [
          "lambda:InvokeFunction",
        ]
        Resource = [
          var.RESOURCES
        ],
      }
    ]
  })
}

variable "RESOURCES" {
  type    = list(string)
  default = []
}
```

Module consuming the policy module
```hcl
resource "aws_iam_role" "iam-api-authorizer-backend-invoke" {
  name                  = "iam-api-authorizer-backend-invoke"
  force_detach_policies = true

  path               = "/"
  assume_role_policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Action    = "sts:AssumeRole"
        Principal = {
          Service = "apigateway.amazonaws.com"
        }
      },
    ]
  })
}

module "lambda-policy-document" {
  source    = "../module-policy"
  RESOURCES = ["*"]
}

resource "aws_iam_role_policy" "authorizer-da-backend-credentials" {
  name   = "authorizer-da-backend-credentials"
  role   = aws_iam_role.iam-api-authorizer-backend-invoke.id
  policy = module.lambda-policy-document.invoke-function
}
```

Root consumer
```hcl
terraform {
  backend "s3" {
    region = "eu-west-1"
    key    = "data-acquisition/da-backend.tfstate"
  }
}

provider "aws" {
  region = "eu-west-1"
}

module "da-external" {
  source = "../external"
}

module "da-authorizer" {
  source = "../authorizer"
}
```

### Crash Output

Full crash output :
https://gist.github.com/Tirke/93c82c9a3ba02eb85196861c9119462a

Relevant bits :
```
2019-09-16T18:46:17.498+0200 [DEBUG] plugin.terraform-provider-aws_v2.28.1_x4: panic: interface conversion: interface {} is []interface {}, not string
2019-09-16T18:46:17.498+0200 [DEBUG] plugin.terraform-provider-aws_v2.28.1_x4: 
2019-09-16T18:46:17.498+0200 [DEBUG] plugin.terraform-provider-aws_v2.28.1_x4: goroutine 739 [running]:
2019-09-16T18:46:17.498+0200 [DEBUG] plugin.terraform-provider-aws_v2.28.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/jen20/awspolicyequivalence.newAWSStringSet(0x4b56420, 0xc0008ff840, 0xc000999630, 0x1, 0x1)
....
019/09/16 18:46:17 [ERROR] module.da-devices: eval: *terraform.EvalReadState, err: rpc error: code = Unavailable desc = transport is closing
2019/09/16 18:46:17 [ERROR] module.da-authorizer: eval: *terraform.EvalDiff, err: rpc error: code = Unavailable desc = transport is closing
....
```

### Context and expected behavior, fix ...

We are currently migrating our big project from tf 0.11 to tf 0.12.
The first few layers went quite well but we hit a crash during the first 0.12 plan on our two biggest layers. I've done a minimal reproduction on our biggest tfstate (5MO mainly because it contains the swagger definition for our API Gateway).
After discussing some problems we have with the refresh phase on this tfstate (see #22617) we decided to rewrite all our 900 `data.aws_iam_policy_document` to a more simple HCL object + `jsonencode`. All our previous modules containing `data.aws_iam_policy_document`  now contain JSON encoded outputs like you can see in the first snippet I provided.

And this refactoring seems to be the exact source of our problem. Making a plan from a empty local tfstate works. Making the plan against our existing tfstate doesn't. And from the crash log I heavily suspect that there is something going on between our old `data.aws_iam_policy_document` and the new JSON encoded modules.

I've already found what seems to be a fix  but it would cost us a lot of inefficient rewriting of many modules to switch to a working version. The fix is quite simple, I just need to rewrite the second module with an inline policy :

Module consuming the policy module
```hcl
resource "aws_iam_role" "iam-api-authorizer-backend-invoke" {
  name                  = "iam-api-authorizer-backend-invoke"
  force_detach_policies = true

  path               = "/"
  assume_role_policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Action    = "sts:AssumeRole"
        Principal = {
          Service = "apigateway.amazonaws.com"
        }
      },
    ]
  })
}

resource "aws_iam_role_policy" "authorizer-da-backend-credentials" {
  name   = "authorizer-da-backend-credentials"
  role   = aws_iam_role.iam-api-authorizer-backend-invoke.id
  policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = [
          "lambda:InvokeFunction",
        ]
        Resource = [
          var.RESOURCES
        ],
      }
    ]
  })
}
```

I also suspect that doing some surgery in our tfstate could fix things. Something like `tf state remove` everything related to our old modules containing the `data.aws_iam_policy_document`  but I've not tested that yet because I'm hoping that there is a potential fix to this issue.

**Comment by Tirke** [comment]
After sleeping on it, it seems that the real fix is quite easier.
```hcl
output "invoke-function" {
  value = jsonencode({
    Version   = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = [
          "lambda:InvokeFunction",
        ]
        Resource = [
          var.RESOURCES
        ],
      }
    ]
  })
}

variable "RESOURCES" {
  type    = list(string)
  default = []
}
```
This is my first module and the `RESOURCES` variable is an array. And we wrote `[var.RESOURCES]` in the policy object where we should have written `var.RESOURCES`.
Doing that seems to fix the issue. Should I keep the issue open because there is obviously room for improvement here, I don't think Terraform should crash on that.

**Comment by teamterraform** [comment]
Thanks for opening this, @Tirke !
Terraform core can't catch this issue, because it's just feeding into `jsonencode`, so I am going to move this to the aws provider repository. It's up to the provider (or more specifically github.com/jen20/awspolicyequivalence ) to handle.
