### ISSUE TITLE
Multiple results from single data resource

### ISSUE THREAD

**Issue by kwdoos** [hashicorp/terraform#22819]
## Terraform version

```
Terraform v0.12.7
+ provider.aws v2.16.0
+ provider.null v2.1.2
+ provider.random v2.2.0
```
## Configuration

```terraform
data "aws_instance" "ec2" {
        filter {
                name = "tag:aws:autoscaling:groupName"
                values = ["group_name"]
        }
}

/*
resource "aws_lb_target_group_attachment" "ec2" {
        count = "${len(data.aws_instance.ec2)}"

        target_group_arn = "${aws_lb_target_group.group.arn}"
        target_id = "${data.aws_instance.ec2[count.index].private_ip}"
        availability_zone = "all"
}
*/
```

## Expected behavior

Should work because AWS API by using awscli can, and will return more than one results when executing query with same filters.

## Actual behavior

```
Error: Your query returned more than one result. Please try a more specific search criteria.
```

**Comment by teamterraform** [comment]
Hi @kwdoos! 

According to the documentation, [`aws_instance`](https://www.terraform.io/docs/providers/aws/d/instance.html) expects to return a single instance. Use the [`aws_instances`](https://www.terraform.io/docs/providers/aws/d/instances.html) data source if you expect multiple results.
