### ISSUE TITLE
Resource-level customizable timeouts not being respected

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform#22810]
### Terraform Version

```console
$ terraform version
Terraform v0.12.8
```

While working on https://github.com/terraform-providers/terraform-provider-aws/pull/10114 I upped the `Delete` [timeout](https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html) on the `aws_security_group` resource to 30 minutes.
However during testing I found that the timeout fires at the default value of 20 minutes.

Looking at the Terraform state files for the resource I see that with v0.11.10 the customized values are persisted but with v0.12.8 the `timeouts` attribute value is `null`:

Terraform 0.11.10:

```javascript
"resources": {
    "aws_security_group.example": {
        "type": "aws_security_group",
        "primary": {
            "meta": {
                "e2bfb730-ecaa-11e6-8f88-34363bc7c4c0": {
                    "create": 600000000000,
                    "delete": 1800000000000
                },
                "schema_version": "1"
            },
        }
    }
}
```

Terraform 0.12.8:

```javascript
"resources": [{
    "mode": "managed",
    "type": "aws_security_group",
    "name": "example",
    "instances": [
    {
        "schema_version": 1,
        "attributes": {
        "timeouts": null,
        }
    }
    ]
}]
```

**Comment by jbardin** [comment]
Hi @ewbankkit,

Can you show the configuration and steps you're using that results in not having a timeout value?
The defaults are not expected to be stored in the state, and are inserted when creating the resource data.

**Comment by obourdon** [comment]
@jbardin as @ewbankkit mentioned, we are working on PR [#10114 in terraform-providers/terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws/pull/10114) to solve issue [#10044  in terraform-providers/terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws/issues/10044)

Note that this issue only occurs in AWS regions where [new AWS lambda mechanism for 
improving VPC performance](https://aws.amazon.com/blogs/compute/announcing-improved-vpc-networking-for-aws-lambda-functions/) has been pushed, in my case eu-west-1 and eu-central-1

When running the AWS provider acceptance tests in these region, the delete timeout of was security group has [been moved up over 20mn](https://github.com/obourdon/terraform-provider-aws/blob/fix-10044/aws/resource_aws_lambda_function_test.go#L1665:L1667) and [also here](https://github.com/ewbankkit/terraform-provider-aws/blob/issue-10044/aws/resource_aws_security_group.go#L34). However somehow these get reset to the default 20mn timeout

HTH

**Comment by jbardin** [comment]
Thanks @obourdon,

The `"timeouts"` field in the state is only representative of the configuration values. Terraform core isn't aware of the default values, as those are looked up at runtime by the provider SDK. The provider SDK does encode the timeouts into the `"private"` field for later reference however. There was an issue with delete timeout values being lost at one point, but that should only show up with an old AWS provider as it's been fixed for a few months.

The tests we have for this persist both the config values as well as the defaults, so I'm not sure where they are being lost in the AWS provider tests. Does this happen from the command line as well, or is it just in the acceptance tests?

**Comment by ewbankkit** [comment]
@jbardin We noticed this whilst running provider acceptance tests.
