### ISSUE TITLE
MD5 for OSX download hash isn't matching.

### ISSUE THREAD

**Issue by chriswinn** [hashicorp/terraform#22822]
### Terraform Version

```
Terraform v0.12.8
```

### Terraform Configuration Files

```
[terraform_0.12.8_SHA256SUMS.txt](https://github.com/hashicorp/terraform/files/3621755/terraform_0.12.8_SHA256SUMS.txt)
```

### Expected Behavior

```
MD5 (terraform) = 2c2d9d435712f4be989738b7899917ced7c12ab05b8ddc14359ed4ddb1bc9375
```

### Actual Behavior

```
MD5 (terraform) = 3a1def8f91432204ec12a6db9792b3f3
```

### Steps to Reproduce

```
1. `download terraform from "https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_darwin_amd64.zip"`
2. `md5 /path/to/file`
```

**Comment by chriswinn** [comment]
Hey Guys,

No matter what I can't get this to have the correct hash...  I even tried forcing openssl to check the hash as sha256.

 2019-09-17 10:17:17 ⌚  |2.6.3| c17n in ~/Downloads
○ → openssl sha256 terraform
SHA256(terraform)= a355821e74c4dd35ae4a2a845869c8c4055eb8efcfb0d64336027f94dea62036

**Comment by teamterraform** [comment]
Hi @chriswinn,
The SHASUMS are for the zip files, not the unzipped binaries. You can see the filename in SHA256SUMS.txt:


```
grep darwin terraform_0.12.8_SHA256SUMS.txt
2c2d9d435712f4be989738b7899917ced7c12ab05b8ddc14359ed4ddb1bc9375  terraform_0.12.8_darwin_amd64.zip

openssl sha256 terraform_0.12.8_darwin_amd64.zip
SHA256(terraform_0.12.8_darwin_amd64.zip)= 2c2d9d435712f4be989738b7899917ced7c12ab05b8ddc14359ed4ddb1bc9375
```

**Comment by chriswinn** [comment]
Yep, you are correct.  I didn't realize this laptop I just setup was set automatically unzipping downloaded files.

 2019-09-17 12:54:54 |2.6.3| c17n in ~/Dropbox/_/_WorkingOn/__Projects/_BASH
± |master ↑6 U:3 ?:3 ✗| → curl -o terraform_0.12.8_darwin_amd64.zip -k https://releases.hashicorp.com/terraform/0.12.8/terraform_0.12.8_darwin_amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.9M  100 15.9M    0     0  7448k      0  0:00:02  0:00:02 --:--:-- 7450k

 2019-09-17 12:55:54 |2.6.3| c17n in ~/Dropbox/_/_WorkingOn/__Projects/_BASH
± |master ↑6 U:3 ?:4 ✗| → openssl sha256 terraform_0.12.8_darwin_amd64.zip 
SHA256(terraform_0.12.8_darwin_amd64.zip)= 2c2d9d435712f4be989738b7899917ced7c12ab05b8ddc14359ed4ddb1bc9375
