### ISSUE TITLE
Cloned modules with same source are not complete when reused

### ISSUE THREAD

**Issue by kautsig** [hashicorp/terraform#22844]
### Terraform Version

```
Terraform v0.12.8
+ provider.local v1.3.0
```

### Terraform Configuration Files

Create a module file, such as `/home/user/example/module/main.tf`
```
resource "local_file" "example" {
    content     = "this is my example file"
    filename = "${path.module}/example.txt"
}
```
Make sure that `/home/user/example/module/` is a git repository and has a `master` branch.

Make use of that module, e.g in `/home/user/example/main/main.tf`
```hcl
module "module1" {
  source = "git::/home/user/example/module?ref=master"
}

module "module2" {
  source = "git::/home/user/example/module?ref=master"
}
```

### Debug Output

Debug output created using: `TF_LOG=TRACE terraform init -no-color > trace.log 2>&1`

https://gist.github.com/kautsig/817b7902fa3ebd29a67f4d2fea351741

### Crash Output

No crash.

### Expected Behavior

I am expecting the 2 modules created in `.terraform/modules` to be *equal*.

### Actual Behavior

In terraform 0.12 a new way of downloading modules more efficiently was introduced. The function `getWithGoGetter` now checks if a module has been previously downloaded and if so, copies the previous download.

See: https://github.com/hashicorp/terraform/blob/4ecf569aeabad20883185901478810626c792a1f/configs/configload/getter.go#L102

This function uses `copyDir`, which skips dotfiles.

See:
https://github.com/hashicorp/terraform/blob/0c5fd835cec4298b3ad11fc307e064f3aa657953/configs/configload/copy_dir.go#L27

We noticed that, because the `.git` directory was present in some, but not all cloned modules. If it is present depends on whether the modules have been cloned in the same initialize operation.

Looking at the code I would assume it affects arbitrary dotfiles which are part of the module. 

I would expect terraform not to touch the contents of the module. If this is required for some reason, the outcome should be deterministic and not depend on the order in which modules are initialized.

### Steps to Reproduce

1. `terraform init` with the configuration above.

### Additional Context

None.

### References

None.

**Comment by kautsig** [comment]
I checked the assumption if arbitrary dotfiles which are part of the module are affected. 

Yes, they are:

```% ../.terraform/modules diff -r module1 module2
Only in module1: .git
Only in module1: .my-dotfile
Only in module1/nested: .my-dotfile
```

**Comment by mildwonkey** [comment]
Hi @kautsig ! Thank you for reporting this odd behavior. 
Can you please elaborate on any problems this is causing in your environment? If the behavior is simply unexpected, we can update the documentation.

**Comment by kautsig** [comment]
Hi @mildwonkey, thanks for your reply.

What we did is to use the metadata in the `.git` directory of a cloned module to determine the exact git version of the module that was used our repository. We write that metadata to an azure resource group tag to do some bookkeeping of which environments need upgrading etc.

I'd be in favor of fixing it, instead of documenting because:

1) Dotfiles can't break anything, because they are present in the initially cloned module.
2) If tests are done with only 1 module everything works, but breaks as soon a modules is used twice and re-used.
3) It's violating the principle of least surprise that the same module suddenly behaves differently.

Thanks @kmoe for the patch.
