### ISSUE TITLE
No available provider "azure" plugins are compatible with this Terraform version.

### ISSUE THREAD

**Issue by tomarv2** [hashicorp/terraform#22863]
When created `Azure Resource Group` it works:
```
resource "azurerm_resource_group" "rg" {
    name = "demo-rg"
    location = "${var.rg_region}"
```

When trying to deploy `Azure Storage Queue` it does not:
```
resource "azure_storage_queue" "stor-queue" {
  name                 = "demo01"
  storage_service_name = "tfstorserv"
}
```
It saying: No available provider `"azure"` plugins are compatible with this Terraform version.

It should be looking for `azurerm`.

### Terraform Version
```
terraform -v
Terraform v0.12.0
```

Your version of Terraform is out of date! The latest version
is 0.12.9. You can update by downloading from www.terraform.io/downloads.html

Azurerm provider:
`Downloading plugin for provider "azurerm" (hashicorp/azurerm) 1.34.0...`

**Comment by jbardin** [comment]
Hi @tomarv2,

Are you certain you don't mean `azurerm_storage_queue`? There is currently no supported provider called `"azure"`

**Comment by tomarv2** [comment]
@jbardin :

Thanks it worked. 
I was following this doc: https://www.terraform.io/docs/providers/azure/r/storage_queue.html.

```resource "azure_storage_queue" "stor-queue" {
  name                 = "terraform-storage-queue"
  storage_service_name = "tfstorserv"
}
```
