### ISSUE TITLE
Network ACL reporting incorrect resource as source of error

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#2287]
I have a TF file that adds two AWS network ACL's, but TF reports the first as having a duplicate rule #.  If I remove the rule from the second list all is well (this seems to only occur with a rule # of 1).  If I split these resources into two files there is no problem with the exact same ACL's.  Apologies for the pseudo error report.  If you need more info I can reverse my commits and duplicate.

subnet-1-acl {rule 1, rule 10, rule 100}
subnet-2-acl {rule 1, rule 10, rule 100}

error: subnet-1-acl contains duplicate rule '1'

**Comment by mitchellh** [comment]
Can you show a config or repro steps to replicate this? Sorry I can't do it from this information.

**Comment by catsby** [comment]
Hey @mikeyhill – unless you have any more information to share, I'm going to go ahead and close this. Please let me know if you do have something else I can go on, and I'll take another look.

Thanks!

**Comment by mikeyhill** [comment]
Sorry, was out on vacation this week.  I did eventually work around this so I don't have the config that could preproduce anymore.  Hopefully it was just a fluke.

**Comment by catsby** [comment]
OK, thanks for following up :smile:
