### ISSUE TITLE
Error: Mismatch reason: attribute mismatch: ttl.0.attribute_name

### ISSUE THREAD

**Issue by productiveAnalytics** [hashicorp/terraform#22884]
### Terraform Version

```
(Using Terraform with TFEnv)
Terraform v0.11.13
+ provider.aws v2.28.1
+ provider.template v2.1.2

```

### Terraform Configuration Files

```hcl
**dev/terraform.tfvars** file :=
backend_bucket = "hds-chc-dev-medicaltransactions"
backend_key = "hds-terraform/terraform/terraform.state"
backend_region = "us-east-1"
application_name = "qdspac"
application_version = "0.0.0"
ecs_task_execution_role_name = "Hds-EcsTaskExecution"
ecs_task_role_name = "Hds-EcsTask"
environment = "dev"
image = "560395879688.dkr.ecr.us-east-1.amazonaws.com/hds-dev-qdspac"
context = "v0"
desired_count = 10
cpu = 1024
memory = 2048
read_capacity = 5
write_capacity = 5

**dev/tf.backend** file :=
encrypt = true
bucket = "hds-chc-dev-medicaltransactions"
region = "us-east-1"
dynamodb_table = "hds-terraform-state-lock-dynamo"
key = "qdspac/terraform/terraform.state"
```

### Crash Output

* module.ecs-service.module.qdspac_data_ddb.aws_dynamodb_table.dynamodb: aws_dynamodb_table.dynamodb: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.13
    Resource ID: aws_dynamodb_table.dynamodb
    Mismatch reason: attribute mismatch: ttl.0.attribute_name
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"server_side_encryption.0.enabled":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.APP_ID":*terraform.ResourceAttrDiff{Old:"38", New:"38", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.3095739102.type":*terraform.ResourceAttrDiff{Old:"S", New:"S", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"hds-c8a62fc-qdspac-data-c8a62fc", New:"hds-c8a62fc-qdspac-c8a62fc-data", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "server_side_encryption.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.941019757.type":*terraform.ResourceAttrDiff{Old:"S", New:"S", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.3095739102.name":*terraform.ResourceAttrDiff{Old:"data_id", New:"data_id", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "range_key":*terraform.ResourceAttrDiff{Old:"payer_id", New:"payer_id", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stream_label":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "point_in_time_recovery.0.enabled":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "read_capacity":*terraform.ResourceAttrDiff{Old:"0", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"arn:aws:dynamodb:us-east-1:560395879688:table/hds-c8a62fc-qdspac-data-c8a62fc", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ttl.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stream_arn":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "write_capacity":*terraform.ResourceAttrDiff{Old:"0", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "point_in_time_recovery.#":*terraform.ResourceAttrDiff{Old:"1", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.COST_CENTER":*terraform.ResourceAttrDiff{Old:"30138", New:"30138", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.#":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Billing":*terraform.ResourceAttrDiff{Old:"MedicalTransactions/hds", New:"MedicalTransactions/hds", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.CI_TYPE":*terraform.ResourceAttrDiff{Old:"HDS", New:"HDS", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"5", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stream_enabled":*terraform.ResourceAttrDiff{Old:"false", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stream_view_type":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:"", RequiresNew:false, Sensitive:false, Type:0x0}, "billing_mode":*terraform.ResourceAttrDiff{Old:"PAY_PER_REQUEST", New:"PAY_PER_REQUEST", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "hash_key":*terraform.ResourceAttrDiff{Old:"data_id", New:"data_id", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ttl.0.enabled":*terraform.ResourceAttrDiff{Old:"true", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ttl.0.attribute_name":*terraform.ResourceAttrDiff{Old:"Expires", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Description":*terraform.ResourceAttrDiff{Old:"env=c8a62fc/appid=38/monitor=false/team=hds", New:"env=c8a62fc/appid=38/monitor=false/team=hds", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.941019757.name":*terraform.ResourceAttrDiff{Old:"payer_id", New:"payer_id", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"attribute.#":*terraform.ResourceAttrDiff{Old:"", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.3095739102.name":*terraform.ResourceAttrDiff{Old:"", New:"data_id", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.CI_TYPE":*terraform.ResourceAttrDiff{Old:"", New:"HDS", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "point_in_time_recovery.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stream_label":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Billing":*terraform.ResourceAttrDiff{Old:"", New:"MedicalTransactions/hds", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Description":*terraform.ResourceAttrDiff{Old:"", New:"env=c8a62fc/appid=38/monitor=false/team=hds", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "server_side_encryption.0.enabled":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "range_key":*terraform.ResourceAttrDiff{Old:"", New:"payer_id", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "point_in_time_recovery.0.enabled":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stream_enabled":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ttl.0.enabled":*terraform.ResourceAttrDiff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.3095739102.type":*terraform.ResourceAttrDiff{Old:"", New:"S", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "write_capacity":*terraform.ResourceAttrDiff{Old:"", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.APP_ID":*terraform.ResourceAttrDiff{Old:"", New:"38", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "server_side_encryption.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "billing_mode":*terraform.ResourceAttrDiff{Old:"", New:"PAY_PER_REQUEST", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.941019757.name":*terraform.ResourceAttrDiff{Old:"", New:"payer_id", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "attribute.941019757.type":*terraform.ResourceAttrDiff{Old:"", New:"S", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.COST_CENTER":*terraform.ResourceAttrDiff{Old:"", New:"30138", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "read_capacity":*terraform.ResourceAttrDiff{Old:"", New:"5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"hds-c8a62fc-qdspac-c8a62fc-data", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "stream_view_type":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:"", RequiresNew:false, Sensitive:false, Type:0x0}, "hash_key":*terraform.ResourceAttrDiff{Old:"", New:"data_id", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ttl.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "stream_arn":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

### Expected Behavior

Terraform to create DynamoDB table

### Actual Behavior

Terraform crashed...It suggested to report bug.

### Steps to Reproduce

export GIT_HASH=`git rev-parse --short HEAD`
echo GIT_HASH=$GIT_HASH
terraform workspace new $GIT_HASH
terraform workspace select $GIT_HASH || true
terraform init -backend-config=dev/dev.tfbackend
terraform validate \
   -var-file=dev/terraform.tfvars \
   -var "application_version=${GIT_HASH}" \
   -var "context=$GIT_HASH"
terraform plan \
   -var-file=dev/terraform.tfvars \
   -var "application_version=${GIT_HASH}" \
   -var "context=$GIT_HASH" \
   -target module.ecs-service \
   -out planfile

**Comment by teamterraform** [comment]
Hello!

Thanks for reporting this issue. Unfortunately the error output in this "diffs didn't match" situation is often not enough to diagnose the problem. Starting in 0.12 the situation that causes this error is more precisely reported, and the necessary debugging information is recorded in the logs. If this issue persists after upgrading Terraform, please file an issue with the referenced provider.

Thanks
