### ISSUE TITLE
terraform registry stuck publishing module

### ISSUE THREAD

**Issue by tesharp** [hashicorp/terraform#22925]
Terraform registry seems to be stuck on publising our module (https://registry.terraform.io/modules/avinor/application-gateway/azurerm). Cannot publish it again as it says it has already been published. Initially when I published I got an error that block configuration at line 2 in main.tf was incorrect, but its the same as in any other module I've published.

Tried to untag it and publish again but same error. Not able to publish this module..

**Comment by findkim** [comment]
Hi @tesharp sorry for this unexpected behavior with the Registry and thanks for reporting it. I've cleared up the stuck record for `application-gateway`, you should now be able to publish the module.
