### ISSUE TITLE
VM Deploy issue

### ISSUE THREAD

**Issue by tjoyce-admin** [hashicorp/terraform#22933]
When trying to deploy a VM, terraform crashes as the VM completes the creation process. Here is the version of terraform I am using:
Terraform v0.12.8
+ provider.vsphere v1.12.0

[crash.log](https://github.com/hashicorp/terraform/files/3663952/crash.log)

**Comment by tjoyce-admin** [comment]
Here is my main terraform document in case you need it:


data "vsphere_datacenter" "dc" {
  name = "${var.vmdc}"
}

data "vsphere_datastore" "datastore" {
  name          = "${lookup(var.vmdatastore, var.vmprotectionpolicy)}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "${lookup(var.vmcluster,var.vmenvironment)}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "${var.vmnetlabel}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "_Template/${lookup(var.vmtemp, var.vmOS)}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "DeployVM" {
  name             = "${var.vmname}"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = "${var.vmcpu}"
  memory   = "${var.vmmemory}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size 	     = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  disk {
    label            = "disk1"
    unit_number	     = "1"
    size 	     = "${data.vsphere_virtual_machine.template.disks.1.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.1.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.1.thin_provisioned}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      windows_options {
        computer_name  = "${var.vmname}"
        join_domain      = "${var.vmdomain}"
	domain_admin_user = "${var.viuser}"
        domain_admin_password  = "${var.vipassword}"
      }

      network_interface {
        ipv4_address = "${var.vmipaddress}"
        ipv4_netmask = "${var.vmsubnetlength}"
      }

      ipv4_gateway = "${var.vmgateway}"
    }
  }
}
# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = "${var.viuser}"
  password       = "${var.vipassword}"
  vsphere_server = "vc.teckcominco.loc"

  # if you have a self-signed cert
  allow_unverified_ssl = true
#  persist_session = true
}

**Comment by kmoe** [comment]
Thanks for providing the crash log and Terraform config, @tjoyce-admin. I've edited your second post to ensure the code is formatted properly.

From the crash log you provided, it looks like the `panic` is in the vSphere provider. Your issue may be related to https://github.com/terraform-providers/terraform-provider-vsphere/issues/822. I'm tagging this as a provider issue - if it turns out after investigation that this is a Core issue, please reopen an issue in this repository, making sure you follow the issue template.
