### ISSUE TITLE
Google instance should support disk update

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#2296]
This requires splitting into root_disk and extra_disk as done for aws_instance.

root_disk is immutable and can be created with an image, extra_disk can only take an explicit pre-created disk.

This change will require a deprecation cycle and a state update function.

**Comment by sparkprime** [comment]
This is also an opportunity to make the Terraform resource closely match the API

**Comment by iiro** [comment]
Does this apply for disk resizing as well? It seems it's not possible to resize disks with TF now - but you can do it using the APIs...

**Comment by sparkprime** [comment]
You'd do that by having a separate disk resource and referring to it in the instance with a ${} ref, and then modifying the disk.  So if you want that you should file an issue on the disk resource.  But the feature is in the beta API now which makes it a pain to use from Terraform because all the self links change.  It's still worth tracking it in an issue though.

I'm not sure on the exact semantics of the resize.  Does the disk need to be detached?  Can you shrink as well as grow? etc.

**Comment by iiro** [comment]
Yea, noticed that it's still in beta so probably time to just wait...

To my understanding it's a completely online operation - so disk can be attached when resizing. Just tested, can only grow, does not allow shrinking.

**Comment by iiro** [comment]
...and Google has announced it: https://cloudplatform.googleblog.com/2016/03/introducing-Google-Cloud-Persistent-Disks-with-non-disruptive-online-resizing.html

I created #5968

**Comment by paddyforan** [comment]
It seems that we support this now, as we have the `google_compute_disk` type, and you can have multiple disks per instance. If I'm missing something, could you provide some information on a use case? E.g., what are you trying to update?

**Comment by mitchellh** [comment]
Hello! I'm going through `waiting-response` labeled issues and closing issues that haven't been responded to with a meaningful response in at least 2+ weeks. If this is still an issue, please open a new issue so we can start anew. Feel free to reference this existing issue to make a link between the two. Thanks!
