### ISSUE TITLE
aws_ebs_volume - using iops=false and type=gp2 causes new resource every run

### ISSUE THREAD

**Issue by jc-asdf** [hashicorp/terraform#2298]
I've found that when generating a new volume with both type=gp2 and iops=false (which is a bit of an edge case, I admit), every run forces a resource replacement.

    -/+ module.staging_member_service.mysql_db_server.aws_ebs_volume.db_volumes
        availability_zone: "us-east-1b" => "us-east-1b"
        encrypted:         "false" => "<computed>"
        iops:              "300" => "0" (forces new resource)
        kms_key_id:        "" => "<computed>"
        size:              "100" => "100"
    (rest trimmed)

It looks like it's reading the AWS default 3 IOPS/GB, and comparing to the desired 0 iops, forcing a refresh.

However, specifying both iops > 0 and type != io1 generates an error (as it should).

I think the desired behaviour should be to ignore the IOPS on the volume if the type is not io1.  I do want to keep the ability to have both the type and iops parameters specified, so that they can be populated in a flexible way.

**Comment by catsby** [comment]
Hey there @jc-asdf – sorry for the silence here. I've patched this behavior in #4146
