### ISSUE TITLE
Terraform doesn't compile

### ISSUE THREAD

**Issue by michaeltchapman** [hashicorp/terraform#2300]
builtin/providers/aws/resource_aws_iam_group_membership_test.go:62: wrong number of args for format in Errorf call: 1 needed but 2 args

Vet found suspicious constructs. Please check the reported constructs
and fix them if necessary before submitting the code for review.
make[1]: *** [vet] Error 1
make: *** [test] Error 2

Addressed by #2299

**Comment by phinze** [comment]
Dang - Why didn't the Travis build catch this for us?

https://travis-ci.org/hashicorp/terraform/jobs/66059865
