### ISSUE TITLE
Panic/crash when running 'terraform init -from-module=' when module contains another module

### ISSUE THREAD

**Issue by tamsky** [hashicorp/terraform#23010]
### Terraform Configuration Files

I've created a repo that contains a minimal example that triggers the crash:
- https://github.com/tamsky/terraform-0.12.9-init-from-module-crash-example

Invoke repo with `make crash` or `make nocrash`

### Debug Output
I'll assume the `crash.log` file below is sufficient.

### Crash Output
- https://github.com/tamsky/terraform-0.12.9-init-from-module-crash-example/blob/master/crash.log

### Expected Behavior
`terraform init -from-module=...` should initialize without panic

### Actual Behavior
panic.

### Steps to Reproduce
run `make crash` in above linked example repo.

### References
- #21653

**Comment by tamsky** [comment]
https://github.com/hashicorp/terraform/issues/21653#issuecomment-500051495 (from Jun 7 2019):
> … something about calling init -from-module=foo on a module foo that itself contains a module with source set to a relative path causes a crash.

this appears to still be true

**Comment by askoriy** [comment]
Duplicate #22973

**Comment by danieldreier** [comment]
I have reproduced this on 0.12.26 and 0.13.0 beta 1 using `make crash`. Thank you for the excellent reproduction case!

**Comment by mildwonkey** [comment]
🎉  This has been fixed, and I managed to get it merged just in time for our next Terraform v0.13-beta release!
