### ISSUE TITLE
Terraform exit code is 0 when state lock deletion fails

### ISSUE THREAD

**Issue by saveriomiroddi** [hashicorp/terraform#23017]
### Terraform Version

0.12.7

### Expected Behavior

If the state lock deletion fails, Terraform should exit with an error code (e.g. 1).

### Actual Behavior

If the state lock deletion fails, Terraform exits with code 0.

### Steps to Reproduce

- Set an S3-backed TF storage, with a dynamodb table
- Revoke the `dynamodb:DeleteItem` permission from the AWS user that performs the TF operation(s)
- Execute a `plan` operation

**Comment by mildwonkey** [comment]
👋 This has been fixed, but just so y'all know the fix is targeting Terraform v0.14. Thanks!
