### ISSUE TITLE
Keep interactive variable hidden

### ISSUE THREAD

**Issue by carmineesposito73** [hashicorp/terraform#23022]
# Current Terraform Version
```
$ terraform -v
Terraform v0.12.9
+ provider.vcd v2.5.0
```

### Use-cases
Usage of password or some sensitive information are always required, I haven't find a way to keep variables hidden

### Attempted Solutions
I tryed to use interactive input, but terraform does not hyde input
```
variable "password" {
  type = string
}

$ terraform plan
var.password
  Enter a value: CLEAR_TEXT
```

### Proposal
Introduce a parameter to hide variable when inserted interactively
```
variable "password" {
  type = string
  sensitive = true
}
```
the attended result:
```
$ terraform plan
var.password
  Enter a value: **********
```
### References
`sensitive` parameter is already present in `output`
- #5511

**Comment by 27Bslash6** [comment]
+1 

This feature seems critical for protecting secrets in open source CI

**Comment by nokernel** [comment]
Might also hide locals. Basically anything in plan can be a secret, and they would need to be masked.

**Comment by nfroidure** [comment]
I agree with @nokernel , we should default to security and instead opt-out of the `sensitive` property and let it default to `true`.

**Comment by apparentlymart** [comment]
Terraform v0.14.0 includes [a way to mark input variables as sensitive](https://www.terraform.io/docs/configuration/variables.html#suppressing-values-in-cli-output).

**Comment by nokernel** [comment]
Still missing local if I understand the documentation right.
