### ISSUE TITLE
Keypair not being added to instances

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#2302]
I have a keypair that's been working for all the instances I've added with Terraform and it suddenly stopped being added a few hours ago.  It took me a while to figure out this was an issue as there are no problems reported when I add a new instance.

The keypair is being added and has the correct fingerprint.  When I create a new instance in AWS I can see that TF is displaying the correct keypair name, but it is never associated with the instance.  I can associate the keypair with an instance manually in the AWS console so I believe this is an issue with Terraform.  I have also tried directly using the name of the keypair instead of calling it with ${var.keypair} and that does not associate it either.

      instance_type:                                  "" => "m3.medium"
      key_name:                                       "" => "preprod-ops-key"  (this is the correct key name)

**Comment by mikeyhill** [comment]
I'm checking other TF scripts that have not been changed in several weeks and they to are having this same issue.  I did update TF earlier today so I will try reverting back to an earlier changeset to see if I can pinpoint the cause.

**Comment by mikeyhill** [comment]
Seems this was introduced in 05e06d4afdbfb69216d01d08c9b6e41871ccd95e ; the commit just before that (4d59019288f2c2a3bd519728ba841eec7f4e6e59) works for me.

**Comment by catsby** [comment]
Hey @mikeyhill –  05e06d4 didn't change anything in that area, so that's suspicious. Do you have a minimum Terraform config file that reproduces this? If you do and don't mind sharing, please be sure to omit any secrets from the file.

**Comment by mikeyhill** [comment]
@catsby  - I'm a bit short on time right now, but as soon as I catch up I'll condense that portion for you and test to make sure.

**Comment by knuckolls** [comment]
Just to confirm this issue, I'm having the exact same problem.

**Comment by knuckolls** [comment]
"Seems this was introduced in 05e06d4 ; the commit just before that (4d59019) works for me."

I can confirm that the 05e06d4 is the broken commit and that 4d59019 works. Not being able to bootstrap ec2 instances is a pretty big breaking change. I vote for reverting that commit until we figure out what the deal is.

**Comment by catsby** [comment]
I've found the issue, I'll send a patch in just a few...

**Comment by catsby** [comment]
Patched in https://github.com/hashicorp/terraform/pull/2307 . Introduced in 112724fc3910baed280965fabf579269c180e7b0 , likely just a simple oversight in placement of `KeyPair`. I added an acceptance test to catch any regressions.

**Comment by catsby** [comment]
By the way, thank you for reporting!

**Comment by catsby** [comment]
#2307 was merged, sorry for the trouble here :smile:

**Comment by knuckolls** [comment]
Thanks for the quick response!

**Comment by mikeyhill** [comment]
@catsby - confirmed working.  thanks for the quick fix on that :)
