### ISSUE TITLE
Terraform v0.12.10 Error: Invalid index only when using -out=plan.out

### ISSUE THREAD

**Issue by shadycuz** [hashicorp/terraform#23032]
### Terraform Version

```
Terraform v0.12.10
+ provider.aws v2.31.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl

variable "environment" {
  description = "Environment label that is added to resources"
}

variable "env_map" {
  type        = map(object({
    account_id = string
    session_name = string
  }))
  
  description = "Mapping of X Environments to Y Environments."

  default = {
    upgrade12 = {
      account_id   = "XXXXXXXX"
      session_name = "dev23-XXX-session"
    }

    XXXX = {
      account_id   = "XXXXX"
      session_name = "XXX-session"
    }
...
  }
}

data "aws_iam_policy_document" "XXX_role_allow_assume" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type = "AWS"
      # TF-UPGRADE-TODO: In Terraform v0.10 and earlier, it was sometimes necessary to
      # force an interpolation expression to be interpreted as a list by wrapping it
      # in an extra set of list brackets. That form was supported for compatibility in
      # v0.11, but is no longer supported in Terraform v0.12.
      #
      # If the expression in the following list itself returns a list, remove the
      # brackets to avoid interpretation as a list of lists. If the expression
      # returns a single list item then leave it as-is and remove this TODO comment.
      identifiers = [var.env_map[var.environment]["account_id"]]
    }
  }
}
```

### Debug Output

Can provide if you need

### Crash Output

No crash.
### Expected Behavior

Running `terraform plan -input=false -var 'environment="upgade12"' -out=plan.out -detailed-exitcode` should produce a valid plan just like `terraform plan` does.

### Actual Behavior
I get an error about my identifiers.

```
Error: Invalid index

  on iam.tf line 110, in data "aws_iam_policy_document" "developers_role_allow_assume":
 110:       identifiers = [var.shared_services_account, var.env_map[var.environment]["account_id"]]
    |----------------
    | var.environment is "\"upgrade12\""
    | var.env_map is map of object with 8 elements

The given key does not identify an element in this collection value.


Error: Invalid index

  on iam.tf line 181, in data "aws_iam_policy_document" "XXX_role_allow_assume":
 181:       identifiers = [var.env_map[var.environment]["account_id"]]
    |----------------
    | var.environment is "\"upgrade12\""
    | var.env_map is map of object with 8 elements

The given key does not identify an element in this collection value.

Releasing state lock. This may take a few moments...
```
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform plan`
4. `terraform plan -input=false -var 'environment="upgade12"' -out=plan.out -detailed-exitcode`

It doesn't fail until step 4. Step 3 works fine.

### Additional Context

I just upgraded my terraform config from 0.11.14 to 0.12.10. That went really smooth. Then all the cicd builds started failing. It seems that adding the `-out=plan.out` is the culprit or something to do with passing in vars on the command line.

### References

Possibly related?
- #22956

**Comment by teamterraform** [comment]
Hi @shadycuz!

Based on the error message, it seems like the problem here is the `-var 'environment="upgade12"'` argument rather than the `-out=plan.out` argument.

Due to how you've quoted it, Terraform is understanding that you want to set the `environment` variable to `"upgade12"` (with the quotes) rather than `upgrade12` (without the quotes). The quotes are taken literally because you wrote the whole argument in `'` single quotes, which prevents those quotes from being interpreted by the shell.

We think it'll work as you expected if you remove those inner quotes:

```
terraform plan -input=false -var 'environment=upgade12' -out=plan.out -detailed-exitcode
```

Could you give that a try and let us know what happens? Thanks!

**Comment by shadycuz** [comment]
@teamterraform 

Yes it would appear the syntax for passing vars in via the command line has changed from terraform 11 to 12. Thanks for the help.
