### ISSUE TITLE
Experimental Terraform Branch Releases

### ISSUE THREAD

**Issue by pwillis-els** [hashicorp/terraform#23045]
### Current Terraform Version
0.11.14

### Use-cases
Testing experimental features which do not currently have a plan to be incorporated into the mainline tree

### Attempted Solutions
I have not created my own fork yet, but I have been considering it.

### Proposal
This proposal is to suggest an alpha branch of Terraform for experimenting with features that users suggest.

The idea is that if people really want a feature, either they or HashiCorp can submit a PR, and if there is complete test coverage and all tests pass, and the feature does not conflict with any other feature or otherwise change functionality that people depend on, that PR can be merged and a release issued. This would enable rapid testing of scientific experiments aimed at improving the user experience of Terraform.

I propose this rather than having people fork their own branch, because it can be difficult to find and engage with other users to help test a personal fork. By using branches off the main Terraform project, an experiment can be groomed before any code hits the tree, and multiple users can give feedback. This would enable rapid development of features without the need for HashiCorp to take it on solely on their end. (One of the nice use cases of open source software)

Off the top of my head, some of the experiments I've considered are adding a feature to prevent secrets from getting into the terraform state, some command-line shortcuts that combine several common operations into a single command, improving the import feature by attempting to auto-import resources when it makes sense, easier to define "guard rails" (possibly a feature flag) around dangerous operations, and bug fixes around things like trying to destroy resources of sub-sub-modules when you try to remove the provider, and used inherited providers fine to create the resource, but terraform doesn't accept the inherited provider for destroying the now-missing module.

### References
I looked but I didn't find a similar suggestion.

**Comment by pkolyvas** [comment]
I think this a good opportunity to share that test coverage, tests passing, and an apparent lack of conflict are not the only criteria that go into evaluating whether we should include specific community contributions in Terraform. 

As maintainers of Terraform, the onus is on us to manage deficiencies or unexpected side effects of new features within Terraform. This applies to all contributions, including our own. It's (relatively) easy to add something, it's much harder to change that something once released. It's incredibly difficult to remove. Third party provisioners were good evidence of that. We have to be extremely judicious about what kind of contributions we'll accept, even when, at first glance, those contributions are either extremely popular or seem to answer a desperate need. 

Our hope, over the next couple of months is to iterate on a process that starts less with coding and more with the collaborative design of new features, additions or changes, such that by the time a PR (distinct from a draft-PR) lands for review, there's been an explicit willingness to spend the time to test, review and iterate on that contribution. This is doubly important for extremely large changes or new features. 

I hope that, in concert with our new alpha releases, we will find a viable middle ground that balances the ability to collaborate and contribute to this project with the need to carefully design, support, and maintain it. It won't please everyone, but we will try to develop and iterate on these processes in the open; welcoming the feedback of our community along the way.

**Comment by pwillis-els** [comment]
I think alpha releases are a great idea! Is there maybe a middle way, where a ci/cd process cuts alpha releases based on somebody's experimental branch, and users can test it and give feedback back into the design, etc? (Maybe this is basically your idea already?) You don't even need to give it a version, so nobody thinks it will become an eventual feature (until it makes it to beta, pre-release, etc)

The following thoughts are intended as constructive criticism - I apologize if it comes off as lecturing/talking down 😅

> it's much harder to change that something once released. It's incredibly difficult to remove.

Sure, it can be. But Terraform has introduced at least two major breaking-change releases in the past year and a half, and now 0.14 is on the horizon. I think you've already dipped your toes into the world of long-lived major branches and new majors that remove features.

From the perspective of an enterprise user, changing between breaking versions is a gradual process that we don't like to do often. That's why long-term support is so important to us: we don't want to refactor every 6 months. But we are basically fine with refactoring every 2 years (coupled hopefully with a clearly documented migration path; the tools to upgrade or reformat configs are a great help, coupled with in-depth guides and errata).

> Our hope, over the next couple of months is to iterate on a process that starts less with coding and more with the collaborative design of new features, additions or changes, such that by the time a PR (distinct from a draft-PR) lands for review, there's been an explicit willingness to spend the time to test, review and iterate on that contribution. This is doubly important for extremely large changes or new features.

You don't think this is maybe Waterfall 2.0? If you just slowly grind on it until you think it's done, then as soon as you release, somebody starts to use it, and you find out it still needed work. Features almost always need to change. If you don't have a strategy to both release your features and change them over time, you end up fighting entropy.

But I agree that collaboration on big changes is essential. That's part of how experimental branches can help: you cut a new branch and ask people to bang on it. By moving this into the open-source world, but still keeping it a part of your project, you can keep the momentum of communal driving of change within your product, without having to expend your own resources. And of course you still get final say over what ends up, but the product ends up reflecting the needs of the community as they grow a more active role in development.

I guess basically what I'm asking for is more of a cultural shift in development to try to foster outside collaborators to cut new branches and test out new features (in alpha!), without having to go through your org.

**Comment by pwillis-els** [comment]
It sounds like you already have a plan you're moving forward with though, so I'll leave the convo here. Looking forward to see what comes next

**Comment by pkolyvas** [comment]
Appreciate your insight Peter and thanks for taking the time to share it. 

Just a quick point of clarification, the "process" I'm talking is the process of moving enhancement requests towards design of the features / contributions before they go to PR; not the evolution/iteration that comes afterward. 

Stated more simply, our currently goal is to signal, early on, whether we'd even take a contribution in a given area. Once that's been made clear, be able to explicitly commit to helping collaborate on the initial design of a feature.
