### ISSUE TITLE
Native Provisioner support for ssh options

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2304]
I'd like to see connection options for ssh options, (e.g. ssh -o x=y) so that it is possible to handle ssh hopping through a jumpbox in a remote-exec, rather than feeding IPs to a local script via a local-exec, as well as sending keepalive packets and other such niceties.

**Comment by mrwacky42** [comment]
@gtmtech  - See also #1709.

**Comment by mitchellh** [comment]
We got jump box support in #1709. Arbitrary option support is difficult since we don't use OpenSSH, we use an SSH implementation in pure Go. If you have a specific request, let us know and we'll check it out.
