### ISSUE TITLE
panic on passing non-string key to map()

### ISSUE THREAD

**Issue by alxrem** [hashicorp/terraform#23043]
### Terraform Version

```
Terraform v0.12.10
+ provider.local v1.3.0
```

### Terraform Configuration Files

```hcl
locals {
	a = map(1, 1)
}
```

### Debug Output

https://gist.github.com/alxrem/16972d40bbfe8df2fbecac6720a9b5a8

### Crash Output

https://gist.github.com/alxrem/af55977e452fbd3c6be0c192c05bc3bd

### Expected Behavior

Error message from syntax parser.

### Actual Behavior

Panic

### Steps to Reproduce

```
cat <<EOF >bug.tf
locals {
	a = map(1, 1)
}
EOF
terraform init
terraform plan
```

**Comment by mjgpy3** [comment]
@alxrem this function appears to be depreciated in terraform 0.12: https://www.terraform.io/docs/configuration/functions/map.html

**Comment by alxrem** [comment]
Thank you. I don't use it, only reported the noticed bug.
