### ISSUE TITLE
"Invalid for_each argument" incorrectly thrown 

### ISSUE THREAD

**Issue by Leftbrained** [hashicorp/terraform#23052]
### Terraform Version
```
Terraform v0.12.10
+ provider.google v2.17.0
```

### Terraform Configuration Files
```hcl
resource "google_folder" "bu" {
  display_name = "folderdisplayname"
  parent       = "folderparent"
}

locals {
  context = merge({
    folder        = google_folder.bu.name
    members = [
      {
        name = "username",
        identity = "useridentity",
      },
    ]
    roles = [
      "roles/foobar",
    ]
  })
}

resource "google_project_iam_member" "members" {
  for_each = {
    for values in setproduct(local.context.members, local.context.roles):
    "${values[0].name} ${values[1]}" => {
      member = values[0].identity
      role   = values[1]
    }
  }
  project  = "foobarid"
  member   = each.value.member
  role     = each.value.role
}
```

### Debug Output
https://gist.github.com/Leftbrained/fe291ef218727fb42521d0c83d29e6ec

### Crash Output
N/A

### Expected Behavior
Upon running `terraform plan` I should see that two resources should be created:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_folder.bu will be created
  + resource "google_folder" "bu" {
      + create_time     = (known after apply)
      + display_name    = "folderdisplayname"
      + id              = (known after apply)
      + lifecycle_state = (known after apply)
      + name            = (known after apply)
      + parent          = "folderparent"
    }

  # google_project_iam_member.members["username roles/foobar"] will be created
  + resource "google_project_iam_member" "members" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + member  = "useridentity"
      + project = "foobarid"
      + role    = "roles/foobar"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Actual Behavior
`terraform plan` results in this error
```
Error: Invalid for_each argument

  on main.tf line 22, in resource "google_project_iam_member" "members":
  22:   for_each = {
  23:     for values in setproduct(local.context.members, local.context.roles):
  24:     "${values[0].name} ${values[1]}" => {
  25:       member = values[0].identity
  26:       role   = values[1]
  27:     }
  28:   }

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
There are two ways to change the .tf file to make this work:
1. Remove the merge() function call on lines 7-18, but leave the map. I believe the merge function is where this issue actually is.
2. Set `local.context.folder` to a string, i.e. `"folderparent"`

### References
This issue may be related:
- #22735

**Comment by mixmatch** [comment]
```
terraform init
terraform plan -target=google_folder.bu -out=tfplan
terraform apply tfplan
terraform plan
```

**Comment by lesurfl** [comment]
I believe I'm seeing a similar issue with merge()

I use a module as below:

```
module "instance_profile" {
  source = "../iam-instance-profile"
  providers = {
    aws = aws
  }

  name_prefix = var.service_name
  policies = merge(var.custom_policies)
}
```

The relevant part of the module looks like this:

```
resource "aws_iam_role_policy" "role_policy" {
  for_each = var.policies
  name     = "${var.name_prefix}-${each.key}-policy"

  role = aws_iam_role.role.id

  policy = each.value

}
```

If i use `policies = var.custom_policies`, everything is fine however if I use `policies = merge(var.custom_policies)` it causes:

```
Error: Invalid for_each argument

  on ../../../../generic-modules/iam-instance-profile/main.tf line 34, in resource "aws_iam_role_policy" "role_policy":
  34:   for_each = var.policies

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

The content of the variable custom_policies does not change between these two runs. (Obviously, I'd usually have more that one map in the merge but only one map is needed to cause the error here)

**Comment by pielu** [comment]
I confirm merge() breaking _for_each_ behavior as well. The error is somewhat misleading (still better than the previously a crash, of course), pointing toward interpolation issue(s) while in fact ridding of merge and leaving interpolations in place as-were actually works just fine.

**Comment by pselle** [comment]
Hello all, I've opened a PR to update the documentation to make it clearer -- it's likely in your `merge` implementations that there are cases where the _keys_ of the `for_each` value are not known when you are trying to plan/apply, and am closing this issue.

Keys *must* be known (either known, or through targeted applies) as resources are keyed off of those instances. If you've created a dependency (such as relying on a computed value provided by a provider), you'll end up with the `-target` error.
