### ISSUE TITLE
Terraform data source not aware of workspaces

### ISSUE THREAD

**Issue by pscadiz** [hashicorp/terraform#23067]
### Terraform Version
```
Terraform v0.12.9
```

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    bucket         = "terraform12-tfstate"
    key            = "applications/app.tfstate"
    dynamodb_table = "terraform12-lock"
    region         = "us-east-1"
  }
}

data "terraform_remote_state" "network" {
  backend = "s3"

  config = {
    bucket = "terraform12-tfstate"
    key    = "env:/${terraform.workspace}/networks/network.tfstate"
    region = "us-east-1"
  }
}
```

### Steps to Reproduce
terraform plan

Just wanted to clarify something here. I recently started using workspaces (along with upgrading to 0.12) and ran into an issue where configuring the data source key is kind of explicit instead of how the workspace is already implied in setting the backend

I am getting the "Unable to find remote state" error with the following config, with the assumption that the data sources follow the same workspace config as the backend
```hcl
data "terraform_remote_state" "network" {
  backend = "s3"

  config = {
    bucket = "terraform12-tfstate"
    key    = "networks/network.tfstate"
    region = "us-east-1"
  }
}
```

Is this expected? Do data sources really not follow workspaces the way backends do?

**Comment by jbardin** [comment]
Hi @pscadiz,

 I would not recommend using the internal implementation of the workspace path to locate the remote state file. The terraform remote state data source has a [`workspace` argument](https://www.terraform.io/docs/providers/terraform/d/remote_state.html#workspace) you can set to specify the workspace to use if it's supported.

If you want it to use the same workspace as the cli, then you would assign the `terraform.workspace` variable to that argument.

**Comment by pscadiz** [comment]
Thank you for the clarification, I can see the sense in such an implementation
