### ISSUE TITLE
dag noise logs

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/terraform#23072]
Does it possible to disable expensive output when walking on AcyclicGraph?
for example this line https://github.com/hashicorp/terraform/blob/master/dag/walk.go#L142
why it not guarded by some variable to be able to disable this output?

**Comment by jbardin** [comment]
Hi @vtolstov,

All the graph transformation is logged as `TRACE`. Is there significant output at that log level you regularly need besides the graph transformations and walk steps? Since `TRACE` is the highest log level, it would probably be easier to lower some specific calls that are more frequently needed to something like `DEBUG` than to change all graph logging throughout terraform.

**Comment by vtolstov** [comment]
why this messages printed directed via fmt.Printf and via some logger that can be able to lower error level and not display such messages?

**Comment by jbardin** [comment]
Hi @vtolstov,

Can you clarify what messages you're referring to? The link above points to a `TRACE` message written via the `log` package, which is in turn filtered by tags, and the `terraform` package itself doesn't write anything out via `fmt.Print*` functions.

**Comment by vtolstov** [comment]
log.Print("[TRACE] dag/walk: updating graph") message directly outputed via log std package
How can i silent it?

**Comment by jbardin** [comment]
The cli assigns a log output that filters the log messages by the log level, and that line would only be written out with `TF_LOG=trace`. You can filter them with a lower log level like `TF_LOG=debug`.

**Comment by vtolstov** [comment]
nice, and if i'm try to use this dag package via own software as library?

**Comment by jbardin** [comment]
The terraform packages were not meant to be consumed by anything other than the terraform cli, so unfortunately they are often not written in such a way that they can be easily used as dependencies in other projects.

This is using the std `log` package, so a custom output can be set to filter the unwanted lines, which is precisely how the cli itself works. Until we get around to reevaluating how logging is handled in terraform as a whole (we would like logging to be more structured and customizable within the project), there are unlikely to be changes to individual parts of the cli.
