### ISSUE TITLE
terraform module download doesn't follow .gitconfig

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#23089]
### Terraform Version
```
Terraform v0.12.10
terragrunt version v0.20.4
```

### .gitconfig
```
[url "https://github.com/"]
	insteadOf = git@github.com:
[url "https://bitbucket.org/"]
	insteadOf = git@bitbucket.org:
```

### Debug Output
```
Downloading git::git@github.com:hashicorp/terraform-aws-consul.git?ref=v0.7.3 for consul_servers.consul_servers_aws...
- consul_servers.consul_servers_aws in .terraform/modules/consul_servers.consul_servers_aws/modules/consul-cluster
```

### Expected Behavior
for terraform to download the modules using https with github personal token

### Actual Behavior
terraform downloads using ssh key, which requires unlocking

### Steps to Reproduce
1. `terraform init`

**Comment by teamterraform** [comment]
Hi @FernandoMiguel! Sorry for this behavior and thanks for reporting it.

The output you shared here doesn't include any prompts that seem to suggest that it used SSH rather than HTTPS. Did you see some subsequent prompts to unlock that you didn't include in your output?

Terraform is largely just passing the string you gave to `git clone` here (with some minor transforms to handle the `?ref=v0.7.3` part as a subsequent `git checkout` and remove the `git::` prefix), so the interpretation of the URL is left entirely to git and we don't know of anything Terraform is doing here that would prevent it from finding and interpreting your Git configuration just like running `git` directly.

**Comment by FernandoMiguel** [comment]
@teamterraform I use kriptco which stores my ssh key in the secure enclave of my phone.
So requests to decrypt the key are seen on the device not the laptop shell.

But I can easily reproduce this with a local key

**Comment by FernandoMiguel** [comment]
Any other git operations, be via cli or 3rd party tools like vscode or Sourcetree do use the github personal token stored in the macOS keychain

**Comment by FernandoMiguel** [comment]
It's even weird it requests a ssh key to clone a public repo, as in this example.
Although what led me to open the ticket is about our company internal github enterprise, but this was a safer example of a public repo

**Comment by nathancarmona** [comment]
Wanted to add some tangible output that DOES suggest that Terraform is not respecting .gitconfig:

```
$ git config --global --list 
url.https://TOKEN@github.com/.insteadof=git@github.com:
$ terraform init 
Initializing modules...
Downloading git@github.com:org/module.git?ref=branch for xxx... 
- xxx-xxxxxx in .. 
Failed to download module 
 
Could not download module "xxx" (main.tf:1) source code from 
"git@github.com:org/module.git?ref=branch": error downloading 
'ssh://git@github.com/org/module.git?ref=branch': /usr/bin/git 
exited with 128: Cloning into '.terraform/modules/xxx'... 
Warning: Permanently added the RSA host key for IP address 'xxx.xxx.xxx.xxx' to 
the list of known hosts. 
git@github.com: Permission denied (publickey). 
fatal: Could not read from remote repository. 
 
Please make sure you have the correct access rights 
and the repository exists. 
```

**Comment by m13t** [comment]
Hi @FernandoMiguel.

Not sure if you managed to work this out yourself or not, but the reason that this isn't working for you is that your `insteadOf` value needs to be prefixed with `ssh://` as that's what it's translated to behind the scenes.

The correct way (using your example) would be:
```
[url "https://github.com/"]
	insteadOf = "ssh://git@github.com"
```

Hope that helps

**Comment by FernandoMiguel** [comment]
@m13t I'll give it a try

**Comment by FernandoMiguel** [comment]
tested and works.
thanks for pointing it out @m13t
