### ISSUE TITLE
Terraform marking the same AWS resource for deletion and creation

### ISSUE THREAD

**Issue by manojbadam** [hashicorp/terraform#23107]
When deploying the AWS Target Group with a life cycle hook `create_before_destroy`, it is marking the old one as `deposed` and creating the new one. If the Deployment fails because of health checks or EC2 user-data issues, and if we would like to revert that target group changes, terraform is marking the old target group for creation and also have the same target group for deletion (or deposed state). Detailed steps for workflow

https://gist.github.com/manojbadam/742ad1a0755f2c9e2044b399cf42aa67

### Terraform Version
```
0.12.5
```

### Terraform Configuration Files

```hcl
resource "aws_lb_target_group" "app" {
  name     = "${var.app_tg_name}"
  port     = "${var.alb_target_group_port}"
  protocol = "${var.alb_target_group_protocol}"
  vpc_id   = "${var.vpc_id}"
  deregistration_delay = 120

  health_check {
    path                = "${var.alb_healthcheck_path}"
    matcher             = "200"
    port                = "${var.alb_target_group_port}"
    protocol            = "${var.alb_target_group_protocol}"
    healthy_threshold   = "${var.alb_healthcheck_healthly_theshold}"
    unhealthy_threshold = "${var.alb_healthcheck_unhealthly_theshold}"
    timeout             = "${var.alb_healthcheck_timeout}"
    interval            = "${var.alb_healthcheck_interval}"
  }

  lifecycle {
    create_before_destroy = true
  }
}
```
### Expected Behavior
Terraform should just remove the deposed state on existing target group

### Actual Behavior
Terraform is trying to old one and creating a new one with same name

### Steps to Reproduce
Detailed steps https://gist.github.com/manojbadam/742ad1a0755f2c9e2044b399cf42aa67

**Comment by jbardin** [comment]
Hi @manojbadam,

It sounds like the resource is required to be unique, but by definition `create_before_destroy` is going to need to create a new instance before destroying the old one. 

If `create_before_destroy` is required for your use case, you need to use a generated identifier for the resource, and the AWS provider often has a `name_prefix` option for the purpose. If there is no such attribute, or it's still not sufficient to prevent the failure do to conflicting resources, you could open an issue with the AWS provider to see if there are any other workarounds for this resource type.

Thanks
