### ISSUE TITLE
s3 backend cannot write state to buckets with mandatory object lock

### ISSUE THREAD

**Issue by nickatsegment** [hashicorp/terraform#23127]
### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.60.0
+ provider.external v1.2.0
+ provider.null v2.1.2
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.11. You can update by downloading from www.terraform.io/downloads.html
```

but it looks to be a problem in `master` as well

### Crash Output
```
Failed to load backend: Error writing state: failed to upload state: InvalidRequest: Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters
```

### Expected Behavior
State should have been written to S3 bucket.

### Actual Behavior
Terraform failed to write state to bucket with above error message.

### Steps to Reproduce
1. Create an S3 bucket with object locks enabled, with a default mode of `COMPLIANCE` (the actual retention period is not important.
2. Cause terraform to attempt to write to it (apply works)
3. Get error. 

### Additional Context

Object lock makes it possible to lock object-versions so that they cannot be deleted; i.e. the specific object-version is retained for some retention period which not even the `root` user of the AWS account can override.

Ultimately I would have preferred this to have been a backend configuration option, but I was trying to avoid making a feature request :)

### References
I couldn't find anything regarding object lock being used with the S3 backend.

The call to `PutObject` happens around [here](https://github.com/hashicorp/terraform/blob/bac0577c709bbe8007485deb305a39046c73f652/backend/remote-state/s3/client.go#L154). As [the documents for `PutObjectInput` state](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#PutObjectInput), the `ContentMD5` field must be set when using object lock parameters.

**Comment by pdecat** [comment]
This seems to be working fine nowadays: https://github.com/hashicorp/terraform/pull/29900
