### ISSUE TITLE
Provisioner Chef - Ohai Hints

### ISSUE THREAD

**Issue by a13x212** [hashicorp/terraform#2313]
Feature request: Add Ohai Hints to Chef Provisioner

https://docs.chef.io/ohai.html#hints

The issue i’m trying to solve is aws instances provisioned through terraform do not have ec2.json (/etc/chef/ohai/hints/ec2.json ) hint file. Some of our chef recipes use ec2 specific attributes from ohai

**Comment by svanharmelen** [comment]
@a13x212 a very easy and fast fix is to upload the hints file with the file provisioner before executing the chef provisioner (you can configure multiple provisioners which will be executed in order of declaration).

A more permanent (but still easy) fix would be adding a new option to the chef provisioner to specify a list of hint files to upload.
