### ISSUE TITLE
Boolean values, if set to false in tf file, are not executed in terraform apply

### ISSUE THREAD

**Issue by code-lucidal58** [hashicorp/terraform#23138]
I am writing my own provider. I have a property "enabled" which will hold Boolean values. If the value of this property is _false_ , ```terraform plan``` detects the change, but when apply is done, the value is not detected.

### Terraform Version
```Terraform v0.12.12```

### Terraform Configuration Files
```hcl
resource "<resource_name>" "<name>" {
  name      = "sol1"
  enabled   = false
  baud_rate = 9600
}
```
Schema Definition
```go
"enabled": {
		Type:        schema.TypeBool,
		Optional:    true,
	},
```

Code for getting value from tf (Create functionality in resource_demo_resource.go file)
```go
if v, ok := d.GetOk("enabled"); ok {
	x := (v.(bool))
	o.Enabled = &x
	log.Println("enabled data found", o.Enabled)
} else {
	log.Println("enabled data not found")
}
```
### Debug Output
```
2019/10/21 18:21:28 resource_demo_resource.go:244: enabled data not found
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by code-lucidal58** [comment]
https://github.com/hashicorp/terraform/blob/master/helper/schema/resource_data.go#L97

This is the line that is not allowing false value for boolean properties.

**Comment by jbardin** [comment]
Hi @code-lucidal58,

This is a case where you can use `GetOkExists` to skip that particular check. The Legacy SDK has no way to distinguish unset and zero values in all cases however, so this may not trigger an update at all if the `enabled` line is later removed from the config, and will still show as set even if it it was removed along with other changes.

Thanks
