### ISSUE TITLE
Terraform Cloud backend unable to read TOKEN from CLI Config

### ISSUE THREAD

**Issue by osulli** [hashicorp/terraform#23143]
### Terraform Version

```
Terraform v0.12.12
+ provider.tfe v0.11.1
```

### Terraform Configuration Files

```hcl
# ~/.terraformrc
credentials "app.terraform.io" {
  token = "xxxxxx.atlasv1.zzzzzzzzzzzzz"
}
```

```hcl
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "my-unique-org"
    workspaces {
      name = "my-workspace"
    }
  }
}

provider "tfe" {
  hostname = "app.terraform.io"
}

resource "tfe_workspace" "workspace" {
  name                  = "test-workspace"
  organization      = var.organization
}
```

### Expected Behavior

- The local state file (`.terraform/terraform.tfstate`) contains the token for the backend configuration
- On Plan/Apply, resources in the remote stateful are read and recognised

### Actual Behavior

- The local state file (`.terraform/terraform.tfstate`) does *not* contain the token for the backend configuration
- On Plan/Apply, resources in the remote stateful are *not* read and recognised

### Steps to Reproduce

- Have an existing remote state file / hard code the token and create one with a resource
- Have no tokens inside the terraform config, only in the CLI config file (`~/.terraformrc`)
- `terraform init` 
- Check the local state file (`.terraform/terraform.tfstate`) for the `token` value in the `backend` block
- `terraform apply`
- Check for resources that were in the stateful not being acknowledged (e.g. it will attempt to re-create)

### References

Potentially similar issues:
#23093

**Comment by kikitux** [comment]
working on support ticket

**Comment by osulli** [comment]
Should anyone also stumble on this issue, here is the solution provided by Hashicorp Support, in my own words:

- In Terraform Cloud add an Environment Variable that is Sensitive called `TFE_TOKEN`. 
- Run `terraform apply` either locally or through the UI
- Profit

Nowhere in the documentation does it raise this, or so I felt, but this solution works just fine.. if not better than setting a local `rc` file.

Re-opening for documentation to be updated. Thanks
