### ISSUE TITLE
AWS ELB set access log

### ISSUE THREAD

**Issue by nwalke** [hashicorp/terraform#2315]
I'd like to be able to turn on access logs for a given ELB and set the path where it gets stored.

Like this: https://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_ModifyLoadBalancerAttributes.html#API_ModifyLoadBalancerAttributes_Example_Enable_Access_Log

I don't see a way to do that currently according to the ELB docs.

**Comment by willmcg** [comment]
+1

**Comment by cu12** [comment]
+1

**Comment by proffalken** [comment]
+1

**Comment by lenage** [comment]
+1

**Comment by igrayson** [comment]
+1

**Comment by blairham** [comment]
+1

**Comment by abeyuya** [comment]
+1

**Comment by catsby** [comment]
https://github.com/hashicorp/terraform/pull/3062 aims to implement this

**Comment by pigri** [comment]
+1

**Comment by stack72** [comment]
@nwalke there is a PR open for this now ^^

**Comment by nwalke** [comment]
Awesome.

**Comment by tpounds** [comment]
I plan to get the pull request in a mergeable state in the next day or so. The code should merge cleanly to latest release and master. Feel free to give it a try in the short term.

**Comment by catsby** [comment]
Access Logs have been added in #3756, and will go out in the next release!

**Comment by elblivion** [comment]
:tada:
