### ISSUE TITLE
support for lists in element() function

### ISSUE THREAD

**Issue by rbowlby** [hashicorp/terraform#2317]
It appears that the element function only accepts/supports a splat currently. So something like the following doesn't work:

subnet_id = "${element(["${split(",", var.subnets)}"], count.index)}"

Allowing more flexibility with regard to what can be passed to element would prove useful.

**Comment by phinze** [comment]
Hi @rbowlby - If you remove inner square brackets and nested interpolation it should work.

Like this:

```
subnet_id = "${element(split(",", var.subnets), count.index)}"
```

Example in action:

https://github.com/terraform-community-modules/tf_aws_vpc/blob/f-phinze-revamp/main.tf#L26-L27

Let us know if there's a place in the docs we could make this clearer!
