### ISSUE TITLE
Render double dollar ($$) in aws state-machine-definition

### ISSUE THREAD

**Issue by skycremaschinin** [hashicorp/terraform#23180]
### Terraform Version
```
0.11.13
```
### Expected Behavior
In AWS state machine definition, in order to get TaskToken from context, it must be defined as follow:
```
  "TaskToken.$": "$$.Task.Token"
```

### Actual Behavior

state-machine definition is exported as
```
  "TaskToken.$": "$.Task.Token"
```

### Steps to Reproduce
Create a state-machine definition including a "WaitForTask" task:
```
"WaitForTask": {
      "Type": "Task",
      "Resource": "arn:aws:states:::sqs:sendMessage.waitForTaskToken",
      "Parameters": {
        "QueueUrl": "${queue-url}",
        "MessageBody": {
          "MessageTitle": "bla bla",
          "TaskToken.$": "$$.Task.Token"
        }
      },
      "Next": "NotifySuccess",
      "Catch": [
        {
          "ErrorEquals": [ "States.ALL" ],
          "Next": "NotifyFailure"
        }
      ]
    }
```

### References
This closed bug has been opened to get the actual behavior.

- #3079

**Comment by pselle** [comment]
Hi @skycremaschinin could you confirm if this is still an issue in 0.12.x of Terraform?

**Comment by skycremaschinin** [comment]
Hi @pselle , i can't upgrade to 0.12 at the moment.
Would this bug be fixed in 0.11?

**Comment by pselle** [comment]
@skycremaschinin No active development is being done, nor are any 0.11.x releases planned, consistent with past releases of Terraform. Upgrading to 0.12 is the recommended path.

**Comment by jbardin** [comment]
Verified that the current config parser correctly handles `$$` in a string.
