### ISSUE TITLE
Terraform state appears corrupted after following the 0.12 upgrade guide

### ISSUE THREAD

**Issue by ckeyes88** [hashicorp/terraform#23187]
### Terraform Version
```
0.11.14
```

### Debug Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1813cf8]

goroutine 25887 [running]:
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).evalTreeManagedResourceNoState(0xc007efb518, 0x30, 0x2258e80)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:238 +0x328
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).EvalTree(0xc007efb518, 0x2349720, 0xc007efb518)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:98 +0x6e
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2349720, 0xc007efb518, 0x0, 0x0)
        /opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:113 +0x94d
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00064d3b0, 0x2349720, 0xc007efb518, 0xc000e8ac00)
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x33b
created by github.com/hashicorp/terraform/dag.(*Walker).Update
        /opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0xa4f



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```
### Crash Output
```
module.expapp_admin.aws_s3_bucket.assets - *terraform.NodeRefreshableManagedResourceInstance
2019/10/24 15:27:11 [TRACE] [walkRefresh] Entering eval tree: data.aws_vpc.expapp_vpc
2019/10/24 15:27:11 [DEBUG] ReferenceTransformer: "module.expapp_admin.aws_s3_bucket.assets" references: []
2019/10/24 15:27:11 [TRACE] root: eval: *terraform.EvalIf
2019/10/24 15:27:11 [TRACE] Graph after step *terraform.ReferenceTransformer:

module.expapp_admin.aws_s3_bucket.assets - *terraform.NodeRefreshableManagedResourceInstance
2019/10/24 15:27:11 [TRACE] vertex 'root.module.order_create_webhook.provider.aws': walking
2019/10/24 15:27:11 [TRACE] Graph after step *terraform.RootTransformer:

module.expapp_admin.aws_s3_bucket.assets - *terraform.NodeRefreshableManagedResourceInstance
2019/10/24 15:27:11 [TRACE] root: eval: *terraform.EvalCountFixZeroOneBoundary
2019/10/24 15:27:11 [TRACE] vertex 'root.aws_api_gateway_method_response.folder_500': walking
2019/10/24 15:27:11 [TRACE] vertex 'root.module.order_create_webhook.provider.aws': evaluating
2019/10/24 15:27:11 [TRACE] [walkRefresh] Exiting eval tree: data.aws_lambda_function.job_runner_lambda
2019/10/24 15:27:11 [TRACE] vertex 'root.aws_api_gateway_method_response.folder_500': evaluating
2019/10/24 15:27:11 [TRACE] root.ticketing: eval: *terraform.EvalSequence
2019/10/24 15:27:11 [TRACE] [walkRefresh] Entering eval tree: module.order_create_webhook.provider.aws
2019/10/24 15:27:11 [TRACE] root.ticketing: eval: *terraform.EvalInitProvider
2019/10/24 15:27:11 [TRACE] vertex 'root.module.order_updated_email_worker.aws_iam_policy.lambda_logging_policy': walking
2019/10/24 15:27:11 [TRACE] vertex 'root.module.order_updated_email_worker.aws_iam_policy.lambda_logging_policy': evaluating
2019/10/24 15:27:11 [TRACE] [walkRefresh] Entering eval tree: module.order_updated_email_worker.aws_iam_policy.lambda_logging_policy
2019/10/24 15:27:11 [TRACE] vertex 'root.aws_api_gateway_rest_api.api': walking
2019/10/24 15:27:11 [TRACE] vertex 'root.aws_api_gateway_rest_api.api': evaluating
2019/10/24 15:27:11 [TRACE] vertex 'root.module.order_confirmation_email_worker.aws_iam_role.iam_for_lambda': walking
2019-10-24T15:27:11.836-0700 [DEBUG] plugin.terraform-provider-aws_v1.60.0_x4: 2019/10/24 15:27:11 [DEBUG] Reading API Gateway Method Response agmr-bbyl5m30j1-1t8grc-GET-400
2019/10/24 15:27:11 [TRACE] vertex 'root.module.order_confirmation_email_worker.aws_iam_role.iam_for_lambda': evaluating
2019/10/24 15:27:11 [TRACE] vertex 'root.module.order_updated_email_validation.aws_iam_policy.lambda_logging_policy': walking
2019/10/24 15:27:11 [TRACE] [walkRefresh] Entering eval tree: module.order_confirmation_email_worker.aws_iam_role.iam_for_lambda
2019/10/24 15:27:11 [TRACE] vertex 'root.module.order_delete_webhook.provider.aws': walking
2019/10/24 15:27:11 [TRACE] vertex 'root.module.ssl_cert_datasource.provider.aws': walking
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1813cf8]

goroutine 25887 [running]:
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).evalTreeManagedResourceNoState(0xc007efb518, 0x30, 0x2258e80)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:238 +0x328
github.com/hashicorp/terraform/terraform.(*NodeRefreshableManagedResourceInstance).EvalTree(0xc007efb518, 0x2349720, 0xc007efb518)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/node_resource_refresh.go:98 +0x6e
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2349720, 0xc007efb518, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/terraform/graph.go:113 +0x94d
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc00064d3b0, 0x2349720, 0xc007efb518, 0xc000e8ac00)
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:387 +0x33b
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/opt/gopath/src/github.com/hashicorp/terraform/dag/walk.go:310 +0xa4f

```

### Expected Behavior
I was following the steps to update from terraform 0.11 to terraform 0.12. I had several resources which names started with numbers so I followed the steps in `terraform 0.12checklist` to rename them and then called `terraform state mv "<old resource>" "<new_resource>"`. This command worked fine. The upgrade instructions then said to run `terraform init and `terraform apply` one last time to be sure everything worked correctly. Terraform init worked fine and I expected it to make a few updates during the apply command

### Actual Behavior
While the init command worked fine, the apply command crashed during state refreshing with the crash.log snippet above. the crash log is too long for a Github Gist but I'm happy to share more of it if it will help.

**Comment by teamterraform** [comment]
Hi @ckeyes88! Sorry for this crash and thanks for reporting it.

Could you clarify whether you saw this crash while running `terraform apply` on Terraform 0.11.14 prior to upgrading, or if you saw the crash with Terraform 0.12 _after_ upgrading? We think you are saying that v0.11.14 crashed, but we want to make sure we're looking at the right version while trying to debug this. Thanks!

**Comment by ckeyes88** [comment]
Hi correct, Following the instructions in the upgrade checklist it says ```Before switching to Terraform 0.12, we recommend using Terraform v0.11.14 (or any later v0.11 release) to perform one last terraform init and terraform apply to ensure that everything is initialized and synchronized.```
So before I switched over to 0.12 I ran terraform apply which is where I received that crash. Now any command (destroy, plan, or apply) crashes during the state refresh step.

**Comment by ckeyes88** [comment]
@teamterraform it seems this crash has corrupted my terraform state. Luckily I was doing the upgrade on a test environment first to ensure it worked. Any chance there's a way to recover that state so I don't have to manually delete my 100+ AWS resources that it was managing?

**Comment by ckeyes88** [comment]
@teamterraform Is anyone able to provide an update on my question above?

**Comment by teamterraform** [comment]
Hi @ckeyes88,

At the moment we're unsure as to what exactly is going on here. The place where this is crashing is in a codepath that is intended to run only for resource instances that are in the configuration but not yet in the state, such as when the `count` for a resource has increased:

https://github.com/hashicorp/terraform/blob/12bf5f6afec2a9dcc97357671fdfa9fb972884eb/terraform/node_resource_refresh.go#L235-L242

It's very odd that we'd end up here in a situation where the configuration is apparently not available either.

Unfortunately we think that in order to understand this better we'll need a fuller copy of the trace log. You mentioned that the log was too long for a GitHub Gist, which is not a situation we've encountered before! But if you can't share the whole thing, the portion of it that is most likely to help explain what's going on would be the portion starting approximately with a log line containing the text `terraform: building graph: GraphTypeRefresh`, which signals that Terraform is beginning to build the dependency graph for the refresh step.

What we're looking for here is an explanation for why the graph builder has apparently created a graph node for a resource instance that is neither in the latest state nor in the configuration. In order to interpret that, it would be helpful if you can recall both the old and new addresses for the resources you renamed using `terraform state mv`, so that we can match those with the addresses mentioned in the graph builder log.

Sorry for the slow response here... this issue continues to be rather puzzling, but hopefully we can get a better sense of what is going on after a detailed inspection of the graph building process.

**Comment by ckeyes88** [comment]
Hi @teamterraform Sorry for the delayed response. I've updated the gist to contain the full crash log. I renamed several resources that had numbers in the starting character of the name for exampled `400_item` to `item_400` and several other like that. I'll run the terraform state mv command shortly and update with more information but hopefully that will help.

**Comment by ckeyes88** [comment]
Just wanted to ping this one again @teamterraform to keep it active.

**Comment by ckeyes88** [comment]
@teamterraform Pinging again to keep this issue active.

**Comment by ckeyes88** [comment]
@teamterraform Pinging again

**Comment by danieldreier** [comment]
@ckeyes88 is this still preventing your 0.12 upgrade? Before I dig in any further I want to make sure we're not doing archeology on an issue that you worked around.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
