### ISSUE TITLE
Tags on api_gateway_domain_name resource

### ISSUE THREAD

**Issue by rgleme** [hashicorp/terraform#23182]
Hello

I need to add some tags to mine api_gateway_domain_name resource

I've found no way using terraform

https://www.terraform.io/docs/providers/aws/r/api_gateway_domain_name.html

Is there any way to do it ?

Thank you
Rodolfo

**Comment by ewbankkit** [comment]
@rgleme This is being addressed in https://github.com/terraform-providers/terraform-provider-aws/pull/10567. Thanks.
