### ISSUE TITLE
dynamic block documentation bug - incorrect or unclear

### ISSUE THREAD

**Issue by pgienger** [hashicorp/terraform#23190]
It would seem that the documentation around the dynamic blocks is wrong or at least confusing.

My specific case was using a vsphere_virtual_machine but I believe this is the core language doc at fault.  There is a referenced bug [terraform-provider-aws #8260](https://github.com/terraform-providers/terraform-provider-aws/issues/8260#issuecomment-481441480)  where it was stated to be fixed, with the proper format, but the current docs do not match.

In my environment, trying to run this block from the base module:
```hcl
  extradisks  = [
    {
      name  = "disk10"
      size  = 16
      eager = false
      thin  = true
    }
  ]
```
which is passed into another module and used within a vm provision as so:
```hcl
  dynamic "disk" {
    for_each = var.extradisks
    content {
      label            = disk.name
      size             = disk.size
      eagerly_scrub    = disk.eager
      thin_provisioned = disk.thin
      unit_number      = disk.unit_number
    }
  }
```
Would throw an error like in the referenced bug.
```
Error: Unsupported attribute

  on ..\..\modules\cent7\cent7.tf line 115, in resource "vsphere_virtual_machine" "tfdeploy":
 115:       thin_provisioned = disk.thin

This object does not have an attribute named "thin".
```
  The way to make it work was this:
```hcl
  dynamic "disk" {
    for_each = var.extradisks
    content {
      label            = disk.value.name
      size             = disk.value.size
      eagerly_scrub    = disk.value.eager
      thin_provisioned = disk.value.thin
      unit_number      = disk.value.unit_number
    }
  }
```

The official documentation bit here (https://www.terraform.io/docs/configuration/expressions.html) seems out of date, or at best confusing, as follows. In order to follow the fix as described above, this block in the documentation

```hcl
resource "aws_security_group" "example" {
  name = "example" # can use expressions here

  dynamic "ingress" {
    for_each = var.service_ports
    content {
      from_port = ingress.value
      to_port   = ingress.value
      protocol  = "tcp"
    }
  }
}
```

should be something like this, making assumptions about the var.service_ports object: 

```hcl
resource "aws_security_group" "example" {
  name = "example" # can use expressions here

  dynamic "ingress" {
    for_each = var.service_ports
    content {
      from_port = ingress.value.from_port
      to_port   = ingress.value.to_port
      protocol  = "tcp"
    }
  }
}
```

**Comment by apparentlymart** [comment]
Hi @pgienger! Thanks for reporting this, and sorry for the long delay in responding.

It seems like in the meantime someone has updated the current documentation with a different example that doesn't have the bug you mentioned here, so I'm going to close this. Thanks again!
