### ISSUE TITLE
Split the built-in providers and provisioners into separate repos

### ISSUE THREAD

**Issue by qzmfranklin** [hashicorp/terraform#23200]
Proposal:

Now that the terraform-plugin-sdk is on its own repo, with a stable-ish API, it makes sense to split the core built-in providers and provisioners into separate repos.

Rationale:

- Reduce the core library's dependencies.
- Allow different plugins to evolve faster. That is, without having to commit in the `terraform` repo.

Thoughts?

**Comment by teamterraform** [comment]
Hi @qzmfranklin,

Thanks for your interest in the project.

There are no longer any real providers in the terraform repository that use the old sdk. The only remaining provider is the `terraform` provider, which does not use a separate sdk, and is very closely related to terraform itself which prompted its migration back into the main repository.

The provisioners at the moment cannot be separated from the repository, as they are built as part of the terraform binary itself. Work is already underway regarding the future of the provisioners, with the intent of separating them from the core codebase. There is also considerable work being done to remove the last of the old sdk from the core repository.

Making plugins easier to develop is high on our list of priorities.
Thanks again
