### ISSUE TITLE
Unable to transition failed VPC Peering connection to deleted

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#2322]
I've setup peering for two VPC's and missed adding the correct CIDR in my variables which caused the peering connection to fail.  Terraform is unable to transition the resource as well.  It seems to be stuck in this state in the console as well and cannot be deleted (I believe these remove themselves after a period of time).

    InvalidStateTransition: Invalid state transition for pcx-5f8398s3e, attempted to transition from failed to deleting

    "aws_vpc_peering_connection.ops-peering": {
                    "type": "aws_vpc_peering_connection",
                    "depends_on": [
                        "aws_vpc.main-vpc"
                    ],
                    "primary": null,
                    "tainted": [
                        {
                            "id": "pcx-5f8398s3e",
                            "attributes": {
                                "accept_status": "failed",
                                "auto_accept": "true",
                                "id": "pcx-572fd73e",
                                "peer_owner_id": "0747474747",
                                "peer_vpc_id": "vpc-e3487778a",
                                "tags.#": "0",
                                "vpc_id": "vpc-xx73a223"
                            }
                        }
                    ]
                }

**Comment by mitchellh** [comment]
Should the correct behavior here be for Terraform to assume the connection is deleted if it is "failed" then?

**Comment by mikeyhill** [comment]
Correct.  When the connection fails there's no way that I could find, cli tools or otherwise, to recover it.  The behavior of those failed connections is similar to instances - they stay in your list of peering connections for a period of time and then disappear.  The process I went through w/ TF was to manually remove the resource from the state file.

**Comment by eddideku** [comment]
> Correct. When the connection fails there's no way that I could find, cli tools or otherwise, to recover it. The behavior of those failed connections is similar to instances - they stay in your list of peering connections for a period of time and then disappear. The process I went through w/ TF was to manually remove the resource from the state file.

How would you manually remove it from the tfstate file if it's coupled with dynamodb?
