### ISSUE TITLE
openstack with a single instance crash after the first apply

### ISSUE THREAD

**Issue by gionn** [hashicorp/terraform#2323]
With a simple:

```
resource "openstack_compute_instance_v2" "test-server" {
  name = "tf-test"
  image_id = "773236b6-75bd-4f5d-afa6-dbc37a5fb349"
  flavor_id = "2"
  security_groups = ["default"]
}
```

First apply went ok, any further will [crash](https://gist.github.com/gionn/100bf4b59b8f00f32468).

**Comment by gionn** [comment]
The problem is probably due to missing network, that however is marked as optional in documentation.

**Comment by jtopjian** [comment]
Defining networks in your instance resource is optional if your tenant / project has access to only one network. If you create multiple Neutron networks under your project, then from that point on, you must explicitly set a network name or UUID in your instance resource.

Can you confirm if this is the case?

**Comment by gionn** [comment]
I had the possibility to create neutron networks, but I forgot to.

So the instance didn't contains any network attribute, first apply went flawless (hence the instance doesn't have any network at all).

May be a usability problem that I got a crash at the second apply without a reason, it would be great if terraform could report the absence of network on the new instance (not sure if it is a real use-case to start instances without network at all).

Thanks!
