### ISSUE TITLE
Resource for_each can't handle empty list

### ISSUE THREAD

**Issue by muellermatthias** [hashicorp/terraform#23231]
### Terraform Version

This problem occured after I updated my terraform version from v0.12.6 to v0.12.9.
So on v0.12.6 it was running fine.
On the following versions I got the error: v0.12.7, v0.12.8, v0.12.9 and v0.12.12.

### Terraform Configuration Files

```hcl
resource "random_string" "random" {
  for_each = var.test != null ? var.test.list : []

  length = 16
}

variable "test" {
  type = object({
    list   = set(string)
    string = string
  })
  default = null
}
```

### Expected Behavior

If I don't pass any value for the variable `test`, no changes should be applied.

### Actual Behavior

The execution fails with the following error message:
 ```bash
Error: Invalid for_each argument

  on main.tf line 2, in resource "random_string" "random":
   2:   for_each = var.test != null ? var.test.list : []

The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type tuple.

```
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
### Additional Context

I found a workaround for v0.12.9 by using `toset([])`, but that's not working for v0.12.12.

**Comment by jbardin** [comment]
Hi @muellermatthias,

I'm not able to reproduce the issue, both the latest release and master work correctly with the provided config, assuming you use the `toset` function. Converting the tuple or list to a set isn't a workaround per say, as stated in the error the `for_each` argument required a map or set of strings. 

Are you certain that you were using `toset` in the configuration used with the current release?

**Comment by muellermatthias** [comment]
@jbardin Sorry, you're right. The workaround works with the last release.

If we leave the workaround aside, will the original bug be fixed? Or did I misuse for_each?

**Comment by muellermatthias** [comment]
@jbardin Thanks for the help.
