### ISSUE TITLE
azurerm backend not working behind proxy

### ISSUE THREAD

**Issue by ehaselwanter** [hashicorp/terraform#23248]
### Terraform Version

```
terraform --version
Terraform v0.12.12
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "> 0.12.11"
  backend "azurerm" {
    storage_account_name  = "tstatetfexperiments"
    container_name        = "tstate"
    key                   = "terraform.tfstate"
  }
}

provider "azurerm" {
  version = "= 1.35.0"
}
```

### Debug Output

https://gist.github.com/ehaselwanter/feecac00c682fa7d86d60589f8761725#file-trace-log

### Crash Output

```
Error: Error loading state: storage: service returned error: StatusCode=403, ErrorCode=AuthenticationFailed, ErrorMessage=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:d3b04f8b-d01e-00e0-350f-8bc8d4000000
Time:2019-10-25T08:37:04.9954259Z, RequestInitiated=Fri, 25 Oct 2019 08:37:04 GMT, RequestId=d3b04f8b-d01e-00e0-350f-8bc8d4000000, API Version=, QueryParameterName=, QueryParameterValue=

```

### Expected Behavior

it should init and use te azurerm backend

### Actual Behavior

it fails with an error

### Steps to Reproduce

have a setup with HTTP/HTTPS proxy settings

### Additional Context

said proxy settings. 

- if I run the exact same code without proxy settings it DOES work
- if I run the code with local backend it works in both cases

=> IMHO this is something weird with only the azurerm backend, since local state works flawless behind the proxy

**Comment by tombuildsstuff** [comment]
hey @ehaselwanter 

Taking a look into this, I believe this is resolved as of Terraform 0.13.0 - and as such I'm going to close this issue for the moment - however if you're still seeing this with 0.13.0 please let us know and we'll take another look.

Thanks!
