### ISSUE TITLE
Processing ${} does not occur if data loaded from file.

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2325]
It would be nice if (e.g. on an aws_instance)

user_data = "${file("some-file.yaml")}" would substitute ${aws_instance.foo.private_ip} if the ${aws_instance.foo.private_ip} exists in the yaml file.

Otherwise the file() command has less appeal.

**Comment by phinze** [comment]
Hi @gtmtech - have a look at the [`template_file` resource](https://terraform.io/docs/providers/template/r/file.html), which should accomplish what you're looking for.

**Comment by gtmtech** [comment]
This does not support ${count.index}. So it cannot be used in this situation.

**Comment by mitchellh** [comment]
As a workaround, you can set the `count` of the template and achieve the same effect, as long ast he counts match.

**Comment by gtmtech** [comment]
That sounds like a good workaround - so I tried
```
resource "template_file" "some_template" {
  filename = "files/something.yaml"
  count    = 2
}

resource "aws_instance" "some-instance" {
...
    user_data                   = "${template_file.some_template.${count.index}.rendered}"
    count                       = 2
...
}
```

But this doesn't work (nested ${count.index} not allowed). Without the ${count.index} it doesn't find the template. What is the correct syntax for linking them in this way? Thanks

**Comment by gtmtech** [comment]
Ah I see from the docs, the final step is to do:

```
user_data = "${element(template_file.web_init.*.rendered, count.index)}"
```

To link them in the correct way. Thanks for the info, this will do nicely

**Comment by phinze** [comment]
For future reference, this use case is documented under "Using Templates With Count" header here: https://terraform.io/docs/configuration/interpolation.html
