### ISSUE TITLE
https://www.terraform.io/docs/backends/types/etcd.html few links are not working used to work before 

### ISSUE THREAD

**Issue by svopentext** [hashicorp/terraform#23254]
### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by Redhab** [comment]
+1
Getting 404  on these AWS doc links:
 aws_ami_from_instance : https://www.terraform.io/docs/providers/aws/r/ami_from_instance.html
 aws_ami_launch_permission : https://www.terraform.io/docs/providers/aws/r/aws_ami_launch_permission.html

aws_ami_launch_permission
aws_ebs_default_kms_key
aws_ebs_encryption_by_default
aws_ebs_snapshot
aws_ebs_snapshot_copy

![image](https://user-images.githubusercontent.com/6106779/68048446-d11e4e00-fc9d-11e9-8fe8-fcf545d2b489.png)

**Comment by terleckijp** [comment]
Im getting blank page from the batch job definition resource as well:

https://www.terraform.io/docs/providers/aws/r/batch_job_definition.html
