### ISSUE TITLE
I'd like to apply conditionals within a function call

### ISSUE THREAD

**Issue by Jaff** [hashicorp/terraform#23250]
### Current Terraform Version
```
0.12.12
```
### Use-cases
Given a map of a containerized service, I'd like to be able to construct an AWS elb with a set of listener blocks. I've been successful so far, but I have a few special case services for which a load-balancer will not be needed. This could be flagged by the configuration NOT including the lb_port settings:
```
variable container_map         {
default = {
    drm-configuration = [
      {
        container_image   = "drm-configuration:latest"
        mimi_service      = "DrmProvisioning"
        mimi_owner        = "drm-prov-dev@mimi.com"
        lb_port           = 50117
        lb_protocol       = "tcp"
        instance_port     = 40117
        instance_protocol = "tcp"
      }
    ]
    drm-accountanddevices-cooker = [
      {
        container_image   = "drm-accountanddevices-cooker:latest"
        mimi_service      = "DrmProvisioning"
        mimi_owner        = "drm-prov-dev@mimi.com"
        instance_port     = 40112
        instance_protocol = "tcp"
      }
    ]
  }
}

locals {
  nodes = [for index in range(0, var.instance_count) : "drm-binpack-${var.env}-${format("%02d", index + 1 + var.offset)}.${var.datacenter}.mimi.com"]
  services = flatten([
    for service in keys(var.container_map) : [
      for configs in var.container_map[service] : {
        service           = service
        container         = configs.container_image
        mimi_service      = configs.mimi_service
        mimi_owner        = configs.mimi_owner
        lb_port           = configs.lb_port
        lb_protocol       = configs.lb_protocol
        instance_port     = configs.instance_port
        instance_protocol = configs.instance_protocol
      }
    ]
  ])
```

### Attempted Solutions
```
  service_ports = flatten([
    for service in keys(local.services_map) : [
      for configs in local.services_map[service] : {
        %{ if configs.lb_port != "" } lb_port = configs.lb_port %{ endif }
        %{ if configs.lb_port != "" } lb_protocol = configs.lb_protocol %{ endif }
          instance_port     = configs.instance_port
          instance_protocol = configs.instance_protocol
      }
    ]
  ])

```
 the outcome of running the above plan is that I get the error:
```
Error: Invalid expression

  on main.tf line 36, in locals:
  36:         %{ if configs.lb_port != "" } lb_port = configs.lb_port %{ endif }

Expected the start of an expression, but found an invalid expression token.
```

### Proposal
Code fix?

**Comment by teamterraform** [comment]
Hello!

There's a lot going on here, and it's probably going to take some discussion to come figure out what needs to happen here, 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by Jaff** [comment]
I'm not sure if I observed a bug, or if this is not expected use of the conditionals feature. If it's a bug, then it should be fixed. If it's not a bug, then it should be an enhancement feature request.
