### ISSUE TITLE
Terraform crashes after plan only in terraform-cloud

### ISSUE THREAD

**Issue by Nighthawk14** [hashicorp/terraform#23274]
### Terraform Version
```
Terraform v0.12.12
+ provider.aws v2.33.0
+ provider.template v2.1.2
```

### Debug Output

No debug output as this is in terraform-cloud

### Crash Output

https://gist.github.com/Nighthawk14/400c2dbdffc722e53c2fd03bf37707b3

### Expected Behavior
It should list the changes and sets the plan to "Manual confirmation" state

### Actual Behavior
The plan just crashes and can't recover

### Additional Context
- We currently have 10 other workspaces that works perfectly fine, including one other workspace that share the same codebase for configuration files.
- Planning and applying the plan works perfectly fine locally, it crashes only in terraform-cloud
- We deleted the workspace to re-create it (using the previous workspace state) and it keeps crashing

**Comment by mildwonkey** [comment]
This issue was fixed in PR #23492, which was included in the 0.12.17 release - sorry for the extra  noise!
