### ISSUE TITLE
Add an index attribute to the dynamic block iterator object

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/terraform#23288]
Currently the iterator object in the `dynamic` block appears to have only two attributes: [`key`](https://www.terraform.io/docs/configuration/expressions.html#key) & [`value`](https://www.terraform.io/docs/configuration/expressions.html#value)

That means it's impossible to check at which index of the `dynamic` block iteration we are.
I'd love it for it to also contain an `index` attribute, so I can use it to generate names for the resource in the dynamically generated block.

Example:
```terraform
resource "aws_cloudfront_distribution" "default" {
  dynamic "origin" {
    iterator = fqdn
    for_each = var.origin_fqdns
    content {
      domain_name = fqdn.value
      origin_id   = "origin-fqdn-${fqdn.index}"
    }
  }
}
```

**Comment by jbardin** [comment]
Hi @jakubgs,

Can you clarify what you're trying to do that you can't do with the existing `key` attribute? The documentation you linked for the `key` attribute says

> key is the map key or _list element index_ for the current element

Which means that `origin_id   = "origin-fqdn-${fqdn.key}"`  should do what you expect.

**Comment by jakubgs** [comment]
Oh, I must have missed that part, I had no idea `keys` means `index` when the value of `for_each` is a list. Thanks for explaining!
