### ISSUE TITLE
terraform show does not accept -state argument

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#2329]

**Comment by catsby** [comment]
Hey @sparkprime – how would you imagine this behaving?

**Comment by sparkprime** [comment]
IIRC 'apply' allows you to override the location of the state file, so it should be possible to get 'show' to look at the file managed by 'apply'

**Comment by mitchellh** [comment]
We're actually planning on simply redoing `show` completely in TF 0.9 so let's just close this out because it may not resemble anything we have atm.
