### ISSUE TITLE
Add command for checking lock status

### ISSUE THREAD

**Issue by Skyfallz** [hashicorp/terraform#23308]
### Current Terraform Version

```
0.12.13
```

### Use-cases

In a microservice environment, within my CD pipeline, I run multiple Terraform modules. Some of those runs share the same tfstate with multiple microservices (ie for shared infrastructure elements). As multiple microservices are sharing the same tfstate (which is normal, as I don't wan't to pop those shared resources multiple times), so I can't let locking disabled to avoid concurrent runs.
Now the problem is, when this concurrent run situation occurs, my job (and therefore the whole pipeline) will fail (which is totally normal, the lock is on). I would prefer to check the lock before attempting to run my Terraform, so I can make it wait a little for the lock to be released, instead of generating "normal errors". I think it would be an improvement to implement a command for checking the lock state, which could allow us to poll for lock status before attempting a run. I found no pretty way to do this (and moreover no 'agnostic' way, regardless of the locking backend).

### Attempted Solutions

The workaround I setup consists in checking my DynamoDB table for a corresponding lock record. It works, but it's a bit dirty and I think Terraform should be able to check it's locking status. 

### Proposal

Implementing a command like : 
```
terraform lock-status
```
which would return nothing (and a zero returncode) if no lock is setup, and basic information about the lock set if it's on (and a nonzero returncode) : 
```
Lock Info:
  ID:         LOCK_ID
  Path:      path/to/terraform.tfstate
  Operation: OperationTypeCheck
  Who:       user@runner
  Version:   0.12.13
  Created:   2019-11-07 16:02:20.516622883 +0000 UTC
  Info:      
```
would be handy to handle this kind of usecase.

Let me know if I wasn't clear enough, thanks for your work !

**Comment by teamterraform** [comment]
Hi @Skyfallz! Thanks for sharing this use-case.

The `terraform apply` command (and most other commands that interact with remote state) has a `-lock-timeout=...` option which instructs Terraform to retry acquiring the lock for a time period before giving up. Would that work for what you're trying to achieve here?

**Comment by Skyfallz** [comment]
Hi,

yes, this seems to do the job.

Thanks, closing this
