### ISSUE TITLE
Default .terraformignore rules don't work on Windows

### ISSUE THREAD

**Issue by Jaecen** [hashicorp/terraform#23311]
### Terraform Version

```
Terraform v0.12.13
```

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output

n/a

### Crash Output

n/a

### Expected Behavior

When no `.terraformignore` file is present, executing a `plan` or `apply` on a Remote Backend CLI-drive run will ignore any `.git` and `.terraform` folders, excluding `.terraform/modules`, while building the slug to upload.

### Actual Behavior

On Windows, `.terraform` and `.git` folders are included in the uploaded slug.

### Steps to Reproduce

On a Windows machine with latest Terraform installed:
1. Create a new Terraform Cloud workspace
1. Create a Terraform configuration with a remote backend pointing at that workspace
1. `terraform init`
1. Copy a large file (100+ MB) into the `.terraform` folder
1. `terraform plan`
1. Watch your upload statistics and note how long it takes to upload
1. Create a `.terraformignore` file with the following contents:
  ```
  **\.git\**
  **\.terraform\**
  !**\.terraform\modules\**
  ```
1. `terraform plan`
1. Note how this upload is practically instant

### Additional Context

I believe this is happening because the default `.terraformignore` uses forward slashes, but backslashes are required on Windows. If you create a `.terraformignore` file using forward slashes, you see the same behavior as if not using a `.terraformignore` at all. If you change it to backslashes, it works correctly.

### References

n/a

**Comment by pselle** [comment]
@Jaecen Thanks for filing this report! This is definitely an oversight, and I appreciate you posting the current workaround (`.terraformignore` with the default rules) for any users looking for it. I'll get to work on fixing this.
