### ISSUE TITLE
terraform remote subcommands don't support -no-color option

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#2333]
The `-no-color` option isn't available for the `remote` command. 

```
$ terraform remote config -backend=consul -backend-config="path=tf" -no-color
Remote configuration updated
[0m[1m[32mRemote state configured and pulled.[0m
```

In my opinion this should be available for all Terraform commands.

**Comment by radeksimko** [comment]
It actually [does](https://github.com/hashicorp/terraform/blob/master/command/meta.go#L349-357) - that piece of code should apply for all commands, it's just not documented = thank you for pointing it out, it should be documented properly.

**Comment by clstokes** [comment]
I think this isn't just a documentation issue. When I pass `-no-color` to the remote command I still get colorized output.

```
$ AWS_ACCESS_KEY_ID=SNIP AWS_SECRET_ACCESS_KEY=SNIP terraform remote config -backend=s3 -backend-config='region=SNIP' -backend-config='bucket=SNIP'  -backend-config="key=SNIP" -no-color 
Initialized blank state with remote state enabled!
[0m[1m[32mRemote state configured and pulled.[0m
```

**Comment by radeksimko** [comment]
You are kind of right, subcommands don't support `-no-color`.
The code I linked to only applies to 1st level commands (i.e. `terraform FIRST_LEVEL`), therefore `terraform remote` itself does support `-no-color`, but `terraform remote config` does not.

**Comment by radeksimko** [comment]
See #2414
