### ISSUE TITLE
Output of changed/added/destroyed resources for modules should have ability to show full output

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#2335]
Doing some work on a specific resource in a module and it's difficult to know what Terraform is changing without stepping back through all of the code.  It would be helpful to have a command line option to show full module output.

**Comment by radeksimko** [comment]
Would `terraform output NAME` and/or https://github.com/hashicorp/terraform/issues/1209 help here?

**Comment by mikeyhill** [comment]
I would say yes to either.  Really any way one can verify the changes made are expected is helpful but if I'm understanding correctly having -format=json would require running a diff to check those?

**Comment by radeksimko** [comment]
I just made the original issue a little bit more generic, if you agree, I will close this in favour of #1209

**Comment by radeksimko** [comment]
@mikeyhill `terraform output` (w/out any further args) will show all outputs in the upcoming release - #2920 has been merged.

#1209 is solving slightly different, yet related problem, but I think this issue can be closed. Reopen if you think otherwise.

**Comment by mikeyhill** [comment]
@radeksimko - very strange, I hadn't thought about this in quite some time and was literally just pondering over it a few minutes ago.  Great minds must think alike :)  Seriously though, thank you guys for all the work you put into TF, it has made my days a lot easier.
