### ISSUE TITLE
dynamic : plan panic after having succeed to apply

### ISSUE THREAD

**Issue by Adphi** [hashicorp/terraform#23369]
### Terraform Version

```
Terraform v0.12.13
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
locals {
  remote_execs = [
    {
      type: "inline"
      values: [
        "echo 'I will fail'",
        "fail"
      ],
      continue_on_failure: true,
    },
    {
      type: "inline"
      values: [
        "echo 'I did continue anyway'"
      ],
      continue_on_failure: false,
    },
    {
      type: "scripts"
      values: [
        "test.sh",
      ],
      continue_on_failure: false,
    },
  ]
}

resource "null_resource" "test" {
  connection {
    type     = "ssh"
    user     = "root"
    password = "root"
    port     = 2222
    host     = "localhost"
  }
  provisioner "multi-remote-exec" {
    dynamic "remote_exec" {
      for_each = local.remote_execs
      content {
        type   = remote_exec.value.type
        values = remote_exec.value.values
        continue_on_failure = remote_exec.value.continue_on_failure
      }
    }
  }
}

```

### Debug Output

https://github.com/partitio/terraform-provisioner-multi-remote-exec/blob/debug/tests/trace.txt
### Crash Output

https://github.com/partitio/terraform-provisioner-multi-remote-exec/blob/debug/tests/crash.log
### Expected Behavior

After running `terraform apply` with success, `terraform plan` should show that there is no changes.
### Actual Behavior

Terrafom crash
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
3. `terraform plan`
### Additional Context

I did test the same pattern with Habitat Provisioner where i used dynamic on `service` and it did also panic.

**Comment by Adphi** [comment]
I am not certain of the implications of a change at line 51 :

https://github.com/hashicorp/terraform/blob/88a806cc32d2389b8f848b306a9448f2f305a258/lang/references.go#L50-L54

but maybe this changes could be a fix :
```go
 func ReferencesInBlock(body hcl.Body, schema *configschema.Block) ([]*addrs.Reference, tfdiags.Diagnostics) { 
        if body == nil || schema == nil { 
 		return nil, nil 
 	}
        ...
```

It does not seems to break the tests (`go test -v ./...`)

**Comment by kmott** [comment]
FWIW, I verified this using a moderately complex Habitat Provisioner module with the changes described above to `lang/references.go`. Terraform plan / apply / destroy no longer crashes using the Habitat Provisioner.

**Comment by danieldreier** [comment]
@Adphi I copied your reproduction case into https://github.com/danieldreier/terraform-issue-reproductions/tree/master/23369 so that we can collaborate on it better.

When I run your reproduction case, I get:
```
+ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.null: version = "~> 2.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
+ terraform plan

Error: Failed to instantiate provisioner "multi-remote-exec" to obtain schema: unknown provisioner "multi-remote-exec"

```

it looks to me like this is using a provisioner not in terraform core. Can you restate this reproduction case in a way that uses native terraform provisioners?

**Comment by Adphi** [comment]
After almost 9 months ignoring this issue, I have no more interest in contributing to this project, my contribution to resolve this issue has been ignored, despite the verification done by @kmott, I do not care any more... sorry, I did move away from your product.

**Comment by danieldreier** [comment]
@Adphi I'm going to close this because it's gone without a response since June 5th, and I think that the crash involves a provisioner outside of Terraform core, which is not something we could fix. I'm happy to look at this again if we can get a reproduction case that uses native terraform provisioners.
