### ISSUE TITLE
'terraform validate' returns exit code 0 even if the validation failed

### ISSUE THREAD

**Issue by horse27** [hashicorp/terraform#23372]
### Terraform Version
```
v0.12.13
```

### Expected Behavior
'terraform validate' should return non-zero return code if validation fails

### Actual Behavior
return code 0 is returned regardless of outcome

### Steps to Reproduce
1. run 'terraform validate' on an intentionally corrupt .tf file
2. run 'echo $!' to see the return code of the last command

**Comment by ankitabhopatkar13** [comment]
Should't you be using `echo $?` to check the return code @horse27 ?

**Comment by horse27** [comment]
I'm an idiot. return code is "echo $?"
facepalm.jpg

**Comment by renan** [comment]
It still returns 0, as per your issue.

```
⇒  terraform validate

Warning: Quoted type constraints are deprecated

  on ../../modules/config/malicious_ips.tf line 2, in variable "malicious_ip_cidr":
   2:   type = "list"

Terraform 0.11 and earlier required type constraints to be given in quotes,
but that form is now deprecated and will be removed in a future version of
Terraform. To silence this warning, remove the quotes around "list" and write
list(string) instead to explicitly indicate that the list elements are
strings.

Success! The configuration is valid, but there were some validation warnings as shown above.

⇒  echo $?
0
```

**Comment by horse27** [comment]
I don't know, that seems like expected behaviour to me. The config is valid so exit code 0 seems fitting.
