### ISSUE TITLE
Attach or Detach your load-balancer in an autoscaling group

### ISSUE THREAD

**Issue by julienlavergne** [hashicorp/terraform#2337]
Last news from AWS said: 

"Dear Amazon Web Services Customer,

Starting today, you can attach or detach Elastic Load Balancing load balancers in an Auto Scaling group.

Previously, load balancers associated with your Auto Scaling group could not be changed once the group had been created, requiring you to create a brand new Auto Scaling group in order to update your load balancers. Now, you can simply attach or detach load balancers to the Auto Scaling group without disrupting your application. This makes it easier to perform fleet management tasks, such as blue/green deployments or SSL certification upgrades.

You can access these new features using the Auto Scaling API, AWS SDKs, command-line tools, and the AWS Management console. To learn more, please see our documentation."

Any idea when terraform should manage that ?

PS: terraform is so a wonderful tool ;)

**Comment by udangel-r7** [comment]
I think this is solved via the `load_balancers` attribute

**Comment by radeksimko** [comment]
@udangel-r7 is right, this feature is supported since 25th June, specifically from Terraform `v0.6.0` onwards, so I'm closing this.

https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#load_balancers

Feel free to submit a separate issue in case you're having troubles with it.
