### ISSUE TITLE
Cannot move a resource across statefiles

### ISSUE THREAD

**Issue by andrewpage** [hashicorp/terraform#23386]
### Terraform Version

```
terraform -v
Terraform v0.12.14
```

### Terraform Configuration Files
N/A

### Expected Behavior
I have a module, `module.vpn`, that previously existed in my _production_ state file (`./environments/production`), and I wanted to move to my _global_ state file (`./environments/global`).

I was expecting the `module.vpn` to disappear from the production statefile/workspace and appear in the global statefile/workspace.

### Actual Behavior
This is the initial command I ran:
`terraform state mv -backup=original.tfstate.backup -backup-out=destination.tfstate.backup -state-out=../global/.terraform/terraform.tfstate module.vpn module.vpn`.

I then navigated to the `./environments/global` directory and ran the following command, intending to see my `module.vpn`:

```
$ TF_LOG=trace terraform state list                                                                                                               1 ↵
2019/11/14 20:13:05 [INFO] Terraform version: 0.12.14
2019/11/14 20:13:05 [INFO] Go runtime version: go1.12.13
2019/11/14 20:13:05 [INFO] CLI args: []string{"/usr/local/bin/terraform", "state", "list"}
2019/11/14 20:13:05 [DEBUG] Attempting to open CLI config file: /Users/andrew/.terraformrc
2019/11/14 20:13:05 Loading CLI configuration from /Users/andrew/.terraformrc
2019/11/14 20:13:05 [INFO] CLI command args: []string{"state", "list"}
2019/11/14 20:13:05 [TRACE] Meta.Backend: BackendOpts.Config not set, so using settings loaded from backend.tf:2,3-19
2019/11/14 20:13:05 [TRACE] Meta.Backend: built configuration for "remote" backend with hash value 1213106811

Error: Failed to load state: Terraform 0.12.14 does not support state version 4, please update.
```

I thought I might need to run a `terraform init`, so I tried that:
```
$ TF_LOG=trace terraform init                                                                                                                   130 ↵
2019/11/14 20:16:43 [INFO] Terraform version: 0.12.14
2019/11/14 20:16:43 [INFO] Go runtime version: go1.12.13
2019/11/14 20:16:43 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2019/11/14 20:16:43 [DEBUG] Attempting to open CLI config file: /Users/andrew/.terraformrc
2019/11/14 20:16:43 Loading CLI configuration from /Users/andrew/.terraformrc
2019/11/14 20:16:43 [INFO] CLI command args: []string{"init"}
2019/11/14 20:16:43 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
Initializing modules...
2019/11/14 20:16:43 [DEBUG] Module installer: begin dns
2019/11/14 20:16:43 [TRACE] ModuleInstaller: Module installer: dns <nil> already installed in ../../dns
2019/11/14 20:16:43 [DEBUG] Module installer: begin vpn
2019/11/14 20:16:43 [TRACE] ModuleInstaller: Module installer: vpn <nil> already installed in ../../modules/vpn
2019/11/14 20:16:43 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json

Initializing the backend...
2019/11/14 20:16:43 [TRACE] Meta.Backend: built configuration for "remote" backend with hash value 1213106811

Error: Failed to load state: Terraform 0.12.14 does not support state version 4, please update.
```

### Steps to Reproduce
1. `terraform state mv -backup=original.tfstate.backup -backup-out=destination.tfstate.backup -state-out=../global/.terraform/terraform.tfstate module.vpn module.vpn`
2. `terraform state list`

### Additional Context
macOS 10.14.6

Here is the top of the output `terraform.tfstate`:

```json
{
  "version": 4,
  "terraform_version": "0.12.14",
  "serial": 2,
  "lineage": "9d60e165-d6ee-e8f4-a4a4-e22c6cdba014",
  "outputs": {},
  "resources": [...]
}
```

**Comment by andrewpage** [comment]
Nevermind, I found my problem. I was using a remote backend and trying to `state mv` into the .tfstate file within my `.terraform` directory, which was the wrong thing to do.

What worked for me was:
1. `terraform state pull > terraform.tfstate`
2.`terraform state mv -state-out=terraform.tfstate`
3. `terraform state push terraform.tfstate`

**Comment by mildwonkey** [comment]
thanks for updating this with the resolution!
