### ISSUE TITLE
aws_autoscaling_group should not require availability_zones when vpc_zone_identifier is provided

### ISSUE THREAD

**Issue by bmfurtado** [hashicorp/terraform#2338]
The AWS API documentation about the AvailabilityZones parameter for CreateAutoScalingGroup states:
> This parameter is optional if you specify subnets using the VPCZoneIdentifier parameter.

However, the aws provider for terraform seems to consider availability_zones a required parameter and throws the error:
> "availability_zones": required field is not set

It's a minor nuisance but when working with VPCs the fact that availability_zones and vpc_zone_identifiers are interconnected (since you have to make sure the subnets you provide match the availability zones in the other parameter) can make things unnecessarily hard.

**Comment by thepastelsuit** [comment]
+1

**Comment by ckelner** [comment]
:+1:

**Comment by catsby** [comment]
Patched in https://github.com/hashicorp/terraform/pull/2724, let me know what you think
