### ISSUE TITLE
add -no-color support to terraform 0.12checklist

### ISSUE THREAD

**Issue by mmastoras** [hashicorp/terraform#23380]
### Current Terraform Version
```
Terraform v0.11.14
```

### Use-cases
```
$ terraform 0.12checklist . -no-color
Too many command line arguments. Configuration path expected.

$ terraform -no-color 0.12checklist .
Invalid flags before the subcommand. If these flags are for
the subcommand, please put them after the subcommand.

Usage: terraform 0.12checklist [dir]

$ terraform 0.12checklist -no-color .
Too many command line arguments. Configuration path expected.
```

### Attempted Solutions
See use cases

- #6017

**Comment by teamterraform** [comment]
Hi @mmastoras! Thanks for sharing this feature request.

Unfortunately the `0.12checklist` command is in the 0.11 release series and there are no more releases planned in that series, so we will not be able to act on this request. We agree in retrospect that it would've been useful to support the options like this that are commonly accepted by other Terraform commands, but sadly the opportunity to do so has passed.

Thanks again for sharing this, and sorry this command didn't have more tolerant command line parsing from the outset.
