### ISSUE TITLE
Empty metadata value rejected by GCP APIs

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#2339]
provider google {
        account_file = "service_account_key.json"
        project = "abiding-truth-649"
        region = "us-central1"
    }
    resource "google_compute_instance" "default" {
        name = "test"
        machine_type = "n1-standard-1"
        zone = "us-central1-a"
        disk {
            image = "debian-7-wheezy-v20140814"
        }
        network_interface {
            network = "default"
        }
        metadata {
            "startup-script" = ""
        }
    }

    * Error creating instance: googleapi: Error 400: Required field 'value' not specified, required
Error applying plan:

I suspect this is due to "" being treated as a non-present value or something like that.  I.e. go's string semantics.  We should probably just add logic to omit such k/v pairs.

**Comment by lwander** [comment]
The golang compute API patch fixes this.
