### ISSUE TITLE
local-exec on Windows passes in escaped quotes to CMD /C

### ISSUE THREAD

**Issue by logachev** [hashicorp/terraform#23397]
### Terraform Version
```
Windows
v0.12.9
```

### Terraform Configuration Files
```hcl
resource "null_resource" "connect_device" {
  provisioner "local-exec" {
    command ="az vm run-command invoke -g rg -n vm --command-id RunShellScript --script \"/some/script.sh parameters\""
  }
}
```

### Crash Output
None

### Expected Behavior
`CMD /C "az vm run-command invoke -g rg -n vm--command-id RunShellScript --script "/some/script.sh parameters""`

### Actual Behavior
`CMD /C "az vm run-command invoke -g rg -n vm--command-id RunShellScript --script \"/some/script.sh parameters\""`

### Steps to Reproduce
terraform apply

### Additional Context
`CMD /C` doesn't require internal quotes to be escaped characters. It passes the string that comes after `/C` as-is or by stripping first and last quote symbol.

As a result, if quotes are escaped, they're passed with an escape symbol to the underlying command that might not handle it properly.

**Comment by JesseBropez** [comment]
I too have this issue. It's very frustrating and I cannot find a work around.

**Comment by pkolyvas** [comment]
I'm not a windows expert by any means, but because strings require double quotes, I believe you'll need to escape the quotes within your `command` string.

Ex,:
```
resource "null_resource" "null_command" {
  provisioner "local-exec" {
    command = "echo \"Hello World\""
  }
}
```
