### ISSUE TITLE
Terraform couldn't reach the Terraform Registry

### ISSUE THREAD

**Issue by crispinakomea** [hashicorp/terraform#23390]
Hi there,

We are attempting to begin the upgrade of our terraform version we use from v0.11.14 to v0.12. In order to do so, it is advised that we run the command below to check if there are any pre-upgrade tasks
```
terraform 0.12checklist
```

### Terraform Version

```
Terraform v0.11.14
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.11"
  backend "azurerm" {}
}

provider "azurerm" {
  version = "~> 1.23"
}

resource "azurerm_sql_elasticpool" "sql_elastic_pool" {
  name = "${var.elastic_pool_name}"
  resource_group_name = "${var.app_level_resource_group}"
  location = "${var.location}"
  server_name = "${var.app_level_sqlserver}"
  edition = "${var.performance_tier}"
  dtu = "${var.elastic_pool_dtu_count}"
  pool_size = "${var.elastic_pool_size}"
  db_dtu_min = "${var.db_min_dtu_count}"
  db_dtu_max = "${var.db_max_dtu_count}"

  tags {
    environment = "${var.environment}"
    business_unit_name ="${var.business_unit}"
    application_name ="${var.application_long_name}"
  }
}

```

### Expected Behavior

Our expected behaviour is to get a list of task to perform in order to update the configuration files to for compatibility with v0.12.

If configuration files are compatible, the following output is expected.
```
Looks good! We did not detect any problems that ought to be
addressed before upgrading to Terraform v0.12.

This tool is not perfect though, so please check the v0.12 upgrade
guide for additional guidance, and for next steps:
    https://www.terraform.io/upgrade-guides/0-12.html
```

### Actual Behavior

The following response ids obtained
```
After analyzing this configuration and working directory, we have identified some necessary steps that we recommend you take before upgrading to Terraform v0.12:

- [ ] Terraform couldn't reach the Terraform Registry (at `registry.terraform.io`) to determine whether current provider plugins are v0.12-compatible.
  
  In general, we recommend upgrading to the latest version of each provider before upgrading to Terraform v0.12.

Taking these steps before upgrading to Terraform v0.12 will simplify the upgrade process by avoiding syntax errors and other compatibility problems.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform  0.12checklist`

### Additional Context

Our projects are being executed from a virtual machine on our private network. It has connectivity to trusted sites on the internet typically over https.

**Comment by crispinakomea** [comment]
Just an additional question. Are there any other commands tat require the access of registry.terraform.io?

**Comment by teamterraform** [comment]
Hi @crispinakomea,

Thanks for following the [New Issue](https://github.com/hashicorp/terraform/issues/new/choose) format. It seems as if this is a help request. We encourage our practitioners to use our [community forums](https://discuss.hashicorp.com/c/terraform-core) for such discussions.

Terraform `0.12.x` will use the registry unless the plugin (in this case your provider) is installed locally. The [change was in the release notes](https://github.com/hashicorp/terraform/blob/v0.12.0/CHANGELOG.md), but there's likely an opportunity here to improve our upgrade documentation.

Should you wish to make this or any other provider available locally, there is a means to do so: https://www.terraform.io/docs/configuration/providers.html#third-party-plugins

**Comment by tp20165** [comment]
> 
> 
> Just an additional question. Are there any other commands tat require the access of registry.terraform.io?

Were you able to resolve this issue?
