### ISSUE TITLE
json configuration: provider_config_key does not exist in provider_config map

### ISSUE THREAD

**Issue by nkupton** [hashicorp/terraform#23408]
### Terraform Version
```
Terraform v0.12.15
+ provider.aws v2.37.0
```

### Terraform Configuration Files
main.tf
```hcl
provider aws {
  profile = <my-profile>
  region  = <my-region>
}

module test {
  source = "./test"
}
```
./test/s3.tf
```hcl
resource aws_s3_bucket "example" {
}
```

### Expected Behavior
`provider_config_key` should always map to a value in `provider_configs`
https://www.terraform.io/docs/internals/json-format.html#configuration-representation
>  // "provider_configs" describes all of the provider configurations throughout
>  // the configuration tree, flattened into a single map for convenience since
>  // provider configurations are the one concept in Terraform that can span
>  // across module boundaries.
>  "provider_configs": {
>
>    // Keys in the provider_configs map are to be considered opaque by callers,
>    // and used just for lookups using the "provider_config_key" property in each
>    // resource object.
>    "opaque_provider_ref_aws": {

### Actual Behavior
We have a `provider_config_key` that does not map to any value in `provider_configs`:
plan.json excerpt
```json
"configuration": {
    "provider_config": {
      "aws": {
        "name": "aws",
        "expressions": {
          "profile": {
            "constant_value": <my-profile>
          },
          "region": {
            "constant_value": <my-region>
          }
        }
      }
    },
    "root_module": {
      "module_calls": {
        "test": {
          "source": "./test",
          "module": {
            "resources": [
              {
                "address": "aws_s3_bucket.example",
                "mode": "managed",
                "type": "aws_s3_bucket",
                "name": "example",
                "provider_config_key": "test:aws",
                "schema_version": 0
              }
            ]
          }
        }
      }
    }
  }
```
Note the `aws_s3_bucket.example` resource, `provider_config_key` is `test:aws` which does not map to any key in `provider_config`. Since the plan succeeds, it seems clear terraform is aware that the `aws` provider is the proper inherited reference for this resource, but the given `provider_config_key` does not match.
https://www.terraform.io/docs/internals/json-format.html#configuration-representation
> // Keys in the provider_configs map are to be considered opaque by callers,
> // and used just for lookups using the "provider_config_key" property in each
> // resource object.

### Steps to Reproduce
1. `terraform init`
2. replace `<my-profile>` and `<my-region>` in main.tf with values valid for your environment
3. `terraform plan -out temp && terraform show -json temp > plan.json`
4. Inspect the "configuration" part of plan.json

### Additional Context
We're programmatically analyzing the json plan for details related to each resource's configuration. The goal of this particular setup is to detect which aws profile is being used for any particular resource in the module tree.

**Comment by nkupton** [comment]
Hi @mildwonkey, I just noticed your comment that explains this behavior:
https://github.com/hashicorp/terraform/commit/0c94e20a83261f794c80b5317e0fc3ce9af9c65f#diff-33270eefffdafc8abd40222772f583c3R76
> 	// NOTE: If a given resource is in a ModuleCall, and the provider was
>	// configured outside of the module (in a higher level configuration file),
>	// the ProviderConfigKey will not match a key in the ProviderConfigs map.

Any ideas how I can work around this, to identify the correct provider if this key does not match? It seems terraform must be doing this somehow under the hood to correctly evaluate the module.

**Comment by mildwonkey** [comment]
Hi @nkupton !
I am going to re-label this issue as a feature request; as you discovered, it is expected (but understandably annoying!) behavior. The `show` command does not do all the same provider inheritance parsing that terraform does during plan/apply. 
Thank you for sharing your use case!

**Comment by nkupton** [comment]
Thanks! Would love to see `show` get to the point where it fully describes the information available to the `plan`.

For now we're going to make it our practice that only the root module of our projects should declare a provider. We just had a few edge cases that can be refactored to not use a submodule provider.

**Comment by jacobappleton-orbis** [comment]
This would help me implement some rules using Open Policy Agent (https://www.openpolicyagent.org/docs/latest/terraform/). I am looking to have rules that enforce certain AWS resource configurations being created in certain regions only, but cannot currently link a resource in a module to its provider, and thus region.
