### ISSUE TITLE
trim* functions are not available in 0.12.16

### ISSUE THREAD

**Issue by golonzovsky** [hashicorp/terraform#23413]
### Terraform Version
```
v0.12.16
```

### Terraform Configuration Files
```hcl
resource "helm_release" "es_kibana" {
  chart     = "elastic/kibana"
  name      = "es"
  namespace = kubernetes_namespace.elasticsearch.metadata[0].name
  version   = local.es_version
  values = [templatefile("${local.helm_values_prefix}/es-kibana.yml", {
    dns_host : trimsuffix(var.dns_zone.dns_name, ".")
  })]

  depends_on = [helm_release.es_data]
}
```

### Expected Behavior
according to [release](https://github.com/hashicorp/terraform/releases/tag/v0.12.16) and [docs](https://www.terraform.io/docs/configuration/functions/trimsuffix.html) trim* functions should be available in 0.12.16

### Actual Behavior
```
Error: Call to unknown function

  on modules/elasticsearch/main.tf line 37, in resource "helm_release" "es_kibana":
  37:     dns_host : trimsuffix(var.dns_zone.dns_name, ".")

There is no function named "trimsuffix".
```

**Comment by gechr** [comment]
Oops, sorry! Fixed by https://github.com/hashicorp/terraform/pull/23414

**Comment by jlarocque88** [comment]
Glad to see this has been fixed, any idea when we might see a release with it?

**Comment by StefanSchoof** [comment]
The release tag page still mentions this for 0.12.16: https://github.com/hashicorp/terraform/releases/tag/v0.12.16

**Comment by pselle** [comment]
@StefanSchoof Thanks for that, I've updated that release info (although the CHANGELOG for the tagged release will remain unchanged because of git tagging).

@jlarocque88 It will go out with the next release (0.12.17).

**Comment by 3h4x** [comment]
What a blunder! 😂
