### ISSUE TITLE
0.12.16 create_before_destroy behavior changes

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform#23422]
### Terraform Version

There is a change in behavior with resources that depend on a resource with create_before_destroy between 0.12.13 and 0.12.16
```
Terraform v0.12.16
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    google-beta = "~> 2.20.0"
    google = "~> 2.20.0"
  }
}
data "google_compute_image" "my_image" {
  family  = "debian-9"
  project = "debian-cloud"
}

resource "google_compute_instance_template" "igm-primary" {
  provider       = google-beta
  name_prefix    = "reproducer-stable-"
  machine_type   = "n1-standard-1"
  can_ip_forward = false
  tags           = ["foo", "bar"]

  disk {
    source_image = data.google_compute_image.my_image.self_link
    auto_delete  = true
    boot         = true
  }

  network_interface {
    network = "default"
  }

  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_instance_template" "igm-canary" {
  provider       = google-beta
  name_prefix    = "reproducer-canary-"
  machine_type   = "n1-standard-1"
  can_ip_forward = false
  tags           = ["foo", "bar"]

  disk {
    source_image = data.google_compute_image.my_image.self_link
    auto_delete  = true
    boot         = true
  }

  network_interface {
    network = "default"
  }

  service_account {
    scopes = ["userinfo-email", "compute-ro", "storage-ro"]
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "google_compute_instance_group_manager" "igm-basic" {
  provider           = google-beta
  description        = "Terraform test instance group manager"
  name               = "reproducer"
  base_instance_name = "igm-basic"
  zone               = "us-central1-c"
  target_size        = 2

  version {
    name              = "primary"
    instance_template = google_compute_instance_template.igm-primary.self_link
  }

  version {
    name              = "canary"
    instance_template = google_compute_instance_template.igm-canary.self_link
    target_size {
      fixed = 1
    }
  }
}
```

### Debug Output

https://gist.github.com/migibert/a51ad6521f565f4060aedd93b4337c33#file-tf-output-log
### Expected Behavior

Terraform should update the `google_compute_instance_group_manager` prior to deleting the old `google_compute_instance_template`

### Actual Behavior

Terraform attempts to delete the `google_compute_instance_template` in parallel with updating the `google_compute_instance_group_manager`

### Steps to Reproduce

1. `terraform apply`
2. Modify `data.google_compute_image.my_image` to set `family  = "debian-10"`.
3. `terraform apply` re creating the template and updating the instance group manager.

These steps work with terraform core `0.12.13` and lower, but not in `0.12.16` due to API-level restrictions. This restriction is hit due to a change in behavior between 0.12.13 and 0.12.16

### Additional Context

Prompted by: https://github.com/terraform-providers/terraform-provider-google/issues/4934

Updating the disk family forces the `google_compute_instance_template` to recreate according to `create_before_destroy`. It also causes an update to the `google_compute_instance_group_manager` that depends on the instance template self link. The API requires that the instance group manager cannot reference deleted instance templates, so the update to `google_compute_instance_group_manager` must occur before the deletion of the old `google_compute_instance_template`.

This worked in versions of terraform core <= 0.12.13, and does not work in 0.12.16
Versions 0.12.14 and 0.12.15 did not work due to https://github.com/hashicorp/terraform/issues/23374

In 0.12.16 terraform attempts to delete the old `google_compute_instance_template` in parallel with the update to the `google_compute_instance_group_manager`, which causes the API to throw an error.

It seems like the behavior of terraform core has changed between version 0.12.13 and 0.12.16. I have built the graph with both versions via the `terraform graph` command, and they are identical.

### References
https://github.com/hashicorp/terraform/issues/23374
https://github.com/terraform-providers/terraform-provider-google/issues/4934

**Comment by slevenick** [comment]
I have updated the config, as it seems like two `google_compute_instance_template`s are needed to cause the issue.

During the second apply, both new instance templates are created, and then one of the old ones `igm-canary` is deleted prior to the update of the instance group manager. The deletion for the old instance template for `igm-primary` is correctly done after the update to the instance group manager

**Comment by jbardin** [comment]
Hi @slevenick,

Thanks for the information! Would it be possible to get a trace log using 0.12.16 too? The latest version removes the errant edge causing the cycle, and should produce a more useful output to see what actually changed.

**Comment by jbardin** [comment]
@slevenick, no need for the extra log output, I've identified where create_before_destroy multiple dependents may not get connected.
