### ISSUE TITLE
Minor issue in the turorial

### ISSUE THREAD

**Issue by anandbaskaran** [hashicorp/terraform#23428]
The tutorial available in the link :https://learn.hashicorp.com/terraform/azure/change_az asks the user to create the following tf file.

```
resource "azurerm_resource_group" "rg" {
    name     = "myTFResourceGroup"
    location = "eastus"

    tags {
        environment = "TF sandbox"
    }
}
```

However, there is an error in this file as tags should be assigned like`tags = {enviroinment ="TF Sabdbox"}` as referred to in issue #21742.

**Comment by anandbaskaran** [comment]
Similarly the configuration file provided in the link: https://learn.hashicorp.com/terraform/azure/dependencies_az#complete-configuration is not working.

It fails with the error below, which seem to be very valid:
![image](https://user-images.githubusercontent.com/6847984/69234699-109ad480-0b90-11ea-97b4-61dc6eaca5fc.png)

**Comment by pkolyvas** [comment]
Looks like a PR including the change has been merged!

Ref: https://github.com/hashicorp/learn/pull/865
