### ISSUE TITLE
destroy fails on openstack provider for network ports still in use due to attached floating ip

### ISSUE THREAD

**Issue by gionn** [hashicorp/terraform#2343]
It looks like that terraform on destruct wants to delete one of the two router interfaces before de-allocating a floating ip that requires such interface to work.

May be necessary to explicitly de-attach the floating ip from the instance instead of simply deleting the instance (and get the floating-ip naturally de-attached).

logs: https://gist.githubusercontent.com/gionn/afb3a790f188cf407985/raw/e41cff94dbfb12aac7928ebdaa558cfc1df5440e/gistfile1.txt

Thanks!

**Comment by ggiamarchi** [comment]
In some situations terraform cannot know there is a dependency between resources because there is no explicit reference from one to another. In such a situation, you have to declare dependencies yourself using the attribute `depends_on`.

**Comment by gionn** [comment]
Sounds reasonable, since the floating ip has a dependency only on the instance, that is a slower operation than remove a network, so the error is easy to hit.

May be useful a PR with a working example of a typical deployment on openstack, to be put on the examples/ folder?

**Comment by ggiamarchi** [comment]
Yes, i have some good examples. I'll do a PR.

**Comment by jtopjian** [comment]
#3712 was just merged which might help with this issue. Please let me know.

**Comment by jtopjian** [comment]
I'm going to close this issue as it should have been fixed with #3712. However, if that's incorrect please feel free to re-open or open a new issue. As well, if you run into any other issues similar to this, please let me know!
