### ISSUE TITLE
Crash on empty map in map

### ISSUE THREAD

**Issue by bjornrog** [hashicorp/terraform#23431]
### Terraform Version

```
Terraform v0.12.16
```

### Terraform Configuration Files

```hcl
variable "files_test" {
  type = map(map(any))
  default = {
    "/var/log/amazon/ssm/amazon-ssm-agent.log" = {
      datetime_format = "%Y-%m-%d %H:%M:%S"
    }
    "/var/log/boot.log" = { }
  }
}
```

### Crash Output

https://gist.github.com/bjornrog/aa7c8ec26e8f1701b4d532a591496aac

### Actual Behavior

Crash:

panic: inconsistent map element types (cty.Map(cty.String) then cty.Map(cty.DynamicPseudoType))

### Steps to Reproduce

`terraform init`

Will fail also on `apply`.

### Additional Context

If I add any key/value to the empty map, it will not crash.

**Comment by ahyari** [comment]
I had the same issue and using `object({})` instead `any` seems to solve the issue
