### ISSUE TITLE
Can't change template_file vars with remote state

### ISSUE THREAD

**Issue by sheldonh** [hashicorp/terraform#2344]
I can't change the set of vars declared in a template_file resources when I'm using remote state.

How to repeat:

* Create a template_file resource that declares a variable called `first_name` in its `vars`.
* Interpolate the `first_name` variable into the template file.
* Configure remote state, e.g. `terraform remote config -backend-config="name=hetznerza/terraform-bug"`
* Apply the resource: `terraform apply`.
* Now change the name of the variable to `second_name` in the resource definition and in the template file.
* Run `terraform plan`.
* You will receive the following error:

```
Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* failed to render example.yml: 8:28: unknown variable accessed: second_name
```

I have created [a repository](https://github.com/sheldonh/terraform-bug) that shows an example in this error state.

It seems to me that the complexity of template_file resources in tfstate doesn't pay for itself. We'd be better of storing only a hash of the rendered template_file, as we do for things like aws_instance.user_data.

**Comment by sheldonh** [comment]
The work-around is pretty horrible.

* Warn your team to down tools.
* `terraform remote disable`
* Edit `terraform.tfstate`, hacking the new variable names into the state of the template_file. Remember to bump `"vars.#` accordingly.
* Now you can `terraform plan` and `terraform apply`.
* `terraform remote config -backend-config="name=hetznerza/terraform-bug"`
* Tell your team the war is over.

Alternatively, back out your changes to the template_file definition and the template file, create a new template_file resource (with a new name), use the new one and remove the old one.

**Comment by josephholsten** [comment]
dup #2306

**Comment by josephholsten** [comment]
dup #2013
