### ISSUE TITLE
commands taking too long to respond in MacOS Mojave 10.14.6 (18G103)

### ISSUE THREAD

**Issue by guillemlc** [hashicorp/terraform#23458]
### Terraform Version

```
Terraform v0.12.16
```

### Terraform Configuration Files

```

```

### Debug Output

```
$ export TF_LOG=trace ; time terraform --version
2019/11/21 19:29:57 [INFO] Terraform version: 0.12.16
2019/11/21 19:29:57 [INFO] Go runtime version: go1.12.13
2019/11/21 19:29:57 [INFO] CLI args: []string{"/usr/local/bin/terraform", "--version"}
2019/11/21 19:29:57 [DEBUG] Attempting to open CLI config file: /Users/gliartecano/.terraformrc
2019/11/21 19:29:57 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/11/21 19:29:57 [INFO] CLI command args: []string{"version", "--version"}
Terraform v0.12.16
2019/11/21 19:29:57 [DEBUG] checking for provider in "."
2019/11/21 19:29:57 [DEBUG] checking for provider in "/usr/local/bin"
2019/11/21 19:29:57 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2019/11/21 19:29:57 [DEBUG] found provider "terraform-provider-aws_v2.36.0_x4"
2019/11/21 19:29:57 [DEBUG] found valid plugin: "aws", "2.36.0", "/Users/gliartecano/workspace/git/ebsi-network/ebsi1_orchestration/base/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.36.0_x4"
+ provider.aws v2.36.0
2019/11/21 19:30:00 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=fcc0431b-ff6a-ab58-73e3-c9ed18233eb0&version=0.12.16: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

real	0m42.679s
user	0m0.457s
sys	0m0.166s
```

### Expected Behavior

I would expect Terraform to either succeed and fail immediately. More than 3 seconds for command is unacceptable.

### Actual Behavior

So, as you can see, commands seems to be failing because of this:

``` Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=fcc0431b-ff6a-ab58-73e3-c9ed18233eb0&version=0.12.16: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)```

I try to curl,  and it works fine:

``` $ curl -k Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=fcc0431b-ff6a-ab58-73e3-c9ed18233eb0&version=0.12.16
[1] 55241
[2] 55242
[3] 55243
[2]-  Done                    os=darwin
[3]+  Done                    signature=fcc0431b-ff6a-ab58-73e3-c9ed18233eb0
gliartecano@LM-LXB-00876890 base [dev] $ curl: (6) Could not resolve host: Get
{"product":"terraform","current_version":"0.12.16","current_release":1574120725,"current_download_url":"https://releases.hashicorp.com/terraform/0.12.16/","current_changelog_url":"https://github.com/hashicorp/terraform/blob/v0.12.16/CHANGELOG.md","project_website":"https://www.terraform.io","alerts":[]}
[1]+  Done                    curl -k Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64```


### Steps to Reproduce
<!--
Please list the full steps required to reproduce the issue, for example:
1. Install terrafom in MacOS
2. Run try to run any command
-->

### Additional Context
<!--
Are there anything atypical about your situation that we should know? For example: is Terraform running in a wrapper script or in a CI system? Are you passing any unusual command line options or environment variables to opt-in to non-default behavior?
-->

All other commands and tools run well.

Also, it is worth noting that ANY subcommand even a fake one takes time to process:

```
 time terraform foo
2019/11/21 19:38:15 [INFO] Terraform version: 0.12.16
2019/11/21 19:38:15 [INFO] Go runtime version: go1.12.13
2019/11/21 19:38:15 [INFO] CLI args: []string{"/usr/local/bin/terraform", "foo"}
2019/11/21 19:38:15 [DEBUG] Attempting to open CLI config file: /Users/gliartecano/.terraformrc
2019/11/21 19:38:15 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/11/21 19:38:15 [INFO] CLI command args: []string{"foo"}
Usage: terraform [-version] [-help] <command> [args]

The available commands for execution are listed below.
The most common, useful commands are shown first, followed by
less common or more advanced commands. If you're just getting
started with Terraform, stick with the common commands. For the
other commands, please read the help and docs before usage.

...

real	0m31.981s
user	0m0.062s
sys	0m0.075s
```

### References
<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- #6017

-->

I have looked, but I can't quite find the same.

**Comment by pkolyvas** [comment]
Hi @guillemlc, are you still seeing this behaviour? It may have been a brief issue with the route to our checkpoint endpoint that's now past, and I've been unable to duplicate it on a number of 10.14 machines or VMs.

**Comment by guillemlc** [comment]
Yes, @pkolyvas it is still behaving the same way:

```[dev] $ export TF_LOG=trace ; time terraform --version
2019/11/25 01:36:56 [INFO] Terraform version: 0.12.16
2019/11/25 01:36:56 [INFO] Go runtime version: go1.12.13
2019/11/25 01:36:56 [INFO] CLI args: []string{"/usr/local/bin/terraform", "--version"}
2019/11/25 01:36:56 [DEBUG] Attempting to open CLI config file: /Users/gliartecano/.terraformrc
2019/11/25 01:36:56 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/11/25 01:36:56 [INFO] CLI command args: []string{"version", "--version"}
Terraform v0.12.16
2019/11/25 01:36:56 [DEBUG] checking for provider in "."
2019/11/25 01:36:56 [DEBUG] checking for provider in "/usr/local/bin"
2019/11/25 01:36:56 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2019/11/25 01:36:56 [DEBUG] found provider "terraform-provider-aws_v2.36.0_x4"
2019/11/25 01:36:56 [DEBUG] found valid plugin: "aws", "2.36.0", "/Users/gliartecano/workspace/git/ebsi-network/ebsi1_orchestration/base/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.36.0_x4"
+ provider.aws v2.36.0
2019/11/25 01:36:59 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=darwin&signature=fcc0431b-ff6a-ab58-73e3-c9ed18233eb0&version=0.12.16: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

real	0m42.646s
user	0m0.473s
sys	0m0.179s```

**Comment by pkolyvas** [comment]
Hey @guillemlc I'm sorry you're still experiencing this issue. It looks like some ongoing network connectivity issues to our `Checkpoint` endpoint. 

We don't believe this is a bug. You can speed up your runs by disabling Checkpoint either within a config or by setting an environment variable:
https://www.terraform.io/docs/commands/index.html#upgrade-and-security-bulletin-checks

If you'd like to continue discussing this, I'd invite you to join us at our [community forums](https://discuss.hashicorp.com/c/terraform-core).

**Comment by guillemlc** [comment]
FYI, `disable_checkpoint = true` in `terraform.rc` did NOT have any effect. 

OK, I will follow up in the community forum. I guess that you are implying that I have some configuration issue on my side. While that may be the case, Terraform command is failing to come back on a reasonable time with the error, nevertheless.
