### ISSUE TITLE
Error when using s3 as a source in terraform modules when using environment variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by latikag** [hashicorp/terraform#23463]
### Terraform Version

```
v0.11.6
```

### Terraform Configuration Files

```hcl
module "s3" {
        source = "s3::https://url-to-private-s3-object-example.aws_vpc.zip"

        name = "learntf-vpc"
        cidr = "10.0.0.0/16"
}
...
```

### Debug Output

2019/11/22 11:22:17 [INFO] Terraform version: 0.11.6 
2019/11/22 11:22:17 [INFO] Go runtime version: go1.10.1
2019/11/22 11:22:17 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/1.0.2/versions/0.11.6/terraform", "init"}
2019/11/22 11:22:17 [DEBUG] Attempting to open CLI config file: /Users/lgupta/.terraformrc
2019/11/22 11:22:17 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/11/22 11:22:17 [INFO] CLI command args: []string{"init"}
2019/11/22 11:22:17 [DEBUG] command: loading backend config file: /Path/to/Module/terraform/s3
Initializing modules...
- module.s3
2019/11/22 11:22:17 [TRACE] module source: "s3::https://url-to-private-s3-object-example.aws_vpc.zip"
2019/11/22 11:22:17 [TRACE] detected module source "s3::https://url-to-private-s3-object-example.aws_vpc.zip"
2019/11/22 11:22:17 [DEBUG] fetching module from s3::https://url-to-private-s3-object-example.aws_vpc.zip
2019/11/22 11:22:17 [DEBUG] fetching "s3::https://url-to-private-s3-object-example.aws_vpc.zip" with key "1.vpc;s3::https://url-to-private-s3-object-example.aws_vpc.zip"
  Getting source "s3::https://url-to-private-s3-object-example.aws_vpc.zip"
2019/11/22 11:22:17 [DEBUG] plugin: waiting for all plugin processes to complete...
Error downloading modules: Error loading modules: URL is not a valid S3 URL
### Expected Behavior

I have exported the following env variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as mentioned in the module documentation https://www.terraform.io/docs/modules/sources.html#s3-bucket. So expecting it to validate using them and initialise terraform successfully.
### Actual Behavior

Failed with:
Error downloading modules: Error loading modules: URL is not a valid S3 URL
### Steps to Reproduce

1. export environment variables
   a. export AWS_ACCESS_KEY_ID=<Your access key Id>
   b. export AWS_SECRET_ACCESS_KEY=<Your secret access key>
(This is as per the documentation of terraform as mentioned in https://www.terraform.io/docs/modules/sources.html#s3-bucket)
2. Took the s3 link from a private bucket by copying the url.
2. Run terraform init

**Comment by pkolyvas** [comment]
@latikag The S3 resource requires the the Path-style URL specificially, as noted in the documentation you linked to: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

The S3 bucket URL should include the region for Terraform to be able to to use it.

**Comment by latikag** [comment]
Hi,
After following the documentation properly I have put the following url:

s3::https://s3-us-west-2.amazonaws.com.terraformmoduleforreandeploy/aws_vpc/aws_vpc.zip

but still it is showing error:
Error downloading modules: Error loading modules: URL is not a valid S3 URL

other URLs I have tried are:
s3::https://s3.us-west-2.amazonaws.com.terraformmoduleforreandeploy/aws_vpc/aws_vpc.zip
s3::http://s3.us-west-2.amazonaws.com.terraformmoduleforreandeploy/aws_vpc/aws_vpc.zip
s3::http://s3-us-west-2.amazonaws.com.terraformmoduleforreandeploy/aws_vpc/aws_vpc.zip

I have exported the following input variables:
AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
using terraform version v0.11.6
