### ISSUE TITLE
Template version

### ISSUE THREAD

**Issue by jedineeper** [hashicorp/terraform#2346]
Might be useful to define the version of terraform used to create a template in the template provider block? This could be checked by terraform and allows min-versions to be set for provider features that are only recently available?

Would also potentially be useful to store this in the statefile so if atlas/remote-s3-state is used to check that a compatible (read: higher) version is used when updating the state.

**Comment by phinze** [comment]
This is a great thought, and luckily I believe we already have this covered.

Each Resource has `SchemaVersion int` which can be bumped by provider authors when a backwards-incompatible resource change happens. These versions are stored in the state, and if a version is lower than Terraform's latest version, the Resource's `MigrateState` function is called to "upgrade" the state. If Terraform encounters a SchemaVersion that is higher - it exits with a message informing the user to upgrade.

Does this address your question? If not - hit me with an example scenario and that should help clarify. :+1:

**Comment by jedineeper** [comment]
If I understand that correctly, that sounds great and should work for providers and keeping the state safe :)

Thanks!
