### ISSUE TITLE
Error: orphan resource: Terraform 0.12.13

### ISSUE THREAD

**Issue by jay-ouellette** [hashicorp/terraform#23471]
### Terraform Version

```
Terraform v0.12.13
+ provider.aws v2.35.0
+ provider.template v2.1.2
```

If the state file contains an AWS resource that does not exist, `terraform apply` fails with:

```
Error: orphan resource module.ecs_service_ned_flanders.aws_alb_target_group.app_main still has a non-empty state after apply; this is a bug in Terraform
```

### Expected Behavior

If the state file contains a resource that doesn't exist and is not referenced by any HCL files, then `terraform apply` should remove the non-existent resource from the state file and complete normally.

### Actual Behavior

`terraform apply` fails with non-zero exit status

### Steps to Reproduce

1. Create an AWS resource with `terraform apply`
2. Manually delete the resource with the AWS cli
3. Remove the resource from the the *.tf file
4. run `terraform apply` on an empty *.tf file against the state file that contains the deleted resource

### Additional Context

I accidentally created two `aws_alb_target_group` with the same name in separate terraform modules with separate state files. I was able to delete the first one, but when I tried to deleted duplicate, terraform failed because the state file contained a non-existent  resource.

**Comment by pkolyvas** [comment]
Hi @jay-ouellette I think there's a tool just for the case you describe:
https://www.terraform.io/docs/commands/state/rm.html

You can remove items from the state manually if they're accidentally been managed/changed/removed outside of Terraform. This command is a bit like the opposite of `import`.

I think this is what might help you, but if I got the use case wrong, and there's an issue here, please feel free to re-open this ticket.
