### ISSUE TITLE
Terraform plugins expect darwin_amd64 on an Intel I9 Macbook

### ISSUE THREAD

**Issue by rbrondgeest** [hashicorp/terraform#23486]
### Terraform Version

```
Terraform v0.12.16
+ provider.google v2.18.1
+ provider.helm v0.10.4
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```
### Expected Behavior
Plugins are expected to be built for Darwin i386 architecture and located in ~/.terraform.d/plugins/darwin_386 on my i386 machine.

### Actual Behavior
Plugins are expected to be built for Darwin amd64 architecture and are expected to be located in ~/.terraform.d/plugins/darwin_amd64 on my i386 machine.

### Steps to Reproduce
1. Download a community plugin, with darwin_386 architecture(e.g. https://github.com/carlpett/terraform-provider-sops/releases)
2. Unzip into `~/.terraform.d/plugins/darwin_386
3. `terraform init`

### Additional Context
```
$ uname -msp
Darwin x86_64 i386

$ tf init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "sops" not available for installation.

A provider named "sops" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64
```

After getting my hands on the `darwin_386` build, and putting it in the     `terraform.d/plugins/darwin_386` directory, the plugin DOES NOT work.

After getting my hands on the `darwin_amd64` build, and putting it in the     `terraform.d/plugins/darwin_amd64` directory, the plugin DOES work.

**Comment by rbrondgeest** [comment]
Seems to be quirkiness of golang... Ill close this then

**Comment by jbardin** [comment]
Hi @rbrondgeest,

Just to help you out in the future, there is no supported 32bit darwin (which is why we no longer have darwin_386 releases). The `uname -p` output was left as `i386` for the processor family type for compatibility reasons, the `-m` flag is what shows the actual kernel type.

**Comment by rbrondgeest** [comment]
@jbardin thanks... uname -m just output "Darwin"

I've learned by now that the "64 bit instruction set" was invented by AMD and therefore is named AMD64. Even for intel machine's, you need a Darwin_amd64 package, if you are running on a 64 bit CPU machine
