### ISSUE TITLE
State transmitted in cleartext for azurerm backend with SAS token

### ISSUE THREAD

**Issue by phekmat** [hashicorp/terraform#23493]
### Terraform Version

```
Terraform version: 0.12.16
```

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.36.1"
}
terraform {
  backend "azurerm" {
    storage_account_name = "<REDACTED>"
    container_name       = "tfstate"
    key                  = "terraform.tfstate"
  }
}
```

### Expected Behavior

Terraform should transfer state over HTTPS
### Actual Behavior

Terraform transmits the state over HTTP 
### Steps to Reproduce

1. Create a SAS token for the storage account with either the `spr` set to `https,http` or not present
1. Run a `plan` using the SAS token for authenticating
### Additional Context

This was originally discovered under the azure provider as https://github.com/terraform-providers/terraform-provider-azurerm/issues/4912 and is related to https://github.com/Azure/azure-sdk-for-go/pull/4870. Terraform is still using an older version of the SDK which doesn't have this fix. Workarounds are to set the `spr` to `https` or use an access key instead. 

With the SDK fix, if `spr` is `https,http`, then HTTP is also used instead of HTTPS.

### References

- https://github.com/terraform-providers/terraform-provider-azurerm/issues/4912
- https://github.com/Azure/azure-sdk-for-go/pull/4870

**Comment by pkolyvas** [comment]
Thanks for submitting this issue report. We take security concerns very seriously. This issue is in triage and we will post an update here shortly.

**Comment by pkolyvas** [comment]
We have reproduced this issue and are working on a fix.

**Comment by danieldreier** [comment]
We have a fix pending in the [linked PR](https://github.com/hashicorp/terraform/pull/23496). We're expecting to merge it and release it in v0.12.17 on Monday. @phekmat and @giggio thank you for reporting this issue!
