### ISSUE TITLE
Call to function "jsondecode" failed: invalid character '}' looking for beginning of object key string.

### ISSUE THREAD

**Issue by bodonald** [hashicorp/terraform#23501]

**Comment by bodonald** [comment]
Terraform Version
Terraform v0.12.16
+ provider.aws v2.39.0

**Comment by bodonald** [comment]
Code Screenshot

![image](https://user-images.githubusercontent.com/53879533/69635263-4f2f0400-1054-11ea-8c15-b1535c801e01.png)

![image](https://user-images.githubusercontent.com/53879533/69635414-9b7a4400-1054-11ea-985c-94e333aa931c.png)

**Comment by danieldreier** [comment]
Hi @bodonald! Thank you for reporting this. My next step to triage this is to reproduce it on my own workstation, and it would be much easier and less error-prone if I didn't have to re-type it from your screenshot. If you can copy-paste your reproduction code into the issue as text it would be much easier for me to work on reproducing.

**Comment by bodonald** [comment]
@danieldreier hello Daniel, 
apologies, please look bellow the code.  

resource "aws_secretsmanager_secret" "Mon_new_secret2" {
  name = "Mon_new_secret2"
}

resource "aws_secretsmanager_secret_version" "Mon_new_secret2" {
  secret_id = aws_secretsmanager_secret.Mon_new_secret2.id
  secret_string = <<EOF
  {

    "MYSQL_USERNAME":"${var.mysql_password}",
    "MYSQL_PASSWORD":"${jsondecode(data.aws_secretsmanager_secret_version.Mon_new_secret2.secret_string)["MYSQL_PASSWORD"]}",
    "KEY":"125ssw74a223441qq12~~dr"


  }
EOF
}
data "aws_secretsmanager_secret" "Mon_new_secret2" {
  name = "Mon_new_secret2"
}
data "aws_secretsmanager_secret_version" "Mon_new_secret2" {
  secret_id = data.aws_secretsmanager_secret.Mon_new_secret2.id
}


what I want is to use the jsondecode function in order take "MYSQL_PASSWORD" directly from secret manager. 

but what i have is the error as bellow 


Error: Error in function call

  on secrets.tf line 39, in resource "aws_secretsmanager_secret_version" "Mon_new_secret2":
  39:     "MYSQL_PASSWORD":"${jsondecode(data.aws_secretsmanager_secret_version.Mon_new_secret2.secret_string)["MYSQL_PASSWORD"]}",
    |----------------
    | data.aws_secretsmanager_secret_version.Mon_new_secret2.secret_string is "{\n\n    \"MYSQL_USERNAME\":\"test-username\",\n    \"MYSQL_PASSWORD\":\"test_pwd\",\n    \"KEY\":\"test-key\",\n\n\n  }"

Call to function "jsondecode" failed: invalid character '}' looking for

**Comment by bodonald** [comment]
hello @danieldreier you can close this issue, I found the solution, it was due the the "," at the end of the the JSON code during the creation of aws_secretsmanager_secret_version. 

and this was a syntaxe mistake as JSON does not take the "comma" at the end of the last line of the block code
