### ISSUE TITLE
Better documentation about ports

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2351]
Just a bit of feedback - I found the ports section of the main docs to be confusing when setting up the required fw openings (e.g. security_group rules in AWS) because the source, and destination are not clearly explained in each port description.

It would be much clearer to have a common format for explaining each port and say something like:
<PURPOSE> (Default XXXX TCP/UDP/TCP+UDP) From <src-host-type> to <dest-host-type> for the purpose of <description>

As it stands, 8300 and 8302 fulfils the above, 8301 does not explain that agents are the source (or is it only clients are the source, I dont know), 8400 doesnt really explain the source other than it being the CLI - the cli would typically be run on the host itself (hence source being local), or remotely?, 8500 doesnt explain the dest - the HTTP API of the servers? or any agent? - and 8600 once again doesnt explain that all agents can serve DNS requests, and the source could be anything.

It would be awesome to be able to look at the paragraph on ports and know exactly what rules to fw rules to implement straight away

**Comment by phinze** [comment]
I think this bug report was meant for consul? Terraform doesn't listen on any ports. :grinning: 

Let me know if I'm missing something here, but I'm going to close this in the meantime. :+1:
