### ISSUE TITLE
The argument "region" is required, but was not set.

### ISSUE THREAD

**Issue by Craigfis** [hashicorp/terraform#23517]
I'm using Terraform version 12.16 and trying to run terraform apply to update a deployment.

```
Terraform v0.12.16
+ provider.aws v2.20.0
```

### Terraform Configuration Files

```hcl
provider "aws" {
    version = "~> 2.17"
    region = "us-west-2"
}

...
```

### Debug Output
Unable to share.

### Expected Behavior
Should succeeed.

### Actual Behavior
Error

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### References
https://github.com/terraform-providers/terraform-provider-aws/issues/9989

**Comment by pkolyvas** [comment]
Hi @Craigfis, unfortunately there's not enough here to go on, but did have a chance to read @bflad 's response to the referenced issue? It might help explain what's going on.
