### ISSUE TITLE
Unable to compile using version tag

### ISSUE THREAD

**Issue by tmeckel** [hashicorp/terraform#23511]
### Description

While trying to build Terraform using a release tag the compilation stops while parsing (evaluating) the go.mod file with the following error

```
go get: github.com/Unknwon/com@v0.0.0-20151008135407-28b053d5a292 updating to
        github.com/Unknwon/com@v1.0.1: parsing go.mod:
        module declares its path as: github.com/unknwon/com
                but was required as: github.com/Unknwon/com
```

### Expected Behavior

Being able to compile (build) Terraform using a git tag.

### Actual Behavior

Build fails with error

### Steps to Reproduce

```sh
export GO111MODULE='on'
go get -v -u 'github.com/hashicorp/terraform@v0.12.16'
```

### References

N/A

### Proposed fix

The string `Unknwon` must be all lower-case `unknwon`

https://github.com/hashicorp/terraform/blob/60e407a59baef661f94f216ff6c5462500b7b081/go.mod#L7

**Comment by wwan01** [comment]
Hi @tmeckel, I have the same error today, how did you solve it?

**Comment by tmeckel** [comment]
There's no solution on our end... Hashicorp must clean up their go.mod file... As simple as that

**Comment by tmeckel** [comment]
Although I've to admit that I never tried to combine 'GO111MODULE=ON' with '-mod=vendor' as build flag. :smile:

**Comment by wwan01** [comment]
Thanks a lot for your reply!

**Comment by t0rr3sp3dr0** [comment]
I can confirm this bug is still present on Terraform v0.12.24

**Comment by nkall** [comment]
I believe this is a duplicate of https://github.com/hashicorp/terraform/issues/22341. I imagine upgrading the openstack dependency listed there would fix the build

**Comment by tmeckel** [comment]
@nkall yes it definitely is! :grin:

**Comment by tmeckel** [comment]
Closing this because at least with v0.12.29 it's possible to use `go get` to install Terraform locally using a version tag

![image](https://user-images.githubusercontent.com/14177833/88333485-9e871a80-cd30-11ea-93c2-1a8f0889f0a7.png)
