### ISSUE TITLE
Typo (?) in allowed port number range, port 65536 is not valid

### ISSUE THREAD

**Issue by jwlogemann** [hashicorp/terraform#23519]
Hi,
I created a module that wraps aws_alb_target_group amongst other things, and set the default value of "port" and healthcheck.port to 0. When I run terraform apply I get the following errors:

Error: expected port to be in the range (1 - **65535**), got 0
Error: "health_check.0.port" must be a valid port number (1-**65536**) or "traffic-port"

I understand that "0" is not a valid port number, but I'm fairly certain that port numbers only go up to 65535

The same error is in the documentation: https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#port-1

The documentation for "lb_listener" is correct though: https://www.terraform.io/docs/providers/aws/r/lb_listener.html#port-1

### Terraform Version
0.12.13

### Expected Behavior
Port number stop at 65535

### Actual Behavior
port number shown is 65536

**Comment by bradleypmartin** [comment]
Hey @jwlogemann , thanks for contributing this Issue! I was looking through open PRs today to see if anyone had tackled it, and didn't find anything with a quick substring search.

I also haven't seen further discussion here, so if it's okay, I'm going to whip up a PR to address the typo. Good catch!

**Comment by bradleypmartin** [comment]
Hey once again! So I did a bit more digging (thanks for your patience; this'll be my first open-source PR! :) ) and I found where we can make this change in the `terraform-providers` repo.

As linked automatically up above, [a PR is now open](https://github.com/terraform-providers/terraform-provider-aws/pull/11410) to make this change happen.

**Comment by bflad** [comment]
The downstream Terraform AWS Provider pull request has been merged and will publish when version 2.44.0 is released next week. Thanks @bradleypmartin for fixing this. 👍 

@pkolyvas please note that for provider issues you can mark the issue with `provider/XXX` (e.g. `provider/aws` in this case) to have hashibot automatically transfer the issue to the provider repository across GitHub organizations. 😄
