### ISSUE TITLE
Version attributes in docs

### ISSUE THREAD

**Issue by jjshoe** [hashicorp/terraform#2352]
When you add an attribute to an existing resource you should put the version it was added in the docs, ansible does this. If you want to take it a step further provide the ability to select your version from the drop down so you can see what's available.

**Comment by mitchellh** [comment]
This is a reasonable request. I'm open to it. 

@phinze @catsby Are you open to following this?

**Comment by mitchellh** [comment]
For the record, we'll do this from this point forward. It would be far too tedious to backport this, but if someone did it for us (PR), I'd be happy and grateful to see it!

**Comment by catsby** [comment]
:+1:
