### ISSUE TITLE
Error when using any s3 bucket as a source in terraform modules

### ISSUE THREAD

**Issue by latikag** [hashicorp/terraform#23537]
### Terraform Version

```
v0.11.6. AWS provider version: 2.26.0
```

### Terraform Configuration Files

```hcl
module "vpc" {
        source = "s3::https://s3-us-west-2.amazonaws.com/tfmodulebucket-vpc/aws/aws_vpc.zip"

        name = "learntf-vpc"
        cidr = "10.0.0.0/16"
}
```

### Debug Output

https://gist.github.com/latikag/6ad7c6d4284551743660eba28c268bf7

### Steps to Reproduce

1. `terraform init`
### Additional Context

`AWS provider version is 2.26.0`
`Exported env variables  AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY `

**Comment by pkolyvas** [comment]
Hi @latikag  I believe the URL should be `https://s3.us-west-2.amazonaws.com/tfmodulebucket-vpc/aws/aws_vpc.zip` according to the [AWS documentation on S3 path-style URLs.](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro)

Did terraform crash or you simply provided the debug output to help triage the issue?

**Comment by latikag** [comment]
Hi @pkolyvas I had set my provider-region us-gov-west-2 while the bucket region was us-west-2, and after i changed my provider region to us-west-2 it is now working. Is it a requirement to keep same region, even if the bucket is a public one?

**Comment by pkolyvas** [comment]
Thanks for the response @latikag.

Yes, the path-style URL needs to include the region of the bucket itself, even if that bucket is public.
