### ISSUE TITLE
Moving from one aws_security_group to many resulted in diff failure

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2354]
Terraform 0.5.2

I had lots of aws_instance resources in one aws_security_group.

I created more security_groups, and added them the list of the aws_instance security_groups.

They did not "attach" with AWS revealing that each instance only retained its original security group - although it did work after a destroy and an apply. However it did not migrate to that position, and terraform bailed with a warning that diffs dont match and to please raise this as a bug.

**Comment by mitchellh** [comment]
Can you please show us a config and set of steps to reproduce this? It would help immensely. Thanks!

**Comment by catsby** [comment]
Hey @gtmtech – I'm going to close this for now. If you do have more information to help us reproduce and diagnose this, please reopen the issue. Thanks!
