### ISSUE TITLE
aws_dlm_lifecycle_policy | AWS Target Tag not working from tf but works via AWS

### ISSUE THREAD

**Issue by martinwoods** [hashicorp/terraform#23541]
Hi,

Apologies if this turns out to be an AWS issue - but in the hope that someone can help me here and it is a tf issue I'm going to ask :)

I've created a DLM policy with the following target tag:
`
                "target_tags": {
                  "kubernetes.io/created-for/pvc/name": "mongodb"
                }
`

The idea here is that any volume with the a tag that contains the string `mongodb` would be picked up and a snapshot created via the DLM policy

My validate and plan & apply all work fine - it's just that when the policy is supposed to run it doesn't

But if I manually set this up in AWS with the exact same target tag for my policy it works fine, for example it will pick up volumes with the following tags under the policy:
`
kubernetes.io/created-for/pvc/name:123-mongodb-abc`
`kubernetes.io/created-for/pvc/name:mongodb-abc`
`kubernetes.io/created-for/pvc/name:123-mongodb`

Due to the fact that the policy I setup manually worked I decided to import it into my test terraform configuration to see if there was any difference in the `terraform.tfstate` file.

After I ran the import and viewed the state file it had exactly the same target tag `"kubernetes.io/created-for/pvc/name": "mongodb"`. My expectation was that there might be something different

So we're slightly confused as to why the GUI would work and why the Terraform DLM policy would behave differently - If anyone has any comment on this I'm all ears?

Many Thanks

**Comment by danieldreier** [comment]
@martinwoods I am happy to try and reproduce this, in case there's a TF bug. You might also try posting it at https://discuss.hashicorp.com/c/terraform-core to see if other users have seen similar behavior.

If I understand right, you're trying to set an AWS EBS lifecycle policy that automatically snapshots (deletes?) ebs volumes that are tagged with `"kubernetes.io/created-for/pvc/name": "mongodb"`. When you create that DLM policy via the GUI it behaves as expected and when you create it via terraform it never executes. Is that right?

Do you mind showing the exact AWS console showing what the manually-created and TF-created DLM policies look like? I'm wondering if there's some subtle difference between the target tags or policies you're creating vs what TF is creating.

**Comment by martinwoods** [comment]
@danieldreier thanks for the quick reply. I think this may actually be a AWS issue, it seems that it allows fuzzy matching on creation of the policy and when you action the **"Target volumes with these tags"** hyperlink in the policy **Details** window it will list the results of that fuzzy match but when the actual policy time is executed to take a snapshot it will only work on exact match. So a bit of a PEBCAK moment when running my tests above but there still is an actual issue on the AWS side I think, not sure yet if this functionality is intentionally designed that way but it does look a little odd that they allow a fuzzy match list as the list will not match on the actual snapshots taken. Thanks
