### ISSUE TITLE
Add "each.index" for iterators

### ISSUE THREAD

**Issue by donwoodruff** [hashicorp/terraform#23557]
### Current Terraform Version

```
0.12.17
```

### Use-cases

When iterating through a map with for_each, there are many scenarios that would benefit from having access to iteration count (see example workaround).
### Attempted Solutions

I have created a kludge as shown below (AWS is used, but knowledge of AWS not really necessary).  I have a few scenarios where I do things like this (anytime I need an iterator value) - so the list of integers is longer than my largest use-case.
```
locals {
  az_list = ["us-east-1a", "us-east-1b", "us-east-1c"]
  // Normally - the az_list is pulled from a data source - but for clarity I made it by hand
  integers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  az_iterator = zipmap(local.az_list, slice(local.integers, 0, length(az_list)))
}

resource "aws_subnet" "foo" {
    for_each = local.az_iterator
    vpc_id = var.vpc_id
    availability_zone = each.key
    cidr_block = cidrsubnet("10.100.100.0/24", 2, each.value)
   // As the offset moves with each iteration - this splits a subnet block into chunks
}
```
### Proposal

Within terraform, even when iterating with for_each, it should be simple to track (zero-based) the iteration count - which could be exposed by adding "each.index" as a companion to "each.key" and "each.value". It would be very similar to "count.index" available when iterating with "count".

**Comment by donwoodruff** [comment]
BTW: I know the new "cidrsubnets" can do this as well - but the resulting list would STILL need an index value... I am actually using cidrsubnets in new code

**Comment by teamterraform** [comment]
Hi @donwoodruff,

Thanks for the proposal. The `for_each` construct operates of unordered sets and maps, which is the key difference between `for_each` and `count`.  An `index` value in this case would not be consistent between runs, as the resources would be randomly re-assigned to different indexes. The primary purpose for `for_each` is to uncouple the resource from ordering altogether, so that individual resources can be added and removed without effecting the index of the entire group, which we cannot do once an index value is inserted. 

For any index-based needs, the recommended method is still going to be to use `count`.

Thanks

**Comment by donwoodruff** [comment]
Well - this is called "totally missing the point" - which was to give the ITERATOR the ability to do math, but not to trap the elements into an ordered result (the only HUGE advantage of for_each). As noted - I ignore changes to the assignment (my job) - but I do use the math to make the INITIAL assignment. I am not trying to access values via iterator - in my example (which does note have the lifecycle ignore_changes that makes this safe), I am simply tracking the number of executions for the reasons of randomly assigning resources...

Of course - we can all continue to use workarounds - but going back to the fragile count scenario where a change could whack all the objects created instead of just one - is a huge backward step.

In this case - you envision the POOR usage that COULD occur through uneducated use of this feature and assume that the potential for novices to make mistakes (note: Terraform is FULL of tripwires for n00bs... even now I am still throwing away code I created months ago because the documentation lacks completeness and clarity.

Again - the iterator "index" (something unique to the iterator construct - not en enhancement to the data type) was to allow us to do iterative math/assignment - and we can use lifecycle to ignore changes to those results (and it is quite effective)... but as there is a workaround (and I have used it successfully for many months now without a single unexpected result) - I guess we all continue to employ the ugly workarounds... but I would caution against purity of concept overriding the usefulness of the product - that is something that only holds water until there is serious competition that is willing to work through the issues that people have with the existing products... and I really don't want to be learning a new product next year because I can't get what I need out of Terraform due to some artificial purity construct.

**Comment by donwoodruff** [comment]
BTW - the "safe" hook was (because these things can never be "changed")
````
lifecycle {
  ignore_changes = [availability_zone, cidr_block]
}
````

**Comment by donwoodruff** [comment]
Also note that in my construct - I am essentially creating a map from two ordered lists... When I use a list and for_each - I use toset() to iterate - and to date (hundreds of runs) - the set created has the same order as the list that created it. Perhaps this is accidental/unintentional - but do understand that if that is the way it works - people will begin solutioning using that behavior. Undocumented but consistent behavior becomes an accepted standard over time.
