### ISSUE TITLE
deps for v0.5.3 are incomplete

### ISSUE THREAD

**Issue by swills** [hashicorp/terraform#2356]
The deps for the main binary are complete, but all the ones for plugins are missing. This includes:

github.com/pearkes/cloudflare
github.com/xanzy/go-cloudstack
github.com/pearkes/digitalocean
github.com/soniah/dnsmadeeasy
github.com/imdario/mergo
github.com/pearkes/dnsimple
github.com/fsouza/go-dockerclient
golang.org/x/oauth2
golang.org/x/net
google.golang.org/api
google.golang.org/cloud
github.com/cyberdelia/heroku-go
code.google.com/p/go-uuid
github.com/pearkes/mailgun
github.com/rackspace/gophercloud
github.com/dylanmei/winrmtest
github.com/masterzen/winrm
github.com/mitchellh/go-linereader
github.com/packer-community/winrmcp/winrmcp
github.com/dylanmei/iso8601
github.com/masterzen/simplexml/dom
github.com/mitchellh/packer/common/uuid
github.com/nu7hatch/gouuid
github.com/satori/go.uuid
github.com/masterzen/xmlpath
github.com/armon/circbuf

**Comment by phinze** [comment]
Ah dang you're right :disappointed: 

I mis-documented this in `RELEASING.md` - it should be `godep save ./...` not just `godep save`.

Will update that - and I think we can cheat and reconstruct the deps from the homebrew formula.

**Comment by phinze** [comment]
Alright updated and documented - cherry picking the attached commit should allow a build from v0.5.3

**Comment by swills** [comment]
There still seem to be some issues with the deps.  So far, I've found:

The github.com/hashicorp/aws-sdk-go, the only reference to it that I can find is in deps/v0-4-1.json, so I'm not sure how godep is finding that.

The github.com/mitchellh/iochan dependency is only used by github.com/mitchellh/packer, but the part of packer that uses iochan isn't used, so the dep really isn't used or needed.

The github.com/docker/docker dependency doesn't seem to be used either, as the only place I can find it is again in deps/v0-4-1.json, tho it looks like maybe it used to be used as github.com/fsouza/go-dockerclient seems to vendor a copy of it.

Likewise, github.com/Sirupsen/logrus isn't used but vendored by fsouza/go-dockerclient. 

Sorry if this is noise, perhaps at this point I'm just documenting bugs in godep or it's lack of understanding of gox and the way it's used.

And thanks for filling in the gaps on the missing deps!

**Comment by phinze** [comment]
@swills thanks for digging into this. I'm hoping to release 0.6.0 this week and what I'll do this time is check make a release branch with a commit that vendors all the build dependencies (as recommended/required by godeps). That should get us a legitimately reproducible build. If it works well I'll update the release notes so we continue to do that going forward.
