### ISSUE TITLE
unable to mv module for_each instances to new module with new module alias

### ISSUE THREAD

**Issue by holeunlee** [hashicorp/terraform#23569]
### Terraform Version
```
Terraform v0.12.16
+ provider.oci v3.48.0
```

### Terraform Configuration Files
Not applicable for this case

### Expected Behavior
module alias is expected to be renamed

### Actual Behavior
module alias is not renamed and errored with module not existing

### Steps to Reproduce

15:25 $ terraform state mv 'module.base_vcn_subnets_custom_dns.oci_dns_record.default["deletable1.ohisc2.local"]' 'module.base_vcn_subnets_custom_dns.oci_dns_record.default["deletable3.ohisc2.local"]'
Move "module.base_vcn_subnets_custom_dns.oci_dns_record.default[\"deletable1.ohisc2.local\"]" to "module.base_vcn_subnets_custom_dns.oci_dns_record.default[\"deletable3.ohisc2.local\"]"
Successfully moved 1 object(s).

15:25 $ terraform state mv 'module.base_vcn_subnets_custom_dns.oci_dns_record.default["deletable3.ohisc2.local"]' 'module.base_vcn_subnets_custom_dns.oci_dns_record.default["deletable1.ohisc2.local"]'
Move "module.base_vcn_subnets_custom_dns.oci_dns_record.default[\"deletable3.ohisc2.local\"]" to "module.base_vcn_subnets_custom_dns.oci_dns_record.default[\"deletable1.ohisc2.local\"]"
Successfully moved 1 object(s).

15:25 $ terraform state mv 'module.base_vcn_subnets_custom_dns.oci_dns_record.default["deletable1.ohisc2.local"]' 'module.base_vcn_subnets_custom_dns_test.oci_dns_record.default["deletable3.ohisc2.local"]'
Move "module.base_vcn_subnets_custom_dns.oci_dns_record.default[\"deletable1.ohisc2.local\"]" to "module.base_vcn_subnets_custom_dns_test.oci_dns_record.default[\"deletable3.ohisc2.local\"]"

Error: Invalid target address

Cannot move to
module.base_vcn_subnets_custom_dns_test.oci_dns_record.default["deletable3.ohisc2.local"]:
module.base_vcn_subnets_custom_dns_test.oci_dns_record.default does not exist
in the current state.

### Additional Context
Invalid target address is issued in the last mv command, which is expected it to be fixed in version 0.12.6.

Within the module a for_each has been used to create resources. As an example I have recreated the original problem to a more simplified version. A dummy example within bugfix #21346 has been tried unsuccesfully. 

### References
- #21346

**Comment by danieldreier** [comment]
@holeunlee do you think you can come up with a reproduction case that doesn't involve the OCI provider? I don't have any OCI infrastructure available for local reproduction so this will be difficult for me to assess as-is. I've been trying to reproduce issues using [null_resource](https://www.terraform.io/docs/providers/null/resource.html) when possible because it has the simplest reproduction case and the fewest dependencies on provider-specific details.

**Comment by holeunlee** [comment]
Hi danieldreier,

thank you for your response. currently it is my first project with terraform, and I am unable to provide some example code within AWS. Are there any resources you can create for free within AWS?

The main thing which I am trying to do, is to move an "instance" (terraform state terminology) from module to module. I expect terraform to create this new module resource and move the "instance" into it. I assume it fails to move the instance as the new module (including resource and its alias) is not existing.

As I read the documentation in https://www.terraform.io/docs/commands/state/mv.html, there doesn't seem to be an example case for this. This seem to be a combination of these 2 examples
1. Example: Move a Module Into a Module
2. Example: Move a Resource configured with for_each

I will provide my terraform code, maybe you are able to create a similar thing. basically it is a module which creates for_each instances. Afterwards, try to move the for_each instances to another module.

main.tf 
=====================
module "mydestinationmodulename" {
  source = "./temporary"
}

temporary/fakedns.tf
=====================
variable "record" {
  type = map(string)

  default = {
    "record1.domain.local" = "10.0.254.254"
    "record2.domain.local" = "10.0.254.253"
  }
}

resource "oci_dns_record" "default" {
  for_each = var.record
  domain = each.key
  rtype = "A"
  rdata = each.value
  zone_name_or_id = "domain.local"
  ttl = 3600
}

Hope this provides a bit of more information to reproduce the issue!

**Comment by holeunlee** [comment]
I have been trying some more thing and came up with more findings.. This **seems** to be a bug when moving for_each instances out of a resource into a new (not-yet created) resource

1. I have converted the module to a non-module resource with terraform state mv module, so my resources are now:
oci_dns_record.default["deletable1.ohisc2.local"]
oci_dns_record.default["deletable2.ohisc2.local"]

2. Next I want to move the instance oci_dns_record.default["deletable1.ohisc2.local"] to a new resource with alias 'new' which fails with the same error as before.

_Cannot move to oci_dns_record.new["deletable1.ohisc2.local"]:
oci_dns_record.new does not exist in the current state._

3. Now I at least know it is not the fault of the instance being in a module. But actually, the basic movement of a for_each into a new resource is acting weird.
