### ISSUE TITLE
String regex function errors

### ISSUE THREAD

**Issue by Jaff** [hashicorp/terraform#23587]
### Terraform Version
```
Terraform v0.12.17
```

### Terraform Configuration Files

```hcl
locals {
  random_string       = "12345xxyyxyxzzzabcdefghijk.54321"
  transform1          = "regex(\"[xyz]+\", local.random_string)"
  transformed_string1 = regex("[xyz]+", local.random_string)
  transform2          = "regex(\"[^x]+\", local.random_string)"
  transformed_string2 = regex("[^x]+", local.random_string)
  transform3          = "regex(\"[^y]+\", local.random_string)"
  transformed_string3 = regex("[^y]+", local.random_string)
}

output "transform1"          { value = local.transform1 }
output "transform2"          { value = local.transform2 }
output "transform3"          { value = local.transform3 }
output "random_string"       { value = local.random_string }
output "transformed_string1" { value = local.transformed_string1 }
output "transformed_string2" { value = local.transformed_string2 }
output "transformed_string3" { value = local.transformed_string3 }
```

### Expected Behavior

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

random_string = 12345xxyyxyxzzzabcdefghijk.54321
transform1 = regex("[xyz]+", local.random_string)
transform2 = regex("[^x]+", local.random_string)
transform3 = regex("[^y]+", local.random_string)
transformed_string1 = xxyyxyxzzz
transformed_string2 = 12345yyyzzzabcdefghijk.54321
transformed_string3 = 12345xxxxzzzabcdefghijk.54321
```
### Actual Behavior

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

random_string = 12345xxyyxyxzzzabcdefghijk.54321
transform1 = regex("[xyz]+", local.random_string)
transform2 = regex("[^x]+", local.random_string)
transform3 = regex("[^y]+", local.random_string)
transformed_string1 = xxyyxyxzzz
transformed_string2 = 12345
transformed_string3 = 12345xx

```
### References
n/a

**Comment by Jaff** [comment]
[regex_test.log](https://github.com/hashicorp/terraform/files/3933708/regex_test.log)
Debug log

**Comment by Jaff** [comment]
Determined I could use `join("", regexall("[^aeiou]+", local.random_string))` to trim vowels

**Comment by Jaff** [comment]
There's probably still an existing bug in `regex` function, you should add more tests

**Comment by jbardin** [comment]
Hi @Jaff,

This is the correct behavior for regular expressions. 

For example, the regex `[^x]+` means "match the first groups of one or more contiguous characters that aren't `x`", which returns the prefix `12345`.

You can achieve the output you want via a regex in a couple ways. The `regexall` function will return all matching groups which you can concatenate:

    join("", regexall("[^x]+", local.random_string))

which results in `12345yyyzzzabcdefghijk.54321`

Or you can filter them via `replace`, which interprets anything wrapped in `//` as a regex:

    replace(local.random_string, "/[xyz]/", "")

which results in `12345abcdefghijk.54321`
