### ISSUE TITLE
provider/aws: Route Table Data Source resource ordering

### ISSUE THREAD

**Issue by grubernaut** [hashicorp/terraform#23604]
### Terraform Version
`0.8.3` and master

### Affected Resource(s)
Please list the resources as a list, for example:
- data_source_aws_route_table

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "test" {
  cidr_block = "172.16.0.0/16"
}

resource "aws_subnet" "test" {
  cidr_block = "172.16.0.0/24"
  vpc_id = "${aws_vpc.test.id}"
}

resource "aws_route_table" "test" {
  vpc_id = "${aws_vpc.test.id}"
  tags {
    Name = "Private Route Table"
  }
}

resource "aws_route_table_association" "a" {
  route_table_id = "${aws_route_table.test.id}"
  subnet_id = "${aws_subnet.test.id}"
}

data "aws_route_table" "RTB" {
  depends_on = ["aws_route_table_association.a"]
  tags = {
    Name = "Private Route Table"
  }
}
```

### Debug Output
https://gist.github.com/grubernaut/8343042b560fd88a1f08c247c5d499d7

### Expected Behavior
The data resource be ordered after the `aws_route_table` and `aws_route_table_association` resources

### Actual Behavior
The data resource was ordered before the route table resources, causing an error. 

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

### Important Factoids
Reason the acceptance test `TestAccDataSourceAwsRouteTable` is failing. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Discovered via hashicorp/terraform#11134

**Comment by jbardin** [comment]
Thanks @radeksimko, not sure how this issue laid around open for so long.
The only problem here is that you can't use `depends_on` in a data source.

**Comment by grubernaut** [comment]
![](https://i.kym-cdn.com/entries/icons/original/000/022/978/yNlQWRM.jpg)

**Comment by jbardin** [comment]
@grubernaut, #17034 is a good reference, and will likely be the the solution to allow them.

**Comment by grubernaut** [comment]
most excellent, thanks! :smile:
