### ISSUE TITLE
Update snap version

### ISSUE THREAD

**Issue by matejp** [hashicorp/terraform#23606]
I would love to see an updated snap of terraform: https://snapcraft.io/terraform
Looks like it was last updated on 14th of January 2019.

If I can help you in any way let me know.

$> terraform version
Terraform v0.11.11

Your version of Terraform is out of date! The latest version
is 0.12.17. You can update by downloading from www.terraform.io/downloads.html

**Comment by jbardin** [comment]
Hi @matejp,

Sorry, the snap package for Terraform is not maintained by us. You would need to contact the developer that maintains those packages. We recommend installing from the official source so that you can get the most timely updates.

Thanks!
