### ISSUE TITLE
Support for module count

### ISSUE THREAD

**Issue by sasq31** [hashicorp/terraform#23608]
After looking around previously raised issues I found https://github.com/hashicorp/terraform/issues/953. I was wondering if module count has made itself onto your roadmap anytime soon ?

I have a use case where passing a count to a module would reduce the amount of supporting code I have to write and make it much easier for others to understand.

**Comment by teamterraform** [comment]
Yes, this is a feature under consideration and is an open issue. Please 👍 the existing issue as that  helps with prioritization, more issues and comments create noise for maintainers. Thank you! We know this is highly requested.
