### ISSUE TITLE
Destroy should accept execution plan file.

### ISSUE THREAD

**Issue by tamsky** [hashicorp/terraform#2361]
This error should go away:
https://github.com/hashicorp/terraform/blob/v0.5.3/command/apply.go#L106

and, instead, be replaced with the ability to provide a plan file.

**Comment by catsby** [comment]
Interesting idea. Normally this is accomplished by creating an execution plan with the `-destroy` flag, and using the `apply` command. I feel that makes the most sense; you're still applying a plan, it just happens to be destructive. 

Do you feel we need to support both options? What advantages do you think using the `destroy` command here gives us, over applying a destructive plan?

**Comment by tamsky** [comment]
If there were examples in the documentation directing folks to the "normally this is accomplished" method, that would be great, but I haven't come across any.**

https://www.terraform.io/docs/commands/destroy.html has:
`Usage: terraform destroy [options] [dir]`

https://www.terraform.io/docs/commands/apply.html has:
`Usage: terraform apply [options] [dir]`

Now, imagine the unsuspecting user simply reading the existing documentation... 
    `apply` accepts a plan file where `[dir]` appears
    `destroy` has the same argument list as `apply`, but does not accept a plan file.


Either there should be a distinction between the two `Usage: ... [dir]` arguments in how they are labelled, such as `[dir-or-planfile]`, or they should both accept the same types of arguments.

[**] at a minimum, I'd expect an example at: https://www.terraform.io/intro/getting-started/destroy.html

**Comment by phinze** [comment]
Hi @tamsky. Agreed that the docs could use some clarification here. I'm curious though, what would you expect to happen when you specified a plan file as an argument to `terraform destroy`?

**Comment by mitchellh** [comment]
Closing due to lack of response, but updating the docs now to clarify that the way this is accomplished is `plan -destroy` followed by `apply`!

**Comment by tamsky** [comment]
Apologies for the lack of response.
I think I figured out `plan -destroy` soon after filing this... 

But looking again now at the getting-started docs:
     https://www.terraform.io/intro/getting-started/destroy.html
this page still only describes `plan -destroy` but doesn't mention the utility of it.

A safer, more complete, example might be `plan -destroy -out saved-plan` followed by  `apply saved-plan`.

**Comment by mitchellh** [comment]
I agree @tamsky! I'm adding that now, just dealing with some build issues. :)

**Comment by ozbillwang** [comment]
but currently in the docs, 

https://www.terraform.io/docs/commands/destroy.html
>This command accepts all the arguments and flags that the apply command accepts, with the `exception of a plan file argument`.

So should we use `terraform plan -destroy` to generate the plan file and feed to `terraform destroy` later?

What's the differences in plan file with `-destroy` or without `-destroy` when `terraform plan`?

**Comment by tamsky** [comment]
A long time ago @phinze asked:
> what would you expect to happen when you specified a plan file as an argument to terraform destroy?

Knowing what I know now, I understand what was missing from my mental model when I opened this issue 3 years ago:

A `plan output file` contains a graph of actions to perform.
To me, now, it doesn't make sense to use a graph of "actions" as input to a process that destroys (all/some) resources, since the "actions" in the `plan output file` may not be limited to only destroy/delete actions -- it might have actions that create resources... which doesn't make sense in the context of `destroy`.

@ozbillwang asked recently:
> What's the differences in plan file with -destroy or without -destroy when terraform plan?

Maybe @mitchellh can offer a better explanation, but my understanding of the contents of the "plan file" resulting from:
- `plan -destroy`: is the "plan file" will contain an ordered set of actions needed to remove all resources that exist in your local/current `tfstate`.
- `plan` (without `-destroy`): the "plan file" will contain an ordered set of actions that will transform the current real-world state into the state defined by the current terraform config (the union of all `*.tf` and `*.tf.json` files in the current directory)

**Comment by next-jesusmanuelnavarro** [comment]
"Terraform plan plus apply" has another interesting side effect that hasn't been considered here: it also **blocks** applying a plan if infrastructure has been updated in the meantime.

Without the ability to pass a plan to a destroy operation, you enterily miss this safeward.

1. `terraform plan -destroy -out=planfile`
1. You review the plan and confirm what's planned for destruction is what you meant to be destroyed.
    (...but, in the meantime, somebody updates the infrastructure)
1. `terraform destroy` **but now you are not destroying what you planned to destroy!!!**

On top of that, it is not as if `terraform apply planfile` doesn't also destroy some resources when the plan mandates it, so having to destroy all of them is nothing but a corner case.

**In brief:**
1. the semantics of `terraform apply plan` are obvious, even if the plan is to destroy everything (and you **know** that's exactly what will happen, since that's why you issued a plan and reviewed it, right?).
1. missing the ability to pass a destroying plan to `terraform apply` endangers the infrastructure.

So, please consider reopening this feature request.
