### ISSUE TITLE
Deleting two resources via apply does not respect dependencies

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#2363]
provider google {
        account_file = "../service_account_key.json"
        project = "abiding-truth-649"
        region = "us-central1"
    }
    resource "google_compute_disk" "test" {
        name = "test"
        zone = "us-central1-f"
        size = 20
    }
    resource "google_compute_instance" "test" {
        name = "test"
        machine_type = "f1-micro"
        zone = "us-central1-f"
        disk {
            disk = "${google_compute_disk.test.name}"
        }
        network_interface {
            network = "default"
        }
    }

Apply this, then comment out the resources and apply again:

* Error deleting disk: googleapi: Error 400: The disk resource 'test' is already being used by 'test', resourceInUseByAnotherResource

Using the destroy command does work, but you have to uncomment the resources first.

The dependencies are stored in the tfstate so it should be possible to clean up the resources in the right order.

**Comment by mitchellh** [comment]
This is certainly a regression. This used to function properly. I'm taking a look.

**Comment by mitchellh** [comment]
Got a fix in the linked PR.

**Comment by sparkprime** [comment]
Thanks, I confirmed the fix.
