### ISSUE TITLE
Naming scheme not consistent between count=1 and count=2

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2364]
When creating a resource (e.g. aws_instance) foo without a count, it rightly gets created as:
aws_instance.foo

When creating a resource with a count=2, they get created as:
aws_instance.foo.0  aws_instance.foo.1

However there is no way to create a single resource (when specifying count=1)
aws_instance.foo.0

Unfortunately this means when I scale back from say 3 nodes to 1 node, I have to refactor a whole bunch of code such as anything that references aws_instance.foo.*.property, which no longer works.

It would be better for this to be consistent so I can seamlessly move from 1 node to 3 nodes and back without having to alter other code.

**Comment by phinze** [comment]
Thanks for the report. Tagging as a bug - I believe my work on supporting empty and single-element lists will help clear up this use case, so state tuned!

**Comment by mitchellh** [comment]
Hm, the splat operator is supposed to work with even single nodes. I can take a look at this as well.

**Comment by mitchellh** [comment]
I just tried this and this functioned properly. I even just pushed a test for it. Can you give us code to repro this?
