### ISSUE TITLE
Error waiting for Volume to become available: InvalidVolume.NotFound: The volume does not exist

### ISSUE THREAD

**Issue by kumarannamreddi** [hashicorp/terraform#23651]
Hi,
   I am trying to encrypt the EBS volume with KMS key but getting an error as follows.
Error: Error waiting for Volume (vol-03129ecc35d70c14b) to become available:
InvalidVolume.NotFound: The volume 'vol-03129ecc35d70c14b' does not exist.
        status code: 400, request id: c25be80e-c84d-4e0b-a96f-bfdcd9068408

The volumes are being created successfully if not using KMS. My template looks as follows
provider "aws" {
        region          =       "us-east-1"
}

data "aws_ami" "GoldenDB" {
  most_recent           =       true
  owners                =       ["${var.tag_owners}"]

  filter {
    name   = "tag:CR_NAME"
    values = ["${var.tag_name}"]
        }
}

data "aws_kms_key" "GoldenDB" {
        key_id  =       "${var.tag_kms}"
}

resource "aws_instance" "GoldenDB" {
        ami                     =       "${data.aws_ami.GoldenDB.id}"
        instance_type           =       "${var.type}"
        subnet_id               =       "${var.subnet_id}"
        vpc_security_group_ids  =       "${var.security_groups}"
        key_name                =       "${var.key_name}"
        iam_instance_profile    =       "${var.policy}"
        ebs_optimized           =       "${var.tag_term}"
}
resource "aws_ebs_volume" "vol1-GoldenDB" {
        availability_zone       =       "us-east-1a"
        encrypted               =       true
        kms_key_id              =       "${data.aws_kms_key.GoldenDB.arn}"
        size                    =       "${var.tag_size}"
        type                    =       "${var.tag_type}"
}

resource "aws_volume_attachment" "vol1-GoldenDB-attachment" {
        device_name             =       "/dev/xvdi"
        volume_id               =       "${aws_ebs_volume.vol1-Golden}"
        instance_id             =       "${aws_instance.GoldenDB.id}"
}

Any help is appreciated

**Comment by royoan** [comment]
Hello, can you help me? There was a same error when create a encrypt EBS volume.

**Comment by annamreddi03** [comment]
Is it the same error?
