### ISSUE TITLE
Confusing error message if parameters are in wrong order

### ISSUE THREAD

**Issue by kevingimbel** [hashicorp/terraform#23654]
### Terraform Version

```
Terraform v0.12.16
+ provider.aws v2.41.0
```

### Terraform Configuration Files

```hcl
module "test_service" {
  [...]
  volumes = [
    {
      name                        = "var_lib_docker"
      host_path                   = "/var/lib/docker"
      docker_volume_configuration = []
    },
    {
      name                        = "docker-sock"
      host_path                   = "/var/run/docker.sock"
      docker_volume_configuration = []
    }
  ]

    [...]
}
```

### Debug Output
```
Error: Invalid value for module argument

  on main.tf line 17, in module "test_service":
  17:   volumes = [
  18:     {
  19:       name                        = "var_lib_docker"
  20:       host_path                   = "/var/lib/docker"
  21:       docker_volume_configuration = {}
  22:     },
  23:     {
  24:       name                        = "docker-sock"
  25:       host_path                   = "/var/run/docker.sock"
  26:       docker_volume_configuration = {}
  27:     }
  28:   ]

The given value is not suitable for child module variable "volumes" defined at
../ecs_service/variables.tf:91,1-19: element 0: attribute "host_path": string
required.
```

In `ecs_service` I defined the volume variable as follows:

```hcl
variable "volumes" {
  type = list(object({
    host_path = string
    name      = string
    docker_volume_configuration = list(object({
      autoprovision = bool
      driver        = string
      driver_opts   = map(string)
      labels        = map(string)
      scope         = string
    }))
  }))
  description = "Task volume definitions as list of configuration objects"
  default     = []
}
```
### Expected Behavior

The volumes should be used because all required fields are there.
### Actual Behavior

Terraform shows a "cryptic" error message:

```
The given value is not suitable for child module variable "volumes" defined at
../ecs_service/variables.tf:91,1-19: element 0: attribute "host_path": string
required.
```

What is actually meant by this is: The _order_ of the variables is wrong. I defined it as 

```hcl
variable "volumes" {
  type = list(object({
    host_path = string
    name      = string
[...]
```

but in my main.tf file I used

```hcl
[...]
  volumes = [
    {
      name                        = "var_lib_docker"
      host_path                   = "/var/lib/docker"
      docker_volume_configuration = []
    }
]
```

So because `name` comes before `host_path` terraform is unable to work with these values. I only tried to re-order (and fix!) the variables in my main.tf because it was the last thing I could think of.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment]
Hi @kevingimbel,

Thanks for filing the issue, but unfortunately I'm not able to reproduce this. The order of object fields should not matter in the configuration, as long as they are all assigned. 

Would it be possible to share a more complete configuration, or a minimal example that exhibits this behavior?

**Comment by kevingimbel** [comment]
Hello @jbardin, I'll try and prepare a minimal / reduced case from my files where it didn't work.

When I just tried to replicate it with a "null" resource it was working as expected (= the issue wasn't there).
Maybe the issue is within the AWS resource / provider and not with terraform itself.

**Comment by kevingimbel** [comment]
I can no longer replicate the issue, maybe there was something else wrong and the changing of the attribute order was just a coincidence. 

I'll close this issue.
