### ISSUE TITLE
Changing AWS instance type

### ISSUE THREAD

**Issue by tubaguy50035** [hashicorp/terraform#2365]
So I have an instance like this:
![screen shot 2015-06-16 at 8 52 00 am](https://cloud.githubusercontent.com/assets/1617620/8184641/2782c1a8-1405-11e5-90d7-4bfa457c96b2.png)

I changed the instance type from a c4.large to a c4.xlarge in the console, because terraform wanted to do a delete/create to change the type.  I then changed my terraform configuration to c4.xlarge.

![screen shot 2015-06-16 at 8 54 35 am](https://cloud.githubusercontent.com/assets/1617620/8184679/5dcc35c8-1405-11e5-8369-5c9b7dd4901b.png)

When I run terraform plan, it says that it's refreshing the state prior to the plan.  But then it doesn't see that the type has already been changed outside terraform and thus wants me to delete/create the instance:
![screen shot 2015-06-16 at 8 56 03 am](https://cloud.githubusercontent.com/assets/1617620/8184722/9167c0dc-1405-11e5-82e1-6ec93e4d3e4e.png)

Is this the expected behavior?

**Comment by phinze** [comment]
Ah yes - we should detect this as "drift" of the instance_type param. Tagged as a bug and pushing a fix now.

**Comment by tubaguy50035** [comment]
Awesome @phinze.  You guys are closing these bugs so fast!

**Comment by CpuID** [comment]
@phinze not sure if this is actually fixed...? Just had it happen in 0.6.0

**Comment by CpuID** [comment]
@phinze ignore me, just noticed the .tf file was out of date, so it was trying to make a legitimate change. false alarm.
