### ISSUE TITLE
etcdv3 data terrafrom_remote_state fails with "user name is empty"

### ISSUE THREAD

**Issue by mchristensen76** [hashicorp/terraform#23664]
### Terraform Version

```
Terraform v0.12.18
```

### Terraform Configuration Files

```hcl
terraform {
  backend "etcdv3" {
    endpoints = ["my_endpoint"]
    lock      = true
    prefix    = "terraform.tfstate/"
  }
}


data "terraform_remote_state" "vpc" {
  backend = "etcdv3"
  config = {
    endpoints = ["my_endpoint"]
    prefix    = "terraform.tfstate/"
    lock      = true
  }
}


Partional config file entries:
username = "my_user"
password = "my_password"
```

### Expected Behavior

Running `terraform plan` should have been successful.

### Actual Behavior

Terraform errored out saying the user name was empty.  If I add the username and password it works.  But I don't have the username and password in the terraform block where I set the backend, that's correctly using the partial config file.  It appears that the data terraform_remote_state is not using the partial config file when calling terraform plan.

```
Error: Error loading state error

  on main.tf line 25, in data "terraform_remote_state" "vpc":
  25:   backend = "etcdv3"

error loading the remote state: Failed to lock state in etcd: etcdserver: user
name is empty.
```

**Comment by jbardin** [comment]
Hi @mchristensen76,

This is the expected behavior for the remote state resource. The `terraform_remote_state` resource is entirely separate from the `backend`, and they do not share any configuration. Any required values for that resource will have to be in the config file itself, or passed in through variables.
