### ISSUE TITLE
Error - templatefile function when trying to escape ${ when it's inside an if statement

### ISSUE THREAD

**Issue by mlcooper** [hashicorp/terraform#23674]
### Terraform Version

```
Terraform v0.12.18
+ provider.aws v2.42.0
```

### Terraform Configuration Files

I am using the `templatefile` function for the `user_data` section inside of an `aws_launch_template` resource.  Here is the `user_data` section inside the `aws_launch_template`:
```
  user_data = base64encode(templatefile("${path.module}/files/userdata.sh", {
    AWSREGION                = var.aws_region
    }
  ))
```
Here is my bogus template which reproduces this issue:
```
#!/bin/bash

declare -a my_array=(item1 item2 item3)
if [ ${#my_array[@]} -gt 0 ]; then
  for i in ${my_array[@]}; do 
    echo "$i" 
  done
fi

echo "AWS Region: ${ AWSREGION }"
```

### Error Output

```
-----------------------------------------------------
  50:   user_data = base64encode(templatefile("${path.module}/files/userdata.sh", {
  51:
  52:
  53:
  54:
  55:
  56:
  57:
  58:
  59:
  60:
  61:
    |----------------
    | path.module is "modules/indexers"

Call to function "templatefile" failed:
modules/indexers/files/userdata.sh:5,12-13: Invalid character; This character
is not used within the language., and 3 other diagnostic(s).
```
### Expected Behavior

I would expect this template to be okay provided I escaped `${my_array[@]}` on line 5, like so:
```
#!/bin/bash

declare -a my_array=(item1 item2 item3)
if [ ${#my_array[@]} -gt 0 ]; then
  for i in $${my_array[@]}; do 
  	echo "$i" 
  done
fi

echo "AWS Region: ${ AWSREGION }"
```

### Actual Behavior

What actually happened when I escaped that on line 5 as shown above was this:
```
Error: Error in function call

  on modules/indexers/main.tf line 50, in resource "aws_launch_template" "indexers":
  50:   user_data = base64encode(templatefile("${path.module}/files/userdata.sh", {
  51:
  52:
  53:
  54:
  **55:**
  56:
  57:
  58:
  59:
  60:
  61:
    |----------------
    | path.module is "modules/indexers"

Call to function "templatefile" failed:
modules/indexers/files/userdata.sh:5,12-13: Invalid character; This character
is not used within the language., and 4 other diagnostic(s).
```
### Steps to Reproduce

Write a template that has bash programming syntax such as `${my_array[@]}` and put it **inside** an `if` statement that has syntax such as `if [ ${#my_array[@]} -gt 0 ]; then`.  When it is _inside_ an `if` statement, the escapement of `${` with `$${` is not recognized by Terraform.  When I removed my `if` statement from the code, and escaped it with `$${`, Terraform did not produce any errors.

**Comment by mlcooper** [comment]
I wound up using the data resource `template_cloudinit_config` to pass in my shell script as `content_type = "text/x-shellscript"` with the `content` coming from a `file`.  This way there was no interpolation done by TF and nothing had to be escaped.

**Comment by n3ph** [comment]
See #17899

**Comment by n3ph** [comment]
You need to properly escape the variables not to be interpolated by Terraform..

**Comment by n3ph** [comment]
```sh
#!/bin/bash

declare -a my_array=(item1 item2 item3)
if [ $${#my_array[@]} -gt 0 ]; then
  for i in $${my_array[@]}; do 
    echo "$$i" 
  done
fi

echo "AWS Region: ${ AWSREGION }"
```
