### ISSUE TITLE
Dynamic blocks on keys with `.` fail

### ISSUE THREAD

**Issue by slevenick** [hashicorp/terraform#23672]
### Terraform Version

```
Terraform v0.12.16
+ provider.google v2.20.0
```

### Terraform Configuration Files

```hcl
variable "api_names" {
  type = list(string)
  default = [
    "appengine.googleapis.com",
    "bigquerystorage.googleapis.com",
  ]
}

resource "google_project_service" "enabled_apis" {
  for_each = toset(var.api_names)
  service = each.key
}
```

### Debug Output

        Error: State format upgrade failed: Error upgrading state file format from version 3 to version 4: invalid internal resource address format: google_project_service.enabled_apis.["appengine.googleapis.com"].

### Expected Behavior

Terraform should not have errored

### Actual Behavior

Terraform errored with `invalid internal resource address format`

### Steps to Reproduce

`terraform init`
`terraform apply`

### Additional Context

This looks to be caused by the combination of `for_each` blocks that use keys with periods in them. This line splits on the `.` character: https://github.com/hashicorp/terraform/blob/2f36a82091cf7e513e1f5510b6b0e4bab30b4ac9/terraform/resource_address.go#L180

But the `.` character can be in the name in quotes, causing the split to incorrectly return with more than 4 parts, causing an error. The split should only happen on the part of the identifier outside of the brackets (or something like that)

**Comment by jbardin** [comment]
Hi @slevenick,

Can you provide some more details on how you are producing this error?
The `for_each` keys should work correctly with valid strings, regardless of the presence of a `.`. 

The unusual part here is the `Error upgrading state file format from version 3 to version 4:` message. Terraform v0.12.16 and has only used version 4, which is the version required for the `for_each` feature as well.

**Comment by slevenick** [comment]
I must have had conflicting versions, can no longer reproduce.
