### ISSUE TITLE
Terraform plan modifies state

### ISSUE THREAD

**Issue by dploeger** [hashicorp/terraform#23683]
We recently updated the kubernetes provider from 1.6.2 to the most current version 1.10.0 and used `terraform plan` to check potential changes.

The documentation states about `terraform plan`:

> This command is a convenient way to check whether the execution plan for a set of changes matches your expectations *without making any changes to real resources or to the state*

However, after we ran the command and didn't migrate to the current version, the state wasn't readable using the old version of the provider anymore as it seems that the structural changes in the provider had been carried out to the state, because now `terraform plan` shows errors like these:

```
Error: unsupported attribute "external_traffic_policy"
Error: unsupported attribute "affinity"
```

### Terraform Version
```
Terraform v0.12.18
+ provider.azurerm v1.35.0
+ provider.kubernetes v1.10.0
```

### Terraform Configuration Files

```hcl
provider "kubernetes" {
  version                = "~> 1.10.0"
  host                   = module.azurekubernetes.host
  client_certificate     = base64decode(module.azurekubernetes.client_certificate)
  client_key             = base64decode(module.azurekubernetes.client_key)
  cluster_ca_certificate = base64decode(module.azurekubernetes.cluster_ca_certificate)
}
```

### Expected Behavior
The state wouldn't be updated and the old version works as before.

### Actual Behavior
We were forced to migrate to the new version to have Terraform working again.

### Steps to Reproduce
1. Install Kubernetes provider version 1.6.2
2. Deploy Kubernetes resources like `kubernetes_service` to an infrastructure
3. Change Version requirement for Kubernetes provider to 1.10.0
4. Run `terraform plan`
5. Change version requirement for Kubernetes provider to 1.6.2 again
6. Run `terraform plan`

**Comment by danieldreier** [comment]
Thanks for reporting this, @dploeger. I've linked this from meta-issue https://github.com/hashicorp/terraform/issues/23697 - there are a variety of use cases where state is upgraded contrary to people's expectations and this is a good use case to capture as part of that.

**Comment by jbardin** [comment]
Hi @dploeger,

Can you verify that neither a `refresh` or `apply` was executed with the new provider? Even if the `apply` had no changes, it would cause the refreshed state to be written out to storage. 

The refreshed state used internally no the plan should only be used to render the plan and not be saved. I attempted a number of permutations of provider changes, and no new state files were written without a `refresh` or `apply`.

**Comment by dploeger** [comment]
Phew. I wouldn't swear to it, but I'm pretty sure, there only was a `plan` and no `refresh` or `apply`.

**Comment by jbardin** [comment]
Thanks @dploeger,

In that case I'm going to close this out for now. We can re-open it if we find a reproduction case, but I'm not seeing any way for new attributes to be written from a plan alone.
