### ISSUE TITLE
azure rm storage with queue_properties  causes crash

### ISSUE THREAD

**Issue by chrisvugrinec** [hashicorp/terraform#23707]
I have an Azure subscription and I use terraform to roll out my Azure infra with the azurerm provider,
Tested with the following Terraform versions
  ▸ 0.12.18 *recent
    0.12.17
↓   0.12.16

within one of my modules I have a storage.tf, containing the following:

```
resource "azurerm_resource_group" "storage-rg" {
  name     = var.rg
  location = var.location
}

resource "azurerm_storage_account" "storage-acc" {
  name                     = lower(replace("${var.team-name}-${random_string.random-namespace.result}-sa","-",""))
  resource_group_name      = azurerm_resource_group.storage-rg.name
  location                 = azurerm_resource_group.storage-rg.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = var.tags
  queue_properties{}
 
}

resource "azurerm_storage_container" "pics" {
  name                  = "pics"
  storage_account_name  = azurerm_storage_account.storage-acc.name
  container_access_type = "container"
}
```
The queue properties I was playing with in order to get the CORS setting running...did not manage to get that working either ...but that is another issue. The issue here is that the empty queue_properties block causes terraform to crash...see message below:

some last lines of my crash.log

2019/12/17 16:28:30 [TRACE] module.kpd-team1: eval: *terraform.EvalWriteState
2019/12/17 16:28:30 [ERROR] module.kpd-team1: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/12/17 16:28:30 [TRACE] EvalWriteState: removing state object for module.kpd-team1.azurerm_storage_account.storage-acc
2019/12/17 16:28:30 [TRACE] module.kpd-team1: eval: *terraform.EvalIf
2019/12/17 16:28:30 [TRACE] [walkApply] Exiting eval tree: module.kpd-team1.azurerm_key_vault.devops-kv
2019/12/17 16:28:30 [TRACE] vertex "module.kpd-team1.azurerm_key_vault.devops-kv": visit complete
2019/12/17 16:28:30 [TRACE] module.kpd-team1: eval: *terraform.EvalIf
2019/12/17 16:28:30 [TRACE] module.kpd-team1: eval: *terraform.EvalWriteDiff
2019/12/17 16:28:30 [TRACE] module.kpd-team1: eval: *terraform.EvalApplyPost
2019/12/17 16:28:30 [ERROR] module.kpd-team1: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2019/12/17 16:28:30 [ERROR] module.kpd-team1: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/12/17 16:28:30 [TRACE] [walkApply] Exiting eval tree: module.kpd-team1.azurerm_storage_account.storage-acc
2019/12/17 16:28:30 [TRACE] vertex "module.kpd-team1.azurerm_storage_account.storage-acc": visit complete
2019/12/17 16:28:30 [TRACE] dag/walk: upstream of "module.kpd-team1.azurerm_storage_container.pics" errored, so skipping
2019/12/17 16:28:30 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/12/17 16:28:30 [TRACE] dag/walk: upstream of "provider.azurerm (close)" errored, so skipping
2019/12/17 16:28:30 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019/12/17 16:28:30 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2019/12/17 16:28:30 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 15
2019/12/17 16:28:30 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2019/12/17 16:28:30 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/12/17 16:28:30 [TRACE] statemgr.Filesystem: unlocking te

### Terraform Version

```
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by teamterraform** [comment]
Hi @chrisvugrinec,

This appears to be a crash within the azurerm provider. 
In order for the provider maintainers to diagnose the issue, they are going to need the full crash output, including the traceback showing where the error occurred. Please open a new issue in the azurerm provider repo, and include the requested information for debugging.

Thanks!
