### ISSUE TITLE
Using a map variable declared in version 0.12 variable file not recognized

### ISSUE THREAD

**Issue by ajaybhatnagar** [hashicorp/terraform#23728]
### Terraform Version

```
Terraform v0.12.18
+ provider.azurerm (unversioned)
+ provider.template (unversioned)
```

### Terraform Configuration Files

```hcl
**Variable used as below  in main.tf file**

 #vm_size                       = "${var.vm_size}"
variable "es_vm_name" {
  description = "ELK node name"
  type        = list(string)
}
variable "vm_size" {
  default = "Basic_A0"
}
vm_size = element(
    split("-", var.node_settings[element(var.es_vm_name, count.index)]),
    1,
  )


**Variable defined as below  in file terraform.tfvars**

#Name of the VM
es_vm_name = ["esm01","esm02","esm03","esd01","esd02","esd03"]

# Node Settings
variable "node_settings" {
   description = " Test"
   type = "map"
   default = {
     esm01 = "70-Standard_DS3_v2"
     esm02 = "70-Standard_DS3_v2"
     esm03 = "70-Standard_DS3_v2"
     esd01 = "80-Standard_DS4_v2"
     esd02 = "80-Standard_DS4_v2"
     esd03 = "80-Standard_DS4_v2"
      }
}

Files in the directory
-rwxrwx--- 1 ab ab 4481 May  6  2019 cloud-init.txt
-rwxrwx--- 1 ab ab 7194 Dec 19 12:14 main.tf
-rwxrwx--- 1 ab ab 3376 Dec 19 12:24 terraform.tfvars
-rw-r--r-- 1 ab ab   46 Dec 19 12:14 versions.tf

```

### Crash Output

$ terraform plan
2019/12/19 12:39:45 [INFO] Terraform version: 0.12.18  
2019/12/19 12:39:45 [INFO] Go runtime version: go1.12.13
2019/12/19 12:39:45 [INFO] CLI args: []string{"/usr/bin/terraform", "plan"}
2019/12/19 12:39:45 [DEBUG] Attempting to open CLI config file: /home/ab/.terraformrc
2019/12/19 12:39:45 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/12/19 12:39:45 [INFO] CLI command args: []string{"plan"}
2019/12/19 12:39:45 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2019/12/19 12:39:45 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2019/12/19 12:39:45 [DEBUG] New state was assigned lineage "232d49ee-c2a8-5eba-e407-7c4b91259418"
2019/12/19 12:39:45 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2019/12/19 12:39:45 [TRACE] Meta.Backend: instantiated backend of type <nil>
2019/12/19 12:39:45 [DEBUG] checking for provider in "."
2019/12/19 12:39:45 [DEBUG] checking for provider in "/usr/bin"
2019/12/19 12:39:45 [WARN] found legacy provider "terraform-provider-azurerm"
2019/12/19 12:39:45 [WARN] found legacy provider "terraform-provider-template"
2019/12/19 12:39:45 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/12/19 12:39:45 [DEBUG] found valid plugin: "azurerm", "0.0.0", "/usr/bin/terraform-provider-azurerm"
2019/12/19 12:39:45 [DEBUG] found valid plugin: "template", "0.0.0", "/usr/bin/terraform-provider-template"
2019/12/19 12:39:45 [DEBUG] checking for provisioner in "."
2019/12/19 12:39:45 [DEBUG] checking for provisioner in "/usr/bin"
2019/12/19 12:39:45 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2019/12/19 12:39:45 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend

Error: Variable declaration in .tfvars file

  on terraform.tfvars line 35:
  35: variable "node_settings" {

A .tfvars file is used to assign values to variables that have already been
declared in .tf files, not to declare new variables. To declare variable
"node_settings", place this block in one of your .tf files, such as
variables.tf.

To set a value for this variable in terraform.tfvars, use the definition
syntax instead:
    node_settings = <value>

### Expected Behavior

It should have created a plan output using the  map variables defined in the variables file.
 
### Actual Behavior

only map variable definition not recognized
Error: Variable declaration in .tfvars file
  on terraform.tfvars line 35:
  35: variable "node_settings" {

### Steps to Reproduce

Take a working configuration with a map variable from version 0.11.
1. terraform 0.12upgrade 
2. terraform init 
3. terraform plan.

### Additional Context

The files were working in version 0.11 and terraform upgrade has been done on these files.

**Comment by teamterraform** [comment]
Hi @ajaybhatnagar,

The syntax you have here is not supported in terraform 0.12. The variable declaration needs to be moved to a `.tf` file, as instructed in the error output:

```
A .tfvars file is used to assign values to variables that have already been
declared in .tf files, not to declare new variables. To declare variable
"node_settings", place this block in one of your .tf files, such as
variables.tf.
```

**Comment by ajaybhatnagar** [comment]
It is in  terraform.tf file.
Thanks
Ajay
