### ISSUE TITLE
AWS RDS Aurora Global Cluster support for MySQL 5.7 (Aurora 2.x)

### ISSUE THREAD

**Issue by prateekjaipuria** [hashicorp/terraform#23752]
aws_rds_global_cluster resource currently works only for MySQL 5.6 version.

There is also a note about this on the docs.
https://www.terraform.io/docs/providers/aws/r/rds_global_cluster.html
NOTE: RDS only supports the aurora engine (MySQL 5.6 compatible) for Global Clusters at this time.

AWS has already opened up support for global databases for Aurora MySQL 5.7
https://aws.amazon.com/about-aws/whats-new/2019/11/aurora-global-database-is-now-supported-amazon-aurora-mysql-57/

Please add the corresponding support in the aws provider. This is currently a blocking issue.

**Comment by jacobbednarz** [comment]
@prateekjaipuria This probably belongs in https://github.com/terraform-providers/terraform-provider-aws, not the core repository.
