### ISSUE TITLE
Bug with map variables in .auto.tfvars.json files not working only if in submodules.

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform#23765]
### Terraform Version

```
MacBook-Pro-3:terraform-must-fail-with-local-exec user$ /Users/user/Downloads/terraform --version
Terraform v0.12.18
+ provider.null v2.1.2
```

### Terraform Configuration Files

main.tf
```
module "testmap" {
    source                         = "./modules/testmap" 
}
```

modules/testmap/main.tf
```
variable "openvpn_v2_7_5" {
  type = map(string)
  default = {"":""}
}

resource "null_resource" "provision_1" {
  provisioner "local-exec" {
    command = <<EOT
      set -x
      echo "${lookup(var.openvpn_v2_7_5, "us-east-2")}"
EOT
  }
}
```

modules/testmap/ami_openvpn_v2_7_5.auto.tfvars.json
```
{
    "openvpn_v2_7_5": {
        "eu-north-1":"ami-039e147d",
        "ap-south-1":"ami-00b7bb451c0c20931",
        "eu-west-3":"ami-046a4e41b1e9b05de",
        "eu-west-2":"ami-0d8328d4870bdb740",
        "eu-west-1":"ami-0cb4952aadb21a730",
        "ap-northeast-2":"ami-0ee35e6d85611600d",
        "ap-northeast-1":"ami-0fb7d2efacd90133b",
        "sa-east-1":"ami-01ed0cb648aab86b9",
        "ca-central-1":"ami-027ea0cc4e34dbf65",
        "ap-southeast-1":"ami-086b2468bd6cf03ae",
        "ap-southeast-2":"ami-0d8ba0e9e6b6d18b7",
        "eu-central-1":"ami-01a95ada398994de8",
        "us-east-1":"ami-0ca1c6f31c3fb1708",
        "us-east-2":"ami-06b7ca1fe6197b6ff",
        "us-west-1":"ami-0f2426a96b5ca8a0c",
        "us-west-2":"ami-034692da3c6768a18"
    }
}
```

### Crash Output

```
MacBook-Pro-3:terraform-must-fail-with-local-exec user$ /Users/user/Downloads/terraform apply --auto-approve
module.testmap.null_resource.provision_1: Creating...

Error: Error in function call: Call to function "lookup" failed: lookup failed to find 'us-east-2'.
```

### Expected Behavior
variables should be able to be defined in modules with the format .auto.tfvars.json
instead, it is only possible to get this to function if those files are located at the base path of all modules.  this makes it difficult to produce independent modules that contain things like ami data that should be released with each module.

### Actual Behavior
Terraform produces an error as if it doesn't read in the variable at all.
'Error: Error in function call: Call to function "lookup" failed: lookup failed to find 'us-east-2'.'

### Steps to Reproduce
Terraform apply

**Comment by teamterraform** [comment]
Hi @queglay,

Sorry you were tripped up by this. Terraform does not read the variable file at all, because module variables are only set via module inputs. The `terraform.tfvars` and `.auto.tfvars` files are only used in the root module.
