### ISSUE TITLE
Terraform tries to destroy certificates before remove it from google_compute_target_https_proxy

### ISSUE THREAD

**Issue by i2dcarrasco** [hashicorp/terraform#23767]
Hello,

To be honest, I'm not sure if this report goes here or is related to the provider. I've thought that is a terraform problem because is related with the apply order (maybe I'm wrong).

### Terraform Version
Terraform v0.12.18
+ provider.google v3.3.0
+ provider.google-beta v3.3.0
+ provider.kubernetes v1.9.0
+ provider.local v1.4.0
+ provider.template v2.1.2

I've just updated the Terraform and google providers version to check if maybe was already fixed.

### Terraform Configuration Files
```
// local.workspace["certificates"] is a list of domains
resource "google_compute_managed_ssl_certificate" "lb_certs" {
  provider = google-beta

  name = replace(each.value, ".", "-")
  for_each = toset(
    flatten([
      local.workspace["certificates"]
    ])
  )

  managed {
    domains = ["${each.value}."]
  }
}

resource "google_compute_target_https_proxy" "base_https_proxy" {
  name             = "base-https"
  url_map          = google_compute_url_map.base.self_link
  ssl_certificates = values(google_compute_managed_ssl_certificate.lb_certs).*.self_link
  depends_on = [google_compute_managed_ssl_certificate.lb_certs]
}

### Expected Behavior
Delete the certificates from the google_compute_target_https_proxy resource before try to destroy it.

### Actual Behavior
First tries to destroy the certificates and it fails because they are in use by the google_compute_target_https_proxy

### Steps to Reproduce
1. Create a list of domains in a variable (local.workspace["certificates"] in the example) and create the resources
2. Delete one of more domains from that list and just apply the changes with `terraform apply`

Maybe also can be reproduced without a list and just adding the certificates manually

### Additional info
I've tried to apply just the resource google_compute_target_https_proxy using this command line:
`terraform apply --target=google_compute_target_https_proxy.base_https_proxy`
but same behaviour. Finaly I had to remove the certificates from the load balancer manually and then apply.

Best regards.

**Comment by jbardin** [comment]
Hi @i2dcarrasco,

The order of operations you are seeing here is what is expected from the configuration shown. The `lb_certs` resource must be created before `base_https_proxy`, and it would also need to be destroyed before updating `base_https_proxy` to reflect the changes. 

If you want to have `base_https_proxy` updated before destroying `lb_certs`, you would need to set `create_before_destroy` on `lb_certs`. If the resource doesn't work with this set, please file an issue with the google provider.

Thanks!
