### ISSUE TITLE
Compact function does not work with conditional/indexed values

### ISSUE THREAD

**Issue by Clete2** [hashicorp/terraform#23761]
Hello, my apologies if this issue is not clear. Please ask me to clarify if it is not. I have a bit of a complicated example where `compact`, `count`, and `length` do not all play well together.

### Terraform Version

```
0.12.18
```

### Terraform Configuration Files

Example 1 (what I want to do, important bit is the last line with output):
```hcl
Module declaration:
module "sqs-backoff-sample" {
  source     = "./modules/sqs-exponential-backoff"
  name       = "clete-sqs-test-"
  kms_key_id = var.kms_key_id
  account    = var.account
  region     = var.region
  queue_definitions = [
    { maxReceiveCount : 2, delaySeconds : 0 },
    { maxReceiveCount : 4, delaySeconds : 5 },
    { maxReceiveCount : 6, delaySeconds : 15 },
    { maxReceiveCount : 8, delaySeconds : 60 }
  ]
}
------------------------------------------------------
Module code:
resource "aws_sqs_queue" "queue" {
  name = var.name

  delay_seconds              = var.queue_definitions[0].delaySeconds
  redrive_policy             = "{\"deadLetterTargetArn\":\"${aws_sqs_queue.queue-retry-1[0].arn}\",\"maxReceiveCount\":${var.queue_definitions[1].maxReceiveCount}}"
  visibility_timeout_seconds = var.visibility_timeout
  kms_master_key_id          = var.kms_key_id

  tags = var.tags
}

resource "aws_sqs_queue" "queue-retry-1" {
  count = length(var.queue_definitions) >= 2 ? 1 : 0
  name  = "${var.name}-retry-1"

  delay_seconds              = var.queue_definitions[1].delaySeconds
  redrive_policy             = length(var.queue_definitions) == 2 ? null : "{\"deadLetterTargetArn\":\"${aws_sqs_queue.queue-retry-2[0].arn}\",\"maxReceiveCount\":${var.queue_definitions[2].maxReceiveCount}}"
  visibility_timeout_seconds = var.visibility_timeout
  kms_master_key_id          = var.kms_key_id

  tags = var.tags
}

resource "aws_sqs_queue" "queue-retry-2" {
  count = length(var.queue_definitions) >= 3 ? 1 : 0
  name  = "${var.name}-retry-2"

  delay_seconds              = var.queue_definitions[2].delaySeconds
  redrive_policy             = length(var.queue_definitions) == 3 ? null : "{\"deadLetterTargetArn\":\"${aws_sqs_queue.queue-retry-3[0].arn}\",\"maxReceiveCount\":${var.queue_definitions[3].maxReceiveCount}}"
  visibility_timeout_seconds = var.visibility_timeout
  kms_master_key_id          = var.kms_key_id

  tags = var.tags
}

resource "aws_sqs_queue" "queue-retry-3" {
  count = length(var.queue_definitions) >= 4 ? 1 : 0
  name  = "${var.name}-retry-3"

  delay_seconds              = var.queue_definitions[3].delaySeconds
  redrive_policy             = length(var.queue_definitions) == 4 ? null : "{\"deadLetterTargetArn\":\"${aws_sqs_queue.queue-retry-4[0].arn}\",\"maxReceiveCount\":${var.queue_definitions[4].maxReceiveCount}}"
  visibility_timeout_seconds = var.visibility_timeout
  kms_master_key_id          = var.kms_key_id

  tags = var.tags
}

resource "aws_sqs_queue" "queue-retry-4" {
  count = length(var.queue_definitions) >= 5 ? 1 : 0
  name  = "${var.name}-retry-4"

  delay_seconds              = var.queue_definitions[4].delaySeconds
  visibility_timeout_seconds = var.visibility_timeout
  kms_master_key_id          = var.kms_key_id

  tags = var.tags
}
------------------------------------------------------
output "queue_arns" {
  description = "List of queue ARNs created by this module. Be sure to subscribe to all of them."
  value       = compact([aws_sqs_queue.queue.arn, aws_sqs_queue.queue-retry-1[0].arn, aws_sqs_queue.queue-retry-2[0].arn, aws_sqs_queue.queue-retry-3[0].arn, aws_sqs_queue.queue-retry-4[0].arn]) # Compact removes null values
}
```

Example 2:
```hcl
All above is same.
------------------------------------------------------
output "queue_arns" {
  description = "List of queue ARNs created by this module. Be sure to subscribe to all of them."
  value       = compact([aws_sqs_queue.queue.arn]) # Compact removes null values
}
```

Example 3:
```hcl
All above is same.
------------------------------------------------------
output "queue_arns" {
  description = "List of queue ARNs created by this module. Be sure to subscribe to all of them."
  value       = [aws_sqs_queue.queue.arn, aws_sqs_queue.queue-retry-1[0].arn, aws_sqs_queue.queue-retry-2[0].arn, aws_sqs_queue.queue-retry-3[0].arn, aws_sqs_queue.queue-retry-4[0].arn]
}
```

### Expected Behavior

Examples have 4 total queues: `queue`, `queue-retry-1`, `queue-retry-2`, `queue-retry-3`.

Note `queue-retry-4` does not get created because `length(var.queue_definitions) < 5`. That's crucial to this example.

I expect that Example 1 will output `["arn:aws:sqs:us-east-1:account_num:clete-sqs-test", "arn:aws:sqs:us-east-1:account_num:clete-sqs-test-retry-1", "arn:aws:sqs:us-east-1:account_num:clete-sqs-test-retry-2", "arn:aws:sqs:us-east-1:account_num:clete-sqs-test-retry-3"]` (but it outputs undefined)

Furthermore, I expect that the `length` function can be used on an output that uses the `compact` function, but I get an error:
```
Error: Invalid count argument

  on terraform/failure-lambda.tf line 19, in resource "aws_lambda_event_source_mapping" "read_from_queue":
  19:   count            = length(module.sqs-backoff-sample.queue_arns)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

### Actual Behavior

Example 1 will *not* have any output. The output `queue_arns` will be `undefined`.

Example 2 has an output like such: `["arn:aws:sqs:us-east-1:account_num:clete-sqs-test"]` (NOTE: This is good)

Example 3 has an output: `["arn:aws:sqs:us-east-1:account_num:clete-sqs-test", "arn:aws:sqs:us-east-1:account_num:clete-sqs-test-retry-1", "arn:aws:sqs:us-east-1:account_num:clete-sqs-test-retry-2", "arn:aws:sqs:us-east-1:account_num:clete-sqs-test-retry-3", null]` (NOTE: `null`)

The only example which deviates is Example 1. I have included the other 2 to show that the output does indeed work, but only if `compact` is not used on a resource that has `count` attribute defined.

### References

My example is the same example in this issue that I created last week:
- #23735

**Comment by jbardin** [comment]
Hi @Clete2,

I think you have a few confounding issues here that are making this harder to understand.The error you should immediately get is

        | aws_sqs_queue.queue-retry-4 is empty tuple

    The given key does not identify an element in this collection value

Since you're not creating any `aws_sqs_queue.queue-retry-4` resources, accessing a specific instance via `aws_sqs_queue.queue-retry-4[0].arn` should result in an error. I can only assume you also have `TF_WARN_OUTPUT_ERRORS`, which is suppressing the output error in this case.

Because there is actually an error evaluating the output value (and since this is continuing past an error, the behavior isn't really well-defined, which I think is where the `null` value is coming into play), an unknown value ends up passed to `length` which results in the error you are reporting.

Since there doesn't appear to be any specific bugs shown here, I would suggest starting a conversation in [the community forum](https://discuss.hashicorp.com/c/terraform-core), where other users may be available to offer advice and examples from similar situations.

**Comment by Clete2** [comment]
Hey @jbardin thanks for the reply.

I actually didn't get any errors like an empty element, and I didn't have `TF_WARN_OUTPUT_ERRORS` set either. I struggle with not being able to make dynamic things work in Terraform. I'm disappointed that loops and similar behavior are either not available in Terraform or infeasible.

As it stands, I learned that you cannot string SQS queues together to perform exponential backoff. It turns out that the `DelaySeconds` is only effective the first time you send the message into a queue, and does not apply for messages being moved from queue-to-queue. That being the case, I will close this issue, as I no longer need to do what I was trying to do.
