### ISSUE TITLE
Create Elasticache cluster does not support SnapshotArns 

### ISSUE THREAD

**Issue by jonhatalla** [hashicorp/terraform#2377]
Creating an elasticache redis cluster from terraform with data already loaded in it is an important feature for us.  The document of supported features says that creating an elasticache cluster is complete, however this is an unsupported feature.

This feature references an S3 redis dump file and creates the cluster with the preloaded data.
https://github.com/aws/aws-sdk-go/blob/master/service/elasticache/api.go#L2104

http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/ManagingCacheClusters.SeedingRedis.html

**Comment by nick-parry** [comment]
:+1:  This would make my life complete.

**Comment by catsby** [comment]
Sent a PR for this in #2634

**Comment by catsby** [comment]
@jonhatalla @nick-parry just merged #2634, let me know if you run into any issues
