### ISSUE TITLE
In Terraform 0.12, using resource count based on condition, if resource name already exists is resulting in deletion of resource for the 2nd terraform apply.

### ISSUE THREAD

**Issue by MalarvizhiK** [hashicorp/terraform#23772]
I am using Terraform version 0.12. I have a requirement to skip resource creation if resource with the same name already exists. 

I did the following for this :

Read the list of custom images,

```
data "ibm_is_images" "custom_images" {
}
```

Check if image already exists,

```
locals {
 custom_vsi_image = contains([for x in data.ibm_is_images.custom_images.images: "true" if x.visibility == "private" && x.name == var.vnf_vpc_image_name], "true")
}

output "abc" {
value="${local.custom_vsi_image}"
}
```

Create only if image exists is false.

```
resource "ibm_is_image" "custom_image" {
  count            = "${local.custom_vsi_image == true ? 0 : 1}"
  depends_on       = ["data.ibm_is_images.custom_images"]
  href             = "${local.image_url}"
  name             = "${var.vnf_vpc_image_name}"
  operating_system = "centos-7-amd64"

  timeouts {
    create = "30m"
    delete = "10m"
  }
}
```

This works fine for the first time with "terraform apply". It finds that the image did not exists, so it creates image.

When I run "terraform apply" for the second time. It is deleting the resource "custom_image" that is created above. Any idea why it is deleting the resource, when it is run for the 2nd time ?

Also, how to create a resource based on some condition(like only when it does not exists) ?

Please find attached logs for first time and second time terraform apply command. 

### Terraform Version
terraform -v
2020/01/02 13:42:25 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/01/02 13:42:25 [INFO] Terraform version: 0.12.18  
2020/01/02 13:42:25 [INFO] Go runtime version: go1.13.4
2020/01/02 13:42:25 [INFO] CLI args: []string{"/usr/local/bin/terraform", "-v"}
2020/01/02 13:42:25 [DEBUG] Attempting to open CLI config file: /Users/malark/.terraformrc
2020/01/02 13:42:25 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/01/02 13:42:25 [DEBUG] checking for credentials in "/Users/malark/.terraform.d/plugins"
2020/01/02 13:42:25 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.12.18
2020/01/02 13:42:25 [DEBUG] checking for provider in "."
2020/01/02 13:42:25 [DEBUG] checking for provider in "/usr/local/bin"
2020/01/02 13:42:25 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2020/01/02 13:42:25 [DEBUG] found provider "terraform-provider-external_v1.2.0_x4"
2020/01/02 13:42:25 [DEBUG] checking for provider in "/Users/malark/.terraform.d/plugins"
2020/01/02 13:42:25 [DEBUG] found provider "terraform-provider-ibm_v1.0.0"
2020/01/02 13:42:25 [DEBUG] found valid plugin: "external", "1.2.0", "/Users/malark/content/new/vnf-vpc-f5/.terraform/plugins/darwin_amd64/terraform-provider-external_v1.2.0_x4"
2020/01/02 13:42:25 [DEBUG] found valid plugin: "ibm", "1.0.0", "/Users/malark/.terraform.d/plugins/terraform-provider-ibm_v1.0.0"
+ provider.external v1.2.0
+ provider.ibm v1.0.0

```
...
```

### Expected Behavior
2nd time, terraform apply should have skipped resource creation instead of deletion. 
 
### Actual Behavior
2nd time, terraform apply deleted the resource.
 

### Steps to Reproduce
Please list of steps required to reproduce the issue, for example:
1.  create a resource based on condition like:

```
 resource "ibm_is_image" "custom_image" {
  count            = "${local.custom_vsi_image == true ? 0 : 1}"
  depends_on       = ["data.ibm_is_images.custom_images"]
  href             = "${local.image_url}"
  name             = "${var.vnf_vpc_image_name}"
  operating_system = "centos-7-amd64"

  timeouts {
    create = "30m"
    delete = "10m"
  }
}
```

2. Run `terraform apply` for 2 times.

### Additional Context

[terraform_1st_run.txt](https://github.com/hashicorp/terraform/files/4015259/terraform_1st_run.txt)
[terraform_2nd_run.txt](https://github.com/hashicorp/terraform/files/4015260/terraform_2nd_run.txt)

### References
https://stackoverflow.com/questions/59491608/in-terraform-0-12-how-to-skip-creation-of-resource-if-resource-name-already-ex?noredirect=1#comment105204361_59491608

**Comment by teamterraform** [comment]
Hi @MalarvizhiK,

It looks like you already got a good answer on StackOverflow. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
