### ISSUE TITLE
Destroy Provisioner throwing Cycle error on resources getting destroyed when running Terraform Apply

### ISSUE THREAD

**Issue by Divya1388** [hashicorp/terraform#23782]
I have a .tf file which creates a web app inside ASE ILB, add a custom name binding and do configurations on the Application Gateway (adding a backend pool, listener, rule for web app) using local provisioners. I also hav destroy provisioner which will delete the configurations on application gateway when we delete the web app. 
The configuration is as follows:
```
resource azurerm_app_service "app_service" {
  name                = var.app_service_name
  resource_group_name = var.resource_group_name
  location            = var.location
  app_service_plan_id = var.app_service_plan_id
}
resource azurerm_app_service_custom_hostname_binding "custom_name" {
  hostname            = "${azurerm_app_service.app_service.name}.internetbanking.us"
  app_service_name    = azurerm_app_service.app_service.name
  resource_group_name = var.resource_group_name
}
resource "null_resource" "configuration" {
  triggers = {
    app_service_id = azurerm_app_service.app_service.id
    custom_binding_id = azurerm_app_service_custom_hostname_binding.custom_name.id
  }
  provisioner "local-exec" {
    command = "az login --service-principal --username $ARM_SP_URL --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID --verbose"
  }
  provisioner "local-exec" {
    command = "az network application-gateway address-pool create -g ${var.resource_group_name} --gateway-name ${var.gateway_name} -n ${azurerm_app_service.app_service.name}-pool --servers ${azurerm_app_service.app_service.default_site_hostname} --verbose"
  }
  provisioner "local-exec" {
    command = "az network application-gateway http-listener create --frontend-port ${var.frontend_port} --gateway-name ${var.gateway_name} --name ${azurerm_app_service.app_service.name}-listener --resource-group ${var.resource_group_name} --host-name ${azurerm_app_service_custom_hostname_binding.custom_name.hostname} --verbose"
  }
  provisioner "local-exec" {
    command = "az network application-gateway rule create --gateway-name ${var.gateway_name} --name ${azurerm_app_service.app_service.name}-rule --resource-group ${var.resource_group_name} --address-pool ${azurerm_app_service.app_service.name}-pool --http-listener ${azurerm_app_service.app_service.name}-listener --http-settings ${var.http_setting } "
  }

}
resource "null_resource" "configuration_delete" {
  # triggers = {
  #   configuration = null_resource.configuration.id
  # }
  provisioner "local-exec" {
    when = destroy
    command = "az network application-gateway rule delete -g ${var.resource_group_name} --gateway-name ${var.gateway_name} -n ${azurerm_app_service.app_service.name}-rule --verbose"
  }
  provisioner "local-exec" {
    when = destroy
    command = "az network application-gateway http-listener delete -g ${var.resource_group_name} --gateway-name ${var.gateway_name} -n ${azurerm_app_service.app_service.name}-listener --verbose"
  }
  provisioner "local-exec" {
    when = destroy
    command = "az network application-gateway address-pool delete -g ${var.resource_group_name} --gateway-name ${var.gateway_name} -n ${azurerm_app_service.app_service.name}-pool --verbose"
  }
}
```
The configuration works as expected when running terraform destroy and terraform apply for first time
But if we change any attribute of app service which causes terraform apply to replace resources. 

Lets say i change the name of web app and run terraform apply then it throws cycle error as:

Error: Cycle: null_resource.configuration (destroy), null_resource.configuration_delete (destroy), azurerm_app_service_custom_hostname_binding.custom_name (destroy), azurerm_app_service.app_service (destroy), azurerm_app_service.app_service

What is the best way to handle such configuration changes.

**Comment by jbardin** [comment]
Hi @Divya1388,

I sympathize that attempting to trigger changes at destroy time can be difficult. Unfortunately destroy time provisioners can be quite tricky to use. This is an example of why we're planning on deprecating references in destroy provisioners altogether, as seen in #23559.

There may be other ways to accomplish what you want, possibly without using provisioners at all. I would suggest starting a discussion on the [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help, and may be able to offer advice regarding these particular types of resources. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
