### ISSUE TITLE
Add support for Azure

### ISSUE THREAD

**Issue by pvandervelde** [hashicorp/terraform#238]
Moving this to its own issue because it was mentioned in #75 which was closed.

**Comment by kcq** [comment]
+ 1.1 :)

**Comment by fudomunro** [comment]
I looked into this when I +1'ed it, but it seemed like calling WMI from Go was somewhat new territory, according to http://stackoverflow.com/questions/20365286/query-wmi-from-go.
Checking that again, it looks like someone packaged up the code there: http://godoc.org/github.com/StackExchange/wmi

So this is a little closer. I've never written Go for anything serious, but I would be happy to contribute to this effort.

**Comment by pinterb** [comment]
@mitchellh A couple of weeks ago I listened to an interview you did -- I forget when or with who.  During the interview, (I believe) you mentioned that the msopentech team was working on azure support.  Did I hear correctly?  And if so, any progress updates you can provide?

**Comment by mitchellh** [comment]
@pinterb I'm actually not sure what their progress is, sorry. I'll let you know if I find out more.

**Comment by kcq** [comment]
What about using bits from the Azure Packer plugin? https://github.com/MSOpenTech/packer-azure

**Comment by svanharmelen** [comment]
I think this one would make a much better fit in the context of TF: https://github.com/MSOpenTech/azure-sdk-for-go

**Comment by kcq** [comment]
I was referring to the Powershell bits in the packer plugin... You don't need to interact with WMI directly. You should be able to do it through PS. Dealing with COM objects directly is a pain in any language :) Either way, supporting only Linux should be a reasonable compromise. I assume you won't need to make WMI calls there :)

**Comment by svanharmelen** [comment]
Check... But how/when does WMI come into play when building an Azure provider? Don't think that's needed at all right? With the Azure SDK for Go you have a package that can talk to the API and spin machines and alike (which seems to me should not be that much work to build into a provider actually).

Or are you referring to the current abilities of the provisioners?

Or am I just completely missing the point? :wink:

**Comment by errordeveloper** [comment]
As per #770, should this be closed now?

**Comment by fudomunro** [comment]
Seems like #770 satisfies at least the Azure component of this issue. I have the feeling that may not cover Hyper-V, but it's probably worth splitting that into a new issue.

**Comment by errordeveloper** [comment]
+1

**Comment by spuder** [comment]
+1 Looking for Hyper-V support (No azure). 
Should a new feature request be opened that just covers hyper-v?

**Comment by phinze** [comment]
We have Azure now! Will come out with next release. Going to re-title this for just azure and close - @spuder do you think you could open a new request for hyper-v?
