### ISSUE TITLE
Terraform Cloud with VCS Integrated wants to destroy existing resources

### ISSUE THREAD

**Issue by NiyiOdumosu** [hashicorp/terraform#23812]
### Terraform Version

```
v0.12.17
```

### Terraform Configuration Files

composer.tf
```hcl
provider "google-beta" {
  project     = var.composer_project
  region      = var.composer_region
}

resource "google_composer_environment" "composer" {
  name     = var.composer_name
  project  = var.composer_project
  region   = var.composer_region

  config {
    node_count = var.composer_node_count

    node_config {
      machine_type    = var.composer_machine_type
      network         = var.composer_compute_network_name
      service_account = google_service_account.composer.name
      subnetwork      = var.composer_compute_subnetwork_name
      zone            = var.composer_node_zone
    }

    software_config {
      airflow_config_overrides = {
        core-load_example = var.composer_core_load_example
      }
      image_version   = var.composer_image_version
      python_version  = var.composer_python_version
    }
  }

  depends_on = ["google_project_iam_member.composer-worker"]
}

resource "google_service_account" "composer" {
  account_id   = var.composer_service_account_id
  display_name = var.composer_service_account_display_name
  project      = var.composer_project
  provider     = google
}

resource "google_project_iam_member" "composer-worker" {
  member   = "serviceAccount:${google_service_account.composer.email}"
  role     = "roles/composer.worker"
  project  = var.composer_project
  provider = google
}
```
vpc.tf
```hcl
resource "google_compute_network" "vpc" {
  project                 = var.vpc_project
  provider                = google
  name                    = var.vpc_compute_network_name
  auto_create_subnetworks = var.vpc_auto_create_subnetworks
}

resource "google_compute_subnetwork" "vpc" {
  project                  = var.vpc_project
  provider                 = google
  name                     = var.vpc_compute_subnetwork_name
  ip_cidr_range            = var.vpc_compute_subnetwork_cidr_range
  region                   = var.vpc_compute_subnetwork_region
  private_ip_google_access = var.vpc_compute_subnetwork_private_ip_access
  network                  = google_compute_network.vpc.self_link
}

resource "google_compute_route" "default" {
  project     = var.vpc_project
  name        = var.vpc_default_route_name
  dest_range  = var.vpc_route_dest_range
  network     = google_compute_network.vpc.self_link
  next_hop_gateway = var.vpc_next_hop_gateway
}
```
### Expected Behavior

![Screen Shot 2020-01-08 at 11 19 41 AM](https://user-images.githubusercontent.com/35928853/71995594-d7cec180-3208-11ea-91e7-8b6e01d04da5.png)

### Actual Behavior
![Screen Shot 2020-01-08 at 11 16 19 AM](https://user-images.githubusercontent.com/35928853/71995536-bbcb2000-3208-11ea-8502-2480ba838d2b.png)

### Additional Context
This is very problematic. Although these resources have already been created (using the same terraform cloud workspace as the backend) it wants to destroy these resources for some reason. This should not be the case, it should say no changes detected. When I run `terraform plan` from the CLI it shows the correct output. I have no idea why a queue'd plan through the TF Cloud UI wants to destroy all my resources. Please have someone look into this.

**Comment by pkolyvas** [comment]
Hi @NiyiOdumosu 

A couple of questions... would you be willing to double check that the configured VCS root and working directory are correct/as you expect them to be? Also it could be good opportunity to check that everything you want/need is pushed to the repository in question.

From the information provided, it looks to me like the VCS runs can't access the same variables and so we find ourselves in a situation where there's a diff resulting in a destroy, but it's just a thought at this point.

**Comment by NiyiOdumosu** [comment]
My directory hierarchy for terraformula is as follows:

```
.
└── hdm
    └── main.tf
    └── backend.tf
    └── modules
         ├── composer
         ├── vpc
         ├── kms
```

The modules are referenced in the `main.tf` in the `hdm` directory. So unless this directory tree would pose a problem, this should be fine. All of the resources are pushed to the repo and they are in the master branch. The variables are in the repository itself in github and not in the terraform cloud UI. Do the variables have to be listed in the TF cloud UI in order for it to work? That shouldn't be the case tho right?

**Comment by pkolyvas** [comment]
Thanks NiyiOdumosu.

Is there a possibility another backend is configured somewhere within your codebase? Failing that, I'll pass this along to the TFC team to take a look.

**Comment by NiyiOdumosu** [comment]
Sorry for the late response. No it is not configured with any other backend besides my terraform workspace in terraform cloud

**Comment by NiyiOdumosu** [comment]
Any update? @pkolyvas

**Comment by pkolyvas** [comment]
@NiyiOdumosu no update yet.

**Comment by NiyiOdumosu** [comment]
ok I'll stay tuned @pkolyvas

**Comment by apparentlymart** [comment]
Hi @NiyiOdumosu,

I think at the time you originally started this issue Terraform Cloud's free tier was relatively new and didn't have its customer support process in place yet. Since it seems like this problem is specific to your Terraform Cloud workspace, I suggest contacting Terraform Cloud support if you're still having problems of this type. The Cloud support team is better able to respond to this sort of issue because they (unlike the Terraform Core team) can look directly at the configuration details of your workspace and try to understand why Terraform is behaving differently in that context.

You can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Because the problem you've encountered is only occurring in Terraform Cloud, it isn't something that the Terraform Core team is empowered to debug and solve. The Terraform Cloud teams don't routinely monitor issues in this repository (they expect feedback via the support team), so I'm going to close this issue only because it remaining open here is unlikely to lead to a solution.

Thanks and sorry for the delayed response!
