### ISSUE TITLE
leftover module in state that should have been removed

### ISSUE THREAD

**Issue by adubnik** [hashicorp/terraform#23821]
**Terraform version:** 0.12.19

**Problem**
The problem is when we do destroy via plan -destroy resources list is not getting completely cleaned-up leaving resources in the state file. The issue does not manifest itself until there is a dependency on the resource and destroy (via plan)>apply was called. In our case we did plan -destroy with subsequent apply (sandbox environment) which resulted in error because we had output of the module with depends_on condition on the resource created. Because resource which had depends_on also had count it was present in the state file after the original destroy hence module considered this resource as already created for the depends_on condition and our output logic was broken so did our infrastructure pipeline.

**Expected behaviour** 
both plan -destroy and destroy should leave no resources in the state file.

**How to reproduce**

main.tf
```
data "null_data_source" "values" {
  count = 1
  inputs = {
    name = "test"
  }
}
```

terraform plan -destroy -out=plan.out
terraform apply plan.out

more terraform.tfstate
```
{
  "version": 4,
  "terraform_version": "0.12.19",
  "serial": 22,
  "lineage": "9592d516-e93e-32cb-8d0e-a1844dcc8332",
  "outputs": {},
  "resources": [
    {
      "mode": "data",
      "type": "null_data_source",
      "name": "values",
      "each": "list",
      "provider": "provider.null",
      "instances": []
    }
  ]
}
```

terraform destroy
more terraform.tfstate

```
{
  "version": 4,
  "terraform_version": "0.12.19",
  "serial": 23,
  "lineage": "9592d516-e93e-32cb-8d0e-a1844dcc8332",
  "outputs": {},
  "resources": []
}
```

**Comment by froch** [comment]
Hello TF team, I would like to chime in here as well.
We are seeing this same error every time we run a `terraform delete` on our AWS infrastructure:

```
Error: leftover module [redacted] in state that should have been removed; this is a bug in Terraform and should be reported
```

This seems to be the issue your bot keeps as the root of all duplicates being reported for the past two weeks.

Our temporary workaround is to `tf state pull > file`, manually edit and remove the modules that we want destroyed, and then `cat file | tf state push`. An awful and annoying workaround, i'll admit, but one that works nonetheless in the meantime.
