### ISSUE TITLE
Make `contextComponentFactory` and `basicComponentFactory` public

### ISSUE THREAD

**Issue by njuCZ** [hashicorp/terraform#23842]
Can we make `contextComponentFactory` and `basicComponentFactory` public? I find all the fields of `xxxGraphBuilder` (for example: `PlanGraphBuilder`) are public, except `contextComponentFactory`. now I am making a tool for terraform and want to reuse terraform code as much as poosible. I think the graph function is the top entry of terraform core, it's meaningful to make it exported

### Current Terraform Version

```
...
```

### Attempted Solutions

Make all fields related with `contextComponentFactory` exported

**Comment by pkolyvas** [comment]
Hi @njuCZ!

Thanks for taking the time to make this request. We're very appreciative of our community's passion and participation. 

The internals of Terraform don't present a stable API; we can, and will, make breaking changes internally. The result is that we would be unable to support cases where a workflow relying on such internals worked for one release and then fails for another without warning. Terraform isn't meant to be consumed as a library unfortunately. 

While we wish we could answer every need, we are currently focused on some significant improvements we hope will be meaningful for a broad spectrum of Terraform practitioners.

**Comment by njuCZ** [comment]
@pkolyvas Thanks for your kindly reply. I think it's feasible to make `basicComponentFactory`(an internal implementation) private, but as for `contextComponentFactory`, it is an interface, will it still change with time?

**Comment by jbardin** [comment]
Hi @njuCZ,

Go interfaces are implicitly satisfied, but since its methods are exported, `contextComponentFactory` can be assigned without directly referencing it outside of the `terraform` package. 

As for whether it will change; it has changed in the past, and may be modified, replaced or dropped at some point, but these decisions have yet to be made.
