### ISSUE TITLE
State move from indexed resource to non-indexed produces a failure

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform#23847]
### Terraform Version

```
Terraform v0.12.19
```

### Terraform Configuration Files

https://gist.github.com/grimm26/e973a686526f9d054224d251b713aae6

### Expected Behavior

The outputs of the resource should still be available, i.e. the state of the resource should be correct.

### Actual Behavior

The state of the resource seems incorrect and the only way forward is to manually edit the state file or move the resource back to its original place.

### Steps to Reproduce

    Made a bucket
    Changed the s3_bucket module's aws_s3_bucket to no longer be counted. did a terraform state mv 'module.bucket.aws_s3_bucket.b[0]' module.bucket.aws_s3_bucket.b
    a subsequent apply or plan will show:
```
Error: Unsupported attribute

  on s3_bucket/main.tf line 15, in output "id":
  15:   value = aws_s3_bucket.b.id
    |----------------
    | aws_s3_bucket.b is empty tuple

This value does not have any attributes.
```
In the second state file after I changed the module and moved the aws_S3_bucket resource, I think the problem is that even though I removed the count and it removed the `"index_key": 0,` entry from `resources[0]{"instances"}[0]{"attributes"}` it did not remove` "each": "list"` from `resources[0]`

### References

https://github.com/hashicorp/terraform/pull/23582 seems to have introduced this.

**Comment by irl-segfault** [comment]
I hit this problem via a similar mechanism.  Given a list of resources created via `count`, when I `terraform state mv` them to use `for_each`, the `"each":"list"` field does not change to `"each":"map"`.  I manually edited my state file and this seemed to work, although I don't have a deep enough understanding of why.

Steps to reproduce:

1) Given a collection of elements created with `count` and a valid state file derived from that, change the source code to use `for_each` instead, using a map as a the `for_each` variable.

2) Run ```terraform state mv path.to.collection[0] path.to.collection["first"]
terraform state mv path.to.collection[1] path.to.collection["second"]```

3) Observe that `"each":"list"` is still in the state file.
