### ISSUE TITLE
Split out top-level aws_route resource

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#2388]
Same logic as splitting out other top level resources:

 * routes don't all have to be known at route table definition time
 * routes can be dynamically added and removed
 * individual routes can be managed on route tables that terraform does not manage

**Comment by willmcg** [comment]
+1

I swear you guys are reading my mind. I have an exact use for this case where I need to add a route to an pre-existing route table for a VPC peering connection created with Terraform. In this case I own both of the VPCs being peered but only one of them is created by Terraform and so has its own pre-existing route table that needs the peering route to be created.

**Comment by gkze** [comment]
huge +1 :)

**Comment by gkze** [comment]
@phinze I took a stab ad this -- and since `Route` is not a top-level resource in the EC2 API, it doesn't have an ID that it can be identified by. How do you think the `resourceAwsRouteRead` should be implemented then? I was thinking pass it the route table ID that it's an entry in, and then check whether the route is present in there, but I'm not too sure on how clean that is

**Comment by phinze** [comment]
@gkze - great to hear you're interesting in helping out! :grinning: 

It's correct that we need to build our own identifier in this case. You should be able to look to the implementation of `aws_security_group_rule` which is very similar.

Let me know if that helps - happy to go into more detail here too.

**Comment by gkze** [comment]
Thanks @phinze! That's definitely helpful.

On a semi-related note, in a schema -- what's the difference between `Optional` bing `false` vs. `Required` being `true` (or vice versa)? It seems redundant to me but I'm sure there's a reason...

**Comment by phinze** [comment]
I agree it's a little confusing with all the booleans. Here's a truth table of the relevant scenarios:

| Required | Optional | Computed | Description |
| ---- | ---- | ---- | ---- |
| F | F | F | Invalid |
| F | F | T | Exported, read-only field |
| F | T | F | Optional, user specified field (if unspecified, implies that user requested an empty value) |
| F | T | T | Optional, if unspecified, will be calculated
| T | F | F | Required, user-specified field |
| T | F | T | Invalid |
| T | T | F | Invalid |
| T | T | T | Invalid |

**Comment by gkze** [comment]
This is awesome @phinze! Another question: I see there is a `MigrateState` field in a `Resource`. Does this apply here? Not sure how exactly it's being used in the `aws_security_group_rule` resource

**Comment by phinze** [comment]
If you take a look at the [docs for `MigrateState` and `SchemaVersion`](https://github.com/hashicorp/terraform/blob/7850bb39d5465be88ef05e1efb7067788e5cf094/helper/schema/resource.go#L28-L51), you'll see those exist to provide us with hooks for maintaining backwards compatibility as the state config changes. Since you're implementing a new resource, you don't have to worry about them at all. :+1:

**Comment by gkze** [comment]
sweet! :pray:

**Comment by steve-jansen** [comment]
FYI
PR #3548 is an update to #2454 to implement an `aws_route` resource.

**Comment by catsby** [comment]
Hey all! We merged https://github.com/hashicorp/terraform/pull/3548 some time ago, just forgot to close the loop here.

Thanks!
