### ISSUE TITLE
Feature: Add Huaweicloud OBS backend 

### ISSUE THREAD

**Issue by ShiChangkuo** [hashicorp/terraform#23888]
Hi there,

We would like to add a new backend type with HuaweiCloud OBS.

### Use-cases

```hcl
terraform {
  backend "obs" {
    bucket = "accbucket"
    key    = "obsbackend/terraform.tfstate"
    region = "cn-north-1"
    access_key_id = "{{ your access key }}"
    secret_key_id = "{{ your secret key  }}"
  }
}
```
Thanks.

**Comment by pkolyvas** [comment]
We're not merging new remote state backends at the moment. We are however beginning our planning and design of a new backend plugin interface which should allow the Terraform Core team to step out of the way for addition and use of new backends in Terraform. We will share more of our plans with our community once they're concrete. Thanks!
