### ISSUE TITLE
Error on terraform apply for a 7.5MB AWS lambda but OK when 5MB: ResourceConflictException

### ISSUE THREAD

**Issue by frediana** [hashicorp/terraform#23887]
Hello,

I have a this very simple  use case I'm trying to make work for hours now without any success.

I have a simple lambda (written in Go) that is zipped 7.5MB big. A lambda is eventually created into my account (and works). But terraform is somehow try to re-create the same lambda again, and fails (because the lambda already exists)

It seems to be related to the size of this archive somehow. When I try with a smaller archive (around 5MB) everything works fine.

Is there any workaround, limitation or any clue about this issue?

Thanks

Adrien

### Terraform Version

```
Terraform v0.12.19
+ provider.archive v1.3.0
+ provider.aws v2.45.0
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
variable "aws_region" {
  default = "eu-west-1"
}

provider "aws" {
  region = var.aws_region
}

resource "aws_iam_role" "iam_for_lambda" {
  name = "iam_for_lambda"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_lambda_function" "foo" {
  function_name = "foooooo"

  filename         = "function.zip"

  handler = "main"
  runtime = "go1.x"

  role = aws_iam_role.iam_for_lambda.arn
}

```

### Debug Output

https://gist.github.com/frediana/606331547ca66d41e658449032e63ad4

### Crash Output

https://gist.github.com/frediana/24e0c3454271afa88588b95cf7d99372

### Expected Behavior

A lambda should be created successfully and terraform apply should not end up with an error.

### Actual Behavior

Lambda is created/uploaded to AWS because but terraform crash.

```
Error: Error creating Lambda function: ResourceConflictException: Function already exist: foooooo
{
  Message_: "Function already exist: foooooo",
  Type: "User"
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

The function I try to create is a 7.5MB zip, Golang binary.

**Comment by obourdon** [comment]
Not sure if this is related but I have been having a lot of issues today quite similar to the one you are having but mostly on IAM. In fact seems like AWS API calls have been experiencing some kind of delays/... today (at least in the eu-west-1 zone) and according to AWS status page

**Comment by frediana** [comment]
> Not sure if this is related but I have been having a lot of issues today quite similar to the one you are having but mostly on IAM. In fact seems like AWS API calls have been experiencing some kind of delays/... today (at least in the eu-west-1 zone) and according to AWS status page

Thanks, I just tried deploy my lambda to us-east-1 with same result.

**Comment by frediana** [comment]
The only workaround I got for now is to use a S3 bucket to host the lambda source code.

**Comment by jbardin** [comment]
Hi @frediana,

Since Terraform is only passing the filename to the AWS plugin, it appears to be a problem with the provider itself. I'll mark this to be transferred to the appropriate repo.
