### ISSUE TITLE
Add variable validation similar to AWS CloudFormation Parameters with AllowedPattern & AllowedValues

### ISSUE THREAD

**Issue by heldersepu** [hashicorp/terraform#23884]
### Current Terraform Version
0.12 (Latest)

### Use-cases
Would be nice to get failures right on plan if a given variable is not the expected pattern or allowed value just like AWS CloudFormation does with Parameters with AllowedPattern & AllowedValues

### Proposal
Something like this:
```
variable  "instance_type" : {
    type = string
    allowed_values = ["t2.micro", "m1.small", "m1.large"]
}
```
or we could use the description:
```
variable  "instance_type" : {
    type = string
    description = <<EOF
This is the instance type.
allowed_values = ["t2.micro", "m1.small", "m1.large"]
EOF
}
```

### References
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html

**Comment by heldersepu** [comment]
Decided to try the description proposal `C#` does something a lot of stuff on the comments:
```
    /// <summary>
    /// ## Geographic coordinates
    /// ___
    /// A **geographic coordinate system** is a coordinate system used in geography that enables every location on Earth to be specified by a set of numbers
    /// </summary>
    public class Location
    {
        /// <summary>**Latitude**: a geographic coordinate that specifies the north–south position of a point on the Earth's surface.</summary>
        /// <example>25.85</example>
        [Range(-90, 90)]
        public float Lat { get; set; }

        /// <summary>**Longitude**: a geographic coordinate that specifies the east-west position of a point on the Earth's surface.</summary>
        /// <example>-80.27</example>
        [Range(-180, 180)]
        public float Lon { get; set; }
    }
```

 I think that using the description for this should be OK:

**Comment by heldersepu** [comment]
And now that I think about it the `AllowedValues` we should be able to do it with an `AllowedPattern`

**Comment by apparentlymart** [comment]
Hi @heldersepu!

Based on when you filed this I assume "0.12 (latest)" meant 0.12.19, in which case you might be interested to know that 0.12.20 introduced an experimental new feature that is quite close to what you described here: [Custom Validation Rules](https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules).

It's currently an opt-in experiment so we can gather feedback on it before finalizing it, so it's not ready for "production" use yet but we'd love it if you could give it a try with the use-cases you described here and let us know how it worked out!

**Comment by heldersepu** [comment]
Good stuff that should do it!

**Comment by heldersepu** [comment]
@apparentlymart I got with the:
`Validation error message must be at least one full English sentence starting with an uppercase letter and ending with a period or question mark.`
that is tough validation :smile: 

but that worked fine:
```
variable "instance_type" {
  type = string

  validation {
    condition     = can(regex("t2.micro|m1.small|m1.large", var.instance_type))
    error_message = "Invalid instance type allowed_values = ['t2.micro', 'm1.small', 'm1.large']."
  }
}
```
