### ISSUE TITLE
Getting syntax error with automatically generated terraform templates

### ISSUE THREAD

**Issue by zukeru** [hashicorp/terraform#2389]
Hello,
First question:
I wrote a python dsl to be used in conjuction with a web ui for my job that takes a set of arguments and produces terraform templates. I'm getting a syntax error but I'm not quite sure why. The error returned is not specific at all, and I'm not quite sure where the error is coming from because the line it references I have deleted the line and it still references that line as the error. For example: it says line 47 so I removed line 47 and the syntax error stayed on 47.

My second problem is it possible to run ansible playbooks by executing inline commands against the instances terraform spins up through the ASG. like for every instance that is created in the ASG it would run for example ansible playbook.yml ?

Ignore anything with 000000's attached thats just me sanitizing things for security purposes.

Error: Error loading config: Error parsing configs/Output.tf: Line 46, column 25: syntax error

    provider "aws" {
            access_key = "removed"
            secret_key = "removed"
            region = "us-west-2"
     }

     resource "aws_security_group" "elasticsearch_sg" {
                    name = "elasticsearch_sg"
                    description = "this is a security group for elasticsearch the application"
                    
                    ingress {
                        from_port = 9300
                        to_port = 9300
                        protocol = "tcp"
                        self = true
                        }
                        
                    ingress {
                        from_port = 9200
                        to_port = 9200
                        protocol = "tcp"
                        self = true
                        }
                        
                    ingress {
                        from_port = 22
                        to_port = 22
                        protocol = "tcp"
                        cidr_blocks = ["172.31.0.0/16"]
                        }
                        
       }

    resource "aws_launch_configuration" "ES-LaunchConfig" {
        name="ES-LaunchConfig"
        image_id="ami-00000000"
        instance_type="m3.2xlarge"
        security_groups=['${aws_security_group.elasticsearch_sg.id}']
        iam_instance_profile="arn:aws:iam::000000000000:instance-profile/elasticsearchRole"
        user_data="${file("/Users/grantzukel/Downloads/terraform_0.5.3_darwin_amd64/configs/user-data.txt")}"
        key_name="main-access"
        
            ebs_block_device{
                device_name = "/dev/sdb"
                volume_type = "io1"
                volume_size = 150 #this is line 46 in my text editor.
                delete_on_termination = true
                iops = 1000
            }
        
            ebs_block_device{
                device_name = "/dev/sdc"
                volume_type = "io1"
                volume_size = 150
                delete_on_termination = true
                iops = 1000
            }
        
            ebs_block_device{
                device_name = "/dev/sdd"
                volume_type = "io1"
                volume_size = 150
                delete_on_termination = true
                iops = 1000
            }
        
            ebs_block_device{
                device_name = "/dev/sde"
                volume_type = "io1"
                volume_size = 150
                delete_on_termination = true
                iops = 1000
            }
        

         }
    
    resource "aws_autoscaling_group" "ElasticSearch_ami-0000000_mixed" {
        name = "ElasticSearch_ami-0000000_mixed"
        availability_zones = ['us-west-2b', 'us-west-2c']
        max_size = 1
        min_size = 1
        launch_configuration = "${aws_launch_configuration.ES-LaunchConfig.id}"
        health_check_grace_period = 300
        health_check_type = "EC2"
        desired_capacity = 1
        force_delete = true
        vpc_zone_identifier = ["subnet-00000","subnet-00000","subnet-00000000"]
        
            tag {
                key = "Name"
                value = "ElasticSearch"
                propagate_at_launch = true
                }                                   
            
            tag {
                key = "clusterName"
                value = "ElasticSearch_ami-000000_mixed"
                propagate_at_launch = true
                }                                   
            
            tag {
                key = "Role"
                value = "mixed"
                propagate_at_launch = true
                }                                   
         }

**Comment by zukeru** [comment]
I updated the script a bit to output it a bit different, but now I get an error saying certain things aren't list when they need to be and they obvious are.

Also for VPC_ZONE_IDENTIFIER I use the subnet id correct.
 vpc_zone_identifier (Optional) A list of subnet IDs to launch resources in. 

errors i get 
Errors:

  * aws_launch_configuration.ES-LaunchConfig: security_groups: should be a list
  * aws_autoscaling_group.ElasticSearch_ami-8d80b9bd_mixed: vpc_zone_identifier: should be a list
  * aws_autoscaling_group.ElasticSearch_ami-8d80b9bd_mixed: availability_zones: should be a list
  * aws_autoscaling_group.ElasticSearch_ami-8d80b9bd_mixed: : invalid or unknown key: subnet-0fec2278  <- this exist because I copied it out of aws, so is this vpc_id instead?




            provider "aws" {
                access_key = ""
                secret_key = ""
                region = "us-west-2"
            }

            resource "aws_security_group" "elasticsearch_sg" {
                    name = "elasticsearch_sg"
                    description = "this is a security group for elasticsearch the application"
                    ingress {
                        from_port = 9300
                        to_port = 9300
                        protocol = "tcp"
                        self = true
                    
                    ingress {
                        from_port = 9200
                        to_port = 9200
                        protocol = "tcp"
                        self = true
                    }
                    ingress {
                        from_port = 22
                        to_port = 22
                        protocol = "tcp"
                        cidr_blocks = ["172.31.0.0/16"]
                    }     
            }

            resource "aws_launch_configuration" "ES-LaunchConfig" {
                    name="ES-LaunchConfig"
                    image_id="ami-8d000000"
                    instance_type="m3.2xlarge"
                    security_groups="['${aws_security_group.elasticsearch_sg.id}',]"
                    iam_instance_profile="arn:aws:iam::00000000:instance-profile/elasticsearchRole"
                    user_data="${file("/Users/grantzukel/Downloads/terraform_0.5.3_darwin_amd64/configs/user-data.txt")}"
                    key_name="main-access"
                        ebs_block_device{
                            device_name = "/dev/sdb"
                            volume_type = "io1"
                            volume_size = 150
                            delete_on_termination = true
                            iops = 1000
                        }
                        ebs_block_device{
                            device_name = "/dev/sdc"
                            volume_type = "io1"
                            volume_size = 150
                            delete_on_termination = true
                            iops = 1000
                        }
                        ebs_block_device{
                            device_name = "/dev/sdd"
                            volume_type = "io1"
                            volume_size = 150
                            delete_on_termination = true
                            iops = 1000
                        }
                        ebs_block_device{
                            device_name = "/dev/sde"
                            volume_type = "io1"
                            volume_size = 150
                            delete_on_termination = true
                            iops = 1000
                        }
                }
            resource "aws_autoscaling_group" "ElasticSearch_ami-8d000000_mixed" {
                    name = "ElasticSearch_ami-8d000000_mixed"
                    availability_zones = "['us-west-2b', 'us-west-2c']"
                    max_size = 1
                    min_size = 1
                    launch_configuration = "${aws_launch_configuration.ES-LaunchConfig.id}"
                    health_check_grace_period = 300
                    health_check_type = "EC2"
                    desired_capacity = 1
                    force_delete = true
                    vpc_zone_identifier = "["subnet-8d000000",]"
                        tag {
                            key = "Name"
                            value = "ElasticSearch"
                            propagate_at_launch = true
                            }                                   
                        
                        tag {
                            key = "clusterName"
                            value = "ElasticSearch_ami-8d000000_mixed"
                            propagate_at_launch = true
                            }                                   
                        
                        tag {
                            key = "Role"
                            value = "mixed"
                            propagate_at_launch = true
                            }                                   
                }

**Comment by phinze** [comment]
Hi there!

The list syntax is indeed a little off there.

Here's what they should look like:

```js
resource "aws_launch_configuration" "ES-LaunchConfig" {
  // ...
  security_groups = ["${aws_security_group.elasticsearch_sg.id}"]
}

resource "aws_autoscaling_group" "ElasticSearch_ami-8d000000_mixed" {
  // ...
  availability_zones = ["us-west-2b", "us-west-2c"]
  vpc_zone_identifier = ["subnet-8d000000"]
}
```

**Comment by zukeru** [comment]
is it because I use ' instead of " ^reference my first post.

**Comment by phinze** [comment]
@zukeru yes, the [HCL config syntax](https://terraform.io/docs/configuration/syntax.html) is relatively simple, only double quotes are allowed as string delimiters.

**Comment by zukeru** [comment]
Thanks, that clears it up and I think I fixed it. Thanks.

**Comment by phinze** [comment]
> My second problem is it possible to run ansible playbooks by executing inline commands against the instances terraform spins up through the ASG. like for every instance that is created in the ASG it would run for example ansible playbook.yml ?

You should look into [user data](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) to get commands to be run on every instance boot - Terraform does not get direct access to ASG instances because can always be recycled.
