### ISSUE TITLE
terraform doesn't show/remove resource from a state when resource is empty

### ISSUE THREAD

**Issue by navi86** [hashicorp/terraform#23898]
Hi,
### Terraform Version
```
v0.12.12
```

### Terraform Configuration Files
I have postgresql module where I create db if it's required

```hcl
module "postgresql" {
  source = "../postgresql"

  host         = var.host
  port         = var.port
  database     = var.database
  rds_username = var.rds_username
  rds_password = var.rds_password
  db_username  = var.db_username
  db_password  = var.db_password
  db_name      = var.db_name
  create_db    = true
  db_schema    = var.db_schema
}
# content of Postgresmodule
resource "postgresql_database" "this" {
  count = var.create_db ? 1 : 0
  name  = var.db_name
  owner = var.rds_username
}
```
in some cases, I need to remove configuration related to postgresql module(so I use command "terraform state rm module.postgresql ", but resource postgresql_database doesn't removed from state.
### Debug Output
destroy terraform state with previously removed module with resource that are empty
### Crash Output
I got error that provider can't connect to db but state should not have any information related to postgresql module:
```
Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: dial tcp :5432: connect: connection refused
```
### Expected Behavior
terraform rm should remove module information entirely

### Actual Behavior
destroy failed because state has resource with zero instances which is not possible to delete via "terraform state rm" or view via "terraform state list"

content of terraform state:
```
{
      "module": "module.postgresql",
      "mode": "managed",
      "type": "postgresql_database",
      "name": "this",
      "each": "list",
      "provider": "module.postgresql.provider.postgresql",
      "instances": []
    }
```
### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
3. `terraform rm state module.postgresql`
4. `terraform destroy`

**Comment by jbardin** [comment]
Hi @navi86,

This appears to be fixed in the current release.
Please let us know if you can replicate this issue after upgrading your terraform installation.

Thanks!
