### ISSUE TITLE
How to change aws cli to terraform

### ISSUE THREAD

**Issue by kientrinhvan** [hashicorp/terraform#23897]
### Terraform Version

Terraform v0.12.19
+ provider.aws v2.44.0
### Terraform Configuration Files

provider "aws" {
	region     = "us-west-2"
}

resource "aws_launch_template" "ecs_instance" {
	image_id                    = "ami-09e71fb1baf16d0cd"
	instance_type               = "t2.medium"
	key_name 					= "in***USWest2QA"
	
	network_interfaces {
		subnet_id                   = "subnet-804e77f6"
		security_groups = ["sg-dcc844a7"]
	}
	
	tag_specifications {
		resource_type = "instance"

		tags = {
		  Key = "Owner"
		  Value = "QA"
		}
	}
	
	tag_specifications {
		resource_type = "volume"

		tags = {
		  Key = "Owner"
		  Value = "QA"
		}
	}
}
### Debug Output

C:\Public\jenkins_cli_terraform>terraform apply -auto-approve
aws_launch_template.ecs_instance: Creating...

Error: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: E8tJy2EnbrHi6B_Z6MXC_
AJvdLXmY0XR9zML6H5ZuRSfc1HJCUmzTFmwlzANLH1CLPuwp3yuaBINwYiseoz3yJpxiTHve7xPoR1cAc3oZeCQqxJUDi470-JFRhtD1dAY1X1NhOdM-wcgZkebJFD0KC8j-SCjbR1_T
-AjKdXu7G2bsZNaieB5w4RnT4DFWCPFkw31F04IoPFopnbnt18nLg6inNhPm6O5s5V-R9GZibJ4FmWuxv0g7BpGaqRGDRPjco0TzR8CLU0SAvWEidG20vVxV3xCXkM6Y60YlalGGu91M
4oylScmeT5yhCYpUB-K1nCtepYubKhf2tJzQ1c5vJfhf0AG34egODLS-qupUk-c9DW5rCoT096a6Sh1suyovGCbB3SQHcTRYCWMOZu3NpqOUHULBxcFDoOQYonE0LCH2EvT-IkdaVAIO
U2JVf_tTpriLV_5bzqePDMzx-SiR2Vfo4cug45jmweQ2IVR3vsXeL-B4XvnkLeXXYQ2OVcMyCIwtdehywMQ04k
        status code: 403, request id: fcb45c5e-a250-4e84-b7b8-6c83ea29bef2

  on testTerra.tf line 47, in resource "aws_launch_template" "ecs_instance":
  47: resource "aws_launch_template" "ecs_instance" {
### Expected Behavior

I have an aws cli command line: the cli run  instances is ok.

aws ec2 run-instances --image-id ami-09e71fb1baf16d0cd --count 1 --instance-type t2.medium --key-name in***USWest2QA --security-group-ids sg-dcc844a7 --subnet-id subnet-804e77f6 --tag-specifications ResourceType=instance,Tags=[{Key=Owner,Value=QA}] ResourceType=volume,Tags=[{Key=Owner,Value=QA}]

### Steps to Reproduce

terraform apply -auto-approve

### Additional Context

I try to change aws cli to terraform, but not successful
How to solve my this issue?

**Comment by teamterraform** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Since this issue doesn't represent a specific bug or feature request, We're going to close it. Please do feel free to ask your question in the community forum. Thanks!
