### ISSUE TITLE
`terraform output` with no params should show all configured outputs

### ISSUE THREAD

**Issue by LeftyBC** [hashicorp/terraform#2390]
Currently `terraform output` requires a NAME parameter.

I'm thinking this should be optional, and if not specified it should just emit all configured outputs.

I can emulate this behaviour by running `terraform apply` again, but I don't necessarily want to apply pending changes.

**Comment by gtmtech** [comment]
:+1:

**Comment by sparkprime** [comment]
+1

**Comment by radeksimko** [comment]
See #1209 and #2335

**Comment by mstuparu** [comment]
+1

**Comment by radeksimko** [comment]
#2920 has been merged.
