### ISSUE TITLE
SIGINT on terraform plan should also interrupt state refresh

### ISSUE THREAD

**Issue by eherot** [hashicorp/terraform#23908]
In environments with slow internet connections or large numbers of state objects, this means a significant amount of waiting before an interrupt can go through. E.g.

```
Jan 21 12:10:11❯ terraform plan 2>&1 | ts

  ** Ctrl + C hit at Jan 21 12:10:11 **

Jan 21 12:10:12 ^CInterrupt received.
Jan 21 12:10:13 Please wait for Terraform to exit or data loss may occur.
Jan 21 12:10:13 Gracefully shutting down...
Jan 21 12:10:13 Refreshing Terraform state in-memory prior to plan...
Jan 21 12:10:13 The refreshed state will be used to calculate this plan, but will not be
Jan 21 12:10:13 persisted to local or remote state storage.
Jan 21 12:10:13
Jan 21 12:10:14 module.haproxy_cluster.data.ct_config.haproxy_node: Refreshing state...

  ** Tons of state objects refreshed **

Jan 21 12:10:19 module.haproxy_cluster.aws_cloudwatch_metric_alarm.proxy-cluster-asg-high-cpu: Refreshing state... [id=ec2-stg-proxy-cluster-asg-High-CPU-Utilization]
Jan 21 12:10:20
Jan 21 12:10:20 ------------------------------------------------------------------------
Jan 21 12:10:23
Jan 21 12:10:23 No changes. Infrastructure is up-to-date.
Jan 21 12:10:23
Jan 21 12:10:23 This means that Terraform did not detect any differences between your
Jan 21 12:10:23 configuration and real physical resources that exist. As a result, no
Jan 21 12:10:23 actions need to be performed.
```

...A total of 12 seconds elapses between sending the interrupt signal and the actual shutdown, even if the signal is sent _immediately_ after the command is invoked (this is extremely annoying!).

Perhaps even more relevant, because of this long wait, users who have executed the command in error are likely to hit Ctrl + C multiple times, forcing an immediate shutdown, which, curiously, still does not quite exit immediately:

```
❯ terraform plan
^C^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Two interrupts received. Exiting immediately. Note that data
loss may have occurred.
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.haproxy_cluster.data.ct_config.haproxy_node: Refreshing state...

  ** A few more state objects refreshed(!??!) **

Error: operation canceled
```

# What should happen

During `terraform plan`, which is supposed to be a (mostly) read-only operation, terraform should shut down after receiving SIGINT or SIGTERM _without_ performing any additional steps (such as state refresh). To do otherwise adds unnecessary frustration to the user experience.

This is possibly sort of a rehashing of #16571 which seems to have been closed without being addressed.

**Comment by jeffbyrnes** [comment]
There’s also #18345, which appears to be similar.

**Comment by eherot** [comment]
Closing this because it is definitely a duplicate of #18345 (not sure why I wasn't able to find that before!).
