### ISSUE TITLE
Modification of RDS subnet groups causes recreation of instance

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#2392]
Was just modifying the subnet groups for and RDS Instance and was surprised that TF was trying to recreate it.  I did have the prevent_destroy set, but had I not it would've been a tough night.

There's not special about the code I'm using.

    resource "aws_db_subnet_group" "db-subnet-1-group" {

        name        = "${var.env}-db-subnet-1-group"
        description = "${var.env} db subnet group"
        subnet_ids  = ["${var.db_subnet_1_id}","${var.db_subnet_2_id}"]

    }

    resource "aws_db_instance" "db-mysql-1" {

        identifier              = "${var.env}-mysql-1"
        allocated_storage       = "${var.allocated_storage}"
        engine                  = "mysql"
        engine_version          = "${var.engine_version}"
        instance_class          = "${var.instance_class}"
        name                    = "${var.env}mysql1"
        username                = "${var.env}bqmysql"
        password                = "${var.mysql_password}"
        multi_az                = "${var.multi_az}"
        apply_immediately       = true
        publicly_accessible     = false
        db_subnet_group_name    = "${aws_db_subnet_group.db-subnet-1-group.id}"
        parameter_group_name    = "default.mysql5.6"
        backup_retention_period = 3
    
        lifecycle = {
    	   prevent_destroy = true
        }
    }

**Comment by thegedge** [comment]
Just had the same issue. Modifying the subnet ids will recreate the subnet group (because `ForceNew = true`), but through the AWS console one can add and remove subnet IDs without having to destroy the subnet group.
