### ISSUE TITLE
Load Variables from Terraform Cloud Workspace even in Local Mode

### ISSUE THREAD

**Issue by mitchellmaler** [hashicorp/terraform#23952]
### Use-cases
Being able manage TF variables in the workspace make organizing variables simply. The issue is these variables are not loaded when ran in local mode and have to used only in remote mode.

Our use case currently is we use a CI server which runs our TF plans and applies but want to use TF cloud for state and variables.

### Attempted Solutions
None, this is not supported to pull variables.

### Proposal
Create a way to provide variables as part of the backed when state is refreshed. This would then provide this variables file that can be loaded for the local tf run.

**Comment by pkolyvas** [comment]
Thanks for your feedback @mitchellmaler. Super interesting use case! I've passed your feedback onto the Terraform Cloud team and will close this out (even if it would mean work from both teams should it be something we pursue).
