### ISSUE TITLE
Ability to re-order variables in a Terraform Cloud Workspace

### ISSUE THREAD

**Issue by mitchellmaler** [hashicorp/terraform#23951]
### Use-cases
Re-order variables as you add them in the variables sections in a Terraform Cloud Workspace.

### Attempted Solutions
None, currently would have to remove and re-add all variables in the order I would like.

### Proposal
Having a way to drag up and down a variable which would update the index of that variable so when loaded in the UI it would always be in that order.

**Comment by pkolyvas** [comment]
Another great suggestion @mitchellmaler. I've forwarded it to the Terraform Cloud team.
