### ISSUE TITLE
Introduce provider metadata

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#23959]
Specifically the core would benefit from knowing:
1) Human-friendly name of the provider (for generating docs and using the name elsewhere in error messages)
2) URL for reporting issues (for error messages like these:

> This is a bug in the provider, which should be reported in the provider's own issue tracker.

There may be some considerations to make in relation to the Registry. We'll need to maintain this metadata inside the provider binary - but the Registry could leverage this somehow, if it's exposed in a machine-readable way.

**Comment by apparentlymart** [comment]
This issue seems to be representing a possible implementation strategy for the use-case described in #23945, so I'm going to close it to consolidate over there.
