### ISSUE TITLE
set diffs, mainly subtract

### ISSUE THREAD

**Issue by jeffdyke** [hashicorp/terraform#23977]
### Current Terraform Version

Terraform v0.12.19 (I'll update soon)

### Use-cases

I was looking around and saw nothing obvious in documentation or extending terraform, if you can prove me wrong, great!!!  

The functions on sets are very nice, but i more often seem to be trying to trim down my configs by removing items from commonly used sets in `for_each`.  The common pattern is 
`for_each = toset([for p in data.instance_profiles: p if p != "S3Admin" && p != "ECRAdmin"])`

I like `for_each` much more than `count`, so the example is personal bias :) 

### Attempted Solutions

Well.... none.  That is why this is mainly a question and perhaps a PR.  
### Proposal

Its seems like adding a boolean to match keys is a really bad idea (joke), so i was wondering about a `setdiff(all, unwanted)`.  You could go to add and subtract as well, but that allows me to do both.

Thanks for pointers.  If i can do this in a extension, i'd be happy to and publish it so you can see it, just can't see how that's possible right now.

**Comment by jeffdyke** [comment]
actually could this be as simple as: 
`"setsub": stdlib:SetSubtractFunc`

in https://github.com/hashicorp/terraform/blob/ff4ea042c208f7a5115b045de56fe6faba56bdc5/lang/functions.go

**Comment by apparentlymart** [comment]
Hi @jeffdyke! Thanks for sharing this use-case.

It looks like #23424 did the very thing you were proposing to do here, albeit calling it `setsubtract` instead. It's been merged ready for inclusion in the forthcoming v0.12.21 release, so I'm going to close this out to reflect that. Thanks again for the feature request!
