### ISSUE TITLE
aws_security_group_rule - panic on 0.5.3

### ISSUE THREAD

**Issue by btobolaski** [hashicorp/terraform#2399]
Unfortunately, I'm not really sure what I did to cause this. I do know that I did an apply without a plan and since then, every time I've tried to do a plan I get a panic. Since this has broken things for me, I stashed the changes and tried to do a plan again and it is still panicing. 

Here is the crash.log from one of the recent attempts. https://gist.githubusercontent.com/btobolaski/bf967e15214b50dd68a8/raw/1f92738ed87df9fb2248280678e430f0e5bf8799/gistfile1.txt

**Comment by mitchellh** [comment]
This is fixed on master, will be in the next release!
