### ISSUE TITLE
0.12upgrade fails to catch resource name syntax issue

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#24008]
`terraform 0.12upgrade` fails to catch when resource types are named improperly (see error below for example). This causes a problem because after your syntax is upgraded, you attempt a `terraform plan` and see the "invalid resource name" error. If you try to perform a `state mv` tf12 tells you your name syntax is invalid. so if you try to use tf11 to perform a state mv, tf11 says your syntax is invalid (because you already performed 0.12upgrade)

bug aside - ive been super impressed with how good the 0.12upgrade works. great job, yall!

```
Error: Invalid resource name

  on records.tf line 193, in resource "cloudflare_record" "3<redacted>":
 193: resource "cloudflare_record" "3<redacted>" {

A name must start with a letter or underscore and may contain only letters,
digits, underscores, and dashes.
```

### Terraform Version
0.12.20

**Comment by jbardin** [comment]
Hi @drewmullen,

The upgrade tool will leave configuration which required user intervention in the config, with a `# TF-UPGRADE-TODO` comment describing what action needs to take place. In this case you would find in the upgraded config:

```
# TF-UPGRADE-TODO: In Terraform v0.11 and earlier, it was possible to begin a
# resource name with a number, but it is no longer possible in Terraform v0.12.
#
# Rename the resource and run `terraform state mv` to apply the rename in the
# state. Detailed information on the `state move` command can be found in the
# documentation online: https://www.terraform.io/docs/commands/state/mv.html
```

The 0.11 `terraform 0.12checklist` tool will also flag this for you, and output the following:

After analyzing this configuration and working directory, we have identified some necessary steps that we recommend you take before upgrading to Terraform v0.12:

```
- [ ] `resource "cloudflare_record" "3XXXXX"` has a name that is not a valid identifier.

  In Terraform 0.12, resource names must start with a letter. To fix this, rename the resource in the configuration and then use `terraform state mv` to mirror that name change in the state.
```

Closing this out, as the `0.12upgrade` tool is effectively frozen to prevent any changes in behavior for existing upgrade scenarios.
