### ISSUE TITLE
Error: Failed to instantiate provider "aws" to obtain schema: fork/exec

### ISSUE THREAD

**Issue by brettcave** [hashicorp/terraform#24010]
### Terraform Version

```
0.12.6.  + provider.aws v2.47.0 (s3 backend)
```

### Terraform Configuration Files

```none
...
```

### Expected Behavior
`terraform init` succeedss.

### Actual Behavior

after a `validate`: 

```
Error: Failed to instantiate provider "aws" to obtain schema: fork/exec /some/local/path/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.47.0_x4: permission denied```

after `init -verify-plugins=true`:

```Initializing the backend...
Backend configuration changed!

Terraform has been successfully initialized!....etc```

```$ terrafrm plan -out=plan.out

Error: Failed to instantiate provider "aws" to obtain schema: fork/exec /some/local/path/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.47.0_x4: permission denied
```

### Steps to Reproduce
The error is happening in a C?I pipeline. The CI agents use the job name as a directory. 
Environment: Ubuntu 16.04 on EC2. There are no filesystem issues. I suspect it might be related to a changing file system path.

1. root is in /some/local/path/job1/, `terraform validate; terraform init; terraform plan; terraform apply; terraform destroy`. A .terraform directory is generated after the init.
2. The root directory is copied (via the ci server and back to the agent) into /some/local/path/job2/
including the .terraform dir (including tfstate).
3. `terraform init` (the init doesn't get the -reconfigure paramet, not sure if that would make a difference. error occurs.

### Additional Context
validate, init and plan are executed via Makefile.

### References
#19808

-->

**Comment by brettcave** [comment]
removing `.terraform` redownloaads aws and everything works.

**Comment by echoboomer** [comment]
Running into the same issue with the `google` provider. Out of curiosity, which CI/CD platform are you using for this?

**Comment by teamterraform** [comment]
Hi @brettcave,

Sorry you're having an issue here, but it doesn't look like something terraform has control over. The plugins are expected to keep the permission and executable bits as set during the `init` process. If something changes the permissions on the provider to prevent terraform from executing the binary, you will see the above error message. 

If something has corrupted the `.terraform` directory, removing it and re-initializing is the correct course of action.

**Comment by fernandosalomao** [comment]
This is a permission issue. It seems the permissions on the files are lost when downloaded to the agent. (Azure Pipelines has this [issue](https://github.com/microsoft/azure-pipelines-tasks/issues/6364))

Terraform best practice is to artifact and restore the whole .terraform directory.
[Plan and Apply on different machines](https://learn.hashicorp.com/terraform/development/running-terraform-in-automation#plan-and-apply-on-different-machines)

Workaround with
`chmod -R a+x ./.terraform/plugins/linux_amd64/*`
