### ISSUE TITLE
Terraform can't handle quotations in command line flags.

### ISSUE THREAD

**Issue by tarrant** [hashicorp/terraform#2401]
When called from the command line the following command works:

```
terraform remote config -backend=consul -backend-config="path=application-data/system/devel-test"
```

When called directly from go this fails:

```
cmd := exec.Command(
	"/usr/local/bin/terraform", "remote", "config", "-backend=consul",
	fmt.Sprintf(`-backend-config="path=%s"`, remotePath),
)
```

With the following error:

> missing 'path' configuration
> 
> 2015/06/18 15:22:19 waiting for all plugin processes to complete...
> If the error message above mentions requiring or modifying configuration
> options, these are set using the `-backend-config` flag. Example:
> -backend-config="name=foo" to set the `name` configuration

The following will work:

```
cmd := exec.Command(
	"/usr/local/bin/terraform", "remote", "config", "-backend=consul",
	fmt.Sprintf(`-backend-config=path=%s`, remotePath),
)
```

It appears that terraform is relying upon the shell to remove the quotation marks for it and is unable to deal with them itself.

This is really confusing because the error messages indicate that they are required.

**Comment by mitchellh** [comment]
That is really strange, but I'm not sure this is a a Terraform bug. The flag parsing is all 100% done by the Go standard library `flag` library. I'm going to do some testing to verify though.

**Comment by mitchellh** [comment]
I've verified that this is the way the Go standard library handles it. I tested with a basic int type:

```
what → go run exec.go
invalid value "\"7\"" for flag -foo: strconv.ParseInt: parsing "\"7\"": invalid syntax
Usage of /var/folders/q_/r20nyp2d0fvgwnsztdv8wwqw0000gn/T/go-build859097545/command-line-arguments/_obj/exe/main:
  -foo=0: what
```

I think the safest thing to do would be to just separate the args (don't use the =):

```
exec.Command("terraform", "remote", "config", "-backend", "consul", "-backend-config", "path="+path)
```

Sorry!
