### ISSUE TITLE
Update lib/pq to at least version 1.1.0 to support new postgres encryption scheme

### ISSUE THREAD

**Issue by svenstaro** [hashicorp/terraform#24016]
[PostgreSQL now supports scram-sha-256](https://www.postgresql.org/docs/11/auth-password.html) as a password encryption mechanism. Sadly, the version of lib/pq that is currently used by Terraform as of today doesn't support this. However, lib/pq does support this in a newer version. This is actually a deal-breaker right now on databases that support this scheme as you'll get this when using PostgreSQL as a storage backend:

    terraform init
    Initializing the backend...
    
    Error: pq: unknown authentication response: 10

This is documented [here](https://github.com/lib/pq/issues/817). For reference: Terraform currently uses lib/pq version 1.0.0 but [1.1.0 added support for it](https://github.com/lib/pq/releases/tag/v1.1.0).

It should, therefore, be as simple as bumping the minor version. I suggest going all the way up to the current version: [1.3.0](https://github.com/lib/pq/releases/tag/v1.3.0)

**Comment by pezhore** [comment]
For others who have found this issue, a work around (without changing the PostgreSQL encryption mechanism back to md5 for the server), you can manually generate the md5 password:

```
tf@terraform:~$ echo -n passwordusername | md5sum
5a231fcdb710d73268c4f44283487ba2  -
...
edb=# alter role username password 'md55a231fcdb710d73268c4f44283487ba2';
ALTER ROLE
```
