### ISSUE TITLE
add additional aws_security_group causes force new resource

### ISSUE THREAD

**Issue by franklinwise** [hashicorp/terraform#2404]
Terraform v0.6.0-dev (f045e9e8d1daadef343539df4d8a41e4eb54849b)

Adding a new security group to an aws_instance causes it to get created and destroyed.  There's no reason why adding a new group to an instance should cause it to get recreated.

```
-/+ module.api.aws_instance.api.1
   security_groups.#:                         "3" => "4" (forces new resource)
    security_groups.2071441191:                "sg-a77d9dc3" => "sg-a77d9dc3" (forces new resource)
    security_groups.2102606956:                "" => "sg-31fa0c55" (forces new resource)
    security_groups.2192028676:                "sg-0838d86c" => "sg-0838d86c" (forces new resource)
    security_groups.2308945171:                "sg-ad7d9dc9" => "sg-ad7d9dc9" (forces new resource)
```

**Comment by scalp42** [comment]
I'm assuming it's missing a link to check if running inside VPC.

**Comment by franklinwise** [comment]
Thanks @scalp42 your comment helped me find the solution.

Looks like the spec changed underneath me between versions.  The solution was to use:
vpc_security_group_ids instead of security_groups, which is kind of lame IMO.  The framework should be able to tell if a security group is a vpc group or not. Also this creates a precedent that there VPC and non-VPC properties inconsistently.
