### ISSUE TITLE
Computed schema.TypeMap fields incorrectly show having a diff if the field is nested

### ISSUE THREAD

**Issue by chrisst** [hashicorp/terraform#24044]
### Terraform Version

```
Terraform v0.12.21-dev
```

### Expected Behavior

I have a resource which has an Optional/Computed element that is a `schema.TypeMap`. It's nested a couple levels deep under a list of `schema.Resource`. When the api response has a value for that computed element and I set it in the Read method it should be set in state and subsequent `plan`'s should not show a diff.

### Actual Behavior
The field is getting correctly set in state, however on subsequent `plan` calls Terraform shows a diff that these fields need to be removed.

### Steps to Reproduce
The resource in question is [google_cloud_run_service](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_cloud_run_service.go). But since it's a complex resource I created a unit test that shows this behavior and opened a PR with it here: https://github.com/hashicorp/terraform/pull/24043

If the unit test isn't enough I'm happy to provide full debug logs as well.

### References

- PR with repro #24043
- Downstream issue https://github.com/terraform-providers/terraform-provider-google/issues/5587

**Comment by jbardin** [comment]
Hi @chrisst,

SDK issues should be filed directly in the https://github.com/hashicorp/terraform-plugin-sdk/ repo. This however is the desired behavior for this schema.

The `nested_resources` block is not `computed`, therefore the provider is not allowed to insert a value where there isn't one. The planned value for the resource looks like:

```
cty.ObjectVal(
  map[string]cty.Value{
    "computed_map":cty.UnknownVal(cty.Map(cty.String)),
    "id":cty.UnknownVal(cty.String), 
    "nested_resources":cty.ListValEmpty(cty.Object(map[string]cty.Type{"limits":cty.Map(cty.String)})), 
    "optional_map":cty.NullVal(cty.Map(cty.String))
  }
)
```

and the resource must apply the value which it recorded in the plan. If you look at the logs, you'll see a warning when the provider returns a different value after apply:

```
[WARN] Provider "test" produced an unexpected new value for test_resource_computed_map.foo, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .nested_resources: block count changed from 0 to 1
```

There are a number of edge cases that can't be handled in the legacy SDK right now, so we can't make these hard errors until a new SDK is released. 

The new value containing the unexpected `nested_resources` is initially saved to state after the apply step. When the new plan is generated, the same config is used which indicates that there should be no `nested_resources`, producing the same planned value above, and diff you see.

**Comment by chrisst** [comment]
Ok, so a nested `Computed` resource would need to have every field above it marked as `Computed` in order for it to have fields set after plan is done? If that's the case should that just be enforced rather than presenting the ability to create schemas which are prone to runtime failures? Though I'm guessing that would also be the job of the sdk rather than core.

**Comment by jbardin** [comment]
The SDK can’t enforce that, because it doesn’t know what the intent is. This is perfectly valid if only the attribute within the block is computed, the resource just can’t add the entire block if it isn’t in the config.

**Comment by jbardin** [comment]
Closing this since everything seems to be working correctly.
