### ISSUE TITLE
Working 0.11 code fails in 0.12 with "invalid count argument"

### ISSUE THREAD

**Issue by barnharts4** [hashicorp/terraform#24050]
### Terraform Version

```
Terraform v0.12.20
+ provider.null v2.1.2

```

### Terraform Configuration Files

```hcl
locals {
  expirydate    = "${timestamp()}"

  cost_attr_tags = {
    "cost1" = "value1"
  }

  base_tags = {
      "DSPApplication"       = "myApplication"

      # Comment me out and I work in TF 0.12.20
      "ExpiryDate"           = "${local.expirydate}"
  }

  # Switch the next two lines and I also work in TF 0.12.20
  all_tags = "${merge(local.base_tags, local.cost_attr_tags)}"
  #all_tags = "${local.base_tags}"
}


output "tags" {
  value = "${local.all_tags}"
}

data "null_data_source" "asg-tags" {
  count = "${length(keys(local.all_tags))}"

  inputs = {
    key                 = "${element(keys(local.all_tags), count.index)}"
    value               = "${element(values(local.all_tags), count.index)}"
    propagate_at_launch = "true"
  }
}

output "asg_tags" {
  value = "${data.null_data_source.asg-tags.*.outputs}"
}

```

### Expected Behavior

It should have outputted the two output fields as a list of tags, and then a list of maps of tags, as it does in TF 0.11.x

### Actual Behavior

```Error: Invalid count argument

  on barn.tf line 26, in data "null_data_source" "asg-tags":
  26:   count = "${length(keys(local.all_tags))}"

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
### Additional Context

If you look at the two lines in comments, you will see that you only have to do *ONE* of the two changes I reference.  Doing _either_ one makes it start working in 0.12.20.  So it appears to be some combination of using `timestamp()`, `merge()`, and `count`.

I have trimmed our real code down to the bare minimum to show the problem, so it might look silly that I am merging two static maps, but in our real code, there is a reason, since one of the maps has a variable number of entries.

**Comment by jbardin** [comment]
Thanks for filing the issue @barnharts4,

The problem here is that the `timestamp` function is "impure" meaning that it can only be calculated once with the same value, so we initially evaluate the function an "unknown". When the initial unknown result is fed into `merge`, that in turn returns an unknown value.

We have an open issue to enhance the `merge ` function here: #24024
