### ISSUE TITLE
File creation with EOF not working: lines cut and file created incompletely

### ISSUE THREAD

**Issue by Thomas999999** [hashicorp/terraform#24057]
Hi there,

Using remote-exec provisioner with EOF in order to create a file worked well since a while, but with a specific file and line it does not create the file correctly:

- File incompletely created:
line  "      args: [\"-c\", 'python -c \"import tensorflow as tf; print(tf.__version__);x=tf.placeholder(tf.float32,[None]);y=x*2; sess=tf.Session(config=tf.ConfigProto(log_device_placement=True)); print(sess.run(y,{x:[2,3]}))\"']",
cannot be added somehow, onlx the following string is in file:
" args: ["-c", python "

### Terraform Version
terraform version
Terraform v0.12.20
+ provider.google v3.7.0
+ provider.null v2.1.2.

### Terraform Configuration Files
snip:
...
    inline = [
            
      #block for gpu-workers config: add nvidia device plugin
      "sudo su - <<EOF",
      "kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml",
      "EOF",

      ###check GPU node: after that a pod called "slv-gpu-test" should have status COMPLETED, if not contact SLV keyusers
      "sudo bash -c 'cat <<EOF >/usr/local/bin/slv-gpu-test.yaml",
      "###provided by DI DEV",
      "###test yaml in order to check GPU worker node connection/availability, to be started from jumphost",
      "###created&started automatically during terraform runtime",
      "apiVersion: v1",
      "kind: Pod",
      "metadata:",
      "  name: slv-gpu-test",
      "spec:",
      "  restartPolicy: 'Never'",
      "  containers:",
      "    - name: cuda-container",
      "      image: tensorflow/tensorflow:1.4.0-gpu",
      "      resources:",
      "        limits:",
      "          nvidia.com/gpu: 1 # requesting 1 GPUs",
      "      command: [\"/bin/sh\"]",
      "      args: [\"-c\", 'python -c \"import tensorflow as tf; print(tf.__version__);x=tf.placeholder(tf.float32,[None]);y=x*2; sess=tf.Session(config=tf.ConfigProto(log_device_placement=True)); print(sess.run(y,{x:[2,3]}))\"']",
      "  nodeSelector:",
      "    kubernetes.io/hostname: [ \"google_container_node_pool.gpupool.instance.name\" ]",
      "EOF'",
      "kubectl apply -f /usr/local/bin/slv-gpu-test.yaml",

   ...
snap

### Expected Behavior
File slv-gpu-test.yaml shoulöd be created correctly

### Actual Behavior
File is created incompletey:

[root@d021970gpu1-jumphost bin]# cat slv-gpu-test.yaml
###provided by DI DEV
###test yaml in order to check GPU worker node connection/availability, to be started from jumphost
###created&started automatically during terraform runtime
apiVersion: v1
kind: Pod
metadata:
  name: slv-gpu-test
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: tensorflow/tensorflow:1.4.0-gpu
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
      command: ["/bin/sh"]
      args: ["-c", python

File ends with incomplete args line...

### Steps to Reproduce
snip:
....
google_container_node_pool.gpupool: Creation complete after 1m54s [id=projects/sap-p-and-i-iqs-eval/locations/europe-west1-b/clusters/d021970gpu1/nodePools/gpupool]
null_resource.gke_jump: Creating...
null_resource.gke_jump: Provisioning with 'remote-exec'...
null_resource.gke_jump (remote-exec): Connecting to remote host via SSH...
null_resource.gke_jump (remote-exec):   Host: 104.155.80.239
null_resource.gke_jump (remote-exec):   User: emroot
null_resource.gke_jump (remote-exec):   Password: false
null_resource.gke_jump (remote-exec):   Private key: true
null_resource.gke_jump (remote-exec):   Certificate: false
null_resource.gke_jump (remote-exec):   SSH Agent: false
null_resource.gke_jump (remote-exec):   Checking Host Key: false
null_resource.gke_jump (remote-exec): Connected!
null_resource.gke_jump: Still creating... [10s elapsed]
null_resource.gke_jump (remote-exec): Last login: Fri Feb  7 11:14:48 UTC 2020
null_resource.gke_jump: Still creating... [20s elapsed]
null_resource.gke_jump (remote-exec): daemonset.apps/nvidia-driver-installer configured
null_resource.gke_jump (remote-exec): -c: line 17: warning: here-document at line 0 delimited by end-of-file (wanted `EOF')
null_resource.gke_jump (remote-exec): error: error parsing /usr/local/bin/slv-gpu-test.yaml: error converting YAML to JSON: yaml: line 17: did not find expected ',' or ']'

Error: error executing "/tmp/terraform_1392836749.sh": Process exited with status 1

**Comment by jbardin** [comment]
Hi @Thomas999999,

I'm not exactly sure why you're getting the exact output your'e seeing here, but I wouldn't expect this to work because each `inline` argument is sent as a separate command to the shell. It would be much easier to manage this in a single shell script rather than using the `inline` argument. 

Since this is entirely dependent on the remote shell parsing the command, there's not much terraform can do here so we're going to close this out. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
