### ISSUE TITLE
`terraform destroy` doesn't initialize provider correctly if it's using data source

### ISSUE THREAD

**Issue by bkabrda** [hashicorp/terraform#24055]
### Terraform Version

```
Terraform v0.12.20
+ provider.datadog v2.6.0
+ provider.local v1.4.0
```

### Terraform Configuration Files
```hcl
data "local_file" "api" {
  filename="api"
}

data "local_file" "app" {
  filename="app"
}

provider "datadog" {
    api_url = "https://api.datadoghq.com"
    api_key = trimspace(data.local_file.api.content)
    app_key = trimspace(data.local_file.app.content)
}

# Create a new Datadog monitor
resource "datadog_monitor" "foo" {
  name               = "Name for monitor foo"
  type               = "metric alert"
  message            = "Monitor triggered. Notify: @hipchat-channel"

  query = "avg(last_1h):avg:aws.ec2.cpu{environment:foo,host:foo} by {host} > 4"

  thresholds = {
    warning           = 3
    critical          = 4
  }

  new_host_delay = 300

  tags = ["foo:bar", "baz"]
  notify_no_data = true
}
```

### Debug Output
https://gist.github.com/bkabrda/c565ac6677167f8c43b103691b985c5c

### Crash Output
N/A

### Expected Behavior
Should have passed without an error

### Actual Behavior
```
Plan: 0 to add, 0 to change, 0 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes


Error: Invalid or missing credentials provided to the Datadog Provider. Please confirm your API and APP keys are valid and see https://terraform.io/docs/providers/datadog/index.html for more information on providing credentials for the Datadog Provider

  on example.tf line 10, in provider "datadog":
  10: provider "datadog" {
```

### Steps to Reproduce

1. `terraform init`
2. `terraform destroy`

### Additional Context

This seems to only occur when there is at least one resource defined in the terraform config, but the terraform statefile is empty.

### References

This happened to a user of Datadog Provider who initializes the provider with values from Amazon SSM data source: https://github.com/terraform-providers/terraform-provider-datadog/issues/360#issuecomment-582450080

**Comment by jbardin** [comment]
The method for handling dependencies during destroy has been improved significantly since 0.13, and I have confirmed this is working in the latest 0.14 release.

Thanks!
