### ISSUE TITLE
Terraform cloud - Organization-level global variables

### ISSUE THREAD

**Issue by binaryfire** [hashicorp/terraform#24068]
Hi all,

It would be great if we could have organization-level global variables which could be used in all workspaces in that organization. This would be very useful for things like IaaS API tokens, which currently have to be duplicated into every workspace. This isn't very intuitive and makes maintenance difficult because we have to update these variables in multiple locations if they change.

These global variables would live in a new menu: Organization -> Variables

**Comment by pkolyvas** [comment]
Thanks for the feedback @binaryfire.

I've passed this feedback onto the Terraform Cloud team. As this is the repo for the Terraform OSS tool, I'll close this issue out.

Before I do, as a workaround, I should mention that you can use the TFC Provider to inject variables across a number of workspaces. It's what I do when I want to setup an organization.

In the example below, I'm adding the same AWS credentials to every workspace.

Here's my `main.tf` file:
```hcl
# Provider setup
provider "tfe" {
  hostname = "app.terraform.io"
}

resource "tfe_workspace" "my_workspace" {
  for_each     = var.workspaces
  name         = each.value
  organization = var.my_org_name
  lifecycle {
    prevent_destroy = true
  }
}

resource "tfe_variable" "aws_key_id" {
  for_each     = var.workspaces
  key          = "AWS_ACCESS_KEY_ID"
  value        = var.my_aws_key_id
  category     = "env"
  workspace_id = tfe_workspace.my_workspace[each.key].id
}

resource "tfe_variable" "aws_key" {
  for_each     = var.workspaces
  key          = "AWS_SECRET_ACCESS_KEY"
  value        = var.my_aws_access_key
  category     = "env"
  sensitive    = true
  workspace_id = tfe_workspace.my_workspace[each.key].id
}
```

My `variables.tf` file:
```hcl
# Variables for my plan
variable "my_aws_key_id" {
  type        = string
  description = "AWS Access key id"
}

variable "my_aws_access_key" {
  type        = string
  description = "AWS key"
}

variable "my_org_name" {
  type        = string
  description = "My organization's name"
}

variable "my_org_email" {
  type        = string
  description = "My organizaton's email"
}

variable "workspaces" {
  type        = map
  description = "Workspaces list"
}
```

My `terraform.tfvars` file:
```hcl
my_org_email = "petros+varsdemo@hashicorp.com"

my_org_name = "tf-org-vars-demo"

workspaces = {
  zones                   = "Prod_Route53_Zones"
  networking              = "Prod_Networking"
  certs                   = "Prod_Certificates"
  app_a_domains           = "Prod_Domains_App_A"
  app_a_resources         = "Prod_Resources_App_A"
  app_b_domains           = "Prod_Domains_App_B"
  app_b_domains_resources = "Prod_Resources_App_B"
  app_c_domains           = "Prod_Domains_App_C"
  app_c_resource          = "Prod_Resources_App_C"
}
```

Some variation on this may help get you halfway there in the mean time.
