### ISSUE TITLE
Azurerm provider not recognizing environment parameter

### ISSUE THREAD

**Issue by LHGDevOps** [hashicorp/terraform#24089]
In the tf file:
provider "azurerm" {
  version     = "=1.43.0"
  environment = **"usgovernment"**
}

From Debug log:
2020/02/12 17:16:50 [TRACE] Meta.Backend: moving from default local state only to "azurerm" backend
2020/02/12 17:16:50 [DEBUG] Loading Environment **"public"**

I have attempted to change environment to each of those documented with the same outcome.
It **does** recognize the environment using the bash environment variable: ARM_ENVIRONMENT

**Comment by LHGDevOps** [comment]
Additional Details:
Terraform version: 0.12.20
Running on linux vm under same subscription as build environment
When run under Cloud Shell getting authentication errors, thus moved to small vm.
Does run successfully in public cloud - which is not much help.
Connected to Azure Gov through Az cli (ver. 2.0.81) prior to running terraform init

**Comment by BellaLi** [comment]
The other customer confirmed that it's fixed. Please refer to:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/5302
