### ISSUE TITLE
aws_route53_zone data resource falsely returns no matching Route53Zone found

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform#24082]
### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.48.0
+ provider.null v2.1.2
+ provider.template v2.1.2

```

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = var.aws_region
  version = "~> 2.48"
}

data "aws_route53_zone" "internal" {
  name         = var.environment == "qa" ? "qa.redacted.domain.com." : "redacted.domain.com."
  tags         = map("view", "internal")
  private_zone = false
}

```

### Expected Behavior
`terraform plan` should have run successfully

### Actual Behavior
terraform threw the error:

```
Error: no matching Route53Zone found

  on data.tf line 19, in data "aws_route53_zone" "internal":
  19: data "aws_route53_zone" "internal" {
```

### Steps to Reproduce

1. In a separate repo, we created separate Route53 Hosted Zones for prod and qa. Each zone was tagged appropriately and attributes set such that the above data resource described above indeed matches a unique zone. We verified such query with the aws cli successfully.
2. Run `terraform plan` with aws provider v2.48.0 and v2.47.0

### Additional Context

The error only manifests with v2.48.0 and not with v2.47.0

**Comment by bflad** [comment]
Please note that this issue is with the Terraform AWS Provider and the fix (https://github.com/terraform-providers/terraform-provider-aws/pull/11953) has been merged for release with version 2.49.0 on Thursday this week. 👍
