### ISSUE TITLE
Setting AWS IAM password requires a keybase invite

### ISSUE THREAD

**Issue by mabushey** [hashicorp/terraform#24081]
I love, love, love Terraform, but what is going on with the aws_iam_user_login_profile resource? It requires a proprietary keybase account!?!  I installed the keybase app and it requires an invite. I need an invite to use a Terraform AWS resource. WTF??????

Please remove this proprietary nonsense.

Thanks,
Michael

**Comment by jbardin** [comment]
Hi @mabushey,

That resource looks like it has an attribute that requires pgp public key. It has the ability to lookup a public key via keybase, but should not require it. 

If there is a problem using a regular pgp public key, please file an issue with the example configuration and reproduction steps with the [AWS Provider](https://github.com/terraform-providers/terraform-provider-aws)

Thanks!
