### ISSUE TITLE
Error: leftover module in state

### ISSUE THREAD

**Issue by rmalchow** [hashicorp/terraform#24099]
### Terraform Version
```
 $ terraform --version
 Terraform v0.12.19
```

### Terraform Configuration Files

we have seen this in several situations. mainly when some 2nd-level module has been removed. in this case, we changed the way that the bucket name was constructed as follows:

```hcl

=====================
[ROOT]
module "s3_stage_assets" {
   source = [s3_module]
}

=====================
OLD [s3_module]  
...
module "s3_hostnames" {
    source = [hostname_module]
   // some params
}

resource "aws_s3_bucket" "bucket" {
    name = modules.s3_hostnames.name
}

=====================

NEW [s3_module]  
...
variable "bucket_name" {}

resource "aws_s3_bucket" "bucket" {
    name = var.bucket_name
}
=====================
```

### Crash Output
Error: leftover module module.s3_stage_assets.module.s3_hostnames in state that should have been removed; this is a bug in Terraform and should be reported

### Expected Behavior
module should be removed from the state.

### Actual Behavior
module is kept in the state

**Comment by jbardin** [comment]
Hi @rmalchow,

This issue was fixed in the 0.12.20 release.
