### ISSUE TITLE
Empty optional nested block crashes Terraform.

### ISSUE THREAD

**Issue by kubiak95** [hashicorp/terraform#24098]
### Terraform Version
```
Terraform v0.12.20
```

### Terraform Configuration Files

```hcl
provider "artifactory" {
  url = [REDACTED]
  api_key  = [REDACTED TOO]
}

resource "artifactory_permission_target" "permission_target" {

  name = "test-permission-target"

  repo {
    excludes_pattern = [ "npm/**" ]
    includes_pattern = [ "pypi/**" ]
    repositories = [ "test-repo" ]

    actions {
    }
  }
}
```

### Debug Output
https://gist.github.com/kubiak95/550567f7cf10073c656bdebdc7a20bd1

### Crash Output
https://gist.github.com/kubiak95/6a4a17d790604126bf5ca3fb1ad602ff

### Expected Behavior
Either:
1. Terraform returning an error and exiting 'gracefully', considering it's aware of potential causes e.g.:
```
The following problems may be the cause of any confusing errors from downstream operations:
- .includes_pattern: planned value cty.StringVal("**") does not match config value cty.NullVal(cty.String)
- .repo[0].actions[0].groups: attribute representing a set of nested blocks must be empty to indicate no blocks, not null
- .repo[0].actions[0].users: attribute representing a set of nested blocks must be empty to indicate no blocks, not null
```
and 
```
interface conversion: interface {} is nil, not map[string]interface {}
```

Or 

2. Terraform doing absolutely nothing with the empty `actions` block and moving on, although I suspect that might be more related to the provider.

### Actual Behavior

Terraform panics and crashes.

### Steps to Reproduce

Provided you have Artifactory instance to test against:
1. Install terraform-provider-artifactory 2.0.0-alpha1 from https://github.com/atlassian/terraform-provider-artifactory/releases
2. Create a config file like the one shown above with an empty `actions` block.
3. terraform init
4. terraform apply

### Additional Context

So you might ask _'Why are you supplying an empty `actions` block with no values? Just don't put it there if it's empty! What's wrong with you?'_

This crash is an outcome of me playing with dynamic blocks like so:

```hcl
actions {
  dynamic "users" {
    for_each...
    }
  }
}
```
If I don't specify any users or groups, the result is an empty `actions` block. I will get around this by making `actions` dynamic as well, but ultimately Terraform crashed so I'm reporting it.

### References
Other similar issues, suggesting that it might not entirely be down to the provider I'm using:

- #22167
- #23784 
- #23992

**Comment by jbardin** [comment]
Hi @kubiak95,

Thanks for raking the time to file and issue. This is a crash in the artifactory provider, not in terraform itself. Since this isn't a provider we manage, I can't transfer the issue automatically, but please feel free to file a new issue with that provider specifically.
