### ISSUE TITLE
Crash in PlanResourceChange

### ISSUE THREAD

**Issue by thnee** [hashicorp/terraform#24093]
### Terraform Version

```
Terraform v0.12.12
```

https://gist.github.com/thnee/2155a68405c4db6737b5f161551d969d

### Steps to Reproduce
1. `terragrunt apply`

### Additional Context

Using terragrunt on GCP. Exact same code works fine in one project/environment, but crashes in another, with only very small differences in config between them.

### References

I guess this is similar, but not the same?

hashicorp/terraform#23088

**Comment by paultyng** [comment]
Sorry I think this issue got caught up in some transfers and ended up on a repo that was not the appropriate target. Going to send it to the GCP provider.
