### ISSUE TITLE
Cycle Incorrectly Detected During Destroy

### ISSUE THREAD

**Issue by JayThomason** [hashicorp/terraform#24121]
Terraform incorrectly detects a cycle during `terraform delete` when setting the aws provider access key id and secret key to values from another terraform workspace via data.terraform_remote_state.

### Terraform Version
```
Terraform v0.12.20
+ provider.aws v2.48.0
```

Note: terraform is running in terraform cloud and the version there is also set to v0.12.20.

### Terraform Configuration Files

```hcl
terraform {
  backend "remote" {
    organization = "my-org"
    workspaces {
      name = "workspace-a"
    }
  }
}

data "terraform_remote_state" "core" {
  backend = "remote"
  config = {
    organization = "my-org"
    workspaces = {
      name = "workspace-b"
    }
  }
}

locals {
  access_key = data.terraform_remote_state.core.outputs.terraform_admin_access_key
  secret_key = data.terraform_remote_state.core.outputs.terraform_admin_secret_key
  subnet_cidr_block = "10.0.10.0/24
  subnet_azs = "us-east-1a"
}

provider "aws" {
  region = "us-east-1"
  access_key = local.access_key
  secret_key = local.secret_key
}

resource "aws_subnet" "test_subnet" {
  vpc_id = "my-vpc-id"
  cidr_block = local.subnet_cidr_block
  availability_zone = local.subnet_az
}
```

### Debug Output
When running `terraform destroy -auto-approve`:
```
Running apply in the remote backend. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

To view this run in a browser, visit:
...

Waiting for the plan to start...

Terraform v0.12.20
Configuring remote state backend...
Initializing Terraform configuration...
2020/02/14 20:33:27 [DEBUG] Using modified User-Agent: Terraform/0.12.20 TFC/a2ec22b07b
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.core: Refreshing state...
aws_subnet.test_subnet: Refreshing state... [id=...]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # aws_subnet.test_subnet will be destroyed
  - resource "aws_subnet" "test_subnet" {
      - arn                             = "..." -> null
      - assign_ipv6_address_on_creation = false -> null
      - availability_zone               = "us-east-1a" -> null
      - availability_zone_id            = "use1-az1" -> null
      - cidr_block                      = "10.0.10.0/24" -> null
      - id                              = "..." -> null
      - map_public_ip_on_launch         = false -> null
      - owner_id                        = "..." -> null
      - tags                            = {} -> null
      - vpc_id                          = "..." -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.


Error: Cycle: local.secret_key, local.access_key, provider.aws, aws_subnet.test_subnet (destroy), data.terraform_remote_state.core (destroy)
```

### Crash Output
Terraform does not crash, just outputs the above cycle error.

### Expected Behavior
Terraform should have properly destroyed the resource.

### Actual Behavior
Terraform incorrectly detected a cycle and failed to destroy the resource.

### Steps to Reproduce
1. Create a terraform workspace which creates an AWS IAM user with and outputs the user access key id and secret key.
2. Create a new terraform workspace, put the above snippet in it as main.tf, filling in the my-org, my-vpc-id, and workspace-a/workspace-b fields with the correct names.
3. Run `terraform apply` in the new workspace.
4. Run `terraform destroy` in the new workspace.
5. Note that out the secret_key and access_key_id lines in the provider block (and setting the corresponding environment variables in terraform cloud) allows `terraform destroy` to work properly.

### Additional Context

Terraform is running with the terraform cloud remote backend.

There must be another workspace that outputs the access_key_id and secret_key for an IAM user that has ec2/vpc permissions.

### References

This may be related to this ticket: https://github.com/hashicorp/terraform/issues/9653.

**Comment by jbardin** [comment]
Confirmed that this is fixed in master, and will included in the next major release.

**Comment by danieldreier** [comment]
[Terraform 0.13.0 beta 1 launched today](https://github.com/hashicorp/terraform/issues/25016), and you're welcome to confirm the issue you reported is fixed in it. If it isn't, please feel free to file a new issue or reach to to me (ddreier@hashicorp.com) and I can re-open this one.
