### ISSUE TITLE
Support AWS SSO login

### ISSUE THREAD

**Issue by valorl** [hashicorp/terraform#24133]
### Use-cases
AWS CLI v2 now supports `aws sso login` which allows you to temporarily acquire a token by logging in with SSO credentials. This way, companies already using SSO do not need to provision additional IAM users for programmatic access. 

Terraform doesn't seem to handle this properly. Could it be implemented so that Terraform can reuse the token acquired during `aws sso login` ?

**Comment by aibou** [comment]
The topic seems to be discussed in https://github.com/terraform-providers/terraform-provider-aws/issues/10851.
Could you please confirm it and please vote `:+1:`! 😃

**Comment by valorl** [comment]
@aibou You're right. Should have looked in the provider repo :) Closing this in favor of https://github.com/terraform-providers/terraform-provider-aws/issues/10851
