### ISSUE TITLE
Custom variable validation error despite enabling experiment

### ISSUE THREAD

**Issue by Nevon** [hashicorp/terraform#24147]
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.12"
  experiments      = [variable_validation]
}

# The Kafka module is using custom variable validation
module "kafka" {
  source      = "../../../modules/confluent-cloud/kafka"
}
```

### Expected Behavior

I should see a **warning** that I'm using an experimental feature, but no error. Something like:

```
Warning: Experimental feature "variable_validation" is active

  on prod.tf line 28, in terraform:
  28:   experiments      = [variable_validation]

Experimental features are subject to breaking changes in future minor or patch
releases, based on feedback.

If you have feedback on the design of this feature, please open a GitHub issue
to discuss it.
```

### Actual Behavior

I do get the warning as shown above.

But I **also get an error** saying the following:

```
Error: Custom variable validation is experimental

  on ../../modules/confluent-cloud/kafka/variables.tf line 86, in variable "topics":
  86:   validation {

This feature is currently an opt-in experiment, subject to change in future
releases based on feedback.

Activate the feature for this module by adding variable_validation to the list
of active experiments.
```

**Comment by grimm26** [comment]
try putting the `  experiments      = [variable_validation]` in your kafka module, not at root.  That's what works for me.

**Comment by Nevon** [comment]
Tried that as well. Had the same issue. Maybe it's because I'm sourcing the module from another directory? Doing this didn't work:

```hcl
module "kafka" {
  experiments = [variable_validation]
  source      = "../../../modules/confluent-cloud/kafka"
}
```

**Comment by grimm26** [comment]
no, put the experiments setting in a terraform{} block in a file in your module.

**Comment by apparentlymart** [comment]
Hi @Nevon!

@grimm26 is correct: experiments are enabled on a module-by-module basis, so the `terraform` block containing the `experiments` argument must be in the same module that contains the validations.

For example, in your `../../modules/confluent-cloud/kafka` module:

```hcl
terraform {
  experiments = [variable_validation]
}

variable "topics" {
  # ...

  validation {
    # ...
  }
}
```

**Comment by Nevon** [comment]
Ah, gotcha! Took me a little bit to figure out that the `terraform { experiments ... }` block has to be in the same file as the variable declaration. I initially put it in the `main.tf` of the module, which didn't work, but once I put it in the `variables.tf` where I declare the variables and their validation, it worked.

Thanks for the support!
