### ISSUE TITLE
Destination state file resulting from `state mv` becomes formatted incorrectly

### ISSUE THREAD

**Issue by Tomesco** [hashicorp/terraform#24168]
A functioning state file, after being the destination of a `state mv` command, becomes unusable and returns the error:

```
Error: Failed to load state: Terraform 0.12.20 does not support state version 4, please update.
```

### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.49.0
```

### Steps to Reproduce

```shell
terraform init # pwd old-state-key
cd ./new-state-key && terraform init && terraform plan # Successful plan 
cd ..
terraform state mv -state-out=./new-state-key/.terraform/terraform.tfstate module.this module.this # Successfully moved 1 object(s).
terraform state list # module.this is gone
cd ./new-state-key && terraform plan # Error: Failed to load state: Terraform 0.12.20 does not support state version 4, please update.
```

### Terraform Configuration Files

I have removed some keys that I do not believe relevant. The state file I am moving to is identical except for an updated key.

```hcl
provider "aws" {
  version = "~> 2.19"
}

terraform {
  backend "s3" {
    bucket  = "state"
    key     = "old-state-key"
  }
}

data "terraform_remote_state" "this" {
  ...
}

module "this" {
  ...
}
```

### Debug Output

Debug for `terraform state mv` encrypted [here](https://gist.github.com/Tomesco/42bdd4e2f4f995c125c5cac6aa149a88).

Short debug below for `terraform plan`.

```
2020/02/19 14:42:18 [INFO] Terraform version: 0.12.20
2020/02/19 14:42:18 [INFO] Go runtime version: go1.12.13
2020/02/19 14:42:18 [INFO] CLI args: []string{"/Users/.../terraform/0.12.20/bin/terraform", "plan"}
2020/02/19 14:42:18 [DEBUG] Attempting to open CLI config file: /Users/.../.terraformrc
2020/02/19 14:42:18 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/02/19 14:42:18 [INFO] CLI command args: []string{"plan"}
2020/02/19 14:42:18 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 542975631

Error: Failed to load state: Terraform 0.12.20 does not support state version 4, please update.
```

**Comment by jbardin** [comment]
Hi @Tomesco 

It looks like you've attempted to modify a `.terraform/terraform.tfstate` file. The `.terraform` directory is where terraform stores configuration and is not meant to be accessed outside of terraform itself. In particular, the `.terraform/terraform.tfstate` does not contain your configuration state, it's the storage for the cli and backend configuration, but for legacy purposes it's still named `terraform.tfstate` and uses an older file format. 

Writing your modified state to any path outside of `.terraform` should work as expected.
