### ISSUE TITLE
Terraform in AWS EKS v1.14 doesn't switch to expected fine-grained role

### ISSUE THREAD

**Issue by chroche** [hashicorp/terraform#24165]
### Terraform Version
```
Terraform v0.12.20
+ provider.aws v2.49.0
```

### Terraform Configuration Files
```hcl
terraform {

  required_version = ">= 0.12"
  backend "s3" {
    region         = "us-east-1"
    key            = "terraform/us-east-1/bootstrap.tfstate"
    acl            = "bucket-owner-full-control"
    dynamodb_table = "usage-tflocktable"
  }
}

provider "aws" {
  version             = "~> 2"
  region              = var.aws_region
  allowed_account_ids = [ var.aws_account ]
}
```

Terraform runs in an AWS EKS v1.14 container configured with [fine-grained IAM roles](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/)
```bash
AWS_ROLE_ARN=arn:aws:iam::12345678:role/usage-util-eks-nonprod-jenkins-agent-terraform
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
````
The `token` file is accessible by user `jenkins`:
```bash
> id
uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins)
>  ls -la /var/run/secrets/eks.amazonaws.com/serviceaccount/..2020_02_19_15_28_53.365026870/token
-rw-r-----    1 root     jenkins       1012 Feb 19 15:28 /var/run/secrets/eks.amazonaws.com/serviceaccount/..2020_02_19_15_28_53.365026870/token
```
The role switch happens as expected when running the AWS CLI:
```bash
> aws sts get-caller-identity
{
    "UserId": "AROAXYZ:botocore-session-1582133116",
    "Account": "12345678",
    "Arn": "arn:aws:sts::12345678:assumed-role/usage-util-eks-nonprod-jenkins-agent-terraform/botocore-session-1582133116"
}
```
### Debug Output

Cf [this gist](https://gist.github.com/chroche/23d7c08b1f26842ad774392207011813)

The problematic part is this one:
```
2020/02/19 17:31:15 [DEBUG] [aws-sdk-go] <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
    <Arn>arn:aws:sts::12345678:assumed-role/usage-util-eks-nonprod.worker-node-role/i-083fb7a9e23d850b8</Arn>
    <UserId>AROAXYZ:i-083fb7a9e23d850b8</UserId>
    <Account>12345678</Account>
  </GetCallerIdentityResult>
  <ResponseMetadata>
    <RequestId>9819de5e-5136-4c4b-baec-56cb538eaa07</RequestId>
  </ResponseMetadata>
</GetCallerIdentityResponse>
````
which shows that Terraform did not switch to fine-grain role `usage-util-eks-nonprod-jenkins-agent-terraform` as expected but used the EC2 host role `usage-util-eks-nonprod.worker-node-role` instead.

### Expected Behavior

`terraform init` should complete successfully.

### Actual Behavior

Terraform fails to switch to the proper role, uses the EC2 host role instead and fails to read from S3 since this role doesn't have the proper permissions:
```bash
Error refreshing state: AccessDenied: Access Denied
  status code: 403, request id: FF797E037EBC91E7, host id: 1gfaELzFK9kwL9X/LSah/ZHweaBxVkuCUr51IME4+cu1tA
```

### Additional Context

Terraform running in a Docker container in an AWS EKS v1.14 cluster using the fine-grained IAM roles feature.

**Comment by guidoffm** [comment]
This is because an outdated AWS SDK is used: #24480

**Comment by bflad** [comment]
Hi folks 👋  This should be fixed in the Terraform S3 Backend as of Terraform 0.13.0-beta2. Similar changes in the Terraform AWS Provider will occur in 3.0.0, releasing in a few weeks. If you are still having trouble after these versions, please file new issues. Thanks!
