### ISSUE TITLE
aws_dynamodb_table_item is not working

### ISSUE THREAD

**Issue by imortkz** [hashicorp/terraform#24173]
I'm using official examples which not works for me:

Terraform v0.12.20
+provider.aws v2.49.0

### Terraform Configuration Files
```
resource "aws_dynamodb_table_item" "example" {
  table_name = "${aws_dynamodb_table.example.name}"
  hash_key = "${aws_dynamodb_table.example.hash_key}"
  item = <<ITEM
{
  "exampleHashKey": {"S": "something"},
  "one": {"N": "11111"},
  "two": {"N": "22222"},
  "three": {"N": "33333"},
  "four": {"N": "44444"}
}
ITEM
}

resource "aws_dynamodb_table" "example" {
  name = "example-name"
  read_capacity = 10
  write_capacity = 10
  hash_key = "exampleHashKey"

  attribute {
    name = "exampleHashKey"
    type = "S"
  }
}
```

### Debug output

```
Error: Error retrieving DynamoDB table item: ValidationException: The provided key element does not match the schema
        status code: 400, request id: <request_id>
```

### Expected Behavior

DynamoDB table and item created.

### Actual Behavior

Validation error.

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by VincentHokie** [comment]
@imortkz did you figure out the issue here? I'm hitting this same issue

**Comment by arekkulczycki** [comment]
I had the same issue, but seems to work after I added the range_key to the resource.

`resource "aws_dynamodb_table_item" "example-item" {
  table_name = aws_dynamodb_table.example-table.name
  hash_key   = aws_dynamodb_table.example-table.hash_key
  range_key  = aws_dynamodb_table.example-table.range_key

  item = <<EOF
{
...
}
EOF
}`

**Comment by VincentHokie** [comment]
Yup, thanks. I found this out only after a lot of painful hours trying to understand the error and then looking at the resource tests on the repo. That's definitely not clear from the docs.
