### ISSUE TITLE
var null is double quoted

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#24180]
### Terraform Version
```
Terraform v0.12.21
```

### Terraform Configuration Files
```hcl
variable "my_var" {
  description = "some var"
  type        = string
}

output my_var {
	value = var.my_var
}

variable "my_var_default" {
  description = "some var with a default"
  type        = string
  default     = null
}

output my_var_default {
	value = var.my_var_default
}
```

### Debug Output
```hcl
Outputs:

my_var = {
  "my_var" = "null"
  "my_var_default" = null
```

### Expected Behavior
if calling  a module with a non defaulted var, and the value passed is `null`, it should result in `null` 

### Actual Behavior
value and output of var with `null` is `"null"` (double quoted)

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
this forces all chain of modules to have a default of `null` so that the value is always `null`, but that prevents the var from being required!

**Comment by jbardin** [comment]
Hi @FernandoMiguel 

Thanks for filing the issue. Can you show the complete configuration and steps you've used to get the output shown? Running this example as-is in both the root module and as a sub-module produces no value for `my_var_default`.

**Comment by FernandoMiguel** [comment]
@jbardin i tried to create a repro with the linux version but cant reproduce
https://github.com/FernandoMiguel/terraform-24180

i'll have to try again from mac / terragrunt.

closing for now, will reopen when i have further details
