### ISSUE TITLE
More granular exit code for terraform plan

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#2418]
This is a followup on https://github.com/hashicorp/terraform/pull/1355 which probably works ok for most use-cases.

I'd like to be able to differentiate between state where no resource exists (i.e. all resources in plan are green, having `+` prefix) and where some resources exist (i.e. some resources scheduled for destruction, change or add).

Would there be interest in such change?

**Comment by radeksimko** [comment]
cc @ryanuber

**Comment by ryanuber** [comment]
Interesting idea, what is the use case? If it is generally helpful then I don't see why not. The only thing is that this will likely break things that currently depend on the current 0/1/2 exit code range. I know we use it internally, but not sure if others are using it in the wild.

**Comment by radeksimko** [comment]
Let's say I have an app consisting of AWS ASG & launch configuration etc. and I version that in git, then I use Terraform to deploy this app and I want to be able to deploy/destroy each version (i.e. git hash).

I store state for each version in S3 currently, which means I could eventually just list all existing state files:
```
s3://terraform-state/my-app/hash-1.tfstate
s3://terraform-state/my-app/hash-2.tfstate
s3://terraform-state/my-app/hash-3.tfstate
```
but that doesn't really tell me what is truly "deployed", because state file will exist even if I just run `terraform plan` or when I created and then destroyed everything.

I would like to be able to see the difference between apps that have no resources at all and apps that are only waiting for some tiny changes, because someone has changed some resources manually, `refresh` detected such changes and terraform only wants to fix it.

I guess this could be useful for you in Atlas too.

**Comment by radeksimko** [comment]
If this turns out to be a no-go, I think https://github.com/hashicorp/terraform/issues/2355 will do for me.

**Comment by mitchellh** [comment]
Its been almost 18 months and there hasn't been a strong request for this. I think I'm going to just close it as a "wontfix." I think the currently available exit codes are good enough and for more complicated behaviors we should just look into how to make plan files themselves introspectable with JSON output or something.
