### ISSUE TITLE
Terraform crashes when applying mysql grants.

### ISSUE THREAD

**Issue by T0MM0R** [hashicorp/terraform#24183]
### Terraform Version

```
0.12.2
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

https://gist.github.com/T0MM0R/76a25f6a0f7137908ada058a179641d4

**Comment by jbardin** [comment]
Hi @T0MM0R,

Thanks for the crash report. Could you please share the configuration or steps  used that triggers this?

**Comment by T0MM0R** [comment]
@jbardin You can close this.  I discovered it was because we're injecting credentials using a python script inside of a docker container and the credentials file wasn't being persisted between the plan and apply commands.  Not sure if a better error message could be printed for a bad credentials file though might be helpful.
