### ISSUE TITLE
Variable interpolation interpreted as string not as variable

### ISSUE THREAD

**Issue by Nornode** [hashicorp/terraform#24181]
### Terraform Version

```
Terraform v0.12.20
& 
Terraform v0.12.21
```

### Terraform Configuration Files

```hcl
terraform {
  backend "gcs" {}
  required_version = ">= 0.12"
  required_providers {
    google = "=2.20.0"
  }
}
```

When two variables are interpolated it will be interpreted as a string value and does not resolve to the actual variable value.

```hcl
resource "google_compute_firewall" "allow-all-to-spoke" {
  project                 = "${var.dataRemoteStatePath}${var.hubProjectName}"
  ...
  ...
}
```
### Plan Output

```hcl
  # google_compute_firewall.allow will be created
  + resource "google_compute_firewall" "allow" {
      + creation_timestamp = (known after apply)
      + destination_ranges = [
          + "...",
        ]
      + project            = "data.terraform_remote_state.hub-project.outputs.output_projectId.Dev1"
     ...
    ...
    }
```

### Expected Behavior
Hardcoding the variable like this:

```hcl
resource "google_compute_firewall" "allow-all-to-spoke" {
  project                 = data.terraform_remote_state.hub-project.outputs..... 
```
will resolve the variable

### Actual Behavior

The two variables resolves and will be presented as a string value that will fail:
```hcl
 # google_compute_firewall.allow-all-to-spoke will be created
  + resource "google_compute_firewall" "allow-all-to-spoke" {
      ...
      + project            = "data.terraform_remote_state.hub-project.outputs.xxx."
```

```
google_compute_firewall.allow-all-to-spoke: Creating...

Error: Error creating Firewall: googleapi: Error 400: Invalid value 'data.terraform_remote_state.hub-project.outputs.xxx. Values must match the following regular expression: '(?:(?:[-a-z0-9]{1,63}\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))', invalidParameter
```

### Steps to Reproduce

1. Define two variables
2. Interpolate the two so you can use them in a resource definition
3. Plan and see if that sum of your two variables gets interpreted as a string or if it will in turn also resolve to the variable you built.

**Comment by jbardin** [comment]
Hi @Nornode 

I'm guessing that the value for `var.dataRemoteStatePath` is a string value `"data.terraform_remote_state.hub-project.outputs"`. If that's the case, then the string value in the plan is what would be expected, because strings are not evaluated as references themselves. 

If you have a config than can reproduce this using correct references, then feel free to reply and we can reopen this. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help if you have further questions.

**Comment by Nornode** [comment]
Yeah, either you are on the point and this is more of a user error, but I think this is a valid use-case.

I need to define both project_id and network in the remote state in order to allow traffic to the local project after peering the two networks.

What I want to achieve is this:

```hcl
  # google_compute_firewall.allow-all-to-spoke will be created
  + resource "google_compute_firewall" "allow-all-to-spoke" {
     ....
      + project            = "pahub-dev1-xxxxxxx"
```

From this definition:

```hcl
resource "google_compute_firewall" "allow-all-to-spoke" {
  project                 = "${var.dataRemoteStatePath}${var.hubProjectName}"
```

variable _var.dataRemoteStatePath_ states only the part of the path for the output which may be different between deployments
variable _var.hubProjectName_ is obviously different between different deployments.



This particular issue might be able to get solved by adjusting the outputs in the source state, however, when defining which VPC & and subnet ranges that are created and stored in the remote state this get way more tricky and this interpolation of two variables into one is pretty much required to get it working.

In definition for spoke project creation:
```hcl
  project                 = "${var.dataRemoteStatePath}${var.hubProjectName}"
  name                    = lower( "allow-all-to-${element( var.projectName, 0 )}" )
  network                 = "${var.dataRemoteStatePath}${var.hubVpcName}" 
  destination_ranges      = var.spoke01_subnet
  direction               = "EGRESS"

  allow {
    protocol              = "icmp"
  }
}
```

**Comment by Nornode** [comment]
@jbardin Did you see this comment? ☝️

**Comment by jbardin** [comment]
@Nornode

This is going to take a different approach from what you are attempting. The language does not turn strings into references, so what you are asking is not possible.

Reading the data sources into some local structures, and assigning the appropriate values should allow you to assign the values you need based on string keys. If you need more guidance, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
