### ISSUE TITLE
Terraform as Docker does not work

### ISSUE THREAD

**Issue by smoms** [hashicorp/terraform#24190]
Hi,

I am running Terraform as Docker as per https://hub.docker.com/r/hashicorp/terraform/
When I run the command _docker run -i -t hashicorp/terraform:light plan main.tf_ I get error:

_stat main.tf: no such file or directory_

**Comment by grimm26** [comment]
you need to allow the docker container access to your storage where your main.tf is.  This is not a terraform issue, this is an issue with you configuring docker.  See https://docs.docker.com/storage/

**Comment by mildwonkey** [comment]
@grimm26 nailed it - this is a docker configuration issue, not a terraform issue, so I am going to close this. Thanks!
