### ISSUE TITLE
app_service_environment_id propertie of azurerm_app_service_plan looks required

### ISSUE THREAD

**Issue by GregoryFrance** [hashicorp/terraform#24209]
A new error append when I create a "azurerm_app_service_plan" with AzureRM 2.0.0

"app_service_environment_id" propertie looks required, but it should not (optional in the documentation)

 

### Terraform Version
Terraform v0.12.21
+ provider.azuread v0.7.0
+ provider.azurerm v2.0.0

```
...
```

### Terraform Configuration Files

```hcl
...
```

### Crash Output

Error creating/updating App Service Plan "test-euw-asp" (Resource Group "test-middle-euw-rg"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.hostingEnvironmentProfile.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."
### Actual Behavior

Can't create a app service plan wihout ASE

**Comment by woeterman94** [comment]
Follow. Got the same issue.
