### ISSUE TITLE
Collection merge does not work as expected

### ISSUE THREAD

**Issue by aryni01** [hashicorp/terraform#24236]
### Terraform Version

```
Terraform v0.12.20
```

### Terraform Configuration Files

```hcl
...
```

### Expected Behavior

While merging two or more collections, the output is not an expected output, for example with:
merge({"x"={"a"="b", "c"="d"}}, {"x"={"e"="f"}}) 
The result should be {"x"={"a"="b", "c"="d", "e"="f"}}

### Actual Behavior

result is:
{"x" = {"e" = "f"}}
### Steps to Reproduce

This can be reproduced by just terraform console

**Comment by aryni01** [comment]
more finding..
the AND conditional does not work as expected with any other programming languages:
for example:
contains(keys({"x"={"y"="z"}}),"x") && contains(keys({"x"={"y"="z"}}.x), "y") returns true as expected
but following throws error:
contains(keys({"x"={"y"="z"}}),"m") && contains(keys({"x"={"y"="z"}}.m), "z")
once the first expression is evaluated and is false, by definition, the second expression should not be evaluated for any AND condition, at least almost all (I am saying almost because I have not worked with all available) programming languages works this way

**Comment by jbardin** [comment]
Hi @aryni01,

Thanks for taking the time to file an issue. 

While the `merge` command takes an arbitrary number of maps or objects, it makes no mention of nested maps or objects, and indeed performs no flattening of the objects being passed int. Each object in your example has a single attribute of `x`, and according the merging rule, the final assignment "wins", meaning the value of `{"e"="f"}` is what is expected. 

As for the `&&` operator behavior, that is recorded in issue #24128, and will require a change in the upstream dependency for the expression evaluation.

Thanks!

**Comment by aryni01** [comment]
haha.. closed the issue without even very good explanation, a merge by definition is merging two or objects and becoming bigger object, there is no such thing as winning in merging, may be in software engineering it is, as two companies merge, most of the people from smaller companies get laid off, very realistic approach... but still not quite right because in my example the people from bigger company are laid off..

**Comment by jbardin** [comment]
Sorry, maybe I can phrase it differently. The `merge` function operates only on the map or object value passed in, and purposely takes no account of the type or value of the nested elements. This follows the documented and historical behavior of `merge`, and changing that would be a breaking change to any configuration currently using `merge`. While "merge" may have different linguistic meanings in different contexts, we have to remain compatible with the current implementation at this time.

A function that recursively merges nested maps and/or objects would need to be a different function entirely. I new function is not entirely out of the question, but should be filed as a proposal with the desired behavior and use cases.
