### ISSUE TITLE
Cycle on destroy not correctly detected as fixed

### ISSUE THREAD

**Issue by erikpaasonen** [hashicorp/terraform#24234]
### Terraform Version
```
Terraform v0.12.21
```

### Terraform Configuration Files
```hcl
resource aws_s3_bucket_object myobject {
  bucket  = aws_s3_bucket.mybucket.bucket
  key     = local.test_pipeline_trigger_stub_key
  content = timestamp()

  depends_on = [
    aws_cloudwatch_event_rule.myrule,
  ]
}

resource aws_cloudwatch_event_rule myrule {
  name     = "my-test"
  role_arn = aws_iam_role.myrole.arn
  event_pattern = jsonencode(
    {
      "source" : ["aws.s3"],
      "detail-type" : ["AWS API Call via CloudTrail"],
      "detail" : {
        "eventName" : ["PutObject"],
        "eventSource" : ["s3.amazonaws.com"],
        "requestParameters" : {
          "bucketName" : [aws_s3_bucket.mybucket.bucket],
          "key" : [local.test_pipeline_trigger_stub_key]
        }
      }
    }
  )
}
```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
Terraform should recognize that there is no cycle in the current config and delete the resources successfully.

### Actual Behavior
Running `terraform destroy` results in the following error:

>Error: Cycle: aws_s3_bucket_object.myobject, aws_cloudwatch_event_rule.myrule

### Steps to Reproduce
1. Modify the reference code above:
    * change `requestParameters` to:
```hcl
          "bucketName" : [aws_s3_bucket_object.myobject.bucket],
          "key" : [aws_s3_bucket_object.myobject.key]
```
1. `terraform init`
1. `terraform apply`
1. Modify the two lines back to the reference code above
1. `terraform apply`
1. `terraform destroy`

### Additional Context

To be clear: the bug being reported here is that the cycle check logic is partially relying on the tfstate file taking precedence over the .tf files in the current directory.

Not sure how to get repro step 3 to apply without the cycle error occurring, but I somehow accomplished this in multiple namespaces with it coded this way. Makes reproducing this issue unfortunately difficult, almost have to trigger an as-yet-unknown bug in the resource provider to get to the prerequisite state for this issue. Sorry about that!

I can't seem to reproduce this issue in an isolated environment. However, I was able to make the problem go away by manually deleting the S3 object out of the bucket and manually deleting the CWE rule, then letting Terraform recreate them (with the resources coded properly, of course!) before attempting another destroy.

When I first created the S3 object and the CWE rule I remember seeing a warning about a cycle, but somehow the TF apply still went through. This was using Terraform v0.12.18 and AWS provider v2.48.0. Repro step 1 replicates the way the code was on that commit when this issue first started happening to us. Later I realized the cycle did exist in the way it was coded, and fixed it (reference code above). However, this error occurs on all future attempts to delete these resources.

I suspect what's going on here is there's an upstream condition on `apply` which is letting through a cycle condition to be created anyway (separate issue), and then that cycle condition is tracked in the tfstate file even though the current Terraform code no longer actually has a cycle in it.

Suggested supporting resources, to jump-start a full stack:

```hcl
locals {
  test_pipeline_trigger_stub_key = "stub.txt"
}

resource aws_s3_bucket mybucket {
  bucket_prefix = "mybucket-"
  force_destroy = true
  versioning {
    enabled = true
  }
}


resource aws_cloudwatch_event_target test_pipeline_execution {
  rule     = aws_cloudwatch_event_rule.myrule.name
  arn      = aws_codepipeline.mypipeline.arn
  role_arn = aws_iam_role.myrole.arn
}

resource aws_codepipeline mypipeline {
  name     = "my-test"
  role_arn = aws_iam_role.test_pipeline_execution.arn

  artifact_store {
    location = aws_s3_bucket.mybucket.bucket
    type     = "S3"
  }

  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "S3"
      version          = "1"
      output_artifacts = ["source-output"]

      configuration = {
        S3Bucket             = aws_s3_bucket.mybucket.bucket
        S3ObjectKey          = local.test_pipeline_trigger_stub_key
        PollForSourceChanges = "false"
      }
    }
  }

  stage {
    name = "Check"

    action {
      name      = "Check"
      category  = "Approval"
      owner     = "AWS"
      provider  = "Manual"
      version   = "1"
      run_order = 1
    }
  }

  depends_on = [
    aws_iam_role.test_pipeline_execution,
    aws_iam_role_policy.test_pipeline_execution,
  ]
}

resource aws_iam_role myrole {
  name_prefix           = "my-test-"
  force_detach_policies = true

  assume_role_policy = data.aws_iam_policy_document.myrole_assumerole_policy.json

  tags = local.global_tags
}

data aws_iam_policy_document myrole_assumerole_policy {
  statement {
    principals {
      identifiers = ["events.amazonaws.com"]
      type        = "Service"
    }

    actions = [
      "sts:AssumeRole",
    ]
  }
}

resource aws_iam_role_policy myrole {
  role   = aws_iam_role.myrole.id
  policy = data.aws_iam_policy_document.myrole.json
}

data aws_iam_policy_document myrole {
  statement {
    actions   = ["codepipeline:StartPipelineExecution"]
    resources = [aws_codepipeline.mypipeline.arn]
  }
}

resource aws_iam_role test_pipeline_execution {
  name_prefix           = "my-test-"
  force_detach_policies = true

  assume_role_policy = data.aws_iam_policy_document.pipeline_exec_assumerole.json

  tags = local.global_tags
}

data aws_iam_policy_document pipeline_exec_assumerole {
  statement {
    principals {
      identifiers = ["codepipeline.amazonaws.com"]
      type        = "Service"
    }

    actions = [
      "sts:AssumeRole",
    ]
  }
}

resource aws_iam_role_policy test_pipeline_execution {
  role   = aws_iam_role.test_pipeline_execution.id
  policy = data.aws_iam_policy_document.test_pipeline_execution.json
}

data aws_iam_policy_document test_pipeline_execution {
  statement {
    sid = "ManageArtifactsInS3"

    actions = [
      "s3:*",
    ]

    resources = [
      aws_s3_bucket.mybucket.arn,
      "${aws_s3_bucket.mybucket.arn}/*",
    ]
  }
}
```

### References
- #24121

**Comment by jbardin** [comment]
Confirmed that this no longer produces the cycle in master, and will be included in the next major release.

**Comment by danieldreier** [comment]
[Terraform 0.13.0 beta 1 launched today](https://github.com/hashicorp/terraform/issues/25016), and you're welcome to confirm this issue is fixed in it. If it isn't, please feel free to file a new issue or reach to to me (ddreier@hashicorp.com) and I can re-open this one.
