### ISSUE TITLE
data.*.* still contains unknown values during apply

### ISSUE THREAD

**Issue by crispinakomea** [hashicorp/terraform#24257]
We're upgrading our terraform version from v0.11.14 to v0.12.21. We've ran all the old configuration files with v0.12.21 and carried out all the code changes advised by the terraform validate command.

We have now however ran into the following dependency issue.

### Terraform Version

```
Terraform v0.12.21
```

### Terraform Configuration Files

**../../../modules/global_vars/app.tf**
```hcl

locals {
  iac_environment_prefix_aad = "${var.iac_environment == "" ? "" : join("", list(var.iac_environment, " "))}"
}

output "service_account_role_AAD_group" {
  value = "AAD SVC AZR APP ${upper(local.iac_environment_prefix_aad)}${upper(var.environment)} ${upper(local.risk_name_mapping[var.risk_profile])} ${upper(var.application_short_name)}"#"AAD RES AZR APP ${upper(var.environment)} LOW ${upper(var.application_short_name)} DATA_ACCESS"
}

output "octopus_SP_group_name" {
  value = "AAD SVC AZR OCTOPUS ${upper(local.iac_environment_prefix_aad)}${upper(var.environment)} ${upper(local.risk_name_mapping[var.risk_profile])} ${upper(var.application_short_name)}"#"AAD SVC AZR OCTOPUS {ENV} {RISK} {APP}"
}
```

**main.tf**
```hcl
locals {
  service_account_role_group_name = var.service_account_role_group_name == "" ? module.global_vars_app.service_account_role_AAD_group : var.service_account_role_group_name
  octopus_sp_role_group_name = var.octopus_sp_role_group_name == "" ? module.global_vars_app.octopus_SP_group_name : var.octopus_sp_role_group_name
}

module "global_vars_app" {
  source = "../../../modules/global_vars/app"
  environment = var.environment
  business_unit = local.business_unit
  application_short_name = var.application_short_name
  application_shortest_name = local.application_shortest_name
  application_long_name = local.application_long_name
  location = var.location
  risk_profile = local.risk_profile
  instance_name = var.instance_name
  iac_environment = var.iac_environment
}

data "azuread_group" "service_account_role_group" {
  provider = azuread.main
  name = local.service_account_role_group_name
}

data "azuread_group" "octopus_sp_role_group" {
  provider = azuread.main
  name = local.octopus_sp_role_group_name
}
```

### Expected Behavior
Successful execution

### Actual Behavior
Failed execution with the following message
```hcl
Error: configuration for module.app_onboarding_app_instance_level_Infra-Dev1.data.azuread_group.octopus_sp_role_group still contains unknown values during apply (this is a bug in Terraform; please report it!) 
Error: configuration for module.app_onboarding_app_instance_level_Infra-Dev1.data.azuread_group.service_account_role_group still contains unknown values during apply (this is a bug in Terraform; please report it!)
```

### Steps to Reproduce
1. `terraform init`
2. `terraform validate`
3. `terraform apply`

**Comment by jbardin** [comment]
Hi @crispinakomea,

Thanks for filing the issue here. Unfortunately there's not quite enough to go by in the configuration provided. Something appears to be causing the locals to evaluated as unknown, but we will need more information.

If the `main.tf` file is in the root module, we can narrow things down to the `global_vars_app` outputs. In those outputs, I think the only unaccounted-for value is the `local.risk_name_mapping[var.risk_profile]`. 

If you can determine where the original unknown value is coming from, or provide the entire chain of values back to their sources, we should be able to see where the bug is here. The trace logs may also have some important information if some of the data is coming from other resources.

**Comment by crispinakomea** [comment]
Hi @jbardin,

Thanks for your help. We were able to figure out what the issue was. We tracked back all of the inputs and discovered the unknown value was coming from

`var.octopus_sp_role_group_name`

This value was an output of a different module 

And we were able to fix the output from this module

Thanks for your help again. I'll close this issue.
