### ISSUE TITLE
Support AWS EKS IAM Roles

### ISSUE THREAD

**Issue by guidoffm** [hashicorp/terraform#24252]
- I want to run Terraform in a pod on AWS Elastic Kubernetes Service (EKS).
- Terraform should write the state to S3.
- Access rights for S3 should be granted to the pod by a service account that is assigned an IAM Role:
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

- To get this working a Go AWS SDK with a version of at least 1.23.13 is required according to https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by guidoffm** [comment]
Please reopen this case.

This is an issue with the remote state for S3. It seems it has nothing to do with the AWS provider.

**Comment by bflad** [comment]
Multiple fixes for credential ordering, automatically using the AWS shared configuration file if present,  and `profile` configuration handling of the S3 Backend have been merged and will release with version 0.13.0-beta2 of Terraform. In particular, this functionality has been specifically verified. See also: https://github.com/hashicorp/aws-sdk-go-base/issues/33
