### ISSUE TITLE
make updatedeps fails on master

### ISSUE THREAD

**Issue by joekhoobyar** [hashicorp/terraform#2426]
The part that fails:

```
github.com/xanzy/go-cloudstack/cloudstack
go build github.com/xanzy/go-cloudstack/cloudstack: /usr/lib/go/pkg/tool/linux_amd64/6g: signal: killed
```

**Comment by joekhoobyar** [comment]
We would like to be able to build terraform from *master*, so that we can (purportedly) stop hitting the AWS rate limiting issue.

**Comment by svanharmelen** [comment]
Thanks for reporting, I'll have a look in a few ro see if I can reproduce.

**Comment by joekhoobyar** [comment]
It might be the PPA I am using on Ubuntu to get go 1.4.2.  I am going to try it again with the binary distribution.

**Comment by joekhoobyar** [comment]
Nope, it still fails using the official 1.4.2 distribution from Go.

**Comment by joekhoobyar** [comment]
I believe the reason the process gets killed is that the virtual box building this is running out of memory.  Trying again with 2 gigs.

**Comment by svanharmelen** [comment]
@joekhoobyar ah, that could maybe explain... I'm just booted my macbook and will also have a look.

**Comment by joekhoobyar** [comment]
The build seems to work on darwin.amd64, just failing on linux.amd64

**Comment by svanharmelen** [comment]
Just for the headsup... I cannot reproduce this and we are discussing the issue further here: https://github.com/xanzy/go-cloudstack/issues/30

Will update here when we found the problem.

**Comment by joekhoobyar** [comment]
I tried again with 2 gigs.  The build completes but I am not seeing any binaries produced after running ``make`` with no arguments.  Any other steps I should follow besides what is in the documentation?

**Comment by joekhoobyar** [comment]
You can close this.  I am now using ``make dev`` instead of ``make``
