### ISSUE TITLE
Dashboard folder not listed as Dependency 

### ISSUE THREAD

**Issue by luiscamaral** [hashicorp/terraform#24283]
I've lost many hours to found that the errors "Error: 412 Precondition Failed" that grafana dashboards were reporting when trying to "terraform apply" while using a folder definition was because it doesn't link the resource dependency in between the dashboard and folder automatically. I could workaround this issue by declaring the resource on a "depend_on" clause for the dashboard, but it looks like a design flaw for when a folder is listed, as it is "obviously" a dependency.

To Reproduce:

Create a folder and dashboard inside this folder, then try to destroy or change the dashboard created. 

Result:

Terraform will error with message "Error: 412 Precondition Failed". Also it is hidden the detailed message for this error, what could be of help to resolve the issue. 

Expected:

Terraform grafana provider should know that there is a dependency in between these resources, without having to have it declared on a "depends_on" clause explicitly.

--

**Comment by jbardin** [comment]
Hi @luiscamaral,

Terraform itself doesn't have any knowledge of implicit dependencies between resources. Dependencies are created via references in the configuration, or setting `depends_on` in the rare case that a reference isn't being made.

If the Grafana provider could improve some documentation, or provide better error messages, please open an issue with that provider. If you have more questions about the Grafana resource it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
