### ISSUE TITLE
substr("x", 0, 0) returns "x" instead of ""

### ISSUE THREAD

**Issue by alexyakunin** [hashicorp/terraform#24318]
It seems `substr` assumes the whole string tail must be returned when the last argument is zero:

    terraform console
    > substr("abc", 0, 0)
    abc
    > substr("abc", 1, 0)
    bc

This behavior isn't described in the documentation; moreover, it seems this can lead to a number of issues when the length of a substring is computed rather than pre-defined.

**Comment by nick96** [comment]
I'm interested in contributing to terraform and thought this issue looked good (hope that's okay!). Looks like this is an issue in zclconf/go-cty. I've submitted a patch (again, hope that's okay!)

**Comment by nick96** [comment]
My upstream patch got merged. They're not ready to release a new version of go-cty and there's also the issue of this potentially being a breaking change (?)

**Comment by alisdair** [comment]
Hi @nick96! The go-cty release has been pulled into master now, so this fix will go out as part of 0.13. Thanks for your contribution!
