### ISSUE TITLE
Helm release resource does not recognise dependency_update key

### ISSUE THREAD

**Issue by cotvictor** [hashicorp/terraform#24327]
Hi,

While running a terraform configuration which is using helm release resource, it doesn't recognise a key which is documented in docs:
- terraform version: ``` Terraform v0.11.14```
- terraform config: 
```resource "helm_release" "app" {
         repository = "dxp"
         chart = "${var.chart_name}"
         version = "${var.chart_version}"
         name = "${var.app_name}"
         timeout = "${var.deployment_timeout}"
         wait = true
         dependency_update = true 
}
```

- output: 
```
Error: module.app.helm_release.app: : invalid or unknown key: dependency_update
```

**Comment by mildwonkey** [comment]
Hi @cotvictor ! I labeled this issue so it will get moved to the helm provider repository, but it will help if you update it to include your helm provider version - it's possible that you are trying to access an attribute that's only available in a newer (or older) version of the provider.
