### ISSUE TITLE
Unable to create  Azure Windows VM .

### ISSUE THREAD

**Issue by NisharunnisaShaik** [hashicorp/terraform#24326]
Hi
I am not sure whether it is a right place to post my question but hoping some one might help.
I am unable to create Windows Virtual Machine.I gone through many blogs, official docs but nothing helped . Somehow one or the other error is popping up.

Terraform version : v0.12.23
My config for creating vm:

```
resource "azurerm_windows_virtual_machine" "resource_virtual_machine" {
name = "${var.virtual-machine}"
location = "${azurerm_resource_group.resource_group_name.location}"
resource_group_name = "${azurerm_resource_group.resource_group_name.name}"
size = "Standard_B1ls"
admin_username = "${var.admin}"
admin_password = "${var.password}"
network_interface_ids = ["${azurerm_network_interface.resource_network_interface.id}"]

os_disk {
caching = "ReadWrite"
storage_account_type = "Standard_LRS"

}

source_image_reference{
publisher="MicrosoftWindowsDesktop"
offer="Windows-10"
sku="19h1-ent"
version="18362.592.2001092016"
}
}

```
**Error : compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The Admin Username specified is not allowed." Target="adminUsername"**

Note : Storage_image_reference , os_profile_windows_config, os_profile

I have tried using all the above options in the config file but every time i get a new error stating the "
os_profile is not expected here".

Solutions & suggestions appreciated.
Thank you

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help. Thanks!
