### ISSUE TITLE
Terraform crashes when for_each is used with a provisioner on a destroy "when = destroy

### ISSUE THREAD

**Issue by TheFLHurricane** [hashicorp/terraform#24325]
### Terraform Version

```
0.12.19
```

### Terraform Configuration Files

```
variable "test_map" {
  type = map
  default = {
    key1 = "A"
    key2 = "B"
  }
}

resource "null_resource" "test"{
  for_each          = var.test_map
  provisioner "local-exec" {
    when    = destroy
    command = "sleep 60"
  }
}
```

**Comment by mildwonkey** [comment]
Hi @TheFLHurricane,
I just tested your configuration in a more recent version of terraform (0.12.21), and it's working  - we implemented some recent bug fixes with `for_each` that (apparently) fixed the behavior you see. Please upgrade your terraform version, and open a new issue if you are still seeing a problem. Thank you!
