### ISSUE TITLE
aws_launch_configuration: Allow ClassicLinkVPCId and ClassicLinkVPCSecurityGroups to be specified

### ISSUE THREAD

**Issue by jschneiderhan** [hashicorp/terraform#2433]
As detailed [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-classiclinkvpcid).

I'm happy to give this a shot when I have some bandwidth.

**Comment by stack72** [comment]
Closed via #7470 :)
