### ISSUE TITLE
Latest Terraform unable to run on Mac

### ISSUE THREAD

**Issue by elainedavid** [hashicorp/terraform#24337]
Hi,

I'm currently unable to run the latest version of the Terraform exe for Mac (terraform_0.12.23_darwin_amd64.zip), after I had downloaded it this morning.  I'm running macOS Catalina 10.15.3 (19D76).

When I run any terraform command in my terminal window, it throws a security error:

**“terraform” can’t be opened because Apple cannot check it for malicious software.**
This software needs to be updated. Contact the developer for more information.
Chrome downloaded this file today at 10:05 AM from www.terraform.io.

I can try to revert to an earlier version of Terraform for now.

**Comment by jbardin** [comment]
Hi @elainedavid,

Sorry you're having a problem with this. I downloaded the latest 0.12.13 release binary on Catalina, and confirmed it has a correct signature. 

```
$ codesign --verify  --verbose ./terraform
./terraform: valid on disk
./terraform: satisfies its Designated Requirement
$ ./terraform version
Terraform v0.12.23
```

Can you show the series of commands you ran to encounter that error?

**Comment by danieldreier** [comment]
@elainedavid we haven't gotten any more reports of this issue, so I'm going to close it and assume that you've had success.  Please let us know if this is still an issue for you and I'm happy to help.
