### ISSUE TITLE
Terraform 0.12 cannot iterate through subnets on plan/apply

### ISSUE THREAD

**Issue by lukebakare** [hashicorp/terraform#24348]
## Terraform Version
0.12.23

## Terraform Configuration Files
Taken from: https://www.terraform.io/docs/providers/aws/d/subnet_ids.html
```terraform
data "aws_subnet_ids" "example" {
  vpc_id = module.vpc.vpc_id
}

data "aws_subnet" "example" {
  for_each = data.aws_subnet_ids.example.ids
  id       = each.value
}

output "subnet_cidr_blocks" {
  value = [for s in data.aws_subnet.example : s.cidr_block]
}
```

## Crash Output
```
Error: Invalid for_each argument

  on elasticsearch.tf line 14, in data "aws_subnet" "example":
  14:   for_each = data.aws_subnet_ids.example.ids

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```
## Expected Behavior
Terraform to iterate through each subnet id in the for_each loop

**Comment by jbardin** [comment]
Hi @lukebakare 

In your version of the configuration, the `vpc_id` is coming from `module.vpc.vpc_id`. I assume that this is not hard-coded in the module, and being derived form a vpc resource of some sort. This mean that the data source cannot be read until after the module resources have been applied, and therefor they cannot be used as the input for the `for_each` expression.

The keys passed to `for_each` must be known during the plan, so you will need to extract the subnets from the config in some other way than waiting for the vpc to be created. If you have more questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
