### ISSUE TITLE
Validate should check configuration against provider's ValidateFunc on schema

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform#24352]
### Current Terraform Version

```
Terraform v0.12.18
```

### Use-cases

We run `terraform validate` in CI on branches and locally to catch simple issues before running `plan` and `apply` when merged to master. This doesn't catch everything but is quick to run and can catch a lot of simple mistakes or even some mistakes around outputs or branching logic from conditionals that aren't seen on `plan` or `apply` that don't take those branches.

I was under the impression that `terraform validate` would catch failures to meet a resource or data source's `ValidateFunc` (not sure if it did back in 0.11, haven't checked yet but 0.12 deliberately introduced a reduced scope for this tool to be much more friendly to "offline" runs and this might have been dropped during that work). However I raised an internal WIP pull request yesterday to move our DLM lifecycle policies to every hour while also raising https://github.com/terraform-providers/terraform-provider-aws/pull/12327 to add this to the allowed values in the `IntInSlice` `ValidateFunc` after seeing the plan fail. I then expected to see my branch's CI fail because of the validation failure but `terraform validate` passed fine on this.

### Attempted Solutions

I don't really have a solution right now other than running a plan on every push to non master branches which is a lot slower and requires the CI runner to have the relevant IAM permissions to actually run the plan. Or we just have to remember that `terraform validate` can't catch these errors and just revert changes that fail this that make it on to master.

### Proposal

`terraform validate` should check if `ValidateFunc`'s pass for all fields. I haven't really looked into this part of the code base but feel like it still fits inside the reduced scope for allowing more offline only actions as this should be doable as long as the provider is present (either bundled or the workspace has been `terraform init`'d) which is already a requirement for `terraform validate`.

**Comment by jbardin** [comment]
Hi @tomelliff,

Part of the validation of the configuration calls `ValidateResourceTypeConfig` for every resource found in the configuration. Most of the overall validation process is checking the types and structure of the configuration, but there is no evaluation of state or variables done at this time. The result is that unless the value is hard-coded in the configuration, the resource's internal validation isn't likely able to return anything useful.

The [terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk/issues) is responsible for how the provider's validate function is called, and work on a new version of the SDK may provide some more options for better type validation. The situation however is likely that the resource is seeing an "unknown" value, which it can't validate.

Any proposals for enhancement should go to the terraform-plugin-sdk. While the current SDK is frozen for compatibility, there will be forthcoming development of the next SDK version.

Thanks!
