### ISSUE TITLE
Incorrect destroy order when working with Azure Policies in a set

### ISSUE THREAD

**Issue by erikpaasonen** [hashicorp/terraform#24351]
### Terraform Version

```
Terraform v0.12.23
+ provider.azurerm v1.44.0
```

### Terraform Configuration Files

https://gist.github.com/erikpaasonen/cf0670ca533d81851b875d76533696ad

This is simply the sample code for the [azurerm_policy_definition](https://www.terraform.io/docs/providers/azurerm/r/policy_definition.html#example-usage) and [azurerm_policy_set_definition](https://www.terraform.io/docs/providers/azurerm/r/policy_set_definition.html#example-usage) resources of the AzureRM provider adapted to work with each other.

### Debug Output

https://gist.github.com/erikpaasonen/d097156afe8762db947b7c9bf0f01bcd

### Crash Output

N/A

### Expected Behavior

When the `azurerm_policy_definition` is part of an `azurerm_policy_set_definition` and the policy definition needs to be deleted/recreated to perform a modification, the policy should be detached/removed from the set prior to being deleted.

### Actual Behavior

The policy deletion is always attempted first, resulting in the following error message:

>Error: Error deleting Policy Definition "accTestPolicy": policy.DefinitionsClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDeletePolicyDefinitionRequest" Message="The policy definition 'accTestPolicy' cannot be deleted.  It is referenced by the policy set definition '/subscriptions/aadd890f-876d-4390-9d6e-a5450e9eacb7/providers/Microsoft.Authorization/policySetDefinitions/testPolicySet'. Please remove this policy definition from all policy set definitions that reference it."

### Steps to Reproduce

1. `terraform apply`
1. make a change to the policy, such as modifying the name
1. `terraform apply`

### Additional Context

The bug report template for new issues in the github repo for the `azurerm` provider specifically calls out resource ordering issues as belonging instead in Terraform core.

**Comment by jbardin** [comment]
Hi @erikpaasonen,

Sorry about the confusion here. While the issue template mention ordering issues, this isn't an error in ordering, the order is being applied as defined in the configuration. 

If the policy resource cannot be deleted first, the option is to set it to `create_before_destroy`.  This will not only create the new resource first, but update the dependents before the destroy happens as well. If this workflow isn't compatible with the resource for some reason that would need to be rectified within the resource types themselves. 

I'll move this over for now, and tag this as documentation. It may just be a matter of updating the resource docs, but the provider team can handle any other necessary changes. as well.
