### ISSUE TITLE
Boolean data type is case-sensitive

### ISSUE THREAD

**Issue by brandonh-msft** [hashicorp/terraform#24354]
### Terraform Version

```
Terraform v0.12.21
```

### Terraform Configuration Files

```hcl
variable "val" {
  type = bool
}

output "output" {
    value = (var.val) ? "yup" : "nope"
}
```

### Expected Behavior

~~~
terraform apply -var val=True

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

output = yup
~~~
### Actual Behavior

~~~
terraform apply -var val=True

Error: Invalid value for input variable

The argument -var="val=..." does not contain a valid value for variable "val":
a bool is required; to convert from string, use lowercase "true".
~~~
### Steps to Reproduce

Using the above HCL, just
```
terraform apply -var val=True
```

### Additional Context

For external systems calling terraform, their values aren't always lower-case boolean. Some of these are `True` and `False` and others may choose to use `TRUE` or `FALSE`. Terraform should be more sensible here.

**Comment by jbardin** [comment]
Hi @brandonh-msft,

Thanks filing the issue. 

I understand the frustration here, as we often need to handle inputs from various data, incompatible sources. Unfortunately this isn't a matter of parsing a flag; just like the tfvars files, and `TF_VAR_*` environment variables,  the `-var` flag is passing _configuration_ to the process. This means that the `-var` flag arguments must be valid Terraform HCL syntax, and the boolean keywords are `true` and `false`. 

Interpreting other strings as boolean leaves room for ambiguity and bugs, and the concept of "truthiness" was something the we purposely left out of the language specification. This way we avoid the inconsistencies for users with experience in other languages; e.g `True == 1` is true in python, while `true ==1 ` is false in ruby, and `x = 'True'; x == True` is false in python, but `if x:` evaluates to `True`.


While we're not going to accept this as an enhancement, know that we do take these issues into consideration, and try to evaluate their impact against the workflows of all users to the best of our abilities. 

Thanks
