### ISSUE TITLE
Support ignoring whether or not an ENI is attached to an instance

### ISSUE THREAD

**Issue by joekhoobyar** [hashicorp/terraform#2436]
If we use Terraform to create an unattached ``aws_network_interface``, and then have an ASG that launches instances that connect themselves to the ENI, future runs of Terraform will actually *disconnect* that network interface - it is imperative that we are able to ignore this difference and prevent Terraform from disconnecting the network interface on future runs.

**Comment by TheM0ng00se** [comment]
+1 : Ran into this as well

**Comment by mikerahmati** [comment]
+1
