### ISSUE TITLE
Terraform 0.12.23 changelog is blank

### ISSUE THREAD

**Issue by Apollorion** [hashicorp/terraform#24360]
https://github.com/hashicorp/terraform/blob/v0.12.23/CHANGELOG.md

Just trying to figure out what changed, looks like it was released on the same day? So maybe it was a mistake, just want to be sure.

**Comment by pkolyvas** [comment]
Hi @Apollorion. Sorry for the confusion.

`0.12.23`'s only change is that the version is correctly reported. 

The why:

`0.12.21` was our first `0.12.x` release from a branch. The cleanup step didn't run completely and we manually cleaned up, but we missed updating Terraform's reported version. 

This mean Terraform `0.12.22` reports it's version (`terraform -v`) as `0.12.21`.
