### ISSUE TITLE
Include ID information when a resource already exists.

### ISSUE THREAD

**Issue by adschutz** [hashicorp/terraform#24365]
This is related to https://github.com/hashicorp/terraform/issues/22206.

When a resource already exists, terraform fails with "The -resource- already exists." It would be nice if terraform would include the ID of the resource in the error message. This would ease importing without having to run in DEBUG mode.

Thanks!

**Comment by jbardin** [comment]
Hi @adschutz,

I understand that trying to import existing resources can be cumbersome, and improving that is on our roadmap.

Terraform does not know what part of the configuration is the unique identifier for a resource; and it may not even be part of the configuration, as some use a derived value, or one that needs to be looked up via the API. This unfortunately means there's no way to automatically report this directly from terraform. 

If there is a resource that is causing trouble in particular, you can file an issue with that provider to return more information in the error message. 

Thanks!
