### ISSUE TITLE
Error: Could not satisfy plugin requirements

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform#24378]
### Terraform Version
```
hashicorp/terraform-github-actions@v0.8.0
v0.12.23
```

### Terraform Configuration Files
https://github.com/ironPeakServices/infrastructure/tree/feat/monitoring/terraform

### Debug Output
https://github.com/ironPeakServices/infrastructure/runs/510560959?check_suite_focus=true

### Expected Behavior
Since `init` and `validate` works, I would expect `plan` to work.

### Actual Behavior
```
2020/03/16 09:06:42 [TRACE] terraform.NewContext: resolving provider version selections
82

83
Error: Could not satisfy plugin requirements
```

### Steps to Reproduce
Run the pipeline.

### References
https://github.com/hashicorp/terraform-github-actions/issues/154

**Comment by jbardin** [comment]
Hi @hazcod,

From the logs output it appears that you are providing the `plan` command with a specific state file, which is not provided to the `init` process. If there are any resource left in the state file that need providers not listed in the config, they won't be installed via `init`. 

Can you confirm that the statefile is empty, or does not contain any unexpected resources? If you wish for this to plan the destruction of resource in the state file, that will be have to be present for `init` as well to ensure the proper providers are available.

**Comment by hazcod** [comment]
Hmm, weirdly enough, `terraform init` uses the state but does not have a cli argument to specify the state file?

**Comment by jbardin** [comment]
@hazcod, Do you have the logs from them using the same state? The link you provided shoes `init` using `./terraform.tfstate`, while plan is using `./state/terraform.tfstate`.

**Comment by hazcod** [comment]
HI @jbardin , well the problem is I cannot pass the correct state path to `terraform init`.

**Comment by jbardin** [comment]
@hazcod, If the default paths are not adequate, the overall state should be configured via a `backend` in the configuration so that it is consistent between init, plan and apply. You can use the `local` backend for this:

```
terraform {
  backend "local" {
    path = "state/terraform.tfstate"
  }
}
```

**Comment by hazcod** [comment]
Seems to be fixed, did not know about the local backend. Thanks!
