### ISSUE TITLE
Support ignoring changes to a resource, if it already exists.

### ISSUE THREAD

**Issue by joekhoobyar** [hashicorp/terraform#2437]
It would be great if the ``lifecycle`` block supported ignoring changes to a resource, if it already existed.  Something like ``ignore_updates = true``.  This would solve the problem with #2436, as well as many other situations where we want Terraform to create the infrastructure initially but we do not want it to *undo* changes that are done to the infrastructure outside of it's control - for example, when instances are launched from an ASG and then the instance makes changes to infrastructure.

**Comment by cdelorme** [comment]
Our team has encountered these problems as well.

The current, known, high-availability models which describe a solution using dynamic routing tables or shared network interfaces conflict with the declarative behavior of terraform.

If resources created by terraform are manipulated outside of terraform, running changes through the terraform configuration will reset the state of those modified resources.

We effectively need a way to say "treat this resource imperatively", or "ignore this if it has been created".  It might be worth investigating a lifecycle rule to accomplish this:

	lifecycle {
		ignore_updates = true
	}

**Comment by mikerahmati** [comment]
:+1:  ran into this as well

**Comment by berset** [comment]
:+1: same here, very annoying when terraform kills the aws_route_table.route's for example.

**Comment by josh-padnick** [comment]
:+1: We're attempting to use Terraform with Mesos and would like to provision the Auto Scaling Groups with Terraform, but allow Mesos to alter their desired / min / max values after the fact. This feature would perfectly support that use case!

**Comment by engine07** [comment]
+1 for this

**Comment by pmoust** [comment]
#2525 should have this case covered

**Comment by radeksimko** [comment]
@pmoust Thanks for noticing. #2525 has been merged and will be part of the upcoming release. Closing.

Here's an example of how it works:

```hcl
resource "aws_instance" "web" {
    ami = "foo"
    lifecycle {
        ignore_changes = ["ami"]
    }
}
```
