### ISSUE TITLE
Terraform console crashes when passing incorrect arguments to setsubtract() function

### ISSUE THREAD

**Issue by allexandr112** [hashicorp/terraform#24377]
### Terraform Version

```
Terraform v0.12.23
```

### Terraform Configuration Files

No file, just a commands
```hcl
terraform console
setsubtract([["a"], "b", null], ["a"])
```

### Debug Output

https://gist.github.com/allexandr112/6020d1b5da7f2aef98b880ef89511045

### Crash Output

https://gist.github.com/allexandr112/b35d5f362bf7649f276d63ec680a9d24
### Expected Behavior

I suppose it should be some error message, but no crash
### Actual Behavior

Terraform console crashes and panic
### Steps to Reproduce

1. `terraform console`
2. `setsubtract([["a"], "b", null], ["a"])`
### Additional Context

```
Linux 4.15.0-88-generic x86_64 x86_64 GNU/Linux amd64
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
```

**Comment by danieldreier** [comment]
I've reproduced this on 0.12.25
