### ISSUE TITLE
SIGSEGV when terraform registry is returning 503 errors

### ISSUE THREAD

**Issue by bobcallaway** [hashicorp/terraform#24383]
### Terraform Version

```
Terraform v0.12.23
```

### Terraform Configuration Files

```hcl
using:
gcs backend
provider "google"
data "archive"
```

### Crash Output

https://gist.github.com/bobcallaway/8f0af764e5acd55ee2e9a6d1162fb2bc

### Expected Behavior

No crash

### Actual Behavior

terraform crashed

### Steps to Reproduce

terraform init -reconfigure

**Comment by jbardin** [comment]
Tracking this issue in #24384
