### ISSUE TITLE
aws_db_instance PORT change forces new resources - should just modify existing

### ISSUE THREAD

**Issue by jonhatalla** [hashicorp/terraform#2439]
I created an rds resource, populated it with data, and would like to change its name now because it will conflict with other VPCs that use my terraform configs.

`identifier:                       "rds-db" => "rds-db-production" (forces new resource)`

In the aws console you are able to modify the ID of the resources, it does require a reboot, however does not destroy the resource.

Temp workaround: We just used the console to modify the resource, manually modified the state file, and ran a terraform plan and it runs clean - all that was updated was the route53 record that points to the rds instance, which is expected.

**Comment by catsby** [comment]
Hey @jonhatalla thanks for opening this! I didn't know the identifier was something you could modify... 

I played around with this some on Friday and it's a bit tricky. Like all RDS modifications, if they aren't `apply_immediately`, RDS waits for the next maintenance window. Terraform likes to enforce state _now_, so waiting for things to happen in a future time window is hard to support.

Using `apply_immediately` will force the instance to reboot, but until it's out of the `modifying` state, it still goes by the former ID. The way I see it, we'd have to do at least the following:

- enforce renaming to use the `apply_immediately` flag 
- have both the _new_ and _old_ IDs around and poll for the modifications to finish
- when they do finish, check that the API no longer sees the _old_ ID and does in fact see the _new_ ID
- after confirming that, do `d.SetId` with the new ID 

This is all do-able of course, but adds extra hoops to the current `Update` function. I don't know that I'll get to this anytime soon, but I'm documenting my thoughts above in case someone in the community wants to pick it up.

**Comment by kestred** [comment]
I'd like to *+1* this issue, I checked the terraform source ahead of time so I avoided changing the identifier, but it is something I would like to be able to do.

Also @catsby, I'd like to point out that `builtin/providers/aws/resource_aws_db_instance.go` also treats the `"port"` value as `ForceNew`, but it also can be modified via `rds.ModifyDBInstanceInput`.

**Comment by catsby** [comment]
Updated issue to reflect that we can/should allow updating the `port`

**Comment by Russell-IO** [comment]
@stack72 Can we reopen this issue, we can't rename a live rds instance via Terraform & trying to do it outside of TF just causes pain.
https://www.dropbox.com/s/mqx58pgeih3b7yu/pasted_image_at_2016_12_22_15_34.png?dl=0
