### ISSUE TITLE
Terraform does not pass provider options fully to a child module

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform#24418]
### Terraform Version
```
terraform -version
Terraform v0.12.24
+ provider.azurerm v2.2.0
+ provider.random v2.2.1
```

```hcl
provider "azurerm" {
  alias           = "one"
  version         = "=2.2.0"
  subscription_id = var.one_subscription_id

  features {}
}

provider "azurerm" {
  alias           = "two"
  version         = "=2.2.0"
  subscription_id = var.two_subscription_id

  features {}
}

module "test" {
  source = "./test/"
  providers = {
    azurerm.one = azurerm.one
    azurerm.two = azurerm.two
  }
}
```

### Expected Behavior
Terraform passes providers with all the options

### Actual Behavior
Getting

```Error: "features": required field is not set```

even if "features {}" is explicitly set on both root and child modules

**Comment by jbardin** [comment]
Hi @vladimirtiukhtin,

Can you provide the module configuration as well here? I am guessing that there is no placeholder of the `azurerm.one` provider in the module, hence passing in the configured provider is doing nothing here.

**Comment by vladimirtiukhtin** [comment]
Hi @jbardin. I think I fixed it. It is not terraform but azurerm provider bug. Since version 2.0.0 they introduced this "features {}" flag, and if azurerm provider is not defined explicitly with "fetures {}" set, it does not assume it by default. Then if you have resources consuming Azure API and don't define provider it fails with the message above. Thanks

**Comment by jbardin** [comment]
Thanks for letting us know @vladimirtiukhtin!
