### ISSUE TITLE
Terraform should use IAM role from "refresh" and "plan" commands

### ISSUE THREAD

**Issue by joekhoobyar** [hashicorp/terraform#2442]
Right now, this works with "apply" and "destroy", but not when with "refresh" or "plan".  Terraform fails and says that the AWS environment variables are not found.  It should just be using the IAM role like "apply" and "destroy" do.

**Comment by joekhoobyar** [comment]
Any movement on this yet?  It seems like it should be relatively simple to close, am I wrong about that?

**Comment by mitchellh** [comment]
This should be fixed with #1841. Working on this now.
