### ISSUE TITLE
Terraform plan not picking up manual route addition changes

### ISSUE THREAD

**Issue by wfeng-fsde** [hashicorp/terraform#24429]
### Terraform Version

```
$ terraform -v
Terraform v0.12.24
+ provider.aws v2.54.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.tls v2.1.1
+ provider.vault v2.9.0
```

### Terraform Configuration Files

```
resource "aws_route_table" "route_table_private" {
  count = var.zone_count

  vpc_id = var.vpc_id
}

output "private_route_table_ids" {
  value = aws_route_table.route_table_private.*.id
}

resource "aws_vpc_peering_connection" "peering_connection" {
  vpc_id        = var.vpc_id
  peer_vpc_id   = var.peering_vpc_id
  peer_owner_id = var.peering_aws_account_id
  peer_region   = var.peering_aws_region
}

resource "aws_route" "private_subnet_route_to_peer" {
  count                     = length(var.private_route_table_ids)
  route_table_id            = element(var.private_route_table_ids, count.index)
  destination_cidr_block    = var.peering_vpc_cidr
  vpc_peering_connection_id = aws_vpc_peering_connection.peering_connection.id
}
```

### Debug Output

Not pasting terraform plan output here as the misbehavior I'm seeing is that the plan output is not picking up a manual addition of a route to the route table, although it did pick up manual deletion of a route table.

### Expected Behavior

I'd expect terraform plan to detect the route that was manually added.

### Actual Behavior

The plan did not show any changes after manually adding a route to the route table.

### Steps to Reproduce

N/A

**Comment by wfeng-fsde** [comment]
@rmlsun

**Comment by jbardin** [comment]
Hi @wfeng-fsde,

Can you provide the steps to replicate the issue here? I'm not sure I understand what's going on.  What does "manually added" mean in this context? Was the route added to the config, or was the route created in the AWS console?

**Comment by wfeng-fsde** [comment]
@jbardin sorry for the confusion. The route was added manually in aws console.
This happened in our production code and we have a sprawling code base. I took the shortcut of not trying to reproduce a minimal working example. Let me know if you still need me to produce one.

**Comment by jbardin** [comment]
@wfeng-fsde,

Terraform cannot detect change outside of resource it manages. Adding a resource that does not exist in the configuration requires importing it into terraform manually. The existing `import` documentation can be found here: https://www.terraform.io/docs/import/index.html.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by wfeng-fsde** [comment]
@jbardin Just want to clarify, we create the route table (which we made manual changes to) in our terraform code as well as you can see in the snippets I posted. So the route table is not considered `resource terraform manages` in this case? Or maybe there is some nuance that I'm missing here.

**Comment by jbardin** [comment]
@wfeng-fsde,

The configuration looks like it is managing routes as separate resources, e.g `"aws_route" "private_subnet_route_to_peer"`, and not as part of the route table itself. Looking at the [resource docs](https://www.terraform.io/docs/providers/aws/r/route_table.html) it appears you could define them inline, but you cannot manage the resources in both ways, as terraform can't reconcile the differences between separate resources. 

So in this case there are no route entries managed by the `route_table` resource, so there is no change to detect. There may be more details involved with the behavior of the resources, and the community forum may have users more familiar with the specific of the aws resources themselves.
