### ISSUE TITLE
Cannot taint resource with a space in address

### ISSUE THREAD

**Issue by andrew-schlackman** [hashicorp/terraform#24435]
Attempting to taint a single resource that has a string index with a space in it fails. It works fine for other resources created in the same way but without spaces in their address. This should either be an invalid configuration and Terraform should not create the resource, or it should be able to be tainted like any other resource.

### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files
```hcl
variable "instances" {
  default = {
    "first" = 1
    "second" = 2
    "third" = 3
    "the fourth" = 4
  }
}

resource "random_integer" "host_index" {
  for_each = var.instances  
  min     = 0
  max     = 10
}
```

### Expected Behavior
```
terraform taint random_integer.host_index[\"third\"]
Resource instance random_integer.host_index["third"] has been marked as tainted.

terraform taint random_integer.host_index[\"the fourth\"]
Resource instance random_integer.host_index["the fourth"] has been marked as tainted.
```

### Actual Behavior
```
terraform taint random_integer.host_index[\"third\"]
Resource instance random_integer.host_index["third"] has been marked as tainted.

terraform taint random_integer.host_index[\"the fourth\"]
The taint command expects exactly one argument.
Usage: terraform taint [options] <address>
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform taint random_integer.host_index[\"the fourth\"]`

### Additional Context
I've tried various forms of quoting and escaping, but none have worked. For example,

terraform taint 'random_integer.host_index[\"the fourth\"]'
terraform taint `random_integer.host_index[\"the fourth\"]`
terraform taint random_integer.host_index["""the fourth"""]

**Comment by jbardin** [comment]
Hi @andrew-schlackman,

Shell arguments are traditionally space delimited, so the arguments you are supplying to the `taint` command are interpreted as `random_integer.host_index[\"the` and  `fourth\"]`. You need to escape the space, or quote the argument, e.g. for most unix shells, it would be:

    terraform taint 'random_integer.host_index["the fourth"]'

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by andrew-schlackman** [comment]
Thanks for replying, but I specifically stated in Additional Context that I tried various forms of escaping the space and quoting the arguments, including the one you posted. Can you confirm that this actually works for you, because it does not for me,

**Comment by andrew-schlackman** [comment]
Sorry, I failed to mention I am currently working in Windows. For anyone coming across this in the future, the answer turned out to be the following:

```
terraform taint "random_integer.host_index[\"the fourth\"]"
```

Sorry for the unnecessary issue.
