### ISSUE TITLE
introduce timeout in remote-exec provisioner 

### ISSUE THREAD

**Issue by Anil-CM** [hashicorp/terraform#24431]
Hi there,
Currently terraform remote-exec provisioner not implementing the timeout functionality. This will lead to blocking the terraform execution if user is trying to run infinite-loop script or running a command which never ends.
For example running shell command - “while :; do echo ‘Hello World!’; sleep 1; done”
This would cause provisioner run infinitely.
### Current Terraform Version
```
terraform v0.11.x
terraform v0.12.x
```
### Use-cases
Implementation of timeouts is only specific to resources which are asynchronously provisioned. By introducing the timeout, provisioner can restrict the execution time of the command. If the command execution taking more than default/maximum timeout, the provisioner needs to stop executing the command(sending KILL signal to the remote process) and return.
### Attempted Solutions
To solve the problem
1. introduced the timeout in remote-exec provisioner schema.
2. Read timeout if specified or take the default value.
3. Pass timeout value to communicator-start method
4. start timer before executing the command in start() in communicator implementation
5. Handle the command execution.status and timer
6. If timer triggers timeout before command is completed, send KILL signal to remote command and stop the ssh/winrm session
### Proposal
If timeout is introduced in the provisioner the example would look like as shown below
```
resource “null_resource” “test-remote-exec-1” {
 connection {
  type    = “ssh”
  user    = “root”
  host    = “x.x.x.x”
  password  = “*******”
 }
 provisioner “remote-exec” {
  inline = [“while :; do echo ‘Hello world!’; sleep 1; done”]
  timeout = 45
 }
}
```
When this example executed, after 45 seconds provisioner will send SIGKILL to the remote process and terminate shell command.

**Comment by pkolyvas** [comment]
@Anil-CM 

Thanks for your thoughtful contribution, the proposal makes a lot of sense. 

I believe #17387 is focused on the same feature  and problem space however, so I'm going to close this one out due to the overlap.
