### ISSUE TITLE
Crash with akamai provider

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform#24453]
### Terraform Version
Terraform v0.12.24
 + provider.akamai v0.5.0
 + provider.aws v2.54.0
 + provider.template v2.1.2

### Crash Output
see attachment

### Expected Behavior
no crash

### Actual Behavior
crash

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

[crash.log.gz](https://github.com/hashicorp/terraform/files/4381742/crash.log.gz)

**Comment by danieldreier** [comment]
@ericrichtert thanks for reporting this issue! It looks to me like it is most likely an issue in the akamai provider. Can you please open this issue with [that provider](https://github.com/terraform-providers/terraform-provider-akamai/issues), which is maintained by Akamai? It would probably be helpful to them if your new issue report included the specific conditions needed to reproduce this, e.g. a sample terraform config needed. If they think this is a core issue we can re-open this an investigate on our side.
