### ISSUE TITLE
provisioner/chef: self variable not available in chef provisioner's node_name

### ISSUE THREAD

**Issue by fishnix** [hashicorp/terraform#2446]
I would like to do this `node_name = "${self.id}"` using the aws_instance provider and the chef provisioner, but I get this error:

```
Errors:

  * aws_instance.jenkins_master1: Key not found: node_name
```

**Comment by svanharmelen** [comment]
@fishnix could you post a small example so I can take a look at maybe run some tests?

**Comment by mitchellh** [comment]
Marking as fixed due to the PRs.
