### ISSUE TITLE
Variable type defined as regex

### ISSUE THREAD

**Issue by yzargari** [hashicorp/terraform#24489]
Hello,

I've been writing a lot of modules recently and found many use-cases for new variable types. For example, if I could define a variable as type IP - then Terraform would validate the input matches an IP address format. More examples could include URL, directory, AWS ARN, etc.

Eventually, I reached a conclusion that for the majority of the cases, a regex definition of a variable type would do - for example, IP address would be defined as `^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$`

Thanks,
Yosi

**Comment by pkolyvas** [comment]
@yzargari Perhaps it might be worth looking our our experimental variable validation rules? 

https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules

In the near term, we're not considering adding a regex variable type, but we hope variable validation is a compromise that offers greater flexibility in the long run.
