### ISSUE TITLE
Terraform does not respect dependency of azurerm_user_assigned_identity on its parent resource group

### ISSUE THREAD

**Issue by silvermeru** [hashicorp/terraform#24486]
### Terraform Version 
```
0.12.23
```

### Terraform Configuration Files
```hcl
resource "azurerm_user_assigned_identity" "instance" {
  resource_group_name = "${local.prefix}-web-nr"
  location            = local.primary_location

  name = "${local.prefix}-web-identity"
}
```

### Debug Output
The terraform trace log was 7z compressed and then pgp encrypted using the HashiCorp public key - 
https://drive.google.com/open?id=1kP2dA5BGxj8WN_Gy3Eg25ghEGC4Ec6FT

### Expected Behavior
The `azurerm_user_assigned_identity` resource is expected to be created after the resource group to which it belongs ("${local.prefix}-web-nr").

### Actual Behavior
Terraform attempts to create them concurrently. The net result - it complains about non existing resource group.

### Additional Context
Here is our plan file (pgp encrypted) - https://drive.google.com/open?id=1mWgKTPjjoIaCLsPpzIlWJr_V9HFbqCJW

This is the standard output - https://drive.google.com/open?id=12UCvgYlh01FNES7a4eh6eEBbQVlOXi4X

Running the code the second time works, because the resource group already exists.

I think this is the core issue, rather than the provider, because dependency computation is a core functionality.

**Comment by MarkKharitonov** [comment]
I think I found what is the problem. We do not specify the resource group name through the resource itself, but through the name string. I have just changed it to:
```hcl
resource "azurerm_user_assigned_identity" "instance" {
  resource_group_name = azurerm_resource_group.non_regional_web_rg.name
  location            = azurerm_resource_group.non_regional_web_rg.location

  name = "${local.prefix}-web-identity"
}
```
And testing now.

**Comment by MarkKharitonov** [comment]
Yup, that was the problem. This was a bug in our code.

**Comment by danieldreier** [comment]
Thanks for reporting back!
