### ISSUE TITLE
mysql RDS connectivity issue 

### ISSUE THREAD

**Issue by vgprash24** [hashicorp/terraform#24488]
[root@ip-172-31-86-171 db2]# terraform -version
Terraform v0.11.13
+ provider.aws v2.54.0
=================================

[root@ip-172-31-86-171 db2]# cat db2.tf
data "aws_security_group" "allow" {
  filter {
    name   = "group-name"
    values = ["*allow-ssh*"]
  }
  depends_on = ["aws_security_group.allow-ssh"]
}

resource "aws_db_subnet_group" "sample" {
  name       = "main"
  subnet_ids = ["${aws_subnet.main-public-1.id}", "${aws_subnet.main-public-2.id}"]

  tags = {
    Name = "main"
  }
}
resource "aws_db_instance" "default" {
  identifier = "mydb"
  engine = "mysql"
  engine_version = "5.7.19"
  instance_class = "db.t2.micro"
  name = "mydb"
  username = "sai"
  password = ".,lkoi98"
  vpc_security_group_ids = ["${data.aws_security_group.allow.id}"]
  db_subnet_group_name = "main"
  parameter_group_name = "default.mysql5.7"
  apply_immediately = true
  allocated_storage = "20"
  #iops = 1000

  # disable backups to create DB faster
  backup_retention_period = 0

  enabled_cloudwatch_logs_exports = ["audit", "general"]

  # Snapshot name upon DB deletion
  final_snapshot_identifier = "mydb-rds"

  # Database Deletion Protection
  deletion_protection = false

  lifecycle {
    #ignore_changes = ["allocated_storage","iops"]
  }

}
[root@ip-172-31-86-171 db2]#
================================
Above is my code to create the DB instance. I have another instance running with wordpress application, i am trying to connect with DB but it is not connecting. I also opened mysql port in security group. 

can u help me to figure it out

**Comment by vgprash24** [comment]
when i enter my password, username and endpoint connection it is coming like  "Error connecting with Database"

**Comment by pkolyvas** [comment]
Hey @vgprash24,

Thanks for taking the time to write us. 

Due to the number of issues we work through here, we encourage our community to ask questions over at our [community forums](https://discuss.hashicorp.com/c/terraform-core/27).
