### ISSUE TITLE
Unreliable keybase.io installation procedure dependency

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [hashicorp/terraform#24498]
### Terraform Version

```
# Since the issue prevents me from installating terraform, obviously, I have 
# no terraform -v  output to perform
```

### Terraform Configuration Files

```hcl
# same as for terraform -v
```

### Crash Output

![sometimes it snows in april](https://github.com/Jean-Baptiste-Lasselle/for-fellow-developers/raw/master/docuementation/impr.ecrans/terraform/TERRAFORM_KEYBASE_IO_Firefox_Screenshot_2020-03-26T07-13-53.508Z.png)

### Expected Behavior

The keybase.io GPG public key to not ever be unavailable, whatever key server is in use.

### Actual Behavior

I launched docker builds, in which I install terraform if and only if, The complete Content Trust is reached, stating with checking signatures of checksums files 

### Steps to Reproduce

* Step 1 Make unavalailable the key on keybase.io, 
* Step 2 and run the secure terraform installation, as such : 

```bash
#/bin/bash

# ---
# Can be a commit hash, a branch name, or a tag (be it a release or not).
# from this git repo : https://github.com/hashicorp/terraform
# I privately mirror it on git@gitlab.com:second-bureau/bellerophon/terraform/terraform.git
# You should also reference your own private mirror of this repo, in your automation recipes
# because then you will remove any external service build time and runtime dependency from your CI/CD factory, your pipelines run faster, with more reliability.
export TERRAFORM_VERSION=${TERRAFORM_VERSION:-'0.12.24'}
# ---
# can be :
# => 'darwin' (mac os)
# => 'linux' (for any GNU/Linux distrib.)
# Terraform does not support Windows
#
export TERRAFORM_OS=${TERRAFORM_OS:-'linux'}
# ---
# can be :
# => 'amd64' (mac os)
# Terraform does not support any other CPU ARCH to my knowledge
#
export TERRAFORM_CPU_ARCH=${TERRAFORM_CPU_ARCH:-'amd64'}


export TERRAFORM_PKG_DWLD_URI="https://github.com/hashicorp/terraform/archive/terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip"
export TERRAFORM_PKG_DWLD_URI="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip"

export TERRAFORM_CHECKSUMS_FILE_DWLD_URI="https://releases.hashicorp.com/terraform/0.12.24/terraform_${TERRAFORM_VERSION}_SHA256SUMS"
# Signature of the TERRAFORM_CHECKSUMS_FILE_DWLD_URI, to verify the signature of the checksum file.
export TERRAFORM_CHECKSUMS_FILE_SIGNATURE_DWLD_URI="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig"
# HASHICORP_PGP_SIGNING_KEY => to verify [TERRAFORM_CHECKSUMS_FILE_SIGNATURE_DWLD_URI]
# see https://www.hashicorp.com/security.html#secure-communications to find again the key its fingerprint and doc on how to automate retreiving key.
export HASHICORP_PGP_SIGNING_KEY=hashicorp.pgp.key
curl https://keybase.io/hashicorp/pgp_keys.asc -o ${HASHICORP_PGP_SIGNING_KEY}


echo '---------------------------------------------------------------'
echo ' Commandes GPG dans le conteneur kubeone#./install-terraform.sh'
echo "----------------------- [$(pwd)] "
echo '---------------------------------------------------------------'
ls -allh .
ls -allh ./${HASHICORP_PGP_SIGNING_KEY}
echo '---------------------------------------------------------------'

# TODO : générer une clef ?
echo '---------------------------------------------------------------'
echo '--- GPG FULL GENERATE KEY :  '
echo '---------------------------------------------------------------'
# gpg --full-generate-key
gpg --list-keys
echo '---------------------------------------------------------------'

# curl https://keybase.io/hashicorp/pgp_keys.asc | gpg --import
gpg --batch --import ./${HASHICORP_PGP_SIGNING_KEY}
cat ./${HASHICORP_PGP_SIGNING_KEY}
# I need a PGP Key for this container, to
# sign HashiCorp's Key and make it a "trusted" key in
# the eyes of [gpg]
# ---
# To Sign an imported key with an utltimately
# trusted key :
#
# https://raymii.org/s/articles/GPG_noninteractive_batch_sign_trust_and_send_gnupg_keys.html
# ---
# Now silently ultimately trusting the newly added HashiCorp PGP Keys
# https://www.rzegocki.pl/blog/how-to-make-gnupg2-to-fall-in-love-with-docker/
for fpr in $(gpg --list-keys --with-colons  | awk -F: '/fpr:/ {print $10}' | sort -u); do  echo -e "5\ny\n" |  gpg --batch --command-fd 0 --expert --edit-key $fpr trust; done

gpg --list-keys
# exit 99
# Non, il faut générer une seule et unique fois une seule clef GPG





checkIntegrityUsingTerraformChecksums () {
  echo '--------------------------------------------------------'
  echo '---- VERIF CLEF TRUST ULTIMATE HASHICORP : '
  echo '--------------------------------------------------------'
  gpg --list-keys
  echo '--------------------------------------------------------'
  curl -LO "${TERRAFORM_CHECKSUMS_FILE_DWLD_URI}"
  curl -LO "${TERRAFORM_CHECKSUMS_FILE_SIGNATURE_DWLD_URI}"
  gpg --verify ./terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig ./terraform_${TERRAFORM_VERSION}_SHA256SUMS
  if [ "$?" == "0" ]; then
    echo "Successfully checked trusted HashiCorp signature of the downloaded checksum file [./terraform_${TERRAFORM_VERSION}_SHA256SUMS]"
    echo "Proceeding installation"
  else
    echo "HashiCorp signature check  of the downloaded checksum file [./terraform_${TERRAFORM_VERSION}_SHA256SUMS] failed."
    echo "check yourself the Hashicorp signature running the following command : "
    echo "   gpg --verify $(pwd)/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig $(pwd)/terraform_${TERRAFORM_VERSION}_SHA256SUMS"
    exit 3
  fi;
  cat terraform_${TERRAFORM_VERSION}_SHA256SUMS | grep ${TERRAFORM_OS} | grep ${TERRAFORM_CPU_ARCH} | tee ./terraform.integrity.checksum
  echo "------------------------------------------------------------------------"
  echo " [$0#checkIntegrityUsingTerraformChecksums ()] Contenu de [./terraform_${TERRAFORM_VERSION}_SHA256SUMS]   "
  echo "------------------------------------------------------------------------"
  cat ./terraform_${TERRAFORM_VERSION}_SHA256SUMS
  echo "------------------------------------------------------------------------"
  sha256sum -c ./terraform.integrity.checksum
  if [ "$?" == "0" ]; then
    echo "Successfully checked integrity of the downloaded terraform version ${TERRAFORM_VERSION} package for ${TERRAFORM_OS} OS on ${TERRAFORM_CPU_ARCH} cpu"
    echo "Proceeding installation"
  else
    echo "Integrity check failed for the downloaded terraform version ${TERRAFORM_VERSION} package for ${TERRAFORM_OS} OS on ${TERRAFORM_CPU_ARCH} cpu"
    echo "check yourself the integrity breach running the following command : "
    echo "   zip -T $(pwd)/terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip"
    exit 5
  fi;
}

# ---
# That's where we 'll install Terraform on the nix system' filesystem
# export TERRAFORM_INTALLATION_HOME=${BUMBLEBEE_HOME_INSIDE_CONTAINER}/terraform/installation/${TERRAFORM_VERSION}
echo " ENV CHECK - TERRAFORM_INTALLATION_HOME=[${BUMBLEBEE_HOME_INSIDE_CONTAINER}/terraform/installation/${TERRAFORM_VERSION}]"
# ---
# Downloading Terraform executable

curl -LO "${TERRAFORM_PKG_DWLD_URI}"

ls -allh

installTerraform () {
  # TODO create terraform user group, and give ownership
  groupadd terraform
  # Adding
  usermod -aG terraform ${BUMBLEBEE_LX_USERNAME}
  mkdir -p ${TERRAFORM_INSTALLATION_HOME}/
  unzip ./terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip -d ${TERRAFORM_INSTALLATION_HOME}/
  echo '-----------------------------------------------------------------------'
  echo "Le contenu de [TERRAFORM_INSTALLATION_HOME=[${TERRAFORM_INSTALLATION_HOME}]]"
  echo " juste après le dezippe : "
  echo '-----------------------------------------------------------------------'
  ls -allh ${TERRAFORM_INSTALLATION_HOME}/
  echo '-----------------------------------------------------------------------'
  ln -s ${TERRAFORM_INSTALLATION_HOME}/terraform /usr/local/bin/terraform
}

# installTerraform
# terraform --version

# chmod a+rwx ./terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip
echo ''
echo " Je suis ici [$(pwd)] et les fichiers présents sont : "
echo '------------------------------------------------------------'
ls -allh .
echo '------------------------------------------------------------'
echo " y a til [./terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip] ?"
echo '------------------------------------------------------------'
echo " test d'existence de [./terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip] : "
echo '------------------------------------------------------------'
ls -allh ./terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip
echo '------------------------------------------------------------'
echo " execution de [zip -T ./terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip] : "
echo '------------------------------------------------------------'
echo ''
# zip -T /go/terraform_0.12.24_linux_amd64.zip
# zip -T ./terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip


if [ "$?" == "0" ]; then
  # echo "Successfully checked integrity of the downloaded terraform version ${TERRAFORM_VERSION} package for ${TERRAFORM_OS} OS on ${TERRAFORM_CPU_ARCH} cpu"
  echo "Skipped checking integrity of the downloaded terraform version ${TERRAFORM_VERSION} package for ${TERRAFORM_OS} OS on ${TERRAFORM_CPU_ARCH} cpu"
  echo "Proceeding installation"
  checkIntegrityUsingTerraformChecksums
  installTerraform
else
  echo "Integrity check failed for the downloaded terraform version ${TERRAFORM_VERSION} package for ${TERRAFORM_OS} OS on ${TERRAFORM_CPU_ARCH} cpu"
  echo "check yourself the integrity breach running the following command : "
  echo "   zip -T $(pwd)/terraform_${TERRAFORM_VERSION}_${TERRAFORM_OS}_${TERRAFORM_CPU_ARCH}.zip"
  exit 3
fi;

terraform --version
```

### References

There are no issue related as of today, to that issue, as the https://github.com/hashicorp/terraform/issues?q=is%3Aissue+keybase.io+ search will show you : only 9 issues mention the term `keybase.io`, and I am sure anyone having experienced that issue, would have mentioned that term for sure.

Funnily, It makes me wonder how many people check signatures ... 
So I woke up this sunday morning, so happy "Yeah, I'm gonna rotate my passwords today" ^^

Oh, most importantly your work is AWEEESOME!  I love it ! :smile: :heart:

**Comment by jbardin** [comment]
Hi @Jean-Baptiste-Lasselle 

Thanks for filing the issue. Can you explain further what exactly the unexpected behavior is here? Is it just that the Keybase server may not be available, which interrupts your automation?

If that is the issue, can I ask why you are relying on Keybase as a part of your automation here? You have a reference to the security page with the public key data, ID and fingerprint which you could verify and store, and the key is stored in other public key servers as well.

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @jbardin 

Thank you so much for such a quick answer. I will bring further informations, but I want to immediately give you indication : 

* When I experenced the issue, the Keybase.io service was up n running : I first wondered if it was keybase indeed.
* But it appeared that keybase.io was up , but it seemed lke the hashicorp team had teared down /deleted  the PGP public key from the hashicorp keybase.io account, as you can see on the screenshot I took immediately, to report the issue (_**a mistery user with no key**_) : 

![](https://github.com/Jean-Baptiste-Lasselle/for-fellow-developers/raw/master/documentation/impr.ecrans/terraform/TERRAFORM_KEYBASE_IO_Firefox_Screenshot_2020-03-26T07-13-53.508Z.png)

From my chair, It is hard, if not impossible to tell whether it was a keybase.io issue or a hashicorp team operation that deleted the PGP public key , but it felt like it was hashicorp, since keybase.io web front was up, plus on my personal account https://keybase.io/jblasselle well my PGP Key was there, I had no problem with it...

# Reference in the docuementation, to the Keybse.io account 

Here : https://www.hashicorp.com/security.html#checksum-verification

Quoting : 

<p>If you would like to secure your communications with us, the following PGP key can be used. You can also fetch our key from Keybase or from most keyservers with the key ID <code>51852D87348FFC4C</code> and fingerprint
<code>91A6 E7F8 5D05 C656 30BE F189 5185 2D87 348F FC4C</code>.</p>

**Comment by danieldreier** [comment]
@Jean-Baptiste-Lasselle if I understand correctly, you're trying to automate key retrieval in CI and you have been doing that using keybase, and what you're seeing is that the company key just disappeared from keybase.

If I'm understanding those needs correctly, I think you can run the following in CI:
```gpg --recv-keys 51852D87348FFC4C```

This will retrieve HashiCorp's public GPG key from key servers. Alternatively, you can store the GPG key listed on the web site permanently and not re-download it each time. You can expect this key to be stable; there is no need to re-download it from the web site with every CI run.

Next, you can verify checksums as per the "Checksum Verification" section of the [HashiCorp Security Policy](https://www.hashicorp.com/security.html#secure-communications) site.

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi Mister Dreier , Thank you so much for your answer.

> 
> if I understand correctly, you're trying to automate key retrieval in CI and you have been doing that using keybase, and what you're seeing is that the company key just disappeared from keybase.
> 

Now I have the most serious reference, from HashiCorp  Core Team, to justifiy to my management why we no have to invest into a solution to manage a key referential, to monitor any future change of PGP public keys of all dependencies (which is a whole universe).

I needed to justify that work which is a huge workload, a thrilling challenge, and we have to justify to investors. 

All I will have to say, is "believe me, if HashiCorp publicly says we have to work like this, I guarantee 99% of the companies in the world are not even close from having a better solution. So I propose you to put behind 99% of world, and discuss the matter again then."

I now thank you very much, and want to say I highly appreciate getting a direct answer from such a distinguished engineer, Mr. Dreier.

I consider this issue closed.
