### ISSUE TITLE
AWS TAG POLICY CONTENT LIMIT EXCEEDED WHILE IN WEB CONSOLE IT'S INTERPRETED AS CORRECT

### ISSUE THREAD

**Issue by rlig** [hashicorp/terraform#24512]
Hello,

### **Terraform Version**
0.12.19

### **Terraform Configuration Files**
I'm trying to create a **tag policy** using **aws_organizations_policy** resource just by passing json file as template to **content** argument, example below:

```
resource "aws_organizations_policy" "aws_master_parent_policy" {
  name        = "AWS_MASTER_PARENT_POLICY_"
  type        = "TAG_POLICY"
  description = "Policy for master tag"

  content = data.template_file.aws_master_parent_policy.rendered
}
```

Tried also using **templatefile**(https://www.terraform.io/docs/configuration/functions/templatefile.html) function. Same issue.

### **Actual Behavior**
Problem is, when I create that using aws console I do not meet any errors as the whole policy has about 2000 characters (limit is 2500). When I try to create that using terraform I meet error:
<img width="1659" alt="Zrzut ekranu 2020-03-31 o 18 28 00" src="https://user-images.githubusercontent.com/32437712/78051657-4c377d80-737e-11ea-9479-2cf9b3295f3d.png">

### **Expected Behaviour**
Policy created.  Its size is valid. 

Regards
Rlig

**Comment by danieldreier** [comment]
Hi @rlig! This looks to me like an issue with the [Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws) rather than  Terraform core. I've labeled this as `provider/aws` and HashiBot will be moving this issue over to that repository so they can take a look at it.
