### ISSUE TITLE
Terraform login prompt should require `yes` for approval

### ISSUE THREAD

**Issue by pkolyvas** [hashicorp/terraform#24514]
### Current Terraform Version
```
0.12.21+
```

### Use-cases
The `terraform login` command requires acceptance to proceed. 

Currently, acceptance of the login workflow requires a `y` input on the CLI. The prompt is currently `y/n`. This is inconsistent with Terraform's current approval prompt which requires an explicit `yes`.

### Proposal
Alter the approval of `terraform login` to `yes`. This would be consistent with current workflows.

If Terraform Login is being used in automation this is a breaking change.

**Comment by mmmorris1975** [comment]
Why does this _have_ to be a breaking change?  Couldn't you update both prompts to accept either `y` or `yes` (case in-sensitive), and still get consistent behavior?
