### ISSUE TITLE
Add a Terraform Sensitive function, and/or sensitive block to allow your config to specify what you deem sensitive

### ISSUE THREAD

**Issue by WilliamABradley** [hashicorp/terraform#24529]
### Current Terraform Version

```
v0.12.21
```

### Use-cases

Currently we depend on providers to deem what they provide sensitive parameters for, e.g. set_sensitive in helm_release, etc. This isn't very flexible if there is something you deem sensitive that gives you no choice to specify as sensitive to the resource.

Sometimes these providers provide you no other solution, e.g. if you want to pass sensitive info through to the external data source, data "external".

That means allowing our terraform to contain sensitive information, or create a script to work around this issue, e.g. using a null_resource provisioner to send that data to a file, to be be picked up by the external data source. 

### Attempted Solutions

- Use null_resource to run the scripts instead, ugly, hacky, hard to pull data back in to the terraform.

### Proposal

- Create a function that you can wrap a value in, which will deem it sensitive and not show in diffs.
  e.g.
  ```tf
  locals {
    password = sensitive("myPass")
  }
  
  data "external" "login" {
    program = [...]
    query = {
      site = "mysite.com/login"
      password = local.password
    }
  }
  ``` 
  Then the diffs would show that the property alone in the query was sensitive, and it would allow you to use resources, data sources that don't support sensitive properties.

- Create a sensitive property for all resources and data sources, like ignore_changes, that marks outputs of resources as sensitive.

  This would work by hiding outputs of a resource or data source as sensitive in the diff, which would allow you to achieve the same goal as the sensitive function, but also hide things that shouldn't be seen, perhaps in error of the provider, e.g. helm_release might leak sensitive properties from `set_sensitive` in diffs, because of it's metadata output: https://github.com/terraform-providers/terraform-provider-helm/issues/424

  You could wait for the fix to be applied in the provider, while you leave your terraform vulnerable, or you apply the fix yourself, e.g.

  ```tf
  resource "helm_release" "registry" {
    name            = "docker-registry"
    namespace       = "docker-registry"
    chart           = "docker-registry"
    repository      = "stable"
    version         = "1.9.1"
    cleanup_on_fail = true

    # We ignore changes to all set_sensitive, as it causes unnecessary diffs.
    set_sensitive {
      name  = "secrets.htpasswd"
      value = local.credentials
    }

    lifecycle {
      ignore_changes = [set_sensitive]
    }
  
    sensitive_properties {
      version # Hide version parameter
      output.metadata # Hide metadata output
    }
  }
  ```

### References

- https://github.com/terraform-providers/terraform-provider-helm/issues/424 - Sensitive output "metadata"

**Comment by pselle** [comment]
👋 I believe upcoming changes in Terraform 0.14 may address this request. Terraform 0.14 adds an optional `sensitive` attribute to variables, and experimental support for extending sensitivity to provider-defined sensitive attributes

Please refer to the upgrade guide: https://github.com/hashicorp/terraform/blob/v0.14/website/upgrade-guides/0-14.html.markdown#sensitive-values-in-plan-output for some details on this feature, which you can test on the 0.14 beta versions.

**Comment by balupton** [comment]
@pselle does the implementation of this `sensitive` flag combined with terraform cloud encryption at rest mean that the warnings at:

- https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key
- https://registry.terraform.io/providers/hashicorp/tls/latest/docs#example-usage

will be able to go away?

**Comment by pselle** [comment]
@balupton The warnings about sensitive data in state still apply to this enhanced sensitivity -- the threat area this covers is logs, UI output, that ilk. Since the warnings there are related to state, I would say that warning should remain.

**Comment by balupton** [comment]
> @balupton The warnings about sensitive data in state still apply to this enhanced sensitivity -- the threat area this covers is logs, UI output, that ilk. Since the warnings there are related to state, I would say that warning should remain.

Ok cool, is there a plan for Terraform 0.15 or later to expand on this sensitive functionally, to safely protect the sensitive values at state?

**Comment by pselle** [comment]
@balupton Yes, it is something we want to do, but it's not in the near-term timeline for implementation (that is, likely not 0.15).

**Comment by apparentlymart** [comment]
The feature that @pselle mentioned earlier, [marking variables as sensitive](https://www.terraform.io/docs/configuration/variables.html#suppressing-values-in-cli-output), is now available in Terraform v0.14.0. If you try that out and have further feedback about other use-cases it doesn't cover, please feel free to open a new feature request to discuss those. Thanks!

**Comment by balupton** [comment]
As this is now closed, for encryption of sensitive values at sate, is this the successor issue?
https://github.com/hashicorp/terraform/issues/9556

Also, seems this issue can also now be closed:
https://github.com/hashicorp/terraform/issues/16643

**Comment by pselle** [comment]
@balupton It might be! There are probably multiple issues that discuss encrypting values in state -- the one you've linked appears to be related to encrypting the whole state, rather than partially encrypting state (sensitive-values only). Which is to say: yes, _but_ there are probably multiple issues and strategies out there.

Thank you for flagging the other issue! I've since closed it 🎉
