### ISSUE TITLE
Allow deletion of default state for the S3 backend

### ISSUE THREAD

**Issue by walkafwalka** [hashicorp/terraform#24538]
### Current Terraform Version

```
Terraform v0.12.24
```

### Use-cases

When using workspaces, you do not always need the default workspace. For example, I have a workspace for each environment, dev and prod, but I do not use default.

### Attempted Solutions

```
$ terraform workspace delete default
Releasing state lock. This may take a few moments...
can't delete default state
```

### Proposal

Allow the deletion of the default state for the S3 backend.

**Comment by pkolyvas** [comment]
Thanks for taking the time to send us some feedback @walkafwalka.

At the current time we don't have any plans to enable removal or renaming of the default workspace in the near/middle term. 

That said, I'm always open to hearing from our community, so if you'd like to chat Terraform you can always reach me using the info on my GitHub profile.
