### ISSUE TITLE
Grafana provider does not allow to add settings to the alert notification

### ISSUE THREAD

**Issue by edevost** [hashicorp/terraform#24537]
### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.55.0
+ provider.grafana v1.5.0
```

### Terraform Configuration Files

```hcl
resource "grafana_alert_notification" "slack" {
  name = "Slack team"
  type = "slack"

  settings {
    slack = "xxx"
  }
}
```

### Crash Output

Error: Unsupported block type

  on main.tf line 39, in resource "grafana_alert_notification" "slack":
  39:   settings {

Blocks of type "settings" are not expected here. Did you mean to define
argument "settings"? If so, use the equals sign to assign it a value.
### Expected Behavior

The alerting notification channel should be added.
### Actual Behavior

Unexpected block "settings"
### Additional Context

 The config is taken straight from the Terraform documentation.

**Comment by remilapeyre** [comment]
Hi @edevost, it looks like you are having an issue specific to the Grafana provider. In that case, you will want to open the issue directly at https://github.com/terraform-providers/terraform-provider-grafana, this repository is for issues with Terraform itself.
