### ISSUE TITLE
locals are not working with count in modules

### ISSUE THREAD

**Issue by ibacalu** [hashicorp/terraform#24546]
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
# google_service_account_key
variable "enabled" {
  default = true
}

locals {
  enabled = true
}

resource "google_service_account_key" "default" {
  count = local.enabled ? 1 : 0

  service_account_id = local.service_account_id
  key_algorithm      = local.key_algorithm
  public_key_type    = local.public_key_type
  private_key_type   = local.private_key_type

  provider = google-beta
}

# google_service_account
module "key" {
  source = "../google_service_account_key"
  service_account_id = google_service_account.default.* [0].email
}
```

### Expected Behavior

```
# module.key.google_service_account_key.default[0] will be created
  + resource "google_service_account_key" "default" {
      + id                      = (known after apply)
      + key_algorithm           = (known after apply)
      + name                    = (known after apply)
      + pgp_key                 = (known after apply)
      + private_key             = (sensitive value)
      + private_key_encrypted   = (known after apply)
      + private_key_fingerprint = (known after apply)
      + private_key_type        = (known after apply)
      + public_key              = (known after apply)
      + public_key_type         = (known after apply)
      + service_account_id      = (known after apply)
      + valid_after             = (known after apply)
      + valid_before            = (known after apply)
    }
```
### Actual Behavior

```
Error: Invalid count argument

  on ../google_service_account_key/main.tf line 23, in resource "google_service_account_key" "default":
  23:   count = local.enabled ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
### Additional Context

If we replace `local.enabled` with `var.enabled` in `google_service_account_key` module, it works.
Is this expected behaviour?

**Comment by ljluestc** [comment]
rgument of the google_service_account_key resource. Terraform can't determine the value of local.enabled during the planning phase because it depends on resource attributes that can only be known after applying the configuration.

To work around this issue, you can follow the error message's suggestion and use the -target argument to apply only the resources that the count argument depends on. Here's how you can do that:

First, you need to apply the resources that the count depends on. In this case, it seems to be the google_service_account module. Run the following command:
```
terraform apply -target=module.key
```

**Comment by crw** [comment]
Thanks for the question and thanks for the response, @ljluestc! I am going to close this issue as this is a question better handled on [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers. Thanks!
