### ISSUE TITLE
Azure Event Hub Namespace - for_each does not work for network rule blocks

### ISSUE THREAD

**Issue by eliasvakkuri** [hashicorp/terraform#24544]
### Terraform Version

```
Terraform v0.12.24
provider.azuread v0.8.0
provider.azurerm v2.1.0
provider.random v2.2.1
```

### Terraform Configuration Files

```hcl
terraform {}

provider "azurerm" {
  version  = "~> 2"
  features {}
}

variable "eventhub_namespace_allowed_ips_list" {
  type        = list(string)
  default     = []
  description = <<-EOT
  "List of IP addresses to allow in Event Hub Namespace firewall. Provide in full
  CIDR format with the subnet mask suffix"
  EOT
}

resource azurerm_resource_group rg {
  name     = "elias-test-rg"
  location = "westeurope"
}

resource "azurerm_eventhub_namespace" "eventhub_namespace" {
  name                 = "elias-test-ehnamespace"
  location             = azurerm_resource_group.rg.location
  resource_group_name  = azurerm_resource_group.rg.name
  sku                  = "Standard"
  capacity             = 1
  auto_inflate_enabled = true

  network_rulesets {
    default_action = "Deny"

    dynamic "ip_rule" {
      for_each = var.eventhub_namespace_allowed_ips_list

      content {
        ip_mask = ip_rule.value
        action  = "Allow"
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/eliasvakkuri/b53baca45c6d5ae40da58fbcd71fd0a5

### Crash Output

No crash

### Expected Behavior

Similar to other resources where IP and subnet firewall rules are set with blocks within the main resource, Terraform creates the correct number of these blocks.

### Actual Behavior

Error similar to hashicorp/terraform#22340.

When trying to use for_each to set a parametrized number of ip_rule blocks or virtual_network_rule blocks, the following error is raised:
 ```
Error: Unknown variable

  on main.tf line 34, in resource "azurerm_eventhub_namespace" "eventhub_namespace":
  34:       for_each = var.eventhub_namespace_allowed_ips_list

There is no variable named "var".
```

There is no variable named "var".
However, this works for some reason:

```hcl
ip_rule = [
      for ip in var.eventhub_namespace_allowed_ips_list : {
        ip_mask = ip
        action   = "Allow"
   }
]
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

No special circumstances, running locally installed Terraform directly from command line

### References

- #22340

**Comment by danieldreier** [comment]
Thanks for reporting this! If I'm reading the log output correctly, I believe the error is coming from the AzureRM provider, and I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. 

I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. AzureRM folks - if I read this wrong, feel free to send it back our way.

**Comment by eliasvakkuri** [comment]
Hi @danieldreier , thanks for taking a look at this. I actually posted this issue first in the Azure provider GitHub, but I was instructed to post to general Terraform instead. Let's see what happens now :)
