### ISSUE TITLE
got crash report wanted to post issue 

### ISSUE THREAD

**Issue by joestein** [hashicorp/terraform#2456]
https://gist.github.com/joestein/4b737f6a3ab25aa42ca7

Not sure if it is fixed or if I am doing something wrong or new issue to figure out

**Comment by mitchellh** [comment]
This is indeed now fixed in master, will be part of 0.6.0 coming out shortly!

**Comment by joestein** [comment]
here is the failure from master https://gist.github.com/joestein/e01e707366c0b8cedc76 just tried now

**Comment by mitchellh** [comment]
Yep, the fix is in a PR right now, but will be merged before release. I just opened it today. :)

**Comment by mitchellh** [comment]
Actually the line number looks slightly different, I'll fix that one in the same PR though: https://github.com/hashicorp/terraform/pull/2449/files

**Comment by mitchellh** [comment]
It was actually the same error, I just didn't realize that even the value of the array could be nil. Fixed in that PR.

**Comment by joestein** [comment]
Yup, that worked, thanks!
