### ISSUE TITLE
`terraform import` should propagate provider config to the module as `terraform plan` does

### ISSUE THREAD

**Issue by pazderak** [hashicorp/terraform#24570]
### Terraform Version

```
0.12.23
```

### Terraform Configuration Files

```hcl
# Terraform state
terraform {
  backend "s3" {
  }
}

# Variables
variable "rabbitmq_server_endpoint" {
  type = string
}

variable "rabbitmq_server_password" {
  type = string
}

variable "rabbitmq_server_username" {
  type = string
}

variable "vault_server_address" {
  type = string
}

variable "vault_server_token" {
  type = string
}

# Configure the MySQL providers
provider "mysql" {
  version  = "~> 1.9"
  alias    = "module_create_db_timeline"
  endpoint = "<redacted>"
  username = "<redacted>"
  password = "<redacted>"
}

provider "mysql" {
  version  = "~> 1.9"
  alias    = "module_create_db_messaging"
  endpoint = "<redacted>"
  username = "<redacted>"
  password = "<redacted>"
}


# Module
module "module_create_db" {
  source = "./../../modules/module_create_db/q/qa1"
  providers = {
    mysql.module_create_db_timeline  = mysql.module_create_db_timeline
    mysql.module_create_db_messaging = mysql.module_create_db_messaging
  }
}
# Vault provider
provider "vault" {
  version = "~> 2.0"
  alias   = "module_vault_db_mounts"
  address = var.vault_server_address
  token   = var.vault_server_token
}

# Module
module "module_vault_db_mounts" {
  source = "./../../modules/module_vault_db_mounts/q/qa1"
  providers = {
    vault.module_vault_db_mounts = vault.module_vault_db_mounts
  }
  vault_server_address     = var.vault_server_address
  vault_server_token       = var.vault_server_token
  mysql_database_timeline  = module.module_create_db.mysql_database_timeline
  mysql_database_messaging = module.module_create_db.mysql_database_messaging
}
# Configure random provider
provider "random" {
  version = "~> 2.2"
  alias   = "module_create_rabbitmq_resources"
}

# Configure RabbitMQ provider
provider "rabbitmq" {
  version  = "~> 1.0"
  alias    = "module_create_rabbitmq_resources"
  endpoint = var.rabbitmq_server_endpoint
  username = var.rabbitmq_server_username
  password = var.rabbitmq_server_password
}

# Configure Vault provider
provider "vault" {
  version = "~> 2.0"
  alias   = "module_create_rabbitmq_resources"
  address = var.vault_server_address
  token   = var.vault_server_token
}

# Module
module "module_create_rabbitmq_resources" {
  source = "./../../modules/module_create_rabbitmq_resources/q/qa1"
  providers = {
    random.module_create_rabbitmq_resources   = random.module_create_rabbitmq_resources
    rabbitmq.module_create_rabbitmq_resources = rabbitmq.module_create_rabbitmq_resources
    vault.module_create_rabbitmq_resources    = vault.module_create_rabbitmq_resources
  }
  vault_server_address     = var.vault_server_address
  vault_server_token       = var.vault_server_token
  rabbitmq_server_endpoint = var.rabbitmq_server_endpoint
  rabbitmq_server_username = var.rabbitmq_server_username
  rabbitmq_server_password = var.rabbitmq_server_password
}
```

### Debug Output

https://gist.github.com/pazderak/0d6b1f1c333acea0042c22099976f601

### Expected Behavior

Terraform should import resource.
### Actual Behavior

module.module_create_rabbitmq_resources.rabbitmq_user.qa1_timeline: Importing from ID "qa1_timeline"...
module.module_create_rabbitmq_resources.rabbitmq_user.qa1_timeline: Import prepared!
  Prepared rabbitmq_user for import
module.module_create_rabbitmq_resources.rabbitmq_user.qa1_timeline: Refreshing state... [id=qa1_timeline]

Error: Get /api/users/qa1_timeline: unsupported protocol scheme ""

### Steps to Reproduce

1. `terraform init` with S3 remote state
2. `terraform validate`
3. `terraform plan -input=false -out terraform.tfplan`
4.  read terraform.tfplan file using Terraform provider SDK and for all resources in the plan generate `terraform import` call
5. `terraform import` from step above

### Additional Context

Terraform runs as part of GitLab CI pipeline which should create resources or import the existing ones. It is called from the another Golang-based binary via `exec.CommandContext` method.
When I run the pipeline, import of MySQL resources works, import of Vault resources too. But import of RabbitMQ resources fails due missing provider configuration (endpoint, username and password are empty values).
Based on my investigation it looks like import of MySQL resources works because providers have static config. Import of Vault resources works because I have set environment variables required by Vault API client (`VAULT_ADDR` and `VAULT_TOKEN`.

**Comment by danieldreier** [comment]
@pazderak I don't understand the "read terraform.tfplan file using Terraform provider SDK and for all resources in the plan generate terraform import call" part of your reproduction steps. I don't have enough detail to run this locally, so I don't know how to further work on this without more information from you.

Are you're saying that during import, the `var.rabbitmq_server_endpoint`, `var.rabbitmq_server_username`, and `var.rabbitmq_server_password`variables are not being loaded as expected? If so, I suspect this reproduction case could be significantly simplified to just a single resource.

**Comment by pazderak** [comment]
@danieldreier - I wrote a tool (small Golang app) which reads Terraform plan and checks if resource exists already or not. The reason is that we created some resources outside of Terraform and now we want to import them. If resource exists, it calls `terraform import` to import given resource to the terraform state.
And yes, I am saying that variables are not being loaded during `terraform import` call.
In meantime I figured out if I call `terraform import` with `-provider` parameter set to the correct provider, import works. But I suspect that `import` should work even without this parameter as `terraform plan` does.

**Comment by danieldreier** [comment]
@pazderak thanks for the additional context here. I had initially been treating this as a bug report, but based on your explanation I think this is more of an enhancement request because this is a known, expected behavior. I think it's a good idea, and I appreciate you pointing it out.

I've labeled this as an import enhancement request to put it on our product manager's radar.

**Comment by mbrancato** [comment]
@danieldreier - is this issue the same where variables are not passed to modules? During `terraform import`, even hard-coded values are not passed to the submodule. If not, I will open a new issue.

A very simple example is below:

root module - main.tf
```hcl
module "sub" {
  source        = "./sub/"
  vault_address = "https://myvault"
}
```

submodule - main.tf
```hcl
provider "vault" {
  address = var.vault_address
}

variable "vault_address" {
  type    = string
  default = "http://localhost:8200"
}

resource "vault_generic_secret" "example" {
  path = "secret/testing"

  data_json = jsonencode({
    foo = "bar"
  })
}
```

Which results in the following:
```
$ terraform import module.sub.vault_generic_secret.example secret/testing

Error: Get http://localhost:8200/v1/auth/token/lookup-self: dial tcp [::1]:8200: connect: connection refused

  on sub/main.tf line 1, in provider "vault":
   1: provider "vault" {

```

**Comment by mbrancato** [comment]
Update - my issues is really #22721
@pazderak - I think you can do this:

In your `module_create_rabbitmq_resources` module, don't set a provider alias (I'm not sure what you're doing, guessing from the code). You can probably just do this:

```hcl
module "module_create_rabbitmq_resources" {
  source = "./../../modules/module_create_rabbitmq_resources/q/qa1"
  providers = {
    random  = random.module_create_rabbitmq_resources
    rabbitmq= rabbitmq.module_create_rabbitmq_resources
    vault   = vault.module_create_rabbitmq_resources
  }
}
```

Note - I removed all the variables as they would already be set in the provider object.

Same thing for this module:

```hcl
module "module_vault_db_mounts" {
  source = "./../../modules/module_vault_db_mounts/q/qa1"
  providers = {
    vault = vault.module_vault_db_mounts
  }
  mysql_database_timeline  = module.module_create_db.mysql_database_timeline
  mysql_database_messaging = module.module_create_db.mysql_database_messaging
}
```

**Comment by jbardin** [comment]
Hello,

I have verified that configuration of providers via variables during import works without the `-provider` flag in v0.15.

Thanks!
