### ISSUE TITLE
Compact Terraform plan output

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform#24580]
### Current Terraform Version
```
Terraform v0.12.20
+ provider.azuread v0.7.0
+ provider.azurerm v1.41.0
+ provider.external v1.2.0
+ provider.random v2.2.1
```

### Use-cases

When updating large list resources such as `listOfResourceTypesAllowed` in Azure, the current value may be even 700 rows, and all of these are displayed in `terraform plan` regardless of how many get updated. Updating one such policy in 20 subscriptions without ability of [Inverse targeting](https://github.com/hashicorp/terraform/issues/2253) leads to unreadable Plan which just needs to be believed...

``` HCL
 value = [
  "Microsoft.AAD/domainServices",
  "Microsoft.AAD/locations/operationresults",
  "Microsoft.AAD/Operations",
  "microsoft.aadiam/diagnosticsettings",
  "microsoft.aadiam/diagnosticsettingscategories",
  "Microsoft.Advisor/configurations",
 -"Microsoft.Advisor/generateRecommendations",
 +"Microsoft.Advisor/generateRecommendations",
  ...
]
```
### Attempted Solutions

Run 20 plans, one per each subscription, targeting only the exact resource that's being modified.

### Proposal

Adjust `terraform plan` to summarize unchanged values into a single line and only display changed values.

``` HCL
value = [
  668 values unchanged
 -"Microsoft.Advisor/generateRecommendations",
 +"Microsoft.Advisor/generateRecommendations",
]
```

**Comment by Tbohunek** [comment]
Eventually control this through `-summarize` (`-sum`) switch so that processes tied to current output are not impacted.

**Comment by pkolyvas** [comment]
Hi @Tbohunek. Thanks for taking the time to suggest this change to Terraform. 

We have a number of open issues for which I believe this issue would be a duplicate or at least closely related to a degree I feel comfortable closing this one out.

#10507 is the current master issue. 

We are trying to be very thoughtful and cautious about adding options to Terraform as they increase complexity in development and testing at a point where we are still re-working/refactoring some of Terraform's internals. 

We appreciate your contribution and your patience.
