### ISSUE TITLE
Dependency relation isn't detected after removed resource B and the reference of resource B in resource A from tfconfig

### ISSUE THREAD

**Issue by neil-yechenwei** [hashicorp/terraform#24591]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform v0.12.24
terrafomr azure provider v2.0

### Affected Resource(s)

* `azurerm_public_ip`
* `azurerm_nat_gateway`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "neil-pip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  public_ip_address_ids   = [azurerm_public_ip.test.id]
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```

### Panic Output

D:\natgateway>terraform apply --auto-approve
azurerm_resource_group.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg]
azurerm_public_ip.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/publicIPAddresses/neil-pip]
azurerm_virtual_network.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/virtualNetworks/neil-vnet]
azurerm_nat_gateway.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/natGateways/neil-gateway]
azurerm_subnet.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/virtualNetworks/neil-vnet/subnets/neil-subnet]
azurerm_subnet_nat_gateway_association.test: Refreshing state... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/virtualNetworks/neil-vnet/subnets/neil-subnet]
azurerm_public_ip.test: Destroying... [id=/subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/publicIPAddresses/neil-pip]

Error: Error deleting Public IP "neil-pip" (Resource Group "neil-nat-rg"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/publicIPAddresses/neil-pip can not be deleted since it is still allocated to resource /subscriptions/xxxx-xxx-xxx-xx/resourceGroups/neil-nat-rg/providers/Microsoft.Network/natGateways/neil-gateway. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]

### Expected Behavior
`azurerm_nat_gateway` resource should be updated first, then delete `azurerm_public_ip` resource.

### Actual Behavior

Terraform would delete `azurerm_public_ip` resource before updates `azurerm_nat_gateway`.

### Steps to Reproduce

1. Run `terraform apply --auto-approve` with below tfconfig.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_public_ip" "test" {
  name                = "neil-pip"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  public_ip_address_ids   = [azurerm_public_ip.test.id]
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```
2. Run `terraform apply --auto-approve` with below tfconfig:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "neil-nat-rg"
  location = "westus"
}

resource "azurerm_virtual_network" "test" {
  name                = "neil-vnet"
  address_space       = ["10.5.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "neil-subnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.5.1.0/24"
}

resource "azurerm_nat_gateway" "test" {
  name                    = "neil-gateway"
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  sku_name                = "Standard"
}

resource "azurerm_subnet_nat_gateway_association" "test" {
  subnet_id      = azurerm_subnet.test.id
  nat_gateway_id = azurerm_nat_gateway.test.id
}
```

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core.

I'm going to label it as such, and the HashiBot will shortly migrate it over to the AzureRM provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
