### ISSUE TITLE
terraform import on GCP Cloud Armor resource causes crash

### ISSUE THREAD

**Issue by RobertFr0st** [hashicorp/terraform#24596]
So essentially terraform crashes with a Seg Fault when importing a GCP Cloud Armor resource. It happens consistently, I have not yet attempted upgrading either the provider or terraform version.  I plan to do so later and will post an update if one of those fixed it.  This is actually the first time I've tried importing a Cloud Armor resource, so I'm uncertain if it is specific to being unable to import cloud armor, that it's having trouble because it uses advanced mode matching rules (which I think are a newer addition to GCP), or possibly something else.  While I continue investigating, I'll include the crash logs for you all to review.

Also I expunged client specific data hence the weird resource names, but I left the crashing cloud armor resource name as is to make searching easier.

Please let me know if further information is needed or have any input.

terraform / provider version info:
[tf-version-info.txt](https://github.com/hashicorp/terraform/files/4450883/tf-version-info.txt)

crash log from cli:
[cli-output.txt](https://github.com/hashicorp/terraform/files/4450887/cli-output.txt)

And then the following is the full crash file:
[crash.log](https://github.com/hashicorp/terraform/files/4450878/crash.log)

**Comment by danieldreier** [comment]
Hi @RobertFr0st! Thanks for reporting this. Based on your crash log, it looks to me like this crash is happening in the google provider:
```
2020-04-07T13:40:49.390-0400 [DEBUG] plugin.terraform-provider-google_v2.13.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
```

I'm going to label this as belonging to that provider, and the HashiBot should migrate the issue over there. If they look into it and determine that this requires work on terraform core we can re-open this and dig in.
