### ISSUE TITLE
User Data Compression Issue

### ISSUE THREAD

**Issue by ssk199441** [hashicorp/terraform#24612]
I am using terraform 0.11.14 version when i try to run user_data_base64 is showing error.
Kindly let me know how the reduce the size of userdata

**Comment by pkolyvas** [comment]
Hey there,

Thanks for taking the time to write us.

Due to the number of issues we work through here, we encourage our community to ask questions in our [Terraform community forum](https://discuss.hashicorp.com/c/terraform-core/27).
