### ISSUE TITLE
Cannot associate the Capacity Provider with ECS cluster which created by aws_batch_compute_environment

### ISSUE THREAD

**Issue by ctrongminh** [hashicorp/terraform#24615]
### Current Terraform Version

```
Terraform v0.12.24
```

### Use-cases

Our use case is first create AWS batch compute environment with UNMANAGED type, which will automatically create the ECS cluster. Then, we will create the Launch Template, AutoScaling Group. After that, go to the ECS Cluster, and create the Capacity Provider.
However, I cannot find a way to associate the ECS Cluster created by aws_batch_compute_environment with the resource aws_ecs_capacity_provider.

### Attempted Solutions

I try to use the resource aws_ecs_cluster with the ECS cluster name created by aws_batch_compute_environment, and aws_ecs_capacity_provider.resource.name but got error.

There are three cases
1. Define both capacity_providers and default_capacity_provider_strategy

resource "aws_ecs_cluster" "resource" {
  name               = "${trimprefix(data.aws_arn.ecs-cluster-resource.resource, "cluster/")}"
  capacity_providers = ["${aws_ecs_capacity_provider.resource.name}"]

  default_capacity_provider_strategy {
    capacity_provider = "${aws_ecs_capacity_provider.resource.name}"
  }
}

Got error
```
Error: InvalidParameterException: Arguments on this idempotent request are inconsistent with arguments used in previous request(s).
```

2. Only use the capacity_providers

resource "aws_ecs_cluster" "resource" {
  name               = "${trimprefix(data.aws_arn.ecs-cluster-resource.resource, "cluster/")}"
  capacity_providers = ["${aws_ecs_capacity_provider.resource.name}"]
}
Got the same error
```
Error: InvalidParameterException: Arguments on this idempotent request are inconsistent with arguments used in previous request(s)
```

3. Ony use the default_capacity_provider_strategy

resource "aws_ecs_cluster" "resource" {
  name               = "${trimprefix(data.aws_arn.ecs-cluster-resource.resource, "cluster/")}"
  default_capacity_provider_strategy {
    capacity_provider = "${aws_ecs_capacity_provider.resource.name}"
  }
}
Got different error
```
Error: InvalidParameterException: The specified capacity provider strategy cannot contain a capacity provider that is not associated with the cluster. Associate the capacity provider with the cluster or specify a valid capacity provider and try again.
```
### References

[#11531](https://github.com/terraform-providers/terraform-provider-aws/issues/11531)

**Comment by pkolyvas** [comment]
Hi @ctrongminh 

Unfortunately there's not much we can do with this issue as is. If you have a question about the AWS Provider or Terraform, we'd welcome you to ask in our [community forums](https://discuss.hashicorp.com/c/terraform-core/27).

**Comment by ctrongminh** [comment]
@pkolyvas 
Sorry I was updating the description

**Comment by pkolyvas** [comment]
Sorry about that, I've reopened it. This looks like a concern for AWS Provider team however so we'll move the ticket their for them to evaluate first.

**Comment by ctrongminh** [comment]
Thank you,
I just update more cases
