### ISSUE TITLE
make terraform fmt recursive on the folder tree

### ISSUE THREAD

**Issue by blugri** [hashicorp/terraform#24627]
### Current Terraform Version

```
v0.12.23
```

### Use-cases

When using submodules or a folder structure for deploying multiple environments it is not possible to use the terraform fmt command in a recursive way. I would primarly use the command as a pre-commit command to make sure that code in the git repo is clean and formatting changes are kept to a minimal.

**Comment by megubyte** [comment]
It appears that this is possible on `v0.12.24` using the `-recursive` flag when doing `terraform fmt`. Looking at the changelog between our versions, it should be possible on your version also.

**Comment by pkolyvas** [comment]
@blugri as @megubyte noted the `-recursive` command line flag should scratch that itch. It's documented here: https://www.terraform.io/docs/commands/fmt.html

If it's not working for you, please do open a bug report.
