### ISSUE TITLE
globalaccelerator argument named "tags" is not expected here

### ISSUE THREAD

**Issue by zagr0** [hashicorp/terraform#24640]
### Terraform Version

```
Terraform v0.12.21
+ provider.aws v2.51.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
resource "aws_globalaccelerator_accelerator" "default" {
  name            = "name"
  ip_address_type = "IPV4"
  enabled         = true

  tags = module.label.tags
}
```

### Expected Behavior
terraform creates globalaccelerator resource with tags

### Actual Behavior
```
Error: Unsupported argument

  on ../../modules/global_accelerator/main.tf line 17, in resource "aws_globalaccelerator_accelerator" "default":
  17:   tags            = module.label.tags

An argument named "tags" is not expected here.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by bflad** [comment]
Hi @zagr0 👋 Thank you for submitting this and sorry you ran into trouble here. Tagging for the `aws_globalaccelerator_accelerator` resource was added in [version 2.53.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2530-march-12-2020). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
