### ISSUE TITLE
AWS API Gateway not possible to set HTTP status method response as Proxy

### ISSUE THREAD

**Issue by abhi-dwivedi** [hashicorp/terraform#24672]
Hi 
AWS API Gateway not possible to set HTTP status method response as Proxy when I use VPC link HTTP_proxy . and its already enable from terraform script 
Use Proxy Integration if i go UI and uncheck and check again it works
 
please help

**Comment by pkolyvas** [comment]
Hey there,

Thanks for taking the time to write us. This repository is for the Terraform CLI tool. It sounds like you have a specific concern with AWS. 

The best place to ask questions is over at our [community forums](https://discuss.hashicorp.com/c/terraform-core/27). We try to reserve Github for bugs specific to Terraform.
