### ISSUE TITLE
Cannot modify launch configurations when they are attached to autoscaling groups

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#2468]
Because launch configurations always destroy and recreate when they are modified, but cannot be destroyed when attached.

Using the lifecycle `create_before_destroy = true` causes updates to work fine (since terraform creates the launch configuration, attaches, and destroys the old one), but this causes terraform to think there is a cycle when you attempt to `terraform -plan destroy` with the below configuration. Looking at the file, it seems like the ordering should be:

0. destroy autoscaling group
0. destroy launch configuration
0. destroy elb
0. destroy the other things

```
provider "aws" {
  access_key = ""
  secret_key = ""
  region = "us-east-1"
}

resource "aws_security_group" "cycle" {
  vpc_id = "${aws_vpc.cycle.id}"
  name   = "cycle"
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"]
  }
  ingress {
    from_port   = -1
    to_port     = -1
    protocol    = "icmp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = -1
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_vpc" "cycle" {
  cidr_block = "10.0.0.0/19"
}

resource "aws_subnet" "cycle" {
  vpc_id            = "${aws_vpc.cycle.id}"
  cidr_block        = "10.0.0.0/20"
  availability_zone = "us-east-1a"
}

resource "aws_launch_configuration" "cycle" {
  image_id             = "ami-1ecae776"
  instance_type        = "t2.medium"
  key_name             = "CosmosPairing"
  security_groups      = ["${aws_security_group.cycle.id}"]
  /* lifecycle = { create_before_destroy = true } */
}

resource "aws_elb" "cycle" {
  name = "cycle"
  subnets = ["${aws_subnet.cycle.id}"]
  internal = true
  listener {
    instance_port = 80
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
  security_groups      = ["${aws_security_group.cycle.id}"]
}

resource "aws_autoscaling_group" "cycle" {
  name = "test-cycle"
  min_size = 1
  max_size = 2
  launch_configuration = "${aws_launch_configuration.cycle.name}"
  availability_zones = ["us-east-1a"]
  vpc_zone_identifier = ["${aws_subnet.cycle.id}"]
  load_balancers = ["${aws_elb.cycle.name}"]
}
```

**Comment by jszwedko** [comment]
Related to #1648

**Comment by phinze** [comment]
Hi @jszwedko - a `create_before_destroy` resource cannot depend on non-CBD resources without causing a real cycle. If you add `create_before_destroy = true` to your security group and VPC, that should take care of the cycle error.

**Comment by jszwedko** [comment]
@phinze ah, gotcha, that does fix the issue. Still trying to tag all of the dependencies in our actual configuration which is much larger than the example, but hopefully all of them support generating attribute values for things that must be unique.

Do you think terraform will add the ability to modify launch configs without having to use `create_before_destroy` ? Although it does feel like the best route is to tag as many things as create_before_destroy as possible.

**Comment by phinze** [comment]
> Do you think terraform will add the ability to modify launch configs without having to use create_before_destroy?

I'm guessing not, since it's the resource model on the AWS side that's preventing it. I've considered adding in some features to help point users in the right direction (e.g. making `aws_launch_configuration` throw a warning if `create_before_destroy` is not set, throwing a clearer validation error when the above scenario is hit, etc), so hopefully that will help a little.

**Comment by jszwedko** [comment]
@phinze yeah, that seems like the right approach to me -- thanks for the help!

**Comment by jszwedko** [comment]
PS: Got all of the appropriate resources lifecycles tagged appropriately -- it might be nice to throw an explicit error saying that a dependency of a resource marked create_before_destroy is not marked as such.
