### ISSUE TITLE
`ignore changes` attribute usage in azure redis resource

### ISSUE THREAD

**Issue by harsh-vm** [hashicorp/terraform#24687]
This issue is related to the documentation that's in place [here](https://www.terraform.io/docs/providers/azurerm/r/redis_cache.html) for azure redis. The 'ignore changes' attribute usage section on the above link possibly has wrong format. When I followed the documentation I hit the issue that I have mentioned here. The documentation needs to be updated to include right syntax.

In fact, the error message actually guides you in right direction. So, the syntax should be this - 
```
ignore_changes = [redis_configuration[0].rdb_storage_connection_string]
```
instead of 

```
ignore_changes = [redis_configuration.0.rdb_storage_connection_string]
```
### Terraform Version

```
0.12.24
```

### Terraform Configuration Files

```hcl
resource "azurerm_redis_cache" "redis_cache_prod" {
  name                = var.redis_resource_name
  location            = azurerm_resource_group.redis_rg.location
  resource_group_name = azurerm_resource_group.redis_rg.name
  capacity            = var.redis_capacity
  family              = var.redis_family
  sku_name            = var.redis_sku_name
  enable_non_ssl_port = false
  subnet_id = var.redis_subnet_id

  redis_configuration {
    enable_authentication = coalesce(var.redis_subnet_id, false) ? false : true
    #Backup configuration
    rdb_backup_enabled            = var.rdb_backup_enabled
    rdb_backup_frequency          = var.rdb_backup_frequency
    rdb_backup_max_snapshot_count = var.rdb_backup_max_snapshot_count
    rdb_storage_connection_string = var.redis_sku_name == "Premium" ? "${azurerm_storage_account.redis_cache_sa[0].primary_blob_connection_string}" : null
    
    # Cluster configuration
    maxmemory_reserved = var.maxmemory_reserved
    maxmemory_delta    = var.maxmemory_delta
    maxmemory_policy   = var.maxmemory_policy
  }

  patch_schedule {
    day_of_week = var.redis_patch_schedule_day
    start_hour_utc = var.redis_patch_schedule_start_time
  }

  lifecycle {
    ignore_changes = [redis_configuration.0.rdb_storage_connection_string]
  }
}
```

### Expected Behavior

The above resource should pass validation and should get created with its pre-reqs (resource group and storage account) in place. 
### Actual Behavior

The terraform validation fails giving the following error message:
```
Error: Attribute name required

  on main.tf line 61, in resource "azurerm_redis_cache" "redis_cache_prod":
  61:     ignore_changes = ["redis_configuration.0.rdb_storage_connection_string"]

Dot must be followed by attribute name.
```
### Steps to Reproduce

`terraform validate` with above mentioned resource config along with its pre-reqs (resource group and storage account)

**Comment by danieldreier** [comment]
sorry about the accidental closing. I've labeled this as being AzureRM provider related and HashiBot will move the issue over there shortly. Thanks for reporting this!
