### ISSUE TITLE
Visualize progress when downloading providers (terraform init)

### ISSUE THREAD

**Issue by arthrp** [hashicorp/terraform#24693]
### Current Terraform Version

```
Terraform v0.12.24
```

### Problem
When downloading providers during terraform init stage, there's no indication of progress. People with slower internet connection might experience substantial delays, it appears as though terraform is hanging.

### Proposal
Introduce a progress bar that would state how much has been downloaded (in Kb/Mb) of the total size. This could be similar to ```apt``` utility in Linux.

**Comment by sanspace** [comment]
Thank you, @pkolyvas 

What's the response from the TF team? Would this be considered in a future release or in the 0.13.0 beta?

**Comment by pkolyvas** [comment]
We have some broad plans to improve the user experience of Terraform that would include visible feedback of all types, but they are not likely to come in the near team - as we have some other areas of concern that we feel are more pressing.
