### ISSUE TITLE
filename in local_file resource doesn't expand variables

### ISSUE THREAD

**Issue by alessiot77** [hashicorp/terraform#24706]
### Terraform Version

Terraform v0.12.24

### Terraform Configuration Files

resource "local_file" "test" {
    content     = "mycontent"
    filename = "~/.test/testfile"
    file_permission = "0600"
}

### Debug Output

No relevant errors or messages in the logs beyond resource initialization and completion

### Crash Output

No crash

### Expected Behavior

I'd expect that the tilde ("~") was expanded to the user's home folder.

### Actual Behavior

The filename variable is not expanded correctly and the file is not written to the home folder. It does work if I use an absolute path instead.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Additional Context

If the above is 'working as design', can you please document it properly with a hope to save folks some time !!!

**Comment by AndrewSav** [comment]
Just a nitpick about wording. `~` is not a terraform variable. 

Variables are documented here:

- https://www.terraform.io/docs/configuration/variables.html
- https://www.terraform.io/docs/configuration/outputs.html
- https://www.terraform.io/docs/configuration/locals.html

I could not find anywhere in terraform documentation that `~` could be expanded, so according to what's documented I personally would not expect it expanded. `~/.test/testfile"` is a string, and terraform uses it as is. In addition, terraform is cross platform, and `~` does not have special meaning on Windows command line as it has on Linux.

I have no affiliation with Hashicorp and/or Terraform, just giving my perspective as a user.

**Comment by pkolyvas** [comment]
Hi @alessiot77 - thanks for your submission.

Suggested changes to our documentation are welcomed, as there is always room for improvement. Every page on the Terraform documentation invites edits at the bottom.

@AndrewSav 's point is a good one. The `~` is expanded by a shell. Terraform expects an absolute or relative path. 

However, we do provide a function that does what you seek! The `pathexpand` function: https://www.terraform.io/docs/configuration/functions/pathexpand.html

Please do submit a change to our documentation if you feel we could clarify this further.
