### ISSUE TITLE
Crash on terraform apply

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/terraform#2470]
Crashed like this once. Subsequent applies completed successfully. 

Terraform `crash.log`: https://gist.githubusercontent.com/fromonesrc/61bb44e830d6b407954c/raw/gistfile1.txt

**Comment by mitchellh** [comment]
This is fixed upstream and will be part of 0.6.0 :)

**Comment by mitchellh** [comment]
(If you decide to build from  master, make sure you update deps)
