### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by j4zzcat** [hashicorp/terraform#24700]
Terraform v0.12.24
+ provider.ibm v1.3.0
+ provider.null v2.1.2

Crash report: https://gist.github.com/j4zzcat/1ef08c5258b2480f6cce9cdc37c7de18
Source files: https://github.com/j4zzcat/j4zzcat-ibmcloud/tree/1cec0e86608fdc0a06947df6f59e96ad123d7830

**Comment by danieldreier** [comment]
Hi! Thanks for reporting this. We're definitely interested in finding out when Terraform crashes. In this case, I don't quite understand what problem is being reported here. I looked at your crash report, and there are no panics. 

Can you please explain what error you're seeing, and what you ran to trigger it?
