### ISSUE TITLE
Having to repeat ouputs across a chain of modules is very cumbersome

### ISSUE THREAD

**Issue by earzur** [hashicorp/terraform#24703]
### Current Terraform Version

```
Terraform v0.12.23
+ provider.aws v2.54.0
+ provider.datadog v2.7.0
+ provider.http v1.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.vault v2.0.0
```

### Use-cases
Hello, 

when using a hierarchy of modules who depend on themselves to provision the infra, we usually end up repeating every other module's output in every modules in the chain.

Tools like terragrunt make a point in encouraging "DRY" by creating a lot of modules...

In our own infra this parent <-> child relationship between modules can go down to 4 levels.

That means that for the top level module to access a value produced by a module at the 4th layer, i'll *always have to* pass along those parameters (or use very nasty splat expressions which are very difficult to work out with modules that return structured data - `module.A.module.B[0].module.C.vpc_id`)

A flagship of such issue is the cloudcraft vpc module (https://github.com/terraform-aws-modules/terraform-aws-vpc) that we use in our infra and outputs 50+ different values that are usually needed up the caller chain and have to be repeated everywhere. 2 layers in the module call chain, and you have to repeat those ouputs 100 times.

In templates with module A -> module B -> module C, i know that i can just export the interesting output from module C in module A and won't have to repeat them, but it implies a deep knowlegde of both module B & module C structures, and doesn't encourage reusability.

I would love to see a way to make some outputs auto exportable, for instance. 

### Attempted Solutions

We are already using a hackish way for providing the later in our code:

```
output "json" {
  description = "Every output of the module encoded as a JSON object - avoid repeating outputs in other modules as it can be passed directly"
  value = jsonencode({
    bootstrap = module.bootstrap
  })
}
```
and use it like

```  
  private_root_zone_id = jsondecode(module.root_account.json).bootstrap.private_zone_id
  root_vpc_id          = jsondecode(module.root_account.json).bootstrap.vpc_id
```

3 levels upper. But i find this very fragile, prone to errors and requiring explicit, imperative things when all the tools we're discussing here are build to encourage declarativeness.

### Proposal

* module A & B would automatically receive module C's output marked with "exportable" ? with the module relationship built as map ?
* a bit like aws provider's `data.aws_policy_document` data source ? provide a global `json` output to modules that would be automatically populated with json object built from all the outputs declared in the module ? we could then just pass along that json obect in the call chain ?

**Comment by vyasknellutla** [comment]
Hi @earzur,

I'm not sure if this would be what you're looking for, but I use the following code when calling modules so that the terminal output returns the full path of where the values came from.

main.tf:
```hcl
module "my_module" {
  source = "./my_module"
}

output "my_output" {
  value = module.my_module
}
```
Terminal Output:
```bash
my_module = {
  "output1" = "foo"
  "output2" = "bar"
}
```

Note: Tested it on terraform v0.12.24

Would this be helpful for what you're trying to accomplish?

**Comment by earzur** [comment]
Hey @vyasknellutla 

yes, thanks, i found out that you could pass the output of modules directly

This gives very funky things in my code (`remote_state`s, yikes...) when trying to address thing down in the chain but it solved my problem, indeed... i'm going to go ahead and close that non-issue.
