### ISSUE TITLE
Terraform not ignoring changes in sub config block

### ISSUE THREAD

**Issue by tonyslab** [hashicorp/terraform#24719]
Hi there,

Terraform not ignoring changes in configurations of a sub-block in the EMR cluster resources. I would like to ignore changes in `master_instance_group["instance_count"]` and ` core_instance_group["instance_count"]` but every time I ran a plan I see changes done to these two ignored attributes. I think this is a bug as I'm following the docs to ignore sub-config block as described on Terraform [documentation page](https://www.terraform.io/docs/configuration/resources.html#ignore_changes). I tried all possible options in the ignore changes array but none seem to work. 

### Terraform Version
```bash 
terraform --version                                                                                                      
Terraform v0.12.13
+ provider.aws v2.51.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from www.terraform.io/downloads.html
```

### Terraform Configuration Files

```hcl
resource "aws_emr_cluster" "emr_cluster" {
  ....
 
  core_instance_group {
     ....
    instance_count = var.core_instance_group_instance_count
    ....
  }

  master_instance_group {
    ....
    instance_count = var.master_instance_group_instance_count
    ....
  }
    ....
  configurations_json = var.configurations_json
    ....
  lifecycle {
    ignore_changes = [
      master_instance_group["instance_count"],
      core_instance_group["instance_count"],
      "core_instance_group.0.instance_count",
      "core_instance_group.0.instance_count",
      "core_instance_count",
      core_instance_count,
      configurations_json,
    ]
  }
```

### Expected Behavior
Terraform plan and apply should ignore changes but this is not happening. 

### Actual Behavior
Terraform wants to update both ignored attributes. 

### Steps to Reproduce

```hcl
Terraform will perform the following actions:

  # module.emr_datapipeline_cluster_01.aws_emr_cluster.emr_cluster[0] will be updated in-place
  ~ resource "aws_emr_cluster" "emr_cluster" {
        ....
      ~ core_instance_group {
            id             = "ig-xxxxxx"
          ~ instance_count = 1 -> 3
            ....
        }
....
Plan: 0 to add, 1 to change, 0 to destroy
```

**Comment by danieldreier** [comment]
@tonyslab thanks for reporting this. It looks really similar to #21788 but that was already merged and released.

I need to reproduce it locally as part of triage, and I'd ideally like to avoid creating an EMR cluster just to reproduce this bug. Can you please try and reproduce this using a `null_resource` and terraform 0.12.24?

**Comment by tonyslab** [comment]
Hi @danieldreier, 
Thank you for your quick response, I don't fully understand what you mean by using a null_resource? Looking forwards to your response! 

BR,
Tony

**Comment by jbardin** [comment]
Hi @tonyslab,

Unfortunately the validation around the `ignore_changes` fields still isn't great. The correct syntax for that field should be:
```
    ignore_changes = [
      core_instance_group[0].instance_count,
    ]
```

Can you confirm if this works for that resource?

**Comment by tonyslab** [comment]
@jbardin amazing! Thank you so much for you help, this indeed worked.
