### ISSUE TITLE
Incorrect behavior: azurerm_role_assignment - assigning multiple spn to the same role doesn't work

### ISSUE THREAD

**Issue by moneygit** [hashicorp/terraform#24732]
### Terraform Version
bash-5.0# terraform -v
Terraform v0.12.16

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from https://www.terraform.io/downloads.html

### Terraform Configuration Files
child module
```hcl
variable "depends_list" {
    default             = []
}

resource "azurerm_role_assignment" "role_assignment" {
  depends_on            = [var.depends_list]
  for_each              = var.role-map
  
  role_definition_name  = each.key
  scope                 = each.value.scope
  principal_id          = each.value.principal-id
}
```
root module
```hcl
module "rbac_role_assignment" {
    source                  = "../modules/role-assignment/2.0"
    
    role-map                      = var.rbac-role-map
}
```
config.tfvars
```hcl
environment                             = "core"
configuration                           = "roleassignments"

rbac-role-map = {
  "Network Peer" = {
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 1>"    
  }
  "Network Peer" = {
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 2>"   
  }
  "Network Peer" = {
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 3>"  
  }
  "Network Peer" = {
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 4>"  
  } 
}
```

### Debug Output

Full debug output can be obtained by running Terraform with the environment variable `TF_LOG=trace`. Please create a GitHub Gist containing the debug output. Please do _not_ paste the debug output in the issue, since debug output is long.

Debug output may contain sensitive information. Please review it before posting publicly, and if you are concerned feel free to encrypt the files using the HashiCorp security public key.

### Expected Behavior

To assign the role 'Network Peer' to each of the 4 Service Principals

### Actual Behavior

It only assigns the role to the last service principal in the map.
```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.rbac_role_assignment.azurerm_role_assignment.role_assignment["Network Peer"] will be created
  + resource "azurerm_role_assignment" "role_assignment" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = "<spn 4>"
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Network Peer"
      + scope                            = "/subscriptions/<sub 1>"
      + skip_service_principal_aad_check = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
------------------------------------------------------------------------

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Additional Context

Yes, running in a custom wrapper script
It can work with assigning same spn or different spn to a different scope, just can't have it assign multiple spn to the same scope.

### References

No, not that I am aware of

**Comment by narbiter** [comment]
Map keys need to be unique. Try changing your config to the following;

rbac-role-map = {
  "Network Peer1" = {
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 1>"    
  }
  "Network Pee2r" = {
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 2>"   
  }
  "Network Peer3" = {
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 3>"  
  }
  "Network Peer4" = {
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 4>"  
  } 
}

**Comment by moneygit** [comment]
Thank you, I renamed my keys and added the  role_assignment into the map
My config now looks like this and runs smoothly.

```hcl
environment                             = "core"
configuration                           = "roleassignments"

rbac-role-map = {
  "001" = {
    role-definition = "Network Peer"
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 1>"    
  }
  "002" = {
    role-definition = "Network Peer"
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 2>"   
  }
  "003" = {
    role-definition = "Network Peer"
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 3>"  
  }
  "004" = {
    role-definition = "Network Peer"
    scope           = "/subscriptions/<sub id1>"
    principal-id    = "<spn 4>"  
  } 
}
```
