### ISSUE TITLE
Terraform doesn't surface the correct error when ADCs expire.

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform#24736]
### Terraform Version

```
terraform v0.12.21
```

### Terraform Configuration Files

any config with a remote gcs bucket.

### Output
```
Error: Failed to get existing workspaces: querying Cloud Storage failed: Get https://www.googleapis.com/storage/v1/b/REDACTED/o?alt=json&delimiter=%2F&pageToken=&prefix=mgcp-1252957-omg-vpc%2F&prettyPrint=false&projection=full&versions=false: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

### Additional Context

Terraform uses ADC(application default credentials) and the gcloud sdk generates one but it does expire after 60 days of no use. Terraform doesn't surface appropiate error so the end user is confused.

The ADC for an end user is effectively a long life oauth2 refresh token and Google defines some expiry reasons here.
https://developers.google.com/identity/protocols/oauth2#expiration

It would be great if terraform can detect failing ADCs and prompt the user to regenerate them with `gcloud auth application-default login`

Thank you

**Comment by danieldreier** [comment]
Thanks for reporting this! The error you're showing seems to happening in the [Google provider](https://github.com/terraform-providers/terraform-provider-google) rather than Terraform core, so I'm going to label it as a Google provider issue, and the HashiBot will shortly migrate it over to the Google provider's repository so that they can investigate it.

Thanks again for reporting this, and please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by upodroid** [comment]
The error will happen when the remote gcs backend is used and any resource in the google provider because they both use the same credential.

**Comment by upodroid** [comment]
A very simple example:

```
provider "google" {
  project = "FOO"
  region  = "europe-west2"
}

terraform {
  backend "gcs" {
    bucket = "FOO"
    prefix = "data-lake"
  }
}

resource "google_pubsub_topic" "spanner" {
  name = "spanner"
  labels = {
    role = "harvester"
  }
}
```

```
PS C:\Git\analytics\terraform> gcloud auth application-default login 
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/FOOOO



Credentials saved to file: [C:\Users\FOO\AppData\Roaming\gcloud\application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
PS C:\Git\analytics\terraform> terraform init

Initializing the backend...

Error: Failed to get existing workspaces: querying Cloud Storage failed: Get https://www.googleapis.com/storage/v1/b/FOO/o?alt=json&delimiter=%2F&pageToken=&prefix=data-lake%2F&prettyPrint=false&projection=full&versions=false: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "invalid_client",
  "error_description": "Unauthorized"
}

```

This time I opened the ADC file and swapped two characters around. Even here the error is cryptic and you need to look here some answers. https://cloud.google.com/storage/docs/json_api/v1/status-codes#401_Unauthorized 


I don't have an expired refresh token to test with.  :( 

Now, if you remove the gcs backend, you get a successful plan but apply fails with the same Google error which is cryptic too.

```
PS C:\Git\analytics\terraform> terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # google_pubsub_topic.spanner will be created
  + resource "google_pubsub_topic" "spanner" {
      + id      = (known after apply)
      + labels  = {
          + "role" = "harvester"
        }
      + name    = "spanner"
      + project = (known after apply)

      + message_storage_policy {
          + allowed_persistence_regions = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_pubsub_topic.spanner: Creating...

Error: Error creating Topic: Put https://pubsub.googleapis.com/v1/projects/FOO/topics/spanner?alt=json: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "invalid_client",
  "error_description": "Unauthorized"
}

  on main.tf line 14, in resource "google_pubsub_topic" "spanner":
  14: resource "google_pubsub_topic" "spanner" {

```
