### ISSUE TITLE
Invalid count argument for variable

### ISSUE THREAD

**Issue by ZsoltPath** [hashicorp/terraform#24739]
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
main.tf
module "step_lambda" {
  source = "git@github.com:rbs-path/terraform-modules.git//modules/compute/aws-lambda?ref=v0.11.2"
  providers = {
    aws = aws.us-east-1
  }

  function_name  = "${local.app}-${var.environment}-step-edge-lambda"
  handler        = "edge.handler"
  runtime        = "nodejs10.x"
  timeout        = 30
  lambda_at_edge = true

  policy = data.aws_iam_policy_document.step_lambda_s3

  content  = templatefile("${path.module}/lambda/step_edge_lambda/edge.js", { bucket_name = module.step.bucket_id })
  filename = "edge.js"
}

archive.tf in the called module
data "archive_file" "lambda" {
  count       = var.content == null ? 0 : 1
  type        = "zip"
  output_path = "${path.module}/builds/${var.filename}_${sha1(var.content)}.zip"

  source {
    content  = var.content
    filename = var.filename
  }
}

```

### Expected Behavior

Archive file and dependent resource created

### Actual Behavior

terraform plan -var-file "environments/prod.tfvars" -target module.step_lambda.aws_lambda_function.lambda

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.step_lambda.data.aws_iam_policy_document.assume_role: Refreshing state...
module.step_lambda.aws_iam_role.lambda: Refreshing state... [id=step-prod-step-at-edge-lambda]
module.step_lambda.aws_lambda_function.lambda: Refreshing state... [id=step-prod-step-edge-lambda]

------------------------------------------------------------------------

Warning: Resource targeting is in effect

You are creating a plan with the -target option, which means that the result
of this plan may not represent all of the changes requested by the current
configuration.

The -target option is not for routine use, and is provided only for
exceptional situations such as recovering from errors or mistakes, or when
Terraform specifically suggests to use it as part of an error message.

Error: Invalid count argument

  on .terraform/modules/step_lambda/modules/compute/aws-lambda/archive.tf line 47, in data "archive_file" "lambda":
  47:   count       = var.content == null ? 0 : 1

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

**Comment by danieldreier** [comment]
Hi! Thanks for reporting this. I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As-is, I don't have your template, or your vars, and so I'm not able to run your example and reproduce the issue.

Based on the error you're reporting, I don't think those are actually needed to reproduce this. Ideally, this would use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies. I think you could do it with a null resource and a very simplified example that just showcases the count behavior.

Can you please restate your reproduction case such that I can copy-paste it and run it locally?

**Comment by ZsoltPath** [comment]
Hi @danieldreier ,

Unfortunately I can't reproduce it with a test case. 
And it's frustrating for me too. 
It must be some kind of edge case which almost never happens.

In my real situation I had to move another lambda resource state into the one created from this archive file. And then it was modifying it correctly.
But that seemingly has nothing to do with the count parameter.

I understand if you close this issue, but it's better to have some record.

**Comment by danieldreier** [comment]
How odd. Can you tell me what values you expect to have in `var.content`?

**Comment by ZsoltPath** [comment]
> 
> 
> How odd. Can you tell me what values you expect to have in `var.content`?

Either a Lambda script from template or null. See my example at the top for the first!

**Comment by danieldreier** [comment]
Here's the two cases I tried to reproduce this, unsuccessfully:

```hcl
variable "filename" {
  type = string
  default = "foo"
}

variable "content" {
  type = string
  default = null
}

data "archive_file" "sample" {
  count       = var.content == null ? 0 : 1
  type        = "zip"
  output_path = "${path.module}/archive/${var.filename}_${sha1(var.content)}.zip"

  source {
    content  = var.content
    filename = var.filename
  }
}
```
As expected, this case produced no changes.

With the `content` variable changed to `"foo"` as below, the expected archive file was produced:
```hcl
variable "filename" {
  type = string
  default = "foo"
}

variable "content" {
  type = string
  default = "foo"
}

data "archive_file" "sample" {
  count       = var.content == null ? 0 : 1
  type        = "zip"
  output_path = "${path.module}/archive/${var.filename}_${sha1(var.content)}.zip"

  source {
    content  = var.content
    filename = var.filename
  }
}
```

I think we'll have to leave this unsolved for a while, until you or someone else can provide a reproduction case.

**Comment by ZsoltPath** [comment]
Found it!

It was due to a circular reference. I was close to pulling out my remaining hair.
The Lambda module's call was referencing an output from the cloudfront module which call was referencing the output of the same lambda module.
