### ISSUE TITLE
aws_directory_service_log_subscription fails when aws_directory_service_directory is re-created

### ISSUE THREAD

**Issue by dtns2** [hashicorp/terraform#24762]
### Terraform Version
```
Terraform v0.12.24
+ provider.aws v2.56.0
```

### Terraform Configuration Files
```
##### Layer 1 Module
### Directory Service
resource "aws_directory_service_directory" "management" {
  name        = var.ds_fqdn
  short_name  = var.ds_netbios
  password    = var.ds_admin_password
  edition     = "Standard"
  type        = "MicrosoftAD"
  description = "Directory Service for Management"
  vpc_settings {
    vpc_id     = aws_vpc.management.id
    subnet_ids = [
      aws_subnet.management_directory_1a.id,
      aws_subnet.management_directory_1b.id
    ]
  }
}

output "directory_service_management_id" { value = aws_directory_service_directory.management.id }
```
In another terraform module that references the statefile of the module above via [terraform_remote_state](https://www.terraform.io/docs/providers/terraform/d/remote_state.html):
```
data "terraform_remote_state" "layer_1" {
  backend = "s3"
  config = {
    encrypt        = true
    region         = "us-gov-west-1"
    bucket         = "BUCKET-NAME"
    dynamodb_table = "TABLE-NAME"
    key            = "management/layer-1.tfstate"
  }
}

##### Layer 2 Module
### Directory Service Logs
resource "aws_cloudwatch_log_group" "directory_service_log_group" {
  name = "/aws/directoryservice/management"
  retention_in_days = 14
}

resource "aws_directory_service_log_subscription" "management" {
  directory_id   = data.terraform_remote_state.layer_1.outputs.directory_service_management_id
  log_group_name = aws_cloudwatch_log_group.directory_service_log_group.name
}
```

### Crash Output
Initial runs successfully create all resources in both modules (with different backend statefiles). 

Then, `aws_directory_service_directory.management` gets re-created successfully in module layer1. 

Then after `aws_directory_service_directory.management` is re-created successfully, when module layer2 gets re-run, instead of re-creating/updating `aws_directory_service_log_subscription.management` with the new Directory Services ID, the following error will occur:
```
Error: error listing Directory Service Log Subscription: 
    EntityDoesNotExistException: Directory: 'd-<OLD-DIRECTORYSERVICE-ID>' does not exist. : 
    RequestId: <REQUEST-ID>
```

**NOTE:** the `d-<OLD-DIRECTORYSERVICE-ID>` value will contain the original ID for the directory service that was initially created but was since deleted then re-created with a new ID.

### Expected Behavior
Due to the interpolation of `aws_directory_service_directory.management.id`, the `aws_directory_service_log_subscription.management` should either update-in-place or get recreated with the new Directory Services ID outputted from the other terraform module.

### Actual Behavior
During the refreshing state phase of the terraform execution for module layer 2 (before a successful plan or apply output can be observed), the run will fail with the above error.

### Steps to Reproduce
1. Create two terraform modules
    * layer1: contains configuration of `aws_directory_service_directory`
    * layer2: contains configuration of `aws_directory_service_log_subscription` that references Directory Services ID from output of layer1 module using `terraform_remote_state`
2. Run `terraform apply` on both layers to successfully create all resources net-new.
3. Destroy and recreate layer1 module's `aws_directory_service_directory`, which will result in a new value for output `directory_service_management_id`
4. Attempt to run `terraform plan/apply` on layer2 module, hoping that `aws_directory_service_log_subscription` will notice that the Directory Services ID has changed and attempt to re-create or update with the new value
    * should observe error at this point

### References
* [aws_directory_service_directory](https://www.terraform.io/docs/providers/aws/r/directory_service_directory.html)
* [aws_directory_service_log_subscription](https://www.terraform.io/docs/providers/aws/r/directory_service_log_subscription.html)

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
