### ISSUE TITLE
Allow global alias module, make the module clear

### ISSUE THREAD

**Issue by XSAM** [hashicorp/terraform#24797]
### Current Terraform Version

```
Terraform v0.12.24
```

### Use-cases

Suppose my terraform repo structure like this:

```
├── a
│   ├── a.tf
│   │   ├── b
│   │   │   ├── b.tf
│   │   │   ├── c
│   │   │   │   ├── c.tf
├── modules
│   ├── compute
│   │   ├── main.tf
```

`a.tf`, `b.tf` and `c.tf` want to refer the `compute` module.

```hcl
# a.tf
module "compute" {
  source = "../modules/compute"
}
# b.tf
module "compute" {
  source = "../../modules/compute"
}
# c.tf
module "compute" {
  source = "../../../modules/compute"
}
```

These three files all refer to the same module, but the `source` field is not the same. 
Every time I reuse to the `compute` module, I have to check the relative path between the target module, calculate how much `../` should I add. That's pretty annoying and inconsistent.

Furthermore, if I want to move this terraform file or refactor the repo structure, I have to recalculate the `../`.

I want to use the absolute source path, but it's also not convenience since I cannot use a dynamic variable to inject source path, like this `"${local.root_path}/modules/compute"`. And the terraform root path may not be constant because we use CI.

### Proposal

Allow dynamic module source or allow to declare a global alias module, like this

```hcl
# main.tf
module-alias "modules" "compute" {
  source = "./modules/compute"
}

# a.tf
module "compute" {
  source = "@modules/compute"
}
```

**Comment by ljckennedy** [comment]
Why not just use git or similar ie:
module "compute" {
  source = "git::https://gitlab.com/tf/tf-modules.git//compute"

Or if you need to use local files, use absolute paths.

**Comment by XSAM** [comment]
That would require maintaining two git repo. Can we use one repo to achieve this? Or the recommended way to manage terraform repo is to separate the module and the live resource into two repo?

Absolute paths will limit the repo location. Not saying that's bad, but repo only works in a fixed path, well, not very graceful.

**Comment by ljckennedy** [comment]
you would not have to have 2 git repos - you are specifying the path to your module inside it's git repo, but we do maintain 2 as module development is much higher impact.  We might use one module in dozens of terraform projects.  That's more about our processes than terraform.

**Comment by XSAM** [comment]
I get it. Thank you for your prompt reply. I will close this issue now.
