### ISSUE TITLE
`terraform fmt` inconsistent formatting within the same resource

### ISSUE THREAD

**Issue by carlosjgp** [hashicorp/terraform#24793]
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

N/A

### Expected Behavior

All the property values of a resource, module, provider, maps,... (anything within `{ }`) are indented at the same level even when there are blank like to separate them

New lines improve readability by grouping properties of an object that are somehow related eg `aws_db_instance`

```
resource "aws_db_instance" "default" {
  name                 = "mydb"

  instance_class       = "db.t2.micro"

  allocated_storage    = 20
  storage_type         = "gp2"

  engine               = "mysql"
  engine_version       = "5.7"
  parameter_group_name = "default.mysql5.7"

  username             = "foo"
  password             = "foobarbaz"
}
```

### Actual Behavior
Property values spacing is only consistent when there are no newlines separating the properties

### Steps to Reproduce

1. Create `example.tf`

```
resource "xxx" "example" {
  name     = "example"
  tag = "my-tag"

  property_a = "a"
  property_b = "b"

  # value is `c` because I like Cs... :D
  very_log_property_c = "c"

  prop_d = {
    prop_map_a           = "a"
    prop_map_b           = "b"

    very_long_prop_map_c = "c"
  }
}
```

2. Run `terraform fmt .`
```
resource "xxx" "example" {
  name = "example"
  tag  = "my-tag"

  property_a = "a"
  property_b = "b"

  # value is `c` because I like Cs... :D
  very_log_property_c = "c"

  prop_d = {
    prop_map_a = "a"
    prop_map_b = "b"

    very_long_prop_map_c = "c"
  }
}
```

Expected output will be
```
resource "xxx" "example" {
  name                = "example"
  tag                 = "my-tag"

  property_a          = "a"
  property_b          = "b"

  # value is `c` because I like Cs... :D
  very_log_property_c = "c"

  prop_d              = {
    prop_map_a           = "a"
    prop_map_b           = "b"

    very_long_prop_map_c = "c"
  }
}
```
### References

I consider #24303 part of this issue

**Comment by danieldreier** [comment]
Thanks, you're right that this looks very related. Is this something you'd be interested in contributing code for? I don't know how hard of a fix it would be, but if you're interested I can help start the process of getting a proposed change reviewed and approved so that you can be more confident in a PR being accepted before doing the work.

**Comment by carlosjgp** [comment]
> Thanks, you're right that this looks very related. Is this something you'd be interested in contributing code for? I don't know how hard of a fix it would be, but if you're interested I can help start the process of getting a proposed change reviewed and approved so that you can be more confident in a PR being accepted before doing the work.

Yeah happy to contribut, I'll do my best :smile:

**Comment by carlosjgp** [comment]
@danieldreier Thanks for offering to write the proposal that will be amazing

I was checking the code tonight and I realised that Terraform is using the HCL specification format
- https://github.com/hashicorp/terraform/blob/v0.12.24/command/fmt.go#L179
- https://github.com/hashicorp/hcl/blob/v2.4.0/hclwrite/public.go#L38

And found this comment
https://github.com/hashicorp/hcl/issues/87#issuecomment-181380903

This makes me think that this could have a wider impact than I initially suspected
If we try to change `hcl` that will impact other Hashicorp products, like Vault, Consul... it's not like they user formatting but the change will be there.
And if we extend somehow `hclwrite.Format` somehow that will add complexity to Terraform and upgrading the language specification but hopefully not too much so the change doesn't get pushed back :crossed_fingers: 

As Faith mentioned in his comment format is hard

What do you think Daniel?

**Comment by jbardin** [comment]
Hi @carlosjgp,

Thanks for looking into this, and sorry for sending you on a quest that you couldn't necessarily solve. 

The current output format is what is intended to be printed by the `fmt` command. The format follows that of many languages, using newlines to delimit lexical groups, which are formatted independently. 

While a case could be made to align all groups equally, there is unfortunately no format that can please everyone. Hopefully in the future we can implement a more strict formatter, that can provide better guidance for users, leaving everyone with more consistent formatting overall.

**Comment by carlosjgp** [comment]
Thanks for looking into this @jbardin 

I fully understand that formatting is not an easy task to work on and please everyone is just impossible

Would a proposal to implement a formatting rules engine like `editorconfig` or similar will be acceptable?

I'm happy to close this issue since I understand it might deviate from what the project wants to be the approach for this and not sure how much interest this might have for other users

**Comment by grimm26** [comment]
this change would mangle thousands and thousands of lines of terraform/hcl that are already written and formatted cleanly,  If this change goes in, we will all have PRs with a boatload of changes masking the real change, which will negate the feature of having an enforceable format.  Like jbardin said, there isn't going to be a format that pleases everyone, but changing what is already enforced will displease almost everyone.

**Comment by danieldreier** [comment]
@carlosdp I am pretty hesitant to add more configurability than needed. We tend to follow the `go fmt`approach in order to ensure that all terraform code looks similar. The downside is that not everybody likes it, but the upside is that it's all pretty familiar. I think this comes down to that basic tradeoff - that we are following a convention and are making the decision that the terraform community overall is better off with a singular convention than a bunch of different formats. A lot of folks only interact with terraform very occasionally, so it's super important that the cognitive load of picking it up is as low as possible. I think it makes sense to close this proposal, based on the discussions we've had, but I really appreciate you making the suggestion and offering to build it. If you're interested in contributing more to terraform overall, feel free to reach out to me at ddreier@hashicorp.com if you're looking for areas to work on.

**Comment by carlosdp** [comment]
> @carlosdp I am pretty hesitant to add more configurability than needed. We tend to follow the `go fmt`approach in order to ensure that all terraform code looks similar. The downside is that not everybody likes it, but the upside is that it's all pretty familiar. I think this comes down to that basic tradeoff - that we are following a convention and are making the decision that the terraform community overall is better off with a singular convention than a bunch of different formats. A lot of folks only interact with terraform very occasionally, so it's super important that the cognitive load of picking it up is as low as possible. I think it makes sense to close this proposal, based on the discussions we've had, but I really appreciate you making the suggestion and offering to build it. If you're interested in contributing more to terraform overall, feel free to reach out to me at [ddreier@hashicorp.com](mailto:ddreier@hashicorp.com) if you're looking for areas to work on.

I think you mean @carlosjgp =P

**Comment by carlosjgp** [comment]
> @carlosdp I am pretty hesitant to add more configurability than needed. We tend to follow the `go fmt`approach in order to ensure that all terraform code looks similar. The downside is that not everybody likes it, but the upside is that it's all pretty familiar. I think this comes down to that basic tradeoff - that we are following a convention and are making the decision that the terraform community overall is better off with a singular convention than a bunch of different formats. A lot of folks only interact with terraform very occasionally, so it's super important that the cognitive load of picking it up is as low as possible. I think it makes sense to close this proposal, based on the discussions we've had, but I really appreciate you making the suggestion and offering to build it. If you're interested in contributing more to terraform overall, feel free to reach out to me at [ddreier@hashicorp.com](mailto:ddreier@hashicorp.com) if you're looking for areas to work on.

That's ok. Thanks for looking into this.

Thankfully all this code is Open source I can implement my own formatting package and GitHub Actions based on my own requirements for my projects

:+1:
