### ISSUE TITLE
“panic: runtime error: index out of range” using a combination of null and splat

### ISSUE THREAD

**Issue by izeau** [hashicorp/terraform#24805]
### Terraform Version

```
v0.12.24
```

### Terraform Configuration Files

```hcl
locals {
  x = concat([1, null]...)
}
```

### Debug Output

https://gist.github.com/izeau/8be4f9671c27a2404eee74ca82a9a29c#file-trace-out

### Crash Output

https://gist.github.com/izeau/8be4f9671c27a2404eee74ca82a9a29c#file-crash-log

### Expected Behavior

I expected it to fail with an error, but not a panic. The generic one would have been nice:

```
Invalid value for "seqs" parameter: argument must not be null.
```

### Actual Behavior

💥 

### Steps to Reproduce

```shell
$ terraform console <<< 'concat([1, null]...)'
```

**Comment by danieldreier** [comment]
@izeau thanks! I've reproduced this and am seeing the same behavior. Even a `terraform validate` on this causes the panic. We're pretty heads-down on 0.13 feature work right now, but are hoping to do a big clean-up of known panics and I'm hoping we can come back to this at that point.
