### ISSUE TITLE
etcdv3 backend creates default key on init

### ISSUE THREAD

**Issue by andrew-schlackman** [hashicorp/terraform#24803]
### Terraform Version
```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
terraform {
  backend "etcdv3" {
    endpoints = ["etcd-server"]
    lock      = true
    prefix    = "terraform-state/"
  }
}
```

### Expected Behavior
The backend should be initialized, but no key should be created in etcd until an apply is performed.

### Actual Behavior
The backend is initialized and a key is created in etcd for the default workspace with a minimal state file:

```
{  "version": 4,  "terraform_version": "0.12.24",  "serial": 0,  "lineage": "c11a3441-e802-3b02-7e52-804c6949b810",  "outputs": {},  "resources": []}
```

The output of `terraform workspace list` is confusing as well:

```
 terraform workspace list
* default
* default
```

This seems to indicate that this is not what terraform is expecting either.

### Steps to Reproduce
1. `terraform init`
2. `terraform workspace list`

### Additional Context
Other than the 2 defaults showing in the workspace list, this doesn't cause any immediate errors, but it is a blocker for my use case and also differs from the behavior of other backends (consul at least).

I am using terraform in an automation environment and constantly creating and deleting workspaces. Since the default workspace cannot be deleted, this current behavior of etcd will cause me to be left with an ever-growing number of default keys in my etcd that cannot be deleted without manual intervention outside of terraform. 

Using Consul, I can avoid using the default workspace and since no default key is created on init and named workspaces can be deleted, I don't have the explosion of useless keys. I'm trying to migrate to etcd to avoid the 512kb value cap of Consul, and this is a potential blocker.

**Comment by alxndr13** [comment]
Having the same issue currently. Did you managed to fix this or at least understand what the output of the two default workspaces mean? @andrew-schlackman 

The docs are also a bit misleading for my understanding. When supplying a "prefix" i would terraform to expect to create a unique id or something after the `terraform-state/` part. It seems to only create a `default` key. (like `terraform-state/default` how i can change the key which terraform is going to create in etcd?

**Comment by andrew-schlackman** [comment]
sorry @alxndr13, I gave up on trying to use the etcv3 backend until this and some other issues are resolved.

I think the 2 defaults in the list are because terraform doesn't expect the provider to have created a default key yet, but I'm not sure. There doesn't seem to actually be 2 different workspaces, as far as I can tell. My biggest issue is that these default keys in etcd can never be deleted without intervention outside of terraform.

**Comment by jasons42** [comment]
From my reading of the docs, it seems it's expected that the backend would be initialized as part of a `terraform init`.

https://www.terraform.io/docs/cli/commands/init.html#backend-initialization

The docs mention the option of passing the `-backend=false` flag to the init command to opt out of initializing the backend but I tried this locally and a default key was created anyway.

For what it's worth, I opened a separate issue regarding the duplicated output of the default workspace when running `workspace list` and linked a PR with a potential solution.

https://github.com/hashicorp/terraform/issues/28098

It does seem a little odd that these keys are created during the init with no way to delete them from within terraform.

**Comment by apparentlymart** [comment]
Hello! Thanks for reporting this.

We removed the etcd backends in Terraform v1.3 because they hasn't had a dedicated maintainer for a few versions now and so they were becoming problematic to keep working in newer Terraform versions. Since these backends are no longer present in the Terraform codebase, I'm going to close this issue.

If you're currently using one of these backends with an older version of Terraform, see [Removal of Deprecated State Storage Backends](https://www.terraform.io/language/v1.3.x/upgrade-guides#removal-of-deprecated-state-storage-backends) in the Terraform v1.3 upgrade guide for some information on the available options for migration.

Thanks again!
