### ISSUE TITLE
terraform init -backend-config using Azure Service Principal with partial configuration not working

### ISSUE THREAD

**Issue by nnellans** [hashicorp/terraform#24809]
terraform 0.12.24 on windows 10 x64

I'm trying to use an Azure Service Principal to connect to my Azure remote backend.  I don't want to store my Service Principal's secret directly in main.tf.  I also can't use variables in the backend block, so I'm using partial configuration.  That means my backend block is basically empty, and I'm defining the config entries in a separate file called backend.tfvars.  Then I'm using this to try to initialize:  terraform init -backend-config=backend.tfvars

However, this is not working.  When I run that init command, it simply comes back and says "Terraform initialized in an empty directory!".  My current directory is definitely the directory that contains my .tf files.  Even more, it doesn't even download the Azure provider!

Am I doing something wrong?

**file:  main.tf (also includes some Resource blocks that are not shown):**
provider "azurerm" {
  subscription_id = var.subscription_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tenant_id

  features {}
}

terraform {
  backend "azurerm" {}
}

**file:  backend.tfvars**
resource_group_name  = "xxx"
storage_account_name = "xxx"
container_name       = "terraform"
key                  = "prod.terraform.tfstate"
subscription_id      = "xxx"
client_id            = "xxx"
client_secret        = "xxx"
tenant_id            = "xxx"

**Comment by milescattini** [comment]
Theres likely 2 issues at play here. Regardless of the implementation of a partial configuration theres an issue with the directory that you are running the init on. Probably best to ensure the directory is correct and the file extensions are appropriate first.

**Comment by nnellans** [comment]
Thanks for the reply.

I know my directory is okay.  If I remove "-backend-config=backend.tfvars" from my terraform init command, and I place all of the options directly into the backend block in my main.tf, then the init works just fine.

To your second point, I am indeed including the -backend-config switch on my terraform init command, and pointing it at my separate tfvars file that includes the config options for my backend.  I do not want to include the options inline, for example with something like -backend-config="subscription_id=xxx" because then I'll have sensitive info in my command history.

**Comment by nnellans** [comment]
Okay, I think I figured it out, for some reason
- -backend-config=filename  >> does NOT work
- -backend-config="filename"  >> works when I include the double quotes around path
