### ISSUE TITLE
trusted_root_certificate_names parameter in backend_http_settings for Application Gateways V2 not working

### ISSUE THREAD

**Issue by di669** [hashicorp/terraform#24816]
### Terraform Version

```
Terraform v0.12.24
+ provider.azurerm v1.37.0
+ provider.null v2.1.2
...
```

### Terraform Configuration Files

```hcl

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = var.gw_sku_capacity
  }

  trusted_root_certificate {
    name     = local.authentication_certificate_name
    data     = filebase64("${path.module}/RootCA.crt")
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    port                  = 443
    protocol              = "Https"
    request_timeout       = 5
    host_name             = local.host_name
    probe_name           = "host-probe"
    trusted_root_certificate_names = [local.authentication_certificate_name]
  }

```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
Application Gateway V2 should have been created

### Actual Behavior
```
on main.tf line 637, in resource "azurerm_application_gateway" "we-test-2":
 637:     trusted_root_certificate_names = [local.authentication_certificate_name]

An argument named "trusted_root_certificate_names" is not expected here.
```
### Steps to Reproduce
Create a Standard V2 Application Gateway in Azure with trusted root certificates

**Comment by Tbohunek** [comment]
I'd like to add that if the ` trusted_root_certificate_names = xx` is removed from `backend_http_settings {}`, then `terraform apply` would remove the certificate from the actual http settings, even if that's not mentioned anywhere in the plan.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
