### ISSUE TITLE
Empty custom_webhook_payload is enabled by default for query_rules_alert

### ISSUE THREAD

**Issue by vsotog** [hashicorp/terraform#24817]
### Terraform Version

```
Terraform v0.12.24

```

### Terraform Configuration Files

I'm taking the sample configuration from the  [documentation](https://www.terraform.io/docs/providers/azurerm/r/monitor_scheduled_query_rules_alert.html)
```hcl



# Example: Alerting Action with result count trigger
resource "azurerm_monitor_scheduled_query_rules_alert" "example" {
  name                = format("%s-queryrule", var.prefix)
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  action {
    action_group           = []
    email_subject          = "Email Header"
    # (This is an optional parameter) -> custom_webhook_payload = "{}"
  }
  data_source_id = azurerm_application_insights.example.id
  description    = "Alert when total results cross threshold"
  enabled        = true
  # Count all requests with server error result code grouped into 5-minute bins
  query       = <<-QUERY
  requests
    | where tolong(resultCode) >= 500
    | summarize count() by bin(timestamp, 5m)
  QUERY
  severity    = 1
  frequency   = 5
  time_window = 30
  trigger {
    operator  = "GreaterThan"
    threshold = 3
  }
}
```

### Expected Behavior

Custom webhook payload (empty payload) shouldn't be enabled by default.

### Actual Behavior

An empty payload is enabled by default, even when not using the `custom_webhook_payload` parameter, causing the alert to send an empty message every time.
### References

![image](https://user-images.githubusercontent.com/35499518/80718881-b734bb00-8ac8-11ea-8b04-04dd5a9cecb1.png)

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by vsotog** [comment]
Will do. Thanks!
