### ISSUE TITLE
BeanStalk Environment Default Security Group is NOT removed

### ISSUE THREAD

**Issue by UdhavPawar** [hashicorp/terraform#24827]
### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.60.0
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
 # Add security group to BeanStalk Environment ASG Launch Configuration
 # Uses Beanstalk Env SG + my specified SG in this array below
 # instead of using just my specified SG from the array

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name = "SecurityGroups"
    value = var.ease_beanstalk_security_groups[0]
    resource = ""
```

### Expected Behavior

- BeanStalk Environment's ASG should launch instances with just the specified security group and not with "default" BeanStalk security group + user specific security group.

### Actual Behavior

- BeanStalk Environment's ASG launch configuration has "default" BeanStalk security group + the user specific security group.
specified security group

### Steps to Reproduce

1. Create a basic beanstalk environment module
2. Set this software environment setting:
```
  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name = "SecurityGroups"
    # provide your security group ID as string 
    value = var.ease_beanstalk_security_group
    resource = ""
```

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by UdhavPawar** [comment]
> Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

Thanks @danieldreier
