### ISSUE TITLE
Treat strings like lists for use in collection functions

### ISSUE THREAD

**Issue by ajohnston9** [hashicorp/terraform#24825]
### Current Terraform Version
```
Terraform v0.12.24
+ provider.tls v2.1.1
```

### Use-cases
This issue has become frustrating for me as I'm trying to generate a public key for a DKIM record and having to jump through a number of hoops just to handle the fact that I have to add a set of double quotes after the first 255 characters. 

Moreover, I think most Terraform users are accustomed to programming languages where strings to some extent naturally act like lists (e.g. in Python, you can simply call `"hello"[0]` and get `'h'` but I can't call `element("hello",0)` and expect `"h"`. 

### Attempted Solutions
For me, I have to do something like the following:
```
output "dkim_record" {
    value = "v=DKIM1; k=rsa; p=${substr(element(regex("-----BEGIN PUBLIC KEY-----(.*)-----END PUBLIC KEY-----",join("",split("\n",data.tls_public_key.dkim_pub.public_key_pem))),0)0,237)}\"\"${substr(element(regex("-----BEGIN PUBLIC KEY-----(.*)-----END PUBLIC KEY-----",join("",split("\n",data.tls_public_key.dkim_pub.public_key_pem))),0)237,512)}"
}
```
### Proposal
Treat strings as a subset of lists and allow string arguments as list functions. For my predicament, I would really prefer first-class treatment of DKIM records but the problem of how to manipulate strings should likely be dealt with first.

**Comment by apparentlymart** [comment]
Hi @ajohnston9!

So we can be sure we understand the given use-case, would you mind showing what the expected output format of that long expression is? I'm having a little trouble imagining what that is doing and I got a syntax error when I tried to execute it as-is so I think something may have got lost in summarization. :confounded:

**Comment by apparentlymart** [comment]
Hi @ajohnston9,

I didn't hear back from you, so I'm going to close this for now. Please let me know if you'd like to continue talking about this enhancement request!
