### ISSUE TITLE
Panic: runtime error

### ISSUE THREAD

**Issue by dzirg44** [hashicorp/terraform#24835]
In my configuration i use HTTPS proxy variables, with one url I have error with another everything works fine. Both of proxies work fine, only one difference in kubernetes cluster version , but it cannot be a problem . 

### Terraform Version

```
Terraform v0.12.24
+ provider.helm v1.1.1
+ provider.kubernetes v1.11.1
+ provider.tls v2.1.1
+ provider.vault v2.10.0
```

### Terraform Configuration Files
i guess it can be connected with some external providers, but i am not sure

### Debug Output
https://gist.github.com/dzirg44/1d6e0c9ebe47f578da3062cf2d33e823

### Crash Output
https://gist.github.com/dzirg44/1d6e0c9ebe47f578da3062cf2d33e823

### Expected Behavior
apply without errors or crashes

### Actual Behavior
application crashed

plan or validate run without errors.

P>S. also i can provide  access to  my cluster if it needs.

**Comment by dzirg44** [comment]
figured out what is going on, *go* libraries don't have 
`curl -v -k --proxy-insecure`
only with this flag i have errors.

**Comment by danieldreier** [comment]
Ah! Very nice troubleshooting. I really appreciate your update here.

**Comment by dzirg44** [comment]
@danieldreier i think you cannot check this bug with mitmproxy because of 
https://github.com/mitmproxy/mitmproxy/issues/3398
this bug (i also faced with it)
I will come up something..

**Comment by danieldreier** [comment]
Thanks! I really appreciate your help working up a reproduction.

**Comment by oliverjhernandez** [comment]
Hey guys,

I'm having the exact same error when going through a simple squid proxy.

**Comment by dzirg44** [comment]
@oliverjhernandez i could reproduce this bug only with AWS ALB, if you can provide your squid config , it would be nice.

**Comment by oliverjhernandez** [comment]
Hi, sorry for the delay.
Have you found a work around for this?

Here's the squid.config we use
https://gist.github.com/oliverjhernandez/dcdb7a647c136166eff61fea8fab2f6b

**Comment by danieldreier** [comment]
@dzirg44 @oliverjhernandez I have tried to reproduce this using squid and have been unsuccessful. I put up a reproduction case in https://github.com/danieldreier/terraform-issue-reproductions/tree/master/24835 so we can collaborate on a reproduction case more easily.

@oliverjhernandez the only thing I had to change from your squid config was to allow local access so I could actually use the squid proxy from my workstation.

I haven't been able to create a situation where any kind of proxy configuration causes terraform to panic. If you can, please help me reproduce it! I'd love to get it fixed.

**Comment by danieldreier** [comment]
This has gone without a response since June 15th, so I'm going to close it. I do believe this is probably a real issue, and I would love to fix it, but that's not possible without a clear reproduction case. If anyone involved in this can help come up with a good reproduction case, please let me know (ddreier@hashicorp.com) or feel free to file a new issue and link to this one.
