### ISSUE TITLE
Add support for EFS mounts in ECS Fargate tasks

### ISSUE THREAD

**Issue by nbrys** [hashicorp/terraform#24830]
### Current Terraform Version

```
0.12.18
```

### Use-cases
Add an EFS volume to ECS Fargate tasks

### Proposal
Extend https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html#efs_volume_configuration to be compatible with ECS fargate tasks. According to https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/ this should now be possible.

### References
https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/

**Comment by cgmckeever** [comment]
@nbrys did you close this because it does work with Fargate/EFS ? Thanks -- about to go down this path
