### ISSUE TITLE
Terraform backend config file is ignored when explicitly specified.

### ISSUE THREAD

**Issue by ArseniiPetrovich** [hashicorp/terraform#24845]
### Terraform Version
```
Terraform v0.12.24
```

### Terraform Configuration Files
main.tf file:
```hcl
output "test" {
  value = "Hello, World"
}
```
terraform.backend file:
```hcl
terraform {
  backend "local" {}
}
```
### Debug Output
https://gist.github.com/ArseniiPetrovich/dc3bc69a25592fc789c0543cae48b7e4

### Expected Behavior
According to the Terraform docs:
File: A configuration file may be specified via the init command line. To specify a file, use the -backend-config=PATH option when running terraform init. If the file contains secrets it may be kept in a secure data store, such as Vault, in which case it must be downloaded to the local disk before running Terraform.

### Actual Behavior
Terraform does not see any backend files.

### Steps to Reproduce

1. Put two files above to the temp folder.
2. `terraform init -upgrade=false -backend-config=terraform.backend`

### References
https://github.com/gruntwork-io/terratest/pull/518

**Comment by jbardin** [comment]
Hi @ArseniiPetrovich,

The `-backend-config` flag can point to a file containing key-value pairs for configuration of the backend named in the config. The file itself is not a meant to contain a complete configuration block. This should probably return some sort of error when we don't get any valid configuration values.
