### ISSUE TITLE
Not able to write to Vault using aws/ vault terraform provider

### ISSUE THREAD

**Issue by amarjothi** [hashicorp/terraform#24844]
### Terraform Versio
```
Terraform v0.12.24
```

### Terraform Configuration Files

```hcl
resource "tls_private_key" "ec2" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "generated_key" {
  key_name   = local.key_name
  public_key = tls_private_key.ec2.public_key_openssh

}

locals {
  resource_key_name = aws_key_pair.generated_key.key_name
  key_pair_id= aws_key_pair.generated_key.key_pair_id
  fingerprint = aws_key_pair.generated_key.fingerprint
  
}

resource "vault_generic_secret" "example" {
  
  path = "tf/cas/terraformkv/data/test/kv"
  

  data_json = <<EOT
{
  "key_name":   ${local.resource_key_name},
  "key_pair_id": ${local.key_pair_id},
  "fingerprint": ${local.fingerprint}
}
EOT
}
```

### Crash Output

Error: failed to create limited child token: Error making API request.

URL: POST https://vaultip/v1/auth/token/create
Code: 403. Errors:

* 1 error occurred:
	* permission denied

  on <empty> line 0:
  (source code not available)

### Expected Behavior
data written to Vault

### Actual Behavior
Getting 403 error, the path value we specify in the configuration file, is not taken into consideration when the Vault API request is made, and hence we get a http 403 back. If the path value is taken into consideration, the call will be successful.

Vault API, the namespace seems to have a specific requirement,
ie,  there is 'data' tag in-between namespace and path.

namespace/data/path

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the Vault Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the Vault provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by jeffsanicola** [comment]
I think the auth role for Vault that Terraform is using needs the `update` permission on `auth/token/create` per https://www.terraform.io/docs/providers/vault/index.html#token
