### ISSUE TITLE
Wrong version of terraform in releases for 0.12.22 linux_amd64

### ISSUE THREAD

**Issue by siwyroot** [hashicorp/terraform#24864]
It looks like following archive contains wrong version of terraform, expected 0.12.22 but got 0.12.21.

[https://releases.hashicorp.com/terraform/0.12.22/terraform_0.12.22_linux_amd64.zip](https://releases.hashicorp.com/terraform/0.12.22/terraform_0.12.22_linux_amd64.zip)

**Comment by danieldreier** [comment]
I've confirmed this. How odd - I will investigate. Thank you for reporting it!

**Comment by danieldreier** [comment]
okay, team reminded me that this was a known bug that was [fixed in 0.12.23](https://github.com/hashicorp/terraform/blob/v0.12/CHANGELOG.md#01223-march-05-2020). The version was reporting wrong.
