### ISSUE TITLE
Terraform fails with unexpected end of JSON input error

### ISSUE THREAD

**Issue by AshOfSpades** [hashicorp/terraform#24885]
Hi there,

I have been trying to pass a SQL query as a payload to a lambda function (written in C#). I have tested it through console and it works without any issues. However when I try to do the same using Terraform I am getting following error -
Error: unexpected end of JSON input 

### Terraform Version
v12.18

### Terraform Configuration Files
```
data "aws_lambda_invocation" "sqlscript" {
  function_name = aws_lambda_function.mysqllambda.function_name

  input = jsonencode({
    script = file("${path.module}/query.sql")
  })
}
```

```hcl
...
```
### Expected Behavior
Lambda should be able to create table in RDS db.

### Actual Behavior
Fails with following error -
`Error: unexpected end of JSON input    on lambda.tf line 124, in data "aws_lambda_invocation" "sqlscript":  124: data "aws_lambda_invocation" "sqlscript" { `

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider.
