### ISSUE TITLE
API: config.LoadDir / LoadFile don't support hcl2 / 0.12 syntax

### ISSUE THREAD

**Issue by mykter** [hashicorp/terraform#24881]
_(edit: found the `configs` module)_
### Terraform Version
```
0.12.24
```

### Expected Behavior
The docs for LoadDir state it is for 0.11 and earlier, and point to the configs module instead

### Actual Behavior
LoadDir returns an error for valid config, for example: `unexpected token while parsing list: IDENT` because it is treating the input as <=0.11 syntax.

### Steps to Reproduce
Call `config.LoadDir` with a path that contains a 0.12.x config with non-backwards-compatible syntax elements.

### Additional Context
It looks like the 0.12 version of LoadFile is in loader_hcl2.go, but it isn't public. 

I was using LoadDir to load, validate, and then inspect some generated config files - it looks like I should have been using configs.Parser instead, and config.LoadDir shouldn't be used?

### References
LoadDir was added here: #18 
The new private loadFile functionality is here: https://github.com/hashicorp/terraform/blob/v0.12.24/config/loader_hcl2.go#L39
The package I initially missed that does work with 0.12 syntax: https://pkg.go.dev/github.com/hashicorp/terraform/configs?tab=doc

**Comment by danieldreier** [comment]
@mykter we recommend against using Terraform as a go library. The fact that terraform can be imported and used as a library is essentially an accident. Martin wrote a [discussion forum post](https://discuss.hashicorp.com/t/terraform-automation-is-there-any-way-to-interact-with-terraform-cli-using-api-golang/4935) that "there is no supported in-process Go library API for Terraform", and that's the current official stance. We maintain stable interfaces via the API, and via HCL, but internally, Terraform is subject to significant changes like you've seen, and we don't (currently) consider those bugs.

**Comment by mykter** [comment]
OK, thanks
