### ISSUE TITLE
Nested loops -- Multuple VMs -- Multiple disks

### ISSUE THREAD

**Issue by vijayrajah** [hashicorp/terraform#24897]
I'm trying to create multiple server with multiple disks attached in azure.

Here is what my Disk object looks like 
```
variable "data_disk" {
    default = [
        {
            size = "128"
            lun = "0"
            name_suffix = "disk0"
            disk_tag = "aaa"
        },
        {
            size = "1024"
            lun = "1"
            name_suffix = "disk1"
            disk_tag = "bb"
        }
    ]
}
```

```
variable "vmcount" { default = "3"}
variable "vmprefix" {default = "aaa"}
```

I want to attach 2 disks to each of these 3 VMs.

i tried this:
```
locals {
	vm_names = {
		value = [for c in range(var.vmcount) : format("%s%0d",var.vmprefix,c)]
	}
}

locals {
	disk_details = flatten([
		for k, v in var.data_disk : [
			for vm in local.vm_names : {				
				name = "${vm}"
				disk_size_gb = v.size
			}
		]
	])
}
```

I go this output 
```
Outputs:

a = [
  {
    "disk_size_gb" = "128"
    "name" = [
      "aaa0",
      "aaa1",
      "aaa2",
    ]
  },
  {
    "disk_size_gb" = "1024"
    "name" = [
      "aaa0",
      "aaa1",
      "aaa2",
    ]
  },
]

```

Instead I want something like this:
```
{
  "disk_size_gb: = "128"
  "name" = "aaa0-disk0"
},
{
  "disk_size_gb: = "1024"
  "name" = "aaa0-disk1"
},

{
  "disk_size_gb: = "128"
  "name" = "aaa1-disk0"
},
{
  "disk_size_gb: = "1024"
  "name" = "aaa1-disk1"
},
{
  "disk_size_gb: = "128"
  "name" = "aaa2-disk0"
},
{
  "disk_size_gb: = "1024"
  "name" = "aaa2-disk1"
},
```

How do I achieve this?

**Comment by true64gurus** [comment]
Hi, you could try something like this.. 

locals {
    vm_array = flatten([
       for k, v in var.data_disk : [
         for i in range(var.vmcount): {
           disk_size_gb = v.size
           name = format("%s%g-%s", var.vmprefix , i , v.name_suffix)
         }
       ]
    ])
}

output "vms_array" {
  value = local.vm_array
}


>>terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

vms_array = [
  {
    "disk_size_gb" = "128"
    "name" = "aaa0-disk0"
  },
  {
    "disk_size_gb" = "128"
    "name" = "aaa1-disk0"
  },
  {
    "disk_size_gb" = "128"
    "name" = "aaa2-disk0"
  },
  {
    "disk_size_gb" = "1024"
    "name" = "aaa0-disk1"
  },
  {
    "disk_size_gb" = "1024"
    "name" = "aaa1-disk1"
  },
  {
    "disk_size_gb" = "1024"
    "name" = "aaa2-disk1"
  },
]

**Comment by danieldreier** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, I don't immediately see evidence of a bug in Terraform core. I'm going to close this for now, because I think the community forum is the right approach.
