### ISSUE TITLE
AWS: Existing SSL certificates prevent dependent resources from provisioning

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#2490]
I have a certificate that I've created using terraform, but if it's not destroyed (for whatever reason), and I then attempt to re-apply the config, AWS (via terraform) yells at me saying the resource already exists.

```
resource "aws_iam_server_certificate" "some_certificate" {
    name = "some_certificate_name"
    certificate_body = "${file("files/certificates/certificate.crt")}"
    certificate_chain = "${file("files/certificates/chain.crt")}"
    private_key = "${file("files/certificates/key.pem")}"
}                                                                                    
```

My desired behavior is terraform syncs the local state with the resource that currently exists. Or am I misreading the warning and it does it already? I don't believe it does as the load balancer that depends on the certificate won't be created.

**Comment by nathanielks** [comment]
[Here are some logs.](https://gist.github.com/nathanielks/542b54d31c88c1523d08)

**Comment by mitchellh** [comment]
In your logs, it appears that Terraform believes that the certificate doesn't exist. Are you using the same state file? Terraform can't rediscover resources it created from another state file. In fact, it looks like according to the logs your state file is empty (nothing is in it).
