### ISSUE TITLE
Why isn't there a web based editor to edit configuration in the cloud? 

### ISSUE THREAD

**Issue by kundeng** [hashicorp/terraform#24900]
### Current Terraform Version

```
...
```

### Use-cases

This seems so obvious to me but I'm new to terraform.  You have gone all the way to support multiple VCSs. 

Minimally, we should be able to see the configurations, but better yet why don't allow the user to view and edit configurations, instead of just variables???

**Comment by pkolyvas** [comment]
Hey @kundeng ,

Thanks for taking the time to request this Terraform Cloud enhancement. This issue tracker is for the Terraform Open Source tool. 

I've forwarded your request to the Terraform Cloud Team. Should you wish to contact them via our support team you can send them a message @ tf-cloud-support@hashicorp.com. 

If you have an Enterprise account, please use your enterprise team contacts.

Thanks,
PK
