### ISSUE TITLE
Document how to create multiple copies of an environment

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/terraform#2491]
I want to have 1 QA environment per active feature branch.  I understand now that resource names cannot have variables, which leaves me unsure how to do this with Terraform.  [The docs](https://www.terraform.io/intro/use-cases.html) (under "Disposable Environments") indicate that this is possible, but I don't really see any examples for this use case.  

Is the right way like this (where `./app_environment` would define e.g. a web and DB server)?
```
module "qa-feature1" {
    source = "./app_environment"
}

module "qa-feature2" {
    source = "./app_environment"
}

module "staging" {
    source = "./app_environment"
}

module "production" {
    source = "./app_environment"
}
```

Or to call terraform from the command line like this?
`NAME=qa-feature1 terraform plan -var “NAME=$NAME” -state=“$NAME.tfstate”`
`NAME=qa-feature2 terraform plan -var “NAME=$NAME” -state=“$NAME.tfstate”`
`NAME=staging terraform plan -var “NAME=$NAME” -state=“$NAME.tfstate”`
`NAME=production terraform plan -var “NAME=$NAME” -state=“$NAME.tfstate”`

I'll be happy to update the docs via a PR once I have a better understanding.

**Comment by jjshoe** [comment]
I do the latter myself.

**Comment by outrunthewolf** [comment]
I also do the latter, but for many regions.

I use a little script to do the hard work:

```sh
#!/bin/bash
COMMAND=$1
REGION=$2
STORE_DIR="../terraform_states"

# Make a regional directory if it doesn't exist
if [ ! -d "$STORE_DIR/$REGION" ]; then
    mkdir $STORE_DIR/$REGION
fi

# For any planning
if [ "$COMMAND" == "plan" ]; then
    terraform plan -out=$STORE_DIR"/"$REGION"/"out.tf -state=$STORE_DIR"/"$REGION"/"terraform.tfstate -var='region='$REGION
fi
```

Then I can just type:

```sh
./tfscript plan eu-west-1
```

You get the idea...

**Comment by stack72** [comment]
Hi @jkodroff 
Apologies this slipped through the net. For best practices around multiple environments have a look here

https://github.com/hashicorp/best-practices/tree/master/terraform

Sorry again for the time this took!

Paul
