### ISSUE TITLE
Argument conflicts while using null in aws_route53_record

### ISSUE THREAD

**Issue by denzhel** [hashicorp/terraform#24912]
### Terraform Version
```
Terraform v0.12.24
provider.aws v2.61.0
```

### Terraform Configuration Files
1. main.tf
```hcl
resource aws_route53_zone "bp_route53_zone" {                                                                                                                                     
  name = "dennis.io."
}

resource aws_route53_record "bp_route53_record" {
  zone_id = aws_route53_zone.bp_route53_zone.zone_id
  name    = "test.dennis.io"
  type    = "A"
  ttl     = var.lb_name == "" ? 300 : null
  records = var.lb_name == "" ? ["8.8.8.8"] : null

  alias {
    name                   = var.lb_name == "" ? null : "prod-service-elb-130352321.eu-west-3.elb.amazonaws.com"
    zone_id                = var.lb_name == "" ? null : "Z3Q77PNBQS71R4"
    evaluate_target_health = false
  }
}
```
2. variables.tf
```hcl
variable "lb_name" {                                                                                                                                                              
  type    = string
  default = ""
}
```

### Expected Behavior
Null function basically omits the argument, this allows us to dynamically and conditionally use arguments according to our needs. In this case, I'm trying to use the same resource to create multiple zones and records (I've simplified the example). Some records are A, MX, NS and etc .. and some are aliases. I use var.lb_name as an indicator, if the variable is set to a load balancer's name, I look it up in my exported outputs and assign the relevant info(using the alias block). If the variable is not set, it will create normal records(using the ttl and records arguments).

### Actual Behavior
While trying to conditionally set arguments with values or null, it fails. I get conflicts all the time.
The only case it will work is if I set records argument to null (without the condition)
```hcl
Error: "ttl": conflicts with alias

  on main.tf line 5, in resource "aws_route53_record" "bp_route53_record":
   5: resource aws_route53_record "bp_route53_record" {



Error: "records": conflicts with alias

  on main.tf line 5, in resource "aws_route53_record" "bp_route53_record":
   5: resource aws_route53_record "bp_route53_record" {



Error: "alias": conflicts with records

  on main.tf line 5, in resource "aws_route53_record" "bp_route53_record":
   5: resource aws_route53_record "bp_route53_record" {
```

### Steps to Reproduce
1. Create a dummy AWS elb
2. Copy its zone id and dns address
3. Paste the info on the code I've provided
4. Run Terraform apply and get the error
5. Change records to null
6. Run again and see that it works

**Comment by denzhel** [comment]
Managed to solve it by using the following block:

```hcl
  dynamic "alias" {
    for_each = length(each.value.lb_name) == 0 ? [] : [each.value.lb_name]
    content {
      name                   = [for elb, info in var.elb_zone_ids : info.lb_address if elb == each.value.lb_name][0]
      zone_id                = [for elb, info in var.elb_zone_ids : info.zone_id if elb == each.value.lb_name][0]
      evaluate_target_health = false
    }
```
If there's any other way other than using for_each on a string and converting it to list with [] while at it, please let me know.

**Comment by apparentlymart** [comment]
Hi @denzhel!

I think what's going on here is that the provider's own validation logic is considering the presence of the `alias` block (regardless of contents) as a request to create an alias record, which then causes the non-alias-related arguments to be prohibited.

A `dynamic "alias"` block is indeed a good way to create a conditionally-present `alias`, ensuring that the result is valid in either case. I might write it a little differently so that the expressions inside the `content` block can be simpler, but this should be functionally equivalent:

```hcl
  dynamic "alias" {
    for_each = each.value.lb_name != "" ? [var.elb_zone_ids[each.value.lb_name]] : []
    content {
      name                   = alias.value.lb_address
      zone_id                = alias.value.zone_id
      evaluate_target_health = false
    }
  }
```

**Comment by denzhel** [comment]
Thank you @apparentlymart  for the reply ! 

Why did you use alias.value.lb_address and not each.value.lb_address ? Is there any difference or benefit from addressing the alias rather than each ?

**Comment by apparentlymart** [comment]
`each.value` is the value from the main resource `for_each` expression, while `alias.value` is the value from the `dynamic "alias"` block's `for_each` expression.

I don't think I saw in your full examples what your resource's own `for_each` was set to, but `each.value` would be an element from _that_ collection, while `alias.value` here is referring to the selected element from `var.elb_zone_ids`.

**Comment by denzhel** [comment]
Thank you for the great explanation !
