### ISSUE TITLE
Integrate DNSControl

### ISSUE THREAD

**Issue by gurjeet** [hashicorp/terraform#24923]
### Current Terraform Version
```
Terraform v0.12.24
```

### Use-cases
Support Hexonet DNS provider.

### Attempted Solutions
None, because there doesn't seem to be any documentation suggesting that Terraform supports Hexonet.

### Proposal
Integrate [DNSControl][] package into Terraform. This will allow Terraform users to use all the Providers supported by DNSControl, including Hexonet whose support I am looking for.

[DNSControl]: https://github.com/StackExchange/dnscontrol

### References
I could not find any mention of Hexonet in any Terraform related Docs, code, or issue.

**Comment by pkolyvas** [comment]
Hi @gurjeet!

Thanks for writing. This repository is for the core Terraform tool, which is independent of providers. 

When it comes to a new provider, the best place to start is with the community of users and the vendor of that particular tool or service. That means either Hexonet or DNSControl and their communities would be the place to bootstrap provider development. 

We have some documentation on [writing custom providers ](https://www.terraform.io/docs/extend/writing-custom-providers.html)if it's something that is of interest to you. 

Thanks!
