### ISSUE TITLE
aws_budgets_budget create and update fail with multilpe TagKeyValue cost_filters

### ISSUE THREAD

**Issue by ndench** [hashicorp/terraform#24924]
When managing an `aws_budgets_budget` resource, a single `cost_filter` for `TagKeyValue` is all that can be specified, if multiple are specified, an error occurs on both create and update.

The create/update must be applied manually in the AWS Budgets Console, and then `terraform apply` successfully completes as long as there are no required changes to the `aws_budgets_budget` resource.

### Terraform Version
```
Terraform v0.12.24
+ provider.aws v2.41.0
```

### Terraform Configuration Files
```hcl
resource "aws_budgets_budget" "test" {
  name = "test-budget"
  budget_type = "COST"
  limit_amount = "1.0"
  limit_unit = "USD"
  time_period_start = "2020-05-01_00:00"
  time_unit = "MONTHLY"

  cost_filters = {
    TagKeyValue = "user:App$my-app,user:App$my-app-2"
  }
}
```

### Expected Behavior
The budget should be created or updated.

### Actual Behavior
When trying to initially create the resource:
```
Error: create budget failed: InvalidParameterException: Failed to call CreateBudget for [AccountId: 771882897437] - null
        status code: 400, request id: b471c15f-dabb-4656-8267-bc2f4e49fa6e

  on main.tf line 525, in resource "aws_budgets_budget" "test":
 525: resource "aws_budgets_budget" "test" {
```

When trying to update a resource:
```
Error: update budget failed: InvalidParameterException: Failed to call UpdateBudget for [AccountId: 771882897437] - null
        status code: 400, request id: 99f2e1b0-0a5f-4ea6-8b23-c5bdacd42f24

  on main.tf line 525, in resource "aws_budgets_budget" "test":
 525: resource "aws_budgets_budget" "test" {

```

### Steps to Reproduce
1. Add `aws_budgets_budget` resource specified above
2. `terraform apply` -> fails with `update budget failed` error
4. Comment out the `TagKeyValue` line
5. `terraform apply` -> success
6. Uncomment the `TagKeyValue` line
7. `terraform apply` -> fails with `update budget failed` error
8. Add the specified tags in the AWS Budgets console
9. `terraform apply` -> success with no changes
10. Change some other parameter (not TagKeyValue)
11. `terraform apply` -> fails with `update budget failed` error
12. Remove one of the tags from `TagKeyValue`
13. `terraform apply` -> success

### Additional Context
The tags specified in `TagKeyValue` need to be [cost allocation tags](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html), I've been using user defined ones which I had to enable in the Billing Console. 

It appears that the [aws budgets cli](https://docs.aws.amazon.com/cli/latest/reference/budgets/create-budget.html) takes `TagKeyValue` as a list, maybe the data type is incorrect?

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.

**Comment by ndench** [comment]
Ah, fair point @danieldreier, my bad. I should have realised that. Thanks for migrating it.
