### ISSUE TITLE
Cannot destroy due to cycles when using create_before_destroy

### ISSUE THREAD

**Issue by joekhoobyar** [hashicorp/terraform#2493]
This should not produce cycles - and it makes the workaround for #2421 unusable for the ``terraform destroy`` case. 

**In other words, we can create infrastructure, but we cannot destroy it!**

Here are the files involved, and example output:

https://gist.github.com/joekhoobyar/5421b3ebbf9c313404ec

**Comment by joekhoobyar** [comment]
#2438 also makes a reference to this issue, but the code in this ticket is a much smaller example yielding the same problem.  All you need to do to duplicate this issue is run:  ``terraform destroy``

**Comment by joekhoobyar** [comment]
FWIW - The only workaround I have found is literally to:
* ``sed -e 's/create_before_destroy = true/create_before_destroy = false/g' -i .bk infrastructure.tf``
* ``terraform destroy``
* ``mv infrastructure.tf.bk infrastructure.tf`.

Clearly, the ``create_before_destroy`` is affecting destroy logic.  Since we aren't creating anything, only destroying, there should be no impact at all.  Can this be fixed?

**Comment by catsby** [comment]
Hey @joekhoobyar – sorry for the silence here. Unfortunately, at this time you cannot use the `create_before_destroy = true` key in the `lifecycle` block on a resource if it depends on other resources that are **not** also `create_before_destroy = true`. 

For example, in configuration you shared resource `aws_launch_configuration.mobilecloud` is `create_before_destroy`, and depends on `aws_iam_instance_profile.mobilecloud`, `aws_security_group.mobilecloud`, and `template_file.mobilecloud-bootstrap`. Of those three, the `template_file` resource is the only one that is also `create_before_destroy = true`. 

In order for your example configuration to successfully destroy with no cycles, the same `create_before_destroy` lifecycle block needs to be added to each resource up the dependency graph.:

- `aws_iam_instance_profile.mobilecloud`
- `aws_iam_role.mobilecloud`
- `aws_security_group.mobilecloud`

This is a known limitation that isn't currently documented, so I opened https://github.com/hashicorp/terraform/pull/2944 in attempt to document it better. 

Sorry again for the trouble and the silence, I hope this clears things up!

**Comment by catsby** [comment]
#2944 documenting this issue was merged, so I'm going to close this issue now. Please let me know if you have further questions. 

Thanks!

**Comment by gposton** [comment]
I just found this after reporting a duplicate issue myself (https://github.com/hashicorp/terraform/issues/3294).  This introduces a significant limitation for us: 

> When the lifecycle rule is not on the ASG, I can change the AMI in the launch config w/o the ASG being destroyed (thus cycling my instances).

> When the lifecycle rule is added to the ASG, both the ASG and the launch config is destroyed and re-created. This cycles my instances which happens too quickly for all of our services to initialize and pass health checks.

**Comment by roboll** [comment]
IMHO this issue deserves a 'real' solution; however, I've had success using the `taint` command on launch configurations and their autoscaling groups prior to destroy. This triggers terraform to ignore dependency cycles, and eliminates the need to cascade `create_before_destroy` across the entire manifest for everything the launch configuration depends on. Cascading `create_before_destroy` for the sake of appeasing the dependency graph isn't really a viable solution, in my experience the performance impact is severe.

    terraform apply
    terraform taint -module mymodule aws_launch_configuration.mylc
    terraform taint -module mymodule aws_autoscaling_group.myasg
    terraform destroy

**Comment by gposton** [comment]
Thanks @roboll for the workaround... and I completely agree w/ your assessment.... 

> Cascading create_before_destroy for the sake of appeasing the dependency graph isn't really a viable solution

**Comment by rojaro** [comment]
This issue should not have been closed. The problem described here is not addressed in any of the other 28 open issue related to create_before_destroy and still present.

**Comment by ljsommer** [comment]
This issue is a massive inconvenience that continues to haunt our infrastructure. It usually results in us forcefully and very manually disassembling everything and then starting from scratch.

**Comment by joshuaspence** [comment]
Is there an issue that I can track for a real solution here? I'll admit that I haven't looked into this issue in any great detail, but it seems like this could be fixed by having Terraform automatically apply `create_before_destroy` to dependent resources as well? For example, if I specify an `aws_launch_configuration` (that has `create_before_destroy` enabled) referencing an `aws_security_group`, it seems that the situation would be improved if Terraform propagated the `create_before_destroy` lifecycle attribute to the `aws_security_group` resource.
