### ISSUE TITLE
App Settings from Function App asking to be modified every time I run terraform apply

### ISSUE THREAD

**Issue by mansing2** [hashicorp/terraform#24937]
### Terraform Version
```
Terraform v0.11.14
+ provider.azuread v0.8.0
+ provider.azurerm v1.44.0
+ provider.null v2.1.1
+ provider.template v2.1.1

```

### Terraform Configuration Files
```
resource "azurerm_function_app" "function-app" {
  name                      = "test-functions"
  location                  = "${var.location}"
  resource_group_name       = "${var.resourceGroupName}"
  app_service_plan_id       = "${var.appServicePlanId}"
  version = "~3"
  storage_connection_string = "DefaultEndpointsProtocol=https;AccountName=${var.funcStorageName};AccountKey=${var.funcStorageKey}"
  app_settings {
      "APPINSIGHTS_INSTRUMENTATIONKEY"="${var.appInsightsUrl}",
      "AzureWebJobsDashboard" = "@Microsoft.KeyVault(SecretUri=https://${var.vaultName}.vault.azure.net/secrets/StorageFuncConnectionString/)"
      "AzureWebJobsStorage" = "@Microsoft.KeyVault(SecretUri=https://${var.vaultName}.vault.azure.net/secrets/StorageFuncConnectionString/)"
     
  }
```

### Debug Output
NA

### Crash Output
Below is what I get on every run of ```terraform apply```
```
 ~ azurerm_function_app.function-app
2020-05-13T04:03:37.2666326Z       app_settings.%:                                          "8" => "10"
2020-05-13T04:03:37.2669082Z       app_settings.AzureWebJobsDashboard:                      "" => "@Microsoft.KeyVault(SecretUri=https://kvl-test.vault.azure.net/secrets/StorageFuncConnectionString/)"
2020-05-13T04:03:37.2671934Z       app_settings.AzureWebJobsStorage:                        "" => "@Microsoft.KeyVault(SecretUri=https://kvl-test.vault.azure.net/secrets/StorageFuncConnectionString/)"
```
### Expected Behavior
The expected behavior is that the terraform should not ask to modify the values being set for AzureWebJobsDashboard and AzureWebJobsStorage in App Settings on every run of the terraform plan/apply.

### Actual Behavior
Every single time I run terraform apply, the AzureWebJobsStorage and AzureWebJobsDashboard showing to be modified.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
NA

**Comment by rquadling** [comment]
I'm not an expert, but my experience shows that sometimes, planning only suggests changes, but it won't know until apply time if they are actually going to change. What does the plan say about the changes?

I'd recommend upgrading to Terraform 0.12 as that seems to provide clearer reasoning over its decisions.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
