### ISSUE TITLE
AWS Route Table - target argument network_interface_id recreates the resource

### ISSUE THREAD

**Issue by mpiala** [hashicorp/terraform#24939]
### Terraform Version

```
Terraform v0.12.24
```

### Use Case [bug] - AWS routing table with target *network_interface_id*
We would like to create route in AWS which target argument is `network_interface_id`. According to the Terraform [documentation](https://www.terraform.io/docs/providers/aws/r/route_table.html#route-argument-reference), only one target argument can be used.

In our case the target of route should be 3rd network interface of firewall instance (that's why we cannot use `instance_id` as a target argument).

### Terraform Configuration Files - AWS route table

```hcl
resource "aws_route_table" "private" {
  vpc_id = aws_vpc.vpc.id
  route {
    cidr_block           = "10.10.10.0/24"
    network_interface_id = aws_network_interface.firewall_eni2.id
  }
}
```

### Expected Behavior

`terraform plan`
-> to create resource route table (Plan: 1 to add, 0 to change, 0 to destroy.)
`terraform apply`
-> created resource route table (Resources: 1 added, 0 changed, 0 destroyed.)
`terraform plan`
-> nothing (Plan: 0 to add, 0 to change, 0 to destroy.)
`terraform apply`
-> nothing (Resources: 0 added, 0 changed, 0 destroyed.)

### Actual Behavior

`terraform plan`
-> to create resource route table (Plan: 1 to add, 0 to change, 0 to destroy.)
`terraform apply`
-> created resource route table (Resources: 1 added, 0 changed, 0 destroyed.)
`terraform plan`
-> **to recreate resource** route table (**Plan: 1 to add**, 0 to change, **1 to destroy**.)
`terraform apply`
-> **recreated resource** route table (**Resources: 1 added**, 0 changed, **1 destroyed**.)

### Steps to Reproduce
1. prepare code for new route table with target argument `network_interface_id` (instance should have more than 1 eni, most probably)
2. `terraform apply`
3. do nothing
4. `terraform apply`

### Current Workaround
After small investigation we found out the resource `aws_route_table` in tfstafe contains both `network_interface_id` and `instance_id`.
According to the documentation, we cannot add both of the target arguments in the code.

Therefore we applied two-step workaround:
1. In the initial build of the route table, defined value only for `network_interface_id` 
```hcl
resource "aws_route_table" "private" {
  vpc_id = aws_vpc.vpc.id
  route {
    cidr_block           = "10.10.10.0/24"
    network_interface_id = aws_network_interface.firewall_eni2.id
  }
}
```
2. In the following build, to add also value for `instance_id` - no change expected as it is already covered in tfstate. This step is in a **conflict with the Terraform [documentation](https://www.terraform.io/docs/providers/aws/r/route_table.html#route-argument-reference)**.
```hcl
resource "aws_route_table" "private" {
  vpc_id = aws_vpc.vpc.id
  route {
    cidr_block           = "10.10.10.0/24"
    network_interface_id = aws_network_interface.firewall_eni2.id
    instance_id          = aws_instance.firewall.id
  }
}
```

### Proposed solution
A. If the _route target argument_ is solely `network_interface_id`, do not recreate the same resource (it might cause an unexpected outage, as happened in our environment).

or

B. Allow two route target arguments (if the `instance_id` contains more than one ENI) in one step and update the documentation. However this might cause another confusion.
We were quite surprised, it allowed us to add additional target argument in 2-step workaround.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
