### ISSUE TITLE
Provider search for registry

### ISSUE THREAD

**Issue by abitrolly** [hashicorp/terraform#24949]
### Use-cases

I was looking for info who maintains [GitLab provider](https://www.terraform.io/docs/providers/gitlab/index.html).

[GitHub provider page](https://www.terraform.io/docs/providers/github/index.html) contains a link to https://registry.terraform.io/providers/hashicorp/github/2.7.0 but GitLab page is missing that info.

I tried to search the registry explicitly for GitLab but no provider is to be found in https://registry.terraform.io/search?q=gitlab and no provider is found for GitHub https://registry.terraform.io/search?q=github too. The provider filter on the left doesn't include GitHub too.

### Attempted Solutions

Eventually I discovered that the search string only looks for modules. This is not what I really really expected.

### Proposal

Search both modules and providers.

**Comment by bflad** [comment]
Hi @abitrolly 👋  Thank you for raising this. It appears that this enhancement has been implemented since it was filed. Opening https://registry.terraform.io and typing `gitlab` into the search bar yields multiple provider results. Please reach out if you need anything else.
