### ISSUE TITLE
azurerm_storage_account: PATCH is not valid in the allowed_methods of the cors_rule

### ISSUE THREAD

**Issue by diegopeinador** [hashicorp/terraform#24941]
### Terraform Version

```
Terraform v0.12.24
+ provider.azurerm v2.6.0
```

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.6"
  features {}
}

resource "azurerm_resource_group" "test-cors" {
  name     = "test-cors-RG"
  location = "West Europe"
}

resource "azurerm_storage_account" "test-cors" {
  name                     = "terraformtestcors"
  resource_group_name      = azurerm_resource_group.test-cors.name
  location                 = azurerm_resource_group.test-cors.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  enable_https_traffic_only= true
  account_kind             = "StorageV2"
  static_website {
    index_document = "index.html"
  }
  blob_properties {
    cors_rule {
        allowed_headers    = ["x-ms-*"]
        allowed_methods    = [
            "PUT",
            "OPTIONS",
            "POST",
            "GET",
            "HEAD",
            "DELETE",
            "MERGE",
            "PATCH", # Not allowed by terraform CLI, but present on Azure
        ]
        allowed_origins    = ["http://localhost:61674"]
        exposed_headers    = ["x-ms-*"]
        max_age_in_seconds = 86400
    }
  }
  tags = {"DETELEME":"THIS IS A TEST"}
}
```

### Debug Output

terraform validate:
```bash
Error: expected blob_properties.0.cors_rule.0.allowed_methods.7 to be one of [DELETE GET HEAD MERGE POST OPTIONS PUT], got PATCH

  on test-cors.tf line 11, in resource "azurerm_storage_account" "test-cors":
  11: resource "azurerm_storage_account" "test-cors" {
```

### Expected Behavior

PATH To be a valid method.

### Actual Behavior

Error from the validator

### Steps to Reproduce
1. `terraform init`
2. `terraform validate`

### Additional Context

In the Azure portal the patch is listed as a valid method:
<img width="229" alt="Screenshot 2020-05-13 at 15 03 21" src="https://user-images.githubusercontent.com/3635322/81818413-4b256e80-952e-11ea-878c-4dd7fcd97e45.png">

### References

The documentation is consistent with the validator and doesn't list PATCH as a valid method for this parameter:
https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#allowed_methods

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
