### ISSUE TITLE
Lambda Provisioned Concurrency Cannot Change Simultaneously with Alias

### ISSUE THREAD

**Issue by TheFLHurricane** [hashicorp/terraform#24957]
I have encountered an issue when using aws_lambda_provisioned_concurrency_config with a lambda alias.  In most scenarios, this will work fine.  However if I am simultaneously updating the Lambda (causing a new version to be published and the alias to be moved to that new version) while also updating the provisioned_concurrent_executions, I will fail with the message "InvalidParameterValueException: Alias with weights can not be used with Provisioned Concurrency"

It seems the issue is that the alias is rolling out a canary deployment, which causes the alias to be weighted for a period of time and prevents terraform from then updating the provisioned concurrency immediately afterward.

An ideal solution would be to have provisioned concurrency play nice by allowing the current provisioned version to spin down and spinning back up the correct number with the new version (in fact it seems reasonable to recreate this resource anytime the qualifying version/alias changes)  Also reasonable would be adding an AllAtOnce Deployment Preference option to the alias to bypass the canary roll out.

### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```
resource "aws_lambda_alias" "alias" {
  name             = "alias"
  description      = "alias"
  function_name    = aws_lambda_function.lambda.function_name
  function_version = aws_lambda_function.lambda.version
}

resource "aws_lambda_provisioned_concurrency_config" "lambda" {
  function_name                     = aws_lambda_function.lambda.function_name
  provisioned_concurrent_executions = 2
  qualifier                         = aws_lambda_alias.alias.name
}
```

### Crash Output

(When changing both alias function_version and provisioned concurrency provisioned_concurrent_executions)
On Apply:

Error: error putting Lambda Provisioned Concurrency Config (lambda-function:alias): InvalidParameterValueException: Alias with weights can not be used with Provisioned Concurrency
 {
   RespMetadata: {
     StatusCode: 400,
     RequestID: "82b1c399-056e-41b7-96e5-821593e992f6"
   },
   Message_: "Alias with weights can not be used with Provisioned Concurrency",
   Type: "User"
 }

### Expected Behavior

Provisioned concurrency with new version should succeed

### Actual Behavior

Provisioned concurrency fails with InvalidParameterValueException

### Steps to Reproduce

1. Run the above resources with any aws_lambda_function.lambda resource
2. Deploy a new version of the lambda and change provisioned_concurrent_executions and run again.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
