### ISSUE TITLE
Unfortunate interaction between local-exec provisioner working_dir and path.module in command

### ISSUE THREAD

**Issue by Cinderhaze** [hashicorp/terraform#24964]
### Terraform Version

```
Terraform v0.12.6
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
resource "null_resource" "example" {
  provisioner "local-exec" {
    command    =  "${path.module}/scripts/doThing.sh"
    working_dir = "${path.module}/working_dir"
  }
}
```

### Expected Behavior

The existing executable script that is a part of the module ( scripts/doThing.sh ) should have been run as a part of the local-exec provisioner

### Actual Behavior

The path.module evaulated to `./`, which then tried to execute the the working_dir/scripts/doThing.sh script (which did not exist) instead of the scripts/doThing.sh script.

### Additional Context

I can make my command path relative to the work directory and it will work correctly, but it seems counter-intuitive that path.module doesn't mean the path to the module when used as a part of the command.  

```hcl
resource "null_resource" "example" {
  provisioner "local-exec" {
    command    =  "../scripts/doThing.sh"
    working_dir = "${path.module}/working_dir"
  }
}
```

**Comment by danieldreier** [comment]
@Cinderhaze I reproduced locally that this behaves exactly as you described, but I think that this is working exactly as designed, and as documented: according to the [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html#command) documentation,

>command - (Required) This is the command to execute. It can be provided as a relative path to the current working directory or as an absolute path. It is evaluated in a shell, and can use environment variables or Terraform variables.

You're providing a relative path, and relative paths are evaluated relative to the working directory. `working_dir` is akin to running a `cd` to that directory before running the command. I also tested and confirmed that when I use an absolute path (starting in /), it runs the `scripts/doThing.sh` as expected.
