### ISSUE TITLE
Encrypt Terraform state with KMS managed keys for GCS backend

### ISSUE THREAD

**Issue by dinvlad** [hashicorp/terraform#24967]
### Current Terraform Version

```
v0.12.25
```

### Use-cases

Following up on https://github.com/hashicorp/terraform/issues/16836 and https://github.com/hashicorp/terraform/pull/16936, currently the GCS backend supports customer-_supplied_ encryption key, which is stored in clear text on the client, when configured using the `encryption_key` parameter for the backend.

Instead, GCS has supported [customer-_managed_ keys](https://cloud.google.com/storage/docs/encryption/customer-managed-keys) for some time now, which could provide a simple way to encrypt Terraform state with KMS.

### Attempted Solutions

We may be able to use [_default_ customer-managed keys](https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys#using_default_encryption_keys), which enable transparent encryption/decryption of objects, without any explicit configuration for the GCS backend in Terraform.

### Proposal

It would be great to be able to explicitly specify a KMS Customer-Managed encryption key in GCS backend:

```tf
terraform {
  backend "gcs" {
    bucket  = "tf-state-prod"
    prefix  = "terraform/state"
    kms_encryption_key {
      location = "us-east1" # optional, defaults to 'global'
      key_ring = "terraform-keyring"
      key = "terraform-key" 
    }
  }
}
```

This would allow us to enforce the encryption on the bucket, instead of relying on the implicit configuration of the default key for the bucket (which can oftentimes be overlooked).

Additionally, this would prevent the encryption key leakage (as it would not be stored on the client) and enable its rotation through KMS, as opposed to the current static setting for `encryption_key`.

### References

- #16836
- #16936

**Comment by FranAguiar** [comment]
Are there any chance for this enhacement?

**Comment by crw** [comment]
@FranAguiar, thanks for the question! The GCP team has looked into the feasibility of this feature, but there is not currently a specific commitment or timeline. If that changes we will update this ticket. Thanks again!
