### ISSUE TITLE
FQDN output from azurerm_dns_a_record has a dot in the end

### ISSUE THREAD

**Issue by joaooamaral** [hashicorp/terraform#24982]
### Terraform Version

```
Terraform v0.12.24
+ provider.azurerm v2.9.0
+ provider.random v2.2.1
```

### Terraform Configuration Files

```hcl
resource "azurerm_dns_a_record" "pip-ppr-dc-a-record" {
  name                = "${lower(var.client-name)}-ppr01"
  zone_name           = data.azurerm_dns_zone.devops-dns-zone.name
  resource_group_name = "DomainRegistrationGroup"
  ttl                 = 300
  target_resource_id  = azurerm_public_ip.pip-ppr-dc.id
}

output "fqdn-ppr-dc" {
  value = azurerm_dns_a_record.pip-ppr-dc-a-record.fqdn
}

resource "azurerm_application_gateway" "agw-ppr" {
  name                = "AGW-Ppr"
  resource_group_name = var.rg_bootcamp
  location            = var.location
backend_address_pool {
    name          = "agw-ppr-backendpool"
    fqdns         = [var.fqdn_ppr_dc, var.fqdn_ppr_fe]
  }
}


```

### Debug Output

When I run terraform apply, under fqdns you can see it outputs the FQDN but with a dot at the end

```
 # module.agws.azurerm_application_gateway.agw-ppr will be created
  + resource "azurerm_application_gateway" "agw-ppr" {
      + id                  = (known after apply)
      + location            = "westeurope"
      + name                = "AGW-Ppr"
      + resource_group_name = "DevOpsProject-Bootcamp"

      + backend_address_pool {
          + fqdns = [
              + "devopsproject-ppr01.redacteddomain.com.",
              + "devopsproject-ppr02.redacteddomain.com.",
            ]
          + id    = (known after apply)
          + name  = "agw-ppr-backendpool"
        }
```

### Crash Output

I then obviously get an error accepting the `terraform apply`:

Error: Error Creating/Updating Application Gateway "AGW-Ppr" (Resource Group "DevOpsProject-Bootcamp"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayBackendAddressInvalidFormat" Message="Backend Address /subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/DevOpsProject-Bootcamp/providers/Microsoft.Network/applicationGateways/AGW-Ppr/backendAddressPools/agw-ppr-backendpool does not meet the format requirements. **The address must contain only digits, letters, hyphens and dots for separation. Moreover, it cannot have hyphens at the start, end or next to a dot." Details=[]**

### Expected Behavior

The output of resource azurerm_dns_a_record shouldn't come with a dot in the end

### Actual Behavior

The output of resource azurerm_dns_a_record comes with a dot in the end

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Not sure if this is working as design or if there is anyway for me to automatically remove the last dot

**Comment by danieldreier** [comment]
Thanks for reporting this! This is an interesting case because [RFC 1035](https://tools.ietf.org/html/rfc1035) specifies that
> Domain names that end in a dot are called absolute, and are taken as complete.  

Yet, it sounds like either AzureRM or the terraform provider handle them inconsistently. This is happening outside of Terraform Core, though, and this github repository is for Terraform Core issues. 

I think that this is an issue to be addressed in the AzureRM Terraform provider, rather than in core. I'm going to label it as such, and the HashiBot will shortly migrate it over to the  provider GitHub repository. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
