### ISSUE TITLE
Variable Validation should use lazy evaluation

### ISSUE THREAD

**Issue by matteomazza91** [hashicorp/terraform#24998]
### Terraform Version
0.12.24

### Terraform Configuration Files

```hcl
variable "my_variable_name" {
  type = object({
    a = string
    b = string
  })
  validation {
    condition     = var.my_variable_name == null || (var.my_variable_name.a != null && var.my_variable_name.b != null)
    error_message = "Something."
  }
}
```

### Debug Output
```
Error: Attempt to get attribute from null value

  on [...]/variables.tf line 96, in variable "my_variable_name":
  96:     condition     = var.my_variable_name == null || (var.my_variable_name.a != null && var.my_variable_name.b != null)
    |----------------
    | var.my_variable_name is null

This value is null, so it does not have any attributes.

  on [...]/variables.tf line 96, in variable "my_variable_name":
  96:     condition     = var.my_variable_name == null || (var.my_variable_name.a != null && var.my_variable_name.b != null)
    |----------------
    | var.my_variable_name is null

This value is null, so it does not have any attributes.
```

### Expected Behavior
if `var.my_variable_name` is null, the condition for variable-validation should evaluate to true

### Actual Behavior
error returned because the right part of the validation expression is evaluated. It fails evaluating both `var.my_variable_name.a` and `var.my_variable_name.b` because `var.my_variable_name` is null

**Comment by jbardin** [comment]
Hello @matteomazza91,

Thanks for filing the issue. This isn't specific to variable validation, conditional operators not short-circuiting evaluation is a known issue we're tracking in #24128.

Closing as a duplicate.
