### ISSUE TITLE
GCS Backend doesn't support credentials of type "authorized_user"

### ISSUE THREAD

**Issue by fpoon** [hashicorp/terraform#25040]
### Terraform Version

```
0.12.24 and 0.12.25
```

### Configuration Files

**configuration.tf.json**
```json
...
"terraform": {
        "backend": {
            "gcs": {
                "bucket": "project-bucket-tfstate",
                "prefix": "tfstate/",
                "credentials": "/home/user/.config/gcloud/application_default_credentials.json"
            }
        }
    },
...
```

**/home/user/.config/gcloud/application_default_credentials.json**
```json
{
  "client_id": "<client id>",
  "client_secret": "<client secret>",
  "refresh_token": "<refresh token>",
  "type": "authorized_user"
}
```

### Expected Behavior
GCS Backend should be initialized properly, using json credentials of type `authorized_user`, just like with `service_account` type.

### Actual Behavior
Initialization of GCS Backend fails on request to Google Storage API with message
```
Error: Failed to get existing workspaces: querying Cloud Storage failed: Get https://www.googleapis.com/storage/v1/b/project-bucket-tfstate/o?alt=json&delimiter=%2F&pageToken=&prefix=tfstate%2F&prettyPrint=false&projection=full&versions=false: private key should be a PEM or plain PKCS1 or PKCS8; parse error: asn1: syntax error: sequence truncated
```

### Steps to Reproduce
1. login to Google Cloud SDK with `gcloud` tool - `gcloud auth application-default login`
2. create terraform configuration with `gcs` backend and `credentials` set to json obtained in previous step
3. run `terraform init`

### Additional Context
This behavior is inconsistent with google-provider, where both types of credentials are accepted.

I'm able to workaround this issue by setting GOOGLE_APPLICATION_CREDENTIALS environment variable, so it points to that json file, and subsequently is picked up by Google API Client, but I think that proper solution is required here. 

If that's OK with you, I'd like to contribute a fix to this issue.

**Comment by upodroid** [comment]
@fpoon That is not how to use User ADCs.

You run `gcloud auth application-default login` and leave the credentials field empty.
