### ISSUE TITLE
Tfstate corruption when moving AWS Lambda code to a Layer

### ISSUE THREAD

**Issue by thekguy** [hashicorp/terraform#25085]
```
Terraform v0.12.25
+ provider.aws v2.61.0
```

I have noticed a problem when I run "terraform apply" to update an AWS Lambda Function to move code from the Lambda's package to a Layer. This happens when the Lambda function's previous package size and the new Layer's size sum to more than the 250mb limit of layers + package. The "terraform apply" not only fails but also puts things in a bad state.

The problem can be reproduced in two steps. In the first step, declare a Lambda Function with no layers and make its package size larger than half the 250mb limit, say, 126mb when unzipped. Run terraform apply.

Version 1:

```hcl
resource "aws_lambda_function" "my_lambda_function" {
  name = "my-lambda-function"
  s3_key = "lambda_code_plus_dependency_126mb_prior_to_compression.zip"
...
  layers = []
}
```

In step 2, modify your Terraform code to introduce a Lambda Layer having a size of at least half the 250mb limit but less than 250mb itself, say, 125mb when unzipped. Modify your Lambda Function's declaration from Version 1 above to reference the new layer while also changing the Lambda's package to be small enough to sum with the layer and still fit under the 250mb limit, say, by shrinking it to 1mb (unzipped).

Version 2:

```hcl
resource "aws_lambda_layer_version" "my_lambda_layer_version" {
  s3_key = "dependency_alone_125mb_prior_to_compression.zip"
...
}

resource "aws_lambda_function" "my_lambda_function" {
  name = "my-lambda-function"
  s3_key = "lambda_code_alone_1mb_prior_to_compression.zip"
...
  layers = [aws_lambda_layer_version.my_lambda_layer_version.arn]
}
```

Then run "terraform apply".

Ideally, I would expect that one would be able to update the Lambda successfully to use the new layer. But when I do it manually from the AWS console, AWS reports that I am exceeding the 250mb limit, so I need to shrink the function code package of the Lambda and save the modifications to the Lambda before I can introduce the Layer. This is unfortunate because you are forced to put your Lambda into a non-working state if you really need all 126mb of code for your program to run, but is an AWS issue, not a Terraform issue.

If you update your Terraform code to Version 2 above and run "terraform apply", Terraform reports the error about exceeding the size threshold of 250mb:

```
Error: Error modifying Lambda Function Configuration my-lambda-function: InvalidParameterValueException: Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 263192576 bytes.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "53796a9d-5ced-4b9e-a0dd-fcbfd4885706"
  },
  Message_: "Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 263192576 bytes.",
  Type: "User"
}
```

I guess this is to be expected because AWS does the same thing, but I expect that this failure should not corrupt the tfstate file. I made a copy of my tfstate file before I ran "terraform apply" on Version 2. After running "terraform apply" on Version 2, I compared the two versions of tfstate file and saw that the layer had been added to my-lambda-function and the s3_key had been updated despite the error.

Now, if I attempt to fix the problem by updating the Lambda in two steps, taking out the layer in the Terraform code (as in Version 2a below) and re-running terraform apply, it fails to see the change in the content and so does nothing:

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Version 2a:

```hcl
resource "aws_lambda_function" "my_lambda_function" {
  s3_key = "lambda_code_alone_1mb_prior_to_compression.zip"
...
}
```

To workaround this issue, I changed the code back to Version 1, ran "terraform apply", changed the code to version 2a and ran "terraform apply" to get terraform to pick up the file change and see the new content size as 1mb. Then I was able to update to Version 2 (to add the Layer) and run "terraform apply" successfully.

**Comment by danieldreier** [comment]
@thekguy I appreciate you reporting this. I'm having a hard time understanding the issue you're reporting, so I've been a bit slow to triage it. Right now, I'm trying to understand what's actually happening, so that I can figure out whether this should be addressed in terraform core or in the AWS provider. I think that this is a provider issue, but I'm not quite sure, and so I'd appreciate your help here.

I'm not sure what you mean when you say that the terraform state is corrupted. I think that you're saying that after you get back the `Function code combined with layers exceeds the maximum allowed size` error, the state file shows that the layer you added was added successfully, when in fact it was not added in the lambda, and so the state is inaccurate. Is that accurate?

Second, are you using the s3 backend? Does it matter?

**Comment by thekguy** [comment]
@danieldreier Thank you for looking into this issue. Yes, what I meant by corrupted is that the state no longer matches AWS because the state file believes the layer was added successfully while in reality it was not. I was using the s3 backend. I did not test with a local tfstate file.

**Comment by danieldreier** [comment]
Thanks @thekguy! I think this is most likely an issue with the provider, because terraform core stores whatever state the provider returns. I'm going to label this so that hashibot can automatically migrate it to the AWS provider github repo.
