### ISSUE TITLE
Invalid index - XXX is is empty tuple when destroying on conditional resource

### ISSUE THREAD

**Issue by jaksky** [hashicorp/terraform#25080]
### Terraform Version

```
Terraform v0.12.26
+ provider.google v3.23.0
+ provider.google-beta v3.23.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
```

### Terraform Configuration Files

```hcl
resource "google_compute_address" "cluster_ingress" {
  count = var.cluster_standard_deployments.ingress ? 1 : 0

  name = "${var.cluster_name}-ingress-ip"
}


output "ingress_ip" {
  value       = { (var.cluster_name) = (var.cluster_standard_deployments.ingress ? google_compute_address.cluster_ingress.0.address : null) }
  description = "IP address reserved for nginx ingress cluster"
}
...
```

### Expected Behavior

Resources should be destroyed and output empty value??

### Actual Behavior

Error: Invalid index

  on ../../modules/k8s_deployments/output.tf line 2, in output "ingress_ip":
   2:   value       = { (var.cluster_name) = (var.cluster_standard_deployments.ingress ? google_compute_address.cluster_ingress.0.address : null) }
    |----------------
    | google_compute_address.cluster_ingress is empty tuple

The given key does not identify an element in this collection value.

### Steps to Reproduce

Have terraform env deployed with conditional resource enabled.
terraform destroy 
will fail either on first or on rerun

### Additional Context

Do I need a null check condition in case of different run order or how to treat empty or non existing list in output?

**Comment by jbardin** [comment]
Hi @jaksky,

Thanks for reporting this. I confirmed this is fixed in master, and will be included in the next major release.

**Comment by danieldreier** [comment]
@jaksky [Terraform 0.13.0 beta 1 launched today](https://github.com/hashicorp/terraform/issues/25016), and you're welcome to confirm the issue you reported is fixed in it. If it isn't, please feel free to file a new issue or reach to to me (ddreier@hashicorp.com) and I can re-open this one.
