### ISSUE TITLE
Provisioning tutorial remote-exec not working

### ISSUE THREAD

**Issue by tiagob** [hashicorp/terraform#25092]
Following the tutorial
https://learn.hashicorp.com/terraform/getting-started/provision but remote-exec fails

### Terraform Version

```
% terraform -v
Terraform v0.12.26
+ provider.aws v2.64.0
```

### Terraform Configuration Files
```hcl
provider "aws" {
  profile = "default"
  region  = "us-west-2"
}

resource "aws_key_pair" "example" {
  key_name   = "examplekey"
  public_key = file("~/.ssh/terraform.pub")
}

resource "aws_instance" "example" {
  key_name      = aws_key_pair.example.key_name
  ami           = "ami-04590e7389a6e577c"
  instance_type = "t2.micro"

  connection {
    type        = "ssh"
    user        = "ec2-user"
    private_key = file("~/.ssh/terraform")
    host        = self.public_ip
  }

  provisioner "remote-exec" {
    inline = [
      "sudo amazon-linux-extras enable nginx1.12",
      "sudo yum -y install nginx",
      "sudo systemctl start nginx"
    ]
  }
}
```

### Debug Output
https://gist.github.com/tiagob/c7ea184eb799937ee160d1471b4f0663

### Expected Behavior

remote-exec runs

### Actual Behavior

```
aws_instance.example (remote-exec): Connecting to remote host via SSH...
aws_instance.example (remote-exec):   Host: 52.43.45.77
aws_instance.example (remote-exec):   User: ec2-user
aws_instance.example (remote-exec):   Password: false
aws_instance.example (remote-exec):   Private key: true
aws_instance.example (remote-exec):   Certificate: false
aws_instance.example (remote-exec):   SSH Agent: true
aws_instance.example (remote-exec):   Checking Host Key: false
aws_instance.example: Still creating... [5m10s elapsed]
aws_instance.example: Still creating... [5m20s elapsed]


Error: timeout - last error: dial tcp 52.43.45.77:22: i/o timeout
```

### Steps to Reproduce

```
terraform apply
```

**Comment by dgttm** [comment]
I got the same problem and can confirm the behavour.

I seems to me that it's an issue with systemctl commands, they seem to "hang" remote-exec somehow. 

it doesnt't matter if you use a remote script or inline-commands, once you use systemctl the process never ends until timeout happens.

**Comment by frntn** [comment]
I've seen the following in the documentation (https://www.terraform.io/docs/provisioners/connection.html) :

> Note: In Terraform 0.11 and earlier, providers could set default values for some connection settings, so that connection blocks could sometimes be omitted. This feature was removed in 0.12 in order to make Terraform's behavior more predictable.

So I believe the correct syntax should be : 
```tf
  provisioner "remote-exec" {

    connection {
      type        = "ssh"
      user        = "ec2-user"
      private_key = file("~/.ssh/terraform")
      host        = self.public_ip
    }

    inline = [
      "sudo amazon-linux-extras enable nginx1.12",
      "sudo yum -y install nginx",
      "sudo systemctl start nginx"
    ]

  }
```

**Comment by bflad** [comment]
Hi folks 👋  Thank you for reporting this. It appears that since this issue was raised that the HashiCorp Learn tutorials have since moved or materially changed as the link is now pointing to a Packer tutorial instead of one featuring Terraform's remote-exec provisioner. Given that, I'm going to close this issue out. I believe it is now possible to provide direct feedback on the tutorial pages so that the team that maintains them, which doesn't typically monitor the issues in this repository, can act on it.
