### ISSUE TITLE
Is there any way to disable module execution by condition

### ISSUE THREAD

**Issue by ivanguravel** [hashicorp/terraform#25109]
Hello!

As per our requirements we have 2 options of downloading modules for users:
- if some of them has an access to one source, they should use first one
- if some has second,  they need to use second.

how to implement switching modules by condition. like we can do with `count` for resources, but with disabling module execution at all.

### Current Terraform Version
Terraform v0.12.21

### Use-cases
Make 2 modules. If condition is true -> terraform executes one , if false - another.

### Attempted Solutions
i tried to do different scripts, but those are too hacky. 

### References
i read about https://github.com/hashicorp/terraform/issues/12906 , but that's about execution some stuff inside module, not for my case.

Thanks in advance for your help and ideas.

**Comment by ipmb** [comment]
#17519 might be what you want if you can wait for the release of 0.13, setting count to `1` or `0` based on your condition, e.g.

```
count = var.condition ? 1 : 0
```

**Comment by ivanguravel** [comment]
> #17519 might be what you want if you can wait for the release of 0.13, setting count to `1` or `0` based on your condition, e.g.
> 
> ```
> count = var.condition ? 1 : 0
> ```

Thanks for your help! Seems like 0.13 has been released. will wait for stable version then
