### ISSUE TITLE
error applying change of aws_launch_configuration (ami)

### ISSUE THREAD

**Issue by wernerwws** [hashicorp/terraform#2512]
files to reproduce the error are at https://github.com/wernerwws/terraform_issue.git

terraform version
Terraform v0.5.3

terraform apply
var.access_key
  Default: 
  Enter a value: 

var.secret_key
  Default: 
  Enter a value: 

aws_launch_configuration.worker: Refreshing state... (ID: worker)
aws_autoscaling_group.worker: Refreshing state... (ID: worker)
aws_launch_configuration.worker: Destroying...
aws_launch_configuration.worker: Error: 1 error(s) occurred:

* ResourceInUse: Cannot delete launch configuration worker because it is attached to AutoScalingGroup worker
	status code: 400, request id: [39d17856-1bf3-11e5-8146-f14588707425]
Error applying plan:

2 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* ResourceInUse: Cannot delete launch configuration worker because it is attached to AutoScalingGroup worker
	status code: 400, request id: [39d17856-1bf3-11e5-8146-f14588707425]
* 1 error(s) occurred:

* aws_autoscaling_group.worker: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by CpuID** [comment]
@wernerwws I hope that keypair was revoked... :)

**Comment by wernerwws** [comment]
Yes, it was! Thanks anyway!

**Comment by mitchellh** [comment]
When working with launch configurations, you should either leave off the `name` parameter to have it auto-generate, or insert some sort of randomness in there. They have some weird ordering otherwise. Unfortunately we don't have any other fix other than this. In TF 0.5 we introduced the random name generation to help with this.
