### ISSUE TITLE
Module depends_on does not delay reading nested data resources

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#25121]
### Terraform Version

```
Terraform v0.13.0-beta1
```

### Terraform Configuration Files

Root module:

```hcl
resource "local_file" "example" {
  content  = "hello world"
  filename = "${path.root}/hello.txt"
}

module "uses_local_file" {
  source     = "./uses-local-file"
  depends_on = [local_file.example]
}

output "hello" {
  value = module.uses_local_file.hello
}
```

The module in `./uses-local-file`:

```hcl
data "local_file" "example" {
  filename = "${path.root}/hello.txt"
}

output "hello" {
  value = data.local_file.example.content
}
```

(the above is a contrived example just to illustrate the issue, not a reasonable thing to be doing in practice.)

### Expected Behavior
Terraform should see that `module.uses_local_file` has a dependency on `local_file.example` and that `local_file.example` is pending creation, and therefore defer reading `module.uses_local_file.data.local_file.example` until the apply phase.

### Actual Behavior
Terraform tried to read the data resource during the refresh phase, as it would normally do in the absence of `depends_on`:

```
$ terraform apply
module.uses_local_file.data.local_file.example: Refreshing state...

Error: open ./hello.txt: no such file or directory

  on uses-local-file/main.tf line 2, in data "local_file" "example":
   2: data "local_file" "example" {
```

### Steps to Reproduce
With a configuration like the one above, apply the configuration as normal with no existing state:

* `terraform init`
* `terraform apply`

**Comment by dotenorio** [comment]
I had a similar problem, i think:
https://github.com/hashicorp/terraform/issues/25016#issuecomment-638464991
