### ISSUE TITLE
Terraform 0.13 validate crashes on Custom Validation Rules when error_message contains an accent

### ISSUE THREAD

**Issue by sharkyze** [hashicorp/terraform#25143]
### Terraform Version

```
Terraform v0.13.0-beta1
```

### Terraform Configuration Files

```hcl
variable "email_address" {
  type    = string
  default = "Application <application@example.com>"
  validation {
    condition     = can(regex(".{4,20} <.+@example.com>", var.email_address))
    error_message = "A sentence with an accent é."
  }
}
```

### Debug Output

https://gist.github.com/sharkyze/b3db1dd702518f2ad7d067b1a469f3f8

### Crash Output

https://gist.github.com/sharkyze/b3db1dd702518f2ad7d067b1a469f3f8

### Expected Behavior

Not to crash

### Actual Behavior

Terraform crashes

### Steps to Reproduce

```
$ mkdir tf-crash && cd tf-crash
$ cat <<END >main.tf
variable "email_address" {
  type    = string
  default = "Application <application@example.com>"
  validation {
    condition     = can(regex(".{4,20} <.+@example.com>", var.email_address))
    error_message = "A sentence with an accent é."
  }
}
END
$ terraform validate
```
### References

The error comes from the following line due to the accent: https://github.com/hashicorp/terraform/blob/ff4ea042c208f7a5115b045de56fe6faba56bdc5/configs/named_values.go#L402
I was able to fix this bug by making the following changes: https://github.com/hashicorp/terraform/compare/master...sharkyze:configs/fix-looksLikeSentences-index-out-of-range?expand=0.

I would be happy to send a PR if you are ok with the changes

**Comment by danieldreier** [comment]
Thanks @sharkyze! I really, really appreciate you testing out 0.13!

I have [reproduced this issue](https://github.com/danieldreier/terraform-issue-reproductions/tree/master/25143) on 0.13 beta 1.
