### ISSUE TITLE
No compatible versions of registry.terraform.io/-/terraform provider - 0.13-beta1

### ISSUE THREAD

**Issue by jeffwecan** [hashicorp/terraform#25148]
### Terraform Version

```
Terraform v0.13.0-beta1
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"

  required_providers {
    acme = {
      source  = "terraform-providers/acme"
      version = "~> 1.5"
    }
   # etc., no explicit entry for `terraform` here
  }
}
data "terraform_remote_state" "infrastructure" {
  backend = "remote"
  config = {
    hostname     = "<some TFE instnace>"
    organization = var.tfe_org_name
    workspaces = {
      name = var.tfe_infrastructure_workspace_name
    }
  }
}
...
```

### Debug Output

https://gist.github.com/jeffwecan/d0307acdf6976aae1ec20a7e23b04599

### Expected Behavior

The builtin terraform provider should have been selected with no attempt to download the legacy https://registry.terraform.io/providers/hashicorp/terraform provider.

### Actual Behavior

The https://registry.terraform.io/providers/hashicorp/terraform provider provider was downloaded 

### Steps to Reproduce

1. Include a `terraform_remote_state` data source in a batch of terraform config
1. Run `terraform init` with 0.13-beta1 

Note: the issue only appears to come up when working with extant state. I.e.,  an `init` run against the same configuration in a fresh workspace / empty state does not hit the same issue.

**Comment by alisdair** [comment]
Thanks for the report, @jeffwecan! I was able to reproduce this, but only when there's an existing local state file (created with Terraform 0.12). My config:

```hcl
data terraform_remote_state "random" {
  backend = "remote"
  config = {
    organization = "alisdair-v2"
    workspaces = {
      name = "terraform-random"
    }
  }
}

output ids {
  value = data.terraform_remote_state.random.outputs.random
}
```

**Comment by jeffwecan** [comment]
Hmm, so it turns out that "removing" the long `terraform_remote_state` data source ([logs](https://gist.github.com/jeffwecan/381d8d141d5cdde5c4310e533d42d32e)) and _then_ re-running `terraform init` worked just fine: https://gist.github.com/jeffwecan/a6e3fc902ef5fc251683532836f5aaf3

**Comment by mildwonkey** [comment]
Hi, thanks for reporting this! 

Unfortunately this bug will impact anyone using terraform v0.13-beta1 and `terraform_remote_state` - I've got a fix in process, but if you are interested in testing the beta release and use `terraform_remote_state` you will need to wait until 0.13-beta2, or build from master once the fix is merged (I will link the PR once I have it ready)
