### ISSUE TITLE
Crash when using terraform_remote_state data source

### ISSUE THREAD

**Issue by alisdair** [hashicorp/terraform#25150]
### Terraform Version
```
Terraform v0.13.0-dev
```

Built from 0b38ab30782462153ea8b82613b9e2eb39bc3dc7

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12"
}

data "terraform_remote_state" "random" {
  backend = "remote"
  config = {
    organization = "alisdair-v2"
    workspaces = {
      name = "terraform-random"
    }
  }
}

output ids {
  value = data.terraform_remote_state.random.outputs.random
}
```

### Debug Output
https://gist.github.com/alisdair/7c02fc9340d4686e8797d9a2b8fec777#file-output-log

### Crash Output
https://gist.github.com/alisdair/7c02fc9340d4686e8797d9a2b8fec777#file-crash-log

### Expected Behavior
Apply succeeds and displays outputs from Terraform Cloud workspace.

### Actual Behavior
Crash.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### References
I found this while trying to reproduce #25148.

**Comment by jbardin** [comment]
This is also fixed by the upstream change: https://github.com/zclconf/go-cty/pull/55
