### ISSUE TITLE
apply doesn't update some attributes in state file

### ISSUE THREAD

**Issue by dmettem** [hashicorp/terraform#25164]
### Terraform Version

```
Terraform v0.12.25
+ provider.vra (unversioned)

Your version of Terraform is out of date! The latest version
is 0.12.26. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```hcl
resource "vra_deployment" "this" {
  name        = var.deployment_name
  description = "terraform test deployment-1"

  catalog_item_id      = data.vra_catalog_item.this.id
  catalog_item_version = var.catalog_item_version
  project_id           = data.vra_project.this.id

  inputs = {
    count = 2
    flag = false
  }

  timeouts {
    create = "30m"
    delete = "30m"
    update = "30m"
  }
}
```

### Debug Output
Nothing that points to an incorrect behavior. Output shows that the read method is invoked at the end of update, and hence the attributes should be updated as received in the response.

### Crash Output
N/A

### Expected Behavior
When a change is made to `vra_deployment` resource inputs and apply command is run, all the attributes should get updated into the state file upon successful completion of the command run.

### Actual Behavior
Few attributes such as `last_request` and `resources` under the `vra_deployment` resource are not updated in the state file when `apply` command is run, however when the `refresh` command is run, all the attributes are updated as expected.

Debug output shows that the read method is invoked at the end of update, and hence the attributes should be updated as received in the response. But they are not updated as part of apply, but an immediate refresh command updates all the attributes.

### Steps to Reproduce
1. Install the terraform-provider-vra plugin from https://github.com/vmware/terraform-provider-vra/releases/latest.
2. Create a workspace and use the configuration files from https://github.com/vmware/terraform-provider-vra/tree/master/examples/deployment/catalog_item and update the correct values for tfvars.
3. Run `terraform init`
4. Run `terraform apply` and observe the state file upon successful completion.
5. Make changes to one of the values in `inputs` argument under `vra_deployment` resource and run the `terraform plan` command.
6. Run `terraform apply` command make sure it completes successful.
7. Verify the state file and note that the attributes `last_request` and `resources` in the `vra_deployment` resources still show the old values whereas the rest of the attributes are updated as expected. Check the API responses as they show the latest values that failed to updated in state file.
8. Run the `terraform refresh` command and note the state file this time that all the attributes are updated as expected and same as the API response received.

### Additional Context
NA
### References
NA

**Comment by abelal83** [comment]
This looks more like an issue with the provider than terraform. I'd suggest you open an issue on the vra provider site.

**Comment by dmettem** [comment]
I work on vra provider and from my tests so far, it doesn't appear to be an issue with the provider. Looking for help to narrow down the issue.

**Comment by jbardin** [comment]
Hi @dmettem,

Terraform core should be storing exactly what the provider is returning to us. A common problem is eventual consistency delay in the remote service, causing the values being read back immediately after an update to not reflect the latest update. You can try logging what you get back for the `inputs` during `Read`. 

The `inputs` however are not computed, so they can only come from the configuration and there should be no reason to `Set` then in the `Read` function if they are already set. You can check for warnings in the logs or incorrectly changed values from the provider, which may give some more clues.

**Comment by dmettem** [comment]
Hi @jbardin,

Thanks for getting back. The issue is not with the `inputs`, but the `last_request` and `resources` which are computed attributes as per schema.

I initially suspected that it may be the remote service response, but it doesn't appear to be that. Here I've added the snippets from both log and state file for one of the attributes (`last_request`) after initial apply command to create the resource, next apply command to update, followed by refresh.

Here're the snippets from API response, log statement I added before `Set` and state file after initial `apply` to create, second `apply` to update and `refresh` commands.
https://gist.github.com/dmettem/f3fad48b2b32a0263f6b40fa52b8aabd

Here're the warnings during update:

> 2020/06/09 12:55:18 [WARN] Provider "registry.terraform.io/-/vra" produced an unexpected new value for vra_deployment.this, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .status: was cty.StringVal("CREATE_SUCCESSFUL"), but now cty.StringVal("UPDATE_SUCCESSFUL")
      - .inputs_including_defaults["count"]: was cty.StringVal("1"), but now cty.StringVal("2")

**Comment by jbardin** [comment]
Thanks @dmettem,

Looking at the provider code, `last_request` and `resources` are both `TypeSet`, which has some known limitations.  If there is an inconsistency between what was planned for the set value and what was applied, the legacy plugin shims need to prefer a value to pick, which IIRC is the planned value in this case in order to prevent perpetual diffs. Unfortunately because the SDK has to handle this incongruity in order to work at all, we don't get a chance to detect and log it in core.

Since the entire set is computed, you may be able to customize the diff with `SetNewComputed` to allow any new value to be saved from apply. You may also be able to simply not use a `TypeSet` at all, so that individual values can be correlated correctly. 

I'm going to close this out since it doesn't appear to be related to how Terraform core operates. Further related issues can be filed against the https://github.com/hashicorp/terraform-plugin-sdk/ repo, however the legacy SDK is mostly frozen now while work is progressing towards a new SDK that can make use of the rich type system in Terraform.
