### ISSUE TITLE
Terraform not able to enable deletion_protection for Postgres RDS replicas in AWS 

### ISSUE THREAD

**Issue by sravankurra** [hashicorp/terraform#25178]
### Terraform Version

```
Terraform v0.12.8
```

### Terraform Configuration Files

Sample configuration tf file to create instances 
```
Master instance 
resource "aws_db_instance" "master_region_replicas" {
  provider                        = "aws.master_region"
  count                           = "${var.local_replica_count}"
  apply_immediately               = "true"
  allocated_storage               = "${var.allocated_storage}"
  auto_minor_version_upgrade      = "false"
  engine                          = "${var.engine}"
deletion_protection = "${var.deletion_protection}"
performance_insights_enabled    = "${var.performance_insights_enabled}"
  performance_insights_kms_key_id = "${var.local_region_kms_arn}"
}
replicas 
resource "aws_db_instance" "cross_region_replicas" {
  provider                        = "aws.cross_region"
  count                           = "${var.cross_replica_count}"
  apply_immediately               = "true"
 replicate_source_db      = "${aws_db_instance.master.arn}"
 deletion_protection             = "${var.deletion_protection}"
  performance_insights_enabled    = "${var.performance_insights_enabled}"
  performance_insights_kms_key_id = "${var.cross_region_kms_arn}"
}
```

### Expected Behavior

Expecting to enable delete protection to all rds postgres instances
### Actual Behavior

While creating the instance terraform only  enabling delete protection to master instances not replicas. is that expected behavior from terraform or is it a bug?
### Additional Context

After RDS instances created re applying terraform is enabling delete protection to replicas, but while initial creation time terraform not able to enable delete protection to replica instances

**Comment by apparentlymart** [comment]
Hi @sravankurra,

This seems to be related to the AWS provider rather than to Terraform Core itself. Providers are developed in their own repositories, so to report a bug in the AWS provider you'll need to create an issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws).

I'm going to close this to reflect that it's a provider-specific report, rather than a Terraform Core issue. Thanks!

**Comment by sravankurra** [comment]
Thank you @apparentlymart Will open in provider repo, do I need to re open again or is there a way to move issue from here to terraform-providers?
