### ISSUE TITLE
Getting error while using this from study guide

### ISSUE THREAD

**Issue by muditmn** [hashicorp/terraform#25187]
https://learn.hashicorp.com/terraform/getting-started/dependencies

resource "aws_eip" "ip" {
    vpc = true
    instance = aws_instance.example.id
}
**This didn't worked for me. Untill i write in this below format.**
resource "aws_eip" "ip" {
    vpc = true
    instance = "${aws_instance.web.id}"
}
if i am not wrong this need to be updated on website.

**Comment by apparentlymart** [comment]
Hi @muditmn,

The problem you encountered here suggests that you are using Terraform 0.11 or earlier. The Getting Started guide is written to use syntax from the latest version of Terraform, which is Terraform v0.12 at the time I write this.

Can you confirm which version of Terraform you are using? You can run `terraform version` to see it.

**Comment by muditmn** [comment]
yes, its an older version.
**$terraform version**
Terraform v0.11.13
+ provider.aws v2.65.0

Your version of Terraform is out of date! The latest version
is 0.12.26. You can update by downloading from www.terraform.io/downloads.html
---Please help to update as well. I have downloaded the latest version zip and unzip as well.
what is next step.

**Comment by alisdair** [comment]
@muditmn How to upgrade Terraform depends on how you first installed it. [Please try following this Learn guide on installing Terraform](https://learn.hashicorp.com/terraform/getting-started/install).
