### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by yanni1994** [hashicorp/terraform#25182]
Provider produced inconsistent final plan[0m

[0mWhen expanding the plan for
module.diagnostic_settings_redis.azurerm_monitor_diagnostic_setting.main to
include new values learned so far during apply, provider
"registry.terraform.io/-/azurerm" produced an invalid new value for .log:
planned set element
cty.ObjectVal(map[string]cty.Value{"category":cty.UnknownVal(cty.String),
"enabled":cty.UnknownVal(cty.Bool),
"retention_policy":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"days":cty.UnknownVal(cty.Number),
"enabled":cty.UnknownVal(cty.Bool)})})}) does not correlate with any element
in actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by danieldreier** [comment]
Hi @yanni1994 where it says "This is a bug in the provider, which should be reported in the provider's own issue tracker." that means that this is an issue with the AzureRM provider. I'm going to label it to migrate it over there.
