### ISSUE TITLE
Format func doesn't work when multiplied by 0.1 or 10%

### ISSUE THREAD

**Issue by im-dgundam** [hashicorp/terraform#25184]
I am trying to achieve a calculated value of 0.22 for `metric_interval_lower_bound`. On TF plan it looks alright formatted but when applied I get 0.42000000000000004 and if I replace 0.1 to 0.2 it gets applied with the desired decimal format 0.44 
The value for` var.autoscaling_alb_request_duration_target` is 0.2

```
resource "aws_appautoscaling_policy" "alb_target_request_duration_scaling_policy_test" {
  count              = var.autoscaling_alb_request_duration_target == null ? 0 : 1
  name               = "service-alb-target-request-duration-policy"
  policy_type        = "StepScaling"
  resource_id        = "service/ecs-cluster/staging-ecs-service"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  step_scaling_policy_configuration {
    adjustment_type         = "PercentChangeInCapacity"
    cooldown                = 30
    metric_aggregation_type = "Average"

    step_adjustment {
      metric_interval_lower_bound = format("%.2f", var.autoscaling_alb_request_duration_target * 0.1 + var.autoscaling_alb_request_duration_target)
      scaling_adjustment          = 25
    }
  }

}
```

**Comment by apparentlymart** [comment]
Hi @im-dgundam,

The fact that this is happening only after apply suggests that it's being reformatted by either the remote AWS API or by the AWS provider itself. Terraform uses high-precision floating point for calculations, but the result you are seeing here seems like a typical approximation for a 64-bit floating point number, suggesting that either the provider itself or the remote API are storing the result as that data type and returning it to Terraform that way after applying the change.

The AWS provider is developed in [its own repository](https://github.com/terraform-providers/terraform-provider-aws), so I suggest to open a bug report issue in that repository to see what the AWS provider team makes of it. When you do, please be sure to properly fill out the issue template.

Thanks!

**Comment by im-dgundam** [comment]
will do that..thanks
