### ISSUE TITLE
State import in parallel

### ISSUE THREAD

**Issue by dexterleng** [hashicorp/terraform#25197]
I would like to import a list of resources at once, which means I run a sequence of `terraform import` commands.

Perhaps the actual state modification has to be sequential, but the API calls to fetch the state could be done in parallel.

I would be interested to contribute in its implementation if possible.

**Comment by jbardin** [comment]
HI @dexterleng 

Batch import via configuration is something we're looking into. You can track the issue via #26364

Thanks!
