### ISSUE TITLE
"panic: no expansion registered" during import (modules not expanded)

### ISSUE THREAD

**Issue by mikegreen** [hashicorp/terraform#25192]
### Terraform Version

```
Terraform v0.13.0-dev - master from today
+ provider registry.terraform.io/-/aws v2.65.0
+ provider registry.terraform.io/hashicorp/aws v2.65.0
```

This appears the same panic output as https://github.com/hashicorp/terraform/pull/25176 - But I built from master just now and still getting the error.

To note: Everytime I run it, I get a different module name in the panic - ie,
panic: no expansion has been registered for module.s3
panic: no expansion has been registered for module.rds
panic: no expansion has been registered for module.networking
which just cycles thru the modules

### Terraform Configuration Files

Running on remote backend to TFC

```hcl
main
# main.tf
# addition for TF Cloud Migration
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "pilotsnpaws"

    workspaces {
      name = "aws-infras-build"
    }
  }
}

# Setup AWS, using Ohio for now
# Requires aws configure to be run locally to setup AWS ID and Key
provider "aws" {
  version = "~> 2.54"
  profile = "pilotsnpaws"
  region  = var.aws_region
}

module "s3" {
  source = "./modules/s3"
}

module "rds" {
  source                = "./modules/rds"
  rds_security_group_id = module.networking.rds_security_group_id
}

module "compute" {
  source = "./modules/compute"
}

# Even though we use networking, via the webservers module, to create security groups, 
# having it here is redundant to calling it in the compute module and will result in 
# duplicate sec groups being planned 

module "networking" {
  source = "./modules/networking"
}


# aws-infras-build/modules/compute.hcl
# Create instances, how many defined in var instance_count

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_instance" "dev-wordpress" {

}



```

### Debug Output
https://gist.github.com/mikegreen/818c00744c793289ba0acd76ec33e4ee

### Crash Output
Console output:
panic: no expansion has been registered for module.rds

Crash.log - https://gist.github.com/mikegreen/0c428725c17bab897e01e1a78eb36bbd

### Expected Behavior
TF would Import resource (or at least try, my syntax could be wrong)

### Actual Behavior
Import crash/panic

### Steps to Reproduce

1. Init works fine
1. terraform import module.compute.aws_instance.dev-wordpress i-097f4adc96413b96a
1. This leaves workspace in locked state
1. terraform force-unlock -force pilotsnpaws/aws-infras-build
1. Trying again, same panic except it will iterate thru the modules defined

### References
https://github.com/hashicorp/terraform/pull/25176

**Comment by adamhorden** [comment]
@mikegreen I have a pipeline that compiles Terraform from master. I still see random panics so still trying to come up with a test case but your issue matches what I am seeing in master at this moment in time. I see the same random issue with the panic as well where it will choose a module at random to panic about.

#25114 is the original issue and the test case on the original issue still fails with a panic.

**Comment by WillooWisp** [comment]
Any update on when beta 2 will be released with a fix for this?

**Comment by mikegreen** [comment]
Per https://github.com/hashicorp/terraform/issues/25016 it should be tomorrow the 17th. 
I just built from master and my import problem is resolved.  Can you build it on your own and test now?
