### ISSUE TITLE
aws_sns_topic_subscription import issue

### ISSUE THREAD

**Issue by acvejic** [hashicorp/terraform#25198]
### Terraform Version

```
Terraform v0.12.25
```

### Terraform Configuration Files

```
resource "aws_sns_topic_subscription" "workersCheck_lambda" {
  topic_arn = aws_sns_topic.workersCheck.arn
  protocol  = "lambda"
  endpoint_auto_confirms          = null
  confirmation_timeout_in_minutes = null
  endpoint  = aws_lambda_function.workersCheck.arn
}
```

### Expected Behavior

Terraform plan should not show any changes after the import and aligning resource with the imported state.  
### Actual Behavior
shows that current changes will be applied
      + confirmation_timeout_in_minutes = 1
      + endpoint_auto_confirms          = false

### Steps to Reproduce

1. Create SNS topic subscription manualy through AWS console
2. Use terraform import to import state of the resource
3. Aligne changes in resource
4. terraform plan
5. shows that current changes will be applied
      + confirmation_timeout_in_minutes = 1
      + endpoint_auto_confirms          = false
### Additional Context

I'm trying to import manually created aws_sns_topic_subscription and then change it in tf so no changes will be applied when running plan/apply.
In terraform.tfstate I can see for this resource:
```
{
  "module": "module.testing",
  "mode": "managed",
  "type": "aws_sns_topic_subscription",
  "name": "workersCheck_lambda",
  "provider": "provider.aws",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "arn": "arn:aws:sns:eu-west-2:123456789:checking_workers:XXXXXXXXXXXXXXXXXX",
        "confirmation_timeout_in_minutes": null,
        "delivery_policy": "",
        "endpoint": "arn:aws:lambda:eu-west-2:955776871051:function:XXXXXXXXXXXXXXXXXX",
        "endpoint_auto_confirms": null,
        "filter_policy": "",
        "id": "arn:aws:sns:eu-west-2:123456789:checking_workers:XXXXXXXXXXXXXXXXXX",
        "protocol": "lambda",
        "raw_message_delivery": false,
        "topic_arn": "arn:aws:sns:eu-west-2:123456789:checking_workers"
      },
      "private": "auisdgf567asrd6asgd7at8f"
    }
  ]
}
```
I've tried adding 
```
  endpoint_auto_confirms          = null
  confirmation_timeout_in_minutes = null
```
to resource, or omitting this attributes completely but it always shows 
```
# module.testinf.aws_sns_topic_subscription.checking_workers will be updated in-place
~ resource "aws_sns_topic_subscription" "workersCheck_lambda" {
      arn                             = "arn:aws:sns:eu-west-2:123456789:checking_workers:XXXXXXXXXXXXXXXXXX"
    + confirmation_timeout_in_minutes = 1
      endpoint                        = "arn:aws:lambda:eu-west-2:123456789:function:checking_workers"
    + endpoint_auto_confirms          = false
      id                              = "arn:aws:sns:eu-west-2:123456789:checking_workers:XXXXXXXXXXXXXXXXXX"
      protocol                        = "lambda"
      raw_message_delivery            = false
      topic_arn                       = "arn:aws:sns:eu-west-2:123456789:checking_workers"
  }
```

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
