### ISSUE TITLE
BUILDING.md doesn't describe how to build the master

### ISSUE THREAD

**Issue by cpesch** [hashicorp/terraform#25217]
For https://github.com/hashicorp/terraform/issues/25172 I was asked to build the master. The following steps led me to a binary

- Update go-lang to 1.14
- Ignore the `make test` stuff from BUILDING.md
- go get
- go build doesn't work: go build: build output "terraform" already exists and is a directory
- go build -o tfmaster

Please include some of the steps to BUILDING.md

**Comment by bensymonds** [comment]
@cpesch I just ran into this myself. I noticed from the `Dockerfile` that this works:

```
TF_DEV=true TF_RELEASE=1 scripts/build.sh
```

I also tried building the docker image but that had a different problem (which I guess should go in a separate issue):

```
Step 8/10 : RUN /bin/bash scripts/build.sh
 ---> Running in e8604f2810cd
==> Removing old directory...
==> Installing gox...
go: downloading github.com/mitchellh/gox v1.0.1
go: github.com/mitchellh/gox upgrade => v1.0.1
go: downloading github.com/mitchellh/iochan v1.0.0
go: downloading github.com/hashicorp/go-version v1.2.0
go: github.com/hashicorp/go-version upgrade => v1.2.0
==> Building...
error reading Go version: exit status 1
Stderr: go: inconsistent vendoring in /go/src/github.com/hashicorp/terraform:
	github.com/mitchellh/gox@v1.0.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory

==> Results:
total 0
```

**Comment by alisdair** [comment]
To build for local development/testing, please follow [these instructions in CONTRIBUTING.md](https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md#terraform-clicore-development-environment). It ought to be as simple as:

```
cd terraform
go install
```

The BUILDING.md documentation is definitely out of date and we need to decide what to do with that file.
