### ISSUE TITLE
Insufficient privileges to create a service principle via Azure DevOps

### ISSUE THREAD

**Issue by johnlace1986** [hashicorp/terraform#25229]
We are trying to create a service principle for an app registration but we keep getting a 403 back telling us we have "Insufficient privileges to complete the operation." (graphrbac.ServicePrincipalsClient#Create).

The terraform is being run via an Azure DevOps pipeline running under a service principle that is a member of the Cloud application administrator and User administrator roles which should satisfy the requirement in the documentation that the service principle must have permissions to both Read and write all applications and Sign in and read user profile within the Windows Azure Active Directory API.

When running the terraform locally we have also seen a different error: "When using this permission, the backing application of the service principal being created
must in the local tenant". However, this is also confusing because we are not trying to create the application in a different tenant (we only have 1 tenant).

### Terraform Version
```
12
```

### Terraform Configuration Files
```hcl
data "azuread_client_config" "current" {
}

resource "azuread_application" "this" {
  name = var.resource_name_prefix
  type = "native"
  owners = [data.azuread_client_config.current.object_id]
}

resource "azuread_service_principal" "this" {
  application_id = azuread_application.this.application_id
}
```

### Expected Behavior
The service principle is created.

### Actual Behavior
A 403 response is returned:

> Error: Error creating Service Principal for application  "...": graphrbac.ServicePrincipalsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"Authorization_RequestDenied","date":"2020-06-11T10:56:08","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"c8cbbe11-63e9-47ac-bb89-24c403a10e8e"}}]

**Comment by jbardin** [comment]
Hi @johnlace1986!

This doesn't look like an issue with terraform itself. If you feel this is a provider issue, you can file it in the [`azuread`](https://github.com/terraform-providers/terraform-provider-azuread) provider repo. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
