### ISSUE TITLE
Include attributes on all resources

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/terraform#2524]
In order to avoid confusion with other people who may be working on our cloud environment, it would be useful to be able to define attributes (tags, specifically) that should be included on all resources (or all resources of a given type), e.g something like

```
variable default_tags {
  tags {
    CreatedBy = "This resource was generated by Terraform (http://terraform.io) and is managed programmatically.  Do not make changes directly to this resource.  Instead contact Leopold McDevops in the operations department."
  }
}
```

Then do something like:
```
resource "aws_instance "some_server" {
  ...
  @include var.default_tags # the similarity to SASS' syntax is intentional
  tags {
    SomeTagSpecificToThisResource = "some value"
  }
}
```

so the result would be equivalent to:
```
resource "aws_instance "some_server" {
  ...
  tags {
    SomeTagSpecificToThisResource = "some value"
    CreatedBy = "This resource was generated by Terraform (http://terraform.io) and is managed programmatically.  Do not make changes directly to this resource.  Instead contact Leopold McDevops in the operations department."
  }
}
```

If this functionality already exists, I must have missed it in the docs and would gladly do a PR to provide a sample use case/code.

**Comment by mitchellh** [comment]
I'm sorry for my laziness in finding the other issue, but there is a very old enhancement tagged issue tracking something around the lines of "reusable components" within Terraform configs. I would consider this a dup of that.
