### ISSUE TITLE
Not implementing update in a provider causes a hard crash

### ISSUE THREAD

**Issue by spkane** [hashicorp/terraform#25241]
While developing a new terraform provider for a class, and I noticed that when the provider has not yet implemented delete or update in the provider, terraform will give a nice clean error message during a plan, but when create is not implemented, the provider will build fine and plan fine, but terraform will crash hard during an apply. The underlying issue is obviously easy to fix, but this seems like something that should be handled, so that the failure mode is better and it provides better feedback.

```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource todo: No Update defined, must set ForceNew on: []string{"description", "completed"}
```

and

```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource todo: Delete must be implemented
```

versus

```
Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-06-14T09:41:40.382-0700 [DEBUG] plugin.terraform-provider-todo: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1995230]
...
```

### Terraform Version

```
v0.12.24
```

### Terraform Configuration Files

```hcl
provider "todo" {
  host = "127.0.0.1"
  port = "8080"
  apipath = "/"
  schema = "http"
}

resource "todo" "test1" {
  count = 5
  description = "${count.index}-1 ${var.purpose} todo"
  completed = false
}
```

### Debug Output

https://gist.github.com/spkane/04a92ce02f95506798d06a52942b331f#file-trace-output-txt

### Crash Output

https://gist.github.com/spkane/04a92ce02f95506798d06a52942b331f#file-crash-log

### Expected Behavior

A nice error should have been generated during the plan or apply that simply said.

```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource todo: Create must be implemented
```

### Actual Behavior

There was no error during a plan and when the apply step was approved, terraform crashed hard.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

The big thing here is that I was intentionally writing the code in section as a teaching mechanism, and although not implementing update or delete seemed to caught fine (I can not recall if I tested read), not implementing create is not caught and causes a hard crash.

**Comment by jbardin** [comment]
Hi @spkane 

From the stack it appears this error is coming from the `Create` function, rather than `Update`. If that function is missing, or the resource type entirely, I'm not sure how it missed validation, but it's possible that the code here is no longer working as intended. The packages being import by this provider has been moved to the `github.com/hashicorp/terraform-plugin-sdk` repository, which is required for use with terraform >= 0.12. 

First I would try updating the code to work with the current `terrafrom-plugin-sdk` packages. If you still encounter a problem, you can file issues in the https://github.com/hashicorp/terraform-plugin-sdk repository. 

Thanks
