### ISSUE TITLE
Import state throws exception with modules in 0.13.0 beta 1, but works with 0.12.6

### ISSUE THREAD

**Issue by WillooWisp** [hashicorp/terraform#25256]
### Terraform Version
```
0.13.0 beta1
azurerm: 2.14.0
```

### Terraform Configuration Files
```hcl
provider "azurerm" {
  features {}

  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  client_id       = var.client_id
  client_secret   = var.client_secret
}

locals {
  resource_group_name         = "${var.resource_group_name != "" ? var.resource_group_name : var.resource_prefix}"
}

module "resource_group" {
  source               = "./modules/resource-group"
  name                 = local.resource_group_name
  location             = var.location
}

# main.tf for resource-group module
resource "azurerm_resource_group" "rg" {
  name     = var.name
  location = var.location
}
```

### Debug Output
https://gist.github.com/WillooWisp/bf986bcda87b3e2f20ff2655a5e952be

### Crash Output
https://gist.github.com/WillooWisp/bf986bcda87b3e2f20ff2655a5e952be

### Expected Behavior
As of in 0.12.6 the import is successful.

### Actual Behavior
It crashes in 0.13.0 beta1 using modules, but flattening out the hierarchy, referencing the resource directly from main file works. So import with modules, even the most simple ones, does not seem to work in 0.13.0 beta1.

### Steps to Reproduce
1. `terraform init`
2. `terraform import`

### Additional Context
Using the docker container with volume map for the configuration on host, to execute the commands within.

**Comment by jbardin** [comment]
Hi @WillooWisp,

Thanks for reporting this. We have this issue recorded in #25192
