### ISSUE TITLE
null resources depends_on doesn't work on replacement 

### ISSUE THREAD

**Issue by Dineshk77** [hashicorp/terraform#25269]
Hi,
  I am having issues with null provision depend_on strategies. I am trying to recreate the null provision resource if any changes happens to template file that's used during the provision. The resources in which the template file changed performs the force replacement correctly. However the dependent resources are not recreated.

### Terraform Version
0.12.26

### Terraform Configuration Files

- resource  1:
```
data "template_file" "disk_tmp_file" {
    count       =   var.node_count
    template    =   file(var.script_source_tpl)
    vars = {
        disk                =   var.disk
    }
}

resource "null_resource" "first_resource" {
    count       =   var.node_count
    triggers    =   {
        private_ip  =   element(var.private_ip,count.index)
        data        =   element(data.template_file.disk_tmp_file.*.rendered,count.index)
    }
    connection {
        host            =   element(var.private_ip,count.index)
        type            =   var.login_type
        user            =   var.user_name
        password        =   var.instance_password
        port            =   var.port
    }
    provisioner "file" {
        content     =   element(data.template_file.disk_tmp_file.*.rendered,count.index)
        destination =   var.script_destination
    }
}

```
- resource 2:

```
resource "null_resource" "second_resource" {
    depends_on  =   [var.md_depends_on]
}

```
- module 1:

```
module "first_module" {
    source     = ${resource1}
    script_source_tpl               =   "../../scripts/${var.platform}/diskPart.tpl"
}
```
- module 2: 

```
module "second_module" {
    source     = ${resource2}
    md_depends_on                       =   [module.first_module]
}
```
- md_depends_on  var:

```
variable "md_depends_on" {
    type    =   any
    default =   null
}
```

### Expected Behavior
On template change - Should recreate both the resources - resource 1 and resource 2

### Actual Behavior
On template change -  Updates only the resource 1

### Additional Context
Dependency works perfectly if I create or destroy resources. The problem is only if the template file changes and triggers tries to update the resource.

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by Dineshk77** [comment]
@jbardin I have created a topic in forum - https://discuss.hashicorp.com/t/null-resources-depends-on-doesnt-work-on-replacement/10109. However I still feel its a bug in terraform as the depends_on attribute in resource doesn't work as expected.
