### ISSUE TITLE
terraform init crashes on provider install - 0.13-beta1

### ISSUE THREAD

**Issue by kevinmarx** [hashicorp/terraform#25270]
### Terraform Version

```
0.13-beta1
...
```

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    storage_account_name = "..."
    container_name = "..."
    key = "....tfstate"
  }
}

provider "azurerm" {
  version = "~> 2.10"
  features {}
}

provider "azuread" {}
provider "random" {}
```

### Crash Output

https://gist.github.com/kevinmarx/f671c9e11edd45f8e11662094d5d3bd8

### Actual Behavior

terraform init appears to be crashing on the circleci provider, which we aren't using.
### Steps to Reproduce

1. `terraform init`

**Comment by jbardin** [comment]
Hi @kevinmarx, thanks for reporting this.

The partial configuration you've posted here isn't going to be able to cause the crash shown, so I have a feeling it's from an included module which isn't shown here.

Could you try creating a standalone reproduction of the issue?

Thanks!

**Comment by kevinmarx** [comment]
I was able to track down the issue, it was my bad. I had a typo in a data source within the module.
