### ISSUE TITLE
`-version` Flag Not Accepted In v0.13.0-beta2

### ISSUE THREAD

**Issue by jeffwecan** [hashicorp/terraform#25276]
### Terraform Version

```
Terraform v0.13.0-beta2
```

### Terraform Configuration Files

N/A

### Debug Output

https://gist.github.com/jeffwecan/6d727b63fc16de9dbdf5dac30f7a71f4

### Crash Output

N/A

### Expected Behavior

`terraform -version` would ideally be accepted (and output the equivalent of `terraform version`) _or_ its removal would be called out in a changelog entry.
### Actual Behavior

`terraform -version` returns:

```
Error parsing command-line flags: flag provided but not defined: -version
```

### Steps to Reproduce

Using v0.13.0-beta2:

1. `terraform -version`
2. 💥 

### Additional Context

While not directly related, I'll call out that the only reason I initially noticed the change (aside from `-version` being my go-to default for some reason) is that an older version of the 3rd-party tfenv tool seemed to be using `-version` as opposed to `version`.

Also fun to observe that this repository's bug report issue template calls out using `terraform -v` :P 

> Run `terraform -v` to show the version, and paste the result between the ``` marks below.

**Comment by mikl** [comment]
This problem has also made it into the official Docker image, as seen here:

<img width="670" alt="Screenshot 2020-06-18 at 13 19 41@2x" src="https://user-images.githubusercontent.com/10263/85014356-65beb900-b166-11ea-8751-3d11aa9963f8.png">

**Comment by quentin9696** [comment]
Same issue with terraform 0.13-beta2 amd64

**Comment by jbergknoff-rival** [comment]
:+1: I encountered this because Terragrunt invokes `terraform --version`.
