### ISSUE TITLE
0.13.0 Break Import with Missing Config

### ISSUE THREAD

**Issue by juliosueiras** [hashicorp/terraform#25294]
### Terraform Version

```
Terraform v0.13.0-beta2
+ provider registry.terraform.io/hashicorp/azurerm v2.14.0
+ provider registry.terraform.io/hashicorp/github v2.8.1
```

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

provider "github" {
}
```

### Debug Output

https://gist.github.com/juliosueiras/b3e4c603b8b6b2dbdcbbc5a029e3a03d

### Expected Behavior
Import resource successfully 

### Actual Behavior
> Error: Resource github_repository.terraform not found in the configuration.

### Steps to Reproduce
1. terraform import -allow-missing-config github_repository.terraform terraform

**Comment by alisdair** [comment]
Thanks for reporting this! The issue has been fixed in #25352 which will be part of the next 0.13.0 prerelease.
