### ISSUE TITLE
terraform --version variants break in 0.13.0-beta2

### ISSUE THREAD

**Issue by itmustbejj** [hashicorp/terraform#25301]
### Terraform Version

```
Terraform v0.13.0-beta2
```

### Expected Behavior

`terraform --version` and other variants like `-v` and `-version` continue to work
### Actual Behavior

Only `terraform version` reports the version.

### Steps to Reproduce

```
➜  /tmp terraform version
Terraform v0.13.0-beta1
➜  /tmp terraform -version
Terraform v0.13.0-beta1
➜  /tmp terraform --version
Terraform v0.13.0-beta1
➜  /tmp terraform -v       
Terraform v0.13.0-beta1
➜  /tmp tfenv use 0.13.0-beta2
Switching default version to v0.13.0-beta2
Error parsing command-line flags: flag provided but not defined: -version

'terraform --version' failed. Something is seriously wrong
➜  /tmp terraform version
Terraform v0.13.0-beta2
➜  /tmp terraform -version
Error parsing command-line flags: flag provided but not defined: -version

➜  /tmp terraform --version
Error parsing command-line flags: flag provided but not defined: -version

➜  /tmp terraform -v       
Error parsing command-line flags: flag provided but not defined: -v
```
### Additional Context

This causes an error in tfenv (but still works), and breaks terragrunt.
### References

[terragrunt using terraform --version](https://github.com/gruntwork-io/terragrunt/blob/bfd8a233c41085c4fd378e7deb35cc59c48834de/cli/version_check.go#L25)
[tfenv using terraform --version](https://github.com/tfutils/tfenv/search?q=--version&unscoped_q=--version)

**Comment by itmustbejj** [comment]
Looks like https://github.com/hashicorp/terraform/commit/163c943e9bd6739730f4e7fd02d7e4dc5d60fd4c addressed this yesterday :)

**Comment by apparentlymart** [comment]
Hi @itmustbejj! Thanks for reporting this.

Indeed, it looks like #25276 reported this first, so we got a bit of a head start! Since this was already addressed, I'm going to close it. Thanks again for reporting it.
