### ISSUE TITLE
v0.13.0-beta releases break --version/-v flag

### ISSUE THREAD

**Issue by geota** [hashicorp/terraform#25304]
### Terraform Version
v0.13.0-beta2

```
$ terraform version
Terraform v0.13.0-beta2

$ terraform --version
Error parsing command-line flags: flag provided but not defined: -version

$ terraform -v
Error parsing command-line flags: flag provided but not defined: -v
```
### Terraform Configuration Files
n/a

### Debug Output
```
$ terraform version
Terraform v0.13.0-beta2

$ terraform --version
Error parsing command-line flags: flag provided but not defined: -version

$ terraform -v
Error parsing command-line flags: flag provided but not defined: -v
```

### Crash Output
Error parsing command-line flags: flag provided but not defined: -v

### Expected Behavior
The version number should be printed like in 0.12

### Actual Behavior
Terraform errors out.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. Install terraform v0.12.26 release
2. Confirm `terraform -v`, `terraform --version` , and `terraform version` are working as expected
3. Install terraform v0.13.0-beta2 release
4. See `terraform -v` and `terraform --version` are broken
5. See `terraform version` is working as expected

### Additional Context
In terraform 0.13 series, it broke the `--version/-v` flag. Oddly enough `terraform version` works. Even the instructions for this bug report instruct the user to use `terraform -v`.

Looks related to adding -json support to the version argument. Hopefully, this can be implemented in a backward-compatible way. I can take a stab at doing so. 

### References
https://github.com/hashicorp/terraform/pull/25252

**Comment by apparentlymart** [comment]
Hi @geota,

This seems to be describing the same issue as #25276, so I'm going to close this one to consolidate discussion over there. Thanks for reporting it!

**Comment by geota** [comment]
Thanks! No worries, I tried to find an existing issue but searching for `terraform version bug` brought up a ton of issues :)
