### ISSUE TITLE
TypeMap in provider config set up empty in specific scenarios 

### ISSUE THREAD

**Issue by EliiseS** [hashicorp/terraform#25314]
In the [terraform-provider-databricks](https://github.com/databrickslabs/terraform-provider-databricks) we are using TypeMap for the `azure_auth` schema type. `azure_auth` results in being empty when creating a Resource Group and an Azure Databricks workspace with [terraform-provider-azurerm](https://github.com/terraform-providers/terraform-provider-azurerm), initializing the databricks provider with the created workspace and creating a secret scope and secret with the databricks provider.

### Terraform Version
```
# tf version
Terraform v0.12.24
+ provider.azurerm v2.15.0
+ provider.databricks v0.2

```

### Terraform Configuration Files

```hcl
variable "client_id" {
  type = string
}
variable "client_secret" {
  type = string
}
variable "tenant_id" {
  type = string
}
variable "subscription_id" {
  type = string
}

provider "azurerm" {
  client_id = var.client_id
  client_secret = var.client_secret
  tenant_id = var.tenant_id
  subscription_id = var.subscription_id
  features {}
}

resource "azurerm_resource_group" "db" {
  name     = "db-labs-resources66"
  location = "centralus"
}

resource "azurerm_databricks_workspace" "demo_test_workspace" {
  location = "centralus"
  name = "terraform-test-ws-6"
  resource_group_name = azurerm_resource_group.db.name
  sku = "premium"
}

provider "databricks" {
  azure_auth = {
    managed_resource_group = azurerm_databricks_workspace.demo_test_workspace.managed_resource_group_name
    azure_region = azurerm_databricks_workspace.demo_test_workspace.location
    workspace_name = azurerm_databricks_workspace.demo_test_workspace.name
    resource_group = azurerm_databricks_workspace.demo_test_workspace.resource_group_name
    client_id = var.client_id
    client_secret = var.client_secret
    tenant_id = var.tenant_id
    subscription_id = var.subscription_id
  }
}

resource "databricks_secret_scope" "my-scope" {
  name = "terraform-demo-scope2"
}

resource "databricks_secret" "test_secret" {
  key = "demo-test-secret-1"
  string_value = "hello world 123"
  scope = databricks_secret_scope.my-scope.name
}
```

### Debug Output
https://gist.github.com/EliiseS/b3607a034f5f48a870b909cdf701784c

### Expected Behavior
```bash
Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
```
### Actual Behavior
```bash
/workspaces/databricks-terraform/examples/simple-azure-tf-deployment

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "azurerm" (hashicorp/azurerm) 2.15.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.azurerm: version = "~> 2.15"
* provider.databricks: version = "~> 0.2"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: failed to get credentials from config file; error msg: Authentication is not configured for provider. Please configure it
through one of the following options:
1. DATABRICKS_HOST + DATABRICKS_TOKEN environment variables.
2. host + token provider arguments.
3. Run `databricks configure --token` that will create /root/.databrickscfg file.

Please check https://docs.databricks.com/dev-tools/cli/index.html#set-up-authentication for details

  on main.tf line 36, in provider "databricks":
  36: provider "databricks" {

```

### Steps to Reproduce
1. Clone https://github.com/lawrencegripper/terraform-provider-databricks/tree/lg/119repo branch
2. Add terraform.tfvars with service principal credential to  `examples/simple-azure-tf-deployment`
3. Execute the `run.sh` in `examples/simple-azure-tf-deployment`
   ```bash
   cd examples/simple-azure-tf-deployment/ && ./run.sh  
   ```

### Additional Context
This issue does not occur when you just create a secret scope without a secret or when you have a pre-existing resource group. (Verification needed)

### Work Around
We've managed to work around this issue by using TypeList instead of TypeMap

### References
- https://github.com/databrickslabs/terraform-provider-databricks/pull/119
- https://github.com/databrickslabs/terraform-provider-databricks/pull/120

@lawrencegripper @stikkireddy @stuartleeks

**Comment by nfx** [comment]
+1

**Comment by jbardin** [comment]
Hi @EliiseS 

From the configuration shown, you appear to be passing configuration to the provider from resources that have not yet been created.

Each of `managed_resource_group`, `azure_region`, `workspace_name`, and `resource_group` are going to be unknown during the plan, and hence unavailable to the provider. If those fields are required to initialize the provider, then you cannot reference resources that have yet to be created.

If the provider _can_ operate without those parameters, but the _entire_ map is unknown during plan, then you may be able to file an issue with the [`terraform-plugin-sdk`](https://github.com/hashicorp/terraform-plugin-sdk/issues), however changes to the legacy SDK are unlikely at this point. and you may need to re-factor the schema to work around the issue for now.
