### ISSUE TITLE
fileexists should not return an error when subject is a directory (should always return boolean)

### ISSUE THREAD

**Issue by barneyparker** [hashicorp/terraform#25316]
### Terraform Version

```
Terraform v0.12.26
```

### Terraform Configuration Files

```hcl
terraform console
> fileexists(".")

>  
Error: Error in function call

  on <console-input> line 1:
  (source code not available)

Call to function "fileexists" failed: . is not a regular file, but
"drwxrwxr-x".
```

### Expected Behavior

```
terraform console
> fileexists(".")
true
```

### Actual Behavior

```
fileexists returns an error
```

### Additional Context

I am trying to determine if the `node_modules` directory exists to determine if `npm install` needs to be performed, e.g.
```
resource "null_resource" "lambda_dependencies" {
  provisioner "local-exec" {
    command = "cd ${path.module}/src && npm install"
  }

  triggers = {
    index = "${base64sha256(file("${path.module}/src/index.js"))}"
    package = "${base64sha256(file("${path.module}/src/package.json"))}"
    lock = "${base64sha256(file("${path.module}/src/package-lock.json"))}"
    node = fileexists("${path.module}/src/node_modules")
  }
}
```

There doesn't appear to be a useful case where you would want to error on a file being a directory (that I can think of) but in this case there also doesn't appear to be any other native way to discover if a directory resource exists (no `direxists` function for example)

### References

Identical to issue #22260 but with a different use case

**Comment by GergelyKalmar** [comment]
I think that the suggestion in https://github.com/hashicorp/terraform/issues/22260 to introduce a new `direxists` function would be great – currently there seems to be no way in Terraform to check if a folder exists.

**Comment by willemm** [comment]
Indeed, even `try(fileexists("directory/file.txt"), false)` errors out when the directory does not exist.

And also `try(file("directory/file.txt"), "")` gives an error instead of returning an empty string if that directory does not exist.

**Comment by austinvalle** [comment]
Hey everyone 👋🏻 ,

The `hashicorp/local` provider has just released a new [`direxists` ](https://registry.terraform.io/providers/hashicorp/local/latest/docs/functions/direxists) function in `v2.5`, which should provide what you're looking for here.

You can test this out now with Terraform [`v1.8.0-beta1`](https://github.com/hashicorp/terraform/releases/tag/v1.8.0-beta1) or wait for the upcoming `v1.8.0` release.

```terraform
# Configuration using provider functions must include required_providers configuration.
terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "2.5.1"
    }
  }
  # Provider functions require Terraform 1.8 and later.
  required_version = ">= 1.8.0"
}

output "exists" {
  value = provider::local::direxists("${path.module}/example-directory")
}

output "does_not_exist" {
  value = provider::local::direxists("${path.module}/fake-directory")
}
```

```bash
 $ tree          
.
├── example-directory
└── main.tf

2 directories, 1 file

 $ terraform plan

Changes to Outputs:
  + does_not_exist = false
  + exists         = true

```

It's designed similar to `filexists` for directories, so if you try to use it on a file it'll return an error.

If you run into any problems testing out the new function, please create an issue over in the [`local` provider issue tracker](https://github.com/hashicorp/terraform-provider-local/issues ), thanks!

**Comment by crw** [comment]
A function such as `fileexists` will continue to be supported for reasons of 1.x compatibility. The path for new functions to be added to core Terraform will be through providers. New functions that are proven out through a provider function may in rare cases be brought into terraform as a built-in function, but I would not expect that to happen frequently.

**Comment by crw** [comment]
Yes, go ahead an open a new issue. We can use it to both nudge this idea in the future and gather support for the request (move `direxists` from `local` to a built-in).
