### ISSUE TITLE
Feature Request: GitLab backend state storage provider

### ISSUE THREAD

**Issue by kinghuang** [hashicorp/terraform#25315]
### Current Terraform Version

```
Terraform v0.12.26
```

### Use-cases

GitLab introduced Terraform state storage in 12.10. It provides Terraform state storage associated with each GitLab project, similar to how each project has a container registry for Docker images.

@ash2k proposed a native GitLab backend type in #24439, with an implementation in #24566. The issue and pull request have been closed by @hashibot, without any comments from maintainers.

As both a Hashicorp and GitLab customer, I am interested in having a native GitLab backend in Terraform. It would improve the experience of using GitLab-managed state storage in Terraform projects hosted in GitLab.

### Attempted Solutions

The http backend can be configured for GitLab-managed state storage. However, this provides a rougher user experience than what a native backend could provide.

### Proposal

Review #24439 and #24566. And, either accept or reject them.

### References

* [Infrastructure as code with Terraform and GitLab](https://docs.gitlab.com/ee/user/infrastructure/).
* [GitLab managed terraform state epic](https://gitlab.com/groups/gitlab-org/-/epics/2673).

**Comment by pkolyvas** [comment]
Hi @kinghuang Thanks for submission. Both tickets were closed by @ash2k after I discussed the issues directly with the Gitlab team. 

We've agreed that using the `http` standard backend for remote storage is best way forward until such a time as when state storage backends become plugins, much like providers.

**Comment by ash2k** [comment]
That's right. We'll build a native backend once we have a way to do it independently.
