### ISSUE TITLE
aws_elasticsearch_domain does not allow to configure fine-grained access control

### ISSUE THREAD

**Issue by holisticode** [hashicorp/terraform#25322]
I read https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html and https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/fgac.html#fgac-walkthrough-basic and concluded that for our needs, the AWS ES domain should have fine-grained access control enabled.

But I was not able to enable it by using the terraform resource `aws_elasticsearch_domain` module.

### Terraform Version
```
Terraform v0.12.26
...

### Terraform Configuration Files
```
aws_elasticsearch_domain
...

### Expected Behavior
Ability to configure an AWS Elasticsearch domain with fine-grained access control enabled
### Actual Behavior
Fine-grained access control is disabled. No options in the terraform resource template to enable it.

### Steps to Reproduce
Create an `aws_elasticsearc_domain`

**Comment by holisticode** [comment]
Oh, I guess this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/12054

The question is, what is the status of that feature?

**Comment by pselle** [comment]
Hi @holisticode! As you found, the AWS provider is responsible for this feature/code, not Terraform Core. Additionally, since you're asking a question, you might want to check out the [AWS Provider Discuss forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). Thanks!
