### ISSUE TITLE
Confusing error message: "Bitwise operators are not supported. Did you mean boolean OR ("&&")?"

### ISSUE THREAD

**Issue by gdubya** [hashicorp/terraform#25326]
### Terraform Version
```
Terraform v0.12.26
```

### Expected Behavior
Expected the correct boolean operator in the error message ("AND" instead of "OR")
```
Error: Unsupported operator

  on myapp-web.tf line 10, in resource "kubernetes_deployment" "myapp-web":
  10:     replicas = |

Bitwise operators are not supported. Did you mean boolean AND ("&&")?
```

### Actual Behavior
```
Error: Unsupported operator

  on myapp-web.tf line 10, in resource "kubernetes_deployment" "myapp-web":
  10:     replicas = |

Bitwise operators are not supported. Did you mean boolean OR ("&&")?
```

### Steps to Reproduce
Using kubernetes provider to declare a new deployment. Accidentally typed pipe char ("|") instead of "1" for number of replicas.

**Comment by minamijoyo** [comment]
Hi, Thank you for reporting this!

The issue was reported in upstream (the hcl library), but the fix has not been merged yet.
https://github.com/hashicorp/hcl/issues/376
https://github.com/hashicorp/hcl/pull/380

**Comment by alisdair** [comment]
This has been merged upstream and is waiting for a release.
