### ISSUE TITLE
Dynamically create providers with for each.

### ISSUE THREAD

**Issue by maxcbc** [hashicorp/terraform#25320]
# Dynamically create providers with for each.

_NOTE: I don't think this exist already_

## Current Terraform Version
`0.12.26`

## Use-cases
We use multiple (20+) AWS accounts in our organisation. I'm currently trying to create various roles for our CI to use, which are all duplicated across different combinations of accounts. `for_each` for resources enables me to do this easily (thanks for this) by iterating through a list of providers.

## Proposal
What I'd really like to do is the following (assume for this that aws_account_name matches the profile in my AWS config, though this could easily work with a role for each account).

```
locals {
  providers = [
    "aws_account_one",
    "aws_account_two",
    "aws_account_three"
  ]
}

provider "aws" {
  for_each = toset(local.providers)
  alias = each.key
  profile = each.key
  region = "eu-west-1"
}
```

**Comment by jbardin** [comment]
Closing to track this in #19932
