### ISSUE TITLE
destroy time cycle with a nested provider and output forwarding

### ISSUE THREAD

**Issue by jeremykatz** [hashicorp/terraform#25330]
### Terraform Version

```
terraform-0.13.0-beta2
```

### Terraform Configuration Files

main.tf
```hcl
provider "null" {}

resource "null_resource" "primary" {}

module "mod" {
  source = "./module"
  depends_on = [ null_resource.primary ]
}

output "out" {
  value = module.mod.out
}
```

module/main.tf
```hcl
provider "null" {}

resource "null_resource" "subres" {}

output "out" {
  value = 1
}
```
### Debug Output

https://gist.github.com/jeremykatz/b33d91d2f573c66c52bb93ea615de55f

### Expected Behavior

`terraform destroy` should destroy all resources.
### Actual Behavior

terraform reports an error and doesn't destroy the resources.

The exact text or the error varies from run to run. For example, one run produced:
```
$ terraform destroy -auto-approve
null_resource.primary: Refreshing state... [id=167061396610859690]
module.mod.null_resource.subres: Refreshing state... [id=167061396610859690]

Error: Cycle: module.mod.provider["registry.terraform.io/hashicorp/null"], module.mod.null_resource.subres (destroy), null_resource.primary (destroy), module.mod (expand)
```

Repeating the command again reported:
```
destroy$ terraform destroy -auto-approve
null_resource.primary: Refreshing state... [id=167061396610859690]
module.mod.null_resource.subres: Refreshing state... [id=167061396610859690]

Error: Cycle: null_resource.primary (destroy), module.mod (expand), module.mod.provider["registry.terraform.io/hashicorp/null"], module.mod.null_resource.subres (destroy)
```

A third attempt:
```
$ terraform destroy -auto-approve
null_resource.primary: Refreshing state... [id=167061396610859690]
module.mod.null_resource.subres: Refreshing state... [id=167061396610859690]

Error: Cycle: module.mod.null_resource.subres (destroy), null_resource.primary (destroy), module.mod (expand), module.mod.provider["registry.terraform.io/hashicorp/null"]
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform destroy`

### Additional Context

This doesn't occur if any of the following changes are made:
* module/main.tf doesn't have a nested provider.
* module/main.tf doesn't create a resource
* main.tf doesn't forward the output variable from module/main.tf
* depends_on is not used in the module "mod" block.

**Comment by debovema** [comment]
Thanks for narrowing down this use case I'm experiencing in a much larger project. I did notice that it has something to to with "output forwarding" and nested provider (other issues are open concerning nested providers).

You might be able to perform the destroy in two steps with this workaround:
```
terraform -target module.mod -auto-approve
terraform -auto-approve
```
This workaround shows that this is clearly a bug since the resources are actually destroyable.

**Comment by jeremykatz** [comment]
> Thanks for narrowing down this use case I'm experiencing in a much larger project. I did notice that it has something to to with "output forwarding" and nested provider (other issues are open concerning nested providers).
> 
> You might be able to perform the destroy in two steps with this workaround:
> 
> ```
> terraform -target module.mod -auto-approve
> terraform -auto-approve
> ```

Unfortunately, attempting to use `terraform destroy -target` is how I encountered https://github.com/hashicorp/terraform/issues/25319. `terraform state rm` has worked so far, with the caveat that deallocation needs to be handled outside of terraform. 

Removing nested providers appears to be a more practical solution, as that's necessary for `for_each` or `count` use anyway.

**Comment by debovema** [comment]
@jbardin : based on #25345 resolution, you mean that it is not valid to have a ```provider``` in a module which will be used as a dependency? I'm confused about this behaviour. It seems to me that this limitation implies that the ```depends_on``` will be quite useless.

**Comment by jbardin** [comment]
Hi @debovema,

Specifically, a provider cannot be declared within a module using `depends_on`, which as @jeremykatz pointed out, is also the restriction required for `count` and `for_each`, albeit for slightly different technical reasons.

Providers should not generally be declared within modules,  and `depends_on` for a module should be rarely required. It's unlikely there is a reason to crate a configuration in this manner, but if there is a use case, another solution will have to be devised.
