### ISSUE TITLE
aws_eks_node_group resource not respecting "remote_access" source_security_group_ids list

### ISSUE THREAD

**Issue by mark-bixler** [hashicorp/terraform#25333]
### Terraform Version

```
Terraform v0.12.26
+ provider.archive v1.3.0
+ provider.aws v2.67.0
+ provider.helm v1.2.3
+ provider.kubernetes v1.11.3
+ provider.null v2.1.2
```

### Terraform Configuration Files

```hcl
resource "aws_eks_node_group" "cluster_node_group" {
  cluster_name    = aws_eks_cluster.cluster.id
  node_group_name = "${var.cluster.name}-node-group"
  node_role_arn   = aws_iam_role.eks_node_group_role.arn
  subnet_ids      = data.aws_subnet_ids.private_subnets.ids
  disk_size       = var.disk_size

  scaling_config {
    desired_size = var.cluster.desired_size
    max_size     = var.cluster.node_max_size
    min_size     = var.cluster.node_min_size
  }

  remote_access {
    ec2_ssh_key               = var.cluster.key_pair
    source_security_group_ids = [
      aws_security_group.node_group_sg.id,
      aws_eks_cluster.cluster.vpc_config[0].cluster_security_group_id
      ]
  }

```

### Expected Behavior

Managed Nodes should be created with 2 security groups assigned [node_group_sg (created earlier in the module) & cluster_security_group (group created by eks during the control plane spin up)

```
"SecurityGroups": [
 {
     "GroupName": "eks-cluster-sg-demo-eks-cluster-592393474",
      "GroupId": "sg-090ab5eb109401437"
 },
 {
      "GroupName": "worker_node_group_ssh_sg",
      "GroupId": "sg-032d856469e115492"
 }
```

### Actual Behavior
`aws_security_group.node_group_sg.id` is ignored and new worker nodes are built with a new `eks-remoteAccess-2eb96d45-cf07-0835-022a-fcb721be7dce` auto created security group along side specified cluster_security group. 

```
"SecurityGroups": [
 {
     "GroupName": "eks-cluster-sg-demo-eks-cluster-592393474",
      "GroupId": "sg-090ab5eb109401437"
 },
 {
      "GroupName": "eks-remoteAccess-2eb96d45-cf07-0835-022a-fcb721be7dce",
      "GroupId": "sg-032d856469e115491"
 }
```

### Steps to Reproduce
```
1. terraform init
2. terraform apply
```

### References

Could not find any others reporting this issue. Github search of code shows others doing something similar.

**Comment by apparentlymart** [comment]
Hi @mark-bixler!

This seems like behavior implemented in the AWS provider rather than in Terraform Core, so I don't think it's something we could fix in this repository. If you like, you could report it in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws), if there isn't already an issue in the provider repository covering this behavior.

Thanks!
