### ISSUE TITLE
Proposal to have a JSON array to map converter based on a unique field

### ISSUE THREAD

**Issue by kviktorman** [hashicorp/terraform#25349]
### Current Terraform Version
```
Terraform v0.12.26
```
### Use-cases

Multiple resources (ie:virtual machines) are needed to be created programatically. The configuration of those resources are arriving as a JSON array. There is a unique field for each array element which allows referencing them individually. The use case is to provide a custom JSON array search functionality based on the unique field. So the configuration assignment would be cleaner and easier. 

### Attempted Solutions

So far I have managed to write a module which converts a JSON array to a map. So the elements can be easily referenced for the modules.

```
### JSON array input ###

[
 {"id":"virtual_machine_type1", "setting1"="..."},
 {"id":"virtual_machine_type2", "setting2"="..."}
]

### [parent_module] ###
variable "virtual_machines_settings" {}

module "virtual_machine_type1_module" {
  source                      = "../virtual_machine_type1"
  providers                   = { ... }
  virtual_machine_settings    = module.virtual_machine_converter.object_array_as_map["virtual_machine_type1"]
}

module "virtual_machine_type2_module" {
  source                      = "../virtual_machine_type2"
  providers                   = { ... }
  virtual_machine_settings    = module.virtual_machine_converter.object_array_as_map["virtual_machine_type2"]
}

# import converter module which takes JSON array and returns map
module "virtual_machine_converter" {
  source                = "../virtual_machine_converter_module"
  virtual_machines_settings = var.virtual_machines_settings
}

### [virtual_machine_converter_module sub] ###
### converting the JSON array to map ()  ###

variable "virtual_machines_settings" {}

# returns a map object from an array
output "object_array_as_map" {
  value = { for setting in var.virtual_machines_settings : setting.id => setting }
}
```
### Proposal

To have a function which would do the "object_array_as_map" conversion. 
Something like this:

```
### [inputArray] ###
[
 {"uniqueField":"virtual_machine_type1", "setting1"="..."},
 {"uniqueField":"virtual_machine_type2", "setting2"="..."}
]

### [parent_module] ###
variable "inputArray" {}

module "virtual_machine_type1_module" {
  source                      = "../virtual_machine_type1"
  providers                   = { ... }
  virtual_machine_settings    = array_to_map(inputArray, uniqueField) ["virtual_machine_type1"]
}

module "virtual_machine_type2_module" {
  source                      = "../virtual_machine_type2"
  providers                   = { ... }
  virtual_machine_settings    = array_to_map(inputArray, uniqueField) ["virtual_machine_type2"]
}

```

### References
None

**Comment by apparentlymart** [comment]
Hi @kviktorman! Thanks for making this proposal.

After reviewing the configuration examples you shared in your comment, I see that your attempted solution was to use a `for` expression, like `{ for setting in var.virtual_machines_settings : setting.id => setting }`. That is how I would've solved this problem, too. Did you see an error when you tried that? If so, can you share it so I can understand better what part of that didn't work?

If I'm misunderstanding and you're proposing something else, could you explain what you would expect `array_to_map(var.virtual_machines_settings, "id")` to return, and how that is different than what `{ for setting in var.virtual_machines_settings : setting.id => setting }` returns?

Thanks!

**Comment by kviktorman** [comment]
Hi @apparentlymart,

So far I haven't received any errors using the solution described under the attempted solution. 

However it has a limitation, which is that, in the module I have to hard code the field name. This means that for different resources where the unique field's name might be different than "id" I can't use the same converter module. I did not manage to overcome this limitation.

My proposal is about having a generic Built-in Function instead of a module, which would allow such a conversion just by specifying an array and a unique field name as an input.  

Cheers,
Viktor

**Comment by apparentlymart** [comment]
Hi @kviktorman,

I think what I am not understanding in your proposal is why you need that extra module at all. Couldn't you instead write the `for` expression directly in the calling module? If you expect to use the result multiple times then you can declare a [local value](https://www.terraform.io/docs/configuration/locals.html) to make it reusable elsewhere in the same module:

```hcl
locals {
  settings_map = { for setting in var.virtual_machines_settings : setting.id => setting }
}
```

**Comment by kviktorman** [comment]
Hi @apparentlymart,
sorry for the late reply, I have had a busy week.

I see your point and you are completely right, thanks a lot for taking the time and sharing your point of view, I agree the code would be more complicated using a module for that. I fall into a modularisation trap and couldn't see the forest for the trees.

I think I will close the issue. 

Thanks, 
Viktor
