### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by eakman-nomad** [hashicorp/terraform#25353]
### Terraform Version

```
Terraform v0.12.19
```

### Terraform Configuration Files

```hcl
...
```

### Actual Behavior

After running queueing a plan in Terraform cloud. We received a `panic: runtime error: invalid memory address or nil pointer dereference` error.

and 
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
### Additional Context

Just prior to queueing the plan we deleted a workspace via UI that was created by a different workspace.

**Comment by alisdair** [comment]
Thanks for reporting the crash. Unfortunately, without the crash log or other means of reproducing the bug, there's not much we can do to help.

Can you redact any sensitive information from the log and upload it here, along with your configuration? Please also describe detailed steps to reproduce the bug.

**Comment by eakman-nomad** [comment]
actually we sought out support elsewhere and managed to find a solution to our problem. Was the issue described [here](https://github.com/terraform-providers/terraform-provider-tfe/issues/149)
