### ISSUE TITLE
Deprecate destroy

### ISSUE THREAD

**Issue by mcandre** [hashicorp/terraform#25359]
apply, with the desired resources removed from the configuration, is a more CI-friendly and intuitive workflow than separate apply, destroy tasks.

**Comment by ajohnston9** [comment]
Destroy still has uses in some workflows. I utilize terraform for infrastructure with very short lifespans, so having to maintain two separate configuration files (one for the actual infrastructure and one that is effectively null) just to provide that same functionality would be a hassle.

**Comment by pkolyvas** [comment]
Hey @mcandre! Thanks for taking the time to submit this. We have no plans to remove the destroy command at the current time. For those that want to destroy infrastructure by removing the resources from their configuration, they can do so today. 

However the ability to destroy resources without needing to "empty" or null out a configuration, is a feature many of us rely on for needs like @ajohnston9's. In my case it's helpful simply while developing configurations. Sometimes our practitioners/customers want to recreate the same resources with a different set of variables - and so being able to do so, both manually and in automation are just a few use cases that make `terraform destroy` a useful command. This list is far from exclusive.

We do appreciate every idea and contribution to Terraform, even if we can't implement them all. My door is always open to talk about Terraform both present and future.
