### ISSUE TITLE
Remote state data source broken on master branch

### ISSUE THREAD

**Issue by jbergknoff-rival** [hashicorp/terraform#25351]
Hi, I'm experimenting with the very latest master branch commit of Terraform ([`3178d7d7acb6609dcbe2fc47f98f1554fd232ff8`](https://github.com/hashicorp/terraform/commit/3178d7d7acb6609dcbe2fc47f98f1554fd232ff8)) to get the various fixes for bugs in 0.13-beta-2.

Terraform fails to read remote state as a data source. When planning:

```
Error: Provider produced invalid object

Provider "terraform.io/builtin/terraform" produced an invalid value for
data.terraform_remote_state.stack: missing required attribute "workspace".

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

The remote state in question is stored in S3, generated by TF 0.12.26.

There appears to have been a regression between [`dc8fd14c1ee9c0f582a8df0a59b27631eff929b0`](https://github.com/hashicorp/terraform/commit/dc8fd14c1ee9c0f582a8df0a59b27631eff929b0) of a few days ago, because remote state was working when I built off of that commit. [This commit](https://github.com/hashicorp/terraform/commit/fb06063b2beb03c1cf13e4b5a944ff9d17fafcd7) ("don't set remote workspace in state") seems related.

**Comment by jbardin** [comment]
Thanks for testing @jbergknoff-rival! There is a PR (#25377) pending that will take care of this, and get master back into a working state. 

Thanks!
