### ISSUE TITLE
0.13-beta2 destroy provisionners should be able to reference variables or workaround the restriction

### ISSUE THREAD

**Issue by mildred** [hashicorp/terraform#25365]
### Terraform Version
```
Terraform v0.13.0-beta2
```

### Terraform Configuration Files

```hcl
variable "unit_name" {}

resource "local_file" "redis_service" {
  filename = "/etc/systemd/system/${var.unit_name}-redis.service"
  content = <<EOF
[Unit]
Description=Just testing

[Service]
ExecStart=/bin/true

EOF

  provisioner "local-exec" {
    command = "systemctl daemon-reload && systemctl disable --now ${var.unit_name}-redis.service"
  }

  provisioner "local-exec" {
    when    = destroy
    command = "systemctl daemon-reload && systemctl enable --now ${var.unit_name}-redis.service"
  }
}
```

### Expected Behavior

The changelog tells about destroy time provisionners not being able to reference resources other than self, but in this case I'm referencing a variable which value is static and constant throughout the terraform run. I would have expected to be able to reference it.

If this is truly impossible, then perhaps the release notes should be augmented to tell that nothing can be referenced, not even variables, from destroy time provisioners.

Then, a workaround to be able to use external data from the destroy time provisioner would be to allow every resource to accept arbitrary metadata, that would be stored to the resource at creation time, then those would be able to be referenced from the provissioner. This could also help reduce code duplication. Example:

```hcl
variable "unit_name" {}

resource "local_file" "redis_service" {
  meta {
    unit_name = "${var.unit_name}-redis.service"
  }

  filename = "/etc/systemd/system/${self.meta.unit_name}"
  content = <<EOF
[Unit]
Description=Just testing

[Service]
ExecStart=/bin/true

EOF

  provisioner "local-exec" {
    command = "systemctl daemon-reload && systemctl disable --now ${self.meta.unit_name}"
  }

  provisioner "local-exec" {
    when    = destroy
    command = "systemctl daemon-reload && systemctl enable --now ${self.meta.unit_name}"
  }
}
```

This would actually solve https://github.com/hashicorp/terraform-provider-null/issues/5 (PR: https://github.com/hashicorp/terraform-provider-null/pull/15)

### Actual Behavior

```
Error: Invalid reference from destroy provisioner

  on .../test.tf line 75, in resource "local_file" "redis_service":
  75:     command = "systemctl daemon-reload && systemctl enable --now ${var.unit_name}-redis.service"

Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.

References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.

```

### References

- https://github.com/hashicorp/terraform/issues/24083
- https://github.com/hashicorp/terraform-provider-null/issues/5
- https://github.com/hashicorp/terraform-provider-null/pull/15

**Comment by jbardin** [comment]
Hi @mildred 

Unfortunately this is not possible, which is why these references are now an error in 0.13.

The release notes do state this change under "BREAKING CHANGES:", and there will be a section devoted to this in the 0.13 upgrade guide.

Since we already have #23679 open for discussion and workarounds, I'm going to close this out as the suggested documentation will be in place.
