### ISSUE TITLE
Failure creating Repo+CI on AZDO

### ISSUE THREAD

**Issue by lfmundim** [hashicorp/terraform#25368]
### Terraform Version

```
Terraform v0.12.26
+ provider.azuredevops v0.0.1
```

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version = ">= 0.0.1"
}

resource "azuredevops_git_repository" "repo" {
  project_id = "some-guid"
  name       = "some-name"
}

resource "azuredevops_build_definition" "build" {
  project_id = "some-guid"
  name       = "some-name - CI"
 
  repository {
    repo_type   = "TfsGit"
    repo_id   = azuredevops_git_repository.repo.id
    branch_name = azuredevops_git_repository.repo.default_branch
    yml_path    = "azure-pipelines.yml"
  }
}
```

### Debug Output

https://gist.github.com/lfmundim/8083ce0abadb4567545e33ace29ba4bf
### Crash Output

https://gist.github.com/lfmundim/7658419c40c4607ae88ff459da79f6c0
### Expected Behavior

New repo and CI should have been created
### Actual Behavior

New repo was created
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Following (partly) [the article](https://cloudblogs.microsoft.com/opensource/2020/06/18/announcing-hashicorp-terraform-azure-devops-provider-release/) that marked the release of v0.0.1 of the AZDO provider, along with the official [reference](https://www.terraform.io/docs/providers/azuredevops/r/build_definition.html). The `.tf` works fine without the `azuredevops_build_definition` section

**Comment by apparentlymart** [comment]
Hi @lfmundim,

This seems to be talking about a problem in the `azuredevops` provider rather than in Terraform Core. This repository is only for Terraform Core, so I'm going to close this. If you like, you could open a similar issue in [the `azuredevops` provider repository](https://github.com/terraform-providers/terraform-provider-azuredevops).
