### ISSUE TITLE
0.13-beta2 in-house providers required by tfstate fails in 0.13

### ISSUE THREAD

**Issue by mildred** [hashicorp/terraform#25374]
### Terraform Version

```
Terraform v0.13.0-beta2
+ provider registry.terraform.io/hashicorp/random v2.2.1
```

### Description of the problem

When using in-house providers (`sys` provider in my example) with terraform 0.12, the provider gets registered in the tfstate. When using terraform 0.13, the hcl files can be updated to refer to the correct provider source ([using the guide](https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/draft-upgrade-guide.md#in-house-providers)), but the tfstate still refers to the legacy provider source.

Given a terraform module which was upgraded to specify a source for the in-house provider `sys`, I get the following error when running terraform init in 0.13

### Actual Behavior

```
+ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed localhost/local/sys v1.0.0
- Using previously-installed hashicorp/random v2.2.1
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed -/random v2.2.1
- Using previously-installed -/template v2.1.2
- Finding latest version of -/sys...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/sys: provider
registry registry.terraform.io does not have a provider named
registry.terraform.io/-/sys

```

### Expected Behavior

Specifying the provider in the terraform files should be enough for terraform to understand the provider source in 0.12

### Steps to Reproduce

I guess applying a module with in-house provider in 0.12, configure the module to work with 0.13 and run terraform init with 0.13

### Additional Context

```
+ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/random]
├── provider[localhost/local/sys]
└── module.mailu
    ├── provider[localhost/local/sys]
    ├── provider[registry.terraform.io/hashicorp/random]
    ├── provider[registry.terraform.io/hashicorp/template]
    ├── module.mailu_addr
    │   ├── provider[registry.terraform.io/hashicorp/random]
    │   └── provider[localhost/local/sys]
    ├── module.nginx_proxy_service
    │   ├── provider[localhost/local/sys]
    │   └── provider[registry.terraform.io/hashicorp/template]
    ├── module.redis_proxy_service
    │   ├── provider[localhost/local/sys]
    │   └── provider[registry.terraform.io/hashicorp/template]
    └── module.admin_proxy_service
        ├── provider[localhost/local/sys]
        └── provider[registry.terraform.io/hashicorp/template]

Providers required by state:

    provider[registry.terraform.io/-/sys]

    provider[registry.terraform.io/-/random]

    provider[registry.terraform.io/-/template]

```

### References

- follows #25367 with my experiments with 0.13

**Comment by apparentlymart** [comment]
Hi @mildred! Thanks for reporting this.

We're currently iterating on that upgrade guide over in #25113, and there's some extra content in the latest version about the situation you're describing; look for the additional paragraphs at the end of the "In-house Providers" section.

With that said, because this requires changes to state I would not suggest following those instructions unless you are working in a temporary testing environment, because once the state is upgrade to use the new syntax it will no longer be readable by Terraform 0.12.

**Comment by apparentlymart** [comment]
Hi again @mildred!

I just noticed that the existing issue #25346 is reporting the same problem, so I'm going to close this issue to consolidate the discussion over there. Thanks again!
