### ISSUE TITLE
Apply on aws_db_instance tries to refresh parameter group

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#2537]
Terraform v0.6.0-dev (aea85e40274d17732f15193c00061a2a686c5ae2)

I've created an RDS parameter group and applied successfully, however, in a second plan/apply I am trying to use this new parameter group with the aws_db_instance, but it's failing with an error in the naming of the parameter group (the parameter group has not been modified).

     terraform apply -var-file=variables/dev.tf  -target=module.bq-rds.aws_db_parameter_group.main-rds-parameters
        module.bq-rds.aws_db_parameter_group.main-rds-parameters: Creating...
          description:                      "" => "dev RDS default parameter group"
          family:                           "" => "mysql5.6"
          name:                             "" => "dev-mysql-parameters"
          parameter.#:                      "" => "1"
          parameter.973660974.apply_method: "" => ""
          parameter.973660974.name:         "" => "log_bin_trust_function_creators"
          parameter.973660974.value:        "" => "true"
        module.bq-rds.aws_db_parameter_group.main-rds-parameters: Creation complete

--

       terraform apply -var-file=variables/dev.tf  -target=module.bq-rds.aws_db_parameter_group.main-rds-parameters
        module.bq-rds.aws_db_parameter_group.main-rds-parameters: Refreshing state... (ID: dev-mysql-parameters)
        module.bq-rds.aws_db_parameter_group.main-rds-parameters: Modifying...
          parameter.950177639.apply_method: "" => ""
          parameter.950177639.name:         "log_bin_trust_function_creators" => ""
          parameter.950177639.value:        "1" => ""
          parameter.973660974.apply_method: "" => ""
          parameter.973660974.name:         "" => "log_bin_trust_function_creators"
          parameter.973660974.value:        "" => "true"
        module.bq-rds.aws_db_parameter_group.main-rds-parameters: Error: 1 error(s) occurred:

        * Error modifying DB Parameter Group: InvalidParameterValue: Parameter name cannot be empty
            status code: 400, request id: [4f50692e-1dc9-11e5-9e23-2939e5063eb6]
        Error applying plan:

        1 error(s) occurred:

        * Error modifying DB Parameter Group: InvalidParameterValue: Parameter name cannot be empty
            status code: 400, request id: [4f50692e-1dc9-11e5-9e23-2939e5063eb6]

--

     resource "aws_db_parameter_group" "main-rds-parameters" {
            
            name        = "dev-mysql-parameters"
            family      = "mysql5.6"
            description = "dev RDS default parameter group"

            parameter {
              name          = "log_bin_trust_function_creators"
              value         = "true"
              apply_method  = "immediate"
            }

            # parameter {
            #   name = "character_set_client"
            #   value = "utf8"
            # }
        }

**Comment by mitchellh** [comment]
Reproduced, taking a look.

**Comment by mitchellh** [comment]
It looks like AWS on the other side is changing the value from "true" to "1". This isn't Terraform itself modifying the value. Just change "true" with "1" and this problem goes away. Updating the documentation to note this, since I don't think it really should be Terraform's job to do this since we're treating that value opaquely.
