### ISSUE TITLE
destroy -target=module.somemodule.resource.name destroys the entire module

### ISSUE THREAD

**Issue by mikeyhill** [hashicorp/terraform#2538]
Terraform v0.6.0-dev (aea85e40274d17732f15193c00061a2a686c5ae2)

    terraform destroy -var-file=variables/dev.tf  -target=module.bq-varnish.aws_iam_server_certificate.varnish-iam-certs

Destroys all of module.bq-varnish rather unexpectedly - From the behavior of plan/apply I would expect destroy to work the same with a specific resource.

--

     terraform destroy -var-file=variables/dev.tf  -target=module.bq-varnish.aws_iam_server_certificate.varnish-iam-certs
		Do you really want to destroy?
		  Terraform will delete all your managed infrastructure.
		  There is no undo. Only 'yes' will be accepted to confirm.

		  Enter a value: yes

		module.bq-varnish.aws_elb.varnish-elb: Refreshing state... (ID: dev-varnish-elb)
		module.bq-varnish.aws_lb_cookie_stickiness_policy.varnish-sticky-cookie: Refreshing state... (ID: dev-varnish-elb:80:dev-varnish-sticky-cookie)
		module.bq-varnish.template_file.varnish-cloud-init: Refreshing state... (ID: b5fe0014c71bbb13fc8aa560d86166dd86c89faae0cf0ce78ea335bddfc4ffdb)
		module.bq-varnish.aws_launch_configuration.varnish-launch-config: Refreshing state... (ID: dev-varnish-launch-config)
		module.bq-varnish.aws_autoscaling_group.varnish-autoscaling-group: Refreshing state... (ID: dev-varnish-autoscaling-group)
		aws_lb_cookie_stickiness_policy.varnish-sticky-cookie: Destroying...
		aws_autoscaling_group.varnish-autoscaling-group: Destroying...
		aws_lb_cookie_stickiness_policy.varnish-sticky-cookie: Destruction complete
		aws_autoscaling_group.varnish-autoscaling-group: Destruction complete
		aws_launch_configuration.varnish-launch-config: Destroying...
		aws_launch_configuration.varnish-launch-config: Destruction complete
		template_file.varnish-cloud-init: Destroying...
		template_file.varnish-cloud-init: Destruction complete
		aws_elb.varnish-elb: Destroying...
		aws_elb.varnish-elb: Destruction complete

**Comment by josephholsten** [comment]
@mikeyhill was the resource deleted from the config? this sounds similar to #4515

**Comment by mikeyhill** [comment]
@josephholsten - it's been a while but yes, I do recall it removing it from the config.
