### ISSUE TITLE
"Unsupported attribute" / "empty tuple" when removing count from reference

### ISSUE THREAD

**Issue by ahilsend** [hashicorp/terraform#25389]
Changing a resource with a count to not have a count fails to reference it.

### Terraform Version

```
> terraform version
Terraform v0.12.26
+ provider.random v2.2.1
+ provider.template v2.1.2
```

This works fine in 0.12.25, but also fails with 0.12.27

### Terraform Configuration Files

Initial config:
```hcl
terraform {
  backend "local" {}
}

provider "random" {
  version = "= 2.2.1"
}

provider "template" {
  version = "2.1.2"
}

resource "random_id" "random" {
  count       = 1
  byte_length = 10
}

data "template_file" "document" {
  template = "{id}"
  vars = {
    id = random_id.random[0].hex
  }
}
```

After applying it, remove the count for `random_id.random`:

```hcl
terraform {
  backend "local" {}
}

provider "random" {
  version = "= 2.2.1"
}

provider "template" {
  version = "2.1.2"
}

resource "random_id" "random" {
  byte_length = 10
}

data "template_file" "document" {
  template = "{id}"
  vars = {
    id = random_id.random.hex
  }
}
```

With this change, planning fails

### Debug Output

https://gist.github.com/ahilsend/4b35e938fd90652099bcbdc6e1cd7b10

### Expected Behavior

Plan should have no changes and not fail.

### Actual Behavior

Plan fails with 

```bash
Error: Unsupported attribute

  on main.tf line 20, in data "template_file" "document":
  20:     id = random_id.random.hex
    |----------------
    | random_id.random is empty tuple

This value does not have any attributes.
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
3. remove count from resource
4. `terraform plan`

### References

- #23676 looks related

**Comment by jbardin** [comment]
Hi @ahilsend 
Thanks for reporting this. I can confirm this is fixed in master, and will be included in the next major release.

Thanks!

**Comment by TomTucka** [comment]
@jbardin I'm using `λ terraform version Terraform v0.12.28` and I'm still experiencing this issue, anything I can do to help get this fixed?

**Comment by evanstoddard23** [comment]
> Hi @ahilsend
> Thanks for reporting this. I can confirm this is fixed in master, and will be included in the next major release.
> 
> Thanks!

@jbardin As in `0.12.29` or `0.13`?

**Comment by mpescetto** [comment]
@jbardin Yeah, I compiled terrafrom from the `v0.12` branch and using this version:
```bash
Terraform v0.12.29-dev
```

But I'm still seeing this error:
```bash
Error: Unsupported attribute

  on .terraform/modules/fargate_web_service.web_service/locals.tf line 19, in locals:
  19:   unique_resource_name = random_id.r.hex
    |----------------
    | random_id.r is tuple with 2 elements

This value does not have any attributes.

Releasing state lock. This may take a few moments...
[terragrunt] 2020/07/15 13:39:19 Hit multiple errors:
exit status 1
```

**Comment by mpescetto** [comment]
FYI, I was able to reproduce this with random provider `2.3.0` and terraform version `0.12.24` and came up with a crappy way to return the state file to normal:

1. Create the normal objects and apply:
```hcl
resource "random_id" "r" {
  byte_length = 2
  prefix      = "foobar-"
}

output "test_random_id" {
  value = random_id.r.hex
}
```
Output:
```bash
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

test_random_id = foobar-82e1
```

2. Add a count and apply:
```hcl
resource "random_id" "r" {
  count       = 2
  byte_length = 2
  prefix      = "foobar-"
}

output "test_random_id" {
  value = random_id.r
}
```
Output:
```bash
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

test_random_id = [
  {
    "b64" = "foobar-guE"
    "b64_std" = "foobar-guE="
    "b64_url" = "foobar-guE"
    "byte_length" = 2
    "dec" = "foobar-33505"
    "hex" = "foobar-82e1"
    "id" = "guE"
    "prefix" = "foobar-"
  },
  {
    "b64" = "foobar-07o"
    "b64_std" = "foobar-07o="
    "b64_url" = "foobar-07o"
    "byte_length" = 2
    "dec" = "foobar-54202"
    "hex" = "foobar-d3ba"
    "id" = "07o"
    "prefix" = "foobar-"
  },
]
```

3. Remove the count and apply, but leave off the `.hex` so it doesn't error. Adding the `.hex` will reproduce the error. In the output you can see it's an empty list still, but it _should_ be a map: 
```hcl
resource "random_id" "r" {
  byte_length = 2
  prefix      = "foobar-"
}

output "test_random_id" {
  value = random_id.r
}
```
Output:
```bash
Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

Outputs:

test_random_id = []
```

4. Don't add `.hex` and re-run the apply:
Outputs:
```bash
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

test_random_id = {
  "b64" = "foobar-guE"
  "b64_std" = "foobar-guE="
  "b64_url" = "foobar-guE"
  "byte_length" = 2
  "dec" = "foobar-33505"
  "hex" = "foobar-82e1"
  "id" = "guE"
  "prefix" = "foobar-"
}
```

5. THEN you can finally add reference the attribute(s) needed and re-apply:
```hcl
resource "random_id" "r" {
  byte_length = 2
  prefix      = "foobar-"
}

output "test_random_id" {
  value = random_id.r.hex
}
```
Outputs:
```bash
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

test_random_id = foobar-82e1
```

Overall this is a super annoying and detrimental bug.
