### ISSUE TITLE
Issue with aws_iam_server_certificate resource via the AWS Provider

### ISSUE THREAD

**Issue by bscott** [hashicorp/terraform#2539]
When trying to have this resource upload a  cert based in a file, I get the following error:

```
Errors:

  * aws_iam_server_certificate.test_ssl: Provider doesn't support resource: aws_iam_server_certificate
```

I'm using the doc here as a example TF file:

```
resource "aws_iam_server_certificate" "test" {
  name = "some_test_cert"
  certificate_body = "${file("test.pem")}"
}

resource "aws_elb" "ourapp" {
  name = "terraform-asg-deployment-example"
  availability_zones = ["us-west-2a"]
  cross_zone_load_balancing = true

  listener {
    instance_port = 8000
    instance_protocol = "http"
    lb_port = 443
    lb_protocol = "https"
    ssl_certificate_id = "${aws_iam_server_certificate.test_cert.arn}"
  }
}
```

https://www.terraform.io/docs/providers/aws/r/iam_server_certificate.html

**Comment by mitchellh** [comment]
I can't reproduce this. Are you using the latest version of Terraform? If so, maybe we accidentally deployed the docs for master? Either way, we'll be releasing a new version soon, so this error will disappear. :)

**Comment by bscott** [comment]
@mitchellh Thanks, yes I'm using latest version.

**Comment by bscott** [comment]
@mitchellh I didn't this this resource announced in the changelog, did it make it in 0.6.0?

https://github.com/hashicorp/terraform/blob/v0.6.0/CHANGELOG.md
