### ISSUE TITLE
Honor dependencies when destroying resources in modules with count

### ISSUE THREAD

**Issue by artemsablin** [hashicorp/terraform#25391]
### Terraform Version

```
Terraform v0.13.0-beta2
```

### Terraform Configuration Files

```hcl
$ cat main.tf
provider "local" { }

module "access" {
  count = 1
  source = "./access"
}

$ cat access/main.tf
resource "local_file" "file_out_2" {
  filename = "./instance_details"
  depends_on = [
    local_file.file_out
  ]
}

resource "local_file" "file_out" {
  filename = "./instance_details"
}
```

### Expected Behavior

I expect terraform to do this:
```
module.access.local_file.file_out_2: Destroying... [id=da39a3ee5e6b4b0d3255bfef95601890afd80709]
module.access.local_file.file_out_2: Destruction complete after 0s
module.access.local_file.file_out: Destroying... [id=da39a3ee5e6b4b0d3255bfef95601890afd80709]
module.access.local_file.file_out: Destruction complete after 0s
```

### Actual Behavior

It does this instead:
```
module.access[0].local_file.file_out_2: Destroying... [id=da39a3ee5e6b4b0d3255bfef95601890afd80709]
module.access[0].local_file.file_out: Destroying... [id=da39a3ee5e6b4b0d3255bfef95601890afd80709]
module.access[0].local_file.file_out: Destruction complete after 0s
module.access[0].local_file.file_out_2: Destruction complete after 0s
```

### Steps to Reproduce

Apply the code above then destoy it. 

### Additional Context

Removing `count` from module configuration gets terraform to behave as expected. 

In real-life application, this issue causes terraform to fail destroying an aws_db_subnet_group inside a "counted" module as it tries to do so while a dependent aws_db_instance is still being destoyed, causing the entire destroy command to fail.

**Comment by jbardin** [comment]
Thanks @artemsablin, excellent find! It appears the stored dependencies got lost in here somehow.
