### ISSUE TITLE
Support conditional expression in depends_on

### ISSUE THREAD

**Issue by jacobisaliveandwell** [hashicorp/terraform#25395]
### Current Terraform Version

```
Terraform v0.12.20
```

### Use-cases
I want to be able to ensure my dependency chain exists regardless of whether I'm creating the resource, or using a data source to supplement when resources are created out-of-band.

```hcl
resource "github_branch" "foobar" {
  ...
  depends_on = ["${var.manage_repo ? github_repository.main : data.github_repository.main}"]
}
```

### Attempted Solutions
There isn't one.

### Proposal
extend expression support to depends_on

### References
I could not find any open references

**Comment by apparentlymart** [comment]
Hi @jacobisaliveandwell,

Based on the use-case you described, I'd expect to write the following:

```
resource "github_branch" "foobar" {
  ...
  depends_on = [github_repository.main, data.github_repository.main]
}
```

Did you try that and find that it doesn't work? If so, I'd love to see exactly what error message you saw, because something like the above _ought_ to work.

**Comment by jacobisaliveandwell** [comment]
@apparentlymart I did not think to try that. If it works, I'll close this. If not, I'll ping you again. Thanks!!

**Comment by jacobisaliveandwell** [comment]
@apparentlymart This got more interesting. It looks like using `count` does not prevent `data` blocks from performing work, because my `github_repository` block is getting a 404 despite count = 0. You can close this. Not sure if you want to make an issue to track this behavior I've uncovered.

Thanks!

**Comment by apparentlymart** [comment]
Thanks for confirming, @jacobisaliveandwell! I'll close this issue, then.

If you want to talk more about how `count = 0` is interacting with your data resources, feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core) and share your full configuration there. Then we can get into the details of your specific situation there and see if there's a different way to express what you're trying to express, and other folks who are perhaps more familiar with the GitHub provider might also be able to offer some tips.
