### ISSUE TITLE
v0.12.28 (darwin, amd64) gets signal: killed

### ISSUE THREAD

**Issue by skyzyx** [hashicorp/terraform#25415]
### Issue

v0.12.28 (darwin, amd64) gets _signal: killed_. macOS 10.15.6 Beta (19G46c)

### Using v0.12.26

```bash
terraform --version
```

```plain
Terraform v0.12.26

Your version of Terraform is out of date! The latest version
is 0.12.28. You can update by downloading from https://www.terraform.io/downloads.html
```

### Using v0.12.28

```bash
terraform --version
```

```plain
signal: killed
```

### Possible context?

<img width="305" alt="Screen Shot 2020-06-26 at 11 01 09 AM" src="https://user-images.githubusercontent.com/39447/85887314-5fe75a00-b79c-11ea-8720-767f2d095503.png">

**Comment by alisdair** [comment]
Hi @skyzyx! I'm not able to reproduce this on macOS 10.15.5.

If you run `TF_LOG=trace terraform version`, is there any more output?

**Comment by skyzyx** [comment]
So I was downloading the latest zip version in Golang, then unzipping it from Golang as well. When trying to run Terraform on the shell (via Golang, again), this was giving me _signal: killed_, which appeared to be related to Gatekeeper.

Downloading and installing the latest version of Terraform via another tool (like [asdf](https://asdf-vm.com)) doesn't have this issue. (Not sure what's different here.)

Downloading the zip from Golang, then unzipping and running `./terraform` from Bash works just fine (and, I assume, does whatever ping that macOS needs to validate for Gatekeeper). Terraform runs just fine. And now, subsequent attempts to download, unzip, and run from inside Golang appears to work just fine.

So, this definitely appears to be something that I don't _quite_ understand about Gatekeeper and notarization. I'm pretty sure this isn't a Terraform issue, though.

Resolving, but I'd love any insight anyone has around unzipping a notarized package from Go. I know that @mitchellh created `gon` (which I'm using to notarize _my_ app), and may know things here.
