### ISSUE TITLE
'Outputs' are not printing out while performing "terraform apply"

### ISSUE THREAD

**Issue by shruk95** [hashicorp/terraform#25429]
### Terraform Version

```
Terraform v0.12.28
```

### Terraform Configuration Files

```
resource "aws_iam_role" "design" {
  name                 = "${module.config.env}-design"
  max_session_duration = 3600

  assume_role_policy = data.aws_iam_policy_document.design_assume_role.json
}
```

```
output "design_assumable_role_arn" {
  value = aws_iam_role.design.arn
}
```
```
```
### Expected Behavior

After applying `terraform apply` it should have printed the output "design_assumable_role_arn" with AWS IAM Role arn value.

### Actual Behavior

There is no output after performing `terrafrom apply` . The `terraform output` doesn't contain show "design_assumable_role_arn"
### Steps to Reproduce

1. terraform plan 
2. terraform apply

FYI , it's happening today . I used output before and was facing this issue form the morning.

**Comment by apparentlymart** [comment]
Hi @shruk95! Sorry for this odd behavior, and thanks for reporting it.

Unfortunately I've been unable to reproduce the behavior you reported here. The configuration you shared wasn't complete, so I modified it slightly so I'd be able to apply it:

```hcl
resource "aws_iam_role" "design" {
  name                 = "boop-design"
  max_session_duration = 3600

  assume_role_policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": "sts:AssumeRole",
        "Principal": {
          "Service": "ec2.amazonaws.com"
        },
        "Effect": "Allow",
        "Sid": ""
      }
    ]
  })
}

output "design_assumable_role_arn" {
  value = aws_iam_role.design.arn
}
```

When I applied this configuration I saw the output value as expected:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_iam_role.design will be created
  + resource "aws_iam_role" "design" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "ec2.amazonaws.com"
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + max_session_duration  = 3600
      + name                  = "boop-design"
      + path                  = "/"
      + unique_id             = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_iam_role.design: Creating...
aws_iam_role.design: Creation complete after 1s [id=boop-design]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

design_assumable_role_arn = arn:aws:iam::853745824908:role/boop-design
```

Because of this, I'm assuming that something else you have in your configuration is important to reproduce the bug you saw. In order to continue debugging here, it would help to see a complete (but minimal) configuration example that you've been able to run and see the missing output, and also the full output from `terraform apply` you saw when you tried it, similar to what I shared above.

Thanks!

**Comment by shruk95** [comment]
Hi @apparentlymart ,

Thank you for your time and sorry about the bug. 

The issue was on my end , I forgot about having `data "terraform_remote_state"` in our main module configuration . 

I was trying to print nested modules outputs. This is why I was having the trouble with printing outputs.
