### ISSUE TITLE
terraform plan/apply doesn't respect sensitive output of remote state

### ISSUE THREAD

**Issue by alxrem** [hashicorp/terraform#25423]
### Terraform Version

```
$ terraform-0.13 version
Terraform v0.13.0-beta2
+ provider registry.terraform.io/terraform-providers/gitlab v2.10.0
```

### Terraform Configuration Files

```hcl

data "terraform_remote_state" "cloud" {
  backend = "gcs"
  config = {
    bucket      = "bucket"
    prefix      = "prefix"
    credentials = var.terraform_states_credentials
  }
}
```

### Expected Behavior

`data.terraform_remote_state` outputs are not displayed at all as in terraform 0.12

### Actual Behavior

`data.terraform_remote_state` outputs are displayed, including marked in remote output as sensitive.

### Steps to Reproduce

`terraform plan`

**Comment by jbardin** [comment]
Thanks for filing the issue @alxrem,

This is the expected behavior at the moment, and we are tracking the issue in #8076

Thanks!
