### ISSUE TITLE
aws_batch_job_definition | Error: "Container properties should not be empty"

### ISSUE THREAD

**Issue by Geartrixy** [hashicorp/terraform#25449]
### Terraform Version

```
Terraform v0.12.23
+ provider.aws v2.68.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
# job definition
resource "aws_batch_job_definition" "job_definition" {
  name = var.batch_job_definition_name
  type = "container"
  
  retry_strategy {
      attempts = var.retry_strategy_attempts
  }

  timeout {
    attempt_duration_seconds = var.timeout_attempt_duration_seconds
  }

  # API Container Properties: https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerProperties.html
  container_properties = data.template_file.job_definition.rendered
}

# template file
data "template_file" "job_definition" {
  template = file("${path.module}/job_definitions/job_definition.json")

vars = {
    command                = jsonencode(var.job_def_command)
    image                  = jsonencode(var.job_def_image)
    jobrolearn             = jsonencode(aws_iam_role.ecs_task.arn)
    memory                 = var.job_def_memory
    vcpus                  = var.job_def_vcpus
    privileged             = var.job_def_privileged
    readonlyrootfilesystem = var.job_def_readonly_root_file_system
    gpus                   = var.job_def_gpus
  }
}

# job definition json
{
    "containerProperties": {
        "command": [ ${command
            }
        ],
        "image": ${image
        },
        "jobRoleArn": ${jobrolearn
        },
        "memory": ${memory
        },
        "vcpus": ${vcpus
        }
    },
    "nodeProperties": {
        "nodeRangeProperties": [
            {
                "container": {
                    "privileged": ${privileged
                    },
                    "readonlyRootFilesystem": ${readonlyrootfilesystem
                    },
                    "resourceRequirements": [
                        {
                            "type": "GPU",
                            "value": ${gpus
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```

### Debug Output
https://gist.github.com/Geartrixy/9d5944e0a60c8c06dfeba37664b61927

### Expected Behavior

Job definition for batch gets created.

### Actual Behavior

Error: : Error executing request, Exception : Container properties should not be empty, RequestId: b61cd41a-6f8f-49fe-b3b2-2b0e6d01e222
        status code: 400, request id: b61cd41a-6f8f-49fe-b3b2-2b0e6d01e222 "tf-my-job"

  on modules\batch\batch.tf line 40, in resource "aws_batch_job_definition" "job_definition":
  40: resource "aws_batch_job_definition" "job_definition" {

### Steps to Reproduce

`terraform apply`

**Comment by apparentlymart** [comment]
Hi @Geartrixy,

This error message seems to be from the AWS provider rather than from Terraform Core, so I don't think there's anything we can change in this repository that would improve the situation. There being a RequestId in the error message also suggests that this error was returned from the remote API rather than directly from the provider, which makes me suspect that the template you're rendering here isn't producing a valid value for `container_properties`.

I suggest starting a topic about this in [the AWS Provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33), because the folks who participate there are generally more familiar with these AWS provider resources than the Terraform Core maintainers who work in this repository.

**Comment by Geartrixy** [comment]
Upgraded terraform version and receive the same error

```
Terraform v0.12.28
+ provider.aws v2.68.0
+ provider.template v2.1.2
```

**Comment by Geartrixy** [comment]
> Hi @Geartrixy,
> 
> This error message seems to be from the AWS provider rather than from Terraform Core, so I don't think there's anything we can change in this repository that would improve the situation. There being a RequestId in the error message also suggests that this error was returned from the remote API rather than directly from the provider, which makes me suspect that the template you're rendering here isn't producing a valid value for `container_properties`.
> 
> I suggest starting a topic about this in [the AWS Provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33), because the folks who participate there are generally more familiar with these AWS provider resources than the Terraform Core maintainers who work in this repository.

Ok thanks for the update, sorry saw the message late.
