### ISSUE TITLE
Merge conflict markers in documentation website

### ISSUE THREAD

**Issue by simonschmidt** [hashicorp/terraform#25444]
There are merge conflict markers in:
https://www.terraform.io/docs/import/index.html

Not sure why, the markdown files look fine:
https://github.com/hashicorp/terraform/blob/master/website/docs/import/index.html.md

Screenshot:
--

![tf](https://user-images.githubusercontent.com/2243140/86210127-bbd72780-bb7c-11ea-8c53-a0f88733eb22.png)

**Comment by alisdair** [comment]
Thanks for pointing this out! It seems to have been fixed since you reported it, so I'm closing the issue.
