### ISSUE TITLE
Escape outputs according to variable types

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#2547]
Related to https://github.com/hashicorp/terraform/pull/2503 , #1209 , #2335 and #2390 
Currently when output is printed via `terraform output` or just attached to `terraform apply`, it is not escaped at all, e.g.

```
Outputs:

  test-count  = 3
  test-region = us-east-1
```

I know it would be best to just allow formatting the output as JSON, but at the same time it would be nice to just make the current output format compatible with HCL - i.e. escape output properly per specific type:

https://github.com/hashicorp/hcl/blob/master/hcl/object.go#L15-22

I guess even JSON format will need to take similar approach based on object type, so it probably doesn't make a huge difference whether this is solved via JSON or current HCL format.

**Comment by mitchellh** [comment]
Outputs aren't really meant to be in any re-consumable format. I'm supportive of a JSON output format for things, but don't think the general human-readable output should be in any such format.
