### ISSUE TITLE
module.***_asg.aws_autoscaling_group.this: aws_autoscaling_group.this: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

### ISSUE THREAD

**Issue by suryasingh336** [hashicorp/terraform#25478]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hi @suryasingh336 

While you have not provided any info here, unfortunately we are well aware that the error output in this "diffs didn't match" situation is often not enough to diagnose the problem. Starting in 0.12 the situation that causes this error is more precisely reported, and the necessary debugging information is recorded in the logs. If this issue persists after upgrading Terraform, please file an issue with the referenced provider.
