### ISSUE TITLE
aws_inspector_resource_group resource property should accept list values over its keys

### ISSUE THREAD

**Issue by kkalugerov** [hashicorp/terraform#25479]
Hi there,

Today when I tried to launch a AWS Inspector using the provided TF resource I saw that the following resource aws_inspector_resource_group doesn't take the right value for its tags property.

```
resource "aws_inspector_resource_group" "bar" {
  tags = {
    Name = "foo"
    Env  = "bar"
  }
}
```
What I mean is as follows: the Name key inside the tags property should accept a list of strings instead of single string. Same should be applied to every key inside the tags property. I belive it should become something like this:
```
resource "aws_inspector_resource_group" "bar" {
  tags = {
    Name = [ "foo1", "foo2" ]
    Env  = [ "bar1", "bar2" ]
  }
}
```
This is currently available in the AWS Console and like this we are able to create only one AWS Inspector resource group with multiple values for its keys instead of creating multiple groups like this.

So my question is : will it be this possible to be implemented soon ? :)

```Terraform version 0.12.24```

**Comment by bflad** [comment]
Hi @kkalugerov 👋  This appears to be a request for certain functionality within the [Terraform AWS Provider](https://www.terraform.io/docs/providers/aws/r/inspector_resource_group.html), which has a separate codebase than Terraform itself so it can be released separately. I will have our bot automatically migrate this issue to the other repository.
