### ISSUE TITLE
jsonencode changing order of the elements

### ISSUE THREAD

**Issue by popiol** [hashicorp/terraform#25481]
### Terraform Version
```
Terraform v0.12.28
```

### Expected Behavior
The jsonencode function should preserve the order of elements

### Actual Behavior
The elements are sorted by key

### Steps to Reproduce
1. `terraform console`
2. `jsonencode({b = 1, a = 2})`
3. The output is: {"a":2,"b":1}

### Additional Context
The order of elements is important in AWS configuration, e.g. the event pattern needs to have "source" element before the "detail" element. Currently, it can be handled using the "heredoc" syntax, but it would be convenient to be able to use jsonencode function.

**Comment by jbardin** [comment]
Hi @popiol 

JSON objects, which this syntax would encode to, are unordered per the specification:

> An object is an unordered collection of zero or more name/value pairs, ...

The internal storage for an arbitrary object will also at some point in the encoding/decoding process be a map, which is also unordered.  The output will appear sorted to make it consistent, but nothing should be depending on this ordering. 

If there is some requirement for the ordering of keys within the AWS provider, the provider will have to sort the keys itself. I suggest opening a issue with that provider, along with an example showing the specific resource and attributes effected.

Thanks!
