### ISSUE TITLE
Add `-read-only` option for `remote` commands

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#2548]
`terraform remote config -backend=...` (i.e. just the initiation) uploads a current local state if none exists in the remote storage. I think this behaviour should be optional.

There should be a more elegant way of checking the current state. I may only want to check the current state by running `terraform plan` or `terraform show` and in these cases I don't want to create anything, in fact I should not even need write access to that storage (whatever that storage happens to be).

**Comment by thegedge** [comment]
So, this would be really useful for us. We've been bitten by the [state persistence](https://github.com/hashicorp/terraform/blob/408ae6230676831f70eefb179da61c52c531bf88/command/plan.go#L82) of `terraform plan` when `--refresh=true` (the default).

A specific scenario: a coworker and I are both working on a single stack in separate branches, I apply my changes and my remote state gets pushed. My coworker does some stuff and just wants to see the plan to "test" out their work, but there are changes with the refresh so the state gets pushed to the remote and my work gets clobbered. This happened to us in the past and we learned from our mistakes by enabling versioned S3 buckets, but this is still quite frustrating. Read-only or state locking would save us a lot of hassle.

**Comment by ajmath** [comment]
This issue is also biting us where access to prod/qa s3 buckets is restricted making planning locally impossible.

**Comment by catsby** [comment]
Closing – `terraform plan` and `terraform show` no longer update state (local or remote)
