### ISSUE TITLE
Loop over a Map type variable

### ISSUE THREAD

**Issue by pranshu-KN** [hashicorp/terraform#25483]
### Current Terraform Version
`Terraform v0.12.25`

As I need to put the AWS Lambda Environment variables , which are in the form of map block , as shown below:-

`environment {
    variables = {
      foo = "bar"
    }
  }`

So I need to put the key and value of the map again and again , which is not being possible as I am not being able to iterate over the given variable map:- 
```
`variable "lambda_env_variables" {
    description     = "the environment variables for the lambda function"
    type            = map(string)
    default         = {
        "db_host":"asasx.rds.amazonaws.com"
        "db_name":"DATABASE"
        "db_port":"3306"
        "db-user":"dev_only"

    }
}`
```

for this I need to set the above variables in the lambda function environments variables , as I cannot use the dynamic
 block for this with for_each as dynamic block will create a multiple environment or variables inline block , which is not supported by the terraform , as of now.

**Comment by apparentlymart** [comment]
Hi @pranshu-KN,

What you've described here should already work, if you write the `environment` block like this:

```hcl
environment {
  variables = var.lambda_env_variables
}
```

If you tried that and saw an error, please share the error so we can understand better what situation you've encountered.

Thanks!

**Comment by pranshu-KN** [comment]
Thanks @apparentlymart  the solution worked
