### ISSUE TITLE
Opsworks - Puppet Enterprise

### ISSUE THREAD

**Issue by Anil-A** [hashicorp/terraform#25493]
### Current Terraform Version

we are running with TF 12

### Use-cases

We are planning to deploy opsworks- Puppet enterprise using terraform resources, however existing resource doesn't seems to be available for PE. Could you please confirm is there a way we can launch PE using terraform or we need to move to other solution?

### Attempted Solutions

I've tried raising this question is github, hashicorp, terraform and stackoverflow however I haven't got any responses, any help you can provide to understand if this is possible or not so that we can opt for cloudformation or any other available features/services?

**Comment by pkolyvas** [comment]
@Anil-A - the best place to check for support of a given service is in the [AWS Provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs). It seems the [Opswork resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_application) doesn't yet support Puppet Enterprise. 

The best place to make a request for support of any AWS service, if you would like to use Terraform is via the AWS provider issue tracker on Github.

I'm going to move this ticket there.
