### ISSUE TITLE
Remote config init may cause a lost of control over existing resources

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#2549]
### Example

1) Make sure there's nothing saved in `s3://terraform-state/terraform.tfstate` and there's no local state in the current directory
2) Create `sample.tf`:
```ruby
resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/16"

  tags {
    Name = "Apple"
  }
}
```
3) Run `terraform apply` -> VPC created as `vpc-0000000`
4) Enable remote state via `terraform remote config -backend=s3 -backend-config=bucket=terraform-state -backend-config=region=us-east-1 -backend-config=key=terraform.tfstate`
5) Remove any local state/configuration (i.e. `rm -rf .terraform && rm -f terraform.*`) - i.e. Imagine I'm just another team member checking out the same repository. :alien: 
6) Add a resource to the existing code, e.g. S3 bucket and change tag for the VPC:
```ruby
resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/16"

  tags {
    Name = "Pear"
  }
}

resource "aws_s3_bucket" "default" {
  bucket = "my-pear-terraform-test-bucket"
}
```
7) Run `terraform apply` (_because for some reason this new team member forgot to sync the remote state first_) ->  VPC created as `vpc-1111111`
8) Now panic :eyes: -> realise that everything is now deployed twice -> in this case it's probably best to just destroy these duplicate resources and start over, but imagine I just decide not to do it.
9) Enable remote state via `terraform remote config -backend=s3 -backend-config=bucket=terraform-state -backend-config=region=us-east-1 -backend-config=key=terraform.tfstate`
10) Which one wins? `vpc-1111111` - i.e. Control over the original VPC created by the first team member is gone from S3 and local state. :boom: 

------

I'm not sure yet whether this is a core `remote` problem or just a bug in S3 remote storage, I will assume it's core for now and whoever begins debugging this (eventually me) can change the label.

**Comment by radeksimko** [comment]
I should also note that I tried to just change the single existing resource (not add anything new, like the S3 bucket above) and that caused error (which I believe is expected behaviour in these cases):

> Error while performing the initial pull. The error message is shown
below. Note that remote state was properly configured, so you don't
need to reconfigure. You can now use `push` and `pull` directly.

> Unknown refresh result: Local and remote state conflict, manual resolution required

Although it's not very clear how user can solve the conflict.

**Comment by mitchellh** [comment]
I don't think this is a bug, you should/must be committing the `.terraform` directory. There is a better way to fix this that we have planned as a larger core change (splititng tfstate into tfstate and tfcache, where tfcache can be deleted, but the state must be kept).

**Comment by mitchellh** [comment]
Going further: if you don't commit the `.terraform` directory, then this exact situation happens: the other team member doesn't get the remote state config and it looks like nothing is created. This should be documented as such, and as I said the long term solution is above.

**Comment by radeksimko** [comment]
@mitchellh Separation into tfstate and tfcache makes sense, but it obviously depends what do you intend to store in each. Currently there's multiple things stored in `.terraform` - cached modules & tfstate (which contains both remote config & the actual state of resources). If people are going to use remote storages, then they will likely going to ignore `.terraform` or at least tfstate, otherwise each change in the state (caused by terraform apply) will need committing to CVS (git).

So if there's plan to separate `remote` section of tfstate into a separate file, then :+1:

**Comment by mmell** [comment]
> separate remote section of tfstate into a separate file

This is still needed.
