### ISSUE TITLE
Failed to create CloudFlare Record: API Error: Zone does not exist.

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#2551]
In a CloudFlare multi-user organizational account no single user owns the data, but only has access rights to it, while it's owned by the organization. This causes zones seemingly not to exist when you try to add a record using one of the users and their api key.

The old api (https://www.cloudflare.com/docs/client-api.html) does not support the multi-user model, where the new one (https://api.cloudflare.com/) does.

I see the https://github.com/pearkes/cloudflare/ provider still uses the old api. Should I raise this issue with pearkes?

**Comment by ziggythehamster** [comment]
I'm subscribing here as well - the upstream API used for CloudFlare (pearkes/cloudflare) prohibits Terraform from supporting the other APIs that CloudFlare exposes, like page rules (which would be the exact kind of thing that you'd want to manage with Terraform).

**Comment by Turneliusz** [comment]
Would be great to update

**Comment by loicAG** [comment]
This is an issue for us as well

**Comment by stack72** [comment]
Hi all

The cloudflare provider now uses the official cloudflare API - please can you tell me if this is still an error?

Thanks

Paul

**Comment by craigedmunds** [comment]
This is still an issue in Terraform 0.7.0, I believe it's the same issue. I get:
* cloudflare_record.cf_dns: Error finding zone ":domain:": ListZones command failed: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6103,\"message\":\"Invalid format for X-Auth-Key header\"}]}],\"messages\":[],\"result\":null}"

**Comment by craigedmunds** [comment]
Hey @stack72 not sure if you've seen this - worth removing the "waiting-response" label?

**Comment by pasali** [comment]
@stack72 i guess i am getting same error in Terraform v0.7.7
`Error finding zone "example.com": Zone could not be found`
