### ISSUE TITLE
Condition_scope will be included all the time you run terraform plan  

### ISSUE THREAD

**Issue by MadhuraDhanajaya** [hashicorp/terraform#25514]
### Terraform Version

```
Terraform version = 0.12.24
Provider version = 1.16.0
```

### Terraform Configuration Files

```terraform
Under alert_conditions we have defined a Condition scope to "instance"
```
### Expected Behavior
module.alert_policies.newrelic_alert_condition.alert_conditions["xyzzzzzzzzzz"] 
   resource "newrelic_alert_condition" "alert_conditions" {
       condition_scope       = "instance"
        enabled               = true

### Actual Behavior
module.alert_policies.newrelic_alert_condition.alert_conditions["xyzzzzzzzzzz"] **will be updated in-place**
  ~ resource "newrelic_alert_condition" "alert_conditions" {
      **+ condition_scope       = "instance"**
        enabled               = true
 **Plan: 0 to add, 4 to modify, 0 to destroy.**     
Modify should not happen each time you run terraform plan/apply because you have already defined it with in your resource. When there is no change in resources why is that condition scope getting added all the time? 

### Steps to Reproduce
`terraform plan`
`terraform apply`

**Comment by jbardin** [comment]
Hi @MadhuraDhanajaya,

This appears to be an issue with the NewRelic provider. Feel free to open an issue in their repository: https://github.com/newrelic/terraform-provider-newrelic

Thanks!
