### ISSUE TITLE
Integreate Proxmox provider and provisioner

### ISSUE THREAD

**Issue by Syntax3rror404** [hashicorp/terraform#25531]
Please support the Proxmox VE plattform. I use packer to build the templates. In Packer Proxmox was official supported. 

You can integrate a existing Provider and provisioner from this GitHub site: (The logic exist and working)
https://github.com/Telmate/terraform-provider-proxmox

**Comment by pkolyvas** [comment]
Hi @Syntax3rror404 - thanks for the submission!

Regarding provisioners, we aren't going to be accepting PRs for new third party provisioners; the have been an area of Terraform that has been increasingly difficult, even impossible for the team to maintain. 

Great news about providers however! We're really fortunate to be able to encourage third party provider developers to join our publishing beta for the [Terraform Registry](https://registry.terraform.io) – the future home for publishing and discovering Terraform Providers. 

Community provider developers can join the program and publish community providers to the registry using the instructions linked below. If you're not the provider developer, please consider filing an issue with community providers you use and encourage them to add the provider to the Terraform Registry. 

https://www.terraform.io/docs/registry/providers/publishing.html
