### ISSUE TITLE
Crash on `terraform init` 

### ISSUE THREAD

**Issue by andpatt** [hashicorp/terraform#25560]
### Terraform Version

```
Terraform v0.13.0-beta2
```

* (The issue also occurs on Terraform v0.13.0-beta1, and i upgraded to beta 2 to try fix it.)
* On `Terraform v0.12.28` the output is not a crash, but a regular error: 

```
acpatt@kestrel:~/Repos/createam$ terraform init

Initializing provider plugins...
- Checking for available provider plugins...

Provider "null resource" not available for installation.

A provider named "null resource" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

- Downloading plugin for provider "azuread" (hashicorp/azuread) 0.10.0...

Warning: Skipping backend initialization pending configuration upgrade

The root module configuration contains errors that may be fixed by running the
configuration upgrade tool, so Terraform is skipping backend initialization.
See below for more information.


Error: no provider exists with the given name



Error: Invalid resource type name

  on createam.tf line 7, in resource "null resource" "test_resource":
   7: resource "null resource" "test_resource" {

A name must start with a letter or underscore and may contain only letters,
digits, underscores, and dashes.

acpatt@kestrel:~/Repos/createam$
```

### Terraform Configuration Files

```terraform
-> createam.tf
# Define the provider. In this case we're building in azureAD initially
provider "azuread" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "=0.10.0"
  # we're working with the test tennancy right now.
  tenant_id = "[REDACTED]" 

}

resource "null resource" "test_resource" {
    
}

-> project_secrtets.tf

variable "secret" {
    type = map(string)
    default = {
      "secret_key" = "secret_value"
    }
}

-> variables.tf


terraform {
  backend "http" {
  }
}




```

* the tenant_id is a standard format though, it looks like 00000000-0000-000-0000-000000000000 but with zeroes replaced by hex characters.

### Debug Output

`https://gist.github.com/andpatt/c52d3c8525694ac1e893eecd7b08be1e`

### Crash Output

`https://gist.github.com/andpatt/a9eed92691944d4976629a3d982fc98b`
### Expected Behavior

It should have either init'd or complained that it couldn't init because of some syntax error or etc.
### Actual Behavior

I got the crash above.

### Steps to Reproduce

1. `terraform init`
### Additional Context

The only unusual thing I was trying to do was use gitlab as the http backend, but I hadn't even got as far as putting the URL in and all that!I literally created those files in my repository and typed 'terraform init' in the terminal. Running ubuntu 18.04.

thanks guys!

**Comment by mildwonkey** [comment]
Hi @andpatt , thanks for reporting this and sorry you've experienced it! As you've said, you should be getting an error here, but definitely not a crash. 

This can be reproduced with just the misnamed `"null resource"` (instead of `"null_resource"`): 

```
resource "null resource" "test_resource" {

}
```
