### ISSUE TITLE
Feature / bug : (Azure RM) NSGs (Network Security Groups) do not allow multiple individual ports for source/destination port

### ISSUE THREAD

**Issue by AlexcFrench** [hashicorp/terraform#25573]
Hi,

New to terraform (2 days now!) and building out a library. We are defining multiple individual ports in the NSG rules. In the portal / ARM it is possible to define the ports as '80, 443' in a single security rule but this does not appear to be supported in terraform

Error is:
StatusCode=400 -- Original Error: Code="SecurityRuleInvalidPortRange" Message="Security rule has invalid Port range. Value provided: 80, 443. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535." 

Expected behaviour would be that a comma-separated list of ports is supported and applied.

**Comment by apparentlymart** [comment]
Hi @AlexcFrench! Welcome to Terraform! :wave: 

This seems to be a question about a particular provider, though I'm not sure which one. This repository is for the Terraform Core (provider-agnostic) functionality, and each provider has its own separate repository where their own teams track bug reports and enhancements via GitHub issues.

This seems like it might be a usage question though, in which case I would recommend starting a topic in [the Terraform Providers community forum](https://discuss.hashicorp.com/c/terraform-providers/31). Some providers (those which get enough questions to warrant it) have their own specific sub-category there, so if your question is about one of those then you can select it from the "Category" box when you create a topic to make it more likely to be seen by folks who are knowledgable about that provider. I think people there will also be more likely to be able to offer good advice if you include the configuration you're working with that generated that error, so the reader can understand better what it relates to.

We use issues in this repository only for tracking bugs and enhancements in Terraform Core, so I'm going to close this. I hope you find the answer you need in the forum! Thanks!

**Comment by AlexcFrench** [comment]
Martin,

Please accept my apologies for posting in the wrong place and thank you for the advice. I shall have a good rummage in that forum :-)

Thanks

Alex
