### ISSUE TITLE
Crashes when switching Wifi signals mid-task

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#2557]
Was executing `terraform refresh` when I switched wifi signals because the one I was connected to had time out when terraform crashed.

```
Error refreshing state: 7 error(s) occurred:

* 1 error(s) occurred:

* unexpected EOF
* 1 error(s) occurred:

* unexpected EOF
* 1 error(s) occurred:

* connection is shut down
* 1 error(s) occurred:

* connection is shut down
* 1 error(s) occurred:

* connection is shut down
* 1 error(s) occurred:

* connection is shut down
* 1 error(s) occurred:

* connection is shut down
```

[Crash logs here.](https://gist.github.com/nathanielks/06450a91d84a4621ad60)

Perhaps related to #2431 and #2434?

**Comment by mitchellh** [comment]
This should be fixed upstream. Note that Terraform handled this properly given the crash: it saved partial state and shut down. Given an exceptional event such as changing networks, this is a good behavior. The crash itself shouldn't happen but upstream it should be fixed now.

**Comment by nathanielks** [comment]
Awesome, just wanted to make sure y'all were aware. Keep up the good work!
