### ISSUE TITLE
Terraform import fails when evaluating local blocks with variables

### ISSUE THREAD

**Issue by chrisminton** [hashicorp/terraform#25574]
A `locals` block with variables does not expand those variable references correctly when running `terraform import`, using the default settings of the variable. The below is for AWS resources but others have seen similar issues on Azure etc.

### Terraform Version

```
Terraform v0.12.26
```

### Terraform Configuration Files

```terraform
variable "tags" {
  type        = map(any)
  description = "Required tags for resources"
  default     = {}
}
variable "env_private_rt_ids" {
  type        = list(string)
  default     = []
  description = "List of private route table IDs in the application VPC"
}
variable "peer_cidr_blocks" {
  type        = list(string)
  default     = []
  description = "List of CIDR blocks for the peer VPC"
}

locals {
  peer_cidr_block_length = length(var.peer_cidr_blocks)
  env_to_peer_private = var.tags["environment"] == "someenv" ? [] : flatten([
    for id in var.env_private_rt_ids : [
      for cidr in var.peer_cidr_blocks : {
        idx            = "${id}-${cidr}"
        route_table_id = id
        cidr_block     = cidr
      }
    ]
  ])
}

resource "aws_route" "env_to_peer_private" {
  for_each                  = { for route in local.env_to_peer_private : route.idx => route }
  route_table_id            = each.value.route_table_id
  destination_cidr_block    = each.value.cidr_block
  vpc_peering_connection_id = aws_vpc_peering_connection.peering[0].id
}

resource "aws_vpc_peering_connection" "peering" {
  count         = var.tags["environment"] == "someenv" ? 0 : 1
  peer_owner_id = var.account_id
  peer_vpc_id   = var.peer_vpc_id
  vpc_id        = var.env_vpc_id
  auto_accept   = true

  accepter {
    allow_remote_vpc_dns_resolution = true
  }

  requester {
    allow_remote_vpc_dns_resolution = true
  }
}
```

### Expected Behavior

Terraform should import the resource correctly

### Actual Behavior

```
Error: Invalid index

  on shared_modules/vpc_peering/routes.tf line 3, in locals:
   3:   env_to_peer_public = var.tags["environment"] == "someenv" ? [] : flatten([
    |----------------
    | var.tags is empty map of dynamic

The given key does not identify an element in this collection value.
```

### Steps to Reproduce
1. create `aws_route` resources using count
```terraform
resource "aws_route" "env_to_peer_private" {
  count                     = var.tags["environment"] == "somenv" ? 0 : var.env_private_rt_count
  route_table_id            = element(var.env_private_rt_ids, count.index)
  destination_cidr_block    = var.peer_cidr_block
}
```
2. change resources to for_each (as above)
3. attempt to import e.g. `terraform import 'module.vpc_peering.aws_route.env_to_peer_public["rtb-012345676789-10.0.0.0/23"]' rtb-012345676789_10.0.0.0/23`

### Additional Context
The `aws_route` resources were originally created using `count`, then switched to `for_each`, necessitating `terraform import`
The variable `tags` is being populated in a tfvars file and is of the form:
```terraform
tags = {
  environment = "otherenv"
}
```

### References

#24985

**Comment by amithapa** [comment]
@chrishoffman were you able to find any workaround over this bug?

**Comment by chrisminton** [comment]
@amithapa the only way I could perform the import was to hardcode the variable values.

**Comment by kimor79** [comment]
i don't think it's related to any particular resource. I'm importing ~100 resources into an empty state and they each give something like:
```
module.foo.aws_cloudtrail.main: Importing from ID "my-cloudtrail"...
module.foo.aws_cloudtrail.main: Import prepared!
  Prepared aws_cloudtrail for import
module.foo.aws_cloudtrail.main: Refreshing state... [id=my-cloudtrail]

Error: Invalid for_each argument

  on unrelated/but/used/path/buried/in/my/config.tf line 2, in module "bar":
   2:   for_each = { for bar, bar_info in local.bars : bar => bar_info if bar != local.bar }

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.


Error: Invalid for_each argument

  on another/path/buried/in/my/config.tf line 5, in module "baz":
   5:   for_each = toset(module.vpc.info["baz"] == "baz" ? var.bazs : [])

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

Releasing state lock. This may take a few moments...
```

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.5.0
+ provider registry.terraform.io/hashicorp/time v0.5.0
```

`plan` runs fine, and `apply` on a similar config runs fine (I can't apply here because the resources already exist)

**Comment by danieldreier** [comment]
@chrisminton I'm having a tough time with this one because it's a relatively complicated reproduction case for an issue that I think ought to be possible to simplify, as you described. Specifically, that `local` has two nested for loops and conditional logic in it, the `aws_vpc_peering_connection` resource is a difficult one because it requires us to have VPCs set up to peer as a test fixture, and the `count` and `for_each` on these resource both have conditional logic on them. This all makes it a relatively difficult test case for an engineer to expediently set up and reproduce, and to understand exactly where this behavior is coming from.

What would be really helpful is if you could simplify this into something that just exercises the most basic language features needed to reproduce this, and uses a super-simple resource, something that we can copy-paste rather than having to do external setup. For example, the `key_pair` resource is absolutely simple to set up with no other dependencies.

Is that something you can help with? I see a lot of people upvoting this and would like to get to the bottom of it, so I'm trying to explain what is needed to move this forward.

**Comment by chrisminton** [comment]
@danieldreier yes you are correct - I was merely putting my exact use case - but I think this could be replicated with any number of resources as others have suggested. I'll try to cobble something together for you.

**Comment by 0x91** [comment]
We're seeing this too. It's part of a much larger terraform state, but unfortunately I've had trouble reproducing it locally.

We use the S3 backend and I was testing with local state, which might be why I could not reproduce it. Here's the relevant snippets:

Error when importing unrelated resource - using a different provider:
```
Error: Invalid index

  on ./modules/api_gateway/main.tf line 2, in locals:
   2:   api_gateway_rest_api = var.private ? aws_api_gateway_rest_api.private[0] : aws_api_gateway_rest_api.public[0]
    |----------------
    | aws_api_gateway_rest_api.private is empty tuple

The given key does not identify an element in this collection value.

Code:
./modules/api_gateway/main.tf
```
locals {
  api_gateway_rest_api = var.private ? aws_api_gateway_rest_api.private[0] : aws_api_gateway_rest_api.public[0]
}

variable "private" {
  default = true
}

variable "vpc_endpoint_apigw_id" {
  default = null
}

resource "aws_api_gateway_rest_api" "public" {
  count = var.private ? 0 : 1
  name  = "${var.api_name}-public"
  endpoint_configuration {
    types = ["REGIONAL"]
  }
}

resource "aws_api_gateway_rest_api" "private" {
  count  = var.private ? 1 : 0
  name   = "${var.api_name}-private"
  policy = data.aws_iam_policy_document.private[0].json
  endpoint_configuration {
    types            = ["PRIVATE"]
    vpc_endpoint_ids = [var.vpc_endpoint_apigw_id]
  }
}

data "aws_iam_policy_document" "private" {
  count = var.private ? 1 : 0
  statement {
    effect = "Allow"

    actions = [
      "execute-api:Invoke",
    ]

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    resources = [
      "*",
    ]

    condition {
      test     = "StringEquals"
      variable = "aws:SourceVpce"

      values = [
        var.vpc_endpoint_apigw_id,
      ]
    }
  }
}
```

Root module:
```
module "api_gtw" {
  source             = "./modules/api_gateway"
  api_name        = "some-string"
  private            = false
  [extra variables ommitted]
}

resource "foo" "to be imported" {
  [...]
}
```

**Comment by jghal** [comment]
I believe I am hitting this issue too. We have this in one module

```terraform
locals {
  hostname = var.use_nat_workaround ? "${var.firewall_mgmt_address}.nip.io" : var.firewall_mgmt_address
}

provider "panos" {
  hostname = local.hostname
  username = var.firewall_username
  password = var.firewall_password
}
```

And imports will fail on the provider hostname `Error: Post https:///api: http: no Host in request URL`

We have another module with this

``` terraform
locals {
  vpc_size             = split("/", var.IP_Address_Block)[1]
  cluster_subnet_bits  = var.do_deploy_cluster_subnets == "true" ? var.cluster_subnet_size - local.vpc_size : var.cluster_subnet_size - local.vpc_size - 2
  dmz_subnet_bits      = var.do_deploy_cluster_subnets == "true" ? var.dmz_subnet_size - local.vpc_size : var.dmz_subnet_size - local.vpc_size - 2
```
and the `var.IP_Address_Block` is supplied by the caller, and in our case set in terraform.tfvars file in the pipeline. And imports fail with 

```
  24:   vpc_size             = split("/", var.IP_Address_Block)[1]
    |----------------
    | var.IP_Address_Block is ""
```

Version info:

```
$ terraform version
Terraform v0.12.29
+ provider.aws v2.70.0
+ provider.azurerm v1.44.0
+ provider.local v2.0.0
+ provider.null v3.0.0
+ provider.panos v1.6.3
+ provider.random v3.0.0
+ provider.tls v3.0.0
```

**Comment by jbardin** [comment]
Hello,

Import should now be evaluating all values correctly in the latest releases.
The remaining known issue is that multiple resource instances cannot be imported simultaneously, which is something that is going to need to wait until we develop new methods for import in general. If a single instance is being imported and the evaluation of that instance is failing, we are tracking that issue in #28188

Thanks!
