### ISSUE TITLE
Parsing kubeconfig data as a data source with kubernetes provider

### ISSUE THREAD

**Issue by linuxbsdfreak** [hashicorp/terraform#25588]
### Terraform Version
```
Terraform v0.13.0-beta2

terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/tls]
├── provider[registry.terraform.io/hashicorp/kubernetes] ~> 1.11.3
└── provider[registry.terraform.io/hashicorp/local]

Providers required by state:

    provider[registry.terraform.io/hashicorp/kubernetes]

    provider[registry.terraform.io/hashicorp/local]

    provider[registry.terraform.io/hashicorp/tls]

```

### Terraform Configuration Files
```
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    kubernetes = "~> 1.11.3"
  }
}

provider "kubernetes"{
  alias = "robotaccount"
  config_patj = "/tmp/robot.kubeconfig"
  load_config_file = "true"
}

data "kubernetes_secret" "test" {
  provider = kubernetes.robotaccount
  metadata {
    name = "test.kubeconfig"
    namespace = "test-ns"
  }
}
resource "local_file" "credentials" {
    content     = data.kubernetes_secret.test.data.kubeconfig
    filename = "credentials.kubeconfig"
}

provider "kubernetes"{
  alias = "target"
  //config_path = data.kubernetes_secret.test.data.kubeconfig
  config_path = "/tmp/credentials.kubeconfig"
  load_config_file = "true"
}

resource "kubernetes_namespace" "example" {
  provider = kubernetes.target
  metadata {
    annotations = {
      name = "example-annotation"
    }

    labels = {
      mylabel = "label-value"
    }
    name = "terraform-example-namespace"
  }
}

```

### Debug Output

This works by saving the credentials to a temporary file. However it does not work with using the below directly

**config_path = data.kubernetes_secret.test.data.kubeconfig**

### Crash Output

With the **config_path = data.kubernetes_secret.test.data.kubeconfig** set i get the below output.

```
Error: Get "http://localhost/api/v1/namespaces/terraform-example-namespace": dial tcp 127.0.0.1:80: connect: connection refused
```

### Expected Behavior
It should i have taken the contents of the kubeconfig in memory and created the connection with the data value.

### Actual Behavior
The file creation step had to added and then load the config

**Comment by linuxbsdfreak** [comment]
@mildwonkey Is this a real issue or am I doing something incorrect ?

**Comment by mildwonkey** [comment]
At a glance this looks like a configuration issue: the `config_path` argument expects the path to a file, and `data.kubernetes_secret.test.data.kubeconfig` is not a path to a file. Did you mean to use the local_file.credentials instead? 

If you aren't sure if you have a question versus an issue, it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by linuxbsdfreak** [comment]
@mildwonkey Thanks for the reply. I could use local_file.credentials.

 Is there a way to  not create the the file locally and leverage the data way for the passing the kubeconfig credentials ?

**Comment by mildwonkey** [comment]
I don't know the answer to that; this is regarding provider configuration options so it's really a question for the kubernetes provider maintainers.

Since this does seem to be a question, I am going to close it and suggest you ask in [the community forum](https://discuss.hashicorp.com/c/terraform-core).
