### ISSUE TITLE
Module broken if subdirectory (/ sub-path / submodule) matches git ref name

### ISSUE THREAD

**Issue by jantman** [hashicorp/terraform#25597]
# Terraform Version

```
0.12.28
```

### Terraform Configuration Files

```terraform
module "foo" {
  source = "git::ssh://git@github-enterprise.example.com/MyOrg/MyRepo//submod?ref=submod"
  foo    = "bar"
}
```

### Expected Behavior

Terraform would properly clone the module, and a plan would run successfully.

### Actual Behavior

```
+ terraform init -input=false
Initializing modules...
Downloading git::ssh://git@github-enterprise.example.com/MyOrg/MyRepo?ref=submod for us-east-2...
- us-east-2 in .terraform/modules/foo/submod

+ terraform plan
Error: Unsupported argument

on main.tf line 21, in module "foo":
   21:   foo                  = local.tags
An argument named "foo" is not expected here.
```

### Steps to Reproduce

1. Create a git repository with a terraform module nested within a directory called <anything>
2. Commit that to a branch with the same name as the subdirectory (<anything>)
3. Attempt to use this as a terraform module. When the subdirectory and branch have the same name, the branch will be ignored and ``master`` will be cloned.

### Workaround

1. Rename the branch used in ``ref``, or create another branch off of it, called _anything_ other than the same string as the subdirectory name.
2. Update the ``ref`` to point to that new branch.
3. Success.

**Comment by alisdair** [comment]
I'm not able to reproduce this issue with either Terraform 0.12.28 or 0.13.0. Here's the configuration I used:

```hcl
module "foo" {
  source = "git::ssh://git@github.com/alisdair/terraform-random-nonsense-words//repro?ref=repro"
  length = 4
}

output "words" {
  value = module.foo.repro_words
}
```

Running `terraform init` succeeds, and apply has the appropriate outputs [for the repro branch of my module](https://github.com/alisdair/terraform-random-nonsense-words/blob/repro/repro/main.tf):

```shellsession
$ terraform apply -auto-approve
module.foo.random_pet.nonsense: Creating...
module.foo.random_pet.nonsense: Creation complete after 0s [id=totally-greatly-classic-falcon]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

words = totally-greatly-classic-falcon
```

I had the same result with both versions of Terraform.

If this is still happening for you, could you provide a full but minimal reproduction case, including a public module?

**Comment by jantman** [comment]
@alisdair Thank you so much for looking into this. I'm just wrapping up for the day and will be away this weekend, but I'll reply back first thing Monday morning with some specific code to reproduce.

**Comment by jantman** [comment]
I'm really sorry, but now I can't reproduce this either. Apologies.
