### ISSUE TITLE
Unable to change aws_subnet resource when aws_vpc_entrypoints are attached to it

### ISSUE THREAD

**Issue by xorxsan** [hashicorp/terraform#25596]
### Terraform Version
```
Terraform v0.12.28
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region  = "eu-west-1"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.1.0.0/24"
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags = {
    Name = "test"
  }
}

resource "aws_subnet" "private" {
  vpc_id = aws_vpc.vpc.id

  cidr_block = cidrsubnet(
    aws_vpc.vpc.cidr_block, 4, 1
  )

  availability_zone = "eu-west-1a"

  tags = {
    Name = "test-private",
    Type = "Private",
  }
}

resource "aws_security_group" "allow_ssm" {
  name        = "allow-ssm-only"
  description = "Allow SSM"
  vpc_id      = aws_vpc.vpc.id

  ingress {
    from_port = 443
    to_port   = 443
    protocol  = "tcp"
    cidr_blocks = [aws_subnet.private.cidr_block]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_vpc_endpoint" "ssm" {
  vpc_id              = aws_vpc.vpc.id
  service_name        = "com.amazonaws.eu-west-1.ssm"
  vpc_endpoint_type   = "Interface"
  private_dns_enabled = true
  subnet_ids          = [aws_subnet.private.id]
  security_group_ids  = [aws_security_group.allow_ssm.id]

  tags = {
    Name = "test-ssm",
  }
}
```

### Debug Output
https://gist.github.com/xorxsan/4f3f187e688a0333531d5add50f2f044

### Expected Behavior
All aws_vpc_entrypoints resources attached to that aws_subnet should be destroyed first and then recreated.

### Actual Behavior
As terraform wasn't finishing (it kept on showing the following log: **aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, YmZs elapsed]**) I decided to go to AWS to manually destroy the subnet but it did not let it had aws_vpc_entrypoints attached to the aws_subnet. I had to stop terraform after 9 minutes. Last trace was:
```
aws_subnet.private: Destroying... [id=subnet-xxxxxxxxx]
aws_subnet.public: Creating...
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 10s elapsed]
---------------------- More traces ------------------
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 9m10s elapsed]
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 9m20s elapsed]
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 9m30s elapsed]
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 9m40s elapsed]
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 9m50s elapsed]
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 10m0s elapsed]
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 10m10s elapsed]
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 10m20s elapsed]
aws_subnet.private: Still destroying... [id=subnet-xxxxxxxxx, 10m30s elapsed]
Two interrupts received. Exiting immediately. Note that data
loss may have occurred.

Error: operation canceled
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. Update the **aws_subnet.private** resource so it needs to be destroyed. For instance, change the resource name from private to public and its references
4. `terraform apply`

### Additional Context
None

### References
None found

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
