### ISSUE TITLE
azure: sometimes fails with "Network configuration does not exist"

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#2560]
I seem to have worked around the issue for now, but I managed to get my testing account in a state where the networkConfigurationURL `GET` request would return a 404.

```
--- FAIL: TestAccAzureDnsServerUpdate (2.62s)
        testing.go:135: Step 0 error: Error applying: 1 error(s) occurred:

                * 1 error(s) occurred:

                * 1 error(s) occurred:

                * Failed to get the current network configuration from Azure: Error response from Azure. Code: ResourceNotFound, Message: Network configuration
 does not exist.
FAIL
exit status 1
FAIL    github.com/hashicorp/terraform/builtin/providers/azure  5.601s
```

This was causing test failures until I manually went into the web console and created a dummy network, which seemed to fix everything.

Pinging @aznashwan to follow up on this, seems relatively low priority but worth fixing up.

**Comment by aznashwan** [comment]
Hello Paul!

Indeed I'm aware of this; this has happened to me a couple of times as well.

This is (not the only) immense shortcoming of the Azure API.
I would imagine that, internally, the API tries to get the network configuration (which, if you don't have anything at all in it, will be a null object in C#) and then blindly throws this hissy fit.

This is bad API design; and there's really no way completely around it from the SDK or Terraform's side.
The only feasible thing I see to be done here is check if we get this particular error and create a completely new virtualnetwork.NetworkConfiguration struct if it happens.

**Comment by aznashwan** [comment]
Pushed fix.
