### ISSUE TITLE
Multiple Partial Configuration

### ISSUE THREAD

**Issue by tikicoder** [hashicorp/terraform#25607]
### Current Terraform Version
v0.12.28

```
...
```
The ability when using partial configuration to state what provider it is for.  Since you can have multiple providers you should be able to connect it to its matching configuration.

### Use-cases
If you have 2 providers and part of the settings are dynamic (like the storage account for prod, staging, primary, secondary)

### Attempted Solutions
The only thing I can think of is to just create multiple secondary providers

### Proposal
when you create the backend file you should be able to do something like provider_name {settings ...}

### References
\

**Comment by jbardin** [comment]
Hi @tikicoder,

If I understand this correctly, it seems like you are proposing what we have recorded in "Partial/Progressive Configuration Changes" #4149.

We can track this in #4149, as any solution to this type of problem will be recorded there. 

Thanks
