### ISSUE TITLE
docs: fix the output format of state show command

### ISSUE THREAD

**Issue by suzuki-shunsuke** [hashicorp/terraform#25616]
### Note

I selected the issue type `Bug report` because `blank_issues_enabled` is false but this issue isn't Bug report but about document.
I think an issue type about document may be needed.

### Summary

From v0.12 the output format of `state show` command seems to be changed
but the old format is used in the document.

### Terraform Version

```
$ terraform version
Terraform v0.12.28
+ provider.packet v2.10.1
```

### Terraform Configuration Files

```terraform
provider "packet" {
  auth_token = ""
}
```

### The example output in document

- https://www.terraform.io/docs/commands/state/show.html
- https://github.com/hashicorp/terraform/blob/79d74c9ba0753000caafaef11700e10bcedda003/website/docs/commands/state/show.html.md

```
$ terraform state show 'packet_device.worker'
id                = 6015bg2b-b8c4-4925-aad2-f0671d5d3b13
billing_cycle     = hourly
created           = 2015-12-17T00:06:56Z
facility          = ewr1
hostname          = prod-xyz01
locked            = false
...
```

### Actual output

```
$ terraform state show 'packet_device.worker'
# packet_device.worker:
resource "packet_device" "worker" {
    billing_cycle = "hourly"
    created       = "2015-12-17T00:06:56Z"
    facility      = "ewr1"
    hostname      = "prod-xyz01"
    id            = "6015bg2b-b8c4-4925-aad2-f0671d5d3b13"
    locked        = false
}
```

### References

- https://www.terraform.io/docs/commands/state/show.html
- https://github.com/hashicorp/terraform/blob/79d74c9ba0753000caafaef11700e10bcedda003/website/docs/commands/state/show.html.md

**Comment by suzuki-shunsuke** [comment]
I have created a pull request. https://github.com/hashicorp/terraform/pull/25615

**Comment by suzuki-shunsuke** [comment]
BTW, I can't find the change of `state show` command in the Change log of v0.12 .

**Comment by suzuki-shunsuke** [comment]
After we run `terraform import` command we can generate the terraform configuration automatically by `terraform state show` command.
It may be helpful to write about it in the document.

**Comment by suzuki-shunsuke** [comment]
📝  The change seems to be introduced by #19200 .

**Comment by danieldreier** [comment]
I'm going to close this because https://github.com/hashicorp/terraform/pull/25615 was merged. Thank you for fixing it!
