### ISSUE TITLE
Incorrect "Error: Cycle" on destroy after reversing dependencies (since 0.12.15)

### ISSUE THREAD

**Issue by dpiddockcmp** [hashicorp/terraform#25611]
### Terraform Version

```
Terraform v0.12.28
+ provider.null v2.1.2
```

### Terraform Configuration Files

Config 1:
```terraform
locals {
  name = "test-123"
}

resource "null_resource" "a" {
  triggers = {
    name = local.name
  }
} 

resource "null_resource" "b" {
  triggers = {
    name = null_resource.a.triggers.name
  }
}
```

Config 2 - reverse the dependencies:
```terraform
locals {
  name = "test-123"
}

resource "null_resource" "a" {
  triggers = {
    name = local.name
  }
  depends_on = [null_resource.b]
} 

resource "null_resource" "b" {
  triggers = {
    name = local.name
  }
}
```

### Debug Output

https://gist.github.com/dpiddockcmp/b9746db4ee98f831b228b287b0c2092e

### Expected Behavior

Running `terraform destroy` should complete successfully

### Actual Behavior

` Error: Cycle: null_resource.b (destroy), null_resource.a (destroy)`

### Steps to Reproduce

1. Use "Config 1" above
1. `terraform init`
1. `terraform apply`
1. Replace config with "Config 2" - swapping the dependencies
1. `terraform destroy`

### References

- Original report hitting the bug: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/950
- PR that caused the bug in the module: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/933

It looks like this was caused by the switch from storing `resources[].instances[].dependencies[]` in the state file instead of `resources[].instances[].depends_on[]`. `dependencies` does not get cleaned up when the dependency is no longer present in the terraform configuration file. But it only appears to cause an issue when doing a destroy.

**Comment by jbardin** [comment]
Hi @dpiddockcmp 

Thanks for the simple reproduction here.
This is similar to problem stated in #25473, as we don't currently have a way to update the internal state of these values for individual resource instances.

In this example, `null_resource.b` was created with a dependency on `null_resource.a`, and that relationship is stored in the state to ensure we can destroy the resources in the correct order if even the config is no longer present (which is common when swapping out modules). If it's possible to modify the config to force an update to the "b" resource in your case, that would cause a new state to be written out. Another workaround would be to `taint` the "b" resource too.

Looking at the linked PR, I'm not certain I understand the case for reversing all the dependencies like this. While there may be a valid use case, `depends_on` is very rarely needed and trying to structure the dependencies like this is highly unusual. My first inclination is that you are trying to emulate `create_before_destroy` somehow, but I would need to study the details of the resources themselves to be able to answer in more detail.

**Comment by dpiddockcmp** [comment]
The problem is because we're dealing with kubernetes. Everything is 10x more complicated than it needs to be.

Before the PR, the `workers` security group unnecessarily depended on the `aws_eks_cluster` for its name attribute. There was no requirement for this ordering and it works perfectly well to take the name directly from the input variable instead.

The PR author has configured their clusters to run clean-up tasks when the cluster is being destroyed. I'm not sure on the details of how they have configured this. But as part of it they create new pods which often requires pulling images from remote repos and communication between the cluster and worker nodes. The security group rules need to still be present before Terraform destroys the cluster or workers. Terraform cannot normally know about this ordering as it's unrelated to the obvious dependencies between AWS resources. Terraform happily deletes the `aws_security_group_rule`s as they appear to be leaves whilst waiting for the much slower deletion of the `aws_autoscaling_group`s thus blocking/breaking the cluster clean-up tasks. Hence the introduction of `depends_on`.
