### ISSUE TITLE
Terraform mistakenly destroys data source while provider depends on it

### ISSUE THREAD

**Issue by TamasNeumer** [hashicorp/terraform#25626]
### Issue TL;DR
- I have a Postgres provider which uses a password fetched from Vault. (The password is fetched via a `vault_generic_secret`). The password is backed by a **static role**, which is rotated quite often.
- `tf apply` works, terraform can connect to Postgres and create resources (e.g.: a `postgres_role`)
- `tf destroy` doesn't work properly, it says `Error: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "test_postgres_provisioner"`.
- Desired (and old TF 0.12) behavior: TF fetched the password, connected using the (recently rotated) password and destroyed the `postgres_role`

### Terraform Version
```
Terraform v0.13.0-beta3
+ provider registry.terraform.io/hashicorp/vault v2.12.0
+ provider registry.terraform.io/terraform-providers/postgresql v1.7.0
```

### Issue and Recreation

- To reproduce the issue we need to have the postgres password stored in vault, which will be fetched using the data source.
- The following block creates a postgres role, which I will later use to provision resources. It also creates the vault mount, vault to postgres backend connection and finally a static role which is used to rotate the provisioner password. **I believe the bug occurs when vault rotates the password between apply and destroy.**.

```tf
terraform {
  required_version = ">= 0.13"
}

provider "postgresql" {
  host = local.postgres-address
  port = local.postgres-port

  username = "postgres"
  password = "xxx"
  database = "postgres"

  sslmode         = "require"
  connect_timeout = 15
  superuser       = false
}

provider "vault" {
  address = "http://localhost:8200"
  token   = "xxx"
}

locals {
  postgres-address = "xxx.xxx.xxx.xxx"
  postgres-port = "5432"
}

##################
# POSTGRES SETUP
# - Create provisioner role
##################

resource "postgresql_role" "postgres-database-and-role-provisioner" {
  name            = "test_postgres_provisioner"
  inherit         = false
  login           = true
  create_role     = true
  create_database = true

  skip_reassign_owned = true
}

##################
# VAULT SETUP
# - Vault mount
# - Vault-backend-connection
# - Static role for "provisioner" role.
##################

resource "vault_mount" "db" {
  path = "db/postgres"
  type = "database"
  default_lease_ttl_seconds = 120
  max_lease_ttl_seconds = 31536000
}

# Specify the connection used between vault and postgres.
resource "vault_database_secret_backend_connection" "vault-postgres-connection" {

  backend = vault_mount.db.path
  name    = "vault-postgres-backend-connection"

  // A list of roles that are allowed to use this connection.
  allowed_roles = [
    postgresql_role.postgres-database-and-role-provisioner.name
  ]

  postgresql {
    connection_url = "postgres://{{username}}:{{password}}@${local.postgres-address}:${local.postgres-port}/postgres"
  }

  data = {
    username = "postgres"
    password = "xxx"
  }
}

resource "vault_database_secret_backend_static_role" "postgres-provisioner-static-role" {
  backend         = vault_mount.db.path
  name            = postgresql_role.postgres-database-and-role-provisioner.name
  db_name         = vault_database_secret_backend_connection.vault-postgres-connection.name
  username        = postgresql_role.postgres-database-and-role-provisioner.name
  rotation_period = 180
  rotation_statements = [
    "ALTER USER \"{{name}}\" WITH PASSWORD '{{password}}';"
  ]
}
```

- In another "project" I use the `test_postgres_provisioner` to create a role. The password is fetched from vault.

```tf
terraform {
  required_version = ">= 0.13"
}

provider "postgresql" {
  host = local.postgres-address
  port = local.postgres-port

  username = "test_postgres_provisioner"
  password = data.vault_generic_secret.postgres-provisioner-secret.data["password"]
  database = "postgres"

  sslmode         = "require"
  connect_timeout = 15
  superuser       = false
}

provider "vault" {
  address = "http://localhost:8200"
  token   = "xxx"
}

data "vault_generic_secret" "postgres-provisioner-secret" {
  path = "db/postgres/static-creds/test_postgres_provisioner"
}

locals {
  postgres-address = "xxx.xxx.xxx.xxx"
  postgres-port = "5432"
}

resource "postgresql_role" "postgres-dev-role" {

  depends_on = [
      data.vault_generic_secret.postgres-provisioner-secret
  ]

  name    = "dev_role"
  inherit = false
  login   = false

  # Role won't have any objects anyway. (No create object rights)
  skip_reassign_owned = true
}
```

- `terraform apply` runs through as expected. 
- Then I go to vault and start running `vault read db/postgres/static-creds/test_postgres_provisioner` to see when the password is rotated.
- Once rotated I run `terraform destroy` and get the error: `Error: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "test_postgres_provisioner"`
- I even tried to add an explicit dependency from the `postgres_role` on the data source... Didn't work.

### Debug Output
- [Link](https://gist.github.com/TamasNeumer/50a5c2d800aed251cb3ac5f91d6cc16e)
- [Illustrated dependency tree](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%20%20%20%20%20%20%20%20compound%20%3D%20%22true%22%0A%20%20%20%20%20%20%20%20newrank%20%3D%20%22true%22%0A%20%20%20%20%20%20%20%20subgraph%20%22root%22%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20data.vault_generic_secret.postgres-provisioner-secret%20(expand)%22%20%5Blabel%20%3D%20%22data.vault_generic_secret.postgres-provisioner-secret%22%2C%20shape%20%3D%20%22box%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20postgresql_role.postgres-dev-role%20(expand)%22%20%5Blabel%20%3D%20%22postgresql_role.postgres-dev-role%22%2C%20shape%20%3D%20%22box%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fhashicorp%2Fvault%5C%22%5D%22%20%5Blabel%20%3D%20%22provider%5B%5C%22registry.terraform.io%2Fhashicorp%2Fvault%5C%22%5D%22%2C%20shape%20%3D%20%22diamond%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fterraform-providers%2Fpostgresql%5C%22%5D%22%20%5Blabel%20%3D%20%22provider%5B%5C%22registry.terraform.io%2Fterraform-providers%2Fpostgresql%5C%22%5D%22%2C%20shape%20%3D%20%22diamond%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20data.vault_generic_secret.postgres-provisioner-secret%20(expand)%22%20-%3E%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fhashicorp%2Fvault%5C%22%5D%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20meta.count-boundary%20(EachMode%20fixup)%22%20-%3E%20%22%5Broot%5D%20postgresql_role.postgres-dev-role%20(expand)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20postgresql_role.postgres-dev-role%20(expand)%22%20-%3E%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fterraform-providers%2Fpostgresql%5C%22%5D%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fhashicorp%2Fvault%5C%22%5D%20(close)%22%20-%3E%20%22%5Broot%5D%20data.vault_generic_secret.postgres-provisioner-secret%20(expand)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fterraform-providers%2Fpostgresql%5C%22%5D%20(close)%22%20-%3E%20%22%5Broot%5D%20postgresql_role.postgres-dev-role%20(expand)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fterraform-providers%2Fpostgresql%5C%22%5D%22%20-%3E%20%22%5Broot%5D%20data.vault_generic_secret.postgres-provisioner-secret%20(expand)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fterraform-providers%2Fpostgresql%5C%22%5D%22%20-%3E%20%22%5Broot%5D%20local.postgres-address%20(expand)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fterraform-providers%2Fpostgresql%5C%22%5D%22%20-%3E%20%22%5Broot%5D%20local.postgres-port%20(expand)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20root%22%20-%3E%20%22%5Broot%5D%20meta.count-boundary%20(EachMode%20fixup)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20root%22%20-%3E%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fhashicorp%2Fvault%5C%22%5D%20(close)%22%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%5Broot%5D%20root%22%20-%3E%20%22%5Broot%5D%20provider%5B%5C%22registry.terraform.io%2Fterraform-providers%2Fpostgresql%5C%22%5D%20(close)%22%0A%20%20%20%20%20%20%20%20%7D%0A%7D)

### Expected Behavior

Terraform (as in 0.12) should have used the data source to fetch the recent password, connect to postgres and remove the created `postgres_role`

### Actual Behavior

- I believe TF deleted the data source and then it was surprised it can't connect to postgres.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. wait 180sec or check if PW was rotated
4. `terraform destroy`

**Comment by jbardin** [comment]
Thanks for the complete report @TamasNeumer 

This should be fixed in master, and will be included in the next development release.
If you're still having an issue with the next release, feel free to follow up here and we can investigate further.

Thanks!
