### ISSUE TITLE
Populating a terraform map variable from a CSV file

### ISSUE THREAD

**Issue by shareKnowledge** [hashicorp/terraform#25630]
How to define a value for map variable in a CSV file.
Getting following error :
"Inappropriate value for attribute "tags": map of string required."
CSV file is like:
```
srl_no,create_in_rg,proximity_placement_group_name,tag_ppg,aset_name,tag_aset
1,hub-vnet-rg,test-hub-pg,division = 'XYZ' desc = 'test-ppg',test-hub-aset,division = 'ABC' desc = 'test-aset'
```

Thanks.

**Comment by alisdair** [comment]
Hi @shareKnowledge. This doesn't seem like an issue report, but rather a usage question. Please try asking again in [the Terraform community forum](https://discuss.hashicorp.com/c/terraform-core/27), where hopefully someone will be able to help you. I recommend adding more details about your Terraform configuration and what you're trying to do.
