### ISSUE TITLE
Terraform destroy hangs/extremely slow on large-scale infra

### ISSUE THREAD

**Issue by usernamegoeshereyall** [hashicorp/terraform#25643]
### Terraform Version

```
Terraform v0.12.24
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output

No output, it just hangs or takes an hour or more to complete. 

### Expected Behavior

The infra takes only minutes to stand up, I would expect a tear down to take a similar amount of time. 

### Actual Behavior

It just hangs. 

### Steps to Reproduce

Create 500+ VMs then try to `terraform destroy` them. 

### Additional Context

This behavior is being seen with the AWS provider. The main resource being created are EC2 instances, around 500 of them. If you remove the configuration files that define these VMs and then do a `terraform apply`, the destruction of these resources happens very rapidly. There doesn't seem to be any logging or output when you go to `terraform destroy` a large number of VMs, it just hangs on the state refresh.

**Comment by jbardin** [comment]
Hi @usernamegoeshereyall 

Sorry you're having here, large infrastructure configs can pose a problem. 

Can you supply the trace logs around the time terraform slows or hangs? The operations that are happening with the gaps in the timestamps may provide more insight. There's a good chance this is covered by a number of optimizations that were made for 0.13, so you may want to test with the latest 0.13 rc if you have the ability too.

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
