### ISSUE TITLE
No error message for aws_instance creation failure

### ISSUE THREAD

**Issue by aaronbrashears** [hashicorp/terraform#2564]
I was creating an aws_instance resource with an attached ebs_block_device. On `apply`, the error message from terriform was:

```
* Error waiting for instance (i-81795976) to become ready: unexpected state 'terminated', wanted target 'running'
```

Going into the AWS UI to test, I found that I was bumping up against the ebs iops limit which returns the move useful message:

```
Error creating volume
Maximum number of active volumes iops, 100000, exceeded.
```

I would like to see that error message during the terraform operation.

**Comment by mitchellh** [comment]
Hm, interesting. I wonder where this error message appears. Where did you see it in the console? We check all API responses for errors so this must mean it is coming from some non-intuitive endpoint.

**Comment by aaronbrashears** [comment]
During the `apply` after some things refresh, I see:

    aws_instance.replayer: Creating...
      ami:                                               "" => "ami-5189a661"
      ...
      ebs_block_device.#:                                "" => "1"
      ebs_block_device.4023988449.delete_on_termination: "" => "1"
      ebs_block_device.4023988449.device_name:           "" => "/dev/xvdf"
      ebs_block_device.4023988449.encrypted:             "" => "<computed>"    
      ebs_block_device.4023988449.iops:                  "" => "20000"
      ebs_block_device.4023988449.snapshot_id:           "" => "<computed>"
      ebs_block_device.4023988449.volume_size:           "" => "2000"
      ebs_block_device.4023988449.volume_type:           "" => "io1"
      ...

and after an moment:

    aws_instance.replayer: Error: 1 error(s) occurred:

    * Error waiting for instance (i-81795976) to become ready: unexpected state 'terminated', wanted target 'running'

**Comment by pikeas** [comment]
I believe @mitchellh is asking which section of the AWS console displayed the error.

**Comment by mstuparu** [comment]
I just encountered something similar when I was trying to launch a instance with a 3 terabyte standard volume. No obvious error was thrown instance just got terminated, Then  i used volume_type = "gp2" which fixed it.

**Comment by mmell** [comment]
I see this error now. I hit CTRL-C in the middle of an apply and then started `apply` again. In the AWS UI I saw two instance being created. I terminated the older one. The second `apply` completed successfully. Now, on a third `apply` I see 

    * aws_instance.cluster_member: Error waiting for instance (i-e088de24) to become ready: unexpected state 'terminated', wanted target 'running'

I resolved the issue by manually replacing the instance id in the tfstate file.

**Comment by RyanBowlby-Reflektion** [comment]
What's the status on this one? Bubbling up that error would prove useful.

**Comment by mengesb** [comment]
I get a different issue. `delete_on_termination` doesn't seem to matter, however to see the error message I receive from AWS, I go to one of the terminated instances and get the following:

```
State transition reason: Client.InvalidParameterCombination: Could not create volume with size 40GiB and iops 5000 from snapshot 'snap-67dd9c7a'
```

I'm creating a 40G root volume with 5k IOPS on Ubuntu 14.04 LTS 64-bit LVM (ami-415f6d2b)

**Comment by mengesb** [comment]
Looks like this is more related to the AMIs compatibility. Seems that I should probably be using `ami-aac24fbd` instead

**Comment by mengesb** [comment]
So the root of my issue is there's math involved in creating the volume itself.  Doing direct `aws ec2 create-volume` commands, it shows there's a ratio of size in GiB and IOPS 1:30:

```
$ aws ec2 create-volume --size 20 --snapshot-id snap-b619c24e --region us-east-1 --availability-zone us-east-1a --volume-type io1 --iops 1000

An error occurred (InvalidParameterValue) when calling the CreateVolume operation: Iops to volume size ratio of 50.000000 is too high; maximum is 30
```

The maximum IOPS for a 20 GiB volume would be 600 (20 * 30 = 600). To get to a minimum of 1000 I'd have to create a volume 33GiB in size or larger. 10k IOPs would require a volume 334GiB in size or larger.

Not sure that this check can be included in terraform, however the error messages are not that grand even considering the 'state transition reason` message.

**Comment by mengesb** [comment]
Is it possible to not make the `iops` parameter required with `io1` volume_types? Could we just assume `${volume_size * 30}` for `iops` unless the user overrides this value?

**Comment by mylons** [comment]
I actually work with @aaronbrashears ! and ran into this issue as well, a year later =/ 
```
➜  repo git:(airflow_tweaks) ✗ terraform version
Terraform v0.6.14
```

I believe, for whatever reason, my ebs block:
```
  ebs_block_device = {
    device_name = "/dev/xvdi"
    volume_size = "${var.ebs_size}"
    #volume_type = "gp2"
  }
```
is prefering iops as the `volume_type` instead of `gp2`. Once I uncomment `gp2` it will work. It's quite likely that this aws account's iops limit is hit.

**Comment by ajvb** [comment]
Just hit this today.

Terraform output:
```
* aws_instance.dbserver: Error waiting for instance (i-01a31aa8844145a8e) to become ready: unexpected state 'terminated', wanted target 'running'. last error: %!s(<nil>)
```

Terraform version:
```
$ terraform version
Terraform v0.7.4
```

The reason was hitting an EBS-related limit. When viewing the terminated EC2 instance in the console, this was error message:
```
State transition reason: Client.VolumeLimitExceeded: Volume limit exceeded
```
```

**Comment by rmmcnulty9** [comment]
I was getting this error too. But for me the cause was the AMI I was using (Ubuntu 16.04) did not allow the device name I gave it. It took a long time to debug because Terraform and AWS had very unhelpful error messages. I went with a `/dev/sdb` for my device name and it worked perfectly.
