### ISSUE TITLE
error 403  while creating storage account in terraform author:maaloom 

### ISSUE THREAD

**Issue by maaloom** [hashicorp/terraform#25640]
provider "azurerm" {
  # Whilst version is optional, we /strongly recommend/ using it to pin the version of the Provider being used
  version = "=2.0.0"
  features {}
  subscription_id = "f34f3b71-55bb-4244-95d7-14f027fe40a8"
}

# Create a resource group
resource "azurerm_resource_group" "Prod" {
  name     = "myresourcegroup"
  location = "West Europe"
}
resource "azurerm_public_ip" "Prod" {  //Here defined the public IP
  name                         = "VMpublicIP"  
  location                     = "${azurerm_resource_group.Prod.location}"  
  resource_group_name          = "${azurerm_resource_group.Prod.name}"  
  allocation_method            = "Static"  
  idle_timeout_in_minutes      = 30  
  domain_name_label            = "myvm1"
}
# Create a virtual network within the resource group
resource "azurerm_virtual_network" "Prod" {
  name                = "myvnet"
  resource_group_name = "${azurerm_resource_group.Prod.name}"
  location            = "${azurerm_resource_group.Prod.location}"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "Prod" {
  name                 = "mysubnet"
  resource_group_name  = "${azurerm_resource_group.Prod.name}"
  virtual_network_name = "${azurerm_virtual_network.Prod.name}"
  address_prefix       = "10.0.2.0/24"
}
resource "azurerm_storage_account" "Prod" {
  name                     = "wedstracc"
  resource_group_name      = "${azurerm_resource_group.Prod.name}"
  location                 = "${azurerm_resource_group.Prod.location}"
  account_tier             = "Standard"
  account_replication_type = "GRS"
}
resource "azurerm_storage_account_network_rules" "Prod" {
  resource_group_name  = "${azurerm_resource_group.Prod.name}"
  storage_account_name = "${azurerm_storage_account.Prod.name}"

  default_action             = "Allow"
  ip_rules                   = ["127.0.0.1"]
  virtual_network_subnet_ids = [azurerm_subnet.Prod.id]
  bypass                     = ["Metrics"]
}
resource "azurerm_network_security_group" "Prod" {
  name                = "mydemo-nsg"
  location            = "${azurerm_resource_group.Prod.location}"
  resource_group_name = "${azurerm_resource_group.Prod.name}"

security_rule {   //Here opened remote desktop port
    name                       = "RDP"  
    priority                   = 110  
    direction                  = "Inbound"  
    access                     = "Allow" 
    protocol                   = "Tcp"  
    source_port_range          = "*"  
    destination_port_range     = "3389"  
    source_address_prefix      = "*"  
    destination_address_prefix = "*"  
  }
}

resource "azurerm_network_interface" "Prod" {
  name                = "vm1nic"
  location            = "${azurerm_resource_group.Prod.location}"
  resource_group_name = "${azurerm_resource_group.Prod.name}"

  ip_configuration {
    name                          = "internal"
    subnet_id                     = "${azurerm_subnet.Prod.id}"
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = "${azurerm_public_ip.Prod.id}"
  }
}

resource "azurerm_network_interface_security_group_association" "Prod" {
  network_interface_id      = "${azurerm_network_interface.Prod.id}"
  network_security_group_id = "${azurerm_network_security_group.Prod.id}"
}
resource "azurerm_windows_virtual_machine" "Prod" {
  name                = "myvm1"
  resource_group_name = "${azurerm_resource_group.Prod.name}"
  location            = "${azurerm_resource_group.Prod.location}"
  size                = "Standard_DS2_v2"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.Prod.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-Datacenter"
    version   = "latest"
  }
}

Getting this below error after terraform apply command.   

Error: Error reading static website for AzureRM Storage Account "wedstracc": accounts.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationPermissionMismatch" Message="This request is not authorized to perform this operation using this permission.\nRequestId:d0d4fa74-401e-0069-3f4e-600f83000000\nTime:2020-07-22T17:33:21.0152511Z"

"""""Please someone help me ot to fix this""'

**Comment by apparentlymart** [comment]
Hi @maaloom,

This seems related to the Azure provider rather than to Terraform Core. Issues in this repository are only for capturing bug reports and enhancement requests for Terraform Core, and so we can't help with the behaviors of individual providers here.

Instead, I'd suggest asking this question in [the Azure provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34), where the participants are more familiar with the details of Azure services and the Azure provider.

Thanks!

**Comment by maaloom** [comment]
hi i changed azurerm version from 2.0.0 to 2.1.0 & got resolved.
