### ISSUE TITLE
Terraform Plan/Apply can be executed without internet connectivity?

### ISSUE THREAD

**Issue by goyalvickey78** [hashicorp/terraform#25654]
### Terraform Version

```
...0.12.29
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

```
Terraform Plan/Apply should work without internet
```
### Actual Behavior

```
Terraform init command is run when I have internet connectivity with the box. Then trying to run terraform Plan/Apply without internet connectivity; then not able to run command.
```
### Steps to Reproduce

```
I want to execute the Terraform script on closed environment; where internet connectivity will not be provided.

Initially; terraform init command got executed with the internet connectivity and all plugins are in placed(working for AWS).

Now I am trying to execute the terraform Plan/Apply command without internet connectivity and command got stuck unless until you forcefully kill the command.

I am going to create cloud resources on same account/VPC where terraform master/controller machine is there.

I assume; internet connectivity is required at any cost. Because AWS authentication and remote API calls require the same.
```
### Additional Context

```
Is there any way to run Terraform Plan/Apply command without having internet connectivity.
```

**Comment by apparentlymart** [comment]
Hi @goyalvickey78!

I think I already addressed this question [the community forum](https://discuss.hashicorp.com/t/terraform-plan-apply-execute-without-internet/11807/2). If you'd like to talk more about the details of setting that up for AWS, that would be an AWS-provider-specific question and so I'd suggest starting new topics in [the AWS provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where hopefully some participants are familiar with VPC endpoints and using them with Terraform.

Issues in this repository are only for bug reports and feature requests for Terraform Core, not for specific providers. If you'd like to report a bug or a feature request for the AWS provider, you can create an issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws). Thanks!
