### ISSUE TITLE
Terraform crash issue in azure pipeline when perform terraform apply

### ISSUE THREAD

**Issue by LayMui** [hashicorp/terraform#25679]
### Terraform Version

I added the following plugin for terraform CLI to azure devOps
Add plugin for terraform
Terraform 1 (https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks)
- Terraform 2 (https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform)

```
the log shows:
2020-07-26T11:23:27.3221310Z Task         : Terraform CLI
2020-07-26T11:23:27.3221813Z Description  : Execute terraform cli commands
2020-07-26T11:23:27.3222315Z Version      : 0.5.12
2020-07-26T11:23:27.3222759Z Author       : Charles Zipp
2020-07-26T11:23:27.3223197Z Help         : 
...
```

### Terraform Configuration Files

```terraform
provider "azurerm" {
  version = "~> 1.42"
  features {}
}

resource "azurerm_resource_group" "resource_group" {
  name     = "${var.resource_group}_${var.environment}"
  location = var.location
}

resource "azurerm_kubernetes_cluster" "terraform-k8s" {
  name                = "${var.cluster_name}_${var.environment}"
  location            = azurerm_resource_group.resource_group.location
  resource_group_name = azurerm_resource_group.resource_group.name
  dns_prefix          = var.dns_prefix

```

### Crash Output

https://gist.github.com/LayMui/6eaa93e31c4e26401f45e8cdd1e6181b

### Expected Behavior

It should able to perform terraform apply to create the k8s cluster

### Actual Behavior

The pipeline show terraform crashes

### Steps to Reproduce

Here is my azure-pipeline.yml to trigger the CI
trigger:
  - master
  
pool:
    vmImage: 'ubuntu-latest'
  
steps:
  - script: echo K8S Terraform Azure!
    displayName: 'Run a one-line script'

  - task: DownloadSecureFile@1
    name: publickey
    inputs:
      secureFile: 'id_rsa.pub'
  
  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    #  commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
      backendType: 'azurerm'
      backendServiceArm: 'azure-resource-manager-service-connection'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'terraform-backend-rg'
      backendAzureRmResourceGroupLocation: 'southeastasia'
      backendAzureRmStorageAccountName: 'storageacctlaymui'
      backendAzureRmContainerName: 'storageacctlaymuicontainer'
      backendAzureRmKey: 'kubernetes-dev.tfstate'

  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
      environmentServiceName: 'azure-resource-manager-service-connection'
      commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'

**Comment by LayMui-Toh** [comment]
this crash did not happen after
I remove the version line   version = "~> 1.42"
change become:
provider "azurerm" {
  features {}
}

Please close this ticket
