### ISSUE TITLE
EMR cluster 5.30.1 error

### ISSUE THREAD

**Issue by GLOBE1984** [hashicorp/terraform#25673]
I got error "Error waiting for EMR Cluster state to be "WAITING" or "RUNNING": TERMINATED_WITH_ERRORS: VALIDATION_ERROR: ServiceAccessSecurityGroup is missing ingress rule from EmrManagedMasterSecurityGroup on port 9443" while creating emr cluster with 5.30.1 version.

### Terraform Version

```
0.11.11
```

### Terraform Configuration Files

```terraform
resource "aws_emr_cluster" "emr_cluster" {
  name                   = "<cluster-name>"
  release_label          = "emr-5.30.1"
  service_role           = "<cluster-service-role>"
  security_configuration = "<security-configuration>"
  log_uri                = "<log-uri>"
  applications           = ["Ganglia", "Spark"]
  termination_protection = "false"


  ec2_attributes {
    key_name                          = "<ec2-key-pair>"
    subnet_id                         = "<subnet-id>"
    emr_managed_master_security_group = "<emr-master-security-group>"
    additional_master_security_groups = "<emr-additional-master-security-group>"
    emr_managed_slave_security_group  = "<emr-slave-security-group>"
    additional_slave_security_groups  = "<emr-additional-slave-security-group>"
    service_access_security_group     = "<service-security-group>"
    instance_profile                  = "<instance-profile>"
  }

  configurations_json = "<configuration-json-file>"

  master_instance_group {
    instance_type = "m4.large"
    instance_count = 3
  }

  core_instance_group {
    instance_type = "m4.large"
    instance_count = 3
  }

  ebs_root_volume_size   = 10

}
```

### Debug Output

2020-07-24T11:08:31.920-0500 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4.exe: 2020/07/24 11:08:31 [DEBUG] [aws-sdk-go] {"Cluster":{"Applications":[{"Name":"Spark","Version":"2.4.5"},{"Name":"Ganglia","Vers
ion":"3.7.2"}],"AutoScalingRole":"emr-perf-test-autoscaling-role-integ","AutoTerminate":false,"ClusterArn":"arn:aws:elasticmapreduce:eu-central-1:231381194550:cluster/j-33STO8FVQ0QA7","Configurations":[{"Classi
fication":"spark-defaults","Properties":{"spark.driver.extraJavaOptions":"-XX:+UseG1GC -XX:+UnlockDiagnosticVMOptions -XX:+G1SummarizeConcMark  -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:OnOutOf
MemoryError='kill -9 %p'","spark.executor.extraJavaOptions":"-XX:+UseG1GC -XX:+UnlockDiagnosticVMOptions -XX:+G1SummarizeConcMark  -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:OnOutOfMemoryError='
kill -9 %p'","spark.sql.files.maxPartitionBytes":"64M"}}],"EbsRootVolumeSize":10,"Ec2InstanceAttributes":{"AdditionalMasterSecurityGroups":["sg-08ea22b8b2f1e23d6"],"AdditionalSlaveSecurityGroups":["sg-08ea22b8b
2f1e23d6"],"Ec2KeyName":"int-emr-cluster-instance-key-pair","Ec2SubnetId":"subnet-091e0d106480b1263","EmrManagedMasterSecurityGroup":"sg-055f8b3ecb378bf60","EmrManagedSlaveSecurityGroup":"sg-02a1d37387dfc9e1a",
"IamInstanceProfile":"arn:aws:iam::231381194550:instance-profile/emr-perf-test-cluster-ec2-profile-integ","RequestedEc2AvailabilityZones":[],"RequestedEc2SubnetIds":["subnet-091e0d106480b1263"],"ServiceAccessSe
curityGroup":"sg-08ea22b8b2f1e23d6"},"Id":"j-33STO8FVQ0QA7","InstanceCollectionType":"INSTANCE_GROUP","KerberosAttributes":{},"LogUri":"s3n://emr-perf-test-logs/","Name":"integ-emr-perf-test-cluster","Normalize
dInstanceHours":0,"ReleaseLabel":"emr-5.30.1","ScaleDownBehavior":"TERMINATE_AT_TASK_COMPLETION","SecurityConfiguration":"emr-perf-test-security-config","ServiceRole":"arn:aws:iam::231381194550:role/emr-perf-te
st-cluster-role-integ","Status":{"State":"TERMINATED_WITH_ERRORS","StateChangeReason":{"Code":"VALIDATION_ERROR","Message":"ServiceAccessSecurityGroup is missing ingress rule from EmrManagedMasterSecurityGroup
on port 9443"},"Timeline":{"CreationDateTime":1.595606881001E9,"EndDateTime":1.595606887473E9}},"StepConcurrencyLevel":1,"Tags":[{"Key":"mdsp-team","Value":"SEA Plano Team 1"},{"Key":"mdsp-area","Value":"SEA"},
{"Key":"mdsp-environment","Value":"int"},{"Key":"Name","Value":"integ-emr-perf-test-cluster"},{"Key":"mdsp-services","Value":"edi"}],"TerminationProtected":true,"VisibleToAllUsers":true}}
2020-07-24T11:08:31.920-0500 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4.exe: 2020/07/24 11:08:31 [DEBUG] EMR Cluster status (j-33STO8FVQ0QA7): TERMINATED_WITH_ERRORS
2020/07/24 11:08:31 [TRACE] root.emr: eval: *terraform.EvalWriteState
2020/07/24 11:08:31 [TRACE] root.emr: eval: *terraform.EvalApplyProvisioners
2020/07/24 11:08:31 [TRACE] root.emr: eval: *terraform.EvalIf
2020/07/24 11:08:31 [TRACE] root.emr: eval: *terraform.EvalWriteState
2020/07/24 11:08:31 [TRACE] root.emr: eval: *terraform.EvalWriteDiff
2020/07/24 11:08:31 [TRACE] root.emr: eval: *terraform.EvalApplyPost
2020/07/24 11:08:31 [ERROR] root.emr: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_emr_cluster.emr_cluster: Error waiting for EMR Cluster state to be "WAITING" or "RUNNING": TERMINATED_WITH_ERRORS: VALIDATION_ERROR: ServiceAccessSecurityGroup is missing ingress rule from EmrManagedMaste
rSecurityGroup on port 9443
2020/07/24 11:08:31 [ERROR] root.emr: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_emr_cluster.emr_cluster: Error waiting for EMR Cluster state to be "WAITING" or "RUNNING": TERMINATED_WITH_ERRORS: VALIDATION_ERR
OR: ServiceAccessSecurityGroup is missing ingress rule from EmrManagedMasterSecurityGroup on port 9443
RR] plugin: plugin server: accept tcp 127.0.0.1:10000: use of closed network connection
2020-07-24T11:08:31.941-0500 [DEBUG] plugin.terraform.exe: local-exec-provisioner (internal) 2020/07/24 11:08:31 [ERR] plugin: plugin server: accept tcp 127.0.0.1:10002: use of closed network connection
2020-07-24T11:08:31.941-0500 [DEBUG] plugin.terraform.exe: local-exec-provisioner (internal) 2020/07/24 11:08:31 [DEBUG] plugin: waiting for all plugin processes to complete...

### Expected Behavior

Cluster should be created successfully.

### Actual Behavior

Error out

### Steps to Reproduce

terraform init
terraform apply --auto-approve=true

**Comment by apparentlymart** [comment]
Hi @GLOBE1984,

These error messages seem to be coming from the Terraform AWS provider rather than from Terraform Core. Issues in this repository are only for tracking bug reports and feature requests related to the Terraform Core (provider-agnostic) functionality, so I'm going to close this.

I'd suggest starting a new topic in [the AWS provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) to discuss this problem. The participants there are much more familiar with different AWS services than the Terraform Core maintainers who monitor issues in this repository. Thanks!

**Comment by GLOBE1984** [comment]
Thanks for reminding @apparentlymart.
