### ISSUE TITLE
Add support for user configured state object names in swift containers for Terraform v0.11

### ISSUE THREAD

**Issue by sapeish** [hashicorp/terraform#25684]
### Current Terraform Version

```
v0.11.13
```

### Use-cases
We have several separate pipelines each with it's own tfstate file. Right now the only way to organize tfstate files in Swift backend is having a different container name per process and having a very long and descriptive container name. So we have 20 containers each with a single tfstate file since we cannot control the filename. Right now we have:
```
tfstate-serviceW-process1-pipelineY-environmentZ/tfstate.tf
tfstate-serviceW-process2-pipelineY-environmentZ/tfstate.tf
tfstate-serviceW-process3-pipelineY-environmentZ/tfstate.tf
tfstate-serviceW-process4-pipelineY-environmentZ/tfstate.tf
tfstate-serviceW-process5-pipelineY-environmentZ/tfstate.tf
tfstate-serviceW-process6-pipelineY-environmentZ/tfstate.tf
tfstate-serviceW-process7-pipelineY-environmentZ/tfstate.tf
..
..
..
```

If we could control the filename we could better organize our files in a single container like:
```
tfstate-files/serviceW/processX/pipelineY/environmentZ/tfstate.tf
```

### Attempted Solutions
No workaround for Terraform v0.11

### Proposal
- There is a commit with this improvement already, so my proposal is to merge the commit https://github.com/hashicorp/terraform/pull/17465/commits/cd7bfba1416f1fd2d8b04671735ab7e236d918e8 for Terraform v0.11 which is already included in v0.12.4 and above. See previously merged PR https://github.com/hashicorp/terraform/pull/17465

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. 

Unfortunately, we are no longer maintaining Terraform `0.11` and have no plans to release any updates to it. We recommend upgrading to Terraform `0.13` (via Terraform `0.12` first). Terraform `0.14` is expected to be generally available at the beginning of December. 

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
