### ISSUE TITLE
Terraform `init` Not Loading Custom Provider From Vendor Directory

### ISSUE THREAD

**Issue by kevinbirch** [hashicorp/terraform#25685]
### Terraform Version

```
Terraform v0.12.29
+ provider.google v3.29.0
+ provider.google-beta v3.29.0
+ provider.helm v1.2.3
+ provider.kubernetes v1.11.3
+ provider.local v1.4.0
+ provider.mysql v1.9.0
+ provider.null v2.1.2
+ provider.postgresql v1.7.0
+ provider.random v2.3.0
+ provider.tls v2.1.1
```

### Terraform Configuration Files

Not really applicable in this case, but I have a provider declaration for my custom provider.

```terraform
provider "hush" {
# ...
}
```

Here is the layout of the `terraform.d` directory in the root module:

```
$ tree terraform.d
terraform.d
└── plugins
    ├── darwin-amd64
    │   └── terraform-provider-hush_v0.5.0
    └── linux-amd64
        └── terraform-provider-hush_v0.5.0
```

### Debug Output

https://gist.github.com/kevinbirch/5cb9a9c17c9eca38c1906f1d8aa8bd48 (encrypted using the [Hashcorp public GPG key](https://www.hashicorp.com/security#secure-communications)).

### Expected Behavior

I expected that the custom provider I installed "vendor" directory [described in the documentation](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations) would be loaded and used.  I have successfully used this exact method before, so I'm not sure why it's not working this time.

Looking at the debug logs it seems that the `terraform.d` directory is not being searched.  At least it isn't listed in any of the "checking for provider" lines.

### Actual Behavior

We receive the typical "can't find provider error message":

```
Provider "hush" not available for installation.

A provider named "hush" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

Error: no provider exists with the given name
```

### Steps to Reproduce

1. Install a new provider in the ["vendor" directory described in the documentation](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations).
2. Add the appropriate provider declaration block.
3. Run `terraform init`
4. Observe failure.

### Additional Context

I understand that there are other locations where custom providers can be installed but given that all this is being completely overhauled for 0.13 I want to do the simplest thing for right now which is "vendoring" my custom provider.  All the other locations are impractical for our environment where many people work with the same Terraform code using only the CLI.  Moving to 0.13 is not an option for us until it is released.

**Comment by alisdair** [comment]
```
$ tree terraform.d
terraform.d
└── plugins
    ├── darwin-amd64
    │   └── terraform-provider-hush_v0.5.0
    └── linux-amd64
        └── terraform-provider-hush_v0.5.0
```

I am pretty sure that the OS/arch directories should be `darwin_amd64` and `linux_amd64` (underscores, not dashes). Could you check and see if that solves the problem?

**Comment by kevinbirch** [comment]
Yes, you're correct and I noticed that as well the moment after I submitted the issue 🤦.  Thank you for the quick response.
