### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dustin-H** [hashicorp/terraform#2569]
While trying out terraform (the official [get started](https://www.terraform.io/intro/getting-started/build.html)) there were some issues in my local network. So terraform got a timeout error for every request. However it is not easy to understand the problem by just reading the error message. May this should be changed.

`panic: runtime error: invalid memory address or nil pointer dereference`

![screen shot 2015-06-30 at 13 50 59](https://cloud.githubusercontent.com/assets/6003519/8430171/1d394ac0-1f2f-11e5-8455-b69a56dc0eaf.png)
`/*  plus about 100-200 lines */`
![screen shot 2015-06-30 at 13 52 25](https://cloud.githubusercontent.com/assets/6003519/8430186/5014f73c-1f2f-11e5-9647-50f8826594f6.png)

**Comment by joekhoobyar** [comment]
My guess would be that this is fixed if you build from master - because it is using a newer aws-sdk.  Can anyone validate this?

**Comment by mitchellh** [comment]
That is correct, this was an upstream bug that shuld now be fixed.
