### ISSUE TITLE
Latest and Light docker image are still 0.12.28

### ISSUE THREAD

**Issue by Nainterceptor** [hashicorp/terraform#25693]
Dear team,

In docker tags, I can see that 0.12.29 is published, but latest and light seems to be 0.12.28.
Easy comparaison : latest & light has been published a month ago. 0.12.29 has been published 6 days ago.

Thanks for your help :)

**Comment by alisdair** [comment]
Thanks for reporting this! This was due to a bug in our automated release process which has now been fixed. We've also manually pushed the tags so that latest and light both point at 0.12.29.
