### ISSUE TITLE
aws_appsync_graphql_api is missing cache options

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform#25701]
![Screenshot from 2020-07-30 11-29-06](https://user-images.githubusercontent.com/64852480/88900470-13d67c00-d258-11ea-994c-ef7a0758e2b5.png)

### Current Terraform Version

```
Terraform v0.13.0-beta3
```

**Comment by bflad** [comment]
Hi @mgzenitech 👋  Thank you for submitting this. Please note that provider resources are managed separately from this repository, which is just for the core logic of Terraform. I'm going to have our bot automatically migrate this issue over to the Terraform AWS Provider repository, where that team can triage this issue appropriately.
