### ISSUE TITLE
panic: runtime error: index out of range terraform crashes

### ISSUE THREAD

**Issue by hkamat** [hashicorp/terraform#25709]
**Terraform version:**
Terraform v0.12.29

**Issue Description**
Running terraform to create a simple resource group results in terraform crashing. 

**Terraform actual output**
[crash.log](https://github.com/hashicorp/terraform/files/5002678/crash.log)

**Probable Cause**
I had copied some of the variable information in the json file from microsoft one note. This caused some special characters to appear which were not directly visible.
As I kept using json terraform kept crashing. Once I moved to tfvars file I got errors saying unrecognised 
 characters [it did not show which character though] properly from terraform.
![terraformtfvarsmsg](https://user-images.githubusercontent.com/14257733/88953416-8c6c2580-d2b6-11ea-9747-1da9da54ef6c.png)

**Expected Output**
Similar to tfvars as input i should get an error message for json file also and terraform should not crash.
![terraformvscodecharsjson](https://user-images.githubusercontent.com/14257733/88953614-cccba380-d2b6-11ea-862f-15fc7559d0de.png)

**JSON File**
[terraform.tfvars.log](https://github.com/hashicorp/terraform/files/5004846/terraform.tfvars.log)

**Comment by alisdair** [comment]
Thanks for reporting this crash. Could you upload the exact JSON file which causes the panic (after removing any sensitive data)?

**Comment by hkamat** [comment]
Done. Edited in the original comment for future reference.
Missed to do this before. Couldn't upload as .json so changed to .log

**Comment by alisdair** [comment]
This crash has been fixed as of 0.13.0-rc1, which now displays a more useful error diagnostic. The upstream pull request fixing this is https://github.com/hashicorp/hcl/pull/358. Here's the result:

![image](https://user-images.githubusercontent.com/68917/89039959-ee597900-d310-11ea-9193-33a201ebea23.png)

I think this is a pretty reasonable diagnostic, which would hopefully have been more helpful in identifying this invalid whitespace. 

Closing out. Thanks again for reporting!
