### ISSUE TITLE
Terraform 0.13-rc1 incorrect destroy cycle (glitched on provider)

### ISSUE THREAD

**Issue by JakubWojtowicz-TomTom** [hashicorp/terraform#25715]
Terraform is able to correctly create environment however it is unable to destroy it.
Each time destroy command is executed I'm receiving "Error: Cycle: ..."

My analysis so far shows that the problem is a provider (kubernetes/helm in my case) that is configured based on the output of a submodule (or a resource in general).
It's quite easy to reproduce however posting complete code would be too verbose.
My case is:
1. Create EKS or AKS cluster using aws or azurerm provider.
2. Use output from step 1. to configure Kubernetes provider.
3. Create some Kubernetes resource (e.g. namespace).
4. Try to destroy what you have just created.

If I'm not using the output from step 1. to configure provider (leave config block empty) and point my kubeconfig to that cluster everything works just fine. The root cause seem to be in dependency graph if there is a provider in the middle.

Example cycle error:
```
Error: Cycle: module.eks.module.node_group.aws_iam_role_policy_attachment.iam_eks_node_AmazonEC2ContainerRegistryReadOnly (destroy)
 module.eks.module.node_group.aws_iam_role_policy_attachment.iam_eks_node_AmazonEKSWorkerNodePolicy (destroy)
 module.eks.module.node_group.aws_iam_role.iam_eks_node (destroy)
 module.eks.module.node_group.data.aws_caller_identity.current (destroy)
 module.eks.module.node_group.aws_eks_node_group.eks_managed_node_group[1] (destroy)
 module.eks.module.node_group.aws_eks_node_group.eks_managed_node_group[0] (destroy)
 module.eks.module.node_group.data.aws_availability_zones.available (destroy)
 module.eks.module.node_group.aws_iam_role_policy_attachment.iam_eks_node_AmazonEKS_CNI_Policy (destroy)
 module.eks.module.node_group.data.aws_region.current (destroy)
 module.eks.module.node_group.aws_iam_role_policy_attachment.iam_eks_node_autoscaling (destroy)
 module.eks.module.node_group.aws_iam_policy.iam_eks_node_asg (destroy)
 module.eks.output.kubernetes_token (expand)
 module.eks.output.kubernetes_cluster_ca_certificate (expand)
 provider["registry.terraform.io/hashicorp/helm"]
 module.helm_packages.module.ingress[0].helm_release.ingress (destroy)
 module.helm_packages.module.ingress[0].kubernetes_namespace.ingress (destroy)
 module.eks.module.node_group.data.aws_iam_policy_document.iam_policy_document_asg (destroy)
 module.eks.module.node_group (close)
 module.eks.output.kubernetes_host (expand)
 provider["registry.terraform.io/hashicorp/kubernetes"]
 module.helm_packages.module.ingress[0].module.ingress_controller_tls_secret.kubernetes_secret.secret (destroy)
```

### Terraform Version
v0.13.0-rc1

### Expected Behavior
Terraform should destroy resources in reverse (in respect to creation) order.

### Actual Behavior
Error

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform destroy`

### Additional Context
I'm running Terraform on local machine with Ubuntu 20.04 system.

**Comment by danieldreier** [comment]
@JakubWojtowicz-TomTom can Thanks for reporting this. I think this is probably a valid issue, and I'd like to reproduce it locally.

To do that, I have to be able to run this and run it on my workstation without inventing any details in order to be confident we're seeing the same behavior. As the Terraform Core engineering manager I don't manage Kubernetes clusters with Terraform frequently, so me inventing these details would be a pretty significant amount of work.

Can you please restate your reproduction case such that I can run it and see this error happen? If it's too much to paste into the issue, you could make a PR against https://github.com/danieldreier/terraform-issue-reproductions or put it in a git repo of your own and I'm happy to clone it.

**Comment by JakubWojtowicz-TomTom** [comment]
@danieldreier I've managed to reproduce the issue, but I'm pretty sure it was user fault.

The scenario for reproduction looks as follows:
We have 4 modules A, B, C and D.
B and C depend on A.
C depends on B.
D consists of A, B and C.
Output from D depends implicitly on output from B (output forwarded to another output) and explicitly depends on C (I guess this is the point where we had the cycle).

Output from D was used to configure Kubernetes/Helm provider thus the issue was kind of obscured.
After removing (incorrect) depends_on in the output section everything works as intended.

Lesson learned - we need better code review.

**Comment by jbardin** [comment]
This appears to be resolved, closing.

Thanks!
