### ISSUE TITLE
Add -dry-run option for terraform import

### ISSUE THREAD

**Issue by jaksky** [hashicorp/terraform#25713]
### Current Terraform Version

```
v0.12.26
```

### Use-cases

Validate the command before actually running it. I would expect that the provider part will be run, state will be validated as well but not modified.

### Attempted Solutions

There is currently no way to achieve it AFAIK unless you actually run the command and manipulate the state immediately. 

### Proposal

Extend
```
terraform import [options] ADDR ID
```
with option -dry-run

**Comment by psilva261** [comment]
Hi, I'd also be interested in such a command. Probably it shouldn't be so much effort to realize it so I wonder if it's worth creating a pull request

**Comment by dreinhardt-terminus** [comment]
Our company uses terraform import a lot and this would be extremely useful

**Comment by yo1-markenstein** [comment]
+1 to have this

**Comment by yshollander-selerity** [comment]
+1.  I'm importing a complex manually created setup, and would be great to dry-run resource by resource.

**Comment by jlusterlvx** [comment]
+1

**Comment by crw** [comment]
Thanks for your interest in this issue! This is just a reminder to please avoid "+1" comments, and to use the upvote mechanism (click or add the 👍 emoji to the original post) to indicate your support for this issue. Thanks again for the feedback!

**Comment by hawk-luca-ricchi** [comment]
+1

**Comment by felixlut** [comment]
[Terraform Import Blocks](https://developer.hashicorp.com/terraform/language/import) largely solves this issue for me. 

`terraform plan` with an import block will say whether the import will work or not, as well as if any fields will be changed. Eg:

![image](https://github.com/hashicorp/terraform/assets/34520175/ba1d5037-6f69-4f3f-bf9d-d67a7cbb5043)
