### ISSUE TITLE
Terraform 0.13-rc1 environment variable TF_INPUT is not working

### ISSUE THREAD

**Issue by dungdm93** [hashicorp/terraform#25710]
### Terraform Version
```bash
$ terraform --version
Terraform v0.13.0-rc1
```

### Terraform Configuration Files
```terraform
terraform {
  required_version = ">= 0.13"

  required_providers {
    postgresql = {
      source  = "terraform-providers/postgresql"
      version = "~> 1.5"
    }
  }
}

locals {
  postgres_host = "localhost"
  postgres_port = 5432
}

provider "postgresql" {
  host    = local.postgres_host
  port    = local.postgres_port
  sslmode = "disable"
  # username = env.PGUSER
  # password = env.PGPASSWORD
}
```

### Steps to Reproduce
```bash
terraform init
terraform plan

export TF_INPUT=false
terragrunt apply
```
![Screenshot from 2020-07-31 12-13-35](https://user-images.githubusercontent.com/6848311/89002452-4f8c4700-d327-11ea-855b-75ef96728aac.png)

Terraform shouldn't prompts when `TF_INPUT=false` is setted.

**Comment by alisdair** [comment]
The [`TF_INPUT` environment variable disables prompts for input variable values](https://www.terraform.io/docs/commands/environment-variables.html#tf_input). The configuration example in your report does not include any variables, so it will have no effect.

I verified that `TF_INPUT` is working correctly in 0.13.0-rc1:

```shellsession
$ cat main.tf
variable "aleph" {
  type = number
}

resource "null_resource" "none" {
  count = var.aleph
}
$ export TF_INPUT=false
$ terraform apply

Error: No value for required variable

  on main.tf line 1:
   1: variable "aleph" {

The root module input variable "aleph" is not set, and has no default value.
Use a -var or -var-file command line argument to provide a value for this
variable.
```

Perhaps what you are looking for is the [`-auto-approve` flag for the apply command](https://www.terraform.io/docs/commands/apply.html#auto-approve), which will skip the confirmation prompt.

**Comment by dungdm93** [comment]
Thanks. It's my mistake.
