### ISSUE TITLE
Delcare variables (multiple or group of variable) if condition is true

### ISSUE THREAD

**Issue by opensourcejunkie101** [hashicorp/terraform#25726]
Hi,

I'm trying to declare multiple local variables if another given variable is set to true,

```
variable "db_type" {
  description = "Database type, allowed values, paas, iaas"
}

locals {
if var.db_type == "paas"; then
  db_name = "paasdb-dev01"
  db_disk = "some_value"
  db_tier = "some_value"

elif var.db_type == "iaas"; then
  db_name = "iaasdb-dev01"
  db_disk = "some_value"
  db_machine_type = "some_value"
}
```
Is there anyway to achieve the above, an alternate method or something?

Thanks for any help provided in this regard.

**Comment by apparentlymart** [comment]
Hi @opensourcejunkie101,

The usual way to write something like this in Terraform would be to create a map of objects that you can look up based on the `db_type` variable:

```hcl
locals {
  possible_database_settings = tomap({
    paas = {
      name         = "paasdb-dev01"
      disk         = "some_value"
      tier         = "some_value"
      machine_type = null
    }
    iaas = {
      name         = "iaasdb-dev01"
      disk         = "some_value"
      tier         = null
      machine_type = "some_value"
    }
  })
  database_settings = local.possible_database_settings[var.db_type]
}
```

Elsewhere in the module you can then access the attributes of this conditionally-set object as, for example, `local.database_settings.name`. I've set some of the attributes to `null` to reflect that they aren't relevant, which means you can assign those to optional resource arguments and have them be omitted when they are `null`.

If you have further questions about this, I recommend starting a new topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core/27), where we can work through some different variations of this idea if the exact solution I showed above doesn't meet your needs for some reason.

Thanks!
