### ISSUE TITLE
modules: github origin; allow ssh, not just https checkout

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#2572]
modules: github origin; allow ssh, not just https checkout

**Comment by radeksimko** [comment]
Could you be more specific?

I believe that SSH is actually supported, I use it heavily in private codebases I maintain.

Example that works:

```ruby
module "ecs" {
  source = "git@github.com:TimeIncOSS/tf_aws_ecs"
...
}
```

**Comment by pmoust** [comment]
@radeksimko: you are write, I must've made a typo. Sorry for wasting your time :)
