### ISSUE TITLE
Cannot target a resource inside a module with for_each

### ISSUE THREAD

**Issue by llomgui** [hashicorp/terraform#25748]
Hello,

I opened an issue #25186 with almost the same problem.
I cannot target a resource inside a module.

### Terraform Version

```
Terraform v0.13.0-rc1
```

### Terraform Configuration Files

https://github.com/hashicorp/terraform/tree/guide-v0.13-beta/module-repetition

### Expected Behavior

```
  # module.certificates["example.com"].tls_locally_signed_cert.cert will be created
  + resource "tls_locally_signed_cert" "cert" {
      + allowed_uses          = [
          + "server_auth",
        ]
      + ca_cert_pem           = "89786ea14e2fe52dfbabe2ce359cb7dd254c0c52"
      + ca_key_algorithm      = "RSA"
      + ca_private_key_pem    = (sensitive value)
      + cert_pem              = (known after apply)
      + cert_request_pem      = (known after apply)
      + early_renewal_hours   = 0
      + id                    = (known after apply)
      + ready_for_renewal     = true
      + validity_end_time     = (known after apply)
      + validity_period_hours = 24
      + validity_start_time   = (known after apply)
    }

```

### Actual Behavior

```

Warning: Resource targeting is in effect

You are creating a plan with the -target option, which means that the result
of this plan may not represent all of the changes requested by the current
configuration.
		
The -target option is not for routine use, and is provided only for
exceptional situations such as recovering from errors or mistakes, or when
Terraform specifically suggests to use it as part of an error message.


Warning: Applied changes may be incomplete

The plan was created with the -target option in effect, so some changes
requested in the configuration may have been ignored and the output values may
not be fully updated. Run the following command to verify that no other
changes are pending:
    terraform plan
	
Note that the -target option is not suitable for routine use, and is provided
only for exceptional situations such as recovering from errors or mistakes, or
when Terraform specifically suggests to use it as part of an error message.


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -target='module.certificates["example.com"].tls_locally_signed_cert.cert'`

**Comment by llomgui** [comment]
The error is here https://github.com/hashicorp/terraform/blob/master/addrs/resource.go#L146.

It compares "module.certificates.tls_locally_signed_cert.cert" == "module.certificates[\"example.com\"].tls_locally_signed_cert.cert"

to = `addrs.ConfigResource{targetable:addrs.targetable{}, Module:addrs.Module{"certificates"}, Resource:addrs.Resource{referenceable:addrs.referenceable{}, Mode:77, Type:"tls_locally_signed_cert", Name:"cert"}}`

r = `addrs.AbsResource{targetable:addrs.targetable{}, Module:addrs.ModuleInstance{addrs.ModuleInstanceStep{Name:"certificates", InstanceKey:"example.com"}}, Resource:addrs.Resource{referenceable:addrs.referenceable{}, Mode:77, Type:"tls_locally_signed_cert", Name:"cert"}}`

**Comment by jbardin** [comment]
Thanks for the extra research @llomgui,

You're correct that is the spot where the comparison is made, but that is not a comparison that should have been made (at least with the current way target addresses are handled). We may refactor the target addressing a bit in the future since parsing the target into an `AbsResource` is a bit of an anomaly now, and to allow for more generalized targeting to handle features like: #2182
