### ISSUE TITLE
shared_credentials_file config not considered

### ISSUE THREAD

**Issue by shahrakesh** [hashicorp/terraform#25758]
### Terraform Version

```
Terraform v0.12.29
+ provider.aws v3.0.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region                  = "eu-west-2"
  shared_credentials_file = "~/.aws/other_credentials"
}
data "aws_route53_zone" "domain" {
  name = var.domain
}

resource "aws_route53_zone" "sim" {
  name    = "sim.${var.domain}"
  tags    = var.tags
  comment = "sim"
}

resource "aws_route53_zone" "cos" {
  name    = "cos.${var.domain}"
  tags    = var.tags
  comment = "cos"
}

resource "aws_route53_record" "domain-to-sim" {
  name    = "sim"
  type    = "NS"
  zone_id = data.aws_route53_zone.domain.zone_id
  records = aws_route53_zone.sim.name_servers
  ttl     = 172800
}

resource "aws_route53_record" "domain-to-cos" {
  name    = "cos"
  type    = "NS"
  zone_id = data.aws_route53_zone.domain.zone_id
  records = aws_route53_zone.cos.name_servers
  ttl     = 172800
}

terraform {
  backend "s3" {
    bucket = "terraform-state"
    key    = "global/subdomains/terraform.tfstate"
    region = "eu-west-2"

    dynamodb_table = "terraform-up-and-running-locks"
    encrypt        = true
  }
}
```

### Debug Output

Debug output - https://gist.github.com/shahrakesh/7c89f8b74047af7e6da3d7637ad3f246

### Expected Behavior

Terraform should use the credentials file configured in shared_file_credentials option under provider block.

### Actual Behavior

Terraform ignores shared_file_credentials and instead looks for the default credentials file.

### Steps to Reproduce

1. Delete the default credentials file
2. Create new credentials file with different name, say "other_credentials"
3. Run terraform plan

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/8832

**Comment by danieldreier** [comment]
@shahrakesh are you saying that the `shared_file_credentials` setting doesn't work for the AWS provider, or the S3 backend? I see that the [issue you linked](https://github.com/terraform-providers/terraform-provider-aws/issues/8832) is about the S3 backend, but it sounds like you're reporting a bug similiar to [this one in the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/issues/103). Can you clarify whether you're talking about the backend or the provider?

**Comment by shahrakesh** [comment]
@danieldreier In my case, I get the error if I use S3 backend. If I don't use S3 backend (so no backend), then it works.

**Comment by shahrakesh** [comment]
A very simple script to recreate if it helps. This throws the same error if I delete the default credentials file but works if I remove the S3 backend block.

```
terraform {
  backend "s3" {
    bucket = "terraform-state"
    key    = "9999-test/terraform.tfstate"
    region = "eu-west-2"

    dynamodb_table = "terraform-up-and-running-locks"
    encrypt        = true
  }
}

provider "aws" {
  region  = "eu-west-2"
  shared_credentials_file = "~/.aws/test_credentials"
}
data aws_caller_identity current {}
output "aws_caller_info" {
  value = data.aws_caller_identity.current
}
```

**Comment by danieldreier** [comment]
Thanks! I've categorized this as an issue with the S3 backend, and the AWS provider team, who maintains that backend, will handle it from here.

**Comment by bflad** [comment]
Hi @shahrakesh 👋  To use a custom location for the AWS Shared Credentials file in the S3 Backend, the S3 Backend configuration must include the [`shared_credentials_file` argument](https://www.terraform.io/docs/backends/types/s3.html#shared_credentials_file). e.g.

```hcl
terraform {
  backend "s3" {
    # ... other configuration ...

    shared_credentials_file = "~/.aws/test_credentials"
  }
}
```

The S3 Backend configuration is wholly separate from the Terraform AWS Provider configuration, as they are unrelated pieces of functionality within Terraform. Can you please try adding that argument?

**Comment by shahrakesh** [comment]
Hi @bflad It still doesn't work unfortunately if the default credentials file is deleted.

> 2020/08/13 19:33:14 [INFO] Attempting to use session-derived credentials
> 
> Error: No valid credential sources found for AWS Provider.
>         Please see https://terraform.io/docs/providers/aws/index.html for more information on
>         providing credentials for the AWS Provider

**Comment by shahrakesh** [comment]
Hi, any update on this one? Just wondering if it's accepted as a bug or something not right in how we are using it.

**Comment by dstuck** [comment]
I've also just run into this issue. I'm specifying `shared_credentials_file` in the `backend "s3"` block. If I don't also specify a profile, terraform ignores the `shared_credentials_file` variable and looks in the default shared_credentials. If I do specify the profile in the block, I get the same `No valid credential sources found for AWS Provider` error after `Attempting to use session-derived credentials`
If I set a profile, remove the `shared_credentials_file` variable and copy the session credentials in to `~/.aws/credentials` from my custom location, I am able to successfully migrate to the s3 backend

**Comment by gijs3it** [comment]
I got the same issue. on Terraform 0.14.7 with AWS: 3.27.0

It works fine on the "regular" S3 configuration, but fails on the S3->Backend configuration.

Fallback to the default ~/.aws/credentials file is the only option then.

Maybe the title and original ticket should be changed that this is explicitly about the S3 Backend Configuration? @shahrakesh  can you do that?
@bflad and @danieldreier can you see if a fix is possible and mark this as a bug?

**Comment by ypismerov** [comment]
Only specifying AWS_PROFILE works for me, nothing else.
Terraform v0.14.9

**Comment by LyricL-Gitster** [comment]
I'm sad I missed the anniversary of this ticket. Really hope this gets worked out!

**Comment by tmegow** [comment]
Is there any hope for some progress on this issue?

**Comment by ctriegg-mak** [comment]
I've run into the same issue with the setup I'm currently working on. It would be good if the S3 backend supports the same authentication configuration options as the `aws` provider.

**Comment by gdavison** [comment]
There have been many changes to authentication since this issue was created, and there are more coming in v1.6. I'm going to close this issue. If you're still seeing this error, please open a new issue.
