### ISSUE TITLE
Support KMS usage with ECR

### ISSUE THREAD

**Issue by thelok** [hashicorp/terraform#25753]
Amazon recently added support for KMS with ECR:

https://aws.amazon.com/about-aws/whats-new/2020/07/ecr-supports-encryption-images-aws-kms-keys/

This feature request is to add support for configuring KMS options when using ECR.

**Comment by anarsen** [comment]
:point_right: https://github.com/terraform-providers/terraform-provider-aws

**Comment by trevorrea** [comment]
@thelok - this has been added in https://github.com/terraform-providers/terraform-provider-aws/pull/14520 and released as part of 3.1.0. You can close this issue.
