### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by elliottn** [hashicorp/terraform#25767]
### Terraform Version

```
Terraform v0.12.29
+ provider.vsphere v1.21.1
```

### Terraform Configuration Files

```terraform
provider "vsphere"{
  user = var.vsphere_user
  password = var.vsphere_password
  vsphere_server = var.vsphere_server

  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc"{
  name = "Lab"
}

data "vsphere_datastore" "datastore" {
  name          = "NFS"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = "Broadwell"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "Standard MGMT PG"
  datacenter_id = data.vsphere_datacenter.dc.id
}


data "vsphere_virtual_machine" "template" {
  name  = "Windows2019"
  datacenter_id = data.vsphere_datacenter.dc.id
}
/*
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus = 2
  memory   = 1024
  guest_id = data.vsphere_virtual_machine.template.guest_id

  scsi_type = data.vsphere_virtual_machine.template.scsi_type

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }

  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
91
    customize {

      network_interface {
        ipv4_address = "10.0.0.10"
        ipv4_netmask = 24
      }

      ipv4_gateway = "10.0.0.1"
    }
  }
}
*/

```

### Debug Output
https://gist.github.com/elliottn/1cfa3b33d37e86c9203b8c184ddaef7d

### Crash Output
https://gist.github.com/elliottn/cb1e22121063ae595c08652c9c3c74ba

### Expected Behavior
Expecting it to not panic

### Actual Behavior
Received a panic

### Steps to Reproduce
Please list the full steps required to reproduce the issue
1. `terraform init`
2. `terraform apply`

### Additional Context
I noticed this behavior only occurs when I have the vsphere_virtual_machine template block uncommented.  The name is correct and I do get an appropriate error when the name of the template is incorrect.  I am following https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html as a guide for how this configuration file should be written.

### References
#914

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the VSphere Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the VSphere provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
