### ISSUE TITLE
Terraform remote state push -force fails lineage check for S3 backend

### ISSUE THREAD

**Issue by ConnorGraham** [hashicorp/terraform#25761]
# Terraform Version
`v0.12.29`

# Expected Behavior
The state should be pushed to the remote and forced over any existing state

# Actual Behavior
```
$ tf state push -force B.tfstate
Failed to write state: cannot import state with lineage "c65f30fe-24db-19f7-43c8-bd29fb644be5" over unrelated state with lineage "bfeaceb5-75f6-5a22-5068-bc488243b268"
```

# Steps to reproduce
I am using an s3 backend
```
terraform {
  backend "s3" {
    bucket = "my-terraform-state"
    region = "us-east-1"
  }
}
```
```
terraform workspace new A || terraform workspace select A
terraform apply -auto-approve
terraform state pull > A.state

terraform workspace new B || terraform workspace select B
terraform apply -auto-approve
terraform state pull > B.state

terraform workspace select A
terraform state push -force B.state
```

# References
#5663
#15674
#24916

**Comment by ConnorGraham** [comment]
For those who come across this issue. I worked around it by using `jq` to manually update the `lineage` and `serial` properties
```
A_LINEAGE=$(cat A.state | jq .lineage)
A_SERIAL=$(cat A.state | jq .serial)
B_LINEAGE=$(cat B.state | jq .lineage)
B_SERIAL=$(cat B.state | jq .serial)

mv A.state temp.json
jq -r ".lineage |= ${B_LINEAGE}" temp.json > A.state
jq -r ".serial |= ${B_SERIAL}" temp.json > A.state

mv B.state temp.json
jq -r ".lineage |= ${A_LINEAGE}" temp.json > B.state
jq -r ".serial |= ${A_SERIAL}" temp.json > B.state

terraform workspace select A
terraform state push B.state

terraform workspace select B
terraform state push A.state
```

**Comment by pselle** [comment]
@ConnorGraham Not all backends support the `-force` flag, and I believe S3 is one of these backends.

This feature was added for the Terraform Cloud remote backend in this PR: https://github.com/hashicorp/terraform/pull/24696/files. I'm going to mark this as an enhancement for those who maintain the S3 backend, or should you be interested in implementing this feature for the S3 backend.

**Comment by pselle** [comment]
An update here: I believe I made a mistake associating this with the remote backend work, and that this is a bug and should be classified as such. I am updating the issue accordingly.
