### ISSUE TITLE
BucketRegionError: incorrect region, the bucket is not in 'us-east-2' region at endpoint ''

### ISSUE THREAD

**Issue by Eliasi1** [hashicorp/terraform#25782]
Terraform and other providers Version

Terraform v0.12.29
+ provider.aws v3.1.0       
+ provider.cloudflare v2.0.0
+ provider.template v2.1.2  

Affected Resource(s)

    s3

Terraform Configuration Files

s3_cluster_files.tf:

    resource "aws_s3_bucket" "ecs_bucket" {
      bucket = "${var.brand_name}-ecs-files"
      acl = "private"
      force_destroy = true
      versioning {
        enabled = true
      }
    }

    resource "aws_s3_bucket_object" "put_prometheus" {
      bucket = "${aws_s3_bucket.ecs_bucket.id}"
      key    = "${path.module}/prometheus/prometheus.yml"
      source = "${path.module}/files/prometheus.yml"
      content_type = "text"
      acl = "private"
      }

provider.tf:

    provider "aws" {
      region     = "us-east-2"
    }

backend.tf:

    terraform {
      backend "s3" {
        encrypt        = false
        key            = "ecs/terraform.tfstate"
        region         = "us-east-2"
        bucket         = "wp-tf-state-devops"
        dynamodb_table = "wp-tf-state-devops-db"
      }
    }

Output

    Error: Error putting object in S3 bucket (eliasi.club-ecs-files): BucketRegionError: incorrect region, the bucket is not in 'us-                     east-2' region at endpoint ''
        status code: 301, request id: , host id:

      on ..\..\..\..\..\..\modules\aws\ecs\cluster\1.0.0\S3_cluster_files.tf line 10, in resource "aws_s3_bucket_object"  "put_prometheus":
  10: resource "aws_s3_bucket_object" "put_prometheus" {

Expected Behavior

Should put prometheus.yml file in S3 bucket

Actual Behavior

Fails with error BucketRegionError

Steps to Reproduce

    terraform plan
    terraform apply

Important Factoids

The AWS provider resource is configured to use us-east-2 as that is where we would like to provision. The S3 bucket is in us-east-2 and so the ECS cluster. in fact, the whole project is build in the same region, no other region is mentioned anywhere. I have tried to delete ./terraform folder and recreate. i have looked for a solution over google but no luck.

**Comment by Eliasi1** [comment]
state file on bucket resource: 
![image](https://user-images.githubusercontent.com/58950564/89771441-fc757980-db08-11ea-823f-d6dfeb393067.png)

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
