### ISSUE TITLE
Cannot remove last data resource without empty provider (0.13)

### ISSUE THREAD

**Issue by dghubble** [hashicorp/terraform#25795]
# Terraform Version

```
Terraform v0.13.0
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    ct = {
      source = "poseidon/ct"
      version = "0.6.1"
    }
  }
}

data "ct_config" "worker" {
  content = ""
}
```

### Debug Output

https://gist.github.com/dghubble/bbc86815e821f8dc78d57799ec91cfd7

### Expected Behavior

Apply can remove the worker config data from Terraform state.

### Actual Behavior

```
Error: Provider configuration not present

To work with data.ct_config.worker its original provider configuration at
provider["registry.terraform.io/poseidon/ct"] is required, but it has been
removed. This occurs when a provider configuration is removed while objects
created by that provider still exist in the state. Re-add the provider
configuration to destroy data.ct_config.worker, after which you can remove the
provider configuration again.
```

### Steps to Reproduce

```
terraform init
terraform apply
```

Next remove the `data` block (comment it or delete). Any subsequent `plan` or `apply` operations with the message above.

```
terraform apply
```

### Additional Context

* Workaround is to keep at least one usage of the provider around, since this behavior only seems to be triggered when removing the last usage of a Terraform provider
* Terraform v0.13 [upgrade guide](https://github.com/hashicorp/terraform/blob/master/website/upgrade-guides/0-13.html.markdown#explicit-provider-source-locations) has a similar message, but suggests this occurs from not running `terraform apply` before removing the resource.

### References

* https://github.com/hashicorp/terraform/issues/25719 - similar but specific to terraform_remote_data resource

**Comment by dghubble** [comment]
The provider takes no inputs, but having an empty provider block does also workaround the problem. Since the most common providers are cloud providers that accept credentials, I imagine most testing expects them to be there. 

```
provider "ct" {}
```

Not sure if this is expected for all providers or whether this is a bug.

**Comment by davicdsalves** [comment]
Had the same problem but using **terraform_remote_state**, thank you for the empty provider hint, I could finally delete a remote state I'm no longer using after upgrading to 0.13.
I also had to add the explicity provider for terraform in versions.tf
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    terraform = {
      source = "terraform.io/builtin/terraform"
    }
  }
  required_version = ">= 0.13"
}
```
And then declared an empty provider in my tf file as you suggested @dghubble 
```
provider "terraform" {}
```
With this I could remove the **data "terraform_remote_state"**

**Comment by sdebruyn** [comment]
We have the same issue with the null and the local providers. Even adding an empty block didn't solve the issue for us.

```
provider "local" {}
```

**Comment by mildwonkey** [comment]
Hi, the original reported workaround is the expected [and documented](https://www.terraform.io/docs/configuration/modules.html#providers-within-modules) behavior: terraform needs the provider configuration inside the module.

@sdboyer If you are experiencing this error and you *do* have the `provider` block inside a module, that's a different problem - please open a new Github issue and fill out the issue template entirely, including a configuration that reproduces the issue and your debug logs. 

Thanks!
