### ISSUE TITLE
terraform cannot compare `[]` to an empty list; requires `tolist([])`

### ISSUE THREAD

**Issue by mildwonkey** [hashicorp/terraform#25798]
### Terraform Version
v0.13.0 (build from master)

### Terraform Configuration Files

```terraform
variable empty_list {
  type = list      // same result if type = list(string)
  default = []
}
```

### Debug Output
I feel both qualified and empowered to say it's not helpful.

### Crash Output
n/a

### Expected Behavior
```bash
terraform console
> var.empty_list
[]
> var.empty_list == []
true
```

### Actual Behavior

```bash
terraform console
> var.empty_list
[]
> var.empty_list == []
false
```

### Steps to Reproduce
same as 'actual behavior': `terraform console`

### Additional Context
Now if you remove the `type` attribute from the variable, the comparison works as expected:
```hcl
variable empty_list {
  default = []
}
```

```bash
terraform console
> var.empty_list
[]
> var.empty_list == []
true
```

### Explanation
This behavior occurs because `[]` is an empty _tuple_, not a list, and so when the variable type is explicitly declared as a *list*, the comparison does not work. When the type is removed, `[]` matches the *assumed* variable type, which is `tuple` (thanks @alisdair!)
Note that this comparison works:

```
> var.empty_list == tolist([])
true
``` 

This seems unintuitive I'd expect that it will lead to many questions from users (wearing my user hat I can say this would infuriate me, especially given that I could not easily find documentation to explain it). Note that the behavior is the same within a configuration:
```hcl
output "test" {
  value = var.empty_list == []
}
``` 

```bash
Outputs:

test = false
```

Given that you can write `default = []`, why can't you compare `var.empty_list == []`? I'd almost rather users were required to write `default = tolist([])` so that it's explicit from the start.

There's a hint of a reference to a thing that looks like a list being a tuple in the [Type Constraints Documentation](https://www.terraform.io/docs/configuration/types.html#dynamic-types-the-quot-any-quot-constraint); at minimum we might want to extend this section to make explicit that `[]` is not actually a list:

> If the given value were ["a", "b", "c"] -- whose physical type is tuple([string, string, string]), Terraform analyzes this as follows:

**Comment by apparentlymart** [comment]
I've helped a few folks with this in one-on-one settings since we released 0.12 (no more than two or three people, I think) and I've generally suggested that they write `length(var.empty_list) == 0` instead, as a different way to express "if the list is empty".

I'm saying this not to say that we shouldn't do anything about it, but just in case someone ends up here having encountered the unintuitive behavior and can use that alternative formulation instead until we figure out what we might change about this.
