### ISSUE TITLE
Click to Copy for Resource Arguments in Referece Docs / Remove the Hyperlinks.

### ISSUE THREAD

**Issue by drpdishant** [hashicorp/terraform#25799]
When going through the Reference documents for various terraform resources, most of the time we need to select and copy the argument names to avoid any spelling mistakes. 
But currently the names are clickable hyperlinks which are useless as it does nothing but scrolls the page putting the argument at the top. 
Its making copying the name difficult.
Or else if you are keeping it clickable, you many implement click to copy function, so if a reader clicks on the name of the argument it copies it to the clipboard to be pasted anywhere else.
![Screencast from 08-11-2020 08 00 14 PM](https://user-images.githubusercontent.com/27772366/89910298-a9d1b580-dc0d-11ea-9848-990a0f38dfd7.gif)

**Comment by pkolyvas** [comment]
Hi there! Thanks for reporting/suggesting this change. I'll bring this to the attention of the registry team! I'm going to close the issue here however as this is the repository for Terraform itself.
