### ISSUE TITLE
provide epoch time (integer) instead timestamp string

### ISSUE THREAD

**Issue by toralf** [hashicorp/terraform#25802]
### Current Terraform Version
```
$ terraform version
Terraform v0.12.24
```

### Use-cases
Calculate diff eg.:
```
let "diff = $(date +%s) - $epochtime"
```

**Comment by smutel** [comment]
Or add sequence in formatdate function to be able to convert it in epoch ?

**Comment by toralf** [comment]
> Or add sequence in formatdate function to be able to convert it in epoch ?

better: "do not convert it from epoch into a string" :-)

**Comment by crw** [comment]
Thank you for your continued interest in this issue. 

[Terraform version 1.8](https://github.com/hashicorp/terraform/blob/v1.8.0-beta1/CHANGELOG.md) launches with support of provider-defined functions. It is now possible to implement your own functions! We would love to see this implemented as a provider-defined function. 

Please see the [provider-defined functions documentation](https://developer.hashicorp.com/terraform/plugin/framework/functions) to learn how to implement functions in your providers. If you are new to provider development, learn how to [create a new provider](https://developer.hashicorp.com/terraform/plugin/framework) with the Terraform Plugin Framework. If you have any questions, please visit the [Terraform Plugin Development category in our official forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). 

We hope this feature unblocks future function development and provides more flexibility for the Terraform community. Thank you for your continued support of Terraform!

**Comment by austinvalle** [comment]
Hey everyone 👋🏻 ,

The `hashicorp/time` provider has just released a new [`rfc3339_parse` ](https://registry.terraform.io/providers/hashicorp/time/latest/docs/functions/rfc3339_parse) function in `v0.11` which should allow you to grab the unix time (along with other data about an RFC3339 timestamp, example below using the built-in `plantimestamp()` function).

You can test this out now with Terraform [`v1.8.0-beta1`](https://github.com/hashicorp/terraform/releases/tag/v1.8.0-beta1) or wait for the upcoming `v1.8.0` release.

```terraform
# Configuration using provider functions must include required_providers configuration.
terraform {
  required_providers {
    time = {
      source  = "hashicorp/time"
      version = "0.11.1"
    }
  }
  # Provider functions require Terraform 1.8 and later.
  required_version = ">= 1.8.0"
}

locals {
  plan_time = provider::time::rfc3339_parse(plantimestamp())
}

output "unix" {
  value = local.plan_time.unix
}
```

```bash
 $ terraform plan

Changes to Outputs:
  + unix = 1710201187
```

If you run into any problems with the new function, please create an issue over in the [`time` provider issue tracker](https://github.com/hashicorp/terraform-provider-time/issues ), thanks!
