### ISSUE TITLE
0.13.0 - Is it possible to suppress or hide the "will be read during apply" messages for `data` resources? 

### ISSUE THREAD

**Issue by mendhak** [hashicorp/terraform#25805]
### Current Terraform Version

```
Terraform v0.13.0
```

### Use-cases

We are using terraform as part of a CI pipeline.  As part of code review, we review the output of `terraform plan` to make sure nothing bad's about to happen.  

Problem - in v0.13.0, many `data` resources are showing up in the `terraform plan` output with a "will be read during apply" message, even if there are no changes. So far we see if for (AWS)  KMS secrets, ACM certificates, Route Tables, Subnets.    Example: 

> \# module.xxx.yyy.zzz will be read during apply
> \# (config refers to values not yet known)
> 
> data "aws_acm_certificate" "example"  {
       arn         = "..."
        domain      = "*.example.com"
      ~ id          = "2020-08-11 13:14:36.7163237 +0000 UTC" -> "2020-08-11 13:14:39.5159431 +0000 UTC"
        most_recent = false
        statuses    = [
            "ISSUED",
        ]
        tags        = {}
    }

We have a lot of `data` resources that refer to resources not in our control.  The plan is now quite noisy and difficult to follow. 

Is there a way to suppress the "will be read during apply" messages for data resources in Terraform plan?  
If it's not possible, can this feature be introduced?  

### Attempted Solutions

I'm unsure what to do, I checked the changelogs but I see no notes about the data resource output during plan phase I tried searching these threads, but it's not clear to me why the output is appearing and how to suppress it.

**Comment by jbardin** [comment]
Hi @mendhak,

Thanks for filing the issue. In general, correctly working data sources should not show up in the plan when there are no changed to the data source configuration when there are no changes to the configuration or `depends_on` references. These particular data sources should be reported to the associated provider so they can be fixed.

Thanks!

**Comment by mendhak** [comment]
Thanks, I've just seen an issue filed here in terraform provider aws:  

https://github.com/terraform-providers/terraform-provider-aws/issues/14579

And I see you've opened a separate issue:

https://github.com/hashicorp/terraform/issues/25812

So I'll close this off as any real progress can be tracked in those two places.
