### ISSUE TITLE
"provider template couldn't be found"

### ISSUE THREAD

**Issue by jc-asdf** [hashicorp/terraform#2581]
When moving to Terraform 0.6.0, terraform refresh now generates errors around my templates:

    * module.staging_member_service.module.mysql_db_server.template_file.userdata (destroy): provider template couldn't be found

My overall terraform code is pretty crazy, so I'm working on creating a smaller reproduction case which I'll attach when I figure out how to reproduce.

**Comment by shamil** [comment]
I'm experiencing exactly same problem after upgrading to 0.6.0

**Comment by jc-asdf** [comment]
So the closest I can figure is that this is related to nested modules.  I'm only able to recreate this when I have a template inside a module, included from another module, included from the root.  Even then, it's frustratingly inconsistent.

**Comment by vitroth** [comment]
I'm seeing this with openstack and google modules being not found when called from a module two levels down, i.e. root->module->module

Exact same config works with 0.5.3, fails with 0.6.0, seems to be consistent for me.

**Comment by phinze** [comment]
Looking into this now!

**Comment by phinze** [comment]
Quick update on this - still trying to reproduce on my side with no luck, so more information about how it reproduces in your environments is welcome here.

**Comment by jc-asdf** [comment]
Confirmed that the merge above fixed the issue.  0.6.1 works now; thanks!

**Comment by roboll** [comment]
I'm seeing this same issue in Terraform 0.6.4 - is there a chance this resurfaced?

**Comment by phinze** [comment]
Hi @roboll - sorry for the trouble here. Can you open a fresh issue with your repro steps? Then we'll investigate and figure out what's up. :+1:

**Comment by roboll** [comment]
@phinze Weirdly, I only ran into the issue with `go get`-ed terraform. When I installed from homebrew, the problem disappeared. Assuming the problem was on my end. Thanks.

**Comment by roboll** [comment]
for the sake of documenting this for anyone else - installing terraform via `go get` will install the terraform binary, but will install the plugin binaries with the wrong names (`provider-template` vs `terraform-provider-template`). need to run `make dev` to get the plugins built properly.

cc. @phinze might be worth documenting elsewhere.

**Comment by ryangraham** [comment]
I ran into the same problem with 0.6.6 copied from the tarball to /usr/local/bin. @roboll thanks for the tip on homebrew. That fixed it for me.

`brew update`
`brew remove terraform`
`brew install terraform`
`brew link --overwrite terraform`

**Comment by phinze** [comment]
@roboll definitely worth documenting - where do you think would be good? Could add it to https://github.com/hashicorp/terraform#developing-terraform perhaps - or is there somewhere better?

**Comment by vivekmenezes** [comment]
I ran into the same problem when I copied from the tarball into /usr/local/bin. I fixed it by creating a symlink from /usr/local/bin to the tarball.

**Comment by arehmandev** [comment]
If anyone experiences this error make sure you've copied your plugin into the same location as your terraform binary (e.g. /user/local/bin). In my case I also had to name the plugin as "terraform-provider-pluginname"
