### ISSUE TITLE
linux_arm64 support

### ISSUE THREAD

**Issue by liqiang-fit2cloud** [hashicorp/terraform#25814]
Hi there,

Just a quick question, do we have plan to support linux_arm64?

**Comment by pkolyvas** [comment]
Hi @liqiang-fit2cloud, we have plans but no timeline to communicate yet. 

I'm going to close this against https://github.com/hashicorp/terraform/issues/14474 as a duplicate for now. We'll make sure to communicate our plans regarding ARMv8 on darwin and linux once we've got something concrete to share.
