### ISSUE TITLE
Increase Block Storage Creation Timeouts

### ISSUE THREAD

**Issue by coreylarew** [hashicorp/terraform#25820]
I regularly have to create large volumes from images using terraform.  I would like the blockstorage timeout to be increased from 10 minutes.

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by danieldreier** [comment]
@coreylarew can you please provide additional information about what provider you're using to provision block storage? I believe these timeouts would need to be changed in the provider. I'm happy to forward your request to the right team, but I need to know which provider this is about.

**Comment by coreylarew** [comment]
I will add this to the request but it is the openstack provider

**Comment by danieldreier** [comment]
Thanks @coreylarew  - I've labeled it, and HashiBot will migrate the issue over for us.
