### ISSUE TITLE
customer_x509_cas - not able to read root cert when intermediate exists

### ISSUE THREAD

**Issue by kpskohli** [hashicorp/terraform#25838]
### Terraform Version
12.24

```
...
```

### Terraform Configuration Files

resource "mongodbatlas_x509_authentication_database_user" "x509" {
  project_id        = "1ABCXXXXXXXXXXXX"
  customer_x509_cas = <<-EOT
-----BEGIN CERTIFICATE-----
alksjflkajdflkajfkjs....
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
qwijgqopijvfopiqjfbiojqiofjoqi....
-----END CERTIFICATE-----"
EOT
}

```terraform
...
```

### Expected Behavior

The above should save the whole cert chain.
### Actual Behavior

It only save intermediate cert.

**Comment by alisdair** [comment]
This looks like an issue with the mongodbatlas provider, not Terraform core, so I'm closing it here. [You may want to report it on the provider repository here](https://github.com/mongodb/terraform-provider-mongodbatlas). Thanks!
