### ISSUE TITLE
Segfault when dynamic block iterates over nested map(object(map(object))) and contains content

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform#25846]
### Terraform Version
```
0.12.29
```

### Terraform Configuration Files

Given a struct with a nested `map(object(map(object)))`:

```terraform
variable = {
  "key" = {
    blocks = {
      "nested key" = {<object>}
    }
  }
}    
```

A resource can be specified like:

```terraform
resource "resource_type" "resource_name" {
  for_each = var.variable

  ...

  dynamic "block" {
    for_each = each.value.blocks
  }
}
```

and thus far we are completely fine. However, if `content` is added to the dynamic block with anything whatsoever (including only whitespace):

```terraform
resource "resource_type" "resource_name" {
  for_each = var.variable

  ...

  dynamic "block" {
    for_each = each.value.blocks

    content {}
  }
}
```

### Debug Output
available upon request

### Crash Output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xe02e8e]

goroutine 1 [running]:
github.com/hashicorp/terraform/lang/blocktoattr.walkVariables(0x2468e40, 0xc00022b600, 0x0, 0x1, 0x2468e40, 0xc00022b600, 0x0, 0x0, 0xc000700e10, 0x1)
	/home/circleci/project/project/lang/blocktoattr/variables.go:34 +0x1ae
github.com/hashicorp/terraform/lang/blocktoattr.ExpandedVariables(...)
	/home/circleci/project/project/lang/blocktoattr/variables.go:24
github.com/hashicorp/terraform/lang.ReferencesInBlock(0x2468e40, 0xc00022b600, 0x0, 0x1, 0xc000700e08, 0x1, 0x1, 0x1, 0xc000e34030)
	/home/circleci/project/project/lang/references.go:68 +0x66
github.com/hashicorp/terraform/terraform.(*NodeAbstractResource).References(0xc000e7c000, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/node_resource_abstract.go:198 +0x33d
github.com/hashicorp/terraform/terraform.NewReferenceMap(0xc000987100, 0x6a, 0x6a, 0x6a)
	/home/circleci/project/project/terraform/transform_reference.go:492 +0x24a
github.com/hashicorp/terraform/terraform.(*ReferenceTransformer).Transform(0x367d188, 0xc000906500, 0x14, 0x0)
	/home/circleci/project/project/terraform/transform_reference.go:79 +0x71
github.com/hashicorp/terraform/terraform.(*BasicGraphBuilder).Build(0xc000185740, 0x0, 0x0, 0x0, 0x365d4a0, 0xc000185770, 0x4e57b0, 0xc0000b8000)
	/home/circleci/project/project/terraform/graph_builder.go:50 +0x477
github.com/hashicorp/terraform/terraform.(*PlanGraphBuilder).Build(0xc0001a0380, 0x0, 0x0, 0x0, 0x1, 0x1fd6d98, 0xc0005b5501, 0xc0001857d0)
	/home/circleci/project/project/terraform/graph_builder_plan.go:65 +0xbc
github.com/hashicorp/terraform/terraform.(*Context).Graph(0xc00022d0e0, 0x6, 0xc0001857c6, 0xc00126c100, 0xc00048c228, 0xc000898ba8, 0xc0007e67c0)
	/home/circleci/project/project/terraform/context.go:292 +0x1b8
github.com/hashicorp/terraform/terraform.(*Context).Validate(0xc00022d0e0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/context.go:675 +0xc9
github.com/hashicorp/terraform/command.(*ValidateCommand).validate(0xc0002b0700, 0xc000044340, 0x3a, 0x0, 0x0, 0x0)
	/home/circleci/project/project/command/validate.go:127 +0x4f9
github.com/hashicorp/terraform/command.(*ValidateCommand).Run(0xc0002b0700, 0xc00000c090, 0x0, 0x0, 0xc000085c20)
	/home/circleci/project/project/command/validate.go:83 +0x752
github.com/mitchellh/cli.(*CLI).Run(0xc000372280, 0xc000372280, 0xc000533d90, 0x1)
	/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:251 +0xc8a
main.realMain(0x0)
	/home/circleci/project/project/main.go:106 +0xb4
main.main()
	/home/circleci/project/project/main.go:42 +0x3b
```

### Expected Behavior
Terraform iterates over a nested `map(object(map(object)))` inside a dynamic block and populates content. Alternatively, Terraform outputs an error if something is wrong with the usage.

### Actual Behavior
segmentation fault

### Steps to Reproduce
`terraform validate`

### Additional Context
I am aware that nested iteration is not supported for `resource` (ergo the `locals { flatten([[{...}]]) } pattern`), but my understanding was this was supported for dynamic blocks. Please let me know if otherwise.

### References
n/a

**Comment by mschuchard** [comment]
Sorry; disregard. I actually made a pair of dumb mistakes to cause this segfault: a typo in the resource type combined with `each.<key> instead of `each.value.<key>`.

If this crash occurring due to a combination of two typos is interesting, then please let me know. Otherwise, I will close this promptly.

**Comment by danieldreier** [comment]
@mschuchard yes! I'm absolutely interested - terraform should never, ever segfault, even with typos. What would be really helpful is if you can put together a copy-pastable bit of HCL that produces it when run. I could probably piece it together from what you've written, but I imagine that in a few minutes you can show me how to produce it. We've recently prioritized fixing crashes and have fixed about 90% of reported crashes and 100% in recent versions of terraform, so this is helpful and we want to know about all crashes.

**Comment by danieldreier** [comment]
@mschuchard are you still working on putting together a reproduction case? I'd love to get this fixed, but we really can't do much without a clear reproduction case, and if you can put one together it would really help.

**Comment by mschuchard** [comment]
I have this on my unread GH notifications, so it would still be on a "TODO" list, but ETA is murky due to how busy I am.
If the duration becomes too long and it seems like I will be unable to have time to circle back, then I will just close.

**Comment by mschuchard** [comment]
Sorry, but it appears I have no idea when I would have time to return to this. If nothing else, it is half-dependent upon a dumb typo, so it is really along the lines of user error.
