### ISSUE TITLE
Terraform 0.13 breaks backward compatibility for backend-config files. Config blocks no longer supported.

### ISSUE THREAD

**Issue by xmlRoot** [hashicorp/terraform#25843]
### Terraform Version
```
Terraform v0.13.0
```
### Terraform Configuration Files
An examlpe config file can be found in this gist  
https://gist.github.com/xmlRoot/1218d857df9aeea639ac439c7ffe6f9b

### Expected Behavior
As per [the documentation](https://www.terraform.io/docs/backends/types/remote.html#using-cli-input) the format of the `backend-config` file allows for configuration blocks, which clearly has been changed in 0.13 ( although I can't see any mention of that anywhere, I could've missed it of course). Going from the documentation it is expected to be able to specify the workspace using the backend-config hcl file, however with v0.13 that seems to no longer be possible.

### Actual Behavior
when running the command 
```bash
terraform init 
```
We get the error 

```bash
Initializing the backend...

Error: Invalid backend configuration file

The backend configuration file "backend-localdev.hcl" given on the command
line must contain key-value pairs only, and not configuration blocks.

```

### Steps to Reproduce
1. Create a terraform cloud account.
2. Create an organization and a workspace. ( The workspace mustn't be linked to a git repo. )
3. Run `terraform init -backend-config=backend-localdev.hcl`

**Comment by alisdair** [comment]
Thanks for reporting this! We're tracking this bug in #25793, so I'm going to close this one as a duplicate.
