### ISSUE TITLE
Switching to registry published provider version breaks existing state

### ISSUE THREAD

**Issue by loafoe** [hashicorp/terraform#25867]
### Terraform Version

```
0.13
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    hsdp = {
      source  = "philips-software/hsdp"
      version = "0.5.5"
    }
    cloudfoundry = {
      source  = "terraform-registry.us-east.philips-healthsuite.com/philips-forks/cloudfoundry"
      version = "0.12.2-202008131826"
    }
  }
}
```

### Debug Output
```
$ terraform providers
Providers required by configuration:
.
├── provider[terraform-registry.us-east.philips-healthsuite.com/philips-forks/cloudfoundry] 0.12.2-202008131826
├── provider[registry.terraform.io/philips-software/hsdp] 0.5.5
├── module.dev_client
│   └── provider[registry.terraform.io/philips-software/hsdp] 0.5.5
├── module.east_client
│   └── provider[registry.terraform.io/philips-software/hsdp] 0.5.5
└── module.west_client
    └── provider[registry.terraform.io/philips-software/hsdp] 0.5.5

Providers required by state:

    provider[registry.terraform.io/-/hsdp]
```
### Crash Output
```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/hsdp:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/-/hsdp
```

### Expected Behavior
State file uses registry provider OR hint on how to fix reference to stale `-/hsdp` provider 

### Actual Behavior
Cannot get past `terraform init`

### Additional Context
Our provider was recently published to the official Terraform provider registry. In the past we've been installing this provider locally. When switching to the registry version we can't seem to reconcile the existing state to accept the new registry served version. Terraform 0.13 is looking for `provider[registry.terraform.io/-/hsdp]`. Is there any way to fix our state? For another provider that had only a `data` entry the issue was resolved by just wiping the state entry, but we cannot really do this for the other existing state.

**Comment by loafoe** [comment]
Found the solution after a few minutes:

```
terraform state replace-provider -- -/hsdp philips-software/hsdp
```

**Comment by andrewpage** [comment]
Thanks for documenting this. I was having the same problem with `-/aws` & `hashicorp/aws`. Seems like my state broke immediately after the `0.13upgrade`. Took a bit of google-fu to find this issue, but glad I did!
