### ISSUE TITLE
Template new variable error.

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2586]
When using a preexisting template resource, if you reference a new template variable, (in both the template file, and the vars {} block within the template resource), you cannot terraform apply, as terraform complains that it cannot find the variable in the tfstate state. 

It should recognise that its a new variable and be able to deal with this situation.

Terraform 0.5.3

**Comment by phinze** [comment]
Hey there - this should be fixed in 0.6.0 - feel free to follow up if not!
