### ISSUE TITLE
d.GetOk cannot distinguish between nil and ""

### ISSUE THREAD

**Issue by neil-yechenwei** [hashicorp/terraform#25872]
### Terraform Version

```
Terraform v0.12.28
provider.azurerm (2.20.0)
```

### Terraform Configuration Files

```terraform
provider "azurerm" {
  features {}
} 

resource "azurerm_resource_group" "example" {
  name     = "cg-rg-test01"
  location = "westeurope"
}

resource "azurerm_container_group" "example" {
  name                = "example-continst-test01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  ip_address_type     = "public"
  dns_name_label      = "jerome-aci-label"
  os_type             = "Linux"

  container {  
    name   = "hello-world"
    image  = "microsoft/aci-helloworld:latest"
    cpu    = "0.5"
    memory = "1.5"

    ports {
		port     = 8000
		protocol = "TCP"
    }
    
    secure_environment_variables = {
      PRIVATE_EMPTY = ""
      PRIVATE_VALUE = "test"
    }
	
    environment_variables = {
      PUBLIC_EMPTY = "abc"
      PUBLIC_VALUE = "test"
    }
  }
}
```

### Expected Behavior

d.GetOk("container.0.secure_environment_variables.PRIVATE_EMPTY") should return `"", true`.
### Actual Behavior

d.GetOk("container.0.secure_environment_variables.PRIVATE_EMPTY") should return `"", false`.
### Steps to Reproduce

1. terraform apply
2. terraform plan

### Additional Context

After investigated, seems the empty string value of PRIVATE_EMPTY of secure_environment_variables isn't stored to tfstate file while setting PRIVATE_EMPTY as "" in tfconfig.

After do more testing, I found [d.GetOk()](https://github.com/terraform-providers/terraform-provider-azurerm/blob/a719cb5f91144a17408d27e0a7292a371ad059b9/azurerm/internal/services/containers/container_group_resource.go#L1155) would return "false" when the value of PRIVATE_EMPTY property is set as "" in tfconfig, which means terraform doesn't find the value of "PRIVATE_EMPTY" property. So empty string value of PRIVATE_EMPTY isn't set in the tfstate file. I assume the root cause is that d.GetOk() doesn't distinguish between `nil` and `""`. I expect d.GetOk() should be able to distinguish between `nil` and `""`. So for this scenario, d.GetOk("container.0.secure_environment_variables.PRIVATE_EMPTY") should return `"", true` not `"", false`.

**Comment by jbardin** [comment]
Hi @neil-yechenwei 

Sorry for the confusing behavior, but unfortunately this is expected with the legacy SDK, as there there is no way to reliably differentiate between `null` and `""` in the old protocol. 

Note that if you're building a provider yourself, you should be using the [terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk/) rather than this repository, as that contains the last stable version of the SDK and may contain bug fixes not present in the terraform repository.

Thanks
