### ISSUE TITLE
google_sql_database_instance: cannot reuse var.project since it looks emptied.... 

### ISSUE THREAD

**Issue by ccancellieri** [hashicorp/terraform#25875]
### Terraform Version
0.13

### Terraform Configuration Files

Trying to obtain a string interpolating 2 variables:
 var.project
 var.subnetwork

I've properly configured those two variables which are actually used in many other places inside my main.tf root module

### Debug Output

```
Error: "settings.0.ip_configuration.0.private_network" ("/projects//global/networks/CORRECT_VAR_VALUE") doesn't match regexp 

  database_private_network = "projects/${var.project}/global/networks/${var.subnetwork}"
...
```

### Expected Behavior
A string interpolated in the correct way...

```
("/projects/CORRECT_PROJECT_VALUE/global/networks/CORRECT_VAR_VALUE") 
```

### Actual Behavior
var.project is interpolated as empty value.... while var.subnetwork is fine. I'm 100% sure that also var.project has a value

**Comment by ccancellieri** [comment]
### Configuration

module "database" {
  source                 = "./modules/database"
  # instance
  project                = var.project
  region                 = var.region
  dependson              = [module.instance.instance-url]
  database_instance_name = var.database_instance_name
  database_version       = var.database_version
  tier                   = var.tier
  database_private_network = join("",["projects/",var.project,"/global/networks/",var.subnetwork])
  database_name          = var.database_name
  # users
  sql_users_name         = var.sql_users_name
  sql_users_pass         = var.sql_users_pass
}

I'm also trying with join with same result:

Error: "settings.0.ip_configuration.0.private_network" ("projects//global/networks/XXXXXXXXX") doesn't match regexp "projects/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?)))/global/networks/((?:[a-z](?:[-a-z0-9]*[a-z0-9])?))$"
  on modules/database/database.tf line 1, in resource "google_sql_database_instance" "db":
   1: resource "google_sql_database_instance" "db" {

**Comment by ccancellieri** [comment]
Let me also add that it's strictly related to the var.project variable, using another variable join is able to properly interpolate it's value

**Comment by ccancellieri** [comment]
```
resource "google_sql_database_instance" "db" {
  project = var.project
  name   = var.database_instance_name
  database_version = var.database_version
  region = var.region
  depends_on = [ var.dependson ]
  settings {
    tier = var.tier
    ip_configuration {
      ipv4_enabled    = false
      private_network = join("",["projects/",var.project,"/global/networks/",var.subnetwork])
    }
  }
}
```

**Comment by mildwonkey** [comment]
Hi @ccancellieri ,

It's hard to determine what's going on here with the information you've provided. Can you provide a simplified configuration that we can use to reproduce your problem? 

For troubleshooting, I frequently use `output` to or `terraform console` to inspect variable values and the output of functions like your `join`.

**Comment by mildwonkey** [comment]
I'm unable to reproduce the issue you are reporting with the supplied configuration. I had to make some modifications, since the configuration you provided was not valid:

```main.tf
module "database" {
  source                   = "./database"
  project                  = var.project
  subnetwork               = var.subnetwork
  database_private_network = join("", ["projects/", var.project, "/global/networks/", var.subnetwork])
}

output "network" {
  value = module.database.network
}
output "database_private_network" {
  value = module.database.database_private_network
}
```

```database/db.tf
output "network" {
  value = join("",["projects/",var.project,"/global/networks/",var.subnetwork])
}

output "database_private_network" {
  value = var.database_private_network
}

variable "database_private_network" {}
variable "project" {}
variable "subnetwork" {}
```

And here are the outputs. You can see that I tested both the variable being passed to the module - `var.database_private_network`, and the result of the same `join()` function inside the module (`output "network"`):

```
database_private_network = projects/MY-PROJECT/global/networks/MY-SUBNETWORK
network = projects/MY-PROJECT/global/networks/MY-SUBNETWORK
```

I am sorry that you are having difficulty, but there does not appear to be terraform bug here. I recommend that you post your question on the community forums. If you still feel that there is a terraform bug, you can open a new issue; please include a full reproduction that someone else can run locally which reproduces the problem you've reported.

**Comment by ccancellieri** [comment]
Apologize for the 'not working' configuration but as explained I was not able to run so it's an handmade config one.
Thanks for testing it, I've tryied asking on gitter but nobody provided any hint. I'll continue using my workaround maybe someone will be able to reproduce soon or later.
Best regards.
