### ISSUE TITLE
Terraform pipeline setup error Error: Could not load plugin Plugin reinitialization required. Please run "terraform init".

### ISSUE THREAD

**Issue by connectgeeks** [hashicorp/terraform#25882]
Running with gitlab-runner 13.3.0-rc1 (669fc507)
  on docker-auto-scale 72989761
Preparing the "docker+machine" executor
00:14
Using Docker executor with image hashicorp/terraform:light ...
Pulling docker image hashicorp/terraform:light ...
Using docker image sha256:55a3668eaa153b5fc584aa93d64397e3cb5820204de9885fa5e0c5bdda1b1623 for hashicorp/terraform:light ...
Preparing environment
00:02
Running on runner-72989761-project-20526456-concurrent-0 via runner-72989761-srm-1597676473-beba1cde...
Getting source from Git repository
00:02
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/connectgeeks/test/.git/
Created fresh repository.
Checking out 0200fb52 as master...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:00
$ export _MODULE_ROOT_DIR=$CI_PROJECT_DIR$MIA_PROCESSING_DIR_PREFIX
$ export _BACKEND_CONFIG_DEV=$CI_PROJECT_DIR/environment$MIA_PROCESSING_DIR_PREFIX/dev/dev-backend.tfvars
$ export _VAR_FILE_DEV=$CI_PROJECT_DIR/environment$MIA_PROCESSING_DIR_PREFIX/dev/dev.tfvars
$ export AWS_CLI_DEFAULT_REGION=${AWS_CLI_DEFAULT_REGION:-$_AWS_CLI_DEFAULT_REGION}
$ export AWS_ROLE_DEV=${AWS_ROLE_DEV:-$_AWS_ROLE_DEV}
$ export _HAS_PARENT=${HAS_PARENT:-no}
$ chmod +x $_MODULE_ROOT_DIR/assume_role.sh
$ echo "Storing GitLab CI Token for depending git clones (e.g. in terraform) from gitlab.com"
Storing GitLab CI Token for depending git clones (e.g. in terraform) from gitlab.com
$ git config --global credential.helper 'store --file ~/.git-credentials'
$ echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com" >> ~/.git-credentials
$ terraform validate
Error: Could not load plugin
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".
Failed to instantiate provider "registry.terraform.io/hashicorp/aws" to obtain
schema: unknown provider "registry.terraform.io/hashicorp/aws"
ERROR: Job failed: exit code 1

**Comment by alisdair** [comment]
I'm not sure what the context of this error is, but it looks like (as advised) you will need to add a step to run `terraform init`.

This doesn't look like a bug in Terraform, so I'm going to close this issue. If you'd like to ask follow-up questions, please open a thread on [the Terraform discussion forum](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
