### ISSUE TITLE
Changing the IP range on a VPC throws an error

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/terraform#2588]
In attempting to isolate an issue, I changed the IP range on my VPC from `10.0.0.0/16` to `192.168.0.0/16`.  I likewise changed my subnets with `/24`'s.

I got the following output:

```

* Error creating subnet: InvalidSubnet.Range: The CIDR '192.168.1.0/24' is invalid.
        status code: 400, request id: []
aws_subnet.us-east-1d-public: Error: 1 error(s) occurred:

* Error creating subnet: InvalidSubnet.Range: The CIDR '192.168.2.0/24' is invalid.
        status code: 400, request id: []
aws_security_group.web: Creation complete
Error applying plan:

4 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error deleting VPC: DependencyViolation: The vpc 'vpc-ae0209cb' has dependencies and cannot be deleted.
        status code: 400, request id: []
* 1 error(s) occurred:

* aws_internet_gateway.default: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* 1 error(s) occurred:

* 1 error(s) occurred:

* Error creating subnet: InvalidSubnet.Range: The CIDR '192.168.1.0/24' is invalid.
        status code: 400, request id: []
* 1 error(s) occurred:

* 1 error(s) occurred:

* Error creating subnet: InvalidSubnet.Range: The CIDR '192.168.2.0/24' is invalid.
        status code: 400, request id: []
```

Due to the presence of "this is a bug with Terrafrom and should be reported", I'm reporting it although I suspect this is not a common use case...

**Comment by radeksimko** [comment]
What terraform version do you use? There has been some changes lately w/ VPC CIDR validation and it would help to know whether you're already using `0.6.0` or any previous version.

**Comment by jkodroff** [comment]
`Terraform v0.5.3`

**Comment by radeksimko** [comment]
I can confirm this is happening in the latest version:

repro case:
```ruby
resource "aws_vpc" "main" {
    cidr_block = "10.0.0.0/16"
}

resource "aws_internet_gateway" "gw" {
    vpc_id = "${aws_vpc.main.id}"
}
```
Create VPC & IGW by running `terraform apply`, then change `cidr_block` as suggested to `192.168.0.0/16` and run `terraform apply` again. Terraform is trying to destroy VPC first and it obviously struggles to do so as there's IGW attached to it.

This would be the simplest fix:

```ruby
resource "aws_vpc" "main" {
    cidr_block = "192.168.0.0/16"

    lifecycle {
        create_before_destroy = true
    }
}
```

I remember there is a similar problem w/ ASG / Launch Configuration and the `lifecycle` workaround above is treated as a solution, is that still the case, or are we looking for better solution that would work out of the box? @phinze

**Comment by mitchellh** [comment]
Hey there. It has been a long time since there has been activity on this issue (our fault, sorry!), and the last known repro was against a very old version of Terraform. It is possible this issue still exists but we've addressed dozens of issues with the same type of error message in the past year. Could you please try again on the latest version and let us know if it doesn't work? The easiest way would be to simply open a new issue. Thanks!

**Comment by mitchellh** [comment]
Note that @radeksimko's issue still exists but is unrelated to this exact issue and is also tracked elsewhere.
