### ISSUE TITLE
Terraform 0.13 for_each import fails

### ISSUE THREAD

**Issue by hongkongkiwi** [hashicorp/terraform#25881]
I'm trying to import a resource like this:

terraform import module.mymodule.mysubmodule.google_kms_crypto_key.crypto_key["ssh-host-key"] "projects/mycompany/locations/global/keyRings/mykeyring/cryptoKeys/ssh-host-key"

This fails because "ssh-host-key" does not exist (it's a for_each resource). But I can't create it because it already exists. So I'm a bit stuck....

When running the above command I get this error:
zsh: no matches found: module.mymodule.mysubmodule.google_kms_crypto_key.crypto_key[ssh-host-key]

**Comment by alisdair** [comment]
This looks like a shell quoting error from zsh. Please try wrapping the argument in single quotes, i.e.

```
terraform import \
'module.mymodule.mysubmodule.google_kms_crypto_key.crypto_key["ssh-host-key"]' \
"projects/mycompany/locations/global/keyRings/mykeyring/cryptoKeys/ssh-host-key"
```

Because this is a zsh error, I don't think this is a Terraform bug, so I'm going to close the issue.

**Comment by hongkongkiwi** [comment]
Thank you this fixed my issue.
