### ISSUE TITLE
Terraform v0.13.0, vsphere provider not usable in module with vsphere resources id stored in remote state  

### ISSUE THREAD

**Issue by masert** [hashicorp/terraform#25899]
### Terraform Version

```
$ ./terraform_v13 version
Terraform v0.13.0
+ provider e.com/2E31.com/consul v2.6.1
+ provider e.com/2E31.com/local v1.3.0
+ provider e.com/2E31.com/null v2.1.2
+ provider e.com/2E31.com/template v2.1.2
+ provider e.com/2E31.com/vsphere v1.21.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/vsphere v1.21.0

```

### Terraform Configuration Files

```terraform
$ cat ~/.terraformrc
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
disable_checkpoint = true

provider_installation {
  filesystem_mirror {
    path    = "/usr/share/terraform/plugins"
    include = ["e.com/2E31.com/*"]
  }
  filesystem_mirror {
    path    = "/usr/share/terraform/plugins"
    include = ["registry.terraform.io/hashicorp/*"]
  }
}
-----------------
$ cat versions.tf
terraform {
  required_version = ">= 0.13"

  required_providers {

    consul = {
      source  = "e.com/2E31.com/consul"
      version = ">= 2.6.1"
    }
    template = {
      source  = "e.com/2E31.com/template"
      version = ">= 2.1.2"
    }
    local = {
      source  = "e.com/2E31.com/local"
      version = ">= 1.3.0"
    }
    null = {
      source  = "e.com/2E31.com/null"
      version = ">= 2.1.2"
    }

    vsphere = {
      source = "e.com/2E31.com/vsphere"
      version = ">= 1.21.0"
    }
  }
}
----------------------
$ tree
.
├── backend_consul.tf
├── env_v5_test.tf
├── env_var
│   ├── env_data.tf
│   ├── env_output.tf
│   ├── env_p10_HAM_Infra.tf
│   └── global_var_remote_tfstate.tf
├── main.tf
├── mod_vm_rhel_v5
│   ├── env_var_v5.tf
│   ├── global_var_remote_tfstate.tf
│   ├── main_v5_rhel.tf
│   ├── variables_glob.tf
...
│   └── variables_tmpl_p10_HAM.tf
├── terraform.log
├── terraform.tfvars
...
└── versions.tf
---------------
cat global_var_remote_tfstate.tf
data "terraform_remote_state" "global_var" {
  backend = "consul"

  config = {
    path = "Atlantis/global_var_p10/terraform.tfstate"
    }
}
------------
$ cat mod_vm_rhel_v5/main_v5_rhel.tf
resource "vsphere_virtual_machine" "mod_vm_v5" {....

----------
$ cat env_v5_test.tf

module "fr1-......" {
  source                   = "./mod_vm_rhel_v5"
  mod_vm_name              = "fr1......."
  mod_num_cpu              = 1
  mod_num_cores_per_socket = 1
  mod_memory               = 2048
  mod_vm_ipv4              = "192.168.0....."
  mod_size_disk1           = 60
  mod_vm_folder            = "XXXXXX/YYYYY"
}
-----------
$ cat main.tf
provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_user_psw
  vsphere_server = var.vsphere_server_name
  # if you have a self-signed cert
  allow_unverified_ssl = true
  client_debug    = false
  persist_session = false
}

provider "consul" {
  address    = "127.0.0.1:8501"
  scheme     = "https"
  datacenter = "xxx-infra-YYYY"
}

variable "vsphere_user" {
  type    = string
}

variable "vsphere_user_psw" {
  type    = string
}

variable "vsphere_server_name" {
  type    = string
}

```

### Debug Output

....
2020/08/18 15:20:28 [TRACE] [walkValidate] Exiting eval tree: module.fr1-vs2E31-d03.module.env_var (close)
2020/08/18 15:20:28 [TRACE] vertex "module.fr1-vs2E31-d03.module.env_var (close)": visit complete
2020/08/18 15:20:28 [TRACE] dag/walk: visiting "provider[\"registry.terraform.io/hashicorp/template\"] (close)"
2020/08/18 15:20:28 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/template\"] (close)": starting visit (*terraform.graphNodeCloseProvider)
2020/08/18 15:20:28 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/template\"] (close)": evaluating
2020/08/18 15:20:28 [TRACE] [walkValidate] Entering eval tree: provider["registry.terraform.io/hashicorp/template"] (close)
2020/08/18 15:20:28 [TRACE] eval: *terraform.EvalCloseProvider
2020/08/18 15:20:28 [TRACE] GRPCProvider: Close
2020-08-18T15:20:28.726+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
2020/08/18 15:20:28 [TRACE] No provider meta schema returned
2020/08/18 15:20:28 [WARN] eval: *terraform.EvalValidateProvider, non-fatal err: 2 problems:

- Missing required argument: The argument "user" is required, but was not set.
- Missing required argument: The argument "password" is required, but was not set.
2020/08/18 15:20:28 [ERROR] eval: *terraform.EvalSequence, err: 2 problems:

- Missing required argument: The argument "user" is required, but was not set.
- Missing required argument: The argument "password" is required, but was not set.
2020/08/18 15:20:28 [ERROR] eval: *terraform.EvalOpFilter, err: 2 problems:

- Missing required argument: The argument "user" is required, but was not set.
- Missing required argument: The argument "password" is required, but was not set.
2020/08/18 15:20:28 [ERROR] eval: *terraform.EvalSequence, err: 2 problems:

- Missing required argument: The argument "user" is required, but was not set.
- Missing required argument: The argument "password" is required, but was not set.
2020/08/18 15:20:28 [TRACE] [walkValidate] Exiting eval tree: provider["registry.terraform.io/hashicorp/vsphere"]
2020/08/18 15:20:28 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/vsphere\"]": visit complete
....

### Expected Behavior

As in V12, to be able to create an vsphere virtual machine with cluster resources id /storage id / network id /... stored in remote state (layering)

Seems properties of provider (user / password)  are not inherited from root to module and remote state

### Actual Behavior

$ terraform validate

Error: Missing required argument

The argument "user" is required, but was not set.

Error: Missing required argument

The argument "password" is required, but was not set.

### Steps to Reproduce

terraform init
terraform validate or terraform plan

### Additional Context

Atlantis is not used in this context.

Remote state has been created with TF V13:
global_var_p10]$ ./terraform providers
Providers required by configuration:
.
├── provider[e.com/2E31/template] >= 2.1.2
├── provider[e.com/2E31/local] >= 1.3.0
├── provider[e.com/2E31/null] >= 2.1.2
├── provider[e.com/2E31/vsphere]
└── provider[e.com/2E31/consul] >= 2.6.1
Providers required by state:
    provider[e.com/2E31/vsphere]
    provider[e.com/2E31/consul]

**Comment by alisdair** [comment]
In each module using a non-HashiCorp provider, you must specify the provider source address in a `required_providers` block. This is necessary because it is possible for multiple providers to share the same local name, so Terraform needs to know which fully-qualified provider name is intended.

Please try adding a `required_providers` block in your "mod_vm_rhel_v5 " module, like so:

```hcl
terraform {
  required_providers {
    vsphere = {
      source = "e.com/2E31.com/vsphere"
    }
  }
}
```

The same goes for any other modules using the re-namespaced providers currently specified in your root configuration.

**Comment by masert** [comment]
You're right. Issue was not an issue. And it's working now as expected.

Thanks a lot
