### ISSUE TITLE
Terraform init failed saying - after installation of the provider it's still not detected in the targeted directory

### ISSUE THREAD

**Issue by sijeesh** [hashicorp/terraform#25893]
### Terraform Version

```
Terraform v0.13.0
```
### Terraform Configuration Files

```terraform
...
```

### Debug Output

2020/08/18 10:45:13 [TRACE] providercache.fillMetaCache: error while scanning directory .terraform/plugins: failed to read metadata about .terraform/plugins/localhost/local/an_old_provider/1.0.0/linux_amd64: stat .terraform/plugins/localhost/local/an_old_provider/1.0.0/linux_amd64: no such file or directory

### Crash Output

Error: Failed to install provider

Error while installing localhost/local/provider_name v1.0.0: after installing
localhost/local/provider_name it is still not detected in the target directory;
this is a bug in Terraform

### Expected Behavior

terraform init should be successful
It should not scan an old provider path(which is deleted) for meta files.

### Actual Behavior

terraform init Failed
terraform is scanning  an old provider path which is deleted.

**Comment by mildwonkey** [comment]
Hi @sijeesh !

I am sorry you've experiencing this behavior.

Terraform expects to manage the contents of `.terraform/plugins` and the behavior is unspecified when the user modifies that directory. If you are going to delete a provider from that path, you will need to delete the entire provider directory, not just the provider binary, so in your example you need to remove `.terraform/plugins/localhost/local/an_old_provider`

Thanks!
