### ISSUE TITLE
Local unversioned provider binary locations in TF 0.13

### ISSUE THREAD

**Issue by taiidani** [hashicorp/terraform#25906]
### Current Terraform Version

```
Terraform v0.13.0
```

### Provider development

Expanding upon the documentation issue in #25862 which attempts to address a documentation gap around the new Terraform 0.13 local plugin directory structure.

The new directory structure requires that a semantic version and OS_architecture pair are in the directory tree of the built plugin. This supports the new custom registry features of 0.13 which added a `required_providers` block to specify the location, alias, and version requirements of providers.

Unfortunately this does not play well with the use case of in-development providers where contributors work in feature branches (e.g. no version until tagged) and want to compile their providers locally for testing before publishing the new logic to the registry. This also can cause conflicts between contributors on different unix-based platforms such as `darwin_amd64` vs. `linux_amd64` as the platform and architecture are also embedded into the directory structure.

### Providers not published to registry

Second use case added by @fbreckle below.

> I also want to add the use-case of using a provider from github that is NOT in the official registry yet (which is a thing I do not have under my control).
> Previously, I would just download them to ./terraform.d/plugins, but https://www.terraform.io/docs/commands/cli-config.html#implied-local-mirror-directories does not list that anymore. Even worse, there is no overlap between Mac and Linux paths, essentially forcing separate routines based on the arch, as explained above.

## Attempted Solutions

Currently the solution appears to be making an an assumption that developers will be working on the macOS architecture and hardcoding a "dummy" version. This version has to be manually kept up to date alongside newer versions of the provider in order to stay compatible with any `required_versions` blocks that contributors may be using.

[Example from the Hashicups repository](https://github.com/hashicorp/terraform-provider-hashicups/blob/master/Makefile#L28-L30):
```makefile
HOSTNAME=hashicorp.com
NAMESPACE=edu
NAME=hashicups
BINARY=terraform-provider-${NAME}
VERSION=0.2
OS_ARCH=darwin_amd64

default: install

build:
	go build -o ${BINARY}

install: build
	mkdir -p ~/.terraform.d/plugins/${HOSTNAME}/${NAMESPACE}/${NAME}/${VERSION}/${OS_ARCH}
	mv ${BINARY} ~/.terraform.d/plugins/${HOSTNAME}/${NAMESPACE}/${NAME}/${VERSION}/${OS_ARCH}
```

In the [Writing Custom Providers tutorial](https://learn.hashicorp.com/tutorials/terraform/provider-setup#test-the-provider) you can see the resulting complexity, where the "Mac" instructions guide the user to run `make install` but the Linux and Windows instructions are providing step-by-step manual actions in order to achieve the same effect.

## Proposal

Add support for "versionless" provider binaries in order to support local development.

Multiple potential ideas have been proposed below, each of which could be implemented independently to address the use case.

### 1. Support Prior Directory Structures

One possible way for this would be to have Terraform prioritize support for one of the [prior 0.12 directory structures](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations) (still documenting 0.12 at time of issue submission) of
* `~/.terraform.d/plugins/terraform-provider-<alias>`
* `${pwd}/terraform-provider-<alias>`

Where `alias` is the name of the provider as set in the `required_providers` block. If a binary were found in one of these locations Terraform would prefer it over a lookup in the remote registry.

The latter bullet point would likely be the most explicit which would further emphasize that this is for local development only and is not meant as an official distribution method.

### 2. Enhance filesystem_mirrors

A more flexible solution would be to enhance the `filesystem_mirrors` block itself to support the use case.

For example, the [new "file mirrors" functionality](https://www.terraform.io/docs/commands/cli-config.html#explicit-installation-method-configuration) currently looks to only point at a directory and supports two layouts within that directory:

* Packed: `HOSTNAME/NAMESPACE/TYPE/terraform-provider-TYPE_VERSION_TARGET.zip`
* Unpacked: `HOSTNAME/NAMESPACE/TYPE/VERSION/TARGET`

If this were to also support a `binary` explicit path to the binary itself then this would enable the use case. Terraform would then prefer this binary regardless of the versioning & remote registry configuration of `required_providers`.

### 3. Leverage 0.0.0 with dummy arch

Currently `terraform init` does not appear to detect providers added to the `HOSTNAME/NAMESPACE/TYPE/0.0.0/TARGET` directory with a semantic version of "0.0.0". If Terraform were to understand this location then this directory could be made a special case, where the `required_providers` block is explicitly set to require 0.0.0 of the provider and then developers' makefiles could be hardcoded to build their binaries against the 0.0.0 path.

That support would solve for versions, but not for the disparate contributors' OS_arch platforms. In this case a decision could be made for a platform of `development`, `generic`, `yolo` or similar where Terraform prefers that string over the others and simply _expects_ that the user has placed a binary in that location matching their architecture.

## References

https://github.com/hashicorp/terraform/issues/25862 around the existing documentation being updated for 0.13 which led to this issue.

**Comment by fbreckle** [comment]
This is indeed very annoying.

I also want to add the use-case of using a provider from github that is NOT in the official registry yet (which is a thing I do not have under my control).
Previously, I would just download them to ./terraform.d/plugins, but https://www.terraform.io/docs/commands/cli-config.html#implied-local-mirror-directories does not list that anymore. Even worse, there is no overlap between Mac and Linux paths, essentially forcing separate routines based on the arch, as explained above.
Finally, for my own in-house providers, I now need to fake-version it and do some symlink magic.

Please implement solution 1 above.

The problem with solution 2 above is that the file mirrors configuration is only possible in the CENTRAL terraform config file of a user, as opposed to being able to put it in the repo.

**Comment by mildwonkey** [comment]
This is my suggestion, and what I expect will end up in the provider development documentation:

1. use the filesystem_mirror cli configuration to specify a convenient-to-you local path for the provider you are working on:
```
provider_installation {
  filesystem_mirror {
    path    = "/workdir/"
    include = ["registry.terraform.io/hashicorp/aws"]
  }
  direct {
    exclude = ["registry.terraform.io/hashicorp/aws"]
  }
}
```

(The explicit 'exclude' block is not required, but I've included it for completeness)

2. symlink your locally-built provider binary to the proper subdirectory under the configured `path`

As long as terraform finds a locally-installed provider that matches the version constraints in your configuration, it will not query the registry. If your config has no version constraint, you can use any arbitrary version in the directory. To continue the example:

```
/workdir/registry.terraform.io/hashicorp/aws/1.0/linux_amd64
```

Because the binary is a symlink, you can rebuild it as often as necessary without needing to copy it into place again.

**Comment by mildwonkey** [comment]
Whoops, I did not mean to close this before explaining why. Sorry!

We already have a couple of issues open to update the provider developer documentation, and have no plans to implementing a change in terraform core, so I am going to close this issue. If you have any further questions, please visit our [community forums](https://discuss.hashicorp.com/c/terraform-core/27) , or open a new Github issue if you find any problems. Thank you!

**Comment by taiidani** [comment]
So you're proposing a combination of 2 and 3, with a manual setup step of a `filesystem_mirrors` block with an end-user chosen special directory plus a dummy version? That's a lot of manual action you're expecting from the end-users and provider contributors. Confirmed that it works but I'm not sure it's the best user experience.

So for the two use cases this is more or less what you're suggesting?

### Unregistered Providers

For developers who want to ignore the TF 0.13+ registry feature and continue with locally-installed providers, they have an easier time than providers in the registry.

```hcl
# ~/.terraformrc

provider_installation {
  filesystem_mirror {
    path    = "/Users/username/.terraform.d/plugins_local/"
    include = ["registry.terraform.io/taiidani/jenkins"]
  }
}
```

```makefile
# makefile
VERSION=0.0.1
LOCAL_PROVIDERS="$$HOME/.terraform.d/plugins_local"
BINARY_PATH="registry.terraform.io/taiidani/jenkins/${VERSION}/$$(go env GOOS)_$$(go env GOARCH)/terraform-provider-jenkins_v${VERSION}"

# Builds the provider and adds it to an independently configured filesystem_mirror folder.
build:
	@echo "Please configure your .terraformrc file to contain a filesystem_mirror block pointed at '${LOCAL_PROVIDERS}' for 'registry.terraform.io/taiidani/jenkins'"
	@echo "You MUST delete existing cached plugins from any .terraform directories in Terraform installations you want to test against so that it will perform a lookup on the local mirror"
	go build -o "${LOCAL_PROVIDERS}/${BINARY_PATH}"
```

### Provider Developers

For developers who _are_ using the Terraform registry, you've got a lot more legwork to perform in order to have your repository contributors all on the same page.

Note the addition of `exclude` and the extra MUSTs in the makefile.

```hcl
# ~/.terraformrc

provider_installation {
  filesystem_mirror {
    path    = "/Users/username/.terraform.d/plugins_local/"
    include = ["registry.terraform.io/taiidani/jenkins"]
  }
  direct {
    exclude = ["registry.terraform.io/taiidani/jenkins"]
  }
}
```

```makefile
# makefile
VERSION=0.0.1
LOCAL_PROVIDERS="$$HOME/.terraform.d/plugins_local"
BINARY_PATH="registry.terraform.io/taiidani/jenkins/${VERSION}/$$(go env GOOS)_$$(go env GOARCH)/terraform-provider-jenkins_v${VERSION}"

# Builds the provider and adds it to an independently configured filesystem_mirror folder.
build:
	@echo "Please configure your .terraformrc file to contain a filesystem_mirror block pointed at '${LOCAL_PROVIDERS}' for 'registry.terraform.io/taiidani/jenkins'"
	@echo "You MUST use a direct exclusion in this block in order to pick up the built binary. Otherwise it will query the registry and find a distribution version"
	@echo "You MUST comment out the 'version' constraint in the required_providers block in any Terraform installation you test this in."
	@echo "You MUST delete existing cached plugins from any .terraform directories in Terraform installations you want to test against so that it will perform a lookup on the local mirror"
	go build -o "${LOCAL_PROVIDERS}/${BINARY_PATH}"
```

**Comment by njpaul** [comment]
So as not to forget about those of us on Windows, [mildwonky's solution](https://github.com/hashicorp/terraform/issues/25906#issuecomment-676401569) does work for non-administrators if you use hard links instead of symbolic links, using `mklink /H`. Don't try using Windows shortcuts; they will not work.

I got bit today by a combination of this issue and the docs being out of date while trying to upgrade from a 0.12.X installation. I was hoping to find a solution that is completely relocatable (portable) - meaning I can pass off a folder containing a clone of my configuration and modules, as well as our pre-built internally-developed plugins and the Terraform executable - for a no-setup-required usage.
