### ISSUE TITLE
Wrong Terraform Linux version on server (v0.13.0 -> 0.12.29)

### ISSUE THREAD

**Issue by bruceharrison1984** [hashicorp/terraform#25904]
### Terraform Version
v0.13.0 - Linux

### Debug Output

```sh
/bin/bash --noprofile --norc /home/vsts/work/_temp/ed9f215d-b255-49fc-b6e3-eb7db09858f1.sh
Download Terraform from https://releases.hashicorp.com/terraform/0.13.0/terraform_0.13.0_linux_amd64.zip
Archive:  ./terraform_0.13.0_linux_amd64.zip
  inflating: terraform               
Terraform v0.12.29

Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html
```
### Expected Behavior
When downloading version 0.13.0, I expect to download 0.13.0

### Actual Behavior
It appears that version 0.12.29 was downloaded

### Steps to Reproduce
Download the file at `https://releases.hashicorp.com/terraform/0.13.0/terraform_0.13.0_linux_amd64.zip` and run `terraform -v`

### Additional Context
We ran across this when we blanket updated all of our CI/CD scripts to the latest version. Windows build boxes don't appear to be affected, so the downloaded 0.13.0 binary is correct in those cases.

**Comment by alisdair** [comment]
I can't reproduce this:

![image](https://user-images.githubusercontent.com/68917/90534946-5d740180-e148-11ea-8548-4e3ead9f080e.png)

Is it possible there is a `PATH` issue here? If you run `terraform -v`, perhaps you are not using the `terraform` binary you just downloaded.

**Comment by bruceharrison1984** [comment]
hmm, it is on an Azure DevOps box, so there shouldn't be any other version present

**Comment by bruceharrison1984** [comment]
Looks like something strange is going on with our DevOps build agent. Downloading the file directly on a different workstation shows the correct binary. Closing, thanks for the fast reply.
