### ISSUE TITLE
Terraform 0.13 / Error: Provider configuration not present

### ISSUE THREAD

**Issue by alex-3sr** [hashicorp/terraform#25908]
Hi all,

I've an issue since I'm upgrading Terraform 0.13.00, I didn't have this issue before with Terraform 0.12.26
The odd point here, is that I've a terraform project as prefix workspace backend, and it's still work on 1 environnement, and not on antoher one.

The error is specific with azurerm provider, and with azurerm_key_vault_secret ressource. The error is 
```
Error: Provider configuration not present

To work with azurerm_key_vault_secret.kvsecret_xxxx its
original provider configuration at provider["registry.terraform.io/-/azurerm"]
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
azurerm_key_vault_secret.xxxx, after which you can
remove the provider configuration again.
```
 Tried to upgrade init, but it didn't fix anything.
Have to know that I use Terraform Cloud as backend state location, but running is local. Maybe this information can help.

Thank for your help

### Terraform Version
```
Terraform v0.13.0
* -/azurerm: version = "~> 2.23.0"
```

### Terraform Configuration Files
Here the main part of involved code, but unable to repro the issue in new workspace

```terraform
terraform {
  required_version = ">= 0.13"
  required_providers {
    azuread = {
      source = "hashicorp/azuread"
    }
    azurerm = {
      source = "hashicorp/azurerm"
    }
    random = {
      source = "hashicorp/random"
    }
  }
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "ORG"
    workspaces {
      prefix = "PROJECT-"
    }
  }
}
provider "azurerm" {
  version         = "~> 2"
  subscription_id = local.az_spn.subscription_id
  tenant_id       = local.az_spn.tenant_id
  client_id       = local.az_spn.client_id
  client_secret   = local.az_spn.client_secret
  
  features {
    key_vault {
      recover_soft_deleted_key_vaults = true
      purge_soft_delete_on_destroy    = true
    }
    virtual_machine {
      delete_os_disk_on_deletion = true
    }
    virtual_machine_scale_set {
      roll_instances_when_required = true
    }
  }
}
resource "azurerm_key_vault_secret" "kvsecret_xxxx" {
  name     = "MySecret"
  value    = "abcdef"
  key_vault_id = azurerm_key_vault.keyvault.id
}
```

### Debug Output
Too long and with many confidential info, if need i can share with PM or noise some info inside

### Crash Output
```
Error: Provider configuration not present
To work with azurerm_key_vault_secret.xxx its
original provider configuration at provider["registry.terraform.io/-/azurerm"]
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
azurerm_key_vault_secret.xxx, after
which you can remove the provider configuration again.
```

### Expected Behavior
I expect that plan is able to run

### Actual Behavior
the terraform plan failed

### Steps to Reproduce
1. `terraform workspace select XX`
2. `terraform init`
3. `terraform plan`
-->

### Additional Context
We using Terraform Cloud as backend storage, and using prefix workspace. It's work on the same project, but different workspace (with same code so)

Maybe it's not related to terraform 0.13 directly, and so maybe due to azurerm provider, but the issue happend just after upgrade terraform 0.13 on this workspace, and already works before with azurerm 2.23 version.

Thanks for your help
Kind regards
Alex

**Comment by alex-3sr** [comment]
OK, finally I was able to fix it !
It's just that I removed some terraform resources  (only key vault secrets) before upgrading 0.13, and I didn't update state on all workspace. And now that I update TF 0.13, this ressources was not in config files anymore, and only in a state for a specific workspace. I terraform state rm xxx.yyy the resources, and it's working again ;)

Have to admit that error message is not clearly and was only focus on provider ;)

Thx
Regards
Alex

**Comment by dgonzalezp** [comment]
It still happens to me trying to user databricks provider... terraform creates a folder - and copies all its own providers to it, but it doesn't copy other providers, for me its databricks

'-' folder
![image](https://user-images.githubusercontent.com/20174436/90559469-41318e00-e163-11ea-9b9a-f5d1b232f939.png)

databrickslabs folder
![image](https://user-images.githubusercontent.com/20174436/90559533-51496d80-e163-11ea-97dc-1e709a752393.png)

workaround... manual copy the folder of the provider to - folder
![image](https://user-images.githubusercontent.com/20174436/90559613-7211c300-e163-11ea-9439-76de03a0483d.png)

![image](https://user-images.githubusercontent.com/20174436/90559658-85249300-e163-11ea-9aa2-84025eb8d2fe.png)

Just need to think If you're going to automate this, creating a scripts that copies the folder while this is fixed

**Comment by ppuschmann** [comment]
@alex-3sr It happened to me in the same way and my solution looked like this:

1. revert changes
2. terraform init --upgrade
3. terraform apply
4. terraform 013upgrade  --> yes
5. terraform apply
6. NOW apply intended changes

**Comment by mildwonkey** [comment]
For anyone who missed it, the [upgrade guide](https://www.terraform.io/upgrade-guides/0-13.html#before-you-upgrade) does specify that you should run plan _before_ you upgrade and `apply` changes before upgrading.

**Comment by ppuschmann** [comment]
Hi @mildwonkey , that's correct 👍 , thank you for pointing this out.

But things start to become really funny when you discover Terraform 0.13 code with a 0.11 statefile.
Didn't know this was possible, but I guess just some missing `terraform apply` after upgrading.
