### ISSUE TITLE
`terraform init` needlessly makes recursive copies of locally sourced modules

### ISSUE THREAD

**Issue by awh** [hashicorp/terraform#25900]
### Terraform Version

```
Terraform v0.13.0
Terraform v0.12.29
```

### Terraform Configuration Files
N/A
### Debug Output
N/A
### Crash Output
N/A

### Expected Behavior
If your terraform configuration instantiates a locally-sourced module multiple times, each corresponding file in `.terraform/modules` should be a symlink to the local source.

### Actual Behavior
The first instantiation of the module results in a symlink in `.terraform/modules` but all subsequent instantiations are a real directory containing a recursive copy of the source. This is because [this piece of code](https://github.com/hashicorp/terraform/blob/83630a7003fb8b868a3bf940798326634c3c6acc/internal/initwd/getter.go#L110-L118) does not take into account that the existing `prevDir` may actually just be a symlink to a local source directory, and merrily makes a full copy on every subsequent module instantiation.

A possible fix is to make [this assignment](https://github.com/hashicorp/terraform/blob/83630a7003fb8b868a3bf940798326634c3c6acc/internal/initwd/getter.go#L136-L138) conditional on `realAddr` not starting with the `file://` scheme.

### Steps to Reproduce
N/A
### Additional Context
N/A
### References
N/A

**Comment by mildwonkey** [comment]
Hi @awh, thank you for reporting this! 

Can you share a sample configuration that we can use to reproduce this issue? I'm not entirely certain what you mean by a locally-sourced module; for example if the modules are relative to the terraform directory, no links are created:

```hcl
module "foo" {
  source = "../module"
}
```

```
ls .terraform/modules/
modules.json
```

We will look into this once we get that missing information - thank you!

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity.

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!
