### ISSUE TITLE
Terraform uses local kubeconfig rather than state

### ISSUE THREAD

**Issue by jleechp-occm** [hashicorp/terraform#25919]
When making changes to an AKS cluster (requiring cluster to be re-created), the cluster is destroyed without removing managed kubernetes resources.  This leads to it referencing the current `.kube/config` for future actions rather than the state file.

### Terraform Version
```
Terraform v0.12.28
+ provider.azurerm v1.44.0
+ provider.kubernetes v1.11.3
+ provider.template v2.1.2
+ provider.time v0.5.0
```

### Expected Behavior

`terraform apply` causing a cluster to be recreated should first destroy all managed k8s resources that are dependent on it.

### Actual Behavior

AKS cluster was destroyed.  Storage account and Load Balancer in the managed resource group (along with the managed resource group) were not destroyed.

Trying to re-create (to switch from Basic to Standard LB) failed due to the LB still existing.  Using `terraform destroy` to finish removing the remaining resources (storage/lb) went through and also destroyed namespaces/service accounts/role bindings (part of the initial deployment to ensure standard objects existed in k8s) using the current .kube/config file (pointing to a different cluster).

**Comment by mildwonkey** [comment]
Hi @jleechp-occm , I am sorry you are experiencing this.

We cannot troubleshoot your problem without more information. At minimum we'll need to see your full configuration, or a smaller example that reproduces the issue, as well as the `TRACE` log output.
 
Please open a new issue, filling out the entire issue template, if you still need assistance. Thanks!
