### ISSUE TITLE
TF 0.6: prompting for values even though default is defined

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#2592]
Just updated to 0.6.0 and now variables that have defaults are prompting for a value. Ideally it would use the default value silently. I couldn't find any PR's or issues describing the new behavior. Is this intentional or oops?

**Comment by phinze** [comment]
@nathanielks thanks for the report! We actually noticed something similar as we rolled 0.6.0 out to Atlas.

I'll do some more testing to figure out where the behavior change is coming from, but in the meantime you can always add the `-input=false` flag or set the `TF_INPUT=0` env variable to opt-out of this behavior.

**Comment by nathanielks** [comment]
@phinze aha, thanks for that!

**Comment by nathanielks** [comment]
@phinze would it be helpful if I started documentation on the various env variables? So far I'm aware of:

- TF_LOG
- TF_LOG_PATH
- TF_INPUT
- TF_MODULE_DEPTH
- TF_VAR_name
- TF_DEV
- TF_QUICKDEV
- TF_ACC
- TF_PLUGIN_MIN_PORT
- TF_PLUGIN_MAX_PORT
- TF_PLUGIN_MAGIC_COOKIE

**Comment by phinze** [comment]
@nathanielks yeah might be worth gathering them all into one place - though we should probably categorize them since some are really only for development while others are actually useful to users

**Comment by mitchellh** [comment]
Agreed with @phinze that we shouldn't doc the dev ones except for perhaps in the README or contributors guide.

**Comment by nathanielks** [comment]
will do. Where'd you like me to write those up? I can get started on that tonight.

**Comment by phinze** [comment]
@nathanielks good question! perhaps a new "Environment Variables" page under "Configuration"?

**Comment by nathanielks** [comment]
@phinze that sounds pretty good to me.

**Comment by phinze** [comment]
I think the relevant code change here is https://github.com/hashicorp/terraform/pull/2502

**Comment by phinze** [comment]
Okay, so that code change uncovered the core bug here that's been hanging out for some time: terraform is prompting for any variables without values, even if they have defaults set.

Tagged and we'll get this fixed up!

**Comment by nathanielks** [comment]
whoop whoop!

**Comment by nathanielks** [comment]
Okie doke, here's my first go at it: https://github.com/hashicorp/terraform/pull/2601

**Comment by RichSteele** [comment]
Thanks, just ran into this myself and caused some head scratching for me.

**Comment by RichSteele** [comment]
I'm afraid I'm still seeing this behavior after updating and building locally.  In my case I'm using the OpenStack provider and not specifying the openstack.api_key and openstack.endpoint_type which aren't required (according to the docs) but am still getting prompted for them.  (I suppose the docs could be wrong, but everything works as expected if I specify blank values for them so I suspect not.)

**Comment by phinze** [comment]
Hi @RichSteele - this issue was specifically around variables (i.e. `variable "foo" {}`). That sounds like it might be a bug with provider attributes. Do you think you could open a separate issue with your config? Then we can get it looked at and fixed. :+1:

**Comment by phinze** [comment]
@RichSteele ah I hadn't seen this PR #2626 - will be fixed it 0.6.1!

**Comment by RichSteele** [comment]
Awesome, thanks, I misread this defect.  I hadn't thought to look through the pull requests for it.

**Comment by mildwonkey** [comment]
@umeshksingla - I haven't seen any requests for that feature; you can open a feature request!

**Comment by naumannt** [comment]
@umeshksingla did you ever open a feature request for this? I would also like that feature very much!

**Comment by codejamninja** [comment]
:+1:

**Comment by umeshksingla** [comment]
@naumannt @codejamninja I did. Here #18702

**Comment by codejamninja** [comment]
@umeshksingla how do you control showing the default or not showing the default?
