### ISSUE TITLE
Can't configure two versions of one provider

### ISSUE THREAD

**Issue by hfrog** [hashicorp/terraform#25935]
### Terraform Version

```
Terraform v0.13.0
```

### Terraform Configuration Files

```
versions.tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 3.0"
    }
    google-2 = {
      source  = "hashicorp/google"
      version = "~> 2.0"
    }
  }
  required_version = ">= 0.13"
}

manifest.tf
provider "google-2" {
  region  = "europe-west1"
  alias = "legacy"
}

provider "google" {
  region  = "europe-west1"
}

module "custom_legacy_module" {
  source = "..."

  providers = {
    google = google-2.legacy
  }
}
```

### Debug Output

https://gist.github.com/hfrog/d740a7aff7e5f9464bb67ab0f2e48db7

Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the given constraints ~> 3.0, ~> 2.0

### Expected Behavior

I expect to get one provider with two versions and names: hashicorp/google v3.0+ as google, and hashicorp/google v2.0+ as google-2.

### Actual Behavior

Terraform tries to find a version 2.0+ and 3.0+ at the same time, and fails.

### Steps to Reproduce

terraform init

### Additional Context

https://www.terraform.io/docs/configuration/provider-requirements.html states:
each provider can have one or more distinct versions, allowing the functionality of the provider to evolve over time

**Comment by mildwonkey** [comment]
hi @hfrog ! 

I'm sorry that the documentation is unclear on this, and I will label this issue appropriately so we can clear that page up. Thank you for reporting this.

A terraform configuration can only use a single version of any given provider. You can have multiple version constraints for one provider as long as there is one or more versions of that provider that meets all constraints (so you can't say, for example, > 1.0 and < 1.0 in the same configuration).

You can _not_ have two different versions of a single provider in a configuration; terraform uses the source address of the provider to disambiguate and so it can't have multiple providers with the same source.

Sorry again for the confusion!

**Comment by hfrog** [comment]
Hi @mildwonkey !
Thank you for the clarification.
