### ISSUE TITLE
Backend config has no effect in modules

### ISSUE THREAD

**Issue by manoadamro** [hashicorp/terraform#25933]
### Current Terraform Version

```
0.13.0
```

### Use-cases
When things are improperly configured or actions within terraform fail.

### Proposal
There are a few cases where things fail silently and give absolutely no feedback.

1) string interpolation in backend.

The docs say:
```
Only one backend may be specified and the configuration may not contain interpolations. Terraform will validate this.
```
 If you use string interpolation, say in the prefix value, you get no error, nothing. Terraform plan/apply does it's thing, just no state gets stored. If terraform is actually validating this, it doesn't give any feedback on its findings.

2) hard coded backend.
Similarly, without string interpolation (just a straight up string), my state was also not being stored, the target bucket was empty and again, zero feedback from terraform. 

On both of these occasions, it was a long time before I realised no state was being stored (I figured if something so fundamental had gone wrong, it would have at least shown a warning?)

If state has been configured to be stored in a bucket, and storing the state in that bucket fails, this should not be silent, terraform should shout loudly.

**Comment by jbardin** [comment]
Hi @manoadamro,

This is certainly the intent when initializing the configuration directory. Can you provide an example where terraform is not validating interpolations in the backend configuration?

You should be seeing an immediate error like:

```
Initializing the backend...

Error: Variables not allowed

  on main.tf line 3, in terraform:
   3:     path = var.foo

Variables may not be used here.
```

**Comment by manoadamro** [comment]
```
terraform {
  backend "gcs" {
    bucket = "vulcan-terraform-state"
    prefix = "github.com/dyad-ai/vulcan/terraform/infrastructure/cluster/${var.cluster_name}"
  }
}
```

I get no errors, clusters are created, everything appears to work exactly as it should:
`Apply complete! Resources: 5 added, 0 changed, 0 destroyed.`

except the state file `terraform.tfstate` is in my cwd and not in the cluster.

**Comment by jbardin** [comment]
Thanks @manoadamro, but I still can't reproduce this. 

```

Error: Variables not allowed

  on main.tf line 4, in terraform:
   4:     prefix = "github.com/dyad-ai/vulcan/terraform/infrastructure/cluster/${var.cluster_name}"

Variables may not be used here.
```

Can you post the trace log from `terraform init` in case that has some more info that may help?

**Comment by manoadamro** [comment]
@jbardin thanks for your reply,
I think I've figured this out, I had my backend in a module (probably should have mentioned that, sorry), which appears to make it behave differently. I do get the error when I use a straight variable (no string interpolation) though.
The docs here https://www.terraform.io/docs/backends/config.html do say that you can only have one backend per specification, so that's definitely on me, however it does also say "Terraform will validate this."

backend at root level:
```
Error: Variables not allowed

  on backend.tf line 4, in terraform:
   4:     prefix = "github.com/dyad-ai/vulcan/terraform/infrastructure/cluster/${var.cluster_name}"

Variables may not be used here.
```

same backend in module
```
Initializing modules...
- live-app-dns in modules/cluster
- live-data-dns in modules/cluster

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.12.0...
- Downloading plugin for provider "google" (hashicorp/google) 3.35.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.google: version = "~> 3.35"
* provider.kubernetes: version = "~> 1.12"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

```

**Comment by jbardin** [comment]
Thanks @manoadamro,

Yes, backends must be defined in the root module; using a module should not be able to change how the state is stored. 
It may be possible to validate this in the future, in the meantime we can also check that the docs make this more clear.

Thanks!

**Comment by manoadamro** [comment]
@jbardin thanks for your time and help 🌮
