### ISSUE TITLE
Extend plugin protocol to allow providers to define custom terraform functions

### ISSUE THREAD

**Issue by iwarapter** [hashicorp/terraform#25940]
### Use-cases

Providers could supply additional helper functions to make using their resources more easy, instead of using local-exec or other hacks for functionality not provided by the core terraform functions.

### Proposal

Allow providers to expose terraform functions 
https://www.terraform.io/docs/configuration/functions.html

### References

https://discuss.hashicorp.com/t/extendable-terraform-functions/13023

**Comment by mildwonkey** [comment]
HI @iwarapter ! Thank you for opening this feature request - it's an interesting idea! Can you give some examples of your use-case? I would think that any function that would be useful for a single provider would be something we would want to enable for all users, so I'm very curious to hear what kind of provider-specific functions you are thinking of!

**Comment by iwarapter** [comment]
Hi @mildwonkey, sorry for the extremely late reply 😂 .

I was originally looking for support for more crypto specific functions, such as RSA/EC to JWKS transformation. However I think this (specific) use-case might actually be best suited in terraform. I have raised #30419 to track this and https://github.com/hashicorp/terraform/pull/30420 as a draft implementation.

Thanks!

**Comment by apparentlymart** [comment]
Hi @iwarapter!

As I mentioned over in #30419, I'm going to close this in favor of the existing #2771, just to consolidate the discussion. I'm sorry we didn't notice this was a duplicate when you originally opened it.

Thanks!
