### ISSUE TITLE
Terraform 0.13 upgrade: Terraform confused between "-/provider" and "hashicorp/provider"

### ISSUE THREAD

**Issue by sdebruyn** [hashicorp/terraform#25951]
### Terraform Version
```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.23.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
```

### Configuration
We have a root module that has the provider config for providers that need it (e.g. `azurerm`) and implicit configs for other providers (e.g. `random`)
The child modules implicitly inherit these provider configs.
Both the root and all childs modules have a `versions.tf` that is created by the `terraform 0.13upgrade` command.

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
    random = {
      source = "hashicorp/random"
    }
  }
  required_version = ">= 0.13"
}
```

### Debug Output
```
Error: Provider configuration not present

To work with module.databricks.data.azurerm_client_config.current its original
provider configuration at provider["registry.terraform.io/-/azurerm"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.databricks.data.azurerm_client_config.current, after which you can
remove the provider configuration again.
```

It looks like Terraform is confused between `registry.terraform.io/-/azurerm` and `hashicorp/terraform`. We can't delete our resources anymore because of this issue. **Adding a provider config in the child module does not make any difference.**

### Expected Behavior
When we delete a resource, the resource should be deleted.

### Actual Behavior
When we delete a resource, we get the error above. There are still other resources from the same provider in the same module. A provider config does not make a difference.

### Steps to Reproduce
1. `terraform apply`

**Comment by sdebruyn** [comment]
This documentation page explicitly mentions that you don't have to write any provider configuration in child modules as long as the root has one: https://www.terraform.io/docs/configuration/providers.html#provider-configuration-1

> Provider configurations belong in the root module of a Terraform configuration. (Child modules receive their provider configurations from the root module; for more information, see Providers Within Modules.)

**Comment by sdebruyn** [comment]
At the moment my state file has the old provider configs, e.g.

```
    {
      "module": "module.databricks",
      "mode": "data",
      "type": "azurerm_client_config",
      "name": "current",
      "provider": "provider.azurerm",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "client_id": "...",
            "id": "2020-07-29 11:12:15.323456432 +0000 UTC",
            "object_id": "...",
            "subscription_id": "...",
            "tenant_id": "...",
            "timeouts": null
          }
        }
      ]
    },
```

When I run the module on a fresh state, it sets the new provider source:

```
    {
      "module": "module.databricks",
      "mode": "data",
      "type": "azurerm_client_config",
      "name": "current",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
...
            "timeouts": null
          }
        }
      ]
    }
```

Terraform should understand that this is the same provider, but apparently it doesn't.

**Comment by sdebruyn** [comment]
The `replace-provider` command fixed it for me. Shouldn't Terraform do this automatically?

**Comment by IanMoroney** [comment]
Must be a bug in the 0.13 upgrade.
I ran into this issue for the second time, just earlier.
I had to run the `replace-provider` command and it modified a whole lot of things in the state to fix the issue.

It seems to be a non-issue until it becomes an issue, like a land mine. Then loads of state changes have to be made to fix the problem, then it's fine.

**Comment by golance-mightydevops** [comment]
Guys,

**So I am very confused with the workflow to upgrade to 0.13**

I had a working 0.12.6 terraform code
installed terraform 0.13.0 CLI

any command from terraform gives me a bunch of 

```
Error: Unsupported Terraform Core version

  on .terraform/modules/vpc.vpc/terraform-aws-vpc-2.33.0/versions.tf line 2, in terraform:
   2:   required_version = "~> 0.12.6"

Module module.vpc.module.vpc (from terraform-aws-modules/vpc/aws) does not
support Terraform version 0.13.0. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.
```

if I run 0.13upgrade

```
➜ terraform 0.13upgrade  -yes                              

Upgrade complete!

Use your version control system to review the proposed changes, make any
necessary adjustments, and then commit.
```

it just updates my root/config.tf

```
diff --git a/config.tf b/config.tf
index 31050f2..29f66eb 100644
--- a/config.tf
+++ b/config.tf
@@ -5,8 +5,14 @@ terraform {
   required_version = "~> 0.13.0"
 
   required_providers {
-    aws  = "~> 2.60"
-    null = "~> 2.1"
+    aws = {
+      source  = "hashicorp/aws"
+      version = "~> 2.60"
+    }
+    null = {
+      source  = "hashicorp/null"
+      version = "~> 2.1"
+    }
   }
 }
```

I tried to remove .terraform and run `terraform init`, everything worked but then the next command I ran gives me this

```
➜ terraform apply -var-file env.auto.tfvars

Error: Provider configuration not present

To work with
module.kubernetes.module.eks-cluster.data.null_data_source.node_groups[0] its
original provider configuration at provider["registry.terraform.io/-/null"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.kubernetes.module.eks-cluster.data.null_data_source.node_groups[0],
after which you can remove the provider configuration again.

Releasing state lock. This may take a few moments...
```

I am using terraform-cloud for remote state management. 

So what should I do to update to 0.13 and upgrade the state. 



but then

**Comment by IanMoroney** [comment]
Inside every module you have, you need to cd into that module, and also run the upgrade command.

**Comment by golance-mightydevops** [comment]
I did that - same outcome.

**Comment by IanMoroney** [comment]
Also, in terraform cloud, inside workspace settings > general, you need to update the terraform version here
![image](https://user-images.githubusercontent.com/10791260/91282992-f4ad0a80-e781-11ea-9fab-d46966f356b9.png)

**Comment by mildwonkey** [comment]
Hi folks, sorry for the confusion! When you see `-/` in a provider source string, that indicates that terraform found a "legacy" provider in state and is querying the Registry for the provider's namespace. `-` is a special namespace; when terraform queries the registry using that namespace the registry will respond with the providers _real_ namespace (provided it is a HashiCorp or partner provider - all the official providers that terraform was able to automatically download in v0.12). It's normal, and not an issue, to see this during your first `init` in v0.13 when you have v.012 state.

This behavior - and an optional workaround, which was mentioned in the comments already: `terraform state replace-providers`, is covered in [this section](https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers) of the upgrade guide. You don't *have* to do anything, however - terraform will update the state after the first `apply` and you shouldn't see any odd-looking providers again.

To clarify something else I've seen in the comments: you do not need to put your provider _configuration_ in every single module, but every module MUST have a `required_providers` entry for all (non-HashiCorp) providers in that module. The configuration can still be inherited, but only if the source addresses match (so for e.g., if I forked the aws provider and wanted to use it in one module, I couldn't expect it to inherit the configuration for the official aws provider: `"hashicorp/aws"` can't inherit a configuration for `"mildwonkey/aws"`).

This has come up a number of times, so I'm going to label this issue as a documentation issue and see what I can do about making this easier to find in the upgrade guide. Thanks for letting us know, and sorry for the confusion!

**Comment by mildwonkey** [comment]
Whoops, I updated the docs and forgot to close this!
