### ISSUE TITLE
The of use variables in module providers block

### ISSUE THREAD

**Issue by nael-fridhi** [hashicorp/terraform#25978]
### Current Terraform Version

```
0.12.28
```

### Use-cases

- The Goal of the feature is to pass the provider where my infrastructure will be created as a variable: 

In my terraform configuration files i use different providers with alias and I have created a pipeline to apply my infrastructure but I want that my infrastructure  will be created depending of an input variable to specify the alias and the provider terraform will use to generate the infrastructure.

### Attempted Solutions

```
provider "aws" {
  alias       = "alias-1"
  ...
}

provider "aws" {
  alias       = "alias-2"
  ...
}

variable "provider_alias" {
  default = "alias-1"
}

module "compute" {
  providers = {
    aws= var.provider_alias
  }
  source       = ...
}
```
when I run ```terraform validate``` I got "missing provider provider.var.provider_alias"

**Comment by jbardin** [comment]
Hi @nael-fridhi 

We have a couple open requests to cover this use case already:
 - #25244
 - #24476

Thanks!
