### ISSUE TITLE
0.13 crash when running init -reconfigure -backend-config

### ISSUE THREAD

**Issue by civ0** [hashicorp/terraform#25976]
### Terraform Version

```
Terraform v0.13.0
```

### Terraform Configuration Files

main.tf
```terraform
variable "bucket" {}
variable "dynamodb_table" {}
variable "encrypt" {}
variable "envname" {}

locals {
  tags = {
    Terraform   = "remote-state",
    Environment = var.envname,
    Application = "terraform-remote-state"
  }
}

module "backend" {
  source = "git::https://gitlab.example.de/.../aws-backend.git?ref=v0.1.1"

  bucket         = var.bucket
  dynamodb_table = var.dynamodb_table
  tags           = local.tags
}
```

terraform.tf
```terraform
terraform {
  backend "s3" {
    key = "remote_state.tfstate"
  }
}
```

prod.hcl
```terraform
bucket         = "bucket-name"
dynamodb_table = "dynamodb-name"
encrypt        = true
region         = "eu-central-1"
```

### Crash Output

https://gist.github.com/civ0/a3b45751f4d9aac5c77651a7b07ef236

### Expected Behavior

Successfull reconfigure of the backend or error message.

### Actual Behavior

Crash

### Steps to Reproduce

I cannot provide full resources for this crash, because it contains internal tooling, but these are the basic steps:

1. Create a terraform stack with a S3 Backend and local state (I did this using modules, but this step did not produce the crash).
In this first step the S3-Bucket und DynamoDB table are created with Terraform and the state is stored locally.
2.  Run `terraform init -reconfigure -backend-config ../prod.hcl`

**Comment by alisdair** [comment]
This bug should be fixed as part of #25960 and will be released as part of Terraform 0.13.1.
