### ISSUE TITLE
Incorrect change count

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#2597]
I've made a simple change to a Terraform config file - adding a Name Tag to an `aws_instance`. Here's the output from `terraform plan`:

```
~ aws_instance.bastion_nat
    tags.#:    "0" => "1"
    tags.Name: "" => "empire-bastion-nat"

Plan: 0 to add, 15 to change, 0 to destroy.
```

`15 to change` is incorrect. I'm running the recent 0.6.0 release.

**Comment by phinze** [comment]
Hi @pikeas - this is a dup of https://github.com/hashicorp/terraform/issues/2590, but thanks for the report! You can track that issue to learn when we push a fix.
