### ISSUE TITLE
Terraform does not cleanup tmp folder after init

### ISSUE THREAD

**Issue by awasilyev** [hashicorp/terraform#25977]
### Terraform Version
```
terraform --version
Terraform v0.13.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
version = "~> 2.57"
}
```

### Debug Output

https://gist.github.com/awasilyev/a9b4186100ab9691b9da63afff41ed11

### Expected Behavior
no terraform temporary files after init

### Actual Behavior

$ ls -l /tmp/terraform-provider447340969
-rw------- 1 ubuntu docker 36641765 Aug 24 10:54 /tmp/terraform-provider447340969

### Steps to Reproduce
export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
mkdir -p $HOME/.terraform.d/plugin-cache
terraform init

### Additional Context
TF_PLUGIN_CACHE_DIR env var is defined

**Comment by alisdair** [comment]
Thanks for reporting this! There's a fix and an explanation in #25990.
