### ISSUE TITLE
Could not delete AWS API Gateway authorizer using terraform due to conflict exceptions

### ISSUE THREAD

**Issue by ashokdasari06** [hashicorp/terraform#25980]
I have added a request based authorizer to my API config and that worked fine. I am trying to delete the authorizer from my config and Terraform removes the authorizer from the state file but not from the console. Error from the Cloudtrail logs when terraform is trying to delete the authorizer is as below. Terraform is trying to delete the authorizer prior to updating the authorizer in the methods to null. We tried to create dependencies between authorizer and method and that throws cycle errors. All i want is the method updates to happen prior to deletion of authorizer. Am using terraform 0.12.24.

"errorCode": "ConflictException",
"errorMessage": "Cannot delete authorizer 'xxxx', is referenced in method: GET//test",

resource "aws_api_gateway_authorizer" "api_authorizer" {
  count          = var.enabled && var.has_authorizer_from_formation ? 1 : (var.authorizer_lambda_arn != "" ? 1 : 0)
  name           = "${var.environment}-${var.app_name}-api-gw-authorizer"
  rest_api_id    = aws_api_gateway_rest_api.api[0].id
  authorizer_uri = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${var.authorizer_lambda_arn}/invocations"

  type                             = var.authorizer_type == "REQUEST" ? "REQUEST" : "TOKEN"
  identity_source                  = var.authorizer_type == "REQUEST" ? var.authorizer_identity_source : local.default_authorizer_identity_source
  authorizer_result_ttl_in_seconds = var.authorizer_result_ttl_in_seconds
}

resource "aws_api_gateway_method" "api_method" {
  for_each = var.enabled ? local.api_resources_key_set : toset([])

  rest_api_id = aws_api_gateway_rest_api.api[0].id
  resource_id = aws_api_gateway_resource.api_resource[var.api_resources[each.key].path].id
  http_method = var.api_resources[each.key].http_method
  request_parameters = zipmap(formatlist("method.request.querystring.%s", var.api_resources[each.key].query_params), [for i in var.api_resources[each.key].query_params : false])

  authorization = local.has_authorizer ? "CUSTOM" : (var.enable_iam_authorization ? "AWS_IAM" : "NONE")
  authorizer_id = local.has_authorizer ? aws_api_gateway_authorizer.api_authorizer[0].id : ""
}

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in the AWS Terraform provider, rather than in core. This GitHub repository is for issues specifically about Terraform core, and issues specific to individual providers are tracked in other repositories. I'm going to label it as such, and the HashiBot will shortly migrate it over to the AWS provider. Please feel free to re-open this if they determine that it is indeed an issue that needs to be addressed in Terraform core.
