### ISSUE TITLE
Terraform 0.13 not implicitly passing provider configs for third-party providers properly

### ISSUE THREAD

**Issue by aequasi** [hashicorp/terraform#25984]
### Terraform Version

```
Terraform v0.13.0
```

### Terraform Configuration Files

https://github.com/aequasi/terraform-13-custom-provider-test

### Debug Output

```
❯ TF_LOG=trace tfm init
2020/08/24 19:54:06 [INFO] Terraform version: 0.13.0  
2020/08/24 19:54:06 [INFO] Go runtime version: go1.14.2
2020/08/24 19:54:06 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/08/24 19:54:06 [DEBUG] Attempting to open CLI config file: /home/aaron/.terraformrc
2020/08/24 19:54:06 Loading CLI configuration from /home/aaron/.terraformrc
2020/08/24 19:54:06 [DEBUG] checking for credentials in "/home/aaron/.terraform.d/plugins"
2020/08/24 19:54:06 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/08/24 19:54:06 [DEBUG] will search for provider plugins in /home/aaron/.terraform.d/plugins
2020/08/24 19:54:06 [DEBUG] ignoring non-existing provider search directory /home/aaron/.local/share/terraform/plugins
2020/08/24 19:54:06 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2020/08/24 19:54:06 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2020/08/24 19:54:06 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2020/08/24 19:54:06 [INFO] CLI command args: []string{"init"}
2020/08/24 19:54:06 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
Initializing modules...
2020/08/24 19:54:06 [DEBUG] Module installer: begin _
2020/08/24 19:54:06 [TRACE] ModuleInstaller: Module installer: _ <nil> already installed in test
2020/08/24 19:54:06 [DEBUG] Module installer: begin _._
2020/08/24 19:54:06 [TRACE] ModuleInstaller: Module installer: _._ <nil> already installed in test/test
2020/08/24 19:54:06 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json

Initializing the backend...
2020/08/24 19:54:06 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/08/24 19:54:06 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/08/24 19:54:06 [DEBUG] New state was assigned lineage "ea6df296-0437-caf5-02b3-704176a04224"
2020/08/24 19:54:06 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/08/24 19:54:06 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/08/24 19:54:06 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
2020/08/24 19:54:06 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/aequasi/discord v0.0.2 for linux_amd64 at .terraform/plugins/registry.terraform.io/aequasi/discord/0.0.2/linux_amd64
2020/08/24 19:54:06 [TRACE] providercache.fillMetaCache: including .terraform/plugins/registry.terraform.io/aequasi/discord/0.0.2/linux_amd64 as a candidate package for registry.terraform.io/aequasi/discord 0.0.2
2020/08/24 19:54:06 [DEBUG] checking for provisioner in "."
2020/08/24 19:54:06 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/08/24 19:54:06 [DEBUG] checking for provisioner in "/home/aaron/.terraform.d/plugins"
2020/08/24 19:54:06 [DEBUG] found provisioner "terraform-provisioner-ansible_v2.1.0"
2020/08/24 19:54:06 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2020/08/24 19:54:06 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2020/08/24 19:54:06 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/08/24 19:54:06 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/08/24 19:54:06 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay

2020/08/24 19:54:06 [TRACE] statemgr.Filesystem: read nil snapshot
2020/08/24 19:54:06 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
Initializing provider plugins...
2020/08/24 19:54:06 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/aequasi/discord v0.0.2 for linux_amd64 at .terraform/plugins/registry.terraform.io/aequasi/discord/0.0.2/linux_amd64
2020/08/24 19:54:06 [TRACE] providercache.fillMetaCache: including .terraform/plugins/registry.terraform.io/aequasi/discord/0.0.2/linux_amd64 as a candidate package for registry.terraform.io/aequasi/discord 0.0.2
2020/08/24 19:54:06 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/08/24 19:54:06 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
- Using previously-installed aequasi/discord v0.0.2
- Finding latest version of hashicorp/discord...
2020/08/24 19:54:06 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/discord/versions
2020/08/24 19:54:06 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/discord/versions
2020/08/24 19:54:06 [TRACE] providercache.fillMetaCache: using cached result from previous scan of .terraform/plugins
2020/08/24 19:54:06 [DEBUG] GET https://registry.terraform.io/v1/providers/-/discord/versions
2020/08/24 19:54:06 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/discord/versions

Error: Failed to install provider

Error while installing hashicorp/discord: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/discord
```

### Crash Output

None

### Expected Behavior

Terraform should only attempt to install aequasi/discord

### Actual Behavior

Terraform downloads aequasi/discord for the top-level module, and then attempts to install hashicorp/discord for the child modules

### Steps to Reproduce

clone the above repo, and run `terraform init`

**Comment by alisdair** [comment]
Thanks for reporting this, and especially for the full configuration reproducing the issue!

What you're seeing here is actually the intended behaviour. Each module must declare its own provider requirements, so you'll need a configuration block like this in each module:

```hcl
terraform {
  required_providers {
    discord = {
      source = "aequasi/discord"
    }
  }
}
```

Once you've done this, the `discord` provider configuration in your root module should be inherited by the rest of your module tree, as the provider source addresses will then match.

An explanation of what's happening here might help. While provider configurations defined using a provider block with the local name (e.g. `provider "discord" { }`), they are inherited based on the fully-qualified provider source address (e.g.  `registry.terraform.io/aequasi/discord`). Modules do not inherit a mapping of provider local name to fully-qualified source address, so any child modules without a `required_providers` block will fall back on the implicit provider source address rules.

The reason for this is that it's completely valid for a configuration to have multiple providers with the same local name (i.e. `discord`) but different source addresses. Your configuration could have a module which uses the `hashicorp/discord` provider, and it should not inherit the provider configuration from the `aequasi/discord` provider.

There's a lot more on this in the [Providers Within Modules documentation](https://www.terraform.io/docs/configuration/modules.html#providers-within-modules), as well as the [Provider Configuration docs](https://www.terraform.io/docs/configuration/providers.html). I hope this clarifies what's happening here!

**Comment by aequasi** [comment]
The documentation says that provider configs are implicitly passed for unaliased providers: https://www.terraform.io/docs/configuration/modules.html#implicit-provider-inheritance

Is this considered an aliased provider? If so, this is very unfriendly DX :/

**Comment by alisdair** [comment]
It's not an aliased provider, and the config should be passed implicitly, as long as you add the `required_providers` block to let Terraform know that your module maps `discord` to `aequasi/discord`.

**Comment by aequasi** [comment]
https://github.com/aequasi/terraform-13-custom-provider-test/blob/master/terraform.tf#L4-L9

I believe i'm doing that here.

**Comment by alisdair** [comment]
Every module using a non-default provider needs this same `required_providers` block, so that Terraform knows which provider is represented by `discord`. If you copy that same section to all modules using your `aequasi/discord` provider, I believe that should solve the problem.

**Comment by aequasi** [comment]
It does, but that's a really poor DX :/ Prevents any sort of organization using modules. The documentation on this wasn't super clear. I would expect *any* non-aliased provider (default or not) to be implicitly passed down through children modules.

**Comment by alisdair** [comment]
I'm sorry that the documentation wasn't clear on this. I've tried to add a note for future developers to clarify this: #25994

Can you explain why you feel this prevents any sort of organization using modules? We'd like to improve this if we can.

Here's some perspective on how we arrived at this point. We want Terraform modules to be self-contained representations of configuration, with clearly defined input variables and outputs. Modules should be written to be reusable, even if they're only used once.

As a result, each module should explicitly declare exactly which providers it should be used with. This is why we expect a `required_providers` block for each module.

For modules depending on default providers, the source address can be omitted. But now that we have introduced non-default providers in Terraform 0.13, it becomes essential for each module using such a provider to explain for example that provider `discord` is actually `aequasi/discord`, and not `alisdair/discord` or `hashicorp/discord`. Since there can be any number of `discord` providers (even multiple in one configuration!) we need to be explicit about which one our module depends on.

I hope that clarifies what led to this approach, and I also hope the doc update helps a bit in future.

**Comment by aequasi** [comment]
I suppose the lack of being able to organize better may be due to me using modules improperly. 

I'm not sure how familiar you are with [Discord](https://discord.com), but to explain what I'm trying to do briefly:

Trying to create a server, with multiple categories of channels inside the server.
I want to separate the categories in to their own directories to keep them organized, and to avoid clashing of keys.

* `terraform.tf`
* `provider.tf`
* `server.tf`
* `categories.tf` (Creates the modules)
* **Categories**
    * *information*
        * `provider.tf`
        * `terraform.tf`
        * `channels.tf`
        * `permissions.tf`
    * *chatting* (Same structure as information)
    * *media* (Same structure as information)
    * *staff* (Same structure as information)

**Comment by alisdair** [comment]
I'm familiar with Discord! I don't quite have enough information to say whether or not this is a good use of modules, but my instinct is that the categories _might_ be better represented using data, and a module could be used to represent the Terraform resources needed to instantiate any given category & its channels. Then you'd pass the data to several instances of that single module.

This is turning into more of a discussion than a bug report, and I'd recommend continuing it [on the Terraform discussion forum](https://discuss.hashicorp.com/c/terraform-core/27) if you're interested!

**Comment by rymir** [comment]
@alisdair thanks for the details, I'm not getting the reason why this behaviour isn't just an "opt-in" though, overriding the non-default 3rd party providers in the root child modules whenever there's a need to do so and otherwise going forward with the source/version declared in the root?

In our case, we have hundreds of terraform states and hundreds of terraform modules. Explicitly configuring the defaults throughout the codebase feels unnecessary, given that we always stick with the root versions compatibility.
