### ISSUE TITLE
Terraform v0.13 doesn't support coexistence of both local and remote provider but different versions

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform#25985]
### Terraform Version

```
Terraform v0.13.0
```

### Terraform Configuration Files

```terraform
provider "azurerm" {
  features {}
}
```

### Steps to Reproduce

1. Setup following directory structure:

        💤 tree $HOME/.terraform.d 
        /home/magodo/.terraform.d
        ├── checkpoint_cache
        ├── checkpoint_signature
        └── plugins
            └── registry.terraform.io
                ├── hashicorp
                │   └── azurerm
                │       └── 99.99.99
                │           └── linux_amd64
                │               └── terraform-provider-azurerm_v99.99.99 -> /home/magodo/go/bin/terraform-provider-azurerm
                └── magodo
                    └── demo
                        └── 99.99.99
                            └── linux_amd64
                                └── terraform-provider-demo_v99.99.99 -> /home/magodo/go/bin/terraform-provider-demo
2. Run `terraform init`, which successfully find the local version of azurerm provider
3. Adding a version constraint in the terraform config file
4. Run `terraform init` again

### Debug Output

```
💤 TF_LOG=DEBUG tf init
2020/08/25 11:27:23 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/08/25 11:27:23 [INFO] Terraform version: 0.13.0  
2020/08/25 11:27:23 [INFO] Go runtime version: go1.14.6
2020/08/25 11:27:23 [INFO] CLI args: []string{"/home/magodo/.local/bin/terraform", "init"}
2020/08/25 11:27:23 [DEBUG] Attempting to open CLI config file: /home/magodo/.terraformrc
2020/08/25 11:27:23 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/08/25 11:27:23 [DEBUG] checking for credentials in "/home/magodo/.terraform.d/plugins"
2020/08/25 11:27:23 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/08/25 11:27:23 [DEBUG] will search for provider plugins in /home/magodo/.terraform.d/plugins
2020/08/25 11:27:23 [DEBUG] ignoring non-existing provider search directory /home/magodo/.local/share/terraform/plugins
2020/08/25 11:27:23 [DEBUG] ignoring non-existing provider search directory /home/magodo/.local/share/flatpak/exports/share/terraform/plugins
2020/08/25 11:27:23 [DEBUG] ignoring non-existing provider search directory /var/lib/flatpak/exports/share/terraform/plugins
2020/08/25 11:27:23 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2020/08/25 11:27:23 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2020/08/25 11:27:23 [INFO] CLI command args: []string{"init"}
2020/08/25 11:27:23 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

2020/08/25 11:27:23 [DEBUG] New state was assigned lineage "643bd8b3-a995-b8b7-a51b-a0198d1d49bb"
Initializing the backend...
2020/08/25 11:27:23 [DEBUG] checking for provisioner in "."
2020/08/25 11:27:23 [DEBUG] checking for provisioner in "/home/magodo/.local/bin"
2020/08/25 11:27:23 [DEBUG] checking for provisioner in "/home/magodo/.terraform.d/plugins"
2020/08/25 11:27:23 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "2.20.0"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/azurerm: no available releases match the given constraints 2.20.0
```

### Expected Behavior

Terraform automatically download the 2.20.0 azurerm provider from remote and place it to both plugin search directory and plugin cache directory.

### Actual Behavior

Terraform can't find the 2.20.0 azurerm provider. Does it just stop querying remote registry now that it find a azurerm provider in local plugin search directory?

### Additional Context

I have no special setting for the filesystem mirror.

**Comment by alisdair** [comment]
I'm able to reproduce this behaviour locally. Thanks for the clear report!

When investigating the cause, [I found this PR which intended this to be the installer behaviour](https://github.com/hashicorp/terraform/pull/24689) for the implicit global cache, in order to match 0.12. Any providers found in the global cache directory are only installed from the cache, and the registry is not queried:

https://github.com/hashicorp/terraform/blob/af2fb8f5260cd3077a0701a862fc225f2dadd9dd/provider_source.go#L163-L168

Note that [this behaviour can be overridden using `provider_installation` configuration](https://www.terraform.io/docs/commands/cli-config.html#provider-installation). That is, you can specify configuration like this `~/.terraform.d/providercache.tfrc`:

```hcl
provider_installation {
  filesystem_mirror {
    path = "~/.terraform.d/plugins"
  }
  direct {
    exclude = []
  }
}
```

I believe this configuration will result in the behaviour you expected: both the global cache and the registry will be consulted in that order of priority. Does this satisfy your use case?

**Comment by magodo** [comment]
@alisdair Thank you for your quick response :+1:

The code and the solution make total sense, and I can verify that it works! Whilst I have some further uncertainties here:

1. From the code in *provider_source.go*, it seems that the config dir (i.e. *$HOME/.terraform.d/plugins*) is treated as implicit local mirror, which unfortunately is not listed in the [document](https://www.terraform.io/docs/commands/cli-config.html#implied-local-mirror-directories).
2. You suggested to add the `provider_installation` snippet in file *~/terraform.d/providercache.tfrc* whilst the [document](https://www.terraform.io/docs/commands/cli-config.html#location) says:

    >  the file must be named .terraformrc

**Comment by alisdair** [comment]
Agreed, thanks for pointing that out!

I think I probably misspoke in recommending creating an additional CLI configuration file in `~/.terraform.d/*`—that might not be something we intend to support. But we can certainly improve the docs to fix the missing reference to this plugins directory as an implicit local mirror, and I think also call out more clearly that the implicit `direct` source ignores all plugins found in this directory.

**Comment by magodo** [comment]
@alisdair many thanks to your support! I leave you to decide whether to close this issue (as my issue has been addressed), or keep it open to track the document enhancement.
