### ISSUE TITLE
Terraform reports stale plan without a change

### ISSUE THREAD

**Issue by sjarking** [hashicorp/terraform#25981]
### Terraform Version
```
Terraform v0.12.29
```

### Terraform Configuration Files

```terraform
        terraform init -no-color -input=false
        terraform workspace select $WORKSPACE_NAME -no-color || terraform workspace new $WORKSPACE_NAME -no-color
        terraform validate -no-color
        terraform state pull | grep serial 
        terraform plan -no-color -out=$stack.tfplan -var-file=$WORKSPACE_NAME.tfvars -input=false -detailed-exitcode -lock=true
        terraform state pull | grep serial 
```

### Expected Behavior
```
Initializing modules...
--
65 |  
66 | Initializing the backend...
67 |  
68 | Initializing provider plugins...
69 |  
70 | Terraform has been successfully initialized!
71 | "serial": 51,
72 |  
73 | Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Actual Behavior
```
Initializing modules...
--
65 |  
66 | Initializing the backend...
67 |  
68 | Initializing provider plugins...
69 |  
70 | Terraform has been successfully initialized!
71 | Switched to workspace "test".
72 | "serial": 51,
73 |  
74 | Error: Saved plan is stale
75 |  
76 | The given plan file can no longer be applied because the state was changed by
77 | another operation after the plan was created.
```

### Additional Context
We are moving towards AWS CodePipeline with CodeBuild for our terraform deployments on AWS.
We run several stages in the pipeline, one per workspace which represents an environment (TEST, QA, PROD) each in a different account.

Every stage has an action for validate/plan, one for manual approval and one for the apply.

We create a plan in the validate/plan action using following commands:
```
        terraform init -no-color -input=false
        terraform workspace select $WORKSPACE_NAME -no-color || terraform workspace new $WORKSPACE_NAME -no-color
        terraform validate -no-color
        terraform state pull | grep serial 
        terraform plan -no-color -out=$stack.tfplan -var-file=$WORKSPACE_NAME.tfvars -input=false -detailed-exitcode -lock=true
        terraform state pull | grep serial 
```
We `grep` the `serial` from the `remote state` for debugging purposes.

Everything works fine in the first stage, however in all following stages we get `Error: Saved plan is stale`.
We pass the whole directory including the `.terraform` as artifact to the next stage.
We also use a remote stage on S3 with a lock table in dynamoDB.

We verified that the serial did not change between the plan and apply command.

What could cause Terraform to report the stale plan?
We are totally stuck on this one.

Any help is much appreciated.

**Comment by alisdair** [comment]
I'm not sure what could be causing this!

The error message comes from here: https://github.com/hashicorp/terraform/blob/c5c02684d5107b72a98b79427266ed8b4f0f9427/backend/local/backend_local.go#L208-L216

It is only displayed if the plan's previous state file `serial` or `lineage` values do not match the current state `serial` or `lineage`. You can inspect the plan' state file by running `unzip` on it and looking at the `tfstate` JSON file.

**Comment by sjarking** [comment]
Hi alisdair,
I don't know if it makes a difference, but we use a backend in S3.

I have verified that the `serial` has not changed, I will check for the `lineage`.
I have not been able to reproduce it outside of AWS codebuild, however it only occurs when the codebuild project is located in a different account than the codepipeline itself. The codebuild projects that run the same code and use the same artifacts and run in the same account as the codepipeline do not have this issue.

The artifact is stored in a bucket using encryption with a CMK. The codebuild project has an admin IAM role and access to the bucket. It can download and read the artifact.

**Comment by sjarking** [comment]
I added a check that reads the `serial` and `lineage` before and after the `terraform plan` and also before the `terraform apply`. Three times we get exactly the same value (as expected).
However, we still get the same error: 
```
Error: Saved plan is stale

The given plan file can no longer be applied because the state was changed by
another operation after the plan was created.
```

**Comment by alisdair** [comment]
I'm really at a loss to explain this. As you can see from the code I linked above, the serial & lineage checks are quite straightforward, so given the information you've shared I don't understand how they could be failing.

We'd be happy to investigate this further but it's difficult to make progress without access to a reproduction case. Would it be possible for you to make a new, small, shareable configuration using your same pipeline, check that it exhibits the same problem and upload the configuration, state file, and plan file?

Alternatively, if you can find another way to reproduce this error outside the pipeline you're using, that would also help.

**Comment by sjarking** [comment]
Hi alisdair,
We found the issue by following your advice. We unzipped the plan file and it was the plan file of a previous stage.
It was an issue or expected behavior (still don't know) by AWS CodePipeline. You cannot overwrite an artifact.
Every stage needs an artifact with a different name.

Thanks for your help.
