### ISSUE TITLE
When using PFX certificate is requiring explict filename extention

### ISSUE THREAD

**Issue by bnfbiz** [hashicorp/terraform#25997]
When using certificate based authentication with a security principal and a valid certificate it complains about the file extention on the certificate:

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error: Error building AzureRM Client: 1 error occurred:
	* The Client Certificate Path is not a *.pfx file: "****"

  on provider-azure.tf line 1, in provider "azurerm":
   1: provider "azurerm" {

Error: Error building AzureRM Client: 1 error occurred:
	* The Client Certificate Path is not a *.pfx file: "****"

  on provider-azure.tf line 21, in provider "azurerm":
  21: provider "azurerm" {

The issue is that Jenkins plugin Azure credentials and the correspoinding Ceritificate code from Credentials plugins do not name the files as pfx files.  

Since it is really a valid certificate the authentication work instead of having the plugin complain about the certificate not being a pfx file.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

╰─$ terraform -v
Terraform v0.12.28
+ provider.azurerm v2.24.0

Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

provider authentication to Azure

### Terraform Configuration Files

```hcl
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version                     = "~> 2.24.0"
  environment                 = "public"
  subscription_id             = var.azure_subscription_id
  tenant_id                   = var.azure_tenant_id
  client_id                   = var.azure_client_id
  client_certificate_path     = var.azure_client_certificate_path
  client_certificate_password = var.azure_client_certificate_password

  features {
    virtual_machine {
      delete_os_disk_on_deletion = var.azure_delete_os_disk_on_termination
    }
  }
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

Authentication should have been successful.

### Actual Behavior

Authentication failed with the error: 
Error: Error building AzureRM Client: 1 error occurred:
	* The Client Certificate Path is not a *.pfx file: "****"

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Azure public instance authentication using azure security principal and certificate

### References

n/a

* #0000

**Comment by tombuildsstuff** [comment]
Duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/8250 - closing in favour of that issue

**Comment by bnfbiz** [comment]
you closed the wrong one, I wanted this one open and the other one closed.
The one from COREProgrammers as I was accidentally still logged into the
high school teams account.

**Comment by tombuildsstuff** [comment]
@bnfbiz this issue is for the Azure Provider, and so is unrelated to Terraform Core, so this issue would have been closed in favour of one on that provider anyway; you're welcome to open a new issue on that Provider we can close that in favour of should you wish to track this under a separate account however
