### ISSUE TITLE
nested for_each modules cause resolution issue during import

### ISSUE THREAD

**Issue by brian-mcnamara** [hashicorp/terraform#26007]
### Terraform Version
```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/aws v3.3.0
```

### Terraform Configuration Files
See repo here: https://github.com/brian-mcnamara/terraform-foreach-import-bug

The setup is a top level project with two nested modules. The root module instantiates a module using for_each and that module instantiates a the second module also in a for_each (nested for_each). The first module creates a IAM user and the second a s3 bucket. 

### Debug Output
https://gist.github.com/brian-mcnamara/c28dd0634f8f414534cb617c398d383a

### Expected Behavior
I expect the import to have succeeded since the sub_module is not required to import the iam user. Plus TF does have the full configuration to be able to fully graph the project but for some reason gets caught up.

It can be worked around by commenting out the sub_module, running the import.

### Actual Behavior
Running `terraform import 'module.main_module["module1"].aws_iam_user.shared_user' test-shared-user` results in.  
```
module.main_module["module1"].aws_iam_user.shared_user: Importing from ID "test-shared-user"...
module.main_module["module1"].aws_iam_user.shared_user: Import prepared!
  Prepared aws_iam_user for import
module.main_module["module1"].aws_iam_user.shared_user: Refreshing state... [id=test-shared-user]

Error: Invalid for_each argument

  on module/main.tf line 11, in module "test":
  11:     for_each = var.sub_modules

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

### Steps to Reproduce
1) create a IAM user named `test-shared-user`
2) clone the example repo project
3) terraform init
4) terraform import 'module.main_module["module1"].aws_iam_user.shared_user' test-shared-user

**Comment by danburkhol** [comment]
I too am still seeing this bug. I am getting around it by commenting out everything unrelated to the path im trying to import against

```17:03:57 danburkhol@Daniels-MacBook-Pro-2:~/company-co [feature/steve-docker !?]
$ terraform import module.develop.module.networking.module.core.aws_vpc.vpc vpc-509fce37

module.develop.module.networking.module.core.aws_vpc.vpc: Importing from ID "vpc-509fce37"...
module.develop.module.networking.module.core.aws_vpc.vpc: Import prepared!
  Prepared aws_vpc for import
module.develop.module.networking.module.core.aws_vpc.vpc: Refreshing state... [id=vpc-509fce37]

Error: Invalid for_each argument

  on terraform/environments/develop/develop.tf line 62, in module "target_group_request_anomalies":
  62:   for_each = module.networking.target_group_arn_suffixes

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.


Error: Invalid for_each argument

  on terraform/environments/production-us/production-us.tf line 62, in module "target_group_request_anomalies":
  62:   for_each = module.networking.target_group_arn_suffixes

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.


Error: Invalid count argument

  on terraform/company-co/networking/networking.tf line 109, in module "frontend_listener_rules":
 109:   count = length(module.frontend_listeners.listener_arns)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.```

**Comment by jbardin** [comment]
This appears to be a duplicate of #25816. @danburkhol, is this still happening with 0.13.1?

**Comment by brian-mcnamara** [comment]
Thanks @jbardin, can confirm this is working in 13.1 (Didn't even realize its been released). Thanks!

**Comment by danburkhol** [comment]
> This appears to be a duplicate of #25816. @danburkhol, is this still happening with 0.13.1?

Yes it's still happening after upgrading to 0.13.1.
