### ISSUE TITLE
Reference - Issue #23833

### ISSUE THREAD

**Issue by vishalaj1** [hashicorp/terraform#26025]
### Terraform Version

Terraform Cloud

```
...
```

### Terraform Configuration Files

module "service_accounts" {
  source        = "terraform-google-modules/service-accounts/google"
  version       = "~> 2.0"
  project_id    = "globalvpc1"
  prefix        = "test-sa"
  names         = ["first", "second"]
  project_roles = [
    "project-foo=>roles/viewer",
    "project-spam=>roles/storage.objectViewer",
  ]
}

```terraform
...
```

### Debug Output

Terraform v0.13.0
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
[0m[1mInitializing modules...[0m
- service_accounts in modules/serviceaccounts
Downloading terraform-google-modules/service-accounts/google 2.0.2 for service_accounts.service_accounts...
[31m
[1m[31mError: [0m[0m[1mFailed to download module[0m

[0mCould not download module "service_accounts"
(modules/serviceaccounts/main.tf:1) source code from
"https://github.com/terraform-google-modules/terraform-google-service-accounts/archive/v2.0.2.tar.gz//*?archive=tar.gz":
bad response code: 403.
[0m[0m
[31m
[1m[31mError: [0m[0m[1mFailed to download module[0m

[0mCould not download module "service_accounts"
(modules/serviceaccounts/main.tf:1) source code from
"https://github.com/terraform-google-modules/terraform-google-service-accounts/archive/v2.0.2.tar.gz//*?archive=tar.gz":
bad response code: 403.
[0m[0m


### Expected Behavior

Module should be downloaded and steps service account should be created

### Actual Behavior

Error

### Steps to Reproduce
module "service_accounts" {
  source        = "terraform-google-modules/service-accounts/google"
  version       = "~> 2.0"
  project_id    = "globalvpc"
  prefix        = "test-sa"
  names         = ["first", "second"]
  project_roles = [
    "project-foo=>roles/viewer",
    "project-spam=>roles/storage.objectViewer",
  ]
}

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

- Issue #23833

**Comment by alisdair** [comment]
Hi @vishalaj1! This looks like you're being affected by [this Terraform Cloud incident](https://status.hashicorp.com/incidents/z42xmmmjt0rm), which is actively being worked on right now. This isn't a Terraform core bug, so I'm going to close this ticket. Please follow along at Statuspage for updates: https://status.hashicorp.com/incidents/z42xmmmjt0rm
