### ISSUE TITLE
VMSS with Shared_image_version "latest"

### ISSUE THREAD

**Issue by marcelkmfst** [hashicorp/terraform#26022]
Hi,

AzureRM 2.24. 

Shared Image Gallery and VMSS with automatic OS Upgrade enabled.

existing Shared Image Gallery version imported with Name "latest" like described in the documentation.

https://www.terraform.io/docs/providers/azurerm/d/shared_image_version.html 

VMSS provisioning fails with 

Error: Error creating Windows Virtual Machine Scale Set "vmss-app" (Resource Group "RG-TFCICDAPP105"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="virtualMachineScaleSets with Automatic OS Upgrade enabled must use Platform or Gallery Image with version set to 'latest'."

Seems like that TF is not using the latest Version as expected.

**Comment by ausfestivus** [comment]
Hey @marcelkmfst can I suggest opening the issue in the Azure Provider repo? https://github.com/terraform-providers/terraform-provider-azurerm

**Comment by marcelkmfst** [comment]
Hey, sorry - of course, was my fault...

**Comment by jbardin** [comment]
Looks like this is already moved to azurerm repo.

Thanks!
