### ISSUE TITLE
Documentation link fails due to godoc changes

### ISSUE THREAD

**Issue by rgardam** [hashicorp/terraform#26029]
All the godoc related links from this page now point to broken links.

https://www.terraform.io/docs/plugins/provider.html 

Im not sure this is a hashicorp problem, but it does look like godoc has been deprecated. 

Old links:
https://godoc.org/github.com/hashicorp/terraform/helper/schema

New links. 
https://pkg.go.dev/github.com/hashicorp/terraform/helper/schema

**Comment by alisdair** [comment]
Thanks for reporting this! We should update those links.

I'm unable to reproduce the problem though. The godoc links are working properly for me in an incognito window, and redirecting to pkg.go.dev as expected in my normal browser.

Can you say more about the behaviour you're seeing?

**Comment by rgardam** [comment]
Hey, no worries at all.

I think godoc might have been having some issues last week. I was getting internal server errors all day and had made an assumption that they might have prematurely moved. 

Also might have something to do with my Melbourne Australia time zone :D
