### ISSUE TITLE
Security group docs inaccurate?

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#2602]
From https://www.terraform.io/docs/providers/aws/r/security_group.html:

> NOTE on Egress rules: By default, AWS creates an ALLOW ALL egress rule when creating a new Security Group inside of a VPC. When creating a new Security Group inside a VPC, Terraform will remove this default rule, and require you specifically re-create it if you desire that rule. We feel this leads to fewer surprises in terms of controlling your egress rules. If you desire this rule to be in place, you can use this egress block: <...>

When bringing up a new Terraform stack with a VPC containing at least one security group, this note suggests that the default egress rule for all ports to 0.0.0.0/0 will be deleted. However, this does not appear to be the case - I just brought up a stack (using Terraform 0.6.0) with one SG, but the AWS console shows two, the one I requested and the default SG, including full outbound access.

**Comment by jedineeper** [comment]
If I'm understanding your comment correctly then this is actually correct.

A new VPC will be created with a "default" security group, this is done by Amazon and not Terraform. 

This security group isn't what the docs you linked refer to, the new security group that you created in your template should have no egress rules (unless you explicitly create them as part of the template). This is (relatively) new behaviour, previously the group you created would of had an egress rule of 0.0.0.0/0 added automatically by Terraform.

Hope this helps.

**Comment by jedineeper** [comment]
Here is the AWS docs referring to the default security group created with a VPC.

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_SecurityGroups.html#DefaultSecurityGroup

**Comment by pikeas** [comment]
You're absolutely right, I misread the docs. There's a difference between the default group (which is still created), and new groups being created without the default *rule*.
