### ISSUE TITLE
aws_db_subnet_group only permits alphanumeric and hyphens, whereas underscores are valid characters.

### ISSUE THREAD

**Issue by CpuID** [hashicorp/terraform#2603]
We currently have a heap of DB Subnet Groups that were created with Terraform, that have underscores in the name. Since upgrading to 0.6.0 it errors with:

```
  * aws_db_subnet_group.production_default: only alphanumeric characters and hyphens allowed in "name"
```

The name cannot be changed in the AWS Console, and I suspect it cannot be changed via API also. Can we adjust the logic to permit underscores in names? Being that AWS allows these as valid characters. Thanks.

**Comment by CpuID** [comment]
PR https://github.com/hashicorp/terraform/pull/2604 created for this.

**Comment by radeksimko** [comment]
#2604 merged
