### ISSUE TITLE
terraform not properly storing provider args from command line when there is no provider block

### ISSUE THREAD

**Issue by mildwonkey** [hashicorp/terraform#26035]
### Terraform Version
0.13.2-dev (build from master)

### Terraform Configuration Files

```terraform
resource "aws_bucket" "yo" {
  name = "yo"
}
```

### Expected Behavior
```
  The region where AWS operations will take place. Examples
resource "aws_bucket" {
  are us-east-1, us-west-2, etc.

  Enter a value: us-east-1

Refreshing Terraform state in-memory prior to plan...
```

### Actual Behavior
```
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: us-east-1


Error: Missing required argument

The argument "region" is required, but was not set.
```

### Steps to Reproduce
plan

### References
Could possibly relate to https://github.com/hashicorp/terraform/issues/26027

**Comment by bflad** [comment]
In the meantime, this particular issue can be worked around by including the AWS region in the Terraform configuration, e.g.

```terraform
provider "aws" {
  region = "us-east-1"
}

# ... existing configuration ...
```

This will prevent the "Enter a value" prompt from appearing. Please note that if you are using [multiple provider configurations](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations), the region configuration will need to be added to each provider configuration.
