### ISSUE TITLE
Access legacy S3 state from TFE cloud / enterprise

### ISSUE THREAD

**Issue by sai1621** [hashicorp/terraform#26045]
Hi team, 

Can we access terraform s3 state from terraform cloud which uses remote state backend? 

We have some infra deployed using terraform 11.13 version with Amazon S3 backend. 

```
  remote_state {
    backend = "s3"

    config {
      bucket         = var.state_bucket
      key            = "environments/dev/network"
      region         = "us-east-2"
      dynamodb_table = var.dynamo_db_lock
      encrypt        = true
      acl            = "bucket-owner-full-control"
    }
```

We have recently moved to Terraform cloud and is using terraform version 12 with remote backend as shown below 

```
terraform {
  required_version = ">= 0.12.0"
  backend "remote" {
    hostname     = "terraform.mycorp123.net"
    organization = "org123"
    workspaces {
      prefix = "remote-state-access"
    }
  }
}
```
Included the below data provider in my TFE repo to be able to access the state from S3

```
data "terraform_remote_state" "network_state" {
  backend = "s3"

  config = {
    bucket  = var.state_s3_bucket
    key     = "environments/dev/network"
    region  = "us-east-2"
    profile = "default"
  }
}
```

But I am receiving the below error 

```
Error: AccessDenied: Access Denied
	status code: 403, request id: 868DBDEF9B9085D3, host id: bohQ4XQBU/vpJHasWpfU2KYcNqQlbAFnzOGMmyQdeVCoVIQ1uIcB6e0ILI43Pn3N6QA2TjHWhBM=
```

I am looking to see if this is possible at the first place and any sample patterns / code. Please let me know for any more information. Thanks!

**Comment by alisdair** [comment]
I was just able to execute a run on Terraform Cloud which accesses remote state from an S3 bucket. As a result, I don't believe this is a bug in Terraform, and it looks more likely to be an AWS authentication problem.
