### ISSUE TITLE
TF 0.31.1: error "This value does not have any indices" when referencing aws_acm_certificate.cert.domain_validation_options[0]

### ISSUE THREAD

**Issue by nigelellis** [hashicorp/terraform#26043]
### Terraform Version
```
Terraform v0.13.1
+ provider registry.terraform.io/-/aws v3.3.0
+ provider registry.terraform.io/-/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/aws v3.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
```

### Terraform Configuration Files

```terraform
resource "aws_acm_certificate" "cert" {
  domain_name               = replace(data.aws_route53_zone.domain.name, "/\\.$/", "")
  subject_alternative_names = var.subject_alternative_names
  validation_method         = "DNS"

  lifecycle {
    create_before_destroy = true
  }
}

data "aws_route53_zone" "domain" {
  name    = var.domain_name
  zone_id = var.zone_id
}

resource "aws_route53_record" "cert-validation" {
  name    = aws_acm_certificate.cert.domain_validation_options[0].resource_record_name
  type    = aws_acm_certificate.cert.domain_validation_options[0].resource_record_type
  zone_id = data.aws_route53_zone.domain.zone_id
  records = [aws_acm_certificate.cert.domain_validation_options[0].resource_record_value]
  ttl     = 60
}

resource "aws_acm_certificate_validation" "cert" {
  certificate_arn         = aws_acm_certificate.cert.arn
  validation_record_fqdns = [aws_route53_record.cert-validation.fqdn]
}
```

### Debug Output
See https://gist.githubusercontent.com/nigelellis/4cd3d1ad224c7566ddb65c0f201abbc1/raw/107b118a576006338a40da061a3a1fadd06b3184/gistfile1.txt

### Crash Output
None

### Expected Behavior
Plan should have worked just fine - this was working ok on 0.12.29 before we upgraded to 0.13.1.

### Actual Behavior
Plan fails to return result with error: "This value does not have any indices"

```tf
Error: Invalid index

  on ../../../modules/aws/security/domain-certificate/main.tf line 19, in resource "aws_route53_record" "cert-validation":
  19:   name    = aws_acm_certificate.cert.domain_validation_options[0].resource_record_name

This value does not have any indices.


Error: Invalid index

  on ../../../modules/aws/security/domain-certificate/main.tf line 20, in resource "aws_route53_record" "cert-validation":
  20:   type    = aws_acm_certificate.cert.domain_validation_options[0].resource_record_type

This value does not have any indices.


Error: Invalid index

  on ../../../modules/aws/security/domain-certificate/main.tf line 22, in resource "aws_route53_record" "cert-validation":
  22:   records = [aws_acm_certificate.cert.domain_validation_options[0].resource_record_value]

This value does not have any indices.
```

Running `terraform show` and locating the module snippets you can clearly see the module has an array property `aws_acm_certificate.cert.domain_validation_options`:
```tf
# module.cert.aws_acm_certificate.cert:
resource "aws_acm_certificate" "cert" {
    arn                       = "arn:aws:acm:..."
    domain_name               = "<domain-name>"
    domain_validation_options = [
        {
            domain_name           = "*.<domain-name>"
            resource_record_name  = "....<domain-name>."
            resource_record_type  = "CNAME"
            resource_record_value = ".....acm-validations.aws."
        },
        {
            domain_name           = "<domain-name>"
            resource_record_name  = "....<domain-name>."
            resource_record_type  = "CNAME"
            resource_record_value = ".....acm-validations.aws."
        },
    ]
    id                        = "arn:aws:acm:us-west-2:...:certificate/..."
    subject_alternative_names = [
        "*.<domain-name>",
    ]
    tags                      = {}
    validation_emails         = []
    validation_method         = "DNS"

    options {
        certificate_transparency_logging_preference = "ENABLED"
    }
}

# module.cert.aws_acm_certificate_validation.cert:
resource "aws_acm_certificate_validation" "cert" {
    certificate_arn         = "arn:aws:acm:us-west-2:...:certificate/..."
    id                      = "2020-05-01 03:37:07 +0000 UTC"
    validation_record_fqdns = [
        "....<domain-name>",
    ]
}
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Additional Context
Nothing special - we're running vanilla TF over AWS.   This resource was previously created in TF 0.11 or 0.12 and is broken after the 0.13 upgrade.

### References
n/a

**Comment by alisdair** [comment]
Thanks for reporting! This looks like a similar issue to #25943 (attempting to index into a `set` value) and I believe the change was part of the 3.0.0 release of the AWS provider. [The change in the provider is documented in this very detailed comment from @bflad](https://github.com/terraform-providers/terraform-provider-aws/issues/10098#issuecomment-663562342):

> The `domain_validation_options` attribute is now a `set` type and the resource will attempt to populate the information necessary during the planning phase to handle the above situation in most environments without workarounds. This change also prevents Terraform from showing unexpected differences if the API returns the results in varying order.
> 
> Configuration references to this attribute will likely require updates since sets cannot be indexed (e.g. `domain_validation_options[0]` or the older `domain_validation_options.0.` syntax will return errors). If the `domain_validation_options` list previously contained only a single element like the two examples just shown, it may be possible to wrap these references using the `tolist()` function (e.g. `tolist(aws_acm_certificate.example.domain_validation_options)[0])` as a quick configuration update, however given the complexity and workarounds required with the previous `domain_validation_options` attribute implementation, different environments will require different configuration updates and migration steps.

There are some examples of how to migrate your configuration to adjust to this change in behaviour in the linked comment. If those don't quite meet your needs, I would recommend [posting a question in the discussion forum](https://discuss.hashicorp.com/c/terraform-core/27) for further assistance.

**Comment by nigelellis** [comment]
Thanks @alisdair, super helpful.
