### ISSUE TITLE
[WARN] retryable error: dial tcp: lookup self.public_ip on 127.0.0.53:53: no such host

### ISSUE THREAD

**Issue by boiledeggs** [hashicorp/terraform#26054]
### Issue:
Hello All,

Thanks for your time. So I am new to Terraform and in general devops.
I feel I am doing something wrong under the provisioner connection block.
I'm trying to create an ansible master and slave configuration using terraform. For my master to be able to talk with the slaves, need the ssh public keys of the master node to be available in all slaves in .ssh/authorized, for that I'm trying to ssh and pass on the master public keys while creating the slave.
For some reason I am not able to ssh into the slave while creation I tried all I could have imagined and went through lots of forums. I'm sure I maybe doing something wrong here.
Any help would be appreciated.
Regards.

### Terraform Version

```
Terraform v0.13.0
...
```

### Terraform Configuration Files
```
variable "region" {
  default = "us-east-1"
}

variable "type" {
  default = "t2.micro"  
}

variable "ec2LinuxAmi" {
  type = map(string)
  default = {
    us-east-1 = "ami-0bcc094591f354be2"
  }  
}

variable "keyname" {
  default = "terraformKeys"  
}

variable "privateKeyPath" {
  description = "Path to private key"
  default = "/home/userName/.ssh/id_rsa"
}

variable "awsKey" {
  default = "terraformKeys.pem"
}

variable "user_names" {
  description = "Create IAM users with these names"
  type        = list(string)
  default     = ["ansibleMaster"]
}


provider "aws" {
  region = var.region
  shared_credentials_file = "/home/userName/.aws/credentials"
  profile = "default"
}

resource "aws_security_group" "port_22_ingress_globally_accessible" {
    name = "port_22_ingress_globally_accessible"

    ingress { 
        from_port = 22    
        to_port = 22
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }
}

resource "aws_instance" "linux"{
  count = length(var.user_names)
  ami = lookup(var.ec2LinuxAmi, var.region)
  instance_type = var.type
  security_groups = [ "port_22_ingress_globally_accessible" ]
  key_name = var.keyname

  tags = {
    Name = var.user_names[count.index]
}

  provisioner "file" {
    source      = "foo"
    destination = "/tmp/foo"
  }
    connection {
      type = "ssh"
      user = "ubuntu"
      host = "self.public_ip"
      port = 22
      private_key = "${file("/home/userName/.ssh/id_rsa")}"
  }
}


...
```

### Debug Output
2020/08/30 19:10:30 [WARN] Provider "registry.terraform.io/hashicorp/aws" produced an unexpected new value for aws_instance.linux[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .disable_api_termination: was null, but now cty.False
      - .ebs_optimized: was null, but now cty.False
      - .hibernation: was null, but now cty.False
      - .monitoring: was null, but now cty.False
      - .iam_instance_profile: was null, but now cty.StringVal("")
      - .credit_specification: block count changed from 0 to 1
2020/08/30 19:10:30 [TRACE] eval: *terraform.EvalMaybeTainted
2020/08/30 19:10:30 [TRACE] eval: *terraform.EvalWriteState
2020/08/30 19:10:30 [TRACE] EvalWriteState: recording 0 dependencies for aws_instance.linux[0]
2020/08/30 19:10:30 [TRACE] EvalWriteState: writing current state object for aws_instance.linux[0]
2020/08/30 19:10:30 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/08/30 19:10:30 [TRACE] EvalApplyProvisioners: provisioning aws_instance.linux[0] with "file"
aws_instance.linux[0]: Provisioning with 'file'...
2020-08-30T19:10:30.228-0400 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/08/30 19:10:30 using private key for authentication
2020-08-30T19:10:30.229-0400 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/08/30 19:10:30 [DEBUG] Connecting to self.public_ip:22 for SSH
2020-08-30T19:10:30.248-0400 [DEBUG] plugin.terraform: file-provisioner (internal) 2020/08/30 19:10:30 [ERROR] connection error: dial tcp: lookup self.public_ip on 127.0.0.53:53: no such host

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
