### ISSUE TITLE
empty aws_db_instance identifier with recent validation changes

### ISSUE THREAD

**Issue by CpuID** [hashicorp/terraform#2605]
@radeksimko @phinze interesting side effect of https://github.com/hashicorp/terraform/pull/2516 (tested on 0.6.0), we seemed to have an RDS instance with an empty identifier (the Instance Name in the Console was set to "wordpress"), when I tried to set it in the .tf file to "wordpress" it tried to recreate it. There was no identifier attribute in the tfstate file, once I added one though it agreed that everything was consistent (no changes required).

Would you agree this is an expected action? Would the RDS instance actually still have no identifier attached? or?

Was getting this after updating the .tf file without changing .tfstate:

```
  * aws_db_instance.wordpress: only lowercase alphanumeric characters and hyphens allowed in "identifier"
  * aws_db_instance.wordpress: first character of "identifier" must be a letter
```

**Comment by radeksimko** [comment]
@CpuID Interesting, how did you manage to create RDS instance with an empty `identifier` in the first place?

Recreating RDS instance isn't obviously desired behaviour in any case, but I'm keen to understand how did you manage to get into that situation since `aws_db_instance.identifier` is required.

**Comment by CpuID** [comment]
@radeksimko confirmed what happened here, we were using Terraform 0.3.6, and the RDS instance was created via the AWS Console and then backported into .tf configs and refreshed into the state file.

In all versions up until now (we were using 0.5.2 at the last time our .tfstate was refreshed, just bumped to 0.6.0 today) it allowed it to proceed as though the resource complied with the definition, without an identifier attribute in the state file, and with "" as the identifier in the .tf file. Pretty sure all along it has had the identifier though on the resource itself, in this case "wordpress".

When I go Modify DB Instance in the console, the identifier appears as wordpress, which would imply the DB Instance Name = Identifier effectively.

I guess prior to https://github.com/hashicorp/terraform/pull/2516 Terraform just ignored the identifier attribute on existing resources...?

**Comment by radeksimko** [comment]
I still don't quite understand how did you manage to create such instance even via AWS Console... maybe a missing validation which has been added later?
![screen shot 2015-07-02 at 11 32 33](https://cloud.githubusercontent.com/assets/287584/8475217/48d9ee98-20ae-11e5-9125-c3d3d0964f0f.png)

https://github.com/aws/aws-sdk-go/blob/4862a174f7fc92fb523fc39e68f00b87d91d2c3d/service/rds/api.go#L2595

```go
DBInstanceIdentifier *string `type:"string" required:"true"`
```

**Comment by CpuID** [comment]
I think the chain of events was as follows:

- Created RDS instance via AWS Console, including an identifier of "wordpress"
- Backported (added to .tf file), with an identifier of ""
- Terraform 0.3.6 (possibly earlier also) -> 0.5.2 (possibly 0.5.3 also, untested) didn't verify the state of the identifier attribute, was completely ignored.
- Terraform 0.6.0 starts validating identifier, which triggers my issues, since resolved.

Sound plausible?

**Comment by radeksimko** [comment]
@CpuID My assumption is, that such edge case was possible before https://github.com/hashicorp/terraform/commit/0725486e894d81da5f74f2b68031f292e2d150a2#diff-0b21e21c91dc560c837c95806e2ba913R396 , that is before `0.3.5`. 

`0.3.5+` has been checking this edge case already and would have caused plan & apply to report/make changes.

I actually managed to add empty `identifier` into both `tfstate` & `*.tf` so that `plan` reports no changes if I just made these tiny changes in Terraform code:

```diff
diff --git a/builtin/providers/aws/resource_aws_db_instance.go b/builtin/providers/aws/resource_aws_db_instance.go
index 53b6a69..543cfd1 100644
--- a/builtin/providers/aws/resource_aws_db_instance.go
+++ b/builtin/providers/aws/resource_aws_db_instance.go
@@ -74,26 +74,6 @@ func resourceAwsDbInstance() *schema.Resource {
 				Type:     schema.TypeString,
 				Required: true,
 				ForceNew: true,
-				ValidateFunc: func(v interface{}, k string) (ws []string, errors []error) {
-					value := v.(string)
-					if !regexp.MustCompile(`^[0-9a-z-]+$`).MatchString(value) {
-						errors = append(errors, fmt.Errorf(
-							"only lowercase alphanumeric characters and hyphens allowed in %q", k))
-					}
-					if !regexp.MustCompile(`^[a-z]`).MatchString(value) {
-						errors = append(errors, fmt.Errorf(
-							"first character of %q must be a letter", k))
-					}
-					if regexp.MustCompile(`--`).MatchString(value) {
-						errors = append(errors, fmt.Errorf(
-							"%q cannot contain two consecutive hyphens", k))
-					}
-					if regexp.MustCompile(`-$`).MatchString(value) {
-						errors = append(errors, fmt.Errorf(
-							"%q cannot end with a hyphen"))
-					}
-					return
-				},
 			},
 
 			"instance_class": &schema.Schema{
@@ -674,8 +654,7 @@ func resourceAwsDbInstanceRetrieve(
 		return nil, fmt.Errorf("Error retrieving DB Instances: %s", err)
 	}
 
-	if len(resp.DBInstances) != 1 ||
-		*resp.DBInstances[0].DBInstanceIdentifier != d.Id() {
+	if len(resp.DBInstances) != 1 {
 		if err != nil {
 			return nil, nil
 		}
```

This situation shouldn't be happening to anyone migrating from `0.3.5+`.

I'm closing this because there's no way I can reliably replicate that issue anymore.
Reopen if you think otherwise or if you have a specific suggestion for solution.
