### ISSUE TITLE
Gitlab VCS Integration - Manual Setup

### ISSUE THREAD

**Issue by kskewes** [hashicorp/terraform#26052]
It would be good to clarify why `master` (`maintainer` in gitlab.com) permission is required.

The [docs](https://www.terraform.io/docs/cloud/vcs/gitlab-com.html) state:

> Important: The account you use for connecting Terraform Cloud must have admin (master) access to any shared repositories of Terraform configurations, since creating webhooks requires admin permissions.

Following least privilege principle would an alternative be to use a lower permission level and provide documentation on how to create a `Webhook` manually similar to the SSH Key docs?

The automatically created webhook could be created by users if Terraform Cloud provides the dynamic URL & secret during the setup flow. Users could then copy paste that into Gitlab.

Are the URL's and secrets updated periodically in Terraform Cloud?
This might require Terraform to routinely interact with Gitlab.

Related, Gitlab `Project` scoped API Tokens are not yet available for gitlab.com - tracking epic: https://gitlab.com/groups/gitlab-org/-/epics/2587

### Current Terraform Version
```
$ terraform version
Terraform v0.12.28
```

### Use-cases

Following least privilege principle and don't give `master` level privileges for Terraform Cloud for the sole purposes of creating a webhook.

### Attempted Solutions

1. Create Gitlab application with `maintainer` permissions - setup in Terraform Cloud. Webhook created automatically.

### Possible Workaround?

1. Create Gitlab application with `maintainer` permissions - setup in Terraform Cloud. Webhook created automatically.
2. Reduce Gitlab application permission level to `developer` ?

### Proposal

Terraform Cloud provides alternative Webhook setup flow, providing dynamic URL & secret for use in Gitlab.

### References

- #22709

**Comment by pkolyvas** [comment]
Hey there,

Thanks for taking the time to request this Terraform Cloud enhancement. This issue tracker is for the Terraform Open Source tool’s code. 

I've forwarded your request to the Terraform Cloud Team. Should you wish to contact them via our support team you can send them a message via tf-cloud-support@hashicorp.com. 

If you have an Enterprise account, please use your enterprise support contacts.

Thanks,
PK
