### ISSUE TITLE
Terraform unable to set Glue Job version as 2.0 no errors it stays at 1.0

### ISSUE THREAD

**Issue by prateekmanasvi** [hashicorp/terraform#26057]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hi @prateekmanasvi 

There doesn't seem to be any info included in this issue.
If you meant to open an issue with a provider, you should use that provider's repository. If you have a terraform bug, please open a new issue with the requested information.

Thanks!
