### ISSUE TITLE
Error creating S3 bucket: InvalidBucketName

### ISSUE THREAD

**Issue by wiltzie75** [hashicorp/terraform#26065]
I'm getting an error creating S3 bucket: InvalidBucketName: The specificed bucket is not valid.  status code: 400.  Not sure, because my bucket name is: norton-munki-bucket

`variable "munki_s3_bucket" {
  default = "norton-munki-bucket"
}`

**Comment by Mostela** [comment]
In the AWS your bucket S3 need have a unique name, like example: _pandora999box_ this name need unique in this region. try append in your name a number like 1, 2 or outher sometimes this can do. Sometimes is this beacause outher people create a S3 with this name or you runner this code before.

**Comment by wiltzie75** [comment]
Hi,
I've tried multiple variations and throwing in random numbers, ie. norton19wiltzie23munki, norton19munki23wiltzie, norton19munki23wiltzie75.  I'm still getting this error, not sure what else to do:
`Error: Error applying plan:

1 error occurred:
	* module.munki-repo.aws_s3_bucket.log_bucket: 1 error occurred:
	* aws_s3_bucket.log_bucket: Error creating S3 bucket: InvalidBucketName: The specified bucket is not valid.
	status code: 400, request id: FTAY7RCMBKAJ0GEP, host id: Uo+qp1J9cQcVe3f9xapiKZ4m+mfDqACTPGkzQAJ8fnx+LLc7J+dozUU/bwNOyfI3qMsjj3O/lrM=`

Thanks

**Comment by akolkarsohan** [comment]
Check if your bucket name are violating any naming conventions (underscores in bucket name). Refer this page https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by wiltzie75** [comment]
Hi,
Should I have already created a bucket before running this?  I've gone through this link before and can't find any reason why my name might be invalid.  Can you take a look at my .tf file I've attached to see if I'm missing anything?  I saved it as a .txt so I could attach it.

Thanks,

[main.txt](https://github.com/hashicorp/terraform/files/5169184/main.txt)

**Comment by pantelis-karamolegkos** [comment]
@wiltzie75 what TF version are you using?
I am facing the same issue (bucket name does not exist for sure since I created and deleted it in another account)
I am using tf `0.11.14`

**Comment by pselle** [comment]
Hi there, apologies that this has sat here so long without a response from the Terraform team, this didn't get tagged as `bug` so we didn't triage it! It sounds like you have more of a question rather than an issue relating to Terraform Core, I recommend in the future using [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
