### ISSUE TITLE
Dynamic population of list with resource ids

### ISSUE THREAD

**Issue by dharapvj** [hashicorp/terraform#26077]
### Current Terraform Version

```
$ terraform version
Terraform v0.12.26
+ provider.aws v2.69.0
+ provider.random v2.3.0
```
### Use-cases

I want to create many aws lambda resources using a for-loop. Each lambda needs to have number of security groups associated with it. I might be creating those security groups also along with lambdas. So I just want to give a list of the names of security groups to lambda configuration and lambda should be able to decipher the id of security group that I should assign to lambda.

### Attempted Solutions

Common vars definitions and tfvars content
```
# vars.tf
variable "lambda_test" {
  description = "All lambdas"
  type = set(object({
    name=string,
    secgrp=list(string),  # this part is added only for attempt 3
  }))
}
# vars.tfvars
lambda_test = [
  {
    name = "vj_sample",
    secgrp=[    # this part is added only for attempt 3
      "adp-rds-access-marker-sg"
    ]
  }
]
```
__attempt 1__: First I tried to use dynamic evaluation for loop
I want to provide value of sec group from my list of lambdas..
```
resource "aws_lambda_function" "adp_lambda" {
  for_each = { for l in var.lambda_test : l.name => l }
  function_name = "adp_${each.value.name}_${var.env}"
  vpc_config {
    security_group_ids = [ aws_security_group.${each.value.secgrpname}.id  ]
    subnet_ids         = [ .... ]
  }
}
```
__Issue with attempt 1__: This syntax does not work. `aws_security_group.${each.value.secgrpname}.id `

__attempt 2__: Used a dynamically evaluated data blocks
```
# lambda.tf
data "aws_security_group" "rds_marker_sg" {
  depends_on = [aws_security_group.xxx-rds-access-marker-sg]
  filter {
    name   = "tag:Name"
    values = ["xxx-rds-access-marker-sg-${var.env}"]
  }
}
resource "aws_lambda_function" "xxx_lambda" {
  for_each = { for l in var.lambda_test : l.name => l }
  function_name = "adp_${each.value.name}_${var.env}"
  role          = aws_iam_role.adp_lambda_role[each.value.name].arn
  vpc_config {
    security_group_ids = [ 
       data.aws_security_group.rds_marker_sg.id
    ]
    subnet_ids         = [ ... ]
  }
}
```
__Issue with attempt 2__: While this works... a. I am not able to dynamically specify the data elements in `security_group_ids` block. and b. since the data block get evaluated during apply, the lambda always shows changes in the plan even though there was no change in lambda definition.
```
  # data.aws_security_group.rds_marker_sg will be read during apply
  # (config refers to values not yet known)
 <= data "aws_security_group" "rds_marker_sg"  {
      + arn         = (known after apply)
      + description = (known after apply)
      + id          = (known after apply)
      + name        = (known after apply)
      + tags        = (known after apply)
      + vpc_id      = (known after apply)

      + filter {
          + name   = "tag:Name"
          + values = [
              + "xxx-rds-access-marker-sg-dev",
            ]
        }
    }

  # aws_lambda_function.adp_lambda["vj_sample"] will be updated in-place
  ~ resource "aws_lambda_function" "xxx_lambda" {
        function_name                  = "xxx_vj_sample_dev"

      ~ vpc_config {
          ~ security_group_ids = [
              - "sg-0df24d34ce9c5a7a6",
            ] -> (known after apply)
            subnet_ids         = [
                "...",
            ]
            vpc_id             = "vpc-xxx"
        }
    }

```

__attempt 3__: tried to use a simple for loop inside `security_group_ids` list.
Relevent lambda block definition
```
resource "aws_lambda_function" "xxx_lambda" {
  for_each = { for l in var.lambda_test : l.name => l }
  function_name = "xxx_${each.value.name}"
  role          = aws_iam_role.xxx_lambda_role[each.value.name].arn
  ... more attributes ...
  vpc_config {
    security_group_ids = [ for sg in each.value.secgrp: 
      "aws_security_group.${sg}.arn"
    ]
    subnet_ids         = [ ... ]
  }
}
```
__Issue with attempt 3__: The plan shows that it will add the literal string aws_security_group.xxxx.arn.. instead of the evaluated security group id. So this will not give desired output.
```
  # aws_lambda_function.xxx_lambda["vj_sample"] will be updated in-place
  ~ resource "aws_lambda_function" "xxx_lambda" {
      ~ vpc_config {
          ~ security_group_ids = [
              + "aws_security_group.XXX-rds-access-marker-sg.arn",
              - "sg-XXXXXXXX",
            ]
            subnet_ids         = [
                "....",
                "...",
            ]
            vpc_id             = "vpc-...."
        }
    }
```
### Proposal

Not exactly is proposal.. I wish that I could specify the sec group name via aws_security_group.${each.value.secgrpname}.id and get those resources looked up at plan time and proper plan get calculated.

**Comment by jbardin** [comment]
Hi @dharapvj,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the Terraform community forum](https://discuss.hashicorp.com/c/terraform-core), or the [AWS provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
