### ISSUE TITLE
Terraform Crash during stackpath compute_workload_resource import: Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by laurenkosub** [hashicorp/terraform#26088]
[crash.log](https://github.com/hashicorp/terraform/files/5159417/crash.log)

terraform (*.tf files)
```
variable "STACKID" {}
variable "CLIENTID" {}
variable "SECRET" {}

provider "stackpath" {
  stack_id      = var.STACKID
  client_id     = var.CLIENTID
  client_secret = var.SECRET
}

terraform {
  required_providers {
    stackpath = {
      source = "terraform-providers/stackpath"
    }
  }
  required_version = ">= 0.13"
}

resource "stackpath_compute_workload" "terraform" {}
```

I am trying to import a stackpath workload using 
```
$ terraform import stackpath_compute_workload.terraform 0a61802e-1edf-4d4d-9d15-686e327433b9
```
but terraform crashes during the import. TF_VAR_STACKID, TF_VAR_CLIENTID, and TF_VAR_SECRET are all valid environment variables that map to proper stackpath stackid, clientid, and client secret for authentication.

**Comment by jbardin** [comment]
This appears to be a bug with a stackpath provider. You should be able to file an issue in their github repository: https://github.com/stackpath/terraform-provider-stackpath
