### ISSUE TITLE
aws_network_interface forces aws_instance eth0 subnet change. 

### ISSUE THREAD

**Issue by suizman** [hashicorp/terraform#2608]
Hi yesterday i've downloaded the latest 0.6.0 release to give a try on a new aws_network_interface functionality. The case is that it isnt working very well. Once i create some instances and attach to them a second aws interface when i execute "terraform plan" it foreces to destroy the instance becouse form some reason when the terraform.tfstate refreshes the the subnet_id of the default eth0 changes with subnet_id for the new eni eth1:

terraform.tfstate >>>

                "aws_instance.proxy.0": {
                    "type": "aws_instance",
                    "depends_on": [
                        "aws_security_group.gbx",
                        "aws_security_group.proxy",
                        "aws_subnet.management"
                    ],
                    "primary": {
                        "id": "i-8d506327",
                        "attributes": {
                            "ami": "ami-e6602191",
                            "associate_public_ip_address": "true",
                            "availability_zone": "eu-west-1a",
                            "ebs_block_device.#": "1",
                            "ebs_block_device.3905984573.delete_on_termination": "true",
                            "ebs_block_device.3905984573.device_name": "/dev/xvdb",
                            "ebs_block_device.3905984573.encrypted": "false",
                            "ebs_block_device.3905984573.iops": "0",
                            "ebs_block_device.3905984573.snapshot_id": "",
                            "ebs_block_device.3905984573.volume_size": "10",
                            "ebs_block_device.3905984573.volume_type": "standard",
                            "ebs_optimized": "false",
                            "ephemeral_block_device.#": "0",
                            "id": "i-8d506327",
                            "instance_type": "t2.micro",
                            "monitoring": "false",
                            "private_dns": "ip-172-18-0-167.eu-west-1.compute.internal",
                            "private_ip": "172.18.0.167",
                            "public_dns": "",
                            "public_ip": "52.16.180.145",
                            "root_block_device.#": "1",
                            "root_block_device.0.delete_on_termination": "true",
                            "root_block_device.0.iops": "0",
                            "root_block_device.0.volume_size": "16",
                            "root_block_device.0.volume_type": "standard",
                            "security_groups.#": "0",
                            "source_dest_check": "false",
                            "subnet_id": "subnet-601a8017",
                            "tags.#": "3",
                            "tags.Greenbox": "gbx1",
                            "tags.Hostname": "proxy0",
                            "tags.Name": "gbx1-proxy0",
                            "tenancy": "default",
                            "vpc_security_group_ids.#": "2",
                            "vpc_security_group_ids.1071140996": "sg-4a1c1d2f",
                            "vpc_security_group_ids.2537102243": "sg-4b1c1d2e"
                        },
                        "meta": {
                            "schema_version": "1"
                        }
                    }
                },
terraform plan output >>>

-/+ aws_instance.proxy
    ami:                                               "ami-e6602191" => "ami-e6602191"
    associate_public_ip_address:                       "true" => "1"
    availability_zone:                                 "eu-west-1a" => "eu-west-1a"
    ebs_block_device.#:                                "1" => "1"
    ebs_block_device.3905984573.delete_on_termination: "true" => "1"
    ebs_block_device.3905984573.device_name:           "/dev/xvdb" => "/dev/xvdb"
    ebs_block_device.3905984573.encrypted:             "false" => "<computed>"
    ebs_block_device.3905984573.iops:                  "0" => "<computed>"
    ebs_block_device.3905984573.snapshot_id:           "" => "<computed>"
    ebs_block_device.3905984573.volume_size:           "10" => "10"
    ebs_block_device.3905984573.volume_type:           "standard" => "standard"
    ephemeral_block_device.#:                          "0" => "<computed>"
    instance_type:                                     "t2.micro" => "t2.micro"
    key_name:                                          "" => "<computed>"
    placement_group:                                   "" => "<computed>"
    private_dns:                                       "ip-172-18-0-168.eu-west-1.compute.internal" => "<computed>"
    private_ip:                                        "172.18.0.168" => "<computed>"
    public_dns:                                        "" => "<computed>"
    public_ip:                                         "52.16.182.109" => "<computed>"
    root_block_device.#:                               "1" => "<computed>"
    security_groups.#:                                 "0" => "<computed>"
    source_dest_check:                                 "false" => "0"
    subnet_id:                                         "subnet-601a8017" => "subnet-621a8015" (forces new resource)
    tags.#:                                            "3" => "3"
    tags.Greenbox:                                     "gbx1" => "gbx1"
    tags.Hostname:                                     "proxy0" => "proxy0"
    tags.Name:                                         "gbx1-proxy0" => "gbx1-proxy0"
    tenancy:                                           "default" => "<computed>"
    vpc_security_group_ids.#:                          "2" => "2"
    vpc_security_group_ids.1071140996:                 "sg-4a1c1d2f" => "sg-4a1c1d2f"
    vpc_security_group_ids.2537102243:                 "sg-4b1c1d2e" => "sg-4b1c1d2e"

+ aws_network_interface.proxy0-management
    attachment.#:                         "" => "1"
    attachment.~3470761036.attachment_id: "" => "<computed>"
    attachment.~3470761036.device_index:  "" => "1"
    attachment.~3470761036.instance:      "" => "${aws_instance.proxy.0.id}"
    security_groups.#:                    "" => "1"
    security_groups.2537102243:           "" => "sg-4b1c1d2e"
    subnet_id:                            "" => "subnet-601a8017"
    tags.#:                               "" => "2"
    tags.Greenbox:                        "" => "gbx1"
    tags.Name:                            "" => "gbx1-proxy0-management"

Additionaly aws_network_interface forces private_ips from 1 >>> 0

terraform.tfstate >>>
                "aws_network_interface.proxy0-service": {
                    "type": "aws_network_interface",
                    "depends_on": [
                        "aws_instance.proxy",
                        "aws_security_group.proxy",
                        "aws_subnet.service"
                    ],
                    "primary": {
                        "id": "eni-ff1ffab6",
                        "attributes": {
                            "attachment.#": "1",
                            "attachment.3876967536.attachment_id": "eni-attach-10fe7552",
                            "attachment.3876967536.device_index": "1",
                            "attachment.3876967536.instance": "i-8d506327",
                            "id": "eni-ff1ffab6",
                            "private_ips.#": "1",
                            "private_ips.2201243490": "172.18.1.181",
                            "security_groups.#": "1",
                            "security_groups.2537102243": "sg-4b1c1d2e",
                            "subnet_id": "subnet-621a8015",
                            "tags.#": "2",
                            "tags.Greenbox": "gbx1",
                            "tags.Name": "gbx1-proxy0-servicez"
                        }
                    }
                },
Plan output >>>

/+ aws_network_interface.proxy0-service
    attachment.#:                       "1" => "1"
    attachment.3876967536.device_index: "1" => "0"
    attachment.3876967536.instance:     "i-8d506327" => ""
    attachment.~41262290.attachment_id: "" => "<computed>"
    attachment.~41262290.device_index:  "" => "1"
    attachment.~41262290.instance:      "" => "${aws_instance.proxy.1.id}"
    private_ips.#:                      "1" => "0" (forces new resource)
    private_ips.2201243490:             "172.18.1.181" => ""
    security_groups.#:                  "1" => "1"
    security_groups.2537102243:         "sg-4b1c1d2e" => "sg-4b1c1d2e"
    subnet_id:                          "subnet-621a8015" => "subnet-621a8015"
    tags.#:                             "2" => "2"
    tags.Greenbox:                      "gbx1" => "gbx1"
    tags.Name:                          "gbx1-proxy0-servicez" => "gbx1-proxy0-servicez"

**Comment by catsby** [comment]
Hey @suizman – can you provide a sample configuration that demonstrates this? That will help me diagnose what's happening here. By the plan output, it appears you're changing the `subnet_id` in the `aws_instance`, which is an operation that requires us to re-create the instance.

Seeing the config and knowing the changes you're making would help me dig in deeper here. If you have something that easily demonstrates this and are willing to share, I would appreciate it greatly.  If you do, please be sure to remove any secrets from the config.

Thanks!

**Comment by suizman** [comment]
Hi @catsby please download the config sample to reproduce the issue from here:  https://gist.github.com/suizman/8b356041806a02edb8f3
  Before running terrafom make sure to export this vars
  export TF_VAR_aws_access_key="XXXXX"
  export TF_VAR_aws_secret_key="XXXX"

Thanks for your help. If you need anything else just tell me

**Comment by suizman** [comment]
Please close the issue i'am no longer able to reproduce the error with v0.6.3

**Comment by catsby** [comment]
Hey @suizman – so sorry for my delay here! Thank you for following up, I'll close this (finally!)
