### ISSUE TITLE
remote-exec inline issue

### ISSUE THREAD

**Issue by kenvpt** [hashicorp/terraform#26080]
theres some commands that will not execute when using inline. I was trying to use export to make env variable inside the inline and when I was checking inside the remote server, it was not executed and env variable was not created. 
<img width="538" alt="picture" src="https://user-images.githubusercontent.com/49701513/91881465-240ebc00-ec47-11ea-90e7-247259f4641f.png">

**Comment by pselle** [comment]
Hello @kenvpt ,

There's a lot of information missing in this issue, but I was unable to confirm what you're describing. Here is the config I used to test, which depends on setting up the necessary prerequisites to a remote connection in AWS:
```
resource "aws_instance" "web" {
  ami                         = var.instance_ami
  instance_type               = var.instance_type
  subnet_id                   = module.network_access.subnet_id
  vpc_security_group_ids      = [module.network_access.sg_id]
  key_name                    = aws_key_pair.key_pair.key_name
  associate_public_ip_address = true

  connection {
    type        = "ssh"
    user        = "ubuntu"
    host        = self.public_ip
    port        = 22
    private_key = file(var.private_key_path)
    timeout     = "1m"
  }

  provisioner "remote-exec" {
    inline = [
      "echo 'foo'",
      "echo ${var.foo}",
      "export Server=${var.foo}",
      "echo $Server"
    ]
  }
}
```

When I ran this configuration, the values were printed to stdout as expected:
```
aws_instance.web: Provisioning with 'remote-exec'...
aws_instance.web (remote-exec): Connecting to remote host via SSH...
aws_instance.web (remote-exec):   Host: 34.221.215.125
aws_instance.web (remote-exec):   User: ubuntu
aws_instance.web (remote-exec):   Password: false
aws_instance.web (remote-exec):   Private key: true
aws_instance.web (remote-exec):   Certificate: false
aws_instance.web (remote-exec):   SSH Agent: true
aws_instance.web (remote-exec):   Checking Host Key: false
aws_instance.web: Still creating... [50s elapsed]
aws_instance.web (remote-exec): Connected!
aws_instance.web (remote-exec): foo
aws_instance.web (remote-exec): bar
aws_instance.web (remote-exec): bar
aws_instance.web: Creation complete after 52s [id=i-0006178c0ccdbabb6]
```

I'm going to close this issue as I was unable to replicate your report, however if you are still seeing this issue and believe it to be a bug in Terraform, please open another issue filling out the issue template (which will include the version of Terraform you're running, providing config and logs, etc).
