### ISSUE TITLE
Terraform crash while running "plan" from Visual Studio Studio Code

### ISSUE THREAD

**Issue by broderick-roelf** [hashicorp/terraform#26097]
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform version: 0.13.1   
[crash.log](https://github.com/hashicorp/terraform/files/5162880/crash.log)

**Comment by para0056** [comment]
Also experiencing the same issue.

`user@host:~/scratchpad/new_provider$ terraform -v
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/azurerm v2.25.0
`
