### ISSUE TITLE
Destroying null_resource (local_exec) resource is not consistent when executing "terraform destroy" vs "terraforma apply"

### ISSUE THREAD

**Issue by TamasNeumer** [hashicorp/terraform#26092]
### Background

- Postgres databases can't be deleted while having active connections to it. As a countermeasure I want to execute a shell script, which effectively "cordons" the database by setting the connection limit to 0 and terminating all active connections.

### Simplified version / Setup

- In the `main.tf` I have the confirugration parameters:

```tf
locals {
  database-name = "test-db"
}
```

- In the `module.tf` file I have a `null_resource` which is executed on_destroy. Since tf 13+ doesn't allow parameters in destroy time `local-exec` I had to "save it" as a trigger.
```tf
resource null_resource "cordon-team-database-public-database" {

  triggers = {
    database-name = local.database-name
  }

  provisioner "local-exec" {
    when    = destroy
    command = "/bin/bash cordon-database.sh ${self.triggers.database-name}"
  }
}
```

- The shell script `cordon-database.sh`:

```sh
#!/bin/bash
set -e

if [ -z "$1" ]
then
   echo "Database name required" && exit 1
else
  DATABASE_NAME=$1
fi

echo "Setting connection limit to 0 on database: $DATABASE_NAME..."
#psql -h $TF_VAR_postgres_address -p $TF_VAR_postgres_port -U $TF_VAR_postgres_provisioner_username -d postgres -c "ALTER DATABASE \"$DATABASE_NAME\" CONNECTION LIMIT 0;"

echo "Terminating all connections to database '$DATABASE_NAME'"
#psql -h $TF_VAR_postgres_address -p $TF_VAR_postgres_port -U $TF_VAR_postgres_provisioner_username -d postgres -c "SET ROLE pg_signal_backend; SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity where datname = '$DATABASE_NAME'  AND pid <> pg_backend_pid();"
```

### terraform destroy vs terraform apply

- Now, when I run `terraform destroy` I see in the output that the shell script was called:

```
null_resource.cordon-team-database-public-database (local-exec): Executing: ["/bin/sh" "-c" "/bin/bash cordon-database.sh test-db"]
null_resource.cordon-team-database-public-database (local-exec): Setting connection limit to 0 on database: test-db...
null_resource.cordon-team-database-public-database (local-exec): Terminating all connections to database 'test-db'
```

- However (the full blown version of this example) deletes the `module.tf` file and runs `terraform apply`. In case of this the output is the following:

```
null_resource.cordon-team-database-public-database: Destroying... [id=7124733404667690434]
null_resource.cordon-team-database-public-database: Destruction complete after 0s
```

### Bug/question
- **The resource is destroyed, but the underlying shell script is not triggered if `terraform apply` is executed**
- Desired behavior would be the same as when executing `tf destroy`. In the end the resource is destroyed either way...

### Terraform Version

Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/null v2.1.2

**Comment by jbardin** [comment]
Hi @TamasNeumer 

Thanks for filing the issue, but this is the expected behavior. Since you have removed the config from terraform, there is no longer any provisioner configuration to execute. As for developing a method for handling this situation, we are tracking the feature as part of #13549

Thanks
