### ISSUE TITLE
Vultr Provider

### ISSUE THREAD

**Issue by smougenot** [hashicorp/terraform#2611]
Vultr is somethink like DigitalOcean.
It would be nice to have a provider for Vultr. 
API is described here : https://www.vultr.com/api/

**Comment by donbeave** [comment]
There is one implementation of Vultr provider:
https://github.com/rgl/terraform-provider-vultr

**Comment by thasmo** [comment]
I'd love to see this officially supported.

**Comment by jazoom** [comment]
+1

**Comment by catsby** [comment]
Hey Friends – I'm going to close this for now. If the author(s) of the above provider would like it to be considered, please request they open a pull request. Thanks!

**Comment by koalalorenzo** [comment]
+1 I hope this will be done soon 👍

**Comment by elricsfate** [comment]
@catsby Could you reopen this?

Also, would anyone like to help get a few more features implemented before I create the pull request? In particular Floating IP and Block Storage. 

https://github.com/elricsfate/terraform-provider-vultr/issues/5
https://github.com/elricsfate/terraform-provider-vultr/issues/3

@smougenot @donbeave @thasmo @jazoom @koalalorenzo ?

**Comment by thasmo** [comment]
I dont know Go, so I won't be much of a help here but I'm happy to see progress being made and I'm looking forward using it! Thanks for your work on this! :)

**Comment by dalenoe** [comment]
@elricsfate Submit as is, can be added to at any point. I would love to see vultr support.

Unfortunately I don't know go.

**Comment by elricsfate** [comment]
@catsby Is there any documentation on how to properly submit a pull request for a provider? 

I'll go ahead and submit a pull for the current state of the provider but wanted to know what you guys considered as best practice.

**Comment by jcs224** [comment]
@elricsfate Here's something I found:
https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md#new-provider

**Comment by tk8817** [comment]
There is an AWESOME 3rd party implementation of Vultr that just popped up, written by @squat 

https://github.com/squat/terraform-provider-vultr

It is feature complete for all core vultr services (instances, startup-scripts, ssh-keys, firewalls, networking). 

I know @elricsfate is still looking to get features added in his repo, and that @rgl 's repo has been abandoned. Perhaps it would be wise for us to rally around this new and very well thought out implementation.

It would be great to get the ball rolling on having it be an official provider.

**Comment by jcs224** [comment]
@tk8817 agreed. I can probably help implement this if needed.

Submitted an issue in his repo.
https://github.com/squat/terraform-provider-vultr/issues/5

**Comment by tk8817** [comment]
Thanks @jcs224 ! 

FYI I have a 12 node stack being managed by squat's implementation including heavy use of `count` for firewall rules, and instances. It is rock solid so far and he has been very responsive to issues. There are great examples in the repo to get you started. 

:)

**Comment by elricsfate** [comment]
I agree. The new implementation appears superior to the one I am working on. I am absolutely for integrating it into mainline as well.

**Comment by koalalorenzo** [comment]
Do we have a ETA for this? It would be awesome!

**Comment by mirageglobe** [comment]
Any movement or PR to official repo for vultr?

**Comment by dalenoe** [comment]
I can't believe this hasn't been done, yet. Just surprised vultr themselves haven't stepped up to the plate. I wonder how the DO provider has existed so long.

**Comment by damien-roche** [comment]
+1! This is a marriage that needs to happen. Though looks like that 3rd party stuff above is more than up to the task.

**Comment by atif089** [comment]
+1 Puhleez!

**Comment by ddymko** [comment]
I know this ticket is over a year old. However vultr did just release an official terraform provider...along with some other open source projects. 

https://github.com/vultr/terraform-provider-vultr

**Comment by tstrohmeier** [comment]
@ddymko Will this provider also be included on this page? https://www.terraform.io/docs/providers/index.html

**Comment by ddymko** [comment]
@tstrohmeier Yup! We are working with the Terraform team to get the terraform-provider-vultr listed as an official provider
