### ISSUE TITLE
Unable to create VPC Peering Between Cross Accounts As Multiple Aws Account Profiles Are Not Working As Excepted

### ISSUE THREAD

**Issue by anuya9** [hashicorp/terraform#26119]
Hi team,

We are working on an usecase where we need to do VPC Peering between two cross accounts. In order to pass aws credentials, we have configured two profiles one for development and another for production account using "aws configure set" command. 
Profile definition has been done in locals block. When we execute script using "terraform apply" command, it is noted that terraform is only picking one profile credentials and ignores the definition of other profile. This results into failing of VPC Peering connection between two accounts as terraform searches for VPC in the same account only. We also tried to maintain two separate aws credentials files as per environment. But still results same. Is there any way to use two profiles together?
 
  
### Terraform Version
0.12.28

### Terraform Configuration Files
Root Module main.tf
locals {
    prod_profile = "prod"
   dev_profile = "dev"
}
module "module-1" {
    source = "./module-1"
    profile = local.prod_profile
    peer_profile = local.dev_profile
    }
Child Module-1 main.tf
provider "aws" {
  alias = "requester"
  region = "us-east-1" 
  profile = var.profile   # Requester's credentials.
  shared_credentials_file = "/home/.aws/prod_credentials"
}

provider "aws" {
  alias = "accepter"
  profile = var.peer_profile  # Accepter's credentials.
  shared_credentials_file = "/home/.aws/dev_credentials"
}

resource "aws_vpc" "main" {
  provider = aws.requester
  cidr_block = "xx.x.x.x.xxx"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

data "aws_caller_identity" "peer" {
  provider = aws.accepter
}

# Requester's side of the connection.
resource "aws_vpc_peering_connection" "peer" {
  provider = aws.requester
  vpc_id        = aws_vpc.main.id
  peer_vpc_id   = var.aws_vpc.peer.id
  peer_owner_id = data.aws_caller_identity.peer.account_id
  auto_accept   = false

  tags = {
    Side = "Requester"
  }
}
NOTE: We have configured accepter vpc in another script
resource "aws_vpc" "peer" {
  provider = aws.accepter
  region = "us-west-2" 
  cidr_block = "xx.x.x.x.xxx"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

### Expected Behavior
Terraform should switch between the profiles are use both profile credentials as per the declaration.

### Steps to Reproduce
1. terraform init
2. terraform apply

### Additional Context
One more thing was noted, the locals block mentioned in Terraform Configuration Files section, terraform is picking the  credentials of the profile which is defined first in locals block. If we change the sequence of definition as mentioned below  then it will pick dev_profile credential and creates resources in development account and fails again at VPC Peering creation stage. 

locals {
   dev_profile = "dev"
  prod_profile = "prod"
  }

**Comment by mildwonkey** [comment]
Hi! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
