### ISSUE TITLE
aws_elasticache_cluster maintenance_window argument missing

### ISSUE THREAD

**Issue by PurrBiscuit** [hashicorp/terraform#2612]
would like to be able to set the maintenance_window in aws_elasticache_cluster like can be set for aws_db_instance

**Comment by catsby** [comment]
I've opened a patch for this in https://github.com/hashicorp/terraform/pull/2642 , let me know if you're able to check it out, otherwise we'll likely just merge it soon :smile:

**Comment by PurrBiscuit** [comment]
hey cool, looks good to me :+1:  thanks a lot!

**Comment by catsby** [comment]
Fixed in #2642
