### ISSUE TITLE
Terraform version command randomly hanging on Windows

### ISSUE THREAD

**Issue by dom54** [hashicorp/terraform#26131]
### Terraform Version

```
C:\projects\tools\terraform>terraform.exe version
Terraform v0.13.2

C:\projects\tools\terraform>terraform.exe version
Terraform v0.13.2

C:\projects\tools\terraform>terraform.exe version
Terraform v0.13.2

C:\projects\tools\terraform>terraform.exe version
Terraform v0.13.2

C:\projects\tools\terraform>terraform.exe version
<hangs indefinitely>
...
```

### Expected Behavior
Terraform should always print the version

### Actual Behavior
Terraform doesnt report any output (even with TF_LOG=DEBUG) sometimes when running the version command.
Other commands also hang randomly but version is the "simplest" one

Install Terraform v0.13.2
Run terraform version 10+ times.  For me - one of them hangs.

I am not sure how to further debug the issue, as it must be related to my environment

**Comment by dom54** [comment]
C:\projects\tools\terraform>terraform.exe version
2020/09/04 14:36:40 [INFO] Terraform version: 0.13.2
2020/09/04 14:36:40 [INFO] Go runtime version: go1.14.7
2020/09/04 14:36:40 [INFO] CLI args: []string{"C:\\projects\\tools\\terraform\\terraform.exe", "version"}
2020/09/04 14:36:40 [DEBUG] Attempting to open CLI config file: C:\Users\redacted\AppData\Roaming\terraform.rc
2020/09/04 14:36:40 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/09/04 14:36:40 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/09/04 14:36:40 [DEBUG] ignoring non-existing provider search directory C:\Users\dredacted\AppData\Roaming\terraform.d\plugins
2020/09/04 14:36:40 [DEBUG] ignoring non-existing provider search directory C:\Users\dredacted\AppData\Roaming\HashiCorp\Terraform\plugins
2020/09/04 14:36:40 [INFO] CLI command args: []string{"version"}
Terraform v0.13.2

C:\projects\tools\terraform>terraform.exe version
2020/09/04 14:36:43 [INFO] Terraform version: 0.13.2
2020/09/04 14:36:43 [INFO] Go runtime version: go1.14.7
2020/09/04 14:36:43 [INFO] CLI args: []string{"C:\\projects\\tools\\terraform\\terraform.exe", "version"}
2020/09/04 14:36:43 [DEBUG] Attempting to open CLI config file: C:\Users\redacted\AppData\Roaming\terraform.rc
2020/09/04 14:36:43 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/09/04 14:36:43 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/09/04 14:36:43 [DEBUG] ignoring non-existing provider search directory C:\Users\dredacted\AppData\Roaming\terraform.d\plugins
2020/09/04 14:36:43 [DEBUG] ignoring non-existing provider search directory C:\Users\dredacted\AppData\Roaming\HashiCorp\Terraform\plugins
2020/09/04 14:36:43 [INFO] CLI command args: []string{"version"}
Terraform v0.13.2

C:\projects\tools\terraform>terraform.exe version
<hangs forever unless I kill terraform.exe via process explorer>  (subsequent commands also hang)

**Comment by alisdair** [comment]
Thanks for reporting this! I'm unable to reproduce it on Windows 10, even after 30 attempts.

Since nothing is being printed at all, even with debug logs, it looks like something in your system is preventing the executable from running. This sounds like a virus protection system or malware detection software to me. Do you have anything like that which could be causing the problem?

**Comment by dom54** [comment]
Yes, several things I think could interfere ( but aren't reporting that they blocked anything ).

Also things that I cannot switch off to test ( work laptop etc ). Not sure how to prove it

**Comment by dom54** [comment]
So I have had a colleague do the exact same thing (same setup , same AV, etc) and he doesn't have the same issue.  I can even get it to hang (again, not everytime) by doing an invalid command (i renamed the exe to see if it was that somehow)

C:\projects\tools\terraform>terraform1 blah


Also, whenever I do this, I see two terraform.exe processes start up, is that normal?

**Comment by alisdair** [comment]
Yes, that's normal—it's Terraform forking at startup due to [panicwrap](https://github.com/mitchellh/panicwrap). In case that's somehow the issue, you could try disabling it using `set TF_FORK=0` (cmd.exe) or `$env:TF_FORK =` (PowerShell).

Beyond that, I'm not really sure what to suggest. If you're so inclined, perhaps you could try building Terraform from source and seeing if that helps? Or start it with a debugger such as [delve](https://github.com/go-delve/delve) and see if there's a system call which causes it to fail. Sorry, I'm running out of ideas!

**Comment by dom54** [comment]
No root cause found, but it seems to have stopped happening... going to close for now

**Comment by dom54** [comment]
Just to update this.... my problem has mysteriously disappeared, but 3 other colleagues have the same issue now!!  I installed Go, and the windows SDK WinDbg and the problem seems to have got scared and disappeared, I can no longer reproduce..
