### ISSUE TITLE
(MISSING) logger produce missing and encoded urls  in outputs for id's => terraform 0.13.2

### ISSUE THREAD

**Issue by innovia** [hashicorp/terraform#26139]
this is documented in here clearly 

https://github.com/hashicorp/terraform-provider-google/issues/7050

I get similar issue

```
: module.peering.google_service_networking_connection.private_vpc_connection: Refreshing state... [id=https%!A(MISSING)%!F(MISSING)%!F(MISSING)www.googleapis.com%!F(MISSING)compute%!F(MISSING)v1%!F(MISSING)projects%!F(MISSING)ami-doit-playground%!F(MISSING)global%!F(MISSING)networks%!F(MISSING)default:servicenetworking.googleapis.com]
````

as well as `%2f` for urls with `\`

**Comment by mildwonkey** [comment]
Here's the offending line (copied from the linked issue report): 


https://github.com/hashicorp/terraform/blob/27affd06cedff04d5a74c819cd296fa8ecff9e2b/terraform/eval_read_data_plan.go#L135

This has already been fixed in master, so I am going to close this issue. Thank you!
