### ISSUE TITLE
Problem with plugin-dir in Azure Pipeline

### ISSUE THREAD

**Issue by BartoszDopke** [hashicorp/terraform#26130]
Hi,

I'm using self-hosted agent in Azure Pipelines and I installed Terraform 0.13 there. When I use Terraform tasks in Azure Devops, as commandOptions I chose '-plugin-dir=/usr/local/bin/.terraform.d/plugins' to skip plugin downloading. Unfortunately, Terraform downloads it to artifact and makes it much heavier than it should be. Also next stage (deployment stage) uses only plugins from artifact, not from our agent.
We do not have much space on our virtual machine that's why we want to avoid unnecessary downloads.
In addition, we defined .terraformrc in home directory with plugin directory. Also we added environment variable as written there:
https://www.terraform.io/docs/commands/cli-config.html#provider-installation

Thank you in advance!

**Comment by pselle** [comment]
Hi there, apologies for the delay. Could you provide more details, including steps for reproduction, the exact version of Terraform you're using, and debug/trace logs? (basically, what's in the issue template?).

Also, it sounds like you're thinking of the provider cache, or perhaps you're trying to skip plugin downloading (previously `get-plugins=false` ... as of Terraform 0.13, providers are always installed on init and this cannot be skipped.

Could you share some more details, and we can figure out if there's a bug here? Apologies again that this issue ended up not getting triaged.

**Comment by BartoszDopke** [comment]
Hi there!
No problem, problem has been resolved. I actually used method below (Cache Task) to make it faster and lighter.
https://itnext.io/infrastructure-as-code-iac-with-terraform-azure-devops-f8cd022a3341

**Comment by pselle** [comment]
Thanks for following up!
