### ISSUE TITLE
Change in local location for child module directory

### ISSUE THREAD

**Issue by bharathkkb** [hashicorp/terraform#26143]
### Terraform Version

```
Terraform v0.12.29
Terraform v0.13.1
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Previously running `terraform init` initialized child modules, say foo, in 
`foo in .terraform/modules/foo/foo-module-v1.0.0`

### Actual Behavior

Now running `terraform init` initializes child modules in 
`foo in .terraform/modules/foo`
### Additional Context

This seemed to have happened sometime mid August, but I am unable to find any documentation around this change. We have 0.12.29 pinned in CI, so this does not seem to be due to 0.13.x.

**Comment by mildwonkey** [comment]
Hi @bharathkkb ,
It's not clear what the issue is here. Are you getting an error? The contents of the `.terraform` directory are an implementation detail, so we don't necessarily document changes that (should) only effect terraform, and not the end user. If this is causing a problem for you, I'd like to know why so we can discuss options.

**Comment by bharathkkb** [comment]
Hi @mildwonkey 
We have a module that uses `local-exec` provisioners to run some scripts. We had a recent issue opened https://github.com/terraform-google-modules/terraform-google-gcloud/issues/78 regarding a diff that was caused due to this and I wanted some clarity on whether this path did actually change. 

We use `${path.module}/scripts/foo.sh` so any changes to `${path.module}` will trigger a diff. [Example](https://github.com/terraform-google-modules/terraform-google-gcloud/blob/da14e0920412c5e0a355fbb798b366663dff22e8/main.tf#L164)

**Comment by mildwonkey** [comment]
Ah ok, now I understand - thank you for the clarification.

I'll dig around a bit - I don't see any changes in the module installer codepath that would explain this change, so I'm not sure if it's something we did deliberately _elsewhere_, or if it's the result of a change in an underlying library.

Can you share a snippet of your configuration that shows how you wrote that module's source? I can use that to write a local reproduction and compare 0.12 and 0.13 behavior.

**Comment by mildwonkey** [comment]
Update! I spoke with some internal folks who Know Things, and I have learned this:

> Last week some users started hitting rate limits on the GitHub endpoints for generating archives that the registry was linking to. Those archives included a top-level directory for the repository name.
> In order to buy some time to address that, the registry team switched the registry to use git:: sources instead, so now Terraform is just running git clone directly into the directory

So previously the registry was directing terraform to the zipfile archive of the module's git branch/tag in question, and now it's directing terraform to run git clone directly. 

The unanticipated side effect of that change is that there's no longer an extra directory in your module path (which was the result of unzipping the zip file archive). 

I'll report back to the registry team letting them know this ended up being disruptive in ways we hadn't anticipated, so we can avoid issues like this in the future. 

I'm sorry for the unexpected change!

**Comment by bharathkkb** [comment]
@mildwonkey many thanks for the update and if the registry team is looking for feedback, I would very much prefer the current directory structure because it will fix this issue https://github.com/terraform-google-modules/terraform-google-gcloud/issues/75 😅

**Comment by mildwonkey** [comment]
And EVEN MORE INFORMATION!

This issue is only going to impact users who were on Terraform v0.12.19+  before August 27th. That's the date that they started seeing rate limits getting hit and switched the protocol.  The registry always returned the `git::` url for Terraform v0.12.0-0.12.18 , and would not have the "extra" subdirectory. 

This also only impacts users of modules that use `path.module`.

**Comment by bharathkkb** [comment]
@mildwonkey would it be safe to assume that moving forward, we will be keeping the current structure or will be moving back to the "extra" subdirectory approach?

**Comment by mildwonkey** [comment]
That's the plan! The terraform core and registry teams have all been made aware that this caused problems for some users so we won't make a change like that again without ample communication beforehand. Sorry!
