### ISSUE TITLE
Handle un-quoted index keys from the CLI

### ISSUE THREAD

**Issue by EscVector** [hashicorp/terraform#26148]
### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/-/aws v3.5.0
+ provider registry.terraform.io/-/http v1.2.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/http v1.2.0
```

### Terraform Configuration Files

```terraform
variable "region" {
  default = "us-east-1"
}

# data.aws_vpcs.main:
data "aws_vpcs" "main" {
    tags = {
        "Type" = "test"
    }
}

data "aws_vpc" "main" {
    id = "${element(tolist(data.aws_vpcs.main.ids),1)}"
}

data "aws_subnet_ids" "public" {
  vpc_id = "${data.aws_vpc.main.id}"

  tags = {
    Type = "Public"
  }
  #depends_on = [aws_subnet.public_subnet]
}

# This fails
# Example: terraform state show will fail if id has dash
data "aws_subnet" "public" {
  for_each = data.aws_subnet_ids.public.ids
  id       = each.value
}

# This works fine
# Example: 
data "aws_subnet" "alternate_public" {
    count = "${length(data.aws_subnet_ids.public.ids)}"
    id = "${element(tolist(data.aws_subnet_ids.public.ids),count.index)}"
}

data "aws_subnet_ids" "private" {
  vpc_id = "${data.aws_vpc.main.id}"

  tags = {
    Type = "Private"
  }
}
```

### Debug Output

https://gist.github.com/EscVector/92d13f937ec59867c71424b6fb8ccf80#file-terraform-state-show-debug-output

### Expected Behavior

Expected run terraform state list:
terraform state show data.aws_subnet.public["subnet-008ebaf1ce58b3ed4"]

It should work just like: 
terraform state show data.aws_subnet.alternate_public[0]

### Actual Behavior

terraform state show data.aws_subnet.public["subnet-008ebaf1ce58b3ed4"]
Error parsing instance address: data.aws_subnet.public[subnet-008ebaf1ce58b3ed4]
This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify
the address to reference a specific instance.

### Steps to Reproduce

1. terraform init
2. terraform apply
3. terraform state list
4. terraform state show data.aws_subnet.public["subnet-008ebaf1ce58b3ed4"]

**Comment by jbardin** [comment]
Hi @EscVector 

Sorry you're having trouble here, as this is a common mistake. 
You can see in the output that terraform is attempting to parse the address `data.aws_subnet.public[subnet-008ebaf1ce58b3ed4]`, with no quotes around the instance key. Your shell is consuming the quotes in your command, and they need to be quoted or escaped in order to have them passed into terraform. 

Wrap the string in single quotes to prevent the shell from interpreting the inner quotes, e.g.

    terraform state show 'data.aws_subnet.public["subnet-008ebaf1ce58b3ed4"]'

We use GitHub issues for tracking bugs and enhancements, rather than for questions. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by EscVector** [comment]
Hey @jbardin, thanks for the feedback.

I'd consider it a feature request to make it work from the cmd prompt quotes or not.
I had tried simply quoting and got the same result which is when I created the bug issue here after a brief google search.
I'd have created as a feature request if I had more sleep.

As for the your noted solution, I'm guessing you are not running on Windows.
That said, the actual solution for Windows is to escape the quotes.  

Here's the obtuse way to return results from a Windows command prompt.
Showing examples where single or double or backtick fail and where character escape works.
. 
`  terraform state show 'data.aws_region.info["ap-northeast-2"]'
Error parsing instance address: 'data.aws_region.info[ap-northeast-2]'

This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify
the address to reference a specific instance.

  terraform state show "data.aws_region.info["ap-northeast-2"]"
Error parsing instance address: data.aws_region.info[ap-northeast-2]

This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify
the address to reference a specific instance.

  terraform state show `data.aws_region.info["ap-northeast-2"]`
Error parsing instance address: `data.aws_region.info[ap-northeast-2]`

This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify
the address to reference a specific instance.

  terraform state show data.aws_region.info["""ap-northeast-2"""]
# data.aws_region.info["ap-northeast-2"]:
data "aws_region" "info" {
    description = "Asia Pacific (Seoul)"
    endpoint    = "ec2.ap-northeast-2.amazonaws.com"
    id          = "ap-northeast-2"
    name        = "ap-northeast-2"
}

  terraform state show data.aws_region.info[\"ap-northeast-2\"]
# data.aws_region.info["ap-northeast-2"]:
data "aws_region" "info" {
    description = "Asia Pacific (Seoul)"
    endpoint    = "ec2.ap-northeast-2.amazonaws.com"
    id          = "ap-northeast-2"
    name        = "ap-northeast-2"
}
`
I believe the show command should be capable of handling the quote or non-quoted index name regardless and without having to comment out from the command prompt, so maybe not a bug, but a feature, but not a question.

**Comment by EscVector** [comment]
@jbardin thanks for providing clarity here.  I'd have opened it under Feature Request had I had more sleep, though I know that as a feature it would be debated that it is behaving as "expected".  

As for quoting, it doesn't work like that on Windows, which is why I opened this as a bug in the first place.  I'm guessing you are not running on Windows.

Here's the obtuse way to return results from a Windows command prompt.
Showing examples where single or double or backtick fail and where character escape works.

    terraform state show 'data.aws_region.info["ap-northeast-2"]
    Error parsing instance address: 'data.aws_region.info[ap-northeast-2]'

    This command requires that the address references one specific instance.
    To view the available instances, use "terraform state list". Please modify
    the address to reference a specific instance.  

    terraform state show "data.aws_region.info["ap-northeast-2"]"
    Error parsing instance address: data.aws_region.info[ap-northeast-2]
    
    This command requires that the address references one specific instance.
    To view the available instances, use "terraform state list". Please modify
    the address to reference a specific instance.

    terraform state show \`data.aws_region.info["ap-northeast-2"]\` 
    Error parsing instance address: `data.aws_region.info[ap-northeast-2]`

    This command requires that the address references one specific instance.
    To view the available instances, use "terraform state list". Please modify
    the address to reference a specific instance.

    terraform state show data.aws_region.info["""ap-northeast-2"""]
    # data.aws_region.info["ap-northeast-2"]:
    data "aws_region" "info" {
        description = "Asia Pacific (Seoul)"
        endpoint    = "ec2.ap-northeast-2.amazonaws.com"
        id          = "ap-northeast-2"
        name        = "ap-northeast-2"
    }

       terraform state show data.aws_region.info[\"ap-northeast-2\"]
       # data.aws_region.info["ap-northeast-2"]:
       data "aws_region" "info" {
           description = "Asia Pacific (Seoul)"
           endpoint    = "ec2.ap-northeast-2.amazonaws.com"
           id          = "ap-northeast-2"
           name        = "ap-northeast-2"
       }

I believe the show command should be capable of handling the quote or non-quoted index name regardless and without having to comment out from the command prompt, so maybe a feature request and not a bug, but definitely not a question.  

I would be nice

**Comment by jbardin** [comment]
Thanks @EscVector 
I reopened this as possible feature request.

**Comment by bflad** [comment]
For reference, some previous discussion on this (although its likely the implementation details have changed further by now): https://github.com/hashicorp/terraform/pull/22395

**Comment by EscVector** [comment]
@jbardin Thanks!  
I have a workaround [.bat helper file](https://github.com/EscVector/terraform-windows-helper-files/blob/master/tfs.bat) that replaces single " with """ and also removes : if clip is grabbed from initial apply state output.

Windows cmd "Quick Edit Mode" cut-n-paste is what I'm doing.  
Huge time saver, but having the terraform.exe windows version do this naturally would be very nice.

**Comment by EscVector** [comment]
helper file fixed it
