### ISSUE TITLE
Provider configuration not present using aws provider alias - v0.13.2

### ISSUE THREAD

**Issue by iamsec** [hashicorp/terraform#26159]
<!--
Hi there,

Error: Provider configuration not present

To work with module.guarduty-multi.aws_guardduty_detector.member its original
provider configuration at
module.guarduty-multi.provider["registry.terraform.io/hashicorp/aws"].member
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
module.guarduty-multi.aws_guardduty_detector.member, after which you can
remove the provider configuration again.

### Main.tf
```
module "guardduty-multi" {
    source = "./modules/guardduty" 
}

```

### Providers.tf
```
provider "aws" {
    alias = "master"
    region = "us-east-1"
    profile = var.master_profile
}

provider "aws" {
    alias = "member"
    region = "us-east-1"
    profile = var.member_profile
}
```

### Variables.tf
```
variable "member_profile" {
    type = string
    default = "member"
}

variable "master_profile" {
    type = string
    default = "default"
}

```
### guardduty module file
```
resource "aws_guardduty_detector" "master" {
    enable = true
}

resource "aws_guardduty_detector" "member" {
    provider = aws.member
    enable = true
}

resource "aws_guardduty_member" "member" {
    account_id         = aws_guardduty_detector.member.account_id
    detector_id        = aws_guardduty_detector.master.id
    email              = "emailid@acme.com"
    invite             = true
    invitation_message = "please accept Guardduty invitation from Master Account"
}

```

### Terraform Version
v0.13.2
* hashicorp/aws: version = "~> 3.5.0"

### Expected results
I'm trying to have Terraform enable GD on two accounts (master & member). Enabling GD on the member account appears to be the issue:

```
module file:

resource "aws_guardduty_detector" "member" {
    provider = aws.member
    enable = true
}

```

**Comment by iamsec** [comment]
I'm trying to have Terraform enable AWS GuardDuty on two accounts (Master & Member) using provider alias.

## Moule file
esource "aws_guardduty_detector" "master" {
    enable = true
}

resource "aws_guardduty_detector" "member" {
    provider = aws.member
    enable = true
}

resource "aws_guardduty_member" "member" {
    account_id         = aws_guardduty_detector.member.account_id
    detector_id        = aws_guardduty_detector.master.id
    email              = "emailid@acme.com"
    invite             = true
    invitation_message = "please accept Guardduty invitation from Master Account"
}



### Terraform Version
v0.13.2
* hashicorp/aws: version = "~> 3.5.0"

### Expected results
I'm trying to have Terraform enable GD on two accounts (master & member). Enabling GD on the member account appears to be the issue:


resource "aws_guardduty_detector" "member" {
    provider = aws.member
    enable = true
}

## Error output
Error: Provider configuration not present

To work with module.guardduty-multi.aws_guardduty_detector.member its original
provider configuration at
module.guardduty-multi.provider["registry.terraform.io/hashicorp/aws"].member
is required, but it has been removed. This occurs when a provider
configuration is removed while objects created by that provider still exist in
the state. Re-add the provider configuration to destroy
module.guardduty-multi.aws_guardduty_detector.member, after which you can
remove the provider configuration again.

**Comment by iamsec** [comment]
### Main.tf
```
module "guardduty-multi" {
    source = "./modules/guardduty" 
}

```

### Providers.tf
```
provider "aws" {
    alias = "master"
    region = "us-east-1"
    profile = var.master_profile
}

provider "aws" {
    alias = "member"
    region = "us-east-1"
    profile = var.member_profile
}
```

### Variables.tf
```
variable "member_profile" {
    type = string
    default = "member"
}

variable "master_profile" {
    type = string
    default = "default"
}

**Comment by pselle** [comment]
Hello! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

It appears that you haven't passed your aliased provider to your module:

```
module "guardduty-multi" {
    source = "./modules/guardduty" 
}
```

If you need a particular provider in that module that you've defined in your providers.tf (I'm not confident of the file structure here, but this is what I'm guessing), you need to pass that provider to the module as documented here: https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly. I hope this helps a little!
