### ISSUE TITLE
terraform should warn when unexpected attributes are in required_providers

### ISSUE THREAD

**Issue by francisferrell** [hashicorp/terraform#26160]
I'm just getting spun up with vanilla terraform for a personal project after using terragrunt at work. I think I've got it configured correctly, but maybe I made a mistake. I think this is a bug in terraform, not in the aws provider, because a trivial sample works on 0.12.29 but the behavior regresses on 0.13.2.

I have the region configured in the tf and as the region in the AWS profile config. I therefore expect to not be prompted for the region.

### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.5.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.5.0"
      profile = "terraform"
      region = "us-east-1"
    }
  }

  backend "s3" {
    profile = "terraform"
    region = "us-east-1"
    bucket = "terraform-francisferrell"
    key = "terraform.tfstate"
    dynamodb_table = "terraform-francisferrell"
  }
}


resource "aws_s3_bucket" "foo" {
}
```

```
 ~ $ cat ~/.aws/config
[profile francis]
region = us-east-1
cli_pager =
[profile terraform]
region = us-east-1
cli_pager =
```

```
 ~ $ env | grep AWS
AWS_DEFAULT_PROFILE=francis
```

### Expected Behavior

A plan

### Actual Behavior

```
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value:
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by francisferrell** [comment]
For comparison, the following produces the expected result. Same AWS profile configuration and env is in effect here.

### Terraform Version


```
Terraform v0.12.29
+ provider.aws v3.5.0

Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files


```terraform
provider "aws" {
  version = "3.5.0"
  profile = "terraform"
  region = "us-east-1"
}

terraform {
  backend "s3" {
    profile = "terraform"
    region = "us-east-1"
    bucket = "terraform-francisferrell"
    key = "terraform.tfstate"
    dynamodb_table = "terraform-francisferrell"
  }
}

resource "aws_s3_bucket" "foo" {
}
```

**Comment by mildwonkey** [comment]
hi @francisferrell !

The required_providers setting is only used to set the version and source for a provider - you still need your provider configuration block:

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.5.0"
    }
  }

provider "aws" {
  profile = "terraform"
  region = "us-east-1"
}

  backend "s3" {
    profile = "terraform"
    region = "us-east-1"
    bucket = "terraform-francisferrell"
    key = "terraform.tfstate"
    dynamodb_table = "terraform-francisferrell"
  }
}


resource "aws_s3_bucket" "foo" {
}
```

When I originally wrote this, I omitted any error message for unexpected attributes in a required_providers setting (like "region" in your first example) for backwards compatibility (0.12 accepted the new required_providers syntax but ignored anything other than "version"), but if this confusion comes up frequently we can change that. 

I am going to re-title and re-label this as an enhancement, specifically to add a warning when unexpected attributes show up in `required_providers`. Thanks for reporting it, and I'm sorry for the confusion!

**Comment by bflad** [comment]
Related: https://github.com/terraform-providers/terraform-provider-aws/issues/15042

**Comment by francisferrell** [comment]
@mildwonkey got it, thanks for clarifying. I'll give it a try tonight and verify that it works like expected.

I think I was confused by the way the docs present it (https://registry.terraform.io/providers/hashicorp/aws/latest/docs). In the docs for the aws provider, when I click on the USE PROVIDER button and get the popup, the two forms are presented in a way that _seems_ mutually exclusive:

Terraform 0.13  [Latest]

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.5.0"
    }
  }
}
```

vs:

Terraform <= 0.12

```terraform
provider "aws" {
  version = "3.5.0"
}
```

Then, in the body of that document, right at the top, is this example:

```terraform
# Configure the AWS Provider
provider "aws" {
  version = "~> 3.0"
  region  = "us-east-1"
}
```

Not knowing better, I interpret this as a holdover from 0.12.x that hasn't yet been updated for the new 0.13.x syntax, so I dutifully migrate the entire provider section into the aws section inside required_providers.

Maybe there's some other documentation somewhere else that explains how providers _in general_ are configured and how 0.13 introduces a split of the provider version into a separate block form the provider's own parameters. But, looking at https://www.terraform.io/docs/backends/config.html there is no mention of required_providers.

**Comment by francisferrell** [comment]
@mildwonkey as written this gives:

```
Error: Unsupported block type

  on main.tf line 10, in terraform:
  10: provider "aws" {

Blocks of type "provider" are not expected here.
```

I put `provider "aws" { ... }` in its own top-level block adjacent to, instead of inside of, `terraform { ... }`.

That got my issue sorted out. I got a complete plan/apply/destroy cycle working as expected with no prompts for region. Thanks for pointing me in the right direction.

Here's the full tf for reference

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.5.0"
    }
  }

  backend "s3" {
    profile = "terraform"
    region = "us-east-1"
    bucket = "terraform-francisferrell"
    key = "terraform.tfstate"
    dynamodb_table = "terraform-francisferrell"
  }
}


provider "aws" {
  profile = "terraform"
  region = "us-east-1"
}


resource "aws_s3_bucket" "foo" {
}
```
