### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by oihuegbu** [hashicorp/terraform#26161]
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.5.0"
    }
  }
}

resource "aws_s3_bucket" "kashbucket1" {
  bucket = "kashbucket860"
  acl    = "private"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

**This is the error the pops up:**

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "3.5.0"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
could not connect to registry.terraform.io: Failed to request discovery
document: Get "https://registry.terraform.io/.well-known/terraform.json":
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by alisdair** [comment]
Thanks for the report! This looks like a networking error, which I'm unable to reproduce and may have self-resolved. Can you confirm that this is still happening?

**Comment by oihuegbu** [comment]
It work now. Thank you
