### ISSUE TITLE
EKS VPC Identifier. 

### ISSUE THREAD

**Issue by void0x79** [hashicorp/terraform#26167]
Hello, I am currently running Terraform v0.13.0.
I have a AWS account with 3 VPCs and trying to create a EKS cluster in each VPC. 

I have noticed that there is not documentation on HOW to identify which cluster should be long to which VPC. 
We have all the options in the VPC_Config block (Subnets, Private/Public etc) but not a VPC_ID identifier. 

resource "aws_eks_cluster" "vault_cluster" {
    depends_on = [aws_iam_role.vault_eks_role]
    name = "vault"
    role_arn = aws_iam_role.vault_eks_role.arn
    vpc_config {
        subnet_ids = ["subnet-xxxxxxxx", "subnet-yyyyyyyy"]
        endpoint_private_access = true
        endpoint_public_access = false
       **_vpc_id = <This would be nice>_** 
    }
}

**Comment by bflad** [comment]
Closing to stop hashibot issue.
