### ISSUE TITLE
Terraform 0.13.2 cannot read AWS provider credentials from ~/.aws/credentials

### ISSUE THREAD

**Issue by amartopoulos** [hashicorp/terraform#26174]
###
OS
```
Debian bullseye
```

### Terraform Version

```
0.13.2
```

### Terraform Configuration Files

```
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "XXXXXXXXXXXXXXX"

    workspaces {
      name = "eks-prod"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

data "aws_availability_zones" "available" {}

# Not required: currently used in conjunction with using
# icanhazip.com to determine local workstation external IP
# to open EC2 Security Group access to the Kubernetes cluster.
# See workstation-external-ip.tf for additional information.
provider "http" {}

```

### Debug Output

https://gist.github.com/amartopoulos/aeaee00143d4f9cd0011605157c7fda6

### Expected Behavior

Terraform should be able to read from the file indicated in shared_credentials_file and/or from environment variables.

### Actual Behavior

Terraform fails to read credentials unless both the access/secret keys are _explicitly_ written in the provider block, which prevents me from pushing my configuration to any source control.  (At the moment, I'm simply trying to use one of the examples from the terraform-providers-aws repo).  I have tried specifying the provider block like so:

```
provider "aws" {
  region                  = "us-west-2"
  shared_credentials_file = "/home/andrew/.aws/credentials"
  profile                 = "profile"
}
```
and when that didn't work, I ripped out everything but region and tried specifying various environment variables:

```
export AWS_SHARED_CREDENTIALS_FILE=/home/andrew/.aws/credentials
export AWS_PROFILE=default

export AWS_ACCESS_KEY_ID=XXXX
export AWS_SECRET_ACCESS_KEY=XXXX
export AWS_DEFAULT_REGION
```
Every time, I get the `Error: NoCredentialProviders: no valid providers in chain.` error.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by pselle** [comment]
@amartopoulos In the information you've shared here, you're running your plan on the remote backend. Have you updated your Terraform Cloud account to have the appropriate credentials?

**Comment by amartopoulos** [comment]
@pselle I haven't explicitly added any credential information to my Terraform Cloud account.  It's only specified in one of my providers.tf config file.  Is there a way I can check to see what's in my TC account?  I'm poking around in the UI now and don't see anything about AWS provider credentials.

**Comment by amartopoulos** [comment]
Also, FWIW, it seems the aws CLI is using the credentials file just fine:

```
$ aws cloudformation list-stacks
{
    "StackSummaries": []
}

```

**Comment by amartopoulos** [comment]
Sorry, I fundamentally misunderstood how the Cloud product worked (I didn't know you set the environment variables in the Cloud UI itself).
