### ISSUE TITLE
Failed to pull image "gcr.io/terraform-project/test:v1": rpc error: code = Unknown desc = Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials.

### ISSUE THREAD

**Issue by priyankak1212** [hashicorp/terraform#26196]
### Terraform Version
Terraform v0.12.28
+ provider.kubernetes v1.13.1

Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html

### Terraform Configuration Files
resource "google_container_cluster" "dev" {
  provider = google-beta
  name               = "test"
  network            = "default"
  location           = "us-central1-a"
  initial_node_count = 3
  networking_mode    = "VPC_NATIVE"

  
  ip_allocation_policy {
    cluster_ipv4_cidr_block  = ""
    services_ipv4_cidr_block = ""
  }  

  master_auth {
    username = ""
    password = ""

    client_certificate_config {
      issue_client_certificate = false
    }
  }

  node_config {
    service_account = "XXXX@XXXXx.iam.gserviceaccount.com"
    oauth_scopes = [
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
      "https://www.googleapis.com/auth/servicecontrol",
      "https://www.googleapis.com/auth/service.management.readonly",
      "https://www.googleapis.com/auth/trace.append"
    ]

    metadata = {
      disable-legacy-endpoints = "true"
    }

  }

}

### Expected Behavior
After creating kubernetes cluster on GCP using above terraform script, ideally i should be able to deploy deployment in kubenetes cluster without manually configuring the google container registry into kuberenetes cluster.

### Actual Behavior
I created GKE cluster using above terraform script.Then, trying to deploy deployment.yaml (through terminal using gcloud) on created kubernetes cluster which is generated by terraform script.But it's giving me the following error:
Failed to pull image "gcr.io/terraform-project/test:v1": rpc error: code = Unknown desc = Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials.

But, when i created another GKE cluster from GCP console by taking the clone or duplicate of above GKE cluster (which is generated by terraform script) , then I am successfully able to deploy deployment.yaml (through terminal using gcloud) in cloned cluster.
 
Unable to understand, why unable to deploy deployment in GKE cluster which is generated by terraform script and able to deploy deployment in GKE cluster which is generated from GCP console although tried using the same service account for both the clusters.

Thanks

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by pselle** [comment]
Hello! This reads as more of a question related to the kubernetes provider than to Terraform Core.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.
