### ISSUE TITLE
repo_url

### ISSUE THREAD

**Issue by waynejnicklin** [hashicorp/terraform#26199]
When I deploy a "azurerm_function_app" via Terraform, it creates a "source_control" properties block, with repo_url set to "", which is correct.

When we then deploy a function into that function app, and run the infrastructure pipeline again, it changes that repo_url to "VSTSRM" in the state file... and then fails with:

Error: failed to create App Service Source Control for "sr-dm-tst-we-app" (Resource Group "SR-DM-TST-WE-RG"): web.AppsClient#CreateOrUpdateSourceControl: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Operation not supported: RepoUrl VSTSRM is not supported." Details=[{"Message":"Operation not supported: RepoUrl VSTSRM is not supported."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51024","Message":"Operation not supported: RepoUrl VSTSRM is not supported.","MessageTemplate":"Operation not supported: {0}","Parameters":["RepoUrl VSTSRM is not supported."]}}]

It also deletes the existing function from the azurerm_function_app.

Where is that VSTSRM coming from? We don't specify it anywhere, but Terraform seems to create it, and then fail because it's there.

Thanks,
Wayne

**Comment by pselle** [comment]
Hello! 

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by bytemech** [comment]
Think this was closed in error... seeing the same bug in current provider version.

**Comment by waynejnicklin** [comment]
I raised it on the community forums as requested.

**Comment by waynejnicklin** [comment]
Good to know it’s not just me seeing this issue :-)

**Comment by waynejnicklin** [comment]
https://discuss.hashicorp.com/t/vstsrm-value-in-repo-url-in-function-app/14133

**Comment by pselle** [comment]
I'll reopen and tag this as the Azure provider -- thanks for posting in the forum, my concern is it's not under the Azure category to the folks who can help might not see it. Hopefully getting this into the Azure queue would move this forward for you getting an answer.

**Comment by waynejnicklin** [comment]
Brilliant, thank you :-)
