### ISSUE TITLE
timecmp function

### ISSUE THREAD

**Issue by jnehlt** [hashicorp/terraform#26217]
### Current Terraform Version

```
Terraform v0.12.29
```

### Use-cases

Rotating credentials for `azuread_service_principal` resources, but it might be helpful for any kind of resources.
This resource doesn't provide any information about credentials expiration, so I want to add `credential_timestamp` and `credential_duration` tags to `azuread_service_principal` resource. Later just want to use `timeadd` and `timestamp` fuctions and compare it using `timecmp` function so I can use `triggers` in `azuread_service_principal_password` resource, `random_password`, assign new credentials to `azuread_service_principal` and override `azuread_service_principal` tags.

### Attempted Solutions

I was trying to compare timestamps in Terraform but with no luck.

### Proposal

I've created timecmp function feature on my fork. Please take a look [here](https://github.com/jnehlt/terraform/commit/deee615406cce7dcd42c58cb24673aedc94aa4f6)
Let me know if you accept it so i can write tests, update documentation/terraform-website and create PR for it.

Greetings guys!

**Comment by alisdair** [comment]
@jnehlt I'm not completely clear on your use case here, but you may want to look at [the `time` provider](https://registry.terraform.io/providers/hashicorp/time/latest/docs), as it may be able to do what you're looking for. In particular, see [the `time_rotating` resource](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating).

I would also recommend [posting on the discussion forum](https://discuss.hashicorp.com/c/terraform-core/27), as other more experienced Terraform users may have ideas for how to do what you're looking to do.

**Comment by jnehlt** [comment]
Thank you @alisdair 

I've did it with time_rotationg resource as you suggested.

Simple example:
```terraform
resource "azuread_application" "app" {
  name = "name"
}

resource "time_rotating" "credential_rotation" {
  rotation_minutes = 1
}

resource "azuread_service_principal" "sp" {
  application_id = azuread_application.app.application_id
}

resource "random_password" "sp_password_generator" {
  keepers = {
    credential_rotation = time_rotating.credential_rotation.id
  }
  length = 30
}

resource "azuread_service_principal_password" "sp_password" {
  service_principal_id = azuread_service_principal.sp_list.id
  value                = random_password.sp_password_generator.result
  end_date             = timeadd(time_rotating.credential_rotation.id, "1m")
}
```

It works like a charm.

Thanks a lot!
