### ISSUE TITLE
Changing root directory does not work with "init"

### ISSUE THREAD

**Issue by ussuritiger** [hashicorp/terraform#26218]
### Terraform Version
```
v0.13.2
```

### Expected Behavior
Terraform working directory should be initialized.

### Actual Behavior
```
Invalid flags before the subcommand. If these flags are for
the subcommand, please put them after the subcommand.
```

### Steps to Reproduce
`terraform -chdir=directory-with-terraform-files init`
or
`terraform init -chdir=directory-with-terraform-files`

### References
https://www.terraform.io/docs/commands/init.html#passing-a-different-configuration-directory

**Comment by pselle** [comment]
@ussuritiger Our apologies -- by the time you read this, ideally those docs will have been updated. The `-chdir` option will be released in (not yet complete) Terraform 0.14, but is not available in the current 0.13 series.
