### ISSUE TITLE
timestamp function unexpected behaviour in an if statement within a dynamic block

### ISSUE THREAD

**Issue by itzimourakas** [hashicorp/terraform#26220]
### Terraform Version
```
Terraform v0.12.29
+ provider.oci v3.92.0
+ provider.tls v2.2.0
```

### Terraform Configuration Files
```terraform
resource "tls_private_key" "tls_private_key" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P384"
}

resource "tls_cert_request" "example" {
  key_algorithm   = "ECDSA"
  private_key_pem = tls_private_key.tls_private_key.private_key_pem

  dynamic subject {
    for_each = tonumber(formatdate("YYYY", timestamp())) > 2021 ? [true] : []
    # for_each = 2020 > 2021 ? [true] : []
    # for_each = []

    content {
      common_name  = "example.com"
      organization = "ACME Examples, Inc"
    }
  }
}
```

### Debug Output
https://gist.github.com/itzimourakas/728380de25b97884cb71478129ced426

### Crash Output
No crash

### Expected Behavior
expected the below error
```
Error: "subject": required field is not set
```
but without any diff before that.

### Actual Behavior
```
Terraform will perform the following actions:

  # tls_cert_request.example will be created
  + resource "tls_cert_request" "example" {
      + cert_request_pem = (known after apply)
      + id               = (known after apply)
      + key_algorithm    = "ECDSA"
      + private_key_pem  = (sensitive value)

      + subject {
          + common_name  = (known after apply)
          + organization = (known after apply)
        }
    }
```
followed by the error
```
Error: "subject": required field is not set
```

### Steps to Reproduce
use the snippet above

### Additional Context
The if statement should return false in which case the result should be an empty list. In this case Terraform should error immediately rather than suggesting the addition of the subject block. I've commented two lines after the for_each statement in order to show that uncommenting any of the commented out lines will produce the expected results which is error immediately without a diff. I put this down to the timestamp function. Whenever I replace it with something else it works as expected. I've also tried the same with the oci provider and another type of resource. Same behaviour.

### References
N/A

**Comment by alisdair** [comment]
Thanks for reporting this issue!

I believe this is expected behaviour. The [`timestamp` function docs explain why](https://www.terraform.io/docs/configuration/functions/timestamp.html):

> The result of this function will change every second, so using this function directly with resource attributes will cause a diff to be detected on every Terraform run. We do not recommend using this function in resource attributes, but in rare cases it can be used in conjunction with the `ignore_changes` lifecycle meta-argument to take the timestamp only on initial creation of the resource.
> 
> Due to the constantly changing return value, the result of this function cannot be predicted during Terraform's planning phase, and so the timestamp will be taken only once the plan is being applied.

Terraform does not evaluate `timestamp` until the apply phase, at which point it is too late to see the error behaviour you're expecting. I don't know of any way of achieving what I'm guessing your goal is: conditionally creating resources based on the time of the Terraform execution. [You may want to post a question in the discussion forum for ideas](https://discuss.hashicorp.com/c/terraform-core/27).

I'm closing this issue as I believe Terraform is working as designed.
