### ISSUE TITLE
aws_elb destructive changes fail

### ISSUE THREAD

**Issue by rbowlby** [hashicorp/terraform#2623]
aws_elb destructive changes fail due to failed destroy of corresponding security group. Upon updating an aws_elb resource to contain an additional listener the terraform apply fails. It appears that terraform attempts to destroy the security group before first destroying resources using that sec group.

```
aws_security_group.admin_elb: Destroying...
aws_security_group.admin_elb: Error: 1 error(s) occurred:

* DependencyViolation: resource sg-1476fa71 has a dependent object
	status code: 400, request id: []
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* DependencyViolation: resource sg-1476fa71 has a dependent object
	status code: 400, request id: []
```

**Comment by rbowlby** [comment]
I ended up having to taint the entire module.

**Comment by catsby** [comment]
Hey @rbowlby – do you have an example config that demonstrates this that I could use to debug further?   I'm not clear on the structure here, you have an ELB and a Security Group, it sounds like the ELB hasn't been fully destroyed before we attempt to destroy the SG. 

If you do have a config you can share, please make sure to remove any secrets. Thanks!

**Comment by catsby** [comment]
I'm going to close this for now. It looks like the security groups in question need the `lifecycle` block added to prevent this kind of issue:

- https://terraform.io/docs/configuration/resources.html

Let me know if you have any other questions, or a configuration that otherwise reproduces this issue.
