### ISSUE TITLE
DNS lookup on android fails

### ISSUE THREAD

**Issue by baztian** [hashicorp/terraform#26235]
I'm getting 

    Error: error using credentials to get account ID: error calling sts:GetCallerIdentity: RequestError: send request failed
    caused by: Post https://sts.amazonaws.com/: dial tcp: lookup sts.amazonaws.com on [::1]:53: read udp [::1]:34299->[::1]:53: read: connection refused

(guessing that this is not provider specific or should affect all providers)

### Terraform Version

```
Terraform v0.12.29
```
(Also tested with Terraform v0.13.2)

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.12.2"

  backend "s3" {
    region         = "eu-central-1"
    bucket         = "foobar-dev-terraform-state"
    key            = "dev/terraform-state.tfstate"
    dynamodb_table = "foobar-dev-terraform-state-lock"
    encrypt        = "true"
  }
}

provider "aws" {
  region = "eu-central-1"
}

data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

module "terraform_state_backend" {
  source        = "git::https://github.com/cloudposse/terraform-aws-tfstate-backend.git?ref=0.21.0"
  namespace     = data.aws_caller_identity.current.account_id
  stage         = "dev"
  name          = "terraform"
  attributes    = ["state"]
  region        = data.aws_region.current.name
  billing_mode = "PAY_PER_REQUEST"
  force_destroy                      = false
 }
```

### Debug Output

https://gist.github.com/baztian/fca874824f945017096c08b491dd770d

### Expected Behavior

Proper terraform initilization with downloading of the modules.

### Actual Behavior

    Error: error using credentials to get account ID: error calling sts:GetCallerIdentity: RequestError: send request failed
    caused by: Post https://sts.amazonaws.com/: dial tcp: lookup sts.amazonaws.com on [::1]:53: read udp [::1]:34299->[::1]:53: read: connection refused

### Steps to Reproduce

    $ terraform12 init

    Error: error using credentials to get account ID: error calling sts:GetCallerIdentity: RequestError: send request failed
    caused by: Post https://sts.amazonaws.com/: dial tcp: lookup sts.amazonaws.com on [::1]:53: read udp [::1]:34299->[::1]:53: read: connection refused
    $ # Debug output included in the gist
    $ terraform12 --version
    Terraform v0.12.29

This are my experiences in upgrading to terraform 0.13 (no debug output)

    $ terraform 0.13upgrade
    This command will update the configuration files in the given directory to use
    the new provider source features from Terraform v0.13. It will also highlight
    ...
    Enter a value: yes

    -----------------------------------------------------------------------------

    Warning: Could not detect provider source

    Error looking up provider source for "aws": could not connect to
    registry.terraform.io: Failed to request discovery document: Get
    "https://registry.terraform.io/.well-known/terraform.json": dial tcp: lookup
    registry.terraform.io on [::1]:53: read udp [::1]:47326->[::1]:53: read:
    connection refused

    -----------------------------------------------------------------------------

    Upgrade complete!

    Use your version control system to review the proposed changes, make any
    necessary adjustments, and then commit.
    $ terraform --version
    Terraform v0.13.2

### Additional Context

I'm using the official Terraform release for ARM architecture on Android with [Termux](https://termux.com/).

This seems to be typical to go applications. I had the same issue with aws-vault. Fortunately the maintainer [could fix it](https://github.com/99designs/aws-vault/issues/647) for me. Maybe that patch could help to fix terraform as well.

### References

https://github.com/99designs/aws-vault/issues/647

**Comment by alisdair** [comment]
Thanks for reporting this issue.

Unfortunately Android is not one of our supported operating systems, and the hack proposed to work around the bug in Android would adversely affect other Linux/ARM users due to bypassing their DNS configuration. As a result I don't think we'll be able to fix this for you. Sorry!
