### ISSUE TITLE
Terraform always tries to find providers from "hashicorp".

### ISSUE THREAD

**Issue by bcline760** [hashicorp/terraform#26251]
Terraform is always trying to load the provider from "hashicorp" repository instead of the repository mentioned in my configuration.

### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/mrparkers/keycloak v2.0.0-rc.0
```

### Terraform Configuration Files
```terraform
terraform {
  required_providers {
    keycloak = {
      source = "mrparkers/keycloak"
      version = "2.0.0-rc.0"
    }
  }
}

provider "keycloak" {
  client_id      = var.provider_client_id
  client_secret  = var.provider_client_secret
  url            = var.realm_url
  realm          = var.realm_name
  client_timeout = 10
}
```

### Debug Output
[Debug Gist](https://gist.github.com/bcline760/474532da79362e00cb17af081035826f)

### Expected Behavior

Terraform should use the provider mentioned in the terraform block only.

### Actual Behavior

```text
Initializing modules...
- client in _modules/client

Initializing the backend...

Initializing provider plugins...
- Finding mrparkers/keycloak versions matching "2.0.0-rc.0"...
- Finding latest version of hashicorp/keycloak...
- Installing mrparkers/keycloak v2.0.0-rc.0...
- Installed mrparkers/keycloak v2.0.0-rc.0 (self-signed, key ID C50867915E116CD2)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing hashicorp/keycloak: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/keycloak
```

### Steps to Reproduce

1. Run `terraform init`

**Comment by apparentlymart** [comment]
Hi @bcline760!

Could you try running `terraform providers` and share the output? It looks like you have two modules in your configuration but I suspect only one of them contains a dependency declaration for `mrparkers/keycloak`, and so the other one is defaulting to `hashicorp/keycloak`.

**Comment by bcline760** [comment]
```text
Providers required by configuration:
.
├── provider[registry.terraform.io/mrparkers/keycloak] 2.0.0-rc.0
└── module.client
    └── provider[registry.terraform.io/hashicorp/keycloak]
```

So you're saying I need to place the provider declaration in the module directory as well?

**Comment by apparentlymart** [comment]
Thanks for sharing that additional context, @bcline760.

And indeed, the client module must also declare that "keycloak" in that module means `mrparkers/keycloak` rather than `hashicorp/keycloak`. This ensures that each module is self-contained and its meaning will not change depending on where it is used.

**Comment by mildwonkey** [comment]
I'm going to close this issue since it's been explained and there's a solution. Thanks!
