### ISSUE TITLE
Backend hash is updated too early

### ISSUE THREAD

**Issue by lsierant** [hashicorp/terraform#26259]
### Terraform Version
```
0.12.29
0.13.2
0.14.0-dev (master)
```

### Terraform Configuration Files
Essentialy this is: `command/testdata/backend-change` dir:  https://github.com/hashicorp/terraform/tree/master/command/testdata/backend-change

### Debug Output
Full output with all steps to reproduce: https://gist.github.com/lsierant/ad4169675b0e6ee9697d1b37333f504d

### Expected Behavior
When backend configuration is changed I expect that failed `terraform init` will not change my cached backend config in `.terraform/terraform.tfstate`. Any subsequent (failed) inits should behave the same (informing on changed backend). 

### Actual Behavior
When `terraform init` fails, the hash in `.terraform/terraform.tfstate` is updated with value calculated from updated config, but cached config remains unchanged. Subsequent `terraform init` fails to recognise changed backend config and uses old cached backend without informing the user. 

This could be dangerous as the user is not expecting terraform is using old backend having another one set in config file (see additional context below). 

### Steps to Reproduce
Please see https://gist.github.com/lsierant/ad4169675b0e6ee9697d1b37333f504d for all steps to reproduce with debug output.

Steps: 
1. Have an existing backend (local or remote) configured locally, with existing state. 
2. Change backend configuration in any way. This could be changed remote bucket or path to a local state in config file or by `-backend-config=`
3. Run `terraform init`. Terraform will ask for confirmation whether to copy existing state to the new backend.
4. Do not answer, but interrupt (^C). Alternatively there could be a problem locking the remote state. Effect will be the same - interrupted init.
5. Run `terraform init` again. It thinks backend was not changed (hashes are equal) and initialises cleanly but uses old backend config!

### Additional Context
This behaviour was caught when I had one environment configured and changed remote bucket along with some env config in order to create a completely new environment. I forgot about existing state and was surprised when terraform init informed me about existing state, so I ^C'd instinctively to find out what happened. After that I have run terraform init which finished cleanly without warning. After that running terraform plan resulted in replacing all infra in old backend, despite having new backend bucket in config. 
When preparing this test case I found out that any interruption will cause this behaviour, i.e. network issues or problems with acquiring a lock. 

### References
#13165 - introduced this early hash change
#26260 - I have prepared a failing test case showing this problem as a draft PR

**Comment by alisdair** [comment]
Thanks for reporting this, @lsierant! I'm able to confirm this with Terraform 0.13.3, using the folllowing steps:

1. Create this main.tf:

    ```hcl
    terraform {
      backend "local" {
        path = "./a.tfstate"
      }
    }

    resource "null_resource" "none" {}
    ```
1. `terraform init` and `terraform apply -auto-approve`
1. Change the backend configuration to `path = "./b.tfstate"` and remove the resource
1. Run `terraform init` and hit ctrl-C
1. Run `terraform init` again and it "succeeds" without confirmation
1. Run `terraform apply -auto-approve` and the resource will be deleted from `a.tfstate`

As you found yourself, the issue looks like it is in the backend hash being updated too early/incorrectly. This is the same underlying issue as #23093. Unfortunately this area of code is very tricky to think through, so I don't have a clear solution at this time. Your failing test in #26260 is a great place to start for whoever picks this up next.
