### ISSUE TITLE
Crash when using Destroy

### ISSUE THREAD

**Issue by LunaticZorr** [hashicorp/terraform#26281]
### Terraform Version

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.6.0
```

### Terraform Configuration Files

`versions.tf`
```terraform
terraform {
  required_version = ">= 0.13"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.6.0"
    }
  }
}
```

`provider.tf`
```terraform
terraform {
  required_version = ">= 0.13"
}

provider "aws" {
  version                 = "~> 3.6.0"
  region                  = "eu-west-2"
  shared_credentials_file = "~/.aws/credentials"
}
```

`.terraform/modules/vpc/versions.tf`
```terraform
terraform {
  required_version = ">= 0.12.7, < 0.14"

  required_providers {
    aws = ">= 2.68, < 4.0"
  }
}
```

### Crash Output

No error throughout the whole process, until it suddenly crashes with the following error

```
Error: fork/exec .terraform/plugins/registry.terraform.io/hashicorp/aws/3.6.0/linux_amd64/terraform-provider-aws_v3.6.0_x5: permission denied
```

And shows this at the end of the Debug log:
```
-----------------------------------------------------
2020/09/17 14:24:08 [DEBUG] [aws-sdk-go] 
2020-09-17T14:24:08.163+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-09-17T14:24:08.168+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/aws/3.6.0/linux_amd64/terraform-provider-aws_v3.6.0_x5 pid=6725
2020-09-17T14:24:08.168+0100 [DEBUG] plugin: plugin exited
```

### Expected Behavior
I would expect it to go through the process just like when running PLAN or APPLY, and in this case, destroy all the resources.

### Actual Behavior
It crashes and doesn't destroy any resource.

### Steps to Reproduce
```bash
terraform destroy -var-file="environment/mvrv3-dev/terraform.tfvars" --force
```

### References
Same debug message in the following issue:
- #22349

**Comment by alisdair** [comment]
Thanks for reporting this, @LunaticZorr. That's a strange error.

Seeing "permission denied" seems to indicate that the provider plugin may not have the correct file permissions. Assuming you're on a UNIX-like environment, what is the output of `ls -lR .terraform/plugins`?

If the permissions are wrong, this would seem like an issue outside of Terraform's control. `terraform init` ensures that the permissions are correct on install, so if some external process is changing that, there's not much we can do. You might try removing the `.terraform` directory and rerunning `init` to see if it fixes the problem.

If you can post the full debug logs (removing any secrets) that might be helpful too.

**Comment by alisdair** [comment]
Thanks! I'm still not able to reproduce this error, and your file permissions seem like they should not be the problem.

A similar issue from the past is #15909, where the underlying cause was the execution environment in which Terraform was run preventing fork from succeeding. Perhaps that's the issue here.

Some more questions:

- Can you say more about how you're using Terraform? Is it directly on a Linux host, or in a VM, or a Docker container?
- Does the error occur with all Terraform configurations, or just one? If it's configuration related, can you share the Terraform configuration?
- You mentioned that `init` and `plan` are fine, but `destroy` fails. Does `terraform apply` work?

Thanks for investigating this with us!

**Comment by LunaticZorr** [comment]
> 
> 
> Thanks! I'm still not able to reproduce this error, and your file permissions seem like they should not be the problem.
> 
> A similar issue from the past is #15909, where the underlying cause was the execution environment in which Terraform was run preventing fork from succeeding. Perhaps that's the issue here.
> 
> Some more questions:
> 
>     * Can you say more about how you're using Terraform? Is it directly on a Linux host, or in a VM, or a Docker container?
> 
>     * Does the error occur with all Terraform configurations, or just one? If it's configuration related, can you share the Terraform configuration?
> 
>     * You mentioned that `init` and `plan` are fine, but `destroy` fails. Does `terraform apply` work?
> 
> 
> Thanks for investigating this with us!

Thanks for the response Alisdair.

Responding to your questions:

* My Linux machine is a VM running on Virtualbox.
* This is the only configuration I currently have and am running, so can't test with any other.
* Terraform `apply` works too, I did run that before the destroy and all resources were created in AWS correctly. Now I need/want to destroy them again and that is failing 😓 

Kind Regards,
Kevin

**Comment by alisdair** [comment]
Can you try the following simple configuration on your host?

```hcl
resource "null_resource" "none" {}
```

Please `init`, `apply`, and `destroy` with this configuration. This works for me with Terraform 0.13.3 on VirtualBox 6.1.12 on a macOS host with Ubuntu Server 20.04.1.

If that works, please try to create as simple a configuration as possible which does fail, so that we can try to reproduce the issue.

**Comment by LunaticZorr** [comment]
> 
> 
> Can you try the following simple configuration on your host?
> 
> ```terraform
> resource "null_resource" "none" {}
> ```
> 
> Please `init`, `apply`, and `destroy` with this configuration. This works for me with Terraform 0.13.3 on VirtualBox 6.1.12 on a macOS host with Ubuntu Server 20.04.1.
> 
> If that works, please try to create as simple a configuration as possible which does fail, so that we can try to reproduce the issue.

Hello Alisdair,

I wasn't able to test this configuration, but it seems the issue was related to having the repository on my VM shared with windows.

So I had a shared folder between my Windows and my Linux VM and in that folder the repository for my Terraform configuration. It seems Windows was modifying the permissions or something and causing it to fail.
I cloned the repo into `/tmp/` and tested and could run the destroy fine from there.
Kinda weird because it did work in the past, not sure what happened. But knowing that I just need to clone into a non-shared folder works for me.

Kind Regards,
Kevin.
