### ISSUE TITLE
Hide CloudFormation template sensitive parameters

### ISSUE THREAD

**Issue by BartekChojnacki** [hashicorp/terraform#26288]
Hello,

When I want to run cloudformation stack from Terraform and this stack has sensitive parameters, which are set up in cloudformation template as ( SecretString: Type: 'String' NoEcho: true ) there are no possibility to make sensitive section parameters = {} / parameter_overrides = { } and all sensitive parameters are visible in terraform plan.

### Current Terraform Version
```
Terraform v0.13.0
+ provider registry.terraform.io/-/aws v3.7.0
+ provider registry.terraform.io/-/template v2.1.2
+ provider registry.terraform.io/hashicorp/aws v3.7.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
```

### Use-cases

` # module.iam_module.aws_cloudformation_stack_set_instance.smsminstance["aws-network-non-prod"] will be updated in-place
  ~ resource "aws_cloudformation_stack_set_instance" "examample_instance" {
        account_id          = "example_account"
        id                  = "tfe-stackset-sm-deployer,016091306659,eu-west-1"
      ~ parameter_overrides = {
          ~ "SecretString" = "****" -> jsonencode(
                {
                  + SECRET_KEY = "SECRET_KEY_VALUE"
`

### Proposal

There should be an option to make parameters {} section for resource "aws_cloudformation_stack_set" and  parameter_overrides = {} for resource "aws_cloudformation_stack_set_instance" sensitive, and hide it on the plan if it is needed. Especially when the input parameters of the cloudformation template are sensitive.

**Comment by pkolyvas** [comment]
Thanks @BartekChojnacki for your submission. With the inclusion of `sensitive` input variables and the ability to better handle attributes which provider schemas mark as sensitive in `0.14` (see [here](https://discuss.hashicorp.com/t/terraform-0-14-beta1-available)), I'm going to hand this off to the AWS Provider team in the case this is something they can help with.
