### ISSUE TITLE
Extra connection attributes for DMS S3 Endpoints incomplete --> no error is shown

### ISSUE THREAD

**Issue by Olgoetz** [hashicorp/terraform#26296]
### Terraform Version

```
Terraform v0.13.2
```

### Terraform Configuration Files

```terraform
resource "aws_dms_endpoint" "s3_endpoint" {

  count                       = length(var.zones)
  endpoint_id                 = "${var.s3_endpoint_id_prefix}-${var.environment}-${var.shortApp}-${var.zones[count.index]}"
  endpoint_type               = "target"
  engine_name                 = "s3"
  ssl_mode                    = "none"
  kms_key_arn = var.kms_key_arn
extra_connection_attributes = "ServiceAccessRoleArn=${var.service_access_role_arn};bucketFolder=${var.zones[count.index]}/dms-export/${var.shortApp};bucketName=${var.bucket_name};cannedAclForObjects=BUCKET_OWNER_FULL_CONTROL;cdcPath=undefined;compressionType=NONE;csvDelimiter=,;csvRowDelimiter=\n;dataFormat=csv;datePartitionEnabled=false;includeOpForFullLoad=true;timestampColumnName=CDCTIMESTAMP"
  
  
  s3_settings {
    bucket_folder           = "${var.zones[count.index]}/dms-export/${var.shortApp}"
    bucket_name             = var.bucket_name
    service_access_role_arn = var.service_access_role_arn

  }

  tags = merge(var.tags, { "global.project" = "${local.global_project_tag}" })

}
...
```

### Debug Output

https://gist.github.com/Olgoetz/9e7aec3af0af47b347822f20d0ce6b47

### Expected Behavior

The extra connection attributes should look like:

ServiceAccessRoleArn=arn:aws:iam::*******:role/SDP_DMS_MIGRATION_TO_S3_ROLE;bucketFolder=komo/dms-export/pc;bucketName=*****-nonprod-sdp-lz-stag-pnc;cannedAclForObjects=BUCKET_OWNER_FULL_CONTROL;cdcPath=undefined;compressionType=NONE;csvDelimiter=,;csvRowDelimiter=\n;dataFormat=csv;datePartitionEnabled=false;includeOpForFullLoad=true;timestampColumnName=CDCTIMESTAMP

### Actual Behavior

When I go to the endpoint in the AWS management console, these are the settings in extra connection attributes:

bucketFolder=komo/dms-export/pc;bucketName=axade-nonprod-sdp-lz-stag-pnc;compressionType=NONE;csvDelimiter=,;csvRowDelimiter=\n;datePartitionEnabled=false;

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

No.

**Comment by alisdair** [comment]
Thanks for reporting this! I believe this is a bug in the AWS provider: https://github.com/terraform-providers/terraform-provider-aws/issues/8009. Closing this issue as it is not on Terraform core.
