### ISSUE TITLE
gitub issue while executing the terraform modules 

### ISSUE THREAD

**Issue by kkantedi** [hashicorp/terraform#26310]
Error: Error applying plan:

1 error occurred:
        * module.rundeck.module.elb-http-redirect.aws_elb.masters-elb: aws_elb.masters-elb: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.14
    Resource ID: aws_elb.masters-elb
    Mismatch reason: attribute mismatch: listener.408756206.instance_port

**Comment by jbardin** [comment]
Hello!

Thanks for reporting this issue. Unfortunately the error output in this "diffs didn't match" situation is often not enough to diagnose the problem. Starting in 0.12 the situation that causes this error is more precisely reported, and the necessary debugging information is recorded in the logs. If this issue persists after upgrading Terraform, please file an issue with the referenced provider.

Thanks
