### ISSUE TITLE
AWS autoscaling group names should be able to be autogenerated

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#2632]
Currently name is required and must be unique within the region/account.

**Comment by ericfode** [comment]
:+1:

**Comment by radeksimko** [comment]
I'm :+1: on this, but I would wait with implementation until https://github.com/hashicorp/terraform/pull/2571 gets reviewed & merged, so we have the prefixed-unique-ID functionality in core and we can use it here too.

**Comment by jszwedko** [comment]
@radeksimko :+1: :+1:

**Comment by stack72** [comment]
@radeksimko #2571 is now merged so I think this one can be closed now - is this correct?

**Comment by radeksimko** [comment]
@stack72 The function for generating unique names is merged, but ASGs still have `name` `Required: true`:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_autoscaling_group.go#L28

**Comment by stack72** [comment]
ok, I opened the PR that allows this to work now :) Thanks for the hints @radeksimko

**Comment by catsby** [comment]
I merged #3710 , completing this. Thanks all!
