### ISSUE TITLE
No way to see all modules by the user in Terraform Registry

### ISSUE THREAD

**Issue by antonbabenko** [hashicorp/terraform#26324]
"View more" link after 6 modules does not show more modules by this user. Eg: https://registry.terraform.io/namespaces/terraform-aws-modules

Currently, I don't know how to see all modules by the user.

**Comment by alisdair** [comment]
@antonbabenko Thanks for reporting this. I'm not able to reproduce the problem. Clicking "View more" takes me to this page, which shows all 30 modules: https://registry.terraform.io/search/modules?namespace=terraform-aws-modules

What happens for you?

**Comment by antonbabenko** [comment]
Now I can see that it works correctly. At the time when I opened this issue the "View more" was linking to https://registry.terraform.io/search/modules which shows all modules.

Probably it was some sort of front-end bug.

Closing now.
