### ISSUE TITLE
Terraform taint does not respect required_version

### ISSUE THREAD

**Issue by stellirin** [hashicorp/terraform#26325]
### Terraform Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/google v3.39.0
+ provider registry.terraform.io/hashicorp/google-beta v3.39.0
+ provider registry.terraform.io/hashicorp/http v1.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.14.0
```

### Terraform Configuration Files

```terraform
N/A
```

### Debug Output

N/A
### Crash Output

N/A
### Expected Behaviour

`terraform taint my.special.resource` should respect the `required_version` in `versions.tf` and not proceed if there is a mismatch, similar to `terraform apply`.
### Actual Behaviour

We have `required_version = "0.13.2"` set, but Terraform v0.13.3 happily tainted the state and set a new minimal version in the state.
### Steps to Reproduce

Run `terraform taint my.special.resource` with v0.13.3 on a state file from v0.13.2.
### Additional Context

We use Homebrew as a makeshift package manager due to inadequacies in macOS. It is easy to 'accidentally' upgrade packages with no easy way to roll back to an older version when the upgrade is discovered. Therefore we set a fixed Terraform version to prevent accidental upgrades of the state file.

Terraform was upgraded on my machine. `terraform taint` was able to taint my state file without issue. The subsequent `terraform apply` immediately failed because the Terraform version did not match the value in `required_version`. After downgrading, `terraform apply` failed again because the state file was set with a higher Terraform version.

**Comment by alisdair** [comment]
Thanks for reporting this, @stellirin! I've confirmed the bug exists on 0.13 and 0.14.
