### ISSUE TITLE
device_name now required on root_block_device of AWS_LAUNCH_CONFIGURATION

### ISSUE THREAD

**Issue by jjshoe** [hashicorp/terraform#2633]
Pre 0.6.0 I had the following in terraform

```
resource "aws_launch_configuration" "service_launch_configuration" {
    name = "${var.service_name}-1.0.1-lc"
    image_id = "${var.service_ami}"
    instance_type = "m3.medium"
    iam_instance_profile = ""
    key_name = "ami-key-pair"
    security_groups = ["${aws_vpc.env_vpc.default_security_group_id}"]
    associate_public_ip_address = true

    root_block_device {
        volume_type = "gp2"
        volume_size = "64"
    }
}

```

Now in 0.6.0 I get the following error:
```
* Error creating launch configuration: InvalidParameter: 1 validation errors:
- missing required parameter: BlockDeviceMappings[0].DeviceName
```

The docs at https://terraform.io/docs/providers/aws/r/launch_configuration.html don't indicate this as a new requirement?

**Comment by jjshoe** [comment]
Root cause: variable in EOF block.

**Comment by catsby** [comment]
Hey @jjshoe – Sorry for the trouble here! According to the [AWS documentation][1], the `device_name` is indeed a required field. I've updated our documentation in #2635 to reflect this.

Thanks for writing in and pointing this out, sorry for any frustration 

[1]: http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_BlockDeviceMapping.html

**Comment by jjshoe** [comment]
@catsby - It's not a doc issue:

Errors:

  * aws_launch_configuration.service_launch_configuration: root_block_device.0: invalid or unknown key: device_name

**Comment by jjshoe** [comment]
```
<phinze> Joel: yep - added some robustness around AMIs where RootDeviceName is not present in the list of BlockDeviceMappings - i think it might have regressed launch configs. will dig in soon
```

**Comment by jjshoe** [comment]
Note: NoDevice option for the root device at your own documentation link.

**Comment by jjshoe** [comment]
@phinze feel free to chime in here please.

**Comment by catsby** [comment]
Ah, my mistake @jjshoe I was looking at the EBS volumes. 

Looks like we're looking that device name up from the source AMI:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L720

Going to chat with @phinze

**Comment by jjshoe** [comment]
@catsby probably worth re-opening this and changing labels?

**Comment by jjshoe** [comment]
Root cause: non-existant AMI ID. The error message is a giant red hearing, and should be updated.

**Comment by catsby** [comment]
@jjshoe this should be patched with https://github.com/hashicorp/terraform/pull/2646
