### ISSUE TITLE
Combine 2 lists to create multiple resources

### ISSUE THREAD

**Issue by eladazary** [hashicorp/terraform#26335]
### Description

Hi,

In order to create multiple CloudFront distros in aws I need to use the following details:
I have a list of prefixes (api1, api2, api3), and I have several domains (example1.com, example2.com) - I counted the prefixes and the domains by different amounts on purpose.

To do so I thought I might need to use dynamic blocks this way:
  certificates = [
    {
      domain = ["example1.com", "example2.com"]
      prefix = ["api1", "api2", "api3"]
}
and then configure the resource with 2 dynamic blocks (One for each list) but it seems like it's not the way I need to implement it as the variable in the content section shouldn't be a list..

Hope you guys can help me with a hint.

### Terraform Version
```
0.13

```

### Expected Behavior
The expected behavior should be a CloudFront distro for every mix:
api1.example1.com
api2.example1.com
api3.example1.com
api1.example2.com
etc.

**Comment by alisdair** [comment]
Hi @eladazary. You don't appear to be reporting a bug here, and this is not a great place to ask for help. I think you might find more luck if you [post on the Terraform discussion forum](https://discuss.hashicorp.com/c/terraform-core/27).
