### ISSUE TITLE
Incorrect subscription id resollution for terraform apply

### ISSUE THREAD

**Issue by Ramutis** [hashicorp/terraform#26341]
### Terraform Version

``` 
Terraform v0.13.3+ provider registry.terraform.io/hashicorp/azurerm v2.25.0
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Azure alert rule should be created in multiple subscriptions. All required variables are stored in csv file.
for alert rule creation used resource "azurerm_monitor_scheduled_query_rules_alert"

### Actual Behavior

terraform plan shows correct subscriptions where rule should be created, after terraform apply get message that alert rule exists and can't be created, but this alert rule exists in different subscription which it's not in scope

### Steps to Reproduce

terraform apply

### Additional Context

Some warnings found in debug log:
2020/09/23 01:36:37 [WARN] Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_monitor_scheduled_query_rules_alert.main["2"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .location: planned value cty.StringVal("westeurope") does not match config value cty.StringVal("West Europe")
      - .query_type: planned value cty.StringVal("ResultCount") does not match config value cty.NullVal(cty.String)
2020/09/23 01:36:37 [WARN] Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_monitor_scheduled_query_rules_alert.main["1"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .query_type: planned value cty.StringVal("ResultCount") does not match config value cty.NullVal(cty.String)
      - .location: planned value cty.StringVal("eastus") does not match config value cty.StringVal("East US")

Interesting entry in debug log

2020-09-23T01:51:37.409+0300 [DEBUG] plugin.terraform-provider-azurerm_v2.25.0_x5.exe: GET /subscriptions/629f9ad3-

Subscription 629f9ad3- nowhere listed or hardcoded. There is the issue, somehow plugin gets this subscription processing.

**Comment by danieldreier** [comment]
@Ramutis our GitHub bot that automatically migrates issues isn't working, so this didn't get moved automatically, but this is an AzureRM issue rather than a Terraform Core issue. This GitHub repository is for issues in Terraform Core, and this needs to be reported directly to the AzureRM folks at https://github.com/terraform-providers/terraform-provider-azurerm. I'm going to close this, and your next step is to re-open it with that team. Thank you for reporting this!
