### ISSUE TITLE
Destroying a group of resources based on the name of a .tf file.

### ISSUE THREAD

**Issue by samispurs** [hashicorp/terraform#26352]
### Proposal
If I had a group of .tf files with resources defined in them. e.g
network.tf
s3.tf
db.tf

But wanted to delete all the resources in network.tf but keep the s3.tf and db.tf resources.

would like to see something like terraform destroy -file network.tf to remove only the resources defined in network.tf

**Comment by pkolyvas** [comment]
Thanks for enhancement request @samispurs 

Terraform's design does not lend itself to using file names for infra decomposition in a way that Terraform itself "understands".  I think, personally, I'd advise against leaning on filenames for anything other than organization, especially where there may be other options. 

In your specific case, I'd recommend modularizing your configuration. Then you can begin experimenting with targeted destruction of those modules. You could then have modules named as you have them above (`s3`, `db`, etc.) each containing a set of resources that can be destroyed, in a targeted fashion, as needed. The added advantage is that each module could be placed in a subdirectory matching your filenames, allowing you to continue to organize your configurations as is most helpful to you.

Targeting should be a good start: https://www.terraform.io/docs/commands/plan.html#resource-targeting

Join us over at our [community forums](https://discuss.hashicorp.com/c/terraform-core/27) and I'm sure a number of other practitioners can help share their strategies for decomposing their infrastructure in a way that helps get you what you need for your workflow/use case.
