### ISSUE TITLE
Unable to fix erroneous provider reference without rolling back state

### ISSUE THREAD

**Issue by bleachbyte** [hashicorp/terraform#26368]
### Terraform Version
```
terraform --version
Terraform v0.13.2
```

### Terraform Configuration Files
```terraform
terraform {
  backend "s3" {}
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 2.67.0"
    }
    external = {
      source = "hashicorp/external"
      version = "~> 1.2.0"
    }
    github = {
      source = "hashicorp/github"
      version = "~> 2.9"
    }
    null = {
      source = "hashicorp/null"
      version = "~> 2.1.2"
    }
    template = {
      source = "hashicorp/template"
      version = "~> 2.1.2"
    }
  }
  required_version = ">= 0.13"
}
```

### Debug Output
Trace log when first running `state replace-provider -- -/newrelic registry.terraform.io/hashicorp/newrelic`:
https://gist.github.com/bleachbyte/d20c44367206619017318681a634c99a

Trace log when attempting to run `state replace-provider -- hashicorp/newrelic registry.terraform.io/newrelic/newrelic`, or any other command including `0.13upgrade`:
https://gist.github.com/bleachbyte/fb10a4f6ee42aee1634096529e28fcc2

### Expected Behavior
Through either `state replace-provider` or a similar command like `0.13upgrade`, Terraform should:
1) observe that `hashicorp/newrelic` is invalid
2) suggest the alternative `newrelic/newrelic`
3) accept the `state replace-provider` command to do so and/or suggest running `0.13upgrade` which should prompt to do this anyway

### Actual Behavior
Error message:
```
Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/newrelic -> newrelic/newrelic

If these suggestions look correct, upgrade your configuration with the
following command:

```
No command is provided (despite the last sentence), state file is not updated, and provider is not fixed/replaced. As a result, no Terraform operations can be run, as it errors out and exits any time it attempts to load the erroneous entry `hashicorp/newrelic`.

Thus far, the only way to correct this has been to roll back to a previous version of the state file, correcting the manifest ID in DynamoDB when doing so, and then running `state replace-provider` with the correct replacement value of `newrelic/newrelic` instead.

### Steps to Reproduce
1. `terraform state replace-provider -- -/newrelic registry.terraform.io/hashicorp/newrelic`
2. Any Terraform command, including any of the following:
```
terraform state replace-provider -- hashicorp/newrelic registry.terraform.io/newrelic/newrelic
terraform state replace-provider -- -/newrelic registry.terraform.io/newrelic/newrelic
terraform state replace-provider -- hashicorp/newrelic newrelic/newrelic
[...etc....]
```

### Additional Context
This is run in a wrapper script which serves to verify the Terraform version, AWS account ID, and existence of the S3 bucket/DynamoDB for storing the remote state; this results in the following example `init` command:

```
terraform init -backend-config=bucket=redacted-s3-bucket-name -backend-config=key=terraform-app/terraform-testenv.tfstate -backend-config=dynamodb_table=terraform_locks -backend-config=region=us-west-2
```

All of our code has been migrated to Terraform 13, using the new `required_providers` format. In other environments, the `newrelic/newrelic` provider was replaced correctly, so this error does not occur, and all legacy style `-/PROVIDER` entries in state have been migrated.

THIS error came up as the result of using a `for` loop to replace all `-/${PROVIDER}` entries with `registry.terraform.io/hashicorp/${PROVIDER}`. As noted, once this provider is replaced with this erroneous entry, Terraform gets hung up on being unable to find it, and refuses to run past its `Initializing provider plugins` stage.

### References
#25995 appears to be the closest issue I could find to the one I've encountered here.

**Comment by apparentlymart** [comment]
Hi @bleachbyte! Thanks for reporting this, and sorry for the odd behavior.

I think you may have ended up in a situation that the upgrade process doesn't anticipate: your initial attempt to use `terraform state replace-provider` has rewritten the "legacy" provider addresses in the state to be new-style references to the non-existent provider `hashicorp/newrelic`, and so now Terraform doesn't understand how to proceed because the entries in the state are not in the legacy syntax and thus it seems like your upgrade is already complete.

In order to understand better how things sit in your system right now, could you run `terraform providers` and share the output? That command should print out which providers Terraform has found in the configuration and in the state, and so hopefully give a better idea of where exactly this `hashicorp/newrelic` reference is being tracked and get a clue as to what steps might work to correct it.

**Comment by bleachbyte** [comment]
Negative -- as mentioned, **_no_** Terraform commands work once the legacy provider has been pointed to the erroneous address:

```
+ terraform --version
+ terraform init -backend-config=bucket=redacted-s3-bucket-name -backend-config=key=terraform-app/terraform-testenv.tfstate -backend-config=dynamodb_table=terraform_locks -backend-config=region=us-west-2
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/github v2.9.2
- Using previously-installed hashicorp/null v2.1.2
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed hashicorp/external v1.2.0
- Using previously-installed hashicorp/aws v2.67.0
- Using previously-installed newrelic/newrelic v2.1.2
- Finding latest version of hashicorp/newrelic...

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/newrelic -> newrelic/newrelic

If these suggestions look correct, upgrade your configuration with the
following command:

```

**Comment by bleachbyte** [comment]
According to that command, it's _only_ in the state, and not in the config. Here's a truncated version of the output (in the interest of keeping some config info private):

```
Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/template] ~> 2.1.2
├── provider[registry.terraform.io/hashicorp/aws] ~> 2.67.0
├── provider[registry.terraform.io/hashicorp/external] ~> 1.2.0
├── provider[registry.terraform.io/hashicorp/github] ~> 2.9
├── provider[registry.terraform.io/hashicorp/null] ~> 2.1.2
├── module.ZZZ_lifecycle_hooks
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.rds_dashboard_XXX
│   └── provider[registry.terraform.io/hashicorp/aws]
...
├── module.newrelic
│   ├── provider[registry.terraform.io/newrelic/newrelic] ~> 2.1.2
│   └── provider[registry.terraform.io/hashicorp/aws]
...
Providers required by state:

    provider[registry.terraform.io/hashicorp/newrelic]

    provider[registry.terraform.io/-/aws]

    provider[registry.terraform.io/-/external]

    provider[registry.terraform.io/-/github]

    provider[registry.terraform.io/-/null]

    provider[registry.terraform.io/-/template]
```

**Comment by apparentlymart** [comment]
Thanks for that extra information, @bleachbyte.

Given that the incorrect reference exists only in the state, I think the most important question here is why a command like the following wasn't able to repair it:

```
terraform state replace-provider -- hashicorp/newrelic newrelic/newrelic
```

Based on the output you shared from your attempt to run this command, it seems like the error you saw was from running `terraform init` rather than from the `terraform state replace-provider` command itself. By the time Terraform is trying to install providers there it should already have initialized the backend enough that the `terraform state replace-provider` command ought to work, even though the provider installation failed.

Could you try running the command above after you see `terraform init` fail, and see if it correctly plans to switch the references in the state? If it's able to make that change correctly then I would expect a subsequent `terraform init` to then work successfully.

(This does still leave the question of why `terraform init` didn't propose the above command itself as part of its output, but let's come back to that after we see if we can address your direct blocker.)

**Comment by bleachbyte** [comment]
That did the trick -- sort of. Details:

I ran our wrapper script, which runs the `terraform init` block above; it initialized, but then got stuck on the provider, as before:

```
Initializing modules...

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Using previously-installed hashicorp/template v2.1.2
- Using previously-installed hashicorp/github v2.9.2
- Using previously-installed hashicorp/null v2.1.2
- Using previously-installed newrelic/newrelic v2.1.2
- Using previously-installed hashicorp/aws v2.67.0
- Using previously-installed hashicorp/external v1.2.0
- Finding latest version of -/null...
- Finding latest version of -/aws...
- Finding latest version of -/github...
- Finding latest version of -/template...
- Finding latest version of hashicorp/newrelic...
- Finding latest version of -/external...
- Using -/null v2.1.2 from the shared cache directory
- Using -/aws v3.8.0 from the shared cache directory
- Using -/github v3.0.0 from the shared cache directory
- Using -/template v2.1.2 from the shared cache directory
- Using -/external v1.2.0 from the shared cache directory

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/newrelic -> newrelic/newrelic

If these suggestions look correct, upgrade your configuration with the
following command:

```

However, since at THAT point the `init` configuration was still present in the local cache, I was able to run `replace-provider` successfully:

```
$ terraform state replace-provider -- hashicorp/newrelic newrelic/newrelic

Terraform will perform the following actions:

  ~ Updating provider:
    - registry.terraform.io/hashicorp/newrelic
    + registry.terraform.io/newrelic/newrelic

Changing 14 resources:
[...deletia...]
```

I think this problem is more related to our wrapper script running `terraform init` each time it runs, which I believe it does to make sure that our local caches and the backend state aren't out of sync/populated with incorrect data. I can see about adding a flag to our wrapper in case `init` is broken like this.
