### ISSUE TITLE
Allow aliasing of state items for easier and safer state moves

### ISSUE THREAD

**Issue by Raynor33** [hashicorp/terraform#26388]
### Use-cases
My team has found that refactoring terraform can often require state moves, for example when resources that can't be destroyed and recreated need to be renamed or moved into/out of modules.

State moves and the code changes that they reflect happen outside of the normal locking mechanism of terraform and therefore are risky when other users/pipelines may be applying changes, as this could lead to the accidental deletion of resources when the code does not match the state.

The coordination of state moves and code changes is difficult to automate and roll out across environments.

### Proposal
Adding the ability to alias paths in terraform state, so that state can either be picked up from the old location and migrated to the new automatically during a `terraform apply`, or picked up from the new location, might solve the issues described above.

The migration of state would take place while the lock was held to avoid dangerous situations where state moves and deployments of new/old code happen in the wrong order.

The state move would be defined entirely in code and would not need to be applied manually/automated through some other mechanism, reducing the risk of manual error.

After all state is migrated to the new location, the alias could be removed as the new location defined in the code would match the state.

Example syntax:
```
resource "new" "location" {
  state_alias = "old.location"
}
```

**Comment by nikolay** [comment]
This is a workaround, which requires multiple commits and applies. Instead, you can use `terraform state mv`

**Comment by Raynor33** [comment]
I agree, it would require multiple commits, normally 2 I think.

However, we feel that would be preferable to the risks mentioned above with using `terraform state mv` (which is what we currently do use), as the state moves would then be defined in code and therefore more repeatable when rolled out across different environments, and could all take place while the lock was held.

**Comment by apparentlymart** [comment]
Hi @Raynor33! Thanks for sharing this feature request.

I think this request is describing the same use-case that motivates #9048, so I'm going to close this one to consolidate the discussion there. I think the discussion there already covers the use-case you've described, but if you disagree then please do feel free to add a new comment with the "use-cases" portion of your issue here, for easier future reference.
