### ISSUE TITLE
Cannot provision more than 10 EC2 instances concurrently

### ISSUE THREAD

**Issue by IvanTing** [hashicorp/terraform#2639]
Here is my case.
I have to launch e.g. 11 EC2 instances.
Then, use file provisioner to upload files to all EC2 instances. Need to ensure all files are uploaded to all instances before go to next steps as there is dependency.
Next, run remote-exec provisioner on all instances.

The issue is that terraform only create and provision 10 instances at the same time. The 11th instance will be started to create only if any instance of first 10 instances is done (may be created successfully or with error).
So, in my case, the first 10 instances keep waiting for all files uploaded to all (11) instances but the 11th instance has not created yet until if there is an instance of the first 10 instances done.

I expect Terraform can create and provision more than 10 EC2 instances concurrently.

Setup:
* Used Terraform v0.5.3 and 0.6.0
* Below is sample main.tf to create 11 EC2 instances to illustrate that the 11th instance will only create if any one instance of first 10 instances finishes the creation (after the "sleep 30" local-exec at the end done).

```
provider "aws" {
    access_key = "<Access Key>"
    secret_key = "<Secret Key>"
    region = "us-west-1"
}

resource "aws_vpc" "main" {
    cidr_block = "10.0.10.0/24"
    tags {
        Name = "Scale VPC"
    }
}

resource "aws_subnet" "main" {
    vpc_id = "${aws_vpc.main.id}"
    cidr_block = "10.0.10.0/24"
    tags {
        Name = "Scale VPC Subnet"
    }
}

resource "aws_internet_gateway" "gw" {
    vpc_id = "${aws_vpc.main.id}"
    tags {
        Name = "Scale VPC Internet GW"
    }
}

resource "aws_route_table" "r" {
    vpc_id = "${aws_vpc.main.id}"
    route {
        cidr_block = "0.0.0.0/0"
        gateway_id = "${aws_internet_gateway.gw.id}"
    }
}

resource "aws_route_table_association" "a" {
    subnet_id = "${aws_subnet.main.id}"
    route_table_id = "${aws_route_table.r.id}"
}

resource "aws_eip" "public" {
   vpc = true
}

resource "aws_security_group" "default" {
    name = "VPC Security Group"
    description = "VPC Security Group"
    vpc_id = "${aws_vpc.main.id}"

    tags {
        Name = "Sacle VPC Secutiry Group"
    }

    ingress {
        from_port = 22
        to_port = 22
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }

    ingress {
        from_port = 80
        to_port = 80
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }

    ingress {
        from_port = 443
        to_port = 443
        protocol = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }

    egress {
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = ["0.0.0.0/0"]
    }
}

resource "aws_instance" "ec2_node" {
  count = "11"
  connection {
    user = "centos"
    key_file = "<Key File>"
  }

  instance_type = "m3.large"
  ami = "ami-6bcfc42e"
  key_name = "<Key Name>"
  security_groups = ["${aws_security_group.default.id}"]
  subnet_id = "${aws_subnet.main.id}"
  associate_public_ip_address = true
  root_block_device {
    volume_size = 20
  }

  tags {
      Name = "${format("ec2-%02d", count.index+1)}"
  }

  depends_on = ["aws_internet_gateway.gw"]

    # Dummy remote-exec to make ssh connection to EC2 instances
    provisioner "remote-exec" {
       inline = [
           "ls -la /tmp"
        ]
    }

    provisioner "local-exec" {
        command = "sleep 30"
    }
}
```

**Comment by IvanTing** [comment]
According to the code https://github.com/hashicorp/terraform/blob/ed115f495b6f674f3cc0276c82411ce512976be7/terraform/context.go#L86-L92, the parallelism is hardcoded to handle a default of 10 resources.
And I have searched if any configuration can override this value but no. 

May make this parallelism setting exposed to user?

**Comment by radeksimko** [comment]
@IvanTing See https://github.com/hashicorp/terraform/pull/1834 - when that's finished, would it be sufficient for you?

**Comment by IvanTing** [comment]
@radeksimko, thanks for reply.

The feature in #1834 looks good and is something what I need.
However, in my case, I need to launch large number of EC2 instances at the same time, at least 11 and up to 21 EC2 instances. While the use cases in #1834 seem target to limit the parallelism to small number. 
So, my concern is that if I provide -parallelism=21, could terraform create and provision all EC2 instances at the same time properly.

In addition, it would be great if can keep the terraform command simple like "terraform apply" instead of "terraform apply -parallelism=21". In my case, I will use terraform.tfvars as single point to let other user to provide the required values for deployment at AWS. And in my terraform.tfvars, user will provide node_num value (already defined 'node_num' as variable in variable.tf) and then this value will pass to "count" parameter of aws_instance resource in main.tf. So, if the parallelism setting can be embedded in e.g. main.tf, then I can also pass the node_num to the parallelism setting such that I don't need to provide -parallelism in CLI again.

**Comment by phinze** [comment]
We now support `-parallelism` as a flag. :+1:

As for the use case of commonly needing to spin up groups of EC2 instances concurrently, I'd recommend looking into ASGs and user_data to handle booting and provisioning, respectively.
