### ISSUE TITLE
Terraform Cloud: workspace deletion confirmation is ineffective

### ISSUE THREAD

**Issue by lewispeckover** [hashicorp/terraform#26392]
### Description
The workspace deletion confirmation screen on app.terraform.io supposedly requires entry of the correct workspace name to confirm deletion, but hitting enter with anything (or nothing) entered deletes the workspace anyway.

### Terraform Version

```
Terraform Cloud
```

### Steps to Reproduce

- Create a workspace
- Go to the workspace Settings > Destruction & Deletion
- Click the Delete from Terraform Cloud button, and at the confirmation prompt, enter any random text (or nothing at all)
- Hit enter

### Expected Behavior

Nothing should have happened as the correct workspace name was not entered.

### Actual Behavior

The workspace was deleted.

**Comment by danieldreier** [comment]
Thanks for reporting this! I think that this is an issue to be addressed in Terraform Cloud, rather than in core, which is just the CLI. This GitHub repository is for issues specifically about Terraform core. Please open a support request by emailing this to tf-cloud@hashicorp.support.
