### ISSUE TITLE
Crash report in TF 0.12.29

### ISSUE THREAD

**Issue by immo-huneke-zuhlke** [hashicorp/terraform#26399]
This was while I was trying to run terraform destroy in a workspace.
[crash.log](https://github.com/hashicorp/terraform/files/5292871/crash.log)

**Comment by jbardin** [comment]
Hi @immo-huneke-zuhlke 

This appears to be a crash with a provider called "aws-synthetics".
This isn't a provider within our organization, so I cannot transfer the issue automatically. I suggest you open an issue with them directly.

Thanks!
