### ISSUE TITLE
Filter feature in GCP when do list

### ISSUE THREAD

**Issue by merceskoba** [hashicorp/terraform#26404]
Hi, I wanna ask to terraform community. I am a newcomer on terraform stack.

Currently, i do gcloud command like this
```
gcloud compute network-endpoint-groups list --filter="name~'alpha-neg' AND zone~'some-zone-$zone'" --project=my-project-23fa --format="csv[no-heading](name)"
```
That code above will do list network-endpoint-groups and then do filter (grep in linux command) after done listing.
In terraform documentation https://www.terraform.io/docs/providers/google/d/compute_network_endpoint_group.html , i don't find `filter` feature like gcloud command.
I want to do this because i don't want to hardcode the NEG name.

Give me some hint and insight please.

**Comment by apparentlymart** [comment]
Hi @merceskoba,

The issues in this repository are for bug reports and feature requests in Terraform Core. This seems to be a question about the Google Cloud Platform provider, which is not maintained in this repository and so I'm going to close this issue.

I suggest starting a new topic in [the Google Cloud Platform provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) to ask this question. The participants in the community forum are more familiar with that provider and thus better equipped to answer questions about it. Thanks!
