### ISSUE TITLE
Internalize all of the Go packages in this repository

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#26418]
Now that the SDK has moved out into [a separate repository](https://github.com/hashicorp/terraform-plugin-sdk), this main Terraform repository is a _main_ Go module rather than a _library_ Go module, and so none of the Go package APIs in here are intended for external consumption and they are not subject to semver-style backward compatibility promises.

Terraform is an older codebase that predates the introduction of the `internal` mechanism for to the Go toolchain that packages are not for external use, but since that is now the expected way to communicate that we're going to retroactively move all of Terraform's Go packages (aside from `package main` in the root) down under the `internal` directory.

We're intending to do this prior to tagging a Terraform 1.0 in order to avoid making it appear to the Go toolchain that our `v1.0.0` tag is a stable release of a Go Module containing library packages. However, we will have some delay before doing it in order to give a chance to land some already-opened pull requests that would likely end up with merge conflicts once the top-level packages have new import paths.

**Comment by wata727** [comment]
I'm so interested in this. As far as I know, some third-party utilities (including TFLint) are importing packages from this repository. And some of the packages are not included in terraform-plugin-sdk. For example, TFLint uses an internal API to [load configuration files](https://github.com/terraform-linters/tflint/blob/v0.20.2/tflint/loader.go#L60) and [evaluate expressions](https://github.com/terraform-linters/tflint/blob/v0.20.2/tflint/runner.go#L54-L63).

Are you planning to offer such functionality as a separate repository? If don't, I'm considering writing a Go module like "libterraform", just like when I opened https://github.com/hashicorp/terraform/issues/17904.

I agree with this change. I would like to discuss the policy of future third-party products. Thanks to the Terraform team.

**Comment by apparentlymart** [comment]
Hi @wata727,

The supported public interfaces for Terraform are protocols and file formats rather than in-process Go function calls, so I'd recommend integrating via external implementations of the documented protocols and formats. Because Terraform is open source, it's fine to use copies of code in this repository as the basis of those implementations, but it's important to distinguish between the documented interfaces and the current implementation details if you are building something that should work with multiple versions of Terraform.

Part of the 1.0 release will be some stronger promises about which parts of Terraform's behavior are integration points you can rely on.

**Comment by apparentlymart** [comment]
This is now done, in #28723.

If you end up here because you had an external codebase importing packages from Terraform, you can continue to import from older releases as a stop-gap measure for the moment, but I'd strongly recommend migrating to other approaches using the CLI executable via its machine-readable interfaces. Most of the supported surface area is available via [the `terraform-exec` library](http://pkg.go.dev/github.com/hashicorp/terraform-exec), which wraps execution of Terraform CLI and includes parsers for the machine-readable interfaces. If you need something that CLI offers but `terraform-exec` doesn't support yet, please open a feature request for that library.

Thanks!
