### ISSUE TITLE
Terraform workspace list doesn't error when there are no credentials 

### ISSUE THREAD

**Issue by waqarkhan3389** [hashicorp/terraform#26414]
### Terraform Version

```
0.12.29
```

### Terraform Configuration Files

```terraform
#backend.tf
terraform {
  backend "s3" {
    bucket  = "<redacted>"
    key     = "<redacted>"
    region  = "eu-west-2"
    encrypt = "true"
    acl     = "bucket-owner-read"
  }
}
```

### Expected Behavior

When running terraform workspace list it should error when a backend is configured as S3 and it cannot read the key/bucket

### Actual Behavior

Displays "Default" instead

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init` (with a user with access to backend S3) 
2. Log out, either unset AWS* variables or whatever method is used to log in - remove it
3. `terraform workspace list`
4. It should only display "Default" and not say it cannot read the rest of the workspaces to display them

**Comment by gdavison** [comment]
This issue seems to have been resolved since it was submitted. If you are still seeing this problem, please create a new issue
