### ISSUE TITLE
Provider blocks

### ISSUE THREAD

**Issue by jedineeper** [hashicorp/terraform#2641]
I've discovered provider blocks are no longer required if you have nothing to supply it. I can pass the relevant information to terraform via environment variables and it picks it up and everything seems to work fine.

Should we be declaring providers even if they have no variables to pass? Not sure how I feel about this so I thought I'd ask how other people are dealing with it...

Thanks,
Craig

**Comment by catsby** [comment]
Hey @jedineeper – if you're supplying all you need in the ENV they by all means omit it in your tf files! Personally I've seen a few provider blocks that have variables that come from lookups based on other criteria, so it seems there are setups like that up that would still require it. 

If you're looking for best practices, or to get an idea of what others are using, the [Terraform mailing list][1] may be a better place to ask.

Unless there's anything specific you're asking for here, regarding configuration requirements et. al, I'm going to close this and defer to the mailing list for discussion. 

[1]: https://groups.google.com/group/terraform-tool
