### ISSUE TITLE
terraform diff w/o changing state file

### ISSUE THREAD

**Issue by steeling** [hashicorp/terraform#26423]
Hi there,

I'm looking for a way to detect out of band changes in terraform, as a pre-check before apply to prevent automation from "stomping" users changes in emergencies.

What I would like to do is:
```
# Check for differences without modifying state file. Will return an exit code similar to plan's -detailed-exitcode
code = terraform check_for_differences [-target=resource]
if code == 2:
  # Mark as locked so other automation knows an out of band change happened. Out of band changes should be dealt with manually.
  terraform lock [-target=resource] #  See https://github.com/hashicorp/terraform/issues/26422
else:
  # Else apply normally
  terraform apply [-target=resource]
```

I know I could do this myself, by changing the `-state-out` path on `terraform refresh`, and diffing against the remote state file, but encapsulating in a single command would be useful

**Comment by jbardin** [comment]
Hi @steeling,

This feature has been implemented via #28634 and will be included in an upcoming release.

Thanks!
