### ISSUE TITLE
Error 404 response when create node_pool

### ISSUE THREAD

**Issue by Muhamed-Hamid** [hashicorp/terraform#26430]
Hey,

* Using google provider
When i try to create a node pool to a GKE cluster managed by composer, i refer the `config.0.gke_cluster` in cluster but i got the response: 
**Error: error creating NodePool: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>** 
<p>The requested URL <code>/*******/clusters/zone-pricing-dev-id-gke/nodePools?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>

* While i confirmed the correct name is the same in the url which not found

my resource is : 
```
resource "google_container_node_pool" "pricing" {
  name                   = "${var.name}-${var.env}"
  cluster                = google_composer_environment.pricing.config.0.gke_cluster
  location               = var.zone
```

Is there something i'm missing here ?

**Comment by danieldreier** [comment]
Hi @Muhamed-Hamid! Thank you for reporting this. This GitHub repository is for issues with Terraform Core, and the issue you reported appears to be an issue with the Google provider. I'm going to close it, and your next step is to file an issue directly with the Google provider at https://github.com/hashicorp/terraform-provider-google/issues.
