### ISSUE TITLE
Terraform 0.13.3 fails to load provider from local

### ISSUE THREAD

**Issue by VickyWinner** [hashicorp/terraform#26432]
Hi there,
     Terraform provider for vRA 7 forked from [here](https://github.com/vmware/terraform-provider-vra) and customized for my requirement.  When I upgrade terraform to 0.13.3, and run `terraform init`, it loads the provider from `terraform-providers/vra7`.  I tried to change the `versions.tf` as below but throws error when ran `terraform init`.  

```terraform
terraform {
  required_providers {
    vra7 = {
      //source = "terraform-providers/vra7"
      source = "C:/Users/userid/AppData/Roaming/terraform.d/plugins/windows_amd64/terraform-provider-vra7.exe"
    }
  }
  required_version = ">= 0.13"
}
```

Error after changing code as shown above:

```log
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Invalid provider source string

  on versions.tf line 3, in terraform:
   3:     vra7 = {
   4:       //source = "terraform-providers/vra7"
   5:       source = "C:/Users/userid/AppData/Roaming/terraform.d/plugins/windows_amd64/terraform-provider-vra7.exe"
   6:     }

The "source" attribute must be in the format "[hostname/][namespace/]name"

Terraform 13 doesn't import vra7 provider from the local or other path as source parameter only supports "[hostname/][namespace/]name" format
```

### Terraform Version
0.13.3

### Terraform Configuration Files

```terraform
provider "vra7" {
  username = var.vraUsername
  password = var.vraPassword
  host     = var.host
}

resource "vra7_deployment" "modname" {
  count               = var.instances
  catalog_item_name   = var.blueprint_name

  resource_configuration = {
    "vSphereVM1.description"                                                      = var.deployment_description
    "vSphereVM1.cpu"                                                              = var.cpu
    "vSphereVM1.memory"                                                           = var.memory
  }
}
...
```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
Terraform should load the providers if exist in the path mentioned above and shouldn't try to load from external github.

### Actual Behavior
Terraform loads provider from github.com or registry and ignores the local path.

### Steps to Reproduce

1. download vra 7 provider and keep it in the standard path.
2. `terraform init`

**Comment by pkolyvas** [comment]
Hey @VickyWinner - providers in 0.13 use a source address which means that you can specify your custom version of a provider in fun new ways! This does, however have some implications on how providers are installed locally.

Terraform `0.13` introduced a "namespace" requirement. This means that, even on-disk, the folder hierarchy needs to reflect the components of the provider source address. 

Let's take your forked VRA provider. Your required providers block could look like this, as an example:

```hcl
terraform {
  required_providers {
      vra7 = {
         source = "vickywinner.com/vmware/vra7"
      }
}
```

Following the above, the on-disk the above provider's location would be:
`C:/Users/userid/AppData/Roaming/terraform.d/plugins/vickywinner.com/vmware/vra7/windows_amd64/terraform-provider-vra7.exe`

Providers use a new source address that includes the following components:
`<registry_host>/<namespace>/<type>`

Let's take the verified VRA provider from the registry:
```hcl
terraform {
  required_providers {
      vra7 = {
         source = "vmware/vra7"
      }
}
```

In the example above, where no registry host is specified, Terraform assumes the registry address is `registry.terraform.io` and so the relative folder structure (on-disk) would be `../registry.terraform.io/vmware/vra/..`.

I hope that clarifies how to setup your locally installed providers?

There are some features that can further help here including some new tools around provider installation: 
https://www.terraform.io/docs/commands/cli-config.html#provider-installation

I'm going to close this issue, but if you want further input into how to setup your on-disk providers please join us over at the [community forums](https://discuss.hashicorp.com/c/terraform-core/27).
