### ISSUE TITLE
terraform plan doesnt work for prefix_length other than 28

### ISSUE THREAD

**Issue by swapnild2111** [hashicorp/terraform#26449]
Hello,

I have an Azure IP prefix with `prefix_length = 30`
Then I imported that with `terraform import xxx` and I could see perfect data in tfstate. All good.

After which when I run `terraform plan`, I could see resource will be replaced due to `prefix_length` getting changed from 30 to 28.

Terraform version - 

```bash
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.29.0
```

Terraform config - 

```bash
resource "azurerm_public_ip_prefix" "test-prefix" {
  name                = "test-prefix"
  resource_group_name = "xxx"
  location            = "westeurope"
}
```

Terraform import command -

```bash
terraform import azurerm_public_ip_prefix.test-prefix /subscriptions/x-y-z/resourceGroups/xxx/providers/Microsoft.Network/publicIPPrefixes/test-prefix
```

Terraform state file - 

```bash
{
  "version": 4,
  "terraform_version": "0.13.3",
  "serial": 1,
  "lineage": "4598e109-1138-8ad1-aa83-e26c6f8c114d",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "azurerm_public_ip_prefix",
      "name": "test-prefix",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "/subscriptions/x-y-z/resourceGroups/xxx/providers/Microsoft.Network/publicIPPrefixes/test-prefix",
            "ip_prefix": "xxx/30",
            "location": "westeurope",
            "name": "test-prefix",
            "prefix_length": 30,
            "resource_group_name": "xxx",
            "sku": "Standard",
            "tags": {
              "Self Managed": "Yes"
            },
            "timeouts": {
              "create": null,
              "delete": null,
              "read": null,
              "update": null
            },
            "zones": []
          },
          "private": "xxx"
        }
      ]
    }
  ]
}
```

Terraform plan output - 

```bash
Terraform will perform the following actions:

  # azurerm_public_ip_prefix.test-prefix must be replaced
-/+ resource "azurerm_public_ip_prefix" "test-prefix" {
      ~ id                  = "/subscriptions/x-y-z/resourceGroups/xxx/providers/Microsoft.Network/publicIPPrefixes/test-prefix" -> (known after apply)
      ~ ip_prefix           = "xxx/30" -> (known after apply)
        location            = "westeurope"
        name                = "test-prefix"
      ~ prefix_length       = 30 -> 28 # forces replacement
        resource_group_name = "xxx"
        sku                 = "Standard"
      - tags                = {
          - "Self Managed" = "Yes"
        } -> null
      - zones               = [] -> null

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I tested this with couple of other resource groups and result is same.

Can someone please help?

Note 
----------
I had raised this with AzureRM provider community, Ref: https://github.com/terraform-providers/terraform-provider-azurerm/issues/8684

However they think, I should be raising the question here. Can you help?

**Comment by jbardin** [comment]
Hi @swapnild2111,

Sorry you're having trouble with this. Your resource was created with a setting which differs from the default, therefore it is expected that you would need to supply the correct value in the configuration to prevent Terraform from attempting to reset it back to the default.

Since this isn't a bug, I believe the response on your Azure issue was hinting that you may get more assistance in the community forums. There is a general [Terraform](https://discuss.hashicorp.com/c/terraform-core/27) category there, as well as specific pages for providers, like [Azure](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).


Thanks!

**Comment by swapnild2111** [comment]
@jbardin Thank you for reply. I have generic terraform module to import these. 
What I don't understand is, why it gets set to default instead of setting it to the value being imported? That's why I see it as a bug.

**Comment by jbardin** [comment]
The default is 28, so not setting `prefix_length` in the configuration means you're telling the provider to use the default, which is 28. This differs from the state, and attempts to override the previous setting of 30. If you don't want the provider to use the default, you must provide another value.

**Comment by swapnild2111** [comment]
As per documentation - `prefix_length` is an optional field, which in my opinion means, can be overridden in resource import scenario. So if consider what you are saying, if it is not set, it will be set to default value, can I ask what happens with other optional fields which get set properly with import scenario?

I am not trying to debate :D but frankly am not satisfied with your logic :( 

If I were there, my coding logic will be - 
1. If we are creating a new ip prefix with terraform and prefix_length is not set, then it makes sense to set it to 28.
2. If we already have an ip prefix in azure cloud and we wish to manage that resource via terraform going forward, then I will import the resource with bare minimum required fields, and set rest all fields to the values imported. In above scenario, imported prefix_length is 30, so will set as it is.
3. If we already have an ip prefix in azure cloud and we wish to manage that resource via terraform going forward, but I wish to have different prefix_length, then it's as good as first scenario of creating a new resource itself.

Tried to explain as much as possible, let's ignore if we both still disagree, I will patch my code as you mentioned.

**Comment by jbardin** [comment]
I understand the desire to have a different behavior in some cases, but this is the defined behavior of the default value. Other optional attributes that don't have a `Default` are not overridden. The way the default values are handled by the plugin SDK is merely a convenience to alleviate providers from needing to handle the logic, but it is limited in what it can do. A future SDK may provide more functionality.

Note that Terraform itself has no influence over any of this, as the defaults are implemented by the plugin via a combination of the SDK and the resource implementation. The above behavior may be implemented by the provider itself, but the cost of changing all uses of `Default` may not be worth the effort, and they may be waiting for the next generation SDK to offer more flexibility.
