### ISSUE TITLE
aws_cognito_resource_server API does not match the AWS API

### ISSUE THREAD

**Issue by pll** [hashicorp/terraform#26455]
The current documentation for the resource `aws_cognito_resource_server` specifies that custom scopes should be defined using `scope {}` blocks, which are maps with the keys `scope_name` and `scope_description`.

However, both the Boto3 and the AWS API specify that scopes should be defined as a list of maps:

    Scopes (list) -- A list of scopes. Each scope is map, where the keys are name and description .

- https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/create-resource-server.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html#CognitoIdentityProvider.Client.create_resource_server

The problem with the current implementation in Terraform is that, when assigning custom scopes to a `aws_cognito_user_pool_client` resource, the `allowed_oauth_scopes` takes a list of strings.  Which means, if I know the order of the list the scopes were added to, I could simply index into the list.

Unfortunately, the current implementation does not indicate any order to the resulting list `aws_cognito_resource_server.foo.scope_identifiers`, which makes indexing into the list unreliable.  At present, the best alternative I have is to concoct the name of the specific scope I wish to add to my app client by using something like this:

     allowed_oauth_scopes = [ "${aws_cognito_resource_server.foo.identifier}/SCOPE_NAME" ]

This is not ideal, since, if I need to change the name of the scope, I now have to do so in multiple places.

I think a better solution would be to define custom scopes according to the AWS API like this:

```

resource "aws_cognito_resource_server" "tms" {
  user_pool_id = aws_cognito_user_pool.foo.id
  name	       = "My Cognito Server"
  identifier   = aws_cognito_user_pool_domain.foo.domain

  scope {
    [
      {
	scope_name = "SCOPE_ONE"
	scope_description = "First Scope"
      },
      {
	scope_name = "SCOPE_TWO"
	scope_description = "Second Scope"
      }
    ]
  }
}

```

Presumably, this would then result in `aws_cognito_resource_server.foo.scope_identifiers` being a list of all scopes configured for this resource server in the format identifier/scope_name, and in the order defined by the scope list declaration.

Thanks.
--
Paul

**Comment by apparentlymart** [comment]
Hi @pll! 

This seems like feedback for the AWS provider rather than for Terraform Core, and unfortunately the AWS provider is developed by a separate team in a separate repository. In order to get this feedback to the AWS provider team, please open a feature request issue in [the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws).

Because there isn't anything we could change in this repository to help with what you've reported here, I'm going to close this. Thanks for sending in the feedback, though!
