### ISSUE TITLE
Updating terraform provider version in workspace fails to find provider version in registry

### ISSUE THREAD

**Issue by jooh-lee** [hashicorp/terraform#26489]
### Terraform Version

```
0.13.4
```

### Terraform Configuration Files

```terraform
versions.tf in a module:

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.4.0"
    }
  }
  required_version = ">= 0.13"
}
```

```terraform
versions.tf in the workspace:

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.9.0"
    }
  }
  required_version = ">= 0.13"
}
```

### Expected Behavior
 The aws provider version 3.9.0 should be found and installed.

### Actual Behavior
 fails to find the provider. Have to set the version of all modules to ">= 3.9.0" for the provider to be found.
```
Error: Failed to query available provider packages
--
885 |  
886 | Could not retrieve the list of available versions for provider hashicorp/aws:
887 | no available releases match the given constraints 3.9.0, >= 3.4.0, .... (just repeats a bunch of >= 3.4.0)
```

### Steps to Reproduce
1. `terraform init -input=false -no-color`

### Additional Context
 Does not work locally

### References
 None that im aware of

**Comment by alisdair** [comment]
@jooh-lee I'm unable to reproduce this issue. Here's the configuration I'm using:

main.tf:

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.9.0"
    }
  }
  required_version = ">= 0.13"
}

module "mod" {
  source = "./mod"
}
```

mod/main.tf:

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.4.0"
    }
  }
  required_version = ">= 0.13"
}
```

Initializing works:

```shellsession
$ terraform-0.13.4 init
Initializing modules...
- mod in mod

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "3.9.0, >= 3.4.0"...
- Installing hashicorp/aws v3.9.0...
- Installed hashicorp/aws v3.9.0 (signed by HashiCorp)

Terraform has been successfully initialized!
```

Some questions to help figure out what's going on here:

- Can you modify my simple configuration to reproduce the bug?
- Do you have any [`plugin_cache_dir`](https://www.terraform.io/docs/commands/cli-config.html#plugin_cache_dir) or [`provider_installation`](https://www.terraform.io/docs/commands/cli-config.html#provider_installation) blocks in your `~/.terraformrc`?
- Can you paste the output of `terraform providers`?

**Comment by joao-miranda** [comment]
@alisdair 

- Do you have any plugin_cache_dir or provider_installation blocks in your ~/.terraformrc?

Your configuration has no issues, but if you specify a higher required version that 0.13.3 you should have the same error:

main.tf:

> terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.9.0"
    }
  }
  required_version = ">= 0.13.4"
}

Just using required_version = ">= 0.13" (which defaults to 0.13.3 ) or required_version = ">= 0.13.3" works fine.

- Do you have any plugin_cache_dir or provider_installation blocks in your ~/.terraformrc?

No.

- Can you paste the output of terraform providers?

> Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws] 3.9.0
└── module.mod
    └── provider[registry.terraform.io/hashicorp/aws] >= 3.4.0

But that seems to just be the "leftovers" of executing your configuration.

**Comment by alisdair** [comment]
> Your configuration has no issues, but if you specify a higher required version that 0.13.3 you should have the same error

I'm still not able to reproduce this here. Note that specifying a higher required Terraform version will not affect the `terraform init` behaviour, so long as that version requirement is satisfied by the running version.

If you can reliably reproduce this, please create a gist with the full Terraform log output after setting the environment variable `TF_LOG=trace`.

**Comment by joao-miranda** [comment]
@alisdair Executing **terraform init** on a folder with the following main.tf:

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.9.0"
    }
  }
  required_version = ">= 0.13.4"
}

```
 I get the following:

> 2020/11/04 16:40:06 [INFO] Terraform version: 0.13.3  
2020/11/04 16:40:06 [INFO] Go runtime version: go1.14.7
2020/11/04 16:40:06 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/11/04 16:40:06 [DEBUG] Attempting to open CLI config file: <USER_HOME>/.terraformrc
2020/11/04 16:40:06 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/04 16:40:06 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/04 16:40:06 [DEBUG] ignoring non-existing provider search directory <USER_HOME>/.terraform.d/plugins
2020/11/04 16:40:06 [DEBUG] ignoring non-existing provider search directory <USER_HOME>/Library/Application Support/io.terraform/plugins
2020/11/04 16:40:06 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/04 16:40:06 [INFO] CLI command args: []string{"init"}

Error: Unsupported Terraform Core version

  on main.tf line 8, in terraform:
   8:   required_version = ">= 0.13.4"

This configuration does not support Terraform version 0.13.3. To proceed,
either choose another supported Terraform version or update this version
constraint. Version constraints are normally set for good reason, so updating
the constraint may lead to other errors or unexpected behavio

**Comment by alisdair** [comment]
@joao-miranda I don't understand the issue here. Your configuration is requiring that you use Terraform version 0.13.4 or higher, and you are running Terraform 0.13.3. Terraform is therefore refusing to run, as specified by the configuration.

This also doesn't seem to relate to the originally reported issue of being unable to install a provider. Am I missing something?

**Comment by joao-miranda** [comment]
@alisdair you are correct. I was making a mistake locally. From my end all is fine like you said.

**Comment by alisdair** [comment]
Thanks for confirming!

As we haven't had a response from the original reporter for a month now, and I still can't find a way to reproduce this issue, I'm going to mark it closed.

Note to anyone who finds this issue via search: the original provider installation symptoms may occur with a misconfigured global `provider_installation` setting, so perhaps check there first.
