### ISSUE TITLE
Inconsistent/incorrect(?) handling of null input variables

### ISSUE THREAD

**Issue by artburkart** [hashicorp/terraform#26499]
### Terraform Version
Build Terraform binary using `go build -o bin/terraform .` in root of the repository. The SHA is bad0adb9968332cd9f9ca272b5698102b3cc7ea6.

```command
$ ./bin/terraform version
Terraform v0.14.0-dev
```

### Terraform Configuration Files

**main.tf**
```hcl
module "m" {
  source = "./module"
  input  = var.input
}

variable "input" {
  type = string
  default = "hello"
}

output "out" {
  value = module.m.out
}
```

**module/main.tf**
```hcl
variable "input" {
  type = string
  default = "howdy"
}

output "out" {
  value = "'${var.input}'"
}
```

### Expected Behavior

> null: a value that represents absence or omission. If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met.

https://www.terraform.io/docs/configuration/expressions.html

### Actual Behavior

Terraform handles null input variables in a number of different ways.

### Steps to Reproduce

**Test 1** ✅ 

```command
$ terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out = "'hello'"
```

This behaves as expected. 

---

**Test 2** ❓ 
```command
TF_VAR_input= terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out = "''"
```

I assume this is interpreting the absence of a value as an empty string. Does this mean there's no way to null a value with environment variables? I could see this being the result of a decision that was made based on `null` not existing in older versions of Terraform.

---

**Test 3** ✅ 
```command
TF_VAR_input=null terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out = "'null'"
```

This one makes sense, but it could be seen as somewhat unexpected.

---

**Test 4** ❓ 
```command
$ terraform apply -auto-approve -var input=

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out = "''"
```

I assume this is interpreting the absence of a value as an empty string. Does this mean there's no way to nullify a value with the `-var` flag? I could see this being the result of a decision that was made based on `null` not existing in older versions of Terraform, but perhaps the default choice of empty string is no longer applicable.

---

**Test 5** ❓ 
```command
$ terraform apply -auto-approve -var input=null

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

out = "'null'"
```

I perceive this as the same behavior as TF_VAR_input=null, except it would seem to me that there should be a difference between `-var input=null` and `-var input="null"`

---

**Test 6** ❌ 
```command
$ terraform apply -var-file=<(echo "input=null")

Error: Invalid template interpolation value

  on module/main.tf line 7, in output "out":
   7:   value = "'${var.input}'"
    |----------------
    | var.input is null

The expression result is null. Cannot include a null value in a string
template.
```

This seems to be a bug. Passing in a file where the value of input is successfully set to null should result in the default value being used, which in this case is "howdy" per the default module value.

---

**Test 7** ❌ 
```command
$ terraform apply -var-file=<(echo "input=")

Error: Invalid expression

  on /dev/fd/63 line 1:
   1: input =

Expected the start of an expression, but found an invalid expression token.
```

I note this test scenario only because the absence of a string appears to be treated differently from the scenarios where we use environment variables and the `-var` command line option.

---

**Test 8** ❓ 
```command
$ terraform apply -var-file=<(echo '{"input": null}')

Error: Argument or block definition required

  on /dev/fd/63 line 1:
   1: {"input": null}

An argument or block definition is required here.
```

This scenario is also interesting, because it would seem the `-var-file` command line option defaults to `.tfvars` files and cannot parse JSON files unless they have the `.json` extension. Since a `.tfvars` file may technically have any extension whatsoever, it would seem the `-var-file` command line option should respect either file type, because there'd be no reason to expect one file type over another to be passed in.

The documentation has this to say:
> To set lots of variables, it is more convenient to specify their values in a variable definitions file (with a filename ending in either .tfvars or .tfvars.json) and then specify that file on the command line with -var-file

> Files whose names end with .json are parsed instead as JSON objects, with the root object properties corresponding to variable names:

https://www.terraform.io/docs/configuration/variables.html

I could see it going either way. If nothing else, it's worth noting that the `.tfvars` extension seems to be more of a convention than a standard while the `.auto.tfvars` extension is enforced by code.

### Additional Context

I mostly wanted to get a sense of whether others perceived the handling of null variable inputs as either inconsistent or incorrect. I also wanted to know if setting a variable to null is something we should be able to do outside the context of a `.tfvars` file.

Thanks 👍

**Comment by jbardin** [comment]
Hi @artburkart,

Thanks for enumerating those various conditions! We generally don't have a method to _unset_ a variable outside of the configuration, but that is a possibility now that we have `null`.  It would be a breaking change however to accept `null` as not being a string, since it would alter how all string arguments need to be quoted on the CLI, so we need to weigh what the overall benefit here would be.

The fact that setting `null` overrides a default (`#6` here) was brought up in #24142, and is also be a breaking change to alter the behavior, as some modules do use the current behavior to override defaults.

Thanks!

**Comment by artburkart** [comment]
Ah, in that case, I'd be okay with closing this issue in favor of that. I searched around a little bit, but I failed to find it. Might I propose that the documentation be updated to reflect the reality? I'd be happy to make a PR to achieve that much.

Thanks for your follow up.

**Comment by earchibald** [comment]
The problem here is really that the documentation is very specifically misleading -- still the case as of today that the documentation states:

```
 If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met.
```

If it doesn't work for modules, we should remove "or module" from the docs.

**Comment by jbardin** [comment]
Consoidating with #24142
