### ISSUE TITLE
Terraform crashes when expecting a string but getting a list in configuration

### ISSUE THREAD

**Issue by gosuri** [hashicorp/terraform#2649]
Haven't looked into further but here's the log https://gist.githubusercontent.com/gosuri/dc5bec1edc957c91bce2/raw/6defc11ef9123bb02bdb7a43e84c984a02ad092b/tfcrash-jun-7.log

**Comment by catsby** [comment]
Hey @gosuri – it's hard to say much without a matching configuration file.
The root of the issue involves your `aws_route_table_association.main` resource:

```
2015/07/07 15:19:43 terraform-provider-aws: panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
```

Do you have a config from this resource you can safely share (minus any secrets)? Do you recall what change you were making? It _appears_ that the input it received didn't match up with what it was expecting.

**Comment by gosuri** [comment]
Hey @catsby - Here's the config:

**Comment by catsby** [comment]
thanks @gosuri – sorry for the delay, I was out of the office the end of last week. I'll try to take a look today

**Comment by gosuri** [comment]
No worries @catsby, hope you had a good time off :)

**Comment by catsby** [comment]
Hey @gosuri – so, the short of it is that `subnet_id` is singular, and in the example above it's getting a list:

     subnet_id = ["${aws_subnet.main.id}"]

That should just be  `subnet_id = "${aws_subnet.main.id}"`

The long of it would be "why does that _crash_?", which requires some more investigation :smile: 

Let me know if that sounds right to you

**Comment by gosuri** [comment]
Ah! good deal, that totally worked :) Thanks so much @catsby!

**Comment by catsby** [comment]
Glad to hear! We'll leave this open so we can dig into why that crashes... 

Thanks again

**Comment by gosuri** [comment]
:+1:

**Comment by catsby** [comment]
Same issue in https://github.com/hashicorp/terraform/issues/3044

**Comment by gosuri** [comment]
🎉
