### ISSUE TITLE
Allow to override sensitive TFC variables locally

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform#26497]
When using Terraform Cloud, often we need to import resources. Unfortunately, if you have sensitive variables and use remote runs, the CLI just halts and doesn't give you a way to override those sensitive variables locally.

### Terraform Version
```
Terraform v0.13.4
```

### Crash Output
```
Warning: Value for var.aws_secret_key unavailable

The value of variable "aws_secret_key" is marked as sensitive in the remote
workspace. This operation always runs locally, so the value for that variable
is not available.


Error: Invalid provider configuration

  on providers.tf line 1:
   1: provider "aws" {

The configuration for provider["registry.terraform.io/hashicorp/aws"] depends
on values that cannot be determined until apply.
```

### Expected Behavior
I should be able to pass the variable either via `-var` CLI switch or add a `.tfvars` file with the sensitive values locally.

**Comment by petems** [comment]
Is this a duplicate of https://github.com/hashicorp/terraform/issues/26494?

**Comment by nikolay** [comment]
@petems It sure is. I searched but didn't find it.
