### ISSUE TITLE
aws_eip resource should output public_dns

### ISSUE THREAD

**Issue by rafikk** [hashicorp/terraform#2650]
EC2 elastic IPs have associated public_dns. That field should be exposed as an output if provided via the AWS APIs.

**Comment by catsby** [comment]
Hey @rafikk – I'm looking at the documentation in the API docs, but I'm not seeing a public DNS:

- http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Address.html

Am I looking in the wrong place? Can you help me find the documentation for what you're asking?

**Comment by catsby** [comment]
Closing for now, I don't believe there's a way to get this information from the current API
