### ISSUE TITLE
terraform 0.13 state show doesn't have option for json output

### ISSUE THREAD

**Issue by Upgreydd** [hashicorp/terraform#26500]
According to https://www.terraform.io/docs/commands/show.html#json-output
In terraform 0.13 there's no option for json output.

```
Error parsing command-line flags: flag provided but not defined: -json

terraform state show --help
Usage: terraform state show [options] ADDRESS

  Shows the attributes of a resource in the Terraform state.

  This command shows the attributes of a single resource in the Terraform
  state. The address argument must be used to specify a single resource.
  You can view the list of available resources with "terraform state list".

Options:

  -state=statefile    Path to a Terraform state file to use to look
                      up Terraform-managed resources. By default it will
                      use the state "terraform.tfstate" if it exists.

```

### Terraform Version
```
Terraform v0.13.3
+ provider registry.terraform.io/datadog/datadog v2.13.0
+ provider registry.terraform.io/hashicorp/aws v3.8.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/github v3.0.0
+ provider registry.terraform.io/hashicorp/google v3.41.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
```

**Comment by jbardin** [comment]
Hi @Upgreydd 

The interface to get a json representation of the state is via `terraform show -json`, which is the command you linked in the docs. Can you describe the problem or a different use-case you're trying to solve using the `state` command?

Thanks!

**Comment by sklarsa** [comment]
I'm seeing similar behavior running terraform 12...
```
$ terraform state show -json my.resource.path
Error parsing command-line flags: flag provided but not defined: -json

$ terraform version
Terraform v0.12.24
```

**Comment by jbardin** [comment]
Closing since we have not heard back.  We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
