### ISSUE TITLE
API Gateway domain object is not being populated when using type REGIONAL

### ISSUE THREAD

**Issue by carloshenrique153** [hashicorp/terraform#26515]
`terraform apply` is not populating the object in the output below when the API Gateway is `REGIONAL`
 instead of `EDGE`. 

```
resource "aws_api_gateway_domain_name" "api_gateway_domain_name" {
  regional_certificate_arn = "arn:..."
  domain_name              = "my-domain"
  security_policy          = "TLS_1_2"

  endpoint_configuration {
    types = [
      "REGIONAL"
    ]
  }
}

output test {
  value = aws_api_gateway_domain_name.api_gateway_domain_name
}
```

And without this value, I'm not able to set a Route 53 record to this API Gateway domain.

Tested on terraform Version 0.12.29

**Comment by awsiv** [comment]
Probably belongs to: https://github.com/terraform-providers/terraform-provider-aws ?

**Comment by carloshenrique153** [comment]
This bug is not happening in Terraform 0.13.4 :)
