### ISSUE TITLE
Vague error, unable to determine IAM policy changes

### ISSUE THREAD

**Issue by jjshoe** [hashicorp/terraform#2651]
Running terraform plan from CI to do basic checking. However when using an aws_iam_instance_profile the errors returned back don't tell me what I'm un-authorized to do. 

```
build	08-Jul-2015 14:13:28	[0m[1maws_iam_instance_profile.build_agent_iam_instance_profile: Refreshing state... (ID: bamboo_build_agent_iam_instance_profile)[0m
error	08-Jul-2015 14:13:28	[31mError refreshing state: 3 error(s) occurred:
error	08-Jul-2015 14:13:28	
error	08-Jul-2015 14:13:28	* 1 error(s) occurred:
error	08-Jul-2015 14:13:28	
error	08-Jul-2015 14:13:28	* UnauthorizedOperation: You are not authorized to perform this operation.
error	08-Jul-2015 14:13:28		status code: 403, request id: []
error	08-Jul-2015 14:13:28	* 1 error(s) occurred:
error	08-Jul-2015 14:13:28	
error	08-Jul-2015 14:13:28	* UnauthorizedOperation: You are not authorized to perform this operation.
error	08-Jul-2015 14:13:28		status code: 403, request id: []
error	08-Jul-2015 14:13:28	* 1 error(s) occurred:
error	08-Jul-2015 14:13:28	
error	08-Jul-2015 14:13:28	* UnauthorizedOperation: You are not authorized to perform this operation.
error	08-Jul-2015 14:13:28		status code: 403, request id: [][0m[0m
simple	08-Jul-2015 14:13:28	Failing task since return code of [/usr/local/bin/terraform plan -state=./state/agent.tfstate -var-file=./vars/agent.tfvars ./ami] was 1 while expected 0
```

**Comment by radeksimko** [comment]
I think the error actually comes from `refresh` which runs on behalf of `plan`.
When running `plan` in your CI setup, do you have any existing state - either remote or local?

Can you try forcing `plan` to not run any refresh?

```
terraform plan -refresh=false
```
I'm not quite sure what do you intend to get out that CI setup. You actually may want to see the real plan against real state - i.e. do the `refresh` - in that case you may have to setup AWS credentials properly in that CI.

**Comment by phinze** [comment]
> the errors returned back don't tell me what I'm un-authorized to do.

Unfortunately this is the response from the AWS API we get. In order to figure out what precisely the unauthorized operation was, you can turn on [debug logging](https://terraform.io/docs/internals/debugging.html) and check out what was happening just before the error.

**Comment by jjshoe** [comment]
Why not update the error to show what was trying to be done?

**Comment by phinze** [comment]
@jjshoe we do [prefix the error with the operation we were trying to perform](https://github.com/hashicorp/terraform/blob/abe62e635a0141243c199dd066f33a33a7ae3991/builtin/providers/aws/resource_aws_iam_instance_profile.go#L179) which makes me think perhaps the error is coming from somewhere else.

Can you post debug logs and we can try and run it down?

**Comment by jjshoe** [comment]
Sadly, I don't have an easy way to reproduce this at the moment :(

**Comment by catsby** [comment]
Hey @jjshoe , do you have any more information here, or have you hit this since? I'm going to close this issue for now, but if you do have more information please follow up and I can take another look.

Thanks!
