### ISSUE TITLE
Adding Support for s390x and ppc64le

### ISSUE THREAD

**Issue by james-crowley** [hashicorp/terraform#26522]
### Use-cases
Adding `s390x` and `ppc64le` would allow users to utilize Terraform on platform. Currently if a user wants to use Terraform, we must be on an `amd64` or `arm` platforms. This limits the user’s choice and might potential block them entirely if the currently supported architectures are not available in their environments. 

Also, the lack of support limits the design choices when making Terraform files. Some providers interact with resources on a given server rather than talking to remote resources. In these use cases, users are blocked from using their Terraform files.

Adding support for `s390x` and `ppc64le` would not only allow users to run on platform but will also allow users to design their Terraform files without being constrained. 

### Attempted Solutions
Our attempted solutions have been compiling Terraform and the needed providers for each Terraform environment. Most of Terraform’s code, providers included, is written in Golang. Golang has excellent support for both `s390x` and `ppc64le`, which allows us to compile everything without an issue. An additional benefit of Golang is the support for cross compiling for other architectures, which makes building for additional architectures less complicated.

While this solution “works”, it is extremely inconvenient as we have to manually build all the providers. Additionally, without being an official supported architecture we lack the support from the Terraform staff/community on issues.

### Proposal
The proposal is to add `s390x` and `ppc64le` officially to Terraform. This includes having releases of the Terraform binary plus all the official Terraform providers. 

In order to complete the proposal Terraform would need to have access to `s390x` and `ppc64le` hardware. For open source communities/tools like Terraform, IBM does offer free resources for both `s390x` and `ppc64le`. 

Other than having access to hardware, what other requirements are needed to add support for `s390x` and `ppc64le`? A couple things were mentioned in this comment, https://github.com/hashicorp/terraform/pull/18708#issuecomment-414462625, but I want to make sure we have all the requirements in one place. 

### References
#21283
#18708
#23979

**Comment by pkolyvas** [comment]
Hi @james-crowley 

Unfortunately adding `s390x` and `ppc64le` is not on our roadmap at the moment. The main requirement is that we are convinced the proposed work is of higher priority than our other areas of focus and unfortunately it's not. 

The reality for us at Terraform (Core) is that we simply don't have the ability to support these architectures for the very reason you highlight: official releases will need support from our team. We are deeply focused on the final technical changes that feed into a 1.0 release. While we can and will reconsider the platforms we officially support periodically, we're just not able to add these currently. 

As you noted, the threshold to adding support for a platform in Terraform isn't only at the level of this part of the product (the CLI tool), rather the entire provider ecosystem. We recently included `linux_arm64` in our official releases for `0.14`+. We've seen the popularity of that platform trending up pretty decisively. Additionally, most provider developers were already releasing `linux_arm64` binaries [based on HashiCorp's guidance](https://www.terraform.io/docs/registry/providers/os-arch.html). We will very likely add `darwin_arm64` once Go support is available. 

This is by no means a "never" and my door is always open for further discussion My contact info is on my Github profile should anyone wish to discuss further.
