### ISSUE TITLE
Invalid count argument when using spat expressions of zero length

### ISSUE THREAD

**Issue by jescholl** [hashicorp/terraform#26526]
### Terraform Version

```
v0.13.3
```

### Terraform Configuration Files

```terraform
locals {
  one_outputs = data.null_data_source.one.*.outputs
  # flip these two assignments back and forth to make it fail
  values = []
  #values = ["foo", "bar", "baz"]
}

data "null_data_source" "one" {
  count = length(local.values)
  inputs = { value = local.values[count.index] }
}

resource "null_resource" "two" {
  # flip these two assignments back and forth to make it succeed
  #count = 0
  count = length(local.one_outputs)
}

output "values_length" {
  value = length(local.values)
}

output "one_outputs" {
  value = {
    outputs = local.one_outputs
    length = length(local.one_outputs)
  }
}

output "two" {
  value = null_resource.two
}
```

### Debug Output

https://gist.github.com/jescholl/980eb7199371ec8afee6072a9dc486d6

### Expected Behavior

Splat expressions on a data resource with `count = 0` should return an empty list with `length` 0 allowing other resources to use the `length` of the output to determine their own `count` even if the `length` is 0

### Actual Behavior

Sometimes the splat expression returns an empty list as expected giving the following output
```terraform
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

one_outputs = {
  "length" = 0
  "outputs" = []
}
two = []
values_length = 0
```

Sometimes it halts execution with the following error.
```terraform
Error: Invalid count argument

  on test.tf line 16, in resource "null_resource" "two":
  16:   count = length(local.one_outputs)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

If the run succeeds, it can be forced to fail by
1. swap the `values` assignments on lines 4 and 5
2. `terraform apply
3. swap the `values` assignments on lines 4 and 5 back to their original state
4. `terraform apply`
5. All `terraform apply` runs will now fail

If the run fails, it can be forced to succeed by
1. swap the `count` assignments on lines 15 and 16
2. `terraform apply
3. swap the `count` assignments on lines 15 and 16 back to their original state
4. `terraform apply`
5. All `terraform apply` runs will now succeed

Once it starts failing, it will fail consistently until lines 15 and 16 are flipped a

**Comment by jbardin** [comment]
Hi @jescholl 

Thanks for filing the issue. This general type of error has been resolved for the 0.14 release. It is caused by the inability to run the refresh step when terraform cannot reconcile difference between the state and the configuration. Terraform 0.14 no longer requires a separate refresh phase, instead reading individual resources on demand. 

I verified this configuration is working with the latest build.

Thanks!
