### ISSUE TITLE
Flag for chef zero in chef provisioner?

### ISSUE THREAD

**Issue by jmreicha** [hashicorp/terraform#2652]
It would be useful to have a flag that can be turned on in the chef provisioner to run the chef client in local mode.  Sometimes there are cases when a checkin to the chef server is not wanted.

Does this functionality make sense and would there be much work involved to get this to work?

**Comment by svanharmelen** [comment]
@jmreicha yeah, think that makes sense... Don't think it's that much work, but it will need a few tweaks and some good testing to get it working properly.

**Comment by kpettijohn** [comment]
I would find a chef-zero/local provisioner helpful as well. Currently I am building AMI's using packer/chef-zero and orchestrating them using terraform. It would be nice to have the ability to make small changes to the attributes/run_list directly from terraform. 

I would love to help with testing if someone takes a pass at adding the feature. 

Also thanks for implementing the Chef provisioner in the first place @svanharmelen !

**Comment by svanharmelen** [comment]
I'm closing this one as "would fix" for the time being... It turns out this would have a reasonable impact on the current Chef provisioner and would take some more time then first expected to build and test.

It's still doable, but it's more then likely not going to happen any time soon. Of course if anyone out there is up for adding the needed code, I would be more then happy reviewed and accept a PR for this!

If someone feels like this one shouldn't be close for some reason, then by all means feel free to reopen the issue! Thanks!

**Comment by sandstrom** [comment]
Chef Zero would be very useful! :boat:

**Comment by apparentlymart** [comment]
Perhaps it would be more straightforward to have a separate provisioner specifically for chef-zero, like Packer does. I expect it would have a pretty similar interface and might even share some implementation, but keeping it separate allows us to avoid conflicting design constraints.

**Comment by rcsavage** [comment]
Yes, I think a separate chef-zero provisioner would be nice.

**Comment by boldandbusted** [comment]
Howdy. My infrastructures for several clients are chef-zero (i.e. chef-client in local mode). Here's to having this fully supported in Terraform! :+1:

**Comment by jobmiller** [comment]
any updates on this request or workarounds?   I saw this workaround here:  
https://github.com/joewww/ci-cd/blob/master/terraform/main.tf

**Comment by Mwea** [comment]
+1 Is there any considerations about writing a chef-zero provider ? 
I'm really interested into coding this but I doesn't want to waist efforts if there are already stuff that are WIP. I'd rather help what's been started :smiley: 

Else if nothing has been started, I would really appreciate to get any information that could guide me in the dev process. :+1:
