### ISSUE TITLE
sort(), reverse() functions not well documented in Terraform docs

### ISSUE THREAD

**Issue by srishtipmishra** [hashicorp/terraform#26536]
### Terraform Version

```
12.29
```

### Terraform Configuration Files

```terraform
// Copyright (c) 2017, 2020, Oracle and/or its affiliates. All rights reserved.
// Licensed under the Mozilla Public License v2.0
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
provider "oci" {
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  region           = "${var.region}"
  version          = "3.90.1"
}
data "oci_objectstorage_bucket_summaries" "buckets1" {
  compartment_id = var.compartment_ocid
  namespace      = "dxterraformdev"
}
output "buckets" {
  value = data.oci_objectstorage_bucket_summaries.buckets1.bucket_summaries
}
```

### Expected Behavior
User is attempting to order the output list in descending order. 
https://www.terraform.io/docs/configuration/functions/sort.html
https://www.terraform.io/docs/configuration/functions/reverse.html

These pages show an example of only a list as an input to be sorted. It's not intuitive as to how we can use these in files or complex expressions. This documentation could contain more helpful resources/example usage to guide a user better.

**Comment by alisdair** [comment]
`sort` and `reverse` are functions which are used with lists. I'm sorry, but I don't know what you mean by using theses functions "in files or with complex expressions".

However, this doesn't seem like a bug in Terraform or the documentation, so I'm going to close it. I would recommend [posting a question on our Terraform discussion forum](https://discuss.hashicorp.com/c/terraform-core/27), where I'm sure someone might be able to help!
