### ISSUE TITLE
Terraform 0.13.4 seems to fail to properly use a custom provider that is not versioned as 1.0.0

### ISSUE THREAD

**Issue by spkane** [hashicorp/terraform#26545]
### OS Version
```
macOS 10.15.7
```

### Terraform Version
```
Terraform v0.13.4
```

### SDK version
```
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk/v2",
  "Version": "v2.0.4"
}
```

### Relevant provider source code
*N/A*

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    todo = {
      source  = "terraform.spkane.org/spkane/todo"
      versions = ["1.1.0"]
    }
  }
}
```

### Debug Output
*See*: https://gist.github.com/spkane/a0e1a52fc474b7fdb91732185cdabc2b

This seems to be the relevant line from that gist:
```
2020/10/10 23:14:39 [TRACE] providercache.fillMetaCache: error while scanning directory .terraform/plugins: failed to read metadata about .terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64: stat .terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64: no such file or directory
```

### Expected Behavior
It should have used the correct version of the installer which it found, but then didn't use.

### Actual Behavior
```
Initializing provider plugins...
- Finding latest version of terraform.spkane.org/spkane/todo...
- Installing terraform.spkane.org/spkane/todo v1.1.0...

Error: Failed to install provider

Error while installing terraform.spkane.org/spkane/todo v1.1.0: after
installing terraform.spkane.org/spkane/todo it is still not detected in the
target directory; this is a bug in Terraform
```

### Steps to Reproduce
1. `git clone https://github.com/spkane/todo-for-terraform`
2. `cd terraform-provider-todo/`
3. `go build .`
4. `mkdir -p ~/.terraform.d/plugins/terraform.spkane.org/spkane/todo/1.1.0/darwin_amd64` # Edit for Linux/Windows
5. `cp terraform-provider-todo ~/.terraform.d/plugins/terraform.spkane.org/spkane/todo/1.1.0/darwin_amd64/` # Edit for Linux/Windows
6. `cd ../terraform-tests`
7. `TF_LOG=trace terraform init`

### References
*N/A*

**Comment by spkane** [comment]
*Temporary Ugly Workaround*:
`ln -s ~/.terraform.d/plugins/terraform.spkane.org/spkane/todo/1.1.0 ~/.terraform.d/plugins/terraform.spkane.org/spkane/todo/1.0.0`

**Comment by jbardin** [comment]
Hi @spkane 

I'm not sure offhand why it's succeeding when you link to the 1.0.0 version, but the first problem I see is that the configuration isn't valid ([Requiring Providers](https://www.terraform.io/docs/configuration/provider-requirements.html#requiring-providers)). The correct syntax there would be `version = "1.1.0"`. Does that correction fix the installation problem?

**Comment by spkane** [comment]
Hmmm, I think I was mis-led by this Hashicorp blog post while trying to investigate this:
https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13

which has this example:

```
providers {
  customplugin = {
    versions = ["0.1"]
    source = "example.com/myorg/customplugin"
  }
}
```

But after a little more digging I see that this might actually be the format for the `terraform-bundle` command, which looks very similar, but is not quite the same.

https://github.com/hashicorp/terraform/blob/master/tools/terraform-bundle/README.md

That all being said, I still get the same behavior with the version line changed to:
`version = "1.1.0"`
or
`version = "~> 1.1"`

I updated the gist ( https://gist.github.com/spkane/a0e1a52fc474b7fdb91732185cdabc2b ) with the debug output of `terraform init`, plus the HCL that is being used, and the including the file listing that shown where the plugin is installed.

Although the issues could be environmental or a config issue, I think it would be worth looking over the debug output. It is very strange to me that it seems to detect and info version 1.1.0 and then try to use version 1.0.0 for some reason.

**Comment by spkane** [comment]
@jbardin After looking at the updated debug output does this still look like something mi-configured on my end? From all the documentation I am pretty sure that everything is correct, but there still seems to be some issue that is causing terraform to search for `/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64` even though it is clearly `- Installing terraform.spkane.org/spkane/todo v1.1.0...`

```
2020/10/12 17:04:59 [TRACE] providercache.fillMetaCache: error while scanning directory .terraform/plugins: failed to read metadata about .terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64: stat .terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64: no such file or directory
2020/10/12 17:04:59 [WARN] Failed to scan provider cache directory .terraform/plugins: failed to read metadata about .terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64: stat .terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64: no such file or directory
2020/10/12 17:04:59 [TRACE] providercache.Dir.InstallPackage: installing terraform.spkane.org/spkane/todo v1.1.0 from /Users/skane/.terraform.d/plugins/terraform.spkane.org/spkane/todo/1.1.0/darwin_amd64
2020/10/12 17:04:59 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins- Finding terraform.spkane.org/spkane/todo versions matching "1.1.0"...

2020/10/12 17:04:59 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins
2020/10/12 17:04:59 [TRACE] providercache.fillMetaCache: error while scanning directory .terraform/plugins: failed to read metadata about .terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64: stat .terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64: no such file or directory
- Installing terraform.spkane.org/spkane/todo v1.1.0...

Error: Failed to install provider

Error while installing terraform.spkane.org/spkane/todo v1.1.0: after
installing terraform.spkane.org/spkane/todo it is still not detected in the
target directory; this is a bug in Terraform
```

**Comment by apparentlymart** [comment]
Hi @spkane,

From reading that trace log I suspect that you have a leftover dangling symlink to a previous v1.0.0 version of this provider under your `.terraform` directory, which is making the cache directory scanning fail. If that's the cause, then removing the symlink at `.terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64` should fix it, I think.

I think the sequence of events here was that you previously had a 1.0.0 at `~/.terraform.d/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64`, which `terraform init` found and symlinked from `.terraform/plugins/terraform.spkane.org/spkane/todo/1.0.0/darwin_amd64`. You've then subsequently deleted the original 1.0.0 directory, and so that symlink is pointing at a non-existent directory, and so that's causing a failure for the code that scans `.terraform` to see what's already installed.

If my theory is correct here, I think we could improve it for next time by making the directory scanning code (the `getproviders.SearchLocalDirectory` mentioned in the log) handle a "not found" error from that symlink lookup the same way as it would handle the symlink itself not being present: ignore it altogether and consider that version to not be present in the directory. (It should still generate a debug log line to help in noticing that there's a dangling symlink there, though.)

**Comment by apparentlymart** [comment]
(If my theory above is correct then this looks to be the same as #26469.)

**Comment by agseijas** [comment]
Was opening another issue when I found this issue. We have a similar error, here is the Gist with a Dockerfile that reproduces the error we found (linking it if this helps):
https://gist.github.com/agseijas/4a625bc058e0c88991df05735516e6f8

I agree with @apparentlymart , seems to be the symlinks fault.

**Comment by spkane** [comment]
Ok. So it is working now. I do think that the error must of been something in the `.terraform` directory (which never even crossed my mind, since I was doing an init). Testing in a new directory of tf files worked fine.

Oddly I don't recall ever making a symlink in the `.terraform` directory (although this does not mean that I did not as there was a lot of troubleshooting going on). I was mostly messing around with links in the `~/.terraform.d` directory.

 It does seem like some improvements to the scanning code might make this something that can be self-resolved or at least at least more directly point the user to the likely problem.

Thank you for the help. It is much appreciated!
