### ISSUE TITLE
Refactor logging infrastructure to use a structured logger

### ISSUE THREAD

**Issue by davidalpert** [hashicorp/terraform#26546]
### Current Terraform Version
```
Terraform v0.13.1
```

### Use-cases
I have seen several open issues/feature requests related to logging inconsistencies or enhancements:
- https://github.com/hashicorp/terraform/issues/17367 Inconsistent logging structure
- https://github.com/hashicorp/terraform/issues/6468 TRACE level logging when TF_LOG=DEBUG
- https://github.com/hashicorp/terraform/issues/25594 Terraform not logging what particular instance of a module is causing the error
- https://github.com/hashicorp/terraform/issues/22785 `Unreadable module directory` error is not clear for nested modules
- https://github.com/hashicorp/terraform/pull/25086 Support whitelisting log lines via regular expressions

In addition, while building custom terraform providers I have stumbled many times over the proper syntax to write log messages of different levels, or various interpolation strings to capture properties.

I wonder if these merit some investment into improving the logging infrastructure.

### Proposal

I propose refactoring all logging in this package and the `terraform-plugin-sdk` package to use a structured logger which would enable:
- terraform and provider/plugin developers to write log statements more concisely and with structured fields/properties to provide additional context/detail in a standard way
- terraform users and provider/plugin developers to configure the logging destination, format, and level in a standard way

I have come across a number of existing structured logging packages which might be seen as enhancements over the standard go `log` package:
- [apex/log](https://github.com/apex/log)
- [zerolog](https://github.com/rs/zerolog)
- [logrus](https://github.com/sirupsen/logrus)
- [zap](https://github.com/uber-go/zap)

### References
- #17367 Inconsistent logging structure
- #6468 TRACE level logging when TF_LOG=DEBUG
- #25594 Terraform not logging what particular instance of a module is causing the error
- #22785 `Unreadable module directory` error is not clear for nested modules
- #25086 Support whitelisting log lines via regular expressions

**Comment by davidalpert** [comment]
I have been experimenting in a custom provider and related acceptance tests with using the `apex/log` package and wiring it up to respect `TF_LOG` as the log level and `TF_LOG_PATH` as the logfile destination; it's working so far.

**Comment by jbardin** [comment]
Hi @davidalpert 

Thanks for bringing this up. Refactoring logging throughout Terraform is definitely something we are planning to do.
As for the implementation, our tools use [hclog](`https://github.com/hashicorp/go-hclog) internally, which is already supported in the plugin system, and is likely the package which will be incorporated into Terraform.

Thanks!

**Comment by jbardin** [comment]
The current master branch is now using `hclog` throughout.
While the plugins will require some updated to send the correct log levels in many cases, they are handled correctly within core. 

Closed by #26632, #26665, #26685 and #26694
