### ISSUE TITLE
Feature request: Support inter-output variable references

### ISSUE THREAD

**Issue by peterpramb** [hashicorp/terraform#26542]
### Current Terraform Version
```
Terraform v0.13.4
```

### Use-cases
I recently discovered that it's currently not possible to reference output variables from other outputs within the same module. This leads to unnecessary code duplication in special cases.

Please consider the following (hopefully not too simplified) example:
```terraform
resource "null_resource" "samples" {
  for_each = { "test1" = 1, "test2" = 2 }
}

output "samples" {
  description = "List of all sample objects."
  value = [
    for name, sample in null_resource.samples : merge(sample, {
      "name" : name
      "key"  : "value"
    })
  ]
}

output "sample_ids" {
  description = "Map of all sample objects indexed by ID."
  value = {
    for name, sample in null_resource.samples : sample.id => merge(sample, {
      "name" : name
      "key"  : "value"
    })
  }
}

output "sample_names" {
  description = "Map of all sample objects indexed by name."
  value = {
    for name, sample in null_resource.samples : name => merge(sample, {
      "name" : name
      "key"  : "value"
    })
  }
}
```

### Attempted Solutions
Initially I tried to reference the output `samples` directly, which would have allowed for maintaining the `merge` code above in just one place:
```terraform
resource "null_resource" "samples" {
  for_each = { "test1" = 1, "test2" = 2 }
}

output "samples" {
  description = "List of all sample objects."
  value = [
    for name, sample in null_resource.samples : merge(sample, {
      "name" : name
      "key"  : "value"
    })
  ]
}

output "sample_ids" {
  description = "Map of all sample objects indexed by ID."
  value = {
    for sample in output.samples : sample.id => sample
  }
}

output "sample_names" {
  description = "Map of all sample objects indexed by name."
  value = {
    for sample in output.samples : sample.name => sample
  }
}
```
But unfortunately this fails:
```
Error: Reference to undeclared resource

  on main.tf line 18, in output "sample_ids":
  18:     for sample in output.samples : sample.id => sample

A managed resource "output" "samples" has not been declared in the root
module.


Error: Reference to undeclared resource

  on main.tf line 25, in output "sample_names":
  25:     for sample in output.samples : sample.name => sample

A managed resource "output" "samples" has not been declared in the root
module.
```

Using `locals` as a workaround works indeed, but makes (in my opinion) the code harder to read/maintain, especially when splitted across multiple files:
```terraform
locals {
  output_samples = [
    for name, sample in null_resource.samples : merge(sample, {
      "name" : name
      "key"  : "value"
    })
  ]
}

resource "null_resource" "samples" {
  for_each = { "test1" = 1, "test2" = 2 }
}


output "samples" {
  description = "List of all sample objects."
  value       = local.output_samples
}

output "sample_ids" {
  description = "Map of all sample objects indexed by ID."
  value = {
    for sample in local.output_samples : sample.id => sample
  }
}

output "sample_names" {
  description = "Map of all sample objects indexed by name."
  value = {
    for sample in local.output_samples : sample.name => sample
  }
}
```
There might also be cases where `locals` can't be used as a workaround.

### Proposal
Support for referencing output variables from other outputs within the same module, to prevent unnecessary code duplication for complex outputs:
```terraform
output "sample" {
  value = output.other_output.value
}
```

### References
This is somewhat releated to #17144, which proposes outputs to be generally accessibly within a module, but was created for 0.11 (not sure if it is still considered for future implementation).

**Comment by Galser** [comment]
Peter, maybe not that straightforward applicable to your request, but  I think that's exactly the situation where usage of [local variables](https://www.terraform.io/docs/configuration/locals.html) can be beneficial. Have you considered this?

**Comment by peterpramb** [comment]
Yes, this is also a workaround mentioned in #17144, but does not really help in making the code more maintainable, especially when the code is splitted across multiple files.

**Comment by jbardin** [comment]
Hi @peterpramb 

Thanks for the added context. We can continue to track this in the original issue #17144

Thanks!
