### ISSUE TITLE
Destroying resources failure (Intermittent)

### ISSUE THREAD

**Issue by netvisao** [hashicorp/terraform#2656]
Logs to support

```
[0m[1maws_elb.####: Destroying...[21m[0m
[0m[1maws_elb.####: Error: 1 error(s) occurred:

* Error deleting ELB: Post https://elasticloadbalancing.us-east-1.amazonaws.com/: EOF[21m[0m
[0m[1maws_launch_configuration.####: Destruction complete[21m[0m
[31mError applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error deleting ELB: Post https://elasticloadbalancing.us-east-1.amazonaws.com/: EOF
```

**Comment by catsby** [comment]
Hey @netvisao – are you able to reliably reproduce this?
I've attempted to do so with an ELB and it seems to work every time. A sample configuration would help me reproduce this, as well as full logs by using `TF_LOG=1` (minus any secret information)

Thanks!

**Comment by netvisao** [comment]
Let me know if this is what you wanted : 
`
# Create a new load balancer
resource "aws_elb" "terraform-app-elb" {
  name = "${var.app_name}-${var.app_env}-app-elb"
  security_groups = ["${var.elb_security_group}"]
  subnets =  ["${split(",", var.app_subnet)}"]
  internal = "true"

  listener {
    instance_port = 11400
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }

  health_check {
    healthy_threshold = 2
    unhealthy_threshold = 2
    timeout = 3
    target = "HTTP:1140/trafficcontrol/TrafficControlHTTPHeaderServlet"
    interval = 30
  }
  cross_zone_load_balancing = true
  provisioner "local-exec" {
        command = "echo '#!/bin/bash -v' > web_userdata_updated.sh;echo 'echo ${aws_elb.terraform--app-elb.dns_name} > /tmp/backenddetails.txt' >> web_userdata_updated.sh;cat web_userdata.sh >> web_userdata_updated.sh"
  }
`

PS: it is slightly redacted. Thanks !

**Comment by catsby** [comment]
Hey @netvisao – sorry for the silence here. I've recently revisited this issue and still can't reproduce it. I'm assuming this was an issue with the SDK at this time, which has since been resolved.

If you can still reproduce this, please let me know!
Thanks!
