### ISSUE TITLE
Terraform, SSH handshake failed

### ISSUE THREAD

**Issue by mmastro94** [hashicorp/terraform#2658]
so i'm currently using packer to build an ubuntu ami through AWS. After which i'm using terraform to launch and provision the instance. I'm running in to problems when I try provisioning within terraform. When it attempts to establish a connection to the server it will hang up and repeatedly print out: 

    aws_instance.web (remote-exec): Connecting to remote host via SSH...
    aws_instance.web (remote-exec):   Host: 54.210.77.32
    aws_instance.web (remote-exec):   User: ec2-user
    aws_instance.web (remote-exec):   Password: false
    aws_instance.web (remote-exec):   Private key: true
    aws_instance.web (remote-exec):   SSH Agent: true

after which it will eventually fail with the error:

    Error applying plan:
    
    1 error(s) occurred:
    
    * ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
    
    Terraform does not automatically rollback in the face of errors.
    Instead, your Terraform state file has been partially updated with
    any resources that successfully completed. Please address the error
    above and apply again to incrementally change your infrastructure.

Upon further investigation it appears that the server is looking for an ed25519 security key when i'm providing a rsa key.

What strikes me as being particularly odd is that I am able to SSH manually through the terminal. However, when I attempt to do the exact same thing through terraform to do some provisioning it will fail. 

Heres the .json file i'm calling with packer for reference, this step works perfectly fine. 

    {
      "variables": {
            "aws_access_key":       "${var.access_key}",
            "aws_secret_key":       "${var.secret_key}",
            "name":                 "chat",
            "version":              "1",
            "source_ami":           "ami-d05e75b8",
            "service":              "chat",
            "project":              "devops",
            "packer_build_number":  ""
    
      },
      "builders": [
        {
            "type":                         "amazon-ebs",
            "ami_name":                     "packer-chat {{timestamp}}",
            "source_ami":                   "{{user `source_ami`}}",
            "access_key":                   "{{user `aws_access_key`}}",
            "secret_key":                   "{{user `aws_secret_key`}}",
            "region":                       "us-east-1",
            "instance_type":                "t2.micro",
            "ssh_username":                 "ubuntu",
            "ssh_keypair_name":             "MyKey",
            "ssh_private_key_file":         "${var.key_path}",
            "tags":                         {
              "service":            "{{user `service`}}",
              "project":            "{{user `project`}}",
              "createdTime":        "{{isotime \"20060102 15:04:05 MST\"}}",
              "packerBuildNumber":  "{{user `packer_build_number`}}"
            }
    
        }
      ],
      "provisioners": [
        {
    	  "type": "shell",
          "execute_command": "echo 'vagrant'|sudo -S sh '{{.Path}}'",
          "scripts": [
    			"shCode/node_chat_script.sh"
          ]
        }
      ]
    }

Here's the terraform (.tf) file where I'm running in to problems:

    provider "aws" {
    	region     = "us-east-1"
      access_key = "${var.access_key}""
    	secret_key = "${var.secret_key}""
    }
    
    resource "aws_instance" "rhel-ami" {
        ami = "ami-710bc51a"
        instance_type = "t2.micro"
        key_name = "MyKey"
    }
    
    resource "aws_instance" "web"{
     
        connection={
            user="ubuntu"
            key_file="${var.key_path}""
        }
        ami = "ami-7b0ec010"
        instance_type = "t2.micro"
        key_name = "MyKey"
        provisioner "remote-exec" {
            inline = [
            "/usr/bin/nodejs /Documents/chat-example/index.js &",
            "sudo apt-get -y install google-chrome-stable",
            "google-chrome 'http://172.31.29.248:3000/'"
            ]
        }
    }

My main goal with the provisioning is to run a node.js script that starts a local chat server on that ami. I have everything in place to allow that to happen from the provisioning I did in my .json file but I can't seem to get terraform to successfully ssh in to run the final few commands. 

Thank you in advanced for any help! hopefully it's a silly mistake on my part.

**Comment by phinze** [comment]
Hi @mmastro94 - not a silly mistake! It's a bug introduced with the SSH Proxy support in 0.6 - the details are in #2614. The good news is (a) a fix is already in `master`, and (b) you can work around it by adding `agent = false` to your connection block.

**Comment by bikbajwa** [comment]
I have agent = false in my connection block but I still get the ssh handshake failure :frowning:

**Comment by phinze** [comment]
@bikbajwa can you open a fresh issue with your Terraform version and steps to reproduce? Then we can take a look and figure out what's happening in your setup. :+1:

**Comment by chandankumarpathak** [comment]
Hi 

provisioner "remote-exec" in terraform v 0.7.7 gives below error.
* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

Look like time out error as it try to do ssh for 5 mint and then spit above error.

aws_instance.Instanc2: Still creating... (4m30s elapsed)
aws_instance.Instanc1 (remote-exec): Connecting to remote host via SSH...
aws_instance.Instanc1 (remote-exec):   Host: 10.*.*.*
aws_instance.Instanc1 (remote-exec):   User: ubuntu
aws_instance.Instanc1 (remote-exec):   Password: false
aws_instance.Instanc1 (remote-exec):   Private key: false
aws_instance.Instanc1 (remote-exec):   SSH Agent: false
aws_instance.Instanc1: Still creating... (4m20s elapsed)
