### ISSUE TITLE
It should be possible to pin the terraform state version.

### ISSUE THREAD

**Issue by richardj-bsquare** [hashicorp/terraform#26581]
### Current Terraform Version

*any* - 'Inadvertently' upgrading from one version of Terraform to another, so any version basically.

```
...
```

### Use-cases

The current state is, say terraform 0.12.29 state and your CI/CD system is running said version.

An engineer needs to workaround a terraform deployment issue by tainting or removing the state.

The unfortunate engineer downloads a later version of Terraform and proceeds to taint or remove state.

The state is now upgraded to the version they downloaded.

The CI/CD now fails since it is running an older version of Terraform than the engineer ran on the state.

### Attempted Solutions

Nothing comes to mind.

### Proposal

Provide a mechanism that allows the state to be locked to a given version or version specifier, such that the above cannot happen. The result should be an error and an appropriate message about choosing the right terraform version.

**Comment by remilapeyre** [comment]
Hi @richardj-bsquare, have you tried specifying a required Terraform version in your code: https://www.terraform.io/docs/configuration/terraform.html#specifying-a-required-terraform-version?
