### ISSUE TITLE
Variables in provider and backend blocks

### ISSUE THREAD

**Issue by adduty** [hashicorp/terraform#26592]
### Current Terraform Version

```
0.13.4
```

### Use-cases

Some people use separate AWS accounts (unified under a single AWS organization) for prod, dev, etc. When using this with Terraform workspaces, it would be helpful to be able to use variables in the provider block in order to reference the appropriate AWS credentials profile for each workspace. Also, since bucket names must be unique, it would also help to be able to use variables in the backend block. For example:

```
provider "aws" {
  profile = var.environment
}

terraform {
  backend "s3" {
    bucket = "administration-${var.environment}"
    ...
  }
}
```
### Attempted Solutions

It is possible to accomplish the same thing by using provider aliases, but this means every resource block must specify the provider, which is cumbersome.

**Comment by apparentlymart** [comment]
Hi @adduty! Thanks for this feature request.

The S3 backend documentation has [a guide on the current suggested approach for working across multiple AWS accounts](https://www.terraform.io/docs/backends/types/s3.html#multi-account-aws-architecture), which may be useful for you in the short term. [Workspaces are not an ideal way to represent separate environments](https://www.terraform.io/docs/state/workspaces.html#when-to-use-multiple-workspaces), but an approach like in the S3 backend guide can make it work with the primitives as they exist today.

**Comment by varnav** [comment]
Hi!

We have a huge discussion about variables in backend block here:

https://github.com/hashicorp/terraform/issues/13022

**Comment by adduty** [comment]
Thank you both very much! I think those resources will help me accomplish what I am trying to do.
