### ISSUE TITLE
v0.13.4 high CPU usage, very slow

### ISSUE THREAD

**Issue by fubar** [hashicorp/terraform#26607]
### Terraform Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.8.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/terraform-providers/mysql v1.9.0
```

### Actual Behavior

Since we upgraded to Terraform v0.13.4, plan and apply have become incredibly slow and CPU usage is frequently sustained at about 300% (on a Macbook Pro quad core i7) with very little progress in CLI output during the plan phase. Our project currently takes 5 minutes to complete the "Refreshing state..." phase, and it then takes about 40 seconds between "Terraform will perform the following actions:" is shown and all actions being output (ending with the "Do you want to perform these actions?" dialog). I don't have numbers for previous versions, but this is a significant slow-down in exec time and increase in CPU usage.

If there are any other details that would help diagnose this, I'd be happy to provide them. Thanks!

**Comment by jbardin** [comment]
Hi @fubar 

There's not much we can do with the information provided. There weren't any major changes between 0.13.3 and 0.13.4, did you change the versions of any providers in that time as well? The trace logs may narrow down which operations are taking the longest to complete, which can be inferred by the timestamps between messages.

**Comment by fubar** [comment]
@jbardin since this is a rather vague issue I know there's not a lot to go on. Trace logs produce several tens of thousands lines of output in our project, so I doubt that would help. However, I just noticed this issue https://github.com/hashicorp/terraform/issues/25889 and the linked bugfix PR https://github.com/hashicorp/terraform/pull/26577 which got packported into 0.13 2 days ago, so I'll wait for the next release and see if that changes anything. Thanks!

**Comment by fubar** [comment]
0.13.5 fixes the issue as hoped.

Everything else being equal, here are the runtimes in our stack:

Terraform v0.13.4
```
0:00 start
1:25 state lock acquired
4:52 plan finished
```

Terraform v0.13.5
```
0:00 start
0:10 state lock acquired
1:10 plan finished
```

I.e. from almost 5 minutes down to 1 minute and 10 seconds.
