### ISSUE TITLE
Terraform cloud doesn't support use of credentials via the instance role.

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform#26620]
### Terraform Version

```
Terraform v0.13.4
```

### Terraform Configuration Files

```terraform
resource "aws_vpc" "main" {
  count       = var.create_vpc ? 1 : 0

  cidr_block       = var.vpc_cidr

  enable_dns_support   = true
  enable_dns_hostnames = true

  tags = local.vpc_tags
}
```

### Debug Output

using TF_LOG=trace didn't produce any different output.

```
admin:~/environment/firehawk-main-rollout/firehawk-main (tf.13) $ terraform apply --auto-approve
Running apply in the remote backend. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

To view this run in a browser, visit:
https://app.terraform.io/app/firehawk/firehawk-main/runs/run-Tr8FAgrtkXoy6HQX

Waiting for the plan to start...

Terraform v0.13.4
Configuring remote state backend...
Initializing Terraform configuration...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

Please see https://registry.terraform.io/providers/hashicorp/aws
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

Please see https://registry.terraform.io/providers/hashicorp/aws
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### Crash Output
See above

### Expected Behavior
The AWS cloud9 instance where terraform was run from doesn't need to use AWS Secret Keys as env vars, since the instance role provides the permissions to launch resources.  This works without terraform cloud without issue, but if you use the terraform cloud provider, this feature isn't available which is my main reason for using cloud9 in the first place.  Expected behaviour would be for terraform cloud to have parity with this behaviour, its a highly beneficial security feature to not have to transfer AWS secret keys by using the role permissions provided to the instance..

### Actual Behavior
Terraform understanadably complains that credentials haven't been provided because the operation is running on another system without the permissions available.

### Steps to Reproduce
1. Start a cloud9 instance
2. login to the IDE.
3. `terraform apply`with anything basic.
4. enable to the terraform cloud backend.
5. `terraform apply` again
6. The above failure will ensue, along with errors about aws region not being defined.

**Comment by alisdair** [comment]
Hi @queglay, thanks for the report.

I'm not sure that I understand what you're hoping to happen here. Because Terraform Cloud is executing remotely, it doesn't have access to the IAM role on the instance where you ran `terraform`. I can't think of any way to achieve this.

If you want to run `terraform` locally, but still use Terraform Cloud to store state, you can [enable "local" execution mode for your workspace](https://www.terraform.io/docs/cloud/workspaces/settings.html#execution-mode). This should hopefully allow you to achieve what you're looking for.

I'm closing this issue because I think the local execution workaround is the best we could do here. If I've misunderstood, please let me know and I'll be happy to reopen.
