### ISSUE TITLE
Notify user of -reconfigure option after failed terraform init

### ISSUE THREAD

**Issue by pwithams** [hashicorp/terraform#26621]
### Current Terraform Version

```
v0.13.4
```

### Use-cases

**End goal:** To be able to easily recognize that the `-reconfigure` option is required to fix an incorrectly configured backend after running `terraform init` without the need to read GitHub issues or the `init` command documentation, and to avoid mistaking it for a bug.

**Problem scenario example:**

1. Create a S3 backend config file with a bucket that does not exist (by accident):
```
terraform {
  backend "s3" {
    bucket = "this-bucket-does-not-exist"
    key    = "example/terraform.tf_state"
    region = "us-east-1"
  }
}
```
Initialization completes successfully, but an error is generated when existing workspaces are fetched.

3. Change bucket name to one that does exist.
4. Rerun `terraform init` to fix the configuration.
This will always fail as the state of the existing backend cannot be fetched due to the invalid bucket name:

```
Error: Error inspecting states in the "s3" backend:
    S3 bucket does not exist
```

### Attempted Solutions

This is the an overview of the usual user response:

1. Double check config file to make sure there are no typos, rerun `terraform init` and repeat. Especially likely if the correct bucket was recently created.
2. Give up and either reset using `rm -rf .terraform/` or discover the `-reconfigure` option via the documentation or GitHub issues.

### Proposal

Add a line to the migration failure error message that notifies the user about the `-reconfigure` option. This has already been mentioned a few times in response to the numerous issues created surrounding this, such as here: https://github.com/hashicorp/terraform/issues/22488#issuecomment-522002336. This would allow the user to realize how the migration logic works and what they need to do to fix their problem without the need to delete cache files, search the documentation, or mistake it as a bug and file another issue.

**Suggestion:**

Change this constant: https://github.com/hashicorp/terraform/blob/b239570abb17fe4609e7c0adadad14b94916a558/command/meta_backend_migrate.go#L463

To include something similar to this:

```
Note: If you are running `terraform init` and your current backend is invalid or
does not exist anymore you should add the `-reconfigure` option to skip the
migration step.
```

Happy to submit a PR.

### References

 - #23532
 - #22488
 - #18011 (contains multiple references to similar issues and a proposal for a more complex solution)

**Comment by jbardin** [comment]
Closed via #28718
