### ISSUE TITLE
Docs on Dockerfile are out of date

### ISSUE THREAD

**Issue by anisjonischkeit** [hashicorp/terraform#26629]
The docs on /Dockerfile point to /scripts/docker-release, but this directory was deleted in #26484.

### Current Terraform Version
NA

### Use-cases

NA
### Attempted Solutions

NA
### Proposal

NA
### References

#26484

**Comment by mildwonkey** [comment]
Thanks for reporting this @anisjonischkeit ! I've updated the comment so that Dockerfile doesn't reference the old build scripts.
