### ISSUE TITLE
aws_dynamodb_table docs are incorrect for local_secondary_index hash_key

### ISSUE THREAD

**Issue by rlister** [hashicorp/terraform#2662]
Here: http://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#local_secondary_index

`local_secondary_index` argument indicates the `hash_key` property to be required. In fact it is required only for GSI, and not permitted (and does not make sense) for LSIs. Terraform correctly errors if it is set. FWIW the awd-sdk docs are slightly misleading (though self-consistent) in this respect also.

**Comment by catsby** [comment]
Fixed in #4147 , thanks!
