### ISSUE TITLE
Our published provider in the registry is loading forever

### ISSUE THREAD

**Issue by DavidGOrtega** [hashicorp/terraform#26636]
Hi,

Apologies if this is not the correct place to rise this issue.

We tried to publish a provider but it's always loading. Never gets totally published. We tried to contact support by email without any luck so far.

![image](https://user-images.githubusercontent.com/414967/96507942-2ca06d80-125a-11eb-856f-178f09ba424c.png)

How we should proceed? Delete the repo? 

Thanks a lot.

**Comment by alisdair** [comment]
Hi @DavidGOrtega, can you specify which provider you're seeing this with?

**Comment by alisdair** [comment]
I've raised this with the Terraform Registry team—if you're still blocked, can you respond with some more details? Hopefully they'll be able to help you out!

**Comment by DavidGOrtega** [comment]
Hi @alisdair, thanks for the support.

[Here](https://github.com/iterative/terraform-provider-iterative) you can find our provider

**Comment by aicarmic** [comment]
@DavidGOrtega we took a look and did find an issue so removed the partially published one. Could you please try publishing again and if you continue to have an issue, please reach out to us via terraform-registry@hashicorp.com and we'll help from there, thanks!
