### ISSUE TITLE
Error: Invalid provider version constraints

### ISSUE THREAD

**Issue by danieladams456** [hashicorp/terraform#26631]
### Terraform Version

```
Terraform v0.14.0-beta1
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.11"
    }
  }

  required_version = ">= 0.14"
}
```

### Debug Output

https://gist.github.com/danieladams456/2a62510f5646fb073647f9e367c68062

### Expected Behavior

terraform init should be able to be run twice.

### Actual Behavior

The second time terraform init runs, it errors. This seems to be due the required_providers using a single version string like "3.11" and it being saved in the lock file as "3.11.\*".

### Steps to Reproduce

1. `terraform init`
2. `terraform init`

### Additional Context
`.terraform.lock.hcl` contents:
```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.11.0"
  constraints = "3.11.*"
  hashes = [
    "h1:J+FDe23QpxhMKYDh9xGrr+9HcWIAkyodIZXvUvuxpDY=",
  ]
}
```
### References

#26524

**Comment by alisdair** [comment]
Thanks for reporting this! I've confirmed the issue.

**Comment by alisdair** [comment]
There's a possible fix for this in #26637, although I'm not completely sure that's the right approach.

One thing to note here is that I don't think Terraform _intentionally_ supports the `major.minor` version constraint that you wrote in your original configuration. This is currently equivalent to writing `major.minor.0`, and if the configuration had included `3.11.0` from the start, I believe this bug would not have been triggered.

With that in mind, a different fix might be to make the version constraint in the original configuration invalid, with a useful diagnostic explaining what the alternatives are.

**Comment by danieladams456** [comment]
As terraform is moving closer to 1.0, is now the time to tighten up on version specifiers since the behavior is not exactly explicit on just major.minor?

**Comment by alisdair** [comment]
Yeah, I think it would be helpful to have a deprecation for version constraints with no operator and fewer than three version segments.
