### ISSUE TITLE
aws_db_subnet_group should allow dots in the name

### ISSUE THREAD

**Issue by bitglue** [hashicorp/terraform#2664]
I have a preexisting configuration with a `aws_db_subnet_group` named `phabricator.prod.paperg.com`. This is perfectly valid as far as AWS is concerned: I'm looking at the RDS web console right now, and there's my subnet group, with dots in the name.

However, attempting to apply this configuration yields an error:

```console
$ awsudo terraform plan
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * aws_db_subnet_group.phabricator: only alphanumeric characters, hyphens and underscores allowed in "name"
```

I'm using terraform built from git master as of now.

```console
$ terraform --version
Terraform v0.5.3-dev (ac270552033edfc984b0ce6911fed5420ed1964d+CHANGES)
```

My `terraform.tfstate` is dated May 27, so I suspect some change since then is responsible.

**Comment by philk** [comment]
underscores are also allowed and worked fine in Terraform 0.5.3

**Comment by radeksimko** [comment]
@philk Underscores have been already [fixed](https://github.com/hashicorp/terraform/issues/2603) and will be allowed again in `0.6.1`, sorry for the glitch between versions, but it's hard to guess limitations which AWS doesn't document.
