### ISSUE TITLE
Offer associate_elastic_ip for resource instance

### ISSUE THREAD

**Issue by TheM0ng00se** [hashicorp/terraform#2666]
It would be beneficial if terraform had the option to allocate and/or associate an elastic IP with an instance. While some still use the classicy-style Public, many want a permanent address for the host. This would solve that.  It would also make needing 'count' under the aws_eip resource unnecessary when provisioning something like a group of proxies or nat instances. 

I have also put in request here as in many cases the eip may be available.

```js
resource "aws_instance" "web-proxy" {
    ...
      request_elastic_ip = true
      associate_elastic_ip = true
    ...
}
```

**Comment by phinze** [comment]
Hi @TheM0ng00se - thanks for the feature request. I'm trying to understand why you'd prefer this to explicitly declaring an `aws_eip` resource. It seems like if we had the booleans you propose, we would lose the declarative nature of the way we currently support EIPs.

```js
resource "aws_instance" "web-proxy" { /* ... */ }
resource "aws_eip" "web-proxy" {
  instance = "${aws_instance.web-proxy.id}"
  // ...
}
```

Can you share a bit more about your motivation?

**Comment by TheM0ng00se** [comment]
Here's an example...there are a number of use cases but first one that pops in my mind. 

I want to terraform VPCs for various accounts and regions. As we know some regions will have a different number of AZs. Also my VPC will interface with 3rd parties that are security conscience so they want to whitelist my IPs.

I can use instance with count to spin up the right number of NAT instances per region dynamically, however I want elastic IPs not public IPs since public IPs can change and elastic's won't (unless you release them to Amazon). If the aws_eip resource supported count, I could use element with splat and count.index to assign the correct number of EIPs to nat instances whether the number was 2 or 3 or 5.

There are other resources we have as well (proxies, virtual routers, etc) that sit in the public VPC subnet that we want elastic IPs for but don't have static counts for.

Yes I could wrap terraform in a script, but one of the things I love is how agile and clean it is so I'd prefer not to... If there's a way of accomplishing this I'm missing, please let me know.

Thanks

**Comment by phinze** [comment]
>  If the aws_eip resource supported count, I could use element with splat and count.index to assign the correct number of EIPs to nat instances whether the number was 2 or 3 or 5.

It does support count! :grinning: The `count` parameter is a meta-parameter available on all resources.

Here's a quick example:

```js
variable "azs" {
  default = "us-east-1a,us-east-1c"
}
resource "aws_instance" "web-proxy" {
  count         = "${length(split(",", var.azs))}"
  instance_type = "t2.micro"
  ami           = "abcd"
}
resource "aws_eip" "web-proxy" {
  count    = "${length(split(",", var.azs))}"
  instance = "${element(aws_instance.web-proxy.*.id, count.index)}"
}
```

**Comment by TheM0ng00se** [comment]
You're right, was able to splat and have it work, I'm mixed about whether the option makes sense under the instance now. On one hand it's quite convenient, on the other hand if you needed to destroy and recreate your instances, the eips would adjust and not be released.

Thanks...
