### ISSUE TITLE
S3 Backend sts_endpoint Requires Protocol

### ISSUE THREAD

**Issue by BrentSouza** [hashicorp/terraform#26676]
Not sure when this change was introduced, but with newer terraform releases, the `sts_endpoint` attribute for an s3 backend now requires specifying the https protocol, e.g `https://sts.us-east-1.amazonaws.com`. 

Previously, one only needed to give the endpoint: `sts.us-east-1.amazonaws.com`

The workaround is simple enough (described below), but I'm reporting this as an issue because the `endpoint` property still works without a protocol specified, so the interface is inconsistent.

### Terraform Version

0.13.4

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {
    bucket       = "foo"
    key          = "foo.state"
    region       = "us-east-1"
    endpoint     = "s3.us-east-1.amazonaws.com"
    sts_endpoint = "sts.us-east-1.amazonaws.com"
  }
}
```

### Expected Behavior

Terraform init succeeds with the above configuration.

### Actual Behavior

```
Initializing the backend...
Error: error configuring S3 Backend: error validating provider credentials: error calling sts:GetCallerIdentity: RequestError: send request failed
caused by: Post "sts.us-east-1.amazonaws.com/": unsupported protocol scheme ""
```

### Steps to Reproduce

1. Configure terraform with an s3 backend
2. Define the `sts_endpoint`
3. Run `terraform init`

### Workaround

You can just add the protocol in the config:

```terraform
terraform {
  backend "s3" {
    bucket       = "foo"
    key          = "foo.state"
    region       = "us-east-1"
    endpoint     = "s3.us-east-1.amazonaws.com"
    sts_endpoint = "https://sts.us-east-1.amazonaws.com"
  }
}
```

**Comment by gdavison** [comment]
This is the behaviour expected by the AWS SDK. Validation was added in #33822
