### ISSUE TITLE
aws_elb only lowercase alphanumeric characters and hyphens allowed in name

### ISSUE THREAD

**Issue by alexintel** [hashicorp/terraform#2670]
Version 0.6.0

Regression from the previous versions.

If AWS ELB name contains UPPER case chars throws this error:

aws_elb.[my_resource]: only lowercase alphanumeric characters and hyphens allowed in "name"

This is a normal scenario where AWS resource names can be UPPER case.

Thanks,
Alex.

**Comment by phinze** [comment]
Sorry for the trouble here - already fixed in #2580 and will come out in 0.6.1
