### ISSUE TITLE
Support complex objects in template_file vars

### ISSUE THREAD

**Issue by sonic1981** [hashicorp/terraform#26718]
### Current Terraform Version

```
Terraform v0.13.4
```

### Use-cases

When adding azure reports using terraform it is often advised to use `template_file`:

> Since the contents of the dashboard JSON can be quite lengthy, use a template file to improve readability:

[Source](https://www.terraform.io/docs/providers/azurerm/r/dashboard.html#using-a-template_file-data-source-or-the-templatefile-function)

Given the complexity of these templates it is often painful to extract out each required individual string to format the template. This results in variables getting passed like:

```
vars = {
    rg_name = azurerm_resource_group.rg.name
    rg_location= azurerm_resource_group.rg.location
  }
```

### Proposal

support the passing of complex objects into templates, e.g.:

```
vars = {
    rg= var.rg
  }
```

and allow these to be consumed in the template as:
```
"value": "/subscriptions/${subscriptionId}/resourceGroups/${rg.name}
```
currently this results in:

> Inappropriate value for attribute "vars": element "rg": string required.

**Comment by alisdair** [comment]
Hi @sonic1981, thanks for filing your issue. I think the issue here is a mixup between the `template_file` data source and the `templatefile` function. The `templatefile` function, introduced in Terraform 0.12, does work with complex objects. Users of Terraform 0.12 and later should be using `templatefile`.

Here's a sample configuration to demonstrate:

main.tf:
```hcl
variable "rg" {
  type    = map(string)
  default = {
    "name" = "foo",
    "location" = "bar",
  }
}

locals {
  dash = templatefile("dash.tpl", { rg = var.rg })
}

output "dash" {
  value = local.dash
}
```

dash.tpl:
```hcl
Name is '${rg.name}' at ${rg.location}
```

Result:

```shellsession
$ terraform apply -auto-approve

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

dash = "Name is 'foo' at bar\n"
```

Does this meet your needs?

**Comment by sonic1981** [comment]
Ah ok. I'm thinking that document is a bit confusing. I might have a go at editing it. Thanks for the info
