### ISSUE TITLE
Terraform Destroy fails on OpenStack due to improper resource destroy order

### ISSUE THREAD

**Issue by kaizoku0506** [hashicorp/terraform#2671]
Running Terraform Destroy against OpenStack will fail if you have used Terraform to build a router, router interface, network, subnet, and floating IPs.  Terraform will destroy VMs, keys, etc. first, but instead of then destroying the floating IPs, it will attempt to destroy the router interface.  This will fail as the floating IP still exists.

```
Error applying plan:

1 error(s) occurred:

* Error deleting OpenStack Neutron Router Interface: Expected HTTP response code [200] when accessing [PUT http://IP_ADDRESS:9696/v2.0/routers/b8ca36f7-b20c-47e6-8742-5ba4472cb523/remove_router_interface], but got 409 instead
{"NeutronError": {"message": "Router interface for subnet 3aa1d3f5-c874-4c9a-a128-d25657faf6a6 on router b8ca36f7-b20c-47e6-8742-5ba4472cb523 cannot be deleted, as it is required by one or more floating IPs.", "type": "RouterInterfaceInUseByFloatingIP", "detail": ""}}
```

**Comment by boernd** [comment]
Why is this issue closed? Not fixed in 0.6.1 as far as I can see?

**Comment by samdunne** [comment]
Still having this issue. It should be reopened.

The issue also affects removing pools from a vip

**Comment by imduffy15** [comment]
Spent a good bit of today looking at this but in the context of VIPs and Pools.

A delete request on a VIP and pool isn't instantly actioned, it is scheduled. The openstack provider doesn't poll to ensure the VIP/Pool hasn't been removed accordingly. By the time we try delete something like the router or a monitor the VIP/Pool hasn't been removed thus failure.

Removal is needed across the whole openstack provider to check where polling is required on delete.

@radeksimko @kaelumania @boernd @samdunne

**Comment by phinze** [comment]
> A delete request on a VIP and pool isn't instantly actioned, it is scheduled. The openstack provider doesn't poll to ensure the VIP/Pool hasn't been removed accordingly. 

@jtopjian sounds like we just need to add some polling in here, yes?

**Comment by jtopjian** [comment]
Hi all,

#3712 might resolve this issue if anyone wants to take a look and give feedback.

**Comment by jtopjian** [comment]
#3712 was just merged. Please let me know if this helps.

**Comment by Fodoj** [comment]
I believe there is still a bug here related to destroying resources that depend on Neutron Ports. I will try to compile and example in next few days.

**Comment by jtopjian** [comment]
@Fodoj Thanks! That would be much appreciated.

**Comment by jtopjian** [comment]
@Fodoj any update on this one? Are you still hitting a bug?

**Comment by Fodoj** [comment]
Yes and no :) I do still have this bug, but it's rather a bug with openstack version I use and I solved it by specifying some dependencies manually in terraform 



Best regards,
Kirill Shirinkin

**Comment by jtopjian** [comment]
OK, sounds good. Similar to #2343, I'm going to close this as #3712 should have fixed this. However, if that's incorrect, please re-open this issue or open a new issue. As well, if there are any other ordering/timing issues with the other resources, please let me know.

**Comment by boernd** [comment]
Hi, fyi just tested with master and my issue during destroy is gone (openstack_networking_router_interface_v2.router-interface: Error deleting OpenStack Neutron Router Interface...).

Thx!
