### ISSUE TITLE
Create an aws ssm association with Target as a resource group. 

### ISSUE THREAD

**Issue by shivansh931** [hashicorp/terraform#26728]
I am trying to add resource group as a target to an association.

This is how it looks like. 

targets {
    key    = "ResourceGroup"
    values = "xyz"
  }

But I am getting an error Error creating ssm association. Invalid Target.

**Comment by alisdair** [comment]
Hi @shivansh931. Unfortunately there is not enough information for us to be able to help investigate what is going wrong here. Please fill out [the full bug report template](https://github.com/hashicorp/terraform/issues/new?labels=bug%2C+new&template=bug_report.md), and try to include as much information as possible.

**Comment by shivansh931** [comment]
### Terraform Version


```
undefinedTerraform v0.12.2

Initializing plugins and modules...
2020/10/28 12:53:19 [DEBUG] Using modified User-Agent: Terraform/0.12.2 TFE/v202005-2
aws_ssm_association.test_association[0]: Destroying... 
aws_ssm_document.test_document[0]: Creating...
aws_ssm_association.test_association[0]: Destruction complete after 0s
aws_ssm_document.test_document[0]: Creation complete after 0s [id=testDocument]
aws_ssm_association.test_association[0]: Creating...

Error: leftover module module.start-patch-deployment in state that should have been removed; this is a bug in Terraform and should be reported

Error: Error creating SSM association: InvalidTarget: Unsupported Target Type

  on ssm.tf line 134, in resource "aws_ssm_association" "test_association":
 134: resource "aws_ssm_association" "test_association" {

```


THIS is how that piece of code looks like:

resource "aws_ssm_association" "test_association" {
  count = "${var.deploy_patch_ssm_automation ? 1 : 0}"
  association_name = "patch_deployment-${var.environment}"
  name  = "testDocument"
  targets {
    key    = "ResourceGroup"
    values = ["${aws_resourcegroups_group.dev_wcfserver[count.index].name}"]
  }
  depends_on = [
    "aws_ssm_document.test_document"
  ]
}


EXPECTED RESULT:

To create  an. association that has a target as a resource group.

**Comment by alisdair** [comment]
From [looking at the AWS docs](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_Target.html), it seems like the only supported value for targets with SSM associations is `InstanceIds`.

If that's not the case, and you're able to confirm it by creating the association outside of Terraform, then this may be an AWS provider bug. If so, [please report the issue on the AWS provider repository](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose).

Either way, this doesn't seem to be a Terraform core bug, so I'm going to close this issue for now.
