### ISSUE TITLE
Migration script

### ISSUE THREAD

**Issue by entropitor** [hashicorp/terraform#26727]
### Current Terraform Version
```
Terraform v0.13.5
```

### Use-cases

  *  Importing resources from multiple branches without deploying 1 branch deleting things imported by the other branch
  *  Previewing diffs without actually importing resources / running state commands

### Attempted Solutions

*    Running terraform import / terraform state ... and coordinating the deploys
*    Running terraform import / terraform state, terraform plan and then terraform state ...

### Proposal
Have the idea of migration scripts which could be part of a terraform program under the terraform HCL key and they are used during `terraform plan` and `terraform apply` which would run right before and after the plan / apply

Running `terraform plan` would do the following:
1. Get the state lock
2. Run the migrations (should only consist of `terraform import` and `terraform state mv` like commands, this could be a DSL, it could potentially also be part of the terraform HCL with a certain key)
3. Run the plan
4. Run the "undo" part of the migrations / restore the backup
5. Release the lock

Running terraform apply would be similar. Except it wouldn't roll back the migration and it would store that it ran the migration in the state file, so it will not re-run and the developer can remove the migration from their program.

### References
- #26364 Same problem, different proposed solution

**Comment by pkolyvas** [comment]
Thanks @entropitor. This falls into the same family of requirements as #9048 (which is linked in #26364)

It's something we're planning on doing but is not the focus of our highest priority work. At the moment we're stabilizing Terraform for its 1.0 release. 

I'll refer specifically to this comment from Martin: https://github.com/hashicorp/terraform/issues/9048#issuecomment-700360009

The highest-level summary of our goals is that actions would be taken by Terraform in HCL using certain "keys"  not unlike what you describe. Once we get close to a proposed solution internally, we'll begin releasing more info and previews for the community. It's still a significant ways off however.
