### ISSUE TITLE
"cannot read property 'match' of null"       i am getting this error while releasing pipeline in Azure Devops.

### ISSUE THREAD

**Issue by naimaloom1** [hashicorp/terraform#26748]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
git repo: https://github.com/naimaloom1/terraformproj.git

```

### Actual Behavior
 i am trying to deploy infrastructure in Azure using  Azure Devops, But i am getting error message in terraform plan,while releasing pipeline. please help me out.

### References

"cannot read property 'match' of null"    i am getting this error while releasing pipeline in Azure Devops.

![Azure devops pipeline](https://user-images.githubusercontent.com/69838717/97588471-86efba00-1a22-11eb-841f-c3251e0e0919.JPG)

![issue](https://user-images.githubusercontent.com/69838717/97515246-ad780b80-19b6-11eb-8d5e-05b3fd8339e9.JPG)

**Comment by alisdair** [comment]
@naimaloom1 Thanks for reporting this. Unfortunately there is not enough information here for us to help figure out what's going wrong. Can you please edit your issue and fill out all of the sections?

**Comment by numewre** [comment]
I faced the same issue specifying "=" with version worked. I have also noticed the same error if there is spacing issue in .tf file. 

  provider "azurerm" {
    version = "=2.33.0"
      features {}
  }

**Comment by naimaloom1** [comment]
@numewre  Thanks Resolved with above steps.!!
