### ISSUE TITLE
Unable to render a particular list element in the terraform template.

### ISSUE THREAD

**Issue by mehulgogri** [hashicorp/terraform#26751]
Hello,

I am unable to render a particular list element in the terraform template.

Terraform version: 0.13.5

Example:
render_template.tf
```
resource local_file template_a {
  file_permission = "644"
  content = templatefile("${path.root}/templates/template_a.tpl", {
    value = ['John', 'Jane', 'Joe']
  })
  filename = "template_a.ini"
}
```

template_a.ini
```
Name is ${value.0}
```

I am getting following error:
**Invalid template interpolation value; Cannot include the given value in a string template**

I tried following variations in the template:
${value.0}
${value[0]}

**Comment by jbardin** [comment]
Hi @mehulgogri 

Your config file syntax is not correct, but after fixing the parsing errors I cam not able to replicate your results. 

```
resource "local_file" "template_a" {
  file_permission = "644"
  content = templatefile("${path.root}/templates/template_a.tpl", {
    value = ["John", "Jane", "Joe"]
  })
  filename = "template_a.ini"
}
```

And the output is `Name is John`.

Both the legacy "dot" syntax and an index expression will work here as well.

Can you double check the file contents and versions you are using here?

Thanks!

**Comment by mehulgogri** [comment]
My bad. The actual issue is if the list/tuple value is empty, then the templatefile function fails with error
 **Invalid index; The given key does not identify an element in this collection value.**

Is there a way that terraform can just render the blank value if the list/tuple is empty?

**Comment by apparentlymart** [comment]
You can use the `try` function to include a fallback value for situations where the first index isn't available:

```
Name is ${try(value[0], "")}
```

Since you found an explanation for your original concern, I'm going to close this issue now. If you have any more follow-up questions, please feel free to start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core)! Thanks.

**Comment by mehulgogri** [comment]
@jbardin Thanks for looking into my issue.
@apparentlymart Thanks for your suggestion. Using the terraform 'try' function inside the template file solved my problem.
