### ISSUE TITLE
Crash while trying to run a provider under delve

### ISSUE THREAD

**Issue by the-maldridge** [hashicorp/terraform#26757]
### Terraform Version

```
$ terraform version
Terraform v0.13.4
```

### Terraform Configuration Files
Crash occurs prior to loading any config files.  For context though, I am running the example file from [here](https://github.com/resinstack/terraform-provider-linuxkit/tree/master/examples/sshd/)

### Debug Output
See crash log below

### Crash Output
https://gist.github.com/the-maldridge/8986cd9b4260034327e02a26ae65ea98

### Expected Behavior
I expected terraform to not crash, and to contact my provider specified by `TF_REATTACH_PROVIDERS`.  As terraform seems to be ignoring this variable, I removed the provider on disk, and this appears to have triggered the crash.

### Actual Behavior
Terraform did not connect to the provider that was started under delve, and instead crashed.

### Steps to Reproduce
I'm not entirely certain what the triggering item is in this crash, as there's very little documentation around debugging a provider (perhaps that's a separate doc bug...).   I believe this can be reproduced by initializing with a provider in the local disk cache, then removing that provider and exporting a reattach configuration to the environment and running terraform.  Terraform won't reconnect, won't fetch a new provider, and will crash.

### Additional Context
The provider in question is known to work with the exception of one bug, which is why I was trying to get it to run under delve.  It is not presently available on the registry due to this bug which can cause persisted data corruption in managed resources.

**Comment by jbardin** [comment]
Hi @the-maldridge 

I have not been able to reproduce this yet, as any attempt to connect to an unmanaged provider incorrectly have resulted in an error returned to the user rather than a crash. The only thing I see that is suspicious in you log output is that the client is being created from `*RPCClient` rather than `*GRPCClient`, but I'm not sure yet how it got to that point. Is the provider being built with the latest version of the plugin sdk?

**Comment by the-maldridge** [comment]
From the `go.mod`: `github.com/hashicorp/terraform-plugin-sdk v1.16.0`  I can update to a newer version of the SDK if you think that's the best course to proceed with troubleshooting.

**Comment by jbardin** [comment]
Thanks @the-maldridge, while updating wouldn't hurt, I believe re-attaching providers did work with that version. I can came back to this and try to reproduce the crash again later, but the next step is to make a reproducible example of the issue.

Thanks!

**Comment by mfranczy** [comment]
@jbardin any update on this? I am facing similar issue, the `TF_REATTACH_PROVIDERS` is ignored by terraform.
Some details about my setup:

go.mod:
```
github.com/hashicorp/terraform-plugin-sdk/v2 v2.2.0
```

tf version:
```
terraform --version
Terraform v0.13.5
```

output with `-debuggable` flag
```
Provider started, to attach Terraform set the TF_REATTACH_PROVIDERS env var:

        TF_REATTACH_PROVIDERS='{"registry.terraform.io/hashicorp/anxcloud":{"Protocol":"grpc","Pid":212966,"Test":true,"Addr":{"Network":"unix","String":"/tmp/plugin538050798"}}}'
```

I exported `TF_REATTACH_PROVIDERS` but it is ignored.

**Comment by jbardin** [comment]
Hi @mfranczy ,

Thanks for the extra info. Do you have a way to replicate the crash seen here? If this is a question about debugging providers, you can probably find more help on the community forums in the [Terrform](https://discuss.hashicorp.com/c/terraform-core), or [Providers](https://discuss.hashicorp.com/c/terraform-providers/31) categories. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by mfranczy** [comment]
@jbardin ok thanks for your input, that was only a question about debugging providers, in my case the binary never crashed.

**Comment by the-maldridge** [comment]
I'm relatively convinced that this is triggered by using the v1 plugin SDK, as after upgrading the SDK terraform no longer crashes and correctly attaches to my plugin.  As I can no longer trigger the original bug I am closing this ticket.
