### ISSUE TITLE
Terraform replace function does not work inside the template file.

### ISSUE THREAD

**Issue by mehulgogri** [hashicorp/terraform#26760]
Terraform replace function does not work inside the template file.

**Terraform version: 0.13.5**

Example:
versions.tf
```
terraform {
  required_providers {
    local = {
      source = "hashicorp/local"
    }
  }
  required_version = ">= 0.13"
}
```

render_template.tf
```
resource "local_file" "template_a" {
  file_permission = "644"
  content = templatefile("${path.root}/templates/template_a.tpl", {
    ips= ["1.2.3.4", "5.6.7.8"]
  })
  filename = "template_a.ini"
}
```
template_a.ini
```
%{ for ip in ips ~}
host-${replace(${ip}, ".", "-")} ansible_host=${ip}
%{ endfor ~}
```

**Expected Result:**
```
host-1-2-3-4 ansible_host=1.2.3.4
host-5-6-7-8 ansible_host=5.6.7.8
```

I am getting the following error message:
**Invalid character; This character is not used within the language.**

**Comment by apparentlymart** [comment]
Hi @mehulgogri,

The reason for this error is that you have not used the correct syntax for the function argument. The `${` symbol is only for switching from literal text mode into expression mode, but your function arguments are already in expression mode so it isn't necessary (or allowed) to use that symbol in that location.

```
%{ for ip in ips ~}
host-${replace(ip, ".", "-")} ansible_host=${ip}
%{ endfor ~}
```

**Comment by mehulgogri** [comment]
@apparentlymart Thanks, it worked.
