### ISSUE TITLE
Dynamic rules for "aws_network_acl" not deleting "removed rule" from terraform.tfvars

### ISSUE THREAD

**Issue by dvaliev** [hashicorp/terraform#26767]
### Terraform Version
```
Terraform v0.13.3
```

### Terraform Configuration Files

`main.tf` 
```terraform
resource "aws_network_acl" "main" {
  for_each = var.vpc-01-nacl
  vpc_id   = "vpc-1234567890"

  dynamic "egress" {
    for_each = var.vpc-01-nacl[each.key].egress
    content {
      rule_no    = element(egress.value, 0)
      action     = element(egress.value, 1)
      from_port  = element(egress.value, 2)
      to_port    = element(egress.value, 3)
      protocol   = element(egress.value, 4)
      cidr_block = element(egress.value, 5)
    }
  }
  dynamic "ingress" {
    for_each = var.vpc-01-nacl[each.key].ingress
    content {
      rule_no    = element(ingress.value, 0)
      action     = element(ingress.value, 1)
      from_port  = element(ingress.value, 2)
      to_port    = element(ingress.value, 3)
      protocol   = element(ingress.value, 4)
      cidr_block = element(ingress.value, 5)
    }
  }

  tags = {
    Name = "main"
  }
}
```
`variables.tf`
```terraform
## [NACL] ##
variable "vpc-01-nacl" {
  description = "List of NACL rules"
}
```
`terraform.tfvars`
```terraform
vpc-01-nacl = {
  "Main-acl" = {
    "ingress" = {
      rule-1  = ["100", "allow", "22", "22", "tcp", "0.0.0.0/0"]
      rule-2  = ["101", "allow", "80", "80", "tcp", "0.0.0.0/0"]
      rule-3  = ["102", "allow", "443", "443", "tcp", "0.0.0.0/0"]
    }
    "egress" = {
      rule-1 = ["100", "allow", "22", "22", "tcp", "0.0.0.0/0"]
      rule-2 = ["101", "allow", "80", "80", "tcp", "0.0.0.0/0"]
      rule-3 = ["102", "allow", "443", "443", "tcp", "0.0.0.0/0"]
    }
}
```

### Expected Behavior
`terraform apply` changing and creating rules as expected but if I remove one of the rules and run `terraform apply` again terraform should remove rule that was deleted in `terraform.tfvars`

### Actual Behavior
When one of the rules is removed (whole line for example "rule-1" deleted in `terraform.tfvars`), `terraform apply` reporting `Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`

### Steps to Reproduce
1. `terraform init`
2. `terraform apply` - Apply will apply rules as expected, if you change rules, changes are as expected as well.
3. Remove one of the rules from either "egress" or "ingress" and run `terraform apply` again. Terraform will not see the change in `terraform.tfvars` file and will report `Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`

-----
I am new to reporting bugs but utilizing terraform for over a year and love it, I am expecting to have a lot of lines of NACL rules thus created this approach with compact style variables. Any thoughts on what am I missing here?

**Comment by dvaliev** [comment]
Everything as commented above, but rules now are being removed. I have upgraded Terraform version to 13.5 and upgraded provider version from "3.11.0" to "3.13.0"
Only problem I am seeing now is that if I remove all rules in ingress or egress after creating they will not be removed, so there should be at least one rule?

**Comment by jbardin** [comment]
Hi @dvaliev 

Due to the way the AWS provider implemented the `ingress` and `egress` functionality, it cannot detect when there is no block present for either of those. The provider however is using a feature that allows those blocks to be assigned as attribute, allowing the use of "for expressions" as well as allowing the assignment of an empty list. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. Issue with the AWS Provider can be filed in their [project repository](https://github.com/terraform-providers/terraform-provider-aws/issues).

Thanks!
