### ISSUE TITLE
Plugins are duplicated outside of TF_PLUGIN_CACHE_DIR

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/terraform#26765]
### Terraform Version

I built terraform from master today.

```
Terraform v0.14.0-dev
13d70844d7638cd12b67f2cd9184458893eb2032
```

### Terraform Configuration Files

To reproduce, create a new directory. Mine was called `test2`, but the name doesn't matter.

```
mkdir test2
cd test2
```

This directory contains main.tf:

```terraform
resource "null_resource" "test" {
}
```

Create another directory at the same level as main.tf.

```
mkdir somewhere
```

Running the following command should cache provider plugin files in `TF_PLUGIN_CACHE_DIR`:

```
$ TF_PLUGIN_CACHE_DIR=somewhere TF_LOG=trace terraform init
```

Instead, plugin cache directories are created in both the working directory, and the specified directory. And they both contain the provider binary.

```
[dakini@dax test2]$ ls -la
total 24
drwxrwxr-x. 4 dakini dakini 4096 Oct 30 16:37 .
drwxrwxr-x. 6 dakini dakini 4096 Oct 30 16:34 ..
-rw-rw-r--. 1 dakini dakini   36 Oct 30 16:37 main.tf
drwxrwxr-x. 3 dakini dakini 4096 Oct 30 16:37 somewhere
drwxr-xr-x. 3 dakini dakini 4096 Oct 30 16:37 .terraform
-rwxrwxrwx. 1 dakini dakini 1002 Oct 30 16:37 .terraform.lock.hcl

[dakini@dax test2]$ du -sh somewhere/registry.terraform.io/hashicorp/null/3.0.0/linux_amd64/terraform-provider-null_v3.0.0_x5 
15M     somewhere/registry.terraform.io/hashicorp/null/3.0.0/linux_amd64/terraform-provider-null_v3.0.0_x5

[dakini@dax test2]$ du -sh .terraform/providers/registry.terraform.io/hashicorp/null/3.0.0/linux_amd64/terraform-provider-null_v3.0.0_x5 
15M     .terraform/providers/registry.terraform.io/hashicorp/null/3.0.0/linux_amd64/terraform-provider-null_v3.0.0_x5
```

### Debug Output

https://gist.githubusercontent.com/dak1n1/2b0c27c0f5dac64ac6e9a4d9b144b02e/raw/120ed08be43f25bd8c5fdb0a57c69d822c253969/gistfile1.txt

### Crash Output

N/A

### Expected Behavior

The plugin cache dir should be used as the sole plugin cache, and `.terraform` should not be duplicated in the current working directory.

### Actual Behavior

The plugin cache was created in both the default location and the specified location.

### Steps to Reproduce

Specify a plugin cache directory and run `terraform init`. See Terraform Config section for details.

### Additional Context

I don't see any environment variables that would have affected this.

```
$ env |grep CACHE
$ env |grep TF_CLI
```

I'm on Fedora 32.

**Comment by alisdair** [comment]
Thanks for reporting this, @dak1n1! I'm unable to reproduce the issue on macOS, although my logs do seem to be the same as yours.

What Terraform should be doing here is installing the plugin to `somewhere`, then symlinking the binary into place in `.terraform/providers`. I'm not familiar with exactly how `du` handles symlinks on Fedora, but could it be following the symlink and reporting its usage? Or have you confirmed that there's no symlink there?

From the log output in your report, there's no sign of the linking process failing as far as I can tell. What's the output of `ls -lR .terraform/providers`? For reference, here's mine:

```shellsession
$ ls -lR .terraform/providers
total 0
drwxr-xr-x  3 alisdair  staff  96  4 Nov 11:54 registry.terraform.io

.terraform/providers/registry.terraform.io:
total 0
drwxr-xr-x  3 alisdair  staff  96  4 Nov 11:54 hashicorp

.terraform/providers/registry.terraform.io/hashicorp:
total 0
drwxr-xr-x  3 alisdair  staff  96  4 Nov 11:54 null

.terraform/providers/registry.terraform.io/hashicorp/null:
total 0
drwxr-xr-x  3 alisdair  staff  96  4 Nov 11:54 3.0.0

.terraform/providers/registry.terraform.io/hashicorp/null/3.0.0:
total 0
lrwxr-xr-x  1 alisdair  staff  101  4 Nov 11:54 darwin_amd64 -> /Users/alisdair/Desktop/repro/26765/somewhere/registry.terraform.io/hashicorp/null/3.0.0/darwin_amd64
```

**Comment by dak1n1** [comment]
oh, I see, one of the directories is a symlink!

```
[dakini@dax 20201106]$ ls -lR .terraform
.terraform:
total 4
drwxr-xr-x. 3 dakini dakini 4096 Nov  6 10:44 providers

.terraform/providers:
total 4
drwxr-xr-x. 3 dakini dakini 4096 Nov  6 10:44 registry.terraform.io

.terraform/providers/registry.terraform.io:
total 4
drwxr-xr-x. 3 dakini dakini 4096 Nov  6 10:44 hashicorp

.terraform/providers/registry.terraform.io/hashicorp:
total 4
drwxr-xr-x. 3 dakini dakini 4096 Nov  6 10:44 null

.terraform/providers/registry.terraform.io/hashicorp/null:
total 4
drwxr-xr-x. 2 dakini dakini 4096 Nov  6 10:44 3.0.0

.terraform/providers/registry.terraform.io/hashicorp/null/3.0.0:
total 4
lrwxrwxrwx. 1 dakini dakini 91 Nov  6 10:44 linux_amd64 -> /home/dakini/work/20201106/somewhere/registry.terraform.io/hashicorp/null/3.0.0/linux_amd64
```

So this shouldn't actually be an issue for disk space. Thanks!
