### ISSUE TITLE
openstack_networking_port_v2 being created incorrectly

### ISSUE THREAD

**Issue by agowa338** [hashicorp/terraform#26770]
### Terraform Version
```
Terraform v0.13.5
+ provider registry.terraform.io/-/null v2.1.2
+ provider registry.terraform.io/-/openstack v1.32.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.32.0
```

### Terraform Configuration Files

Full terraform at: https://github.com/agowa338/openstack-k8s/blob/54534f6272dc1322bc4d3643a614d22fa8f3d690/40-node-network-ports.tf

```terraform
resource "openstack_networking_port_v2" "k8s-worker-port" {
  count          = var.worker-node-count
  name           = "k8s-worker-port_${count.index}"
  network_id     = openstack_networking_network_v2.network_k8s.id
  admin_state_up = true
  no_fixed_ip    = true
}

resource "openstack_networking_port_v2" "k8s-master-port" {
  count          = var.master-node-count
  name           = "k8s-master-port_${count.index}"
  network_id     = openstack_networking_network_v2.network_k8s.id
  admin_state_up = true
  no_fixed_ip    = true
}
```

Edit:
My configuration may have been a bit implicit (that was what I found in the internet for doing ipv6 only interfaces). I changed some sections to a more explicit definition and now it appears to be working. I'll leave this issue open, as the race condition is really not intuitive and either way the behaviour of terrafrom in this case is wired.
This is the diff of the commit that avoids the error (by doing it more strict): https://github.com/agowa338/openstack-k8s/commit/6004d75a9b08213b91c3ff703be48e10dbada1b6#diff-378cf4d7b2be4e774ff52a3e7e7867d18ffd260d758766d0be9b876f69ee975a

### Debug Output
https://gist.github.com/agowa338/b94fddfbbb8b21f3307962a25d525f76
(log is from 0.13.4, but issue still occurs in 0.13.5)

### Crash Output
no crash

### Expected Behavior
network port being created and an ip address being assigned through openstack.

### Actual Behavior
Race condition some of the ports do not get an ip address assigned and terraform is not aware of that. Even when ran again it thinks the port is fine and therefore fails later down the line when the port should be used.
It appears, that manually deleting (`terraform taint openstack_compute_instance_v2.FAILED_PORT_NAME[FAILED_PORT_ID]`) the defective ports and rerunning terraform may create it correctly (if still not delete again and run again. Until now it works the 2nd or 3rd time it is created).

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @agowa338 

This appears to be an issue with the openstack provider, which is not part of our organization can cannot be migrated automatically. You can file issues with that provider directly in their [GitHub repository](https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues).

Thanks!
