### ISSUE TITLE
Flexible engine elb resource timeout although it is created, because it take longer than 4 minutes to be created.

### ISSUE THREAD

**Issue by amyounis** [hashicorp/terraform#26778]
### Terraform Version
0.13.5

### Terraform Configuration Files
```
provider "flexibleengine" {
  user_name   = var.user_name
  password    = var.password
  domain_name = var.domain_name
  tenant_name = var.tenant_name
  auth_url    = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3"
  region      = var.region
  version     = "~> 1.16"
}

.
.
.

resource "flexibleengine_elb_loadbalancer" "elb_2" {
  count = var.enable_autoscaling ? 1 : 0
  name              = "rancher-elb"
  type              = "Internal"
  description       = "rancher elb"
  vpc_id            = flexibleengine_vpc_v1.vpc_1.id
  security_group_id = flexibleengine_networking_secgroup_v2.secgroup_2.id
  vip_subnet_id     = flexibleengine_vpc_subnet_v1.subnet_1.id
  az                = "eu-west-0a"
  admin_state_up    = true
}
.
.
.
```

### Debug Output
https://gist.github.com/amyounis/aa9107bef72945cff75d127ef6d31173

### Expected Behavior
create elb resource and continue

### Actual Behavior
the elb creation request is sent then terraform will query the status of the creation job for about 4 minutes then no queries sent after that. and although the elb is actually created, the terraform will not know and after sometime (depending on timeouts settings) it will give the timeout error

### Additional Context
other resources (like rds) take long time to be created but it is working OK and it doesn't behave the same as elb.
also, elb resource with type "External" (meaning it has a public IP) like this:
resource "flexibleengine_elb_loadbalancer" "elb_1" {
  name              = "k8s-workers-elb"
  type              = "External"
  bandwidth         = flexibleengine_vpc_eip_v1.eip_nat[1].bandwidth.0.size
  description       = "kubernetes workers elb"
  vpc_id            = flexibleengine_vpc_v1.vpc_1.id
  vip_address       = flexibleengine_vpc_eip_v1.eip_nat[1].publicip.0.ip_address
  admin_state_up    = true
}
is working OK and it is created without a problem !!!

**Comment by jbardin** [comment]
Hi @amyounis 

This appears to be an issue withe a provider called [`flexibleengine`](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues).
We only can track issues for Terraform itself in this repo, I suggest you file an issue with that project in their GitHub repository.

Thanks
