### ISSUE TITLE
Unable to run double simultaneous for loop inside terraform template

### ISSUE THREAD

**Issue by mehulgogri** [hashicorp/terraform#26787]
Unable to run double simultaneous for loop inside terraform template. Not sure if my syntax is correct or not for what I am trying to achieve.

**Terraform version: 0.13.5**

Example:
versions.tf
```
terraform {
  required_providers {
    local = {
      source = "hashicorp/local"
    }
  }
  required_version = ">= 0.13"
}
```

render_template.tf
```
resource "local_file" "template_a" {
  file_permission = "644"
  content = templatefile("${path.root}/templates/template_a.tpl", {
    ips= ["ip1", "ip2"]
    hostnames=["hostname1", "hostname2"]
  })
  filename = "template_a.ini"
}
```

template_a.ini
```
%{ for ip, hostname in ips, hostnames ~}
${hostname} ansible_host=${ip}
%{ endfor ~}
```
Expected Result:
**host1 ansible_host=ip1
host2 ansible_host=ip2**

I am getting the following error message:
**Extra characters in for marker; Expected a closing brace to end the sequence, but found extra characters..**

**Comment by alisdair** [comment]
Hi @mehulgogri. This seems more like a usage question than a bug report. We use GitHub issues to track bugs and feature requests, and so this is not a good place to ask questions. [Please try asking on the community Terraform forum](https://discuss.hashicorp.com/c/terraform-core/27), explaining what you're trying to do, and hopefully someone will be able to help!
