### ISSUE TITLE
New ignore_changes validation is somewhat awkward in 0.14

### ISSUE THREAD

**Issue by astorath** [hashicorp/terraform#26790]
New ignore_changes validation prevents some reasonable use cases. Consider the following: I want to create a google disk. I don't want to reference disk snapshot for it:

* If I recreate the disk from scratch - I don't need any snapshot
* I want to be able to recreate the disk from backup snapshot outside of terraform

With new ignore_changes validation I have to define some snapshot in this case (`snapshot = null` won't do). 

### Terraform Version
```
Terraform v0.14.0-beta2
+ provider registry.terraform.io/hashicorp/google v2.12.0
+ provider registry.terraform.io/hashicorp/google-beta v2.12.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Terraform Configuration Files
```terraform
resource "google_compute_disk" "vm-disk" {

  name = "name"

  size = 10
  type = "pd-standard"

  lifecycle {
    ignore_changes  = [snapshot]
  }
}
```

### Expected Behavior

The config should work.

### Actual Behavior

```
Error: Cannot ignore argument not set in the configuration

  on ../modules/gce-vm/disks.tf line 19, in resource "google_compute_disk" "vm-disk":
  19:     ignore_changes  = [snapshot]

The ignore_changes argument is not set in the configuration.
The ignore_changes mechanism only applies to changes within the configuration,
and must be used with arguments set in the configuration and not computed by
the provider.
```

The config should work.

### References
https://github.com/hashicorp/terraform/commit/7fa4c00d1ae6d67b6a28e8bc5dfc17244c970f6e

**Comment by jbardin** [comment]
Hi @astorath 

I agree that this is more awkward than we'd like when trying to prevent external changes from impacting the configuration. That particular validation has been rolled back for now in 0.14 with #26825

Thanks!
