### ISSUE TITLE
Site Configurations Displayed In Console App Services / Function App- Terraform Plan

### ISSUE THREAD

**Issue by chchadha** [hashicorp/terraform#26800]
When executing Terraform Plan command, site configurations for azurerm_function_app and azurerm_app_service, the site configurations are exposed when creating a client secret for the Azure AD Application. This causes an issue when automating processes as secrets are exposed in plain text.

site_credential 
{
 password = "..." (exposed in logs) 
 username = "...."
}

**_Repro Steps:_**

resource "random_password" "example" {
  length  = 32
  special = true
}

resource "azuread_application_password" "example" {
  application_object_id = azuread_application.example.id
  value                 = random_password.example.result
  end_date_relative     = "17520h" #expire in 2 years
}

resource "azurerm_app_service" "example" {    //issue can be replicated for azurerm_function_app
  ../configs../
  [site configurations are displayed for this resource]
}

**Comment by romeomorcia** [comment]
@chchadha The solution to your issue is implemented in the beta version [0.14.0-beta2](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-beta)

you need also to add this to your configuration file.

```
terraform {
  experiments = [provider_sensitive_attrs]
}  
```

**Comment by alisdair** [comment]
Hi @chchadha, thanks for reporting this! As @romeomorcia helpfully pointed out, hiding sensitive resource attributes in the plan output is part of the upcoming 0.14 release. You can try it out in the 0.14.0-beta2 release: [more details on our discussion forum here](https://discuss.hashicorp.com/t/terraform-v0-14-beta-testing/15752). I believe this will solve your issue, so I'm going to mark this closed for now.
