### ISSUE TITLE
Need top level aws_eip_association so Terraform can manage existing EIPs

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2680]
Given that the purpose of EIPs are to be able to keep and associate/dissociate with instances, I wonder if it makes sense for terraform to support that too, rather than just creating and destroying EIPs themselves.

For example when destroying and creating a terraform configuration involving EIPs, they can destroy and create the actual EIPs, resulting in new EIPs. This means that I have to change DNS records, anything external with IP addresses in etc. Obviously I could use Route53 or similar within terraform to update DNS records.

I wonder if an option on aws_eip called "associate_only = true", with "preferred_address = x.x.x.x" could instead associate a pre-allocated EIP with an instance (and dissociate it on destroy), failing to do either if it was associated already with a different resource. That way the EIPs could be maintained in the meantime resulting in less external changes.

Not sure if this fits with the terraform usecase, but thought I'd raise a WBNI anyway.

**Comment by phinze** [comment]
Yep I think we could model this as we've done elsewhere with a resource like `aws_eip_association`.

Then using #2275 we can rework the `instance` attribute of `aws_eip` to just be sugar for an association.

Tagging as an enhancement - let me know if this strategy makes sense to you. :+1:

**Comment by gtmtech** [comment]
Yeah that sounds like a good approach :+1:

**Comment by antonosmond** [comment]
+1 for this - so currently is there any workaround for associating an existing eip with an instance?

**Comment by inkblot** [comment]
I would also like to attach an existing EIP to either an `aws_instance` or to an `aws_network_interface` (related, I would also like to invert terraform's handling of the relationship between `aws_network_interface` and `aws_instance`: #3105). In my case, the EIP in question is one that I have hard-coded into puppet hiera data for configuring an IPSec tunnel, but this feature would be necessary in at least a couple of other situations I can think of:

1. Amazon has "blessed" a specific EIP with special privilege (e.g. unlimited outbound TCP 25) and dynamic create/destroy of the EIP would drop this privilege. This is a real thing, by the way. I've seen it!
2. Third parties are doing source-based access control from a specific EIP and dynamic create/destroy would require a configuration change with those third parties.
3. Remote devices are configured to interact with a specific EIP and for a variety of reasons it might be difficult or impossible to reconfigure them after a dynamic create/destroy.

**Comment by mrwilby** [comment]
+1 for this. Doable in Cloud-formation but was surprised to see this pattern is not supported in terraform. Can't think of a workaround either as the current EIP code assumes ownership of any EIP. 

As per above, we need an "aws_eip_association" or similar structure that binds an instance to an EIP without requiring creation of the EIP at the same time..

**Comment by gtmtech** [comment]
Any thoughts from the collaborators about this? Still having to do weird things to maintain our EIPs in the meantime

**Comment by phinze** [comment]
Still seems like a top level `aws_eip_association` is still worth doing from here. Updating title to reflect that more directly.

**Comment by davidhoyt** [comment]
Need exactly this in order to break what terraform thinks is a cycle.

**Comment by jkinred** [comment]
This is important functionality for us as we have Elastic IPs whitelisted with remote API's and such. Often we will allocate EIP's at the beginning of a project which are then communicated elsewhere and can't be changed without major disruption.

This will allow us to create them initially with `prevent_destroy` and later allocate them when we actually provision the infrastructure.

**Comment by jkinred** [comment]
I've got a working `aws_eip_association` resource in #5236. The resource can currently associate an EIP based on allocation id and instance id.

Will work on feature parity with the AWS API in the next week or so.

**Comment by girisreenivas** [comment]
looking forward to seeing this merged in - thanks!

**Comment by jkinred** [comment]
Moved the https://github.com/hashicorp/terraform/pull/5236 PR out of WIP for anyone watching the progress of this :).

**Comment by stack72** [comment]
Hi all, 

I am delighted to say that the work by @jkinred has been merged and will be available in Terraform 0.6.16

Thanks a bunch @jkinred!! :)

P.
