### ISSUE TITLE
RDS Instance Security Groups

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform#2681]
Hi

I just built TF from source (Terraform v0.6.1-dev (0dc0cff14d714ff6976c7cb38f3ed8da41b9afca)) and I am trying to provision an RDS instance. I have the following code:

```
resource "aws_security_group" "rds" {
  name = "rds-sg"
  description = "RDS Security Group"
  vpc_id = "${aws_vpc.default.id}"

  ingress {
    from_port = 3306
    to_port   = 3306
    protocol  = "tcp"
    security_groups = ["${aws_security_group.node.id}"]
  }

  ingress {
    from_port = 5432
    to_port   = 5432
    protocol  = "tcp"
    security_groups = ["${aws_security_group.node.id}"]
  }

  egress {
    from_port = "0"
    to_port = "0"
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags {
    Name = "RDS Instance"
  }
}

resource "aws_db_subnet_group" "mysql" {
    name = "mysql-sng"
    description = "DIGIT Private Subnets"
    subnet_ids = ["${aws_subnet.primary-private.id}","${aws_subnet.secondary-private.id}","${aws_subnet.tertiary-private.id}"]
}

resource "aws_db_instance" "mysql" {
    identifier = "mysql"
    allocated_storage = 60
    storage_type = "gp2"
    engine = "mysql"
    engine_version = "5.6.22"
    instance_class = "db.t2.medium"
    name = "mum"
    username = "myuser"
    password = "sdadfsndvoiw"
    db_subnet_group_name = "${aws_db_subnet_group.mysql.name}"
    parameter_group_name = "default.mysql5.6"
    vpc_security_group_ids = ["${aws_security_group.rds.id}"]
    apply_immediately = true
    multi_az = true
    port = 3306
    publicly_accessible = false
    snapshot_identifier = "rds:2015-07-10-08-18"
}
```

All works except the fact that the Security Group doesn't get added to the RDS instance until i run the terraform apply a second time

Paul

**Comment by jedineeper** [comment]
Hi Paul, 

Can you post the stdout from your plan/apply(s)?

**Comment by stack72** [comment]
This has not happened since - this may have been an issue on my end

**Comment by tehnorm** [comment]
We seem to be seeing something similar now. The one key might be we are restoring from a snapshot_identifier has anyone else seen this?

**Comment by pinterl** [comment]
If Terraform times out during the RDS instance creation, the security group is not set in the RDS instance. My solution is to set the timeout in the aws_db_instance resource. When I launch a multi-az RDS instance from a snapshot, the process can take more than 55 minutes.
 
```
resource "aws_db_instance" "default" {
...
  timeouts {
    create = "120m"
    delete = "120m"
  }
...
}
```

**Comment by lazyfunctor** [comment]
I ran into thus problem even without the RDS instance timeout! I think it should at least flag an error when it fails to associate a security group to the instance instead of failing silently.
