### ISSUE TITLE
0.13.5: unable to import if a variable references for_each module instance

### ISSUE THREAD

**Issue by zarnovican** [hashicorp/terraform#26824]
### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/local v2.0.0
```

### Terraform Configuration Files

`foo/main.tf`:
```terraform
output "foo_output" {
  value = "foo"
}
```

`main.tf`:
```terraform
locals {
  foo1_output = module.foo["foo1"].foo_output
}

module "foo" {
  source   = "./foo"
  for_each = toset(["foo1"])
}

# this resource is unrelated to the problem
# it is here just to show rm+import
resource "local_file" "foo2" {
  content  = ""
  filename = "foo2.txt"
}
```

### Expected Behavior

Import shouldn't fail because of `module.foo["foo1"].foo_output`

### Actual Behavior

```bash
$ terraform_0.13.5 import local_file.foo2 foo2
local_file.foo2: Importing from ID "foo2"...

Error: resource local_file doesn't support import



Error: Invalid index

  on /home/zarnovic/tmp/for_each/main.tf line 2, in locals:
   2:   foo1_output = module.foo["foo1"].foo_output
    |----------------
    | module.foo is object with no attributes

The given key does not identify an element in this collection value.
```

Import of "foo2" resource is failing for reasons related to "foo1". `terraform import` cannot handle ` foo1_output = module.foo["foo1"].foo_output`, while `terraform apply/plan` can.

The fact that `local_file` doesn't support import is not related to this case. I was trying to give you a minimal reproducer. The same problem happens on AWS provider on resources that support import.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform state rm local_file.foo2`
4. `terraform import local_file.foo2 foo2`

### Additional Context

Affecting 0.13.1, 0.13.2, 0.13.2, 0.13.3, 0.13.4, 0.13.5

I cannot reproduce it on 0.14.0-beta2.

**Comment by jbardin** [comment]
Hi @zarnovican 

From the description here, it appears that the issue has been fixed in 0.14.
Since 0.13 is only illegible for critical fixes at this point with the 0.14 release forthcoming, I'm going to close the issue out.

Thanks!
