### ISSUE TITLE
Removed data sources should not require a provider configuration

### ISSUE THREAD

**Issue by hypsrizzari** [hashicorp/terraform#26833]
Hello,

I have a root module with a provider alias defined as shown below.  I want to remove the provider entirely, and so tried to run `terraform plan -target data.aws_iam_policy.role1_administrator_access`, but no diff is generated.  Of course, if I remove the config below I get the error about the provider configuration missing.  This is because `data.aws_iam_policy.role1_administrator_access` still exists in the state file.

I found that if I don't use  `-target` in the plan/apply and remove or comment out the data resource, terraform will silently remove the data resource from the state file, and then I can remove the provider configuration.  Is this the intended way this should work?

### Terraform Version

```
terraform 0.13.5
hashicorp/aws: version = "~> 3.12.0"
```

### Terraform Configuration Files

```terraform
provider "aws" {
  alias = "alias1"

  assume_role {
    role_arn = "arn:aws:iam::*******:role/OrganizationAccountAccessRole"
  }

  region = "us-east-1"
}

data "aws_iam_policy" "role1_administrator_access" {
  provider = aws.alias1

  arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}
```

### Expected Behavior

Data resource `data.aws_iam_policy.role1_administrator_access` can be removed via targeted plan/apply
### Actual Behavior

Data resource remained in state file until the resource was commented out and a `terraform apply` was run (no targeting)

**Comment by jbardin** [comment]
Hi @hypsrizzari 

Can you expand on the use case here, or the problem you're trying to solve? Data sources shouldn't have external side effects, so there is nothing to accomplish by "destroying" them, nor does their inclusion in the state have any effect if it's not used in the configuration. In this case one would normally remove the unneeded data source and provider from the configuration, and the next apply would update the state to match.

Thanks!

**Comment by hypsrizzari** [comment]
Hi @jbardin,

Thank you for responding and working on this great product.

My use case is that I was trying to remove that configuration above since I no longer needed it, but when I did that on my next `terraform plan` I got the provider error message below.  My expectation is that if I target a data resource for destruction it will be removed.  This is because I have many AWS providers defined (per tenant), and sometimes I need to remove a single tenant.  I start by targeting all the resources (including the data resource), destroy them, and then I'd like to just remove the provider config in the next step.  I can't because the data resource doesn't get removed from the state file with `-target`.  No diff is generated if I comment or remove the data source.

Result of targeted plan
```

terraform plan -destroy -target 'data.aws_iam_policy.role1_administrator_access'
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

Result of trying to remove provider
```
Error: Provider configuration not present

To work with data.aws_iam_policy.role1_administrator_access its original
provider configuration at
provider["registry.terraform.io/hashicorp/aws"].alias1 is required, but it
has been removed. This occurs when a provider configuration is removed while
objects created by that provider still exist in the state. Re-add the provider
configuration to destroy data.aws_iam_policy.entintdev_administrator_access,
after which you can remove the provider configuration again.
```

This error of course is because `data.aws_iam_policy.role1_administrator_access` didn't get removed when I destroyed all the other resources.

In this case I couldn't remove the unneeded provider (I have multiple AWS providers defined) until I either ran `terraform rm` on the data resource, ran a full plan and apply (without -target) which removed the data resource and then allowed me to remove the provider, or finally running `terraform refresh`, which removed the data resource from the state file.

Thank you,

Sal

**Comment by jbardin** [comment]
Thank you @hypsrizzari, that helps a lot.

Rather than using `-target`, I think I would recommend removing the data source from the configuring and applying that config. The confusing thing here is that because the data source has visible side effects, it does not show up in the rendered plan, however applying that plan _does_ remove it from the state.

This is actually the same case with `-target`, it works but does not show up in the rendered plan. I would however avoid recommending `-target`, only because it's better to reflect the actual desired state in the configuration, and will lead to more predictable results. 

I think the root of the confusion is that because data sources are not actually destroyed, there is no reason for them to require a provider to remove them from the state. Fixing that may be easier said than done, but I'll rename this issue with that goal for now.

Thanks!
