### ISSUE TITLE
Function documentation error: cidrhost

### ISSUE THREAD

**Issue by kkotowick** [hashicorp/terraform#26830]
### Terraform Version
0.13.5

### Documentation Problem

In the [documentation](https://github.com/hashicorp/terraform/blob/master/website/docs/configuration/functions/cidrhost.html.md) for the `cidrhost` function, it has:

```
> cidrhost("10.12.127.0/20", 16)
10.12.112.16
> cidrhost("10.12.127.0/20", 268)
10.12.113.12
> cidrhost("fd00:fd12:3456:7890:00a2::/72", 34)
fd00:fd12:3456:7890::22
```

This is incorrect. `cidrhost("10.12.127.0/20", 16)` returns `10.12.127.16`, not `10.12.112.16`. Similar issue for the second example.

**Comment by pselle** [comment]
@kkotowick Thanks for raising this issue! I've just tried the lines you've pointed out and gotten the same results that are documented. Could you provide more information about the system in which you're running Terraform, in case that is relevant to what you're seeing?

**Comment by kkotowick** [comment]
Yep, you're right. Just an issue with me not paying enough attention and noticing that `10.12.127.0/20` is equivalent to `10.12.112.0/20`. Please disregard.
