### ISSUE TITLE
Terraform 0.14 concise plan diff shows sub-module outputs

### ISSUE THREAD

**Issue by alexjurkiewicz** [hashicorp/terraform#26834]
[I wrote this issue up on the Terraform forums, @apparentlymart asked me to re-open here.](https://discuss.hashicorp.com/t/terraform-0-14-concise-plan-diff/15759/4)

### Terraform Version
0.14 beta 2

### Terraform Configuration Files
![](https://aws1.discourse-cdn.com/hashicorp/original/2X/3/36c43a5c1e90dfc0147b69eb62303370c52831ac.jpeg)

```terraform
...
```

### Expected Behavior
No sub-module outputs are shown in plan diff.

### Actual Behavior
![](https://aws1.discourse-cdn.com/hashicorp/original/2X/9/9d9200377f206506421c64b353ce417d87529d8e.png)

### Steps to Reproduce

```
terraform init
terraform apply
```

**Comment by pkolyvas** [comment]
Hey @alexjurkiewicz, thanks for the issue report. It's been fixed via #26784 and will be available in 0.14.0-rc1 next week.

:)
