### ISSUE TITLE
Terraform vague error message on length=-1 for random_string resource

### ISSUE THREAD

**Issue by bogdanbarna** [hashicorp/terraform#26849]
### Terraform Version

```bash
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/random v3.0.0
```

### Terraform Configuration Files

```terraform
variable "name_prefix" {}

resource "random_string" "name_suffix" {
  length  = 30 - length(var.name_prefix)
  upper   = false
  special = false
}

resource "aws_instance" "web" {
  ami           = "ami-07dd19a7900a1f049"
  instance_type = "t3.micro"

  tags = {
    Name = "foo-${random_string.name_suffix.result}"
  }
}
```

### Crash Output

https://gist.github.com/bogdanbarna/4181ddf0b5fe0082e6cdcf4aae8cf0e0

### Expected Behavior

A specific error message appearing during plan and/or apply.

### Actual Behavior

Receiving `Error: rpc error: code = Unavailable desc = transport is closing` on apply.

### Steps to Reproduce

```bash
terraform init
terraform apply -var name_prefix=small # this works
terraform apply -var name_prefix=laaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarge # this crashes
```

### Additional Context

The crash report isn't created when the random_string output is used for the aws_instance input.
So apply -target=random_string creates the crash report, but apply without target does not.

**Comment by jbardin** [comment]
Hi @bogdanbarna 

While this will be transferred to the random provider so it can properly validate the inputs, the grpc error output was addressed in #26694.

Thanks!
