### ISSUE TITLE
Tab completion is extremely slow

### ISSUE THREAD

**Issue by cornfeedhobo** [hashicorp/terraform#26856]
### Terraform Version

```
> 0.12.x
```

### Terraform Configuration Files
n/a

### Debug Output
n/a

### Crash Output
n/a

### Expected Behavior
tab completion should be _fast_ and include all options.

### Actual Behavior
tab completion takes multiple seconds sometimes

### Steps to Reproduce
setup tab completion and try it

### Additional Context
I use tfenv, but the overhead of bash launching the final binary is minimal

### References
surprisingly i can't find any

**Comment by alisdair** [comment]
Thanks for this report. I'm not able to reproduce the issue locally—Terraform bash completion is very fast for me. But I suspect the issue might be Checkpoint HTTP requests.

Can you try disabling checkpoint for the completion command, and see if that improves the performance for you? Something like `complete -C "CHECKPOINT_DISABLE=1 terraform" terraform` ought to work.

If so, I think the most expedient fix would be to make that change in the bash completion repository linked to this issue.

**Comment by cornfeedhobo** [comment]
@alisdair Thank you for looking into this. `strace` revealed that the issue is local and outside of terraform. That said, I'd like to make a follow up ticket to finish building out some of the tab completion options (e.g. flags).

Do you know if anyone else is working on that already?

**Comment by alisdair** [comment]
I don't think anyone is, so that would be appreciated! Feel free to add `@alisdair` to your ticket to make sure I see it.
