### ISSUE TITLE
Failed to install provider in aws

### ISSUE THREAD

**Issue by Sabari6600** [hashicorp/terraform#26852]
Hi guyzz,
I'm new to aws terraform. im facing issue in installing provider for my modules.

Initializing provider plugins...

    Finding latest version of hashicorp/aws...
    Finding latest version of hashicorp/ec2...
    Installing hashicorp/aws v3.13.0...
    Installed hashicorp/aws v3.13.0 (signed by HashiCorp)

Error: Failed to install provider

Error while installing hashicorp/ec2: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/ec2

**Comment by alisdair** [comment]
There is no `ec2` provider. If you want to manage AWS EC2 resources, you can use the `aws` provider.

This doesn't appear to be a bug in Terraform, so I'm going to close this issue. If you have a more general question about getting started with Terraform, I'd recommend [posting on our discussion forum](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
