### ISSUE TITLE
Enable rsync on Linux Repos

### ISSUE THREAD

**Issue by mallmaluss** [hashicorp/terraform#26859]
It would be great, if you could enable rsync/s3 as a protocol for hashicorp yum/deb repositories in order to easily mirror them locally. This is needed quite frequently due to company policies that keep datacenter machines isolated from the internet.

**Comment by pkolyvas** [comment]
Hey @mallmaluss - We don't currently have any plans to officially package Terraform for specific distributions. AFAIK the Hashicorp linux repos are limited to Vault, Nomad and Consul at the moment. I will bring the feature request to the team however, but will close this as we don't track this work ourselves.

**Comment by pkolyvas** [comment]
So, following on the last issue, I'm wrong again. Terraform _is_ now distributed! TIL - thanks!

**Comment by kpenfound** [comment]
Hi @mallmaluss , is this resolved by https://github.com/hashicorp/terraform/issues/26858 or are you specifically requesting rsync functionality over reposync?

**Comment by mallmaluss** [comment]
Hi @kpenfound 
I specifically requested rsync or s3, since in my organization there is no direct access to the Internet for infrastructure servers.
We made a mirror for RPM packages, but we could not do this for the DEB packages. Your repository does not allow viewing file paths, which prevents you from creating a local mirror.

**Comment by kpenfound** [comment]
Awesome, thanks for the context. We are planning on making the repos browsable, so I'll post back here when that's enabled!
