### ISSUE TITLE
yum repo error

### ISSUE THREAD

**Issue by mallmaluss** [hashicorp/terraform#26858]
Hi!
When creating a mirror of the repository rpm, an error appears:
[MIRROR] terraform-0.13.4-2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 28464464 but expected size is: 28470416

OS: RHEL 8.3
dnf version 4.2.23

**Comment by pkolyvas** [comment]
Hey @mallmaluss! Unfortunately, we don't package Terraform for specific Linux distributions. You'll likely have to contact RedHat support for help with a RPM / RPM repo mirror issue.

**Comment by pkolyvas** [comment]
@mallmaluss I'm wrong - HashiCorp does package Terraform internally, but it's another team. I've raised the issue with them.

**Comment by kpenfound** [comment]
Hi @mallmaluss , thanks for reporting this!  I've resolved the issue with that specific package and confirmed that reposync will complete cleanly
