### ISSUE TITLE
aws_iam_role gives syntax errors

### ISSUE THREAD

**Issue by bdesilva** [hashicorp/terraform#2686]
Hi guys,

I need to create a role dynamically so I use the proper terraform resource as follows:

```ruby
resource "aws_iam_instance_profile" "elasticsearch_profile" {
  name = "elasticsearch_profile"
  roles = ["${aws_iam_role.ec2.name}"]
}

resource "aws_iam_role" "ec2" {
  name = "elasticsearch_role"
  path = "/"
  assume_role_policy = <<EOF
  {
      "Version": "2012-10-17",
      "Statement": [
      {
        "Effect": "Allow",
        "Principal": {
          "Service": "ec2.amazonaws.com"
        },
      "Action": "sts:AssumeRole"
      }
    ]
  }
  EOF
}

resource "aws_iam_policy_attachment" "elasticsearch_policy_attach" {
  name = "elasticsearch_policy_attach"
  roles = ["${aws_iam_role.ec2.name}"]
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
}
```

But as per this image, you can see that I have errors showing up in the syntax, possibly because it's a mis-mash of regular syntax with AWS' JSON syntax for roles:

<img width="487" alt="screen shot 2015-07-10 at 2 30 56 pm" src="https://cloud.githubusercontent.com/assets/8118187/8629462/7e333672-2710-11e5-8180-3e2702256a38.png">

And here's the error in the output:

<img width="843" alt="screen shot 2015-07-10 at 2 31 06 pm" src="https://cloud.githubusercontent.com/assets/8118187/8629476/97f20c46-2710-11e5-8714-36ca59c6d92f.png">

Can someone please help me out with this?

**Comment by radeksimko** [comment]
You are using wrong [HEREDOC](https://en.wikipedia.org/wiki/Here_document) syntax, the end delimiter `EOF` must not have any white spaces around:

```diff
27c27
<   EOF
---
> EOF
```

Reopen if it still doesn't solve your problem, but I ran `terraform plan` on your example after fixing it the way suggested above and it was ok.

**Comment by bdesilva** [comment]
Thanks, that worked!
