### ISSUE TITLE
Terraform generates unnecessary diff on modules.json

### ISSUE THREAD

**Issue by sylr** [hashicorp/terraform#26863]
### Terraform Version

```
Terraform v0.13.5
```

### Expected Behavior

**module.json** content should be sorted so that it is not changed between `terraform refresh` runs and generate diffs

### Actual Behavior

```diff
diff --git terraform-workspace/.terraform/modules/modules.json terraform-workspace/.terraform/modules/modules.json
index bb89d2f..76d3c35 100644
--- terraform-workspace/.terraform/modules/modules.json
+++ terraform-workspace/.terraform/modules/modules.json
@@ -1 +1 @@
-{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"aks04-CNN2-prod-aks","Source":"./modules/aks-cluster-cnn2","Dir":"../modules/aks-cluster-cnn2"}]}
\ No newline at end of file
+{"Modules":[{"Key":"aks04-CNN2-prod-aks","Source":"./modules/aks-cluster-cnn2","Dir":"../modules/aks-cluster-cnn2"},{"Key":"","Source":"","Dir":"."}]}
\ No newline at end of file
```

**Comment by CpuID** [comment]
Just hit this myself... everytime I `terraform plan`, the `git diff` changes due to the data being reordered every time.

**Comment by yokomotod** [comment]
+1, and I have submitted a PR to fix this issue.

I know it's popular to git ignore the whole `.terraform/*` like https://github.com/github/gitignore/blob/main/Terraform.gitignore , but I do want to commit `.terraform/modules/modules.json`.

My use case: 

- I have a monorepo which contains many terraform working directories and a number of shared local modules.
- When some shared modules are changed, I want to run CI jobs for the affected directories.
- In doing so, I'm going to use `modules.json` to analyze the dependencies of the modules.
