### ISSUE TITLE
AWS Global dynamodb table now supports custom managed key

### ISSUE THREAD

**Issue by PoornachandS** [hashicorp/terraform#26860]
Hi Team,

AWS dynamodb  global table now supports custom key. This feature is not supported in terraform dynamodb table currently. Could you add this as a future request and provide the timeline for this?

https://aws.amazon.com/about-aws/whats-new/2020/11/encrypt-your-amazon-dynamodb-global-tables-by-using-your-own-encryption-keys/

**Comment by pkolyvas** [comment]
@PoornachandS it's not immediately evident to me if you're referring to the Dynamo DB table used as part of the s3 remote state backend or the [Dynamo DB resources in our AWS provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table).

If it's the later, this request should be made in the [AWS provider repository](https://github.com/hashicorp/terraform-provider-aws).

**Comment by PoornachandS** [comment]
@pkolyvas  I am referring to the later one i.e dynamodb table as a resource. Nevertheless, the required configuration should be 
completed in both AWS provider end and terraform end to make use of the custom key.

**Comment by pkolyvas** [comment]
This all happens via the provider.
