### ISSUE TITLE
Argument naming convention between aws_autoscaling_group and aws_instance not consistent

### ISSUE THREAD

**Issue by ckelner** [hashicorp/terraform#2687]
Only highlighting a single argument here, but possible there may be more like this.  For aws_instance, subnets are referred to as [subnet_id](https://www.terraform.io/docs/providers/aws/r/instance.html#subnet_id) and for aws_autoscaling_group, subnets are referred to as [vpc_zone_identifier](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#vpc_zone_identifier).

Ideally these should be consistent between resources.  However I did note that in the AWS HTTP API the parameter for instances is [SubnetId](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html) and the parameter for autoscalinggroups is [VPCZoneIdentifier](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_CreateAutoScalingGroup.html).  

I'm uncertain if the goal of terraform here is to be as close to the provider as possible, or if it means to abstract more to make it easier to a user.  Feel free to squash this if it isn't in line with the goals of terraform.

**Comment by radeksimko** [comment]
I agree this is confusing, I got caught by that couple times, not sure if it's worth drifting away from the API - most importantly I don't know what is the reason for the API itself to have such naming.

**Comment by ckelner** [comment]
@radeksimko From the AWS perspective, from having worked with the AWS API in the past quite a bit, the only reasonable excuse I've seen is to prevent breaking contract with customers and maintaining backwards compatibility.  I'd see the same issue here though, you'd need to make the change during a major version change (or very soon while still in the earlier stages of development).  My 2 cents anyways.

All in all, I'd love to see if be consistent, but I can understand why it isn't or won't be.

**Comment by phinze** [comment]
Good question, @ckelner!

I agree that the inconsistency between the argument names is not ideal, but at this point in the project we're sticking close to the naming in the AWS API to avoid ambiguity (1) for implementors and (2) for users migrating from other AWS tooling.

Down the road we may revisit places where we can drift more from upstream APIs for UX improvements. But for now while we're still doing lots of work to get API coverage complete and bug-free, we're going to stay close to upstream's naming.

**Comment by ckelner** [comment]
:+1: thanks for the response @phinze
