### ISSUE TITLE
centralised storage of providers

### ISSUE THREAD

**Issue by marengaz** [hashicorp/terraform#26876]
### Current Terraform Version
```
0.13.4
```

### Use-cases

i/my team manage a few hundred terraform modules. all of them are on gcp. i have a few hundred copies of the same gcp provider (70mb each) and am running out of hard disk space! its also a waste of time to download the same provider every time i `terraform init`, when i know i already have the same file in the neighboring directory

### Attempted Solutions

every now and again i have to run `find . -type f -name "terraform-provider-google_*" | xargs rm` to free up some space, then start downloading again

### Proposal

i would like to be able to configure a centralised store of providers that are symlinked to the module when i run `terraform init`

**Comment by pkolyvas** [comment]
@marengaz good news, what you want exists. It's called the provider plugin cache: - The Provider Plugin Cache: https://www.terraform.io/docs/commands/cli-config.html#provider-plugin-cache

There are some options to further reduce how frequently the providers are downloaded should you so choose:
- The implied local mirror directories:  https://www.terraform.io/docs/commands/cli-config.html#implied-local-mirror-directories
- The Filesystem Mirror and Network Mirror options: https://www.terraform.io/docs/commands/cli-config.html#explicit-installation-method-configuration

Hope that helps! If not, please just us in over at our [community forums](https://discuss.hashicorp.com/c/terraform-core) where we can continue the conversation.

**Comment by marengaz** [comment]
hi @pkolyvas - thanks for the hint, that solves the 'download time/bytes' problem, but not the 'eating up my hard disk' problem.
would it be possible to add an option to symlink to the plugin cache, instead of copying the file from the plugin cache?

**Comment by pkolyvas** [comment]
@marengaz It should use a symbolic link where possible as per the docs:
```
When possible Terraform will use symbolic links to avoid storing a separate 
copy of a cached plugin in multiple directories.
```

There's some discussion of the ins/outs here: https://github.com/hashicorp/terraform/issues/26144

**Comment by marengaz** [comment]
sorry, my mistake, i see now that the dir is symlinked, not the file!
