### ISSUE TITLE
Allows disabling of TLS verification in S3 state backend

### ISSUE THREAD

**Issue by tongpu** [hashicorp/terraform#26883]
### Current Terraform Version
```
Terraform v0.13.5
```

### Use-cases
It's currently not possible to disable TLS verification in the Terraform S3 state backend.

### Attempted Solutions
Found no way to ignore a certificate whose CN doesn't match the the hostname used to connect to the S3 endpoint.

### Proposal
Extend configuration parameters for Terraform S3 state backend to allow disabling TLS verification.

**Comment by tongpu** [comment]
For reference this is how disabling TLS verification has been implemented in `velero-plugin-for-aws`: https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/2e329d8a9c7fd6556f6348bc0a1b4dd13c2985ad/velero-plugin-for-aws/object_store.go#L150-L167

**Comment by horizon46** [comment]
Any update for this  request?

**Comment by DCkQ6** [comment]
It would be nice since S3 tends to be a [recommended replacement](https://discuss.hashicorp.com/t/replacement-for-now-deprecated-swift-backend/43488) for deprecated swift backend, and we do not always has proper certs in our local openstack deployments.

**Comment by crw** [comment]
Thanks for the additional context, @DCkQ6, regarding typical usage in OpenStack.

**Comment by digitalray** [comment]
There is a feature request for aws cli that may help with this: https://github.com/aws/aws-cli/issues/4215

**Comment by gdavison** [comment]
This was added by #33765
