### ISSUE TITLE
aws_instance Changing monitoring argument doesn't change an instance

### ISSUE THREAD

**Issue by robertfirek** [hashicorp/terraform#2688]
Changing monitoring option in terraform file doesn't change the instance in AWS if the instance already exists. 

Plan shows:
```
~ aws_instance.someinstance
    monitoring: "0" => "1"
``` 

During execution everything looks fine
```
aws_instance.someinstance: Modifying...
  monitoring: "0" => "1"
```

Unfortunately the EC2 instance remains unchanged and next execution of plan command showing that the instance must be changed and execution of apply command tries to modify this instance again.
***Output doesn't show any errors.***

Workaround:
Manually change monitoring settings. State will be refreshed with the right status.

**Comment by robertfirek** [comment]
Probably this issue and https://github.com/hashicorp/terraform/issues/2700 is the same issue.

**Comment by catsby** [comment]
Hey @robertfirek thanks for sending this in – I've patched the behavior in #2794

**Comment by robertfirek** [comment]
@catsby Thank you for your update. I'm waiting for next release :+1:

**Comment by catsby** [comment]
Hey @robertfirek – I just merged this fix, but I'm sorry to say it didn't make the v0.6.1 release (out yesterday) :frowning:  

Hopefully building from master is something you can do, or if not, it will go out in the next release (though I'm not totally sure when that will be).

I apologize for not getting this in there when I said I would.

**Comment by robertfirek** [comment]
That's fine @catsby. When do you plan next release?

**Comment by catsby** [comment]
It's not scheduled yet... if I were to guess now I would say the first week of July
