### ISSUE TITLE
Ability to delay instance creation

### ISSUE THREAD

**Issue by amontalban** [hashicorp/terraform#2689]
Hey guys,

Thank you for another AWESOME product (Been using Vagrant and Packer for a while). I'm creating a staging environment for a customer using VPC and a NAT instance, I have around 5 instances and a RDS one that depends on the VPC and NAT instance but I'm facing a race condition when the 5 instances starts and needs to be provisioned (Using salt) and they don't have Internet because the NAT instance is still starting.

I'm using cloud-init and doing the Salt minion install and stuff, I've just added a sleep XX but this seems like a complete ugly h4x and don't like it.

So the question, is it possible to either delay instance creation or maybe adjust the depends_on parameter to check if the instance is done booting?

Thank you very much!

**Comment by phinze** [comment]
Hi @amontalban,

There's no way to delay instance creation, but you can use provisioners for verification steps like this.

```js
resource "aws_instance" "app" {
  provisioner "local-exec" {
    command = "./poll-until-has-outbound-connectivity ${self.id}"
  }
}
```

Does that accomplish what you're looking for? If not, can you share some config examples and explain a bit more how you have things wired together?

**Comment by amontalban** [comment]
Hi @phinze,

Thanks for the reply, actually I can't use local-exec because that would not delay my cloud-init config that I'm sending via EC2 user-data. Here are my configs:

**NAT Instance:**

```yaml
resource "aws_instance" "ws-staging-natinstance" {
    ami = "${lookup(var.aws_natinstance_amis, var.aws_region)}"
    instance_type = "t2.micro"
    monitoring = "True"
    key_name = "amontalban"
    availability_zone = "${var.aws_region}${var.aws_availability_zone}"

    vpc_security_group_ids = ["${aws_security_group.ws-staging-allow-outbound-http-https.id}",
                              "${aws_security_group.ws-staging-allow-outbound-saltstackmaster.id}",
                              "${aws_security_group.ws-staging-allow-incoming-ssh-bastionhost.id}",
                              "${aws_security_group.ws-staging-allow-outbound-ssh-bitbucket.id}",
                              "${aws_security_group.ws-staging-natinstance.id}"
                             ]

    subnet_id = "${aws_subnet.ws-staging-public-subnet.id}"
    private_ip = "${var.natinstance_ip}"
    user_data = "${template_file.ws-staging-minion-userdata.rendered}"
    iam_instance_profile = "${aws_iam_instance_profile.ws-staging-default-profile.name}"
    source_dest_check = "False"

    depends_on = ["aws_internet_gateway.ws-staging-gw",
                  "aws_security_group.ws-staging-natinstance",
                  "aws_vpc.ws-staging-vpc",
                  "aws_subnet.ws-staging-public-subnet",
                  "aws_iam_instance_profile.ws-staging-default-profile",
                 ]

    tags {
        Environment = "STAGING"
        Name = "ws-staging-nat-instance"
        Role = "NAT_INSTANCE"
    }
}
```
**Salt Master server:**

```yaml
resource "aws_instance" "ws-staging-saltmaster" {
    ami = "${lookup(var.aws_debian_amis, var.aws_region)}"
    instance_type = "t1.micro"
    monitoring = "True"
    key_name = "amontalban"
    availability_zone = "${var.aws_region}${var.aws_availability_zone}"

    vpc_security_group_ids = ["${aws_security_group.ws-staging-allow-outbound-http-https.id}",
                              "${aws_security_group.ws-staging-allow-outbound-saltstackmaster.id}",
                              "${aws_security_group.ws-staging-allow-incoming-ssh-bastionhost.id}",
                              "${aws_security_group.ws-staging-allow-outbound-ssh-bitbucket.id}",
                              "${aws_security_group.ws-staging-saltmaster.id}"
                             ]

    subnet_id = "${aws_subnet.ws-staging-saltmaster-subnet.id}"
    private_ip = "${var.saltmaster_ip}"
    iam_instance_profile = "${aws_iam_instance_profile.ws-staging-saltmaster-profile.name}"
    user_data = "${template_file.ws-staging-saltmaster-userdata.rendered}"

    depends_on = ["aws_internet_gateway.ws-staging-gw",
                  "aws_instance.ws-staging-natinstance",
                  "aws_instance.ws-staging-bastionhost",
                  "aws_route_table.ws-staging-default-route",
                  "aws_route_table.ws-staging-public-route",
                  "aws_main_route_table_association.ws-staging-default-route-assoc",
                  "aws_route_table_association.ws-staging-saltmaster-route-assoc",
                  "aws_route_table_association.ws-staging-public-route-assoc",
                  "aws_security_group.ws-staging-saltmaster",
                  "aws_vpc.ws-staging-vpc",
                  "aws_subnet.ws-staging-saltmaster-subnet",
                  "aws_s3_bucket.ws-staging-saltmaster",
                  "aws_iam_role_policy.ws-staging-saltmaster-policy",
                  "aws_iam_instance_profile.ws-staging-saltmaster-profile",
                 ]

    tags {
        Environment = "STAGING"
        Name = "ws-staging-saltmaster"
        Role = "SALT_MASTER"
    }
}
```

I think that the best approach would be that when you are depending on instances, such instances are in running state, ie the status checks are all ok meaning that the instance has fully booted.

For now I have "fixed" this by adding a "sleep 120" on the instances depending on NAT instance so it is initialised properly before connecting to the Internet.

Thanks!

**Comment by phinze** [comment]
Thanks for the extra detail, @amontalban.

I think you might be right that we can poll on instance health status to guarantee the instance is booted before moving on. Let me think about this a bit.

In the meantime, it is possible to get the behavior I was describing by adding a provisioner to the NAT instance that runs a script that polls until the NAT instance is available. The dependent resources will not be created until after all provisioning of the NAT completes successfully.

**Comment by mijit** [comment]
I may have a use for delayed or staggered resource creation. In the case where I have, say, five hosts launching from a single template, I have five hosts looking for an IP with the same hostname simultaneously. I don't know what the cause of this particular problem is, so it may well be particular to my private network or my third-party provider plugin, but I'm seeing VM lockups and the occasional Terraform crash. And, I do know that if I stagger instance creation manually, I can create all desired resources successfully. While I would prefer to solve the underlying problem (and will continue investigation,) it appears it could be of short-term benefit if I could create my resources serially.

**Comment by mitchellh** [comment]
I think we agree that the best approach still is just to use a provisioner on the instance that needs to be waited on. This affects _all_ downstream resources but I think for now this is right.
