### ISSUE TITLE
v0.14-rc1 and Terraform Cloud, plan with no changes still expecting to create resources

### ISSUE THREAD

**Issue by jurgenweber** [hashicorp/terraform#26899]
### Terraform Version

```
Terraform v0.14.0-rc1
+ provider instaclustr/instaclustr/instaclustr v1.6.1
+ provider registry.terraform.io/hashicorp/aws v3.14.1
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tfe v0.22.0
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior
When there are no changes, terraform should report:
```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Actual Behavior
Terraform reports:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce
1. go into terraform cloud and queue another run

### Additional Context
I have had this issue for a long time, in v0.13, the AWS provider v3+ had a lot of problems with data sources and non deterministic ID's, etc that made sort of sudo changes. This has all been cleaned up and in v0.13.... it works now... But ude to some other errors I had to move to v0.14 and now this behaviour is back.

**Comment by jbardin** [comment]
Hi @jurgenweber 

I suspect there is a still a data source involved here which is not behaving correctly. If the data source has no visible side-effects but is still deferred until apply, it might cause this behavior. Can you provide a configuration which reproduces this issue? 

We may also be able to figure out what is triggering the the change from trace logs when applying this plan.

Thanks!

**Comment by jurgenweber** [comment]
Ok, my code base is pretty big so I can not really give you the whole lot. Here is a list of the current used data sources:

```
aws_iam_policy
aws_iam_policy_document
aws_kms_key
aws_kms_secrets
aws_lb
kubernetes_service
aws_availability_zones
aws_caller_identity
aws_eks_cluster
aws_eks_cluster_auth
aws_organizations_organization
aws_partition
aws_route53_zone
aws_s3_bucket
terraform_remote_state
```
what I am looking for in the trace? I have not been able to find anything useful so far.

**Comment by jurgenweber** [comment]
if I could get some direction on what to look for, hopefully we can pin it down?
