### ISSUE TITLE
azurerm_data_factory_integration_runtime_managed CatalogPricingTier not functioning for Azure SQL Managed Instances [Need to add NULL as an option]

### ISSUE THREAD

**Issue by dadams0641** [hashicorp/terraform#26897]
```
$ terraform -version
Terraform v0.13.5
```

`What I'm trying to do`
Build a Data Factory Integration Runtime that connects to an Azure SQL Managed Instance

`What is happening`
An **_incorrect_** Catalog Pricing Tier is sent, which causes the IR to fail. It DOES NOT allow for a **null** value. 

This is due to the fact that the DEFAULT VALUE for Catalog Pricing Tier is "Basic" and it does not allow for a value **below that** to be sent. 

`Expected Action`
I would expect to be able to send a "NULL" value for the Pricing Tier. 

`Requested Bug Fix`

Hello Hashicorp,

When utilizing Terraform, within Azure, to create a Data Factory Integration Runtime that integrates with SQL Managed Instances, an invalid property is given. The Data Factory IR CatalogPricingTier for SQL Managed Instances NEEDS TO BE "null" or "empty".

No Other Option is accepted by Azure, thus this causes an error. 

This seems to be easily resolved by

1. Removing "Basic" as a default and force Pricing Tier to be required
or
2. Allowing the unquoted "null" to be sent as a valid value

3. Allow for custom values and send THAT VALUE to the IR API. 

Number 3 is pretty important because there are more Pricing Tiers than just Basic, Standard, Premium, and PremiumRS (Such as S0, S1, H3, H4, etc.) 

As SQL Managed Instances become more and more prevalent, it will become more and more important for "Null" to be a valid value when building out DF IRs. 

Thank you so very much
David Adams

**Comment by kcross2000** [comment]
I'm also seeing this issue.  #MeToo
