### ISSUE TITLE
hashicorp/terraform:full still 0.13.4 instead of 0.13.5

### ISSUE THREAD

**Issue by bnelson729** [hashicorp/terraform#26903]
### Terraform Version

```
Trying to run 0.13.5 through hashicorp/terraform:full, but it is still using 0.13.4
```

### Terraform Configuration Files

```terraform
N/A
```

### Expected Behavior

The version of hashicorp/terraform:full should match the hashicorp/terraform:latest and hashicorp/terraform:light versions.

### Actual Behavior

hashicorp/terraform:full is a version behind.

### Steps to Reproduce

1, Try to use hashicorp/terraform:full when your required terraform version is 0.13.5.
2. You get an error that 0.13.4 doesn't match requirement.

**Comment by mildwonkey** [comment]
Hi folks, sorry for the confusion here. We are no longer publishing the `full` docker images, and not communicating this was a mistake on my part. I am sorry for that.

The `full` image contained both a binary and the terraform source code, and was originally intended for developers. The `light` image is the one we recommend for general use. We have chosen to stop publishing the `full` image and instead encourage developers to set up their own development environments as the see fit. 

We will remove the `full` tag from dockerhub entirely when 0.14 is released.

**Comment by mildwonkey** [comment]
@bnelson729  I'm sorry, I should have asked this yesterday: I'd love to hear your use case for the `terraform:full` image - I'm curious what use folks are getting out of it and if there's something we should continue supporting.

**Comment by bytemech** [comment]
@mildwonkey #24102 <- there's a few of us that would like more :full images, not less!

**Comment by mildwonkey** [comment]
Hi folks! We are in the process of removing the :full image tag from dockerhub entirely. 

While I've seen someone mention installing go on top of our :light image as a workaround, I'd generally recommend using a base image that is intended as a base image, and installing terraform on that image. 

We are leaving the Dockerfile (and build scripts) that was used to build the full image in this repository for now, so you could also grab that and build your own image.

Thanks!
