### ISSUE TITLE
Removal of helper/schema and other SDK packages

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform#26919]
Following the release of the standalone [Terraform Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk), new Terraform providers should no longer import `github.com/hashicorp/terraform`. Core packages used exclusively for provider development, including `helper/schema`, should be removed from the public API - either deleted, or moved to `internal`.

This is a tracking issue for removing these packages from the public API, which I understand is currently blocked due to their use in Core's tests. The new provider https://github.com/hashicorp/terraform-provider-corner is intended to fulfil dummy provider testing needs.

Please correct any of the above assumptions in comments. The SDK team is happy to supply an updated list of packages to be deleted when Core is ready.

**Comment by jbardin** [comment]
Hi @kmoe 

Thanks for the update! Is just so happens that the refactoring I'm working is to be able to remove the legacy types from the the tests.

The blocking issue for complete removal is the fact that _provisioners_ still use the internal types. While I'm working on the builtin provisioners at the moment, there are technically 3rd party provisioners in use, and we need to come up with a plan for their support as well.
