### ISSUE TITLE
provider/aws: Increased retention period for Kinesis streams

### ISSUE THREAD

**Issue by ElizaRayner** [hashicorp/terraform#26910]
Aws has recently released an update allowing streams to have a retention period up to one year (8760 hours) that is not allowed with terraform.

Relevant API calls:
IncreaseStreamRetentionPeriod
DecreaseStreamRetentionPeriod

**Comment by jbardin** [comment]
Hi @ElizaRayner 

This appears to be for AWS provider issue rather than Terraform itself. Please fill out a feature request in the AWS provider issue tracker, https://github.com/hashicorp/terraform-provider-aws/issues. 

Thanks!
