### ISSUE TITLE
Terraform template file escaping

### ISSUE THREAD

**Issue by spatel96** [hashicorp/terraform#26915]
### Terraform Version

```
0.12.29
```

### Terraform Configuration Files

test.tpl
```terraform
appender.json_rolling.filePattern = $${sys:ls.logs}/logstash-json-%%d{yyyy-MM-dd}-%%i.log.gz
```
test.tf
```terraform
locals {
  test= templatefile("test.tpl",{})
}

output "render" {
  value = local.logstash
}
```

### Debug Output
```
terraform refresh
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.


Outputs:

render = appender.json_rolling.filePattern = ${sys:ls.logs}/logstash-json-%%d{yyyy-MM-dd}-%%i.log.gz
```

### Expected Behavior
The escaped character would be consumed leaving only a single character 
e.g. 

`
appender.json_rolling.filePattern = $${sys:ls.logs}/logstash-json-%%d{yyyy-MM-dd}-%%i.log.gz
`

renders into:

`
appender.json_rolling.filePattern = ${sys:ls.logs}/logstash-json-%d{yyyy-MM-dd}-%i.log.gz
`

### Actual Behavior
The escape character is rendered into the template:
appender.json_rolling.filePattern = ${sys:ls.logs}/logstash-json-**%%d{yyyy-MM-dd}-%%i.log.gz**

### Steps to Reproduce

1. Setup a template file with the strings above.
2. Create a locals which renders the template. 
3. Output the locals to print it out the the console. 
4. Run a terraform refresh.

**Comment by mildwonkey** [comment]
Hi @spatel96 ,
Those escape sequences are not recognized by the `templatefile` function. The `templatefile` syntax is the same as the string template syntax documented [here](https://www.terraform.io/docs/configuration/functions/templatefile.html).

You can remove the extra `%` signs and your expected output is rendered:


```hcl
locals {
  test= templatefile("test.tpl",{})
}

output "render" {
  value = local.test
}
```

```
Changes to Outputs:
  ~ render = <<-EOT
      - appender.json_rolling.filePattern = ${sys:ls.logs}/logstash-json-%%d{yyyy-MM-dd}-%%i.log.gz
      + appender.json_rolling.filePattern = ${sys:ls.logs}/logstash-json-%d{yyyy-MM-dd}-%i.log.gz
```
