### ISSUE TITLE
Make verbose output for Acceptance testing optional

### ISSUE THREAD

**Issue by A141864** [hashicorp/terraform#26926]
### Current Terraform Version
Terraform v0.13.5

### Proposal
When the `TF_ACC` environment variable is set to `1`, terraform requires tests to be run with the verbose flag. This is difficult to configure with VS Code and is not always necessary when stepping through code. 

I propose making verbose output optional by logging a `warning` message instead of calling `t.fatal` and returing.

```hcl

// We require verbose mode so that the user knows what is going on.
if !testTesting && !testing.Verbose() && !c.IsUnitTest {
	t.Fatal("Acceptance tests must be run with the -v flag on tests")
	return
}
```
#### Becomes
```hcl
// Encourage verbose mode so that the user knows what is going on.
if !testTesting && !testing.Verbose() && !c.IsUnitTest {
	log.Printf("[WARN] Use the -v flag to enable verbose test output")
}
```

#### 1. Update VSCode launch.json
```json
"configurations": [
    {
        "name": "Launch",
        "type": "go",
        "request": "launch",
        "mode": "debug",
        "port": 2345,
        "host": "127.0.0.1",
        "program": "${filename}",
        "env": {},
        "args": ["-v"],
        "showLog": true
    }
```
#### Update VSCode settings.json
```json
{
    "go.testEnvVars": {
        "TF_ACC": "1",
      },
    "go.testFlags": ["-v"]
}
```

### References
https://github.com/Microsoft/vscode-go/issues/1377

**Comment by jbardin** [comment]
Hi @A141864 

The code you're referencing should no longer be used by providers, as the only supported package for development is the [Terraform Plugin SDK](github.com/hashicorp/terraform/terraform-plugin-sdk). Looking at their repo it seems the `testing.Verbose` requirement no longer applies, so you may want to try upgrading to the latest version.

Thanks!
