### ISSUE TITLE
Shorthand for module directive in state paths

### ISSUE THREAD

**Issue by jaycarlton** [hashicorp/terraform#26925]
I've started using modules recently, and I've found it confusing trying to read paths when there are multiple generations of modulels, such as `module.workbench.module.reporting.module.main.google_bigquery_dataset.main`.

It seems to me that a `.module.` is really more of an operator or junction point than a real part of the path. Would it be possible to introduce shorthand syntax to replace it and shorten the path in one stroke?

Something like  `||workbench||reporting||main.google_bigquery_dataset.main` is more compact in the state list and graph outputs. I'm guessing there's a reason a simple `/` wasn't feasible here.

It would be nice to distinguish something to indicate resources, variables, locals, etc succinctly as well. Right now it's not obvious what each token corresponds to.

### Current Terraform Version
```
Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.5.0
```

### Use-cases

Displaying output in `terraform state list` nad `terraform  graph` could be much more compact with a symbol for `module`, while adding clarity. It would simplify providing arguments for `terraform import` as well.

**Comment by pkolyvas** [comment]
Thanks for your submission @jaycarlton! I think there's enough similarity to #21645 that I'm going to close this down as related enough to coalesce the feedback there. 

I do think this issue is becoming increasingly important, especially as we see more and more buy-in to modules and modularized configurations.
