### ISSUE TITLE
Terraform Provisioner Should Run Every Apply

### ISSUE THREAD

**Issue by jrsmith17** [hashicorp/terraform#26940]
### Terraform Version

0.13.5 (but I also tested on 0.13.2)

### Terraform Configuration Files

```terraform
resource "aws_iam_role" "iam_for_lambda" {
  name = "iam_for_lambda"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "null_resource" "compile_lambda" {
  provisioner "local-exec" {
    when = "create"
    command = "GOOS=linux GOARCH=amd64 go build -o alert_handler slack/alert_handler.go"
  }

  triggers = {
    #md5 = "${filemd5("${path.module}/alert_handler.go")}"
    #md5 = "${sha1("${path.module}/alert_handler.go")}"
    always_run = "${timestamp()}"
  }
}

data "archive_file" "zip" {
  depends_on  = [null_resource.compile_lambda]
  type        = "zip"
  source_file = "alert_handler"
  output_path = "alert_handler.zip"
}

resource "aws_lambda_function" "slack_alert_lambda" {
  function_name    = "slack_alert_lambda"
  filename         = "alert_handler.zip"
  handler          = "alert_handler"
  role             = aws_iam_role.iam_for_lambda.arn
  source_code_hash = "data.archive_file.zip.output_base64sha256"
  runtime          = "go1.x"
}
```

### Debug Output

```
Error: error archiving file: could not archive missing file: alert_handler
```

### Expected Behavior

Terraform runs provisions, which compiles the Go binary to be shipped out in the AWS Lambda.

### Actual Behavior
It does not run the command.

### Steps to Reproduce

0. Make a quick hello world style go file (mine is work specific)
1. terraform init
2. terraform

### References
As implied by the commented out portions of my code, I tried all the suggestions mentioned in [https://github.com/hashicorp/terraform/issues/8266]. None of them worked as advertised.

**Comment by jbardin** [comment]
Hi @jrsmith17 

This appears to be the same problem as described in #26939. The error is not from the provisioner failing to run, rather it is from the data source failing to find the file defined in its configuration. In order for the data source to succeed here, the file must be available during refresh.

The enhancement in 0.14 have now made this use case possible, so I'm going to close out this issue. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help that may have experience solving problems with this type of workflow. 

Thanks!
