### ISSUE TITLE
Kinesis application not keeping the order of record_columns 

### ISSUE THREAD

**Issue by tfeuser123** [hashicorp/terraform#26943]
Since Nov. 6 Friday, TFE is mixing column orders defined below.  If you see code snippets below, HEADER_TYPE is the 1st column and AWS component (Kinesis Analytics) was keeping the same order as the terraform codes. But since Nov 6 (no changes), DATA_CD is the 1st column and all other columns are mixed up. So, we have to manual re-arrange the column orders from AWS console.  More strangely, It works fine on local deploy with S3 backend (I mean it keeps the order).  It is happening only for TFE deploy (TFE backend).
 
    schema {
      record_columns {
        name     = "HEADER_TYPE"
        sql_type = "INTEGER"
      }

      record_columns {
        name     = "COL_2"
        sql_type = "INTEGER"
      }
      record_columns {
        name     = "DATA_CD"
        sql_type = "INTEGER"
      }

**Comment by danieldreier** [comment]
@tfeuser123 as a TFE user, you are eligible for [commercial support](https://support.hashicorp.com/hc/en-us). I encourage you to file a support ticket for this because you will get more support going through the commercial support channel than via open source.

**Comment by tfeuser123** [comment]
When this can be fixed?  We are having same issue on 3.14.0 and 3.15.0. We are back to 3.13.0.
