### ISSUE TITLE
[0.14-rc1] Module with depends_on that uses for_each fails

### ISSUE THREAD

**Issue by innovate-invent** [hashicorp/terraform#26950]
### Terraform Version

```
Terraform v0.14.0-dev
+ provider registry.terraform.io/brinkmanlab/galaxy v0.2.6
+ provider registry.terraform.io/hashicorp/null v3.0.0

```

### Terraform Configuration Files
```terraform
provider "galaxy" {
  host    = "http://localhost:8081"
  apikey = "admin"
}

resource "null_resource" "test" {}

module "test" {
  source = "./test_module"
  depends_on = [null_resource.test]
}
```

```terraform
data "galaxy_workflow_repositories" "islandcompare" {
  json = file("/home/nolan/Projects/IslandCompare/workflow/workflows/IslandCompare_unpacked_w._BLAST.ga")
}

resource "galaxy_repository" "islandcompare" {
  for_each = { for repo in data.galaxy_workflow_repositories.islandcompare.repositories: "${repo.tool_shed}/repos/${repo.owner}/${repo.name}" => repo }
  tool_shed = each.value.tool_shed
  owner = each.value.owner
  name = each.value.name
  changeset_revision = each.value.changeset_revision
}
```

### Debug Output
[log.txt](https://github.com/hashicorp/terraform/files/5556881/log.txt)

### Expected Behavior
Successfully apply

### Actual Behavior
```
Error: Invalid for_each argument

  on test_module/main.tf line 6, in resource "galaxy_repository" "islandcompare":
   6:   for_each = { for repo in data.galaxy_workflow_repositories.islandcompare.repositories: "${repo.tool_shed}/repos/${repo.owner}/${repo.name}" => repo }

The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.
```

### Steps to Reproduce
1. `docker run --rm -d -p 8081:80 -e GALAXY_CONFIG_OVERRIDE_ALLOW_USER_DELETION=true quay.io/bgruening/galaxy:19.09`
2. `terraform init`
3. `terraform apply`

### Additional Context
commenting out `depends_on = [null_resource.test]` allows the recipe to succeed

Full recipe folder available here: 
[test_terraform.tar.gz](https://github.com/hashicorp/terraform/files/5556903/test_terraform.tar.gz)

**Comment by jbardin** [comment]
Hi @innovate-invent,

Thanks for trying out the RC! 
In order to plan the `galaxy_repository` resource, the number of instances must be known during planning. Adding the `depends_on` for the module is forcing everything in the module to evaluated after `null_resource` is created the during apply. This means that the data source, is not known during plan, and it's not valid to use in a `for_each` expressions. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by innovate-invent** [comment]
Thanks, I see my mistake now. Perhaps output the dependency that is triggering the error to assist in debugging? In my case the depends_on was two modules up and very hard to locate.

**Comment by jbardin** [comment]
Thanks @innovate-invent, the error messages are definitely something we are always trying to improve. While we may be able to help debug these types of errors by improving the messages, it would be good to note that in general we recommend avoiding `depends_on` whenever possible, especially with modules. There is usually a more precise way to create the needed dependencies by threading the necessary data from those dependences to where it is required.

**Comment by innovate-invent** [comment]
The dependency was implicit but I was able to work around the issue using a null_resource:
```
data "null_data_source" "wait_on_microbedb" {
  depends_on = [docker_container.microbedb]
  inputs = {
    microbedb_path = var.microbedb_path
  }
}

module "galaxy" {
  source = "../galaxy"

  data_dir = var.data_dir
  instance = var.instance
  uwsgi_uid = var.uwsgi_uid
  uwsgi_gid = var.uwsgi_gid
  microbedb_path = data.null_data_source.wait_on_microbedb.outputs.microbedb_path
}
```
