### ISSUE TITLE
cmd/fmt: Avoid removing quotes from empty labels

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#26960]
### Terraform Version

```
0.14.0-beta2
```

### Terraform Configuration Files

```terraform
provider "" {
}
```

### Expected Behavior

`fmt` to leave the code as is.

### Actual Behavior

`fmt` removed quotes and therefore removed the empty label.

### Steps to Reproduce

**`v0.13`**
```
$ echo "provider \"\" {\n}\n" | terraform fmt -
```
```terraform
provider "" {
}
```

**`v0.14`**
```
$ echo "provider \"\" {\n}\n" | terraform fmt -
```
```
provider {
}
```

**Comment by alisdair** [comment]
Confirmed, thanks! Upstream fix is here: https://github.com/hashicorp/hcl/pull/422
