### ISSUE TITLE
State Management Within Terraform Code

### ISSUE THREAD

**Issue by dunnill** [hashicorp/terraform#26979]
### Current Terraform Version
12.29 (I've also looked at release notes etc for newer versions)

```
...
```

### Use-cases
Current state management is via commands e.g. _terraform state mv_.  This is a little painful when using a single deployment state i.e. not using workspaces or similar to deploy to multiple environments.  However if you are doing that then you have a multi-deployment whereby you must modify multiple state files at the same time.  This is far from desirable and also very difficult to track.

### Attempted Solutions
No solution beyond adding a script file to run before deployment - but this is too high risk in terms of failure plus not wieldy for workspaces.

### Proposal
I don't have the code implementation but I wondered if we could have:
```
resources "aws_instance" "foo" {
....
}
```
Is changed to:
```
resources "aws_instance" "foobar" {
....
}
```
Se we add
```
state "aws_instance" "foo" {
   moved = "aws_instance.foobar"
}
```
This `state` resource can then denote moved resources, deleted resources (so it will create a new one and ignore an old one), and import too.  They would need to be removed in the next commit but that is a small price to pay to have some change control around this.  It would also avoid the result `1000 additions` etc due to drift (resources created in console) as diff would note the state imports and have an `1000 state updates, 0 additions` or something to that effect.  I am aware that this would have a significant impact in terms of dependency as state updates would need to be considered first.  It also needs to consider move/import/deletions in submodules e.g. `terraform state mv module.x.module.y module.x.aws_instance.y` and similar.  Similarly an error would need to arise when someone forgets to remove the state changes.  

### References
There are a lot of questions around state management but nothing like the above idea.

**Comment by jbardin** [comment]
Hi @dunnill 

We are tracking this use case in issue #16860.

Thanks!
