### ISSUE TITLE
Prevent Terraform from destroying specific resource

### ISSUE THREAD

**Issue by TechGirl-3** [hashicorp/terraform#26972]
Hi,

I want to know if it is possible to prevent Terraform from destroying specific resources when doing "terraform destroy". 

Appreciate any suggestions.

**Comment by jbardin** [comment]
Hi @TechGirl-3 

If you as asking about adding features to help control resource destruction, we have an issue open for that at #24658.
If you are asking about the usage of [`prevent_destroy`](https://www.terraform.io/docs/configuration/resources.html#prevent_destroy) in general, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
