### ISSUE TITLE
Terraform Could not retrieve the list of available versions for provider hashicorp/azurerm

### ISSUE THREAD

**Issue by deepforu47** [hashicorp/terraform#26989]
### Terraform Version

  
```
Terraform version: 0.13.5 (Using Mac)
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output

2020/11/20 10:43:34 [INFO] Terraform version: 0.13.5  
2020/11/20 10:43:34 [INFO] Go runtime version: go1.14.7
2020/11/20 10:43:34 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/11/20 10:43:34 [DEBUG] Attempting to open CLI config file: /Users/kulsharm2/.terraformrc
2020/11/20 10:43:34 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/20 10:43:34 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/20 10:43:34 [DEBUG] ignoring non-existing provider search directory /Users/kulsharm2/.terraform.d/plugins
2020/11/20 10:43:34 [DEBUG] ignoring non-existing provider search directory /Users/kulsharm2/Library/Application Support/io.terraform/plugins
2020/11/20 10:43:34 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/20 10:43:34 [INFO] CLI command args: []string{"init"}

Initializing the backend...
2020/11/20 10:43:34 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/11/20 10:43:34 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/11/20 10:43:34 [DEBUG] New state was assigned lineage "afc22af1-561a-8530-4d38-d851cff88626"
2020/11/20 10:43:34 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/11/20 10:43:34 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/11/20 10:43:34 [DEBUG] checking for provisioner in "."
2020/11/20 10:43:34 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/11/20 10:43:34 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2020/11/20 10:43:34 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2020/11/20 10:43:34 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/11/20 10:43:34 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/11/20 10:43:34 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/11/20 10:43:34 [TRACE] statemgr.Filesystem: read nil snapshot
2020/11/20 10:43:34 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
2020/11/20 10:43:34 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins

Initializing provider plugins...
2020/11/20 10:43:34 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/11/20 10:43:34 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
- Finding hashicorp/azurerm versions matching ">= 2.26.*"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/azurerm: could not connect to registry.terraform.io: Failed to
request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": net/http: request
canceled while waiting for connection (Client.Timeout exceeded while awaiting
headers)

**Comment by nomoresecrets** [comment]
Having the same issue on CentOS /w TF 0.13.5
```bash-4.2$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "~> 2.36.0"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/azurerm: could not query provider registry for
registry.terraform.io/hashicorp/azurerm: the request failed after 2 attempts,
please try again later: Get
"https://registry.terraform.io/v1/providers/hashicorp/azurerm/versions": EOF```

**Comment by danieldreier** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions and generally helping troubleshoot issues people encounter while using Terraform. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

In this case, the most likely cause of your issue is a misconfigured network or proxy, though since you're on a Mac it is possible you are running into https://github.com/hashicorp/terraform/issues/3536.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
