### ISSUE TITLE
Yes/No deployment

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform#26980]
### Current Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.0.0
+ provider registry.terraform.io/hashicorp/azurerm v2.31.0
```

### Use-cases

You have a module that represents your application, and you deploy this application across environments. But there may be components that you may not want to deploy in certain environment: for example the application won't have a public IP when in development.

### Attempted Solutions

The only way I know of is using `count` attribute, but this not meant for yes/no purposes and might have many side effects. It also makes the code more complex.

The other solution is per-environment module, which defeats the purpose of modules.

### Proposal

Introduce additional attribute `deploy` which is `true`/`false` in nature (default `true`) exclusive to `count`, which allows you to clearly define the condition under which you wish to deploy this resource and simply pass it into the module. It also removes the need for many `[0]` indices on dependent resources.

Moreover, when a parent resource is explicitly set to `deploy=false`, all dependent resources should automatically take that into account and assume `false` as well.

### References

I did not find any similar suggestion here. I'm glad to hear your feedback.

**Comment by jbardin** [comment]
This appears to be the same use case as #26811

Thanks!
