### ISSUE TITLE
import using different account for state and provider fails

### ISSUE THREAD

**Issue by visheyra** [hashicorp/terraform#26993]
Hi,

The import command does not look like it uses the default provider when importing resource.

I have a simple with a remote state hosted in an s3 bucket in account A and my resource is being deployed on account B. My config looks like this:

```
terraform {
  backend "s3" {
    bucket = "tf-bucket-remote-state" # available in account A, AWS_PROFILE env var is set to this account
  }
}

provider "aws" {
  access_key = "something" # id to access the B account
  secret_key = "somethingelse" # key to access the B account
  region = "eu-west-1"
}
```

When importing my resource the following error occurs:
*where XXXXXX is my resource anonymized*

```
Error: error reading XXXXXXXXXXXX: Forbidden: Forbidden
```

When using the key manually to check the bucket I can access it. Is used to use the `-provider` switch on terraform import before to avoid this issue but I just noticed it's being deprecated. This looks like a regression according to the fact that this behaviour was implemented following this [issue](https://github.com/hashicorp/terraform/issues/10029).

### Terraform Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.13.0
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {
    bucket = "tf-bucket-remote-state" # available in account A, AWS_PROFILE env var is set to this account
  }
}

provider "aws" {
  access_key = "something" # id to access the B account
  secret_key = "somethingelse" # key to access the B account
  region = "xxxxxx"
}
```

### Debug Output

see this [anonymized gist](https://gist.github.com/visheyra/df4b6d5a7866c3816fbcbfcfbab456be)

### Crash Output
Not applicable, terraform did not crash

### Expected Behavior

The import should works

### Actual Behavior

The import did not succeed

### Steps to Reproduce
1. use a configuration that has a remote backend in an AWS account A
2. configure the provider to create a resource in account B
3. import a resource using this provider

### Additional Context
terraform in that case is run from my local machine (linux).

### References
* https://github.com/hashicorp/terraform/issues/10029
* https://github.com/hashicorp/terraform/pull/10310

**Comment by apmarshall** [comment]
Just checking to see: are you still experiencing this issue?

**Comment by cvirtucio** [comment]
We're experiencing similar behavior, but with roles instead of access keys. Looking at our trace logs, it seems that when it tries to upload terraform state:

```
2022-08-22T21:49:17.258Z [DEBUG] Uploading remote state to S3: {
```

at no point does it switch back to the role set for the backend in the `terraform` block. This is the only identity-related call that we see in the logs preceding the state upload attempt:

```
2022-08-22T21:49:16.448Z [DEBUG] provider.terraform-provider-aws_v4.26.0_x5: <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
2022-08-22T21:49:16.448Z [DEBUG] provider.terraform-provider-aws_v4.26.0_x5:   <GetCallerIdentityResult>
2022-08-22T21:49:16.448Z [DEBUG] provider.terraform-provider-aws_v4.26.0_x5:     <Arn>*arn used for the role used in the provider block*</Arn>
```

**Comment by gdavison** [comment]
Are you still seeing this issue? The AWS Provider and the S3 backend authenticate their connections separately, but if environment variables are used, they will use the same variables. However, the AWS Provider v4 introduced some changes which will be part of the S3 backend in Terraform v1.6.

If you are seeing the problem, please include the following:
1. The Terraform configuration used
2. Which environment variables have been set
3. A debug log including the AWS Provider authentication steps and the S3 backend operations

**Comment by gdavison** [comment]
I'm going to assume that this is no longer a problem since there has been no response.

If you still see this problem, please open a new issue and include 

1. The Terraform configuration used
2. Which environment variables have been set
3. A debug log including the AWS Provider authentication steps and the S3 backend operations
