### ISSUE TITLE
CLI interface to setting variables

### ISSUE THREAD

**Issue by robparrott** [hashicorp/terraform#270]
The format of the tfvars files is a source of user error, and there may be features around organizing variables which will require a more complex file format than the current (such as global variables versus project local, variables which pertain to specific environments such as "dev"/"test"/"prod" etc.)

As such, it would make the user experience simpler to introduce a a simpler CLI to managing a vars file (which becomes more like a simple persistence layer for parameters).  Global vars could be stored in a file under `~/.terraform` and local vars in the cwd.

This syntax may look like this
```
terraform variable set foo bar
terraform variable list 
terraform variable unset foo
terraform variable get foo
```

For reference, I'll point to the project we started last year (and which terraform may now make obsolete):

- https://github.com/huit/nepho

**Comment by phinze** [comment]
This is still a nice idea, and we'd welcome PRs to this effect, but judging by the inactivity here it's unlikely the core team is going to picking this up any time soon, so I'm going to close this for now. :+1:
