### ISSUE TITLE
aws_launch_configuration enable_monitoring option is not obeyed

### ISSUE THREAD

**Issue by antonosmond** [hashicorp/terraform#2700]
I have a terraform config for an AWS launch configuration which contains the following line:
`  enable_monitoring = false`
as per the docs:
https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#enable_monitoring
On running terraform apply,  the following line appears in the output:
`  enable_monitoring:           "" => "0"`
However once the apply has completed and I view the instance in AWS, detailed monitoring is enabled.
I'm running terraform v0.6.0 on Mac OS X 10.10.4

**Comment by catsby** [comment]
Hey @antonosmond – thanks for reporting this. I just patched this recently and the fix will go out in the next release, which should be in the next few days. The fix was in https://github.com/hashicorp/terraform/pull/2735 , if you're curious. 

Thanks again!

**Comment by antonosmond** [comment]
Awesome stuff thanks for the update! Can't wait for the next release I was
wondering when it would come.
