### ISSUE TITLE
Dependencies from v3 -> v4 State

### ISSUE THREAD

**Issue by xescugc** [hashicorp/terraform#27020]
### Terraform Version

```
0.13.5
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

To migrate (if possible) dependencies from State v3 -> v4

### Actual Behavior

Not migrating them even if they are read from the TFState

### Additional Context

Basically I know that the `depends_on` has been dropped and moved to `dependencies` and on this commit https://github.com/hashicorp/terraform/commit/9fe87fe520760c7139436dd4f7b059086ce0ba23 it was removed from the v3->v4 which IDK if it was intentional (https://github.com/hashicorp/terraform/commit/9fe87fe520760c7139436dd4f7b059086ce0ba23#diff-3736e46b6f903757c3c43803e893c47b659e961020e674b63d701235cd00fe6dL373).

The `dependencies` are calculated but then they are not used (https://github.com/hashicorp/terraform/blob/master/states/statefile/version3_upgrade.go#L339) so I'm curious about them:
* Should they be migrated to v4? "Basically" instead of `DependsOn:      dependencies,` do `Dependencies:      dependencies,`. This fails if I try to do it with `Invalid address: A resource address is required here. The module path must be followed by a resource specification.`
* Not migrate them and remove that code and potentially document it somewhere as it's not clear and IDK if it would generate other errors.

The TFState I'm using as reference it's a `terraform_version: 0.11.14`.

I'm also basically using `statefile.Read`, I know Terraform is not meant to be used as a lib, but this behavior is not expected and would happend anyway using it normally.

**Comment by jbardin** [comment]
Hi @xescugc 

The contents of the fields are not directly transferrable, and in most cases will not match, so there is no reason to migrate them from the old state version. Upgrading the terraform state requires more than the translation from the previous state format, it also requires successfully applying the configuration to ensure that the state contains all the necessary information. 

Thanks!

**Comment by xescugc** [comment]
Ok then I would suggest to clean the https://github.com/hashicorp/terraform/blob/master/states/statefile/version3_upgrade.go#L339 as it's not used :).
