### ISSUE TITLE
Need to run multiple "terraform imports" with same tfstatefile

### ISSUE THREAD

**Issue by kvyas248** [hashicorp/terraform#27027]
### Current Terraform Version

```
0.13.5
```

### Use-cases

Improve the performance of importing multiple resources.

### Attempted Solutions

Tried invoking multiple terraform imports from golang routines. Sometimes it imports only 1 resource and sometimes it doesnt import anything.  The probable reason for the same is the race condition for writing the import results to "terraform.tfstate" file. 
### Proposal

Terraform can run multiple terraform imports to different .tfstate files and merge it to single file as final output.

**Comment by jbardin** [comment]
HI @kvyas248,

Batch import via configuration is something we're looking into. You can track the issue via #26364

Thanks!
