### ISSUE TITLE
-target option doesn't work

### ISSUE THREAD

**Issue by cosminstirbu** [hashicorp/terraform#27032]
`-target` option doesn't work.

Given the sample script below (please notice that this sample is just for reproducing the issue)

```
# Configure the Azure provider
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">= 2.26"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "myTFResourceGroup"
  location     = "westus2"
}
```

Run `terraform plan -target=azurerm_resource_group` and notice the following error

```
Usage: terraform plan [options] [DIR]

  Generates an execution plan for Terraform.

  This execution plan can be reviewed prior to running apply to get a
  sense for what Terraform will do. Optionally, the plan can be saved to
  a Terraform plan file, and apply can take this plan file to execute
  this plan exactly.

Options:

...
```

### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.36.0
```

The issue reproduces both using Ubuntu (bash) and Windows 10 (Powershell)
### Expected Behavior

`-target` parameter should work

### Actual Behavior
`-target` doesn't work

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -target=azurerm_resource_group`

**Comment by alisdair** [comment]
Hi @cosminstirbu, thanks for reporting this. I think there are two problems here: an incorrect `-target` parameter, and a missing error message when this is the case. The correct command here would be `terraform plan -target=azurerm_resource_group.rg`.

The second issue is tracked in #26786, where the error message for an invalid `-target` parameter is being suppressed. I'm closing this as a duplicate, and feel free to subscribe to the other issue for updates.

**Comment by cosminstirbu** [comment]
I was just looking over https://github.com/hashicorp/terraform/issues/26786 and realised that I may be using an invalid resource.

Thank you for looking into this!
