### ISSUE TITLE
Lifecycle option to keep/retain/detach resources on destroy

### ISSUE THREAD

**Issue by WilliamABradley** [hashicorp/terraform#27035]
### Current Terraform Version

```
Terraform v0.13.3
```

### Use-cases

This feature would cover multiple use cases.

- If you are destroying an environment, and you would like to keep a resource, then this would allow you to always unlink the resource from the Terraform state, without having to perform the terraform state rm command prior.
- If this is a resource that will be destroyed anyway by a parent resource, a CDN Config resource, it will be destroyed regardless when you destroy the CDN, Kubernetes resources, etc, so destroying it beforehand is just wasting time.
- If there is a resource that is failing to destroy due to some external dependency, that makes it impossible to destroy, e.g. an AWS Edge Lambda, Postgres Role attached to a database, etc. Perhaps it will be destroyed due to a parent resource, so it would be nice to have the option.

This also matches Cloudformation's Deletion Policy option which allows you to do this.

### Attempted Solutions

`terraform state rm` achieves this, but it is inconvenient as you have to perform those commands each time, and add scripting.

### Proposal

**Style 1: Combine with prevent_destroy**

```terraform
resource "provider_resource" "resource" {
  lifecycle {
    on_destroy = "delete" | "retain" | "prevent/fail"
  }
}
```

**Style 2: Retain prevent_destroy, but have more than one destroy property**
```terraform
resource "provider_resource" "resource" {
  lifecycle {
    detach_on_destroy = true
    # Could have both at the same time? prevent_destroy = true
  }
}
```

**Comment by innovate-invent** [comment]
I would like to see something along the lines of `destroyed_with = <parent resource reference>` that marks the resource as destroyed if the referred resource is destroyed

**Comment by innovate-invent** [comment]
my suggestion specifically refers to the second use case

**Comment by daraul** [comment]
I like the `on_destroy = "retain"` option. 

It gets me around a problem I have where I found myself `destroy`ing my `gandi_livedns_domain` resource while testing. When I attempt to `apply` I get an error stating that the domain already exists; terraform doesn't know about it, so it attempts to create one. 

I am not sure if this would be considered a bug in the provider, but being able to tell terraform "don't destroy this resource even if I tell you to destroy everything" sounds reasonable in cases like this.

**Comment by innovate-invent** [comment]
@daraul that is certainly a bug in the provider. If the provider reports that it has destroyed gandi_livedns_domain, yet the object remains then that is a failure of the provider.

**Comment by Michael-McClelland** [comment]
This would be extremely helpful for resource teardown in situations where certain resources cannot be deleted due to security constrains.  Many development paradigms at large organizations constrain deletion of certain resources entirely and also restrict directly running commands to alter state.  This feature would significantly reduce friction in those situations.

**Comment by dotdc** [comment]
+1 for `on_destroy = "retain"`

**Comment by fatbasstard** [comment]
+1 from me!

I'm looking for a way to "abandon" a resources in 30+ workspaces (same codebase). It's a github repository that's now "archived" and I want to get it out my Terraform configuration with leaving the archived repositories out in the wild...

Terraform indeed has the "retain" option (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html).

I want this. Now I have to go through 30 remote states to do an `terraform rm` while simultaniously removing the resource from code. While making sure nobody else starts a TF run....

**Comment by dotdc** [comment]
Good news! 
We're probably going to have a real chance to discuss this topic once the fork will be available at:
https://github.com/opentffoundation
I encourage everyone to reopen their issues there 😊

**Comment by iancward** [comment]
I like how opentofu has a `removed` block; that seems to follow the existing `moved` and `import` blocks, and allows you to document that a removal happened in later versions of code.

https://opentofu.org/docs/intro/whats-new/#removed-block

**Comment by iancward** [comment]
It looks like there is a [removed](https://developer.hashicorp.com/terraform/language/resources/syntax#removing-resources) block, but it seems buried in the documentation and my initial searches didn't find it.

**Comment by crw** [comment]
Thanks, indeed removed block should cover this use case. If anyone has related or more nuanced issues surrounding this issue, please open a new ticket. Thanks very much!

**Comment by autarchprinceps** [comment]
removed block isn't really helpful, as it needs to be specified after the fact individually and e.g. outside modules, more like an import, whereas deletion policy in cloudformation or its equivalent suggested here would be specifying on the resource that it should preserved, even when you delete entire modules or the like, whereas prevent_destroy lifecycle errors in your apply instead of only removing the state without touching the real infrastructure.
