### ISSUE TITLE
0.14.0-rc regression: opinionated formatting creates syntax errors with parentheses

### ISSUE THREAD

**Issue by aaronsteers** [hashicorp/terraform#27040]
### Terraform Version

```
Terraform v0.14.0-rc1
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.17.0
+ provider registry.terraform.io/hashicorp/http v2.0.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0```
```

### Terraform Configuration Files

```terraform
locals {
  value_a = ([
    [1,2,3],
    [1]
  ])
  value_b = 4
}
```

### Actual Behavior

Code is formatted into uncompilable code which will subsequently fail basic code validation. Specifically this seems to occur when code has surrounding parenthesis. Those parenthesis are likely not necessary but they otherwise would not block compilation until after auto-format is applied.

The below output is generated from the above sample. Note the paren incorrectly placed ahead and inline with the next statement.

```terraform
locals {
  value_a = ([
    [1, 2, 3],
    [1]
    ]
  ) value_b = 4
}
```

### Expected Behavior

Applying `terraform fmt` should not create syntax errors or otherwise create code that then would fail validation.

One or (ideally) both of the following should occur:
1 - In general, `terraform fmt` would render everything as expected, without error.
2 - Adopting a pessimistic approach to (1), `terraform fmt` should attempt a compile check post-operation - and the format operation should fail if code cannot compile. This check already is performed beforehand and `terraform fmt` will abort if code cannot be initially compiled. Ideally, the same check would occur afterwards which already is performed beforehand.

### Steps to Reproduce

1. Apply `terraform fmt` to code containing parenthetical groupings such as in the example above.

### Additional Context

Also documented here in Discuss thread: https://discuss.hashicorp.com/t/terraform-v0-14-0-rc1-released/15752/15

**Comment by alisdair** [comment]
Hi @aaronsteers, thanks for reporting this. I've confirmed the issue on 0.14.0-rc1.

**Comment by aaronsteers** [comment]
@alisdair - thanks so much!!

**Comment by aaronsteers** [comment]
One thing I just realized here - since in most (maybe all?) instances where I found this the parenthesis were for readability and not necessary required, it might be a reasonable fix for the formatter to simply remove the parentheses. This would be similar behavior to what the python "black" formatter does with extraneous parenthetical groups.

**Comment by apparentlymart** [comment]
I expect (but have not yet confirmed) that this bug is in the `hclwrite` package in the HCL module, with that final newline somehow ending up being incorporated into the expression and thus being removed. Either way, I expect we'd want to start here by fixing the immediate problem (it's making the configuration invalid by removing a significant newline) and save further adjustments that it might otherwise make for a separate change.

**Comment by aaronsteers** [comment]
@apparentlymart - I don't know anything about this module but I did some digging and found this issue tagged to `hclwrite`: https://github.com/hashicorp/hcl/issues/402

Seems like same root cause. I'll cross-link just in case they are same.

**Comment by apparentlymart** [comment]
The change in hashicorp/hcl#426 should address this, once it's included in an HCL release and we've upgraded our dependency here in Terraform.

**Comment by wyardley** [comment]
Another example of something that seems to be affected by this would be something like:
https://github.com/forseti-security/terraform-google-forseti/blob/524e684a4bac0b3af9ed8e3035bcb12a992e3d1b/modules/server_config/main.tf#L35

**Comment by aaronsteers** [comment]
@wyardley - In your very simple example, yes, I believe removal of the parenthesis is a good fix.

The guideline I've started using for myself is to _not_ use parenthesis unless I am trying to force order of operations, or unless the expression covers multiple lines and the parenthesis are needed for logical grouping. (I'm still not entirely sure how to properly deal with multi-line expressions in hcl.)

I'm curious if others have best practice guidelines for when to use parenthesis - I haven't found a lot of documentation on this topic, tbh.

**Comment by apparentlymart** [comment]
It is a valid thing to use parentheses solely to allow an expression to wrap over multiple lines, but of course that's the very situation that this bug affects so for now you'll either need to hold off for 0.14.1 or not wrap your expressions over multiple lines.

There are some other ways to get into the mode where the parser will accept newlines -- any sort of brackets will do it -- but the result will look weird so I'd probably not do it just to avoid the confusion it might cause if left that way for too long. For example:

```hcl
  example = [
    # any single expression here, to make a single-element list
  ][0] # then take the first element of the list
```

**Comment by aaronsteers** [comment]
@apparentlymart. That's very helpful; thank you!

For our purposes, and in case it helps anyone else, we've decided to move forward using 0.14.0 with the following mitigations: (1) we've simply remove parenthesis in simple examples when not needed, and (2) for more complex expressions, we either add workarounds like the above or just refrain from auto-formatting those files.

It turns out most of our cases fit into the first category, and only a small handful strictly do require parenthesis as multi-line expressions.
