### ISSUE TITLE
version 0.13.5 unsupported arguments for S3 backend 

### ISSUE THREAD

**Issue by msuzoagu** [hashicorp/terraform#27051]
### Terraform Version
```
Terraform v0.13.5
```

### Terraform Configuration Files
Given  that **s3.backend.tf** contains:
```
bucket      = "bucket_name"
key            = "key_path"
region       = "aws_region"
encrypt     = true
dynamodb_table = "litafi-terraform-state-db"
```

And **main.tf** contains: 
```terraform 
provider "aws" {
  version = "2.47.0"
  region  = var.aws_region
  profile = var.aws_profile
  shared_credentials_file = "~/.aws/credentials"
}

terraform {
  backend "s3" {
  }
  
  required_version = ">=0.13.5"
}
```
### Debug Output

$ terraform init -backend-config=s3.backend.tf

```
terraform init -backend-config=s3.backend.tf 
2020/11/29 13:02:44 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/11/29 13:02:44 [INFO] Terraform version: 0.13.5  
2020/11/29 13:02:44 [INFO] Go runtime version: go1.14.12
2020/11/29 13:02:44 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init", "-backend-config=s3.backend.tf"}
2020/11/29 13:02:44 [DEBUG] Attempting to open CLI config file: /Users/uzo/.terraformrc
2020/11/29 13:02:44 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/29 13:02:44 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/29 13:02:44 [DEBUG] ignoring non-existing provider search directory /Users/uzo/.terraform.d/plugins
2020/11/29 13:02:44 [DEBUG] ignoring non-existing provider search directory /Users/uzo/Library/Application Support/io.terraform/plugins
2020/11/29 13:02:44 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/29 13:02:44 [INFO] CLI command args: []string{"init", "-backend-config=s3.backend.tf"}
2020/11/29 13:02:44 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported argument

  on s3.backend.tf line 5:
   5: bucket  = "bucket_name"

An argument named "bucket" is not expected here.


Error: Unsupported argument

  on s3.backend.tf line 6:
   6: key  = "key_path"

An argument named "key" is not expected here.


Error: Unsupported argument

  on s3.backend.tf line 7:
   7: region         = "aws_region"

An argument named "region" is not expected here.


Error: Unsupported argument

  on s3.backend.tf line 8:
   8: encrypt        = true

An argument named "encrypt" is not expected here.


Error: Unsupported argument

  on s3.backend.tf line 9:
   9: dynamodb_table = "table_name"

An argument named "dynamodb_table" is not expected here.
```

### Expected Behavior
-  Given the instructions [here](https://github.com/hashicorp/terraform/issues/26152), [here](https://github.com/hashicorp/terraform/issues/25953), and [here](https://github.com/hashicorp/terraform/issues/25976)
- I expect to run `terraform init -reconfigure -backend-config part_to_key_value_file` and
- Terraform to initialize normally

### Actual Behavior
Terraform throws an unsupported block type error

### Steps to Reproduce
1. Install Terraform version 0.13.5 
2. Setup an S3 backed and s3.backend.tf file
3. run `terraform init`

### Additional Context
- none

### References
- #26152
- #25953
- #25976

**Comment by elmehalawi** [comment]
I'm having the same problem with 0.13. The arguments it's complaint about though are:

```terraform
skip_requesting_account_id  = true
skip_credentials_validation = true
skip_get_ec2_platforms      = true
skip_metadata_api_check     = true
```

All of which are required to use Digitalocean's S3 service. I had to downgrade to 0.12 to get this working.

**Comment by jbardin** [comment]
Hello,

All files in the configuring directory with the `.tf` extension are loaded as terraform configuration files. Because the syntax of the `s3.backend.tf` is not a valid configuration file, you get the errors seen here. Many users use the `.tfvars` extension by convention, just be aware of the names that are loaded by defaulted, which are listed here: https://www.terraform.io/docs/configuration/variables.html#variable-definitions-tfvars-files

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
