### ISSUE TITLE
json plan prior state fails to marshal with incompatible schema

### ISSUE THREAD

**Issue by kylet21** [hashicorp/terraform#27065]
### Terraform Version

```
0.13.5
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output
In the state file you can see the instance having both the old and new attributes set to the same value (`role` and `roles`):
```
{
      "module": "XXXXX",
      "mode": "managed",
      "type": "aws_iam_instance_profile",
      "name": "main",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "XXXXX",
            "create_date": "2020-08-07T19:41:14Z",
            "id": "XXXXX",
            "name": "XXXXX",
            "name_prefix": null,
            "path": "/",
            "role": "ecs-123456",
            "roles": [
              "ecs-123456"
            ],
            "unique_id": "XXXXX"
          },
          "private": "XXXXX",
          "dependencies": [
            "XXXXX",
            "XXXXX"
          ]
        }
      ]
    },
```

### Expected Behavior
Old attribute `roles` to be removed or ignored and the diff to work successfully.

### Actual Behavior
Plan errors:
```
Plan: 63 to add, 24 to change, 54 to destroy.
Failed running command "cd '/terraform' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 1)
Output: Failed to marshal plan to json: error marshaling prior state: unsupported attribute "roles"
```
### Steps to Reproduce
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_iam_instance_profile

1. Create resources and state using old provider version and argument (`roles`) 
2. Remove deprecated argument and set value using new argument (`role`)
3. Attempt to plan after upgrading to new provider version with deprecated argument

### References
May be related to this issue: https://github.com/hashicorp/terraform/issues/23297

**Comment by jbardin** [comment]
Hi @kylet21 

Thanks for filing the issue! It does seem the json plan output attempts to marshal the prior state using the current schema, which may often fail. 

Since this is only a problem with `terraform show -json`, you should be able to work around this by running an apply manually without that step. If it's possible to run a separate `terraform refresh`, that should update the state to the newest schemas as well.

**Comment by jbardin** [comment]
Hi @kylet21,

I confirmed that this issue no longer happens in the current development version of terraform. It is still possible to get the error seen here when attempting to show the prior state with a newer version of the provider, but that is expected when the stored state schema does not match the current provider until the state is upgraded.
