### ISSUE TITLE
Deprecate s3 remote backend lock table with new strong consistency

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform#27070]
### Current Terraform Version

```
0.13.5
```
### Proposal

Terraform currently requires the usage of a DynamoDB table for state file locking due to consistency requirements that have previously been impossible in S3 directly as it has eventual consistency on read after write. The GCS backend, however, is able to avoid this extra mechanism and just write the lock file to the GCS bucket as GCS provides strong read after write consistency.

AWS have announced that S3 will now support strong read after write consistency: https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

I think this means that the DynamoDB lock table is now unnecessary and the same approach as the GCS backend can be used here to write the lock file directly to S3.

This should simplify the usage of Terraform's S3 backend as it removes an extra component.

I'd propose aligning the S3 backend with the GCS backend so it uses the lock file in S3 and marks the `dynamodb_table` argument as deprecated in 0.14 releases. I'd then propose removing the `dynamodb_table` argument altogether in 0.15/1.0.

### References

- https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/
- https://www.terraform.io/docs/backends/types/s3.html
- https://www.terraform.io/docs/backends/types/gcs.html

**Comment by tomelliff** [comment]
If there's interest in this I might have some time to contribute the change on Friday.

**Comment by pkolyvas** [comment]
@tomelliff Thanks for the proposal!

The AWS team here at HashiCorp maintain our S3 remote state backend. They're probably a little busy with re:invent going at the moment so I'm not sure they'll have a chance to review and weigh this by Friday, but I'll bring it to their attention.

**Comment by tbugfinder** [comment]
I'm curious if this could make it into 0.15.0 :-)

**Comment by tdmalone** [comment]
Related:
> We’ve not yet done any research to see if S3’s new guarantees are sufficient for that model to be safe, and I also want to be transparent that this isn’t an area we’re actively working on: the existing S3/DynamoDB solution is working and meeting the use-case, so our efforts are naturally focused on other situations that are not yet solved.

https://discuss.hashicorp.com/t/feature-request-terraform-state-locking-in-aws-with-s3-strong-consistency-no-dynamodb/18456/8

**Comment by kennedyjustin** [comment]
@pkolyvas Any timeline updates here?

**Comment by dcloud9** [comment]
Correct me if wrong, but shouldn't this S3-strong-consistency tfstate locking improvement be done in Terraform core itself as opposed to the AWS provider codebase?
I can see in [GCS state locking code](https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/gcs/backend_state.go) this snippet
```golang
const (
	stateFileSuffix = ".tfstate"
	lockFileSuffix  = ".tflock"
)
```
So in [S3 state locking code](https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/s3/backend_state.go), is where the DynamoDB table is looked up to.
```golang
// get a remote client configured for this state
func (b *Backend) remoteClient(name string) (*RemoteClient, error) {
	if name == "" {
		return nil, errors.New("missing state name")
	}

	client := &RemoteClient{
		s3Client:              b.s3Client,
		dynClient:             b.dynClient,
		bucketName:            b.bucketName,
		path:                  b.path(name),
		serverSideEncryption:  b.serverSideEncryption,
		customerEncryptionKey: b.customerEncryptionKey,
		acl:                   b.acl,
		kmsKeyID:              b.kmsKeyID,
		ddbTable:              b.ddbTable,
	}

	return client, nil
}
```
Reference:
> Object Lock
Store objects using a write-once-read-many (WORM) model to help you prevent objects from being deleted or overwritten for a fixed amount of time or indefinitely.

**Comment by tomelliff** [comment]
@dcloud9 this is proposed for Terraform core because that's where all the remote backends live right now. What made you think it was a suggestion for the AWS provider?

**Comment by dcloud9** [comment]
@tomelliff Nothing, just asking for confirmation :point_up: . Thanks for confirming that there's an AWS team within Terraform core or maybe it's a shared resource for AWS provider as well.

**Comment by shanedabes** [comment]
Assuming this issue is acknowledged, what does this mean for people using s3 compatible storage like minio?

**Comment by tomelliff** [comment]
> Assuming this issue is acknowledged, what does this mean for people using s3 compatible storage like minio?

How does that currently get used with the lock table? Still using DynamoDB? Using DynamoDB Local?

Also, this looks like it would just work with MinIO anyway as it [already has strict read after write consistency on non NFS filesystems](https://docs.min.io/docs/distributed-minio-quickstart-guide.html):

> **Consistency Guarantees**
> MinIO follows strict read-after-write and list-after-write consistency model for all i/o operations both in distributed and standalone modes. This consistency model is only guaranteed if you use disk filesystems such as xfs, ext4 or zfs etc.. for distributed setup.
>
> If MinIO distributed setup is using NFS volumes underneath it is not guaranteed MinIO will provide these consistency guarantees since NFS is not consistent filesystem by design (If you must use NFS we recommend that you atleast use NFSv4 instead of NFSv3).

**Comment by binlab** [comment]
@tomelliff @pkolyvas any update on this? Thanks!

**Comment by dmccue** [comment]
pulumi implements s3 lock files, dynamodb locks are superfluous

**Comment by yann-soubeyrand** [comment]
Hello,

Are you sure that strong consistency allows achieving locking? As far as I understand, this strong consistency doesn’t prevent to concurrent processes to write a lock file simultaneously and latest wins. So there’s still race condition where two concurrent processes think they’ve locked the state, isn’t it?

Reference: https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel
> Amazon S3 does not support object locking for concurrent writers. If two PUT requests are simultaneously made to the same key, the request with the latest timestamp wins. If this is an issue, you must build an object-locking mechanism into your application.

**Comment by dmccue** [comment]
S3 is no longer eventually consistent, it's consistent on write so if you were to generate a lock file in S3, it would be an atomic action. This wasn't the case 3-4 years ago which is why dynamodb was used.
Pulumi uses S3 lock files

**Comment by crw** [comment]
See also: https://github.com/hashicorp/terraform/pull/31454

**Comment by gdavison** [comment]
Hello all. According to the AWS documentation on concurrency in the S3 data consistency model (https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel), we are not able to rely on the read-after-write consistency for locking.

The documentation notes that
> Amazon S3 does not support object locking for concurrent writers. If two PUT requests are simultaneously made to the same key, the request with the latest timestamp wins. If this is an issue, you must build an object-locking mechanism into your application.

We will reconsider this feature if the S3 consistency guarantees change in the future.

**Comment by dude0001** [comment]
This makes sense. Thank you for commenting.

**Comment by bschaatsbergen** [comment]
Picking this up under #35625, now that S3 supports conditional writes.
