### ISSUE TITLE
Add support for single variables in a dynamic block, not just blocks.

### ISSUE THREAD

**Issue by silvermy** [hashicorp/terraform#27083]
### Current Terraform Version

```
Terraform v0.12.28
```

### Use-cases

```
module 'x' {
  dynamic {
      for_each = var.variables
      key = each.key
      value = each.value  
  }
}
```

### Attempted Solutions

N/A

### Proposal
See use case.
Would be great if this worked for any resource, not just module invocations.

### References

N/A

**Comment by apparentlymart** [comment]
Hi @silvermy,

It's not clear from your write-up here what you are suggesting. When we ask for a use case what we are looking for is a description of an underlying problem you were aiming to solve but which you could find no existing Terraform feature to address. Without a clear use-case, we can't evaluate the proposal you've made in order to meet that proposal.

Can you say a little more about what you're trying to achieve here? Thanks!

**Comment by silvermy** [comment]
I would like to generate a spinnaker terraformer stage to call an arbitrary HashiCorp terraform module without knowing about the variables it requires, rather allowing my consumer to pass variables matching the module that is going to be used (the source of which they also pass.)

My script would set up a tfvars file containing variables needed for a wrapper terraform file that would look something like this:

```
variable "module_source" {}
variable "vars" { default = { var1: "val1", var2: "val2"} } # default is just to show the semantics, I would expect the value to be a tfvars file.

module "module" {
  source = var.module_source
  dynamic
     for_each = var.vars
     name = each.key
     value = each.value
  }
}
```

This would "expand" to:

```
module "module" {
  source = var.module_source
  var1 = "val1"
  var2 = "val2"
}
```

**Comment by apparentlymart** [comment]
Hi @silvermy,

Thanks for the additional context.

The typical way to address the problem of passing opaque data items through a module to be processed elsewhere is to define a single variable to accept all of the data, like this:

```hcl
variable "vars" {
  type = any

  # optionally, you can write "validation" blocks here to
  # apply certain constraints to the value, if the value
  # isn't _truly_ opaque/arbitrary.
}
```

Then when you call the module you can just pass your input variable through to the module directly:

```hcl
variable "vars" {
  type = any
}

module "module" {
  source = "..."

  vars = var.vars
}
```

I think this existing mechanism should meet your use-case. Can you confirm whether that's true and let me know if there's anything else in your requirements that makes this answer unsuitable? Thanks!

**Comment by mildwonkey** [comment]
I'm going to close this, since there hasn't been a response, but if you are still experiencing a problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
