### ISSUE TITLE
Add a meta variable to module invocation to allow multiple variables in an object..

### ISSUE THREAD

**Issue by silvermy** [hashicorp/terraform#27082]
### Current Terraform Version

```
Terraform v0.12.28
```

### Use-cases
I would like to call terraform with a tfvars file where one of the variables can be used as multiple variables to a module invocation (and possible all resources.)

E.g.
```
x.tfvars:
v = { subnets: ["a", "b"], security_groups: [ "a" ], delay: 10 }

x.tf:
#...
module "x" {
  variables var.v
  offset = 20
}
#...
```

### Attempted Solutions

N/A

### Proposal

Add meta variable for use in module invocations, or possible all resources, called `variables` which contains a map of key, value where key is the name of the variable and value is the value.  It might also handle blocks by making the value a map.

Specifying a variable directly as well as in a variables meta variable would prefer the direct variable or generate an error.

Multiple variables meta variables could be specified as well in a single module invocation / resource.

### References

N/A

**Comment by apparentlymart** [comment]
Hi @silvermy! Thanks for this feature request.

The existing way to do this is to define a single complex-typed variable in each of your modules. If you make them all have compatible types then you can just pass the whole object to a child module as a single argument:

```hcl
# Put this declaration both in your root module and in your child
# modules that will accept the same data.
variable "v" {
  type = object({
    subnets         = set(string)
    security_groups = set(string)
    delay           = number
  })
}

# In your root module, pass through the given object.
module "x" {
  source = "..."

  v      = var.v
  offset = 20
}

```

This is already possible in Terraform today (was introduced in Terraform v0.12), so I'm going to close this. If you have any more questions about the above, please start a topic in [the community forum](https://discuss.hashicorp.com/c/terraform-core). Thanks again!
