### ISSUE TITLE
Event Hub disaster recovery alias connection is not set when running deployment for the first time.

### ISSUE THREAD

**Issue by WarAngelos** [hashicorp/terraform#27086]
Hi, 

I am trying to deploy Event Hub with Namespace.

Here is what I have done
```
Deploy Primary Namespace
Then Secondary Namespace
Then Disaster Recovery Config
Output alias connection string using Primary Namespace
```

I am trying to output `azurerm_eventhub_namespace.primaryNamespace.default_primary_connection_string_alias`

However, this outputs ""... An empty string

I checked the state file and noticed that `default_primary_connection_string_alias is ""`

if I run terraform apply again then all of this works fine, and alias connection string is returned correctly (Probably because it does a refresh for all states at the beginning.

so, it seems to me when I first create the primary namespace this state is set and not updated when disaster recovery config has completed.

I tried to google if there is anything that can be added after DR completes and before output to refresh the state of primary namespace.
or if there is even anything like ListKeys for terraform like there is for ARM, but no luck.

If anybody knows a fix/workaround for this (except running terraform apply again) or if I am doing something wrong, please let me know.

P.S. I didn't actually want to raise a bug when I don't know if it is one, but I could not find a place to ask.

**Comment by jbardin** [comment]
Hi @WarAngelos 

You can ask question in the [community forum](https://discuss.hashicorp.com/), which has a separate category for [Azure](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) if it's provider specific. 

If you need to raise an issue with the azurerm provider, you can do so in that project's [github repository](https://github.com/terraform-providers/terraform-provider-azurerm/). 

Thanks!
