### ISSUE TITLE
Add a command line flag to terraform plan/apply/output/etc.. to use the backend provisioner

### ISSUE THREAD

**Issue by silvermy** [hashicorp/terraform#27084]
### Current Terraform Version
```
Terraform v0.12.28
```

### Use-cases

Often the backend and the terraform execution itself use the same credentials.  It would be nice to avoid specifying the credentials twice, once for the terraform init command and once for the terraform command itself.

### Attempted Solutions

N/A

### Proposal

Add a command line argument `-use-backend-provisioner` that would be the default provisioner for the resources for which it works in the .tf files.

### References

N/A

**Comment by apparentlymart** [comment]
Hi @silvermy,

Although you said "provisioner" here I think what you are meaning to suggest is a way to share credentials between the `hashicorp/aws` provider and the `s3` backend. Is that correct?

If so, the current answer to that is to configure your AWS credentials in one of the standard ways _outside_ of Terraform. That could mean the usual environment variables (`AWS_ACCESS_KEY_ID`, etc), an EC2 instance profile granting necessary access, an `~/.aws/credentials` file, etc. If you write settings directly in a `backend "s3"` block or `provider "aws"` block then you're telling Terraform to use unique settings only for that item, which seems like the opposite of what you wanted to achieve here.

If I've misunderstood what you're asking about here, please let me know!

**Comment by mildwonkey** [comment]
I'm going to close this, since there hasn't been a response, but if you are still interested in discussing your use case I can re-open this. Thanks!
