### ISSUE TITLE
Using counts in resource "template_file" not working?

### ISSUE THREAD

**Issue by jrake-revelant** [hashicorp/terraform#2709]
I am using the template file resource and would like to (eventually) set up n nodes:

    resource "template_file" "vault_userdata" {
        filename = "chef-client.userdata.20150701173837"
        count = "${var.vault_nodes}"
        vars {
            instance = "vault-node-${count.index}"
            fqdn = "vault-node-${count.index}.${var.tenant}.${var.internal_domain}"
            tenant = "${var.tenant}"
            chef_server = "${var.chef_server}"
            chef_organization = "${var.chef_organization}"
            chef_validator = "${template_file.org_validator_1.rendered}"
        }
    }

Now i want to reference the corresponding rendered template for the user data:

    user_data = "${{template_file.vault_userdata.${count.index}}.rendered}"

But I think this nested approach is not working, since i get a syntax error.

Can anyone point me in the right direction please?

**Comment by mlrobinson** [comment]
This is how I use similar templated resources:

user_data = "${element(template_file.vault_userdata.*.rendered, count.index)}"

**Comment by jrake-revelant** [comment]
Cool, thanks that seems to be working. Is that somewhere in the docs and I missed it?

**Comment by jrake-revelant** [comment]
ok found it: https://www.terraform.io/docs/configuration/interpolation.html --> Buit in function
