### ISSUE TITLE
Alltrue function introduced in .13.something, but the document about the alltrue function makes no mention of it not existing in .12

### ISSUE THREAD

**Issue by salexpdx** [hashicorp/terraform#27098]
This may be more of a documentation bug than a code bug.  The documentation at https://www.terraform.io/docs/configuration/functions/anytrue.html gives details on the usage of the alltrue function. 
At the top of the page, it includes the disclaimer that 
```
Note: This page is about Terraform 0.12 and later. For Terraform 0.11 and earlier, see 0.11 Configuration Language: Interpolation Syntax.
```
Reading that, one would expect that this function is available in any .12 series release or later.  The actual situation is the function was implemented on July 23rd, the day after the most recent .12 commit was made (based on the most recent tags last commit date.

The PR that implemented the feature is https://github.com/hashicorp/terraform/pull/25656

The usage is in an enterprise environment, so a 0.12.30 release that cherry picks that feature doesn't really solve much since it's unlikely I can get the version bumped easily.

I think the solution is that the documentation should reflect what specific versions this is released in so that when users are on dated versions, they can quickly determine that the feature they need is/isn't available. 
### Terraform Version

```
Terraform v0.12.28

```

### Terraform Configuration Files

```
cat main.tf
output "alltruefunction" {
   value = alltrue([true,true,true])
}
```

### Debug Output
```
Error: Call to unknown function

  on main.tf line 2, in output "alltruefunction":
   2:    value = alltrue([true,true,true])

There is no function named "alltrue".
```

### Expected Behavior
The expected behavior is that I should be able to use alltrue([things]) and receive the response as described in the documentation.  Alternately, the documentation should be explicit that this function was introduced in .13.X and .14.X or just .14

### Actual Behavior
Looking at the codebase, It doesn't look like alltrue was backported to the v12 series.  I'm not sure if this is an issue for other functions, but if old versions aren't receiving functions, then the header at the top of the function page 
```
Note: This page is about Terraform 0.12 and later. For Terraform 0.11 and earlier, see 0.11 Configuration Language: Interpolation Syntax.
```
is very misleading since the function doesn't exist in .12
### Steps to Reproduce
Run that file in .12.28 or 29 and it will throw the error

### Additional Context
None

**Comment by pkolyvas** [comment]
Thanks for pointing that out @salexpdx - we are only adding new features to the latest release of Terraform. However, you're absolutely spot on that the docs do not help in this case. I'll get them clarified today.
