### ISSUE TITLE
Sensitive errors if specified in multiple levels of variables

### ISSUE THREAD

**Issue by douglaswth** [hashicorp/terraform#27095]
### Terraform Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.19.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
```

### Terraform Configuration Files

`main.tf`:

```terraform
variable "secret" {
  type      = string
  sensitive = true
}

module "module" {
  source = "./module"
  secret = var.secret
}
```

`module/main.tf`:

```terraform
variable "secret" {
  type      = string
  sensitive = true
}

resource "local_file" "secret" {
  content         = var.secret
  filename        = "${path.module}/secret.txt"
  file_permission = "0600"
}
```

### Debug Output

https://gist.github.com/douglaswth/daf02c0a31f51b21db3d945bb2ccba39

### Expected Behavior

Either `terraform plan` or `terraform apply` should show the expected changes.

### Actual Behavior

Instead, both commands error with the following message:

```
Error: .content: value has marks, so it cannot be serialized
```

### Steps to Reproduce

1. `export TF_VAR_secret=secret`
2. `terraform init`
3. `terraform apply`

### References

- #26922

**Comment by danieldreier** [comment]
I've reproduced this issue and copied the reproduction case to https://github.com/danieldreier/terraform-issue-reproductions/tree/master/27095. Thanks for reporting this with a clear, simple reproduction case @douglaswth!

**Comment by nick4fake** [comment]
@danieldreier Is there a way to create a minor release for this one? Unfortunately there are no ways to use terraform 0.14 with GKE module due to this bug.

**Comment by pselle** [comment]
@nick4fake This is going out in the 0.14.1 version, which will be releasing today.

**Comment by nick4fake** [comment]
Unfortunately I still see "value has marks, so it cannot be serialized" issue, so probably will open a separate ticket.
