### ISSUE TITLE
0.14: panic: value is marked, so must be unmarked

### ISSUE THREAD

**Issue by lwsanty** [hashicorp/terraform#27107]
### Terraform Version

```
Terraform v0.14.0
```

### Terraform Configuration Files

```terraform
terraform {}

variable "test" {
  type      = object({ enabled = bool })
  default   = { enabled = false }
  sensitive = true
}

resource "local_file" "file" {
  count    = var.test.enabled ? 1 : 0
  filename = "johnny"
}
```

### Debug Output

https://gist.github.com/lwsanty/73104e3fbe9bb5042802687c1a1c6f54
### Crash Output

https://gist.github.com/lwsanty/73104e3fbe9bb5042802687c1a1c6f54
### Expected Behavior

Command succeeded
### Actual Behavior

`panic: value is marked, so must be unmarked first`
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
### References

- https://github.com/hashicorp/terraform/issues/27041
- https://github.com/hashicorp/terraform/issues/26633
- https://github.com/hashicorp/terraform/issues/26625

**Comment by pselle** [comment]
Thank you for reporting this! I've confirmed the issue and am working on a fix.
