### ISSUE TITLE
Checkpoint provides wrong download URL for Terraform v0.14.0

### ISSUE THREAD

**Issue by MulberryBeacon** [hashicorp/terraform#27101]
https://checkpoint-api.hashicorp.com/v1/check/terraform currently returns the following:

{
  "product": "terraform",
  "current_version": "0.14.0",
  "current_release": 1606948835,
  "current_download_url": "https://www.terraform.io/downloads.html",
  "current_changelog_url": "https://github.com/hashicorp/terraform/blob/v0.14.0/CHANGELOG.md",
  "project_website": "https://www.terraform.io",
  "alerts": []
}

The URL in **current_download_url** should be something like "https://releases.hashicorp.com/terraform/0.14.0/".

**Comment by pselle** [comment]
Fixed!

**Comment by MulberryBeacon** [comment]
Thanks for looking into it so quickly!
