### ISSUE TITLE
`ignore_changes = all` causes computed fields to be ignored, which the legacy SDK cannot properly validate

### ISSUE THREAD

**Issue by mendhak** [hashicorp/terraform#27106]
### Terraform Version
```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.19.0
```

### Terraform Configuration Files

```terraform
resource "aws_route53_record" "my_new_dns" {
  zone_id = "ZXXXXXXXX"
  name    = "my.example.com."
  type    = "CNAME"
  ttl     = "300"

  records = ["another.example.com."]
  lifecycle {
    ignore_changes = all
  }
}
```

### Expected Behavior

Terraform plan should run without errors.  

### Actual Behavior

This is the error that appears. 

> Error: Computed attribute cannot be set

>   on main.tf line 1, in resource "aws_route53_record" "my_new_dns":
   1: resource "aws_route53_record" "my_new_dns" {

> Error: Invalid or unknown key

>   on main.tf line 1, in resource "aws_route53_record" "my_new_dns":
   1: resource "aws_route53_record" "my_new_dns" {

### Steps to Reproduce

Copy my configuration above.  Substitute values for your own Route 53 Zone.  

    terraform plan  
    terraform apply  

After applying, run the plan again

    terraform plan

The errors appear.  

### Additional Context

Similar problem seen with `aws_service_discovery_public_dns_namespace` - even if I have hardcoded values. 

```
resource "aws_service_discovery_public_dns_namespace" "my-example-svc" {
  name = "svc.example.com"
  description = "DNS namespace for Service Discovery"
  lifecycle {
    ignore_changes = all
  }
}
```

**Comment by konstl000** [comment]
The same issue applies to other resources, such as parameter store variables.
For instance,
resource "aws_ssm_parameter" "foobar" {
  name        = "/foo/bar"
  description = "Foo bar"
  tier = "Standard"
  type        = "SecureString"
  value       = "foo"
  overwrite = true
  lifecycle {
    ignore_changes=all
  }
}

If "all" is replaced by a list such as [value], plan works again.

**Comment by konstl000** [comment]
Also, at least in the case of SSM, ignore changes is not ignored:
```
konstl@susevm:~/test> aws ssm get-parameter --name /foo/bar --with-decryption 2>/dev/null | jq -r '.Parameter.Value'
foo
konstl@susevm:~/test> aws ssm put-parameter --name /foo/bar --value bar --overwrite
{
    "Version": 2,
    "Tier": "Standard"
}
konstl@susevm:~/test> terraform plan -out plan
aws_ssm_parameter.foobar: Refreshing state... [id=/foo/bar]

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
konstl@susevm:~/test> aws ssm get-parameter --name /foo/bar --with-decryption 2>/dev/null | jq -r '.Parameter.Value'
bar
```

**Comment by jbardin** [comment]
This appears to be caused by a change which allows provider to validate the final configuration they will receive before planning, so as to include values that may have been previously unknown during static validation. Unfortunately is seems that certain combinations of changes from the state will trip up the legacy SDK, causing validation to fail.

**Comment by wyardley** [comment]
should #27141 have fixed all such issues?
I'm seeing the same error with
```terraform
  lifecycle {
    ignore_changes = [node_pool]
  }
```
Inside a `google_container_cluster` resource from the google provider. Is this something that needs to be addressed within https://github.com/hashicorp/terraform-provider-google/, or could there be a lingering issue here?
