### ISSUE TITLE
Support for SQS Redrive Policies and Dead Letter Queues

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/terraform#2711]
Hello! I see that the SQS resource supports `redrive_policy` as a boolean value but I do not see a way to configure [dead letter queues](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/SQSDeadLetterQueue.html). 

I was going to submit a PR for adding `redrive_policy` to the [docs](https://www.terraform.io/docs/providers/aws/r/sqs_queue.html) but it seems that `redrive_policy` would be useless without being able to configure the details.

Would love to have support for this SQS feature in Terraform.

**Comment by mpeter** [comment]
We have been configuring redrive_policy in our project. This is supported, if you can use the heredoc inline policy syntax. Here's an example:

  redrive_policy = <<EOF
{"deadLetterTargetArn":"arn:aws:sqs:${var.aws_region}:${var.aws_account_id}:${var.env}-${var.group}-${var.name}-dlq","maxReceiveCount":10}
EOF

**Comment by mpeter** [comment]
You shouldn't have closed this -- this is missing from the documentation. I only found it from reading the source code.

**Comment by fromonesrc** [comment]
Whoops I think I saw yesterday it was added to the documentation. I'll check when I can. Thanks for getting me in the right direction.

**Comment by fromonesrc** [comment]
We found the EOF approach did not work as hoped because a \n was seen at the end of the JSON during each plan/apply so it was always being modified on each run. Using a string literal with escaped quotes seems to have done the trick.

**Comment by mpeter** [comment]
That's a problem with many of the policies, not just the redrive_policy.
You can also use a file template, that will get around the newline problem.

**Comment by fromonesrc** [comment]
@mpeter it landed [here](https://github.com/hashicorp/terraform/pull/3030) but doesn't look like it got out to the [site](https://terraform.io/docs/providers/aws/r/sqs_queue.html). @catsby any ideas?
