### ISSUE TITLE
arm64 output formatting is diffrent then in amd64/arm

### ISSUE THREAD

**Issue by naorlivne** [hashicorp/terraform#27113]
### Terraform Version
0.14

### Terraform Configuration Files

```
resource "null_resource" "test" {
  count   = 1
}

variable "test" {
  default = "not_set"
}

output "test" {
  value = var.test
}
```

### Expected Behavior
Output in amd64, arm & arm64 should be exactly the same

### Actual Behavior
Output in amd64 & arm shows:
```
null_resource.test[0]: Creating...
null_resource.test[0]: Creation complete after 0s [id=1854451236535832054]


Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

test = not_set
```
while output in arm64 shows:
```
null_resource.test[0]: Creating...
null_resource.test[0]: Creation complete after 0s [id=8907829183761162487]


Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

test = "not_set"

```
(note `test = "not_set"` in arm64 vs `test = not_set` in amd64/arm)

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
in arm64 and in arm/am64 and compere the outputs of the 2

### Additional Context
noticed in https://cloud.drone.io/naorlivne/terraformize/452/3/4

**Comment by apparentlymart** [comment]
Hi @naorlivne! Thanks for reporting this.

Are you sure you were using Terraform v0.14.0 on all three architectures? The output you showed for amd64 and arm looks like output from an earlier version of Terraform, before we updated the "Outputs" section to use the same presentation as the other values in the Terraform output.

**Comment by naorlivne** [comment]
My bad looks like your right, thanks for the quick response.
