### ISSUE TITLE
terraform version output that is valid format for required_providers

### ISSUE THREAD

**Issue by clebio** [hashicorp/terraform#27157]
### Current Terraform Version

```
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/http v1.2.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 0.14.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use-cases

As an author of terraform modules and configurations, I'd like to be able to redirect the output of `terraform version` (possibly with an optional argument) into a configuration file.

### Attempted Solutions

The current workflow requires munging the output of `terraform version` in order to create such as

```
terraform {
  required_providers {
    external = "~> 1.2"
    http     = "~> 1.2"
    archive  = "~> 1.3"
    null     = "~> 2.1"
    random   = "~> 2.3"
    template = "~> 2.1"
  }
}
```

### Proposal

Add an optional formatting attribute to the `version` subcommand, akin to `-json`, such that the output can then be redirected directly into some `versions.tf`:

    terraform version -reqfmt >> versions.tf

### References

* #26438

**Comment by apparentlymart** [comment]
Hi @clebio,

From Terraform v0.14 onwards, we're intending that [the dependency lock file](https://www.terraform.io/docs/configuration/dependency-lock.html) will replace the need to pre-emptively set upper limits on provider versions. After you run `terraform init` for the first time, Terraform will remember which versions it selected and will always re-select those same versions unless you run `terraform init -upgrade`.

Our intent is that under this new model your module could potentially have no version constraints at all, or (if you know that your module is using a provider feature added recently) only _minimum_ version constraints with `>=`. I'd suggest adding upper limits to version constraints only if you know your module is _already_ incompatible with a newer provider version, if your intent is to communicate to other maintainers that you already tried upgrading to that newer version and it didn't work.

If you have some requirements that the dependency lock file doesn't meet, we'd love to hear more about it. Our design direction is to move away from mandatory manually-maintained version constraints, so we'll ideally want to try to meet your use-cases in a different way that doesn't require writing (or generating) explicit version constraints.

**Comment by clebio** [comment]
Makes sense, thanks! I haven't caught up to 0.14 just yet.
