### ISSUE TITLE
.terraform.lock.hcl is make as executable

### ISSUE THREAD

**Issue by mathcantin** [hashicorp/terraform#27152]
### Terraform Version

```
0.14
```

### Expected Behavior

The .terraform.lock.hcl must be a simple file.

```-rw-r--r--   6 username  staff   192  4 déc 13:36 .terraform.lock.hcl```

### Actual Behavior

By default, the .terraform.lock.hcl is an executable file. Example of _ls -al_ on a Mac:

```-rwxrwxrwx   1 username  staff  3906  4 déc 13:36 .terraform.lock.hcl```

### Steps to Reproduce

Run _terraform init_ on an Unix like system.

### Additional Context

That could be a security issue.

**Comment by apparentlymart** [comment]
Hi @mathcantin! Thanks for reporting this.

I suspect this has the same root cause and will have the same solution as #27116, so I'm going to close this one just to consolidate the discussion over there. Thanks again!
