### ISSUE TITLE
azurerm backend ignoring ARM_ENDPOINT env variable or endpoint parameter -cannot direct it to Azure Stack

### ISSUE THREAD

**Issue by werton13** [hashicorp/terraform#27156]
Hi there, i'm trying to direct azurerm backend to Azure Stack storage account while authenticating using the  Service Principal.
I'm using this command
```terraform
terraform init -backend-config="azscreds.conf"
```
and my conf file look like:
```txt
client_id             = "" 
client_secret         = ""
subscription_id       = ""
tenant_id             = "" 
endpoint              = ""
```
but I always get an error
```sh

Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "tfsa13": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription 'my subscription id' could not be found."

```
In the debug output I can see what terraform ignoring ARM_ENDPOINT env variable and also endpoint parameter, which a tried to put in the backend file, backend config file, and in the command prompt.
As it is described here: https://www.terraform.io/docs/backends/types/azurerm.html#environment
```txt
endpoint - (Optional) The Custom Endpoint for Azure Resource Manager. This can also be sourced from the ARM_ENDPOINT environment variable.

NOTE: An endpoint should only be configured when using Azure Stack.
```
it should work, but it does not - it always trying to connect  https://management.azure.com

### Terraform Version

```sh
2020/12/05 23:55:32 [INFO] Terraform version: 0.13.5
2020/12/05 23:55:32 [INFO] Go runtime version: go1.14.7
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.13"
  backend "azurerm" {
    #environment          = "stack"
    endpoint             = "https://management.myazurestack.fqdn" 
    resource_group_name  = "Terraform-RG01"
    storage_account_name = "tfsa13"
    container_name       = "tfstate"
    key                  = "prod.terraform.tfstate"
     
  }
}
```

### Debug Output
```terraform
2020/12/06 00:04:07 [DEBUG] Azure Backend Response for https://management.azure.com/subscriptions/mysubscription id/resourceGroups/Terraform-RG01/providers/Microsoft.Storage/storageAccounts/tfsa13/listKeys?api-version=2016-01-01:
HTTP/2.0 404 Not Found
Content-Length: 129
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Sat, 05 Dec 2020 21:04:07 GMT
```

### Expected Behavior

It should connect to the arm endpoint I specified

### Actual Behavior

It trying to connect to global Azure ARM endpoint

**Comment by werton13** [comment]
can someone give me an example  - how the custom ARM endpoint should be specified?

**Comment by werton13** [comment]
I checked this vs .14 version - not working
vs .12 - working flawless
```sh
PS S:\PS-Scripts\Terraform-play\AzS-Backend> terraform version
2020/12/06 19:37:02 [INFO] Terraform version: 0.12.29
```
Please fix it for the latest version

**Comment by mildwonkey** [comment]
Hi @werton13 ,
I'm a little confused by this issue. Is this literally what your backend configuration file looks like, the one you are using to overwrite your backend block?

```
client_id             = "" 
client_secret         = ""
subscription_id       = ""
tenant_id             = "" 
endpoint              = ""
```

If so, terraform takes this to mean that you are explicitly setting the value of those to empty strings, instead of "unsetting" them so terraform uses your environment variables.

**Comment by mildwonkey** [comment]
If the above is correct, you can use `null` instead of `""` to "unset" any of your backend configuration and tell terraform to check elsewhere for any of those values (such as environment variables):

```
client_id             = null
```

**Comment by mildwonkey** [comment]
I'm going to close this, since there hasn't been a response. Please open a new issue or post in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27) if you have further questions. Thanks!
