### ISSUE TITLE
lifecycle.ignore_changes conflicts with required variables

### ISSUE THREAD

**Issue by cthulhu** [hashicorp/terraform#27165]
After upgrading to version 0.14 existing terraform codebases display errors regarding required fields when in combination with lifecycle.ignore_changes.

### Terraform Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
```

### Terraform Configuration Files

```terraform
resource "random_password" "john_doe" {
  length  = 40
  special = true
}

resource "azuread_user" "john_doe" {
  user_principal_name   = "john.doe@example.com"
  display_name          = "John Doe"
  mail_nickname         = "john.doe"
  password              = random_password.john_doe.result
  force_password_change = false
  lifecycle {
    ignore_changes = [password]
  }
}

```

### Expected Behavior

Infrastructure should offer a plan or no changes.

### Actual Behavior

Error message: 

```
Error: "password": required field is not set

 on users.tf line 4, in resource "azuread_user" "john_doe":
 4: resource "azuread_user" "john_doe" {
```

### Additional Context

Rollback to 0.13.5 on the same state shows correct behaviour.
Rollbacks to previous versions of azuread(1.1.0, 1.0.0) provider didn't affect the actual behavior.

### References

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/user

**Comment by jbardin** [comment]
HI @cthulhu,

I have a feeling this is a manifestation of same problem as #27106. I'm not sure exactly _why_ this particular instance is happening though, since `password` should exist already in the state, so there shouldn't be any way to send a missing password to the provider for validation.  Also, `random_password.john_doe.result` should not be changing between plans, and therefor should not require `ignore_changes` in order to work correctly. 

I don't have an `azuread` environment easily accessible; if this configuration does trigger the issue as shown, can you show the steps and the resulting state up until the `plan` that returns the error?

Thanks!

**Comment by cthulhu** [comment]
Hi @jbardin,

Thanks for the quick response. I tried to create a sep setup and found that if a user has been created with a new terraform version(even on 0.13.5) it works just fine. 
I did a few experiments and actually found the issue:

It fails if a user was imported even with a new provider. So if a resource has **required** field and it is during import is not set 0.14 starts to show that error, even if you have a lifecycle statement to ignore changes. That's a difference with 0.13.5. 

Here is a reproduced sequence:

Before migration:

```
>terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/random v3.0.0

Your version of Terraform is out of date! The latest version
is 0.14.0. You can update by downloading from https://www.terraform.io/downloads.html
```

State content:

```
terraform state list
azuread_user.john_doe
random_password.john_doe
```

State content for user:

```
terraform state show azuread_user.john_doe
# azuread_user.john_doe:
resource "azuread_user" "john_doe" {
    account_enabled     = true
    display_name        = "John Doe"
    id                  = "XXXXX"
    mail_nickname       = "john.doe"
    object_id           = "XXXXXX"
    user_principal_name = "john.doe@example.com"
}
```
**Note that the password is not set at all.**

After migration:

```
terraform version
Terraform v0.14.0
```

```
tf plan                                                                                                                                                                                                                                                                                                                                         
random_password.john_doe: Refreshing state... [id=none]
azuread_user.john_doe: Refreshing state... [id=XXXXXX]

Error: "password": required field is not set

  on main.tf line 9, in resource "azuread_user" "john_doe":
   9: resource "azuread_user" "john_doe" {

```

```
terraform state show azuread_user.john_doe
# azuread_user.john_doe:
resource "azuread_user" "john_doe" {
    account_enabled     = true
    display_name        = "John Doe"
    id                  = "XXXXX"
    mail_nickname       = "john.doe"
    object_id           = "XXXXXX"
    user_principal_name = "john.doe@example.com"
}
```

Hope this will help!

Feel free to ask any details, I have a pretty isolated example I can test over.

**Comment by jbardin** [comment]
Thank you @cthulhu. I wasn't thinking about import, which explains how you can get a user with no password (or indeed any `required` field that is empty)! While it is appearing for a slightly different reason, this indeed is the same root cause as #27106.
