### ISSUE TITLE
Linux distribution files

### ISSUE THREAD

**Issue by vogash** [hashicorp/terraform#27183]
### Current Terraform Version
any version

### Use-cases
While downloading Linux distribution from your web site you must have unzip utility to extract the binary.
Due to license legal issue of unzip on customer site we are unable to extract it

### Attempted Solutions
As part of deliverables we can provide terraform binary, but it was rejected by our legal department

### Proposal
In addition to zip distribution also to provide tar or tar.gz files which is part of any Linux distribution

**Comment by pkolyvas** [comment]
For Linux-based installs, we now provide distribution specific repositories:

Debian-based: https://www.terraform.io/docs/cli/install/apt.html

Yum-based: https://www.terraform.io/docs/cli/install/yum.html

I apologized that they're not more clearly listed on the Downloads page - we have an upgrade coming that should remedy that concern. 

We are not considering supporting additional delivery mechanisms at this time unfortunately.
