### ISSUE TITLE
outputs in remote terraform.tfstate isn't written

### ISSUE THREAD

**Issue by pythago418** [hashicorp/terraform#27185]
### Terraform Version

```
Terraform v0.13.4
```
```
terraform {
  required_version = ">= 0.13.4"
  backend "s3" {
    bucket         = "*******"
    region         = "us-west-2"
    key            = "terraform.tfstate"
    encrypt        = true
    dynamodb_table = "*******"
  }
}
```

### Expected Behavior
I implemented below outputs.tf in a module directory. After `terraform apply`, outputs of terraform.tfstate  is empty.
I expected the outputs have below values. 

```
output "user" {
  value = [
    for access_key in aws_iam_access_key.access_key :
    access_key.user
  ]
}

output "id" {
  value = [
    for access_key in aws_iam_access_key.access_key :
    access_key.id
  ]
}

output "secret" {
  value = [
    for access_key in aws_iam_access_key.access_key :
    access_key.secret
  ]
}
```

### Question
How can I write outputs in remote terraform.tfstate?

### Concerned
I have two concerns.
First is state argument. According to below document, state file is ignored in `apply`.
[https://www.terraform.io/docs/commands/apply.html#state-path](https://www.terraform.io/docs/commands/apply.html#state-path)
Second is the log. It's displayed when `plan` is done.
```
Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

**Comment by pkolyvas** [comment]
Hey @pythago418, it sounds like you've created outputs in a sub-module, but you'd like to expose those outputs in the root module so, for example, you can access them via `terraform output`. If that's the case you'll need to also define the outputs in the root module, referring to the outputs you defined in the module. 

In other words, the child module can expose its outputs to it's parent module and the root module is used to print those outputs (and store them in state's root outputs where you're looking). 

Ex.:
```hcl
output "user" {
  value = module.mymodulename.user
}
```

You can read more here: https://www.terraform.io/docs/configuration/outputs.html#accessing-child-module-outputs

I think your other two questions are best answered in our [community forum](https://discuss.hashicorp.com/c/terraform-core/27) and I'd recommend you head over there where we can leverage our community to help get you some answers. We try to keep GitHub for bugs, though I know it can be hard to know what's a bug and what's not.

Briefly, however, the CLI argument `-state=<somepath>`, when defined, is only ignored on apply if the given Terraform configuration refers to remote state. 

As for `-out` - the docs state the following: 
`The path to save the generated execution plan. This plan can then be used with terraform apply to be certain that only the changes shown in this plan are applied. Read the warning on saved plans below.
`

This allows you to be sure that when you run `apply`, Terraform will use the plan you've just seen/viewed. 

Please join us in our [community forums](https://discuss.hashicorp.com/c/terraform-core/27).
