### ISSUE TITLE
aws_db_instance maintenance window capitalization?

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#2719]
Given a maintenance_window setting of `Fri:09:00-Fri:09:30`, which has never been changed, I'm seeing terraform plan/apply output like this:

```
~ aws_db_instance.pg_main: Modifying...
  maintenance_window: "fri:09:00-fri:09:30" => "Fri:09:00-Fri:09:30"
```

I'm guessing AWS is lowercasing somewhere along the line, and Terraform should either do the same or throw a validation error if the string contains any caps.

**Comment by catsby** [comment]
Thanks @pikeas ! I went ahead and applied lower casing to `maintenance_window`. The API doesn't strictly say that they lowercase it, so I thought that a better path than throwing a local validation error.

The patch is  22e73d7 , in PR https://github.com/hashicorp/terraform/pull/3053
