### ISSUE TITLE
Add a String `contains` or `includes` function that can replace the `can(regex(..., ...))` pattern

### ISSUE THREAD

**Issue by Gowiem** [hashicorp/terraform#27198]
### Current Terraform Version

```
0.14.1
```

### Use-cases

The current solution for checking if a string var or local contains a given substring is typically done using `can(regex("substring_to_check", var.my_string))` ([and there are a number of other ways to do so as well](https://stackoverflow.com/questions/47243474/how-to-check-if-string-contains-a-substring-in-terraform-interpolation)). IMHO, this is pretty unintuitive as it requires using a couple functions and doesn't "read" well. 

The end goal of providing a specific function to handle this problem is to provide a cleaner and more concise way to accomplish the same.

### Attempted Solutions

As mentioned above, the current solution is typically done with `regex` and pals. There are many ways to accomplish this. 

### Proposal

I'm proposing that Terraform provide a native function to handle this instead of the unintuitive ways it's handled now. This can be seen in many programming languages: 

1. [Golang strings#Contains](https://golang.org/pkg/strings/#Contains)
1. [Ruby String#include?](https://ruby-doc.org/core-1.9.3/String.html#method-i-include-3F)
1. [JS string#includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

I believe a new function like `contains` (problematic because of the Collection `contains` function?) or `includes` would solve this problem elegantly. I think this is worth bringing up since this is such common business logic pattern. 

### References

N/A

**Comment by scaswell-hirez** [comment]
Hashicorp, y'all have been sitting on this one for over a year since the last comment; almost 2 years since the PR was submitted.  It solves a very common use case.  Please expedite its inclusion into the next release.

**Comment by Chinikins** [comment]
would love to see this in the next release....

**Comment by mward-varonis** [comment]
Any plans on including this in an upcoming release?

Thanks!

**Comment by crw** [comment]
It is very difficult for us to make forward-looking statements, however the linked PR is on the radar for future inclusion.

**Comment by bflad** [comment]
@crw I believe this was resolved with https://github.com/hashicorp/terraform/pull/33069 introducing the [`strcontains()` function](https://developer.hashicorp.com/terraform/language/functions/strcontains) in Terraform 1.5

**Comment by crw** [comment]
Thanks @bflad, I appreciate the callout.
