### ISSUE TITLE
remote backend Terraform version validation does not work with Terraform Cloud local execution mode

### ISSUE THREAD

**Issue by e-moshaya** [hashicorp/terraform#27200]
### Terraform Version
0.14.1

```
...
```

### Terraform Configuration Files

```terraform
data "terraform_remote_state" "remote" {
  backend = "remote"

  config = {
    organization = "organisation"
    workspaces = {
      name = "workspace1"
    }
  }
}
```

### Expected Behavior
Ideally, check the remote state file terraform_version field instead of execution mode remote version

### Actual Behavior
```
Error: Error loading state error

  on data.tf line 81, in data "terraform_remote_state" "organization":
  81:   backend = "remote"

error loading the remote state: Remote workspace Terraform version "latest"
does not match local Terraform version "0.14.1"
```

### References
https://github.com/hashicorp/terraform/pull/26947

**Comment by alisdair** [comment]
Thanks for reporting this. A fix is forthcoming in #27197.

**Comment by e-moshaya** [comment]
> Thanks for reporting this. A fix is forthcoming in #27197.

Thanks alisdair any chance for a quick 0.14.2 release with this fix?

**Comment by alisdair** [comment]
Yes. I'm working on it right now.

**Comment by alisdair** [comment]
@e-moshaya Terraform 0.14.2 is out now: https://releases.hashicorp.com/terraform/0.14.2/

I'd appreciate it if you could verify that this fixes the issue for you. If not, please let me know and we can reopen this ticket and investigate further.

**Comment by e-moshaya** [comment]
thanks, @alisdair I can confirm 0.14.2 fixes this issue
