### ISSUE TITLE
Incorrect docs for decrypting output with base64 and keybase

### ISSUE THREAD

**Issue by stuartmaxwell** [hashicorp/terraform#27213]
This is a slightly modified copy/paste from the forum here: https://discuss.hashicorp.com/t/aws-iam-access-key-encrypted-secret-base64-decode/14531/5

### Terraform Version

```
Terraform v0.14.2
```

### Terraform Configuration Files

```terraform
n/a
```

### Debug Output

n/a

### Crash Output

n/a

### Expected Behavior

The commands provided in the docs should work.

### Actual Behavior

The commands in the docs do not work.

### Steps to Reproduce

Run the following command (as suggested by the docs) to decrypt secrets with keybase:
```
terraform output password | base64 --decode | keybase pgp decrypt
```
And get the following output:
```
base64: invalid input
```

This command is referenced on many pages of documents, e.g.
- https://www.terraform.io/docs/providers/mysql/r/user_password.html
- https://registry.terraform.io/providers/hashicorp/consul/latest/docs/data-sources/acl_token_secret_id
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_login_profile
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key
- https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/ram_access_key
- https://registry.terraform.io/providers/petelopez/octopusdeploy/latest/docs/resources/variable

The command fails because the output generated by the `terraform output password` command is wrapped with quotes and the `base64 --decode` command fails to decode it.

Wrapping the output in quotes must have been a recent change because the command above definitely used to work on version 0.13.3 at least. [There is a page on the docs](https://www.terraform.io/docs/commands/output.html#use-in-automation) that describes why the output may be wrapped in quotes:

> The terraform output command by default displays in a human-readable format, which can change over time to improve clarity. 

I'm guessing a recent version has introduced the quotes to make it look more human-readable. That link suggests the following to fix that:

>For use in automation, use -json to output the stable JSON format. You can parse the output using a JSON command-line parser such as jq.

There are two possible fixes. The first one, as suggest by your own docs is to use the following command instead:
```
terraform output -json password | jq -r . | base64 --decode | keybase pgp decrypt
```
The downside to this is that (on my Debian install at least) I had to install the `jq` command as it was not already installed. The alternate fix is to include the `--ignore-garbage` argument with the `base64` command (which tells `base64` to ignore characters it can't decode) as follows:
```
terraform output password | base64 --decode --ignore-garbage | keybase pgp decrypt
```
The downside to this approach is that the human-readable output of `terraform output password` may change again in the future breaking this again.

I'll leave it to you to decide which approach is best to recommend.

### Additional Context

I don't think I have anything atypical about my situation. This used to work in v0.13.3 but no longer does with v0.14.2 but I can't say for sure when it changed.

### References

- Forum link: https://discuss.hashicorp.com/t/aws-iam-access-key-encrypted-secret-base64-decode/14531/7

**Comment by Surafel-Getachew** [comment]
Great. it works

**Comment by mildwonkey** [comment]
Hi! I'm cleaning up some documentation issues, and the documentation around `output` has been updated since this issue was opened, so I will close this. thanks!
