### ISSUE TITLE
Make lookup work with nested maps

### ISSUE THREAD

**Issue by baurmatt** [hashicorp/terraform#27219]
### Current Terraform Version

```
v0.14.2
```

### Use-cases

Accessing nested maps is currently hard. Sometimes you need a value from somewhere deep within a map

```terraform
variable node_deployments {
  description = "A list of node deployments for this cluster"
  default = {
    nd01 = {
      spec = {
        replicas = 1
      }
    }
  }
}
```

### Attempted Solutions

Taking the code from above, this code is currently needed to take the users input of `replicas` or default to `3`

```terraform
locals {
  replicas = lookup(lookup(lookup(var.node_deployments, "nd01", {}), "spec", {}), "replicas", 3)
}
```

### Proposal
Coming from a Puppet focused world, I'd like to have something like the [`get`](https://puppet.com/docs/puppet/7.0/function.html#get) function. This might look like this:

```terraform
lookup($var.node_deployments, "nd01.spec.replicas", 3)
```

**Comment by alisdair** [comment]
Hi @baurmatt, thanks for suggesting this change.

I think [the `try` function](https://www.terraform.io/docs/configuration/functions/try.html) might work very similarly to what you're looking for here. Like this:

```hcl
locals {
  replicas = try(var.node_deployments.nd01.spec.replicas, 3)
}
```

Does that solve the problem for you?

**Comment by baurmatt** [comment]
Hey @alisdair, you're absolutely right. This is exactly what I'm looking for. Not sure how I could have overlook it 🙈 Thank you for pointing me in the right direction!
