### ISSUE TITLE
Option -refresh=false seems not to be working anymore

### ISSUE THREAD

**Issue by sdickhoven** [hashicorp/terraform#27228]
### Terraform Version

```
$ terraform version
Terraform v0.14.2
+ provider registry.terraform.io/cloudflare/cloudflare v2.14.0
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
```

### Terraform Configuration Files
n/a

### Debug Output
```
$ terraform apply -refresh=false
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
...
```
```
$ env | grep TF_CLI_ARGS
TF_CLI_ARGS_apply=-refresh=false
$ terraform apply
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
...
```
```
$ TF_CLI_ARGS_apply="-refresh=false" terraform apply
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
<redacted>: Refreshing state... [id=<redacted>]
...
```

### Crash Output
n/a

### Expected Behavior
When option `-refresh=false` is used or env var `TF_CLI_ARGS` (or `TF_CLI_ARGS_apply`) is set to `-refresh=false` then terraform should _not_ do a refresh when running `terraform apply`.

### Actual Behavior
Terraform does a full-on state refresh.

### Steps to Reproduce
```
$ terraform apply -refresh=false
```

### Additional Context
We have some large configs (e.g. DNS, GitHub) that take 1hr+ to refresh state. We only do refreshes on those occasionally. So not having `-refresh=false` is kind of a show stopper for us.

### References
n/a

**Comment by sdickhoven** [comment]
another use case for `-refresh=false` is config change validation for users who are not allowed to interact with the provider api (but _do_ have read-only access to the terraform state file).

**Comment by jbardin** [comment]
Thanks @sdickhoven!

Looks like since the primary workflow is to apply from a plan, the `-refresh` flag for `apply` was overlooked. The flag does work correctly with `terraform plan`. 

Just a note about the second use-case you've presented; providers may need to make API calls to create a plan as well, so even without refresh, there is no way to guarantee that users can always create a plan successfully without API access. 

Thanks!
