### ISSUE TITLE
Support renaming resources during plan/apply

### ISSUE THREAD

**Issue by mcanevet** [hashicorp/terraform#27229]
### Current Terraform Version

```
Terraform v0.14.2
```

### Use-cases

Refactoring Terraform code is sometime very difficult because as soon as you want to rename a resource or move it to another module, you'll break compatibility with what exists and you have to manually play with `terraform state mv` to move the resources in the state before applying your new manifests.
This is highly incompatible with the usage of Terraform exclusively in a CD pipeline.
It would be great if terraform supports it natively.

### Proposal

I can see at least 3 ways to improve this situation:
- Add a `--resource-move` argument to the `plan` and `apply` command that would allow us to specify during plan which resources moved in the new manifests,
- Support some kind of "migration path" configuration file that modules authors could provide with their modules to tell terraform which resources moved between two versions of the module they maintain, so that when a user wants to upgrade a module, he does not have to deal with specifying which resources moved,
- Try to automatically detect which resources moved, but I guess this would not be easy.

This way, we would be able to update our terraform workspace in a declarative way without using any imperative command as we have to do today.

**Comment by jbardin** [comment]
Hi @mcanevet,

Thanks for the proposal. This use-case would be covered by whatever solution results from #19354, so we can move any further discussion over there.

Thanks!
