### ISSUE TITLE
aws_lambda_permission resources are replaced when using an account ID for the Principal

### ISSUE THREAD

**Issue by L0ntra** [hashicorp/terraform#27226]
When using the account ID to specify the principal for aws_lambda_permission resources, every time a new plan is generated a replacement of the resource is planned. 

### Terraform Version
```
0.12.28
```

### Expected Behavior
No change is planned

### Actual Behavior
A plan is created to replace the principal ARN with the account ID
```
resource "aws_lambda_permission" "allow_bucket" {
    ~ principal     = "arn:aws:iam::123456789012:root" -> "123456789012" # forces replacement
}
```

### Steps to Reproduce
Plan and apply an aws_lambda_permission resource that uses an account id for the principal
Plan again without making any changes.

Ex:
```
# The important bits:
data "aws_caller_identity" "current" {}

resource "aws_lambda_permission" "allow_bucket1" {
  statement_id  = "AllowExecutionFromS3Bucket1"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.func1.arn
  principal     = data.aws_caller_identity.current.account_id
  source_arn    = aws_s3_bucket.bucket.arn
}

# Other things that also need to be setup:
resource "aws_iam_role" "iam_for_lambda" {
  name = "iam_for_lambda"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow"
    }
  ]
}
EOF
}

resource "aws_lambda_function" "func1" {
  filename      = "your-function1.zip"
  function_name = "example_lambda_name1"
  role          = aws_iam_role.iam_for_lambda.arn
  handler       = "exports.example"
  runtime       = "go1.x"
}

resource "aws_s3_bucket" "bucket" {
  bucket = "your_bucket_name"
}
```

**Comment by apparentlymart** [comment]
Hi @L0ntra,

The AWS provider is responsible for deciding how to interpret this change, so a change to fix this would need to be made in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws) instead. There's nothing we could do in this repository to avoid this proposed change, so I'm going to close this issue.

If the AWS provider intends to treat the ARN and the plain account id as interchangable, as seems to be the case here, then I think it would need to implement what the Terraform SDK calls `DiffSuppressFunc`, to implement the logic for recognizing when a given ARN represents the same AWS account as a naked account id. If you open a new issue in the AWS provider repository then feel free to include that hint or to link over to this issue for context!

Thanks.
