### ISSUE TITLE
Cloudfront support

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/terraform#2723]
We're using Terraform to manage all our AWS infrastructure except Cloudfront distributions where we are relying on Cloudformation. Is bringing Cloudfront into Terraform on the roadmap? Would be great to use Terraform for this and ditch Cloudformation.

**Comment by justincampbell** [comment]
This was mostly done in #1780, and will hopefully be resubmitted by @AlexanderEkdahl soon

Also see spreadsheet in https://github.com/hashicorp/terraform/issues/28

**Comment by fromonesrc** [comment]
:heart:

**Comment by mwarkentin** [comment]
Most recent work being done in https://github.com/hashicorp/terraform/pull/3330
