### ISSUE TITLE
AMI with Terraform

### ISSUE THREAD

**Issue by sarathc9** [hashicorp/terraform#27252]
Hi there,
I need to use existing EC2-AMI to create kafka cluster in AWS through terraform. Please provide the related script.

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
