### ISSUE TITLE
Dark Mode (follow system theme) for registry.terraform.io

### ISSUE THREAD

**Issue by AdamCoulterOz** [hashicorp/terraform#27259]
Implement a dark theme for the registry.terraform.io website which follows the operating system default theme.

**Comment by danieldreier** [comment]
Hi @AdamCoulterOz! This GitHub issue tracker is for the Terraform Core OSS project, and not the entire Terraform ecosystem, so I'm going to close this out because the registry folks don't track this. However, I'll share this with the team responsible so they're aware of your request. Thanks!
