### ISSUE TITLE
Terraform security concerns in state files

### ISSUE THREAD

**Issue by githubtiwari** [hashicorp/terraform#27256]
how can rectify this below issue ...
ptiwari@UBUNTU-PTIWARI:~/zeus-infrastructure/rke-cluster$ ENV=qa make check-security
Configuring the terraform backend
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of rancher/rke from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/vsphere from the dependency lock file
- Reusing previous version of hashicorp/template from the dependency lock file
- Reusing previous version of hashicorp/local from the dependency lock file
- Installing rancher/rke v1.1.5...
- Installed rancher/rke v1.1.5 (signed by a HashiCorp partner, key ID 2EEB0F9AD44A135C)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)
- Installing hashicorp/vsphere v1.24.2...
- Installed hashicorp/vsphere v1.24.2 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
- Installing hashicorp/local v2.0.0...
- Installed hashicorp/local v2.0.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Problem 1

  [GEN003][WARNING] Block 'provider.vsphere' includes a potentially sensitive attribute which is defined within the project.
  /home/ptiwari/zeus-infrastructure/rke-cluster/qa/modules/vsphere/provider.tf:3

       1 | provider "vsphere" {
       2 |   user                 = var.vsphere_user
       3 |   password             = var.vsphere_password    [string] "ComplicatedHiddenPassword"
       4 |   vsphere_server       = var.vsphere_vcenter
       5 |   allow_unverified_ssl = var.vsphere_unverified_ssl
       6 | }

   See https://tfsec.dev/docs/general/GEN003/ for more information.

Problem 2

  [GEN003][WARNING] Block 'module.rke_nodes' includes a potentially sensitive attribute which is defined within the project.
  /home/ptiwari/zeus-infrastructure/rke-cluster/qa/rke-nodes/main.tf:7

       4 |   # vCenter Provider Variables
       5 |   vsphere_vcenter        = var.vsphere_vcenter
       6 |   vsphere_user           = var.vsphere_user
       7 |   vsphere_password       = var.vsphere_password    [string] "ComplicatedHiddenPassword"
       8 |   vsphere_unverified_ssl = var.vsphere_unverified_ssl
       9 |
      10 |   # Virtual Machine variables

   See https://tfsec.dev/docs/general/GEN003/ for more information.

Problem 3

  [GEN003][WARNING] Block 'module.rke_nodes' includes a potentially sensitive attribute which is defined within the project.
  /home/ptiwari/zeus-infrastructure/rke-cluster/qa/rke-nodes/main.tf:55

      52 |   vm_domain         = var.vm_domain
      53 |
      54 |   default_user     = var.default_user
      55 |   default_password = var.default_password    [string] "ComplicatedHiddenPassword"
      56 |   ssh_public_key   = var.ssh_public_key
      57 |   ssh_key          = var.ssh_key
      58 | }

   See https://tfsec.dev/docs/general/GEN003/ for more information.

Problem 4

  [GEN003][WARNING] Block 'module.rke_lb' includes a potentially sensitive attribute which is defined within the project.
  /home/ptiwari/zeus-infrastructure/rke-cluster/qa/rke-nodes/main.tf:117

     114 |   vm_domain         = var.vm_domain
     115 |
     116 |   default_user     = var.default_user
     117 |   default_password = var.default_password    [string] "ComplicatedHiddenPassword"
     118 |   ssh_public_key   = var.ssh_public_key
     119 |   ssh_key          = var.ssh_key
     120 | }

   See https://tfsec.dev/docs/general/GEN003/ for more information.

Problem 5

  [GEN003][WARNING] Block 'module.rke_lb' includes a potentially sensitive attribute which is defined within the project.
  /home/ptiwari/zeus-infrastructure/rke-cluster/qa/rke-nodes/main.tf:76

      73 |   # vCenter Provider Variables
      74 |   vsphere_vcenter        = var.vsphere_vcenter
      75 |   vsphere_user           = var.vsphere_user
      76 |   vsphere_password       = var.vsphere_password    [string] "ComplicatedHiddenPassword"
      77 |   vsphere_unverified_ssl = var.vsphere_unverified_ssl
      78 |
      79 |   # Virtual Machine variables

   See https://tfsec.dev/docs/general/GEN003/ for more information.

Problem 6

  [GEN003][WARNING] Block 'module.rke_nodes:provider.vsphere' includes a potentially sensitive attribute which is defined within the project.
  /home/ptiwari/zeus-infrastructure/rke-cluster/qa/modules/vsphere/provider.tf:3

       1 | provider "vsphere" {
       2 |   user                 = var.vsphere_user
       3 |   password             = var.vsphere_password    [string] "ComplicatedHiddenPassword"
       4 |   vsphere_server       = var.vsphere_vcenter
       5 |   allow_unverified_ssl = var.vsphere_unverified_ssl
       6 | }

   See https://tfsec.dev/docs/general/GEN003/ for more information.

Problem 7

  [GEN003][WARNING] Block 'module.rke_lb:provider.vsphere' includes a potentially sensitive attribute which is defined within the project.
  /home/ptiwari/zeus-infrastructure/rke-cluster/qa/modules/vsphere/provider.tf:3

       1 | provider "vsphere" {
       2 |   user                 = var.vsphere_user
       3 |   password             = var.vsphere_password    [string] "ComplicatedHiddenPassword"
       4 |   vsphere_server       = var.vsphere_vcenter
       5 |   allow_unverified_ssl = var.vsphere_unverified_ssl
       6 | }

   See https://tfsec.dev/docs/general/GEN003/ for more information.

  disk i/o             80.362249ms
  parsing HCL          1.705183ms
  evaluating values    18.93703ms
  running checks       11.333196ms
  files loaded         21

7 potential problems detected.

make: *** [Makefile:62: check-security] Error 1

**Comment by jbardin** [comment]
Hi @githubtiwari 

Thanks for filing the issue. The state file in its entirely is currently considered sensitive, and needs to be treated as such. There are some solution for encrypting the state at rest with various backends, but currently terraform needs access to the entire state in order to operate. There has been lots of discussion about storing secrets in the state file, which you can see in #516

Thanks!
