### ISSUE TITLE
Creating Over 2000 DNS Records Gives me StatusCode=429 

### ISSUE THREAD

**Issue by IQ-OO** [hashicorp/terraform#27266]
### Terraform Version

```
Terraform v0.13.5 
+ provider registry.terraform.io/hashicorp/azurerm v2.39.0
(also tried Terraform v0.14, same error)
```

### Terraform Configuration Files

```terraform
provider "azurerm" {
    version="2.39"
    features {}
}

resource "azurerm_resource_group" "example" {
  name     = "large-rg"
  location = "West US"
}

resource "azurerm_dns_zone" "example" {
  name                = "dnsrecords.com"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_dns_a_record" "arecord" {
        name                = " arecord "
        zone_name           = " dnsrecords.com"
        resource_group_name = "large-rg"
        ttl                 = 300
        records             = ["1.1.1.1"]
}

resource "azurerm_dns_cname_record" "cname" {
        name                = "cname"
        zone_name           = " dnsrecords.com"
        resource_group_name = "large-rg"
        ttl                 = 300
        record              = "testing.trafficmanager.net."
}

```

### Debug Output

`2020/12/09 17:11:22 [TRACE] eval: *terraform.EvalWriteState
2020/12/09 17:11:22 [TRACE] EvalWriteState: recording 1 dependencies for azurerm_dns_zone.example
2020/12/09 17:11:22 [TRACE] EvalWriteState: writing current state object for azurerm_dns_zone.example
2020/12/09 17:11:22 [TRACE] [walkRefresh] Exiting eval tree: azurerm_dns_zone.example
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example": visit complete
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example": dynamic subgraph completed successfully
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example": visit complete
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example (expand)": dynamic subgraph completed successfully
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example (expand)": visit complete
2020/12/09 17:11:22 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping
2020/12/09 17:11:22 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/12/09 17:11:22 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/12/09 17:11:22 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
2020-12-09T17:11:22.725-0800 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.39.0/windows_amd64/terraform-provider-azurerm_v2.39.0_x5.exe pid=18812
2020-12-09T17:11:22.725-0800 [DEBUG] plugin: plugin exited`

### Expected Behavior

Should be able to generate the 2000+ A and CNAME records

### Actual Behavior

Getting  “dns.RecordSetsClient#Get: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded” when running terraform apply
### Steps to Reproduce

`terraform apply`

**Comment by alisdair** [comment]
I see you've [filed the same issue on the provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9816), which I think is correct. This doesn't seem to be a core bug, so I'm closing this out.
