### ISSUE TITLE
Issue with iam_assumable_role_with_oidc terraform module

### ISSUE THREAD

**Issue by aknirak82** [hashicorp/terraform#27270]
I am using the terraform iam module to create an IAM role with OIDC and I am running into an issue. Its ignoring the variable oidc_fully_qualified_subjects. What am I missing ?

Here's what I am passing:

module "iam_assumable_role_with_oidc" {
  source = "git::ssh://git@bitbucket_url:port/tm/iam_role_oidc.git"
  create_role = true
  role_name = var.role_name
  tags = {
    Role = var.role_name
  }
  provider_url = var.provider_url

  role_policy_arns = [module.iam_policy.arn]
  number_of_role_policy_arns = 1

  oidc_fully_qualified_subjects = ["sts.amazonaws.com"]
}

If you look closely, there's no condition in the terraform plan. Please advise

# module.iam_assumable_role_with_oidc.module.iam_assumable_role_with_oidc.aws_iam_role.this[0] will be created
  + resource "aws_iam_role" "this" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRoleWithWebIdentity"
                      + Effect    = "Allow"
                      + Principal = {
                          + Federated = "arn:aws:iam::xxx:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/id"
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + max_session_duration  = 3600
      + name                  = "myRole"
      + path                  = "/"
      + tags                  = {
          + "Role" = "myRole"
        }
      + unique_id             = (known after apply)
    }

**Comment by jbardin** [comment]
We use GitHub issues for tracking Terraform bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
