### ISSUE TITLE
Terraform Cloud Create Run API Showing Unexpected Behavior

### ISSUE THREAD

**Issue by mnazir23** [hashicorp/terraform#27296]
### Terraform Version

```
0.14.2
```

### Problem Statement
Hi,

I am working with the Terraform Cloud APIs to automate runs in my workspace. 

For testing purposes, I created two different workspaces in the same organization: workspace A and B. I use the **Create Run API** call to queue a plan (automatic applies are off) in both of my workspaces using the same request payload as given below.

However, the Create Run API is showing different behavior for both the workspaces. For workspace A, the Create Run API works and queues a plan successfully but for workspace B, it assumes that we are trying to delete the infrastructure in the workspace.

### Terraform Cloud Create Run API Request Body
```terraform
{
  "data": {
    "attributes": {
      "is-destroy": "false",
      "message": "<Test Message>"
    },
    "type":"runs",
    "relationships": {
      "workspace": {
        "data": {
          "type": "workspaces",
          "id": "<Workspace ID>"
        }
      }
    }
  }
}
```

### Expected Behavior

The expected behavior is that the API call should trigger a run/queue plan every time it gets called. 

### Actual Behavior

The API call works different for different workspaces. For one workspace, the API successfully created a run, for another it tried to delete the whole infrastructure. 

I used the same request payload as shown above for both the workspaces. As far as I have been able to tell, in the above payload, the **{ "is_destroy": "false" }** attribute is getting parsed/interpreted differently for the two workspaces. For workspace A, it gets treated as **false** meaning we are not trying to destroy the infrastructure but simply queueing a plan, whereas for workspace B, it does not get interpreted as **false** and hence it tries to delete everything.

### Steps to Reproduce

1. Create two different workspaces within the same organization.
2. Run the Create Run API using Postman. Make sure to use the above mentioned payload.
3. Use the same API to trigger run in both workspaces one after another.

(In some cases, the API first seemed to work well for both workspaces but after some time the behavior changed to what has been stated in the problem statement)

### Additional Context

Create Run API can be found [here](https://www.terraform.io/docs/cloud/api/run.html#create-a-run)

**Comment by qwerty1979bg** [comment]
@mnazir23, Is it creating a "destroy" run or you triggered a run with a configuration version that has (empty?) Terraform code that would make Terraform mark resources for deletion ?

Check / share the results of the run.

You can add an ENV variable named "TF_LOG" with a value of "TRACE" do add [debuging info](https://www.terraform.io/docs/internals/debugging.html).

**Comment by apparentlymart** [comment]
Hi @mnazir23! Thanks for reporting this and sorry for the delayed response.

We use issues in this repository to represent bugs and feature requests in Terraform CLI. Terraform Cloud is developed by other teams who don't typically monitor this repository, and they prefer to hear about bug reports and feature requests via the customer support system.

If you have a paid account on Terraform Cloud, please send this feedback to your usual support contacts. Otherwise, you can contact the Terraform Cloud support team at [tf-cloud-support@hashicorp.com](mailto:tf-cloud-support@hashicorp.com). If you contact the support team, be sure to include your Terraform Cloud username and organization name in your request.

Thanks again!
