### ISSUE TITLE
Not setting `private_ips` on `aws_network_interface` resource causes permadiff

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform#2729]
Example terraform config:

```
provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "default" {
  cidr_block = "10.40.0.0/19"
}

resource "aws_subnet" "private" {
  vpc_id            = "${aws_vpc.default.id}"
  availability_zone = "us-east-1a"
  cidr_block        = "10.40.0.0/22"
}

resource "aws_network_interface" "router" {
  subnet_id = "${aws_subnet.private.id}"
}
```

Terraform doesn't appear to be storing the IP addresses that AWS assigns to it automatically in the state file which is what I would expect. Instead, it thinks that there should be no `private_ips` and tries to destroy and recreate the resource.

**Comment by jszwedko** [comment]
cc/ @zdzolton

**Comment by catsby** [comment]
Thanks @jszwedko – patched in #2738

**Comment by jszwedko** [comment]
Awesome, thanks @catsby -- apologies for missing your PR, I looked yesterday, but failed to look today before submitting to see if one already existed.

**Comment by catsby** [comment]
closing since @jszwedko fixed it https://github.com/hashicorp/terraform/pull/2743
