### ISSUE TITLE
azurerm_monitor_metric_alert failing to update action block in tfstate file

### ISSUE THREAD

**Issue by romeomorcia** [hashicorp/terraform#27309]
Hello, I've created this issue also in AZURERM github but as i don't know really if this is related to terraform itself or azurerm provider, i'll open an issue here.

### Terraform (and Provider) Version

```
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/azuread v1.0.0
+ provider registry.terraform.io/hashicorp/azurerm v2.34.0
```

### Affected Resource(s)

* `azurerm_monitor_metric_alert`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "main" {
  name     = "example-resources"
  location = "West US"
}

resource "azurerm_storage_account" "to_monitor" {
  name                     = "examplestorageaccount"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_monitor_action_group" "main" {
  name                = "example-actiongroup"
  resource_group_name = azurerm_resource_group.main.name
  short_name          = "exampleact"

  webhook_receiver {
    name        = "callmyapi"
    service_uri = "http://example.com/alert"
  }
}

resource "azurerm_monitor_action_group" "main_second" {
  name                = "example-actiongroup-second"
  resource_group_name = azurerm_resource_group.main.name
  short_name          = "exampleactsec"

  webhook_receiver {
    name        = "callmyapi"
    service_uri = "http://example.com/alert"
  }
}

resource "azurerm_monitor_metric_alert" "example" {
  name                = "example-metricalert"
  resource_group_name = azurerm_resource_group.main.name
  scopes              = [azurerm_storage_account.to_monitor.id]
  description         = "Action will be triggered when Transactions count is greater than 50."

  criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts"
    metric_name      = "Transactions"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = 50

    dimension {
      name     = "ApiName"
      operator = "Include"
      values   = ["*"]
    }
  }

  action {
    action_group_id = azurerm_monitor_action_group.main.id
  }
```

### Expected Behaviour

The tfstate file should've been updated with the ID of the secondary action group.

### Actual Behaviour

Even if we apply the changes to the .tf main file by setting the secondary action group as "action_group" for the azurerm_monitor_metric_alert resource, tfstate is not being updated in the azurerm_monitor_metric_alert object state in "action" block.

### Steps to Reproduce

1. Create the resource with the first action group set.
2. Set secondary action group instead of the first one.
3. `terraform apply` 
4. Check tfstate file

If this cannot be reproduced:
1. Create the resource with the first action group set.
2. Create a third action group and add it through AZ CLI to the alert rule
3. In tf file, apply changes and replace the first action group with the secondary one
4. `terraform apply`

If this cannot be reproduced:
1. Create the resource with the first action group set.
2. Delete the action group manually from az cli or azure portal
3. Replace in main.tf file the action group with the second one
4. `terraform apply` (will go in error during apply like below)

`Error: Error creating or updating metric alert "name_metric" (resource group "***"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Action Group /subscriptions/***/resourceGroups/... Not found`

### Important Factoids

I've found this issue because in one of my azurerm_monitor_metric_alert I've got an error while applying changes to it because in the tfstate file it had a very old action group that doesn't exist anymore. I've resolved by setting another existing action group manually in the tfstate file but after changing it to another target action group, the tfstate file wasn't edited at all.

### References

- [9891 azurerm](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9891)

**Comment by jbardin** [comment]
Hi @romeomorcia 

This appears to be an issue with the provider itself. Since you already opened an issue in their repo, I'll close this for now. 

Thanks!

**Comment by romeomorcia** [comment]
@jbardin Hello, sorry for bothering you on a closed ticket but seems like no-one from azurerm side is willing to answer to my issue... Do you have any chance of contacting anyone from azurerm side so they at least check the ticket?

Thanks!
