### ISSUE TITLE
Ordering issue when removing resource and reference to that resource in another one.

### ISSUE THREAD

**Issue by rolandkool** [hashicorp/terraform#27302]
This bug was reported first to the Google Terraform Provider issue tracker: https://github.com/hashicorp/terraform-provider-google/issues/7969. It is believed to be a bug in terraform itself and suggested to raise an issue here as well. Related issue could be https://github.com/hashicorp/terraform/issues/20196

### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/google v3.50.0

Also tested with
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/google v3.51.0

### Affected Resource(s)

* google_access_context_manager_access_level
* google_access_context_manager_service_perimeter

### Terraform Configuration Files

```tf
resource "google_access_context_manager_access_level" "access_level_test" {
  provider    = google.vpcsc
  parent      = "accessPolicies/1234"
  name        = "accessPolicies/1234/accessLevels/access_level_test"
  title       = "access_level_test"
  basic {
    combining_function = "AND"
    conditions {
      members = [
        "user:someone@domain.com",
      ]
    }
    conditions {
      ip_subnetworks = [
        "1.2.3.4/32",
        "4.5.6.7/32",
      ]
    }
  }
}
resource "google_access_context_manager_access_level" "another_access_level_test" {
  provider    = google.vpcsc
  parent      = "accessPolicies/1234"
  name        = "accessPolicies/1234/accessLevels/another_access_level_test"
  title       = "another_access_level_test"
  basic {
    combining_function = "AND"
    conditions {
      members = [
        "user:someone@domain.com",
      ]
    }
    conditions {
      ip_subnetworks = [
        "1.2.3.4/32",
        "4.5.6.7/32",
      ]
    }
  }
}
resource "google_access_context_manager_service_perimeter" "tftest" {
  provider       = google.vpcsc
  parent         = "accessPolicies/1234"
  name           = "accessPolicies/1234/servicePerimeters/tftest"
  title          = "tftest"
  perimeter_type = "PERIMETER_TYPE_REGULAR"
  status {
    restricted_services = [
      "storage.googleapis.com",
      "pubsub.googleapis.com",
    ]
    access_levels = [
      google_access_context_manager_access_level.access_level_test.name,
      google_access_context_manager_access_level.another_access_level_test.name,
    ]
  }
  lifecycle {
    ignore_changes = [ status[0].resources ]
  }
}
```

### Expected Behavior

When removing the `another_access_level_test` `google_access_context_manager_access_level` resource and the reference in the `access_levels` array in the `google_access_context_manager_service_perimeter` resource in a single run, terraform fails with the following error:

> google_access_context_manager_access_level.another_access_level_test: Destroying... [id=accessPolicies/1234/accessLevels/another_access_level_test]
> google_access_context_manager_service_perimeter.tftest: Modifying... [id=accessPolicies/1234/servicePerimeters/tftest]
> google_access_context_manager_service_perimeter.tftest: Modifications complete after 3s [id=accessPolicies/1234/servicePerimeters/tftest]

Error: Error when reading or editing AccessLevel: googleapi: Error 400: Level name 'another_access_level_test' is not available in this Access Policy resource, but is referenced in 'status' field of Perimeter 'tftest'. If you are trying to delete a Level which is referenced in this Perimeter, you must first remove the reference.

### Actual Behavior

It would expect it to succeed. Terraform should update the service perimeter resource first before destroying the access_level.

### Steps to Reproduce

Use example tf files provided, apply the changes to create the perimeter and access levels. Remove one access level and the reference in the perimeter resource. After removal, the config looks like:

```tf
resource "google_access_context_manager_access_level" "access_level_test" {
  provider    = google.vpcsc
  parent      = "accessPolicies/1234"
  name        = "accessPolicies/1234/accessLevels/access_level_test"
  title       = "access_level_test"
  basic {
    combining_function = "AND"
    conditions {
      members = [
        "user:someone@domain.com",
      ]
    }
    conditions {
      ip_subnetworks = [
        "1.2.3.4/32",
        "4.5.6.7/32",
      ]
    }
  }
}
resource "google_access_context_manager_service_perimeter" "tftest" {
  provider       = google.vpcsc
  parent         = "accessPolicies/1234"
  name           = "accessPolicies/1234/servicePerimeters/tftest"
  title          = "tftest"
  perimeter_type = "PERIMETER_TYPE_REGULAR"
  status {
    restricted_services = [
      "storage.googleapis.com",
      "pubsub.googleapis.com",
    ]
    access_levels = [
      google_access_context_manager_access_level.access_level_test.name,
    ]
  }
  lifecycle {
    ignore_changes = [ status[0].resources ]
  }
}
```

Run terraform apply and observe the error.

I've also tried with a `depends_on` on the perimeter resource and on the access_level resource and changed the references in the `access_levels` array to actual names like (`accessPolicies/1234/accessLevels/another_access_level_test`).

In all cases, error remains.

**Comment by jbardin** [comment]
Hi @rolandkool,

I'm not familiar with the specific resources here, so it's hard to sort out exactly what the ordering requirements should be. The snippet of the output you show indicates terraform is completing the operations in the defined order. You however mentioned that you want to "update the service perimeter resource first before destroying the access_level". This is not the default ordering of operations, since destroying resources will happen before creates and updates. If you want to invert the order of operations, you need to use `create_before_destroy`. 

Again, not being familiar with the details of the resources I'm not sure what other impact that may have, but looking at the required attributes it appears it may interfere with resource replacement, since specific names are required and may need to be unique. If replacement isn't a concern for you, then you should be able to apply the configuration with `create_before_destroy` and get the desired order when you remove the resource from the configuration.

Thanks!

**Comment by rolandkool** [comment]
Hi @jbardin 

Thanks for your feedback and suggestion to use `create_before_destroy`. That seems to have helped:

> google_access_context_manager_access_level.another_access_level_test: Destroying... [id=accessPolicies/1234/accessLevels/another_access_level_test]
> google_access_context_manager_service_perimeter.tftest: Modifying... [id=accessPolicies/1234/servicePerimeters/tftest]
> google_access_context_manager_access_level.another_access_level_test: Destruction complete after 2s
> google_access_context_manager_service_perimeter.tftest: Modifications complete after 2s [id=accessPolicies/1234/servicePerimeters/tftest]

> Apply complete! Resources: 0 added, 1 changed, 1 destroyed.

It still does a destroy first, but that doesn't fail as there's also a modify done.

**Comment by jbardin** [comment]
Hi @rolandkool 

If the ordering is correct, but still fails occasionally it is often due to eventual consistency in the remote service. That can sometimes be checked by doing the removal in steps, or adding in artificial delays. Since the order of operations appears to match the configuration, I'll close this out. 

Thanks!
