### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by andrewyding** [hashicorp/terraform#27308]
Error: Provider produced inconsistent final plan

When expanding the plan for module.aks_helm.helm_release.release["dmuatmdm"]
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/helm" produced an invalid new value for .set:
block set length changed from 1 to 5.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.aks_helm.helm_release.release["dmuatmdm-mdmdeployment"] to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/helm" produced an invalid new value for .set:
block set length changed from 1 to 8.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by jbardin** [comment]
Hi @andrewyding,

Unfortunately there's not enough information here to determine what may have gone wrong. Can you please fill out the Bug Report issue template with the necessary information. The error does resemble some more recent issue, so you may want to ensure you are testing with the latest version of Terraform (currently 0.14.2) as well. 

Thanks!
