### ISSUE TITLE
Expose an "ami" attribute for Atlas Artifacts

### ISSUE THREAD

**Issue by pearkes** [hashicorp/terraform#2731]
Currently an artifact exports something like this:

```
atlas_artifact.example:
  id = us-east-1:ami-b9985bd2
  build = latest
  file_url =
  metadata_full.# = 1
  metadata_full.region-us-east-1 = ami-b9985bd2
  name = hashicorp/example
  slug = hashicorp/example/amazon.ami/1
  type = amazon.ami
```

Right now, writing Terraform configuration that references just this AMI requires you to hardcode the region, like this:

```
ami = "${atlas_artifact.example.metadata_full.region-us-east-1}"
```

Totally agree with the decision to write the region into the ID (as in Amazon, AMIs are per-region) but it'd be great to get an `atlas_artifact.example.metadata_full.ami` helper so moving between regions doesn't require rewriting the artifact reference.

Hope that makes sense!

**Comment by jedineeper** [comment]
Would love to see this, currently doing `${element(split(":", atlas_artifact.example.id),1)}` to get my ID out

**Comment by clstokes** [comment]
+1 for a better way to reference Atlas artifacts, without tying them to a region or other specific qualifier.

**Comment by maxenglander** [comment]
+1, and thanks @jedineeper for the work-around

**Comment by pearkes** [comment]
For newly built artifacts in Atlas we now automatically parse and store a metadata key called `ami_id`. For example:

```
ami = "${atlas_artifact.example.metadata_full.ami_id}"
```

You can see this and a list of other metadata keys in the [artifacts UI](https://atlas.hashicorp.com/artifacts) in Atlas:

![image](https://cloud.githubusercontent.com/assets/846194/9865368/096fd5ec-5b0a-11e5-963c-9d82e11e0f47.png)
