### ISSUE TITLE
provider.okta: Incompatible API version with plugin. Plugin version: 5, Ours: 4

### ISSUE THREAD

**Issue by rahul-sambyal** [hashicorp/terraform#27312]
While trying to create Okta resources via terraform I am facing the below mentioned error : 

`2020/12/17 17:07:52 [DEBUG] plugin: waiting for all plugin processes to complete...
2020/12/17 17:07:52 [ERR] yamux: Failed to read stream data: read tcp 127.0.0.1:XXXXX->127.0.0.1:XXXXX: wsarecv: An existing connection was forcibly closed by the remote host.
2020/12/17 17:07:52 [ERR] yamux: Failed to write header: write tcp 127.0.0.1:XXXXX->127.0.0.1:XXXXX: use of closed network connection
2020-12-17T17:07:52.933+0530 [WARN ] plugin: error closing client during Kill: err="unexpected EOF"
* provider.okta: Incompatible API version with plugin. Plugin version: 5, Ours: 4`

This error is specific to newly released Okta version 3.7.1 (released 16/12/2020)
I tried to roll back to Okta version 3.6.1 (released 14/11/2020) and it works just fine.
Can anyone confirm if this is just with new version or there is something else to it.

**Comment by jbardin** [comment]
Hi @rahul-sambyal,

It appears that you are using the Okta provider with an unsupported version of terraform. If you are using a current terraform release, I suggest you file an issue with the Okta provider here: https://github.com/oktadeveloper/terraform-provider-okta/issues. If you have questions about using the new provider, we can sometimes help with certain simple problems here, but it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks

**Comment by rahul-sambyal** [comment]
Thanks @jbardin, yup indeed I am using an old version.
Couldn't find Okta in [linked provider repos](https://github.com/terraform-providers). Will keep the pointers in mind for next time. Cheers!
