### ISSUE TITLE
in-house provider not working

### ISSUE THREAD

**Issue by Fabian1976** [hashicorp/terraform#27358]
### Terraform Version

```
0.13.5
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 3.0"
    }
    myphpipam = {
      source = "terraform.cmc.nl/conclusionmc/myphpipam"
      version = "1.0.0"
    }
    template = {
      source = "hashicorp/template"
      version = "2.2.0"
    }
  }
  required_version = ">= 0.13"
}
```

### Debug Output
I won't paste complete debug output. Only relevant section.

```
2020/12/23 08:23:27 [DEBUG] will search for provider plugins in /Users/fvanderhoevenconclusion.nl/.terraform.d/plugins
2020/12/23 08:23:27 [TRACE] getproviders.SearchLocalDirectory: /Users/fvanderhoevenconclusion.nl/.terraform.d/plugins is a symlink to /Users/fvanderhoevenconclusion.nl/.terraform.d/plugins
2020/12/23 08:23:27 [TRACE] getproviders.SearchLocalDirectory: found terraform.cmc.nl/conclusionmc/myphpipam v1.0.0 for darwin_amd64 at /Users/fvanderhoevenconclusion.nl/.terraform.d/plugins/terraform.cmc.nl/conclusionmc/myphpipam/1.0.0/darwin_amd64
2020/12/23 08:23:27 [DEBUG] ignoring non-existing provider search directory /Users/fvanderhoevenconclusion.nl/Library/Application Support/io.terraform/plugins
2020/12/23 08:23:27 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/12/23 08:23:31 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
2020/12/23 08:23:31 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins
2020/12/23 08:23:31 [TRACE] getproviders.SearchLocalDirectory: found terraform.cmc.nl/conclusionmc/myphpipam v1.0.0 for darwin_amd64 at .terraform/plugins/terraform.cmc.nl/conclusionmc/myphpipam/1.0.0/darwin_amd64
2020/12/23 08:23:31 [TRACE] providercache.fillMetaCache: including .terraform/plugins/terraform.cmc.nl/conclusionmc/myphpipam/1.0.0/darwin_amd64 as a candidate package for terraform.cmc.nl/conclusionmc/myphpipam 1.0.0
2020/12/23 08:23:32 [DEBUG] checking for provisioner in "/Users/fvanderhoevenconclusion.nl/.terraform.d/plugins"
2020/12/23 08:23:32 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2020/12/23 08:23:33 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
2020/12/23 08:23:33 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins
2020/12/23 08:23:33 [TRACE] getproviders.SearchLocalDirectory: found terraform.cmc.nl/conclusionmc/myphpipam v1.0.0 for darwin_amd64 at .terraform/plugins/terraform.cmc.nl/conclusionmc/myphpipam/1.0.0/darwin_amd64
2020/12/23 08:23:33 [TRACE] providercache.fillMetaCache: including .terraform/plugins/terraform.cmc.nl/conclusionmc/myphpipam/1.0.0/darwin_amd64 as a candidate package for terraform.cmc.nl/conclusionmc/myphpipam 1.0.0
2020/12/23 08:23:33 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
- Using previously-installed -/aws v3.22.0
2020/12/23 08:23:33 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
- Using previously-installed -/template v2.2.0
- Using previously-installed hashicorp/template v2.2.0
- Using previously-installed hashicorp/aws v3.22.0
- Using previously-installed terraform.cmc.nl/conclusionmc/myphpipam v1.0.0
- Finding latest version of hashicorp/myphpipam...
2020/12/23 08:23:33 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/myphpipam/versions
2020/12/23 08:23:33 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/myphpipam/versions
2020/12/23 08:23:34 [TRACE] providercache.fillMetaCache: using cached result from previous scan of .terraform/plugins
2020/12/23 08:23:34 [DEBUG] GET https://registry.terraform.io/v1/providers/-/myphpipam/versions
2020/12/23 08:23:34 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/myphpipam/versions

Failed to install provider

Error while installing hashicorp/myphpipam: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/myphpipam
```

### Expected Behavior

In-house provider should be installed and working.

### Actual Behavior

The logs and output seem to indicate that the in-house provider is installed, but at the final step it tries to download it from the terraform registry, even though it allready installed it from the local file-system.

### Steps to Reproduce

I've placed the custom provider in the following folder `~/.terraform.d/plugins`. This is the output of `tree`:
```
.
└── terraform.cmc.nl
    └── conclusionmc
        └── myphpipam
            └── 1.0.0
                └── darwin_amd64
                    └── terraform-provider-myphpipam_v1.0.0
```
Then run `terraform init`. The logs indicate that the provider is installed but at the final step it also tries to download it from the registry, which obvously fails.

I've also looked in the `<PROJECT>/.terraform/plugins` folder of the terraform-base, and the plugin is also installed there. 
Tree output of that folder:
```
└── terraform.cmc.nl
    └── conclusionmc
        └── myphpipam
            └── 1.0.0
                └── darwin_amd64 -> /Users/fvanderhoevenconclusion.nl/.terraform.d/plugins/terraform.cmc.nl/conclusionmc/myphpipam/1.0.0/darwin_amd64
```

So all seems to install fine, until the last step. Am I missing something?

**Comment by pselle** [comment]
@Fabian1976 Apologies for the delay, the team is back after some time off. In your debug log, as you saw, it appears Terraform is looking for the wrong provider: `- Finding latest version of hashicorp/myphpipam...`. This makes me wonder if perhaps you have a submodule using leveraging provider? Each module needs to declare its own `required_providers`.

**Comment by braunsonm** [comment]
This is definitely a bug @pselle I'm not sure what your comment refers to but we're seeing the same thing. If you use modules with a local provider it will never pass the init phase even though it shows it's been installed it will still try to reach out for the latest version on the registry.
This also fails when using dev overrides.

**Comment by pselle** [comment]
Hi @braunsonm, this issue is not yet triaged (thus the `new` label). Could you provide a simplified config that demonstrates the issue you're talking about? 

My comment is discussing [`provider_requirements`](https://www.terraform.io/docs/language/providers/requirements.html) are a per-module concept -- when people report this behavior as a bug, often it is because they do not have `required_providers` in the modules called by the root Terraform configuration. If you're seeing a bug, we'd be happy to investigate when there's more information to replicate it.

**Comment by braunsonm** [comment]
@pselle Hey, I think the issue that referenced this explains it much better. And includes an example: https://github.com/hashicorp/terraform/issues/27459

Basically the `init` phase will never pass if you're using a provider you overrided or passed as a file system mirror if you are ALSO using a public registry provider. It will still try to look at the hashicorp registry to resolve the latest version.

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.43.0"
    }
    k14s = {
      // Local provider
      source  = "carvel.dev/carvel/k14s"
      version = "0.7.0"
    }
  }
}
```

Installed as:
```
terraform.d
└── plugins
    └── carvel.dev
        └── carvel
            └── k14s
                └── 0.7.0
                    ├── darwin_amd64
                    │   └── terraform-provider-k14s
                    ├── linux_amd64
                    │   └── terraform-provider-k14s
                    └── windows_amd64
                        └── terraform-provider-k14s
```

```
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding carvel.dev/carvel/k14s versions matching "0.7.0"...
- Finding hashicorp/azurerm versions matching "2.43.0"...
- Finding latest version of hashicorp/k14s...
- Installing carvel.dev/carvel/k14s v0.7.0...
- Installed carvel.dev/carvel/k14s v0.7.0 (unauthenticated)
- Installing hashicorp/azurerm v2.43.0...
- Installed hashicorp/azurerm v2.43.0 (signed by HashiCorp)
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider hashicorp/k14s:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/k14s
If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.
```

You can also add a file system mirror like in the issue I referenced above without any luck. If you specify a dev overridden module it will still try to look it up in the registry. You can see that TF correctly finds the provider locally and installs it, but tries to check for versions against the registry.

**Comment by Fabian1976** [comment]
Aah, yes. I've added to other submodules and then it appears to be working. But it is strange behaviour and braunsonm pointed out.

**Comment by pselle** [comment]
Thanks for the updates, I've relabeled this as `working as designed` and I know we have other issues related to this area of friction (such as https://github.com/hashicorp/terraform/issues/26448) -- generally we want to encourage everyone to adopt the `required_providers` but our docs and the errors currently given by Terraform aren't serving that well. We're aware of this and hope to make it better!
