### ISSUE TITLE
Import fails with “Terraform version mismatch” using Terraform Cloud

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform#27353]
https://github.com/hashicorp/terraform/pull/26947 introduced an unexpected behaviour for Terraform Cloud users using local execution mode when running `terraform import`. The `terraform-version` field on the workspace properties would be set to whatever the default was when the workspace was first created — and prior to April this year there was no way to create a workspace with local execution mode directly so all workspaces would have had some version set — and that would cause `terraform import` to fail even though the project and its state files were all considerably newer.

The workaround is simple:

1. Change the workspace to remote execution mode
2. Select a version >= 0.14.0
3. Save
4. Set local execution mode
5. Save

**Comment by alisdair** [comment]
Hi @acdha, thanks for reporting this. I haven't yet been able to reproduce the issue but from re-reading the code I think I can see the issue. Unless I'm missing something, I don't think there's any reason for Terraform to check the remote workspace version when using local operations, so hopefully we should be able to fix this.

In the mean time, can you confirm that using the `-ignore-remote-version` flag with `terraform import` works as expected?
