### ISSUE TITLE
core: Save used module version in state

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#2736]
Even though there's a way to pin any module to a specific version (e.g. by using `?ref` for git & mercurial), I think that there would be benefit in saving module version in state.

It may not be possible for [all supported storages](https://github.com/hashicorp/terraform/blob/4052be6c7aefb73f65c088791c997aef43ce56fc/config/module/get.go#L41-L47):

``` go
    Getters = map[string]Getter{
        "file":  new(FileGetter),
        "git":   new(GitGetter),
        "hg":    new(HgGetter),
        "http":  httpGetter,
        "https": httpGetter,
    }
```

but I think it's worth implementing at least for the ones where it's possible - git + mercurial (version hash).

I believe this would help improving reproducibility of the whole environment between team members if version-pinning is not used, make operations safer.

It may also help solving https://github.com/hashicorp/terraform/issues/1568

**Comment by phinze** [comment]
+1 Good idea.

**Comment by teamterraform** [comment]
#4234 seems to be representing the same idea as this one; although that other issue is newer than this one, it has more discussion associated with it and so we'll close that one to consolidate over there.
