### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by teruz** [hashicorp/terraform#27371]
Hi, I tried terraform with IBM Cloud Schematics Service, but it failed with message "TERRAFORM CRASH". Anybody can help to resolve it?

---------------

 2020/12/25 08:54:07 -----  New Workspace Action  -----
 2020/12/25 08:54:07 Request: activitId=defe5d8926d38f6df11447059f4a48da, account=6b7c81b7463e2e8dbefbd3fa223c9de3, owner=TERUZ@jp.ibm.com, requestID=1cbeef3d-5eaa-45b6-a72c-3f12d893b361
 2020/12/25 08:54:07 Related Activity: action=WORKSPACE_CREATE, workspaceID=paloalto-a4a21bc1-2ff4-40, processedBy=orchestrator-5d8b64f6b8-ck85j
 2020/12/25 08:54:07 Related Workspace: name=paloalto, sourcerelease=(not specified), sourceurl=https://github.com/PaloAltoNetworks/ibmcloud/archive/v1.2.tar.gz
 2020/12/25 08:54:10  --- Ready to execute the command --- 
 2020/12/25 08:54:10 -----  New Action  -----
 2020/12/25 08:54:10 Request: RepoURL=https://github.com/PaloAltoNetworks/ibmcloud/archive/v1.2.tar.gz, WorkspaceSource=Schematics, Branch=, Release=, Folder=ibmcloud-1.2
 2020/12/25 08:54:10 Related Activity: action=CREATE_TAR_WORKSPACE,processedBy=sandbox-5f6c6b867d-8sgqd_775
 2020/12/25 08:54:10 Getting tar download command
 2020/12/25 08:54:13 No Vulnerabilities Found. Successfully saved all the files from the repo.
 2020/12/25 08:54:14 Successfully read the README file
 2020/12/25 08:54:15 Done with the Activity
 2020/12/25 08:54:15  --- Ready to execute the command --- 
 2020/12/25 08:54:16 workspace.template.SecFile: 24f386b2-47a7-4061-bbf8-e7ce1bdf47f4
 2020/12/25 08:54:15 -----  New Action  -----
 2020/12/25 08:54:15 Request: requestID=1cbeef3d-5eaa-45b6-a72c-3f12d893b361
 2020/12/25 08:54:16 Related Activity: action=Apply, workspaceID=paloalto-a4a21bc1-2ff4-40, processedByOrchestrator=1cbeef3d-5eaa-45b6-a72c-3f12d893b361_defe5d8926d38f6df11447059f4a48da, processedByJob=job12-76564d54cb-752jr
 
 2020/12/25 08:54:21 -----  Terraform INIT  -----
 2020/12/25 08:54:21 Starting command: terraform init -input=false -lock=false -no-color
 2020/12/25 08:54:21 Terraform init | 
 2020/12/25 08:54:21 Terraform init | Initializing the backend...
 2020/12/25 08:54:21 Terraform init | 
 2020/12/25 08:54:21 Terraform init | Initializing provider plugins...
 2020/12/25 08:54:22 Terraform init | 
 2020/12/25 08:54:22 Terraform init | The following providers do not have any version constraints in configuration,
 2020/12/25 08:54:22 Terraform init | so the latest version was installed.
 2020/12/25 08:54:22 Terraform init | 
 2020/12/25 08:54:22 Terraform init | To prevent automatic upgrades to new major versions that may contain breaking
 2020/12/25 08:54:22 Terraform init | changes, it is recommended to add version = "..." constraints to the
 2020/12/25 08:54:22 Terraform init | corresponding provider blocks in configuration, with the constraint strings
 2020/12/25 08:54:22 Terraform init | suggested below.
 2020/12/25 08:54:22 Terraform init | 
 2020/12/25 08:54:22 Terraform init | * provider.ibm: version = "~> 1.17"
 2020/12/25 08:54:22 Terraform init | * provider.random: version = "~> 3.0"
 2020/12/25 08:54:22 Terraform init | 
 2020/12/25 08:54:22 Terraform init | Terraform has been successfully initialized!
 2020/12/25 08:54:22 Command finished successfully.
 
 2020/12/25 08:54:22 -----  Terraform APPLY  -----
 2020/12/25 08:54:22 Starting command: terraform apply -state=terraform.tfstate -var-file=schematics.tfvars -auto-approve -no-color -lock=false -parallelism=10
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | Error: rpc error: code = Unavailable desc = transport is closing
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | panic: runtime error: invalid memory address or nil pointer dereference
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a85da3]
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: goroutine 61 [running]:
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.FunctionClient(0xc000fa1960, 0x2, 0xc000500d20, 0x0)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/config_functions.go:24 +0xe3
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.(*Config).ClientSession(0xc00083dd10, 0xc00083dd10, 0x0, 0x0, 0x0)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/config.go:891 +0x29a
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: github.com/IBM-Cloud/terraform-provider-ibm/ibm.providerConfigure(0xc000223ab0, 0x0, 0xc000891540, 0xc000223ab0, 0x0)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/provider.go:659 +0xa1f
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Configure(0xc0009c3300, 0xc000af6630, 0x221eca0, 0xc000af65a0)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/provider.go:275 +0x102
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).Configure(0xc0005093d0, 0x29a6840, 0xc000a1d8c0, 0xc0009f2a40, 0xc0005093d0, 0xc000a1d8c0, 0xc000fd5b78)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/helper/plugin/grpc_provider.go:487 +0x2e7
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_Configure_Handler(0x24f48c0, 0xc0005093d0, 0x29a6840, 0xc000a1d8c0, 0xc000af0000, 0x0, 0x29a6840, 0xc000a1d8c0, 0xc000aee000, 0x1ad)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/tfplugin5/tfplugin5.pb.go:3135 +0x214
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a7080, 0x29bc7a0, 0xc000102900, 0xc000519000, 0xc0009b9e00, 0x36f1e18, 0x0, 0x0, 0x0)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.206Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.206Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: google.golang.org/grpc.(*Server).handleStream(0xc0004a7080, 0x29bc7a0, 0xc000102900, 0xc000519000, 0x0)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.206Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.206Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000274070, 0xc0004a7080, 0x29bc7a0, 0xc000102900, 0xc000519000)
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.206Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.206Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.206Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [ERROR] <root>: eval: *terraform.EvalConfigProvider, err: rpc error: code = Unavailable desc = transport is closing
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: rpc error: code = Unavailable desc = transport is closing
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] [walkRefresh] Exiting eval tree: provider.ibm
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] vertex "provider.ibm": visit complete
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] dag/walk: upstream of "data.ibm_is_subnet.vnf_subnet3" errored, so skipping
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] dag/walk: upstream of "data.ibm_is_subnet.vnf_subnet1" errored, so skipping
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] dag/walk: upstream of "data.ibm_is_instance_profile.vnf_profile" errored, so skipping
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] dag/walk: upstream of "data.ibm_is_ssh_key.vnf_ssh_pub_key" errored, so skipping
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] dag/walk: upstream of "data.ibm_is_region.region" errored, so skipping
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] dag/walk: upstream of "data.ibm_is_subnet.vnf_subnet2" errored, so skipping
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] dag/walk: upstream of "provider.ibm (close)" errored, so skipping
 2020/12/25 08:54:28 Terraform apply | 2020/12/25 08:54:28 [TRACE] dag/walk: upstream of "root" errored, so skipping
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.209Z [DEBUG] plugin: plugin process exited: path=/home/nobody/.terraform.d/plugins/terraform-provider-ibm_v1.17.0 pid=125 error="exit status 2"
 2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.209Z [DEBUG] plugin: plugin exited
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | Terraform crashed! This is always indicative of a bug within Terraform.
 2020/12/25 08:54:28 Terraform apply | A crash log has been placed at "crash.log" relative to your current
 2020/12/25 08:54:28 Terraform apply | working directory. It would be immensely helpful if you could please
 2020/12/25 08:54:28 Terraform apply | report the crash with Terraform[1] so that we can fix this.
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | When reporting bugs, please include your terraform version. That
 2020/12/25 08:54:28 Terraform apply | information is available on the first line of crash.log. You can also
 2020/12/25 08:54:28 Terraform apply | get it by running 'terraform --version' on the command line.
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | SECURITY WARNING: the "crash.log" file that was created may contain 
 2020/12/25 08:54:28 Terraform apply | sensitive information that must be redacted before it is safe to share 
 2020/12/25 08:54:28 Terraform apply | on the issue tracker.
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | [1]: https://github.com/hashicorp/terraform/issues
 2020/12/25 08:54:28 Terraform apply | 
 2020/12/25 08:54:28 Terraform apply | !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 2020/12/25 08:54:28 Terraform APPLY error: Terraform APPLY errorexit status 1
 2020/12/25 08:54:28 Could not execute action

**Comment by danieldreier** [comment]
Hi @teruz! Thanks for reporting this. Based on looking at the following line, this appears to be a crash happening in the ibm provider itself, rather than in Terraform Core:
```
2020/12/25 08:54:28 Terraform apply | 2020-12-25T08:54:28.205Z [DEBUG] plugin.terraform-provider-ibm_v1.17.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a85da3]
```
You can see that the error is returned from `plugin.terraform-provider-ibm_v1.17.0`.

This needs to be fixed in the ibm provider itself; we can't do anything about it in Terraform Core. I'm going to close this issue, and your next step is to open an issue at https://github.com/IBM-Cloud/terraform-provider-ibm to report the same thing there. When you report an issue there, I encourage you to provide a reproduction case of how to trigger this crash - it is very hard to fix issues of this nature without a clear reproduction case.
