### ISSUE TITLE
List of objects with optional attribtues throws error

### ISSUE THREAD

**Issue by Matthewsre** [hashicorp/terraform#27374]
### Terraform Version
```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
```

### Terraform Configuration Files

```terraform
variable "microservices" {
  type = list(object({
    name       = string
    appservice = optional(string)
    function   = optional(string)
    sql        = optional(string)
    cosmos_containers = optional(list(object({
      name               = string
      partition_key_path = string
      max_throughput     = optional(number)
    })))
  }))
  default = [
    {
      name       = "service1"
      appservice = "plan"
      function   = "plan"
      sql        = "elastic"
      cosmos_containers = [
        {
          name               = "MyContainer"
          partition_key_path = "/PartitionKey"
        }
      ]
    },
    {
      name              = "service2"
      appservice        = "plan"
      function          = "consumption"
      sql               = "elastic"
    }
  ]
}
```

### Crash Output
panic: inconsistent list element types (cty.Object(map[string]cty.Type{"appservice":cty.String, "cosmos_containers":cty.List(cty.Object(map[string]cty.Type{"max_throughput":cty.Number, "name":cty.String, "partition_key_path":cty.String})), "function":cty.String, "name":cty.String, "sql":cty.String}) then cty.Object(map[string]cty.Type{"appservice":cty.String, "cosmos_containers":cty.List(cty.ObjectWithOptionalAttrs(map[string]cty.Type{"max_throughput":cty.Number, "name":cty.String, "partition_key_path":cty.String}, []string{"", "max_throughput"})), "function":cty.String, "name":cty.String, "sql":cty.String}))

goroutine 39 [running]:
github.com/zclconf/go-cty/cty.ListVal(0xc0004e8200, 0x2, 0x2, 0xc000967170, 0xc0008140f0, 0x1, 0x1)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/value_init.go:166 +0x5a8
github.com/zclconf/go-cty/cty/convert.conversionCollectionToList.func1(0x362fe20, 0xc0004acdd0, 0x2d04f00, 0xc0009555a0, 0x0, 0x0, 0x0, 0xc000100400, 0x10, 0x10, ...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/convert/conversion_collection.go:54 +0x793
github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x362fe20, 0xc0004acdd0, 0x2d04f00, 0xc0009555a0, 0x0, 0x0, 0x0, 0xc0006f0210, 0xc0008140e0, 0x362fe20, ...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/convert/conversion.go:46 +0x433
github.com/zclconf/go-cty/cty/convert.retConversion.func1(0x362fe20, 0xc0004acdd0, 0x2d04f00, 0xc0009555a0, 0xc0008140e0, 0x0, 0x2, 0x2e29c00, 0xc00033bb18, 0xc0009677a0)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/convert/conversion.go:188 +0x72
github.com/zclconf/go-cty/cty/convert.Convert(0x362fe20, 0xc0004acdd0, 0x2d04f00, 0xc0009555a0, 0x362fe20, 0xc0004ac610, 0x362fda0, 0xc00004ea5f, 0x31d9300, 0xc000285bc0, ...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/convert/public.go:51 +0x1cb
github.com/hashicorp/terraform/terraform.checkInputVariables(0xc0009677a0, 0xc00095d7a0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/terraform/variables.go:255 +0x1b3
github.com/hashicorp/terraform/terraform.NewContext(0xc0005e59d0, 0x1, 0x1, 0xc0009af900, 0x1)
        /home/circleci/project/project/terraform/context.go:279 +0x11f3
github.com/hashicorp/terraform/backend/local.(*Local).contextDirect(0xc0004efee0, 0xc0009380e0, 0xc00096e340, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00095d4a0, 0xc0009325e0, ...)
        /home/circleci/project/project/backend/local/backend_local.go:178 +0x305
github.com/hashicorp/terraform/backend/local.(*Local).context(0xc0004efee0, 0xc0009380e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/backend/local/backend_local.go:111 +0xf18
github.com/hashicorp/terraform/backend/local.(*Local).opPlan(0xc0004efee0, 0x362dda0, 0xc0004e8c40, 0x362dda0, 0xc0004e8c80, 0xc0009380e0, 0xc0004e8c00)
        /home/circleci/project/project/backend/local/backend_plan.go:70 +0x2d8
github.com/hashicorp/terraform/backend/local.(*Local).Operation.func1(0xc0004ac190, 0xc0004ac1a0, 0xc0004ac1b0, 0xc0004efee0, 0xc0004ac180, 0x362dda0, 0xc0004e8c40, 0x362dda0, 0xc0004e8c80, 0xc0009380e0, ...)
        /home/circleci/project/project/backend/local/backend.go:340 +0xef
created by github.com/hashicorp/terraform/backend/local.(*Local).Operation
        /home/circleci/project/project/backend/local/backend.go:334 +0x36d

### Expected Behavior
object with List of object with optional attributes should be allowed. also fails if passing an empty list instead of using optional.

### Actual Behavior
Crashed with the output listed above

### Steps to Reproduce

1. Add optional variable provided above with 'experiments = [module_variable_optional_attrs]' set.
1. `terraform init`
2. `terraform plan`

### Additional Context
N/A

### References
N/A

**Comment by Matthewsre** [comment]
Found the same issue reported recently #27269 so this could be flagged as duplicate.

**Comment by danieldreier** [comment]
Thanks for reporting it, and thanks again for noticing it's a duplicate. I really appreciate this! Please make sure you 👍 issue #27269 because we factor that in heavily in our prioritization.
