### ISSUE TITLE
Terraform fmt changes and breaks module syntax

### ISSUE THREAD

**Issue by jkatic85** [hashicorp/terraform#27381]
### Terraform Version

```
Terraform v0.14.0
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {}

}

provider "aws" {
  region = var.region
  assume_role {
    role_arn     = var.role_arn
    session_name = "terraform-test-instance"
  }
}

resource "aws_security_group_rule" "security_group_rule_self" {
  count = (var.self == "true" ? 1 : 0)
  self              = true
  from_port         = var.from_port
  protocol          = var.protocol
  security_group_id = var.security_group_id
  to_port           = var.to_port
  type              = "ingress"
}
```

### Crash Output
Although you could _break_ the syntax just by running `terraform fmt` within the module folder, output from `git` actually shows what's broken:
```git commit -m "Addressing TF warnings"
[WARNING] The 'exclude' field in hook 'terragrunt_fmt' is a regex, not a glob -- matching '/*' probably isn't what you want here
Terraform fmt............................................................Failed
- hook id: terraform_fmt
- exit code: 2


Error: Missing newline after argument

  on main.tf line 16, in resource "aws_security_group_rule" "security_group_rule_self":
  15:   count = (var.self == "true" ? 1 : 0
  16:   ) self            = true

An argument definition must end with a newline.


Error: Missing newline after argument

  on main.tf line 16, in resource "aws_security_group_rule" "security_group_rule_self":
  15:   count = (var.self == "true" ? 1 : 0
  16:   ) self            = true

An argument definition must end with a newline.


Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1
Terragrunt fmt.......................................(no files to check)Skipped
```

### Expected Behavior
`Terraform fmt...........................................................Succeeded`
It shouldn't change valid syntax.

### Actual Behavior
`terraform fmt` breaks file syntax on `git commit` or, by being executed inside the module folder.

Valid syntax, gets changed from:
```terraform
  count = (var.self == "true" ? 1 : 0)
  self              = true
```
To:
```terraform
  count = (var.self == "true" ? 1 : 0
  ) self            = true
```

### Steps to Reproduce
1. Save to the `main.tf` file as shown in the example above with correct syntax
2. Run `terraform fmt`
3. Check the file for breaking syntax change

### Additional Context
We use the official [security-group-rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule) module, with code as presented above.
The issue manifested itself after trying to address warning message from Terraform:
```
Warning: Version constraints inside provider configuration blocks are deprecated

  on main.tf line 8, in provider "aws":
   8:   version = ">= 2.11"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.
```
Change to the code block was this:
```
 provider "aws" {
   region  = var.region
-  version = ">= 2.11"
```

Edit: Added code snippet that changes under _Actual Behavior_

**Comment by jkatic85** [comment]
It appears that the syntax changes so there is no actual issue with `terraform fmt` rather with my use of braces where they should be omitted:
- This doesn't work:
`count = (var.self == "true" ? 1 : 0)`
- This works:
`count = var.self == "true" ? 1 : 0`

**Comment by juzov-mag** [comment]
What if I want to multiline?

**Comment by jkatic85** [comment]
I tested that initially, it didn't work. 
There might be a workaround for this use case, but I opted to have everything in a single line ¯\_(ツ)_/¯
