### ISSUE TITLE
"missing provider" when attempting to override default

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#27409]
If a user attempts to override a default provider in a module, `init` will still find and store the default provider, but `plan` and `apply` will indicate that the provider cannot be found. 

### Config

```
# main.tf
terraform {
  required_providers {
    null = {
      source = "terraform.io/local/null"
    }
  }
}

module "mod" {
  source = "./mod"
  providers = {
    null = null
  }
}
```

```
# ./mod/main.tf
resource "null_resource" "a" {
}
```

### Output

```
% tf init
Initializing provider plugins...
- Reusing previous version of terraform.io/local/null from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Installing terraform.io/local/null v1.0.0...
- Installed terraform.io/local/null v1.0.0 (unauthenticated)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)

% tf plan
Error: missing provider provider["registry.terraform.io/hashicorp/null"]
```

Adding a "proxy provider block" to the module config does not change the error condition.

### Expected Result

The specific error is not useful because the provider does appear to be found. We can either allow this type of override, or catch the invalid configuration and indicate what needs to be changed.

**Comment by mildwonkey** [comment]
Interesting! This definitely _should not_ work; you cannot override a module's provider's namespace. That's a very deliberate design choice. We should catch that situation and return an error that the configuration is invalid.

**Comment by jbardin** [comment]
Updating with an example that probably should work. It seems passing in providers that don't use the default name is not working. Again it continues to fail even with a proxy provider block. The `foo` identifier was used here to avoid any possible conflict with the `null` keyword, but using `null` makes no difference. 

```
# main.tf
terraform {
  required_providers {
    foo = {
      source = "terraform.io/local/null"
    }
  }
}

module "mod" {
  source = "./mod"
  providers = {
    test = foo
  }
}
```

```
# ./mod/main.tf
terraform {
  required_providers {
    test = {
      source = "terraform.io/local/null"
    }
  }
}

resource "null_resource" "a" {
  provider = test
}
```

**Comment by jbardin** [comment]
Ah, found where the inconsistency lies. The `providers` map is looking for a _configuration block_, not the provider itself, but we're not reporting the missing config in any sort of validation. If everything is using the default provider names, the module gets the default provider rather than what is passed in. There is usually no distinction between the two when the config is empty, but internally we're silently resolving the provider differently.
