### ISSUE TITLE
[0.14] Can't use sensitive variables with query, value has marks, so it cannot be serialized

### ISSUE THREAD

**Issue by WilliamABradley** [hashicorp/terraform#27425]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.14.3
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 0.14"
}

variable "path" {
  type = string
}

variable "data" {
  type = string
  sensitive = true
}

data "external" "file_write" {
  working_dir = path.module
  program     = ["node", "configure.js"]

  query = {
    path = abspath(var.path)
    data = var.data
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

```
Error: .query["data"]: value has marks, so it cannot be serialized
```

### Expected Behavior
What should have happened?

Accepts the sensitive data, hides it from the diff.

### Actual Behavior
What actually happened?

Errors out, not accepting sensitive marking logic.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- hashicorp/terraform-provider-external#44

**Comment by alisdair** [comment]
Hi @WilliamABradley, thanks for reporting this. I was able to reproduce the problem with Terraform 0.14.3. The bug was fixed in #27335 which was released as part of 0.14.4 this week, so please upgrade to that version for the fix.
