### ISSUE TITLE
rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio

### ISSUE THREAD

**Issue by gyang909** [hashicorp/terraform#27431]
Terraform crashed today. I tried init again, rebooting my computer, upgrading to the latest Terraform version. All didn't help. The crash.log file is attached. Hope someone can guide me through the issue. Thanks a lot. -Gary

[crash.log](https://github.com/hashicorp/terraform/files/5778455/crash.log)

**Comment by gyang909** [comment]
It turned out that my credential expired. After update my credential, it succeeded. In the past however, terraform would tell me the reason.

**Comment by jbardin** [comment]
Hi @gyang909 

This crash is from the AWS provider, and I believe it is fixed in an upcoming release. If there is a regression around the handling of AWS credentials, I suggest you open an issue with the provider.

Thanks!
