### ISSUE TITLE
Import existing infrastructure

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [hashicorp/terraform#27441]
Hi,
What is the prefered way to import an existing resource group with all services in azure. 
Regards
Andreas

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
