### ISSUE TITLE
Migrating from `count = 1` resources to `for_each` resources produces unhelpful error

### ISSUE THREAD

**Issue by grahamc** [hashicorp/terraform#27465]
### Terraform Version

```
$ terraform version
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/null v3.0.0
```

### Terraform Configuration Files

Step one:

```hcl
resource "null_resource" "example" {
  count = 1
}
```

Step two:

```hcl
resource "null_resource" "example" {
  for_each = { foo = "bar" }
}
```

### Expected Behavior

I would expect to be able to use `terraform state mv` using the exact names produced by `terraform plan`, like this:

```
$ terraform plan
null_resource.example: Refreshing state... [id=962373015004004525]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # null_resource.example will be destroyed
  - resource "null_resource" "example" {
      - id = "962373015004004525" -> null
    }

  # null_resource.example["foo"] will be created
  + resource "null_resource" "example" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

then:

```
$ terraform state mv null_resource.example 'null_resource.example["foo"]'

Move "null_resource.example" to "null_resource.example[\"foo\"]"
Successfully moved 1 object(s).
```

or, have the diff output the resource name with `[0]`:

```
  # null_resource.example[0] will be destroyed
  - resource "null_resource" "example" {
      - id = "962373015004004525" -> null
    }

  # null_resource.example["foo"] will be created
  + resource "null_resource" "example" {
      + id = (known after apply)
    }
```

### Actual Behavior

Using the names printed by the diff, I get the following mysterious error:

```
$ terraform state mv null_resource.example 'null_resource.example["foo"]'

Error: Invalid target address

Cannot move null_resource.example to <invalid>..: the target must also be a
whole resource.
```

Note this error indicates the problem is in the name of the target, and doesn't hint at all to the name of the source. I would expect terraform's diff output or rename error message to guide me to this solution.

### Steps to Reproduce
1. Apply the "Step One" configuration
2. `terraform init`
3. `terraform apply`
4. Replace the configuration with the "Step Two" configuration
5. `terraform plan`, noticing the names of the removed and created resources
6. `terraform state mv null_resource.example 'null_resource.example["foo"]'`
7. try to diagnose the issue from the resulting error

### References
- #22301

**Comment by pselle** [comment]
Hey @grahamc! I think we can improve that error to help you get to what you want -- to move an _instance_; the error is trying to tell you that you have an invalid address for "take this resource and put it at this other resource" ... what you have is "take this resource and put it at this instance" and that's why Terraform gives you an error.

If you instead ran the command to move from one instance to another, you won't get an error:
```
$ terraform state mv null_resource.example[0] null_resource.example[\"foo\"]
Move "null_resource.example[0]" to "null_resource.example[\"foo\"]"
Successfully moved 1 object(s).
```

**Comment by grahamc** [comment]
Thanks for clarifying the `[0]` addition. I had a bit about that in my original write-up for the ticket, but I guess I deleted it during some editing :sweat_smile:.
