### ISSUE TITLE
OpenStack Image - use latest image

### ISSUE THREAD

**Issue by snooops** [hashicorp/terraform#27460]
Is this done? I can't find anything in the documentation, and the following issues lost tracking.

@jseaidou Thanks for the background. I understand the use case and I agree that hard-coded image-ids are no good here. However, I feel that placing this kind of logic in the `image_name` retrieval wouldn't be a good design. Let's say after it was implemented, someone wanted the earliest image instead.

Gophercloud (the underlying OpenStack Golang library that Terraform uses) doesn't support the Glance API yet, though most of the work has been [done](https://github.com/rackspace/gophercloud/pull/458). Once this is merged, I can see this kind of flexible image searching implemented. For example:

```
image {
  name = "Ubuntu 14.04"
  tag = "latest"
}
```

And hopefully that query would result in a single image-id, or else an error would be thrown.

In the meantime, what if the logic of determining the latest image was moved outside of Terraform: somehow or another, the latest image-id found its way to `latest-image-id.txt`, and you specified the following in your instance:

`image_id = "${trimspace(file("latest-image-id.txt"))}"`

Or maybe the image-id is stored in a Consul key (the example use of `consul_keys` in the [docs](https://www.terraform.io/docs/providers/consul/r/keys.html) is doing this exact thing - reading an ami ID)

Thoughts?

_Originally posted by @jtopjian in https://github.com/hashicorp/terraform/issues/6166#issuecomment-209734721_

**Comment by jbardin** [comment]
Hi @snooops 

This appears to be an issue regarding an openstack provider. If you are using [this provider](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs), you can file issue in their issue tracker [here](https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues)

Thanks
