### ISSUE TITLE
AWS Route53 Geo, Latency, and Weighted Record Policies

### ISSUE THREAD

**Issue by jwestboston** [hashicorp/terraform#2746]
Currently it is not possible to create AWS Route53 record entries for the non-Simple DNS policies in Terraform.  This is related / due to bug #330 

Can this feature please be added?  Would be helpful, so I can manage my DNS configuration within Terraform.

**Comment by catsby** [comment]
Thanks @jwestboston – specifically, you're looking to have Weighted, Latency, Geolocation, and Failover  types, correct?

**Comment by jwestboston** [comment]
@catsby Yes.  Well actually -- it looks like Weighted and Failover types are indeed already supported.  And I'm having success (so far) with the Weighted type, which is good.

So it looks like the Latency, Geolocation types just need to be added.

**Comment by TheLinuxNinja** [comment]
+1

**Comment by catsby** [comment]
Hello friends –

We added proper weighted, latency, and geo location records in #6954 thanks to the work of @acm1 !
