### ISSUE TITLE
alb listener certificate remove

### ISSUE THREAD

**Issue by karthickcse86** [hashicorp/terraform#27462]
### Current Terraform Version

```
...
```

### References

I am unable to remove existing listener certificate from AWS Application Load Balancer using terraform.  Please include this in feature version

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
