### ISSUE TITLE
Is there a plan to support MySQL as Terraform Backend?

### ISSUE THREAD

**Issue by YoungYang0820** [hashicorp/terraform#27471]
### Current Terraform Version

```
Terraform v0.13.5
```

### Use-cases

Want a consistent way to persist terraform state in MySQL
### Proposal

Per https://github.com/hashicorp/terraform/issues/23531 
We can have MySQL as an officially-supported Terraform Backend, or Terraform has a plugin mechanism for its backends so that we can add the support for MySQL backend without changing Terraform core.
### References

- #23531

**Comment by pkolyvas** [comment]
Hi @YoungYang0820 ! For the time being, we're not considering adding new remote state backends. As you noted there's no plugin mechanism at the moment. As Terraform has matured we're beginning to find ourselves in the same position as we were with providers; that is to say maintaining a growing number of state storage backends is problematic. 

This is by no means a "no", but we're unlikely to reconsider our position until we have a pluggable state storage interface. The natural next question there is "when?" Sadly, we don't have an answer at this time as we're deeply focused on getting Terraform to 1.0. 

Should you ever want to discuss this or any other concerns/issues around Terraform, my office doors are always open (links in my GH profile.)

**Comment by YoungYang0820** [comment]
Thanks for your quick response @pkolyvas ! No problem, we will evaluate other options. 

Looking forward to the v1.0
