### ISSUE TITLE
Explicit passing of Providers to module not working

### ISSUE THREAD

**Issue by RastogiAbhijeet** [hashicorp/terraform#27472]
### Terraform Version

```
... Terraform v0.14.2
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "0.14.2"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 3.30"
    }

    helm = {
      source  = "hashicorp/helm"
      version = "2.0.1"
    }

    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "1.13.3"
    }

    gitlab = {
      source  = "registry.terraform.io/gitlabhq/gitlab"
      version = "3.3.0"
    }

    random = {
      source  = "hashicorp/random"
      version = "3.0.0"
    }
  }
}

module "gitlab_kubernetes" {
  source = "../../../../terraform-modules/gitlab-kubernetes"

  gcp_project_location = var.gcp_project_location
  gitlab_project       = var.gitlab_project
  gitlab_token         = var.gitlab_token

  top_level_resource_suffix = random_id.tlrs.hex

  cluster = {
    gke_cluster  = local.cluster.gke_cluster
    gke_location = local.cluster.gke_location
    gke_project  = local.cluster.gke_project
    gke_endpoint = local.cluster.gke_endpoint

    gke_client_certificate     = local.cluster.gke_client_certificate
    gke_client_key             = local.cluster.gke_client_key
    gke_cluster_ca_certificate = local.cluster.gke_cluster_ca_certificate

    k8s_ns_production = local.k8s_elements.k8s_ns_production
    k8s_ns_sandbox    = local.k8s_elements.k8s_ns_sandbox
  }

  providers = {
    gitlab     = gitlab.b8_gitlab_k8s
    helm       = helm.b8_gitlab_k8s
    kubernetes = kubernetes.b8_gitlab_k8s
    google     = google.b8_gitlab_k8s
  }
}

...
```

### Debug Output

Providers required by configuration:
.
├── provider[registry.terraform.io/gitlabhq/gitlab] 3.3.0
├── provider[registry.terraform.io/hashicorp/random] 3.0.0
├── provider[registry.terraform.io/hashicorp/google] ~> 3.30
├── provider[registry.terraform.io/hashicorp/helm] 2.0.1
├── provider[registry.terraform.io/hashicorp/kubernetes] 1.13.3
├── provider[terraform.io/builtin/terraform]
└── module.gitlab_kubernetes
    ├── provider[registry.terraform.io/hashicorp/google]
    ├── provider[registry.terraform.io/hashicorp/gitlab]
    ├── provider[registry.terraform.io/hashicorp/kubernetes]
    └── provider[registry.terraform.io/hashicorp/helm]

### Crash Output

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding gitlabhq/gitlab versions matching "3.3.0"...
- Finding hashicorp/random versions matching "3.0.0"...
- Finding hashicorp/google versions matching "~> 3.30"...
- Finding hashicorp/helm versions matching "2.0.1"...
- Finding hashicorp/kubernetes versions matching "1.13.3"...
- Finding latest version of hashicorp/gitlab...
- Installing hashicorp/random v3.0.0...
- Installed hashicorp/random v3.0.0 (signed by HashiCorp)
- Installing hashicorp/google v3.52.0...
- Installed hashicorp/google v3.52.0 (signed by HashiCorp)
- Installing hashicorp/helm v2.0.1...
- Installed hashicorp/helm v2.0.1 (signed by HashiCorp)
- Installing hashicorp/kubernetes v1.13.3...
- Installed hashicorp/kubernetes v1.13.3 (signed by HashiCorp)
- Installing gitlabhq/gitlab v3.3.0...
- Installed gitlabhq/gitlab v3.3.0 (signed by a HashiCorp partner, key ID BC097C3333027B14

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/gitlab: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/gitlab

### Expected Behavior
On running `terraform init` No error should have been thrown

### Actual Behavior
 
 Got an error as the module was still trying to source gitlab provider from hashicorp namespace inside the module, where as in the parent module it is specified to source provider from gitlab namespace. 

### References
Used this as a reference to implement the solution
https://www.terraform.io/docs/configuration/meta-arguments/module-providers.html

**Comment by jbardin** [comment]
Hi @RastogiAbhijeet 

Though you have not shown the module configuration, I'm guessing that you have omitted the ["proxy configuration blocks"](https://www.terraform.io/docs/modules/providers.html#proxy-configuration-blocks), which are required for passing in providers to modules. See [Passing Providers Explicitly](https://www.terraform.io/docs/modules/providers.html#passing-providers-explicitly). If this is not the case, feel free to add more information here and we can investigate further.

This is a known pain point, and something we're working on clearing up. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
