### ISSUE TITLE
Crash on sigint on aws plan with expired creds

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/terraform#27500]
### Terraform Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.23.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = "us-west-1"
}

resource "aws_instance" "space" {
  ami           = "ami-0a16c82eb0cc3aad8"
  instance_type = "g3.4xlarge "
  key_name      = "aws-test-west"
}
```

### Debug Output

https://gist.github.com/mwhooker/27986cf7b9b7bcd78b01e8ee3b18d4fd

### Crash Output

This appears to be the same as what's in the debug output
### Expected Behavior

TF should exit gracefully

### Actual Behavior

a crash

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

Hi all,

I tried to plan an AWS configuration with expired credentials. It seems to spin for a while hoping the creds eventually become unexpired, so I ctrl+c to quit. That caused a crash and some text asking me to post the logs. I also tried to find the aws provider in https://github.com/terraform-providers, but I didn't see it, so posting here.

**Comment by bflad** [comment]
The fix for this will release in version 3.25.0 of the Terraform AWS Provider, likely later today. 👍
