### ISSUE TITLE
aws_instance Security groups are not refreshed properly. 

### ISSUE THREAD

**Issue by robertfirek** [hashicorp/terraform#2750]
When we add existing security group to aws_instance resource and at the same time this security group  was added manually plan shows that aws_instance should be modified.

I discovered that plan is not refreshed properly. In the state file attributes "vpc_security_group_ids" is updated properly, but attribute "security_groups" is not refreshed from Amazon.

For example we assigned an instane to sg-xxxxx3 manually in AWS Console and we also add this dependency to Terraform config file. The dependency in config was updated, but during the plan current state was not update. 
```
(...)
"security_groups.#": "2",
"security_groups.200000001": "sg-xxxxx1",
"security_groups.200000002": "sg-xxxxx2"
(...)                       
"vpc_security_group_ids.#": "3",
"vpc_security_group_ids.200000001": "sg-xxxxx1",
"vpc_security_group_ids.200000002": "sg-xxxxx2",
"vpc_security_group_ids.200000003": "sg-xxxxx3"
(...)
```

**Comment by phinze** [comment]
Hi @robertfirek - `vpc_security_group_ids` and `security_groups` are not really meant to be used together. In fact, `security_groups` is really only useful of in EC2 Classic environments. If you consolidate on `vpc_security_group_ids` does the behavior get better?

**Comment by robertfirek** [comment]
I will check behaviour with `vpc_security_groups_ids`. Probably you have right that this is the reason why it doesn't work properly, because we have this instance inside a non-default VPC. 

It is a little bit confusing. When I use `security_groups_ids` for instances in non-default VPC my security groups are still assigned properly in AWS, but it is not reflected in state file. Why this behaviour is split into two different property? Maybe when instance is assigned to non-default VPC it should be forbidden to use `security_groups_ids`

**Comment by robertfirek** [comment]
@phinze Thank you. It works now without any issue.

**Comment by catsby** [comment]
Thanks for following up @robertfirek :smile:
