### ISSUE TITLE
aws workspaces getting recreated.

### ISSUE THREAD

**Issue by uthayann** [hashicorp/terraform#27522]
aws workspaces get recreated every time, even though no changes were applied to tf files. 
It does see the current instance running during refresh state, but still destroys and recreates it. 
output:
# aws_workspaces_workspace.workspace-admin must be replaced
-/+ resource "aws_workspaces_workspace" "workspace-admin" {
      ~ computer_name                  = "WSAMZN-QAC5G8E8" -> (known after apply)
      ~ id                             = "ws-841wxws1g" -> (known after apply)
      ~ ip_address                     = "10.6.11.33" -> (known after apply)
      ~ state                          = "AVAILABLE" -> (known after apply)

**Comment by jbardin** [comment]
Hi @uthayann,

Without a complete example configuration we cannot determine what may be causing the resource to be resourced. If this is a question about the usage of a particular resource, we can sometimes help with certain simple problems here, but it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. If this is a problem with the `aws_workspaces_workspace` resource itself, you can file an issue in the [AWS Provider issue tracker](https://github.com/hashicorp/terraform-provider-aws/issues).

Thanks
