### ISSUE TITLE
digitalocean initial_filesystem_type creates 380 MB filesystem

### ISSUE THREAD

**Issue by hholst80** [hashicorp/terraform#27537]
The initial_filesystem_type flag does not actually provision the whole block device on creation.

Provision a block device @ 50 GB; connect it to a droplet. Mount it. Voila 380 MB of fantastic SSD backed storage.

- - - 

```
» tf version
Terraform v0.14.4
+ provider registry.terraform.io/digitalocean/digitalocean v2.3.0
```

```
resource "digitalocean_volume" "test" {
  name   = "test"
  region = "ams3"
  size   = 50
  initial_filesystem_type = "ext4"
}
```

**Comment by hholst80** [comment]
The same behavior is present with `doctl` so this might be a wont-fix.  Any workarounds that can be employed?

**Comment by alisdair** [comment]
This does not seem like a bug in Terraform itself, so I'm going to close it. I would recommend [submitting this report to the Digital Ocean provider repository](https://github.com/digitalocean/terraform-provider-digitalocean).
