### ISSUE TITLE
External data resource result, results in continual plan diff

### ISSUE THREAD

**Issue by cyrus-mc** [hashicorp/terraform#27540]
Using External data source (https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source) to generate IAM credentials that are then used as authentication values for the Vault provider.

When on Terraform 0.12.29 the result of the External data source was not shown within the plan/apply step. However after upgrading to Terraform 0.13.6 every plan run shows the result output of the External Data source. As this result contains authentication values used to authenticate to Vault it is somewhat of a security issue.

### Terraform Version

```
› terraform version
Terraform v0.13.6
+ provider registry.terraform.io/-/aws v3.24.1
+ provider registry.terraform.io/-/external v2.0.0
+ provider registry.terraform.io/-/null v3.0.0
+ provider registry.terraform.io/-/random v3.0.1
+ provider registry.terraform.io/-/vault v2.17.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/vault v2.17.0
```

### Terraform Configuration Files

```terraform
  provider "vault" {
    address = format("https://%s", local.vault_addr)

    // we use a self signed certificate
    skip_tls_verify = true

    // use aws auth with specific profile
    auth_login {
      path = "auth/aws/login"

      parameters = {
        # IAM role is XXXRoleName where Vault role is RoleName
        role                                      = lower(trimprefix(local.role_environment, "XXX"))
        iam_http_request_method = data.external.vault_auth.result["iam_http_request_method"]
        iam_request_url                  = data.external.vault_auth.result["iam_request_url"]
        iam_request_body             = data.external.vault_auth.result["iam_request_body"]
        iam_request_headers        = data.external.vault_auth.result["iam_request_headers"]
      }
    }
  }

  data "external" "vault_auth" {
    program = [ "${path.module}/${local.root_relative_path}/sign-request.py", var.environment, local.vault_addr ]
    query = {}
  }
```

When run with Terraform 0.13.6 the plan shows

```
Terraform will perform the following actions:

  # data.external.vault_auth will be read during apply
  # (config refers to values not yet known)
 <= data "external" "vault_auth"  {
        id      = "-"
        program = [
            "./../../../sign-request.py",
            "non-prod",
            "vault",
        ]
      ~ result  = {
            "iam_http_request_method" = "POST"
            "iam_request_body"             = "xxxx"
          ~ "iam_request_headers"       = "xxxxx" -> "yyyyy"
            "iam_request_url"                 = "xxxx"
        }
    }

Plan: 0 to add, 0 to change, 0 to destroy.
```

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

My expectation was the behaviour under Terraform 0.12.x in which the External Data source result was not shown as part of the plan stage.

### Actual Behavior

Using External Data source, the result is shown in the plan.

**Comment by jbardin** [comment]
Hi @cyrus-mc 

Without a complete configuration it's hard to determine why the data source is show up each time. If there are no unknown values in the data source plan, it's likely a side-effect of something else happening in the plan. I suggest trying a sample of your configuration with the current 0.14 release, which significantly improves the planing behavior of data sources. 

Since any details regarding this behavior would only be applicable to 0.13, and 0.13 is no longer under active development, I'm going to close this for now. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
