### ISSUE TITLE
rpc error : code = Unavailable desc = transport is closing 

### ISSUE THREAD

**Issue by ojesvi** [hashicorp/terraform#27546]
I am not able to run terraform plan and apply. 
![image](https://user-images.githubusercontent.com/12774650/105075480-1937b500-5a8a-11eb-927e-48b21e0eb541.png)

terraform --version
Terraform v0.14.2
+ provider registry.terraform.io/akamai/akamai v1.0.0
+ provider registry.terraform.io/alxrem/jsonnet v1.0.1
+ provider registry.terraform.io/hashicorp/local v2.0.0

**Comment by jbardin** [comment]
Hi @ojesvi 

Thanks for reporting this. The stack trace indicated it is a crash in the Akamai provider. You can file an issue in their [project repo](https://github.com/akamai/terraform-provider-akamai/issues)

Thanks!

**Comment by ojesvi** [comment]
Hi @jbardin, 

Thank you for your quick reply.
