### ISSUE TITLE
.deb builds for armhf platform?

### ISSUE THREAD

**Issue by alc6379** [hashicorp/terraform#27548]
Hello, 

Is it possible, or on the roadmap, to include Terraform armhf .deb binaries in the apt repository? I know they're available as a ZIP download, but I wanted to integrate the apt repo into my automation scripts. 

### Use-cases

I have an armhf (Odroid XU4) device I would like to run Terraform from. 

### Attempted Solutions

I can build Terraform myself on this platform from source

### Proposal

Incorporate the armhf build into the build/CI process

**Comment by pkolyvas** [comment]
Hi @alc6379, we don't have any plans to support `armhf` - we recently added `linux_arm64` binaries to our official releases, though they aren't yet supported by our apt/yum repos. 

I think it would be fair to say that we don't intend to support any new 32-bit platforms at this time.
