### ISSUE TITLE
terraform 0.14 output includes unapplied type conversion functions

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform#27551]
### Terraform Version

```
$ terraform version
Terraform v0.14.4
```

### Terraform Configuration Files

```terraform
locals {
  wooo = [1, 2, 3]
  yeah = toset(local.wooo)
  heyy = tolist(local.yeah)
}

output "wooo" {
  value = local.wooo
}

output "yeah" {
  value = local.yeah
}

output "heyy" {
  value = local.heyy
}
```

### Expected Behavior

`terraform output` should apply type conversion functions - the hcl conversion functions aren't useful to most tools we want to use the outputs with.

Example desirable output:
```
 $ terraform-0.13.3 output
heyy = [
  1,
  2,
  3,
]
wooo = [
  1,
  2,
  3,
]
yeah = [
  1,
  2,
  3,
]
```
(For the record - I'm not sure what format `yeah` should have, since it's a set.  But the other two should clearly be lists.)

### Actual Behavior

```$ terraform output
heyy = tolist([
  1,
  2,
  3,
])
wooo = [
  1,
  2,
  3,
]
yeah = toset([
  1,
  2,
  3,
])
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform output`

### Additional Context

terraform 0.13.3 does not display this behavior - sounds related to https://github.com/hashicorp/terraform/issues/27212 released in 0.14.3.

**Comment by pselle** [comment]
Thanks for the report! I confirmed that your reproduction ends in the result you supplied -- I also want to include a note for whoever tackles this that `-json` has the correct types. Snippet:

```
$ terraform output -json
{
  "heyy": {
    "sensitive": false,
    "type": [
      "list",
      "number"
    ],
    "value": [
      1,
      2,
      3
    ]
  },
```

**Comment by jbardin** [comment]
Hello, Thanks for filing the issue!

This is the expected output in the [current release](https://github.com/hashicorp/terraform/blob/f6951a5d8e80389535625fbab7ed030559de3a53/repl/format.go#L68). The literal list syntax in the configuration is technically a tuple, and will be converted to a set or list if needed and possible. There is no syntax to distinguish the types other than the explicit conversion functions. This type of output annotation also applies to the distinction between maps and objects as well.

The syntax of the output is meant to mimic the configuration syntax as closely as possible, and is intended only for human consumption. For machine-readable output there is the `-json` flag as noted above.

Thanks!
