### ISSUE TITLE
Trraform state pull command outputs wrong terraform_version instead of reporting what is actually declared in the state file

### ISSUE THREAD

**Issue by mdpdesign** [hashicorp/terraform#27555]
### Terraform Version

```
Terraform v0.14.4
```

### Terraform Configuration Files

None

### Debug Output

None

### Crash Output

None

### Expected Behavior

Terraform should output unchanged remote/local state and `terraform_version` field to `stdout` as described in the documentation

### Actual Behavior

Terraform should output **unmodified** remote/local state when using `terraform state pull`  command but it injects current terraform version into state.

According to the documentation it should work with local tfstate to be able to use it programatically/in scripts. In our case we actually have a need to determine which terraform version was used to provision resources.

### Steps to Reproduce

1. Use terraform for e.g. version 0.12.29
2. Apply configuration with that terraform version to have the state file present locally
3. Upgrade terraform to version 0.14.4 (**no need to update the configuration**)
4. Try to determine which terraform version was used previously by running `terraform state pull | jq .terraform_version`
5. Command will report the current version 0.14.4 instead of the original from the state file

![image](https://user-images.githubusercontent.com/5243838/105194441-de8d5580-5b39-11eb-8393-8d24915ad808.png)

### Additional Context

None

### References

None

**Comment by alisdair** [comment]
Hi @mdpdesign, thanks for reporting this.

The `state pull` command uses the same state loading path as the rest of Terraform, and as a result always upgrades the state file format and version to the current version before outputting the state. It is not intended as a way to access the raw state without processing it.

I'm surprised to read this line in your report:

> Terraform should output unchanged remote/local state and terraform_version field to stdout as described in the documentation

Can you point out where in the documentation we specify that the `terraform_version` field is supposed to be left unchanged by `terraform state pull`? As you are finding out, that is not how the command works and that would be a bug in the documentation.

[The `state pull` documentation](https://www.terraform.io/docs/commands/state/pull.html) doesn't specify this either way, and unless we decide to change the behaviour, I think we should update that to clarify this behaviour.

**Comment by mdpdesign** [comment]
Hi @alisdair thanks for the reply.

Regarding the documentation or actually that I wrote that this command should return unmodified state as per the docs. There is no explicit statement that this command should return unmodified state - you're right, I should probably use other words for the expected behavior.

From the other hand, in the documentation there is also nothing said that this command modifies the state before outputting it to stdout. So my/our team assumption was clear that this returns unmodified state and you can read the unmodified values from it using for e.g. `jq` - including the `terraform_version`.

Not going into too much details here, we wanted to use the `terraform state pull` command to grab the info about Terraform version used to create infrastructure. This is to have some backward compatibility in our automation that we have.

So maybe the question is, is there any "best practices" way to determine Terraform version from both local and remote state, but not directly try to read the `terraform.tfstate` file?

**Comment by alisdair** [comment]
That's a reasonable assumption to make, given the phrasing of the help output and the docs. Unfortunately because of how Terraform's state loading works at the moment, it would require significant rework to implement this. This enhancement is being tracked in #25866.

In related work, for the 0.14 release we've been [improving the compatibility situation for different versions of Terraform](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-general-availability):

> **Forward compatibility for state files.** Terraform will now support reading and writing all compatible state files, even from future versions of Terraform. This means that users of Terraform 0.14.0 will be able to share state files with future Terraform versions until a new state file format version is needed.

I'm not sure of your use-case for retrieving state file versions, but I hope this change might be helpful for you in the future.

I completely agree that the documentation should be improved, and I'm opening a PR to propose some changes along these lines. Thanks again for reporting!

**Comment by mdpdesign** [comment]
Thanks for making the documentation clearer.
