### ISSUE TITLE
Remote-exec provisioner inline needs set -o errexit for on_failure to function

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#27554]
### Terraform Version

```
Terraform v0.14.4
```

### Terraform Configuration Files

```terraform
provisioner "remote-exec" {
  on_failure = fail # explicit or as default
  inline = [
    "false",
    "true",
   ]
 }
```

### Expected Behavior

Fail & taint on `false`.

### Actual Behavior

Continues to `true` and succeeds.

### Steps to Reproduce

1. `terraform apply`

### Additional Context

I think what's happening is that the `inline` array is joined up and executed as a script, and so, unless `set -o errexit`/`set -e` is specified in the array, it doesn't exit non-zero on early errors, and `on_failure` only looks at the final command in `inline`.

The `inline` argument [is described]() as:
> a list of command strings. They are executed in the order they are provided.

which makes it being a script under the hood seem like an implementation detail, and this behaviour surprising.

```hcl
inline = [
  "set -o errexit",
  "false",
  "true",
]
```

does indeed work as expected, that is, `terraform apply` stops at `false` with:

> Error: error executing "/tmp/terraform_1893939040.sh": Process exited with status 1

(Oh, right, assuming `/tmp/terraform_*.sh`s don't just contain a single command, that confirms it.)

**Comment by OJFord** [comment]
@jbardin Should 'documentation' be interpreted as 'this is intended behaviour, just maybe needs more explanation in docs'?

Maybe `on_failure` could at least be disallowed with `inline`, since it seems to me they can't function sensibly together (with non-default `false` value for the former).

**Comment by jbardin** [comment]
Hi @OJFord, since changing the behavior would be a breaking change, there isn't much we can do other than attempt to more accurately document the current behavior. It's also certainly possible that there are configurations using `inline` and `on_failure` expecting the latter to only apply to the final command, but documenting and providing more examples should help.

**Comment by OJFord** [comment]
Understood.
