### ISSUE TITLE
Applied archive_file data source with sensitive content crashes future plans

### ISSUE THREAD

**Issue by cdb39** [hashicorp/terraform#27565]
### Terraform Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/archive v2.0.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.0.0"
    }
  }
  required_version = ">= 0.14.5"
}

provider "archive" {}

variable "secret" {
  type = string
  sensitive = true
}

data "archive_file" "lambda_zip" {
  type = "zip"
  output_path = "${path.module}/test.zip"

  source {
    content = var.secret
    filename = "secret.txt"
  }
}

output "hash" {
  value = data.archive_file.lambda_zip.output_base64sha256
}
```

### Debug Output

https://gist.github.com/cdb39/43e13da4edf15ecf1c8d6f65f3bce8f6#file-tf_bug_archive_file_trace-log

### Crash Output

https://gist.github.com/cdb39/43e13da4edf15ecf1c8d6f65f3bce8f6#file-tf_bug_archive_file_crash-log

### Expected Behavior

Planning after an apply shouldn't crash.

### Actual Behavior

The plan crashes.

### Steps to Reproduce

1. `terraform init`
2. `TF_VAR_secret=foo terraform apply`
3. `TF_VAR_secret=foo terraform plan`

### Additional Context

None

**Comment by cdb39** [comment]
For anyone else experiencing this issue, my short-term work-around has been to write the templated file to disk using a `local_file` resource, then read the contents back from disk using a `local_file` data source.  This causes terraform to lose information about the sensitivity marking and the `archive_file` then works as expected.

**Comment by alisdair** [comment]
Thanks for reporting this with such a clear reproduction, @cdb39! I can see the same crash in 0.14 and on the main branch.
