### ISSUE TITLE
0.13.6 can't read statefile from 0.14.3

### ISSUE THREAD

**Issue by webbdog28** [hashicorp/terraform#27564]
### Terraform Version

```
Terraform v0.13.6
```

### Expected Behavior

Based on the release notes, Terraform 0.13.6 should be able to read state files created by 0.14.3
### Actual Behavior

```
Initializing modules...
- aks_1 in ../../../Modules/aks
- aks_2 in ../../../Modules/aks
- aks_diag_1 in ../../../Modules/aks-diagnostics
- aks_diag_2 in ../../../Modules/aks-diagnostics

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: state snapshot was created by Terraform v0.14.3, which is newer than current v0.13.6; upgrade to Terraform v0.14.3 or greater to work with this state
##[error]Error: The process '/opt/hostedtoolcache/terraform/0.13.6/x64/terraform' failed with exit code 1
```

### Steps to Reproduce

Run "terraform init" against the remote backend

### Additional Context

Running against a backend stored in Azure blob storage

**Comment by jbardin** [comment]
Hi @webbdog28 

It appears you are attempting to use the state created by 0.14.3 as the storage state for 0.13.6. Unfortunately this is not supported, and only the `terraform_remote_state` data supported reading the state from future releases.

Thanks!
