### ISSUE TITLE
aws_autoscaling_notification tries to manage subscriptions not controlled by Terraform

### ISSUE THREAD

**Issue by johnrengelman** [hashicorp/terraform#2758]
Trying to use Terraform to manage an ASG Notification subscription to an SNS topic that is not managed by Terraform. First apply works but subsequent applies attempt to remove subscriptions that are not managed by terraform (i.e. an ASG that isn't terraform managed and has a subscription to the same SNS topic)

This is the same problem that appears in other areas (such as https://github.com/hashicorp/terraform/issues/2100) where Terraform is attempting to access far too much information about a particular resource...generally in the areas where the Terraform resource is an ephemeral mapping of concrete AWS relationships.

**Comment by phinze** [comment]
Ah yeah - we'll have to see if we can make the code more conservative and filter out the subscription.

So enumerating repro steps:

 * Create ASG, SNS topic, and aws_autoscaling_notification in one TF separate config (these are "not managed by terraform")
 * In another TF config, create a second ASG and an aws_autoscaling_notification referencing by name the same SNS topic

And TF should not touch the notification from the first config, but it does. Sound correct?

**Comment by johnrengelman** [comment]
Yup, that sounds right.

**Comment by johnrengelman** [comment]
Thought I wonder if there is a way to model this kind of concept more concisely where it could be reusable across multiple resources. Something like an explicit "ephemeral resource" or "virtual resource" that would force the implementation to account for this (don't have more concise thoughts on this)
