### ISSUE TITLE
Data source evaluates to null instead of deferring the read to apply time

### ISSUE THREAD

**Issue by bharathkkb** [hashicorp/terraform#27583]
### Terraform Version

```
0.14.5
```

### Terraform Configuration Files

```terraform

resource "google_compute_network" "custom-test" {
  name                    = "test-network"
  auto_create_subnetworks = false
}

module "subnet" {
  source  = "./subnet_module"
  network = google_compute_network.custom-test.id
}

data "google_compute_subnetwork" "my-subnetwork" {
  name   = module.subnet.subnet_name
  region = "us-central1"
}

resource "google_compute_firewall" "test" {
  name      = "test"
  network   = google_compute_network.custom-test.id
  direction = "EGRESS"

  target_tags = ["foo"]
  destination_ranges = [
    data.google_compute_subnetwork.my-subnetwork.ip_cidr_range,
  ]

  allow { protocol = "tcp" }

}
```
#### Module subnet

```terraform

variable "network" {
  
}

resource "google_compute_subnetwork" "custom-subnet" {
  name          = "test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = var.network
  secondary_ip_range {
    range_name    = "tf-test-secondary-range-update1"
    ip_cidr_range = "192.168.10.0/24"
  }
}

output "subnet_name" {
  value = google_compute_subnetwork.custom-subnet.name
}
```
This throws error

```
Error: Null value found in list

  on test.tf line 33, in resource "google_compute_firewall" "intra_egress":
  33:   destination_ranges = [
  34:     data.google_compute_subnetwork.my-subnetwork.ip_cidr_range,
  35:   ]
  
```

If the subnet resource is not wrapped in a module or if data source has `depends_on = [module.subnet]` it works as expected with  0.13.5/0.14.5
```terraform


resource "google_compute_network" "custom-test" {
  name                    = "test-network"
  auto_create_subnetworks = false
}

# module "subnet" {
#   source  = "./subnet_module"
#   network = google_compute_network.custom-test.id
# }

resource "google_compute_subnetwork" "custom-subnet" {
  name          = "test-subnetwork"
  ip_cidr_range = "10.2.0.0/16"
  region        = "us-central1"
  network       = google_compute_network.custom-test.id
  secondary_ip_range {
    range_name    = "tf-test-secondary-range-update1"
    ip_cidr_range = "192.168.10.0/24"
  }
}

data "google_compute_subnetwork" "my-subnetwork" {
  name   = google_compute_subnetwork.custom-subnet.name
  region = "us-central1"
}

resource "google_compute_firewall" "test" {
  name      = "test"
  network   = google_compute_network.custom-test.id
  direction = "EGRESS"

  target_tags = ["foo"]
  destination_ranges = [
    data.google_compute_subnetwork.my-subnetwork.ip_cidr_range,
  ]

  allow { protocol = "tcp" }

}
``` 
Apply is ordered as expected
```
google_compute_network.custom-test: Creating...
google_compute_network.custom-test: Still creating... [10s elapsed]
google_compute_network.custom-test: Creation complete after 12s [id=projects/foo/global/networks/test-network]
google_compute_subnetwork.custom-subnet: Creating...
google_compute_subnetwork.custom-subnet: Still creating... [10s elapsed]
google_compute_subnetwork.custom-subnet: Still creating... [20s elapsed]
google_compute_subnetwork.custom-subnet: Still creating... [30s elapsed]
google_compute_subnetwork.custom-subnet: Creation complete after 32s [id=projects/foo/regions/us-central1/subnetworks/test-subnetwork]
data.google_compute_subnetwork.my-subnetwork: Reading...
data.google_compute_subnetwork.my-subnetwork: Read complete after 1s [id=projects/foo/regions/us-central1/subnetworks/test-subnetwork]
google_compute_firewall.test: Creating...
google_compute_firewall.test: Still creating... [10s elapsed]
google_compute_firewall.test: Creation complete after 11s [id=projects/foo/global/firewalls/test]
```

### Expected Behavior

I expected behavior to be the same - either erroring out in both cases as `google_compute_subnetwork.custom-subnet.name` is not a computed resource or deferring the read to apply time.

### Actual Behavior

With subnet wrapped in a module, it shows 
```
Error: Null value found in list

  on test.tf line 33, in resource "google_compute_firewall" "intra_egress":
  33:   destination_ranges = [
  34:     data.google_compute_subnetwork.my-subnetwork.ip_cidr_range,
  35:   ]
  
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hi @bharathkkb,

It is surprising that the data source returns null for that value during plan, most data sources are expected to return an error if the singular resource they represent is not present. This however would be an issue with the provider, as terraform cannot control what the data source returns. 

The data source is being read during planning because the configuration is fully known at that time, as `module.subnet.subnet_name` is referencing a statically defines attribute. As you found out, using `depends_on` will force the data source to be deferred until apply, resolving the missing value.

In general you should not be using a data source to represent a resource which is being managed within the same configuration. The resource attributes, or even the entire resource itself can be passed explicitly to other parts of the configuration with the need for a data source. If you cannot avoid the usage of the data source, you must either reference a computed attribute to delay evaluation, or add `depends_on`.

Thanks!

**Comment by bharathkkb** [comment]
Hi @jbardin 
Thanks for the quick reply.

> The data source is being read during planning because the configuration is fully known at that time, as module.subnet.subnet_name is referencing a statically defined attribute.

In this case why is there a difference between behavior when the resource is wrapped in a module vs otherwise? 
In the case of the module we have 
```terraform
output "subnet_name" {
  value = google_compute_subnetwork.custom-subnet.name
}
data "google_compute_subnetwork" "my-subnetwork" {
  name   = module.subnet.subnet_name
  region = "us-central1"
}
```
which does not work

vs 

```terraform
resource "google_compute_subnetwork" "custom-subnet" {
...
}

data "google_compute_subnetwork" "my-subnetwork" {
  name   = google_compute_subnetwork.custom-subnet.name
  region = "us-central1"
}
```
which works


> In general you should not be using a data source to represent a resource which is being managed within the same configuration.

Ack yes this is an example I cooked up, in reality what we want to do is use a data source within a [module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/master/examples/safer_cluster). This was working fine in 0.12.x but broke in 0.13.

**Comment by jbardin** [comment]
The fact that it does work when the resource is referenced directly is an unfortunate side effect of the resolution to #25961. Direct references from a data source to a managed resource are treated like `depends_on`, and you should get the same change in behavior if you insert a local value between the data source and the resource. 

It would be much better of course to make this consistent, but the concession to treat the direct reference like `depends_on` was the only way we could see to maintain compatibility with the mis-feature for providers, and not break more complicated configurations that cannot work in that manner.
