### ISSUE TITLE
Separate the remote configuration from the state

### ISSUE THREAD

**Issue by rawkode** [hashicorp/terraform#2759]
I would love to see the state and configuration separated, to allow for multiple people managing infrastructure with an S3 backend:

Using .gitignore to block .tfstate and adding .tfconfig with Terraform always pulling the remote state prior to an operation would provide much better collaborative experience.

```
# .tfconfig
{
    "version": 1,
    "serial": 1,
    "remote": {
        "type": "s3",
        "config": {
            "bucket": "bucket-name",
            "key": "platform"
        }
    }
}
```

**Comment by thegedge** [comment]
#1964 is relevant here, I believe

**Comment by rawkode** [comment]
It is - thanks for pointing that out. My searching skills failed me!

Cheers

**Comment by thegedge** [comment]
There are a lot of issues lingering around here, so no worries. I've skimmed through enough of them to sometimes recall the fact that one exists :)
