### ISSUE TITLE
Conditionally setting module variables

### ISSUE THREAD

**Issue by hmlkao** [hashicorp/terraform#27590]
### Current Terraform Version

```
Terraform v0.13.5
```

### Use-cases

Example uses openstack provider but it can be applied to any module.
```
# modules/node-openstack/main.tf
variable "instance_name" {
  type = string
}

variable "flavor" {
  type = string
  default = "c2m8d20"
}

resource "openstack_compute_instance_v2" "instance" {
  name = var.instance_name
  flavor_name = var.flavor
  ...
}
```

```
# main.tf
locals {
  nodes = [
    {
      instance_name = "node1"
    },
    {
      instance_name = "node2"
      flavor = "c8m16d40"
    },
  ]
}

module "nodes-openstack" {
  source = ./modules/node-openstack

  for_each = local.nodes

  instance_name = each.value.instance_name
  flavor = lookup(each.value, "flavor", null)
}
```
But it override module' `flavor` variable default value with `null`.

### Attempted Solutions

Terraform should use default variable value if null is given.

### Proposal

I've expected that it doesn't fail and module use default value
Otherwise there should be some method how to conditionally set the value.

### References

- #4015

**Comment by jbardin** [comment]
Thanks @hmlkao 

We are tracking this issue in #26499. Unfortunately this would constitute a breaking change rather than a an additional feature, but it is something we're aware of.
