### ISSUE TITLE
Terraform Enterprise: "Bulk cancel" option for plans

### ISSUE THREAD

**Issue by secureoptions** [hashicorp/terraform#27607]
### Current Terraform Version
```
v0.13.5
```

### Use-cases

We have a single Github repo mapped to multiple TFE workspaces. Each workspace is mapped to an unique AWS account, etc. Sometimes unintended workspaces get a long queue of plans when we are iterating in one specific workspace. This queue builds up because we have sentinel policies that must be manually overridden in some cases.

### Attempted Solutions

We understand that you can control TFE workspaces based on Github branch and working directory, but it isn't feasible in every use case. 

### Proposal

It would be nice to have a "bulk cancel" option just to cleanup when we see this arbitrary queue.

**Comment by danieldreier** [comment]
Hello! It looks like you’ve reported an issue around using terraform on Terraform Enterprise. This issue tracker is for the Open Source Terraform Core, and this particular issue is something in the Terraform Enterprise codebase that we can't help with. The best way to get support to file a support ticket. Please open a support ticket at https://support.hashicorp.com/ or email support@hashicorp.com using your work email and reference this GitHub issue.
