### ISSUE TITLE
Provider dependency on destroy

### ISSUE THREAD

**Issue by patuzov** [hashicorp/terraform#27601]
I'm deploying a Kubernetes Cluster (AKS) and create a namespace in it using the Kubernetes provider.

The provider configuration seems to _lazy-load_, as during the initial creation, the cluster is correctly created first and only then the namespace. Everything as expected.

But as soon as I change a setting for the cluster that leads to re-create, during `terraform refresh` the namespaces resource somehow loses the _connection_ to the cluster:

`Error: Get "http://localhost/api/v1/namespaces/demo": dial tcp 127.0.0.1:80: connect: connection refused`

It seems like the provider configuration is being _cleared_, but I can't explain why this happens during refresh.

Might be related to #2430. But how does it get the correct order on first run?

### Terraform Version
```
v0.14.0
```

### Terraform Configuration Files

```terraform
provider "azurerm" {
  features {}
}

provider "kubernetes" {
  host                   = azurerm_kubernetes_cluster.demo.kube_config.0.host
  client_certificate     = base64decode(azurerm_kubernetes_cluster.demo.kube_config.0.client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.demo.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.demo.kube_config.0.cluster_ca_certificate)
}

resource "azurerm_resource_group" "demo" {
  name     = "demo"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "demo" {
  name                = "demo"
  location            = azurerm_resource_group.demo.location
  resource_group_name = azurerm_resource_group.demo.name
  dns_prefix          = "demo"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "kubernetes_namespace" "demo" {
  metadata {
    name = "demo"
  }

  # explicit dependency doesn't help
  # depends_on = [ azurerm_kubernetes_cluster.demo ] 
}
```

### Debug Output
```
...
kubernetes_namespace.demo: Refreshing state... [id=demo]

Error: Get "http://localhost/api/v1/namespaces/demo": dial tcp 127.0.0.1:80: connect: connection refused
```

### Expected Behavior
First the namespace is deleted, then the cluster re-created.

### Actual Behavior
Errors on `terraform refresh`

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Change cluster name from _demo_ to _demo2_
4. `terraform apply`

### References
- #2430

**Comment by jbardin** [comment]
Hi @patuzov 

When the aws resources are removed, then the kubernetes provider cannot be fully configured during planning, and will fail to read any existing kubernetes resources.

The recommended pattern here is to use multiple configurations to manage the resources, as outlined in the [kubernetes provider docs](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs)

```
The most reliable way to configure the Kubernetes provider is to ensure that the cluster itself and the Kubernetes provider resources can be managed with separate apply operations. Data-sources can be used to convey values between the two stages as needed.
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. 

Thanks
