### ISSUE TITLE
Output shows values from previous applies when using for loop with data source

### ISSUE THREAD

**Issue by DannyArr** [hashicorp/terraform#27617]
<img width="285" alt="TerraformShowsDataFromPreviousState" src="https://user-images.githubusercontent.com/16082818/106148993-a5746700-6171-11eb-9871-6ddf751e353a.png">
### Terraform Version
Terraform v0.14.5

### Terraform Configuration Files
```terraform
locals {

    ### COLLECTION A ###
    collection = {
        dudeSet1 = {
            name = "Bill"
        }
    }

    ## COLLECTION B ###
    # collection = {
    #     dudeSet2 = {
    #        name = "Ted"
    #    }
    # }
}

### DATA SOURCE BLOCK ###
data "null_data_source" "get_dude" {
    for_each = local.collection

    inputs = {
        dude = each.value["name"]
    }
}

# This should only output the dude from the data source for this run and NOT include data from the previous run.
output output_dude {
    value = {for dudeSetKey in keys(data.null_data_source.get_dude) : dudeSetKey => data.null_data_source.get_dude[dudeSetKey].outputs.dude}
}
```

### Debug Output
https://gist.github.com/DannyArr/3431834b3080890683f6bbbc935344f3

### Expected Behavior
Output should show the results of the data source as per the inputs provided.

### Actual Behavior
Output includes data from previous runs. i.e. data that is not included in any variables or locals. This then disapears on a subsequent run making the results inconsistent.

### Steps to Reproduce
Apply will need to be run 3 times to illustrate the issue. The first time with the local collection A included, and collection B commented out. The second time with Collection B included and Collection A commented out. Then rerun previous config again.

1. `terraform init`
2. `terraform apply`
3. Note the output: It should have "Bill"
4. Comment out the local "Collection A"
5. Remove comments for the local "Collection B"
6. `terraform apply`
7. Note the output: It should have both "Bill" and "Ted"
8. `terraform apply`
9. Note the output: It should now only have "Ted"

NOTE: this only seems to occur when using a for_each loop in a data source. 

### Additional Context
None

### References
None

**Comment by jbardin** [comment]
Thanks for the complete example @DannyArr!
The data source instance which is removed from the config was inadvertently left in the state for evaluation during plan.
