### ISSUE TITLE
Updating required provider from an old address to a new address terraform keeps using the old provider

### ISSUE THREAD

**Issue by sonic1981** [hashicorp/terraform#27627]
### Terraform Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.8.0
```

### Terraform Configuration Files

initial terraform config:

```terraform
terraform {
  required_providers {
    mongodbatlas = {
      source = "terraform-providers/mongodbatlas"
      version = "= 0.8.0"
    }
  }
}
```
followed by an update to:
```terraform
terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "= 0.8.0"
    }
  }
  required_version = ">= 0.14"
}
```

### Debug Output
Running terraform with the provider set as `terraform-providers/mongodbatlas` produces the error:

```hcl
Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/terraform-providers/mongodbatlas:
- For users on Terraform 0.13 or greater, this provider has moved to
mongodb/mongodbatlas. Please update your sourc
```

So I update my provider config to use `mongodb/mongodbatlas`. But I still get the error above. Running `terraform providers` shows that terraform is still using `terraform-providers/mongodbatlas` not `mongodb/mongodbatlas`:

```hcl
Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/azurerm] 2.44.0
├── provider[registry.terraform.io/hashicorp/random]
├── module.takeapi
│   └── provider[registry.terraform.io/hashicorp/azurerm]
├── module.compare
│   └── provider[registry.terraform.io/hashicorp/azurerm]
├── module.mongo
│   └── provider[registry.terraform.io/mongodb/mongodbatlas] 0.8.0
├── module.process
│   └── provider[registry.terraform.io/hashicorp/azurerm]
├── module.dashboards
│   ├── provider[registry.terraform.io/hashicorp/azurerm]
│   └── provider[registry.terraform.io/hashicorp/template]
├── module.dl
│   └── provider[registry.terraform.io/hashicorp/azurerm]
├── module.sche
│   └── provider[registry.terraform.io/hashicorp/azurerm]
├── module.take
│   └── provider[registry.terraform.io/hashicorp/azurerm]
├── module.kv
│   └── provider[registry.terraform.io/hashicorp/azurerm]
└── module.list
    └── provider[registry.terraform.io/hashicorp/azurerm]

Providers required by state:

    provider[registry.terraform.io/hashicorp/azurerm]

    provider[registry.terraform.io/hashicorp/random]

    provider[registry.terraform.io/hashicorp/template]

    provider[registry.terraform.io/terraform-providers/mongodbatlas]
```

If I delete the tfstate file and start again with the new provider config then the correct provider is used. But this isn't practical for all my production instances. Reading the [Moving resources](https://www.terraform.io/docs/cli/state/move.html) I would expect terraform to update this property or delete my resource and recreate it:

> This is seamless when changing a resource's attributes, but Terraform will lose track of a resource if you change its name, move it to a different module, or **change its provider**.
> 
> Usually that's fine: **Terraform will destroy the old resource**, replace it with a new one (using the new resource address), and update any resources that rely on its attributes.

### Expected Behavior
Terraform should update to the new provider and stop erroring that an old provider is being used.

### Actual Behavior
Terraform continues to use the old out of date provider on the old address.

### Steps to Reproduce

1. create a terrform config with a `required_providers` block set to use `terraform-providers/mongodbatlas`
2. run `terraform init`
3. run `terraform providers`
4. note provider being used for mongo
5. update the terraform config to now use `mongodb/mongodbatlas`
6. run `terraform init`
7. run `terraform providers`

Terraform is still using the `registry.terraform.io/terraform-providers/mongodbatlas` despite the config being updated to `mongodb/mongodbatlas`.

### References
- https://github.com/mongodb/terraform-provider-mongodbatlas/issues/396

**Comment by jbardin** [comment]
Hi @sonic1981 

As you correctly discovered, the state will still contain references to the old provider. Terraform cannot know that the new provider and the old provider can provider the same resources, and therefor will require both providers to replace the existing resources. If you want to specifically change the provider, you can use the [`terraform state replace-provider`](https://www.terraform.io/docs/cli/commands/state/replace-provider.html) command. 


We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by sonic1981** [comment]
@jbardin We use a CI pipeline to run our terraform, so for example I don't have access to the production state, only the pipeline does. So I can't directly run this command on the state. So I have no way to configure this without running that command directly?

**Comment by jbardin** [comment]
That is correct, we currently don't have a programatic interface for manipulating state through configuration.
It is a feature we are considering, and are tracking in #19354. Similar to the upgrade commands that need to be run when terraform versions are changed, some commands will need to occasionally be run against the existing state or configuration.
