### ISSUE TITLE
Helper Directory

### ISSUE THREAD

**Issue by datagrime** [hashicorp/terraform#27623]
What happened to the helper directory. Removing this prevents cf-terraforming from installing. 

`root@:/usr/local/go/bin# go get -u github.com/cloudflare/cf-terraforming/...
package github.com/cloudflare/cf-terraforming/cmd/cf-terraforming: cannot find package "github.com/hashicorp/terraform/helper/hashcode" in any of:
        /usr/local/go/src/github.com/hashicorp/terraform/helper/hashcode (from $GOROOT)
        /root/go/src/github.com/hashicorp/terraform/helper/hashcode (from $GOPATH)`

**Comment by jbardin** [comment]
Hi @datagrime,

The terraform packages are not meant to be imported as a library, and we are in the process of removing exported code, and legacy code in general.

The `helper` packages remaining public use is in v1 of the legacy plugin sdk, which you can find in the [terraform-plugin-sdk repo](https://github.com/hashicorp/terraform-plugin-sdk/).  You should be able to get all the helper packages from version 1 from there.

Thanks!
