### ISSUE TITLE
terraform commands additional values

### ISSUE THREAD

**Issue by AndriiOmelianenko** [hashicorp/terraform#2764]
In new terraform version to use terraform commands like `plan` or `apply` I should input all this info:

```
$ terraform version
Terraform v0.6.0

$ terraform plan
provider.openstack.api_key
  Enter a value:

provider.openstack.api_key
  Enter a value:

provider.openstack.endpoint_type
  Enter a value:

provider.openstack.endpoint_type
  Enter a value:

provider.openstack.password
  Enter a value: pass

provider.openstack.password
  Enter a value: pass

provider.openstack.user_name
  Enter a value: user

provider.openstack.user_name
  Enter a value: user
```
I have few questions:

1. Should every field be duplicated?
2. Should password field show inputed password? It's not very secure imo.

Thanks

**Comment by mitchellh** [comment]
1. What does your config look like? There are cases where we do duplicate.

2. That is a feature we don't support yet but would be interesting, feel free to open an issue.

**Comment by AndriiOmelianenko** [comment]
1. what do your mean by config? I didn't set up any config files. Just downloaded new version of terraform, and sourced few variables by `source openstack.sh` to have access to openstack environment from `nova`, `neutron` etc.
There is few variables, such as
```
OS_AUTH_URL
OS_TENANT_ID
OS_TENANT_NAME
OS_USERNAME
OS_PASSWORD
```
btw, terraform v0.5.3 doen't require input of all those fields from my first message.

 2, cool, I'll be waiting for this feature, thanks.

**Comment by manuelmazzuola** [comment]
Same issue here
I have to input `api_key` and `input_endpoint`

```
+ terraform plan
provider.openstack.api_key
  Enter a value: 

provider.openstack.endpoint_type
  Enter a value: 

Refreshing Terraform state prior to plan...
```

`Terraform v0.6.0-dev (cddd54c3deef11e73e10c0fd91814c1ed57ee74f)`

**Comment by manuelmazzuola** [comment]
Probably fixed in 0.6.1 https://github.com/hashicorp/terraform/pull/2626

**Comment by AndriiOmelianenko** [comment]
issue didn't appeared in 0.6.1
Thanks guys, you're doing great job.

**Comment by catsby** [comment]
Thanks for following up!
