### ISSUE TITLE
Terraform backend s3 with AWS SSO login fails

### ISSUE THREAD

**Issue by CostelLupoaie** [hashicorp/terraform#27650]
### Terraform Version
```
Terraform v0.14.5
```
running on BigSur.

### Terraform Configuration Files
backend.tf
```backend
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.26"
    }
  }

  backend "s3" {
    bucket = "xxx-bucket"
    key    = "dns/terraform.tfstate"
    region = "eu-central-1"
    profile = "xxx-prod"
  }
}
```

main.tf
```main
provider "aws" {
  region  = "eu-central-1"
  profile = "dns"
}
```

### Debug Output
```terraform_init
2021/02/01 16:40:35 [INFO] Terraform version: 0.14.5
2021/02/01 16:40:35 [INFO] Go runtime version: go1.15.6
2021/02/01 16:40:35 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2021/02/01 16:40:35 [DEBUG] Attempting to open CLI config file: /Users/<username>/.terraformrc
2021/02/01 16:40:35 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/02/01 16:40:35 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021/02/01 16:40:35 [DEBUG] ignoring non-existing provider search directory /Users/<username>/.terraform.d/plugins
2021/02/01 16:40:35 [DEBUG] ignoring non-existing provider search directory /Users/<username>/Library/Application Support/io.terraform/plugins
2021/02/01 16:40:35 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2021/02/01 16:40:35 [INFO] CLI command args: []string{"init"}

Initializing the backend...
2021/02/01 16:40:35 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 2159496475
2021/02/01 16:40:35 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2021/02/01 16:40:35 [DEBUG] New state was assigned lineage "bad17307-b80f-0a32-6f0d-5f85c51862e5"
2021/02/01 16:40:35 [TRACE] Meta.Backend: moving from default local state only to "s3" backend
2021/02/01 16:40:35 [INFO] Attempting to use session-derived credentials

Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.

Please see https://www.terraform.io/docs/backends/types/s3.html
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### Expected Behavior
When running terraform init s3 backend should be created successfully.

### Actual Behavior
When using AWS SSO "terraform init" fails (see log above)

### Steps to Reproduce
1. setup terraform
2. login to aws cli using sso (aws sso login)
3. create terraform configuration as above
4. run "terraform init"

### Additional Context
I have also tested with classic profile and it's ok.
So my two profiles look like this:
sso login
``` aws sso login
[profile xxx-prod]
sso_start_url = https://xxxxxxx.awsapps.com/start
sso_region = eu-central-1
sso_account_id = xxxx
sso_role_name = xxxx
region = eu-central-1
```
"classic" profile
``` aws clasic profile
[profile no_sso_creds]
aws_access_key_id=xxx
aws_secret_access_key=xxx
aws_session_token=xxx
region=eu-central-1
```
First configuration fails, the classic one seems to be running ok. Both profiles are defined in the default aws configuration paths.

I have to mention that I am correctly logged in SSO. I have also manually tested the upload to the s3 bucket and it works successfully. Also if I run with local state we see no issues with update.

### References
- #26995

**Comment by bflad** [comment]
Hi @CostelLupoaie 👋  Thank you for raising this. AWS SSO cached credential support has not been merged into the Terraform S3 Backend yet. Please follow https://github.com/hashicorp/terraform/pull/27620 for updates.

**Comment by CostelLupoaie** [comment]
Thank you. Will keep and eye out for the release.

**Comment by iJebus** [comment]
I have basically the same config as provided above and I'm seeing the same issue; anyone else or have I derped somewhere? Relevant tf/provider versions:

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.26.0
```

**Comment by iJebus** [comment]
Yep, I derped somewhere. There were `terraform_remote_state` resources using s3 backends, which also needed a profile passed in. The error message wasn't specific about which s3 backend and I didn't think of these, oops.
