### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by jzhou3** [hashicorp/terraform#27657]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jzhou3** [comment]
Terraform v0.12.24
+ provider.azurerm v2.33.0
[crash.log](https://github.com/hashicorp/terraform/files/5908502/crash.log)

**Comment by jbardin** [comment]
Hi @jzhou3 

This appears to be a problem with the azurerm provider, however I cannot transfer the issue with no information in the issue template. Please file the issue in their [project repository](https://github.com/terraform-providers/terraform-provider-azurerm/), along with the requested information.

Thanks!
