### ISSUE TITLE
[Feature] Add wait command for locked state file

### ISSUE THREAD

**Issue by abhi1693** [hashicorp/terraform#27667]
### Current Terraform Version

```
v0.14.5
```

### Use-cases

There are several people in my team that are using the remote workspace. We only use it to store states. However, we are constantly running into issues due to `locked state file`.

### Proposal

Can a `wait` command be added to terraform that would keep on waiting for the lock to be released? There can also be a timeout defined for this to ultimately fail the execution.

This would immensely help in reducing multiple runs and would also help in queueing up automated runs.

### References

NA

**Comment by jbardin** [comment]
Hi @abhi1693 

This option already exists in the form of the [`-lock-timeout`](https://www.terraform.io/docs/cli/commands/plan.html#lock-timeout-0s) flag. 

Thanks!
