### ISSUE TITLE
Inline azurerm_key_vault_access_policy requires optional application_id and certificate_permissions for tf.json HCL

### ISSUE THREAD

**Issue by ilons** [hashicorp/terraform#27673]
Trying to run the official example Azure Key Vault (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault), I encounter an issue where terraform would say that `application_id` and `certificate_permissions` are required for `access_policy` objects. 
Looking at the documentation, neither of them should be required.

Since I run terraform against the JSON HCL, I then tried to run against the regular TF HCL, which worked.

I initially filed this issue against (provider azurerm)[https://github.com/terraform-providers/terraform-provider-azurerm/], but they closed it and asked me to open it upstream.

### Terraform Version
```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.45.1
```

### Terraform Configuration Files
JSON:
```json
{
  "provider": {
    "azurerm": {
      "features": {
        "key_vault": {
          "purge_soft_delete_on_destroy": true
        }
      }
    }
  },
  "data": {
    "azurerm_client_config": {
      "current": {}
    }
  },
  "resource": {
    "azurerm_resource_group": {
      "example": {
        "name": "example-resources",
        "location": "West Europe"
      }
    },
    "azurerm_key_vault": {
      "example": {
        "name": "examplekeyvault",
        "location": "${azurerm_resource_group.example.location}",
        "resource_group_name": "${azurerm_resource_group.example.name}",
        "enabled_for_disk_encryption": true,
        "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
        "soft_delete_retention_days": 7,
        "purge_protection_enabled": false,
        "sku_name": "standard",
        "access_policy": [
          {
            "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
            "object_id": "${data.azurerm_client_config.current.object_id}",
            "key_permissions": [
              "get"
            ],
            "secret_permissions": [
              "get"
            ],
            "storage_permissions": [
              "get"
            ]
          }
        ]
      }
    }
  }
}

```
TF:
```terraform
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_key_vault" "example" {
  name                        = "examplekeyvault"
  location                    = azurerm_resource_group.example.location
  resource_group_name         = azurerm_resource_group.example.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false

  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "get",
    ]

    secret_permissions = [
      "get",
    ]

    storage_permissions = [
      "get",
    ]
  }
}
```

### Debug Output
Output for `terraform plan`, using;
JSON: https://gist.github.com/ilons/b4d89ac3d78c84d8e109f399e97e0703
TF: https://gist.github.com/ilons/e7c3bff72073764c8718fed1dcaaa7c6

### Expected Behaviour
A plan to create the key vault are generated

### Actual Behaviour
An error (`Incorrect attribute value type`) are shown, complaining that `application_id` and `certificate_permissions` are required for the `access_policy` object.

### Steps to Reproduce
0. Insert the JSON config in a file named test.tf.json
1. `terraform init`
2. `terraform apply`

### References
* Resource documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault
* JSON HCL documentation: https://www.terraform.io/docs/language/syntax/json.html
* Closed provider issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/10445

**Comment by ilons** [comment]
And just to confirm that the syntax in the JSON HCL are correct, I tried adding the access policy separately instead of inline, which worked as expected:

{
  "provider": {
    "azurerm": {
      "features": {
        "key_vault": {
          "purge_soft_delete_on_destroy": true
        }
      }
    }
  },
  "data": {
    "azurerm_client_config": {
      "current": {}
    }
  },
  "resource": {
    "azurerm_resource_group": {
      "example": {
        "name": "example-resources",
        "location": "West Europe"
      }
    },
    "azurerm_key_vault": {
      "example": {
        "name": "examplekeyvault",
        "location": "${azurerm_resource_group.example.location}",
        "resource_group_name": "${azurerm_resource_group.example.name}",
        "enabled_for_disk_encryption": true,
        "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
        "soft_delete_retention_days": 7,
        "purge_protection_enabled": false,
        "sku_name": "standard"
      }
    },
    "azurerm_key_vault_access_policy": {
      "example": {
        "key_vault_id": "${azurerm_key_vault.example.id}",
        "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
        "object_id": "${data.azurerm_client_config.current.object_id}",
        "key_permissions": [
          "get"
        ],
        "secret_permissions": [
          "get"
        ],
        "storage_permissions": [
          "get"
        ]
      }
    }
  }
}

**Comment by apparentlymart** [comment]
Hi @ilons,

Although the documentation doesn't mention it, I can see in the provider code that this particular argument is using the legacy [Attributes as Blocks mode](https://www.terraform.io/docs/language/attr-as-blocks.html), which has [some differences in behavior for JSON](https://www.terraform.io/docs/language/attr-as-blocks.html#in-json-syntax) because the JSON syntax is ambiguous, and so (unlike native HCL syntax) it' can't use your choice of syntax to understand which of the two interpretations you meant.

While the behavior of this backward-compatibility mechanism is admittedly confusing, it is unfortunately working as intended here because the provider has opted in to this behavior. To make it pass validation, set the two arguments explicitly to `null`, like this:

```json
        "access_policy": [
          {
            "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
            "object_id": "${data.azurerm_client_config.current.object_id}",
            "key_permissions": [
              "get"
            ],
            "secret_permissions": [
              "get"
            ],
            "storage_permissions": [
              "get"
            ],
            "application_id": null,
            "certificate_permissions": null
          }
        ]
```

If the provider is able to make a future breaking change which opts out of this legacy behavior then that would make this argument behave as you expected, but until that time you'll need to explicitly set these to `null` when you use the JSON syntax.

**Comment by ilons** [comment]
> Hi @ilons,
> 
> Although the documentation doesn't mention it, I can see in the provider code that this particular argument is using the legacy [Attributes as Blocks mode](https://www.terraform.io/docs/language/attr-as-blocks.html), which has [some differences in behavior for JSON](https://www.terraform.io/docs/language/attr-as-blocks.html#in-json-syntax) because the JSON syntax is ambiguous, and so (unlike native HCL syntax) it' can't use your choice of syntax to understand which of the two interpretations you meant.
> 
> While the behavior of this backward-compatibility mechanism is admittedly confusing, it is unfortunately working as intended here because the provider has opted in to this special behavior. To make it pass validation, set the two arguments explicitly to `null`, like this:
> 
> ```json
>         "access_policy": [
>           {
>             "tenant_id": "${data.azurerm_client_config.current.tenant_id}",
>             "object_id": "${data.azurerm_client_config.current.object_id}",
>             "key_permissions": [
>               "get"
>             ],
>             "secret_permissions": [
>               "get"
>             ],
>             "storage_permissions": [
>               "get"
>             ],
>             "application_id": null,
>             "certificate_permissions": null
>           }
>         ]
> ```
> 
> If the provider is able to make a future breaking change which opts out of this legacy behavior then that would make this argument behave as you expected, but until that time you'll need to explicitly set these to `null` when you use the JSON syntax.

Thank you for the explanation.
