### ISSUE TITLE
Unable to change disk type to SSD in GKE terraform

### ISSUE THREAD

**Issue by rajeevsharmaCS** [hashicorp/terraform#27684]
Hi Team,

I’m unable to change disk type to SSD in GKE terraform. Even after using disk_type under node config for node pool as below, the terraform doesn’t change it to SSD.

disk_type = "pd-ssd”

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
