### ISSUE TITLE
Terraform AWS IAM User and multiple inline policies error (size limit 2048) based on order of resource creation

### ISSUE THREAD

**Issue by navalprabhakar** [hashicorp/terraform#27685]
Hi Admin,

I used terraform "0.14.5".

Issue: When I create or update AWS user with multiple policies with using "depends_on" allowing policies to be added to IAM user only when all policies are created- works successfully. But without depends_on, the below error is encountered.

Also, suppose we make changes to say 1 of 2 policies (as in example tf file below ) and run terraform apply, then the AWS validation error is triggered that max inline policy size reached although each individual policy is less than max size limit.

To avoid this error, I ensure that user-policy objects are created only once all links are created/recreated.
--
This works first time, if we update one policy json, gives size error, if we delete user policies on aws console and recreate, again that works. If we remove depends_on condition, then it fails even the first time applying/creating:

```
resource "aws_iam_user" "app-ci-cd-user" {
  name = "cicd-user"
}

resource "aws_iam_policy" "app-policy-first" {
  name = "policy-first"
  policy = data.aws_iam_policy_document.app-ci-cd-user-policy-first.json
}

resource "aws_iam_policy" "app-policy-second" {
  name = "policy-second"
  policy = data.aws_iam_policy_document.app-ci-cd-user-policy-second.json
}

resource "aws_iam_user_policy" "app-ci-cd-user-policy-first" {
  depends_on = [
    aws_iam_policy.app-policy-first,
    aws_iam_policy.app-policy-second
  ]
  name = "cicd-user-policy-first"
  user = aws_iam_user.app-ci-cd-user.name
  policy = aws_iam_policy.app-policy-first.policy
}

resource "aws_iam_user_policy" "app-ci-cd-user-policy-second" {
  depends_on = [
    aws_iam_policy.app-policy-first,
    aws_iam_policy.app-policy-second
  ]
  name = "cicd-user-policy-second"
  user = aws_iam_user.app-ci-cd-user.name
  policy = aws_iam_policy.app-policy-second.policy
}

```   
---------------------------------------------------
> Error: Error putting IAM user policy "cicd-user-policy-first": LimitExceeded: Maximum policy size of 2048 bytes exceeded for user "cicd-user"
>         status code: 409, request id: 9f4c8f74-b04e-4847-86a3-a68a7f29d43e
> 
--------------------------------------------------

Please advise. Thanks.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by navalprabhakar** [comment]
Thanks for your immediate pointing to correct forum.
