### ISSUE TITLE
0.13.5 cannot import resources in nested modules when count value for any module is variable

### ISSUE THREAD

**Issue by duganth-va** [hashicorp/terraform#27687]
https://github.com/hashicorp/terraform/issues/25816 looks like is still relevant. 

### Terraform Version
0.13.5
### Terraform Configuration Files
n/a

### Debug Output
n/a

### Crash Output
none
### Expected Behavior
resources is imported

### Actual Behavior
Error: Invalid count argument

### Steps to Reproduce
terraform import

### References
https://github.com/hashicorp/terraform/issues/25816
-->

**Comment by jbardin** [comment]
Hi @duganth-va,

The specific example in the reference issue appears to work as expected. Can you create an example here demonstrating the problem you're having using the current version of terraform? (0.14.6 at the moment)

Thanks!

**Comment by duganth-va** [comment]
Hey @jbardin 
This was on 0.13.5. We ended up using the work around in the linked issue (remove offending files for import then put them back) and wanted to communicate it back to the community in case others had the same problem. I'm ok if you'd like to close this issue but happy to try and reproduce at some point in the future if it's of interest. Thanks!

**Comment by duganth-va** [comment]
@jbardin I was able to set a quick test to reproduce this on 0.13.5 (and 0.13.6). Using the same environment I then switched to 0.14.6 and the issue was no longer there. As we are not able to move to 0.14.6 we will just continue to use the work around for further imports. Thanks

**Comment by jbardin** [comment]
Thanks for confirming @duganth-va! Since we wouldn't be able to fix this in 0.13 anyway, we can close this issue for now.
