### ISSUE TITLE
Bastion configuration does not draw a resource dependency

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#2768]
Had a scenario where my bastion host failed to launch because of an unrelated problem, but a host that needed the bastion IP for its provisioner happily launched and tried to connect without a bastion config.

Instead, any host with a bastion config that references another resource should gain a dependency on that resource so it doesn't create until after the bastion is healthy.

**Comment by mitchellh** [comment]
Hm, having trouble repro-ing this, I see the graph edge properly. Do you have a minimal repro case?

**Comment by phinze** [comment]
I'll come up with something concrete, but sketching from memory it was across a module boundary.

```
module "bastion" -> resource "aws_instance" -> output "bastion_ip"
input "bastion_ip" -> module "nat" -> resource "aws_instance" (provider that needs bastion_ip)
```

**Comment by mitchellh** [comment]
Going to close this @phinze unless we can get back to it.
