### ISSUE TITLE
regression jsonencode behaviour in 0.14.5 different then in 0.13.5

### ISSUE THREAD

**Issue by alexeyauslender** [hashicorp/terraform#27693]
### Terraform Version
Terraform v0.14.5

```
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior
jsonencode({"hello"="world"})
{"hello":"world"}

### Actual Behavior

jsonencode({"hello"="world"})
"{\\"hello\\":\\"world\\"}"

### Steps to Reproduce

jsonencode({"hello"="world"})

**Comment by mildwonkey** [comment]
Hi @alexeyauslender ,
Thank you for reporting this, and I'm sorry you are experiencing this unexpected behavior. 

Can you tell me a bit more about where you are calling this function from, and what problem it is causing? We have made some changes to the `terraform console` output format; if that is where you are seeing this, I can flag this as a documentation issue. 

This may or may not be helpful, but you can get the expected output  by using `terraform output -raw`: 

```hcl
// main.tf
output "jsonencode" {
  value = jsonencode({"hello"="world"})
}
```

```bash
terraform output -raw jsonencode
{"hello":"world"}
```

**Comment by alexeyauslender** [comment]
Thank you @mildwonkey that helped.
