### ISSUE TITLE
Unable to delete an entire module

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#2770]
- using s3 for state
- all my modules are local paths.
- when I run `terraform show` I see a bunch of modules that are no longer used (and have 0 resources in them)

$ terraform plan --refresh=false
No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.

[ comment out module ]

$ terraform plan --refresh=false
No changes. Infrastructure is up-to-date. This means that Terraform
could not detect any differences between your configuration and
the real physical resources that exist. As a result, Terraform
doesn't need to do anything.

Also. At the top level I have 3 modules. When i comment one of them out, terraform says "no changes". When I comment out a second one, it hangs. Output with TF_LOG=1 [here](https://gist.github.com/ryanking/05740917e77e9b9cbeb1).

**Comment by mitchellh** [comment]
Ah, so just to clarify: your modules have no active resources, but deleting them from the config keeps them in the state? That is an edge case I could believe, but just checking.

**Comment by ryanking** [comment]
I have both situations currently

1. I have some modules with 0 active resources and not references in any
.tf files

2. I have modules with resources in them (and more modules) and when I
comment the top level module out it does not trigger a planned destroy.

One note about #2- the the module that doesn't trigger a delete only
contains other modules, which then contain resources. Perhaps there's a
non-recursive check that should be recursive?

-ryan

**Comment by ryanking** [comment]
That was it.

Here's what I did.

1. Added a resource inside the outer module.
2. applied that change
3. commented whole outer module out
4. run plan and now the deletes show up

So it appears that terraform doesn't detect a deleted module when that
module only contains modules.

-ryan

**Comment by mitchellh** [comment]
Thanks... that will certainly help me repro.

![Turtles](http://www.nasuni.com/writable/images/Blog_Images/turtles-1-1-1.jpg)

**Comment by mitchellh** [comment]
Reproduced! Working on this now.

**Comment by mitchellh** [comment]
Got a fix in the attached PR!
