### ISSUE TITLE
provider/cloudflare - terraform deduces hashicorp/cloudflare for a community provider even with an explicit source directive

### ISSUE THREAD

**Issue by labsvisual** [hashicorp/terraform#27701]
### Terraform Version
```
Terraform v0.14.5
```

### Terraform Configuration Files
```terraform
terraform {
    required_version = ">= 0.14.0"

    backend "remote" {
        // Backend configuration
    }

    required_providers {
        cloudflare = {
            source = "registry.terraform.io/cloudflare/cloudflare"
            version = "2.18.0"
        }

        aws = {
            source = "hashicorp/aws"
            version = "3.26.0"
        }
    }
}

provider "aws" {
    region = "us-east-2"
    access_key = var.aws_access_key_id
    secret_key = var.aws_secret_access_key
}

provider "cloudflare" {
    api_token = var.cloudflare_api_token
}
```

Elsewhere, I have a [`cloudflare_zones` data source](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/zones) in the form of:

```hcl
data "cloudflare_zones" "domain" {
    filter {
        name = "<Domain>"
    }
}
```

### Expected Behavior
Terraform apply and plan steps should not result in an error.

### Actual Behavior
On running `terraform init` without the `cloudflare` data source, the initialization/plan succeed. However, when the `data` block is added, I am greeted with the following:

```
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Finding latest version of hashicorp/cloudflare...
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/tls from the dependency lock file
- Reusing previous version of cloudflare/cloudflare from the dependency lock file
- Installing cloudflare/cloudflare v2.18.0...
- Installed cloudflare/cloudflare v2.18.0 (signed by a HashiCorp partner, key ID DE413CEC881C3283)
- Installing hashicorp/aws v3.26.0...
- Installed hashicorp/aws v3.26.0 (signed by HashiCorp)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)
- Installing hashicorp/tls v3.0.0...
- Installed hashicorp/tls v3.0.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/cloudflare: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/cloudflare

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

Did you intend to use cloudflare/cloudflare? If so, you must specify that
source address in each module which requires that provider. To see which
modules are currently depending on hashicorp/cloudflare, run the following
command:
    terraform providers
```

### Steps to Reproduce
Copy and paste the configuration file and run `terraform plan` or `terraform init`.

### References
Even after explicitly specifying the registry/namespace, Terraform deduces `hashicorp/cloudflare` for some reason. I saw another issue [here](https://github.com/cloudflare/terraform-provider-cloudflare/issues/920) which mentions the same problem but I can't find/use the resolution posted.

**Comment by vince-franco** [comment]
I am having the exact same issue with the Digital Ocean Provider.  

In a child module used to define a DigitalOcean k8s cluster I receive the same error as the user above.  The only way I've been able to get the code to work is by explicitly declaring the providers within the child modules that use resources associated with the modules, but that breaks the depends_on meta argument with modules, which I need to use.

Until it's fixed and if you don't need the depends_on meta argument, explicitly declare your provider in your child module using the required_providers block.

Side note: I've never used a Terraform version < 15

My Root module main.tf looks like this:

`terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = ">= 2.5.0"
    }

  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "my-org"

    workspaces {
      name = "my-workspace"
    }
  }
}

provider "digitalocean" {
  # Provider is configured using Terraform cloud env variables:
  # DIGITALOCEAN_ACCESS_TOKEN
  # SPACES_ACCESS_KEY_ID
  # SPACES_SECRET_ACCESS_KEY
}

module "doks_setup" {
  source = "./modules/doks_setup"
  doks_cluster_name = var.doks_cluster_name_remote
  doks_region = var.doks_region_remote
  doks_version_prefix = var.doks_version_prefix_remote
  doks_node_pool_name = var.doks_node_pool_name_remote
  doks_node_size = var.doks_node_size_remote
  doks_min_nodes = var.doks_min_nodes_remote
  doks_max_nodes = var.doks_max_nodes_remote
}`

doks_setup child module looks like this:

'# Define Kubernetes Major and Minor release to stay at
data "digitalocean_kubernetes_versions" "doks_version" {
  version_prefix = var.doks_version_prefix
}


# Define doks cluster
resource "digitalocean_kubernetes_cluster" "my_doks_cluster" {
  name         = var.doks_cluster_name
  region       = var.doks_region
  auto_upgrade = true
  version      = data.digitalocean_kubernetes_versions.doks_version.latest_version

  node_pool {
    name       = var.doks_node_pool_name
    size       = var.doks_node_size
    auto_scale = true
    min_nodes  = var.doks_min_nodes
    max_nodes  = var.doks_max_nodes
  }
}'

**Comment by vince-franco** [comment]
I am having the exact same issue with the Digital Ocean Provider.  

In a child module used to define a DigitalOcean k8s cluster I receive the same error as the user above.  The only way I've been able to get the code to work is by explicitly declaring the providers within the child modules that use resources associated with the modules, but that breaks the depends_on meta argument with modules, which I need to use.

Until it's fixed and if you don't need the depends_on meta argument, explicitly declare your provider in your child module using the required_providers block.

Side note: I've never used a Terraform version < 15

non-working root module main.tf
```
terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = ">= 2.5.0"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = ">= 2.0.2"
    }
    helm = {
      source  = "hashicorp/helm"
      version = ">= 2.0.2"
    }
  }

  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "my-org"

    workspaces {
      name = "my-workspace"
    }
  }
}

provider "digitalocean" {
  # Provider is configured using Terraform cloud env variables:
  # DIGITALOCEAN_ACCESS_TOKEN
  # SPACES_ACCESS_KEY_ID
  # SPACES_SECRET_ACCESS_KEY
}

module "doks_setup" {
  source              = "./modules/doks_setup"
  doks_cluster_name   = var.doks_cluster_name_remote
  doks_region         = var.doks_region_remote
  doks_version_prefix = var.doks_version_prefix_remote
  doks_node_pool_name = var.doks_node_pool_name_remote
  doks_node_size      = var.doks_node_size_remote
  doks_min_nodes      = var.doks_min_nodes_remote
  doks_max_nodes      = var.doks_max_nodes_remote
}
```

non-working child module main.tf
```
# Define Kubernetes Major and Minor release to stay at
data "digitalocean_kubernetes_versions" "doks_version" {
  version_prefix = var.doks_version_prefix
}


# Define k8s cluster
resource "digitalocean_kubernetes_cluster" "k8s_cluster" {
  name         = var.doks_cluster_name
  region       = var.doks_region
  auto_upgrade = true
  version      = data.digitalocean_kubernetes_versions.doks_version.latest_version

  node_pool {
    name       = var.doks_node_pool_name
    size       = var.doks_node_size
    auto_scale = true
    min_nodes  = var.doks_min_nodes
    max_nodes  = var.doks_max_nodes
  }
}
```

**Comment by labsvisual** [comment]
## Update 07/02/2021
This bug also exists for any other provider initialised as mentioned in the issue. I tried this with the [`acme`](https://registry.terraform.io/providers/vancluever/acme/latest/docs) provider and got the same error.

**Comment by mildwonkey** [comment]
Hi @labsvisual ,

The fact that terraform also installs `cloudflare/cloudflare` indicates that terraform thinks you need both providers. Usually that happens if your configuration includes a module that uses `cloudflare` but does not have a `required_providers` block for that provider.

Can run the `terraform providers` command to see where terraform is getting `hashicorp/cloudflare` from, and share the output here? If it's a module, the module needs to be updated to include the `source` for `cloudflare`.

This situation also can arise during an upgrade from terraform v0.12 to v0.13 (or higher). If that's the case, you would see that terraform is finding `hashicorp/cloudflare` from your state, not the configuration. In that case, you can use [`terraform state replace-provider`](https://www.terraform.io/docs/cli/commands/state/replace-provider.html) to replace `hashicorp/cloudflare` with `cloudflare/cloudflare`.

**Comment by vince-franco** [comment]
Yo @mildwonkey,

Terraform isn't trying to install cloudflare/cloudflare or digitalocean/digitalocean in the child module it's trying to install hashicorp/cloudflare (you can see that in @labsvisual's init) or hashicorp/digitalocean (in my case) this is a problem with how terraform child modules inherit their provider from the root modules.

I have the same issue and have never used a version of terraform <14.  I also deleted all terraform meta data from my project directory, cloned it to another directory and reinstalled the terraform binary using the latest version.  This isn't an upgrade issue.

```
Providers required by configuration:
.
├── provider[registry.terraform.io/digitalocean/digitalocean] >= 2.5.0
├── provider[registry.terraform.io/hashicorp/kubernetes] >= 2.0.2
├── provider[registry.terraform.io/hashicorp/helm] >= 2.0.2
├── module.doks_setup
│   └── provider[registry.terraform.io/digitalocean/digitalocean] >= 2.5.0
└── module.jenkins
    ├── provider[registry.terraform.io/hashicorp/kubernetes]
    └── provider[registry.terraform.io/hashicorp/digitalocean]
```

**Comment by mildwonkey** [comment]
Hi @vince-franco ,

Your output shows that terraform sees `hashicorp/digitalocean` in the module `doks_setup`. *Every module* which references a non-Hashicorp provider needs a `required_providers` block specifying the providers' source. The module needs to be upgraded to work with terraform v0.13+.

**Comment by vince-franco** [comment]
Hey @mildwonkey

So I did as you suggested, I exported my k8s cluster host, token, and cluster_ca_certificates as sensitive output variables in my doks_setup child module and I'm now getting:

```
terraform plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://app.terraform.io/app/odij/odij-spacedock/runs/run-tRsHbiu5TcPDMM11

Waiting for the plan to start...

Terraform v0.14.6
Configuring remote state backend...
Initializing Terraform configuration...

Error: Unable to find cluster with name: my-doks-cluster
```

I seem to be in a chicken and egg scenario where because I have to explicitly declare the required providers in the child module I can't use the depends_on meta argument?  I think the meta argument would solve my issue correct?

When I add it though I get:
```
terraform init
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Module does not support depends_on

  on main.tf line 47, in module "jenkins":
  47:     source                      = "./modules/jenkins"

Module "jenkins" cannot be used with depends_on because it contains a nested
provider configuration for "digitalocean", at
../modules/jenkins/main.tf:12,10-24.

This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.


Error: Module does not support depends_on

  on main.tf line 47, in module "jenkins":
  47:     source                      = "./modules/jenkins"

Module "jenkins" cannot be used with depends_on because it contains a nested
provider configuration for "kubernetes", at
../modules/jenkins/main.tf:19,10-22.

This module can be made compatible with depends_on by changing it to receive
all of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
```
But I can't make the child module get its provider info from the root module because of the way that terraform enforces non-HashiCorp module definitions.  I feel there should be a way to allow a child module to call a provider that depends on data from another child module without splitting this into two separate workspaces and lacing it together with a script.

If I'm missing something obvious here I apologize in advance.

**Comment by mildwonkey** [comment]
Ah, I am sorry for the confusion. The only change I suggested was to add a `required_providers` block to the module but (as you've just discovered!) there are some additional complications depending on how each module configures the providers or if you are passing a provider into the module itself. 


> But I can't make the child module get its provider info from the root module because of the way that terraform enforces non-HashiCorp module definitions.

It is possible to do this! The syntax is frequently confusing but with some modifications your module(s) should work just fine.

There's a whole page of documentation on handling providers inside modules which might help (but, again, confusing!): https://www.terraform.io/docs/language/modules/develop/providers.html

At this point we're discussing a question that isn't related to this github issue directly @vince-franco , so I suggest you open a new issue or better yet post it to the community forum. You'll need to share your configuration, including the module(s) itself, though in this case the "terraform" and "provider" blocks from the module will probably be enough.

**Comment by mildwonkey** [comment]
(alas, I cannot tell our bot that I am waiting for a response from the original poster, so I will re-label this)

**Comment by labsvisual** [comment]
@mildwonkey - I ran `terraform providers` before filing this issue and it showed that the module `hashicorp/cloudflare` was referenced from the module which mentioned the data source (`cloudflare_zones`); it went away the moment I removed the block.

However, here is the output:

```
Providers required by configuration:
.
├── provider[registry.terraform.io/cloudflare/cloudflare] 2.18.0
├── provider[registry.terraform.io/hashicorp/aws] 3.26.0
├── module.bastion
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.gitlab
│   ├── provider[registry.terraform.io/hashicorp/aws]
│   ├── provider[registry.terraform.io/hashicorp/time]
│   ├── provider[registry.terraform.io/hashicorp/null]
│   └── provider[registry.terraform.io/hashicorp/cloudflare]
├── module.key_pairs
│   ├── provider[registry.terraform.io/hashicorp/tls]
│   └── provider[registry.terraform.io/hashicorp/aws]
└── module.vpc
    └── provider[registry.terraform.io/hashicorp/aws]

Providers required by state:

    provider[registry.terraform.io/hashicorp/aws]

    provider[registry.terraform.io/hashicorp/null]

    provider[registry.terraform.io/hashicorp/time]

    provider[registry.terraform.io/hashicorp/tls]
```

Here, `module.gitlab` is the module which uses the `cloudflare/cloudflare` provider.

---

The issue is solved when I add a `terraform.tf` file in the module using the provider (in this case `module.gitlab` and add the `required_providers` block as in the root `terraform.tf` file. However, the documentation mentions:

> Although provider configurations are shared between modules, each module must declare its own provider requirements, so that Terraform can ensure that there is a single version of the provider that is compatible with all modules in the configuration and to specify the source address that serves as the global (module-agnostic) identifier for a provider.

with no explicit reference pointing me towards the fact that I need to do this on a per-module basis which is directly opposite of what the documentation says.

**Comment by mildwonkey** [comment]
There is definitely much room for improvement in our documentation around modules and providers. Would you mind sharing which page of our documentation you found that in? We can re-label this is a documentation issue. 

I can point to places where it is documented, but those don't really matter if the page that you are actually working from doesn't make it clear, or at least include a link to the more detailed [documentation](https://www.terraform.io/docs/language/providers/requirements.html#requiring-providers).

**Comment by labsvisual** [comment]
@mildwonkey  - [this](https://www.terraform.io/docs/language/modules/develop/providers.html) is the piece I am talking about. I saw it referenced in a few pieces of docs as well as some issues (I'll go through my history and try to backlink it here).

**Comment by mildwonkey** [comment]
Thanks @labsvisual - and it's ok, you don't need to dig for more examples unless you want to. I really didn't mean to ask you to dig through all of our documentation for us :)

**Comment by labsvisual** [comment]
@mildwonkey - not a worry at all; I have been riding on top of Terraform for a while. This is the least I can do for the community. I'd try opening a PR for this as and when I get some time over the weekend?

**Comment by iwoonder** [comment]
Hi terraform community,

I have the same issue with terraform 0.14.7 (mac), the problem is exact same as you describe above, in the process of parsing the problem, I notices that after terraform init with this provider.tf tries to find in terraform registry provider **registry.terraform.io/hashicorp/digital** but it doesn't exist in registry.

**terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = ">= 2.5.0"
    }
    aws = {
      source = "hashicorp/aws"
      version = "3.30.0"
    }
  }
}**

@teamterraform please fix this issue 
![Screenshot 2021-03-03 at 22 54 18](https://user-images.githubusercontent.com/59572761/109877753-aff3b600-7c73-11eb-8394-af4aa809d209.png)

**Comment by mildwonkey** [comment]
Hi @iwoonder ,
Please follow the instructions in [this previous comment](https://github.com/hashicorp/terraform/issues/27701#issuecomment-775173646) to see where terraform is seeing the hashicorp/digital provider.

**Comment by iwoonder** [comment]
Hi @mildwonkey, thanks for recommendation,

the problem appears only when i use both `aws 3.30.0` and `digital-ocean 2.5.1` provider, i tested also  many scenarios to understand why terraform inicalize  in after `terrafrom init` registry provider name `hashicorp/digital` and fail after.



Also i tried [previous comment](https://github.com/hashicorp/terraform/issues/27701#issuecomment-775173646) with command `terraform state replace-provider hashicorp/digital digitalocean/digitalocean` but terraform actually can't find state for replacing because after `Initializing provider plugins...`as you can see in ([sceenshot](https://user-images.githubusercontent.com/59572761/109877753-aff3b600-7c73-11eb-8394-af4aa809d209.png)
) state file is not changes.

Also as you can see in the  ([sceenshot](https://user-images.githubusercontent.com/59572761/109877753-aff3b600-7c73-11eb-8394-af4aa809d209.png) i think terraform tries to connect  to https://registry.terraform.io/providers/hashicorp/digital wich is actually could not be found.

**Comment by mildwonkey** [comment]
Hi @iwoonder, 
Are you able to run the  `terraform providers` command? That will show you where terraform is getting those (incorrect) providers from.

**Comment by iwoonder** [comment]
Sure, this is the output 

`
Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/digital]
├── provider[registry.terraform.io/hashicorp/aws] 3.31.0
└── provider[registry.terraform.io/digitalocean/digitalocean] 2.5.1`

**Comment by mildwonkey** [comment]
Thanks @iwoonder! So that shows us that terraform sees a provider named "digital" in your configuration which doesn't have a required_providers block. Is it possible that you have a misnamed resource, like `digital_kubernetes_cluster` instead of `digitalocean_kubernetes_cluster`, for example? Or a `provider "digital"` block?
