### ISSUE TITLE
Allow data resource that lookup sets of items to return empty sets.

### ISSUE THREAD

**Issue by bcsgh** [hashicorp/terraform#27712]
### Current Terraform Version
0.13, though I have reason to suspect the issue also exist in 0.14.

### Use-cases

I need to create a resource `for_each` of some other thing. Things that exists outside TF's control.

```
data "some_things" "lookup" {
  ...
}

resource "other_things" "make" {
  for_each = data.some_things.lookup.ids

  ...
  build_from_thing = each.key
}
```

Right now this is made more complicated when the possibility exist that there may be zero of those things as all (or most) data rules that lookup sets of things issue an error when they find nothing.

Note that, as far as what is being specified and created, this use case is no different than any other use of `for_each` that could end up taking an empty set. Thus the argument about "dynamic decision-making" (see references) does not apply.

### Attempted Solutions

The general workaround is to use a wider query that is assured to always return _something_ and lookup enough about each of those results to manually filter that in terraform. Besides being much more complex and requiring many more data requests, this has many other issues that I shouldn't need to go into.

### Proposal

`data` resources returning a list of matching results should be allowed to (opt into?) return an empty list.

### References

- This is a related to https://github.com/hashicorp/terraform/issues/16380 but specifically for the case where a class of resources in being acted on rather than a specific resource being queried for.

**Comment by jbardin** [comment]
Hi @bcsgh 

Terraform itself does not limit what a data source deems appropriate to return for a given configuration. It is up to the provider to implement the data source in such a way that it is valid to return no results from the given inputs. Many data source employ a pattern of requiring a data source representing a singular resource to have a single result, while plural data sources have the option of returning 0 or more values. This is purely convention however, and it is up to the provider to decide which is appropriate for the type of data structure being referenced.

Thanks!

**Comment by bcsgh** [comment]
In that case I'll file an FR for the primary offender I have to deal with: https://github.com/hashicorp/terraform-provider-aws/issues/17540
