### ISSUE TITLE
"Error: Failed to query available provider packages" with "hashicorp/iam" after adding any IAM data

### ISSUE THREAD

**Issue by mattk-ce** [hashicorp/terraform#27714]
### Terraform Version
0.14.5

### Terraform Configuration Files
```
provider "aws" {
  region  = "us-east-1"
}

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

data "iam_policy" "ssm_managed_instance_core" {
  name = "AmazonSSMManagedInstanceCore"
}
```

### Debug Output
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/iam:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/iam

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

### Steps to Reproduce
1. `terraform init`

### Additional Context
Seems like it could be related to [27701](https://github.com/hashicorp/terraform/issues/27701) or [27641](https://github.com/hashicorp/terraform/issues/27641)

### References
- #27641 
- #27701

**Comment by alisdair** [comment]
I think the issue here is that you mean to write [`data "aws_iam_policy"`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy). When you wrote `data "iam_policy"`, Terraform interpreted that as a resource on the `iam` provider (which as you found out, doesn't exist).

Closing as this does not appear to be a Terraform bug.

**Comment by mattk-ce** [comment]
🤦‍♂️ I've been writing Terraform for _years_ and this is the first time I've done something like this.  But even with those years of experience, I was unwittingly led down a rabbit hole from a pretty misleading error message.  Can we get better error messages, please?
