### ISSUE TITLE
Have a set of standard global flags for providers and resources

### ISSUE THREAD

**Issue by tibers** [hashicorp/terraform#27720]
### Current Terraform Version

```
1.13.x
```

### Use-cases

https://github.com/hashicorp/terraform-provider-kubernetes/pull/1112 <- something like this PR is a good example of needing a pattern of globally honored flags in resources or providers. 

### Attempted Solutions

Have one TF run which handles internet things, and then a second TF run which handles onprem things, and they load each others buckets so they know about each others resources. Basically this leads to order-of-operations hell.

### Proposal

I propose we all smoosh our brains together and come up with a set of globally honored flags which always work the same way. Current annoyances are: `timeout`, `retries`, and `proxy`. These would be SDK additions where a provider or resource would be expected to honor them.

If set in a provider block, I would expect all resources which that provider is responsible for to inherit these settings. If set in a resource block, I would expect them to override the defaults. 

It looks like at one point it was mentioned as a **may** sort of thing, but then that idea vanished: https://www.terraform.io/docs/configuration-0-11/resources.html#timeouts 

It never seems to have been formalized as a best-practice or design guidance.

The use cases are the same:
* My thing I'm terraforming is on prem and I have to cross a proxy to get to it from the cloud
* My thing I'm terraforming is in a special network tenancy in the cloud which only accepts traffic from a bastion host
* I need a proxy to get to things on the internet, but I _cannot_ use this proxy to get to things on prem.
* My resource takes an inordinate amount of time to deploy, I need to customize it
* My resource is misbehaved and has something like circular dependencies, I need to force several retries before giving up

**Comment by jbardin** [comment]
Hi @tibers 

Thanks for the proposal. Unfortunately terraform cannot add any attributes to resources without causing a breaking change across all providers (nor do all these attribute necessarily make sense across all providers and resources). Providers themselves can already implement this type of behavior internally if they desire, however the legacy SDK does not provide a built-in mechanism for doing so. If you are interested in creating a proposal for the SDK, that project is located [here](https://github.com/hashicorp/terraform-plugin-sdk).

Thanks!
