### ISSUE TITLE
Unexpected Crash - most probably related while deleting s3 bucket - terraform detroy

### ISSUE THREAD

**Issue by dshanke** [hashicorp/terraform#27729]
@
[crash.log](https://github.com/hashicorp/terraform/files/5955804/crash.log)
[crash.log](https://github.com/hashicorp/terraform/files/5955805/crash.log)

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by mildwonkey** [comment]
Hi @dshanke ! I'm sorry you've experienced this behavior. Can you please update this issue, filling out the complete issue template? We will need to see your configuration, or better yet a simpler reproduction case, in order to look into this problem.

**Comment by mildwonkey** [comment]
There's been no response, so I am going to close this. Please open a new issue if necessary.
