### ISSUE TITLE
Variables & terraform_remote_state

### ISSUE THREAD

**Issue by rawkode** [hashicorp/terraform#2773]
We already have our "core" infrastructure created on AWS, so I tried to create a "dummy" terraform configuration and pushed it to Atlas.

```
variable "vpc-id" {
    default = "vpc-id"
}
```

Pushing this to Atlas sets the variable, which is great. However, this variable isn't then available in other Terraform templates when using terraform_remote_state (Looks like only outputs are available)

Are there any strong feelings towards not opening up variables, or has this just not been needed to date?

**Comment by mitchellh** [comment]
Thanks for the question. There is a very strong feeling towards not opening up variables. The point of remote state is to access only outputs. Consider Terraform modules functions, and outputs are the return values. You can work around this by just setting an output to the variable value.

**Comment by rawkode** [comment]
Thanks for the prompt response! Still getting to grips with these new tools, so I appreciate the feedback,

Cheers - I'll try what you've suggested.
