### ISSUE TITLE
Does not use argument's default value when null is passed

### ISSUE THREAD

**Issue by stigok** [hashicorp/terraform#27730]
### Terraform Version

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

### Terraform Configuration Files

https://github.com/stigok/terraform-use-default-value-when-null

### Debug Output

https://raw.githubusercontent.com/stigok/terraform-use-default-value-when-null/main/tfdebug.log

### Expected Behavior

The `modules/test` module should use the module's default value for `my_var` when it is passed a `null` value, as [stated in the Terraform syntax documentation](https://www.terraform.io/docs/language/expressions/types.html):
> null: a value that represents absence or omission. If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory. null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met. 

### Actual Behavior

`my_var` in the resource definition is not ignored as if it was ommited, but passed as an acutal `null` value, which in this example breaks string interpolation.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

Linux 64bit

### References

Somewhat related to https://github.com/hashicorp/terraform/issues/5471

**Comment by jbardin** [comment]
Thanks @stigok 

We're tracking this in #24142
