### ISSUE TITLE
Log warning for unmatched configuration providers

### ISSUE THREAD

**Issue by knutwannheden** [hashicorp/terraform#27757]
### Current Terraform Version

```
0.14.6
```

### Use-cases
When using a module the user can specify providers to be used by the module using aliases and which the module has declared proxy configuration blocks for. In case a provider is specified for which no matching (by alias) proxy configuration block exists in the module, it would be helpful if Terraform would log a warning. This can happen in a number of situations:

* there is a typo in the alias on the consumer side
* the provider alias on the module side was changed or the provider proxy was even removed
* the module inadvertently changed the proxy configuration block in a regular configuration block (e.g. by adding an empty features block)

### Proposal
As described under Use-cases I think it would make sense if the `terraform` command could log warnings when the configured providers don't align with the module's provider proxy configurations.

**Comment by jbardin** [comment]
Thanks @knutwannheden!
Closed by #27739
