### ISSUE TITLE
SNS Subscription Pending Confirmation Errors

### ISSUE THREAD

**Issue by zollie** [hashicorp/terraform#2776]
Maybe this is corruption in my AWS account? If so it seems real easy to do.

SNS Subscriptions return a pending ARN before accepted as documented [here](http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html#SendMessageToHttp.subscribe)

When using terraform to apply and/or destroy SNS subscriptions I often get 

* Error unsubscribing from SNS topic: InvalidParameter: Invalid parameter: SubscriptionArn Reason: pending confirmation does not start with arn
	status code: 400, request id: [cdc87910-6665-5996-8171-37334f899735]

And the apply/destroy stops. 

I cannot find any SNS subscriptions pending or otherwise using the AWS Console and CLI, yet I still get these errors.

**Comment by catsby** [comment]
Hey @zollie – can you help me understand how to reproduce this with some steps, or better a configuration file that reproduces it? If so please be sure to omit any secrets or passwords.

**Comment by zollie** [comment]
I think it's because the SNS resource expects the endpoint to auto-confirm the subscription response with code. If your using an endpoint that requires a manual human response, you can get a bunch of subscription requests in the pending state where their ARN is 'Pending Confirmation'.  You can see them on the Console (SNS->Subscriptions), but I cannot find them through the AWS API. 

So to repro try to subscribe with an SMS protocol endpoint like your phone number. 

I think this is why Email subscriptions are not allowed as well.

I have this fixed locally. Email also works with this fix. The acceptance test fails as my profile is setup for us-east-1 but the acceptance test is running in us-west. 

Here is the [diff](https://github.com/hashicorp/terraform/compare/master...zollie:b-sns-pending-confirm-errors)

**Comment by coen-hyde** [comment]
I've just bumped into this issue.

**Comment by ruudk** [comment]
I have the same issue

**Comment by Remz-Jay** [comment]
Same issue. Trying to do a `protocol = https`  subscription to a topic that auto-confirms the subscription (PagerDuty, see: https://www.pagerduty.com/docs/guides/aws-cloudwatch-integration-guide/ ). 

The resource is applied and the subscription shows with ARN in the AWS console (so it's not pending at all), but in the meantime, every subsequent plan/apply fails with:

```
Error refreshing state: 1 error(s) occurred:

* aws_sns_topic_subscription.cda-alarms-pagerduty: InvalidParameter: Invalid parameter: SubscriptionArn Reason: pending confirmation does not start with arn
        status code: 400, request id: 57243ac6-8fba-5f4c-bb01-741cb0ffbd0f
```
This happens in both 0.6.7 and 0.6.8

**Comment by comozo** [comment]
I have the same issue

**Comment by catsby** [comment]
Hello –

I opened #4639 to address this. Unfortunately, it addresses it by restricting the use of the SNS Topic Subscription resource to just Lambda, Applications, and SQS. The other protocols require an external confirmation that doesn't sit well with Terraform's workflow. Worse, there are no IDs or ARNs returned in the initial create that would allow us to apply a confirmation code on a second run; we get no ID or anything in return to the `Subscribe` API call; an ARN is only returned if it was auto-accepted. 

I'm going to close this for now. Sorry we weren't able to address this in a better way, hopefully in the future we'll have more capabilities to do so.

Thanks!

**Comment by jmstone617** [comment]
Just an FYI the docs on `master` are updated, but not on Terraform.io
