### ISSUE TITLE
Expose PARALLELISM parameter as environment variable

### ISSUE THREAD

**Issue by spuder** [hashicorp/terraform#27765]
# Feature Request

Terraform should support environment variables like `TF_parallelism` to supplement command line arguments. 

### Current mechanism

`terraform apply -parallelism=1`

### Purposed mechanism
```
export TF_parallelism=1
terraform apply
```

Terraform currently supports a variety of parameters and environment variables. 

## Parameters

https://www.terraform.io/docs/cli/commands/apply.html

```
-backup=path
-compact-warnings
-lock=true
-lock-timeout=0s
....
-parallelism=n
....
```

## Environment Variables

https://www.terraform.io/docs/cli/config/environment-variables.html
https://github.com/hashicorp/terraform/blob/4d65cbdedf425b0a5a90737100b265e207002c85/website/docs/cli/config/environment-variables.html.md

```
TF_LOG
TF_LOG_PATH
TF_INPUT
TF_VAR_name
TF_CLI_ARGS
TF_CLI_ARGS_name
TF_DATA_DIR
TF_WORKSPACE
TF_IN_AUTOMATION
TF_REGISTRY_CLIENT_TIMEOUT
TF_CLI_CONFIG_FILE
TF_IGNORE
```

# Justification

Some plugins for terraform require parallelism be reduced down from the default of 10 to 1. (Specifically jfrog/artifactory). 

It is currently not possible to set the parallelism to a value other than 10 when using an automated pipeline (such as with gitlabs native terraform support) 

## Possible workarounds

1. Fork the [official gitlab terraform docker container](
https://gitlab.com/gitlab-org/terraform-images/-/blob/master/Dockerfile) and change parallelism

## Resources

https://github.com/atlassian/terraform-provider-artifactory/issues/75#issuecomment-647049225

https://docs.gitlab.com/ee/user/infrastructure/terraform_state.html

https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml

https://gitlab.com/gitlab-org/terraform-images/-/blob/master/Dockerfile

**Comment by apparentlymart** [comment]
Hi @spuder! Thanks for sharing this use-case.

The environment variables of the form `TF_CLI_ARGS_name` are designed to allow you to set any command line option using an environment variable, so I think what you want to achieve here is already possible with an invocation like this:

```
export TF_CLI_ARGS_apply="-parallelism=1"
terraform apply
```

Could you give that a try at let me know if it meets your need? Thanks!

**Comment by spuder** [comment]
Thank you for the quick reply. I overlooked `TF_CLI_ARGS_apply` which does appear to do precisely what I need. Thank you.
