### ISSUE TITLE
Terraform import should import or show config

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform#27766]
Currently `terraform import` imports a resource into the tfstate, but does not show the resource config that would lead to 0 planned changes if applied.

It should print this info, and it should not be necessary to have a resource block for the name and required params. Importing into the state should be optional, most often I just want to determine what HCL2 will reproduce the existing resource so I can duplicate it, in those cases I have to use terraform state rm many times.

**Comment by jbardin** [comment]
Thanks @schollii,

We have many ideas being considered for import improvements.
What is described here is not directly achievable, but since #26364 is in-line with the current thinking about import issues, I'm going to combine this as UX to take into consideration when designing the final solution.
