### ISSUE TITLE
AD Provider WinRM Issue

### ISSUE THREAD

**Issue by Lucero7919** [hashicorp/terraform#27775]
I have two VMs in azure in two different (peered) Vnets. I'm trying to use the AD Provider:

https://registry.terraform.io/providers/hashicorp/ad/latest/docs

The documentation is very light on how the WinRM should be configured and what possible options there are. However, I can successfully connect to WinRM on the remote PC (which is running Windows Server 2019 Active Directory) successfully using PowerShell so I know all the routing and ports are correct. I can PS Remote too.

The AD Provider WinRM config I have is:

provider "ad" {
    winrm_hostname      = local.virtual_machine_fqdn
    winrm_username      = local.domain.name\\local.domain.username
    winrm_password      = local.domain.password
    winrm_insecure        = true
    winrm_proto            = "https"
    winrm_port              = 5986
}

When run, Terraform exits with the following error:

Error: powershell command failed with exit code 1
stdout: 
stderr: 
error: http response error: 401 - invalid content type

Does anyone have any idea why Terraform can't communicate using that config block?

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
