### ISSUE TITLE
Error: filename, s3_* or image_uri attributes must be set while creating lambda function

### ISSUE THREAD

**Issue by ciciya** [hashicorp/terraform#27774]
Here is my code:

provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_role" "iam_for_lambda" {
  name = "terraformTestLambaRole"

  assume_role_policy = <<-EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }terr
  ]
}
EOF
}

resource "aws_lambda_function" "lambda0000" {
  function_name    = "${var.Customer}-${var.Environment}-terraformTestLamba-${var.Stage}"
  role             = "aws_iam_role.iam_for_lambda.arn"
  runtime          = "nodejs12.x"
  handler          = "index.handler"
  source_code_hash = "data.archive_file.lambda_zip.output_base64sha256"
  filename         = "lambda_function.zip"
  environment {
    variables = {
      foo = "bar"
    }
  }
}

data "archive_file" "lambda_zip" {
  type        = "zip"
  source_file = "index.js"
  output_path = "lambda_function.zip"
}

**Comment by Chainshark** [comment]
You should follow the guidelines to report a bug defined when creating one. This is also not a bug but a variable you are missing.

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
