### ISSUE TITLE
Plan reports unexpected change of subnet_id in azurerm_app_service_virtual_network_swift_connection 

### ISSUE THREAD

**Issue by thecodetinker** [hashicorp/terraform#27803]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.6
azurerm v2.47.0

### Affected Resource(s)

* `azurerm_app_service_virtual_network_swift_connection`

### Terraform Configuration Files

```hcl

resource "azurerm_app_service" "main" {
  ... properties
}

data "azurerm_resource_group" "main" {
  name = var.rg_name
}

data "azurerm_subnet" "vnet_integration" {
  name                 = var.vnet_integration_subnet_name
  virtual_network_name = var.vnet_name
  resource_group_name  = data.azurerm_resource_group.main.name
}

resource "azurerm_app_service_virtual_network_swift_connection" "administrator_vnet_integration" {
  app_service_id = azurerm_app_service.main.id
  subnet_id      = data.azurerm_subnet.vnet_integration.id
}
```

### Expected Behaviour

No changes have been made to the terraform files here, so plan should not have picked up any changes. 

### Actual Behaviour

The terraform plan indicates that a change of subnet_id is required, although the two IDs listed by the plan are in fact identical.

```
  # azurerm_app_service_virtual_network_swift_connection.vnet_integration will be updated in-place
  ~ resource "azurerm_app_service_virtual_network_swift_connection" "vnet_integration" {
        app_service_id = "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Web/sites/sandbox-site"
        id             = "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Web/sites/sandbox-site/config/virtualNetwork"
      ~ subnet_id      = "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Network/virtualNetworks/VNET-SANDBOX/subnets/vnet-integration-app" -> "/subscriptions/2183.../resourceGroups/SANDBOX/providers/Microsoft.Network/virtualNetworks/VNET-SANDBOX/subnets/vnet-integration-app"
    }
```

### Steps to Reproduce

1. Create an `azurerm_app_service` and an `azurerm_subnet` resource
2. Note that here the `azurerm_subnet` resource and resource group are created by an upstream TF project, and brought in here via Datasources. I'm not sure if that is relevant.
3. Create an `azurerm_app_service_virtual_network_swift_connection` resource to inject the App Service into the vNet
4. `terraform apply` to create the resources
5. Run `terraform plan` to verify

No changes are expected, but the plan indicates the `subnet_id` needs to change (yet displays the two IDs as identical).

I know the above TF is not complete but hopefully is enough to go on. Let me know if you need any further details.

### References

* #10105 is a very different resource, but exhibited similar behaviour. Probably unrelated, but I was glad when that got fixed :)

**Comment by thecodetinker** [comment]
Argh I'm sorry I've opened this in the wrong repository. I'll raise again in the azurerm one.

**Comment by tombuildsstuff** [comment]
Reopening since this appears to be a Core issue

**Comment by thecodetinker** [comment]
Thanks @tombuildsstuff - just to confirm I have tried with Terraform 0.14.7 and get exactly the same problem - plan still reports a change the subnet_id.

**Comment by jbardin** [comment]
Hi @thecodetinker,

It is quite odd that terraform would show a change between 2 identical strings. I assume the `SANDBOX` and `VNET-SANDBOX` are placeholders for your own account information -- are you certain that there is no change at all to hose fields as well? 

On the surface this appears to be similar to https://github.com/terraform-providers/terraform-provider-azurerm/issues/10809. Terraform itself cannot determine what changes are semantically significant, and it is up to the configuration to be cased correctly, or the provider to prevent unintended changes from being written to the configuration.

**Comment by jbardin** [comment]
I'm going to close this out as we have not heard back in a while.
If this issue is still reproducible with the latest releases of terraform and the provider, feel free to add in more debugging information here, preferably the full trace logs from the plan.
