### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by kerempg** [hashicorp/terraform#27809]
[crash.log](https://github.com/hashicorp/terraform/files/5998289/crash.log)

**_terraform version is:_**  v0.14.6

I initiated
**terraform plan**

**the response was:**
Acquiring state lock. This may take a few moments...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1f9a631]

goroutine 38 [running]:
github.com/hashicorp/terraform/backend/remote-state/azure.(*RemoteClient).Lock(0xc0003d6000, 0xc0001fa800, 0xc0003d6000, 0xd4bd800, 0xc0003d6000, 0x1)
	/home/circleci/project/project/backend/remote-state/azure/client.go:154 +0x291
github.com/hashicorp/terraform/states/remote.(*State).Lock(0xc00009aea0, 0xc0001fa800, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/states/remote/state.go:208 +0xbd
github.com/hashicorp/terraform/states/statemgr.LockWithContext(0x38e4260, 0xc00009af00, 0xd4bd7d8, 0xc00009aea0, 0xc0001fa800, 0xc0002c3a70, 0xc0002c3a60, 0x0, 0x106b5e1)
	/home/circleci/project/project/states/statemgr/locker.go:76 +0x82
github.com/hashicorp/terraform/command/clistate.(*locker).Lock.func1(0xc000350000, 0xc0002c3a50)
	/home/circleci/project/project/command/clistate/state.go:116 +0x5b
github.com/hashicorp/terraform/helper/slowmessage.Do.func1(0xc00009af60, 0xc00001eb40)
	/home/circleci/project/project/helper/slowmessage/slowmessage.go:20 +0x27
created by github.com/hashicorp/terraform/helper/slowmessage.Do
	/home/circleci/project/project/helper/slowmessage/slowmessage.go:19 +0x77

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by sshafiuddin** [comment]
[crash.log](https://github.com/hashicorp/terraform/files/6009434/crash.log)

While creating the azure webapp service got crashed. PFA
