### ISSUE TITLE
Graceful shutdown doesn't work after ctrl+c during terraform apply

### ISSUE THREAD

**Issue by MetalRex101** [hashicorp/terraform#27814]
Terraform does not stop apply process after interrupt signal from OS.

![image](https://user-images.githubusercontent.com/17021192/108355004-46979000-71fb-11eb-80ff-5819983b02da.png)

### Terraform Version
`v0.12.28`

**Comment by jbardin** [comment]
Hi @MetalRex101 

The output shows the point where terraform requests the provider to stop the current operations, and once they are complete no further changes would be applied. Unfortunately there's not much more that terraform can do here other than to wait for the provider to return if it wants to exit gracefully. The provider itself must implement a way to return more quickly in the case of an interrupt.

Thanks

**Comment by MetalRex101** [comment]
So just to clarify, need to update / fix helm operator, which causes that problem.

**Comment by jbardin** [comment]
@MetalRex101, I don't know if updating the helm provider will change anything, it depends on whether it has implemented a way to interrupt the request or not.

**Comment by MetalRex101** [comment]
Thanks! I got your point. The rest of job for graceful shutdown should be made by provider. In that case - helm provider. So need to fix this problem in helm provider.
