### ISSUE TITLE
Duplicate AWS target groups handled incorrectly

### ISSUE THREAD

**Issue by kiamatt** [hashicorp/terraform#27839]
### Terraform Version
```
0.13.3
```

### Terraform Configuration Files

```terraform
resource "aws_lb_target_group" "tg" {
  name                 = "some_name"
  port                 = var.container_port
  protocol             = "HTTP"
  vpc_id               = var.vpc_id
  target_type          = "ip"
  deregistration_delay = 10
}
```

### Expected Behavior
When you attempt to create an AWS target group with the same name as an existing one, it should fail with an error message like "A target group with this name already exists"

### Actual Behavior
The extra target group succeeds according to Terraform, but no new target group is created. Then, Terraform things two exist, when only one does. So, any resources that need to go to either separate target group go instead to a single target group. Update and destroy actions that are supposed to affect one group or the other also affect the single group.

### Steps to Reproduce
1. Create a .tf file with two aws target groups with the same name
2. terraform init
3. terraform apply
4. The result is that the apply should succeed, but only only one target group is created

**Comment by jbardin** [comment]
Hi @kiamatt,

Thanks for filing an issue. Terraform itself expects a separate resource to be created for each resource defined in the configuration. There is no way to ensure uniqueness between resources, and duplicating a logical resource like this would be classified as user error. 

The only action that could be taken here, is if the aws provider were to catch the duplicate logical resource. It may already do this, but the concurrent creation is avoiding the early detection. If it's not being detected at all, yet should be, an issue can be filed with the [AWS provider project](https://github.com/hashicorp/terraform-provider-aws/issues). They also may have knowledge of any plans working with the [terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk/) around the use of some sort of unique identifier to detecting these sort of incongruities, but that is also currently outside of the control of terraform itself. 

Thanks!
