### ISSUE TITLE
Terraform Crash "Error: rpc error: code = Unavailable desc = transport is closing" 

### ISSUE THREAD

**Issue by jonathan2324** [hashicorp/terraform#27842]
### Terraform Version
`Terraform v0.14.5`

### Terraform Provider File Code
```
terraform {
  required_providers {
    skytap = {
      source = "skytap/skytap"
      version = "0.14.4"
    }
  }
}

provider "skytap" {
  username = var.skytap_username
  api_token = var.skytap_api_token
  
}
```

### Terraform main.tf Code
```
variable "skytap_api_token"{}
variable "skytap_username" {}


module "management_env" {
    source = "./management_environment"
    skytap_api_token = var.skytap_api_token
    skytap_username = var.skytap_username

}

module "dev_env" {
    source = "./developement_environment"
    skytap_api_token = var.skytap_api_token
    skytap_username = var.skytap_username
    
}

module "test_env" {
    source = "./test_environment"
    skytap_api_token = var.skytap_api_token
    skytap_username = var.skytap_username
}

module "dallas_env" {
    source = "./dallas_environment"
    skytap_api_token = var.skytap_api_token
    skytap_username = var.skytap_username
}

resource "skytap_icnr_tunnel" "tunnel-management-dev" {
    source = module.management_env.management_network_id
    target = module.dev_env.dev_network_id

}

resource "skytap_icnr_tunnel" "tunnel-management-test" {
    source = module.management_env.management_network_id
    target = module.test_env.test_network_id

}
resource "skytap_icnr_tunnel" "tunnel-dev-test" {
    source = module.dev_env.dev_network_id
    target = module.test_env.test_network_id

}
```

### Notes

- The initial `terraform apply` execution was successful and my resources were created in the Skytap account. I tried to manually add resources that are not available to the Skytap Provider and when I ran `terraform plan`, I saw this error message: `Error: rpc error: code = Unavailable desc = transport is closing`. 
- I then used `export TF_LOG="TRACE"` and `export TF_LOG_PATH="terraform.txt"` to generate a crash.log file in my project directory.

### Crash Log Errors

[crash.log](https://github.com/hashicorp/terraform/files/6012095/crash.log)

One thing I noticed in the crash logs was the repeating of line `[WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"`  although I am not entirely sure what that means. 

### Additional Information

- When I run `terraform version`, I do see a message stating that I should update my terraform to a new version but I have tried to test terraform plan with another project that uses this same provider and terraform version and it works just fine.

**Comment by jbardin** [comment]
Hi @jonathan2324 

The crash indicates that this is a problem with a `skytap` provider.
You can file an issue in their [project repo here](github.com/terraform-providers/terraform-provider-skytap)

Thanks!
