### ISSUE TITLE
terraform init fail after backend profile change

### ISSUE THREAD

**Issue by adduty** [hashicorp/terraform#27879]
### Terraform Version

```
$ terraform version 
Terraform v0.14.7
```

### Terraform Configuration Files

```terraform
backend "s3" {
    bucket  = "bucketname"
    key     = "terraform.tfstate"
    region  = "us-west-2"
    profile = "prod"
}
```

### Debug Output

Initializing the backend...
2021/02/22 20:58:06 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 1557995203
2021/02/22 20:58:06 [TRACE] Preserving existing state lineage "7c4584e7-771b-d36c-a406-9ce8077c3dbb"
2021/02/22 20:58:06 [TRACE] Preserving existing state lineage "7c4584e7-771b-d36c-a406-9ce8077c3dbb"
2021/02/22 20:58:06 [TRACE] Meta.Backend: working directory was previously initialized for "s3" backend
2021/02/22 20:58:06 [TRACE] backendConfigNeedsMigration: configuration values have changed, so migration is required
2021/02/22 20:58:06 [TRACE] Meta.Backend: backend configuration has changed (from type "s3" to type "s3")
2021/02/22 20:58:06 [WARN] backend config has changed since last init
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.

2021/02/22 20:58:06 [INFO] Attempting to use session-derived credentials

Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.

Please see https://www.terraform.io/docs/language/settings/backends/s3.html
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

### Expected Behavior

The new `profile` value should be reflected in .terraform/terraform.tfstate and terraform should be able to interact with the backend normally.

### Actual Behavior

Terraform uses the old value in .terraform/terraform.tfstate and fails.

### Steps to Reproduce

1. Have a working remote S3 backend with credentials specified by the `profile` argument.
2. Change the value of the `profile` argument in the `backend` block to a valid, existing profile.
3. Run `terraform init`.

**Comment by jbardin** [comment]
Hi @adduty,

It sounds like the stored backend configuration is incorrect or no longer has permission to access the state. In that case you should use the `-reconfigure` flag for `init` to ignore the existing backend config.  Can you verify if the `-reconfigure` option does what you need here?

**Comment by adduty** [comment]
Well, I should have at least re-familiarized myself with the relevant flags first, especially after the -upgrade flag became a requirement for changing version numbers. That did the trick. My apologies, and thanks for the polite answer.
