### ISSUE TITLE
VPC aws_instance security group change forces new resource

### ISSUE THREAD

**Issue by phoolish** [hashicorp/terraform#2787]
I did a cursory search, but couldn't find anything related to this topic.

The benefit of using a VPC ec2 instance is you do not have to recreate it to adjust security groups, but Terraform still seems to require it.

**Comment by mzupan** [comment]
make sure you use `vpc_security_group_ids` 

it works fine in terraform as I use it a lot and when I add/remove a security group it doesn't destroy the resource. If its still not working please show some sample code

**Comment by phoolish** [comment]
Didn't even see that argument. Thanks!
