### ISSUE TITLE
Error while using terraform plan with S3 backend.

### ISSUE THREAD

**Issue by bharti8085** [hashicorp/terraform#27889]
I am trying to use **S3 backend** with Terraform **v0.14.7** with **AWS SSO**. Below is there in my configuration file.

```
provider "aws" {
  version = "~>3.27.0"
  region  = var.region
  profile = var.profile
}

terraform {
  required_version = ">= 0.12"
}

terraform {
  backend "s3" {
       profile        = "AdministratorAccess-my aws account id"
       bucket         = "my-bucket-name"
       encrypt        = true
       key            = "Path-to-key-file"
       region         = "eu-west-1"
  }
}
```

When I run `terraform init -backend-config="../params/s3backend.tfvars"` , I get below message. 

```
Initializing modules...
Downloading **my-module-name** in .terraform\modules\my-module-name

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/aws versions matching "~> 3.27.0"...
- Installing hashicorp/aws v3.27.0...
- Installed hashicorp/aws v3.27.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary. 
```

When I run `terraform plan --var-file=../params/test.tfvars --var-file=../params/common.tfvars` , I get below error. 

```
Error: error configuring S3 Backend: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: 61a36cfd-74be-4d4e-aea2-058dba2eaa7e
```

**Comment by jbardin** [comment]
Hi @bharti8085 

Can you show what parameters you are passing in via the `-backend-config`? The process you're showing should work for most situations, so I'm not sure what's going on yet without a way to reproduce the error.

Thanks!

**Comment by bharti8085** [comment]
Correction - My configuration file has below:

terraform {
  backend "s3" {
    #Backend info is declared in s3backend.tfvars. This s3 backend is used to write state file.
  }
}

And I am passing backend configuration in **s3backend.tfvars** as below (terraform init -backend-config="../params/s3backend.tfvars"):

profile          = "AdministratorAccess-my aws account id"
bucket         = "my-bucket-name"
encrypt        = true
key              = "Path-to-key-file"
region         = "eu-west-1"

**Comment by jbardin** [comment]
Thanks @bharti8085,

Everything looks correct here configuration-wise. Do you have any global AWS setting configured or AWS environment variables set? Terraform isn't indicating any change in the configuration itself, or it would return a `Backend configuration changed` message.  This means that the same config is failing for some reason, during plan even though it was valid when initializing the backend.  

How much time has passed from `init` to `plan`? The message `The security token included in the request is expired` is something I only see when a temporary session token in the aws credentials has expired and need to be refreshed.

**Comment by bharti8085** [comment]
I don't have any global AWS setting configured or AWS environment variables set. I am running terraform plan just after running terraform init.

**Comment by jbardin** [comment]
Your `profile` must correspond to something in the AWS configuration. How exactly are you authenticating to AWS? Can you access the bucket and objects from the aws cli?

**Comment by bharti8085** [comment]
We use AWS SSO and I have different profiles under **C:\Users\Dilip.Bharti\\.aws\config**. e.g. 

[profile AdministratorAccess-**AWS Account ID#1**]
sso_start_url = my-sso-url
sso_region = eu-west-1
sso_account_id = **AWS Account ID#1**
sso_role_name = AdministratorAccess
region = eu-west-1
[profile AdministratorAccess-**AWS Account ID#2**]
sso_start_url = my-sso-url
sso_region = eu-west-1
sso_account_id = **AWS Account ID#2**
sso_role_name = AdministratorAccess
region = eu-west-1

When I run, **aws s3 ls --profile AdministratorAccess-AWS Account ID#1 or 2**, I can see all my buckets.

**Comment by bharti8085** [comment]
Closing the issue, as I fixed my code.
