### ISSUE TITLE
Terraform versions 0.12.30 still can not read stare file from newer 0.13.6

### ISSUE THREAD

**Issue by akomlik** [hashicorp/terraform#27887]
Despite what changelog says I can not use TF 0.12.30 with state file created by 0.13.6

_Originally posted by @alisdair in https://github.com/hashicorp/terraform/issues/25412#issuecomment-756187210_

**Comment by akomlik** [comment]
```
$terraform-0.12  init -reconfigure

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: state snapshot was created by Terraform v0.13.6, which is newer than current v0.12.30; upgrade to Terraform v0.13.6 or greater to work with this state

```

**Comment by alisdair** [comment]
Hi @akomlik. Sorry, there's been a misunderstanding here. Terraform 0.12.30 can read remote state from Terraform 0.13.6 using [the `terraform_remote_state` data source](https://www.terraform.io/docs/language/state/remote-state-data.html). It cannot read and write a full state file.

Terraform versions 0.14 and later will be able to interoperate until the state file format changes, which will not be before Terraform 1.0.

**Comment by akomlik** [comment]
thanks for clarification! I was banging my head on this since yesterday.
