### ISSUE TITLE
Module level depends on causing unprompted module rebuild

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform#27893]
### Terraform Version

```
Terraform v0.14.6
```

### Terraform Configuration Files

```terraform
This involves a ton of code, spanning multiple modules. What exactly do I need to provide?
```

### References

This is a weird one, and I'm not sure how to explain it.
We have a large elk stack module, that has a depends_on (module level) on another module
```hcl
module "elk" {
  source = "../../../modules/aws/monitoring/ELK"
  providers = {
    aws.region      = aws.us_east_1
    aws.hosted_zone = aws.us_east_1
  }

  environment          = local.environment
  ... omitted

  depends_on = [module.document_convert]
}

module "document_convert" {
  source = "../../../modules/aws/services/document_convert"
  providers = {
    aws = aws.us_east_1
  }

  environment               = local.environment
  ... omitted
}
```

Any change to the `document_convert` module, triggers a rebuild (resources must be replaced) of a bunch of resources in the `elk` module.
Looking at some of the terraform plan output, it seems that, something is prompting `elk` to re-read data sources, such as `aws_region`, `aws_iam_policy_document`, when anything in the depends_on module changes. In one of the resources that is deployed in `elk`, the `aws_region.name` attribute is being used in a string interpolation, in an attribute, that forces replacement when changed. So, because `aws_region` gets re-read, at plan time, terraform doesn't know what the region name will be, and so assumes it will change and will need to rebuild the resource.

the code:
```hcl
resource "aws_lambda_permission" "allow_cloudwatch" {
  provider = aws.region

  for_each      = var.cloudwatch_log_group_arns

  action        = "lambda:InvokeFunction"
  function_name = local.name
  principal     = "logs.${data.aws_region.current.name}.amazonaws.com"
  source_arn    = "${each.value}:*"
}
```

the plan output:
```hcl
  # module.elk_us_east_1.aws_lambda_permission.allow_cloudwatch["document_convert"] must be replaced
-/+ resource "aws_lambda_permission" "allow_cloudwatch" {
      ~ id            = "AllowExecutionFromCloudWatch" -> (known after apply)
      ~ principal     = "logs.us-east-1.amazonaws.com" -> (known after apply) # forces replacement
      ~ statement_id  = "AllowExecutionFromCloudWatch" -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

This same problem cascades throughout the whole module, with a bunch of different resources wanting to rebuild.
Removing the module level depends_on, makes the problem go away

**Comment by jbardin** [comment]
Hi @lijok 

You are correct, something is triggering the data sources in `elk` to be re-read and deferred until apply; that something is `depends_on`. See #26383 for a duplicate with a more complete explanation. 

Thanks!
