### ISSUE TITLE
Using Terraform for Builds as well as Deploys

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#2789]
(Note well: This is more of a philosophical discussion than an issue, but I decided to create it here since the Terraform team and community seems to be paying most attention to the Github issue queue.)

A while back I opened #1586 about having a way for a Terraform build to run Packer, so that the Terraform state mechanism could be used as a convenient way to hand off between a Packer build and a Terraform deployment.

Since that time my ideas on this subject have evolved and so I'm opening this issue primarily to share what I've been thinking about and hopefully start a discussion about it.

In summary, I believe that the core of Terraform -- combined with an appropriate set of resources that might not all exist yet -- can be used to implement most of the key functionality of Packer, and that doing so could result in a smoother integration between the build and deploy steps and add new capabilities that Packer and Terraform together do not have today.

This can be achieved via the following broad changes:
- Create a new frontend for Terraform that has verbs more appropriate for building:
  - `build`: create an empty state, read a config, and create all of the resources in this config before writing out a state file of the result. Unlike `terraform apply` this would always start from an empty state and thus create new resources on each run.
  - `destroy`: given an existing state file, destroy all of the resources in the state. This allows the resources from earlier builds to be easily destroyed when they are no longer required, improving on the capabilities of Packer today
  - `publish`: given an existing state file, publish it to a Terraform remote state backend so that it can be easily consumed by a downstream Terraform config.
- Add the new concept of a _temporary resource_, which is created only to support the creation of other resources and can be destroyed at the end of the build. This can then be functionally equivalent to Packer's process of e.g. creating an EC2 keypair, security group and source instance that can then be unwound once an AMI is created.

This of course represents enormous scope creep for Terraform, so I'm not suggesting to add these new features to the existing product but rather thinking about a potential _new_ product that shares the core functionality of Terraform but is presented as a separate, complementary tool.

To delve into this concept some more I built a prototype called [Padstone](https://github.com/apparentlymart/padstone), and I've written [a longer article on my blog](http://apparently.me.uk/padstone-terraform-for-deployment/) with some more exposition, a more detailed analysis of the implications of this approach, and how the Padstone prototype implements the idea.

Of course I'm not expecting immediate action on this idea. Rather I'd like to discuss more broadly the pros and cons of the idea, the way I implemented it in the prototype, and whether this direction is compatible with the philosophy of the HashiCorp family of tools.

It might well be that github issues is not a great place to discuss a big idea like this; if so, I'm happy to close this up and post it elsewhere.

**Comment by jonathandietz** [comment]
@apparentlymart this is a pretty interesting approach.

**Comment by beddari** [comment]
I've been thinking almost the same. Following this.

**Comment by beddari** [comment]
I saw your other update @apparentlymart ... just to muddle it a little bit more, we now got https://www.nomadproject.io/docs/jobspec/index.html

**Comment by apparentlymart** [comment]
I did another pass at a design for this, with a different approach entirely: https://gist.github.com/apparentlymart/52323c9456b317ab559666da91c94865

This new proposal is intended to support both dev *and* build use-cases, and to be familiar to folks who are used to tools like `make` which work in terms of targets.

I'll probably slowly prototype this over in my padstone repo, but it's not a focus for me right now.

**Comment by misham** [comment]
Been reading up on the various approaches and what people have done around this.  I spent some time with Atlas as well, to see how that solves the problem.

I am thinking of a fairly simple approach via Terraform Provider for Packer.

Curious to get feedback on the following:

The high-level workflow is:

* Create the Packer setup separately, test it, add support for Vagrant, AWS, OpenStack, etc.  At the end, you can run Packer file independent of anything and it will work just fine.
* Use that Packer file in a Terraform Packer Provider to generate an AMI / OpenStack image / etc.
* Save the resulting image information information in the `terraform.tfstate` file about the generated image ID and the "version" of Packer file used to generate that image

There are a few gotchas to this approach:

### Handling State

How do you know the "version" of the Packer file used to generate that image?  My initial idea is to generate a SHA hash of the entire Packer file.  However, this won't work, as the Packer file may not have changed but the scripts driving the Packer file, e.g. Ansible playbooks, have changed.

It's possible to add versioning information to the Packer file, but that's a manual process and the whole idea is to avoid that.

It's possible to update Packer to build a version of itself based on a hash of all of it's components, including hashing all the scripts it uses.  I'm not sure if Packer folks would be interested in this.

Another approach is to assume that Packer file is version-controlled and trigger on the Git / SVN / etc. version only.  To handle a case when a Packer file is not in version control or for local development, add a flag to always run the Packer provisioner, as a CLI option and as part of the provisioner options.

The last option is quite hack-y, but might be the closest option without baking versioning into Packer.

### Relying on Non-Image Packer Builds

What to do about cases when the output of Packer run is a VM box and not an image?

I'd argue, nothing.  Either Terraform has a way of taking advantage of that kind of output or it doesn't, it's up to the end-user to understand what they're after and how to manage it.

Also, the Packer Provider can be restricted only to those image types that generate an image for a Cloud-based system, e.g. AWS, OpenStack, etc.

### Example Provider Config

```hcl
resource "packer_image" "rails_app" {
    packer_file_path = "/my/packer/file/rails_app.json"

    variable {
        name = "vpc_id"
        value = "${aws_vpc.default.id}"
    }

    variable {
        name = "subnet_id"
        value = "${aws_subnet.default.id}"
    }

    # Force to always run
    #    Default is false, but can be triggered via
    #        terraform taint packer_image.rails_app
    force = false

    # Limit which provisioners to build
    #   The result of each image is placed into <provisioner>_id format for output
    provisioners = ["amazon-ebs", "openstack"]
}

output "rails_app_ami_id" {
    value = "${packer_image.rails_app.ami_id}"
}

output "rails_app_openstack_image_id" {
    value = "${packer_iamge.rails_app.openstack_id}"
}
```

**Comment by mitchellh** [comment]
I'm going to close this.

I'm completely open to Terraform supporting resources to assist with image creation (such as @apparentlymart's `ami_from_instance`). In the future, I'd love for tools such as our own Packer to simply be thin layers above Terraform. I think this makes sense and centralizes the logic of dealing with resource CRUD into Terraform, which is something Terraform is particularly good at.

**Comment by sheerun** [comment]
@mitchellh I think packer would serve better as data provider for terraform, especially packer often needs to be launched in the middle of setting up infrastructure. For example creating disk image on azure require storage to be existing, but on the other hand creating VM requires disk image by packer to exists... This is a chicken and egg problem that can be only solved by treating packer run as a part of terraform build.
