### ISSUE TITLE
Unable to do terraform init to pull module from Gitlab.com

### ISSUE THREAD

**Issue by mizunos** [hashicorp/terraform#27892]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform version 0.13.4

If you are not running the latest version of Terraform, please try upgrading because your issue may have already been fixed.
-->

```
...
```

### Terraform Configuration Files

```terraform
module "gl_project" {
    source = "git::ssh://git@gitlab.com/company/sandbox/user-sandbox/iac/terraform-modules/gitlab/terraform-gitlab-arc-project.git"
    modinput_name = var.tplinput_project_name
    modinput_namespace_id = var.tplinput_parent_id
    modinput_description = var.tplinput_description
}

```

### Output when running terraform init

Initializing modules...
Downloading git::ssh://git@gitlab.com/company/sandbox/user-sandbox/iac/terraform-modules/gitlab/terraform-gitlab-arc-project.git for gl_project...

Error: Failed to download module

Could not download module "gl_project" (main.tf:12) source code from
"git::ssh://git@gitlab.com/company/sandbox/user-sandbox/iac/terraform-modules/gitlab/terraform-gitlab-arc-project.git":
error downloading
'ssh://git@gitlab.com/company/sandbox/user-sandbox/iac/terraform-modules/gitlab/terraform-gitlab-arc-project.git':
/usr/bin/git exited with 128: Cloning into '.terraform/modules/gl_project'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### Additional Context
git clone using ssh works fine

**Comment by pselle** [comment]
Hi there! Could you please fill out the issue template, including debug logs (with any secrets removed)? Are you seeing this issue with all [git](https://www.terraform.io/docs/language/modules/sources.html#generic-git-repository) repositories or with this specific one? (it appears you have permissions issues)

**Comment by mizunos** [comment]
I am having issue with all git repos under gitlab.  Modules that used to work for me now seemed to have the same issue with terraform init with the host key verification failed.  It is really mind boggling because everything else seemed to be working for  git operations such as cloning, pushing to gitlab fine for those same directory using the current ssh key.

**Comment by mizunos** [comment]
I am closing this issue as I figure out what happened.  I was running terraform inside docker while comparing git clone from my local.  Once I downloaded terraform directly to my local instead of dockerized version, everything is working fine.
