### ISSUE TITLE
OCI: Dependency on module with compartment is not fulfilled

### ISSUE THREAD

**Issue by kacejot** [hashicorp/terraform#27899]
### Terraform Version

```
> $ terraform version                                                                                                                                                                                                     [±dev-zte ●]
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.25.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/oci v4.10.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
```

### Terraform Configuration Files

```terraform
# Compartment.tf
resource oci_identity_compartment compartment {
  name = var.name
  description = var.description
  compartment_id = var.compartment_id
  enable_delete = var.enable_delete
}

# VCN.tf
resource oci_core_vcn vcn {
  cidr_block = var.vcn_subnet
  compartment_id = var.compartment_id
  display_name = var.vcn_name
}

...

resource oci_core_drg drg {
  compartment_id = var.compartment_id
  display_name = var.drg_name
}

resource oci_core_drg_attachment drg_attachment {
  drg_id = oci_core_drg.drg.id
  vcn_id = oci_core_vcn.vcn.id
  display_name = var.drg_attachment_name
}

...

# main.tf
module Compartment {
  source = "./Compartment"

  name = var.compartment_name
  description = var.compartment_description
  enable_delete = var.enable_delete
  compartment_id = var.compartment_id
}

module VCN {
  providers = {
    oci = oci.ap_mumbai_1
  }

  source = "./VCN"
  depends_on = [
    module.Compartment
  ]
}
```

### Expected Behavior
VCN module creation must be started after Compartment module creation is finished

### Actual Behavior
Compartment module is not created despite the logs.
```
module.Compartment.oci_identity_compartment.compartment: Creating...
module.Compartment.oci_identity_compartment.compartment: Creation complete after 6s [id=ocid1.compartment.#######################################################]
module.VCN.oci_core_drg.drg: Creating...
module.VCN.oci_core_vcn.vcn: Creating...
module.VCN.oci_core_vcn.vcn: Still creating... [10s elapsed]
module.VCN.oci_core_vcn.vcn: Still creating... [20s elapsed]
module.VCN.oci_core_vcn.vcn: Still creating... [30s elapsed]
module.VCN.oci_core_vcn.vcn: Still creating... [40s elapsed]

Error: Post https://iaas.ap-mumbai-1.oraclecloud.com/#########/vcns: EOF

  on VCN/VCN.tf line 13, in resource "oci_core_vcn" "vcn":
  13: resource oci_core_vcn vcn {



Error: Service error:RelatedResourceNotAuthorizedOrNotFound. Compartment: ocid1.compartment..####################################################### does not exist or you are not authorized to access it. http status code: 400.

  on VCN/VCN.tf line 55, in resource "oci_core_drg" "drg":
  55: resource oci_core_drg drg {

```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
I can't show all the configs and debug logs. This info should be enough.
As you can see from the logs, Terraform acts as if compartment is already created, but error says that compartment does not exist. It is true, because I have applied [workaround](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep) that delays DRG creation and it worked. The problem is that I can't really tell how much I need to wait before compartment is created. This value differs from time to time. No delay can substitute strong module dependency.

**Comment by jbardin** [comment]
Hi @kacejot 

Thanks for filing the issue. Unfortunately without the complete configuration or logs we cannot see exactly what was happening, but the output here does appear to indicate that the resources in `module.Compartment` are completed before the resources in `module.VCN`. 

The fact that terraform reports `Creation complete` and execution continued means that the provider reported the resource change for `module.Compartment.oci_identity_compartment.compartment:` was applied successfully. There's nothing else that terraform could wait for if that is the key dependency in this error situation. Many cases like this arise from the eventual consistency delays in the service, where the provider will create a resource, but looking up that same resource can fail for a short amount of time immediately after. 

The provider itself may be able to implement some sort of double-check for resources that are only eventually consistent like this. I would suggest filing an issue with the provider regarding the situation. If you have more information that leads to an issue in terraform itself, feel free to add it here and we can re-evaluate. 

Thanks!
