### ISSUE TITLE
terraform state mv not creating backups

### ISSUE THREAD

**Issue by mattk-ce** [hashicorp/terraform#27908]
### Terraform Version
0.14.6 - WINDOWS

### Expected Behavior
backup file should be created

### Actual Behavior
no backup file is created

### Steps to Reproduce
0. on windows
1. using s3 remote state - might not be relevant, but is my current configuration
2. `terraform state mv -backup="test.backup"  -state-out="test/terraform.tfstate" aws_iam_role.test aws_iam_role.test`
OR
`terraform state mv -state-out="test/terraform.tfstate" aws_iam_role.test aws_iam_role.test`

### Additional Context
Using an s3 backend (might not be relevant, but is my current configuration).  When specifying a `-backup`, no backup file is created when executing a `state mv`.  When not specifying `-backup`, no backup file is created when executing a `state mv`

**Comment by alisdair** [comment]
Hi @mattk-ce, thanks for reporting this.

The remote state storage backends do not support local backups (including the `-backup` CLI flag), to avoid accidentally exfiltrating sensitive state to a local filesystem. For more on this, see #16464, where the change was made. [We recommend using bucket versioning](https://www.terraform.io/docs/language/settings/backends/s3.html) as the S3 backup strategy.

That said, Terraform could be clearer about this. I think we might be able to find somewhere in the docs to clarify this exception, and perhaps we can render a diagnostic warning or error when using `-backup` with a remote state storage backend.
