### ISSUE TITLE
iam user policy error of resource repetition

### ISSUE THREAD

**Issue by monicagangwar** [hashicorp/terraform#2790]
i have multiple aws_iam_user_policy instances with same name and policy but different user.
but when i run terraform plan, i get the following error
* aws_iam_user_policy.<resource name>: resource repeated multiple times

is there any way around here?

**Comment by catsby** [comment]
Hey @monicagangwar – that error sounds like you're giving the `aws_iam_user_policy` resource the same "name" in the configuration, like so:

```javascript
resource "aws_iam_user_policy" "first" {
  [...]
  user = "first_user"
}
resource "aws_iam_user_policy" "first" {
  [...]
  user = "second_user"
}
resource "aws_iam_user_policy" "first" {
  [...]
  user = "third_user"
}
```

Where as you probably want:

```javascript
resource "aws_iam_user_policy" "first" {
  [...]
  user = "first_user"
}
resource "aws_iam_user_policy" "second" {
  [...]
  user = "second_user"
}
resource "aws_iam_user_policy" "third" {
  [...]
  user = "third_user"
}
```

Is that what you have, by chance?

**Comment by monicagangwar** [comment]
i want it as the first code snippet only. AWS allows resources to be named as such. 
i'm retrieving the already developed infrastructure from AWS and then trying terraform plan.  
i was expecting it to output no change instead of the error  " resource repetition"

**Comment by catsby** [comment]
I'm sorry to say that the first code snippet is not valid syntax for a Terraform configuration. The `resource repetition` referenced here is specific to Terraform (the `resource "aws_iam_user_policy" "first"` part)... that name is not shared with AWS. 

The `name` property inside the `resource` block can be the same, if I recall correctly, but the first snippet syntax is invalid for Terraform. Terraform needs to track each resource and does so by that name.

**Comment by catsby** [comment]
To expand, this should be valid:

```javascript
resource "aws_iam_user_policy" "first" {
  [...]
  name = "iam_name"
  user = "first_user"
}
resource "aws_iam_user_policy" "second" {
  [...]
  name = "iam_name"
  user = "second_user"
}
resource "aws_iam_user_policy" "third" {
  [...]
  name = "iam_name"
  user = "third_user"
}
```

**Comment by catsby** [comment]
Please see also:

- https://terraform.io/docs/providers/aws/r/iam_group_membership.html
- https://terraform.io/docs/providers/aws/r/iam_policy_attachment.html
