### ISSUE TITLE
Module "gke" ... cannot be found in the module registry

### ISSUE THREAD

**Issue by soudaburger** [hashicorp/terraform#27907]
### Terraform Version
```
Terraform v0.14.7
```
### Terraform Configuration Files
```terraform
# provider.tf
provider kubernetes {
  load_config_file       = true
  host                   = "https://${module.gke.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(moduel.gke.cluster_ca_certificate)
}
# cluster.tf
module gke {
  source                     = "terraform-google-modules/kuberetes-engine/google"
  version                    = "13.1.0"
  project_id                 = var.project_id
  name                       = "k8s-${var.environment}"
  region                     = var.cluster_region
  zones                      = var.cluster_zones
  network                    = "k8s-${var.environment}"
  subnetwork                 = "k8s-${var.environment}"
  horizontal_pod_autoscaling = true
  network_policy             = true
}
```

```
Terraform v0.14.7
```

### Debug Output
https://gist.github.com/soudaburger/6d039586c8edba9e80f1d770fc331880

### Steps to Reproduce
1. Follow instructions at https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest
2. Create necessary tf files
3. Run `terraform init`
4. Terraform fails to initialize

### References

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/831

**Comment by mildwonkey** [comment]
Hi @soudaburger , this is interesting! Terraform is able to download the module when I remove the `version` block:

```
module "kubernetes-engine" {
  source  = "terraform-google-modules/kubernetes-engine/google"
  # insert the 9 required variables here
}
```

It also works when I replace the `version` and put a `v` in front of the number:
```
module "kubernetes-engine" {
  source  = "terraform-google-modules/kubernetes-engine/google"
   version                    = "v13.1.0"
  # insert the 9 required variables here
}
```

Now, this is weird, because I can download a different google cloud module that uses the same version tags in their repository (v2.0, etc) without that v:
```
module "gcloud" {
  source  = "terraform-google-modules/gcloud/google"
  version = "2.0.3"
}
```

Now here's the _really_ fun part: the third time I ran this - with the originally failing configuration - it worked just fine. I'm curious if it works for you now - perhaps there was some registry/network wonkiness? 

If it still fails, could you update this issue with a full TRACE log from a failed `init`? The one you have linked does not show any error.

**Comment by soudaburger** [comment]
I was definitely optimistic, but still having the same issue after removing the module version and nuking any `.terraform` directory just to ensure we were starting fresh.

https://gist.github.com/soudaburger/b3de51f74fac652f6e9e363c58849e34

**Comment by mildwonkey** [comment]
I believe you, and I did reproduce that same message the same time, but I haven't been able to get that message again. That might suggest a registry (or CDN) issue 🤔 

I would be curious to hear if you get a different result with a slightly modified version string? (I don't expect you to, and I'd go as far as to say you shouldn't, but I'm curious). 

```
module "kubernetes-engine" {
  source  = "terraform-google-modules/kubernetes-engine/google"
   version                    = "v13.1.0"
  # insert the 9 required variables here
}
```

I'll reach out to the public registry team and see if there's anything they can take a look at. Thanks for getting back with that log!

**Comment by soudaburger** [comment]
I even set the version string to something arbitrary that I've never used and probably isn't even a valid version, but same results.  I used `v9.9.9` just to test and behavior and output is the same.

**Comment by mildwonkey** [comment]
Hi @soudaburger ! Good news!
The reason I was able to reproduce this the first time, and not again, was that I'd started with your configuration my first time through, but replaced it with a copy-paste of the source block in the registry. 

One of our registry team members very helpfully found the discrepancy - the module source is misspelled in your configuration, It's missing an `n` in kubernetes:


`source                     = "terraform-google-modules/kuberetes-engine/google"`
vs
 `source                     = "terraform-google-modules/kubernetes-engine/google"`

Can you give that a try?

**Comment by soudaburger** [comment]
Well, now i just feel dumb.  I hate that I wasted my time and everyone else's on a typo.  Ugh!!! But Thanks! I'll close this!
