### ISSUE TITLE
Terraform 0.15.0-rc2 released!

### ISSUE THREAD

**Issue by pkolyvas** [hashicorp/terraform#27917]
We’ve just released Terraform 0.15.0-rc2! We’d be very grateful for help in testing it.

Download it here: https://releases.hashicorp.com/terraform/0.15.0-rc2/

We do not recommend using the release candidates in production. While this release has seen some alpha testing prior to these beta releases, the betas will be the first exposure of some of this code to use-cases the Terraform team didn’t anticipate during initial testing. There may well be bugs lurking which we’ll aim to address during the beta period.

The draft upgrade guide is here: https://github.com/hashicorp/terraform/blob/v0.15/website/upgrade-guides/0-15.html.markdown

This issue is locked in order to redirect feedback and discussion to our community forums: https://discuss.hashicorp.com/t/terraform-0-15-0-rc2-released

If you discover an issue with 0.15.0-rc2 we'd kindly ask that you report issues in the usual way so that we can track and triage each concern appropriately.

**Comment by danieldreier** [comment]
Now that [Terraform 0.15 is GA](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-15-general-availability), I'm going to resolve this. 🎉
