### ISSUE TITLE
Add Terraform Homebrew formula for Apple Silicon

### ISSUE THREAD

**Issue by bkuhlmann** [hashicorp/terraform#27921]
### Terraform Version

0.14.0 (or most recent possible)

### Terraform Configuration Files

N/A

### Debug Output

``` 
Error: terraform: no bottle available!
```

### Crash Output

N/A

### Expected Behavior

Would have liked to see `brew install terraform` work without error.

### Actual Behavior

Am seeing this instead:

``` 
Error: terraform: no bottle available!
```

### Steps to Reproduce

Chip: Apple M1

1. On macOS 11.2.1 (20D75), run `brew install terraform` to see the error.

**Comment by jbardin** [comment]
Hi @bkuhlmann 

Thanks for filing the issue, but we don't maintain the homebrew formula here.
I believe that formula is maintained in the homebrew-core project.

Thanks!

**Comment by bkuhlmann** [comment]
:bow: @jbardin That's good to know, I will follow up with them there.
