### ISSUE TITLE
Is TF_LOG deprecated?

### ISSUE THREAD

**Issue by arvidviderberg** [hashicorp/terraform#27938]
### Terraform Version

```
0.14.4
```

### Expected Behavior

According to the [docs](https://www.terraform.io/docs/internals/debugging.html), setting `TF_LOG` to `WARN` should decrease Terraform log level. However, doing so fires a warning that such log level is unreliable. What's the purpose of having the log levels? Have they been deprecated? I think the docs could clarify a bit here. What is the best approach to keep the log level down? Should we use something as suggested in #27214?

### Actual Behavior

`[WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.`

### Steps to Reproduce

Set `TF_LOG` to `WARN` and run any terraform command.

### References

- #27214

**Comment by jbardin** [comment]
Hi @arvidviderberg 

The fix for this was initiated in #26632, and is part of the 0.15 release: https://github.com/hashicorp/terraform/blob/v0.15/CHANGELOG.md

Thanks!
