### ISSUE TITLE
Automatic Import Using Identifier Specification

### ISSUE THREAD

**Issue by bondsbw** [hashicorp/terraform#27959]
### Current Terraform Version

```
0.14.6
```

### Use-cases

Terraform only provides an import mechanism through parameters supplied to the `terraform import` command.  It is unable to utilize data sources or variables in determining the identifier used for import, and its limitations result in rare use in complex scenarios.

### Proposal

A resource may not specify its identifier via argument.  This is provided by the cloud provider.

This proposal allows the resource to specify its identifier.  Doing so will attempt to import the resource:

```tf
resource "aws_instance" "web" {
    id = "i-12345678"
    ...
}
```
would be the equivalent of
```
terraform import aws_instance.web i-12345678
```

The identifier may also be specified by variable or interpolation:

```tf
resource "aws_instance" "web" {
    id = var.instance_id
    ...
}
```

Allowing references opens up succinct "import-if-not-exists" scenarios, including lookups and filtering:

```tf
data "aws_instance" "existing_server" {
  filter {
    name   = "tag:Name"
    values = ["instance-name-tag"]
  }
}

resource "aws_instance" "web" {
    id = try(data.aws_instance.existing_server.id, null)
    ...
}
```

This could enable more complex cases of importing related resources:

```tf
# same as above
data "aws_instance" "existing_server" {
  filter {
    name   = "tag:Name"
    values = ["instance-name-tag"]
  }
}

resource "aws_instance" "web" {
    id = try(data.aws_instance.existing_server.id, null)
    ...
}

# import all security groups assigned to the "web" instance
resource "aws_security_group" "web_security_groups" {
    for_each = aws_instance.web.security_groups
    id       = each.value
    ...
}
```

**Comment by jbardin** [comment]
Hi @bondsbw,

Thanks for filing the issue. We are tracking the feature request for configuration driven import in #26364.
