### ISSUE TITLE
Terraform 0.14.7 panic: value is marked, so must be unmarked first

### ISSUE THREAD

**Issue by pbzdyl** [hashicorp/terraform#27954]
### Terraform Version
```
terraform version 
Terraform v0.14.7
```
### Terraform Configuration Files

`repro/main.tf`:
```terraform
output "out" {
  value = {
    a = "x"
    b = "y"
  }
  sensitive = true
}
```

`main.tf`:
```
module "repro" {
  source = "./repro"
}

locals {
  m = {
    x = 1
    y = 2
  }
  z = local.m[module.repro.out.a]
}
```

### Debug Output

https://gist.github.com/pbzdyl/e63393715d124570e33a8a94c49f8a73#file-terraform-debug-log

### Crash Output

https://gist.github.com/pbzdyl/e63393715d124570e33a8a94c49f8a73#file-terraform-crash-log

### Expected Behavior

`terraform plan` should not crash.

### Actual Behavior

`terraform plan` crashes with `panic: value is marked, so must be unmarked first`

### Steps to Reproduce

Using the two files mentioned above (`repro/main.tf` and `main.tf`) run:
1. `terraform init`
2. `terraform plan`

The second step will crash.

### References

Similar to #27403, #27220, #27107

**Comment by jbardin** [comment]
Thanks for filing the issue @pbzdyl. This is fixed upstream in https://github.com/hashicorp/hcl/pull/451, and should be included in the next release.

**Comment by pbzdyl** [comment]
Great news @jbardin. Is the next release date already known?

**Comment by jbardin** [comment]
Close via #28034
