### ISSUE TITLE
InvalidClientVpnDuplicateRoute: Route already

### ISSUE THREAD

**Issue by debu99** [hashicorp/terraform#27951]
### Terraform Version

```

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.30.0
```

### Terraform Configuration Files

```terraform
resource "aws_ec2_client_vpn_route" "vpn_route" {
  for_each               = toset(var.subnet_ids)
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.client_vpn_endpoint.id
  destination_cidr_block = var.target_network_cidr
  target_vpc_subnet_id   = aws_ec2_client_vpn_network_association.subnet_association[each.key].subnet_id
}
```

### Debug Output

aws_ec2_client_vpn_endpoint.client_vpn_endpoint: Modifying... [id=cvpn-endpoint-06xxxxx]
aws_ec2_client_vpn_endpoint.client_vpn_endpoint: Modifications complete after 1s [id=cvpn-endpoint-06xxxxx]
aws_ec2_client_vpn_route.vpn_route["subnet-0bd12xxx"]: Creating...

Error: error creating client VPN route "cvpn-endpoint-06xxxxx,subnet-0bd12xxx,10.10.0.0/16": InvalidClientVpnDuplicateRoute: Route already exists
	status code: 400, request id: efa086f4-110c-4331-af0d-342c568fa096

  on main.tf line 75, in resource "aws_ec2_client_vpn_route" "vpn_route":
  75: resource "aws_ec2_client_vpn_route" "vpn_route" {

### Crash Output

aws ec2 describe-client-vpn-routes --client-vpn-endpoint-id cvpn-endpoint-06xxxxx 
{
    "Routes": [
        {
            "ClientVpnEndpointId": "cvpn-endpoint-06xxxxx",
            "DestinationCidr": "10.10.0.0/16",
            "TargetSubnet": "subnet-0bd12xxx",
            "Type": "Nat",
            "Origin": "associate",
            "Status": {
                "Code": "active"
            },
            "Description": "Default Route"
        }
    ]
}

terraform import aws_ec2_client_vpn_route.vpn_route cvpn-endpoint-06xxxxx
aws_ec2_client_vpn_route.vpn_route: Importing from ID "cvpn-endpoint-06xxxxx"...

Error: unexpected format for ID ("cvpn-endpoint-06xxxxx"), expected endpoint-id,target-subnet-id,destination-cidr-block

### Expected Behavior

Terraform apply/re-apply error but it should be able to import

### Actual Behavior

Failed apply & re-apply and can't import

### Steps to Reproduce

create aws_ec2_client_vpn_endpoint and aws_ec2_client_vpn_route

### Additional Context

https://github.com/hashicorp/terraform-provider-aws/issues/16048

**Comment by jbardin** [comment]
Hi @debu99,

Sorry you're having trouble with this, but it does not look like a Terraform issue. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. If there is an issue here with the format of the id preventing import, you would need to file an issue with the AWS provider.

Thanks!
