### ISSUE TITLE
init and apply fail while running in Azure Container Instances

### ISSUE THREAD

**Issue by ralacher** [hashicorp/terraform#27968]
### Terraform Version

```
v0.14.7
```

### Terraform Configuration Files

```
provider "null" {}
resource "null_resource" "cluster" {}
```

### Debug Output

Logs were created by running `terraform init` until successful (three times) then running `terraform apply` until successful (three times).
1. First `terraform init` [link](https://gist.github.com/ralacher/8e59b8b4daa9f47746f3e691be68737f#file-terraform-init-01-log)
2. Second `terraform init` [link](https://gist.github.com/ralacher/8e59b8b4daa9f47746f3e691be68737f#file-terraform-init-02-log)
3. Third `terraform init` [link](https://gist.github.com/ralacher/8e59b8b4daa9f47746f3e691be68737f#file-terraform-init-03-log)
4. First `terraform apply` [link](https://gist.github.com/ralacher/8e59b8b4daa9f47746f3e691be68737f#file-terraform-apply-01-log)
5. Second `terraform apply` [link](https://gist.github.com/ralacher/8e59b8b4daa9f47746f3e691be68737f#file-terraform-apply-02-log)
6. Third `terraform apply` [link](https://gist.github.com/ralacher/8e59b8b4daa9f47746f3e691be68737f#file-terraform-apply-03-log)

### Crash Output

Could not reproduce the crash using the `null` resource provider. Crash log was created using AzureRM and AzureAD providers.
https://gist.github.com/ralacher/8e59b8b4daa9f47746f3e691be68737f

### Expected Behavior

Initialize and apply should have been successful on the first attempt.

### Actual Behavior

`init` failed initially and appeared to be successful the third time. `apply` complains about the plugins not being initialized or fails but I can't find a pattern as to why.

### Steps to Reproduce

1. `terraform init` (until successful)
2. `terraform apply` (combinations of running `init` prior to `apply` and re-running `apply` seem to produce different errors)

### Additional Context

1. Same results running in a wrapper script on a CI system and interactively
2. Terraform was installed directly from the website and from the Alpine edge repo and produced the same result
3. Terraform is running on Azure Container Instances using the [mcr.microsoft.com/azure-cli:2.9.1](https://hub.docker.com/_/microsoft-azure-cli) image

**Comment by ralacher** [comment]
After some further testing it looks as though the problem is with a mounted Azure Storage File Share. When I move my Terraform configurations off of the mounted directory it works fine.

**Comment by alisdair** [comment]
Looking at the crash logs, all I can see is SIGBUS errors. From my understanding that seems like a crash which is outside of Terraform's control, at the system level. Unless I'm mistaken I don't think this points to a bug in either Terraform or the crashing provider.

As an aside, Terraform generally does not work well with unreliable file systems. Another example of this sort of problem includes using VMWare shared folders. If you are able to avoid these crashes by running Terraform elsewhere in the filesystem, I think that might be the most pragmatic solution to the problem.

**Comment by apparentlymart** [comment]
Hi again @ralacher!

It looks like this issue has been idle for some time and the last comment was from one of my colleagues on the Terraform Core team. As noted above, Terraform generally expects to be running on a reliable local filesystem rather than via a high-latency network filesystem, and we typically cannot test on specific network filesystems such as Azure Storage File Share.

Our recommendation is to always run Terraform with the working directory on a local disk, and to use remote state to store the persistent state snapshots in a remote location over the network. Since you said that moving it off of the network filesystem solved the problem for you, I'm going to close this issue now. Thanks!
