### ISSUE TITLE
Questions related to spawning nodes on AWS

### ISSUE THREAD

**Issue by madhurranjan** [hashicorp/terraform#2796]
We're big fans of Terraform . Great going. 

We've a couple of questions :
1. How do I assign a specific public ip to a vpc instance while starting up rather than allow the code to assign a public ip ?
2. If I have a bunch of terraform files, is there a way I can run terraform on only one of the *.tf files ? This is an intermediate step till we sync up all our resources but is needed for now.

**Comment by mitchellh** [comment]
Can you please ask usage questions like this on the mailing list? It is a much better way to get responses. I'll answer your questions briefly, but for deeper questions please move to the mailing list.

1. I don't know off the top of my head.

2. Unfortunately no, but you can put them in separate directories for dev.
