### ISSUE TITLE
Issue removing GKE Workload Identity - GCP

### ISSUE THREAD

**Issue by lcoupe** [hashicorp/terraform#27983]
Hi there,

I enabled the `Workload Identity` feature on our GKE cluster - however, it caused a separate issue so I was required to revert the change.

I had initially configured it like so:

Within the cluster resource
![Screenshot 2021-03-04 at 19 51 44](https://user-images.githubusercontent.com/77781046/110021829-23a0cc00-7d23-11eb-9ce9-6b38cde506d4.png)

Within the node pool resource
![Screenshot 2021-03-04 at 19 52 00](https://user-images.githubusercontent.com/77781046/110021849-27345300-7d23-11eb-8723-9fa3ec4567df.png)

Now - initially, I removed these references and the plan implied it was just going to remove the `workload_identity_config` - which this fails on the first run as the metadata config needs to be removed from the node pool first - however, Terraform didn't seem to notice this had been removed from the code - so I disabled it manually and then ran Terraform again - this then proceeds to remove the `workload_identity_config` (Although Terraform does time out during the process as it takes longer than what I assume the timeout value is) however, it still removes the config successfully in the GCP console. 

Now I'm not sure if the timeout caused this, but the statefile now has the config partially there, like so:

![Screenshot 2021-03-04 at 19 52 53](https://user-images.githubusercontent.com/77781046/110021904-3b785000-7d23-11eb-98b7-7c097784ef62.png)

This means the plans constantly see this and attempt to remove it like so:

![Screenshot 2021-03-04 at 19 47 13](https://user-images.githubusercontent.com/77781046/110021281-729a3180-7d22-11eb-9c33-a46c0fe84f79.png)

If I apply this, it runs and completes but subsequent plans still see the change.

Any guidance/assistance would be greatly appreciated.

### Terraform Version
```
0.13.6
```
### Google Provider Version
```
3.58.0
```
### Expected Behavior
The feature should be removed from both the cluster AND the state file - clean Terraform plans should follow.

### Actual Behavior
The feature is removed from the cluster but remains partially in the state file - Terraform plans are not clean.

**Comment by lcoupe** [comment]
Just to update on this - I thought I could perhaps work around it by adjusting the timeout value on the resources - I re applied and removed again - this time Terraform did not time out and exited cleanly - but the state still shows 

`      - workload_identity_config {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.`

**Comment by jbardin** [comment]
Hi @lcoupe,

Thanks for filing the issue. The behavior you are seeing here is because of the data being returned by the provider, and there unfortunately is not much we can do in Terraform to prevent this case. Applying the change to the resource should result in a state that matches the configuration exactly, but for some reason the provider is still returning a value for the `workload_identity_config` block. 

I'm going to transfer this to the provider in case there is something they can do internally to fix the situation.

Thanks!
