### ISSUE TITLE
Elastic beanstalk support

### ISSUE THREAD

**Issue by stinky22** [hashicorp/terraform#2799]
Elastic beanstalk has advantages over ECS, in particular it's easy to configure autoscaling. Elastic beanstalk support in terraform would be great.

**Comment by nathanpalmer** [comment]
Yes. Just recently started building a new stack but had to go completely on CloudFormation due to the lack of support for Elastic Beanstalk (Application, ConfigurationTemplates and Environments.)

**Comment by phinze** [comment]
Good news on this front, we've got some work in this area that should be showing up as a PR soon. Stay tuned! :radio:

**Comment by rajinders** [comment]
I am starting a new project in 2 weeks. We are planning on using elastic beanstalk, RDS, VPC etc.
We will like to use Terraform but we will need elastic beanstalk support.
It will be great if you can tell me when terraform will support elastic beanstalk.
we need to know now to decide if we need to ramp up on cloud formation. Given a choice between leveraging cloud formation or terraform we prefer using terraform.

**Comment by rvangraan** [comment]
Hey @phinze - any chance that we could have a look at what you are doing RE: Elastic Beanstalk? We've just started using Terraform, and the one thing we desperately needs is support for Beanstalk.

**Comment by radeksimko** [comment]
@rvangraan See https://github.com/hashicorp/terraform/pull/3157

**Comment by jgwmaxwell** [comment]
That's awesome - we've been auditing Terraform too and was hoping to use EB. Do you know how quickly that PR is likely to get merged in?

**Comment by bkconrad** [comment]
I've also been waiting anxiously for EB support. I've been lurking this and #3157 for about three weeks. No rush, but this is definitely something I'm looking forward to :)

**Comment by jgwmaxwell** [comment]
Very happy to contribute if there's anything that can get that PR unstuck.

**Comment by catsby** [comment]
Hello all – https://github.com/hashicorp/terraform/pull/3157 has languished a bit and I welcome any contributions too it. I admit that, not using Elastic Beanstalk myself, some of the concepts evaded me for a bit. I changed my focus in favor of getting Terraform v0.6.4 out. 

I would love any reviews of #3157 from people who use Beanstalk. If you can, checkout the branch and try to use it. What are we missing? What's not quite right? Please feel free to comment there so we can keep tabs.

Thanks!

**Comment by juniorplenty** [comment]
@catsby Is there a plan for getting that integrated into a release?

**Comment by catsby** [comment]
I'm targeting this PR for the v0.7.0 release, though I do not have a date for that. There by be a release between now and then anyway... sorry :frowning: 

I've been hung up with some other things this week. I'll make Beanstalk a priority next week. Thanks for the patience!

**Comment by therealjessesanford** [comment]
I would also love to see beanstalk support! Thanks!

**Comment by jrab89** [comment]
I've been using Terraform to manage RDS, ElastiCache, and security groups. It would be awesome if I could also it to manage my app tier which is in Beanstalk.

@catsby is there anything I could do to help with this feature?

**Comment by adamenger** [comment]
Would love this functionality and also willing to contribute code/testing. EB is the only "handcrafted" piece of our infrastructure that's left to terraform :zap:

**Comment by ortenheim** [comment]
+1. Any update on this?

**Comment by hoshy** [comment]
Hi @catsby, any updates on this?

**Comment by veqryn** [comment]
+1

**Comment by chris-redekop** [comment]
+1

**Comment by akitanak** [comment]
+1

**Comment by ianlgibbons** [comment]
+1

**Comment by catsby** [comment]
Today I merged https://github.com/hashicorp/terraform/pull/3157 with initial support for Elastic Beanstalk. Let us know what you think!

**Comment by armenr** [comment]
+1

**Comment by yonatannn** [comment]
+1
