### ISSUE TITLE
AWS Provider Coverage

### ISSUE THREAD

**Issue by pearkes** [hashicorp/terraform#28]
### AWS Provider Coverage

View this spreadsheet for a near-time summary of AWS resource coverage. If there's a resource you would like to see coverage for, just add your GitHub username to next to the resource. We will use the number of community upvotes in the spreadsheet to help prioritize our efforts.

https://docs.google.com/spreadsheets/d/1yJKjLaTmkWcUS3T8TLwvXC6EBwNSpuQbIq0Y7OnMXhw/edit?usp=sharing

**Comment by drnic** [comment]
Created an issue for "AWS EBS volume support" https://github.com/hashicorp/terraform/issues/746

**Comment by joescii** [comment]
Created ticket for AWS Route 53 ALIAS A Record support. #747

**Comment by Tokynet** [comment]
+1 for EBS support.

Funny, I was just trying this out today under block_device and it failed.

I think it should work just like the snapshot_id option.

-Miguel

**Comment by buth** [comment]
@drnic @Tokynet This should work using the `block_device` option.

**Comment by Tokynet** [comment]
What option though? I'm writing on my phone and can't paste the code snip.

Block_device {
Device_name = "/dev/sdb"
Volume_type = "gp2"
Volume_size = "50"
}

**Comment by netors** [comment]
As a user who wants to implement private DNS on an internal VPC with Terraform, I need the following:

First, I need to be able to associate a hosted zone to a VPC: http://docs.aws.amazon.com/Route53/latest/APIReference/API_AssociateVPCWithHostedZone.html
(maybe adding the vpc_id to the aws_route53_zone resource?)

Second, I need to create a DHCP Option Set: http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-CreateDhcpOptions.html

Then I need to associate the DHCP Option Set to a VPC:
http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-AssociateDhcpOptions.html
(maybe this can also be done in a new aws_dhcp_option_set resource using a vpc_id)

(reference: http://aws.amazon.com/about-aws/whats-new/2014/11/05/amazon-route-53-now-supports-private-dns-with-amazon-vpc/)

**Comment by teancom** [comment]
@Tokynet Device name should just be 'sdb' (or possibly 'xvdb') - it should not include the /dev/. At least, that's what worked for me.

**Comment by buth** [comment]
@Tokynet That code block, within an `aws_instance` block, should create a new EBS volume and attatch it. (Note: it does not mount it.)

**Comment by Tokynet** [comment]
The code I have works and as mentioned here, it creates a new EBS volume
every time.

I would like to have a specific EBS volume mounted every time I bring this
instance up. I would make the config not destroy the volume on instance
termination.

What I want to see is the config (option) that allows me to specify the
volume NOT the snapshot (I have seen and used that one but have to
constantly update the terraform config since we have to make new snapshots
as we update the packages on that volume).

-Miguel

**Comment by likwid** [comment]
+1 on egress. I am really impressed with Terraform otherwise.

**Comment by neurogenesis** [comment]
+1 for tags, with the additional requirement for a means of applying tags to instances created via autoscaling groups. some use cases:

- "name" tag for organization & filter in AWS UI
- apply tags for audit / accounting / billing purposes (customer=acme, offering=..., department=..., etc.)

in looking at https://www.terraform.io/docs/providers/aws/r/instance.html, it looks like this might apply only to single instances.

in looking at https://www.terraform.io/docs/providers/aws/r/autoscale.html, there's no way to specify tags.

info about tags and autoscaling groups:

http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/ASTagging.html

**Comment by ojongerius** [comment]
Could you please add VPN support ( #551 ) to this one?

**Comment by davedash** [comment]
RDS encryption at rest.

**Comment by plombardi89** [comment]
VPC peering +1 and IAM +1

Those two are holding us back from using this over Cloud Formation at the moment (VPC peering more so).

**Comment by bhourigan** [comment]
I'd like to add auto scaling group policy to this list, such as documented here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html

**Comment by rodrickbrown** [comment]
Any plans to move to aws-go-sdk instead?

**Comment by knuckolls** [comment]
It wasn't until I saw this post that I understood what aws-go-sdk was. If it's going to be amazon's official go client then i'll :+1: moving to that eventually.

https://aws.amazon.com/blogs/aws/coming-soon-aws-sdk-for-go/

**Comment by phinze** [comment]
@robparrott yep that is indeed the plan!

**Comment by jespada** [comment]
Enhancement: https://github.com/hashicorp/terraform/issues/938

**Comment by ryanking** [comment]
Can we add enabling ELB access logs to this one?

**Comment by nevins-b** [comment]
#856 adds support for egress rules but requires a pull request to the upstream goamz to be merged first

**Comment by david-latham** [comment]
:+1: for private dns in route 53

**Comment by d3v1an7** [comment]
`aws_autoscaling_group`

:+1: Add/edit tags (also modify `Tag New Instances`)
:+1: Add/edit scaling policies

:heart:

**Comment by nevins-b** [comment]
So I have a pull request to support ELB policies in goamz (https://github.com/mitchellh/goamz/pull/224/files). Now I'm looking for recommendations of how to implement these in terraform.

**Comment by mbrevoort** [comment]
Support for ECS would be great

**Comment by toddmichael** [comment]
+1 for VPC peering.  Man I love me some Terraform!  Bravo Hashicorp.

**Comment by Tokynet** [comment]
Tagging of ELBs. 
Currently we tag all resources that belong to a specific application/team with Tags.

**Comment by sage-oli-wood** [comment]
+1 to @Tokynet's tagging all of the things!

**Comment by toddmichael** [comment]
+1 for route53 PrivateZone support.  Love me some Terraform.  Keep up the great work Hashicorp! :+1:

**Comment by estahn** [comment]
:+1:

**Comment by jessem** [comment]
Also would love:
:+1: Add/edit tags (also modify Tag New Instances)
:+1: Add/edit scaling policies

**Comment by jaxxstorm** [comment]
Any news on DHCP option sets?

**Comment by c4milo** [comment]
@pearkes @mitchellh is anyone working on getting Route53 aliases working? I'm willing to collaborate on this if no one is working on it.

**Comment by catsby** [comment]
@c4milo I don't believe anyone is tackling it at present. The migration to `aws-sdk-go` just wrapped up and `goamz` was removed this morning. I'll be working on bug fixes for a bit, so if you want to add new things by all means :smile:

**Comment by c4milo** [comment]
@catsby ok, I will make some time this week to implement that then. Thanks!

**Comment by catsby** [comment]
Thank you @c4milo :+1:

**Comment by KFishner** [comment]
@bhourigan +1 for autoscaling group policy
http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_PutScalingPolicy.html

**Comment by ryanking** [comment]
Is is still the best place to track changes for AWS? Is someone creating issues from the comments left here?

**Comment by wazoo** [comment]
If we are still tracking here, I would like to request the following:

ELB Tags
S3 Bucket Tags
RDS Instance Tags / Snapshot Tags
Encrypted RDS (Even without KMS support, just providing key ARN)
EC2 Tenancy
Placement Groups
VPC VPN Configuration
EBS Encryption (when volume creation is created)

**Comment by Tokynet** [comment]
Yeah, I'm really stuck without the tags for elb and rds (basically all
resources that allow them) since we use tags to filter
viewa/config/reports.

Thanks for all the efforts :)
-Miguel

**Comment by nevir** [comment]
Also curious/interested about ECS integration

**Comment by rhiann0n** [comment]
Please add custom ICMP types and codes to security group options.

Example
Ingress ICMP traceroute from 0.0.0.0/0
Ingress ICMP echorequest from 0.0.0.0/0
Ingress ICMP echo-reply from 0.0.0.0/0
Ingress ICMP Destination Unreachable from 0.0.0.0/0
Ingress ICMP Time Exceeded from 0.0.0.0/0
Ingress ICMP Parameter Problem: Bad header from 0.0.0.0/0

I saw what looked like the logic for icmp_code and icmp_types in the source code but I'm not sure that its been implemented yet.

It is allowable through AWS CLI.

Also, here is a good reference:
http://www.nthelp.com/icmp.html

Please and thank you.

**Comment by rlister** [comment]
+1 for `Network ACL subnet association (you can associate one ACL with multiple subnets)`.

This omission makes it impossible to use Terraform for any non-trivial VPC work. It looks like a fix was provided in #644 but that issue was closed without merge, possibly for backward-compatibility reasons. Should we reopen that issue?

**Comment by ketzacoatl** [comment]
+1 for ECS support - https://aws.amazon.com/blogs/aws/ec2-container-service-ready-for-production-use/ and https://aws.amazon.com/ecs/details/ for more. This already integrates well with ELB,

**Comment by CpuID** [comment]
+1 for ECS, now that it's GA. Would be a nice addition.

Nathan Sullivan

**Comment by c4milo** [comment]
@catsby, I put off writing support Route53 alias records to focus on DHCP Option Set support as that is more pressing on my side.

**Comment by andreijs** [comment]
Also route 53 does not support internal vpc associations

**Comment by c4milo** [comment]
@catsby, @phinze, I'm almost done with DHCP Options support but Terraform is crashing on me. May I have a hand? https://github.com/managedbyq/terraform-1/tree/aws_dhcp_options and https://gist.github.com/c4milo/4c68e16a33fdfe7e8380

**Comment by c4milo** [comment]
@catsby @phinze I got unstuck \o/. I will be sending a PR shortly.

**Comment by nevir** [comment]
Just +1ing for ElastiCache's `CreateReplicationGroup` (also added to spreadsheet)

**Comment by phinze** [comment]
@nevir Part of the motivation for the spreadsheet is to collect feedback on desired features while avoiding the need to send a github notification for a "+1" to the 77 folks on this thread + 176 watchers on the repo. In other words, if you got your name on the spreadsheet, no need to post here. :grinning: 

That being said, if anybody has a specific use case or details they'd like to share or discuss further, please feel free to open a fresh issue and link it from the "Relevant Issues" column on the spreadsheet.

**Comment by catsby** [comment]
Hello friends –

With regret, I'm going to close this issue. The spreadsheet was a great idea but ultimately mapping api calls to valuable features in Terraform didn't quite pan out. 

For now we'll be tracking individual feature requests in their own GitHub issues. I realize this may lead to duplication, but I'll do the best I can to stay on top of things.

Please let know if you have any questions, comments, concerns et. al. Thanks for helping out here :smile:
