### ISSUE TITLE
Fails updating resource after updating userdata attached to launch config

### ISSUE THREAD

**Issue by aavileli** [hashicorp/terraform#2800]
terraform 0.6 

After editing user data which is associated to a launch config the resource tries to delete the launch config instead of creating a new one and associating it with the current ASG

terraform plan 

```
-/+ aws_launch_configuration.asg_lc_conf
    associate_public_ip_address: "false" => "0"
    ebs_block_device.#:          "0" => "<computed>"
    ebs_optimized:               "false" => "<computed>"
    enable_monitoring:           "true" => "<computed>"
    iam_instance_profile:        "S-instance-profile-DefaultInstanceProfile-1A6SWVVDER" => "S-instance-profile-DefaultInstanceProfile-1A6SWVVDER"
    image_id:                    "ami-3ff5037b" => "ami-3ff5037b"
    instance_type:               "t2.micro" => "t2.micro"
    key_name:                    "s-us-west-1" => "s-us-west-1"
    name:                        "lc_web_config" => "lc_web_config"
    root_block_device.#:         "0" => "<computed>"
    security_groups.#:           "1" => "1"
    security_groups.2204770009:  "sg-86e373e3" => "sg-86e373e3"
    user_data:                   "aa82cf10c271a428f8acd708daae1b8567bbf773" => "8dbdd028e5a336966bb938854c94a908a316d264" (forces new resource)

Plan: 0 to add, 9 to change, 0 to destroy.
```

terraform apply 

```
* ResourceInUse: Cannot delete launch configuration lc_web_config because it is attached to AutoScalingGroup ASG-web-test2
	status code: 400, request id: [997ab4f8-2f6b-11e5-8883-1fe3bb688569]
Error applying plan:

1 error(s) occurred:

* ResourceInUse: Cannot delete launch configuration lc_web_config because it is attached to AutoScalingGroup ASG-web-test2
	status code: 400, request id: [997ab4f8-2f6b-11e5-8883-1fe3bb688569]
```

**Comment by catsby** [comment]
Hey @aavileli – Launch Configurations are kind of tricky. We've found the best way to work with them is to _not_ supply a `name`, and to use the `lifecycle` block:

```javascript
resource "aws_launch_configuration" "foobar" {
  [...]
  image_id = ""
  instance_type = ""
  lifecycle {
    create_before_destroy = true
  }
}
```

Omitting the name allows Terraform to auto-generate a unique name for you, which avoids name conflicts when you try to create the new, update Launch Configuration. 

Once the new one is successfully created, your Auto Scaling Group gets updated (assuming you're referencing it in your configuration file) and the old one can then be destroyed.

Let me know if that works!

**Comment by josh-padnick** [comment]
I independently had issues with modifying Launch Configurations and this seemed to work for me, however I now get issues when attempting to delete Launch Configurations.  Upon running `terraform destroy` I receive:

```
rror creating plan: 3 error(s) occurred:

* Cycle: module.prod-vpc.module.nat.aws_iam_role.nat (destroy), module.prod-vpc.module.nat.aws_iam_role.nat, module.prod-vpc.module.nat.aws_iam_instance_profile.nat, module.prod-vpc.module.nat.aws_launch_configuration.nat, module.prod-vpc.module.nat.aws_launch_configuration.nat (destroy), module.prod-vpc.module.nat.aws_iam_instance_profile.nat (destroy)
* Cycle: module.mgmt-vpc.module.nat.aws_iam_role.nat, module.mgmt-vpc.module.nat.aws_iam_instance_profile.nat, module.mgmt-vpc.module.nat.aws_launch_configuration.nat, module.mgmt-vpc.module.nat.aws_launch_configuration.nat (destroy), module.mgmt-vpc.module.nat.aws_iam_instance_profile.nat (destroy), module.mgmt-vpc.module.nat.aws_iam_role.nat (destroy)
* Cycle: module.stage-vpc.module.nat.aws_iam_role.nat, module.stage-vpc.module.nat.aws_iam_instance_profile.nat, module.stage-vpc.module.nat.aws_launch_configuration.nat, module.stage-vpc.module.nat.aws_launch_configuration.nat (destroy), module.stage-vpc.module.nat.aws_iam_instance_profile.nat (destroy), module.stage-vpc.module.nat.aws_iam_role.nat (destroy)
```

**Comment by aavileli** [comment]
yes I have the same issue if I add the lifecycle policy I cant delete the resource I get the following error

Error creating plan: 1 error(s) occurred:

* Cycle: aws_launch_configuration.asg_lc_conf (destroy), aws_security_group.default (destroy), aws_security_group.default, aws_launch_configuration.asg_lc_conf, aws_autoscaling_group.asg

**Comment by josh-padnick** [comment]
@aavileli I temporarily resolved this by manually destroying my Auto Scaling Group, Launch Configuration, and VPCs.  Then I did `terraform destroy` once or twice more until it succeeded.

**Comment by aavileli** [comment]
@josh-padnick I don't like the solution as I plan to integrate this process in jenkins. So temporarily before calling destroy I am removing the life cycle policy from the launch config and then deleting which works now. Hope a proper solution is implemented have to grep and sed to do the work around

**Comment by josh-padnick** [comment]
@aavileli I hear ya. Right now I'm setting up greenfield infrastructure, but before going live with it, I plan on diving in deep to understand how Terraform's resource graph works, why @phinze recommends what he does in #2359, and generally how to build terraform templates without running into these issues.

It sounds like additional docs on best practices here would be quite helpful.

**Comment by catsby** [comment]
Hey all – I'm going to go ahead and close this issue, as it does not seem to be an actual bug in Terraform but an issue with dependencies on AWS. For updating Launch Configurations, we recommend not supplying a name and using the `create_before_destroy` as I mentioned above.

Regarding the cycles, we've update the [Configuring Resources][1] documentation to explain this, but the gist is that for any resource with `create_before_destroy` that also depends on another resource, that dependency must also have `create_before_destroy`.

For example, in the config shared above:

```javascript
resource "aws_security_group" "secure_api" {
    name = "terra-secure-api"
    description = "Api instances security group"
    vpc_id = "${var.vpc_main_id}"
    [...]
    tags {
        Name = "terra-secure-api"
    }
}

resource "aws_launch_configuration" "lc_api" {
    name = "terra-lc-api"
    [...]
    security_groups = ["${aws_security_group.secure_api.id}"]

    lifecycle {
        create_before_destroy = true
    }
}
```

Here `aws_launch_configuration.lc_api` and depends on `aws_security_group.secure_api`. Because `aws_launch_configuration.lc_api` uses `create_before_destroy`, `aws_security_group.secure_api` must now also use `create_before_destroy`.

In your example @josh-padnick , your Launch Configuration likely depends on another resource that too needs to be `create_before_destroy`. We realize this is not ideal and are hoping to address this need in the future. 

Sorry for the trouble! 

[1]: https://terraform.io/docs/configuration/resources.html
