### ISSUE TITLE
logging errors

### ISSUE THREAD

**Issue by failshell** [hashicorp/terraform#2801]
~~~ text
Error refreshing state: 2 error(s) occurred:

* NoSuchHostedZone: The specified hosted zone does not exist.
	status code: 404, request id: [7a31f214-2fa9-11e5-be68-61e8c41f077e]
* NoSuchHostedZone: The specified hosted zone does not exist.
	status code: 404, request id: [7a343bc5-2fa9-11e5-ad88-3f2443d13dbd]
~~~

This is a typical error one gets from Terraform. It would be really neat if it could give more info, like in this instance, which hosted zone are we talking about?

Telling the user which resource failed would be awesome.

**Comment by catsby** [comment]
Hey @failshell – totally agree here, thanks for writing in. I _think_ this is happening somewhere in Route 53 Records, do you have a configuration and steps that reproduce this? That will help me track down and fix this specific issue.

Overall, being more verbose _everywhere_ is of course what we should do, but tracking down all the holes is difficult. If you can help me track this one and patch it, we'll be one step closer :smile: 

Even if you don't have a config for me handy, I'll take a stab at it. Thanks!

**Comment by catsby** [comment]
I've managed to reproduce this by simply deleting the record and zone in the AWS console, I'll fix this to be more specific :smile:

**Comment by catsby** [comment]
#2809 should add some clarity here. As far as being more clear _everywhere_, that's going to take some time and diligence on my part but I'll do my best :smile:

**Comment by failshell** [comment]
![](https://media0.giphy.com/media/MCKQEmHkUyGf6/200.gif)

**Comment by radeksimko** [comment]
I agree that error reporting across different commands is not exactly consistent and helpful and AWS API errors are not making it any better.
I just proposed something in #2815

**Comment by catsby** [comment]
Hey all – #2815 was merged and the errors are more clear now. If you think there's still room for improvement let us know. Thanks!
