### ISSUE TITLE
Upload GPG key onto distinct domain

### ISSUE THREAD

**Issue by maltfield** [hashicorp/terraform#28013]
Hi,

Can the hashiorp team please upload their gpg public keys to a keyserver to facilitate its users in cross-checking the validity of the key when importing it for the first-time?

(this affects terraform, but the scope of this issue is hashicorp-wide. If there is a more appropriate place for me to open this issue, please let me know)

I downloaded the hashicorp gpg key from the following URL:

 * https://apt.releases.hashicorp.com/gpg

That gave me a key with fingerprint `E8A0 32E0 94D8 EB4E A189  D270 DA41 8C88 A321 9F7B` and a uid for `HashiCorp Security (HashiCorp Package Signing) <security+packaging@hashicorp.com>`

```
user@personal:~$ gpg --list-keys hashicorp
pub   rsa4096/0xDA418C88A3219F7B 2020-05-07 [SC]
      Key fingerprint = E8A0 32E0 94D8 EB4E A189  D270 DA41 8C88 A321 9F7B
uid                   [ unknown] HashiCorp Security (HashiCorp Package Signing) <security+packaging@hashicorp.com>
sub   rsa4096/0x59146B181EDA18DE 2020-05-07 [E]

user@personal:~$ 
```

But then I went to validate that this key was indeed correct, and I was stunned to find that it isn't listed on the sks keyservers or the better/replacement keyserver https://keys.openpgp.org/

 * https://keys.openpgp.org/search?q=security%2Bpackaging%40hashicorp.com

Moreover, there's no non-self signatures on the key

```
user@disp7118:~$ cat hashicorp.gpg | gpg --list-packets
gpg: keybox '/home/user/.gnupg/pubring.kbx' created
# off=0 ctb=99 tag=6 hlen=3 plen=525
:public key packet:
	version 4, algo 1, created 1588874982, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: DA418C88A3219F7B
# off=528 ctb=b4 tag=13 hlen=2 plen=81
:user ID packet: "HashiCorp Security (HashiCorp Package Signing) <security+packaging@hashicorp.com>"
# off=611 ctb=89 tag=2 hlen=3 plen=590
:signature packet: algo 1, keyid DA418C88A3219F7B
	version 4, created 1588874982, md5len 0, sigclass 0x13
	digest algo 8, begin of digest af d6
	hashed subpkt 33 len 21 (issuer fpr v4 E8A032E094D8EB4EA189D270DA418C88A3219F7B)
	hashed subpkt 2 len 4 (sig created 2020-05-07)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 2)
	hashed subpkt 21 len 5 (pref-hash-algos: 10 9 8 11 2)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (keyserver preferences: 80)
	subpkt 16 len 8 (issuer key ID DA418C88A3219F7B)
	data: [4095 bits]
# off=1204 ctb=b9 tag=14 hlen=3 plen=525
:public sub key packet:
	version 4, algo 1, created 1588874982, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 59146B181EDA18DE
# off=1732 ctb=89 tag=2 hlen=3 plen=566
:signature packet: algo 1, keyid DA418C88A3219F7B
	version 4, created 1588874982, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 95 e7
	hashed subpkt 33 len 21 (issuer fpr v4 E8A032E094D8EB4EA189D270DA418C88A3219F7B)
	hashed subpkt 2 len 4 (sig created 2020-05-07)
	hashed subpkt 27 len 1 (key flags: 0C)
	subpkt 16 len 8 (issuer key ID DA418C88A3219F7B)
	data: [4091 bits]
user@disp7118:~$ 
```

In-case it isn't clear, there's significant security risks with the X.509 security model used by my browser (or curl, etc) when downloading your gpg key from `hashicorp.com`. HSTS is great when re-visiting a website, but the *first* time I visit `hashicorp.com`, it wouldn't be too difficult for a malicious actor to MITM the connection with a cert signed by the [extremely large list](https://ccadb-public.secure.force.com/mozilla/RemovedCACertificateReport) of CAs trusted by popular browsers -- which includes, for example, organizations controlled by State Actors who have a history of human rights abuses. And, historically, included many CAs that had to be [removed](https://ccadb-public.secure.force.com/mozilla/RemovedCACertificateReport) because the CA's private key was stolen or was otherwise signing certificates that they shouldn't have been. If any cert is signed by any of those CAs, a MITM actor can send the wrong gpg key to a client, and the browser will show no indication of wrong-doing.

...not to mention the fact that hashicorp's DNS or infrastructure could be hacked and there's no other domain to cross-reference.

As suggested above, the solution to this problem is:

1. publishing your public key on other domains in addition to `hashicorp.com`, such as the `keys.openpgp.org` keyserver

1. signing your public key with other gpg keys that are well integrated in the web of trust

The second item is a more complicated and long-term solution, so this issue is a feature request to upload your gpg key to the `keys.openpgp.org` keyserer, which should only take a few minutes to do. You'll need to click a link sent to the uid of the key (`security+packaging@hashicorp.com`) as described here https://keys.openpgp.org/about

I also recommend that yousetup a keybase account and uses their official twitter account to publicly list the fingerprint of their gpg key, but I'd be happy to create a distinct issue for this

 * https://keybase.io/docs/proof_integration_guide
 * https://twitter.com/micahflee/status/908390382882373632

**Comment by maltfield** [comment]
Oh boy. I see hashicorp *does* have a keybase account with a gpg key (`91A6 E7F8 5D05 C656 30BE  F189 5185 2D87 348F FC4C`) listed, but it's in conflict with what's available on `hashicorp.com`

 * https://keybase.io/hashicorp

It looks like the key listed on your keybase account is for `HashiCorp Security <security@hashicorp.com>`

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFMORM0BCADBRyKO1MhCirazOSVwcfTr1xUxjPvfxD3hjUwHtjsOy/bT6p9f
W2mRPfwnq2JB5As+paL3UGDsSRDnK9KAxQb0NNF4+eVhr/EJ18s3wwXXDMjpIifq
fIm2WyH3G+aRLTLPIpscUNKDyxFOUbsmgXAmJ46Re1fn8uKxKRHbfa39aeuEYWFA
3drdL1WoUngvED7f+RnKBK2G6ZEpO+LDovQk19xGjiMTtPJrjMjZJ3QXqPvx5wca
KSZLr4lMTuoTI/ZXyZy5bD4tShiZz6KcyX27cD70q2iRcEZ0poLKHyEIDAi3TM5k
SwbbWBFd5RNPOR0qzrb/0p9ksKK48IIfH2FvABEBAAG0K0hhc2hpQ29ycCBTZWN1
cml0eSA8c2VjdXJpdHlAaGFzaGljb3JwLmNvbT6JAU4EEwEKADgWIQSRpuf4XQXG
VjC+8YlRhS2HNI/8TAUCXn0BIQIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAK
CRBRhS2HNI/8TJITCACT2Zu2l8Jo/YLQMs+iYsC3gn5qJE/qf60VWpOnP0LG24rj
k3j4ET5P2ow/o9lQNCM/fJrEB2CwhnlvbrLbNBbt2e35QVWvvxwFZwVcoBQXTXdT
+G2cKS2Snc0bhNF7jcPX1zau8gxLurxQBaRdoL38XQ41aKfdOjEico4ZxQYSrOoC
RbF6FODXj+ZL8CzJFa2Sd0rHAROHoF7WhKOvTrg1u8JvHrSgvLYGBHQZUV23cmXH
yvzITl5jFzORf9TUdSv8tnuAnNsOV4vOA6lj61Z3/0Vgor+ZByfiznonPHQtKYtY
kac1M/Dq2xZYiSf0tDFywgUDIF/IyS348wKmnDGjuQENBFMORM0BCADWj1GNOP4O
wJmJDjI2gmeok6fYQeUbI/+Hnv5Z/cAK80Tvft3noy1oedxaDdazvrLu7YlyQOWA
M1curbqJa6ozPAwc7T8XSwWxIuFfo9rStHQE3QUARxIdziQKTtlAbXI2mQU99c6x
vSueQ/gq3ICFRBwCmPAm+JCwZG+cDLJJ/g6wEilNATSFdakbMX4lHUB2X0qradNO
J66pdZWxTCxRLomPBWa5JEPanbosaJk0+n9+P6ImPiWpt8wiu0Qzfzo7loXiDxo/
0G8fSbjYsIF+skY+zhNbY1MenfIPctB9X5iyW291mWW7rhhZyuqqxN2xnmPPgFmi
QGd+8KVodadHABEBAAGJATwEGAECACYCGwwWIQSRpuf4XQXGVjC+8YlRhS2HNI/8
TAUCXn0BRAUJEvOKdwAKCRBRhS2HNI/8TEzUB/9pEHVwtTxL8+VRq559Q0tPOIOb
h3b+GroZRQGq/tcQDVbYOO6cyRMR9IohVJk0b9wnnUHoZpoA4H79UUfIB4sZngma
enL/9magP1uAHxPxEa5i/yYqR0MYfz4+PGdvqyj91NrkZm3WIpwzqW/KZp8YnD77
VzGVodT8xqAoHW+bHiza9Jmm9Rkf5/0i0JY7GXoJgk4QBG/Fcp0OR5NUWxN3PEM0
dpeiU4GI5wOz5RAIOvSv7u1h0ZxMnJG4B4MKniIAr4yD7WYYZh/VxEPeiS/E1CVx
qHV5VVCoEIoYVHIuFIyFu1lIcei53VD6V690rmn0bp4A5hs+kErhThvkok3c
=+mCN
-----END PGP PUBLIC KEY BLOCK-----
```

Please add your repo signing key to your keybase account. That should be an easy way to add a second domain for users to verify the authenticity of your key out-of-band.

**Comment by jbardin** [comment]
Hi @maltfield 

Thanks for the information. The contact point for security related concerns is security@hashicorp.com (https://www.hashicorp.com/security#vulnerability-reporting).

The Terraform project itself does not control the Hashicorp signing keys, and the security team can coordinate with the teams responsible for various aspects of the release process as needed.

Thanks!

**Comment by maltfield** [comment]
I emailed them 10 days ago and got no response.

**Comment by milescrabill** [comment]
Hi Michael, sorry for the delayed response.

Regarding your point about conflicting GPG keys, there are two keys at play here: the `security@hashicorp.com` key, and the `security+packaging@hashicorp.com` key. The latter was created in May of last year, and I understand your skepticism towards it. We should have better communicated our usage of that key.

We have added the `security+packaging@hashicorp.com` key to keys.openpgp.org, see [here](https://keys.openpgp.org/vks/v1/by-fingerprint/E8A032E094D8EB4EA189D270DA418C88A3219F7B). The key has been signed by `security@hashicorp.com`.`security@hashicorp.com` is also available on keys.openpgp.org, see [here](https://keys.openpgp.org/vks/v1/by-fingerprint/91A6E7F85D05C65630BEF18951852D87348FFC4C).

The key fingerprints for both keys are listed on the Hashicorp Security page.

- `security@hashicorp.com` is [here](https://www.hashicorp.com/security#secure-communications) and is intended for messaging the Hashicorp security team and verifying SHASUM files for releases.
- `security+packaging@hashicorp.com` is listed [here](https://www.hashicorp.com/security#linux-package-checksum-verification) and is used to sign apt / rpm packages.

Our Keybase account only has the `security@hashicorp.com` key as that is the key that messages to the security team should use for encryption (the packaging key has a different internal audience).

Thank you for your feedback - please let me know if you have any more questions.
