### ISSUE TITLE
Can't redirect or pipe terraform console input on Windows

### ISSUE THREAD

**Issue by SadokLadhari** [hashicorp/terraform#28027]
### Terraform Version

```
Terraform v0.14.3
```

### Terraform Configuration Files

```sh
$ echo "1 + 5" | terraform console
```

### Expected Behavior

Should return 6
### Actual Behavior

I have a Terraform Console without any execution !!
### Steps to Reproduce

> $ echo "1 + 5" | terraform console
### Additional Context

Running the command in MacOs or Linux distribution( Ubuntu for eg) works fine but in Windows does not!
### References

- https://www.terraform.io/docs/cli/commands/console.html
- May be related to [this issue](https://github.com/hashicorp/terraform/issues/18242) but I'm not sure !

**Comment by apparentlymart** [comment]
Hi @SadokLadhari!

The misbehavior you described here is familiar to me from working on #27487, where I noticed that Terraform had previously been trying to work around some limitations of the Windows API but doing so incorrectly, causing Terraform to always write its output to the main console even if the output is redirected elsewhere. (I left some technical details in a comment on #18242, for anyone who's interested in that.)

Although that quirk wasn't the focus of my work on #27487, I did make a change intended to fix the misbehavior you saw, and so I think if you try what you tried here on Terraform v0.15.0-beta1 you will see it work on WIndows just as it works on other platforms.

Would you give that a try and let me know if it works for you? Thanks!

**Comment by mildwonkey** [comment]
I'm going to close this, since there hasn't been a response, but if you are still experiencing a problem please open a new issue or ask in the [community forums](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
