### ISSUE TITLE
Error: key must not start with '/' (Error should print key)

### ISSUE THREAD

**Issue by jeffdyke** [hashicorp/terraform#28031]
I will happily commit some code when i can, but this block of code, should emit the key that its failing on allowing a person to search source code.  I'm in the process of a migration from terragrunt to terraform, which should not matter other than that is how i found it. Since it was not used terragrunt may have done something with the `data "terraform_remote_state"` block that was not called anywhere. Not sure, but adding the key to the error message would be dope.  The fix is simple, but it may take me a while to get the build up.   I'll be following my own gotcha!

https://github.com/hashicorp/terraform/blob/e5538693ced0dc42bb90a3919875cb8bbd625736/backend/remote-state/s3/backend.go#L30-L42

Thanks for the great product!

**Comment by gdavison** [comment]
This has been addressed in changes made for v1.6
