### ISSUE TITLE
Error: value must be known when using GKE module, google_service_account resource 

### ISSUE THREAD

**Issue by justinturpin** [hashicorp/terraform#28061]
### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v3.59.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
provider "google" {
  project = "wesearch-prod"
  region  = "us-west1"
}

data "google_client_config" "default" {}

# module to create gke cluster
module "gke" {
  source = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"

  project_id               = "wesearch-prod"
  name                     = "test-jt-cluster"
  regional                 = true
  region                   = "us-west1"
  zones                    = ["us-west1-a"]
  network                  = "wesearch-prod-vpc"
  subnetwork               = "wesearch-prod-gke"
  ip_range_pods            = "gke-gke-cluster-1-pods-test"
  ip_range_services        = "gke-test-gke-cluster-1-services"
  create_service_account   = true
  enable_private_nodes     = true
  remove_default_node_pool = true
  kubernetes_version       = "1.18.16-gke.300"

  node_pools = [
    {
      name         = "nodepool-with-min-config"
      min_count    = 1
      max_count    = 2
      disk_size_gb = 50
      disk_type    = "pd-standard"
      image_type   = "COS"
      machine_type = "n1-standard-1"
      auto_repair  = true
      auto_upgrade = true
      preemptible  = false
    },
  ]
}
```

### Debug Output

https://gist.github.com/justinturpin/062e6bb65aa02b27dc95a4cdf92dce2a

### Expected Behavior
Either no error, or a helpful message with context about what value was expected.

### Actual Behavior
When trying to use the GKE private cluster module "terraform-google-modules/kubernetes-engine/google//modules/private-cluster", Terraform gives a "Error: value must be known" error with no context on trying to create the google_service_account.

### Steps to Reproduce
Use full Terraform configuration above in a GCP environment, run `terraform init` and `terraform apply`.

### Additional Context
This can be reproduced using just Terraform, no wrapper script. Running in Pop Os (Ubuntu 20.10).

**Comment by jbardin** [comment]
Hi @justinturpin,

Thanks for filing the issue. I'm not certain what is causing the error yet, but I have a feeling it is related to the google module itself. 0.15 should be able to provide more context into what is happening. Could you see if the latest beta (currently [0.15.0-beta1](https://releases.hashicorp.com/terraform/0.15.0-beta1/)) produces a more reasonable error?

Thanks!

**Comment by justinturpin** [comment]
Thanks for the reply! I have ran with terraform 0.15.0-beta1 and while it does give some additional context, it doesnt seem to be actionable.

Versions of things:

```
Terraform v0.15.0-beta1
on linux_amd64
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v3.59.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

Full debug output:

https://gist.github.com/justinturpin/5b049fcb029e48584e80964696318ee8

Relevant snippet:

```
2021-03-11T12:33:51.104-0800 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/kubernetes/1.13.3/linux_amd64/terraform-provider-kubernetes_v1.13.3_x4 pid=15321
2021-03-11T12:33:51.104-0800 [DEBUG] provider: plugin exited

Error: value must be known

  on .terraform/modules/gke/modules/private-cluster/sa.tf line 39:
  (source code not available)
```

Terraform code at sa.tf, lines 39-44:

```terraform
resource "google_service_account" "cluster_service_account" {
  count        = var.create_service_account ? 1 : 0
  project      = var.project_id
  account_id   = "tf-gke-${substr(var.name, 0, min(15, length(var.name)))}-${random_string.cluster_service_account_suffix.result}"
  display_name = "Terraform-managed service account for cluster ${var.name}"
}
```

**Comment by bharathkkb** [comment]
@jbardin 
It seems to happen due to our recent provider_meta implementation. Below is a small repro. We use a local to interpolate the final string being passed into provider_meta. Without the local, it seems to be working. The current implementation was working in `0.13.5` but seems to break for `0.14.5`.
x-ref: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/843
```tf
variable "_dynamic" {
    default = "foo"
}

locals {
  dynamic_local="example-${var._dynamic}"
}

resource "random_id" "name" {
  byte_length = 8
}

resource "google_storage_bucket" "auto-expire" {
  name          = "test-providermeta-${random_id.name.hex}"
  project       = "YOUR-PROJECT-ID"
  force_destroy = true
}

terraform {
  required_version = ">=0.13"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 3.39.0, <4.0.0"
    }
  }
  provider_meta "google" {
    module_name = "test/${local.dynamic_local}"
  }
}
```

**Comment by bharathkkb** [comment]
Also tested with `0.15.0-beta1` and same error but works if we omit the `local.dynamic_local` and switch to `module_name = "test/${var._dynamic}"` in `provider_meta`.
```
random_id.name: Creating...
random_id.name: Creation complete after 0s [id=87PDlMoDDG4]
google_storage_bucket.auto-expire: Creating...
╷
│ Error: value must be known
│ 
│   on test.tf line 13:
│   (source code not available)
│ 
╵
```

**Comment by jbardin** [comment]
Thanks @bharathkkb, that confirms my suspicion. I have a feeling that `"test/${var._dynamic}"` only works because the provider may be getting `"test/`. The `provider_metas` value is not located in a context which can evaluate arbitrary expressions.

I'm not sure if the implementation was supposed to allow this, or if we are missing validation to prevent it. I'll look into the original proposal to see what we can do from here.
