### ISSUE TITLE
Orchestrate Project

### ISSUE THREAD

**Issue by gvenka008c** [hashicorp/terraform#2808]
Hi Team,

Do you have any project sample on how to Orchestrate multi-tiered application securely on AWS with Docker and Terraform? Thanks.

Thanks,
Govind

**Comment by catsby** [comment]
Hey @gvenka008c –

The best place for questions like this is likely the mailing list, or on IRC

- **IRC:** #terraform-tool on Freenode
- **Mailing list:** https://groups.google.com/group/terraform-tool

There's also a community driven GitHub organization that has example setups:

- https://github.com/terraform-community-modules

Lastly, a quick Google search turned up this guide:

- https://www.airpair.com/aws/posts/ntiered-aws-docker-terraform-guide

Good luck!
