### ISSUE TITLE
Unable to create Linux VM with Extensions

### ISSUE THREAD

**Issue by bhupa20** [hashicorp/terraform#28082]
[crash.log](https://github.com/hashicorp/terraform/files/6139272/crash.log)
Terraform v0.12.8
+ provider.azurerm v1.44.0
+ provider.random v3.1.0

**Comment by jbardin** [comment]
Hi @bhupa20,

This appears to be a crash with v1.44.0 of the azurerm provider.
I suggest seeing if the crash can be reproduced with a current version of the provider, and filing an issue in the azurerm provider's GitHub repository.

Thanks!
