### ISSUE TITLE
terraform-bundle doesn't correctly pull hashicorp/kubernetes and hashicorp/local

### ISSUE THREAD

**Issue by jehutyy** [hashicorp/terraform#28091]
I'm trying to bundle hashicorp/kubernetes and hashicorp/local provider with the following bundle.hcl : 
```
terraform {
  version = "0.13.6"
}

providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
    local = {
      source = "hashicorp/local"
    }
}
```

which result in an archive only containing `terraform` binary. 

I also tried to add other provider which seems to work as the resulting archive correctly contains defined providers.

**Comment by mildwonkey** [comment]
Hi @jehutyy ! I am sorry this isn't working for you, and thank you for reporting it. 

I will take a look at this (this version of terraform-bundle is definitely my fault 😂 ) , but while I do I'm curious to hear your use case for terraform-bundle, if you don't mind sharing. It's slowly being deprecated in favor of the enhanced [provider installation](https://www.terraform.io/docs/cli/config/config-file.html#provider-installation) options, so it helps me to understand how folks are using terraform-bundle so we can make sure all their use cases are met. Up to you, though! Thanks again, and sorry about this!

**Comment by jehutyy** [comment]
Hi @mildwonkey, thank you for your answer. 

Our use case is to provide a set of terraform provider for user to use them in air gap environment.
I read what you linked but I didn't really find that suits the need to download and bundle a set of provider into an installable archive.

I tried a new workflow that seems, I must admit, more flexible than using a "third-party" tool even though it is not really properly a third-party tool.

Anyway, say I would like to export the following provider : 
```
terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
    }
    docker = {
      source = "kreuzwerker/docker"
    }
    nutanix = {
      source = "nutanix/nutanix"
    }
    rke = {
      source = "rancher/rke"
    }
    cobbler = {
      source = "cobbler/cobbler"
    }
  }
}

provider "kubernetes" {}
provider "local" {}
provider "cobbler" {}
provider "rancher2" {}
provider "null" {}
provider "docker" {}
provider "helm" {}
provider "nutanix" {}
provider "rke" {}
```

I could just do `terraform init` and copy resulting `.terraform` to `~user/.terraform.d` and have a user-scope defined set of provider , could I ? 

Or is there a workflow which would be much cleaner that I would not be aware of ?

**Comment by mildwonkey** [comment]
Hi @jehutyy !

I'm both embarrassed and sorry that it took me so long to see your problem - your example config file does not have any versions for those providers, which is required. 

This bundle file works (`"source"` is optional for registry providers; no harm in leaving it in)

```
terraform {
  version = "0.13.6"
}

providers {
    kubernetes = {
      versions = ["2.0.3"]
    }
    local = {
      versions = ["2.1.0"]
    }
}
```

As for alternatives to terraform-bundle: if you take a look at the documentation I linked in the previous comment, the `provider_installation` settings enable you to host the provider binaries you need on a filesystem or network mirror inside your air-gapped environment. The `terraform providers mirror` subcommand (run from a workstation with internet access) downloads the providers you need into a directory layout suitable for use as a mirror (more info [here](https://www.terraform.io/docs/internals/provider-network-mirror-protocol.html)). 

I'll update terraform-bundle so it returns an error if a provider doesn't have versions supplied in the bundle file, to save us both this headache in the future 😂

**Comment by jehutyy** [comment]
Hi @mildwonkey,

thank you very much for your answer, be reassured that I'm in no way bothered ;)

I'll definitely have a look at both of these solutions. 

In any case thank you for your involvement, I think I'll stick to the new method with terraform providers mirror as it seems that this is the new canonical way to do things ^_^
