### ISSUE TITLE
State output is invalidated randomly

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/terraform#28102]
### Terraform Version
```
0.14.7
```

### Expected Behavior

Terraform should always output a deterministic set of state outputs, as long as they are not altered by any operation.

### Actual Behavior

Terraform sometimes invalidates the output, which requires a new plan+apply to recreate the output, making other states that depend on it crash

### Additional Context

Output is the arn of the s3 bucket that terraform is using for its state backend.

**Comment by alisdair** [comment]
Hi @dimisjim, thanks for reporting this. Unfortunately without the ability to reproduce what you're seeing, we can't investigate the problem and fix it.

Can you add a small Terraform configuration and some steps to demonstrate this issue, so that we can proceed? Thanks!

**Comment by dimisjim** [comment]
Hey @alisdair 

It's a bit hard to tell you about a deterministic way of reproducing this.
The issue occurs with outputs on the state level, that are generated in turn via an output of a custom module, which we use to create s3 buckets.

This s3 bucket represents the S3 state backend, so it looks like this:
```
module "terraform-state" {
  source               = "git@github.com:<org>/<repo-name>.git//s3_bucket?ref=1.0.0"
  bucket_name          = "bucket-state"
  ...
}

output "tf-state-bucket-arn" {
  value = module.terraform-state.bucket_arn
}

```
Then after modifying the state, sometimes, the `tf-state-bucket-arn` outputs seems to be deleted, thus other states that depend on this output, error-out when trying to plan them as this output is no longer available through the remote data source.

The few times that I have encountered this in the past few weeks, it has happened for different states (we have a few and the setup for them all is identical, with same kind of module used and output value)

**Comment by dimisjim** [comment]
@alisdair 

I have encountered this again.
What I did was:

1. Imported a resource with the aws provider
2. Did a full plan, it returned an error due to incorrect resource attributes' configuration
3. Fixed them and planned again
4. Now it says:
```
Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + tf-state-bucket-arn = "arn:aws:s3:::my-bucket-name"
```
