### ISSUE TITLE
aws_iam_policy_attachment inconsistenty attaching policies

### ISSUE THREAD

**Issue by bfidgeon** [hashicorp/terraform#2810]
When run terraform to attach 2 policies to a role we get the following behavior

Run once: only one policy is attached
Run a second time: both policies are attached
Run a third time: one policy is attached.

Code as below:

resource "aws_iam_policy_attachment" "waf-svc-policy-attachment" {
    name = "${var.environment}-waf-svc-policy-attachment"
    roles = ["${aws_iam_role.waf-svc-role.name}"]
    policy_arn = "${aws_iam_policy.waf-svc-policy.arn}"
}

resource "aws_iam_policy_attachment" "base-waf-svc-policy-attachment" {
    name = "${var.environment}-base-waf-svc-policy-attachment"
    roles = ["${aws_iam_role.waf-svc-role.name}"]
    policy_arn = "${aws_iam_policy.base-svc-policy.arn}"
}

resource "aws_iam_instance_profile" "waf-svc-instance-profile" {
    name = "${var.environment}-waf-svc-instance-profile"
    roles = ["${aws_iam_role.waf-svc-role.name}"]
}

Please advise.

**Comment by nelg** [comment]
we can provide a complete tf example file that replicates the problem if it's not clear.

**Comment by bfidgeon** [comment]
Complete example.tf availalbe on pastebin: http://pastebin.com/nE9u59zQ
The first time is attached 2 roles to a policy. the second time it is run it detaches the roles. 

Third run 
  roles.#:          "0" => "1"
  roles.3574953296: "" => "dev-test-base-svc-role"
aws_iam_policy_attachment.base-test-waf-svc-policy-attachment: Modifying...
  roles.#:         "0" => "1"
  roles.956680925: "" => "dev-test-waf-svc-role"

Fourth run
  roles.#:          "2" => "1"
  roles.3574953296: "dev-test-base-svc-role" => ""
  roles.956680925:  "dev-test-waf-svc-role" => "dev-test-waf-svc-role"
aws_iam_policy_attachment.test-base-svc-policy-attachment: Modifying...
  roles.#:          "2" => "1"
  roles.3574953296: "dev-test-base-svc-role" => "dev-test-base-svc-role"
  roles.956680925:  "dev-test-waf-svc-role" => ""

**Comment by GrayCoder** [comment]
That pastebin has 3 `aws_iam_policy_attachment`s for 2 policies.

It's not possible to declare the attachment of a policy more than once because a single `aws_iam_policy_attachment` owns the policy it implements the attachment of. This was implemented in this way so that all the users, groups, and roles that one wants to have a specific policy are all attached to that policy in the same place.
This would technically fall under undefined behavior... I think.

**Comment by bfidgeon** [comment]
Patrick, 

AWS allows the attachment of up to 2 policies to a role. The limitations are described here: http://docs.aws.amazon.com/IAM/latest/UserGuide/limits.html 

We think that the policy_arn should accept an array of up to 2 elements. 

regards 

Brendan

**Comment by GrayCoder** [comment]
@bfidgeon sorry if I wasn't clear.

The way you would attach 2 policies to a role is exactly the way that you and your team have: with 2 different `aws_iam_policy_attachment` resources with one for each policy.

For some reason, there is a third `aws_iam_policy_attachment` resource in your example that tries to manage the same policy as one of the first 2.

I would recommend that instead, you try this:
```
resource "aws_iam_policy_attachment" "test-waf-svc-policy-attachment" {
    name = "dev-test-waf-svc-policy-attachment"
    roles = ["${aws_iam_role.test-waf-svc-role.name}"]
    policy_arn = "${aws_iam_policy.test-waf-svc-policy.arn}"
}
resource "aws_iam_policy_attachment" "test-base-svc-policy-attachment" {
    name = "dev-test-base-svc-policy-attachment"
    roles = [
        "${aws_iam_role.test-base-svc-role.name}",
        "${aws_iam_role.test-waf-svc-role.name}"]
    policy_arn = "${aws_iam_policy.test-base-svc-policy.arn}"
}
#resource "aws_iam_policy_attachment" "base-test-waf-svc-policy-attachment" {
#    name = "dev-base-test-waf-svc-policy-attachment"
#    roles = ["${aws_iam_role.test-waf-svc-role.name}"]
#   policy_arn = "${aws_iam_policy.test-base-svc-policy.arn}"
#}
```

This does what you want it to, attaches 2 manages policies to `test-waf-svc-role`, and it doesn't introduce the problem you were seeing. A single `aws_iam_policy_attachment` per managed policy was a design choice and I've added documentation to the docs with #2913 to alert users.

**Comment by bfidgeon** [comment]
Patrick, 

It's not working. Attached is a file which creates more than one policy and attaches them to different roles. When we run the terraform the first time it creates the expected attachments. We would not expect it to make changes when it is run for a second time but it does. A third run reverts the changes and the roles have two policies attached. 

Hopefully you can advise. 

regards 

Brendan 

First run abbreviated output: 

aws_iam_instance_profile.elk-svc-instance-profile: Creation complete 
aws_iam_instance_profile.base-svc-instance-profile: Creation complete 
aws_iam_policy_attachment.base-elk-svc-policy-attachment: Creation complete 
aws_iam_policy_attachment.elk-svc-policy-attachment: Creation complete 
aws_iam_policy_attachment.base-puppetmaster-svc-policy-attachment: Creation complete 
aws_iam_policy_attachment.puppetmaster-svc-policy-attachment: Creation complete 

Apply complete! Resources: 12 added, 0 changed, 0 destroyed. 

Second run abbreviated output: 

aws_iam_policy_attachment.base-puppetmaster-svc-policy-attachment: Modifying... 
roles.#: "2" => "1" 
roles.2485809687: "deviam-elk-svc-role" => "" 
roles.3756833025: "deviam-elk-puppetmaster-role" => "deviam-elk-puppetmaster-role" 
aws_iam_policy_attachment.base-elk-svc-policy-attachment: Modifying... 
roles.#: "2" => "1" 
roles.2485809687: "deviam-elk-svc-role" => "deviam-elk-svc-role" 
roles.3756833025: "deviam-elk-puppetmaster-role" => "" 
aws_iam_policy_attachment.base-elk-svc-policy-attachment: Modifications complete 
aws_iam_policy_attachment.base-puppetmaster-svc-policy-attachment: Modifications complete 

Apply complete! Resources: 0 added, 2 changed, 0 destroyed. 

Third run abbreviated output: 

aws_iam_policy_attachment.base-puppetmaster-svc-policy-attachment: Modifying... 
roles.#: "0" => "1" 
roles.3756833025: "" => "deviam-elk-puppetmaster-role" 
aws_iam_policy_attachment.base-elk-svc-policy-attachment: Modifying... 
roles.#: "0" => "1" 
roles.2485809687: "" => "deviam-elk-svc-role" 
aws_iam_policy_attachment.base-puppetmaster-svc-policy-attachment: Modifications complete 
aws_iam_policy_attachment.base-elk-svc-policy-attachment: Modifications complete 

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.

**Comment by GrayCoder** [comment]
@bfidgeon I don't think github supports attachments to comments via email, so I can't see the file you sent.

Please do count the number of policies you declare in that file, and the number of policy attachments.

**Comment by bfidgeon** [comment]
Patrick, 

We have declared 3 policies(base, machine1, machine2) and 4 policy attachments. We want 2 policies attached to roles for machine1 and machine2. The desired configuration for the roles is as follows: 

machine1_role: base policy, machine1 policy 
machine2_role: base policy, machine2 policy 

I have put the terraform file in pastebin: http://pastebin.com/nzMAcq1g 

regards 

Brendan

**Comment by GrayCoder** [comment]
@bfidgeon please use a single attachment for the base policy, and just put both machine's roles into the base policy attachment's list of roles.

There should only be 3 attachments because you only have 3 distinct policies.
There needs to be a single policy attachment per policy and no more. The attachment supports multiple roles, users, and/or groups.

Instead of creating an attachment for each machine for the base role, you should have a line like this:
`roles = [ "aws_iam_role.machine1.name", "aws_iam_role.machine2.name" ]`

**Comment by GrayCoder** [comment]
I think this issue can be closed unless @bfidgeon has more problems.

**Comment by bfidgeon** [comment]
Patrick, 

All sorted, thanks for your help. Can close 

Brendan

**Comment by GrayCoder** [comment]
@catsby please close this issue. I believe it's all sorted and isn't a bug. With #2913 we clarified the use of `aws_iam_policy_attachment` and I think everything should be good.

In future we should probably make attachments somehow aware of each other to alleviate these types of pains altogether, but a decent solution isn't overly obvioys (to me) right now.

**Comment by catsby** [comment]
@GrayCoder awesome, thank you for your great support here!

**Comment by bwhaley** [comment]
I read through the issue history here and the clarification that was added in #2913, but I'm afraid it misses a bunch of use cases. Sometimes you don't know all the roles that will be used for a managed policy. I may have a managed policy with a few roles now, but then I add more infrastructure and additional roles. Then I have to update the `aws_iam_policy_attachment` with the new role? Seems like I should just be able to do that within the role.

**Comment by GrayCoder** [comment]
#4016 should fix that
