### ISSUE TITLE
Terraform fails to use output variables from Module A as a configuration for provider for Module B

### ISSUE THREAD

**Issue by ilya-git** [hashicorp/terraform#28121]
### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/fluxcd/flux v0.0.12
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.49.0
+ provider registry.terraform.io/hashicorp/helm v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
module "cluster" {
  source                  = "./modules/cluster/"
}

module "kubernetes" {
  source = "./modules/kubernetes/"
  host = module.cluster.host
  client_certificate = base64decode(module.cluster.client_certificate)
  client_key = base64decode(module.cluster.client_key)
  cluster_ca_certificate = base64decode(module.cluster.cluster_ca_certificate)
}

// This is the provider inside kubernetes module
provider "kubernetes" {
  host =  var.host
  client_certificate =  var.client_certificate
  client_key =  var.client_key
  cluster_ca_certificate =  var.cluster_ca_certificate
}
```

### Expected Behavior

No errors, config passed properly

### Actual Behavior

Empty config is passed forcing some default values in kubernetes provider config and as a result connection to "localhost"

### Steps to Reproduce

I have a simple configuration with two modules:
Cluster: creates AKS kubernetes cluster returns values required for kubernetes provider to connect
Kubernetes: takes input variables to configure provider and create a configmap/secret inside kubernetes

First terraform apply works just fine: AKS is created, and provider connects to AKS properly and creates resources inside k8s.
However sometime after that (I am not sure if it's right away or there are some other prerequisites) terraform fails each time in kubernetes module trying to connect to "localhost" during plan. e.g.

> Error: Get "http://localhost/api/v1/namespaces/flux-system/configmaps/env-config": dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.

So far I can understand it's not a problem of the provider (or perhaps it is but a more deep one that just "localhost") but rather a problem of terraform not properly figuring out dependencies or something resulting in an empty configuration for "kubernetes" provider that then defaults to localhost for some reason.

If I change host from module output to some hardcoded value, the provider will then try to connect to that hardcoded value. The state seems to contain the correct values (it did work on the first apply as well).

P.S. If I use data to connect to the cluster directly, not via module, then the correct values are being passed to the provider, but then terraform decides it needs to delete the whole cluster which is unacceptable for me at this point.

I would also appreciate any workaround on this as it effectively means I can only run apply once and cannot change anything. I'd like to continue without destroying the cluster as well, which many of the workarounds seem to do like e.g. using data to connect to the cluster. 

### References

There are some multiple scattered issues regarding dialing localhost, none of them has any proper workaround for this issue though and many are closed, so I am not sure how are they really connected.

**Comment by ilya-git** [comment]
I have actually figured out what was wrong here and it seems like still something that needs fixing:

Due to some other error (not sure if this is arm provider bug or mine, but it's probably not relevant) terraform decided to recreate the cluster. That probably results in the fact that "host" would not be not known yet, and then terraform tries to plan on an non existing host.

All that together failure spectacularly without a clear indication on what is going on (see the error above). I did not even understand the cluster was planned to be recreated since there was no indication of that in the log due to these errors. Just figured it out randomly.

Perhaps "plan" should not even try to connect if it knows that variable will only be known after apply or some other fix might be possible?

Right now debugging is very hard due to this error

**Comment by jbardin** [comment]
Hi @ilya-git 

Thanks for filing the issue. It appears you have sorted things out here. Unfortunately the existing behavior is required for compatibility with many providers, which do not required a complete configuration during planning, and can wait until apply to be fully initialized. The configuration here is not considered to be a supported use case, and is called out as a warning in the [documentation](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources) to create the managed cluster in a separate configuration.

In the long term we have plans to try and make configurations like this possible with some sort of multi-step progressive apply, but nothing is concrete at the moment. 

Any more immediate changes would need to come from the providers themselves in how they handle missing values. the unknown status of values is carried over the provider plugin protocol, but they may not be able to fully access that information through the legacy SDK. As provider development continues, they should be able to provide better feedback about situations like this.

Thanks!

**Comment by ilya-git** [comment]
I have read that warning that you are referring to. It was quite unclear to me though. I did indeed have 2 modules: one where the kubernetes cluster is created and another one where the provider is used. So I felt like I did not quite violate the warning, but perhaps I am misunderstanding something here @jbardin?

There is perhaps still an error that can be fixed since the documentation says that input variables are safe to use? But they are apparently empty at planning time

**Comment by jbardin** [comment]
Thanks @ilya-git, yes I can see how that warning is unclear, as they really mean that it should be done in an entirely separate configuration to avoid the issue; composing it into individual modules does not change anything. Feel free to file an issue with the provider about their documentation. The next development version of the kubernetes provider is working on removing the legacy SDK, and may be able to better handle the case where a configuration value is unknown.

**Comment by ilya-git** [comment]
Thanks for the information!
