### ISSUE TITLE
Azure API management custom domain gets recreated on each run

### ISSUE THREAD

**Issue by sai-ns** [hashicorp/terraform#28120]
### Terraform Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.46.1
```

### Terraform Configuration Files

```
resource "azurerm_api_management" "apim" {
  name                = "apim-${var.sdlc}-${var.location}"
  location            = var.location
  resource_group_name = var.resource_group_name
  publisher_name      = "Demo publisher"
  publisher_email     = "something@email.com"
  sku_name            = "Standard_1"
 #  hostname_configuration {
 #     proxy {
  #       host_name           = "api.custdomain.com"
  #      default_ssl_binding = true
  #      key_vault_id        = "<KV SECRET ENDPOINT>"
   #  }
  #}
}
resource "azurerm_api_management_custom_domain" "apim_custom_domain" {
  api_management_id = azurerm_api_management.apim.id
   ## Had to insert the default domain which is the gateway url, otherwise terraform tries to change the default domain  
   ## host_name to custom domain and removing the custom domain that was created. 
   ## State file has two entries, default domain and custom domain, not sure why terraform is capturing the default in state file
   proxy {
    host_name           = "apim-${var.sdlc}-${var.location}.azure-api.net"
   }
   proxy {
    host_name           = "api.customedomain.com"
    default_ssl_binding = true
    key_vault_id        = "<KV SECRET ENDPOINT>"
  }
  # below is to make sure APIM system identity is added to access policy before it can create custom domain 
  depends_on = [KEYVAULT ACCESS POLICY RESOURCE]
}
```

### Expected Behavior

To establish the flow of APIM->keyvault AccessPolicy->custom domain, I have removed hostname_configuration from API management resource and added as part of the new resource which is used just to add custom domain. Expecting terraform to remove existing custom domain and recreate with new resource.
### Actual Behavior

First run is doing what it is supposed to do by deleting custom domain from API management and recreating it, but the very next `terraform plan` run is trying to delete custom domain which seems to have come from the azurerm_api_management resource rather than the azurerm_api_management_custom_domain resource. State file has no hostname_configuration for azurerm.api.management which looks like `"hostname_configuration": [],` whereas in azurerm_api_management_custom_domain, I do see the two proxy hosts(default and custom). Below is what it looks like when I run `terraform plan`  after the first apply
```
# azurerm_api_management.apim will be updated in-place
  ~ resource "azurerm_api_management" "apim" {
        id                        = "/subscriptions/xxxyyyzzz/resourceGroups/prod-rg/providers/Microsoft.ApiManagement/service/apim-prod-eastus"
        name                      = "apim-prod-eastus"
        # (17 unchanged attributes hidden)

      - hostname_configuration {

          - proxy {
              - default_ssl_binding          = true -> null
              - host_name                    = "api.customdomain.com" -> null
              - key_vault_id                 = "https://expvault.azure.net/secrets/prodcert" -> null
              - negotiate_client_certificate = false -> null
            }
        }
```
And when I apply, it is removing custom domain, and I have to run the custom_domain resource again to recreate it only to have it removed in the next run.
### Steps to Reproduce

`terraform plan`
`terraform apply`
`terraform plan`
### Additional Context

I have noticed 2 issues with azurerm_api_management_custom_domain resource, one is it adding default host_name to state file and expecting it be in terraform configuration file and other is the custom domain being deleted as part of a different resource.

**Comment by sai-ns** [comment]
Please hold off looking at this issue for now..looks like this is fixed on Azure provider 2.51. I am testing the changes.

**Comment by pselle** [comment]
Thanks for the comment! I've marked this as `waiting-response`, please close if your issue has been resolved :) Additionally, if you suspected an issue in the azurerm provider, please report those issues in [their tracker](https://github.com/terraform-providers/terraform-provider-azurerm/) (but please continue to report Core issues here!)

**Comment by sai-ns** [comment]
Tested and its looked good now. Thanks and yes I should've reported this in Azurerm provider tracker.
