### ISSUE TITLE
Passing `-state=state.tfstate` to terraform state list does not work

### ISSUE THREAD

**Issue by danpilch** [hashicorp/terraform#28133]
### Terraform Version

```
terraform version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.32.0
+ provider registry.terraform.io/hashicorp/http v2.0.0
+ provider registry.terraform.io/hashicorp/vault v2.18.0
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Terraform should look up resources from the passed in statefile.

### Actual Behavior

Terraform looked up state from the current workspace (remote s3 backend)
### Steps to Reproduce

start with a terraform project with a remote `s3` backend and a workspace. Then run:
`terraform state list -state=dev.tfstate` with a local state file

If I move the `dev.tfstate` out of a terraform working directory and run the command again it runs correctly

**Comment by jbardin** [comment]
Hi @danpilch,

Thanks for filing the issue. Unfortunately I'm not able to replicate this myself.

```
% tf version
Terraform v0.14.8

% tf state list
null_resource.a
null_resource.b

% tf state list -state=dev.tfstate
null_resource.local
```

Can you provide more detailed steps you used to create the issue?

Thanks!
