### ISSUE TITLE
Ability to skip resource on destroy without having to use targets

### ISSUE THREAD

**Issue by TrueCyberAxe** [hashicorp/terraform#28134]
I'd like to suggest the following feature to allow the ability to skip deleting a resource on delete without the need to add some complicated pipeline logic to add targets at the commandline level for ones pipeline.

### Current Terraform Version
Terraform v0.14.5

### Use-cases
So the main scenario is for resources that are automatically deleted when their parent is deleted in this scenario if you create a kms key then attach and iam role with aws_kms_grant, in my working environment i have a data that refers to the kms key (the kms key is created via a cloud formation stack that is created via terraform that runs a lamda) due to how our environment was setup we cant directly create the key as a resrouce

The problem is when i come to do a teardown of the created stack, terraform will attempt to revoke the kms key grant and that will flag up an error for an sts role that is tied to my employee number that will stop the destroy due to not having revoke permissions

I have permissions to delete the stack which will delete the grants along with the key, and i have to always perform a manual deletion of the stack due to this error.

### Attempted Solutions
I have attempted to use prevent_destroy but this stops the destroy in its tracks as it requires adding targets at the commandline level and since this is part of a module is less than ideal as requires everyone to add more code to their pipelines.

```
resource "aws_kms_grant" "a" {
  name              = "my-grant"
  key_id            = aws_kms_key.a.key_id
  grantee_principal = aws_iam_role.a.arn
  operations        = ["Decrypt"]

  lifecycle {
    prevent_destroy = true
  }
}
```

### Proposal
I suggest adding the following option to lifecycle of skip_on_destroy which when destroying a resource ignores it and moves onto the next one it would normally continue on to.

```
resource "aws_kms_grant" "a" {
  name              = "my-grant"
  key_id            = aws_kms_key.a.key_id
  grantee_principal = aws_iam_role.a.arn
  operations        = ["Decrypt"]

  lifecycle {
    skip_on_destroy = true
  }
}
```

**Comment by jbardin** [comment]
Thanks for filing the issue @TrueCyberAxe. This is the same use case covered by #3874, so I'm going to combine these.

Thanks!
