### ISSUE TITLE
Terraform crashes if a provider segfaults

### ISSUE THREAD

**Issue by nick96** [hashicorp/terraform#28147]
### Terraform Version

```
Terraform v0.14.8
+ provider nspain.dev/test/segfault v0.0.1
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    segfault = {
      version = "0.0.1"
      source = "nspain.dev/test/segfault"
    }
  }
}

provider "segfault" {}

data "segfault" "test" {}
```

The provider needs to be installed first from https://github.com/nick96/terraform-provider-segfault.

### Crash Output

https://gist.github.com/nick96/aaa4c6f4c9678f9376f516492d407942

### Expected Behavior

Terraform shouldn't crash and that the provider crashed should be logged.

### Actual Behavior

Terraform crashes.

### Steps to Reproduce

1. `git clone https://github.com/nick96/terraform-provider-segfault`
2. `cd terraform-provider-segfault`
3. `make install`
4. `cd examples`
5. `terraform init`
6. `terraform apply`

**Comment by jbardin** [comment]
Hi @nick96 

Terraform itself is not actually crashing in this case, but the parent process that monitors for crashing is incorrectly attributing the stack trace to a crash within terraform. This issue is fixed by 26694, and will be in the 0.15 release.

Thanks!
