### ISSUE TITLE
Option to generate partial plan, omitting resources that can't be determined until apply

### ISSUE THREAD

**Issue by sgrimm** [hashicorp/terraform#28167]
### Current Terraform Version

```
v0.13.4
```

But this also applies to more recent versions.

### Use-cases

Given a dependency graph of resources where some of the resources in the middle of the graph have `count` or `for_each` parameters, the goal is to be able to create all the specified resources without having to manually inspect error messages and run `terraform plan -target`. It should be possible for a CI system or other automated process to successfully create all the new resources without human intervention.

### Attempted Solutions

It is possible to hack around specific instances of the "value depends on resource attributes that cannot be determined until apply" error using tricks like adding `[*]` suffixes to string values, but those hacks only work in some cases and often have undesirable side effects such as modifying the types of expressions (changing strings to lists, etc.)

### Proposal

Add an option to `terraform plan` to output a plan to create or modify all the resources that can be unambiguously determined, and omit the ambiguous ones with a warning message. Exit with a unique exit code if there were resources omitted from the plan because they depended on not-yet-created resources.

It will then be possible to write a wrapper that detects the fact that a partial plan has been generated and generates another one after applying the partial one.

Exiting with a nonzero exit code serves two purposes: it's a way for tools to detect partial plans, and it should ensure that existing tools that expect `terraform plan` to fail if it can't generate a complete plan will not get confused by partial plans even if a user configures them to run `terraform plan` with the new option.

A possible failure mode will be if there is a configuration error that can only be detected after the partial plan is applied and the resources have been created. However, that's no worse than the current situation where you wouldn't discover such an error until after running `terraform plan -target` and applying the targeted plan by hand.

### References

There have been lots of issues related to this use case, for example #26755 .

**Comment by jbardin** [comment]
Hi @sgrimm,

If I understand correctly here, this is one of the possible paths for handing #4149 (aka "Progressive Apply"), which I have referred to in other contexts as "automatic targeting". 

I agree this is a useful path to explore, and in concept seems perfectly possible. Having attempting an implementation in the past I can say that it is far more complex than it sounds, but I also did not see any blockers preventing it from being a possibility in the future. Since we are tracking the use case in #4149 already, I'm going to close this out and link the two issues. 

Thanks!
