### ISSUE TITLE
 Inconsistency while dynamic block generation using typeset

### ISSUE THREAD

**Issue by Prativa20** [hashicorp/terraform#28169]
### Terraform Version
v0.13.0

```
...
```
### Terraform Configuration Files

data "vra_project" "this" {
  name = "vra-project"
}
```

### Debug Output
- .zone_assignments: block set length changed from 0 to 1


### Expected Behavior
The datasource vra_project has property called zone_assignments which is a dynamic list of objects. State file should contain all the objects inside zone_assignments returned by the vRA api.

### Actual Behavior
State file is inconsistent. There are 5 zone_assignments objects returned by the API but only a few of them are saved in the state file. Changing the type from TypeSet to TypeList saves all objects.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`


### References
https://github.com/vmware/terraform-provider-vra/issues/305

**Comment by jbardin** [comment]
Hi @Prativa20,

Can you provide an example configuration that demonstrated the issue you have? I don't see any use of dynamic blocks here or in the linked issue, and I'm not sure how to reproduce the problem. 

In general Terraform stores the state exactly as the provider returns it, so I don't see where we could be dropping values in Terraform itself. Dynamic blocks are known to have shortcomings when using the legacy SDK's `SchemaConfigModeAttr` option, is that being used in this case was well?

Thanks!

**Comment by jbardin** [comment]
Hello, we have not head back in a while, so I'm going to close this. If you are having an issue still with 0.13, I suggest you see if 0.15 can help solve the problem. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
