### ISSUE TITLE
terraform fails when user is attached to group and has name changed (AWS)

### ISSUE THREAD

**Issue by GrayCoder** [hashicorp/terraform#2818]
aws_iam_user.vpolchuk: Error: 1 error(s) occurred:

* Error deleting IAM User vpolchuck: DeleteConflict: Cannot delete entity, must remove users from group first.
        status code: 409, request id: [bcac89eb-307c-11e5-b474-9f5062e1342d]
aws_vpn_gateway.main: Modifications complete
Error applying plan:

2 error(s) occurred:

* Error deleting IAM User vpolchuck: DeleteConflict: Cannot delete entity, must remove users from group first.
        status code: 409, request id: [bcac89eb-307c-11e5-b474-9f5062e1342d]
* aws_iam_group_membership.dev: diffs didn't match during apply. This is a bug with Terraform and should be reported.

**Comment by GrayCoder** [comment]
This is solved by #3227

**Comment by catsby** [comment]
I merged #3227 , thanks all!
