### ISSUE TITLE
When a resource needs to be destroyed and then created again, show this as a "recreation" in the plan output

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/terraform#28207]
### Current Terraform Version

```
0.14.7
```

### Proposal

I believe the plan output is easier to read if instead of having `Plan: 1 to add, 1 to change, 1 to destroy.` we could have something simpler, like this: `Plan: 1 to recreate, 1 to change.`

This output would correspond better with resources that appear in the plan with the `-/+` semantic.

**Comment by Tbohunek** [comment]
Duplicate to https://github.com/hashicorp/terraform/issues/24233

**Comment by jbardin** [comment]
Combining this with #24233
