### ISSUE TITLE
Make prevent destroy a state property

### ISSUE THREAD

**Issue by sylr** [hashicorp/terraform#28206]
### Current Terraform Version

```
0.14.x
```

### Use-cases

I think it would be re-assuring for everyone if the prevent_destroy option if enabled would be kept in the state so that when applying a configuration where a prevent_destroy enabled resource has been removed terraform would fail.

### Proposal

I wish that for prevent_destroy enabled resources that the workflow to destroy such resources were to first apply a configuration where prevent_destroy would be turn off, then be destroyed in an second apply run where the resources would have been removed from configuration.

**Comment by pdesgarets** [comment]
Duplicate of https://github.com/hashicorp/terraform/issues/17599
