### ISSUE TITLE
endswith and startswith

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform#28209]
### Current Terraform Version

```
0.14.8
```

### Use-cases

Need to take action depending on how a string ends or starts

### Attempted Solutions

This is the code I have to use to add an ending if it is missing:
```
locals {
my_var = (
    trimsuffix(var.some_other_var, '/') == var.some_other_var ?
      var.some_other_var
      : "${var.some_other_var}/"
  )
}
```
The code would be very similar for string start but would use trimprefix, and would need to be modified just a bit if it's a more generic "if ends with this then do that else this other". 

### Proposal

Add endswith and startswith. Although really you probably need to start namespacing your functions eg str.endswith and str.startswith. Or even better, allow to create custom functions.

**Comment by Tbohunek** [comment]
@schollii what's your use-case here? I fear decision on `startswith()` only leads to anti-patterns and dangerous constructs.

**Comment by marcindulak** [comment]
Examples may include validations of the variable naming conventions

```
...
  validation {
    condition     = var.cluster.environment == "prod" ? str.startswith( var.cluster.name, "prod") : true
    error_message = "Invalid value."
  }
...
```

**Comment by Tbohunek** [comment]
Thanks @marcindulak, it was not clear straight away from the previous example.
It's possible and arguably easy to do this with `regex("prod$", var.cluster.name)` (ends with) and `regex("^prod", var.cluster.name)` (starts with).

I would vote to keep the number of functions low and to avoid namespacing to keep simplicity for the normal user, but `startswith()` and `endswith()` are simple and obvious enough, and given that not having those leads to "ugly" workarounds, addition of those two simple function would probably benefit everyone.

**Comment by schollii** [comment]
Cool

**Comment by sergei-ivanov** [comment]
My case is: given two FQDNs, I want to figure out if one domain is a subdomain of the other. I cannot plug a FQDN literally into a regex, because it contains periods. Therefore the construct like this `regex("\\.${var.domain1}$", var.domain2)` won't work reliably.

There's also no function to escape a string for regex, similar to `urlencode()`. For example, `regexencode("foo\\bar.")` would produce `"foo\\\\bar\\."`, which then could be safely inserted into a regex for literal matching.

With `regexencode()`, functions like `startswith()` and `endswith()` _could_ be emulated using `regex()`, e.g. `regex("\\.${regexencode(var.domain1)}$", var.domain2)`. But honestly, it looks so fugly, so non-obvious, and is so easy to mess up, I would really prefer having dedicated functions for simple string matching.

**Comment by yinzara** [comment]
I think there's a much easier way than using regex

For `endswith`:
```hcl
substr(var.domain2, (length(var.domain1) + 1) * -1, -1) == ".${var.domain1}"
```

And `startswith`:
```hcl
substr(var.domain2, 0, length(var.domain1) + 1) == "${var.domain1}."
```

**Comment by jwilner** [comment]
Not that I disagree that these basic str funcs should exist, but I think you can write @yinzara's code slightly more legibly:

```hcl
substr(var.domain2, length(".${var.domain1)") * -1, -1) == ".${var.domain1}"
```

**Comment by jwilner** [comment]
It occurs to me tho:

endswith:
```hcl
trimsuffix(var.domain2, var.domain1) != var.domain2
```

startswith:
```hcl
trimprefix(var.domain2, var.domain1) != var.domain2
```

**Comment by sergei-ivanov** [comment]
Even if we can reliably construct `startswith` and `endswith` logic via elaborate expressions, I am still not convinced that we _should_. It's not about the existence of workarounds, it's about readability and making the intent clear. Otherwise it's a question of why we have higher level programming languages if the same logic can be coded in assembly.

**Comment by sergei-ivanov** [comment]
Having said that, I'll probably use @jwilner 's solution for the time being, many thanks for contributing it!

**Comment by Tbohunek** [comment]
Looking at @jwilner's solution I'd vote for addition of built-in functions to get arguably much easier-to-understand code for the future juniors.

**Comment by simonweil** [comment]
Any chance to get this implemented?
There is a workaround but it's really not readable...

**Comment by mkielar** [comment]
Is this any more difficult than adding references to `strings.HasPrefix` and `strings.HasSuffix` in https://github.com/hashicorp/terraform/blob/main/internal/lang/functions.go#L34-L40 

and then, writing unit tests in `functions_test.go`?

**Comment by crw** [comment]
Hi @mkielar, you are correct in terms of implementation. As for getting a PR accepted, please see this comment: https://github.com/hashicorp/terraform/issues/28855#issuecomment-856345294, specifically:

> We're being pretty cautious about adding new functions that overlap with existing use-cases because Terraform has grown quite an unwieldy collection of builtins over the years, and so we've been considering various ways to allow for externally-defined functions (e.g. https://github.com/hashicorp/terraform/issues/2771) to avoid continuing to grow that set. However, that's not something we'll be working on in the very near future, due to our current focus being elsewhere, so we'll revisit this at a later time and post any updates in those other issues.

The conversation around external functions is active, but I do not have any other update to share.

**Comment by schollii** [comment]
The provider approach is interesting. I imagine the provider could define data sources as functions, so for example if the provider is called `string` then there would be a `string_endswith` and a `string_startswith` data source that we could use in our code. Each "function call" would be a separate data source, which is a little clunky as this is like having to assign the return value of each function call to a variable instead of using it in an expression, but it might be better than what we have now. So it could look something like this: 
```
data string_endswith file_type {
  input = var.file_path // (or a more complex expression like "${var.var1}-{var.var2}")
}
resource local_file file {
  filename = "${var.somefile}+${data.string_endswith.file_type}"
}
```

The data source here is a "function" with one input and one output, but a data source could easily represent functions of several inputs and outputs. 

This would require a bit of experimentation to see how verbose and understandable the tf code would be. Main problem being, that these data sources are all in global namespace of the module that defines them, so there could be name clashes, or naming (which not many people like to do) could be tricky so that you can keep track of which data source is used where. I suppose if that became an issue one could create a module and move the data source definitions there and use module outputs. 

Sounds like this might work, even if it wouldn't be nearly as easy and concise to use as user-defined functions. 

Anyone interested in teaming up on trying this approach? I'm super busy but teaming up will spread the load.

**Comment by crw** [comment]
> Is this any more difficult than adding references to `strings.HasPrefix` and `strings.HasSuffix` in https://github.com/hashicorp/terraform/blob/main/internal/lang/functions.go#L34-L40 and then, writing unit tests in `functions_test.go`?
> 
> Would you accept a pull request if someone does that?

Hi @mkielar, I took your comments back to the team, and we revisited this particular decision. We do not need to wait for a function provider framework for these functions. In this case, `startswith` and `endswith` meet a sufficiently wide use case need to be considered for built-in functions. We would be happy to review a pull request per your suggestion above. Thanks for your feedback on this issue.

**Comment by apparentlymart** [comment]
Thanks for the reminder @schollii! Sadly I didn't see it at the time but I'm seeing it now so better late than never I suppose. :grinning:
