### ISSUE TITLE
RDS storage not being modified

### ISSUE THREAD

**Issue by davedash** [hashicorp/terraform#2820]
```
module.dev.aws_db_instance.db: Modifying...
  allocated_storage: "5" => "50"
module.dev.aws_db_instance.db: Modifications complete

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate
```

Every time I run this it says that it modifies the storage but it never takes.

**Comment by catsby** [comment]
Hey @davedash – modifications that do **not** force a destroy-create cycle are applied in your next maintenance window, unless you specify the `apply_immediately` attribute to be true. 

When you look in the console, do you see anything indicating a change coming up with the next maintenance?

**Comment by davedash** [comment]
I didn't look - but after doing things manually I get it.  I wonder if there would be a way to eliminate the confusion.

**Comment by catsby** [comment]
The `apply_immediately` attribute can "help" here, in that the change is applied immediately. Otherwise, I don't think there's much Terraform can do.
