### ISSUE TITLE
Is there a way to prompt user to build each modules separately

### ISSUE THREAD

**Issue by UmeshVeerasingam** [hashicorp/terraform#2822]
Before using terraform, we(Pearson) used to build our modules in a particular sequence. We did this because we our chef provisioning script needed the ips from the previously built node. For example, we need mysql master node to be built before mysql slave is built. 

We were wondering if there is a way to prompt user before building each node?

**Comment by phinze** [comment]
Hi @UmeshVeerasingam,

There's no way to prompt for input on each node. Terraform collects all inputs at the beginning of the run. 

Terraform automatically manages dependency ordering, so you can reference the IP address attribute of a node before it is known.

```tf
resource "aws_instance" "foo" {
  // ...
}

resource "aws_instance" "bar" {
  // ...
  provisioner "remote-exec" {
    inline = "echo 'first node ip addr: ${aws_instance.foo.private_ip}'"
  }
}
```

Hope this helps! Feel free to follow up if you have further questions.

**Comment by dhoer** [comment]
yes you can, use `depends_on`
```
resource "aws_launch_configuration" "liveoak_selenium_dev_node" {
     depends_on = ["aws_instance.liveoak_selenium_dev_hub”]
```
you can also snag the private ip as mentioned above:
```
output "hub_private_ip" {
 value = "${aws_instance.liveoak_selenium_dev_hub.private_ip}”
}
```
