### ISSUE TITLE
Detect type of variables (again, revisited)

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#28225]
Related to https://github.com/hashicorp/terraform/issues/23070

Your rationale for not including type checking seems to be focussed on creators of module, but in my case, I have a datasource which brings back arbitrary maps full of different types, and I need to do an action for every map key in the map which has a submap as a value:

```
  root:
    a:
      a1:
        a1.1: value
        a1.2: value
      a2: value
    b: value
```

There are many many instances of such maps - e.g. the organisational structure in gcp, aws and azure, the aws_api_gateway structure etc. These are just 2, but you can think of lots - an external rest api for a service for which you have to instantiate watchers/crawlers etc.

So suppose now I have to create a resource (or do an action) for every key that has a map value, but not a "value" value.

I would need to be able to detect the type of k in `for k, v in data.xxx.map` so that I know whether to recurse down, or whether to terminate.  (because also terraform isn't supporting recursive functions, modules, or recursion in general - see https://github.com/hashicorp/terraform/issues/27248)

I believe the only solution for this at the moment is `try()` but this has limitations. I can try to exclude "b" in the list by using `try( tomap(v), {} )` and converting b's value into an empty map. Then I can try to force-cast a value to a string using `try( tostring(v), "didntwork")` and then use an "if" like this:

```
  items_level1 = compact(flatten([
    for k1, v1 in local.datamap:            # a => {a1,a2,a3}, b=> "value"
      try( tostring(v1), "didntwork" ) == "didntwork" ? null : {
        "name"   = k1,
        "parent" = local.root_node
      }
  ]))
```

Now for second level (because we dont have recursion:

```
  items_level1 = compact(flatten([
    for k1, v1 in local.datamap:            # a => {a1,a2,a3}, b=> "value"
      try( tostring(v1), "didntwork" ) == "didntwork" ? null : for k2, v2 in try( tomap(v1), {} ):
        try( tostring(v2), "didntwork" ) == "didntwork" ? null : {
          "name"   = k2,
          "parent" = k1
        }
  ]))
```

Something like that... horrific code, and it still doesnt work if "value" can be boolean, string, number etc.

It would be useful to have the ability to detect types, even though the state reason is that you want everything to be strongly types, external datasources (over which you have no control) may be far more fluid

**Comment by Tbohunek** [comment]
@gtmtech could you list a few examples of the different content of `local.datamap` that you expect to work with?

The best approach for any variable is to fix it to an explicitly defined structure/type where instead of dropping an empty submap, you just have it empty.
Trying to detect a variable type on-the-fly is a very dangerous action, and building that on top of an already dangerous concept of allowing `any` variable type makes it `pow("dangerous",2)` as receiving an unexpected type only leads to a runtime error. Please don't do that. 😉

**Comment by gtmtech** [comment]
@Tbohunek I understand that ideally an explicitly defined structure/type is great, but (as I think I mentioned) when taking an external datasource as your input, which contains fluid types to represent a hierarchy ( I provided 4 examples I think? ) - you dont get to set what types you want where , that's your datasource. 

If my datasource contains a map of elements which may be lists, maps or strings for example (like any json source object), and I need to create a bunch of resources for each of the strings in the json object, no matter what the hierarchy, I need to detect what type something is, and be able to crunch the whole thing down into a list. 

Here is an example of a orgstructure which I need to be able to make in GCP

```
---
root:
  folder1:
    folder1.1: {}
    folder1.2:
      projects: ["myproject-a", "myproject-b"]
  folder2:
    projects: ["myproject-c"]
```

It would be useful to detect the types as I go through it - isArray, isMap etc., so I know what to instantiate when and where. 
In reality this is around 200 folders and 500 projects btw. 

I want my input to be as simple as possible, so I dont want to overcomplicate the yaml above (or json equivalent) by adding a map type for everything - that would be hard to understand - its important the terraform code does the work, and the inputs are as simple as possible. 

I worked out a way to do this, because of the code at the top, but its not really pretty. I then read your prior issue where detecting the datatypes was requested, but it was denied on account that you should always know the datatypes. But I thought well I know at least 4 APIs where you might want to create stuff based off something you are not in control of (a 3rd party API for example) and it's made quite complicated when you dont control the inputs.

Thanks for your time.

**Comment by Tbohunek** [comment]
@gtmtech Yes, I had same idea, but I was explained why it is wrong and I understood.
By not supporting this, Terraform Devs are sparing many users headaches of debugging complex dynamic code.

![image](https://user-images.githubusercontent.com/16520646/126035579-105c6640-7a2b-4947-b60a-97e03bbecc0b.png)

**Comment by gtmtech** [comment]
@Tbohunek I think I'll close this ticket as a wont resolve  :)

In the end I decided to use an external datasource to translate the less-than-perfectly typed thirdparty API to be more able to be typed to interact with terraform - ugly but that's what I'll do in future. Appreciate terraforms position of course, and understandable. It's not always easy to deal pragmatically with real world services...
