### ISSUE TITLE
Incorrect interpolation in key of hash

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#28227]
Terraform 0.15.0-beta2

(Used terraform console to show issue)

This seems wrong:

```
> [for k,v in {"one"=1, "two"=2}: { k = v } ]
[
  {
    "k" = 1
  },
  {
    "k" = 2
  },
]
```

The "k" isnt being correctly substituted as a variable. 

Instead you have to do this:

```
> [for k,v in {"one"=1, "two"=2}: { "${k}" = v } ]
[
  {
    "one" = 1
  },
  {
    "two" = 2
  },
]
```

I thought terraform went through a "value-only interpretations" are deprecated back in 0.12.

**Comment by jbardin** [comment]
Hi @gtmtech, direct interpolation of the map keys can be done by using parenthesis. See https://www.terraform.io/docs/language/expressions/types.html#maps-objects and  #27037

Thanks!
