### ISSUE TITLE
Terraform CLI not working with bash on MacOS 11.2.1

### ISSUE THREAD

**Issue by th3r10n** [hashicorp/terraform#28223]
Hi,

I've ran:

`terraform -install-autocomplete`

after this, the contents of my .bashrc are:

`complete -C /usr/local/bin/terraform terraform`

I've logged out and logged in, but no command completion is happening when I press Tab.

**Comment by jbardin** [comment]
The auto-complete error in 0.15 will be fixed in the next release via #28251.

**Comment by mildwonkey** [comment]
I'm going to close this now that 0.15 is released. Thanks!
