### ISSUE TITLE
Unable to use a community provider 

### ISSUE THREAD

**Issue by tsenay** [hashicorp/terraform#28224]
### Terraform Version

```
0.14.9
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    solidserver = {
      source = "alexissavin/solidserver"
    }
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "solidserver" {
}
```

### Debug Output
https://gist.github.com/tsenay/6f685ecea8d05c136d5fee3e51f0063c

### Expected Behavior

The provider solidserver is downloaded and installed 

### Actual Behavior

The provider is correctly installed in `.terraform`directory but the init task failed with message: 
```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/solidserver: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/solidserver
```

Content of `.terraform` directory
```
find .terraform/providers -ls                                                                                                                                                                                             ✔  5854  10:42:39
8653932066        0 drwxr-xr-x    3 tsenay           staff                  96 29 mar 10:24 .terraform/providers
8653932067        0 drwxr-xr-x    4 tsenay           staff                 128 29 mar 10:25 .terraform/providers/registry.terraform.io
8653932068        0 drwxr-xr-x    3 tsenay           staff                  96 29 mar 10:24 .terraform/providers/registry.terraform.io/hashicorp
8653932069        0 drwxr-xr-x    3 tsenay           staff                  96 29 mar 10:24 .terraform/providers/registry.terraform.io/hashicorp/aws
8653932070        0 drwxr-xr-x    3 tsenay           staff                  96 29 mar 10:24 .terraform/providers/registry.terraform.io/hashicorp/aws/3.34.0
8653932071        0 drwxr-xr-x    3 tsenay           staff                  96 29 mar 10:24 .terraform/providers/registry.terraform.io/hashicorp/aws/3.34.0/darwin_amd64
8653932072   393344 -rwxr-xr-x    1 tsenay           staff            197837680 29 mar 10:36 .terraform/providers/registry.terraform.io/hashicorp/aws/3.34.0/darwin_amd64/terraform-provider-aws_v3.34.0_x5
8653932135        0 drwxr-xr-x    3 tsenay           staff                  96 29 mar 10:25 .terraform/providers/registry.terraform.io/alexissavin
8653932136        0 drwxr-xr-x    3 tsenay           staff                  96 29 mar 10:25 .terraform/providers/registry.terraform.io/alexissavin/solidserver
8653932137        0 drwxr-xr-x    3 tsenay           staff                  96 29 mar 10:25 .terraform/providers/registry.terraform.io/alexissavin/solidserver/1.1.9
8653932139        0 drwxr-xr-x    5 tsenay           staff                 160 29 mar 10:25 .terraform/providers/registry.terraform.io/alexissavin/solidserver/1.1.9/darwin_amd64
8653932142        8 -rw-rw-r--    1 tsenay           staff                1311 29 mar 10:36 .terraform/providers/registry.terraform.io/alexissavin/solidserver/1.1.9/darwin_amd64/LICENSE
8653932140    63616 -rwxrwxr-x    1 tsenay           staff            31663312 29 mar 10:36 .terraform/providers/registry.terraform.io/alexissavin/solidserver/1.1.9/darwin_amd64/terraform-provider-solidserver_v1.1.9
8653932143       16 -rw-rw-r--    1 tsenay           staff                5580 29 mar 10:36 .terraform/providers/registry.terraform.io/alexissavin/solidserver/1.1.9/darwin_amd64/README.md
```

### Steps to Reproduce

`terraform init`

**Comment by mildwonkey** [comment]
Hi @tsenay ,

I can see that terraform is successfully installing the community provider `alexissavin/solidserver` but also looking for `hashicorp/solidserver`. There are a couple of reasons terraform might think your configuration requires `hashicorp/solidserver`. Your attached logs show that you are using a module. Does that module reference the `solidserver` provider without a `required_providers` block?  Another possible place where terraform thinks it is seeing a "hashicorp/solidserver" provider could be your terraform state file.

Please run `terraform providers` to see where terraform is getting `hashicorp/solidserver` from. If it's in the module, you need to copy your required_providers block into the module, too - every module, root and child modules alike, need a "required_providers" block for any non-hashicorp provider. If it's in your state, you can use [`terraform state replace-provider`](https://www.terraform.io/docs/cli/commands/state/replace-provider.html) to replace hashicorp/solidserver with `alexissavin/solidserver`.

Hope this helps!

**Comment by tsenay** [comment]
The provider requirement was already declared in the module. The issue came up when I upgraded the module to TF 0.14(from 0.12). I finally found a workaround: 
- I added the `required_providers` block inside the caller terraform file. Then the plugin is installed AND terraform did not fails.

It is very annoying to have to declare provider source inside the module code AND the caller code. It should be only necessary to declare a provider source in the code that uses the provider.

**Comment by mildwonkey** [comment]
We need a `required_providers` block in every module because terraform has no way of being _certain_ what provider you want without it. Now that we've opened up the terraform registry to community providers, there's nothing keeping folks from creating providers that all have the same name. There could legitimately be 10 - or 100 - different `solidserver` providers in the registry. And there are likewise legitimate situations where someone wants to use different providers in each module. We have no way of knowing that without an explicit source block.
We generally compare this to various programming language's concepts of importing libraries: every file needs to need declare _exactly_ which library it is importing; the language can't possible assume what you mean if you reference `solidserver` without additional namespace information. 
Since there's no bug here, I am going to close this issue.
