### ISSUE TITLE
diffs didn't match during apply. This is a bug with Terraform and should be reported.

### ISSUE THREAD

**Issue by anshulshrivastava** [hashicorp/terraform#2823]
I got this issue while working on fetching the key/value data from consul server into terraform environment. When i did "terraform plan", it doesn't show any error in file. And when I tried "terraform apply" I got this error 

Error applying plan:
1 error(s) occurred:
* aws_instance.web: diffs didn't match during apply. This is a bug with Terraform and should be reported.

**Comment by jszwedko** [comment]
@anshulshrivastava can you post an example configuration reproducing this issue?

**Comment by anshulshrivastava** [comment]
Hey @jszwedko, Thanks for your response. But actually, I wrote the wrong path of a key in consul_keys resource.
