### ISSUE TITLE
Cant find way to regex a dot

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#28232]
Terraform 0.15-beta2

As demonstrated in terraform console, standard regex escaping of dot doesnt work:

```
regex("\.[^.]*$", "a.b.c.d")

> ╷
│ Error: Invalid escape sequence
│ 
│   on <console-input> line 1:
│   (source code not available)
│ 
│ The symbol "." is not a valid escape sequence selector.
```

Reading the docs, it seems that `\Q...\E` looks to be the only way you can escape a dot.

```
regex("\Q.\E[^.]*$", "a.b.c.d")

> ╷
│ Error: Invalid escape sequence
│ 
│   on <console-input> line 1:
│   (source code not available)
│ 
│ The symbol "Q" is not a valid escape sequence selector.
╵

╷
│ Error: Invalid escape sequence
│ 
│   on <console-input> line 1:
│   (source code not available)
│ 
│ The symbol "E" is not a valid escape sequence selector.
╵
```

Out of interest why the "strange" and feature-poor implementation of regexes? Is this a go underlying-regex-library thing? It seems vastly inferior to standard perl compatible regexes. It makes me a little sad that there's another regex engine to learn.

**Comment by gtmtech** [comment]
Self solved

```
regex("\\Q.\\E[^.]*$", "a.b.c.d")
".d"
```

**Comment by crabby345** [comment]
Am I missing something?

\. In regex is dot literal. \. In HCL is an attempt to escape the ., for which there isn't one (hence the error). You want an HCL literal \ to provide a regex escape so it needs escaping..... Giving \\. this works fine for me, and is the standard anywhere else you use \ in a HCL string.
