### ISSUE TITLE
Allow Datasources to be set as sensitive

### ISSUE THREAD

**Issue by MeNsaaH** [hashicorp/terraform#28258]
### Current Terraform Version

```
...
```

### Use-cases

Secret Managers allow you to access secret values. Unlike variables tho, this are accessed as data source and I don't want to make them visible in terraform plan or apply.

**Comment by pkolyvas-hashicorp** [comment]
Hi @MeNsaaH, 

Terraform 0.15's `sensitive` function should be able to help here. 

Given the follow example:
```hcl
resource "someprovider_resource" "name" {
  attribute = data.someprovider_resource.name.id
  ...
}
```

In Terraform 0.15 you could feasibly do the following:
```hcl
resource "someprovider_resource" "name" {
  attribute = sensitive(data.someprovider_resource.name.id)
  ...
}
```

This would result in the same behavior available to input variable values with `sensitive = true` and redact those values in the console output. 

You can read about the new function here: https://github.com/hashicorp/terraform/blob/v0.15/website/docs/language/functions/sensitive.html.md

If you'd be willing to try our 0.15.0-rc1 to see if this solves your use case, I'd be grateful. Our community  announcement and download link is here: https://discuss.hashicorp.com/t/terraform-0-15-0-rc1-released/22679

I think there's still some value in considering `sensitive = true` on data sources directly, but I'm hopeful this is a viable solution given Terraform's current limitations.

**Comment by MeNsaaH** [comment]
Thanks @pkolyvas-hashicorp.
