### ISSUE TITLE
error output should include the full resource address

### ISSUE THREAD

**Issue by dmrzzz** [hashicorp/terraform#28257]
### Current Terraform Version

```
$ terraform-0.14.9 version
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.34.0
```

### Use-cases

I have a data source with for_each which might fail due to "no results found":

```hcl
provider "aws" {
  region = "us-east-2"
}

data "aws_ec2_transit_gateway_vpc_attachment" "x" {
  for_each = {
    foo = "vpc-04d45bf5d7d4c6e04" 
    bar = "vpc-00000000000000000" 
    # ... imagine I have 50 more of these
  }

  filter {
    name   = "vpc-id"
    values = [each.value]
  }
}
```

In this case 'foo' legitimately identifies an actual VPC which has a TGW attachment in my account, while 'bar' (hypothetically unbeknownst to me) does not.

My problem is that the error output I currently get from Terraform:

```
$ terraform-0.14.9 plan

Error: error reading EC2 Transit Gateway Route Table: no results found

  on main.tf line 5, in data "aws_ec2_transit_gateway_vpc_attachment" "x":
   5: data "aws_ec2_transit_gateway_vpc_attachment" "x" {
```

does not help me figure out _which_ of my many data sources is failing.

### Proposal

I would like this error output to mention the specific for_each key(s) that resulted in the error, i.e. 'bar' in this case.

**Comment by jbardin** [comment]
Closed via #28275
