### ISSUE TITLE
Give more details when "Error: Failed to query available provider packages"

### ISSUE THREAD

**Issue by lchastel** [hashicorp/terraform#28255]
### Current Terraform Version

```
Terraform v0.14.9
```

### Use-cases

I have a module in which I put 
```
provider "kubectl" {
...
}
```
But I forget to add it in required_providers of terraform object.

I used this module in my main configuration and when I execute terraform init I received next result (I truncate it)
```
Upgrading modules...
- app in ../app
Downloading git::ssh://git@gitlab.com/....
Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/external...
...
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/kubectl: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/kubectl

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.
```
As you see the error is not explicite enough to find the source of the issue.

### Proposal

I would like to get the name of the module in the error message so I could find the issue more quickly.

**Comment by jbardin** [comment]
Hi @lchastel,

Thanks for filing the issue. The output in the next release will look slightly different:

```
- Finding latest version of hashicorp/kubectl...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/kubectl: provider registry
│ registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/kubectl
│
│ All modules should specify their required_providers so that external consumers will get the correct providers when
│ using a module. To see which modules are currently depending on hashicorp/kubectl, run the following command:
│     terraform providers
╵
```

In the error output we try to highlight exactly what terraform is looking for, in this case a provider called `registry.terraform.io/hashicorp/kubectl`, as well as indicating `required_providers` should be set.  The error also directs users to run the `terraform providers` command, which will show exact modules where providers are declared:

```
% terraform providers

Providers required by configuration:
.
└── module.test
    └── provider[registry.terraform.io/hashicorp/kubectl]
```

The next release will also validate how providers are configured and passed into modules, preventing modules from accidentally requiring providers they don't explicitly declare, which will show exact source locations of the problems. These changes seem to satisfy the requirements you presented here, so I'm going to close this as as these changes are already present in the upcoming release.

Thanks!
