### ISSUE TITLE
state mv ignores -state if -state-out is specified

### ISSUE THREAD

**Issue by mykter** [hashicorp/terraform#28265]
### Terraform Version

```
Terraform v0.14.8
```

### Expected Behavior

terraform uses the state specified in `-state` as its source state
(or at worst, errors out saying you can only specify one of `-state` or `-state-out`)

### Actual Behavior

terraform fails to find the input state, and says you should specify it using `-state`

### Steps to Reproduce
1. copy two state files into an otherwise empty directory, in.tfstate and out.tfstate.
2. `terraform state mv -state=in.tfstate -state-out=out.tfstate module.mymod module.mymod`

### References
It looks like the input state path is being overridden by the output state path here: https://github.com/hashicorp/terraform/blob/main/command/state_mv.go#L81

**Comment by alisdair** [comment]
Hi @mykter! I'm unable to reproduce this. Here's what I tried:

1. Created a simple config:

    ```hcl
    resource "null_resource" "none" {}
    ```
2. `terraform apply -auto-approve`
3. `mv terraform.tfstate in.tfstate`
4. Check the state:

    ```shellsession
    $ terraform state list -state=in.tfstate
    null_resource.none
    ```
5. Move the resource:

    ```shellsession
    $ terraform state mv -state=in.tfstate -state-out=out.tfstate null_resource.none null_resource.none`
    Move "null_resource.none" to "null_resource.none"
    Successfully moved 1 object(s).
6. Check old state:

    ```shellsession
    $ terraform state list -state=in.tfstate
    ```
7. Check new state:

    ```shellsession
    $ terraform state list -state=out.tfstate
    null_resource.none
    ```

Terraform seems to be working correctly for me. Can you suggest what might be missing from my reproduction steps?

**Comment by mykter** [comment]
Agreed, I can't reproduce this either now, sorry.
