### ISSUE TITLE
Inline Policies

### ISSUE THREAD

**Issue by jayjhan8** [hashicorp/terraform#2826]
I'm attempting to create inline policies for an  IAM role associated with an instance but I am having trouble doing so.  If I choose to attach policies to a role, these show up as managed policies so I hit the limit of two right away.  If I try the approach with role policies, Terraform outputs an error saying that I cannot specify resources.  Is there a way to get inline policies implemented with Terraform? If not, how trivial is the change?

**Comment by catsby** [comment]
Hey @jayjhan8 – I'm sorry to say that I'm not an IAM expert by any means, but I'm curious if you could construct a policy for a group ,and then use a group membership resource: `https://terraform.io/docs/providers/aws/r/iam_group_membership.html`

If that doesn't work, I recommend inquiring on our mailing list, https://groups.google.com/group/terraform-tool . That list is probably a better place to get advice or recommendations on best practices.

Sorry I'm not much help :frowning:

**Comment by jedineeper** [comment]
Hi @jayjhan8,

Sorry for taking so long to reply, but you can create inline policies by using the aws_iam_role_policy object.

Here's an example; https://gist.github.com/jedineeper/4346fc20b5865e41c9aa

Thanks,
Craig

**Comment by jayjhan8** [comment]
Hey @jedineeper,
We currently have inline policies that make references to specific resources... Is there a workaround for this?  Not particularly urgent, but I've ran into some walls with Terraform in trying to specify these resources using aws_iam_role_policy.

**Comment by jedineeper** [comment]
IAM policies should work as you expect from AWS? You can refer to specific resources as the IAM format allows. If you need the id from a Terraform resource you can just insert a variable interpolation into the IAM statement?

If that's not it, any chance you can drop an example of what the walls you are seeing are :)

**Comment by sandyfox** [comment]
aws_iam_role_policy resource works fine for me to create inline policy.  aws_iam_role_policy_attachment works for managed policy.

**Comment by RichardBronosky** [comment]
Question: How do you create a *policy* on a *role* with a *Policy type* of *Inline policy* like in the attached screenshot?
<img width="1032" alt="Screen Shot 2019-11-11 at 4 47 09 PM" src="https://user-images.githubusercontent.com/13620/68623781-46123480-04a3-11ea-810f-f4de5101485f.png">

Answer: That is the purpose of aws_iam_role_policy even though the word *inline* does not appear anywhere on https://www.terraform.io/docs/providers/aws/r/iam_role_policy.html at this time.

(I'm dropping this info here for anyone else who gets lead here by Google before I can format a documentation PR.)
