### ISSUE TITLE
Please can compact() support a list of any objects not just strings

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#28264]
Terraform 0.15.0-beta2

At the moment compact() removes the `""` from a list of strings. It was useful back in the day when terraform did everything in strings. Now lists of complex objects are commonplace, we need a function to remove nulls from a list whatever the inner object type.

In my view there is no reason why compact() could not now remove nulls from a list of any type of objects, e.g. a list of maps. This is critical functionality in `for k,v in var.map : y if z` style expressions where y is also a map. There is currently no way to remove the nulls in the result. 

Thanks

**Comment by jbardin** [comment]
Hi @gtmtech,

The current form of the `compact()` function was retained for compatibility reasons, since subtle changes in the behavior may not be immediately apparent in existing configurations. We did consider various alterations, but because there is no one version that suits every users needs, we left generic filtering of collections to be done with the existing for-expressions.

Can you show an example of the data you are working with that cannot be "compacted" using a general for-expression?

Thanks!

**Comment by lkysow** [comment]
This was something I was trying to use `compact` for but there might be a better way?

```hcl
            environment = compact([
              var.enabled ?
              {
                name  = "ENABLED"
                value = "true"
              }
              : null
            ])

```

**Comment by jbardin** [comment]
@lkysow, I think in that case I would assign the lists rather than compact one, like:

```

output "two" {
  environment = var.enabled ? [{
    name  = "ENABLED"
    value = "true"
  }] : []
```

However if you have multiple values, you can use a for expression (though this is a little ugly with just the single object literal)

```
  environment  = [for each in [
    {
      name  = "ENABLED"
      value = "true"
    }
  ] : each if var.enabled]
```

**Comment by gtmtech** [comment]
@jbardin Thanks for your reply.

So I'm doing this:

```
  resources_level1 = sort(compact(flatten([
    for k,v in local.org: [
      format("%s.%s=%s", try( tostring(v), "other") == "other" ? "folder" : "project",
                         "${k}",
                         try( tostring(v), tostring(k) ))
    ]
  ])))

  resources_level2 = sort(compact(flatten([
    for f in compact([ for r in local.resources_level1: element(split("=", r), 0) if substr(r, 0, 7) == "folder." ]): [
      for k,v in local.org[ element(split(".", f), 1) ]: [
        format("%s.%s.%s=%s", try( tostring(v), "other" ) == "other" ? "folder" : "project",
                              element(split(".", f), 1),
                              "${k}",
                              try( tostring(v), tostring(k) ))

      ]
    ]
  ])))

```

Horrible code - but it goes through a yaml description of an org, and creates a structure whereby terraform can use foreach to create each level of folder because

* recursion is not allowed in self-referencing modules, so we have to do everything from the top
* each folder needs to know its parent (containing) folder ID, so we have to do it in levels like this. 

Ideally I would have liked to keep the whole map information about a folder, and then when I decide (from the org yaml) whether something is a folder or a project, I can drop the project from the list (for creating the folders), and keep the map of each folder - and foreach over them all. 

However I could not do this, because there was no way to remove nulls from a list of maps.

Instead I had to use a single value representing the information I needed - hence the "%s.%s=%s" string  (the single value) - and then I could use compact to remove the nulls or empty strings. 

I couldnt quite believe there wasnt a function to remove nulls from a list of maps.

**Comment by clayrisser** [comment]
I figured out a clever way to do this.

Let say I am trying to filter only the pets that are cats `kind = "cat"` from a list of pets.

```hcl
variable "pets" {
  type = list(object({
    name = string
    kind = string
  }))
  default = [
    {
      name = "Fido"
      kind = "dog"
    },
    {
      name = "Max"
      kind = "dog"
    },
    {
      name = "Milo"
      kind = "cat"
    },
    {
      name = "Simba"
      kind = "cat"
    }
  ]
}
```

1. First convert the list of pets to a map `pets_map` of pets using the index `tostring(i)` as the key.
   This will be used in step 3 to lookup the filtered pets.

```hcl
locals {
  pets_map = { for i, pet in var.pets : tostring(i) => pet }
}
```

2. Next create a filtered list of the keys that respectivley matches the condition `pet.kind == "cat"`
   by looping over the keys in the `pets_map` and setting the respective keys that do not match to an
   empty string. Then compact the list which removes the empty strings from the list.

```hcl
locals {
  cat_keys = compact([for i, pet in local.pets_map : pet.kind == "cat" ? i : ""])
}
```

3. Loop over the filtered keys `cat_keys` and lookup the respective pet from the `pets_map`. Now you
   have the filtered list of pets that are cats `kind = "cat"`. You can now access the cats with `local.cats`.

```hcl
locals {
  cats     = [for cat_key in local.cat_keys : lookup(local.pets_map, cat_key)]
}
```

Below is the full example.

```hcl
variable "pets" {
  type = list(object({
    name = string
    kind = string
  }))
  default = [
    {
      name = "Fido"
      kind = "dog"
    },
    {
      name = "Max"
      kind = "dog"
    },
    {
      name = "Milo"
      kind = "cat"
    },
    {
      name = "Simba"
      kind = "cat"
    }
  ]
}

locals {
  pets_map = { for i, pet in var.pets : tostring(i) => pet }
  cat_keys = compact([for i, pet in local.pets_map : pet.kind == "cat" ? i : ""])
  cats     = [for cat_key in local.cat_keys : lookup(local.pets_map, cat_key)]
}
```

**Comment by jbardin** [comment]
@clayrisser,

I think this is where users are getting confused, as I see `compact` being used to filter, when a conditional would suffice.
For example, the `cat_keys` value would normally be written as

    cats_keys = [for i, pet in local.pets_map : i if pet.kind == "cat"]

**Comment by jbardin** [comment]
Since the `compact` behavior is working as defined, and _for expressions_ already provide a generic method for collection filtering based arbitrary conditions, I'm going to close this out.  

Thanks!

**Comment by clayrisser** [comment]
@jbardin thanks
