### ISSUE TITLE
Implement __FILE__ and __DIR__ equivalents for filepaths

### ISSUE THREAD

**Issue by ofbeaton** [hashicorp/terraform#28268]
### Current Terraform Version

```
Terraform v0.14.8
```

### Use-cases
When using any file path, be it [filesystem function](https://www.terraform.io/docs/language/functions/index.html) or `source` module parameter, I want to be able to specify a path relative to the current file, not the current working directory. 

This is important for clarity and readability, but also for modules that include relative modules, which can have problems with current working directory paths depending how they are invoked.

It is especially important when trying to create code that will work with terraform AND any kind of pre-processor like terragrunt, or a package manager like a terrafile handler, as they tend to change the current working directory and directory structure of your project.

### Attempted Solutions
If using a pre-processor like terragrunt, you can use the terragrunt function `get_parent_terragrunt_dir()` and `get_terragrunt_dir()` to create absolute paths, however this only covers part of the use cases. It doesn't help when pulling in a module that should work without terragrunt, especially if that module has relative includes of sub-modules. 

It also still makes the path a bit confusing as you often have to "walk" your directory tree based on those functions to get at the file you want which bakes in things like intermediary directory names which may change over the lifetime of the project.

### Proposal
Like many programming and scripting languages, implement a `__FILE__` and `__DIR__` dynamic constant or function equivalent that resolves to the file path of the current file and its directory respectively. This way we can construct paths with confidence that they are relative to the current file.

**Comment by jbardin** [comment]
Hi @ofbeaton 

Thanks for filing the feature request. You you provide some more detail on how this proposals differs from the current `path.module`, `path.root`, and `path.cwd` values that we have in terraform? https://www.terraform.io/docs/language/expressions/references.html#filesystem-and-workspace-info

Thanks!

**Comment by ofbeaton** [comment]
ugh, I google so many times trying to find this, and even held off filling an issue for weeks. I think `path.module` and `path.root` would work for almost all my use cases. I think `__file__` and `__dir__` is likely better for readability and maintainability, but likely not worth the support overhead on your head.

Sorry about that and thank you!
