### ISSUE TITLE
support optional data sources

### ISSUE THREAD

**Issue by mgk** [hashicorp/terraform#28279]
### Current Terraform Version

```
Terraform v0.14.9
```

### Use-cases
I would like to be able to to configure a data source that may or may not have any data resource behind it. My specific use case is a website "foo.example.com" that needs to lookup and use the AWS ACM SSL certificate for "foo.example.com" -or- fallback to the "*.example.com" certificate if not "foo.example.com" exists.

As far as I can tell data sources error if they cannot find a resource, so the above is not possible without a custom or external provider.

### Attempted Solutions
I cobbled together the following to address the use case:

```hcl
terraform {
  required_providers {
    external = {
      source = "hashicorp/external"
      version = "2.1.0"
    }
  }
}

variable "hostname" {
  description = "Hostname for which SSL certificate is wanted"
}

locals {
   # Get the domain of the hostname (foo.example.com → example.com)
  hostname_parts = split(".", var.hostname)
  domain = join(".", slice(local.hostname_parts, 1, length(local.hostname_parts)))
}

data "external" "certificate" {
  program = ["ruby", "${path.module}/find-first-certificate-arn.rb"]

  query = {
    domains = "${var.hostname},*.${local.domain}"
  }
}

output "certificate" {
  value = data.external.certificate.result
}
```

with `find-first-certificate-arn.rb`:

```ruby
require "json"
require "aws-sdk-acm"

# Terraform external program that finds the first ACM certificate that covers
# a list of domain names.
#
# Given the list "foo.example.com,*.example.com"
# -> the certificate # for "foo.example.com" will be returned if it exists
# -> otherwise the certificate # for "*.example.com" will be returned if it exists
# -> otherwise an "empty" certificate will be returned, i.e.: {"domain_name": "", "arn": ""}
query = JSON.parse STDIN.read
domains = query["domains"].split(",")

acm = Aws::ACM::Client.new

certificates =
  acm
  .list_certificates(certificate_statuses: ["ISSUED"])
  .certificate_summary_list
  .map { |cert| [cert.domain_name, cert.certificate_arn] }
  .to_h

domain = domains.find { |d| certificates[d] }

puts({domain_name: domain, arn: certificates[domain]}.to_json)
```

This works, but is not ideal as it uses the external provider escape hatch.

### Proposal

This could potentially be a feature of the AWS provider, but I was thinking of a couple more general solutions:

#### coalescing data source
Have a data source that effectively performs a `coalesce()` of multiple data sources: returning the first non-empty set of results. Various ways one could express this, but it might go something like:

```hcl
data "aws_acm_certificate" "foo" {
  domain      = "foo.example.com"
}

data "aws_acm_certificate" "wildcard" {
  domain      = "*.example.com"
}

data "coalesce" "certificate" {
  data_sources = [data.aws_acm_certificate.foo, data.aws_acm_certificate.foo]
}
```

#### optional data source
Another possibility would be to allow all data sources to be optional:

```hcl
data "aws_acm_certificate" "foo" {
  domain   = "foo.example.com"
  optional = true
}
```

This is more general as it would allow data sources to be composed in other ways, while the coalescing data source only handles one pattern (and is a little annoying to type and speak :).

I expect the tricky part is catching data source errors and knowing when it is safe to deem an error as "resource missing". Maybe it could just treat all errors as empty.

**Comment by jbardin** [comment]
Hi @mgk,

The decision to for an action to error or not is up to the provider implementation. There are examples of data sources which do not error when no results are found, and they are usually specified in the plural as returning 0 or more values; while data sources which return a single value conventionally will error when the resource cannot be found.

There is no reason a data source cannot already add an `optional` argument, and return a "empty" value of some sort, or add another data source intended to return 0 or more results. If a particular data source is often used in a context where it may not exist, you may want to file an issue to request this feature with the provider. 

Thanks!
