### ISSUE TITLE
S3 backend profile parameter doesn't work

### ISSUE THREAD

**Issue by alex-onyshchenko** [hashicorp/terraform#28283]
### Terraform Version

```
0.14.8
```

### Terraform Configuration Files

```terraform
...
```

### References

```
backend "s3" {
    ...
    profile        = "bc"
  }
```

When I run `terraform init` it argues about Access Denied but when I use `AWS_PROFILE="bc" terraform init` it works well.

**Comment by jbardin** [comment]
Hi @alex-onyshchenko,

Can you show the configuration and steps used to produce the error here?

I'm not able to reproduce this, and I think the most likely cause is that you have a stored config with the incorrect value, and need to run `terraform init -reconfigure` to update the stored values.

**Comment by alex-onyshchenko** [comment]
```terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.32.0"
    }
  }

  backend "s3" {
    bucket         = "oonyshchenko-terraform-state"
    key            = "global/s3/terraform.tfstate"
    region         = "us-west-1"
    dynamodb_table = "oonyshchenko-terraform-locks"
    encrypt        = true
    profile        = "bc"
  }
}

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
}```

I have aws_profile in my variable file testing.tfvars.
When I run it in such way:

```
terraform init -var-file="testing.tfvars"
terraform plan -var-file="testing.tfvars"

```
it doesnt take profile keys.

But running with env vars works well:
```
AWS_PROFILE="bc" terraform init
AWS_PROFILE="bc" terraform plan
```

**Comment by alex-onyshchenko** [comment]
Just checked `terraform init -reconfigure` and it works now as expected. My bad. I will close the issue.

**Comment by alex-onyshchenko** [comment]
This is not a bug.
