### ISSUE TITLE
Error 409: This application already exists and cannot be re-created - help, please :) 

### ISSUE THREAD

**Issue by saidi-adam** [hashicorp/terraform#28289]
Hi Team Terraform, 

I've been having issue recently whereby whenever i try to deploy a GCP App Engine or GCP Monitoring Dashboard resource, i get an error alluding to `Error: Error creating App Engine application: googleapi: Error 409: This application already exists and cannot be re-created., alreadyExists` 

The error above is just for App engine, but I get the same one for the Monitoring Dashboard... I'll paste snippets of the code below.

Its good to note that these resources do not exist in the console and commenting them out leads to a successful, but incomplete deployment. Also, the properties (`gcp-project.project_id`, `var.gcp_reigon `and `stats_dashboard_json.json`) files/references work as expected

App Engine:
` resource "google_app_engine_application" "stats_bot_app_engine" {
   project     = module.gcp-project.project_id
   location_id = var.gcp_region
   database_type = "CLOUD_DATASTORE_COMPATIBILITY"
 }`

Monitoring Dashboard:
`resource "google_monitoring_dashboard" "stats_bot_dashboard" {
  project        = module.gcp-project.project_id
  dashboard_json = file("assets/stats_dashboard_json.json")
}`

**Comment by jbardin** [comment]
Hi @saidi-adam,

Sorry you're you're having trouble with your GCP resources. If you can reproduce the situation, I would suggest filing an issue with the google provider, including the information requested in the issue template. If you are unsure how to handle the situation or have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
