### ISSUE TITLE
Feature request: add the schema option to google pubsub

### ISSUE THREAD

**Issue by GabrielBG99** [hashicorp/terraform#28284]
Currently, there seems to be no way to apply schema to Google Pub/Sub topics.

What about defining a resource like `google_pubsub_topic_schema` to create a Pub/Sub scheme and allow it to be referenced it in the `google_pubsub_topic` declaration?

### Exemple

```terraform
# The following resource does not exists
resource "google_pubsub_topic_schema" "test_schema" {
  name = "topic-schema"
  schema = <<EOF
syntax = "proto2";

message ProtocolBuffer {
  string string_field = 1;
  int32 int_field = 2;
}
EOF
}

resource "google_pubsub_topic" "with_schema" {
  name = "topic-with-schema"
  schema = {
    name = google_pubsub_topic_schema.test_schema.name
    encoding = "JSON"
  }
}


```

### References

[GCP Pub/Sub - Creating and managing schemas](https://cloud.google.com/pubsub/docs/schemas)

**Comment by apparentlymart** [comment]
Hi @GabrielBG99,

This seems to be a feature request for the Google Cloud Platform provider, which has its own separate repository. We don't develop individual providers in _this_ repository.

If you'd like to send this request to the team that works on the Google Cloud Platform provider, please open an issue in [the Google Cloud Platform provider repository](https://github.com/hashicorp/terraform-provider-google). Thanks!
