### ISSUE TITLE
Terraform action changed after modify the resource modules

### ISSUE THREAD

**Issue by pkqsun** [hashicorp/terraform#28287]
Hi There,

I am using Terrafrom for about 4 years and recently, I plan to uppgrade Terraform from v0.12.29 to v0.14.8. 
So, I am trying of v0.14 new deployment first.
Though the resource creation is done after adding provider file per module, but the scale-in action is different from v0.12 version.

### Terraform Version

```
v0.12.29
v0.14.8
```

### Terraform Configuration Files

```
./openstack.tf
./modules/instance/pkq-01/group_01/main.tf
./modules/instance/pkq-01/group_01/provider.tf

```
Content is as below shows.

### Debug Output

As below show.

### Crash Output

```

$ terraform plan -state=terraform.tfstate.pkq-01
...
Error: Provider configuration not present

To work with module.slaver-02.openstack_compute_instance_v2.instance
(orphan) its original provider configuration at
module.slaver-02.provider["terraform.io/hashicorp/openstack"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.slaver-02.openstack_compute_instance_v2.instance (orphan),
after which you can remove the provider configuration again.


Error: Provider configuration not present

To work with
module.slaver-02.openstack_blockstorage_volume_v3.blockstorage_volume-01
(orphan) its original provider configuration at
module.eslaver-02.provider["terraform.io/hashicorp/openstack"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.slaver-02.openstack_blockstorage_volume_v3.blockstorage_volume-01
(orphan), after which you can remove the provider configuration again.


Error: Provider configuration not present

To work with
module.slaver-02.openstack_networking_port_v2.port_net-01_v4 (orphan)
its original provider configuration at
module.slaver-02.provider["terraform.io/hashicorp/openstack"] is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.slaver-02.openstack_networking_port_v2.port_net-01_v4
(orphan), after which you can remove the provider configuration again.



```
### Expected Behavior

In v0.12, I always keep the openstack.tf up-to-date.
When do scale-in event, I would comment/delete some blocks , run terraform apply, then according resources will be deleted.

Expected as v0.12 shows:
Plan: 0 to add, 0 to change, 3 to destroy.

But for v0.14, I know the terraform plan/apply has some enhancement, but this method does not work any more.

### Actual Behavior

Reported above error.

### Steps to Reproduce

1) I separate all resources into several modules, one moduel contain one template file named main.tf 

```
$ ls modules/  -1r
server_group_v2
security_groups
networks
keypair_v2
instance
glance_images


./modules/instance/pkq-01/group_01/main.tf

resource "openstack_compute_instance_v2" "instance" {
    name = "${var.name_prefix}-${var.hostname}${var.cluster_domain}"
    key_pair = var.keypair_name
    flavor_id = var.flavor_uuid

    image_id = var.image_uuid

    config_drive = "true"
    availability_zone = var.zone_of_instance

    scheduler_hints {
        group =  var.servergroup_uuid
    }

    network {
        port = openstack_networking_port_v2.port_net-01_v4.id
    }

    block_device {
        uuid             = var.image_uuid
        source_type      = "image"
        destination_type = "local"
        boot_index       = 0
        delete_on_termination = true
    }

    block_device {
        uuid             = openstack_blockstorage_volume_v3.blockstorage_volume-01.id
        source_type      = "volume"
        destination_type = "volume"
        boot_index       = -1
        delete_on_termination = true
    }

    metadata = {
        dc = var.datacenter
        role = var.role_names
        ssh_user = var.ssh_user
    }

    lifecycle {
         ignore_changes = [
             image_id
         ]
    }
}

// new added for v0.14 as plugin/Provider need to be specified explicitly from v0.13
./modules/instance/pkq-01/group_01/provider.tf

terraform {
    required_version = “>= 0.13”
    required_providers {
        openstack = {
        version = “1.40.0”
        source = “terraform.io/hashicorp/openstack”
        }
    }
}
provider “openstack” {
}

```

I use local provider as there is no network to access public:

```
$ ls terraform.d/plugins/terraform.io/hashicorp/openstack/1.40.0/linux_amd64/
terraform-provider-openstack_v1.40.0
```

2) In openstack.tf file, I define several modules per resouces type and nodes:

```
$ cat openstack.tf | grep modules/ -C1
module “master-01” {
    source = “./modules/instance/pkq-01/group_01/”
    ssh_user = “user1”
module “slaver-01” {
    source = “./modules/instance/pkq-01/group_02/”
    ssh_user = “user2”
module “slaver-02” {
    source = “./modules/instance/pkq-01/group_02/”
    ssh_user = “user2”
```
3)  After terraform init and plan, the apply finished successfully.

4) Now I want to do scale-in one node, such as slaver-02,  so I just comment/delete the module “slaver-02” block, and then did terraform apply again.

5) Above error will show. 

### Additional Context

My Questions:

1) 
Not sure if there is a more efficient way of adding provider.tf to each sub-module folder ?
As I use the only one local openstack provider, is one global provider definition supported or not for v0.14 ?

2) 
Regarding above “Provider configuration not present” error, any idea or hint for me ?
I know the cmd of “terraform destroy -target module.slaver-02” and then update openstack.tf file works, but I still want to find a way to be compatible with the method in v0.12. 
Sometimes, I don't need to care or know which resources are added or deleted (openstack.tf could be changed by several operators), but just want to apply these changes in common (one dedicated operator is responsible to perform changes).  Is it possible?

3)
I know in deveploment level, v0.12 is not suggested to use or without any new fix/features. But I still could use v0.12, right ?
Without TLS 1.3 or Unicode 12.0 character tables, etc. Any other potential issues of keep using v0.12 ?

### References

https://discuss.hashicorp.com/t/terraform-action-changed-after-modify-the-resource-modules/22821

**Comment by jbardin** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
