### ISSUE TITLE
sensitive vars still plain text in backend state

### ISSUE THREAD

**Issue by Maarc-D** [hashicorp/terraform#28292]
# Description 

This issue is relative to `sensitive` attribute of a variable

Indeed when you use it a hash is managed to compare value for the plan but the plain text value is still on the state at the backend level, following sample is with the gcp storage bucket.

# What I get

In my terraform code I put like this my var psk tu use environment TF_VAR syntaxe to be safer :

```hcl
# Will be complete using env var TF_VAR_psk
variable "psk" { 
  sensitive = true
}

resource "google_compute_vpn_tunnel" "primary" {
  for_each                        = google_compute_ha_vpn_gateway.onprem
  project                         = local.account_ids[terraform.workspace]
  name                            = "vpn-onprem-primary-${lower(each.key)}"
  region                          = var.region
  peer_external_gateway           = google_compute_external_vpn_gateway.vpni-cloudpartners[each.key].id
  peer_external_gateway_interface = 0
  shared_secret                   = var.psk # here where I use it

  vpn_gateway           = each.value.id
  vpn_gateway_interface = 0
  router                = google_compute_router.vpn[each.key].id
}
```

And I have in the state stuff like this : 

```json
            "shared_secret": "<mysecretasplaintext>", # should not be there
            "shared_secret_hash": "AEhrfpxmMo_A6A0k2yG5A3By22aE",
            "vpn_gateway_interface": 0
          },
          "sensitive_attributes": [
            [
              {
                "type": "get_attr",
                "value": "shared_secret"
              }
            ]
```

# What I expect 

For me sould be better to not store the plain text value and use only hash comparison

```json
            "shared_secret_hash": "AEhrfpxmMo_A6A0k2yG5A3By22aE",
            "vpn_gateway_interface": 0
          },
          "sensitive_attributes": [
            [
              {
                "type": "get_attr",
                "value": "shared_secret"
              }
            ]
```

Regards Marc.

**Comment by jbardin** [comment]
Hi @Maarc-D,

Thanks for filing the issue. The implementation for sensitive values is only meant to help prevent their display in normal CLI usage, it does not prevent the storage fo the values in the state. Terraform cannot store only the hash of the value, because the original value is required for terraform's operation. We do have plans for improved handling of these values, and the proposals for handling of sensitive values in general are being tracked in #9556 and #516. See also #28263.

Thanks!
