### ISSUE TITLE
Slash gets replace by the current directory when importing a resource into the state - happens also with quotes

### ISSUE THREAD

**Issue by DenWin** [hashicorp/terraform#28291]
Hi,

@jbardin: I am aware about quotes. I just forgot them in the demo. Same behavior with single quotes, double quotes and escaped quotes. I also added shell debugging this time. It is NOT the shell that adds the path it is Terraform, or most likely it is Go as part of Terraform.

when I try to execute:
`terraform import azurerm_resource_group.rg $'/subscriptions/000000-0000-0000-0000-000000000000/resourceGroups/prtl-mo-rg'` it the leading slash before "subscription" gets replace by the current path I'm in.

![image](https://user-images.githubusercontent.com/13867326/113715193-7df9c780-96e9-11eb-88da-9eed989a62d8.png)

This specific behavior only occurs when I execute this in Bash for Windows.
If I run it in Linux everything works fine.
If I run it in Powershell on Windows: Works

But running it in Bash for Windows causes this odd behavior.

My terraform file:
```
terraform {
    required_providers {
        azurerm = {
            source = "hashicorp/azurerm"
            version = "<=2.53.0"
        }
    }
}

provider "azurerm" {
    # Configuration options
    features {}
}

resource azurerm_resource_group rg {
    name = "prtl-mo-rg"
}
```

I was able to boil it down to the fact, that it seems to already be read in improperly by Go according to the output in the TRACE Log:
```
2021/04/06 15:02:01 [INFO] Terraform version: 0.14.7  
2021/04/06 15:02:01 [INFO] Go runtime version: go1.15.6
2021/04/06 15:02:01 [INFO] CLI args: []string{"C:\\ProgramData\\chocolatey\\lib\\terraform\\tools\\terraform.exe", "import", "azurerm_resource_group.rg", "C:/Program Files/Git/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/prtl-mo-rg"}
```

The corresponding lines in Terraform in main.go (line 142-146):
```
	log.Printf(
		"[INFO] Terraform version: %s %s",
		Version, VersionPrerelease)
	log.Printf("[INFO] Go runtime version: %s", runtime.Version())
	log.Printf("[INFO] CLI args: %#v", os.Args)
```

I'm not 100% sure, whether this is a something to be tracked here and forwarded into the Go-Issue board, or whether it should be entered there directly.
At the very least, if someone has the same issue with Terraform here is why.

**Comment by jbardin** [comment]
Hi @DenWin,

I understand that the behavior here is not what you expect, but like you've demonstrated, there is nothing that terraform can do in this case because the argument has already been altered by the shell. A quick search for this behavior turns up the git-bash release notes with known issues here https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues:

> If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "/usr/bin/bash.exe" to "C:\Program Files\Git\usr\bin\bash.exe". When that is not desired -- e.g. "--upload-pack=/opt/git/bin/git-upload-pack" or "-L/regex/" -- you need to set the environment variable MSYS_NO_PATHCONV temporarily, like so:

> `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`
Alternatively, you can double the first slash to avoid POSIX-to-Windows path conversion, e.g. "//usr/bin/bash.exe".

**Comment by DenWin** [comment]
@jbardin: But why do both options MSYS_NO_PATHCONV and the double slash do not do the trick?

![image](https://user-images.githubusercontent.com/13867326/113721562-ed72b580-96ef-11eb-95fa-8851d87723a7.png)

The problem seems to be within.

**Comment by DenWin** [comment]
Actually the double-slash might do, but the odd number of segments seems to be - once again - an issue within Terraform as the string the error message provides does not have an odd number of segments.

**Comment by DenWin** [comment]
The error most have been on my site - second try it worked.

@jbardin: Thx for the link, I have searched the web up and down to find exactly this and thought in the end it was terraform.
Seems I didn't had the proper angle and/or search terms.
