### ISSUE TITLE
Dynamic block statement: Ensure iteration order

### ISSUE THREAD

**Issue by chris922** [hashicorp/terraform#28304]
### Current Terraform Version

```
Terraform v0.14.2
```

### Use-cases
We use the AWS provider to provision Glue Tables via resource `aws_glue_catalog_table`.
This table contains `columns` blocks (see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_catalog_table#column).

We would like to dynamically create the column blocks based on an input variable as we would like to move the table generation to a Terraform module.

### Attempted Solutions

Following an extract how our resource looks like:

```hcl
resource "aws_glue_catalog_table" "table" {
  storage_descriptor {

    dynamic "columns" {
      for_each = {for column in var.columns: column.name => column}

      content {
        name    = columns.key
        type    = columns.value.type
        comment = columns.value.comment
      }
    }
  }
}
```

In general, it works, but unfortunately, the order of the columns is getting lost. We need to keep the order as it is important for us to have it correct in the Glue catalog.

The issue is that we have to use `dynamic` to create the _n_-`columns` blocks and by doing so we could only use `for_each`. Unfortunately, this expects a map or a set and both are always unordered, so I am not able to find any solution to solve this issue.

### Proposal
I see the following possible solutions:

1. Add also `count` to `dynamic` statements so that we can iterate over a list that has a fixed order
2. Introduce a kind of `count.index` that contains the index of the current iteration, with this we can then access our input map so that we access this one in order
3. Introduce ordered maps
4. Allow assigning lists to blocks like it was available prior Terraform v0.12 (see [here](https://www.terraform.io/docs/language/attr-as-blocks.html#arbitrary-expressions-with-argument-syntax))

I personally would prefer the first idea. The second one feels like a workaround and the third one sounds like a much bigger topic for the overall Terraform HCL design.
The fourth one would be fine for me, but I guess there were some good reasons in the past to remove this possibility... even if it would give us back a lot of flexibility.

### References
_nothing_

**Comment by chris922** [comment]
Oh wow! I just found the solution.. the `for_each` within `dynamic` behaves differently than the one in `resource`/`module` .. it accepts a list and doesn't need a map or set 😮 

I just checked the documentation and it states that _"`for_each` argument accepts any collection or structural value"_ 

Nevertheless there is one paragraph (the one that I read) that says `for_each` expects maps or sets:

> The for_each value must be a map or set with one element per desired nested block. If you need to declare resource instances based on a nested data structure or combinations of elements from multiple data structures you can use Terraform expressions and functions to derive a suitable value. For some common examples of such situations, see the flatten and setproduct functions.
> 
> _(https://www.terraform.io/docs/language/expressions/dynamic-blocks.html)_

I think this whole paragraph in the documentation can be removed, WDYT?
Maybe instead of this clearly state that this `for_each` behaves differently than the one for `resource`/`module`.

**Comment by apparentlymart** [comment]
Funnily enough, I independently noticed and fixed that documentation mistake in #28243 last week, and so at least _that_ problem will be addressed shortly as part of the forthcoming v0.15.0 release.

As I mentioned over in that PR, the main thing this paragraph is trying to do is draw attention to the `flatten` and `setproduct` functions, and so I elected to keep the paragraph but generalize the confusing part that was talking about specifically which types it supports.

**Comment by chris922** [comment]
Ah, that sounds great and your rather small change in the documentation should definitely make it more clear! 

I guess we can then close this issue or would you like to keep it open for some other tasks left towards this? If not feel free to close it :)

**Comment by apparentlymart** [comment]
Hi @chris922,

I must admit that on my first read I was reacting directly to your latest comment about the documentation and didn't read the original issue report in detail, because I thought the documentation comment was _in addition to_ the bug report, but I see now that you were instead sharing how you found the solution to the problem you had and what about the documentation made you not see that answer initially.

Given that, I'm going to close this now. Hopefully the documentation update I linked to will help avoid similar confusion in the future, and if not we'll decide how to deal with that in response to future issues. :grinning: Thanks!
