### ISSUE TITLE
file function has size limit 

### ISSUE THREAD

**Issue by sce81** [hashicorp/terraform#28305]
Hi, i am trying to use data.archive_file to create a zip file for use with Lambda. unfortunately i am hitting a maximum size limit which I believe should have been fixed/increased but this does not seem to be the case. 

```
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (88035971 vs. 4194304)



Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0



data "local_file" "foo" {
    filename = "${path.module}/files/functionbeat/${var.functionbeat_version}/pkg/functionbeat-aws"
}


data "archive_file" "functionbeat" {
  type        = "zip"
  output_path = "${path.module}/files/zip/functionbeat.zip"

    source {
        content = data.local_file.foo.content_base64
        filename = "functionbeat-aws"

    }

  source {
    content  = file("${path.module}/files/functionbeat/${var.functionbeat_version}/functionbeat.yml")
    filename = "functionbeat.yml"   
  }
}
```

**Comment by apparentlymart** [comment]
Hi @sce81,

Could you include a debug/trace log as was requested in the issue template? That would allow us to see exactly which component failed here. This is a limit that can be enforced either on the client or server end of the RPC protocol, with different values, and so a change to make this work for you might need to happen either in Terraform Core or in one of these two providers you are using.

With that said, I would typically recommend against passing around large strings in memory like this. Depending on which component is failing here, we might be best to solve this by extending the `archive_file` data source to allow passing a path to an existing source file on disk which it'll read directly, and then you'd no longer need to do this awkward pattern of reading the file into memory first just to pass it back to a file on disk anyway. For example:

```hcl
    source {
        from_file = "${path.module}/files/functionbeat/${var.functionbeat_version}/pkg/functionbeat-aws"
        filename  = "functionbeat-aws"
    }
```

It's unfortunate that the existing argument is called just `filename`, making it ambiguous to potentially have two arguments that both accept a filename, but I think we could make that clear enough in the documentation if it came to it.

**Comment by sce81** [comment]
hey.. i have changed my code to take the artifact from a bucket. which in my use case really doesn't work well. what i would like to do is package up a binary with a configuration file, but parameterise the configuration file using terraform. But this breaks due to the file size limitation. which i hit however i use the file() command. 
IMO i feel that 0.5MB is _far_ too small a limit and given modern computing power, a few tens or hundreds of megabytes is not a large amount of data to be storing in memory temporarily. 
I did read somewhere that you had increased the size limit to 64MB which would have been enough for my use case...

**Comment by crw** [comment]
I am going to close this one as no trace log was posted and thus no further progress can be made to evaluate this issue. Per:

> Could you include a debug/trace log as was requested in the issue template? That would allow us to see exactly which component failed here. This is a limit that can be enforced either on the client or server end of the RPC protocol, with different values, and so a change to make this work for you might need to happen either in Terraform Core or in one of these two providers you are using.

https://github.com/hashicorp/terraform/issues/28305#issuecomment-815384676

Thanks!
