### ISSUE TITLE
`configuration_aliases` in required_providers uses only one provider for data source

### ISSUE THREAD

**Issue by marshall7m** [hashicorp/terraform#28324]
### Terraform Version

```
Terraform v0.15.0-rc2
```

### Terraform Configuration Files

```terraform
module "mut" {
    source = "..//foo"
    providers = {
      aws.one = aws.master
      aws.two = aws.logs
     }
}

provider "aws" {
  alias   = "master"
  profile = "entrypoint-admin"
  region = "us-west-2"
}

provider "aws" {
  alias   = "logs"
  profile = "sandbox-admin"
  region = "us-west-2"
}

output "one_id" {
    value = module.mut.one_id
}

output "two_id" {
    value = module.mut.two_id
}
```

Within target module `..//foo`:

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.36"
      configuration_aliases = [
        aws.one, 
        aws.two
      ]
    }
  }
}

data "aws_caller_identity" "one" {
    provider = aws.one
}

data "aws_caller_identity" "two" {
    provider = aws.two
}

output "one_id" {
    value = data.aws_caller_identity.one.id
}

output "two_id" {
    value = data.aws_caller_identity.two.id
}
```

### Expected Behavior

```
Changes to Outputs:
  + one_id = "111111111111"
  + two_id = "222222222222"
```
### Actual Behavior

```
Changes to Outputs:
  + one_id = "111111111111"
  + two_id = "111111111111"
```
### Steps to Reproduce

Within the Terraform configuration calling the module:
1. `terraform init`
2. `terraform apply`
### Additional Context

- Using [aws-vault](https://github.com/99designs/aws-vault) to execute terraform commands (e.g. `aws-vault exec marshall -- terraform init`). The AWS profile `marshall` is verified to use the AWS profiles defined within the two provider blocks above.

**Comment by jbardin** [comment]
Hi @marshall7m,

Thanks for filing the issue. I'm not able to reproduce this locally, and a few different combinations of provider settings and data sources have all produced the expected output. Can you verify that there is nothing in your environment overriding the provider authentication when executing `terraform plan` or `apply`?

**Comment by marshall7m** [comment]
> Hi @marshall7m,
> 
> Thanks for filing the issue. I'm not able to reproduce this locally, and a few different combinations of provider settings and data sources have all produced the expected output. Can you verify that there is nothing in your environment overriding the provider authentication when executing `terraform plan` or `apply`?

Thanks @jbardin for the reply. My environment is pretty straightforward. I'm only using aws-vault for passing the AWS profile to use for executing terraform commands. If it helps, here's my `~/.aws/config` file: 

```
[profile marshall]
mfa_serial = arn:aws:iam::111111111111:mfa/Marshall
region = us-west-2
output = json

[profile entrypoint-admin]
source_profile = marshall
role_arn = arn:aws:iam:: 111111111111:role/cross-account-admin-access
mfa_serial = arn:aws:iam:: 111111111111:mfa/Marshall
region = us-west-2
output = json

[profile sandbox-admin]
source_profile = marshall
role_arn = arn:aws:iam:: 222222222222:role/cross-account-admin-access
mfa_serial = arn:aws:iam:: 111111111111:mfa/Marshall
region = us-west-2
output = json
```

And then my `~/.aws/credentials` file contains the credentials for the `marshall` profile. 

After some experiments, I found out that the problem is probably not caused by `configuration_aliases` feature. The problem is even the case when I define the configuration below:

```
provider "aws" {
  alias   = "master"
  profile = "sandbox-admin"
  region = "us-west-2"
}

data "aws_caller_identity" "current" {
    provider = aws.master
}

output "foo" {
    value = data.aws_caller_identity.current.id
}
```

Expected output: 
```
Changes to Outputs:
  + foo = "222222222222"
```

Actual output: 
```
Changes to Outputs:
  + foo = "111111111111"
```

I'm not too familiar with how aws-vault works internally but I'm thinking aws-vault somehow overwrites the provider configuration with the profile used to exec aws-vault with. Given my assumption, I'll post this issue on aws-vault's issue page.

**Comment by marshall7m** [comment]
Defining an IAM role for each provider via the `assume_role` block did the trick like so:

```
provider "aws" {
  alias   = "master"
  region = "us-west-2"
  assume_role {
    role_arn = "arn:aws:iam::111111111111:role/cross-account-admin-access"
  }
}

provider "aws" {
  alias   = "logs"
  region = "us-west-2"
  assume_role {
    role_arn = "arn:aws:iam::222222222222:role/cross-account-admin-access"
  }
}
```
