### ISSUE TITLE
Unable to Unmark Provider-Based Sensitive Value With nonsensitive()

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform#28321]
### Terraform Version

```console
$ terraform version
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

$ terraform0.15.0-rc2 version
Terraform v0.15.0-rc2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

Initial discovery with `aws_ssm_parameter` resource:

```terraform
terraform {
  required_version = ">= 0.14.10"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.35.0"
    }
  }
}

provider "aws" {
  region = "us-east-2"
}

resource "aws_ssm_parameter" "example" {
  name  = "bflad-testing"
  type  = "String"
  value = "not-actually-sensitive-value"
}

# locals {
#   nonsensitive_value = nonsensitive(aws_ssm_parameter.example.value)
# }

output "parameter_value" {
  value = aws_ssm_parameter.example.value
  # sensitive = true
  # value = nonsensitive(aws_ssm_parameter.example.value)
  # value = local.nonsensitive_value
}
```

Additional reproduction with `random_password`:

```terraform
terraform {
  required_version = ">= 0.14.10"
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "3.1.0"
    }
  }
}

resource "random_password" "example" {
  length = 16
}

output "bare" {
  value = random_password.example.result
}

output "sensitive_true" {
  sensitive = true
  value     = random_password.example.result
}

output "nonsensitive_function" {
  value = nonsensitive(random_password.example.result)
}

locals {
  nonsensitive_value = nonsensitive(random_password.example.result)
}

output "local_nonsensitive" {
  value = local.nonsensitive_value
}
```

### Debug Output

Can provide if needed. 😄 

### Expected Behavior

When upgrading from Terraform CLI 0.14 to Terraform CLI 0.15 that there is a method for unhiding a provider-based sensitive value, e.g.

```
Outputs:

parameter_value = "not-actually-sensitive-value"
```

```
Outputs:

nonsensitive_function = "$rt8Sq7vkSzYkJU2"
```

### Actual Behavior

Upgrading to Terraform CLI 0.15 forces `sensitive = true` for attributes:

```
╷
│ Error: Output refers to sensitive values
│ 
│   on main.tf line 15:
│   15: output "bare" {
│ 
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
╵
```

Attempting to use the `nonsensitive()` function always returns an error, whether its in the output directly or a local:

```
│ Error: Invalid function argument
│ 
│   on main.tf line 25, in output "nonsensitive_function":
│   25:   value = nonsensitive(random_password.example.result)
│     ├────────────────
│     │ random_password.example.result will be known only after apply
│ 
│ Invalid value for "value" parameter: the given value is not sensitive, so this call is redundant.
╵
╷
│ Error: Invalid function argument
│ 
│   on main.tf line 29, in locals:
│   29:   nonsensitive_value = nonsensitive(random_password.example.result)
│     ├────────────────
│     │ random_password.example.result will be known only after apply
│ 
│ Invalid value for "value" parameter: the given value is not sensitive, so this call is redundant.
╵
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

The Terraform Plugin SDK does not provide functionality to conditionally mark or unmark sensitive attributes. In numerous cases, provider developers have had to compromise by marking certain attributes with `Sensitive: true` in their schema while the value may not be always sensitive. Given this, some practitioners may desire their existing workflows with visible value output.

It might be good to give a shout out for this change in the Terraform CLI 0.15 upgrade guide, since sensitivity currently has no mentions.

For what it is worth, it is still possible to use `terraform output` to get the `sensitive = true` unprotected value:

```console
$ terraform0.15.0-rc2 output sensitive_true
"$rt8Sq7vkSzYkJU2"
$ terraform0.15.0-rc2 output -raw sensitive_true
$rt8Sq7vkSzYkJU2%                                    
$ terraform0.15.0-rc2 output -json sensitive_true
"$rt8Sq7vkSzYkJU2"
```

Which seems to make sense, but if this is the desired new behavior instead of allowing `nonsensitive()`, it might be worth calling that out too.

### References

- https://github.com/hashicorp/terraform-provider-aws/issues/9090

**Comment by alisdair** [comment]
Thanks for reporting this, @bflad! I've confirmed locally (with the `random_password` example, thanks for that), although I'm not quite sure why this is happening.

**Comment by alisdair** [comment]
There's a bit of an explanation in #28326, but I'll attempt another summary here. This error is arising in the validate walk before the plan walk, at which point we only have an unknown value for the resource, which therefore cannot have its sensitive attributes marked as such. This makes the `nonsensitive` function fail, as on this walk the value passed to it isn't sensitive.

Having chatted with a few folks, I don't think there's any good way around this, other than removing the `nonsensitive` restriction, which is what I've done in the linked PR.
