### ISSUE TITLE
Can't splat over a resource's list attribute

### ISSUE THREAD

**Issue by thegedge** [hashicorp/terraform#2833]
The best example is for elasticache:

```
resource "aws_elasticache_cluster" "memcache" {
   …
}

output "cache_nodes" {
  value = "${join(",', aws_elasticache_cluster.memcache.cache_nodes.*.address)}"
}
```

When testing locally with our own stacks, cache_nodes isn't even an output when I do the above. For now we've simply restricted the cluster size to 1 and access the cache_node directly.

**Comment by maxrothman** [comment]
Any movement on being able to splat over list attributes?

**Comment by apparentlymart** [comment]
This will be supported in [the next major version of Terraform](https://www.hashicorp.com/blog/terraform-0-1-2-preview), as described in [the _Generalized Splat Expressions_ article](https://www.hashicorp.com/blog/terraform-0-12-generalized-splat-operator).

**Comment by apparentlymart** [comment]
In Terraform v0.12-alpha1 we can see the new "generalized splat" behavior working for all list values:

```hcl
locals {
  example = [
    {
      id = "foo"
    },
    {
      id = "bar"
    },
    {
      id = "baz"
    },
  ]
}

output "example" {
  value = local.example.*.id
}
```

```
$ terraform output
example = [
  "foo",
  "bar",
  "baz",
]
```

Although the above uses a local value list for simplicity, the splat expression syntax can now be applied to any list value, regardless of where it is obtained from.
