### ISSUE TITLE
Terraform - Duplicate Output Definition, but there is not duplicate

### ISSUE THREAD

**Issue by manmedia** [hashicorp/terraform#28336]
I had a terraform `main.tf` file for a module, where I previously added outputs e.g.

```
    output "ids" {
      value       = some_resource.name.value
      description = something 
    }
```

I have now moved the above block to a separate `outputs.tf` file for cleanliness. But I am getting the following error:

```
    Error: Duplicate output definition
    
      on modules/my/outputs.tf line 1:
      11: output "ids" {
    
    An output named "ids" was already defined at modules/my/main.tf:11,1-13.
    Output names must be unique within a module.
```

This doesn't make any sense. Is this something like a local cache messup? Or, am I not allowed to do this refactoring (I'm sure I can)...? I am using version 0.14.4

Any help is appreciated.

Regards,

**Comment by alisdair** [comment]
Hi @manmedia. I can't reproduce the issue you're describing here. If you can reproduce the problem, please edit your report a sample configuration with reproduction steps, [using the issue template](https://raw.githubusercontent.com/hashicorp/terraform/main/.github/ISSUE_TEMPLATE/bug_report.md), and we can look into it.

**Comment by manmedia** [comment]
I will close this issue because this was a problem due to VS Code not being able to collate changes on disk. I have resolved it since then. All sorted!
