### ISSUE TITLE
Expressions in dynamic blocks don't create references in the plan JSON

### ISSUE THREAD

**Issue by aliscott** [hashicorp/terraform#28346]
### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.36.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = "us-east-1"
}


variable "worker_groups_launch_template" {
  type = list
  default = [
    {
      launch_template_version = "$Latest"
    },
    {
      launch_template_version = "1"
    }
  ]
}

resource "aws_launch_template" "workers_launch_template" {
  count = 2
  image_id      = "ami-0b55b3040fb5668a3"
  instance_type = "t2.medium"
}

resource "aws_autoscaling_group" "workers_launch_template" {
  count = 2
  min_size = 1
  max_size = 3
  
  dynamic "launch_template" {
    iterator = item
    for_each = list(var.worker_groups_launch_template[count.index])

    content {
      id = aws_launch_template.workers_launch_template.*.id[count.index]
      version = lookup(
        var.worker_groups_launch_template[count.index],
        "launch_template_version",
        "$Latest"
      )
    }
  }
}
```

### Expected Behavior

The plan JSON contains an expression and reference for the `launch_template` field, like:

```js
{
  // ...
  "configuration": {
    // ...
    "root_module": {
      "resources": [
        {
          "address": "aws_autoscaling_group.workers_launch_template",
          // ...
          "expressions": {
            "launch_template": [
              {
                "id": {
                  "references": [
                    "aws_launch_template.workers_launch_template",
                    "count.index"
                  ]
                },
                "version": {
                  "references": [
                    "var.worker_groups_launch_template",
                    "count.index"
                  ]
                }
              },
            ],
            "max_size": {
              "constant_value": 3
            },
            "min_size": {
              "constant_value": 1
            }
            // ...
```

### Actual Behavior

The plan JSON does not contain any expressions for the `launch_template` field:

```js
{
  // ...
  "configuration": {
    // ...
    "root_module": {
      "resources": [
        {
          "address": "aws_autoscaling_group.workers_launch_template",
          // ...
          "expressions": {
            "max_size": {
              "constant_value": 3
            },
            "min_size": {
              "constant_value": 1
            }
          },
          // ...
```

### Steps to Reproduce

1. terraform init
2. terraform plan -save plan.tfplan
3. terraform show -json plan.tfplan | jq

**Comment by apparentlymart** [comment]
Hi @aliscott! Thanks for reporting this.

Could you also share what the non-JSON plan output looks like for this plan? That is, run `terraform show` without the `-json` option when generating it. I'm wondering if this is a situation where Terraform doesn't have enough information to know how many `launch_template` blocks will be generated yet, and so the entire processing of that block is being deferred until the apply step. In that case, unfortunately the information Terraform has is limited here and it's unlikely that we'll be able to achieve exactly the result you expected, but we might be able to achieve something similar that approximates it.

**Comment by aliscott** [comment]
Hi @apparentlymart, thanks. Here is the non-JSON plan output:
```
  # aws_autoscaling_group.workers_launch_template[0] will be created
  + resource "aws_autoscaling_group" "workers_launch_template" {
      + arn                       = (known after apply)
      + availability_zones        = (known after apply)
      + default_cooldown          = (known after apply)
      + desired_capacity          = (known after apply)
      + force_delete              = false
      + health_check_grace_period = 300
      + health_check_type         = (known after apply)
      + id                        = (known after apply)
      + max_size                  = 3
      + metrics_granularity       = "1Minute"
      + min_size                  = 1
      + name                      = (known after apply)
      + protect_from_scale_in     = false
      + service_linked_role_arn   = (known after apply)
      + vpc_zone_identifier       = (known after apply)
      + wait_for_capacity_timeout = "10m"

      + launch_template {
          + id      = (known after apply)
          + name    = (known after apply)
          + version = "$Latest"
        }
    }

  # aws_autoscaling_group.workers_launch_template[1] will be created
  + resource "aws_autoscaling_group" "workers_launch_template" {
      + arn                       = (known after apply)
      + availability_zones        = (known after apply)
      + default_cooldown          = (known after apply)
      + desired_capacity          = (known after apply)
      + force_delete              = false
      + health_check_grace_period = 300
      + health_check_type         = (known after apply)
      + id                        = (known after apply)
      + max_size                  = 3
      + metrics_granularity       = "1Minute"
      + min_size                  = 1
      + name                      = (known after apply)
      + protect_from_scale_in     = false
      + service_linked_role_arn   = (known after apply)
      + vpc_zone_identifier       = (known after apply)
      + wait_for_capacity_timeout = "10m"

      + launch_template {
          + id      = (known after apply)
          + name    = (known after apply)
          + version = "1"
        }
    }

  # aws_launch_template.workers_launch_template[0] will be created
  + resource "aws_launch_template" "workers_launch_template" {
      + arn             = (known after apply)
      + default_version = (known after apply)
      + id              = (known after apply)
      + image_id        = "ami-0b55b3040fb5668a3"
      + instance_type   = "t2.medium"
      + latest_version  = (known after apply)
      + name            = (known after apply)

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }
    }

  # aws_launch_template.workers_launch_template[1] will be created
  + resource "aws_launch_template" "workers_launch_template" {
      + arn             = (known after apply)
      + default_version = (known after apply)
      + id              = (known after apply)
      + image_id        = "ami-0b55b3040fb5668a3"
      + instance_type   = "t2.medium"
      + latest_version  = (known after apply)
      + name            = (known after apply)

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }
    }

Plan: 4 to add, 0 to change, 0 to destroy.
```

**Comment by alisdair** [comment]
Hi @aliscott, thanks for reporting this. The JSON configuration output currently doesn't support `dynamic` blocks, as noted in a code comment here: https://github.com/hashicorp/terraform/blob/95b86bf7ad814b5859e51f9fbaaeb2a29a361e4a/command/jsonconfig/expression.go#L69-L73

We should update the JSON plan documentation to include that limitation.

I'm not sure it's feasible to add support for `dynamic` blocks here, as this section of the JSON plan is rendering the configuration as written. We don't have access to an evaluation context with which to convert the dynamic blocks into their static equivalents.

I'd be interested to know more about what your underlying use case is here, as it would help us to plan what we could do to help here in future.

**Comment by aliscott** [comment]
Hi @alisdair thanks!

We've had Infracost users hit this issue when trying to use Infracost with some of the third-party [terraform-aws-modules](https://github.com/terraform-aws-modules). See the issue here: https://github.com/infracost/infracost/issues/425.

Internally Infracost uses the Terraform plan JSON to find the relationships between all the resources and find the attributes for each resource that have a potential cost. So if we have Terraform code like this:

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_default_vpc" "default" {
}

data "aws_subnet_ids" "default" {
  vpc_id = aws_default_vpc.default.id
}

module "my-cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = "my-cluster"
  cluster_version = "1.17"
  subnets         = data.aws_subnet_ids.default.ids
  vpc_id          = aws_default_vpc.default.id

  worker_groups_launch_template = [
    {
      instance_type = "m4.large"
      asg_desired_capacity  = 5
    },
  ]
}
```

The `my-cluster` module creates an `aws_autoscaling_group` and an `aws_launch_template` resource. The cost of the `aws_autoscaling_group` depends on attributes from the `aws_launch_template` resource. Normally, we could use the plan JSON to find the relationship between these resources by looking for `references` in the configuration expressions.

But the terraform-aws-modules/eks/aws module use a [dynamic block](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers_launch_template.tf#L165-L177) to specify the launch template for the autoscaling group. So for this case, we don't have any information in the plan JSON that links the `aws_autoscaling_group` and `aws_launch_template` resources.

For this specific module we could work round it by matching on known resource names, but this wouldn't work in the more general case.

**Comment by apparentlymart** [comment]
The HCL dynamic blocks extension (which is what Terraform's feature is built with) does have a helper function [`dynblock.VariablesHCLDec`](https://pkg.go.dev/github.com/hashicorp/hcl/v2/ext/dynblock#VariablesHCLDec) which can in principle extract the necessary "variables" (in Terraform's terms: references). This is what Terraform does internally in order to learn that e.g. `aws_autoscaling_group.workers_launch_template` depends on `var.worker_groups_launch_template` in the original example here.

Unfortunately it does this only for the entire resource configuration at once, not for the individual arguments. The JSON configuration output is trying to act at a different level of abstraction than what the Terraform runtime would do in order to give some more details, but it seems that this comes at the cost of not handling `dynamic` blocks because they don't fit into the assumptions it's making.

Knowing now what's going on underneath this feature I'm also unsure about how we could improve on it within the existing technical constraints. The configuration description is always a best-effort because it's trying to represent some concepts that don't really fit well into a simple JSON rendering.

Unfortunately cost estimation of a plan is a tricky use-case to meet reliably because, as we can see here, there's various information that we don't know until final apply and thus we need to rely on heuristics to infer what the likely result will be. I think a practical cost estimation system built around plans must unfortunately allow for certain information just not being known at all and be able to somehow report the uncertainty to the user so they can account for it. Hopefully we can find a way to improve the precision of this particular case to give the infracost heuristics more information to work from, but I don't think this can ever be totally dependable because there will always be cases where we can't even know how many blocks the dynamic block will generate until apply time. :confounded:
