### ISSUE TITLE
vmware / terraform-provider-vra7 Provider is considerind the computed values as changes in the resource even though there is no update which has taken place

### ISSUE THREAD

**Issue by divya-goyal** [hashicorp/terraform#28347]
Hi there,

I am using vmware / terraform-provider-vra7 version 3.0.2, facing an issue with the the way terraform evaluate the difference for the newly created resource.

For example, we provide the module with the expected input to create a VM in Vshere, and successfully get the VM created as well in return we receive the extended set of variables which gets computed as output which is more then the ones which has been submitted with the request to create the VM.

Now, if the vm gets updated in the backend, and we try to submit the request again without any changes to the resource in that case we gets too many differences which impacts the day 2 operation as we didnt have those values as input.

### Terraform Version
Run `terraform version` 0.14

### Terraform Configuration Files
Terraform config files cant be uploaded due to security. but from reference perspective all the standard config has been used. for provider username, password and tenant value has been passed to the provider to create the resource in the vsphere.

After, resource gets successfully provisioned, terraform returns with the output with all the computed values and th outout gets stored in the tf.state file.

Now, if we run terraform apply, the provided shows up multiple difference in console even though there is no update to the resource. Only difference is the provided input and computed values after the resource provisioning is different. 

### Debug Output
Cant update the output file here. 

On running the terraform plan, there should not be any difference.

### Expected Behavior
As there is no update in the resource when we run the terraform plan on an already created resource there should not be any difference. 

### Actual Behavior
1. First step is to create a resource.
2. After resource creation run the, Teraform plan or apply comes back with multiple differences in resource state. Even though there is no update for the resource. 

### Steps to Reproduce
1. Configure vra 7 provider.
2. run 
terraform init 
terraform plan
terraform apply
3. vm should get created.
4. Once the resource gets created successfully. Run below command without making any update to resource
terraform init
terraform apply
5. Console comes back with multiple difference even though there is no update in the resource.

**Comment by jbardin** [comment]
Hi @divya-goyal,

Issues with providers should be filed directly with that provider's developers. The issue tracker for the vra7 provider is located here: https://github.com/vmware/terraform-provider-vra7/issues

Thanks!
