### ISSUE TITLE
Providers cannot always correctly plan values within dynamic blocks

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#28340]
### Background

The handling of [`dynamic` blocks](https://www.terraform.io/docs/language/expressions/dynamic-blocks.html) within Terraform does not expose enough information to providers to create correct initial plans in all cases. 

Dynamic blocks themselves only exist within the Terraform configuration language, and are solely handled by the Terraform CLI, which uses the information to generate the complete configuration to be sent to the provider. A provider has no insight into how dynamic blocks are used, and will apply the same rules when planning resources for dynamic blocks, as it would for any number of literal blocks written into the configuration. 

This is normally not a problem, as the plan generated by Terraform is sufficient for most resources, however if a provider wishes to customize the planning of the resource, the protocol offers no way to indicate to the provider that the block data may not be complete. With the legacy SDK this is most commonly caused by providers adding a `Default` or `DefaultFunc` to a block attribute, which is inserted into the block value during planning, and prevents Terraform from properly expanding that dynamic value. 

Because the provider is altering a plan value which is not yet known, it often results in an error of 

    Error: Provider produced inconsistent final plan

With the details indicating that the block contains elements which cannot be correctly correlated with the plan, or the length of the container changed unexpectedly. 

### Workarounds

During the 0.12 transition, many providers initially changed some blocks to use the SDK `SchemaConfigModeAttr`, which allows the attribute-like assignment of the block values and for-expressions to be used directly. This particular workaround is harder to implement moving forward, as the volume of configuration in production has increased significantly and subtle breaking changes across existing configurations can have a large impact on users.

The recommendation for providers has been to not alter the block data during planning if compatibility with the `dynamic` feature was desired. The behavior of the legacy SDK often made that difficult however, as it is not obvious that builtin features like `Default` can also hinder the ability to correctly handle the planning requests. 

### Proposal

While this is the result of the SDK or providers unexpectedly altering the plan data, we need to be able to handle blocks using `dynamic` completely within the  Terraform CLI, allowing existing providers to work transparently with any valid configuration. There is no representation of dynamic blocks in the protocol, nor can the legacy SDK be retrofitted to handle new data types that could be used. While the next generation provider SDK will primarily focus on complex attributes as the primary data structure, if blocks are to be used at all, a protocol for handling unknown blocks during plan must be devised there as well.

A solution will need to take into account the ability to correctly plan these values with a new SDK, while allowing for the existing behavior of the legacy SDK.

# References

This is not an exhaustive list, only a small number of examples from the major providers which appear to be caused by the SDK or provider altering dynamic block data during the plan:

#### Google
https://github.com/hashicorp/terraform-provider-google/issues/8826
https://github.com/hashicorp/terraform-provider-google/issues/3937
https://github.com/hashicorp/terraform-provider-google/issues/3498

#### AzureRM
https://github.com/terraform-providers/terraform-provider-azurerm/issues/10984
https://github.com/terraform-providers/terraform-provider-azurerm/issues/9923
https://github.com/terraform-providers/terraform-provider-azurerm/issues/7000
https://github.com/terraform-providers/terraform-provider-azurerm/issues/6254

#### AWS
https://github.com/hashicorp/terraform-provider-aws/issues/15210
https://github.com/hashicorp/terraform-provider-aws/issues/14456
https://github.com/hashicorp/terraform-provider-aws/issues/13865

### Related Issues

We also need to investigate the interactions with `DiffSuppressFunc` and `SchemaSetFunc`, which may be able to trigger the same issue. 

An example of using `DiffSuppressFunc`:
https://github.com/hashicorp/terraform-provider-aws/issues/16674

Another example with `SchemaSetFunc`:
https://github.com/hashicorp/terraform-provider-aws/issues/14085

**Comment by jbardin** [comment]
@magodo, Removing the `Default` value doesn't leave anything unusual about the block, and we know that `dynamic` currently works for most other resources. I suspect there's something else at play there, perhaps just a mistake in the `for_each` value?

**Comment by magodo** [comment]
@jbardin As the config shows in both issues above, the iterator of the dynamic block comes from a data source, where the data source is not known at the first apply. Therefore, the first apply will cause the reported error, whilst a second run will work (even with `default` defined), since the resource corresponding to the data source is provisioned at the first apply (IMO, the config in the #25600 is a simplified one that has less noise).

**Comment by jbardin** [comment]
@magodo, I have confirmed that the example in 25600 is correctly planning the dynamic blocks, and the value being sent contains 2 values. My only guess here is that by when you removed the `Default` attribute value, the provider is filtering the objects and considering no block values as being set.

**Comment by magodo** [comment]
@jbardin It seems to be the case. Is there anyway I can do on provider side to fix this?

**Comment by jbardin** [comment]
@magodo, I'm not familiar with the that providers internals, but it looks like you either need to not reject the values here[https://github.com/terraform-providers/terraform-provider-azurerm/blob/36b13c7dc9e78d10d3cda3d63eee69e3b14f2f0b/azurerm/internal/services/monitor/monitor_diagnostic_setting_resource.go#L221] or assign a default for `Enabled` in [`expandMonitorDiagnosticsSettingsMetrics`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/36b13c7dc9e78d10d3cda3d63eee69e3b14f2f0b/azurerm/internal/services/monitor/monitor_diagnostic_setting_resource.go#L487).

**Comment by magodo** [comment]
@jbardin Thank you to look into the provider code and provide the potential changes here.

Ultimately, the reasonable change for this resource here seems to be remove the `Default` for the `log`/`metric`'s `enabled` properties, and modify the config in 25600 to include the `enabled`. My comment: https://github.com/hashicorp/terraform/issues/28340#issuecomment-818354027 is not right, as the error is caused from the [provider code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/36b13c7dc9e78d10d3cda3d63eee69e3b14f2f0b/azurerm/internal/services/monitor/monitor_diagnostic_setting_resource.go#L229).

Additionally, I surprisingly found that if I don't remove the `Default` in the schema, the `Create` is not even called by Terraform.
