### ISSUE TITLE
Error: Reference to "count" in non-counted context

### ISSUE THREAD

**Issue by joaooamaral** [hashicorp/terraform#28359]
### Terraform Version

```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azurerm v2.40.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

### Terraform Configuration Files

```
.
.
.
resource "azurerm_virtual_machine" "vm-coaching" {
  count                            = var.coaching-persons * 3
  name                             = "VM-${count.index}-Coaching"
  location                         = var.location
  resource_group_name              = azurerm_resource_group.rg-coaching.name
  network_interface_ids            = [azurerm_network_interface.nic-coaching[count.index].id]
  vm_size                          = "Standard_B2ms" #2vCPUs / 8 GB RAM
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true
  
  storage_image_reference {
  publisher = "MicrosoftWindowsServer"
  offer     = "WindowsServer"
  sku       = "2016-Datacenter"
  version   = "latest"
  }
  storage_os_disk {
    name              = "VM-${count.index}-Coaching-OsDisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  storage_data_disk {
    name              = "VM-${count.index}-Coaching-DataDisk"
    caching           = "ReadWrite"
    create_option     = "Empty"
    managed_disk_type = "Standard_LRS"
    disk_size_gb      = 64
    lun               = 0
  }
  os_profile {
    computer_name  = "VM-${count.index}-Coaching"
    admin_username = local.admin_username
    admin_password = local.admin_password
  }
  os_profile_windows_config {
    enable_automatic_upgrades = false
    provision_vm_agent        = true
  }
}
resource "azurerm_virtual_machine_extension" "vm-coaching-ext" {
  name               = "VM-${count.index}-Coaching-Ext"
  virtual_machine_id = azurerm_virtual_machine.vm-coaching[count.index].id
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.9"
  protected_settings = <<PROTECTED_SETTINGS
    {
      "commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -File ops_coaching_setup.ps1"
    }
  PROTECTED_SETTINGS

  settings = <<SETTINGS
    {
        "fileUris": [
          "${local.script_url}"
        ]
    }
  SETTINGS
}
.
.
.
```

### Expected Behavior
Shouldn't have errored with "Error: Reference to "count" in non-counted context" as I'm using count within a resource

### Actual Behavior
Errors with:
```
Error: Reference to "count" in non-counted context

  on public_ops_coaching.tf line 213, in resource "azurerm_virtual_machine_extension" "vm-coaching-ext":
 213:   name               = "VM-${count.index}-Coaching-Ext"

The "count" object can only be used in "module", "resource", and "data"
blocks, and only when the "count" argument is set.


Error: Reference to "count" in non-counted context

  on public_ops_coaching.tf line 214, in resource "azurerm_virtual_machine_extension" "vm-coaching-ext":
 214:   virtual_machine_id = azurerm_virtual_machine.vm-coaching[count.index].id

The "count" object can only be used in "module", "resource", and "data"
blocks, and only when the "count" argument is set.
```

### Steps to Reproduce
1. Download TF code: https://github.com/joaooamaral/platform_ops_coaching/blob/public_ops_coaching/terraform/public_ops_coaching.tf
2. terraform init
3. terraform validate

### Additional Context
I've tried also with an older version of Terraform (Terraform v0.14.2) and same issue happens.
I don't know what's different between azurerm_virtual_machine_extension and the other resources I'm using count.index without any issues as this is only happening with azurerm_virtual_machine_extension

### References
Didn't find any related issues

**Comment by jbardin** [comment]
Hi @joaooamaral,

In order for there to be a `count.index` value, the resource itself must be using the `count` meta argument to create multiple instances. Since the `azurerm_virtual_machine_extension` resource is not using `count`, there is no value for `count.index`.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!
