### ISSUE TITLE
Misleading reporting of destroyed resources on plan, when forced new resource

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#2835]
terraform 0.6.1

Example - change a VPC CIDR block, and plan gives you:

-/+ aws_vpc.default
    cidr_block:                "10.15.0.0/16" => "10.16.0.0/16" (forces new resource)

but summary gives you:

Plan: 0 to add, 1 to change, 0 to destroy.

This is misleading as your VPC would be destroyed in the process. In general if a resource will end up being destroyed because of a "forces new resource", I should know about it in the plan summary.

**Comment by phinze** [comment]
Totally agreed with the logic here - this was done in https://github.com/hashicorp/terraform/pull/3173
