### ISSUE TITLE
git module sources with refs fail on 0.11.14 on default branches other than "master"

### ISSUE THREAD

**Issue by curiositycasualty** [hashicorp/terraform#28375]
Seeing as how this is far from a modern version of terraform, feel free to close this.
But I wanted to at least leave some footprints in the sand about an issue I lost most of my day to.

Yesterday, I triumphantly received the green light to switch all repos in the github org I manage from `master` to `develop`.
Today, runs of our main terraform repo began to fail.

Our modules are of the "one-per-git-repo" style so that we can use git tags as refs in `source` blocks. And they began failing when `terraform get -update` was being run. It was discovered that omitting `-update`, allowed the runs to succeed.

What eventually became apparent was that when checking out a git source as with `terraform init`, terraform was successfully utilizing its `?ref=` parameter-- but subsequent updates to that module, as with `terraform get -update`, were failing and instead attempting to checkout `master`-- a now nonexistent.

Usage of the script below in place of my local `git` binary revealed the issue. Terraform was using `git show-ref -q --verify refs/heads/<ref>` to do branch detection and defaulting to `master`. Running that `show-ref` command manually sans `-q` revealed that the command was failing due to `refs/heads/v0.1.2` being invalid as indicated with the list of refs produced by the command:
```
git -C /Users/user/Development/github.com/curiositycasualty/<main module>/.terraform/modules/bcd4441073df324387f60853109fae81 show-ref
/Users/user/Development/github.com/curiositycasualty/<main module>
git -C /Users/user/Development/github.com/curiositycasualty/<main module>/.terraform/modules/bcd4441073df324387f60853109fae81 show-ref
78745647d07a58f93977d2dfee0c30707108139a refs/heads/develop
78745647d07a58f93977d2dfee0c30707108139a refs/remotes/origin/HEAD
78745647d07a58f93977d2dfee0c30707108139a refs/remotes/origin/develop
cb54459ae1ad03d4d34ec6b967c18ca206b22211 refs/tags/v0.1.0
78745647d07a58f93977d2dfee0c30707108139a refs/tags/v0.1.1
78745647d07a58f93977d2dfee0c30707108139a refs/tags/v0.1.2
```

Supplying a winning value of `"refs/tags/"+ref` seems impossible owing to the hardcoding of `"refs/heads/"`: https://github.com/hashicorp/terraform/blob/v0.11.14/vendor/github.com/hashicorp/go-getter/get_git.go#L150-L158

### Workaround

We are now only using `rm -rf .terraform/modules/*; terraform get` which prompts the correct clone, but avoids the incorrect "update".

### Terraform Version

```
Terraform v0.11.14
+ provider.aws v2.70.0
+ provider.null v2.1.2

Your version of Terraform is out of date! The latest version
is 0.15.0. You can update by downloading from www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
module "nodule" {
  source     = "github.com/<org>/terraform_module_<module repo>?ref=v0.1.2"
}
```

### Debug Output

I wound up swapping out `git` locally for a bash script that logs to `/tmp/log`:

```bash
#!/usr/bin/env bash

touch /tmp/log

pwd >> /tmp/log
echo "git $@" >> /tmp/log

exec /usr/local/bin/../Cellar/git/2.31.1/bin/git $@
```

These logs were generated first by running `tail -n0 -F /tmp/log &` to place a tail reading /tmp/log in the background. Then running the indicated `terraform` commands such that the git commands from my faux git executable script above, are inline along side terraform output.

**NOTE** both instances of `git checkout` where the second references "master" but the first does not.

```
[localhost] local: /usr/local/bin/terraform init
2021/04/14 17:27:41 [WARN] Invalid log level: "all". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR]
2021/04/14 17:27:41 [INFO] Terraform version: 0.11.14
2021/04/14 17:27:41 [INFO] Go runtime version: go1.12.4
2021/04/14 17:27:41 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/2.2.0/versions/0.11.14/terraform", "init"}
2021/04/14 17:27:41 [DEBUG] Attempting to open CLI config file: /Users/user/.terraformrc
2021/04/14 17:27:41 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/04/14 17:27:41 [INFO] CLI command args: []string{"init"}
2021/04/14 17:27:41 [DEBUG] command: loading backend config file: /Users/user/Development/github.com/curiositycasualty/terraform_cloud/atelier/applications/mangoustan
Initializing modules...
2021/04/14 17:27:41 [TRACE] module source: "github.com/<org>/<module>?ref=v0.1.2"
2021/04/14 17:27:41 [TRACE] detected module source "git::https://github.com/<org>/<module>.git?ref=v0.1.2"
- module.nodule
2021/04/14 17:27:41 [DEBUG] fetching module from git::https://github.com/<org>/<module>.git?ref=v0.1.2
2021/04/14 17:27:41 [DEBUG] fetching "git::https://github.com/<org>/<module>.git?ref=v0.1.2" with key "1.nodule;github.com/<org>/<module>?ref=v0.1.2"
  Getting source "github.com/<org>/<module>?ref=v0.1.2"
/Users/user/Development/github.com/curiositycasualty/terraform_cloud/atelier/applications/mangoustan
git clone https://github.com/<org>/<module>.git .terraform/modules/bcd4441073df324387f60853109fae81
/Users/user/Development/github.com/curiositycasualty/terraform_cloud/atelier/applications/mangoustan/.terraform/modules/bcd4441073df324387f60853109fae81
git checkout v0.1.2
/Users/user/Development/github.com/curiositycasualty/terraform_cloud/atelier/applications/mangoustan/.terraform/modules/bcd4441073df324387f60853109fae81
git submodule update --init --recursive
2021/04/14 17:27:42 [DEBUG] found "git::https://github.com/<org>/<module>.git?ref=v0.1.2" in ".terraform/modules/bcd4441073df324387f60853109fae81": true
2021/04/14 17:27:42 [TRACE] "git::https://github.com/<org>/<module>.git?ref=v0.1.2" stored in ".terraform/modules/bcd4441073df324387f60853109fae81"
...
[localhost] local: /usr/local/bin/terraform get -update
2021/04/14 17:28:04 [WARN] Invalid log level: "all". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR]
2021/04/14 17:28:04 [INFO] Terraform version: 0.11.14
2021/04/14 17:28:04 [INFO] Go runtime version: go1.12.4
2021/04/14 17:28:04 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/2.2.0/versions/0.11.14/terraform", "get", "-update"}
2021/04/14 17:28:04 [DEBUG] Attempting to open CLI config file: /Users/user/.terraformrc
2021/04/14 17:28:04 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/04/14 17:28:04 [INFO] CLI command args: []string{"get", "-update"}
2021/04/14 17:28:04 [TRACE] module source: "github.com/<org>/<module>?ref=v0.1.2"
2021/04/14 17:28:04 [TRACE] detected module source "git::https://github.com/<org>/<module>.git?ref=v0.1.2"
- module.nodule
2021/04/14 17:28:04 [DEBUG] fetching module from git::https://github.com/<org>/<module>.git?ref=v0.1.2
2021/04/14 17:28:04 [DEBUG] fetching "git::https://github.com/<org>/<module>.git?ref=v0.1.2" with key "1.nodule;github.com/<org>/<module>?ref=v0.1.2"
  Updating source "github.com/<org>/<module>?ref=v0.1.2"
/Users/user/Development/github.com/curiositycasualty/terraform_cloud/atelier/applications/mangoustan/.terraform/modules/bcd4441073df324387f60853109fae81
git show-ref -q --verify refs/heads/v0.1.2
/Users/user/Development/github.com/curiositycasualty/terraform_cloud/atelier/applications/mangoustan/.terraform/modules/bcd4441073df324387f60853109fae81
git checkout master
2021/04/14 17:28:04 [DEBUG] plugin: waiting for all plugin processes to complete...
Error loading modules: error downloading 'https://github.com/<org>/<module>.git?ref=v0.1.2': /usr/local/bin/git exited with 1: error: pathspec 'master' did not match any file(s) known to git


Fatal error: local() encountered an error (return code 1) while executing '/usr/local/bin/terraform get -update'

Aborting.
```

Finally, I believe this issue is already fixed in `go-getter` where more sophisticated git default branch logic has been implemented (aka `git branch -r --points-at refs/remotes/origin/HEAD`):
- https://github.com/hashicorp/go-getter/blob/v1.5.2/get_git.go#L185
- https://github.com/hashicorp/go-getter/blob/v1.5.2/get_git.go#L226

Hopefully this github issue can help serve someone else trapped on terraform v.0.11.x stuck in a similarly shaped rut.

**Comment by apparentlymart** [comment]
Hi @curiositycasualty! Thanks for sharing your experience here.

I must confess that I didn't read your message all the way through before I realized that the behavior you were describing probably belongs to `go-getter` and went to see which version of `go-getter` v0.11.14 was using. Long story short: I ended up repeating the same investigation you did and reaching the same conclusion, that this indeed was arguably a bug in an older version of `go-getter` which has subsequently been fixed.

Unfortunately v0.11 is now far out of our window of ongoing support that indeed we won't be able to do anything to improve this for the v0.11 line. `go-getter` has changed in various other ways which mean that it wouldn't be appropriate for us to just unilaterally update it anyway, and so to get that working in v0.11 would likely be quite involved.

For that reason (as you suggested) I'm going to close this, but I do appreciate you sharing all of the details you learned. If you or anyone else finds that the _current_ `go-getter` behaviors are still problematic in some way in the case of selecting a tag, or other similar non-main-branch situations, please do feel free to open an issue in [the `go-getter` repository](https://github.com/hashicorp/go-getter) about it.
