### ISSUE TITLE
Init migration on backend gcs from 0.14.x to 0.15.0 fails

### ISSUE THREAD

**Issue by mcgin** [hashicorp/terraform#28379]
### Terraform Version

```
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/franckverrot/stripe v1.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

State Configuration:

```terraform
terraform {
  backend "gcs" {
    bucket = "mybucket"
    prefix = "terraform/prefix/"
  }
}

```

Current contents of .terraform/terraform.tfstate for backend config:

```
    "backend": {
        "type": "gcs",
        "config": {
            "access_token": null,
            "bucket": "mybucket",
            "credentials": null,
            "encryption_key": null,
            "path": null,
            "prefix": "terraform/prefix/",
            "project": null,
            "region": null
        },
        "hash": 2154004050
    },
```

### Debug Output

[Debug Output](https://gist.github.com/mcgin/f73edf017ef0b415a36fd5a780b3455a)

### Expected Behavior

Terraform init should complete successfully

### Actual Behavior

```
Error: Failed to decode current backend config
│
│ The backend configuration created by the most recent run of "terraform init" could not be decoded: unsupported attribute "path". The configuration may have been
│ initialized by an earlier version that used an incompatible configuration structure. Run "terraform init -reconfigure" to force re-initialization of the backend.
```

### Steps to Reproduce

1. `terraform init`

### Additional Context

I can work around this by deleting the .terraform directory and running `terraform init` with it removed.  
I believe the problem is caused by the `path: null` entry in the tfstate file.  I would expect running `terraform init` with terraform 0.14 or 0.15 would remove the path: null entry from the state file.

**Comment by apparentlymart** [comment]
Hi @mcgin! Sorry for this odd behavior, and thanks for reporting it.

Out of curiosity, did it work to run `terraform init -reconfigure` as the error message suggested? I agree that for a case where an argument is removed it would be better for this to just be handled automatically, but whether `-reconfigure` works to fix it would help to understand whether this is just an upgrade path quirk or something more significant.

Thanks!

**Comment by mcgin** [comment]
I didn't actually run the reconfigure as I wasn't clear exactly what that would do.  It seemed like it might run the risk of trashing the entire state and I wasn't clear whether this would just be locally (which would be fine) or also apply to the remote state (which would not be fine).  As I couldn't get a clear answer I just went with my workaround.

**Comment by jbardin** [comment]
I verified that the stored state is not decoded at all when using `-reconfigure`. 
Since this is in the legacy codepath, and the error output and suggestion are correct, we can leave the decoding as-is for now.
