### ISSUE TITLE
Error removing aws_security_group_rule that has self reference rule

### ISSUE THREAD

**Issue by alexintel** [hashicorp/terraform#2837]
@catsby 

Terraform version 0.5.3

This is NOT a duplicate of #1985 (https://github.com/hashicorp/terraform/issues/1985)
#2305 only fixes a specific use case where:
```
resource "aws_security_group_rule" "self" {
  type = "ingress"
  protocol = "-1"
  from_port = 0
  to_port = 0
  self = true
  security_group_id = "${aws_security_group.web.id}"
}
```

Following case is still broken (note specific port number range):
```
resource "aws_security_group_rule" "self" {
  type = "ingress"
  protocol = "-1"
  from_port = 5501
  to_port = 5504
  self = true
  security_group_id = "${aws_security_group.web.id}"
}
```

Error:
```
* Error revoking security group sg-9136df35 rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: []
Error applying plan:

1 error(s) occurred:

* 1 error(s) occurred:

* 1 error(s) occurred:

* Error revoking security group sg-9136df35 rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: []
```

After I manually modified security group sg-9136df35 from AWS console to allow all TCP traffic 'terraform destroy' worked fine.

**Comment by alexintel** [comment]
Issue for some reason persists in 0.5.3 even with 0-0 range. Seems like the issue with "self" reference, because the following works:
Note absence of "self" reference and adding SG source back to itself.
```
resource "aws_security_group_rule" "self" {
  type = "ingress"
  protocol = "-1"
  from_port = 5501
  to_port = 5504

  security_group_id = "${aws_security_group.web.id}"
  source_security_group_id = "${aws_security_group.web.id}"
}
```

**Comment by catsby** [comment]
Thank you for writing in @alexintel – this should be fixed in a refactoring of Security Group Rules I've done in #3019

**Comment by catsby** [comment]
Closing this for now, I can no longer reproduce the bug as shown, thanks!
