### ISSUE TITLE
Adding a "reference" resource for cross-environment resource sharing

### ISSUE THREAD

**Issue by rvangundy** [hashicorp/terraform#2838]
We've set up several environments on Atlas and have a need to share certain resources amongst them. For example, we configure our base VPC on AWS using one set of Terraform configurations. We then have additional environments set up that refer to subnets, etc. in that base environment. Right now we have to copy the IDs associated with those resources in to our other Terraform configurations. This is OK but assuming some resource had to be recreated, it would be nice to refer to it like we do artifacts, e.g.:

```
resource "reference" "vpc" {
    atlas_environment = "username/base-vpc"
    resource = "aws_vpc.base_vpc"
}

resource "aws_subnet" "new_subnet" {
    vpc_id = "${reference.vpc.id}
    ...
}
```

**Comment by jedineeper** [comment]
We use Consul for this and upload the vpc and subnet ids as key value pairs.

**Comment by rvangundy** [comment]
OK this feature exists by configuring the terraform_remote_state resource, seen in the docs here: https://terraform.io/docs/state/remote.html
