### ISSUE TITLE
terraform destory using dymanic aws credentials from vault.

### ISSUE THREAD

**Issue by yagashiraevil** [hashicorp/terraform#28405]
https://learn.hashicorp.com/tutorials/terraform/secrets-vault?utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS&_ga=2.94138141.1000881772.1618550275-1500626752.1618550275

I was following the above guide to set up provider dynamic creds using vault. everything went well till the point where I need to destroy the ec2 instance. instead of creating new creds to destroy, it kept giving me the below error.

**Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request 
is invalid.
        status code: 403, request id: 9d8c594c-f99e-41a9-8b2a-e977028a4b81**

1. I tried to create use creds on AWS using the vault  (Secusseful) 
2. I looked at the permission for both AWS keys and the dynamic keys both hay permission to deleted the resources

**Comment by jbardin** [comment]
Hi @yagashiraevil,

I'm not sure what's going on here without all the details about your setup, but if you are using v0.14 I suspect you are seeing the behavior described in #27172. If that's the case you can work around the issue by refreshing the state immediately before running destroy. If you are already using v0.15, please fill out the reset of the information requested in the issue template, and we can look into 

Thanks!

**Comment by yagashiraevil** [comment]
Hello @jbardin , 
I was using v0.14 with vault on 1.7 after upgrading to v0.15 the issue resolved. Thank you for you help.
