### ISSUE TITLE
TF v0.15 - lack of colours using CLI and Terraform Cloud

### ISSUE THREAD

**Issue by evilr00t** [hashicorp/terraform#28408]
After upgrade to TF v0.15 - colours disappeared from the output using Terraform Cloud as a remote backend.

```
evilroot in ~ λ terraform --version
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

![Screenshot 2021-04-16 at 11 06 40 am](https://user-images.githubusercontent.com/12815767/115009246-ff98e480-9ea3-11eb-895d-c45aa1815f72.png)

**Comment by alisdair** [comment]
Hi @evilr00t, thanks for reporting this. I'm able to reproduce it, and it looks like a local Terraform issue. For me, viewing the runs in Terraform Cloud's web UI shows the normal syntax highlighting. Is that the case for you, too?

**Comment by evilr00t** [comment]
hey @alisdair - yes it is! In web UI everything is as it should. Local TF seems to be too shy to show its colours 😅
