### ISSUE TITLE
Feature Request: Add support for Alpine Linux / musl

### ISSUE THREAD

**Issue by chiefy** [hashicorp/terraform#2840]
I like keeping my docker images slim as possible, and finally got a [Alpine Linux based Terraform image](https://registry.hub.docker.com/u/chiefy/alpine-terraform/) going after a lot of dickery. I am pretty much a Go n00b, so I was following [the advice in this article](http://www.blang.io/2015/04/19/golang-alpine-build-golang-binaries-for-alpine-linux.html). There's also [golang-builder](https://github.com/CenturyLinkLabs/golang-builder) which I have not tried w/ TF, but considering the complexity of this project, might be more trouble than it's worth?

Was wondering what the thoughts were on adding a compile for musl to CD?

**Comment by johnrengelman** [comment]
Just ran into this myself. I've been looking at using [Drone](github.com/drone/drone) as a CI tool and have been implementing a plugin to execute Terraform plans from an Alpine Linux base image.

**Comment by stack72** [comment]
Hi all

The official terraform docker images are available at https://hub.docker.com/r/hashicorp/terraform/

The light version is based off alpine :)

Closing this out

Paul
