### ISSUE TITLE
RSA verification failure for terraform-provider-aws 2.15.0

### ISSUE THREAD

**Issue by keyneston** [hashicorp/terraform#28440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -version
Terraform v0.11.14
```

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "2.15.0"
}
```

### Expected Behavior

`terraform init` should successfully download the plugin.

### Actual Behavior

Upon running `terraform init` we get the following error message:

> terraform_test$ terraform init
> 
> Initializing provider plugins...
> - Checking for available provider plugins on https://releases.hashicorp.com...
> 
> Error installing provider "aws": openpgp: invalid signature: RSA verification failure.
> 
> Terraform analyses the configuration and state and automatically downloads
> plugins for the providers used. However, when attempting to download this
> plugin an unexpected error occured.
> 
> This may be caused if for some reason Terraform is unable to reach the
> plugin repository. The repository may be unreachable if access is blocked
> by a firewall.
> 
> If automatic installation is not possible or desirable in your environment,
> you may alternatively manually install plugins by downloading a suitable
> distribution package and placing the plugin's executable file in the
> following directory:
>     terraform.d/plugins/darwin_amd64

### Steps to Reproduce

1. `terraform init`

### Important Factoids

My fear in reporting this is that it is a regional issue. That is to say the mirror I'm pulling from has a bad copy, but the mirror someone else is pulling from is fine.

I'm currently working around this issue by just manually bumping the version from `2.15.0` to `2.16.0` but figured I'd report it anyways in case it was a sign of a bigger issue.

**Comment by apparentlymart** [comment]
Hi @bflad,

Has the RSA key used to sign new AWS provider releases changed somewhere along the line? I notice this issue is with Terraform v0.11, which I recall had a particular approved public key embedded into it. The modern Terraform installer (from v0.13 onwards) uses a different scheme where it can accept various different keys, including self-asserted community keys, but a provider released using one of these other keys would not be verifiable by Terraform v0.12 and earlier, and I think would therefore be a v0.13-or-later-only provider.

**Comment by apparentlymart** [comment]
The only public key that Terraform v0.11 accepts is visible in the source code here:

https://github.com/hashicorp/terraform/blob/fe16e9b7c0a1348afe5a1e986f26210366b86e3e/plugin/discovery/signature.go#L24-L53

**Comment by jbardin** [comment]
Both of those AWS and Terraform releases were published nearly 2 years ago, so it's interesting that only now we see a report of a problem. I wonder if the error might not be quite accurate, and there is a simpler failure like retrieving the file from the edge server or something that is being masked.

**Comment by keyneston** [comment]
This is a really edge case, if you want to just close the ticket I won't be offended. I've already worked around it by upgrading the aws provider to `2.16.0`. Additionally my coworker attempted to replicate the issue and was unable to. That said I've replicated it multiple times on my computer, which gives further credence to a mirror caching issue, or something screwed up with my computer.

## Debug Output

>>> $ TF_LOG=trace terraform init
2021/04/20 14:53:10 [INFO] Terraform version: 0.11.14
2021/04/20 14:53:10 [INFO] Go runtime version: go1.15.5
2021/04/20 14:53:10 [INFO] CLI args: []string{"/usr/local/Cellar/terraform@0.11/0.11.14/bin/terraform", "init"}
2021/04/20 14:53:10 [DEBUG] Attempting to open CLI config file: /Users/tabitha/.terraformrc
2021/04/20 14:53:10 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/04/20 14:53:10 [INFO] CLI command args: []string{"init"}
2021/04/20 14:53:10 [DEBUG] command: loading backend config file: /Users/tabitha/Code/src/github.com/keyneston/terraform_test
2021/04/20 14:53:10 [INFO] command: empty terraform config, returning nil
2021/04/20 14:53:10 [DEBUG] command: no data state file found for backend config
2021/04/20 14:53:10 [DEBUG] New state was assigned lineage "b54f4b73-ff68-7f19-e238-913dc8e89aff"
2021/04/20 14:53:10 [INFO] command: backend initialized: <nil>
2021/04/20 14:53:10 [DEBUG] checking for provider in "."
2021/04/20 14:53:10 [DEBUG] checking for provider in "/usr/local/Cellar/terraform@0.11/0.11.14/bin"
2021/04/20 14:53:10 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2021/04/20 14:53:10 [DEBUG] checking for provisioner in "."
2021/04/20 14:53:10 [DEBUG] checking for provisioner in "/usr/local/Cellar/terraform@0.11/0.11.14/bin"
2021/04/20 14:53:10 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2021/04/20 14:53:10 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2021/04/20 14:53:10 [INFO] command: backend <nil> is not enhanced, wrapping in local
2021/04/20 14:53:10 [DEBUG] checking for provider in "."
2021/04/20 14:53:10 [DEBUG] checking for provider in "/usr/local/Cellar/terraform@0.11/0.11.14/bin"
2021/04/20 14:53:10 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"

2021/04/20 14:53:10 [DEBUG] plugin requirements: "aws"="2.15.0"
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

2021/04/20 14:53:10 [ERROR] 1 error occurred:
	* openpgp: invalid signature: RSA verification failure

Error installing provider "aws": openpgp: invalid signature: RSA verification failure.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
2021/04/20 14:53:10 [DEBUG] plugin: waiting for all plugin processes to complete...
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64

**Comment by jbardin** [comment]
Thanks for the extra testing @keyneston! Since there are not going to be any more patch releases for either of these versions, and this has not been reported in any current releases, I'm going to close this for now. Thanks for the heads up though, and we can keep an eye out for any similar issues.
