### ISSUE TITLE
Unexpected diffs are displayed with terraform plan when sensitive flag is changed

### ISSUE THREAD

**Issue by chroju** [hashicorp/terraform#28454]
### Terraform Version

```
❯ terraform version
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.36.0
```

### Terraform Configuration Files

```terraform
variable "sensitive_value" {
  default   = "sensitive"
  type      = string
  sensitive = false
}

resource "aws_ssm_parameter" "foo" {
  name  = "foo"
  type  = "SecureString"
  value = var.sensitive_value
}
```

### Debug Output

N/A

### Crash Output

N/A

### Expected Behavior

When I run `terraform apply` once and then change the `variable.sensitive_value` to `sensitive = true` and run `terraform plan`, I get the following.

```hcl
  # aws_ssm_parameter.foo will be updated in-place
  ~ resource "aws_ssm_parameter" "foo" {
        id        = "foo"
        name      = "foo"
        tags      = {}
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ value     = (sensitive value)
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

Actually, I get the following. `allowed_pattern` and `description` are optional values. It is not expected that empty strings will be set there.

```hcl
  # aws_ssm_parameter.foo will be updated in-place
  ~ resource "aws_ssm_parameter" "foo" {
      + allowed_pattern = ""
      + description     = ""
        id              = "foo"
        name            = "foo"
        tags            = {}
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ value           = (sensitive value)
        # (6 unchanged attributes hidden)
    }
```

Also, if you change from `sensitive = true` to `false`, `allowed_pattern` and `description` will be set back to null.

```hcl
  # aws_ssm_parameter.foo will be updated in-place
  ~ resource "aws_ssm_parameter" "foo" {
      - allowed_pattern = "" -> null
      - description     = "" -> null
        id              = "foo"
        name            = "foo"
        tags            = {}
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change
      ~ value           = (sensitive value)
        # (6 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. `terraform init`
1. `terraform apply -auto-approve`
1. Rewrite the configuration (`sensitive = true`).
1. `terraform plan`

### Additional Context

No, but I'm not sure if this is a problem with terraform itself or with the aws provider. So, the same issue has also been submitted to hashicorp/terraform-provider-aws#19010

**Comment by jbardin** [comment]
Thanks @chroju,

What you are seeing is an artifact from the legacy SDK which often cannot distinguish between unset and empty values. If you look at the logs from the plan you will see something like:

```
2021-04-20T10:22:50.756-0400 [WARN]  Provider "registry.terraform.io/hashicorp/aws" produced an invalid plan for aws_ssm_parameter.foo, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .description: planned value cty.StringVal("") for a non-computed attribute
      - .allowed_pattern: planned value cty.StringVal("") for a non-computed attribute
```

We generally suppress these changes when possible, but when there is another change to be made they will unfortunately show up in the diff output. If you inspect the state, you will see that indeed in both cases an empty string is saved for those 2 values. 

Since Terraform is working as expected here, I'm going to close this out. This is a known shortcoming of the legacy SDK, and work is being done on the next generation SDK which can take full advantage of the rich type system offered by Terraform. 

Thanks!
