### ISSUE TITLE
Changing for_each to toset([for not working

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform#28458]
Tried to follow steps outlined in [docs](https://www.terraform.io/docs/language/meta-arguments/for_each.html#limitations-on-values-used-in-for_each) to use a for_each on a sensitive map.

### Terraform Version
```
Terraform v0.14.9
```

### Terraform Configuration Files
```terraform
variable "secrets_map" {
  type = map(string)
  default = {
    "key1" : "foo"
    "key2" : "bar"
  }
  sensitive = true
}

resource "null_resource" "this" {
  #   for_each = var.secrets_map
  for_each = toset([for k, v in var.secrets_map : k])

  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    command = "echo ${each.key} = ${each.value}"
  }
}
```

### Expected Behavior
Was expecting the documented workaround to work.

### Actual Behavior
```
Error: Invalid for_each argument

  on main.tf line 12, in resource "null_resource" "this":
  12:   for_each = toset([for k, v in var.secrets_map : k])

Sensitive values, or values derived from sensitive values, cannot be used as
for_each arguments. If used, the sensitive value could be exposed as a
resource instance key.
```

### Steps to Reproduce
- terraform init
- terraform plan -out my.tfplan

### References
- https://www.terraform.io/docs/language/meta-arguments/for_each.html#limitations-on-values-used-in-for_each

**Comment by alisdair** [comment]
Hi @dkirrane, thanks for reporting this.

The workaround described in the docs is for a slightly different situation from yours:

> if you would like to call `keys(local.map)`, where local.map is an object with sensitive values (but non-sensitive keys), you can create a value to pass to `for_each` with `toset([for k,v in local.map : k])`

In your report, the entire map is a sensitive value, which means that you cannot use it as an argument to `for_each` at present. I can suggest a couple of possible workarounds, both of which require an upgrade to Terraform 0.15:

- Use the `sensitive` function to mark each individual value as sensitive, not the whole variable:

    ```hcl
    variable "secrets_map" {
      type = map(string)
      default = {
        "key1" : sensitive("foo")
        "key2" : sensitive("bar")
      }
      sensitive = false
    }
    ```

    In conjunction with changes we are planning to release in 0.15.1 tomorrow, this should allow you to write `for_each = var.secrets_map`, and still have the sensitive values obscured in the log output.

- Keep your original definition, but use `for_each = nonsensitive(keys(var.secrets_map))`, and then `command = "echo ${each.key} = ${var.secrets_map[each.key]}"`. Again, this should have the same result.

I haven't tested either of these locally, but I believe they should both work.

I don't think there's a bug in Terraform here, so I'm going to close this issue. If you continue to hit problems after trying these other options, do let me know!
