### ISSUE TITLE
Enable links to subcategory sections in the Terraform.io website

### ISSUE THREAD

**Issue by cjcarpen** [hashicorp/terraform#28491]
### Current Terraform Version

N/A - website (documentation) only

### Use-cases

Our [IBM Cloud Terraform provider docs](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs) contain resources and data sources for many different IBM Cloud services, which we've organized into subcategories. We want to link from the service's main product documentation to the specific subcategory for the service in the Terraform provider reference.

### Attempted Solutions

Currently, we're linking to the first resource that's available underneath a subcategory, for example: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/api_gateway_endpoint

<img width="340" alt="image" src="https://user-images.githubusercontent.com/12972763/115771851-6e7ead80-a37c-11eb-9a72-6df3dd758223.png">

This isn't ideal because the available resources can change, leading to a random landing spot or broken link.

### Proposal

Generate an ID from the available subcategories in the website so that they have a linkable URL.

### References

Searched but did not see any other issues related to the website behavior.

**Comment by sean-freeman** [comment]
@cjcarpen This appears to remain a functionality gap for the Terraform Registry; although I senes this is a design decision. As the Terraform Registry allows for multiple guide documents, an inefficient workaround to your request, would be to....

1. Copy Markdown file for [Index of Terraform on IBM Cloud resources and data sources](https://github.com/ibm-cloud-docs/ibm-cloud-provider-for-terraform/blob/master/provider/sitemap.md)
2. Paste Markdown into provider subdirectory [/website/docs/guides](https://github.com/IBM-Cloud/terraform-provider-ibm/tree/master/website/docs/guides)

**Comment by crw** [comment]
Just a note that the registry team does not work out of this repository; I will pass this issue along to give them a chance to add it to their backlog. Thanks for submitting this request!
