### ISSUE TITLE
Apply with update and delete no longer completes in terraform v0.15

### ISSUE THREAD

**Issue by yamamoto-febc** [hashicorp/terraform#28514]
### Terraform Version
```
Terraform v0.15.0
on darwin_amd64
```

### Terraform Configuration Files

See here for a ready to go example: https://github.com/yamamoto-febc/terraform-update-and-delete

### Expected Behavior

Complete `terraform apply` including both deletion and update.

### Actual Behavior

Deletion times out.

### Steps to Reproduce

See here for a ready to go example: https://github.com/yamamoto-febc/terraform-update-and-delete

### Additional Context

I'm experiencing an issue with terraform v0.15 and our custom provider where `terraform apply` does not complete.

Our Terraform configuration is as follows:

```hcl
resource "sakuracloud_server" "foobar" {
  name           = "example"
  private_host_id = sakuracloud_private_host.foobar.id
}

resource "sakuracloud_private_host" "foobar" {
  name = "example"
}
```

`terraform-provider-sakuracloud` is used to operate the IaaS cloud service "SAKURA Cloud".
This provider has following resources:
- `sakuracloud_server`: A computing resource such as AWS EC2.
- `sakuracloud_private_host`: A dedicated host that the instance of `sakuracloud_server` will be assigned to.

`sakuracloud_server` will be assigned to a dedicated host if `private_host_id` is specified, or to a shared host if it is not specified.
`private_host_id` can be updated without recreating `sakuracloud_server` resource.

After applying with the previous configuration, I tried to apply the following changes, but it did not complete.

```hcl
# assign to a shared host
resource "sakuracloud_server" "foobar" {
  name           = "example"
  # private_host_id = sakuracloud_private_host.foobar.id
}

# resource "sakuracloud_private_host" "foobar" {
#   name = "example"
# }
```

`sakuracloud_private_host` cannot be deleted if an instance has been assigned to itself, so it checks if there is an instance assigned to itself before deleting it.
- https://github.com/sacloud/terraform-provider-sakuracloud/blob/4063b51a35a88163163b0c70cafd86702543863d/sakuracloud/resource_sakuracloud_private_host.go#L157
- https://github.com/sacloud/terraform-provider-sakuracloud/blob/4063b51a35a88163163b0c70cafd86702543863d/vendor/github.com/sacloud/libsacloud/v2/helper/cleanup/private_host.go#L27

Before terraform v0.15, `sakuracloud_private_host` was deleted after `sakuracloud_server` was updated, but now the deletion of `sakuracloud_private_host` is not completed.
I think this behavior is based on https://github.com/hashicorp/terraform/pull/28165.

Is this issue should be solved by Terraform Core or by the provider?

### References

- Terraform provider for SAKURA Cloud: https://github.com/sacloud/terraform-provider-sakuracloud

**Comment by jbardin** [comment]
Hi @yamamoto-febc,

The way to achieve the desired ordering of "update then delete" in this case is to use the `create_before_destroy` lifecycle option. While this example is not replacing any resources, the desired ordering of operations is still the same as what `create_before_destroy` achieves, and will also work as desired with other combinations of replacements and updates.  For example, while the config here would appear to work at times in earlier versions of terraform, as the ordering was not deterministic, it would have failed in the replacement scenario where the intended ordering was correctly enforced.

If it helps, I've tried to make some notes in a document [here](https://github.com/hashicorp/terraform/blob/main/docs/destroying.md) to help developers understand the various ordering decisions being made when destroying resources. 

Thanks!
