### ISSUE TITLE
HCSEC-2021-12: Terraform releases still signed with a revoked GPG key

### ISSUE THREAD

**Issue by christophetd** [hashicorp/terraform#28518]
Re: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512
**tl;dr:** Hashicorp signing key with fingerprint `91A6 E7F8 5D05 C656 30BE F189 5185 2D87 348F FC4C`
was leaked and revoked, but latestTerraform releases are still signed with it

I am verifying the authenticity of Terraform v0.14.9 using:

```
gpg --import hashicorp-security.asc
wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O terraform.zip \
  && wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig -O terraform_SHA256SUMS.sig \
  && wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS -O terraform_SHA256SUMS \
 && gpg --verify terraform_SHA256SUMS.sig terraform_SHA256SUMS
```

And it seems Terraform 0.14.9 (at least) is still signed with the old key:

```
$ gpg --verify terraform_SHA256SUMS.sig terraform_SHA256SUMS
gpg: Signature made Mi 24 Mär 19:50:18 2021 CET
gpg:                using RSA key 91A6E7F85D05C65630BEF18951852D87348FFC4C
```

Which is contradictory with the following Hashicorp statement:

>  Existing releases have been validated and re-signed

**Notes**:
- Same behavior for Terraform 0.15.0
- Vault 1.7.1, however, is signed with the proper key (`C874 011F 0AB4 0511 0D02  1055 3436 5D94 72D7 468F`)

**Comment by phinze** [comment]
Hi @christophetd - thanks for the report and apologies for the unclear status here.

All Terraform binary and provider releases have been signed by the rotated key - those signatures are available at the extension `SHA256SUMS.72D7468F.sig`

The existing `.sig` files are currently being left as-is to preserve working behavior on existing Terraform releases. We're in the process of producing patch releases for Terraform which will verify against the new key.

You should be able to verify using the same steps you cited, just switching out the file extension for `SHA256SUMS.72D7468F.sig`. We'll be following up with more information once the patch releases are available. I'll swing around and link those details once they're published.

Let me know if you're able to verify using the other signatures and if you have any follow up questions here.

**Comment by NicoleYson** [comment]
I noticed that the public key PRs were released for v0.12.31, but it still seems to be an intermittent issue at ~10% success rates with plans and applies. 
Is there any further action that needs to be done or is this still expected at this point? Could you clarify that if beyond these PRs https://github.com/hashicorp/terraform/pull/28499, additional work needs to be done to re-sign the individual plugins? or is this only a patch to terraform core? 

```
Upgrading modules...

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...

Error verifying GPG signature for provider "template"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.


Error verifying GPG signature for provider "kubernetes"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.

- Downloading plugin for provider "vault" (hashicorp/vault) 2.19.1...
- Downloading plugin for provider "aws" (hashicorp/aws) 3.37.0...

Error: unable to verify signature

Error: unable to verify signature
```

**Comment by jbsolomon-fw** [comment]
The aws provider never succeeds for me :)

**Comment by repl-mike-roest** [comment]
We're seeing similar issues with the grafana plugin but the core providers such as aws/template/null seem fine (with 0.12.31)
```
- Checking for available provider plugins...

Error verifying GPG signature for provider "grafana"
Terraform was unable to verify the GPG signature of the downloaded provider
files using the keys downloaded from the Terraform Registry. This may mean that
the publisher of the provider removed the key it was signed with, or that the
distributed files were changed after this version was released.

- Downloading plugin for provider "template" (hashicorp/template) 2.2.0...

Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to grafana/grafana. Please update your source in required_providers.
```

**Comment by jbardin** [comment]
Hello,

The provider validation issues on 0.12.31 were caused by problems purging stale responses from the global caches, and these should be cleared out now. Let us know if there are any remaining failures.

Thanks!

**Comment by repl-mike-roest** [comment]
@jbardin I just attempted to do an init with 0.12.31 from a clean dir with no .terraform dir and am still receiving the error validating signature on grafana plugin.

**Comment by jbardin** [comment]
Thanks @repl-mike-roest. What OS, architecture, and provider version are you using?

**Comment by repl-mike-roest** [comment]
Platform: darmwin_amd64
Provider: Grafana 1.9.0 (not pinned just pulling latest)

**Comment by jbardin** [comment]
Thanks @repl-mike-roest! That appears to be a different issue as the grafana provider was moved out of the hashicorp namespace. The registry team is working on it now.

**Comment by repl-mike-roest** [comment]
great thanks @jbardin

**Comment by jbardin** [comment]
@repl-mike-roest, grafana should be updated now, and works from my test.

**Comment by repl-mike-roest** [comment]
@jbardin yep appears to be working on my limited  local test.  I've just re-run a pipeline here to see what it looks like there.

**Comment by repl-mike-roest** [comment]
@jbardin my pipeline passed as well seems to be resolved for us at least.  Thanks

**Comment by joe-a-t** [comment]
@jbardin is there a way to fix the terraform latest release tag in this repo? Right now it is on https://github.com/hashicorp/terraform/releases/tag/v0.11.15 when I believe it should be on https://github.com/hashicorp/terraform/releases/tag/v0.15.1

**Comment by jbardin** [comment]
@joe-a-t, there is no differentiation between git tags to indicate what "latest" means. If you're referring to https://github.com/hashicorp/terraform/releases/latest, that is part of the GitHub UI which takes latest to mean "most recent", which could be from any branch.

**Comment by joe-a-t** [comment]
@jbardin yes, we have some onboarding documentation that says to grab and install the latest version from https://github.com/hashicorp/terraform/releases/latest so I got very confused when a new hire messaged me about Terraform 11. If you simply update the description of https://github.com/hashicorp/terraform/releases/tag/v0.15.1 (no changes to the actual code or re-release required, you can literally just add a space to the end of a line and press save), it should switch the https://github.com/hashicorp/terraform/releases/latest to point at 0.15.1.

**Comment by joshsleeper** [comment]
@joe-a-t not to be rude, but could we please not commandeer this issue for something unrelated? thanks!

also, if the `latest` tag isn't guaranteed to represent what you want, you're best bet is probably to change your internal docs to not rely on it, otherwise it's just a ticking time bomb. ¯\\\_(ツ)\_/¯

**Comment by bleachbyte** [comment]
I'm also still running into this error -- even using the `terraform_0.13.7_SHA256SUMS.72D7468F.sig` file -- in Terraform `v0.13.7`, unless I'm missing something?

```
$ gpg --verify terraform_0.13.7_SHA256SUMS.72D7468F.sig terraform_0.13.7_SHA256SUMS
gpg: Signature made Mon Apr 26 15:27:01 2021 CDT
gpg:                using RSA key B36CBA91A2C0730C435FC280B0B441097685B676
gpg: Good signature from "HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: C874 011F 0AB4 0511 0D02  1055 3436 5D94 72D7 468F
Subkey fingerprint: B36C BA91 A2C0 730C 435F  C280 B0B4 4109 7685 B676
```

**Comment by jbardin** [comment]
@bleachbyte, that is not an error, and it should have returned a `0` exit status having given the "Good signature" message. 
The warning is about your local "web of trust" configuration for that key, but you can manually verify the primary key fingerprint in the output if needed.

**Comment by rxp1997** [comment]
Still have this issue

2021/04/28 19:27:08 [INFO] Terraform version: 0.11.14  
2021/04/28 19:27:08 [INFO] Go runtime version: go1.12.4
....
2021/04/28 19:27:08 [DEBUG] found provider "terraform-provider-random_v2.3.1_x4"
2021/04/28 19:27:08 [DEBUG] found provider "terraform-provider-template_v2.2.0_x4"
2021/04/28 19:27:08 [DEBUG] found valid plugin: "random", "2.3.1", "/tmp/build/48f1f378/prod-provision/datascience/services/.terraform/plugins/linux_amd64/terraform-provider-random_v2.3.1_x4"
2021/04/28 19:27:08 [DEBUG] found valid plugin: "template", "2.2.0", "/tmp/build/48f1f378/prod-provision/datascience/services/.terraform/plugins/linux_amd64/terraform-provider-template_v2.2.0_x4"
....
2021/04/28 19:27:08 [DEBUG] plugin requirements: "google-beta"=""
2021/04/28 19:27:08 [DEBUG] plugin requirements: "random"=""
2021/04/28 19:27:08 [DEBUG] plugin requirements: "template"=""
2021/04/28 19:27:08 [DEBUG] plugin requirements: "google"=""

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "google-beta": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64


Error installing provider "google": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
2021/04/28 19:27:08 [ERROR] 2 errors occurred:
        * openpgp: signature made by unknown entity
        * openpgp: signature made by unknown entity

2021/04/28 19:27:08 [DEBUG] plugin: waiting for all plugin processes to complete...
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64


have same issue with terraform v0.12.30 with just the two Google providers.

**Comment by jbardin** [comment]
Hi @rxp1997,

In order to validate new provider releases, you will need to update to the current terraform release. See https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570

**Comment by arcenik** [comment]
Hi @rxp1997

I had similar issue with terraform0.11 and vault provider.

The latest version of the provider (2.20.0) is signed with a new PGP key that is not present in terraform0.11 keystore.

```
$ cat vault.tf
provider "vault" {
  version = "2.20.0"
}

$ terraform11 version
Terraform v0.11.15-oci

Your version of Terraform is out of date! The latest version
is 0.15.4. You can update by downloading from www.terraform.io/downloads.html

$ terraform11 init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "vault": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64
```

But once I set an older version, that work again

```
$ cat vault.tf
provider "vault" {
  version = "2.19.1"
}

$ terraform11 init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "vault" (2.19.1)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

In your case, for random-2.3.1, upgrading to terraform-0.11.15 seems to work.

But eventually, you need to upgrade to terraform 0.15.

Best regards.

**Comment by christophetd** [comment]
I believe this issue is no longer relevant so I'll close it, feel free to reopen if applicable
