### ISSUE TITLE
Terraform code block for attaching multiple Elastic Inference accelerators with EC2 instance in AWS

### ISSUE THREAD

**Issue by ashish60808** [hashicorp/terraform#28517]
### Current Terraform Version

```
...
```

**Comment by jbardin** [comment]
Hi @ashish60808,

There doesn't seem to be any information in your issue. If this was meant for the AWS provider, please file it in their project repository with the information requested in the issue template. If you have questions about using a resource, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
