### ISSUE TITLE
Terraform crashing

### ISSUE THREAD

**Issue by anuradhaarao** [hashicorp/terraform#28513]
Hi , my Terraform apply command is crashing.
Attached the crash log. Please assist. Thanks
[crash.905164386.log](https://github.com/hashicorp/terraform/files/6371888/crash.905164386.log)

**Comment by MitchDrage** [comment]
Please take a look at the formatting and required information for raising a bug. You would have deleted all of the guidance text that describes this when you raised a new issue ticket.
