### ISSUE TITLE
Function setproduct() panics with empty sets/lists

### ISSUE THREAD

**Issue by peikk0** [hashicorp/terraform#28524]
### Terraform Version

```
Terraform v0.15.1
on darwin_amd64
```

### Terraform Configuration Files

```terraform
output "panics" {
  value = setproduct([], [])
}

output "panics_too" {
  value = setproduct(["a", "b"], [])
}

output "panics_again" {
  value = setproduct([], ["c", "d"])
}

output "does_not_panic" {
  value = setproduct(["a", "b"], ["c", "d"])
}
```

### Debug Output

https://gist.github.com/peikk0/813a660c334fef294db7b12557be9048#file-debug-log

### Crash Output

https://gist.github.com/peikk0/813a660c334fef294db7b12557be9048#file-crash-log

### Expected Behavior

`setproduct()` should not panic with empty lists or sets.

### Actual Behavior

`setproduct()` panics with empty lists or sets.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by thehunt33r** [comment]
I've encountered the same issue. It seems to be a regression between 0.15.0 and 0.15.1, as using 0.15.0 works as expected.
