### ISSUE TITLE
[mac1.metal][auto scaling] support launching mac1 ec2 instance through Launch Template Host Resource Group

### ISSUE THREAD

**Issue by OliverKoo** [hashicorp/terraform#28531]
### Current Terraform Version
0.14.6

### Use-cases
mac1.metal instance requires running on a dedicated host. My org wants to create an Auto Scaling Group for mac1.metal instances. ASG requires a launch template, when creating Launch Templates one would have to specify tenancy (Advance Detail -> Tenancy) as "Dedicated Host" then specify the either "tenancy host ID" or "tenancy Host Resource Group" (create under License Manager). 

"Tenancy host ID" would map existing dedicated host to a to be launched instance. Which is not workable for auto scaling. 
Hence using "Tenancy host resource group" is necessary for auto scaling as it would dynamically create dedicated host for you and when launching instance .

from [AWS autoscaling userguide](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-dg.pdf)
> For Tenancy host resource group, you can specify a host resource group for a BYOL AMI to
> use on Dedicated Hosts. You do not have to have already allocated Dedicated Hosts in your
> account before you use this feature. Your instances will automatically launch onto Dedicated
> Hosts regardless.
(I also manually created a launch template with host resource group and tested it 👍 )

### Issue

I don't think terraform currently support "tenancy Host Resource Group" nor "Dedicated Host" tenancy on Launch Template. Would be great if it does, I think this is the last piece needed to auto scale mac instances

Terraform also doesn't support Host Resource Group under [License Manager](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/licensemanager_license_configuration) (but this is not much of an issue since I think 90% of use cases doesn't require update on LM, so if this resource is created manually and not managed by terraform is not a big deal)

### Things I have tried

1. using [cloudformation_stack](https://serhii.vasylenko.info/2021/01/20/terraforming-mac1-metal-at-AWS.html) suggested by @vasylenko and [terraform-aws-dedicated-host module](https://github.com/DanielRDias/terraform-aws-dedicated-host). While these solutions are great at creating dedicated host that can be allocated to mac1 instance, it does not dynamically allocate dedicated host for mac1 instances.

2. looked into using [placement group ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#placement) as alternative but its not supported by AWS

[dedicated hosts cannot be launch into Placement Group ](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html)
>You cannot launch Dedicated Hosts in placement groups.

**Comment by vasylenko** [comment]
@OliverKoo Thank you for supporting this subject. I was also looking for possible ways to automate the horizontal scaling, and it seems that even Launch Template won't work here. When you manually create the Launch Template (from AWS web Console) with "Dedicated Host" tenancy for mac1.metal, AWS still asks you to launch the host manually:

```
The selected instance type must be launched onto a Dedicated Host. To continue, choose a Dedicated Host that has been allocated for this instance type.
```

Or could you manage to create a Host resource group that was capable of allocating the `mac1.metal` Dedicated Hosts automatically?

**Comment by OliverKoo** [comment]
Hi @vasylenko 👋  - yep I manually created a host resource group under License Manager and use that in my Launch Template.

Gave the Launch Template to my Auto Scaling Group then viola! we scaling 🚀 . But now I like to manage these resource with terraform

Also just want to say all you blogs about mac1.metal instances so far are 💯
