### ISSUE TITLE
Error message "The plugin returned an unexpected error" does not include context

### ISSUE THREAD

**Issue by dpkirchner** [hashicorp/terraform#28532]
### Terraform Version

```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/github v4.3.0
+ provider registry.terraform.io/hashicorp/google v3.53.0
+ provider registry.terraform.io/hashicorp/google-beta v3.53.0
+ provider registry.terraform.io/hashicorp/helm v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.1
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/tls v3.0.0
```

### Terraform Configuration Files

I don't know which part is relevant.

### Debug Output

```
2021-04-27T13:27:18.904-0700 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unknown desc = no client configuration"
```

and

```
│ Error: Plugin error
│
│ The plugin returned an unexpected error from plugin.(*GRPCProvider).ReadResource: rpc error: code = Unknown desc =
│ no client configuration
```

### Expected Behavior

The output should mention which plugin returned the unexpected error and which resource was involved.

### Actual Behavior

The output just says "The plugin returned an unexpected error" with no context.

### Steps to Reproduce

I don't know what plugin or resource is involved so I don't think I can provide steps to reproduce. I'm using a lot of resources and modules so it'd be pretty tricky to track it down without any hints.

**Comment by jbardin** [comment]
Thanks @dpkirchner!

That looks like the one place where we're missing attempting to correlate the configuration context with the error.

It's not the usual error path, because providers should not be returning error information via an rpc error. Looking at your list of providers, I think the most likely culprit here is the kubernetes-alpha provider. You may be able to correlate which resource is returning the error by looking at the trace logs, but hopefully that narrows it down enough to find configuration at fault.

**Comment by dpkirchner** [comment]
@jbardin Yeah, it looks like it was indeed kubernetes-alpha. I eventually found it in the trace logs by grepping for the generic "Plugin Error" and not the slightly more specific "no client configuration" message (which is in the trace logs, but without context). It didn't show me the resource involved but the quantity of errors made it possible to correlate it with a specific resource I apply in bulk.

**Comment by jbardin** [comment]
Closing via #28543

Just noting here that the error shown is not coming through the normal terraform diagnostics message, so while terraform can now add more context to the error and possibly indicate which provider is at fault, the provider itself will need to return the error in correct manner to be able to supply more information.
