### ISSUE TITLE
terraform hangs if provider not in main

### ISSUE THREAD

**Issue by dzmitry-lahoda** [hashicorp/terraform#28533]
put  next into `provider.tf`(replace with yours ids) and run `init`:

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.56.0"
    }
  }
}


provider "azurerm" {
  tenant_id       = "d.."
  subscription_id = "a..."
  features {}
}
```

# result

- terraform hangs

# expected

Error telling me to put provider into main.

# links 
https://github.com/vancluever/terraform-provider-acme/issues/133

**Comment by jbardin** [comment]
Hi @dzmitry-lahoda,

Terraform combined all `*.tf` files in the working directly into a single configuration, so the file name will make no difference as long as the extensions match. I suspect the file name is not relevant here, and you are unable to contact the registry or fetch the provider. Can you share the trace logs from the `init` command, or the steps you used to reproduce the problem?

**Comment by dzmitry-lahoda** [comment]
will repro today. will wait long -may be that is just long download during init with no progress indication.
