### ISSUE TITLE
Custom State File Location Breaks Local Backend Storage

### ISSUE THREAD

**Issue by kudla** [hashicorp/terraform#28534]
### Terraform Version

```
Terraform v0.15.0
on linux_amd64
```

```
Terraform v0.15.1
on linux_amd64
```

### Expected Behavior
Imported state version is consisted with the release supported version

### Actual Behavior
Imported state version is non consisted with the release supported version

### Steps to Reproduce
```
terraform init
terraform import -state="$TF_DATA_DIR/terraform.tfstate"
cat terraform.tfstate
|{
|     "version": 4,
|     "terraform_version": "0.15.0",
|      ...
|}
terraform import -state="$TF_DATA_DIR/terraform.tfstate"
| Error: Failed to load state: Terraform 0.15.0 does not support state version 4, please update.
terraform plan -state="$TF_DATA_DIR/terraform.tfstate"
| Error: Failed to load state: Terraform 0.15.0 does not support state version 4, please update.
```
Looks like custom state file  is a crucial point here. And exactly the `$TF_DATA_DIR/terraform.tfstate` value causes the problem. E.g. `$TF_DATA_DIR/.tfstate` works fine

**Comment by jbardin** [comment]
Hi @kudla,

The `TF_DATA_DIR` contains configuration and data for the cli, and should not be used to store the state, nor should it under normal circumstances be modified by anything other the `terraform` process itself. That directory is also considered somewhat ephemeral, and terraform should be able to recreate that as needed. The `terraform.tfstate` file within that directory is never used to store resource data, and uses an old version format for compatibility. 

Resources should be stored in a state file outside of `TF_DATA_DIR`.
