### ISSUE TITLE
when providing multiple ssh keys, it wrap lines 2 and 3 from the resulting authorized_keys file

### ISSUE THREAD

**Issue by rbrutas** [hashicorp/terraform#2856]
from terraform template;

variable "public_key" {
  default = "\nssh-rsa AAAAB3NzaC1yc2***_Do88GU3G2Im7XFJUL5R\nssh-rsa AAAAB3NzaC1yc**__W4D0iXjgYENIgPbkYDYB\nssh-rsa AAAAB3NzaC1yc2_***66eZLZZBfKkH1VSrSepOGQ=="
}

resulting authorized_keys file on the host, line 2 become invalid since it combined provided keys 1 & 2;

ssh-rsa AAAAB3NzaC1yc2E**_lvyT5iWCSt18do7wsdRTZAzBSue5 Generated by Nova
ssh-rsa AAAAB3NzaC1yc2EAAAAD**_+Do88GU3G2Im7XFJUL5R ssh-rsa AAAAB3NzaC1yc2EA**_bVa5lDThJW4D0iXjgYENIgPbkYDYB
ssh-rsa AAAAB3NzaC1yc2EAAA**_0Zy1X66eZLZZBfKkH1VSrSepOGQ==

**Comment by mitchellh** [comment]
This should be fixed in the latest version of TF.
