### ISSUE TITLE
aws_security_group: ingress rule + security_groups not working

### ISSUE THREAD

**Issue by rradecki** [hashicorp/terraform#2857]
Hi :)

I am trying to create an aws_security_group resource but am getting an error when using security_groups in ingress rule:

```
resource "aws_security_group" "mysql-cluster_haproxy" {
  name = "sg_mysql-cluster_haproxy"
  description = "Allow traffic to mysql-cluster loadbalancer"
  vpc_id = "${var.aws_vpc_id}"
  ingress {
    protocol = "tcp"
    from_port = 22
    to_port = 22
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    security_groups = ["sg-1234567"]
  }
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

```
Error:
aws_security_group.mysql-cluster_haproxy: Error: 1 error(s) occurred:

* Error authorizing security group ingress rules: InvalidGroup.NotFound: You have specified two resources that belong to different networks.
        status code: 400, request id: []

```

Once I change:

    security_groups = ["sg-1234567"]
to

    cidr_blocks = ["0.0.0.0/0"]

it works as expected.

Can you verify and fix this?

BR,
Rafal.

**Comment by catsby** [comment]
Hello –

I apologize for the delay in getting back to you here. By the error message, it seems you're trying to authorize ingress from a Security Group that is in a different VPC. The AWS documentation indicates that you can't do this, e.g. the security groups must all be in the same source VPC:

- http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupIngress.html

Can you confirm for me that the security group you're referencing in `sg-1234567` is in the same VPC?

**Comment by mtunstill** [comment]
You can do this now as long as you have a peering connection between both VPCs that you have referenced. It has to be setup and accepted before it's accepted via CloudFormation.

**Comment by LouiseMcMahon** [comment]
You will need to use the `DependsOn` attribute with your peering config as the value to make cloud formation wait until that has been created before attempting to edit the security group.

**Comment by xxthegonzxx** [comment]
Ran into the same issue and @LouiseMcMahon's comment really helped! Thanks!
More specifically:

https://www.terraform.io/docs/configuration/resources.html#explicit-dependencies

**Comment by bs1px** [comment]
Hi @xxthegonzxx I'm confronted with the same problem even if I'm using the `depends_on` for explicitly depending on the `aws_vpc_peering_connection` and/or on additional resources such as `aws_route`s created exclusively for this VPC peering.

**Comment by xxthegonzxx** [comment]
@bs1px What version of Terraform are you using? I was coming across problems creating an `aws_nat_gateway`. I resolved my issue by adding: `depends_on = ["aws_internet_gateway.this"]` as a dependency for the `aws_nat_gateway` method.

**Comment by bs1px** [comment]
@xxthegonzxx thanks for your reply!
I'm using `Terraform v0.11.3` and struggling creating a `aws_security_group` with an ingress a security group from a peered VPC (using `security_groups` argument under the form `security_groups = ["sg-1234"]`

**Comment by rexroof** [comment]
Is there any way around this?  I'm having the same problem.  
I have a security group that allows access from a security group in another vpc, traffic routes via vpc peering.   this works when done manually in the aws console but not in a terraform ingress.

**Comment by max-lobur** [comment]
Having same issue :(
My peering is created via cloudformation thus can't set a dependency :(
