### ISSUE TITLE
documentation shows that aws_route53_zone exports the zone_id variable, but it does not.

### ISSUE THREAD

**Issue by dansteen** [hashicorp/terraform#2859]
The documentation for aws_route53_zone shows that it exports the zone_id variable, but if you try to use it you get an error:

* Resource 'aws_route53_zone.load' does not have attribute 'zone_id' for variable 'aws_route53_zone.load.zone_id'

Instead you need to use the "id" variable:

aws_route53_zone.load.id

Then things work.  I don't know if this is a bug in the provider or the documentation.

**Comment by apparentlymart** [comment]
The implementation seems to agree that the attribute is called ``zone_id``:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_route53_zone.go#L105

I think something else is going on here. Could you share a bit more of your config?

**Comment by dansteen** [comment]
Interesting.  Here is my config:

```resource "aws_route53_zone" "base" {
  name = "traitify.com"
}

resource "aws_route53_zone" "load" {
  name = "load.awse.traitify.com"
}

resource "aws_route53_record" "load_ns" {
    zone_id = "${aws_route53_zone.base.id}"
    name = "load.awse.traitify.com."
    type = "NS"
    ttl = "300"
    records = [
        "${aws_route53_zone.load.name_servers.0}",
        "${aws_route53_zone.load.name_servers.1}",
        "${aws_route53_zone.load.name_servers.2}",
        "${aws_route53_zone.load.name_servers.3}"
    ]
}
```

If I change `zone_id = "${aws_route53_zone.base.id}"` to `zone_id = "${aws_route53_zone.base.zone_id}"` I get the above error.

Thanks for taking a look at this!  And thanks for terrform, it's fantastic!

**Comment by catsby** [comment]
Hey all – seems this was fixed in https://github.com/hashicorp/terraform/pull/596 , but that also came in 2014, so...

Regardless, the given config applies correctly when using `zone_id = "${aws_route53_zone.base.zone_id}"` , so I'm going to close this.

Let me know if something is still amiss. Thanks!

**Comment by dansteen** [comment]
I have tested this and it seems to work fine now.  Thanks!

**Comment by catsby** [comment]
Thanks for the follow up!
