### ISSUE TITLE
Add post-GPG fix terraform releases to conda-forge

### ISSUE THREAD

**Issue by A114397** [hashicorp/terraform#28592]
### Current Terraform Version

```
0.11.15
```

### Use-cases
We manage terraform version via conda and [conda-forge](https://anaconda.org/conda-forge/terraform), however post gpg-key fix https://github.com/hashicorp/terraform/issues/28525 the "latest" TF 11 version `0.11.15` is not available via conda-forge.

### Attempted Solutions
We are updating directly from https://www.terraform.io/downloads.html to install `0.11.15` however our tooling is much more robust when using the conda package manager.

### Proposal
add release `0.11.15` to conda-forge... please! 😄 

### References
Version `0.11.15` was released to fix this issue https://github.com/hashicorp/terraform/issues/28525

**Comment by jbardin** [comment]
Hi @A114397,

Hashicorp does not maintain this Anaconda package. I would contact the package maintainer for updates.

**Comment by A114397** [comment]
Thank you!
