### ISSUE TITLE
Environment variable interpolation or relative path dev_overrides

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#28602]
### Current Terraform Version

```
0.14.9
```

### Use-cases
Maintaining a `terraform.rc` that's portable across systems, platforms, or users.

### Attempted Solutions

```hcl
dev_overrides {
  "OJFord/provider" = "/home/username/wherever"
}
```

is fine for Linux, but then I need to change it on macOS, or if I had a system where I used a different username.

### Proposal

Any or all of:

1. Shell-like
```hcl
dev_overrides {
  "OJFord/provider" = "$HOME/wherever"
}
```
2. Terraform-like
```hcl
dev_overrides {
  "OJFord/provider" = pathexpand("~/wherever")
}
```
3. Relative to `terraform.rc` (here it's `~/.config/terraform/terraform.rc`)
```hcl
dev_overrides {
  "OJFord/provider" = "../../wherever"
}
```

Env var interpolation is obviously most flexible, since it needn't be `HOME`, so not restricted to being `terraform.rc` or `~` relative.

**Comment by brad-jones** [comment]
My workaround for now is to use [direnv](https://direnv.net/) with a `.envrc` like this.

```sh
export TF_CLI_CONFIG_FILE="$PWD/dev.tfrc"
envsubst '$PWD' <"$TF_CLI_CONFIG_FILE.tpl" >"$TF_CLI_CONFIG_FILE"
```
