### ISSUE TITLE
Terraform crash after queuing a plan 

### ISSUE THREAD

**Issue by burmkiller** [hashicorp/terraform#28628]
This happened while queuing a plan, by changing back to 0.15.0 version the issue resolved itself
### Terraform Version

```
0.15.2
```

### Crash Output
```
Output: panic: interface conversion: interface {} is nil, not map[string]interface {}
```

crash.807455276.log
link to the run
https://app.terraform.io/app/spockee/workspaces/EUW-Platforms/runs/run-WkuXDru68n1kVdHp

**Comment by jbardin** [comment]
Thanks @burmkiller! Fixed via #28624.
