### ISSUE TITLE
FSx support in AWS ECS task definition

### ISSUE THREAD

**Issue by kiawnna** [hashicorp/terraform#28621]
### Current Terraform Version
```
Terraform v0.14.4
...
```

### Use-cases
I would like the ability to add FSx for windows volumes in the task definition resource in my terraform.

Currently, I have to manually create the task definitions, launch my terraform stack, and then update the task definitions to reflect the correct arns of my IAM resources, ECRs, etc.

**Comment by jbardin** [comment]
Hi @kiawnna,

If this is a feature of AWS which is not supported by the provider, I suggest you file an issue with the AWS provider here: https://github.com/hashicorp/terraform-provider-aws/issues, filling out their feature request template. 

If this is a question about using an existing resource, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by kiawnna** [comment]
Hey @jbardin ! Actually, AWS does support FSx in their task definition now, which is great! I can easily add an FSx volume if I want to work within AWS. Unfortunately, I don't see that support for terraform's task definition resource -- you can add EFS volume blocks, and docker volumes, but not FSx volumes. Am I misunderstanding something? If this is an AWS provider issue, let me know and I will reach out via the link above. But I'm still a little confused about exactly who should/could implement this, as it seems like AWS already has and now terraform just needs to mirror that support..? :) Thank you!

**Comment by jbardin** [comment]
Hi @kiawnna, The AWS provider project is linked above, and is where new features for that provider would need to be implemented. This repository is only for the Terraform CLI, and is independent from the providers. You can also find this information in the terraform registry, where each provider listed will have a link to the source code and another to "Report an issue".

Thanks!
