### ISSUE TITLE
Digital Ocean provider, remote-exec provisioner cannot connect via SSH.

### ISSUE THREAD

**Issue by romanvbabenko** [hashicorp/terraform#2863]
Terraform 0.6.1 agent=false doesn't work for me, so I've created the ticket as you guys @phinze @ajlanghorn told me here #2614 

config is quiet simple 

```
# Configure the DigitalOcean Provider
provider "digitalocean" {
  token = "<cut>"
}

# Create a new Web droplet in the nyc2 region
resource "digitalocean_droplet" "web" {
    image = "ubuntu-15-04-x64"
    name = "web-1"
    region = "fra1"
    size = "512mb"
    ssh_keys = ["993002"]

    connection {
      agent = false
    }

    provisioner "remote-exec" {
        inline = ["sudo aptitude install htop"]
    }
}
```
part of log

```
digitalocean_droplet.web (remote-exec): Connecting to remote host via SSH...
digitalocean_droplet.web (remote-exec):   Host: <cut>
digitalocean_droplet.web (remote-exec):   User: root
digitalocean_droplet.web (remote-exec):   Password: false
digitalocean_droplet.web (remote-exec):   Private key: false
digitalocean_droplet.web (remote-exec):   SSH Agent: false
```

ERROR
```
Error applying plan:

1 error(s) occurred:

* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

I tried to login as root directly via SSH and it worked.

**Comment by ajlanghorn** [comment]
Can you add TF_LOG=1 TF_LOG_PATH=terraform.log as environment variables before that command is run so we can get the output in to terraform.log and pasted in to here? It looks like an underlying SSH error at first glance, especially given the error.

**Comment by phinze** [comment]
@romanvbabenko in your config, it looks like you are assigning an SSH key to the droplet, but then in your connection block you're not doing anything to provide that key to the SSH connection.

Seems like you need to do either `private_key` or `agent` in order to tell SSH how to find the proper key to connect.

**Comment by romanvbabenko** [comment]
@phinze setting connection key_file param has helped, thanks

**Comment by thachmai** [comment]
I ran into the same problem. For further references, here's one way to solve it:

DigitalOcean doesn't let you supply a password during account creation, so ssh key seems to be the only way to automate remote-exec. In the resource declaration, specify an ssh_keys value (retrievable from DO API). Then, you should declare in the resource the value `connection = { key_file = "path_to_the_id_rsa_associated_with_the_ssh_key" }`
