### ISSUE TITLE
 terraform show blank after import

### ISSUE THREAD

**Issue by sreeninair** [hashicorp/terraform#28637]
Hi there,

I have imported a vpc resource , after import the terraform show is empty and the resource is actually not added.

```
terra2 % terraform -v
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.39.0
```
```
lap.top@toplap terra2 %  terraform import aws_vpc.myapp-vpc vpc-87y9h867gt86t97yh
aws_vpc.myapp-vpc: Importing from ID "vpc-87y9h867gt86t97yh"...
aws_vpc.myapp-vpc: Import prepared!
  Prepared aws_vpc for import
aws_vpc.myapp-vpc: Refreshing state... [id=vpc-87y9h867gt86t97yh]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

```
lap.top@toplap terra2 % terraform show

lap.top@toplap terra2 %
```

```
lap.top@toplap terra2 % cat main.tf
provider "aws" {
	region = "us-west-2"
}
resource "aws_vpc" "myapp-vpc" {
#	cidr_block = "10.2.0.0/16"
  # (resource arguments)
}
```

**Comment by jbardin** [comment]
Hi @sreeninair,

Thanks for filing the issue, but I am unable to reproduce this. Do you have any other terraform configuration in the same directory, or are you specifying remote state storage of some sort? Can you provide all the steps to reproduce this from scratch? Setting `TF_LOG_CORE=trace` may offer clues about where the state is being loaded and stored.

**Comment by sreeninair** [comment]
Hi James, 
Thanks for the update.
Initially I started the import in a directory which contains some existing terraform code, the remote storage of that directory is  s3 and using DynamoDb for locking. I also thought the issue might be because of the presence of existing files. The above output is from a new directory which I created just to perform the import.  File contents are
.terraform		.terraform.lock.hcl	main.tf			terraform.tfstate

Is there any know issue while using remote s3 storage and I suppose the remote storage which I configured will be only for the other directory.

**Comment by Willis0826** [comment]
Hi, I also faced the issue. I tried to import `aws_route53_record` but the state file is not change. Therefore, when I run the `terraform apply` command it try to create a new resource.

The environment I used:
```
terraform -v
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
```

The command I ran to import the resource:
```
AWS_PROFILE={my_profile_name} terraform import 'aws_route53_record.my-record' "***********_my.domain.com_A"
```

The result after I run the import command:
```
aws_route53_record.my-record: Import prepared!
  Prepared aws_route53_record for import
aws_route53_record.my-record: Refreshing state... [id=***********_my.domain.com_A]

Import successful!
....
```

**Comment by jbardin** [comment]
Thanks @Willis0826, that is a great clue!

It turns out that most resource don't fully implement import, and will accept any given id. Terraform follows this up by reading the resource, but the validation for a missing resource was lost in some refactoring.  This may very well be the original issue here too, but we'll have a fix in the next release to verify that.

**Comment by Jasstkn** [comment]
Same problem here. I used wrong credentials for Hetzner Cloud but terraform showed successful output.
