### ISSUE TITLE
Error in the documentation of the blockstorage_volume_v1 resource of the OpenStack provider

### ISSUE THREAD

**Issue by berendt** [hashicorp/terraform#2864]
According to https://www.terraform.io/docs/providers/openstack/r/blockstorage_volume_v1.html valid values for ``volume_type`` are either SATA or SSD.

```
volume_type - (Optional) The type of volume to create (either SATA or SSD). Changing this creates a new volume.
```

This is not correct. The possible values for ``volume_type`` depend on the used OpenStack environment. You can use ``openstack volume type list`` or ``cinder type-list`` to list available volume types of the used OpenStack environment. `(either SATA or SSD)` should be removed.

Example:

```
% openstack volume type list
+--------------------------------------+------+
| ID                                   | Name |
+--------------------------------------+------+
| 965716f4-7fcb-441d-b2aa-ad48f44b41b7 | Ceph |
+--------------------------------------+------+
```

**Comment by catsby** [comment]
#2867 was merged, thanks!
