### ISSUE TITLE
Please consider updating go-getter to 1.5.3

### ISSUE THREAD

**Issue by graywolf-at-work** [hashicorp/terraform#28664]
Hello,

go-getter in version 1.5.3 added support for aws_profile query string for s3
protocol. That is something we really need, so I would like to ask if you would
please consider releasing patch version with just update of go-getter?

**Comment by jbardin** [comment]
Hi @graywolf-at-work,

I don't see any aws related changes between v1.5.2 and v1.5.3. It looks like you're referring to https://github.com/hashicorp/go-getter/pull/261, which is in v1.5.0, and updated here with #26762.

Thanks!
