### ISSUE TITLE
Error: no suitable version is available for  plugin in provider.aws: version = 3.38

### ISSUE THREAD

**Issue by wanismvp** [hashicorp/terraform#28683]
I specify this version but getting this error 

provider "aws" {
  region  = var.aws_region
  version = "3.38.0"

```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "random" (hashicorp/random) 3.1.0...

No provider "aws" plugins meet the constraint "3.38.0".
```
if I remove the version field, the lasted version being pulled is 3.37, while https://registry.terraform.io/providers/hashicorp/aws/latest 3.38 and 3.39 are not accessible

terraform:  0.12.30

```
├── provider.aws 3.38.0
├── provider.aws.account_data
├── provider.aws.bucket_region
├── provider.aws.cloudfront-region-provider
├── provider.aws.s3-pod-provision
├── provider.template
├── provider.terraform
├── module.password-generator-pgdb-augmented
│   ├── provider.aws (inherited)
│   └── provider.random
├── module.password-generator-pgdb-datacat
│   ├── provider.aws (inherited)
│   └── provider.random
└── module.password-generator-pgdb-main
    ├── provider.aws (inherited)
    └── provider.random


```

**Comment by devopsrick** [comment]
Any reason you aren't using 0.12.31?  I think those two releases are using the new GPG signing key.  Though I thought it just complained explicitly about the key mismatch, I would bump your terraform version up and try again.

**Comment by devopsrick** [comment]
Yep sounds like you can't install the newer provider versions with the older terraform client as terraform cannot verify them:  https://github.com/hashicorp/terraform/issues/28557

**Comment by jbardin** [comment]
Hi @wanismvp, @devopsrick has the correct answer here, you will not be able to automatically download and verify new plugin releases without upgrading terraform to the latest patch release.

Thanks!
