### ISSUE TITLE
AWS Budget: CostFilters Wrong Field type

### ISSUE THREAD

**Issue by zakariahoussa** [hashicorp/terraform#28698]
### Terraform Version

Terraform v0.13.5

### Terraform Configuration Files

```terraform
resource "aws_budgets_budget" "ec2" {
  name              = "budget-ec2-monthly"
  budget_type       = "COST"
  limit_amount      = "1200"
  limit_unit        = "USD"
  time_period_end   = "2087-06-15_00:00"
  time_period_start = "2017-07-01_00:00"
  time_unit         = "MONTHLY"
  cost_filters = {
     LinkedAccount = ["XXXXXXXXXXXX'',''YYYYYYYYYYYYYY"],
     Service = "Amazon Elastic Compute Cloud - Compute"
  }
 }

**Inappropriate value for attribute "cost_filters": incorrect map element type:
string required.**

 
I tried also this way 

  cost_filters = {
     LinkedAccount = "XXXXXXXXXXXX, YYYYYYYYYYYYYY"
     Service = "Amazon Elastic Compute Cloud - Compute"
  } => it is taken as one string search
  or 
  cost_filters = {
     LinkedAccount = "XXXXXXXXXXXX"
      LinkedAccount = "YYYYYYYYYYYY"
     Service = "Amazon Elastic Compute Cloud - Compute"
    } =>the last LinkedAccount value erase the previous one.

Recommendation:
**Please adjust that the cost_filters should be map of list not string**
Notes:In the AWS CLI/Cloudformation it works , it has the right field type



### Debug Output
Inappropriate value for attribute "cost_filters": incorrect map element type:
string required.

### Expected Behavior

Create Budget

### Actual Behavior

Bug
### Steps to Reproduce
<!--
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`
-->
Use the ressource above

**Comment by jbardin** [comment]
Hi @zakariahoussa,

The `cost_filters` attribute for this resource is of the type `map(string)`, so there is no way to assign a list of values.
If this is not adequate to represent the required values I suggest you file an issue with the AWS provider.

Thanks!

**Comment by zakariahoussacroesus** [comment]
Hello jbardin,

From the AWS side the field is type map(list), I invite you the examples provided in their page

https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_budgets_CreateBudget.html

"CostFilters": {
      "TagKeyValue" : ["user:Key$value1","user:Key$value2"]
   },

**Comment by zakariahoussa** [comment]
Hello jbardin,
From the AWS side this field is Map(list), i invite you to check the API doc https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_budgets_CreateBudget.html


      "CostFilters": { 
         "string" : [ "string" ]
      },
Example
   "CostFilters": {
      "TagKeyValue" : ["user:Key$value1","user:Key$value2"]
   },

Thanks!

**Comment by jbardin** [comment]
@zakariahoussa, the AWS provider issue tracker is located here: https://github.com/hashicorp/terraform-provider-aws/issues. 
Searching there for `aws_budgets_budget` brings up a number of existing issues already, so I suspect this is a known problem.

Thanks!
