### ISSUE TITLE
Plan should WARN if resources that can have tags do not

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#28694]
Now that terraform providers can provide [default_tags](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider), it would be really cool if we could get a _warning_ in `terraform plan` output when a resource that _can_ have tags _does not_.

I got to thinking about this while switching from a `local.common_tags` convention to the new `default_tags` convention, specifically with child modules. Previously i was providing sane defaults in child modules using the common_tags variable but now I'm removing that and _trusting_ that parent modules will define the `default_tags` in the provider (which trickles do the child module resources).

A warning in `plan` output could help ensure people are making use of this **fantastic** new feature. It could also help accelerate providers adopting `default_tags` into their codebase!

### Current Terraform Version

```
tf version
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.38.0
```

**Comment by jbardin** [comment]
Hi @drewmullen,

Thanks for filing the issue. The feature you are referring to is part of the AWS provider configuration, and is not a feature particular to Terraform itself. Terraform does not have concept of what `tags` are, or how they relate to resources, and can only tell when a schema defines an attribute named `tags` and act accordingly. Providers already have mechanisms for making attributes required and validating their contents, and as such this would fall into a provider feature request. 


Thanks!

**Comment by drewmullen** [comment]
my mistake - i saw the log post from hashi and mistakenly thought it was enabled from terraform source
