### ISSUE TITLE
Even with a false sensitive flag, outputs are still treated as sensitive 

### ISSUE THREAD

**Issue by senjoux** [hashicorp/terraform#28692]
Hi there,

I am not sure, if this is the expected behaviour of Terraform, but in reality setting the "sensitive" flags to "false"
should expose the values/outputs as plain text. 

### Terraform Version
```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0
```

### Terraform Configuration Files
```
# main.tf
resource "local_file" "book" {
    filename = each.value
    # als Set konvertieren
    for_each = toset(var.books)
}

resource "local_file" "country" {
    filename = each.value
    # als Set konvertieren
    for_each = toset(var.countries)
}

resource "local_file" "pet" {
    filename = each.value
    for_each = var.pets
}


# variables.tf
variable "books" {  
  default = ["Don-Quixote.txt", "The-Lion.txt", "Pinocchio.txt"] 
  sensitive = false
}

variable "countries" {
  type = list(string)
  default = ["Tunisia.txt", "Germany.txt", "Ghana.txt"]  
  sensitive = false
}

variable "pets" {
  type = set(string)  
  default = ["Cat.txt", "Cow.txt", "Dog.txt"]  
  sensitive = false
}


# output.tf
output "bk" {
  value = local_file.book
  sensitive = false
}

output "ct" {
  value = local_file.country
  sensitive = false
}

output "pt" {
  value = local_file.pet
  sensitive = false
}  
...
```

### Output

 Error: Output refers to sensitive values
│ 
│   on output.tf line 3:
│    3: output "bk" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm
│ your intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
╵
╷
│ Error: Output refers to sensitive values
│ 
│   on output.tf line 7:
│    7: output "ct" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm
│ your intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
╵
╷
│ Error: Output refers to sensitive values
│ 
│   on output.tf line 11:
│   11: output "pt" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm
│ your intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true

### Expected Behavior
Variable shouldn't be treated as sensitive.
### Actual Behavior
Variables treated as sensitive.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### References
https://www.terraform.io/docs/language/functions/toset.html
https://www.terraform.io/docs/language/values/outputs.html

**Comment by jbardin** [comment]
Hi @senjoux,

The `sensitive` attribute only effects the definition of the variable or output itself, but in order to allow sensitivity to be maintained, it will not remove the marks from values passed in from another source. In order to override the sensitivity of a particular value, we have added the [`nonsensitive`](https://www.terraform.io/docs/language/functions/nonsensitive.html) function.

Thanks!

**Comment by senjoux** [comment]
Thanks @jbardin! 



This [know-how article](https://www.terraform.io/upgrade-guides/0-15.html) is also helpful to get a clear picture on how sensitive values are treated by **outputs**.
