### ISSUE TITLE
VMWare vSphere - datastore ISO not connected at VM power on

### ISSUE THREAD

**Issue by cyrokamogawa** [hashicorp/terraform#28705]
### Terraform Version

```
Terraform v0.15.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/vsphere v1.26.0
```

### Terraform Configuration Files

```terraform
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 4096
  guest_id = "windows8Server64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 100
  }

  cdrom {
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    path         = <path/to/iso>
  }
}
```

### Expected Behavior
The datastore ISO is connected to the VM at power on automatically

### Actual Behavior
The datastore ISO is not connected to the VM at power on automatically

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. Open VCSA and test the VM

### Additional Context
When I try to launch a VM console in VCSA, it says "Operating system not found." Looking at the VM settings, the CD/DVD drive section has a checkbox checked for "Connect at power on." This is supposed to connect the datastore ISO that I specified to the VM, but the ISO is not connected. I have to manually connect it and reboot the VM for it to work. We've built VMs through Power CLI before and did not have this problem.

**Comment by jbardin** [comment]
Hi @cyrokamogawa,

If you wish to file an issue with the vSphere provider, you can do so in their project repository here: https://github.com/hashicorp/terraform-provider-vsphere/issues. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
