### ISSUE TITLE
Adding in support to programatically give teams access to Dependabot and security alerts 

### ISSUE THREAD

**Issue by uceimmp** [hashicorp/terraform#28722]
### Current Terraform Version
14.5

### Use-cases
We have recently migrated our repositories to GitHub and we are currently managing our repositories and user access via Terraform. We have recently enabled security scanning and Dependabot alerts on our repositories but have had to give the relevant teams membership to this resource manually (which is very time consuming). 

It would be fantastic if there could be terraform that would enable us to do this. 

### Proposal
The solution could be in the form of a resource block e.g.: 

resource "github_security_alerts_membership" "membership_for_repository_x" {
repository = ""
team_id/user_id = ""
}

**Comment by jbardin** [comment]
Hi @uceimmp,

This looks like a feature request for the [GitHub provider](https://registry.terraform.io/providers/integrations/github/latest). If so, you can file an issue in their repository here: https://github.com/integrations/terraform-provider-github/issues

Thanks!
