### ISSUE TITLE
provider dnacenter crash

### ISSUE THREAD

**Issue by sandeep3in** [hashicorp/terraform#28728]
provider dnacenter crash with adding global IP pool.

c:\tform-projects\dnac-tform>terraform version
[WARN] Invalid log level: "\"TRACE\"". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR OFF][WARN] Invalid log level: "\"TRACE\"". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR OFF]Terraform v0.15.1
on windows_amd64
+ provider registry.terraform.io/cisco-en-programmability/dnacenter v0.0.3

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html

c:\tform-projects\dnac-tform>terraform  apply
[WARN] Invalid log level: "\"TRACE\"". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR OFF][WARN] Invalid log level: "\"TRACE\"". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR OFF][WARN] Invalid log level: "\"TRACE\"". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR OFF][WARN] Invalid log level: "\"TRACE\"". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR OFF][WARN] Invalid log level: "\"TRACE\"". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR OFF]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # dna_network_global_ip_pool.response will be created
  + resource "dna_network_global_ip_pool" "response" {
      + gateway          = "13.0.0.1"
      + id               = (known after apply)
      + ip_address_space = "IPv4"
      + last_updated     = (known after apply)
      + type             = "Generic"

      + item {
          + client_options          = (known after apply)
          + configure_external_dhcp = (known after apply)
          + context                 = (known after apply)
          + create_time             = (known after apply)
          + dhcp_server_ips         = (known after apply)
          + dns_server_ips          = (known after apply)
          + gateways                = (known after apply)
          + id                      = (known after apply)
          + ip_pool_cidr            = "13.0.0.0/24"
          + ip_pool_name            = "tform-created"
          + ipv6                    = (known after apply)
          + last_update_time        = (known after apply)
          + overlapping             = (known after apply)
          + owner                   = (known after apply)
          + parent_uuid             = (known after apply)
          + shared                  = (known after apply)
          + total_ip_address_count  = (known after apply)
          + used_ip_address_count   = (known after apply)
          + used_percentage         = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

[WARN] Invalid log level: "\"TRACE\"". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR OFF]dna_network_global_ip_pool.response: Creating...
╷
│ Error: json: cannot unmarshal number 9223372036854776000 into Go struct field GetGlobalPoolResponseResponse.response.totalIpAddressCount of type int
│
│   with dna_network_global_ip_pool.response,
│   on check1.tf line 25, in resource "dna_network_global_ip_pool" "response":
│   25: resource "dna_network_global_ip_pool" "response" {
│

**Comment by sandeep3in** [comment]
``terraform {
  required_providers {
    dnacenter = {
      source = "cisco-en-programmability/dnacenter"
      version = "0.0.3"
    }
  }
}

provider "dnacenter" {

  username = "admin"
  password = "Start@123"
  base_url = "https://10.104.55.22"
  debug = "false"
  ssl_verify = "false"
}
/*
data "dna_network_global_ip_pool" "response" {
  provider = dnacenter
  # offset = 0
  # limit = 4
}
*/
resource "dna_network_global_ip_pool" "response" {
  provider         = dnacenter
  type             = "Generic"
  ip_address_space = "IPv4"
  gateway   ="14.0.0.1"
  count =1
  item {
    ip_pool_name   = "tform-created-1"
    ip_pool_cidr   = "14.0.${count.index}.0/24"
  }
}

**Comment by jbardin** [comment]
Hi @sandeep3in,

This appears to be an issue with a "dna" Terraform provider. You can file an issue in that provider's repo. You can find a link to the issue tracker on the provider's registry page. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
