### ISSUE TITLE
Unable to use IAM Access control method using terraform aws_msk_cluster resource. AWS MSK

### ISSUE THREAD

**Issue by raoim** [hashicorp/terraform#28720]
HI there,

I am trying to develop a module to create AWS MSK. I would like to enable IAM authentication for MSK resource
I am following the below link, but I don't see anything related to IAM authentication.
[(https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster#sasl)]

(https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster#sasl)

> 

 dynamic "client_authentication" {
    for_each = var.client_tls_auth_enabled || var.client_sasl_iam_enabled ? [1] : []
    content {
      dynamic "tls" {
        for_each = var.client_tls_auth_enabled ? [1] : []
        content {
          certificate_authority_arns = var.certificate_authority_arns
        }
      }
      dynamic "sasl" {
        for_each = var.client_sasl_iam_enabled ? [1] : []
        content {
          **_iam = var.client_sasl_iam_enabled_**
        }
      }
    }
  }

**Comment by jbardin** [comment]
Hi @raoim,

This appears to be a bug or feature request for the AWS provider. If that is correct, please file an issue with the information requested in the issue template here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
