### ISSUE TITLE
Terraform registry website: Wrong variable type display in inputs tab

### ISSUE THREAD

**Issue by josef-brandl-db** [hashicorp/terraform#28734]
https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest?tab=inputs shows the `default_max_pods_per_node` var as string, but it really is a number. The readme of the module lists the type correctly.

Implementation:

```tf
variable "default_max_pods_per_node" {
  description = "The maximum number of pods to schedule per node"
  default     = 110
}
```
[source](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/9172b3eaeeb806caca29aa1e3e83e58a26df57b1/variables.tf#L360-L363)

It seems the type is parsed incorrectly.

I do not believe this to be an issue with the Google module. Instead it seems that the parsing is getting the type wrong. Plz refer me to the correct repo, if this is not the right one. I didn't find a way to report the bug on the website and a Google search didn't yield additional info.

**Comment by alisdair** [comment]
Thanks for reporting this! For issues with the Terraform Registry, please send an email to terraform-registry@hashicorp.com, which is monitored by the team at HashiCorp responsible for the registry. I'm closing this issue out because it's not a Terraform core bug.

**Comment by josef-brandl-db** [comment]
I reported the bug to the email. thx :)
