### ISSUE TITLE
bad change detection with empty-string security groups

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#2873]
I made a change to my security groups that is falsely causing a rebuild of instances.

Basically I went from this:
```
security_groups = ["a", "b"]
```
To this:
```
security_groups = ["a", "b", "${split(",", var.additional_security_groups)}"
```

And in the cases where additional_security_groups is empty, terraform still thinks the list changed  and therefore wants to recreate my instances. I would expect that change to be a no-op.

**Comment by catsby** [comment]
Hey @ryanking – we chatted in IRC yesterday, did the `${concat("a","b", split())}` suggestion work?

**Comment by ryanking** [comment]
Here's what I had to do to get it to work:

vpc_security_group_ids = ["${split(",", replace(format("%s,%s,%s,",
aws_security_group.instance.id, var.ssh_from_bastion_id,
var.additional_instance_security_groups), "/[,]+$/", ""))}"]

**Comment by catsby** [comment]
They key to avoiding the rebuilds here is the use of `vpc_security_group_ids` over `security_groups`; the later should only be used with EC2 Classic, where rebuilding instances is a requirement when changing security groups of instances.
