### ISSUE TITLE
"Error: pq: syntax error at or near "AS"" when running "terraform init" with pg backend

### ISSUE THREAD

**Issue by fantasy4z** [hashicorp/terraform#28732]
### Terraform Version

```
Terraform v0.15.3
on darwin_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.14.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.27"
    }
  }

  backend "pg" {
    conn_str = "postgres://terraform@localhost:8432/terraform_backend?sslmode=disable"
  }
}
```

### Debug Output

https://gist.github.com/fantasy4z/cefe3edb10707a40a6bad1437aca2005

### Expected Behavior

Inited pg backend successfully.

### Actual Behavior

Showed `Error: pq: syntax error at or near "AS"`

### Steps to Reproduce

`terraform init`

### Additional Context

I believe the root cause of this bug is at https://github.com/hashicorp/terraform/blob/e39ba2816bb2de65edd80305494dfd5f433a5a27/internal/backend/remote-state/pg/backend.go#L108
which tries to create sequence with `AS bigint`. However, `AS <data type>` expression is not supported by PostgreSQL.

PostgreSQL doc: https://www.postgresql.org/docs/9.5/sql-createsequence.html

**Comment by jbardin** [comment]
Hi @fantasy4z,

The pg backend requires a minimum version of PostgreSQL 10, which added the `CREATE SEQUENCE AS`  command.
Note that the linked version 9.5 is no longer supported, and the 9 series is soon to be end of life this year. 

Thanks!

**Comment by fantasy4z** [comment]
https://www.terraform.io/docs/language/settings/backends/pg.html
"Stores the state in a Postgres database version 9.5 or newer."

So this page delivers false (or outdated) information...

**Comment by jbardin** [comment]
Thanks @fantasy4z! We can update the documentation to match.
