### ISSUE TITLE
Bug: google_sql_user password state entry gets updated despite of failed apply

### ISSUE THREAD

**Issue by progressivesasha** [hashicorp/terraform#28740]
# Issue description
`google_sql_user` password state entry gets updated despite of failed apply.

There was a password change for cloudsql user. First run of terraform apply failed with 403 error. After 403 was fixed (the service account used for running terraform missed `cloudsql.users.update` permission), the second run of `terraform plan` didn't return any changes. It means, that terraform state was updated after (or even before) the first failed run. As a result, password wasn't changed, and 3rd run using correct permissions and one more password change was required.

> Tested with terraform version 0.12.16/0.12.21 + gcp provider version 2.20.0 and terraform version 0.15.3 + gcp provider version 3.67.0
# Steps to reproduce the issue
Sample configuration:
```
resource "google_sql_database_instance" "this" {
  database_version = "POSTGRES_9_6"
  name             = "cloudsql-instance"
  project          = "project"
  region           = "us-west1"

  settings {
    activation_policy           = "ALWAYS"
    authorized_gae_applications = []
    availability_type           = "ZONAL"
    crash_safe_replication      = false
    disk_size                   = 200
    disk_autoresize             = false
    disk_type                   = "PD_SSD"
    pricing_plan                = "PER_USE"
    replication_type            = "SYNCHRONOUS"
    tier                        = "db-custom-2-7680"

    ip_configuration {
      ipv4_enabled = true
      require_ssl  = false

      authorized_networks {
        name  = "WHATEVER"
        value = "0.0.0.0/0"
      }
  }

  timeouts {}
}

resource "google_sql_user" "this" {
   name     = "change_pass_user"
   instance = google_sql_database_instance.this.name
   password = "123123qwewq"
}

resource "google_sql_user" "postgres" {
   name     = "postgres"
   instance = google_sql_database_instance.this.name
   password = "12321qwewq"
}
```
run:
```
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/json/for/SA/without/cloudsql.users.update/permission
terraform init
terraform plan -out=tfplan
terraform apply tfplan
```
Then, change the password for `change_pass_user`:
```
resource "google_sql_user" "this" {
   name     = "change_pass_user"
   instance = google_sql_database_instance.this.name
   password = "newpass"
}
```
And run:
```
terraform plan -out=tfplan
terraform apply tfplan
```

## What's the expected result?
You should receive the `googleapi: Error 403: The client is not authorized to make this request., notAuthorized` error.
The state should be the same as before the apply.

## What's the actual result?
We receive the `googleapi: Error 403: The client is not authorized to make this request., notAuthorized` error.
But looking into statefile, we see the password was actually changed.

**Comment by jbardin** [comment]
Hi @progressivesasha,

Thanks for filing the issue, but this appears to be an issue with the google provider. Terraform will save the state that is returned by the provider in case of an error, since partial changes may have been saved already in the remote service. If the password was not saved correctly in the remote service, it is up to the provider to return the old value or nothing at all, in which case the prior known state will be saved.

Thanks!
