### ISSUE TITLE
The true and false result expressions must have consistent types. The given expressions are object and object, respectively.

### ISSUE THREAD

**Issue by Lasering** [hashicorp/terraform#28751]
### Terraform Version
Its failing with: `Terraform v0.15.3` and `Terraform v0.14.10`

### Steps to Reproduce
1. `terraform init`
2. `terraform console`
3. Paste: `true ? { attributes = [] } : { backend-ip = "192.168.1.20", backend-port = 443}`

Also fails with `false ? ...`

### Actual Behavior
```
Error: Inconsistent conditional result types

  on <console-input> line 1:
  (source code not available)

The true and false result expressions must have consistent types. The given
expressions are object and object, respectively.
```

### Expected Behavior
The if should type check with no problems.

### Additional Context
The result returned by the if will be passed to the `jsonencode` function, thus producing different JSON's according to the if condition.

**Comment by jbardin** [comment]
Hi @Lasering,

The Terraform language (actually HCL in this case) must be able to resolve the type of the conditional expression expression, meaning that the true and false results must have the same type, or be convertible to the same type. What you have here is an `object({attributes=list(any)})` and an `object({backend-ip=string,backend-port=number})`, which are not structurally equivalent. 

If you want the result to be an object with mixed attribute types (meaning the true and false value cannot be converted to a map), you will need to ensure all the desired fields are represented. This might be a little clearer my assigning the values to locals beforehand:

```
locals {
  true_expr = {
    attributes = []
    backend-ip = ""
    backend-port = 0
  }

  false_expr = {
    attributes = []
    backend-ip = "192.168.1.20"
    backend-port = 443
  }
}

output "out" {
  value = true ? local.true_expr : local.false_expr
}
```

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, even though I understand that Terraform isn't doing what you expect it to, and so I'm going to close it. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.


Thanks!

**Comment by Lasering** [comment]
@jbardin If structural equivalence is what HCL looks for then I suggest the error message should be way more clear and informative.

The code I presented is simplified. In my scenario I cannot extract the if branches to local variables (I'm using count.index to compute values for the if branches). Also my use case is to then pass the resulting object/map to jsonencode, thus I should be able to force it to be a `map(any)` somehow (but that would be a whole new feature request).

**Comment by jbardin** [comment]
Unfortunately `map(any)` does not work here either, as a map must have a single value type. If the two arguments can be unified to a single map type, in most cases it will work, however unification to `map(any)` is not supported as a concrete type is needed for evaluation.

Getting a more useful error here is difficult, because the expression evaluation is happening in the hcl language package, while the comparison and conversion is happening in the zclconf/go-cty package. I agree the `The given expressions are object and object` error is not very helpful in this case, and improvements there would need to start in the upstream packages.
