### ISSUE TITLE
single occurence aws_autoscaling_schedule yields a ValidationError on destroy

### ISSUE THREAD

**Issue by alexmnyc** [hashicorp/terraform#28760]
```
resource "aws_autoscaling_schedule" "ca_asg_spin_up" {
  scheduled_action_name  = "Spin up ca worker for ${var.cluster_name}"
  min_size               = 1
  desired_capacity       = 1
  max_size               = data.aws_autoscaling_group.current[0].max_size
  start_time             = timeadd(timestamp(), "45s")
  end_time               = timeadd(timeadd(timestamp(), "45s"), "10m")
  autoscaling_group_name = data.aws_autoscaling_group.current[0].name
}
```

```
terraform apply >>> OK
terraform destroy >>> after 1 minute or so 
Error: Error deleting Autoscaling Scheduled Action: ValidationError: Scheduled action name not found
	status code: 400, request id: 46dbd9ad-c2f9-4302-8ba3-dacdaf7ffd85
```
Expected, if aws_autoscaling_schedule cannot be found and start_time is in the past, assume that this was a single shot fire and forget action. it should not produce a ValidationError

**Comment by jbardin** [comment]
Hi @alexmnyc,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
