### ISSUE TITLE
aws_vpn_gateway.id doesn't work until applied once

### ISSUE THREAD

**Issue by georgebashi** [hashicorp/terraform#2876]
I wrote definitions for an aws_vpn_gateway and some aws_customer_gateways and aws_vpn_connections based off it. When planning, I get:

```
* Resource 'aws_vpn_gateway.uswest1_slprod' does not have attribute 'id' for variable 'aws_vpn_gateway.uswest1_slprod.id'
```

If I delete the aws_customer_gateways and aws_vpn_connections, it will then successfully apply. If I then put those configs back, it will all successfully apply. It seems as though the `id` output doesn't exist until the aws_vpn_gateway has been applied.

**Comment by georgebashi** [comment]
This also appears to happen for `aws_security_group` resources too.

**Comment by josephholsten** [comment]
confirmed for `aws_security_group`.

**Comment by catsby** [comment]
Hey friends – sorry for the silence here: I've tried this config and had no issues, so I'm going to close this as "fixed". Let me know if you're still having issues.

```hcl
resource "aws_vpc" "foo" {
	cidr_block = "10.1.0.0/16"
}

resource "aws_vpn_gateway" "foo" {
	vpc_id = "${aws_vpc.foo.id}"
}

resource "aws_route_table" "foo" {
	vpc_id = "${aws_vpc.foo.id}"

	propagating_vgws = ["${aws_vpn_gateway.foo.id}"]
}

resource "aws_security_group" "bar" {
  name = "bar"
  description = "bar"
  vpc_id = "${aws_vpc.foo.id}"

  ingress {
    protocol = "tcp"
    from_port = 4001
    to_port = 4001
    cidr_blocks = ["0.0.0.0/0"]
  }
}

output "gateway_id" {
  value = "${aws_vpn_gateway.foo.id}"
}

output "sg_id" {
  value = "${aws_security_group.bar.id}"
}
```
