### ISSUE TITLE
"Objects have changed outside of Terraform" but no actual changes are shown

### ISSUE THREAD

**Issue by twbecker** [hashicorp/terraform#28776]
I have a configuration I've just updated to 0.15.4 and now terraform plan/apply always reports the following:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these
changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

```

I've done as the message suggests and issued `terraform apply -refresh-only` but the issue persists. I would not expect to see `Note: Objects have changed outside of Terraform` unless they have in fact changed. Is this working as expected?

**Comment by szEvEz** [comment]
I guess it's somewhat working as expected - https://github.com/hashicorp/terraform/pull/28634

But I really would love to have the option to get rid of that output, as I do not want to see changes outside of terraform, that I decided to ignore via the lifecycle configuration.

**Comment by twbecker** [comment]
I don't understand the entirety of that PR but I don't see anything that would lead me to believe this was expected. To be clear, I'm not talking about the output of drift detection in general, I'm talking about the specific verbiage that "Objects have changed outside of Terraform" but then no such changes being displayed.

**Comment by jbardin** [comment]
Thanks for filing the issue @twbecker,

You are correct that the output here is not expected, or at least with the inconsistencies you see. I think the primary cause here is that the renderer is showing the `Objects have changed` output if the states have changed at all, while the code which renders the diff will skip possibly trivial changes introduced by ill-behaving providers. This might be confirmed by looking for warnings in the logs about providers returning unexpected values.

Another possibility is that there are computed values which change each time the resource is read, but the change is suppressed by terraform or the provider.

Do you have a configuration you can share which can reproduce the output?

Thanks!

**Comment by leonsmith** [comment]
I think there are 2 issues here that should be split?

@twbecker original issue is around the diff messaging showing when its empty (as explained by yourself @jbardin)

and another issue that @szEvEz raised in that even when you ignore an attribute it still shows it as drifting 
https://github.com/hashicorp/terraform/pull/28634#issuecomment-845934989

I have seen the drifting on `aws_efs_file_system.size_in_bytes` and `aws_db_instance.latest_restorable_time` even though these attributes have been added into the lifecycle ignore list

**Comment by twbecker** [comment]
Apologies but I don't have a configuration I can share at the moment. Based on your response I upgraded the AWS provider to the latest version (3.42.0) and actually got some plan output for what it considered drift - once. But when I re-ran to save the output, it disappeared again (I could have sworn I did not apply). So now I'm on the newest provider version but back to where I started.

**Comment by jbardin** [comment]
Thanks @twbecker. Do you recall what resource caused the temporary diff? That may provide enough of a clue to confirm which behavior we're seeing.

**Comment by twbecker** [comment]
I believe it was something like `tags` on `aws_ebs_volume` going from absent to `{}` and also `capacity_reservation_preference` on `aws_instance`.  Unfortunately I lost the output so can't confirm :/

**Comment by zswanson** [comment]
I was seeing it with `aws_iam_role_policy`, which adds an inline policy to an existing role. Same as what twbecker is experiencing - the plan kept showing this iam policy as 'changing' and seemed to imply something had changed outside of terraform (which it had not, I'd created the resources only moments before), and kept wanting to remove/add the same resource. I then did a `refresh` and that at least went away but I still see all the notifications about drift.

**Comment by apparentlymart** [comment]
Hi all,

I agree with @leonsmith that we should keep these two ideas distinct:

* This issue is about the bug that there is an inconsistency between what low-level Terraform considers to be "a detected change" and what differences Terraform's UI is able to present to the user. We should make sure those two agree enough that Terraform will either produce a useful explanation of what's changed in all cases or not report a change at all.
* There also apparently a feature request to be able to turn off this mechanism altogether. While we typically avoid having lots of switches and knobs for customizing Terraform's output, we certainly can discuss the use-cases for that to see if making that customizable would be impactful enough to justify the maintenence cost of having another codepath. If you'd like to discuss a use-case for that, please open a new [feature request](https://github.com/hashicorp/terraform/issues/new?assignees=&labels=enhancement%2C+new&template=feature_request.md) to discuss that use-case. (It's important to share the use-case and not just your idea for addressing it, because we can often find different ways to solve a problem that have better costs and tradeoffs.)

Thanks!

**Comment by szEvEz** [comment]
Just wanted to provide an example to outline the issue and help a bit, the following is a good starting point - https://github.com/terraform-aws-modules/terraform-aws-rds/tree/master/examples/complete-postgres.

Make sure to set a value for backup retention period, e.g.
`backup_retention_period = 7`

Immediately after applying, the following diff is displayed

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.db.module.db_instance.aws_db_instance.this[0] has been changed
  ~ resource "aws_db_instance" "this" {
        id                                    = "complete-postgresql"
        name                                  = "completePostgresql"
      + security_group_names                  = []
        tags                                  = {
            "Environment" = "dev"
            "Name"        = "complete-postgresql"
            "Owner"       = "user"
        }
        # (46 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these
changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only
```

After waiting for ~5 minutes for the backup to kick in, recurring diffs like the following kick in

```
Note: Objects have changed outside of Terraform                                                                                                                                              
                                                                                                                                                                                             
Terraform detected the following changes made outside of Terraform since the last "terraform apply":                                                                                         
                                                                                                                                                                                             
  # module.db.module.db_instance.aws_db_instance.this[0] has been changed                                                                                                                    
  ~ resource "aws_db_instance" "this" {                                                                                                                                                                                                                                                                                    
        id                                    = "complete-postgresql"                                                                                                                        
      ~ latest_restorable_time                = "0001-01-01T00:00:00Z" -> "2021-05-23T11:09:14Z"                                                                                             
        name                                  = "completePostgresql"                                                                                                                         
        tags                                  = {                                                                                                                                            
            "Environment" = "dev"                                                                                                                                                            
            "Name"        = "complete-postgresql"                                                                                                                                            
            "Owner"       = "user"                                                                                                                                                           
        }                                                                                                                                                                                    
        # (45 unchanged attributes hidden)                                                                                                                                                   
                                                                                                                                                                                             
        # (1 unchanged block hidden)                                                                                                                                                         
    }                                                                                                                                                                                        
                                                                                                                                                                                             
Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these   
changes.                                                                                                                                                                                     
                                                                                                                                                                                             
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
                                                                                                                                                                                             
No changes. Your infrastructure matches the configuration.
```

This also occurs for all resources which I decided to ignore via the lifecycle -> ignore_changes.

This makes the plan output hugely verbose and in some cases very unuseable for me. As previously mentioned, I guess this is just bug, if it is wanted behavior, I highly suggest providing a configuration option for disabling this.

**Comment by simlu** [comment]
Any idea when this fix is going to go out?

**Comment by maustin-iwm** [comment]
Running the latest 0.15.5 I am still seeing the notice.

**Comment by jbardin** [comment]
Hi @tomislater, This issue was about getting the notification with _no_ changes to the resource being displayed. Since the provider has reported changed for your resource, the output is expected.

**Comment by tomislater** [comment]
Hmm, but after applying `terraform apply -refresh-only` nothing changes. I still get the same output again and again. And, as you can see, there is no change at all. Just some items in a list which were at the top now are at the bottom.

**Comment by jbardin** [comment]
@tomislater, that is still a change returned by the provider, and the order of a list of values may be significant in many situations. The second message indicates that the plan resulted in no changes, so either your configuration is ignoring the `policy` changes, or the provider is.

**Comment by tomislater** [comment]
@jbardin thank you for the info. Is there any solution to conceal these "changes"? It is very confusing. There is a change, but there is no change at all. I mean, before `0.15.4` it worked as expected, but now we have a lot of such messages in logs. Even if we `apply` changes, we still get these messages again.

Do you suggest that there is something wrong with `aws` provider?

Here is an example; I created a repo in AWS ECR (via `terraform apply`). And, after that I run `terraform plan` (just for checking, but it might be `terraform apply` again as well of course:
```
...

# module.ecr-devops.aws_ecr_repository.ecr["my-repo"] has been changed
~ resource "aws_ecr_repository" "ecr" {
  id                   = "my-repo"
  name                 = "my-repo"
  + tags                 = {}
  # (5 unchanged attributes hidden)
  # (2 unchanged blocks hidden)
}

...

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
─────────────────────────────────────────────────────────────────────────────
No changes. Your infrastructure matches the configuration.
Your configuration already matches the changes detected above. If you'd like
to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only
```

Looks, like `terraform` has not created `tags` for this resource? And wants to create it now, but... `apply` won't change anything, because there is no changes? So... there are changes or not? It is very very confusing for me.

**Comment by jbardin** [comment]
The "Objects have changed outside of Terraform" message is only showing the difference between what the provider stored in the state, and what the provider is indicating as the current state, nothing more. The configuration is only taken into account for the actual plan output, which results in 0 changes for your example.

If the provider is unexpectedly changing values where it shouldn't, then it is an issue with the provider.

It does turn out that some providers are noisier in this regard than others, and we are working on ideas to quiet the output while not hiding possibly significant changes. You can follow along with the open issue here: #28803
