### ISSUE TITLE
aws_sqs_queue Deduplication Scope support

### ISSUE THREAD

**Issue by slichtenthal** [hashicorp/terraform#28780]
### Current Terraform Version
```
0.15.4
```

### Attempted Solutions
There doesn't seem to be a way to add this value currently to attempt a fix

### Proposal
I would add the following optional property to resource aws_sqs_queue:
**deduplication_scope**
By default it will be set to "queue" with the ability to override to "message_group".

Another option would be to have it be:
**deduplication_scope_queue** with a default value of true and if set to false, set to message_group.  While this is easier to understand the possible values (true/false), it would prevent scaling in case AWS adds a third option.

### References
None that I saw
-->

**Comment by jbardin** [comment]
Hello,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
