### ISSUE TITLE
Data block "Query returned no results" should return more information

### ISSUE THREAD

**Issue by archoversight** [hashicorp/terraform#28799]
This is re-opening ticket https://github.com/hashicorp/terraform/issues/27283 which was locked and thus I can't comment on.

Supposedly the fix for that was back ported and released in the newest version of 0.14, which after the date that was mentioned was 0.14.11, which is what I am using

### Terraform Version
```
Terraform v0.14.11
```

### Expected Behavior

```
Error: Your query returned no results. Please change your search criteria and try again.

  on ../../../../modules/aws-instance/instance.tf line 9, in data "aws_ami" "instance":
   9: data "aws_ami" "instance" {

```

Would include a bit more information what exactly it is that it failed to find, what was the search criteria. This is deep inside a module that is being called from deep within the code base. It is impossible, other than guess work, to figure out where the issue actually lies. Trying to figure out where in the code this is being called (over 100+ locations) makes it impossible to figure out what exactly is wrong.

### Actual Behavior
```
Error: Your query returned no results. Please change your search criteria and try again.

  on ../../../../modules/aws-instance/instance.tf line 9, in data "aws_ami" "instance":
   9: data "aws_ami" "instance" {

```

**Comment by jbardin** [comment]
Hi @archoversight,

The current version of Terraform will return a little more information here, which may include some more context about the error, including the individual instance address. If there is some information about the query itself which needs to be known, that would have to be added to the error by the provider itself, as terraform has no insight into what the data source configuration actually represents.

Thanks!
