### ISSUE TITLE
terraform login to remote backend not working

### ISSUE THREAD

**Issue by surfd4wg** [hashicorp/terraform#28794]
### Terraform Version
```
$terraform -version
Terraform v0.15.4
on linux_amd64
```

### Terraform Configuration Files
```
https://github.com/surfd4wg/tf_remote_login_bugs
```

### Debug Output
```
https://github.com/surfd4wg/tf_remote_login_bugs/blob/main/error_login_DEBUG
```

### Crash Output
```
https://github.com/surfd4wg/tf_remote_login_bugs/blob/main/error_login_DEBUG
```

### Expected Behavior
```
Should prompt for the API key, without error messages.
```

### Actual Behavior
```
  Enter a value: /usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'https://app.terraform.io/app/settings/tokens?source=terraform-login'
```

### Steps to Reproduce
```
Follow the tutorial, https://learn.hashicorp.com/tutorials/terraform/infrastructure-as-code.
then, when you get to this section, 
https://learn.hashicorp.com/tutorials/terraform/aws-remote
it fails...
```

### Additional Context
```
N/A
```

### References
```
N/A
```

**Comment by alisdair** [comment]
`terraform login` uses [pkg/browser](https://github.com/pkg/browser) to open the URL given, which on Unix-like systems delegates to `xdg-open`. It looks like your local system is somehow not set up to open a web browser, which would prevent you from visiting the tokens page on Terraform Cloud/Enterprise to create a token.

You should be able to override this by setting the `BROWSER` environment variable to your web browser of choice—or even perhaps just `echo` to print the URL to the terminal.

I don't think that there's much that Terraform can do to cope better with a situation where there is no web browser available, so I'm going to close this issue for now.
