### ISSUE TITLE
Is it possible to create an Aurora DB through terraform

### ISSUE THREAD

**Issue by tayzlor** [hashicorp/terraform#2882]
I gather from here this might *not* be possible - http://docs.aws.amazon.com/AmazonRDS/latest/CommandLineReference/CLIReference-cmd-CreateDBInstance.html (since theres no mention of aurora)

I'm trying with the following configuration -

```
resource "aws_db_instance" "aurora" {
    identifier = "testdb-rds"
    allocated_storage = 100
    engine = "aurora"
    engine_version = "5.6.10a"
    instance_class = "db.r3.large"
    name = "test"
    username = "test"
    password = "test1234"
    db_subnet_group_name = "${aws_db_subnet_group.aurora.name}"
    vpc_security_group_ids   = ["${aws_security_group.default.id}"]
}

resource "aws_db_subnet_group" "aurora" {
    name = "aurora"
    description = "Our aurora group of subnets"
    subnet_ids = ["${aws_subnet.private.0.id}"]
}
```

I have a private VPC subnet and security group set up elsewhere in other .tf files.

Which is giving the following error -

```
* Error creating DB Instance: InvalidParameterCombination: Standalone DB Instances are not supported for the specified engine
	status code: 400, request id: [0c8d3c80-35ea-11e5-8612-7714ac2ff77e]
```

If I change it to create a default RDS mysql DB it works - 

```
resource "aws_db_instance" "aurora" {
    identifier = "mydb-rds"
    allocated_storage = 10
    engine = "mysql"
    engine_version = "5.6.23"
    instance_class = "db.t1.micro"
    name = "test"
    username = "test"
    password = "test1234"
    db_subnet_group_name = "${aws_db_subnet_group.aurora.name}"
    vpc_security_group_ids   = ["${aws_security_group.default.id}"]
}
```

**Comment by stack72** [comment]
@tayzlor I don't even believe there is a cloudformation setup for it yet as the public API will be released later

**Comment by tayzlor** [comment]
cool, thought this might be the case, thanks!

**Comment by stack72** [comment]
@tayzlor btw, I immediately looked for the APIs as well yesterday when it was released so you are certainly on the ball :)

**Comment by catsby** [comment]
Correct, not available yet :smile: 
I have an issue open on the SDK if you want to watch https://github.com/aws/aws-sdk-go/issues/328

Aurora is on my short list once it's available

**Comment by catsby** [comment]
Aurora just came out in [release v0.7.1](https://github.com/aws/aws-sdk-go/releases/tag/v0.7.1), I plan on starting on it tomorrow

**Comment by dalehamel** [comment]
@catsby did you make any progress on aurora? We're looking at using it

**Comment by catsby** [comment]
Yup see https://github.com/hashicorp/terraform/pull/2935
