### ISSUE TITLE
How to prevent Azure  Cosmos connection string from being stored in the state file?

### ISSUE THREAD

**Issue by sdg002** [hashicorp/terraform#28835]
### Current Terraform Version

```
0.13
...
```

### Proposal

Terraform should easily allow omitting fields from being persisted to the storage state.

### References

We are on Terraform version 0.13 with Azure back end.  We are using Azure KeyVault for storing all confidential information like keys and connection strings.

![image](https://user-images.githubusercontent.com/20245330/119996976-24b26400-bfc7-11eb-9e28-b4aa1c4bd6c5.png)

In the interest of overall simplification and reduction in surface area of attack, we would like to avoid storing Cosmos connection string in the Terraform state file. 

Our Terraform storage account is secure.  Nevertheless, we want to avoid awkward questions from Auditors.  Azure KeyVault is our only source of truth when it comes to confidential information.

Any suggestions?

Thank you,
Sau

**Comment by jbardin** [comment]
Hi @sdg002,

We are tracking possible features for dealing with sensitive values in state in #9556 and #516. There are also many discussion in the linked issue with more detail about various aspects of the problem space, like https://github.com/hashicorp/terraform/issues/28263#issuecomment-824051947. 

In short, the entire state is currently expected to be treated as a sensitive artifact, and there is no way to current exclude or encrypt individual fields. 

Thanks!
