### ISSUE TITLE
Escape bug when creating compound alarms in AWS Cloudwatch

### ISSUE THREAD

**Issue by burasuzu** [hashicorp/terraform#28830]
When creating compound alarms in AWS, if you reference an alarm with "()" in the AlarmRule, a validation error will occur.
If the referenced alarm contains "()", it must be escaped appropriately.

**Comment by jbardin** [comment]
Hi @burasuzu,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
