### ISSUE TITLE
Terraform crash when running aws_macie2_member from Macie2 module

### ISSUE THREAD

**Issue by anasillo** [hashicorp/terraform#28841]
### Terraform Version

```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.42.0
```

### Terraform Configuration Files

```terraform
resource "aws_macie2_account" "example" {
  finding_publishing_frequency = "ONE_HOUR"
  status                       = "ENABLED"
}

resource "aws_macie2_organization_admin_account" "example" {
  admin_account_id = var.security_account_id
  depends_on       = [aws_macie2_account.example]
}

resource "aws_macie2_member" "example" {
  for_each                              = var.aws_accounts
  account_id                            = each.value.account_id
  email                                 = each.value.email
  status                                = "ENABLED"
  invite                                = true
  invitation_message                    = "Joining Macie"
  invitation_disable_email_notification = true
}

resource "aws_macie2_invitation_accepter" "macie_admin" {
  administrator_account_id = var.security_account_id
  depends_on               = [aws_macie2_member.example]
}
```

### Crash Output
 https://gist.github.com/anasillo/5f8e4245989461ae78a0b6d1bd3d5721

### Expected Behavior
 The Macie module should enable all members without crashing.

### Actual Behavior
 The module enables all members but randomly (some members join correctly, others just don't)

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context
 No

### References
 Didn't see anything related so far.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by anasillo** [comment]
Thank you James, will let the new issue here: https://github.com/hashicorp/terraform-provider-aws/issues/19611

**Comment by anasillo** [comment]
Thank you James, will let the new issue here for anyone who may be interested in: hashicorp/terraform-provider-aws#19611
