### ISSUE TITLE
azuread_application... required_resource_access failing with "Role" added

### ISSUE THREAD

**Issue by waynejnicklin** [hashicorp/terraform#28848]
My azuread_application works fine with just "Scope" types for graph api, but when I add a "Role" type for an app, it fails with the error below. I checked the plan file and the IDs I'm using are correct. The terraform is here. I am not specifying the "public_client" flag as I saw that issue raised previously and removed it. I'm using 1.5.0 of AzureAD provider, and 0.15.3 of Terraform.

resource "azuread_application" "tagetik" {
    display_name               = lower("gfp-${var.environment_name}-tagetik-wjntest")
    type                       = "native"
    reply_urls                 = ["https://tagetik-dev.gfp.swissre.com/tagetikcpm"]
    available_to_other_tenants = false
    oauth2_allow_implicit_flow = true
    owners                     = [for value in data.azuread_user.ad_app_owners: value.object_id]
    required_resource_access {
        resource_app_id = local.graph
        resource_access {
            id   = local.graph_email
            type = "Scope"
        }
        resource_access {
            id   = local.graph_open_id
            type = "Scope"
        }
        resource_access {
            id   = local.graph_profile
            type = "Scope"
        }
        resource_access {
            id   = local.graph_user_read
            type = "Scope"
        }
    }
    required_resource_access {
        resource_app_id = data.azuread_application.reporting_cycle_service.application_id
        resource_access {
            id   = local.rcs_submission_state_read
            type = "Role"
        }
    }
}

Error: Updating Application with object ID "2915be5b-e696-4780-8b76-380d79ecb7ce"
│ 
│   with azuread_application.tagetik,
│   on tagetik_service_principal.tf line 1, in resource "azuread_application" "tagetik":
│    1: resource "azuread_application" "tagetik" {
│ 
│ graphrbac.ApplicationsClient#Patch: Failure responding to request:
│ StatusCode=400 -- Original Error: autorest/azure: Service returned an
│ error. Status=400 Code="Unknown" Message="Unknown service error"
│ Details=[{"odata.error":{"code":"Request_BadRequest","date":"2021-05-31T09:18:49","message":{"lang":"en","value":"Property
│ requiredResourceAccess.resourceAccess is
│ invalid."},"requestId":"bb3fd667-5721-47df-9d26-45c50dacf772","values":[{"item":"PropertyName","value":"requiredResourceAccess.resourceAccess"},{"item":"PropertyErrorCode","value":"GenericError"}]}}]

**Comment by jbardin** [comment]
Hi @waynejnicklin,

This appears to be an issue with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by waynejnicklin** [comment]
OK thanks I'll raise the issue on there.
