### ISSUE TITLE
RDS: Terraform does not accept "oemagent" Oracle log type as a value for enabled_cloudwatch_logs_exports

### ISSUE THREAD

**Issue by michal-kubicki** [hashicorp/terraform#28843]
### Terraform Version

```
Terraform v0.15.4
```

### Expected Behavior

When I create an RDS Oracle `aws_db_instance` resource and set: `enabled_cloudwatch_logs_exports: ["alert", "audit", "listener", "trace", "oemagent"]` I expect all the listed logs to be exported to CloudWatch. "[oemagent](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html)" is a valid log type for Oracle.

### Actual Behavior

Terraform stops with the following error:

`Error: expected enabled_cloudwatch_logs_exports.3 to be one of [agent alert audit error general listener slowquery trace postgresql upgrade], got oemagent`

### Steps to Reproduce

Try to create an RDS Oracle instance and set `enabled_cloudwatch_logs_exports: ["alert", "audit", "listener", "trace", "oemagent"]`

**Comment by circa10a** [comment]
This should go to the aws provider repo, not the terraform core repo
https://github.com/hashicorp/terraform-provider-aws

**Comment by jbardin** [comment]
Hello,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
