### ISSUE TITLE
terraform force-unlock: Failed to load state:remote workspace Terraform version "0.13.5" does not match local Terraform version "0.15.4"

### ISSUE THREAD

**Issue by ecerulm** [hashicorp/terraform#28853]
### Terraform Version

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/helm v2.1.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

`terraform force-unlock xxxx` should just unlock the state. Or at least tell me exactly which remote state is the offending one as I can think of several

* The `backend "remote"` that hold the state of this terraform configuration
* Any of the 5  `data "terraform_remote_state" "xxx" ` that are used in this terraform configuration (I checked in Terraform Cloud and they are have `  "terraform_version": "0.15.4",`

### Actual Behavior

`terraform force-unlock xxxxxx` seems to remove the lock, but immediatelly after terraform fails with

     Failed to load state: Remote workspace Terraform version "0.13.5" does not match local Terraform version "0.15.4"

leaving the state locked again (with a new lock ID)

### Steps to Reproduce

I'm not sure how I landed in this state 

### Additional Context

I tried to 

    terraform apply -refresh-only -lock=false
    terraform force-unlock 85f52642-4dc4-379f-8031-a286b7db6aa9

but I still get the `Failed to load state: Remote workspace Terraform version "0.13.5" does not match local Terraform version "0.15.4"

At this point all the remote workspaces referenced in the terraform configuration are already on 0.15.4 (both the `backend "remote"` and the 5 `data "terraform_remote_state "xxx"`) , I've checke on Terraform Cloud and all of them have `"terraform_version": "0.15.4",`

**Comment by ecerulm** [comment]
I tried 

```
terraform destroy -lock=false # Destroy complete! Resources: 9 destroyed
terraform plan -out latest.tfplan # Error: Error acquiring the state lock
terraform force-unlock e1adafcd-a7f2-d6d0-95ef-055b3b92e3cd
Failed to load state: Remote workspace Terraform version "0.13.5" does not match local Terraform version "0.15.4"
```

**Comment by ecerulm** [comment]
I deleted the workspace from terraform cloud (the `backend "remote"`) 
and 

```
terraform init
# change execution plan to local in terraform cloud
terraform plan # now works
```

So well, I could not wait and I managed to circumvent the problem since I destroyed everything first and then deleted the remote workspace from terraform cloud. 

But I guess this still needs to be looked into .

**Comment by ecerulm** [comment]
After googling more on this I believe that most likely the remote workspace in Terraform Cloud was locked to 0.13.5 (I guess because at some point I did Terraform Cloud > workspace-xxx > Settings > General > Execution Mode: Remote > Terraform version 0.13.5 ) 

Most likely I could have just updated that in terraform cloud or used `terraform force-unlock -ignore-remote-version` as documented on https://www.terraform.io/docs/language/settings/backends/remote.html#command-line-arguments

But even then... should terraform leave the state  locked  in this case?  I believe not.

**Comment by ecerulm** [comment]
This happend to me again so and I think the correct procedure to get rid of this now is:

* Terraform Cloud > workspace-xxx > Settings > General > Execution Mode: Remote (change to Remote so that the terraform version dropdown box appears)
* Terraform Cloud > workspace-xxx > Settings > General > Execution Mode: Remote > Terraform version xxxx
* Terraform Cloud > workspace-xxx > Settings > General > Execution Mode: Local (change back to local execution mode)
* Delete  the lock / remove the lock with  `terraform force-unlock 'orgname/workspaceshortname'`(note that the LOCKID is **NOT**. a  UUID )

**Comment by acdha** [comment]
> Most likely I could have just updated that in terraform cloud or used `terraform force-unlock -ignore-remote-version` as documented on https://www.terraform.io/docs/language/settings/backends/remote.html#command-line-arguments

In case anyone else is wondering, `-ignore-remote-version` was removed at some point.
