### ISSUE TITLE
Add setting for auto apply for run triggers

### ISSUE THREAD

**Issue by drewhemm** [hashicorp/terraform#28850]
This applies to Terraform Cloud and Enterprise. 

### Current Terraform Version

```
v0.14.11 (issue affects all versions)
```

### Use-cases

At present, it is not possible to have a workspace auto plan and apply due to run triggers from another workspace:

https://www.terraform.io/docs/cloud/workspaces/settings.html#auto-apply-and-manual-apply

```
Plans queued due to run triggers from another workspace must always be manually applied. 
```
I believe this should be a config option so that operators can choose to have triggered workspaces automatically 
plan and apply, leaving the decision-making and review steps to version control flow. 

### Attempted Solutions

I am trying to find hacky ways to get around this limitation. 

### Proposal

Code change to workspace a >> workspace b retrieves info from workspace a via remote state >>workspace b is configured to plan whenever workspace a changes >> if plan is successful, auto apply

**Comment by chrisarcand** [comment]
Hi!

Requests for the Terraform Cloud platform aren't organized on this issue tracker for Terraform CLI, so I went ahead and added this request to Terraform Cloud's internal tracker, which you can submit to via the support portal on the HashiCorp website; thanks for opening this!

**Comment by drewhemm** [comment]
Adding a bit more detail on the use case for this feature request...

This is a large-scale Terraform Enterprise setup. We have a number of 'base' modules that are referenced in almost every other workspace, of which there are dozens. The base modules are used for things such as compliance and access control etc.

When a change is made in the base module, plans are triggered for all the other workspaces. It is then necessary to go into each one and manually click confirm. In addition to our gitops workflow, which leverages the access and peer-review settings for the repository, we have a redundant clickops workflow that is highly tedious and repetitive, one which makes it impossible to automate the rollout of changes purely from a code change.

**Comment by drewhemm** [comment]
> Hi!
> 
> Requests for the Terraform Cloud platform aren't organized on this issue tracker for Terraform CLI, so I went ahead and added this request to Terraform Cloud's internal tracker, which you can submit to via the support portal on the HashiCorp website; thanks for opening this!

Thanks, I couldn't see where to open the issue. (I was writing the above reply when you closed the issue).
