### ISSUE TITLE
Error looking up workspace with multiple environments when prefix contains a digit/number

### ISSUE THREAD

**Issue by reixd** [hashicorp/terraform#28858]
### Terraform Version

* 0.14.11
* 0.15.4

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.14.11, < 0.15.0"

  backend "remote" {
    hostname = "app.terraform.io"
    organization = "myorg"
    workspaces {
      prefix = "cp-10-dns-"
    }
  }

}
```

### Debug Output

```
$ terraform init
Initializing modules...

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.



Error: Error looking up workspace

Workspace read failed: invalid value for workspace
```

### Expected Behavior

Migrate the local state per workspace to the corresponding TFC workspace, with the namespace name following this scheme:

`${NAMESPACE}-${MODULE_INDEX}-${MODULE_NAME}-${ENVIRONMENT}`

Example:
```
cp-10-dns-dev
cp-15-network-prod
cp-20-eks-staging
```

### Actual Behavior

Following the official docs (https://www.terraform.io/docs/cloud/migrate/workspaces.html) to migrate current local workspaces (dev, staging, prod) to TFC using the recommended `workspaces.prefix` scheme, I get an error, when the TFC workspace name contains an digit. 
Even if digits are allowed character (https://www.terraform.io/docs/cloud/workspaces/naming.html).

Removing the digit from the TFC workspace name seems to solves this issue.

In addition, when using `worspaces.name` with the exact string works.

### Steps to Reproduce

1. Fork this repo https://github.com/hashicorp/tfc-guide-example
2. Login to TFC
3. Create 3 workspaces as VCS and name them using this scheme: `cp-42-tfc-guide-example-${environment}`
4. Clone the repo locally
5. Update the backend remote configuration with prefix
6.  perform `terraform init` to sync state

```
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "my-org"

    workspaces {
      prefix = "cp-42-tfc-guide-example-"
    }
  }
}
```

### References

- #28092

**Comment by alisdair** [comment]
Hi @reixd, thanks for reporting this. I think the cause here is slightly different than your description. My attempts to reproduce indicate that initializing using the workspaces `prefix` argument (vs `name`) is not working, regardless of whether or not the prefix contains a number. I'll edit the title accordingly.

I think the cause is that the remote workspace version check during state migration is trying to read a workspace without a name. From a trace log:

```
2021-06-02T14:00:44.298-0400 [TRACE] backendMigrateState: need to migrate from "local" to "remote" backend config
2021-06-02T14:00:44.442-0400 [TRACE] backend/remote: looking up workspace for alisdair-v2/
╷
│ Error: Error looking up workspace
│
│ Workspace read failed: invalid value for workspace
╵
```

**Comment by reixd** [comment]
Hello @alisdair,

that was a quick response. Thank you!

> I think the cause is that the remote workspace version check during state migration is trying to read a workspace without a name. From a trace log:

Interesting.... Nevertheless I'm glad I could help ;-)
