### ISSUE TITLE
Terraform aws provider - Resource aws_autoscaling_attachment

### ISSUE THREAD

**Issue by jdoshi110** [hashicorp/terraform#28869]
### Terraform Version

terraform version 0.14.11
...
```

### Terraform Configuration Files
<!--
resource "aws_autoscaling_attachment" "tg_attach" {
    autoscaling_group_name = var.asg_id 
    alb_target_group_arn   = var.tg_arn
    }
-->

```terraform
...
```

**Comment by jbardin** [comment]
Hi @jdoshi110,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If this is a question about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
