### ISSUE TITLE
 Error: Error creating OpenStack compute client: json: cannot unmarshal array into Go struct field response.versions of type utils.versionsResp

### ISSUE THREAD

**Issue by rahulsharma01111986** [hashicorp/terraform#28875]
I am trying to create a openstack vm using terraform template. the main.tf file is given below:

# Define required providers
terraform {
required_version = ">= 0.14.0"
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 1.42.0"
    }
  }
}

# Configure the OpenStack Provider
provider "openstack" {
  user_name   = "----------------"
  tenant_name = "-------------------"
  password    = "-----------------------"
  auth_url    = "----------------------------"
  insecure = true
}

resource "openstack_compute_instance_v2" "vm"  {
  name            = "terraform01"
  image_id       = "7a1a9a9f-8e04-4e47-86ca-ae313cd0c67a"
  flavor_name      = "m1.2xlarge"
  key_pair        = "Jan2021"
  security_groups = ["default"]
  

  network {
    name = "vnet-app-dev"
  }
} 

After terraform apply i am getting the below error mesage:

Error: Error creating OpenStack compute client: json: cannot unmarshal array into Go struct field response.versions of type utils.versionsResp
│
│   with openstack_compute_instance_v2.vm,
│   on main.tf line 24, in resource "openstack_compute_instance_v2" "vm":
│   24: resource "openstack_compute_instance_v2" "vm"  {

**Comment by jbardin** [comment]
This appears to be an issue with the OpenStack provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues. If you have questions about Terraform or the OpenStack provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
