### ISSUE TITLE
Terraform keeps opening new terminal.

### ISSUE THREAD

**Issue by JosephCanete** [hashicorp/terraform#28873]
Whenever I use any terraform command it keeps opening new terminal/cmd/gitbash/powershell. This gives me a hard time to see what's the output.

Example:
terraform -v

Behavior: Open new cmd then closed immediately.
Expected: Output should be on the current terminal.

Thank you!

**Comment by alisdair** [comment]
That's confusing! There is no code in Terraform which has the ability to launch a new terminal on Windows. This sounds like you may have a script or other executable called `terraform` which is doing this.

From Powershell, what is the output of `Get-Command terraform`? And what is the contents of that path?

**Comment by JosephCanete** [comment]
@alisdair Hey the terraform itself is .exe right? I put that in certain location then mapped into my global variable as per installation guide. 

Application     terraform.exe                                      1.0.0.0    C:\Program Files\terraform\terraform.exe

That is the result of the command. 

The terraform works fine, when I do terraform -v it gives the version however it opens up new terminal then quickly disappear which isn't correct. It should run into my current terminal though...

**Comment by alisdair** [comment]
Huh! When I've previously seen this it has been due to a lack of privileges in the current cmd.exe/Powershell instance. Have you tried running Terraform from an administrator command prompt?

**Comment by JosephCanete** [comment]
cmd/powershell is running at administrator as well as the terraform file itself from properties.

**Comment by alisdair** [comment]
I'm afraid I can't reproduce this with Terraform 0.15.5 on Windows 10: all my Terraform commands execute in the same Powershell instance. It seems unlikely that this is a bug in Terraform, and rather something specific to your Windows working environment. I'm not an expert Windows user so I can't really help there.

One thing to note is that your output for `Get-Command` differs from mine. The version number "1.0.0.0" is not what Terraform's signed binaries report ("0.0.0.0"). Is it possible that this is not the official Terraform binary?

Finally, you may want to try [alternative installation methods](https://learn.hashicorp.com/tutorials/terraform/install-cli), such as using Chocolatey. Hope you can figure it out!

**Comment by JosephCanete** [comment]
Hey its my first time hearing the choco package manager, thank you so much. it is now working as expected 💯 👍 🥇
