### ISSUE TITLE
azurerm_role_assignment Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by isaacdan** [hashicorp/terraform#28888]
Team,
My transformer pipeline is failing while creating assignment to a managed identity which was working fine till 04/Jun/2021

I have hard coded the principal_id just to double check yet no luck.  Any help on this please?

resource "azurerm_role_assignment" "appgw_role" {
  depends_on           = [azurerm_user_assigned_identity.appgw_identity]
  count                = var.ext_cert == "letsencrypt"  ? 0 : 1
  scope                = azurerm_user_assigned_identity.appgw_identity[0].id
  role_definition_name = "Managed Identity Operator"
  principal_id         = "${var.object_id}"
#  principal_id         = data.azuread_service_principal.aks_obj_identity.object_id
#  principal_id        = "${data.external.aks_objid.result.objid}"
}

Error message 

Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.apcfg_kv_db.azurerm_role_assignment.appgw_role[0], provider
│ "module.apcfg_kv_db.provider[\"registry.terraform.io/hashicorp/azurerm\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

**Comment by jbardin** [comment]
Hi @isaacdan,

While you have not provided all the requested information, this does appear to be an issue with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
