### ISSUE TITLE
security group error reporting

### ISSUE THREAD

**Issue by SamBarker** [hashicorp/terraform#2889]
I've just tried to setup a new environment using our terraform rules, however 1 of our 168 security group rules failed due to a typo in the type field. It would be really helpful if the error ```* Security Group Rule must be type 'ingress' or type 'egress'``` included the name of the offending rule.

**Comment by catsby** [comment]
Hey @SamBarker – something like this was added just a few days ago in #2815, and should go out in the next release. You can check it out now if you build from `master`. 

Hopefully you can take a look at that output and let me know if that is what you're looking for. 

Thanks!
