### ISSUE TITLE
Passing `null` value to a required variable doesn't throw an error

### ISSUE THREAD

**Issue by rishabh1403** [hashicorp/terraform#28894]
### Issue
According to terraform docs about `null` type on https://www.terraform.io/docs/language/expressions/types.html#null
> Terraform behaves as though you had completely omitted it — it will use the argument's default value if it has one, or raise an error if the argument is mandatory.

However, I am able to pass `null` for a required variable and `terraform` doesn't throw an error.

### Terraform Version
```
v0.14.4
```

### Terraform Configuration Files
I created an `ECR` module with two files `main.tf` and `variables.tf`. The intent here is to enable image scanning and send the results to SNS only when the environment is `production` and `sns_topic_arn` exists.

```terraform
resource "aws_ecr_repository" "main" {
  name                 = "${var.image_prefix}/${var.name}-${var.environment}"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = var.is_production_environment
  }

  tags = {
    Environment = var.environment
  }
}

resource "aws_cloudwatch_event_rule" "event_rule" {
  count         = var.is_production_environment && var.sns_topic_arn != null ? 1 : 0
  name          = "${var.name}-ecr-scan-${var.environment}"
  description   = "A CloudWatch Event Rule that triggers when each ECR vulnerability image scan is completed."
  is_enabled    = true
  event_pattern = <<PATTERN
{
  "detail-type": [
    "ECR Image Scan"
  ],
  "source": [
    "aws.ecr"
  ]
}
PATTERN

  tags = {
    Environment = var.environment
  }
}

resource "aws_cloudwatch_event_target" "target_for_event_rule" {
  count = var.is_production_environment && var.sns_topic_arn != null ? 1 : 0
  rule  = aws_cloudwatch_event_rule.event_rule[0].name
  arn   = var.sns_topic_arn
}

data "aws_iam_policy_document" "sns_topic_policy" {
  statement {
    sid       = "Allow CloudwatchEvents"
    actions   = ["sns:Publish"]
    resources = var.sns_topic_arn != null ? [var.sns_topic_arn] : null

    principals {
      type        = "Service"
      identifiers = ["events.amazonaws.com"]
    }
  }
}

resource "aws_sns_topic_policy" "policy_for_sns_topic" {
  count  = var.is_production_environment && var.sns_topic_arn != null ? 1 : 0
  arn    = var.sns_topic_arn
  policy = data.aws_iam_policy_document.sns_topic_policy.json
}

output "aws_ecr_repository_url" {
  value = aws_ecr_repository.main.repository_url
}

```

```terraform
variable "sns_topic_arn" {
  description = "the arn for sns notification to slack"
}
... other variables
```
In another file i am initializing this module with the following 

```terraform
module "ecr_app" {
  source                    = "./ecr"
  name                      = "app"
  environment               = var.environment
  sns_topic_arn             = null
  is_production_environment = var.is_production_environment
}
```
I expect this to throw an error since I am passing `null` for a required variable i.e. `sns_topic_arn` according to the docs. But this setup doesn't throw an error on `init`, `plan` or `apply` step. It even produces the required behaviour i.e. `SNS` topic is not created when we pass `null` and is created when we pass a valid `arn`

### Expected Behavior
It should throw an error because we are passing `null` value to a required variable.

### Actual Behavior
The `plan` and `apply` stage runs without errors.

**Comment by jbardin** [comment]
Thanks @rishabh1403, Duplicate of #24142
