### ISSUE TITLE
User and Groups creation in Azure Active Directory without over riding the existing users and groups

### ISSUE THREAD

**Issue by jhansinaidu** [hashicorp/terraform#28904]
<!--
Hi there,

### Use-cases
Hi Team, We created a IAM feature using terraform for provisioning users and groups in Azure Active Directory.

So when ever we have a request to provision new user we use the Input.tfvars.json template to create a user.

When Using terraform state file, as we know state checks for any changes made from previous file to the latest one and it updates the infrastructure...This is causing an issue by deleting the existing users and groups in the AAD which is not ideal. As we have have "N" numbers of users and groups 

I would like to know if there is any work around for this, or is it in your roadmap to implement this feature in the future.

**Comment by jbardin** [comment]
Hi @jhansinaidu,

It seems you forgot to add the information in into the issue template, though it looks to be to be an issue with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by manicminer** [comment]
Hi @jhansinaidu, just to clarify the issue most likely wants raising in the [AzureAD provider](https://github.com/hashicorp/terraform-provider-azuread) (rather than AzureRM) if it pertains to Azure Active Directory as per this issue title. Thanks!
