### ISSUE TITLE
TF_X_CONCISE_DIFF not working

### ISSUE THREAD

**Issue by caphrim007** [hashicorp/terraform#28906]
The code appears to still have this flag in it, but it appears impossible to use it. From another ticket,

```
Just came across this today for the first time after upgrading to Terraform v0.15.4 and it seems
to me that even the `TF_X_CONCISE_DIFF` env var might be deprecated, as it doesn't seem to
do anything...
```

_Originally posted by @soapergem in https://github.com/hashicorp/terraform/issues/27547#issuecomment-850932625_

I concur with the original author that the important aspect of being able to see the whole diff is that it provides context for the reader. Concise diff is not useful when an operator has no context around what is changing.

**Comment by jbardin** [comment]
Hi @caphrim007,

The environment variable you are referring to was to disable the concise diff experiment in version 0.14. That experiment has concluded, and the resulting diff renderer is now the default. I don't see that variable in the documentation any where, so I'm going to close this out.

Thanks

**Comment by burner1024** [comment]
Oh come on... what's with the rushing, did an environment variable ever hurt anyone?
What I'm supposed to do with this plan
```
  # module.cloudfront.aws_cloudfront_distribution.tfer--A3KCW00UAK6JKF will be updated in-place
  ~ resource "aws_cloudfront_distribution" "tfer--A3KCW00UAK6JKF" {
        id                             = "A3KCW00UAK6JKF"
        tags                           = {}
      + wait_for_deployment            = false
        # (17 unchanged attributes hidden)

      ~ ordered_cache_behavior {
          ~ min_ttl                = 0 -> 3600
            # (11 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (35 unchanged blocks hidden)
    }

```
Please add it back.

**Comment by jbardin** [comment]
@burner1024, just to clarify a couple things, the `TF_X_` only applies to experimental features, since there is no longer a concise diff experiment, the environment variable wouldn't apply to anything. The other point which I mentioned above, is that the concise diff renderer from the experiment is the default now, so enabling it would have no effect.

**Comment by smaslennikov** [comment]
@jbardin does that mean that it's not possible to have the full plan output in versions 0.15 and up, including v1?

**Comment by jbardin** [comment]
@smaslennikov, The current output should show all planned changes, so in essence it is the "full plan output", just in a more succent format.  if you want to see all the unchanged values in the plan, the json output via `terraform show -json planfile` contains all the detailed plan information in a stable format.
