### ISSUE TITLE
'terraform init' does not work on Mac OSX Big Sur

### ISSUE THREAD

**Issue by techempowers** [hashicorp/terraform#28917]
### Terraform Version
```
Terraform v1.0.0
on darwin_amd64
```

### Terraform Configuration Files

```

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.26"
    }
  }

  required_version = ">= 1.0.0"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "myTFResourceGroup"
  location = "westus2"
}
```

### Actual Behavior
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 2.26.0"...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/azurerm: could not connect to registry.terraform.io: Failed to request discovery document: Get "https://registry.terraform.io/.well-known/terraform.json":
│ net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### Steps to Reproduce

Run `terraform init` after a fresh install of terraform on mac osx Big Sur, using the above main.tf(content of which is pasted above)

**Comment by utsavgupta** [comment]
Works fine on my installation of Big Sur (11.2.3).

## Test details
* Downloaded terraform 1.0.0 from [here](https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_darwin_amd64.zip)
* Extracted terraform binary in the downloads folder.
* Ran `~/Downloads$ ./terraform --version`
* The above command returned Terraform v1.0.0
* Copied the above tf file into main.tf
* Ran `~/Downloads$ ./terraform init`
* Got the following output
```
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 2.26.0"...
- Installing hashicorp/azurerm v2.62.1...
- Installed hashicorp/azurerm v2.62.1 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

## Possible issues
The error looks like the terraform binary is not being able to reach https://registry.terraform.io. Could be an issue with network connectivity or proxy.

**Comment by jbardin** [comment]
Hi @utsavgupta

Sorry you are encountering this, though there is likely nothing specific about MacOS 11.4 (I think the majority of terraform development happens on Big Sur at the moment). Since this is likely a network configuration issue of some sort, I'm going to combine this with the duplicate #26532

Thanks!

**Comment by roslee3677** [comment]
26532

Pada Kha, 10 Jun 2021 20:49 James Bardin ***@***.***> menulis:

**Comment by roslee3677** [comment]
---------- Forwarded message ---------
Daripada: Roslee Sulaiman ***@***.***>
Date: Kha, 8 Jul 2021 08:03
Subject: Fwd:
To: ***@***.***>



---------- Forwarded message ---------
Daripada: Roslee Sulaiman ***@***.***>
Date: Kha, 8 Jul 2021 07:45
Subject: Fwd:
To: ***@***.***>



---------- Forwarded message ---------
Daripada: Roslee Sulaiman ***@***.***>
Date: Kha, 8 Jul 2021 07:44
Subject:
To: ***@***.***>
