### ISSUE TITLE
"Objects changed outside of Terraform" shown with wrong order in produced jsonencode array items

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/terraform#28911]
### Terraform Version

```
terraform version: 1.0.0
aws provider version: 3.44.0
```

### Terraform Configuration Files

```terraform
resource "aws_s3_bucket_policy" "policy" {
  bucket = var.bucket_name
  policy = <<-EOF
  {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Sid": "DelegateS3Access",
              "Effect": "Allow",
              "Principal": {
                  "AWS": [
                      "principal#1",
                      "principal#2",
                      "principal#3"
                  ]
              },
              "Action": [
                  ...
              ],
              "Resource": [
                  ...
              ]
          }
      ]
  }
  E0F
}
```

### Expected Behavior

Terraform should not show any diff at all on the "Objects changed outside of Terraform" section.

### Actual Behavior

Terraform thinks that something was changed outside terraform (which is not the case) and shows output such as:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.module-name.aws_s3_bucket_policy.policy[0] has been changed
  ~ resource "aws_s3_bucket_policy" "policy" {
        id     = "whatever"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = [
                                "principal#1",
                              - "principal#3",
                                "principal#2",
                              + "principal#3",
                            ]
                        }
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }
```

essentially thinking that the order of the items in the principal array has changed

### Steps to Reproduce

1. Use multiple principals in the S3 bucket json document.
1. Create the bucket policy
2. plan again and see the diff shown in the "Objects changed outside of Terraform" section

### Additional Context

Tried to edit the bucket policy manually by adding the array items in the same order as in terraform heredoc, then planned again, which showed no drift, even for bucket policies that I didn't modify, then planned again and all bucket policy drifts came back.

The bucket policy is generated via a module instantiation and the heredoc is passed to it as a string variable, but I suppose this implementation detail doesn't really matter here.

**Comment by jbardin** [comment]
Hi @dimisjim,

Thanks for filing the issue. The output that terraform is showing is exactly what the provider is returning to terraform. Terraform itself cannot determine if the order of the list is relevant to the provider or not, so since it's an ordered data structure it will always be seen as a change internally.

We have some ideas how to quiet the displayed information in some cases like these when the provider changes the data unexpectedly, but ultimately this discrepancy is being caused by the provider itself. 

Thanks!

**Comment by dimisjim** [comment]
@jbardin Would it make sense to open this very same issue in the provider repo?

**Comment by jbardin** [comment]
It probably wouldn't hurt, but I'm sure they're going to have a bunch to fix now that we are making any discrepancies more visible outside of the logs. Thanks!
