### ISSUE TITLE
Plugin failure

### ISSUE THREAD

**Issue by pmanvoj** [hashicorp/terraform#28931]
Traying to import existing connection to express route 
azurerm_virtual_network_gateway_connection.hub_egw_conn["conn1"]: Refreshing state... [id=***]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-azurerm_v2.61.0_x5.exe plugin: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5185c49]

goroutine 69 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network.resourceVirtualNetworkGatewayConnectionRead(0xc000dc0b60, 0x6041fa0, 0xc000de5200, 0x0, 0x0)   
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/network/virtual_network_gateway_connection_resource.go:386 +0x449
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000899040, 0xc000ad9130, 0x6041fa0, 0xc000de5200, 0xc000006cc0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:470 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00038d708, 0x6f2a850, 0xc0015839e0, 0xc001d683c0, 0xc00038d708, 0xc0015839e0, 0xc00135dba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:535 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x6524380, 0xc00038d708, 0x6f2a850, 0xc0015839e0, 0xc001d68360, 0x0, 0x6f2a850, 0xc0015839e0, 0xc000059500, 0x32e)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023ae00, 0x6f70898, 0xc00007f500, 0xc000312600, 0xc000f849c0, 0xa3357f0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00023ae00, 0x6f70898, 0xc00007f500, 0xc000312600, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000f0c6f0, 0xc00023ae00, 0x6f70898, 0xc00007f500, 0xc000312600)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-azurerm_v2.61.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jbardin** [comment]
This appears to be an issue with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
