### ISSUE TITLE
Timed-out waiting for Linode instance to reach status offline

### ISSUE THREAD

**Issue by DarkMristov** [hashicorp/terraform#28932]
Hi, I try to create linode instance from a private image via terraform+gitlab but the error `Error: timed-out waiting for Linode instance ************ to reach status offline: [002] Get "https://api.linode.com/v4/linode/instances/*********": context deadline exceeded` is occur.
When I use a `linode/ubuntu18.04` image no errors happen.

My private image was created from `linode/ubuntu18.04` and contains a few libs, packages, and tools. For example docker. 
I checked created instance on the Linode cloud panel and via API, and it has status `running`.
I can connect to the instance via ssh and looks like the image is fine. All libs and packages installed.

And no problem when I use digital ocean provider with private image, and same resource and image build.

### Terraform Version
```
Terraform v1.0.0
on linux_amd64

+ provider registry.terraform.io/digitalocean/digitalocean v2.0.0
+ provider registry.terraform.io/linode/linode v1.18.0

```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
    }
  }
}
resource "linode_instance" "resourcename" {
  image = "private/************"
  label = "labelforserver"
  group = "mygroup"
  region = "eu-west"
  type = "g6-standard-4"
  authorized_keys = [var.pub_key]
  root_pass = var.linode_root_pass

  connection {
    host = self.ip_address
    user = "root"
    type = "ssh"
    private_key = var.pvt_key
    timeout = "60m"
  }

  provisioner "remote-exec" {

    inline = [
     .....
    ]
  }
}
```

### Expected Behavior
Linode instance successfully created with private image and the remote-exec provision executed.

### Actual Behavior
Linode instance successfully created with the private image but terraform stops with error `Error: timed-out waiting for Linode instance ********* to reach status offline: [002] Get "https://api.linode.com/v4/linode/instances/********": context deadline exceeded` after running for 10 minutes with messages  `Still creating...`

### Steps to Reproduce
1) Create Linode instance with `linode/ubuntu18.04` image
2) Install to the linode instance docker and few libs.
3) Create from the linode instance image via Linode cloud panel.
4) Use terraform+gitlab to create a linode instance.

### Additional Context
I checked linode instance on private image and on  `linode/ubuntu18.04` and found that instance with private image have `"image": null,` in API response.
 API response for  `linode/ubuntu18.04`
 ```
 {
  "id": *****************,
  "label": "**********************",
  "group": "*************",
  "status": "running",
  "created": "2021-06-11T06:53:23",
  "updated": "2021-06-11T06:53:23",
  "type": "g6-standard-4",
  "ipv4": [
    "****************"
  ],
  "ipv6": "*********************************",
  "image": "linode/ubuntu18.04",
  "region": "eu-west",
  "specs": {
    "disk": 163840,
    "memory": 8192,
    "vcpus": 4,
    "gpus": 0,
    "transfer": 5000
  },
  "alerts": {
    "cpu": 360,
    "network_in": 10,
    "network_out": 10,
    "transfer_quota": 80,
    "io": 10000
  },
  "backups": {
    "enabled": false,
    "schedule": {
      "day": null,
      "window": null
    },
    "last_successful": null
  },
  "hypervisor": "kvm",
  "watchdog_enabled": true,
  "tags": []
}
 ```
  API response for private image
 ```
 {
  "id": *******,
  "label": "*********",
  "group": "*******",
  "status": "running",
  "created": "2021-06-11T06:30:02",
  "updated": "2021-06-11T06:30:02",
  "type": "g6-standard-4",
  "ipv4": [
    "********"
  ],
  "ipv6": "****************************************",
  "image": null,
  "region": "eu-west",
  "specs": {
    "disk": 163840,
    "memory": 8192,
    "vcpus": 4,
    "gpus": 0,
    "transfer": 5000
  },
  "alerts": {
    "cpu": 360,
    "network_in": 10,
    "network_out": 10,
    "transfer_quota": 80,
    "io": 10000
  },
  "backups": {
    "enabled": false,
    "schedule": {
      "day": null,
      "window": null
    },
    "last_successful": null
  },
  "hypervisor": "kvm",
  "watchdog_enabled": true,
  "tags": []
}
 ```

**Comment by jbardin** [comment]
Hi,

This appears to be an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in their GitHub project repository, linked from the provider's registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
