### ISSUE TITLE
Submodule using fileset with path.module as base path results in file not found errors for every file enumerated

### ISSUE THREAD

**Issue by PaulStanos** [hashicorp/terraform#28943]
When the `fileset` function is used in a submodule and the base path is set to `path.module`, the wildcard is applied and all files are enumerated as expected but an error is logged for every file stating it could not be found.

If the same files are loaded without `fileset` it works as expected. For example:

Works:
```terraform
data "local_file" "A" {
  filename = "${path.module}/A.txt"
}

data "local_file" "B" {
  filename = "${path.module}/B.txt"
}

data "local_file" "C" {
  filename = "${path.module}/C.txt"
}
```

Does not work:
```terraform
data "local_file" "TextFiles" {
  for_each = fileset(path.module, "*.txt")
  filename = each.value
}
```

### Terraform Version

```
Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
```

#### File structure

```
root
   | main.tf
   | SubModule
      | sub.tf
      | A.txt
      | B.txt
      | C.txt
```

#### main.tf

```terraform
module "SubModule" {
   source = "./SubModule"
}
```

#### sub.tf

```terraform
data "local_file" "TextFiles" {
  for_each = fileset(path.module, "*.txt")
  filename = each.value
}
```

### Debug Output

```
$ terraform apply
╷
│ Error: open A.txt: The system cannot find the file specified.
│
│   with module.SubModule.data.local_file.TextFiles["A.txt"],
│   on SubModule\sub.tf line 13, in data "local_file" "TextFiles":
│   13: data "local_file" "TextFiles" {
│
╵
╷
│ Error: open B.txt: The system cannot find the file specified.
│
│   with module.SubModule.data.local_file.TextFiles["B.txt"],
│   on SubModule\sub.tf line 13, in data "local_file" "TextFiles":
│   13: data "local_file" "TextFiles" {
│
╵
╷
│ Error: open C.txt: The system cannot find the file specified.
│
│   with module.SubModule.data.local_file.TextFiles["C.txt"],
│   on SubModule\sub.tf line 13, in data "local_file" "TextFiles":
│   13: data "local_file" "TextFiles" {
│
╵
```

### Expected Behavior

`terraform apply` succeeds and `data.local_file.TextFiles` is a set containing references to the 3 text files `A.txt`, `B.txt`, and `C.txt`.

### Actual Behavior

Errors stating `The system cannot find the file specified` are shown for each of the 3 files and the `terraform apply` fails.

### Steps to Reproduce

`terraform init`
`terraform apply`

**Comment by mildwonkey** [comment]
Hi @PaulStanos ! I'm sorry for this confusing behavior.

The [`fileset` documentation](https://www.terraform.io/docs/language/functions/fileset.html) states that the function removes the path (the first argument) when returning the values, so the result of `fileset(path.module, "*.txt")` is `A.txt`, `B.txt`, etc. 

In your case, since you need the module path in the value returned from `fileset`, you can write the fileset function as `fileset("", "${path.module}/*.txt")` and get the results you are looking for. Hope this helps!
