### ISSUE TITLE
Group IDs for Azure container Registry

### ISSUE THREAD

**Issue by niravgshah28** [hashicorp/terraform#28945]
Hello All,

While creating Azure container registry in premium SKU with Private endpoint it throws an error of Group IDs.

And there is no usage guidelines on using this groups in output or in private endpoint.

Any help is welcome help, or i am referring to wrong documentation.

Regards
Nirav

**Comment by jbardin** [comment]
Hi @niravgshah28,

This appears to be a question about the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have _questions_ about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
