### ISSUE TITLE
Terraform crash while trying to create Github Repository.

### ISSUE THREAD

**Issue by ngauravit** [hashicorp/terraform#28948]
Terraform version: 1.0.0

[crash.315757274.log](https://github.com/hashicorp/terraform/files/6643500/crash.315757274.log)

**Comment by jbardin** [comment]
Hi @ngauravit,

Thanks for filing the issue. Can you provide any information about how you triggered this error? It would helpful to have an example configuration which reproduces the issue.

Thanks!

**Comment by jbardin** [comment]
We have not heard back in a while, so I'm going to close this out. If the issue persists in the most recent release, please file a new issue with the requested information.

Thanks!
