### ISSUE TITLE
for_each: if condition in for loop ignored?

### ISSUE THREAD

**Issue by flobeier** [hashicorp/terraform#28955]
### Terraform Version

```
1.0.0
```

### Terraform Configuration Files

```terraform
dynamic "backend_address_pool" {
  for_each = {for k, v in local.service_configuration: k => v if contains(keys(v), "api_app_name_match") && contains(keys(data.azurerm_resources.app_service), k)}
  iterator = each
  content {
    name  = "${each.key}-${local.backend_api_address_pool_name}"
    fqdns = [
      "${local.api_app_services[each.key][0].name}.azurewebsites.net"]
  }
}
```

### Debug Output

Output from `terraform console` command:
```log
> keys({for k, v in local.service_configuration: k => v if contains(keys(v), "api_app_name_match") && contains(keys(data.azurerm_resources.app_service), k)})
[
  "abc",
  "cde",
  "efg",
  "hij",
]
```
Error from `terraform plan`:
```log
│ Error: Invalid index
│ 
│   on agw.tf line 231, in resource "azurerm_application_gateway" "app_gateway":
│  231:         "${local.api_app_services[each.key][0].name}.azurewebsites.net"]
│     ├────────────────
│     │ each.key is "xyz"
│     │ local.api_app_services is object with 4 attributes
│ 
│ The given key does not identify an element in this collection value.
```
### Expected Behavior

for_each uses only keys from evaluated for loop

### Actual Behavior

for_each uses a key from the map that the for loop iterates through / ignores if condition in for loop

Addition: Actually it looks like just the condition `contains(keys(data.azurerm_resources.app_service), k)` is ignored. The position of it doesn't matter.

### Steps to Reproduce

?

**Comment by flobeier** [comment]
I tried rewriting the for loop to:
```log
{for k, v in {for k, v in local.service_configuration: k => v if contains(keys(v), "api_app_name_match")}: k => v if lookup(data.azurerm_resources.app_service, k, "") != ""}
```
It doesn't change anything. What am I missing? Running this expression in `terraform console` yields the same expected result as before (without the key "xyz") but when I run `terraform plan` the key "xyz" is there again.

**Comment by jbardin** [comment]
Hi @flobeier,

It hard to say what could be happening here without a reproducible example. One hint I can offer is that the console can only evaluate what is currently in the state, while `plan` is going to evaluate everything including the proposed changes. This means that if `data.azurerm_resources.app_service` is going to include a new instance key of `"xyz"` in the plan, and that key is not in `local.api_app_services`, you would see the demonstrated behavior.

If that doesn't help uncover the problem, we will likely need a standalone config that can reproduce the issue.

Thanks!

**Comment by flobeier** [comment]
That was indeed the issue, thank you very much for your fast response!
