### ISSUE TITLE
AWS WAFv2 Web ACL Logging - Redacted Fields Removal

### ISSUE THREAD

**Issue by lee-clements-rft** [hashicorp/terraform#28951]
### Terraform Version

```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0...
```

### Terraform Configuration Files

```terraform
resource "aws_wafv2_web_acl_logging_configuration" "example" {
  log_destination_configs = [aws_kinesis_firehose_delivery_stream.example.arn]
  resource_arn            = aws_wafv2_web_acl.example.arn
  redacted_fields {
    single_header {
      name = "my-test-header"
    }
  }
}
...
```

### Expected Behavior

When the redacted_fields block which contains a HTTP header (my-test-header) is removed and a terraform apply is ran, I would expect the redacted fields configuration to be removed.

### Actual Behavior

The HTTP header is not removed when the configuration block is removed. Terraform shows no changes detected. The AWS console shows the HTTP header is still redacted.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

I have provided a really basic example to keep it as simple as possible. I am using dynamic blocks and have a whole WAF configuration as well which can be provided if required.

**Comment by jbardin** [comment]
Hi @lee-clements-rft,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
