### ISSUE TITLE
Lifecycle ignore_changes ignored since Terraform 1.0.0

### ISSUE THREAD

**Issue by bmariesan** [hashicorp/terraform#28953]
It seems that `ignore_changes` is ignored for at least some of the aws tags if not all of them.

Since we have a single repository the output of terraform plan is that it will try to override the repository count attribute from 0 to 1.

### Terraform Version
```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
```

### Terraform Configuration Files
```terraform
resource "aws_codeartifact_domain" "repository-domain" {
  provider = aws.us-east-1
  domain   = "domain"
  tags     = merge({ "Name" = "repository-domain" }, var.devops_tags)
  lifecycle {
    ignore_changes = [
      repository_count,
    ]
  }
}
```

### Expected Behavior
ignore_changes should discard changes to the amount of repositories linked to the domain

### Actual Behavior
terraform plan states that the repository count attribute will be overridden even though ignored

### Steps to Reproduce
1. create a AWS CodeArtifact repository
2. create a code artifact domain
3. run terraform plan
4. run terraform apply
5. run terraform plan

**Comment by jbardin** [comment]
Hi @bmariesan,

Thanks for filing the issue. There were no changes to the behavior of `ignore_changes` in recent releases. Are you referring to the information shown as ` Objects have changed outside of Terraform`?

**Comment by bmariesan** [comment]
@jbardin yes that's the case, did I misunderstood the behaviour perhaps?

**Comment by jbardin** [comment]
The "drift" output is simply informative, showing changes that are detected outside of terraform, and the output should include the following message indicating that `ignore_changes` may prevent these difference from having any effect:

> Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using `ignore_changes`, the following plan may include actions to undo or respond to these changes.

Nothing has changed in the operation of terraform here, it is providing more information for users that want to know how resources are changing outside of Terraform's control. The new output shows the differences in the refreshed state and the prior state, as opposed to the `ignore_changes` feature, which acts on the difference in the configuration and the state.

You can follow #28803 for updates on how we may be able to quiet the output in the future for changes that are not relevant to changes in the plan itself.

Thanks!
