### ISSUE TITLE
depends_on only creates a "creational" dependency

### ISSUE THREAD

**Issue by thegedge** [hashicorp/terraform#2895]
If resource A `depends_on` resource B, A will be created after B, but if B gets tainted then nothing will happen to A (assuming no other reference to B). An example:

```
$ cat main.tf
resource "template_file" "foo" {
  filename = "foo.tpl"
}

resource "template_file" "bar1" {
  depends_on = ["template_file.foo"]
  filename = "bar.tpl"
}

resource "template_file" "bar2" {
  filename = "bar.tpl"
  vars {
    spam = "${template_file.foo.rendered}"
  }
}

$ terraform apply && terraform taint template_file.foo && terraform plan
...
-/+ template_file.bar2
    filename:  "bar.tpl" => "bar.tpl"
    rendered:  "" => "<computed>"
    vars.#:    "1" => "<computed>" (forces new resource)
    vars.spam: "2" => ""

-/+ template_file.foo
    filename: "" => "foo.tpl"
    rendered: "" => "<computed>"
```

Is this expected behaviour? I think it is, and if so, it might be nice to call this out in the documentation as it's not immediately clear from https://terraform.io/docs/configuration/resources.html that `depends_on` is _only_ for ordering the creation of resources. Unfortunately, for the setup I have I need the tainted-style dependency, so I've been using the "unused var that references dependent resource" approach of `template_file.bar2`.

**Comment by LusciousPear** [comment]
+1, I actually didn't realize this until I read this post.

**Comment by eyalzek** [comment]
I notice this problem mostly when tainting an `aws_instance` resource and its dependent `aws_route53_record` doesn't update and still points to the old destroyed instance.

**Comment by ElliotG** [comment]
Hit this recently with a depends_on + create_before_destroy. The next object in the chain will be created before the previous object was finished being destroyed.

**Comment by madmod** [comment]
I have had this problem with an implicit interpolation dependency between `aws_ses_rule_set` and `aws_ses_active_rule_set` causing it to fail to destroy.

**Comment by dploeger** [comment]
I think, we actually need some kind of taint_dependency. Maybe in a second parameter besides `depends_on`? Something like `taint_when`?

**Comment by shantanugadgil** [comment]
My resources have the correct `depends_on` set, but I have to remember to `taint` all of them during a destroy-and-recreate

**Comment by jennybrown8** [comment]
I'm also facing this trying to attach an EFS mount to an EC2 instance, where I used the mount target provisioner to build and install the amazon_efs_utils on the ec2 instance.  I'd prefer that when the ec2 instance is tainted and recreated, the efs utils get reinstalled and the efs share mounted correctly, without having to manually taint the whole dependency tree.  Even including depends_on = ec2 instance wasn't enough to trigger it.

**Comment by lsapan** [comment]
This is also an issue when using Terraform with GKE. Changes to a `google_container_cluster` that require recreation don't result in the `google_container_node_pool`(s) getting recreated.

**Comment by e-moshaya** [comment]
just came across this same issue... surely this is a bug...

**Comment by fiid** [comment]
Is there a good workaround or something for this?

I'm deploying code via an s3 bucket object and I need the instance to be recreated when the code changes.

**Comment by shantanugadgil** [comment]
My workaround is to use a Makefile, which has a target "recreate", which taints the appropriate resources before doing an "apply"

**Comment by mildwonkey** [comment]
I am going to close this issue due to inactivity. We do have feature request tickets open that cover this topic, so it's not forgotten!

If there is still a question, I recommend the [the community forum](https://discuss.hashicorp.com/c/terraform-core), where there are far more people available to help. If there is a bug or you would like to make a feature request, please open a new issue and fill out the template.
Thanks!

**Comment by nihr43** [comment]
found this today with a postgresql database resource and some dependent schemas.  i may go poking around for those feature request tickets mentioned
