### ISSUE TITLE
Intermittent reporting of `Objects have changed outside of Terraform`

### ISSUE THREAD

**Issue by pikesley** [hashicorp/terraform#28961]
### Terraform Version

```
Terraform v1.0.0
```

### Actual Behaviour

We have an `aws_kms_key` defined:

```terraform
resource "aws_kms_key" "aws-cloudtrail-key" {
  enable_key_rotation = true
  policy = jsonencode(
    {
      Id = "Key policy created by CloudTrail"
      Statement = [
        {
          Action = "kms:*"
          Effect = "Allow"
          Principal = {
            AWS = [
              "arn:aws:iam::12345678:user/some.user",
              "arn:aws:iam::12345678:root",
            ]
          }

<more config here>
```

Since we upgraded from TF 0.14 to 1.0, there is an issue where on `terraform plan` or `apply`, it *intermittently* reports

```terraform
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.cloud-trail.aws_kms_key.aws-cloudtrail-key has been changed
  ~ resource "aws_kms_key" "aws-cloudtrail-key" {
        id                       = "id-goes-here"
      ~ policy                   = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = [
                              - "arn:aws:iam::12345678:user/some.user",
                                "arn:aws:iam::12345678:root",
                              + "arn:aws:iam::12345678:user/some.user",
                            ]

<snip>

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to
match, create and apply a refresh-only plan:
  terraform apply -refresh-only
```

Notes:
* this does not happen on every run - I presume the AWS API reports that list back in an arbitrary order, and sometimes that matches the fixed order in the Terraform state so everything is clean
* we have tried running `terraform apply -refresh-only` as recommended there, but all that seems to do is change the list order in the state, which means the problem still exists
* this has only started since we moved from `0.14` to `1.0`

### Expected Behaviour

When nothing has changed, `terraform plan` or `apply` should be quiet, not raise (maybe harmless, but very distracting) warning messages

**Comment by jbardin** [comment]
Hi @pikesley,

The provider itself is what is returning the changes that Terraform reports when reading the resources, so the provider would need to be updated to prevent unecessary changes like this. We are also working on reducing the output of changes that are not directly related to the plan, and you can follow any updates there in #28803

Thanks!

**Comment by llange** [comment]
See also:
* hashicorp/terraform-provider-aws#19727 (An issue raised with the AWS provider)
* #28911 (a duplicate, closed for the same reason)
