### ISSUE TITLE
Google Cloud SLO | String passed through must be an Integer, and defaults to none

### ISSUE THREAD

**Issue by saidi-adam** [hashicorp/terraform#28969]
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_slo

I'm trying to create a google_monitoring_slo resource within GCP via Terraform and as per the documentation (link above), it states that the range block which consists of min and max will always default to Infinity if let blank as well as they're both optional.

I currently want to specify a `min` of 1440 and a `max` of infinity - so as per the docs, i could leave max blank. Doing this returns the following error message when running Terraform Deploy

│ Error: Error creating Slo: googleapi: Error 400: The minimum of the range in a MetricSumInRange must be less than its maximum. Got a minimum of 1440.0 and a maximum of 0.0

I've created the resource via GCP console and viewed the JSON version of it - and it specifies the following
`"range": { "min": 1440, "max": "Infinity" }`
I've tried passing through` max="Infinity"` but i shortly get a failure, stating that max must be an integer, not a string. I then tried passing a large number 999 million as the max value, which worked. I just want to have infinity and i feel like the docs are suggesting something that i've tried. Do you have any idea how i can get over this?

Moreover, I've noticed that within the codebase (link below) there doesn't seem to be a check for `min`, just `max` 
https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_monitoring_slo_test.go 

Just to add - the issue i'm having here seems to be similar to the one closed before here - https://github.com/hashicorp/terraform-provider-google/issues/7614#issuecomment-715634061, but there were no comments made about a fix on the ticket

Thank you!

**Comment by jbardin** [comment]
Hi @saidi-adam,

This appears to be an issue with the Goole provider, not with Terraform itself. While the underlying type system in Terraform can support infinite values, the SDK and json endoer used by the provider cannot. From the documention the provider seems to intend to detect when a value is unset, however the legacy SDK in use by the provider cannot reliably differentiate between null and zero values, so the intended behavior is not directly possible. However, I think they should be able to detect when a 0 value is not valid, and convert that to an implied infinitiy, so I would suggest opening an issue with the Google provider team. 

Thanks!
