### ISSUE TITLE
Terraform 1.0.0: Parameter private_ip_address_version in resource azurerm_lb not picked up 

### ISSUE THREAD

**Issue by markokole** [hashicorp/terraform#28960]
After upgrading to 1.0.0 and running plan/apply the resource **azurerm_lb** keeps getting argument **private_ip_address_version** into update state. It does not matter if this argument is in the tf file or not. If the update is provisioned, the next *terraform plan* will again show the same to be updated.

It seems as if it does not read this argument and always assumes it has been changed: **private_ip_address_version    = "IPv4"**

### Terraform Version
```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.2.5
+ provider registry.terraform.io/hashicorp/azuread v1.2.2
+ provider registry.terraform.io/hashicorp/azurerm v2.46.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Terraform Configuration Files

```terraform
resource azurerm_lb lb {
  name                = "${local.project}-lb"
  sku                 = "Standard"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  frontend_ip_configuration {
    name                        = azurerm_public_ip.public_ip_endpoint.name
    public_ip_address_id        = azurerm_public_ip.public_ip_endpoint.id
    # private_ip_address_version  = "IPv4"  # does not matter if its commented or not.
  }
}
```

### Expected Behavior

Read the parameter and create plan based on the value of the parameter

### Actual Behavior

```terraform
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_lb.lb will be updated in-place
  ~ resource "azurerm_lb" "lb" {
        id                   = "/subscriptions/abc/resourceGroups/rg/providers/Microsoft.Network/loadBalancers/test-lb"
        name                 = "test-lb"
        tags                 = {
            "created-by"  = "tester"
            "environment" = "test"
            "project"     = "test"
        }
        # (4 unchanged attributes hidden)

      ~ frontend_ip_configuration {
            id                            = "/subscriptions/abc/resourceGroups/rg/providers/Microsoft.Network/loadBalancers/test-lb/frontendIPConfigurations/test-publicip"
            name                          = "test-publicip"
          + private_ip_address_version    = "IPv4"
            # (6 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. create a simple resource azurerm_lb in version lower than 1.0.0
2. upgrade terraform to 1.0.0.
3. run `terraform plan`

### Additional Context

Upgraded Terraform from 0.14.5 to 1.0.0, using a custom container on windows.

**Comment by jbardin** [comment]
This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by markokole** [comment]
Are you guys even reading issues? Its an Azure resource and your closing this because its an AWS issue?

**Comment by jbardin** [comment]
Sorry @markokole, you are correct, I hit the wrong form button on that. The correct repo link for AzureRM is: https://github.com/terraform-providers/terraform-provider-azurerm/issues.

Thanks!
