### ISSUE TITLE
ISSUE: volume_tags not working for root_block_device

### ISSUE THREAD

**Issue by hostedvideorn** [hashicorp/terraform#28971]
TFE CODE
```
resource "aws_instance" "awsusql0034" {

  root_block_device {
    volume_size           = "50"
    volume_type           = "gp2"
    delete_on_termination = "true"
  }

  volume_tags = {
    "Name" = "ebs-root-awsusql0034"
    "Backup" = "true"
  }

  tags {
    Name         = "awsusql0034"
    Description  = "host awsusql0034"
    Environment  = "qa"
    Server_Type  = "app_db"
    Backup       = "false"
    Managed      = "terraform"
  }

}

resource "aws_volume_attachment" "ebs-attach-awsusql0034-data-2" {
  device_name = "/dev/sdk" 
  volume_id   = "${aws_ebs_volume.ebs-awsusql0034-data-2.id}"
  instance_id = "${aws_instance.awsusql0034.id}"
}

resource "aws_ebs_volume" "ebs-awsusql0034-data-2" {
  type              = "gp2"
  size              = "100"

  tags {
    Name        = "ebs-data-2-awsusql0034"
    Environment = "qa"
    Tier        = "app_db"
    Backup      = "false"
    Managed     = "terraform"
  }
}
```

Terraform v0.11.15

Configuring remote state backend...
Initializing Terraform configuration...
2021/06/16 21:48:46 [DEBUG] Using modified User-Agent: Terraform/0.11.15 TFE/v202101-1

.....
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

~aws_instance.awsusql0034
      volume_tags.%:           "5" => "2"
      volume_tags.Backup:      "false" => "true"
      volume_tags.Environment: "qa" => ""
      volume_tags.Managed:     "terraform" => ""
      volume_tags.Name:        "ebs-data-2-awsusql0034" => "ebs-root-awsusql0034"
      volume_tags.Tier:        "app_db" => ""

It is changing the tag of a different volume and not the root volume. See code above for reference

**Comment by jbardin** [comment]
Hi @hostedvideorn,

This appears to be an issue with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. I would first confirm that you can replicate your issue with a current release of terraform, as 0.11 is no longer supported, and it's behavior may not match the expectations recent provider releases.

If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
