### ISSUE TITLE
Azure Data Factory Linked Service not being deployed

### ISSUE THREAD

**Issue by NickBishop2112** [hashicorp/terraform#28978]
Terraform not creating an Azure SQLDatabase linked service from ADF. 

### Terraform Version
hashicorp/azurerm = "=2.63.0"
```
...
```

### Terraform Configuration Files
Example

```
resource "azurerm_data_factory_linked_service_azure_sql_database" "foobar_sql_database" {
  name                = "foobar-linked-service"    
  resource_group_name = data.azurerm_resource_group.foobar.name
  data_factory_name   = azurerm_data_factory.foobar.name

  key_vault_connection_string {
      linked_service_name = azurerm_data_factory_linked_service_key_vault.key_vault.name
      secret_name = "ConnectionStrings--AdfConnection"
  }
}.
```

### Expected Behavior
Azure SQL Linked service should be created in ADF.

### Actual Behavior
Azure SQL Linked service was not created in ADF. 

### Steps to Reproduce
Delete the linked service from within ADF and run the Terraform deploy (init, validate, generate plan and build) to re-create the linked service. The generate plan did not pick up the change. The linked service was not re-created.

**Comment by NickBishop2112** [comment]
Having the same issue with other linked services.

One other information the names were set as "foobar-linked-service" instead of "foobar_linked_service".  Changes still not picked up.

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
