### ISSUE TITLE
Terraform Docker Hub instructions don't work

### ISSUE THREAD

**Issue by jonassteinberg1** [hashicorp/terraform#28980]
### Terraform Version

```
docker run -it hashicorp/terraform:light -version                                                                                                               ✘ INT
Terraform v1.0.0
on linux_amd64
```

### Terraform Configuration Files

```terraform
# taken straight from
# this hashicorp tutorial:
# https://learn.hashicorp.com/tutorials/terraform/install-cli?in=terraform/aws-get-started#quick-start-tutorial

# main.tf
terraform {
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
    }
  }
}

provider "docker" {}

resource "docker_image" "nginx" {
  name         = "nginx:latest"
  keep_locally = false
}

resource "docker_container" "nginx" {
  image = docker_image.nginx.latest
  name  = "tutorial"
  ports {
    internal = 80
    external = 8000
  }
}

```

### Crash Output
```
# command is taken directly from hashicorp docker hub page
~/code/terraform-install-terraform ❯ docker run -it hashicorp/terraform:light plan main.tf
╷
│ Error: Too many command line arguments
│
│ To specify a working directory for the plan, use the global -chdir flag.
╵

For more help on using this command, run:
  terraform plan -help

~/code/terraform-install-terraform ❯ ls -la main.tf
-rw-r--r--  1 jonas  staff  362 Jun 18 07:51 main.tf
```

### Expected Behavior
the terraform light docker container plans my local main.tf?

### Actual Behavior
see crash output

### Steps to Reproduce
1. pull hashicorp/light
2. create a main.tf with the code block above
3. run the command above

### Additional Context
I'm not sure what I'm doing wrong?  Am I suppose to docker cp the main.tf and create a new image or?  I was assuming that the light image was going to read a *local* file but now that I think about it how would that even happen?  Now I'm thinking that the `plan main.tf` args in the docker hub instructions are just args to the container's entrypoint and that the main.tf file actually needs to be in the container?  But the docker hub instructions make it seem like the way the container is supposed to function is that you provide terraform arguments and somehow the container reads local files.

### References
docker hub instruction link is given above.

**Comment by mildwonkey** [comment]
Hi @jonassteinberg1 !

You're correct in that the directions on docker hub don't make sense! You might run `terraform apply planfile` (to apply a planfile that you created with `terraform plan -out planfile`, but never `terraform apply main.tf`. 

I'll label this as a documentation issue and see if I can track down where those instructions even come from - sorry for the confusion!

**Comment by jonassteinberg1** [comment]
@mildwonkey no apologies needed.  glad I'm not crazy.

**Comment by mildwonkey** [comment]
That was easier than I expected, I've removed the misleading `main.tf` from the docker hub instructions! 
Thanks for letting us know 😁

**Comment by jonassteinberg1** [comment]
@mildwonkey sorry but that doesn't change anything.  did you test that?  does not work for me.

```
docker run -i -t hashicorp/terraform:light plan
╷
│ Error: No configuration files
│
│ Plan requires configuration to be present. Planning without a configuration would mark everything for destruction, which is normally not what is desired. If you would like to destroy everything,
│ run plan with the -destroy option. Otherwise, create a Terraform configuration file (.tf file) and try again.
╵

❯ ls
main.tf
```

I'm on a Mac Intel.  Brand new.  This really shouldn't be complicated?  Not sure what I'm missing; just seems like the image does not work.
