### ISSUE TITLE
remove extra newline in validate output

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform#28996]
```
% tf validate                             
Success! The configuration is valid.

%
```

Just creating as a placeholder, to see if I can get some review on #28461

Totally fine if you want to reclassify as an enhancement, since it's (obviously) quite trivial.

**Comment by wyardley** [comment]
@mildwonkey @alisdair sorry to bug you two somewhat at random, but not sure where a good place is to bug people @ Hashicorp about issues / PRs - would either of you have time to look at this and / or have someone take a look?

**Comment by wyardley** [comment]
Hi @crw 
Any more news on some kind of fix for this? I know you had mentioned working on consistency of error message formatting broadly - is there a ticket for that somewhere?

**Comment by crw** [comment]
As far as I know, there is not a Github issue for examining error message consistency. This is typical of the type of issue that would be cleaned up when working on some adjacent feature or technology, which makes it somewhat unpredictable in terms of scheduling. I am also following up on the attached PR.

**Comment by wyardley** [comment]
Ok, but doesn't it seem a given that a UNIX program should not output an extra newline when printing something? For example:
```
% ls
bar/ foo/
```
vs
```
% ls
bar/ foo/

```

It is insane to me that the Terraform core team will not accept a PR removing a cosmetic / extra newline, where there would be no harm in _not_ having it, and no benefit at all for _having_ it, especially when keeping it open for over a year without any kind of meaningful code review, but 🤷 🙄
