### ISSUE TITLE
from root_module with for_each need to call a local in a module 

### ISSUE THREAD

**Issue by cslinuxfr** [hashicorp/terraform#28990]
### Current Terraform Version

Terraform v0.15.3

Hi, is it possible to call a local which is in a module from the root module to do a for_each from it?

Example:
From root_module:

module "public_asg_metric_alarms" {
  source = "./modules/cloudwatch"

  for_each = "${local.public_asg_metrics}"

  alarm_name          = "${each.key}_public_asg"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 1
  metric_name         = each.key
  namespace           = "AWS/EC2"
  period              = 60
  statistic           = "Maximum"
  threshold           = each.value.threshold
  unit                = "Milliseconds"

  dimensions = {
    AutoScalingGroupName = module.public_asg.autoscaling_group_name
  }
  alarm_actions = [module.public_asg_sns_topic.sns_topic_arn]
}

local i want to call from public_asg_metric_alarms module:

locals {
  public_asg_metrics = {
    DiskWriteBytes = {
      threshold = 5
    },
    NetworkOut = {
      threshold = 150000
    },
    CPUCreditUsage = {
      threshold = 30
    },
    EBSWriteOps = {
      threshold = 30000
    },
    StatusCheckFailed = {
      threshold = 2
    },
    StatusCheckFailed_Instance = {
      threshold = 2
    },
    StatusCheckFailed_System = {
      threshold = 2
    }
  }
}

**Comment by jbardin** [comment]
Hi @cslinuxfr,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
