### ISSUE TITLE
Terraform Crash while Creating Private DNS Zone

### ISSUE THREAD

**Issue by roshanp85** [hashicorp/terraform#29001]
[crash.zip](https://github.com/hashicorp/terraform/files/6689545/crash.zip)
Crash Log attached.

While trying to create the Private DNZ Zone, the terraform crashed.
Azurerm: 2.64.0
Terraform Version: 0.12.24

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
