### ISSUE TITLE
S3 backend - better error messages when using AWS credentials with no access to the configured S3 bucket

### ISSUE THREAD

**Issue by qwerty1979bg** [hashicorp/terraform#29008]
### Current Terraform Version

```
Terraform v1.0.0
on darwin_amd64
```

### Use-cases

A better error handling / error message will save time and effort in troubleshooting.

### Proposal

The S3 backend has a good error handling for the cases where:

* No credentials were provided:
```
Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
```

* The credentials are invalid in some way:
```
Error: error configuring S3 Backend: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid
```

* Or the credentials are expired:
```
Error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
```

```
Error: error configuring S3 Backend: error validating provider credentials: error calling sts:GetCallerIdentity: ExpiredToken: The security token included in the request is expired
```

However, if you try to use the S3 backend (as a backend or a remote state source) with AWS credentials that does not have access to the S3 bucket, the error message is less helpful:

```
$ terraform init

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: P76NG4DR5MDC5C8P, host id: gNiY/lgJ1YVdzOauB8uFxF8ej7aeVa/+wWLM241ut6LTlSQET3Ouih308fqiNsDTZehHsb07PR4=
```

Note that is says that is "successfully configured the backend" and then shows the "Access Denied" message.

**It is even worse, when you are using the S3 backend to fetch data from a remote state:**

```
$ terraform plan
╷
│ Error: AccessDenied: Access Denied
│ 	status code: 403, request id: A48SMMRNVHXYP1Z0, host id: woYzJVOLST83OsL8zozRFwemoADdNwL9dOWmLZzl9uuBJuWuoofdHGPijXTjMGL++noU7EMsMH0=
```

**Note that it is not clear why the plan is failing and where the "Access Denied" is coming from.**

Steps to reproduce:

1. Have a Terraform code to fetch data from a S3 based remote state:
```
data "terraform_remote_state" "test" {
  backend = "s3"
  config = {
    bucket = "some_S3_bucket"
    key    = "path/to/my/key"
    region = "us-east-1"
  }
}
```
2. Provide valid S3 credentials that do not have access to the S3 bucket containing the remote state
3. Perform "terraform plan"

**Comment by paulgear** [comment]
> The S3 backend has a good error handling for the cases where:
> 
> * No credentials were provided:
>
> ```Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.```

Actually, it's not that good.  In the case where AWS_PROFILE is set, if the profile in ~/.aws/credentials uses AWS_ACCESS_KEY_ID in upper case rather than lower case, terraform fails to recognise it as a correct credential, even though the AWS CLI has no difficulty using it like that.

```
$ echo $AWS_PROFILE
my-special-iam-user
$ aws sts get-caller-identity
{
    "UserId": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "Account": "123456789012",
    "Arn": "arn:aws:iam::123456789012:user/my-special-iam-user"
}
$ terraform --version
Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/aws v5.9.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
$ terraform plan
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│ 
╵
$ vi ~/.aws/credentials  # change AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in the profile to lower case
$ terraform plan
Acquiring state lock. This may take a few moments...
...
[the rest works fine]
```

**Comment by paulgear** [comment]
It seems that my problem is actually https://github.com/hashicorp/terraform-provider-aws/issues/1996 and it's possible that it's due to a difference between the AWS Go SDK and the python SDK which the CLI uses...
