### ISSUE TITLE
Azurerm: Public IP SKU Tier support

### ISSUE THREAD

**Issue by hallerx** [hashicorp/terraform#29015]
### Current Terraform Version

```
0.14.8
``` 

### Use-cases

Azure Public IP has an option to set up Tier (Global or Regional). Unfortunately, Terraform AzureRM provider does not support Tier parameter under SKU.

### Attempted Solutions

```
resource "azurerm_public_ip" "main" {
  name                = "test-publicip"
  resource_group_name = "resouce-group-1"
  location            = "West Europe"
  sku               =  {
    name = "Standard"
    tier = "Global"
  }
}
...
```

Actual output:
```
Error: Incorrect attribute value type

  on ..\main.tf line 29, in resource "azurerm_public_ip" "main":
  29:   sku               =  {
  30:     name = "Standard"
  31:     tier = "Regional"
  32:   }
```
### Proposal

I have dig into PowerShell Azure Public IP parameters, and it looks like SKU has multiple properties. Ideally, Terraform should accept SKU a map rather than string to accept Tier property:
```
$publicip.sku | Get-Member 

   TypeName: Microsoft.Azure.Commands.Network.Models.PSPublicIpAddressSku

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
Name        Property   string Name {get;set;}
Tier        Property   string Tier {get;set;}
```
### References

N/A

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
