### ISSUE TITLE
Fortigate Crash

### ISSUE THREAD

**Issue by pivetta1975** [hashicorp/terraform#29013]
My terraform crashed when I tried to deploy two fortigates on IBM Cloud portal catalog:

 2021/06/22 18:25:54 Terraform apply | ibm_is_instance.fgt1: Still creating... [10m30s elapsed]
 2021/06/22 18:25:56 Terraform apply | ibm_is_instance.fgt2: Still creating... [9m20s elapsed]
 2021/06/22 18:26:04 Terraform apply | ibm_is_instance.fgt1: Still creating... [10m40s elapsed]
 2021/06/22 18:26:06 Terraform apply | ibm_is_instance.fgt2: Still creating... [9m30s elapsed]
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | Error: rpc error: code = Unavailable desc = transport is closing
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | Error: rpc error: code = Unavailable desc = transport is closing
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | panic: runtime error: invalid memory address or nil pointer dereference
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.454Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xd5314f]
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.454Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.454Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: goroutine 281 [running]:
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.454Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).MakeRequest(0xc00011d480, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0x0, 0x0, 0x0)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.454Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:108 +0x36f
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc00011d480, 0x4, 0x12a05f200, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0xc000d50030, 0xc000443770, 0xc000ea1313)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:124 +0x56
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc00011d480, 0x4, 0x12a05f200, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0xc000ea6d20, 0xc000443770, 0xc000ea1313)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc00011d480, 0x5, 0x12a05f200, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0xc000ea6000, 0xc000443770, 0xc000b81313)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc00011d480, 0x6, 0x12a05f200, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0xc000b8f6b0, 0xc000443770, 0xc000cc1313)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc00011d480, 0x7, 0x12a05f200, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0xc000cc20c0, 0xc000443770, 0xc000bd1313)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc00011d480, 0x8, 0x12a05f200, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0xc000bd3e60, 0xc0004f3800, 0x0)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).tryHTTPRequest(0xc00011d480, 0x9, 0x12a05f200, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0x40ed2d, 0x256ff80, 0xc000ea77a0)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:134 +0x17d
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).SendRequest(0xc00011d480, 0xc00050ef68, 0x20c1540, 0xc000fdc5e0, 0xf, 0xc0000494c0, 0x3f)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:74 +0xce
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/client.(*Client).Post(0xc00011d480, 0xc0002ec1c0, 0xf, 0x20c1580, 0xc00078a700, 0x20c1540, 0xc000fdc5e0, 0x0, 0x0, 0x0, ...)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/client/client.go:178 +0x205
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/bluemix-go/api/globaltagging/globaltaggingv3.(*tags).AttachTags(0xc0000ada50, 0xc000d21780, 0x78, 0xc00078a6c0, 0x4, 0x4, 0x0, 0x4, 0x4, 0x2573340, ...)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/!i!b!m-!cloud/bluemix-go@v0.0.0-20210125055453-344c1ff77d84/api/globaltagging/globaltaggingv3/tagging.go:80 +0x1d6
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.UpdateTagsUsingCRN(0x2573340, 0xc000fdc4e0, 0x2573340, 0xc000fdc420, 0x2625920, 0xc000111500, 0xc000d21780, 0x78, 0x0, 0xc000897400)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/structures.go:1682 +0x482
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.instanceCreate(0xc000421180, 0x2625920, 0xc000111500, 0xc000433ee7, 0x7, 0xc00019f830, 0x23, 0xc00019fb60, 0x29, 0xc000d9a000, ...)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_is_instance.go:829 +0x19d5
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/IBM-Cloud/terraform-provider-ibm/ibm.resourceIBMisInstanceCreate(0xc000421180, 0x2625920, 0xc000111500, 0x2, 0x3825620)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/resource_ibm_is_instance.go:856 +0x414
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00087f780, 0xc000f0ae60, 0xc000516780, 0x2625920, 0xc000111500, 0x229ff01, 0xc000ded7b8, 0xc000d22030)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/resource.go:305 +0x375
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000a8e380, 0xc00050fa10, 0xc000f0ae60, 0xc000516780, 0xc000c13a68, 0xc00049cf68, 0x22a3020)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/helper/schema/provider.go:294 +0x99
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000ad620, 0x2a49a00, 0xc000dd15c0, 0xc000d357a0, 0xc0000ad620, 0xc000dd15c0, 0xc000ca2b78)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x2584f40, 0xc0000ad620, 0x2a49a00, 0xc000dd15c0, 0xc000d35740, 0x0, 0x2a49a00, 0xc000dd15c0, 0xc000c28000, 0x1501)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.6.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a0f00, 0x2a605a0, 0xc000092a80, 0xc000199000, 0xc000596510, 0x37c40c0, 0x0, 0x0, 0x0)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: google.golang.org/grpc.(*Server).handleStream(0xc0004a0f00, 0x2a605a0, 0xc000092a80, 0xc000199000, 0x0)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0007622d0, 0xc0004a0f00, 0x2a605a0, 0xc000092a80, 0xc000199000)
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.455Z [DEBUG] plugin.terraform-provider-ibm_v1.20.1: 	/Users/harinireddy/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [DEBUG] ibm_is_instance.fgt2: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalMaybeTainted
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalMaybeTainted: ibm_is_instance.fgt2 encountered an error during creation, so it is now marked as tainted
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalWriteState
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalWriteState: removing state object for ibm_is_instance.fgt2
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalApplyProvisioners
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalApplyProvisioners: ibm_is_instance.fgt2 has no state, so skipping provisioners
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalMaybeTainted
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalMaybeTainted: ibm_is_instance.fgt2 encountered an error during creation, so it is now marked as tainted
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalWriteState
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalWriteState: removing state object for ibm_is_instance.fgt2
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalIf
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalIf
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalWriteDiff
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalApplyPost
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] [walkApply] Exiting eval tree: ibm_is_instance.fgt2
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] vertex "ibm_is_instance.fgt2": visit complete
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "ibm_is_floating_ip.publicip3" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "output.FGT2_Public_HA_Mangment_IP (expand)" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.457Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/ibm-cloud/ibm/1.20.1/linux_amd64/terraform-provider-ibm_v1.20.1 pid=171 error="exit status 2"
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [DEBUG] ibm_is_instance.fgt1: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalMaybeTainted
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalMaybeTainted: ibm_is_instance.fgt1 encountered an error during creation, so it is now marked as tainted
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalWriteState
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "output.FGT2_Default_Admin_Password (expand)" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalWriteState: removing state object for ibm_is_instance.fgt1
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalApplyProvisioners
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalApplyProvisioners: ibm_is_instance.fgt1 has no state, so skipping provisioners
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalMaybeTainted
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalMaybeTainted: ibm_is_instance.fgt1 encountered an error during creation, so it is now marked as tainted
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalWriteState
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] EvalWriteState: removing state object for ibm_is_instance.fgt1
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalIf
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalIf
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalWriteDiff
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] eval: *terraform.EvalApplyPost
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] [walkApply] Exiting eval tree: ibm_is_instance.fgt1
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] vertex "ibm_is_instance.fgt1": visit complete
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "ibm_is_floating_ip.publicip" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.458Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "output.FGT1_Default_Admin_Password (expand)" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "ibm_is_floating_ip.publicip2" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "output.FortiGate_Public_IP (expand)" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "output.FGT1_Public_HA_Mangment_IP (expand)" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/ibm-cloud/ibm\"] (close)" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] dag/walk: upstream of "root" errored, so skipping
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] statemgr.Filesystem: no original state snapshot to back up
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 5
 2021/06/22 18:26:07 Terraform apply | 2021/06/22 18:26:07 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
 2021/06/22 18:26:07 Terraform apply | 2021-06-22T18:26:07.464Z [DEBUG] plugin: plugin exited
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | Terraform crashed! This is always indicative of a bug within Terraform.
 2021/06/22 18:26:07 Terraform apply | A crash log has been placed at "crash.log" relative to your current
 2021/06/22 18:26:07 Terraform apply | working directory. It would be immensely helpful if you could please
 2021/06/22 18:26:07 Terraform apply | report the crash with Terraform[1] so that we can fix this.
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | When reporting bugs, please include your terraform version. That
 2021/06/22 18:26:07 Terraform apply | information is available on the first line of crash.log. You can also
 2021/06/22 18:26:07 Terraform apply | get it by running 'terraform --version' on the command line.
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | SECURITY WARNING: the "crash.log" file that was created may contain 
 2021/06/22 18:26:07 Terraform apply | sensitive information that must be redacted before it is safe to share 
 2021/06/22 18:26:07 Terraform apply | on the issue tracker.
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | [1]: https://github.com/hashicorp/terraform/issues
 2021/06/22 18:26:07 Terraform apply | 
 2021/06/22 18:26:07 Terraform apply | !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 2021/06/22 18:26:07 Terraform APPLY error: Terraform APPLY errorexit status 1
 2021/06/22 18:26:07 Could not execute action

**Comment by jbardin** [comment]
Hi,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
