### ISSUE TITLE
Terraform crashes with interface conversion in GCE Instance Template

### ISSUE THREAD

**Issue by j-oconnor** [hashicorp/terraform#2901]
Seems to be related to the disk_size_gb arg.

panic: interface conversion: interface is int, not int64
2015/07/31 02:41:57 terraform-provider-google:
2015/07/31 02:41:57 terraform-provider-google: goroutine 38 [running]:
2015/07/31 02:41:57 terraform-provider-google: github.com/hashicorp/terraform/builtin/providers/google.buildDisks(0xc2080522a0, 0x99d3c0, 0xc208040eb0, 0x0, 0x0, 0x0, 0x0, 0x0)

Not sure if I'm expected to create the disk separately then reference it in to the template.  The disk_size_gb arg isn't documented, but i saw the code was there and its supported by API.

I'm on 0.6.2dev built from master.  I can duplicate readily just using the sample code from docs and adding "disk_size_gb = 20" on the boot disk.  I'll post the crash.log if needed.

**Comment by j-oconnor** [comment]
I got it to work on my local with simple typecast.  

````
@@ -261,7 +261,7 @@ func buildDisks(d *schema.ResourceData, meta interface{}) ([]*compute.AttachedDi
                                disk.InitializeParams.DiskName = v.(string)
                        }
                        if v, ok := d.GetOk(prefix + ".disk_size_gb"); ok {
-                               disk.InitializeParams.DiskSizeGb = v.(int64)
+                               disk.InitializeParams.DiskSizeGb = int64(v.(int))
                        }
                        disk.InitializeParams.DiskType = "pd-standard"
                        if v, ok := d.GetOk(prefix + ".disk_type"); ok {
````

**Comment by suguru** [comment]
I have same issue disk_size_gb in google_container_cluster.node_config

```
panic: interface conversion: interface is int, not int64
2015/07/31 17:14:31 terraform-provider-google:
2015/07/31 17:14:31 terraform-provider-google: goroutine 74 [running]:
2015/07/31 17:14:31 terraform-provider-google: github.com/hashicorp/terraform/builtin/providers/google.resourceContainerClusterCreate(0xc208390240, 0x593d00, 0xc2082a7b30, 0x0, 0x0)
2015/07/31 17:14:31 terraform-provider-google: 	/private/tmp/terraform20150721-61224-ibcnhu/terraform-0.6.1/src/github.com/hashicorp/terraform/builtin/providers/google/resource_container_cluster.go:256 +0xb6a
```
