### ISSUE TITLE
Terraform Registry: Module input variables with "null" default show as "Required"

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform#29023]
Not sure where the best place is to report a bug with the Terraform Registry, but perhaps someone can direct this to the right place.

### Terraform Version

```
[Terraform Registry](https://registry.terraform.io/)
```

### Terraform Configuration Files

```terraform
variable "myvar" {
  description = "(Optional) Some variable that defaults to `null`."
  type        = string
  default     = null
}
```

### Expected Behavior

The Terraform registry documentation for the module should show the `myvar` input variable under the "Optional Inputs" section since it has a default value (`null`) and doesn't need to be provided.

### Actual Behavior

The Terraform registry documentation for the module shows the `myvar` input variable under the "Required Inputs" section.

### Steps to Reproduce

1. Create a new module with an input variable that has a default value of `null`.
2. Import the module into the Terraform Registry.
3. Look at the Terraform Registry documentation page for the module, under the "Inputs" category.
4. Note that your variable that has a default value (and isn't actually required) appears under the "Required Inputs" section.

### Additional Context
Here's a real-world example.
[GitHub repo](https://github.com/Invicton-Labs/terraform-aws-sts-role-assumption/blob/84c832ce13e8b9d0abf806a4a7560567adba0e45/variables.tf)
[Corresponding Terraform Registry page](https://registry.terraform.io/modules/Invicton-Labs/sts-role-assumption/aws/0.1.0?tab=inputs)

**Comment by alisdair** [comment]
Thanks for reporting this! For issues with the Terraform Registry, please send an email to terraform-registry@hashicorp.com, which is monitored by the team at HashiCorp responsible for the registry. I'm closing this issue out because it's not a Terraform core bug.
