### ISSUE TITLE
atlas_artifact not behaving as documented

### ISSUE THREAD

**Issue by leg100** [hashicorp/terraform#2904]
I suspect this is an upstream problem with Atlas, but since that's closed source, I thought this'll be the next best place to report it.

```
resource "atlas_artifact" "zookeeper" {
  name = "leg100/zookeeper"
  type = "aws.ami"
}
```

On running a `terraform apply`:

```
* No matching artifact for 'leg100/zookeeper'
```

Explicitly setting `version` to latest:

```
resource "atlas_artifact" "zookeeper" {
  name = "leg100/zookeeper"
  type = "aws.ami"
  version = "latest"
}
```
```
* No matching artifact for 'leg100/zookeeper'

```

While this succeeds:

```
resource "atlas_artifact" "zookeeper" {
  name = "leg100/zookeeper"
  type = "aws.ami"
  version = "29"
}
```

Indeed, running the underlying request confirms it's a problem with Atlas:

```
curl -H "X-Atlas-Token: ${ATLAS_TOKEN}" https://atlas.hashicorp.com/api/v1/artifacts/leg100/zookeeper/aws.ami/search?version=latest
```
Returns
```
{"versions":[]}
```

Combined with issue #732, this makes `atlas_artifact` a nightmare to work with.

**Comment by jedineeper** [comment]
What does this link return?

https://atlas.hashicorp.com/leg100/artifacts/zookeeper/types/aws.ami

If its empty, its worth checking the permissions for the artifact in Atlas?

**Comment by leg100** [comment]
@jedineeper It returns a list of versions for that build. Are you seeing the same behaviour described above?

**Comment by jedineeper** [comment]
No, I have had some issues with artifact where I didn't have access to the artifact in Atlas and it failed in a similar manner you described so I thought that might be it.

I've tried reproducing your issue this morning and it seemed to work ok for me on Terraform 0.6.1?

https://gist.github.com/jedineeper/a298f100bfe817978f28

Some possible issues;

a.) I've discovered that "type" in atlas_artifact on both the packer and terraform side is basically a freeflow text field, be sure to standardise on "something" on both sides. (I chose amazon.ami, I notice you are using aws.ami, I think it is fine as long as you don't accidentally try to use both.)
b.) Worth double checking your Atlas token is correct? I know it sounds obvious, but if you can see it in the dashboard and not in the API call then it is something to validate as I can reproduce the correct results from your tests above. :(

I even tried your curl command;

``` javascript
$ curl -H "X-Atlas-Token: ${ATLAS_TOKEN}" https://atlas.hashicorp.com/api/v1/artifacts/jedineeper/var-test/amazon.ami/search?version=latest
{"versions":[{"username":"jedineeper","name":"var-test","tag":"jedineeper/var-test","slug":"jedineeper/var-test/amazon.ami/2","artifact_type":"amazon.ami","id":"eu-west-1:ami-1af8b16d","version":2,"metadata":{"region":"eu-west-1","provider":"amazon","created-at":"1437342640","region.eu-west-1":"ami-1af8b16d"},"file":false}]}
```

I'll think about it some more but I've no other ideas right now, sorry :(

**Comment by jedineeper** [comment]
Oh, and as a temporary fix to 732, add the region as metadata to the packer build and specify it in the atlas_artifact like this....

```
resource "atlas_artifact" "var-test-2" {
  name = "jedineeper/var-test"
  type = "amazon.ami"
  version = "1"
  metadata {
    region = "${var.region}"
  }
}
```
`image_id = "${element(split(":", atlas_artifact.test.id),1)}"`

dirty, but works for now, hope it helps.

**Comment by KFishner** [comment]
@jedineeper thanks for digging into this and @leg100 thanks for the details you provided. We've been able to diagnose the issue and are working on a fix! 

**The problem:**
On our side, the artifact lookup order is creating issues. In the artifact lookup logic we filter based on version first. So if you have an artifact with multiple types (vagrant.box, aws.ami, googlecompute, etc), and those are at different versions, it's possible we pull the latest version of `vagrant.box` at 20, and then when the lookup tries to find an `aws.ami` type at version 20, it cannot be found because it doesnt exist. 

**The solution:**
Reverse the lookup order. The type and metadata filters should happen first, so we grab all the artifacts of type `aws.ami`, and then grab the latest version of that.

**Comment by leg100** [comment]
Thanks @KFishner 

@jedineeper Thanks for the workaround for #732, however that doesn't work for us. Like @armon said in his comment, the validation is overly aggressive, and we can't run `plan`, `apply` nor `destroy`! We have to delete all AWS resources and start again.

**Comment by KFishner** [comment]
@leg100 you shouldn't need to delete all AWS resources. Until we fix the lookup order, all you need to do is set version manually rather than to latest. Once the lookup order is correct, you can go back to setting version to latest and it should be all good!

**Comment by KFishner** [comment]
@jedineeper @leg100 thanks for your help here! We updated the artifact lookup order in Atlas, so these issues should be resolved.
