### ISSUE TITLE
AWS KMS High Availability 

### ISSUE THREAD

**Issue by weyderfs** [hashicorp/terraform#29050]
### About
I'm looking at [Registry documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_key) of the AWS Provider and not found a feature about _Regionality (multi-region)_, to _deploy_ or _manage_ KMS Keys.

### Provider
- AWS
### Current Terraform Version
- `Terraform v0.14.11`

### Use-cases
The idea here it's possible manage AWS KMS Keys with Regionality using the Terraform.
### Attempted Solutions
I guess that not possible try running something.

### References
- [AWS KMS docs](https://aws.amazon.com/kms/features/#Scalability.2C_Durability.2C_and_High_Availability)

**Comment by apparentlymart** [comment]
Hi @weyderfs,

This seems to be a feature request for the AWS provider, so the better place to record it would be in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws). This repository only contains Terraform Core, so I'm going to close this. Thanks!
