### ISSUE TITLE
add data disk to aks node pool

### ISSUE THREAD

**Issue by themonaminor** [hashicorp/terraform#29057]
i am trying to add data disk to aks node pool, but did not found any way to do that.
is there a way to attach the data disk to aks node pool using terraform

**Comment by jbardin** [comment]
Hi,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
