### ISSUE TITLE
Store providers/plugins in central location

### ISSUE THREAD

**Issue by archoversight** [hashicorp/terraform#29062]
### Current Terraform Version

```
% terraform  --version
Terraform v1.0.1
on darwin_amd64
```

### Use-cases

I am currently using terraform to manage multiple different environments, and within each environment we use a layered approach to reduce foot cannons. This however means that within a single environment I have up to 3 different copies of `.terraform` with the exact same binaries in each of them.

Currently I have close to 12 GiB of `.terraform` folders for managing ~10 environments.

I would love to have these stored centrally in `~/.config/terraform/{providers,plugins}` somewhere so they could get re-used as much as possible, and reduce the cost of storing multiple `.terraform` folders.

### Attempted Solutions

Nothing attempted yet

### Proposal

Store providers/plugins in a central place and reference them so that if the user is using terraform in multiple directories they don't store almost a gigabyte of more of binaries for each terraform init.

**Comment by archoversight** [comment]
```
% du -sh .terraform
1.4G	.terraform
% find .terraform -depth 4
.terraform/plugins/registry.terraform.io/hashicorp/archive
.terraform/plugins/registry.terraform.io/hashicorp/time
.terraform/plugins/registry.terraform.io/hashicorp/local
.terraform/plugins/registry.terraform.io/hashicorp/null
.terraform/plugins/registry.terraform.io/hashicorp/http
.terraform/plugins/registry.terraform.io/hashicorp/aws
.terraform/plugins/registry.terraform.io/hashicorp/random
.terraform/providers/registry.terraform.io/gavinbunney/kubectl
.terraform/providers/registry.terraform.io/hashicorp/archive
.terraform/providers/registry.terraform.io/hashicorp/template
.terraform/providers/registry.terraform.io/hashicorp/time
.terraform/providers/registry.terraform.io/hashicorp/local
.terraform/providers/registry.terraform.io/hashicorp/null
.terraform/providers/registry.terraform.io/hashicorp/http
.terraform/providers/registry.terraform.io/hashicorp/aws
.terraform/providers/registry.terraform.io/hashicorp/external
.terraform/providers/registry.terraform.io/hashicorp/random
.terraform/providers/registry.terraform.io/hashicorp/kubernetes
.terraform/providers/registry.terraform.io/hashicorp/helm
.terraform/providers/registry.terraform.io/hashicorp/cloudinit
```

**Comment by apparentlymart** [comment]
Hi @archoversight! Thanks for sharing this use-case.

Have you tried enabling [the plugin cache](https://www.terraform.io/docs/cli/config/config-file.html#provider-plugin-cache)? It's not exactly what you're asking for here but you mentioned that your primary concern is how much disk space the plugins take and so the plugin cache might well address that for you if your Terraform configurations live in a location where Terraform would be able to create symlinks from the directory-specific cache to the global cache, instead of copying the files into place.

**Comment by crw** [comment]
Hi @archoversight, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
