### ISSUE TITLE
Error: Provider produced inconsistent final plan while redploying the terraform code

### ISSUE THREAD

**Issue by Sandy414** [hashicorp/terraform#29065]
Hi team,

We are getting the below error while deploying the code to already existing stack:

Error: Provider produced inconsistent final plan

When expanding the plan for
module.targettrackingscalingUI.aws_autoscaling_policy.somepolicy[0] to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .cooldown: was cty.NumberIntVal(0), but now
null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.targettrackingscalingUI.aws_autoscaling_policy.somepolicy[0] to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .id: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.targettrackingscalingUI.aws_autoscaling_policy.somepolicy[0] to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .arn: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.targettrackingscalingUI.aws_autoscaling_policy.somepolicy[0] to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .autoscaling_group_name: was
cty.StringVal("br-bpsusrunbooksbx-rbg-ui-lafwROwX-ASG-6IWOBB1WDE5W"), but now
cty.StringVal("br-bpsusrunbooksbx-rbg-ui-lafwROwX-ASG-QG237F2BM069").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.targettrackingscalingUI.aws_autoscaling_policy.somepolicy[0] to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .scaling_adjustment: was
cty.NumberIntVal(0), but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.targettrackingscalingUI.aws_autoscaling_policy.somepolicy[0] to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for
.target_tracking_configuration[0].predefined_metric_specification[0].resource_label:
was cty.StringVal(""), but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.targettrackingscaling.aws_autoscaling_policy.somepolicy3[0] to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
changed the planned action from Update to DeleteThenCreate.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by apparentlymart** [comment]
Hi @Sandy414,

This error message seems to suggest a bug in the AWS provider rather than in Terraform Core. However, if you suspect it's a bug in Terraform Core rather than in the AWS provider then it would help to see all of the information we request in [our bug report template](https://raw.githubusercontent.com/hashicorp/terraform/main/.github/ISSUE_TEMPLATE/bug_report.md) so that we can understand where this issue originated.

In particular for this issue, it'd be important to see the full trace log, as described under "Debug Output" in the issue template, in order to understand where these inconsistent values originated.

Thanks!

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
