### ISSUE TITLE
Terraform Registry Stuck Publishing Provider

### ISSUE THREAD

**Issue by mcalhoun** [hashicorp/terraform#29073]
It appears that the Terraform Registry is stuck publishing our [cloudposse/awsutils](https://registry.terraform.io/providers/cloudposse/awsutils?pollNotifications=true) provider for the first time. 

It shows as published in our dashboard but just shows a spinner when trying to go to its page on the registry. It also cannot be found via search, etc.

cc: @osterman

**Comment by osterman** [comment]
Additional context:

Repository shows as published:

![CleanShot 2021-06-30 at 16 23 36](https://user-images.githubusercontent.com/52489/124033455-92cfb980-d9bf-11eb-8aed-44411eef9c00.png)

But it's not publicly available.

![CleanShot 2021-06-30 at 16 23 36](https://user-images.githubusercontent.com/52489/124033472-995e3100-d9bf-11eb-83c6-ed396e56241d.png)

**Comment by apparentlymart** [comment]
Hi @mcalhoun! Thanks for reporting this.

This repository is monitored only by the folks who work on Terraform CLI/Core and not the team that maintains Terraform Registry, so I'm going to close thise but I'd suggest sending this note to terraform-registry@hashicorp.com, which is the email address the team asked us to refer folks to when they have feedback about Terraform Registry, so they can track the requests in their own (not open source) repository. Thanks!
