### ISSUE TITLE
Terraform can't run remote-exec while normal SSH works as expected

### ISSUE THREAD

**Issue by AliSajid** [hashicorp/terraform#29082]
### Terraform Version

```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.47.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```tf
data "template_file" "user_data" {
  template = file("user-init.yml")
  vars = {
    public_key_string = file("${var.ssh_public_key}")
  }
}

resource "aws_security_group" "ssh_access" {
  name        = "ssh_access"
  description = "Standard SSH Access for the instance"

  ingress {
    from_port        = 22
    to_port          = 22
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  ingress {
    from_port        = 80
    to_port          = 80
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = -1
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}

resource "aws_instance" "streamer" {
  ami             = var.instance_ami_id
  instance_type   = "t3.micro"
  key_name        = "streamer_key_pair"
  user_data       = data.template_file.user_data.rendered
  security_groups = [aws_security_group.ssh_access.name]
  depends_on      = [aws_security_group.ssh_access]
  tags = {
    Name = "BBV-Streamer"
  }

  root_block_device {
    volume_size = 12
    tags = {
      Name = "Streamer-Root-Volume"
    }
  }

  ebs_block_device {
    device_name = "/dev/xvdf"
    volume_size = 20
    tags = {
      Name = "Streamer-Data-Volume"
    }
  }

}

resource "aws_eip" "streamer_ip" {
  instance = aws_instance.streamer.id
}

resource "aws_key_pair" "streamer_key_pair" {
  key_name   = "streamer_key_pair"
  public_key = file("${var.ssh_public_key}")
}

data "aws_route53_zone" "banseljaj" {
  name = "banseljaj.com."
}

resource "aws_route53_record" "streamproxy" {
  zone_id = data.aws_route53_zone.banseljaj.zone_id
  name    = "streamproxy.banseljaj.com"
  type    = "A"
  ttl     = "300"
  records = [aws_eip.streamer_ip.public_ip]
}

resource "null_resource" "ansible_provision" {

  connection {
    host        = aws_route53_record.streamproxy.name
    type        = "ssh"
    user        = "fedora"
    agent       = false
    private_key = file("${var.private_key_path}")
  }

  provisioner "remote-exec" {
    inline = ["echo 'Instance is Up'"]
  }

  provisioner "local-exec" {
    command = "ansible-playbook -i '${aws_instance.streamer.public_ip},' --private-key ${var.private_key_path} ansible/site.yml"
  }

  depends_on = [aws_route53_record.streamproxy]
}

```

### Debug Output

Debug output here: https://gist.github.com/bf59aa548be91936f5301add7c9e8863
### Expected Behavior

Successful execution

### Actual Behavior

Failure of last resource creation

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`

### Important Factoids

* This only happens in terraform. I am able to connect to the instance by simple ssh easily.

* I have also suspected a host key checking issue and tried to connect beforehand but it still fails.
* I was able to remove the `remote-exec` block and run a `local-exec` block with my ansible script. That ran and co pleted successfully

**Comment by jbardin** [comment]
Hi @AliSajid,

Thanks for filing the issue. I suspect you are running into a similar issue to #27768, triggered by stricter ssh configuration settings in the newer fedora images. Can you confirm in the server logs the reason for the connection failures?

**Comment by AliSajid** [comment]
Hi @jbardin. Thank you for responding.

I tried a fresh run of terraform to capture the _sshd_ and _audit_ logs. They are available here: https://gist.github.com/AliSajid/f136ee1072cb02a923c1d64294070359

The key thing is that in the `audit.log` I see the following line:

```
Jul 07 02:27:48 ip-172-31-20-231.us-east-2.compute.internal audit[717]: USER_LOGIN pid=717 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login acct="fedora" exe="/usr/sbin/sshd" hostname=? addr=[redacted] terminal=ssh res=failed'
```

This is similar to the problem reported in #27768. In addition, the `sshd.log` I see the following line:

```
Jul 07 02:27:48 ip-172-31-20-231.us-east-2.compute.internal sshd[717]: userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
Jul 07 02:27:48 ip-172-31-20-231.us-east-2.compute.internal sshd[717]: Connection closed by authenticating user fedora [redacted] port 61732 [preauth]
```

This makes me suspect that this is indeed the same issue.


As I am building this as a quick and dirty way to generate some necessary infrastructure, is it another distribution that I can try that won't have the problem? Fedora 33 has the same issue and I thought to ask you people first.

**Comment by AliSajid** [comment]
Just to report that I can run my original terraform script on a Fedora 32 instance successfully. It fails only for Fedora 33 and 34 which further leads credence to the golang issue. I hope it gets resolved soon.

**Comment by jbardin** [comment]
Thanks @AliSajid, the `key type ssh-rsa not in PubkeyAcceptedAlgorithms` message indicates that https://github.com/golang/go/issues/39885 is the issue here.

**Comment by jbardin** [comment]
Merging with #27768
