### ISSUE TITLE
Openstack load balancer vip address isn't computed

### ISSUE THREAD

**Issue by brianvans** [hashicorp/terraform#2908]
I'm having trouble understanding the behavior of openstack_lb_vip_v1 when the address parameter isn't defined.  I'm running terraform 0.6.1 against openstack juno.

Here's a test case:
```
resource "openstack_lb_vip_v1" "test_vip" {
  name = "test-vip"
  subnet_id = "123456"
  protocol = "TCP"
  port = 80
  pool_id = "78910"
}

output "vip_ip_address" {
  value = "${openstack_lb_vip_v1.test_vip.address}"
}
```
The `vip_ip_address` output will always be `""` in this case, even though in openstack it has an address.  With logging enabled, the `[DEBUG] Retreived OpenStack LB VIP` line will show the address, but it never gets consumed by terraform.

I can workaround this by removing the conditions bounding `d.Set("address", p.Address)` in `builtin/providers/openstack/resource_openstack_lb_vip_v1.go` around line 170, but that's probably not ideal for every use-case.

Any thoughts?

**Comment by lesaux** [comment]
I agree with your observations. I don't understand in what case it is relevant to set the vip address to an empty string. Maybe someone else can chime in?
It might also be relevant to set 
```
Computed: true
```
on this variable.

**Comment by jtopjian** [comment]
Hey guys, #3927 should fix this. If you're able to test it, I'd appreciate any feedback :smile:
