### ISSUE TITLE
terraform import for route53 not importing all records

### ISSUE THREAD

**Issue by jainpratik163** [hashicorp/terraform#29091]
### Terraform Version

```
Terraform v0.14.5
...
```

### Terraform Configuration Files

Below is tf file which we created 
```
resource "aws_route53_record" "this" {

}
resource "aws_route53_zone" "this" {

}
...
```
### Expected Behavior
It should only update the existing resources.
`Plan: 2 to add, 0 to change, 3 to destroy.`

### Actual Behavior
it is destorying the reasource 

### Steps to Reproduce

1. `terraform init`
2. `terraform import aws_route53_record.this <r53_id>_<r53>_SOA`
3. `terraform plan`

### Additional Context
we want to migrate our R53 into terraform for this we import command for importing r53 and state file created successfully but when we run ```terraform plan``` we see it is destroying existing resource and we are not getting why it is destroying the whole reasource.

**Comment by jbardin** [comment]
This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by jainpratik163** [comment]
thanks
