### ISSUE TITLE
ECS tasks don't inherit tags from service

### ISSUE THREAD

**Issue by deliaiuga23** [hashicorp/terraform#29098]
Hello, 

I noticed a weird behaviour in regards to tags attached to ECS resources.

I take care to tag all the taggable resources, and I did the same with my ECS ones.
The problem is, even though I set tags for the task definition and service, my actual tasks don't inherit these tags.

### Terraform Version

```
 v0.14.3
```

### Terraform Configuration Files

```terraform
ECS service for grafana:
resource "aws_ecs_service" "service_grafana" {
  name                   = "cluster_name"
  cluster                 = data.aws_ecs_cluster.selected.arn
  task_definition        = aws_ecs_task_definition.td_grafana.arn
  desired_count          = var.desired_count
  launch_type            = "FARGATE"
  platform_version       = "1.4.0"
  enable_execute_command = true

  network_configuration {
     ....
  }

  load_balancer {
     ...
  }

  tags       = var.tags
  depends_on = [aws_lb_target_group.tg_grafana]
}

ECS task definition for Grafana:
resource "aws_ecs_task_definition" "td_grafana" {
  family                   = format("%s_%s_%s", var.cluster_name, "td_grafana", var.env)
  network_mode             = "awsvpc"
  execution_role_arn       = var.ecs_task_execution_role_arn
  task_role_arn            = var.ecs_task_role_arn
  requires_compatibilities = ["FARGATE"]
  container_definitions    = data.template_file.grafana.rendered
  tags                     = var.tags
}

Both the service and task definition have tags attached.
```

### Expected Behavior

I was expecting that the spawned tasks will also have the tags attached.
### Actual Behavior

The tasks don't have tags attached.
### Steps to Reproduce

Apply the terraform script containing the ECS resources.

**Comment by apparentlymart** [comment]
Hi @deliaiuga23,

I think you're describing a behavior of the AWS provider rather than of Terraform itself. Please open this issue instead in [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws), so that the AWS provider maintainers can review it.

I don't think there's anything we could change in _this_ repository to address what you've described here, and so I'm going to close this. Thanks!

**Comment by deliaiuga23** [comment]
Hi, @apparentlymart 

Thanks for the hint :)  I will open the issue in the right repo.
