### ISSUE TITLE
Tainted resources do not consider create_before_destroy in ordering

### ISSUE THREAD

**Issue by mwagg** [hashicorp/terraform#2910]
I have an existing autoscaling launch configuration created by terraform for which I need to change the root block device volume size.

Contents of the .tf look like this.

```
resource "aws_launch_configuration" "some_launch_config" {
  image_id = "..."
  instance_type = "..."
  iam_instance_profile = "..."
  key_name = "..."
  security_groups = ["...","..."]

  lifecycle {
    create_before_destroy = true
  }

  root_block_device {
    volume_size = "${var.some_volume_size}"
  }
}
```

After changing the value of the some_volume_size variable the change does not seem to be recognized either when running plan or apply.

I have also tried replacing the variable with a hard coded value with the same result.

**Comment by stack72** [comment]
@catsby I think this is related to this bug that you had to fix before

https://github.com/hashicorp/terraform/pull/2735

I have just tried to change the volume type as well and still get no new resource

Paul

**Comment by xuwang** [comment]
This behavior mentioned on https://www.terraform.io/docs/providers/aws/r/launch_configuration.html
It says:

NOTE: Changes to *_block_device configuration of existing resources cannot currently be detected by Terraform. After updating to block device configuration, resource recreation can be manually triggered by using the taint command.

**Comment by catsby** [comment]
Hey @mwagg – thanks for writing in. As @xuwang points out, this is a documented limitation of Terraform at present. In order for Terraform to apply your changes, you'll need to `taint` the resource:

    $ terraform taint aws_launch_configuration.some_launch_config

That will force Terraform to re-create the resource. 

Thanks @xuwang for the reply :smile:

**Comment by xuwang** [comment]
Note:
```
$ terraform taint aws_launch_configuration.some_launch_config
$ terraform apply
```
will not work with the CBD and auto-generated lc name ( i.e. name arg is not given):

```
...
2 error(s) occurred:
* ResourceInUse: Cannot delete launch configuration terraform-ux2fghrxjfcsnatw3ssuxwfxty because it is attached to AutoScalingGroup some_sg
	status code: 400, request id: [d1a29c29-3fba-11e5-a4e1-0153f2881c49]
* Resource 'aws_launch_configuration.some_launch_config' does not have attribute 'name' for variable 'aws_launch_configuration.some_launch_config.name'
```

Looks like there is a bug after all.

As a workaround, you need to manually assign a new name to lc before apply.

**Comment by semarj** [comment]
@catsby @phinze Should someone reopen this bug?  Tainting an attached launch config gives me the same error he mentions above.

**Comment by phinze** [comment]
> it seems that taint does not respect create before delete?

Yeah that's an interesting point. Currently the "tainted" concept is equivalent to "this resource is no good, clean it up when you can", but with specific resource relationships like LC/ASG, a stricter ordering is required.

Reopening, renaming, and tagging w/ thinking.

**Comment by joslynesser** [comment]
Ran into this as well with `create_before_destroy` EC2 instances that become tainted from a failed provisioning run. 

For now, we're working around by performing 2 runs of apply after resources become tainted. After the ec2 instance is tainted, the next apply ends up performing a destroy, but no create. The second run ends up with a creation. However, this workaround isn't what we'd expect with `create_before_destroy`. We'd expect to see creation before destruction.

**Comment by cu12** [comment]
+1 for this, just ran into the same issue.

I updated my SSH keys and since TF didn't detect the change, I tainted the necessary LC/ASG resources and hit the same issue as @xuwang. I'm also having `create_before_destroy` around these resources.

```
Error applying plan:

1 error(s) occurred:

* ResourceInUse: Cannot delete launch configuration apigateway-bfyo4sqhnvhkddh3ahnkpu6t3a because it is attached to AutoScalingGroup apigateway - apigateway-bfyo4sqhnvhkddh3ahnkpu6t3a
	status code: 400, request id: 0fcc53a1-a6f7-11e5-9f8d-ed7adf6c6ae5
```

**Comment by ElliotG** [comment]
+1 also having this. Having difficulty working around.

**Comment by marceldegraaf** [comment]
Same issue here. I want to change the `volume_size` of the `ebs_block_device` in the launch configuration below from 512GB to 2048GB.

1. Update the `.tf.` file, and `terraform taint` the resource as per documentation
2. Run `terraform plan`
3. Observe Terraform plans to create a new launch configuration, and plans to update two auto scaling groups that use this launch configuration
4. Run `terraform apply`
5. Get an error: `ResourceInUse: Cannot delete launch configuration lc-production-es-xxxx because it is attached to AutoScalingGroup asg-production-elasticsearch-slave`

It seems to me that the `lifecycle` rule on the launch configuration should specifically deal with creating the new resource before destroying the old one.

The output of `terraform apply` doesn't include a line for creating a new launch configuration. After refreshing all states it immediately tries to destroy the current launch configuration, which is obviously not possible.

Using Terraform v.0.6.9.

**Launch configuration**:
```
resource "aws_launch_configuration" "lc_production_elasticsearch" {
  name_prefix = "lc-production-es-"
  image_id = "${var.production_base_ami}"
  ...

  ebs_block_device {
    device_name = "/dev/sdb"
    volume_type = "gp2"
    volume_size = 2048
    delete_on_termination = false
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

**Auto scaling group** (there are two, a `master` and a `slave`. They are identical except for the EC2 tags and the min/max/desired counts):
```
resource "aws_autoscaling_group" "asg_production_elasticsearch_master" {
  name = "asg-production-elasticsearch-master"
  launch_configuration = "${aws_launch_configuration.lc_production_elasticsearch.name}"
  ...

  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by marceldegraaf** [comment]
@phinze @catsby any updates on this? This is basically blocking me from making _any_ changes with Terraform now, as every `terraform apply` crashes on the `ResourceInUse` error.

**Comment by eedwardsdisco** [comment]
Just ran into this today with an aws autoscaling group.

I wanted to test the create_before_destroy behavior along with ELB based 'wait for min capacity' stuff, and thought I should be able to terraform taint the autoscaling group and have it 'create before destroy'.

It then proceeded to destroy it immediately.

/cry

```
aws_autoscaling_group.autoscaling_group: Destroying...
aws_autoscaling_group.autoscaling_group: Creating...
```

**Comment by bigkraig** [comment]
Ran into this today. What do people do if they want to refresh the nodes behind their ELB? One would assume you could taint the LC or the ASG and apply, but that will cause an outage.

**Comment by jseaidou** [comment]
Hey guys, this seems to also be a issue with openstack as well.

**Comment by br0ch0n** [comment]
@phinze out of curiosity why isn't ebs_block_device just set to ForceNew: true like everything else in resource_aws_launch_configuration.go?  I see things like
```
"attributes": {
                            "associate_public_ip_address": "false",
                            "ebs_block_device.#": "0",
                            "ebs_optimized": "false",
                            "enable_monitoring": "true",
                            "ephemeral_block_device.#": "0",
                             "instance_type": "m4.2xlarge",
                            "name": "super-servers-abcdefg123456",
                            "name_prefix": "super-servers-",
                            "root_block_device.#": "1",
                            "root_block_device.0.delete_on_termination": "true",
                            "root_block_device.0.iops": "0",
                            "root_block_device.0.volume_size": "250",
                            "root_block_device.0.volume_type": "gp2",

```

inside the tfstate so presumably the info is available to diff against?  I could've sworn this used to work fine without tainting but maybe I was always changing root disk size and instance type together thus masking the issue.
