### ISSUE TITLE
Confusing behaviour of terraform validate command

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform#29105]
### Terraform Version

```
→ terraform version
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.48.0
```

### Terraform Configuration Files

See: [tf.zip](https://github.com/hashicorp/terraform/files/6770797/tf.zip)

### Expected Behavior
Running `terraform init && terraform validate` in `environments/dev` and in `modules/foo` should be either successful or yield warnings / errors consistently.

#### Approach 1
1. Running `(cd tf1/environments/dev/ && terraform init && terraform validate)` is successful and generates no warnings.
2. Running `(cd tf1/modules/foo && terraform init && terraform validate)` fails with following error message:
```
Error: missing provider provider["registry.terraform.io/hashicorp/aws"].us-east-1
```

#### Approach 2
3. Running `(cd tf2/environments/dev/ && terraform init && terraform validate)` is successful, but generates a warning:
```
Warning: Empty provider configuration blocks are not required
│
│   on ../../modules/foo/main.tf line 12:
│   12: provider "aws" { alias = "us-east-1" }
│
│ Remove the aws.us-east-1 provider block from module.foo.
```
4. Running `(cd tf2/modules/foo && terraform init && terraform validate)` is successful and generates no warnings.

### Steps to Reproduce
1. Unzip the [tf.zip](https://github.com/hashicorp/terraform/files/6770797/tf.zip) archive
2. Follow the steps mentioned in _"Actual Behaviour"_.

### Additional Context
The attached simple terraform templates show an example where an aliased terraform provider is passed from "environment" template, to module, and then to another, nested, module. In this scenario it seems it's not possible to get a clean `terraform validate` log, because - depending on the configuration - we either get a warning, or an error.

The only difference between `tf1` and `tf2` folders is that in `tf2/modules/foo/main.tf` we additionally have the `provider` block like so:
```
provider "aws" { alias = "us-east-1" }
```

This - according to the warning message in pt. 3 above - should not be required. If, however, I remove it, I get the error message as in pt. 2. 

This seems like a bug or a contradicting validation rules in the `terraform validate` command, but I may also be doing something wrong in the template configuration. This setup is not new. We've had it since 0.12.x with explicit `provider "aws" { alias = ... }"` blocks, and now it started generating warnings so I attempted to clean this up, but to no avail.

**Comment by jbardin** [comment]
Hi @mkielar, thanks for filing the issue. While this is a slightly different error message, the underlying issue is the same as #29042. Modules which require providers to be supplied externally cannot be used as a root module, and therefor running `validate` from within the same directory is going to fail since the providers cannot be correctly configured.
