### ISSUE TITLE
Terraform destroy not working without two init 

### ISSUE THREAD

**Issue by vdahmane** [hashicorp/terraform#29103]
### Terraform Version

```terraform
Terraform v0.14.11
```

### Crash Output

```terraform
Error: Could not load plugin
Plugin reinitialization required. Please run "terraform init".
Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.
Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".
5 problems:
- Failed to instantiate provider "registry.terraform.io/datadog/datadog" to
obtain schema: unknown provider "registry.terraform.io/datadog/datadog"
- Failed to instantiate provider "registry.terraform.io/hashicorp/aws" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/aws"
- Failed to instantiate provider "registry.terraform.io/hashicorp/helm" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/helm"
- Failed to instantiate provider "registry.terraform.io/hashicorp/template" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/template"
- Failed to instantiate provider "registry.terraform.io/hashicorp/dns" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/dns
```
### Actual Behavior

When i run terraform destroy i have the mentionned crash output. If i run `terraform init` twice the issue does not happen
I have no issue with `terraform plan` or `terraform apply` run

### Steps to Reproduce

1. `terraform init`
2. `terraform destroy`

It's working with
1. `terraform init`
2. `terraform init`
3. `terraform destroy`

### Additional Context

Terraform running in gitlab-ci pipeline jobs.

**Comment by jbardin** [comment]
Hi @vdahmane,

Thanks for filing the issue. We are no longer actively developing the 0.14 version of terraform, and there have been many changes released since. Can you replicate the problem with the 1.0 series of terraform? 

If the problem exists in a current release, it would help to have a configuration from which to start with so that we can reproduce the same issue.

Thanks!
