### ISSUE TITLE
Allow AWS LaunchConfiguration auto-generated name with a user defined prefix

### ISSUE THREAD

**Issue by xuwang** [hashicorp/terraform#2911]
Terraform auto generated lc name is a nice feature combined with CBD to allow lc update.  It currently 
generates a lc name *terraform-`<uniqueid`>*. 

It would be very helpful to allow a user defined prefix, for example, *etcd-cluster-`<uniqueid`>*.
I would think to add a  _name_prefix_  attribute, or _auto_name_versioning_ flag so that the lc name will be used as the prefix.

**Comment by xueshanf** [comment]
+1
It'd be useful to query launch configuration based on a specific prefix in lc name.

**Comment by ericfode** [comment]
+1

**Comment by pforman** [comment]
+1, this would be really nice to have given that the dependency cycle issues in LC vs ASG effectively require auto-generated names.

**Comment by ericfode** [comment]
+1

**Comment by freeman** [comment]
+1

**Comment by nathanpalmer** [comment]
Yes agree. I just ran into an issue where we need to use `create_before_destroy` but it can't be done while we're explicitly naming the resource. I'd like to at-least have some sort of prefix or a variable that I can use that includes an autogenerated id

**Comment by CpuID** [comment]
+1, definitely would be nice for identification purposes.

**Comment by mrfoobar1** [comment]
+1, you can't delete the LC if it's being used with an AS.

**Comment by catsby** [comment]
Hey all – thanks for opening the issue. @pforman  graciously added this in #3802 and I just merged it.
