### ISSUE TITLE
tf-0.15+: Backend re-initialisation no longer possible

### ISSUE THREAD

**Issue by stuart-shelton-contino** [hashicorp/terraform#29118]
From at least terraform-11.x to terraform-0.14.x, it was possible to change the state-file Terraform used from within a pipeline by following a process which simplifies to:

```
terraform init -backend-config 'key=old_key'
terraform state pull > local_file
terraform init --backend-config 'key=new_key'
terraform state push - < local-file
```

However, from terraform-0.15.x this now results - when executed with state stored in an AWS S3 bucket - in one of two errors:

```
Error refreshing state: state data in S3 does not have the expected content.
This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
to manually verify the remote state and update the Digest value stored in the
DynamoDB table to the following value: 
```

(... noting that no Digest value is provided - the output stops at this point)

Or:

```
Initializing the backend...
Backend configuration changed!
Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.
╷
│ Error: Error loading state:
│     state data in S3 does not have the expected content.
│ 
│ This may be caused by unusually long delays in S3 processing a previous state
│ update.  Please wait for a minute or two and try again. If this problem
│ persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
│ to manually verify the remote state and update the Digest value stored in the
│ DynamoDB table to the following value: 
│ 
│ 
│ Terraform failed to load the default state from the "s3" backend.
│ State migration cannot occur unless the state can be loaded. Backend
│ modification and state migration has been aborted. The state in both the
│ source and the destination remain unmodified. Please resolve the
│ above error and try again.
│ 
│ 
╵
```

... and this is consistent no matter which of the `-reconfigure`, `-migrate-state`, `-force-copy` and/or `-ignore-remote-version` flags are also passed.

Even if these options allow for a newer/simpler method of state-migration, it would be a significant benefit to still be able to follow the original process for compatibility.

It also feels like a bug that none of the command-line options allow terraform-0.15+ to complete this process without generating an error.

### Terraform Version

```
0.15.0 to 1.0.2 (output included above from 1.0.2)
```

### Expected Behavior

All versions of terraform should be able to reconfigure the active back-end and pull/push local state.

Referenced 'Digest value' should be present.

More details of the 'expected content' should be provided to aid with debugging.

### Actual Behavior

As above, terraform-0.15+ fail with an error no matter what command-line arguments are passed.

'Digest value' is missing.

'Error refreshing state: state data in S3 does not have the expected content' provides little actionable information on what the expected content was, what was found, and why this is a problem or how it can be resolved.

### Steps to Reproduce

```
terraform init -backend-config 'key=old_key'
terraform state pull > local_file
terraform init --backend-config 'key=new_key'
terraform state push - < local-file
```

### Additional Context

This comes from an optional CI/CD pipeline stage which allows projects to migrate from legacy tfstate S3 filenames to standards-compliant replacements without manual intervention.

**Comment by jbardin** [comment]
Hi @stuart-shelton-contino,

There seems to be a couple different issues colliding here, so I'm not sure exactly what might be the actual problem. Let's start with the reconfiguration of the backend, which can be done automatically or manually using the `-reconfigure` flag.

If you need to initialize the backend config, then change it while moving the state without interactive prompts, you can do the following:

```
terraform init -backend-config 'key=old_key'
terraform init -backend-config 'key=new_key' -force-copy
```

If you want to manually reconfigure the backend as you were attempting here, you need to add the `-reconfigure` flag:

```
terraform init -backend-config 'key=old_key'
terraform state pull > local_file
terraform init -reconfigure -backend-config 'key=new_key'
terraform state push - < local_file
```

The `state data in S3 does not have the expected content` error you've shown is unrelated to the usage of `init`, that is the checksum verification done within the s3 remote state itself. I'm not sure how you are arriving at this without something changing the state data outside of terraform. My first guess is that you have multiple configurations, one with a `dynamodb_table` defined, and one without, causing the state to be updated without updating the checksum info. Creating a standalone reproduction of the issue will likely point out where the inconsistency is arising, but if not we can use that here for further troubleshooting. 

Thanks!

**Comment by jbardin** [comment]
Closing for now as we have not heard back. If you have any more information feel free to update this thread, or if you have more questions, you can use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
