### ISSUE TITLE
Support for new id field in aws_security_group_rule

### ISSUE THREAD

**Issue by adrianwright** [hashicorp/terraform#29129]
### Current Terraform Version
1.0.1

### Use-cases
Importing security groups by ID. AWS recently released the security group rule ID, which vastly simplifies working with security group rules in the CLI. Support for security group rule ID when importing `aws_security_group_rule` resources would make imports much simpler for the developer. Additionally, it would provide an easier mechanism for mapping AWS resources to Terraform state.

### Attempted Solutions
The import function for `aws_security_group` rule requires specifying several data elements. From the documentation: "Security Group Rules can be imported using the `security_group_id`, `type`, `protocol`, `from_port`, `to_port`, and source(s)/destination(s) (e.g. `cidr_block`) separated by underscores (_). All parts are required." This works, but it is cumbersome.

### Proposal
- Add a new exported field `id` to `aws_security_group_rule` that contains the security group rule id. Use this field to map the AWS resource to the terraform resource in the state file.
- Allow imports to occur using the security group rule ID, such as "$ terraform import aws_security_group_rule.ingress sgr-abcdefghi01234561"

### References
https://aws.amazon.com/blogs/aws/easily-manage-security-group-rules-with-the-new-security-group-rule-id/

**Comment by jbardin** [comment]
This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by adrianwright** [comment]
Got it, thanks!
