### ISSUE TITLE
ecs_cluster isn't preserving desired_count on update/recreation

### ISSUE THREAD

**Issue by samuelkdavis-mccarthyfinch** [hashicorp/terraform#29141]
### Use-cases
When updating aws_autoscaling_group, the desired_capacity isn't preserved when the resource needs to be deleted/created as part of the any change. This means that every time ecs is deployed, the ec2 agents are scaled in.

### Attempted Solutions
jugging with counts, commenting out desired_capacity, setting ignore_changes, etc

### Proposal
the desired_count field should be preserved across deployments.

### References
I was asked to re-post this from the terraform-provider-aws repo https://github.com/hashicorp/terraform-provider-aws/issues/20110

**Comment by jbardin** [comment]
Hi @samuelkdavis-mccarthyfinch,

Thanks for filing the issue. Going on the example you posted in the linked issue. Since you have an issue open with the provider already, I'm going to close this, and will reply over there where there's some more context.
