### ISSUE TITLE
Unable to create Databricks workspace with environment based restriction!

### ISSUE THREAD

**Issue by mahmood2103015** [hashicorp/terraform#29144]
* A short example can be directly copy-pasteable; longer examples should be in separate git repositories, especially if multiple files are needed
* Please include all needed context. For example, if you figured out that an expression can cause a crash, put the expression in a variable definition or a resource
* Set defaults on (or omit) any variables. The person reproducing it should not need to invent variable settings
* If multiple steps are required, such as running terraform twice, consider scripting it in a simple shell script. For example, see [this case](https://github.com/danieldreier/terraform-issue-reproductions/tree/master/25719). Providing a script can be easier than explaining what changes to make to the config between runs.
* Omit any unneeded complexity: remove variables, conditional statements, functions, modules, providers, and resources that are not needed to trigger the bug
* When possible, use the [null resource](https://www.terraform.io/docs/providers/null/resource.html) provider rather than a real provider in order to minimize external dependencies. We know this isn't always feasible. The Terraform Core team doesn't have deep domain knowledge in every provider, or access to every cloud platform for reproduction cases.

-->

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output

Hi ,
Added condition in Databricks resource as below :

resource “azurerm_databricks_workspace” “cropdbr” {
count = var.environment == “dev” ? 0 : 1
name = “ 
v
a
r
.
p
r
e
f
i
x
−
c
r
o
p
−
d
b
r
−
 {var.environment}”
resource_group_name = azurerm_resource_group.RG.name
location = azurerm_resource_group.RG.location
sku = “premium”
managed_resource_group_name = “DATABRICKS_ 
l
o
c
a
l
.
p
r
e
f
i
x
u
p
p
e
r
∗
C
R
R
G
∗
 {local.environment_upper}”

custom_parameters {
public_subnet_name = azurerm_subnet.pubcrsubnet.name
private_subnet_name = azurerm_subnet.prvcrsubnet.name
virtual_network_id = azurerm_virtual_network.crvnet.id
no_public_ip = var.environment != “dev” ? true : false
}

tags = {
SGI_Country = var.country
SGI_Region = var.location
}
}

provider "databricks" {
  alias = "crop"
  azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1].id
}
Still i am unable to read Databricks workspace ID .
Error: Invalid index

on provider.tf line 28, in provider “databricks”:
28: azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1].id
azurerm_databricks_workspace.cropdbr is tuple with 1 element

The given key does not identify an element in this collection value.
--->

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
