### ISSUE TITLE
NAT Gateway

### ISSUE THREAD

**Issue by Divyanshutomar27** [hashicorp/terraform#29140]
Hi Team,

I am getting below error in nat gateway, please advise. 

![image](https://user-images.githubusercontent.com/36529072/125195509-8f67e800-e273-11eb-822a-5810e01511af.png)

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
