### ISSUE TITLE
State file version and output version mismatch

### ISSUE THREAD

**Issue by akfroman** [hashicorp/terraform#29152]
### Terraform Version

```
1.0.3 and 0.13.7
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
  backend "s3" {}
}
provider "aws" {
  region = "us-east-1"
  assume_role {
    role_arn     = <redacted role>
    session_name = <redacted session>
  }
}
```

### Expected Behavior

Either Terraform 1.0 should init successfully or terraform 0.13 should init so I can upgrade the state

### Actual Behavior

When I run `terraform init` with 0.13, I get the below error:
```
Error refreshing state: state snapshot was created by Terraform v1.0.2, which is newer than current v0.13.7; upgrade to Terraform v1.0.2 or greater to work with this state
```
But when I run `terraform init` with 1.0, I get this error:
```
╷
│ Error: Invalid legacy provider address
│
│ This configuration or its associated state refers to the unqualified provider "aws".
│
│ You must complete the Terraform 0.13 upgrade process before upgrading to later versions.
╵
```
### Steps to Reproduce

I have renamed the 0.13.7 exe to `terraform13.exe` and 1.0.3 is just `terraform.exe` and both are added to PATH, so I run the 2 commands below depending on what version I'm trying:
```
terraform init
terraform13 init
```
### Additional Context

This terraform and subsequent state file were created before 0.13 and we forgot to update it post 0.13. This terraform is usually run in a Jenkins Pipeline. The problem is our Jenkins agent is running Terraform 1.0.3 and I tried to run this pipeline for the first time in over a year, not realizing it still needed to be updated to 0.13. Somehow the statefile got updated to 1.0.3 even though I have never gotten 1.0.3 to even run a plan. The code block in the configuration section is what I have changed it to, so the "Terraform 0.13 upgrade process" should be complete. I am troubleshooting this locally rather than our pipeline and I have tried deleting the `.terraform` folder as part of my troubleshooting steps.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
