### ISSUE TITLE
Local modules cannot be found during AZ DevOps pipelines execution

### ISSUE THREAD

**Issue by cerrakoth** [hashicorp/terraform#29168]
Hello

I am executing a deployment via Terraform and have run into an issue when trying to call local modules but only when executing via pipeline. The deployment is intended to deploy resources to Azure and works successfully when executed via the azure CLI but fails with the following error when executed via a pipeline: 

```
2021-07-12T20:56:16.9400933Z ##[error]Terraform command 'init' failed with exit code '1'.
2021-07-12T20:56:16.9420461Z ##[error][31m[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mUnreadable module directory[0m
[31m│[0m [0m
[31m│[0m [0m[0mUnable to evaluate directory symlink: CreateFile modules: The system cannot
[31m│[0m [0mfind the file specified.
```
I've attempted to run the deployment using self hosted run times as well as DevOps hosted Windows and Ubuntu images and have tried multiple versions

### Terraform Version

```
V1.0.2 (have tried several older versions as well)
```

### Terraform Configuration Files

```terraform

module "ResourceGroups" {
    source = "./modules/resourcegroups"
    rgname = "rg1"
}
```
Directory structure:

Terraform
 --modules
 ----resourcegroups
  main.tf
  others...

### Debug Output

https://gist.github.com/cerrakoth/855f7a037b8786539f37035694e05cda

### Expected Behavior

When running Terraform deployment via azure CLI, I am able to init, plan and apply without issue. The module directory is read successfully and the referenced modules are able to be used by the other resources. This should be repeated when executing via an Azure DevOps pipeline

### Actual Behavior

The deployment fails on the terraform init stage due to not being able to read the local module directory

### Steps to Reproduce

Create a new deployment where main.tf references a local module directory and attempt to call it.

### Additional Context

Have attempted to execute using a self hosted run time as well as the Azure DevOps provided Windows Server 2019 and Ubuntu 20.04 runtimes.

### References
<!--
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

**Comment by jbardin** [comment]
Hi,

We use GitHub issues for tracking bugs and enhancements, rather than for questions, and is only monitored by a few core maintainers. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
