### ISSUE TITLE
Auto-import existing resources matching the configuration

### ISSUE THREAD

**Issue by jocutajar** [hashicorp/terraform#29160]
### Current Terraform Version
```
v0.14.5
```

### Use-cases
I have infrastructure code, but empty tfstate.
 * tfstate failed to update after creating resources
 * accidental loss of state
 * describing existing infrastructure with code

And I want to easily update my state from reality.

### Attempted Solutions

`terraform import` allows me to add specific resources, but I have to dig out all the configuration paths and IDs and run them in one by one. That is clumsy

`terraformer` would suck reality in and create a configuration. Not too useful since I already have the configuration.

### Proposal

When I run `terraform apply` with empty state and existing infrastructure, it actually tells me that a resource already exists. It seems like a tiny step to actually tell terraform - hey, if you find existing infrastructure, import it.

In fact, I've taken the error output from `terraform apply` and with a few text editing tricks was able to construct a list of `terraform import ...` commands. The only trouble with that was that the accurate configuration path was missing and I had to add a bit of that context.

For instance:

> Error: A resource with the ID "/subscriptions/xyz/resourceGroups/mygroup/providers/Microsoft.Network/virtualNetworks/mynet" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_network" for more information.
> 
>  on some/path/network.tf line 11, in resource "azurerm_virtual_network" "mynet":
>  11: resource "azurerm_virtual_network" "mynet" {

translates to:

```
terraform import module.base.azurerm_virtual_network.mynet "/subscriptions/xyz/resourceGroups/mygroup/providers/Microsoft.Network/virtualNetworks/mynet" 
```

Note that the only bit of information missing in the error message is the module path `module.base.`. Wouldn't terraform know it internally?

Now **imagine** if the output precisely identified the configuration path and the existing resource ID. I'd just put `terraform import ` in front of it and roll.

Example:

> Error: Cannot create resource **"module.base.azurerm_virtual_network.mynet"**: A resource with the ID **"/subscriptions/xyz/resourceGroups/mygroup/providers/Microsoft.Network/virtualNetworks/mynet"** already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_network" for more information.
> 
>  on some/path/network.tf line 11

Now **imagine** a command `terraform auto-import` that would run the internal checks for existing resources and interactively or automatically imported them into the state :)

Examples:
* `terraform auto-import` - interactively confirm each import
* `terraform auto-import --yes` - import all existing resources, don't ask
* `terraform auto-import module.base.azurerm_virtual_network.mynet` - import resource matching that specific configuration
* `terraform auto-import --yes 'module.base.*'` - import all existing resources defined in the base module, don't ask

**Comment by jbardin** [comment]
Hi @jocutajar,

Thanks for filing the issue. We are tracking the feature request for configuration driven import in #26364.

**Comment by jocutajar** [comment]
Please reopen, as it is not a duplicate of #26364. Or please explain how does that issue achieve autoimport as it is quite confusing.

**Comment by jbardin** [comment]
@jocutajar,

The solution as you've proposed it is not possible within terraform right now. Terraform is not able to detect if a resource exists, only the provider can determine this. The providers also currently have no way to indicate which attributes are the unique identifiers, so there would be no way for terraform to convert the configuration into an import request. Since the goal for both this and 26364 is to allow import via the configuration, and would be resolved by the same solution, we can track them in the same issue.
