### ISSUE TITLE
Unable to create Azure Stream Analytics job of hosting type 'edge'

### ISSUE THREAD

**Issue by sharigitpersonal** [hashicorp/terraform#29170]
I need to create Stream Analytics job resource in Azure using Terraform of hosting environment 'edge' so that I can have inputs from edgehub. 

Terraform version is 1.2
azurerm_version is 2.67.0

Error
│ Error: Unsupported argument│
│ on streamanalytics/main.tf line 35, in resource “azurerm_stream_analytics_job” “ixstream2”:
│ 35: jobType = "Edge"│
│ An argument named “jobType” is not expected here.

Code snippet:
#this is used to deploy the job to an IoT Gateway Edge device.
resource “azurerm_stream_analytics_job” “ixstream2” {
name = “ixstreamedgejob”
resource_group_name = var.stream_rg
location = var.location
compatibility_level = “1.1”
data_locale = “en-GB”
events_late_arrival_max_delay_in_seconds = 0
events_out_of_order_max_delay_in_seconds = 5
events_out_of_order_policy = “Adjust”
output_error_policy = “Stop”
streaming_units = 3
jobType = “Edge” ## this was added to make the job of type edge##
tags = {
environment = “test”
}

transformation_query = <<QUERY

QUERY
}

I don’t see any option in the terraform documentation to create this. Can someone shed some light on how can I create this resource so that input and output for this job can be ‘edgehub’.

Thanks,
Sunil

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
