### ISSUE TITLE
winrm : http error 401 although correct credential supplied

### ISSUE THREAD

**Issue by teewhey** [hashicorp/terraform#2918]
I was trying to do run a script remotely via remote-exec.
I'm very sure the credentials that I provided are correct and yet i'm getting http error: 401 

From terraform stdout : 
aws_instance.ec2crmapp (remote-exec): Connecting to remote host via WinRM...
aws_instance.ec2crmapp (remote-exec):   Host: 52.76.8.9
aws_instance.ec2crmapp (remote-exec):   Port: 5985
aws_instance.ec2crmapp (remote-exec):   User: DOMAIN\user
aws_instance.ec2crmapp (remote-exec):   Password: true
aws_instance.ec2crmapp (remote-exec):   HTTPS: false
aws_instance.ec2crmapp (remote-exec):   Insecure: false
aws_instance.ec2crmapp (remote-exec):   CACert: false

From TF-debug log:
2015/08/03 17:43:06 terraform-provisioner-remote-exec: 2015/08/03 17:43:06 connecting to remote shell using WinRM
2015/08/03 17:44:12 terraform-provisioner-remote-exec: 2015/08/03 17:44:12 connection error: unknown error Post http://52.76.8.9:5985/wsman: dial tcp 52.76.8.9:5985: connection refused
2015/08/03 17:44:12 terraform-provisioner-remote-exec: 2015/08/03 17:44:12 Retryable error: unknown error Post http://52.76.8.9:5985/wsman: dial tcp 52.76.8.9:5985: connection refused
2015/08/03 17:44:15 terraform-provisioner-remote-exec: 2015/08/03 17:44:15 connecting to remote shell using WinRM
2015/08/03 17:44:15 terraform-provisioner-remote-exec: 2015/08/03 17:44:15 connection error: http error: 401 -
2015/08/03 17:44:15 terraform-provisioner-remote-exec: 2015/08/03 17:44:15 Retryable error: http error: 401 -
2015/08/03 17:44:18 terraform-provisioner-remote-exec: 2015/08/03 17:44:18 connecting to remote shell using WinRM
2015/08/03 17:44:18 terraform-provisioner-remote-exec: 2015/08/03 17:44:18 connection error: http error: 401 -
2015/08/03 17:44:18 terraform-provisioner-remote-exec: 2015/08/03 17:44:18 Retryable error: http error: 401 -

**Comment by svanharmelen** [comment]
> error Post http://52.76.8.9:5985/wsman: dial tcp 52.76.8.9:5985: connection refused

This seems to indicate you cannot connect to that IP/port combo. Can you check/verify with telnet if that could be your problem?

**Comment by svanharmelen** [comment]
Hmm... So are you also sure that at this time the newly created machine is already a domain member?

**Comment by teewhey** [comment]
Yeah I'm sure. When this message is still popping up, I'm able to login to the machine using the exact same credentials. Also did a curl to the endpoint as reported in the log, it gave some response saying only POST method allowed. So I presume connectivity is working fine.
Any other stuff that I might miss out?

Sent from Outlook




On Mon, Aug 3, 2015 at 3:41 AM -0700, "Sander van Harmelen" <notifications@github.com> wrote:
Hmm... So are you also sure that at this time the newly created machine is already a domain member?

---

**Comment by svanharmelen** [comment]
Are you sure that WinRM is configured correctly so that it allows unencrypted traffic? See [here](https://github.com/masterzen/winrm/blob/master/README.md) for more details and info about how to setup your Windows host.

**Comment by teewhey** [comment]
Okay. It never crossed my mind that WinRM needs to be configured to use with terraform to run the provisioning scripts. I thought it would support out of the box. I'll give it a try nevertheless.

**Comment by kbrooks** [comment]
I'm seeing a similar issue to the above intermittently on version 0.6.4.

I have a file provisioner on a windows instance that fails with the following error messgage:

```
...
aws_instance.gateway: Provisioning with 'file'...
Error applying plan:

1 error(s) occurred:

* http error: 401 -
```

It looks like my winrm is configured correctly:
```<script>                                                                                                        
  winrm quickconfig -q & winrm set winrm/config/winrs @{MaxMemoryPerShellMB="300"} & winrm set winrm/config     
@{MaxTimeoutms="1800000"} & winrm set winrm/config/service @{AllowUnencrypted="true"} & winrm set               
winrm/config/service/auth @{Basic="true"}                                                                       
</script>                                                                                                       
```

I have been able to provision these instances successfully using the exact same template on several occasions, which makes this issue especially frustrating.

**Comment by svanharmelen** [comment]
@teewhey are you ok with closing this one? Since things are silent now, I suppose you managed to get things working?

**Comment by teewhey** [comment]
Can close this one. I will raise it again if I encounter similar issues in the future.

**Comment by chrisoldwood** [comment]
For those like myself that are new to Terraform and stumble across this issue it's because the WinRM Go library that Terraform uses requires Basic Authentication to be enabled. I could remote into my AWS instance using PowerShell remoting, but my `remote-exec` steps failed with a somewhat confusing `401: Invalid content type` [1].

If you're using one of Amazon's Windows AMIs you can get away with this as the bare minimum in your instance `user_data`:
```
<powershell>
winrm set winrm/config/service/Auth '@{Basic="true"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}'
</powershell>
```

To troubleshoot this originally I downloaded and built the [winrm-cli](https://github.com/masterzen/winrm-cli) tool which uses the same underlying Go library. The `README` for that repo provided the steps above and a link to a much longer and more detailed blog post [Using OverThere to control a Windows Server from Java](https://frontier.town/2011/12/overthere-control-windows-from-java/).

[1] Note that only the HTTP status code is displayed in the OP's question (`error: 401 - `), the error message is missing (_is this a Terraform bug?_). If you use the `winrm-cli` tool you'll see the entire error message (i.e. `401 - Invalid content type`).

**Comment by kolly83** [comment]
Hello

Anybody has resolved that issue?

Thank you.
