### ISSUE TITLE
Inappropriate value for attribute "destination": string required.

### ISSUE THREAD

**Issue by pavant85** [hashicorp/terraform#29194]
Hi ,
 Trying to pass a block as destination ip's as variable for aws network firewall rule group . But iam getting below error . Below is the code block and tf.vars
Inappropriate value for attribute "destination": string required.

rule_group {
    rules_source {
      stateful_rule {
        action = "PASS"
        header {
          destination      = var.aws_eu_central_ip_ranges
          destination_port = "ANY"
          direction        = "ANY"
          protocol         = "TCP" 
          source           = "10.0.0.0/24"
          source_port      = "ANY"
        }
      }
    }

tf.vars --

variable "aws_eu_central_ip_ranges" {
	type = "list"
    default = [
            "52.219.170.0/23" ,
	    "52.219.168.0/24"
  ]
}

**Comment by jbardin** [comment]
We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by pavant85** [comment]
Actually it is a bug, we are not able to pass mutliple CIDR blocks to destination of a rule group while AWS CLI allows us to do that..
