### ISSUE TITLE
terraform validate command no longer reports invalid variable defaults

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform#29198]
Please note this is not really a bug, but none of the categories really fit this issue.

### Terraform Version
0.15.5

### Terraform Configuration Files
Any `variable` declaration with a `validation` block and a `defaults` argument.

### Debug Output
n/a

### Crash Output
n/a

### Expected Behavior
If a variable declaration contains a `default` argument with values that are considered invalid according to a `validation` block, then `terraform validate` will fail and report on the invalid defaults.

### Actual Behavior
`terraform validate` reports success, but `terraform plan` reports the expected failure on the variable defaults.

### Steps to Reproduce
terraform validate

### Additional Context
In Terraform 0.13, the "Expected Behavior" occurred. I believe it also occurred in Terraform 0.14. In Terraform 0.15, this behavior has changed to the "Actual Behavior". I cannot find a reference to this behavior change in the CHANGELOG. I was just wondering if this change was intentional or a side effect of a related change, and if intentional, if information could please be added to the CHANGELOG to reference this behavior change to assist with upgrade processes between minor versions of Terraform. Thank you.

### References
n/a

**Comment by jbardin** [comment]
Hi @mschuchard,

Thanks for filing the issue. I don't think that was the intended behavior, but I am not able to reproduce this. with the following input:

```
variable "in" {
  type        = number

  validation {
    condition     = var.in > 8
    error_message = "Variable must be > 8."
  }
}
```

I see
```
% tf validate
╷
│ Error: Invalid value for variable
│
│   on main.tf line 3, in module "mod":
│    3:   in = 3
│
│ Variable must be > 8.
╷
```

Can you show an example of the problem you are seeing?

Thanks!

**Comment by mschuchard** [comment]
Using your MCVE, I can alter it to be:

```terraform
variable "in" {
  type    = number
  default = 5

  validation {
    condition     = var.in > 8
    error_message = "Variable must be > 8."
  }
}
```

and Terraform validate reports success. However, I now see with 0.14.11 and 0.13.7 that those also report success. I am completely certain that on multiple occasions in 0.13, `terraform validate` would throw an error at the location of the `default` argument with a message about the `default` value not satisfying the variable validation block if the default was invalid. However, I do know I saw this in 0.13.5, and maybe this change propagated to 0.13 in 0.13.6 or 0.13.7?

Maybe with the clarification above I would not have to do some binary search on versions to pinpoint in case that assists with the change in behavior I am describing.

**Comment by jbardin** [comment]
Hi @mschuchard, that also fails validation when I test it, but I think I see where the confusion lies now. 

If you place that variable block in the root module it will not be checked during validation, because root module variables are always unknown during validation. The `validate` command is a static analysis of the configuration, meaning to check whether it is structurally valid. Because root module variables are by definition _variable_ (i.e. any number of new values could be supplied on the CLI each time terraform is invoked), they are not taken into account during validation. This is the same as if a module input was derived from a resource rather than being statically written into the configuration, it could not be checked during `validate` and would not be caught until plan or apply.

**Comment by mschuchard** [comment]
Ok so actual root cause is declared module defaults versus root module defaults. I look back at the prior examples and realize that is very likely the source of my confusion here. It has been years since I developed a root module config versus one that primarily declares modules, so I have never encountered this before.

Sorry about all this, and thanks for the explanation.
