### ISSUE TITLE
backend consul problem with address contains subdirectory

### ISSUE THREAD

**Issue by kingindanord** [hashicorp/terraform#29230]
I am not able to use an address of format `dnsname:port/subdirectory` in the backend configuration for consul. The address is reachable with curl and it is working.

Is it only possible to use `dnsname:port` as mentioned in the [documentation](https://www.terraform.io/docs/language/settings/backends/consul.html#address) or am I doing something wrong?

### Terraform Version

```
Terraform v1.0.1
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  backend "consul" {
    address = "command-center:28500/consul"
    scheme  = "http"
    path    = "terraform/state/dev/nomad/jobs"
    lock = true

  }
}
```

### Debug Output
```
Successfully configured the backend "consul"! Terraform will automatically
use this backend unless the backend configuration changes.
╷
│ Error: Failed to get existing workspaces: Get "http://command-center:28500%2Fconsul/v1/kv/terraform/state/dev/nomad/jobs-env:?keys=&separator=%2F": dial tcp: lookup command-center:28500/consul: no such host
│ 
│ 
```
### Steps to Reproduce

1. `terraform init`

**Comment by remilapeyre** [comment]
Hi @kingindanord, I'm not sure of the setup you are trying to use. Does Terraform access the Consul API through a proxy that adds `/consul` to the base API url? Does the Consul CLI works with this setup?

I tried doing this on my computer but it did not work either:

```
$ CONSUL_HTTP_ADDR=localhost:8500/consul consul members
Error retrieving members: Get "http://localhost:8500%2Fconsul/v1/agent/members?segment=_all": dial tcp: lookup localhost:8500/consul: no such host
``` 

If this is what you are trying to do, support for this would first need to be added in https://github.com/hashicorp/consul and we would just update the Consul client used by Terraform in this repo.

**Comment by kingindanord** [comment]
Thanks for checking @remilapeyre, yes that is exactly what I am trying to do. I've just tried it with Consul CLI and I get the same error. So apperently this is not related to Terraform.
