### ISSUE TITLE
Ran into Error deleting DB parameter group: InvalidDBParameterGroupState: One or more database instances are still members of this parameter group

### ISSUE THREAD

**Issue by claudio-aurora** [hashicorp/terraform#29232]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hi,

There doesn't appear to be any information here, but the title sounds like an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
