### ISSUE TITLE
HTTP client errors should fail early

### ISSUE THREAD

**Issue by Berbe** [hashicorp/terraform#29231]
### Current Terraform Version
```
Terraform v1.0.3
on inux_amd64
```

### Use-cases
When requests to providers end up in HTTP 4xx (client error), it usually means the error won't solve by itself.
However, the current client still retries requests until hitting the max attempts:
```
[...]
Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="ValidationError"
[...]
```

### Proposal
Client errors (classified with the help of the 400-499 HTTP status codes) could end up in an immediate error.
Failing early would speed up problems reporting & resolution.

**Comment by jbardin** [comment]
Hi @Berbe,

The retry output you are showing here is not coming from Terraform itself, though I'm not sure specifically which provider or library it's using would issue that exact message. If this is a provider error I would suggest filing an issue with that provider; there may be some more detailed configuration they can use from their cloud service's SDK to better control the retries. If you are asking specifically about the provider plugin SDK, you can find their repo here: https://github.com/hashicorp/terraform-plugin-sdk.

Thanks!

**Comment by Berbe** [comment]
I was using providers indeed but I thought this was generic, hence filled a ticket here.
I will tackle that at the provider level.
