### ISSUE TITLE
vault_identity_group_member_entity_ids is not working

### ISSUE THREAD

**Issue by mohamedbayoudh** [hashicorp/terraform#29237]
### Terraform Version

Terraform v1.0.3 on windows_amd64
with provider registry.terraform.io/gitlabhq/gitlab v3.7.0 and provider registry.terraform.io/hashicorp/vault v2.22.0

### Terraform Configuration Files

```terraform
terraform.tf(simple configuration)
```

### Crash Output

Error: Plugin did not respond
│
│   with vault_identity_group_member_entity_ids.CMTeam_membering,
│   on terraform.tf line 114, in resource "vault_identity_group_member_entity_ids" "CMTeam_membering":
│  114: resource "vault_identity_group_member_entity_ids" "CMTeam_membering" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vault_v2.22.0_x4.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x17aeecc]

goroutine 71 [running]:
github.com/hashicorp/terraform-provider-vault/vault.identityGroupAliasUpdate(0xc0003d1f10, 0x1a4cd40, 0xc000905f40, 0x24, 0x22ed9a0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vault/vault/resource_identity_group_alias.go:85 +0x30c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000689710, 0xc000073ea0, 0xc000256be0, 0x1a4cd40, 0xc000905f40, 0x1920501, 0xc00022f8d0, 0xc0006aede0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/resource.go:316 +0x293
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00013e580, 0xc00022fa38, 0xc000073ea0, 0xc000256be0, 0xc0006b2988, 0xc0000cd670, 0x1922760)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/provider.go:294 +0xa5
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000cd2d8, 0x1c77210, 0xc0006ae1b0, 0xc0003d1420, 0xc0000cd2d8, 0xc0006ae1b0, 0xc00060fba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/helper/plugin/grpc_provider.go:885 +0x8c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1a1ab80, 0xc0000cd2d8, 0x1c77210, 0xc0006ae1b0, 0xc0002a36e0, 0x0, 0x1c77210, 0xc0006ae1b0, 0xc00069e1e0, 0x1d5)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002d4000, 0x1c826d8, 0xc0003fac00, 0xc000458300, 0xc000316bd0, 0x2297360, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002d4000, 0x1c826d8, 0xc0003fac00, 0xc000458300, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xccf
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00002a2c0, 0xc0002d4000, 0x1c826d8, 0xc0003fac00, 0xc000458300)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa8

Error: The terraform-provider-vault_v2.22.0_x4.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior
Assigning members to a Vault group

### Actual Behavior
crashing with the above crash trace

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by jbardin** [comment]
Hello @mohamedbayoudh,

Hi,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
