### ISSUE TITLE
Seeing InvalidDBParameterGroupState when trying to upgrade RDS Postgres DB from 11 to 12 with replication and custom parameter group kept on failing on trying to remove the parameter group

### ISSUE THREAD

**Issue by claudio-aurora** [hashicorp/terraform#29233]
I had this RDS Postgres 11 DB I was trying to upgrade to 12 which had an attached custom parameter group. The DB had a replication slot (this detail will be important later). When I tried to upgrade I made sure to specify the new version of the db engine in the parameter group so the old one would be removed and a new one would be created. The plan showed it showed it would replace the parameter group. When I applied the upgrade the messages on the console said the DB was being upgraded and after a few minutes it said "modification complete" followed by messages about trying to destroy the old parameter group which would eventually fail with this error:

Error: Error deleting DB parameter group: InvalidDBParameterGroupState: One or more database instances are still members of this parameter group XXXXXXXXX, so the group cannot be deleted
	status code: 400, request id: XXXXXXXXXX

I looked at the DB and it was still in the old version even tho Terraform said earlier the instance had been successfully modified. To get my work done I removed the parameter group by removing it from the tf file. Terraform had no problem removing the old  parameter group like this. Then I tried to upgrade the DB on a single step with no custom parameter groups but this operation now failed, I checked the pre-upgrade log in AWS and I found an error saying it couldn't upgrade the instance because there was a replication slot. I dropped the replication slot, applied the DB upgrade with no issues and finally added the new parameter group with the same config and re-created the replication slot manually.

The issue here looks to me is that the DB upgrade failed and instead of stopping the plan continued to execute to a state where it couldn't proceed anymore. I was running Terraform v0.14.10

**Comment by jbardin** [comment]
Hello

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
