### ISSUE TITLE
Azure NetApp Files Need support for multiple  Accounts with single AD connection 

### ISSUE THREAD

**Issue by RajendraVenkata** [hashicorp/terraform#29249]
Hi Team,

Firstly while creating multiple NetApp accounts azurerm_netapp_account resource allows to specify active_directory information for a single netapp account, which is logical as netapp only supports a single AD connection.

Subsequent accounts will automatically get the AD connection details pre populated.

resource "azurerm_netapp_account" "netapp_files" {
  name                = "anf account1"
  location            = data.azurerm_resource_group.resource_group.location
  resource_group_name = data.azurerm_resource_group.resource_group.name

  active_directory {
    username            = data.azurerm_key_vault_secret.domain_user_name.value
    password            = data.azurerm_key_vault_secret.domain_secret.value
    smb_server_name     = "${var.landscape}acc"
    dns_servers         = ["xx.xx.xxx.xxx", "xx.xx.xxx.xxx"]
    domain              = "yyy.yyyyy.yyy"
    organizational_unit = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
  }

  lifecycle {
    prevent_destroy = true
    ignore_changes = [
      active_directory
    ]
  }
  tags = local.tags_new

}

resource "azurerm_netapp_account" "netapp_files1" {
  name                = "anf account2"
  location            = data.azurerm_resource_group.resource_group.location
  resource_group_name = data.azurerm_resource_group.resource_group.name

  

  lifecycle {
    prevent_destroy = true
    ignore_changes = [
      active_directory
    ]
  }
  tags = local.tags_new

}
However which creating volumes on the new account we get an error

Error: Error waiting for creation of NetApp Account "netapp_files1" (Resource Group "yyyyy"): Code="BadRequest" Message="Unable to delete Active Directory information while SMB/Kerberos/LDAP enabled volume still exists." Details=[{"code":"ADInfoDeleteAdInUse","message":"Unable to delete Active Directory information while SMB/Kerberos/LDAP enabled volume still exists."}]
with azurerm_netapp_account.netapp_files
on main.tf line xxx, in resource "azurerm_netapp_account" "netapp_files1":

### Terraform Version
Terraform 1.0.1

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
