### ISSUE TITLE
ec2 instance cant plan if launch_template has been deleted

### ISSUE THREAD

**Issue by mtesch-um** [hashicorp/terraform#29246]
Working with an ec2 instance that was imported into TF many months ago.  This running EC2 can not be replaced.  It was started using a launch template in the aws console.  In recent versions of (aws or tf - not sure) the launch_template has been showing up as a changed resource (although nothing has actually changed in AWS!).

The launch template, however, no longer exists in AWS, but the tag on the EC2 resource (aws_instance) still exists indicating what launch template was used to start the instance.

When terraform runs a plan, it tries to load this (nonexistant) launch template, and the plan fails with:

```
Error: error reading Instance (i-...) Launch Template: error reading Launch Template: InvalidLaunchTemplateId.NotFound: Atleast one of the launch templates specified in the request does not exist.
│ 	status code: 400, request id
```

### Terraform Version

```
1.0.3
```

### Terraform Configuration Files

```terraform
```

### Expected Behavior

TF should ignore `aws_instance` resources that have `launch_template` tags which no longer exist - or there should be a way to tell TF to ignore them.  It is not possible to edit the `aws:` tag in aws that assigns a launch template to an instance, and that tag is not deleted by aws itself when the template has been deleted.

Or another solution?  At least the current state of things is completely broken as we have no way to run terraform on this instance (actually several instances that were started w/ the now defunct launch template).

### Actual Behavior

TF errors out when a launch template has been deleted if there are still stale tags for that template on managed `aws_instance` resources.

### Steps to Reproduce

1. create a launch template in aws
2. create an instance in aws console by using that launch template
3. import that instance into terraform as an `aws_instance`
4. delete the launch template from 1.
5. run `terraform plan`

### References

couldn't find any...

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by mtesch-um** [comment]
@jbardin thanks for the redirect!  Just a note - the current github issue template points at https://github.com/terraform-providers for providers - I looked there but didnt see the aws provider there (didn't think to look at the top level hashicorp github)

**Comment by jbardin** [comment]
Thanks for the heads up @mtesch-um! The majority of providers are not under either of those organizations, and are found in the [Terraform Registry](https://registry.terraform.io/browse/providers). I'll update the template to match.

**Comment by mtesch-um** [comment]
for future searchers: issue moved to https://github.com/hashicorp/terraform-provider-aws/issues/20331
