### ISSUE TITLE
Terraform route has a missing reference in plan output JSON

### ISSUE THREAD

**Issue by moradiv-ll** [hashicorp/terraform#29267]
Hi,

I am using Terraform cli version 1.0.1
I ran the attached TF called “vpc_subnet_rtb_route_to_nic.tf.txt”, which creates a VPC, subnet, 2 network interfaces, and a route table that contains a route targeted to the 2nd created network interface.

This is the created route table on AWS console after running “terraform apply”:
![image](https://user-images.githubusercontent.com/70267242/127511381-87242db2-5a87-4c02-bd36-6d6e1e597d78.png)

The issue I found is in the attached terraform json output, which was created by running:
1.	terraform plan -out= vpc_subnet_rtb_route_to_nic.out
2.	terraform show -json vpc_subnet_rtb_route_to_nic.out > vpc_subnet_rtb_route_to_nic.json

According to the TF file, the created route table has a route targeted to the second network interface called “test_interface_2”:
 
![image](https://user-images.githubusercontent.com/70267242/127511422-927b2d6b-ac40-4248-b42e-306d64a06d26.png)

From the created JSON file (attached, named vpc_subnet_rtb_route_to_nic.json) there is no clue that the created route table named “my_rtb” has a route which is targeted to the 2nd ENI. The only way to figure that out is by looking at the TF file.
In the json file there is an attribute under the “after_unknown” section for the route table, which implies there is going to be a route created, with a network interfaces id, but we cannot know which network interface id it is going to be:
![image](https://user-images.githubusercontent.com/70267242/127511465-0d1b00c7-3867-425d-ad1b-31e831de79da.png)

 
The created JSON file should represent what is going to be done by the terraform plan, but here we have a case where we cannot know which route is going to be created.

@mildwonkey  @jbardin - I saw this issue should have been fixed in your PR (https://github.com/hashicorp/terraform/pull/28884), but it still happens for me. I'd be thankful if you can take a look into it.

Can you please assist and examine this issue? Am I missing something? If not, can it be solved somehow?

[vpc_subnet_rtb_route_to_nic.json.txt](https://github.com/hashicorp/terraform/files/6901355/vpc_subnet_rtb_route_to_nic.json.txt)
[vpc_subnet_rtb_route_to_nic.tf.txt](https://github.com/hashicorp/terraform/files/6901356/vpc_subnet_rtb_route_to_nic.tf.txt)

**Comment by jbardin** [comment]
Hi @moradiv-ll,

The linked PR was only to provide both resource-level and attribute level references, but it appears here that you have no reference listed at all. 

Looking at the provider schema, it appears that `route` is treated as an attribute rather than a block, but the block syntax is allowed via `SchemaConfigModeAttr`. The current workaround would be to use attribute syntax for `route`, however that object has numerous attributes, which will unfortunately make the config much more verbose in this situation if the json references are required for your use case. You can see the open issue tracking that bug here: #29022. 

Thanks!

**Comment by moradiv-ll** [comment]
Thank you @jbardin for your response.
I've noticed that there has been an update with aws route_table/security_group/network_acl resources that is relevant for my issue, for exmaple:
 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table
Now, according to the documentation, routes can be added within route_table resource without all the null config attributes:
![image](https://user-images.githubusercontent.com/70267242/129186923-6a346217-40e6-4d5d-8fa0-d5299479e25c.png)
Unfortunately, after upgrading terraform client to v1.0.4 and using latest aws provider, I receive an error that says there are missing attributes:
![image](https://user-images.githubusercontent.com/70267242/129187077-972a0e4f-bb17-4754-b0ea-e12cbffc5bd8.png)
after setting the described attributes as null, it works.
Is that an issue should be fixed?

**Comment by jbardin** [comment]
@moradiv-ll, that looks like a problem with the AWS documentation. The attributes in that syntax cannot be made optional.

**Comment by moradiv-ll** [comment]
Thank you @jbardin, any idea who can I contact regarding that problem?
Another thing that got added in the documentation is this one:
![image](https://user-images.githubusercontent.com/70267242/129212618-31bf71ff-f16a-4706-8920-4a35a501e6e4.png)

Which means "aws_route" cannot be defined in conjuction to "route" in a "route_table" (same for security group and acl rules).
Are you familiar with this limitation?

**Comment by jbardin** [comment]
You can file issue with the AWS provider in their github repository. Questions about the provider are best asked in the corresponding category of [the community forum](https://discuss.hashicorp.com/).

Thanks!
