### ISSUE TITLE
Conditional dynamic block with list  of resource

### ISSUE THREAD

**Issue by Handsome-Jaxon** [hashicorp/terraform#29269]
Hi everyone , I'm trying to use condition dynamic block in a list of resource , I create list of google_compute_instance , and one of the attribute block "alias_ip_range" , some instance might have some not , so I use condition dynamic block inside the list of resource but seems something goes wrong , is it possible to use conditional dynamic block inside of list of resource ?

below is my code for reference

variable for the list of resource :

```
variable "gce" {
  type = list(object({
    hostname         = string
    ip               = string
    alias_ip         = string
    subnet           = string
    zone             = string
    instance_type    = string
    image            = string
    disk_type        = string
    boot_disk_size   = string
    second_disk_size = string
    labels           = map(string)
    tag              = list(string)
    ssh_user         = string
    status           = string
  }))
}
```

input of the variable :

```
gce = [
    { ### server_1
      hostname         = "test-1"
      ip               = "192.168.1.2"
      alias_ip         = "192.168.1.10/32"
      subnet           = module.VPC.subnet_1_id
      zone             = "asia-east1-a"
      instance_type    = "e2-small"
      image            = "projects/centos-cloud/global/images/centos-7-v20210512"
      disk_type        = "pd-balanced"
      boot_disk_size   = "20"
      second_disk_size = "0"
      labels = {
        "test" = "jason"
      }
      tag      = ["ssh"]
      ssh_user = "user1"
      status   = "RUNNING"
    },
    { ### server_2
      hostname         = "test-2"
      ip               = "192.168.1.3"
      alias_ip         = ""
      subnet           = module.VPC.subnet_1_id
      zone             = "asia-east1-c"
      instance_type    = "e2-small"
      image            = "projects/centos-cloud/global/images/centos-7-v20210512"
      disk_type        = "pd-balanced"
      boot_disk_size   = "20"
      second_disk_size = "0"
      labels = {
        "test" = "jason"
      }
      tag      = ["ssh"]
      ssh_user = "user1"
      status   = "RUNNING"
    },
  ]
```

and my resource code for google_compute_instance like below :

```
resource "google_compute_instance" "gce" {
  for_each       = { for instance in var.gce : instance.hostname => instance }
  name           = each.value.hostname
  machine_type   = each.value.instance_type
  tags           = each.value.tag
  zone           = each.value.zone
  desired_status = var.gce_status

  network_interface {
    subnetwork = each.value.subnet
    access_config {
      network_tier = "PREMIUM"
    }

    dynamic "alias_ip_range" {
      for_each = {for instance in var.gce: instance.hostname=>instance if instance.alias_ip != "" }
      content {
        ip_cidr_range = each.value.alias_ip
      } 
    }

  }

  service_account {
    scopes = var.service_account_scope
  }

  boot_disk {
    source = google_compute_disk.disk0[each.key].name
  }
}

```

and if one of the value of alias_ip in variable isn't "" ,it will create a attribute block but the attribute in that block is null , but the attribute block can't be empty since some attribute inside is required then cause error.

change when terraform plan like below 

 module.GCE.google_compute_instance.gce["test-1"] will be updated in-place
  ~ resource "google_compute_instance" "gce" {
        id                   = "projects/ms-devproject/zones/asia-east1-a/instances/test-1"
        name                 = "test-1"
        tags                 = [
            "jason-mac",
        ]
        # (18 unchanged attributes hidden)

      ~ network_interface {
            name               = "nic0"
            # (4 unchanged attributes hidden)

          + alias_ip_range {
              + ip_cidr_range = "192.168.1.10/32"
            }
            # (1 unchanged block hidden)
        }

        # (4 unchanged blocks hidden)
    }

  # module.GCE.google_compute_instance.gce["test-2"] will be updated in-place
  ~ resource "google_compute_instance" "gce" {
        id                   = "projects/ms-devproject/zones/asia-east1-c/instances/test-2"
        name                 = "est-2"
        tags                 = [
            "jason-mac",
        ]
        # (18 unchanged attributes hidden)

      ~ network_interface {
            name               = "nic0"
            # (4 unchanged attributes hidden)

          + alias_ip_range {}
            # (1 unchanged block hidden)
        }

        # (4 unchanged blocks hidden)
    }

and will get error below 

 Error: Plugin did not respond
│ 
│   with module.GCE.google_compute_instance.gce["jason-test-2"],
│   on Modules/GCE/main.tf line 1, in resource "google_compute_instance" "gce":
│    1: resource "google_compute_instance" "gce" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.GCE.google_compute_instance.gce["jason-test-1"],
│   on Modules/GCE/main.tf line 1, in resource "google_compute_instance" "gce":
│    1: resource "google_compute_instance" "gce" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-google_v3.68.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 89 [running]:
github.com/hashicorp/terraform-provider-google/google.expandAliasIpRanges(0xc000bf0bd0, 0x1, 0x1, 0xe, 0xc000b13bb8, 0x1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/compute_instance_helpers.go:39 +0x33f
github.com/hashicorp/terraform-provider-google/google.expandNetworkInterfaces(0x3dd9b58, 0xc000cb4f00, 0xc00037b800, 0x0, 0xc000a54000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/compute_instance_helpers.go:249 +0x607
github.com/hashicorp/terraform-provider-google/google.resourceComputeInstanceUpdate(0xc000cb4f00, 0x38d7160, 0xc00037b800, 0x0, 0xffffffffffffffff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/resource_compute_instance.go:1369 +0x470
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0004d9500, 0x3da1ca0, 0xc000dd9540, 0xc000cb4f00, 0x38d7160, 0xc00037b800, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:352 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004d9500, 0x3da1ca0, 0xc000dd9540, 0xc000e702a0, 0xc000ce42e0, 0x38d7160, 0xc00037b800, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002857b8, 0x3da1ca0, 0xc000dd9540, 0xc0009e43c0, 0xc000dd9540, 0x382a640, 0xc0009c9b00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000e1ef40, 0x3da1d48, 0xc000dd9540, 0xc000e701c0, 0xc000e1ef40, 0xc0009c9b30, 0xc0005e6ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x382a640, 0xc000e1ef40, 0x3da1d48, 0xc0009c9b30, 0xc000f26d20, 0x0, 0x3da1d48, 0xc0009c9b30, 0xc000e7e000, 0x1deb)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fc540, 0x3dd9bb8, 0xc00008b500, 0xc000e90100, 0xc0009c99b0, 0x4b8d520, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001fc540, 0x3dd9bb8, 0xc00008b500, 0xc000e90100, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000034740, 0xc0001fc540, 0x3dd9bb8, 0xc00008b500, 0xc000e90100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:876 +0x1fd

Error: The terraform-provider-google_v3.68.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by Handsome-Jaxon** [comment]
Hi @jbardin 
The main issue I'm facing is conditional dynamic block in list of resource , I suppose the attribute block won't exist in resource if the condition is true , but It seems there is something wrong in my code that if one of the variable alias_ip isn't "" then It'll let all resource have the attribute block , what I want is if the variable alias_ip is "" then there's no attribute block in the resource , if the alias_ip is IP in CIDR format then the resource will have the attribute block and input the value of variable alias_ip to the attribute. But now if in the list of variable , even the alias_ip is "" in that object , it still create the attribute block then cause the error , so I'd like to know if it's workable to use conditional dynamic block in list of resource.

Jason
