### ISSUE TITLE
cloudwatch_log_group missing name output field

### ISSUE THREAD

**Issue by samuelkdavis-mccarthyfinch** [hashicorp/terraform#29262]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group

The Attributes Reference only shows 'arn' and 'tags_all', however you can also reference the name field. It works but is undocumented.

```
resource "aws_cloudwatch_log_subscription_filter" "worker_log_subscription_filter" {
  for_each = var.filter_subscriptions
  # depends_on      = [module.cloudwatch_log_group]
  role_arn        = ""
  name            = "${var.name}${each.key}"
  log_group_name  = aws_cloudwatch_log_group.default.name
  filter_pattern  = each.value.filter_pattern
  destination_arn = each.value.destination_arn
}
```

**Comment by jbardin** [comment]
This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
