### ISSUE TITLE
Custom pre-shared key for AWS VPN

### ISSUE THREAD

**Issue by pranav-mahajan-cko** [hashicorp/terraform#29275]
Hi All,

I have been deploying site -to-site vpn using terraform-aws-modules/vpn-gateway/aws. I am trying to set custom pre-shared key against AWS generated key. But every time after creating vpn, the configuration shows AWS generated key instead of custom key that I am trying to configure.
I am able to configure same key post vpn configuration by manually changing it via _"Modify tunnel options"_  so key is valid.
FYI, there are no errors in terraform plan. And key is not displayed while running plan as it hidden under sensitive value.
`+ tunnel1_preshared_key                = (sensitive value)`

Below is snippet from my main.tf

```
module "vpn_gateway" {
  source  = "terraform-aws-modules/vpn-gateway/aws"
  version = "~> 2.0"

  connect_to_transit_gateway        = true
  transit_gateway_id                = data.aws_ec2_transit_gateway.TGW.id
  customer_gateway_id               = aws_customer_gateway.main.id
  vpn_connection_static_routes_only = true

  #Tunnel 1 Options
  tunnel1_ike_versions                 = ["ikev2"]
  tunnel1_inside_cidr                  = var.vpn_remote_inside_cidr
  tunnel1_preshared_key                = "1234567890abcdefghijklmn"
  tunnel1_phase1_dh_group_numbers      = var.dh_group
  tunnel1_phase1_encryption_algorithms = var.encryption_algorithms
  tunnel1_phase1_integrity_algorithms  = var.integrity_algorithms
  tunnel1_phase1_lifetime_seconds      = 28800
  tunnel1_phase2_dh_group_numbers      = var.dh_group
  tunnel1_phase2_encryption_algorithms = var.encryption_algorithms
  tunnel1_phase2_integrity_algorithms  = var.integrity_algorithms
  tunnel1_phase2_lifetime_seconds      = 3600
}
```

**Comment by jbardin** [comment]
This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
