### ISSUE TITLE
terraform init writes remote config to cwd even if target path provided

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#2927]
the ``terraform init`` command has an optional second positional argument for the path where the module should be placed, defaulting to the current working directory.

When that argument is provided, the module config is copied into the given directory as expected, but the ``.terraform/terraform.tfstate`` file (created if you simultaneously configure remote state) is always written to the current working directory, and not to the target path.

This is bothersome since running terraform commands in the new directory then uses local state rather than remote state, which causes confusion at best and duplicated resources at worst.

**Comment by mitchellh** [comment]
PR opened.
