### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.58.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by justPaulo** [hashicorp/terraform#29279]
azurerm_virtual_network.vnet-bastion: Still destroying... [id=/subscriptions/the subscription/-...t.Network/virtualNetworks/vnet-bastion, 10s elapsed]
azurerm_public_ip.public-ip-bastion: Destruction complete after 21s
azurerm_virtual_network.vnet-bastion: Destruction complete after 11s
azurerm_resource_group.theRessource: Destroying... [id=/subscriptions/theSubscription/resourceGroups/theRessource]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.70.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x5437bd6]

goroutine 219 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/resource.resourceResourceGroupDelete(0xc0014cda00, 0x5aa25e0, 0xc000f60e00, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/resource/resource_group_resource.go:128 +0x236
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc0009469a0, 0x6a36c28, 0xc001a7e1c0, 0xc0014cda00, 0x5aa25e0, 0xc000f60e00, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:369 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0009469a0, 0x6a36c28, 0xc001a7e1c0, 0xc000bc49a0, 0xc0017b05e0, 0x5aa25e0, 0xc000f60e00, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:428 +0x8f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000285bc0, 0x6a36c28, 0xc001a7e1c0, 0xc0015a6690, 0xc001a7e1c0, 0x5f82e40, 0xc0014c4d00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef    
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001b788e0, 0x6a36cd0, 0xc001a7e1c0, 0xc000bc4850, 0xc001b788e0, 0xc0014c4d20, 0xc0003ffba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5f82e40, 0xc001b788e0, 0x6a36cd0, 0xc0014c4d20, 0xc001672780, 0x0, 0x6a36cd0, 0xc0014c4d20, 0xc0010e0340, 0x190)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022e8c0, 0x6a83418, 0xc000585080, 0xc001d1c360, 0xc00122d3e0, 0xa009ec0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00022e8c0, 0x6a83418, 0xc000585080, 0xc001d1c360, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0007b3b70, 0xc00022e8c0, 0x6a83418, 0xc000585080, 0xc001d1c360)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.70.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
