### ISSUE TITLE
"name" cannot end with a hyphen, -sb, or -mgmt

### ISSUE THREAD

**Issue by cacizi41** [hashicorp/terraform#29278]
I am trying to give service bus instance a name "{resourcegroup}-{env}-sb", and got this error msg: "name" cannot end with a hyphen, -sb, or -mgmt.

Just want to understand why.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help.

Thanks!
