### ISSUE TITLE
Missing endpoints due to out of date aws-sdk-go

### ISSUE THREAD

**Issue by slimm609** [hashicorp/terraform#29285]
### Terraform Version

```
v1.0.3
```

github.com/aws/aws-sdk-go v1.37.0

Several endpoints have been added to the aws-sdk-go since the release in-use.   While the ability to override endpoints exists at the provider level, not having the ability to override per region makes it very difficult to update when using terraform across multiple environments and regions.     Please update the aws-sdk-go version to provide updated endpoints

**Comment by jbardin** [comment]
Closed via #29017
