### ISSUE TITLE
How to create a file in a script and then use it

### ISSUE THREAD

**Issue by wint00** [hashicorp/terraform#2928]
I need to run a python script that renders a few files together in a valid yaml format and then read those files to shove into metadata.

The way I am trying to do with is to have a local-exec provisioner that creates the file:
`provisioner "local-exec" {
      command = "./python -c 'from cloud_config import timbuktu; print timbuktu(\"ubuntu-1404-common.cloud-config\", \"ubuntu-artifact.cloud-config\", \"ubuntu-core-report.cloud-config\", \"wint00-final.cloud-config\")' > wintoo.cloud-config"
}`

`metadata {
  user-data = "${file("wintoo.cloud-config")}"
}`

however, I immediately get a complaint that the file wintoo.cloud-config doesn't exist. Which of course it doesn't b/c I'm asking that script to create it. I am currently wrapping it in a bash script to create the files but perhaps I can do it all in terraform?

As a side note I'm not sure if I've escaped the above local-exec correctly. Can someone kindly critique that for me? I can open a separate issue for that if it warranted.

**Comment by wint00** [comment]
My workaround here was to generate a script first so TF won't complain and then regenerate it again at instantiation. Not the best but it works.

**Comment by keymon** [comment]
+1, I think this kind of problems can be solved should have two different features. 

First a resource that can execute external commands and capture the output. For example:

```
resource "external_command" "my_public_ip" {
  command = "curl -qs http://ifconfig.me"
  run = "always"
}

output "my_public_ip" {
  value = "${external_command.my_public_ip.output}"
}
```

Second, I think `${file("my_file.txt")}` shouldn't check that my_file.txt exists until it actually reads it.

**Comment by jen20** [comment]
Hi, @wint00. Have you looked at using the `template_file` resource for this? You can use it like this:

```hcl
resource "template_file" "bootstrap" { /* ... */ }

resource "aws_instance" "app" {
  # execute as a script directly
  provisioner "remote-exec" {
    inline = "${template_file.bootstrap.rendered}"
  }
  # drop as a file on the machine
  provisioner "remote-exec" {
    inline = "cat <<FILE > /tmp/bootstrap.sh
${template_file.bootstrap.rendered}}
FILE"
}
```

I'll close this issue for now, feel free to reopen it if this suggestion doesn't solve your problem!
