### ISSUE TITLE
Missing expected { - when using PG as remote backend during plan

### ISSUE THREAD

**Issue by Pushp1403** [hashicorp/terraform#29290]
Hi there,

I am getting this error "missing expected {" when using PG as backend. It runs fine if Use local state.

Even with remote PG state, terraform validate and init run just fine, it's just plan which results in an error. I dont see any issue with provider.

###Terraform Version: 0.14.3

### Expected Behavior
Terraform plan should have successfully completed

### Actual Behavior
Error: Missing expected {

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
