### ISSUE TITLE
Docker Container With Host Networking

### ISSUE THREAD

**Issue by therevoltingx** [hashicorp/terraform#2929]
In order to achieve optimal network performance we want to be able to set `--net=host` option when starting our containers.  However it seems that this options is not accessible from Terraform.  It does not seem possible to set this variable any other way.  It would be great to have this as an option for the Docker provider.

Thanks,
Miguel.

**Comment by therevoltingx** [comment]
Hi, any updates or comments on this issue?

**Comment by ColinHebert** [comment]
Any news regarding this?

Also @phinze I'm not sure that's a question, it's more an enhancement of the docker provider to support the `--net` option. It could also be used to specify `--net=container:ContainerName`.

**Comment by therevoltingx** [comment]
Thanks for adding this feature!
