### ISSUE TITLE
Computed fields make `terraform plan` fail

### ISSUE THREAD

**Issue by gukoff** [hashicorp/terraform#29292]
_This issue is upstreamed from https://github.com/terraform-providers/terraform-provider-azurerm/issues/12828_

### Terraform Version

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0
```

### Terraform Configuration Files

Please see `main.tf` in the repo reproducing the bug at https://github.com/gukoff/bug_in_azurerm_resource_group_template_deployment

It's small, I promise :)

### Debug Output

```
    │ Error: Unsupported attribute
    │
    │   on main.tf line 52, in resource "azurerm_role_assignment" "file_st_role_assignment":
    │   52:   principal_id         = jsondecode(azurerm_resource_group_template_deployment.arm_deployment.output_content).principalId.value
    │     ├────────────────
    │     │ azurerm_resource_group_template_deployment.arm_deployment.output_content is "{}"
    │
    │ This object does not have an attribute named "principalId".
```

### Expected Behavior

Outputs of `azurerm_resource_group_template_deployment` are known only after
the ARM template is provisioned.

### Actual Behavior

Outputs of `azurerm_resource_group_template_deployment` are evaluated on terraform plan stage.
`terraform plan` fails.
### Steps to Reproduce

Please see the repo reproducing the bug at https://github.com/gukoff/bug_in_azurerm_resource_group_template_deployment

### References

- This issue was originally opened here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/12828

**Comment by jbardin** [comment]
Closing, with further discussion in the azurerm issue.

Thanks!
