### ISSUE TITLE
Unable to force recreation of an S3 bucket when switching AWS regions which causes an error 

### ISSUE THREAD

**Issue by iaminov** [hashicorp/terraform#29293]
My terraform code currently uses an S3 bucket with an auto-generated name by terraform. If I want to apply this infrastructure to another region by changing the region parameter in the provider resource, I get an error upon “terraform apply” that the S3 bucket is not located in that new region (which is true). Is there any way to avoid this error? I would assume the solution is to somehow force terraform to create a new bucket in the new region (instead of trying to read the old bucket) but I am not sure how to do that. Or is this a bug?

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
