### ISSUE TITLE
TypeSet, TypeList and TypeMap attributes saved as `null` in state file after Creation if not set in configuration, should be empty set

### ISSUE THREAD

**Issue by CyrusJavan** [hashicorp/terraform#29319]
### Terraform Version

```
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/cyrusjavan/example v1.1.0

```

### Terraform Configuration Files

```terraform
provider "example" {}

terraform {
  required_providers {
    example = {
      source = "CyrusJavan/example"
      version = "1.1.0"
    }
  }
}

resource "example_pet" "pet_1" {
  name = "sharik"
}
```

### Debug Output

Not sure if it would be helpful to have the debug log for the apply or the subsequent plan? Please let me know and I can provide it.

### Expected Behavior

Resource `example_pet` has two optional attributes `nicknames` (TypeSet of string) and `favorite_foods` (TypeList of string). After creating an `example_pet` resource with both `nicknames` and `favorite_foods` not set in configuration, the Create function then calls the Read function which sets `nicknames` and `favorite_foods` to empty slice. In the statefile, these attributes should be set to `[]`.

### Actual Behavior

After creating an `example_pet` both `nicknames` and `favorite_foods` are set to `null`. Then on subsequent calls to `terraform plan`, we see the following warning message.
```
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # example_pet.pet_1 has been changed
  ~ resource "example_pet" "pet_1" {
      + favorite_foods = []
        id             = "4037200794235010051"
        name           = "sharik"
      + nicknames      = []
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```

The state is only rectified after executing an apply.

### Steps to Reproduce

To run my `example` provider you need to clone the CyrusJavan/terraform-provider-example repo and call `make run` to run the local server. Then you can do the following in another terminal:
`terraform init`
`terraform apply` // See statefile after this step to see the attributes are `null`
`terraform plan` // See the warning output

### Additional Info
I have also observed similar behavior with TypeMap attributes.

**Comment by jbardin** [comment]
Hi @CyrusJavan,

If an optional attribute is not present in the configuration, there is no value for that attribute, which is represented by `null`. This is distinct from an empty list, map or set; which are single container values containing zero elements. 

The behavior you are describing here is caused by the provider, which is changing the previously stored values when refreshing the resource during the plan. In most cases this is not caused directly by the provider itself, but by the legacy SDK, which cannot handle empty values consistently. While terraform (and the protocol shims within the SDK) does its best to deal with these inconsistencies, it's going to require the net generation SDK in order to solve the remaining issues.

Thanks!

**Comment by CyrusJavan** [comment]
Thanks for the reply @jbardin!

Do you know of a workaround to avoid showing my users the “Terraform detected the following changes made outside of Terraform” warning message with the v2 SDK? From my understanding terraform-plugin-framework is not ready for production providers yet.

**Comment by jbardin** [comment]
Unfortunately there isn't likely to be a workaround, as the SDK is probably going to mangle the values again. We do have #28803 to track the possibility of suppressing refresh output that is not relevant to the configuration, but right now we can only rely on the values eventually converging for these particular attribute types.
