### ISSUE TITLE
azurerm_consumption_budget_resource_group notification does not allow "Actual" or "Forecasted" selection

### ISSUE THREAD

**Issue by mayuritsme** [hashicorp/terraform#29310]
The template does not provide an option for "Actual" vs "Forecasted" notifications.
By default, it is taking "Actual" for the threshold and setting all the notifications on "Actual"

We should have the option "type" to select if the notification is for Actual or Forecasted

notification {
    enabled   = true
    threshold = 75.0
    operator  = "EqualTo"
    
    contact_groups = [
      azurerm_monitor_action_group.CostAlertActionGroup.id,
    ]
  }

   notification {
    enabled   = true
    threshold = 80.0
    operator  = "GreaterThan"
    
    contact_groups = [
      azurerm_monitor_action_group.CostAlertActionGroup.id,
    ]
  }

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
