### ISSUE TITLE
Meta-Argument condition or include_if & content

### ISSUE THREAD

**Issue by damon-atkins** [hashicorp/terraform#29314]
### Current Terraform Version
All

### Use-cases
The Meta-Argument `count` and new `for_each` are used to perform "if statements" in the case of `count` 0 or 1, in the case `for_each` empty set or set 

### Proposal
a) Provide a new Meta-Argument like `condition` or `include_if` instead of using `count` and `for_each` as a workaround for a `if` 
b) allow resource information to be provided as `content` i.e. pass a data structue which represents the same lines as the DSL

I am surprise you can not do
```
locals {
   something = {
      prevent_destroy = true
    }
}
dynamic "lifecycle" {
    condition = can(var.ENVIRONMENT)
    content = something  # as long as the map is what the resource expects in this block. i.e. its passing prevent_destroy
}
```
And also

```
resource "abc" "xyz" {
     somesetting = var.ENVIRONMENT
}
```
As
```
resource "abc" "xyz" {
    dynamic "somesetting" {
      condition = can(var.ENVIRONMENT)
      content = var.ENVIRONMENT
}
```

**Comment by jbardin** [comment]
Thanks @damon-atkins, combining with #21953 which covers the same use case.

**Comment by damon-atkins** [comment]
Thanks. Did not spot the existing issue.
