### ISSUE TITLE
There must be a better way to create a targetpool with Google?

### ISSUE THREAD

**Issue by wint00** [hashicorp/terraform#2932]
I've tried several ways and the only one that works for me is:

``` ruby
resource "google_compute_target_pool" "tp-proxy" {

    name = "tp-proxy"

    instances = [ "${var.region}-${element(split(",", var.zones), count.index)}/proxy-00", "${var.region}-${element(split(",", var.zones), count.index+1)}/proxy-01", "${var.region}-${element(split(",", var.zones), count.index+2)}/proxy-02" ]

    health_checks = [ "hc-proxy" ]

    depends_on = [ "google_compute_http_health_check.hc-proxy" ]
}
```

What I want to do is to allow the resource to discover the proxies. Something like this, though it doesn't work:

``` ruby
resource "google_compute_target_pool" "tp-proxy" {

    name = "tp-proxy"

    instances = [ "${google_compute_instance.proxy.*.zone/(google_compute_instance.proxy.*.name)}
}
```

Any suggestions would be appreciated.

**Comment by sparkprime** [comment]
Sorry, I didn't notice this issue until now.

This looks like a config / interpolation question, so retagging as core.  I think the question is how to assemble a list of strings of zone / instance name given a roundrobin assignment of zones to instances in a cluster of instance created with the 'count' attribute.

I will say that ${} should not be used in the target pool, as the target pool does not need to exist before the instances exist, and ForceNew on the instances should not ForceNew the target pool (to do so would cause an outage).  So this is purely an exercise in string construction, not in referencing computed attributes / creating dependencies.

**Comment by roman8422** [comment]
Came here googling the same question. In case someone else will look for it, this did the trick for me:
```
    instances = [
    "${formatlist("%v/%v",
	               google_compute_instance.tp-proxy.*.zone,
	               google_compute_instance.tp-proxy.*.name)}",
  ]

```

**Comment by mildwonkey** [comment]
Great answer, @roman8422! I'll close this, since it's an old ticket and that's the right way to handle it.
