### ISSUE TITLE
Terraform bugs out after ~20 min waiting for resource to be active

### ISSUE THREAD

**Issue by pgaijin66** [hashicorp/terraform#29320]
Hello,

I am creating an instance from a snapshot. It takes around 35 min to restore VM from the snapshot. while I try to do that using terraform, it bugs out after waiting for ~20 min. Is there a workaround to increase the context deadline where we can specify if needed wait X time until the particular resource is ready? 

I tried adding time_sleep and added dependency but it did not work as it dies before it could reach the time_sleep resource due to waiting for more than 20 min.

Here is the log from the event discussed above

```
module.vultr.module.jenkins.vultr_instance.corp_jenkins_worker_nodes_windows[0]: Still creating... [19m51s elapsed]
module.vultr.module.jenkins.vultr_instance.stage_jenkins_worker_nodes_windows[0]: Still creating... [19m51s elapsed]
module.vultr.module.jenkins.vultr_instance.corp_jenkins_worker_nodes_windows[1]: Still creating... [19m50s elapsed]
module.vultr.module.jenkins.vultr_instance.corp_jenkins_worker_nodes_windows[3]: Still creating... [19m51s elapsed]

Error: error while waiting for Server 38f60893-bc56-475f-bcff-235208612f38 to be in a active state : context deadline exceeded

  on VULTR/modules/jenkins_worker_nodes/main.tf line 26, in resource "vultr_instance" "corp_jenkins_worker_nodes_windows":
  26: resource "vultr_instance" "corp_jenkins_worker_nodes_windows" {
```

I had tried this, but it still did not work. Just to repeat, one resource takes about 45 min but if done via terraform, it bugs out after ~20 min.
```
# Creating null_resource to run
resource "null_resource" "previous" {}

resource "vultr_instance" "corp_jenkins_worker_nodes_windows" {
...
..
..
  depends_on = [null_resource.previous]
..
..
}

# Specify timeout period
resource "time_sleep" "wait_30_sec" {
 # Added dependency to make sure, this resource is executed only after the worker node creation
  depends_on = [
    vultr_instance.corp_jenkins_worker_nodes_windows,
  ]
  create_duration = "30s"
}

# Also, i had a null_resource which would run after the time_sleep resouce.
resource "null_resource" "next" {
  depends_on = [time_sleep.wait_30_sec]
}
```

**Comment by CyrusJavan** [comment]
This is a bug within the provider, https://github.com/vultr/terraform-provider-vultr. Terraform has a default 20 minute context deadline, this provider needs to extend that.

**Comment by pgaijin66** [comment]
Thank you for that. I have raised issue with the provider.
