### ISSUE TITLE
SSH Provisioner using agent and certificates not working

### ISSUE THREAD

**Issue by FWest98** [hashicorp/terraform#29323]
### Terraform Version
```
Terraform v1.0.4
on linux_amd64
```

### Terraform Configuration Files
```terraform
resource "null_resource" "test" {
  connection {
    host = <HOST>
    type = "ssh"
    user = <USER>
    agent = true
    certificate = file("/home/<USER>/.ssh/id_rsa-cert.pub")
  }
}
```

### Debug Output
Client:
```
2021-08-08T00:19:45.926+0200 [DEBUG] Connecting to <HOST>:22 for SSH
2021-08-08T00:19:45.942+0200 [DEBUG] Connection established. Handshaking for user <USER>
2021-08-08T00:19:46.073+0200 [WARN]  SSH authentication failed (<USER>@<HOST>:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
2021-08-08T00:19:46.074+0200 [WARN]  retryable error: SSH authentication failed (<USER>@<HOST>:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
2021-08-08T00:19:46.074+0200 [INFO]  sleeping for 8s
```

Server:
```
Aug  8 00:21:39 <HOST> sshd[67344]: Connection from <CLIENTIP> port 61220 on <HOSTIP> port 22
Aug  8 00:21:39 <HOST> sshd[67344]: Failed publickey for <USER> from <CLIENTIP> port 61220 ssh2: RSA SHA256:<MYKEY>
Aug  8 00:21:39 <HOST> sshd[67344]: Connection closed by authenticating user <USER> <CLIENTIP> port 61220 [preauth]
```
### Expected Behavior
SSH authentication should work

### Actual Behavior
SSH authentication fails

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Additional Context
I'm using an SSH keypair on a smartcard through GPG; this works just fine in normal circumstances. However, for the servers I'm using here, I am working with SSH certificates for access control. This means that I need to include an additional certificate file. Using normal `ssh`, this works just fine and it seems to automatically pick up on the `id_rsa-cert.pub` file next to my `id_rsa.pub`. However, this does not work in Terraform. Explicitly including this certificate file also does not work.

While digging around, I found the following clues:
- If I understand correctly, the GPG ssh-agent does not support handling certificates (https://dev.gnupg.org/T1756, causing issues with agent-forwarding), so I think the `ssh` client itself is looking for the certificate file.
- Support from the ssh-agent itself seems difficult as well: https://bugzilla.mindrot.org/show_bug.cgi?id=2472 (but again, I don't know all the little details)
- https://github.com/hashicorp/terraform/blob/10e431487f0586e07852d6522893737a050e8976/internal/communicator/ssh/provisioner.go#L331-L335 It looks like here you're only doing something with the certificate if a private key is set, maybe it would be possible to change/extend this?
- Maybe it's related to limitations in Go: https://github.com/golang/go/issues/16524
- The client does send the correct keypair; as shown by the server logs it receives the same hash as I get when I do `ssh-add -l`, the one from my smartcard. However, it does not send a certificate.

For reference and completeness, the server and client logs when connecting using normal ssh (working setup):
SERVER
```
Aug  8 01:01:04 <HOST> sshd[118038]: Connection from <CLIENTIP> port 64692 on <HOSTIP> port 22
Aug  8 01:01:04 <HOST> sshd[118038]: Failed publickey for <USER> from <CLIENTIP> port 64692 ssh2: RSA SHA256:<MYKEY>
Aug  8 01:01:04 <HOST> sshd[118038]: Accepted certificate ID "vault-<USERNAME>-<ID>" (serial <SERIALNO>) signed by RSA CA SHA256:<CertAuthorityKey> via /etc/ssh/trusted-user-ca-keys.pem
Aug  8 01:01:04 <HOST> sshd[118038]: Postponed publickey for <USER> from <CLIENTIP> port 64692 ssh2 [preauth]
Aug  8 01:01:04 <HOST> sshd[118038]: Accepted certificate ID "vault-<USERNAME>-<ID>" (serial <SERIALNO>) signed by RSA CA SHA256:<CertAuthorityKey> via /etc/ssh/trusted-user-ca-keys.pem
Aug  8 01:01:04 <HOST> sshd[118038]: Accepted publickey for <USER> from <CLIENTIP> port 64692 ssh2: RSA-CERT SHA256:<MYKEY> ID vault-<USERNAME>-<ID> (serial <SERIALNO>) CA RSA SHA256:<CertAuthorityKey>
Aug  8 01:01:04 <HOST> sshd[118038]: pam_unix(sshd:session): session opened for user <USER> by (uid=<UID>)
```
<details><summary>CLIENT</summary>

```
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
<...>
debug1: Connecting to <HOST> [<HOSTIP>] port 22.
debug1: Connection established.
debug1: identity file /home/<USER>/.ssh/id_rsa type 0
debug1: identity file /home/<USER>/.ssh/id_rsa-cert type 4
<...>
debug1: Authenticating to <HOST>:22 as '<USER>'
<...>
debug1: Will attempt key: /home/<USER>/.ssh/id_rsa RSA SHA256:<MYKEY> agent
debug1: Will attempt key: /home/<USER>/.ssh/id_rsa RSA-CERT SHA256:<MYKEY>
<...>
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/<USER>/.ssh/id_rsa RSA SHA256:<MYKEY> agent
debug1: Authentications that can continue: publickey
debug1: Offering public key: /home/<USER>/.ssh/id_rsa RSA-CERT SHA256:<MYKEY>
debug1: Server accepts key: /home/<USER>/.ssh/id_rsa RSA-CERT SHA256:<MYKEY>
debug3: sign_and_send_pubkey: RSA-CERT SHA256:<MYKEY>
debug2: sign_and_send_pubkey: using private key "/home/<USER>/.ssh/id_rsa" for certificate
debug3: sign_and_send_pubkey: signing using rsa-sha2-512-cert-v01@openssh.com SHA256:<MYKEY>
debug1: Authentication succeeded (publickey).
Authenticated to <HOST> ([<HOSTIP>]:22).
```

Maybe less related but still surprising, the `debug2` output above does not print "from agent" as one would expect from the `ssh` source code: https://github.com/openssh/openssh-portable/blob/cf27810a649c5cfae60f8ce66eeb25caa53b13bc/sshconnect2.c#L1389-L1392. For the record, I do not have this `id_rsa` file, my private key only exists on my smartcard.
</details>

**Comment by jbardin** [comment]
Hi @FWest98,

Thanks for filing the issue. The certificate handling in the provisioner does not use an agent for signing, so this isn't expected to work. Combining with #29368 as a future enhancement.
