### ISSUE TITLE
error fetching virtual switch data: could not find virtual switch 

### ISSUE THREAD

**Issue by Rakshith2294** [hashicorp/terraform#29333]
Terraform v0.12.16
Vcenter version 6.7
I am trying to create infrastructure using terraform for vsphere which contains more than 30 virtual switches, terraform plan is successfull, deployment works successfully but frequently it times out while creating the vswitch saying the above error. Syntactically there is no issue seen. Is this a bandwidth issue, or terraform performance issue. Is there any requirement before running the setup. 

[1m[31mError: [0m[0m[1merror fetching virtual switch data: could not find virtual switch rs-3s_b1e1_crmpls[0m
[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1merror fetching virtual switch data: could not find virtual switch rs-3s_bastion-host[0m
[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1merror fetching virtual switch data: could not find virtual switch rs-3s_l3swh2_273[0m
[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1merror fetching virtual switch data: could not find virtual switch rs-3s_B1E1_HA[0m
[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1merror fetching virtual switch data: could not find virtual switch rs-3s_cri2_665[0m
[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1merror fetching virtual switch data: could not find virtual switch rs-3s_b1ce_crmpls[0m
[0m[0m[0m
[31m
[1m[31mError: [0m[0m[1merror fetching virtual switch data: could not find virtual switch rs-3s_Edge-3-1_client1[0m

**Comment by jbardin** [comment]
Hi,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
