### ISSUE TITLE
Include support for availability-zone-relocation parameter in aws_redshift_cluster to handle new AWS feature that supports cluster relocation across AZs

### ISSUE THREAD

**Issue by IndhuShanmugam** [hashicorp/terraform#29335]
Hi Team,

AWS introduced a new feature a few months ago which enables Redshift relocation across AZs:
https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-recovery.html

So with this new feature, we can now enable cluster relocation using this CLI command:
aws redshift modify-cluster --cluster-identifier mycluster --availability-zone-relocation

But this feature is not supported by Terraform in 'aws_redshift_cluster' resource or any other related resources. Please implement this new feature so that cluster relocation can be enabled through Terraform and we need not rely only on AWS CLI.

Thanks & Regards,
Indhu S

**Comment by jbardin** [comment]
This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
