### ISSUE TITLE
The "count" value depends on resource attributes that cannot be determined until apply (datasource)

### ISSUE THREAD

**Issue by hc-danieltiziani** [hashicorp/terraform#29348]
### Terraform Version

```
Terraform v0.15.4
```

### Terraform Configuration Files

```terraform
# module.tf
resource "aws_iam_role_policy" "iam_role_policy" {
  count = length(var.iam_policy_inline_json) > 0 ? 1 : 0

  name   = "iam-policy-inline-app-${var.app_name}-${local.environment}"
  policy = var.iam_policy_inline_json
}


# main.tf
module "mod" {
  source = "../../../resources/module"

  iam_policy_inline_json = data.aws_iam_policy_document.policy.json

  depends_on = [
    data.aws_iam_policy_document.policy
  ]
}

data "aws_iam_policy_document" "policy" {
  statement {
    effect = "Allow"

    actions = [
      "ses:SendRawEmail"
    ]

    resources = ["*"]
  }
}

```

### Debug Output

Error: Invalid count argument
│ 
│   on ../../../resources/modules/module.tf line 34, in resource "aws_iam_role_policy" "iam_role_policy":
│   34:   count = length(var.iam_policy_inline_json) > 0 ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around
│ this, use the -target argument to first apply only the resources that the count depends on.

### Expected Behavior

I expected it to compute the datasource and avoid this circle dependency error.

### Actual Behavior

The count attribute on module's resource gives this error.

### Steps to Reproduce

terraform init
terraform plan
terraform apply

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
