### ISSUE TITLE
Cannot perform terraform destoy after terraform state command

### ISSUE THREAD

**Issue by vdahmane** [hashicorp/terraform#29347]
### Terraform Version

```
Terraform version: 1.0.4

```

### Terraform Configuration Files

```terraform

...
```

### Crash Output

 Error: Could not load plugin
 
 
 Plugin reinitialization required. Please run "terraform init".
 
 Plugins are external binaries that Terraform uses to access and manipulate
 resources. The configuration provided requires plugins which can't be
 located,
 don't satisfy the version constraints, or are otherwise incompatible.
 
 Terraform automatically discovers provider requirements from your
 configuration, including providers used in child modules. To see the
 requirements and constraints, run "terraform providers".
 
 5 problems:
 
 - failed to instantiate provider "registry.terraform.io/datadog/datadog" to
 obtain schema: unknown provider "registry.terraform.io/datadog/datadog"
 - failed to instantiate provider "registry.terraform.io/hashicorp/aws" to
 obtain schema: unknown provider "registry.terraform.io/hashicorp/aws"
 - failed to instantiate provider "registry.terraform.io/hashicorp/helm" to
 obtain schema: unknown provider "registry.terraform.io/hashicorp/helm"
 - failed to instantiate provider "registry.terraform.io/hashicorp/template"
 to obtain schema: unknown provider
 "registry.terraform.io/hashicorp/template"
 - failed to instantiate provider "registry.terraform.io/hashicorp/dns" to
 obtain schema: unknown provider "registry.terraform.io/hashicorp/dns"

### Expected Behavior

terraform init
terraform state ***
terraform apply

### Actual Behavior

I have to run terraform init twice for make it work:

terraform init
terraform state ***
terraform init 
terraform apply

### Steps to Reproduce

1. `terraform init`
2.  `terraform state xxx`
3. `terraform apply`

### Additional Context

This issue occured since we have upgraded terraform from 0.13.5 to 0.14.0

**Comment by jbardin** [comment]
Hi @vdahmane,

Thanks for filing the issue. The `state` command should have no effect on the CLI data directory, so I'm not sure how to reproduce the behavior you are seeing.  Can you create a minimal, complete, reproducible example, showing the exact steps you used when seeing the issue?

Thanks!

**Comment by vdahmane** [comment]
Here an extract of our script:
- terraform init ..........
- |
      for s3_address in `terraform state list | grep 'aws_s3_bucket\.'`; do
      BUCKET="$(terraform state show $s3_address | sed -rnE 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g;s/.*^\s+bucket\s+=\s+"([^"]+)"$.*/\1/p')"
      ......
      ......
- terraform destroy ........

No problem with that before upgrade to 0.14 and 1.0.x

**Comment by jbardin** [comment]
@vdahmane,

Your `find ... -delete` command is removing necessary terraform files, probably the provider lock file.
Verify the matches from that command to make sure you are keeping all files used by terraform.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
