### ISSUE TITLE
`state mv` returns 0 on invalid source address

### ISSUE THREAD

**Issue by acarapetis** [hashicorp/terraform#29365]
### Terraform Version

```
Terraform v1.0.4
on linux_amd64
...
```

### Expected Behavior
When given a source address that does not exist in the state, `terraform state mv` should exit with a non-zero code to signal failure.

### Actual Behavior
An error is printed but 0 is returned.

### Steps to Reproduce
1. touch blank.tf
2. terraform init
3. terraform apply
4. terraform state mv foo.bar1 foo.bar2

It looks like this is an oversight in [state_mv.go](https://github.com/hashicorp/terraform/blob/120629848761f5434c75b9876a030f8145abf043/internal/command/state_mv.go#L136): in the case where `sourceAddrs` is empty, an error is added to the diags, but the code that checks diags for errors (and returns 1 if any are found) is only inside the loop over `sourceAddrs`, so 1 is never returned. I could supply a simple patch to fix the issue, but I'm following the contribution guidelines by opening an issue first instead.

**Comment by alisdair** [comment]
Thanks for reporting this! I can confirm the issue. There is a pending PR to fix it at #29839.

**Comment by alisdair** [comment]
The fix for this issue has been merged and will ship in the next Terraform 1.1 patch release.
