### ISSUE TITLE
provider/aws crash on 0.6.2-dev

### ISSUE THREAD

**Issue by dlsniper** [hashicorp/terraform#2936]
Hi,

I've got the following situation:

- created tf file and ran 0.6.1 on it
- compiled 41c732dd6c7e2d32f73c56cf6b15c02633501aee
- uncommented the line with ```termination_policies```
- ran the new binaries on the same file with ```terraform plan```
- ran 0.6.1 plan on the same file with the changes and nothing happened (I've used the compiled version from https://www.terraform.io/downloads.html)

Panic: ```panic: interface conversion: interface {} is nil, not *aws.AWSClient```

Terraform file: http://pastebin.com/n2Rng2hv

Crash log: http://pastebin.com/eVW8UUtv

Please let me know if I can provide any further details if needed.

EDIT:
- github.com/aws/aws-sdk-go version is ```1c75632eb9b77bb3d8e6416fbd8f3e98fc1367db```
- github.com/awslabs/aws-sdk-go/aws version is ```1c75632eb9b77bb3d8e6416fbd8f3e98fc1367db```

Also it seems that the awslabs/aws-go-sdk is used in only one place, I'll try replacing it with the aws/aws-sdk-go one and see what happens.

**Comment by catsby** [comment]
Hello –

Thank you for writing in, and I apologize for the delay in getting back to you.
At this time we're on version 0.6.7 of Terraform, so quite a bit has changed!

Thank you for the example configuration, that's incredibly helpful. I applied it with Terraform v0.6.1 and then ran the same plan with the latest release, and things worked as expected, Terraform wanted to apply the termination polices. 

That all said, I'm going to close this issue as unreproducible. Thanks!
