### ISSUE TITLE
azurerm_data_factory

### ISSUE THREAD

**Issue by DysonGates** [hashicorp/terraform#29363]
We appear to have come across an issue with Terraform / Azure.

Terraform version : v1.04
AzureRM version : v2.72.0

We can create an Azure Data Factory with Global Parameters, all is good, the deployments work successfully.
But, if someone makes a change to the Global Parameters via the portal, Terraform fails with any Global Parameter that was configured as an Int or Bool.

![image](https://user-images.githubusercontent.com/43134512/129219221-005efa49-cf89-4705-b213-f793eed26cbb.png)

![image](https://user-images.githubusercontent.com/43134512/129219298-0616fa4f-148a-43e4-9b71-77099e0ea558.png)

![image](https://user-images.githubusercontent.com/43134512/129219351-947171de-eab7-4b47-9f7c-c49e5489fa6e.png)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
