### ISSUE TITLE
Remote state incorrectly configured with S3 folders

### ISSUE THREAD

**Issue by thegedge** [hashicorp/terraform#2937]
It seems like initializing S3 remote state with an existing remote state file doesn't work. It seems to download the correct initial state, but sets the key incorrectly in the state file:

```
$ terraform remote config --backend=S3 --backend-config="bucket=terraform" --backend-config="key=us-east-1/test/apps/foo"
Initialized blank state with remote state enabled!
Remote state configured and pulled.
$ cat .terraform/terraform.tfstate
{
    "version": 1,
    "serial": 4,
    "remote": {
        "type": "s3",
        "config": {
            "bucket": "terraform",
            "key": "foo",
            "region": "us-east-1"
        }
    },
    ...actual state from us-east-1/test/apps/foo...
}
```

**Comment by thegedge** [comment]
I think I know why this is happening. We shuffled our state around some in S3 to be better prepared for future state files. When we initialize the remote state it downloads the file, including the "remote" section of the state file, which will still point to the old location.

Should `terraform remote config` pull the existing remote state but ignore the "remote" section, keeping what was specified on the command line?

**Comment by antonosmond** [comment]
We had exactly the same issue earlier today - confused the hell out of me! Following a move of the state files in s3 a couple of days ago, I had deleted the old s3 folder, checked my scripts with the remote config were correct, ran some terraform actions and the old folder was reappearing in s3. I was baffled for a while before I realised what was happening. As @thegedge explained, the fact the s3 config is stored in the .tfstate file is a problem if you ever want to move your state files. It means you have to remember to manually change the state files.

**Comment by joescii** [comment]
I'm playing around with remote config for the first time and I discovered that if I manually put my existing config into the S3 bucket, then it is rejected because it does not contain the remote config.  (I know that you can switch from local to remote to handle this, but I was trying to figure out why it wasn't working against the us-west-1 region)

**Comment by jleclanche** [comment]
This is probably less relevant in the new backend system.

**Comment by apparentlymart** [comment]
Indeed @jleclanche, with the new backend system the remote config is stored separately from the state and so this should no longer be an issue.

As @thegedge guessed this issue resulted from the (in retrospect) troublesome decision to mix the remote config and the state into a single structure which ended up getting persisted to the remote backend. As of 0.9 there is no local state cache file when remote state is enabled and the remote config is kept in a file that *looks like* a state file for transitional reasons but is maintained separately.

Apologies for letting this sit here for so long, and thanks for everyone's patience while we shuffled around some of Terraform's architecture to address this problem!
