### ISSUE TITLE
Default value of Property public_network_access_enabled of resource azurerm_databricks_workspace, forces to recreate the resource again and again

### ISSUE THREAD

**Issue by rakeshaggarwal1980** [hashicorp/terraform#29378]
### Terraform Version
Terraform v0.13.0

### Terraform Configuration Files

resource "azurerm_resource_group" "example-databricks" {
  name     = "example-databricks-resources"
  location = "West Europe"
}

resource "azurerm_databricks_workspace" "example-databricks" {
  name                = "databricks-test"
  resource_group_name = azurerm_resource_group.example-databricks.name
  location            = azurerm_resource_group.example-databricks.location
  sku                 = "standard"
  tags = {
    Environment = "Production"
  }
}

### Crash Output
There is no crash in this case, as it is destroying the existing resource and recreating it again, if running 'terraform apply' command again and there is no failure at all

### Terraform Plan Before Rewriting of the resource

{
    "format_version": "0.1",
    "terraform_version": "0.13.5",
    "variables": {
    }, 
          
    "planned_values": {
       "root_module": {
          "resources": [
             {
                "address": "azurerm_databricks_workspace.example-databricks",
                "mode": "managed",
                "type": "azurerm_databricks_workspace",
                "name": "example-databricks",
                "provider_name": "registry.terraform.io/hashicorp/azurerm",
                "schema_version": 0,
                "values": {
                   "customer_managed_key_enabled": false,
                   "infrastructure_encryption_enabled": false,
                   "load_balancer_backend_address_pool_id": null,
                   "location": "westeurope",
                   "managed_services_cmk_key_vault_key_id": null,
                   "name": "databricks-test",
                   "public_network_access_enabled": true,
                   "resource_group_name": "example-databricks-resources",
                   "sku": "standard",
                   "tags": {
                      "Environment": "Production"
                   },
                   "timeouts": null
                }
             },
             {
                "address": "azurerm_resource_group.example-databricks",
                "mode": "managed",
                "type": "azurerm_resource_group",
                "name": "example-databricks",
                "provider_name": "registry.terraform.io/hashicorp/azurerm",
                "schema_version": 0,
                "values": {
                   "id": "/subscriptions/XXXXXX/resourceGroups/example-databricks-resources",
                   "location": "westeurope",
                   "name": "example-databricks-resources",
                   "tags": {},
                   "timeouts": null
                }
             }
          ]
       }
    },
    "resource_changes": [
       {
          "address": "azurerm_databricks_workspace.example-databricks",
          "mode": "managed",
          "type": "azurerm_databricks_workspace",
          "name": "example-databricks",
          "provider_name": "registry.terraform.io/hashicorp/azurerm",
          "change": {
             "actions": [
                "delete",
                "create"
             ],
             "before": {
                "custom_parameters": [
                   {
                      "machine_learning_workspace_id": "",
                      "nat_gateway_name": "nat-gateway",
                      "no_public_ip": false,
                      "private_subnet_name": "",
                      "private_subnet_network_security_group_association_id": "",
                      "public_ip_name": "nat-gw-public-ip",
                      "public_subnet_name": "",
                      "public_subnet_network_security_group_association_id": "",
                      "storage_account_name": "dbstorageaifs5gs73fjtu",
                      "storage_account_sku_name": "Standard_GRS",
                      "virtual_network_id": "",
                      "vnet_address_prefix": "10.139"
                   }
                ],
                "customer_managed_key_enabled": false,
                "id": "/subscriptions/XXXXXX/resourceGroups/example-databricks-resources/providers/Microsoft.Databricks/workspaces/databricks-test",
                "infrastructure_encryption_enabled": false,
                "load_balancer_backend_address_pool_id": null,
                "location": "westeurope",
                "managed_resource_group_id": "/subscriptions/XXXXXX/resourceGroups/databricks-rg-example-databricks-resources",
                "managed_resource_group_name": "databricks-rg-example-databricks-resources",
                "managed_services_cmk_key_vault_key_id": null,
                "name": "databricks-test",
                "network_security_group_rules_required": null,
                "public_network_access_enabled": false,
                "resource_group_name": "example-databricks-resources",
                "sku": "standard",
                "storage_account_identity": [],
                "tags": {
                   "Environment": "Production"
                },
                "timeouts": null,
                "workspace_id": "XXXXXX",
                "workspace_url": "adb-XXXXXX.12.azuredatabricks.net"
             },
             "after": {
                "customer_managed_key_enabled": false,
                "infrastructure_encryption_enabled": false,
                "load_balancer_backend_address_pool_id": null,
                "location": "westeurope",
                "managed_services_cmk_key_vault_key_id": null,
                "name": "databricks-test",
                "public_network_access_enabled": true,
                "resource_group_name": "example-databricks-resources",
                "sku": "standard",
                "tags": {
                   "Environment": "Production"
                },
                "timeouts": null
             },
             "after_unknown": {
                "custom_parameters": true,
                "id": true,
                "managed_resource_group_id": true,
                "managed_resource_group_name": true,
                "network_security_group_rules_required": true,
                "storage_account_identity": true,
                "tags": {},
                "workspace_id": true,
                "workspace_url": true
             }
          }
       },
       {
          "address": "azurerm_resource_group.example-databricks",
          "mode": "managed",
          "type": "azurerm_resource_group",
          "name": "example-databricks",
          "provider_name": "registry.terraform.io/hashicorp/azurerm",
          "change": {
             "actions": [
                "no-op"
             ],
             "before": {
                "id": "/subscriptions/XXXXXX/resourceGroups/example-databricks-resources",
                "location": "westeurope",
                "name": "example-databricks-resources",
                "tags": {},
                "timeouts": null
             },
             "after": {
                "id": "/subscriptions/XXXXXX/resourceGroups/example-databricks-resources",
                "location": "westeurope",
                "name": "example-databricks-resources",
                "tags": {},
                "timeouts": null
             },
             "after_unknown": {}
          }
       }
    ],
    "prior_state": {
       "format_version": "0.1",
       "terraform_version": "0.13.5",
       "values": {
          "root_module": {
             "resources": [
                {
                   "address": "azurerm_databricks_workspace.example-databricks",
                   "mode": "managed",
                   "type": "azurerm_databricks_workspace",
                   "name": "example-databricks",
                   "provider_name": "registry.terraform.io/hashicorp/azurerm",
                   "schema_version": 0,
                   "values": {
                      "custom_parameters": [
                         {
                            "machine_learning_workspace_id": "",
                            "nat_gateway_name": "nat-gateway",
                            "no_public_ip": false,
                            "private_subnet_name": "",
                            "private_subnet_network_security_group_association_id": "",
                            "public_ip_name": "nat-gw-public-ip",
                            "public_subnet_name": "",
                            "public_subnet_network_security_group_association_id": "",
                            "storage_account_name": "dbstorageaifs5gs73fjtu",
                            "storage_account_sku_name": "Standard_GRS",
                            "virtual_network_id": "",
                            "vnet_address_prefix": "10.139"
                         }
                      ],
                      "customer_managed_key_enabled": false,
                      "id": "/subscriptions/XXXXXX/resourceGroups/example-databricks-resources/providers/Microsoft.Databricks/workspaces/databricks-test",
                      "infrastructure_encryption_enabled": false,
                      "load_balancer_backend_address_pool_id": null,
                      "location": "westeurope",
                      "managed_resource_group_id": "/subscriptions/XXXXXX/resourceGroups/databricks-rg-example-databricks-resources",
                      "managed_resource_group_name": "databricks-rg-example-databricks-resources",
                      "managed_services_cmk_key_vault_key_id": null,
                      "name": "databricks-test",
                      "network_security_group_rules_required": null,
                      "public_network_access_enabled": false,
                      "resource_group_name": "example-databricks-resources",
                      "sku": "standard",
                      "storage_account_identity": [],
                      "tags": {
                         "Environment": "Production"
                      },
                      "timeouts": null,
                      "workspace_id": "XXXXXXX",
                      "workspace_url": "adb-XXXXXX.12.azuredatabricks.net"
                   },
                   "depends_on": [
                      "azurerm_resource_group.example-databricks"
                   ]
                },
                {
                   "address": "azurerm_resource_group.example-databricks",
                   "mode": "managed",
                   "type": "azurerm_resource_group",
                   "name": "example-databricks",
                   "provider_name": "registry.terraform.io/hashicorp/azurerm",
                   "schema_version": 0,
                   "values": {
                      "id": "/subscriptions/XXXXXX/resourceGroups/example-databricks-resources",
                      "location": "westeurope",
                      "name": "example-databricks-resources",
                      "tags": {},
                      "timeouts": null
                   }
                },
                {
                   "address": "data.azurerm_client_config.current",
                   "mode": "data",
                   "type": "azurerm_client_config",
                   "name": "current",
                   "provider_name": "registry.terraform.io/hashicorp/azurerm",
                   "schema_version": 0,
                   "values": {
                      "client_id": "XXXXXX",
                      "id": "2021-08-11 06:45:54.6665304 +0000 UTC",
                      "object_id": "XXXXXX",
                      "subscription_id": "XXXXXX",
                      "tenant_id": "***",
                      "timeouts": null
                   }
                },
                {
                   "address": "data.azurerm_subscription.primary",
                   "mode": "data",
                   "type": "azurerm_subscription",
                   "name": "primary",
                   "provider_name": "registry.terraform.io/hashicorp/azurerm",
                   "schema_version": 0,
                   "values": {
                      "display_name": "sub-dp-das-prod",
                      "id": "/subscriptions/XXXXXX",
                      "location_placement_id": "Public_2014-09-01",
                      "quota_id": "CSP_2015-05-01",
                      "spending_limit": "Off",
                      "state": "Enabled",
                      "subscription_id": "XXXXXX",
                      "tags": {},
                      "tenant_id": "***",
                      "timeouts": null
                   }
                }
             ]
          }
       }
    },
    "configuration": {
       "provider_config": {
          "azuread": {
             "name": "azuread",
             "version_constraint": "=0.7.0",
             "expressions": {
                "client_id": {
                   "constant_value": "__clientid__"
                },
                "subscription_id": {
                   "constant_value": "__subscriptionid__"
                },
                "tenant_id": {
                   "constant_value": "__tenantid__"
                }
             }
          },
          "azurerm": {
             "name": "azurerm",
             "version_constraint": "2.71.0",
             "expressions": {
                "client_id": {
                   "constant_value": "XXXXXX"
                },
                "client_secret": {
                   "constant_value": "XXXXXX"
                },
                "features": [
                   {}
                ],
                "subscription_id": {
                   "constant_value": "XXXXXX"
                },
                "tenant_id": {
                   "constant_value": "***"
                },
                "use_msi": {
                   "constant_value": true
                }
             }
          }
       },
       "root_module": {
          "resources": [
             {
                "address": "azurerm_databricks_workspace.example-databricks",
                "mode": "managed",
                "type": "azurerm_databricks_workspace",
                "name": "example-databricks",
                "provider_config_key": "azurerm",
                "expressions": {
                   "location": {
                      "references": [
                         "azurerm_resource_group.example-databricks"
                      ]
                   },
                   "name": {
                      "constant_value": "databricks-test"
                   },
                   "public_network_access_enabled": {
                      "constant_value": true
                   },
                   "resource_group_name": {
                      "references": [
                         "azurerm_resource_group.example-databricks"
                      ]
                   },
                   "sku": {
                      "constant_value": "standard"
                   },
                   "tags": {
                      "constant_value": {
                         "Environment": "Production"
                      }
                   }
                },
                "schema_version": 0
             },
             {
                "address": "azurerm_resource_group.example-databricks",
                "mode": "managed",
                "type": "azurerm_resource_group",
                "name": "example-databricks",
                "provider_config_key": "azurerm",
                "expressions": {
                   "location": {
                      "constant_value": "West Europe"
                   },
                   "name": {
                      "constant_value": "example-databricks-resources"
                   }
                },
                "schema_version": 0
             },
             {
                "address": "data.azurerm_client_config.current",
                "mode": "data",
                "type": "azurerm_client_config",
                "name": "current",
                "provider_config_key": "azurerm",
                "schema_version": 0
             },
             {
                "address": "data.azurerm_subscription.primary",
                "mode": "data",
                "type": "azurerm_subscription",
                "name": "primary",
                "provider_config_key": "azurerm",
                "schema_version": 0
             }
          ],
          "variables": {
            }
       }
    }
 }

### Expected Behavior
If using the default value for the property public_network_access_enabled then resource should  create successfully on running 'terraform apply' command and again running the same command should not drop the resource and recreate it again.

### Actual Behavior

Using default value for the property public_network_access_enabled recreates the resource if running 'terraform apply' command again

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`
3. `terraform apply`

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
