### ISSUE TITLE
Terraform wants to destroy an instance because of a new volume from snapshot attached

### ISSUE THREAD

**Issue by hostedvideorn** [hashicorp/terraform#29371]
### Terraform Version

```
Terraform Enterprise
```

### Backup problem

When we provision a EC2 instance with let's say 2 volumes via TFE, the instance gets created along the volumes and everything has its own IDs. Later we take snapshots of the volumes for backups

When we want to restore a volume we create one from the snapshot - here is a problem because it is a NEW volume it gets a NEW ID. Then if we attach this new volume to the instance, TFE will want to destroy it and creates a new instance because it is seeing a different ID for that particular volume.

### Expected Behavior

I was wondering how we could this to avoid TFE from destroying the instance and from wanting to create a new one just because of the volume that was replaced by a new one from a snapshot.

### Actual Behavior

TFE will want to destroy it and creates a new instance because it is seeing a different ID for that particular volume.
**NOTE: This does not happen with the root volume that can be restored from a snapshot**

### Steps to Reproduce

**Instance creation**
1. `terraform init`
2. provision a new instance with 2 volumes (A, B) attached + root via TFE (code) - aws_instance, etc
3. `terraform apply`

root - /dev/sda1
EBS A - /dev/sdf
EBS B - /dev/sdg

**Adding new root volume from snapshot**
4. Create a snapshot of the root volume
5. Create a new volume for this root snapshot
6. Detach the actual root volume (/dev/sda1)
7. Attach the new root volume from the root snapshot to /dev/sda1 - NO PROBLEMS HERE
8. Add a new EBS volume via code (aws_ebs_volume, aws_volume_attachment - C) and run TFE
**- It will create/attach the new volume without any problems and most importantly it will not want to destroy the instance**
Up to this point there are no problems.

**Snapshot of other EBS volumes (A, B)**
9. Create a snapshot of the EBS volume A
10. Create a new volume for this EBS volume A snapshot 
11. Detach the actual EBS volume A (/dev/sdf)
12. Attach the new root volume from the EBS volume A snapshot to /dev/sdf

Here is the problem. If you make any updates to TFE code and run it it will see a different volume ID for /dev/sdf and will want to destroy the instance and create a new one because of 'new resource'

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for support questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. Since you mentioned Terraform Enterprise, you can also file a ticket through the normal support channels in that case. 

Thanks!
