### ISSUE TITLE
Databricks fails with authentication error while using AzureRM 2.69.0 and above

### ISSUE THREAD

**Issue by vigneshkumar50** [hashicorp/terraform#29377]
**Terraform (and AzureRM Provider) Version**
        terraformVersion: 0.14.9
**Affected Resource(s)**
azurerm version : 2.69.0 and above
Panic Output
The issue is not introduced when switching back to 2.68.0.
We are using it for authentication. our code broke after 2.68.0 and more.
Error: authentication is not configured for the provider. Please configure it
through one of the following options:

DATABRICKS_HOST + DATABRICKS_TOKEN environment variables.
host + token provider arguments.
azure_databricks_workspace_id + AZ CLI authentication.
azure_databricks_workspace_id + azure_client_id + azure_client_secret + azure_tenant_id for Azure Service Principal authentication.
Run data bricks configure --token that will create ~/.databrickscfg file.

**Steps to Reproduce**
   terraform apply

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by vigneshkumar50** [comment]
Already raised this issue under the terraform provider azurerm.  
https://github.com/hashicorp/terraform-provider-azurerm/issues/12977

The comments are not the right place to raise the ticket in this place.
