### ISSUE TITLE
Cannot get boot_diagnostics enabled since boot_diagnostics block seems NOT support "enabled=true"

### ISSUE THREAD

**Issue by gkzz** [hashicorp/terraform#29376]
### Terraform Version

```
Terraform v1.0.0
```

### Terraform Configuration Files

```terraform

resource "azurerm_linux_virtual_machine" "main" {
  name                = "tf-vm"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  size                = "Standard_F2"
  admin_username      = "admin_user"
  network_interface_ids = [
    azurerm_network_interface.main.id,
  ]

  boot_diagnostics {
        ## DOES ANYONE KNOW HOW TO FIX IT??
        enabled = "true"
        storage_account_uri = azurerm_storage_account.main.primary_blob_endpoint
  }
}

resource "random_id" "main" {
    keepers = {
        # Generate a new ID only when a new resource group is defined
        resource_group = azurerm_resource_group.main.name
    }

    byte_length = 8
}

resource "azurerm_storage_account" "main" {
    name                        = "diag${random_id.main.hex}"
    location            = azurerm_resource_group.main.location
    resource_group_name         = azurerm_resource_group.main.name
    account_replication_type    = "LRS"
    account_tier                = "Standard"

    tags = {
        environment = "dev"
    }
}
```

Ref: https://github.com/gkzz/azure-provider-terraform-linux/blob/main/main.tf

### Debug Output

```
$ terraform plan
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 99, in resource "azurerm_linux_virtual_machine" "main":
│   99:         enabled = "true"
│ 
│ An argument named "enabled" is not expected here.
╵
$ 
```

```
$ terraform apply
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 99, in resource "azurerm_linux_virtual_machine" "main":
│   99:         enabled = "true"
│ 
│ An argument named "enabled" is not expected here.
╵
$
```

### Expected Behavior

Both of `terraform plan` and `terraform apply` work as usual

### References

- The following Azure document says
  - > Enable managed boot diagnostics using Azure Resource Manager (ARM) templates

```
 "diagnosticsProfile": {
     "bootDiagnostics": {
         "enabled": true
      }
 }
```

Ref: https://docs.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#enable-managed-boot-diagnostics-using-azure-resource-manager-arm-templates

- The following Terraform document also mentions

  - > A boot_diagnostics block supports the following:
    >
    > ・enabled - (Required) ty
    >
    > ・storage_uri - (Required) The Storage Account's Blob Endpoint which should hold the virtual machine's diagnostic files.
    
Ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by gkzz** [comment]
Thanks man!!
