### ISSUE TITLE
data source refresh causes unwanted/unneeded recreation of resource

### ISSUE THREAD

**Issue by imaji** [hashicorp/terraform#29380]
### Terraform Version
```
Terraform v0.14.5
```

### Terraform Configuration Files
```terraform
data “azurerm_key_vault” “key_vault” {
name = var.kv_name
resource_group_name = var.rg_name
}

data “azurerm_key_vault_secret” “key_vault_secret” {
name = var.secret_name
key_vault_id = data.azurerm_key_vault.key_vault.id
}

resource “azurerm_app_service_certificate” “app_service_certificate” {
name = var.cert_name
resource_group_name = var.rg_name
location = var.location
key_vault_secret_id = data.azurerm_key_vault_secret.key_vault_secret.id

tags = var.tags
}
```

### Expected Behavior
After the first creation, the azurerm_app_service_certificate should not be recreated, as the underlying certificate has not been changed in the Azure Vault.

### Actual Behavior
Terraform core is refreshing the data source, which makes it think that the ID has changed, so when the plan is performed it thinks it needs to recreate the certificate as the ID is in theory new.

The reason for this is the change of the key_vault_secret_id requires a recreation of the certificate, which on a production system isn't great as the service temporarily disappears.

### Steps to Reproduce
1. Have an Azure Account
2. Have a certificate for an application service exist inside a azure key vault
3. Setup a terraform file that creates an azure app service and uses a certificate on a certificate binding for that service
4. terraform plan

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by imaji** [comment]
Hi,

I've actually been directed over here, as they say it's a problem with the terraform core refreshing data sources when reading them in.

They say they can't fix it, as it's the core at fault, not the provider code.

**Comment by imaji** [comment]
I'll raise it there...

**Comment by jbardin** [comment]
Hi @imaji,

This is the intended behavior of data sources in terraform. Data sources refreshed during every plan, so if the data source changes each time, other resources using that data source may have changes as well. 

If this is how the resources were designed to be used, then you would have to add `key_vault_secret_id ` to `ignore_changes` in order to prevent each update from changing the resource. I'm not familiar with these resources, but perhaps there are users in the AzureRM community forum with more experience on how to better structure the configuration. 

Thanks!

**Comment by imaji** [comment]
Interesting, thanks.

I've raised on the azure one, lets see what they say :)
