### ISSUE TITLE
Downloaded module files have no file permissions

### ISSUE THREAD

**Issue by xenalite** [hashicorp/terraform#29395]
### Terraform Version
```
1.0.3
```

### Terraform Configuration Files
```terraform
module "conventions" { 
  source              = "<my_https_url>"
}
```

### Debug Output
https://gist.github.com/xenalite/cfc3bdb78fb3aaf80ca0938af68b4ab6

### Expected Behavior
- Downloaded module files should have correct file permissions.

### Actual Behavior
- When downloading a module from a HTTPS URL, the files are downloaded to disk.
- When looking up file permissions on files, all of the file permissions are missing.
- This results in `terraform init` command to fail with the following pipeline errors:
- https://gist.github.com/xenalite/d7b12bfcf7922688592566fa6d8ff314
- Executing `ls -lah -R` on the `.terraform` folder:
- https://gist.github.com/xenalite/47bbe32f0fe988db845ad4ccf769ad71
- All file permissions are missing on downloaded files.

### Steps to Reproduce
- Azure Pipelines Terraform V2 task
- Create a HTTPS module to reference by URL
- Execute `terraform init`

### Additional Context
I am running this terraform process in a CI pipeline in Azure DevOps agent with Docker containers. Terraform installed as part of the Docker image is version 1.0.3. User running inside the container has ID 1001:1001 but also has sudo permissions.

**Comment by jbardin** [comment]
Hi @xenalite,

Thanks for filing the issue. This might be a problem with the upstream go-getter package, but I'd like to verify before we send the issue along. Do you have an example of a module which exhibits this behavior?

Under the hood, modules are usually fetched via an https url and unpacked into the local directory. For example, the popular [aws vpc](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest) module can be fetched via `https://github.com/terraform-aws-modules/terraform-aws-vpc/archive/refs/tags/v3.5.0.zip`, and in fact putting that url directly in the module source results in a usable module with all permissions intact.

**Comment by xenalite** [comment]
You can close. It's unrelated to Terraform.
Related issue: https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/36
