### ISSUE TITLE
azurerm_private_endpoint import returning case sensitive "private_connection_resource_id" which will block terraform import

### ISSUE THREAD

**Issue by gowtham9394** [hashicorp/terraform#29393]
**Terraform v1.0.3**

We are trying to import the `azurerm_private_endpoint` using terraform import in azure. When we run the terraform import command to import private_endpoint, in statefile "private_connection_resource_id" is imported as : "/subscriptions/00000000-0000-0000-0000-000000000000/resource**g**roups/terraform/providers/Microsoft.Storage/storageAccounts/terraadls" 

But in azure portal storage resource id will be  "/subscriptions/00000000-0000-0000-0000-000000000000/resource**G**roups/terraform/providers/Microsoft.Storage/storageAccounts/terraadls"  due to case sensitivity  terraform trying to the destroy and create the private_endpoint resource. 

**Here the code used:**

```
resource "azurerm_private_endpoint" "pvtendpoint" {
  name                = var.private_endpoint_name
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.subnet_id

  private_service_connection {
    name                              = var.private_service_connection_name
    private_connection_resource_id    = var.private_connection_resource_id
    subresource_names                 = var.subresource_names
    is_manual_connection              = var.is_manual_connection
    private_connection_resource_alias = var.private_connection_resource_alias
  }
}
```
 ```
variable "location" {}
 variable "resource_group_name" {}
 variable "subnet_id" {}
 variable "private_service_connection_name" {}
 variable "private_connection_resource_id" {}
 variable "subresource_names" {}
 variable "is_manual_connection" {}
 variable "private_connection_resource_alias" {}
```

```
module "pvtendpoint_terraadlspvtlnk" {
  source                          = "../config/private_endpoint"
  private_endpoint_name           = "terraadlspvtlnk"
  location                        = module.resource_group.resource_group_location
  resource_group_name             = module.resource_group.resource_group_name
  subnet_id                       = module.subnet.subnet1_id
  private_service_connection_name = "terraadlspvtlnk_00964819-0b92-44a7-b1a9-b7bae9e01085"
  private_connection_resource_id  = module.storage_account.storage_account_id
  subresource_names               = ["blob"]
  is_manual_connection            = false
  private_connection_resource_alias = null
}
```

**Comment by jbardin** [comment]
This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
