### ISSUE TITLE
s3 backend complains "Error: ...may require migrating existing state" on add role_arn when no migration seems necessary.

### ISSUE THREAD

**Issue by sgpinkus** [hashicorp/terraform#29390]
### Terraform Version

```
2021-08-17T11:06:29.885+1000 [INFO]  Terraform version: 1.0.4
2021-08-17T11:06:29.885+1000 [INFO]  Go runtime version: go1.16.4
2021-08-17T11:06:29.885+1000 [INFO]  CLI args: []string{"/usr/bin/terraform", "version"}
2021-08-17T11:06:29.885+1000 [INFO]  Loading CLI configuration from /home/sam/.terraform.d/credentials.tfrc.json
2021-08-17T11:06:29.885+1000 [INFO]  CLI command args: []string{"version"}
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.54.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

```

### Terraform Configuration Files
I want to change s3 backend config from this:

```terraform
backend "s3" {
  bucket = "bu8Di-terraform-state"
  region = "ap-southeast-2"
  key = "terraform.tfstate"
  workspace_key_prefix = "dai4A"
}
```

To this:

```terraform
backend "s3" {
  bucket = "bu8Di-terraform-state"
  region = "ap-southeast-2"
  key = "terraform.tfstate"
  workspace_key_prefix = "dai4A"
  role_arn = "arn:aws:iam::12323432:role/SomeRole"
  session_name = "terraform"
}
```

But terraform complains:

```
Initializing the backend...
╷
│ Error: Backend configuration changed
│ 
│ A change in the backend configuration has been detected, which may require migrating existing state.
│ 
│ If you wish to attempt automatic migration of the state, use "terraform init -migrate-state".
│ If you wish to store the current configuration with no changes to the state, use "terraform init -reconfigure".
```

### Expected Behavior
Just access backend storage as a different credentials. No need for any migrations.

### Actual Behavior
Complains about migration asks me to migrate, when it's not clear what's being migrated where, why, or which of the two options to use if any,

### Steps to Reproduce

 1. Have a non empty s3 backend config and config.
 2. Change access controls on bucket thus requiring addition of `role_arn` to s3 backend config.
 3. Try run `terraform init`

**Comment by jbardin** [comment]
Hi @sgpinkus,

Terraform cannot determine what changes in a backend configuration may actually require moving the stored objects themselves, so any change in the configuration will indicate that it may be necessary. If you know that you are not changing the location of the backend storage, then you can use the `-reconfigure` flag.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by sgpinkus** [comment]
Hi @jbardin. I guess it is a bit of a question-y.

> Terraform cannot determine what changes in a backend configuration may actually require moving the stored objects themselves, so any change in the configuration will indicate that it may be necessary. 

I'm not sure why it can't. Just maintain a list of fields a change to which requires and migration or reconfiguration. That's what I was getting at. I guess it's a feature request not a bug though.

>  If you know that you are not changing the location of the backend storage, then you can use the -reconfigure flag.

Cool thanks. So just do a -reconfigure. If it's just a matter of doing this then this issue is N/A. I was scared I would somehow mess up or blow away my state using that. The help says:

> -reconfigure            Reconfigure the backend, ignoring any saved  configuration.

Sounds kind like it's going to blow away my state, but I'll take your word for it.
