### ISSUE TITLE
Terraform not supporting ES saml option

### ISSUE THREAD

**Issue by sachinpate007** [hashicorp/terraform#29403]
I am including SAML option for ES in terraform. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain_saml_options

I am using terraform version 12.29 and aws provider version as "3.54.0". It is giving me error:

The provider provider.aws does not support resource type
"aws_elasticsearch_domain_saml_options"

**Comment by jbardin** [comment]
This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
