### ISSUE TITLE
Module source field

### ISSUE THREAD

**Issue by jedineeper** [hashicorp/terraform#2940]
Hi guys,

Is it possible to enable variable interpolation on the "source" parameter for modules? We've recently implemented these in a new series of environments and would like to insert variables into the source URL for the following use cases;

* the value of <tag> in "?ref=<tag>" for git sources
* inserting passwords into https requests to private git repositories; eg;

`source = "git::https://ro-user:${var.git_pwd}@github.com/private-org/private-repo//module-womble?ref=${var.womble-version}"`

or even...

`source = "$format("git::https://%s:%s@github.com/private-org/private-repo//module-womble?ref=%s",var.user, var.pwd, var.tag)"`

Thanks!
Craig

**Comment by phinze** [comment]
Hi Craig,

This definitely makes sense as a feature. Tagged and we'll see what we can do to get this done!

**Comment by joescii** [comment]
+1. I was just on my way over to suggest the same feature.

In my case, I wanted to have modules defined for regions (such as [this us-west-1](https://github.com/joescii/aws-terraform-modules/tree/master/us-west-1)) and then let a `region` var select the template:

```
variable "region" {
  default = "us-west-1"
}
```

```
module "region" {
  source = "github.com/joescii/aws-terraform-modules/${var.region}"
}
```

**Comment by phinze** [comment]
dup of #1439 - merging!
