### ISSUE TITLE
crash during terraform destroy

### ISSUE THREAD

**Issue by gposton** [hashicorp/terraform#2941]
➜  skippy git:(master) ✗ terraform --version
Terraform v0.5.3

Your version of Terraform is out of date! The latest version
is 0.6.1. You can update by downloading from www.terraform.io

crash.log: https://gist.github.com/gposton/483a4496aca3ecfc491c

Command Output: https://gist.github.com/gposton/adecf8c82774b1e4685b

**Comment by dlsniper** [comment]
Have you tried to see if this happens with 0.6.1? It's been close to four months since 0.5.3 as far as I can see so maybe the issue was fixed meanwhile.

**Comment by gposton** [comment]
This was a one time issue on 0.5.3.  I just wanted to report it for tracking.  I just upgraded to 0.6.1... I'll update this ticket if I see it again.

**Comment by phinze** [comment]
Hey folks! Feel free to follow up if you do see it on a later version of TF - closing in the meantime. :+1:
