### ISSUE TITLE
AWS EC2 instance public IP address is not updated on instance type change

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform#29424]
I have the following piece of the configuration:

```
resource "aws_instance" "control" {
  ami = data.aws_ami.control.id
  instance_type = "t2.micro"
  subnet_id = module.vpc.public1_subnet_id
  associate_public_ip_address = true
  vpc_security_group_ids = [
    aws_security_group.control.id
  ]
}

resource "aws_route53_record" "control" {
  name = "control"
  type = "A"
  zone_id = data.aws_route53_zone.tld.id
  records = [aws_instance.control.public_ip]
  ttl = 300
}
```

The idea here is that the record must have the instance's public IP address. And it worked well. Then I changed the instance type to `t2.nano` and Terraform has created the following plan:

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  # aws_instance.control will be updated in-place
  ~ resource "aws_instance" "control" {
        id                                   = "i-0f0cca024bef87452"
      ~ instance_type                        = "t2.micro" -> "t2.nano"
        # (28 unchanged attributes hidden)
        # (5 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

You may see here that TF has changed the instance instead of replacing it. In the reality, the instance is replaced and gets a new public IP address. But this change is not reflected in the plan and after executing, the infrastructure becomes broken because the DNS record remains to have an old invalid IP address.

### Terraform Version
1.0.3 Docker

### Expected Behavior
EC2 instance is replaced in TF state.
Route 53 record is updated with the new instance's IP address.

### Actual Behavior
EC2 instance is not replaced in TF state.
Route 53 record is not updated with the new instance's IP address.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
