### ISSUE TITLE
Error creating API Gateway Integration Response: NotFoundException: Invalid Method identifier specified

### ISSUE THREAD

**Issue by cloudhubzawsaz** [hashicorp/terraform#29422]
Terraform Version
Terraform v1.0.2

Affected Resource(s)
aws_api_gateway_method
aws_api_gateway_integration
aws_api_gateway_integration_response

Terraform Configuration Files
https://gist.github.com/cloudhubzawsaz/21e341067e9092267e248e31522c6390

Debug Output
Error applying plan:

1 error(s) occurred:

│ Error: Error creating API Gateway Integration Response: NotFoundException: Invalid Method identifier specified
│ 
│   with aws_api_gateway_integration_response.dummy,
│   on main.tf line 112, in resource "aws_api_gateway_integration_response" "dummyResponse":
│  112: resource "aws_api_gateway_integration_response" "dummyResponse" {
│ 

Expected Behaviour
All resources created successfully.

Actual Behaviour
When running terraform apply the above error is produced stating the Invalid Method identifier specified. I created all the depends_on as suggested by other Issues in GitHub .

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
