### ISSUE TITLE
Stablize the yamlencode function output

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#29436]
Back when we originally introduced `yamlencode`, circa the v0.12 release, we included a note in its documentation that the exact layout of its output was subject to change in future releases and so not to use it in situations that would react poorly to such changes:

> **Warning:** This function is currently experimental and its exact result format may change in future versions of Terraform, based on feedback. Do not use `yamldecode` to construct a value for any resource argument where changes to the result would be disruptive. To get a consistent string representation of a value use `jsonencode` instead; its results are also valid YAML because YAML is a JSON superset.

The motivation for this leeway arose from the fact that YAML is a relatively complex language (in comparison to, say, JSON) and so we expected that we'd need to make some pragmatic adjustments to allow for quirks in other YAML _parser_ implementations, to try to maximize interop with other systems that consume YAML. In the intervening time we have made some small adjustments to both `yamlencode` and `yamldecode`, but nothing particularly substantial.

In practice, we're now treating `yamlencode` as _largely_ frozen, because although the letter of our documented exception would allow it we don't actually have any wish to churn existing uses of `yamlencode` for any purely-stylistic reasons, and so the bar for changing it at this point is high. Specifically, I expect we'd only change it if we found that it either had a significant bug where it's producing a result that isn't valid per the YAML spec, or if there were a YAML parser elsewhere that is commonly used within software relevant to Terraform's use-cases (infrastructure tools) which can't reliably parse our `yamldecode` output _even if_ it's valid per the YAML spec.

This issue represents further raising that bar to say that the current output of `yamlencode` for a given input is effectively frozen under the Terraform v1.0 Compatibility Promises _unless_ the change is to address behavior that's inconsistent with the YAML specification _and_ the benefit of fixing it outweighs the costs when considering the behavior of existing third-party YAML parsers. To make that more specific:

* If we learn that `yamlencode` produces something that isn't valid per the YAML spec then our first order of business would be to understand why we hadn't previously been aware of that. If the outcome is that common YAML parsers in the wild are more tolerant than the YAML spec requires then we would likely conclude that the benefit of fixing the bug is outweighed by the cost of breaking compatibility. If the outcome is that the bug only occurs in a rarely-encountered edge case and that common YAML parser in the wild _can't_ parse the buggy output then we would likely move to fix the bug, even at the risk of impacting modules that are already generating invalid YAML in that edge case.
* If we learn that `yamlencode` produces something that _is_ valid per the YAML spec but yet still can't be parsed correctly by some particular third-party YAML parser, we would now typically _not_ change the `yamlencode` behavior and instead propose that the third party update their parser implementation to be more compliant with the specification.

Although the experiment warning in the documentation isn't specific about what situations it's talking about, I want to be clear here that _one_ major motivating use-case for this stabilization is to de-risk the use of `yamlencode` in userdata/metadata features in common cloud providers when producing [cloud-init's "Cloud config" language](https://cloudinit.readthedocs.io/en/latest/topics/examples.html), which typically requires including an additional YAML comment and thus isn't a suitable situation for using JSON instead:

```hcl
  user_data = <<-EOT
    #cloud-config
    ${yamlencode({
      packages = [
        "mysql-client",
      ]
    })}
  EOT
```

`user_data` in EC2, and its equivalent in most/all other cloud VM systems, is an argument which can be changed only by replacing the corresponding virtual machine with a fresh one, because cloud-init processes it only on system boot. However, from the cloud provider level of abstraction it's just an opaque string or sequence of bytes, and thus there's no scope for any classification of two inputs as functionally-equivalent. It's therefore a particularly sensitive situation when it comes to churn, and so a configuration like the above would be against the current recommendation in the docs.

---

However, before we do this we ought to first try to conclude some due diligence related to the existing issue #23322.

That was originally opened to discuss making the `yamlencode` output configurable, but as I already noted over there we don't intend to do that because YAML encoding is a relatively-minor programmatic integration point from Terraform's perspective, rather than a big part of it's scope, and so the cost of implementing and maintaining a highly-configurable YAML encoder (particularly under 1.0 compatibility promises as discussed here) is too high.

However, there was some other commentary in that issue about how some `yamlencode` output is causing non-specific problems with specific external software. I asked the participants in that issue to share some more concrete examples, but at the time of writing nobody has done so.

Given that, I think our best path forward would be to spend some time with the specific software mentioned (Ansible, and Kubernetes config maps) to see if we can reproduce any such problems ourselves. If we can then we can discuss here any tactical changes we might want to make to `yamlencode`'s current behavior (while preserving our goal of minimizing unjustified churn).

If we can't reproduce any such problems, and if nobody in the other issue comes forward with a specific example in the meantime, then I suggest we move forward with stabilization of the current implementation and then respond to any late-arriving feedback per the principles I described above, and within the principles of our 1.0 Compatibility Promises.

**Comment by nfi-opsguru** [comment]
As I mentioned in https://github.com/hashicorp/terraform/issues/23322#issuecomment-1105608660, I am hard-pressed to think of an example resource API that accepts YAML that actually extends beyond JSON-compatible, and would not therefore be better-served by using actual JSON, besides the aforementioned `cloud-init`.

The `aws_auth` map example above could be JSON.

So I'd say `yamlencode` should just have a big warning that encourages users to use the (presumably stable) `jsonencode` instead, where possible.
