### ISSUE TITLE
Terraform Destroy EKS cluster with vpc,subnets & internet gateway

### ISSUE THREAD

**Issue by saikrishna2733** [hashicorp/terraform#29458]
### Terraform Version

```
Terraform v1.0.5

```

### Terraform Configuration Files

```terraform
Repo: https://github.com/saikrishna2733/terraform-aws-eks/
Branch : CICD
```

### Crash Output

Repo: https://github.com/saikrishna2733/terraform-aws-eks/
Branch : tf-bug1

### Expected Behavior

When the user destroys the resources using the terraform destroy command it should delete the resources.
### Actual Behavior

It is unable to destroy some of the resources because in the process of eks cluster creation using terraform & Helm, it is creating a load balancer resource which is depending on some of the resources and is not getting updated in the terraform state.
Hence, Terraform is unable to delete some of the resources,
### Additional Context

Issue story
Resources that am creating using terraform are as follows.
1.VPC
2. Subnets,
3. Internet gateway
4. security hub
5. EKS cluster
6. EKS node group
7. IAM roles
8. code commit
9. code build
10. code pipeline
11. ECR
12. any other dependent for the above services.

I have created the EKS cluster and I have deployed my sample images into the cluster manually and used it for some time and when i tried to destroy all the resources, some of the network-related resources are not getting deleted. Because, when we deploy a sample image into the cluster, it is creating one load balancer which is acting as a service for the pod or deployment. 

I can replicate this issue, please let me know your comments on this. In case of any queries, please feel comfortable reaching out to me.

**Comment by anarsen** [comment]
If EKS deploys ALBs into either of your subnets then yeah, Terraform or even AWS CLI will not be able to delete those. This is not a Terraform bug but rather how AWS works.

**Comment by crw** [comment]
Hello all, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
