### ISSUE TITLE
support data source for azurerm_backup_policy_file_share

### ISSUE THREAD

**Issue by Frenchie-in-the-trenchies** [hashicorp/terraform#29452]
Hello all,

### Current Terraform Version

Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/azurerm v2.67.0

Your version of Terraform is out of date! The latest version
is 1.0.5. You can update by downloading from https://www.terraform.io/downloads.html

Yes it's out of date, but the feature is not included to the new versions of terraform

### Use-cases

We want to be able to fetch fileshare policies without creating a new one using `data "azurerm_backup_file_share"`.
Because the ressource `azurerm_backup_protected_file_share` aks for a `backup_policy_id` (of the file share policy) , we want to be able to use data source for this argument instead of the ID of the file share policy litteraly.

### Proposal

```
data "azurerm_backup_file_share" "policy" {
  name                = "policy"
  recovery_vault_name = "recovery_vault"
  resource_group_name = "resource_group"
}
```

### References

None

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
