### ISSUE TITLE
aws_apigatewayv2_stage : Null in throttle limit sets value to 0

### ISSUE THREAD

**Issue by sachin-kumar-ik8** [hashicorp/terraform#29454]
Definition of `null` datatype says that a null value represents absence or omission. If you set an argument of a resource or module to null, Terraform behaves as though you had completely omitted it it is setting the value to 0. 

But when I am setting route throttle limit in `aws_apigatewayv2_stage` to null then it becomes 0.

### Terraform configuration

    resource "aws_apigatewayv2_stage" "api_stage" {
       dynamic "route_settings" {
          for_each = var.routes_config
          
          content {
             route_key = var.route_key

            detailed_metrics_enabled = lookup(route_settings.value, "detailed_metrics_enabled", false)
            throttling_burst_limit   = lookup(route_settings.value, "throttling_burst_limit", null)
           throttling_rate_limit    = lookup(route_settings.value, "throttling_rate_limit", null)
        }
      }
    }
  
  

### Expected Behavior
It should not have set the throttle limit and should have shown as "Not configured" as shown in the screenshot.
<img width="620" alt="Screenshot 2021-08-24 at 6 13 51 PM" src="https://user-images.githubusercontent.com/79145678/130618374-e9460463-5876-49ec-b64a-32492b35ba84.png">

### Actual Behavior
It is setting the default value to 0 when we pass null and in route throttle config 0 means no API request will be allowed.

### Terraform Version
Terraform v1.0.
on darwin_amd64
+provider registry.terraform.io/hashicorp/aws v3.50

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
