### ISSUE TITLE
terraform providers crash with invalid terraform

### ISSUE THREAD

**Issue by ablackrw** [hashicorp/terraform#29455]
### Terraform Version
```
Terraform v1.0.5
on darwin_arm64
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "~> 1.0.0"
}

resource "null_resource" "resource" {

}

resource "null_resource" "resource" {

}
```

### Debug Output
https://gist.github.com/ablackrw/67551577d1e1d28a11328d49e8e3533e

### Crash Output
https://gist.github.com/ablackrw/1fe5c2ffdf884b5abc74ed03afb6e45c

### Expected Behavior
Invocation of `terraform providers lock` succeeds with output similar to following:
``` 
- Obtained hashicorp/null checksums for darwin_arm64 (signed by HashiCorp)

Success! Terraform has updated the lock file.

Review the changes in .terraform.lock.hcl and then commit to your
version control system to retain the new checksums.
```

### Actual Behavior
Invocation of `terraform providers lock` crashes with referenced backtrace.

### Steps to Reproduce
1. `terraform providers lock`

**Comment by jbardin** [comment]
Closing, as I verified this no longer crashes in the latest release.
