### ISSUE TITLE
Default AutoResolveIntegrationRuntime for Azure DataFactory created with public sub_type

### ISSUE THREAD

**Issue by kabal2010** [hashicorp/terraform#29462]
### Terraform Version

```
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.73.0
```

### Terraform Configuration Files

```terraform
resource "azurerm_data_factory" "data_factory" {
  name                            = var.name
  resource_group_name             = data.azurerm_resource_group.resource_group.name
  location                        = data.azurerm_resource_group.resource_group.location
  managed_virtual_network_enabled = var.managed_virtual_network_enabled
  public_network_enabled          = var.public_network_enabled
}
```

### Expected Behavior

Default Integration runtime created;
- Name: *`AutoResolveIntegrationRuntime`*
- Type: *`Azure`*
- Sub-Type: *`Managed Virtual Network`*

### Actual Behavior

Default Integration runtime created;
- Name: *`AutoResolveIntegrationRuntime`*
- Type: *`Azure`*
- Sub-Type: *`Public`*

### Additional Context

- *`managed_virtual_network_enabled`* is set to *`true`*
- *`public_network_enabled`* is set to *`false`*

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by kabal2010** [comment]
@jbardin 
Thanks for pointing me in the right direction.

Best Regards
