### ISSUE TITLE
In action 'Source' is not available in region 'EU_WEST_3'

### ISSUE THREAD

**Issue by bhamichi** [hashicorp/terraform#29471]
Hi there,
I'm getting this error while trying to create aws CodePipeline using terraform. 

Error: Error creating CodePipeline: InvalidActionDeclarationException: ActionType (Category: 'Source', Provider: 'Bitbucket', Owner: 'ThirdParty', Version: '1') in action 'Source' is not available in region 'EU_WEST_3'.

When I check in aws reference, the codepipeline is handled in region Paris : https://aws.amazon.com/fr/about-aws/global-infrastructure/regional-product-services/

Also, when I try to create it manually it's working fine.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
