### ISSUE TITLE
 The plugin returned an unexpected error from plugin.(*GRPCProvider).ConfigureProvider

### ISSUE THREAD

**Issue by som-nitjsr** [hashicorp/terraform#29474]
On My windows 10 Machine I was running terraform  for azure and was able to create my resources and from yesterday I am started getting this error. Even I am getting the same issue in my sample apps.
The code in my sample app is from here.
https://learn.hashicorp.com/tutorials/terraform/azure-build?in=terraform/azure-get-started

PS C:\sns\tf> **terraform init**

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "~> 2.65"...
- Installing hashicorp/azurerm v2.74.0...
- Installed hashicorp/azurerm v2.74.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work. 
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

PS C:\sns\tf> **terraform plan**
╷
│ Error: Plugin error
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 13, in provider "azurerm":
│   13: provider "azurerm" {
│
│ The plugin returned an unexpected error from plugin.(*GRPCProvider).ConfigureProvider: rpc error: code = Internal
│ desc = grpc: error while marshaling: string field contains invalid UTF-8

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
