### ISSUE TITLE
Lookup over map of objects

### ISSUE THREAD

**Issue by mmancebo** [hashicorp/terraform#29487]
I have the following variable

variable "something_info" {
  description = "Host info"
  type = map(object({
    server_name         = string
    instance_type       = string
    assoc_public_ipaddr = bool
    ami_owners          = list(string)
    ami_name            = list(string)
    volume_size         = number
    ingress_list = list(object({
      from_port   = number
      to_port     = number
      protocol    = string
      cidr_blocks = list(string)
    }))
    egress_list = list(object({
      from_port   = number
      to_port     = number
      protocol    = string
      cidr_blocks = list(string)
    }))
  }))
  default = {
    host1 = {
      server_name         = "my_host"
      instance_type       = "t2.small"
      assoc_public_ipaddr = true
      ami_owners          = ["amazon"]
      ami_name            = ["amzn2-ami-hvm-*-x86_64-gp2"]
      volume_size         = 20
      ingress_list = [{
        from_port   = -1
        to_port     = -1
        protocol    = "icmp"
        cidr_blocks = ["0.0.0.0/0"]
        },
        {
          from_port   = 22
          to_port     = 22
          protocol    = "tcp"
          cidr_blocks = ["0.0.0.0/32"]
      }],
      egress_list = [{
        from_port   = 0
        to_port     = 0
        protocol    = "-1"
        cidr_blocks = ["0.0.0.0/0"]
      }]
    }
    host2 = {
      server_name         = "my_host2"
      instance_type       = "t3.xlarge"
      assoc_public_ipaddr = true
      ami_owners          = ["amazon"]
      ami_name            = ["amzn2-ami-hvm-*-x86_64-gp2"]
      volume_size         = 100
      ingress_list = [{
        from_port   = -1
        to_port     = -1
        protocol    = "icmp"
        cidr_blocks = ["0.0.0.0/0"]
        },
        {
          from_port   = 22
          to_port     = 22
          protocol    = "tcp"
          cidr_blocks = ["0.0.0.0/32"]
      }],
      egress_list = [{
        from_port   = 0
        to_port     = 0
        protocol    = "-1"
        cidr_blocks = ["0.0.0.0/0"]
      }]
    }
  }
}

my module is basically like this. 

  for_each            = var.something_info
  ami_name       = each.value["ami_name"]
  ami_owners     = each.value["ami_owners"]
  ec2_tags            = merge(var.tags, { Name = each.value.server_name })
  instance_type       = each.value["instance_type"]
  assoc_public_ipaddr = each.value["assoc_public_ipaddr"]
  volume_size         = each.value["volume_size"]

the thing is, I need to do a lookup to search a specific variable (ingress_list for example) , but I can't find a way to do it, as my lookup says that the variable doesn't exist, is there any other way? 

Thanks in advance

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
