### ISSUE TITLE
Excessively verbose diff when a value changes in a set of blocks

### ISSUE THREAD

**Issue by CyberShadow** [hashicorp/terraform#29498]
I'm trying to use Terraform with https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeters. In my code I have:

```terraform
resource "google_access_context_manager_service_perimeters" "service-perimeters" {
  # ...

  # There is just one perimeter in this access policy, so there is
  # only one service_perimeters block.
  service_perimeters {
    # ...
  }
}
```

The problem is that if a very small change occurs inside the `service_perimeters` block, `terraform plan` produces an unreasonably verbose diff:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_access_context_manager_service_perimeters.service-perimeters must be replaced
-/+ resource "google_access_context_manager_service_perimeters" "service-perimeters" {
      ~ id     = "accessPolicies/123456789012/servicePerimeters" -> (known after apply)
        # (1 unchanged attribute hidden)

      - service_perimeters { # forces replacement
          - name                      = "accessPolicies/123456789012/servicePerimeters/my_project" -> null
          - perimeter_type            = "PERIMETER_TYPE_REGULAR" -> null
          - title                     = "my_project" -> null
          - use_explicit_dry_run_spec = true -> null

          - spec {
              - access_levels       = [
                  - "accessPolicies/123456789012/accessLevels/My_Access_Level",
                ] -> null
              - resources           = [
                  - "projects/234567890123",
                ] -> null
              - restricted_services = [
                  - "service0.googleapis.com",
                  - "service1.googleapis.com",
                  - "service2.googleapis.com",
                  - "service3.googleapis.com",
                  - "service4.googleapis.com",
                  - "service5.googleapis.com",
                  - "service6.googleapis.com",
                  - "service7.googleapis.com",
                ] -> null

              - vpc_accessible_services {
                  - allowed_services   = [] -> null
                  - enable_restriction = true -> null
                }
            }
        }
      + service_perimeters { # forces replacement
          + create_time               = (known after apply)
          + name                      = "accessPolicies/123456789012/servicePerimeters/my_project"
          + perimeter_type            = "PERIMETER_TYPE_REGULAR"
          + title                     = "my-project"
          + update_time               = (known after apply)
          + use_explicit_dry_run_spec = true

          + spec {
              + access_levels       = [
                  + "accessPolicies/123456789012/accessLevels/My_Access_Level",
                ]
              + resources           = [
                  + "projects/234567890123",
                ]
              + restricted_services = [
                  + "service0.googleapis.com",
                  + "service1.googleapis.com",
                  + "service2.googleapis.com",
                  + "service3.googleapis.com",
                  + "service4.googleapis.com",
                  + "service5.googleapis.com",
                  + "service6.googleapis.com",
                  + "service7.googleapis.com",
                ]

              + vpc_accessible_services {
                  + allowed_services   = []
                  + enable_restriction = true
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

It's very difficult to tell that the only thing that changed is `my_project` changing to `my-project` in the `title`.

Is there a possibility to make it produce a structured field-by-field diff like it does in other contexts?

### Terraform Version

```
Terraform v1.0.5
on linux_amd64
```

### Terraform Configuration Files

Happy to try to put together a minimal example on request.

### Debug Output

Happy to produce this from a minimal example on request.

**Comment by apparentlymart** [comment]
Hi @CyberShadow,

It seems like the provider has declared this block type as being represented as a set of objects, which means that the blocks are identified only by their content (not by position in a list, or by a separate key) and so unfortunately Terraform is correct here in reporting that you've removed one object and added another: there is no meaningful sense of updating a set element in place, because changing its content changes its identity.

The provider could represent this block type in some other ways in order to get a different result:
* Declaring this block type as being a list of objects would mean that changing the first element would be understood by Terraform as an in-place update, because both the old and new blocks would both have index zero in the list.
* Declaring this as a singleton block type (where there can only be zero or one blocks) would similarly cause Terraform to understand changes as in-place updates to only that one block.
* Declaring this block type as being a map of objects would make the syntax be something like `service_perimeters "foo"` instead, and then Terraform would use those labels as keys to understand the difference between an in-place update vs. adding or removing an item.

I don't know which of these would be most appropriate for this scenario, and indeed some of these are hard to achieve with the older plugin SDK that the Google Cloud provider currently uses, but ultimately this modelling decision is one made by the provider rather than by Terraform Core and so to change this behavior would require a change to the provider itself. Given that, I'm going to close this but you may wish to open a similar issue in [the Google Cloud Platform provider's repository](https://github.com/hashicorp/terraform-provider-google) to discuss whether one of the options I listed above -- or possibly some other compromise -- would be appropriate here.

**Comment by CyberShadow** [comment]
Hi @apparentlymart,

Thanks for the detailed explanation.

> and so unfortunately Terraform is correct here in reporting that you've removed one object and added another

Sorry. I don't understand how that ties in with the rest of the explanation.

- `google_access_context_manager_service_perimeters.service-perimeters` will be replaced (destroyed then created).
- The `service_perimeters` block will be replaced (destroyed then created).
- Yet, only the former gets a nice `-/+` icon and a per-field breakdown (up to the set of blocks).

I understand that because the set elements don't have an identifier / identity, there is no obviously correct path to diff here. But, that problem seems orthogonal to the observation that the object is being destroyed and re-created, a circumstance which Terraform can represent nicely in its diffs elsewhere.

As for the problem of set elements not having any identity, I can think of ways to address this in Terraform itself.

Would it be reasonable to add a meta-argument to Terraform which gives blocks (which are elements of a set) a key, so that `terraform plan` can thus produce meaningful output?

Alternatively, what about using weighted Levenshtein distance to produce a best-effort diff? A heuristic diff like that would still be technically correct (as long as it still specified that the entire object will be recreated anyway), but much more useful than the status quo.

> you may wish to open a similar issue in [the Google Cloud Platform provider's repository](https://github.com/hashicorp/terraform-provider-google) to discuss whether one of the options I listed above -- or possibly some other compromise -- would be appropriate here.

Thanks for the suggestion. :+1:

**Comment by CyberShadow** [comment]
> Alternatively, what about using weighted Levenshtein distance to produce a best-effort diff? A heuristic diff like that would still be technically correct (as long as it still specified that the entire object will be recreated anyway), but much more useful than the status quo.

A crude beginning towards that direction:

```diff
diff --git a/internal/command/format/diff.go b/internal/command/format/diff.go
index 982b95980..39cd31034 100644
--- a/internal/command/format/diff.go
+++ b/internal/command/format/diff.go
@@ -882,6 +882,30 @@ func (p *blockBodyDiffPrinter) writeNestedBlockDiffs(name string, blockS *config
 			return 0
 		}
 
+		if len(oldItems) == len(newItems) {
+			// If the length is equal, assume there is a 1:1
+			// correspondence between items.
+			for i := 0; i < len(oldItems); i++ {
+				oldValue := oldItems[i]
+				newValue := newItems[i]
+				var action plans.Action
+				if !oldValue.IsKnown() || !newValue.IsKnown() {
+					action = plans.Update
+				} else if oldValue.Equals(newValue) == cty.True {
+					action = plans.NoOp
+				} else {
+					action = plans.DeleteThenCreate
+				}
+
+				path := append(path, cty.IndexStep{Key: oldValue})
+				skipped := p.writeNestedBlockDiff(name, nil, &blockS.Block, action, oldValue, newValue, indent, path)
+				if skipped {
+					skippedBlocks++
+				}
+			}
+			return skippedBlocks
+		}
+
 		allItems := make([]cty.Value, 0, len(oldItems)+len(newItems))
 		allItems = append(allItems, oldItems...)
 		allItems = append(allItems, newItems...)
@@ -1022,8 +1046,8 @@ func (p *blockBodyDiffPrinter) writeNestedBlockDiff(name string, label *string,
 	}
 
 	p.buf.WriteString("\n")
-	p.buf.WriteString(strings.Repeat(" ", indent))
-	p.writeActionSymbol(action)
+	p.buf.WriteString(strings.Repeat(" ", indent-2))
+	p.buf.WriteString(p.color.Color(DiffActionSymbol(action)) + " ")
 
 	if label != nil {
 		fmt.Fprintf(p.buf, "%s %q {", name, *label)
```

It solves the specific problem at hand, and this now causes Terraform to produce a much nicer diff:

```
Terraform will perform the following actions:

  # google_access_context_manager_service_perimeters.service-perimeters must be replaced
-/+ resource "google_access_context_manager_service_perimeters" "service-perimeters" {
      ~ id     = "accessPolicies/123456789012/servicePerimeters" -> (known after apply)
        # (1 unchanged attribute hidden)
    -/+ service_perimeters { # forces replacement
          + create_time               = (known after apply)
            name                      = "accessPolicies/123456789012/servicePerimeters/my_project"
          ~ title                     = "my_project" -> "my-project
          + update_time               = (known after apply)
            # (2 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }
```

BTW, I noticed that there is apparently precedent for doing this kind of best-effort diff:

https://github.com/hashicorp/terraform/blob/05f21cdff8c85bd31f2bb36c524ce9f799e0e2fa/internal/command/format/diff.go#L1208-L1211
