### ISSUE TITLE
aws_route_table - way to add a new route to an existing route table

### ISSUE THREAD

**Issue by antonosmond** [hashicorp/terraform#2949]
I may just need some advice here or maybe this will end up as a feature request, but is there any way to add a route to an existing route table?
Here's my scenario:
Using terraform, I create a VPC which includes a route table.
Then in a separate terraform module, I have a something that'll need a route adding to the VPC route table. I can get the remote state for the VPC and get the route table id, but I want to add a route to it. Can it be done?
If not, would it make sense in future versions of terraform for a route to become a resource in its own right, and just have a required property of route_table_id? Then I guess it would be possible.

**Comment by jedineeper** [comment]
I think https://github.com/hashicorp/terraform/pull/2454 is what you are looking for, its currently WIP.

**Comment by antonosmond** [comment]
That's exactly what we need! Thank you!

**Comment by madAndroid** [comment]
Looking forward to this as well, would come in handy when doing routing between VPCs using peering.

**Comment by catsby** [comment]
I'm going to close this as https://github.com/hashicorp/terraform/pull/2454 looks like what we need here, thanks!
