### ISSUE TITLE
Azure AKS idempotency not working

### ISSUE THREAD

**Issue by vidyasagarreddyc** [hashicorp/terraform#29505]
### Expected Behavior

idempotency, rerunning same IaC code, should not change

### Actual Behavior

Recreate and destroy existing components, when we re run same code

### Steps to Reproduce

Clone repo https://github.com/vidyasagarreddyc/aks_terraform.git
Go to project directory
cd aks_terraform/projects/project
init, plan and apply
terraform init
terraform plan --var-file=./env/dev.tfvars.json
terraform apply -auto-approve --var-file=./env/dev.tfvars.json
Once successfully deployed run again terraform plan without changing any code
terraform plan --var-file=./env/dev.tfvars.json
It will show,
Plan: 1 to add, 1 to change, 1 to destroy.

expected behaviour: 0 add and 0 to destroy

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
