### ISSUE TITLE
Security group lifecycle

### ISSUE THREAD

**Issue by joshgarnett** [hashicorp/terraform#2950]
By default the aws_security_group lifecycle should have create_before_destroy set to true.  When changing the name of a security group that is associated with a live instance, if this flag is not set the terraform apply process hangs.  I can't think of any downside to having this be the default behavior.

**Comment by catsby** [comment]
This is an interesting idea. I don't believe we have support for a default like this (for `create_before_destroy`), but this seems like a valid case. I'm just curious, do you have an example config offhand (minus anything secret of course)?

**Comment by mlrobinson** [comment]
I would say it should create but not attach before destroying. AWS does impose limits to the number of Security groups you can have associated with a given instance at once, but just ordering it as Create New -> Unattach Old -> Attach New -> Destroy Old would be a sufficient work around (and how I would do it by hand anyway).

**Comment by catsby** [comment]
Closing this after some time. I don't believe a consensus on having create_before_destroy was ever reached, as I don't believe we've heard others call for it since. 

Thanks!
