### ISSUE TITLE
azurerm_monitor_diagnostic_setting failing when using eventhub rule id as a destination 

### ISSUE THREAD

**Issue by nourriba** [hashicorp/terraform#29514]
When creating a monitor diagnostic setting and want to use event hub as a destination 

- if I provide eventhub_authorization_rule_id with a value referencing an policy rule on a eventhub namespace 
     Ex : "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{My_eventhub_namespace}/authorizationRules/{MyAaccessPolicyName}"
   everything is working fine 

- if I provide "eventhub_authorization_rule_id with a value referencing an policy rule on a eventhub ( not an eventhub namespace ) 
   | Ex : |"/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}"
     it is failing to parse the id 

      This is the Error Displayed 

      
      │ Error: ID contained more segments than required: "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}", map[eventhubs:{My_eventHub_name}]
      │
      │   with azurerm_monitor_diagnostic_setting.monitor_diagnostic_settings,
      │   on t.tf line 10, in resource "azurerm_monitor_diagnostic_setting" "monitor_diagnostic_settings":
      │   10: eventhub_authorization_rule_id  = "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}"

Example :   
      
resource "azurerm_monitor_diagnostic_setting" "monitor_diagnostic_settings" {

  eventhub_authorization_rule_id  = /subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}
  name                           = "monitor_diagnostic_setting"
  target_resource_id             = "/subscriptions/........."

  log {
     category = "ContainerRegistryRepositoryEvents"
     enabled  = true
     retention_policy {
        days    = 0
        enabled = true
    }
  }
  metric {
    category = "AllMetrics"
    enabled  = false
    retention_policy {
       days    = 0
       enabled = false
    }
  }
}

### Terraform Version
```
Terraform version: 1.0.5
```

 
 

### Crash Output

      │ Error: ID contained more segments than required: "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}"  map[eventhubs:{My_eventHub_name}]
      │
      │   with azurerm_monitor_diagnostic_setting.monitor_diagnostic_settings,
      │   on t.tf line 10, in resource "azurerm_monitor_diagnostic_setting" "monitor_diagnostic_settings":
      │   10: eventhub_authorization_rule_id  = "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}" 

 
### Steps to Reproduce
    replace {..}  with real values 
resource "azurerm_monitor_diagnostic_setting" "monitor_diagnostic_settings" {
  eventhub_authorization_rule_id  = "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}"
  name                           = "monitor_diagnostic_setting"
  target_resource_id             = "/subscriptions/........."

  log {
     category = "ContainerRegistryRepositoryEvents"
     enabled  = true
     retention_policy {
        days    = 0
        enabled = true
    }
  }
  metric {
    category = "AllMetrics"
    enabled  = false
    retention_policy {
       days    = 0
       enabled = false
    }
  }
}

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
