### ISSUE TITLE
Provider "registry.terraform.io/-/apsarastack" produced an invalid plan for apsarastack_db_instance.instance

### ISSUE THREAD

**Issue by lizangstc831** [hashicorp/terraform#29533]
### Terraform Version

```
1.0.3
```

### Terraform Configuration Files

```terraform
export APSARASTACK_ACCESS_KEY="9eviMMKKxVNcDBlU"
export APSARASTACK_DOMAIN="internal.asapi.cn-neimeng-env30-d01.intra.env30.shuguang.com/asapi/v3"
export APSARASTACK_INSECURE="true"
export APSARASTACK_PROXY="HTTP://100.67.76.9:53000"
export APSARASTACK_REGION="cn-neimeng-env30-d01"
export APSARASTACK_RESOURCE_GROUP_SET="ResourceSet(terraform_wy)"
export APSARASTACK_SECRET_KEY="TFILju836GUac9Tr8KR5rs6ImZl8VO"
export TF_ACC=1
export TF_LOG="TRACE"
export DEBUG=",terraform"
```

### Debug Output

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2021/09/07 17:39:41 [TRACE] EvalMaybeTainted: apsarastack_db_instance.instance encountered an error during creation, so it is now marked as tainted
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalWriteState
2021/09/07 17:39:41 [TRACE] EvalWriteState: removing state object for apsarastack_db_instance.instance
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2021/09/07 17:39:41 [TRACE] EvalApplyProvisioners: apsarastack_db_instance.instance has no state, so skipping provisioners
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2021/09/07 17:39:41 [TRACE] EvalMaybeTainted: apsarastack_db_instance.instance encountered an error during creation, so it is now marked as tainted
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalWriteState
2021/09/07 17:39:41 [TRACE] EvalWriteState: removing state object for apsarastack_db_instance.instance
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalIf
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalIf
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2021/09/07 17:39:41 [TRACE] <root>: eval: *terraform.EvalApplyPost
2021/09/07 17:39:41 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Provider produced inconsistent result after apply: When applying changes to apsarastack_db_instance.instance, provider "registry.terraform.io/-/apsarastack" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2021/09/07 17:39:41 [ERROR] <root>: eval: *terraform.EvalSequence, err: Provider produced inconsistent result after apply: When applying changes to apsarastack_db_instance.instance, provider "registry.terraform.io/-/apsarastack" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2021/09/07 17:39:41 [TRACE] [walkApply] Exiting eval tree: apsarastack_db_instance.instance
2021/09/07 17:39:41 [TRACE] vertex "apsarastack_db_instance.instance": visit complete
2021/09/07 17:39:41 [TRACE] dag/walk: upstream of "apsarastack_db_database.db[0]" errored, so skipping
2021/09/07 17:39:41 [TRACE] dag/walk: upstream of "apsarastack_db_readonly_instance.default" errored, so skipping
2021/09/07 17:39:41 [TRACE] dag/walk: upstream of "apsarastack_db_account.account[0]" errored, so skipping
2021/09/07 17:39:41 [TRACE] dag/walk: upstream of "apsarastack_db_connection.connection" errored, so skipping
2021/09/07 17:39:41 [TRACE] dag/walk: upstream of "apsarastack_db_account_privilege.privilege[0]" errored, so skipping
2021/09/07 17:39:41 [TRACE] dag/walk: upstream of "provider.apsarastack (close)" errored, so skipping
2021/09/07 17:39:41 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/09/07 17:39:41 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/09/07 17:39:41 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2021/09/07 17:39:41 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 2
2021/09/07 17:39:41 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate

2021/09/07 17:39:41 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
Error: Provider produced inconsistent result after apply

When applying changes to apsarastack_db_instance.instance, provider
"registry.terraform.io/-/apsarastack" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

2021/09/07 17:39:41 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-09-07T17:39:41.572+0800 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-09-07T17:39:41.575+0800 [DEBUG] plugin: plugin process exited: path=/Users/lizan/Downloads/terraform2/terraform-provider-apsarastack pid=38944
2021-09-07T17:39:41.575+0800 [DEBUG] plugin: plugin exited

### Expected Behavior

terraform apply success

### Actual Behavior

terraform apply fail

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
