### ISSUE TITLE
Modules aren't depending on interpolated vars

### ISSUE THREAD

**Issue by jjhuff** [hashicorp/terraform#2953]
I have a module that sets up an aws instance and has vars for things like `subnet_id`, which is created by another resource. Unfortunately, TF 0.6.1 doesn't add a dependency edge from the aws_subnet resource to the module.

In the following example, I'd expect that the two `aws_instance`s would each depend on the `aws_subnet`.

```
# module/main.tf
variable "subnet_id" {}

resource "aws_instance" "inst" {
 subnet_id = "${var.subnet_id}"
 instance_type="t1.micro"
 ami="ami-xxxxxx"
}
```

```
# main.tf
provider "aws" {
    region = "us-east-1"
}

resource "aws_subnet" "main" {
  vpc_id = "vpc-xxxx"
  cidr_block = "10.15.100.0/24"
  map_public_ip_on_launch = true
  availability_zone = "us-east-1b"
}

module "riak1" {
  source = "./module"
  subnet_id = "${aws_subnet.main.id}"
}

resource "aws_instance" "riak2" {
 subnet_id = "${aws_subnet.main.id}"
 instance_type="t1.micro"
 ami="ami-xxxxxx"
}
```

Dep graph:
![deps](https://cloud.githubusercontent.com/assets/1055147/9118598/5d70e86e-3c26-11e5-8067-986110c65773.png)

**Comment by mitchellh** [comment]
At some point since then and now, the graph now looks like this:

![graph](https://cloud.githubusercontent.com/assets/1299/17870904/2f562ec4-686e-11e6-8271-ddeec2cd4a2c.png)

**Comment by jjhuff** [comment]
:+1:
