### ISSUE TITLE
TF plan always shows changes on google_monitoring_alert_policy

### ISSUE THREAD

**Issue by tm185187** [hashicorp/terraform#29547]
Hello,

On use of resource "google_monitoring_alert_policy" TF google resource to create a alerting policy with Terraform, it always shows  + cross_series_reducer = "REDUCE_NONE getting added and TF plan shows has been changed.

```

resource "google_monitoring_alert_policy" "logging_alert_policy" {
        id                    = "projects/dbk-ref1-global-sre/alertPolicies/16007304137780151117"
        name                  = "projects/dbk-ref1-global-sre/alertPolicies/16007304137780151117"
        # (7 unchanged attributes hidden)

      ~ conditions {
            name         = "projects/dbk-ref1-global-sre/alertPolicies/16007304137780151117/conditions/16007304137780151806"
            # (1 unchanged attribute hidden)

          ~ condition_threshold {
                # (4 unchanged attributes hidden)

              ~ aggregations {
                  + cross_series_reducer = "REDUCE_NONE"
                    # (3 unchanged attributes hidden)
                }

                # (1 unchanged block hidden)
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
