### ISSUE TITLE
Enable point_in_time_restore_containers for storage account

### ISSUE THREAD

**Issue by kumehta** [hashicorp/terraform#29546]
Hi Team,
 I am using azurerm version 2.75.0

<img width="577" alt="point_in_time" src="https://user-images.githubusercontent.com/13599302/132632308-1781e3e9-47b5-4788-b114-4c4e55b50658.PNG">

blob properties don't have any attribute to enable "point_in_time_restore_for_containers" : 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
