### ISSUE TITLE
azurerm_application_insights asks for workspace_id but requires id of the azurerm_log_analytics_workspace in lower case

### ISSUE THREAD

**Issue by JamesDLD** [hashicorp/terraform#29558]
### Terraform Version

```
Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.75.0
```

### Expected Behavior
```
resource "azurerm_application_insights" "example" {
  name                = "tf-test-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  workspace_id        = azurerm_log_analytics_workspace.example.workspace_id
  application_type    = "web"
}
```

### Actual Behavior
```
resource "azurerm_application_insights" "example" {
  name                = "tf-test-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  workspace_id        = azurerm_log_analytics_workspace.example.id
  application_type    = "web"
}
```

### Additional Context
On the resource "azurerm_log_analytics_workspace" : 
- The **id** is The Log Analytics Workspace ID.
- The **workspace_id** is The Workspace (or Customer) ID for the Log Analytics Workspace.

And it requires it in lower case, when using a data source on azurerm_log_analytics_workspace we are asked to update the resource --> 
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_application_insights.ains["xxx"] will be updated in-place
  ~ resource "azurerm_application_insights" "ains" {
        id                                    = "/subscriptions/xxx/resourceGroups/xxx/providers/microsoft.insights/components/xxx"
        name                                  = "xxx"
      ~ workspace_id                          = "/subscriptions/xxx/resourcegroups/xxx/providers/microsoft.operationalinsights/workspaces/xxx" -> "/subscriptions/xxxxxx/resourceGroups/xxx/providers/Microsoft.OperationalInsights/workspaces/xxx"
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by JamesDLD** [comment]
My fault https://github.com/hashicorp/terraform-provider-azurerm/issues/13348
