### ISSUE TITLE
Error 400: Unknown project id - Due to Dependency Issue

### ISSUE THREAD

**Issue by dmcgowandmc** [hashicorp/terraform#29555]
### Terraform Version

```
Terraform v1.0.5
on linux_amd64
```

### Terraform Configuration Files

```terraform
module "seed_project" {
  source                      = "terraform-google-modules/project-factory/google"
  version                     = "~> 10.1.1"
  name                        = local.seed_project_id
  random_project_id           = var.random_suffix
  disable_services_on_destroy = false
  folder_id                   = var.folder_id
  org_id                      = local.seed_org_depends_on
  billing_account             = var.billing_account
  activate_apis               = local.activate_apis
  labels                      = var.project_labels
}

/******************************************
  Service Account - Terraform for Org
*******************************************/

resource "google_service_account" "org_terraform" {
  project      = module.seed_project.project_id
  account_id   = var.tf_service_account_id
  display_name = var.tf_service_account_name
}

/***********************************************
  GCS Bucket - Terraform State
 ***********************************************/
data "google_storage_project_service_account" "gcs_account" {
  project = module.seed_project.project_id
}
```

### Crash Output
```
module.bootstrap_standard.module.seed_project.module.project-factory.random_id.random_project_id_suffix: Refreshing state... [id=xqU]
╷
│ Error: Error when reading or editing GCS service account not found: googleapi: Error 400: Unknown project id: 'dcs-seed-c6a5', invalid
│ 
│   with module.bootstrap_standard.data.google_storage_project_service_account.gcs_account,
│   on .terraform/modules/bootstrap_standard/main.tf line 83, in data "google_storage_project_service_account" "gcs_account":
│   83: data "google_storage_project_service_account" "gcs_account" {
```

### Expected Behavior
All steps in the project factory module (specifically project creation) should have completed first, then

```bash
data "google_storage_project_service_account" "gcs_account"
```

Should execute successfully

### Actual Behavior
Data resource is executing before all resources in the project factory module has even started, hence the error

### Steps to Reproduce

(use default tfvars file)

```bash
terraform init
terraform apply
```

### Additional Context
I found this issue when using the following google module. I don't have control over the source code, but I did raise a case with them to inform them and offer a workaround fix, but I suspect this is a core terraform issue

https://github.com/terraform-google-modules/terraform-google-bootstrap

Within that module, there is a call to a module called project factory to perform a number of tasks including the creation of the project, then there is a data resource to obtain google_storage_project_service_account

```terraform
/***********************************************
  GCS Bucket - Terraform State
 ***********************************************/
data "google_storage_project_service_account" "gcs_account" {
  project = module.seed_project.project_id
}
```

It takes the project ID from the project factory module as an input, so I would expect that all resources in the project factory module should execute (including the actual creation of the project) before running this data resource.

However, this data resource seems to be triggering as soon as a project ID is calculated (a step within the project factory module), and it isn't waiting for the actual project to get created, hence the error.

I was able add a dependency which forced the data resource to wait until all resources in the project factory completed, and this fixed the issue.

```terraform
/***********************************************
  GCS Bucket - Terraform State
 ***********************************************/
data "google_storage_project_service_account" "gcs_account" {
  project = module.seed_project.project_id

  depends_on = [
    module.seed_project.project_id
  ]
}
```

But I would expect this should happen by default considering all resources in a module should complete before any other resources are triggered that take inputs from this module

### References
https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/122

**Comment by jbardin** [comment]
Hi @dmcgowandmc,

Thanks for filing the issue, and sorry that you are getting bounced back and forth here. The observed behavior you are describing is exactly how Terraform is intended to work. If a data source has a complete configuration, it will be read as early as possible in the planning process. If the data source must depend on a managed resource, but there is no computed attribute which can be used in the data source configuration, then the `depends_on` meta attribute is the correct solution as you have shown here.

If you have more questions, feel free to also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by dmcgowandmc** [comment]
Thanks Jbardin for getting back to me.

That does seem like odd behaviour, but if that's the way it's intended to operate, I will pass that on to the authors of the module and see if they can make adjustments at there side.

Regards,
Doug.
