### ISSUE TITLE
provider/aws crash when authenticating via instance profile on 0.6.2

### ISSUE THREAD

**Issue by bosmanx** [hashicorp/terraform#2955]
Hi,

- I created resources on 0.6.1 (5 tf files + template)
- upgraded to 0.6.2 to use aws_s3_bucket_object
- crashed on "plan/apply" - http://pastebin.com/Wj62NHhr
- removing aws_s3_bucket_object doesn't help - http://pastebin.com/azdyRP41
- removing all resources (only provider settings left) doesn't help neither - http://pastebin.com/DFzP4J05

Looks like problem is with my tfstate - http://pastebin.com/BTaXQMxC

**Comment by phinze** [comment]
Sorry for the trouble! Let's see if we can't get this figured out.

Are you authenticating to AWS via access_key / secret_key or via another method?

**Comment by bosmanx** [comment]
I'm authenticating via instance profile. So I'm screwed anyway, as both https://github.com/hashicorp/terraform/pull/1595 and https://github.com/hashicorp/terraform/pull/2730 break instance profiles as both use iamconn.GetUser(nil):
```
* ValidationError: Must specify userName when calling with non-User credentials
        status code: 400, request id: [dabf17c6-3c8d-11e5-b79c-a50fb504c59a]
```

**Comment by phinze** [comment]
The reason I ask is it looks like a `GetUser` api call to test the provider config is where it failed:

```
2015/08/06 21:00:15 [ERROR] root: eval: *terraform.EvalConfigProvider, err: 1 error(s) occurred:
 
* ValidationError: Must specify userName when calling with non-User credentials
        status code: 400, request id: [22bdfc24-3c7e-11e5-a422-e51fd6279686]
```

**Comment by phinze** [comment]
@bosmanx sorry about this! we'll get it fixed up and cut another release as soon as we can.

**Comment by phinze** [comment]
Related: https://github.com/hashicorp/terraform/issues/2828

**Comment by catsby** [comment]
Hey @bosmanx , terribly sorry for the trouble here. I sent a patch in https://github.com/hashicorp/terraform/pull/2959 to  address this, and right now I'm trying to duplicate the setup you described to confirm things work as expected. If you have the chance and ability to build Terraform from that branch, it would be awesome to help me confirm this is fixed. If not, I should know with some confidence soon.

Again, I sincerely apologize for this. We're working on patching and then cutting a new release today.

**Comment by jszwedko** [comment]
@catsby verified that this works for me, thanks for putting together this PR so quickly. Do you think it would be possible to release a patched version after this is merged? I'd really like to take advantage of some of the changes in `0.6.2`, but this is blocking our ability to upgrade.

**Comment by catsby** [comment]
@jszwedko we're waiting on one more hot fix but yes, a new release should go out ASAP with this

**Comment by jszwedko** [comment]
Awesome, thank you @catsby !

**Comment by jszwedko** [comment]
Also, apologies for not responding to #2828 before 0.6.2 was cut.

**Comment by catsby** [comment]
https://github.com/hashicorp/terraform/pull/2959 and https://github.com/hashicorp/terraform/issues/2963 have been merged and will go out in the next release (targeting this coming Monday, August 10th ), so I'm going to close this now. Thanks for writing in! Sorry for the trouble
