### ISSUE TITLE
AWS S3 domain name replacement?

### ISSUE THREAD

**Issue by chengJun2021** [hashicorp/terraform#29583]
Ask: When configuring TF's aws s3 backend storage state, tf is wrong when init
Error refreshing state: RequestError: send request failed
caused by: Get "https://xxxxx-bucket.s3.ap-southeast-2.amazonaws.com/xxxxxxx/terraform.tfstate": dial tcp 67.230.169.182:443: connect: connection refused
How to modify the default domain name???

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
