### ISSUE TITLE
Plugin did not respond .plugin crashed!

### ISSUE THREAD

**Issue by iulianmarius** [hashicorp/terraform#29584]
### Terraform Version

Terraform v1.0.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.2.0
+ provider registry.terraform.io/hashicorp/azurerm v2.76.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7
+ provider registry.terraform.io/terraform-providers/azuredevops v0.1.7
...
```

### Terraform Configuration Files
<!--
Paste the relevant parts of your Terraform configuration between the ``` marks below.

For Terraform configs larger than a few resources, or that involve multiple files, please make a GitHub repository that we can clone, rather than copy-pasting multiple files in here. For security, you can also encrypt the files using our GPG public key at https://www.hashicorp.com/security.
-->

```terraform
...
```

### Crash Output

azurerm_storage_account.st1: Refreshing state... [id=/subscriptions/abc3cf56-xxxxx/resourceGroups/rg-int-003/providers/Microsoft.Storage/storageAccounts/stint6a94316e9xxxxx]
azurerm_storage_account.st2: Refreshing state... [id=/subscriptions/abc3cf56-xxxxxx/resourceGroups/rg-int-003/providers/Microsoft.Storage/storageAccounts/fnint6a94316xxxxx]
2021-09-15T10:13:53.249+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-09-15T10:13:53.249+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-09-15T10:13:53.249+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-09-15T10:13:53.249+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-09-15T10:13:53.249+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-09-15T10:13:53.249+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-09-15T10:13:53.249+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
2021-09-15T10:13:53.249+0200 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = transport is closing"
╷
│ Error: Plugin did not respond
│
│   with azurerm_key_vault_secret.kvsPortalBaseUrl,
│   on app_service.tf line 81, in resource "azurerm_key_vault_secret" "kvsPortalBaseUrl":
│   81: resource "azurerm_key_vault_secret" "kvsPortalBaseUrl" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_app_service_managed_certificate.chost_webApp1_cert,
│   on dns-records.tf line 31, in resource "azurerm_app_service_managed_certificate" "chost_webApp1_cert":
│   31:  resource "azurerm_app_service_managed_certificate" "chost_webApp1_cert" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_servicebus_subscription_rule.topic2_sub1_rule1,
│   on service_bus.tf line 59, in resource "azurerm_servicebus_subscription_rule" "topic2_sub1_rule1":
│   59: resource "azurerm_servicebus_subscription_rule" "topic2_sub1_rule1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_servicebus_subscription_rule.topic2_sub3_rule1,
│   on service_bus.tf line 106, in resource "azurerm_servicebus_subscription_rule" "topic2_sub3_rule1":
│  106: resource "azurerm_servicebus_subscription_rule" "topic2_sub3_rule1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_key_vault_secret.kvsServiceBusConnectionString,
│   on service_bus.tf line 224, in resource "azurerm_key_vault_secret" "kvsServiceBusConnectionString":
│  224: resource "azurerm_key_vault_secret" "kvsServiceBusConnectionString" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_signalr_service.sr1,
│   on signalr.tf line 1, in resource "azurerm_signalr_service" "sr1":
│    1: resource "azurerm_signalr_service" "sr1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_storage_account.st1,
│   on storage.tf line 1, in resource "azurerm_storage_account" "st1":
│    1: resource "azurerm_storage_account" "st1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_storage_account.st2,
│   on storage.tf line 54, in resource "azurerm_storage_account" "st2":
│   54: resource "azurerm_storage_account" "st2" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.76.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5ec4d4a]

goroutine 1572 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceAppServiceManagedCertificateRead(0xc001e86000, 0x62e32c0, 0xc0005c6700, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/web/app_service_managed_certificate_resource.go:221 +0x70a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0013435e0, 0x72ef5a8, 0xc001dd8540, 0xc001e86000, 0x62e32c0, 0xc0005c6700, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0013435e0, 0x72ef5a8, 0xc001dd8540, 0xc0003ac850, 0x62e32c0, 0xc0005c6700, 0xc00074fa78, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000284570, 0x72ef5a8, 0xc001dd8540, 0xc001dd8580, 0xc001dd8540, 0xbcbeca, 0x661b360)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x45b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001de36a0, 0x72ef650, 0xc001dd8540, 0xc00152c480, 0xc001de36a0, 0xc001d55740, 0xc002485ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x108
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x67e45c0, 0xc001de36a0, 0x72ef650, 0xc001d55740, 0xc00152c3c0, 0x0, 0x72ef650, 0xc001d55740, 0xc0023b8380, 0x363) 
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000238a80, 0x733f298, 0xc000299800, 0xc0023bdb00, 0xc0005f2ae0, 0xaa0c4b0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000238a80, 0x733f298, 0xc000299800, 0xc0023bdb00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0008f48c0, 0xc000238a80, 0x733f298, 0xc000299800, 0xc0023bdb00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.76.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
