### ISSUE TITLE
AWS Lightsail + Userdata Issue

### ISSUE THREAD

**Issue by njdevils9** [hashicorp/terraform#29582]
### Terraform Version
```bash
[njdevils9@laptop]$ terraform version
Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.58.0

Your version of Terraform is out of date! The latest version
is 1.0.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files
```terraform
resource "aws_lightsail_instance" "this" {
  depends_on = [
    aws_lightsail_key_pair.this
  ]

  name = var.name
  key_pair_name = aws_lightsail_key_pair.this.id
  user_data = var.user_data

  availability_zone = "us-east-1a"
  blueprint_id      = var.blueprint_id
  bundle_id         = var.bundle_id
}
```
### Expected Behavior
My custom user_data script will run. 

### Actual Behavior
I run `terraform plan --var-file tfvars/dev.tfvars` && `terraform apply --var-file tfvars/dev.tfvars --auto-approve` , the AWS Lightsail instance launches successfully. I login and notice that my custom user_data script did **not** run. 

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan --var-file tfvars/dev.tfvars`
2. `terraform apply --var-file tfvars/dev.tfvars`

### Additional Context
My custom user_data script does **not** run. 

I have tried:
`user_data = file("${path.module}/etc/userdata.sh")`
`user_data = templatefile("${path.module}/userdata.sh")`
`user_data = file("./etc/userdata.sh")`

I can see the `terraform plan` output show that it's reading my `userdata.sh` script but when I actually SSH into my AWS Lightsail WordPress instance, I see nothing in the logs. 

`/var/log/cloud-init.log`
`/var/log/cloud-init-output.log`
`/var/log/messages`
`/var/log/syslog`

I can `grep` for a string/pattern from my userdata and it will output 3 log files but I don't see anything actually in the files... 
```[root@aws_lightsail_instance]$ grep -ril 'TEST' /var/log/*
/var/log/cloud-init.log
/var/log/daemon.log
/var/log/syslog
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
