### ISSUE TITLE
Datasync Task: ARN account () must match authenticated user

### ISSUE THREAD

**Issue by AlexanderLahutsin** [hashicorp/terraform#29593]
Hello guys,

```
resource "aws_datasync_task" "example" {
  destination_location_arn = data.aws_s3_bucket.example.arn
  name   = "example"
  source_location_arn  = data.aws_efs_file_system.example.arn
}
```

```
│ Error: error creating DataSync Task: InvalidRequestException: Invalid parameter: ARN account () must match authenticated user.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "e***a"
│   },
│   ErrorCode: "InvalidParameter",
│   Message_: "Invalid parameter: ARN account () must match authenticated user."
│ }
```

Maybe this is not a bug, but Google does not say anything about it at all? Any ideas?
How can I understand the error and fix it? Thanks!

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
