### ISSUE TITLE
Module for_each with inclusive outputs causes cycle error

### ISSUE THREAD

**Issue by nomeelnoj** [hashicorp/terraform#29607]
I am seeing a bug with using `for_each` inside of modules when using the module's own outputs within the module.  Attached is a simple example, but internally we have many modules that do this--an ALB with a target group, for example, with any number of listeners, and we instruct users to pass the output `module.alb.target_group.arn` to the listener config, as the target group and listeners are created within the module.

Without `for_each`, this works without issue.  However, as soon as you add `for_each`, you get a cycle error.

### Terraform Version

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.59.0
```

### Terraform Configuration Files

```terraform
# Example S3 Module with policy
resource "aws_s3_bucket" "default" {
  bucket = var.bucket
}

data "aws_iam_policy_document" "default" {
  dynamic "statement" {
    for_each = var.policy_statements
    # for_each = length(keys(var.policy_statements)) == 0 ? {} : var.policy_statements
    content {
      sid    = format("%s%s", title(var.bucket), statement.value.sid)
      effect = statement.value.effect

      dynamic "principals" {
        for_each = lookup(statement.value, "identifiers", null) != null ? [lookup(statement.value, "identifiers")] : []
        content {
          type        = statement.value.type
          identifiers = lookup(statement.value, "identifiers", null)
        }
      }
      actions = statement.value.actions
      resources = length(lookup(statement.value, "resources", [])) > 0 ? lookup(statement.value, "resources", []) : []
    }
  }
}

resource "aws_s3_bucket_policy" "default" {
  bucket = aws_s3_bucket.default.bucket
  policy = data.aws_iam_policy_document.default.json
}

data "aws_caller_identity" "current" {}

variable "bucket" {
  type = string
}

variable "policy_statements" {
  description = "Config block of policy statements to create"
  type        = any
}

output "aws_caller_identity" {
  value = data.aws_caller_identity.current
}
```

```hcl
# Example module call
module "s3" {
  for_each = toset(["foo", "bar"])
  source   = "../s3"
  bucket   = "foobar-${each.value}"
  # bucket   = "foobar"
  policy_statements = {
    default = {
      sid    = "Test"
      effect = "Allow"
      type   = "AWS"
      identifiers = [
        "arn:aws:iam::${module.s3[each.key].aws_caller_identity.account_id}:role/foobar"
        # "arn:aws:iam::${module.s3.aws_caller_identity.account_id}:role/foobar"
      ]
      actions = [
        "s3:GetObject",
        "s3:PutObject"
      ]
    }
  }
}
```
The above config will throw the cycle error.  To see it pass without the cycle error, comment out the `for_each`, comment/uncomment the `bucket` arg, as well as the `identifiers` (this is what causes the issue)

### Debug Output

https://gist.github.com/nomeelnoj/a01f1e0bce3546762745058b5e196481

### Expected Behavior

The module should properly interpolate the outputs used within the module as it does without `for_each`
### Actual Behavior

Cycle error

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. See error
4. Uncomment the `for_each` and update the values to not use `each.value` or `each.key`
5. `terraform plan`
6. Observe normal output

**Comment by jbardin** [comment]
Hi @nomeelnoj,

Thanks for filing the issue. What you are seeing here is expected, the module cannot reference itself without creating a cycle. In this example the `policy_statements` cannot be evaluated until after the `aws_caller_identity.account_id` module output, but we cannot expand the module without passing in `policy_statements`.

I suspect this could be refactored to use multiple modules to accomplish your goal, but while we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
