### ISSUE TITLE
Error: Error modifying Lambda Function Code XXXXXXX: ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:XXXXXXXX:function:XXXXXXX

### ISSUE THREAD

**Issue by gurpartap1986** [hashicorp/terraform#29604]
Hi
 I facing issue 
Error: Error modifying Lambda Function Code XXXXXXXX: ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:XXXXX:function:XXXXXXXX

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
