### ISSUE TITLE
Plan with read only remote state

### ISSUE THREAD

**Issue by jedineeper** [hashicorp/terraform#2960]
I would like to be able to locally do a plan with a remote config (Atlas) setup when I only have read only access to the remote config. When working collaboratively, it is useful to be able to see what changes my code will make to the infrastructure the remote state has on record without having to make a change to the remote state. Once I'm happy with the changes I can then push to git (usually) so they can be merged into master by the CI process.

I can't do this currently as it appears "terraform plan" does a refresh and tries to push that refresh to Atlas which results in this error message :(

Error writing state file: HTTP error: 404
Body: {"errors":["Resource not found!"]}

**Comment by radeksimko** [comment]
:+1: Isn't this a duplicate of https://github.com/hashicorp/terraform/issues/2548 though?

**Comment by jedineeper** [comment]
Yes it is! Not sure why I didn't find this in my search, closing as dupe and subscribing to 2548.
