### ISSUE TITLE
Sensitive inputs are visible in terminal

### ISSUE THREAD

**Issue by kamil-wojcik** [hashicorp/terraform#29609]
### Terraform Version

```
terraform version
Terraform v1.0.7
on linux_amd64
```

### Terraform Configuration Files

```terraform
variable "secret" {
    sensitive = true
}

variable "plain" {
    sensitive = false
}
```

### Debug Output

```
terraform plan
var.plain
  Enter a value: plain-value

var.secret
  Enter a value: secret-value


No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are
needed.

```

### Expected Behavior

Input for sensitive variables should be masked

### Actual Behavior

When value for sensitive variable is given it is visible on console.

### References

I would be happy to prepare fix for it.

**Comment by patchon** [comment]
Took me a couple of hours to get here.
From a personal perspective I think this makes perfect sense. 
If I mark a variable **sensitive = true**, I would expect terraform to mask the input when asking.

**Comment by matthewjdegarmo** [comment]
+10000 for this feature.
Would love to see sensitive variables masked when typed in at the console.

**Comment by jhvhs** [comment]
Seems like a duplicate of #28122

**Comment by crw** [comment]
Agreed, although I am going to retain this issue as I think the description is a bit easier to understand.

**Comment by mbenson** [comment]
How is this still open?

**Comment by crw** [comment]
Closed by https://github.com/hashicorp/terraform/pull/29520
