### ISSUE TITLE
[FEATURE REQUEST] Import service principal completely when importing an AKS cluster

### ISSUE THREAD

**Issue by Shaybs** [hashicorp/terraform#29613]
The command terraform import module.x.x /subscription/x/x/aks-cluster will import the cluster but not the secret value of the service principal. If a user proceeds to then update their cluster essentially the entire cluster restarts with a way to stop it. Could a system be put in place that avoids that.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
