### ISSUE TITLE
Failed to get existing workspaces: containers.Client#ListBlobs error with Azure container level sas token

### ISSUE THREAD

**Issue by endejoli** [hashicorp/terraform#29612]
### Terraform Version
```
version: 1.0.2
```

### Terraform Configuration Files
```
terraform {  
  backend "azurerm" {
   resource_group_name   = "abc"
   storage_account_name  = "abcstate"
   container_name        = "abccontainer"
   key                   = "abcstatekey"
   sas_token             = "sv=2018-04-05&sr=c&spr=https&se=2032-09-18T10%3A36%3A20.0000000Z&sp=racwdl&sig=UDbEasdfsdafsadfsdafsadfsd"
 }
}

```

### Expected Behavior
 Terraform was supplied with a SAS token which has enough privilege to store the state inside the specified container. 

### Actual Behavior
Failed to get existing workspaces: containers.Client#ListBlobs: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.
### Steps to Reproduce
1. `terraform init`

### Additional Context
 Terraform is querying for all blobs in the container to see how many "workspaces" it can find. Which is think is not expected here.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
