### ISSUE TITLE
Issue with helm provider

### ISSUE THREAD

**Issue by isaacdan** [hashicorp/terraform#29611]
Team,

I'm getting error after upgrading my helm module to the latest version.
When I rerun the terraform after making any changes to the modules it throws an error like "cluster not reachable and specify the kube config path" looks like it is not reading kube config path while refresh
.
It was working fine till "1.3.2"

provider "helm" {
 alias = "akshelmconfig"
 kubernetes {
   host                   = azurerm_kubernetes_cluster.aks_cluster.kube_config.0.host
   client_certificate     = base64decode(azurerm_kubernetes_cluster.aks_cluster.kube_config.0.client_certificate)
   client_key             = base64decode(azurerm_kubernetes_cluster.aks_cluster.kube_config.0.client_key)
   cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.aks_cluster.kube_config.0.cluster_ca_certificate)
}
}

Kindly advice.

Thanks,
Isaac

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
