### ISSUE TITLE
Dependency issue when creating RDS read replicas

### ISSUE THREAD

**Issue by gposton** [hashicorp/terraform#2961]
This is not a blocker as we've worked around this by adding the following param to the 'replica_rds_instance' resource, but wanted to submit this for tracking purposes.

    depends_on             = ["aws_db_instance.main_rds_instance"]

We have a template that is used to create an RDS instance with read replicas.  Here are the relevant resources from that template.

    resource "aws_db_instance" "main_rds_instance" {
        identifier             = "${var.instance_name}"
        allocated_storage      = "${var.allocated_storage}"
        engine                 = "${var.engine_type}"
        engine_version         = "${var.engine_version}"
        instance_class         = "${var.instance_class}"
        name                   = "${var.database_name}"
        username               = "${var.database_user}"
        password               = "${var.database_password}"
        vpc_security_group_ids = ["${aws_security_group.db_allow_all.id}"]
        db_subnet_group_name   = "${aws_db_subnet_group.main_db_subnet_group.name}"
        parameter_group_name   = "${aws_db_parameter_group.default-psql-94.name}"
        multi_az               = "${var.multi_az}"
        storage_type           = "${var.storage_type}"
        backup_retention_period = "${var.backup_retention_period}"
    }

    resource "aws_db_instance" "replica_rds_instance" {
        count                  = "${var.replica_count}"
        identifier             = "${var.instance_name}-replica-${count.index}"
        replicate_source_db    = "${var.instance_name}"
        allocated_storage      = "${var.allocated_storage}"
        engine                 = "${var.engine_type}"
        engine_version         = "${var.engine_version}"
        instance_class         = "${var.instance_class}"
        name                   = "${var.database_name}"
        username               = "${var.database_user}"
        password               = "${var.database_password}"
        vpc_security_group_ids = ["${aws_security_group.db_allow_all.id}"]
        db_subnet_group_name   = "${aws_db_subnet_group.main_db_subnet_group.name}"
        parameter_group_name   = "${aws_db_parameter_group.default-psql-94.name}"
        multi_az               = "${var.multi_az}"
        storage_type           = "${var.storage_type}"
    }

The terraform apply fails with the following error:

    * Error creating DB Instance: DBInstanceNotFound: The source instance could not be found: main_rds_instance
            status code: 404, request id: [ccd608c4-3bb0-11e5-bf3e-b12f367975b4]

I would expect terraform to wait for the existence of the RDS master instance before creating the read replicas.

This occurred w/ Terraform v0.6.1

Let me know if it would be helpful if I provided our full template.

**Comment by catsby** [comment]
Hey @gposton – thanks for the detailed config! In your example there, `replica_rds_instance` doesn't reference `main_rds_instance` at all, so Terraform does not know they're related. They'll generate as two independent nodes on the graph. 

Adding the `depends_on` you mentioned forces the two to be related, as you've seen. I've typically seen (and tested with) replicas by referencing the source in the replica's `replicate_source_db` attribute, like so:

```javascript
resource "aws_db_instance" "main_rds_instance" {
    identifier             = "${var.instance_name}"
    [...]
}

resource "aws_db_instance" "replica_rds_instance" {
    count                  = "${var.replica_count}"
    identifier             = "${var.instance_name}-replica-${count.index}"
    replicate_source_db    = "${aws_db_instance.main_rds_instance.identifier}"   # link the two here
    [...]
}
```

The replica has to know that the primary is a resource that it depends on, so it needs to be created first. Adding the reference as shown above does that (though the `depends_on` works as well) 

Does that clarify things? Let me know if you have further questions. I'm going to go ahead and close the issue though, as Terraform is working as expected from what I can see.

Thanks!

**Comment by kceb** [comment]
What if we want to create the resources in separate files? The `depends_on` doesn't seem to work in that case

**Comment by kceb** [comment]
Basically I want to create a replica in a different region, is there an easy way to do that? Maybe I'm missing something in the docs, but once you declare the region in the provider block, are you able to change it in the same module?
