### ISSUE TITLE
provider github_repository suddenly fails

### ISSUE THREAD

**Issue by sudocraft** [hashicorp/terraform#29629]
### Terraform Version

```
Terraform Github Actions Latest
```

### Terraform Configuration Files

```terraform
provider "github" {
  token        = "HIDDEN" #Github Personal Token
}

resource "github_repository" "master" {
  name        = "MY_REPO"
  description = "Nothing goes here..."
  visibility  = "private"
}

# Local Executable
resource "github_repository_file" "master" {    
  repository          = github_repository.master.name
  branch              = "main"
  file                = ".github/actions/deploy/hosts"
  content  = <<EOT
}
...
```

### Crash Output

```
/home/runner/work/_temp/56f8bb14-3c8e-4aba-a476-535e6021dd5c/terraform-bin validate -no-color

Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource github_repository: etag: DiffSuppressFunc is for suppressing differences between config and state representation. There is no config for computed-only field, nothing to compare.



  with provider["registry.terraform.io/hashicorp/github"],
  on hosts.tf line 1, in provider "github":
   1: provider "github" {

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```
### Expected Behavior

All my repo suddenly fail with parsing hosts file to other ansible repo today.

This is suppose to parse all IP address to hosts file to another Ansible Repo github action to automate tasks

### Actual Behavior

Failed at Terraform validate

### Steps to Reproduce

Please pm for my private repo inv
### Additional Context

Github Actions -> Terraform Cloud -> Create Repo -> Put Hosts file -> Ansible... ...

**Comment by alisdair** [comment]
Thanks for reporting this. The error message indicates that this is a bug in the GitHub provider, which unfortunately we can't help with here. Please [report this issue on the provider repository](https://github.com/integrations/terraform-provider-github).
