### ISSUE TITLE
Publishing a new provider on https://registry.terraform.io just hangs

### ISSUE THREAD

**Issue by kalyan-nidumolu** [hashicorp/terraform#29628]
Hi,

We are trying to publish our new terraform provider - terraform-provider-zedcloud:
https://github.com/zededa/terraform-provider-zedcloud

We followed the process described here:
https://www.terraform.io/docs/registry/providers/publishing.html

The following page on the registry says it is already published, but terraform is not able to find the provider:
https://registry.terraform.io/publish/provider/github/zededa

The registry link for the provider just hangs:
https://registry.terraform.io/providers/zededa/zedcloud?pollNotifications=true

Any idea how to fix this? 

Appreciate your help on this. If this is not the right forum, can you please let me know where to report this?

Thanks,
Kalyan

**Comment by alisdair** [comment]
Thanks for reporting this! For issues with the Terraform Registry, please send an email to terraform-registry@hashicorp.com, which is monitored by the team at HashiCorp responsible for the registry. I'm closing this issue out because it's not a Terraform core bug.

**Comment by kalyan-nidumolu** [comment]
> Thanks for reporting this! For issues with the Terraform Registry, please send an email to [terraform-registry@hashicorp.com](mailto:terraform-registry@hashicorp.com), which is monitored by the team at HashiCorp responsible for the registry. I'm closing this issue out because it's not a Terraform core bug.

@alisdair - I reported this issue at terraform-registry@hashicorp.com , but saw no response. We are stuck at this point, would appreciate any help.
