### ISSUE TITLE
Version is out of date message is wrong

### ISSUE THREAD

**Issue by jjshoe** [hashicorp/terraform#2962]
Website shows 0.6.2 as latest, terraform on the cli shows 0.6.1 as latest

Terraform v0.6.0

Your version of Terraform is out of date! The latest version
is 0.6.1. You can update by downloading from www.terraform.io

**Comment by phinze** [comment]
That's odd - this was updated yesterday with the release. We just tested from a few different nodes over here and saw 0.6.2 responses everywhere. Must be some sort of cache between you and the Checkpoint API server.

Either way - everything's looking good on our side. Feel free to follow up if there's anything else we can do to help here. :+1:
