### ISSUE TITLE
init with backend=false still attempts to authorize when using S3 backend

### ISSUE THREAD

**Issue by jcollum** [hashicorp/terraform#29625]
I'm trying to set up a pre-push validate script. Using these instructions: https://www.terraform.io/docs/cli/commands/validate.html. I don't want the user to be required to be logged in to AWS via CLI, since the purpose of this is only to validate TF files. 

### Terraform Version

```
✗ tf version
Terraform v1.0.7
on darwin_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.0.6"
  backend "s3" {
    // bucket name is in backends/[env].tf
    key = "insights-ui-backend.tfstate"
    region = "us-west-2"
  }
```

### Debug Output

https://gist.github.com/jcollum/85fd1d7dffbc455cdb5c866b842afc13

### Expected Behavior

TF should ignore the backend since I set backend to false. 

### Actual Behavior

TF barfed because I wasn't logged in to AWS. 

### Steps to Reproduce

1. don't be logged in to AWS
2. Have an S3 backend in config 
3. `terraform -chdir=infrastructure init -backend=false`

Result: TF barfs because user is not logged in to AWS.

**Comment by jbardin** [comment]
Hi @jcollum,

Thanks for filing the issue, I can see how this might be confusing. The `-backend` flag for `init` determines if the backend is going to be configured or not during the operation, but does not prevent an already configured backend from being accessed.

The `init` operation not only reads the configuration, but also need to query the state in order to determine if there are provider required by the state which are not present in the configuration. This means that if there is a state stored in `s3`, terraform will still attempt to read it. This was intended to be used in an uninitialized directory to fetch providers while not attempting to setup the backend.

Ignoring a currently configuration backend however does feel to me to be within the same scope, and may be something we can look into incorporating into that flag.

Thanks!

**Comment by wilmardo** [comment]
Hitting this too, also trying to setup a `terraform validate`CI job to run without access to the provider credentials as a before merge check. We use the google provider with a gcs bucket but the same issue, validate tries to get the state from the bucket.

Would be a nice feature!

**Comment by nunolima** [comment]
I have bypass it by changing the backend config just for the validation CI job (without credentials):
- sed -i 's/"s3"/"local"/g' backend.tf
- terraform init -backend=false
- terraform validate

**Comment by ruckc** [comment]
I see this issue as a blocker for me.  If I'm making a pull request, that needs an update to the dependencies, but i can't use `terraform init` to update the `.terraform.lock.hcl` without read access to the terraform state.

**Comment by andigwandi** [comment]
> ```terraform
> terraform init -reconfigure -backend=false -upgrade
> ```

This didn't work for me. But when I deleted `.terraform.lock.hcl` and `.terraform` folder and re-run the init command with backend false, it worked.

**Comment by mike-marcacci** [comment]
Working around this limitation is a nuisance for engineers who need to run `terraform validate` without access to the state, and is a major hurdle for those unfamiliar with terraform trying to write their first few PRs.

It's possible to simply remove the backend block before running `terraform init -backend=false`, but if `init` is attempted with the block still present, it is persisted in `.terraform`, which must be removed.

**Comment by nwalters512** [comment]
I ran into this as well. My use case is that I have a single repo with Terraform code for multiple AWS accounts. I want to be able to run `terraform init` and `terraform validate` for config across multiple accounts without needing to auth with all of them. This works fine in CI environments like GitHub Actions where there aren't any preexisting `.terraform/terraform.tfstate` files, but it fails locally when I already have those files.

**Comment by MDRCS** [comment]
### - FIX:
- Make sure That you don't commit HCL Files generated by `terraform init` command in your repo, if it's the case the command will work.

**Comment by gdavison** [comment]
@jbardin @crw Is this specific to the S3 backend, or is this something that should be handled by the `terraform init` command?

**Comment by jbardin** [comment]
@gdavison, yes this is a core issue, not related to an individual backend. It is however working as designed, so it's probably better to just replace this with the latest version of the enhancement request here: #33726
