### ISSUE TITLE
dependency resolution between resouces needs to take care of operation type

### ISSUE THREAD

**Issue by wstill** [hashicorp/terraform#29632]
For setup of our internal environment we develop new providers
* Storage Systems

Within this Storage System Provider we have 2 resources:
* LUN
* HostGroup

These resources have a dependency: the created/deleted LUNs need to be assigned to an HostGroup.

The HostGroup resource can change the luns attribute assignment in an update operation.
To add LUNs this leads to an operation flow:
* add LUN
* update HostGroup

This flow is right as there is an implicit dependency in the configuration between the lun attribute (computed) of the LUN to the luns attribute in HostGroup.

For a delete of an LUN the operation flow should be:
* update HostGroup (remove the reference to the LUN)
* delete LUN

The actual flow is:
* delete LUN
* update HostGroup

This leads to issues within the storage system as it tracks the usage of LUNs and prevents the deletion of the LUN as long as there is a reference within the HostGroup.

The flow of the operations should take care of the type of operation even with an update. For a full create / delete of the configuration this ordering will already be taken care of.

### Terraform Version
v1.0.2

### Terraform Configuration Files
```
resource "zenithdisk_lun" "source" {
       name = "LUNNameTest_${count.index}"
       count = 1
       # lun: computed
}

resource "zenithdisk_hostgroup" "source" {
       hg_name = "HostGroupNameTest"
       luns = zenithdisk_lun.source[*].lun
}
```

### Crash Output

no Crash

### Expected Behavior

Operation flow:
* create LDEV (optional if there is a create of a LDEV)
* update HostGroup
* delete LDEV (optional if there is a delete of a LDEV)

### Actual Behavior

Operation flow:
* create / delete LDEV
* update HostGroup

**Comment by alisdair** [comment]
Hi @wstill. The resource update/delete inter-dependency that you describe is not something that Terraform can auto-detect reliably, as both update-then-delete and delete-then-update are valid options. However, this situation is what the `create_before_destroy` option for the resource `lifecycle` is for.

Setting `create_before_destroy = true` on your LUN resources inverts the dependency resolution order, ensuring that any resources depending on the LUNs are updated before the LUN is destroyed. [There's an internal doc describing some of the details behind that here](https://github.com/hashicorp/terraform/blob/main/docs/destroying.md).

As an example using a publicly available provider, consider this AWS config:

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

variable "sgs" {
  default = 3
}

resource "aws_security_group" "example" {
  name_prefix = "example-"
  count       = var.sgs

  # Ensure we update the instance before destroying the SG
  lifecycle {
    create_before_destroy = true
  }
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "example" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t3.micro"
  vpc_security_group_ids = aws_security_group.example.*.id
}
```

Running `terraform apply` then `terraform apply -var sgs=2` will work only if the `lifecycle` block is present. Removing the `lifecycle` block attempts to delete the SG before updating the instance, which AWS cannot do.
