### ISSUE TITLE
How to disable code lens (reference)

### ISSUE THREAD

**Issue by erihanse** [hashicorp/terraform#29634]
How can we disable the references code lense?
It seems that this doesn't work anymore (suggested in https://github.com/hashicorp/vscode-terraform/issues/128#issuecomment-443195805_):
`"terraform.codelens.enabled": false`
vscode reports "Unknown Configuration Setting"

**Comment by alisdair** [comment]
Hi, thanks for reporting. Please file this issue on the vscode-terraform repository, as it is not a Terraform core problem.
