### ISSUE TITLE
Launch template tags configuration not persisted in state

### ISSUE THREAD

**Issue by aardbol** [hashicorp/terraform#29631]
### Terraform Version

```
Terraform v1.0.7
on linux_amd64
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior
TF persists all the tags in the state so they do not appear as modified in the code

### Actual Behavior
TF is showing falsely that a tag ("Environment") has been newly added to the code and wants to apply it to the state. This causes TF to show that this change needs to be made in the state EVERY TIME.

The launch template version isn't changed after applying the configuration. Either this is because TF doesn't actually apply anything or it's just the way launch template tags work.

### Steps to Reproduce

tf plan
tf apply -out tfplan

```
# module.app-jobs.aws_launch_template.job["gpu-spot"] will be updated in-place
~ resource "aws_launch_template" "job" {
~ default_version         = 22 -> (known after apply)
id                      = "lt-xxx"
~ latest_version          = 22 -> (known after apply)
name                    = "test-eu1-eks-app-gpu-spot"
~ tags                    = {
+ "Environment" = "test"
# (2 unchanged elements hidden)
}
# (11 unchanged attributes hidden)



# (5 unchanged blocks hidden)
}
```

### Additional Context

I'm also using default_tags and this issue is part of my module

**Comment by alisdair** [comment]
Thanks for reporting this. It looks like this is an issue with the AWS provider, rather than Terraform itself. [Please report the problem on the provider repository](https://github.com/hashicorp/terraform-provider-aws/).
