### ISSUE TITLE
nested if statement with brackets fails fmt with no error output

### ISSUE THREAD

**Issue by chris-pateman** [hashicorp/terraform#29635]
### Terraform Version
```
Terraform v1.0.4
```

### Terraform Configuration Files
```terraform
locals {
  env_long_name = var.environment == "sbox" ? "sandbox" : (var.environment == "stg" ? "staging" : var.environment)
}
```

### Expected Behavior
I think this is ok/correct formatting so it should allow it to pass. However, if this is incorrect formatting then an error output declaring what is incorrect should be displayed 

### Actual Behavior
The file name is outputted with no error

### Steps to Reproduce
1. Add the code above
2. run the below command
```
$filePath="/myfile.tf"
terraform fmt -check=true $filePath
```

### Additional Context
removing the brackets allows it to pass

**Comment by alisdair** [comment]
Hi @chris-pateman, thanks for reporting this. I can't see any problem with this code, nor any errors from `terraform fmt`. Here's what I have:

```hcl
variable "environment" {
  default = "stg"
}

locals {
  env_long_name = var.environment == "sbox" ? "sandbox" : (var.environment == "stg" ? "staging" : var.environment)
}

output "name" {
  value = local.env_long_name
}
```

Running `terraform fmt -check=true ./myfile.tf` exits with 0 status and no message. Planning works as expected too:

```shellsession
$ terraform plan

Changes to Outputs:
  + name = "staging"

You can apply this plan to save these new output values to the Terraform state,
without changing any real infrastructure.

───────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
$ terraform plan -var environment=sbox

Changes to Outputs:
  + name = "sandbox"

You can apply this plan to save these new output values to the Terraform state,
without changing any real infrastructure.

───────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

What is the issue that you're seeing?

**Comment by chris-pateman** [comment]
Hello @alisdair 
I think this might be a case of turning it on and off.
Removing the brackets got it working, but putting them back on to reproduce now doesn't work.

I am guessing it just got stuck for some reason.

Happy for this to be closed
