### ISSUE TITLE
Need ability to provide Private DNS Zone ID when specifying azurerm_private_dns_zone_virtual_network_link

### ISSUE THREAD

**Issue by eehret** [hashicorp/terraform#29646]
### Current Terraform Version
```
terraform -v
Terraform v1.0.7
on linux_amd64

```

### Use-cases
The main use case for this applies when you want to create a VNET link between a VNET in one subscription and a Private DNS Zone in a different subscription using the azurerm provider.
Simultaneously it is also required to allow the configuration to be dynamic such that this code could be put into a module and simply provided the necessary context information to create the needed linkages.

Currently, this appears not to be possible as far as I can tell;  Right now the `private_dns_zone_name` argument is how one indicates which Private DNS Zone to create the link with, but there is no way to provide the subscription context dynamically.
I thought about specifying a different provider with an alias in order to provide the context of the private DNS zone but this appears to be problematic because I can't figure out how to set an azurerm provider dynamically (as I would need to in a configurable module scenario).

### Attempted Solutions
As mentioned above I tried to use an alternate provider definition with an alias for the `azurerm_private_dns_zone_virtual_network_link` , but I can't figure out how to do this dynamically without hard coding the subscription context.  I want a completely configurable solution that can be easily configured by variables.

### Proposal
I would like to propose that , similar to the way that the VNET context is provided using a full resource ID in the `virtual_network_id` , the same should be possible for the Private DNS Zone.  
In order to provide some backward compatibility in the short term, perhaps two attributes can be supported:
1) The `private_dns_zone_name`.  If used, behaviour would be as it is today - no change;
2) A new attribute in which one may provide the full resource ID of the Private DNS Zone.   I would propose the name `private_dns_zone_id`.  If used, the Private DNS Zone would be looked up using the full resource ID from whichever subscription it happens to be in

If both arguments above are used simultaneously, I think an error should be raised informing the user they should only use one of them.  Perhaps at some point in the future, the original argument would become deprecated.

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_dns_zone_virtual_network_link

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
