### ISSUE TITLE
aws_route_table and aws_default_route_table don't work / crash

### ISSUE THREAD

**Issue by DagrutCr** [hashicorp/terraform#29643]
### Terraform Version

```
Terraform v0.12.31

Your version of Terraform is out of date! The latest version
is 1.0.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files
```terraform
variable "AWS_ACCESS_KEY" {
}
variable "AWS_SECRET_KEY" {
}
variable "AWS_REGION" {
}

provider "aws" {
  access_key = var.AWS_ACCESS_KEY
  secret_key = var.AWS_SECRET_KEY
  region     = var.AWS_REGION
}

resource "aws_vpc" "vpc" {
  cidr_block       = "192.168.0.0/16"
  instance_tenancy = "default"

  tags = {
    Name = "Test VPC"
  }
}

resource "aws_subnet" "subnet" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "192.168.0.0/16"
  availability_zone = "${var.AWS_REGION}a"

  tags = {
    Name = "Test Subnet"
  }
}

resource "aws_internet_gateway" "gw" {
  vpc_id = aws_vpc.vpc.id

  tags = {
    Name = "Test GW"
  }
}

resource "aws_default_route_table" "route_table" {
  default_route_table_id = aws_vpc.vpc.default_route_table_id

  route = [
    {
      cidr_block = "0.0.0.0/0"
      gateway_id = aws_internet_gateway.gw.id

      # Somehow these are required...
      ipv6_cidr_block            = null
      destination_prefix_list_id = null
      egress_only_gateway_id     = null
      gateway_id                 = null
      instance_id                = null
      nat_gateway_id             = null
      network_interface_id       = null
      transit_gateway_id         = null
      vpc_endpoint_id            = null
      vpc_peering_connection_id  = null
    }
  ]
}
```

### Debug Output & Crash Output
See : https://gist.github.com/DagrutCr/8f4f654104e64fb5c3a97d9c8ae6500f

### Expected Behavior
Create or update route tables properly...

### Actual Behavior
Crash when attempting to create or edit a route table, default or not

### Steps to Reproduce
1. `terraform init`
2. `terraform apply -var AWS_REGION=eu-west-3 -var "AWS_ACCESS_KEY=$key" -var "AWS_SECRET_KEY=$secret" -auto-approve`

### Additional Context
I did not include an example for normal route tables because that is the exact same issue (requiring all variables to be set for each route, and then crashing because nothing is set, even if it is).

### References
This issue seems to have been reported in 2016 but was never investigated : 

https://github.com/hashicorp/terraform/issues/10426

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
