### ISSUE TITLE
Pass auth token when downloading provider binary as download backed might be protected.

### ISSUE THREAD

**Issue by k0da** [hashicorp/terraform#29651]
### Current Terraform Version
```
Terraform v1.1.0-dev
```

### Use-cases
We've [built](https://github.com/AbsaOSS/tf-provider-registry-generator) private terraform provider registry generator, based on GitHub release assets and GitHub pages. In oder to fetch private release asset request to github must be authenticated. This works fine for provider metadata but doesn't for actual provider binary.

### Proposal
in oder to achieve that we need to `addHeadersToRequest` in https://github.com/hashicorp/terraform/blob/main/internal/getproviders/registry_client.go#L432, save token into PackageMeta struct and use it later at https://github.com/hashicorp/terraform/blob/main/internal/providercache/package_install.go#L25

### References
https://github.com/hashicorp/terraform/pull/29642 is a feature implementation

**Comment by apparentlymart** [comment]
Hi @k0da! Thanks for sharing this use-case.

I think you're describing the same behavior that we were discussing earlier in #29349, and so I'm going to close this one just to consolidate the discussion there. Thanks again!
