### ISSUE TITLE
terraform-provider-aws_v3.60.0_x5 plugin crashed

### ISSUE THREAD

**Issue by kvsudheerbabu** [hashicorp/terraform#29653]
when applying the following change it crashed. This code is migrated from 0.11 to 1.0.3
aws_storagegateway_smb_file_share
      - cache_attributes {
          - cache_stale_timeout_in_seconds = 0 -> null
        }

Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v3.60.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 75 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsStorageGatewaySmbFileShareUpdate(0xc0023d6880, 0x7320da0, 0xc0013ae000, 0x0, 0xffffffffffffffff)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_storagegateway_smb_file_share.go:391 +0x1b2c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000ea5880, 0x8d845e8, 0xc000b643c0, 0xc0023d6880, 0x7320da0, 0xc0013ae000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:352 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000ea5880, 0x8d845e8, 0xc000b643c0, 0xc002652460, 0xc002643520, 0x7320da0, 0xc0013ae000, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c660, 0x8d845e8, 0xc000b643c0, 0xc00263acd0, 0xc000b643c0, 0x7f7ec20, 0xc002634800)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00071eca0, 0x8d84690, 0xc000b643c0, 0xc0026522a0, 0xc00071eca0, 0xc0026348a0, 0xc0023c8ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x7f7ec20, 0xc00071eca0, 0x8d84690, 0xc0026348a0, 0xc0026a40c0, 0x0, 0x8d84690, 0xc0026348a0, 0xc0023bd800, 0xb60)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003156c0, 0x8da7098, 0xc00014e600, 0xc0023b2000, 0xc00153b0e0, 0xc784ac0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0003156c0, 0x8da7098, 0xc00014e600, 0xc0023b2000, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001718cd0, 0xc0003156c0, 0x8da7098, 0xc00014e600, 0xc0023b2000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.60.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
