### ISSUE TITLE
how to configure china specific registry.terraform.io / mirrors

### ISSUE THREAD

**Issue by cforce** [hashicorp/terraform#29657]
In china we continuously repeating are blocked by Chinese firewall which leads to tf client failed executions because of timeouts on accessing an (static info) via the below url. How can prevent or workaround this by e.g...
* caching (once provider info has been downloaded it will be reused as fallback)
* configure alternative blackened urls aka mirror. Is there a mirror for china region?

```
- Finding hashicorp/azurerm
 versions matching "1.44.0"...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/kubernetes...
- Installing hashicorp/kubernetes v2.5.0...
- Installed hashicorp/kubernetes v2.5.0 (signed by HashiCorp)

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/azurerm: could not connect to registry.terraform.io: Failed to
request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": net/http: request
canceled while waiting for connection (Client.Timeout exceeded while awaiting
headers)


Error: Failed to install provider

Error while installing hashicorp/random v3.1.0: could not query provider
registry for registry.terraform.io/hashicorp/random: the request failed after
2 attempts, please try again later: Get
"https://registry.terraform.io/v1/providers/hashicorp/random/3.1.0/download/linux/amd64":
net/http: request canceled while waiting for connection (Client.Timeout
exceeded while awaiting headers)

ERROR Terraform init failed.
```

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by cforce** [comment]
This was a feature request rather than a question as there is no such feature right now to get the problem solved

**Comment by cforce** [comment]
https://www.terraform.io/docs/cli/commands/providers/mirror.html
https://www.youtube.com/watch?v=WY9W6tHbS8Y
