### ISSUE TITLE
S3 Backend hung after POST to PutObject

### ISSUE THREAD

**Issue by towbes** [hashicorp/terraform#29662]
### Terraform Version

```
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.60.0
```

### Terraform Configuration Files

```terraform
backend.tf
terraform {
  required_version = ">=0.9.2"
  backend "s3" {
    bucket = "my-bucket-name"
    region = "ap-northeast-1"
    key = "terraform.tfstate"
  }
}

provider "aws" {
  region = "ap-northeast-1"
}

aws-vpc.tf
variable "projname" {
  type = string
}

variable "envtype" {
  type = string
  description = "Main or Dropbox for name tags"
}
#------------------------
#       VPCs            |
#------------------------

# Setup Main VPC
resource "aws_vpc" "MAIN-vpc" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "${var.projname}-${var.envtype}-VPC"
    Project = "Red Team - ${var.projname}"
    Codename = "${var.projname}"
  }
}

test.tfvars
projname = "TEST"

envtype = "MAIN"
```

### Debug Output

terraform init Trace output:
https://gist.github.com/towbes/6c6e4b61ddfcd080df3b8e19c92d51a7

terraform apply trace output:
https://gist.github.com/towbes/c0b612c89de29a2ddd8d54f0009f170e

### Expected Behavior

Terraform should write a new terraform.tfstate file to the s3 bucket 

### Actual Behavior

No terraform.tfstate is written to the bucket.  Terraform gets a 404 error from the GetObject call, but does not attempt to write a new file

### Steps to Reproduce

1. terraform init
2. terraform apply

### Additional Context

No wrapper script, just running from terminal

**Comment by jbardin** [comment]
Hi @towbes,

Thanks for filing the issue. Can you provide any more detail about the problem you are having running terraform? It seems the `apply` log only contains the plan portion, up until the prompt for confirmation. There would be no state written out at this point, since nothing has been applied. Has the log possibly been truncated here?

Thanks!

**Comment by towbes** [comment]
The log was not truncated, I was having troubles earlier with the terraform process hanging on apply without ever writing a tfstate file.  I turned on logging and thought that the tfstate should be written after the plan command.

Before posting this I had problems where the apply would hang after creating the objects and never write any tfstate to the bucket.  I would have to ctrl+c out of the terraform process.  It seems I fixed that issue without realizing since I never went past plan

Thanks for taking the time to look at logs.  Sorry for the misunderstanding!  I will close the issue for now as the posted code seems to write a terraform.tfstate as expected after running apply.

**Comment by towbes** [comment]
@jbardin I have re-opened this issue...

This morning I again confirmed that I could write tfstate to the s3 bucket.  Once I confirmed, I cleared out all the test tfstates by running the "Empty" command on the s3 bucket from the amazon console.

After emptying the bucket,  terraform apply hangs after sending the POST request to s3 PutOjbect.  I have updated the apply trace GIST: https://gist.github.com/towbes/c0b612c89de29a2ddd8d54f0009f170e

Please note I changed the above slightly by removing the key from backend.tf and passing it in terraform init

```
backend.tf
terraform {
  required_version = ">=0.9.2"
  backend "s3" {
    bucket = "my-bucket-name"
    region = "ap-northeast-1"
  }
}
```

$terraform init -backend-config="key=backendtest2/terraform.tfstate"

**Comment by jbardin** [comment]
Thanks @towbes. It appears this is hanging in the  POST call itself, which is really outside of Terraform's control. I have seen some quirks around AWS API calls that have a long timeout if you are not authenticated, or don't have permission for the call. Are you certain there's nothing in the bucket policy that could be blocking this from wiring the new state file?

**Comment by towbes** [comment]
I did an IAM policy simulation and confirmed GetObject ListObject and PutObject were all allowed for the s3 bucket. 

 I just re-ran the above apply command with same settings and same bucket, and now the tfstate wrote successfully.

It's now at T+18 hours from earlier, so something in that timeframe seems to have changed to fix the timeout issue.  I haven't made any adjustments to permissions or anything s3 related in that time.

I could not reproduce this by making a fresh bucket using same configs as above.  Tfstate file was written first time using same configs as above (with new bucket name).  Emptied the bucket and re-ran init + apply, and tfstate file written as expected.

I guess I will try this again in ~6 hours to see if there is some undocumented ap-northeast-1 s3 witching hour causing the issue.  If I can't reproduce it again in the morning will close the issue again.

**Comment by towbes** [comment]
Having issues with PutObject hanging again this afternoon.  No idea why, I am using the same bucket that I successfully wrote to in my previous post 13 hours ago.  The only terraform command I ran today was a destroy using a local tfstate file in another project.

Is there any sort or rate limiting that might be applying? Should there eventually be a timeout? It seems to hang for an infinite amount of time

**Comment by towbes** [comment]
Holy moly just posting this as a follow up....for some reason when connected to our VPN the PutObject request was timing out infinitely.  When I disconnected from our VPN , worked like a charm.

When it worked the other night I was disconnected from VPN, and did not connect the dots that had changed.

So posting for future...if you are having this type of issue, try from a different connection / external IP / non-VPN.
