### ISSUE TITLE
Data source and Resource having inconsistent behavior

### ISSUE THREAD

**Issue by etiennejournet** [hashicorp/terraform#29668]
Hello,

Here is the return of a terraform plan : 

```
  # azurerm_resource_group.rg will be updated in-place
  ~ resource "azurerm_resource_group" "rg" {
        id       = "/subscriptions/1234/resourceGroups/my-test-rg"
        name     = "my-test-rg"
      ~ tags     = {
          - "activity" = "demo" -> null
        }
        # (1 unchanged attribute hidden)
    }

  # module.aks.data.azurerm_resource_group.main will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_resource_group" "main"  {
      ~ id       = "/subscriptions/1234/resourceGroups/my-test-rg" -> (known after apply)
      ~ location = "westeurope" -> (known after apply)
        name     = "my-test-rg"
      ~ tags     = {
          - "activity" = "demo"
        } -> (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

```

As you can see the output from the resource block and the data block are not consistent.
- On one side the resource block finds only changes on "tags"
- On the other side the datasource triggers changes on all fields.

This is a problem because it means I cannot use my datasource to properly fetch arguments that I need in another resource. In my case this will make my other resource be recreated although there is no real change. 
The datasource see a change on the whole resource, but there is none.

Is this something that can be fixed in this provider (using the same resourceResourceGroupRead() func for both the resource and the datasource for example) or is this terraform resolution tree logic ?

Thanks,

**Comment by jbardin** [comment]
HI @etiennejournet,

What you are seeing is the expected behavior, and it is not recommended to have a managed resource and its equivalent data source in the same configuration for this reason. If the managed resource is created in the same configuration, you should pass the values from that resource itself as needed.

A data source is read as soon as possible during the planning process, so that its outputs may be used in the planning of other resources. Because the changes to the corresponding managed resource are not going to be updated until the apply completes, the data source cannot see those changes. 

Thanks!

**Comment by etiennejournet** [comment]
Hello @jbardin !

Thanks for your fast answer. 

I'm not sure I understand because it looks to me there is a contradiction between my example and your explaination. 

As you explained, datasources are read as soon as possible.  In my case let's say I've got a resource that is tagged and I want to delete/modify those tags.

I'm under the impression this use case should be ran according to the following steps:
1. Tags are in the terraform code and in the states
2. I do an operation on tags (delete/modify in the code) and run terraform plan
3. terraform read datasource block first and retrieves my resource => no change compared to my states, it still retrieves the same tag block from the existing resource 
4. terraform read the resource block which compares actual state to the new code and shows a difference

I should add in my particular example i'm not referencing my resource in my datasource, I use a common variable instead.
Root module does:
```
resource "azurerm_resource_group" "rg" {
  location = var.location
  name = var.my-test-rg-name
}
```

Later in another module:
```
data "azurerm_resource_group" "main" {
  name = var.my-test-rg-name
}
```

**Comment by jbardin** [comment]
Hi @etiennejournet,

Without a complete, reproducible example it's hard to explain exactly what is causing the behavior you see here.
If `module.aks.data.azurerm_resource_group.main` is not able to be read during the planning process, something else in the configuration is preventing that. Most likely this is either `var.my-test-rg-name` is unknown during the plan, or `module.aks` is attempting to use `depends_on` .  Regardless of the situation however, it will still not be possible to get consistent results in all cases while simultaneously ` azurerm_resource_group` and `data.azurerm_resource_group` in the same configuration representing the same logical resource.

**Comment by etiennejournet** [comment]
Hello @jbardin !

Thanks again for your time.  You pointed it, there was a `depends_on` :)

Indeed it's a consistency problem : we hit a chicken/egg problem in the past with this resource and this datasource and had to use `depends_on` to ensure they run in the proper order. That's what triggered this issue when trying to modify the resource.

I think that makes things more difficult to setup a simple interface (trying to lower the number of variables by computing as much as possible) when providing modules as deliverables. Do you have any recommendation for this ?

Thanks,

**Comment by jbardin** [comment]
The recommendation for reducing required arguments is generally to accept an object corresponding to the entire resource itself. This was you can pass in a `azurerm_resource_group` as a whole, and let the module worry about which individual attributes it needs.
