### ISSUE TITLE
 [vsphere] If there are multiple port groups with the same name openshift installation fails

### ISSUE THREAD

**Issue by ayesha54** [hashicorp/terraform#29664]
When Installing the Openshift cluster on vsphere, I am getting a following error:
 
```
INFO Creating infrastructure resources...
ERROR
ERROR Error: error fetching network: path 'ocp-internal' resolves to multiple networks, Please specify
ERROR
ERROR   on ../../tmp/openshift-install--880355152/main.tf line 34, in data "vsphere_network" "network":
ERROR   34: data "vsphere_network" "network" {
ERROR
ERROR
ERROR Failed to read tfstate: open /tmp/openshift-install--880355152/terraform.tfstate: no such file or directory
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```
I am expecting a feature/possibility to add more description for my Vsphere distributed OR virtual switch in my installation file so that it can detect what port group/network I want for my cluster

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
