### ISSUE TITLE
fmt should be opinionated about a final trailing newline

### ISSUE THREAD

**Issue by jdufresne** [hashicorp/terraform#29677]
In a team setting, some contributors may not have their editor configured to add a final newline to files. When the GitHub UI displays a diff, it shows a red circle 🚫 when a file is missing a trialing newline. This can result in comments during review. It may also require explicit mention in a team's style guide.

Proposal: Have `terraform fmt` automatically add a trailing newline if it doesn't exist. This goes along with `fmt`'s opinionated philosophy. By having a tool handle this, it removes removes the need to think or care about such details, reduces human energy during code review, and promotes a consistent style across terraform files

```
$ docker run --rm hashicorp/terraform:latest version
Terraform v1.0.8
on linux_amd64
```
Example file (no final newline):

```tf
resource "aws_vpc" "my_vpc" {
  cidr_block = "172.16.0.0/16"

  tags = {
    Name = "tf-example"
  }
}
```

Actual behavior: 

No change to the file when running `fmt`:

```
$ docker run --rm -v $(pwd):/workspace hashicorp/terraform:latest fmt /workspace/test.tf
```

Proposed behavior:

Format the file by adding a final newline.

```
$ docker run --rm -v $(pwd):/workspace hashicorp/terraform:latest fmt /workspace/test.tf
workspace/test.tf
```

**Comment by stawii** [comment]
https://github.com/hashicorp/terraform/issues/23223
