### ISSUE TITLE
Terraform init using non hashicorp providers from the Terraform registry results in incorrect checksum on darwin_amd64

### ISSUE THREAD

**Issue by matt-darwin** [hashicorp/terraform#29676]
Terraform init using non hashicorp providers from the Terraform registry results in incorrect checksum on darwin_amd64

### Terraform Version

```
Terraform v1.0.8
on darwin_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  
  required_version = ">= 1.0.7"
  
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version =  ">= 2.15.0"
    }
    grafana = {
      source = "grafana/grafana"
      version = "1.13.4"
    }
  }
}

```

### Debug Output

https://gist.github.com/matt-darwin/075c58b0dbfc30d95ee2f47e130d946e
### Expected Behavior

Terraform installs the grafana and docker providers.

### Actual Behavior
Receive the following error:-

```
│ Error: Failed to install provider
│ 
│ Error while installing grafana/grafana v1.13.4: archive has incorrect checksum zh:28c2ec3a155b77a824206afafdec437f18cadebe5e433e8590f4718f31269657 (expected zh:f2727feedaa3b04d8aedf455a9c5a8a97208e0db67417aa97a26ccf167e58877)
╵

╷
│ Error: Failed to install provider
│ 
│ Error while installing kreuzwerker/docker v2.15.0: archive has incorrect checksum zh:4c1cd01b5981fedd839139c970022c5d9ca72995fa069c5e04677f2e6791bf97 (expected zh:d034295663d8a39035fd6fdf0488b72544b13f48acaee797af967343248676f8)
```

### Steps to Reproduce
```terraform init```

### Additional Context
This appears to only be for darwin_amd64 installs, I have been able to successfully install the providers on a debian container.

**Comment by matt-darwin** [comment]
Hi @jbardin, no there is no proxy configured.

However I also get the same (incorrect) hash when running the following from my mac:-

```matt.darwin@23063-mbpr ~ % curl -sL https://github.com/grafana/terraform-provider-grafana/releases/download/v1.13.4/terraform-provider-grafana_1.13.4_darwin_amd64.zip | shasum -a256
28c2ec3a155b77a824206afafdec437f18cadebe5e433e8590f4718f31269657  -```

If I run the same from inside a debian container on the same machine however I get:-

```appuser@b7a82e7e3863:/terraform}$ curl -sL https://github.com/grafana/terraform-provider-grafana/releases/download/v1.13.4/terraform-provider-grafana_1.13.4_darwin_amd64.zip | shasum -a256
f2727feedaa3b04d8aedf455a9c5a8a97208e0db67417aa97a26ccf167e58877  -```

So this looks like it's possibly a mac issue?

**Comment by taoufik07** [comment]
I can not reach `github.com` and I think that its related to this

```
$ terraform providers lock \
  -platform=darwin_amd64 \
  -platform=linux_amd64
  
- Fetching hashicorp/azurerm 2.76.0 for darwin_amd64...
- Obtained hashicorp/azurerm checksums for darwin_amd64 (signed by HashiCorp)
- Fetching hashicorp/random 3.1.0 for darwin_amd64...
- Obtained hashicorp/random checksums for darwin_amd64 (signed by HashiCorp)
╷
│ Error: Could not retrieve providers for locking
│
│ Terraform failed to fetch the requested providers for darwin_amd64 in order to calculate their checksums: some providers could not be installed:
│ - github/go-gandi/gandi: could not connect to github: Failed to request discovery document: Get "https://github/.well-known/terraform.json": dial tcp: lookup github: no such host.
╵
```

**Comment by jbardin** [comment]
Thanks @matt-darwin,

Since you can replicate the incorrect hash accessing the file directly, can you save the file to the filesystem and inspect what exactly you are getting, and how it differs from the normal release artifact? The fact that you are using a mac shouldn't effect the object retrieved from that url, plus I cannot replicate the issue myself with either darwin_amd64 or darwin_arm64.

**Comment by jbardin** [comment]
I cannot see any reason for you getting a slightly different binary for `terraform-provider-grafana_1.13.4_darwin_amd64.zip` only from a MacOS machine. My last guess is that perhaps that specific binary was re-published somehow and you are getting a stale cache entry. You could check the `-v` output from curl to see where the 302 goes, which should end up at `https://github-releases.githubusercontent.com/93446086/8ec98d0d-97ba-439b-94a5-11ef44b9b4ed` (plus the credentials). Seeing how Terraform and `curl` get the same bytes, it appears that github is returning something different for you here, and there's nothing in that Terraform can do on its own to fix it.

There has been a new release of the provider which you can check to see if you have any issues installing.
