### ISSUE TITLE
Proposal: Delete-protected Resources

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#2967]
There are some resources that are a pain to recreate if they get accidentally deleted. For example, a database can hopefully be restored from a backup but you'll probably lose some latest data and it'll take some time to get the backup restored and get things back online.

As a way to help avoid such accidents, I'd like to propose the concept of a "delete-protected" resource. The basic idea is that Terraform won't delete a delete-protected resource unless some specific actions are taken that are less likely to occur by accident.

That's the goal. Here's my idea for how to implement it:
* Allow each resource to have a ``protect_from_deletion`` flag, defaulting to ``false``. (This could perhaps live inside the ``lifecycle`` sub-block of a resource.) 
* Any time a resource is applied, if ``protect_from_deletion`` is set then a similar flag is set in the resource's state.
* During plan, it is a fatal error if there is a resource in the state with ``protect_from_deletion`` set but that resource does not exist in the new configuration.

There are two ways to get Terraform to delete such a resource:
* Delete it manually via the UI or API of whatever system the resource belongs to. Terraform will notice the resource is gone during refresh and will remove it from the state, so there won't be a deletion diff and thus the plan will complete successfully. Let's call this *out-of-band confirmation*.
* Remove the ``protect_from_deletion`` flag from the configuration and apply it once before actually removing it from the config. The first apply will unset the flag in the state, allowing the second apply to delete it successfully. Let's call this "two-step confirmation".

Both the *out-of-band confirmation* and the *two-step confirmation* require something more than just removing a resource block from the configuration, and both require the user to acknowledge that something is intentionally being deleted. In the former case they acknowledge that by actually deleting it with a different tool, and in the latter case they acknowledge it by explicitly dropping the protection flag.

Of course this flag ought to be used sparingly or else the value of the explicit confirmation will be diluted by the special confirmation steps becoming routine for users. My intent is to use such a feature only for the few resources that have significant local state that cannot be trivially reproduced by a subsequent re-run of ``terraform apply``, so those doing routine deployment can have more confidence that their pushes can be undone relatively-quickly if something doesn't go to plan.

**Comment by stack72** [comment]
@apparentlymart is this a different set of work to this:

```
resource "aws_instance" "web" {
    ami = "foo"
    lifecycle {
        prevent_destroy = "true"
    }
}
```

https://terraform.io/docs/configuration/resources.html#prevent_destroy

**Comment by apparentlymart** [comment]
Oh hey I guess that snuck in when I wasn't paying attention. I've not checked the details but on the surface it looks like exactly what I proposed, so I guess I'll kill this issue. :)

Sorry for the redundant suggestion!

**Comment by stack72** [comment]
@apparentlymart ah glad it was the same functionality :) Best to ask before you spent any further time on it
