### ISSUE TITLE
Can't import _domainkey aws_route53_record into Terraform.

### ISSUE THREAD

**Issue by adamdonahue** [hashicorp/terraform#29688]
```
$ terraform version
Terraform v0.13.7

+ provider registry.terraform.io/hashicorp/aws v3.60.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

Attempting to import the following record fails:

```
$ terraform import 'aws_route53_record.route53_alias["3x6jr7puidd7aqtkh56b2fiagfc2xcgy._domainkey.our-domain.com."]' 'Z04069581CFCSW4QREQQE_3x6jr7puidd7aqtkh56b2fiagfc2xcgy._domainkey.our-domain.com._CNAME'

Error: InvalidInput: 1 validation error detected: Value 'domainkey.our-domain.com.' at 'startRecordType' failed to satisfy constraint: Member must satisfy enum value set: [AAAA, A, CAA, NS, SOA, SPF, MX, PTR, CNAME, DS, TXT, SRV, NAPTR]
	status code: 400, request id: b2b5ba0a-9b97-43d4-93c7-fd40bc12c4b8
```

My impression from reading through prior issues is that this was fixed, although it's not clear if a syntax change of the import format is required.  How can we work around the issue?

(For the record, using underscores in this way with no way of escaping them seems far from ideal.  Shouldn't we at least use a delimiter that would not be accepted within a valid AWS record name?)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
