### ISSUE TITLE
Error: Creating metric alarm failed: ValidationError: MetricName must not contain Non-ASCII characters. Status code: 400, request id ....

### ISSUE THREAD

**Issue by vitaliejicol** [hashicorp/terraform#29681]
Hi There,
I am redeploying one of my Terraform module, but I am getting and error, please see the title. Scope it is to create cloudwatch metric alarm for Cloudfront. I tried all possible scenarios but I am getting constantly the same error when I am changing the metric_name. Can you please advise.

Provider AWS. 

              `resource "aws_cloudwatch_metric_alarm" "_5xxErrors" {
                alarm_name          = "${var.tag_app}_alarm_name"
                comparison_operator = "LessThanOrEqualThreshold"
                evaluation_periods  = "1"
                metric_name         = "5xxErrorRate"
                namespace           = "AWS/CloudFront"
                period              = "60"
                statistic           = "Average"
                threshold           = "1"
                alarm_description   = "Bla bla bla bla"
                alarm_actions       = ["${data.aws_sns_topic.blabla.arn}"]
              
                dimensions = {
                  DistributionId  = "${aws_cloudfront_distribution.cloudfrontdistribution.id}"
                  Region.            = "Global"
                }
              }`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by vitaliejicol** [comment]
@jbardin Thanks!
