### ISSUE TITLE
Random errors when upgrading from 0.12.x to 0.13.x

### ISSUE THREAD

**Issue by grumpper** [hashicorp/terraform#29684]
Hi there,

I am currently trying to move my 0.12.25 repo to 1.0.7.
What my process is for each folder:

1. Initial init to make sure infra is up-to-date:
`terraform init` (+ plan/apply to check for discrepancies)

2. edit the state’s key to have to 0.13 instead of 0.12 in its path (to preserve the 0.12 state just in case):
`terraform init → yes` (when it prompts you to migrate the state)

3. Check again with plan/apply that everything is up-to-date with the new (migrated) state

3. Change TF’s required_version to be 0.13.7 in the code, switch to it and run the upgrade command:
`terraform 0.13upgrade → yes`

4. Init with TF 0.13.7 so it can reconfigure the providers:
`terraform init -reconfigure`

5. Check with plan/apply for issues:
`terraform apply`

6. Change TF’s required_version to be 1.0.7 in the code, init with migrate and check again:
```
terraform init -migrate-state
terraform apply -auto-approve -refresh-only
```

Most of the time this process works fine.
However completely randomly it sometimes fail on step 6.
When i run terraform plan or apply with TF 0.13.7 after its init it sometimes gives me this error:
`Error: cannot decode dynamic from flatmap`

So I delete the 0.13 state file and start the whole process again. It usually complains a few more times and at some point it just succeeds. Nothing changed in the code... I just do the same thing multiple times until it succeeds.

I tried to debug it but no clues:

### Debug Output
```
2021/09/29 15:35:30 [TRACE] eval: terraform.EvalNoop
2021/09/29 15:35:30 [TRACE] [walkRefresh] Exiting eval tree: provider["registry.terraform.io/hashicorp/aws"]
2021/09/29 15:35:30 [TRACE] vertex "provider[\"registry.terraform.io/hashicorp/aws\"]": visit complete
2021/09/29 15:35:30 [TRACE] dag/walk: upstream of "aws_iam_role.stg_backoffice_server_task_role (expand)" errored, so skipping
2021/09/29 15:35:30 [TRACE] dag/walk: upstream of "aws_iam_role_policy_attachment.amazon_ecs_exec_policy_attach (expand)" errored, so skipping
2021/09/29 15:35:30 [TRACE] dag/walk: upstream of "aws_iam_policy.stg_backoffice_server_s3_access_custom_policy (expand)" errored, so skipping
2021/09/29 15:35:30 [TRACE] dag/walk: upstream of "output.stg_backoffice_server_task_role_arn (expand)" errored, so skipping
2021/09/29 15:35:30 [TRACE] dag/walk: upstream of "aws_iam_role_policy_attachment.s3_access_custom_policy_attach (expand)" errored, so skipping
2021/09/29 15:35:30 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" errored, so skipping
2021/09/29 15:35:30 [TRACE] dag/walk: upstream of "root" errored, so skipping
```

I think it fails to update the providers in the state maybe?
I honestly don't have an idea.
It is not related to any specific resource types or anything.
This is completely random.

I even tried removing the .terraform folder and running init without -reconfigure and the behavior is the same.
I checked the state file (versioned file in s3) and it looks like it's not adjusting it at all as there is no new version of it.
It is the same state that 0.12.25 TF migrated.

The TF 0.13.7 init looks like handling the providers name change ok based on it's output:

```
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/aws versions matching "2.36.*"...
- Finding latest version of -/aws...
- Finding latest version of -/random...
- Finding hashicorp/random versions matching "3.1.0"...
- Installing hashicorp/aws v2.36.0...
- Installed hashicorp/aws v2.36.0 (signed by HashiCorp)
- Installing -/aws v3.61.0...
- Installed -/aws v3.61.0 (signed by HashiCorp)
- Installing -/random v3.1.0...
- Installed -/random v3.1.0 (signed by HashiCorp)
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
```

But at this point due to this random behavior it's a cross-fingers situation for me if the consequent apply would be ok or would throw the error.

Side note: no such issues with 0.13 -> 1.0.7 upgrades.

**Comment by jbardin** [comment]
Hi @grumpper,

Can you clarify which step exactly is failing? The log snippet shows that there is a failure during when planning, but "step 5" above is `terraform init -reconfigure`. The complete trace logs from the specific command that is failing might help locate which part of the process is generating the error.

Note that v0.13 is no longer actively developed, so there isn't really any change that we can make at this point. You may have more luck using [the community forum](https://discuss.hashicorp.com/c/terraform-core) where other users may have seen similar problems. However, if there is a bug in the 0.13 upgrade process, it would be good however to at least record it here for future users attempting this upgrade.

Thanks!

**Comment by jbardin** [comment]
Hello,

Since we have not heard back in a while I'm going to close this out.

Because this appears to be a question related to upgrading older versions of Terraform rather than a bug, it would be better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
