### ISSUE TITLE
Add day of week as number to formatdate (and other formatting options)

### ISSUE THREAD

**Issue by gw0** [hashicorp/terraform#29694]
### Current Terraform Version
```
Terraform v1.0.8
on linux_amd64
```

### Use-cases
The `formatdate()` function supports similar formatting options as other tools (see `man date`), but is missing some of them. I currently stumbled upon the missing `u` formatting option that represents day of week as a number (1..7) where 1 is Monday (needed by `google` provider in [sql_database_instance#day](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#day)).

As a workaround for my use case I used the `EEE` formatting option (English day of week name abbreviated to three letters) in combination with mapping from English names to numbers.

### Attempted Solutions
```
output "tu" {
  value = formatdate("u", timestamp())
}

│ Error: Invalid function argument
│ 
│   on a.tf line 2, in output "tu":
│    2:   value = formatdate("u", timestamp())
│ 
│ Invalid value for "format" parameter: invalid date format verb "u".
```

### Proposal
Add `u` and other missing formatting options to `formatdate()`.

**Comment by crw** [comment]
Thank you for your continued interest in this issue. 

[Terraform version 1.8](https://github.com/hashicorp/terraform/blob/v1.8.0-beta1/CHANGELOG.md) launches with support of provider-defined functions. It is now possible to implement your own functions! We would love to see this implemented as a provider-defined function. 

Please see the [provider-defined functions documentation](https://developer.hashicorp.com/terraform/plugin/framework/functions) to learn how to implement functions in your providers. If you are new to provider development, learn how to [create a new provider](https://developer.hashicorp.com/terraform/plugin/framework) with the Terraform Plugin Framework. If you have any questions, please visit the [Terraform Plugin Development category in our official forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). 

We hope this feature unblocks future function development and provides more flexibility for the Terraform community. Thank you for your continued support of Terraform!

**Comment by austinvalle** [comment]
Hey everyone 👋🏻 ,

The `hashicorp/time` provider has just released a new [`rfc3339_parse` ](https://registry.terraform.io/providers/hashicorp/time/latest/docs/functions/rfc3339_parse) function in `v0.11` which should allow you to grab the weekday number (along with other data about an RFC3339 timestamp, example below using the built-in `plantimestamp()` function).

You can test this out now with Terraform [`v1.8.0-beta1`](https://github.com/hashicorp/terraform/releases/tag/v1.8.0-beta1) or wait for the upcoming `v1.8.0` release.

```terraform
# Configuration using provider functions must include required_providers configuration.
terraform {
  required_providers {
    time = {
      source  = "hashicorp/time"
      version = "0.11.1"
    }
  }
  # Provider functions require Terraform 1.8 and later.
  required_version = ">= 1.8.0"
}

locals {
  plan_time = provider::time::rfc3339_parse(plantimestamp())
}

output "weekday" {
  value = local.plan_time.weekday
}

output "weekday_name" {
  value = local.plan_time.weekday_name
}
```

```bash
 $ terraform plan

Changes to Outputs:
  + weekday      = 1
  + weekday_name = "Monday"
```

If you run into any problems with the new function, please create an issue over in the [`time` provider issue tracker](https://github.com/hashicorp/terraform-provider-time/issues ), thanks!
