### ISSUE TITLE
Report a coding issue that uses reference to loop iterator variable

### ISSUE THREAD

**Issue by guodongli-google** [hashicorp/terraform#29693]
### Actual Behavior
At https://github.com/hashicorp/terraform/blob/main/internal/configs/resource.go#L148-L157
https://github.com/hashicorp/terraform/blob/9e0de1c46483f4bcacbe71b79925dde58408382c/internal/configs/resource.go#L148-L156

Within the loop `for _, block := range content.Blocks {`, variable `block` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec).
All instances of `&block.DefRange` within the loop may refer to the last node item updated by the loop. As a consequence, nodes may hold multiple instances of the same `block.DefRange`.

More information on the bug can be found at https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable.

### Expected Behavior

A fix is to avoid storing the address of the shared variable `block`:
```
	for i, block := range content.Blocks {
				...
				diags = append(diags, &hcl.Diagnostic{
					Severity: hcl.DiagError,
					Summary:  "Duplicate lifecycle block",
					Detail:   fmt.Sprintf("This resource already has a lifecycle block at %s.", seenLifecycle.DefRange),
					Subject:  &content.Blocks[i].DefRange,
				})
```
Other places need to be changed as well:

- https://github.com/hashicorp/terraform/blob/9e0de1c46483f4bcacbe71b79925dde58408382c/internal/configs/resource.go#L246
- https://github.com/hashicorp/terraform/blob/9e0de1c46483f4bcacbe71b79925dde58408382c/internal/configs/resource.go#L273
- https://github.com/hashicorp/terraform/blob/9e0de1c46483f4bcacbe71b79925dde58408382c/internal/configs/resource.go#L291

**Found by #deepgo.**

**Comment by jbardin** [comment]
Thanks @guodongli-google,

While it's true that capturing a range loop iterator is something to watch out for, these are not instances of that situation. 
The `content.Blocks` type is `hcl.Blocks`, which has an underlying type of `[]*hcl.Block`. This means that the `block` loop variable is a pointer itself, and individually addressable. It would be nice if this were confirmed by the `go vet` and `staticcheck` analyses, but unfortunately neither have a check for this sort of variable capture (`go vet` can detect instances of closures referencing the loop variable, but not storing a the struct field address in a slice).

Thanks!
