### ISSUE TITLE
ALB as Target Goup for NLB

### ISSUE THREAD

**Issue by ozinka** [hashicorp/terraform#29695]
Dear Hashicorp team,

just a few days ago AWS released new feature ALB as Target Goup for NLB.

Could you advise if it will be supported soon by TerraForm?
We need this feature on our project.

Thnx

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!

**Comment by ozinka** [comment]
Thank you, James!
