### ISSUE TITLE
aws_route_table_association ... diffs didn't match during apply.

### ISSUE THREAD

**Issue by ryanczak** [hashicorp/terraform#2970]
When applying a modular configuration we get the following errors with TF 6.2. TF5.3 works normally. 

The underlying configuration uses an iterator & index to associate the correct routing table with a subnet. 

Error applying plan:

2 error(s) occurred:

* aws_route_table_association.internal.0: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* aws_route_table_association.internal.1: diffs didn't match during apply. This is a bug with Terraform and should be reported.

**Comment by catsby** [comment]
Hey @ryanczak – could you possibly provide a bare-minimum configuration that demonstrates this?

**Comment by catsby** [comment]
Closing for now. If you do have a config that reproduces this that you can share, we'll happily revisit.
