### ISSUE TITLE
Terraform always replaces(destroy & create) GKE autopilot

### ISSUE THREAD

**Issue by hiracchy** [hashicorp/terraform#29730]
### Terraform Version
```
v1.0.8
```

### Prerequisites
I made a gke cluster by calling `terraform apply` with the following code.
```terraform
resource "google_container_cluster" "default" {
  name     = "test"
  location = "asia-northeast1"

  network    = {id of existing vpc}
  subnetwork = {id of existing subnetwork}

  enable_autopilot = true

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
}
```

### Expected Behavior
When I exec `terrafrom plan` with the above same code, terraform shows there's no change and terraform won't do anything.

### Actual Behavior
When I exec `terrafrom plan` with the above same code, terraform says it will replace (destroy & create) the gke cluster even though there's no change.
If the code doens't have `node_config`, it won't happen.

### Steps to Reproduce
0. write the above code
1. call `terraform init`
2. call `terraform apply`
3. call `terraform apply` again

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
