### ISSUE TITLE
ECR Tags Workflow

### ISSUE THREAD

**Issue by moberlander08** [hashicorp/terraform#29752]
So I recently added a new ECR repository to my AWS environment and it caused the tags on each of my ECR repository to be cleared out.  This makes sense given what terraform is supposed to do, so no issue there.  

Currently I use the ECR tags to create an approvedimage, adminoverride, etc, etc tag which containers the value of an ECR image that is approved for K8S deployment.  Is there a way to add an override/flag to not have Terraform manage the ECR tags.   In summary the ECR tags are being levered as part of a container workflow/pipeline.

### Current Terraform Version
12.30

### Use-cases
Allow ECR tags to be managed by another process/script and not terraform(via an override)

### Attempted Solutions
None, as the ECR tags are removed upon each module executation.

**Comment by moberlander08** [comment]
Thank you for the quick response, after some thought that seams more like an AWS provider request.  That being said let me get a test setup and report back.

**Comment by jbardin** [comment]
Since we have not head back, and this is likely a provider issue, I'm going to close this out for now. If you do come up with an example that pertains to Terraform itself, feel free to respond here, or file a new issue with the requested information.

Thanks!

**Comment by moberlander08** [comment]
Sorry for the delay, alot going on.  After some thought, I'm going to tweak the workflow to use a datastore such as DynamoDB as using tags for workflow while technically works isn't meant for dynamic values.
