### ISSUE TITLE
403 Forbidden errors when downloading Terraform providers from the public registry

### ISSUE THREAD

**Issue by caitlincooper** [hashicorp/terraform#29775]
### Terraform Version

```
1.0.5
```

### Expected Behavior

When running terraform init, artifactory provider should have been installed.

### Actual Behavior

Error: Failed to install provider

│
│ Error while installing jfrog/artifactory v2.2.15: could not query provider
│ registry for registry.terraform.io/jfrog/artifactory: failed to retrieve
│ cryptographic signature for provider: 403 Forbidden

### Steps to Reproduce

1. `terraform init`

### Additional Context

This error was happening sporadically today between 11:27am and 12:38pm MST.

**Comment by NeckBeardPrince** [comment]
Seeing same thing with other providers

**Comment by jbardin** [comment]
Hi all,

Thanks for reporting the issue!
The registry team is looking into this. You can follow the current status at https://status.hashicorp.com/
