### ISSUE TITLE
Enable cold storage for AWS Opensearch domain using terraform

### ISSUE THREAD

**Issue by sing22** [hashicorp/terraform#29771]
AWS recently introduced Cold Storage for AWS OpenSearch
https://aws.amazon.com/blogs/big-data/introducing-cold-storage-for-amazon-opensearch-service/

Seems there is no support in terraform as the moment to enable it.

### Current Terraform Version

```
v1.0.6
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Thanks!
