### ISSUE TITLE
`terraform init` fails with s3 backed and workspaces when on default workspace

### ISSUE THREAD

**Issue by jebl01** [hashicorp/terraform#29810]
Since a while back (not really sure when) we get errors when running `terraform init` (on the `default` workspace) on projects with workspace configuration in an s3 backend.

Note! If the first  thing you do is to create and switch to a new workspace, it works as expected.

### Terraform Version
```
Terraform v1.0.9
on darwin_amd64
```

### Terraform Configuration Files
```terraform
terraform {
  required_version = ">= 0.13"
  backend "s3" {
    bucket = "terraform-services.<our_domain>"
    key    = "service.tfstate"
    workspace_key_prefix = "<name>"
    region = "eu-west-1"
    encrypt = true
    dynamodb_table = "terraform_lock"
  }
}
```

### Crash Output
```
Initializing the backend...
Error refreshing state: state data in S3 does not have the expected content.

This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
to manually verify the remote state and update the Digest value stored in the
DynamoDB table to the following value: 
```

### Expected Behavior
The backend should be initialized and when switching to a workspace, the key `terraform-services.<our_domain>/<name>/service.tfstate` should be created after applying (we never apply anything on the `default` workspace).

### Actual Behavior
It crashes with the error above

### Steps to Reproduce
Configure a backend like the example above and try to init it on the `default` workspace.

**Comment by gdavison** [comment]
Hi @jebl01, the error message that you received is because of the DynamoDB lock. In this particular case, it looks like there previously was a Terraform state in the default workspace, which was then deleted from S3 but the lock entry was  not removed from DynamoDB.

We've improved the error message in #29610
