### ISSUE TITLE
templatefile should keep consistent indentation for multiline strings

### ISSUE THREAD

**Issue by tibbon** [hashicorp/terraform#29824]
Currently the code rendered by templatefile does not keep indentation for multiline strings

If the value of `foo` is:

```
hello
world
```

And you use the following template:

```
  # Notice the two space indent
  ${foo}
```

Then the output is, and `world` is not indented.

```
  # Notice the two space indent
  hello
world
```

### Current Terraform Version

```
0.13.5, but this impacts all versions I think
```

### Use-cases
Cleaner end-result rendered templates.

### Attempted Solutions
I tried looking into the way the multiline heredocs are handled, but it doesn't seem applicable here as a solution

### Proposal

Change the interpolation with `templatefile` to keep the inserted code at a consistent indentation level between multiline strings.

### References

My request is largely duplicative of this, which was auto-closed without change:

https://github.com/hashicorp/terraform/issues/15308

**Comment by apparentlymart** [comment]
Hi @tibbon! Thanks for sharing this use-case.

It looks like the other issue you referred to led to the addition of [the `indent` function](https://www.terraform.io/docs/language/functions/indent.html), which allows you to explicitly declare that you intend to have the subsequent lines of your string indented:

```
  ${indent(2, foo)}
```

`indent`'s result here would be `"hello\n  world"` and thus achieve your intended result of having both lines indented by two spaces.

The definition of template interpolation is to just insert verbatim the sequence of characters in the given string value, so I don't think there's any feasible path here to it automatically guessing that you intended to indent and modifying the string directly as you proposed: even ignoring some concerns I have that it'd be a bit too "magical" and surprising, it would also be a breaking change for [the Terraform v1.0 Compatibility Promises](https://www.terraform.io/docs/language/v1-compatibility-promises.html) and so not something we would be able to do for a long time.

I think the `indent` function should allow you to achieve your goals with current versions of Terraform, and so I'm going to close this. Thanks again for sharing the use-case, though!
