### ISSUE TITLE
download zipped terraform module from gcs bucket

### ISSUE THREAD

**Issue by christopherlynnsmith** [hashicorp/terraform#29820]
The syntax on this page https://www.terraform.io/docs/language/modules/sources.html simply has not produced results for me.
this module download from GCS is happening from cloud build.  the service account for cloud build has read access

I have tried every possible combination and I continue to get all kinds of errors. Given urls are prone to mistakes and formation.

it would be nice to have the logs print out the bucket and resource it is attempting to consume..

ie. download module from bucketName: xxx
attempting to retrieve GCS resource: yyy.

I have enabled TF_LOG=TRACE

The logs are not sufficient for trouble shooting

I have gotten storage: bucket name is empty

I have tested my urls with authenticated sessions from cloud shell and I can retrieve via wget.

Configuring urls guided by T\the docs at this page: https://www.terraform.io/docs/language/modules/sources.html
generates errors- 404 errors as.
You can use archives stored in Google Cloud Storage as module sources using the special gcs:: prefix, followed by a GCS bucket object URL.

For example

gcs::https://www.googleapis.com/storage/v1/BUCKET_NAME/PATH_TO_MODULE
gcs::https://www.googleapis.com/storage/v1/BUCKET_NAME/PATH/TO/module.zip

**Logging of error**
- "tf init": Downloading gcs::
Step #1 - "tf init": [31m
Step #1 - "tf init": [1m[31mError: [0m[0m[1mFailed to download module[0m
Step #1 - "tf init": 
Step #1 - "tf init": [0mCould not download module "demo-bucket" (main.tf:10) source code from
Step #1 - "tf init": "gcs::https://storage.cloud.google.com/<bucketName>/path/xxxxmodule.gz":
Step #1 - "tf init": storage: bucket name is empty
Step #1 - "tf init": [0m[0m 

Is this supported? download zip modules from GCS?  if so, what is the url syntax that works?

Thanks

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to [use the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by our few core maintainers.

Based on the information you've provided, it looks like this doesn't represent a specific bug or feature request, so I'm going to close it. Please do feel free to ask your question in the community forum. Thanks!

**Comment by christopherlynnsmith** [comment]
@alisdair ,

In investigating the issue, there are comments that suggest the logging details can be improved - see line #117.
in the below link
https://github.com/hashicorp/terraform/blob/main/internal/getmodules/getter.go

IN addition, there are some possible improvements in the URL parsing logic. hardcoded integers, 3 , 5 and hostnames ...
Thoughts?

https://github.com/hashicorp/go-getter/commit/33529d6ed871a187d943964cd6c5633b8f91e332
