### ISSUE TITLE
Terraform removes static ip addresses & ethernet interfaces from vyatta 6.1 template

### ISSUE THREAD

**Issue by marissaeinhorn** [hashicorp/terraform#29848]
### Terraform Version
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/vsphere v1.15.0

### Terraform Configuration Files

data "vsphere_virtual_machine" "template1" {
  name          = "${var.virtual_machine_template1}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "cloned_virtual_machine1" {
  name             = "vyatta-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  guest_id = "${data.vsphere_virtual_machine.template1.guest_id}"
  wait_for_guest_net_timeout = 1
  scsi_type = "${data.vsphere_virtual_machine.template1.scsi_type}"

  network_interface {
    network_id = "${data.vsphere_network.net1.id}"
  }
  network_interface {
    network_id = "${data.vsphere_network.net2.id}"
  }

  disk {
    label = "disk0"
    size = "${data.vsphere_virtual_machine.template1.disks.0.size}"
    thin_provisioned = false
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template1.id}"
    customize {

      linux_options {
        host_name = "vyatta1"
        domain = "workgroup"
      }
      network_interface {}

      network_interface {}
    }
  }

### Expected Behavior
Virtual machine is cloned from template and static ip addresses and interfaces are preserved from the template.

### Actual Behavior
Virtual machine is cloned but configuration errors out.  Reviewing the vm, the ethernet interfaces 0 and 1 are removed and eth4 and eth5 are listed in the ifconfig output instead.  

│ Error:
│ Virtual machine customization failed on "/DUCKNet DEVELOPMENT/vm/UCWT-CLASS-TEST/Student2/131net_clone":
│
│ An error occurred while customizing VM 131net_clone. For details reference the log file <No Log> in the guest OS.
│
│ The virtual machine has not been deleted to assist with troubleshooting. If
│ corrective steps are taken without modifying the "customize" block of the
│ resource configuration, the resource will need to be tainted before trying
│ again. For more information on how to do this, see the following page:
│ https://www.terraform.io/docs/commands/taint.html
│
│
│   with vsphere_virtual_machine.cloned_virtual_machine1,
│   on main.tf line 158, in resource "vsphere_virtual_machine" "cloned_virtual_machine1":
│  158: resource "vsphere_virtual_machine" "cloned_virtual_machine1" {

### Steps to Reproduce
1. `terraform init`
2.  `terraform plan`
3. `terraform apply`

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
