### ISSUE TITLE
Terraform binary releases are not stripped

### ISSUE THREAD

**Issue by MaxPeal** [hashicorp/terraform#29859]
https://github.com/hashicorp/terraform/blob/f019fb112ee99604b8e437757b04d7bd5b1e1711/scripts/build.sh#L41-L44

strip of the terraform binary / TF_RELEASE dont work,as the terraform binary is not stripped

user@box:/tmp$ wget -q -O- https://releases.hashicorp.com/terraform/1.0.10/terraform_1.0.10_linux_amd64.zip | funzip | file -
/dev/stdin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=quq6RNC8lZOxNUHQ2PeF/YBeVhSaNNEVJIuBCMtf4/LLEhbqE3KcSzk1M8EIw2/HG5x3O7FsONYQXxsMJmR, not stripped
user@box:/tmp$

**Comment by jbardin** [comment]
Hi @MaxPeal,

Terraform is not released via the script you are referencing, so that explain why the `-s -w` flags are not being honored. It does appear that the released binaries could benefit from stripping them down a bit. The current terraform release would save about 13MB in this case.

Thanks!

**Comment by jbardin** [comment]
The build system has been updated, and the next release should contain smaller binaries.
