### ISSUE TITLE
How to give the continaer_id on terraform

### ISSUE THREAD

**Issue by rampatnaik** [hashicorp/terraform#29855]
I refered the terraform code
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecs_container_definition

I can see only variable for container_name not container_id

I wanted to creat all log files in "/var/log/<container_id>/*.log"

Cloud : AWS/ECS
Launch type : EC2

can you help me , how to  add logs after <container_id>

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
