### ISSUE TITLE
The extended API didn't return the corresponding resources

### ISSUE THREAD

**Issue by Wanghx0991** [hashicorp/terraform#29852]
Hi, While trying to use the extended API implemented by the official module registry(https://www.terraform.io/docs/registry/api.html) to query which resources are involved in a specific module , i got the inconsistent behavior between the Api Response and the Website .

### Expected Behavior
The content returned by the interface should be consistent with the page display.

### Actual Behavior
RequestPath: https://registry.terraform.io/v1/modules/terraform-alicloud-modules/disk/alicloud
The content returned by the interface:
```json
{
    "id": "terraform-alicloud-modules/disk/alicloud/1.4.0",
    "owner": "xiaozhu36",
    "namespace": "terraform-alicloud-modules",
    "name": "disk",
    "version": "1.4.0",
    "provider": "alicloud",
    "provider_logo_url": "/images/providers/alibaba.png?2",
    "description": "Terraform module which creates ECS Disks and attach them to ECS instance on Alibaba Cloud",
    "source": "https://github.com/terraform-alicloud-modules/terraform-alicloud-disk",
    "tag": "v1.4.0",
    "published_at": "2019-10-17T01:34:44.760981Z",
    "downloads": 205,
    "verified": true,
    "root": {
        "path": "",
        "name": "disk",
        "readme": "...",
        "empty": false,
        "inputs": [...],
        "outputs": [ ...  ],
        "dependencies": [],
        "provider_dependencies": [
            {
                "name": "alicloud",
                "namespace": "hashicorp",
                "source": "",
                "version": ">=1.56.0"
            }
        ],
        "resources": []
    },
```

But the page can display the specified resources under a specific module:
https://registry.terraform.io/modules/terraform-alicloud-modules/disk/alicloud/latest?tab=resources

### Steps to Reproduce
1. Call Api interface with RequestPath="https://registry.terraform.io/v1/modules/terraform-alicloud-modules/disk/alicloud" that **the 'resources` field  is a empty list.**
2. Query the page(https://registry.terraform.io/modules/terraform-alicloud-modules/disk/alicloud/latest?tab=resources)

### Additional Context
Personally, this is a problem. If not, I hope you can tell me how to obtain the resource type under the specified module in this case. 

Thank you very much!

**Comment by alisdair** [comment]
Thanks for reporting this! For issues with the Terraform Registry, please send an email to terraform-registry@hashicorp.com, which is monitored by the team at HashiCorp responsible for the registry. I'm closing this issue out because it's not a Terraform core bug.
