### ISSUE TITLE
Support for configuring ClassicLink (VPC & launch configuration)

### ISSUE THREAD

**Issue by neurogenesis** [hashicorp/terraform#2985]
While new AWS accounts are VPC-only by default, older accounts may have a bulk of their hosts provisioned in classic / public EC2 instances.

For large customers migrating from classic EC2 to VPC, the best practice is to migrate back-end services like SMTP clusters, databases or message queue servers into VPCs first. Connectivity from classic/public EC2 instances into private ip only VPCs is then enabled via ClassicLink per-instance or with an autoscaling launch configuration.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/vpc-classiclink.html
https://aws.amazon.com/blogs/aws/classiclink-private-communication-between-classic-ec2-instances-vpc-resources/

The two pieces required for this to work are enabling ClassicLink on the VPC and enabling it on the instances / launch configuration.

It looks like it's partially supported in the AWS GO-SDK (autoscale launch configurations):

https://github.com/aws/aws-sdk-go/blob/7eb22717a36d32f4c60645b914ce54ba7c8b375d/service/autoscaling/api.go#L2063

**Comment by CpuID** [comment]
Also, the only way to get any IPv6 support in AWS right now is via an ELB outside of a VPC, with EC2 instances outside a VPC. This is a specific use case where ClassicLink is useful for newly created instances.

**Comment by catsby** [comment]
I just merged #3994 to address this, let me know if you need anything else!

**Comment by dfboyd** [comment]
What about launching EC2 instances with ClassicLink enabled?  There's nothing in the HCL documentation to suggest this is possible.

**Comment by howdoicomputer** [comment]
@catsby @dfboyd So... is creating vanilla classic instances with ClassicLink enabled a thing? That would be tops for doing migrations.

**Comment by lra** [comment]
@dfboyd @howdoicomputer I don't see such a thing, and I doubt it will ever be supported as the AWS API can only attach a classic link to running instances, which lose it on stop/terminate.

Hard to keep a state out of this.
