### ISSUE TITLE
The terraform-provider-aws_v3.63.0_x5 plugin crashed

### ISSUE THREAD

**Issue by dilipkumar888** [hashicorp/terraform#29857]
Error: Request cancelled
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEKSWorkerNodePolicy["devops-tools0"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 48, in resource "aws_iam_role_policy_attachment" "worker-AmazonEKSWorkerNodePolicy":
│   48: resource "aws_iam_role_policy_attachment" "worker-AmazonEKSWorkerNodePolicy" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEKSWorkerNodePolicy["devops-loki"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 48, in resource "aws_iam_role_policy_attachment" "worker-AmazonEKSWorkerNodePolicy":
│   48: resource "aws_iam_role_policy_attachment" "worker-AmazonEKSWorkerNodePolicy" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEKSWorkerNodePolicy["prometheus"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 48, in resource "aws_iam_role_policy_attachment" "worker-AmazonEKSWorkerNodePolicy":
│   48: resource "aws_iam_role_policy_attachment" "worker-AmazonEKSWorkerNodePolicy" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEKS_CNI_Policy["prometheus"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 54, in resource "aws_iam_role_policy_attachment" "worker-AmazonEKS_CNI_Policy":
│   54: resource "aws_iam_role_policy_attachment" "worker-AmazonEKS_CNI_Policy" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEKS_CNI_Policy["devops-tools0"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 54, in resource "aws_iam_role_policy_attachment" "worker-AmazonEKS_CNI_Policy":
│   54: resource "aws_iam_role_policy_attachment" "worker-AmazonEKS_CNI_Policy" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEKS_CNI_Policy["devops-loki"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 54, in resource "aws_iam_role_policy_attachment" "worker-AmazonEKS_CNI_Policy":
│   54: resource "aws_iam_role_policy_attachment" "worker-AmazonEKS_CNI_Policy" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEC2ContainerRegistryReadOnly["prometheus"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 60, in resource "aws_iam_role_policy_attachment" "worker-AmazonEC2ContainerRegistryReadOnly":
│   60: resource "aws_iam_role_policy_attachment" "worker-AmazonEC2ContainerRegistryReadOnly" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEC2ContainerRegistryReadOnly["devops-loki"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 60, in resource "aws_iam_role_policy_attachment" "worker-AmazonEC2ContainerRegistryReadOnly":
│   60: resource "aws_iam_role_policy_attachment" "worker-AmazonEC2ContainerRegistryReadOnly" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_iam_role_policy_attachment.worker-AmazonEC2ContainerRegistryReadOnly["devops-tools0"],
│   on .terraform/modules/k8s-cluster/eks/instance-profile.tf line 60, in resource "aws_iam_role_policy_attachment" "worker-AmazonEC2ContainerRegistryReadOnly":
│   60: resource "aws_iam_role_policy_attachment" "worker-AmazonEC2ContainerRegistryReadOnly" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_launch_template.workers["prometheus"],
│   on .terraform/modules/k8s-cluster/eks/launch_template.tf line 18, in resource "aws_launch_template" "workers":
│   18: resource "aws_launch_template" "workers" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_launch_template.workers["devops-loki"],
│   on .terraform/modules/k8s-cluster/eks/launch_template.tf line 18, in resource "aws_launch_template" "workers":
│   18: resource "aws_launch_template" "workers" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_launch_template.workers["devops-tools0"],
│   on .terraform/modules/k8s-cluster/eks/launch_template.tf line 18, in resource "aws_launch_template" "workers":
│   18: resource "aws_launch_template" "workers" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.k8s-cluster.aws_eks_node_group.worker["devops-tools0"],
│   on .terraform/modules/k8s-cluster/eks/main.tf line 34, in resource "aws_eks_node_group" "worker":
│   34: resource "aws_eks_node_group" "worker" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.k8s-cluster.aws_iam_role.this["phenom-prodcr-us1-alb-controller-role"],
│   on .terraform/modules/k8s-cluster/eks/serviceaccount-roles.tf line 50, in resource "aws_iam_role" "this":
│   50: resource "aws_iam_role" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with module.k8s-cluster.aws_iam_role.this["phenom-prodcr-loki-role"],
│   on .terraform/modules/k8s-cluster/eks/serviceaccount-roles.tf line 50, in resource "aws_iam_role" "this":
│   50: resource "aws_iam_role" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-aws_v3.63.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 36 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEksNodeGroupRead(0x8316a18, 0xc000ed91a0, 0xc001d10200, 0x0, 0x0, 0xc00157e0f0, 0xc00029f908, 0x40e0f8)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_eks_node_group.go:374 +0x201f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0009d9ea0, 0x83169a8, 0xc0017006c0, 0xc001d10200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0009d9ea0, 0x83169a8, 0xc0017006c0, 0xc00158e150, 0x0, 0x0, 0xc000288888, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000d668, 0x83169a8, 0xc0017006c0, 0xc0017008c0, 0xc0017006c0, 0x40b965, 0x71dbca0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001e6fee0, 0x8316a50, 0xc0017006c0, 0xc000ed8900, 0xc001e6fee0, 0xc00147c960, 0xc0013e2ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x74d4b80, 0xc001e6fee0, 0x8316a50, 0xc00147c960, 0xc000ed88a0, 0x0, 0x8316a50, 0xc00147c960, 0xc001410e00, 0x6a3)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000011880, 0x833a6d8, 0xc001ebc900, 0xc0002a6e00, 0xc0013d6990, 0xbdc2fd0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000011880, 0x833a6d8, 0xc001ebc900, 0xc0002a6e00, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000d34130, 0xc000011880, 0x833a6d8, 0xc001ebc900, 0xc0002a6e00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.63.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
