### ISSUE TITLE
Terraform resource to promote cloud sql replica to primary 

### ISSUE THREAD

**Issue by kp250278** [hashicorp/terraform#29877]
### Current Terraform Version

[vagrant@centos7 ~]$ terraform version
Terraform v0.12.31

Checked with the Existing provider/versions this feature is not available with latest as well

### Use-cases

We are using cloud sql postgres with cross region read replica option and there is option to enable automatic failover using terraform but there is no option to failover that using terraform resource/settings/option.

Currently we are suing Gcloud API commands to promote the replica for DR testing. As we are using gcloud command to promote the replica our cloud sql instance created using terraform no longer sync with statefile(terraform)

Autofailover option not feasible as if there is any other issue with primary it will promote the replica in that case. also we need to update the connections strings into applications as application is still pointing to primary instance connection string.

### Attempted Solutions

Created ansible role using gcloud command to promote replica. due to this instance going out of sync with statefile and we unable to update using TF.
referance - https://cloud.google.com/sql/docs/mysql/replication/manage-replicas#:~:text=gcloud%20sql%20instances%20promote

### Proposal

if there is a TF resource/settings/option available that we can use for promote read replica to primary that will be good.
so statefile will not out of sync with the promoted instance and we are good to use this clous sql instance under terraform

### References

referance - https://cloud.google.com/sql/docs/mysql/replication/manage-replicas#:~:text=gcloud%20sql%20instances%20promote
- #6017

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
