### ISSUE TITLE
Create ouput objects/arrays

### ISSUE THREAD

**Issue by Kronk74** [hashicorp/terraform#29897]
### Current Terraform Version

```
0.15.4
```

### Use-cases

Hi all,

I created virtual machines via vmware terraform provider. My goal is to generate an output file to list all VMs created with their name, IP, tags, etc...

### Attempted Solutions

It could be great if we could create output map, or array like this : 

```
"vms" = {
  "vm1" = {
    "name" = "test",
    "ip" = "10.0.0.1",
    "tags" = "test, plop, ..."
  },
  "vm2" = {
    "name" = "test2",
    "ip" = "10.0.0.2",
    "tags" = "test, plop, ..."
  }, ...
}
```

If the output look like this, it can be reuse for documentation, for example with terraform-docs.

I don't know if it a good idea or if it can be usefull to someone else but here is my idea :)

**Comment by jbardin** [comment]
Hi @Kronk74,

Thanks for filing the issue. Can you show an example of what are trying to do which isn't working? You can create output values of any type. In the simplest form, if you assign a resource created with `for_each` to an output you will get a map exactly as you as described here. 

For example:

```
resource "random_pet" "test" {
  for_each = toset(["a", "b"])
}

output "pets" {
  value = random_pet.test
}
```

yields:

```
pets = {
  "a" = {
    "id" = "vital-puma"
    "keepers" = tomap(null) /* of string */
    "length" = 2
    "prefix" = tostring(null)
    "separator" = "-"
  }
  "b" = {
    "id" = "pure-shiner"
    "keepers" = tomap(null) /* of string */
    "length" = 2
    "prefix" = tostring(null)
    "separator" = "-"
  }
}
```

Which can also be accessed via `terraform show` in both human readable and json formats.

**Comment by jbardin** [comment]
Since we have not heard back I'm going to close this issue.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
