### ISSUE TITLE
Support for VMSS and AppService in Application Gateway Backend Pool

### ISSUE THREAD

**Issue by kantkrish** [hashicorp/terraform#29906]
```
...
```

### Use-cases

To use VMSS/App Service as a backend target in Application Gateway Backend Pool, other than IP and FQDNs

### Attempted Solutions

As of now we are using the option of Application Gateway Backend Pool ID on the VMMS side, but our App GW code state see that as a change and reverts it in the next run. We have done state import of Application Gateway post deployment of VMSS and adding the VMSS in backend pool as target but its not scalable.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
