### ISSUE TITLE
vSphere plugin - doesnt connect network adapter

### ISSUE THREAD

**Issue by it-pappa** [hashicorp/terraform#29905]
### Terraform Version
```
v1.0.10
```

### Expected Behavior
Network Adapter should be connected. 

### Actual Behavior
Isnt connected and get error: 
An error occurred while setting up network properties of the guest OS. See the log file /var/log/vmware-imc/toolsDeployPkg.log in the guest OS for details.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
Use any guides from online:
vSphere 6.7
Template built with packer v 1.7.6
template OS: Ubuntu 20.04 Iso. 

### Additional Context
I have tested with minimal config and larger, i have tested the guides on hashicorp/terraform website and more. 

### References
Seen this been mentioned alot but hasnt seen anyone solving this.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
