### ISSUE TITLE
Error waiting for AMI: unexpected state 'failed', wanted target 'available'

### ISSUE THREAD

**Issue by bevacqua** [hashicorp/terraform#2990]
Hey there, I'm in the process of switching from AWS EC2 packer builds to using VPS. I first build a base image installing debian, nginx, and configuring things. Later, I use that base image to install a node app on top. This worked great before changing to VPS. Now I'm seeing this error.

<img width="1235" alt="screen shot 2015-08-12 at 17 59 14" src="https://cloud.githubusercontent.com/assets/934293/9236546/de6029f4-411b-11e5-870d-24bb094ff9a3.png">

Can you think of any possible issues?

**Comment by bevacqua** [comment]
It didn't happen the second time around, though.

**Comment by apparentlymart** [comment]
@bevacqua this looks like a Packer issue rather than a Terraform one. Did you mean to open this in [https://github.com/mitchellh/packer](the Packer repo)?

**Comment by bevacqua** [comment]
Oops. Sorry about that.

**Comment by eikenb** [comment]
I couldn't find a packer issue about this? I'm seeing this same issue, was it resolved or is there a packer issue I'm am missing? Thanks.

**Comment by bevacqua** [comment]
It went away and I never saw it again so I didn't open another one over at the `packer` repo

**Comment by eikenb** [comment]
Transient AWS a potential diagnosis... so that helps. Thanks.

**Comment by eikenb** [comment]
Turns out our problem was that we hit the snapshot limit. Use trusted adviser's performance tab to check.

**Comment by aravindgv** [comment]
Yes, I had a similar issue. Resolved after increasing soft limit for snapshot from 10K to 20K
