### ISSUE TITLE
Resource "aws_ebs_encryption_by_default" doesn't support import

### ISSUE THREAD

**Issue by VF-mbrauer** [hashicorp/terraform#29911]
### Current Terraform Version

```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.40.0

Your version of Terraform is out of date! The latest version
is 1.0.10. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use-cases

Importing of the ressource "aws_ebs_encryption_by_default" is not possible.

Example:
_terraform import  module.secure_baseline.module.ebs-volume-encryption_eu-central-1.aws_ebs_encryption_by_default.main main_

Result: 
Error: resource aws_ebs_encryption_by_default doesn't support import

### Attempted Solutions

n/a
### Proposal

n/a
### References

n/a

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
