### ISSUE TITLE
Kafka Connect

### ISSUE THREAD

**Issue by lewisstevens1** [hashicorp/terraform#29935]
Currently, we are trying to implement Kafka connect with our new Kafka cluster. This is able to be done via the AWS console however as it is a new service we noticed it is not in Terraform.

Until it is available in Terraform I have been having to make separate API calls to:
`aws kafkaconnect list-custom-plugins`
`aws kafkaconnect create-custom-plugin`
`aws kafkaconnect list-connectors`
`aws kafkaconnect create-connector`

This should be able to create a new plugin and connector under "Custom plugins" and "Connectors" tab (Under MSK Connect).

I hope someone with skills will go would be able to implement this if possible.

# References
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/kafkaconnect/index.html
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/kafkaconnect

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by lewisstevens1** [comment]
No worries thanks will do!
