### ISSUE TITLE
How to loop over variable using count?

### ISSUE THREAD

**Issue by toddrosner** [hashicorp/terraform#2993]
I've seen several questions that relate to this but I can't seem to find an accurate comparison or solution. I have 3 existing subnets. I also have 6 instances in a resource that need to be launched. The instances need to be spread across the already existing 3 subnets (i1=s1, i2=s2, i3=s3, i4=s1, i5=s2, i6=s3). The sequence can be random as long as each subnet is receiving 2 instances.

If I use the count method, the first 3 instances are mapped to the 3 subnets, then the following 3 are looking for an additional 3 subnets...which don't exist. This is understandably due to the mapping feature of the lookup function I've tried. Below is what I have.

#### Subnet variables
```
variable "subnets" {
  default = {
    "0" = "subnet-123"
    "1" = "subnet-456"
    "2" = "subnet-789"
  }
}
````
#### Instance resource
```
resource "aws_instance" "web-layer" {
  connection {
    user = "ec2-user"
    key_file = "${var.aws_key_path}"
  }
  count = 6
  ami = "${var.aws_ami}"
  instance_type = "${var.aws_instance}"
  subnet_id = "${lookup(var.subnets, count.index)}"
  tags {
    Name = "web-layer-${var.environment}-${count.index}"
    Environment = "${var.environment}"
  }
  # Set user data
  user_data = "${file(\"bootstrap.sh\")}"
  key_name = "${var.aws_key_name}"
}
````

#### Errors
````
* 1 error(s) occurred:

* 3 error(s) occurred:

* lookup: lookup in 'subnets' failed to find '3' in:

${lookup(var.subnets, count.index)}
* lookup: lookup in 'subnets' failed to find '4' in:

${lookup(var.subnets, count.index)}
* lookup: lookup in 'subnets' failed to find '5' in:

${lookup(var.subnets, count.index)}
````

Is there a method to accomplish what I'm after?

**Comment by mlrobinson** [comment]
I needed something similar. You can achieve it using the modulus (%) operator when doing the lookups:
```
 subnet_id = "${lookup(var.subnets, count.index%3)}"
```

It would be nice to have a function to get the size of a map like that, but there isn't. Your "best" bet is to set the max number of subnets in a variable, so if you update the subnets you can also update the total in one file.

**Comment by toddrosner** [comment]
That worked perfectly. Amazing how simple that is and yet I couldn't find the solution anywhere else.

Much appreciated!

**Comment by koebane** [comment]
I tried this but I ran into a problem, Maybe someone can help.

```
variable "zones" { default = [ "us-west-1","us-west-2"] }
variable "services" { default = [ "git","jenkins","ui","jms"] }

resource "something" "monitoring" {
  count = "${length(var.zones) * length(var.services)}"
  name = "Monitoring - ${element(var.zones,count.index%length(var.zones)} - ${element(var.services,count.index%length(var.services)}"
}

```

the result of this is 
"Monitoring - us-west-1 - git"
"Monitoring - us-west-2 - jenkins"
"Monitoring - us-west-1 - ui"
"Monitoring - us-west-2 - jms"
"Monitoring - us-west-1 - git"
"Monitoring - us-west-2 - jenkins"
"Monitoring - us-west-1 - ui"
"Monitoring - us-west-2 - jms"

If one of the lists is an odd number, it works fine but 2 odds would have some duplication as well.

Am I doing something wrong?

Thanks in advance

**Comment by moxli** [comment]
@koebane Did you figure it out? 
I am facing the exact same problem right now...

**Comment by dallasgraves** [comment]
@koebane and @moxli 
I know I'm late to the party but leaving this here to hopefully help anyone wrestling with this.  Looks like it's a problem with using "element" in the count index, apparently it doesn't let Terraform assess the current inventory.  Check [HERE](https://github.com/hashicorp/terraform/issues/15612) for more details...
