### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Bdoom** [hashicorp/terraform#29960]
Just submitting this because the output says I should

Stack trace from the terraform-provider-aws_v3.58.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 707 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.readBlockDevices(0xc000f73b80, 0xc001ba6240, 0xc00247b560, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_instance.go:1892 +0x799
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsInstanceRead(0xc000f73b80, 0x6e81b60, 0xc0006c4000, 0xc0022f2400, 0xc000680000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_instance.go:1105 +0x1cc6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000526000, 0x88cc088, 0xc0020fea40, 0xc000f73b80, 0x6e81b60, 0xc0006c4000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:335 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000526000, 0x88cc088, 0xc0020fea40, 0xc0020bf490, 0x6e81b60, 0xc0006c4000, 0xc0003099f8, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00073a678, 0x88cc088, 0xc0020fea40, 0xc0020fea80, 0xc0020fea40, 0xa6beca, 0x77e9400)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675/helper/schema/grpc_provider.go:575 +0x45b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001143b40, 0x88cc130, 0xc0020fea40, 0xc0013aa120, 0xc001143b40, 0xc002159020, 0xc001739ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x108
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7ad7000, 0xc001143b40, 0x88cc130, 0xc002159020, 0xc0013aa0c0, 0x0, 0x88cc130, 0xc002159020, 0xc0010cc000, 0x78e)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000231500, 0x88eeff8, 0xc001ff8000, 0xc001a86b00, 0xc000841530, 0xc2a2650, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000231500, 0x88eeff8, 0xc001ff8000, 0xc001a86b00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000fd4db0, 0xc000231500, 0x88eeff8, 0xc001ff8000, 0xc001a86b00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.58.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
