### ISSUE TITLE
provider/aws: Add support for multiple EIPs to a single Network Interface

### ISSUE THREAD

**Issue by choosy** [hashicorp/terraform#2997]
Hi,

There must be a way to associate an eip with a network interface and with a private ip address.

Like here:

http://boto3.readthedocs.org/en/latest/reference/services/ec2.html#EC2.Client.associate_address

**Comment by stack72** [comment]
@choosy the way I would do this is as follows:

```
resource "aws_eip" "nat_ip" {
  vpc = true
  network_interface = "${aws_network_interface.nat_eni.id}"
}

resource "aws_network_interface" "nat_eni" {
  subnet_id = "${aws_subnet.primary-public.id}"
  security_groups = ["${aws_security_group.nat.id}"]
  source_dest_check = false
}
```

**Comment by choosy** [comment]
Hi @stack72 , thank you for your response.
Indeed, I am already doing this as a workaround. 
But this way I cannot specify multiple private ips for the same network interface and still connect a particular eip with a particular private ip.

**Comment by stack72** [comment]
@choosy I'm not sure i follow. Let me try and summarise:

* you have an ENI with multiple private_ips
* you are associating that ENI with an ElasticIP
* you are not able to associate a specific private_ip to the EIP

Is this correct?

**Comment by choosy** [comment]
Hi @stack72,

That's correct, except I want to associate 2 ElasticIPs with the same ENI. And associate each of the 2 ElasticIPs with a particular private ip, as the aws console and API let you do.

**Comment by stack72** [comment]
@choosy ok, this makes sense now - I agree that this isn't possible with Terraform 

Hopefully this gives enough information for 1 of the team to be able to classify it though :)

**Comment by catsby** [comment]
Hey @choosy and @stack72 – I think I follow here, and I _think_ I see what's missing.
Can you give me an example of how you would ideally configure this in Terraform? 

Something like so?

```javascript
resource "aws_eip" "nat_ip_one" {
  vpc = true
  network_interface = "${aws_network_interface.nat_eni.id}"
  private_ip = "${element(aws_network_interface.private_ips, 0)}"
}

resource "aws_eip" "nat_ip_two" {
  vpc = true
  network_interface = "${aws_network_interface.nat_eni.id}"
  private_ip = "${element(aws_network_interface.private_ips, 1)}"
}

resource "aws_network_interface" "nat_eni" {
  subnet_id = "${aws_subnet.main.id}"
  security_groups = ["${aws_security_group.nat.id}"]
  private_ips = ["10.0.10.1", "10.0.9.1"]
}
```

**Comment by choosy** [comment]
@castby yeah, like that would work. or specify the private_ip directly in the "aws_eip".
Like
resource "aws_eip" "nat_ip_one" {
  vpc = true
  network_interface = "${aws_network_interface.nat_eni.id}"
  private_ip = "10.10.2.3"
}

But I think you mean the same thing. And if it works, it will work in both ways.

**Comment by daveadams** [comment]
I think what's missing is a Terraform resource that represents an elastic IP association.

I have a need to provision some elastic IPs in a separate module from where I provision my instances and I would like to be able to specify the association in a separate step. And to re-associate the EIP without destroying it at some later point. A separate association resource (AWS recognizes it as a separate resource) would solve both our problems.

Other AWS relationships have separate resources for representing the association--volume mounts for one, as an example.

**Comment by duggan** [comment]
Being able to associate multiple EIPs with ENIs is something I'd like to see too. Otherwise, there's an "EIP per ENI" limit on configuring via Terraform ([which is quite limiting, as you can see from the table in the docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html)).

**Comment by justnom** [comment]
I came up against the same problem and my solution was:

1. Query the network interface API from the instance with the ENI attached
2. Template my nginx configuration to listen on private IP x depending on which EIP it is mapped too

I know it sounds like a "work around" but in practice it means that we don't have to worry about which EIP is assigned to which private address. 

This works wonders when auto-scaling or having two load balancers with multiple EIP's - in my case.

**Comment by borsboom** [comment]
@justnom: Your workaround makes sense, but how were you able to attach multiple EIPs to an instance in the first place?

**Comment by justnom** [comment]
You need to set the EIP to attach to only the network interface and not the instance:

If that has already been done - then just make sure that there is a un-assigned private IP address on the ENI.

Example:
```
resource "aws_network_interface" "lb_sites_1" {
	subnet_id = "${aws_subnet.public_a.id}"
	private_ips = ["10.0.33.0", "10.0.33.1"]
	attachment {
		instance = "${aws_instance.lb_a.0.id}"
		device_index = 1
	}
	depends_on = ["aws_instance.lb_a"]
}

resource "aws_eip" "lb_sites_1" {
	count = "2"
	vpc = true
	network_interface = "${aws_network_interface.lb_sites_1.id}"
	depends_on = ["aws_network_interface.lb_sites_1"]
	lifecycle {
		prevent_destroy = true
	}
}
```

**Comment by borsboom** [comment]
@justnom: Hmm, that doesn't work for me.  I copied and pasted exactly your configuration, only adjusting the IP addresses an subnet/instance IDs, and I still get the same error ([full output here](https://gist.github.com/borsboom/8435f89b67b168046a38)).  Which version of TF are you using?  I'm on the latest (0.6.14).

**Comment by justnom** [comment]
@borsboom 

I haven't tested my configuration on the latest version, I am still using v0.6.6.

If you look at the ENI in the AWS console - is there at least one free private IP address available?

I'll try again on v0.6.14 and let you know! :)

**Comment by borsboom** [comment]
@justnom I confirmed that there's a free private IP address available in the AWS console.  I also tried downgrading to v0.6.6, but still got the same error.  So colour me confused... I can live with adding EIPs as a manual step after running the TF, although I'd rather not have to of course.
