### ISSUE TITLE
Splat operator on an unknown value should result in an unknown value

### ISSUE THREAD

**Issue by Nuru** [hashicorp/terraform#29973]
### Terraform Version

```
$ tf1 version
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

<details><summary>Click to reveal full Terraform HCL</summary>

### ./child/main.tf

```terraform
variable "name" {
  type = string
}

variable "label" {
  type    = string
  default = null
}

resource "null_resource" "label_succeed" {
  count = length(var.label[*]) > 0 ? 1 : 0
}

resource "null_resource" "name_succeed" {
  count = length(var.name[*]) > 0 ? 1 : 0
}

resource "null_resource" "name_fail" {
  count = 0
}

locals {
  dependent = substr(compact(concat(null_resource.name_succeed[*].id, null_resource.name_fail[*].id, ["b"]))[0], 0, 1) == "+"
}

output "label_id" {
  value = null_resource.label_succeed[0].id
}

output "name_id" {
  value = local.dependent ? "non-null" : null
}
```

### main.tf

```hcl
variable "v" {
  type    = string
  default = "1"
}

resource "random_id" "random_label" {
  byte_length = 2
  keepers = {
    keep : var.v
  }
}

module "a" {
  source = "./child"
  name   = substr(random_id.random_label.hex, 0, 1) == "N" ? "non-null" : null
  label  = random_id.random_label.hex
}

resource "random_id" "dependent" {
  count       = length(module.a.name_id[*]) > 0 ? 1 : 0
  byte_length = 2
}

output "main-test-out" {
  value = {
    label : module.a.label_id
    name : module.a.name_id
    name_length : length(module.a.name_id[*])
    dependent        = join("", random_id.dependent[*].hex)
    dependent_length = length(random_id.dependent)
    random_label : random_id.random_label.hex
  }
}
```

</details>

### Expected Behavior

I expected this to fail with the error
```
 "count" value depends on resource attributes that cannot be determined until apply...
```

because there is no way to tell how many `random_id.dependent` resources to make until after `random_id.random_label` is generated.

### Actual Behavior

- On the first `plan`, `dependent_length` and `name_length` are both predicted to be `1`.
- After `apply`, the actual output shows `dependent_length = 1` and `name_length = 0`
- Running `apply` again, `dependent_length` becomes `0` and resources `random_id.dependent[0]` and `module.a.null_resource.name_succeed[0]` are destroyed

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -auto-approve`
3. `terraform apply -auto-approve`

### References

Seems similar to #29799, but I would expect the current Hashicorp `null` and `random` providers not to be having problems you can blame on legacy SDK behavior.

**Comment by jbardin** [comment]
Hi @Nuru,

Thanks for bringing up this example. The difference here can be summed by the two expressions:

 - the expression `"val"[*]` expands to `["val"]`
 - the expression `null[*]` expands to `[]`

This means that `<unknown>[*]` may or may not have a single item, and therefor should produce an entirely unknown value. 

I'm a bit surprised that we haven't seen this reported before, but this particular legacy behavior is rarely used, so perhaps no one has exercised it to this extent. 

Thanks!

**Comment by Nuru** [comment]
@jbardin wrote
> 
> I'm a bit surprised that we haven't seen this reported before, but this particular legacy behavior is rarely used, so perhaps no one has exercised it to this extent.
> 

I bring this up because it is (or was) a [recommended workaround](https://github.com/hashicorp/terraform/issues/26755#issuecomment-794258499) for #26755, and I think perhaps a lot of people are using it without knowing about this behavior. My guess is the main use case is for situations where the value is unknown but guaranteed non-null, such as the ID of a provisioned resource, in which case this issue will never cause problems. It only causes problems when the unknown value turns out to be `null` at apply time.

**Comment by Cajga** [comment]
So I had another look and we do use this method to be able to run our terraform code at once. @jbardin just to make it sure that we understand your change:
This change will break our code that I describe here: https://github.com/hashicorp/terraform/issues/26755#issuecomment-794258499

**Comment by jbardin** [comment]
The HCL update only partially fixes the issue, but this particular glitch in the evaluation is still there. I'll follow up in the HCL repository.

**Comment by jbardin** [comment]
@Cajga, yes that is correct. The linked example should not be valid because the count argument cannot be known during the plan.
