### ISSUE TITLE
encryption

### ISSUE THREAD

**Issue by themonaminor** [hashicorp/terraform#29975]
how to encrypt the terraform files(main.tf, varibales.tf etc) so that if in any case we share our code no one can see the code as it is encrypted.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
