### ISSUE TITLE
Specify network interface to use when launching instance

### ISSUE THREAD

**Issue by choosy** [hashicorp/terraform#2998]
There needs to be a way to indicate the network interface to use when launching an instance. This way, the default (eth0) network interface of the instance could be the one indicated.
Otherwise, a later attached network interface will be added on top of the default one.

**Comment by catsby** [comment]
I looks like we can do this by adding a `network_interface` attribute to Instance, and specifying the `NetworkInterfaceId` in the [InstanceNetworkInterfaceSpecification][1]

[1]: https://github.com/hashicorp/terraform/blob/b-aws-eip-computed-instance/builtin/providers/aws/resource_aws_instance.go#L990

**Comment by choosy** [comment]
@catsby, actually it is not the same thing with the one I am requesting. I am already using the InstanceNetworkInterface specification to attach an eni to an instance.
But when creating an instance, aws already makes an eni, before you attach anything. So when you attach something, you will end up with a second eni.
So for example by default, if you use device_index = 0 in the eni-instance attachment, you will have an error like:
* aws_network_interface.eni-vpc29-idx-1: Error attaching ENI: InvalidParameterValue: Instance 'i-407995e0' already has an interface attached at device index '0'.

if you use other device_index, you will get two enis, even if you only need one. And if for example you want to attach to enis, like we need in our scenario, you won't be able. Because you will have three in total (two plus the default one), and aws has a limit on this.

That is why, the aws api call for creating an instance have a specific parameter for indicating an ani. That's the default and first eni with which the instance start. Whatever attachements you do afterwards, come on top of that.

**Comment by joelmoss** [comment]
@catsby This is really annoying for me. Would like to help here if I can. Any chance you can point me in the right direction?

**Comment by pikeas** [comment]
+1, I'm setting up some critical instances (eg, Kubernetes master) that should have ENIs in case they ever fall over. My options are a) create instance with auto ENI and manually turn off the ENI's "Delete on terminate" attribute, or b) attach a second ENI to every instance, leaving the original AMI dangling per @choosy and preventing the use of an additional ENI.

It would be much easier if I could specify the ENI on instance creation, and this is already supported by the AWS API.

**Comment by fattyuke** [comment]
I just ran into this as well. I would prefer to assign eth0 to an end I create. I've got 2 ENIs that get created, but I end up with a total of 3 interfaces on the instance. I would prefer just two. I can do this via the AWS cli as well as cloudformation. Has there been any work done on this?

**Comment by aberrios85** [comment]
Hi, also hitting up against this. Just wondering if there's much movement on the issue.

**Comment by aaroncaito** [comment]
Also needing this - and can we use it from within a aws_launch_configuration?

**Comment by zzzuzik** [comment]
+1

**Comment by Andy--Rose** [comment]
+1

**Comment by lbernail** [comment]
+1
This would be great and solve issue #1557 
(probably better this solution is more generic)

**Comment by cmonaghan** [comment]
+1. I'm hitting up against this too.

**Comment by rjinski** [comment]
+1

**Comment by thallam08** [comment]
Also have the same issue.  The link from instance to its interfaces needs be maintained.

**Comment by geoffles** [comment]
+1 please!

**Comment by evan-glick** [comment]
+1.  Experiencing same issue with indicating the network interface to use when launching an instance, and wanting to be able to Tag/Name this default Network Interface.

**Comment by acholt** [comment]
+1 - Have the same issue.

**Comment by thomasrg** [comment]
+1 yes please!

**Comment by JustLeo** [comment]
+1

**Comment by leofernandezg** [comment]
+1
We need to attach more than a network interface to an intances. network_instances_ids must be a list.

**Comment by KieranHons** [comment]
+1

**Comment by 3rwww1** [comment]
Hi, same here, this issue prevents me from terraforming a critical part of my infrastructure.

I've noticed there is at least two already opened pull-requests for this:
https://github.com/hashicorp/terraform/pull/10244
https://github.com/hashicorp/terraform/pull/10516

@sebcreme

**Comment by chiradeep** [comment]
@Andy--Rose for a workaround to the NetScaler issue, you could try using CloudFormation for just the NS VPX. Here is an example:
https://github.com/chiradeep/netscaler-autoscale-lambda/tree/master/setup

**Comment by lisfo4ka** [comment]
+1

**Comment by morkot** [comment]
+1

**Comment by PeterWeiler** [comment]
+1

Use case is for name servers referenced in DHCP options.  The ENIs are setup by another team's automation when the VPC is created.  I need to find and use those ENIs when starting the instances that provide recursive name resolution.

**Comment by grubernaut** [comment]
Fixed via #12933

**Comment by geoffles** [comment]
Thanks for the fix :)
