### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing during terraform deployment

### ISSUE THREAD

**Issue by boboky** [hashicorp/terraform#29982]
Please assist with looking into this issue:
[Error: rpc error: code = Unavailable desc = transport is closing during terraform deployment](https://github.com/hashicorp/terraform-provider-azurerm/issues/14273)

and 

[The terraform-provider-azurerm_v2.86.0_x5.exe plugin crashed!](url)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
