### ISSUE TITLE
Error creating CloudTrail: InsufficientS3BucketPolicyException

### ISSUE THREAD

**Issue by kairu97** [hashicorp/terraform#29991]
Hi, I have an issue integrating CloudTrail with CloudWatch Log Group. I troubleshooted it using this issue found three years ago: https://github.com/hashicorp/terraform/issues/6388 . Problem was, even if I put depends_on, it still shows up the error.

This is the error that shows up:
```
│ Error: Error creating CloudTrail: InsufficientS3BucketPolicyException: Incorrect S3 bucket policy is detected for bucket: cloudtrail-demotrail-bucket
│ 
│   with module.cloudtrail.aws_cloudtrail.cloudtrail,
│   on module/cloudtrail/main.tf line 7, in resource "aws_cloudtrail" "cloudtrail":
│    7: resource "aws_cloudtrail" "cloudtrail" {
│ 
```

```
data "aws_caller_identity" "current" {}

resource "aws_cloudwatch_log_group" "cloudtrail_logs" {
  name = "CloudTrail_Logs"
}

resource "aws_cloudtrail" "cloudtrail" {
  name                          = "tf-cloudtrail"
  s3_bucket_name                = aws_s3_bucket.cloudtrail_bucket.id
  s3_key_prefix                 = "cloudtrail"
  include_global_service_events = true
  enable_log_file_validation    = true
  is_multi_region_trail         = true
  cloud_watch_logs_group_arn = "${aws_cloudwatch_log_group.cloudtrail_logs.arn}:*"
  depends_on = [aws_s3_bucket_policy.CloudTrailS3Bucket, aws_s3_bucket.cloudtrail_bucket]
}

resource "aws_s3_bucket" "cloudtrail_bucket" {
  bucket        = var.cloudtrail_bucket_name
  force_destroy = true
  versioning {
    enabled = true
  }
}

resource "aws_s3_bucket_policy" "CloudTrailS3Bucket" {
  bucket = aws_s3_bucket.cloudtrail_bucket.id
  depends_on = [aws_s3_bucket.cloudtrail_bucket]
    policy = <<POLICY
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSCloudTrailAclCheck",
            "Effect": "Allow",
            "Principal": {
              "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:GetBucketAcl",
            "Resource": "arn:aws:s3:::${var.cloudtrail_bucket_name}"
        },
        {
            "Sid": "AWSCloudTrailWrite",
            "Effect": "Allow",
            "Principal": {
              "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::${var.cloudtrail_bucket_name}/prefix/AWSLogs/${data.aws_caller_identity.current.account_id}/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        }
    ]
}
POLICY  
}
```

**Comment by kairu97** [comment]
`aaaa`

**Comment by kairu97** [comment]
`data "aws_caller_identity" "current" {}

resource "aws_cloudwatch_log_group" "cloudtrail_logs" {
  name = "CloudTrail_Logs"
}

resource "aws_cloudtrail" "cloudtrail-ibm" {
  name                          = "tf-cloudtrail"
  s3_bucket_name                = aws_s3_bucket.cloudtrail_bucket.id
  s3_key_prefix                 = "cloudtrail"
  include_global_service_events = true
  enable_log_file_validation    = true
  is_multi_region_trail         = true
  cloud_watch_logs_group_arn = "${aws_cloudwatch_log_group.cloudtrail_logs.arn}:*"
  depends_on = [aws_s3_bucket_policy.CloudTrailS3Bucket, aws_s3_bucket.cloudtrail_bucket]
}

resource "aws_s3_bucket" "cloudtrail_bucket" {
  bucket        = var.cloudtrail_bucket_name
  force_destroy = true
  versioning {
    enabled = true
  }
}

resource "aws_s3_bucket_policy" "CloudTrailS3Bucket" {
  bucket = aws_s3_bucket.cloudtrail_bucket.id
  depends_on = [aws_s3_bucket.cloudtrail_bucket]
    policy = <<POLICY
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSCloudTrailAclCheck",
            "Effect": "Allow",
            "Principal": {
              "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:GetBucketAcl",
            "Resource": "arn:aws:s3:::${var.cloudtrail_bucket_name}"
        },
        {
            "Sid": "AWSCloudTrailWrite",
            "Effect": "Allow",
            "Principal": {
              "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::${var.cloudtrail_bucket_name}/prefix/AWSLogs/${data.aws_caller_identity.current.account_id}/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        }
    ]
}
POLICY  
}`

**Comment by dbergamin** [comment]
you have:
```
s3_key_prefix                 = "cloudtrail"
```

But the policy reads 'prefix'
```
"Resource": "arn:aws:s3:::${var.cloudtrail_bucket_name}/prefix
```

**Comment by kairu97** [comment]
> you have:
> 
> ```
> s3_key_prefix                 = "cloudtrail"
> ```
> 
> But the policy resource reads 'prefix'
> 
> ```
> "Resource": "arn:aws:s3:::${var.cloudtrail_bucket_name}/prefix
> ```
> 
> which might be causing this.

Hi, it fixed the issue, but now I am receiving another error. 

```
│ Error: Error creating CloudTrail: InvalidCloudWatchLogsRoleArnException: You must specify a role ARN as well as a log group.
│ 
│   with module.cloudtrail.aws_cloudtrail.cloudtrail,
│   on module/cloudtrail/main.tf line 131, in resource "aws_cloudtrail" "cloudtrail":
│  131: resource "aws_cloudtrail" "cloudtrail" {
│ 
```

**Comment by dbergamin** [comment]
I would guess that this field is also required:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail#cloud_watch_logs_role_arn
```
cloud_watch_logs_role_arn - (Optional) Role for the CloudWatch Logs endpoint to assume to write to a user’s log group.
```

**Comment by dbergamin** [comment]
> 

#6217 suggests the cause may be AWS side - may need to re-run the terraform.

**Comment by kairu97** [comment]
Thanks for the help @dbergamin . I have already resolved it. I forgot to add a CloudWatch Logs Role. Will close this now.
