### ISSUE TITLE
Create new resources on muti-accounts on AWS?

### ISSUE THREAD

**Issue by Pierre-Alexandre35** [hashicorp/terraform#29992]
### Current Terraform Version

`Terraform v1.0.11`

```
...
```

### Use-cases
I am building a small tool using Terraform to generate sandbox on AWS. I will be the owner of every new sandbox and each user will be added as an IAM user with appropriate rights. 

The input file looks like this: **users.auto.tfvars**

    sandboxs_manager = "pierre-alexandre.mousset"
    
    dev_team_members = [
      { name = "brian.davids", is_enabled = true }, { name = "tom.hanks", is_enabled = true }]

Which is going to create 2 different AWS accounts: 

    pierre-alexandre.mousset+brian.davids@company.com 
    pierre-alexandre.mousset+tom.hanks@company.com 

What I am now trying to achieve, is to create a simple `S3 bucket` on every new `aws_organizations_account` generated by Terraform. 

This is how I am generating AWS accounts on my Terraform:

    resource "aws_organizations_account" "this" {
      for_each  = local.all_user_names
      name      = "Dev Sandbox ${each.value}"
      email     = "${var.manager}+sbx_${each.value}@company.com"
      role_name = "Administrator"
      parent_id = var.sandbox_organizational_unit_id
    }

Is there a way to loop over every `id` generated by `aws_organizations_account` to create a `S3 bucket` on each of those newly created account?

Based on [this Github issue][1], I would need to use muti-provider which is not yet supported by Terraform and would probably look like this before to generate my `s3 buckets`:

    provider "aws" {
      for_each = local.aws_accounts
      alias = each.value.aws_account_id
      assume_role {
        role_arn    = "arn:aws:iam::${aws_organizations_account.this.id}:role/TerraformAccessRole"
      }
    }

Is there any way to deal with this?

  [1]: https://github.com/hashicorp/terraform/issues/19932

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
