### ISSUE TITLE
Issue with "Objects have changed outside of Terraform" repeat occurrences.

### ISSUE THREAD

**Issue by adoyle3ds** [hashicorp/terraform#29998]
### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.66.0
```

### Terraform Configuration Files

```terraform
resource "aws_iam_role" "data-api-ecs-role" {
  name               = "${local.service_prefix}-data-api"
  path               = "/"
  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "ec2.amazonaws.com",
          "ecs-tasks.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
  tags = {
    Product = "cppdmsdataapi"
  }
}
```

### Debug Output

https://gist.github.com/adoyle3ds/b2820f39c61a7cdb29c2ee52e6f552fb

### Expected Behavior

IF I execute `terraform plan`
AND the command returns `Note: Objects have changed outside of Terraform`
AND I then execute `terraform apply -refresh-only`
THEN the `tfstate` should be updated and no subsequent warnings should appear

### Actual Behavior

With the expected workflow referenced above - I receive continued warnings about the resource being changed outside of Terraform.

### Steps to Reproduce

1. `terraform init`
2. `terraform workspace select sandbox`
3. `terraform plan`
4. `terraform apply -refresh-only`
5. `terraform plan`

### Additional Context

Please reference this additional gist with more detailed output:

https://gist.github.com/adoyle3ds/c6e33189dff2f9926ca7e4783a57a3e6

This behavior has also been happening between my local machine and my CICD server.  The CICD server is running a wrapper script which follows the same core workflow - initialize, select workspace, plan (save plan file), apply plan file.

Some common patterns I was seeing was that in one environment (local vs server), the "warning" would show up in one place and not the other, or, would not show up locally, but then show up on the server, and then show up locally after the fact.

I did some testing to make sure that I could indeed see differences between environments before running a `-refresh-only` operation and concluded that the state file did not change and did not see any other changes from CloudTrail.

I also made a note to check the `tfstate` file in S3 to see if changes were made.  Naturally, after a `-refresh-only` operation, the state file changed.  However, the same warning would re-appear.

**Comment by adoyle3ds** [comment]
Upon some further investigation I've found an interesting thing:

Note that this was recorded after a round of `plan` and `apply -refresh-only`.

The message again during a build:
```
  # module.cppdms-sandbox.aws_iam_role.data-api-ecs-role has been changed
  ~ resource "aws_iam_role" "data-api-ecs-role" {
      ~ assume_role_policy    = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ Service = [
                              - "ec2.amazonaws.com",
                                "ecs-tasks.amazonaws.com",
                              + "ec2.amazonaws.com",
                            ]
                        }
        ...
```

In my code, the resource declares:
```
...
  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "ec2.amazonaws.com",
          "ecs-tasks.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
...
```

In the `tfplan` file:
```
"assume_role_policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"ecs-tasks.amazonaws.com\",\"ec2.amazonaws.com\"]},\"Action\":\"sts:AssumeRole\"}]}",
```

The result of `aws iam get-role`:
```
...
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Service": [
                            "ec2.amazonaws.com",
                            "ecs-tasks.amazonaws.com"
                        ]
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        },
...
```
I also attempted a `plan` operation with the `aws_iam_role` `assume_role_policy` written with `jsonencode()` instead of `<<POLICY` and it did not suggest a change, but it did produce the same warning message above.

It seems based on this information that the state file is for some reason not getting refreshed to match current state.

I am tempted to go ahead and try to `terraform rm/import` this resource to see if that fixes the issue.

**Comment by alisdair** [comment]
Thanks for reporting this issue!

I'm able to confirm this behaviour, and I can't currently find a workaround. From my local testing, it seems that no matter which order the `Service` array items have in the configuration, Terraform will detect the opposite order and show the "changes made outside of Terraform" diff.

At the moment I'm not sure if this something we can readily fix in Terraform, as I don't understand the root cause. According to the library used by the AWS provider, [the two policies in your report are equivalent](https://go.dev/play/p/Med51Nw5VsJ) regardless of the `Service` item order. Without knowing the details of how the AWS provider works, my best guess is that the AWS API is returning a policy with the `Service` items in arbitrary order, and since this is being passed through to Terraform as a JSON-encoded string, the change detection algorithm in Terraform is unable to determine that this ought to be suppressed.

**Comment by adoyle3ds** [comment]
Thanks @alisdair for your reply, I'm happy that you were able to confirm the issue.  I'll do my best to provide any additional context you might need.

**Comment by jbardin** [comment]
Hi @adoyle3ds,

What you are seeing is indeed is an issue with the AWS provider. There are a number of open bugs about various policy documents not being normalized by the provider (https://github.com/hashicorp/terraform-provider-aws/issues/19349 and https://github.com/hashicorp/terraform-provider-aws/issues/19444 for example), which will show as changes outside of Terraform. The only option we have in Terraform is to hide these changes, which we have an open enhancement request for in #28803.

Thanks!
