### ISSUE TITLE
engine value changes in tfstate after "apply", causing recreation of resources after reapply or plan

### ISSUE THREAD

**Issue by PeeKaay** [hashicorp/terraform#2999]
In my env_config.tf, for one of my  AWS RDS resource, I have set engine = "oracle-se1"
After terraform apply, tfstate changes that value to  engine = "oracle-se"
As a result, subsequent terraform plan marks it green and recreates the resources, which is not desirable.
Output from plan
-/+ aws_db_instance.kalepar-orasupport-r2
    address:                          "kalepar-xxxxxx" => "<computed>"
    allocated_storage:                "10" => "<computed>"
    apply_immediately:                "" => "<computed>"
    engine:                           "oracle-se" => "oracle-se1" (forces new resource)

I manually edited tfstate to oracle-se and then all was fine.
Version used:  Terraform v0.6.0-dev
(I don't know if this is been fixed in latest version)

**Comment by catsby** [comment]
Hey @PeeKaay – sorry for the delay here. I believe this issue has been resolved. I attempted to reproduce with this configuration:

```hcl
provider "aws" {
  region = "us-west-1"
}

resource "aws_db_instance" "tf-oracle" {
  identifier = "tf-oracle"

  allocated_storage = 10
  engine            = "oracle-se1"
  engine_version    = "11.2.0.2.v6"
  instance_class    = "db.t1.micro"
  name              = "BAZ"
  password          = "fofofofxx"
  username          = "foo"
  multi_az          = false
  apply_immediately = true

  license_model = "license-included"

  backup_retention_period = 0

  tags {
    Name = "tf-oracle"
  }
}
```

And receive no new plans after successfully applying; The engine version remains `oracle-se1`

Sorry for the delay! Please let us know if you need anything else, or are still hitting this.
