### ISSUE TITLE
Usage of a network mirror for Terraform providers

### ISSUE THREAD

**Issue by alxy** [hashicorp/terraform#29995]
**Situation**
We are currently facing a critical bug in an open-source Terraform provider. We have been able to resolve that bug for our use case (with an argueably hacky fix) and now want to bring that fixed version into our main automation system. One way to do that is using a [network mirror](https://www.terraform.io/docs/internals/provider-network-mirror-protocol.html), to load providers from a custom location. In our case, we are on Azure and thus using an Azure storage account which also supports hosting static websites.

**Problem**
After we have set up the file structure and tested the network mirror locally, everything seemed to be working. On my Windows machine, the provider is correctly beeing downloaded from the mirror and running `terraform init` showed that indeed the custom version was used:

```bash
- Installing hashicorp/azurerm v2.66.0...
- Installed hashicorp/azurerm v2.66.0 (self-signed, key ID 34365D9472D7468F) # this is a provider from the official registry
- Installing codecutout/powerbi v1.4.0...
- Installed codecutout/powerbi v1.4.0 (unauthenticated) # this is a provider from the mirror
```

On the automation environment (which is running on linux/ubuntu), I get the same output, however, when I then try to use the provider via `terraform plan/apply`, there is an issue with the permissions of the file that was just downloaded. It looks like the file is not executable:
```bash
Error: Could not load plugin


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/codecutout/powerbi" to
obtain schema: fork/exec
.terraform/providers/registry.terraform.io/codecutout/powerbi/1.4.0/linux_amd64/terraform-provider-powerbi_v1.4.0:
permission denied
```

To make in the end practical use of the provider, I needed to run the following hack:
```bash
chmod -R +x .terraform/providers
```
After running that command (of course it needs to be executed after initialization has happened), everything seems to be working as expected. The problem is that this really makes the automation pipeline look completely hacky, and as we don't really need that code for all our terraform modules, I really don't like putting it where I have currently put it

**Question**
What is the proper way to use providers from a network mirror without the additional steps. Is there something wrong in my setup? Would appreciate any help here :)

**Comment by alisdair** [comment]
When installing providers, Terraform unzips the received archive from the source directly in place. That means that the file mode of the executable in the zip archive must be executable for the provider to be valid.

I'm not sure how you're building the provider packages, but when doing so it's important to ensure that the built binaries are executable before creating the zip archive. I believe that should fix the problem you're seeing, and I don't think there's a bug in Terraform here, so I'm going to close this out.

If my suggestion doesn't solve the issue for you, please share more detailed reproduction steps (including how you built the provider package) and I'll happily reopen and investigate. Thanks!

**Comment by alxy** [comment]
Hi @alisdair and thanks for the response :)

I have built the providers on my Windows machine using `go build` for the two target architectures and have then ziped them and uploaded them. If I doanload and extract the archive locally (again on my Windows machine) and use WSL to see the file permissions, everything looks good to me:

```bash
$ ls -la
-rwxrwxrwx 1 alxy alxy 29366921 Nov 19 11:01 terraform-provider-powerbi_v1.4.0
```

I can even execute the file from WSL (suggesting to me that the file is indeed executable):
```bash
$ ./terraform-provider-powerbi_v1.4.0
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

And again, on Windows everything is working fine for me and I have built the provider exactly the same way.

**Comment by alisdair** [comment]
Huh! I'm not familiar with how WSL interacts with filesystem permissions, so my best guess still remains something to do with the zip archive incompatibility.

Are you able to upload the archive somewhere for me to take a look? Failing that, can you explain the steps you took to create the zip archive, so that I can try to reproduce the issue?

**Comment by alxy** [comment]
[terraform-provider-powerbi_1.4.0_linux_amd64.zip](https://github.com/hashicorp/terraform/files/7589849/terraform-provider-powerbi_1.4.0_linux_amd64.zip)

This is the exact archive I have also uploaded to my storage account :) Hope this helps, and again, thanks for looking into it!

**Comment by alisdair** [comment]
Thanks!

When I extract this zip file on a macOS or Linux host, the resulting provider binary is also missing the executable bit in the file mode. Looking closer at the zip, it seems that the permissions are not correctly set:

```shellsession
$ zipinfo terraform-provider-powerbi_1.4.0_linux_amd64.zip
Archive:  terraform-provider-powerbi_1.4.0_linux_amd64.zip
Zip file size: 12821190 bytes, number of entries: 1
-rw-a--     2.0 fat 29366921 bx defX 21-Nov-19 11:01 terraform-provider-powerbi_v1.4.0
1 file, 29366921 bytes uncompressed, 12820990 bytes compressed:  56.3%
```

I'd expect that entry to start with `-rwx` instead.

I'm afraid I can't suggest how to create a zip file in Windows which preserves the correct file permissions. On UNIX-like systems, the default `zip` command does so. Here's a macOS-created zip file of the provider, after running `chmod +x` to set the correct file mode:

```shellsession
$ zipinfo my-terraform-provider-powerbi_1.4.0_linux_amd64.zip
Archive:  my-terraform-provider-powerbi_1.4.0_linux_amd64.zip
Zip file size: 13123002 bytes, number of entries: 1
-rwxr-xr-x  3.0 unx 29366921 bx defN 21-Nov-19 11:01 terraform-provider-powerbi_v1.4.0
1 file, 29366921 bytes uncompressed, 13122786 bytes compressed:  55.3%
```

**Comment by alxy** [comment]
Thanks for that, it was very useful. I got the same output from WSL, as I have indeed been creating the zip file from windows. Using the approach you outlined above and creating the zip file from WSL as well indeed solves the problem and I can now use the providers as usually (without any manual involvement).

Closing this issue as it is resolved . Many thanks again!
