### ISSUE TITLE
Terraform keep destroy/recreate kusto cluster without any change on it

### ISSUE THREAD

**Issue by ekersale** [hashicorp/terraform#30006]
Hi,

We are facing an issue with terraform azurerm provider on azurerm_kusto_cluster. 

Each time we are running terraform it detects breaking change on the resource that trigger destruction and recreation even when there is absolutely no change made on it. 

The plan proposed by terraform is the following: 

```
-/+ resource "azurerm_kusto_cluster" "kusto" {
      ~ data_ingestion_uri        = "https://ingest-xxxxxx.canadacentral.kusto.windows.net" -> (known after apply)
      - enable_streaming_ingest   = false -> null
      ~ id                        = "/subscriptions/xxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxxxxx/resourceGroups/psp-prod01-kusto/providers/Microsoft.Kusto/Clusters/xxxx" -> (known after apply)
      - language_extensions       = [] -> null
        name                      = "xxxx"
      - tags                      = {} -> null
      ~ trusted_external_tenants  = [
          - "*",
        ] -> (known after apply)
      ~ uri                       = "https://xxxxxxx.canadacentral.kusto.windows.net" -> (known after apply)
      ~ zones                     = [ # forces replacement
            "1",
          - "3",
            "2",
          + "3",
        ]
        # (6 unchanged attributes hidden)

      ~ identity {
          - identity_ids = [] -> null
          ~ principal_id = "xxxxxxx-xxxxxx-xxxxx-xxxxx-xxxxxxxxxxxx" -> (known after apply)
          ~ tenant_id    = "***" -> (known after apply)
            # (1 unchanged attribute hidden)
        }


        # (2 unchanged blocks hidden)
    }
```

However we are not making any change on the zones.

We are running terraform v1.0.5 and azure rm provider v2.81.0

I am not sure it is either an issue with terraform or with the provider so i did recreate the same issue on https://github.com/hashicorp/terraform-provider-azurerm/issues/14307

If this is not the right place i will let it close the issue here.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
