### ISSUE TITLE
Add support for AWS Incident Manager

### ISSUE THREAD

**Issue by ChenLi0830** [hashicorp/terraform#30008]
### Current Terraform Version
```
Terraform v0.15.0
```

### Use-cases
Adding AWS Incident Manager Infrastructure into Terraform to capture our configuration for paging service.

https://aws.amazon.com/about-aws/whats-new/2021/05/introducing-incident-manager-aws-systems-manager/

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
