### ISSUE TITLE
Cannot ignore changes to nested attribute

### ISSUE THREAD

**Issue by axc450** [hashicorp/terraform#30027]
Hi,

I am using the following azurerm_app_service block to create an Azure App Service:
```hcl
resource "azurerm_app_service" "API" {
  name                = var.app_service
  resource_group_name = var.resource_group
  app_service_plan_id = azurerm_app_service_plan.app_service_plan.id
  site_config {
    linux_fx_version = "PYTHON|3.8"
  }
  identity {
    type = "SystemAssigned"
  }
  location            = local.location
  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}
```
Various tags get added once the app service is created - this is OK as I can ignore them in the `ignore_changes` block. However, Terraform is also throwing up the below as an issue (some info ommitted):
```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # azurerm_app_service.API has been changed
  ~ resource "azurerm_app_service" "API" {


      ~ identity {
          + identity_ids = []
            # (3 unchanged attributes hidden)
        }


      ~ site_config {
          + default_documents                    = []
            # (19 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like
to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only
```
I am unsure if this is an Azure thing or something to do with my organisation, however I cannot seem to get rid of this warning. I have tried multiple different approaches to ignoring the above such as:
```hcl
ignore_changes = [
      tags,
      identity[0].identity_ids,
      site_config[0].default_documents
    ]
```
and
```hcl
ignore_changes = all
```
however Terraform continues to flag this as an issue. What can be done to resolve this? Is this a provider bug?

**Comment by alisdair** [comment]
Pleas try running the refresh-only plan suggested by Terraform, `terraform apply -refresh-only`. This should update your Terraform state to match what the provider is returning. I was able to verify locally that this resolves the problem for the `azurerm_app_service` resource, so I'm going to close this issue for now, but if this doesn't work for you please let us know.

This is not a provider bug per se, but an artifact of how Terraform interacts with some remote services. For an explanation of why `ignore_changes` is not doing what you expect, see the last comment in issue #28803.
