### ISSUE TITLE
azurerm_key_vault issue with multiple subscriptions - subscription ID is replaced by terraform

### ISSUE THREAD

**Issue by Marco10101** [hashicorp/terraform#30026]
In the end i need to copy a secret from subscription A to subscription B.
But what happens is that terraform replaces the subscription ID with the one of subscription A when trying to get data from the keyvault in subscription B. That ends up in an error:

Error: making Read request on KeyVault "keyvault-sub-b": keyvault.VaultsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'someone@somedomain.com' with object id 'xxxxxxx' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/**subscription a id but should be subscription b id**/resourceGroups/rg-sub-b/providers/Microsoft.KeyVault/vaults/keyvault-sub-b' or the scope is invalid. If access was recently granted, please refresh your credentials."

It is no permission issue because they are in place and working. It is going wrong because terraform is somehow replacing the subscription ID of subscription B with that of subscription A when trying to get data from keyvault-sub-b.
This happens even when i hard code the subscription id's.

terraform {
  required_version = ">= 0.14.1"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.80.0"
    }
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true
}

data "azurerm_key_vault" "subscription-a" {
  name = "keyvault-sub-a"
  resource_group_name = "rg-sub-a"
}

data "azurerm_key_vault" "subscription-b" {
  name = "keyvault-sub-b"
  resource_group_name = "rg-sub-b"
}

data "azurerm_key_vault_secret" "subscription-a" {
  name         = "test-key-sub-a"
  key_vault_id =  data.azurerm_key_vault.subscription-a.id
}

data "azurerm_key_vault_secret" "subscription-b" {
  name         = "test-key-sub-b"
  key_vault_id =  data.azurerm_key_vault.subscription-b.id
}

**Comment by alisdair** [comment]
Hi @Marco10101, thanks for the report. This looks most likely to be an issue with the AzureRM provider, so please [report it on the provider repository](https://github.com/hashicorp/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Bug_Report.md).
