### ISSUE TITLE
For aws_autoscaling_group add support Lambas used as custom termination policy callouts

### ISSUE THREAD

**Issue by jjones-smug** [hashicorp/terraform#30038]
### Current Terraform Version

```
Terraform v1.0.4
```

### Use-cases

AWS now allows ASG's to call a customer provided Lambda to select instances to be terminated when scale-in, rebalance, etc... event require that a pool of instances be reduced.

### Attempted Solutions

The Terraform documentation notes that currently the support options for the `termination_policies` are a list of static AWS pre-defined policies.  As far as I can tell, there's no option to provided the name or ARN of a Lambda function.

### Proposal

I believe the current termination policy mechanism just needs an option to specific an ARN for the Lambda to be called.  Meaning expand the current list of static options and allow an ARN.

### References

None that I could find.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by jjones-smug** [comment]
Thanks!  Created a topic on the community forum to get guidance.
