### ISSUE TITLE
Feature Request : google_dialogflow_cx_agent "security_settings"

### ISSUE THREAD

**Issue by charul97** [hashicorp/terraform#30034]
Hello,

I wanted to create Dialogflow CX agent using Terraform and I am using this document https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dialogflow_cx_agent

There is an argument "security_settings" (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dialogflow_cx_agent#security_settings) and the value it takes in is the name of the SecuritySettings reference for the agent (and the reference agent should be in the same project where you are trying to create the new agent). Though it is an optional argument but since I do not want it take default settings so I want to provide it a value.

But, since my organization has more than 800 projects, so it is not feasible for us to create a reference agent in each project to provide value of "security_settings" to my new agent that I want to create using terraform. So, is there a possibility wherein instead of providing reference value to this argument, we can provide individual values to security settings parameters like redaction_strategy, redaction_scope, etc?

Can we open a feature request for the same?

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
