### ISSUE TITLE
Missing darwin_arm64 binary for the hashicorp/template provider (Apple Silicon, M1)

### ISSUE THREAD

**Issue by larstobi** [hashicorp/terraform#30055]
If I use the `darwin_arm64` binary of terraform, then I cannot run `terraform init` if I use the `template_file` provider.

(A quick `terraform -version` will reveal if you run amd64 on Rosetta or on arm64.)

The releases show that the `darwin_arm64` is in fact not published:

* https://releases.hashicorp.com/terraform-provider-template/2.2.0/

I have checked out the source code for this and built it on my M1 macbook, and it compiles and runs without issue, so it should be a quick fix for Hashicorp to publish this binary for the same 2.2.0 version.

**Comment by jbardin** [comment]
Hi @larstobi,

The [template provider](https://github.com/hashicorp/terraform-provider-template) was deprecated before `darwin_arm64` providers were released, and the repository is now archived and read-only. The functionality from this provider is now handled by the `templatefile` function in Terraform. 

Thanks!

**Comment by larstobi** [comment]
@jbardin 
Thanks. I was able to migrate most of our uses of `template_file` to `templatefile()`, however some uses are not possible to migrate, like when using the output of a resource as an input to `template_file`:

```hcl
data "aws_s3_bucket_object" "example" {
  bucket = "example-bucket-name"
  key    = "example.yaml"
}

data "template_file" "example" {
  template = data.aws_s3_bucket_object.example.body
  vars = {
    foo  = "bar"
  }
}

```

Since the `templatefile()` function doesn't support string input, but requires a file name, it can't be converted. Is this use case supported by a different function?

If I can't make it work by other means, I can see there is a fork of your old template provider repo that has published a binary for `darwin_arm64` here: https://github.com/gxben/terraform-provider-template/tree/v2.2.0-m1

**Comment by larstobi** [comment]
https://github.com/hashicorp/terraform/issues/26838 

It seems that the only way forward is to use a self-compiled `darwin_arm64` provider or a the third party one from gxben, as the above use case is impossible to achieve without using a deprecated provider running on terraform with Intel emulation.
