### ISSUE TITLE
Terraform Test error is unclear when you hit service quota during build phase

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#30066]
### Terraform Version

```
$ tf -version
Terraform v1.0.8
on darwin_amd64
```

### Terraform Configuration Files

https://github.com/aws-ia/terraform-aws-label/tree/terraform-test/tests/examples_formatted_tags

### Debug Output

https://gist.github.com/drewmullen/9ae7fe11f8f67b4d11788914ad305bc4

### Expected Behavior

Error should be more relevant to the cause

### Actual Behavior

```
│ Error: Failed to clean up after tests
│
│ Due to errors during destroy, test suite "examples_formatted_tags" has left behind an object for aws_vpc.test_aws_to_aws. You will
│ need to delete this object manually in the remote system, or else it may have an ongoing cost.
```

### Steps to Reproduce

1. run create-vpc till service quota is filled:
```
$ aws ec2 create-vpc --cidr-block "10.0.0.0/16"

An error occurred (VpcLimitExceeded) when calling the CreateVpc operation: The maximum number of VPCs has been reached.
```

2. `terraform test` in root

**Comment by apparentlymart** [comment]
[(some earlier discussion about this in the Community Forum, just to keep this all connected)](https://discuss.hashicorp.com/t/terraform-test-error-is-unclear-when-you-hit-service-quota-during-build-phase/32620/3)

**Comment by drewmullen** [comment]
I ran into another instance of this error but instead of the error above, tests are just passing: here is the output from my debug log"
```
[ERROR] vertex "module.no_ipam_vpc_example.aws_vpc.this[0]" error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
	status code: 400, request id: bd4dbc73-45e4-4bb2-aab8-d6e06e1e0c65
```

**Comment by liamcervante** [comment]
I think this has been fixed in the final release of the `terraform test` command. We now expose the same diagnostics that the plan and apply commands would, so test should be at parity with the rest of Terraform now.
