### ISSUE TITLE
key_vault { purge_soft_delete_on_destroy = false } breaks soft-deleted key recovery in azurerm

### ISSUE THREAD

**Issue by db0** [hashicorp/terraform#30068]
When trying to create a VM disk encryption sets in azure using terraform, I'm running into a situation where no matter my approach, terraform will fail in some instances.

Specifically, if I delete an encryption key from an azure keyvault and then later on try to recreate one with the same name, if the following is set

```
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}
```
then terraform will always fail with the following:

```
azurerm_key_vault_key.disk_encryption[5]: Creating...
╷
│ Error: Creating Key: keyvault.BaseClient#CreateKey: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Key vmname-custom-disk-encryption is currently in a deleted but recoverable state, and its name cannot be reused; in this state, the key can only be recovered or purged." InnerError={"code":"ObjectIsDeletedButRecoverable"}
│ 
│   with azurerm_key_vault_key.disk_encryption[5],
│   on encryption.tf line 12, in resource "azurerm_key_vault_key" "disk_encryption":
│   12: resource "azurerm_key_vault_key" "disk_encryption" {
```

If However, I have the following provider

```
provider "azurerm" {
  features {}
}
```

Then the key will be recovered and reused automatically.

Unfortunately, if I do not put `purge_soft_delete_on_destroy = false`, then terraform will instead fail during `azurerm_key_vault_key` resource destroy with this error

```
│ Error: purging of Key "vmname-custom-disk-encryption" (Key Vault "https://keyvaultname.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after 
the retention period has passed.\r\nVault: keyvaultname;location=westeurope"
```

which is expected. However this set of behaviours, ensures that a terraform destroy/create operation will fail no matter what.

### Terraform Version

```
1.0.11
```

### Expected Behavior

Azure keyvault soft-deleted key should be automatically recovered when discovered, while `purge_soft_delete_on_destroy = false`

### Actual Behavior

Terraform fails when it tries to create a key with the same name as a soft-deleted key when `purge_soft_delete_on_destroy = false`, but succeeds when `purge_soft_delete_on_destroy = true`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
