### ISSUE TITLE
Azure synapse {managed_virtual_network_enabled = true} does not correctly set up virtual network

### ISSUE THREAD

**Issue by uceimmp** [hashicorp/terraform#30069]
### Terraform Version

```
1.1.0
```

### Terraform Configuration Files

```terraform
resource "azurerm_synapse_workspace" "example" {
  name                                                      = "example"
  resource_group_name                                       = azurerm_resource_group.warehouse_rg.name
  location                                                  = var.location
  storage_data_lake_gen2_filesystem_id                      = azurerm_storage_data_lake_gen2_filesystem.warehouse_filesystem.id
  sql_administrator_login                                   = "sqladminuser"
  sql_administrator_login_password                          = random_password.synapse-sql-password.result
  managed_virtual_network_enabled                           = true

  aad_admin {
    login     = "AD Admin"
    object_id = "var.object_id"
    tenant_id = var.tenant_id
  }

  azure_devops_repo {
    account_name    = "example"
    branch_name     = var.git_config["branch_name"]
    project_name    = "Example"
    repository_name = "example"
    root_folder     = "/"
  }
}
```

### Additional Context

Are there anything atypical about your situation that we should know? For example: is Terraform running in a wrapper script or in a CI system? Are you passing any unusual command line options or environment variables to opt-in to non-default behavior?
-->

### References
<img width="332" alt="Screenshot 2021-12-02 at 13 56 09" src="https://user-images.githubusercontent.com/32641643/144436539-fb272a6b-8935-42da-918f-e203afb130a7.png">

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
