### ISSUE TITLE
Terraform doesn't see environmental variables 

### ISSUE THREAD

**Issue by romanvbabenko** [hashicorp/terraform#3006]
Documentation sys that Terraform maps environments vars like TF_VAR_varname into variable "varname", so 

~/.bashrc

    TF_VAR_foo="bar"

main.tf
```
variable "foo" {}
output "foo" {
  value = "${var.foo}"
}
```

terraform plan gives me
```
errors:

  * 1 error(s) occurred:

* Required variable not set: foo
```

I expected than described in manual rules work, but in fact they are not. How so?

**Comment by dwb** [comment]
You haven't exported it to any child process's environment. Try

`export TF_VAR_foo="bar"`

or run terraform like `TF_VAR_foo="bar" terraform plan`

**Comment by catsby** [comment]
Thanks for the answer there @dwb – @romanvbabenko please let us know if that doesn't address your issue. The docs illustrate this as @dwb mentioned:

    $ TF_VAR_image=foo terraform apply

- https://terraform.io/docs/configuration/variables.html
