### ISSUE TITLE
Failing to upgrade Aurora Cluster for Postgres database from version 11.9 to 11.12

### ISSUE THREAD

**Issue by rawashdeha** [hashicorp/terraform#30070]
Terraform Version  = v0.14.6
Provider = AWS
Using TFE 
There error is during Apply:

Plan Result
***********************
Terraform will perform the following actions:

  # module.aurora_01_cluster.aws_rds_cluster.this will be updated in-place
  ~ resource "aws_rds_cluster" "this" {
      ~ engine_version                      = "11.9" -> "11.12"
        id                                  = "snaurorapsgcluster"
        tags                                = {

            "Core"            = "true"
            "Description"     = "Aurora Cluster"
  
        }
        # (34 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # module.aurora_01_cluster_instance_reader.aws_rds_cluster_instance.default will be updated in-place
  ~ resource "aws_rds_cluster_instance" "default" {
      ~ engine_version                        = "11.9" -> "11.12"
        id                                    = "snaurorapsginstance"
      ~ tags                                  = {
          + "Environment"     = "Test"
            # (10 unchanged elements hidden)
        }
      ~ tags_all                              = {
          + "Environment"     = "Test"
            # (10 unchanged elements hidden)
        }
        # (28 unchanged attributes hidden)
    }

  # module.aurora_01_cluster_instance_writer.aws_rds_cluster_instance.default will be updated in-place
  ~ resource "aws_rds_cluster_instance" "default" {
      ~ engine_version                        = "11.9" -> "11.12"
        id                                    = "snaurorapsginstance"
      ~ tags                                  = {
          + "Environment"     = "Test"
            # (10 unchanged elements hidden)
        }
      ~ tags_all                              = {
          + "Environment"     = "Test"
            # (10 unchanged elements hidden)
        }
        # (28 unchanged attributes hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.
****************************************************

Apply result:
*********************
Terraform v0.14.6
Initializing plugins and modules...
[0m[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Modifying... [id=snaurorapsgcluster-ti4][0m[0m
[0m[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Still modifying... [id=snaurorapsgcluster-ti4, 10s elapsed][0m[0m
[0m[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Still modifying... [id=snaurorapsgcluster-ti4, 20s elapsed][0m[0m
[0m[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Still modifying... [id=snaurorapsgcluster-ti4, 30s elapsed][0m[0m
[0m[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Modifications complete after 31s [id=snaurorapsgcluster-ti4][0m[0m
[31m
[1m[31mError: [0m[0m[1mProvider produced inconsistent final plan[0m

[0mWhen expanding the plan for
module.aurora_01_cluster_instance_writer.aws_rds_cluster_instance.default to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.engine_version: was cty.StringVal("11.12"), but now cty.StringVal("11.9").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
[0m[0m
[31m
[1m[31mError: [0m[0m[1mProvider produced inconsistent final plan[0m

[0mWhen expanding the plan for
module.aurora_01_cluster_instance_reader.aws_rds_cluster_instance.default to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.engine_version: was cty.StringVal("11.12"), but now cty.StringVal("11.9").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
[0m[0m
************************************************************

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
