### ISSUE TITLE
Support Amazon S3 Object Ownership（Bucket owner enforced）

### ISSUE THREAD

**Issue by yusuke-takikawa-s** [hashicorp/terraform#30077]
### Current Terraform Version

```
1.0.0.
```

### Use-cases

I want to set the following new features (Amazon S3 Object Ownership) with aws provider.
https://aws.amazon.com/jp/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/

### Attempted Solutions

```
resource "aws_s3_bucket" "example" {
  bucket = "example"
}

resource "aws_s3_bucket_ownership_controls" "example" {
  bucket = aws_s3_bucket.example.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

```

### Proposal

I want to make sure that the settings are applied according to the contents described in "Attempted Solutions" above.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
