### ISSUE TITLE
Clear up language about download types for Apple

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#30086]
Just a small syntactical problem on the main downloads page for Apple (this page https://www.terraform.io/downloads.html) which causes assumptions and suboptimal user behaviour.

The main download offers two choices - "64 bit" and "arm64". But arm64 is also 64-bit, and I am seeing some users getting confused, thinking they should download the "64-bit" version on their Apple M1 Silicons.

It would be better to label the downloads as "x86_64" and "arm64" -- or "amd64" and "arm64", to stop the confusion about whether it is appropriate to download and use "64-bit" for M1. It's always a bad idea due to emulation, emulator crashes, and resulting poor speed performance compared to natively compiled version. 

Thanks!

**Comment by crw** [comment]
@gtmtech Thanks for the report! I agree that the wording is a bit confusing, it clearly comes from pre-`arm64` days.

**Comment by crw** [comment]
I looked into this a bit, those docs are auto-generated using a system that is going to be decommissioned soon. I am going to hold this issue open to check what the new system does when it comes online.

**Comment by laurapacilio** [comment]
@crw Thank you! As soon as we investigate the new system, I can make changes to the docs if necessary - standing by!

**Comment by crw** [comment]
After some internal debate, the team decided to move to the golang `GOARCH` targets as what will be published to reference release target architectures. The idea is that those arch target names are in the filenames, so we want the thing you click on the website to be consistent with the filename you download. In practical terms that means the following:

`32-bit` -> `386`
`64-bit` -> `amd64`

Personally I find the idea of downloading a 386 binary to be a bit silly, but we are hoping that people who are going through the trouble of finding the right architecture target to download will have a sense of what that means in the golang universe. And it solves the original problem of clearly differentiating x86 targets from ARM targets.

**Comment by crw** [comment]
Hi @gtmtech, check out https://www.terraform.io/downloads -- this should meet your requirements! Thanks!
