### ISSUE TITLE
aws_ecs_task_definition recreates resource unless container_definitions healthCheck defaults are specified explicitly

### ISSUE THREAD

**Issue by hertzsprung** [hashicorp/terraform#30081]
### Terraform Version

```
Terraform v1.0.11
```

### Terraform Configuration Files

```terraform
resource "aws_ecs_task_definition" "mytaskdefinition" {
  family = "myfamily"
  container_definitions = jsonencode([
    {
      "name" : "mytask",
      "image" : "myimage:latest",
      "portMappings" : [{
          "containerPort" : 8080
      }],
      "healthCheck": {
        "command": ["CMD-SHELL", "curl -f http://localhost:8000/test || exit 1"],             
        # defaults must be specified else terraform thinks the resource has changed
        //"interval": 30,
        //"retries": 3,
        //"timeout": 5
      }
    }
  ])
  requires_compatibilities = ["FARGATE"]
  cpu                      = 256
  memory                   = 512
  network_mode             = "awsvpc"
} 
```

### Expected Behavior
Subsequent invocations of `terraform apply` report no updates.

### Actual Behavior
`aws_ecs_task_definition.mytaskdefinition` must be replaced because healthCheck interval, retries and timeout are null.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform apply`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by hertzsprung** [comment]
My mistake.  I've raised a [bug against terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws/issues/22060).
