### ISSUE TITLE
Suggestion `JsonBody` parameters in WAFv2

### ISSUE THREAD

**Issue by woodonggyu** [hashicorp/terraform#30085]
### Current Terraform Version

```
v1.0.11
```

### Attempted Solutions
* AWS WAFv2

### Proposal

When i tested, I couldn't find parameter of `JsonBody`.
Do you have any plans to support these features? or already supported?

### References
* https://docs.aws.amazon.com/waf/latest/APIReference/API_FieldToMatch.html

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
