### ISSUE TITLE
Disable key and shared access signature authentication of Event Grid Topic

### ISSUE THREAD

**Issue by bacman0304** [hashicorp/terraform#30091]
Hi there,

Can you add this functionality? Is it possible?

regards

https://docs.microsoft.com/en-us/azure/event-grid/authenticate-with-active-directory?WT.mc_id=Portal-Microsoft_Azure_EventGrid#disable-key-and-shared-access-signature-authentication

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
