### ISSUE TITLE
Unable to create Azure resource lock via Terraform

### ISSUE THREAD

**Issue by i89825** [hashicorp/terraform#30108]
Hi there,

We started receiving the below error while creating Azure resource lock via terraform. The issue started from Friday (03 Dec 2021), prior to this it was working fine. We upgraded the terraform version to the latest (1.0.11) but still same error:

_azurerm_management_lock.rglock: Creating...
╷
│ Error: parsing "resource-group-level": parsing scope prefix: unable to find the scope prefix from the value "resource-group-level" with the regex "^((.){1,})/providers/Microsoft.Authorization/locks/(.){1,}"_

While configuring lock for any Azure resource via Terraform we get this error. Strange thing is that it works fine via azure cli or directly via portal.

### Terraform Version

```
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v2.88.1
```

### Terraform Configuration Files

```
Main.tf
-------
data "azurerm_resource_group" "example" {
  name     = "testing-terraform-01"
}

resource "azurerm_management_lock" "rglock" {
  name       = "resource-group-level"
  scope      = data.azurerm_resource_group.example.id
  lock_level = "ReadOnly"
  notes      = "This Resource Group is Read-Only"
}
```

### Debug Output
[terraform.txt](https://github.com/hashicorp/terraform/files/7675999/terraform.txt)

### Expected Behavior
Terraform should have create Read-only lock for the Azure resource group. 

### Actual Behavior
We are getting the below error and resource is created with status "tainted".
Attached it the statefile for reference. 
[terraform copy.tfstate.txt](https://github.com/hashicorp/terraform/files/7676036/terraform.copy.tfstate.txt)

### Steps to Reproduce
Use the terraform module for Azure resource lock to create lock.
```
Main.tf
-------
data "azurerm_resource_group" "example" {
  name     = "testing-terraform-01"
}

resource "azurerm_management_lock" "rglock" {
  name       = "resource-group-level"
  scope      = data.azurerm_resource_group.example.id
  lock_level = "ReadOnly"
  notes      = "This Resource Group is Read-Only"
}
```

### Additional Context
NA

### References
NA

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
