### ISSUE TITLE
Changing instance_type for "aws_eks_node_group" forces replacement

### ISSUE THREAD

**Issue by DanielHajduk2-TomTom** [hashicorp/terraform#30109]
### Terraform Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.11.3
+ provider registry.terraform.io/hashicorp/aws v3.61.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/hashicorp/vault v3.0.1

```

### Terraform Configuration Files

```terraform
resource "aws_eks_node_group" "node_group" {
  count           = local.availability_zones
  cluster_name    = var.cluster_name
  node_group_name = random_pet.node_groups_pets[count.index].id
  node_role_arn   = local.node_iam_role_arn
  subnet_ids      = flatten([
    local.private_subnet_ids[count.index]])
  instance_types  = local.instance_types
...
}
```

### Debug Output
N/A

### Expected Behavior
Instance Types will be modified on the fly the same way I can do that when modifying ASG manually via console..

### Actual Behavior
Instance Type changes force recreation of whole node_group.

### Steps to Reproduce
terraform init
terraform plan

### Additional Context
N/A

### References
Didn't find any.

**Comment by DanielHajduk2-TomTom** [comment]
If someone gives me a good reason why I cannot reflect the behaviour of console using the same API underneath - Ill close this ticket and wear a dokney hat ;)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
