### ISSUE TITLE
project argument for all CloudStack resources

### ISSUE THREAD

**Issue by hany** [hashicorp/terraform#3010]
Hi, I'm making use of a CloudStack provider that requires the `projectID` query parameter to be passed to all CloudStack API calls. I see that some resources like `cloudstack_instance` accept a `project` argument, while others, such as `cloudstack_vpc`, do not. Are there any options for this?

**Comment by hany** [comment]
It appears that the underlying xanzy/go-cloudstack repo has support for these options:

https://github.com/xanzy/go-cloudstack/blob/master/cloudstack44/NetworkService.go#L45-L47
https://github.com/xanzy/go-cloudstack/blob/master/cloudstack44/VPCService.go#L58-L60

Sounds like it should be fairly simple to add?

**Comment by hany** [comment]
I've attempted to patch this here: vmfarms/terraform@228da7cf270263bae4969f7b071d26c099659826

Let me know if you'd like me to submit a formal PR.

**Comment by hany** [comment]
Here is another update:

vmfarms/terraform@078b16b20e30d09b60c36e8799ada42c0d52c22a

I'll look into making a PR.

**Comment by svanharmelen** [comment]
@hany the PR referenced here is merged already, so are you OK with closing this one?

**Comment by hany** [comment]
@svanharmelen technically the `project` parameter should be added to all resources. The PR submitted only adds it to a subset of resources. However, I can proceed to add the parameter as I encounter more use cases, and submit new PRs at that time.

I will close this out.
