### ISSUE TITLE
docker_container command options fail if they contain a space

### ISSUE THREAD

**Issue by rvm2015** [hashicorp/terraform#3011]
Given an image called testimage which is a centos:6 image that has just had "yum install httpd install -y" run on it
Given the following tf file:

    provider "docker" {
      host = "tcp://coreos.example.org:4243/"
    }
    
    resource "docker_container" "foo" {
      image = "${docker_image.testimage.latest}"
      name = "foo"
      command = [ "/usr/sbin/apachectl -DFOREGROUND" ]
      ports {
        internal = 80
        external = 80
      }
    }

terraform apply fails with the following error:

    docker_image.testimage: Refreshing state... (ID: b493020f0ed98cf9a38e36e7b1cd78afcec6755efdbb3e0f25483229ba18396btestimage:latest)
    docker_container.foo: Refreshing state... (ID: 2c3581b373afb85d199f71312e174ed5a2aa1f94007dfdb81126db0af235e534)
    docker_container.foo: Creating...
      bridge:                    "" => "<computed>"
      command.#:                 "" => "1"
      command.0:                 "" => "/usr/sbin/apachectl -DFOREGROUND"
      gateway:                   "" => "<computed>"
      image:                     "" => "b493020f0ed98cf9a38e36e7b1cd78afcec6755efdbb3e0f25483229ba18396b"
      ip_address:                "" => "<computed>"
      ip_prefix_length:          "" => "<computed>"
      must_run:                  "" => "1"
      name:                      "" => "foo"
      ports.#:                   "" => "1"
      ports.1516735375.external: "" => "80"
      ports.1516735375.internal: "" => "80"
      ports.1516735375.ip:       "" => ""
      ports.1516735375.protocol: "" => "tcp"
    Error applying plan:
    
    1 error(s) occurred:
    
    * docker_container.foo: Unable to start container: API error (404): Cannot start container c5f8b81c948a213a856f968870b64bdf7a04de380177955bfb2242667ca08242: [8] System error: exec: "/usr/sbin/apachectl -DFOREGROUND": stat /usr/sbin/apachectl -DFOREGROUND: no such file or directory

If I wrap the same command in a start.sh shell script, seems to only happen if the command has a space in it.

**Comment by apparentlymart** [comment]
I don't know Docker or this provider very well, but my guess would be that it is treating that value as the name of an executable to exec, rather than passing it to a shell to handle, and thus it fails trying to find a file named after that whole string.

Again I am totally guessing here but I would try setting that array so that -DFOREGROUND is a separate second array element:

```js
command = ["/usr/sbin/apachectl", "-DFOREGROUND"]
```

**Comment by rvm2015** [comment]
I will give this a try and report back.

**Comment by doomsbuster** [comment]
I am trying to start apache in a similar fashion in my shell script, i get error `exec: /usr/sbin/apachectl -DFOREGROUND: not found` when i run this script from sh prompt. When i run it outside the shell script it works just fine. I am doing all this in a docker container.

```
#!/bin/sh

set -e

if [ -z "$1" ]
then
  exec "/usr/sbin/apachectl -D FOREGROUND"
else
  exec "$@"
fi```

**Comment by doomsbuster** [comment]
I think i answered my own question - i have double quotes around the apachectl instruction after exec, which resulted in the executable not found error - `exec "/usr/sbin/apachectl -D FOREGROUND". Here is my script that works:
```

#!/bin/sh

set -e

if [ -z "$1" ]
then
  exec /usr/sbin/apachectl -D FOREGROUND
else
  exec "$@"
fi```
