### ISSUE TITLE
context deadline exceeded with key vault and private endpoint

### ISSUE THREAD

**Issue by chlsmith** [hashicorp/terraform#30137]
I'm quoting this because I don't see where there was a solution at that time, and I'm having the same issue now.   Any progress made on it?

https://github.com/hashicorp/terraform-provider-azurerm/issues/10501

If I run 

```
az login --allow-no-subscriptions --service-principal --username $DEPLOY_CLIENT_ID --password $DEPLOY_CLIENT_SECRET --tenant $DEPLOY_TENANT_ID
az rest --method GET --uri "https://xxxx.vault.azure.net/certificates/contacts?api-version=7.1" --resource "https://vault.azure.net"
```
immediately before my TF apply, **I get a valid response**. The private endpoint isn't blocking access to the KeyVault.

If I deploy the KeyVault with ARM (hence removing the need to read the contact), I get the same issue with certificate read, but not the contact read.

_Originally posted by @marrobi in https://github.com/hashicorp/terraform-provider-azurerm/issues/10501#issuecomment-788921731_

**Comment by chlsmith** [comment]
Note that I cannot run the command above in my own instance (restrictions on my account), but I'm seeing the same issue as what discussed in that thread.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
