### ISSUE TITLE
Feature proposal: Make it easier to delete dangling resources on terraform test failures

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform#30143]
When `terraform test` fails it leaves behind dangling resources. This can be useful for practitioners to investigate why the test failed in the first place but its also frustrating to have to delete entire stacks that were left behind.

Proposed ideas:

1. `terraform test` can have a flag to delete despite test failure
2. test can create a `tfstate` file of the remaining resources on failures that practitioners can then run `destroy` on

**Comment by liamcervante** [comment]
We're tracking a similar issue for the finalised `test` command in https://github.com/hashicorp/terraform/issues/33786. I will close this issue as obsolete, and any discussion can happen in the new thread. Thanks!
