### ISSUE TITLE
Inappropriate value for attribute "security_rule" when using the list of objects syntax for security_rule

### ISSUE THREAD

**Issue by dumblerod** [hashicorp/terraform#30145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.12.0
+ provider registry.terraform.io/hashicorp/azurerm v2.88.1
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)
* `azurerm_network_security_group`

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "mgmtsubnet-nsg" {
  name                = "mgmtsubnet-nsg"
  location            = azurerm_resource_group.baserg.location
  resource_group_name = azurerm_resource_group.baserg.name

  security_rule = [
    {
      name                       = "mgmtrdpaccess"
      description                = "Allow RDP(3389) inbound from specified IPs"
      priority                   = 100
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_port_range          = "*"
      destination_port_range     = "3389"
      source_address_prefixes    = var.win10allowedips
      destination_address_prefix = "*"
    },
    {
      name                       = "denyallothertraffic"
      description                = "Deny all inbound traffic not already allowed"
      priority                   = 200
      direction                  = "Inbound"
      access                     = "Deny"
      protocol                   = "Tcp"
      source_port_range          = "*"
      destination_port_range     = "*"
      source_address_prefix      = "*"
      destination_address_prefix = "*"
    }
  ]
}
```

### Expected Behaviour

The security group should have been created with the two rules. In order to get the security group to create it with two rules, you have to create two security_rule objects and add appropriate values to each. But the documentation calls this attribute a list of objects. After some reading in docs, my format is not recommended, but it should be allowed. In either case, it seems something should be updated to make this more clear. Maybe an example in the doc with more than one rule?  Setting my rule up like this works for those who stumble upon this in the future:
```hcl
resource "azurerm_network_security_group" "mgmtsubnet-nsg" {
  name                = "mgmtsubnet-nsg"
  location            = azurerm_resource_group.baserg.location
  resource_group_name = azurerm_resource_group.baserg.name

  security_rule {
    name                       = "mgmtrdpaccess"
    description                = "Allow RDP(3389) inbound from specified IPs"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "3389"
    source_address_prefixes    = var.win10allowedips
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "denyallothertraffic"
    description                = "Deny all inbound traffic not already allowed"
    priority                   = 200
    direction                  = "Inbound"
    access                     = "Deny"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}
```

### Actual Behaviour

I received an error message about missing values:
```
Error: Incorrect attribute value type
│
│   on network.tf line 202, in resource "azurerm_network_security_group" "mgmtsubnet-nsg":
│  202:   security_rule = [
│  203:     {
│  204:       name                       = "mgmtrdpaccess"
│  205:       description                = "Allow RDP(3389) inbound from specified IPs"
│  206:       priority                   = 100
│  207:       direction                  = "Inbound"
│  208:       access                     = "Allow"
│  209:       protocol                   = "Tcp"
│  210:       source_port_range          = "*"
│  211:       destination_port_range     = "3389"
│  212:       source_address_prefixes    = var.win10allowedips
│  213:       destination_address_prefix = "*"
│  214:     },
│  215:     {
│  216:       name                       = "denyallothertraffic"
│  217:       description                = "Deny all inbound traffic not already allowed"
│  218:       priority                   = 200
│  219:       direction                  = "Inbound"
│  220:       access                     = "Deny"
│  221:       protocol                   = "Tcp"
│  222:       source_port_range          = "*"
│  223:       destination_port_range     = "*"
│  224:       source_address_prefix    = "*"
│  225:       destination_address_prefix = "*"
│  226:     }
│  227:   ]
│     ├────────────────
│     │ var.win10allowedips will be known only after apply
│
│ Inappropriate value for attribute "security_rule": element 0: attributes "destination_address_prefixes", "destination_application_security_group_ids", "destination_port_ranges", "source_address_prefix",    
│ "source_application_security_group_ids", and "source_port_ranges" are required.
```

### Steps to Reproduce

1. `terraform apply`

### References

* hashicorp/terraform-provider-azurerm#12329
* hashicorp/terraform-provider-azurerm#8702

**Comment by jbardin** [comment]
Hi @dumblerod,

Sorry about the confusing error here. The `ConfigModeAttr` workaround used by some providers allows using attribute syntax, however the legacy SDK cannot create optional object attributes, meaning all fields must be supplied when assigning an object value in order to satisfy the type constraints.

Since assigning `null` to an attribute is equivalent to leaving it unassigned, you can fill in the missing attributes with `null` to complete the object type:

```
  security_rule {
    name                       = "mgmtrdpaccess"
    description                = "Allow RDP(3389) inbound from specified IPs"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "3389"
    source_address_prefixes    = var.win10allowedips
    destination_address_prefix = "*"
    destination_address_prefixes = null
    source_application_security_group_ids = null
    source_port_ranges = null
  }
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by dumblerod** [comment]
Not the answer I wanted, but certainly AN answer. Shouldn't the module who is calling this take care of passing in nulls if no values are passed in? It's not very often in Terraform when an attribute is marked as optional in the documentation that it is actually required. Does this need to go back to @tombuildsstuff? I would hope either the documentation is updated in or the code calling Terraform core is updated to pass in nulls if no attributes are set.

**Comment by jbardin** [comment]
Hi @dumblerod,

Terraform v1.0 includes the ability to have optional object attributes, but unfortunately that ability is only compatible with a new SDK, and upgrading all providers to the new SDK will take some time to accomplish. The ability to omit null values is done via the block syntax which you noted. The attribute syntax can be reserved for setting a single empty container value, or when a "for expression" is required to expand some collections of values.
