### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by Andrew-J-MacKenzie** [hashicorp/terraform#30157]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior
Terraform returns with success

### Actual Behavior
No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like
to update the Terraform state to match, create and apply a refresh-only plan.
Failed running command "cd '/terraform' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 2)
Output: panic: value is marked, so must be unmarked first

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.771064786.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

### Steps to Reproduce
1. `terraform apply`

Terraform v1.0.1
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
[0m[1mmodule.payeduc-fls.random_id.server: Refreshing state... [id=vzyKmfjYngo][0m
[0m[1mazurerm_resource_group.static_resource_group: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigitalcloud-uat-rg-staticstite][0m
[0m[1mmodule.payeduc-fls.azurerm_app_service_plan.AED-payeduc-fls: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-payeduc-fls/providers/Microsoft.Web/serverfarms/payeduc-fls-account][0m
[0m[1mmodule.strapi.azurerm_resource_group.AED-strapi-rg: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-two][0m
[0m[1mmodule.payeduc-fls.azurerm_resource_group.AED-payeduc-fls: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-payeduc-fls][0m
[0m[1mazurerm_resource_group.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice][0m
[0m[1mazurerm_resource_group.AED-FLS: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-payeduc-fls][0m
[0m[1mmodule.strapi.azurerm_resource_group.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-one][0m
[0m[1mmodule.payeduc-fls.azurerm_storage_account.AED-payeduc-fls: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-payeduc-fls/providers/Microsoft.Storage/storageAccounts/payeducflsstorageuat][0m
[0m[1mazurerm_resource_group.AED-keyvault: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/GOA-IT-AEDigitalCloud-rg-TOR][0m
[0m[1mmodule.strapi.azurerm_data_protection_backup_vault.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-two/providers/Microsoft.DataProtection/backupVaults/aed-strapi-recovery][0m
[0m[1mmodule.strapi.azurerm_postgresql_server.AED-strapi-srv: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-two/providers/Microsoft.DBforPostgreSQL/servers/aed-uat-psql-strapi][0m
[0m[1mmodule.strapi.azurerm_recovery_services_vault.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-one/providers/Microsoft.RecoveryServices/vaults/aedigital-uat-postgres-strapi-recovery-vault][0m
[0m[1mazurerm_storage_account.staticwebsitestorage_account: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigitalcloud-uat-rg-staticstite/providers/Microsoft.Storage/storageAccounts/staticwebstorageuat][0m
[0m[1mmodule.strapi.azurerm_storage_account.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-one/providers/Microsoft.Storage/storageAccounts/strapistorageaccountuat][0m
[0m[1mmodule.strapi.azurerm_postgresql_server.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-one/providers/Microsoft.DBforPostgreSQL/servers/aedigital-uat-postgres-strapi][0m
[0m[1mazurerm_postgresql_server.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.DBforPostgreSQL/servers/psql-shared-application-server-uat][0m
[0m[1mazurerm_application_insights.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.Insights/components/microservice-appinsights][0m
[0m[1mazurerm_app_service_plan.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.Web/serverfarms/goa-cc-aedigital-uat-rg-microservice][0m
[0m[1mazurerm_key_vault.AED-keyvault: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/GOA-IT-AEDigitalCloud-rg-TOR/providers/Microsoft.KeyVault/vaults/aedigital-uat-kv][0m
[0m[1mmodule.strapi.azurerm_postgresql_database.AED-strapi-db: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-two/providers/Microsoft.DBforPostgreSQL/servers/aed-uat-psql-strapi/databases/aed-pg-strapi][0m
[0m[1mmodule.strapi.azurerm_postgresql_database.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-one/providers/Microsoft.DBforPostgreSQL/servers/aedigital-uat-postgres-strapi/databases/aedigital-postgres-strapi][0m
[0m[1mmodule.payeduc-fls.azurerm_app_service.AED-payeduc-fls: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-payeduc-fls/providers/Microsoft.Web/sites/payeduc-fls-uat][0m
[0m[1mmodule.strapi.azurerm_data_protection_backup_policy_postgresql.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-two/providers/Microsoft.DataProtection/backupVaults/aed-strapi-recovery/backupPolicies/aed-strapi-recovery-policy][0m
[0m[1mazurerm_postgresql_firewall_rule.AED-microservice-rule2: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.DBforPostgreSQL/servers/psql-shared-application-server-uat/firewallRules/AllowAll][0m
[0m[1mazurerm_postgresql_firewall_rule.AED-microservice-rule1: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.DBforPostgreSQL/servers/psql-shared-application-server-uat/firewallRules/][0m
[0m[1mazurerm_postgresql_firewall_rule.AED-microservice-rule3: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.DBforPostgreSQL/servers/psql-shared-application-server-uat/firewallRules/AllowAccessToAzureServices][0m
[0m[1mmodule.microservice["AED-Address-uat"].azurerm_postgresql_database.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.DBforPostgreSQL/servers/psql-shared-application-server-uat/databases/AED-Address-uat][0m
[0m[1mmodule.microservice["AED-Person-uat"].azurerm_postgresql_database.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.DBforPostgreSQL/servers/psql-shared-application-server-uat/databases/AED-Person-uat][0m
[0m[1mmodule.microservice["AED-Provider-uat"].azurerm_postgresql_database.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.DBforPostgreSQL/servers/psql-shared-application-server-uat/databases/AED-Provider-uat][0m
[0m[1mmodule.notify.azurerm_app_service.AED-Notify: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.Web/sites/AED-Notify-uat][0m
[0m[1mmodule.microservice["AED-Provider-uat"].azurerm_app_service.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.Web/sites/AED-Provider-uat][0m
[0m[1mmodule.eibis.azurerm_app_service.AED-Eibis: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.Web/sites/AED-Eibis-uat][0m
[0m[1mmodule.microservice["AED-Address-uat"].azurerm_app_service.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.Web/sites/AED-Address-uat][0m
[0m[1mmodule.microservice["AED-Person-uat"].azurerm_app_service.AED-microservice: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.Web/sites/AED-Person-uat][0m
[0m[1mazurerm_storage_blob.staticwebsitestorage_resource: Refreshing state... [id=https://staticwebstorageuat.blob.core.windows.net/$web/index.html][0m
[0m[1mmodule.payeduc-fls.azurerm_storage_share.AED-payeduc-fls: Refreshing state... [id=https://payeducflsstorageuat.file.core.windows.net/payeducflsstorage-share][0m
[0m[1mmodule.strapi.azurerm_storage_share.AED-strapi: Refreshing state... [id=https://strapistorageaccountuat.file.core.windows.net/strapi][0m
[0m[1mmodule.strapi.azurerm_container_group.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-one/providers/Microsoft.ContainerInstance/containerGroups/strapi-with-ssl-sidecar][0m
[0m[1mmodule.strapi.azurerm_backup_policy_file_share.AED-strapi: Refreshing state... [id=/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-strapi-one/providers/Microsoft.RecoveryServices/vaults/aedigital-uat-postgres-strapi-recovery-vault/backupPolicies/ae-default][0m
[0m
[1m[36mNote:[0m[1m Objects have changed outside of Terraform[0m

[0mTerraform detected the following changes made outside of Terraform since the
last "terraform apply":

[1m  # module.notify.azurerm_app_service.AED-Notify[0m has been changed[0m[0m
[0m  [33m~[0m[0m resource "azurerm_app_service" "AED-Notify" {
        [1m[0mid[0m[0m                                = "/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigital-uat-rg-microservice/providers/Microsoft.Web/sites/AED-Notify-uat"
        [1m[0mname[0m[0m                              = "AED-Notify-uat"
      [32m+[0m [0m[1m[0mtags[0m[0m                              = {}
        [90m# (17 unchanged attributes hidden)[0m[0m

        [90m# (4 unchanged blocks hidden)[0m[0m
    }
[1m  # azurerm_storage_account.staticwebsitestorage_account[0m has been changed[0m[0m
[0m  [33m~[0m[0m resource "azurerm_storage_account" "staticwebsitestorage_account" {
        [1m[0mid[0m[0m                             = "/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigitalcloud-uat-rg-staticstite/providers/Microsoft.Storage/storageAccounts/staticwebstorageuat"
        [1m[0mname[0m[0m                           = "staticwebstorageuat"
      [32m+[0m [0m[1m[0mtags[0m[0m                           = {}
        [90m# (32 unchanged attributes hidden)[0m[0m

        [90m# (5 unchanged blocks hidden)[0m[0m
    }
[1m  # azurerm_resource_group.static_resource_group[0m has been changed[0m[0m
[0m  [33m~[0m[0m resource "azurerm_resource_group" "static_resource_group" {
        [1m[0mid[0m[0m       = "/subscriptions/9d73f4f4-d3d4-4484-9d81-eaff51a75c9f/resourceGroups/goa-cc-aedigitalcloud-uat-rg-staticstite"
        [1m[0mname[0m[0m     = "goa-cc-aedigitalcloud-uat-rg-staticstite"
      [32m+[0m [0m[1m[0mtags[0m[0m     = {}
        [90m# (1 unchanged attribute hidden)[0m[0m
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
[90m
─────────────────────────────────────────────────────────────────────────────[0m

[0m[1m[32mNo changes.[0m[1m Your infrastructure matches the configuration.[0m

[0mYour configuration already matches the changes detected above. If you'd like
to update the Terraform state to match, create and apply a refresh-only plan.
Failed running command "cd '/terraform' && envdir /env terraform show -json /terraform/terraform.tfplan" (exit 2)
Output: panic: value is marked, so must be unmarked first

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.LengthInt(0x2cbab70, 0xc001808920, 0x25536a0, 0xc0008236c8, 0x2cbab01)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1050 +0x4f
github.com/zclconf/go-cty/cty.transform(0xc00171f920, 0x1, 0x1, 0x2cbab70, 0xc001808920, 0x25536a0, 0xc0008236c8, 0x2c84028, 0xc00000c090, 0xc0008236c8, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:144 +0x2e8
github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x2cbab38, 0xc001809190, 0x245fdc0, 0xc000eeb770, 0x2c84028, 0xc00000c090, 0xc00171f0b0, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:209 +0x10ed
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/walk.go:125
github.com/zclconf/go-cty/cty.Value.MarkWithPaths(0x2cbab38, 0xc001809190, 0x245fdc0, 0xc000eeb770, 0xc0006d0f00, 0x3, 0x4, 0x2c1a2c0, 0x1, 0xc00127a920, ...)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/marks.go:236 +0xc5
github.com/hashicorp/terraform/internal/command/jsonstate.marshalResources(0xc00076f7a0, 0xc001003cc0, 0x1, 0x1, 0xc000a3e4b0, 0xc001876580, 0x1, 0x2, 0x0, 0x0)
	/home/circleci/project/project/internal/command/jsonstate/state.go:333 +0xe07
github.com/hashicorp/terraform/internal/command/jsonstate.marshalModules(0xc00013c490, 0xc000a3e4b0, 0xc0008c1380, 0x7, 0x8, 0xc0012c51a8, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/internal/command/jsonstate/state.go:254 +0x538
github.com/hashicorp/terraform/internal/command/jsonstate.marshalRootModule(0xc00013c490, 0xc000a3e4b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/internal/command/jsonstate/state.go:234 +0x8c9
github.com/hashicorp/terraform/internal/command/jsonstate.(*state).marshalStateValues(0xc000ed1f50, 0xc00013c490, 0xc000a3e4b0, 0x0, 0x0)
	/home/circleci/project/project/internal/command/jsonstate/state.go:166 +0x14a
github.com/hashicorp/terraform/internal/command/jsonstate.Marshal(0xc00076e480, 0xc000a3e4b0, 0x0, 0x0, 0x0, 0x0, 0x219f5b5)
	/home/circleci/project/project/internal/command/jsonstate/state.go:146 +0xf8
github.com/hashicorp/terraform/internal/command/jsonplan.Marshal(0xc00065dc70, 0xc0010c8dc0, 0xc00076e480, 0xc000a3e4b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/project/internal/command/jsonplan/plan.go:152 +0x633
github.com/hashicorp/terraform/internal/command.(*ShowCommand).Run(0xc00037c000, 0xc000140070, 0x1, 0x2, 0xc00034e170)
	/home/circleci/project/project/internal/command/show.go:152 +0x966
github.com/mitchellh/cli.(*CLI).Run(0xc000368280, 0xc00034c000, 0x282e5dd, 0x4)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
main.wrappedMain(0x0)
	/home/circleci/project/project/main.go:384 +0x1112
main.realMain(0x0)
	/home/circleci/project/project/main.go:115 +0x554
main.main()
	/home/circleci/project/project/main.go:58 +0x25

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.771064786.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.771064786.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!


**Comment by alisdair** [comment]
Thanks for reporting the crash. This issue was fixed in #29049, released in 1.0.2. Please upgrade to 1.0.11 for the fix.
