### ISSUE TITLE
GCP google_monitoring_alert_policy "Auto close incidents" option

### ISSUE THREAD

**Issue by ghebo** [hashicorp/terraform#30158]
Hi there,

I couldn't find a way to set "Auto close incidents" for google_monitoring_alert_policy. In GCP dashboard there is an option for that (see picture below), but how can I set this one using TF ?

![image](https://user-images.githubusercontent.com/24297672/145959136-f99df49b-b9f0-4c24-b136-3986fb2d14ba.png)

### Current Terraform Version

```
Terraform v0.13.7
```

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_notification_channel

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
