### ISSUE TITLE
Support AllowMajorVersionUpgrade flag when modifying RDS instances

### ISSUE THREAD

**Issue by mahileeb** [hashicorp/terraform#3017]
I was trying to launch a MySQL 5.6 instance from a 5.5 snapshot and it launched ok but then when I re-ran it seems that the instance picks up the version from the snapshot instead of the version specified when launching.

The modify then fails due to:

```
aws_db_instance.demo_db: Error modifying DB Instance uat-demo-db: InvalidParameterCombination: The AllowMajorVersionUpgrade flag must be present when upgrading to a new major version.
	status code: 400, request id: [f2cce8f0-4530-11e5-a1f2-adad95a051a5]
```

**Comment by vervas** [comment]
I can experience the same problem when trying to upgrade a Postgres instance from 9.3.10 to 9.4.7. My Terraform version is v0.6.16.

I would reopen this.
