### ISSUE TITLE
Moved Block doesn't move nested modules in modules

### ISSUE THREAD

**Issue by StanGirard** [hashicorp/terraform#30197]
### Terraform Version

```
1.1.0
```

### Terraform Configuration Files

```terraform
moved {
  from = module.staging.module.consent_drop
  to   = module.data_engineering.module.consent_drop
}
```

### Expected Behavior

Moves all the resources in the `module.consent_drop` into the new `module.consent_drop`

### Actual Behavior

It only moves the `resources` that are declared in `module.consent_drop` and doesn't move the nested modules called in module.consent_drop

### Steps to Reproduce

- Create a module that has resources and modules created inside
- Try to rename it and use the move block

It will only move the resources and not the nested modules

**Comment by crw** [comment]
Thanks for the report! I will let @apparentlymart comment on whether this is expected behavior or an issue, in the meantime your question sounds a little like the discussion from https://github.com/hashicorp/terraform/issues/30182 - the info in that ticket may help set some context.

**Comment by apparentlymart** [comment]
Hi @StanGirard, (and @crw!)

It does sound like you have found a bug here. Our design intent was that you should be able to rename (or, in this case, "reparent" I suppose) a module block without modifying any of the source code in the module's implementation -- including any nested modules -- and have Terraform behave as if everything encapsulated inside that module had originally been declared at the new name.

I've not yet looked deeply to understand what's going on here but I suspect what we have here is a missing rule inside the algorithms which answer questions like "is address A nested inside resource B?", causing it to get an incorrect answer when considering the resources declared inside your nested modules.

**Comment by StanGirard** [comment]
Hello @apparentlymart & @crw ! Thanks for the reply.

I dug a bit (damn, it is a huge code base 😄) . Could it be `ParseMoveEndpoint` that doesn't work for modules?

**Comment by alisdair** [comment]
Thanks for the report. I'm able to confirm this with the following configuration and steps:

### Initial setup

```shellsession
$ tree
.
├── main.tf
└── modules
    ├── bar
    │   └── main.tf
    ├── foo
    │   └── main.tf
    └── staging
        └── main.tf
```

main.tf:

```terraform
module "staging" {
  source = "./modules/staging"
}
```

modules/staging/main.tf:

```terraform
module "foo" {
  source = "../foo"
}
```

modules/foo/main.tf:

```terraform
resource "null_resource" "foo" {}

module "bar" {
  source = "../bar"
}
```

modules/bar/main.tf:

```terraform
resource "null_resource" "bar" {}
```

Apply this configuration:

```shellsession
$ terraform-1.1.2 apply -auto-approve

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.staging.module.foo.null_resource.none will be created
  + resource "null_resource" "none" {
      + id = (known after apply)
    }

  # module.staging.module.foo.module.bar.null_resource.bar will be created
  + resource "null_resource" "bar" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
module.staging.module.foo.module.bar.null_resource.bar: Creating...
module.staging.module.foo.null_resource.none: Creating...
module.staging.module.foo.null_resource.none: Creation complete after 0s [id=8023837833563797539]
module.staging.module.foo.module.bar.null_resource.bar: Creation complete after 0s [id=9042121017066492354]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

### Prepare move

Move modules/staging to modules/production and run `terraform init`

Update main.tf:

```terraform
module "production" {
  source = "./modules/production"
}

moved {
  from = module.staging.module.foo
  to   = module.production.module.foo
}
```

Re-plan:

```shellsession
$ terraform-1.1.2 plan
module.staging.module.foo.module.bar.null_resource.bar: Refreshing state... [id=9042121017066492354]
module.production.module.foo.null_resource.none: Refreshing state... [id=8023837833563797539]

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # module.staging.module.foo.null_resource.none has moved to module.production.module.foo.null_resource.none
    resource "null_resource" "none" {
        id = "8023837833563797539"
    }

  # module.production.module.foo.module.bar.null_resource.bar will be created
  + resource "null_resource" "bar" {
      + id = (known after apply)
    }

  # module.staging.module.foo.module.bar.null_resource.bar will be destroyed
  # (because null_resource.bar is not in configuration)
  - resource "null_resource" "bar" {
      - id = "9042121017066492354" -> null
    }

Plan: 1 to add, 0 to change, 1 to destroy.

───────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

The resource in `module.staging.module.foo` is planned to move, but the nested resource in `module.staging.module.foo.module.bar` is planned to destroy/recreate.
