### ISSUE TITLE
`moved` documetation page typo

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/terraform#30198]
Documentation miss `moved` block in renaming module call section (https://www.terraform.io/language/modules/develop/refactoring#renaming-a-module-call)

### Terraform Version

```
Terraform v1.1.0
```

### Expected Behavior

```hcl
module "b" {  source = "../modules/example"
  # (module arguments)  
}

moved {
  from = module.a
  to = module.b
}
```

### Actual Behavior

```hcl
module "b" {  source = "../modules/example"
  # (module arguments)
}
```

**Comment by quentin9696** [comment]
I tried to create a PR but it looks somebody already merge a fix to master.

**Comment by crw** [comment]
It looks like it is already fixed in the docs, so I am going to close this one. Let me know if I am misunderstanding the place with the issue.
