### ISSUE TITLE
Error Deleting Subnet, Error Deleting EC2 Internet Gateway

### ISSUE THREAD

**Issue by sohailanjum97** [hashicorp/terraform#30213]
Terraform Version:
v0.13.0

Architecture:
1 VPC, 4 Subnets, 2 subnect in each availability zone, 1 public and 1 private subnet, 1 NAT Gateway, 1 Internet Gateway, Eks Cluster. 
Whenever I am trying to run 
terraform destroy. 
This is the error:
 
![image](https://user-images.githubusercontent.com/48083468/146709143-dc4d2d8d-68db-464b-aa6d-b9ad7381c803.png)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
