### ISSUE TITLE
Add triggers argument and last_updated attribute to lifecycle meta-argument

### ISSUE THREAD

**Issue by RobCannon** [hashicorp/terraform#30210]
### Current Terraform Version
```
Terraform v1.1.2
on linux_amd64
```

### Use-cases
I ended up using the ```null_resource``` with it's ```triggers``` argument to control when some external scripts are run and I found the ability very handy and I think that this ability would be very useful for all resources.

1) Be able to trigger a resource rebuild based on an external factor.  For instance, a REST API could indicate when a server needs to be patched due to a critical
vulnerability with an available patch.
2) A resource (like a server) could be triggered to rebuild on a schedule like "at least every 7 days".
3) When one resource is rebuilt, it should trigger the rebuild of a second resource (discussed in #8099).

### Attempted Solutions
Using the ```random_id``` resource with ```keepers``` as a way to trigger a rebuild node_pools on a GKE cluster.  But not every resource has an attribute that can be used to trigger a rebuild without other impacts.  Changing the name of some resource to a random base value in not always an acceptable solution.

### Proposal
Add a ```triggers``` argument to the ```lifecycle``` meta-argument for every resource that would work similar to how the ```triggers``` argument works for the ```null_resource``` resource.  The ```trigger``` arguement would accept a map(string) and would trigger the rebuild of the resource if any of the values of that map are changed.  Using the ```lifecycle``` meta-argument makes this non-breaking since you will not have to worry about breaking any resources that are already using an attribute name triggers.  

Also, add a ```last_updated``` attribute to the ```lifecycle``` meta-argument to indicate the last date/time a resource was updated.

Here is an example of how this could be used.  This would ensure that a server is updated at least once a week.  This assumes that there is a job that applies terraform on a regular basis.
```
resource "google_compute_instance" "test" {
  name         = "test"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  lifecycle {
    triggers = {
      time_to_update = timeadd(self.lifecycle.last_updated, 7d) > timestamp
    }
  }
}
```

Here is an example using a rest api to trigger a rebuild of a server.  The HTTP would indicate that a server needs to be rebuilt based on external factors (like a failed vulnerability scan) and return a json response with a true or false result.  This also assumes that there is a job that applies terraform on a regular basis.
```
data "http" "example" {
  url = "https://checkserver.constoso.com/needs_rebuild/${google_compute_instance.test.name}"
}

resource "google_compute_instance" "test" {
  name         = "test"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  lifecycle {
    triggers = {
      needs_rebuild = jsondecode(data.http.example.body)
    }
  }
}
```

Finally, here is an example of having one resource trigger the rebuild of another resource.  server-2 would be rebuilt any time server-1 was rebuilt.
```
resource "google_compute_instance" "server1" {
  name         = "server-1"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  lifecycle {
    triggers = {
      needs_rebuild = jsondecode(data.http.example.body)
    }
  }
}

resource "google_compute_instance" "server2" {
  name         = "server-2"
  machine_type = "e2-medium"
  zone         = "us-central1-a"

  lifecycle {
    triggers = {
      server1_last_updated = jsondecode(google_compute_instance.server1.lifecycle.last_updated)
    }
  }
}
```

The ```lifecycle``` meta-argument is not currently available as an attribute that can be used in terraform expression, but perhaps that could be changed to
enable this feature.

The ```lifecycle``` docs have this caveat which would not allow this since triggers would this to work, but does the caveat have to apply to all values in lifecycle?
```
The lifecycle settings all affect how Terraform constructs and traverses the dependency graph. As a result, only literal values can be used because the processing happens too early for arbitrary expression evaluation.
```

### References

I found issue #8099 and I think this proposed feature would solve a lot of the scenarios discussed in that issue.

**Comment by bulebuk** [comment]
I submitted a ticket to add a keeper/trigger argument to `aws_iam_access_key`. This feature would render that and other future enhancements moot. https://github.com/hashicorp/terraform-provider-aws/issues/23180

However, lifecycle parameters only accept a string literal and would not support a programmatic value. I would suggest instead to add this as a new meta-argument, ala `count` and `for_each`.
