### ISSUE TITLE
Highlighting missing in the documentation 

### ISSUE THREAD

**Issue by samuraifox1** [hashicorp/terraform#30216]
Hi, I find it strange that , in many places, documentation does not highlights the key points as separate note or warning. 

For instance: On [functions Page](https://www.terraform.io/language/functions), we should make the below point highlighted instaed of part of the common text for more professional and user-friendly manner: 

```
The Terraform language does not support user-defined functions, and so only the functions built in to the language are available for use. 
```

This line deserve a special yellow warning block.

**Comment by apparentlymart** [comment]
Hi @samuraifox1,

We typically reserve the yellow "callout" formatting for information that, if missed, could have confusing or dangerous consequences. The paragraph you mentioned here seems to be purely information and not obviously any more important than anything else mentioned on this page; the user not being aware that Terraform doesn't support user-defined functions won't cause them to accidentally try something dangerous, or to see a confusing error message.

Is there something special you see about that particular paragraph that causes you to think it deserves to be in a warning callout?

Thanks!

**Comment by crw** [comment]
Hi @samuraifox1, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
