### ISSUE TITLE
IAM Policy parse error

### ISSUE THREAD

**Issue by meylor** [hashicorp/terraform#3022]
I'm trying to create the following policy via aws_iam_group_policy
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreateAccessKey",
                "iam:UpdateAccessKey"
            ],
            "Resource": "arn:aws:iam::REPLACE-WITH-ACCOUNT-ID-HERE:user/${aws:username}"
        }
    ]
}
```
when running apply, I receive the following error:
```
Error loading config: Error loading /home/meylor/infra/terraform/users.tf: Error reading config for aws_iam_group_policy[engineering]: parse error: syntax error
```
It appears as though the parser is unable to parse ```${aws:username}```. When I replace with ```"Resource": "arn:aws:iam::REPLACE-WITH-ACCOUNT-ID-HERE:user/*"``` it parses just fine.

**Comment by meylor** [comment]
Reviewing https://www.terraform.io/docs/configuration/interpolation.html , I'm able to escape interpolation with ```"Resource": "arn:aws:iam::REPLACE-WITH-ACCOUNT-ID-HERE:user/$${aws:username}"```, but the resulting policy appears as ```"Resource": "arn:aws:iam:::REPLACE-WITH-ACCOUNT-ID-HERE:user/$${aws:username}"``` with the second ```$```. I don't believe this is the correct behavior.

**Comment by catsby** [comment]
Hey @meylor – sorry for the very long silence here. I believe this issue has since been resolved (parsing variables or other things in-line). 

Let me know if you're still hitting this!
