### ISSUE TITLE
Azure Alert rule there is option called Suppress alerts

### ISSUE THREAD

**Issue by prakashashokan** [hashicorp/terraform#30230]
In Azure Alert rule there is option called Suppress alerts. But I don't see the variables to enable the Suppress alerts. I tried with suppress_alerts = enable. It is not working. Please let me know.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert
![Supress_rulealert](https://user-images.githubusercontent.com/7718648/146954036-55415332-d1da-4fe7-adca-cf006eb1c225.JPG)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
