### ISSUE TITLE
`consul_keys` intermittently returns a Terraform error on `terraform apply`

### ISSUE THREAD

**Issue by trentonstrong** [hashicorp/terraform#3023]
I've been received this error message lately:

```
Error applying plan:

2 error(s) occurred:

* consul_keys.dashboard_keys: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* consul_keys.scribe_keys: diffs didn't match during apply. This is a bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

EDIT: ~~The odd part is it seems that the consul_keys are being updated properly.~~  The reproducing criteria seems to be having consul_key values that depend on another resource (say an aws_instance dns name) and the resource needs to be recreated, therefore the consul_keys need to be refreshed.

EDIT:  Spoke too soon.  The consul_keys did not change correctly.

Hope this helps.

**Comment by trentonstrong** [comment]
Additonally, running `terraform apply` a second time results in the state refreshing and the usual:

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

  consul_address = ec2-52-21-32-160.compute-1.amazonaws.com
```

**Comment by apparentlymart** [comment]
Thanks for the report and the debugging work!

If you separately run the three steps that ``terraform apply`` does, do you still see the issue?

* ``terraform refresh``
* ``terraform plan -refresh=false -out=plan``
* ``terraform apply plan``

I wouldn't expect that to make any difference, but then I also wouldn't expect this issue to exist. :)

Also, if you could share a suitably-anonymized version of the relevant parts of your configuration I think that would go a long way to helping figure out how to reproduce this.

**Comment by trentonstrong** [comment]
Sorry about the delay, things are rather busy over here.

I had a chance to to try out your suggestion, and as you expected it did not make a difference.  I'll attach a copy of the plan and the relevant portions of the anonymized config in a bit.

**Comment by trentonstrong** [comment]
Consul config
```
provider "consul" {
  address = "127.0.0.1:8500"
  datacenter = "dc1"
  scheme = "http"
}

module "consul" {
  source = "github.com/hashicorp/consul/terraform/aws"
  key_name = "${var.key_name}"
  key_path = "${var.key_path}"
  region = "${var.region}"
  servers = "3"
}
```

The resource that changed:
```
resource "aws_instance" "admin_backend" {
  ami = "${var.admin_backend_ami}"  // This AMI changes due to a change in the variable
  instance_type = "m3.medium"
  key_name = "${var.key_name}"
  security_groups = ["consul", "${aws_security_group.admin_backend.name}"]
  iam_instance_profile = "${aws_iam_instance_profile.admin_backend_profile.name}"
  count = 1

  tags {
    Name = "admin-backend-${count.index}"
  }
  ...
}
```

Example of variable declaration:
```
...

variable "admin_backend_ami" {
  default = "ami-xxxxxx" // We change this value to update the deploy
}

...
```

The consul_keys that depend on the resource being changed:
```
resource "consul_keys" "dashboard_keys" {
  key {
    name = "http_port"
    path = "service/dashboard/port"
    value = "${var.dashboard_http_port}"
  }
  key {
    // This is the value that does not update
    name = "admin_api_url"
    path = "service/dashboard/api_host"
    value = "http://${aws_instance.admin_backend.public_dns}:${var.admin_backend_port}"
  }
  key {
    name = "api_client_id"
    path = "service/dashboard/api_client_id"
    value = "orphid-admin"
  }
  key {
    name = "admin_api_token"
    path = "service/dashboard/api_token"
    value = "${var.scribe_admin_api_token}"
  }
}
```

Our workaround in the interim has been to taint the consul_keys that are affected and force them to be recreated.  This works.

Let me know if I should send you the plan file or anything else that was generated!
