### ISSUE TITLE
  aws_mq_broker.mybroker.instances ip_address property always empty

### ISSUE THREAD

**Issue by Houuse** [hashicorp/terraform#30241]
### Terraform Version

```
1.1.2
```

### Terraform Configuration Files

```
output "rabbit-cluster-ip" {
  value = aws_mq_broker.Rabbit-Dev.instances
}
```

### Debug Output
rabbit-cluster-ip = tolist([
  {
    "console_url" = "https://b-xxxxxxxx-xxxx-xxxx-xxxxxx7f54c0.mq.xx-north-1.amazonaws.com"
    "endpoints" = tolist([
      "amqps://b-xxxxxxxx-xxxx-xxxx-xxxxxx7f54c0..mq.xx-north-1.amazonaws.com:5671",
    ])
    "ip_address" = ""
  },
])

### Expected Behavior
to have the ip address property filled

### Actual Behavior
it's empty 

### References
- #2821

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
