### ISSUE TITLE
Multi-attach is now enabled on AWS EBS for io2

### ISSUE THREAD

**Issue by jkstenzel95** [hashicorp/terraform#30244]
https://aws.amazon.com/about-aws/whats-new/2020/12/multi-attach-support-now-available-on-amazon-ebs-provisioned-iops-volume-type-io2/

### Terraform Version

```
terraform version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0

Your version of Terraform is out of date! The latest version
is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```
terraform
terraform {
    backend "s3" { 
        bucket          = locals.BUCKET_NAME
        key             = "global/s3/terraform.tfstate"
        region          = "us-east-2"

        dynamodb_table  = locals.DYNAMODB_NAME
        encrypt         = true
    }
    
    required_providers {
        aws = {
            source  = "hashicorp/aws"
            version = "~> 3.70"
        }
    }

    required_version = ">= 1.0.11"
}

provider aws {
    profile = "default"
    region  = "${var.server_region}"
}
```

### Expected Behavior
Creating an AWS EBS volume with the following parameters should not be failing because of the io2 type and multi-attach:
```
resource "aws_ebs_volume" "volume" {
    availability_zone = "us-east-2b"
    size = 200
    type = "io2"
    multi_attach_enabled = true
    iops = 200

    tags = {
        Name = "jks-gs-blahblahblah-data-volume"
    }
}
```

### Actual Behavior
```
│ Error: 'multi_attach_enabled' must not be set when 'type' is 'io2'
│
│   with module.game-servers.module.ark_cluster.module.shared_data_volume.module.volume.aws_ebs_volume.volume,
│   on game-servers/modules/volume/main.tf line 3, in resource "aws_ebs_volume" "volume":
│    3: resource "aws_ebs_volume" "volume" {
```

### Steps to Reproduce
Create a similar volume with a backend of your choice. init, then plan.

### Additional Context
Running on WSL

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
