### ISSUE TITLE
The "for_each" value depends on resource attributes that cannot be determined until apply

### ISSUE THREAD

**Issue by gallowaystorm** [hashicorp/terraform#30246]
### Terraform Version

```
Terraform v1.1.2
```

### Terraform Configuration Files

```terraform
resource "aws_route53_record" "vanity_route53_cert_validation" {
  # use domain management secondary aws provider
  provider = aws.domain-management

  for_each = {
    # Grabs values of certificates for validation records only needed in domain management account by filtering for ones that includes var.fully_qualified_domain_name
    for dvo in aws_acm_certificate.vanity_certificate.domain_validation_options : dvo.domain_name => dvo if contains(values(dvo), var.fully_qualified_domain_name)
  }

  zone_id         = data.aws_route53_zone.vanity_zone.zone_id
  name            = each.value.resource_record_name
  records         = [each.value.resource_record_value]
  ttl             = 60
  type            = each.value.resource_record_type
  allow_overwrite = true
}
```

### Expected Behavior

The contains() function should have been evaluated on plan to allow for for_each to know the amount of resources needed.  I know the information to do this is available because if you follow the "classic" way of doing Certificate validation that is listed here on Terraform's site:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate

```terraform
resource "aws_route53_record" "example" {
  for_each = {
    for dvo in aws_acm_certificate.example.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.example.zone_id
}
```

This ends up working... Even though it depends on a resource attribute that cannot be determined until applied.  Just like the error message above.  So to fix this, we would need these functions (like contains) to be evaluated on a terraform plan.

### Actual Behavior

The "contains()" function is what is messing me up.  I am trying to create a record in a separate account for a vanity certificate.  To do so, I need to filter the domain_validation_options based off FQDN.  This contains() function is apparently not evaluated on plan, so it fails with:

```bash
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target
│ argument to first apply only the resources that the for_each depends on.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by jbardin** [comment]
Hi @gallowaystorm,

The problem here isn't specifically the `contains` function, its the fact that the `domain_validation_options` is a computed value from the `aws_acm_certificate` so it's not going to be known during the plan. In order to use `for_each` here you will need to supply some static information, possibly some data from which the `domain_validation_options` are derived.

Since this doesn't represent a bug in Terraform I'm going to close the issue. You may be able to find more assistance in [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more users familiar with the details of these resource, and have experience structuring their configurations.

Thanks!

**Comment by gallowaystorm** [comment]
Hi @jbardin ,

That is the point I am trying to make, the value that I am trying to use is `domain_name` which is computed on the plan.  See below from my output:



```bash
  # module.some-module..aws_acm_certificate.vanity_certificate will be created
  + resource "aws_acm_certificate" "vanity_certificate" {
      + arn                       = (known after apply)
      + domain_name               = "some-url.com"
      + domain_validation_options = [
          + {
              + domain_name           = "*.staging.some-url.com"
              + resource_record_name  = (known after apply)
              + resource_record_type  = (known after apply)
              + resource_record_value = (known after apply)
            },
          + {
              + domain_name           = "some-url.com"
              + resource_record_name  = (known after apply)
              + resource_record_type  = (known after apply)
              + resource_record_value = (known after apply)
            },
        ]
      + id                        = (known after apply)
      + status                    = (known after apply)
      + subject_alternative_names = [
          + "*.staging.some-url.com",
        ]
      + validation_emails         = (known after apply)
      + validation_method         = "DNS"
    }
```


As you can see (even though I changed the values for privacy), the `domain_name` is computed at plan
