### ISSUE TITLE
Skip some resources from deletion/re-creation, rather create a new resource whenever there's a change associated with it

### ISSUE THREAD

**Issue by Chandni91** [hashicorp/terraform#30258]
We are using terraform to deploy our applications on AWS ECS cluster. 

In our terraform module, we create a task definition for a particular application using the terraform resource 'aws_ecs_task_definition' which is then used to create an ecs service using the terraform resource 'aws_ecs_service'. 

Now let's assume there's a change in task definition resource and we run terraform apply on this module then terraform deletes existing task definition resource and creates a new version. Deleting a task definition resource in AWS means marking it as INACTIVE. And inactive task definitions are not good for us for below reasons:

1. If there are existing tasks running with INACTIVE task definition then it is not possible to scale-up the service from AWS console as inactive task definition version is not available in the list to choose from while updating the service.

2. If we want to revert our service at any point of time to some previous task definition version which is now inactive then it won't be possible.

3. AWS doesn't recommend using INACTIVE task definitions:  https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeregisterTaskDefinition.html 
 " At this time, INACTIVE task definitions remain discoverable in your account indefinitely. However, this behavior is subject to change in the future. We don't recommend that you rely on INACTIVE task definitions persisting beyond the lifecycle of any associated tasks and services. " 

Our query:
Is it somehow possible to instruct terraform not to delete and re-create task definition resource rather just create a new version whenever there is a change associated with it? 

### Proposal
May be Terraform can introduce some feature where we can explicitly tag a resource which should not be deleted and re-created on change, rather a new one is created.

**Comment by jbardin** [comment]
Hi @Chandni91,

Thanks for filing the proposal! Terraform does not make the decision to replace a resource on its own, it only does so at the request of a provider. When a provider gets a configuration which it determines triggers the replacement of a resource, it will indicate in the plan result that the resource requires replacement. Terraform shows which attributes the provider labeled as the cause of replacement by marking with `forces replacement` in the plan output.

You can then use the [ignore_changes](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes) lifecycle attribute to instruct Terraform to not change the existing values of those attributes which trigger replacement. If you want no changes to be made, you can specify `all` in the list of attribute under `ignore_changes`. 

Does this fit your intended use case?

**Comment by Chandni91** [comment]
Hi @jbardin 

Thanks for your quick response and explaining that this behavior is coming from provider end. Probably we can log this enhancement in 'hashicorp/terraform-provider-aws' repository. 

Regarding ignore_changes lifecycle attribute, unfortunately it will not work for us because we would like terraform to create a new version of the resource whenever there's a change around it.

**Comment by jbardin** [comment]
Thanks @Chandni91, it does does sound like you are describing something specific to the resources here. You can use `ignore_changes` for individual attributes which cannot be changed without replacement, you are not required to list all of them.

If what you were intending to propose what that the resource be abandoned rather than destroyed, we can track that in #27035.

Thanks!

**Comment by Chandni91** [comment]
Yes abandoning the resource rather than destroying it is something that will help us.

**Comment by Chandni91** [comment]
Yes abandoning the resource rather than destroying it is something that will help us. Thanks a lot for this.

From the linked issue:
`resource "provider_resource" "resource" {
  lifecycle {
    on_destroy = "retain"
  }
}`

Quick question: Will we still be able to create the new version of this resource using terraform apply when there's a change? My expectation would be that previous version is abandoned and a new one is created.

**Comment by jbardin** [comment]
We have yet to design an implementation for this feature, so I can't answer exactly what would happen, but that is one possible scenario.

**Comment by Chandni91** [comment]
Cool, thanks a lot for all your help in this case!
