### ISSUE TITLE
Terraform is not adding tags to network interfaces created when a private endpoint is created.

### ISSUE THREAD

**Issue by epfaffinger** [hashicorp/terraform#30251]
When you create a private endpoint using Terraform and tag the end point the NIC created for the endpoint is not tagged. Below is a sample of my config file:

resource "azurerm_private_endpoint" "apppe1" {
  name                = "pe-${azurerm_app_service.appsvc1.name}"
  location            = var.location
  resource_group_name = "${azurerm_resource_group.rg.name}"
  subnet_id           = lookup(var.subnet_id, var.subnet_name)

  private_service_connection {
    name                           = "${azurerm_app_service.appsvc1.name}-psc"
    private_connection_resource_id = azurerm_app_service.appsvc1.id
    subresource_names              = ["sites"]
    is_manual_connection           = false	
  }
  
  tags = {
	  costCenter = lookup(var.cost_center, var.billing_dept)
	}

}

This creates the private endpoint and tags it fine but the NIC is not tagged? How do we tag the NIC, my expectation would be that the NIC uses the same tag?

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
