### ISSUE TITLE
terraform push errors with projects with symlinks

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#3025]
When a Terraform resource references a file on the local filesystem that is a symlink, `terraform push` fails and exits with an error. In this case the resources is `template_file` and the `filename` property is pointing to a symlink which points to a file in another location within the repository.

Relative symlinks fail with an "invalid path" error because `${path.module}` seems to use the current working directory that terraform executes from instead of the DIR passed to terraform. Absolute symlinks fail 

`plan`, `apply`, and `destroy` work fine.

I would expect `terraform push` to interpret/read the symlinks as normal files as it appears the other commands are doing.

Tested with Terraform v0.6.0 and v0.6.3.

Project to reproduce this is at https://github.com/clstokes/terraform-push-symlink-error.

Example project structure:

```
$ tree
.
├── README.md
├── create-symlink-absolute.sh
├── create-symlink-relative.sh
├── files
│   └── main-userdata.sh.tpl
└── terraform
    ├── files
    │   └── main-userdata.sh.tpl -> ../../files/main-userdata.sh.tpl
    └── main.tf

3 directories, 6 files
```

**Comment by teamterraform** [comment]
The `terraform push` command is now defunct and removed in current versions of Terraform, replaced with [remote operations](https://www.terraform.io/docs/enterprise/run/cli.html). For that reason, we're going to close this out now.
