### ISSUE TITLE
enhance documentation of depends_on

### ISSUE THREAD

**Issue by tbugfinder** [hashicorp/terraform#30252]
### Current Terraform Version

```
1.1.2 / Webpage https://github.com/hashicorp/terraform/blob/58e4676aea77eb39038daff166c7b4a475e918b3/website/docs/language/meta-arguments/depends_on.mdx
```

### Use-cases

After having some discussions about the implications or side-effects when using `depends_on`, I'm suggesting to add more details to the documentation of it. Maybe also link to the details within data sources.

As a user, I understand that I can use `depends_on` to change the execution plan of terraform so that it processes those resources before the module / resource which has `depends_on` set. However based on the discussions and also the additional information within data sources docs, use of `depends_on` changes when data sources are processed. This is not documented well or even obvious to a user.

### Attempted Solutions

Google & post on discuss.hashicorp.com

### Proposal

I suggest to link the data sources information within the `depends_on` page and also explicitly state that `depends_on` also could  defer data source processing.

### References

https://discuss.hashicorp.com/t/terraform-plan-changes-based-on-existence-of-depends-on-in-module/33169/7?u=tbugfinder

https://www.terraform.io/language/data-sources#data-resource-dependencies

**Comment by laurapacilio** [comment]
Hi @tbugfinder - Thank you so much for bringing this to our attention! I just merged a docs PR that adds more context to the `depends_on` documentation. It summarizes the conversation you had with the Terraform team in the discussion thread, and will hopefully help future users better understand how `depends_on` can affect Terraform operations and planning. In particular, it specifically mentions that it affects data sources, and links to the associated dependencies documentation on that page. 

https://github.com/hashicorp/terraform/pull/30487

Please let us know if you have any additional thoughts, but just wanted to let you know that this has been taken care of. :-)

**Comment by tbugfinder** [comment]
LGTM! thank you!
