### ISSUE TITLE
Terraform 1.1.2 condition could lead to an empty state being written when run is interrupted

### ISSUE THREAD

**Issue by caiodelgadonew** [hashicorp/terraform#30266]
### Terraform Version

```
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.70.0"
    }
  }
  required_version = "~> 1.1.2"
}
```

### Debug Output

Can't get it since the state is empty and the run was not with debug log_level.

### Expected Behavior

The state is ok

### Actual Behavior

state is empty

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `CTRL+C` to interrupt the execution

### References

https://github.com/hashicorp/terraform/pull/30199

- #30178

**Comment by jbardin** [comment]
Hi @caiodelgadonew,

Thanks for filing the issue. Can you provide any more details about the exact commands and timing of what you are running?  Setting up a plan+apply with interrupts placed at various times does't reproduce this, but that of course is not an exhaustive measure of all possible program states. If there is no easily reproducible example, the console output and trace logs may help determine exactly where the interrupt is happening such that a new state is being written without a second SIGINT (which can always lead to loss of information from the state).

**Comment by caiodelgadonew** [comment]
I'll try to make it happen again (backing up the state) but it was just an init and apply, in the middle of the apply (it was creating a autoscalinggroup on AWS) I typed interrupt just once and it lead to the state corruption.

**Comment by apparentlymart** [comment]
Hi @caiodelgadonew,

Thanks for the additional context. Unfortunately I think it will be difficult to make progress here without some way to reproduce, but I also understand that it's hard to reproduce what appears to be a very timing-specific behavior.

Some other potential avenues we could take for debugging here, if you have the necessary information, would be:
* If you were running Terraform in any automation environment which keeps track of the Terraform output and when exactly the interrupt occurred, and were able to share that output for the job which exhibited the problem, we may be able to narrow down when exactly that interrupt occurred in relation to other actions and thus perhaps focus our debugging efforts a little better.
* If you are storing state in a backend which retains older versions, and you still have the empty snapshot that you were reporting here _and_ the prior one which you presumably restored as a backup to recover here, it could be helpful to know the answers to the following:
  1. Did the empty state snapshot have the same "lineage" value at the top-level of the JSON structure as the one which came before it? Similarly, did it have a "serial" value greater than what came before it? (In normal circumstances, Terraform retains the lineage and increments the serial by one for each new snapshot.)
  2. For the state snapshot which you described as empty, was it _totally_ empty (as in, zero bytes long), was it a valid-looking JSON data structure but with a zero-length `resources` array, or some sort of hybrid where perhaps some information was still preserved but other information was not?
  3. This final question's a bit broad and so I'm not sure _exactly_ what to ask, but I'd be curious if you could share anything else that might be "interesting" about the plan you were applying. You already mentioned it was creating an autoscaling group, which is good context. Was there any other action for any other resource instance included in that plan? Were there resource instances in your state that had no planned actions at all but were still omitted in the new empty state snapshot?

I will say that I'm trying my best to find a thread to tug on here but at this stage we're still broad enough that it's difficult to know exactly what avenues to explore, so if you can recall any other possibly-relevant or unusual aspects of that particular plan, any additional context could help narrow this down and help us ask some more specific questions. However, I do understand that it's hard to answer a question as broad as "what might be interesting?".

**Comment by caiodelgadonew** [comment]
Hello @apparentlymart .

It happened running this code https://github.com/caiodelgadonew/books-pyapi/tree/main/infra/ec2 

The interrupt was not a "double one" it was the graceful shutdown.

Trying to fetch more information about it, it happened twice but I cannot reproduce it again.

**Comment by jbardin** [comment]
Closing this since we have not heard back. If the issue can be replicated with a current release, feel free to reply here or open a new issue.

Thanks!
