### ISSUE TITLE
"provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.

### ISSUE THREAD

**Issue by prabirkrsarkar** [hashicorp/terraform#30262]
### Terraform Version

```
$ terraform -version
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0

```

### Terraform Configuration Files

https://github.com/prabirkrsarkar/bug-30262

### Debug Output

https://gist.github.com/prabirkrsarkar/d307066e982e95d1ae20ae766ff53f09

### Expected Behavior

Expect to create the DataLake Storage.

### Actual Behavior

```
Creating an Azure Data Lake Storage (among other resources) by calling a child module 
from root module. Got the following error: -

(Note: - After creating DataLake Storage (in modules/analyze) we are whitelisting virtual_network_subnet_ids 
from subnets created in modules/predict.)
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.analyze.azurerm_storage_account.optra, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: 
   Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

```
1. $ git clone https://github.com/prabirkrsarkar/bug-30262.git
2. Update values of parameters in main.tf, terraform.tfvars in root module
3. $ cd prerequisites and update values of params in terraform.tfvars
4. While still in prerequisites directory, run: $ terraform init && terraform apply
5. cd .. (to the root module level)
6. $ terraform init && terraform apply

```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
