### ISSUE TITLE
AWS S3 Backend in ap-southeast-3 (Jakarta) region is considered invalid

### ISSUE THREAD

**Issue by stevensim226** [hashicorp/terraform#30282]
### Terraform Version

```
Terraform v1.1.2
on darwin_amd64
```

### Terraform Configuration Files

```
provider "aws" {
    region = "ap-southeast-3"
}

terraform {
  backend "s3" {
    encrypt = "true"
    region  = "ap-southeast-3"
    bucket  = "terraform-remotestate"
    key     = "production/vpc/terraform.tfstate"
  }
}
```

### Debug Output

https://gist.github.com/stevensim226/c574e299a5f784dd83c948ae8c427af6

### Expected Behavior

Since `ap-southeast-3` has already been released with S3, the backend should initialize successfully

### Actual Behavior

Failed to initialize backend due to invalid region `ap-southeast-3`

### Steps to Reproduce

1. Copy this config
```
provider "aws" {
    region = "ap-southeast-3"
}

terraform {
  backend "s3" {
    encrypt = "true"
    region  = "ap-southeast-3"
    bucket  = "terraform-remotestate"
    key     = "prod/vpc/terraform.tfstate"
  }
}
```
2. Run `terraform init`

**Comment by littlejo** [comment]
Hello, 
The code problem is there:
https://github.com/aws/aws-sdk-go/blob/258263306d5faf0fc5f629dfcccf0f5ffedca131/aws/endpoints/defaults.go

There is no ap-southeast-3 region

**Comment by apparentlymart** [comment]
Hi @stevensim226! Thanks for reporting this.

Unfortunately, as @littlejo noted, the set of valid regions is hard-coded into the AWS SDK and so a particular version of Terraform can only support the AWS regions available in the AWS SDK version that was compiled into it. Conversely, new regions added later won't be directly selectable in Terraform's S3 backend until there is a release with a newer SDK version.

Upgrading the AWS SDK can sometimes have other side-effects for the S3 backend, and so we typically rely on the AWS provider maintainers to drive those upgrades as they have more familiarity with the upstream changes in S3 and what consequences there might be for upgrading. The "backend/s3" label added earlier is what they can use to find issues which might need their attention.

However, the region name is really just a shorthand for looking up a set of endpoint URLs that are unique per region, and so in the meantime you should be able to get the S3 backend working with any unsupported AWS regions by setting [the `iam_endpoint` argument](https://www.terraform.io/language/settings/backends/s3#iam_endpoint), which directly specifies the endpoint that the SDK would normally infer automatically itself from the region name. I don't know what is the appropriate endpoint URL for IAM in the ap-southeast-3 region, but that endpoint should be available in the AWS documentation somewhere.

**Comment by stevensim226** [comment]
@littlejo Yes, but unfortunately I still get an error with `1.1.3`
```
Terraform v1.1.3
on darwin_amd64
```

With the message
```
Initializing the backend...
╷
│ Error: Invalid AWS Region: ap-southeast-3
│ 
│ 
╵
```
