### ISSUE TITLE
No changes. Your infrastructure matches the configuration

### ISSUE THREAD

**Issue by Brucemendi** [hashicorp/terraform#30293]
### Terraform Version

Run `terraform version` to show the version, and paste the result between the ``` marks below.

PS C:\Terraform> terraform version
Terraform v1.1.2
on windows_amd64
PS C:\Terraform> 

 Terraform configuration file
'''   resource "aws_instance" "First-tf" {
ami           = "ami-002068ed284fb165b"
instance_type = "t2.micro"
  Name = "Demo1"
}

### Expected Behavior
Terraform returned with success

### Actual Behavior

PS C:\Terraform> terraform init

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
PS C:\Terraform> terraform plan   

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no      
differences, so no changes are needed.
PS C:\Terraform> terraform apply  

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no
differences, so no changes are needed.

Apply complete! Res

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

What actually happened?

### Steps to Reproduce
<!--
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
PS C:\Terraform> terraform init 

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

2. `terraform apply`

PS C:\Terraform> terraform apply

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no
differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
PS C:\Terraform>

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by Brucemendi** [comment]
Hi,
Thanks for the reply. i am new here.

**Comment by Brucemendi** [comment]
Hi James,

Can you help with the issue. Sorry I am new to Terraform and I am just
learning. I don't know why I can't automate the resources after doing
everything ?

Your help will be greatly appreciated.

Thanks
Bruce

**Comment by jbardin** [comment]
Hi @Brucemendi,

I'm not able to tell exactly what is or isn't working from the info provided. If you want to create a post with a little more detail in the community forum, I'm sure someone could help try to sort out what may have gone wrong for you.

**Comment by Brucemendi** [comment]
Ok, I will do that.
Thank you.

**Comment by umicheers** [comment]
please save the main.tf file in terraform folder before running the command.
