### ISSUE TITLE
Unable to Apply Subscription Filter Policy with Conditional: aws:PrincipalOrgID

### ISSUE THREAD

**Issue by td4b** [hashicorp/terraform#30302]
### Terraform Version

Running the following Terraform version (latest as of this post).
```
v1.1.2
```

### Terraform Configuration Files

The following Config is for the attachment of a cloud watch log policy for putting a subscription filter for a kinesis destination.
```terraform
resource "aws_cloudwatch_log_destination_policy" "kinesis_dest_policy" {
    access_policy    = jsonencode(
        {
            Statement = [
                {
                    Action    = "logs:PutSubscriptionFilter"
                    Effect    = "Allow"
                    Principal = "*"
                    Condition = {
                        StringEquals = {
                            "aws:PrincipalOrgID" = ["o-olabksbco938"]
                        }
                    }
                    Resource  = "${aws_cloudwatch_log_destination.kinesis_put_dest.arn}"
                    Sid       = "SubscriptionFilterDestPolicy"
                },
            ]
            Version   = "2012-10-17"
        }
    )
    destination_name = "${aws_cloudwatch_log_destination.kinesis_put_dest.name}"
}
```

### Debug Output

I can provide this upon request however the error code should probably be sufficient.
```bash
Output:

│ Error: Error creating DestinationPolicy: {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "5439acaa-1753-4cd2-9f4c-f9695eb6f460"
│   },
│   Message_: "Cannot update existing policy on Subscription Destination. The existing policy specifies AWS Principals by Account Id while the provided policy specifies AWS Principals by Org Id. This can cause subscription delivery failures for Subscriptions using this destination that are not configured with a Role. Use the Force flag to accept this risk."
│ }
```

### Expected Behavior

Ability to handle --force flags on resources that request it, ideally the config is pushed on apply. On Apply we have accepted the risk of a config failure through code review. 

### Additional Details

This recently came out so I am not surprised terraform doesn't support this change yet. But it would be awesome that we could push this change via terraform :)

FYI the setup is done practically copy paste in terraform from this config guide for setting up a Cloud Watch Destination. So an IAM role is attached to the resource above.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CreateDestination.html

More Details here:
https://aws.amazon.com/about-aws/whats-new/2022/01/amazon-cloudwatch-logs-aws-organizations-subscriptions/

**Comment by td4b** [comment]
FYI for anyone else seeing this behavior in the error log, it may be because an IAM role is missing (as the error log suggests). Will keep you posted on my findings here.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by td4b** [comment]
Thank you @jbardin :)
