### ISSUE TITLE
Moved block ignored

### ISSUE THREAD

**Issue by rkitron** [hashicorp/terraform#30306]
Hi,
 I have an issue with moved block; no errors from terraform plan/apply but the moved is ignored.

The moved block (root level):
`moved {
    from = module.ric-aws-eu-lab-host-nprd
    to = module.ric-aws-eu-lab-host-nprd-project-vertical
}
`

There are nested moved block, the moved block within the module:
`moved {
  from = module.project_roles
  to   = module.vertical_roles
}
`

The plan's output wants to destroy `module.ric-aws-eu-lab-host-nprd` and creates `module.ric-aws-eu-lab-host-nprd-project-vertical`.

[2022-01-06T12:06:58.008Z [TRACE].txt](https://github.com/hashicorp/terraform/files/7822073/2022-01-06T12.06.58.008Z.TRACE.txt)

Thanks in advance,

**Comment by jbardin** [comment]
Hi @rkitron,

Thanks for filing the issue. I can't be certain without the information requested in the issue template, but you do mention nested move blocks, so this is likely a duplicate of #30197. If that does not match your described problem, feel free to open new issue with the version information and a complete reproduction.

Thanks!
