### ISSUE TITLE
Terraform cannot be informed about all the resources creation

### ISSUE THREAD

**Issue by dpaliou** [hashicorp/terraform#30346]
### Terraform Version

```
v1.0.11
```

### Terraform Configuration Files

[main.tf](https://drive.google.com/file/d/1KB_YiUXs0eUcC4S5_x9raNJM8sy7Ge6A/view?usp=sharing)

### Issue Description 

We want to create 2 resources in the same terraform config file, specifically 2 "oci_database_db_system" (Oracle DBs). While they are successfully created, the Terraform isn't informed about the creation of the 1 out of the 2 DBs. 

### Expected Behavior

Both DBs should have been created correctly and Terraform should have been informed properly: that both DBs are up and running. 

### Actual Behavior

Both DBs are created as we can observe on the OCI administration page, but Terraform isn't properly informed. Terraform is informed for only 1 DB that is successfully created. For the other one, it waits until its healthcheck responds that is up, but it never happens. Despite this wrong update of Terraform about the status of DB creation, the DB is created successfully in time, but Terraform never is informed about it. 
So, a) the steps that we want to execute after this creation, are never executed. 
Moreover, the terraform.tfstate contains nothing related to the DB that is created but Terraform hasn't been informed about. 
So, b) the terraform destroy will never destroy this resource. 
 
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Additional Context

In the specific run, Terraform wans't informed about DB Rack creation. In other runs, it wasn't be informed about DB Single Node creation. So, it is randomly informed for only 1 successful creation.

The same issue is observed when we have 2 Single Nodes in the same config file, not only 1 Single Node and 1 Rack. Both DBs are created but Terraform is informed only for 1 out of the 2 resources. The Terraform randomly is informed for only 1 resource. 
Last but not least, when we create only 1 DB resource, we never observe any issue.

### Debug Output

- As you can see in the [output](https://drive.google.com/file/d/1QiFO_U5WEKGLhwoI0mW-ZlmgnsUNC1Zy/view?usp=sharing), "oci_database_db_system.terra_db_rack: Still creating... [1h25m1s elapsed]" despite the fact that the resource was already created by that time (can be observed on OCI admin page). But terraform wasn't be informed.

- As you can see in the [terraform.tfstate](https://drive.google.com/file/d/1jssBvheeRjS8Fa-oNbtOc-GcQXgY_jbr/view?usp=sharing) , the file doesn't contain any information about terra_db_rack _(any sensitive information was hidden)_.

- [Logs](https://drive.google.com/file/d/1K-kifsoudCHP5Fh6oV6bC1zEpYj50YT3/view?usp=sharing)

### References
Maybe [this issue](https://github.com/hashicorp/terraform-provider-vsphere/issues/104) is related

**Comment by jbardin** [comment]
Hi @dpaliou,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
