### ISSUE TITLE
Timestream iot rule missing for AWS

### ISSUE THREAD

**Issue by FrancoCorleone** [hashicorp/terraform#30343]
As stated in the title. Any plans for introducing timestream iot rule to terraform?

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by FrancoCorleone** [comment]
Thanks!
