### ISSUE TITLE
Replace Directives Break Standard `go install`

### ISSUE THREAD

**Issue by rwxrob** [hashicorp/terraform#30356]
Fails to install using standard `go install ...@latest` method.

```
$ go install github.com/hashicorp/terraform@latest
go install: github.com/hashicorp/terraform@latest (in github.com/hashicorp/terraform@v1.1.3):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by jbardin** [comment]
Hi @rwxrob,

Sorry if this has caused an issue for you. Yes, it is expected that a Go module must be installed from the source directory when it uses `replace` directives, and for that reason the only universal way to install a Go package is to checkout the source and run `go build` or `go install` from within the module.

Thanks!
