### ISSUE TITLE
databricks_mount resource unable to authenticate with US Gov Cloud API

### ISSUE THREAD

**Issue by aaronhurstB3** [hashicorp/terraform#30355]
The databricks_mount resource is unable to authenticate when communicating with the US Gov Cloud API.  I'm trying to create a Databricks Mount using the ABFS protocol against Azure Gen2 Data Lake storage.

I run the following Terraform:
resource "databricks_mount" "my_mount" {
  name       = "/myMount/"
  cluster_id = var.cluster_id
  abfs {
    client_id                          = var.client_id
    client_secret_scope         = var.secret_scope
    client_secret_key             = var.client_secret
    tenant_id                         = var.tenant_id
    container_name              = var.container_name
    directory                          = var.directory
    initialize_file_system        = false
    storage_account_name   = var.storage_account_name
  }
}

Terraform plan is successful and tells me that my resource will be created.

I instead get the following error:
**"Error: INVALID_STATE: Databricks could not access keyvault: https://myKeyVault.vault.usgovcloudapi.net/."**

I checked Key Vault access policies and my Databricks workspace has the access needed to perform the action.  The Databricks mount can be created from a Notebook in the Databricks workspace using the same Azure Service Principal as defined in the Terraform script.  However, the Terraform script errors.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
