### ISSUE TITLE
Issue azuread provider 2.15 - "URI must have a trailing slash when there is no path segment"

### ISSUE THREAD

**Issue by skeletonrush** [hashicorp/terraform#30364]
### Terraform Version

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0

```

### Terraform Configuration Files

```terraform
resource "azuread_application" "appreg" {
  display_name                   = "myapp"
  identifier_uris                = ["https://${local.default_aad_domain}/${local.default_as_domain}"]
  fallback_public_client_enabled = false
  prevent_duplicate_names        = true
  owners                         = ["3exxxxxxxxx"]
  web {
    redirect_uris = [
      "https://${local.default_as_domain}",
      "https://${local.default_as_domain}/.auth/login/aad/callback",
      "https://${local.default_as_domain}/auth.html"
    ]
  }
}
```

### Expected Behavior
App Registration on AAD should be successfully created when the redirect_uris of the "web" section have no trailing "slash", because:
1. such url "https://xxx/.auth/login/add/callback" is accepted by the Azure UI
2. when adding a trailing slash to the redirect_uris, the resource is created but the oidc login process fails because Azure App Service uses the following redirect_uri: "https://xxx/.auth/login/add/callback" (without trailing slash) and no match can be found with the configuration of the "app registration" in AAD. 

### Actual Behavior
Terraform plan fails with the following error:
╷
│ Error: URI must have a trailing slash when there is no path segment
│ 
│   with module.xxx[0].azuread_application.appreg,
│   on ../module/main.tf line 60, in resource "azuread_application" "appreg":
│   60:     redirect_uris = [
│   61:       "https://${local.default_as_domain}",
│   62:       "https://${local.default_as_domain}/.auth/login/aad/callback",
│   63:       "https://${local.default_as_domain}/auth.html"
│   64:     ]
│ 
╵

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Additional Context
None

### References

- [#642](https://github.com/hashicorp/terraform-provider-azuread/issues/642)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
