### ISSUE TITLE
Resource Ordering Issue when Referencing Data Source  

### ISSUE THREAD

**Issue by schwarzzz** [hashicorp/terraform#30365]
I’m using the `azurerm` provider and want to “connect” the resources of my configuration to a pre-existing resource in Azure. The pre-existing resource has a set of tags that makes it uniquely identifiable. I’m using a data source for getting resources in Azure and the refer to the `data` element. This element has a `resources` property which represents a list of all resources matching my criteria. In my scenario, it is guaranteed, that there will always be exactly one match.

When I introduce the data element and a referencing resource in the same change, the execution _sometimes_ fails. This looks like a resource ordering issue to me…

According to the `azurerm` project, resource ordering issues shall be reported here.

### Terraform Version
```
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.84.0
```

## Config A (required for preparation, only)

```terraform
resource "azurerm_resource_group" "logs" {
  name     = "rg-logs"
  location = "westeurope"
}

resource "azurerm_log_analytics_workspace" "instance" {
  name                = "logs-myapp"
  location            = azurerm_resource_group.logs.location
  resource_group_name = azurerm_resource_group.logs.name
  sku                 = "PerGB2018"
  retention_in_days   = 30

  tags = {
    "app" = "myApp"
    "resourceUsage" = "logs"
  }
}
```

## Config B

```terraform
resource "azurerm_resource_group" "my_app" {
  name     = "rg-my-app"
  location = "westeurope"
}

resource "azurerm_app_service_plan" "my_app" {
  name                = "api-my-app"
  location            = azurerm_resource_group.my_app.location
  resource_group_name = azurerm_resource_group.my_app.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

data "azurerm_resources" "log_anayltics_workspaces" {
  type = "Microsoft.OperationalInsights/Workspaces"

  required_tags = {
    "app" = "myApp"
    "resourceUsage" = "logs"
  }
}

resource "azurerm_monitor_diagnostic_setting" "analytics" {
  name               = "analytics"
  target_resource_id = azurerm_app_service_plan.my_app.id
  
  log_analytics_workspace_id = data.azurerm_resources.log_anayltics_workspaces.resources[0].id

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = false
    }
  }

  depends_on = [
    data.azurerm_resources.log_anayltics_workspaces
  ]
}

```

### Debug Output
I cannot share this; sorry.

### Expected Behavior
`terraform plan` and/or `terraform apply` of config B should succeed (if Config A has been applied before).

### Actual Behavior
`terraform plan` and/or `terraform apply` of config B _sometimes_ fail with the following error:

```
Error: Invalid index
# data.azurerm_resources.log_anayltics_workspaces.resources is empty list of object
# The given key does not identity an element in this collection value: the
# collection has no elements
```

Sometime, it helps to just re-run the configuration. Sometimes, I got stuck. The I manually executed a `terraform apply -target data.azurerm_resources.log_anayltics_workspaces`, and the issue was gone.

### Steps to Reproduce
I was not able to reproduce it in a minimal configuration. It only happens in a larger configuration (which I cannot share). I also cannot share a debug log from my actual configuration.
1.	Ensure that a resource as shown in configuration A exists
2.	Introduce the `data` element as well as another element referring to it (here: ` "azurerm_monitor_diagnostic_setting.analytics`) in a single change to configuration B
3.	Run `terraform plan` or `terraform apply` on configuration B

This happened multiple times to me now, while I'm extending my configuration using this "pattern".

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
