### ISSUE TITLE
AzureRM - Create role assignment with system assigned identity of data protection backup vault

### ISSUE THREAD

**Issue by yarashagarwal** [hashicorp/terraform#30370]
resource "azurerm_data_protection_backup_vault" "backupvault" {
  name                = "backupvault"
  resource_group_name = var.resourcegroup
  location            = var.location
  datastore_type      = "VaultStore"
  redundancy          = "LocallyRedundant"
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_role_assignment" "roleassignment01" {
  scope                = azurerm_storage_account.storageaccount.id
  role_definition_name = "Storage Account Backup Contributor Role"
  principal_id         = azurerm_data_protection_backup_vault.backupvault.identity.0.principal_id

   depends_on = [
    azurerm_data_protection_backup_vault.backupvault
    ]
}

│   on modules\storage\main.tf line 42, in resource "azurerm_role_assignment" "roleassignment01":
│   42:   principal_id         = azurerm_data_protection_backup_vault.backupvault.identity[0].principal_id
│     ├────────────────
│     │ azurerm_data_protection_backup_vault.backupvault.identity is empty list of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.

│ Error: Missing required argument
│
│   with module.storage.azurerm_role_assignment.roleassignment01,
│   on modules\storage\main.tf line 44, in resource "azurerm_role_assignment" "roleassignment01":
│   44:   principal_id         = azurerm_data_protection_backup_vault.backupvault.identity.0.principal_id
│
│ The argument "principal_id" is required, but no definition was found.

terraform -version
Terraform v1.1.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.12.0
+ provider registry.terraform.io/hashicorp/azurerm v2.92.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
