### ISSUE TITLE
aws_spot_fleet_request recreates every time

### ISSUE THREAD

**Issue by kleijnweb** [hashicorp/terraform#30374]
### Terraform Version
```
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.72.0
```

### Terraform Configuration Files

```terraform
resource "aws_spot_fleet_request" "ecs-spot-request" {
  iam_fleet_role                      = var.spot_role_arn
  target_capacity                     = var.target_capacity
  terminate_instances_with_expiration = true
  wait_for_fulfillment                = true
  allocation_strategy                 = "diversified"
  replace_unhealthy_instances         = true

  launch_specification {
    ami                         = var.ami
    instance_type               = var.instance_type
    iam_instance_profile        = var.instance_profile_name
    associate_public_ip_address = false
    monitoring                  = true
    user_data                   = "#!/bin/bash\necho ECS_CLUSTER=${var.name} >> /etc/ecs/ecs.config"
    vpc_security_group_ids      = [var.security_group_id]
    subnet_id                   = join(",", var.subnet_ids)
    tags                        = {
      Name : var.name
    }
  }
}

```

### Expected Behavior
No changes when applying repeatedly.

### Actual Behavior
Recreates fleet requests every time I ask apply. Other resources are detected as "fresh", only the spot requests are recreated.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
