### ISSUE TITLE
Missing terraform 1.1.4 version from terraform.io

### ISSUE THREAD

**Issue by AlessioCasco** [hashicorp/terraform#30378]
Hello

Just a heads up, it seems that the [latest release of terraform](https://github.com/hashicorp/terraform/releases/tag/v1.1.4) is missing from the main [terraform website](https://www.terraform.io/downloads)

A this time latest is still `v1.1.3`

**Comment by jbardin** [comment]
Thanks @AlessioCasco!

The website has been updated.
