### ISSUE TITLE
Error - google api : error 400 : Invalid argument to the service push config::oidc_token::service_account_email

### ISSUE THREAD

**Issue by cmohank** [hashicorp/terraform#30389]
Hi,
I am trying to create push subscription in GCP using terraform script. I need to provide the service account and audience in the script. I am using the below.

oidc_token {
service_account_email = "id-pubsub-push-svc@${var.project_id}.iam.gserviceaccount.com"
audience = "xxx"
}

But when applying it, I am getting error message saying that "google api : error 400 : Invalid argument to the service push config::oidc_token::service_account_email". Please let me know how to resolve it.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
