### ISSUE TITLE
Cannot import cloudwatch log group for EKS

### ISSUE THREAD

**Issue by antonisnyc94** [hashicorp/terraform#30396]
Hello im using terraform 0.14.11 and for some reason whenever i import an existing cloudwatch log group for EKS control plane logging im getting the following.

`terraform import module.eks-cluster.aws_cloudwatch_log_group.eks-logs "/aws/eks/eks-cluster/cluster"`

```
module.eks-cluster.aws_cloudwatch_log_group.eks-logs: Importing from ID "/aws/eks/eks-cluster/cluster"...
module.eks-cluster.aws_cloudwatch_log_group.eks-logs: Import prepared!
  Prepared aws_cloudwatch_log_group for import
module.eks-cluster.aws_cloudwatch_log_group.eks-logs: Refreshing state... [id=/aws/eks/eks-cluster/cluster]

Error: Missing required argument

The argument "address" is required, but was not set.
```

config within module

```
resource "aws_cloudwatch_log_group" "eks-logs" {
  name = "/aws/eks/${var.cluster-name}/cluster"
  #retention_in_days = var.eks-log-retention
}
```

any ideas?

Thanks,
Tony

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
