### ISSUE TITLE
TF init goes into infinite loop if referenced itself 

### ISSUE THREAD

**Issue by arunkillu** [hashicorp/terraform#30391]
Hi There,

module "cicd" {
  source = "./"
}

and if we run terraform init goes into an infinite loop. This can be a potential security issue. please add a fix to exit gracefully.

**Comment by jbardin** [comment]
Hi @arunkillu,

Can you please supply the version of Terraform and the host operating system you are using? 
If this is reproducible with a current release of Terraform, a sample of the output would also be helpful in diagnosing the issue.

Thanks!

**Comment by jbardin** [comment]
Closing since we have not heard back. If this can be reproduced with a current Terraform release, feel free to file a new issue with the requested information.

Thanks!
