### ISSUE TITLE
Have a imported resource type

### ISSUE THREAD

**Issue by moogly81** [hashicorp/terraform#30390]
### Use-cases
I'm refactoring a terraform module that is used many times. 
This use case is using aws_cloudwatch_log_group, but the feature request is for any type of tf resource.  
  - The v1 of my module does **not**  declare a  an `aws_cloudwatch_log_group`, however  AWS creates it automatically. 
  - The v2 of the module declares the `aws_cloudwatch_log_group` explicitly (This allows me to control parameters like `retention_period`). 
  - When upgrading the module version, the apply fails, because the log group already exists. I have to import it using `terraform import aws_cloudwatch_log_group XXXXX`. Then the apply succeeds. 

  - I have to do this 50 times ...

### Proposal
I would like to see a `imported` resource.  

```hcl
imported  {
  to = aws_cloudwatch_log_group.MyLogGroup
  param = XXXXXX
}

# I then declare my log_group, as a normal resource
resource "aws_cloudwatch_log_group" "MyLogGroup" {
  name = "XXXXXX"
}
```

When I apply, the behaviour would be the same as doing : 
```
terraform import aws_cloudwatch_log_group.MyLogGroup XXXXXX
terraform apply
```
 

_note : the mechanism is very similar to the `moved` resource_

**Comment by jbardin** [comment]
Hi @moogly81,

Thanks for filing the issue! We are tracking this proposed feature in #26364
