### ISSUE TITLE
Unable to install Terraform amd64 1.1.4 

### ISSUE THREAD

**Issue by avinash-sv** [hashicorp/terraform#30404]
Hi there,

team, I am trying to install latest version of terraform, which i downloaded from the site.

I unzip it and placed it in C:/apps

I added the path under system environment variables. 
 when i run below command on cmd
terraform -version
Terraform v1.0.0
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.1.4. You can update by downloading from https://www.terraform.io/downloads.html

I am unable to get this working to 1.1.4, the latest.

Please help.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
