### ISSUE TITLE
CLI docs should show double-dash and indicate legacy single-dash supported

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform#30422]
This might be an enhancement request, not sure. 

### Terraform Version

```
1.1
```

### Expected Behavior

Terraform supports long options (ie options where name is more than one character) with either single or double dash. Eg both `-auto-approve` and `--auto-approve` are supported. The latter has become the de facto standard past few years. Only older utilities like find still take single dash eg `find` only accepts `-name` not `--name`. 

The terraform docs should show examples with the modern double-dash style, and indicate that single-dash is still supported (likely for legacy reasons -- backward compatibility). 

### Actual Behavior

The terraform docs only show the older, single-dash CLI syntax. 

### Steps to Reproduce

Try any command that has arguments, and use double-dash instead of single, and it will work. 

### Additional Context

Based on terraform usage of the `cli` go package on github, it looks like this is actually built into the library, so it is not likely by chance that this works.

**Comment by jbardin** [comment]
Hi @schollii,

The `double-dash` standard you allude to is not something more modern. It is new in comparison to the POSIX single letter options, but it became predominant with the GNU coding standards which started in the 80s, along with the use of `getopt_long()`. (I'm probably glossing over some details I've forgotten there too).

 Terraform uses the `go` `flags` library, which always uses a _single_ dash for all flags. It was derived from a flags package used internally at Google, and follows the convention of many other options libraries, just not GNU-style ones. The library does accept a double dash for convenience, as that is a common pattern and is unambiguous in most cases, but the builtin help text will always show the single dash for all defined flags.
