### ISSUE TITLE
Error on terraform plan `was not found in the list of supported Azure Locations`

### ISSUE THREAD

**Issue by maheshbthapa** [hashicorp/terraform#30438]
### Terraform Version

```
>=2.90
```

### Terraform Configuration Files

```terraform
terraform {
 required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.90"
    }
  }
}

resource "azurerm_resource_group" "example" {
  name     = "resourceGroupExample"
  location = "westeurope"
}

resource "azurerm_frontdoor" "frontdoor" {
  name                                         = "frontdoor"
  resource_group_name              = azurerm_resource_group.example.name
  enforce_backend_pools_certificate_name_check = true
}
```

### Debug Output

**Error: "resourceGroupExample" was not found in the list of supported Azure Locations**

### Expected Behavior

`terraform plan` should have run without error.

### Actual Behavior

 It was working before and suddenly it didn't. I was using version >=2.90. Later I updated it to >=2.94, still same issue. 
 
 I later changed version to =2.93.1 which seem to work.

### Steps to Reproduce

`terraform init`
`terraform apply`
`terraform plan`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
