### ISSUE TITLE
Id must not be null 500 error

### ISSUE THREAD

**Issue by SrinivasanSE** [hashicorp/terraform#30435]
### Terraform Version

Terraform v1.1.4

### Terraform Configuration Files
...

### Debug Output
Error: Bad status 500: {
│   "code" : 500,
│   "message" : "id must not be null"
│ }
│ 
│   with module.detectors.module.detectors-bxo-PPDG.signalfx_detector.sfx-signals-openwalletsev-count,
│   on ../detectors/Branded Experience/PPDG/openwalletserv.tf line 2, in resource "signalfx_detector" "sfx-signals-openwalletsev-count":
│    2: resource "signalfx_detector" "sfx-signals-openwalletsev-count" {

### Expected Behavior
Terraform apply should run successfully

### Actual Behavior

Getting this error when we make any update to an existing detector. We able to fix the error by changing the detector id
resource "signalfx_detector" **[id]**. But when we make any changes to this newly created detector also we get the same error.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` -> fails here

### Additional Context

All our recent PRs from yesterday are failing with this issue. Please let us know how we can fix this.

### References
...

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
