### ISSUE TITLE
An auto-import feature idea

### ISSUE THREAD

**Issue by chrispytoes** [hashicorp/terraform#30432]
I'm guessing auto-importing of resources isn't a high priority just judging by the lack of anything I can find on it, but I think I thought of a simple way to add this without disturbing much else. I'm in no way qualified to understand if this is or isn't a good idea. I'm just curious if it would work, and if not, why?

My idea is to add an optional `import` block to resources to describe how the resource should be imported if it does not exist in state:
```
resource "something" "my_resource" {
  import {
    id = "<import id>" # Literal value, or variables existing before apply
  }
}
```
When planning/applying (or running a specific command to run imports?), if this resource does not exist in the state, Terraform could do a check against the given ID to see if it exists in the service, and import it if it does or prompt the user for consent first. If it does not exist in the state or service, then it would be created as usual. The import blocks can then be removed after imports are complete.

With this, not only would migrating existing infrastructure into Terraform be much easer, but this will also allow your state to "self-heal" if resources ever get mistakenly lost or moved around. It can also be used as a safety mechanism to explicitly "lock" resources that you know should never change and never be deleted.

**Edit**: As I'm re-reading this I'm realizing that resources in submodules would need to be dealt with as well somehow. Perhaps instead of putting the import block inside the resource, it could be separate like so:
```
import {
  resource = module.submodule.something.my_resource
  id = "<import id>"
}
```

**Comment by jbardin** [comment]
Hi @chrispytoes,

Thanks for filing the issue. We are tracking the feature of importing via configuration in #26364.
