### ISSUE TITLE
Hashicorp Ubuntu apt package -Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_xenial_main_binary-amd64_Packages

### ISSUE THREAD

**Issue by juralio-james** [hashicorp/terraform#30436]
Overview of the Issue
The terraform package is broken on Ubuntu which is causing any apt commands to fail.

Reproduction Steps
Follow the instructions from the Ubuntu/Debian installation guide.

`$ curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -`
`$ sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"`
`$ sudo apt-get update && sudo apt-get install terraform`

At this point you'll see output like
`Fetched 32.0 MB in 5s (5,922 kB/s)    `                        
`Reading package lists... Error!`
`E: Encountered a section with no Package: header`
`E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_xenial_main_binary-amd64_Packages`
`E: The package lists or status file could not be parsed or opened.`
`circleci@default-7837aa15-cbd6-4729-9d10-e0fce51bf7b2:~$ sudo apt-get update && sudo apt-get install terraform`
`Hit:1 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial InRelease`
`Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-updates InRelease`
`Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-backports InRelease`
`Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease              `
`Hit:5 https://apt.releases.hashicorp.com xenial InRelease              `        
`Reading package lists... Error!`
`E: Encountered a section with no Package: header`
`E: Problem with MergeList /var/lib/apt/lists/apt.releases.hashicorp.com_dists_xenial_main_binary-amd64_Packages`
`E: The package lists or status file could not be parsed or opened.`

Operating system and Environment details
Ubuntu 16.04.5 LTS (Xenial Xerus)

**Comment by jbaskeen** [comment]
Seeing this as well and +1'd, just noting this is not isolated to terraform...the issue occurs during `apt-get update`

**Comment by apakhomov** [comment]
same issue on bionic during apt -get update

**Comment by gene1wood** [comment]
I can confirm this began happening in the last couple days on Ubuntu 18.04 with the `https://apt.releases.hashicorp.com bionic InRelease` PPA

**Comment by apakhomov** [comment]
Problem is due to https://github.com/hashicorp/consul/issues/11162#issuecomment-1026137376

**Comment by bharvey-brt** [comment]
I also commented on [hashicorp/consul#11162](https://github.com/hashicorp/consul/issues/11162) but I'm experiencing this same issue.

**Comment by jbaskeen** [comment]
I think this can be closed now @juralio-james
