### ISSUE TITLE
SFTP support in Azure Blob Storage - Terraform support for SFTP management APIs

### ISSUE THREAD

**Issue by yashluna** [hashicorp/terraform#30442]
### Current Terraform Version

```
...
```

### Use-cases

Terraform support for SFTPI APIs in this [release](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fblob%2Fmain%2Fspecification%2Fstorage%2Fresource-manager%2FMicrosoft.Storage%2Fstable%2F2021-08-01%2Fstorage.json&data=04%7C01%7Cylunagaria%40microsoft.com%7Cc62e694702944a8a10bf08d9e1edc961%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637789233677868023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PN5vbqvaUaclgap%2FvekzZ03k5Ddl9Xcq32B86sHn5nU%3D&reserved=0).

Many customers participating in the preview for [Azure SFTP](https://docs.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-support) have requested Terraform support to be able to deploy Blob Storage accounts with SFTP enabled. They would also like support for local user (identity used for SFTP) management.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by yashluna** [comment]
What do you mean by an issue with AzureRM provider? Can you please explain?

I filed a feature request not a bug so not sure what issue is being referred.

Thanks,
Yash

**Comment by jbardin** [comment]
Resources deployed by Terraform are done so through providers, Terraform alone does not manage any cloud resources. Since Azure resources are mostly handled by the [AzureRM provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest), that is where I tried to direct you first. Feature requests for new or existing resources should go through the corresponding provider's project repository.

**Comment by yashluna** [comment]
Gotcha! How and where can I submit a request for AzureRM to support the new SFTP management APIs??

Thanks,
Yash
