### ISSUE TITLE
StateFunc should be allowed for computed values

### ISSUE THREAD

**Issue by marawan31** [hashicorp/terraform#30447]
According to the [upgrade guide](https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide#statefunc), the stateFunc should not be used with the computed fileds but, computed fields are indeed stored in the state when I run terraform.

Either we should not store the computed fields in the state or we should allow computed fields to override the stateFunc

**Comment by jbardin** [comment]
Hi @marawan31,

The `StateFunc` is part of the legacy plugin SDK which is maintained in the https://github.com/hashicorp/terraform-plugin-sdk repository. The reason for the error is what is described in the linked documentation, the behavior is undefined and generally meaningless for data that is not coming from an outside source. The internals of the plugin SDK are also mostly frozen for backwards compatibility, so changing their behavior is unlikely to be possible at this point. New development is happening in the [Terraform Plugin Framework](https://github.com/hashicorp/terraform-plugin-framework), which is designed to work directly against the new CLI plugin protocol

Thanks!
