### ISSUE TITLE
Terraform Error: Can't resolve Data Source is using Locals

### ISSUE THREAD

**Issue by jjperry** [hashicorp/terraform#30448]
### Terraform Version

```
1.1.4, 0.14.11, 0.15.5
```

### Terraform Configuration Files

kms.tf
```terraform
terraform {
  required_version = ">= 0.12"
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = ">= 3.50.0"
    }
  }
}

provider "aws" {
  region  = "us-east-1"
}
resource "aws_kms_key" "kmskey" {
  description             = "Foo KMS Key"
  deletion_window_in_days = 10
}
resource "aws_kms_alias" "my_alias" {
  name          = "alias/some_kms_alias"
  target_key_id = aws_kms_key.kmskey.key_id
}
locals {
  my_kms_alias = length(aws_kms_alias.my_alias.name) > 0 ? aws_kms_alias.my_alias.name : "empty"
}
module "foo" {
  source = "./foo"
  providers = {
    aws = aws
  }

  kms_key_alias = local.my_kms_alias
}
```
foo/test.tf
```terraform
variable "kms_key_alias" {}

data "aws_kms_alias" "my_key_alias" {
  name = var.kms_key_alias
}


terraform {
  required_version = ">= 0.14"
  required_providers {
    aws = {
      //source = "hashicorp/aws"
      version = ">= 3.50.0"
    }
  }
}
```
### Debug Output

$ terraform plan
╷
│ Error: error reading KMS Alias (alias/some_kms_alias): couldn't find resource
│
│   with module.foo.data.aws_kms_alias.my_key_alias,
│   on foo/test.tf line 3, in data "aws_kms_alias" "my_key_alias":
│    3: data "aws_kms_alias" "my_key_alias" {
│
╵

### Expected Behavior

Plan / Apply / Destroy should have resolved the locals variable and provided it to the `data "aws_kms_alias" "my_key_alias"` because the parent module is creating the resource passed to the child module.

### Actual Behavior

Plan and Apply fail with the above error. They do not appear to be trying to create the dependent resource required for the child module.  

### Steps to Reproduce

$ terraform init
$ terraform plan
* fails
$ terraform apply 
* fails 

### Additional Context

* It is assumed that the AWS credentials are setup, the AWS_PROFILE environment variable is properly set, and the AWS profile has the required permissions to access/create/delete aws_kms_key and aws_kms_alias. 

When recently setting up Terratest and upgrading existing Terraform modules in the code base, I hit this issue first when testing adding a vault secret to as K8S cluster.  For the apply, it got a the vault token from an AWS secret, got the needed data, accessed Vault to pull the secret, and created in the K8S cluster, as expected.  When the Terratest went to do the destroy, it failed on a error regarding the secret it had read from Vault to do the apply.   It gave a similar error to the above complaining about an error reading the data from the Vault secret. It did successfully destroy the K8S Vault secret.  The reference in the Vault data source was set using a local variable. If I hard-coded the value being derived from the local variable, the Vault data source did not fail. 

To work around the problem, in the Terratest module, I had to create a dummy secret. That had something for Vault to destroy, thus the child module was able to access the Vault data source. 

I dismissed the behavior as "quirky" and possibly linked to the Vault provider's code.

Today I had an AWS module failing with the above error. Again, it is trying to use a Local variable to decide whether to use the aws_kms_alias Resource, or default to name of "empty". If the resource kms_key_alias passed to the child module is set to ```

Based on the seen behaviors in two different providers, this appears to be an issue in the Terraform code.  

In troubleshooting this issue, I used multiple versions of Terraform including the latest available, and the error persists between versions. 

1. If `module "foo"` is commented out, Terraform will create the resources. 
2. Uncommenting `module "foo"` after resource creation does not cause the subsequent plan/apply/destroy to fail. 

The issue appears to be somewhere in the to dependency process where the data source in the child module is being checked before the dependent resource is created in the parent module.

Here is the graph from when I ran the module. 
```
digraph {
        compound = "true"
        newrank = "true"
        subgraph "root" {
                "[root] aws_kms_alias.my_alias (expand)" [label = "aws_kms_alias.my_alias", shape = "box"]
                "[root] aws_kms_key.kmskey (expand)" [label = "aws_kms_key.kmskey", shape = "box"]
                "[root] module.foo.data.aws_kms_alias.my_key_alias (expand)" [label = "module.foo.data.aws_kms_alias.my_key_alias", shape = "box"]
                "[root] provider[\"registry.terraform.io/hashicorp/aws\"]" [label = "provider[\"registry.terraform.io/hashicorp/aws\"]", shape = "diamond"]
                "[root] aws_kms_alias.my_alias (expand)" -> "[root] aws_kms_key.kmskey (expand)"
                "[root] aws_kms_key.kmskey (expand)" -> "[root] provider[\"registry.terraform.io/hashicorp/aws\"]"
                "[root] local.my_kms_alias (expand)" -> "[root] aws_kms_alias.my_alias (expand)"
                "[root] module.foo (close)" -> "[root] module.foo.data.aws_kms_alias.my_key_alias (expand)"
                "[root] module.foo.data.aws_kms_alias.my_key_alias (expand)" -> "[root] module.foo.var.kms_key_alias (expand)"
                "[root] module.foo.var.kms_key_alias (expand)" -> "[root] aws_kms_alias.my_alias (expand)"
                "[root] module.foo.var.kms_key_alias (expand)" -> "[root] module.foo (expand)"
                "[root] provider[\"registry.terraform.io/hashicorp/aws\"] (close)" -> "[root] module.foo.data.aws_kms_alias.my_key_alias (expand)"
                "[root] root" -> "[root] local.my_kms_alias (expand)"
                "[root] root" -> "[root] module.foo (close)"
                "[root] root" -> "[root] provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
        }
}
```

**Comment by jbardin** [comment]
Hi @jjperry,

Thanks for the very complete example demonstrating the issue. The observed behavior here is what is expected from Terraform, with the data source being read during the plan, which means that `aws_kms_alias` has yet to be created.

Data sources are read as early as possible in order to use their information elsewhere in the planning process. It is generally recommended to never have the same logical resource represented by both a managed resource and a data source within the same configuration for this reason. If the `foo` module needs information from the `aws_kms_alias` resource, that entire resource, or at least the subset of relevant attributes, should be passed into the module removing the need for the data source.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
