### ISSUE TITLE
Use variable in module source parameter

### ISSUE THREAD

**Issue by user-saik** [hashicorp/terraform#30441]
I want to have multiple modules that I pull from, but I will always want those to use same branch, within a project.
 
```
 prod_git_tag = "v.0.0.1"
 staging_git_tag = "v.0.5.7"
 git_repo_path="https://gitlab.com/project"
``` 

and use variables 

```
module "vpc" {
  source = "${git_repo_path}?ref=${git_tag}"
}

module "kubernetes-cluster" {
  source = "${git_repo_path}?ref=${git_tag}"
}

```

**Comment by apparentlymart** [comment]
Hi @user-saik,

Like most programming languages, Terraform needs to install all dependencies before evaluating the resulting program, and so dependency information like module and provider requirements can only be defined statically. This is similar to how in e.g. the NodeJS ecosystem you need to write your dependencies in the `package.json` file statically, and so can't decide to change the source of a dependency dynamically at runtime.

The ordering of first installing all of the modules and only then evaluating them is not something we will be able to change, and so your options here will either be to specify each module source separately, or to use some other software to update or generate the references systematically before you run Terraform.
