### ISSUE TITLE
backend/s3: Upgrade to `aws-sdk-go-base/v2`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform#30443]
The AWS provider will be upgrading to [`aws-sdk-go-base/v2`](https://github.com/hashicorp/aws-sdk-go-base) as part of v4.0. Upgrading to `aws-sdk-go-base/v2` will provide enhancements to the AWS authentication process and add consistency to the configuration of both the backend and the provider.

Note: Because `aws-sdk-go-base/v2` changes the authentication flow to be more in-line with the default flow for the AWS CLI and SDKs, this will be a multi-stage process over several releases of Terraform to prevent breaking changes. It will also require changes to `aws-sdk-go-base/v2` itself.

**Comment by FireballDWF** [comment]
Resolving is expected to resolve the current problem where an S3onOutposts bucket can't be used as the S3 bucket for backend/s3
