### ISSUE TITLE
v0.6.3 crash while using parameter_group_name = ["${aws_db_parameter_group.default.name}"]

### ISSUE THREAD

**Issue by psychicindian** [hashicorp/terraform#3044]
v0.6.3 crash while using parameter_group_name = ["${aws_db_parameter_group.default.name}"] in resource "aws_db_instance"

Crashlog: https://gist.github.com/catsby/16697c2fc0c938603a53

*Edited by @catsby to move crash log to a gist

**Comment by psychicindian** [comment]
parameter_group_name = "${aws_db_parameter_group.default.name}" is the supported config, but a crash was awkward

**Comment by catsby** [comment]
Same core issue as https://github.com/hashicorp/terraform/issues/2649

**Comment by catsby** [comment]
Thanks for opening the ticket @psychicindian – it's very similar to another one, hopefully we can get around to that in the near future. Sorry for the trouble!

**Comment by mitchellh** [comment]
Fixed in #2649

**Comment by alexng-canuck** [comment]
Has the panic itself been fixed? From my understanding, the panic was avoided by changing the config to avoid passing lists into string attributes. But Terraform should catch such type mismatches and give an error rather than to panic.
