### ISSUE TITLE
Way to have module variable use defautl value if user supplies null. 

### ISSUE THREAD

**Issue by tmccombs** [hashicorp/terraform#30459]
### Current Terraform Version

```
Terraform v1.1.3
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.1.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use-cases

An input to a module A  has a default value, and that module is then used by another module B which passes it's own variable through to module A that is itself optional, or maybe the input comes from a local that is computed and may either be a specific value or null to use the default. In either case, it may be desirable for a value of `null` to use the default value rather than passing  an actual null value which may cause an error if the inner module doesn't expect a null value.

The fact that pasing a null value to a module is different than not passing any value for an optional input is also inconsistent with how passing a null value to a resource works (where it behaves the same as not passing anything).

### Attempted Solutions

There a re a couple ways to work around this: one is to change the inner module to use `coalesce` or similar to use the default value if the input is null, which either requires duplicating the default value in the variable definition and usage location, or losing the self-documented default value and using a dummy default value of null.  The other is to change the place calling the module to pass in the default value of the module explicitly if the default value should be used (possibly using `coalesce` or similar). But again the default value must be duplicated. Both options are rather awkward to use.

### Proposal

Since changing how passing null to a module variable behaves would be backwards incompatible. I propose adding a new attribute on variable declarations that would specify that if the supplied value is null, then the default value should be used. Maybe something like:

```hcl
variable "my_var" {
   type = number
   default = 200
   default_if_null = true
 }
 ```
 
 Alternatively, have some way to conditionally specify an attribute on a module. Something like a dynamic block, but for attributes instead of blocks.

**Comment by jbardin** [comment]
Hi @tmccombs,

Thanks for filing the issue. I believe you are describing non-nullable input variable, controlled by the `nullable` variable argument: https://www.terraform.io/language/values/variables#disallowing-null-input-values.

**Comment by tmccombs** [comment]
Oh awesome! Somehow I missed that. Thank you!
