### ISSUE TITLE
openstack_blockstorage_volume_v1 need pending creatingstate

### ISSUE THREAD

**Issue by guanglinlv** [hashicorp/terraform#3045]
Hi,

when i use `openstack_blockstorage_volume_v1` to create a volume resource, terraform give `Error waiting for volume (xxxxx) to become ready: unexpected state 'creating', wanted target 'available'`,terraform should be pending volume creating state. [resource_openstack_blockstorage_volume_v1.go#L138](https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_blockstorage_volume_v1.go#L138)

thanks.

**Comment by jtopjian** [comment]
@guanglinlv @berendt FYI: #3224. 

Regarding the configurable "timeout", it would be nice to be able to set this value, but the values are hard-coded for all other Terraform resources.

**Comment by berendt** [comment]
LGTM

**Comment by jtopjian** [comment]
Closing this issue as it was fixed in #3224, but let me know if anyone still runs into problems.
