### ISSUE TITLE
data google_compute_instance_template can't get provider's project

### ISSUE THREAD

**Issue by nightwatch92** [hashicorp/terraform#30464]
### Terraform Version

```
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.9.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "4.9.0"
    }
  }
}


provider "google" {
  project = "a_project"
  region  = "us-central1"
}

terraform {
  backend "gcs" {
    bucket = "somebucket"
    prefix = "myprefix"
  }
}

data "google_compute_instance_template" "generic" {
  filter      = "name :*"
  most_recent = true
}
```

### Expected Behavior

Should use the project variable from the provider. From docs [project](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_instance_template#project) - (Optional) The ID of the project in which the resource belongs. If project is not provided, the provider project is used.
### Actual Behavior

```
→ terraform plan
╷
│ Error: Missing required argument
│ 
│   on main.tf line 25, in data "google_compute_instance_template" "generic":
│   25: data "google_compute_instance_template" "generic" {
│ 
│ The argument "project" is required, but no definition was found.

```
project should be defined as variable in data google_compute_instance_template
### Steps to Reproduce

`terraform init`
`terraform plan`

### References

https://github.com/hashicorp/terraform-provider-google/blob/809c30d7537e342a4700894a0075542777e12086/google/data_source_google_compute_instance_template.go#L26
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_instance_template#project

### Possible solution

```go
diff --git a/google/data_source_google_compute_instance_template.go b/google/data_source_google_compute_instance_template.go
index 84ec12501..16561648f 100644
--- a/google/data_source_google_compute_instance_template.go
+++ b/google/data_source_google_compute_instance_template.go
@@ -22,8 +22,10 @@ func dataSourceGoogleComputeInstanceTemplate() *schema.Resource {
                Optional: true,
        }
 
-       // Set 'Required' schema elements
-       addRequiredFieldsToSchema(dsSchema, "project")
+       dsSchema["project"] = &schema.Schema{
+               Type:     schema.TypeString,
+               Optional: true,
+       }
 
        // Set 'Optional' schema elements
        addOptionalFieldsToSchema(dsSchema, "name", "filter", "most_recent")
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
