### ISSUE TITLE
Terraform 1.1.x reporting "Objects have changed outside of Terraform" when they have not been

### ISSUE THREAD

**Issue by DrStrangepork** [hashicorp/terraform#30468]
### Terraform Version

```
Terraform v1.1.4
```

### Terraform Configuration Files

dashboard-assume.tpl:
```terraform
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::123456789011:root",
          "arn:aws:iam::123456789012:root",
          "arn:aws:iam::123456789013:root",
          "arn:aws:iam::123456789014:root"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
main.tf:
```terraform
data "template_file" "dashboard-role-trusted" {
  template = file("${path.module}/dashboard-assume.tpl")
}

resource "aws_iam_role" "dashboard-read-only-role" {
  name                 = "${var.name}-role"
  max_session_duration = 43200
  assume_role_policy   = data.template_file.dashboard-role-trusted.rendered
  tags                 = merge(var.tags, { "aws_iam_permission_boundary_exempt" = "true" })
}
```

### Expected Behavior

`terraform plan` should report no changes, since there were no changes

### Actual Behavior

```
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.dashboard_role.aws_iam_role.dashboard-read-only-role has changed
  ~ resource "aws_iam_role" "dashboard-read-only-role" {
      ~ assume_role_policy    = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = [
                              - "arn:aws:iam::123456789011:root",
                                "arn:aws:iam::123456789012:root",
                              + "arn:aws:iam::123456789011:root",
                                "arn:aws:iam::123456789013:root",
                                # (1 unchanged element hidden)
                            ]
                        }
                        # (2 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        id                    = "dashboard-cross-account-role"
        name                  = "dashboard-cross-account-role"
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
All that is reflected here is a change in the order of the principals, but the change proposed by terraform is NOT the actual order of the _assume_role_policy_ of the role, and neither the policy nor the role have changed outside of terraform. This is happening _at random_ to 3 different roles on any given run of `terraform plan`, and even after `terraform apply -no-color -lock=false -input=false -auto-approve -refresh-only ./plan` is executed, these role policies continue to come up, still reflecting changes that are NOT the actual status of the policy.

**Comment by DrStrangepork** [comment]
This problem occurs with Terraform v1.1.5 as well

**Comment by DrStrangepork** [comment]
From the tfstate file:
```
{
  "module": "module.dashboard_role",
  "mode": "data",
  "type": "template_file",
  "name": "dashboard-role-trusted",
  "provider": "provider[\"registry.terraform.io/hashicorp/template\"]",
  "instances": [
    {
      "schema_version": 0,
      "attributes": {
        "filename": null,
        "id": "e993276b5966a7bc59cb41f1956bd785473cd43cb093206fda8062754734a09d",
        "rendered": "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"AWS\": [\n          \"arn:aws:iam::123456789011:root\",\n          \"arn:aws:iam::123456789012:root\",\n          \"arn:aws:iam::123456789013:root\",\n          \"arn:aws:iam::123456789014:root\"\n        ]\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}\n",
        "template": "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"AWS\": [\n          \"arn:aws:iam::123456789011:root\",\n          \"arn:aws:iam::123456789012:root\",\n          \"arn:aws:iam::123456789013:root\",\n          \"arn:aws:iam::123456789014:root\"\n        ]\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}\n",
        "vars": null
      },
      "sensitive_attributes": []
    }
  ]
},
```
As you can see, the data in the tfstate file correctly reflects the contents of the template, however the actual role trust relationship policy is this:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::123456789014:root",
          "arn:aws:iam::123456789013:root",
          "arn:aws:iam::123456789012:root",
          "arn:aws:iam::123456789011:root"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
which does NOT correctly reflect the contents of the template. So I can't determine the source of the discrepancy. None of this is being changed outside of terraform.

**Comment by apparentlymart** [comment]
Hi @DrStrangepork! Thanks for reporting this.

It looks like what you are seeing here is the AWS provider issue represented by hashicorp/terraform-provider-aws#19727, which is that various AWS APIs don't preserve the ordering of elements in IAM policies, and that the AWS provider is incorrectly classifying that situation as a change to the meaning of the object rather than as just a normalization where the new value has equivalent meaning to what you entered.

Terraform Core relies on providers to detect and report the difference between a meaningful change and a normalization change like this, and so when a provider misclassifies a change Terraform CLI will report that incorrect classification in the UI. To address this, the provider will need a new rule to notice when the set of principals has all the same members but a different order, and to report it to Terraform Core as unchanged in that case.

Since there's already an AWS provider issue tracking this problem, I'm going to close this one just to consolidate the discussion. Thanks!
