### ISSUE TITLE
aws_kinesis_stream - cannot switch between PROVISIONED and ON_DEMAND mode

### ISSUE THREAD

**Issue by gaboraron** [hashicorp/terraform#30466]
### What is the problem?
Switching between PROVISIONED and ON_DEMAND capacity mode fails.

### Reproduction Steps 
Having an already deployed aws_kinesis_stream resource with 
```
shard_count = 1
stream_mode_details {
    stream_mode = "PROVISIONED"
}
```
change it to 
```
shard_count = null
stream_mode_details {
    stream_mode = "ON_DEMAND"
}
```
and try to deploy.

### What did you expect to happen?
Deployment succeed and the Kinesis stream capacity mode is updated accordingly.

### What actually happened?
The deployment failed with the following error message:

> Error: shard_count must not be set when stream_mode is ON_DEMAND

### Versions
terraform: 1.0.9
hashicorp/aws: v3.63.0

### Other information
Switching between ON_DEMAND and PROVISIONED also fails. This time claiming that no shard_count is specified even though it is.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
