### ISSUE TITLE
AWS S3 Bucket - Possible Bug?

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform#3046]
I am trying to start managing my S3 buckets using TF, currently I have the following code:

```
resource "aws_s3_bucket" "b" {
    bucket = "digit-test-bucket"
    acl = "private"
    region = "us-east-1"
}
```

As you can see, I am setting the region to **us-east-1**. I get the output from Terraform as follows:

```
s3 [master●] % terraform apply 
aws_s3_bucket.b: Creating...
  acl:              "" => "private"
  bucket:           "" => "digit-test-bucket"
  force_destroy:    "" => "0"
  hosted_zone_id:   "" => "<computed>"
  region:           "" => "us-east-1"
  website_domain:   "" => "<computed>"
  website_endpoint: "" => "<computed>"
aws_s3_bucket.b: Creation complete
```

Again, as you can see, the region is **us-east-1**

When i go to the AWS console, I see the following:

<img width="405" alt="screen shot 2015-08-21 at 11 14 54" src="https://cloud.githubusercontent.com/assets/227823/9406170/fe7c78c4-47f5-11e5-9ac5-7d4d93f7f498.png">

Is this a bug in Terraform?

Paul

**Comment by radeksimko** [comment]
I reckon this is because aws provider has `eu-west-1` (i.e. Ireland). The `region` is actually marked as `Optional: true` in the code, but is really always `Computed` - taken from the provider.

I'd widen this problem a little bit - most AWS resources take the region from provider and don't allow defining different one per resource (which is contrary to e.g. Google provider), I feel almost all AWS resources should have `region` as `Optional` (and actually reflected), by default taken from provider.

**Comment by stack72** [comment]
@radeksimko so that is *really* interesting.

```
s3 [master●] % tree
.
├── makefile
├── terraform.tfstate
├── terraform.tfvars
└── test_for_ireland.tf
```

tfvars file looks as follows:

```
aws_access_key=""
aws_secret_key=""
```

makefile has this

```
plan:
	terraform plan -refresh=true -input=false -backup=-

apply:
	terraform apply -input=false -backup=-
```

tfstate looks like this

```
{
    "version": 1,
    "serial": 1,
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {
                "aws_s3_bucket.b": {
                    "type": "aws_s3_bucket",
                    "primary": {
                        "id": "digit-test-bucket",
                        "attributes": {
                            "acl": "private",
                            "bucket": "digit-test-bucket",
                            "force_destroy": "false",
                            "hosted_zone_id": "Z1BKCTXD74EZPE",
                            "id": "digit-test-bucket",
                            "policy": "",
                            "region": "eu-west-1",
                            "tags.#": "0",
                            "website.#": "0"
                        }
                    }
                }
            }
        }
    ]
}
```

The hosted_zone_id is Ireland and the region is eu-west-1

Thanks for the explanation here. I'm really hoping that multi-region becomes a thing soon...

**Comment by radeksimko** [comment]
@stack72 I'm sure there's a provider somewhere in that directory, otherwise Terraform would error w/ out it.

> I'm really hoping that multi-region becomes a thing soon...

You can do multi-region now via provider aliases. It's a bit more verbose, but it is totally possible:

```ruby
provider "aws" {
  alias = "eu"
  region = "eu-west-1"
}
provider "aws" {
  alias = "us"
  region = "us-east-1"
}
resource "aws_s3_bucket" "a" {
    provider = "aws.us"
    bucket = "digit-test-bucket-in-us"
    acl = "private"
}
resource "aws_s3_bucket" "b" {
    provider = "aws.eu"
    bucket = "digit-test-bucket-in-eu"
    acl = "private"
}
```

See full example w/ aliases here: https://github.com/hashicorp/terraform/blob/master/examples/aws-s3-cross-account-access/main.tf

**Comment by stack72** [comment]
yeah i know you can do that - I have over 500 resources. I don't want to duplicate them for each provider :)

I'd like to be able to declare a list of regions and then TF do that for me

**Comment by stack72** [comment]
I'm going to close this - this is definitely *not* an S3 error
