### ISSUE TITLE
Importing for_each resources that is numbers

### ISSUE THREAD

**Issue by jkupidura14** [hashicorp/terraform#30489]
When creating resources from a list of strings that are numbers, you cannot import them into the state file because terraform removes the quotes around the number during import. In this case, I have clients that are represented by numbers in a set a strings that I iterate through using a for_each loop. Since all of these already exist and I cannot remove them, I need to import them into the statefile. When importing them, even with the quotes around the index, it removes it making it just a number in the bracket so a plan then wants to destroy and recreate it every time.

### Terraform Version

```
1.0.1
```

### Terraform Configuration Files

```terraform
resource "aws_ssm_parameter" "payment_methods" {
  for_each = var.payment_methods
  name     = "/SCRUBBED/${each.key}"
  type     = "SecureString"
  key_id   = aws_kms_key.default.arn
  value    = var.payment_method_value[each.key]

  tags = local.tags

  lifecycle {
    ignore_changes = [value]
  }
}

payment_methods = ["101","103","105","108","112","113","114"]

```

### Debug Output

Using the terraform import command:

terraform import aws_ssm_parameter.payment_methods["114"] /SCRUBBED/114

aws_ssm_parameter.payment_methods[114]: Importing from ID "/SCRUBBED/114"...
aws_ssm_parameter.payment_methods[114]: Import prepared!
  Prepared aws_ssm_parameter for import
aws_ssm_parameter.payment_methods[114]: Refreshing state... [id=/SCRUBBED/114]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

Following terraform plan:

 # aws_ssm_parameter.payment_methods[114] will be destroyed
  - resource "aws_ssm_parameter" "payment_methods" {
      - arn       =SCRUBBED
      - data_type = "text" -> null
      - id        = SCRUBBED
      - key_id    = SCRUBBED
      - name      = "/SCRUBBED/114" -> null
      - tags      = {
          - SCRUBBED
        } -> null
      - tier      = "Standard" -> null
      - type      = "SecureString" -> null
      - value     = (sensitive value)
      - version   = 1 -> null
    }

# aws_ssm_parameter.payment_methods["114"] will be created
  + resource "aws_ssm_parameter" "payment_methods" {
      + arn       = (known after apply)
      + data_type = (known after apply)
      + id        = (known after apply)
      + key_id    = (known after apply)
      + name      = "SCRUBBED"
      + tags      = {
          + SCRUBBED
        }
      + tier      = "Standard"
      + type      = "SecureString"
      + version   = (known after apply)
    }

### Expected Behavior

It should have imported the 114 with quotes.

### Actual Behavior

It dropped the quotes around 114 since it thinks its a number, making it not match when running a plan afterwards.

### Steps to Reproduce

See debug steps that includes the import command used along with the terraform configuration above. Make sure that var is a set(string) or map (both have the same output). Then try to import it into a statefule.

### Additional Context

No wrapper system or anything unusual. State file is in s3 but I dont believe that to be the issue.

### References

None

**Comment by jbardin** [comment]
Hi @jkupidura14,

When passing the argument `aws_ssm_parameter.payment_methods["114"] /SCRUBBED/114` to terraform, most shells will remove the quotes leaving you with the numerical value `114` as the index for the resource instance. If you want literal quotes in the argument, you must escape them accordingly for your particular shell, in most Bourne compatible shells the easiest method is to surround the argument with single quotes.

```
$ terraform import 'aws_ssm_parameter.payment_methods["114"] /SCRUBBED/114'
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
