### ISSUE TITLE
Include PassedProviderConfig information in JSON output format.

### ISSUE THREAD

**Issue by nozaq** [hashicorp/terraform#30480]
### Current Terraform Version

```
Terraform v1.1.5
on linux_amd64
```

### Use-cases

I'm working on a tool to visualize the resource structure by analyzing [the JSON output](https://www.terraform.io/internals/json-format) produced from `terraform show -json` command, and would like to identify which provider to be used for each resource.

Suppose we have the following tf file.

```hcl
provider "null" {
  alias = "provider_1"
}

provider "null" {
  alias = "provider_2"
}

module "a" {
  providers = {
    null = null.provider_1
  }

  source = "./modules/foo"
}

module "b" {
  providers = {
    null = null.provider_2
  }

  source = "./modules/foo"
}
```

Running `terraform plan -out plan.out` and `terraform show -json plan.out` will produce the JSON output. The resulting JSON contains the following provider configurations in `configuration.provider_config`.

- null
- null.provider_1
- null.provider_2
- module.a:null
- module.b:null

The issue is that the result does not contain the relations between these providers, so we can't identify that `null.provider_1` is assigned to `module.a:null` as well as `null.provider_2` is assigned to `module.b:null`.

For example, when using [AWS provider](https://github.com/hashicorp/terraform-provider-aws) multiple providers could be defined in one project and each work for a different AWS region. In such case, currently we can not identify in which region the specific resource in a child module would be created from analyzing the JSON output.

### Attempted Solutions

I've created [a repo](https://github.com/nozaq/tmp-json-output-demo) containing all sample code and [the actual JSON output file](https://github.com/nozaq/tmp-json-output-demo/blob/main/plan.json).

### Proposal

Include `PassedProviderConfig` defined in [ModuleCall struct](https://github.com/hashicorp/terraform/blob/d1ac8b71d4c1d6cfae4c250454a1c6f893a31231/internal/configs/module_call.go#L14) into `configuration.module_calls` block of [the JSON output](https://www.terraform.io/internals/json-format) so that tools can infer which provider is actually passed to child modules.

```json
{
  ...
  "configuration": {
    ...
    "module_calls": {
      "child": {
        ...
        "passed_provider_config": {
          "in_child": {
            "name": <provider-name-in-child>,
            "alias": <provider-alias-in-child>
          },
          "in_parent": {
            "name": <provider-name-in-parent>.
            "alias": <provider-alias-in-parent>
          }
        }
      }
    }
  }
}
```

**Comment by apparentlymart** [comment]
Hi @nozaq! Thanks for reporting this.

I think you've reported the same underlying problem as #30113 here, and so I'm going to close this to consolidate the discussion over there. There's already a pending PR to address this issue (albeit in a slightly different way than you proposed) and I believe it's only now pending some coordinated updates in other parts of the Terraform product which consume this JSON output.

Thanks again!
