### ISSUE TITLE
backend/s3: Add multiple credentials and config files parameters

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform#30493]
The AWS SDK for Go v2 allows passing multiple shared credentials and shared config files. Note that the corresponding environment variables, `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` accept single files only.

1. Document support for both environment variables
2. Add parameter `shared_credentials_files`
3. Add parameter `shared_config_files`
4. Deprecate `shared_credentials_file`

Depends on #30443

**Comment by kmoe** [comment]
Thanks, this looks reasonable.
