### ISSUE TITLE
latest_restorable_time in ignore_changes block doesn't work in terraform 1.1.5

### ISSUE THREAD

**Issue by esteban1983cl** [hashicorp/terraform#30509]
### Terraform Version

```
$ terraform --version
Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.14.0
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.8.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Terraform Configuration Files

Related to this link https://github.com/terraform-aws-modules/terraform-aws-rds/issues/375

### Expected Behavior

Resources with latest_restorable_time or any in ignore_changes block must disappear from terraform plan output

### Actual Behavior

We can see resources with latest_restorable_time attribute with changes in terraform plan output

```shell
# module.admincupones_giftcard-rds.module.db_instance.aws_db_instance.this[0] has changed
  ~ resource "aws_db_instance" "this" {
        id                                    = "[MASKED]"
      ~ latest_restorable_time                = "2022-02-10T18:44:30Z" -> "2022-02-10T18:54:31Z"
        name                                  = "[MASKED]"
        # (50 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

```shell
rm -rf .terraform/
terraform init
terraform validate
terraform plan
terraform apply
terraform plan
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. This particular issue is would be covered by https://github.com/hashicorp/terraform-provider-aws/issues/19727, so I'm going to close this one.

 If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
