### ISSUE TITLE
No able to delete google_vertex_ai_featurestore resource

### ISSUE THREAD

**Issue by kiumarskamyab** [hashicorp/terraform#30501]
Hi, I am trying to remove a featurestore from my gcp project by commenting out the creation of it on my terraform file.
Terraform will pick the deletion action but it throws the exception as in the attached file.
[error.txt](https://github.com/hashicorp/terraform/files/8034961/error.txt)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
