### ISSUE TITLE
Add optional subscription_id in data sources.

### ISSUE THREAD

**Issue by hsalluri259** [hashicorp/terraform#30504]
### Current Terraform Version
```
Terraform v1.0.0
```

### Use-cases
I have the following use case. I need to read Azure Log Analytics workspace keys and create a kubernetes secret. My problem here is, I have like  100 log analytics workspaces with all of them in different subscriptions. I have access to read log analytics keys only.

### Attempted Solutions
```
provider "azurerm" {
  features {}
  alias = "cpe"
  subscription_id = "0000-0000-0000"
}
data "azurerm_log_analytics_workspace" "ala_keys" {
  provider = azurerm.cpe
  name = "cpe-laworkspace"
  resource_group_name = "cpe-laworkspace-rg"
}

Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '9ca0af5b-3c67-4757-96ed-6bd941483a00' with object id '9ca0af5b-3c67-4757-96ed-6bd941483a00' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/04898e0e-c649-47de-bd3e-a747870a60ac' or the scope is invalid. If access was recently granted, please refresh your credentials."
│
│   with module.provision_ala_logging.provider["registry.terraform.io/hashicorp/azurerm"].devcom,
│   on ala_logging/main.tf line 42, in provider "azurerm":
│   42: provider "azurerm" {
│
```
This error is expected because I don't have read access over /subscriptions/04898e0e-c649-47de-bd3e-a747870a60ac. I only have read access on  log analytics workspace resource created inside the subscription.

### Proposal
```
data "azurerm_log_analytics_workspace" "ala_keys" {
  subscription_id = "00000-000-000"
  name = "amap-intcusa-hdmaps-laworkspace"
  resource_group_name = "amap-intcusa-hdmaps-laworkspace-rg"
}
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
