### ISSUE TITLE
Dynamically create AWS S3 buckets in multiple regions.

### ISSUE THREAD

**Issue by YuriGal** [hashicorp/terraform#30510]
Is there a way to create `aws_s3_bucket` resources dynamically in different regions? Argument `region` is no longer supported, creating provider aliases in different regions dynamically is also not supported. Is there a way to do this?

**Comment by jbardin** [comment]
Hello @YuriGal,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
