### ISSUE TITLE
Terraform provides no way to declare unset variables to modules

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#30515]
### Use-cases
A module with many variables, will need to have those declared in the root module calling it.
For variables that have sane and expected default values set in the module, the root module still has to declare all of those, making the life of us practitioners much harder, since those will need to be updated in all root modules, not a single place.
The use of `null`, which would be expected to state is it not set in the root module, is actually overriding the module default.

repro https://github.com/FernandoMiguel/alice-and-bob-unset-null/tree/main

### Proposal
Although this can be considered a breaking change, this is in fact a bug and a serious limitation, preventing practitioners from DRY code.
Ideally, root module variables should be able to be declared but not set, and the graph assuming the upstream default value.
Maybe a `default_if_null` kinda situation, so the module default would take precedence. 

### References
closed ticket that has further discussion https://github.com/hashicorp/terraform/issues/24142

**Comment by FernandoMiguel** [comment]
@jbardin after reading the docs, it was not clear to me.
Eventually I ran a few more tests on this with `nullable`
https://github.com/FernandoMiguel/alice-and-bob-unset-null/blob/a4b3b5fbc4e53f71d149cd937fa23757d71a061f/README.md?plain=1
and this achieves the behaviour I expect, when I set `nullable=false` in the module.

I think the docs may need a bit more clarifying. most would expect the default behaviour `nullable=true` would be the behaviour i described, but it's actually `false` that does that.

**Comment by jbardin** [comment]
I'm not certain how to improve the docs, bu tI can have our technical writer take a look at it. `nullable=true` is the current default if it's not set in the config, which basically means that a `null` value can assigned to the variable overriding the default. Setting `nullable=false` means that the value cannot be `null`, so it must take the default if `null` is assigned.

You can see some more examples in the PR which closed the linked issue: #29832

Thanks!

**Comment by FernandoMiguel** [comment]
@apparentlymart had this to say in slack, which kinda made sense to me
> nullable = false means "make sure this can never be null", which for a variable with a default value makes it take on that default, and for without a default value makes null an error
