### ISSUE TITLE
No Changes but terraform is trying to recreate resources

### ISSUE THREAD

**Issue by anagas** [hashicorp/terraform#30514]
Hello

I have an issue that nothing has changed but terraform is still trying to delete and create these resources.  The only thing i have changed is the locals and adding a dynamic resource to peering. Terraform says there are a lot of resources that changed but when I check the resources I can not see any changes. 

I think it has something to do with the dynamic resource but then i would expect that the peering has to be recreated not the tunnels.

This is the output:

 "Terraform used the selected providers to generate the following execution",
      "plan. Resource actions are indicated with the following symbols:",
      "  + create",
      "  ~ update in-place",
      "-/+ destroy and then create replacement",
      " <= read (data resources)",
      "",
      "Terraform will perform the following actions:",
      "",
      "  # module.gke.null_resource.ipmasquerade will be created",
      "  + resource \"null_resource\" \"ipmasquerade\" {",
      "      + id = (known after apply)",
      "    }",
      "",
      "  # module.project.google_compute_project_metadata_item.enable-guest-attributes will be created",
      "  + resource \"google_compute_project_metadata_item\" \"enable-guest-attributes\" {",
      "      + id      = (known after apply)",
      "      + key     = \"enable-guest-attributes\"",
      "      + project = \"x-sandbox-sz1\"",
      "      + value   = \"TRUE\"",
      "    }",
      "",
      "  # module.project.google_compute_project_metadata_item.enable-osconfig will be created",
      "  + resource \"google_compute_project_metadata_item\" \"enable-osconfig\" {",
      "      + id      = (known after apply)",
      "      + key     = \"enable-osconfig\"",
      "      + project = \"x-sandbox-sz1\"",
      "      + value   = \"TRUE\"",
      "    }",
      "",
      "  # module.vpn-tunnel-ha.data.google_compute_ha_vpn_gateway.ha_gateway_host will be read during apply",
      "  # (config refers to values not yet known)",
      " <= data \"google_compute_ha_vpn_gateway\" \"ha_gateway_host\"  {",
      "      + description    = (known after apply)",
      "      ~ id             = \"projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/vpnGateways/vpn-gw-sz-gc-zh-nic7\" -> (known after apply)",
      "        name           = \"vpn-gw-sz-gc-zh-nic7\"",
      "      ~ network        = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/global/networks/fwl-sz-gc-zh-backend-nic7-vpc\" -> (known after apply)",
      "      ~ self_link      = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/vpnGateways/vpn-gw-sz-gc-zh-nic7\" -> (known after apply)",
      "      ~ vpn_interfaces = [",
      "          - {",
      "              - id         = 0",
      "              - ip_address = \"x.x.x.x\"",
      "            },",
      "          - {",
      "              - id         = 1",
      "              - ip_address = \"x.x.x.x\"",
      "            },",
      "        ] -> (known after apply)",
      "        # (2 unchanged attributes hidden)",
      "    }",
      "",
      "  # module.vpn-tunnel-ha.data.google_compute_network.host_project will be read during apply",
      "  # (config refers to values not yet known)",
      " <= data \"google_compute_network\" \"host_project\"  {",
      "      ~ description            = \"SZ Firewall Backend nic7\" -> (known after apply)",
      "      + gateway_ipv4           = (known after apply)",
      "      ~ id                     = \"projects/x-netzwerk-hostvpc-prod1/global/networks/fwl-sz-gc-zh-backend-nic7-vpc\" -> (known after apply)",
      "        name                   = \"fwl-sz-gc-zh-backend-nic7-vpc\"",
      "      ~ self_link              = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/global/networks/fwl-sz-gc-zh-backend-nic7-vpc\" -> (known after apply)",
      "      ~ subnetworks_self_links = [",
      "          - \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/subnetworks/fwl-sz-gc-zh-backend-nic7\",",
      "        ] -> (known after apply)",
      "        # (1 unchanged attribute hidden)",
      "    }",
      "",
      "  # module.vpn-tunnel-ha.data.google_compute_router.host will be read during apply",
      "  # (config refers to values not yet known)",
      " <= data \"google_compute_router\" \"host\"  {",
      "      ~ bgp                = [",
      "          - {",
      "              - advertise_mode       = \"CUSTOM\"",
      "              - advertised_groups    = []",
      "              - advertised_ip_ranges = []",
      "              - asn                  = 64513",
      "            },",
      "        ] -> (known after apply)",
      "      ~ creation_timestamp = \"2021-03-03T05:58:52.378-08:00\" -> (known after apply)",
      "      + description        = (known after apply)",
      "      ~ id                 = \"fwl-sz-gc-zh-backend-nic7-router\" -> (known after apply)",
      "        name               = \"fwl-sz-gc-zh-backend-nic7-router\"",
      "      ~ network            = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/global/networks/fwl-sz-gc-zh-backend-nic7-vpc\" -> \"fwl-sz-gc-zh-backend-nic7-vpc\"",
      "      ~ self_link          = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/routers/fwl-sz-gc-zh-backend-nic7-router\" -> (known after apply)",
      "        # (2 unchanged attributes hidden)",
      "    }",
      "",
      "  # module.vpn-tunnel-ha.google_compute_vpn_tunnel.host_project_tunnel must be replaced",
      "-/+ resource \"google_compute_vpn_tunnel\" \"host_project_tunnel\" {",
      "      ~ creation_timestamp              = \"2021-12-13T16:01:43.562-08:00\" -> (known after apply)",
      "      ~ detailed_status                 = \"Tunnel is up and running.\" -> (known after apply)",
      "      ~ id                              = \"projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/vpnTunnels/ha-vpn-tunnel1-to-x-sandbox-sz1\" -> (known after apply)",
      "      ~ local_traffic_selector          = [",
      "          - \"0.0.0.0/0\",",
      "        ] -> (known after apply)",
      "        name                            = \"ha-vpn-tunnel1-to-x-sandbox-sz1\"",
      "      - peer_external_gateway_interface = 0 -> null",
      "      ~ peer_gcp_gateway                = \"https://www.googleapis.com/compute/v1/projects/x-sandbox-sz1/regions/europe-west6/vpnGateways/ha-vpn-x-sandbox-sz1\" -> \"projects/x-sandbox-sz1/regions/europe-west6/vpnGateways/ha-vpn-x-sandbox-sz1\"",
      "      ~ peer_ip                         = \"x.x.x.x\" -> (known after apply)",
      "      ~ remote_traffic_selector         = [",
      "          - \"0.0.0.0/0\",",
      "        ] -> (known after apply)",
      "      ~ router                          = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/routers/fwl-sz-gc-zh-backend-nic7-router\" -> (known after apply) # forces replacement",
      "      ~ self_link                       = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/vpnTunnels/ha-vpn-tunnel1-to-x-sandbox-sz1\" -> (known after apply)",
      "      ~ shared_secret_hash              = \"x\" -> (known after apply)",
      "      ~ tunnel_id                       = \"1281965462373687304\" -> (known after apply)",
      "      ~ vpn_gateway                     = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/vpnGateways/vpn-gw-sz-gc-zh-nic7\" -> (known after apply) # forces replacement",
      "        # (5 unchanged attributes hidden)",
      "    }",
      "",
      "  # module.vpn-tunnel-ha.google_compute_vpn_tunnel.project_host_tunnel must be replaced",
      "-/+ resource \"google_compute_vpn_tunnel\" \"project_host_tunnel\" {",
      "      ~ creation_timestamp              = \"2021-12-13T16:01:53.820-08:00\" -> (known after apply)",
      "      ~ detailed_status                 = \"Tunnel is up and running.\" -> (known after apply)",
      "      ~ id                              = \"projects/x-sandbox-sz1/regions/europe-west6/vpnTunnels/ha-vpn-tunnel1-to-x-netzwerk-hostvpc-prod1\" -> (known after apply)",
      "      ~ local_traffic_selector          = [",
      "          - \"0.0.0.0/0\",",
      "        ] -> (known after apply)",
      "        name                            = \"ha-vpn-tunnel1-to-x-netzwerk-hostvpc-prod1\"",
      "      - peer_external_gateway_interface = 0 -> null",
      "      ~ peer_gcp_gateway                = \"https://www.googleapis.com/compute/v1/projects/x-netzwerk-hostvpc-prod1/regions/europe-west6/vpnGateways/vpn-gw-sz-gc-zh-nic7\" -> (known after apply) # forces replacement",
      "      ~ peer_ip                         = \"x.x.x.x\" -> (known after apply)",
      "      ~ remote_traffic_selector         = [",
      "          - \"0.0.0.0/0\",",
      "        ] -> (known after apply)",
      "      ~ router                          = \"https://www.googleapis.com/compute/v1/projects/x-sandbox-sz1/regions/europe-west6/routers/ha-vpn-router-x-netzwerk-hostvpc-prod1\" -> \"projects/x-sandbox-sz1/regions/europe-west6/routers/ha-vpn-router-x-netzwerk-hostvpc-prod1\"",
      "      ~ self_link                       = \"https://www.googleapis.com/compute/v1/projects/x-sandbox-sz1/regions/europe-west6/vpnTunnels/ha-vpn-tunnel1-to-x-netzwerk-hostvpc-prod1\" -> (known after apply)",
      "      ~ shared_secret_hash              = \"x\" -> (known after apply)",
      "      ~ tunnel_id                       = \"321961824140025886\" -> (known after apply)",
      "      ~ vpn_gateway                     = \"https://www.googleapis.com/compute/v1/projects/x-sandbox-sz1/regions/europe-west6/vpnGateways/ha-vpn-x-sandbox-sz1\" -> \"projects/x-sandbox-sz1/regions/europe-west6/vpnGateways/ha-vpn-x-sandbox-sz1\"",
      "        # (5 unchanged attributes hidden)",
      "    }",
      "",
      "  # module.project.module.service_project.module.budget.data.google_project.project[0] will be read during apply",
      "  # (config refers to values not yet known)",
      " <= data \"google_project\" \"project\"  {",
      "      + auto_create_network = (known after apply)",
      "      ~ billing_account     = \"x\" -> (known after apply)",
      "      ~ folder_id           = \"x\" -> (known after apply)",
      "      ~ id                  = \"projects/x-sandbox-sz1\" -> (known after apply)",
      "      ~ labels              = {} -> (known after apply)",
      "      ~ name                = \"x-sandbox-sz1\" -> (known after apply)",
      "      ~ number              = \"x\" -> (known after apply)",
      "      + org_id              = (known after apply)",
      "      + skip_delete         = (known after apply)",
      "        # (1 unchanged attribute hidden)",
      "    }",
      "",
      "  # module.vpc.module.vpc.module.subnets.google_compute_subnetwork.subnetwork[\"europe-west1/subnetz-x-sandbox-sz1\"] will be updated in-place",
      "  ~ resource \"google_compute_subnetwork\" \"subnetwork\" {",
      "        id                         = \"projects/x-sandbox-sz1/regions/europe-west1/subnetworks/subnetz-x-sandbox-sz1\"",
      "        name                       = \"subnetz-x-sandbox-sz1\"",
      "      ~ secondary_ip_range         = [",
      "          ~ {",
      "              ~ ip_cidr_range = \"10.42.0.0/16\" -> \"10.43.0.0/16\"",
      "                # (1 unchanged element hidden)",
      "            },",
      "          ~ {",
      "              ~ ip_cidr_range = \"10.100.42.0/24\" -> \"10.100.43.0/24\"",
      "                # (1 unchanged element hidden)",
      "            },",
      "        ]",
      "        # (9 unchanged attributes hidden)",
      "    }",
      "",
      "  # module.project.module.service_project.module.project-factory.module.project_services.google_project_service.project_services[\"containeranalysis.googleapis.com\"] will be created",
      "  + resource \"google_project_service\" \"project_services\" {",
      "      + disable_dependent_services = false",
      "      + disable_on_destroy         = false",
      "      + id                         = (known after apply)",
      "      + project                    = \"x-sandbox-sz1\"",
      "      + service                    = \"containeranalysis.googleapis.com\"",
      "    }",
      "",
      "  # module.project.module.service_project.module.project-factory.module.project_services.google_project_service.project_services[\"osconfig.googleapis.com\"] will be created",
      "  + resource \"google_project_service\" \"project_services\" {",
      "      + disable_dependent_services = false",
      "      + disable_on_destroy         = false",
      "      + id                         = (known after apply)",
      "      + project                    = \"x-sandbox-sz1\"",
      "      + service                    = \"osconfig.googleapis.com\"",
      "    }",
      "",
      "Plan: 7 to add, 1 to change, 2 to destroy.",
      "",
      "─────────────────────────────────────────────────────────────────────────────",
      "",
      "Saved the plan to: /tmp/tmpc1ct52kr",
      "",
      "To perform exactly these actions, run the following command to apply:",
      "    terraform apply \"/tmp/tmpc1ct52kr\""
    ]
  }

### Terraform Version
0.15

```
...
```

### Terraform Configuration Files

```
data "google_compute_network" "host_project" {
  project = var.host_project_id
  name    = substr(var.ip_cidr_range, 0, 6) == "10.206" ? "x" : "x"
}

data "google_compute_router" "host" {
  name    = substr(var.ip_cidr_range, 0, 6) == "10.206" ? "x" : "x"
  network = data.google_compute_network.host_project.name
  project = var.host_project_id
  region  = "europe-west6"

}

data "google_compute_ha_vpn_gateway" "ha_gateway_host" {
  name    = substr(var.ip_cidr_range, 0, 6) == "10.206" ? "x" : "x"
  project = var.host_project_id
  region  = "europe-west6"
}


resource "google_compute_ha_vpn_gateway" "ha_gateway" {
  region  = "europe-west6"
  project = var.project_id
  name    = "ha-vpn-${var.project_id}"
  network = var.vpc.network_name
}

resource "random_id" "random_secret_key" {
  byte_length = 8
}

resource "google_compute_router" "project" {
  name    = "ha-vpn-router-${var.host_project_id}"
  network = var.vpc.network_name
  project = var.project_id
  region  = "europe-west6"

  bgp {
    asn            = (substr(var.ip_cidr_range, 0, 6) == "10.206" ? "64513" : "64514")
    advertise_mode = "CUSTOM"
  }
}

//VPN vpn_1_to_2

resource "google_compute_vpn_tunnel" "host_project_tunnel" {
  name                  = "ha-vpn-tunnel1-to-${var.project_id}"
  project               = var.host_project_id
  region                = "europe-west6"
  vpn_gateway           = data.google_compute_ha_vpn_gateway.ha_gateway_host.id
  peer_gcp_gateway      = google_compute_ha_vpn_gateway.ha_gateway.id
  shared_secret         = random_id.random_secret_key.dec
  router                = data.google_compute_router.host.id
  vpn_gateway_interface = 0
}

//VPN vpn_2_to_1

resource "google_compute_vpn_tunnel" "project_host_tunnel" {
  name                  = "ha-vpn-tunnel1-to-${var.host_project_id}"
  project               = var.project_id
  region                = "europe-west6"
  vpn_gateway           = google_compute_ha_vpn_gateway.ha_gateway.id
  peer_gcp_gateway      = data.google_compute_ha_vpn_gateway.ha_gateway_host.id
  shared_secret         = random_id.random_secret_key.dec
  router                = google_compute_router.project.id
  vpn_gateway_interface = 0

}




resource "google_compute_router_interface" "router_host_interface" {
  name       = "router-interface-${var.project_id}"
  project    = var.host_project_id
  router     = data.google_compute_router.host.name
  region     = "europe-west6"
  ip_range   = "x.x.${var.bgp_counter}.1/30"
  vpn_tunnel = google_compute_vpn_tunnel.host_project_tunnel.name

}

resource "google_compute_router_peer" "router_host_peer" {
  name                      = "router-peer-${var.project_id}"
  project                   = var.host_project_id
  router                    = data.google_compute_router.host.name
  region                    = "europe-west6"
  peer_ip_address           = "x.x.${var.bgp_counter}.2"
  peer_asn                  = (substr(var.ip_cidr_range, 0, 6) == "10.206" ? "64513" : "64514")
  advertised_route_priority = 5
  interface                 = google_compute_router_interface.router_host_interface.name
  advertise_mode            = "CUSTOM"
  advertised_ip_ranges {
    range = "10.0.0.0/8"
  }
  advertised_ip_ranges {
    range = "0.0.0.0/0"
  }
}

resource "google_compute_router_interface" "router_interface_project" {
  name       = "router-interface-${var.host_project_id}"
  project    = var.project_id
  router     = google_compute_router.project.name
  region     = "europe-west6"
  ip_range   = "x.x.${var.bgp_counter}.2/30"
  vpn_tunnel = google_compute_vpn_tunnel.project_host_tunnel.name
}

locals {
		tf_master = var.master_ip_cidr_range == "" ? [] : [var.master_ip_cidr_range]
		tf_serverless = var.serverless_connector_ip_cidr_range == "" ? [] : [var.serverless_connector_ip_cidr_range]
		ranges = flatten([local.tf_master, local.tf_serverless])
}

resource "google_compute_router_peer" "router_project_peer" {
  name                      = "router-peer-${var.host_project_id}"
  project                   = var.project_id
  router                    = google_compute_router.project.name
  region                    = "europe-west6"
  peer_ip_address           = "x.x.${var.bgp_counter}.1"
  peer_asn                  = substr(var.ip_cidr_range, 0, 6) == "10.206" ? "64512" : "64513"
  advertised_route_priority = 5
  interface                 = google_compute_router_interface.router_interface_project.name
  advertise_mode            = "CUSTOM"

  advertised_ip_ranges {
    range = var.ip_cidr_range
  }
  dynamic "advertised_ip_ranges" {
    for_each = local.ranges
    content {
      range = advertised_ip_ranges.value
    }
  }
}

...
```

**Comment by jbardin** [comment]
Hi @anagas,

Sorry you're having trouble here, but the output does not look like a bug in terraform. If you have data sources which depend on changes to other managed resources, those data source cannot be read until the changes are resolved. This in turn forces all resources depending on outputs from the data sources to show changes until the plan is applied. Without a complete example it's hard to say what the problem in the configuration is, but the usual culprit is unnecessary or improper use of `depends_on`. Another common issue is trying to both data sources and managed resources for the same logical resource, which is going either going to lead to incorrect data source output, or deferred reads like seen above.w

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by anagas** [comment]
@jbardin  I have checked the data source twice and someone else has also looked at it. Never changed this data source...

**Comment by jbardin** [comment]
It's not that the data sources themselves have changed, is some dependency of the data sources are is preventing them from being read during the plan. Since this appears on multiple data sources, I would guess that you are forcing them to be deferred by using `depends_on` for their containing module. If you have a more complete example I may be able to spot the problem, but it's generally better to use the community forum where there are more users available to help.
