### ISSUE TITLE
Implicitly passed default providers are not resolved to parent provider keys in JSON output

### ISSUE THREAD

**Issue by nozaq** [hashicorp/terraform#30513]
### Terraform Version

This issue is related to #30138, which is merged but not released yet.

Tested with the current main branch, specifically [this tree](https://github.com/hashicorp/terraform/tree/7a20c07cb0e4e30b6177cb86401ea1edd192eeea).

### Terraform Configuration Files

[This repo](https://github.com/nozaq/providerconfig-demo/tree/main/3layers) contains a complete example.

Below diagram summarizes the setup.
![overview](https://github.com/nozaq/providerconfig-demo/raw/main/3layers/overview.png)

The project contains three layers of module call hierarchy, i.e. `Root module > module.foo > module.bar`, and each module contains one `null_resource` resource.
Root module has two providers `null` and `null.second`, and passes `null.second` to `module.foo`. `module.foo` calls `module.bar` without explicitly passing the provider, but `module.bar` ends up using `null.second` since `module.foo`'s default null provider is `null.second`.

### Expected Behavior

`provider_config_key` for all resources point to `null.second` in [JSON output](https://www.terraform.io/internals/json-format).

### Actual Behavior

`module.foo.module.bar.level3` points to `module.foo.module.bar:null` while `level1` and `module.foo.level2` point to `null.second`.

[This](https://github.com/nozaq/providerconfig-demo/blob/main/3layers/plan.json) is the actual JSON output from `terraform show -json`.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -out temp.out`
3. `terraform show -json temp.out > plan.json`
4. Open `plan.json`

### Additional Context

#30138 intended to resolve provider mappings up to the module call tree, but it seems that the current implementation only considers explicitly passed provider configurations.
This could be fixed by resolving implicitly passed default providers as well.

### References

- #30113 
- #30138 
- #30480

**Comment by alisdair** [comment]
Thanks for the report! I was able to confirm this issue, and [added another example configuration to your reproduction case](https://github.com/nozaq/providerconfig-demo/pull/1) which verified this further for me.

At first glance I don't see an obvious way to fix this. If you do, and you'd like to submit a PR, I'll happily review it. Otherwise I'll try to find time to revisit this shortly, hopefully before Terraform 1.2 is released.

**Comment by nozaq** [comment]
@alisdair Just submitted #30525. Please let me know if you have any comments or suggestions!
