### ISSUE TITLE
Global Parameters being deleted in azurerm_data_factory when using azurerm providers 2.62 and greater

### ISSUE THREAD

**Issue by gsmartvoda** [hashicorp/terraform#30529]
Global Parameters are being deleted in azurerm_data_factory when using azurerm providers 2.62 and greater. 

We currently manage global parameters outside of TF in there own repo & CI/CD pipeline. I understand this is an added function from 2.62 however global parameters are labelled as optional. When we are using ver 2.62 and onwards it will delete the global parameters unless added into the file. 

We plan to continue using global parameters outside of TF. Is there anyway to prevent Terraform from deleting the parameters other than adding them into the code?

**Comment by crw** [comment]
Hello @gsmartvoda,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/tags/c/terraform-providers/31/azure) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
