### ISSUE TITLE
AWS Provider producing invalid values for MSK endpoints

### ISSUE THREAD

**Issue by Zak-Alford** [hashicorp/terraform#30539]
We tried making an aws_lambda_event_source_mapping that _used_ to work, but it's providing the below error. 

We also get this when building our MSK, but we can just manually re-run terraform to fix this. Now we keep running into it pretty 
 consistently when making an outside-repo (handled by a different terraform state file than the MSK terraform) lambda that's using a data call to find the MSK cluster.

<html>
<body>

When expanding the plan for
--
985 | │ module.actimize_event_lambda[0].aws_lambda_event_source_mapping.msk[0] to
986 | │ include new values learned so far during apply, provider
987 | │ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
988 | │ .self_managed_event_source[0].endpoints: was null, but now
989 | │ cty.MapVal(map[string]cty.Value{"KAFKA_BOOTSTRAP_SERVERS":cty.StringVal("<scrubbed-broker-connection-string>")}).
990 | │
991 | │ This is a bug in the provider, which should be reported in the provider's
992 | │ own issue tracker.

</body>
</html>

**Comment by crw** [comment]
Hello @Zak-Alford,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
