### ISSUE TITLE
Managed Private Endpoint on Synapse Serverless with Storage Account

### ISSUE THREAD

**Issue by TruongNguyen888** [hashicorp/terraform#30533]
### Terraform Version

```
1.0.0
```

### Terraform Configuration Files

```terraform

resource "azurerm_storage_data_lake_gen2_filesystem" "lake_gen2" {
  name               = local.containername
  storage_account_id = module.storage_account.id
}


resource "azurerm_synapse_workspace" "synapse_workspace" {
  name                                 = var.name
  resource_group_name                  = var.resource_group.name
  location                             = var.resource_group.location
  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.lake_gen2
  sql_administrator_login              = var.sql_admin_login
  sql_administrator_login_password     = var.sql_admin_password
  managed_virtual_network_enabled      = var.managed_virtual_network_enabled
  public_network_access_enabled        = var.public_network_access_enabled
  aad_admin {
    login     = var.aad_admin
    object_id = var.aad_admin_object_id
    tenant_id = var.aad_admin_tenant_id
  }
}

resource "azurerm_synapse_managed_private_endpoint" "private_endpoint_syn2sta" {
  name                 = "mpe_syn2sta_${var.plant}_${var.data_source}_${var.env}"
  synapse_workspace_id = module.synapse_workspace.id
  target_resource_id   = module.storage_account.id
  subresource_name     = "blob"
  lifecycle {
    prevent_destroy = true
  }
}
```

### Expected Behavior

A private endpoint connection should be created to the Storage. 

### Actual Behavior

After the approval a managed private endpoint is created but not linked with the storage.

### Description
We are creating a synapse workspace serverless which is connected to a storage account container with a delta lake 2 gen. Everything works, the creation of the container and synapse workspace. But when i want to connect them with a managed private endpoint via terraform it seems it worked because the private endpoint is creating and needed to be approved.. after the approval the private endpoint is in approve state. but if i go to the synapse workspace under linked services the storage account didnt show up as linked with a managed private endpoint.

I hope this is understandable, because i cannot upload a screenshot.

**Comment by crw** [comment]
Hello @TruongNguyen888,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the community forum where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
