### ISSUE TITLE
Azure provider should support data disks as part of instance resource definition

### ISSUE THREAD

**Issue by carmstrong** [hashicorp/terraform#3054]
The Azure API allows specifying a data disk as part of an instance definition. We should support the same. This is necessary if the instance expects a data disk to be mounted at boot.

**Comment by stack72** [comment]
Hi @carmstrong 

the Azure Service Manager provider supports the creation of data_disks (https://www.terraform.io/docs/providers/azure/r/data_disk.html)

Closing this ticket out

Thanks

Paul
