### ISSUE TITLE
Include subfolders as part of the current work directory

### ISSUE THREAD

**Issue by divad1196** [hashicorp/terraform#30558]
Hi,
first, thank you for the work on terraform, and sorry if an issue is/was already open, I couldn't find one mentioning this

### Current Terraform Version

Terraform v1.1.6 on linux_amd64

### Use-cases

We have different machine with different purpose with the same providor. I would like to organize them within subfolders without having to repeat many declaration. It would work just as-if the files were in the root folder.

### Attempted Solutions

I tried the following 2 solutions, which are the only ones I could find after hours of research.
* Use modules: This is not great since I have to define the required provider, and I cannot refer resources from other folders.
* Terragrunt: promising, but this is still another program for this mere usage.

### Proposal

I understand that recursive import would be good. So I thought that we could have an "include" key word, similar to "module" key word, that would take a path to a folder or file and consider its contents as part of the current folder.
If folder B includes folder C, and folder A includes folder B, then folder C would be included in A as well.

The content would be included just once. If a source is referenced many time, either ignore it or put a warning/error.

### References

I couldn't find any issue on github, but I found many forums with the same concern that I have.

Thank you for your time

**Comment by crw** [comment]
@divad1196 This looks to be a contender for a previous issue on the same topic: https://github.com/hashicorp/terraform/issues/23047 -- what do you think? If it seems to be the same, can we close this one?

**Comment by divad1196** [comment]
@crw I think you are right. The syntax does not really matter, I would just say that we may want to include a single file and not only folders of file, so "folder" key word wouldn't suits well.
So, sorry for not having found it by myself before posting, I think the reason is that the issue you mentioned is idle for more than 2 years. 
I will continue on this topic, hoping that something will come out of this.
Thank you and have a nice day.
