### ISSUE TITLE
Error: no schema available for aws_s3_bucket_versioning

### ISSUE THREAD

**Issue by dothuan96** [hashicorp/terraform#30555]
Hi all, I got some bug with aws_bucket_versioning. It's still existed even though I deleted all aws_s3_bucket_versioning.
Please help me as soon as possible. Tks.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/26543315/154710935-704b0a99-4c0d-4f8e-94a0-2992455c5fd0.png)

**Comment by crw** [comment]
Hello @dothuan96,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by crw** [comment]
Thanks for reporting it though, I am going to mention it to the AWS team as it may have to do with a recent change to S3 in the v4 provider.
