### ISSUE TITLE
Still the task definition gets deregistered

### ISSUE THREAD

**Issue by hera1002** [hashicorp/terraform#30553]
Still the task definition gets deregistered

_Originally posted by @hera1002 in https://github.com/hashicorp/terraform-provider-aws/issues/258#issuecomment-1044680661_

**Comment by hera1002** [comment]
resource "aws_ecs_task_definition" "default" {
...
..
  skip_destroy             = true 
}
I have the similar task definition  code. Still the task def gets de-registered

**Comment by crw** [comment]
Hi @hera1002, for an issue to be considered it needs significantly more context. Can you please either provide more context to your comment on https://github.com/hashicorp/terraform-provider-aws/issues/258#issuecomment-1044680661, or re-open a new issue here following the issue template? Thanks.
