### ISSUE TITLE
Terraform Registry submodules do not show the correct code to paste into the root module

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform#30564]
When I attempt to use submodules from the terraform registry I see something like this - note the provision instructions.

![image](https://user-images.githubusercontent.com/61512176/154925287-7a871f1e-02b0-4aa2-9ff4-7d89aeb5b7f5.png)

It says to paste in:

```
module "iam" {
  source  = "terraform-aws-modules/iam/aws"
  version = "4.13.1"
  # insert the 3 required variables here
}
```

However, what I need to paste in is as follows:

```
module "iam" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  version = "4.13.1"
  # insert the 3 required variables here
}
```

**Comment by alisdair** [comment]
Thanks for reporting this! For issues with the Terraform Registry, please send an email to terraform-registry@hashicorp.com, which is monitored by the team at HashiCorp responsible for the registry. I'm closing this issue out because it's not a Terraform core bug.

**Comment by crw** [comment]
Just as an FYI, I opened an internal issue with the Registry team for this ticket, so if/when you email them, reference this Github issue, and they'll be able to find the existing issue.

**Comment by gtirloni** [comment]
@crw @scott-doyland-burrows any update from the Terraform Registry support? It's weird that they would go so far as exposing submodules in the web UI but no way to use it directly in Terraform (except to bypass the Registry and go directly to Git).

**Comment by scott-doyland-burrows** [comment]
> @crw @scott-doyland-burrows any update from the Terraform Registry support? It's weird that they would go so far as exposing submodules in the web UI but no way to use it directly in Terraform (except to bypass the Registry and go directly to Git).
> 
> EDIT: For anyone googling this issue, a colleague found out you can use double slashes like `terraform-google-modules/org-policy/google/modules/domain_restricted_sharing`

That is basically what I already described in my original post (except your example missed out the ```//```).
It should be like this:

```source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"```

It is just the instructions in the registry that are incorrect, they just need updating.  

No reply from Terraform Registry support though.
