### ISSUE TITLE
Event Subscriptions change wipes out Function App code

### ISSUE THREAD

**Issue by rhassan91** [hashicorp/terraform#30568]
### Terraform Version

Terraform v0.12.31
+ provider.azurerm v2.57.0
+ provider.http v1.2.0
+ provider.random v3.1.0

### Terraform Configuration Files
Unable to post TF code due to time it would take to redact all company information and configuration.

### Description
When Terraform changes the event subscription for a deployed function app, it seems to clean out all the function codes within the app itself.

### Expected Behavior
The function event subscription should be changed and the function code not wiped out

### Actual Behavior
The function event subscription changes and the function code is wiped clean from the function app

### Steps to Reproduce
Create Function App, deploy python code to a Linux function app. 
Create an even subscription for the function. 
When terraform creates the event subscription for the function it will wipe out the deployed code to the app

**Comment by crw** [comment]
Hello @rhassan91,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
