### ISSUE TITLE
trimspace does not work as expected with file input

### ISSUE THREAD

**Issue by JonasSaegesser** [hashicorp/terraform#30567]
Hi Guys

I am implementing an aws_glue_catalog_table with a column with a complex struct<> type. To enhance the readability of the type defintion I have moved it to a separate file. 
Glue expects no newlines in the type definition: "Member must satisfy regular expression pattern: [\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*;"

Therefor I am using trimspace(file(FILEPATH)) to cut all the newlines and spaces used for better readablilty:
sample type defininition:
```
struct<
  att1:string,
  att2:string,
  att3:struct<
    account_name:string,
    tags:struct<
      tag1:string,
      tag2:string,
    >
  >
>
```
aws_glue_catalog_table definition
```terraform
resource "aws_glue_catalog_table" "sample" {
  name          = local.athena_table_name
  database_name = aws_athena_database.sample_db.id

  table_type = "EXTERNAL_TABLE"

  parameters = {
    EXTERNAL              = "TRUE"
    "parquet.compression" = "SNAPPY"
  }

  storage_descriptor {
    location      = "s3://${local.bucket_name}/findingstream/"
    input_format  = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"

    ser_de_info {
      name                  = "findingstream"
      serialization_library = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"

      parameters = {
        "serialization.format" = 1
        "paths"                = "accountContext,finding"
      }
    }

    columns {
      name = "sample_column"
      type = trimspace(file(local.path_to_file))
    }
  }
}

```

### Expected Behavior
trimspace should remove newlines and spaces resulting in a singleline string accepted by the aws api.

### Actual Behavior
Terraform fails to create / update ressource:
```
 at 'table.storageDescriptor.columns.1.member.type' failed to satisfy constraint: Member must satisfy regular expression pattern: [\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*; Value: struct<
  att1:string,
  att2:string,
  att3:struct<
    account_name:string,
    tags:struct<
      tag1:string,
      tag2:string,
    >
  >
>
```

If I remove the newlines and spaces from the file manually the apply works as expected.

According to the error message I would suspect that the trimspace() function did not work as I expected. Did I understand the documentation wrong or is this a real missbehaviour?

Cheers
Jonas

**Comment by crw** [comment]
Hello @JonasSaegesser,

Thanks for the report! Per the documentation at https://www.terraform.io/language/functions/trimspace:

> `trimspace` removes any space characters from the *start* and *end* of the given string.

I reproduced this and see that it is working as documented. If you have further questions about this feature, please use the [community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
