### ISSUE TITLE
Terraform Keeps Rebuilding AKS When public_network_access_enabled=false

### ISSUE THREAD

**Issue by jingchen1992** [hashicorp/terraform#30563]
Azure Kubernetes Service recently added public_network_access_enabled flag, and we set it to false for our private cluster (prviate_cluster_enabled=true): https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster.  However we noticed very interrupting issue that when public_network_access_enabled is set to false, terraform plan|apply will ask to destroy and recreate AKS and nodepools again and again. We contacted MSFT/Azure and they suggested us to contact Hashicorp/Terraform as this seems to be Terraform defect. 

Does anyone experience similar issue? And most importantly, what is the fix which will NOT require us to rebuild entire AKS AGAIN?

Thanks ahead

**Comment by crw** [comment]
Hello @jingchen1992,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

In this specific case, I would start by asking this question in the forums. Thanks!
