### ISSUE TITLE
Remove satori/go.uuid dependency from go.mod

### ISSUE THREAD

**Issue by cHiv0rz** [hashicorp/terraform#30570]
### Terraform Version
```
1.1.6
...
```
### Problem detected
I'm trying to create a docker image with Alpine linux and terraform, basically I'm adding the latest binary (1.1.6). In my last step I will use trivy for checking vulnerabilities, and it throws that the binary terraform has CVE critical with the library satori/go.uuid:

![image](https://user-images.githubusercontent.com/12000622/155157435-8d354f76-d815-4574-a68e-2c3dbfc55ca1.png)

I was trying to debug a little and I realised that the problem comes from go.mod, it has the following modules out of date:

- github.com/aliyun/alibaba-cloud-sdk-go
- github.com/dylanmei/winrmtest

satori/go.uuid is not maintained anymore, so both libraries have been moved to other projects (github.com/gofrs/uuid or github.com/google/uuid), but for any reason, terraform still has the old ones.

To give more context:
`go get github.com/dylanmei/winrmtest
go get: added github.com/antchfx/xmlquery v1.3.5
go get: upgraded github.com/antchfx/xpath v0.0.0-20190129040759-c8489ed3251e => v1.1.10
go get: upgraded github.com/dylanmei/winrmtest v0.0.0-20190225150635-99b7fe2fddf1 => v0.0.0-20210303004826-fbc9ae56efb6
go get: upgraded github.com/gofrs/uuid v3.3.0+incompatible => v4.0.0+incompatible`

`go get github.com/aliyun/alibaba-cloud-sdk-go
go get: upgraded github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190329064014-6e358769c32a => v1.61.1492
go get: upgraded gopkg.in/ini.v1 v1.42.0 => v1.66.2`

**Comment by stevenbressey** [comment]
I'm having exactly the same issue: Trivy scan fails on any Docker image containing Terraform binary.
I found out that satori/go.uuid module had been removed via [this PR](https://github.com/hashicorp/terraform/pull/22415) a while ago, but for some unknown reason it is still present in go.mod.
For now, we have to sadly exclude terraform binary from Trivy image scan.

**Comment by cHiv0rz** [comment]
I think it is because github.com/aliyun/alibaba-cloud-sdk-go, it has the same problem, they've already moved to google/uuid but it is still require satori/go.uuid. Doesn't make any sense

**Comment by stevenbressey** [comment]
It looks like satori/go.uuid has been removed from github.com/aliyun/alibaba-cloud-sdk-go since they tidied the dependencies (https://github.com/aliyun/alibaba-cloud-sdk-go/pull/348). I can't find it anywhere in current modules. So the dependency must come from another module I guess.

**Comment by cHiv0rz** [comment]
I removed "manually" from go.mod and go.sum, and tried to compile. It said neither github.com/aliyun/alibaba-cloud-sdk-go nor github.com/dylanmei/winrmtest can't work without satori/go.uuid. Both are already moved to another uuid library, so maybe updating the version of both it works fine

**Comment by alisdair** [comment]
Thanks for the report. I've updated the versions of `alibaba-cloud-sdk-go` and `winrmtest`, with the result that the `satori/go.uuid` package no longer exists in built Terraform binaries. The package is still listed in go.sum, because it is used in tests of our transitive dependencies, but this does not affect the security of Terraform itself.

This change should go out in an upcoming 1.1 patch release.

**Comment by stevenbressey** [comment]
Thank you very much for the heads up !
Just a question: did you have the chance to run a trivy scan on the new binary ?

**Comment by alisdair** [comment]
We did, and the `go.uuid` vulnerability is no longer present.
