### ISSUE TITLE
When DMS Endpoint with Oracle not uses KMS Customer Managed Key

### ISSUE THREAD

**Issue by singhrp** [hashicorp/terraform#30578]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

### References

When DMS Endpoint with Oracle is created using KMS Customer Managed Key,  the end point ignores the KMS CMK and uses default aws kms key

resource "aws_dms_endpoint" "dmsendpoint" {
  certificate_arn             = var.certificate_arn
  database_name               = var.database_name
  endpoint_id                 = var.endpoint_id
  endpoint_type               = var.endpoint_type
  engine_name                 = var.engine_name
  extra_connection_attributes = var.extra_connection_attributes
  kms_key_arn              = var.kms_key_arn
  port                        = var.port
  server_name                 = var.server_name
  username                    = var.username
  password                    = var.password
  ssl_mode                    = var.ssl_mode
  tags                        = var.tags
}

This works with Aurora and SQL Server but not Oracle

**Comment by crw** [comment]
Hello @singhrp,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
