### ISSUE TITLE
Bug while creating Cloud Scheduler Job on GCP

### ISSUE THREAD

**Issue by matheus-mansour-el-batti** [hashicorp/terraform#30583]
Hello,

When creating a cloud scheduler job on GCP, the header "User-Agent": "Google-Cloud-Scheduler" is automatically created. If we pass this header manually to the http_target, terraform will create the header automatically but will still show a pending migration on "`terraform plan`", even after `terraform apply`. This is probably because the command itself to add this header was never executed manually (it was automatically by GCP). Please find a screenshot of the problem attached.

<img width="669" alt="no_header_created (1)" src="https://user-images.githubusercontent.com/91345798/155747237-8ee9ca2e-7616-437e-ab37-2f5f0e2d6a4c.png">

**Comment by crw** [comment]
Hello @matheus-mansour-el-batti,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use the community forum where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
