### ISSUE TITLE
DigitalOcean provider should allow specifying SSH key by name

### ISSUE THREAD

**Issue by carmstrong** [hashicorp/terraform#3058]
Currently, we must specify the SSH key by its ID or fingerprint, which is only available by querying the DO API. This is a less than ideal user experience. 

With the DO API, we can enumerate all keys on an account. We should allow SSH keys to be specified by name as well as by ID.

**Comment by nathansamson** [comment]
Names are not required to be unique which makes this a challenging problem

**Comment by cabbiepete** [comment]
Using the approach below 

Droplet config 
```
ssh_keys = ["${digitalocean_ssh_key.april.fingerprint}",
              "${digitalocean_ssh_key.pete.fingerprint}",
              "${digitalocean_ssh_key.garfield.fingerprint}"]
```
Referencing 3 ssh key resource definitions

works great on 0.7.0 maybe this ticket is solved but just wasn't closed?
