### ISSUE TITLE
Module Count interacts adversely with passed in providers

### ISSUE THREAD

**Issue by sjf3** [hashicorp/terraform#30586]
### Terraform Version

Tried 3 different versions 
```
1.1.6
1.0.3
0.15.5
```

### Terraform Configuration Files

https://github.com/lacework/terraform-aws-cloudtrail-controltower/tree/main/examples/default

Was running this example but with `count = 1` on the module 

### Expected Behavior

resources would be deployed across multiple aws accounts respecting the provider properties on each resource in the module

### Actual Behavior

resources were created all in the log_archive account event those with the `provider = aws.audit` set in the module

### Steps to Reproduce

terraform init 
terraform apply

### Additional Context

Removing the count property the module behaved as expected. I was using count = 0 to toggle off the module while testing. commenting out that line yeilds the expected result. Changing the 0 to a 1 results in the providers block not being respected and all resources being created in the log_archive account.

**Comment by jbardin** [comment]
Closing since we have not heard back. If this is still reproducible, feel free to reply here with the pertinent information, or file a new issue.

Thanks!
