### ISSUE TITLE
German IP4 ranges blocked by mistake?

### ISSUE THREAD

**Issue by davidroth** [hashicorp/terraform#30596]
Hi there, this is probably related to https://github.com/hashicorp/terraform/issues/30591

We have 2 root servers hosted at [hetzner](https://hetzner.com). The first is in the subnet [116.202.0.0/16](https://ipinfo.io/AS24940/116.202.0.0/16) and the second is in subnet [142.132.128.0/17](https://ipinfo.io/AS24940/142.132.128.0/17).

**Issue:**

We cannot access `https://releases.hashicorp.com` via **IP4** from the subnet  `116.202.0.0/16`.

I.e `curl -v -4 https://releases.hashicorp.com/terraform-provider-aws/4.3.0/terraform-provider-aws_4.3.0_linux_amd64.zip` via IP4 from the subnet `116.202.0.0/16` fails with:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>405 Not allowed</title>
  </head>
  <body>
    <h1>Error 405 Not allowed</h1>
    <p>Not allowed</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-fra19179-FRA 1646205254 1986550410</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

If I try to access it via IPV6, it works. So  `curl -v -6 https://releases.hashicorp.com/terraform-provider-aws/4.3.0/terraform-provider-aws_4.3.0_linux_amd64.zip` works from 116.202.0.0/16.

However, accessing it from subnet `142.132.128.0/17` works as expected via IPV4 and also via IPV6.

IMO there are ip ranges which have been blocked  by mistake?.  See also #30591

**Comment by crw** [comment]
Hi @davidroth, I suspect this issue is unrelated to trade control IP blocks, but I am investigating internally to make sure. Thanks for your patience.

**Comment by davidroth** [comment]
I retried this today and it seems the host is now reachable via IP4 on both subnets.

**Comment by crw** [comment]
Thanks! In the background I'm checking on the status of those IPs, if nothing else we'll have more information to go on if something similar happens in the future.

**Comment by tboerger** [comment]
I'm having the same issue with https://apps.db.ripe.net/db-web-ui/lookup?source=ripe&key=195.201.112.0%20-%20195.201.119.255&type=inetnum maybe somebody could look into that too? I have written to discuss because of that at https://discuss.hashicorp.com/t/failed-to-install-providers/37637

**Comment by crw** [comment]
@tboerger thanks for the report. I will report this through the usual channels. In the meantime, most of these issues have "resolved itself," whether our upstream vendor has unblocked the IPs without our intervention or it is some other unrelated  issue, I cannot say. I will report back if I have new info.
