### ISSUE TITLE
Not able to enable Appliance mode support

### ISSUE THREAD

**Issue by saurabh71669** [hashicorp/terraform#30590]
I am trying to enable Appliance mode support for one of the vpc, I am getting this error when i do terraform apply:

(and one more similar warning elsewhere)
[0m[0m
[1m[31mError: [0m[0m[1merror creating EC2 Transit Gateway VPC Attachment: DuplicateTransitGatewayAttachment: tgw-09999fee6481d1d82 has non-deleted Transit Gateway Attachments with same VPC ID.
	status code: 400, request id: 0011b552-05fc-44e9-96ff-88aecf4a3f38[0m

[0m  on main.tf line 15, in resource "aws_ec2_transit_gateway_vpc_attachment" "appliance":
  15: resource "aws_ec2_transit_gateway_vpc_attachment" "appliance" [4m{[0m

Do anyone knows how to fix this error.

Terraform Plan:

Terraform will perform the following actions:

  # aws_ec2_transit_gateway_vpc_attachment.appliance will be created
  + resource "aws_ec2_transit_gateway_vpc_attachment" "appliance" {
      + appliance_mode_support                          = "enable"
      + dns_support                                     = "enable"
      + id                                              = (known after apply)
      + ipv6_support                                    = "disable"
      + subnet_ids                                      = [
          + "subnet-01dc90103d8a35e4f",
          + "subnet-09627bda90d5d2ae2",
        ]
      + tags_all                                        = (known after apply)
      + transit_gateway_default_route_table_association = true
      + transit_gateway_default_route_table_propagation = true
      + transit_gateway_id                              = "tgw-09999fee6481d1d82"
      + vpc_id                                          = "vpc-0bb0c10dfe053ce4f"
      + vpc_owner_id                                    = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Note : My terraform version is 0.13.5

**Comment by apparentlymart** [comment]
Hi @saurabh71669!

This seems to be an error from the AWS API rather than from Terraform itself, so this would be an AWS provider usage question rather than a Terraform Core bug. Given that, I suggest asking about it in [the AWS provider's community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). We use issues in this repository only for bug reports and feature requests for Terraform, and so I'm going to close this. Thanks!
