### ISSUE TITLE
Unable to set minimum TLS version in  Azure Sql server and Deny public network access

### ISSUE THREAD

**Issue by kssampath** [hashicorp/terraform#30597]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server

There is no option to set  Deny public network access and to set Minimum TLS version in Sql server. 
Please help me with this we need this feature in our project.

Thank you

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
