### ISSUE TITLE
Releases not accessible from some regions

### ISSUE THREAD

**Issue by PaveLGIL** [hashicorp/terraform#30591]
https://releases.hashicorp.com/terraform/

![Screenshot 2022-03-01 at 12 29 47](https://user-images.githubusercontent.com/15833990/156158067-01bfe688-2ffc-403f-aa62-a5eb15805001.png)

**Comment by jbardin** [comment]
Hi @PaveLGIL,

Are you still experiencing issues? That looks like the edge cache you were hitting was having a problem, but I have not been able to replicate the failure from other locations, so it may be resolved already.

**Comment by PaveLGIL** [comment]
Hello! I don't see any problems using US VPN, but still can't access it form Belarus without VPN.

**Comment by pavelpikta** [comment]
Hi @jbardin 
I also have this problem in Belarus. Trying VPN Russia also cause this problem.

**Comment by IKabdyushev** [comment]
Same for me, experiencing same problem in Belarus at least several hours.

**Comment by PaveLGIL** [comment]
Also
![Screenshot 2022-03-01 at 17 10 53](https://user-images.githubusercontent.com/15833990/156184561-4ea37d0b-1166-4b0d-b45f-b2b3028ef78b.png)

**Comment by y6vmeq** [comment]
I have the same problem in Belarus.

**Comment by arascheuski** [comment]
I have the same issue in Belarus.

**Comment by jbardin** [comment]
Unfortunately I think that Belarus recently fell under Russia-related US sanctions, which we don't have any individual control over. These were last updated this week, and probably only implemented just now by Fastly. There may be more information available through the links on our [Trade Controls](https://www.hashicorp.com/trade-controls) page.

**Comment by dzmitryastrouski** [comment]
Who would have thought that Putin's KGB, army forces and Lukashenko's government use terraform?!
But they blocked all the IT engineers. That's how personal sanctions are enforced. :(

**Comment by arjanfrans** [comment]
We are having similar issues on a Germany based server. It seems to work when downloading from the host system, but for some reason inside of a Docker container we are getting this error.

**Comment by crw** [comment]
@arjanfrans Your issue is likely unrelated, and is likely some type of networking issue. If you can track it down to a Terraform bug, please open a new issue with all of the requested details.

**Comment by fallen-up** [comment]
> Because of the conflict underway in Ukraine, HashiCorp is prohibiting availability of our products and services in Russia and Belarus.

@crw You must understand that the "people in russia" <> "the russian government". But you implement blocking towards and for people who are against the war 👎

**Comment by PaveLGIL** [comment]
> > Because of the conflict underway in Ukraine, HashiCorp is prohibiting availability of our products and services in Russia and Belarus.
> 
> @crw You must understand that the "people in russia" <> "the russian government". But you implement blocking towards and for people who are against the war 👎

Completely agree!

**Comment by crw** [comment]
Thanks for the feedback! We do hear your feedback, even if we cannot respond to it directly. As this issue cannot be resolved through the issue process, I am going to lock the thread. Thanks again for your contributions.
