### ISSUE TITLE
Plan unable to execute with Space in key=value --> key = value

### ISSUE THREAD

**Issue by mohitwasnik132** [hashicorp/terraform#30600]
#### Putting  a space between variable name and value causes a error message
```HCL
F:\terraform-scripts\>terraform plan -var "length = 2"

│ Error: Value for undeclared variable
│
│ A variable named "length " was assigned on the command line, but the root module does not declare a variable of that name. To use this value, add a "variable" block to the configuration.
```

while

```HCL
F:\terraform-scripts\>terraform plan -var "length=2" -var "separator=."   

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
```
Executes perfectly.

### Terraform Version

```
Terraform v1.1.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.3.0
```

### Terraform Configuration Files
```terraform

resource "random_pet" "spacey" {
  prefix     = var.prefix[1]
  length     = var.length
  separator = var.separator
}

variable "prefix" {
  type    = list(any)
  default = ["Err", "Bugy", "meh"]
}

variable "length" {
  default = "1"
}

variable "separator" {
  default = "."
}

output "pet" {
  value = random_pet.spacey
}
```

### Expected Behavior

on 
```terraform
terraform plan  -var "variable1name = value1" -var "variable2name = value2"
```
Please notice the "space" before and after "="
The plan should've executed successfully. Which it does, when spaces are removed  (find the attached image and code).

### Actual Behavior
The code spews confusing error , the one stated at the start of this post.

This error should be prompting to remove spaces instead of 

```HCL
│ Error: Value for undeclared variable
```

### Steps to Reproduce

Just regular terraform workflow. 

```terraform
terraform plan -var "length = 2" -var "separator = ."
#causes one two errors one for each argument

terraform plan -var "length = 2" -var "separator=."
#causes one error one for length argument

terraform plan -var "length = 2" -var "separator=."
#no space no errors. Executes

``` 
It could be any code with spaces  around "=" as you assign -var  values.

### Additional Context

Since variable is declared. Values are ok. It's just a small-innocent mistake(?) at user's part. 
I don't know if others have reported this issue, (I could be naive and posting it repeat)
Or if it qualifies as Documentation/Feature request, So here I am.

Seems like it isn't the bug/issue, from the issue#11 as it's closed.
but documents still lack and could potentially lead a beginner astray. 
Please Consider updating/mentioning this into the documentation, if this issue can't be helped/resolved.  

### References
[Input Variable Documentation](https://learn.hashicorp.com/tutorials/terraform/aws-variables)
[Variables Documentation](https://www.terraform.io/language/values/variables)
[tf-helper issue #11](https://github.com/hashicorp-community/tf-helper/issues/11)
![bug-space-in-var](https://user-images.githubusercontent.com/69758819/156387533-238b78a7-f043-4185-83b6-1fba86b4a04c.png)

**Comment by crw** [comment]
Thanks for this issue report. I'm going to float it past the docs team to see what they think.

**Comment by mohitwasnik132** [comment]
> Thanks for this issue report. I'm going to float it past the docs team to see what they think.

That would be wonderful. Thank you @crw

**Comment by kmoe** [comment]
The error message here is certainly confusing. It may be possible to detect the case in which there are spaces around the "=" and return a better error message. In any case this could do with better documentation. Leaving this open in case we fix the error message.

**Comment by apparentlymart** [comment]
If we do ultimately elect to change the behavior here to treat the spaces differently, I agree with @kmoe that it would be better to still return an error but to make that error more specific, rather than to silently allow it.

Although silently allowing a space before the equals sign would not really hurt _too much_, because a space is never valid to appear in a variable name anyway, a space _after_ the equals sign should always be taken literally because it is valid for a string value to start with a space, even though I would agree that it's not _typical_ for a string value to start with a space. Given that, I think it's better to be consistent and treat a space before the equals sign as if it were a part of the variable name, and then treat it as an error because there is no variable of that name (and such a name would be impossible, due to the identifier rules).

**Comment by mohitwasnik132** [comment]
@apparentlymart I agree. Since nobody can/ "should" make such variable, document on variable character contrains should mention spaces not allowed.
Even though nobody will assign "(space) " as variable value, or  start value like that.. 
A small note should suffice that these fringe cases may throw error with certain error code. That way beginners shall not go on to the wild goose chase or some one who think since "fmt" arranges code stuff symmetrically , why not pass equally good looking symmetrical, well balanced arguments to commands as well, or someone might happen to copy from code in which case they will only remove the quotes and leave spaces, leading to error.

**Comment by laurapacilio** [comment]
Hi all! I put up a PR to help address this issue in the docs. It feels like a simple "Terraform errors if you add spaces" should suffice, but I'm happy to edit if you think it needs more context or detail. Thank you! 

https://github.com/hashicorp/terraform/pull/30969
