### ISSUE TITLE
Inter-module use of required resource attributes do not properly calculate dependencies

### ISSUE THREAD

**Issue by mbrancato** [hashicorp/terraform#30607]
### Terraform Version

```
% terraform version
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/vault v3.3.1
```

### Terraform Configuration Files

The Terraform attribute schema supports several flags, including:
- Computed: https://www.terraform.io/plugin/sdkv2/schemas/schema-behaviors#computed
- Required: https://www.terraform.io/plugin/sdkv2/schemas/schema-behaviors#required

The `Computed` and `Required` flags cannot be used together. I might be late to this game, but cannot find good documentation how to handle the behavior differences here. The following behaviors differ when using these attributes inter-module vs intra-module.

When used inter-module or intra-module, `Computed` attributes will flag that the value is not yet known during a `terraform plan`. Resources that depend on this resources will show `known after apply` during the plan, and be properly created during the apply.

When used intra-module, `Required` attributes will flag that the value is not yet known during a `terraform plan`. Resources that depend on this resources will show `known after apply` during the plan, and be properly created during the apply. Even though the value for a `Required` attribute is known during the plan, the resource referencing this value is flagged so that won't be used until the attribute's resource is created.

When used inter-module, `Required` attributes will treat the value as known during a `terraform plan`. Resources that depend on this attribute will attempt the access the value during the plan. In cases where this is used to feed a data source, this may fail as it tried to access a resource that is not yet created.

I'll use the HashiCorp Vault provider here to illustrate this issue. 

I could have an environment where I use a single root module to configure a password policy, and later, use that policy to generate random passwords. I can create this single module using the following:

```terraform
resource "vault_password_policy" "alpha" {
  name = "alpha"

  policy = <<EOT
    length = 20
    rule "charset" {
      charset = "abcdefghijklmnopqrstuvwxyz"
      min-chars = 1
    }
  EOT

}

data "vault_generic_secret" "random_pw" {
  path = "sys/policies/password/${vault_password_policy.alpha.name}/generate"
}

output "password" {
  value = data.vault_generic_secret.random_pw.lease_id
}
```

And the plan output would look like:

```
Terraform will perform the following actions:

  # data.vault_generic_secret.random_pw will be read during apply
  # (config refers to values not yet known)
 <= data "vault_generic_secret" "random_pw"  {
      + data             = (sensitive value)
      + data_json        = (sensitive value)
      + id               = (known after apply)
      + lease_duration   = (known after apply)
      + lease_id         = (known after apply)
      + lease_renewable  = (known after apply)
      + lease_start_time = (known after apply)
      + path             = "sys/policies/password/alpha/generate"
    }

  # vault_password_policy.alpha will be created
  + resource "vault_password_policy" "alpha" {
      + id     = (known after apply)
      + name   = "alpha"
      + policy = <<-EOT
                length = 20
                rule "charset" {
                  charset = "abcdefghijklmnopqrstuvwxyz"
                  min-chars = 1
                }
        EOT
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

If I want to breakup my infrastructure into modules, I might separate out the Value config, and then read the password generator elsewhere in other modules.

root module:
```terraform
module "vault_config" {
  source = "./vault_config"
}

module "cloud_db" {
  source = "./cloud_db"
  password_path = module.vault_config.password_generator_path
}

output "lease" {
  value = module.cloud_db.lease
}
```

vault_config module:
```terraform
resource "vault_password_policy" "alpha" {
  name = "alpha"

  policy = <<EOT
    length = 20
    rule "charset" {
      charset = "abcdefghijklmnopqrstuvwxyz"
      min-chars = 1
    }
  EOT

}

output "password_generator_path" {
  value = "sys/policies/password/${vault_password_policy.alpha.name}/generate"
}
```

cloud_db module:
```terraform
variable "password_path" {}

data "vault_generic_secret" "random_pw" {
  path = var.password_path
}

output "lease" {
  value = data.vault_generic_secret.random_pw.lease_id
}
```

And the plan output would look like:

```
│ Error: no secret found at "sys/policies/password/alpha/generate"
│ 
│   with module.cloud_db.data.vault_generic_secret.random_pw,
│   on cloud_db/main.tf line 4, in data "vault_generic_secret" "random_pw":
│    4: data "vault_generic_secret" "random_pw" {
│ 
```

### Expected Behavior
The plan should succeed. The use of a `Required` attribute should behave the same with both inter-module and intra-module use.

### Actual Behavior
Any `Required` attributes passed to module variables are immediately fulfilled and cause a plan failure.

**Comment by mbrancato** [comment]
To be clear, i'm not looking for a workaround. But for those who are, many times there is a computed attribute that may work as a replacement for the required attribute. For the Vault example above, the `id` attribute can be used as a replacement computed attribute.

**Comment by jbardin** [comment]
Hi @mbrancato,

The behavior you are seeing here is described in [Data Sources Dependencies](https://www.terraform.io/language/data-sources#data-resource-dependencies)

> In order to ensure that data sources are accessing the most up to date information possible in a wide variety of use cases, arguments directly referencing managed resources are treated the same as if the resource was listed in `depends_on`. This behavior can be avoided when desired by indirectly referencing the managed resource values through a `local` value.

That admittedly is a bit awkward, but was required for backwards compatibility in too many cases to break cleanly.

The problem with the configuration presented is that `vault_password_policy.alpha.name` is not computed, and is statically defined in the configuration, therefore known during plan and will not cause the data source to be deferred until apply. You can work around this using `depends_on` in the data source, however it is better if the data source and resources can work together to give the behavior needed. If there are no computed values from the `vault_password_policy` which can be referenced, and that resource is frequently used with data sources which need computed values, then it may be useful to submit an enhancement request to the vault provider.

Since this is working as expected I'm going to close the issue, but feel free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) for more questions.

Thanks!
