### ISSUE TITLE
Add "reuse_key_for_cluster_volumes" option for "databricks_mws_customer_managed_keys"

### ISSUE THREAD

**Issue by Conor-Gilbert** [hashicorp/terraform#30611]
Hi

In the "databricks_mws_customer_managed_keys" resource, under "key_info" databricks offers the option "reuse_key_for_cluster_volumes" but terraform does not 

Would it be possible to add this to allow for full functionality please

Thank you

**Comment by kmoe** [comment]
Thanks for the issue. Since this is a feature request for the Databricks provider, and not Terraform Core, please open an issue in that provider's repository instead.
