### ISSUE TITLE
azurerm terraform import Azure ID is serverFarms not serverfarms

### ISSUE THREAD

**Issue by Elthas17** [hashicorp/terraform#30621]
### Terraform Version

```
Terraform v1.1.6                                                                    
on windows_amd64                                                                    
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0  
```

### Terraform Configuration Files
NA

### Debug Output
NA

### Expected Behavior

When importing an existing resource the Azure Resource ID is required in the command:
`terraform import <Terraform Resource Name>.<Resource Label> <Azure Resource ID>` 

The Azure Resource ID contains 'resourceFarms' and not 'resourcefarms' , but terraform expects it to contain 'resourcefarms' so the command  fails. when i change the ID so that it contains 'resourcefarms' it passes but this is not what Azure provides as an ID. 

### Actual Behavior
When running
`terraform import <Terraform Resource Name>.<Resource Label> <Azure Resource ID>` 
as
`terraform import azurerm_app_service_plan.<myappserviceplan> /subscriptions/<mysubscription>/resourceGroups/<myresourcegroup>/providers/Microsoft.Web/serverFarms/<myappserviceplan>`

i get the error:
` Error: parsing Resource ID "/subscriptions/<mysubscription>/resourceGroups/<myresourcegroup/serverFarms/freeserviceplan": ID was missing the 'serverfarms' element`

when i run it as 
`terraform import azurerm_app_service_plan.<myappserviceplan> /subscriptions/<mysubscription>/resourceGroups/<myresourcegroup>/providers/Microsoft.Web/serverfarms/<myappserviceplan>` 
the command succeeds but this is not the ID given by Azure in the azure web portal. 

### Steps to Reproduce
run above commands

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
