### ISSUE TITLE
Terraform always wants to apply AWS userdata changes even when using -target to specifically avoid it

### ISSUE THREAD

**Issue by oneandoneis2** [hashicorp/terraform#30635]
I'm trying to change the sizing of an autoscaling group, but even with -target set specifically to only make this cange, TF insists on dragging in an unwanted userdata change as well. There's no reason these two changes need to be coupled, and I often encounter userdata changes that *cannot* be prevented via -targetting. Which does rather defeat the point of having a -target option in the first place.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
