### ISSUE TITLE
Please add a warning when uploading large files for terraform cloud plans

### ISSUE THREAD

**Issue by mbyio** [hashicorp/terraform#30630]
### Current Terraform Version

```
Terraform v1.1.7
on darwin_arm64
```

### Use-cases

This issue is primarily concerning the Terraform Cloud CLI workflow. We have a monorepo containing all the Terraform code for our organization. Because it is a monorepo, sometimes extra files are added that don't need to be uploaded to Terraform Cloud to run a plan. Recently, it has taken a really long time to start plans in our monorepo, and after some extensive debugging, I traced the issue to a few large zip files that were included by accident. They caused the config upload to be after 100 MiB, which takes a while to upload on a typical internet connection.

### Attempted Solutions

To my knowledge, there currently is no easy way to find and debug a problem like this. You would have to parse the `.terraformignore` file correctly, and also replicate the code producing the archive. I only figured out the problem by tracing the Terraform code to https://github.com/hashicorp/go-slug. I cloned it locally and edited the code to record file names and sizes and then print the largest files. Omitting those files using `.terraformignore` brought our plan start time down from minutes to just a few seconds!

### Proposal

I think most of the time, it is a mistake if users upload files that are larger than, say, 0.5 MiB. It would be nice and user friendly if Terraform warned people when they are uploading large files. It should also probably warn people if they are uploading a large config archive (or just tell them the size of the archive). That way most people can quickly identify and fix these issues on their own.

If I were adding this feature, I'd record file sizes along with file names in go-slug's Meta struct: https://github.com/hashicorp/go-slug/blob/master/slug.go#L14. I'd pass the Meta struct up through the code as a return value from `Upload`: https://github.com/hashicorp/terraform/blob/afb956d7453c4c3a283c6e666e7e6a1728670878/internal/cloud/backend_plan.go#L161 Then I'd print, say, the top 5 largest files that are larger than 0.1 MiB, and I'd also print the total archive size. (There are probably other ways to implement it, I haven't contributed to Terraform before, etc. etc.)

**Comment by crw** [comment]
Thanks for the enhancement request @mbyio! I'll forward this on to the Terraform Cloud team. You might also consider suggesting this through your official support channels or account team as well, just so they are tracking the request with your account. Thanks again!

**Comment by barrettclark** [comment]
Closing because using the `.terraformignore` and keeping an eye on local files is the current recommendation.

**Comment by mbyio** [comment]
Hi @barrettclark. As I explained above, you can't just "keep an eye on local files" because you would have to parse the `.terraformignore` file.
