### ISSUE TITLE
Terraform crash

### ISSUE THREAD

**Issue by vamshisiram** [hashicorp/terraform#30646]
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:55 +0x154
panic({0x2250d80, 0x401aac0})
/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hashicorp/terraform/internal/cloud.(*Cloud).Operation(0xc0000276b0, {0x2b4fbf0, 0xc000052088}, 0xc0006e70e0)
/home/circleci/project/project/internal/cloud/backend.go:607 +0x4a
github.com/hashicorp/terraform/internal/command.(*Meta).RunOperation(0xc000001860, {0x7f71defd0318, 0xc0000276b0}, 0xc0006e70e0)
/home/circleci/project/project/internal/command/meta.go:401 +0xde
github.com/hashicorp/terraform/internal/command.(*ApplyCommand).Run(0xc000001860, {0xc00004c200, 0x0, 0x0})
/home/circleci/project/project/internal/command/apply.go:121 +0x59b
github.com/mitchellh/cli.(*CLI).Run(0xc00001e280)
/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.realMain()
/home/circleci/project/project/main.go:309 +0x1509
main.main()
/home/circleci/project/project/main.go:58 +0x19

**Comment by crw** [comment]
Hi @vamshisiram, thanks for the report. If possible, can you please give us a reproduction use case and a trace log from a run when this crash occurs? Thanks again!
