### ISSUE TITLE
Facing Issue while creating a VM from Data Domain Virtual Edition (DDVE) Custom image using terraform

### ISSUE THREAD

**Issue by vineet93** [hashicorp/terraform#30642]
While creating a VM using  Data Domain Virtual Edition (DDVE) Custom image by default a Data disk is getting created and attached to the VM and it's successfully created but when we are creating VM using terraform it's getting exceptioned out  with the below error.

Error: creating Linux Virtual Machine "vm-x-dd-dv-1ln1" (Resource Group "rg-1line-dev"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="StorageProfile.dataDisks.lun does not have required value(s) for image specified in storage profile." Target="storageProfile"
│ 
│   with module.linux_virtual_machine["vm-x-dd-dv-1ln1"].azurerm_linux_virtual_machine.linuxvm,
│   on ..\Infrastructure-TFModule-VM\src\vm-linux\main.tf line 27, in resource "azurerm_linux_virtual_machine" "linuxvm":
│   27: resource "azurerm_linux_virtual_machine" "linuxvm" {

Here is my terraform Configuration for my VM :-

"vm-x-dd-dv-1ln1" = {
      nic_private_ip     = "10.252.146.140",
      nic_name           = "nic-x-dd-dv-1ln1",
      nic_ip_config_name = "ipconfig-x-dd-dv-1ln1",
      public_ip_name     = "",
      accel_networking   = "true",
      subnet_name        = "snet-dev-1line-ap-scus-001",
      osdisk_name        = "osdisk-x-dd-dv-1ln1",
      mgdisk_settings    = {
      "mgdisk-x-dd-dv-1ln1" = {
          name        = "mgdisk-x-dd-dv-1ln1"
          size        = "100"
          stact_type  = "Standard_LRS"
          lun         = "1"
          caching     = "ReadWrite"
        }
      },
      vm_size            = "Standard_D4s_v4",
      osdisk_stact_type  = "Premium_LRS",
      image_publisher    = "dellemc",
      image_offer        = "dell-emc-datadomain-virtual-edition-v4",
      image_sku          = "ddve-40-ver-7105",
      image_version      = "latest",
      av_set_name        = ""
    }

Please let me know if someone has faced similar issue.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
