### ISSUE TITLE
Changing range_key type in aws_dynamodb_table does not trigger replacement

### ISSUE THREAD

**Issue by necro351** [hashicorp/terraform#30644]
### Terraform Version

```
terraform ▶ terraform version
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
```

### Terraform Configuration Files
```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.4.0"
    }
  }
}

provider "aws" {
  shared_config_files      = ["/Users/rick/.aws/config"]
  shared_credentials_files = ["/Users/rick/.aws/credentials"]
  profile                  = "staging"
}

resource "aws_dynamodb_table" "basic-dynamodb-table" {
  name           = "GameScores"
  billing_mode   = "PROVISIONED"
  read_capacity  = 20
  write_capacity = 20
  hash_key       = "UserLocation"
  range_key      = "GameTitle"

  attribute {
    name = "UserLocation"
    type = "S"
  }

  attribute {
    name = "GameTitle"
    type = "N"
  }

  tags = {
    Name        = "dynamodb-table-1"
    Environment = "production"
  }
}
```

### Expected Behavior
When you change the type of a range_key the table will need to be replaced as the application cannot use, e.g., a string-type range key (S) as a number-type (N), and certainly query scans will be in the unexpected/wrong order. I did not check, but I believe DynamoDB would just return errors to the application if it tried to use 'S' type attribute values for, e.g., an 'N' type attribute/range-key.

Given this, terraform should report the table must be replaced if you change the type.

### Actual Behavior
Terraform says the infrastructure already matches and there is nothing to do when you change the type.

### Steps to Reproduce
```
1. terraform init
2. terraform plan
3. terraform apply
4. witness everything is OK
5. change the type of GameTitle from N to S
6. terraform apply claims no need to do anything, infrastructure matches (this is wrong)
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by necro351** [comment]
Thanks, just cross-posted to the other tracker. Hopefully they can resolve it there.
