### ISSUE TITLE
Inconsistent cidrsubnet netnum numbering: incorrect when negative newbits

### ISSUE THREAD

**Issue by OJFord** [hashicorp/terraform#30654]
### Terraform Version

```
1.1.7
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

```shell
> cidrsubnet("12.34.56.78/32", -8 ,0)
```
and
```
> cidrsubnet("12.34.56.78/24", 0 ,0)
```

should be equivalent, `"12.34.56.0/24"`.

### Actual Behavior

```
> cidrsubnet("12.34.56.78/32", -8 ,0)
"12.34.56.78/24"
```

### Steps to Reproduce

1. `$ terraform console`
2. `> cidrsubnet("12.34.56.78/32", -8 ,0)`

**Comment by jbardin** [comment]
Duplicate of #17724

**Comment by OJFord** [comment]
I don't think that's a duplicate in terms of the issue, but just for the avoidance of confusion perhaps you meant it's a duplicate in terms of resolution: i.e. it's not intended to be supported at all anyway.

Thanks.
