### ISSUE TITLE
Issue in reading file which get generated through local provisioner script.

### ISSUE THREAD

**Issue by Kritika-git** [hashicorp/terraform#30652]
Hi Team ,
I am unable to read a file which get created through my local provisioner command.
provisioner “local-exec” {
command = “ command = "${path.module}/healthcheck.sh ${vcd_vapp_vm.vmware_instance[0].name} ${vcd_vapp_vm.vmware_instance[0].network[0].ip}"
}
I need to pass content of the file which get created during runtime and pass it to my ignition data here .“guestinfo.ignition.config.data” . Please suggest if i can try other way out to read the file which get created during runtime for each instance .Thank you!!

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
