### ISSUE TITLE
Error 405 not allowed

### ISSUE THREAD

**Issue by pnx472** [hashicorp/terraform#30667]
Hello,

> Because of the conflict underway in Ukraine, HashiCorp is prohibiting availability of our products and services in Russia and Belarus.

The problem is that you use unreliable geolocation service to implement restrictions and a bunch of servers are being blocked which are not located in those regions.

I need to submit data for correction to maxmind and I need to wait for days before I can deploy code to production if they manage to do correction otherwise I will need to look for different solutions.

**Comment by crw** [comment]
Hi @pnx472, thanks for the report. In order to troubleshoot further, I would need to know which IPs you believe are being incorrectly blocked. Please let me know.

**Comment by pnx472** [comment]
There is a support ticket number 68531 where you can see more information about it.

The issue is that on this list of [geolocation-providers](https://whatismyipaddress.com/geolocation-providers) 6/9 show correct location which is not reliable and if you look at "Geolocation Accuracy section" it should be more clear how accurate they are. Maxmind has accepted data correction but I still need to wait for Friday or extra 4 days for data to be updated.

Maybe you could check accuracy radios of geo location service and/or compare the location with one of others providers.

**Comment by crw** [comment]
Hi @pnx472, thanks for the follow-up. I have relayed this info internally. As you have a support ticket open for this issue, I am going to close this ticket but please feel free to update here if you are not seeing a resolution within the next week or so.
