### ISSUE TITLE
cross-platform file provisioning fails due to command escaping

### ISSUE THREAD

**Issue by tgross** [hashicorp/terraform#30661]
Using the `file` provisioner from macOS to Windows fails with the following error in the logs:

> 2022-03-11T16:15:28.946-0500 [ERROR] scp stderr: "At line:1 char:7\r\n+ "scp" -vt /tmp\r\n+ ~~~\r\nUnexpected token '-vt' in expression or statement.\r\nAt line:1 char:11\r\n+ "scp" -vt /tmp\r\n+ ~~~~\r\nUnexpected token '/tmp' in expression or statement.\r\n + CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordEx \r\n ception\r\n + FullyQualifiedErrorId : UnexpectedToken\r\n \r\n"

### Terraform Version

```
$ terraform version
Terraform v1.1.4
on darwin_amd64
```

Also, the ssh version, just in case that turns out to be relevant:

```
$ ssh -V
OpenSSH_8.1p1, LibreSSL 2.7.3
```

### Terraform Configuration Files

A minimal configuration is as follows:

```terraform
variable "ip_address" {
  description = "IP address where the Windows host can be reached"
  default     = ""
}

variable "key_file_path" {
  description = "The path to the file on disk with your private ssh key"
  default     = "id_rsa.pem"
}

resource "null_resource" "test" {

  connection {
    type            = "ssh"
    user            = "Administrator"
    host            = var.ip_address
    port            = "22"
    private_key     = file(var.key_file_path)
    target_platform = "windows"
    timeout         = "1m"
  }

  provisioner "file" {
    source      = "main.tf"
    destination = "/tmp/"
  }
}
```

### Debug Output

Full `TF_LOG=trace` output can be found at https://gist.github.com/tgross/70401841ab5ee75f7bce2e51e3347171 but it appears that the relevant bit is here:

> 2022-03-11T16:15:28.628-0500 [DEBUG] opening new ssh session
> 2022-03-11T16:15:28.648-0500 [DEBUG] Starting remote scp process:  "scp" -vt /tmp
> 2022-03-11T16:15:28.663-0500 [DEBUG] Started SCP session, beginning transfers...
> 2022-03-11T16:15:28.664-0500 [DEBUG] Copying input data into temporary file so we can read the length
> 2022-03-11T16:15:28.685-0500 [DEBUG] Beginning file upload...
> 2022-03-11T16:15:28.938-0500 [DEBUG] SCP session complete, closing stdin pipe.
> 2022-03-11T16:15:28.938-0500 [DEBUG] Waiting for SSH session to complete.
> 2022-03-11T16:15:28.946-0500 [ERROR] scp stderr: "At line:1 char:7\r\n+ \"scp\" -vt /tmp\r\n+       ~~~\r\nUnexpected token '-vt' in expression or statement.\r\nAt line:1 char:11\r\n+ \"scp\" -vt /tmp\r\n+           ~~~~\r\nUnexpected token '/tmp' in expression or statement.\r\n    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx \r\n   ception\r\n    + FullyQualifiedErrorId : UnexpectedToken\r\n \r\n"
> 2022-03-11T16:15:28.946-0500 [ERROR] Process exited with status 1
> 2022-03-11T16:15:28.947-0500 [WARN]  Errors while provisioning null_resource.test with "file", so aborting

### Expected Behavior

The file should be uploaded. This is the result with Terraform <1.1.0:

```
$ terraform apply -auto-approve -var ip_address="$IP_ADDRESS" -var key_file_path="$(pwd)/ssh.key"
null_resource.test: Creating...
null_resource.test: Provisioning with 'file'...
null_resource.test: Creation complete after 0s [id=3664098153176656293]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Actual Behavior

The file was not uploaded. This is the result with Terraform >=1.1.0:

```
$ terraform apply -auto-approve -var ip_address="$IP_ADDRESS" -var key_file_path="$(pwd)/ssh.key"

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test: Creating...
null_resource.test: Provisioning with 'file'...
╷
│ Error: file provisioner error
│
│   with null_resource.test,
│   on main.tf line 23, in resource "null_resource" "test":
│   23:   provisioner "file" {
│
│ Upload failed: Process exited with status 1
╵
```

### Steps to Reproduce

1. Launch a Windows 2016 server running sshd
2. `terraform init`
3. `terraform apply -var ip_address=$ADDR -var -key_file_path=$PATH_TO_KEY`

### References

In https://github.com/hashicorp/terraform/pull/28626 @eastebry added platform-specific escaping to the `file` provisioner in order to avoid shell injection in the destination when used with the `ssh` communicator. This escaping includes the following critical bit from @apparentlymart's [`go-shquot`](https://github.com/apparentlymart/go-shquot/blob/4ccb4e9d2c6cf5e7288237772b5f5ef97590fff7/shquot/posix.go#L31-L32):

```go
// The first argument is always quoted so that it will bypass alias expansion
// and function call behaviors in compliant shells.
```

This appears to cause file uploads to fail, but only when uploading cross-platform (ex. macOS to Windows). I did notice that this escaping uses the _target_ platform for escaping, but my understanding is that the `scp` command command is executed in the context of the _user's_ shell, which may not be the same platform. I tried the following patch:

```diff
diff --git a/internal/communicator/ssh/communicator.go b/internal/communicator/ssh/communicator.go
index 6dff03367..20cdb0503 100644
--- a/internal/communicator/ssh/communicator.go
+++ b/internal/communicator/ssh/communicator.go
@@ -13,6 +13,7 @@ import (
        "net"
        "os"
        "path/filepath"
+       "runtime"
        "strconv"
        "strings"
        "sync"
@@ -825,14 +826,9 @@ func (c *bastionConn) Close() error {
        return c.Bastion.Close()
 }

-func quoteShell(args []string, targetPlatform string) (string, error) {
-       if targetPlatform == TargetPlatformUnix {
-               return shquot.POSIXShell(args), nil
-       }
-       if targetPlatform == TargetPlatformWindows {
+func quoteShell(args []string, _ string) (string, error) {
+       if runtime.GOOS == TargetPlatformWindows {
                return shquot.WindowsArgv(args), nil
        }
-
-       return "", fmt.Errorf("Cannot quote shell command, target platform unknown: %s", targetPlatform)
-
+       return shquot.POSIXShell(args), nil
 }
 ```

But I got the same error with different escaping:

> 2022-03-11T16:58:00.955-0500 [ERROR] scp stderr: "At line:1 char:7\r\n+ 'scp' -vt /tmp\r\n+       ~~~\r\nUnexpected token '-vt' in expression or statement.\r\nAt line:1 char:11\r\n+ 'scp' -vt /tmp\r\n+           ~~~~\r\nUnexpected token '/tmp' in expression or statement.\r\n    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx \r\n   ception\r\n    + FullyQualifiedErrorId : UnexpectedToken\r\n \r\n"

If I manually remove the `'` around `scp` via `strings.ReplaceAll`, everything works fine. So I'm not sure how to fix this problem without reintroducing the original security concern from https://github.com/hashicorp/terraform/pull/28626 (otherwise I'd have a patch for you already!)

The Nomad end-to-end test suite is still on Terraform 0.14 :blush: so I noticed this while attempting to stand up the test infrastructure from my laptop which has a current version of Terraform. For now we'll continue to pin to the older version, but this likely impacts anyone doing cross-platform uploads.

**Comment by apparentlymart** [comment]
Hi @tgross,

The shapes of both of the remote error messages you saw here seem to suggest that the remote command is being run by PowerShell rather than the standard Windows command interpreter (cmd.exe), so I think it makes sense that neither of the two escaping strategies worked: PowerShell is incompatible with both Unix shells and Windows command interpreter.

Do you know if having PowerShell be the primary command interpreter for Windows SSH is a configurable setting on the server? In our testing so far it seemed to be cmd.exe that interpreted the command, and thus this particular escaping rule worked in that case.

It seems like a thorough solution to this will require allowing the user to explicitly specify what kind of shell will parse the scp command and include PowerShell as one of the options, which seems non-ideal but also seems like necessary complexity given what we've seen here.

**Comment by tgross** [comment]
I was able to verify that switching the default shell worked-around the problem for us, so we're unblocked on this issue for now. Thanks!

**Comment by crw** [comment]
Speaking with @apparentlymart, I think the next step for this ticket is a documentation update. Something along the lines of: 

> the `file` provisioner when talking to a Windows system over SSH requires that OpenSSH be configured to run commands with `cmd.exe`, not by PowerShell.

There is example code linked from this comment: https://github.com/hashicorp/terraform/issues/30661#issuecomment-1067082006.

**Comment by laurapacilio** [comment]
hi! I put up a PR that will hopefully help clarify this for future users. Let me know if anyone has feedback. https://github.com/hashicorp/terraform/pull/30712

@tgross - thank you for bringing this to our attention!
