### ISSUE TITLE
azurerm_backup_protected_file_share source_storage_account_id issue

### ISSUE THREAD

**Issue by neil-andrews** [hashicorp/terraform#30677]
error output is 

[1m[31mError: [0m[0m[1mProvider produced inconsistent final plan[0m

 [0mWhen expanding the plan for azurerm_backup_protected_file_share.mai_backup to
 include new values learned so far during apply, provider
 "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
 .source_storage_account_id: was
cty.StringVal("/subscriptions/{subscription id}/resourceGroups/{resource group first part}-MAI/providers/Microsoft.Storage/storageAccounts/maisboxstr01"),
but now
 cty.StringVal("/subscriptions/{subscription id}/resourceGroups/{resource group first part}-mai/providers/Microsoft.Storage/storageAccounts/maisboxstr01").
 
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

it seems like it is providing a non case sensitive resource group which is causing it to error 

resource "azurerm_backup_container_storage_account" "mai-protection-container" {
  resource_group_name = "resource-group"
  recovery_vault_name = azurerm_recovery_services_vault.sswap.name
  storage_account_id  = azurerm_storage_account.mai_storage.id
}

resource "azurerm_backup_protected_file_share" "mai_backup" {
  resource_group_name       = "resource group"
  recovery_vault_name       = azurerm_recovery_services_vault.sswap.name
  source_storage_account_id = azurerm_backup_container_storage_account.mai-protection-container.storage_account_id
  source_file_share_name    = azurerm_storage_share.mai_share.name
  backup_policy_id          = azurerm_backup_policy_file_share.daily.id
  depends_on                = [azurerm_storage_share.mai_share]
}

### Terraform Version

```
Terraform v0.14.11
provider registry.terraform.io/hashicorp/azurerm v2.67.0
provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
