### ISSUE TITLE
remote config with S3 backend fails for region us-west-1

### ISSUE THREAD

**Issue by joescii** [hashicorp/terraform#3067]
If `AWS_DEFAULT_REGION` is set to `us-west-1`, config fails with the following output:

```text
Initialized blank state with remote state enabled!
Error while performing the initial pull. The error message is shown
below. Note that remote state was properly configured, so you don't
need to reconfigure. You can now use `push` and `pull` directly.

Error reloading remote state: RequestError: send request failed
caused by: Get : 301 response missing Location header
```

It never mattered if the bucket/key combo existed or not.  Even if I dropped in a valid `terraform.tfstate` file, it wouldn't fetch it.

After switching `AWS_DEFAULT_REGION` to `us-east-1`, everything worked like a charm.  My understanding from #880 is that `us-east-1` is preferable because of consistency concerns anyway.  Maybe it shouldn't be an option since it doesn't _really_ matter which region you use for S3 in general anyway?

**Comment by mitchellh** [comment]
This was an issue with how we configured the AWS provider and it has since been fixed, tested locally! :)
