### ISSUE TITLE
Terraform import failing with error "The count value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instance will be created.

### ISSUE THREAD

**Issue by Harshadocker** [hashicorp/terraform#30672]
Hi All, 

I am trying to import a resource which is already available in the AWS console, but when importing i am facing the issue "The count value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instance will be created."

I tried replacing the count with for_each but i am facing the same problem. Has any one faced this issue and found any solution. Please help.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
