### ISSUE TITLE
Issue with converting resources to conditional ( count based ). 

### ISSUE THREAD

**Issue by marek-matys** [hashicorp/terraform#30675]
TF version 1.1.0. I've converted resources aws_service_discovery_service, aws_route53_record and plenty more to conditional ( count based ). This was done after infrastructure has already been applied to AWS account ( without "count" ). This fails at plan step. I took a liberty to comment out client sensitive data with "XXXXXXXX"

```
aws_service_discovery_service.discovery[0]: Refreshing state... [id=srv-s6fbgexgym3wa6fi]
aws_route53_record.route53_validation[0]: Refreshing state... [id=Z07426803D5Y22FNGIAFE__1c40c45b2f8893e46a81e851a1a48b05.XXXXXXXXXXXXXXXXXXXXXXXX_CNAME]
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
runtime error: invalid memory address or nil pointer dereferencegoroutine 2314 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x221d240, 0x3ed5b10})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc000e45270, {{}, 0x4d, {0xc000051440, 0x12}, {0xc000ad9640, 0x10}}, {0xc002f63980, 0x30, 0x4})
	/home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x40, {0xc000966880, 0x0, 0xc000080400}, {{}, 0x4d, {0xc000051440, 0x12}, {0xc000ad9640, 0x10}}, ...)
	/home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc000bb3680, {0xc000966880, 0x1, 0x1}, {{}, 0x4d, {0xc000051440, 0x12}, {0xc000ad9640, 0x10}}, ...)
	/home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc000c3d860, {{}, {0xc000966880, 0x1, 0x1}, {{}, 0x4d, {0xc000051440, 0x12}, {0xc000ad9640, ...}}})
	/home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc00239bb50, {0x2aecc00, 0xc000205ea0})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc00239bb50, {0x2aecc00, 0xc000205ea0})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2aecc00, 0xc000205ea0}, 0xa0)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc000204c40, {0x2aecc00, 0xc000205ea0}, {0x7f2dca3a4820, 0xc00239bb50})
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:[133](https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#L133) +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2553ec0, 0xc00239bb50})
	/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0005c5b60, {0x2553ec0, 0xc00239bb50}, 0xc00192ef00)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0xf85
```

**Comment by apparentlymart** [comment]
Hi @marek-matys,

In addition to what @kmoe requested above, I'd suggest also trying this with the latest v1.1 release, which is v1.1.7 at the time of writing. When encountering bugs like this it's best to try upgrading to the latest patch release in the series you are currently using to see if the bug was already fixed.

In this case the scenario you described seems familiar as something we fixed earlier in the series, and so I suspect that upgrading will address it.

If not, please do follow up with any new information you learn while trying it, and with the additional information requested above.

Thanks!

**Comment by marek-matys** [comment]
Sorry, I haven't noticed the template. The changes were introduced to resources below ( the "count" was not present before ). 

resource "aws_acm_certificate" "certificate" {
  count             = (local.app_type_on_schedule == "true" || local.app_type_on_schedule == true) ? 0 : 1
  domain_name       = local.app_endpoint_url
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }

  tags = local.common_tags
}

resource "aws_acm_certificate_validation" "validation" {
  count           = (local.app_type_on_schedule == "true" || local.app_type_on_schedule == true) ? 0 : 1
  certificate_arn = aws_acm_certificate.certificate[0].arn
}


resource "aws_route53_record" "route53_validation" {
  count = (local.app_type_on_schedule == "true" || local.app_type_on_schedule == true) ? 0 : 1

  name    = tolist(aws_acm_certificate.certificate[0].domain_validation_options)[0].resource_record_name
  type    = tolist(aws_acm_certificate.certificate[0].domain_validation_options)[0].resource_record_type
  zone_id = data.aws_route53_zone.public_zone.zone_id
  records = [tolist(aws_acm_certificate.certificate[0].domain_validation_options)[0].resource_record_value]
  ttl     = "300"
}

resource "aws_route53_record" "www" {
  count = (local.app_type_on_schedule == "true" || local.app_type_on_schedule == true) ? 0 : 1
  zone_id         = data.aws_route53_zone.public_zone.zone_id
  name            = local.app_endpoint_url
  type            = "A"
  allow_overwrite = true

  alias {
    name                   = module.ecs_alb[0].alb_dns_name
    zone_id                = module.ecs_alb[0].alb_zone_id
    evaluate_target_health = true
  }
}

Thanks, I'll try newest TF next time ( I've already overcome this issue by re-running this code on Windows - Windows TF version haven't complained :D  )

**Comment by jbardin** [comment]
Thanks @marek-matys,

It sounds like the newer version is going to fix the crash. I'm going to close the issue, but if there still some incorrect behavior I'm not seeing here, feel free to reply or open a new issue with an example to reproduce the problem.
