### ISSUE TITLE
AWS AutoScaling Warm Pool Hibernated State Support

### ISSUE THREAD

**Issue by mab78611** [hashicorp/terraform#30687]
### Current Terraform Version
```1.1.7```

### Use-cases
There was an announcement from AWS last month around AutoScaling Warm Pools and added support for "hibernating" during scale-in. The link to the announcement can be found below:
https://aws.amazon.com/about-aws/whats-new/2022/02/amazon-ec2-auto-scaling-warm-pools-supports-hibernating-returning-instances-warm-pools-scale-in/

We currently have a solution in place where ```pool_state = "Stopped" ``` but would like Terraform to add in support for ```"Hibernated"``` state. 
As of right now Terraform does not support the Hibernated state:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#pool_state
[pool_state](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#

```pool_state) - (Optional) Sets the instance state to transition to after the lifecycle hooks finish. Valid values are: Stopped (default) or Running.```

### Attempted Solutions
Current state:
`warm_pool {
    pool_state                  = "Stopped"
    min_size                    = var.min_size
    max_group_prepared_capacity = var.min_size
  }`

Attempted solution: 
``warm_pool {
    pool_state                  = "Hibernated"
    min_size                    = var.min_size
    max_group_prepared_capacity = var.min_size
  }``

```Error: expected warm_pool.0.pool_state to be one of [Stopped Running], got Hibernated
│ 
│   with aws_autoscaling_group.Palo-Warm,
│   on Autoscaling.tf line 50, in resource "aws_autoscaling_group" "Palo-Warm":
│   50:     pool_state                  = "Hibernated"```


### Proposal

Add in support for Warm Pools and Hibernated state. 
Is there a timeline for when this will be in place? Thanks

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
