### ISSUE TITLE
Error: Provider produced inconsistent final plan for null_resource after modifying VM

### ISSUE THREAD

**Issue by gdsotirov** [hashicorp/terraform#30696]
### Problem description

In a configuration with VM instance and null resource with local-exec provisioner triggered by IP change provider fails to generate consistent final plan when the IP of VM instance changes after modification. There is no such problem if after modification the public IP of the instance remains the same (e.g. static IP is used).

### Terraform Version

```
% terraform --version
Terraform v1.1.1
on darwin_amd64
```
_Note_: It was also reproducible with 0.14 and later.

### Terraform Configuration Files

```tf
resource "google_service_account" "default" {
	account_id   = "service_account_id"
	display_name = "Service Account"
}

resource "google_compute_instance" "my-vm" {
	name		= "my-vm"
	machine_type= "n2-standard-2"

	allow_stopping_for_update	= true

	boot_disk {
		initialize_params {
			image	= "centos-cloud/centos-8"
		}
	}

	network_interface {
		network = "default"
	
		access_config {
			// Ephemeral public IP
		}
	}

	service_account {
		email  = google_service_account.default.email
		scopes = ["cloud-platform"]
	}

	# Wait for the instance to become available
	desired_status	= "RUNNING"
}

resource "null_resource" "vm-setup" {
	depends_on	=	[
		google_compute_instance.my-vm
	]

	triggers = {
		my_vm_ipaddr = google_compute_instance.my-vm.network_interface.0.access_config.0.nat_ip
	}

	provisioner "local-exec" {
		command	= "ansible-playbook --inventory '${local.host_ip},' my-vm-setup.yml"
	}
}
```

### Expected Behavior

Terraform should produce consistent final plan and there should not be error.

### Actual Behavior

After modifying the VM instance Terraform exits with the following error:

```
Error: Provider produced inconsistent final plan

When expanding the plan for null_resource.my-vm-setup[0] to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/null" produced an invalid new value for
.triggers["my_vm_ipaddr"]: was cty.StringVal("1.2.3.4"), but now
cty.StringVal("5.6.7.8").

This is a bug in the provider, which should be reported in the provider's
own issue tracker.
```

### Steps to Reproduce

1. Change a parameter (e.g. `machine_type`) in VM's configuration; and
2. Then run `terraform apply`.

### References

See [issue 10771](https://github.com/hashicorp/terraform-provider-google/issues/10771) for Google provider, where it was suggested to open issue upstream.

**Comment by jbardin** [comment]
Hi @gdsotirov,

Sorry about the confusion here, but unfortunately this error is coming from the `google_compute_instance` resource in this case. There should be an associated warning in the logs to the effect of:

```
[WARN] Provider "google" produced an unexpected new value for google_compute_instance.my-vm, but we are tolerating it because it is using the legacy plugin SDK. The following problems may be the cause of any confusing errors from downstream operations ...
```

This is the canonical example of "confusing errors from downstream operations", where the resource unexpectedly changed it's result from the plan, causing errors for other resources. I would suggest re-opening the provider issue, since the only solution here is for the resource to more accurately plan the changes to be made during apply.

Thanks!
