### ISSUE TITLE
terraform tries to delete the rule group before disassociating from firewall policy

### ISSUE THREAD

**Issue by orderzi** [hashicorp/terraform#30693]
### Terraform Version

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.5.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
...
```

### Terraform Configuration Files

```terraform
resource "aws_networkfirewall_rule_group" "rule-group-allow-customers-domains" {
  for_each = { for key, fw_value in local.allowlist_yaml["customers_domains"][var.region] : key => fw_value }
  capacity = (length(local.allowlist_yaml["customers_domains"][var.region][each.key]["destination_url"]) * 5)
  name     = each.value["name"]
  type     = "STATEFUL"
  rule_group {
    rule_variables {
      ip_sets{
        key = "HOME_NET"
        ip_set {
          definition = each.value["source_cidr"]
        }
      }
    }
    rules_source {
      rules_source_list {
        generated_rules_type = "ALLOWLIST"
        target_types         = ["HTTP_HOST", "TLS_SNI"]
        targets              = each.value["destination_url"]
      }
    }
  }
  tags = {
    Name = each.value["name"]
  }
  
}

resource "aws_networkfirewall_firewall_policy" "firewall-policy" {
  name = "Inspection-Policy"
  firewall_policy {
    stateless_default_actions          = ["aws:forward_to_sfe"]
    stateless_fragment_default_actions = ["aws:forward_to_sfe"]
    stateful_rule_group_reference {
      resource_arn = aws_networkfirewall_rule_group.rule-group-allow-domains.arn
    }
    stateful_rule_group_reference {
      resource_arn = aws_networkfirewall_rule_group.rule-group-allow-av.arn
    }
    stateful_rule_group_reference {
      resource_arn = aws_networkfirewall_rule_group.rule-group-allow-smtp.arn
    }
    stateful_rule_group_reference {
      resource_arn = local.internet_arn
    }
    dynamic "stateful_rule_group_reference" {
        for_each = local.allowlist_yaml["customers_domains"][var.region]
        content {
          resource_arn = aws_networkfirewall_rule_group.rule-group-allow-customers-domains[stateful_rule_group_reference.key].arn
        }
      }
    }
  }
...
```

**Comment by jbardin** [comment]
Hi @orderzi,

Thanks for filing the issue, this can be confusing sometimes. In order to update `aws_networkfirewall_firewall_policy` before the deletion of `aws_networkfirewall_rule_group` you will need to use the [`create_before_destroy`](https://www.terraform.io/language/meta-arguments/lifecycle#create_before_destroy) lifecycle argument. Even if you are only destroying the referenced resource instance, the order the updates to dependencies is still maintained, allowing the  `aws_networkfirewall_firewall_policy` to deregister the group before it is destroyed.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by orderzi** [comment]
Hi @jbardin ,
thanks for the response, when i'm using the `create_before_destory` instruction it works when i'm trying to 
delete a rule group.
My rules are created using `for_each` loop with `dynamic` instruction to fit the order of the rules into the firewall policy.
When there is a change in the order of the rules(deletion on of the rules), terraform trying to do replace operation and then i'm getting `InvalidRequestException: A resource with the specified name already exists`

What should i do ? 

> Hi @orderzi,
> 
> Thanks for filing the issue, this can be confusing sometimes. In order to update `aws_networkfirewall_firewall_policy` before the deletion of `aws_networkfirewall_rule_group` you will need to use the [`create_before_destroy`](https://www.terraform.io/language/meta-arguments/lifecycle#create_before_destroy) lifecycle argument. Even if you are only destroying the referenced resource instance, the order the updates to dependencies is still maintained, allowing the `aws_networkfirewall_firewall_policy` to deregister the group before it is destroyed.
> 
> We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
> 
> Thanks!

**Comment by jbardin** [comment]
You didn't specify which resource is returning the error, but in general any resource using `create_before_destroy` must be able to create a new instance without a naming conflict. Some resource do this automatically and some have specific arguments to enable it, but you would have to check the documentation to find out. If the resource does not support that option, then you would have to open an issue with the associated provider.
