### ISSUE TITLE
Feature request: - Dark and contrast themes for registry.terraform.io

### ISSUE THREAD

**Issue by Lddeiva** [hashicorp/terraform#30697]
### Use-cases
Considering the millions of downloads and frequent access, it is good have dark and contrast themes on site `registry.terraform.io` for better readability. The existing documentation site is not available in dark mode which makes it harder to spend hours of time when working on the complex deployments.

### Attempted Solutions
None

### Proposal
Introduce dark and contrast themes so that it improves accessibility.

**Comment by crw** [comment]
Thanks for the request, I've forwarded it to the registry team. 

As a workaround in the meantime, I personally use Dark Mode add-ons for my browsers to read websites at night. Just speaking from my own experience, this has been hugely useful for me, as some sites will essentially never have an official dark mode. Your own experience may vary of course!

**Comment by MikeWDevops** [comment]
It has been almost 3 years, any progress?

**Comment by crw** [comment]
The registry team does not use this repository for tracking issues. The current recommended practice is to please email [terraform-registry@hashicorp.com](mailto:terraform-registry@hashicorp.com) with your issue. Thanks very much!
