### ISSUE TITLE
terraform-plan & terraform-apply  InvalidClientTokenId error w/ valid ApiKey containing "/" and "+"

### ISSUE THREAD

**Issue by rick-syncbak** [hashicorp/terraform#30698]
Looks like it's still this issue years later: https://github.com/hashicorp/terraform/issues/2972
Trying to run the https://learn.hashicorp.com/tutorials/terraform/aws-build?in=terraform/aws-get-started tutorial in WSL2 using Docker & existing credentials file. 

### Terraform Version 

```
1.1.17
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.27"
    }
  }

  required_version = ">= 0.14.9"
}

provider "aws" {
  profile = "default"
  region  = "us-east-1"
}

resource "aws_instance" "app_server" {
  ami           = "ami-830c94e3"
  instance_type = "t2.micro"

  tags = {
    Name = "ExampleAppServerInstance"
  }
}
```

### Actual Behavior

 Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
│       status code: 403, request id: 44109bcb-3918-43f1-8092-b10199be213b
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 12, in provider "aws":
│   12: provider "aws" {
### Additional Context

The aws_access_key_id & aws_secret_access_key work in all other scenarios.
### References

2972

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
