### ISSUE TITLE
Add Terraform output value AWS Elasticsearch custom domain

### ISSUE THREAD

**Issue by harik8** [hashicorp/terraform#30692]
The `aws_elasticsearch_domain` just returns Elasticsearch VPC endpoint. It'd be good to have an output value for `custom_endpoint`.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
