### ISSUE TITLE
Block type "admin_ssh_key" is represented by a set of objects, and set elements do not have addressable keys.

### ISSUE THREAD

**Issue by Skyere** [hashicorp/terraform#30704]
Azure
Terraform version: v1.1.7
Issue:
Can't output public key

Terraform plan output with public key part:
![image](https://user-images.githubusercontent.com/70713060/159130521-35eaf02b-4faf-461b-8e58-8059fc5cf4d5.png)

I did it like this:
```
output "linux_virtual_machine_public_key" {
  value = azurerm_linux_virtual_machine.CentOS.admin_ssh_key[0].public_key
}
```
Unfortunately, I have got this error:
```
╷
│ Error: Cannot index a set value
│
│   on outputs.tf line 14, in output "linux_virtual_machine_public_key":
│   14:   value = azurerm_linux_virtual_machine.CentOS.admin_ssh_key[0].public_key
│
│ Block type "admin_ssh_key" is represented by a set of objects, and set
│ elements do not have addressable keys. To find elements matching specific
│ criteria, use a "for" expression with an "if" clause.
```

Thank in advance)

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
