### ISSUE TITLE
managed_resource_group_name not working 

### ISSUE THREAD

**Issue by mevenks** [hashicorp/terraform#30707]
Hi ,

I am using terraform to create a databricks . If I do NOT include the [managed_resource_group_name] parameter , databricks is created successfully in my resource group and a new managed resource groupe is created automatically , until now everything is normal . 

But if I include the [managed_resource_group_name] parameter adding a personalised freshly new created resource group , databricks get created but not the resources that are supposed to be created under the managed resource group (storage,vnet and workers-sg) .

Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0

My naming convention : 
databricks resource gp naming convension : xx-xx-rg-project 
databricks managed resource gp naming convension : xx-xx-rg-project-databricks-workspace

The same main.tf is used to created resource groupe for databricks and databrick's workspace , i've added depends_on under databricks creation to make sure both resources groupes are created before databricks creation. 

main.tf 

module "databricks" {

  source = "./modules/databricks"

  name = var.databricks_name
  resource_group_name = var.resource_group_name
  location = var.resource_group_location
  sku = var.databricks_sku
  managed_resource_group_name = var.managed_resource_group_name

  depends_on = [
    module.resource_group_workspace , module.resource_group
  ]

}

my module un modules\databricks\main.tf : 

resource "azurerm_databricks_workspace" "this" {

  name                        = var.name
  resource_group_name         = var.resource_group_name
  location                    = var.location
  sku                         = var.sku

  managed_resource_group_name = var.managed_resource_group_name
  
}

Terraform does not display any error but only success on creation. 

thank you for your help

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by mevenks** [comment]
Thank @jbardin , i have open a new issue at https://github.com/terraform-providers/terraform-provider-azurerm/issues . please close this one .
