### ISSUE TITLE
sahitya12

### ISSUE THREAD

**Issue by sahitya12** [hashicorp/terraform#30708]
Hi Team,

I am trying to deploy Azure Databriks using terraform, I have subnets that are already created and NSG is already associated to subnet prior to deployment of Databriks resources  , May i know i can i pass the value of existing associated NSG Id in custom parameters block without having new NSG to get created.?

I also have one more issue while trying to deploy databriks i am getting an error as below:

error: performing CreateOrUpdate: workspaces.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidPrivateWorkspaceForSubscription" Message="The subscription 78816d88-f28f-4d39-acba-2dfbbd0c432c is not registered to create private workspace."

Code : 
// Create the databricks workspace
resource "azurerm_databricks_workspace" "databricks" {
  name                = var.workspace_name
  resource_group_name = "${var.uai}-${var.appName}-${var.environment}-rg"
  location            = var.location
  sku                 = var.sku
  managed_resource_group_name = "${var.uai}-${var.appName}-${var.environment}-rg-managed-services"
  managed_services_cmk_key_vault_key_id = data.azurerm_key_vault_key.key.id
  customer_managed_key_enabled = true
  public_network_access_enabled = false

  custom_parameters {
    no_public_ip        = false
    private_subnet_name = data.azurerm_subnet.private_subnet_name.name
    private_subnet_network_security_group_association_id = ""
    public_subnet_name  = data.azurerm_subnet.public_subnet_name.name
    public_subnet_network_security_group_association_id = ""
    virtual_network_id  = data.azurerm_virtual_network.virtual_network.id
    storage_account_name = var.storage_account_name
    storage_account_sku_name = var.storage_account_sku_name
  }

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
