### ISSUE TITLE
Dead links on terraform.io/docs

### ISSUE THREAD

**Issue by thevops** [hashicorp/terraform#30701]
Section https://learn.hashicorp.com/tutorials/terraform/associate-study?in=terraform/certification#read-and-write-configuration contains dead links. For example:
[Resources](https://www.terraform.io/docs/language/resources/index.html) describe infrastructure objects. This link returns:

![image](https://user-images.githubusercontent.com/23660445/159067824-183e0eca-fab3-470e-b959-213b4765eaf6.png)

**Comment by laurapacilio** [comment]
Thank you so much for flagging this :-) I believe our web development team has just merged a PR that fixes this issue, but please let us know if you continue to experience problems with the site.
