### ISSUE TITLE
Feature request: file provisioner - allow specifying file attributes

### ISSUE THREAD

**Issue by mtekel** [hashicorp/terraform#3071]
File provisioner currently only has source and destination arguments. It would be great if it also allowed to specify destination file attributes (e.g. `0600`), owner and group. Ideally we could specify some arbitrary string that would be understood by the local destination filesystem, e.g. 

```
ownership = 'user:group'
attributes = '0600'
```

**Comment by pkolyvas** [comment]
I think, based on a number of factors, including community engagement and what we're working on currently I'm going to close this issue. Appreciate the contribution!
