### ISSUE TITLE
Not  trusted Certification validation failed

### ISSUE THREAD

**Issue by technoidnostress** [hashicorp/terraform#30718]
Hi there,

Not sure, why certification validation is getting failed?

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
```

### Actual Behavior

`Get:1` http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Ign:2 https://apt.releases.hashicorp.com focal InRelease
Err:3 https://apt.releases.hashicorp.com focal Release
Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: *.*.*.* 443]
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1342 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [233 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [9800 B]
Get:10 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [825 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1674 kB]
Get:12 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [117 kB]
Get:13 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [692 kB]
Get:14 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [121 kB]
Get:15 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [14.1 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [316 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [14.8 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [887 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [127 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [910 kB]
Get:21 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [202 kB]
Get:22 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [20.3 kB]
Get:23 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [24.5 kB]
Reading package lists... Done
E: The repository 'https://apt.releases.hashicorp.com focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details`

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `Open terminal (Ubuntu20-*)`
2. `install repo:sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl`

### Additional Context

https://learn.hashicorp.com/tutorials/terraform/install-cli

**Comment by jbardin** [comment]
Hi @technoidnostress,

Thanks for filing the issue. Can you confirm if this is still happening for you?

Thanks!

**Comment by technoidnostress** [comment]
@jbardin  Thank you for the reply, i have been able to use tfnev for most of the time and hcl as well, recently i found out the the problems are intermittent when am behind the proxy, so  i  exported my CA-Certifacties in /usr/local/share/ca-certificates/ updated the ca certificate but still get the same response,

**Comment by jbardin** [comment]
There have been a number of updates to the apt repo system since this was filed. Any similar problems should be file in new issues with any new information.

Thanks!
