### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereferencegoroutine 1103

### ISSUE THREAD

**Issue by EricOropezaelwood** [hashicorp/terraform#30713]
Saw this terraform output today after running an Azure pipeline. When running the plan locally I saw the usual deletion + addition plan, then when it ran in Azure pipeline

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

terraform version = 1.0.0

---------------------------------------------------------------------

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereferencegoroutine 1103 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:44 +0xb5
panic({0x269a6a0, 0x436ed80})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hashicorp/terraform/internal/instances.(*expanderModule).onlyResourceInstances(0xc00129f270, {{}, 0x4d, {0xc000ac82a0, 0x18}, {0xc0005945f0, 0x9}}, {0xc001234300, 0x30, 0x4})
	/home/circleci/project/project/internal/instances/expander.go:392 +0x95
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0x202ee9a1a18, {0xc000894d20, 0x0, 0x43bd920}, {{}, 0x4d, {0xc000ac82a0, 0x18}, {0xc0005945f0, 0x9}}, ...)
	/home/circleci/project/project/internal/instances/expander.go:387 +0x2e5
github.com/hashicorp/terraform/internal/instances.(*expanderModule).resourceInstances(0xc000c62480, {0xc000894d20, 0x1, 0x1}, {{}, 0x4d, {0xc000ac82a0, 0x18}, {0xc0005945f0, 0x9}}, ...)
	/home/circleci/project/project/internal/instances/expander.go:385 +0x293
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandResource(0xc001884700, {{}, {0xc000894d20, 0x1, 0x1}, {{}, 0x4d, {0xc000ac82a0, 0x18}, {0xc0005945f0, ...}}})
	/home/circleci/project/project/internal/instances/expander.go:157 +0x16f
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).deleteActionReason(0xc0031e5c70, {0x2f78680, 0xc000d62620})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:182 +0x445
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc0031e5c70, {0x2f78680, 0xc000d62620})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:140 +0x58c
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0, {0x2f78680, 0xc000d62620}, 0x80)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0009302a0, {0x2f78680, 0xc000d62620}, {0x202eec44160, 0xc0031e5c70})
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:133 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x29d1fc0, 0xc0031e5c70})
	/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000c09140, {0x29d1fc0, 0xc0031e5c70}, 0xc001b9d400)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x2f1
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update

**Comment by jbardin** [comment]
Hi @EricOropezaelwood,

Thanks for filing the issue. This looks like an issue which was fixed in an earlier release of Terraform. The latest release is v1.1.7, which should no longer be able to his this condition. If you can replicate the issue with a current release, please feel free to open a new issue, along with the information requested in the issue template.

Thanks!

**Comment by EricOropezaelwood** [comment]
That was the problem, thanks for that
