### ISSUE TITLE
Public repositories failed (Hashicorp Stable - x86_64) rpm.releases.hashicorp.com

### ISSUE THREAD

**Issue by rtpurificacao** [hashicorp/terraform#30726]
Hi there,

Failing installing package terraform-0.14.8-1.x86_64 through https://rpm.releases.hashicorp.com/AmazonLinux/2/x86_64/stable/repodata

**Steps to reproduce:**
`$> yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
Failed to set locale, defaulting to C
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
adding repo from: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
grabbing file https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo to /etc/yum.repos.d/hashicorp.repo
repo saved to /etc/yum.repos.d/hashicorp.repo`

`$> yum install -y terraform-0.14.8-1.x86_64
Failed to set locale, defaulting to C
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
hashicorp                                                    | 1.4 kB  00:00:00
hashicorp/2/x86_64/primary     FAILED
https://rpm.releases.hashicorp.com/AmazonLinux/2/x86_64/stable/repodata/6c41ba223b874ca185a3d25e348ebd381747a0f4-primary.xml.gz: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
https://rpm.releases.hashicorp.com/AmazonLinux/2/x86_64/stable/repodata/6c41ba223b874ca185a3d25e348ebd381747a0f4-primary.xml.gz: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.`

It appears that the packages are not available in the public repository.

**Comment by jbardin** [comment]
Hi @rtpurificacao,

Thanks for filing the issue. Can you confirm is this is still happening, or if this was a temporary outage?

Thanks!
