### ISSUE TITLE
Interpolation for provider field does not work 

### ISSUE THREAD

**Issue by jarosite** [hashicorp/terraform#3072]
get error while trying to apply plan
Errors:

  * 1 error(s) occurred:

* module root: 1 error(s) occurred:

* aws_security_group.defaultAllOffice: resource depends on non-configured provider '${lookup(var.providers, count.index)}'

```
$terraform -v
Terraform v0.6.3
```
use case:
create same security group in all aws regions:
```javascript
provider "aws" {
  alias = "us-east-1"
  region="us-east-1"
}
provider "aws" {
    alias = "us-west-2"
    region = "us-west-2"
}
variable "providers" {
  default = {
    "0" = "aws.us-west-2"
    "1" = "aws.us-east-1"
  }
}
resource "aws_security_group" "defaultAllOffice" {
    name = "defaultAllOffice ${lookup(var.providers, count.index)}"
    description = "Used in the terraform ${lookup(var.providers, count.index)}"
    count = "2"
    provider = "${lookup(var.providers, count.index)}"
/* some sg rules there*/
}
```

please let me know if there better solution to do cross region transformation

**Comment by jarosite** [comment]
any idea for workaround?

**Comment by jarosite** [comment]
as workaround created this simple script 
```
#!/usr/bin/env bash

REGIONS=("us-east-1" "us-west-2" "us-west-1" "eu-west-1" "eu-central-1" "ap-southeast-1" "ap-southeast-2" "ap-northeast-1" "sa-east-1")

for RG in "${REGIONS[@]}"
do
  echo processing region $RG
  terraform $1 -state=state/$RG-sg.tfstate -var "region=$RG" 
done
```

**Comment by rosmo** [comment]
It would be great to have the interpolation of provider working.

**Comment by phinze** [comment]
This is something we should address. Closing to consolidate around #1819.

**Comment by rodlogic** [comment]
I see that there is an ongoing discussion on #1819, but that seems to take it to a deeper level. 

Wouldn't it make sense to add interpolation here and at least allow one to dynamically select a provider in a module?

**Comment by NickLaMuro** [comment]
I was struggling with this today, and found an alternative workaround to the bash script.  You could include in your module the provider with an interpolated region that then all of your resources within the module use.

As an example, here would be a module for an AWS VPC:

```js
# module/vpc/vpc.tf
variable "aws_region" {}

provider "aws" {
  alias  = "aws_vpc"
  region = "${var.aws_region}"
}

resource "aws_vpc" "vpc" {
  provider = "aws.vpc_aws"

  # Other vpc config here
}

resource "aws_subnet" "private_subnet" {
  provider = "aws.vpc_aws"

  # Other subnet config here
}
```

And then if you need to create a cross region vpc in each region, you could then do in your `main.tf`:

```js
# module/vpc/vpc.tf

module "vpc_east" {
  source "path/to/module/vpc"
  
  region "us-east-1"
}

module "vpc_west" {
  source "path/to/module/vpc"
  
  region "us-west-1"
}
```

Might not work in all cases, but this would allow you to reuse the bulk of configuration code and just make it region specific... or at least as far as I can tell.  I haven't actually run an `terraform apply` with this, but the `plan` was at least compiling properly :smile:

**Comment by mattwillsher** [comment]
From my tests you don't need the alias in the submodule - terraform uses the closest provider. This seems to be backed up in the `terraform graph` output. 

In the above sample, the vpc.tf can be written as:
```hcl
# module/vpc/vpc.tf

variable "aws_region" {}

provider "aws" {
  region = "${var.aws_region}"
}

resource "aws_vpc" "vpc" {
  # Other vpc config here
}

resource "aws_subnet" "private_subnet" {
  # Other subnet config here
}
```
