### ISSUE TITLE
failed to retrieve cryptographic signature for provider: 403 Server failed to │ authenticate the request

### ISSUE THREAD

**Issue by mikebollandajw** [hashicorp/terraform#30722]
This seems to be back again but no outage is showing on status.hashicorp

```
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to install provider
│ 
│ Error while installing pagerduty/pagerduty v1.11.0: could not query
│ provider registry for registry.terraform.io/pagerduty/pagerduty: failed to
│ retrieve cryptographic signature for provider: 403 Server failed to
│ authenticate the request. Make sure the value of Authorization header is
│ formed correctly including the signature.
```

Terraform Version: Using Kubernetes executor with image hashicorp/terraform:1.0.11 
Time: 22/03/2022 4:34 PM UTC

**Comment by jbardin** [comment]
Hi @mikebollandajw,

There were con temporary outages recently. Can confirm that you have access to this again?

Thanks!

**Comment by gantvi01** [comment]
I see a similar issue
![image](https://user-images.githubusercontent.com/91073177/167493860-a12c71bb-e5b4-4b9b-b7b9-c565e37ab224.png)

**Comment by tessiof** [comment]
We had the exact problem yesterday. I'm almost certain that this was the result of a temporary unavailability on Terraform registry side.

**Comment by gantvi01** [comment]
I ended up upgrading the vault provider, which resulted in changing the state file manually because of some unsupported attributes with the old secrets, and finally was able to get past the above issue. Thanks

**Comment by gkarthiks** [comment]
i am facing the same issue now @ `Thu May 12 01:23:40 PDT 2022`

```
Initializing provider plugins...
- Finding latest version of hashicorp/kubernetes...
╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/kubernetes v2.11.0: could not query provider registry for registry.terraform.io/hashicorp/kubernetes: failed to retrieve
│ cryptographic signature for provider: 403 Forbidden
╵

```


The status of the registry is operational though

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/30545166/168026160-53784f7e-7885-4755-a145-f5efb964ea08.png">

**Comment by crw** [comment]
Hello! If you've experienced this issue, can you please test again and let me know if it is continuing to occur? We think it may be related to a (closed) incident with releases.hashicorp.com, but if you are still experiencing issues we may need to revisit that incident. Thanks very much!

**Comment by gkarthiks** [comment]
> Hello! If you've experienced this issue, can you please test again and let me know if it is continuing to occur? We think it may be related to a (closed) incident with releases.hashicorp.com, but if you are still experiencing issues we may need to revisit that incident. Thanks very much!

I confirm this is now working.

**Comment by crw** [comment]
Closing, but please let me know if you are experiencing this as an on-going issue.

**Comment by acidprime** [comment]
Just hit this ```Error while installing kreuzwerker/docker v2.8.0: could not query provider
registry for registry.terraform.io/kreuzwerker/docker: failed to retrieve
cryptographic signature for provider: 403 Server failed to authenticate the
request. Make sure the value of Authorization header is formed correctly
including the signature.
```
