### ISSUE TITLE
AWS Elastic Beanstalk LoadBalancer type option cannot be changed

### ISSUE THREAD

**Issue by SergeySypalo** [hashicorp/terraform#30723]
Hi there, I faced the old issue:
At first, I created an environment with a classic load balancer, then changed the config to the application load balancer, but instead of recreating the environment, Terraform tried to change LB type, which is not allowed, thus operation failed.
Original issue - https://github.com/hashicorp/terraform/issues/14934
It was closed with no action/response.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
