### ISSUE TITLE
Module source & versions parameters should support conditions

### ISSUE THREAD

**Issue by tlindsay42** [hashicorp/terraform#30735]
### Current Terraform Version

```
terraform version
Terraform v1.1.7
```

### Use-cases

The [AWS Integration & Automation team](https://registry.terraform.io/namespaces/aws-ia) is developing modules that include examples for customers, and we also use these examples for module testing (currently with [terratest](https://terratest.gruntwork.io/)). Since Terraform module source & version parameters don't support conditions, we have to choose between setting the source to the Terraform Registry entry, which is better for end users since they can copy & paste and get started without modification, or setting the source to the local relative path (eg: `../..`), which is better for developer experience since module contributors can run the existing tests against their changes without having to update the source path and version in the examples.

#### variables.tf

```hcl
variable "local_test" {
  type    = bool
}
```

#### main.tf
```hcl
module "example" {
  source  = (var.local_test) ? "aws-ia/example/example" : "../.."
  version = (var.local_test) ? ">= 0.0.1" : null
  ...
```

#### Output of terraform init
```
$ terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Variables not allowed
│
│ On main.tf line 3: Variables may not be used here.
╵

╷
│ Error: Unsuitable value type
│
│ On main.tf line 3: Unsuitable value: value must be known
╵

╷
│ Error: Variables not allowed
│
│ On main.tf line 4: Variables may not be used here.
╵

╷
│ Error: Unsuitable value type
│
│ On main.tf line 4: Unsuitable value: value must be known
```

### Proposal

Add support for conditions in module source & version parameters to make it possible to cover both use cases. This will also encourage our module contributors to keep the examples current, which is better for the community. Same goes for module developers that duplicates this model.

### References

* https://github.com/aws-ia/terraform-aws-vpc/pull/32#discussion_r833755984
* https://github.com/hashicorp/terraform/issues/30734

**Comment by crw** [comment]
Hi @tlindsay42, please check out this comment: https://github.com/hashicorp/terraform/issues/30441#issuecomment-1024371002 -- based on that comment, I am going to close this issue, but let me know if you think this case is different and should be re-opened, or reconsidered for any reason.

**Comment by tlindsay42** [comment]
Disappointing, but fair enough
