### ISSUE TITLE
Unable to run terraform 1.1.7 with az cli beta

### ISSUE THREAD

**Issue by michalhoppe** [hashicorp/terraform#30737]
I am testing the migration to Microsoft Graph.  Based on 

https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration?tabs=bash 

there is a beta version of az cli that supports MS Graph.

I tried running terraform with the beta version of az cli, but got this error:

Error building ARM Config: could not parse detected Azure CLI version "2.34.1.post20220318081725": Malformed version: 2.34.1.post20220318081725

### Terraform Version
```
Terraform v1.1.7
```
### Expected Behavior
terraform apply without errors

### Actual Behavior
terraform failed with 

Error building ARM Config: could not parse detected Azure CLI version "2.34.1.post20220318081725": Malformed version: 2.34.1.post20220318081725

### Steps to Reproduce
1. install beta az cli with pip in venv per linked article
2. terraform apply from within venv

### Additional Context
Using beta version of az cli.

**Comment by crw** [comment]
Hello @michalhoppe,

I believe this is an issue with the AzureRM provider, as opposed to with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. 

I am going to leave this open for developer review just in case I am wrong about the source of the issue. Thanks!

**Comment by jbardin** [comment]
Thanks for filing the issue @michalhoppe,

I can't tell where the error is coming from here without any example configuration, but the error string seems to originate from the `github.com/hashicorp/go-azure-helpers` package, which is also maintained by the terraform-provider-azurerm team. I would suggest opening an [issue with the provider](https://github.com/terraform-providers/terraform-provider-azurerm/issues), as they are more likely to be able to help. If you have questions about the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34, the GitHub issues here are monitored only by a few core maintainers.

Thanks!
