### ISSUE TITLE
AWS: modifying ebs_block_device renders empty plan

### ISSUE THREAD

**Issue by alex-fedorov** [hashicorp/terraform#3073]
```bash
$ terraform -v
Terraform v0.6.3
```

Before modification (and after applying):

```tf
resource "aws_instance" "aninstance" {
  # ...

  root_block_device {
    volume_type = "gp2"
    volume_size = 25
  }

  ebs_block_device {
     device_name = "/dev/sdg"
     volume_type = "gp2"
     volume_size = 25
  }
}
```

Modification:

```tf
resource "aws_instance" "aninstance" {
  # ...

  root_block_device {
    volume_type = "gp2"
    volume_size = 25
  }

  ebs_block_device {
     device_name = "/dev/sdg"
     volume_type = "io1"
     volume_size = 500
     iops = 5000
  }
}
```

Running `terraform plan` returns empty plan without changes.

**Comment by catsby** [comment]
Hello @alex-fedorov – 

Sorry for the trouble here. Right now, changes to optional attributes in any `block_device` attribute require manually running `terraform taint` on the specific instances.

> NOTE: Currently, changes to *_block_device configuration of existing resources cannot be automatically detected by Terraform. After making updates to block device configuration, resource recreation can be manually triggered by using the taint command.

(from https://terraform.io/docs/providers/aws/r/instance.html)

You can manually taint your resource like so:

    $ terraform taint aws_instance.aninstance

That will cause Terraform to register the needed update, so `plan` and `apply` will behave as you would expect.

The gory details are in this commit:

- https://github.com/hashicorp/terraform/commit/34c7bbcf4da63a6e5a1a611d89d7c642d76e9859#diff-5ae59bd3cb446e5b3d5b8521f0b43ac4

Sorry again for the trouble

**Comment by alex-fedorov** [comment]
Thanks for a feedback. And sorry for overseeing this not in docs.

**Comment by catsby** [comment]
No worries! It absolutely _should_ behave like you expected, but it's a known limitation at the moment... :frowning: 

Let me know if you need anything else
