### ISSUE TITLE
│ Error: Extraneous JSON object property

### ISSUE THREAD

**Issue by bretagne-peiqi** [hashicorp/terraform#30739]
Does someone know this error, it is related with terraform version or something is wrong ??

my terraform version 1.1.5

terraform plan
╷
│ Error: Extraneous JSON object property
│
│ on main.tf.json line 1, in resource.alicloud_instance.ecshi:
│ 1: {"provider":{"alicloud":null},"resource":{"alicloud_instance":{"ecshi":{"allocate_public_ip":false,"availability_zone":"cn-shanghai-b","image_id":"m-uf69d7x8qidguc5slllq","instance_type":"ecs.sn1ne.xlarge","lifecycle":{"prevent_destroy":true},"name":"ecshi","security_groups":["sg-uf6321mosdrkcnwf50e2"],"vswitch_id":"vsw-uf6svfuk7dc11xn7bk1lb"}}},"terraform":{"required_providers":{"alicloud":{"source":"aliyun/alicloud","version":"1.155.0"}}}}
│
│ No argument or block type is named "name".

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
