### ISSUE TITLE
Add Support to Import Environment Variables in AWS MWAA

### ISSUE THREAD

**Issue by pavan-kumar-99** [hashicorp/terraform#30743]
### Current Terraform Version
1.1.7
### Use-cases
Add Support to Import Environment Variables in AWS MWAA. I would want to import Airflow environment variables in terraform. Probably adding support to import Json directly from terraform itself

### Attempted Solutions
resource "aws_mwaa_environment" "test" {
  airflow_configuration_options = {
    "bucket"        = "${var.source_bucket_name}"
    "cluster_name"  = "${var.mwaa_name}"
    "folder_prefix" = "messages"
    "output_prefix" = "messages_parquet"
  }

### Proposal
resource "aws_mwaa_environment" "test" {
  airflow_configuration_options = {
    "bucket"        = "${var.source_bucket_name}"
    "cluster_name"  = "${var.mwaa_name}"
    "folder_prefix" = "messages"
    "output_prefix" = "messages_parquet"
  }

( OR )

resource "aws_mwaa_environment" "test" {
  airflow_configuration_options = {
            file(./var.json)
  }

**Comment by crw** [comment]
Hello @pavan-kumar-99,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by pavan-kumar-99** [comment]
Thanks @crw, Created one here 
https://discuss.hashicorp.com/t/add-support-to-import-environment-variables-in-aws-mwaa/37645
