### ISSUE TITLE
count.index not reading count value, Call to function "element" failed: cannot read elements from object.

### ISSUE THREAD

**Issue by sara-hann** [hashicorp/terraform#30744]
variable "RdsCreate" {
  type  = string                #Use -var cli flag to pass true or false as args when running terraform apply.
  default       = true          #Set to true to create RDS and its components. true is converted to 1, false is converted to 0.
}

variable "RdsSubnetsCidrs" {
  type  = list(string)
  default       = ["10.0.0.16/28", "10.0.0.32/28"]
}

resource "aws_eip" "NATEIP" {
  provider      = aws.region-main
  count = var.RdsCreate ? 1 : 0
  vpc   = true
  depends_on    = [aws_internet_gateway.IGW]
}

resource "aws_nat_gateway" "NAT" {
  count = var.RdsCreate ? 1 : 0
  provider      = aws.region-main
  allocation_id = aws_eip.NATEIP[0].id    #aws_eip.NATEIP[count.index].id
  subnet_id     = aws_subnet.X360Subnet1.id
  depends_on    = [aws_internet_gateway.IGW]
}

data "aws_availability_zones" "azs" {
  provider      = aws.region-main
  state         = "available"
}

resource "aws_subnet" "RdsSubnet" {
  count                 = "${length(var.RdsSubnetsCidrs)}"
  provider      = aws.region-main
  availability_zone     = "${element(data.aws_availability_zones.azs, count.index)}"  
  vpc_id        = aws_vpc.X360-VPC.id
  cidr_block    = "${element(var.RdsSubnetsCidrs, count.index)}" 
  depends_on    = [aws_eip.NATEIP]
  tags = {
    Name        = "X360RdsSubnet[count.index]-private"
  }
}

resource "aws_route_table" "PrivateSubnetTable" {
#count = var.RdsCreate ? 1 : 0
  provider      = aws.region-main
  vpc_id        = aws_vpc.X360-VPC.id
  route {
    cidr_block        = "0.0.0.0/0"
    nat_gateway_id            = aws_nat_gateway.NAT[0].id   #aws_nat_gateway.NAT[count.index].id
  }
  depends_on    = [aws_eip.NATEIP]
  tags          = {
    Name        = "PrivateSubnetRouteTable"
  }
}

resource "aws_route_table_association" "PrivateTableAssoc" {
#count = var.RdsCreate ? 1 : 0
  provider      = aws.region-main
  subnet_id     = values(aws_subnet.RdsSubnet)[*].id 
  route_table_id        = aws_route_table.PrivateSubnetTable.id   #aws_route_table.PrivateSubnetTable[0].id
  depends_on    = [aws_eip.NATEIP]
}
resource "aws_db_subnet_group" "RdsSubnetGroup" {
  count = var.RdsCreate ? 1 : 0
  provider      = aws.region-main
  name  = "x360rdssubnetgroup"
  subnet_ids    = values(aws_subnet.RdsSubnet)[*].id 
}

 Error: Error in function call
│
│   on network.tf line 130, in resource "aws_subnet" "RdsSubnet":
│  130:   availability_zone     = "${element(data.aws_availability_zones.azs, count.index)}"  
│     ├────────────────
│     │ count.index is 1
│     │ data.aws_availability_zones.azs is object with 9 attributes
│
│ Call to function "element" failed: cannot read elements from object.
╵
╷
│ Error: Error in function call
│
│   on network.tf line 130, in resource "aws_subnet" "RdsSubnet":
│  130:   availability_zone     = "${element(data.aws_availability_zones.azs, count.index)}"  
│     ├────────────────
│     │ count.index is 0
│     │ data.aws_availability_zones.azs is object with 9 attributes
│
│ Call to function "element" failed: cannot read elements from object.

I've also tried several variations on count:
#count                = "${var.RdsCreate ? length(var.RdsSubnetsCidrs) : 0}"
#count                = 2
#count                = var.RdsCreate ? 2 : 0

and a number of different ways to write the availability_zone:
#["${var.RdsSubnetsCidrs}"] 
#element(var.RdsSubnetsCidrs[count.index].rendered)  

I was originally using count to only create the 2 private subnets if RdsCreate was set to true, but when I did that, it wouldn't read the cidrs from my RdsSubnetsCidrs list. So I am using a depends_on instead, which is tied to NATEIP. No matter what I'm trying, whether using count or depends_on, I'm getting errors about count and index for the aws_subnet.RdsSubnet cidr_block and availability_zone. I've been trying every combination I can think of for the different parameters for the past week, and everything I read online seems to indicate that this type of arrangement should work, so I'm beginning to think there may be a bug.

**Comment by jbardin** [comment]
Hello,

The error is indicating that you are passing an object to the `element` function, which is what happens what you pass `data.aws_availability_zones.azs` as the first argument. You probably meant to access one of that data sources outputs, like  `names`, `group_names`, or `zone_ids`.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
