### ISSUE TITLE
create new key version for azure key vault key

### ISSUE THREAD

**Issue by ASBhor** [hashicorp/terraform#30758]
I use Add-AzKeyVaultKey to generate new key versions however I am not able to see any option in terraform to create new key version for Azure key vault key. Please suggest correct way to generate new key version.

**Comment by crw** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
