### ISSUE TITLE
Publish a darwin 0.15.5 `arm` release please

### ISSUE THREAD

**Issue by mhemken-vts** [hashicorp/terraform#30757]
Hello, I'm noticing that there is no darwin build for 0.15.5 on `arm` architecture. This is kind of a bummer for us on company issued M1 laptops. There is an intermittent bug on this version/arch combo when using the [AWS Provider][bug].

Source: [hashicorp releases][releases]

[bug]: https://github.com/hashicorp/terraform-provider-aws/issues/23850 "bug"
[releases]: https://releases.hashicorp.com/terraform/0.15.5/ "releases"

**Comment by jbardin** [comment]
Hi @mhemken-vts,

The v0.15 branch is no longer being developed. Version v1.0 however was a direct continuation of the v0.15 release with no changes. The latest patch for that branch was v1.0.11, which was release for `darwin_arm64`.

Thanks!

**Comment by mhemken-vts** [comment]
Thanks for the quick reply @jbardin , much appreciated!
