### ISSUE TITLE
Make a default_tags of provider as module. it does not apply default_tags to resources

### ISSUE THREAD

**Issue by tanhcnl** [hashicorp/terraform#30759]
### Terraform Version

```
Terraform v1.0.7
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.1.7. You can update by downloading from https://www.terraform.io/downloads.html

```

### Terraform Configuration Files

```terraform
Terraform structure:
environment
  dev
     main.tf
     variables.tf
     terraform.tfvars
modules
  main.tf
  variables.tf

- environment/dev/main.tf file:
<
module "default-tagging" {
  source = "../../modules"
  tags   = var.tags
  region = var.region

}
resource "aws_vpc" "vpcfortesting" {
  cidr_block = "172.0.0.0/16"
  
}
>
- environment/dev/variables.tf file:
<
variable "tags" {
  description = "A map of tags to add to all resources"
  type        = map(string)
}
variable "region" {
  type = string
}
>
- environment/dev/terraform.tfvars file
<
region = "ap-southeast-1"

tags = {
  "Name" : "test"
  "application" : "wordpress"
  "environment" : "uat"
  "business-unit" : "IT"
  "system-tier-classication" : "tier-1"
}
>

- modules/main.tf file
<
terraform {
  required_version = ">= 0.14.7"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.38"
    }
  }
}

provider "aws" {
  region = var.region
  default_tags {
    tags = var.tags
  }
}

>
- modules/variables.tf file
<
variable "tags" {
  description = "A map of tags to add to all resources"
  default = {
    "Name"                       = "-"
    "application"                = "wordpress"
    "environment"                = "uat"
    "business-unit"              = "-"
    "system-tier-classification" = "tier-1"
  }
  type = map(string)
}
variable "region" {
  type = string
}
>
```

### Expected Behavior

Run terraform init, plan in environment/dev folder
The expectation output: vpc resources have to inherit the defaults_tags from module "default-tagging"
The tagging should be:
<
  "Name" : "test"
  "application" : "wordpress"
  "environment" : "uat"
  "business-unit" : "IT"
  "system-tier-classication" : "tier-1"
>

### Actual Behavior

<
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with
the following symbols:
  + create

Terraform will perform the following actions:

  # aws_vpc.vpcfortesting will be created
  + resource "aws_vpc" "vpcfortesting" {
      + arn                                  = (known after apply)
      + cidr_block                           = "172.0.0.0/16"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = (known after apply)
      + enable_dns_support                   = true
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags_all                             = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

>
The tags did not apply to vpc resource.

### Steps to Reproduce

1. `terraform init`
<
Initializing modules...
- default-tagging in ../../modules

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 3.38.0"...
- Installing hashicorp/aws v4.8.0...
- Installed hashicorp/aws v4.8.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
>
3. `terraform apply`
<
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with
the following symbols:
  + create

Terraform will perform the following actions:

  # aws_vpc.vpcfortesting will be created
  + resource "aws_vpc" "vpcfortesting" {
      + arn                                  = (known after apply)
      + cidr_block                           = "172.0.0.0/16"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = (known after apply)
      + enable_dns_support                   = true
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags_all                             = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 

>

**Comment by jbardin** [comment]
Hi @tanhcnl,

The demonstrated behavior here is correct. Providers cannot be "passed upwards" into a parent module, they are typically only configured in the root module and passed into child modules. We generally advise against configuring provider within modules at all, since they prevents the module from ever being removed cleanly, and prevents the ability to expand the module into multiple instances if desired.

The vpc in the given configuration is not using a configured provider, and must be getting all necessary config from your environment instead. In fact with the latest version of Terraform and the AWS provider this configuration will result in the error:

```
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to
│ the root module and configure the provider's required arguments as described in the provider
│ documentation.
│
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
