### ISSUE TITLE
Issue with terraform dependencies on dynamic variables combined with static variables

### ISSUE THREAD

**Issue by Pwd9000-ML** [hashicorp/terraform#30751]
### Terraform (and AzureRM Provider) Version

```hcl
terraform {
  required_version = "~> 1.1.0"
  backend "azurerm" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0.1"
    }
  }
}
```

### Affected Resource(s)

* `azurerm_container_registry`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "APPSVC" {
  name                = var.appsvc_name
  location            = azurerm_resource_group.RG.location
  resource_group_name = azurerm_resource_group.RG.name
  service_plan_id     = azurerm_service_plan.ASP.id
  https_only          = true

  identity {
    type = "SystemAssigned"
  }

  site_config {
    container_registry_use_managed_identity = true
    ftps_state                              = "FtpsOnly"
    application_stack {
      docker_image     = "${var.acr_name}/${var.appsvc_name}"
      docker_image_tag = "latest"
    }
    vnet_route_all_enabled = var.vnet_route_all_enabled
  }

  app_settings = lookup(local.app_settings, "linux_app_settings", null)
  #app_settings = var.appsvc_settings
}

resource "azurerm_app_service_virtual_network_swift_connection" "azure_vnet_connection" {
  count          = var.vnet_integ_required == true ? 1 : 0
  app_service_id = azurerm_linux_web_app.APPSVC.id
  subnet_id      = azurerm_subnet.SUBNETS["App-Service-Integration-Subnet"].id
}

resource "azurerm_container_registry" "ACR" {
  name                = var.acr_name
  location            = azurerm_resource_group.RG.location
  resource_group_name = azurerm_resource_group.RG.name
  sku                 = var.acr_sku
  admin_enabled       = var.acr_admin_enabled

  dynamic "identity" {
    for_each = var.acr_requires_identity == true ? [1] : []
    content {
      type = "SystemAssigned"
    }
  }

  dynamic "georeplications" {
    for_each = var.acr_sku == "Premium" ? var.acr_georeplications_configuration : []
    content {
      location                = georeplications.value.location
      zone_redundancy_enabled = georeplications.value.zone_redundancy_enabled
    }
  }

  dynamic "network_rule_set" {
    for_each = local.acr_fw_rules != null ? local.acr_fw_rules : []
    content {
      default_action = network_rule_set.value.default_action
      dynamic "ip_rule" {
        for_each = network_rule_set.value["ip_rules"] != [] ? network_rule_set.value["ip_rules"] : []
        content {
          action   = ip_rule.value["action"]
          ip_range = ip_rule.value["ip_range"]
        }
      }

      dynamic "virtual_network" {
        for_each = network_rule_set.value["virtual_network_subnets"] != [] ? network_rule_set.value["virtual_network_subnets"] : []
        content {
          action    = virtual_network.value["action"]
          subnet_id = virtual_network.value["subnet_id"]
        }
      }
    }
  }

}
```

The issue is I am building an App service that is VNET integrated.
I then use a dynamic local to generate a list of possible outbound IPs to add to the ACR as whitelisted IPs.
The locals config looks like this:

```hcl
locals {

  ## ACR Firewall rules ##
  #Get all possible outbound IPs from VNET integrated App services and combine with allowed On Prem IP ranges from var.acr_custom_fw_rules
  allowed_ips = distinct(flatten(concat(azurerm_linux_web_app.APPSVC.possible_outbound_ip_address_list, var.acr_custom_fw_rules)))

  acr_fw_rules = [
    {
      default_action = "Deny"
      ip_rules = [for i in local.allowed_ips : {
        action   = "Allow"
        ip_range = i
        }
      ]
      virtual_network_subnets = [
        {
          action    = "Allow"
          subnet_id = azurerm_subnet.SUBNETS["App-Service-Integration-Subnet"].id
        }
      ]
    }
  ]

}
```

I basically get the following error on the first initial run:

![image](https://user-images.githubusercontent.com/44137582/160133789-6302bfc2-9e30-4c23-8659-035da226ed34.png)

Link to the failed initial run:
https://github.com/Pwd9000-ML/Azure-Terraform-Deployments/actions/runs/2040245742

On the second run of the same code, it works fine:

Link to the successful second run:
https://github.com/Pwd9000-ML/Azure-Terraform-Deployments/actions/runs/2040259293

I have tried setting the ACR with an explicit dependency on resource ` depends_on = [azurerm_app_service_virtual_network_swift_connection.azure_vnet_connection]`  to ensure the VNET integration is created fully before building the ACR, however this has no effect and the same error occurs on the initial run, but succeeds on subsequent runs.

**Comment by Pwd9000-ML** [comment]
@magodo mentioned on another thread: https://github.com/hashicorp/terraform-provider-azurerm/issues/16058

Looking through your config above, it appears that the local var acr_fw_rules.ip_rules depends on allowed_ips, which in turn will be expanded after the first apply: Before the first apply, the lenght of the allowed_ips is 1 (comes from var.acr_custom_fw_rules), which is then used for the network_rule_set of the ACR, resulting into one network_rule_set. But after the completion of the 1st apply, the length of allowed_ips is increased into 27 (26 more items from the azurerm_linux_web_app's possible_outbound_ip_address_list). This causes Terraform detects an inconsistency between the plan and the final state, hence the panic you saw above.

(I have opened this issue here as it seems a better place for this issue)

**Comment by jbardin** [comment]
Hi @Pwd9000-ML,

From the example here, combined with the fact that `azurerm_container_registry` uses `SchemaConfigModeAttr` for compatibility, I think you are encountering #22340. 

Because `network_rule_set` is defined as an attribute in that resource, you should be able to avoid the problem using attribute notation. While it could be simplified a bit, reformatting this to work with the existing `local.acr_fw_rules` would look something like:

```
  network_rule_set = [
    {
      default_action = local.acr_fw_rules[0].default_action
      ip_rule = [ for each in local.acr_fw_rules[0].ip_rules :
        {
          action = each["action"]
          ip_range = each["ip_range"]
        }
      ]
      virtual_network = [ for each in local.acr_fw_rules[0].virtual_network_subnets :
        {
          action = each["action"]
          subnet_id = each["subnet_id"]
        }
      ]
    }
  ]
```

Does this prevent the incorrect evaluation of the inner block you are seeing?

**Comment by Pwd9000-ML** [comment]
@jbardin I am not sure I understand correctly.

I am using a dynamic block so that I can have the setting `network_rule_set` as a optional setting:

```hcl
  dynamic "network_rule_set" {
    for_each = local.acr_fw_rules != null ? local.acr_fw_rules : []
    content {
      default_action = network_rule_set.value.default_action
      dynamic "ip_rule" {
        for_each = network_rule_set.value["ip_rules"] != [] ? network_rule_set.value["ip_rules"] : []
        content {
          action   = ip_rule.value["action"]
          ip_range = ip_rule.value["ip_range"]
        }
      }

      dynamic "virtual_network" {
        for_each = network_rule_set.value["virtual_network_subnets"] != [] ? network_rule_set.value["virtual_network_subnets"] : []
        content {
          action    = virtual_network.value["action"]
          subnet_id = virtual_network.value["subnet_id"]
        }
      }
    }
  }
```

The example you give is basically what this dynamic block should interpret the local variable as, as far as I know.

Are you saying I need to get rid of the dynamic block and use the block as you show in your comment?

Ideally I would like to keep this config as dynamic as possible.

**Comment by jbardin** [comment]
The example I showed is no less dynamic than the block version you have, but because the provider elected to use `SchemaConfigModeAttr`, it is no longer technically a block, and the conversion of the block syntax to an attribute interferes with the handling of `dynamic`.

The evaluation of `allowed_ips` is correct, since the plan shows a single `unknown` value for the result, The inconsistency here is that `ip_rule` is only planned with a single value, which it should be an unknown number of values.

**Comment by Pwd9000-ML** [comment]
@jbardin I see what you mean.

I still have a slight issue though with changing the code from a `dynamic` block to a static config of the argument `network_rule_set`.

Does that not mean by doing this, I am assuming that I will always need to make use of a local variable, even if an IP firewall white list and allowed network is not needed. say for example I add that argument as you show, but decided not to use the `network_rule_set`.

Is it correct in my thinking, becuase I am using the attribute with a local variable, that if I  decide I do not want to use that attribute I would need to always explicitly have a local variable such as this?

```hcl
  acr_fw_rules = [
    {
      default_action = null
      ip_rules = []
      virtual_network_subnets = []
    }
  ]
```

I think such a scenario will not work becuase, if you specify the `ip_rules` in config it expects a (required) value:

![image](https://user-images.githubusercontent.com/44137582/160463575-c721c182-8470-482f-bfef-7d5319e22553.png)

**Comment by jbardin** [comment]
The dynamic block syntax does not offer any functionality that can't be done with a for expression; it was created because direct assignment to a block is not possible, so there needed to be another syntax for that type of iteration within a block. Perhaps your confusion stems from the removal of the conditionals like 
```
network_rule_set.value["ip_rules"] != [] ? network_rule_set.value["ip_rules"] : []
```
which I failed to address. These would do nothing in either version, for 2 reasons. The first is that `network_rule_set.value["ip_rules"] != []` is almost always going to be true, because the left hand side is probably never going to be an empty tuple type -- if you want to test for a non-empty list, you can use `length(network_rule_set.value["ip_rules"]) > 0`. Even if the comparison were correct, you  would assign back the same value which you just compared, so it would be a noop.

It would be useful though to confirm if the attribute version does work as you expect, since we could then be assured that #22340 is the actual underlying cause, and there are no other contributing factors from the provider.

**Comment by Pwd9000-ML** [comment]
@jbardin sure I understand.
I'll post my results here on here shortly. Thanks!

**Comment by Pwd9000-ML** [comment]
@jbardin I can confirm the issue now as well with @magodo 

I have reworked this slightly by replacing the `network_rule_set`:

```hcl
  network_rule_set = [
    {
      default_action = var.acr_network_rule_set_default_action
      ip_rule = [for each in local.acr_ip_rules :
        {
          action   = each["action"]
          ip_range = each["ip_range"]
        }
      ]
      virtual_network = [for each in local.acr_virtual_network_subnets :
        {
          action    = each["action"]
          subnet_id = each["subnet_id"]
        }
      ]
    }
  ]
```

My locals:

```hcl
  allowed_ips = distinct(flatten(concat(azurerm_linux_web_app.APPSVC.possible_outbound_ip_address_list, var.acr_custom_fw_rules)))

  acr_ip_rules = [for i in local.allowed_ips :
    {
      action   = "Allow"
      ip_range = i
    }
  ]

  acr_virtual_network_subnets = [
    {
      action    = "Allow"
      subnet_id = azurerm_subnet.SUBNETS["App-Service-Integration-Subnet"].id
    }
  ]
```

Thanks for pointing out the issue with the `ConfigMode` on the `ip_rule`.
