### ISSUE TITLE
aws_dlm_lifecycle_policy | data lifecycle manager rules interval

### ISSUE THREAD

**Issue by abheeshtan** [hashicorp/terraform#30764]
Hi,

Not sure if this was reported already, but I am having trouble following page at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dlm_lifecycle_policy#interval_unit

when it comes to dlm create rule it allows only interval type to Hours. Which makes it difficult to set rules for weekly backup using terraform. 

AWS allows the users to set rules for daily, weekly and cron type of interval. 

### Current Terraform Version

terraform version:  Terraform 0.13+ 
provider version: 4.8.0

### Use-cases

Eg: 

`resource "aws_dlm_lifecycle_policy" "example" {
  description        = "example DLM lifecycle policy"
  execution_role_arn = aws_iam_role.dlm_lifecycle_role.arn
  state              = "ENABLED"

  policy_details {
    resource_types = ["VOLUME"]

    schedule {
      name = "2 weeks of daily snapshots"

      create_rule {
        interval      = 24
        **interval_unit = "HOURS"**              # HOURS is currently the only allowed value and also the default value
        times         = ["23:45"]
      }

      retain_rule {
        count = 14
      }

      tags_to_add = {
        SnapshotCreator = "DLM"
      }

      copy_tags = false

      cross_region_copy_rule {
        target    = "us-west-2"
        encrypted = true
        cmk_arn   = aws_kms_key.dlm_cross_region_copy_cmk.arn
        copy_tags = true
        retain_rule {
          interval      = 30
          interval_unit = "DAYS"
        }
      }
    }

    target_tags = {
      Snapshot = "true"
    }
  }
}`

### Proposal

Requesting the team to add the days and cron type interval for dlm rules, helps in solving issues

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
