### ISSUE TITLE
Raise limit on in-flight operations to avoid pipeline stalls

### ISSUE THREAD

**Issue by pmer** [hashicorp/terraform#30770]
### Current Terraform Version

```
Terraform v1.1.7
on darwin_arm64
```

### Use-cases

Given an Amazon API Gateway with ~100 REST endpoints, where each endpoint is connected to a dedicated AWS Lambda function, use Terraform to deploy 100 AWS Lambda functions in fewer than 30 minutes.

### Attempted Solutions

I've tried setting the parallelism parameter higher than 10, but haven't noticed an improvement.

### Proposal

If I understand correctly, there is a limit to the number of concurrent requests against a cloud provider. For some types of cloud resources, the create operation, update operation, or delete operation may take several minutes. Given enough resources of these types, the Terraform apply step can take a very long time due to what seem to be pipeline stalls. Terraform will wait for some Lambdas to be updated before beginning work on others.

I was wondering, in broad term, as a general concept, if the technique for concurrency limiting in Terraform might benefit from a different parallelism model:

What if a Terraform was allowed to initiate operations on a larger number of resources than currently it does, but when a large number of resources are in transition, the polling checks to see if they resolve are slowed down to such a degree that the number of requests per minute does not actually change? Given a naive model of cloud provider rate limiting, if we are limited by the number of requests per minute, but not the number of cloud resources concurrently updating, might this be able to result in faster completion time for situations where no errors occur during an apply?

Note: Some other issues here and in the AWS provider describe a limit to the number of resources updating at once of a given type within a single cloud provider account.

### References

I've searched through this repo's issues and issues on the AWS provider repo for all comments on concurrency, parallelism, and rate limiting, but did not find anything that seemed to have this proposal

**Comment by jbardin** [comment]
Hi @pmer,

We don't have any indication that the `-parallelism` option is not working in the Terraform CLI, so I suspect the limitation you are seeing is something either inherent to your configuration, or enforced by the provider. Terraform will initiate concurrent operations up to the `parallelism` limit, but there's nothing we can currently do to force a provider to increase its concurrency. Do you have an example showing that the operations are blocked by the CLI itself?

Thanks!

**Comment by pmer** [comment]
Thanks @jbardin! I've tried to create a minimal reproducible example, but it appears to be working correctly there. I think this suggests it is something else going on in my Terraform configuration, and confirms what you say. I'll close this issue.
