### ISSUE TITLE
Lifecycle option to remove resource from state on destroy

### ISSUE THREAD

**Issue by djfinnoy** [hashicorp/terraform#30785]
### Current Terraform Version

 
```
1.1.7
```

### Use-cases

When provisioning a compute instance (eg, a VM, or a cluster), and software that will run on the compute instance; `terraform destroy` can be a bit annoying.

I often create kubernetes clusters, and install some stuff on the cluster with Helm, both via Terraform.
Upon destroy, Terraform will attempt to uninstall the Helm resources before destroying the cluster.
This can often cause problems due to kubernetes finalizers.

I usually just remove the software from the terraform state before running `terraform destroy`.

### Proposal

It would be nice if the `lifecycle` block had an option to simply remove a resource from the state on destroy, instead of attempting to destroy it. This would be very useful for resources that get indirectly destroyed through the destruction of parent resources.

A textbook example of this feature would be how a kubernetes namespace gets deleted indirectly through the destruction of the kubernetes cluster.

```
# Suggestion:
resource "kubernetes_namespace" "example" {
  ...
  lifecycle {
    remove_state_instead_of_destroy = true
  }
}

```

**Comment by jbardin** [comment]
Hi @djfinnoy,

Thanks for filing the request! We are tracking this feature in issue #15485.
