### ISSUE TITLE
Terraform Registry not picking up new version of provider

### ISSUE THREAD

**Issue by lkowalsk-akamai-com** [hashicorp/terraform#30786]
Hi,

My team released yesterday new version (v1.12.0) of Terraform Provider Akamai: https://github.com/akamai/terraform-provider-akamai/releases

This is not being picked up by Terraform Registry as latest is showing as v1.11.0 in the registry docs (https://registry.terraform.io/providers/akamai/akamai/latest/docs) and we are not able to use 1.12.0 in the terraform scripts.

Webhooks are send out correctly from our repository (with the same response as for previous releases) and we followed the same process as for a dozen of previous releases. We even had a successful release as recently as on 1st of March. 

Can you please help us investigating what might be the issue? Happy to share any more details that could be helpful.

**Comment by crw** [comment]
Hi @lkowalsk-akamai-com, is your problem similar to or the same as this on-going issue? https://github.com/hashicorp/terraform/issues/30691

**Comment by lkowalsk-akamai-com** [comment]
Hi @crw, no this is problem with provider, not module. We are in contact with support currently about this issue.

**Comment by crw** [comment]
Since this is being handled by the support team and is not an issue in Terraform Core, I am closing this ticket. Please let me know if you think this is being closed in error.
