### ISSUE TITLE
Rendering $$ as $$

### ISSUE THREAD

**Issue by bentterp** [hashicorp/terraform#3079]
Hi,

I have run into basically the same issue as in #1098:

If I use single $ in a heredoc, then terraform tries to interpolate and fails as that variable doesn't exist.
If I use double $$'s, then it renders in the final document as "$$"....

**Comment by phinze** [comment]
We should definitely have some way of getting a single literal dollar sign into interpolated strings. Tagged as a bug.

**Comment by phinze** [comment]
Consolidating in #2909
