### ISSUE TITLE
Please provide rpm repository for Fedora 36

### ISSUE THREAD

**Issue by christianfosli** [hashicorp/terraform#30790]
### Current Terraform Version

N/A

### Use-cases

I would like to install terraform and terraform language server on Fedora Linux 36 using my distributions package manager.
Fedora Linux 36 is currently in beta and is expected to release later this month.

### Attempted Solutions

I tried to follow the installation guide on https://learn.hashicorp.com/tutorials/terraform/install-cli#install-terraform
but I get an error that the repository does not exist

```
Errors during downloading metadata for repository 'hashicorp':
  - Status code: 404 for https://rpm.releases.hashicorp.com/fedora/36/x86_64/stable/repodata/repomd.xml
```

### Proposal

Please provide an rpm repository for Fedora 36, like you do for Fedora 34/35.

### References

N/A

**Comment by crw** [comment]
Thanks for the request, I am checking with the release engineering team to see how we support new versions of existing OS.

**Comment by crw** [comment]
Fedora Linux 36 is slated to be supported in the near future, certainly before the release of 36 on April 26. Thanks for the inquiry!
