### ISSUE TITLE
Version 1.1.7

### ISSUE THREAD

**Issue by Divyabd** [hashicorp/terraform#30800]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

### References

Initializing modules...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

i am getting error while running my templates  I did tried  uninstalling and reinstalling but still same error

**Comment by jbardin** [comment]
Hi @Divyabd,

Thanks for filing the issue. Can you please include the crash output so we can track down where the error might be. It would also be helpful if you could supply any of the relevant configuration or a reproduction for the crash as well. 

Thanks!

**Comment by jbardin** [comment]
Since we haven't heard back I'm going to close this out. If you have more information about the crash, please file a new issue with the requested info.

Thanks!
