### ISSUE TITLE
Escaped Backslash Doesn't Return Literal Backslash

### ISSUE THREAD

**Issue by hwwilliams** [hashicorp/terraform#30807]
### Terraform Version

```
Terraform v1.1.7
on windows_amd64
```

### Terraform Configuration Files

```terraform
shares = {
  "storage1_profiles" = {
    name = "profiles"
    url = "https://storage1.example.com/profiles"
  },
  "storage2_profiles" = {
    name = "profiles"
    url = "https://storage2.example.com/profiles"
  }
}

locals {
  share_urls = flatten([
    for share_key, share_properties in var.shares :
    replace(replace(share_properties.url, "https://", "\\"), "/", "\\")
    if share_properties.name == "profiles"
  ])
}

output "share_urls" {
  value = local.share_urls
}
```

### Debug Output

```terraform
Outputs:

share_urls = [
  "\\storage1.example.com\\profiles",
  "\\storage2.example.com\\profiles",
]
```

### Expected Behavior

Escaped backslash should only return a single backslash.

`\\storage1.example.com\profiles`

### Actual Behavior

Escaped backslash returns both backslashes.

`\\storage1.example.com\\profiles`

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @hwwilliams,

Since the output value displayed in the UI is quoted to resemble how it would look if written in configuration, the additional backslash in the output _is_ the escaping needed to make that output be valid string syntax. The real string value underneath is `\storage.example.com\profiles`.

**Comment by hwwilliams** [comment]
Thank you, I was able to save the output to an Azure blob and confirm this is correct. Apologies for the confusion.
