### ISSUE TITLE
Cloudfront lifecycle ignore_changes not working on ordered_cache_behavior path_pattern attribute

### ISSUE THREAD

**Issue by ms4thyear** [hashicorp/terraform#30805]
Hello,

I am facing a strange issue where i am trying to ignore the path_pattern attribute in the cloudfront ordered_cache_behavior but its not working as expected

### Terraform Version
Terraform Version: 1.0.8
AWS provider version: 3.61.0

### Terraform Configuration Files

```hcl
lifecycle {
    ignore_changes = [
      ordered_cache_behavior.0.path_pattern
    ]
  }
```

### Debug Output

```
│ Error: error updating CloudFront Distribution (XXXXXXXXXXX): InvalidArgument: The parameter path pattern must be unique.
│       status code: 400, request id: 123abcd-57a4-4bd4-84a5-5c9aba5ee9af
│
│   with aws_cloudfront_distribution.this,
│   on cloudfront.tf line 1, in resource "aws_cloudfront_distribution" "this":
│    1: resource "aws_cloudfront_distribution" "this" {
```

### Expected Behavior

Terraform should ignore any changes to the path_pattern attribute of the first element declared in the cloudfront's ordered_cache_behavior

### Actual Behavior

Terraform throwing error "The parameter path pattern must be unique"

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by ms4thyear** [comment]
Hi @jbardin,

Please find the below example code which i am trying to implement-

resource "aws_cloudfront_distribution" "this" {
..................

origin {
    domain_name = "bucket_name.s3.region.amazonaws.com"
    origin_id   = "s3-default"

    s3_origin_config {
      origin_access_identity = var.aws_cloudfront_origin_access_identity
    }
  }

............................
default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "s3-default"
    cache_policy_id  = data.aws_cloudfront_cache_policy.managed_cachingoptimized.id
    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }
....................................

ordered_cache_behavior {
    path_pattern     = "/abc/*"         #Need to ignore this first path_pattern attribute defined in ordered_cache_behavior
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "s3-default"
    cache_policy_id  = data.aws_cloudfront_cache_policy.managed_cachingoptimized.id
    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }

ordered_cache_behavior {
    path_pattern     = "/xyz/*"
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "s3-default"
    cache_policy_id  = data.aws_cloudfront_cache_policy.managed_cachingoptimized.id
    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }
....................................

lifecycle {
    ignore_changes = [
      ordered_cache_behavior.0.path_pattern
    ]
  }

}

**Comment by jbardin** [comment]
Thanks @ms4thyear,

Actually I missed a potential initial problem here, `ordered_cache_behavior` is a list, so the correct syntax to access the first element would be:
    ignore_changes = [ ordered_cache_behavior[0].path_pattern ]

Does that change result in the desired behavior?
If not, it would help to have the state of the resource you are working with too so we can wee exactly what change we are trying to prevent. The error from the provider is also no particularly helpful here, have you confirmed that manually changing the `path_pattern` value to the prior value results is all that's required to prevent the error?

**Comment by ms4thyear** [comment]
Hello @jbardin ,

I think i found why this error is occurring. I am adding a new ordered_cache_behavior and trying to ignore the path_pattern of that behavior at the same time. I was able to have a workaround by creating the ordered_cache_behavior first and then adding the lifecycle ignore_changes like you mentioned

 ignore_changes = [ ordered_cache_behavior[0].path_pattern ]
 
 Not sure of the cause though as i believe terraform creates the resource first even if we add the ignore block to the same resource during the first run. The changes are ignored during the subsequent runs. Do you know if we can handle them simultaneously to avoid running terraform twice.

**Comment by jbardin** [comment]
If i understand correctly what you are doing, `ignore_changes` is not taking effect here because there is no prior value of `ordered_cache_behavior[0].path_pattern` to ignore, i.e. the `ordered_cache_behavior[0]` path is not valid against the prior state so no action is taken.

The general use case for `ignore_changes` is to prevent Terraform from reverting changes made externally, so in the case of `ordered_cache_behavior` you could prevent reverting a change to `ordered_cache_behavior[0].path_pattern`, or you could prevent changing the entirety of `ordered_cache_behavior`, but there is no way to selectively "filter" configuration values from being applied at all when there is no existing value. Looking at the schema for `aws_cloudfront_distribution` however, `path_pattern` is required, so there would be no way to apply the initial configuration without that value in the first place.

**Comment by ms4thyear** [comment]
@jbardin Thank You for the detailed explanation.
