### ISSUE TITLE
Upgrading the terraform binary to a minor patch version

### ISSUE THREAD

**Issue by aviksamanta1986** [hashicorp/terraform#30813]
I am currently on 0.12.20 of terraform core. I want to upgrade the terraform core binary to 0.12.31 (to use the new hashicorp key). Is there a place where I can download the minor patch from? Can I have multiple terraform core installed and then chose a version using the version blocks?

**Comment by crw** [comment]
Hi @aviksamanta1986, try asking on the [Community Forum](https://discuss.hashicorp.com/c/terraform-core/27), you will get a better response there. Github issues are used for bug reports and feature requests, not for general questions and discussions. Thanks for your understanding!

> Is there a place where I can download the minor patch from?

https://releases.hashicorp.com/terraform/
