### ISSUE TITLE
Yaml Encode does not escape trailing ' or " char.

### ISSUE THREAD

**Issue by fr6nco** [hashicorp/terraform#30815]
### Terraform Version
```
Tomass-MacBook-Pro:madme-prod thomas$ terraform version
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.18.0
+ provider registry.terraform.io/hashicorp/azurerm v2.97.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```terraform

output "ansible_inventory" {
  value = yamlencode({
    "all": {
      "vars": {
        "ansible_ssh_common_args": "-o ProxyCommand='ssh -W %h:%p %r@${module.base.bastion_public_ip}' -o StrictHostKeyChecking=no -o ForwardAgent=yes"
      }
    },
    "_meta": {
      "hostvars": {}
    }
  })
}

```

### Expected Behavior
Valid Yaml file should be printed on screen.

Expected output:
```

"_meta":
  "hostvars": {}
"all":
  "children": {}
  "vars":
    "ansible_ssh_common_args": "-o ProxyCommand='ssh -W %h:%p %r@----------' -o StrictHostKeyChecking=no -o ForwardAgent=yes"
```

### Actual Behavior
Newline (\n) is inserted after the terminating ' char. Tested with ", \\" and \\' too. same result.

```

"_meta":
  "hostvars": {}
"all":
  "children": {}
  "vars":
    "ansible_ssh_common_args": "-o ProxyCommand='ssh -W %h:%p %r@----------'
      -o StrictHostKeyChecking=no -o ForwardAgent=yes"

```

**Comment by alisdair** [comment]
Thanks for the report. I'm able to reproduce this behaviour.

This appears to be correct YAML output, using [double-quoted flow scalar style](https://yaml.org/spec/1.2.2/#73-flow-scalar-styles). A correct YAML parser will unwrap these lines into a single string with no newline characters. For example, [try this YAML to JSON converter](https://jsonformatter.org/yaml-to-json) with the YAML output from your example.

I'm going to close this as I don't believe there's a bug here.
