### ISSUE TITLE
error provisioning azure backup vault

### ISSUE THREAD

**Issue by frasevi123** [hashicorp/terraform#30821]
---------
maint.tf
----------

recurso "azurerm_data_protection_backup_vault" "azbv" {
  nombre                = local.azbv_name
  resource_group_name = local.rsgr_name
  ubicación            = local.azbv_location
       datastore_type = VaultStore
  redundancia          = "Localmente redundante"
                 tag = fusionar(var. etiquetas, local. etiqueta)

   identidad {
    tipo = "SystemAssigned"
  }
}

------------------
APPLY - ERROR
------------------
Terraform v0.14.5
Initializing plugins and modules...
[0m[1mmodule.azlogin.null_resource.azlogin: Destroying... [id=7966894638887294836][0m[0m
[0m[1mmodule.azlogin.null_resource.azlogin: Destruction complete after 0s[0m[0m
[0m[1mmodule.azlogin.null_resource.azlogin: Creating...[0m[0m
[0m[1mmodule.azlogin.null_resource.azlogin: Provisioning with 'local-exec'...[0m[0m
[0m[0mmodule.azlogin.null_resource.azlogin (local-exec): Executing: ["/bin/sh" "-c" "az login --service-principal --username $CLI_CLIENT_ID  --password $CLI_CLIENT_SECRET --tenant $ARM_TENANT_ID --output none && az account set -s $ARM_SUBSCRIPTION_ID"]
[0m[1mmodule.azlogin.null_resource.azlogin: Creation complete after 4s [id=7631440833658029045][0m[0m
[0m[1mmodule.infr_env.module.akvt.azurerm_monitor_diagnostic_setting.log["eastus2"]: Modifying... [id=/subscriptions/c2c4b9e6-06db-47c1-8a66-17e4ae19fb6a/resourceGroups/RSGREU2IAC2D90/providers/Microsoft.KeyVault/vaults/akvteu2iac2d93|AKVTEU2IAC2D90_AuditLog][0m[0m
[0m[1mmodule.infr_env.module.akvt.azurerm_monitor_diagnostic_setting.log["eastus2"]: Modifications complete after 4s [id=/subscriptions/c2c4b9e6-06db-47c1-8a66-17e4ae19fb6a/resourceGroups/RSGREU2IAC2D90/providers/Microsoft.KeyVault/vaults/akvteu2iac2d93|AKVTEU2IAC2D90_AuditLog][0m[0m
[0m[1mmodule.infr_env.module.stac_cloudshell.data.azurerm_client_config.current: Reading... [id=2022-04-07 14:54:48.175011052 +0000 UTC][0m[0m
[0m[1mmodule.infr_env.module.stac_cloudshell.data.azurerm_subscription.current: Reading... [id=/subscriptions/c2c4b9e6-06db-47c1-8a66-17e4ae19fb6a][0m[0m
[0m[1mmodule.infr_env.module.stac_infr.data.azurerm_client_config.current: Reading... [id=2022-04-07 14:54:48.181163883 +0000 UTC][0m[0m
[0m[1mmodule.infr_env.module.stac_infr.data.azurerm_subscription.current: Reading... [id=/subscriptions/c2c4b9e6-06db-47c1-8a66-17e4ae19fb6a][0m[0m
[0m[1mmodule.infr_env.module.stac_cloudshell.data.azurerm_subscription.current: Read complete after 0s [id=/subscriptions/c2c4b9e6-06db-47c1-8a66-17e4ae19fb6a][0m[0m
[0m[1mmodule.infr_env.module.stac_infr.data.azurerm_subscription.current: Read complete after 0s [id=/subscriptions/c2c4b9e6-06db-47c1-8a66-17e4ae19fb6a][0m[0m
[0m[1mmodule.infr_env.module.stac_cloudshell.data.azurerm_client_config.current: Read complete after 0s [id=2022-04-07 18:11:23.472065103 +0000 UTC][0m[0m
[0m[1mmodule.infr_env.module.stac_infr.data.azurerm_client_config.current: Read complete after 0s [id=2022-04-07 18:11:23.498099268 +0000 UTC][0m[0m
[0m[1mmodule.azbv.azurerm_data_protection_backup_vault.azbv: Creating...[0m[0m
[33m
[1m[33mWarning: [0m[0m[1mVersion constraints inside provider configuration blocks are deprecated[0m

[0m  on providers.tf line 87, in provider "azurerm":
  87:   version = [4m"2.82.0"[0m
[0m
Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

(and one more similar warning elsewhere)
[0m[0m
[31m
[1m[31mError: [0m[0m[1mcreating DataProtection BackupVault ("Backup Vault: (Name \"azbveu2iac2d01\" / Resource Group \"RSGREU2IAC2D90\")"): dataprotection.BackupVaultsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="AuthorizationFailed" Message="The client '8a540192-c208-4443-b687-aa5c2bc19e8e' with object id '8a540192-c208-4443-b687-aa5c2bc19e8e' does not have authorization to perform action 'Microsoft.DataProtection/backupVaults/write' over scope '/subscriptions/c2c4b9e6-06db-47c1-8a66-17e4ae19fb6a/resourceGroups/RSGREU2IAC2D90/providers/Microsoft.DataProtection/backupVaults/azbveu2iac2d01' or the scope is invalid. If access was recently granted, please refresh your credentials."[0m

[0m  on .terraform/modules/azbv/main.tf line 2, in resource "azurerm_data_protection_backup_vault" "azbv":
   2: resource "azurerm_data_protection_backup_vault" "azbv" [4m{[0m
[0m
[0m[0m


**Comment by crw** [comment]
Hello @frasevi123,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
