### ISSUE TITLE
"terraform validate" should not fail on partial implicit provider configuration

### ISSUE THREAD

**Issue by adamantike** [hashicorp/terraform#30840]
## Description

Currently, `terraform validate` includes a short-circuit to avoid validating a provider that doesn't have any explicit configuration. However, there are scenarios where a subset of the provider configuration needs to be specified, while the rest of it (commonly, required parameters) are retrieved from environment variables only being set in the remote backend.

### Terraform Version
```
Terraform v1.1.8
on linux_amd64
```

### Terraform Configuration Files
```terraform
terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.31.0"
    }
  }
}

provider "snowflake" {}

provider "snowflake" {
  alias = "useradmin"
  role  = "USERADMIN"
}

resource "snowflake_role" "r1" {
  name = "role1"
}

resource "snowflake_role" "r2" {
  provider = snowflake.useradmin

  name = "role2"
}
```

### Debug Output
https://gist.github.com/adamantike/9f97cc1c43acb9a87cd3b3839d355d13

### Expected Behavior
`terraform validate` should pass without errors, considering both providers valid.

### Actual Behavior
`terraform validate` fails, considering the second provider (which has the `role` parameter configured) is missing other required parameters.

### Steps to Reproduce
1. `terraform init`
2. `terraform validate`

### Additional Context
For this scenario, the first `snowflake` provider is completely configured using environment variables in Terraform Cloud. The second one needs to use the same configuration, except for the `role` which has to be different (this allows using the same Snowflake credentials, with different roles).

### References
A similar issue was discussed in #21408 (and closed by #24896), but only considered providers that had an `alias` set, not a subset of parameters being specified.

**Comment by crw** [comment]
Hi @adamantike, apologies for the late reply. The validation behavior you are encountering is determined by the authors of the provider. Thus, in order to see that behavior changed you will need to open an issue on the provider directly. Looking at the registry and doing a quick google search, the current repository location seems to be: https://github.com/Snowflake-Labs/terraform-provider-snowflake. Thanks for this report!

**Comment by adamantike** [comment]
Hi @crw. Thanks for your response, but I don't think it's accurate. I will appreciate if this can be reviewed again to decide if it should be reopened.

This is an example showing the same failure when running `terraform validate`, using a Hashicorp provider:

```hcl
terraform {
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = "3.8.2"
    }
  }
}

provider "vault" {}

provider "vault" {
  alias = "token2"
  token = "test"
}

resource "vault_generic_secret" "example" {
  path      = "secret/foo"
  data_json = jsonencode({ "foo" = "bar" })
}

resource "vault_generic_secret" "example2" {
  provider  = vault.token2
  path      = "secret/foo"
  data_json = jsonencode({ "foo" = "bar" })
}
```

Displayed error:
```shell
$ terraform validate
╷
│ Error: Missing required argument
│
│   on main_azure.tf line 12, in provider "vault":
│   12: provider "vault" {
│
│ The argument "address" is required, but no definition was found.
```
