### ISSUE TITLE
Allow terraform init to create local execution cloud workspaces

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform#30844]
Hi,

I have started to use terraform enterprise to store statefiles.  I do not use it to run terraform, as this is handled by GitHub Actions.

The following are a couple of suggestions which would help me store the statefiles.

### Automatically creating workspaces
I set my backend block as 
```
terraform {
  backend "remote" {
    hostname     = "MyHostName"
    organization = "MyOrg"

    workspaces {
      prefix = "MyGitHubRepo-"
    }
  }
}
```

The short workspace name to be the suffix to ```MyGitHubRepo``` is determined from the GitHub Actions workflow, it will normally be an environment such as ```dev``` or ```prod```.  This is then set as the ```TF_WORKSPACE``` value.

#### I would like the ```terraform init``` to be able to create the workflow automatically but with a workspace execution mode of ```local```.  Currently I believe it only creates it with an Execution mode of ```Remote```.

I am aware of the newer ```cloud``` block but could not work out how that would be used to create a new workspace if only ```tags``` were supplied - and I think it maybe even makes my problem harder to solve.

### Naming statefiles in the workspace
Even better than the above would be the ability to name the terraform statefiles in the workspace.  So I would set my backend block as above but with ```name = "MyGitHubRepo"```.

I would then be able to put all my statefiles created from that one GitHub Repo into the one workspace.

So I would essentially run something similar to:
```terraform init -backend-config=key=$MyStateFileName```

This is what I currently do now when storing statefiles on S3.  The S3 bucket has:

A folder named after the GitHub Org
Subfolders named after the Repos
Statefiles in each Repo folder named after the GitHub Action Workflow (eg ```MyWorkFlow-dev.tfstate```)

Thanks.

**Comment by barrettclark** [comment]
I'm closing this for now as we are in the process of thinking through some higher-level workflow ideas for Terraform Cloud.

Using the `cloud` implementation with tags, you will still need to specify a workspace name (or select a workspace). You can export state from the cloud as well if you need to have a copy of it locally.
