### ISSUE TITLE
Issue with configuration_manager_version when applying to aws_opsworks_custom_layer

### ISSUE THREAD

**Issue by alohaahola** [hashicorp/terraform#30852]
Hello, I built an opsworks stack with terraform. The Chef version is set to 12.2 (Windows). Any changes to the stack/layers results in an error related to the Chef version even though it hasn't changed. The error is always preceded by: `can only be set for Chef::11.10, Chef::12`. I've tried commenting out the `configuration_manager_version` in my aws_opsworks_stack block but the error persists. 

### Terraform Version
```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.9.0
```

### Terraform Configuration Files
Layer config
```terraform
resource "aws_opsworks_custom_layer" "xxxxxx_hls_1_layer" {
  name                      = var.layer_name.xxxxxx_hls_1
  short_name                = var.layer_short_name.xxxxxx_hls_1
  stack_id                  = aws_opsworks_stack.ow_stack.id
  auto_assign_public_ips    = "true"
  auto_assign_elastic_ips   = "false"
  custom_security_group_ids = ["sg-xxxxxx"]

  custom_setup_recipes = [
    "iceberg::setup",
    "iceberg::nagios_registration",
    "datadog::setup"
  ]
  custom_deploy_recipes = [
    "iceberg::deploy",
    "iceberg::deploy_vader"
  ]
  custom_shutdown_recipes = [
    "iceberg::nagios_deregistration"
  ]

  custom_json = <<EOT
{
    "layer_var": {
        "layer_env": "prod",
        "layer_type": "xxxxxx",
        "app_short_name": "xxxxxx_prod"
    },
        "datadog": {
        "agent_major_version": 7,
        "api_key": "xxxxxx",
        "application_key": "xxxxxx"
    }
}
EOT
}

```

### Debug Output
https://gist.github.com/alohaahola/58f8630169b68141192bada0a48b1915

### Expected Behavior
The new recipe is added to the layer. 

### Actual Behavior
```
╷
│ Error: error updating Opsworks Layer (2013cabe-d495-425b-8028-4e200cad896b): ValidationException: Cloud Watch Logs Configuration: can only be set for Chef::11.10, Chef::12
│
│   with aws_opsworks_custom_layer.audacy_hls_1_layer,
│   on layer_xxxxxxx_hls_ib1.tf line 26, in resource "aws_opsworks_custom_layer" "xxxxxxx_hls_1_layer":
│   26: resource "aws_opsworks_custom_layer" "xxxxxxx_hls_1_layer" {
│
╵
```

### Steps to Reproduce
1. Update my layer.tf file to include a setup recipe
2. terraform apply
3. Receive error

### Additional Context
I've never set cloudwatch logs for any of my layers. This error comes up at random. I can make changes to security groups in the stack and not receive the `can only be set for Chef::11.10, Chef::12` error

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
