### ISSUE TITLE
Terraform CLI treats invalid 'plan' commands as 'plan' when -out file contains an extension

### ISSUE THREAD

**Issue by rymancl** [hashicorp/terraform#30870]
Terraform CLI on Windows seems to allow any command that starts with "plan" as a plan command. For example:
* plant
* planasdf

Tested with a few other commands and only found `plan` to be a culprit, but there could be others that we didn't test.

### Terraform Version

Tested on Windows 1.0.3 and 1.1.8. ~~Cannot reproduce on linux/mac.~~
```
Terraform v1.1.8
on windows_amd64
```

### Terraform Configuration Files

```
N/A
```

### Expected Behavior

> Terraform has no command named "plant". Did you mean "plan"?

It does do this with `-h` but not the actual command.
![image](https://user-images.githubusercontent.com/3211227/163401356-e9c218ba-8dc7-4c61-8fe0-7b597a910f1f.png)

### Actual Behavior

Terraform allows the command.
![image](https://user-images.githubusercontent.com/3211227/163401949-285025a3-f041-4d9b-bcf5-693f9fceff87.png)

![image](https://user-images.githubusercontent.com/3211227/163401131-49ad1bc6-e0a5-44db-b9dd-e899116b04ff.png)

### Steps to Reproduce
1. `terraform planasdf`

**Comment by SignalRichard** [comment]
Hi @jbardin,

Please find the attached output that contains the environment details as well as the output of the command with trace enabled.

I did try other commands and did not encounter this same issue.  Additionally, this issue does not occur if the `-out` option is not included; if the command is simply `terraform planasdf` then the expected error occurs where terraform says that the command does not exist.

Please let me know if I can provide any other details!

[output.log](https://github.com/hashicorp/terraform/files/8490366/output.log)

**Comment by jbardin** [comment]
Thanks @SignalRichard! The `-out` option is somehow the trigger in this case. I'm not able to replicate it with any other flags from the few I've tried.

**Comment by rymancl** [comment]
Even further, this only occurs when the out file contains a file extension. Confirmed this on both Mac and Windows.

(Ignore the errors from a non-Terraform directory below, I was just testing the CLI).

```
-> terraform planasdf -out test
Terraform has no command named "planasdf".

To see all of Terraform's top-level commands, run:
  terraform -help


-> terraform planasdf -out test.plan
╷
│ Error: No configuration files
│ 
│ Plan requires configuration to be present. Planning without a configuration would mark everything for destruction, which is normally not what is desired. If you would like to destroy everything, run plan with the -destroy option. Otherwise, create a Terraform
│ configuration file (.tf file) and try again.
╵


-> terraform planasdf -out test.tfplan
╷
│ Error: No configuration files
│ 
│ Plan requires configuration to be present. Planning without a configuration would mark everything for destruction, which is normally not what is desired. If you would like to destroy everything, run plan with the -destroy option. Otherwise, create a Terraform
│ configuration file (.tf file) and try again.
```

**Comment by apparentlymart** [comment]
I was able to reproduce this on my Linux system even without a dot in the filename:

```
$ terraform plandfd -out=tfplan
null_resource.foo: Refreshing state... [id=1034347886630604491]

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.bar will be created
  + resource "null_resource" "bar" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
```

I'm using a build from the `main` branch, so something roughly equivalent to v1.2.0-alpha20220413.

At the top of the `TF_LOG=trace` output I see the arguments slice which seems to match what I expected, indicating that this problem is within Terraform itself somewhere rather than being a problem of the shell's tokenization of the command line. (Or, on Windows, the Go standard library's tokenization of the command line.)

```
2022-04-14T10:17:34.363-0700 [INFO]  Terraform version: 1.1.0 dev
2022-04-14T10:17:34.364-0700 [DEBUG] using github.com/hashicorp/go-tfe v0.26.0
2022-04-14T10:17:34.364-0700 [DEBUG] using github.com/hashicorp/hcl/v2 v2.11.1
2022-04-14T10:17:34.364-0700 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2022-04-14T10:17:34.364-0700 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2022-04-14T10:17:34.364-0700 [DEBUG] using github.com/zclconf/go-cty v1.10.0
2022-04-14T10:17:34.364-0700 [INFO]  Go runtime version: go1.17.2
2022-04-14T10:17:34.364-0700 [INFO]  CLI args: []string{"terraform", "plandfd", "-out=tfplan"}
```

**Comment by kmoe** [comment]
Confirmed all behaviour observed above on Linux and macOS.

The three most interesting examples are:
```
$ terraform planasdf -out test
# good
```

```
$ terraform planasdf -out tfplan
# bad
```

```
$ terraform planasdf -out tfplann
# good
```

The differentiating factor is therefore not whether the filename has a dot, but whether it ends in the string "plan".

The same approach works for other commands, e.g. `refresh`:
```
$ terraform refreshsh -target=no     
Terraform has no command named "refreshsh". Did you mean "refresh"?

To see all of Terraform's top-level commands, run:
  terraform -help
```

```
$ terraform refreshsh -target=refresh  
╷
│ Error: Invalid target "refresh"
│ 
│ Resource specification must include a resource type and name.
╵

For more help on using this command, run:
  terraform refresh -help
```

As noted by @apparentlymart above, Terraform receives the correct arguments, and supplies the arguments to mitchellh/cli, but `cliRunner.Subcommand()` returns an incorrect subcommand: https://github.com/hashicorp/terraform/blob/5ac1074c541f6e2dff4e05459764cf9f943168d3/main.go#L293

This is therefore a bug in mitchellh/cli. Demonstrated using that library's test cases and will fix there.
