### ISSUE TITLE
Terraform 1.2.0-alpha20220413 Does Not Recognize S3 GLACIER_IR Storage Class in Lifecycle Policy

### ISSUE THREAD

**Issue by maattp** [hashicorp/terraform#30876]
### Terraform Version
```
1.2.0-alpha20220413
```

### Debug Output
```
Error: expected lifecycle_rule.1.transition.0.storage_class to be one of [GLACIER STANDARD_IA ONEZONE_IA INTELLIGENT_TIERING DEEP_ARCHIVE], got GLACIER_IR
```

### Expected Behavior
GLACIER_IR should be supported.

### Actual Behavior
It isn't recognized.

### Steps to Reproduce
1. Create an S3 lifecycle rule which transitions content to GLACIER_IR
```
lifecycle_rule {
    id = "rule"

    enabled                             = true
    tags                                   = {}

    transition {
      days                               = 90
      storage_class               = "GLACIER_IR"
    }
  }
```
2. terraform plan

**Comment by crw** [comment]
Hello @maattp,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
