### ISSUE TITLE
Terraform apply works properly but receiving error when calling terraform destroy

### ISSUE THREAD

**Issue by JoshuaFurman** [hashicorp/terraform#30875]
### Terraform Version
```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vsphere v2.1.1
+ provider registry.terraform.io/rancher/rancher2 v1.23.0
```

### Terraform Configuration Files
data-source-definition
```terraform
data "vsphere_datastore_cluster" "datastore_cluster" {
  for_each = toset(var.vsphere_datastore_cluster == "" ? [] : split(",", var.vsphere_datastore_cluster))
  name = each.value
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
```
resource-causing-error
```terraform
resource "vsphere_datastore_cluster_vm_anti_affinity_rule" "cluster_vm_anti_affinity_rule" {
  count = var.node_count > length(data.vsphere_datastore_cluster.datastore_cluster) && var.vsphere_datastore_cluster != "" && var.vsphere_datastore_cluster_antiaffi == true ? 1 : 0 
  name  = "${var.hostname_prefix}_datastore_anti_affinity_rule"
  datastore_cluster_id = values(data.vsphere_datastore_cluster.datastore_cluster)[0].id
  virtual_machine_ids = vsphere_virtual_machine.cluster.*.id
}
```

### Debug Output
```bash
Error: Invalid count argument

  on ../../modules/k8s_cluster/modules/vsphere/modules/cluster/main.tf line 90, in resource "vsphere_datastore_cluster_vm_anti_affinity_rule" "cluster_vm_anti_affinity_rule":
  90:   count = var.node_count > length(data.vsphere_datastore_cluster.datastore_cluster) && var.vsphere_datastore_cluster != "" && var.vsphere_datastore_cluster_antiaffi == true ? 1 : 0 

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

### Expected Behavior
Terraform apply should provision our infrastructure and terraform destroy should destroy our infrastructure.

### Actual Behavior
Terraform allows us to provision our infrastructure without creating a "vsphere_datastore_cluster_vm_anti_affinity_rule" resource but when we run terraform destroy on the same infrastructure we are receiving the error specified above... 

This error only occurs when we DO NOT use a datastore_cluster. But ONLY WHEN we use a single datastore.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform destroy`
4.  `ERROR`

### Additional Context
Upgrading from Terraform cli v0.12 to v0.13 has caused this error. 

Prior to upgrade, we were able to spin up our infrastructure using either a datastore or a datastore cluster. 

After upgrade, when we use a datastore cluster we can apply and destroy our infrastructure just fine. However, when we specify to use only a datastore our apply command spins up our infrastructure just fine but calling the destroy command makes terraform error out.

It seems to be trying to update/refresh the "vsphere_datastore_cluster_vm_anti_affinity_rule" resource even though we are not using this resource?

How can I get around this error? 
Thank you!

**Comment by jbardin** [comment]
Hi @JoshuaFurman,

I have a feeing that this is a result of what used to be a separate "refresh" phase in the planning process, and using` -refresh=false` may be able to work around that. 

Since we are no longer actively maintaining v0.13, so there's not any fix that we can offer for that version. If you can reproduce the error in a current release, please file a new issue with the configuration to reproduce it. For general questions it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more users ready to help.

Thanks!

**Comment by JoshuaFurman** [comment]
Thank you!
