### ISSUE TITLE
lifecycle: run once

### ISSUE THREAD

**Issue by failshell** [hashicorp/terraform#3088]
It would be nice if we could flag resources as run once. The behaviour would be for Terraform to create the resource and then don't update it if it notices it's been change.

Let me give you a use case for it. We have a primary and secondary VPN network between our VPCs. Custom routes are added to our route tables for the primary. But in we sometimes switch to our secondary VPN network for maintenances for example. Problem is, we do that with a CLI tool we wrote. As it's faster than fetching our TF repo, making a change, and then applying that change. Our tool allows us to switch routes rapidly. But if someone in our teams isn't aware of that change for some reason, and runs TF, it will revert our routing back to the primary. Might not be good.

**Comment by KoeSystems** [comment]
+1

**Comment by phinze** [comment]
Yep - the use case makes sense. Closing this to consolidate around #2018

**Comment by akamalov** [comment]
Pardon my ignorance, was runOnce feature ever implemented? Thanks so much in advance!!
