### ISSUE TITLE
[FEATURE REQ] Cache the providers somewhere to avoid downloading multi times in different samples

### ISSUE THREAD

**Issue by moarychan** [hashicorp/terraform#30887]
I have lots of samples to use and they all have been configured with the terraform support, I need to download the terraform providers for each sample terraform directory in the same system (OS). 

When I execute the `terraform -chdir=terraform init`, I am stuck here for a long time and there is no progress data. 

```text

Initializing the backend...

Initializing provider plugins...
- Finding aztfmod/azurecaf versions matching "1.2.16"...
- Finding hashicorp/azurerm versions matching "2.99.0"...
- Installing hashicorp/azurerm v2.99.0...


```

I would like to be able to reuse the providers which already been downloaded in another sample to save time.

For Chinese developers, it is more difficult to download smoothly O(∩_∩)O.

### Current Terraform Version

```
Terraform v1.1.3
on windows_amd64
```

### Use-cases
Each sample can use the cached terraform providers, just download the relevant provider once.

**Comment by crw** [comment]
@moarychan I am going to close this one based on the answer above. Please let me know if the [plugin cache directory](https://www.terraform.io/cli/config/config-file#provider-plugin-cache) setting does not meet your needs. We also have a [discussion forum](https://discuss.hashicorp.com/c/terraform-core/27) for asking usage questions. Thanks!
