### ISSUE TITLE
terraform refresh -help doesn't include all available options (like -parallelism)

### ISSUE THREAD

**Issue by LDVSOFT** [hashicorp/terraform#30880]
### Terraform Version
```
Terraform v1.1.8
on linux_amd64
```

### Terraform Configuration Files
_Any will do._

### Expected Behavior
Terraform help messages for `apply` and `refresh` share all common flags (since commands are quite similar), like `-parallelism` and `-var`, since they both actually accept those.

### Actual Behavior
Terraform accepts several flags for `apply` command in `refresh` command (like `-parallelism`), but doesn't state those in `-help`. Also, for some reason `apply -help` doesn't state `-var` flags.

### Steps to Reproduce
On any example:
* `terraform refresh -help` (there is no `-parallelism`),
* `terraform refresh -parallelism 1000` (it is accepted and speed in my case is different).

**Comment by kmoe** [comment]
At the end of the `terraform apply` help text the following is displayed:
```
  If you don't provide a saved plan file then this command will also accept
  all of the plan-customization options accepted by the terraform plan command.
  For more information on those options, run:
      terraform plan -help
```

The help text for `plan` includes the `-parallelism` and `-var` options you mentioned.

As for `refresh`, the help text is particularly unhelpful, mentioning a subset of the allowed options but not pointing to the `plan` help text. Opened #30892 to fix. 

Thanks for spotting this. Out of curiosity, what's your use case for a high-parallelism `terraform refresh`?

**Comment by LDVSOFT** [comment]
@kmoe Thank you! Yeah, I've seen that it states looking at `plan`, but it's like saying read the docs here, not exactly what one expects out of `-help` ;)

For me, I'm using Terraform CLI with quite large state in quite far cloud, so every single resource check takes some time due to RTT, so increasing parallelism really boosts planning time. 1000 here isn't the exact wanted number, it's just for "go crazy on parallel queries", it runs almost twice as fast with it. So I just pass that flag to all applies and plans.
