### ISSUE TITLE
Unable to launch ec2 instance with multiple EFA network interfaces

### ISSUE THREAD

**Issue by DanielJuravski** [hashicorp/terraform#30886]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.7
Terraform AWS Provider v4.10.0

### Affected Resource(s)

* aws_network_interface
* aws_instance

### Terraform Configuration Files

```hcl
provider "aws" {
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
    region = "${var.region}"
}

resource "aws_network_interface" "ec2_ani" {
    subnet_id = "${var.region}"
    security_groups = ["${var.region}"]
    interface_type = "efa"
    count = "2"
}

resource "aws_instance" "ec2_instance" {
    count         = "1"
    ami           = "${var.instance_ami}"
    instance_type = "dl1.24xlarge"
    key_name      = "${var.key_name}"
    network_interface {
        device_index            = 0
        network_interface_id    = "${element(aws_network_interface.ec2_ani.*.id, 0)}"
    }
    network_interface {
        device_index            = 1
        network_interface_id    = "${element(aws_network_interface.ec2_ani.*.id, 1)}"
    }
}

```

### Expected Behavior

To be created 2 EFA network interfaces, and an ec2 instance with 2 attachments to those network interfaces

### Actual Behavior

│ Error: Error launching source instance: AttachmentLimitExceeded: EFA interface count 2 exceeds allowed limit for dl1.24xlarge
│       status code: 400, request id: a720dc77-5066-4542-a74d-db30f26a2c14

### Steps to Reproduce

1. Create terraform manifest main.tf with context above
2. `terraform apply`

### Important Factoids

Commenting out the above `interface_type` from value - will recreate 2 ENA network interfaces and attach them to the instance just fine. The issue comes only with the EFA network interface.
dl1.24xlarge should support up to 4 network cards, this behavior indeed works through the UI, I do manage to launch a dl1.24xlarge instance with 4 EFA network cards.

### References

- [dl1.24xlarge supports 4 EFA network interfaces](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#network-cards)
- [Terraform `interface_type` key](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface#interface_type)

* #0000

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
