### ISSUE TITLE
GCP: Configuring stateful IP addresses in MIGs

### ISSUE THREAD

**Issue by ynrn** [hashicorp/terraform#30882]
Hi,

I contact you to know if the feature <Configuring stateful IP addresses in MIGs> is planned in the next versions.

### Current Terraform Version
Terraform 1.1.8

### Use-cases
Configuring stateful IP addresses for all VMs in a MIG is useful in the following scenarios:
- Your application requires an IP address to remain static after it has been assigned. But your application doesn't require assigning specific IP addresses to specific instances. IP addresses can be auto-assigned on instance creation.
- Your users, including other applications, access your servers through static IP addresses that you publish after deploying your application.
- You would like to benefit from instance autohealing and automated updates while preserving the static IP address that is auto-assigned on instance creation.

### Attempted Solutions
Add new parameters: 
--stateful-internal-ip to mark an internal IP address of a given network interface as stateful.
--stateful-external-ip to mark an external IP address of a given network interface as stateful.

### Proposal
For more details: https://cloud.google.com/compute/docs/instance-groups/configuring-stateful-ip-addresses-in-migs#configuring_stateful_ip_addresses_for_all_vms_in_a_group

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by ynrn** [comment]
Hi,
Thank you for your clarification.
I will do it.
Regards
