### ISSUE TITLE
User.Email field is empty in teamList response go SDK.

### ISSUE THREAD

**Issue by MytsYurii** [hashicorp/terraform#30893]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by apparentlymart** [comment]
Hi @MytsYurii!

It looks like you hit the submit button before entering any information to complete the issue template, so I'm going to close this. If you still want to report an issue, feel free to open a new one and answer the questions in the issue template before posting it. Thanks!
