### ISSUE TITLE
AWS CloudFront S3 Redirect Domain

### ISSUE THREAD

**Issue by subaquatic-pierre** [hashicorp/terraform#30898]
There is an error when creating AWS CloudFront distribution linked to AWS S3 bucket which is configured to redirect all requests.

The cloudfront does not point to the correct origin domain.

### Terraform Version

Terraform v1.1.8
on linux_amd64

### Terraform Configuration Files

This iis the part of the config with an error.

```hcl
resource "aws_cloudfront_distribution" "redirect" {
  origin {

    # ------- Error here ----------
    # 
    # Manual configuration in AWS console to this value works as expected
    # eg. DOC-EXAMPLE-BUCKET.s3-website-us-east-1.amazonaws.com
    # 
    # domain_name = aws_s3_bucket_website_configuration.redirect.website_endpoint
    # 
    # --------- Error here ----------

    domain_name = aws_s3_bucket.redirect.bucket_domain_name

    origin_id = local.s3_origin_id_redirect
```

github repo: https://github.com/subaquatic-pierre/pwa-infrastructure

### Expected Behavior

WWW cloudfront should redirect to root domain

### Actual Behavior

Receive access denied error.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by subaquatic-pierre** [comment]
Thanks for the direction James. Will check with AWS provider
