### ISSUE TITLE
terraform azure public IP shows incorrect zones

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform#30902]
I am not sure if this is a terraform or provider issue

```terraform 1.1.9```
```azure provider 3.2.0```

The following creates a public IP in North Europe.
Statefile shows Zone 1 as expected.
Azure Web UI shows Zone 1 as expected.

```
resource "azurerm_public_ip" "azurerm_public_ip" {
  name                = "test-ip"
  resource_group_name = "rg-vpn-dev"
  location            = "northeurope"
  allocation_method   = "Static"
  sku                 = "Standard"
  zones               = [1]
}
```

The following creates a public IP in North Europe.
Statefile shows Zone 1,2 as expected.
Azure Web UI shows Zone 1,2,3 - **NOT** expected.

```
resource "azurerm_public_ip" "azurerm_public_ip" {
  name                = "test-ip"
  resource_group_name = "rg-vpn-dev"
  location            = "northeurope"
  allocation_method   = "Static"
  sku                 = "Standard"
  zones               = [1, 2]
}
```

A subsequent apply wants to destroy the public IP resource and recreate

```
  # azurerm_public_ip.azurerm_public_ip must be replaced
-/+ resource "azurerm_public_ip" "azurerm_public_ip" {
      + fqdn                    = (known after apply)
      ~ id                      = "/subscriptions/[redacted]/resourceGroups/rg-vpn-dev/providers/Microsoft.Network/publicIPAddresses/test-ip" -> (known after apply)
      ~ ip_address              = "20.67.195.88" -> (known after apply)
      - ip_tags                 = {} -> null
        name                    = "test-ip"
      - tags                    = {} -> null
      ~ zones                   = [ # forces replacement
          - "3",
            # (2 unchanged elements hidden)
        ]
        # (7 unchanged attributes hidden)
    }
```

Running similar tests shows that selecting ONE zone or ALL zones (1,2,3) in the terraform code, works as expected.
Selecting just two zones out of the three available, causes the issue where Azure thinks all zones have been selected.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by scott-doyland-burrows** [comment]
I have opened https://github.com/hashicorp/terraform-provider-azurerm/issues/16470
