### ISSUE TITLE
tf destroy failed - no schema available for kubernetes_config_map_v1_data

### ISSUE THREAD

**Issue by dejan-subotic** [hashicorp/terraform#30908]
### Terraform Version

```
Terraform v1.1.7, Terraform v1.1.9
```

### Terraform Configuration Files

```terraform
resource "kubernetes_config_map_v1_data" "patch_argocd_configmap" {
  metadata {
    name      = "argocd-cm"
    namespace = "argocd"
  }
  data = {
    "url" = "XXX"
    "resource.customizations.health.bitnami.com_SealedSecret" = "  XXX"
    "dex.config" ="    XXX"
  }

  force = true
  depends_on = [XXX]
}
```

### Debug Output

```terraform
╷
│ Error: no schema available for kubernetes_config_map_v1_data.patch_argocd_configmap while reading state; this is a bug in Terraform and should be reported
│ 
│ 
╵
╷
│ Error: Missing resource schema from provider
│ 
│ No resource schema found for kubernetes_config_map_v1_data.
```

### Expected Behavior

Terraform destroy of the environment
### Actual Behavior

Destroy failed 
### Steps to Reproduce

Try to destroy the environment which has "kubernetes_config_map_v1_data" resource

**Comment by jbardin** [comment]
Hi @dejan-subotic,

Thanks for filing the issue. I'm not able to replicate the problem with the current provider release. The only situation I could see this happening is if the wrong provider version were used. Can you verify the provider versions required by the configuration, and that you are using the correct version of the provider during the destroy operation?

Thanks!

**Comment by dejan-subotic** [comment]
Hi James, thanks for the answer, the provider versions are correct. Same provider versions were used when resource was created as well when it was tried to be destroyed.

**Comment by jbardin** [comment]
Thanks @dejan-subotic,

Can you show the output of `terraform version` and `terraform providers`? If this is a small example with no sensitive credentials, would it be possible to supply the state file as well so we can try and replicate the error from that?

Thanks!

**Comment by dejan-subotic** [comment]
`$ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/azurerm] 2.99.0     
├── provider[registry.terraform.io/hashicorp/**kubernetes] 2.10.0**  
...
`

`$ terraform version
Terraform v1.1.9
on windows_386
+ provider registry.terraform.io/cloudflare/cloudflare v3.12.0
+ provider registry.terraform.io/hashicorp/azuread v2.20.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/helm v2.5.0
+ provider registry.terraform.io/hashicorp/**kubernetes v2.9.0`**


problem is obviously kubernetes v2.9.0, since this resource exist only in v2.10.0 - 
did init -upgrade and it solved the problem, thanks! and sorry for confusion :)
