### ISSUE TITLE
passing a tfvars file from the cli that is starting with a dot it will result in file not found.

### ISSUE THREAD

**Issue by Raffaello** [hashicorp/terraform#30903]
### Terraform Version

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.18.0
```

### Terraform Configuration Files

```terraform

```

### Expected Behavior

it should read the file for eg `.myvars.tfvars`
### Actual Behavior

```bash
│ Error: Failed to read variables file
│ 
│ Given variables file .myvars.tfvars does not exist.
```
### Additional Context

passing -var-file=`.myvars.tfvars` 

using `terragrunt` wrapper: `terragrunt plan -var-file=.myvars.tfvars` 

of course if replacing the `.` with `_` as eg, there is no issue present.
so for instance this command is working as expected: `terragrunt plan -var-file=_myvars.tfvars`

**Comment by crw** [comment]
I was unable to reproduce this on `Terraform v1.1.9 on darwin_arm64`. Can you please try running this command without using the terragrunt wrapper? It is possible this is a bug with terragrunt's parsing and passing of the command line arguments. Thanks!

**Comment by Raffaello** [comment]
> I was unable to reproduce this on `Terraform v1.1.9 on darwin_arm64`. Can you please try running this command without using the terragrunt wrapper? It is possible this is a bug with terragrunt's parsing and passing of the command line arguments. Thanks!

It could be, I thought that too, just because of the error message that is reporting the exact filename and working without starting with the dot. I though it could be more terraform related.

unfortunately i am not really able to run it without the wrapper, i might try to reproduce it in a sample project tomorrow.

**Comment by Raffaello** [comment]
I don't know why is happening, but it might be the case that the file on unix/linux is hidden and it is not found because excluded from the search?

**Comment by Raffaello** [comment]
@crw  I can confirm with a sample quick start test with both terragrunt and terraform, that terraform is working properly, so it is by exclusion on terragrunt.

**Comment by Raffaello** [comment]
for instance the error is Terragrunt not copy the hidden file into its working cache directory. So consequently Terraform reports file not found (of course) 🙂
