### ISSUE TITLE
apt-key deprecated, update docs for new location to store key

### ISSUE THREAD

**Issue by zesty** [hashicorp/terraform#30911]
On the website, Repository configuration should be updated from:

`curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -`

to:

`curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /etc/apt/trusted.gpg.d/hashicorp.asc`

or something similar.

The current version now gives an error when doing `apt update` in Ubuntu 22.04 LTS:

`W: https://apt.releases.hashicorp.com/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

relevant file: website/docs/cli/install/apt.mdx

**Comment by Naeim-Zarei** [comment]
Hi all, is this documentation change still needed? If so, I'm thinking up picking it up.

**Comment by L1ghtn1ng** [comment]
yes this is needed and had to fix this on my ubuntu 22.04 install and this works perfectly but I would also recommend that having that remove the key first first then re-add it in the correct place afterwards to 
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /etc/apt/trusted.gpg.d/hashicorp.asc

but you will want to do sudo apt-key del E8A032E094D8EB4EA189D270DA418C88A3219F7B first as mentioned to remove it from the old location

**Comment by nvnputta** [comment]
I Will Work on this and submit a PR later

**Comment by laurapacilio** [comment]
Hi All, I believe this community PR will solve this issue, let me know if folks have additional comments: https://github.com/hashicorp/terraform/pull/30956

**Comment by L1ghtn1ng** [comment]
The location of where to store the key file is wrong

**Comment by jfouquat** [comment]
```
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/apt_releases_hashicorp.gpg
sudo bash -c 'echo deb [arch=amd64 signed-by=/usr/share/keyrings/apt_releases_hashicorp.gpg] https://apt.releases.hashicorp.com/ $(lsb_release -cs) main >> /etc/apt/sources.list.d/terraform.list'
```
Just above, a draft, which works on my Ubuntu 22.04

**Comment by laurapacilio** [comment]
Hi All,

Apologies for the very long delay on this! Thank you @L1ghtn1ng - you're right. We still need to fix the location. I'm going to open a PR with this fix for the page, based on @jfouquat input. Thank you both! I'll post it here for review once I've tested it.

 I'm also going to alert others on my team, as I believe we'll need to also update the [Downloads page](https://www.terraform.io/downloads) and our getting started tutorials!

**Comment by robin-norwood** [comment]
With two commands, as the current docs have, I think the correct new version is:

```
wget --no-verbose --output-document=- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor --output=/usr/share/keyrings/hashicorp-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release --codename --short) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
```

1. I'm calling it the `hashicorp` keyring instead of `terraform`, since I believe we use it for all products now.
2. I used long argument names, per our style guide.

**Comment by laurapacilio** [comment]
Hi All! Thanks to @robin-norwood - we've updated the commands and merged a PR for the APT page. We're also working with web dev to get these commands updated on the Terraform Downloads page as well. 

Thanks again for calling this out!

**Comment by karlbateman** [comment]
Consider updating the article (https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository) too as this appears for search queries relating to the Hashicorp Linux repository.

**Comment by laurapacilio** [comment]
@karlbateman - Thank you! I will pass this along to the team responsible for these blogs. We appreciate you flagging this for us!
