### ISSUE TITLE
GP3 EBS Type by default [AWS provider]

### ISSUE THREAD

**Issue by mmi-fbx** [hashicorp/terraform#30928]
[AWS PROVIDER]
Is it possible to use GP3 EBS disk type by default instead of GP2 on every EC2 related deployment.

"[type] (Optional) The type of EBS volume. Can be standard, gp2, gp3, io1, io2, sc1 or st1 (Default: gp2)."

Use-cases
Actually GP3 is more efficent and costless than GP2. But we have to explicitly set to gp3 instead of default.

Attempted Solutions
empty

Proposal
Put GP3 by default storage option on every EC2 related deployment.

References

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
