### ISSUE TITLE
Failed to get existing workspaces error on azure devops pipeline

### ISSUE THREAD

**Issue by sathishneelam0322** [hashicorp/terraform#30926]
We're facing a continues build failures in azure devops, fail around 4/22 5:30 AM onwards, dry runs in staging passed but later on its started failing continuously with below error

Failed to get existing workspaces: Get https://xxx.blob.core.windows.net/xxxxx?comp=list&prefix=XXXXX-t12-xx-xx-XXXXXXtfstateenv%3A&restype=container: read tcp 10.1.0.42:52658->xx.xxx.xx.xxx:443: read: connection reset by peer�[0m

terraform version is 0.11.14
we tried updating azurerm version. But that didn't help

Please help us to resolve the issue asap

Thank you..

**Comment by crw** [comment]
Hello @sathishneelam0322,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
