### ISSUE TITLE
provider/aws: Add support for aws_route

### ISSUE THREAD

**Issue by failshell** [hashicorp/terraform#3093]
I need to dynamically add routes to an aws_route_table.

I have a module that configures our VPCs, in which the aws_route_table is. So I pass a list of subnets to it like so:

~~~ text
module "foo" {
[snip]
  custom_routes = "172.28.1.0/24,10.158.0.0/16"
}
~~~

And then, inside my module, I was hoping to use count to have all the routes generated in the aws_route_able:

~~~ text
[snip]

resource "aws_route_table" "default" {
  vpc_id = "${aws_vpc.standard.id}"
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.default.id}"
  }

  route {
    cidr_block = "${element(split(",", var.custom_routes), count.index)}"
    instance_id = "${var.vpn_instance}"
  }

  count = "${length(split(",", var.custom_routes))}"
  tags { Name = "${var.vpc_name}.droute" }
}

[snip]
~~~

Sadly, I get the following error during a 'terraform plan'

~~~ text
Error running plan: 16 error(s) occurred:

* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
* 1 error(s) occurred:

* Resource 'aws_route_table.default' does not have attribute 'id' for variable 'aws_route_table.default.id'
~~~

I could always use this instead in my module:

~~~ text
resource "aws_route_table" "default" {
  vpc_id = "${aws_vpc.standard.id}"
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.default.id}"
  }

  route {
    cidr_block = "${element(split(",", var.custom_routes), 0)}"
    instance_id = "${var.vpn_instance}"
  }

  route {
    cidr_block = "${element(split(",", var.custom_routes), 1)}"
    instance_id = "${var.vpn_instance}"
  }
  count = "${length(split(",", var.custom_routes))}"
  tags { Name = "${var.vpc_name}.droute" }
}
~~~

But that's very static and can't work with what I need to achieve.

Something like this https://www.terraform.io/docs/providers/aws/r/security_group_rule.html would be awesome to define routes inside an aws_route_table.

**Comment by radeksimko** [comment]
Since I think the solution/problem is in supporting single routes as a resource and not supporting count on subresource level, I renamed your issue. Otherwise :+1:

**Comment by nemski** [comment]
:+1:

**Comment by sairez** [comment]
+1 to this. Running in to a similar wall. Created a module to create spoke VPCs, connected to a central bastion VPC.  I'd like a way to add a route to the route tables in the bastion VPC from any spoke created so that traffic can flow between their peering connection.

**Comment by BSick7** [comment]
:+1:

**Comment by SpencerBrown** [comment]
Big :+1: 

Using Terraform to provision Kubernetes nodes. They need an AWS route table entry added each time a node is added, to support the "pod IP space" that is allocated for each node. The alternative is to use an overlay network like flannel that slows things down.

In particular I need to generate a list of aws_route resources, using a count "n" attribute, and then reference that list in an aws_route_table resource. Just like aws_security_group_rule is to aws_security_group.  

Until then it's "hey devops, please copy and paste this little section and manually increment these IP addresses thusly each time you add a node".

**Comment by steve-jansen** [comment]
:+1:  supporting route table entries as a standalone resource.

This appears to be supported by [`ec2.CreateRoute` in aws/aws-sdk-go](https://github.com/aws/aws-sdk-go/blob/7d9ac5f2079172b9725513796718eaad96218f3b/service/ec2/examples_test.go#L939-L948).

**Comment by BSick7** [comment]
I am currently trying to finish the unfinished implementation of this PR: https://github.com/hashicorp/terraform/pull/2454.

**Comment by steve-jansen** [comment]
FYI

See #3548, an update to #2454

**Comment by jen20** [comment]
This was added in #3548, so I'll go ahead and close this issue for now. Thanks for bringing it up!
