### ISSUE TITLE
TF state file corruption - character \u0000 has appeared

### ISSUE THREAD

**Issue by jamiet-msm** [hashicorp/terraform#30935]
### Terraform Version

v1.1.7

```
...
```

### Terraform Configuration Files

Unfortunately there's just far too much to provide I'm afraid. Our TF state file alone is >9MB

### Debug Output

```
Error loading state: 930 problems:

- Invalid character: This character is not used within the language.
- Invalid character: This character is not used within the language.
- Invalid character: Expected an attribute access or an index operator.
- Invalid character: This character is not used within the language.
- Invalid character: This character is not used within the language.
- Invalid character: Expected an attribute access or an index operator.
- Invalid character: This character is not used within the language.
- Invalid character: This character is not used within the language.
- Invalid character: Expected an attribute access or an index operator.
- Invalid character: This character is not used within the language.
- Invalid character: This character is not used within the language.
- etc
- etc
```

### Expected Behavior
TF state file should not have gotten corrupted

### Actual Behavior
terraform state file corruption during an apply caused the errors seen above that were returned on a the subsequent apply. The character `\u0000` appeared in the state file 620 times.

The corruption appears in the `dependencies` list of 310 resources. We managed to capture the before and after of the one of those dependencies lists (all 310 of them seem identical for a cursory glance). The dependencies list used to look like this:

```
          "dependencies": [
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.ACCOUNT_ID_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.AWIN_UNIQUE_REF_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.BRAZE_UNIQUE_REF_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.CLASSIFIED_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.CLICK_THROUGH_URL_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.CUSTOMER_CONTACT_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.CUSTOMER_DESCRIPTIVE_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.EMAIL_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.ENERGY_UNIQUE_REF_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.ENQUIRY_ID_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.EXTERNAL_UNIQUE_REF_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.IP_ADDRESS_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.MSM_DATA_KEY_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.PAGE_URL_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.PHONE_NUMBER_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.RED_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.UNCLASSIFIED_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.UNIQUE_IDENTIFIER_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.URL_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.USER_ID_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.VARIANT_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.VEHICLE_REGISTRATION_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_taxonomy.msm_colour_taxonomy_resource"
          ]
```

after the apply it looked like this, note the corrupted resource reference `module.PolicyTagMetadata.google_data_catalog_policy_tag.ENQUIRY_ID_policy_tag_resource`. Note also that it appears twice, once with the corruption and once without the corruption:

```
          "dependencies": [
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.ACCOUNT_ID_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.AWIN_UNIQUE_REF_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.BRAZE_UNIQUE_REF_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.CLASSIFIED_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.CLICK_THROUGH_URL_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.CUSTOMER_CONTACT_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.CUSTOMER_DESCRIPTIVE_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.EMAIL_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.ENERGY_UNIQUE_REF_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.ENQUIRY_ID_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.ENQUIRY_ID_policy_tag_resource\u0000\u0000ENQUI",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.EXTERNAL_UNIQUE_REF_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.IP_ADDRESS_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.MSM_DATA_KEY_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.PAGE_URL_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.PHONE_NUMBER_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.UNCLASSIFIED_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.UNIQUE_IDENTIFIER_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.URL_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.USER_ID_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.VARIANT_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_policy_tag.VEHICLE_REGISTRATION_policy_tag_resource",
            "module.PolicyTagMetadata.google_data_catalog_taxonomy.msm_colour_taxonomy_resource"
          ]
```

### Steps to Reproduce
Sorry, there's simply no way we could even begin to try and reproduce this. I'm filing this so that its captured should any other evidence ever come to pass and also just in case anyone reading this may be able to shed some light on it.

**Comment by jamiet-msm** [comment]
If this should be filed with the provider (https://github.com/hashicorp/terraform-provider-google) please let me know

**Comment by jbardin** [comment]
Hi @jamiet-msm,

Thanks for filing the issue! Having a corrupt value like that may indicate a data race, and the value is suspiciously in the same area as the panic being investigated in #30894. 

If it's at all possible, it would be very helpful to try and run `terraform plan` on your configuration with a build of Terraform with the race-detector enabled. If you have the go1.18 toolchain installed, you can use `go build -race` from the root of the Terraform repository to get a new binary with the race detector. Even if the corruption doesn't happen again, running a similar plan can show some useful information if a data race can be triggered.

Thanks!

**Comment by jamiet-msm** [comment]
Hi @jbardin ,
I've never done one iota of Go programming in my life so don't have the toolchain that you mentioned installed anywhere, but first time for everything I suppose. Will see what I can do.

By "data race" do you mean "race condition"?

**Comment by jbardin** [comment]
Give it a go! Any help tracking this down is appreciated :D
Since you only need to build an existing project there hopefully won't be much to setup. You can get Go from https://go.dev/doc/install (homebrew also works well on MacOS). Once it's installed you should be able to clone the terraform repo and run `go build -race` from the root of the repository, which will be the `main` branch by default.

Yes, by "data race" I mean a race condition where there are concurrent writes or read+write at a specific memory location (as opposed to a "logical race" resulting in an unexpected order of operations). This is only a hunch here so far, but there's not much else that could explain the linked crash or corrupted strings.

**Comment by jamiet-msm** [comment]
Apologies but you might need to walk me through this. I've followed those steps and I now have a terraform binary, though it claims to be old:

```shell
➜ terraform --version
Terraform v0.14.9

Your version of Terraform is out of date! The latest version
is 1.1.9. You can update by downloading from https://www.terraform.io/downloads.html
```

I assume I can just ignore this.

I assume it is now simply a case of replacing my terraform binary with this one?

**Comment by jbardin** [comment]
Yeah, there could be considerable overhead with the race detector. What we're looking for is if there is a race detected, you will see `WARNING: DATA RACE` with a stack trace and the race locations.

**Comment by jamiet-msm** [comment]
ok, I'll look out for that.

Ignore the message I put up about it taking in excess of 9 minutes to read a data source (I've since deleted that message). It was user error. https://www.urbandictionary.com/define.php?term=PEBCAK

**Comment by jbardin** [comment]
Another note, if you get a negative result here and have time, you could build the same thing from the v1.1 branch. That would let us confirm if the problem was fixed in development already.

**Comment by jamiet-msm** [comment]
OK, I ran a plan and then searched the output for "WARNING"...it didn't find that string.

Oh well, was worth a try.

**Comment by jbardin** [comment]
Thank OK, thanks for following up! 
Since this is unlikely to manifest again in the same manner, and there's no information to go by here, I'm going to close the issue for for now. Any users with something similar are encouraged to file a new issue with as much information as possible while we continue to investigate.

Thanks!
