### ISSUE TITLE
Private endpoint is going to recreate in every run of terraform apply.

### ISSUE THREAD

**Issue by dev-shubhamverma990** [hashicorp/terraform#30941]
### Terraform Version

```
PS C:\Users\r.ai.jain\Documents\ACI-BITB68> terraform version
Terraform v1.1.9
on windows_386
...
```

### Terraform Configuration Files

```

...
```

### Expected Behavior

I have deployed one keyvault & storage with private endpoint using 'terraform apply' command and if we run the "terraform apply" again then it should not be recreate again, no changes should come

### Actual Behavior

I have deployed one keyvault & storage with private endpoint using 'terraform apply' command and if we run the "terraform apply" again then it is going to **“recreation(delete and create) and also addition”** again, i checked the statefile , there is no entry of private endpoint. How is possible that all resources are coming in statefile but private endpoint not while in the first run private endpoint has been created by terraform.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

**Comment by crw** [comment]
Hi @dev-shubhamverma990, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
