### ISSUE TITLE
Terraform Crash during Terraform Init

### ISSUE THREAD

**Issue by jaszczykwojciech** [hashicorp/terraform#30940]
### Terraform Version

```
1.1.9
```

### Terraform Configuration Files

```
Cannot share the whole configuration - we are using the AzureRM provider v 2.99 and Gitlab environment.
```

### Debug Output

```
Initializing modules...
- crm in crm
- database in database
- general in general
- sync360 in sync360
Initializing the backend...
Successfully configured the backend "http"! Terraform will automatically
use this backend unless the backend configuration changes.
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
called IsLegacy() on zero-value addrs.Provider
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x154
panic({0x1eea1a0, 0x28982f0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/hashicorp/terraform/internal/addrs.Provider.IsLegacy(...)
	/home/circleci/project/project/internal/addrs/provider.go:204
github.com/hashicorp/terraform/internal/command.(*InitCommand).getProviders(0xc00036d[86](https://gitlab.com/CMSLegalServicesEEIG/blueboxazure/-/jobs/2381781768#L86)0, 0x2381bf0, 0xc0000e6048, 0x0, {0x0, 0x244461e, 0x0}, {0x0, 0x0})
	/home/circleci/project/project/internal/command/init.go:504 +0x159b
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc00036d860, {0xc00015e020, 0x10, 0x1e})
	/home/circleci/project/project/internal/command/init.go:303 +0x166d
github.com/mitchellh/cli.(*CLI).Run(0xc0007e6640)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.realMain()
	/home/circleci/project/project/main.go:309 +0x1509
main.main()
	/home/circleci/project/project/main.go:58 +0x19
```

### Expected Behavior

The Terraform init command should finish correctly

### Actual Behavior

It gets crash and cannot be initialised.

### Steps to Reproduce

1. Prepare infrastructure in the azure using the Terraform
2. Deploy infrastructure
3. Try to import resource group: prepare empty resource in .tf file and in the CI pipeline run **terraform import** command
4. The Initialisation went wrong. 

### Additional Context

The behaviour appeared when I wanted to import the existing resource group in the Azure. I'm not sure how it combines, but the crash happen before the command **terraform import**. I've got another TF project in the same repository but in different folder and this one runs correctly using the same configuration.

**Comment by jbardin** [comment]
Hi @jaszczykwojciech,

Thanks for filing the issue! In oder to debug the problem it would be helpful to have the configuration which supplied the unexpected value causing the crash. Would it possible to create a minimal reproducible example from your configuration?
Can you supply the output of `terraform providers`, or the the trace logs from the `init` process?

Thanks!

**Comment by jbardin** [comment]
Hello,

Since we have not heard back with a reproduction, I'm going to close this out. If you can provide the requested information, please feel free to open a new issue.

Thanks!
