### ISSUE TITLE
!!!! TERRAFORM CRASH !!!!

### ISSUE THREAD

**Issue by maheshbthapa** [hashicorp/terraform#30952]
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```
Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Canceled desc = context canceled

Error: rpc error: code = Unavailable desc = transport is closing
.......

```
## Additional error messages
```


╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

```

## Version: 2.93.1

I am getting this on `terrafrom plan`. It was working and suddenly started with this error. I have tried other versions as well. I have not tried versions 3 and latest since there are some deprecated code to be fixed before upgrade to latest.

**Comment by kmoe** [comment]
Thanks for the bug report.

It would be helpful if you could fill in the rest of the [issue template](https://raw.githubusercontent.com/hashicorp/terraform/main/.github/ISSUE_TEMPLATE/bug_report.md) so we have a chance at reproducing this issue.

Please double-check your Terraform version using the output of `terraform version`, as v2.93.1 is not a valid version.

**Comment by maheshbthapa** [comment]
Sorry. The version I mentioned was of the provider hashicorp/azurerm. My local system has version 0.14.7. 



### Terraform Version


```
0.14.7
```

### Terraform Configuration Files


```terraform
terraform {
 required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 2.93.1"
    }
  }
}
```

### Debug Output

Error: The terraform-provider-azurerm_v2.93.1_x5 plugin crashed!

### Expected Behavior

Terraform plan should work

### Actual Behavior


### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context


### References

**Comment by jbardin** [comment]
Hi @maheshbthapa,

The output indicates the provider plugin crashed, which should be reported to the azure provider. I would make sure to try and replicate this with the latest 2.x release (2.99.0 currently) to make sure it's not already fixed, and supply the configuration and stack trace from the error output.

Thanks!
