### ISSUE TITLE
crash when associate EIP provider and incorrect syntax aws

### ISSUE THREAD

**Issue by brezmes** [hashicorp/terraform#3095]
Terraform v0.6.3

Crash when there is an invalid syntax.

> 2015/08/28 12:02:12 terraform-provider-aws: panic: Error reading level config: strconv.ParseBool: parsing "${aws_vpc.vpc_docverif.id}": invalid syntax

**Comment by radeksimko** [comment]
Hi @brezmes 
would you mind attaching a minimal repro case for this?

**Comment by brezmes** [comment]
Sorry. I was trying to do this:

resource "aws_eip" "front" {
  vpc = "${aws_vpc.vpc_docverif.id}"
  instance = "${aws_instance.app.id}"
}

I was wrong about the type parameter vpc, because you can only assign a boolean. I changed it and it works.

I don't have the log file, but I can recreate it.

**Comment by mitchellh** [comment]
I can no longer reproduce this. Given it has been almost a year I'm just going to assume it has been fixed. If you can still reproduce this please let us know by opening a new issue with a repro case. Thanks!
