### ISSUE TITLE
Terraform aws_emr_cluster does not have support for ec2 placement group 

### ISSUE THREAD

**Issue by gwsu2008** [hashicorp/terraform#30966]
### Current Terraform Version
Terraform v1.1.6

### Use-cases
In the AWS CLI to create an EMR cluster, there's an additional option to set EC2 placement group configuration 
`--placement-group-configs InstanceRole=MASTER,PlacementStrategy=SPREAD`
I don't find such an option in the aws_emr_cluster resource.  Using EC2 placement group is recommended for EMR HA from AWS.

https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-ha-placementgroup.html

### Attempted Solutions
No workaround solution

### Proposal
N/A

### References
N/A

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
