### ISSUE TITLE
Terraform run has started failing inconsistently in "data external", after an upgrade

### ISSUE THREAD

**Issue by sksumit1** [hashicorp/terraform#30964]
We recently upgraded to terraform 1.0.0. We were at 0.13.0 for a long time.
While the upgrade went fine, a recent change was done in one of the ec2 wrapper module (totally unrelated to "data external")

That external script for us is used to determine the selected ip addresses (based on our own criterias ) to use while launching ec2 instances in for_each blocks. While the upgrade went fine for most of the instance sets (lets say A, B, C), while upgrading certain other instance sets (e.g. D), terraform started complaining about _"The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply"_ for A & B.

Reverting the module versions of D or even A,B,C,D doesn't solve the problem. The response is inconsistent

```
│ Error: Invalid for_each argument
│
│   on .terraform/modules/A/main.tf line 47, in resource "aws_instance" "this":
│   47:   for_each = (var.number_of_instances > 0 && local.keys_rotation_enabled) ? module.common.filtered_iprange_output : toset([])
│     ├────────────────
│     │ local.keys_rotation_enabled is true
│     │ module.common.filtered_iprange_output is a list of string, known only after apply
│     │ var.number_of_instances is 4
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.
```

module.common.filtered_iprange_output is just a local variable in the common module that is split(",",data.external.cidr_expander.result.filtered_iprange)

However i do query the state file, that the data external is already calculated

```
$ terraform state show module.A.module.common.data.external.cidr_expander

 module.A.module.common.data.external.cidr_expander:
data "external" "cidr_expander" {
    id      = "-"
    program = [
        "python",
        ".terraform/modules/A.common/scripts/myfunction.py",
    ]
    query   = {
        "blacklisted_ips" = jsonencode([])
        "cidr_blocks"     = jsonencode(
            [
                "10.93.81.111",
                "10.93.81.112",
                "10.93.81.113",
                "10.93.81.114",
                "10.93.81.115",
            ]
        )
        "offset"          = "0"
        "range_hop"       = "1"
    }
    result  = {
        "filtered_iprange" = "['10.93.81.111', '10.93.81.112', '10.93.81.113', '10.93.81.114', '10.93.81.115']"
    }
}
```
I am not sure what behaviour has changed in terraform 1.0.0 from 0.13
Terraform should know the output of module.common.filtered_iprange_output even in the plan phase.
There have been lot of requests that have requested not to run data resources in the plan phase or either to simply refresh it.
I am not sure if any change was done around these that is causing side effects for me.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

In your case a minimal complete example would definitely help troubleshoot the problem. You need to look for a reason the data source could not be read, most likely a dependency is unknown during the plan or the data source's configuration is not fully known. The documentation about data sources, their behavior and how dependencies are handled will may help: https://www.terraform.io/language/data-sources


Thanks!

**Comment by sksumit1** [comment]
Its odd also as when removing problematic A & B, terraform does say that it wants to read "data" "external" for some modules during the apply phase. It looks unnecessary as the "data" "external" can be calculated in the plan phase itself

`
  # module.C.module.common.data.external.cidr_expander will be read during apply
  # (config refers to values not yet known)
 <= data "external" "cidr_expander"  {
      + id      = (known after apply)
      + program = [
          + "python",
          + ".terraform/modules/C.common/scripts/myfuction.py",
        ]
      + query   = {
          + "blacklisted_ips" = jsonencode([])
          + "cidr_blocks"     = jsonencode([])
          + "offset"          = "0"
          + "range_hop"       = "1"
        }
      + result  = (known after apply)
    }`

**Comment by crw** [comment]
Hi @sksumit1, thanks for the question! @apparentlymart and the rest of our community will be available to provide further support in [the community forum](https://discuss.hashicorp.com/c/terraform-core). I would not expect further updates on this issue thread. Thanks again, we do appreciate your question!

**Comment by sksumit1** [comment]
Anybody looking for the update on how its resolved. Please check https://discuss.hashicorp.com/t/terraform-doesnt-execute-data-external-in-plan-phase/38882
Thanks @jbardin
