### ISSUE TITLE
Azure provider: Resources to create application credentials and service principals

### ISSUE THREAD

**Issue by keymon** [hashicorp/terraform#3096]
[Azure BOSH CPI](https://github.com/Azure/bosh-azure-cpi-release/blob/master/docs/template-guide.md#132---creating-an-aad-application) requires [application credentials and service principals](https://azure.microsoft.com/en-us/documentation/articles/active-directory-application-objects/) to add resources to azure.

But Terraform does not provide a way to:
- Create Azure Applications
- Create a Service Principals
- Assign roles to applications

To understand how this should work refer to this script in our project [`azure-create-service-principal.sh`](https://github.com/alphagov/cf-terraform/blob/feature/101030380_bosh_on_azure/azure/azure-create-service-principal.sh), which we call before running terraform to create the required resources.

**Comment by aznashwan** [comment]
@keymon: sadly, the same story as with https://github.com/hashicorp/terraform/issues/3097 and all other seemingly missing resource support issues that were raised.
Again; do feel free to add any more requests/suggestions for the ARM switch here: https://github.com/hashicorp/terraform/issues/3212
