### ISSUE TITLE
Azure provider: Terraform resource to create a "azure resource group" and ability to specify it in all resources

### ISSUE THREAD

**Issue by keymon** [hashicorp/terraform#3097]
There is not a explicit way to create a [azure resource group](https://azure.microsoft.com/en-gb/documentation/articles/resource-group-portal/) in terraform (to create it by command line: `azure config mode arm && azure group create <name> <location>)

If I am not wrong, it seems that the terraform resource  [`azure_hosted_service`](https://terraform.io/docs/providers/azure/r/hosted_service.html) creates the group as a collateral effect. 

Then, it would be desirable if every azure resource (instances, networks, etc.) allows specify which azure resource group is should be part. This would allow terraform integrate nicely with other provisioners, like [BOSH CPI](https://github.com/Azure/bosh_azure_cpi). 

Related issue for network: #3089

**Comment by aznashwan** [comment]
@keymon: resource groups are a feature inherent to Azure's ARM API.
Unfortunately; at the time we implemented the Azure provider; we only had bindings available for the old ASM API's in the go sdk.

Plans to add support for using ARM API's as well have started to crystallize; and that should open an enormous amount of new resource types we can deploy (including resource groups).
For the latest status and/or suggestions on the transition; please refer to https://github.com/hashicorp/terraform/issues/3212

**Comment by stack72** [comment]
Closing this as well `azurerm_resource_group` :)
