### ISSUE TITLE
No clean way to create vsphere directory structure when it partially exists

### ISSUE THREAD

**Issue by edqallen** [hashicorp/terraform#30977]
The vsphere provider allows the usage of a `folder` option in a `resource` block and `terraform plan` will succeed regardless of the status of the directory structure in the resource.  However `terraform apply` will fail if the entire specified directory does not exist.  To address this, you are meant to use the `vsphere_folder` resource, which creates directories if they do not exist.  Unfortunately this resource will cause `terraform apply` to fail if the directory *does* already exist.

This combination of behaviors is problematic in a use case where you simply want terraform to create the directories if they don't already exist, but use them if they do exist.  I realize this may be counter to how terraform is *intended* to be used, but that doesn't mean that this less perfect but still real-world scenario shouldn't be supported.

I am unsure of what the best approach to implementation would be, perhaps something like an `ignoreIfExists` flag in the `vsphere_folder` resource, or alternatively, a way to tell terraform to continue even if creation of that `vsphere_folder` resource fails (because it already exists).

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
