### ISSUE TITLE
Azure provider: Resource to create an azure storage account

### ISSUE THREAD

**Issue by keymon** [hashicorp/terraform#3098]
[Azure BOSH CPI](https://github.com/Azure/bosh_azure_cpi) requires a [azure storage account and credentials](https://azure.microsoft.com/en-gb/documentation/articles/storage-create-storage-account/). 

But there is no way to create this resource group in terraform.

In our project, to workaround this we created this script which you can refer for details [`azure-create-storage-service.sh`](https://github.com/alphagov/cf-terraform/blob/feature/101030380_bosh_on_azure/azure/azure-create-storage-service.sh)

This script implements the desired features in a terraform resource: 
 * create the account: `azure resource create ...`
 * query the keys: `azure storage account keys`

**Comment by aznashwan** [comment]
@keymon: Support for storage services was added back in June: https://github.com/hashicorp/terraform/commit/9670e6961328dfb927f48a103eadb05717586b3f
Considering the age of the issue; I presume that the [documentation](https://terraform.io/docs/providers/azure/r/storage_service.html) on the site had not had the chance to get updated at that time...

PS: sorry; was a bad initiative on my part to call it a `storage_service` in Terraform. Hope it's not too confusing...

**Comment by stack72** [comment]
Closing this as this is implemented for both ARM and ASM
