### ISSUE TITLE
openstack plugin crashed 

### ISSUE THREAD

**Issue by Richardswe** [hashicorp/terraform#30996]
Hi the plugin crashed for me as i was developing. I've been working on to create a network and a k8s cluster on openstack but now i got this. 

Error: Plugin did not respond
│ 
│   with openstack_containerinfra_cluster_v1.k8s-2,
│   on binero.k8s-cluster.tf line 60, in resource "openstack_containerinfra_cluster_v1" "k8s-2":
│   60:  resource "openstack_containerinfra_cluster_v1" "k8s-2" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs
│ may contain more details.
╵

Stack trace from the terraform-provider-openstack_v1.46.0 plugin:

panic: interface conversion: interface {} is map[string]interface {}, not map[string]string

goroutine 117 [running]:
github.com/terraform-provider-openstack/terraform-provider-openstack/openstack.flattenContainerInfraV1Kubeconfig(0xc0006f2600, 0xf21b6d)
	github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/containerinfra_shared_v1.go:175 +0xcd4
github.com/terraform-provider-openstack/terraform-provider-openstack/openstack.resourceContainerInfraClusterV1Read({0x1083d78, 0xc00022b400}, 0xc0006f2600, {0xef07e0, 0xc000619680})
	github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_containerinfra_cluster_v1.go:351 +0x937
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000486000, {0x1083d78, 0xc00022b400}, 0x24, {0xef07e0, 0xc000619680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000486000, {0x1083d78, 0xc00022b400}, 0xc0004d29c0, {0xef07e0, 0xc000619680})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c828, {0x1083d78, 0xc00022b400}, 0xc00022b480)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000290200, {0x1083e20, 0xc00040b830}, 0xc000280ea0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xed1c60, 0xc000290200}, {0x1083e20, 0xc00040b830}, 0xc000280e40, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001bcc40, {0x1093e78, 0xc000122780}, 0xc000188100, 0xc000282e70, 0x16fa8d0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0001bcc40, {0x1093e78, 0xc000122780}, 0xc000188100, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-openstack_v1.46.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
