### ISSUE TITLE
Azure provider: Resource to upload ssh keys or certificates to azure

### ISSUE THREAD

**Issue by keymon** [hashicorp/terraform#3099]
[When creating an azure instance in terraform](https://terraform.io/docs/providers/azure/r/instance.html) we can pass either a password or a SSH thumbprint. 

This SSH thumbprint comes from a SSH key uploaded to the same `azure_hosted_service` defined in the instance, and uploaded using a method [like this]([https://media-glass.es/2015/07/22/adding-a-ssh-key-to-azure/]%28https://media-glass.es/2015/07/22/adding-a-ssh-key-to-azure/%29). 

But terraform does not provide any way to upload the ssh key.  Could be nice if terraform provides a resource to generate and upload the certificate and query the SSH thumbprint.

In our project we implemented this feature in a script [like in this commit](https://github.com/alphagov/cf-terraform/commit/71b18939ee0d49ac78f06e56b7d5552b5d94a806), which you can use as reference.

**Comment by aznashwan** [comment]
@keymon: again; there was no way to add a key to instance through the ASM API directly back when it was written. What actually happens here is that the thumbprint you provide is added to the `azure_hosted_service` containing the instance (that was simply how the ASM API works...).

The upcoming ARM implementation makes managing keys per instance much more easy.
Updates and/or further suggestions here: https://github.com/hashicorp/terraform/issues/3212

**Comment by chan-alex** [comment]
The problem is ARM is nice but for many, ASM will have to be support for *years* to come.
