### ISSUE TITLE
AWS Lambda Config & Code apply not atomic causing errors on high availability system

### ISSUE THREAD

**Issue by nomad3k** [hashicorp/terraform#30994]
We recently saw a number of 500 errors on our live AWS server-less API.  This particular API endpoint receives around 3.2M hits per week, as part of a critical national project in the UK.  I won't name the project, but if this API went down it would make headline news on the BBC.  Therefore we're very sensitive to issues.

During the minute of deployment we saw 840 requests and 495 errors, which is a failure rate of nearly 3 in 5 requests (58.9%).  After the deployment everything was fine again.

During the deployment we deleted a single environment variable and replaced it with multiple new ones.  The errors we saw in the log related the the deleted environment variable being empty.

The hypothesis we formed is that, for a moment during the deployment, the old code ran with the new environment variables.  We believe this is caused by terraform code and environment variables not being applied in a single transaction, but two.  This leaves a brief moment where code and config are out of step.  On our API this was enough time for a 58.9% failure rate.

We're mitigating this in future by not deploying code & config in the same release.

### Terraform Version
```
1.1.7
```

### Terraform Configuration Files
Our code uses a module, which references the environment variables and code in the same single block.
```terraform
resource "aws_lambda_function" "lambda" {
  filename                       = var.filename
  function_name                  = var.function_name
  role                           = aws_iam_role.lambda.arn
  handler                        = "index.handler"
  runtime                        = var.runtime
  publish                        = true
  source_code_hash               = filebase64sha256(var.filename)
  memory_size                    = var.memory_size
  timeout                        = var.timeout
  reserved_concurrent_executions = var.reserved_concurrent_executions
  environment {
    variables = var.environment_variables
  }

  depends_on = [aws_cloudwatch_log_group.lambda]
}
```

### Debug Output
Not available as it only occurs during deployment onto a high traffic API.

### Expected Behavior
Old Code should run Old Environment Variables
New Code should run New Environment Variables

### Actual Behavior
Old Code ran using New Environment Variables

### Steps to Reproduce
Need to have requests being executed against lambda during the deploy.

### Additional Context
This was running on a Lambda that receives 3.2M hits a week, and caused a 58.9% failure rate.  For comparison, our normal operating error rate is 0.00068%

### References
n/a

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by nomad3k** [comment]
Thanks for the clarification.
