### ISSUE TITLE
Azure provider: Resource to reserve public IPs on Azure

### ISSUE THREAD

**Issue by keymon** [hashicorp/terraform#3101]
But terraform does not provide a explicit way to allocate IPs (only by creating public endpoints in one instance).

IPs can be allocated and queried by the `azure-cli` with:

```
azure config mode arm
azure resource create \
     ${resource_group_name} \
     ${ip_name} \
     Microsoft.Network/publicIPAddresses \
     "West Europe" 2015-05-01-preview \
     -p "{\"publicIPAllocationMethod\":\"static\"}"


azure resource show \
     ${resource_group_name} \
     ${ip_name} \
     Microsoft.Network/publicIPAddresses \
     2015-05-01-preview 
```

A terraform resource would reserve the ip and provide a way to query it.

In our project we used the script [`azure-create-public-ip.sh`](https://github.com/alphagov/cf-terraform/blob/feature/101030380_bosh_on_azure/azure/azure-create-public-ip.sh), which you can check as reference.

**Comment by aznashwan** [comment]
@keymon: same ASM vs. ARM story. Varying PublicIP allocation methods are pretty much exclusively available using the new ARM API's.

Do please refer to the raised issue on the matter for further updates/requests: https://github.com/hashicorp/terraform/issues/3212

**Comment by stack72** [comment]
Hi @keymon 

I am going to close this out - this is available via `azurerm_public_ip` :)

Paul
