### ISSUE TITLE
Task in VSTS pipeline not work for terraform install

### ISSUE THREAD

**Issue by JerryWang20** [hashicorp/terraform#31024]
Suddenly, the url of "https://releases.hashicorp.com/terraform/" does not return the value which cause install terraform in the pipeline to be fail

error trace as :

##[debug]Env:INPUT_VERSION: '0.14.9'
##[debug]**GET https://releases.hashicorp.com/terraform/ with 0-byte payload**
##[debug]received -1-byte response of content type text/html
##[debug]Caught exception from task script.

**Comment by alisdair** [comment]
I'm unable to reproduce this issue. There was a maintenance window for the releases site yesterday during which this error may have been occurring, but it now has been resolved.

I believe this should be fixed, so I'm going to close this issue, but if you have steps which still reproduce the problem please let us know.

**Comment by alisdair** [comment]
I don't believe there have been any such changes, no. Here's a sample response from the URL, which is working for me:

```
HTTP/2 200 
content-type: text/html
x-api-version: 0.1.0
x-request-id: 581de00b-9367-f17a-91fe-16778876cce4
x-amz-cf-pop: YTO50-P2
x-amz-cf-id: XvCjbpAFj2ABI4GMZQ5fWVrDgDpWU6UKajv4kOMbYyMSeWh36PPsSA==
age: 70192
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: sameorigin
accept-ranges: bytes
date: Tue, 10 May 2022 14:37:38 GMT
vary: Origin, Accept-Encoding
```

Can you provide any more details on the error you're seeing or how to reproduce it?

**Comment by JerryWang20** [comment]
Previous correct log return the value as 
##[debug]GET https://releases.hashicorp.com/terraform/ with 0-byte payload
##[debug]received 17530-byte response of content type text/html

But now the error log return the value as 

##[debug]GET https://releases.hashicorp.com/terraform/ with 0-byte payload
##[debug]received -1-byte response of content type text/html

You will find that the error one just return -1-byte

**Comment by JerryWang20** [comment]
And whether the format of release page changed from <a href="**/terraform/0.1.0/**">terraform_0.1.0</a> to <a href="**/terraform/0.1.0**">terraform_0.1.0</a>

**Comment by alisdair** [comment]
That's correct, the HTML directory listing format has changed slightly. This HTML is not a supported interface and we make no compatibility promises about it, so we'd consider this a bug in the VSTS plugin. I'd recommend [reporting a bug in that plugin](https://github.com/XpiritBV/Xpirit-Vsts-Release-Terraform).

There is now an [official HashiCorp releases API](https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api), which is how we'd recommend integrating with the releases website. [More API details here](https://releases.hashicorp.com/docs/api/v1/).

This doesn't represent a bug in Terraform, so I'm going to close this out for now. Thanks again for reporting it!
