### ISSUE TITLE
Provide arm64 version of docker images

### ISSUE THREAD

**Issue by kinghrothgar** [hashicorp/terraform#31036]
With the growing prevalence of M1 Macbooks, I imagine that the number of terraform users working on arm64 is rapidly increasing. It would be nice if arm64 versions of the docker images were provided. I tried to find the CI code that currently builds the docker images and could not. If that is publicly available, I am willing to submit a PR to support this.

I verified that building the Dockerfile on arm64 works, so this is should be purely a CI change.

**Comment by apparentlymart** [comment]
Hi @kinghrothgar! Thanks for this feature request.

We're already tracking a more general version of this request over in #25571, so I'm going to close this just to consolidate the discussion over there. I don't have any new updates to share at this time, but we'll post over there if the situation changes. Thanks again!

**Comment by kinghrothgar** [comment]
I tried to search for that but couldn't find anything, arm64 was just too broad of a search. Thanks for pointing me to the issue.
