### ISSUE TITLE
terraform import misleading docs

### ISSUE THREAD

**Issue by wojcikm** [hashicorp/terraform#31031]
**[Documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_metric#import) states:**

```
$ terraform import google_logging_metric.default {{project}} {{name}}
$ terraform import google_logging_metric.default {{name}}
```

Both commands failed, below command works (notice `"`):

```
$ terraform import google_logging_metric.default "{{project}} {{name}}"
```

Suggested update - add above line to dosc. I have wasted a lot of time debugging it... and errors was also very misleading, eg:
```
Error: project: required field is not set
OR
Error: Cannot import non-existent remote object
```

**Similar situation with [alert policies](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#import):**

Docs:
```
$ terraform import google_monitoring_alert_policy.default {{name}}
```

What actually worked:
```
$ terraform import google_monitoring_alert_policy.default "{{project}} projects/{{project}}/alertPolicies/{{POLICY ID - NOT NAME (SIC!)}}"
```

_hashicorp/google v4.19.0...
hashicorp/google-beta v4.19.0...
image hashicorp/terraform:1.1.9_

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
