### ISSUE TITLE
Consul 'access_token' difference between code and docs.

### ISSUE THREAD

**Issue by AwaNoodle** [hashicorp/terraform#3103]
The documentation has the Consul variable for ACLs as **access-token**. The code has it as **access_token**. I've created a PR with the docs updated: https://github.com/hashicorp/terraform/pull/3102

- Current Documentation - http://www.terraform.io/docs/commands/remote-config.html
- Current Code - https://github.com/hashicorp/terraform/blob/4052be6c7aefb73f65c088791c997aef43ce56fc/state/remote/consul.go

**Comment by radeksimko** [comment]
https://github.com/hashicorp/terraform/pull/3102 merged.
