### ISSUE TITLE
Terraform test reports success when tests were skipped

### ISSUE THREAD

**Issue by tata2000** [hashicorp/terraform#31038]
terraform test reports success when tests were skipped without notifying about that the user.
This is only seen in the logs and -junit-xml file

This situation can be reproduced with a read-only user. 

When creation of the resources in modules does not succeed all the tests are skipped (even tests such as "x"=="y") and success is reported to the end-user. 

repo with example here:
github.com:tata2000/terraform_test_bugrepor

**Comment by crw** [comment]
Thanks for the report, @tata2000!
