### ISSUE TITLE
Migrating from Terraform Cloud to local state fails

### ISSUE THREAD

**Issue by KarlNord** [hashicorp/terraform#31042]
I emoved the following from main.tf and ran terraform init again.

  cloud {
    organization = "psu-infra-ai-app-platforms"
    workspaces {
      name = "Example-Workspace"
    }
  }

The following is displayed.

Initializing the backend...
Migrating from Terraform Cloud to local state.
╷
│ Error: Migrating state from Terraform Cloud to another backend is not yet implemented.
│ 
│ Please use the API to do this: https://www.terraform.io/docs/cloud/api/state-versions.html

$ terraform version
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.75.1

Ubuntu 20.04.4

**Comment by crw** [comment]
Hi @KarlNord, we use GithHub issues to manage bug report and feature requests, and use [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) to manage these types of usage questions. Please repost this in our discussion forums, where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

By the way, a quick google search turned up a few blog posts on this topic. I cannot recommend any of them directly, as I cannot vouch for their content, but just to mention there does seem to be existing material out there. 

Thanks!
