### ISSUE TITLE
Terraform Version 12.31

### ISSUE THREAD

**Issue by NikhilSardana18** [hashicorp/terraform#31054]
<!--
Hi there,
I have recently upgraded my terraform from 11.15-12.31 and made these changes.
![Capture2](https://user-images.githubusercontent.com/96880270/168596848-d47a1e12-e62c-499b-9a8d-9d1b096708b8.PNG)

 but after doing that when i try to get my passwords I'm stuck with this error.

![Capture3](https://user-images.githubusercontent.com/96880270/168596872-c8f7518b-4a46-4557-aeea-ffc9d2c1c8d3.PNG)

**Comment by NikhilSardana18** [comment]
After upgrading the terraform 12.31 from 11.15 and makiing changes to the file
![Capture2](https://user-images.githubusercontent.com/96880270/168597306-8b0a7d40-1837-4cda-98f8-953724989560.PNG)
.

I'm getting this error when i try to retrieve my passwords 
![Capture3](https://user-images.githubusercontent.com/96880270/168597473-2cee1060-3400-48d2-b30e-b8681293a930.PNG)

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
