### ISSUE TITLE
Wondering if it is possible to use multiple providers within single resource or module in latest terraform versions

### ISSUE THREAD

**Issue by imtaji** [hashicorp/terraform#31055]
### Current Terraform Version

```
➤ terraform version
Terraform v1.1.9
on darwin_amd64
```

I know this was not possible for such a long time but, is somebody able to find the hack around terraform providers?

Pseudocode:

```
resource "aws_iam_account_password_policy" "primary" {
  providers = [aws.account1, aws.account2]

  minimum_password_length      = 14
  max_password_age             = 60
  require_lowercase_characters = true
  require_numbers              = true
  require_uppercase_characters = true
  password_reuse_prevention    = 4
}
```
This is so basic thing a programmer expects from terraform. But not sure why this is never considered by terraform. Does anyone know the reason?

Also, as per their documentation, this looks quite possible in modules https://www.terraform.io/language/modules/develop/providers#implicit-provider-inheritance

but not working for me though.

This is what I have in my module `./modules/password_policy`:

1. main.tf:

```
terraform {
  required_providers {
    aws = {
      source                = "hashicorp/aws"
      version               = ">= 2.7.0"
      configuration_aliases = [aws.account1, aws.account2]
    }
  }
}

resource "aws_iam_account_password_policy" "primary" {
  minimum_password_length      = 14
  max_password_age             = 60
  require_lowercase_characters = true
  require_numbers              = true
  require_uppercase_characters = true
  password_reuse_prevention    = 4
}
```

and this is what I have in the main folder's `password_policy.tf`:

```
module "password_policy" {
  source = "./modules/password_policy"
  providers = {
    aws.account1 = aws.account1,
    aws.account2 = aws.account2
  }
}
```
The output of terraform plan:

```
Terraform will perform the following actions:

  # module.password_policy.aws_iam_account_password_policy.password_policy will be created
  + resource "aws_iam_account_password_policy" "password_policy" {
      + allow_users_to_change_password = true
      + expire_passwords               = (known after apply)
      + hard_expiry                    = (known after apply)
      + id                             = (known after apply)
      + max_password_age               = 60
      + minimum_password_length        = 14
      + password_reuse_prevention      = 4
      + require_lowercase_characters   = true
      + require_numbers                = true
      + require_symbols                = (known after apply)
      + require_uppercase_characters   = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

The expected output must be: `Plan: 2 to add, 0 to change, 0 to destroy.`

i.e.:
`resource "aws_iam_account_password_policy" "password_policy[account1]" {`
`resource "aws_iam_account_password_policy" "password_policy[account2]" {`

My use case is simple: I would like to keep the same password policy for all our 50 AWS accounts. I feel really uncomfortable with repetitive code. It's like writing the same resource 50 times (or same `module "password_policy_account_1" {` 50 times) and just changing a single line i.e. `provider = aws.account_1`, `provider = aws.account_2`. 50 times copy-paste of the same resource. Instead, it's better if terraform just lets me pass the list of multiple aliases into a single resource.

**Comment by jbardin** [comment]
Hi @imtaji,

Thanks for filing the request. We already have open issues to track the ability to dynamically assign providers to module instances (#24476), and to have the ability to create multiple instances of a provider from a single configuration block (#19932). I'm not sure exactly what you're asking for here though, can you explain what exactly you intend to have happen when assigning multiple providers to a single resource?

**Comment by imtaji** [comment]
Ah, you already have this issue in track https://github.com/hashicorp/terraform/issues/19932. Thanks for suggesting, this is what I was looking for. 

I will read the comments and see if anything is helpful for my use case. Thanks again, I am closing the issue.
