### ISSUE TITLE
Feature to provide terraform plan in lowercase or uppercase 

### ISSUE THREAD

**Issue by Muhammada3178** [hashicorp/terraform#31065]
### Current Terraform Version

```
v0.13.7
```

### Use-cases

We use terraform for our infra as code needs. Users are able to add resources such as IAM roles and policies through terraform. Once a terraform plan is generated we do further checks on it to ensure that the changes the user is making do not contain any misconfigurations. The issue is that IAM policies are case insensitive so the following actions: 

`"s3:ListBucket"` and `"s3:listbucket"`

are both valid. We want to be able to evaluate every policy in a consistent manner so we are looking for a feature that would output the terraform plan in a certain case formatting as well. For example: Currently we run `terraform show -json` to get the plan in json format. 

Having something like `terraform show -json -lowercase` or `terraform show -json -uppercase` would be what we need as it would allow us to not worry about different case sensitivities when we are evaluating the plan. 

### Attempted Solutions

We have not been able to find a solution that used an existing terraform feature. The solutions that we implemented were implemented outside of Terraform. 

### Proposal

Having something like `terraform show -json -lowercase` or `terraform show -json -uppercase` which would provide the plan in json format and in lowercase or uppercase would be perfect. 

I have not looked at the code too closely in this repo so I'm not sure how we could go about it but if this is a feature that sounds interesting to your team as well then I could take a look through the code and figure out a way to implement it.

**Comment by apparentlymart** [comment]
Hi @Muhammada3178,

Our intention with these features is that whatever external software you are using to make decisions based on the `terraform show -json` output would itself be responsible for performing any needed normalization for the decisions it intends to make.

There is no common rule that would make sense across every attribute of every resource type: some systems are case sensitive, and some systems that are case-insensitive use different case-folding algorithms. Thinking beyond strings, there are also other possible normalizations you might need to make such as sorting a list prior to comparing it if you know that the ordering is not relevant to the decision you intend to make.

It isn't viable for us to support every possible normalization directly inside Terraform itself, and the specific uppercase and lowercase capabilities you've requested would be useful only in very limited situations that could already be addressed by you normalizing the strings yourself in the separate software you are building to verify the plan.

For these reasons, we will not add any built-in global normalization to the JSON plan or state output, and so I'm going to close this. It's always the responsibility of the consumer of that data to perform whatever normalization is needed for its intended use-case. Thanks!
