### ISSUE TITLE
Appending to `for_each` list in a data source causes existing/unchanged data source to be re-applied

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform#31061]
### Terraform Version

```
v1.1.9
```

### Problem

First apply the following config, which provisions a resource group and read that resource group afterwards into the state:

```terraform
provider "azurerm" {
  features {}
}

locals {
  foos = toset(["magodo-test"])
}

resource "azurerm_resource_group" "test" {
  for_each = local.foos
  name     = each.key
  location = "eastus2"
}

data "azurerm_resource_group" "test" {
  for_each = local.foos
  name     = azurerm_resource_group.test[each.key].name
}
```

Afterwards, append a new entry to the `local.foos`, and run `terraform plan` again, it shows:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.azurerm_resource_group.test["magodo-test"] will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_resource_group" "test"  {
      ~ id       = "/subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/magodo-test" -> (known after apply)
      ~ location = "eastus2" -> (known after apply)
        name     = "magodo-test"
      ~ tags     = {} -> (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # data.azurerm_resource_group.test["magodo-test2"] will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_resource_group" "test"  {
      + id       = (known after apply)
      + location = (known after apply)
      + name     = "magodo-test2"
      + tags     = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # azurerm_resource_group.test["magodo-test2"] will be created
  + resource "azurerm_resource_group" "test" {
      + id       = (known after apply)
      + location = "eastus2"
      + name     = "magodo-test2"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

Note that it doesn't only show it will create and read from the newly added resource group entry, it will also mark the existing resource group data source as to be re-read, which causes all its computed properties marked as "known after apply". It might cause unexpected resource replacement if some other resource depends on these computed properties, when those depending properties requires a force new on change.

### Expected Behavior

Just like the managed resources, appending a new entry to the `for_each` shouldn't affect the existing data sources that exclusivly referencing the `for_each` values as the source of the input properties.

### References

- https://github.com/hashicorp/terraform-provider-azurerm/issues/16806

**Comment by jbardin** [comment]
Oops, I was just looking at the wrong output for that case. The current plan for for the existing data source will read:
```
# (depends on a resource or a module with changes pending)
```

**Comment by magodo** [comment]
@jbardin I can understand that when a data source is *directly* referencing a managed resource (as above example), the data source will be defered to be known at apply time rather than refresh time (as is tated in [data resource behavior](https://www.terraform.io/language/data-sources#data-resource-behavior)).

However, this still can't resolve my question above. Imagine I didn't use the `for_each` in above example, but separate them into two sets of single resource & data source:

```hcl
provider "azurerm" {
  features {}
}

locals {
  foos = ["magodo-test1"]
}

resource "azurerm_resource_group" "test1" {
  name     = local.foos[0]
  location = "eastus2"
}

data "azurerm_resource_group" "test1" {
  name = azurerm_resource_group.test1.name
}
```

Apply above config, and then add a new set as below:

```hcl
# ...
locals {
  foos = ["magodo-test1", "magodo-test2"] # Append a new one
}
# ...
resource "azurerm_resource_group" "test2" {
  name     = local.foos[1]
  location = "eastus2"
}

data "azurerm_resource_group" "test2" {
  name = azurerm_resource_group.test2.name
}
```

Then the plan shows only the newly added data source and resource, but won't show the existing data source, even if it is still *directly* referencing the `azurerm_resource_group.test1.name`.

**Comment by jbardin** [comment]
Hi @magodo,

Dependencies within terraform are managed at the resource level, so when you use `depends_on` in a data source (implied via the direct reference to the managed resource), any change in any instance of that managed resource will defer the reading of the data source until apply. 

Using the alternative described in the documentation of indirectly referencing the managed resource through a local variable produces the exact behavior you are describing. Replacing your resources with the null provider and using `for_each`, I get a plan only showing the new instances:

```
Terraform will perform the following actions:

  # data.null_data_source.test["magodo-test2"] will be read during apply
  # (config refers to values not yet known)
 <= data "null_data_source" "test" {
      + has_computed_default = (known after apply)
      + id                   = (known after apply)
      + inputs               = {
          + "name" = (known after apply)
        }
      + outputs              = (known after apply)
      + random               = (known after apply)
    }

  # null_resource.test["magodo-test2"] will be created
  + resource "null_resource" "test" {
      + id       = (known after apply)
      + triggers = {
          + "name" = "magodo-test2"
        }
    }
Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by magodo** [comment]
@jbardin I've tried to understand how to *indirectly referencing the managed resource values through a local value*, and ends up with following:

```hcl
locals {
  names     = toset(["magodo-test1", "magodo-test2"])
  names_ref = toset([for n in local.names : null_resource.test[n].triggers["name"]])
}

resource "null_resource" "test" {
  for_each = local.names
  triggers = {
    name = each.value
  }
}

data "null_data_source" "test" {
  for_each = local.names_ref
  inputs = {
    name = each.value
  }
}
```

However, the plan result is as below:

```
null_resource.test["magodo-test1"]: Refreshing state... [id=909783909768775715]
data.null_data_source.test["magodo-test2"]: Reading...
data.null_data_source.test["magodo-test1"]: Reading...
data.null_data_source.test["magodo-test1"]: Read complete after 0s [id=static]
data.null_data_source.test["magodo-test2"]: Read complete after 0s [id=static]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.test["magodo-test2"] will be created
  + resource "null_resource" "test" {
      + id       = (known after apply)
      + triggers = {
          + "name" = "magodo-test2"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

This is not the same as yours. In my case, it is just as if I've referenced the `local.names` in the data source, which misses of the dependency on the managed resource.

**Comment by jbardin** [comment]
The difference from my example is that in yours the `name` values are statically known, so the data source will be read optimistically during the plan. In order to defer the reading of the data source, either the configuration must contain an unknown value, or the data source must depend on managed resource which has a pending change. 

This for example will give you the order you are looking for, but in order to do that you need a computed attribute which can be referenced:

```
locals {
  foos = toset(["magodo-test", "magodo-test2"])

  null_resource_test = null_resource.test
}

resource "null_resource" "test" {
  for_each = local.foos
  triggers = {
    name = each.key
  }
}

data "null_data_source" "test" {
  for_each = local.foos
  inputs = {
    name     = local.null_resource_test[each.key].id
  }
}
```

**Comment by magodo** [comment]
@jbardin This is really helpful, thank you! I think the document for the data source for this part can be extended a bit with above example?
