### ISSUE TITLE
provider.azuread and random: missing provider

### ISSUE THREAD

**Issue by spark1825** [hashicorp/terraform#31066]
terraform {
  required_version = ">= 0.12.21"
  required_providers {
    azurerm = ">=2.0.0"
    random = "=2.2.1"
    azuread = "=0.8.0"
  }
} 

I'm using the required providers like this , getting error

error:-
Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* azuread (=0.8.0)
* random (=2.2.1)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

Error: missing provider "random"

Error: missing provider "azuread"

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
