### ISSUE TITLE
Create SSRS azure virtual machine with image

### ISSUE THREAD

**Issue by SGeorge007** [hashicorp/terraform#31076]
I have created a vm for SSRS in azure manually using an image - SQL Server 2017 Reporting Services on Windows Server 2019.
I am not able to find any reference online on how can i use this image and create the VM in terraform.

**Comment by crw** [comment]
Hello @SGeorge007,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
