### ISSUE TITLE
Changing aws_route53_resource_record.set_identifier should replace the resource

### ISSUE THREAD

**Issue by inkblot** [hashicorp/terraform#3107]
Any change to the `set_identifier` property of an `aws_route53_resource_record` should cause a replacement of the resource during planning. This is because the value of this property ends up as a component of the resource record set's ID.

**Comment by stack72** [comment]
@phinze / @jen20 I **think** this can be closed. The change above is already in place:

```hcl
"set_identifier": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: true,
			},
```

This is in resource_aws_route53_record.go

**Comment by phinze** [comment]
Yep looks correct - thanks for the ping @stack72!
