### ISSUE TITLE
OpenID Connect authentication works for init but not for plan

### ISSUE THREAD

**Issue by torivara** [hashicorp/terraform#31085]
### Terraform Version

```
Terraform v1.2.0
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  backend "azurerm" {
    resource_group_name  = "rgname"
    storage_account_name = "testingterraform2313"
    container_name       = "terraformstate"
    key                  = "terraformstate.tfstate"
    use_oidc             = true
    subscription_id      = "***"
    tenant_id            = "***"
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

#Create Resource Group
resource "azurerm_resource_group" "rg" {
  name     = "tf-demo-rg"
  location = "westeurope"
}
```

### Debug Output

[Debug log](https://gist.github.com/torivara/bacdb77821c107a9ae33e1f4e55889af)

The error message is around line 2900.

### Expected Behavior

Terraform init creates the remote backend in Azure storage account.
Terraform plan should show me expected changes needed for infrastructure to match terraform files.

### Actual Behavior

Terraform init creates the remote backend as expected, and seems to be correctly authenticated (supports OIDC).

![image](https://user-images.githubusercontent.com/16333425/169371269-30df8d22-de18-4124-9dc5-3fc78cf937eb.png)

Terraform plan gives an error saying authentication with az cli is not allowed for service principals (does not support OIDC?).

![image](https://user-images.githubusercontent.com/16333425/169370712-be385b8d-6173-41b8-b836-f9d4c6d73fa8.png)

### Steps to Reproduce

1. terraform init
2. terraform plan

### Additional Context

I am trying to authenticate with OpenID Connect from a GitHub workflow. This feature was released in 1.2.0, and I was eager to test it out. Files can be found [here](https://github.com/torivara/oidc-starter). Used the docs from [here](https://www.terraform.io/language/settings/backends/azurerm).

As far as I can tell, the app registration has contributor access to the subscription. It does also have Storage Blob Data Owner on the storage account.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
