### ISSUE TITLE
aws_instance resource destroys machine when host_id is changed

### ISSUE THREAD

**Issue by jdremlap** [hashicorp/terraform#31082]
### Terraform Version

```1.1.9```

### Terraform Configuration Files

```terraform
resource "aws_instance" "db_server" {
  ami                    = var.ami
  instance_type          = var.instance_type
  iam_instance_profile   = var.ec2_profile_id
  monitoring             = true
  key_name               = var.ssh_key_name
  availability_zone      = var.availability_zone
  host_id                = var.dedicated_host_id
```

### Expected Behavior

```The ec2 instance should have been migrated to the new dedicated host based on the host_id parameter.```

### Actual Behavior

```The ec2 instance was destroyed and rebuilt on another dedicated host.```

### Steps to Reproduce

```1. terraform init
   2. Create two dedicated hosts.
   2. Deploy and ec2 instance with host_id set to dedicated host a.
   3. terraform apply
   4. Change host_id to dedicated host b.
   5. terraform apply
```
### Additional Context

```Nothing atypical about our setup.```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
