### ISSUE TITLE
Previously ignored lifecycle changes appear as new changes in every plan

### ISSUE THREAD

**Issue by samsonjs** [hashicorp/terraform#31088]
### Terraform Version

```
1.2.0
```

### Terraform Configuration Files

```terraform
resource "aws_default_vpc" "us_east_1" {
  tags = {
    Name = "default"
  }
}

resource "aws_default_network_acl" "us_east_1" {
  default_network_acl_id = aws_default_vpc.us_east_1.default_network_acl_id
  lifecycle {
    ignore_changes = [subnet_ids] # TF 1.2.0 warns about this but removing it causes TF to show it as changed in every plan
  }
}
```

### Debug Output
https://gist.github.com/samsonjs/aece479f713eeb5eb46cb02fa69cf2d6

### Expected Behavior
The plan shouldn't show any changes for `aws_default_network_acl.subnet_ids` because it's not configured.

### Actual Behavior
It shows that `subnet_ids` has changed.

### Steps to Reproduce

1. On Terraform 1.1, run the code shown above resulting in `subnet_ids` showing up in your state file.
2. Update to Terraform 1.2.0 and then run a plan and note the warning about ignoring an unconfigured property
3. Remove the `ignore_changes` block containing `subnet_ids`
4. Run another plan and note that it shows the subnet IDs as changed
5. Apply that plan and then run another one and note that it's still there
6. Run and apply a refresh-only plan and then run another plan and note that it's still there
7. Despair

### Additional Context
Running in Terraform Cloud with versions pinned to:
- Terraform 1.2.0
- AWS plugin 4.14.0
- TFE 0.31.0

### References
None

**Comment by jbardin** [comment]
Hi @samsonjs,

Thanks for filing the issue. Can you show an example of the output you are seeing when having set `ignore_changes = [subnet_ids]`? That is not a computed attribute, so it should be valid to ignore the changes imposed by the provider.

Thanks!

**Comment by samsonjs** [comment]
@jbardin Right you are. I was too eager to remove some of the ignored attributes and adding back `subnet_ids` doesn't result in a warning at all. Sorry for the false alarm and thanks for pointing me in the right direction!
