### ISSUE TITLE
AWS provider: aws_s3_bucket resource; missing versioning, lifecycle, logging, etc

### ISSUE THREAD

**Issue by packplusplus** [hashicorp/terraform#3108]
[AWS s3 APIs](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketOps.html) support several feature missing the aws_s3_bucket resource. 

Terraform does not provide a way to;
* ~~Turn on / off versioning~~
* ~~Lifecycle control policies~~
* ~~Logging targets~~
* Turn on / off Requestor pays
* Cross region replication
* ~~Events~~

Versioning and lifecycle policies are the features I'm most interested in, but I was trying to be complete (like the format in #3096 h/t: @clstokes )

**Comment by st-isidore-de-seville** [comment]
+1

**Comment by tisba** [comment]
This would be a feature we are interested in as well. We have lots of buckets that have at least one lifecycle policy and it's a pain to manage them via AWS Console (or API) after a TF run :-/

**Comment by tecnobrat** [comment]
+1 on events, we need this for our implementation.

**Comment by sstarcher** [comment]
+1 lifecyle

**Comment by mseiwald** [comment]
+1 lifecyle

**Comment by rmldsky** [comment]
+1 lifecycle

**Comment by scalp42** [comment]
I also don't believe you can create a bucket in a specific region (unless I'm wrong).

**Comment by cordoval** [comment]
buckets are created globally as per amazon

**Comment by packplusplus** [comment]
Buckets are namespaced globally, but you can indicate which region you want the data stored in. [See documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro).

**Comment by scalp42** [comment]
That's what I meant by region sorry.

**Comment by brikis98** [comment]
+1 for lifecycle

**Comment by chrisferry** [comment]
+1 for lifecycle.

**Comment by ben-nz** [comment]
+1 for lifecycle

**Comment by amuraru** [comment]
:+1:

**Comment by iulian-radu** [comment]
+1. See also: #4120

**Comment by failshell** [comment]
missing region as well.

+1 for logging.

**Comment by jasonyoumans** [comment]
+1 for lifecycle

**Comment by ktseytlin** [comment]
+1 for versioning/lifecycle/logging

**Comment by ecneladis** [comment]
+1 logging

**Comment by jen20** [comment]
Hi all. Thanks for commenting. As of the latest released version (0.6.9) versioning is supported (https://www.terraform.io/docs/providers/aws/r/s3_bucket.html).

In addition, logging support is on the `master` branch and will form part of the next release, though you can build from source now (clone; `make updatedeps`, `make bin`) the meantime assuming you have a Go environment.

Lifecycle policies, requestor pays, cross region replication and events are not yet supported - we will aim to support them soon but have a decent backlog of issues and pull requests to get through at the moment. If anyone wants to take these on in the meantime, either myself or @catsby should be able to review and merge.

**Comment by nagas** [comment]
+1

**Comment by kingpong** [comment]
+1 cross-region replicaton

**Comment by dabdine-r7** [comment]
+1 events

**Comment by davido-bs** [comment]
+1 lifecycle

**Comment by curena** [comment]
+1 events

**Comment by egoldschmidt** [comment]
+1 events, lifecycle

**Comment by ruippeixotog** [comment]
+1 lifecycle

**Comment by conorgil** [comment]
+1 events

**Comment by gtmtech** [comment]
+1 cross-region replication

**Comment by panda87** [comment]
+1 for lifecycle

**Comment by SpeedyWinds** [comment]
+1 for lifecycle

**Comment by steve-jansen** [comment]
@packplusplus would you please strike ~~log targets~~ and ~~versioning~~?

Believe both features [shipped](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html).

Cheers!

**Comment by netflash** [comment]
+1  cross-region replication / lifecycle

**Comment by saswatp** [comment]
+1 cross-region 
+1 life-cycle

**Comment by jbiel** [comment]
I am very interested in being able to manage s3 lifecycle policies with Terraform.

**Comment by jlspies1** [comment]
+1 cross-region
+1 lifecycle

**Comment by alfonso-cabrera** [comment]
+1 for cross region replication

**Comment by davidblewett** [comment]
+1 lifecycle

**Comment by aviflax** [comment]
+1 lifecycle please!

**Comment by ajlanghorn** [comment]
+1 lifecycle!

**Comment by radeksimko** [comment]
See S3 lifecycle PR in https://github.com/hashicorp/terraform/pull/6220

Feel free to post any feedback related to the implementation there ^

**Comment by stack72** [comment]
Lifecycle PR (#6220) has been merged

Can someone summate what is still missing from this issue? @packplusplus ?

**Comment by packplusplus** [comment]
I updated the original issue with strike thrus (good idea @steve-jansen).

@stack72  do you want to see these issues split out so you can wrestle them better, or do you like it in one place to point to? 

What's left: 
* Turn on / off Requestor pays - Not hugely important, I was just trying to highlight what wasn't supported that existed in aws. No one has +1'd
* [Cross region replication](http://docs.aws.amazon.com/AmazonS3/latest/UG/cross-region-replication.html) - Seems pretty popular. Also seems hard, there are IAM components that would have to be either auto created or called out in docs. 
* [Events](http://docs.aws.amazon.com/AmazonS3/latest/UG/SettingBucketNotifications.html) - Also seems popular.

**Comment by stack72** [comment]
nice summation @packplusplus - let's leave this issue as the main place right now :)

**Comment by hectcastro** [comment]
Are event notifications covered by https://github.com/hashicorp/terraform/pull/5473? Also, I think adding support for toggling the newly added transfer acceleration feature would be great (landed in the Go SDK yesterday: https://github.com/aws/aws-sdk-go/commit/174327fecba83be58dea4dee0ef1599652e0f2e5):

- https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/
- http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETaccelerate.html
- http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTaccelerate.html

**Comment by stack72** [comment]
Hi all

I just split the last 2 remaining items out into #7490 and #7491 

Thanks

Paul
