### ISSUE TITLE
aws_s3_bucket_website_configuration is temporarily removed during subsequent apply commands

### ISSUE THREAD

**Issue by ckeyes88** [hashicorp/terraform#31084]
Hi there, I'm not sure if this is a bug or my own lack of understanding around the s3 bucket and s3 bucket website configuration resources. I recently set up a terraform deployment to create a static site with an s3 bucket, s3 bucket website configuration, cloudfront distribution, and some dns records. 

Everything deploys and appears to work fine initially but I noticed that on subsequent plan and apply runs terraform gives the following notice even though I haven't changed anything outside of terraform:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:
```

Once it completes the apply the website configuration 

### Terraform Version
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.27"
    }
  }

  required_version = ">= 0.14.9"
}

terraform {
  backend "s3" {}
}

provider "aws" {
  region = var.region

  // Set up tags that all resources will be tagged with
  default_tags {
    tags = {
      Domain      = var.domain
      Environment = terraform.workspace
      ManagedBy   = "Terraform"
    }
  }
}
```

### Terraform Configuration Files
```terraform
resource "aws_s3_bucket" "www_bucket" {
  bucket = "www.mybucket.com"
}

resource "aws_s3_bucket_acl" "www_bucket_acl" {
  bucket = aws_s3_bucket.www_bucket.id
  acl    = "public-read"
}

resource "aws_s3_bucket_website_configuration" "www_bucket" {
  bucket = aws_s3_bucket.www_bucket.bucket

  index_document {
    suffix = "index.html"
  }
}
```

### Expected Behavior
I would expect that terraform could detect when a website configuration exists and not replace it which causes a temporary 404 error while the endpoint is being re configured
### Actual Behavior
Terraform appears to not that the resource already exists and things it needs to create a new one causing a temporary outage on the website during application

### Steps to Reproduce
```
terraform init
terraform apply
```
... Once it's done deploying don't change anything
```
terraform apply
```

**Comment by ckeyes88** [comment]
Cross linked: https://github.com/hashicorp/terraform-provider-aws/issues/24883

**Comment by jbardin** [comment]
Hi @ckeyes88,

Thanks for filing the issues! Since the provider is responsible for determining when a change is going to force replacement vs an update, we can track the issue in the provider repository.
