### ISSUE TITLE
Unable to import provider , Error while installing zscaler/zia v2.0.2: checksum list has unexpected SHA-256 has Any ideas?

### ISSUE THREAD

**Issue by maajin** [hashicorp/terraform#31093]
╷
│ Error: Failed to install provider
│
│ Error while installing zscaler/zia v2.0.2: checksum list has unexpected SHA-256 hash
│ 7904c44c1cef561270a3859ea3d8d43b33ea322d220dee49eb6790d0186356df (expected
│ 57e0e3bd2a2c1d246d49140c56afe8d64594bc23a95f1969bb2c9a9ec5d34133)

**Comment by jbardin** [comment]
Hi @maajin,

That provider seems to have a problem with their release binary for v2.0.2, perhaps they tried overwriting a release leading to a mismatch in the signed hash and the binary. There was of v2.0.3 immediately after which appears to be correct, so upgrading may be the correct solution here.

If that doesn't work I would reach out to the registry support or the provider developers. The terraform CLI can only report the problem it finds with the provided binary, but there's nothing we can do to remedy the situation.

Thanks!
