### ISSUE TITLE
installation of qualys using azurerm_security_center_server_vulnerability_assessment fails incorrectly stating that vm provisioning state is not succeeded.

### ISSUE THREAD

**Issue by satyakrish** [hashicorp/terraform#31106]
### Terraform Version

```
1.0.5
```

### Terraform Configuration Files

```terraform
resource "azurerm_security_center_server_vulnerability_assessment" "qualys" {
  depends_on = [
    module.managed_disk,
    time_sleep.wait_for_vm_agent,
    null_resource.check_vm_readiness
  ]

  count              = var.vm_count
  virtual_machine_id = azurerm_linux_virtual_machine.linux_vm[count.index].id
}
```

### Expected Behavior

Qualys assessment should have installed successfully without any issues

### Actual Behavior

Installation of Qualys vulnerability assessment fails incorrectly stating that the vm provisioning state is not succeeded whereas the provisioning state of the vm was indeed succeeded.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. Create a vm 
2. Create and attach managed disks for the vm (not related to the problem, problem happens even without managed disks.
3. wait for 5 minutes.
4. null resource checks whether the provisioning state of the vm is 'Succeeded'  and the status of vm agent is 'Ready' by executing the following commands.
'az vm get-instance-view --ids $id --query provisioningState -o json'
'az vm get-instance-view --ids $id --query instanceView.vmAgent.statuses[0].displayStatus -o json'

5. Install Qualys vulnerability scanner using the resource `azurerm_security_center_server_vulnerability_assessment`
6. The step-5 fails sometimes stating the vm provisioning state is not Succeeded.. whereas the provisioning state of the vm is in fact succeeded as verified by the null resource. Also checked the provisioning state of the vm immediately after the error it was actually Succeeded so the failure incorrect and has to be fixed.

Error: create Server Vulnerability Assessment for "/subscriptions/****/resourceGroups/dojo-linux-vm-with-encryption-default-cmk-pr-84/providers/Microsoft.Compute/virtualMachines/dojo-linux-vm-pr-84-2": security.ServerVulnerabilityAssessmentClient#CreateOrUpdate: Failure responding to request: StatusCode=424 -- Original Error: autorest/azure: Service returned an error. Status=424 Code="FailedDependency" Message="The provisioning state of the machine /subscriptions/****/resourceGroups/dojo-linux-vm-with-encryption-default-cmk-pr-84/providers/Microsoft.Compute/virtualMachines/dojo-linux-vm-pr-84-2 is not Succeeded."

### Additional Context
Note: 
This problem does not occur always it passes sometimes and sometimes it fails there is no fixed pattern.
This is breaking our CI/CD pipelines and we are not able to get consistent builds.
We tried increasing the delay before installing Qualys but that leads to microsoft defender automatically installing qualys and we face resource already exists error.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
