### ISSUE TITLE
Unable to decode base64code in  Terraform

### ISSUE THREAD

**Issue by muralikrishnarokkam** [hashicorp/terraform#31116]
I got an below error when I tried to decodebase64 in terraform. Can you let me know how to fix this issue.

Call to function "base64decode" failed: failed to decode base64 data
(sensitive value).

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
