### ISSUE TITLE
Change in variables in *.auto.tfvars not detecting new assigned values during terraform plan

### ISSUE THREAD

**Issue by pruchita97** [hashicorp/terraform#31117]
I had configured the below variable and used it in terraform files, earlier any change in the auto.tfvars were detected in terraform plan but now changes are not detected and terraform plan says 'No Changes'.

### Terraform Version

```
1.1.7 and also tested in 1.2.1
```

### Terraform Configuration Files
variables.tf
```terraform
variable "key_vault1" {
  type = object({
    instanceid = string
  })
}
```
config.auto.tfvars
```
key_vault1 = {
  instanceid = "87" // Earlier it was 01 now changing it to 87 but terraform plan fails to detect this change
}
```
tf file to deploy keyvault
```
data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "akv" {
  name                        = "uniquename-${var.key_vault1.instanceid}"
  resource_group_name         = "test"
  location                    = "North Europe"
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 90
  enable_rbac_authorization   = true
  purge_protection_enabled    = true
  sku_name                    = "premium"
}
```

### Expected Behavior
Terraform plan and apply should detect the change.

### Actual Behavior
Terraform Plan shows:
```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
/azp/_work/_tool/terraform/1.2.1/x64/terraform version
Terraform v1.2.1
```

### Steps to Reproduce
1. Put all the above three files in same directory
2. Run `terraform init`
3. Run `terraform plan`
4. Run `terraform apply`
5. Change value of the variable in `config.auto.tfvars`
6. Run `terraform init`
7. Run `terraform plan`
8. It shows no changes when it should've shown changes

### Additional Context
When a variables is set as null at 1st terraform apply which was successful, the second time when a variable value is passed it still shows null and terraform plan shows no changes.
For example:
`count  = var.enable_flag != null ? 1 : 0`

When the value for the variable is passed in config.auto.tfvars second time, it still shows no changes when it should deploy the resource as count would be 1. But even when values is changed from null to some other value, it is not detected by terraform plan.

**Comment by jbardin** [comment]
Hi @pruchita97,

Thanks for filing the issue, though I'm not able to replicate the behavior shown here. Terraform would return an error if it were not reading the variable value from somewhere, and if it's only defined in the `config.auto.tfvars` file, then I don't see any way the variable would not have the new value.

Make sure you don't have that variable also assigned in another tfvars file, which is overriding your change.

If the resource is not showing any changes with a new attribute value, then it would be an issue with the provider. Can you verify that you are using the latest provider release for that resource? 

If the variable is only assigned once, and the provider is not altering the plan, would it possible to include the log output from `TF_LOG_CORE=trace` when you execute `terraform plan`? 

Thanks!

**Comment by pruchita97** [comment]
Hi @jbardin,
I verified and the variable is only assigned once and there is no overriding.
I used latest azurerm provider 3.7.0 but still face the same issue.

I have generated the trace logs but since it contains sensitive data, I will not be able to share the whole log.

**Comment by jbardin** [comment]
Another debugging approach is you assign the variable to an output value in the root module, and see if you also observe a change in the root output during the plan. The variable value must be assigned somewhere, so the key here is to figure out where that might be. The example you shown, when run in a clean directory, shows a corresponding change to the `azurerm_key_vault.akv.name` attribute.

**Comment by pruchita97** [comment]
Although the variable is set to the value `87` in `config.auto.tfvars`, the output block still shows `01` and nowhere the variable is overridden. I will check if there is some other issue with the pipelines. But you are correct, I tested in a clean directory and the changes are showing as expected.
```
output "keyvault_id_value" {
  value = var.key_vault1.instanceid
}
```

During terraform run
```
Changes to Outputs:
  + keyvault_id_value = "01"

```

**Comment by pruchita97** [comment]
Hi @jbardin,
There was some issue in the pipeline which was overriding the value. We can close this bug. Thank you for your help.
