### ISSUE TITLE
AWS plugin is crashing Error : The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.

### ISSUE THREAD

**Issue by kmanika** [hashicorp/terraform#31110]
### Terraform Version

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.15.1
```

### Error details
```
aws_lambda_function.tf_lambda_function: Creating...
╷
│ Error: Request cancelled
│
│   with aws_lambda_function.tf_lambda_function,
│   on lambda.tf line 22, in resource "aws_lambda_function" "tf_lambda_function":
│   22: resource "aws_lambda_function" "tf_lambda_function" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
```

**Comment by jatinsinghalsg** [comment]
https://github.com/jckuester/awsrm/issues/2#issuecomment-876348275

This possibility solves this.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by kmanika** [comment]
Thanks @jbardin
