### ISSUE TITLE
Release downloads are not signed, nor is the checksum

### ISSUE THREAD

**Issue by philpennock** [hashicorp/terraform#3113]
At present, the downloads for Terraform releases are on a third-party download site, and this also includes the checksums file with the SHA256 checksums for all files.

So there's nothing to help the downloader verify that the files haven't been tampered with, since the reference is equally exposed to being tampered with.

Could you please PGP-sign the checksums file, with some verifiable key, so that we can establish a trust-path to the binary updates?

Thanks.

**Comment by mitchellh** [comment]
Yes, we do this for Vault so we do have the machinery in place (within our ecosystem) to do this. Tagged.

**Comment by abitrolly** [comment]
Downloads for Terraform release are now at "own" CDN, so the problem should be less actual https://releases.hashicorp.com/terraform/0.10.7/

**Comment by philpennock** [comment]
More importantly, the checksums file is now signed; the `terraform_0.10.7_SHA256SUMS.sig` signature verifies.  At the time this issue was filed, those `.sig` files were not provided for Terraform.
