### ISSUE TITLE
Associate the service action with a product version

### ISSUE THREAD

**Issue by amayreddy25** [hashicorp/terraform#31137]
### Current Terraform Version

```
Terraform v1.1.9
AWS Provider - V4.15.1
```

### Use-cases

I have used terraform resource "aws_servicecatalog_service_action" to create a service action in the Service Catalog. But I don't see any resource where I can associate the service action with the product version.

### Attempted Solutions

I am looking for direction on how I can tie the service action to the product version via terraform. I am opening this as a feature request incase if this is missing.
### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/servicecatalog/associate-service-action-with-provisioning-artifact.html

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by amayreddy25** [comment]
Hi ,

Thanks for the response. Please feel free to close this ticket as I will first check with the community forum. Apologies for the inconvenience.
