### ISSUE TITLE
data block filter values lists fails if I provide more than one value 

### ISSUE THREAD

**Issue by geof2001** [hashicorp/terraform#31147]
From data source documentation
[values](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_transit_gateway_peering_attachment#values) - (Required) Set of values that are accepted for the given field. An EC2 Transit Gateway Peering Attachment be selected if any one of the given values matches.

My data block looks like this 

```terraform
data "aws_ec2_transit_gateway_peering_attachment" "accepter_attachment_id" { 
  provider = aws.accepter
  depends_on = [ aws_ec2_transit_gateway_peering_attachment.peering_attachment ]
  filter {
    name   = "transit-gateway-id"
    values = [var.accepter_tgw_id]
  }
  filter {
    name   = "remote-owner-id"
    values = [data.aws_caller_identity.requester_id.id]
  }
  filter {
    name   = "state"
    values = ["available","pendingAcceptance"]
  }
}
```

with this definition it's unable to find the resource if it's one of these states.  I have to reduce the values list to either "available" or "pendingAcceptance" in order for it to find the resource.  If feel it's necessary I can provide full debug and a github repo of the module we created for this.  Requirements would just be two separate AWS accounts with existing TGW's

Expected behaviour:
It would identify the resource if it's in either of these two states.  As found in the AWS documentation for this API: Valid values are **available** | deleted | deleting | failed | failing | initiatingRequest | modifying | **pendingAcceptance** | pending | rollingBack | rejected | rejecting)

### Terraform Version
```
tf version
Terraform v1.2.1
on darwin_arm64
```

### Terraform Configuration Files
```provider "aws" {
  region = var.requester_region
}
provider "aws" {
  alias   = "accepter"
  profile = var.accepter_profile
  region  = var.accepter_region
}
provider "aws" {
  alias   = "requester"
  profile = var.requester_profile
  region  = var.requester_region
}

data "aws_caller_identity" "accepter_id" {
  provider = aws.accepter
}

data "aws_caller_identity" "requester_id"{
  provider = aws.requester
}

resource "aws_ec2_transit_gateway_peering_attachment" "peering_attachment" {
  provider                = aws.requester
  peer_account_id         = data.aws_caller_identity.accepter_id.id
  peer_region             = var.accepter_region
  peer_transit_gateway_id = var.accepter_tgw_id
  transit_gateway_id      = var.requester_tgw_id

  tags = {
    Name = "${var.requester_region}-${local.requester_env}-<->-${var.accepter_region}-${local.accepter_env}"
  }
}

# this data resource is required method because the accepter in the same region
# will have a different attachment id than the requester.  Affects intra region connections only
data "aws_ec2_transit_gateway_peering_attachment" "accepter_attachment_id" { 
	provider = aws.accepter
	depends_on = [ aws_ec2_transit_gateway_peering_attachment.peering_attachment ]
	filter {
		name   = "transit-gateway-id"
		values = [var.accepter_tgw_id]
	}
  filter {
    name   = "remote-owner-id"
    values = [data.aws_caller_identity.requester_id.id]
  }
  filter {
    name   = "state"
    values = ["available""pendingAcceptance"]
  }
}

resource "aws_ec2_transit_gateway_peering_attachment_accepter" "accepting_attachment" {
  provider = aws.accepter
  transit_gateway_attachment_id = data.aws_ec2_transit_gateway_peering_attachment.accepter_attachment_id.id
  tags = {
    Name = "${var.accepter_region}-${local.accepter_env}-<->-${var.requester_region}-${local.requester_env}"
  }
}
```

### Debug Output
2022-05-29T14:13:06.804-0700 [TRACE] vertex "module.prod_us_west_2_to_dev_sa_east_1.data.aws_ec2_transit_gateway_peering_attachment.accepter_attachment_id (expand)": dynamic subgraph encountered errors: error reading EC2 Transit Gateway Peering Attachment: no results found
2022-05-29T14:13:06.804-0700 [ERROR] vertex "module.prod_us_west_2_to_dev_sa_east_1.data.aws_ec2_transit_gateway_peering_attachment.accepter_attachment_id (expand)" error: error reading EC2 Transit Gateway Peering Attachment: no results found

### Expected Behavior
module.prod_us_west_2_to_dev_sa_east_1.data.aws_ec2_transit_gateway_peering_attachment.accepter_attachment_id (expand) - *terraform.nodeExpandApplyableResource

That it would find the resource if either of the two values matched the state of the resource in the other account, region.

### Actual Behavior
couldn't find the peering attachment id of resource in the attachment accepter account and region with two values configured in the filter list

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Additional Context
running locally with two aws profiles configured for the accepter/requester accounts

### References
I couldn't find anything on this subject or even examples of multi-valued lists for filters.

**Comment by alisdair** [comment]
Thanks for reporting this! This does not appear to be a Terraform core bug, and rather something related to the AWS provider. [Please report the issue in the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws/issues/new/choose), where it can be seen by the AWS provider maintainers.
