### ISSUE TITLE
AWS RDS: Allow terraform destroy on stopped aurora RDS instance

### ISSUE THREAD

**Issue by Nogginboink** [hashicorp/terraform#31144]
An AWS RDS Aurora serverless cluster must be in the 'available' state in order to be destroyed. If I run 'terraform destroy' on a stopped RDS serverless cluster, I get an InvalidDBClusterStateFault saying 'Db cluster <name> is in stopped state'

Proposed solution: start the RDS cluster if it is in stopped state as part of the destroy process.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
