### ISSUE TITLE
filter parameter on API call for list teams does not work

### ISSUE THREAD

**Issue by rubyisbeautiful** [hashicorp/terraform#31158]
### Terraform Version

```
0.12.31 CLI; 202204-2 TFE
```

### Terraform Configuration Files

```terraform
N/A
```

### Expected Behavior

When I use the filter parameter to an API call that uses scoped resources, e.g. teams, the results reflect only the resources with matching names.  I believe this may affect other scoped resources with list/filter API calls.

### Actual Behavior

When I use the filter parameter to an API call that uses scoped resources, e.g. teams, not all results match the filter parameter and they are not consistent.

### Steps to Reproduce

Setup:

TFE with an organization that has two teams: the implicit owners teams and another team, foo.

1. Use filter on /organizations/:organization_name/teams

`curl -s --location --request GET 'https://my.tfe/api/v2/organizations/test/teams?page%5Bsize%5D=2&filter%5Bnames%5D=foo' --header 'Content-Type: application/vnd.api+json' --header 'Authorization: Bearer aaa.atlasv1.bbb' | jq '.data[].attributes.name '`

```
"foo"
"owners"
```

If I add a third team, bar:

`curl -s --location --request GET 'https://my.tfe/api/v2/organizations/test/teams?page%5Bsize%5D=2&filter%5Bnames%5D=foo' --header 'Content-Type: application/vnd.api+json' --header 'Authorization: Bearer aaa.atlasv1.bbb' | jq '.data[].attributes.name '`

```
"foo"
"bar"
```

### References

- According to [the documentation](https://www.terraform.io/cloud-docs/api-docs/teams): the results are restricted to "a team with a matching name"
- I reported this via Hashicorp support, [74293](https://support.hashicorp.com/hc/en-us/requests/74293?page=1), as both a feature request and a bug.  The feature request was given reference number 1202325257031573.  The Terraform Support Engineer requested that I open a bug report for the incorrect behavior.

**Comment by jbardin** [comment]
Hi @rubyisbeautiful,

This repository os only for the development of the Terraform CLI. You can follow up on the issue through your open support ticket.

Thanks!
