### ISSUE TITLE
Unable to add new AD users/SPN via TF code in Production environment

### ISSUE THREAD

**Issue by NetraLBhushal** [hashicorp/terraform#31150]
### Terraform Version

terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "=1.0.0"
    }
    azuredevops = {
      source  = "microsoft/azuredevops"
      version = ">= 0.1.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.0"
    }
    github = {
      source  = "hashicorp/github"
      version = "~>4.1.0"
    } 
    null = {
      source  = "hashicorp/null"
      version = "~> 2.1"
    }
    external = {
      source  = "hashicorp/external"
      version = "~> 2.0.0"
    }
  }
  required_version = ">= 0.13"
}

### Terraform Configuration Files

```terraform
...
```

### Debug Output

Error: Invalid index

  on 06_RBAC/rbac.tf line 14, in module "security_groups":
  14:   members                 = [for member in concat(each.value.members.users, each.value.members.spn, each.value.members.groups) : local.all_adobjects[member]]
    |----------------
    | local.all_adobjects is object with 112 attributes

The given key does not identify an element in this collection value.

### Expected Behavior

In the plan output file we should see the username and object ID which will get added as part of the code.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
