### ISSUE TITLE
Document the possibility of using the `format` function to robustly show arbitrary values in custom condition `error_message`

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#31165]
### Current Terraform Version

```
1.2.1
```

### Use-cases

There are a number of scenarios where I have variable validation blocks that iterate over all items in a list or map to verify that they meet the required validation. Now that https://github.com/hashicorp/terraform/pull/30613 allows for outputting the variable as part of the error message, I'd like to be able to output a list of all items in the variable's list/map that violate the validation rule as part of the error message. 

I'd also like to be able to output `null` in the error messages. This comes in handy if you have a variable that defaults to `null` but a validation rule that imposes constraints if the variable is specified.

#### List/Map
```tf
variable "custom_labels" {
  description = "Custom labels to be applied to resources."
  default     = {}
  type        = map(string)

  validation {
    condition = alltrue([
      for key, val in var.custom_labels :
      can(regex("^[a-z][a-z0-9-]{0,62}$", key))
    ])
    error_message = "Invalid key(s) ${[for key, val in var.custom_labels : key if !can(regex("^[a-z][a-z0-9-]{0,62}$", key))]}, must match this regex '^[a-z][a-z0-9-]{0,62}$'."
  }
}
```

Fails with:
```
│     │ var.custom_labels is empty map of string
│ 
│ Cannot include the given value in a string template: string required.
```

Adding a `tostring()` also does not work because `tostring()` does not work on lists or maps.

Adding a `join(", ", [...])` to convert it to a string works, but is a painful workaround for something that is seems like Terraform should be able to more natively handle.

#### Null
```tf
variable "team_name" {
  description = "The name of the team that owns this resource."
  default     = null
  type        = string

  validation {
    condition = (
      var.team_name == null ||
      can(regex("^[a-z0-9-]{1,63}$", var.team_name))
    )
    error_message = "Invalid team_name '${var.team_name}', must match this regex '^[a-z0-9-]{1,63}$'."
  }
}
```
 Fails with:
```
│     │ var.team_name is null
│ 
│ The expression result is null. Cannot include a null value in a string
│ template.
```
Adding `tostring()` doesn't solve the issue (although I thought it would based on https://github.com/hashicorp/terraform/pull/30879). 

Adding `coalesce(var.team_name, "null")` does work, but again seems like a painful workaround for something that Terraform should be able to more natively handle.

### Proposal

Allow Terraform to handle these conversions under the hood so that the above example snippets work without any extra configuration.

### References

- https://github.com/hashicorp/terraform/pull/30613
- https://github.com/hashicorp/terraform/pull/30879

**Comment by apparentlymart** [comment]
Hi @joe-a-t! Thanks for sharing this use-case.

I think a general answer with today's Terraform could be to use [the `format` function](https://www.terraform.io/language/functions/format) to convert the value into a formatted string.

The `%v` and `%#v` verbs are intended for this sort of "format an arbitrary value for debugging" situation; both will accept a value of any type and always produce _some_ sort of string representation of it, falling back in a JSON serialisation of nothing else makes sense. (The `#` modifier makes it use JSON in all cases, even for primitive types.)

Would that work for you? I don't think we want to add generalized automatic conversions from all types to string because we see the the relatively simple automatic type conversions in our language already cause confusion for some readers; making the conversion explicit with `format` seems like a good compromise to me because it is an explicit request from the author to just produce _some sort of string_, and a future reader can see that is what the original author intended.

**Comment by joe-a-t** [comment]
Hey @apparentlymart,

Thanks a lot, yeah that works for me and is a lot cleaner than my prior workarounds. I had looked at `format` briefly but didn't see any mention of `list` or `map` (or find results with a command + f) so I moved on. I opened https://github.com/hashicorp/terraform/issues/31175 as a documentation update request re improving the docs for format. 

Can we convert this issue to be a documentation update request to add your response to https://www.terraform.io/language/expressions/custom-conditions#error-messages so that the next time someone is looking at the documentation for error messages, it is easy to discover the best way to incorporate lists/maps/nulls in the error message?

**Comment by laurapacilio** [comment]
Hello @joe-a-t - thank you for this submission and for the docs suggestion.

I opened a little PR that adds this guidance to the custom conditions page. Let me know what you think!

https://github.com/hashicorp/terraform/pull/31198

**Comment by antonpatsev** [comment]
@joe-a-t I Validate complex type using terraform.
Could you share valid code validation custom_labels ? Thanks!

**Comment by joe-a-t** [comment]
@antonpatsev 

```tf
variable "custom_labels" {
  description = "Custom labels to be applied to resources."
  default     = {}
  type        = map(string)

  validation {
    condition = alltrue([
      for key, val in var.custom_labels :
      can(regex("^[a-z][a-z0-9-]{0,62}$", key))
    ])
    error_message = format(
      "Invalid key(s) %v, must match this regex '^[a-z][a-z0-9-]{0,62}$'.", 
      [for key, val in var.custom_labels : key if !can(regex("^[a-z][a-z0-9-]{0,62}$", key))]
  }
}
```
