### ISSUE TITLE
terraform gives Sink: C0644 error, then misses cycle. Ansible playbooks actually execute correctly, but terraform registers a fail

### ISSUE THREAD

**Issue by sara-hann** [hashicorp/terraform#31173]
**It seems there is a bug in passing results from Ansible playbooks back to Terraform. Note that I have no issue when executing on a single node, but when executing the playbooks on two nodes simultaneously, I get the Sink errors. The playbooks actually execute on each node correctly - I am able to reach my application on both nodes afterwards. You will see too, that the terraform shows it was successful with no failures in the summary, then, instead of posting the outputs, it posts this error message:**

null_resource.ExecuteAnsible[0] (local-exec): TASK [The EP.cer has been copied to the controller node at /home/xacta/EP.cer and can be viewed with the cat command.] ***
null_resource.ExecuteAnsible[0] (local-exec): changed: [35.170.187.39]
null_resource.ExecuteAnsible[0] (local-exec): changed: [3.88.0.96]

null_resource.ExecuteAnsible[0] (local-exec): PLAY RECAP *********************************************************************
null_resource.ExecuteAnsible[0] (local-exec): 3.88.0.96                  : ok=51   changed=34   unreachable=0    failed=0    skipped=5    rescued=0    ignored=5
null_resource.ExecuteAnsible[0] (local-exec): 35.170.187.39              : ok=51   changed=34   unreachable=0    failed=0    skipped=5    rescued=0    ignored=5

null_resource.ExecuteAnsible[0]: Creation complete after 8m7s [id=2727211798245715006]
╷
│ Error: local-exec provisioner error
│
│   with null_resource.ExecuteAnsible[1],
│   on instances.tf line 226, in resource "null_resource" "ExecuteAnsible":
│  226:   provisioner "local-exec" {
│
│ Error running command '  ansible-playbook --extra-vars "@AnsiblePlaybooks/Variables.json" AnsiblePlaybooks/PostgresInstaller.yml
│ ': exit status 2. Output: s.",
│             "Unable to read consumer identity",
│             "",
│             "This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.",
│             "",
│             "Waiting for process with pid 14745 to finish.",
│             "Last metadata expiration check: 0:00:10 ago on Wed 01 Jun 2022 02:13:23 PM UTC.",
│             "Dependencies resolved.",
│             "================================================================================",
│             " Package               Arch    Version        Repository                   Size",
│             "================================================================================",
│             "Installing:",
│             " modulemd-tools        noarch  0.7-4.el8      @commandline                 44 k",
│             "Installing dependencies:",
│             " python3-click         noarch  7.1.2-3.el8pc  LocalRepo                   142 k",
│             " python3-createrepo_c  x86_64  0.17.7-3.el8   LocalRepo                    67 k",
│             " python3-libmodulemd   x86_64  2.9.4-2.el8    rhel-8-appstream-rhui-rpms   20 k",
│             "",
│             "Transaction Summary",
│             "================================================================================",
│             "Install  4 Packages",
│             "",
│             "Total size: 274 k",
│             "Total download size: 20 k",
│             "Installed size: 855 k",
│             "Downloading Packages:",
│             "python3-libmodulemd-2.9.4-2.el8.x86_64.rpm      740 kB/s |  20 kB     00:00    ",
│             "--------------------------------------------------------------------------------",
│             "Total                                           398 kB/s |  20 kB     00:00     ",
│             "Running transaction check",
│             "Transaction check succeeded.",
│             "Running transaction test",
│             "Transaction test succeeded.",
│             "Running transaction",
│             "  Preparing        :                                                        1/1 ",
│             "  Installing       : python3-libmodulemd-2.9.4-2.el8.x86_64                 1/4 ",
│             "  Installing       : python3-createrepo_c-0.17.7-3.el8.x86_64               2/4 ",
│             "  Installing       : python3-click-7.1.2-3.el8pc.noarch                     3/4 ",
│             "  Installing       : modulemd-tools-0.7-4.el8.noarch                        4/4 ",
│             "  Running scriptlet: modulemd-tools-0.7-4.el8.noarch                        4/4 ",
│             "  Verifying        : python3-click-7.1.2-3.el8pc.noarch                     1/4 ",
│             "  Verifying        : python3-createrepo_c-0.17.7-3.el8.x86_64               2/4 ",
│             "  Verifying        : python3-libmodulemd-2.9.4-2.el8.x86_64                 3/4 ",
│             "  Verifying        : modulemd-tools-0.7-4.el8.noarch                        4/4 ",
│             "Installed products updated.",
│             "",
│             "Installed:",
│             "  modulemd-tools-0.7-4.el8.noarch                                               ",
│             "  python3-click-7.1.2-3.el8pc.noarch                                            ",
│             "  python3-createrepo_c-0.17.7-3.el8.x86_64                                      ",
│             "  python3-libmodulemd-2.9.4-2.el8.x86_64                                        ",
│             "",
│             "Complete!",
│             "Updating Subscription Management repositories.",
│             "Unable to read consumer identity",
│             "",
│             "This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.",
│             "",
│             "Cache was expired",
│             "32 files removed",
│             "Directory walk started",
│             "Directory walk done - 340 packages",
│             "Temporary output repo path: ./.repodata/",
│             "Preparing sqlite DBs",
│             "Pool started (with 5 workers)",
│             "Pool finished"
│         ]
│     }
│ }
│
│ TASK [Install the Postgres packages] *******************************************
│ skipping: [35.170.187.39]
│ skipping: [3.88.0.96]
│
│ TASK [debug] *******************************************************************
│ ok: [35.170.187.39] => {
│     "msg": {
│         "changed": false,
│         "skip_reason": "Conditional result was False",
│         "skipped": true
│     }
│ }
│ ok: [3.88.0.96] => {
│     "msg": {
│         "changed": false,
│         "skip_reason": "Conditional result was False",
│         "skipped": true
│     }
│ }
│
│ TASK [Install the Postgres packages] *******************************************
│ fatal: [35.170.187.39]: FAILED! => {"changed": true, "cmd": "sudo yum install Postgres12/RHEL8/postgresql-* -y --nogpgcheck", "delta": "0:00:01.193718", "end":
│ "2022-06-01 14:13:42.914110", "msg": "non-zero return code", "rc": 1, "start": "2022-06-01 14:13:41.720392", "stderr": "Error: Failed to download metadata for repo
│ 'rhel-8-appstream-rhui-rpms': Cannot open /var/cache/dnf/rhel-8-appstream-rhui-rpms-41aa424961bb928d/repodata/repomd.xml: No such file or directory", "stderr_lines":
│ ["Error: Failed to download metadata for repo 'rhel-8-appstream-rhui-rpms': Cannot open
│ /var/cache/dnf/rhel-8-appstream-rhui-rpms-41aa424961bb928d/repodata/repomd.xml: No such file or directory"], "stdout": "Updating Subscription Management
│ repositories.\nUnable to read consumer identity\n\nThis system is not registered to Red Hat Subscription Management. You can use subscription-manager to
│ register.\n\nLocalRepo                                       162 MB/s | 438 kB     00:00    \nRed Hat Update Infrastructure 3 Client Configur  30 kB/s | 2.0 kB
│ 00:00    \nRed Hat Enterprise Linux 8 for x86_64 - AppStre 118 MB/s |  44 MB     00:00    ", "stdout_lines": ["Updating Subscription Management repositories.",
│ "Unable to read consumer identity", "", "This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.", "",
│ "LocalRepo                                       162 MB/s | 438 kB     00:00    ", "Red Hat Update Infrastructure 3 Client Configur  30 kB/s | 2.0 kB     00:00    ",
│ "Red Hat Enterprise Linux 8 for x86_64 - AppStre 118 MB/s |  44 MB     00:00    "]}
│ fatal: [3.88.0.96]: FAILED! => {"changed": true, "cmd": "sudo yum install Postgres12/RHEL8/postgresql-* -y --nogpgcheck", "delta": "0:00:01.318278", "end":
│ "2022-06-01 14:13:43.072044", "msg": "non-zero return code", "rc": 1, "start": "2022-06-01 14:13:41.753766", "stderr": "Error: Failed to download metadata for repo
│ 'rhel-8-appstream-rhui-rpms': Cannot open /var/cache/dnf/rhel-8-appstream-rhui-rpms-41aa424961bb928d/repodata/repomd.xml: No such file or directory", "stderr_lines":
│ ["Error: Failed to download metadata for repo 'rhel-8-appstream-rhui-rpms': Cannot open
│ /var/cache/dnf/rhel-8-appstream-rhui-rpms-41aa424961bb928d/repodata/repomd.xml: No such file or directory"], "stdout": "Updating Subscription Management
│ repositories.\nUnable to read consumer identity\n\nThis system is not registered to Red Hat Subscription Management. You can use subscription-manager to
│ register.\n\nLocalRepo                                       162 MB/s | 438 kB     00:00    \nRed Hat Update Infrastructure 3 Client Configur  39 kB/s | 2.0 kB
│ 00:00    \nRed Hat Enterprise Linux 8 for x86_64 - AppStre  85 MB/s |  44 MB     00:00    ", "stdout_lines": ["Updating Subscription Management repositories.",
│ "Unable to read consumer identity", "", "This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.", "",
│ "LocalRepo                                       162 MB/s | 438 kB     00:00    ", "Red Hat Update Infrastructure 3 Client Configur  39 kB/s | 2.0 kB     00:00    ",
│ "Red Hat Enterprise Linux 8 for x86_64 - AppStre  85 MB/s |  44 MB     00:00    "]}
│
│ PLAY RECAP *********************************************************************
│ 3.88.0.96                  : ok=16   changed=7    unreachable=0    failed=1    skipped=8    rescued=0    ignored=1
│ 35.170.187.39              : ok=16   changed=7    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0

**The terraform.log records until it hits this Sink error, then just repeats the dag/walk while the playbooks finish executing (about 10 minutes):**
2022-06-01T14:11:56.791Z [DEBUG] SCP session complete, closing stdin pipe.
2022-06-01T14:11:56.791Z [DEBUG] Waiting for SSH session to complete.
2022-06-01T14:11:56.792Z [ERROR] scp stderr: "Sink: C0644 0 terraform_1316278683.sh\n"
2022-06-01T14:11:56.792Z [TRACE] applyProvisioners: provisioning null_resource.ExecuteAnsible[0] with "local-exec"
2022-06-01T14:11:58.659Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/null\"] (close)" is waiting for "null_resource.ExecuteAnsible[1]"
2022-06-01T14:11:59.429Z [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/null\"] (close)"
2022-06-01T14:12:03.660Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/null\"] (close)" is waiting for "null_resource.ExecuteAnsible[1]"
...

**Finally finishes here:**
2022-06-01T14:20:03.316Z [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/null\"] (close)" is waiting for "null_resource.ExecuteAnsible[0]"
2022-06-01T14:20:03.804Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for null_resource.ExecuteAnsible[0]
2022-06-01T14:20:03.804Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for null_resource.ExecuteAnsible[0]
2022-06-01T14:20:03.804Z [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2022-06-01T14:20:03.805Z [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 7664
2022-06-01T14:20:03.805Z [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2022-06-01T14:20:03.808Z [TRACE] vertex "null_resource.ExecuteAnsible[0]": visit complete
2022-06-01T14:20:03.808Z [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/null\"] (close)" errored, so skipping
2022-06-01T14:20:03.808Z [TRACE] dag/walk: upstream of "root" errored, so skipping
2022-06-01T14:20:03.808Z [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2022-06-01T14:20:03.809Z [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 7665
2022-06-01T14:20:03.809Z [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2022-06-01T14:20:03.816Z [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2022-06-01T14:20:03.816Z [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2022-06-01T14:20:03.817Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-06-01T14:20:03.818Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/null/3.1.1/linux_amd64/terraform-provider-null_v3.1.1_x5 pid=3941
2022-06-01T14:20:03.818Z [DEBUG] provider: plugin exited

### Terraform Version
terraform --version
Terraform v1.2.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.15.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.2.0

```
...
```

### Terraform Configuration Files

```resource "null_resource" "ExecuteAnsible" {
  count         = var.MultiNode ? 2 : 1
  provisioner "remote-exec" {
    connection {
      host      = "${element(aws_instance.X360Instance.*.public_ip, count.index)}"
      #host     = coalesce(aws_instance.X360Instance[count.index].public_ip, aws_instance.X360Instance[count.index].private_ip)
      user      = var.Secrets ? "${local.secrets.TargetUser}" : var.TargetUser
      private_key       = file(pathexpand("~/.ssh/id_rsa"))
    }
    inline = ["echo 'connected!'"]
  }
  provisioner "local-exec" {
    command = <<EOF
  ansible-playbook --extra-vars "@AnsiblePlaybooks/Variables.json" AnsiblePlaybooks/PostgresInstaller.yml
  EOF
  }
  provisioner "local-exec" {
    command = <<EOF
  ansible-playbook --extra-vars "@AnsiblePlaybooks/Variables.json" AnsiblePlaybooks/X360Installer.yml
  EOF
  }
}
...
```

### Expected Behavior
The terraform should have shown the outputs, but instead showed an error, even though the playbooks executed successfully, as far as I can tell.

### Actual Behavior
Terraform logs a Sink: C0644 error, doesn't record the rest of the actual deployment in the logs, and finally errors out after the execution of the Ansible playbooks

### Steps to Reproduce
I can provide access to my git repo if you want to clone

### References
might be related to these:
- #30647, #30656
@alisdair @jbardin

**Comment by jbardin** [comment]
Hi @sara-hann,

Thanks for filing the issue. Can you provide the exact version of the openssh package on the remote system? I have a feeling that the remote `scp` is simply writing more info in verbose mode than it used to, and that is being caught and logged on stderr. That output however does not change the behavior of the provisioner.

The error you see is not from the `scp` transfer of any files, it's from a `local-exec` provisioner which ran a command with a non-zero exit status. There are a number of error messages in the output, so a non-zero exit status isn't surprising. The process may have completely sufficiently to get the infrastructure up, but whatever resource is used to hold the `local-exec` provisioner should still be marked as tainted and planned to be replaced.

You also mention a cycle here, but I don't see anything in the output about that and the apply completed. Was there more output which wasn't shown here?

Thanks!

**Comment by sara-hann** [comment]
Ah, that makes sense. That gives me a much better idea what to troubleshoot, especially knowing it isn't a bug. Thank you @jbardin . I really appreciate your help.
