### ISSUE TITLE
remote/swift: Support config options in addition to ENV vars

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#3117]
Swift remote can only be configured via set of environment variables:
- `OS_AUTH_URL`
- `OS_USERNAME`
- `OS_TENANT_NAME`
- `OS_PASSWORD`

and config option `path`.

This behaviour is inconsistent (1 config option + 4 ENV vars) and it is a convention that all remotes can be configured via `terraform remote config -backend-config=...` without having to manipulate with any ENV variables. I don't think there's any reason why Swift should be an exception.

**Comment by jtopjian** [comment]
There were recently some updates to the Swift remote and so this should now be fixed. But if not, please let me know!
