### ISSUE TITLE
Explicitly call out that `format` can be used with list/map

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#31175]
### Current Terraform Version

```
1.2.1
```

### Proposal

Update https://www.terraform.io/language/functions/format to explicitly call out that people can use `%v` and `%#v`  to output a list/tuple and map/object as json encoded strings. The current doc page do not mention those [types](https://www.terraform.io/language/expressions/types) so it was very unclear to me that `format` could handle those types.

### References

- https://github.com/hashicorp/terraform/issues/31165

**Comment by laurapacilio** [comment]
Hello! Thank you for the submission :-) I've added in some guidance to the top of the `format` page that I believe addresses this request. let me know what you think - thank you!
