### ISSUE TITLE
azurerm_policy_assignment and azurerm_policy_assignment getting error as provider is not supporting

### ISSUE THREAD

**Issue by nandimandalamrajeshreddy** [hashicorp/terraform#31182]
Hi Team,

We are using the azurerm_policy_assignment and azurerm_policy_assignment .we are getting below error.

Error: Invalid resource type

  on modules\az-cost-vm-sku-policy\cmp_vm_sku_policy.tf line 47, in resource "azurerm_policy_assignment" "CNACO-VMSKU-assignment":
  47: resource "azurerm_policy_assignment" "CNACO-VMSKU-assignment" {

The provider provider.azurerm does not support resource type
"azurerm_policy_assignment".

Error: Invalid resource type

  on modules\az-cost-vm-win-moniter-policy\cmp_vm_linux_policy.tf line 331, in resource "azurerm_policy_assignment" "CNM-LinuxVMPolicy-Assignment":
 331: resource "azurerm_policy_assignment" "CNM-LinuxVMPolicy-Assignment" {

The provider provider.azurerm does not support resource type
"azurerm_policy_assignment".

Error: Invalid resource type

  on modules\az-cost-vm-win-moniter-policy\cmp_vm_linux_policy.tf line 358, in resource "azurerm_policy_remediation" "CNM-LinuxVMPolicy-Remediation":
 358: resource "azurerm_policy_remediation" "CNM-LinuxVMPolicy-Remediation" {

The provider provider.azurerm does not support resource type
"azurerm_policy_remediation".

Thanks,
Rajesh

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by crw** [comment]
Hello @nandimandalamrajeshreddy,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
