### ISSUE TITLE
terraform plan hangs for 20 mins before succeeding

### ISSUE THREAD

**Issue by typerlc** [hashicorp/terraform#3118]
@phinze As requested in #2884, I have opened a new issue to track the behaviour I am experiencing.

Terraform plan is taking so long to complete for the Getting Started build example that I thought it was hanging completely.  But it actually does finish ... after 20mins.

terraform was installed on Mac OSX Yosemite, using brew.

```
$ terraform version
Terraform v0.6.3
```

Here's what a run looks like:

```
$ time terraform plan
Refreshing Terraform state prior to plan...


The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_instance.example
    ami:                      "" => "ami-408c7f28"
    availability_zone:        "" => "<computed>"
    ebs_block_device.#:       "" => "<computed>"
    ephemeral_block_device.#: "" => "<computed>"
    instance_type:            "" => "t1.micro"
    key_name:                 "" => "<computed>"
    placement_group:          "" => "<computed>"
    private_dns:              "" => "<computed>"
    private_ip:               "" => "<computed>"
    public_dns:               "" => "<computed>"
    public_ip:                "" => "<computed>"
    root_block_device.#:      "" => "<computed>"
    security_groups.#:        "" => "<computed>"
    source_dest_check:        "" => "1"
    subnet_id:                "" => "<computed>"
    tenancy:                  "" => "<computed>"
    vpc_security_group_ids.#: "" => "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.

real	20m5.565s
user	0m1.350s
sys	0m1.030s
```

That is 20mins to complete a plan.  I've run with logging on, and here's the output from such a run: http://pastebitch.com/MBfA

My config is straight from https://terraform.io/intro/getting-started/build.html:

```
provider "aws" {
    access_key = "AK................EQ"
    secret_key = "cb....................................0x"
    region = "us-east-1"
}

resource "aws_instance" "example" {
    ami = "ami-408c7f28"
    instance_type = "t1.micro"
}
```

(and yes, the access key and secret key are correctly set).

**Comment by typerlc** [comment]
Just to be sure that the problem wasn't something to do with brew, I downloaded the binaries from https://dl.bintray.com/mitchellh/terraform/terraform_0.6.3_darwin_amd64.zip directly and I am having the same issue with these bins.

**Comment by typerlc** [comment]
As a follow-up ... it's not just plan.  It seems anything that tries to speak with aws is having this issue.

terraform apply took about 25mins to run on this example config.

terraform destroy took 21mins.

**Comment by typerlc** [comment]
Uh oh ... I've found the culprit.  My local Eset AV was filtering all web requests.  Disabling that didn't help.  But when I un-installed it, the times have come down to the expected.  Not sure if there's anything you can take out of this, but I've closed the ticket and sorry for any waste of your time.

**Comment by phinze** [comment]
No worries @typerlc - glad you figured it out!
