### ISSUE TITLE
Unexpected behavior - Terraform state file update

### ISSUE THREAD

**Issue by RachidAZ** [hashicorp/terraform#31192]
Hi Team,
We have been tracking Terraform state, and noticed that when we run **Terraform Plan** (with or without any configuration changes), the state file has been updated 4 times and when running **Terraform Apply**, the state file was updated 3 times. the content of the generated files (we could save them based on Azure blob versioning) is exactly the same, so I am wondering what Terraform is doing exactly by this behavior ( my best guess is that it renames the state file temporary to scan/compare it.. 

### Terraform Version

```
v1.1.7
```

### Debug Output

4 versions of the state file have been generated and tracked by "Azure blob versioning" feature. 

### Expected Behavior

State file should have been updated 0 or 1 time.

### Actual Behavior

State file has been updated 4 times.

### Steps to Reproduce

1. `Enable state configuration to be stored in Azure blob storage` 
2. `Enable storage account versioning` 
3. `run Terraform Plan` 
4. `Browse the versions of the state file, there are multiple generated files (4 when running Plan, 3 when running Apply)` 

### Additional Context

The reason why this behavior is not in our favor, as part of our disaster recovery strategy, we have enabled versioning for the state file, so when we will need to recover the state (rollback to old state), we should not see so many useless versions of same file ( 7 files for every and each terraform plan+apply)

**Comment by jbardin** [comment]
Hi @RachidAZ,

Sorry this is causing some issues for you. What you are describing would be a result of the `azurerm` backend implementation, and as with all remote state storage, the implementation details can very greatly between services.

Terraform guarantees there are no writes to the state during a plan, and that is confirmed by the files remaining identical before and after the plan. It looks like the storage services used by `azurerm` uses the concept of _leases_ to maintain exclusive access to the storage blob, so I suspect that the changes you are seeing is the storage service recording changes in some metadata associated with these leases. With 4 changes per plan, there may be other metadata changes being recorded too, but I cannot say for sure without access to the azure data itself.

Do you know if there is more information available than the number of updates which have happened?

Thanks!

**Comment by RachidAZ** [comment]
Hi @jbardin , Thank you for your intervention, 
Regarding "Terraform guarantees there are no writes to the state during a plan" , does it include the metadata of the state file ( file name, author, version .. ) ? 

I have just re-run again Terraform plan, and here are some information that I hope they can help (taking into account terraform plan was showing some errors related to the access to the resources in question):
-Azure versioning feature captured 1 file as old version ( so we have one current version of the state and one previous version of it ) 
-the version (previous version) captured by Azure versioning feature has exact same MD5 as the current version (current state file)

So this means the content itself wasn't changed, I am not sure what's happening behind the scene, what metadata could have changed ?

**Comment by jbardin** [comment]
No, Terraform strictly considers only the raw bytes it writes to the state as the "state file" in this sense, and does not write a new value for this data during the plan. The remote state storage you are using may record any number of things, either set via the client in Terraform, or inherently in the remote service. One experiment you could do is to see what changes for different operations -- If running a plan with `-lock=false` shows fewer changes, then you know it's the object leases which are being recorded. If doing something like `terraform show` records a change, then you know the service is tracking read access too.

**Comment by RachidAZ** [comment]
@jbardin
-"terraform show" is not recording the changes.
-running "terraform plan -lock=false", indeed this time didn't record the changes !
BUT, I have tried to acquire the lease of the state file and break it from the portal, and Azure service didn't record any changes, so I don't think Azure is recording the leases (not mentioned in their documentation  anyway) , so I believe that it's terraform that's doing some metadata changes when running without -"lock=false".
What do you think ?

**Comment by RachidAZ** [comment]
@jbardin so are you suggesting that this behavior (state file metadata changes) is from the azurerm rather than terraform ? 
It's not a bug right, but I wouldn't call it "expected behavior", maybe the client lock-management needs to be enhanced. 
Thanks.
