### ISSUE TITLE
IPAM Data Source issues

### ISSUE THREAD

**Issue by erkwish** [hashicorp/terraform#31195]
The Attributes Reference that is stated on the IPAM data source page is not all valid for filtering.
As far as I have tested I have only got the locale to work in filter.

For other attributes I have tried to use in filter I have got errors like this:
Error: InvalidFilter: The filter 'address_family' is invalid

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
