### ISSUE TITLE
Automatically suffix zone name on record names (AWS)

### ISSUE THREAD

**Issue by delitescere** [hashicorp/terraform#312]
The `name` property in aws_route53_record resources should not have to be fully qualified by the user.

If the value of the `name` property does not already end with the `name` property of the associated zone, then that zone name should be automatically suffixed.

```
resource "aws_route53_zone" "main" {
  name = "example.com"
}

resource "aws_route53_record" "www" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  ttl = "60"
# the following should be able to be specified simply as "www"
  name = "www.example.com"
  type = "A" 
  records = ["${aws_instance.www.public_ip}"]
}
```

**Comment by catsby** [comment]
Hey @clstokes and @delitescere – #969 should fix this, and was just merged, will go out in the next release. 

Thanks for reporting.

**Comment by delitescere** [comment]
Awesome thanks @catsby :+1:

**Comment by clstokes** [comment]
@catsby :heart_eyes: :shipit:
