### ISSUE TITLE
Error: error creating Kinesis Stream (sample-stream): SerializationException: Invalid message body: Could not decode JSON

### ISSUE THREAD

**Issue by anekar3416** [hashicorp/terraform#31207]
I am trying to create a Kinesis Stream using the terraform in localstack endpoint. But I am getting this below exception:
` Error: error creating Kinesis Stream (sample-stream): SerializationException: Invalid message body: Could not decode JSON: {
   "StreamModeDetails" : {
     "StreamMode" : "ON_DEMAND"
   },
   "StreamName" : "sample-stream"
 }
       status code: 400, request id: XXXXXXXX
`

My sample terraform resource looks like this below:

```
resource "aws_kinesis_stream" "stream_sample" {
  name             = "sample-stream"
  retention_period = 24

  stream_mode_details {
    stream_mode = "ON_DEMAND"
  }

  tags = {
    Name        = "sample-stream"
    Environment = "Test"
    ManagedBy   = "Terraform"
  }
}
```

Can someone help me with this?

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
