### ISSUE TITLE
AWS: Elasticache Redis snapshot_arns cannot be blank

### ISSUE THREAD

**Issue by jonhatalla** [hashicorp/terraform#3121]
This is not a terraform issue, as AWS will not let the `snapshot_arns` param be blank.

However, for certain environments, we have parameters that will preload redis with a snapshot.  For other environments, we would like an empty redis instance.  

A couple of possible solutions:
1. If `snapshot_arns` is empty, don't send the parameter
2. Wrap the `snapshot_arns = ["snapshot_id"]` line in a conditional statement (i know there are a ton of threads already created on conditionals)

My workaround in code is to create 2 blocks for elasticache redis and two route 53 endpoints.  I created a couple of flags which set the count to 1 or 0 depending on what option the environment variables passed in needs.

There is a lot of tooling around this in my code now, but wanted to throw this out there as others might run into this.

**Comment by nTraum** [comment]
Stumbled upon the same issue. If you are looking for a workaround until this is fixed:

Extract the value for the `snapshot_arns` parameter into a variable and let it default to an empty dump file (that you upload to S3). This is ugly, but works for us:

```tf
variable "snapshot_arns" {
  description = "foo bar"
  default     = "arn:aws:s3:::redis-dumps/empty-dump.rdb"
}
```
You still need to use the `split` magic to create an array out of the string (terraform 0.6.8).

**Comment by stack72** [comment]
Hi @jonhatalla 

Can you tell me if this is still a problem? As far as the code goes, if there is no snapshot_arns provided to terraforn, then it will not send them as part of the request:

```
	snaps := d.Get("snapshot_arns").(*schema.Set).List()
	if len(snaps) > 0 {
		s := expandStringList(snaps)
		req.SnapshotArns = s
		log.Printf("[DEBUG] Restoring Redis cluster from S3 snapshot: %#v", s)
	}
```

Notice that we only add to the request if there is more than 1 defined

Paul

**Comment by stack72** [comment]
Hi, I am going to close this out for now. This doesn't seem to be an issue in our nightly acceptance tests. IF this is still causing you issues, then please do let me know! :)
