### ISSUE TITLE
 Error: Unsupported attribute when run terraform plan for azure dashboard and workbooks deployment through azurerm_resource_group_template_deployment

### ISSUE THREAD

**Issue by jayeshkumarpatel2611** [hashicorp/terraform#31228]
Hi,

I have created workbook using azurerm template as output i get workbook id from there and use that workbook id in azure dashboard creation code, it first work perfect but after made any changes when we run terraform plan, it will throws below error.

 Error: Unsupported attribute
on modules\dashboard.tf line 145, in data "template_file" "json-template":
usage_analysis_workbook   = jsondecode(azurerm_resource_group_template_deployment.Usage_Analysis.output_content).workbookId.value
azurerm_resource_group_template_deployment.Usage_Analysis.output_content is "{}"
This object does not have an attribute named "workbookId".

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
