### ISSUE TITLE
"Error: Failed to query available provider packages" 

### ISSUE THREAD

**Issue by karthikeyaonda** [hashicorp/terraform#31242]
PS C:\Karthik\Velmurugan\Azure\Terraform\terraform-on-azure-cloud\terraform-on-azure-cloud-main\10-Azure-Virtual-Network-4Tier\terraform-manifests> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/random versions matching ">= 3.0.0"...
- Finding latest version of hashicorp/azure...
- Finding hashicorp/azurerm versions matching ">= 2.0.0"...
- Installing hashicorp/random v3.3.1...
- Installed hashicorp/random v3.3.1 (signed by HashiCorp)
- Installing hashicorp/azurerm v3.10.0...
- Installed hashicorp/azurerm v3.10.0 (signed by HashiCorp)
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/azure: provider registry
│ registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/azure
│
│ Did you intend to use terraform-providers/azure? If so, you must specify that source address in each module   
│ which requires that provider. To see which modules are currently depending on hashicorp/azure, run the        
│ following command:
│     terraform providers
╵

PS C:\Karthik\Velmurugan\Azure\Terraform\terraform-on-azure-cloud\terraform-on-azure-cloud-main\10-Azure-Virtual-Network-4Tier\terraform-manifests>

**Comment by karthikeyaonda** [comment]
# Terraform Block
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">= 2.0" 
    }
    random = {
      source = "hashicorp/random"
      version = ">= 3.0"
    }
  }
}

# Provider Block
provider "azurerm" {
 features {}          
}

**Comment by karthikeyaonda** [comment]
-Network-4Tier\terraform-manifests> terraform version
Terraform v1.2.2
on windows_amd64
PS C:\Karthik\Velmurugan\Azure\Terraform\terraform-on-azure-cloud\terraform-on-azure-cloud-main\10-Azure-Virtual-Network-4Tier\terraform-manifests>

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
