### ISSUE TITLE
backend/s3: Support assume_role_with_web_identity

### ISSUE THREAD

**Issue by james1miller93** [hashicorp/terraform#31244]
The [s3 backend](https://www.terraform.io/language/settings/backends/s3) currently does not support assuming a role with web identity.

This is currently supported by the [aws provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume_role_with_web_identity-configuration-block) and it would be good to have feature parity across the aws provider configurations.

Personally, I'd like to use this with github actions to federate access to a state backend from deployment pipelines whilst using a separate federated role for running terraform plan and apply operations.

**Comment by bschaatsbergen** [comment]
I'll take a look at this :+1:

**Comment by crw** [comment]
Thanks for the enhancement request!

**Comment by bschaatsbergen** [comment]
There seems to be no support yet for `AssumeRoleWithWebIdentity` in the [awsbase go package](https://pkg.go.dev/github.com/hashicorp/aws-sdk-go-base@v0.7.1) we're using. As support for `AssumeRoleWithWebIdentity` through awsbase is only added to the v2 package it will require a bit of refactoring to make the S3 backend compatible with awsbase/v2. 

What do you suggest to do @jbardin ?

**Comment by bschaatsbergen** [comment]
To properly understand your request, the reason you would like to have this is because you want 2 principles to manage your Terraform lifecycle? 1 for writing state to S3 and 1 for executing the Terraform operations? @crw

**Comment by bschaatsbergen** [comment]
See (currently draft) PR for additional information.

**Comment by haakond** [comment]
Hi, chiming in on the conversation. I believe more and more people in the community are facing the same situation as described by the original poster here. My company is also working on modernizing our pipelines and this capability would be really great to have in place for the Terraform s3 backend.

Has there been any alternative approaches announced since June 2022? Anything I can do to help?

**Comment by james1miller93** [comment]
Any further thoughts on this?

**Comment by alencar** [comment]
Any news on supporting AssumeRoleWithWebIdentity for S3 backend?

**Comment by gdavison** [comment]
This will be resolved when #30443 is complete. It is an active project this quarter.
