### ISSUE TITLE
'diffs didn't match during apply' while embedding Packer into a template_file provisioner

### ISSUE THREAD

**Issue by joescii** [hashicorp/terraform#3125]
# Overview
I am working on [a sample Lift project](https://github.com/joescii/lift-jetty-cluster-aws) which utilizes terraform and packer to deploy itself without any existing AWS infrastructure.  Since packer takes as input the VPC ID, subnet ID, and security group ID; and produces as output an AMI to be used in an Autoscaling Launch Configuration, it would be ideal to run packer embedded during the terraform `apply`.  Without a solution proposed by issues #1586 and #2789, I have resorted to a workaround proposed on the mailing list topic [_Packer+Terraform best practices?_](https://groups.google.com/forum/#!topic/terraform-tool/ij9rEBqByX0).

The approach works by creating a pair of `template_file` resources, calling a script to invoke packer and write the resulting AMI ID into a file, then reading the file as a var.  The terraform config looks like this:

```
resource "template_file" "packer" {
  filename = "/dev/null"
  depends_on = "template_file.packer_runner"
  vars {
    ami = "${file(var.ami_txt)}"
  }
}
resource "template_file" "packer_runner" {
  filename = "/dev/null"
  
  provisioner "local-exec" {
    command = "./bake.sh (...a bunch of variables...)"
  }
}

variable "ami_txt" {
  default = "./ami.txt"
}
```

When running the project against an empty infrastructure, everything works except the creation of the autoscaling config:

```
* aws_launch_configuration.lift_as_conf: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

What is interesting is you can take the AMI ID produced, hard-code it into the terraform config and remove the provisioner...

```
resource "template_file" "packer" {
  filename = "/dev/null"
  depends_on = "template_file.packer_runner"
  vars {
    ami = "ami-0b8a714f"
  }
}
resource "template_file" "packer_runner" {
  filename = "/dev/null"
  
#  provisioner "local-exec" {
#    command = "./bake.sh (...a bunch of variables...)"
#  }
}

variable "ami_txt" {
  default = "./ami.txt"
}
```

Then the `apply` works.  Even more interesting is you can now _undo_ the hard-code/removal of the provisioner and it continues to work!  It's only the bootstrapping case that doesn't work.  Note that you _must_ hard code it once it get it out of this state.  Repeatedly applying the config does not work.

# Sample output
You can see the output from terraform and packer runs [here](https://github.com/joescii/lift-jetty-cluster-aws/tree/terraform-bug/terraform-out).  The copy/paste is verbatim, sans obfuscated passwords.

[`first-run.txt`](https://github.com/joescii/lift-jetty-cluster-aws/blob/terraform-bug/terraform-out/first-run.txt) is the output from running terraform `apply` with a blank state in AWS. (doesn't work)
[`second-run.txt`](https://github.com/joescii/lift-jetty-cluster-aws/blob/terraform-bug/terraform-out/second-run.txt) is the output from running `apply` a second time with no changes. (still doesn't work)
[`after-hard-code.txt`](https://github.com/joescii/lift-jetty-cluster-aws/blob/terraform-bug/terraform-out/after-hard-code.txt) is the output after hard-coding the AMI ID and removing the packer provisioner. (works)
[`final.txt`](https://github.com/joescii/lift-jetty-cluster-aws/blob/terraform-bug/terraform-out/final.txt) is the output after undoing the hard-code and reinstating the packer provisioner. (still works)

# Reproducing 
To help you reproduce this issue, I have created a separate branch called [terraform-bug](https://github.com/joescii/lift-jetty-cluster-aws/tree/terraform-bug).  There I have ripped out the application bundling to make reproducing this easier.  In this branch, packer will only install the JVM but not install the application.  With `terraform` and `packer` on the path, you can simply invoke `deploy.sh`.  

`deploy.sh` will complain until you have the following environment variables set:

```
: ${AWS_ACCESS_KEY_ID:?"Must supply AWS_ACCESS_KEY_ID environment variable"}
: ${AWS_SECRET_ACCESS_KEY:?"Must supply AWS_SECRET_ACCESS_KEY environment variable"}
: ${TF_STATE_BUCKET:?"Must supply TF_STATE_BUCKET environment variable (The S3 bucket to store terraform state)"}
: ${TF_STATE_KEY:?"Must supply TF_STATE_KEY environment variable (The S3 key to store terraform state)"}
: ${DB_USERNAME:?"Must supply DB_USERNAME environment variable"}
: ${DB_PASSWORD:?"Must supply DB_PASSWORD environment variable"}
```

# Versions
This issue can be reproduced with the latest Terraform (0.6.3) and Packer (0.8.6) versions.

**Comment by joescii** [comment]
After more tinkering around, I have found that this issue can be reproduced without packer.  It seems that it is an issue of having a provisioner write to a file, then try to read it back in as a var.  For instance, I can reproduce it by trying to consume an output from [this module](https://github.com/joescii/aws-terraform-modules/tree/master/public-ip).

**Comment by joescii** [comment]
BTW, the keys in those log files have been deleted. :+1:

**Comment by mitchellh** [comment]
I can't get this to reproduce anymore so I do believe we fixed this in the past year. :)
