### ISSUE TITLE
azurerm_spring_cloud_service Doc Update

### ISSUE THREAD

**Issue by gradinDotCom** [hashicorp/terraform#31267]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/spring_cloud_service

Doc Notes on service availability are outdated per recent _General Availability_ announcement.

OLD:
> Note:
At this time Azure Spring Cloud Service is only supported in a subset of regions (including East US, South East Asia, West Europe and West US 2.

NEW: (_cited_ https://docs.microsoft.com/en-us/azure/spring-cloud/faq?pivots=programming-language-java#in-which-regions-is-azure-spring-apps-enterprise-tier-available)
> Note:
At this time, Azure Spring Cloud Service is supported in East US, East US 2, Central US, South Central US, North Central US, West US, West US 2, West US 3, West Europe, North Europe, UK South, Southeast Asia, Australia East, Canada Central, UAE North, Central India, Korea Central, East Asia, South Africa North, Brazil South, and France Central. Availability may change and can be confirmed at https://docs.microsoft.com/en-us/azure/spring-cloud/faq?pivots=programming-language-java#in-which-regions-is-azure-spring-apps-enterprise-tier-available

**Comment by crw** [comment]
Hello @gradinDotCom, this appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. The GitHub issues here are monitored only by a few core maintainers. Thanks!

**Comment by gradinDotCom** [comment]
I'll see what I can do. The provider issue log doesn't _seem_ to support basic doc mentions like this.
