### ISSUE TITLE
Multiple tags applied as list - aws_dynamodb_tag

### ISSUE THREAD

**Issue by nikhilbagdi** [hashicorp/terraform#31270]
### Current Terraform Version

```
Terraform v1.2.2
```

### Use-cases

Multiple tags can be applied over the AWS DynamoDB Table.

### References

We can apply multiple tags using terraform resource [aws_dynamodb_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table) in list. Same should done for module [aws_dynamodb_tag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_tag).

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
