### ISSUE TITLE
Unable to attach multiple policies to "aws_iam_role_policy_attachment" resource in Terraform via locals file 

### ISSUE THREAD

**Issue by uceimmp** [hashicorp/terraform#31281]
### Terraform Version

```
1.1.2
```

### Terraform Configuration Files

```terraform
locals {
    policies = join(", ", [aws_iam_policy.datadog_s3_bucket_policy.arn, aws_iam_policy.datadog_integration_policy.arn])
}

resource "aws_iam_role_policy_attachment" "datadog_s3_bucket_policy" {
  role      = aws_iam_role.datadog_integration_role.name
  policy_arn = local.policies
}
```

### Expected Behavior

Plan was successful and should have applied properly

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
