### ISSUE TITLE
Show elapsed time in the progress output using a consistent number of digits for all events

### ISSUE THREAD

**Issue by dotNetCory** [hashicorp/terraform#31285]
Can you just appease my OCD, when doing the time elapsed, can you make '0s', look like '00s' so it lines up?
I know its ridiculous but it would just stop triggering me every single day I have to use terraform
![image](https://user-images.githubusercontent.com/60733518/174777825-bd2d46fe-ed54-4a50-9c68-2a9c35decaf4.png)

**Comment by kmoe** [comment]
The minute-second time format here is the default produced by Go's `time` package, so we'd need a little extra code to transform each `m0s` into `m00s`.

Thanks for the issue, and for your confidence in the Terraform Core team's aesthetic sensibilities. While I certainly see what you mean in the example you posted, I do find the apparent indentation of the "0s" lines serves as a useful marker for the whole-minute intervals, in a way that may actually increase overall readability in an elegant combination of aesthetics and ergonomics. What do you think?

**Comment by crw** [comment]
Hello! I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!

One thing I'll mention, @kmoe, is that the minute value would have to be zero padded to perfectly create the indentation effect you describe. I'm assuming that zero padding the minute value would be the same effort as zero padding the seconds value.
