### ISSUE TITLE
Precondition/Postcondition not accepted on resources with existing lifecycle block

### ISSUE THREAD

**Issue by marciogmorales** [hashicorp/terraform#31303]
### Terraform Version

```
Terraform v1.2.3
on darwin_arm64
```

### Terraform Configuration Files

```
resource "aws_launch_template" "ecs_container_instances" {
  name                   = var.launch_template_name
  image_id               = data.aws_ami.ecs_optimized_ami.id
  instance_type          = var.ec2_instance_types
  vpc_security_group_ids = [aws_security_group.ecs_container_instances_ingress.id]
  update_default_version = true

  lifecycle {
    postcondition {
      condition = CONDITION
      error_message = "MESSAGE."
    }

  lifecycle {
    create_before_destroy = true
  }

```

### Expected Behavior
 Precondition/Postcondition acceptance on resources with existing lifecycle block.

### Actual Behavior
As an example on AWS Launch Templates where the lifecycle block already exists to define some configurations, if the new Precondition or Postcondition is added on the resource level, within the existing lifecycle block, the following error occurs: 
<p><p>
 on main.tf line 190, in resource "aws_launch_template" "ecs_container_instances":
│  190:   precondition {
│ 
│ Blocks of type "precondition" are not expected here.

However, if adding a second lifecycle block within the resource to specify the condition, I receive the following error: 
<p><p>
│   on main.tf line 193, in resource "aws_launch_template" "ecs_container_instances":
│  193:   lifecycle {
│ 
│ This resource already has a lifecycle block at main.tf:183,3-12.

### Steps to Reproduce
 terraform plan

### Additional Context
No

**Comment by jbardin** [comment]
Hi @marciogmorales,

A resource is allowed to have at most 1 lifecycle block defined, which is the reason for the error. You can put any combination of the lifecycle arguments within the single lifecycle block, so your example would be correctly written as:

```
  lifecycle {
    postcondition {
      condition = CONDITION
      error_message = "MESSAGE."
    }

    create_before_destroy = true
  }
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by marciogmorales** [comment]
@jbardin Please, read the post. The reason isn't that one. 

I'm specifying the pre/post condition on the aws_launch_template resource and it says the precondition are not expected in the existing lifecycle block.

**on main.tf line 190, in resource "aws_launch_template" "ecs_container_instances": │ 190: precondition { │ │ Blocks of type "precondition" are not expected here.**

**Comment by marciogmorales** [comment]
```
resource "aws_launch_template" "ecs_container_instances" {
  name                   = var.launch_template_name
  image_id               = data.aws_ami.ecs_optimized_ami.id
  instance_type          = var.ec2_instance_types
  vpc_security_group_ids = [aws_security_group.ecs_container_instances_ingress.id]
  update_default_version = true

  lifecycle {
    postcondition {
      condition = CONDITION
      error_message = "MESSAGE."

    create_before_destroy = true
    }
```
