### ISSUE TITLE
Error: Invalid provider configuration reference

### ISSUE THREAD

**Issue by nimblenitin** [hashicorp/terraform#31313]
is there any workaround available to use variable in provider something like below. If yes please let me know how to do it. Currently terraform is not allowing to use variable in provider name for module. I want to create role in each member account user provides; that is my goal here. User will provide the alias which I will use to create role.

```
providers = {
    aws = "${lookup(var.names, element(var.accounts, count.index))}"
  }

```

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
