### ISSUE TITLE
From Terraform cloud not able to access private EKS cluster

### ISSUE THREAD

**Issue by s9r-5** [hashicorp/terraform#31311]
### Terraform Version

```
1.1.8
```

### Terraform Configuration Files

```terraform
N/A
```

**Comment by s9r-5** [comment]
I am trying to deploy few addons on eks cluster but not able to because from terraform cloud it's not possible to connect private cluster.
Error: Error making request: Get "https://*******************.us-east-2.eks.amazonaws.com/healthz": dial tcp 3.00.00.00:443: connect: connection timed out

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
