### ISSUE TITLE
Unknown workspace sub-command should bail with non-zero exit code

### ISSUE THREAD

**Issue by bengaywins** [hashicorp/terraform#31317]
### Terraform Version

```
Terraform v1.2.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.20.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
```

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Expected Behavior
If I run `terraform workspace seleect foo`, it should bail with non-zero exit code.

### Actual Behavior
It bails with a 0 exit code.

### Steps to Reproduce
1. Run `terraform workspace seleect foo`
2. `echo $?`

### Additional Context
I had this misspelled in a Makefile which is why I caught this. It just continues instead of failing.

### References
N/A

**Comment by bengaywins** [comment]
The offending issue is [here](https://github.com/hashicorp/terraform/blob/main/internal/command/workspace_command.go#L25).

**Comment by crw** [comment]
Thanks for this report!
