### ISSUE TITLE
aws_launch_template and aws_eks_node_group issue

### ISSUE THREAD

**Issue by ivan-at-riva** [hashicorp/terraform#31320]
I am running into some odd issue with `aws_eks_node_group` and more over `aws_launch_template`. Terraform is in a cycle which has always the same plan even after applying it. The output is below:

`terraform apply/paln`
```
  # .........aws_eks_node_group.this will be updated in-place
  ~ resource "aws_eks_node_group" "this" {
        id                     = "....................."
        # (17 unchanged attributes hidden)

      ~ launch_template {
            id      = "lt-....."
            name    = "..............."
          ~ version = "2" -> (known after apply)
        }

        # (3 unchanged blocks hidden)
    }

  # ..........aws_launch_template.this will be updated in-place
  ~ resource "aws_launch_template" "this" {
      ~ default_version         = 2 -> (known after apply)
        id                      = "lt-......"
      ~ latest_version          = 2 -> (known after apply)
        name                    = "........."
        }
        # (7 unchanged attributes hidden)
        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

So it constantly tries to set default_version to 2 and latest_version to 2 (I verified in the aws console it is already set to 2 and it is already 2 as a default). In my module I have:

for `aws_eks_node_group`
```
  launch_template {
    id      = aws_launch_template.this.id
    version = aws_launch_template.this.latest_version
  }
  ```
  
  and for `aws_launch_template`
  
  ```
  resource "aws_launch_template" "this" {
  name_prefix            = local.name_label
  update_default_version = true
  ```
  
  terraform versions are:
  ```
  terraform version
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.12.1
```

I can do `terraform state show` on both resources and I can see it is using the 2 version:

```
    launch_template {
        id      = "lt-...."
        name    = "...."
        version = "2"
    }
    
    and
    
        default_version         = 2
    disable_api_termination = false
    id                      = "lt-...."
    latest_version          = 2
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
