### ISSUE TITLE
extended_auditing_policy block is not working in azurerm_mssql_database resource.

### ISSUE THREAD

**Issue by PriyanshuKatiyarSecurrency** [hashicorp/terraform#31338]
### Terraform Version

```
v1.2.1
```

### Terraform Configuration Files

```terraform
resource "azurerm_mssql_database" "test" {
  name           = "acctest-db-d"
  server_id      = azurerm_mssql_server.example.id
  collation      = "SQL_Latin1_General_CP1_CI_AS"
  license_type   = "LicenseIncluded"
  max_size_gb    = 4
  read_scale     = true
  sku_name       = "S0"
  zone_redundant = true

  extended_auditing_policy {
    storage_endpoint                        = azurerm_storage_account.example.primary_blob_endpoint
    storage_account_access_key              = azurerm_storage_account.example.primary_access_key
    storage_account_access_key_is_secondary = true
    retention_in_days                       = 6
  }


  tags = {
    foo = "bar"
  }
```

### Actual Behavior
```
│ Error: Unsupported block type
│ 
│   on main.tf line 37, in resource "azurerm_mssql_database" "test":
│   37:   extended_auditing_policy {
│ 
| Blocks of type "extended_auditing_policy" are not expected here.
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
