### ISSUE TITLE
Terraform jsonencode unable encode string with spaces

### ISSUE THREAD

**Issue by efernandes-dev-ops** [hashicorp/terraform#31342]
### Terraform Version

```
Terraform v1.2.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.19.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
```

### Terraform Configuration Files

```terraform

locals {

tags = {
    "Owner" = "test"
    "Product"  = "core-infra"
    "DataClassification" = "internal"
    "DataClassificationVersion" = "v2021-05-13DRAFT"
    "Function" = "AWS Accounts Creation"
}

tags2 =  jsonencode(local.tags)

}

```

### Expected Behavior

The value for tags2 should be 

```
'{"DataClassification":"internal","DataClassificationVersion":"v2021-05-13DRAFT","Function":"AWS Accounts Creation","Owner":"test","Product":"core-infra"}'
```

### Actual Behavior

The following is returned/set for tags2

```
'{"DataClassification":"internal","DataClassificationVersion":"v2021-05-13DRAFT","Function":"AWS'
│ Accounts 'Creation","Owner":"test","Product":"core-infra"}'
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

You'll need to output/pass the local.tags to a resource in order to visualise the json.

**Comment by jbardin** [comment]
Hi @efernandes-dev-ops,

Can you show an example of how you are using the `tags2` value? Terraform is creating exactly the string you have under `Expected Behavior`, so I suspect this is something being done within the provider rather than Terraform.

Thanks!

**Comment by efernandes-dev-ops** [comment]
@jbardin Thanks for looking at this, I realised this was a bash issue. 

Using terraform console helped me debug the local variable :)
