### ISSUE TITLE
Make it possible to have optional providers

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/terraform#31340]
### Current Terraform Version
```
Terraform v1.2.3
```
### Use-cases
In order to avoid locking our infrastructure into a single cloud provider we at [Status](https://status.im/) try to deploy across multiple providers. In order to do this we have a Terraform module that combines three different providers into one resources:
https://github.com/status-im/infra-tf-multi-provider

This allows for easily deploying the same fleet across multiple providers. The issue with this approach is that if counts for individual submodules are set to 0 because we want to skip a certain provider Terraform still requires a `provider` to be defined. For example in https://github.com/status-im/infra-tf-multi-provider/pulls/1 Hetzner Cloud support is being added, but if `he_count` is set to zero Terraform still fails with:
```
│ Error: Missing required argument
│ 
│ The argument "token" is required, but was not set.
```
Because it is a required attribute for the `hcloud` provider:
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs#token

### Attempted Solutions
The only solution I can see is providing `provider` blocks with credentials for all supported cloud providers, even in fleet configurations that do not use given providers. That is not an optimal solution from a security perspective.

### Proposal
Seems to me, since the whole module that uses `hcloud` provider resources is made optional with a `count`, there should be no need to evaluate anything related to that provider. But I do not know the implementation details.

### References

* https://github.com/status-im/infra-tf-multi-provider/pull/1
* https://github.com/status-im/infra-tf-multi-provider/pull/2
* https://discuss.hashicorp.com/t/ability-to-specify-optional-provider-ignore-unused-providers/8482

**Comment by jbardin** [comment]
Hi @jakubgs,

Since this is just the zero case of #19932, we can track any possible options via that issue.

Thanks!
