### ISSUE TITLE
AWS Transfer SFTP Internet Facing

### ISSUE THREAD

**Issue by z-mani** [hashicorp/terraform#31352]
### Current Terraform Version

```
1.1.7
```

### Use-cases
I’m setting up an SFTP server using Terraform in AWS. I am wanting to use VPC type SFTP server using internet facing. When setting this up in AWS using UI there is an option to use internet facing or internal, however I don’t see this option when using Terraform? If I have overlooked this option please let me know.

Thanks

**Comment by crw** [comment]
Hello @z-mani, if you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

If you believe this to be a bug or issue with the AWS provider, you can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. 

Thanks!

**Comment by z-mani** [comment]
Hi @crw, thanks for the reply. I have actually posted it in the community forum nearly two weeks ago now and haven't received any reply. 
https://discuss.hashicorp.com/t/aws-transfer-sftp-internet-facing/40947

I am unsure now where to ask this question or get answers for it?

Thanks

**Comment by crw** [comment]
You can check the AWS provider repository to see if there are any open issues on this, the omission of this option may be a known missing feature. I've also promoted this ticket a bit internally, hopefully someone will pop in and direct you to the right place.
