### ISSUE TITLE
Invalid resource instance data in state : data could not be decoded from the state: unsupported attribute "assertions"

### ISSUE THREAD

**Issue by shankargoudapatil** [hashicorp/terraform#31373]
Hi there,
  I was getting below error, while migrating from terraform version 0.12.24 to 0.13.0 , when I checked my terraform state file, its pointing towards assertions block so If I manually remove this code from state file, then its working as expected, but in ideally case we are not supposed to modify our terraform state file, so I was wondering are there any other solutions or approaches to fix this issue ?                                                                                                     "assertion": [
              {
                "operator": "is",
                "property": "",
                "target": "200",
                "targetjsonpath": [],
                "type": "statusCode"
              }
            ],                                                                                                                                                                                              Error: Invalid resource instance data in state
  on datadog/sythentics/recon_health_check_test_1.tf line 12:
  12: resource "datadog_synthetics_test" "egw_recon_sythentic_health_check_monitor" {
Instance
module.datadog.module.sythentics.datadog_synthetics_test.egw_recon_sythentic_health_check_monitor[0]
data could not be decoded from the state: unsupported attribute "assertions"

-->

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
