### ISSUE TITLE
No way to create a google_compute_forwarding_rule for a google_container_cluster

### ISSUE THREAD

**Issue by sorccu** [hashicorp/terraform#3137]
Hi,

Maybe I'm missing something, but since `google_compute_forwarding_rule` requires its `target` to be a pool URL, there doesn't seem to be any way to create a forwarding rule for a `google_container_cluster`. The cluster resource (or the API) creates groups and pools behind the scenes, but only exposes `instance_group_urls` when it's done. I checked the source code and there was nothing undocumented there either.

While this behavior kind of makes sense since the API itself doesn't seem to expose the pool URLs, it seems that it's pretty much impossible to interact with a `google_container_cluster` from any other resource type, thus making it unautomatable.

Surely I can't be the only one using `google_container_cluster`? Is this a known issue or is there some non-obvious workaround that I'm missing?

**Comment by radeksimko** [comment]
Hi @sorccu 
I absolutely agree with you and understand the pain. I was asking myself exactly the same question.

The problem with high-level GKE api, which is creating many other resources under the hood is not just `google_compute_forwarding_rule`.

When I was creating GKE resource (about a month ago), there was no update API at all, then couple days before it almost got merged into terraform upstream, suddenly update API came out, but only supported K8S version attribute. Today it has one extra attribute that we don't support in TF resource yet - monitoring:
https://cloud.google.com/container-engine/reference/rest/v1/projects.zones.clusters/update#ClusterUpdate

e.g. There is still no way to change number of nodes in the cluster when the GKE cluster is up.

I do not know what are the plans of the team behind GKE API - whether they're going to allow us to control underlying resources and transparently get details of these or whether they really want us to use other APIs.

I feel how painful this is, but also how fresh the product is - I anticipate things to change.

@sparkprime @lwander Any suggestions on whether it's worth investing time into controlling/exposing sub-resources like forwarding rule & instance group or whether it's going to be covered in the GKE API at some point?

**Comment by sorccu** [comment]
I considered creating everything myself by using the regular resources, but realized that I would miss out on the free Google-managed Kubernetes master. So that option is not great either :(

**Comment by lwander** [comment]
Hi @radeksimko,

I'm going to reach out to the GKE API guys to see what they say.

**Comment by aronchick** [comment]
Hi --

Thanks for your support! A few items here:

* The good news is the scaling node issue you're talking about is being worked on momentarily, and horizontal autoscaling has been checked into master - https://github.com/kubernetes/kubernetes/pull/12859. There are lots more functions coming soon. 
* Between now and then, per @cjcullen, we provide the MIG URL in our GetCluster response. Then you can use that to resize your cluster.
* Forwarding rules is out of our direct scope, as we see it - we'd love to hear more about the specific use case you'd like to see here.

Hope that helps! Ping me directly at aronchick@goog if you'd like to talk more about this.

**Comment by sorccu** [comment]
If forwarding rules are out of scope, how would one set up rules to direct HTTP/HTTPS traffic to the new container cluster (without doing it by hand)? I get that you'll have to deploy a pod first before anything actually shows up anyway, but I don't really see how it would be that much different from regular instances - they'd take a while to start up too.

**Comment by sorccu** [comment]
Oh... I guess a Service would do it for you behind the scenes?

**Comment by aronchick** [comment]
Sorry, yep - that's exactly right. Just point it at a service, and "magic happens" :)

**Comment by aronchick** [comment]
Actually, to be crystal clear, if you're using GKE, or GCE, or AWS, all you should do is create the service endpoint, and add "Loadbalancer" to the definition, and it'll handle the forwarding rule maintenance for you.

**Comment by sparkprime** [comment]
Shall I close this, as best practice is currently to let Kubernetes manage these extra resources and not to do it via Terraform?
