### ISSUE TITLE
It would be nice to be able to export the Trasnsit Gateway Attachment ID with aws_dx_gateway_association

### ISSUE THREAD

**Issue by yamazoon0207** [hashicorp/terraform#31370]
Trasnsit Gateway Attachment ID is not exported in aws_dx_gateway_association
Trasnsit Gateway Attachment ID must be entered as an argument in aws_ec2_transit_gateway_route_table_association
It would be nice to be able to export the Trasnsit Gateway Attachment ID with aws_dx_gateway_association

**Comment by kmoe** [comment]
Thanks for the issue. Resources such as `aws_dx_gateway_association` are the responsibility of the AWS provider, not Terraform Core. Please open an issue in https://github.com/hashicorp/terraform-provider-aws instead.
