### ISSUE TITLE
Error: Failed to download module

### ISSUE THREAD

**Issue by davewburns** [hashicorp/terraform#31388]
### Terraform Version

```
Terraform v1.2.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.23.0  
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

### Terraform Configuration Files

```main.tf
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

data "aws_availability_zones" "available" {
  state = "available"
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.64.0"

  cidr = "10.0.0.0/16"

  azs             = data.aws_availability_zones.available.names
  private_subnets = ["10.0.101.0/24", "10.0.102.0/24"]
  public_subnets  = ["10.0.1.0/24", "10.0.2.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = false

  tags = {
    project     = "project-alpha",
    environment = "dev"
  }
}

module "app_security_group" {
  source  = "terraform-aws-modules/security-group/aws//modules/web"
  version = "3.17.0"

  name        = "web-sg-project-alpha-dev"
  description = "Security group for web-servers with HTTP ports open within VPC"
  vpc_id      = module.vpc.vpc_id

  ingress_cidr_blocks = module.vpc.public_subnets_cidr_blocks

  tags = {
    project     = "project-alpha",
    environment = "dev"
  }
}

module "lb_security_group" {
  source  = "terraform-aws-modules/security-group/aws//modules/web"
  version = "3.17.0"

  name        = "lb-sg-project-alpha-dev"
  description = "Security group for load balancer with HTTP ports open within VPC"
  vpc_id      = module.vpc.vpc_id

  ingress_cidr_blocks = ["0.0.0.0/0"]

  tags = {
    project     = "project-alpha",
    environment = "dev"
  }
}

resource "random_string" "lb_id" {
  length  = 3
  special = false
}

module "elb_http" {
  source  = "terraform-aws-modules/elb/aws"
  version = "2.4.0"

  # Ensure load balancer name is unique
  name = "lb-${random_string.lb_id.result}-project-alpha-dev"

  internal = false

  security_groups = [module.lb_security_group.this_security_group_id]
  subnets         = module.vpc.public_subnets

  number_of_instances = length(module.ec2_instances.instance_ids)
  instances           = module.ec2_instances.instance_ids

  listener = [{
    instance_port     = "80"
    instance_protocol = "HTTP"
    lb_port           = "80"
    lb_protocol       = "HTTP"
  }]

  health_check = {
    target              = "HTTP:80/index.html"
    interval            = 10
    healthy_threshold   = 3
    unhealthy_threshold = 10
    timeout             = 5
  }

  tags = {
    project     = "project-alpha",
    environment = "dev"
  }
}

module "ec2_instances" {
  source = "./modules/aws-instance"

  instance_count     = 2
  instance_type      = "t2.micro"
  subnet_ids         = module.vpc.private_subnets[*]
  security_group_ids = [module.app_security_group.this_security_group_id]

  tags = {
    project     = "project-alpha",
    environment = "dev"
  }
}

```

### Expected Behavior

Following tutorial here: [https://learn.hashicorp.com/tutorials/terraform/variables?in=terraform/certification-associate-tutorials](https://learn.hashicorp.com/tutorials/terraform/variables?in=terraform/certification-associate-tutorials)
 and trying the ```terraform init``` command to initialize configuration
### Actual Behavior

Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/security-group/aws 3.17.0 for app_security_group...
Downloading registry.terraform.io/terraform-aws-modules/elb/aws 2.4.0 for elb_http...
Downloading registry.terraform.io/terraform-aws-modules/security-group/aws 3.17.0 for lb_security_group...
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 2.64.0 for vpc...
╷
│ Error: Failed to download module
│
│ Could not download module "app_security_group" (main.tf:36) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0':
│ C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127: C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
│ Could not download module "elb_http" (main.tf:73) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-elb?ref=v2.4.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-elb?ref=v2.4.0': C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127:
│ C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
│ Could not download module "lb_security_group" (main.tf:52) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0':
│ C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127: C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
│ Could not download module "vpc" (main.tf:17) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.64.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.64.0': C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127:
│ C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
│ Could not download module "app_security_group" (main.tf:36) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0':
│ C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127: C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
│ Could not download module "app_security_group" (main.tf:36) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0':
│ C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127: C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
│ Could not download module "app_security_group" (main.tf:36) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0':
│ C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127: C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
│ Could not download module "elb_http" (main.tf:73) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-elb?ref=v2.4.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-elb?ref=v2.4.0': C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127:
│ C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
│ Could not download module "app_security_group" (main.tf:36) source code from "git::https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0": error downloading 'https://github.com/terraform-aws-modules/terraform-aws-security-group?ref=v3.17.0':
│ C:\Users\daburns\AppData\Local\Programs\Git\cmd\git.exe exited with 127: C:/Users/daburns/AppData/Local/Programs/Git/mingw64/libexec/git-core\git-submodule: line 637: cmd_: command not found
│ .
╵

╷
│ Error: Failed to download module
│
### Steps to Reproduce

1. 'terraform init`
### Additional Context

I'm new to using terraform so the only unusual thing I can think of is that I used Chocolatey to install terraform.  I did read about turning off ASLR but it is already completely off in my system

**Comment by apparentlymart** [comment]
Hi @davewburns! Sorry for this wall of errors, and thanks for reporting it.

I think what I'm understanding from these errors is that the repository you are referring to contains a Git submodule -- that is, the repository has an embedded link to content from another repository -- and so the `git` command is trying to run the `git-submodule` helper script to initialize that submodule. That is: it is trying to recursively fetch the submodule code so that the module package will be complete.

Can you confirm whether there is a program or script at `C:\Users\daburns\AppData\Local\Programs\Git\mingw64\libexec\git-core\git-submodule` on your computer? That seems to be what Git is trying to run.

If the program isn't there then I think the next step would be to figure out why it is missing and install it. For example, perhaps your mingw64 installation needs some additional software added.

If the file _is_ present then I think my next question would be about why Git is constructing a path that seems to contain a mixture of forward slashes and backslashes as path separators. If I'm remembering correctly, windows will allow either but requires being consistent in a particular path about which to use. If so, it might be necessary to somehow reconfigure git to construct that path with all forward or all back slashes, but I'm not sure how to do that.

In both cases unfortunately this seems to be a Git error rather than a Terraform error, so I'm afraid I'm not sure what exactly to suggest beyond trying to interpret the error messages Terraform is returning to report the errors from Git. When you install from a Git repository like this, Terraform internally runs `git clone ...` to prepare the module package directory, and so unfortunately this relies on your system already having a working installation of Git for Terraform to run.

**Comment by davewburns** [comment]
Hi @apparentlymart. I kinda figured it was more a git issue than a Terraform one. there is sh script in the file path you mentioned above.  I will go down that path to try and resolve my issue.
