### ISSUE TITLE
Plan/Apply output add more detail regarding which resource types will be created/destroyed

### ISSUE THREAD

**Issue by wesleyjconnorsesame** [hashicorp/terraform#31397]
### Current Terraform Version
```
Terraform v1.2.3
on linux_amd64
```

### Use-cases
When a plan or apply finishes it describes the number and type of operations that will be performed 
For example
`Plan: 259 to add, 3 to change, 300 to destroy.`

In the event of a large number of modifications, it can be difficult to keep track of what operations are happening to what resources
The individual changes are detailed in the logs, but when there are some hundreds of changes, its very difficult to track exactly whats happening
A detailed operation summary at the resource level (in addition to the current summary) would give a better insight into proposed changes

### Attempted Solutions
Attempts (unsuccessful) at this point have been to parse the json output and turn it into a github plugin

### Proposal

The existing plan summary would be enhanced to something similar to the following

Plan: 259 to add, 3 to change, 300 to destroy.
* Resource - some_resource_type
  *  Plan: 259 to add, 0 to change, 0 to destroy.
* Resource - another_resource_type
  *  Plan: 0 to add, 0 to change, 300 to destroy.
* Resource - yet_another_resource_type
  *  Plan: 0 to add, 3 to change, 0 to destroy.

This will give users a more easily readable overview of the expected operations, to ensure they align with expectations

**Comment by crw** [comment]
Hi @wesleyjconnorsesame, I'm cleaning up old issues and I see this one did not receive a response. I am going to close this issue now, please let me know if you believe this action to be taken in error. Thanks!
