### ISSUE TITLE
AWS: Elasticache redis snapshot created from elasticache snapshot

### ISSUE THREAD

**Issue by jonhatalla** [hashicorp/terraform#3140]
Currently we can create a redis cluster from an s3 snapshot (with arns s3 path).  However with automated backups, those are stored in elasticache-s3 - and are created with a different parameter endpoint.  

http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/ManagingSnapshots.Restoring.html

`elasticache-create-cache-cluster my-restored-redis --snapshot-name my-manual-snapshot`

**Comment by stack72** [comment]
Hi @jonhatalla 

It has been a long time coming - my apologies for this - but PR incoming for this functionality now. It should make Terraform 0.7.2!

Paul

**Comment by mfrr1118** [comment]
Hi @stack72,
do you have an estimate date for `0.7.2`?

Thanks!

**Comment by stack72** [comment]
@mfrr1118 No official date but soon ™️ :)

**Comment by mfrr1118** [comment]
@stack72 you guys are killing it. Thanks!

**Comment by stack72** [comment]
Hi @jonhatalla / @mfrr1118 

This was released in terraform 0.7.2 via #8419

**Comment by mfrr1118** [comment]
Thanks! 💥💥💥

**Comment by jonhatalla** [comment]
thanks! seems to be awesome now
