### ISSUE TITLE
Drift tutorial mentions port 80

### ISSUE THREAD

**Issue by codedread** [hashicorp/terraform#31400]
Where do I file Tutorial/Docs bugs?

In https://learn.hashicorp.com/tutorials/terraform/resource-drift shouldn't

> your original security group allowing access on port 80 is no longer attached to your EC2 instance

instead be

> your original security group allowing access on port 22 (SSH) is no longer attached to your EC2 instance

**Comment by apparentlymart** [comment]
Hi @codedread! Thanks for reporting this.

Unfortunately the tutorial text _itself_ isn't in any public repository, but for this particular one I suppose you could open an issue in [the repository that the tutorial relies on](https://github.com/hashicorp/learn-terraform-drift-management), which will then make your report visible to the folks responsible for that tutorial.

**Comment by crw** [comment]
Thanks for opening the linked issue!
