### ISSUE TITLE
Error waiting for Creating CloudFunctions Function: timeout while waiting for state to become 'done: true'

### ISSUE THREAD

**Issue by liux13** [hashicorp/terraform#31407]
### Terraform Version

```
v0.14.9

providers
google = "= 4.18.0"
google-beta = "= 4.18.0"
```

### Terraform Configuration Files

```terraform
resource "google_cloudfunctions_function" "main" {
+ available_memory_mb = 256
+ description = "Cloud Function to create flattened BQ tables"
+ entry_point = "create_flattened_view"
+ environment_variables = {
+ "DATA_PROJECT" = "ygt-v2-synth-data"
+ "FHIR_DATASET" = "final_fhir"
+ "FLATTENED_FHIR_DATASET" = "final_fhir_flattened"
}
+ https_trigger_url = (known after apply)
+ id = (known after apply)
+ ingress_settings = "ALLOW_INTERNAL_ONLY"
+ max_instances = 0
+ name = "flattening-function"
+ project = "ygt-v2-synth-intake"
+ region = "us-central1"
+ runtime = "python37"
+ service_account_email = "[function-runner@ygt-v2-synth-intake.iam.gserviceaccount.com](mailto:function-runner@ygt-v2-synth-intake.iam.gserviceaccount.com)"
+ timeout = 540
+ vpc_connector = "projects/ygt-v2-networks/locations/us-central1/connectors/vpc-connector"
+ vpc_connector_egress_settings = "ALL_TRAFFIC"
+ event_trigger {
+ event_type = "google.pubsub.topic.publish"
+ resource = "projects/ygt-v2-synth-intake/topics/fhirflattening"
+ failure_policy {
+ retry = (known after apply)
}
}
+ source_repository {
+ deployed_url = (known after apply)
+ url = "https://source.developers.google.com/projects/hcls-hdc-artifacts-test/repos/hdc-cloud-functions/fixed-aliases/latest"
}
}
```

### Debug Output

Error: Error waiting for Creating CloudFunctions Function: timeout while waiting for state to become 'done: true' (last state: 'done: false', timeout: 5m0s)

on .terraform/modules/flattening_cf/modules/repository-function/main.tf line 17, in resource "google_cloudfunctions_function" "main":
17: resource "google_cloudfunctions_function" "main" {

### Expected Behavior

No error

### Actual Behavior

tf-apply failed due to the error above quite often in our projects

But the Cloud Function is actually deployed. It looks it timed out because CF was not deployed when terraform was checking.

### Steps to Reproduce

terraform apply

### References

We filed another bug with provider [here](https://github.com/hashicorp/terraform-provider-google/issues/12017) to see the discussion.

**Comment by jbardin** [comment]
Hi @liux13,

That type of error need to be handled at the provider level. If the resource has failed to complete by the time allotted in the provider and the provider returns an error, there is nothing more that Terraform can do. If some instance information is not available to the provider before the timeout, the provider has to abort and signal terraform to stop further processing. The only solution here is for the provider to change the conditions which are checked for instance creation if they are incorrect (which doesn't seem the case if this does work most of the time), or increase the timeout for resources which may take extra time to create.

The providers do have an open request to allow an errored resource to be stored in the state with the expectation that it will become available later. However, even if this were implemented in a future version, it would not prevent the error you have seen, it would only allow provisioning to continue without replacing the errored instance.
