### ISSUE TITLE
Unable to create Azure API management resource

### ISSUE THREAD

**Issue by venkatadorisala** [hashicorp/terraform#31416]
I am trying to create  Azure API Management resource in a resource group which has 16 tags already attached to it.  But terraform failing with error.

```
AzureRM: 3.13.0
Terraform : 1.24.0
```

Snippet:
```
resource "azurerm_api_management" "platform" {
  name                = local.apim_name
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = var.region_name
  publisher_name      = var.gateway_publisher_name
  publisher_email     = var.gateway_publisher_email

  sku_name = var.gateway_sku_name

  identity {
    type = "SystemAssigned"
  }

  protocols {
    enable_http2 = true
  }

  lifecycle {
    prevent_destroy = true
  }
}

```

upon `terraform apply` i get below error.

`│Error: creating/updating Api Management: (Service Name "api-ms-dev-xxxx-001" / Resource Group "RG-DEV-XX-XXXX-001"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameters" Message="Invalid parameter: Tags count out of bound. Maximum count value is 15."`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
