### ISSUE TITLE
Windows Terraform - Reading AWS credentials from %UserProfile%/.aws/credentials fails

### ISSUE THREAD

**Issue by Kunal-Chandarana** [hashicorp/terraform#31410]
I have the following version of Terraform -
Terraform v1.2.4
on windows_amd64

I have credentials files under %UserProfile%/.aws/credentials 
![image](https://user-images.githubusercontent.com/14099091/178037156-ae4d32f1-155d-4b71-bf22-656b1c8f9aa8.png)

Terraform provider has the same profile
```
provider "aws" {
  region  = <region>
  profile = <profile>
}
```

**I keep seeing the following error**
NoCredentialProviders: no valid providers in chain

As a workaround I switched to using environment variables but that's not the ideal solution for my usecase.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by Kunal-Chandarana** [comment]
Thank you. I will re-post this issue under terraform AWS provider.
