### ISSUE TITLE
Not able to create azurerm_databricks_workspace with custom_parameters block

### ISSUE THREAD

**Issue by sravani2714** [hashicorp/terraform#31417]
Hi Team

we are not able to launch azurerm_databricks_workspace resource with custom_parameter block . Not getting launch option in azure portal.
we are getting in azure portal like "workspace is in failed state and hence launch cannot be launched".
If we tried without custom_parameter block databricks workspace is creating and launching properly.
![db_workspace](https://user-images.githubusercontent.com/109063411/178209983-db13f921-8fc2-4c3e-9b00-37cece968f2c.PNG)

Please solve this issue as soon as possible.

we are using below configurations:
Terraform version : 1.2.4
Azure version: 2.78.0
Databricks version: 0.5.0

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
