### ISSUE TITLE
Debian installation instructions don't work

### ISSUE THREAD

**Issue by sjshuck** [hashicorp/terraform#31415]
The docs recommend

```
sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/terraform-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/terraform.list
```

This results in a permission denied error.  It's because `sudo` applies to `echo`, but not to the parent shell doing the redirection.

**Comment by kmoe** [comment]
Thanks for spotting this. Assuming this refers to https://www.terraform.io/cli/install/apt, it is fixed in https://github.com/hashicorp/terraform/pull/31227.
