### ISSUE TITLE
Terraform-provider-azurerm_v3.9.0_x5 plugin crashed

### ISSUE THREAD

**Issue by rahulgarg02** [hashicorp/terraform#31427]
I'm facing below error in terraform plan from past 2 hours.

github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func3({0x673a068, 0xc0011a84e0}, 0x45d964b094?, {0x5676020?, 0xc0014d4000?})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:65 +0x159
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x673a068, 0xc0011a84e0}, 0x7f4218f40108?, {0x5676020, 0xc0014d4000})
	github.com/hashicorp/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:185 +0xbe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000573880, {0x6739ff8, 0xc00301c840}, 0x24?, {0x5676020, 0xc0014d4000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000573880, {0x6739ff8, 0xc00301c840}, 0xc001febee0, {0x5676020, 0xc0014d4000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000393698, {0x6739ff8, 0xc00301c840}, 0xc00301c8c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x43f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001d4f00, {0x673a0a0?, 0xc0030461b0?}, 0xc0011a80c0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x33c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x5bfbe40?, 0xc0001d4f00}, {0x673a0a0, 0xc0030461b0}, 0xc0011a8060, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000233180, {0x674b458, 0xc0005ab980}, 0xc00302e5a0, 0xc00151de60, 0xa7749d0, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000233180, {0x674b458, 0xc0005ab980}, 0xc00302e5a0, 0x0)
	google.golang.org/grpc@v1.39.0/server.go:1617 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.39.0/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.39.0/server.go:938 +0x28a

Error: The terraform-provider-azurerm_v3.9.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

##[warning]Can't find loc string for key: TerraformPlanFailed
##[error]Error: TerraformPlanFailed 1

**Comment by kmoe** [comment]
Thanks for the bug report. As indicated in the error message, this is a problem with the terraform-provider-azurerm plugin, not Terraform itself. Please raise an issue in the terraform-provider-azurerm repository.
