### ISSUE TITLE
Facing issue with terraform init

### ISSUE THREAD

**Issue by saurabh71669** [hashicorp/terraform#31426]
I am getting error while I am running my CI CD pipeline to run terraform 

[0m[1mInitializing modules...[0m
- rds.rds-db-instance in 
- rds.rds-subnet-group in 
[31m[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mLocal module path escapes module package[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe given source directory for module.rds.module.rds-db-instance would be
[31m│[0m [0moutside of its containing package
[31m│[0m [0m"git::https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/rds-mssql-v2.git".
[31m│[0m [0mLocal source addresses starting with "../" must stay within the same
[31m│[0m [0mpackage that the calling module belongs to.
[31m╵[0m[0m
[0m[0m
[31m[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mLocal module path escapes module package[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe given source directory for module.rds.module.rds-subnet-group would be
[31m│[0m [0moutside of its containing package
[31m│[0m [0m"git::https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/rds-mssql-v2.git".
[31m│[0m [0mLocal source addresses starting with "../" must stay within the same
[31m│[0m [0mpackage that the calling module belongs to.

Code: 

module "rds-db-instance" {
  source                          = "git::https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-module-rds_db_instance-v2.git"
  allocated_storage               = var.allocated_storage
  allow_major_version_upgrade     = local.allow_major_version_upgrade
  apply_immediately               = var.apply_immediately
  auto_minor_version_upgrade      = local.auto_minor_version_upgrade
  availability_zone               = var.availability_zone
  backup_retention_period         = var.backup_retention_period
  backup_window                   = var.backup_window
  character_set_name              = local.character_set_name
  copy_tags_to_snapshot           = local.copy_tags_to_snapshot
  db_subnet_group_name            = module.rds-subnet-group.id
  deletion_protection             = local.deletion_protection
  enabled_cloudwatch_logs_exports = local.enabled_cloudwatch_logs_exports
  engine                          = var.engine
  engine_version                  = var.engine_version
  identifier                      = local.identifier
  instance_class                  = var.instance_class
  license_model                   = local.license_model
  maintenance_window              = var.maintenance_window
  multi_az                        = var.multi_az
  password                        = var.password
  skip_final_snapshot             = var.skip_final_snapshot
  storage_encrypted               = var.storage_encrypted
  kms_key_id                      = var.kms_key_id
  storage_type                    = var.storage_type
  tags                            = merge(var.tags, { Name = local.identifier })
  iops                            = var.iops
  username                        = local.username
  vpc_security_group_ids          = concat(var.vpc_security_group_ids, [module.rds-security-group.id])
  max_allocated_storage           = var.max_allocated_storage
}

/*
module "rds-parameter-group" {
  source      = "git::https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-module-rds-parameter-group-v2.git"
  description = local.pg_description
  family      = var.family
  name        = local.pg_name
  parameters  = var.parameters
  tags        = merge(var.rds_pg_tags, { Name = local.pg_name })
}
*/

module "rds-subnet-group" {
  source      = "git::https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-module-rds_subnet_group-v2.git"
  description = local.sug_description
  name        = local.sug_name
  subnet_ids  = var.subnet_ids
  tags        = merge(var.rds_sub_tags, { Name = local.sug_name })
}

module "rds-security-group" {
  source                                = "git::https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-module-rds_security_group-v2.git"
  vpc_id                                = var.vpc_id
  name                                  = local.scg_name
  description                           = local.scg_description
  tags                                  = merge(var.rds_sg_tags, { Name = local.scg_name })
  ingress_with_cidr_blocks              = var.sec_group_ingress_with_cidr_blocks
  ingress_with_source_security_group_id = var.sec_group_ingress_with_source_security_group_id
  egress_with_cidr_blocks               = var.sec_group_egress_with_cidr_blocks
  egress_with_source_security_group_id  = var.sec_group_egress_with_source_security_group_id
}

module "rds_option_group"{
  source                                = "git::https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/terraform-module-rds_option_group-v2.git"
    option_group_name           = var.option_group_name
    option_group_description    = var.option_group_description
    engine_name                 = var.engine_name
    major_engine_version        = var.major_engine_version
    option_name                 = var.option_name
    option_settings_name        = var.option_settings_name
    option_settings_value       = var.option_settings_value
    og_tags                     = var.og_tags
    }
    
Can anyone please help in this, Am I doing wrong refrences of module.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
