### ISSUE TITLE
Currently no possible for creating the SNS platform application for a google (FCM) 

### ISSUE THREAD

**Issue by rbiradavolu** [hashicorp/terraform#31433]
### Terraform Version:

```
Terraform v1.1.8
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior
The SNS platform application should be created as per the code upload the API key 

Error Notification : 
<img width="960" alt="Screen Shot 2022-07-13 at 10 31 35 AM" src="https://user-images.githubusercontent.com/108306729/178759350-6b3f4ca1-a80e-4602-9754-e19eabc033d9.png">

aws_sns_platform_application.gcm_application: Creating...
╷
│ Error: Error creating SNS platform application: InvalidParameter: Invalid parameter: Attributes Reason: Platform credentials are invalid
│       status code: 400, request id: e4466da3-d1a5-55fc-8fce-36eb08aaa52b
│ 
│   with aws_sns_platform_application.gcm_application,
│   on gcm.tf line 8, in resource "aws_sns_platform_application" "gcm_application":
│    8: resource "aws_sns_platform_application" "gcm_application" {

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_platform_application

**Comment by crw** [comment]
Hello @rbiradavolu, this appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
