### ISSUE TITLE
Update `path.module` documentation re race conditions

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#31441]
### Terraform Version

```
v1.2.4
```

### Terraform Configuration Files

Any Terraform module invocations where the child module uses `path.module` for a write operation.

### Expected Behavior

https://www.terraform.io/language/expressions/references#filesystem-and-workspace-info should call out the race conditions and inconsistent behavior that can result from using `path.module` and local module source for write operations that @apparentlymart described in https://github.com/hashicorp/terraform/issues/29503. In my opinion, this disclaimer should entirely warn against using `path.module` for any write operations regardless of module source type for the reasons described in that issue, but at a minimum, it should document the current behavior and race conditions that people can hit.

### Actual Behavior

Documentation makes no mention of this issue.

**Comment by crw** [comment]
Thanks for this report!

**Comment by joe-a-t** [comment]
@crw is there any way for the community to create `documentation` request types instead of having to go the `bug` route and have you re-label it? If not, is that something that HashiCorp would consider enabling? Also would probably allow for a more logical template when making documentation requests.

**Comment by crw** [comment]
Hi @joe-a-t, good question. Now that github has the ability to create a templated "wizard" for issue reports, we probably could make this happen. Thanks for this idea, I'll see what we can do.

**Comment by laurapacilio** [comment]
Thanks @joe-a-t! Opened this PR to address this issue: https://github.com/hashicorp/terraform/pull/31545

Let me know if you have thoughts, thank you!
