### ISSUE TITLE
Changing iam_instance_profile on an aws_launch_configuration does not force a new resource

### ISSUE THREAD

**Issue by CpuID** [hashicorp/terraform#3144]
I was renaming the aws_iam_instance_profile resource in a .tf script, and updating the reference to iam_instance_profile on the aws_launch_configuration, but it has not picked up the change, which should trigger a new LC being created.

Using a format like this on the aws_launch_configuration:

```
iam_instance_profile = "${aws_iam_instance_profile.profileresource.name}"
```

Terraform 0.6.3 on OSX.

**Comment by CpuID** [comment]
Not sure if there is any relevance but I have the create_before_destroy lifecycle rule attached to the aws_launch_configuration.

**Comment by CpuID** [comment]
Actually, ignore me, I didn't update the name field on the aws_iam_instance_profile, duh.

**Comment by catsby** [comment]
Glad you got things sorted out :smile: 

Let us know if you need anything else
