### ISSUE TITLE
Crash setting up aws_vpc_peering_connection

### ISSUE THREAD

**Issue by rvangraan** [hashicorp/terraform#3145]
I got this crash while deploying a new aws_vpc_peering_connection resource that uses the outputs of separate modules using Terraform v0.6.3:

```
resource "aws_vpc_peering_connection" "vpc-peer-pci-core-zone" {
    peer_owner_id = "${var.core-vpc-owner-id}"
    peer_vpc_id = "${module.core.core-zone-vpc-id}"
    vpc_id = "${module.pci.pci-zone-vpc-id}"
    auto_accept = true
}
```

**Edit from @catsby:** moved crash log to https://gist.github.com/catsby/a4dfde333e8bb540f019

**Comment by rvangraan** [comment]
It looks like the peering connection got created, but then something went haywire.
![screen shot 2015-09-02 at 14 23 31](https://cloud.githubusercontent.com/assets/2574318/9632295/3b2681fc-517e-11e5-9c44-b7f6e47021d5.png)

**Comment by rvangraan** [comment]
This has to do with 
```
    auto_accept = true
```
when I removed it, the crash disappeared.

**Comment by apparentlymart** [comment]
Thanks for the report and the debugging effort, @rvangraan.

Looks like this is failing trying to dereference one of the ``AcceptVpcPeeringConnectionInput`` response fields:
https://github.com/hashicorp/terraform/blob/0c2f189d083e49b49747ce323702db1861cb2cbf/builtin/providers/aws/resource_aws_vpc_peering_connection.go#L131

Not familiar at all with this API, so no strong theories yet. Just wondering, though: were you trying to peer between two VPCs in the same AWS account, or across two accounts?

**Comment by dsalazar-carecloud** [comment]
I experienced the same issue.  And in my scenario it was across two accounts.  I'm assuming that it has to do with the inability to prove that you are the owner of that other account and execute the auto acceptance of the peer request of the account vpc you're trying to peer in to within the context of the run.

**Comment by rvangraan** [comment]
@apparentlymart: This was with two VPCs on the same account.

**Comment by catsby** [comment]
Hello –

I wasn't able to reproduce this directly, but I did open and merge https://github.com/hashicorp/terraform/pull/3490 to add better error handling and check for `nil` references.

Please let me know if you're still hitting this.
Thanks!
