### ISSUE TITLE
Allow to set mode when attaching google disk

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#3146]
According to https://cloud.google.com/sdk/gcloud/reference/compute/instances/attach-disk you can set a disk to read-only when attaching it to an instance. By doing so you can add the same disk to multiple instances, which I'd like to do for some shared files inside a google_compute_instance_template.

Is it possible to set the mode currently?

**Comment by etiennetremel** [comment]
+1

**Comment by lwander** [comment]
Yup, see the `mode` attribute here: https://www.terraform.io/docs/providers/google/r/compute_instance_template.html#mode
