### ISSUE TITLE
Azure provider: Resource to manage DNS

### ISSUE THREAD

**Issue by mtekel** [hashicorp/terraform#3147]
Azure [APIs](https://msdn.microsoft.com/en-us/library/azure/mt163862.aspx) support creation, deletion and general manipulation of DNS records and zones. We would like to do this using terraform. Azure SDK should support DNS operations soon: https://github.com/Azure/azure-sdk-for-go/issues/184

**Comment by thecodeassassin** [comment]
+1

**Comment by aznashwan** [comment]
@mtekel: with the release of the new ARM API bindings in the go sdk; DNS records and zones (which are **only** definable using ARM) are on their way.

For the status of ARM support, please refer here: https://github.com/hashicorp/terraform/issues/3212

**Comment by mtekel** [comment]
great, looking forward to it

**Comment by mtekel** [comment]
I see TF 0.6.12 adds a lot of Azure resources for DNS:
```
New resource: azurerm_dns_a_record (#5013)
New resource: azurerm_dns_aaaa_record (#5013)
New resource: azurerm_dns_cname_record (#5013)
New resource: azurerm_dns_mx_record (#5041)
New resource: azurerm_dns_ns_record (#5041)
New resource: azurerm_dns_srv_record (#5041)
New resource: azurerm_dns_txt_record (#5041)
New resource: azurerm_dns_zone (#4979)
```
I am not sure if that might cover this feature request, as I'm hands-off Azure now and have no way to test...

**Comment by stack72** [comment]
Hi @mtekel 

The `azurerm` resources you mentioned do indeed cover the DNS functionality you asked for :) 

closing this PR

Paul
