### ISSUE TITLE
Dependencies Don't Wait For Provisioners To Complete

### ISSUE THREAD

**Issue by vesubramanian** [hashicorp/terraform#31472]
I create an S3 bucket using terraform. After that I need to download a couple of files from JFrog Artifactory to a local folder. One of the files is a zip which is extracted. This local folder will have 3 more folders. I am using local-exec provisioners inside null_resources to download the files. Then I am using aws_s3_objects to upload all these files and folders to the S3 bucket. However, the local-exec provisioner seems to be executing in a separate thread and also, the aws_s3_object resource runs before the local-exec provisioner completes. So, even if I have depends_on the aws_s3_objects for the null_resources, the JFrog files are not getting uploaded to the S3 bucket. This is somewhat related to the issue described here.
[https://github.com/hashicorp/terraform/issues/5595](https://github.com/hashicorp/terraform/issues/5595)
Can anyone please help?
Version of TF - 1.1.4

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
