### ISSUE TITLE
provisioner "file" on a remote module to access remote's module files

### ISSUE THREAD

**Issue by AndriiLavrekha** [hashicorp/terraform#31473]
Hello everyone, 
I've been working with Terraform for a month now(and it's awesome!) and I've ended up using the modules feature to be able to create a template for multiple environments. One issue that I've faced during working with Terraform and remote modules (source=git) is that the provisioner "file" is not capable to pass exact functionality from a child to a parent.

I do not know if it is a feature or a bug but may be worth mentioning and maybe introducing missing functionality?

### Current Terraform Version

```
Terraform v1.2.4
```

### Use-cases
As a user, I want to be able to use _provisioner "file"_ declared in a remote module (git source) that references its own local files and will continue to do so even when used as a dependency in other Terraform projects.

Parent TF project which calls remote module that has _provisioner "file"_ referencing locals to a remote git repo
```
module "remote-module-name" {
    source = "git@github.com:git-repo/tf-project.git"
}
```

Remote module TF
```
resource "azurerm_linux_virtual_machine" "vm_machine" {
...
  provisioner "file" {
      source = "config.yaml"
      destination = "/tmp"
    }
}
```

Projects structure
```
Parent TF project
├── env1
│   ├── main.tf
│   └── output.tf
├── env2
│   ├── main.tf
│   └── output.tf
├── envN
│   ├── main.tf
│   └── output.tf


A remote TF module that is used in a parent project as a module
├── modules
│   ├── local_module1
│       ├── config.yaml
│       ├── main.tf
│       ├── outputs.tf
│       └── variables.tf
│   └── local_module2
│        ├── main.tf
│        ├── outputs.tf
│        └── variables.tf
└── README.md

```

### Attempted Solutions
On a `terraform apply` I'm getting the error that **config.yaml** file does not exist on a parent project (which is true and by a design of a project it should not).
```
│ Error: file provisioner error
│
│   with module.remote-module-name.module.local_module1.azurerm_linux_virtual_machine.vm_machine[0],
│   on .terraform\modules\remote-module-name\modules\local_module1\main.tf line 119, in resource "azurerm_linux_virtual_machine" "vm_machine":
│  119:   provisioner "file" {
│
│ CreateFile config.yaml: The system cannot find the path specified.
```

### Proposal

I'm not sure here, but my guess is to check if provisioner "file" is referencing a local file from a remote module and if so - use it unless the parent project has it.

**Comment by apparentlymart** [comment]
Hi @AndriiLavrekha,

From what you've described, I think you could achieve the result you want by changing your provisioner configuration to the following:

```hcl
resource "azurerm_linux_virtual_machine" "vm_machine" {
...
  provisioner "file" {
      source = "${path.module}/config.yaml"
      destination = "/tmp"
    }
}
```

The `path.module` interpolation I added here will cause Terraform to insert the path to the directory where the current module is cached on the local computer. In the example you shared, I would expect today's Terraform to generate the path `.terraform/modules/remote-module-name/config.yaml`, although that `.terraform/modules/remote-module-name` prefix is an implementation detail and may not always be the same in future releases of Terraform; using `path.module` means that your module should keep working even if Terraform needs to install the module in a different location for some reason.

**Comment by CloudbrokerAz** [comment]
Hi @apparentlymart,
Your proposed workaround works. I tested this and  ${path.module} copied the contents of the source file.
Nice work!
