### ISSUE TITLE
Terraform crashed! This is always indicative of a bug within Terraform.

### ISSUE THREAD

**Issue by gouthamkamre68** [hashicorp/terraform#31487]
HI,

Please find the below report to fix this.

Initializing modules...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

missing manifest record for parent module
goroutine 1 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x22bcc80, 0xc0008b0c20})
/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installLocalModule(0x2737bc7?, 0xc0000e2cb0, {0x0, 0x0}, 0x170?, {0x2c588c0, 0xc0006fb728})
/home/circleci/project/project/internal/initwd/module_install.go:253 +0x9ae
github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installDescendentModules.func1(0xc0000e2cb0)
/home/circleci/project/project/internal/initwd/module_install.go:207 +0xc7c
github.com/hashicorp/terraform/internal/earlyconfig.ModuleWalkerFunc.LoadModule(0xc000159a10?, 0x15?)
/home/circleci/project/project/internal/earlyconfig/config_build.go:172 +0x1f
github.com/hashicorp/terraform/internal/earlyconfig.buildChildModules(0xc0000e2bd0, {0x2c4fde0, 0xc0007ebb30})
/home/circleci/project/project/internal/earlyconfig/config_build.go:97 +0x9bb
github.com/hashicorp/terraform/internal/earlyconfig.BuildConfig(0xc0001a0d80, {0x2c4fde0, 0xc0007ebb30})
/home/circleci/project/project/internal/earlyconfig/config_build.go:22 +0x79
github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installDescendentModules(0xc0008afd10, {0x2c6ab10?, 0xc0002bb9c0}, 0x40d3a5?, {0x26b3c8e, 0x1}, 0xc000806330, 0x0, {0x2c588c0, 0xc0006fb728}, ...)
/home/circleci/project/project/internal/initwd/module_install.go:120 +0x2aa
github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).InstallModules(0xc0008afd10, {0x2c6ab10, 0xc0002bb9c0}, {0x26b3c8e, 0x1}, 0xe8?, {0x2c588c0, 0xc0006fb728})
/home/circleci/project/project/internal/initwd/module_install.go:99 +0x354
github.com/hashicorp/terraform/internal/command.(*Meta).installModules(0xc0005836c0, {0xc0000600f0?, 0x24?}, 0x6?, {0x2c588c0, 0xc0006fb728})
/home/circleci/project/project/internal/command/meta_config.go:188 +0x1de
github.com/hashicorp/terraform/internal/command.(*InitCommand).getModules(0xc0005836c0, {0xc0000600f0, 0x4f}, 0x26e0ec4?, 0x0)
/home/circleci/project/project/internal/command/init.go:361 +0x374
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc0005836c0, {0xc00013c010, 0x0, 0x0})
/home/circleci/project/project/internal/command/init.go:192 +0xfd4
github.com/mitchellh/cli.(*CLI).Run(0xc000178640)
/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x5f8
main.realMain()
/home/circleci/project/project/main.go:312 +0x15b4
main.main()
/home/circleci/project/project/main.go:58 +0x19

**Comment by jbardin** [comment]
Hi @gouthamkamre68,

Thanks for filing the issue! In order to assist, we would need more of the information requested in the issue template. It would help if you cold provide the missing info, including an example of the configuration and steps used to trigger the panic.

Thanks!

**Comment by jbardin** [comment]
Closing the issue since we have not heard back in a while. If this is still reproducible, please file a new issue with the information requested in the issue template.

Thanks!
