### ISSUE TITLE
aws_elasticache_cluster: expose configuration_endpoint

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#3149]
Pretty simple:

https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeCacheClusters.html

Has a `ConfigurationEndpoint`

We should set it as a readable attribute. Can probably just join the address and the port with a colon.

**Comment by stack72** [comment]
@phinze after the merge on #3250, this can be closed :)

**Comment by phinze** [comment]
:smile:
