### ISSUE TITLE
data.tls_certificate.tls.certificates is empty list of object, after tls updated to 4.0.0 from 3.4.0

### ISSUE THREAD

**Issue by kailashsridharan** [hashicorp/terraform#31496]
### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by kailashsridharan** [comment]
Bad ticket closing it

**Comment by andrei-dascalu** [comment]
@kailashsridharan Why is this a bad ticket? I'm having an issue like that - basically in the form of 

```
data "tls_certificate" "eks" {
  url = aws_eks_cluster.eks-cluster.identity[0].oidc[0].issuer

  depends_on = [
    aws_eks_cluster.eks-cluster
  ]
}
```

```
resource "aws_iam_openid_connect_provider" "eks" {
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.eks.certificates[0].sha1_fingerprint]
  url             = aws_eks_cluster.eks-cluster.identity[0].oidc[0].issuer

  depends_on = [
    aws_eks_cluster.eks-cluster
  ]
}
```

Message: 
```
│ Error: Invalid index
│ 
│   on modules/development/09-oidc.tf line 11, in resource "aws_iam_openid_connect_provider" "eks":
│   11:   thumbprint_list = [data.tls_certificate.eks.certificates[0].sha1_fingerprint]
│     ├────────────────
│     │ data.tls_certificate.eks.certificates is empty list of object
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
``

**Comment by ShikharG26** [comment]
@andrei-dascalu Even I am facing this issue from last Friday.
I am using eks module and earlier it was working fine but from last Friday it is failing here.

**Comment by rekcah78** [comment]
@ShikharG26 did you try with the last version of the eks module ? https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v18.26.6

**Comment by ShikharG26** [comment]
@rekcah78 No I am using 18.20.5.
Although I checked more and it seems the problem is with TLS provider as it is updated to 4.0.0

Pinning the TLS version to 3.4.0 works.

`terraform {
  required_providers {
    tls = {
      source = "hashicorp/tls"
      version = "3.4.0"
    }
  }
}
`

**Comment by jlees-Gss** [comment]
We fixed by rolling back the tls in the provider from 4.0.0 to 3.0.0.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/104621013/180765618-50c7f031-b0f8-44dc-8191-f3fb4a2503ac.png)

**Comment by przemub** [comment]
@teamterraform Could you please re-open this? I would open a new ticket, but this one shows up in search engines when looking for the solution.

For me, the error occurs within the EKS module:
```
│ Error: Invalid index
│ 
│   on .terraform/modules/eks/main.tf line 171, in resource "aws_iam_openid_connect_provider" "oidc_provider":
│  171:   thumbprint_list = concat([data.tls_certificate.this[0].certificates[0].sha1_fingerprint], var.custom_oidc_thumbprints)
```

Rolling back hashicorp/tls to 3.4.0 fixes the issue.

**Comment by bflad** [comment]
Hi folks 👋 The GitHub issue tracking this error message caused by the TLS provider was here: https://github.com/hashicorp/terraform-provider-tls/issues/244

There was a [version 4.0.1 release](https://github.com/hashicorp/terraform-provider-tls/releases/tag/v4.0.1) today which should resolve this particular issue. If you have further feedback on the TLS provider, please use its [issue tracker](https://github.com/hashicorp/terraform-provider-tls/issues). Thank you.
