### ISSUE TITLE
Error: Your query returned no results. Please change your search criteria and try again.

### ISSUE THREAD

**Issue by dasanirban834** [hashicorp/terraform#31494]
Hi All,

Initially I created image using Packer and then trying to pull that AMI using data block, but I'm getting this error. Could you please help me understand that where I made mistakes. PFB snaps.

![image](https://user-images.githubusercontent.com/67305577/180353888-febda3e0-1f69-49d2-acf1-82ebc2ba331e.png)

![image](https://user-images.githubusercontent.com/67305577/180353957-cffa030f-2948-4160-b265-0d0f99d31362.png)

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
