### ISSUE TITLE
Build failing due to multiple CVE's related to go libraries - Twistlock stage

### ISSUE THREAD

**Issue by RajPathare** [hashicorp/terraform#31503]
### Issue
```
We're trying to create a base-image which will have all the pre-required tools/binaries. When we're trying to run twistlock scan on the built image, it is failing due to multiple critical vulnerabilities. The image is built using the latest terraform version (v1.2.5).
```

### Terraform Version

```
Terraform v1.2.5
```

### Expected Behavior

```
Twistlock scan should have been passed for the given image.
```

### Actual Behavior

```
Twistlock scan is failing due to multiple CVE's related to go.
```

### References

<img width="1199" alt="Screenshot 2022-07-25 at 8 59 25 AM" src="https://user-images.githubusercontent.com/31897425/180694351-a03d5a6c-f81e-472a-953b-efa65e61e94f.png">

**Comment by jbardin** [comment]
Hi @RajPathare,

I'm not familiar with the vulnerability scanner you are using, but the output here does not correlate with the Terraform project's dependencies in the v1.2 branch. Spot checking some of these show that they are either versions below the minimum required version, or are not used within Terraform at all.

I would suggest reviewing the setting for the build system you are using to make sure the vulnerability scanner is configured correctly, or you are building from the expected branch. If you have more question, feel free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help. If you do find security concerns in the Terraform product, please follow the reporting guidelines documented hereat https://www.hashicorp.com/security.

Thanks!
