### ISSUE TITLE
Terraform Crashed while doing Terraform init

### ISSUE THREAD

**Issue by Rameswari1991** [hashicorp/terraform#31518]
Hi There,

I am trying to upgrade terraform version in one of our stacks, where i am upgrading to tf version 1.2.5, but i got an error saying 
      “Error: Invalid legacy provider address
│
│ This configuration or its associated state refers to the unqualified provider “aws”.
│
│ You must complete the Terraform 0.13 upgrade process before upgrading to later versions.”

 **So after I switched to tf version 0.13 and again did terraform init, I got the following error :**

        !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at “crash.log” relative to your current
[crash.log](https://github.com/hashicorp/terraform/files/9191459/crash.log)

working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running ‘terraform --version’ on the command line.
SECURITY WARNING: the “crash.log” file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jbardin** [comment]
Hi @Rameswari1991,

You should always use the latest patch version of a release, and for v0.13 that was v0.13.7. If you have more questions about the upgrade process, please visit [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
