### ISSUE TITLE
Need a way of detecting whether a json document/aws policy document has functionally altered

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#31517]
I raised this also in terraform-provider-aws, but raising here as it might be better to have a generic function doing this rather than an aws resource. 

### Description

Roles and Policies in AWS are eventually consistent - they often take around 10 seconds to take effect. Frequently however it is desirable in terraform to use a role/policy that you have just created to then do some action that the role/policy allows. For example we create a role called foo, apply policy bar to it, wait 10 seconds, and then use foo to do something else, all in the same terraform run. 

Generally speaking this works well, and we use a time_sleep resource to wait 10 seconds, depending on the role/policy etc. 

This all works the first time round, but if the role or policy changes then we need to re-trigger the time_sleep resource to wait another 10 seconds, before downstream objects are to be applied (with the new policy). This creates the question - how can we trigger when a role changes?

I started off using:

```
resource "time_sleep" "ready" {
  triggers = {
    id = aws_iam_role_policy.this.id
    role_policy = aws_iam_role_policy.this.policy
  }
  create_duration = "10s"
  depends_on = [
    aws_iam_role_policy.this
  ]
}
```

And this seems to work fine - when the policy changes, the time_sleep also gets replaced, causing a 10s delay and it all works. 

However in a recent provider version upgrade of aws, whitespace changes were introduced into the policy document which caused all time_sleeps to get replaced - because they thought the policies had changed, even though they are just whitespace changes. 

This rather breaks the model, and suddenly most of the infrastructure is being rebuilt because of a whitespace change. 

I would like a foolproof way of detecting whether the _FUNCTIONAL CONTENT_ of a policy or json document has changed so I can trigger on it.

I initially thought it might be a good case for a function to wrap around a policy rather than for terraform-provider-aws to solve this in the resources themselves. 

Some of my colleagues suggested eTags are pretty standard way to detect differences, but I'd only want to detect functional differences.

### New or Affected Resource(s)

* aws_iam_role
* aws_iam_role_policy
* aws_iam_policy

### Potential Terraform Configuration

If there was a function or attribute which could take a json policy, and deep sort all map keys, and standardise around the difference between `{ AWS: foo }` and `{ AWS: [ foo ] }` which are also functionally identical - and then output a standardised document, that would be very handy.

If implementing in the resource itself, it would be need to be done on all policy types, e.g. assume_role_policy, policy etc. -  I think a datasource in the aws-provider which could take some json content and spit out a standardised version (bearing in mind the aws dialect idiosyncrasies above) might work as a solution - I wonder if a generic function that could identify a standardisation of a json document which coped with reordering/whitespace changes/differences is possible - although aws policies also have other idiosyncrasies mentioned above (such as the single item in square brackets thing).

**Comment by gtmtech** [comment]
Related issue https://github.com/hashicorp/terraform-provider-aws/issues/25980

**Comment by jbardin** [comment]
Thanks @gtmtech. This needs to be something handled in a provider, so we can track it there.
