### ISSUE TITLE
consul_keys should be able to update value

### ISSUE THREAD

**Issue by little-arhat** [hashicorp/terraform#3151]
Currently, you can only set value of the key. If you want to update it, you need to change the `name` of the key (without changing its path). I think, `consul_keys` should provide a way to update previously created key, maybe using additional attribute like `version`.

Terraform v0.6.3.

**Comment by little-arhat** [comment]
Ability to delete keys would also help.

**Comment by little-arhat** [comment]
Update: if I use `template_file` for `consul_keys` value, Terraform seems to see value changes, whenever I modify template/vars. However, when applying those changes, I get following error:

`* consul_keys.some_key: diffs didn't match during apply. This is a bug with Terraform and should be reported.`

**Comment by saliceti** [comment]
+1
I don't see the point of this feature if the keys can't be updated.

**Comment by phinze** [comment]
Merging this issue with #774. The Consul provider could definitely use a pass for bugfixes like this one.
