### ISSUE TITLE
Terraform deletes and adds bucket policy statement in every consecutive builds even when nothing has changed

### ISSUE THREAD

**Issue by Yashwant0108** [hashicorp/terraform#31525]
It has been observed that the Terraform deletes and adds bucket policy statement in every consecutive builds even when nothing has changed.
Build 1: removes the policy statements
Build 2: Add the removed statements
Build 3: removes the policy statements
Build 4: Add the removed statements
Build 5: removes the policy statements
Build 6: Add the removed statements

Any way to fix this?

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
