### ISSUE TITLE
Terraform failed to install provider

### ISSUE THREAD

**Issue by ruslianto707** [hashicorp/terraform#31521]
Terraform --version
Terraform v1.2.5
on linux_amd64

terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/aws v4.23.0: could not query provider registry
│ for registry.terraform.io/hashicorp/aws: failed to retrieve authentication
│ checksums for provider: the request failed after 2 attempts, please try again
│ later: Get
│ "https://releases.hashicorp.com/terraform-provider-aws/4.23.0/terraform-provider-aws_4.23.0_SHA256SUMS":
│ net/http: request canceled while waiting for connection (Client.Timeout exceeded
│ while awaiting headers)

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
