### ISSUE TITLE
S3 bucket creation | Existing Buckets  

### ISSUE THREAD

**Issue by rishabhjain1510** [hashicorp/terraform#31528]
while creating a S3 bucket using terraform, if that bucket already exists we are facing an weird issue

Current Scenario: 
S3 bucket :- "test-rishabh-111"  
This bucket was created via terraform different product about 1 year ago 
![image](https://user-images.githubusercontent.com/89471097/181275041-eb84eccb-66e2-4830-a4d2-d40e3678abac.png)

When created the same bucket via Terraform using below code 

resource "aws_s3_bucket" "test_bucket" {
  bucket = "test-rishabh-111"
}
-----Terraform Apply-------------
$ terraform13 apply --auto-approve
aws_s3_bucket.test_bucket: Creating...
aws_s3_bucket.test_bucket: Still creating... [10s elapsed]
aws_s3_bucket.test_bucket: Still creating... [20s elapsed]
aws_s3_bucket.test_bucket: Creation complete after 22s [id=test-rishabh-111]
----------------------------------------------------------------------------------------

Terraform says it has been successfully created .  and adds this resources in the state also. 

Expected Behavior 

This should have given the error that bucket already exist , at least should not have include the resource under the state. 

Now the same resource is managed by the two different states. 

If i delete any tf resource it will delete the s3 bucket also. 

Terraform Version Details:
AWS Provider :- 3.75.1
Terraform Version : 0.13.6

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
