### ISSUE TITLE
Terraform keep creating when instance_type not availabale in region

### ISSUE THREAD

**Issue by azmifauzan** [hashicorp/terraform#31522]
### Terraform Version

```
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.23.0
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.23"
    }
  }

  required_version = ">= 1.2.0"
}

provider "aws" {
  region  = "ap-southeast-3"
}

resource "aws_instance" "app_server" {
  ami           = "ami-0483d92a8124da6c9"
  instance_type = "t2.micro"

  tags = {
    Name = "ExampleAppServerInstance"
  }
}
```

### Expected Behavior

Terraform produce error message like aws cli produce when instance_type not available in region

This is aws cli result: 
```
aws configure get region 
ap-southeast-3

aws ec2 run-instances --image-id ami-0483d92a8124da6c9 --count 1 --instance-type t2.micro
An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 2): We currently do not have sufficient t2.micro capacity in zones with support for 'gp2' volumes. Our system will be working on provisioning additional capacity.
```

### Actual Behavior

Terraform keep creating

aws_instance.app_server: Creating...
aws_instance.app_server: Still creating... [10s elapsed]
aws_instance.app_server: Still creating... [20s elapsed]
aws_instance.app_server: Still creating... [30s elapsed]
aws_instance.app_server: Still creating... [40s elapsed]
aws_instance.app_server: Still creating... [50s elapsed]
aws_instance.app_server: Still creating... [1m0s elapsed]
aws_instance.app_server: Still creating... [1m10s elapsed]
aws_instance.app_server: Still creating... [1m20s elapsed]
aws_instance.app_server: Still creating... [1m30s elapsed]
aws_instance.app_server: Still creating... [1m40s elapsed]
aws_instance.app_server: Still creating... [1m50s elapsed]
aws_instance.app_server: Still creating... [2m0s elapsed]
aws_instance.app_server: Still creating... [2m10s elapsed]
aws_instance.app_server: Still creating... [2m20s elapsed]
aws_instance.app_server: Still creating... [2m30s elapsed]
aws_instance.app_server: Still creating... [2m40s elapsed]
aws_instance.app_server: Still creating... [2m50s elapsed]
aws_instance.app_server: Still creating... [3m0s elapsed]
aws_instance.app_server: Still creating... [3m10s elapsed]
aws_instance.app_server: Still creating... [3m20s elapsed]
aws_instance.app_server: Still creating... [3m30s elapsed]
aws_instance.app_server: Still creating... [3m40s elapsed]
aws_instance.app_server: Still creating... [3m50s elapsed]
aws_instance.app_server: Still creating... [4m0s elapsed]
aws_instance.app_server: Still creating... [4m10s elapsed]
aws_instance.app_server: Still creating... [4m20s elapsed]
aws_instance.app_server: Still creating... [4m30s elapsed]
aws_instance.app_server: Still creating... [4m40s elapsed]
aws_instance.app_server: Still creating... [4m50s elapsed]
aws_instance.app_server: Still creating... [5m0s elapsed]

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
