### ISSUE TITLE
Error setting SNS Topic Invalid parameter: Policy Error: PrincipalNotFound

### ISSUE THREAD

**Issue by sparkmuse** [hashicorp/terraform#31538]
### Terraform Version

```
Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.23.0

Your version of Terraform is out of date! The latest version
is 1.2.6. You can update by downloading from https://www.terraform.io/downloads.html

```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = "eu-central-1"
}

resource "aws_sns_topic" "topic" {
  name = "sample-topic"
}

locals {
  accounts = [123, 345]
}

resource "aws_sns_topic_policy" "access" {
  count  = length(local.accounts) == 0 ? 0 : 1
  arn    = aws_sns_topic.topic.arn
  policy = data.aws_iam_policy_document.access.json
}

data "aws_iam_policy_document" "access" {
  statement {
    actions = [
      "sns:Subscribe"
    ]
    effect = "Allow"
    principals {
      identifiers = toset([for i in local.accounts : "arn:aws:iam::${i}:root"])
      type        = "AWS"
    }
  }
}
```

### Expected Behavior

A topic should have been created with an access policy attached like below
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::111111111111:root",
          "arn:aws:iam::222222222222:root"
        ]
      },
      "Action": "sns:Subscribe",
      "Resource": "arn:aws:sns:eu-central-1:333333333333:sample-topic"
    }
  ]
}
```

### Actual Behavior

I got an error. The topic was created but the policy was not present. 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

I am running from the terminal with a profile set for AWS.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by sparkmuse** [comment]
@jbardin You are more than right. This ticket belongs elsewhere. I guess it was late at night. Thanks for the help :)
