### ISSUE TITLE
AWS RDS replica storage type bug

### ISSUE THREAD

**Issue by bensojona** [hashicorp/terraform#3153]
I have a [Terraform template]( https://gist.github.com/bensojona/61ed53a8b909b864240f#) where I bring up a master and replica Postgres db. 

The master has an `iops` storage type and the replica is `gp2`. They both come up fine, however, the replica comes up with `iops` as a storage type, even thought I specified `gp2` and commented out the `iops` flag (which I believe forces a storage type of `iops` if set). 

[Here](https://gist.github.com/bensojona/61ed53a8b909b864240f#file-main-tf-L94-L120) is the replica portion (passing in `gp2` as `r_storage_type`), [here](https://gist.github.com/bensojona/bb84f476e482f2dd5d21#file-rds-L57) is the relevant apply output (notice `storage_type` is `gp2` and `iops` is not set for the replica, [here](https://gist.github.com/bensojona/0581f7a7bb562b6f433f) are the variables I'm passing in (variable names are changed in a different module from `pg_r_` to `r_`, and [here](https://gist.github.com/bensojona/df5f660fb815ab1aae54) is the next plan I queued without changing anything.

The next plan fixes it, however it shouldn't have gotten created with an `iops` storage type to begin with.

**Comment by catsby** [comment]
Fixed in #4155 – we were omitting the `storage_type` in the replica creation :scream:
