### ISSUE TITLE
Log analytics cluster supports minimum 1000 GB Size/day but Azure supports 500 GB minimum

### ISSUE THREAD

**Issue by niks-singh** [hashicorp/terraform#31534]
### Current Terraform Version

```
3.15.1
...
```

### Use-cases

- Azure supports cluster creation with minimum 500 GB/Day ingestion but terraform supports minimum 1000 GB/Day which makes it redundant to use as it can cost more to customers.

### Proposal

- Allow  the minimum SKU GB per day to 500. https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-dedicated-clusters#create-a-dedicated-cluster refer the link

**Comment by kmoe** [comment]
This looks like an issue with the Azure provider: please open an issue in the provider repo at https://github.com/hashicorp/terraform-provider-azurerm.
