### ISSUE TITLE
Using terraform to create azure synapse analytics gives error 403 when opening synapse workspace studio

### ISSUE THREAD

**Issue by gauravbatta** [hashicorp/terraform#31531]
Failed to load one or more resources due to no access, error code 403.
Linked service
Credential
Pipeline
SQL script
Apache Spark configuration
Spark job definition
Synapse KQL scripts
Lake databases
Link connection
Trigger
Data flow
Dataset

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
