### ISSUE TITLE
Broken link for terraform_1.2.6_linux_amd64.zip not found

### ISSUE THREAD

**Issue by mlasalmo** [hashicorp/terraform#31530]
### Terraform Version

1.2.6
```
...
```

### Terraform Configuration Files

```terraform
...
```

### Expected Behavior

Download the latest relese

### Actual Behavior

The requested URL returned error: 404

### Steps to Reproduce

Follow this link https://releases.hashicorp.com/terraform/1.2.6/terraform_1.2.6_linux_amd64.zip

**Comment by alisdair** [comment]
Thanks for the report. Closing as duplicate of #31529
