### ISSUE TITLE
 Error: updating Customer Managed Key for Log Analytics Cluster: operationalinsights.ClustersClient#Update: Failure responding to request: StatusCode=202 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF

### ISSUE THREAD

**Issue by niks-singh** [hashicorp/terraform#31535]
### Terraform Version

```
Terraform v1.2.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.15.1
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output

updating Customer Managed Key for Log Analytics Cluster: (Cluster Name "log-cls-ncus-test-lac-msft-06" / Resource Group "rg-xxx-xx-x-xxxx-xx-xx"): operationalinsights.ClustersClient#Update: Failure responding to request: StatusCode=202 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
│
│   with module.wf_test_law_cluster.azurerm_log_analytics_cluster_customer_managed_key.this,
│   on ..\..\terraform-azurerm-wf-log-analytics-cluster\main.tf line 114, in resource "azurerm_log_analytics_cluster_customer_managed_key" "this":
│  114: resource "azurerm_log_analytics_cluster_customer_managed_key" "this" {

### Expected Behavior

- The terraform should be able to parse the Azure API response and apply should be successful as the resource is getting created but it is still giving error.

### Actual Behavior

- The terraform returns status code 202 with error cannot be parsed. The CMK happens and keys get attached to cluster even with the error. Any subsequent runs results in error that resource already exists , please import them in the state.

### Steps to Reproduce

Use the example mentioned in the https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_cluster_customer_managed_key 

### Additional Context

No

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
