### ISSUE TITLE
No documentation on JSON plan "relevant_attributes"

### ISSUE THREAD

**Issue by jearls** [hashicorp/terraform#31537]
With Terraform 1.2, the JSON Output Format was updated to version "1.1", but there is no documentation on that version or the changes between 1.0 and 1.1.  A quick inspection shows a new top-level key called "relevant_attributes", and "type" keys added to the outputs.  I have no idea how either work.  Please update your documentation to reflect the updated format.

**Comment by alisdair** [comment]
Thanks for the report!

The [JSON output format documentation](https://www.terraform.io/internals/json-format#values-representation) has been updated to describe output value types. Here's the section on this:

> Output values include a "type" field, which is a [serialization of the value's type](https://pkg.go.dev/github.com/zclconf/go-cty/cty#Type.MarshalJSON). For primitive types this is a string value, such as "number" or "bool". Complex types are represented as a nested JSON array, such as ["map","string"] or ["object",{"a":"number"}]. This can be used to reconstruct the output value with the correct type.)

We don't yet have documentation for the `relevant_attributes` values, which should be corrected. I'm retitling this issue correspondingly.
