### ISSUE TITLE
optional object type attribute are experiment terraform 

### ISSUE THREAD

**Issue by san6789** [hashicorp/terraform#31541]
Hi 

This feature is currently an opt-in experimental subject change in feature and after that we are getting  optional object type attribute are experimental 

how to fix this type of error

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
