### ISSUE TITLE
-target flag causes for_each errors when using nested for_each resources with a external data script.

### ISSUE THREAD

**Issue by ag-TJNII** [hashicorp/terraform#31559]
There is a corner-case failure with the `target` flag when running in the following configuration:

- Main config calls a module in a for_each loop
- The module utilizes a external data script to generate a data structure that (for one reason or another) cannot be generated directly in Terraform
- The external data script output is used to drive for_each inputs for resources in the module
- The user attempts to target one of the main module keys with `-target`

### Terraform Version

```
Terraform v1.2.6
```

### Terraform Configuration Files

This is a minimal configuration, simplified to only resources needed to demonstrate the problem.

./main.tf:
```terraform
module "example_module" {
  source = "./modules/example_module"

  for_each = {
    "module_one" = null,
    "module_two" = null
  }
}
```

./modules/example_module/main.tf:
```terraform
# This simplified data block represents a external script doing initial
#   structure generation unable to be done directly in Terraform DSL
data "external" "config_generator" {
  program = ["/bin/echo", "{\"one\":\"one\",\"two\":\"two\"}"]
}

# Example resource to be managed
resource "local_file" "example_resource" {
  for_each = data.external.config_generator.result

  content = each.value
  filename = "tmp/${each.value}"
}
```

### Debug Output

When running with `plan -target="module.example_module[\"module_one\"]"`: https://gist.github.com/ag-TJNII/82be0733a46c0a37723cac687189cb95

### Expected Behavior

The plan should have targeted only the `module_one` resources.

### Actual Behavior

Terraform threw an error about `The "for_each" map includes keys derived from resource attributes that cannot be determined until apply`

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -target="module.example_module[\"module_one\"]"`

### Additional Context

This appears to be due to the data script not being run for the non-targeted modules, so the input structure to the for_each resources for the non-targeted modules is missing, but Terraform still expects to be able to iterate the resources in the non-targeted modules.  If the outer for_each (in `./main.tf`) only contains one key then the module targeting works.

### References

None found

**Comment by ag-TJNII** [comment]
I was able to work around this by moving the config_generator external script invocation out of the module and into the top level main.tf.  This spaghetti's the code somewhat but the neatness of the nested loops is an overall improvement so it's tolerable.

**Comment by jbardin** [comment]
Glad you were able to work around this @ag-TJNII! The underlying cause here is the same as in #25836 and #29116, so we can track any progress with the existing issues.

Thanks!
