### ISSUE TITLE
Create documentation issue type and template

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#31552]
### Proposal

Create an issue type template for requesting documentation changes. This would help with triage of issues since they could automatically have the `documentation` label associated with them and would also allow for a template that is more geared towards the information you want with a documentation request than just having people fill out the bug or feature request form and skip half the sections.

To do this, I think that it is just adding a new template (eg `documentation.md`) to https://github.com/hashicorp/terraform/tree/main/.github/ISSUE_TEMPLATE  and copy one of the existing templates then adjust the fields accordingly. 

cc @crw @laurapacilio 

### References

= https://github.com/hashicorp/terraform/issues/31441#issuecomment-1185765105

**Comment by crw** [comment]
Thanks for this! It is on my todo list.

**Comment by crw** [comment]
@joe-a-t I'm soliciting feedback on the new issue template. If you would like to provide feedback, please take a look at this rough draft and let me know what you think is missing or should be added: https://github.com/crw/terraform/issues/new?assignees=&labels=documentation%2Cnew&template=documentation_issue.yml

**Comment by joe-a-t** [comment]
Awesome, thanks! I would lean towards separating out an `Affected Page(s)` section from the `References` section just to make it clearer where the reporter thinks the documentation needs to be updated. I'd also suggest putting the `Affected Page(s)` section either at the top of the sections that users fill out or right under the `Terraform Version` since that's the starting point if I'm reporting an issue to answer the "Where is this issue" before even getting into the "what is the issue".

For 
```
The [hashicorp/terraform](https://github.com/hashicorp/terraform) issue tracker is 
reserved for bug reports relating to the core Terraform CLI application and configuration language.
```
I would suggest 
```
The [hashicorp/terraform](https://github.com/hashicorp/terraform) `Documentation` issue type is 
reserved for reports relating to the documentation on [https://www.terraform.io/docs](). 
This issue type is only for the technical writers so that they can update documentation, it is not
monitored by the engineering team so if this issue is related to the actual functionality of Terraform
and you want engineering to take a look, please use the `Bug report` or `Feature request` issue 
types instead.
```

**Comment by crw** [comment]
Hi @joe-a-t, yes sorry, it got pushed on the back burner a bit, and I accidentally deleted my original work. I'm rebuilding it with feedback from the internal docs team. Now that 1.3 is out, it should be easy to get done in the next week or so.

**Comment by joe-a-t** [comment]
Hey @crw, just wanted to flag that new documentation type doesn't appear to be available yet and https://github.com/hashicorp/terraform/blob/main/.github/ISSUE_TEMPLATE/documentation_issue.yml has this yaml syntax error
![image](https://user-images.githubusercontent.com/67290882/196102479-3623d51c-a596-4d75-9ce7-0a5f761f8c0c.png)

**Comment by crw** [comment]
Strange. I'll check it out. Thanks for the report.

**Comment by crw** [comment]
Fixed! Thanks again for the report here, it looks like a slight problem was introduced during the code review process that I missed at the time.
