### ISSUE TITLE
Management Group not found

### ISSUE THREAD

**Issue by imyashvinder** [hashicorp/terraform#31569]
### Terraform Version

```
Terraform v1.2.4
```

### Terraform Configuration Files

```terraform
data "azurerm_management_group" "example" {
  name = "Institutional"
}

```

### Debug Output

Management Group "Institutional" was not found

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### References

Please see the attached screenshot
<img width="557" alt="Screenshot 2022-08-04 at 10 25 46 AM" src="https://user-images.githubusercontent.com/10432888/182750347-4659b735-126c-4423-a31a-4dccebbe558f.png">

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by imyashvinder** [comment]
@jbardin  Thanks mate
