### ISSUE TITLE
Error creating Azure Disk Encryption Set with customer managed key

### ISSUE THREAD

**Issue by JackCoole-Training** [hashicorp/terraform#31564]
Hi Support,

I'm currently facing a very strange bug/issue when I am trying to deploy Disk Encryption Sets for managed disks using a customer managed key on Microsoft Azure. 

For some back story, we as a team are trying to create re-useable modules to be used in future deployments for customers. The modules are logically separated by the overall Terraform standard module type, so virtual machines would fall under compute, firewalls would fall under network etc. This obviously means that we will be using for each loops and module calls to create all of our infrastructure, this will come into the issue a little later. 

As this is for Disk Encryption Sets with a Customer Managed Key for Managed Disks, I have followed the guide on the TF website, link below, for DES and matched this within our Module structure. This is where I first started seeing an issue. When I ran a terraform apply it would create all the resources, but would show an error 400 for the disk encryption set. Error code details shown below. 

I then decided to test this in a separate, flat Terraform config to try and identify why it was generating this error message, my test code will be attached to this issue. Unfortunately this error still reproduced. When inspecting the Azure Portal I could see that the disk encryption set had not had the correct permissions applied to it, despite having the correct access policy created as per the documentation. This meant that it was not authorized against the key vault or the managed disk and was prompting me to grant access for the DES to the resources. 

After some head scratching I noticed that the terraform name I had assigned the resource block for the disk encryption set was different from the name it would be given in Azure. Out of curiosity I changed it so both names matched, ran a terraform plan then apply and it created my resource without issue and assigned the correct permission to the DES. I confirmed this within the Azure portal and could see that the managed disk was encrypted with the DES and the DES was pointing back to a key within Key Vault. I was able to replicate this a number of times and found that resources where created successfully each time I set the Terraform Name and Azure Name to the same and unsuccessfully every time they where not. 

At this point I'm at a loss as to why this would affect anything and due to me wanting to place this within a module format with for_each loop creation methods for all resources, makes this very tricky. Is someone able to assist me with this error as I'm unsure what I am doing wrong? 

Link to DES for CMK creation:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/disk_encryption_set/

Error: 
Error: creating Windows Virtual Machine: (Name "addc-002" / Resource Group "rg-default-identity-001-dev"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="KeyVaultAccessForbidden" Message="Unable to access key vault resource '[https://keyvlt-identity-1.vault.azure.net/keys/default-gen-key-002/***************************](https://urldefense.com/v3/__https:/keyvlt-identity-1.vault.azure.net/keys/default-gen-key-002/**Z__;KioqKioqKioqKioqKioqKioqKioqKioqKioq!!FL6IzD25AAJiiok!UbruCiKZokHr__1j6FQXxfeNJG1oIXvxGh88920HAfdnTaOPx_XvvpjDllVjtbwmA_10rkHFA5iRpojv0GgaHqeFanfVXA$)' to enable encryption at rest. Please grant get, wrap and unwrap key permissions to disk encryption set 'des-001'. Please visit [https://aka.ms/keyvaultaccessssecmk](https://urldefense.com/v3/__https:/aka.ms/keyvaultaccessssecmk__;!!FL6IzD25AAJiiok!UbruCiKZokHr__1j6FQXxfeNJG1oIXvxGh88920HAfdnTaOPx_XvvpjDllVjtbwmA_10rkHFA5iRpojv0GgaHqcGN53Arg$) for more information."
│
│   with module.virtual_machines.azurerm_windows_virtual_machine.vm_config["addc-002"],
│   on modules/virtual_machines/main.tf line 51, in resource "azurerm_windows_virtual_machine" "vm_config":
│   51: resource "azurerm_windows_virtual_machine" "vm_config" {

Code:
resource "azurerm_key_vault" "key-vault" {
  name                        = "jc-nttdata-des-test-kv"
  location                    = local.location.uksouth
  resource_group_name         = "jc-rg-test-p-uks-001"
  tenant_id                   = data.azurerm_client_config.workingdirectory.tenant_id
  sku_name                    = "premium"
  enabled_for_disk_encryption = true
  enable_rbac_authorization   = false
  enabled_for_deployment      = true
  enabled_for_template_deployment = true
  purge_protection_enabled    = true
}

resource "azurerm_key_vault_key" "key-vault-key" {
  name          = "des-test-key"
  key_vault_id  = azurerm_key_vault.key-vault.id
  key_type      = "RSA"
  key_size      = "2048"
  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
  depends_on = [azurerm_key_vault_access_policy.example-user]
}

resource "azurerm_disk_encryption_set" "des-set" {
  name                = "des-set"
  resource_group_name = "jc-rg-test-p-uks-001"
  location            = local.location.uksouth
  key_vault_key_id    = azurerm_key_vault_key.key-vault-key.id

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_key_vault_access_policy" "example-disk" {
  key_vault_id = azurerm_key_vault.key-vault.id

  tenant_id = azurerm_disk_encryption_set.des-set.identity.0.tenant_id
  object_id = azurerm_disk_encryption_set.des-set.identity.0.principal_id

  key_permissions = [
    "Create",
    "Delete",
    "Get",
    "Purge",
    "Recover",
    "Update",
    "List",
    "Decrypt",
    "Sign",
    "UnwrapKey",
    "WrapKey"
  ]
}

resource "azurerm_key_vault_access_policy" "example-user" {
  key_vault_id = azurerm_key_vault.key-vault.id

  tenant_id = data.azurerm_client_config.workingdirectory.tenant_id
  object_id = data.azurerm_client_config.workingdirectory.object_id

  key_permissions = [
    "Create",
    "Delete",
    "Get",
    "Purge",
    "Recover",
    "Update",
    "List",
    "Decrypt",
    "Sign"
  ]
}

resource "azurerm_role_assignment" "example-disk" {
  scope                = azurerm_key_vault.key-vault.id
  role_definition_name = "Key Vault Crypto Service Encryption User"
  principal_id         = azurerm_disk_encryption_set.des-set.identity.0.principal_id
}

resource "azurerm_managed_disk" "test-disk" {
  name = "mytestdisk"
  resource_group_name = "jc-rg-test-p-uks-001"
  location = local.location.uksouth
  storage_account_type = "Standard_LRS"
  create_option = "Empty"
  disk_size_gb = "10"
  disk_encryption_set_id = azurerm_disk_encryption_set.des-set.id
  #security_type = "ConfidentialVM_DiskEncryptedWithCustomerKey"
  #secure_vm_disk_encryption_set_id = azurerm_disk_encryption_set.des-set.id
  /*encryption_settings {
    enabled = true
    disk_encryption_key{
      azurerm_disk_encryption_set.des-set.id
    }
  }*/
}

resource "azurerm_storage_account" "stjcnttteststore" {
  name = "stjcnttteststore"
  resource_group_name = "jc-rg-test-p-uks-001"
  location = local.location.uksouth
  account_tier = "Standard"
  account_replication_type = "LRS"
  
  identity {
    type = "SystemAssigned"
  }
}

Thanks,
Jack

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
