### ISSUE TITLE
Error: loading Role Definition List: could not find role 'Global Reader'

### ISSUE THREAD

**Issue by nimblenitin** [hashicorp/terraform#31579]
I am trying to assign azure ad role- global reader to service principal in terraform which is tied to an application and then to a container. It says role not found. I tried using template id instead of role name in azurerm_role_assignment, that also throws an error. 

I am getting this error on trying to assign global reader role to service principal-

```
Error: loading Role Definition List: could not find role 'Global Reader'
│
│ with module.infrastructure_cloud-scanner-app.azurerm_role_assignment.main["/subscriptions/aeca76e8-1861-4aed-b28a-b8c48923f89b"],
│ on ../../modules/infrastructure/cloud-scanner-app/[main.tf](http://main.tf/) line 49, in resource "azurerm_role_assignment" "main":
│ 49: resource "azurerm_role_assignment" "main" {
```

### Terraform Version

```
...
```

### Terraform Configuration Files

```terraform
...
```

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
