### ISSUE TITLE
google_cloud_scheduler_job error in schedule or time zone

### ISSUE THREAD

**Issue by bahag-petreccad** [hashicorp/terraform#31571]
The documentation https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_scheduler_job
says that the parameters schedule and time_zone are optional, in order to create a scheduled event that never happens.

However, the following code:
```
resource "google_cloud_scheduler_job" "job" {
  name        = "trigger-clusters-pipe"
  description = "Triggers clusters vertex pipe"

  pubsub_target {
     topic_name = "projects/${var.project}/topics/vertex-compute-clusters-pipeline"
    data       = base64encode("{\"process_data_at\":\"2022-07-01\"}")
  }
} 
```
triggers the error
```
│ Error: Error creating Job: googleapi: Error 400: Schedule or time zone is invalid.
│ 
│   with google_cloud_scheduler_job.job,
│   on scheduler.tf line 1, in resource "google_cloud_scheduler_job" "job":
│    1: resource "google_cloud_scheduler_job" "job" {
│ 
Error: Process completed with exit code 1.
```
we have version 4.31.0

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
