### ISSUE TITLE
Terraform CLI-OCI non-compatibility for IAM Policies 

### ISSUE THREAD

**Issue by cbichsel-personal** [hashicorp/terraform#31574]
I managed to create oci_identity_policy resources through the CLI, including list of string variables for the "statements".  I have tried to execute the same terraform project through both Morpheus Data and OCI Resource Manager, and it errors out on the "Statements" attribute.  Notice the extra parsing characters that don't exist in my original resource declaration.

ORIGINAL:
variable "security_policy_statements" {
    default = ["Allow group security_group to manage all-resources in compartment landingzone_compartment:security_compartment",
               "Allow group security_group to manage cloud-guard-family in tenancy",
               "Allow group security_group to manage cloudevents-rules in tenancy",
               "Allow group security_group to read tenancies in tenancy",
               "Allow group security_group to read threat-intel-family in tenancy",
               "Allow group security_group to use cloud-shell in tenancy"]
}

Error: Incorrect attribute value type
  on IAM_Policies.tf line 8, in resource "oci_identity_policy" "security_policy" 
   8:     statements = var.security_policy_statements
    ├────────────────
    │ var.security_policy_statements is "[ \""Allow group security_group to manage all-resources in compartment landingzone_compartment:security_compartment\"",\""Allow group security_group to manage cloud-guard-family in tenancy\"",\""Allow group security_group to manage cloudevents-rules in tenancy\"",\""Allow group security_group to read tenancies in tenancy\"",\""Allow group security_group to read threat-intel-family in tenancy\"",\""Allow group security_group to use cloud-shell in tenancy\"" ]"
Inappropriate value for attribute "statements"  list of string required.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
