### ISSUE TITLE
Resource aws_route53_zone passes TF plan if TTL is not defined

### ISSUE THREAD

**Issue by lpossamai** [hashicorp/terraform#31577]
The resource `aws_route53_zone` [requires](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record#ttl) the `ttl` argument for non-alias records.

However, running `terraform plan` without the `ttl` specified, passes, and `terraform apply` will fail because of missing argument.

Terraform Plan:
```terraform
  # module.ses.aws_route53_record.test_foo_com_dkim_verification1[0] will be created
  + resource "aws_route53_record" "test_foo_com_dkim_verification1" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "test._domainkey.test.foo.com"
      + records         = [
          + "3_______x.dkim.amazonses.com",
        ]
      + type            = "CNAME"
      + zone_id         = "Z0_______G"
    }
```

Terraform Apply:
```terraform
│ Error: provider.aws: aws_route53_record: test_foo_com_dkim_verification1: "ttl": required field is not set
│ 
│   with module.ses.aws_route53_record.test_foo_com_dkim_verification1[0],
│   on modules/ses/ses.tf line 48, in resource "aws_route53_record" "test_foo_com_dkim_verification1":
│   48: resource "aws_route53_record" "test_foo_com_dkim_verification1" {
```

### Terraform Version
```
1.1.5
```

### Terraform Configuration Files
```terraform
resource "aws_route53_record" "test_foo_com_dkim_verification1" {
  count   = terraform.workspace == "test" ? 1 : 0
  zone_id = var.route53_${terraform.workspace}_public_zone
  name    = "test._domainkey.${terraform.workspace}.foo.com"
  type    = "CNAME"
  records = ["3_______x.dkim.amazonses.com"]
}
```

### Expected Behavior
`terraform plan` should fail as `ttl` was not provided within the `aws_route53_record.test_foo_com_dkim_verification1` resource.

### Actual Behavior
`terraform plan` passed, causing `terraform apply` to fail.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
