### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by ChrisGodfreeAbrdn** [hashicorp/terraform#31582]
### Terraform Version

```
v1.2.6
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

must have at least one character

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x1fb8940, 0xc0008ab7b0})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/hashicorp/terraform/internal/addrs.MustParseProviderPart({0x0?, 0x0?})
	/home/circleci/project/project/internal/addrs/provider.go:449 +0x4c
github.com/hashicorp/terraform/internal/addrs.NewDefaultProvider(...)
	/home/circleci/project/project/internal/addrs/provider.go:122
github.com/hashicorp/terraform/internal/addrs.ImpliedProviderForUnqualifiedType({0x0?, 0x0?})
	/home/circleci/project/project/internal/addrs/provider.go:114 +0x11b
github.com/hashicorp/terraform/internal/configs.validateProviderConfigs.func1(0xc00061c1c0?)
	/home/circleci/project/project/internal/configs/provider_validation.go:161 +0x145
github.com/hashicorp/terraform/internal/configs.validateProviderConfigs(0xc0000ac000, 0xc000900700, 0x0)
	/home/circleci/project/project/internal/configs/provider_validation.go:180 +0x14bd
github.com/hashicorp/terraform/internal/configs.validateProviderConfigs(0x0, 0xc00086c2a0, 0x0)
	/home/circleci/project/project/internal/configs/provider_validation.go:50 +0x610
github.com/hashicorp/terraform/internal/configs.BuildConfig(0xc000878580, {0x29fe200, 0xc0007a1b90})
	/home/circleci/project/project/internal/configs/config_build.go:34 +0xf0
github.com/hashicorp/terraform/internal/configs/configload.(*Loader).LoadConfig(0xc00079d4f0, {0x24534ee?, 0x2f?})
	/home/circleci/project/project/internal/configs/configload/loader_load.go:33 +0xfd
github.com/hashicorp/terraform/internal/command.(*Meta).loadConfig(0x0?, {0xc00069ce80?, 0x0?})
	/home/circleci/project/project/internal/command/meta_config.go:47 +0x98
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc000655860, {0xc00015a020, 0x8, 0xe})
	/home/circleci/project/project/internal/command/init.go:207 +0x139d
github.com/mitchellh/cli.(*CLI).Run(0xc0006b72c0)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.4/cli.go:262 +0x5f8
main.realMain()
	/home/circleci/project/project/main.go:312 +0x15d4
main.main()
	/home/circleci/project/project/main.go:58 +0x19

### Expected Behavior
Terraform initialised

### Actual Behavior
Terraform crashed

### Steps to Reproduce
terraform init

### Additional Context
Running via an Azure DevOps pipeline; only change from previous successful execution was to the value of variables in a map

**Comment by jbardin** [comment]
Hi @ChrisGodfreeAbrdn,

Thanks for filing the issue. In order to diagnose the problem, we would need some more information, namely a sample configuration which can replicate the problem. 

Thanks!

**Comment by ChrisGodfreeAbrdn** [comment]
Hi @jbardin, made another change and it works successfully - do you still want configuration to diagnose?

**Comment by jbardin** [comment]
If you could show just what that change was, it could help diagnose the problem. While it was likely a configuration error, it would be better if Terraform could catch the error before a panic.

Thanks!

**Comment by jbardin** [comment]
Looks like we have a reproduction in #31572.
Thanks
