### ISSUE TITLE
error collecting instance settings: empty result when running terraform apply after terraform state rm

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/terraform#31594]
I had deployed an EC2 instance with terraform.
I then removed the EC2 instance from terraform with:

    $ terraform state rm aws_instance.instance_1

now, when I try to re-create the instance I see an error:

    $ terraform apply -auto-approve
    

> Error: error collecting instance settings: empty result
>
>  with aws_instance.instance_1,
>       on instances.tf line 17, in resource "aws_instance" "instance1":
>       17: resource "aws_instance" "instance1" {

Note that `terraform plan` works as expected and shows the instance to be created:

### Terraform Version

v.1.2.4

**Comment by paololazzari** [comment]
Apparently this was caused by an attempt to launch an instance from an AMI that was no longer available. 

Can the error message be improved?

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
