### ISSUE TITLE
terraform crash report

### ISSUE THREAD

**Issue by YooWaan** [hashicorp/terraform#31599]
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 3972 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x88
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x20
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:55 +0x1a0
panic({0x10285d3e0, 0x1041094b0})
	/usr/local/go/src/runtime/panic.go:1038 +0x21c
github.com/hashicorp/terraform/internal/addrs.Module.String({0x0, 0x2, 0x2})
	/Users/distiller/project/project/internal/addrs/module.go:37 +0x58
github.com/hashicorp/terraform/internal/addrs.ConfigResource.String({{}, {0x0, 0x2, 0x2}, {{}, 0x4d, {0x14002ea6b00, 0x1a}, {0x1400318ac90, 0x3}}})
	/Users/distiller/project/project/internal/addrs/resource.go:380 +0x78
github.com/hashicorp/terraform/internal/terraform.depsEqual.func1.1(0x0, 0x1e)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:279 +0x7c
sort.doPivot_func({0x140048acfa0, 0x14004895950}, 0x0, 0x24)
	/usr/local/go/src/sort/zfuncversion.go:89 +0x248
sort.quickSort_func({0x140048acfa0, 0x14004895950}, 0x0, 0x24, 0xc)
	/usr/local/go/src/sort/zfuncversion.go:143 +0x80
sort.Slice({0x10270af40, 0x140042f7248}, 0x140048acfa0)
	/usr/local/go/src/sort/slice.go:20 +0xdc
github.com/hashicorp/terraform/internal/terraform.depsEqual({0x140042f9b00, 0x24, 0x24}, {0x1400343c400, 0x24, 0x24})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:284 +0x108
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0x1400251d2c0, {0x102cd7780, 0x14001b62460})
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:219 +0xa88
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x1400251d2c0, {0x102cd7780, 0x14001b62460}, 0x2)
	/Users/distiller/project/project/internal/terraform/node_resource_plan_instance.go:54 +0x94
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0x14000f55dc0, {0x102cd7780, 0x14001b62460}, {0x12dc2b360, 0x1400251d2c0})
	/Users/distiller/project/project/internal/terraform/graph_walk_context.go:133 +0x9c
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x102b95660, 0x1400251d2c0})
	/Users/distiller/project/project/internal/terraform/graph.go:74 +0x244
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14000af5c80, {0x102b95660, 0x1400251d2c0}, 0x140041eb240)
	/Users/distiller/project/project/internal/dag/walk.go:381 +0x31c
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/distiller/project/project/internal/dag/walk.go:304 +0xe0c

**Comment by jbardin** [comment]
Hi @YooWaan,

Thanks for reporting this. If you can reproduce the crash with a current release of Terraform along with the information requested in the issue template, please add the information to the issue or file a new one.

Thanks!
