### ISSUE TITLE
Crash creating awkward map

### ISSUE THREAD

**Issue by xposix** [hashicorp/terraform#31611]
### Terraform Version

```
Terraform v1.2.6
on darwin_arm64
```

### Terraform Configuration Files

```terraform
data "aws_ssm_parameter" "user_facing_zone_id" {
  count = var.environment_name == "prod" ? 1 : 0
  name  = "/clz/route53/${var.environment_name}/user_facing_zone_id"
}

data "aws_ssm_parameter" "application_user_facing_domain_name" {
  count = var.environment_name == "prod" ? 1 : 0
  name  = "/${var.environment_name}/route53/xxxxxx_integration/user_facing_domain_name"
}

locals {
 # I'm trying to create a map from two known values
  prod_alternative_domain_names_zone_ids_map = var.environment_name == "prod" ? [
    { "xxxxx.mycompany.io" = "Z0ASKDJQ5V2PQBQCW8K" }, 
    tomap({ data.aws_ssm_parameter.application_user_facing_domain_name[0].value = data.aws_ssm_parameter.user_facing_zone_id[0].value })
  ] : []
}
```

### Debug Output

https://gist.github.com/xposix/bf37d950d53e7fcbce322fc1f65ac5e6

### Expected Behavior
Provide an error without crashing

### Actual Behavior
Terraform crashed

### Steps to Reproduce

TF_LOG=trace terraform apply -auto-approve \
                -lock=true \
                -compact-warnings \
                -var="environment_name=prod" \
                -var="environment_type=prod" \
                -var-file ../../env-common.vars.json \
                -var-file ../../env-prod.vars.json \
                -refresh=true

**Comment by jbardin** [comment]
Hi @xposix, this still produces the same crash with an identical stack trace as the linked issue. The error is happening during evaluation type unification in the upstream cty library.

**Comment by xposix** [comment]
Right, so the root cause is the same. No worries, thanks!
