### ISSUE TITLE
Amazon RDS provider use wrong value when define in_gress 

### ISSUE THREAD

**Issue by udomsak** [hashicorp/terraform#3161]
I use  Terraform as AWS provider with RDS service for basic initial value everything it ok.  But when i define value in 'aws_security_group'  in in_gress section something wrong. 

My case i'm deploy service across zone  with RDS i write to use public ip from my zone to RDS but Terraform replace my define value to  security group id instead. 

That make wrong result.  

:) , Thank you for your work hard to contribute.

**Comment by catsby** [comment]
Hey @udomsak – sorry for the trouble here. Do you possibly have an example Terraform configuration file that demonstrates this issue? If so, please be sure to remove any secrets in anything you share 

Thanks!

**Comment by catsby** [comment]
Closing after no reply. If you have a configuration or more details, please let us know!
