### ISSUE TITLE
Error: Module cannot be found in the module registry at app.terraform.io.

### ISSUE THREAD

**Issue by sr-mpamera** [hashicorp/terraform#31629]
Hi there,

Error while running terraform init.

```
Error: Module not found

Module "workspace-test" (from workspace-test.tf:1) cannot be found in the
module registry at app.terraform.io.
```
Terraform version used 0.14.10

configuration

```
module "workspace-test" {
  source            = "app.terraform.io/org_name/workspace/tfe"
  version           = "~> 0.1.1"
  name              = "github-test"
  repo_name         = "tf-github"
  working_directory = "teams/team-test"
}
```

**Comment by crw** [comment]
Thanks for the report! As a Terraform Cloud customer, I suggest filing this issue with our Support team, who can help you get to the bottom of the issue. https://support.hashicorp.com/hc/en-us/requests/new 

Thanks!

**Comment by crw** [comment]
Hello, I'm going to close this issue as it appears to be an issue that should go through the support channels. You can also trying asking usage questions on [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
