### ISSUE TITLE
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by thrinadh238** [hashicorp/terraform#31626]
Hi there,

while we do terraform plan getting terraform crash error in specific directory.

Terraform version: 0.12.31
[crash.log](https://github.com/hashicorp/terraform/files/9310295/crash.log)

================================================================================
panic: inconsistent list element types (cty.Object(map[string]cty.Type{"Allow all egress":cty.String}) then cty.Object(map[string]cty.Type{"West NVE for backup":cty.String}))

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.ListVal(0xc000400000, 0x77, 0x77, 0xc0004f5200, 0xc000403110, 0x246c9e0, 0x3682188)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/value_init.go:166 +0x4bf
github.com/zclconf/go-cty/cty/convert.conversionTupleToList.func2(0x246cb20, 0xc0004f42e0, 0x1aff660, 0xc0004f4300, 0xc000113620, 0x1, 0x1, 0xc000556000, 0x10, 0x10, ...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion_collection.go:267 +0x54a
github.com/zclconf/go-cty/cty/convert.getConversion.func1(0x246cb20, 0xc0004f42e0, 0x1aff660, 0xc0004f4300, 0x0, 0x0, 0x0, 0xc0003a2450, 0xc000113610, 0x246ca20, ...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:46 +0x1ad
github.com/zclconf/go-cty/cty/convert.retConversion.func1(0x246cb20, 0xc0004f42e0, 0x1aff660, 0xc0004f4300, 0xc000113610, 0x1, 0x1, 0x0, 0xc00048e448, 0xc00048e450)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/conversion.go:179 +0x6b
github.com/zclconf/go-cty/cty/convert.Convert(0x246cb20, 0xc0004f42e0, 0x1aff660, 0xc0004f4300, 0x246ca20, 0xc000135ef0, 0x1, 0x1, 0x1, 0x6, ...)
        /go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/convert/public.go:51 +0x1af
github.com/hashicorp/terraform/configs.decodeVariableBlock(0xc00037dd40, 0x0, 0x1f1cac7, 0x8, 0x1, 0x0)
        /home/circleci/project/project/configs/named_values.go:109 +0x8bb
github.com/hashicorp/terraform/configs.(*Parser).loadConfigFile(0xc0003338e0, 0xc000576cc0, 0xd, 0x0, 0x1, 0xc000590308, 0x0, 0x1)
        /home/circleci/project/project/configs/parser_config.go:96 +0x1c1e
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigFile(...)
        /home/circleci/project/project/configs/parser_config.go:22
github.com/hashicorp/terraform/configs.(*Parser).loadFiles(0xc0003338e0, 0xc000587380, 0x3, 0x4, 0x0, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /home/circleci/project/project/configs/parser_config_dir.go:77 +0x343
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigDir(0xc0003338e0, 0x1f1514d, 0x1, 0x0, 0x1, 0x0, 0xc000555940)
        /home/circleci/project/project/configs/parser_config_dir.go:37 +0x121
github.com/hashicorp/terraform/command.(*Meta).loadSingleModule(0xc000425340, 0x1f1514d, 0x1, 0xc000555940, 0x1966d4c, 0xc0000a3380, 0x1)
        /home/circleci/project/project/command/meta_config.go:113 +0x136
github.com/hashicorp/terraform/command.(*Meta).loadBackendConfig(0xc000425340, 0xc00004a004, 0x40, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/project/command/meta_config.go:175 +0x43
github.com/hashicorp/terraform/command.(*ApplyCommand).Run(0xc000425340, 0xc00000c090, 0x0, 0x0, 0xc0003d4c70)
        /home/circleci/project/project/command/apply.go:132 +0x13a5
github.com/mitchellh/cli.(*CLI).Run(0xc0000e3680, 0xc0000e3680, 0xc000555d90, 0x1)
        /go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1f1
main.wrappedMain(0x0)
        /home/circleci/project/project/main.go:251 +0xc8a
main.realMain(0x0)
        /home/circleci/project/project/main.go:106 +0xb4
main.main()
        /home/circleci/project/project/main.go:42 +0x3b

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
==========================================================================

**Comment by jbardin** [comment]
Hi @thrinadh238,

Thanks for filing the issue. Terraform v0.12 is no longer being developed, and the crash you encountered is likely fixed in a subsequent release. If you still have a problem after upgrading to a current release, please file a new issue with the information requested in the issue template.

Thanks!
