### ISSUE TITLE
namespaces "<namespace>" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "<Namespace>"

### ISSUE THREAD

**Issue by Kundan9** [hashicorp/terraform#31621]

**Comment by Kundan9** [comment]
Hi there,

I am facing one strange issue, 
Context- a month back i had deployed the gke private cluster in GCP VPC Subnet.  i had added secondary ip rages to my subnet  for gke and few extra ranges. It went fine and everything is working fine. It was deployed through terraform "google_compute_subnetwork" resource 

Issue- Now I want to remove those extra secondary ranges which are not used in my subnet, but now when i am commenting or removing the secondary range from the terraform computer subnetwork resource code , it give me the below error in plan for all the resources which are created in gke cluster, e.g namespace, role binding, secrete.

Logically it should shows me the changes for my network subnet changes in plan but nowhere it is showing that and just shows below error in plan .

i did tried all the possible ways, even last i tried to remove the ranges from tfstate file and  from code as well, but still it shows me the same error.

i am deploying through gitlab pipeline, i have verified all the access for sa account as well that looks fine.

strange thing is that, when i keep the secondary range code as is in terraform , the plan get successful.

Putting the issue here , because not able to find whats going wrong. 

Error - namespaces "<namespace>" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "<Namespace>"

Terraform version -1.1.9
Kubernetes provider version - 2.11.0

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
