### ISSUE TITLE
Terraform crash error when running terraform plan

### ISSUE THREAD

**Issue by NinaGo** [hashicorp/terraform#31631]
I'm running terraform version 0.13.1, on plan I get the following error:

10:29:53  [0m[1mRefreshing Terraform state in-memory prior to plan...[0m
10:29:53  The refreshed state will be used to calculate this plan, but will not be
10:29:53  persisted to local or remote state storage.
10:29:53  [0m
10:30:00  [0m[1mdata.aws_ami.bastion_ami: Refreshing state...[0m
10:30:00  [0m[1mdata.aws_ami.eks_worker_ami: Refreshing state...[0m
10:30:00  
10:30:00  ------------------------------------------------------------------------
10:30:07  panic: not a collection type
10:30:07  
10:30:07  goroutine 953 [running]:
10:30:07  github.com/zclconf/go-cty/cty.Type.ElementType(0x2ce50a0, 0xc00217e0c0, 0xc000da64a8, 0x8)
10:30:07  	/home/circleci/project/project/vendor/github.com/zclconf/go-cty/cty/collection.go:25 +0xba
10:30:07  github.com/hashicorp/terraform/terraform.createEmptyBlocks(0xc0017cd080, 0x2ce50a0, 0xc00217e120, 0x2300040, 0xc002c3ed20, 0x2ce50a0, 0xc00217e340, 0x2300040, 0xc0028b34d0)
10:30:07  	/home/circleci/project/project/terraform/eval_read_data_plan.go:242 +0x202
10:30:07  github.com/hashicorp/terraform/terraform.dataObjectHasChanges(0xc0017cd080, 0x2ce50a0, 0xc00217e120, 0x2300040, 0xc002c3ed20, 0x2ce50a0, 0xc00217e340, 0x2300040, 0xc0028b34d0, 0x0, ...)
10:30:07  	/home/circleci/project/project/terraform/eval_read_data_plan.go:211 +0x19e
10:30:07  github.com/hashicorp/terraform/terraform.(*evalReadDataPlan).Eval(0xc000349d10, 0x2d26860, 0xc0019b4270, 0x1, 0x1, 0x0, 0x0)
10:30:07  	/home/circleci/project/project/terraform/eval_read_data_plan.go:107 +0x1238
10:30:07  github.com/hashicorp/terraform/terraform.EvalRaw(0x2c7d420, 0xc000349d10, 0x2d26860, 0xc0019b4270, 0x0, 0x0, 0x0, 0x0)
10:30:07  	/home/circleci/project/project/terraform/eval.go:49 +0xc7
10:30:07  github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc000a18f60, 0x2d26860, 0xc0019b4270, 0x1, 0x1, 0x6, 0xc000118c50)
10:30:07  	/home/circleci/project/project/terraform/eval_sequence.go:20 +0xfd
10:30:07  github.com/hashicorp/terraform/terraform.EvalRaw(0x2c7ce80, 0xc000a18f60, 0x2d26860, 0xc0019b4270, 0x22b4bc0, 0x3fa2622, 0x2214980, 0xc001c58e10)
10:30:07  	/home/circleci/project/project/terraform/eval.go:49 +0xc7
10:30:07  github.com/hashicorp/terraform/terraform.Eval(0x2c7ce80, 0xc000a18f60, 0x2d26860, 0xc0019b4270, 0xc000a18f60, 0x2c7ce80, 0xc000a18f60, 0x0)
10:30:07  	/home/circleci/project/project/terraform/eval.go:35 +0x4d
10:30:07  github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2645300, 0xc0020e96c0, 0x0, 0x0, 0x0)
10:30:07  	/home/circleci/project/project/terraform/graph.go:73 +0xc77
10:30:07  github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc000118a80, 0x2645300, 0xc0020e96c0, 0xc000fa2440)
10:30:07  	/home/circleci/project/project/dag/walk.go:387 +0x357
10:30:07  created by github.com/hashicorp/terraform/dag.(*Walker).Update
10:30:07  	/home/circleci/project/project/dag/walk.go:309 +0x11d7
10:30:07  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
10:30:07  
10:30:07  Terraform crashed! This is always indicative of a bug within Terraform.
10:30:07  A crash log has been placed at "crash.log" relative to your current
10:30:07  working directory. It would be immensely helpful if you could please
10:30:07  report the crash with Terraform[1] so that we can fix this.
10:30:07  
10:30:07  When reporting bugs, please include your terraform version. That
10:30:07  information is available on the first line of crash.log. You can also
10:30:07  get it by running 'terraform --version' on the command line.
10:30:07  
10:30:07  SECURITY WARNING: the "crash.log" file that was created may contain 
10:30:07  sensitive information that must be redacted before it is safe to share 
10:30:07  on the issue tracker.
10:30:07  
10:30:07  [1]: https://github.com/hashicorp/terraform/issues
10:30:07  
10:30:07  !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
10:30:07  terraform plan failed.

**Comment by jbardin** [comment]
Hi @NinaGo,

Thanks for reporting the crash. Terraform v0.13 is no longer being developed, and the crash has likely been fixed in a later release. If you can reproduce the problem with a current release, please file a new issue with the information requested in the issue template.

Thanks!
