### ISSUE TITLE
The given key does not identify an element in this collection value.

### ISSUE THREAD

**Issue by aman-w-kumar** [hashicorp/terraform#31638]
### Terraform Version

Terraform v1.2.6
```
...
```

### Terraform Configuration Files

resource "azurerm_storage_account" "storage" {
 for_each = local.storage_accounts
  name                     = each.key
  resource_group_name      = each.value.resource_group_name
  location                 = each.value.location
  account_tier             = each.value.account_tier  
  account_replication_type = each.value.account_replication_type 
  tags     = each.value.tags
}

resource "azurerm_app_service_plan" "plan" {
  for_each = local.service_plans
  name                = each.key
  location            = each.value.location
  resource_group_name = each.value.resource_group_name
  kind                = each.value.kind 
  tags     = each.value.tags
  sku {
    tier = each.value.sku.tier 
    size = each.value.sku.size 
  }
  depends_on = [
    azurerm_storage_account.storage
  ]
}

resource "azurerm_function_app" "function" {
    for_each = local.functions
  name                       = each.key
  location                   = each.value.location
  resource_group_name        = each.value.resource_group_name
  **app_service_plan_id        = azurerm_app_service_plan.plan[each.key].id**
  storage_account_name       = each.value.storage_account_name
  **storage_account_access_key = azurerm_storage_account.storage[each.key].primary_access_key**
  tags     = each.value.tags
  depends_on = [
    azurerm_storage_account.storage,
    azurerm_app_service_plan.plan
  ]
}
```terraform
...
```

### Expected Behavior

it should read resource reference each.key from source (remote) resource reference but reading each.key from local resource"/
### Actual Behavior

I'm getting an error
 Error: Invalid index
│ 
│   on modules/functions/main.tf line 32, in resource "azurerm_function_app" "function":
│   32:   app_service_plan_id        = azurerm_app_service_plan.plan[each.key].id
│     ├────────────────
│     │ azurerm_app_service_plan.plan is object with 1 attribute "sp-xxxxxxxxxxxx"
│     │ each.key is "func-xxxxxxxxxxxx"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on modules/functions/main.tf line 34, in resource "azurerm_function_app" "function":
│   34:   storage_account_access_key = azurerm_storage_account.storage[each.key].primary_access_key
│     ├────────────────
│     │ azurerm_storage_account.storage is object with 1 attribute "stxxxxxxxxxxxxxx"
│     │ each.key is "func-xxxxxxxxxxxxx"
│ 
│ The given key does not identify an element in this collection value.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
