### ISSUE TITLE
Error when creating a storage account in germanywestcentral

### ISSUE THREAD

**Issue by antonia-adler** [hashicorp/terraform#31630]
I try to create a storage account in germanywestcentral:

``` 
resource "azurerm_storage_account" "storage_acc" {
  name                            = "storage_account_name"
  resource_group_name             = "resource_group_name"
  location                        = "germanywestcentral"
  account_tier                    = var.account_tier
  account_replication_type        = var.account_replication_type
  account_kind                    = var.account_kind
  allow_nested_items_to_be_public = false
  enable_https_traffic_only       = true
  min_tls_version                 = "TLS1_2"
  is_hns_enabled                  = true
}
```
And I receive the following error message:
``` 
 Error: creating Azure Storage Account "storage_account_name": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="LocationNotValid" Message="Supplied location germanywestcentral is not valid."
```
I can create a storage account with the same configuration via the Azure UI and I can also create a storage account with the same configuration but in a different location. I guess it is a terraform problem with the location "germanywestcentral".

Thanks for your help!

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
