### ISSUE TITLE
Not able to use output of module as input to resource 

### ISSUE THREAD

**Issue by samarth3112** [hashicorp/terraform#31640]
Hello ,

Not able to consume module output as input to resource .

Module is defined in output.tf
output "subnet_id" {
  value = module.subnet.id
}

Now while try to use it in resource 

resource "azurerm_network_interface" "main" {
  name                = "my-nic"
  location            = var.location
  resource_group_name =  var.resource_group

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = "${module.custommodule.subnet_id}"
    private_ip_address_allocation = "Dynamic"
  }
}

Getting error

│ Error: Incorrect attribute value type
│ 
│   on nic.tf line 23, in resource "azurerm_network_interface" "main":
│   23:     subnet_id                     = "${module.custommodule.subnet_id}"
│     ├────────────────
│     │ module.custommodulesubnet_id is a object, known only after apply
│ 
│ Inappropriate value for attribute "subnet_id": string required.

-->

### Terraform Version

Terraform v1.2.7
on darwin_amd64

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
