### ISSUE TITLE
lifecycle replace_triggered_by does not replace when referenced resource has a noop delete

### ISSUE THREAD

**Issue by andyroyle** [hashicorp/terraform#31644]
### Terraform Version

```
v1.2.7
```

### Terraform Configuration Files

```terraform
resource "time_rotating" "rotate" {
  rotation_minutes = 1
}

resource "local_file" "test" {
  filename = "${path.module}/file.txt"
  content  = "foo"

  lifecycle {
    replace_triggered_by = [
      time_rotating.rotate.rotation_rfc3339
    ]
  }
}
```
### Debug Output

[debug output](https://gist.github.com/andyroyle/4c4933a38906fc2f795a3a20ca25cb5a)

### Expected Behavior

The `local_file` resource should be replaced when `time_rotating.rotate` expires.

### Actual Behavior

When using `time_rotating` in the `replace_triggered_by` field of another resource (in this case, a `local_file`) the downstream resource is not replaced.

The `time_rotating` resource is replaced without replacing the downstream resource.

```shell
time_rotating.rotate: Refreshing state... [id=2022-08-15T12:53:48Z]
local_file.test: Refreshing state... [id=0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # time_rotating.rotate will be created
  + resource "time_rotating" "rotate" {
      + day              = (known after apply)
      + hour             = (known after apply)
      + id               = (known after apply)
      + minute           = (known after apply)
      + month            = (known after apply)
      + rfc3339          = (known after apply)
      + rotation_minutes = 1
      + rotation_rfc3339 = (known after apply)
      + second           = (known after apply)
      + unix             = (known after apply)
      + year             = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
time_rotating.rotate: Creating...
time_rotating.rotate: Creation complete after 0s [id=2022-08-15T13:04:53Z]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

The terraform plan shows a `create` for the `time_rotating` resource, even though it is a `replace`. This seems to be related to the fact that the `Delete` step for the `time_rotating` resource is `schema.NoopContext` ([code](https://github.com/hashicorp/terraform-provider-time/blob/main/internal/tftime/resource_time_rotating.go#L28)).

When using another resource (e.g. `null_resource`), where the Delete step is [functionally a Noop](https://github.com/hashicorp/terraform-provider-null/blob/main/internal/provider/resource.go#L46-L49), but not semantically, it does work.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply --auto-approve`
3. `sleep 60` (wait 1 minute for the time_rotating to expire)
4. `terraform apply --auto-approve`

### Additional Context

I am opening this as a terraform-core bug, rather than a provider bug because it feels like this is a problem in the logic that identifies when `replace_triggered_by` is triggered. The `time_rotating` resource has no Delete step, so terraform sees the resulting change as a `create` instead of a `replace` even though, it is actually a `replace`.

This might be intentional, but it feels like a bug.

You can work around this by using a `null_resource` as an intermediary:
```terraform
resource "time_rotating" "rotate" {
  rotation_minutes = 1
}

resource "null_resource" "rotate" {
  triggers = {
    rotate = time_rotating.rotate.rotation_rfc3339
  }
}

resource "local_file" "test" {
  filename = "${path.module}/file.txt"
  content  = "foo"

  lifecycle {
    replace_triggered_by = [
      null_resource.rotate
    ]
  }
}
```

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # local_file.test will be replaced due to changes in replace_triggered_by
-/+ resource "local_file" "test" {
      ~ id                   = "0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

  # null_resource.rotate must be replaced
-/+ resource "null_resource" "rotate" {
      ~ id       = "7716790656126891347" -> (known after apply)
      ~ triggers = {
          - "rotate" = "2022-08-15T13:12:25Z"
        } -> (known after apply) # forces replacement
    }

  # time_rotating.rotate will be created
  + resource "time_rotating" "rotate" {
      + day              = (known after apply)
      + hour             = (known after apply)
      + id               = (known after apply)
      + minute           = (known after apply)
      + month            = (known after apply)
      + rfc3339          = (known after apply)
      + rotation_minutes = 1
      + rotation_rfc3339 = (known after apply)
      + second           = (known after apply)
      + unix             = (known after apply)
      + year             = (known after apply)
    }

Plan: 3 to add, 0 to change, 2 to destroy.
local_file.test: Destroying... [id=0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33]
local_file.test: Destruction complete after 0s
null_resource.rotate: Destroying... [id=7716790656126891347]
null_resource.rotate: Destruction complete after 0s
time_rotating.rotate: Creating...
time_rotating.rotate: Creation complete after 0s [id=2022-08-15T13:14:25Z]
null_resource.rotate: Creating...
null_resource.rotate: Creation complete after 0s [id=2309863648806061936]
local_file.test: Creating...
local_file.test: Creation complete after 0s [id=0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33]

Apply complete! Resources: 3 added, 0 changed, 2 destroyed.
```

**Comment by jbardin** [comment]
Hi @andyroyle,

Thanks for reporting this. The problem you see here is with the `time` provider, which seems to just be reporting the resource as missing rather than planning its replacement. This means that the plan is only going to create a new `time_rotating` instance, which doesn't qualify as a change for `replace_triggered_by`. The unexpected removal of the `time_rotating` instance also will show up in the drift report as a change outside of Terraform, rather than just a planned replacement. 

Since this isn't a bug in Terraform I'm going to close the issue, but please do feel free to file this with the `time` provider.

Thanks!

**Comment by andyroyle** [comment]
Ah, I see the unexpected removal in the [debug output](https://gist.github.com/andyroyle/4c4933a38906fc2f795a3a20ca25cb5a#file-terraform-log-L635-L638) but the drift report doesn't show it as a change 🤔 

Is [this](https://github.com/hashicorp/terraform-provider-time/blob/main/internal/tftime/resource_time_rotating.go#L28) therefore wrong?

```golang
	return &schema.Resource{
		Description: "...",
		CreateContext: resourceTimeRotatingCreate,
		ReadContext:   resourceTimeRotatingRead,
		UpdateContext: resourceTimeRotatingUpdate,
		DeleteContext: schema.NoopContext,
```

Is terraform behaving correctly then when encountering the Noop in `time_rotating`?

I am happy to open an issue on the time provider but I would like to understand whether `DeleteContext: schema.NoopContext` is valid [here](https://github.com/hashicorp/terraform-provider-time/blob/main/internal/tftime/resource_time_rotating.go#L28)?

**Comment by jbardin** [comment]
The `DeleteContext` handles the deletion of the instance, and since there is nothing to delete with a "time" resource, it's just a noop. I would guess that the unexpected removal happens within the read function.

Running a plan with this resource shows the following:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # time_rotating.rotate has been deleted
  - resource "time_rotating" "rotate" {
      - day              = 15 -> null
      - hour             = 14 -> null
      - id               = "2022-08-15T14:37:48Z" -> null
      - minute           = 37 -> null
      - month            = 8 -> null
      - rfc3339          = "2022-08-15T14:37:48Z" -> null
      - rotation_minutes = 1 -> null
      - rotation_rfc3339 = "2022-08-15T14:38:48Z" -> null
      - second           = 48 -> null
      - unix             = 1660574268 -> null
      - year             = 2022 -> null
    }
```

**Comment by andyroyle** [comment]
Ah, I see it [in the read](https://github.com/hashicorp/terraform-provider-time/blob/main/internal/tftime/resource_time_rotating.go#L442-L446). I will open an issue with the time provider.

Thanks for your help!
