### ISSUE TITLE
Dynamic dependency tree creation and dependency cycle checking algorithm

### ISSUE THREAD

**Issue by bernardhalas** [hashicorp/terraform#31643]
### Current Terraform Version

```
1.2.7
```

### Use-cases
In order to be able to create and manage resources with dynamic dependencies among them, we'd need to improve the dependency checker and upgrade its static algorithm (that checks just the HCL code for dependencies) to a dynamic one (that would consider HCL code with the input context),

### Attempted Solutions
Here a use-case (simplification from Azure, where a Service Principal can own another Service Principal).
```hcl
locals {
  spns = {
    A = {
      owners = []
    }
    B = {
      owners = ["A"]
    }
  }
}

resource "azuread_application" "new" {
  for_each = local.spns
  owners = [for o in each.value.owners : azuread_application.new[o].object_id]
}
```
At the above code there's no cycle, however the dependency checker sees one. The resource `azuread_application.new["A"]` should be created before `azuread_application.new["B"]`

Simplified resource handling when debugging (for easy local reproducibility of the current limitations); to be used with the same variable content:
```
resource "local_file" "new" {
  for_each = local.spns

  content = jsonencode([for o in each.value.owners : local_file.new[o].filename])
 
  filename = "./${each.key}.txt"
}
```
yields to: `Error: Cycle: local_file.new["B"], local_file.new["A"]`

### References
- #31072

**Comment by jbardin** [comment]
Hi @bernardhalas,

Thanks for filing the issue. We are tracking this use case in #23735.

Thanks!
