### ISSUE TITLE
error while destroying cloudgoat scenario cloud_breach_s3 

### ISSUE THREAD

**Issue by ddkrj** [hashicorp/terraform#31658]
I have created a cloud_breach_s3 scenario using cloudgoat for aws, but it ended with an error. But the scenario was created in the cloudgoat folder. Then I tried to destroy the scenario and got the following error. please help me to clear this issue. However, I want to destroy this scenario.
The error while destroying is as shown below.

Error: error detaching EC2 Internet Gateway (igw-016d98393f866d8f1) from VPC (vpc-064d3448cfff45c40): DependencyViolation: Network vpc-064d3448cfff45c40 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
│       status code: 400, request id: 8c504915-956c-4f36-ac0b-74132f7c0c3b
│ 
│ 
╵
╷
│ Error: Error deleting security group: DependencyViolation: resource sg-0f7a6c79b8b9ba759 has a dependent object
│       status code: 400, request id: ee07b230-ece0-40bb-a3db-52c722b99733
│ 
│ 
╵
╷
│ Error: error deleting EC2 Subnet (subnet-01712c924510c59af): DependencyViolation: The subnet 'subnet-01712c924510c59af' has dependencies and cannot be deleted.
│       status code: 400, request id: 9a200507-94a8-428f-ab72-122792124a76
│ 
│ 
╵
╷
│ Error: Error deleting security group: DependencyViolation: resource sg-0acb884663c860a9e has a dependent object
│       status code: 400, request id: 5f429dae-13a7-4064-a92f-9bf569e7298e
│ 
│ 
╵

[cloudgoat] Error while running `terraform destroy`.
    exit code: 1
    stdout: None
    stderr: None

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
