### ISSUE TITLE
I need to extract Event Hub compatible endpoint@tombuildsstuff Here's an example of connection strings of 'sample_iothub':

### ISSUE THREAD

**Issue by ManojR65302** [hashicorp/terraform#31650]
@tombuildsstuff Here's an example of connection strings of 'sample_iothub':

- **IoT Hub connection string**: HostName=sample_iothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxx
- **sample_iothub's built-in event hub endpoint connection string**: 
Endpoint=sb://**random_created_namespace**.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxx;EntityPath=sample_iothub

Therefore, I don't think they are interwined.

_Originally posted by @gary918 in https://github.com/hashicorp/terraform-provider-azurerm/issues/14670#issuecomment-998571022_

**Comment by ManojR65302** [comment]
is the issue resolved? if so what is the solution to get the "Event Hub compatible endpoint" string?

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
