### ISSUE TITLE
Error when importing azurerm_servicebus_namespace_network_rule_set

### ISSUE THREAD

**Issue by marclidegaardmadsen** [hashicorp/terraform#31661]
Hi,

I have encountered an issue with importing Servicebus Namespace Network Rulesets.

Running the command as suggested by the [documentation for azurerm version 3.17.0](https://registry.terraform.io/providers/hashicorp/azurerm/3.17.0/docs/resources/servicebus_namespace_network_rule_set) on : 
`terraform import azurerm_servicebus_namespace_network_rule_set.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Servicebus/namespaces/sbns1/networkrulesets/default`

However, this prompts me to change Microsoft.Servicebus to Microsoft.ServiceBus. 
![image](https://user-images.githubusercontent.com/79572838/185407092-bbf317e3-af81-4b7a-bd56-4a183cc9604d.png)

After making this change and re-running the command I get 
![image](https://user-images.githubusercontent.com/79572838/185407247-4d497a03-b3ab-4a9c-b052-c6d4fab6e42c.png)

Terraform version is 3.7.0.

### Expected Behavior
Expecting the network rule sets to be imported into my tf state file.

### Actual Behavior
The import of the network rule set fails.

### Steps to Reproduce
Run the command to import networkruleset.
`terraform import azurerm_servicebus_namespace_network_rule_set.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Servicebus/namespaces/sbns1/networkrulesets/default`

### Additional Context
Passing in a variable file to a module similar to 
terraform import -var-file="./environments/env.tfvars" module.servicebus_namespace_network_settings.azurerm_servicebus_namespace_network_rule_set.network_ruleset /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Servicebus/namespaces/sbns1/networkrulesets/default

### References
None

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
