### ISSUE TITLE
Upgrading AWS Provider from 4.24.0 to 4.26.0 breaks Auto Scaling Group creation. Scaling activity fails: "Your requested instance type is not supported in your requested Availability Zone"

### ISSUE THREAD

**Issue by SladeRun14** [hashicorp/terraform#31665]
### Terraform Version
```
Terraform v1.2.7
on windows_amd64
AWS Provider v4.26.0
```

### Terraform Configuration Files
```terraform
See (and diff) plan JSON files (good-v.4.24.0 and bad-4.26.0), attached.
```

### Debug Output
module.hashicorp-cluster.module.servers.aws_route53_record.server_cluster_lb_record: Creation complete after 41s [id=Z14Y1VSI6DSFDD_athleticatech.com_A]

Error: waiting for Auto Scaling Group (terraform-20220818151902124000000001) capacity satisfied: 1 error occurred:       
        * Scaling activity (a2760ac6-2579-bb25-f1fe-a662d3de567a): Failed: Your requested instance type (t3.small) is not supported in your requested Availability Zone (us-east-1e). Please retry your request by not specifying an Availability 
Zone or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1f. Launching EC2 instance failed.

  with module.hashicorp-cluster.module.clients.aws_autoscaling_group.client_autoscaling_group,
  on modules\clients\autoscaling_group.tf line 37, in resource "aws_autoscaling_group" "client_autoscaling_group":       
  37: resource "aws_autoscaling_group" "client_autoscaling_group" {

real    3m59.486s
user    0m0.092s
sys     0m0.200s
### Expected Behavior
After an upgrade from v.4.24.0 to v.4.26.0 Auto Scaling Group creation should succeed as does in v4.24.0 prior to upgrade and without the need to add the `exclude_names = ["us-east-1e"]` parameter to the:  `data "aws_availability_zones"{...` block.

### Actual Behavior
Version 4.26.0 Auto Scaling Group creation fails

### Steps to Reproduce
Starting with AWS Provider v4.24.0:
terraform init -upgrade
terraform apply

### Additional Context
Work-around: Adding the `exclude_names = ["us-east-1e"]` parameter to the: `data "aws_availability_zones" ...` block results in a successful deployment.

### References
[good-bad-plans.zip](https://github.com/hashicorp/terraform/files/9376146/good-bad-plans.zip)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by SladeRun14** [comment]
Thanks for the AWS provider referral. Apologies for the interruption.
