### ISSUE TITLE
terraform creates sockets named /tmp/tf-plugin12345678 and never deletes them

### ISSUE THREAD

**Issue by joekhoobyar** [hashicorp/terraform#3166]

**Comment by josephholsten** [comment]
On mac you'll find these files in `$TMPDIR`, which usually lives somewhere in `/var/folders`.

I can confirm I have tons of these files.

**Comment by catsby** [comment]
Those are temporary files created when loading the plugins: 

- https://github.com/hashicorp/terraform/blob/master/plugin/server.go#L122

We're just using Go's built in `TempFile` util:
> TempFile uses the default directory for temporary files (see os.TempDir)

- https://golang.org/pkg/io/ioutil/#TempFile

Those files are [per-user temporary files and caches][1]; I've found a fairly detailed writeup about them here:

- http://www.magnusviri.com/OS_X_Admin/what-is-var-folders.html

This is the result of Terraform using temporary file space for scratch. I have 1,200 some files in there... but all have been modified in the last 3 days (the author above mentions docs that indicate files are cleared out after 3 days if not used). 

Do you have any of these files that have not been modified in the past 3 days? 



[1]: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man7/hier.7.html

**Comment by josephholsten** [comment]
So long as those files don't contain credentials or sensitive information, I'm comfortable trusting the operating system's cleanup.

**Comment by thomascellerier** [comment]
It will only be cleaned up on reboot, just so you know...

**Comment by wleese** [comment]
Surely this isn't acceptable? I now have 64840 directories after a few weeks - I cringe to think of how bad this will be after a few years of uptime.

> I'm comfortable trusting the operating system's cleanup.

Which will hopefully never happen .. at least if you value high uptime.

**Comment by josephholsten** [comment]
@wleese: are you seeing files older than 3 days? Cleanup occurs more frequently than mere restarts on systems.

Have you confirmed that the fs does runs out of inodes in practice? On what platform is this occurring?

**Comment by wleese** [comment]
RHEL6, indeed just 3 days old. Regardless of if we run out in the end, the fact that a tool puts so much pressure on a resource that we need to worry about it indicates there's something to be fixed. This would be more forgivable is terraform had some kind of incredibly storage heavy state to manage, but yeah..

**Comment by josephholsten** [comment]
I'm sorry this is breaking things for you. Do you need any assistance writing a patch to fix this?

**Comment by wleese** [comment]
I'd expect this to be sufficient:

```
diff --git a/plugin/server.go b/plugin/server.go
index 3daa8a3..a1427b9 100644
--- a/plugin/server.go
+++ b/plugin/server.go
@@ -86,6 +86,7 @@ func Serve(opts *ServeOpts) {
 
        // Serve
        server.Accept(listener)
+       defer os.Remove(listener.Addr().String())
 }
```

Sadly it seems that anything deferred is not run - likely due to the way plugins are handled.

**Comment by wleese** [comment]
Will this ticket be re-opened by the way?

**Comment by bflad** [comment]
We're seeing this in our CI environment. Hundreds of `/tmp/tf-plugin*` files over 30 days old. I'd +1 reopening this as a bug.

**Comment by jleclanche** [comment]
Same. This is a problem, and I suspect it might cause some issues with the kernel limits if there's a lot of terraform instances being run very fast. You can't rely on reboots here.
