### ISSUE TITLE
aws_instance import does not include network_interface in state

### ISSUE THREAD

**Issue by engineertdog** [hashicorp/terraform#31678]
### Terraform Version

```shell
Terraform v1.2.7
on linux_amd64
```

### Terraform Configuration Files

```terraform
module "NIC" {
  source          = "./VM_NetworkInterface"
  subnet          = var.subnet
  security_groups = var.security_group_ids
}

resource "aws_instance" "this" {
  network_interface {
      network_interface_id = module.NIC.id
      device_index         = 0
  }
}
```

VM_NetworkInterface
```terraform
resource "aws_network_interface" "this" {
  subnet_id       = var.subnet.id
  private_ips     = var.ip_config.Nic1.PrivateIP
}
```

### Debug Output

I'll have to circle back to this as it's quite lengthy and I will need to find a better way to extract it and parse the contents (since it's a client's environment).

### Expected Behavior

When importing an AWS instance, it should automatically grab the network attachment and store that in the state.
`terraform import <path> <aws_ec2_instance_id>`
`terraform import <path> <network_interface_id>` - This correlates to the VM_NetworkInterface module.

### Actual Behavior

When importing an existing AWS instance with a network interface attached, it should be imported into the state. However, when importing an AWS instance, the state does not update the value of `network_interface` on the `aws_instance` resource.

The value of `network_interface` is `[]`. However, when compared to the AWS CLI command `describe-instances`, the network interface information is available for the instance. Example:
```json
NetworkInterfaces": [
  {
    "Attachment": {
        "AttachTime": "2022-08-18T19:50:36+00:00",
        "AttachmentId": "eni-attach-id",
        "DeleteOnTermination": true,
        "DeviceIndex": 0,
        "Status": "attached",
        "NetworkCardIndex": 0
    },
    "Description": "",
    "Groups": [
        {
            "GroupName": "sg-name",
            "GroupId": "sg-id"
        }
    ],
    "Ipv6Addresses": [],
    "MacAddress": "1234",
    "NetworkInterfaceId": "eni-id",
    "OwnerId": "id",
    "PrivateDnsName": "ip-10-0.0.1.ec2.internal",
    "PrivateIpAddress": "10.0.0.1",
    "PrivateIpAddresses": [
        {
            "Primary": true,
            "PrivateDnsName": "ip-10-0.0.1.ec2.internal",
            "PrivateIpAddress": "10.0.0.1"
        }
    ],
    "SourceDestCheck": true,
    "Status": "in-use",
  }
]
```

### Steps to Reproduce

1. terraform init
2. Create an AWS EC2 instance via GUI
3. Import EC2 instance and network interface into terraform
4. terraform plan

**Comment by apparentlymart** [comment]
Hi @engineertdog,

The behavior when importing an existing object into Terraform is decided by the provider plugin rather than by Terraform Core, and so the decision for whether to associate a network interface with an EC2 instance when importing the latter lives in the `hashicorp/aws` provider, rather than in Terraform Core.

For that reason, I suggest sending this feedback to [the AWS provider repository](https://github.com/hashicorp/terraform-provider-aws) instead. We use issues in this repository to represent bugs and feature requests for Terraform CLI and Terraform Core rather than providers, and so I'm going to close this issue. Thanks!
