### ISSUE TITLE
Public repositories failed for Amazon Linux

### ISSUE THREAD

**Issue by danielhstahl** [hashicorp/terraform#31683]
### Terraform Version

```shell
N/A, can't install
```

### Terraform Configuration Files

N/A, can't install

### Debug Output

2022-08-24T10:47:48.338Z [INFO]: # Executing command: yum install -y terraform
2022-08-24T10:47:48.436Z [INFO]: Loaded plugins: ovl, priorities
2022-08-24T10:47:48.562Z [WARNING]: https://rpm.releases.hashicorp.com/AmazonLinux/latest/x86_64/stable/repodata/c9af8a3098909c94bfa713605005bdec92ba7a29-primary.xml.gz: [Errno 14] HTTPS Error 404 - Not Found
2022-08-24T10:47:48.563Z [WARNING]: Trying other mirror.
2022-08-24T10:47:48.601Z [WARNING]: https://rpm.releases.hashicorp.com/AmazonLinux/latest/x86_64/stable/repodata/c9af8a3098909c94bfa713605005bdec92ba7a29-primary.xml.gz: [Errno 14] HTTPS Error 404 - Not Found
2022-08-24T10:47:48.601Z [WARNING]: Trying other mirror.
2022-08-24T10:47:48.602Z [WARNING]: One of the configured repositories failed (Hashicorp Stable - x86_64),
                                    and yum doesn't have enough cached data to continue. At this point the only
                                    safe thing yum can do is fail. There are a few ways to work "fix" this:
                                    1. Contact the upstream for the repository and get them to fix the problem.
                                    2. Reconfigure the baseurl/etc. for the repository, to point to a working
                                    upstream. This is most often useful if you are using a newer
                                    distribution release than is supported by the repository (and the
                                    packages for the previous distribution release still work).
                                    3. Run the command with the repository temporarily disabled
                                    yum --disablerepo=hashicorp ...
                                    4. Disable the repository permanently, so yum won't use it by default. Yum
                                    will then just ignore the repository until you permanently enable it
                                    again or use --enablerepo for temporary usage:
                                    yum-config-manager --disable hashicorp
                                    or
                                    subscription-manager repos --disable=hashicorp
                                    5. Configure the failing repository to be skipped, if it is unavailable.
                                    Note that yum will try to contact the repo. when it runs most commands,
                                    so will have to try and fail each time (and thus. yum will be be much
                                    slower). If it is a very temporary problem though, this is often a nice
                                    compromise:
                                    yum-config-manager --save --setopt=hashicorp.skip_if_unavailable=true
                                    failure: repodata/c9af8a3098909c94bfa713605005bdec92ba7a29-primary.xml.gz from hashicorp: [Errno 256] No more mirrors to try.
                                    https://rpm.releases.hashicorp.com/AmazonLinux/latest/x86_64/stable/repodata/c9af8a3098909c94bfa713605005bdec92ba7a29-primary.xml.gz: [Errno 14] HTTPS Error 404 - Not Found

### Expected Behavior

Terraform should have installed

### Actual Behavior

Terraform did not install, see above error.

### Steps to Reproduce

On Amazon Linux:

1. yum install -y yum-utils
2. yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
3. yum install -y terraform

### References

https://github.com/hashicorp/terraform/issues/30726

**Comment by marnixgb** [comment]
This is a wider issue - none of the repos hosted at https://rpm.releases.hashicorp.com are actually available

Why on earth does hashicorp not mirror ? My first criticism of an otherwise excellent company

**Comment by marnixgb** [comment]
This was resolved at about 14:00 BST (06:00 PT)

**Comment by apparentlymart** [comment]
Hi @danielhstahl! Thanks for reporting this.

As @marnixgb noted, there was an outage for the RPM repository earlier today, and you can find some more details on when it happened and what the relevant teams did in response to it in [the incident report](https://status.hashicorp.com/incidents/1fysx522mvzg).

Since this was a problem with the RPM repository service rather than a bug in Terraform itself, and since it's now resolved, I'm going to close this issue. Thanks again for reporting it!
