### ISSUE TITLE
Support mTLS for http backend

### ISSUE THREAD

**Issue by scr-oath** [hashicorp/terraform#31700]
### Terraform Version

```shell
Terraform v1.2.8
on darwin_arm64
```

### Use Cases

- For an enterprise that uses an internal certificate authority to issue certs for TLS servers, allow passing cacert for http backend
- For http backends that demand client certs (mTLS - mutual TLS), allow configuration to declare the cert and key to use.

### Attempted Solutions

There are other backends, which may be challenging to set up for one-off or small deployments or when there is no AWS presence - such as S3 + Dynamo

### Proposal

Enable mTLS and cacert trust for mTLS with an internal signing mechanism.

### References

- #31699

**Comment by kmoe** [comment]
Thanks for this. This is a reasonable request and we'll review the PR when we can.

**Comment by kmoe** [comment]
Implemented in #31699
