### ISSUE TITLE
Incorrect PR link in beta release notes

### ISSUE THREAD

**Issue by dancorne** [hashicorp/terraform#31716]
### Terraform Version

```shell
1.3.0-beta1
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

Link to this PR should be in release notes: #31687

### Actual Behavior

The following PR is actually linked: #31154

### Steps to Reproduce

See https://github.com/hashicorp/terraform/releases/tag/v1.3.0-beta1, second point under Enhancements

### Additional Context

Hello, not sure if Github Issues is the best place to let you know, sorry if there's a better avenue for this...

Very minor thing, but looks like there's an incorrect link in the [new beta Terraform 1.3.0-beta1 release notes](https://github.com/hashicorp/terraform/releases/tag/v1.3.0-beta1). Maybe a copy/paste error? Currently under Enhancements:
```
config: Optional attributes for object type constraints, as described under new features above. (#31154)
config: New built-in function timecmp allows determining the ordering relationship between two timestamps while taking potentially-different UTC offsets into account. (#31154)
```

I think that second PR link should probably be #31687

**Comment by crw** [comment]
Thanks for the report! I let the team know.

**Comment by kmoe** [comment]
Thank you for letting us know. I'm impressed you noticed this so quickly. I've updated both the GitHub Release notes and the changelog on the appropriate release branch, so the changelog for (subsequent prereleases and) the final v1.3.0 release will be correct.
