### ISSUE TITLE
Recover partial state when instance times out in cloudstack provider

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform#3171]
The aws provider stores the resource ID quite early on in the process:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_instance.go#L377

Whereas the cloudstack provider waits until go-cloudstack has returned before storing anything
https://github.com/hashicorp/terraform/blob/master/builtin/providers/cloudstack/resource_cloudstack_instance.go#L194

The actual cloudstack API for this is async, but this is hidden from us by the go-cloudstack driver
https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/VirtualMachineService.go#L411

It would be quite handy if the provider was able to store some VM information even when initial deploy step "fails" - such as when VM creation exceeds the timeout.

I can think of two options for this:
1. update the go-cloudstack lib so that it can expose the async job part of the deploy, and then use that api in the provider
2. in the event of a deploy failure, try calling `GetVirtualMachineByName` and denoting how far it got in the state file

If I understand terraform correctly (I'm pretty new to it), then this would also allow the provider to kick-off provisioning steps after recovering from the failure?

**Comment by svanharmelen** [comment]
@glenjamin what kind of failures are you talking about here? Do you have an example to help me understand what you are trying to fix or achieve?

> Whereas the cloudstack provider waits until go-cloudstack has returned before storing anything

That's just how CloudStack works. You cannot get the ID of a VM until the async job is finished and the VM is actually created, so there is nothing to store until that job is done and the success result is returned containing the VM ID (along with it's other details).

The only corner case I can think of it indeed a timeout waiting for the async job to finish, when that job could still end successfully. In that case you can fail to write the VM ID to the state. But I think the only solution for those cases is to tweak the timeout settings, as (again) CloudStack does not return anything about the VM being created until the async job is done. So partial state doesn't help here I'm afraid. Tweaking the timeout can be done in the provider config: http://www.terraform.io/docs/providers/cloudstack/index.html#timeout

**Comment by glenjamin** [comment]
I've got a clearer picture of how cloudstack's APIs work now, and you are of course correct.

Our cloud provider can take between 2 and 30 minutes to provision VMs, we'll crank the timeout up even higher - but it's pretty annoying.

I think the feature that actually solves my problem would be https://github.com/hashicorp/terraform/issues/2976
