### ISSUE TITLE
azurerm_data_factory_linked_service_azure_sql_database with private endpoint is not able to connect to the database

### ISSUE THREAD

**Issue by edi239** [hashicorp/terraform#31722]
### Terraform Version

```shell
Terraform v1.2.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.1
+ provider registry.terraform.io/hashicorp/azurerm v3.20.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Terraform Configuration Files

terraform {
  
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.20.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "=1.5.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "=3.1.0"
    }
  }
}

provider "azurerm" {
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "test_df"
  location = var.location
}

resource "azurerm_virtual_network" "base_vnet" {
  name          = "base-vnet"
  address_space = ["192.168.1.0/24"]
  
  resource_group_name = azurerm_resource_group.rg.name
  location            = var.location
}

resource "azurerm_subnet" "base_subnet" {
  name                 = "base-sn"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.base_vnet.name
  address_prefixes       = ["192.168.1.0/25"]
  private_endpoint_network_policies_enabled = true
}

resource "azurerm_mssql_server" "sql_server" {
  name = "df-test-sql-239134"
  resource_group_name = azurerm_resource_group.rg.name
  location = var.location
  version = "12.0"
  administrator_login = "sad"
  administrator_login_password = "Test12345"
  public_network_access_enabled = "false"
}

resource "azurerm_private_endpoint" "sql_srv_endpoint" {
  name                = "pe-sql"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  subnet_id           = azurerm_subnet.base_subnet.id

  private_service_connection {
    name                           = "psc-sql"
    private_connection_resource_id = azurerm_mssql_server.sql_server.id
    subresource_names              = [ "sqlServer" ]
    is_manual_connection           = false
  }

  lifecycle { ignore_changes = [ private_dns_zone_group ] }

}

resource "azurerm_mssql_database" "sql_database" {
  name = "sql_db"
  server_id = azurerm_mssql_server.sql_server.id
  sku_name = "Basic"
  
  //geo_backup_enabled = var.mssqldatabase_geo_backup_enabled
  //create_mode = var.mssqldatabase_create_mode
}

resource "azurerm_data_factory" "DataFactory01" {
  name                = "test-df-239134"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  managed_virtual_network_enabled = true
  public_network_enabled = false

  //identity {type = "SystemAssigned" }
}

resource "azurerm_data_factory_integration_runtime_azure" "IntegrationRuntime02" {
  name                = "integrationruntime02"
  data_factory_id   = azurerm_data_factory.DataFactory01.id
  //resource_group_name = azurerm_resource_group.ek_rg.name
  location            = var.location
  time_to_live_min        = 60
  virtual_network_enabled = true
}

resource "azurerm_data_factory_linked_service_azure_sql_database" "df_to_sqllock" {
  name                = "sqldb_db"
  //resource_group_name = azurerm_resource_group.ek_rg.name
  data_factory_id   = azurerm_data_factory.DataFactory01.id
  integration_runtime_name = azurerm_data_factory_integration_runtime_azure.IntegrationRuntime02.name
  connection_string = "data source=${azurerm_mssql_server.sql_server.name}.database.windows.net;Initial Catalog=${azurerm_mssql_database.sql_database.name};Persist Security Info=False;User ID=sad;Password=Test12345;Encrypt=True;Connection Timeout=30;"
  
}

resource "azurerm_data_factory_managed_private_endpoint" "df_to_sql" {
  name               = "pe_to_sql"
  data_factory_id    = azurerm_data_factory.DataFactory01.id
  target_resource_id = azurerm_mssql_server.sql_server.id
  subresource_name   = "sqlServer"

  lifecycle { ignore_changes = [ fqdns ] }

### Debug Output

Error code
9070
Details
Failed to decrypt sub-resource 'None' payload on cloud with error: Failed to decrypt sub-resource payload {
"name": "sqldb_db",
"properties": {
"connectVia": {
"name": "integrationruntime02",
"properties": {
"type": "Managed",
"typeProperties": {
"computeProperties": {
"location": "West Europe",
"dataFlowProperties": {
"computeType": "General",
"coreCount": 8,
"timeToLive": 60,
"cleanup": true
},
"pipelineExternalComputeScaleProperties": {
"timeToLive": 60
}
}
},
"managedVirtualNetwork": {
"referenceName": "default",
"type": "ManagedVirtualNetworkReference",
"id": "fba9f0fd-2a85-4da7-958b-350346efc35f"
}
}
},
"type": "AzureSqlDatabase",
"annotations": [],
"typeProperties": {
"connectionString": "********************",
"servicePrincipalId": "********************",
"tenant": "********************",
"encryptedCredential": "********************"
}
}
} and error is: Message for the errorCode 'UserErrorInvalidDbConnectionString' not found.., status code: BadRequest.
Activity ID: 40622a2d-6a75-40be-9651-8f8f805dd064

### Expected Behavior

After deployment the linked service should be able to connect to the sqlserver like this:

![image](https://user-images.githubusercontent.com/112088262/187863991-a3cace75-024c-42f6-b5db-b2bc12542b30.png)

### Actual Behavior

Test Connection to sql server will produce the above error. Private Endpoint is not found by linked service

![failed Linked Service](https://user-images.githubusercontent.com/112088262/187864851-e6412558-ed35-4068-9405-3630d1ddcbf2.png)

### Steps to Reproduce

1. terraform plan
2. terraform apply

Approve Private Endpoint in SQL Server - Networking - Private Endpoints

Wait some time to let integration service get healthy

Go to datafactory
Open Azure DataFactory Studio
Go To linked services 
Open linked service
Look whether interactive authoring is enabled - otherwise enable it

Test Connection

**Comment by kmoe** [comment]
This looks like an issue with the Azurerm provider rather than Terraform Core. Please open an issue in that provider's repository instead: https://github.com/hashicorp/terraform-provider-azurerm

Code examples can be made more readable in GitHub Markdown by surrounding them with backticks (```) .

**Comment by crw** [comment]
You may also find more help in the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. Thanks!
