### ISSUE TITLE
Output multiple IP of instances

### ISSUE THREAD

**Issue by payals** [hashicorp/terraform#3174]
I am creating two ec2 instances. 

When trying to output both IPs, I am getting errors - 

```hcl
output "ip" {
    value = "${join(",", join(aws_instance.web.*.public_ip)}"
}
```

> Error reading config for output ip: parse error: syntax error

```hcl
     value = "${aws_instance.web.*.public_ip}"
```
> * output 'ip': multi-variable must be in a slice

```hcl
     value = ["${aws_instance.web.*.public_ip}"]
```

Getting only one IP

**Comment by semarj** [comment]
From reading: https://www.terraform.io/docs/configuration/interpolation.html#join_delim_list_
it would seem like you want: `value = "${join(",", aws_instance.web.*.public_ip)}"`

**Comment by daveadams** [comment]
Yes, you have an extra `join(` in the code you included in your writeup. semarj's code is correct.

**Comment by stack72** [comment]
@payals have you looked at trying this? Is this still an issue or can it be closed?

**Comment by thachmai** [comment]
I used the same code as @semarj with digital ocean provider and the output works as expected.

**Comment by radeksimko** [comment]
Hi @payals 
As @semarj mentioned above, this is currently the right way of joining multiple attributes:

```hcl
output "ip" {
    value = "${join(",", aws_instance.web.*.public_ip)}"
}
```

Feel free to reopen, if you still have problems with this.
