### ISSUE TITLE
Changing the aws_network_interface on an aws_eip fails on first apply

### ISSUE THREAD

**Issue by pkqk** [hashicorp/terraform#31744]
### Terraform Version

```shell
Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.75.1
```

### Terraform Configuration Files

```terraform
resource "aws_eip" "ipname" {
  vpc                       = true
  associate_with_private_ip = "10.40.52.82"
  network_interface         = aws_network_interface.ifacename.id # this is changed from one interface to another on a different instance
}
```

### Debug Output

I can share the output privately, it might be easier to create a smaller example than filter through the output of this run.

### Expected Behavior

I would expect the first `plan` and `apply` to move the eip association.

On the first run of apply it fails with the error about multiple interfaces attached to the instance. If I then plan and apply a second time it is happy, as it has disconnected the interface from the original instance.

### Actual Behavior

$ terraform apply -refresh=false -input=false plan
module.modname.aws_eip.ipname: Modifying... [id=eipalloc-abcabcabc]
╷
│ Error: Failure associating EIP: InvalidInstanceID: There are multiple interfaces attached to instance 'i-abcabcabc'. Please specify an interface ID for the operation instead.
│ 	status code: 400, request id: 52c82f68-8f2c-48ba-b5c1-6f7c4957d33x
│ 
│   with module.modname.aws_eip.ipname,
│   on eu-central-1/eip.tf line 290, in resource "aws_eip" "ipname":
│  290: resource "aws_eip" "ipname" {

### Steps to Reproduce

terraform plan
terraform apply

### Additional Context

I am moving EIPs from one instance with multiple ENIs to another instance with multiple ENIs.

The terraform is in a module

It looks like the attachment is ignoring which interface id to use after it finds the instance id on the first apply.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
