### ISSUE TITLE
Add support for IMDSv2 in AWS Batch

### ISSUE THREAD

**Issue by Gouthami-23** [hashicorp/terraform#31740]
### Terraform Version

```shell
1.2.8
```

### Use Cases

IMDSv2 should be enabled for AWS Batch

### Attempted Solutions

resource "aws_instance" "example" {
  ...
  instance_type     = "t2.micro"
+   metadata_options {
        ...
+       http_endpoint = "enabled"
+       http_tokens   = "required"
+  }
  ...
}

The above code is used to ensure IMDSv2 is enabled in EC2. 
But metadata_options is not supported by terraform for AWS Batch.

### Proposal

 metadata_options {
        ...
+       http_endpoint = "enabled"
+       http_tokens   = "required"
+  }

The above parameters need to be made available in this terraform resource  - aws_batch_compute_environment.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
