### ISSUE TITLE
aws_iam_role_policy_attachement error 404 NoSuchEntity requiring inconsistent service-role to be added to policy path

### ISSUE THREAD

**Issue by kbroughton** [hashicorp/terraform#31748]
### Terraform Version

```shell
terraform version
Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.22.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

The 

Error: Error attaching policy arn:aws:iam::aws:policy/AWSLambdaRole to IAM Role bolt_python_s3_storage: NoSuchEntity: Policy arn:aws:iam::aws:policy/AWSLambdaRole does not exist or is not attachable. status code: 404, request id: 936fa20e-30ed-4f08-b7ae-0ccef820540c

Error: Error attaching policy arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole

### Expected Behavior

bolt_python_policy2 applied fine. I expect the other two to apply as well.

```
resource "aws_iam_role_policy_attachment" "bolt_python_policy2" {
  role       = aws_iam_role.bolt_python_s3_storage.name
  policy_arn = "arn:aws:iam::aws:policy/AWSLambdaExecute"
}

resource "aws_iam_role_policy_attachment" "bolt_python_policy3" {
  role       = aws_iam_role.bolt_python_s3_storage.name
  policy_arn = "arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole"
}

resource "aws_iam_role_policy_attachment" "bolt_python_policy4" {
  role       = aws_iam_role.bolt_python_s3_storage.name
  policy_arn = "arn:aws:iam::aws:policy/AWSLambdaRole"
}
```

### Actual Behavior

The first policy bolt_python_policy3 with arn "arn:aws:iam::aws:policy/AWSLambdaExecute" applied fine, but the other two required adding `service-role` to the path like "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
