### ISSUE TITLE
"ParentResourceNotFound" Message="Can  not perform requested operation on nested resource. Parent resource 'hr-dev-ms-sql-server' not found.

### ISSUE THREAD

**Issue by VivekKoppula** [hashicorp/terraform#31755]
### Terraform Version

```shell
Terraform v1.2.6
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
resource "azurerm_mssql_server" "mssql_server" {
  name                         = "${local.resource_name_prefix}-${var.mssql_server_name}"
  resource_group_name          = azurerm_resource_group.rg.name
  location                     = azurerm_resource_group.rg.location
  version                      = "12.0"
  administrator_login          = "adm1n157r470r"
  administrator_login_password = "4-v3ry-53cr37-p455w0rd"
}

resource "azurerm_mssql_database" "mssql_database" {
  name           = "${local.resource_name_prefix}-${var.mssql_database_name}"
  server_id      = azurerm_mssql_server.mssql_server.id
  collation      = "SQL_Latin1_General_CP1_CI_AS"
  license_type   = "LicenseIncluded"
  max_size_gb    = 1
  read_scale     = false
  sku_name       = "S0"
  zone_redundant = false
  depends_on     = [azurerm_mssql_server.mssql_server]
  tags           = local.common_tags
}
```
The full config files are [here](https://github.com/AvtsVivek/Az204WthTerraform/tree/main/src/tf-files/650500-sql-db-with-tf). 

### Debug Output

azurerm_mssql_database.mssql_database: Creating...
╷
│ Error: creating/updating Database: (Name "hr-dev-ms-sql-db" / Server Name "hr-dev-ms-sql-server" / Resource Group "hr-dev-rg-vivrag-dtdwxd"): sql.DatabasesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can 
not perform requested operation on nested resource. Parent resource 'hr-dev-ms-sql-server' not found."
│
│   with azurerm_mssql_database.mssql_database,
│   on tf6-02-sql-server-db.tf line 20, in resource "azurerm_mssql_database" "mssql_database":
│   20: resource "azurerm_mssql_database" "mssql_database" {
│
╵

The [full gist is here](https://gist.github.com/AvtsVivek/c4dc551079649ce4477d19dd968d3336).

### Expected Behavior

The sql database on the ms sql server should get created without errors.

### Actual Behavior

azurerm_mssql_database.mssql_database: Creating...
╷
│ Error: creating/updating Database: (Name "hr-dev-ms-sql-db" / Server Name "hr-dev-ms-sql-server" / Resource Group "hr-dev-rg-vivrag-dtdwxd"): sql.DatabasesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can 
not perform requested operation on nested resource. Parent resource 'hr-dev-ms-sql-server' not found."
│
│   with azurerm_mssql_database.mssql_database,
│   on tf6-02-sql-server-db.tf line 20, in resource "azurerm_mssql_database" "mssql_database":
│   20: resource "azurerm_mssql_database" "mssql_database" {
│
╵

### Steps to Reproduce

```
terraform fmt

terraform init

terraform validate

terraform plan -out main.tfplan

terraform apply main.tfplan 
```

The command list is below.

    https://github.com/AvtsVivek/Az204WthTerraform/blob/main/src/tf-files/650500-sql-db-with-tf/commands.sh

### Additional Context

```
# Terraform Block
terraform {
  required_version = "~> 1.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }

    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

# Provider Block
provider "azurerm" {
  features {}
}

```

Full file [is here](https://github.com/AvtsVivek/Az204WthTerraform/blob/main/src/tf-files/650500-sql-db-with-tf/tf1-provider.tf).

### References

Similar issue [is explained here on the ms docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/error-parent-resource?tabs=bicep), but this about bicep and not terraform.

**Comment by AvtsVivek** [comment]
Now found a work arund and seems to be working.

Based on [the sleep terraform timer resource here](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep), I added a timer to the config.

```
resource "time_sleep" "wait_for_some_time" {
  depends_on      = [azurerm_mssql_server.mssql_server]
  create_duration = "30s"
}
```

The [full set of new configs are here](https://github.com/AvtsVivek/Az204WthTerraform/tree/main/src/tf-files/650510-sql-db-with-tf-and-timer)

**Comment by AvtsVivek** [comment]
Now I found similar errors with another example. 

The [terraform configuration files are here](https://github.com/AvtsVivek/Az204WthTerraform/tree/main/src/tf-files/500110-simple-web-app-to-azure-vm-iis).

 When I plan and apply, I get the following error.

```
azurerm_virtual_machine_extension.iis-windows-vm-extension: Creating...
╷
│ Error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'hr-dev-winvm' not found."
│
│   with azurerm_virtual_machine_extension.iis-windows-vm-extension,
│   on tf7-05-web-windows-vm-resource.tf line 30, in resource "azurerm_virtual_machine_extension" "iis-windows-vm-extension":
│   30: resource "azurerm_virtual_machine_extension" "iis-windows-vm-extension" {
│
╵
```

So here the resource [azurerm_virtual_machine_extension](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_extension) should be created after the resource [azurerm_windows_virtual_machine](azurerm_windows_virtual_machine) is created.

But unless I have sleep timer setup, its giving me the above error. I had to keep azurerm_virtual_machine_extension waiting for 6 minutes, and then only its successful. You can [see that resource in this file here](https://github.com/AvtsVivek/Az204WthTerraform/blob/main/src/tf-files/500110-simple-web-app-to-azure-vm-iis/tf7-05-web-windows-vm-resource.tf).

Is it that I am missing something?

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by AvtsVivek** [comment]
Ok, added this one here.

https://github.com/hashicorp/terraform-provider-azurerm/issues/18311
