### ISSUE TITLE
1.2.9 release not available in apt.releases.hashicorp.com

### ISSUE THREAD

**Issue by rgl** [hashicorp/terraform#31758]
### Terraform Version

```shell
n/a
```

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

I expected to have v1.2.9 release in apt.releases.hashicorp.com.

### Actual Behavior

```console
vagrant@vagrant:~$ apt-cache madison terraform
 terraform |      1.2.8 | https://apt.releases.hashicorp.com jammy/main amd64 Packages
 terraform |      1.2.7 | https://apt.releases.hashicorp.com jammy/main amd64 Packages
 terraform |      1.2.6 | https://apt.releases.hashicorp.com jammy/main amd64 Packages

```

### Steps to Reproduce

apt-get install terraform

**Comment by crw** [comment]
Thanks for this report. We are looking into it.

**Comment by crw** [comment]
This should now be fixed. Our Release Engineering team is also looking into the recurring issue. Thanks for the report!
