### ISSUE TITLE
Azure Private Endpoint with ip_configuration for a Key Vault fails

### ISSUE THREAD

**Issue by sl3dg3hamm3r** [hashicorp/terraform#31784]
### Terraform Version

```shell
TF version:  1.2.9
azurerm version: 3.22.0
```

### Terraform Configuration Files

```
resource "azurerm_private_endpoint" "this" {
  name                = "pe-private-endpoint-test"
  location            = "northeurope"
  resource_group_name = "rg-test"
  subnet_id           = "<subnet-ID>"

  private_service_connection {
    name                           = "pe-private-endpoint-test-privateserviceconnection"
    private_connection_resource_id = "<key-vault-resource-id>"
    is_manual_connection           = false
    subresource_names              = ["vault"]
  }

  ip_configuration {
    name                = "pe-private-endpoint-test-ip-configuration"
    private_ip_address  = "xxx.xxx.xxx.xxx"
    subresource_name    = "vault"
  }
}
```

### Debug Output

From ARM:

`Private Endpoint /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/<resource-group-name>/providers/Microsoft.Network/privateEndpoints/<key-vault-name> contains static ipconfigurations: [PrivateIPAddress: xxx.xxx.xxx.xxx, GroupId: vault, MemberName: vault] and its missing these membernames/groupids requested by Private Link service [GroupId: vault, MemberName: default]. Private Endpoint needs to be reconfigured with missing memberNames.`

### Expected Behavior

One should be able to define the member name of the IP configuration.

### Actual Behavior

`subresource_name` is used for `group_id` AND `member_name` (I suppose this is the problem)

### Steps to Reproduce

terraform init
terraform plan # will work
terraform apply # ARM returns error

### Additional Context

The problem does _not_ apply for private endpoints connected to e.g. Storage Accounts, App Configurations and Azure Data Factories, with `ip_configuration`.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
