### ISSUE TITLE
CLI command "terraform apply -h" does not list "-var-file" as possible option

### ISSUE THREAD

**Issue by g-ser** [hashicorp/terraform#31793]
### Terraform Version

```shell
Terraform v1.2.9
```

### Use Cases

The documentation states that it is possible to use "-var-file" option with the "terraform apply" command: https://www.terraform.io/language/values/variables#variable-definitions-tfvars-files

However, when issuing "terraform apply -h" the "-var-file" option is not listed.

### Attempted Solutions

N/A

**Comment by jbardin** [comment]
Hi @g-ser,

At the end of the `apply` help output there is:
```
  If you don't provide a saved plan file then this command will also accept
  all of the plan-customization options accepted by the terraform plan command.
  For more information on those options, run:
      terraform plan -help
```

There is currently no good way of combining optional flags based on other commands in terraform, so this is the best option we have at the moment to link the two sets of flags together, and completely in sync with one another. While this is not an uncommon pattern in many CLI applications, we recognize that this often slips past users, and are keeping an eye out for better alternatives.

Thanks
