### ISSUE TITLE
Add Resource Module for FrontDoor Endpoint Routes

### ISSUE THREAD

**Issue by jyanez-smg** [hashicorp/terraform#31799]
### Terraform Version

```shell
PS C:\github\itops_azure-us-east_networking_hierarchy_dev\terraform> terraform version
Terraform v1.2.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.21.1

Your version of Terraform is out of date! The latest version
is 1.2.9. You can update by downloading from https://www.terraform.io/downloads.html
PS C:\github\itops_azure-us-east_networking_hierarchy_dev\terraform>
```

### Use Cases

You must add a route to route traffic from a custom domain to the Frontdoor endpoint. Currently, there is no resource module to add a route on the newer Frontdoor deployments using standard or premium, not classic. 

### Attempted Solutions

I can find no workaround found good workaround outside of creating it manually.

![Screenshot 2022-09-15 150846](https://user-images.githubusercontent.com/110114644/190499801-766a734d-f493-4d65-894a-ef5adf65451e.png)

### Proposal

Add a resource module such as azurerm_cdn_frontdoor_endpoint_route or an option on the existing azurerm_cdn_frontdoor_endpoint module to include a custom domain route.

**Comment by apparentlymart** [comment]
Hi @jyanez-smg!

This seems to be a request for the Azure provider, which is a separate codebase from Terraform Core. Please record this feature request as a GitHub issue in [the Azure provider's own repository](https://github.com/hashicorp/terraform-provider-azurerm).

Thanks!

**Comment by jyanez-smg** [comment]
Oh, sorry about that. Thanks!
