### ISSUE TITLE
Support generic OIDC authentication for AzureRM backend

### ISSUE THREAD

**Issue by karlschriek** [hashicorp/terraform#31802]
### Terraform Version

```shell
1.2.9
```

### Use Cases

We want to set up workflows that run terraform using Azure Workload Identities. The workload identity approach works by treating an AKS cluster as an OIDC provider, and a specific ServiceAccount within a specific Namespace on that cluster as an identity, which can be federated to an Azure AD Service Principal. (https://azure.github.io/azure-workload-identity/docs/)

A similar (but specific to GitHub) solution was introduced in https://github.com/hashicorp/terraform/pull/30936. Similarly, this was introduced for GitHub on the AzureRM provider here: https://github.com/hashicorp/terraform-provider-azurerm/pull/16555 (the naming of both PRs is very generic, but the actual implementation is GitHub specific).

## Generic OIDC: AzureRM Provider

A _generic_ OIDC implementation (which works for Azure Workload Identities) was added in the AzureRM provider here: https://github.com/hashicorp/terraform-provider-azurerm/pull/18118. It uses `github.com/hashicorp/go-azure-helpers v0.40.0` and introduces an `oidc_token` variable

This implementation allows us to configure the provider using values populated by the AWI webhook.

```bash
export ARM_CLIENT_ID=$AZURE_CLIENT_ID
export ARM_SUBSCRIPTION_ID=xxx-xxx-xxx-xxx-xxx #this isn't populated by the AWI webhook
export ARM_TENANT_ID=$AZURE_TENANT_ID
export ARM_OIDC_TOKEN=$(cat $AZURE_FEDERATED_TOKEN_FILE)
```

In conjunction with:

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.20.0"
    }
  }
}
```
and
```terraform
provider "azurerm" {
  use_oidc = true
  features {}
}
```

## Generic OIDC: AzureRM Backend

A _generic_ OIDC implementation does not exist for the AzureRM Backend yet. I would like to be able to configure the backend as follows, and have it use the same authentication approach as what is in the AzureRM Provider, i.e:

```bash
export ARM_CLIENT_ID=$AZURE_CLIENT_ID
export ARM_SUBSCRIPTION_ID=xxx-xxx-xxx-xxx-xxx #this isn't populated by the AWI webhook
export ARM_TENANT_ID=$AZURE_TENANT_ID
export ARM_OIDC_TOKEN=$(cat $AZURE_FEDERATED_TOKEN_FILE)
```

```terraform
terraform {
  backend "azurerm" {
    use_oidc=true             
    resource_group_name=myrg
    storage_account_name=mysa
    container_name=myctr
  }
}
```

or, if setting everything explicitly:

```terraform
terraform {
  backend "azurerm" {
    use_oidc=true             
    resource_group_name=myrg
    storage_account_name=mysa
    container_name=myctr
    client_id=xxxxxxxxxxxxxxxxx
    subscription_id=xxxxxxxxxxxxxxxxx
    tenant_id=xxxxxxxxxxxxxxxxx
    oidc_token=xxxxxxxxxxxxxxxxx
  }
}
```

### Attempted Solutions

For this specific situation there is no real workaround other than to use a different authentication method altogether.

### Proposal

I would propose looking into the changes introduced in https://github.com/hashicorp/terraform-provider-azurerm/pull/18118 and following the same approach to add an `oidc_token` / `ARM_OIDC_TOKEN` parameter to the AzureRM Backend implementation.

**Comment by karlschriek** [comment]
I have started looking at how this could be implemented. It _looks_ like it should be quite straightforward, namely:

1. In go.mod, set `github.com/hashicorp/go-azure-helpers v0.40.0`
2. In internal/backend/remote-state/azure/arm_client.go, add the following

```golang
	builder := authentication.Builder{
               ...
		IDToken: config.OIDCToken,  
	}
```
`authentication.Builder` refers to a struct in github.com/hashicorp/go-azure-helpers, to which `IDToken` was added in `v0.40.0`

3. In internal/backend/remote-state/azure/arm_client.go, add the following


```golang
func New() backend.Backend {
	s := &schema.Backend{
		Schema: map[string]*schema.Schema{
                        ...

			"oidc_token": {
				Type:        schema.TypeString,
				Optional:    true,
				DefaultFunc: schema.MultiEnvDefaultFunc([]string{"ARM_OIDC_TOKEN"}, ""),
				Description: "The OIDC ID token for use when authenticating as a Service Principal using OpenID Connect.",
			...
		},
	}
}
```

It doesn't look like anything else is needed, since the existing call to `getMSALToken` (on go-azure-helpers v0.40.0) will now check if the IDToken has been provided, and will return something like:

```golang
Environment: ..., 
TenantID: "xxxxx-xxx-xxx-xxx-xxxx"
ClientID: "b5b4f00d-xxxx-xxxx-xxxx-xxxx"
FederatedAssertion: "eyJXc...oiYXJnbyIsInVpZCI6IjY4YWJlM."
ClientSecret: ""
Resource: ""
TokenURL: ""
Audience: ""
TokenVersion: TokenVersion2 (0)
Scopes: []string len: 1, cap: 1, ["https://management.azure.com/.default"]
PrivateKey: []uint8 len: 0, cap: 0, nil
Certificate: []uint8 len: 0, cap: 0, nil
AuxiliaryTenantIDs: []string len: 0, cap: 0, nil
```

However, if run `init` with the above changes, I get the following error:

```
│ Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "mystorage": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '6e8a22f4-yyyy-yyy-yyy-yyyy' with object id  '6e8a22f4-yyyy-yyy-yyy-yyyy' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/xxxxx-xxx-xxx-xxx-xxxx"5/resourceGroups/devrvk/providers/Microsoft.Storage/storageAccounts/mystorage' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

Notice how it is using a client with ID '6e8a22f4-yyyy-yyy-yyy-yyyy' (which also has the same object ID) instead of `b5b4f00d-xxxx-xxxx-xxxx-xxxx` the way I would expect.

I've narrowed the origin of the error down to (in internal/backend/remote-state/azure/arm_client.go) :

```golang
keys, err := c.storageAccountsClient.ListKeys(ctx, c.resourceGroupName, c.storageAccountName, "")
```

Nested deep within c.storageAccountsClient - at `(*(*(*(*(*c.storageAccountsClient).BaseClient.Client.Authorizer.(data)).Authorizer.(data)).Source.(data)).conf)` to be exact, the is a `github.com/manicminer/hamilton/auth.ClientCredentialsConfig` which contains the results of `getMSALToken` so at this point the ClientID, FederatedAssertion token etc. are all clearly in there

At some point ListKeys (which is a function in `azure-sdk-for-go`) calls the following

`resp, err := client.ListKeysSender(req)`

Stepping further into this function reveals very little to me, although someone who is more versed with the packages that are in use my know more. Long story short though, the `resp` that is returned here is the origin of the error message that is printed once `init` concludes.

**Comment by karlschriek** [comment]
Note, the above is based on branching from tag v1.2.9

**Comment by crw** [comment]
Thanks for this request and possible solution! I notified the Azure Provider team. Thanks again!

**Comment by matt3621** [comment]
> Thanks for this request and possible solution! I notified the Azure Provider team. Thanks again!

Hi, I've run into issues assuming the functionality in the backend mirrored the azurerm provider, while trying to use circleci OIDC to authenticate to Azure. Details here https://github.com/hashicorp/terraform-provider-azurerm/issues/18641, I opened this issue today and then searched the correct place and found this issue (and thankfully the reason terraform had been driving me crazy for the last few days),

Is this likely to be incorporated in a release any time soon ?

Many thanks

Matthew

**Comment by Amier3** [comment]
@karlschriek 

We'd definitely welcome a PR on this if you're still up for it. Your described approach is exactly what the team would do 😄 .


@matt3621 Thanks for reviving this conversation, if Karl is willing to take this up i'll let him give some context into when he'd be able to get the PR in. After that comes in we should be able to merge the PR before the following release.

**Comment by karlschriek** [comment]
Sure I'm happy to have a go at a PR. Anything I should know? Otherwise I'll just branch from HEAD and add the changes as described above.

**Comment by 11lein** [comment]
The fix from #31966 works for me with Gitlab and Azure Federated Identities (OIDC).

**Comment by adamrushuk** [comment]
Thought I'd share a blog post with example code of this working: https://adamrushuk.github.io/configure-terraform-openid-connect-oidc-authentication-from-gitlab-ci-to-azure/

**Comment by mattrawles** [comment]
> Thought I'd share a blog post with example code of this working: https://adamrushuk.github.io/configure-terraform-openid-connect-oidc-authentication-from-gitlab-ci-to-azure/

Thanks @adamrushuk for this and thanks to @karlschriek for getting this fix in, I can also confirm it works nicely on circleci, i've posted some examples https://github.com/CodeInAVan/cicd-oidc-authentication/tree/main/pipeline-examples/azure and also have referenced your blog (more working examples you can find on this the easier it is to adapt it to your use case!).
