### ISSUE TITLE
aws_glue_connection resource: no option for SSL Required? 

### ISSUE THREAD

**Issue by jeffrose-relay** [hashicorp/terraform#31807]
### Terraform Version

```shell
Terraform v1.2.8
on darwin_amd64
```

### Terraform Configuration Files

```terraform
resource "aws_glue_connection" "redshift_glue_connection" {
  name            = "redshift_conn_${terraform.workspace}"
  description     = "Glue connection to redshift"
  connection_type = "JDBC"
  connection_properties = {
    # connection_type = "JDBC"
    JDBC_CONNECTION_URL = "jdbc:redshift://${var.redshift_host}:5439/${var.redshift_db_name}"
    USERNAME            = var.redshift_username
    password            = ""
  }

  physical_connection_requirements {
    availability_zone      = data.aws_subnet.redshift_subnet.availability_zone
    security_group_id_list = tolist(data.aws_security_groups.security_groups.ids)
    subnet_id              = var.redshift_subnet_id
  }

}
```

### Debug Output

Require SSL Connection gets defaulted to False because there is no way for me to fill in this value.

### Expected Behavior

Should be able to fill in a value for `Require SSL connection`

### Actual Behavior

Cannot find any way to fill in `Require SSL connection`

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

Looking through https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_connection, I don't see any reference to the `Require SSL connection` option that is visible in the console.  There should be some way to fill this value in with terraform but I cannot find it.  I have also search stackoverflow but cannot find any solutions to this.
![image](https://user-images.githubusercontent.com/96207770/190676315-25a12893-06d6-4480-b33d-11c014f22237.png)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
