### ISSUE TITLE
Refreshing or validating a stored plan

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform#3181]
Once a plan has been created and written to a file, is there any way to re-validate it?

I can use `show` to read it, and `apply` to run - but I think I'd like a way to feed it back into `plan`, which would refresh and show me if the plan still makes sense against the current state.

**Comment by jasonkuhrt** [comment]
`terraform plan-refresh ...`

**Comment by glenjamin** [comment]
Using `terraform refresh <path-to-plan>` seems to correctly only refresh the resources contained in the plan - but gives no feedback as to whether the plan remains the same with the refreshed state.

**Comment by jasonkuhrt** [comment]
Sorry for the impossibly terse comment. Updated.

**Comment by mitchellh** [comment]
Thanks, this is a good idea.

We have bigger changes planned surrounding plan files in general. I'm going to close this since I think it should wait until after we make those changes, but ideas like this are involved in it.
