### ISSUE TITLE
Terraform is unable to populate usernameSource properly

### ISSUE THREAD

**Issue by mbrosius** [hashicorp/terraform#31824]
### Terraform Version

```shell
v1.2.2
```

### Terraform Configuration Files

```here's what's starting on line 94 of main.tf:

 

resource "azurerm_hpc_cache" "hpc_cache" {
  name                = local.cache_name
  resource_group_name = azurerm_resource_group.hpc_cache_rg.name
  location            = azurerm_resource_group.hpc_cache_rg.location
  cache_size_in_gb    = local.cache_size
  subnet_id           = module.network.cloud_cache_subnet_id
  sku_name            = local.cache_throughput
}  
```

### Debug Output

2022-08-01T12:55:09.676-0400 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: AzureRM Request:
GET /subscriptions/e981345d-8588-42e9-8bbf-57299b1f30ad/resourceGroups/vdbench4_hpc_filer_rg/providers/Microsoft.Network/networkInterfaces/nasfiler1-nic?api-version=2020-11-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.16.3 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.3.0 network/2020-11-01 HashiCorp Terraform/1.2.2 (+https://www.terraform.io) Terraform Plugin SDK/2.7.0 terraform-provider-azurerm/2.66.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
X-Ms-Correlation-Request-Id: cfc706a9-ebad-7b9d-755e-3cd566dbc405
Accept-Encoding: gzip: timestamp=2022-08-01T12:55:09.676-0400
2022-08-01T12:55:09.717-0400 [DEBUG] provider.terraform-provider-azurerm_v2.66.0_x5: AzureRM Response for https://management.azure.com/subscriptions/e981345d-8588-42e9-8bbf-57299b1f30ad/resourcegroups/vdbench4_hpccache_rg/providers/Microsoft.StorageCache/caches/ajointhpccache4?api-version=2021-03-01:
HTTP/2.0 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Mon, 01 Aug 2022 16:55:09 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-HTTPAPI/2.0
Server: Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: cfc706a9-ebad-7b9d-755e-3cd566dbc405
X-Ms-Ratelimit-Remaining-Subscription-Reads: 11999
X-Ms-Request-Id: fbfea375-9afa-4736-af22-b9ce292793db
X-Ms-Routing-Request-Id: EASTUS:20220801T165510Z:d263d66e-e500-4d3c-916b-f4b9baaf819e
X-Ms-Served-By: b898e293-1d26-47be-9bc7-2473812d8153_132969477689823239,b898e293-1d26-47be-9bc7-2473812d8153_132969477689823239

{
  "name": "ajointhpccache4",
  "id": "/subscriptions/e981345d-8588-42e9-8bbf-57299b1f30ad/resourceGroups/vdbench4_hpccache_rg/providers/Microsoft.StorageCache/caches/ajointhpccache4",
  "type": "Microsoft.StorageCache/caches",
  "location": "eastus2",
  "tags": {},
  "sku": {
    "name": "Standard_2G"
  },
  "properties": {
    "networkSettings": {
      "mtu": 1500,
      "utilityAddresses": [
        "10.0.1.10",
        "10.0.1.11",
        "10.0.1.12"
      ],
      "ntpServer": "time.windows.com"
    },
    "securitySettings": {
      "accessPolicies": [
        {
          "name": "default",
          "accessRules": [
            {
              "scope": "default",
              "access": "rw",
              "suid": false,
              "submountAccess": true,
              "rootSquash": false
            }
          ]
        }
      ]
    },
    "directoryServicesSettings": {
      "usernameDownload": {
        "extendedGroups": false,
       **"usernameSource": "None",**
        "groupFileURI": "",
        "userFileURI": "",
        "ldapServer": "",
        "ldapBaseDN": "",
        "encryptLdapConnection": false,
        "requireValidCertificate": false,

### Expected Behavior

When the usernameSource is "None" we get:
"Error: source type "None" is not supported"

When trying an empty string of "", we get the error:
"Error: source type "" is not supported"

### Actual Behavior

null_resource.delay: Refreshing state... [id=1757384545594975015]
?
¦ Error: source type "None" is not supported
¦
¦   with azurerm_hpc_cache.hpc_cache,
¦   on main.tf line 108, in resource "azurerm_hpc_cache" "hpc_cache":
¦  108: resource "azurerm_hpc_cache" "hpc_cache" {

### Steps to Reproduce

a value for usernameSource needs to have a supported value.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
