### ISSUE TITLE
associate-enclave-certificate-iam-role not exists in TF provider

### ISSUE THREAD

**Issue by fengjiang-v** [hashicorp/terraform#31829]
### Terraform Version

```shell
v1.1.7
```

### Use Cases

associate-enclave-certificate-iam-role is in aws cli but not in terraform https://docs.aws.amazon.com/cli/latest/reference/ec2/associate-enclave-certificate-iam-role.html

### Attempted Solutions

This limitation that the provider doesn't exist is a hard blocker so seems no other work around

### Proposal

There should be an enclave-certificate-association aws TF resource that allows users to associate enclave certificate to an IAM role

### References

https://docs.aws.amazon.com/cli/latest/reference/ec2/associate-enclave-certificate-iam-role.html

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by fengjiang-v** [comment]
cut one to AWS instead https://github.com/hashicorp/terraform-provider-aws/issues/26918
