### ISSUE TITLE
for_each in provider definition 

### ISSUE THREAD

**Issue by prmarino1m** [hashicorp/terraform#31835]
### Terraform Version

```shell
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
```

### Use Cases

This relates to all providers not just the AWS provider but I am using it as an example
I would like to create one provider file the covers all regions
I can write a script to generate one but it would be much simpler to use a for_each loop for this
it would also be nice to use a for_each on a provider alias in a resource

### Attempted Solutions

in the provider.tf replace <Profile_Name> with the name of a profile in your AWS cli configuration file 
`# documentation about this provider can be found here https://registry.terraform.io/providers/hashicorp/aws/latest/docs

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "us-east-2"
  profile = "<Profile_Name>"
  # The profile names are defined in ~/.aws/credentials
  # The names used must be consistent for all DevSecOps team members
}

data "aws_regions" "all" {
  all_regions = true

  filter {
    name   = "opt-in-status"
    values = ["opted-in" , "opt-in-not-required"]
  }
}

provider "aws" {
    for_each = toset(data.aws_regions.all.names)
    alias  = each.key
    region = each.key
    profile = "<Profile_Name>"
}`

currently this returns the following error when you run 'terraform init'

`
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Variables not allowed
│
│ On provider.tf line 29: Variables may not be used here.
╵

╷
│ Error: Unsuitable value type
│
│ On provider.tf line 29: Unsuitable value: value must be known
╵
`

and if i do a terraform apply I get this

'
│ Error: Invalid provider configuration alias
│
│ An alias must be a valid name. A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.
╵
╷
│ Error: Duplicate provider configuration
│
│   on provider.tf line 31:
│   31: provider "aws" {
│
│ A default (non-aliased) provider configuration for "aws" was already given at provider.tf:11,1-15. If multiple configurations are required, set the "alias" argument for alternative
│ configurations.
╵
╷
│ Error: Reserved argument name in provider block
│
│   on provider.tf line 32, in provider "aws":
│   32:                 for_each = toset( data.aws_regions.all.names )
│
│ The provider argument name "for_each" is reserved for use by Terraform in a future version.
╵
╷
│ Error: Variables not allowed
│
│   on provider.tf line 33, in provider "aws":
│   33:     alias  = each.key
│
│ Variables may not be used here.
╵
╷
│ Error: Unsuitable value type
│
│   on provider.tf line 33, in provider "aws":
│   33:     alias  = each.key
│
│ Unsuitable value: value must be known
'

### Proposal

What I would expect is for a provider to be created for each region with an alias that looks like aws.<Region_Name> 
also being able to provide a list of regions in a variable in my variables.tf file would be just as useful

furthermore it would be even more useful if in a resource block you could do 'provider = "aws.${each.key}" if I could at least do that then writing a script to generate the provider file would make sense

**Comment by prmarino1m** [comment]
incidentally using count and count.index would be a workable solution (if it didn't produce the same errors )to but for_each would be more useful.

**Comment by jbardin** [comment]
Hello @prmarino1m,

We can follow this request in the existing issue here: #19932

Thanks
