### ISSUE TITLE
intermittent "Failed authenticating with AWS: please verify credentials" errors when using AWS IAM

### ISSUE THREAD

**Issue by michaelneale** [hashicorp/terraform#3183]
I very occasionally get the error raised: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/config.go#L199

(ie a Signature failure). However, trying the request again after some period of time will work the exact same IAM credentials, ie nothing has changed but time has passed. (I have not yet worked out how long as reproducing this is difficult). 

If anyone else has seen this please comment with any extra details. I have seen this happen in other tools with caching of vended credentials.

**Comment by catsby** [comment]
Hey @michaelneale – I apologize for the very long silence here! I believe most IAM permission issues of this kind were resolved in https://github.com/hashicorp/terraform/pull/4254 , which would have been released in Terraform v0.6.9.

If you're still having issues, please let us know!
