### ISSUE TITLE
azurerm_key_vault_certificate ignores dependencies

### ISSUE THREAD

**Issue by slzmruepp** [hashicorp/terraform#31853]
### Terraform Version

```shell
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.28.1
+ provider registry.terraform.io/hashicorp/azurerm v3.1.0
+ provider registry.terraform.io/hashicorp/http v3.1.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.3
```

### Terraform Configuration Files
```shell
resource "azurerm_key_vault_certificate" "jump_vm_ssh" {
  name         = "jumpadm-${var.ENV}"
  key_vault_id = azurerm_key_vault.kv_breakinglass.id

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }

    lifetime_action {
      action {
        action_type = "AutoRenew"
      }

      trigger {
        days_before_expiry = 90
      }
    }

    secret_properties {
      content_type = "application/x-pem-file"
    }

    x509_certificate_properties {
      # Server Authentication = 1.3.6.1.5.5.7.3.1
      # Client Authentication = 1.3.6.1.5.5.7.3.2
      extended_key_usage = ["1.3.6.1.5.5.7.3.1"]

      key_usage = [
        "cRLSign",
        "dataEncipherment",
        "digitalSignature",
        "keyAgreement",
        "keyCertSign",
        "keyEncipherment",
      ]

      subject            = "CN=jumpadm-${var.ENV}"
      validity_in_months = 12
    }
  }
  lifecycle {
    ignore_changes = all
  }

  depends_on = [
    azurerm_key_vault.kv_breakinglass,
    azurerm_key_vault_access_policy.current_object,
  ]
}

data "azurerm_key_vault_certificate_data" "jump_vm_ssh" {
  name         = azurerm_key_vault_certificate.jump_vm_ssh.name
  key_vault_id = azurerm_key_vault.kv_breakinglass.id
  depends_on = [ 
    azurerm_key_vault_certificate.jump_vm_ssh,
    azurerm_key_vault.kv_breakinglass,
    azurerm_key_vault_access_policy.current_object,
   ]
}

data "tls_public_key" "jump_vm_ssh" {
  private_key_pem = data.azurerm_key_vault_certificate_data.jump_vm_ssh.key
  depends_on = [ data.azurerm_key_vault_certificate_data.jump_vm_ssh ]
}

resource "azurerm_key_vault_secret" "jump_vm_ssh" {
  name         = "${azurerm_key_vault_certificate.jump_vm_ssh.name}-pkey"
  value        = data.tls_public_key.jump_vm_ssh.private_key_pem
  key_vault_id = azurerm_key_vault.kv_breakinglass.id
  content_type = "jump_vm_ssh_priv_key"
  depends_on = [ 
    data.tls_public_key.jump_vm_ssh,
    azurerm_key_vault.kv_breakinglass,
    azurerm_key_vault_access_policy.current_object,
  ]
}

resource "azurerm_key_vault_access_policy" "current_object" {
  key_vault_id = azurerm_key_vault.kv_breakinglass.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  certificate_permissions = [
    "Backup",
    "Create",
    "Delete",
    "DeleteIssuers",
    "Get",
    "GetIssuers",
    "Import",
    "List",
    "ListIssuers",
    "ManageContacts",
    "ManageIssuers",
    "Recover",
    "Restore",
    "SetIssuers",
    "Update",
    "Purge",
  ]

  key_permissions = [
    "Backup",
    "Create",
    "Decrypt",
    "Delete",
    "Encrypt",
    "Get",
    "Import",
    "List",
    "Recover",
    "Restore",
    "Sign",
    "UnwrapKey",
    "Update",
    "Verify",
    "WrapKey",
    "Purge",
  ]

  secret_permissions = [
    "Backup",
    "Delete",
    "Get",
    "List",
    "Recover",
    "Restore",
    "Set",
    "Purge",
  ]
}
```
### Debug Output
```shell
}: timestamp=2022-09-23T08:15:45.977Z
2022-09-23T08:15:45.983Z [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for module.blob_private_endpoint.azurerm_private_endpoint.private_endpoint, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .private_service_connection[0].private_connection_resource_alias: planned value cty.StringVal("") for a non-computed attribute
      - .private_service_connection[0].request_message: planned value cty.StringVal("") for a non-computed attribute
╷
│ Error: reading Key Vault Certificate: keyvault.BaseClient#GetCertificate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=***;oid=43188ba7-33ed-46ce-859e-8ecdc8791134;iss=https://sts.windows.net/18b0f0de-9099-4ee4-8ffc-cd75b3ef9d6c/' does not have certificates get permission on key vault 'kv-bg-kqqx-int;location=westeurope'. For help resolving this issue, please see [https://go.microsoft.com/fwlink/?linkid=2125287"](https://go.microsoft.com/fwlink/?linkid=2125287%22) InnerError={"code":"AccessDenied"}
│ 
│   with azurerm_key_vault_certificate.jump_vm_ssh,
│   on secrets.tf line 14, in resource "azurerm_key_vault_certificate" "jump_vm_ssh":
│   14: resource "azurerm_key_vault_certificate" "jump_vm_ssh" {
│ 
╵
```
### Expected Behavior

We configure Azure Vault Access Policies. We got in a terrible mess by adding a terraform managed vault to Azure Devops and then removed it again.
Azure Devops adds and removes vault access policies. After rerun our terraform pipelines, the service principal was either not able to read the secrets, or to add the access policies because it stated "The access policies are already existing".

Now after refactoring the code to depend the certificate on the policies existing, manually delete all policies from the azure vault object, the certificate block tries to read the certificate despite the fact, that the access policy for the service principal of the pipeline run is still not existing and not created.

### Actual Behavior

We expect that the depends_on block is respected, and every action on the resource "azurerm_key_vault_certificate" respects the depends_on, that the access policy is actually existing.

### Steps to Reproduce

Use a service principal to apply terraform
Create a key vault, access policy for the service principal, a certificate and then store it in the key vault.
Delete the access policy through azure cli or gui 
Reapply the terraform config and expect the accesspolicy to get recreated BEFORE Terraform tries to access the stored certificate

**Comment by slzmruepp** [comment]
So now we are in complete misery of recursive dependencies. Because If we try to add get and list permissions manually for the service principal in the Azure GUI, and reapply, the run fails with the hint that the policy object already exists. And if we delete the policy, to let terraform reapply, it fails because it can not read secrets, despite depends_on is set on the policiy.

It is very bad and a complete blocker to roll out changes in infrastructure for us in the future. It is very bad.

```shell
X-Ms-Version: 2018-11-09
╷
│ Error: A resource with the ID "/subscriptions/60ec4723-77d3-44c8-b80e-39dccb661ab5/resourceGroups/rg-app-infra-master-int/providers/Microsoft.KeyVault/vaults/kv-bg-kqqx-int/objectId/43188ba7-33ed-46ce-859e-8ecdc8791134" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.
│ 
│   with azurerm_key_vault_access_policy.current_object,
│   on vault.tf line 67, in resource "azurerm_key_vault_access_policy" "current_object":
│   67: resource "azurerm_key_vault_access_policy" "current_object" {
│ 
╵
2022-09-23T08:59:35.892Z [DEBUG] Azure Backend Request: 
```

**Comment by slzmruepp** [comment]
Now terraform wants to destroy all our K8s Cluster and Nodepools and recreate it, because we only changed by accident the Access Policy of the key vault where the k8s admin certificate and pkey was stored. This is such a huge mess I can not believe. All was happening was that the Azure DevOps add of the key vault in the pipeline changed the access policy of the key vault. We can not believe this.

**Comment by jbardin** [comment]
Hi @slzmruepp,

Sorry you are having trouble with this. The problems here do not appear to be from the Terraform CLI. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help.

Users familiar with [Azure infrastructure](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) are more likely to be able to help you recover from the problems here. Since this repository is monitored only by a few Terraform core maintainers, we don't generally have the experience to advise on specific provider related issues.

Thanks!

**Comment by slzmruepp** [comment]
@jbardin This is a bug and should not be closed. The problem is that a secret created in the key vault is read before the respective azure key vault policy is created. Even if we add the depends_on block to the secret or the data structure, the policy does not get created beforehand. Please reopen the issue otherwise I have to file it again.
