### ISSUE TITLE
terraform init: hidden (dot)files aren't copied

### ISSUE THREAD

**Issue by JeanMertz** [hashicorp/terraform#3185]
When I execute `terraform init /path/to/module`, `.dot` files are ignored. In our use case, a `.envrc` file wasn't copied, which is used to set specific Terraform environment variables.

Is this by design?

**Comment by mitchellh** [comment]
Yes it is, Terraform's module downloader from paths ignores dot files. This avids for example scenarios with VERY large ".git" folders. I'm not sure if there is a better approach here. Given this hasn't come up in over a year though, I feel we should leave it as-is for now.
