### ISSUE TITLE
Error: Invalid count argument in Terraform v1.3.0

### ISSUE THREAD

**Issue by SimonG-Kontentai** [hashicorp/terraform#31852]
### Terraform Version

```shell
Terraform: 1.3
AzureRM: 3.23.0
AzureAD: 2.28.1
Fastly: 2.3.2
```

### Terraform Configuration Files
**simplified/cropped configuration**
```terraform
// Event Hub
variable "event_hub_names" {
  type        = list(string)
  default     = []
}

variable "event_hub" {
  type = object({
    partition_count   = optional(number, 2)
    message_retention = optional(number, 1)
  })
  default = {
    partition_count   = 2
    message_retention = 1
  }
}

// Event Hub Consumer Group Name
variable "consumer_group_names" {
  type        = list(string)
  default     = []
}

locals {
  consumer_groups = flatten([
    for event_hub in azurerm_eventhub.default : [
      for consumer_group_name in var.consumer_group_names : [
        {
          event_hub_name      = event_hub.name
          consumer_group_name = consumer_group_name
        }
      ]
    ]
  ])
}

resource "azurerm_eventhub_namespace" "default" {
  name                = var.event_hub_namespace.name
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name

  auto_inflate_enabled     = var.autoscaling.enabled
  maximum_throughput_units = var.autoscaling.max_units

  sku      = var.event_hub_namespace.sku
  capacity = var.event_hub_namespace.capacity

  lifecycle {
    ignore_changes = [
      capacity
    ]
  }
}

resource "azurerm_eventhub" "default" {
  count = length(var.event_hub_names)

  name                = element(var.event_hub_names, count.index)
  namespace_name      = azurerm_eventhub_namespace.default.name
  resource_group_name = var.resource_group.name

  partition_count   = var.event_hub.partition_count
  message_retention = var.event_hub.message_retention
}

resource "azurerm_eventhub_consumer_group" "default" {
  **count = length(local.consumer_groups)** <- this is the problem

  name                = element(local.consumer_groups, count.index).consumer_group_name
  resource_group_name = var.resource_group.name
  namespace_name      = azurerm_eventhub_namespace.default.name
  eventhub_name       = element(local.consumer_groups, count.index).event_hub_name
}
```

### Debug Output

None

### Expected Behavior

Everything is fine with Terraform 1.2.9

### Actual Behavior

Error: Invalid count argument

  on ..\..\modules_azure\_metaResources\EventHub\eventHub.tf line 47, in resource "azurerm_eventhub_consumer_group" "default":
  47:   count = length(local.consumer_groups)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

### Steps to Reproduce

A new environment with few resources that must be first imported

Terraform import

### References

- #31851
- #31846

**Comment by jbardin** [comment]
Hi @SimonG-Kontentai,

Thanks for filing the issue. Something seems to have changed in how `local.consumer_groups` is being evaluated here. There was a fix to `flatten` upstream in the cty package, but I don't think that would cause any new unknown values to appear. The difference may be from what is being passed into the module. Can you show how `var.consumer_group_names` is being derived during the plan?

Thanks!

**Comment by SimonG-Kontentai** [comment]
Sure. We use the module in 4 places.
1.
```
locals
{
event_hub_consumer_group_name = "cdn-log-service"
}

module "event_hub" {
   ...
  consumer_group_names = [local.event_hub_consumer_group_name]
}
```
2.
```
module "event_hub" {
   ...
  consumer_group_names = ["consistency-check", "dispatcher"]
}
```
3.
```
module "event_hub" {
  ...
 _doesn't contain definition for consumer_group_name_ -> **by default it should be [] as defined in the variable block**
}
```
4.
```
locals{
  consumer_group_name_state      = "state-stream-job"
  consumer_group_name_delta      = "delta-stream-job"
  consumer_group_name_disabled   = "disabled-stream-job"
}
module "event_hub" {
  ...
  consumer_group_names = [local.consumer_group_name_delta, local.consumer_group_name_state, local.consumer_group_name_disabled]
}
```

**Comment by SimonG-Kontentai** [comment]
@jbardin Today I tried Terraform 1.3.2, but the problem still occurs. My workaround for this is 

consumer_groups = flatten([
    for event_hub in **var.event_hub_names** : [
      for consumer_group_name in var.consumer_group_names : [
        {
          event_hub_name      = event_hub
          consumer_group_name = consumer_group_name
        }
      ]
    ]
  ])

and add depends_on block for
resource "azurerm_eventhub_consumer_group" "default" {
...
  depends_on = [
    azurerm_eventhub.default
  ]
}
