### ISSUE TITLE
azurerm mysql flexible server Error: failover only supports exchange between `zone` and `standby_availability_zone`

### ISSUE THREAD

**Issue by myehya-up** [hashicorp/terraform#31882]
### Terraform Version

```shell
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.23.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/tls v4.0.3
```

### Terraform Configuration Files

```resource "azurerm_mysql_flexible_server" "mysql" {
  name                   = "db-up-atlas-${var.env}-${var.location}"
  resource_group_name    = var.rg_name
  location               = var.location
  administrator_login    = "xxxx"
  administrator_password = "xxxx"
  backup_retention_days  = 7
  delegated_subnet_id    = azurerm_subnet.db_subnet.id
  private_dns_zone_id    = azurerm_private_dns_zone.db_dns_zone.id
  sku_name               = var.mysql_sku
  version                = "5.7"
  geo_redundant_backup_enabled = true
  create_mode            = var.mysql_create_mode
  zone                   = "1"                     ## This will not work with westus module because westus does not accept zones redundancy choices
  high_availability {
    mode                 = "SameZone"
    standby_availability_zone = "2"
  }
  maintenance_window {
    day_of_week  = 0
    start_hour   = 4
    start_minute = 0
  }
```

### Debug Output

Debug Output

### Expected Behavior

Provision a mysql flex server resource with HA, without having to designate a zone

### Actual Behavior

│ Error: waiting for creation of Flexible Server: .. : Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '18a42903-5d1b-462b-b5ba-26698688bca4'"
│ 
│   with module.mysql_flex["westus"].azurerm_mysql_flexible_server.mysql,
│   on modules/database/mysql_flexible_server.tf line 35, in resource "azurerm_mysql_flexible_server" "mysql":
│   35: resource "azurerm_mysql_flexible_server" "mysql" {
│ 
╵
╷
│ Error: failover only supports exchange between `zone` and `standby_availability_zone`
│ 
│   with module.mysql_flex["eastus"].azurerm_mysql_flexible_server.mysql,
│   on modules/database/mysql_flexible_server.tf line 35, in resource "azurerm_mysql_flexible_server" "mysql":
│   35: resource "azurerm_mysql_flexible_server" "mysql" {

### Steps to Reproduce

terraform init
terraform plan
terraform apply

### Additional Context

This will not work with westus region because westus does not allow zones, but if I were to create an instance via portal I could do so with high availability enabled and without defining a zone. I cannot seem to do this with Terraform as it seems to hard require a zone to be selected for HA. I would like to be able to deploy HA instance without any zone defined.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
