### ISSUE TITLE
setsubtract example does not behave as expected

### ISSUE THREAD

**Issue by HaanJde** [hashicorp/terraform#31909]
### Terraform Version

```shell
$ terraform --version
Terraform v1.3.1
on linux_amd64
$
```

### Terraform Configuration Files

```terraform
...terraform config...
    none
```

### Debug Output

```
$ TF_LOG=trace
$ terraform console
> setsubtract(["a", "b", "c"], ["a", "c"])
toset([
  "b",
])
> exit
$
```

### Expected Behavior

```
$ terraform console
> setsubtract(["a", "b", "c"], ["a", "c"])
[
  "b",
]
> exit
$
```

### Actual Behavior

```
$ terraform console
> setsubtract(["a", "b", "c"], ["a", "c"])
toset([
  "b",
])
> exit
```

### Steps to Reproduce

$ terraform console
> setsubtract(["a", "b", "c"], ["a", "c"])
toset([
  "b",
])
> exit

### Additional Context

This issue can be worked around by applying a 'flatten()':

```
$ terraform console
> flatten(setsubtract(["a", "b", "c"], ["a", "c"]))
[
  "b",
]
> exit
$ 
```

### References

The issue concerns a literal example from the official documentation that actually does not work as expected:

https://www.terraform.io/language/functions/setsubtract#examples

**Comment by jbardin** [comment]
Hi @HaanJde,

Thanks for filing the issue. The behavior is correct here, but the documentation needs to be updated to reflect the `toset()` notation that will be seen in the console to help indicate the correct type to users.

Thanks!
