### ISSUE TITLE
Object schema validation ignores invalid/non-schema attributes

### ISSUE THREAD

**Issue by marceloboeira** [hashicorp/terraform#31904]
### Terraform Version

```shell
Terraform v1.3.1
on darwin_amd64
```

## example/variables.tf
```terraform
variable "password" {
  type = object({
    length = optional(number, 99)
  })
  default = {}
}
```

## main.tf
```terraform
module "example" {
  source = "./example"

  password = {
    length = 99
    invalid = "attribute" # sending an attribute that is NOT part of the schema
  }
}
```

### Debug Output

--

### Expected Behavior

An error OR at least warn message emphasizing the `invalid` attribute is not part of the schema.

### Actual Behavior

The attribute is ignored and nothing happens

### Steps to Reproduce

1. `terraform init`
1. `terraform plan`

### Additional Context

Is that something that should be part of HCL?

**Comment by jbardin** [comment]
Hi @marceloboeira,

Thanks for filing the issue. Module inputs don't really have a schema per say, and the ability to implicitly convert an object to another with only a subset of attributes was a design feature of the Terraform language. In other words, the behavior you see here is working as designed.

You can see a more detailed discussion about the feature in #29204.

Thanks!
