### ISSUE TITLE
Databricks Credential pass-through ADLS is not working - is it supported or not ?

### ISSUE THREAD

**Issue by ShivaniThadiyan** [hashicorp/terraform#31913]
### Terraform Version

```shell
3.0.2
```

### Terraform Configuration Files

resource "databricks_mount" "passthrough" {
  name       = "pass-ADLS"
  cluster_id = databricks_cluster.shared_autoscaling.id
  uri = "abfss://${var.DBcontainer}@${var.storage_ADLSacc}.dfs.core.windows.net"
  configs = {   
    "fs.azure.account.auth.type": "CustomAccessToken",  
    "fs.azure.account.custom.token.provider.class": {{spark.conf.get/spark.databricks.passthrough.adls.gen2.tokenProviderClassName}}"
  }
  depends_on = [databricks_cluster.shared_autoscaling]
}

### Debug Output

 Error: failed to re-create mounting cluster: cannot configure azure-client-secret auth: cannot get workspace: please set `azure_workspace_resource_id` provider argument. Environment variables used: ARM_CLIENT_SECRET, ARM_CLIENT_ID, ARM_TENANT_ID. Please check https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication for details

### Expected Behavior

Credential pass-through should be enabled on databricks cluster

### Actual Behavior

while connecting to ADLS, it should work.

### Steps to Reproduce

terraform init
terraform plan
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
