### ISSUE TITLE
Support strings validation using `ValidateFunc` from the resource schema

### ISSUE THREAD

**Issue by AlexPykavy** [hashicorp/terraform#31921]
### Terraform Version

```shell
Terraform v1.2.8
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.3.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

It'll be useful for multistate/multiproject Terraform approach. For example, to validate one project's output variables which are consumed by the dependent Terraform project.

### Proposal

I suggest implementing a `validate` function that takes an input string and an attribute path(s) from which `ValidateFunc` will be used and returns the input string if validation passed or throws an error.

For instance,
```
output "example_role_definition_id" {
  value = validate(azurerm_role_definition.example.role_definition_resource_id, 'azurerm_role_assignment.role_definition_id')
}
```
or
```
output "example_role_definition_id" {
  value = validate(
    azurerm_role_definition.example.role_definition_resource_id,
    'azurerm_role_assignment.role_definition_id',
    'another_resource.role_definition_id'
  )
}
```

**Comment by kmoe** [comment]
What output would you expect to see given the example code?

It's true that resources have schemas defined by the provider, in which a `ValidateFunc` may be defined - this is called automatically by Terraform at the validate stage. What would you expect the `validate()` func in configuration to do above and beyond this?

**Comment by AlexPykavy** [comment]
Closing the issue since it doesn't seem useful as I thought before.
