### ISSUE TITLE
Issue with Terraform State/Config after import of resources that include Optional Parameters

### ISSUE THREAD

**Issue by shrusubra** [hashicorp/terraform#31926]
### Terraform Version

```shell
Terraform v1.3.1
- provider registry.terraform.io/hashicorp/oci v4.95.0
```

### Terraform Configuration Files

```
```

### Debug Output

-

### Expected Behavior

No changes. Your infrastructure matches the configuration.

### Actual Behavior

```
  # module.nsg-rules["NSG1-1_security_rule4"].oci_core_network_security_group_security_rule.nsg_rule will be updated in-place
  ~ resource "oci_core_network_security_group_security_rule" "nsg_rule" {
        id                        = "4F8DCF"
        # (9 unchanged attributes hidden)

      ~ tcp_options {
          - destination_port_range {
              - max = 40 -> null
              - min = 21 -> null
            }
        }

        # (1 unchanged block hidden)
    }

  # module.nsg-rules["NSG1-1_security_rule5"].oci_core_network_security_group_security_rule.nsg_rule will be updated in-place
  ~ resource "oci_core_network_security_group_security_rule" "nsg_rule" {
        id                        = "05F7D7"
        # (9 unchanged attributes hidden)

      ~ tcp_options {

          - source_port_range {
              - max = 12 -> null
              - min = 12 -> null
            }
        }

        # (1 unchanged block hidden)
    }
# module.nsg-rules[“NSG1-1_security_rule12”].oci_core_network_security_group_security_rule.nsg_rule will be updated in-place
 ~ resource “oci_core_network_security_group_security_rule” “nsg_rule” {
    id            = “BC5A21"
    # (9 unchanged attributes hidden)
   - icmp_options {
     - code = -1 -> null
     - type = 2 -> null
    }
    # (1 unchanged block hidden)
  } 
```

We use modules to create the resources. Which works fine.

But there is an issue with import of resources using terraform for NSGs. While we import the resources, we find the ICMP and TCP options getting replaced by null as shown above. Can anyone guide us to avoid this please?

### Steps to Reproduce

1. Terraform import of the resource
2. Terraform plan

### Additional Context

This issue started appearing only when we use Optional type parameters as below - 

variable "nsg_rules" {
  type = map(object({
    nsg_id           = string
    direction        = string
    protocol         = string
    description      = optional(string)
    stateless        = optional(string)
    source_type      = optional(string)
    destination_type = optional(string)
    destination      = optional(string)
    source           = optional(string)
    options          = optional(map(any))
  }))
  default = {}
}

Options have the data related to TCP, UDP , ICMP

**Comment by jbardin** [comment]
Hi @shrusubra,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

In this case the provider is likely setting the fields during the import process, which are not present in the configuration. If the absence of the config make no difference in the remote object, then the provider should adjust the plan accordingly. If the fields are required, then they must be added to the configuration to prevent any change in the plan.

Thanks!
