### ISSUE TITLE
> @Dan-Bai which Azure Environment is this running in? Can you provide the debug logs here so that we can take a look into this?

### ISSUE THREAD

**Issue by motsis666** [hashicorp/terraform#31923]
> @Dan-Bai which Azure Environment is this running in? Can you provide the debug logs here so that we can take a look into this?

@tombuildsstuff 
This is running in Azure Public Cloud.
Currently trying to generate the logs. Is there a specific piece you are looking for? This is a small part of a larger terraform project so the logs is looking to be 50MB+.

_Originally posted by @Dan-Bai in https://github.com/hashicorp/terraform-provider-azurerm/issues/16451#issuecomment-1103998285_

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
