### ISSUE TITLE
No Definition Found when using Lookup with Default Value

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/terraform#31938]
### Terraform Version

```shell
Terraform v1.3.1
on linux_amd64
```

### Terraform Configuration Files

```terraform
locals {
  products = {
    "product1" = {
      # ...
      applications = {
        "ruby-web" = {
          # does not include protocol key
        }
        web = {
          # does not include protocol key
        }
      }
    }
  }
}

module "products" {
  for_each      = local.products
  source        = "./products"
  # ...
  applications  = lookup(each.value, "applications", {})
}
```

Products module:

```terraform
variable "applications" {
  type = map(object({
    # ...
    protocol                 = optional(string)            # line 109
  }))
}

resource "boundary_target" "applications" {
  for_each                 = var.applications
  # ...
  type                     = lookup(each.value, "protocol", "tcp")
}
```

### Debug Output

Errors:

```
╷
│ Error: Missing required argument
│ 
│   with module.products["product1"].boundary_target.applications["web2"],
│   on products/main.tf line 109, in resource "boundary_target" "applications":
│  109:   type                     = lookup(each.value, "protocol", "tcp")
│ 
│ The argument "type" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   with module.products["product1"].boundary_target.applications["web1"],
│   on products/main.tf line 109, in resource "boundary_target" "applications":
│  109:   type                     = lookup(each.value, "protocol", "tcp")
│ 
│ The argument "type" is required, but no definition was found.
╵
Releasing state lock. This may take a few moments...
ERROR: Job failed: exit code 1
```

I did not create a gist of the entire debug output because it would take too long to sanitize.  Please let me know if you require some specific portion of it.  Relevant trace portion:

```
2022-10-04T16:14:12.183Z [ERROR] vertex "module.products[\"product1\"].boundary_target.applications[\"web1\"]" error: Missing required argument
2022-10-04T16:14:12.183Z [TRACE] vertex "module.products[\"product1\"].boundary_target.applications[\"web1\"]": visit complete, with errors
2022-10-04T16:14:12.183Z [ERROR] vertex "module.products[\"product1\"].boundary_target.applications[\"web2\"]" error: Missing required argument
2022-10-04T16:14:12.183Z [TRACE] vertex "module.products[\"product1\"].boundary_target.applications[\"web2\"]": visit complete, with errors
2022-10-04T16:14:12.183Z [TRACE] dag/walk: upstream of "root" errored, so skipping
2022-10-04T16:14:12.183Z [TRACE] vertex "module.products.boundary_target.applications (expand)": dynamic subgraph encountered errors: Missing required argument,Missing required argument
2022-10-04T16:14:12.183Z [ERROR] vertex "module.products.boundary_target.applications (expand)" error: Missing required argument
2022-10-04T16:14:12.183Z [ERROR] vertex "module.products.boundary_target.applications (expand)" error: Missing required argument
2022-10-04T16:14:12.183Z [TRACE] vertex "module.products.boundary_target.applications (expand)": visit complete, with errors
```

### Expected Behavior

Default value should be used.

### Actual Behavior

Default value is being ignored.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Additional Context

Terraform is running in a CI system, specifically a Gitlab runner using docker image `terraform:latest`, whose version output is above.  No unusual command line options or environment variables are being used.  No experimental features are being used.

**Comment by alisdair** [comment]
The `lookup` function used against an object which has definitively has an attribute of the given name is redundant. Because you are using an `optional` modifier on the attribute without a default, if it is unspecified when binding the value to the variable, Terraform will add a `null` value of the appropriate type.

As a result, what is happening here is that `lookup` is returning that `null`, since it is present. Your main options here are:

- Define the desired default value of that attribute in the variable type, if that's appropriate:

    ```hcl
    variable "applications" {
      type = map(object({
        # ...
        protocol                 = optional(string, "tcp")
      }))
    }
    ```
- Use [the `coalesce` function](https://www.terraform.io/language/functions/coalesce) instead, which returns the first of its arguments which is not `null`: `coalesce(each.value.protocol, "tcp")`

Assuming this explanation is correct, I don't believe this is a bug in Terraform, so I'm going to mark this issue closed. Let me know if I've misunderstood.

**Comment by micchickenburger** [comment]
Thanks for the quick response @alisdair!  I think your description is correct.  I was not aware of the default parameter of the `optional` function.  I put the default values in the `variable` description and removed the lookup functions altogether, which is working great.  I think it would be beneficial to mention explicitly in the [Lookup documentation](https://www.terraform.io/language/functions/lookup) that the default is not applied if the value is set to `null`.  I think many folks with particular programming backgrounds may consider the statement `if the given key does not exist` to mean falsey (as I did), which would then create the expectation that `null` should also be replaced with the default.
