### ISSUE TITLE
Please change "Experiment has concluded" messages from Error to Warning messages

### ISSUE THREAD

**Issue by ServerNinja** [hashicorp/terraform#31931]
### Terraform Version

```shell
terraform version
Terraform v1.3.1
on darwin_amd64
```

### Use Cases

The "concluded experiments" throws an error when the experiment is merged in with the code base. For Terraform 1.3.0, the "module_variable_optional_attrs" experiment was merged in and when running `terraform init`, it throws the error shown below until the line for the experiment is removed from the `terraform {}` block. **I realize that this method of letting users know the experiment was concluded may have been implemented by design which is why I'm requesting this to be changed.**

If this is not changed, it will prevent teams from upgrading to Terraform 1.3.x as long as there are modules their code base depends on that contain this one line.

As it stands, we will never be able to upgrade to 1.3.x as long as modules such as these contain this line: `experiments = [module_variable_optional_attrs]`

### Example of why this is such a problem that a feature request to fix this is needed:

This block (terraform.tf) fails with the error seen below:
```
terraform {
   required_version = "~> 1.3.1"

   experiments = [module_variable_optional_attrs]
}
```

```
terraform init
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Experiment has concluded
│
│   on terraform.tf line 4, in terraform:
│    4:    experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding
│ to this experiment differs from the experimental form and is available in the Terraform language from
│ Terraform v1.3.0 onwards.
╵
```

### Attempted Solutions

There seems to be no way to get around this method of concluding experiments that is used with terraform.

### Proposal

I propose that the terraform CLI is changed so it no longer exits with an error for referencing "concluded experiments" . Instead, I would like to request that it only throws a warning.

Example:
```
╷
│ Warning: Experiment has concluded
│
│   on terraform.tf line 4, in terraform:
│    4:    experiments = [module_variable_optional_attrs]
│
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding
│ to this experiment differs from the experimental form and is available in the Terraform language from
│ Terraform v1.3.0 onwards.
```

### References

An example of such a case is the terraform-aws-eks-blueprints module: https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/984 (Related issue: https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/982)

Currently we are unable to use the most recent version of this module with Terraform 1.3.x.

**Comment by jbardin** [comment]
HI @ServerNinja,

Sorry you're having trouble with the process, unfortunately there's not really any way around the current error you are getting. You can find more information in some of the prior issues, like #31692, #31355, but the fundamental issue here is that modules using the old `module_variable_optional_attrs` are not compatible with the current release of Terraform. The feature was changed significantly from the original design which was found to be unusable in many circumstances, and attempting to use experimental modules with the new feature would either fail entirely on the use of `defaults`, or more subtly with unexpected changes in behavior.

If you are a module author working to remove the experimental feature, you may want to start a discussion in [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by ServerNinja** [comment]
@jbardin , I understand your reason for closing this. However, why not just tell the user that the "experimental" module is no longer available in a "Warning" message? **It would be difficult to expect authors of modules to change their code to remove this one line, which would break the module for terraform < 1.3.0 in order to get it working with terraform > 1.3.0.**. There needs to be a way to maintain backward compatibility instead of making your newer version completely incompatible with code because of this one line in the `terraform {}` block. Otherwise, there should be a way to make the experimental line conditional to the version of terraform in use. Ie.

```
terraform {
   required_version = "~> 1.3.1"

   for_version_1.2.x_and_older {
        experiments = [module_variable_optional_attrs]
   }
}
```
But even that would require every module author to change their code ^^^

This doesn't make any sense from the perspective that if a development team depends on dozens of modules from various vendors that happen to be using the experimental module_variable_optional_attrs feature that they need to wait for every single module to update their code to 1.3.x in order to be usable. This is only going to keep people from using the newest version of your product for a long period of time.

**Comment by jbardin** [comment]
Hi @ServerNinja,

Terraform issuing a warning implies that it can continue executing the given configuration, but that is not true here. Removing the error about the experiment would just cause Terraform to fail outright when trying to use configuration which is not valid in v1.3. Moving a module from the original `module_variable_optional_attrs` experiment is more involved than simply removing that line, the defaults are defined differently, and in many cases, the resulting objects can contain different values.

The is the reason why experiments were accompanied by warning messages when they were used in the first place, because the actual design and use of the experiment was not finalized and could change in any release. As stated in the other issues, we've since removed the experiments feature from all final releases because the warning alone was not sufficient to prevent them from being used in production configurations.

**Comment by alexeyatbluescape** [comment]
@jbardin fair points, but there are a lot of modules that utilized that experimental feature in their stable releases. This means a breaking change for all modules. Once `module_variable_optional_attrs` is removed, that module can't be used on TF prior 1.3... Not sure if it is possible, but there is a less aggressive depreciation approach where `module_variable_optional_attrs` is simply ignored by TF, and a warning is thrown. All optional functions are parsed as per TF 1.3 syntax.

This impacts larger projects where multiple modules are mixed... which prevents usage of TF 1.3 until ALL modules drop this feature.

**Comment by etaham** [comment]
Agreed with @alexeyatbluescape. This error is making it very difficult to upgrade to 1.3 - especially when using terraform at scale. If you can't convert it to warning in 1.3, would it be possible to patch 1.2 to allow us to remove the flag but still use the feature (or even replace with a flag that would be compat with both versions)?

In our case, it would be much better to just fail specific pipelines for newly invalid usage. We could proceed with a 1.2 & 1.3 compatible code based until we safely upgrade all pipelines. Then convert back to an error in 1.4.
