### ISSUE TITLE
AWS S3 state backend fails with AWS SSO (IAM Identity Center)

### ISSUE THREAD

**Issue by MartinEmrich** [hashicorp/terraform#31943]
### Terraform Version

```shell
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1

(happened with 1.2.8, too)
```

### Terraform Configuration Files

Remote backend configuration:

````
terraform {
  required_version = ">= 1.1.0"
  backend "s3" {
    bucket                  = "xxx-my-bucket-name-xxx"
    key                     = "terraform_state"
    encrypt                 = true
  }
````

### Debug Output

No relevant debug output except the few lines below (Actual Behaviour)

### Expected Behavior

Terraform should access the state store, regardless of whether I use an IAM user or an SSO user. Using an AWS profile with API Key/Secret (I.e. normal IAM user), I can e.g. access the stack outputs with `AWS_PROFILE=xxx AWS_REGION=yyy terraform output", using an SSO user, despite having permissions, results in the behaviour below.

### Actual Behavior

When using an AWS SSO profile, I get this error:

````
...
2022-10-05T15:19:40.231+0200 [TRACE] Meta.Backend: BackendOpts.Config not set, so using settings loaded from backend_remote.tf:4,3-15
2022-10-05T15:19:40.231+0200 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 1129146272
2022-10-05T15:19:40.231+0200 [TRACE] Preserving existing state lineage "5cf4475d-b0ac-4079-b062-744aa401e94b"
2022-10-05T15:19:40.231+0200 [TRACE] Preserving existing state lineage "5cf4475d-b0ac-4079-b062-744aa401e94b"
2022-10-05T15:19:40.231+0200 [TRACE] Meta.Backend: working directory was previously initialized for "s3" backend
2022-10-05T15:19:40.231+0200 [TRACE] Meta.Backend: using already-initialized, unchanged "s3" backend configuration
2022-10-05T15:19:40.232+0200 [INFO]  Attempting to use session-derived credentials
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│
│ Error: : Found invalid number of authz details: []
│       status code: 500, request id: 12696bf9-002f-4778-b2f5-eeaca5bad054
│
│
│
╵
````

### Steps to Reproduce

1. Configure S3 remote state backend (including creating the bucket, making sure your AWS permissions are sufficient, etc.)
2. Configure your AWS client to use AWS IAM Identity Center (SSO). Example ~/.aws/config entry:

````
[profile xxx]
sso_start_url = https://d-XXXXXXXXX.awsapps.com/start
sso_region = yyy
sso_account_id = 123456789012
sso_role_name = SomeRoleNameFromYourPermissionSet
region = yyy
````
3. Login with `AWS_PROFILE=xxx aws sso login`
4. confirm that your bucket is accessible (e.g. `AWS_PROFILE=xxx AWS_REGION=yyy aws s3 ls <your-bucket-name>`)
5. Run e.g. `terraform init`, and receive the error message above.

**Comment by MartinEmrich** [comment]
As AWS-CLI worked fine, I never suspected the login itself to be a problem. but i noticed that e.g. `kubectl` also failed with the same error, I tried on a hunch to log out of AWS (`aws sso logout`) an then logged in again.
Now terraform works again for me.

So apparently it is not a problem in terraform, but in the AWS SDK used, just a less-cryptic error message might be an improvement.

For anyone interested: I have configured the AWS IAM Identity Center (SSO) PermissionSet for 12 hours session duration, but in my ~/.aws/sso/cache/XXX.json file, the fresh login only produced an expiresAt date 8 hours in the future. My speculation: The AWS CLI (python-based) ignores that field and just tries to use the token, while the Golang SDK checks that expiration date... And I might just have been in that window between 8 and 12 hours.

If the terraform team closes this issue, it would be fine with me, but if the error message "no valid credential sources for S3 Backend found" is up for improvement, it would be nice.

**Comment by aquarhead** [comment]
I have this exact problem since a few days ago, but it fails even within the expiry which is very confusing, it had always worked for me before. I've also tried using both 1.2.9 and 1.2.8 Terraform CLI, but still get the same error

```
$ date
Wed Oct  5 14:21:00 GMT 2022

$ cat ~/.aws/sso/cache/abc.json
{"startUrl": "...", "region": "eu-central-1", "accessToken": "...", "expiresAt": "2022-10-05T20:30:53Z"}
```

**Comment by MartinEmrich** [comment]
@aquarhead did you also increase your PermissionSet token lifetime? (Default is 1 hour only, apparently AWS CLI always uses 8 hours for expiresAt, even if the PermissionSet has less.

**Comment by aquarhead** [comment]
> @aquarhead did you also increase your PermissionSet token lifetime? (Default is 1 hour only, apparently AWS CLI always uses 8 hours for expiresAt, even if the PermissionSet has less.

I didn't change it, but I believe it's 12 hours, never noticed issue before, like 2 days ago though.

**Comment by aquarhead** [comment]
@MartinEmrich could you check if your cached SSO token appears like a JWT? or is it purely an expiry thing? I just discovered that when my auth fails the token is no longer a proper JWT - where as a new token right after `sso login` is, hence the errors do make sense. So sounds like something modified the cached token? And in at least one failure case I've basically only been running Terraform commands, so this remains relevant.

I have no idea how `aws-cli` continued to work despite this broken token, but checking `--debug` log on e.g. `aws s3 ls` it seems it does not contact SSO portal at all, where as the Rust aws-sdk also fails and by trace log it tried to contact `portal.sso.[region].amazonaws.com` and got error response..

**Comment by crw** [comment]
Thanks for this report, I'll notify the AWS provider team.

**Comment by MartinEmrich** [comment]
Time's up: After 8+ hours:

- as expected: Golang-SDK-using tools (terraform, kubectl) stopped working
- also: python-boto3 stops working ( `import boto3; client = boto3.client('sts') ; client.get_caller_identity();` )
- AWS CLI continues to work (`aws sts get-caller-identity`) 

But none of these three modified that SSO cache file, it is still from this morning, with that rather long almost-JTW-like accessToken.

**Comment by MartinEmrich** [comment]
Similar problems here. Today, I have to re-`aws sso login` quite often, and I always get the shorter type token, too. And even if neither the token nor the expireDate have expired, It stops working prematurely. Very strange.

Almost as if there was some randomness at play here (AWS running two services in a load balancer with different behaviour).

But again this affects kubectl, too, so it certainly is no terraform issue. Unless someone objects, I'll close this issue soon.

**Comment by MartinEmrich** [comment]
Very well, here it goes! Please share your result from that AWS support ticket here.

**Comment by aquarhead** [comment]
Just FYI, AWS said they have fixed the issue through a recent deployment. I have yet to see it again but I wasn't working on related things this week so far.
