### ISSUE TITLE
Attributes in `ignore_changes` should not cause deprecation warnings

### ISSUE THREAD

**Issue by tmatilai** [hashicorp/terraform#31944]
### Terraform Version

```shell
Terraform v1.3.1
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.37.0
```

### Terraform Configuration Files

```terraform
resource "okta_user" "example" {
  login = "foo@example.com"
  email = "foo@example.com"

  first_name = "Foo"
  last_name  = "Foo"

  lifecycle {
    ignore_changes = [admin_roles]
  }
}

resource "okta_user_admin_roles" "example" {
  user_id     = okta_user.example.id
  admin_roles = ["SUPER_ADMIN"]
}
```

### Debug Output

<details><summary>Plan output</summary>

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # okta_user.example will be created
  + resource "okta_user" "example" {
      + email                     = "foo@example.com"
      + expire_password_on_create = false
      + first_name                = "Foo"
      + id                        = (known after apply)
      + last_name                 = "Foo"
      + login                     = "foo@example.com"
      + raw_status                = (known after apply)
      + status                    = "ACTIVE"
    }

  # okta_user_admin_roles.example will be created
  + resource "okta_user_admin_roles" "example" {
      + admin_roles           = [
          + "SUPER_ADMIN",
        ]
      + disable_notifications = false
      + id                    = (known after apply)
      + user_id               = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
╷
│ Warning: Deprecated attribute
│
│   on okta_users.tf line 9, in resource "okta_user" "example":
│    9:     ignore_changes = [admin_roles]
│
│ The attribute "admin_roles" is deprecated. Refer to the provider documentation for details.
╵
```

</details>

### Expected Behavior

No warnings should be issued, as the attribute still exists and is updated in the resource and state. Removing the `ignore_changes` would cause next `apply` to set the attribute empty, in this example removing the admin role assignment done with another resource.

I guess it could be argued if an empty `set` is the best default value in the resource used in the example config. But changing the behaviour would be a breaking change, which seems funny for a deprecated attribute.

### Actual Behavior

A warning is printed.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

- #31576

**Comment by crw** [comment]
Thanks for this report!

**Comment by jbardin** [comment]
Hi @tmatilai,

Thanks for filing the issue. There may be a case for not warning on ignore changes, but it's not clear exactly what the `admin_roles` reference is doing in this configuration.

The `admin_roles` attribute is optional and not present in the configuration, so the provider should not be assigning a value at all. Also since it's deprecated, the provider should not be assigning any new values in the case of drift externally. Have you raised the issue with the provider directly?

Thanks!

**Comment by tmatilai** [comment]
Hi James,

Thanks for the answer. I guess you are right, it would make sense to ignore external drift in case of deprecated and non-configured attribute.

I haven't raised issues on the provider, but can do it. There are also other resources with similar behaviour.

Pinging @monde, as I know he's been active on the provider development. 🙂

**Comment by tmatilai** [comment]
Let's close this here as it should probably be fixed on the provider.
