### ISSUE TITLE
Unable to install terraform

### ISSUE THREAD

**Issue by ShadySQL** [hashicorp/terraform#31958]
### Terraform Version

```shell
None
```

### Terraform Configuration Files

N/A

### Debug Output

sudo sudo apt update && sudo apt install terraform
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease
Get:4 https://apt.releases.hashicorp.com focal InRelease [16.3 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Err:4 https://apt.releases.hashicorp.com focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DA418C88A3219F7B
Reading package lists... Done
W: GPG error: https://apt.releases.hashicorp.com focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DA418C88A3219F7B
E: The repository 'https://apt.releases.hashicorp.com focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Expected Behavior

Install of terraform

### Actual Behavior

Tried to install Terraform following this guide:

https://www.terraform.io/downloads

### Steps to Reproduce

N/A

**Comment by apparentlymart** [comment]
Hi @ShadySQL! Sorry this didn't work out.

I'm assuming from your mention of `apt` that the specific instructions you followed were the package manager instructions for "Ubuntu/Debian", which at the time of writing this are as follows:

```shell
$ wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
$ echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
$ sudo apt update && sudo apt install terraform
```

The last of those statements matches the one you mentioned in your report.

The _first_ of those statements is the one that's supposed to install the public key you'll need to verify the signatures in this APT repository. Can you also share what command you ran for that step, and what output you saw in your terminal (if any)?

Thanks!

**Comment by cbatson** [comment]
FWIW this occurred for me while installing in a Docker image, because `wget` was not installed.
