### ISSUE TITLE
Terraform Registry 404

### ISSUE THREAD

**Issue by sami-oneonetwo** [hashicorp/terraform#31961]
### Terraform Version

```shell
$ terraform version
Terraform v1.2.8
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.3.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

.

### Debug Output

It looks like the Terraform registry may be down currently. 

Running a terraform apply failed on a specific action trying to use a certain provider:
```
Error: Could not connect to server: dial tcp 10.10.5.87:3306: connect: connection timed out

  with provider["[registry.terraform.io/petoju/mysql](http://registry.terraform.io/petoju/mysql)"],
  on _providers.tf line 19, in provider "mysql":
  19: provider "mysql" {

Releasing state lock. This may take a few moments...
```

I can see the documentation for this provider here: https://registry.terraform.io/providers/petoju/mysql/latest/docs

Though I'm presented with a 404 when visiting the registry URL: https://registry.terraform.io/petoju/mysql
<img width="1168" alt="Screen Shot 2022-10-07 at 11 37 40 am" src="https://user-images.githubusercontent.com/97210326/194442409-7eb60f35-79e0-4a71-a5c1-b9704c583392.png">

This looks to be happening for other providers too (https://registry.terraform.io/bangau1/mysql for example) so this makes me think there's an issue with the registry. 

### Expected Behavior

The `terraform apply` command should utilise the provider and build the resources.

### Actual Behavior

The `terraform apply` command fails stating the connection to the server has timed out.
```
Error: Could not connect to server: dial tcp 10.10.5.87:3306: connect: connection timed out
```

### Steps to Reproduce

`terraform apply`

### References

Related to: https://github.com/hashicorp/terraform/issues/25756

**Comment by crw** [comment]
Thanks for the report. I've let the registry team know.

**Comment by sami-oneonetwo** [comment]
I've done some additional testing and it looks like the issue was related to a Bitbucket runner I had been using that had some bad ACL configurations. 

This was a miss-read on my behalf.
