### ISSUE TITLE
Automatic backend variables

### ISSUE THREAD

**Issue by raven-wing** [hashicorp/terraform#31971]
### Terraform Version

```shell
1.1.9
```

### Use Cases

`terraform init` needs to have backend provided either inline or via partial configuration. Yet to provide partial configuration you have to use flag -backend-config or key=value format.
It could be simplified.

### Attempted Solutions

`terraform init -backend-config backend.tfbackend`

### Proposal

Instead of providing files manually terraform init could take files as .auto.tfbackend the same way as terraform apply takes .auto.tfvars.

**Comment by apparentlymart** [comment]
Hi @raven-wing! Thanks for sharing this feature request.

Terraform Cloud internally achieves a similar effect to this by generating an [override file](https://www.terraform.io/language/files/override) which contains a `backend` block containing the backend settings. Terraform automatically reads override files when loading the configuration, so no additional arguments are required. The override file in this case contains only a `terraform` block with a `backend "remote"` or `cloud` block inside it, so [the rules for merging `terraform` blocks](https://www.terraform.io/language/files/override#merging-terraform-blocks) describe how Terraform interprets this.

Do you think a similar strategy would work for your situation too?

**Comment by raven-wing** [comment]
Indeed, it works. Thank you @apparentlymart.
