### ISSUE TITLE
Terraform destroy fails and complains about module outputs

### ISSUE THREAD

**Issue by nikita-golovin** [hashicorp/terraform#31975]
### Terraform Version

```shell
Terraform v1.3.2 

P.S. also reproducible on v1.3.1, but works on v1.2.3
```

### Terraform Configuration Files

I could not make a small reproduction scenario, but here is terraform destroy output and state file (rerun after state has no more resources in it): https://gist.github.com/nikita-golovin/c9a48bae6066d830213405f532ab4325 

### Debug Output

https://gist.github.com/nikita-golovin/c9a48bae6066d830213405f532ab4325 

### Expected Behavior

Terraform destroys infrastructure and DOES NOT validate module outputs 

### Actual Behavior

Terraform destroys infrastructure, BUT DOES validates module outputs and returns error 

### Steps to Reproduce

terraform destroy

**Comment by kirikors** [comment]
Seems like the fix from #32051 didn't solve the problem, it's still failing with Terraform 1.3.4. Opened a new issue #32185
