### ISSUE TITLE
openstack_lb_pool_v1, multiple members

### ISSUE THREAD

**Issue by lesaux** [hashicorp/terraform#3197]
Hello,
I am wondering how to dynamically assign multiple members to an openstack_lb_pool_v1. I know I can just repeat the member block as many times as I need, when the number of members isn't dynamic. In my case, openstack_compute_instance_v2 uses "count", so how can I do the same for the lbaas members?

I wanted to do the following but it doesn't work.

```
member {
    count = "${var.instance_count}"
    address = "${element(openstack_compute_instance_v2.test-server.*.access_ip_v4, count.index)}"
    port = 80
    admin_state_up = "true"
  }
```

Is there another way of doing this?
Thanks!

**Comment by pdakhane** [comment]
Did you figure this out? i am in the same boat, trying to figure this out.

**Comment by lesaux** [comment]
@pdakhane: Hello no I have not figured out a way of automating the LB members yet. For now I repeat the member stanza as many times as I need it.

**Comment by pdakhane** [comment]
Thank you!

regards

**Comment by jtopjian** [comment]
I was actually just replying to the post on the TF mailing list when I saw this :smile: 

Indeed what you guys are trying to do makes perfect sense, but I don't think it will work with the current `openstack_lb_pool_v1` resource. I think the best option is to create an `openstack_lb_pool_member_v1` resource that links to a parent pool resource. This way you can use `count` to correctly collect all members.

I'm not very familiar with the Neutron API (more Nova/Compute), so the above is only an idea and that's assuming that the Neutron API allows it.

If I get some time, I'll look into making such a resource. :smile:

**Comment by devth** [comment]
@jtopjian don't quite understand your suggestion regarding `openstack_lb_pool_member_v1`. Could you show an example please?

**Comment by jtopjian** [comment]
Sure. I should preface this by saying I have not used LBaaS. This idea is based on working with the other OpenStack components.

The example given in the docs is:

```ruby
resource "openstack_lb_pool_v1" "pool_1" {
  name = "tf_test_lb_pool"
  protocol = "HTTP"
  subnet_id = "12345"
  lb_method = "ROUND_ROBIN"
  monitor_ids = ["67890"]
  member {
    address = "192.168.0.1"
    port = 80
    admin_state_up = "true"
  }
}
```

The problem, if I understand correctly, is the `member` block. There's no way to dynamically create multiple member blocks inside the `openstack_lb_pool_v1` resource. They must all be statically defined.

To make it possible for a dynamic amount, or even being able to just programmatically define, the members, I think a new resource needs to be created: `openstack_lb_member_v1`. The `member` block of `openstack_lb_pool_v1` would stay as-is for backwards compatibility and for reporting (via `terraform show`).

An example of `openstack_lb_member_v1` would look like:

```ruby
resource "openstack_lb_member_v1" "members" {
  count = "${var.count}"
  name = "${format("web-%03d", count.index+1)}"
  pool_id = "${openstack_lb_pool_v1.pool_1.id}"
  address = "${element(openstack_compute_instance_v2.web.*.access_ip_v4, count.index)}"
  port = 80
  admin_state_up = "true"
}
```

That's all just a rough sketch.

**Comment by devth** [comment]
@jtopjian thanks, makes sense. I misunderstood your original post thinking it was something that was already supported. Great suggestion.

**Comment by jtopjian** [comment]
Hi all,

I've begun working on this and you can see the first attempt at #4359. Let me know if you're able to test it  and if you have any feedback.
