### ISSUE TITLE
Passing cloudformation subnetid variables in terraform

### ISSUE THREAD

**Issue by prathmesh-rajmane** [hashicorp/terraform#31987]
### Terraform Version

```shell
Terraform v1.2.8
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.3.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

I was trying to pass the cloudfromation subnet id string into terraform variable
But problem is subnet id variable are in list format like private-subnets-cidr  =["10.0.8.128/27","10.0.8.96/27"] 
and I want to specify subnetids1 = var.private-subnets-cidr[0] & subnetids2=var.private-subnets-cidr[1]
but it is throwing errors ->  Rollback requested by user." "MediaLive must be able to obtain information about the allocation IDs. The trusted entity that you have associated with this channel needs to include the describe-addresses action. (Service: AWSMediaLive; Status Code: 400; Error Code: BadRequestException; Request ID: e7a3cdc6-96cd-4c23-8bc8-1253af50ee26; Proxy: null)"]

main.tf file ->
resource "aws_cloudformation_stack" "medialivechannel" {
  name = var.medialive-stack_name
  parameters = {
    Publicaddressallocationids = var.public-cidr
    Subnetids1 = var.private-subnets-cidr[0]
    Subnetids2 = var.private-subnets-cidr[1]
    Securitygroupids = var.apes-sg-name
}

is there any way to specify the list into single strings?

### Attempted Solutions

I tried out Subnetids1 = var.private-subnets-cidr[0] 
but it gives same error 
 Rollback requested by user." "MediaLive must be able to obtain information about the allocation IDs. The trusted entity that you have associated with this channel needs to include the describe-addresses action. (Service: AWSMediaLive; Status Code: 400; Error Code: BadRequestException; Request ID: e7a3cdc6-96cd-4c23-8bc8-1253af50ee26; Proxy: null)"]

![image](https://user-images.githubusercontent.com/109971130/195139365-c76691ff-8377-4959-bea4-e4288df2648d.png)

### References

https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-medialive-channel-vpcoutputsettings.html

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
