### ISSUE TITLE
tomap does not admit tolist inside.

### ISSUE THREAD

**Issue by hoses-h** [hashicorp/terraform#31985]
### Terraform Version

```shell
1.0.5
```

### Terraform Configuration Files

```terraform
tolist([
          tomap({
                object_id                          = "xxxxx"
                secret_permissions          = tolist(["Get","List"])
            }),
          tomap({
                object_id                          = "xxxxxx"
                secret_permissions          = tolist(["Get","List"])
            })
})
```

### Debug Output

Invalid value for "v" parameter: cannot convert object to map of any single type.

### Expected Behavior

tomap function should have accepted the creation of a list parameter using the function tolist.

### Actual Behavior

The plan errored.

### Steps to Reproduce

Create a local variable for Azure key vault and assign the previous default parameters.

**Comment by hoses-h** [comment]
Maybe you are right, but the point is that I can include tomap functions inside a tolist function but not tolist functions inside a tomap function.

**Comment by hoses-h** [comment]
> Hi @hoses-h,
> 
> A `map` type has a single element type (as do the `list` and `set` collection types). You cannot convert the given object to a map, because `object_id` and `secret_permissions` cannot be converted to a single common type.
> 
> We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
> 
> Thanks!

Maybe you are right, but the point is that I can include tomap functions inside a tolist function but not tolist functions inside a tomap function.

**Comment by alisdair** [comment]
> the point is that I can include tomap functions inside a tolist function but not tolist functions inside a tomap function.

This is not true. As described in our comments above, a `map` must have the same type for all of its values. You can call `tolist` inside `tomap` so long as the value passed to `tomap` can be converted to a map. For example:

```hcl
tomap({ a = tolist(["a", "b"]), b = tolist(["c"]) })
```

**Comment by hoses-h** [comment]
> > the point is that I can include tomap functions inside a tolist function but not tolist functions inside a tomap function.
> 
> This is not true. As described in our comments above, a `map` must have the same type for all of its values. You can call `tolist` inside `tomap` so long as the value passed to `tomap` can be converted to a map. For example:
> 
> ```terraform
> tomap({ a = tolist(["a", "b"]), b = tolist(["c"]) })
> ```

Ok, I think the sentence "This cannot be converted to a map type, as string and list(string) are incompatible" summarizes my doubts.

Thank you for your replies.
