### ISSUE TITLE
Make count and for_each stable

### ISSUE THREAD

**Issue by eau-de-la-seine** [hashicorp/terraform#31982]
### Terraform Version

```shell
v1.0.11
```

### Terraform Configuration Files

```terraform
resource "aws_iam_policy" "lambda_permissions" {
  count       = length(local.statements) > 0 ? 1 : 0
  name        = "iam_policy_${var.lambda_configuration.name}"
  path        = "/"
  description = "IAM policy for ${var.lambda_configuration.name}"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": ${jsonencode(local.statements)}
}
EOF
}

resource "aws_iam_role_policy_attachment" "lambda_permissions" {
  count      = length(local.statements) > 0 ? 1 : 0
  role       = aws_iam_role.iam_role_lambda.name
  policy_arn = aws_iam_policy.lambda_permissions[count.index].arn
}
```

### Debug Output

```
│ Error: Invalid count argument
│ 
│   on lambda-module/main.tf line 139, in resource "aws_iam_policy" "lambda_permissions":
│  139:   count       = length(local.statements) > 0 ? 1 : 0
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be
│ created. To work around this, use the -target argument to first apply only
│ the resources that the count depends on.
```

### Expected Behavior

The error message in *Debug Output* should not happen when you use `count` or `for_each`

### Actual Behavior

When `count` or `for_each` are used in a resource declared in a module, and the argument given to `count` or `for_each` depends on input variable, it may work at the beginning and start to not working anymore at some point! That makes Terraform modules that contain  `count` or `for_each` totally unstable

I have noticed that it works at the beginning because the resources are already created (first TF plan+apply), so we just give their ARN to the module (second TF plan+apply)... And things start to become very unstable when we create the resource **AND** give the ARN to the module during the same TF plan, unstable at a point the state has changed and always reject when Terraform sees `count` or `for_each` in the module even if we are not referencing a new resource

This seems to be [a known issue](https://discuss.hashicorp.com/t/strange-error-during-plan/24267):
> The general answer is that you should usually derive count only from values you’ve defined statically in your configuration, and not from values that are exported by providers after creating objects

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

I am sure there's a technical reason or limitation why this error message has been created:
```
The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends on.
```

But Terraform should improve the `count` and `for_each` features, maybe improve the way the Terraform's IR is generated with "theoretical created resources" when these features are used. Otherwise just prevent the use of these features by adding "_You cannot call a module that contains resources with `count` and `for_each`_" error

As for the actual fix: I have just removed the `count` / `for_each` feature, I was able to do that because the `local.statements` of all my lambdas always contain at least 1 statement. So today I am able to create a new resource AND reference it in my module at the first plan+apply without any problem. But if some of my co-workers create a new lambda without any permission (= no statement means empty `local.statements`), AWS will reject the generated policy without any statement.

I'm sure that's not a specific use case and `count` + `for_each` need to be improved

**Comment by jbardin** [comment]
Hi @eau-de-la-seine,

Thanks for filing the issue. `count` and `for_each` can only as stable as the expression you provide. The plan is showing that the expression evaluated to an unknown value, which cannot be used for `count` or `for_each`, because Terraform must be able to create a plan showing which instances it intends to create, update or destroy.

In your example, there must be an input to the `local.statements` value which has become unknown, which in an intermediate plan means a previously known value is being recomputed, most likely due to resource replacement.

Since this does not represent a bug in Terraform, I'm going to close the issue. We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
