### ISSUE TITLE
Missing option when creating AWS DMS Endpoint through Terraform and docdb is selected as source

### ISSUE THREAD

**Issue by anacronxinetd** [hashicorp/terraform#31980]
### Terraform Version

```shell
Hi,

When creating an AWS DMS Endpoint through the console, the option is displayed to choose the Metadata mode for the source. The values for this option can either be set to document or table. This determines how data is read from the source and migrated to the target. The following doc does not include an option to specify the Metadata mode for a source docdb endpoint: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint 

The following doc provides more information on the option: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.DocumentDB.html

Using the options mentioned in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint for mongodb as a source also does not apply to when using docdb as a source. Does anyone know of a workaround or if the option can be added?
```

### Use Cases

Creating a AWS DMS source endpoint for DocumentDB

### Attempted Solutions

No solution found

### Proposal

Add support for option

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
