### ISSUE TITLE
Connection for remote-exec provisioner timing out at 10 minutes

### ISSUE THREAD

**Issue by ldipaolaIT** [hashicorp/terraform#31981]
### Terraform Version

```shell
0.11.15
```

### Terraform Configuration Files

resource "null_resource" "provision-bash" {
  triggers {
    instance_id = "${openstack_compute_instance_v2.bash.id}"
  }

  depends_on = ["openstack_compute_floatingip_associate_v2.attach-bash-fip"]

  provisioner "remote-exec" {
    inline = [
      "uptime",
    ]
  }

  connection {
    type        = "ssh"
    private_key = "${file("${var.ssh_private_key}")}"
    user        = "${var.ssh_user}"
    timeout     = "${var.ssh_connection_timeout}"
    host        = "${openstack_compute_floatingip_v2.bash-fip.address}"
  }
}

Variable definition for ssh_connection_timeout:

variable "ssh_connection_timeout" {
  type        = "string"
  default     = "15m"
  description = "The timeout to wait for the ssh connection to become available. Should be provided as a string like 30s or 10m."
}

### Debug Output

TestImageID/terraform_apply 2022-10-10T21:04:35+02:00 logger.go:66: null_resource.provision-bash: Still creating... (9m20s elapsed)
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: null_resource.provision-bash (remote-exec): Connecting to remote host via SSH...
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: null_resource.provision-bash (remote-exec):   Host: XX.XX.XX.XX
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: null_resource.provision-bash (remote-exec):   User: cloud-user
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: null_resource.provision-bash (remote-exec):   Password: false
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: null_resource.provision-bash (remote-exec):   Private key: true
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: null_resource.provision-bash (remote-exec):   Certificate: false
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: null_resource.provision-bash (remote-exec):   SSH Agent: false
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: null_resource.provision-bash (remote-exec):   Checking Host Key: false
TestImageID/terraform_apply 2022-10-10T21:04:36+02:00 logger.go:66: 2022-10-10T21:04:36.575+0200 [DEBUG] plugin.terraform-0.11.15: remote-exec-provisioner (internal) 2022/10/10 21:04:36 [DEBUG] Connecting to XX.XX.XX.XX:22 for SSH
TestImageID/terraform_apply 2022-10-10T21:04:45+02:00 logger.go:66: null_resource.provision-bash: Still creating... (9m30s elapsed)
panic: test timed out after 10m0s

### Expected Behavior

The remote-exec provisioner should timeout at 15 minutes, not at 10 minutes based on the connection timeout value.

### Actual Behavior

I need to extend to more than 10 minutes the timeout value for the remote-exec connection. But looks like it does not support more than 10 minutes(?)

### Steps to Reproduce

Set a remote-exec provisioner with ssh type connection and set the timeout to more than 10 minutes (the instance should not be ready before 10 minutes, could be quite a quite difficult to reproduce).

**Comment by jbardin** [comment]
Hi @ldipaolaIT,

Terraform v0.11 is quite old and no longer supported, and no further development is going to be done on that branch. If the problem persists in a current release of Terraform, please file a new issue with the necessary information to reproduce the issue.

If you have more questions, feel free to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
