### ISSUE TITLE
Data Source: azurerm_shared_image_version outputs random version ID

### ISSUE THREAD

**Issue by mvijaybhargava** [hashicorp/terraform#31996]
### Terraform Version

```shell
1.0.5
```

### Terraform Configuration Files

```terraform
...terraform config...
```
variable "shared_image" {
  default = {
    gallery_name           = "XXXXXXXXX"
    gallery_resource_group = "XXXXXXXXX"
    image_name             = "XXXXXXXXX"
    "version"              = "latest"
  }
}

data "azurerm_shared_image_version" "shared_image" {
  name                = var.shared_image.version
  resource_group_name = var.shared_image.gallery_resource_group
  gallery_name = var.shared_image.gallery_name
  image_name   = var.shared_image.image_name
}

resource "azurerm_linux_virtual_machine" "linux_vm" {
...
source_image_id                 = data.azurerm_shared_image_version.shared_image.id
... (other parameters)
}

### Debug Output

Will obtain the debug info if necessary

### Expected Behavior

ID of the latest version of the specified image should be used for creating the VM.

### Actual Behavior

ID of the latest version of the specified image should be used, but some random version of the image is being used for creating the vm.

Below is the output of terraform plan 
 + resource "azurerm_windows_virtual_machine" "windows_vm" {
...
+ source_image_id            = "/subscriptions/XXXXXXXX/resourceGroups/XXXXXXXXXX/providers/Microsoft.Compute/galleries/XXXXXXXXXX/images/XXXXXXXXXX/versions/1.0.9"
...
}

### Steps to Reproduce

1. terraform init
2. terraform plan

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
