### ISSUE TITLE
Unable to create google_dataproc_workflow_template without job

### ISSUE THREAD

**Issue by deepjy** [hashicorp/terraform#32005]
### Terraform Version

```shell
1.1.6
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

```
│ Error: Insufficient jobs blocks
│
│   on dataproc-workflow.tf line 2, in resource "google_dataproc_workflow_template" "template":
│    2: resource "google_dataproc_workflow_template" "template" {
│
│ At least 1 "jobs" blocks are required.
```

### Expected Behavior

In GCP, the dataproc workflow templates can be created without attaching the jobs. Later the jobs can be attached and template can be instantiated. 
Gcloud cli command to create a workflow template without job:
```
gcloud dataproc workflow-templates create test-workflow-template --region us-central1
```

But in terraform [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_workflow_template), the dataproc-workflow-template requires a mandatory job block. Whereas the workflow templates can be created without jobs using cli and jobs can be attached later to the templates

```
 jobs {
    step_id = "someJob"
    spark_job {
      main_class = "SomeClass"
    }
  }
```
 

The following arguments are supported:
[jobs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_workflow_template#jobs) - (Required) Required. The Directed Acyclic Graph of Jobs to submit.

### Actual Behavior

Attaching a job is mandatory in Terraform while creating dataproc_workflow_template resource.

```
Error: Insufficient jobs blocks
on dataproc-workflow.tf line 2, in resource "google_dataproc_workflow_template" "template":
resource "google_dataproc_workflow_template" "template" {
At least 1 "jobs" blocks are required.
```

### Steps to Reproduce

Create a workflow template resource without job attached to it as below:

```

resource "google_dataproc_workflow_template" "template" {
  name = "test-tfe-example1"
  location = "us-central1"
  project  = "test-project"
  placement {
    managed_cluster {
      cluster_name = "test-bucket"
      config {
          staging_bucket = "test-bucket-staging"
          temp_bucket    = "test-bucket-temp"
        gce_cluster_config {
          internal_ip_only       = true
          zone = "us-central1-a"
          tags = ["foo", "bar"]
        }
        endpoint_config {
      enable_http_port_access = "false"
    }
      }
    }
  } 
}

```

Run the following terraform commands to reproduce
```
terraform init
terraform validate
```

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dataproc_workflow_template#jobs

**Comment by apparentlymart** [comment]
Hi @deepjy!

It seems that you are describing a behaviour of the Google Cloud Platform provider, rather than of Terraform Core.

Providers are each developed in their own repositories with their own issue trackers, so you will need to report this problem in the provider repository in order for the provider developers to find it and respond to it. You can find the GitHub URL for each provider in the Terraform Registry.

Thanks!

**Comment by deepjy** [comment]
Thank you, created a new bug in Google Cloud Platform Provider repo.
https://github.com/hashicorp/terraform-provider-google/issues/12783
