### ISSUE TITLE
Make `init` concurrency safe when using a provider cache

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform#32028]
### Terraform Version

```shell
1.3.2
```

### Use Cases

Anyone that has a CI job that tries to `terraform init` multiple root modules at the same time on a worker that would end up with a shared plugin cache (regardless of if that is the [default plugin cache](https://www.terraform.io/cli/config/config-file#implied-local-mirror-directories) or a [user specified plugin cache](https://www.terraform.io/cli/config/config-file#provider-plugin-cache)). 

The error looks like:

```
╷
│ Error: Required plugins are not installed
│
│ The installed provider plugins are not consistent with the packages
│ selected in the dependency lock file:
│   - registry.terraform.io/hashicorp/google: the cached package for registry.terraform.io/hashicorp/google 4.40.0 (in .terraform/providers) does not match any of the checksums recorded in the dependency lock file
│
│ Terraform uses external plugins to integrate with a variety of different
│ infrastructure services. You must install the required plugins before
│ running Terraform operations.
```

### Attempted Solutions

https://github.com/hashicorp/terraform/issues/25849 contains a lot of history on this, right now the only way we have found that really works is to not parallelize the init part by using a mutex.

### Proposal

Make `terraform init` concurrency safe or have some kind of lock/mutex on the Terraform core side to prevent thundering herd scenarios.

### References

- https://github.com/hashicorp/terraform/issues/25849

**Comment by jbardin** [comment]
Thanks @joe-a-t,

This looks like the same request as the existing issue #31964.
