### ISSUE TITLE
Terraform cloud private registry module stuck on publishing state

### ISSUE THREAD

**Issue by somanianshul** [hashicorp/terraform#32029]
### Terraform Version

```shell
1.0.0
```

### Terraform Configuration Files

publishing the module via terraform cloud UI. Other modules publish fine on same VCS connection

### Debug Output

registry module stuck on publishing state/Module ingress is pending.

### Expected Behavior

module is published with all version available

### Actual Behavior

module stuck at publishing state. first version get piblished but reamining stays stuck at publishing state

### Steps to Reproduce

go to ui and publish a module from registry page

**Comment by crw** [comment]
Hi @somanianshul, thanks for this report. Given that this is an issue with Terraform Cloud, I recommend filing a report through the commercial channel. Please email [tf-cloud@hashicorp.support](mailto:tf-cloud@hashicorp.support) or [open a new request](https://support.hashicorp.com/hc/en-us/requests/new). Thanks again!

**Comment by crw** [comment]
I am going to close this issue as this bug cannot be solved by the Core or CLI Terraform team. Please use the resources indicated above to submit this issue. Thanks!
