### ISSUE TITLE
Destroying non-existent resources should not produce changes to outputs

### ISSUE THREAD

**Issue by Nuru** [hashicorp/terraform#32026]
### Terraform Version

```shell
Terraform v1.3.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.1
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    null = {
      source = "hashicorp/null"
      version = "3.1.1"
    }
  }
}

provider "null" { }

data "null_data_source" "example" { }

output "example" {
  value = data.null_data_source.example.random
}

```

### Debug Output

[terraform-debug.log](https://github.com/hashicorp/terraform/files/9793221/terraform-debug.log)

### Expected Behavior

```
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

```
Changes to Outputs:
  - example = "341280706399446186" -> null
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -destroy`

### Additional Context

Deleting a non-existent resource should not result in any sort of configuration change being reported. The old state is wrong, and indicating a configuration change can interfere with smooth operation of automated systems.

### References

-`none`

**Comment by jbardin** [comment]
Hi @Nuru,

The example here is not planning to destroy individual resources, the `-destroy` flag (or the `destroy` command) means destroy _everything_, including outputs. Since outputs are only data stored in the state, the change to `null` is the equivalent of destroying that output.

Thanks

**Comment by Nuru** [comment]
@jbardin 

> The example here is not planning to destroy individual resources, the `-destroy` flag (or the `destroy` command) means destroy _everything_, including outputs. Since outputs are only data stored in the state, the change to `null` is the equivalent of destroying that output.

My point is that there was no output to destroy, since there was no data in the state. If you had run `terraform output` prior to this command you would have gotten an error that there was nothing in the state. So you should not get a change in outputs by running `terraform destroy`.
