### ISSUE TITLE
AWS ALB stickiness policy lb name too long

### ISSUE THREAD

**Issue by polly-qantas** [hashicorp/terraform#32030]
### Terraform Version

```shell
Terraform v0.12.31
```

### Terraform Configuration Files

```terraform
resource "aws_lb_cookie_stickiness_policy" "this" {
  count                    = var.lb_sticky_session ? 1 : 0
  name                     = local.name
  load_balancer      = aws_lb.this[0].id
  lb_port                  = var.sticky_session_port
  cookie_expiration_period = 600
}
```

### Debug Output

https://gist.github.com/polly-qantas/ef44d8f471639fa3e1e063c43582c534

### Expected Behavior

It should attach a cookie stickiness policy with a specified LB id

### Actual Behavior

Response I'm getting

`Error: Error creating LBCookieStickinessPolicy: ValidationError: LoadBalancer name cannot be longer than 32 characters
        status code: 400, request id: `

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Additional Context

LoadBalancer arn (or id) most likely will be more than 32 characters. In my case it's something like arn:aws:elasticloadbalancing:region-name:0000000000:loadbalancer/app/server-example-name/1498f48f333aacc5

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
