### ISSUE TITLE
HTTPS in Consul remote config

### ISSUE THREAD

**Issue by TimJones** [hashicorp/terraform#3203]
I want to use a Consul backend to store the tfstate, but the `address` configuration rejects a `https://` prefix:

    $ terraform remote config -backend=consul -backend-config="path=terraform" -backend-config="address=https://<PUBLIC_IP>:8500"
    Remote state management enabled
    Error while performing the initial pull. The error message is shown
    below. Note that remote state was properly configured, so you don't
    need to reconfigure. You can now use `push` and `pull` directly.
    
    Error reloading remote state: Get http://https://<PUBLIC_IP>:8500/v1/kv/terraform: dial tcp: too many colons in address https://185.24.5.61:8500

Is there a switch or option I'm missing from the docs?

ADDENDUM: We use self-signed certificates, so a way to supply a CA or not verify the cert would also be needed.

**Comment by apparentlymart** [comment]
From reading [the code](https://github.com/hashicorp/terraform/blob/master/state/remote/consul.go#L23) it looks like there's a separate ``scheme`` argument that can be used for this, if you set it to "https".

I'm not too sure why this state backend doesn't just take a URL as a single argument, rather than assembling it from two separate arguments, but that seems to be how it works today.

It doesn't seem to provide a way to customize the certificate validation behavior, though.

**Comment by TimJones** [comment]
Thanks! Adding `-backend-config="scheme=https"` gets me closer! But of course, since we have self.signed certs as I mentioned, I get a cert verification issue. I tried again using an IP address in place of the domain name in the `address`, and it gives me `cannot validate certificate for 185.24.5.61 because it doesn't contain any IP SANs`. When I have a moment to recreate the cert with another subjectAltName I'll update the issue.

Thanks again.

**Comment by apparentlymart** [comment]
I dug a bit deeper into the code and found that ultimately the Go Consul API client is instantiating a Go HTTP client with a default [Transport](http://godoc.org/net/http#Transport) with a default TLS client config that, according to the docs, will use "the host's root CA set" for verification.

The way Go finds root certs varies by OS. Within [the x509 package source](https://github.com/golang/go/tree/29eb7d18ed71c057bbdb69d85953a32252f0ea73/src/crypto/x509) you can find all the different implementations in files named ``root_osname.go``.

So probably the simplest answer for you in the short term is to figure out where Go is -- and thus Terraform is, by proxy -- looking for the list of trusted CA certs and add your cert in there, assuming your self-signed cert was created with the capability of representing a CA.

**Comment by phinze** [comment]
I have walked this same path myself, and I can confirm that @apparentlymart's recommendation is correct. :+1:
