### ISSUE TITLE
openstack_compute_instance_v2  block_device - boot from volume

### ISSUE THREAD

**Issue by lesaux** [hashicorp/terraform#3206]
Hello, I am not understanding how this works and would like some clarifications. (I am using my private openstack cluster "Juno" and not rackspace or similar). Basically I would like to use a volume as a rootfs in an instance.

First, it seems to me that if I was to specify a block_device block in my instance resource, the image_id or image_name should not be required.

From the source_type and destination_type parameters, I am understanding that this should create a volume, but it is not the case.

```
  block_device {
    uuid = "${var.image_id}"
    source_type = "snapshot"
    volume_size = 8
    boot_index = 0
    destination_type = "volume"
  }
```

It seems that the block_device stanza never does anything.

Below is the instance information for an instance created with the "boot from image (creates new volume)" option in the horizon interface. Notice how the image parameter is "Attempt to boot from volume - no image supplied", and there is effectively one volume attached, which was used to boot the instance.
```
+--------------------------------------+----------------------------------------------------------+
| Property                             | Value                                                    |
+--------------------------------------+----------------------------------------------------------+
| OS-DCF:diskConfig                    | AUTO                                                     |
| OS-EXT-AZ:availability_zone          | nova                                                     |
| OS-EXT-SRV-ATTR:host                 | node-69.domain.tld                                       |
| OS-EXT-SRV-ATTR:hypervisor_hostname  | node-69.domain.tld                                       |
| OS-EXT-SRV-ATTR:instance_name        | instance-00000048                                        |
| OS-EXT-STS:power_state               | 1                                                        |
| OS-EXT-STS:task_state                | -                                                        |
| OS-EXT-STS:vm_state                  | active                                                   |
| OS-SRV-USG:launched_at               | 2015-09-10T15:01:10.000000                               |
| OS-SRV-USG:terminated_at             | -                                                        |
| accessIPv4                           |                                                          |
| accessIPv6                           |                                                          |
| config_drive                         |                                                          |
| created                              | 2015-09-10T14:58:14Z                                     |
| flavor                               | t2.small (b9b9cd94-4cfd-41e9-8863-b9ffeab7c9d4)          |
| hostId                               | e64e13e2745fe1bad894eda65b245378b9c6a3f1f8364b8cbe54201f |
| id                                   | 0edf517b-5ada-4242-b933-5e18fda0cfdb                     |
| image                                | Attempt to boot from volume - no image supplied          |
| key_name                             | test                                                     |
| metadata                             | {}                                                       |
| name                                 | test                                                     |
| net04 network                        | 192.168.111.17                                           |
| os-extended-volumes:volumes_attached | [{"id": "d3949ea6-33c4-42f0-b8fa-26e829949606"}]         |
| progress                             | 0                                                        |
| security_groups                      | default                                                  |
| status                               | ACTIVE                                                   |
| tenant_id                            | c7ca4adfa34342519ba20424d7b18ce3                         |
| updated                              | 2015-09-10T15:01:11Z                                     |
| user_id                              | ba276e7f36f34d2b8830f0e97fd71e93                         |
+--------------------------------------+----------------------------------------------------------+
```

**Comment by jtopjian** [comment]
@lesaux Nice catch. You were absolutely right that the `block_device` stanza wasn't doing anything. I've fixed this in #3225. If you're able to, try compiling Terraform from source with the patch and see if everything now works on your end. If you're unable to, I'm pretty confident it's fixed since everything checks out in a Devstack environment. 

Regarding the requirement to still have to specify an Image ID even though you're already specifying it in the `block_device` section: I agree that this should be removed. However, I don't want to pile on too many changes at once. How about we confirm `block_device` now works and then I'd be happy to make the Image ID changes?

**Comment by jtopjian** [comment]
Also, the other reason to hold off on making changes to the Image parts is because I have #3202 in queue. The required changes will conflict with that PR.

Unless I'm mistaken, specifying the image name/id, even though you're booting from a volume, won't cause any issues?

**Comment by jtopjian** [comment]
I began writing a fix for the part about having to specify an image and ran into a bug with Gophercloud: https://github.com/rackspace/gophercloud/pull/481

I'll continue once that's resolved.

**Comment by lesaux** [comment]
@jtopjian Thanks a lot for this work. I will try #3225 shortly and give you my results.
Having to specify the image_id outside of the block_device is really not a problem - It's just that it confused me as I was trying to understand how the block_device part worked.

I think I found another issue with the attached volumes. It seems they're attached in a random order (I guess depending on how quick the api responds for the volume creation request) which makes it hard to track the device name they will use. I wasn't able to find a way to use the attachement attribute yet. I will investigate this one further before creating a separate issue though.

Thanks again!

**Comment by jtopjian** [comment]
@lesaux It's most likely Terraform that's causing the random ordering. If you could, open a new issue with any example output or configuration.

**Comment by jfchevrette** [comment]
+1 I'm stuck on the same issue where I need to specify an image name or id even though I am booting from volume

**Comment by waterfinger** [comment]
+1 Thanks for fixing this :) i'm going to try to deploy Terraform from source :)
