### ISSUE TITLE
Support Ubuntu 22.10 (Kinetic Kudu) in Terraform packages in the HashiCorp apt repository 

### ISSUE THREAD

**Issue by xorinzor** [hashicorp/terraform#32061]
### Terraform Version

```shell
N/A
```

### Terraform Configuration Files

N/A

### Debug Output

```
$ sudo apt update
Get:1 http://nl.archive.ubuntu.com/ubuntu kinetic InRelease [267 kB]
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                                     
Hit:3 http://nl.archive.ubuntu.com/ubuntu kinetic-updates InRelease                                                                                                                                               
Hit:4 https://packages.microsoft.com/repos/ms-teams stable InRelease                                                                                                                        
Hit:5 http://nl.archive.ubuntu.com/ubuntu kinetic-backports InRelease                                                                                                                       
Hit:6 http://security.ubuntu.com/ubuntu kinetic-security InRelease                                                                                                    
Ign:7 https://apt.releases.hashicorp.com kinetic InRelease
Err:8 https://apt.releases.hashicorp.com kinetic Release
  404  Not Found [IP: 52.222.214.72 443]
Reading package lists... Done
E: The repository 'https://apt.releases.hashicorp.com kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Expected Behavior

The repository shouldn't have returned a 404

### Actual Behavior

It returned a 404

### Steps to Reproduce

1. Install Ubuntu 22.10
2. Follow the steps at https://learn.hashicorp.com/tutorials/terraform/install-cli

**Comment by apparentlymart** [comment]
Hi @xorinzor! Thanks for reporting this.

"kinetic" isn't one of [the currently-supported distributions](https://developer.hashicorp.com/terraform/cli/install/apt#supported-debian-and-ubuntu-releases) and so I believe this behavior is as expected.

Until the apt repository supports this distribution you will need to use a different installation strategy. Terraform executables for Linux only depend on the Kernel system call interface and not on libc, so it is typically possible to use packages built for another distribution if you wish to keep using apt, but note that this cross-distribution compatibility is not guaranteed for all other packages in the repository.

Alternatively, installing from the main `.zip` packages is a generally-available alternative. The `.deb` packages are derived from those and so you will get the same executable either way.

I'm going to label this issue as a feature request for supporting Ubuntu 22.10 in the repository, and then we'll update it once the release engineering team tells us the repository supports that distribution. Thanks!

**Comment by ihatemicrosoft-was-already-taken** [comment]
Well, Ubuntu 22.04 jammy isn't in the list of supported distros, but works just fine. I assume that the documentation is outdated regarding this? "No repositories are available for other Debian or Ubuntu versions or any other APT-based Linux distributions." obviously isn't correct.

Also, maybe the documentation should list "supported" distro releases first and the configuration later to minimize misunderstandings?

**Comment by crw** [comment]
@ihatemicrosoft-was-already-taken That page is out-of-date. The current list is:

Ubuntu: Xenial, Bionic, Focal, Groovy, Hirsute, Impish, Jammy
Debian: Jessie, Stretch, Buster, Bullseye, Bookworm

I created a pull request to correct the page in question. https://github.com/hashicorp/terraform/pull/32161

**Comment by crw** [comment]
> Also, maybe the documentation should list "supported" distro releases first and the configuration later to minimize misunderstandings?

This seems like a good idea to me. Once the above PR is approved, I'll rearrange the sections and run it past the Docs team. Thanks!
