### ISSUE TITLE
change endpoing API  resource_ibm_resource_tag

### ISSUE THREAD

**Issue by ibmappm** [hashicorp/terraform#32088]
### Terraform Version

```shell
version terraform 1.1.9
version provider IBM 1.40
```

### Terraform Configuration Files

```terraform
...terraform config...
```
[terraform.zip](https://github.com/hashicorp/terraform/files/9870250/terraform.zip)

### Debug Output

we do not fear debugging of the Code

### Expected Behavior

That the call to the APi is answered without problems

### Actual Behavior

we execute an apply and fail by getting resource tags

```
[ERROR] Error getting resource tags for: crn:v1:bluemix:public:is:eu-de-1:a/44179e2e761f424a980321e07946xxx::instance:xxx7_***** with error : Too Many Requests  with module.compute.ibm_resource_tag.update["hostname**"],
on .terraform/modules/compute/main.tf line 86, in resource "ibm_resource_tag" "update": 86: resource "ibm_resource_tag" "update" 
```

### Steps to Reproduce

We were testing to restore and modify a VSI, and in this test we were modifying the profile.
Attached is the execution of the pipeline again.

1. 17/10 17:30 first failure in apply
[31m│[0m [0m[1m[31mError: [0m[0m[1m[ERROR] Error getting resource tags for: crn:v1:bluemix:public:is:eu-de-1:a/44179e2e761f424a980321e07946cxxx::instance:02b7_9242127e-a431-478b-b710-fb4f19586xxx with error : Too Many Requests[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.compute.ibm_resource_tag.update["xxx11"],
[31m│[0m [0m  on .terraform/modules/compute/main.tf line 86, in resource "ibm_resource_tag" "update":
[31m│[0m [0m  86: resource "ibm_resource_tag" "update" [4m{[0m[0m

2. 17/10 17:53 retry failed in plan
[31m│[0m [0m[1m[31mError: [0m[0m[1m[ERROR] Error getting resource tags for: crn:v1:bluemix:public:is:eu-de-1:a/44179e2e761f424a980321e07946xxx::instance:02b7_9242127e-a431-478b-b710-fb4f19586xxx with error : Too Many Requests[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.compute.ibm_resource_tag.update["xxx11"],
[31m│[0m [0m  on .terraform/modules/compute/main.tf line 86, in resource "ibm_resource_tag" "update":
[31m│[0m [0m  86: resource "ibm_resource_tag" "update" [4m{[0m[0m

3. 18/10 08:10 Finished: SUCCESS

If you need to see the full logs we can send them privately as they contain sensitive information.

### Additional Context

We encountered a random bug related to the tag API call. 

We opened a case with the IBM provider and they told us a solution that we can't implement because the call is included in the provider. This is case CS3070529.

answer in this case:
--------
Can you please use below way to retrieve resources tags that might be particularly helpful to those of you receiving frequent 429 (Too Many Reqeuests ) from the tagging api.

The preferred way to retrieve the tags attached to a resource is the Search API, as shown in the following example.

curl -s -H'Content-type:application/json' -H'Accept:application/json' -H"Authorization:Bearer $IAM_TOKEN" -X POST 'https://api.global-search-tagging.test.cloud.ibm.com/v3/resources/search' -d'{"query":"crn:\"crn:v1:staging:public:codeengine:us-south:a/aa00ffbccdb34a6fbe7a6499ce091aaa:0a01030b-1234-1234-aaaa-002245318e88::\"", "fields":["crn","name","tags", "access_tags", "service_tags"]}'

If the resource with the given CRN exists and you can read it, then you should get the following example output, which includes all the tag types eventually attached to the resource:

{
  "items": [
    {
      "name": "my-codeengine-instance",
      "crn": "crn:v1:staging:public:codeengine:us-south:a/aa00ffbccdb34a6fbe7a6499ce091aaa:0a01030b-1234-1234-aaaa-002245318e88::", 
      "tags": ["one", "two"], 
      "access_tags": ["atag:one", "another-tag:two"], 
       "service_tags": ["service-tag:one", "service-tag:two"] 
     }
  ],
  "limit": 10,
  "search_cursor": "..."
}
You can also use the Get tags API (https://cloud.ibm.com/apidocs/tagging#list-tags) with the attached_to query parameter to obtain the same result. However, that API is strictly rate limited and it does not return all the tag types in a single call as the /v3/resources/search does. So, its usage is discouraged.

Please let us know if you have any further questions or issues we can assist you with
--------

We manage the infrastructure with Terraform and the IBM provider.
This link ( https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/globaltagging/resource_ibm_resource_tag.go) shows the configuration. And you can see that the endpoint is controlled by the provider.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by ibmappm** [comment]
ok. thanks for the information.
we create the issue to the provider
