### ISSUE TITLE
postconditions prevent destroy

### ISSUE THREAD

**Issue by azrdev** [hashicorp/terraform#32096]
### Terraform Version

```shell
Terraform v1.3.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.0
+ provider registry.terraform.io/vmware/vra v0.6.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.3.0"
  required_providers {
    vra = {
      source  = "vmware/vra"
      version = ">= 0.5.1"
    }
  }
}
resource "vra_deployment" "vm" {
  name = "test"
  catalog_item_name = "test"
  lifecycle {
    postcondition {
      condition     = self.last_request[0].action_id != "Deployment.Expire"
      error_message = "Machine has been Expired by vRA"
    }
  }
}
```

### Debug Output

│ Error: Resource postcondition failed

### Expected Behavior

The postcondition should fail in this case. But it should not prevent destruction of the resource.

### Actual Behavior

`terraform destroy` fails instead of destroying the resource

### Steps to Reproduce

1. `terraform init`
2. `terraform destroy`

### Additional Context

Putting the check as a `precondition` on an output value (which should be calculated *after* changes to the resource) still fails `terraform destroy`.

### References

- #31685
- https://github.com/vmware/terraform-provider-vra/issues/473

**Comment by jbardin** [comment]
Closed via #32051
