### ISSUE TITLE
Strange behavior with optional type constraint and variable default values

### ISSUE THREAD

**Issue by seggcsont** [hashicorp/terraform#32109]
### Terraform Version

```shell
Terraform v1.3.3
on linux_amd64
```

### Terraform Configuration Files

```terraform
variable "input" {
  type = list(object({
    a = string                # a required attribute
    b = optional(string)      # an optional attribute
    c = optional(number, 127) # an optional attribute with default value
    d = optional(list(any))
  }))
  default = [
    { a = "a" }, { a = "b", d = [1] }
  ]
}

output "out" {
  value = var.input
}
```

### Debug Output

https://gist.github.com/seggcsont/e7a04c37155e876c4868e9acdc46268b

### Expected Behavior

Without variable override it should use default value

### Actual Behavior

Error: Invalid default value for module argument

  on 1.tf line 1:
   1: variable "input" {

The default value for variable "input" is incompatible with its type
constraint: element types must all match for conversion to list.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. run command:
    `tf plan -var "input=[{a=1},{a=2, d=[]}]"`
    `tf plan -var "input=[{a=1},{a=2, d=[1]}]"`
`tf plan -var "input=[{a=1},{a=2}]"`
`tf plan -var "input=[{a=1}]"`
`tf plan`

### Additional Context
It works if you apply one of  these:
- remove the `1` from the `b=[1]` so it will be an empty list
- use optional default value `d = optional(list(any), [])`
- change type `any` to `number` like `d = optional(list(number))`

**Comment by crw** [comment]
Thanks for this report.

**Comment by kmoe** [comment]
Thanks for the well-written bug report. This shouldn't be happening: a null list should be compatible with a concrete `list(number)` regardless of initial type constraint. It's interesting to see it works with an empty list - perhaps cty should handle null and empty lists similarly in this case. Will investigate upstream.

@seggcsont, I'm curious as to why you use `list(any)` here instead of `list(number)` - could you say more about your use case?

**Comment by seggcsont** [comment]
> @seggcsont, I'm curious as to why you use `list(any)` here instead of `list(number)` - could you say more about your use case?

In my real case it is a list complex object and I do not really use `any`. I wanted to create a small peace of that code to try out something and I faced this issue.
