### ISSUE TITLE
Amazon MSK Tiered Storage

### ISSUE THREAD

**Issue by prithvi514** [hashicorp/terraform#32113]
### Terraform Version

```shell
v0.15
```

### Use Cases

Amazon MSK now supports tiered storage with S3 backend.
Terraform aws_msk_cluster should provide an option to pass `[--storage-mode <value>]` to the MSK cluster create call.

### Attempted Solutions

This option is not available currently and needs to be added to support the new tiered storage feature.

### References

https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-msk-offers-low-cost-storage-tier-scales-virtually-unlimited-storage/
https://docs.aws.amazon.com//cli/latest/reference/kafka/create-cluster.html

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
