### ISSUE TITLE
One extra default aws NACL and security is getting created while using terraform

### ISSUE THREAD

**Issue by nikhilp1411** [hashicorp/terraform#32117]
### Terraform Version

```shell
1.3.3
on linux
```

### Terraform Configuration Files

```terraform
...terraform config...
```
#provider
provider "aws" {
  region = var.region
}
#end of provider

#vpc block
resource "aws_vpc" "my_vpc" {
    cidr_block = var.vpccidrblock
    instance_tenancy = var.instancetenancy
    enable_dns_support = var.dnssupport
    enable_dns_hostnames = var.dnshostname

    tags = {
        Name = "my vpc"
    }
}
#end of resource

#Subnet1 block
resource "aws_subnet" "my_vpc_subnet1" {
    vpc_id = aws_vpc.my_vpc.id
    cidr_block = var.subnet1_cidr
    availability_zone = var.AZ_subnet1
    map_public_ip_on_launch = var.subnet_public_ip_On_lauch

    tags = {
       Name = "my subnet1"
    }
  
}
#end of resource

#Security group block
resource "aws_security_group" "my_vpc_sg" {
    vpc_id = aws_vpc.my_vpc.id
    name = "my vpc sg"
    description = "my vpc sg"

    ingress {
      description = "inbound rule"
      cidr_blocks = var.sg_ingress_cidr
      from_port = 22
      to_port = 22
      protocol = "tcp"
    } 

    egress {
        description = "outbound"
        from_port = 0
        to_port = 0
        protocol = "-1"
        cidr_blocks = var.sg_egress_cidr
    }
  
  tags = {
    Name = "my vpc sg"
    description = "my vpc sg"
  }
}
#end of resource

#NACL block
resource "aws_network_acl" "my_vpc_nacl" {
    vpc_id = aws_vpc.my_vpc.id

    ingress {  # for port22
        protocol = "tcp"
        rule_no = 100
        action = "allow"
        cidr_block = var.destinationCIDR
        from_port = 22
        to_port = 22
    }

    ingress { #for port 80
        protocol = "tcp"
        rule_no = 200
        action = "allow"
        cidr_block = var.destinationCIDR
        from_port = 80
        to_port = 80

    }

    ingress { #ephemeral port
        protocol = "tcp"
        rule_no = 300
        action = "allow"
        cidr_block = var.destinationCIDR
        from_port = 1024
        to_port = 65535

    }

    egress { #22 port
        protocol = "tcp"
        rule_no = 100
        action = "allow"
        cidr_block = var.destinationCIDR
        from_port = 22
        to_port = 22

    }

    egress { #80 port
        protocol = "tcp"
        rule_no = 200
        action = "allow"
        cidr_block = var.destinationCIDR
        from_port = 80
        to_port = 80

    }

    egress { #ephemeralport
        protocol = "tcp"
        rule_no = 300
        action = "allow"
        cidr_block = var.destinationCIDR
        from_port = 1024
        to_port = 65535

    }

  tags = {
    Name = "my_vpc_nacl"
  }

}
#end of resource

##NACL_association for both subnets
resource "aws_network_acl_association" "subnet1" {
  network_acl_id = aws_network_acl.my_vpc_nacl.id
  subnet_id = aws_subnet.my_vpc_subnet1.id

}
#end of resource

#IG block
resource "aws_internet_gateway" "my_vpc_ig" {
  vpc_id = aws_vpc.my_vpc.id

  tags = {
    Name = "my vpc ig"
  }
}
#end of resource

#RT block
resource "aws_route_table" "my_vpc_rt" {
  vpc_id = aws_vpc.my_vpc.id

  tags = {
    Name = "my vpc rt"
  }

}
#end of RT block

#Route block
resource "aws_route" "internet_access" {
  route_table_id = aws_route_table.my_vpc_rt.id
  gateway_id = aws_internet_gateway.my_vpc_ig.id
  destination_cidr_block = var.destinationCIDR
  
}
#end of resource

#RT and subnet association
resource "aws_route_table_association" "RT_subnet1" {
   subnet_id = aws_subnet.my_vpc_subnet1.id
  route_table_id = aws_route_table.my_vpc_rt.id
  
}
#end of resource

#ec2 creation block
resource "aws_instance" "my_instance" {
    ami = var.ami_id
    instance_type = var.ins_type
    key_name = var.key
    subnet_id = aws_subnet.my_vpc_subnet1.id
    vpc_security_group_ids = [aws_security_group.my_vpc_sg.id]
   
    tags = {
	"Name" = "my instance"
     } 
}
#end of resource

### Debug Output

The code mentioned is working fine and resources are getting created.

However the one extra default NACL and security group is getting created in aws console and no subnet associated with it.

No any help is getting on web with related to it.

### Expected Behavior

It should create only specified NACL and security group only.

### Actual Behavior

It should create only specified NACL and security group only.

### Steps to Reproduce

1.terraform init
2.terraform plan
3.terraform apply

**Comment by nikhilp1411** [comment]
here is variable code.

variable "region" {
    default = "ap-south-1"
}

variable "vpccidrblock" {
    default = "192.0.0.0/16"
}

variable "instancetenancy" {
    default = "default"  
}

variable "dnssupport" {
    default = true  
}

variable "dnshostname" {
    default = true
}

variable "subnet1_cidr" {
    default = "192.0.4.0/24"
}

variable "AZ_subnet1" {
    default = "ap-south-1a"
}

variable "subnet_public_ip_On_lauch" {
    default = true
}

variable "sg_ingress_cidr" {
    type = list
    default = ["0.0.0.0/0"]
}

variable "sg_egress_cidr" {
    type = list
    default = ["0.0.0.0/0"]
}

variable "destinationCIDR" {
    default = "0.0.0.0/0"
}

variable "ins_type" {
    default = "t2.micro" 
}

variable "ami_id" {
    default = "ami-0e6329e222e662a52"
}

variable "key" {
    default = "ap-key"
}

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
