### ISSUE TITLE
aws_dms_endpoint.cdc_min_file_size should be in Megabytes and stated default should be 32,000

### ISSUE THREAD

**Issue by alordthorsen** [hashicorp/terraform#32128]
### Terraform Version

```shell
1.3.3
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#cdc_max_batch_interval

### What is the docs issue?

[cdc_min_file_size is listed in megabytes with a default of](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#cdc_max_batch_interval) 32. My team set the value to 400 (in an attempt to get 400 MB files) and we ended up with 400 KB file sizes. If you look at the [AWS Docs for cdcMinFileSize](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.Configuring) under the configuration page you'll see 

> Minimum file size condition as defined in kilobytes to output a file to Amazon S3.

> Default Value: 32000 KB

> When cdcMinFileSize is specified and cdcMaxBatchInterval is specified, the file write is triggered by whichever parameter condition is met first.

Which is a strong contradiction from the Terraform docs on this option.

### Proposal

Change `kilobytes` to `megabytes` and `32` to `32000`.

Specifically

```
[cdc_min_file_size](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#cdc_min_file_size) - (Optional) Minimum file size, defined in kilobytes, to reach for a file output. Default is 32000.
```

**Comment by apparentlymart** [comment]
Hi @alordthorsen! Thanks for reporting this.

The documentation you've linked to here belongs to the `hashicorp/aws` provider, so this documentation lives in that provider's repository here:
https://github.com/hashicorp/terraform-provider-aws/blob/21e06c741af4cbc0c5ae5ae64bbce11089249b94/website/docs/r/dms_endpoint.html.markdown

We therefore can't change anything in this repository that would improve that documentation in the way you've described, so I'm going to close this. Instead, I suggest opening an issue in [the provider's own repository](https://github.com/hashicorp/terraform-provider-aws) to discuss this with the team which maintains that provider.

Thanks again!
