### ISSUE TITLE
Terraform Always Attempts to Destroy Resource Before Removing Any Reference to It

### ISSUE THREAD

**Issue by ysyesa** [hashicorp/terraform#32153]
### Terraform Version

```shell
1.3.3
```

### Terraform Configuration Files

The simplest example I can come up with to show this bug is by having two dependent AWS security groups, shown below.

```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.37.0"
    }
  }
}

resource "aws_security_group" "security_group_1" {
  name = "SecurityGroup1"
  vpc_id = "vpc-xxxxxxxx"
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
  }
}

resource "aws_security_group" "security_group_2" {
  name = "SecurityGroup2"
  vpc_id = "vpc-xxxxxxxx"
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    security_groups = [aws_security_group.security_group_1.id]
  }
}

```

### Debug Output

The relevant debug output is the part which shows when Terraform is building the Apply Graph, specifically in the part of `DestroyEdgeTransformer`:

```
2022-11-03T18:35:40.278+0800 [TRACE] Executing graph transform *terraform.DestroyEdgeTransformer
2022-11-03T18:35:40.278+0800 [TRACE] DestroyEdgeTransformer: "aws_security_group.security_group_1 (destroy)" (*terraform.NodeDestroyResourceInstance) destroys aws_security_group.security_group_1
2022-11-03T18:35:40.278+0800 [TRACE] DestroyEdgeTransformer: aws_security_group.security_group_2 has stored dependency of aws_security_group.security_group_1 (destroy)
2022-11-03T18:35:40.278+0800 [TRACE] Completed graph transform *terraform.DestroyEdgeTransformer with new graph:
  aws_security_group.security_group_1 (destroy) - *terraform.NodeDestroyResourceInstance
    provider["registry.terraform.io/hashicorp/aws"] - *terraform.NodeApplyableProvider
  aws_security_group.security_group_2 - *terraform.NodeApplyableResourceInstance
    aws_security_group.security_group_1 (destroy) - *terraform.NodeDestroyResourceInstance
    aws_security_group.security_group_2 (expand) - *terraform.nodeExpandApplyableResource
    provider["registry.terraform.io/hashicorp/aws"] - *terraform.NodeApplyableProvider
  aws_security_group.security_group_2 (expand) - *terraform.nodeExpandApplyableResource
    provider["registry.terraform.io/hashicorp/aws"] - *terraform.NodeApplyableProvider
  provider["registry.terraform.io/hashicorp/aws"] - *terraform.NodeApplyableProvider
  ------
```
 
The graph above will make Terraform destroy `security_group_1` first before modifying `security_group_2`.

### Expected Behavior

After removing `security_group_1` and the reference to it in `security_group_2`, Terraform **should** do the following **in order**:
1. Update `security_group_2` by removing the reference to `security_group_1`
2. Destroy `security_group_1`

### Actual Behavior

After removing `security_group_1` and the reference to it in `security_group_2`, Terraform does the following in order:
1. Destroy `security_group_1`
2. Update `security_group_2` by removing the reference to `security_group_1`

This operation will always fail at step 1. `security_group_1` is still referenced by `security_group_2`, thus cannot be destroyed. 

The error message I obtained from AWS provider:
```
Error: deleting Security Group (sg-00add460b62cae006): DependencyViolation: resource sg-00add460b62cae006 has a dependent object
status code: 400
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Remove `security_group_1` and the reference to it in `security_group_2` as shown in the code block below.
4. `terraform apply`

```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.37.0"
    }
  }
}

resource "aws_security_group" "security_group_2" {
  name = "SecurityGroup2"
  vpc_id = "vpc-xxxxxxxx"
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    security_groups = []
  }
}
```

### References

Proposed fix in the PR [#32154](https://github.com/hashicorp/terraform/pull/32154)

**Comment by jbardin** [comment]
Hi @ysyesa,

Thanks for filing the issue. The default order of operations here is correct, the destroy must always happen before the update. If you need the update to be applied first, then you must use `create_before_destroy` to get the inverse ordering.
Please see the last issue #32136 for a more complete explanation.

Thanks!
