### ISSUE TITLE
Terraform Registry Documentation down

### ISSUE THREAD

**Issue by rdvansloten** [hashicorp/terraform#32156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

-

### AzureRM Provider Version

-

### Affected Resource(s)/Data Source(s)

Terraform Registry

### Terraform Configuration Files

```hcl
-
```

### Debug Output/Panic Output

```shell
JS Console, doubt it's useful:

chunk.762.edcb5037eb7add53acf4.js:275 
        
       Refused to connect to 'https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j98&tid=UA-53231375-2&cid=1922747385.1667485163&jid=1892938712&gjid=1181778328&_gid=306465306.1667485163&_u=SCCAAEAAQAAAACAAIAB~&z=203293301' because it violates the following Content Security Policy directive: "connect-src 'self' https://www.google-analytics.com https://api.segment.io https://cdn.segment.com https://sentry.io https://api.omappapi.com https://api.opmnstr.com https://api.optmnstr.com https://*.algolia.net https://*.algolianet.com".

(anonymous) @ chunk.762.edcb5037eb7add53acf4.js:275
(anonymous) @ chunk.762.edcb5037eb7add53acf4.js:215
wd @ VM522 analytics.js:43
pe @ VM522 analytics.js:42
oc @ VM522 analytics.js:43
Ea @ VM522 analytics.js:43
g.onreadystatechange @ VM522 analytics.js:42
e @ chunk.762.edcb5037eb7add53acf4.js:194
XMLHttpRequest.send (async)
(anonymous) @ chunk.762.edcb5037eb7add53acf4.js:275
(anonymous) @ chunk.762.edcb5037eb7add53acf4.js:215
wd @ VM522 analytics.js:43
pe @ VM522 analytics.js:42
Sa @ VM522 analytics.js:47
Ha.D @ VM522 analytics.js:45
pc.send @ VM522 analytics.js:82
X.b.<computed> @ VM522 analytics.js:62
Z.v @ VM522 analytics.js:99
Z.D @ VM522 analytics.js:98
N @ VM522 analytics.js:99
(anonymous) @ VM523:1
Z.v @ VM522 analytics.js:99
Z.D @ VM522 analytics.js:98
N @ VM522 analytics.js:99
so @ optimize.js?id=GTM-TZ8DF93:168
Dp @ optimize.js?id=GTM-TZ8DF93:178
Eq @ optimize.js?id=GTM-TZ8DF93:200
Hq @ optimize.js?id=GTM-TZ8DF93:205
Lq.b.push @ optimize.js?id=GTM-TZ8DF93:209
Cq @ optimize.js?id=GTM-TZ8DF93:199
(anonymous) @ optimize.js?id=GTM-TZ8DF93:277
(anonymous) @ optimize.js?id=GTM-TZ8DF93:272
(anonymous) @ optimize.js?id=GTM-TZ8DF93:274
(anonymous) @ optimize.js?id=GTM-TZ8DF93:280
chunk.762.edcb5037eb7add53acf4.js:275 
        
       Refused to connect to 'https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j98&tid=UA-53231375-2&cid=1922747385.1667485163&jid=1291934689&gjid=92213232&_gid=306465306.1667485163&_u=SCCACEABRAAAACAAIAB~&z=1907777907' because it violates the following Content Security Policy directive: "connect-src 'self' https://www.google-analytics.com https://api.segment.io https://cdn.segment.com https://sentry.io https://api.omappapi.com https://api.opmnstr.com https://api.optmnstr.com https://*.algolia.net https://*.algolianet.com".

(anonymous) @ chunk.762.edcb5037eb7add53acf4.js:275
(anonymous) @ chunk.762.edcb5037eb7add53acf4.js:215
wd @ VM522 analytics.js:43
pe @ VM522 analytics.js:42
oc @ VM522 analytics.js:43
Ea @ VM522 analytics.js:43
g.onreadystatechange @ VM522 analytics.js:42
e @ chunk.762.edcb5037eb7add53acf4.js:194
XMLHttpRequest.send (async)
(anonymous) @ chunk.762.edcb5037eb7add53acf4.js:275
(anonymous) @ chunk.762.edcb5037eb7add53acf4.js:215
wd @ VM522 analytics.js:43
pe @ VM522 analytics.js:42
Sa @ VM522 analytics.js:47
Ha.D @ VM522 analytics.js:45
pc.send @ VM522 analytics.js:82
X.b.<computed> @ VM522 analytics.js:62
Z.v @ VM522 analytics.js:99
Z.D @ VM522 analytics.js:98
N @ VM522 analytics.js:99
so @ optimize.js?id=GTM-TZ8DF93:168
Dp @ optimize.js?id=GTM-TZ8DF93:178
Eq @ optimize.js?id=GTM-TZ8DF93:200
Hq @ optimize.js?id=GTM-TZ8DF93:205
Lq.b.push @ optimize.js?id=GTM-TZ8DF93:209
Cq @ optimize.js?id=GTM-TZ8DF93:199
(anonymous) @ optimize.js?id=GTM-TZ8DF93:277
(anonymous) @ optimize.js?id=GTM-TZ8DF93:272
(anonymous) @ optimize.js?id=GTM-TZ8DF93:274
(anonymous) @ optimize.js?id=GTM-TZ8DF93:280
api.min.js:1 
        
       Refused to load the stylesheet 'https://a.omappapi.com/app/js/api.min.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com https://p.typekit.net https://use.typekit.net". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

### Expected Behaviour

The website should load documentation:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management

### Actual Behaviour

It does not load any content. Forever loading. Tested on 5G and 2 different wifi networks. Phone and laptop.
<img width="962" alt="Screen Shot 2022-11-03 at 15 25 02" src="https://user-images.githubusercontent.com/54894409/199747455-4de87b0a-44c8-4050-bd40-72910273b13b.png">

### Steps to Reproduce

Go to: 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management

or 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app

or 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_app_active_slot

### Important Factoids

Visiting from NL, Europe.

**Comment by petetnt** [comment]
Like mentioned in the other issue, the docs can be (inconveniently) found in the repohttps://github.com/hashicorp/terraform-provider-azurerm/tree/2daadb0f15ce7b64107c863ea76526b0b3c6f01a/website/docs

**Comment by cloudhunter89** [comment]
Just adding a little more information here - There seems to be a mismatch in the CSP configuration.  I also lose api.min.css because https://a.omappapi.com/app/js/api.min.css is not in the CSP config in the docs response header `default-src 'self'; script-src 'self' 'unsafe-inline' https://www.google-analytics.com https://cdn.segment.com https://www.googletagmanager.com https://a.optnmstr.com; style-src 'self' 'unsafe-inline' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com https://p.typekit.net https://use.typekit.net; img-src 'self' data: https: https://www.google-analytics.com; font-src 'self' https://maxcdn.bootstrapcdn.com https://fonts.googleapis.com https://fonts.gstatic.com https://use.typekit.net; connect-src 'self' https://www.google-analytics.com https://api.segment.io https://cdn.segment.com https://sentry.io https://api.omappapi.com https://api.opmnstr.com https://api.optmnstr.com https://*.algolia.net https://*.algolianet.com`

**Comment by crw** [comment]
Closing this issue as @SarahFrench seems to have closed the related registry issue. Please see: https://github.com/hashicorp/terraform-provider-google/issues/12942#issuecomment-1302343517
