### ISSUE TITLE
Terraform destroy hangs on nodes removal

### ISSUE THREAD

**Issue by cande1gut** [hashicorp/terraform#32167]
### Terraform Version

```shell
Terraform v1.3.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.15.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
```

### Terraform Configuration Files

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.26.6"

  cluster_name    = local.cluster_name
  cluster_version = "1.23"

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  eks_managed_node_group_defaults = {
    ami_type = "AL2_x86_64"

    attach_cluster_primary_security_group = true

    # Disabling and using externally provided security groups
    create_security_group = false
  }

  eks_managed_node_groups = {
    one = {
      name = "node-group-1"

      instance_types = ["t3.small"]

      min_size     = 1
      max_size     = 2
      desired_size = 1

      pre_bootstrap_user_data = <<-EOT
      echo 'foo bar'
      EOT

      vpc_security_group_ids = [
        aws_security_group.node_group_one.id
      ]
    }

    two = {
      name = "node-group-2"

      instance_types = ["t3.medium"]

      min_size     = 1
      max_size     = 2
      desired_size = 1

      pre_bootstrap_user_data = <<-EOT
      echo 'foo bar'
      EOT

      vpc_security_group_ids = [
        aws_security_group.node_group_two.id
      ]
    }
  }
}
```

### Debug Output

Waiting to be destroyed...

### Expected Behavior

Destroy node groups and cluster.

### Actual Behavior

Destroy nodes but it hangs when nodes are destroyed and state never changes to destroy the cluster.

### Steps to Reproduce

terraform destroy

### Additional Context

Used modules and example from: [hashicorp example](https://github.com/hashicorp/learn-terraform-provision-eks-cluster)

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

It's difficult to determine from the example here which provider may be blocking the operation, but given the bulk of the resources are managed by the AWS provider, that would be a good place to start. Checking the logs output would show specifically which resource is waiting for a response.

Thanks!
