### ISSUE TITLE
Restore a dynamodb db (with stream enable) from AWS backup.

### ISSUE THREAD

**Issue by kytang-collectivfood** [hashicorp/terraform#32176]
### Terraform Version

```shell
Terraform version =1.3.4
```

### Terraform Configuration Files

```terraform
resource "aws_dynamodb_table" "oms_responsibly_producer_score_raw" {
 ...

  stream_enabled = true
  stream_view_type = "NEW_IMAGE"
}
```

### Debug Output

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.order-dynamo-stream-elastic-search-publisher.aws_lambda_event_source_mapping.order_dynamo_es_publisher_event_stream
│ to include new values learned so far during apply, provider
│ "[registry.terraform.io/hashicorp/aws](http://registry.terraform.io/hashicorp/aws)" produced an invalid new value for
│ .event_source_arn: was cty.StringVal(""), but now
│ cty.StringVal("arn:aws:dynamodb:$AWS_DEFAULT_REGION:911481865375:table/apricot-qa2-dynamodb-order/stream/2022-11-07T12:28:02.092").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Expected Behavior

After restore the dynamodb from AWS backup, we expect the data stream will be recreated when we execute the terraform again.

### Actual Behavior

Display an error message

### Steps to Reproduce

1. terraform init
2. terraform apply

### Additional Context

We try to restore the dynamodb from AWS backup, and we would like to re-enable the data stream when we execute the terraform again. I guess the timestamp of data stream does not match the terraform state.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
