### ISSUE TITLE
Terraform 1.3.4 - errors for deleted resources after partial destroy

### ISSUE THREAD

**Issue by kirikors** [hashicorp/terraform#32185]
### Terraform Version

```shell
Terraform v1.3.4
on windows_amd64
+ provider registry.terraform.io/aliyun/alicloud v1.190.0
+ provider registry.terraform.io/hashicorp/null v3.2.0
```

### Terraform Configuration Files

[Sample code to reproduce the issue](https://gist.github.com/kirikors/5bb25cf27a6b7244fc23bac858e19ad5)

### Debug Output

[TF debug logs for the second destroy run](https://gist.github.com/kirikors/efb5b260b78514b418e8caf38b758303)

### Expected Behavior

destroy operation doesn't validate references to already deleted resources

### Actual Behavior

references to non-existing (already deleted) resources are validated during destroy operation, resulting in an exception

### Steps to Reproduce

The issue happens on TF destroy operation after a failure (when previous destroy run managed to delete some of the resources, but not all).

To reproduce:
1. terraform apply
2. manually create a resource that will block VPC deletion
3. run first terraform destroy -> will delete everything except the VPC, VPC deletion will fail (see [gist](https://gist.github.com/kirikors/d56703e0a321d36d3acb1d85060d672e))
4. run second terraform destroy -> will fail because of references to non-existing resources (those deleted by the previous partial destroy run) - see [gist](https://gist.github.com/kirikors/993879e1dbaf75dd58dddb2eab109759)

### Additional Context

The issue doesn't happen with Terraform 1.2.9 - second destroy attempt is successful.

The issue is not limited to just outputs validation, we get similar errors in other places (see [gist](https://gist.github.com/kirikors/779197d319e3bbe2f6cb8de118265dac))

### References

Same issue as https://github.com/hashicorp/terraform/issues/31975, but happens in Terraform 1.3.4 (that was supposed to fix it)

**Comment by jbardin** [comment]
Thanks @kirikors! Because root module outputs have a different use from child modules, this is a slightly different case than the linked issue.
