### ISSUE TITLE
AWS provider creates duplicate ECS Cluster

### ISSUE THREAD

**Issue by brezmes** [hashicorp/terraform#3219]
Terraform v0.6.3

When I'm creating an ecs, with one resource defined, it creates two.

I attach the ecs.tf file.

Thanks

**Comment by brezmes** [comment]
# ECS #
provider "aws" {
    access_key  = "${var.access_key}"
    secret_key  = "${var.secret_key}"
    region      = "${var.region}"
}

resource "aws_ecs_cluster" "arm-op-ecs" {
  name = "${var.project}-ecs"
}

resource "aws_ecs_service" "arm-op-service-fr" {
  name = "${var.project}-service-fr"
  cluster = "${aws_ecs_cluster.arm-op-ecs.id}"
  task_definition = "${aws_ecs_task_definition.arm-fr.arn}"
  desired_count = 2
  }

resource "aws_ecs_service" "arm-op-service-bk-auth" {
  name = "${var.project}-service-bk-auth"
  cluster = "${aws_ecs_cluster.arm-op-ecs.id}"
  task_definition = "${aws_ecs_task_definition.arm-bk-auth.arn}"
  desired_count = 2
  }

resource "aws_ecs_service" "arm-op-service-bk-resources" {
  name = "${var.project}-service-bk-resources"
  cluster = "${aws_ecs_cluster.arm-op-ecs.id}"
  task_definition = "${aws_ecs_task_definition.arm-bk-resources.arn}"
  desired_count = 2
  }

resource "aws_ecs_service" "arm-op-service-consul" {
  name = "${var.project}-service-consul"
  cluster = "${aws_ecs_cluster.arm-op-ecs.id}"
  task_definition = "${aws_ecs_task_definition.arm-consul.arn}"
  desired_count = 2
  }

resource "aws_ecs_service" "arm-op-service-registrator" {
  name = "${var.project}-service-registrator"
  cluster = "${aws_ecs_cluster.arm-op-ecs.id}"
  task_definition = "${aws_ecs_task_definition.arm-registrator.arn}"
  desired_count = 2
  }

**Comment by radeksimko** [comment]
Hi @brezmes 
I will try to reproduce this, but can you clarify what resource exactly is being duplicated in your case?

**Comment by brezmes** [comment]
Hi @radeksimko 

Yes, It's resource "aws_ecs_cluster" "arm-op-ecs", it creates arm-op-ecs and arm-op, but I can't find arm-op on terraform.tfstate, but it is on AWS console.

**Comment by radeksimko** [comment]
@brezmes I was trying to reproduce this, but I had no luck. A single ECS cluster was created without any issues, using the latest version (`v0.6.7-dev (5e282683bfcd819fc3eacd94de424924d14701b5)`)

Can you please try to reproduce this again with the latest release and also attach full debug log (minus any secrets) that you get via `TF_LOG=1 TF_LOG_PATH=<location>.log terraform apply`?
I will be specifically looking for this log message:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_ecs_cluster.go#L42

**Comment by catsby** [comment]
Hey all – I'm going close this for now. If you can reproduce it still please let us know and we'll take another look. Thanks!
