### ISSUE TITLE
unset key_name not causing TF to recreate/update aws_launch_configuraiton

### ISSUE THREAD

**Issue by jaffel-lc** [hashicorp/terraform#32215]
### Terraform Version

```shell
Terraform v1.3.4                                                                                                                                                                            on linux_amd64                                                                                                                                                                              + provider registry.terraform.io/hashicorp/aws v4.38.0
```

### Terraform Configuration Files

```terraform
...terraform config...

resource "aws_launch_configuration" "launch" {
  name_prefix                 = "${local.cluster_name}-"
  image_id                    = local.ami_image_id
  instance_type               = var.cluster_instance_type
  security_groups             = [aws_security_group.launch-security.id]
  iam_instance_profile        = aws_iam_instance_profile.instance_profile.name
  key_name                    = var.cluster_key_name
  associate_public_ip_address = var.public_ip_address
  user_data                   = local.user_data
  root_block_device {
    volume_size = 30
    volume_type = "gp3"
    encrypted   = true
  }
  ebs_block_device {
    device_name = "/dev/xvdcz"
    volume_type = "gp3"
    volume_size = 22
    encrypted   = true
  }
  lifecycle {
    create_before_destroy = true
  }
}


resource "aws_security_group_rule" "ssh_from_anywhere" {
  count             = var.cluster_key_name != "" ? 1 : 0
  type              = "ingress"
  description       = "allow 22 from anywhere"
  prefix_list_ids   = []
  security_group_id = aws_security_group.launch-security.id
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["0.0.0.0/0"]
  ipv6_cidr_blocks  = ["::/0"]
}


```

### Debug Output

https://gist.github.com/jaffel-lc/9acf12f65c13c5b8d0bac34de324cc29

### Expected Behavior

TF plans to destroy security group rule and update/recreate launch configuration (and ASG that uses it)

### Actual Behavior

TF plans to destroy security group rule, but nothing else

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

I tried this with several TF version from 1.X ro 1.3.4, and even one v12.x
all had the same issue.

If i were to create the launch configuration without a key, then add a key it will do the right thing and seek to replace the launch config. But not when we go form key to o key

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by jaffel-lc** [comment]
Thank you.
