### ISSUE TITLE
create rds mariadb  failed

### ISSUE THREAD

**Issue by johanwinter1** [hashicorp/terraform#32212]
### Terraform Version

```shell
1.2.5
```

### Terraform Configuration Files

resource "aws_rds_cluster" "this" {
  cluster_identifier               = "${var.name}-${var.env}-cluster"
  engine                           = "mariadb"
  engine_version                   = "10.6"
... snip

### Debug Output

none

### Expected Behavior

create rds maridb 

### Actual Behavior

Error: expected engine to be one of [aurora aurora-mysql aurora-postgresql mysql postgres], got mariadb

### Steps to Reproduce

Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: expected engine to be one of [aurora aurora-mysql aurora-postgresql mysql postgres], got mariadb
│ 
│   with aws_rds_cluster.this,
│   on dbcluster.tf line 76, in resource "aws_rds_cluster" "this":
│   76:   engine                           = "mariadb"
│

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by johanwinter1** [comment]
thx
