### ISSUE TITLE
Unable to Modify/View "Endpoint encryption" for AWS Workspaces Directory (Set to FIPS Validated) - Possibly GovCloud Specific

### ISSUE THREAD

**Issue by michaelsmoody** [hashicorp/terraform#32229]
### Terraform Version

```shell
Terraform v1.3.4
on windows_amd64
```

### Use Cases

Many compliance standards require FIPS 140-2 (soon FIPS 140-3), and GovCloud itself generally requires FIPS 140-2. Additionally, many Government agencies require connectivity with FIPS Validated (not just compliant) encryption (_A BIG DEAL™_). As such, this is _available_ in AWS (GovCloud at least), but it seems manual at this time. This enables use by not just Government Agencies but those who also require it, and frankly, might not know it.

### Attempted Solutions

No Terraform-based Solution was possible, comments left notifying future users to make a manual change (at this time). 

I was unable to determine if it was available to be set in Boto3.

My comment notes that you must modify the Directory (note, this is _NOT_ a modification in `Directory Service` using either the AWS CLI or the Console, but in `Workspaces` with a Workspaces-registered Directory, which (while somewhat confusing to new users, and perhaps a duplication of settings, frankly, once again, thanks AWS), to enable FIPS-validated Encryption.

### Proposal

Enable FIPS-Validated Encryption via initial setup. Also ensure that this setting is available to the data source (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/workspaces_directory)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by michaelsmoody** [comment]
@jbardin You're absolutely correct, I deeply apologize. That's _MY_ mistake. I had multiple tabs open and opened the issue in the wrong one! Thanks for the patience!!!
