### ISSUE TITLE
The provider returned a resource missing an identifier during ImportResourceState

### ISSUE THREAD

**Issue by brunooliveiramelo** [hashicorp/terraform#32225]
### Terraform Version

```shell
Terraform 1.0.5
```

### Terraform Configuration Files

```
resource "datadog_integration_aws" "int" {}
```

### Debug Output

[TF debug log](https://gist.github.com/brunooliveiramelo/02a528b976b57c4243cc105eb90633a8)

### Expected Behavior

The import of the resource into the state file

### Actual Behavior

Fails in the Terraform import

`datadog_integration_aws.int: Importing from ID "account_id:role_name"...
 Error: The provider returned a resource missing an identifier during ImportResourceState. This is generally a bug in the resource implementation for import. Resource import code should not call d.SetId("") or create an empty ResourceData. If the resource is missing, instead return an error. Please report this to the provider developers.`

### Steps to Reproduce

1. create a resource block datadog_integration_aws.int
2. terraform init
3. terraform validate
4. terraform import

**Comment by gastrodon** [comment]
> Please report this to the provider developers

https://github.com/DataDog/terraform-provider-datadog/issues

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
