### ISSUE TITLE
azurerm_service_app ip_restriction all properties are required

### ISSUE THREAD

**Issue by ross-ivanov-oritain** [hashicorp/terraform#32224]
### Terraform Version

```shell
Terraform v1.3.4
```

### Terraform Configuration Files

resource "azurerm_app_service" "someservice" {

....

  site_config {

    ip_restriction = [
      {
           action     = "allow"
           ip_address = "173.245.48.0/20"
           name       = "cloudflare_ip"

        },
    ]

  }
  
....
}

### Debug Output

 Error: Incorrect attribute value type
│ 
│   on ../../modules/waf.tf line 123, in resource "azurerm_app_service" "someservice":
│  123:     ip_restriction = [
│  124:       {
│  125:            action     = "allow"
│  126:            ip_address = "173.245.48.0/20"
│  127:            name       = "cloudflare_ip"
│  128:         },
│  129:     ]
│ 
│ Inappropriate value for attribute "ip_restriction": element 0: attributes "headers", "priority", "service_tag", and "virtual_network_subnet_id" are required.

### Expected Behavior

One and only one of **ip_address**, **service_tag** or **virtual_network_subnet_id** must be specified.
headers are also optional

### Actual Behavior

Fails on terraform plan

### Steps to Reproduce

1. Create azurerm_service_app
2. add ip_restriction section
    ip_restriction = [
      {
           action     = "allow"
           ip_address = "173.245.48.0/20"
           name       = "cloudflare_ip"

        },
3. terraform plan

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
