### ISSUE TITLE
Please provide RPM repository for Fedora 37

### ISSUE THREAD

**Issue by christianfosli** [hashicorp/terraform#32228]
### Terraform Version

```shell
Terraform v1.3.2
on linux_amd64
```

### Use Cases

I would like to install terraform and terraform-language-server using my distributions package manager.
This is available for Fedora Linux 36, but currently not for Fedora Linux 37, which was released yesterday.

### Attempted Solutions

Following the instructions at https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli#install-terraform I did

```bash
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
sudo dnf -y install terraform
```

But I get an error that the repository does not exist:
```
Errors during downloading metadata for repository 'hashicorp':
  - Status code: 404 for https://rpm.releases.hashicorp.com/fedora/37/x86_64/stable/repodata/repomd.xml (IP: 54.230.111.115)
Error: Failed to download metadata for repo 'hashicorp': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: hashicorp
```

### Proposal

Adding an RPM repository for Fedora 37

### References

- #30790

**Comment by SuperJC710e** [comment]
+1

However, as a workaround, you can edit the `hashicorp.repo` file: `sudoedit /etc/yum.repos.d/hashicorp.repo` and overwrite the `$releasever` variable with `36`.

```shell
[hashicorp]
name=Hashicorp Stable - $basearch
#baseurl=https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
baseurl=https://rpm.releases.hashicorp.com/fedora/36/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://rpm.releases.hashicorp.com/gpg

[hashicorp-test]
name=Hashicorp Test - $basearch
#baseurl=https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/test
baseurl=https://rpm.releases.hashicorp.com/fedora/36/$basearch/test
enabled=0
gpgcheck=1
gpgkey=https://rpm.releases.hashicorp.com/gpg
```

Of course, you'll have to keep any eye for when the proper repo arrives for `37` :smile:

**Comment by vkSegfault** [comment]
+ 1, doing same thing what @SuperJC710e but would be great without this hackish solution :)

**Comment by SuperJC710e** [comment]
> would be great without this hackish solution :)

@vkSegfault Absolutely agree!

**Comment by crw** [comment]
We just did a release which may have fixed this issue (I can download `https://rpm.releases.hashicorp.com/fedora/37/x86_64/stable/repodata/repomd.xml`) -- is this working now?

**Comment by SuperJC710e** [comment]
> We just did a release which may have fixed this issue (I can download `https://rpm.releases.hashicorp.com/fedora/37/x86_64/stable/repodata/repomd.xml`) -- is this working now?

Thank you! I reverted the changes to the repo file, and it no longer complained about the missing path! Should be good! :) Thanks again!

**Comment by christianfosli** [comment]
> We just did a release which may have fixed this issue (I can download `https://rpm.releases.hashicorp.com/fedora/37/x86_64/stable/repodata/repomd.xml`) -- is this working now?

It works perfectly here too. Thanks! Closing.
