### ISSUE TITLE
Make private AWS S3 bucket

### ISSUE THREAD

**Issue by karkir0003** [hashicorp/terraform#32242]
### Terraform Version

```shell
v1.3.4
```

### Affected Pages

N/A

### What is the docs issue?

I'm trying to create a private S3 bucket using Terraform. I followed the script at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket. However, when I create the bucket and go into "Permissions", I'm seeing "Objects can be public", which seems to imply that the bucket isn't private. I'm not sure what I'm missing. Can someone help me out

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket

**Comment by karkir0003** [comment]
@mitchellh

**Comment by thomaschin35** [comment]
Instead of using resource "aws_s3_bucket_acl", use resource "aws_s3_bucket_public_access_block" and add these settings:
<img width="490" alt="Screen Shot 2022-11-17 at 10 46 38 PM" src="https://user-images.githubusercontent.com/81205095/202612668-22055796-aa47-46e6-aa75-717d93ac7dc4.png">

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
