### ISSUE TITLE
Using a non hashicorp provider in a module

### ISSUE THREAD

**Issue by surendragupta481** [hashicorp/terraform#32247]
### Terraform Version

```shell
Terraform v1.3.5
on windows_amd64
+ provider registry.terraform.io/vmware/vcd v3.7.0
```

### Terraform Configuration Files

providers.tf 
terraform {
  # required_version = "1.3.4"
  required_providers {
    vcd = {
      source  = "vmware/vcd"
      version = "3.7.0"
      # configuration_aliases = [vcd] 
    }
  }
}

# Connect VMware vCloud Director Provider
provider "vcd" {
  aalias = "abc"  
  user                 = var.vcd_user
  password             = var.vcd_pass
  auth_type            = "integrated"
  org                  = "System"
  url                  = var.vcd_url
  max_retry_timeout    = var.vcd_max_retry_timeout
  allow_unverified_ssl = var.vcd_allow_unverified_ssl
}

module file 

module "myorg" {
  source = "../vCD_Testing/modules/vcd_org_creation"
  # providers = {
  #   vcd = vcd.abc
  #  }
}

### Debug Output

NA

### Expected Behavior

Must Initializing modules.

### Actual Behavior

Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of vmware/vcd from the dependency lock file
- Finding latest version of hashicorp/vcd...
- Using previously-installed vmware/vcd v3.7.0
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/vcd: provider registry registry.terraform.io does not have a    
│ provider named registry.terraform.io/hashicorp/vcd
│
│ Did you intend to use vmware/vcd? If so, you must specify that source address in each module which requires that provider. To see which  
│ modules are currently depending on hashicorp/vcd, run the following command:
│     terraform providers

### Steps to Reproduce

Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of vmware/vcd from the dependency lock file
- Finding latest version of hashicorp/vcd...
- Using previously-installed vmware/vcd v3.7.0
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/vcd: provider registry registry.terraform.io does not have a    
│ provider named registry.terraform.io/hashicorp/vcd
│
│ Did you intend to use vmware/vcd? If so, you must specify that source address in each module which requires that provider. To see which  
│ modules are currently depending on hashicorp/vcd, run the following command:
│     terraform providers

### Additional Context

if possible kindly provide me resolution or provide some snippet. 

### References

Dont know

**Comment by jbardin** [comment]
Hello,

Each Terraform module must declare its own provider requirements, (see [Provider Version Constraints in Modules](https://developer.hashicorp.com/terraform/language/modules/develop/providers#provider-version-constraints-in-modules))

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
