### ISSUE TITLE
Local files are not created when using Terraform Cloud

### ISSUE THREAD

**Issue by nibblesnbits** [hashicorp/terraform#32245]
### Terraform Version

```shell
Terraform v1.3.4
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.27.0
+ provider registry.terraform.io/digitalocean/digitalocean v2.23.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/integrations/github v5.8.0

Your version of Terraform is out of date! The latest version
is 1.3.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
terraform {
  cloud {
    organization = "mycompany"

    workspaces {
      name = "digitalocean"
    }
  }
}


resource "local_file" "env" {
  filename = "${path.module}/.env"
  content  = <<-EOT
    DO_TOKEN=${var.do_token}
    PROD_DB_NAME=${module.prod.db_name}
    PROD_DB_ID=${module.prod.db_id}
    STAGE_DROPLET_ID=${module.stage.droplet_id}
    PROD_DROPLET_ID=${module.prod.droplet_id}
    STAGE_DB_HOST=${module.stage.db_host}
    STAGE_WEB_HOST=${var.stage_domain}
  EOT
}
```

### Debug Output

https://gist.github.com/nibblesnbits/76f0dc043d6c4073d8ca0366d27763e5

### Expected Behavior

I should see a .env file generated on my local machine.

### Actual Behavior

No file is generated

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

This was working fine when using local state.  As soon as I moved to Terraform Cloud, it stopped working.

**Comment by jbardin** [comment]
Hi @nibblesnbits,

When you are using Terraform Cloud, Terraform is being executed on the cloud servers, so that is also where the `local` provider is being executed and all files will be relative to that process' location.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by nibblesnbits** [comment]
>We use GitHub issues for tracking bugs and enhancements, rather than for questions.

This is kind of insulting.  I feel like it's pretty reasonable that this be considered a bug, given the module's name and the fact that your [documentation](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file) has NO mention of this not functioning the same when used with Terraform cloud.

It would be a reasonable request to be able to still create local files when executing the tool locally.  Or at the very least, update the docs to make this clear.

**Comment by jbardin** [comment]
My apologies, no offense intended here. These types of questions are usually better sorted out in the discussion forums, where any misunderstands about how Terraform operates can first be addressed. The `local` provider operates on files "local" to the execution context, which means your own machine when running Terraform there, or a cloud server when running in TFC. If the files were not handled locally relative to the executable's working directory, Terraform and the other provider processes would not be able to locate them either.

If you feel the `local` provider should have an exception in the documentation to highlight this, you can file a request [here](https://github.com/hashicorp/terraform-provider-local/issues). There is a note in the docs already about running the provider on different machines, where files created are not going to be persisted between runs. While this provider allows for some creative patterns to be applied, it is generally not a good idea to try and manage files which are not checked in as part of the configuration for this reason.
