### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.32.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by MATTHEWTAYLOR1995** [hashicorp/terraform#32248]
### Terraform Version

```shell
Terraform v1.2.9
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Error: Plugin did not respond
│ 
│   with module.swa["<name>"].azurerm_cdn_frontdoor_rule.main[0],
│   on ../Modules/Static_Webapp/front_door.rules.main.tf line 2, in resource "azurerm_cdn_frontdoor_rule" "main":
│    2: resource "azurerm_cdn_frontdoor_rule" "main" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.32.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x106a9d644]

goroutine 2469 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/frontdoorruleactions.FlattenCdnFrontDoorRouteConfigurationOverrideAction({0x1400301c048?, {0x14001c500c0?, 0x14001aed870?}})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:442 +0xc4
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.flattenFrontdoorDeliveryRuleActions(0x14001a25d40)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:1185 +0xed0
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.resourceCdnFrontDoorRuleRead(0x1400251a100, {0x1084423c0?, 0x140031ee000?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:710 +0x4bc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x108e95628?, {0x108e95628?, 0x140024febd0?}, 0xd?, {0x1084423c0?, 0x140031ee000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:712 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000ab35e0, {0x108e95628, 0x140024febd0}, 0x1400250f2b0, {0x1084423c0, 0x140031ee000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400071d5d8, {0x108e95628?, 0x140024feb10?}, 0x14002378700)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:613 +0x40c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140011ef900, {0x108e95628?, 0x140024fe600?}, 0x14002b461e0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:747 +0x39c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x108a98a40?, 0x140011ef900}, {0x108e95628, 0x140024fe600}, 0x14002b46180, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002a8c40, {0x108ea7cd0, 0x14000eec1a0}, 0x140024e58c0, 0x1400166dd70, 0x10d0732d0, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1283 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x140002a8c40, {0x108ea7cd0, 0x14000eec1a0}, 0x140024e58c0, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1620 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.47.0/server.go:922 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.47.0/server.go:920 +0x298

Error: The terraform-provider-azurerm_v3.32.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Terraform plan to succeed as normal

### Actual Behavior

Error: The terraform-provider-azurerm_v3.32.0_x5 plugin crashed!

Stack trace from the terraform-provider-azurerm_v3.32.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x108ab5644]

goroutine 1611 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/frontdoorruleactions.FlattenCdnFrontDoorRouteConfigurationOverrideAction({0x1400233a450?, {0x14002b92180?, 0x14002b85a10?}})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/frontdoorruleactions/cdn_frontdoor_rule_actions.go:442 +0xc4
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.flattenFrontdoorDeliveryRuleActions(0x1400233a3a8)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:1185 +0xed0
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.resourceCdnFrontDoorRuleRead(0x1400142bf80, {0x10a45a3c0?, 0x14001382000?})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:710 +0x4bc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x10aead628?, {0x10aead628?, 0x140021c8cc0?}, 0xd?, {0x10a45a3c0?, 0x14001382000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:712 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000a43340, {0x10aead628, 0x140021c8cc0}, 0x140022e35f0, {0x10a45a3c0, 0x14001382000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140015f09a8, {0x10aead628?, 0x140021c8c00?}, 0x14001ef47c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:613 +0x40c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400162b400, {0x10aead628?, 0x140021c86f0?}, 0x1400011f3e0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:747 +0x39c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x10aab0a40?, 0x1400162b400}, {0x10aead628, 0x140021c86f0}, 0x1400011f380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002aaa80, {0x10aebfcd0, 0x14000554680}, 0x140021718c0, 0x1400172a750, 0x10f08b2d0, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1283 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x140002aaa80, {0x10aebfcd0, 0x14000554680}, 0x140021718c0, 0x0)
        google.golang.org/grpc@v1.47.0/server.go:1620 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.47.0/server.go:922 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.47.0/server.go:920 +0x298

### Steps to Reproduce

`terraform init`
`terraform plan`

### Additional Context

Initially it was working fine... I then went away for a few hours and this error started occurring... 

I've tried running it else where and the same thing occurs.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
