### ISSUE TITLE
Copy cluster db snapshots between regions or create db instance from cluster db snapshot from another region

### ISSUE THREAD

**Issue by mirzazeyrek** [hashicorp/terraform#32259]
### Terraform Version

```shell
Terraform v1.3.3
on linux_amd64
```

### Use Cases

When copying a cluster db snapshot cross regions
Also creating a new db instance from a snapshot in another region

### Attempted Solutions

I tried to use db_snapshot_copy

https://registry.terraform.io/providers/hashicorp/aws/4.15.1/docs/resources/db_snapshot_copy

But it can not find the cluster db snapshots.

The command is available through aws cli and it works:

```
aws rds copy-db-cluster-snapshot 
--region eu-central-1 
--source-db-cluster-snapshot-identifier "arn:aws:rds:eu-west-1:..."
--target-db-cluster-snapshot-identifier "arn:aws:rds:eu-central:..."
```

### Proposal

Adding a cluster_db_snapshot_copy method similar to db_snapshot_copy.

### References

https://stackoverflow.com/questions/73316659/how-to-copy-rds-cluster-snapshot-with-terraform-aws

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
