### ISSUE TITLE
Add golangci-lint to keep code quality

### ISSUE THREAD

**Issue by sivchari** [hashicorp/terraform#32266]
### Terraform Version

```shell
Terraform v1.4.0-dev
on darwin_arm64
```

### Use Cases

Go is a very easy language to analyze ast as it has a standard static analysis tool (go vet). There are also tools such as golangci-lint that provide a variety of linters. This is not a minority setting, but one that is also provided by various well-known libraries, including Kubernetes.
In fact, even terraform has potential bugs like [#32261](https://github.com/hashicorp/terraform/pull/32261) that have gone unnoticed until now. And such bugs may still exist. As we develop more features in the future, such bugs could have a significant impact on users and, more importantly, on the company. Therefore, by introducing linter at this time, the quality of the code can be assured at the level of static analysis.

### Attempted Solutions

None.

## Loadmap

- [ ] Discuss the introduction of golangci-lint
- [ ] Select which linter to enable
- [ ] Set the linter setting and fix lint errors
- [ ] Add a new workflow to check by linter

**Comment by kmoe** [comment]
Thanks for this and for https://github.com/hashicorp/terraform/pull/32261 - I would have thought staticcheck would have caught that one, but I haven't checked. We'll discuss the options for further linting.

**Comment by sivchari** [comment]
I want to discuss with @kmoe and core maintainers. Where should I start?

**Comment by crw** [comment]
Thanks @sivchari. At the moment this is on the backlog. Feel free to leave any appropriate comments on this issue.
