### ISSUE TITLE
source_access_configuration uri value from parameter store 

### ISSUE THREAD

**Issue by smitamoonka** [hashicorp/terraform#32267]
### Terraform Version

```shell
Terraform v1.3.4
on darwin_arm64
```

### Use Cases

Currently for Self Managed Apache Kafka or MSK the resource "aws_lambda_event_source_mapping" source_access_configuration accepted the uri value only from secretmanager which is the arn value. I could not find any documentation or any example for paramter store. All the places it has mentioned as secret manager, is there any way we can utilize paramter store instead of secret manager. Or is there any other alternate we can provide server url, username nad password from parameter store in configuration?

Thanks for the help!

### Attempted Solutions

I tried searching an example for parameter store but could not find any

### Proposal

Please point me to the configuration for event source mapping configuration with parameter store

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
