### ISSUE TITLE
Documented feature datadog_user_config does not exist

### ISSUE THREAD

**Issue by spetssami** [hashicorp/terraform#32277]
### Terraform Version

```shell
Terraform v1.3.5
on darwin_amd64
+ provider registry.terraform.io/aiven/aiven v3.2.1
+ provider registry.terraform.io/datadog/datadog v3.15.1
+ provider registry.terraform.io/hashicorp/google v4.36.0
+ provider registry.terraform.io/hashicorp/google-beta v4.36.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/vancluever/acme v2.10.0
```

### Affected Pages

https://registry.terraform.io/providers/aiven/aiven/latest/docs/resources/service_integration

### What is the docs issue?

The datadog_user_config does not exist. When attempting to implement it, user gets the following error
```
│ Error: Unsupported block type
│ 
│   on aiven-database.tf line 138, in resource "aiven_service_integration" "datadog_pg":
│  138:     datadog_user_config {
│ 
│ Blocks of type "datadog_user_config" are not expected here.
```

### Proposal

Remove the documentation for datadog_user_config or add the documented functionality.

**Comment by kmoe** [comment]
This is a provider issue and looks like it should be filed at https://github.com/aiven/terraform-provider-aiven/issues.
