### ISSUE TITLE
refer to environment variable more easily in config file or .tf file 

### ISSUE THREAD

**Issue by BinaryWorld2099** [hashicorp/terraform#32275]
### Terraform Version

```shell
Terraform v1.2.8
```

### Use Cases

I have my terraform project and there is a config file
![image](https://user-images.githubusercontent.com/106383882/203499840-63376721-7b1b-47bd-871c-444d4a117406.png)

which read the config file value in terraform project
![image](https://user-images.githubusercontent.com/106383882/203499980-948729af-7e41-423d-99d5-a6107230a7f9.png)

azure key vault is sensitive value don't want to store plain text and want to use environment variable 
but find it really hard to use environment variable in terraform 

![image](https://user-images.githubusercontent.com/106383882/203500247-e862d78c-d3db-4304-b431-0e11e49ecdca.png)

### Attempted Solutions

![image](https://user-images.githubusercontent.com/106383882/203500361-70ac4720-47ed-4233-aaeb-e39aa6d54d1d.png)
try refer to environment variable, doesn't working
the azure secret value is exactly  "${TEST}"  rather than the environment variable

### Proposal

refer to environment variable more easily in config file or .tf file

**Comment by BinaryWorld2099** [comment]
It there any way retrieve environment variable in my config file?

**Comment by BinaryWorld2099** [comment]
try export local variable TF_VAR_TEST=abc
in the config file
![image](https://user-images.githubusercontent.com/106383882/203691457-74568d24-fc66-402f-857d-5708f6969f4d.png)
 secretValue: "${var.TEST}"
 secretValue: var.TEST

seems till not working

**Comment by crw** [comment]
Hello @BinaryWorld2099, this appears to be a question with Terraform usage rather than a bug report or feature request. If you have questions about Terraform, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by BinaryWorld2099** [comment]
Dear Craig,
Thank you very much,  would use the community forum
<https://discuss.hashicorp.com/c/terraform-core/27>

Craig Wright ***@***.***> 於 2022年11月30日 週三 上午8:27寫道：
