### ISSUE TITLE
cannot use snapshotFS{} (value of type snapshotFS) as type afero.Fs in variable declaration

### ISSUE THREAD

**Issue by SunMinghui19** [hashicorp/terraform#32282]
### Terraform Version

```shell
github.com/hashicorp/terraform@v0.13.0
```

### Terraform Configuration Files

no terraform config

### Debug Output

no

### Expected Behavior

compile successfully

### Actual Behavior

occurred the follow problem
![image](https://user-images.githubusercontent.com/55644074/203704174-d3d3db11-11f1-443f-92c6-874b21780c9b.png)

### Steps to Reproduce

refer to https://github.com/pulumi/pulumi-tf-provider-boilerplate
1、make prepare NAME=foo REPOSITORY=github.com/SunMinghui19/pulumi-foo
2、cd provider && go mod tidy && cd 
3、make tfgen（occurred error）

**Comment by alisdair** [comment]
This does not appear to be a bug in Terraform, but instead in [pulumi/pulumi-tf-provider-boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate). I suggest filing the issue upstream. Thanks!
