### ISSUE TITLE
Terraform complains of "missing required argument" when trying to pull module from specific Git branch

### ISSUE THREAD

**Issue by tdevopsottawa** [hashicorp/terraform#32292]
### Terraform Version

```shell
Terraform v1.2.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
+ provider registry.terraform.io/hashicorp/azuread v2.30.0
+ provider registry.terraform.io/hashicorp/azurerm v3.27.0
+ provider registry.terraform.io/hashicorp/github v5.9.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/strongdm/sdm v3.5.1

Your version of Terraform is out of date! The latest version
is 1.3.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```
module "datadog" {
  source = "git@github.com:redacted/redacted?ref=Az_datadog"
}
```

### Debug Output

https://gist.github.com/tdevopsottawa/50e583f7a88e50ab560f57e86e7146bf

### Expected Behavior

Terraform plan should output what to do based on my code

### Actual Behavior

│ Error: Missing required argument
│
│   on k8s-datadog.tf line 1, in module "datadog":
│    1: module "datadog" {
│
│ The argument "filename" is required, but no definition was found.
╵

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

If I try a module reference as HEAD ("git@github.com:redacted/redacted?ref=HEAD") it works fine. It only fails if I try to change "HEAD" to an actual branch name. It doesn't matter what branch, every branch I try fails with this error.

**Comment by kmoe** [comment]
Thanks for the bug report. This behaviour sounds odd. 
When you change the module source to `"git@github.com:redacted/redacted?ref=Az_datadog"` and run init, Terraform should detect that the module source has changed, download the new ref, and log something like the following:
```
Initializing modules...
Downloading git::ssh://git@github.com:redacted/redacted?ref=Az_datadog for datadog...
- datadog in .terraform/modules/datadog
```

The module source code is downloaded to `terraform/modules/datadog`, and Terraform then determines the input variables declared by the module. The arguments in the module call (`module` block) are then validated against these. 

Do you see the module source code you expect to see in `terraform/modules/datadog`? Does this module declare any input variables at all?

**Comment by gitbrad** [comment]
I am seeing this issue too with Terraform 1.3.6. I have several modules of the same git repo location and branch ref and five of six module sources are working as intended. One of the modules with the desired branch source keeps retrieving HEAD as mentioned above while all other modules behave as expected. Terraform init clearly shows that one of the modules is not downloading from the expected (and correctly configured) git branch, similar to the below sanitized code. Of note is that I have updated the module source and these are not new modules 🤔 

```
Downloading git::ssh://git@some.server/tm/some-repo.git for moduleName-one...
- moduleName-one in .terraform/modules/moduleName-one
Downloading git::ssh://git@some.server/tm/some-repo.git?ref=someBranch for moduleName-two...
- moduleName-two in .terraform/modules/moduleName-two
Downloading git::ssh://git@some.server/tm/some-repo.git?ref=someBranch for moduleName-three...
- moduleName-three in .terraform/modules/moduleName-three
Downloading git::ssh://git@some.server/tm/some-repo.git?ref=someBranch for moduleName-four...
- moduleName-four in .terraform/modules/moduleName-four
Downloading git::ssh://git@some.server/tm/some-repo.git?ref=someBranch for moduleName-five...
- moduleName-five in .terraform/modules/moduleName-five
Downloading git::ssh://git@some.server/tm/some-repo.git?ref=someBranch for moduleName-six...
- moduleName-six in .terraform/modules/moduleName-six
```

**Comment by kroussou** [comment]
@tdevopsottawa Never had issues with this (terraform v.0.15.6 to v1.3.4). Look for typo in URL, make sure that branch exists on remote, try commit SHA instead of branch name

**Comment by tdevopsottawa** [comment]
@kroussou thanks

Oddly, after I changed to another Git repo entirely (ie. not just another branch) did the problem resolve. Never figured out exactly what, but it was something wrong on GitHub's end.

@gitbrad hope that lead helps
