### ISSUE TITLE
Using `for each` failed when there was only a single Subnet during Load Balancer creation

### ISSUE THREAD

**Issue by Micah-Shallom** [hashicorp/terraform#32290]
### Terraform Version

```shell
$ terraform version
Terraform v1.2.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.40.0

Your version of Terraform is out of date! The latest version
is 1.3.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb

### What is the docs issue?

![act1](https://user-images.githubusercontent.com/64049432/203875352-3632a605-9a24-4fe8-b609-6195a5fad36c.jpg)

This use of for each fails since we are dealing with just a single subnet created.

### Proposal

To fix this, a splat operator can be used to fix the issue
![act2](https://user-images.githubusercontent.com/64049432/203875429-164bf938-a72b-41c4-933d-ac4af032aaf6.jpg)

**Comment by McGon-Fid** [comment]
I will work on this and submit a PR later.

**Comment by McGon-Fid** [comment]
I cannot seem to locate this piece of code within the repo. Can you clarify where the change is required?

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
