### ISSUE TITLE
Default values of optional keys inside nested objects are not visible

### ISSUE THREAD

**Issue by lambohamp** [hashicorp/terraform#32291]
### Terraform Version

```shell
`1.3.4`
```

### Terraform Configuration Files

```
variable "dns" {
  type = object({
    id = string
    k8s = optional(object({
      ingress = optional(object({
        namespace = optional(string, "default")
      }))
    }))
  })
}

output "vars" {
  value = var.dns
}

---

module "dns" {
  source = "./module"

  dns = {
    id = ""
  }
}

output "dns" {
  value = module.dns.vars
}

```

### Debug Output

-

### Expected Behavior

```
Outputs:

dns = {
  "id" = ""
  "k8s" = {
    "ingress" = {
      "namespace" = "default"
    }
  }
}
```

### Actual Behavior

```
Outputs:

dns = {
  "id" = ""
  "k8s" = null /* object */
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

Hi. I noticed that default values inside an optional nested object are not visible to Terraform (please see the code example above).

However, if I add a default value for the object itself, the default values become visible as well, e.g.:

```
variable "dns" {
  type = object({
    id = string
    k8s = optional(
      object({
        ingress = optional(object({
          namespace = optional(string, "default")
          }),
          {}
        )
    }))
  })
}

...

Outputs:

dns = {
  "id" = ""
  "k8s" = {
    "ingress" = {
      "namespace" = "default"
    }
  }
}
```

I am wondering if it is an expected behavior or there is something wrong. I am sorry if it's a duplicate issue, I failed to find any similar ones.

**Comment by alisdair** [comment]
Hi @lambohamp, thanks for reporting this. This is the designed behaviour—if you don't specify a default value for an attribute of type `optional(object({…}))`, and no object is given in the variable input value, the attribute value will evaluate to `null`. As you found, you can specify an empty object if all attributes have defaults, to get the behaviour you're looking for.
