### ISSUE TITLE
Browser Error showing "Page Not Found" when visiting any "latest" docs by explicit version number

### ISSUE THREAD

**Issue by Xiphoseer** [hashicorp/terraform#32300]
### Terraform Version

irrelevant as this is a https://registry.terraform.io issue, but
```shell
$ terraform --version
Terraform v1.3.5
on windows_amd64
```

### Affected Pages

All `https://registry.terraform.io/providers/{source}/{version}/docs/resources/{resource}`

where:

- `{source}` is a valid provider, e.g. `hashicorp/azurerm`
- `{version}` its latest version, e.g. `3.33.0`
- `{resource}` a valid resource, e.g. `resource_group`

Examples (at the time of writing):
- https://registry.terraform.io/providers/hashicorp/azurerm/3.33.0/docs/resources/resource_group
- https://registry.terraform.io/providers/hashicorp/google/4.44.1/docs/resources/app_engine_application

### What is the docs issue?

The automatic redirect to `https://registry.terraform.io/providers/{source}/latest/docs` that triggers sucessfully in other cases (e.g. https://registry.terraform.io/providers/hashicorp/azurerm/3.33.0/docs) does not happen and a "Page Not Found" is displayed, even though the menu entry exists and is correct.

Furthermore, no links on that page actually work, presumably because the ember router crashed. There is an error in the Browser console for that page saying: `Error while processing route: providers.name.version.docs.doc e.reload is not a function TypeError: e.reload is not a function`, c.f. [registry.terraform.io-1669639292025.log](https://github.com/hashicorp/terraform/files/10103846/registry.terraform.io-1669639292025.log)

![Screenshot_20221128_135441](https://user-images.githubusercontent.com/14206221/204282885-2148f8df-1762-4f8f-9062-f6f9070ee54e.png)

I can reproduce this issue in both MS Edge (i.e. Chromium; `Version 107.0.1418.56 (Official Build) (64-Bit)`) and Firefox (`107.0 (64-Bit)`).

### Proposal

This seems like a bug in the registry web-frontend, independent of the provider docs in question and presumably needs to be fixed there.

### References

- Might be related to #32040.
- I discovered this issue through a link generated by https://terraform-docs.io

**Comment by crw** [comment]
Thanks for this report. I will make the Registry team aware of this issue. As it is not an issue with Terraform core or CLI, I will close this issue, but if there are any updates via the registry team, I'll update in this thread. Thanks again for this report!

**Comment by Xiphoseer** [comment]
Seems to be fixed now, thank you!

**Comment by crw** [comment]
Great! I didn't get that update internally so thanks for letting me know! 😄
