### ISSUE TITLE
crash from null nested blocks when included in `ignore_changes`

### ISSUE THREAD

**Issue by farnsworth2008** [hashicorp/terraform#32310]
### Terraform Version

```shell
Terraform v1.3.5
on linux_arm64
+ provider registry.terraform.io/hashicorp/aws v4.42.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
```

### Terraform Configuration Files

```terraform
resource "kubernetes_job" "this" {
  # stuff here
}
```

### Debug Output

N/A

### Expected Behavior

Terraform should not crash. The job should be replaced

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
[1]: https://github.com/hashicorp/terraform/issues
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
value is null
goroutine 3646 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2144f60, 0x2b44e90})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/zclconf/go-cty/cty.Value.LengthInt({{{0x2b6dbb0?, 0xc002a60b60?}}, {0x0?, 0x0?}})
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/value_ops.go:1066 +0x1e5
github.com/hashicorp/terraform/internal/plans/objchange.assertPlanValid(0xc001f60320, {{{0x2b6dc20?, 0xc003f3afc0?}}, {0x221c7a0?, 0xc006ea5ec0?}}, {{{0x2b6dc20?, 0xc003ea9810?}}, {0x221c7a0?, 0xc006ea4480?}}, {{{0x2b6dc20, ...}}, ...}, ...)
	/home/circleci/project/project/internal/plans/objchange/plan_valid.go:105 +0x9e5
github.com/hashicorp/terraform/internal/plans/objchange.assertPlanValid(0xc001f602d0, {{{0x2b6dc20?, 0xc003f3b010?}}, {0x221c7a0?, 0xc006ea5f20?}}, {{{0x2b6dc20?, 0xc003ea9880?}}, {0x221c7a0?, 0xc006ea44e0?}}, {{{0x2b6dc20, ...}}, ...}, ...)
	/home/circleci/project/project/internal/plans/objchange/plan_valid.go:127 +0x2eb8
github.com/hashicorp/terraform/internal/plans/objchange.assertPlanValid(0xc001f41a10, {{{0x2b6dc20?, 0xc003f3b110?}}, {0x221c7a0?, 0xc006efa000?}}, {{{0x2b6dc20?, 0xc003ea9920?}}, {0x221c7a0?, 0xc006ea45a0?}}, {{{0x2b6dc20, ...}}, ...}, ...)
	/home/circleci/project/project/internal/plans/objchange/plan_valid.go:127 +0x2eb8
github.com/hashicorp/terraform/internal/plans/objchange.AssertPlanValid(...)
	/home/circleci/project/project/internal/plans/objchange/plan_valid.go:36
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).plan(0xc002616000, {0x2b84098, 0xc0019660e0}, 0x0, 0xc002fabda0, 0x0, {0x0, 0x0, 0x0?})
	/home/circleci/project/project/internal/terraform/node_resource_abstract_instance.go:857 +0x19fe
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0025eedc0, {0x2b84098, 0xc0019660e0})
	/home/circleci/project/project/internal/terraform/node_resource_plan_instance.go:223 +0xdae
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x2b84098?, 0xc0019660e0?}, 0x0?)
	/home/circleci/project/project/internal/terraform/node_resource_plan_instance.go:60 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0033dd1d0, {0x2b84098, 0xc0019660e0}, {0x7f5d5c0d2ab8, 0xc0025eedc0})
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x256cb40, 0xc0025eedc0})
	/home/circleci/project/project/internal/terraform/graph.go:[74](https://git.rxcorp.com/global/xg/acoe/sre/birch/roots/acoe-dev/ai/acoe-dev-asset-intel-dev-1a-site/-/jobs/2943929#L74) +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000d41ce0, {0x256cb40, 0xc0025eedc0}, 0xc0025ef100)
	/home/circleci/project/project/internal/dag/walk.go:3[81](https://git.rxcorp.com/global/xg/acoe/sre/birch/roots/acoe-dev/ai/acoe-dev-asset-intel-dev-1a-site/-/jobs/2943929#L81) +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0xf65

### Steps to Reproduce

This crash occurs at random times when replacing k8 jobs

**Comment by kmoe** [comment]
Thanks for the bug report. Please provide some Terraform configuration that reproduces this issue, and/or a debug log. 

It's possible this is an issue with the Kubernetes provider, so you may want to open a bug report there: https://github.com/hashicorp/terraform-provider-kubernetes

This issue looks similar, though without narrowing down which resource causes your crash, it's hard to tell. https://github.com/hashicorp/terraform-provider-kubernetes/issues/1552

**Comment by jbardin** [comment]
Yes, the configuration will be important here, because the crash happens when handling the configuration value in Terraform. I suspect there is an `ignore_changes` in there, which is forcing Terraform form to use an invalid value from the provider as configuration, since decoding a block should never directly result in a null value. So while there may be a bug in the provider, it is slipping through the validation somehow to cause a crash in Terraform, which we would like to track down.

Thanks!

**Comment by jbardin** [comment]
Thanks @farnsworth2008, I think the `ignore_changes` there is the key. We may not be able to reproduce the exact state from the kubernetes provider, but the this config should give us enough clues to try and replicate the misbehavior locally.

**Comment by jbardin** [comment]
combining with #31536
