### ISSUE TITLE
Missing fields with complex elements in schema output

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform#32312]
### Terraform Version

```shell
Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/andrewbaxter/stripe v0.0.17
+ provider registry.terraform.io/hashicorp/aws v4.39.0
+ provider registry.terraform.io/kreuzwerker/docker v2.23.1
```

### Terraform Configuration Files

Unrelated to stack

### Debug Output

There's nothing in the logs related to schema output

### Expected Behavior

The docker `container` resource should have a `ports` field

### Actual Behavior

The `ports` field is missing

### Steps to Reproduce

Set up a tf config with the docker provider above, run `terraform init`, then `terraform providers schema -json`

### Additional Context

This also happens with `tiers` in the `price` resource in my stripe provider above.  I triple checked that the `ports` field actually exists in the provider, at least as far as code goes. `ports` is pretty critical to docker so I'd be surprised if it got accidentally removed.

I wasn't able to find any other issues related to this.

**Comment by jbardin** [comment]
Hi @andrewbaxter,

Can you show an example of exactly what resources, blocks and attributes you are not finding in your providers' schemas? The docker provider linked here does not have any attribute named "port" in the provider or any of its resources, and in the schema output for your provider I can see some attributes named "tiers" and "price".

Thanks!

**Comment by jbardin** [comment]
The top level `"ports"` in the `docker_container` is a block, not an attribute. In `jq` syntax the path would be `.provider_schemas["registry.terraform.io/kreuzwerker/docker"].resource_schemas.docker_container.block.block_types.ports`

**Comment by andrewbaxter** [comment]
Ah thanks, you're absolutely right! Sorry, I'm not sure how I missed that.

Closing.
