### ISSUE TITLE
ANSI Escape Codes printed when output is not terminal

### ISSUE THREAD

**Issue by sergiuser1** [hashicorp/terraform#32313]
### Terraform Version

```shell
Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/disaster37/elasticsearch v7.16.2
+ provider registry.terraform.io/hashicorp/azuread v2.30.0
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Terraform Configuration Files

```terraform
resource "azuread_group_member" "atlantis_ci" {
  group_object_id  = azuread_group.tim.id
  member_object_id = azuread_user.atlantis_ci.id
}


```

### Debug Output

https://gist.github.com/sergiuser1/470590751ad3680a94bde0d44678048e

### Expected Behavior

No escape character should be printed. You can't see them on the terminal, since they're immediately succeeded by a "reset" code which nullifies them.

### Actual Behavior

The command `terraform state show` outputs ANSI escape characters when the output is not a terminal:
```terraform
# azuread_group_member.atlantis_ci:
resource "azuread_group_member" "atlantis_ci" {
    [1m[0mgroup_object_id[0m[0m  = "REMOVED"
    [1m[0mid[0m[0m               = "REMOVED"
    [1m[0mmember_object_id[0m[0m = "REMOVED"
}[0m[0m

```

### Steps to Reproduce

1. `terraform init`
2. `terraform state show ...`

**Comment by alisdair** [comment]
Hi @sergiuser1. This is the expected behaviour of Terraform, and we can't easily change this now as it would break compatibility with those users who depend on it.

You can disable Terraform's color output using the `-no-color` option: `terraform state show -no-color azuread_group_member.atlantis_ci`.
