### ISSUE TITLE
AWS S3 bucket object does not allow setting Content-Type

### ISSUE THREAD

**Issue by dbroockman** [hashicorp/terraform#3231]
Because of this, when I upload a .html file, its type is set as ```binary/octet-stream``` and it downloads my webpage instead of rendering it.

**Comment by stack72** [comment]
@dbroockman I just opened a PR that will fix this for you #3265

Hopefully it will get picked up soon

**Comment by stack72** [comment]
@catsby this can also be closed as my PR was merged for it

**Comment by catsby** [comment]
Thanks for the follow up!
