### ISSUE TITLE
Custom linked service type "DB2" gets sent as type "LinkedService" causing an error.

### ISSUE THREAD

**Issue by Thegsgs** [hashicorp/terraform#32342]
### Terraform Version

Trying to create a custom linked service of type DB2 which is a valid connector type according to Microsoft documentation, results in "Invalid type" error because type is changed to "LinkedService" instead which is not a valid connector type.

Code block:

```shell
resource "azurerm_data_factory_linked_custom_service" "AS400_DB2" {
  name                 = "LS_Source_AS400"
  data_factory_id      = module.data_factory.data_factory_id
  type                 = "DB2"
  description          = "test description"
  type_properties_json = <<JSON
{
  "connectionString":"*****"
}
JSON
}
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Not relevant

### Expected Behavior

Custom liked service of type DB2

### Actual Behavior

Error:
```
datafactory.LinkedServicesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Failed to encrypt sub-resource payload {\r\n  \"Id\": \"/subscriptions/***/resourceGroups/HRL-RG-Dev-DataCloud-001/providers/Microsoft.DataFactory/factories/hrl-hdc-adf-dev001/linkedservices/LS_Source_AS400\",\r\n  \"Name\": \"LS_Source_AS400\",\r\n  \"Properties\": {\r\n    \"description\": \"test description\",\r\n    \"type\": \"LinkedService\",\r\n    \"typeProperties\": {\r\n      \"connectionString\": \"********************\"\r\n    }\r\n  }\r\n} and error is: Invalid type 'LinkedService' is provided in 'linkedServices'. Please correct the type in payload and retry.." Target="/subscriptions/***/resourceGroups/HRL-RG-Dev-DataCloud-001/providers/Microsoft.DataFactory/factories/hrl-hdc-adf-dev001/linkedservices/LS_Source_AS400"
```

### Steps to Reproduce

1.terraform init
2.terraform apply

### Additional Context

Trying the custom linked service resource with any other type works perfectly normal.

**Comment by alisdair** [comment]
Hello!

We use GitHub issues for tracking bugs and enhancements, rather than for questions. This also does not appear to be a Terraform core related issue, and is either a bug in the Azure provider or a problem with the Azure service itself.

As a result I'm going to close this issue. Please do feel free to [ask your question in the Terraform Azure provider community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). Thanks!

**Comment by Thegsgs** [comment]
Sorry my bad!
