### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.34.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by bpriyas92** [hashicorp/terraform#32348]
### Terraform Version

```shell
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.34.0
```

### Terraform Configuration Files

```module "compute_cluster" {
  for_each                             = var.clusters
  source                               = "../../../lib/compute_cluster"
  compute_cluster_name                 = each.value.compute_cluster_name
  location                             = each.value.location
  priority                             = each.value.vm_priority
  vm_size                              = each.value.vm_size
  workspace_id                         = each.value.workspace_id
  subnet_id                            = each.value.subnet_ids
  min_node_count                       = each.value.min_node_count
  max_node_count                       = each.value.max_node_count
  scale_down_nodes_after_idle_duration = each.value.scale_down_nodes_after_idle_duration
  identity                             = each.value.vm_identity
  username                             = each.value.username
  ssh_key                              = each.value.ssh_key
```

### Debug Output

Error: Request cancelled
│ 
│   with module.compute_cluster["aml-cluster"].azurerm_machine_learning_compute_cluster.compute_cluster,
│   on ../../../lib/compute_cluster/main.tf line 1, in resource "azurerm_machine_learning_compute_cluster" "compute_cluster":
│    1: resource "azurerm_machine_learning_compute_cluster" "compute_cluster" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-azurerm_v3.34.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 39 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning.expandUserAccountCredentials(...)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning/machine_learning_compute_cluster_resource.go:345
github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning.resourceComputeClusterCreate(0x0?, {0x5a6c2a0?, 0xc0020f4000})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning/machine_learning_compute_cluster_resource.go:182 +0x1954
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x6c65bc0?, {0x6c65bc0?, 0xc000753fb0?}, 0xd?, {0x5a6c2a0?, 0xc0020f4000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0011820e0, {0x6c65bc0, 0xc000753fb0}, 0xc0016e3040, 0xc00183ca80, {0x5a6c2a0, 0xc0020f4000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00030d9c8, {0x6c65bc0?, 0xc000753e90?}, 0xc00175c410)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000e24500, {0x6c65bc0?, 0xc00117b230?}, 0xc00182e150)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x60db9e0?, 0xc000e24500}, {0x6c65bc0, 0xc00117b230}, 0xc00182e000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e21e0, {0x6c77520, 0xc0016981a0}, 0xc001d4e000, 0xc001534f60, 0xade10c0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001e21e0, {0x6c77520, 0xc0016981a0}, 0xc001d4e000, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.34.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

terraform apply should have deployed infrastructure

### Actual Behavior

terraform apply failed

### Steps to Reproduce

1. terrafrom apply

**Comment by alisdair** [comment]
Thanks for the report! This is a bug in the AzureRM provider, not Terraform core. Please [file a bug on the AzureRM provider repository](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) so that its maintainers can investigate.
