### ISSUE TITLE
databricks cluster creation fails when public network is disabled and Noazuredatabricksrules selected

### ISSUE THREAD

**Issue by ShivaniThadiyan** [hashicorp/terraform#32346]
### Terraform Version

```shell
Version: 2.202.19
```

### Terraform Configuration Files

resource "databricks_cluster" "shared_autoscaling" {

  cluster_name            = "hbl-azure-ci-datalake-dbr-dev-Cluster02"

  spark_version           = "10.5.x-scala2.12"

 
  spark_conf       =      {
 
"spark.databricks.delta.preview.enabled" : "true"
"spark.databricks.cluster.profile" : "serverless"
"spark.databricks.passthrough.enabled" : "true"
"spark.databricks.pyspark.enableProcessIsolation" : "true"
"spark.databricks.repl.allowedLanguages" : "python,sql"
 
  }

  node_type_id            = "Standard_F16"

  driver_node_type_id     = "Standard_F16"

  autotermination_minutes = "60"

  autoscale {

    min_workers = 2

    max_workers = 10

  }

}

### Debug Output

databricks_cluster.cluster: Creating...
╷
│ Error: cannot create cluster: invalid character '<' looking for beginning of value
│ <!doctype html><html><head><meta... (487 more bytes)
│
│ with databricks_cluster.cluster,
│ on [main.tf](http://main.tf/) line 148, in resource "databricks_cluster" "cluster":
│ 148: resource "databricks_cluster" "cluster" {

### Expected Behavior

When we are enabling public network for databricks we are able to deploy the cluster using the same code but when we are using the private network same code throwing error.

### Actual Behavior

When we are enabling public network for databricks we are able to deploy the cluster using the same code but when we are using the private network same code throwing error.

### Steps to Reproduce

terraform init
terraform Plan
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
