### ISSUE TITLE
"SubscriptionDoesNotSupportZone" when creating frontendIPConfigurations for LB in a non-Availability Zone region

### ISSUE THREAD

**Issue by mikecuison** [hashicorp/terraform#32340]
### Terraform Version

```shell
aztzmod/caf/azurerm module version 5.6.4
```

### Terraform Configuration Files

```terraform
...terraform config...
global_settings = {
  default_region = "region1"
  regions = {
    region1 = "westcentralus"
  }
  passthrough   = false
  random_length = 0
  prefixes      = []
  suffixes      = []
  use_slug      = true
}


# Create Resource Groups
resource_groups = {
  rg_network = {
    name = "network"
  }
}

vnets = {
  vnet_fw_region1 = {
    resource_group_key = "rg_network"
    region             = "region1"
    vnet = {
      name          = "hub-wcus-01"
      address_space = ["10.218.2.0/23"]
    }
    specialsubnets = {}
    subnets = {
      snet_trusted = {
        name = "trusted"
        cidr = ["10.218.2.0/27"]
      }
    }
  }
}

load_balancers = {
  lb1_region1 = {
    name                      = "ilb-wcus-001"
    sku                       = "Standard" 
    resource_group_key        = "rg_network"
    region                    = "region1"
    backend_address_pool_name = "backend-ilb"
    availability_zone         = "No-Zone"


    frontend_ip_configurations = {
      feip_lb1_config1_region1 = {
        name                          = "frontend-ilb-config1-wcus"
        vnet_key                      = "vnet_fw_region1"
        subnet_key                    = "snet_trusted"
        private_ip_address_allocation = "Dynamic"
        zones                         = null
      }
    }
  }
}


```

### Debug Output

https://gist.github.com/mikecuison/3a6ec19168acb3f6013a2ed60888dfb6.

### Expected Behavior

To provision...resources without any Zones (zoneless) - omit the zones field, per Terraform doc [https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide), 

### Actual Behavior

Regardless of the value specified to the "zone" property of the frontend_ip_configurations (tired null, [], "No-Zone" or by omitting it, the terraform apply results with a failure:

│ Error: creating/updating Load Balancer: (Name "lb-ilb-wcus-001" / Resource Group "rg-network"): network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SubscriptionDoesNotSupportZone" Message="Cannot create/move resource /subscriptions/<subscriptionGUID>/resourceGroups/rg-network/providers/Microsoft.Network/loadBalancers/lb-ilb-wcus-001/frontendIPConfigurations/frontend-ilb-config1-wcus which uses zone 1 since subscription <subscriptionGUID> does not support zone 1 in location westcentralus." Details=[]
│
│   with module.caf.module.load_balancers["lb1_region1"].azurerm_lb.lb,
│   on .terraform\modules\caf\modules\networking\load_balancers\load_balancers.tf line 11, in resource "azurerm_lb" "lb":
│   11: resource "azurerm_lb" "lb" {

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
