### ISSUE TITLE
The following tag namespaces / keys are not authorized or not found: TagNamespace does not exists.

### ISSUE THREAD

**Issue by SiddharthChoudhary** [hashicorp/terraform#32357]
### Terraform Version

```shell
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 1.3.6. You can update by downloading from www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
...terraform config...
```

resource "oci_core_instance" "linux_instance" {
  "defined_tags" = {"pvc_random.abc"="abc"}
}

### Debug Output

Provider version: 4.36.0, released on 2021-07-21. This provider is 72 update(s) behind to current. 
Service: Core Instance 
Error Message: The following tag namespaces / keys are not authorized or not found: TagNamespace pvc_random does not exists.
 

### Expected Behavior

It should work properly

### Actual Behavior

It breaks with the following error:-
Error Message: The following tag namespaces / keys are not authorized or not found: TagNamespace pvc_random does not exists.

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

Can anyone help me with this error?
I am trying to create and modify defined_tags for a resource. In this resource I have provided the defined_tags as mentioned above but it just fails with everything. Only god and TF developers know what shitty code they have written. 
You guys print the same error message for 100,000 errors. I am so frustrated at this point that I might give up with Terraform now.
Can someone help with this issue? or anyone know what could be wrong? Do I need to have this TagNamespace being created before using it in a resource? I tried that also actually anyway and it still fails.

**Comment by liamcervante** [comment]
Hi @SiddharthChoudhary, thanks for the report.

I think this is likely to be an error either with your config or in the Oracle provider, and not something Terraform Core can help you with. I would recommend posting your bug into the [terraform-provider-oci](https://github.com/oracle/terraform-provider-oci) repository.

As an aside, I would recommend updating your Terraform version as you will find less weirdness after the v1 release.
