### ISSUE TITLE
Mistake/ Manage Resources in Terraform State Doc

### ISSUE THREAD

**Issue by mckenzie-lim** [hashicorp/terraform#32350]
### Terraform Version

```shell
terraform -v
Terraform v1.3.6
on linux_amd64
```

### Affected Pages

https://developer.hashicorp.com/terraform/tutorials/certification-associate-tutorials-003/state-cli

### What is the docs issue?

![image](https://user-images.githubusercontent.com/71851249/206168910-f9279d45-ff3d-4db6-beca-27ea60991295.png)
![image](https://user-images.githubusercontent.com/71851249/206169084-ab0ec4f0-feaf-4550-b2a2-7ff36d2dbb14.png)

A simple mistake to be corrected :) 

### Proposal

Replace one of the output "public_ip" with output "instance_id"

**Comment by crw** [comment]
Thanks for this report! I'll let the docs team know. As this documentation is outside of the core repository, I am going to close this issue. Thanks again! We appreciate it.
