### ISSUE TITLE
Publish linux/arm64 platform hashicorp/terraform docker image

### ISSUE THREAD

**Issue by bbednarek** [hashicorp/terraform#32353]
### Terraform Version

```shell
1.2.6
1.3.6
```

### Use Cases

We have following script as a part of our Github Actions CI/CD pipeline which is ensuring correct formatting of terraform modules:

```
#!/usr/bin/env bash

export TF_VERSION=1.2.6
export WORKDIR="/var/tfmodules"

ARCH=$(uname -m)
if [[ "$ARCH" == "aarch64" ]] ; then
  PLATFORM="arm64"
elif [[ "$ARCH" == "x86_64" ]]; then
  PLATFORM="amd64"
else
  echo "Not supported architecture $ARCH"
  exit 1
fi

docker run --platform linux/${PLATFORM} --rm --entrypoint "" --volume ${PWD}:${WORKDIR} --workdir ${WORKDIR} hashicorp/terraform:${TF_VERSION} terraform fmt --check=true -recursive -diff
```

We use `hashicorp/terraform` docker image to be able to run any arbitrarily version of terraform and don't rely on the binary pre-installed on the Github runner machine or developer machine. 

Unfortunately only `linux/amd64` architecture is supported. We use `linux/arm64` as runners architecture. 

### Attempted Solutions

At the moment pipeline fails due to:
```
Digest: sha256:82a29cfa2b977cc471abb0872c73627642e14ff49fa3c24204ee98657e5318fb
Status: Downloaded newer image for hashicorp/terraform:1.2.6
docker: Error response from daemon: image with reference hashicorp/terraform:1.2.6 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.
See 'docker run --help'.
Error: Process completed with exit code 125.
```

### Proposal

Publish `linux/arm64` platform `hashicorp/terraform` docker image

**Comment by apparentlymart** [comment]
Hi @bbednarek! Thanks for this feature request.

I think this request is covered by the existing issue #25571 and so I'm going to close this one just to consolidate the discussion in one place.

Thanks!
