### ISSUE TITLE
Azurerm functionality: azurerm_mssql_managed_instance - Should support AAD Authentication Use Case

### ISSUE THREAD

**Issue by mkprizzle** [hashicorp/terraform#32361]
### Terraform Version

```shell
NA
```

### Use Cases

azurerm_mssql_managed_instance should support Azure Active Directory use case.

![image](https://user-images.githubusercontent.com/37881072/206537619-fda038ca-ee68-4d21-a459-b8e921ebdab6.png)

The current implementation only supports SQL Authentication with username and password fields required. We should support the "AAD only" and "both" use cases which ARM and REST both now support.

### Attempted Solutions

Using workarounds to deploy with arm template deployments, which have inconsistent results due to the deploy time of the MI resource timing out within the template deploy.

### Proposal

Add an authentication mode argument to the MI configuration. If this is not set to "activedirectory" then require username and password, otherwise they should be optional arguments.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
