### ISSUE TITLE
Support source_dest_check flag within resource aws_launch_configuration

### ISSUE THREAD

**Issue by brandongalbraith** [hashicorp/terraform#3236]
Currently, in order to use the source_dest_check flag you're required to use the `aws_network_interface` resource: https://github.com/hashicorp/terraform/issues/2407

It would be helpful if the source_dest_check flag could be specified along side the associate_public_ip_address flag in the aws_launch_configuration resource.

Example:
```
resource "aws_launch_configuration" "private-nat" {
  lifecycle { create_before_destroy = true }

  image_id = "${var.image_id}"
  instance_type = "t2.micro"
  associate_public_ip_address = true
  source_dest_check = false
  key_name = "${var.key_name}"
  security_groups = ["${aws_security_group.private-nat.id}"]
}
```

**Comment by stack72** [comment]
@brandongalbraith the [SDK](https://github.com/aws/aws-sdk-go/blob/master/apis/autoscaling/2011-01-01/api-2.json ) or [CLI](http://docs.aws.amazon.com/cli/latest/reference/autoscaling/create-launch-configuration.html) don't seem to support this 

I am not sure how this would be able to be added to Terraform without it

**Comment by brandongalbraith** [comment]
Thanks @stack72! I'll handle this by baking a script into the AMI to provide for this functionality.

**Comment by jangrewe** [comment]
For anybody having the same issue, this might be a solution: https://github.com/rubenv/ec2-disable-source-dest
