### ISSUE TITLE
Unable to create databricks metastore in Azure databricks

### ISSUE THREAD

**Issue by kdmenghani13** [hashicorp/terraform#32379]
### Terraform Version

```shell
terraform version 1.3.5
databricks version 1.6.5
```

### Terraform Configuration Files

```terraform
...terraform config...
```
provider "databricks" {
  host  = module.databricks.workspaceURL
  azure_workspace_resource_id = module.databricks.resourceId
  azure_client_id             = var.servicePrincipalId
  azure_client_secret         = var.servicePrincipalKey
  azure_tenant_id             = var.tenantId
}

resource "databricks_metastore" "databricksmetastore" {
  provider = databricks
  name = "primary"
  storage_root = format("abfss://%s@%s.dfs.core.windows.net/",
    data.azurerm_storage_container.unitycatalogcontainer.name,
  module.datalakeStorageV2.name)
  owner         = "uc admins"
  force_destroy = true
}

### Debug Output

│ Error: cannot create metastore: Management API token must be provided for service principal admin user login
│ 
│   with databricks_metastore.databricksmetastore,
│   on main.tf line , in resource "databricks_metastore" "databricksmetastore":
│   resource "databricks_metastore" "databricksmetastore" {

### Expected Behavior

It should be able to create the databricks metastore in azure databricks.

### Actual Behavior

It fails with an error. Error: cannot create metastore: Management API token must be provided for service principal admin user login

### Steps to Reproduce

Please try to create databricks_metastore resource with the provided code and it fails. Databricks creation works fine though.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
