### ISSUE TITLE
Cannot delete getting stupid cycle message 

### ISSUE THREAD

**Issue by aavileli** [hashicorp/terraform#3238]
Terraform v0.6.3 

template_file.userdata_tpl: Refreshing state... (ID: 05c8a0bb485036ac912af186f7f73e9272e329c6cff4c7d4b46d113adb02366b)
aws_security_group.default: Refreshing state... (ID: sg-7efb851b)
module.bigdata_web_sg.aws_security_group.default: Refreshing state... (ID: sg-79fb851c)
module.bigdata_lc_asg.aws_launch_configuration.launch_config: Refreshing state... (ID: terraform-rsvaoccbdnhhxaqswavbflz5e4)
module.bigdata_elb.aws_elb.elb: Refreshing state... (ID: bigdata-elb)
module.bigdata_lc_asg.aws_autoscaling_group.main_asg: Refreshing state... (ID: bigdata360)
Error creating plan: 1 error(s) occurred:

* Cycle: module.bigdata_lc_asg.output.launch_config_id, output.bigdata_lc_asg_launch_config_id, module.bigdata_lc_asg.aws_launch_configuration.launch_config (destroy), template_file.userdata_tpl (destroy), template_file.userdata_tpl, module.bigdata_lc_asg.var.user_data, module.bigdata_lc_asg.aws_launch_configuration.launch_config, module.bigdata_lc_asg.aws_autoscaling_group.main_asg (destroy), module.bigdata_elb.aws_elb.elb (destroy), module.bigdata_elb.aws_elb.elb, module.bigdata_elb.output.elb_name, module.bigdata_lc_asg.var.load_balancer_name, module.bigdata_lc_asg.aws_autoscaling_group.main_asg, module.bigdata_lc_asg.output.asg_id, output.bigdata_lc_asg_launch_asg_id

I have created multiple modules for my project

# main
```
resource "template_file" "userdata_tpl" {
    filename = "cloud-config/userdata_tpl.yml"
    vars {
        web-id = "${var.project_name}"
    }
}

resource "aws_security_group" "default" {
  name = "${var.project_name}-sg"
  description = "Default security group that allows inbound and outbound traffic from all instances in the VPC"
  vpc_id = "${var.vpc_id}"

  ingress {
    from_port   = "0"
    to_port     = "0"
    protocol    = "-1"
    cidr_blocks = ["${lookup(var.cidr-info, "VPC")}"]
  }

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"
    cidr_blocks = ["${lookup(var.cidr-info, "VPN")}"]
  }

  egress {
   from_port   = "0"
   to_port     = "0"
   protocol    = "-1"
   cidr_blocks = ["0.0.0.0/0"]
 }

  tags {
    Name = "${var.project_name}-sg"
    Environment = "${var.environment}"
  }
}


/* creating web-sg using module */
module "bigdata_web_sg" {
  source = "../../elb_web_sg"
  sg_name = "bigdata_web_sg"
  vpc_id = "${var.vpc_id}"
  environment = "${var.environment}"
  aws_region = "${var.aws_region}"
}

/* creating an internal elb for http only */
module "bigdata_elb" {
  source = "../../elb-http"
  elb_name = "bigdata-elb"
  elb_is_internal = true
  elb_security_group = "${module.bigdata_web_sg.id}"
  subnet_az1 = "${var.elb_subnet_az1}"
  subnet_az2 = "${var.elb_subnet_az2}"
  backend_port = 8080
  backend_protocol = "http"
  health_check_target = "HTTP:80/"
  aws_region = "${var.aws_region}"
  environment = "${var.environment}"
}

module "bigdata_lc_asg" {
  source = "../../elb_asg"
  ami_id = "${lookup(var.amis, var.aws_region)}"
  instance_type = "${var.instance_type}"
  iam_instance_profile = "${var.web-instace-profile}"
  key_name = "${var.key-pair-name}"
  security_group = "${aws_security_group.default.id}"
  user_data = "${template_file.userdata_tpl.rendered}"
  asg_name = "${var.project_name}"
  asg_number_of_instances = 1
  asg_minimum_number_of_instances = 1
  health_check_grace_period = 300
  health_check_type = "ELB"
  load_balancer_name = "${module.bigdata_elb.elb_name}"
  az1 = "${element(split(\",\", var.availability_zones), 0)}"
  az2 = "${element(split(\",\", var.availability_zones), 1)}"
  subnet_az1 = "${var.elb_subnet_az1}"
  subnet_az2 = "${var.elb_subnet_az2}"
  aws_region = "${var.aws_region}"
  tag_role   = "${var.project_name}"
  tag_name   = "${var.domain_name}"
  tag_environment = "${var.environment}"
}
```

# what is the order that terraform is deleting them and why is there a cycle error which even does not tell you which component is causing the cycle error.

**Comment by aavileli** [comment]
I have moved all security group creation to the root node and added lifecycle {create_before_destroy = true } for all resources . Then terraform deletes the stack successfully.

There should be a clear way to control this dependency and the docs need to have a troubleshooting section for dependency node logic

Dependency graph
![bigdat360](https://cloud.githubusercontent.com/assets/9123144/9894611/e156d532-5c68-11e5-951b-a4a06aeccdc9.png)

**Comment by catsby** [comment]
Hello @aavileli – this is a result of a known issue regarding `create_before_destroy` in the `lifecycle` block. In short, any resource that is a dependent of a resource that uses `create_before_destroy` , must also use `create_before_destroy` as well. 

This is documented here:

- https://terraform.io/docs/configuration/resources.html

You're absolutely correct that the cycle error message is not helpful :frowning: This is a know issue that we plan to address in the near future. Sorry for the trouble
