### ISSUE TITLE
Time Exceeded when applying a Subscription

### ISSUE THREAD

**Issue by Holmern** [hashicorp/terraform#32398]
### Terraform Version

```shell
Terraform v1.3.5
```

### Terraform Configuration Files

```
resource "azurerm_subscription" "this" {
  subscription_name = "${var.name}-${var.env}"
  billing_scope_id  = data.azurerm_billing_mca_account_scope.this.id
}

module "name_subscription" {
  source = "./subscription"

  for_each            = toset(["dev", "prod"])
  env                 = each.key
  name                = "name-it"
  management_group_id = module.name_management_group.management_group_id

  #VAR                  # Output fra Github Module
  repo_name = module.name_github.repo_name

  #   end_date                         = "" #Not required
  #   role_definition_name             = "" #Not Required
  #   federated_credential_description = "" #Not Required
}

```

### Debug Output

subscription.AliasClient#Create: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded

### Expected Behavior

Apply the azurerm subscription to azure 

### Actual Behavior

Pipeline fails with the error: context deadline exceeded

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

When running our GitHub Actions pipeline with apply, the output returns a [still creating], it does this for 30 minuts until the pipeline throws an error which states: Original Error: context deadline exceeded.
The thing is, I did apply and create the prod subscription, but it won't create the "dev" subscription. Is there something I can do for getting a quicker apply and then provision the Subscription? Internet speed, to many resources that want to apply at the same time (even if we are down to 4 resources) or just bad luck and try again tomorrow

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
