### ISSUE TITLE
Support for subscription owner in azurerm_subscription resource

### ISSUE THREAD

**Issue by kusumamurri** [hashicorp/terraform#32399]
### Terraform Version

```shell
tf --version
Terraform v1.3.5
+ provider registry.terraform.io/hashicorp/azurerm v3.35.0
```

### Use Cases

While creating new azure subscription via portal , in the advanced tab  there is a field to enter subscription owner.
url: https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/create-subscription
az cli has this parameter  available as "--owner-object-id"
az account create --enrollment-account-name
                  --offer-type {MS-AZR-0017P, MS-AZR-0148P, MS-AZR-USGOV-0015P, MS-AZR-USGOV-0017P, MS-AZR-USGOV-0148P}
                  [--display-name]
                  [--owner-object-id]
                  [--owner-spn]
                  [--owner-upn]
                  
![screenshot_37](https://user-images.githubusercontent.com/78359384/207901352-784429ed-eda1-4ddb-a646-061be50bff95.png)

### Attempted Solutions

I tried to use the argument "owner_object_id"  in azurerm_subscription resource .
It failed with below error 
An argument named "owner_object_id" is not expected here.

### References

https://learn.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az-account-create
https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/create-subscription

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
