### ISSUE TITLE
`terraform plan -refresh-only` gives error while looking at updated terraform config

### ISSUE THREAD

**Issue by kvipz** [hashicorp/terraform#32405]
### Terraform Version

```shell
╰─ terraform version 
Terraform v1.3.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.47.0

Your version of Terraform is out of date! The latest version
is 1.3.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

./tf_module/ssm.tf 
```terraform
variable "key" {
  type = string
}

variable "value" {
  type = string
}

resource "aws_ssm_parameter" "ssm" {
  name  = var.key
  type  = "String"
  value = var.value
}
```
./main.tf
```terraform
variable "params" {
  type = list(string)
  default = ["secreta", "secretb"]
}

locals {
  supplied_vars = toset(var.params)
}


module "ssm" {
  for_each = local.supplied_vars
  source = "./tf_module"
  key = each.key
  value = aws_s3_bucket.bucket[each.key].arn
}

resource "aws_s3_bucket" "bucket" {
  for_each = local.supplied_vars
  bucket = "vkbucket${each.key}"
}
```

### Debug Output

https://gist.github.com/kvipz/2d38b2bf290bd7a95de83ba478c594e0

### Expected Behavior

After updating adding a new key, `terraform plan -referesh-only` should not look at the updated configuration and refresh the state with just two keys

### Actual Behavior

`terraform plan -referesh-only` is looking for 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -auto-approve`
3. Update config variable default value with `secretc` in ./main.tf as follow
```terraform
variable "params" {
  type = list(string)
  default = ["secreta", "secretb", "secretc"]
}
```
4. `terraform plan -referesh-only` or `terraform apply -referesh-only -auto-approve`

### Additional Context

Provided TF config is before adding 3rd value in the params list variable while error output is after adding 3rd value and running `terraform plan -refresh-only`

### References

Couldn't find a related issue to this.

**Comment by kvipz** [comment]
Actual Behaviour: terraform plan -referesh-only is looking for a new value provided in the tf config

**Comment by jbardin** [comment]
Hi @kvipz,

Thanks for filing the issue. It's possible to create changes in the configuration which are ambiguous without taking into account the future plan for those changes. Because `-refresh-only` cannot plan new instances, downstream configuration changes which would need those instances may not be valid. Refreshing should be done with a configuration which matches the current state.

You can see more information in the duplicate #28939.

Thanks!
