### ISSUE TITLE
azurerm_automation_software_update_configuration - mandatory tag in azure query needed, but optional in documentation

### ISSUE THREAD

**Issue by steini44as** [hashicorp/terraform#32408]
### Terraform Version

```shell
Terraform v1.3.4
on windows_amd64
```

### Terraform Configuration Files

```terraform
locals {
  currentDate          = timestamp()
  currentFormattedTime = formatdate("YYYY-MM-DD", local.currentDate)
  currentHour          = formatdate("hh", local.currentDate)
  nextDay              = timeadd(local.currentDate, "24h")
  nextDayFormattedTime = formatdate("YYYY-MM-DD", local.nextDay)
  startTime            = var.StartingHour > local.currentHour ? "${local.nextDayFormattedTime}T${format("%02d", var.StartingHour)}:00:00Z" : "${local.nextDayFormattedTime}T${format("%02d", var.StartingHour)}:00:00Z"
  #classifications = replace(replace(var.UpdateClassificationList,"[",""),"]","")
}

resource "azurerm_automation_software_update_configuration" "automation_software_update_configuration" {
  name                  = var.ResourceName
  automation_account_id = var.AutomationAccountObjectId
  operating_system      = var.OperatingSystem
  duration              = var.Duration

  dynamic "linux" {
    for_each = var.OperatingSystem == "Linux" ? [1] : []
    content {
      classification_included = join("",var.UpdateClassificationList)
      reboot                  = var.RebootSetting
    }
  }

  dynamic windows {
    for_each = var.OperatingSystem == "Windows" ? [1] : []
    content {
      classifications_included = var.UpdateClassificationList
      reboot                  = var.RebootSetting
    }
  }

  target {
    azure_query {
      scope = var.UpdateScopeList
    }
  }

  schedule {
    frequency = var.Frequency
    interval  = var.Interval
    time_zone = "UTC"
    monthly_occurrence {
      day        = var.Day
      occurrence = var.NumberOfWeekInMonth
    }
    start_time = local.startTime
  }
}
```

### Debug Output

N/A

### Expected Behavior

Create software update configuration without the need of tags in target:
  target {
    azure_query {
      scope = var.UpdateScopeList
    }
  }

according to documentation, it's optional:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_software_update_configuration#azure_query

### Actual Behavior

Error when not providing tags in Azure query:
creating Software Update Configuration: (Name "wus-2nd-tue-0900-pm-rir" / Automation Account Name "aa-prd-shared-001" / Resource Group "gensio-rg-management-automation-dev-001"): automation.SoftwareUpdateConfigurationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="{\"Message\":\"The request is invalid.\",\"ModelState\":{\"softwareUpdateConfiguration.properties.updateConfiguration.targets.azureQueries[0].tagSettings.tags\":[\"The tags field is required.\"]}}"

### Steps to Reproduce

1. terraform init with in variables an update scope with Azure_Query block. Update scope is in my example a subscription:
/subscriptions/xxx
3. terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
