### ISSUE TITLE
Why data source not available for azurerm_container_registry_token_password ?

### ISSUE THREAD

**Issue by MageshSrinivasulu** [hashicorp/terraform#32407]
### Terraform Version

```shell
3.36.0
```

### Use Cases

The data source must be made available for azurerm_container_registry_token_password. 

Because once the password is created we can access it using data sources from any terraform sub-modules.

Currently, it's very restrictive that we can get the password by calling only the resource block which created that password.

### Attempted Solutions

There is no alternative solution for this now currently

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
