### ISSUE TITLE
AWS VPC Terraform module not giving option to create separate  route table for each AZ for intra subnet.

### ISSUE THREAD

**Issue by adi0902** [hashicorp/terraform#32400]
### Terraform Version

```shell
Terraform v1.2.3
```

### Terraform Configuration Files

```terraform
...terraform config...
```
source = "terraform-aws-modules/vpc/aws"

  region                            = var.region
  name                              = var.inspection_vpc_name
  create_igw                        = var.create_igw
  enable_nat_gateway                = var.enable_nat_gateway
  cidr_block                        = var.inspection_cidr_block
  private_subnets_cidr              = var.inspection_private_subnets_cidr
  intra_subnets_cidr                = var.inspection_intra_subnets_cidr
  public_subnets_cidr               = var.inspection_public_subnets_cidr

### Debug Output

VPC and route table created succefully.

### Expected Behavior

Need 3 seperate route table for intra subnet as having one single route table doesn't fulfil option of multi AZ. I am deploying AWS network firewall model where network firewall sits in intra subnet. and in order to make environment multi AZ each subnet route table should have route for each network firewall id. But with this module we are getting only single route table which doesn't give us option to make environment multi AZ.

### Actual Behavior

Only 1 route table shared by all 3 availability zones.

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
