### ISSUE TITLE
Is there a better way to untokenize a string than `replace(replace(replace...)))`

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#32419]
### Terraform Version

```shell
1.3+
```

### Use Cases

We frequently find outselves in situations where we want to untokenize a string. Whilst sometimes we can do so using `${}` or concat(), sometimes we want to define the string format in one module, pass it to another, and have it untokenized in the callee module, where the values can actually be calculated. This is both for modularity and to make nice reusable modules that can be used in different circumstances and projects with different naming conventions.

For example, we might pass `name_format="foo_{env}_bar_{region}_baz_{special_id}"` to a module which knows how to look up the values for {special_id}, {env}, and {region} from some other data and combine them in a way that the calling module wants.

At the moment we have to do something like this:

```
value = replace(replace(replace(var.name_format, "{env}", var.env), "{region}", var.region), "{account}", var.account)
```

Sometimes we have strings with 10 variables in, it contains e.g. `replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(` -  the code isn't pleasant to look at, although does work. 

We could double encode the name_format and instead of using `${}` , we could use `$${}` in the supplied value, and then pass the whole thing to some kind of template() function in the submodule, but there is no template() function, only a templatefile() function - and the old datasource from the template provider also mainly works on files. And in any case `$${}` is kinda horrible anyway.

Are there any other nice untokenise methods around? `regex()` and `regexall()` cant use backreferences so we cant seem to do the above with regexes unfortunately. If not, can we have a new function to untokenise (or do multiple substitutions) in a string properly? Am not bothered about the `{}` bracket syntax, just a standard way to do it. 

Thanks!

### Attempted Solutions

`replace(replace(replace(replace(..... ` - horrible

### Proposal

Perhaps a template function:

```
value = template(var.formatted_string, {
  foo = var.foo,
  bar = var.actions["bar"],
  baz = var.networks[0]["baz"]
}
```

(But this would mean the passed through formatted_string would have to have double-encodings such as `$${}`

or perhaps a general replace/untokenize function:

```
value = replace_all(var.formatted_string. {
  "{foo}", var.foo,
  "{bar}", var.bar
})
```

**Comment by apparentlymart** [comment]
Hi @gtmtech,

I have previously shared somewhere (but I don't remember where) an example of doing this in multiple steps something like this:

* First use `regexall` just to split the source string into a list of tokens that are either placeholders (starting with `{{`` in your syntax) or literal (not starting with the special marker sequence).
* Use a `for` expression on that result whose output expression is conditional on whether each element starts with `{{`. If it does then look up the specified key in a map to find a replacement. If it doesn't then just return it literally.
* The result is a list of strings that are all now literal chunks. Concatenate them back together using `join` to produce the final result string.

This is essentially the same as what you might do in a language that supports arbitrary expressions for the replacements when doing a regex replace, but with the replacement part implemented manually after just tokenizing the string using a regex.

I think aside from writing a custom provider that wraps a template engine of your choice, the above is the most robust approach with today's Terraform language.

**Comment by valentindeaconu** [comment]
Hello!

To complete @apparentlymart's answer, here's a code example of how to do it:

```hcl
locals {
  tokens = {
    "NAME"    = "John"
    "PROJECT" = "Terraform"
  }

  template = "Hello, {{ NAME }}! You're currently working on {{ PROJECT }}. Happy Terraforming!"

  result = format(
    # Replace any variable with a %s which will be filled by the format func
    replace(local.template, "/{{\\s?(${join("|", keys(local.tokens))})\\s?}}/", "%s"),
    [
      # Replace each variable found in the given template with its value from the tokens map
      for value in flatten(regexall("{{\\s?(${join("|", keys(local.tokens))})\\s?}}", local.template)) :
      lookup(local.tokens, value)
    ]...
  )
}

output "result" {
  value = local.result
}
```

After running a `terraform plan`, you will see:
```
Changes to Outputs:
  + result = "Hello, Bob! You're currently working on Terraform. Happy Terraforming!"
```

This implementation is inspired by [this answer](https://stackoverflow.com/questions/67375029/terraform-replacing-multiple-substrings-in-a-string), modified a bit to change the templating variables from `{variable}` to `{{\s?variable\s?}}`.

**Comment by gtmtech** [comment]
Genius

**Comment by apparentlymart** [comment]
Thanks for sharing that, @valentindeaconu!

I had some spare moments today so I wrote up an example of the technique I had been imagining when I made my previous comment:

```hcl
variable "input" {
  type = string
}

locals {
  subst_vals = tomap({
    name = "Jill"
  })

  tokens = regexall("(?:\\{\\{\\w+}}|[^{]+|\\{)", var.input)

  parts = tolist([
    for token in local.tokens : (
      startswith(token, "{{") ?
      local.subst_vals[substr(token, 2, length(token)-4)] :
      token
    )
  ])
}

output "result" {
  value = join("", local.parts)
}
```

This achieves much the same result, with just some slight differences in the details of how to get there.

```
$ terraform apply --auto-approve -var=input='Hello, {{name}}!'
(...)

Outputs:

result = "Hello, Jill!"
```

**Comment by gtmtech** [comment]
I am going to close this issue as workarounds are possible
