### ISSUE TITLE
Add Output To The Test Subcommand Similar To Apply

### ISSUE THREAD

**Issue by b01** [hashicorp/terraform#32425]
### Terraform Version

```shell
2022-12-21T10:43:15.817-0500 [INFO]  Terraform version: 1.3.6
2022-12-21T10:43:15.818-0500 [INFO]  Go runtime version: go1.19.3
2022-12-21T10:43:15.818-0500 [INFO]  CLI args: []string{"C:\\Users\\Khalifah\\bin\\terraform.exe", "version"}
2022-12-21T10:43:15.823-0500 [INFO]  CLI command args: []string{"version"}
Terraform v1.3.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.46.0
```

### Use Cases
On my system: 
Edition	Windows 10 Pro
Version	21H2
Installed on	‎10/‎5/‎2020
OS build	19044.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

Currently When you run `terraform test` you see no output until after the command completes. 

Please give the user some idea what is happening, like which test suite is running and what infrastructure is being deployed. I know it is in the experimental stage, but it would be nice-to-have even for a basic experiment.

### Attempted Solutions

Set the environment variable `TF_LOG="INFO"` as a work-a-round for now.

### References

I will admit I did not search much. But there are currently 1.6 open issues and GitHub search feature is not great. I don't want to rummage by hand through that many issue.

**Comment by b01** [comment]
So I do see there is output when test fail; which you only get to see when the IaC your developing is working perfectly according to Terraform. But this is ONLY when the IaC has no mistakes and only that the test assertions are incorrect when test run. Which I would say is not very useful, because I'm more likely to have mistakes all over the place and also in the assertions (To err is human, and I really like being human).

**Sample of Output From Failed Test**

```shell
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
PS C:\Users\Khalifah\src\github.com\kohirens\aws-tf-s3-backend> terraform test -junit-xml="terraform-test-results.xml"
╷
│ Warning: The "terraform test" command is experimental
│
│ We'd like to invite adventurous module authors to write integration tests for their modules using this command, but all of the behaviors of this command are currently experimental and may
│ change based on feedback.
│
│ For more information on the testing experiment, including ongoing research goals and avenues for feedback, see:
│     https://www.terraform.io/docs/language/modules/testing-experiment.html
╵
─── Failed: setup-backend.verify_setup.verify_log_bucket (exist) ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
wrong value
    got:  "qa-755285156183-tf-backend"
    want: "qa-755285156183-tf-backend-logs"

─── Failed: setup-backend.verify_setup.verify_table_bucket (exist) ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
wrong value
    got:  "qa-755285156183-tf-backend-lock-table"
    want: "qa-755285156183-tf-backend-logs"

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I guess this means unless Terraform code has no mistakes, then you do not get to see this too often. The `test` sub-command is VERY limited on what mistakes/errors it reports right now. You can only see real errors by setting the `TF_LOG="TRACE"` or something.

This also means that someone can easily break test and they can get away with committing them since the assertions will be skipped automatically and the `test` sub-command will return success.

**Comment by crw** [comment]
Thanks for this request!

**Comment by liamcervante** [comment]
I believe the finalised `test` command meets this feature request. Each run block is reported on as it executes, so the feedback is more regular.
