### ISSUE TITLE
Can't destroy secret after creating kubernetes cluster in autopilot mode

### ISSUE THREAD

**Issue by DarioBernardo** [hashicorp/terraform#32421]
### Terraform Version

```shell
Terraform v1.3.5
on darwin_amd64
```

### Terraform Configuration Files

main.tf

```terraform
provider "google" {
  project = var.project-id
  region = var.region
}

module "kubernetes-cluster" {
  source = "./gke"
  region = var.region
  cluster-name = var.cluster-name-prefix
  project-id = var.project-id
  credentials-email = var.credentials-email
  database-user = "my_db_user"
  database-password = "my_db_pass"
  database-schema-name = "my_schema_name"
  database-connection-name = "myconnection_name" 
}
```

gke/main.tf
```terraform
data "google_client_config" "default" {}

resource "google_service_account" "default" {
  account_id   = "gke-service-account"
  display_name = "GKE Service Account"
}

resource "google_container_cluster" "cluster" {
  name     = "${var.cluster-name}-${terraform.workspace}"
  location = var.region
  project = var.project-id

  ip_allocation_policy {}

  # Enabling Autopilot for this cluster
  enable_autopilot = true
}

provider "kubernetes" {
  host     = "https://${google_container_cluster.cluster.endpoint}"

  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(google_container_cluster.cluster.master_auth.0.cluster_ca_certificate)
}

resource "kubernetes_secret" "cloudsql-credentials" {
  metadata {
    name = "database-credentials" # The name of the secret
  }
  data = {
    connection-name = var.database-connection-name
    username = var.database-user
    password = var.database-password
  }
  type = "kubernetes.io/basic-auth"
}
```

### Debug Output

```
╷
│ Error: Provider configuration not present
│ 
│ To work with module.kubernetes-cluster.kubernetes_secret.cloudsql-credentials (orphan) its original provider configuration at module.kubernetes-cluster.provider["registry.terraform.io/hashicorp/kubernetes"] is required, but it
│ has been removed. This occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy
│ module.kubernetes-cluster.kubernetes_secret.cloudsql-credentials (orphan), after which you can remove the provider configuration again.
╵

```

### Expected Behavior

I want to update my infrastructure and I want to remove the secret and kubernetes cluster but i want to keep the rest. I therefore comment the `module "kubernetes-cluster"` section in `main.tf` and launch `terraform apply`. The secret and the cluster should get destroyed.

### Actual Behavior

An error message gets thrown when calling `terraform plan` or `terraform apply` after i comment out the `module "kubernetes-cluster"` section in `main.tf`.  Instead of destroying the secret the following error message gets thrown and both the cluster and the secrets are not destroyed.

```
╷
│ Error: Provider configuration not present
│ 
│ To work with module.kubernetes-cluster.kubernetes_secret.cloudsql-credentials (orphan) its original provider configuration at module.kubernetes-cluster.provider["registry.terraform.io/hashicorp/kubernetes"] is required, but it
│ has been removed. This occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy
│ module.kubernetes-cluster.kubernetes_secret.cloudsql-credentials (orphan), after which you can remove the provider configuration again.
╵

```

 If I instead manually destroy the secret with :
`terraform destroy --target=module.kubernetes-cluster.kubernetes_secret.cloudsql-credentials` and then comment out `module "kubernetes-cluster"` section in `main.tf` and launch `terraform apply`, the cluster gets correctly destroyed.  

### Steps to Reproduce

`terraform init`
`terraform apply`
..comment out `module "kubernetes-cluster"` section in `main.tf` ..
`terraform plan`

### Additional Context

If I instead don't use auto pilot, but I create the cluster specifying the node_pool, the problem does not appear.

**Comment by jbardin** [comment]
Hi @DarioBernardo,

The module you have created contains the provider configuration for the `kubernetes_secret`. If you remove the module as a whole, then there is no provider configuration which which to destroy the `kubernetes_secret`. If the module requires specific provider configuration, that should be passed into the module explicitly: https://developer.hashicorp.com/terraform/language/modules/develop/providers#passing-providers-explicitly

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
