### ISSUE TITLE
Linking in documentation leading to misread character

### ISSUE THREAD

**Issue by lukiffer** [hashicorp/terraform#32423]
### Terraform Version

```shell
1.3.4
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/expressions/version-constraints

from source

https://github.com/hashicorp/terraform/blob/main/website/docs/language/expressions/version-constraints.mdx

### What is the docs issue?

When viewing the markdown directly, the documentation is clear. However, on the developer.hashicorp.com website, linking is applied to each of the bulleted lists.

This leads to the `>` character (when linked and underlined) to read like the `≥` character, which is not supported.

In context with the rest of the document, it's clear what my mistake was, but not sure if anything can be done to avoid that mistake in the first place.

### Proposal

A few options could prevent the issue:
- Add an invisible anchor to avoid linking of the actual text in bullets.
- Add an invisible markdown marker observed by the HTML converter to omit links to specific lines.

**Comment by crw** [comment]
Thanks for this report! I've notified the docs team.

**Comment by tpdownes** [comment]
@crw FYI this remains an issue. It has the impact that it looks like the greater-than symbol is not a valid operator, while I am supposed to figure out Unicode for greater-than-or-equal.

<img width="637" alt="Screenshot 2024-10-31 at 8 56 07 AM" src="https://github.com/user-attachments/assets/1084e673-eb44-4360-ae75-cb567863e300">

**Comment by crw** [comment]
I've raised this again with the docs team -- hopefully someone who understands the semantics can create a fix for this issue! Thanks!
