### ISSUE TITLE
aws_vpc "provider" argument not documented

### ISSUE THREAD

**Issue by cosminnicula** [hashicorp/terraform#32441]
### Terraform Version

```shell
Terraform v1.3.6
on linux_amd64
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc

### What is the docs issue?

The "provider" argument is not documented, although I can use it in code like this:

```
provider "aws" {
  region = "eu-west-1"
  profile = "default"
  alias = "aws-eu-west-1"
}
```

```
resource "aws_vpc" "vpc-eu-west-1" {
  cidr_block = "10.1.0.0/16"
  provider = aws.aws-eu-west-1
}
```

### Proposal

Document the "provider" argument mentioning that it provides a reference to a provider configuration block.

**Comment by liamcervante** [comment]
Hi @cosminnicula, thanks for the report.

Terraform providers are managed in separate repositories. I will close the issue here but if you open a fresh issue within https://github.com/hashicorp/terraform-provider-aws/issues, they will be able to update the documentation for the AWS provider.
