### ISSUE TITLE
Creation of aws_acm_certificate fails because of provider produced inconsistent final plan

### ISSUE THREAD

**Issue by darek73pl** [hashicorp/terraform#32446]
### Terraform Version

```shell
Terraform v0.14.11
```

### Terraform Configuration Files

```
resource "time_rotating" "example" {
  rotation_minutes = 5
}

resource "aws_acm_certificate" "example" {
  domain_name = "mydomain.local"
  subject_alternative_names = [
    "${time_rotating.example.unix}.mydomain.local"
  ]

  certificate_authority_arn = "arn:aws:acm-pca:eu-west-1:xxxxxxxxxxxx:certificate-authority/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```

### Debug Output

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_acm_certificate.example will be created
  + resource "aws_acm_certificate" "example" {
      + arn                       = (known after apply)
      + certificate_authority_arn = "arn:aws:acm-pca:eu-west-1:xxxxxxxxxxxx:certificate-authority/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      + domain_name               = "mydomain.local"
      + domain_validation_options = (known after apply)
      + id                        = (known after apply)
      + key_algorithm             = (known after apply)
      + not_after                 = (known after apply)
      + not_before                = (known after apply)
      + pending_renewal           = (known after apply)
      + renewal_eligibility       = (known after apply)
      + renewal_summary           = (known after apply)
      + status                    = (known after apply)
      + subject_alternative_names = [
          + "mydomain.local",
        ]
      + tags_all                  = (known after apply)
      + type                      = (known after apply)
      + validation_emails         = (known after apply)
      + validation_method         = (known after apply)
    }

  # time_rotating.example will be created
  + resource "time_rotating" "example" {
      + day              = (known after apply)
      + hour             = (known after apply)
      + id               = (known after apply)
      + minute           = (known after apply)
      + month            = (known after apply)
      + rfc3339          = (known after apply)
      + rotation_minutes = 5
      + rotation_rfc3339 = (known after apply)
      + second           = (known after apply)
      + unix             = (known after apply)
      + year             = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

time_rotating.example: Creating...
time_rotating.example: Creation complete after 0s [id=2022-12-31T07:13:13Z]

Error: Provider produced inconsistent final plan

When expanding the plan for aws_acm_certificate.example to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .subject_alternative_names: actual set
element cty.StringVal("1672471093.mydomain.local") does not correlate with any
element in plan.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for aws_acm_certificate.example to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .subject_alternative_names: length changed
from 1 to 2.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Expected Behavior

Created certificate

### Actual Behavior

Error: Provider produced inconsistent final plan

### Steps to Reproduce

1. create a certificate authority whose arn should be entered as the "aws_acm_certificate" argument
2. terraform init
3. terraform apply

### Additional Context

After the first "terraform_apply" (ended in error), the "time_rotating" resource was created. The second "terraform_apply" succeeds.
However, recreating two resources, after the rotation time ends, fails again.

**Comment by liamcervante** [comment]
Hi @darek73pl, thanks for the report.

Terraform providers are managed in separate repositories, so I've transferred this issue across to the AWS provider repository: https://github.com/hashicorp/terraform-provider-aws
