### ISSUE TITLE
Allow importing without associated configuration

### ISSUE THREAD

**Issue by JimmyIL** [hashicorp/terraform#32445]
### Terraform Version

```shell
>= 1.3.0
```

### Use Cases

 I use 'terraform import -allow-missing-config' often for automating the import of massive amount of resources into state.  This is also very useful when creating resources similar to existing resources that are not tracked in the state file, but unsure of some of the parameters/options that they were created with.  "-allow-missing-config" saves me tons of time.   I use this combined with other state options to maneuver around, then just copy "terraform state show <resource i need>" and pipe into the proper .tf files, I then filter out the "extra" parameters in these resources that are not needed.

### Attempted Solutions

I have to use terraform version earlier than v1.3.0 (where this change was made).

### Proposal

Add it back in to a new release/feature maybe? I'm not sure of the actual technical reason it was removed other than to protect developers from themselves.  The people who are using this flag obviously know what it does and I don't think it collides with any other hashicorp goals unless it's to implement importing existing infrastructure and ignore unusable resource params in later versions of TF :)

**Comment by jbardin** [comment]
Hi @JimmyIL,

Thanks for the added use case. The `-allow-missing-config` flag was removed because it no longer works with the internal of the `import` command which need to generate a plan so that configuration can be taken into account. It's possible however that some other workflow can be devised here as the `import` functionality is improved.

Thanks!

**Comment by JimmyIL** [comment]
Hello, curious if there was any talks/progress on this.  I would like to use the newest versions of terraform, but this is very much a drawback as I consistently switch back and forth between versions.  I can program an auto switch when using terraform import commands, but sometimes the repository I am using has version requirements and I have to go and manually change those as well.  Would love to see this functionality back into terraform later versions.

**Comment by JimmyIL** [comment]
Going to go ahead and close this issue since the successful implementation of 'config driven terraform imports'. Thanks!
