### ISSUE TITLE
Terraform Meta-Modules & Meta-Providers

### ISSUE THREAD

**Issue by 0xW1sKy** [hashicorp/terraform#32443]
### Terraform Version

```shell
Terraform v1.0.10
on darwin_amd64
```

### Use Cases

An easier-to-create type of provider and easier-to-interact-with module
Read proposal section for full explanation

### Attempted Solutions

The easiest thing to point out here is the creation of a terraform provider requires proficiency in Go. (based on the documentaiton i was able to find)

I could not find instruction on how to create a provider type resource via terraform-on-terraform approach.

The other part of this is a different way of handling modules to make them easier to interact with.

### Proposal

I would expect it to work like so:

providers.tf
```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.69"
    }
  }
  meta-modules{
    example_meta_module = {
      source = "./modules/my-module"
    }
  }
}
```

by loading the meta-module you could interact with it like so:

```terraform
resource “example_meta_module” “resource_name” {
	
}

data “example_meta_module” “resource_name” {

}

```

then inside the module we would pass through the type and name of the request (i.e. 'resource' or 'data' and "resource_name")

a vars.tf file would thus have something like this

```terraform
# Vars.tf


# This would resolve to "resource" or "data" depending on which was specified
variable "__type__" {
  type = string
   validation {
    condition     = can(regex("^(resource|data)$", var.__type__))
  }
}

# This would resolve to "resource_name"
variable "__name__" {
  type = string
}


variable "source_dir" {}
variable "triggers" {}
variable "output_path" {}


```

using the "\_\_type\_\_" variable, we can then trigger within the module what resources to create

This would allow for pre-packaged easy to manage custom resources that can be delivered to teams who may otherwise not know how to build the more complex implementation contained within the metamodule (same use case as normal modules).

```terraform
# Main.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.69"
    }
  }
}


## In order to maintain the predictability demanded of a terraform module I would recommend
## that if the __type__ value specified is "data", the child objects within the main.tf file
## would only be allowed to be "data" objects.
## if the __type__ value specified is "resource", the child objects within the main.tf file
## would be allowed to be "data" and "resource" objects.


resource "null_resource" "lambda_exporter" {
  # (some local-exec provisioner blocks, presumably...)
  triggers = var.triggers
}

data "null_data_source" "wait_for_lambda_exporter" {
  inputs = {
    # This ensures that this data resource will not be evaluated until
    # after the null_resource has been created.
    lambda_exporter_id = "${null_resource.lambda_exporter.id}"

    # This value gives us something to implicitly depend on
    # in the archive_file below.
    source_dir = "${var.source_dir}"
  }
}

data "archive_file" "package" {
  type        = "zip"
  source_dir  = replace(replace(var.source_dir, "./", "${path.root}"), ".\\", "${path.root}")
  output_path = replace(replace(var.output_path, "./", "${path.root}"), ".\\", "${path.root}")
}

```

Output for the meta module would only be allowed to be a single resource from the template
This output would be expanded before delivering back to the parent template
“example_meta_module” “resource_name”
> i.e. instead of calling it via example_meta_module.resource_name.__default__.output_path you would be able to call it via example_meta_module.resource_name.output_path

```terraform
# Outputs.tf


output "__default__" {
  value = data.archive_file.package
}

```

with the above working as described I could then do something like this in the TF root:

```terraform

resource “example_meta_module” “resource_name” {
  source_dir = "${path.module}/lambda/"
  triggers = {
    index = base64sha256(file("${path.module}/lambda/index.py"))
  }
  output_path = "./out/lambda.zip"
}


resource "aws_lambda_function" "lambda" {
  filename         = example_meta_module.resource_name.output_path
  source_code_hash = example_meta_module.resource_name.output_base64sha256

  function_name = "lambda_function"
  role          = aws_iam_role.role.arn
  handler       = "index.handler"
  runtime       = "python3.8"
}


```

each "meta-module" would only be able to return a single resource, and thus, you could build out a directory of meta modules. 
Using a similar kind of funcitonality as the above, i think you could collect these together to create "meta-providers"

A meta-provider would just be a collection of the meta-modules that would function similar to existing providers, you would just specify the source as a file path and instead of being go on the backend, it would be all terraform.
By being terraform end-to-end terraform users that don't know go would be able to create meta-providers easily for internal use and then interact with it via the provider syntax they're already familiar with.

**Comment by crw** [comment]
Thanks for this request!

**Comment by kmoe** [comment]
Thanks for the proposal. Not sure I fully understand the use case - could you describe what you are trying to achieve?

I'm also curious about what you mean by "easier to interact with". Please take a look at the following popular module for creating Lambdas:
https://github.com/terraform-aws-modules/terraform-aws-lambda#lambda-function-and-lambda-layer-store-packages-on-s3

In this example you can supply the usual parameters (source dir, triggers, etc) in the `module` block. What is missing here for your use?

**Comment by crw** [comment]
I am doing clean-up on old waiting-response issues. As this issue has not seen a response since the previous post, I am going to close this. Please let me know if you are experiencing this issue and can answer the questions raised in the previous post. Thanks!
