### ISSUE TITLE
Permit no routes other than default when using the aws_route_table resource.

### ISSUE THREAD

**Issue by brandongalbraith** [hashicorp/terraform#3245]
The [aws_route_table](https://www.terraform.io/docs/providers/aws/r/route_table.html) resource requires one of the following:
- gateway_id
- instance_id
- vpc_peering_connection_id
- network_interface_id

Our default route table (flagged as our main route table) has no routes other than the default local CIDR route (which according to the Terraform docs, does not need to be provided: "Note that the default route, mapping the VPC's CIDR block to "local", is created implicitly and cannot be specified."). Can the resource be modified in order to allow the creation of a route table without one of the above resources being specified?

**Comment by catsby** [comment]
Hey friend – sorry for the very long time to reply; `aws_route_table` can indeed be created without any routes specified. You cannot however create routes without specifying one of the above mentioned attributes; it's specified by the API as a must:

- http://docs.aws.amazon.com/fr_fr/AWSEC2/latest/APIReference/API_CreateRoute.html
