### ISSUE TITLE
The plan option refresh=false no longer works on terraform v1.3.6

### ISSUE THREAD

**Issue by mattpopa** [hashicorp/terraform#32456]
### Terraform Version

```shell
Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.48.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

### Terraform Configuration Files

N/A -- it's applicable to any example config.

This bug isn't related to a configuration file, but with the refresh option while running `terraform plan`.

Use case: To avoid refresh noise in terraform output I run my pipeline in 2 steps:
1. `terraform refresh -input=false -no-color`
2. `terraform plan --refresh=false -no-color -input=false`

This way I can post a concise output result of `terraform plan` on my open PRs.

### Debug Output

`terraform plan --refresh=false` still reads the state, 

There seems to be no difference between `terraform plan --refresh=true` and `terraform plan --refresh=false` in terms of output.

### Expected Behavior

Running `terraform plan --refresh=false` should only output the terraform changes, if any. If there aren't any changes, it should output `No changes. Your infrastructure still matches the configuration.`

### Actual Behavior

Running `terraform plan --refresh=false` still does and outputs the refresh, e.g.:

```
data.terraform_remote_state.main: Reading...
module.get_image_tag.data.external.fetch_image_tag: Reading...
data.aws_caller_identity.current: Reading...
data.aws_region.current: Reading...
[...]
```

### Steps to Reproduce

1. terraform init
2. terraform refresh
3. terraform plan --refresh=false

### Additional Context

I have upgraded terraform from 1.0.6 where I did not experience this issue. This was tested both using github actions 
```
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6
```

and on macOS arm64 with the same result.

**Comment by jbardin** [comment]
Hi @mattpopa,

The output shown here only lists data sources, which are always expected to be read. Are you seeing any managed resource reads when using `-refresh=false`?

Thanks!

**Comment by mattpopa** [comment]
hi @jbardin 

It's not just data sources, see `module.get_image_tag.data.external.fetch_image_tag: Reading...`
That's just an example, and data sources are not appearing at all in 1.0.6, nor 1.1.0 as far as I tested.

The expectation is to only see the changes when using `-refresh=false` like 

```
 terraform plan -refresh=false 

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

[redacterd]
```

Using 1.3.x the output's like not providing `-refresh=false` in `terraform plan -refresh=false`

**Comment by jbardin** [comment]
`module.get_image_tag.data.external.fetch_image_tag` is a data source, it is just contained within the `get_image` module. There was a bug fixed a while back where data source reads were not always displayed in the CLI output, which may be what is causing the confusion, but there have been no other recent changes to what actions are taken during a plan with `-refresh=false`.

**Comment by mattpopa** [comment]
@jbardin I've edited my comment, added more details. Hope this makes more sense, and it is reproducible regardless of terraform config

e.g. just by changing 

```
terraform {
  required_version = "1.1.0"
...
```

to 
```
terraform {
  required_version = "1.3.6"
```

providers and the rest of the config remains unchanged.

running the plan with or without `-refresh=false` doesn't make any diff in terms of output

**Comment by mattpopa** [comment]
I think the `data` block is just confusing in this case (red herring). Here are some managed resources, part of the redacted output

```
module.redshift.aws_redshift_parameter_group.main: Refreshing state... [id=ZZZredacted]
aws_ecr_repository.alpine-node: Refreshing state... [id=YYYredacted]
module.dms.module.data_migration_service_key.aws_kms_key.main: Refreshing state... [id=39e1a9a2-d716-4d1e-9a74-882fXXXX]
```

**Comment by mattpopa** [comment]
@jbardin you're right, it's only data blocks, I mistakenly confused `Refreshing state...` with `Reading...` 😬

My expectation was to have a clean plan output while using `refresh=false`.
Is there any way to suppress `Reading... | Read complete after 0s | Still reading... ` from output while using `refresh=false`?

Would this be a feature request?

**Comment by jbardin** [comment]
@mattpopa, if you want to see no output except for the plan, the best way is to ignore the CLI output, and and use `terraform show` on the resulting plan (though you may want to store the output for inspection in case of problems). You can also manually filter things from the structured `-json` output if you want. 

It would be a separate feature request to specifically filter the `Reading...` output from the CLI, but that seems very specific to your use case. Perhaps #29061 is more generally applicable.  Since this however does not represent a bug in Terraform, I'm going to close this issue for now.

Thanks!
