### ISSUE TITLE
aws_route53_record with uppercase letters not written to state file

### ISSUE THREAD

**Issue by alexintel** [hashicorp/terraform#3246]
Regression for v. 0.6.3 compared to v. 0.5.3
aws_route53_record resource is not being written to terraform.tfstate file. Probably a root cause for https://github.com/hashicorp/terraform/issues/3168 and https://github.com/hashicorp/terraform/issues/3159

I hope that's an easy fix to squash all 3 bugs. I probably should have looked deeper into terraform.tfstate file before reporting symptoms in two other bugs.

**Comment by apparentlymart** [comment]
I've seen this specific issue occur (not being written to state file) when the name contains uppercase letters. Route53 normalizes these to lowercase in its responses, so when Terraform scans for the record in the describe response it doesn't match and it thinks the record has been deleted.

By any chance does your record name contain uppercase letters, or any other sort of thing that the DNS system might normalize away?

**Comment by alexintel** [comment]
Yes, in fact DNS entry in my case contains UPPER case characters. I use a randomized stack name something like 123aBc (can be upper or lower case letters) in order to identify resources belonging to the same stack. I propagate that randomized name through the resources including instance names, elb names, route53 entries, and etc.

However, this is still a regression compared to 0.5.3 and in my opinion should not happen.

If terraform does not record all created resources regardless of normalization it's doing internally we'll have a problem with unaccounted infrastructure items left behind.

I just re-run terraform and can confirm that UPPER case characters in aws_route53_record resource indeed cause this issue. Using lower case characters also resolves https://github.com/hashicorp/terraform/issues/3159

**Comment by apparentlymart** [comment]
Yeah, it's definitely a bug that Terraform doesn't normalize this. At work we've had submitting a patch for this on the todo list for a while, but it didn't reach the top yet.

If someone else would like to attack it in the mean time, I expect the solution will be something similar to what I did in #3120. Otherwise I expect we'll get to it in a little while as we're getting set up to use Terraform with Route53 to manage some of our DNS zones.

**Comment by reppard** [comment]
seeing this issue as well. we use 'app_name' or 'project' variables that sometimes contain uppercase characters.  normalizing the input would be great.

**Comment by catsby** [comment]
Hey all – sorry for the silence here. I believe this issue was fixed in #3574 , so I'm going to close this. If you feel this is incorrect please let me know and if possible supply an example config that demonstrates this, so that I can dig in further. Thanks!
