### ISSUE TITLE
CloudStack: allow networkdomain as argument in create_vpc

### ISSUE THREAD

**Issue by larstobi** [hashicorp/terraform#3248]
I want to be able to set the networkdomain when I create a VPC with the CloudStack provider.

This is currently not supported by the CloudStack provider in Terraform.

https://cloudstack.apache.org/api/apidocs-4.5/user/createVPC.html
https://terraform.io/docs/providers/cloudstack/r/vpc.html

**Comment by svanharmelen** [comment]
Should be a pretty straight forward change... Will see if I can make some time for it. But in the mean time, I'll be happy to review any PR's for this one :wink:

**Comment by larstobi** [comment]
Thanks! :+1:
