### ISSUE TITLE
Instance image does not auto (default) create when creating a imagebuilder container recipe? 

### ISSUE THREAD

**Issue by PatrickKhai-Moodys** [hashicorp/terraform#32485]
### Terraform Version

```shell
Terrform version `4.49`
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

```
resource "aws_imagebuilder_container_recipe" "this" {
  name           = var.name
  container_type = var.container_type
  parent_image   = var.parent_image
  version        = var.recipe_version
  tags           = var.tags

    
  instance_configuration {
    image = var.ami_id #this is to be created default
    block_device_mapping {
      device_name = "/dev/xvda"
      ebs { 
        delete_on_termination = true
        volume_size           = var.ebs_volume_size
        volume_type           = var.ebs_volume_type
        iops                  = var.ebs_iops
        throughput            = var.ebs_throughput 
      }
    }
  }

}
```

### Expected Behavior

Instance Image should have created an ami ID for the container recipe by default.

### Actual Behavior

Instance image does not get created with the container recipe.

### Steps to Reproduce

1. 'terraform init'
2. terraform plan'

### Additional Context

What should I do to make sure the the AMI ID is provided automatically when using terraform to create the container recipe? 
When I manually create this on AWS console, AMI Id is provided automatically.

Per aws, instanceConfiguration (object) – A group of options that can be used to configure an instance for building and testing container images. However this image object below does not get created through terraform process.
- image (string) – The AMI ID to use as the base image for a container build and test instance. If not specified, Image Builder will use the appropriate Amazon ECS-optimized AMI as a base image.

**Comment by crw** [comment]
Hello @PatrickKhai-Moodys, this appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
