### ISSUE TITLE
Feature: terrform apply -skip="resource.you.want.to.skip.in.main.tf"

### ISSUE THREAD

**Issue by acarlstein** [hashicorp/terraform#32480]
### Terraform Version

```shell
Terraform v1.3.5
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

There is a module that have being flagged for no deletion; however, it is listed inside the `main.tf`.

This means that when running `terraform destroy` those module wont be destroyed.

When trying to use `terraform apply`, we get messages such as:
```terraform
Error: invalid response from API server (409): The resource '...' already exists
```

### Attempted Solutions

One way is to use the target flag, with apply, and try to apply each module and resource that isn't the one giving the 409.

### Proposal

The proposal is to introduce a new flag `-skip`. So, we can tell `apply` which modules and resources, in `main.tf`, we wish to skip.

**Comment by apparentlymart** [comment]
Thanks for this feature request, @acarlstein!

I think what you are describing might be the same as what was discussed over in #2253. Would you agree? If so, I'd like to consolidate these together into a single discussion just to avoid diluting the voting.

**Comment by tigpt** [comment]
looking forward for this option.

**Comment by LDVSOFT** [comment]
Hi! As one of motivations: looks like I've hit a provider bug on one of resources, but I can agree to work around it and still need to apply other changes. Manually `-target`-ing all the other resources seems harder than to say "Ok, skip this one for now".

**Comment by crw** [comment]
As there has not been an update from the original author, I am going to trust @apparentlymart's judgement that this one is the same issue as https://github.com/hashicorp/terraform/issues/2253. Please follow that issue for future updates.
