### ISSUE TITLE
Parser bug: last element in list cannot have a trailing comment

### ISSUE THREAD

**Issue by peterbourgon** [hashicorp/terraform#3249]
This works:

```
resource "something" {
    provisioner "remote-exec" {
        inline = [
            "echo foo",
            "echo bar",
        ]
    }
}
```

This doesn't:

```
resource "something" {
    provisioner "remote-exec" {
        inline = [
            "echo foo",
            "echo bar", # comment
        ]
    }
}
```

Fails with **Error loading Terraform: Error downloading modules: module some_thing: Error parsing .terraform/modules/dd6b603e544a5c946ee97edb36f04ac1/droplet.tf: Line 91, column 3: syntax error**.

**Comment by mitchellh** [comment]
Reproduced in a test case and working on this now.

**Comment by mitchellh** [comment]
Fixed: https://github.com/hashicorp/hcl/commit/4de51957ef8d4aba6e285ddfc587633bbfc7c0e8
