### ISSUE TITLE
Terraform is too impatient with DigitalOcean

### ISSUE THREAD

**Issue by wyattanderson** [hashicorp/terraform#325]
I've been trying to provision some DigitalOcean droplets with Terraform v0.2.2 on Mac OS X. Occasionally, the DO droplet provisioning takes a while (a few minutes) for whatever reason, and Terraform exits, saying it couldn't find the resource:

    digitalocean_droplet.salt_master: Creating...
      image:      "" => "ubuntu-14-04-x64"
      name:       "" => "do-salt-master"
      region:     "" => "nyc2"
      size:       "" => "512mb"
      ssh_keys.#: "" => "1"
      ssh_keys.0: "" => "YYYYYY"
    digitalocean_droplet.salt_master: Error: Error waiting for droplet (XXXXXXX) to become ready: couldn't find resource
    Error applying plan:

    1 error(s) occurred:

    * Error waiting for droplet (XXXXXXX) to become ready: couldn't find resource

Might be nice to increase the amount of time Terraform will wait for a droplet to spin up.

**Comment by pearkes** [comment]
I think 10 minutes was way too aggressive, so it's been increased to an hour. I thought about adding a configuration attribute for this, but in all real cases the droplets should be created in minutes, so this is more working around a potentially temporary issue with their API. Waiting longer is probably fine.

**Comment by giuffresoft79** [comment]
I have this problem. Can i resolve it?
