### ISSUE TITLE
[backend] fails to save state file to remote backend

### ISSUE THREAD

**Issue by rmammadli** [hashicorp/terraform#32506]
### Terraform Version

```shell
Terraform v1.3.7
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {

  required_providers {
    tls = {
      source = "hashicorp/tls"
      version = "4.0.4"
    }
}

  backend "remote" {
    hostname     = "artifactory.example.com"
    organization = "my-org"
    workspaces {
      name = "raw-terraform"
    }
  }
}


resource "tls_private_key" "key" {
  algorithm   = "RSA"
  rsa_bits    = "4096"
}

```

### Debug Output

https://gist.github.com/rmammadli/203940911c1db7566666254acedee21c

### Expected Behavior

Terraform state file would be uploaded / saved to 'remote' backend successfully.

### Actual Behavior

Error: Failed to save state
Error saving state: Error uploading state: 400
Error: Failed to persist state to backend

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Additional Context

**Note:** it works just fine with terraform v1.2.9
Artifactory JFrog is used as terraform backend repository:
https://www.jfrog.com/confluence/display/JFROG/Terraform+Backend+Repository

**Comment by alisdair** [comment]
Thanks for the report. Unfortunately this seems likely to be a server-side incompatibility with Artifactory's `remote` backend integration, which we don't have the ability to diagnose from our side. I'd recommend reporting this bug to JFrog, and if it results in a diagnosis which points to a Terraform bug, we can take a look at it.

**Comment by rmammadli** [comment]
@alisdair thanks for your prompt reply.
We will try to figure it out on Artifactory's JFrog side.

**Comment by crw** [comment]
Closing per information in https://github.com/hashicorp/terraform/issues/32506#issuecomment-1382360925
