### ISSUE TITLE
cli not respecting macOS DNS resolver config

### ISSUE THREAD

**Issue by mimizone** [hashicorp/terraform#32511]
### Terraform Version

```shell
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.48.0
+ provider registry.terraform.io/telmate/proxmox v2.9.11
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.3"

    required_providers {
        proxmox = {
            source = "telmate/proxmox"
            # version = "2.9.11"
        }
    }
}
```

### Debug Output

```
│ Error: Get "https://thehost.mydomain.net:8006/api2/json/cluster/nextid": dial tcp: lookup thehost.mydomain.net on 192.168.1.254:53: no such host
│
│   with proxmox_vm_qemu.moo-04,
│   on main.tf line 8, in resource "proxmox_vm_qemu" "moo-04":
│    8: resource "proxmox_vm_qemu" "moo-04" {
```

### Expected Behavior

the hostname should be resolved using a specific resolver set for the mydomain.net domain.
Those resolvers entries are created by the VPN client, and resolution is working properly in all applications and code (only dig/nslookup don't respect this configuration, which is expected).

### Actual Behavior

terraform uses the DNS configuration of the Wifi network interface, in /etc/resolv.conf (192.168.1.254 in the included debug logs)
which results in not resolving the host, because it is an internal machine only declared in our internal DNS server.

### Steps to Reproduce

Have a custom DNS server X.X.X.X with a specific record for thehost.mydomain.net
create a DNS resolver config on macOS:
```
sudo mkdir /etc/resolver
cat 'nameserver X.X.X.X' > /etc/resolver/mydomain.net
```
check the resolver is set
```
scutil --dns
```
check the config works
```
dscacheutil -q host -a name thehost.mydomain.net
```

use the following terraform.tf file
```
terraform {
  required_version = ">= 1.3"
    required_providers {
        proxmox = {
            source = "telmate/proxmox"
            # version = "2.9.11"
        }
    }
}
provider "proxmox" {
    pm_api_url = "https://thehost.mydomain.net:8006/api2/json"
    pm_tls_insecure = true
}
resource "proxmox_vm_qemu" "vm" {
    name = "vmname"
    target_node = "node"
    vmid = 100
}
```
do a terraform init and apply
```
terraform init
terraform apply
```

### Additional Context

I both tried to have IPv6 enabled and disabled on my Wifi DNS config. The issue stays.

I tried the brew binary version of terraform, the macOS pre compiled version on hashicorp web site (arm64 and amd64).

### References

An old similar bug was reported and said to be fixed and closed.
https://github.com/hashicorp/terraform/issues/26750

**Comment by jbardin** [comment]
Hi @mimizone,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help.

Thanks!

**Comment by mimizone** [comment]
thanks. I didn't think it was related to the provider. I'll check with that community.
