### ISSUE TITLE
AWS Terraform provideer should allow msk cluster configuration upgrade

### ISSUE THREAD

**Issue by alkajawla** [hashicorp/terraform#32517]
### Terraform Version

```shell
0.14.x and earlier versions.
```

### Use Cases

when trying to make any updates to the msk cluster configuration e.g. adding new configuration to msk cluster configuration, upgrading the msk cluster version , we get an error - **MSK Configuration: ConflictException: A resource with this name already exists , even though the msk cluster configuraiton allows versioning. 

Expected behaviour is - if we ar making updates to cluster configuration , then a new verison of the configuration should be created without any Name conflict errors

### Attempted Solutions

Updates are allowed if I change the cluster configuration name , in this case the old configuration is deleted and cluster runs with the new cluster configuration map

### Proposal

Expected behaviour is - if we ar making updates to cluster configuration , then a new verison of the configuration should be created without any Name conflict errors because the msk cluster allows versioning on the cluster configuration

**Comment by kmoe** [comment]
Thanks for the issue. This looks like an issue with the AWS provider: please open an issue at https://github.com/hashicorp/terraform-provider-aws/issues instead.
