### ISSUE TITLE
Support env vars for pg backend connection string / username, password and dbname as input

### ISSUE THREAD

**Issue by janaurka** [hashicorp/terraform#32525]
### Terraform Version

```shell
➜  ~ terraform version
Terraform v1.3.7
on linux_amd64
```

### Use Cases

As of now, the `pg` backend type only support a hard coded `conn_str` in the `backend` configuration according to:  https://developer.hashicorp.com/terraform/language/settings/backends/pg#configuration-variables and also the code does not read any environment variables: https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/pg/backend.go#L22-L26.

In contrast, eg the `azure` remote-state supports multiple env vars to be able to not check-in sensible data into your terraform code. -> https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/azure/backend.go#L78

This would be a great feature for the `pg` backend. 

### Attempted Solutions

-

### Proposal

Add support for environment variables, either one singe `conn_str` but having flexibility using `DB_NAME`, `DB_USER`, `DB_PASSWORD`, `DB_HOSTNAME` would be awesome.

**Comment by crw** [comment]
Thanks for this request!
