### ISSUE TITLE
It would be useful if `iam_user` exported an attribute that `aws_iam_access_key` would accept

### ISSUE THREAD

**Issue by kvz** [hashicorp/terraform#3252]
Hi,

I'd like to create `aws_iam_access_key`s for all my `aws_iam_user`s. I'm currently relying on the `users` var in both cases, but I think it would be prettier (not sure if you'd agree?) if `aws_iam_access_key` would rely on `aws_iam_user`:

```JSON5
variable "users" {
  default = {
    "0" = "nodeknockout"
    "1" = "staticshowdown"
  }
}

resource "aws_iam_user" "infra-hackathon-user" {
  count = 2
  name = "${lookup(var.users, count.index)}"
  path = "/hackathons/"
}

resource "aws_iam_access_key" "infra-hackathon-access-key" {
  count = 2
  user = "${lookup(var.users, count.index)}"
}
```

However, since `aws_iam_user` only exports `unique_id` and `arn` and those are not acceptable inputs to `aws_iam_access_key`, I'm not having much luck.

Very low prio I'd say, mostly also just interested if you'd agree.

**Comment by phinze** [comment]
Hi @kvz - All attributes that are settable on any resource are also exported, so `${aws_iam_user.infra-hackathon-user.name}` is available for reference. :+1:

**Comment by kvz** [comment]
Thanks @phinze. I was being silly indeed. For those stumbling upon this issue, I needed this syntax:

```json5
resource "aws_iam_access_key" "infra-hackathon-access-key" {
  // ...
  user  = "${element(aws_iam_user.infra-hackathon-user.*.name, count.index)}"
}
```
