### ISSUE TITLE
Clarity needed on the delimiter specified in syntax of JOIN function

### ISSUE THREAD

**Issue by adi-garg** [hashicorp/terraform#32528]
### Terraform Version

```shell
Terraform v1.3.6
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/functions/join

### What is the docs issue?

It may help to reword

> join produces a string by concatenating together all elements of a given list of strings with the given delimiter.

TO

join produces a string by concatenating together all elements of a given list of strings with the given delimiter **in output string**.

It may also help to add another example showing the above:
```
> join("-",["jack","123","India"])
"jack-123-India"
```

### Proposal

Has been recommended above.

**Comment by crw** [comment]
Thanks for this report! I've informed the docs team.

**Comment by Nathan12399** [comment]
I am working on this doc change.
