### ISSUE TITLE
`terraform state show -json ...` throws "flag provided but not defined: -json"

### ISSUE THREAD

**Issue by jgspratt** [hashicorp/terraform#32529]
### Terraform Version

```shell
Terraform v1.3.6
on linux_amd64
```

### Terraform Configuration Files

N/A - help file confirms this option is missing.

### Debug Output

```
Error parsing command-line flags: flag provided but not defined: -json
```

### Expected Behavior

It should have output json.

### Actual Behavior

```
Error parsing command-line flags: flag provided but not defined: -json
```

### Steps to Reproduce

```
terraform state show -json module.common_no_proxy.aws_security_group.instance
```

**Comment by jbardin** [comment]
Hi @jgspratt,

The `terraform state` command does not have a `-json` option. If you want the state output in a machine readable json format, you can use the `terraform show -json` command. 

Thanks!
