### ISSUE TITLE
Apply VM step failing due to Error verifying GPG signature for provider "azurerm"

### ISSUE THREAD

**Issue by bb2491** [hashicorp/terraform#32535]
### Terraform Version

```shell
terraform_0.12.28_linux_amd64
```

### Terraform Configuration Files

Error: Could not satisfy plugin requirements

Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".

Error: provider.azurerm: no suitable version installed
  version requirements: "~> 2.20.0,~> 2.20.0"
  versions installed: none

Error: provider.tls: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

##[error]Script failed with exit code: 1
/usr/bin/az account clear
Finishing: Applying vmbatch

### Debug Output

https://dev.azure.com/ACC-Azure-04/29712-XEIP/_build/results?buildId=156845&view=logs&j=cad9d0ec-ffa9-548c-0353-94031b05d5c9&t=2f4db266-4fbc-59a1-76b6-4d08ccd7ecee&l=217

### Expected Behavior

Pipeline should finish, it is failing

### Actual Behavior

Pipeline fails

### Steps to Reproduce

VM Jump Apply:
Starting: Applying vmbatch
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.215.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
azure-cli                         2.44.1

core                              2.44.1
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

Python location '/opt/az/bin/python3'
Extensions directory '/home/AzDevOps/.azure/cliextensions'

Python (Linux) 3.10.8 (main, Jan 10 2023, 15:52:02) [GCC 7.5.0]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
Setting AZURE_CONFIG_DIR env variable to: /agent/_work/_temp/.azclitask
Setting active cloud to: AzureCloud

### Additional Context

Pipeline is failing at Applying 'vmbatch'

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
