### ISSUE TITLE
Azurerm_managed_disk resize deallocates virtual machine before failing in specific case with inconsistent error messages when attempting to hot extend

### ISSUE THREAD

**Issue by RawPatty** [hashicorp/terraform#32534]
### Terraform Version

```shell
latest (1.3.7)
```

### Terraform Configuration Files

```terraform
resource "azurerm_managed_disk" "f_drive" {
  for_each = {
    for k in local.f_drive_lun_map : k.datadisk_name => k
  }
  zones                = can(lookup(var.environment_configuration, "availability_zone")) ? tolist([tostring(lookup(var.environment_configuration, "availability_zone")[0])]) : null
  name                 = each.value.datadisk_name
  location             = var.location
  resource_group_name  = azurerm_resource_group.rg.name
  storage_account_type = lookup(var.environment_configuration, "f_disk_SKU", null)
  create_option        = try(var.environment_configuration["disk_create_option"], "Empty")
  disk_size_gb         = lookup(var.environment_configuration, "f_drive_disk_size", null)
  tags                 = lookup(var.environment_configuration, "tags", null)
  
}
```

### Debug Output

-

### Expected Behavior

Expected error that would say "Disk of size x(<=4096) cannot be resized to 8192 GB while it is attached to a running VM.
The expectation is that the machine would not be changed

### Actual Behavior

Received the error below, the VM was deallocated and then the apply errored

Error: Error updating Managed Disk "REDACTED" (Resource Group "REDACTED"): compute.DisksClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Disks cannot be resized beyond 4095 GiB when attached to a VM. Detach disk REDACTED from VM REDACTED and try again. If caching is enabled for this disk, it will not be supported for disks greater than 4095 GiB."

### Steps to Reproduce

1) changed data disk size from 4090GiB to 8192 GiB for the module azurerm_managed_disk 
2) Planned and applied change

### Additional Context

some investigation from me

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/John/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/John/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/John/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-NZ style='tab-interval:36.0pt;word-wrap:break-word'>

<p class=MsoNormal><span style='mso-fareast-language:EN-US'>Terraform behaviour
is as below when resizing data disks on running VMs:<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-language:EN-US'><o:p>&nbsp;</o:p></span></p>

Action | Result | Notes
-- | -- | --
4GiB ->   4095GiB     (case 1) | Hot extend with   no issue | no outage is   required
Below 4095GiB to   4096GiB or above   (case 2) | Error with outage | To successfully   resize, I had to manually detach the disk and reapply the plan. The plan   would create a new attachment object and make a data disk  change to the   size   This use case   causes an expected outage to the virtual machine, but also fails.   Please see   attached screenshot
4096GiB to   8192GiB +   (case 3) | Error with no   outage | To successfully   resize from here with Terraform, the VM needed to be manually shut down   before applying the plan. This would require an outage to successfully apply   Please see   attached screenshot
8192GiB + | Hot extend with   no issues | No outage is   required

<p class=MsoNormal><span style='mso-fareast-language:EN-US'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-language:EN-US'>The inconsistency
in the behaviour contradicts the error shown in case 3, which suggests that it also
covers the use case of case 2, but it did not, and was the cause of the outage.<o:p></o:p></span></p>

</body>

</html>

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
