### ISSUE TITLE
Missing TypeStruct

### ISSUE THREAD

**Issue by lwander** [hashicorp/terraform#3253]
Currently, if a schema wants to support nested fields, it has to use `TypeList` for a configuration like this:

```
resource "example" "default" {
    unique_struct {
        field1 = "value1"
        field2 = "value2"
    }
}
```

However, the schema definition cannot make it explicit that `unique_struct` in the above example can only appear once per resource, leaving it up to the provider rather than the schema validation to reject the following configuration

```
resource "example" "default" {
    unique_struct {
        field1 = "value1"
        field2 = "value2"
    }

    unique_struct {
        field1 = "value3"
        field2 = "value4"
    }
}
```

I'd like to fix this by implementing `TypeStruct` as an available type for schema elements. As I was poking through the code, I found [this commit](https://github.com/hashicorp/terraform/commit/f416e0edf02226a5c91c939048e59f2129d1136e) adding `typeObject`, but is otherwise not documented. Is `typeObject` the start of something like `TypeStruct`? Is there anything else I should know before getting started?

@mitchellh @armon @radeksimko

**Comment by apparentlymart** [comment]
IIRC ``typeObject`` is how nested ``schema.Resource`` elements are represented.

The schema structure makes it a bit awkward to represent a single nested object as you want to do, but I think adding a new type where the ``Elem`` is then a resource is the closest thing we can do with the current structure. It's a bit strange to say "this is a single item whose element is a resource", but it'd sure be useful!

**Comment by mitchellh** [comment]
I believe this is handled by: #2275

(Not done yet, open issue)
