### ISSUE TITLE
Null Resource-Feedback

### ISSUE THREAD

**Issue by adi-garg** [hashicorp/terraform#32540]
### Terraform Version

```shell
Terraform v1.3.6
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource

### What is the docs issue?

It may help to:

1.Enhance the definition as:

> The _null_resource_ helps to execute any command remotely or locally to provision any resource or even to create a configuration file or perform some command or scripts to change some configuration. 
> It is essential to understand how to use the Terraform provisioner and triggers, which are used with null_resource.

2.Enhance the **triggers** explanation with regard to variable name and how to make this null block run each time, as suggested below:

> The variable on left can take any arbitrary name.
> Terraform does not care about the naming here. What matters is when those values change. 

> A common way to have the null block triggered **EACH TIME** `terraform apply` is run:
> Making use of timestamp() function-
> Every time  you execute Terraform, you will always generate a date (timestamp)which changes and triggers fresh run on null block.

```
triggers = {
    always_run = timestamp()
  }
```
NOTE-USE ANY RANDOM VARIABLE NAME ON LEFT
`timestamp = timestamp()`

### Proposal

Has been covered above.

**Comment by jbardin** [comment]
Hi @adi-garg,

Thanks for the notes! The `null_resource` is developed separately in the [Null Provider](https://github.com/hashicorp/terraform-provider-null/). Note that the upcoming v1.4 release will contain the builtin `terraform_data` resource which will have documentation in this repository. We however don't normally recommend fashioning a configuration which cannot converge into an empty plan, so the note about using `timestamp` may still be relegated to the function's own documentation.

Thanks!

**Comment by adi-garg** [comment]
Hi,
Still did not understand- the current documentation on null resource in official terraform documentation is hard to interpret.

> The null_resource resource implements the standard resource lifecycle but takes no further action.
This is NOT very intuitive.


Further, doesn't it need to be highlighted that a **random variable** in trigger block is used as shown in example.

Regards,
Aditya Garg

**Comment by adi-garg** [comment]
Wonder why issues get closed without proper communication?

**Comment by crw** [comment]
The correct place to file an issue is in the Null Provider repository: https://github.com/hashicorp/terraform-provider-null/issues

As answered in the comment, https://github.com/hashicorp/terraform/issues/32540#issuecomment-1397147708

**Comment by adi-garg** [comment]
Seems like we are just going in circles instead of intending to address a documentation issue.
If Hashicorp feels it is not requiring attention,I don't think it makes sense for me to follow it up so many times to improve their documentation.
