### ISSUE TITLE
Documentation Title Error

### ISSUE THREAD

**Issue by pavanjava** [hashicorp/terraform#32558]
### Terraform Version

```shell
0.13+
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/machine_learning_datastore_blogstorage

### What is the docs issue?

![Screenshot 2023-01-22 at 8 35 50 PM](https://user-images.githubusercontent.com/25398886/213923093-0c0288b1-5c1b-4a00-aa45-d3e3f2f25e2b.png)

the left navigation says "Azure blog storage" but that has to be "blob storage" instead..

### Proposal

please correct the typo

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
