### ISSUE TITLE
Error In Doc while creating the ML blob storage

### ISSUE THREAD

**Issue by pavanjava** [hashicorp/terraform#32559]
### Terraform Version

```shell
0.13+
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/machine_learning_datastore_blogstorage

### What is the docs issue?

![Screenshot 2023-01-23 at 6 03 36 AM](https://user-images.githubusercontent.com/25398886/213949062-77bb3414-85d4-481a-89ad-7ff1c3cd2ea7.png)

### Proposal

resource_manager_id is part of "azurerm_storage_container" but the doc is trying to get it from "azurerm_storage_account", hence the script fails

### References

`
resource "azurerm_storage_container" "az_storage_container" {
  name                  = "ml-storage-acct-container"
  storage_account_name  = azurerm_storage_account.ml_storage_acct.name
  container_access_type = "private"
}

resource "azurerm_machine_learning_datastore_blobstorage" "ml_datastore_blobstorage" {
  name                 = "ml_datastore"
  workspace_id         = azurerm_machine_learning_workspace.ml_workspace.id
  storage_container_id = azurerm_storage_container.az_storage_container.resource_manager_id
  account_key          = azurerm_storage_account.ml_storage_acct.primary_access_key
}
`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
