### ISSUE TITLE
Terraform Plan hands for around a minute when requesting backend/local state lock

### ISSUE THREAD

**Issue by jquinn99002** [hashicorp/terraform#32562]
### Terraform Version

```shell
SimpleSetup> terraform version  
Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.31.0
+ provider registry.terraform.io/hashicorp/azurerm v3.36.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "= 1.3.4"
  backend "local" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.36.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "2.31.0"
    }
  }
}
provider "azurerm" {
  features {}
}
```
No other files or code required.

### Debug Output

https://gist.github.com/jquinn99002/aa3211b29d8c0a660880ee14b4455ba9

### Expected Behavior

line entry `backend/local: requesting state lock for workspace "default"` should only take a few seconds at most to complete

### Actual Behavior

It takes between 1 and 2 minutes to acquire the state lock, in the example we can see it took 1 minute and 27 seconds before we get another log entry.

### Steps to Reproduce

1. $env:TF_LOG = "TRACE"
2. terraform init
3. terraform plan  > output.txt 2>&1

**Comment by jbardin** [comment]
Hi @jquinn99002,

Can you provide any more information about your system? It appears to be winning Windows, but what is the backing filesystem for the local state? Can you trace the process at all to see what exactly is being executed on the system?

Between those two log lines we only do a few basic filesystem operations, making sure the directory exists, and then reading or creating a state file -- the actual lock call is not taking any measurable time at all.

Thanks!

**Comment by jquinn99002** [comment]
After removing Terraform and downloading it again, and another reboot, this issue stopped occuring and has not since, so I suspect something else was causing a lock on the file.
Let's close this issue as it has not repeated for two weeks now.
