### ISSUE TITLE
Specify MSI in azurerm backend 

### ISSUE THREAD

**Issue by kraduk** [hashicorp/terraform#32575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently if you use the azurerm backend for storing the state file and use MSI for authentication you will have something like below. This i fine and works well. What does not work well is if you have multiple MSI bound to the vm, app etc as there is no way to select them. By default it seems to use the system assigned MSI if bound, and ignore the user ones. If you have multiple user ones in not sure what the selection is. Azure cli provides the functionality to select the user-msi of choice so its a valid use case. Support for variablizing it as well would be highly desirable

```hcl
terraform {
  backend "azurerm" {
    resource_group_name  = "terraform-rg"
    storage_account_name = "devops"
    container_name       = "terrformstates"
    key                  = "key.tfstate"
    subscription_id      = "<sub_id>"
    tenant_id            = "<tenant_id>"
    use_msi              = true
  }
}

# this selects the system msi, or user one if only a user is assigned
az login --identity

# this selects the specific user MSI
az login --identity -u <msi_id>

# something like this would suffice

terraform {
  backend "azurerm" {
    resource_group_name  = "terraform-rg"
    storage_account_name = "devops"
    container_name       = "terrformstates"
    key                  = "key.tfstate"
    subscription_id      = "<sub_id>"
    tenant_id            = "<tenant_id>"
    use_msi              = true
    msi_id               = "<ID>"
  }
}

```

### New or Affected Resource(s)/Data Source(s)

backend

### Potential Terraform Configuration

```hcl
# something like this would suffice

terraform {
  backend "azurerm" {
    resource_group_name  = "terraform-rg"
    storage_account_name = "devops"
    container_name       = "terrformstates"
    key                  = "key.tfstate"
    subscription_id      = "<sub_id>"
    tenant_id            = "<tenant_id>"
    use_msi              = true
    msi_id               = "<ID>"
  }
}

```
```

**Comment by crw** [comment]
I am doing clean-up on old waiting-response issues. As this issue has not seen a response since the previous post, I am going to close this. Please let me know if you are experiencing this issue and can answer the questions raised in the previous post. Thanks!
