### ISSUE TITLE
unable to get packages from https://apt.releases.hashicorp.com

### ISSUE THREAD

**Issue by magni2000** [hashicorp/terraform#32578]
### Terraform Version

```shell
this is not an issue with a specific terraform version we are unable to get apt packages from the site https://apt.releases.hashicorp.com
```

### Terraform Configuration Files

not relevant

### Debug Output

apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main". Reason: exit status 100

### Expected Behavior

we should be able to add https://apt.releases.hashicorp.com to our apt repos

### Actual Behavior

we get an error trying to access download apt packages

### Steps to Reproduce

command curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add
apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

**Comment by crw** [comment]
Please follow the instructions here: https://www.hashicorp.com/official-packaging-guide

Please see https://github.com/hashicorp/terraform/pull/32566 for more on this issue. Please let me know in this thread if you are still having problems or if you are seeing a new issue. Thanks!
