### ISSUE TITLE
Error while import BACPAC into the new database

### ISSUE THREAD

**Issue by AnnaBarabas** [hashicorp/terraform#32588]
### Terraform Version

```shell
1.3.7
```

### Terraform Configuration Files

```resource "azurerm_mssql_database" "db1" {
  name                 = "${upper(terraform.workspace)}_MAIN_CONFIG"
  server_id            = azurerm_mssql_server.sqlsvr.id
  max_size_gb          = 1
  read_scale           = false
  sku_name             = "ElasticPool"
  elastic_pool_id      = azurerm_mssql_elasticpool.sqlelasticpool.id
  zone_redundant       = false
  collation            = "SQL_Latin1_General_CP1_CI_AS"
  storage_account_type = "Local"

  short_term_retention_policy {
    retention_days = 7
  }

  import {
    storage_uri                  = "https://********.blob.core.windows.net/database/EMPTY_CONFIG.bacpac"
    storage_key                  = data.azurerm_storage_account.storage-account-state.primary_access_key
    storage_key_type             = "StorageAccessKey"
    administrator_login          = azurerm_key_vault_secret.kv_secret_db.name
    administrator_login_password = azurerm_key_vault_secret.kv_secret_db.value
    authentication_type          = "Sql"
  }
}

resource "azurerm_mssql_database" "db2" {
  name                 = "${upper(terraform.workspace)}_MAIN"
  server_id            = azurerm_mssql_server.sqlsvr.id
  max_size_gb          = 5
  read_scale           = false
  sku_name             = "ElasticPool"
  elastic_pool_id      = azurerm_mssql_elasticpool.sqlelasticpool.id
  zone_redundant       = false
  collation            = "SQL_Latin1_General_CP1_CI_AS"
  storage_account_type = "Local"

  short_term_retention_policy {
    retention_days = 7
  }

  import {
    storage_uri                  = "https://**********.blob.core.windows.net/database/EMPTY.bacpac"
    storage_key                  = data.azurerm_storage_account.storage-account-state.primary_access_key
    storage_key_type             = "StorageAccessKey"
    administrator_login          = azurerm_key_vault_secret.kv_secret_db.name
    administrator_login_password = azurerm_key_vault_secret.kv_secret_db.value
    authentication_type          = "Sql"
  }
}

resource "azurerm_mssql_database" "db3" {
  name                 = "Logistics_${upper(terraform.workspace)}_MAIN"
  server_id            = azurerm_mssql_server.sqlsvr.id
  max_size_gb          = 5
  read_scale           = false
  sku_name             = "ElasticPool"
  elastic_pool_id      = azurerm_mssql_elasticpool.sqlelasticpool.id
  zone_redundant       = false
  collation            = "SQL_Latin1_General_CP1_CI_AS"
  storage_account_type = "Local"

  short_term_retention_policy {
    retention_days = 7
  }

  import {
    storage_uri                  = "https://***********.blob.core.windows.net/database/EMPTY_second.bacpac"
    storage_key                  = data.azurerm_storage_account.storage-account-state.primary_access_key
    storage_key_type             = "StorageAccessKey"
    administrator_login          = azurerm_key_vault_secret.kv_secret_db.name
    administrator_login_password = azurerm_key_vault_secret.kv_secret_db.value
    authentication_type          = "Sql"
  }
}
```

### Debug Output

https://gist.github.com/AnnaBarabas/778b7b572b5db49ebfbf5ee18c36c82d

### Expected Behavior

It should have successfully deployed all 3 database with no errors, instead it just deploys one if them.

### Actual Behavior

In the past terraform version (1.3.4) would have deployed the bacpac in the new databases successfully, but using the newer version (1.3.7) it fails from the first run and will work only on the second run after deleting the databases manually.

│ Error: while import bacpac into the new database PROD_MAIN (Resource Group rg): Code="ImportExportJobError" Message="The ImportExport operation with Request Id '3775c190-8b1a-4b46-b9a7-5dd54de98884' failed due to 'Could not import package.\nWarning SQL0: A project which specifies SQL Server 2017 as the target platform may experience compatibility issues with Microsoft Azure SQL Database v12.\nWarning SQL72012: The object [data_0] exists in the target, but it will not be dropped even though you selected the 'Generate drop statements for objects that are in the target database but that are not in the source' check box.\nWarning SQL72012: The object [log] exists in the target, but it will not be dropped even though you '."
│
│   with azurerm_mssql_database.db2,
│   on sql-db.tf line 100, in resource "azurerm_mssql_database" "db2":
│  100: resource "azurerm_mssql_database" "db2" { 

### Steps to Reproduce

1. terraform init
2. terraform apply
3. deployment fails with error mentioned before
4. delete manually the databases
5. terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by AnnaBarabas** [comment]
@jbardin would you elaborate a bit more how is this problem related to AzureRM, when going back from Terraform 1.3.7 to 1.3.4 resolves the issue? AzureRM version didn't change. Thank you in advance!

**Comment by jbardin** [comment]
Hi @AnnaBarabas, the error you are receiving is generated by the provider while applying the plan for the individual resource instances. It's not clear how any changes in Terraform would have affected the process if the same version of the provider were used. Is the plan output the same between v1.3.4 and 1.3.7? Any change there may provider a clue as to what is going on,  but given that this is an error from the provider it will probably be up to the provider to determine what the actual issue is.

**Comment by AnnaBarabas** [comment]
@jbardin I have checked the plans for both situation. Nothing should have changed more than the version of Terraform. I have tried even other versions, like 1.3.6 or 1.4.0(alpha). All versions higher than 1.3.4 have failed with the same error. 2 out of 3 databases are failing with the import. I am thinking that if it was the issue with the provider AzureRM, it shouldn't have worked for version 1.3.4.

**Comment by jbardin** [comment]
@AnnaBarabas, I don't doubt you are seeing some change in behavior between Terraform versions, but because the error is within the provider, it is not something we can debug from this side. The main changes in that release were around `terraform destroy` and pre/postcondition checks, neither of which are relevant to this configuration on a fresh `init` and `apply`. The provider developers are in a better position to determine what may have changed and what is causing the error.
