### ISSUE TITLE
Allow aws_acm_certificate to filter by tags

### ISSUE THREAD

**Issue by garciacu** [hashicorp/terraform#32585]
### Terraform Version

```shell
Terraform v1.3.7
```

### Use Cases

data "aws_acm_certificate" "domain_cert" does not allow filtering by tags, we have 2 imported certs on ACM with the same domain name, same type, etc. This causes _Terraform returns a "multiple certificates for domain found"_ error. 

### Attempted Solutions

Only viable solution is filtering but none of the arguments for data "aws_acm_certificate" allows filtering by tags

### Proposal

Allow tags as a filtering argument

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
