### ISSUE TITLE
Can't initialize S3 backend with AWS profile

### ISSUE THREAD

**Issue by dan-drew** [hashicorp/terraform#32592]
### Terraform Version

```shell
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.50.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/kreuzwerker/docker v3.0.1
```

### Terraform Configuration Files

```terraform
provider "aws" {
  profile = "xyz"
}

terraform {
  backend "s3" {
    bucket  = "xyz-ops"
    key     = "terraform/core/blah.tfstate"
    profile = "xyz"
    region  = "us-west-2"
    encrypt = true
  }
}
```

### Debug Output

**Note** this module was already initialized to S3 using AWS_xxxx environment variables as a workaround, hence the `using already-initialized, unchanged "s3" backend configuration` log statement. 
Otherwise the logging output was the same before using the workaround, which is to say none except `Attempting to use session-derived credentials` and then the error.

```
2023-01-27T09:31:38.904-0800 [INFO]  Terraform version: 1.3.7
2023-01-27T09:31:38.904-0800 [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2023-01-27T09:31:38.904-0800 [DEBUG] using github.com/hashicorp/hcl/v2 v2.15.0
2023-01-27T09:31:38.904-0800 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-01-27T09:31:38.904-0800 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2023-01-27T09:31:38.904-0800 [DEBUG] using github.com/zclconf/go-cty v1.12.1
2023-01-27T09:31:38.904-0800 [INFO]  Go runtime version: go1.19.4
2023-01-27T09:31:38.904-0800 [INFO]  CLI args: []string{"/home/dan/.asdf/installs/terraform/1.3.7/bin/terraform", "init"}
2023-01-27T09:31:38.904-0800 [TRACE] Stdout is a terminal of width 208
2023-01-27T09:31:38.904-0800 [TRACE] Stderr is a terminal of width 208
2023-01-27T09:31:38.904-0800 [TRACE] Stdin is a terminal
2023-01-27T09:31:38.904-0800 [DEBUG] Attempting to open CLI config file: /home/dan/.terraformrc
2023-01-27T09:31:38.904-0800 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-01-27T09:31:38.904-0800 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-01-27T09:31:38.904-0800 [DEBUG] ignoring non-existing provider search directory /home/dan/.terraform.d/plugins
2023-01-27T09:31:38.904-0800 [DEBUG] ignoring non-existing provider search directory /home/dan/.local/share/terraform/plugins
2023-01-27T09:31:38.904-0800 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2023-01-27T09:31:38.904-0800 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2023-01-27T09:31:38.904-0800 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2023-01-27T09:31:38.905-0800 [INFO]  CLI command args: []string{"init"}
Initializing modules...
2023-01-27T09:31:38.906-0800 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2023-01-27T09:31:38.906-0800 [DEBUG] Module installer: begin container_definition
2023-01-27T09:31:38.908-0800 [TRACE] ModuleInstaller: Module installer: container_definition <nil> already installed in ../../modules/aws/ecs_container_definition
2023-01-27T09:31:38.908-0800 [DEBUG] Module installer: begin container_definition.utils
2023-01-27T09:31:38.910-0800 [TRACE] ModuleInstaller: Module installer: container_definition.utils <nil> already installed in ../../modules/utils
2023-01-27T09:31:38.910-0800 [DEBUG] Module installer: begin service
2023-01-27T09:31:38.912-0800 [TRACE] ModuleInstaller: Module installer: service <nil> already installed in ../../modules/aws/ecs_service
2023-01-27T09:31:38.912-0800 [DEBUG] Module installer: begin service.aws_utils
2023-01-27T09:31:38.912-0800 [TRACE] ModuleInstaller: Module installer: service.aws_utils <nil> already installed in ../../modules/aws/utils
2023-01-27T09:31:38.912-0800 [DEBUG] Module installer: begin service.utils
2023-01-27T09:31:38.912-0800 [TRACE] ModuleInstaller: Module installer: service.utils <nil> already installed in ../../modules/utils
2023-01-27T09:31:38.913-0800 [DEBUG] Module installer: begin utils
2023-01-27T09:31:38.913-0800 [TRACE] ModuleInstaller: Module installer: utils <nil> already installed in ../../modules/utils
2023-01-27T09:31:38.913-0800 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json

Initializing the backend...
2023-01-27T09:31:38.920-0800 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 2408714440
2023-01-27T09:31:38.920-0800 [TRACE] Preserving existing state lineage "4fc49aaf-d83c-d6a9-f56e-868b99871b06"
2023-01-27T09:31:38.920-0800 [TRACE] Preserving existing state lineage "4fc49aaf-d83c-d6a9-f56e-868b99871b06"
2023-01-27T09:31:38.922-0800 [TRACE] Meta.Backend: working directory was previously initialized for "s3" backend
2023-01-27T09:31:38.922-0800 [TRACE] Meta.Backend: using already-initialized, unchanged "s3" backend configuration
2023-01-27T09:31:38.923-0800 [INFO]  Attempting to use session-derived credentials
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│
│
│
╵
```

### Expected Behavior

S3 backend successfully initialized

### Actual Behavior

Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.

### Steps to Reproduce

1. Ubuntu 22.04 (WSL VM on Win11), bash shell, terraform 1.37, AWS provider 4.50.0
2. `~/.aws/credentials` file with profile “xyz” which has full admin privileges + other profiles for other AWS accounts
3. Set aws provider to use profile “xyz” and local state (no backend defined)
4. Define any AWS resources and run `terraform apply`. All operations succeed using “xyz” profile.
5. Add “s3” backend definition with “xyz” profile.
6. Run `terraform init -reconfigure` or run clean by deleting `.terraform` and `*.tfstate` then `terraform init`

### Additional Context

- Other modules for other projects using s3 backend and other AWS profiles work fine, only this one profile on my machine has issues.
- Setting access and secret key via AWS_xxxx environment variables successfully initialized S3 backend. Access key and secret key are identical to those in the profile.
- Using any other profile successfully detects and tries to use the profile credentials (of course fails with access denied, but at least the correct error), so it is not an issue trying to find or parse the credentials file.
- Copying credentials from any other profile (or renaming any other profile “xyz”) again successfully detects and tries to use the profile credentials, so it is not an issue with the specific profile section definition in the credentials file.
- Attempting to generate new keys for this account still fails. The only noticeable difference is that all these new keys have “+” signs in them, whereas none of my other secret keys do.
- Co-worker with credentials for same account and secret key with “+” signs seems to work fine on their machine. Copying their profile info verbatim to my credentials file fails. Both using Ubuntu 22.04 VM, same terraform version and provider versions. Only known differences: I’m running VM via WSL on Windows with bash shell vs. VirtualBox on Mac with zsh shell

### References

- Original write up can be [found in forums here](https://discuss.hashicorp.com/t/s3-backend-fails-to-initialize-using-profile/48978/4)

**Comment by rasagithub** [comment]
I also resulted with the same error as above but managed to get through further, by running aws sso login before initialization.

 - aws sso login --profile <profile_name>
 - then, terraform init 

CODE BLOCK: 
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }
  backend "s3" {
    key                 = "<path>"
    bucket              = "<name_of_s3_bucket>"
    region              = "<aws_region>"
    profile             = "<profile_name>"
  }

  required_version = ">= 1.2.0"
}

provider "aws" {
  shared_config_files = ["~/.aws/config"]
  region              = "<aws_region>"
  profile             = "<profile_name>"
}

hope, it helps

**Comment by Mapel88** [comment]
Hi, 
I'm experiencing the same issue.
any updates on this?

Thanks

**Comment by kornpow** [comment]
> Turned out to be a very hard to see typo with the fonts on my machine: a capital K instead of lowercase.

Can you elaborate on this a bit? Which file had a typo? I have the same problem and pretty confident that I dont have a typo.

I have the same issue on my machine, which I can recreate like so:
Start work in the morning:
`aws sso login`
*Completed Login*
`terraform apply`
*ERROR*
```
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: SSOProviderInvalidToken: the SSO session has expired or is invalid
```
Example to show how a helper tool works (it just adds the credentials into the environment):

`aws-sso-util run-as -a 8675309 -r MyDevUserAccess env | grep "AWS"`
```
AWS_CREDENTIALS_EXPIRATION=2023-04-01T03:28:18Z
AWS_SESSION_TOKEN=my-token-here
AWS_ACCESS_KEY_ID=my-access-key-here
AWS_SECRET_ACCESS_KEY=my-key-here
```

For comparison (this should work, as I already logged-in in the first step:
`env | grep "AWS"`
```
AWS_PROFILE=myssoprofile
```

This works when using helper tool:
`aws-sso-util run-as -a 8675309 -r MyDevUserAccess terraform apply`

The key interesting piece, is that this `aws-sso-util` does not leave the credentials in the environment. However I only need to use the wrapper function 1 time (per day or per shell or so). For subsequent usage of terraform
`terraform apply`
works as expected.


# Some additional testing
*Delete SSO credentials*
```
rm ~/.aws/sso/cache/*
rm ~/.aws/cli/cache/*
```
*Run TF and see*
`terraform init -reconfigure`
*ERROR*
```
Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: SSOProviderInvalidToken: the SSO session has expired or is invalid
│ caused by: open /home/myuser/.aws/sso/cache/3dc4783b2b261f7bb50422d84f284a9334bacea7.json: no such file or directory
```
No idea where `/home/myuser/.aws/sso/cache/3dc4783b2b261f7bb50422d84f284a9334bacea7.json` is coming from!

*Try deleting `.terraform`*
```
rm -r .terraform
terrraform init
```
*SAME ERROR*
```
Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: SSOProviderInvalidToken: the SSO session has expired or is invalid
│ caused by: open /home/myuser/.aws/sso/cache/3dc4783b2b261f7bb50422d84f284a9334bacea7.json: no such file or directory
```

*Re-log into sso and view cache*
```
aws sso login
ls ~/.aws/sso/cache
```

```
total 16K
drwxrwxr-x 2 user user 4.0K Mar 31 09:57 .
drwxrwxr-x 3 user user 4.0K Jan 18 16:00 ..
-rw------- 1 user user 1.7K Mar 31 09:57 cb8dbfb97b3c6ec8d09df39a94e8375b36296a3c.json
-rw------- 1 user user 1.4K Mar 31 09:57 f07da0dcb6008d46ef2e0723892abdee2ad1b7e5.json
```
What is interesting here is `f07da0dcb6008d46ef2e0723892abdee2ad1b7e5.json` is actually an expired credential. Why does an expired credential get recreated? `cb8dbfb97b3c6ec8d09df39a94e8375b36296a3c.json` is a good one though.

*Create the SSO file TF desires*
`cp ~/.aws/sso/cache/cb8dbfb97b3c6ec8d09df39a94e8375b36296a3c.json ~/.aws/sso/cache/3dc4783b2b261f7bb50422d84f284a9334bacea7.json`

*It works*
```
terraform init

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing hashicorp/aws v4.61.0...
- Installed hashicorp/aws v4.61.0 (signed by HashiCorp)

Terraform has been successfully initialized!
```

So definitely something funky going on. I think this magical `~/.aws/sso/cache/3dc4783b2b261f7bb50422d84f284a9334bacea7.json` which terraform seems to really want is a key part of the problem, maybe someone knows where this file is coming from.
Hopefully this debugging procedure is helpful!

```
terraform --version
Terraform v1.4.0
aws --version
aws-cli/2.9.1 Python/3.9.11 Linux/6.0.6-76060006-generic exe/x86_64.pop.22 prompt/off
```

**Comment by dan-drew** [comment]
@kornpow 

> Can you elaborate on this a bit? Which file had a typo?

This was in `~/.aws/credentials` and seems to be an issue with the SDK that doesn't impact the AWS CLI, which is why I thought it was a Terraform bug. Specifically I had `aws_access_Key_id` instead of `aws_access_key_id`.

I'm assuming the CLI is either case-insensitive or converts keys to lower case when parsing the file, while the SDK does not. Note that I could reproduce with Ruby SDK and Terraform (Go SDK), both produced the exact same error and behaved correctly after fixing the typo. I did not with confirm the Python, Javascript or other AWS SDK languages.

**Comment by dan-drew** [comment]
@kornpow should also add this was with simple credentials (AWS keys) and not using SSO. I can't speak to why you would be having issues with that, but it's not related to the problem I reported.

**Comment by gdavison** [comment]
Thanks for the updates, @dan-drew. I'm glad you found the error.

@kornpow, you seem to be having a different issue that what was reported here. Can you please open a new issue? Can you also ensure that you're using a recent version of the provider and include debug logs (see https://developer.hashicorp.com/terraform/internals/debugging)

**Comment by loganpowell** [comment]
Sorry to ping on a closed issue, but I seem to be having the same problem when using `cdktf` on WSL2 (Windows 10 Enterprise):
```sh
aws_instance  Planning failed. Terraform encountered an error while generating this plan.

              ╷
              │ Error: configuring Terraform AWS Provider: failed to get shared config profile, personal-cdktf
              │
              │   with provider["registry.terraform.io/hashicorp/aws"],
              │   on cdk.tf.json line 31, in provider.aws[0]:
              │   31:       }
              │
              ╵
aws_instance  Operation failed: failed running terraform plan (exit 1)
```

I have my credentials in their respective locations and they seem to be getting picked up by the AWS CLI:

```sh
$ aws configure list-profiles
personal-cdktf
$
```
and I'm using that profile in my `main.ts` under the `AwsProvider`:

```diff
class MyStack extends TerraformStack {
    constructor(scope: Construct, id: string) {
        super(scope, id)

        new AwsProvider(this, 'AWS', {
            region: 'us-east-1',
+            profile: 'personal-cdktf',
            sharedConfigFiles: ['~/.aws/config'],
            sharedCredentialsFiles: ['~/.aws/credentials'],
        })

        const ec2Instance = new Instance(this, 'compute', {
            ami: 'ami-01456a894f71116f2',
            instanceType: 't2.micro',
        })

        new TerraformOutput(this, 'public_ip', {
            value: ec2Instance.publicIp,
        })
    }
}
```

I've googled around for about an hour, but I've tried everything I could find... nothing.

**Comment by loganpowell** [comment]
Sorry, found the issue [here](https://discuss.hashicorp.com/t/error-configuring-terraform-aws-provider-failed-to-get-shared-config-profile/45500/2)
