### ISSUE TITLE
features block requirement for azurerm provider

### ISSUE THREAD

**Issue by cveld** [hashicorp/terraform#32591]
### Terraform Version

```shell
Terraform v1.3.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.41.0

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

- easiness of use
- learning curve
- transparency of the tool

### Attempted Solutions

N/A

### Proposal

Currently the cli outputs:

```
 terraform plan
╷
│ Error: Insufficient features blocks
│
│   on <empty> line 0:
│   (source code not available)
│
│ At least 1 "features" blocks are required.
```

whenever a `features` block is not present in the `azurerm` provider definition.

Suggestion would be to include at least the trace why this error is thrown. E.g.

```
│ Error: Insufficient features blocks provided in configuration for azurerm provider
│
│   on <empty> line 0:
│   (source code not available)
│
│ At least 1 "features" blocks are required which can be left blank. E.g.
|  provider "azurerm" {
|    features {}
|  }
```

Actually I would like to learn why an empty `features` block is of any use at all. Maybe make it optional. Benefit would be that also the `azurerm` provider definition can be left out as well.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
