### ISSUE TITLE
How to access elements of a SET(data type)?

### ISSUE THREAD

**Issue by adi-garg** [hashicorp/terraform#32601]
### Terraform Version

```shell
Terraform v1.3.6
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/expressions/types#indices-and-attributes

### What is the docs issue?

1.Need input on how to access elements of the **set** data type,currently this section describes only lists and maps.

Infact,the section [here ](https://developer.hashicorp.com/terraform/language/values/variables#type-constraints)also missed out SETS.

2.Further it may help to emphasize that quotes are mandatory while using this notation to access elements of a MAP:

> In cases where a map might contain arbitrary user-specified keys, we recommend using only the square-bracket index notation (local.map["keyname"]).

may be updated as

> In cases where a map might contain arbitrary user-specified keys, we recommend using only the square-bracket index notation (local.map["keyname"]). The quotes for the key of key-value pair are mandatory.

### Proposal

TBD

**Comment by AlexPykavy** [comment]
Terraform outputted the following when I tried to access set elements by the `0` index:

```
│ Block type "contact" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific        
│ criteria, use a "for" expression with an "if" clause.
```

So, it's impossible to refer the element directly. It's logical taking into account the nature of Set data structure.

**Comment by crw** [comment]
Thanks for this report. That does seem like a glaring omission.

**Comment by brukshut** [comment]
I ran into this issue today. In this example, the AWS LB `security_groups` output is a set.
```
data "aws_lb_listener" "this" {
  arn = local.existing_lb_listener_arn
}

data "aws_lb" "this" {
  arn   = data.aws_lb_listener.this.load_balancer_arn
}
```
I need to access the first element in the `security_groups` output, which is a set. I am able to do this using a `for` expression. 
```
security_group_id        = [for i in data.aws_lb.this.security_groups : i][0]
```

**Comment by gavenkoa** [comment]
`tolist(my_set)[0]` is the same as `one(my_set)`

* https://developer.hashicorp.com/terraform/language/functions/one
* https://stackoverflow.com/questions/66069677/get-an-element-from-a-list-terraform

**Comment by hedaya-khalif** [comment]
You could just add the following blurb or include the example as well:

Accessing elements of a set directly by index is not supported because sets are unordered collections. However, you can convert a set to a list to access elements by index. 

Example: Accessing Elements of a Set

1. Define a Set:
```
variable "example_set" {
type    = set(string)
default = ["foo", "bar"]
}
```
3. Convert Set to List: 
```
locals {
  example_list = tolist(var.example_set)
}
```

5. Access Elements by Index:
```
output "first_element" {
  value = local.example_list[0]
}
output "second_element" {
  value = local.example_list[1]
}
```
