### ISSUE TITLE
GCP Target Region Proxy SSL Certificates Docs

### ISSUE THREAD

**Issue by iamyohann** [hashicorp/terraform#32602]
### Terraform Version

```shell
1.3.7
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_target_https_proxy

### What is the docs issue?

**Docs says**

> [ssl_certificates](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_target_http_proxy#ssl_certificates) - (Required) A list of RegionSslCertificate resources that are used to authenticate connections between users and the load balancer. Currently, exactly one SSL certificate must be specified.

However GCP API Documentation says

> sslCertificates[] | stringURLs to SslCertificate resources that are used to authenticate connections between users and the load balancer. At least one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates. sslCertificates do not apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.

https://cloud.google.com/compute/docs/reference/rest/v1/regionTargetHttpsProxies

**Comment by crw** [comment]
Hello @iamyohann,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use the community forum where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
