### ISSUE TITLE
terraform_remote_state not refreshing values of remote resource

### ISSUE THREAD

**Issue by MrDrMcCoy** [hashicorp/terraform#32613]
### Terraform Version

```shell
Terraform v1.3.7
on linux_amd64
```

### From our `terraform_infra` repo/state:
```terraform
# az_resource_group/aks.tf
resource "azurerm_kubernetes_cluster" "anark" {
  for_each = var.config.aks_regions
  name = "${var.resource_group.name}-${each.key}"
  location = each.key
  resource_group_name = var.resource_group.name
  lifecycle { ignore_changes=[ default_node_pool[0].node_count, default_node_pool[0].node_taints, tags ]}
  api_server_authorized_ip_ranges = ["0.0.0.0/0"]
  auto_scaler_profile {
    balance_similar_node_groups = true
    expander = "least-waste"
    scale_down_utilization_threshold = 0.25
    skip_nodes_with_local_storage = false
    skip_nodes_with_system_pods = false
  }
  azure_policy_enabled = true
  azure_active_directory_role_based_access_control {
    managed = true
    azure_rbac_enabled = true
  }
  ingress_application_gateway {
    gateway_id = azurerm_application_gateway.ingress[each.key].id
  }
  default_node_pool {
    kubelet_config {
      allowed_unsafe_sysctls = [
        "kernel.shm*",
        "kernel.sem",
        "fs.mqueue.*",
        "net.*"
      ]
      container_log_max_line = 2
      container_log_max_size_mb = 20
      cpu_cfs_quota_enabled = false
      cpu_cfs_quota_period = "200ms"
      image_gc_high_threshold = 25
      image_gc_low_threshold = 10
      topology_manager_policy = "best-effort"
    }
    linux_os_config {
      transparent_huge_page_defrag = "defer+madvise"
      transparent_huge_page_enabled = "madvise"
      swap_file_size_mb = each.value.sys_node.swap_size_mb
      sysctl_config {
        net_core_somaxconn = 163849
        net_ipv4_tcp_tw_reuse = true
        net_ipv4_ip_local_port_range_min = 32000
        net_ipv4_ip_local_port_range_max = 60999
        vm_max_map_count = 262144
      }
    }
    enable_auto_scaling = each.value.sys_node.autoscale
    enable_host_encryption = true
    max_count = (
      each.value.sys_node.autoscale ?
      each.value.sys_node.nodes_max : null)
    max_pods = each.value.sys_node.pods_max
    min_count = (
      each.value.sys_node.autoscale ?
      each.value.sys_node.nodes_min : null)
    name = "sys"
    node_count = each.value.sys_node.nodes_min
    os_disk_size_gb = each.value.sys_node.disk_size_gb
    upgrade_settings { max_surge = each.value.max_surge }
    vm_size = each.value.sys_node.vm_size
    vnet_subnet_id = tolist(azurerm_virtual_network.anark[each.key].subnet)[0].id
    zones = [1,2,3]
  }
  dns_prefix = "anark-${var.resource_group.name}-${each.key}"
  identity { type = "SystemAssigned" }
  kubernetes_version = each.value.kubernetes_version
  local_account_disabled = false
  network_profile {
    dns_service_ip = "10.0.255.254"
    docker_bridge_cidr = "192.168.0.0/16"
    network_plugin = "azure"
    network_policy = "azure"
    service_cidr = "10.0.0.0/16"
  }
  role_based_access_control_enabled = true
  sku_tier = "Paid"
  linux_profile {
    admin_username = "anark"
    ssh_key { key_data = var.key_vault["ssh-pub-anark-support"].value }
  }
  oidc_issuer_enabled = true
  windows_profile {
    admin_username = "anark"
    admin_password = var.key_vault["aks-${var.resource_group.name}-admin-pass"].value
  }
  workload_identity_enabled = true
  tags = {
    last_updated = timestamp()
    managed_by = "terraform_infra"
  }
}
output "azurerm_kubernetes_cluster_anark" {
  value = azurerm_kubernetes_cluster.anark
}
```
`terraform console` output of desired value:
```shell
module.az_resource_group["dev2"].azurerm_kubernetes_cluster_anark["centralus"].oidc_issuer_url 
"https://centralus.oic.prod-aks.azure.com/<redacted>/<redacted>/"
```
The change to create this value was applied with `-target`.

### From our `terraform_tenant` repo/state:
```terraform
data "terraform_remote_state" "infra" {
  backend = "azurerm"
  config = {
    container_name = var.infra_container
    resource_group_name = var.infra_group
    storage_account_name = var.infra_account
    key = var.infra_key
  }
}
```
`terraform console` output of desired value after running `terraform plan -refresh`:
```shell
data.terraform_remote_state.infra.outputs.az_resource_groups[var.resource_group].azurerm_kubernetes_cluster_anark["centralus"].oidc_issuer_url
""
```

### Debug Output

[tf.log.gz](https://github.com/hashicorp/terraform/files/10560041/tf.log.gz)

### Expected Behavior

`terraform_tenant` should retrieve the updated value from `terraform_infra`'s state.

### Actual Behavior

The old value, an empty string, is retrieved.

### In `terraform_infra`:
1. Make change to `azurerm_kubernetes_cluster` to set `oidc_issuer_enabled` = `true`
2. Apply targeted change with `terraform apply -refresh -target='module.az_resource_group["dev2"].azurerm_kubernetes_cluster.anark["centralus"]'`
3. Validate the attribute has desired data by running `module.az_resource_group["dev2"].azurerm_kubernetes_cluster_anark["centralus"].oidc_issuer_url` in `terraform console`

### In `terraform_tenant`:
1. Run `terraform apply -refresh`
2. `azurerm` provider spits out error for resource referencing `data.terraform_remote_state.infra.outputs.az_resource_groups[var.resource_group].azurerm_kubernetes_cluster_anark["centralus"].oidc_issuer_url` due to it being an empty string.

### References

- #22607
- <https://github.com/hashicorp/terraform-provider-azurerm/issues/20241>

**Comment by jbardin** [comment]
Hi @MrDrMcCoy,

It appears you are running `terraform` with `-target` which is not going to update everything in the state. The value you are inspecting via the console is `module.az_resource_group["dev2"].azurerm_kubernetes_cluster_anark["centralus"].oidc_issuer_url`, however the only value which `terraform_remote_state` has access to is the `az_resource_groups` root module output. If that output does not contain the data you are looking for, then `terraform_remote_state` cannot get you the data.

The `-target` option should not be used for regular updates to the state, and only as an intermediary measure when part of the configuration cannot be applied. Removing the use of `-target` here will ensure that the output has ben updated correctly.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by MrDrMcCoy** [comment]
@jbardin We have a cascade of outputs from our module resources down to the root module. We have historically had no issues reading the information we needed from a remote state this way, and indeed already do this for other attributes from this resource. Showing this is difficult without granting you access to our private repository, which we cannot do at this time. 

We used `-target` in this case because we wanted to only apply this change to our dev cluster so we can evaluate its safety and effectiveness before applying it to the other clusters, all of which are controlled by the same state. We believe this use case is reasonable. 

As mentioned above, the issue is not that the attributes are inaccessible, but that they are not getting updated for the remote state. Please explain why this issue cannot be supported.

**Comment by jbardin** [comment]
The `-target` flag is instructing terraform to include only the targeted resource and minimum set of dependencies required to evaluate it. The module outputs are not part of that targeted set, and not expected to be updated (IIRC Terraform may include the output if it can be evaluated to maintain compatibility with behavior in earlier versions of the CLI, but that is only going to work in the simplest cases.)

The only way to be certain that the outputs are updated, is to include all resources which could possibly contribute to that output's evaluation, which in general precludes using `-target`.
