### ISSUE TITLE
Dependancy  issue?

### ISSUE THREAD

**Issue by georgegil** [hashicorp/terraform#32623]
### Terraform Version

```shell
Terraform v1.3.7
on windows_amd64
```

### Terraform Configuration Files

deployment:
```
module "intl-dev-test_eus" {
  source = "git::ssh://git@ssh.dev.azure.com/...."

  providers = {
    azurerm = azurerm.intl-dev-test
  }

  rg_name                = "rg-networking"
  location               = "East US"
  dns_servers            = ["10.32.0.6", "10.32.0.7"]
  vnet_cidr              = ["10.32.69.0/24"]
  transit_vnet_id        = data.azurerm_virtual_network.eus2-transit.id
  snet_private_app_cidr  = ["10.32.69.0/26"]
  snet_private_data_cidr = ["10.32.69.64/26"]
  snet_private_web_cidr  = ["10.32.69.128/26"]


  additional_subnets = {

    snet-private-data-02 = {
      address_prefixes   = ["10.32.69.192/26"]
      service_endpoints  = []
      custom_route_table = false
      delegations = {
        flexibleServers = {
          name    = "Microsoft.DBforPostgreSQL/flexibleServers"
          actions = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
        }
      }
    }
  }

  tags = local.tags
}

```
module :

```

resource "azurerm_route_table" "services" {
  count                         = var.create_shared_route_table ? 1 : 0
  name                          = "route-${local.vnet_prefix}"
  location                      = var.location
  resource_group_name           = var.rg_name
  disable_bgp_route_propagation = false

  tags = var.tags

}

module "additional_subnets" {
  source = "./modules/subnets"

  for_each = var.additional_subnets

  tags = var.tags

  rg_name  = var.rg_name
  location = var.location

  vnet_name         = azurerm_virtual_network.az_vnet.name
  subnet_name       = each.value.subnet_name != null ? each.value.subnet_name : each.key
  address_prefixes  = each.value.address_prefixes
  service_endpoints = each.value.service_endpoints
  delegations       = each.value.delegations

  route_table_name = each.value.custom_route_table ? "${local.vnet_prefix}-${lower(each.key)}-route-table" : null
  route_table_id   = each.value.custom_route_table ? null : azurerm_route_table.services[0].id
  default_route_ip = each.value.custom_route_table ? var.default_route_ip : null
}

```

submodule:

```
resource "azurerm_route_table" "subnet" {
  count = var.route_table_id == null ? 1 : 0

  name                = var.route_table_name
  location            = var.location
  resource_group_name = var.rg_name

  disable_bgp_route_propagation = false

  tags = var.tags
}
```

### Debug Output

2023-02-03T12:18:48.839+0200 [TRACE] vertex "module.intl-dev-test_eus.module.additional_subnets.azurerm_route_table.subnet (expand)": failed expanding dynamic subgraph: Invalid count argument: The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends on.

2023-02-03T12:18:48.839+0200 [ERROR] vertex "module.intl-dev-test_eus.module.additional_subnets.azurerm_route_table.subnet (expand)" error: Invalid count argument

2023-02-03T12:18:48.839+0200 [TRACE] vertex "module.intl-dev-test_eus.module.additional_subnets.azurerm_route_table.subnet (expand)": visit complete, with errors

### Expected Behavior

Evaluate if a custom route table should be created without error.

### Actual Behavior

Error: Invalid count argument

  on .terraform\modules\intl-dev-test_eus\modules\subnets\main.tf line 25, in resource "azurerm_route_table" "subnet":
  25:   count = var.route_table_id == null ? 1 : 0

The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many        
instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends   
on.

### Steps to Reproduce

terraform plan

### Additional Context

Doubt is this is a provider bug as it seems to incorrectly error when calculating the dependency of the submodule components.

**Comment by georgegil** [comment]
worth adding below, and removing contitional on the .azurerm_route_table.services does not resolve the issue.

```
variable "create_shared_route_table" {
  description = "Create a shared Route Table for Standard Subnets? Defaults to `true`. NOTE: Can only be `false` when `custom_subnets` are used and all subnets are assigned a custom route table."
  type        = bool
  default     = true
}

```

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by georgegil** [comment]
if i repost it wihout a "?" is then no longer a question?

This is not a question, but rather a statement that the dependency is not able to work out the conditional on a submodule.

**Comment by jbardin** [comment]
Hi @georgegil,

The error indicates that the `count` value is unknown. This is not a bug in Terraform, rather a configuration error. The `route_table_id` variable value depends on computed attributes of a managed resource, and cannot be known until after that resource has been created.
