### ISSUE TITLE
io/ioutil is deprecated since Go v1.16. We should replace this package and its functions with io/os

### ISSUE THREAD

**Issue by zachary-walters** [hashicorp/terraform#32626]
### Terraform Version

```shell
v1.4.0-dev
```

### Use Cases

The io/ioutil package is no longer being maintained. This could lead to issues during future development of the project. 

### Attempted Solutions

The solution is to replace the ioutil package and its functions with the respective io/os functions: https://go.dev/doc/go1.16#ioutil

### Proposal

The solution is to replace the ioutil package and its functions with the respective io/os functions: https://go.dev/doc/go1.16#ioutil

**Comment by jbardin** [comment]
Closing for the same reasons mentioned in the PR. We will incorporate these changes over time.

Thanks!
