### ISSUE TITLE
Some attributes have incorrect names above their documentation

### ISSUE THREAD

**Issue by phill0555** [hashicorp/terraform#32636]
### Terraform Version

```shell
Not an issue with my own generated documentation.
```

### Affected Pages

The pages that have an issue to my knowledge are:  https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/lex_bot#nestedatt--bot_locales--intents--slots--value_elicitation_setting

### What is the docs issue?

The documentation for the `bot_locales.intents.slots.value_elicitation_setting` attribute have the title "Nested Schema for `bot_locales.intents.slots.obfuscation_setting`" instead. Navagating to the link for [bot_locales.intents.slots.value_elicitation_setting](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/lex_bot#nestedatt--bot_locales--intents--slots--value_elicitation_setting) shows the correct attributes for value_elicitation_settings, but the incorrect title.

There are more issue's like this in the AWSCC provider docs. 

### Proposal

I am not sure how the documentation is generated but it seems to be generating the correct link, and the correct documentation, but reading the wrong title.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
