### ISSUE TITLE
Unable to update authentication policy on built_in applications using Terraform

### ISSUE THREAD

**Issue by ClintonianSunBlaster** [hashicorp/terraform#32632]
### Terraform Version

```shell
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.41.0

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

The Okta provider does not have a resource that can update the authentication policy associated with built_in applications (e.g. Okta Dashboard, Okta Admin Console).

We need to assign a different authentication policy to the Okta Dashboard.

### Attempted Solutions

Tried to use various okta_app_* resources but no luck.

### Proposal

create an okta_app_builtin resource that allows new authentication policies to be assigned to the Okta Dashboard, Okta Admin Console, and Okta Browser Plugin.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
