### ISSUE TITLE
Terraform crashes in recent versions - invalid memory address or nil pointer dereference goroutine 3192

### ISSUE THREAD

**Issue by afzalch** [hashicorp/terraform#32645]
### Terraform Version

```shell
1.3.7
1.3.6
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 3192 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x223cde0, 0x3e36ac0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).managedResourceExecute(0xc003751440, {0x2b85518, 0xc00283a2a0})
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:128 +0x415
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstanceOrphan).Execute(0x0?, {0x2b85518?, 0xc00283a2a0?}, 0x20?)
	/home/circleci/project/project/internal/terraform/node_resource_plan_orphan.go:49 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc002e73c20, {0x2b85518, 0xc00283a2a0}, {0x7f239d5dfc98, 0xc003751440})
	/home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x256df60, 0xc003751440})
	/home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc002b09e60, {0x256df60, 0xc003751440}, 0xc006379a80)
	/home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/home/circleci/project/project/internal/dag/walk.go:304 +0xf65
time=2023-01-18T17:11:55Z level=error msg=1 error occurred:
	* exit status 11

***************************************
APPLY_RESULT = 11
***************************************

### Expected Behavior

Terraform should pass successfully, when downgrading the same code to v1.3.5 the code works

### Actual Behavior

Terraform crashes as shown with debug output above

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

Using terragrunt to wrap the terraform command

### References

https://github.com/hashicorp/terraform/issues/30950

**Comment by alisdair** [comment]
Hi @afzalch, thanks for reporting this issue.

Can you share a small configuration which reproduces this crash? Without being able to reproduce the problem it will be difficult to be sure that we've fixed it.

**Comment by jbardin** [comment]
@alisdair, I don't yet have a repro for a test, but I can see where the problem came from. The `readResourceInstanceState` method was refactored in such a way that it returns a `nil` value with no errors for some cases. This is apparently used by other callers, so I think the best course of action is to add another guard here until we can verify all call sites.

**Comment by joavilacr** [comment]
> Hi @afzalch, thanks for reporting this issue.
> 
> Can you share a small configuration which reproduces this crash? Without being able to reproduce the problem it will be difficult to be sure that we've fixed it.

Hi @alisdair I've seen this error occurring in terraform 1.3.6 and up when using the hashicorp **Helm** and **Kubernetes** providers.
```
terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.7.1"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.14.0"
    }
  }
}
```
Once you downgrade terrafrom version to 1.3.5, there is no crashing.

**Comment by alisdair** [comment]
@joavilacr Thanks for sharing that. Are you able to reproduce this issue with a small Helm & Kubernetes configuration? I'm still not able to find any way to reproduce the issue.

Can you also share more about which commands you're using, with which CLI flags, and what state you are in when it occurs?

**Comment by alisdair** [comment]
I've just merged two PRs which should fix this panic. They'll go out in the next 1.3 patch release, as well as in the upcoming 1.4.0. If you're able to build Terraform from the `v1.3` branch to check this, that'd be helpful.
