### ISSUE TITLE
Error with terraform import and count usage not happening with plan/apply

### ISSUE THREAD

**Issue by vbontempi** [hashicorp/terraform#32644]
### Terraform Version

```shell
terraform version
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.49.0
```

### Terraform Configuration Files

```terraform

variable "cidr_blocks" {
  type        = list(string)
  default     = ["10.10.10.0/24", "10.10.11.0/24", "10.10.12.0/24"]
}

variable "zones" {
  type        = list(string)
  default     = ["1", "2", "3"]
}

resource "ibm_is_vpc_address_prefix" "subnet_prefix" {
  
  count = length(var.cidr_blocks) > 0 ? length(var.zones) : 0
  name  = "${var.unique_id}-z-${var.zones[count.index]}"
  zone  = "${var.ibm_region}-${var.zones[count.index]}"
  vpc   = var.vpc_id
  cidr  = element(var.cidr_blocks, count.index)
}
```

### Debug Output

https://gist.githubusercontent.com/vbontempi/c99dfbe77056a013ddef6e9e4aa8f150/raw/e9a5d7b2be166784535b7a9226b46a4861a51e54/gistfile1.txt

### Expected Behavior

Resource imported correctly or terraform plan/apply failed

### Actual Behavior

Terraform import fails with the following error:
```
│ Error: Invalid count argument
│
│   on .terraform/modules/vpc/subnet/main.tf line 9, in resource "ibm_is_vpc_address_prefix" "subnet_prefix":
│    9:   count = length(var.cidr_blocks) > 0 ? length(var.zones) : 0
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work
│ around this, use the -target argument to first apply only the resources that the count depends on.
```

Terraform plan or apply complete successfully on the same template with the same input vars

### Steps to Reproduce

`terraform import module.resource_group.ibm_resource_group.resource_group[0] "[resource group id]"`

### Additional Context

I am trying to import the resource ibm_resource_group into the terraform state before running the apply, to have terraform to not avoid to create the already existing resource but to import it into the terraform state for future management with terraform.
Terraform plan shows the resource to be created and this confirms that the plan command completes successfully with the identical configuration and template
Terraform apply completes successfully in a context where the resource to be imported is not existing

for_each isn't expected to solve the issue but I am going to have a try  in the meantime

**Comment by jbardin** [comment]
Hi @vbontempi,

Thanks for filing the issue. The shown configuration will work as expected, but from the log output it appears you are using a significantly more complex configuration. If your configuration is otherwise working, you are encountering an issue like #28188 or #32329, which will require the ability to plan multiple actions and imports together. 

We can follow the linked issue for any progress on import improvements.

Thanks!
