### ISSUE TITLE
Allow setting plugin cache force via env var

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform#32656]
### Terraform Version

```shell
Terraform v1.3.7
on darwin_arm64
```

### Use Cases

Enabling the new CLI config setting added in #32494 to resolve #32205 requires adding to the CLI config file.
It would be convenient to use an env var (esp. in a CI type setting) or flag to set this vs. editing the config file.

Creating a feature request for it as suggested in https://github.com/hashicorp/terraform/pull/32494#issuecomment-1406703933

### Attempted Solutions

It would obviously also be possible to use a shell command to create and populate the config.

### Proposal
Add environment variable to support enabling this setting.

### References

- #32494
- #32205

**Comment by crw** [comment]
Thanks for this request!
