### ISSUE TITLE
aws_transfer_server: 'As2Transport must be specified to enable AS2 protocol'

### ISSUE THREAD

**Issue by jgohlke1** [hashicorp/terraform#32655]
### Terraform Version

```shell
Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.53.0
```

### Terraform Configuration Files

```
provider "aws" {
  region = "us-east-1"
}

resource "aws_transfer_server" "server" {
  protocols = ["AS2"]
}
```

### Debug Output

https://gist.github.com/jgohlke1/0999538426f8e41c9c7ebd1894fd6fee#file-aws_transfer_as2_tf_debug-txt

### Expected Behavior

Terraform\AWS provider should specify `As2Transports` under `ProtocolDetails` and default to `HTTP` when interacting with AWS API. It seems nothing is being specified currently. 

https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateServer.html

### Actual Behavior

The apply is failing with the following error

```
│ Error: creating Transfer Server: InvalidRequestException: As2Transport must be specified to enable AS2 protocol
│
│   with aws_transfer_server.server,
│   on all.tf line 5, in resource "aws_transfer_server" "server":
│    5: resource "aws_transfer_server" "server" {
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
