### ISSUE TITLE
documentation missing for terraform_data

### ISSUE THREAD

**Issue by rismoney** [hashicorp/terraform#32652]
https://github.com/hashicorp/terraform/pull/31757

missing terraform_data usage

**Comment by jbardin** [comment]
Hi @rismoney,

The `terraform_data` resource was only added to v1.4 which has not yet been released. Documentation will be merged and published once the final release is cut.

Thanks!

**Comment by jbardin** [comment]
Closing as changes are in the release branch and will be published once v1.4 is released.
