### ISSUE TITLE
Terraform Import : provider/azurerm: Network Security Group - facing issues on protocol casing at Import time TCP Tcp

### ISSUE THREAD

**Issue by priyapriyapriya3** [hashicorp/terraform#32650]
### Terraform Version

```shell
terraform 1.3.7
```

### Terraform Configuration Files

```terraform
...terraform config...
```
Terraform Import : provider/azurerm: Network Security Group - facing issues on protocol casing at Import time TCP Tcp
error expected <file>.protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP

### Debug Output

expected security_rule.0.protocol to be one of [* Tcp Udp Icmp Ah Esp], got TCP

### Expected Behavior

Terraform Import in TCP

### Actual Behavior

I have imported NSG from Azure using terraform import and them updated configuration file with the details for  terraform show
 Later to validate it when i run terraform init and terraform pls, it is throwing error on Protocol to be Tcp and it is given TCP

### Steps to Reproduce

terraform init
terraform validate / Terraform Plan

### Additional Context

I have seem similar error #13153, which was resolved. not sure why it is still the same

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
