### ISSUE TITLE
The following policy definition reference Is used in non-compliance messages do not exist in the assigned policy set definition

### ISSUE THREAD

**Issue by GurpreetxSingh90** [hashicorp/terraform#32668]
### Terraform Version

```shell
Terraform v1.2.7
on windows_amd64
```

### Terraform Configuration Files

```terraform
...terraform config...
```
data "azurerm_policy_definition" "mserp_tls_policy_service_bus" {
    display_name = var.display_name_bus
}

data "azurerm_policy_set_definition" "mserp_policy_initiative_definition" {
    display_name = var.display_name_initiative_definition
}

data "azurerm_subscription" "current" {}

resource "azurerm_subscription_policy_assignment" "mserp_tls_policy_service_bus_subscription" {
  name                 = var.policy_assignment_service_bus_subscription
  policy_definition_id = data.azurerm_policy_definition.mserp_tls_policy_service_bus.id
  subscription_id      = data.azurerm_subscription.current.id

  non_compliance_message {
    content = "Example non-compliance message will be used as opposed to default policy error"
    policy_definition_reference_id = data.azurerm_policy_set_definition.mserp_policy_initiative_definition.id
    
  }
}

### Debug Output

│ Error: creating Policy Assignment ID: (Assignment Name "Test_Subscription" / Scope "/subscriptions/remove due to security reason"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidCreatePolicyAssignmentRequest" Message="The policy assignment request is invalid. The following policy definition reference IDs used in non-compliance messages do not exist in the assigned policy set definition: '/subscriptions/remove due to security reason/providers/Microsoft.Authorization/policySetDefinitions/TLSPolicy_Grouped'."   

### Expected Behavior

Assign Policy set definition at subscription level with subscription policy assignment group

### Actual Behavior

Assignment at subscription level does not for policy set definition

### Steps to Reproduce

terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
