### ISSUE TITLE
AWS Batch JobDefinition functionality missing for EksProperties

### ISSUE THREAD

**Issue by er-san** [hashicorp/terraform#32662]
### Terraform Version

```shell
1.3.5
```

### Terraform Configuration Files

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_job_definition

any form of provisioning. nodeProperties and containerProperties pertain to ECS provisioning, you can not include those. eksProperties is missing from here, top level key

### Debug Output

eksProperties not found

### Expected Behavior

AWS Batch JobDefinition provisioned into AWS Batch, which would later allow a pod to run inside eks cluster.

for reference AWS cli doc for registering job definition: https://docs.aws.amazon.com/cli/latest/reference/batch/register-job-definition.html

CloudFormation JobDefinition: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html

Cloudformation JobDefinition EksProperties: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-eksproperties

### Actual Behavior

eks properties not found error. 

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

eksProperties works based on the links provided through CLI, which is how I am navigating this implementation on the JobDefinition portion.

unrelated but in case someone comes across it some other nuances is the Secrets implementation for multi secret setups seems to have bugs, I have a separate AWS ticket going in scope of EKS secrets.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by jbardin** [comment]
@calibrateersan, sorry I don't understand what you want me to elaborate. It seems you are looking for a feature in an AWS resource which exists in CloudFormation but not the provider? That is not something the Terraform CLI can change, you would need to file an issue with the linked provider.

**Comment by calibrateersan** [comment]
are you stating that I should have simply created this issue at https://github.com/hashicorp/terraform-provider-aws specifically? because its just a piece missing from the aws provider. if so I can create the issue there.

**Comment by jbardin** [comment]
Yes. This repo is for the Terraform CLI, which is not directly involved in any provider development.
