### ISSUE TITLE
Import/plan inconsistency introduced by 1.3.8

### ISSUE THREAD

**Issue by jbergknoff** [hashicorp/terraform#32661]
### Terraform Version

```shell
Terraform v1.3.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.54.0
```

### Terraform Configuration Files

```terraform
resource "aws_security_group" "sg" {
  name = "test"
  description = "test"
}
```

### Debug Output

Sorry, no debug output: I was testing the issue on my work computer, but have no public GitHub access there.

### Expected Behavior

The following behavior has changed between TF 1.3.7 and TF 1.3.8:

Preliminary: create an EC2 security group, e.g. `aws ec2 create-security-group --group-name test --description test`.

1. `terraform-1.3.7 init`
1. `terraform-1.3.7 import aws_security_group.sg sg-...`
1. `terraform-1.3.7 plan`: the plan is clean

Now, doing the same with TF 1.3.8:

1. `rm -rf terraform.tfstate .terraform*`
1. `terraform-1.3.8 init`
1. `terraform-1-3.8 import aws_security_group.sg sg-...`
1. `terraform-1.3.8 plan`

The plan is no longer clean:

```
# aws_security_group.sg will be updated in-place
~ resource "aws_security_group" "sg" {
    id = "..."
    name = "test"
  + revoke_rules_on_delete = false
    tags = {}
    # (7 unchanged attributes hidden)

  - timeouts {}
}
```

This poses a problem when using a clean plan as an indication that a set of imports matches expectations, e.g. when using [tfmigrate](https://github.com/minamijoyo/tfmigrate). My team saw this with two different providers (aws and mongodbatlas), so it's not specific to `aws_security_group` (that's simply one of the resources which exhibited the problem).

### Actual Behavior

The 1.3.8 behavior should match the 1.3.7 behavior (clean plan after following the steps above).

### Steps to Reproduce

See above

### References

Looking at the diff between TF 1.3.7 and 1.3.8, I am wondering if this is related to the `hashicorp/hcl` version bump, and [this change](https://github.com/hashicorp/hcl/pull/574).

**Comment by jbardin** [comment]
Hi @jbergknoff,

Thanks for filing the issue. The difference here is actually Terraform presenting a more correct plan. It turns out that the provider is returning an incorrect value for `timeouts` during import, and the plan is showing that block is not present in the config. Unfortunately this misbehavior of the provider was not anticipated, and the small fix for the plan is triggering a diff where there wasn't one before.

Applying these changes will update the state and prevent further diffs, but we'll have to look into how to avoid these changes since this was working previously.

Thanks!

**Comment by jbardin** [comment]
OK, after some investigation the behavior is a little more specific than just importing with the timeouts. It also relied on the provider not supplying the `revoke_rules_on_delete` value during import and inserting the default during the plan. If either the `timeouts` block wasn't written or the `revoke_rules_on_delete` was written to the state, the provider produces an empty plan. So it seems the legacy SDK can mask over 1 mistake, but combinations of them will now show up during the plan.

I don't see a way to continue to hide this change while also correctly supporting newer providers. The imported state returned by the provider is incorrect, and the plan is attempting to fix it.

**Comment by bflad** [comment]
Created https://github.com/hashicorp/terraform-plugin-sdk/issues/1145 downstream to track the SDK's errant inclusion of `timeouts` single nested block during `ImportResourceState`. The provider side has no access to configuration during import, so I would think that it is never valid to include this information into the state.

**Comment by jbardin** [comment]
Thanks @bflad!
Closing this one since there doesn't appear to be anything more we can do in core.

**Comment by jbergknoff** [comment]
For reference, the other resource we happened to see this issue with was [`mongodbatlas_cluster`](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_cluster.go)), which showed changes to `timeouts` and a boolean `provider_backup_enabled`.
