### ISSUE TITLE
setintersection() and/or keys() behave differently for var and local

### ISSUE THREAD

**Issue by moonlightbeamer** [hashicorp/terraform#32669]
### Terraform Version

```shell
1.2.1 or 1.3.8 both show same behavior
```

### Terraform Configuration Files

```terraform

# this file is to prove that there might be a bug in setintersection() or keys() in terraform v1.2.1
# that it treats local and var differently.
# I hope someone can help to confirm, or point out if I did something wrong?

# local.regions is to serve as the setintersection control set of strings 
# as the keys(s_v) has non-region-related keys
locals                    {
  regions               = ["region-1", "region-2"] 
}

# local.local_obj has the exact same data structure as of var.var_obj
locals                    {
  local_obj             = {
    collection_local    = {
      subnet_local      = {
        other_keys      = "somthing"
        region-1        = "cidr-for-region-1-for-local-obj"
        # region-2        = "cidr-for-region-2-for-local-obj"
      }
    }
  }
}

# var.var_obj is a map(map(object())) data structure, outter map is the collection of subnets, 
# inner map is the subnets within a collection, object is the subnet config
variable "var_obj"        {
  type                  = map(
    map                   (
      object              ({
        other_keys      = "whatever"
        region-1        = optional(string)
        region-2        = optional(string)
      })
    )
  )  
  default               = {
    collection_var      = {
      subnet_var        = {
        other_keys      = "something_else"
        region-1        = "cidr-for-region-1-for-var-obj"
        # region-2        = "cidr-for-region-2-for-var-obj"
      }
    }
  }
}

# local.transform-local and local.transform-var are two transforming locals to suite subnet resource needs
locals                    {
  transform-local       = flatten([
    for c_k,c_v        in local.local_obj : [
      for s_k, s_v     in c_v : [
        for rg         in setintersection(local.regions, keys(s_v)) : {
          name          = "${rg}-${s_k}"
          region        = rg
          ip_cidr_range = s_v[rg]
        } 
      ]   
    ]
  ])  
  
  transform-var         = flatten([
    for c_k,c_v        in var.var_obj : [
      for s_k, s_v     in c_v : [
        for rg         in setintersection(local.regions, keys(s_v)) : {
          name          = "${rg}-${s_k}"
          region        = rg
          ip_cidr_range = s_v[rg]
        } 
      ]   
    ]
  ])  
}     

# output.contrast is to show the different behavior of setintersection() and keys() on local and var
# I think it is a bug?
# as commenting out the region-2 in local and var has different behavior, 
# local behaves corretly, not producing region-2 record at all,
# but var transformer produced a region-2 record without ip_cidr_range, which will break the resource code execution
output "contrast"         {
  value                 = {
    transform-local     = local.transform-local
    transform-var       = local.transform-var
  }
}
```

if uncommenting the region-2 line, setintersection() and keys() behave exactly the same on local and var:
```
output:
contrast            : {
  transform-local   : [ 
    { 
      name          : "region-1-subnet_local"
      ip_cidr_range : "cidr-for-region-1-for-local-obj" 
      region        : "region-1" 
    } 
    { 
      name          : "region-2-subnet_local"
      ip_cidr_range : "cidr-for-region-2-for-local-obj" 
      region        : "region-2" 
    } 
  ]

  transform-var     : [ 
    { 
      name          : "region-1-subnet_var" 
      ip_cidr_range : "cidr-for-region-1-for-var-obj" 
      region        : "region-1" 
    } 
    { 
      name          : "region-2-subnet_var" 
      ip_cidr_range : "cidr-for-region-2-for-var-obj" 
      region        : "region-2" 
    } 
  ]
}
```
but if I comment out the region-2 line (as shown in code above), transform-var output is not desirable as it produces something that will cause malfunctioning
```
output:

contrast            : {
  transform-local   : [ 
    { 
      name          : "region-1-subnet_local"
      ip_cidr_range : "cidr-for-region-1-for-local-obj" 
      region        : "region-1" 
    } 
  ]

  transform-var     : [ 
    { 
      name          : "region-1-subnet_var" 
      ip_cidr_range : "cidr-for-region-1-for-var-obj" 
      region        : "region-1" 
    } 
    { 
      name          : "region-2-subnet_var" 
      region        : "region-2" 
    } 
  ]
}

### Expected Behavior

output:

contrast            : {
  transform-local   : [ 
    { 
      name          : "region-1-subnet_local"
      ip_cidr_range : "cidr-for-region-1-for-local-obj" 
      region        : "region-1" 
    } 
  ]

  transform-var     : [ 
    { 
      name          : "region-1-subnet_var" 
      ip_cidr_range : "cidr-for-region-1-for-var-obj" 
      region        : "region-1" 
    } 
  ]
}

### Actual Behavior

output:

contrast            : {
  transform-local   : [ 
    { 
      name          : "region-1-subnet_local"
      ip_cidr_range : "cidr-for-region-1-for-local-obj" 
      region        : "region-1" 
    } 
  ]

  transform-var     : [ 
    { 
      name          : "region-1-subnet_var" 
      ip_cidr_range : "cidr-for-region-1-for-var-obj" 
      region        : "region-1" 
    } 
    { 
      name          : "region-2-subnet_var" 
      region        : "region-2" 
    } 
  ]
}
```
### Steps to Reproduce

terraform plan

### Additional Context

in transformation block: 
c_k is the collection key (outter map): e.g. collection_local and collection_var
c_v is the collection map. 
s_k is the subnet key (inner map): e,g, subnet_local and subnet_var 
s_v is the subnet map. 
inside of the subnet map, there are three key-value pairs: 
three keys are: 
- other_keys 
- region-1 
- region-2. 

rg is the region, since keys(subnet map) has 3 keys and only 2 of them are region keys, so I setintersection() to filter out other_keys. which worked well when I provide both region-1 and region-2 keys. these two keys are optional. 

when I provide only 1 region key (region-1) and not provide the other region key (region-2), I expect the setintersection() to only include region-1 as the "intersection", in transform-local, it worked as I epxected. but in transform-var, it seems the setintersection() still resulted two region keys, the setintersection() didn't work properly.

### References

https://stackoverflow.com/questions/75430666/did-i-do-something-wrong-or-i-found-a-bug

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

The type of the variable `var.var_obj` contains a key which is not present in the literal local value, therefor produces a different output.

Thanks!

**Comment by moonlightbeamer** [comment]
Hi James, thanks for responding, but I have a hard time understanding what your comment...I deliberately moved a key on var.var_obj's default value to trigger this behavior, but since the key is optional, why can't I moved it and expect correct behavior?
    On Monday, February 13, 2023 at 06:55:11 a.m. MST, James Bardin ***@***.***> wrote:  
 
 


Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use the community forum where there are more people ready to help.

The type of the variable var.var_obj contains a key which is not present in the literal local value, therefor produces a different output.

Thanks!

**Comment by jbardin** [comment]
Hi @moonlightbeamer, the value of `var.var_obj` has a `region-2` attribute and therefor shows `region-2` values in the output. The difference between the var and local output is because the values are different. If you have more questions, please reference the community forums where there are many more user who may offer assistance.

**Comment by crw** [comment]
You can find [the community forum here](https://discuss.hashicorp.com/c/terraform-core/27). Thanks!
