### ISSUE TITLE
azure_virtual_network can't assign custom Resource Group

### ISSUE THREAD

**Issue by spuder** [hashicorp/terraform#3266]
There currently is no way (as far as I can tell) to create a network and assign it to a resource group. 

```
resource "azure_virtual_network" "mail-network" {
  "name" = "mail-network"
  address_space = ["172.16.0.0/24"]
  location = "West US"
  subnet {
     "name" = "subnet1"
     "address_prefix" = "172.16.0.0/28"
  }
}
```
![screenshot 2015-09-17 13 29 41](https://cloud.githubusercontent.com/assets/242382/9943689/371cf82a-5d40-11e5-8fad-2eca50794f2a.png)

---

If you create a network through the web interface, selecting a resource group is required. 

![screenshot 2015-09-17 13 31 43](https://cloud.githubusercontent.com/assets/242382/9943739/8231f11c-5d40-11e5-949e-e6f7567b1831.png)

Here is the api documentation. 

https://msdn.microsoft.com/en-us/library/azure/mt163661.aspx

The query should look like this: 

     https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/{resource-group-name}/providers/microsoft.network/virtualNetworks/{virtual-network-name}?api-version={api-version}

**Comment by spuder** [comment]
Additionally, it appears that the `azure_virtual_network` uses the clasic syntax.
![screenshot 2015-09-21 14 33 21](https://cloud.githubusercontent.com/assets/242382/10004212/bfcbaeac-606d-11e5-861e-e01d61fc095d.png)

**Comment by spuder** [comment]
Related to https://github.com/hashicorp/terraform/issues/3212

**Comment by dcarley** [comment]
Also related to #3089 and #3097

**Comment by phinze** [comment]
Thanks for the report, @spuder - closing this thread since I believe we have this covered in the linked issues.
