### ISSUE TITLE
terraform plugin crash due to memory issue

### ISSUE THREAD

**Issue by oussama-noble-ai** [hashicorp/terraform#32686]
### Terraform Version

```shell
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/azure/azapi v1.0.0
+ provider registry.terraform.io/hashicorp/aws v3.59.0
+ provider registry.terraform.io/hashicorp/azuread v2.31.0
+ provider registry.terraform.io/hashicorp/azurerm v3.30.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Stack trace from the terraform-provider-azurerm_v3.30.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1048afd90]

goroutine 838 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/redis.flattenRedisIdentity(0x140025e4ed0)
	github.com/hashicorp/terraform-provider-azurerm/internal/services/redis/redis_cache_resource.go:1081 +0x150
github.com/hashicorp/terraform-provider-azurerm/internal/services/redis.resourceRedisCacheRead(0x140035d8400, {0x105804ca0?, 0x140016b2c00?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/redis/redis_cache_resource.go:661 +0x560
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x106241240?, {0x106241240?, 0x14001c8f080?}, 0xd?, {0x105804ca0?, 0x140016b2c00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:712 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000e29ea0, {0x106241240, 0x14001c8f080}, 0x14001ddadd0, {0x105804ca0, 0x140016b2c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400047e5e8, {0x106241240?, 0x14001c8efc0?}, 0x14002bafe40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:613 +0x40c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400097db80, {0x106241240?, 0x14001c8eab0?}, 0x14001d1ccc0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:747 +0x39c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x105e4ef20?, 0x1400097db80}, {0x106241240, 0x14001c8eab0}, 0x14001d1cc60, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002a6c40, {0x1062534d8, 0x14000b4c680}, 0x14001bffc20, 0x140016475f0, 0x10a3a73d0, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1283 +0xb64
google.golang.org/grpc.(*Server).handleStream(0x140002a6c40, {0x1062534d8, 0x14000b4c680}, 0x14001bffc20, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1620 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x298

Error: The terraform-provider-azurerm_v3.30.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

terraform plan and apply should complete successfully 

### Actual Behavior

terraform-provider-azurerm_v3.30.0_x5 plugin crashes

### Steps to Reproduce

1. `terraform init`
2. terraform plan`

### Additional Context

So far I've tried:
1. closing other apps to free up memory
2. `export GODEBUG=asyncpreemptoff=1`
3. deleting my .terraform folder and lock file
4. Upgrading the azurem module to 3.34.0
Still hitting the same issue

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
