### ISSUE TITLE
DO Droplet atlas_artifact destroy error

### ISSUE THREAD

**Issue by bensojona** [hashicorp/terraform#3268]
Provisioning a DO droplet with `terraform apply` that uses an `atlas_artifact` `digitalocean.droplet`, then doing a `terraform destroy` destroys the resource appropriately but throws the below error.

`* Resource 'atlas_artifact.web' does not have attribute 'id' for variable 'atlas_artifact.web.id'`
 
See [gist](https://gist.github.com/bensojona/423a8f9c37291cf508dd) to reproduce. Will need to set environment variables `DIGITALOCEAN_TOKEN`, `ATLAS_TOKEN`, and `ATLAS_USERNAME`.

- Create DO droplet using Packer droplet.json template
- Upload public key `example.pub` to your DO account
- `terraform get`
- `TF_VAR_digital_ocean_token=$DIGITALOCEAN_TOKEN TF_VAR_atlas_token=$ATLAS_TOKEN TF_VAR_atlas_username=$ATLAS_USERNAME TF_VAR_ssh_fingerprint=3c:e3:4d:a6:81:22:ac:6e:41:c1:f6:85:e1:4b:0f:ec terraform apply`
- `TF_VAR_digital_ocean_token=$DIGITALOCEAN_TOKEN TF_VAR_atlas_token=$ATLAS_TOKEN TF_VAR_atlas_username=$ATLAS_USERNAME TF_VAR_ssh_fingerprint=3c:e3:4d:a6:81:22:ac:6e:41:c1:f6:85:e1:4b:0f:ec terraform destroy`
- `TF_VAR_digital_ocean_token=$DIGITALOCEAN_TOKEN TF_VAR_atlas_token=$ATLAS_TOKEN TF_VAR_atlas_username=$ATLAS_USERNAME TF_VAR_ssh_fingerprint=3c:e3:4d:a6:81:22:ac:6e:41:c1:f6:85:e1:4b:0f:ec terraform plan`
- `TF_VAR_digital_ocean_token=$DIGITALOCEAN_TOKEN TF_VAR_atlas_token=$ATLAS_TOKEN TF_VAR_atlas_username=$ATLAS_USERNAME TF_VAR_ssh_fingerprint=3c:e3:4d:a6:81:22:ac:6e:41:c1:f6:85:e1:4b:0f:ec terraform destroy`

<img width="721" alt="screenshot 2015-09-17 13 40 03" src="https://cloud.githubusercontent.com/assets/2430570/9945350/a407d206-5d41-11e5-9052-27401518b1c2.png">

**Comment by phinze** [comment]
Thanks for the repro case - @bensojona. Smells like a core bug to me. Tagged and we'll take a look.

**Comment by clstokes** [comment]
_(Came across this issue while researching another DO issue...)_

As a counterexample, this DigitalOcean and Atlas Artifact configuration applies and destroys successfully with Packer v0.8.6 and Terraform v0.6.4 and v0.6.6 - https://gist.github.com/clstokes/217a177a9c6881f17cea.
