### ISSUE TITLE
API Gateway access log Log Group is left unmanaged by Terraform

### ISSUE THREAD

**Issue by wayneworkman** [hashicorp/terraform#32693]
### Expected Behavior

When an API Gateway that has access logging enabled and also has a CloudWatch Log Group specified for the access logging within the terraform, Terraform should first disable logging on the API Gateway and then briefly pause for the logging disablement to propagate through AWS. Then, delete the log group and API Gateway. This would result in NO CloudWatch Log Group being created between the log group deletion and API Gateway deletion.

### Actual Behavior

When the Log Group is deleted from API Gateway and then more requests come to the API Gateway, because logging is still enabled on the API Gateway, and because API Gateway deletions are not instant globally in AWS, API Gateway creates a new log group for the requests. Then moments later, the API Gateway deletion is propagated and completed. This results in an AWS CloudWatch Log Group being left behind, not within the Terraform state file.

### Steps to Reproduce

Build an API Gateway with access logging enabled, specify a log group also created by Terraform.

Start sending constant requests to the API gateway at a semi-high rate.

While the requests are being sent, have Terraform delete the API Gateway and log group. You will see Terraform destroys the log group, but because requests are coming still and the API gateway deletion is not fully propagated in AWS, another log group is created.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
