### ISSUE TITLE
DigitalOcean droplet renaming or dynamic naming

### ISSUE THREAD

**Issue by wyattanderson** [hashicorp/terraform#327]
I'd love for Terraform to support renaming or alteration of droplet names after actually instantiating them. Similar to the issues described in #111, I'd like to be able to name my droplets based on attributes of the droplet such as droplet ID, datacenter, etc. For example:

    # [role]-[provider]-[region]-[instanceid].domain
    web-do-nyc2-123456.domain

With DigitalOcean, the reverse DNS for a droplet depends on the droplet's name, so I have to currently  go back and not only manually rename my droplets but also reconcile the Terraform plan with the names having been computed from the application of the plan. If I don't manually reconcile my `.tf` file, Terraform will try to change the droplet name back on the next run. Also, I currently have a provisioner step that goes in to the machine and changes the hostname set at droplet creation to the new, calculated name. What I'd like to do, roughly, is this:

1. Create a DO droplet with a temporary name
1. Create a Route53 record pointing to the new droplet in the format above
1. Rename—actually, through the DO API—said droplet with the name created in the DNS record, a name that reflects properties of the actual, reified droplet

Does that make sense? Is this something that Terraform may support, or should I look to other tools?

**Comment by pearkes** [comment]
Droplets currently support renaming, so I think you're looking for something more like [self variables](https://github.com/hashicorp/terraform/pull/1033) from the sound of it, which was just merged! Let me know if that won't cover your use case.
