### ISSUE TITLE
data_retention_time_in_days as snowflake_object_parameter

### ISSUE THREAD

**Issue by vtseng-agillitics** [hashicorp/terraform#32713]
### Terraform Version

```shell
1.3.9
```

### Terraform Configuration Files

Repo:
https://github.com/AgilliticsLLC/Terraform_Bug

### Debug Output

None. Just has unexpected behavior.

### Expected Behavior

The documentation says that the data_retention_days argument is deprecated for Snowflake tables. When I use the data_retention_days argument under a table resource, Terraform tells me to use the snowflake_object_parameter resource instead. I used the snowflake_object_parameter resource, using "DATA_RETENTION_TIME_IN_DAYS" as the key. I set the value to 7. When I initially apply the table and object parameter, the data retention time for the table is correct. If I update the table on future applies, the data retention time should stay 7 days.

### Actual Behavior

When I initially apply the table and object parameter, the data retention time for the table is correct. However, if I update the table on the next apply, the table's data retention time reverts back to 1 day, the default value for Snowflake time travel.

### Steps to Reproduce

1. terraform init
2. terraform apply
3. Change the DESCRIPTION column's type to be VARCHAR(10).
4. terraform apply

**Comment by crw** [comment]
Hi @vtseng-agillitics, this looks like a question in the Snowflake provider, not in the core of Terraform itself. Please consider opening an issue on the provider's own repository, https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs. Thanks!
