### ISSUE TITLE
Invalid dev override error message is hard to understand

### ISSUE THREAD

**Issue by joneshf** [hashicorp/terraform#32716]
### Terraform Version

```shell
Terraform v1.3.6
on darwin_amd64
```

### Terraform Configuration Files

No Terraform configuration files are necessary. But a `.terraformrc` file in the home directory is necessary. The only part that's important is that the address ends with `terraform-provider-<something>`. E.g.:
```HCL
provider_installation {
  dev_overrides {
      "registry.terraform.io/joneshf/terraform-provider-foo" = ""
  }
}
```

### Debug Output

https://gist.github.com/joneshf/f8446ee061ce3572e12de28bcdddfa0c

### Expected Behavior

The error displayed should include the [original diagnostic information with the suggestion for what the address should be](https://github.com/hashicorp/terraform-registry-address/blob/a459db791fcb28a1b93d9b7e0a46b5f1db027fa9/provider.go#L277).

### Actual Behavior

The error throws away the original diagnostic information in exchange for [a terser detail](https://github.com/hashicorp/terraform/blob/b8f3f802f591e5ff0523bfb8c2e06c9e62f56bfd/internal/command/cliconfig/provider_installation.go#L249).

### Steps to Reproduce

1. `terraform plan`

### Additional Context

I'm developing my first Terraform provider. I followed [the tutorial](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework), and everything went fine. I then tried to start a new provider under my username and things have been going less than ideal. In particular, the `.terraformrc` file I included ends with `terraform-provider-<something>`. According to [a comment](https://github.com/hashicorp/terraform-registry-address/blob/a459db791fcb28a1b93d9b7e0a46b5f1db027fa9/provider.go#L250-L258), this is a mistake on my part. That's fine, I'm still learning this framework. The [useful diagnostic message it provides](https://github.com/hashicorp/terraform-registry-address/blob/a459db791fcb28a1b93d9b7e0a46b5f1db027fa9/provider.go#L277) is unfortunately discarded and instead a [cryptic diagnostic is returned instead](https://github.com/hashicorp/terraform/blob/b8f3f802f591e5ff0523bfb8c2e06c9e62f56bfd/internal/command/cliconfig/provider_installation.go#L249).

It would be great if the diagnostic that provides a solution to my error were propagated to me, instead of being lost.

My terraform version is a little out of date, but these diagnostics are on the trunk branches of the appropriate repos. So I don't think an update would fix anything.

**Comment by kmoe** [comment]
Yes, we are throwing away the fruit of the error here too early. Thanks for the well-written issue.

**Comment by joneshf** [comment]
Thanks for the quick fix!
