### ISSUE TITLE
New AWS health checks

### ISSUE THREAD

**Issue by mwielbut** [hashicorp/terraform#3273]
AWS recently announced new health checks (Calculated Health Checks, Latency Measurement Health Checks). Any plans on the roadmap to support these changes?

https://aws.amazon.com/blogs/aws/route-53-improvements-calculated-health-checks-and-latency-checks/

**Comment by ajvb** [comment]
:+1:

**Comment by stack72** [comment]
I just opened a PR for this #3741

Hopefully it will work out for you
