### ISSUE TITLE
Meta-parameter for enabling or disabling a resource

### ISSUE THREAD

**Issue by mattsafraid** [hashicorp/terraform#32736]
### Terraform Version

```shell
Terraform v1.3.9
on darwin_amd64
```

### Use Cases

The proposal here is to create a new meta-parameter that would allow to control the state of a single resource. 

This is useful for cases when a resource must be destroyed and we want to keep the code, or specially when we want to enable/disable a resource _without turning it into an array of resources_ - which means the references to the resource are kept unchanged. 

A similar behaviour can be found in other configuration languages. For example in Puppet, we can use `ensure => absent` and in Ansible we can use `state: absent`.

### Attempted Solutions

The current behaviour today can be achieved with `count` and a condition, for example: 

From https://www.hashicorp.com/blog/terraform-feature-toggles-blue-green-deployments-canary-test 
```
variable "enable_green_application" {
  default = false
  type    = bool
}

resource "aws_instance" "application_green" {
  count                  = var.enable_green_application ? 1 : 0
  instance_type          = "t2.micro"
  [...]
```

However in this case we don't have a single resource, but an array of resources. So, _any_ further reference to this object must be adapted - Although we _know_ there's only one resource because of `? 1 : 0`.
```
resource "aws_elb" "application_green" {
  count   = var.enable_green_application ? 1 : 0
  name    = "${var.prefix}-green-elb"
  [...]
  instances = aws_instance.application_green.*.id # references an array 
  [...]

resource "aws_route53_record" "application_green" {
  count   = var.enable_green_application ? 1 : 0
  [...]
  alias {
    name                   = aws_elb.application_green.0.dns_name # references first item 
    zone_id                = aws_elb.application_green.0.zone_id
    evaluate_target_health = true
  }
  [...]
```

### Proposal

With this proposal, not only the code would be cleaner because we don't need a condition block neither array references, but we know there is either zero or one resource. 

Applying the concept to the previous snippets, and assuming here a meta-parameter called `enabled` which accepts a boolean value, we'd have as follows: 

```
variable "enable_green_application" {
  default = false
  type    = bool
}

resource "aws_instance" "application_green" {
  enabled                = var.enable_green_application # new meta parameter in action 
  instance_type          = "t2.micro"
  [...]
```

```
resource "aws_elb" "application_green" {
  enabled = var.enable_green_application
  name    = "${var.prefix}-green-elb"
  [...]
  instances = aws_instance.application_green.id # no more array references
  [...]

resource "aws_route53_record" "application_green" {
  enabled = var.enable_green_application
  [...]
  alias {
    name                   = aws_elb.application_green.dns_name # no more array references
    zone_id                = aws_elb.application_green.zone_id
    evaluate_target_health = true
  }
  [...]
```

**Comment by apparentlymart** [comment]
Indeed thanks for sharing this proposal, @mattsafraid!

I think this proposal is essentially the same as https://github.com/hashicorp/terraform/issues/21953. Would you agree? If so, I'd like to close this just to consolidate the discussion in one place.

**Comment by mattsafraid** [comment]
Hi @apparentlymart, thanks for looking into it! 

The proposal is indeed similar to #21953. However as I see one detail is different: On 21953 the `enabled` keyword still creates an array, as noted by the line 
```
network_acl_id = aws_network_acl.public[0].id
```
The main point of my proposal is to have a single resource instead of an array of resources. 

Do you think both concepts could be combined?

**Comment by mattsafraid** [comment]
Hi @apparentlymart, thanks for looking into it! 

The proposal is indeed similar to #21953, however the proposal still references an array as in 
```
network_acl_id = aws_network_acl.public[0].id
```
But from the comments I see that the discussion has advanced to the same idea. This issue can be closed. Thanks!

**Comment by mattsafraid** [comment]
Hi @apparentlymart, thanks for looking into it! 

The proposal is indeed similar to #21953, however the proposal still references an array as in 
```
network_acl_id = aws_network_acl.public[0].id
```
But from the comments I see that the discussion has advanced to the same idea. This issue can be closed. Thanks!
