### ISSUE TITLE
Terraform unable to read tfstate file for specific resource "azurerm_app_service_public_certificate" and inconsistent in reading it

### ISSUE THREAD

**Issue by rajesh-shanmugasundaram8** [hashicorp/terraform#32739]
### Terraform Version

```shell
Terraform version - 1.3.4
```

### Terraform Configuration Files

resource "azurerm_app_service_public_certificate" "example" {
  resource_group_name  = azurerm_resource_group.example.name
  app_service_name     = azurerm_app_service.example.name
  certificate_name     = "example-public-certificate"
  certificate_location = "Unknown"
  blob                 = filebase64("${var.linux_web_app.cert_path}/${"example-public-certificate"}")
}

### Debug Output

╷
│ Error: waiting for creation of Public Certificate: (Name "xxxx.cer" / Site Name "app-xxxx" / Resource Group "rg-xxxx"): couldn't find resource (11 retries)
│ 
│   with module.linux_appservices["frontend001"].azurerm_app_service_public_certificate.public_cert["xxxx.cer"],
│   on ../../shared_modules/linux_web_app/main.tf line 290, in resource "azurerm_app_service_public_certificate" "public_cert":
│  290: resource "azurerm_app_service_public_certificate" "public_cert" {
│ 
╵

### Expected Behavior

It should read the tfstate and show no changes in terraform plan / terraform apply

### Actual Behavior

While running terraform plan from azure pipeline, Initially terraform plan and terraform apply works fine and sync / update tfstate with all details

Again if we run terraform plan , it should new resource to add which is already exists in terraform tfstate file.
When we apply terraform apply, it through an error stating already resource exists in portal and request to import in tfstate.

### Steps to Reproduce

Starting: Terraform Init
==============================================================================
Task         : Terraform CLI
Description  : Execute terraform cli commands
Version      : 1.0.37
Author       : Charles Zipp
Help         : 
==============================================================================
/opt/hostedtoolcache/terraform/1.3.4/x64/terraform version
Terraform v1.3.4
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html
/usr/bin/az login --service-principal -t 9652d7c2-1ccf-4940-8151-4a92bd474ed0 -u *** -p ***

**Comment by kmoe** [comment]
This looks like an issue best suited to the AzureRM provider, since this behaviour is not controlled by Terraform Core. Please open an issue at https://github.com/hashicorp/terraform-provider-azurerm/issues.
