### ISSUE TITLE
Feat: Allow for the creation of multiple Terraform work-spaces with names separated by a list flag, a comma, or a space.

### ISSUE THREAD

**Issue by ChauhanKrunal** [hashicorp/terraform#32745]
### Terraform Version

```shell
Terraform v1.3.7
on linux_amd64
```

### Use Cases

Problem Statement: Terraform has a feature that allows you to create workspaces that are completely functional. If I need to create four, five, or n workspaces, I must do so with the CLI using this command. `terraform workspace new workspace-1, terraform workspace new workspace-2, terraform workspace new workspace-n` is a time-consuming and tedious task.

### Attempted Solutions

I attempted to create multiple Terraform workspaces using the terraform cli and the commands listed below.

`terraform new workspace-1`  However, if I need to create multiple terraform workspaces, I must retype this mentioned command for each new workspace, which isn't a very clean way. I also looked into the man pages of terraform cli workspace but there are no such flags for creating multiple workspaces using only a single command.

```
terraform workspace --help
Usage: terraform [global options] workspace

  new, list, show, select and delete Terraform workspaces.

Subcommands:
    delete    Delete a workspace
    list      List Workspaces
    new       Create a new workspace
    select    Select a workspace
    show      Show the name of the current workspace

```

### Proposal

Suggested Solution: In the existing terraform workspace feature, if we could just add a list flag for creating multiple terraform workspaces within a single command, such as `terraform workspace new -l workspace-1 workspace-2,workspace-n`, or we can add comma or separated values without using the list -l flag, that would be very useful. `terraform workspace new workspace-1,workspace-2,workspace-n or terraform workspace new workspace-1 workspace-2 workspace-n`, for example.

**Comment by crw** [comment]
Thanks for this feature request! Can you say more about your use case? This seems like a problem solved by unix tool composition, for example:

`
 % xargs -n 1 terraform workspace new <<< "ws1 ws2"     
Created and switched to workspace "ws1"!

You're now on a new, empty workspace. Workspaces isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.
Created and switched to workspace "ws2"!

You're now on a new, empty workspace. Workspaces isolate their state,
so if you run "terraform plan" Terraform will not see any existing state
for this configuration.
`

Can you say more about your environment where such composition to achieve the desired effect is not possible? Thanks!

**Comment by ChauhanKrunal** [comment]
> 



> Thanks for this feature request! Can you say more about your use case? This seems like a problem solved by unix tool composition, for example:
> 
> ```
>  % xargs -n 1 terraform workspace new <<< "ws1 ws2"     
> Created and switched to workspace "ws1"!
> 
> You're now on a new, empty workspace. Workspaces isolate their state,
> so if you run "terraform plan" Terraform will not see any existing state
> for this configuration.
> Created and switched to workspace "ws2"!
> 
> You're now on a new, empty workspace. Workspaces isolate their state,
> so if you run "terraform plan" Terraform will not see any existing state
> for this configuration.
> ```
> 
> Can you say more about your environment where such composition to achieve the desired effect is not possible? Thanks!

@crw We can achieve this using UNIX composition, but I was hoping that if we could embed this feature in the terraform CLI itself, it would be easier for newcomers to adapt the terraform and they wouldn't have to dive into the UNIX commands. And, as of now, I am not aware of any environment in which this type of composition is not possible because it is a UNIX or UNIX-like os command. 

What are your thoughts on implementing this feature via flags or comma-separated values in the CLI itself?

**Comment by crw** [comment]
@ChauhanKrunal Thanks for the clarification! I do not have an opinion, my main goal is to help triage and categorize the issues that are filed rather than make any specific recommendations to the core maintainer team.

I can tell you that generally there is a reluctance on the part of the core maintainers to make these types of changes to command-line arguments that can be solved by outside automation. Additionally, generally speaking the target audience of open source Terraform is expected to be somewhat literate with scripting automation and command-line affordances on their automation platforms of choice. For reference see this comment: https://github.com/hashicorp/terraform/issues/32740#issuecomment-1446850118:

> Terraform is designed to be integrated with other software, so running it in a minimal environment with no other software installed is not one of our design goals.

On the plus side, the `workspace` command is specifically *not* covered by the [Terraform 1.x Compatibility Promise](https://developer.hashicorp.com/terraform/language/v1-compatibility-promises#commands-that-might-change), so it could be changed if it needed to. :)

**Comment by ChauhanKrunal** [comment]
> @ChauhanKrunal Thanks for the clarification! I do not have an opinion, my main goal is to help triage and categorize the issues that are filed rather than make any specific recommendations to the core maintainer team.
> 
> I can tell you that generally there is a reluctance on the part of the core maintainers to make these types of changes to command-line arguments that can be solved by outside automation. Additionally, generally speaking the target audience of open source Terraform is expected to be somewhat literate with scripting automation and command-line affordances on their automation platforms of choice. For reference see [#32740 (comment)](https://github.com/hashicorp/terraform/issues/32740#issuecomment-1446850118):
> 
> > Terraform is designed to be integrated with other software, so running it in a minimal environment with no other software installed is not one of our design goals.
> 
> On the plus side, the `workspace` command is specifically _not_ covered by the [Terraform 1.x Compatibility Promise](https://developer.hashicorp.com/terraform/language/v1-compatibility-promises#commands-that-might-change), so it could be changed if it needed to be. :)
 
@crw Thank you for your brief explanation; I understand your point, and thus I am closing this issue.
