### ISSUE TITLE
Terraform Plan - strconv.ParseInt: parsing "53687091200": value out of range

### ISSUE THREAD

**Issue by timothyl1985** [hashicorp/terraform#32746]
### Terraform Version

```shell
Terraform v1.3.8
on windows_386
+ provider registry.terraform.io/databricks/databricks v1.9.2
+ provider registry.terraform.io/hashicorp/azuread v2.33.0
+ provider registry.terraform.io/hashicorp/azurerm v3.45.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

Your version of Terraform is out of date! The latest version
is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

https://gist.github.com/timothyl1985/b6ae9a084ed8fa5d6e8d4af1ed3024fe

### Expected Behavior

Terraform Plan should have generated a plan to deploy my Azure resources

### Actual Behavior

The Terraform AzureRm provider produced following error,

Stack trace from the terraform-provider-azurerm_v3.45.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "53687091200": value out of range

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

This appears to be an error someone else faced on an older Terraform version back in 2020 but it did not have a resolution either.

### References

https://github.com/hashicorp/terraform-plugin-sdk/issues/469

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
