### ISSUE TITLE
no expansion has been registered for module

### ISSUE THREAD

**Issue by xujun6936** [hashicorp/terraform#32743]
### Terraform Version

```shell
"version": 4,
  "terraform_version": "1.1.0",
  "serial": 94,
  "lineage": "7829d9f4-9535-0a0d-49a7-767aa9de92cf",
```

### Terraform Configuration Files

```terraform
...terraform config...
https://gitlab.com/gitlab-org/professional-services-automation/tools/implementation/get-deployment-workshop/-/issues/518
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

no expansion has been registered for module.gitlab_ref_arch_aws
Destroy complete! Resources: 0 destroyed.

### Expected Behavior

 all of Resources:should destroyed.

### Actual Behavior

Destroy complete! Resources: 0 destroyed.

### Steps to Reproduce

Run cd /gitlab-environment-toolkit/terraform/environments/3k
  Task actions 

 Run terraform init
  Task actions 

 Run terraform plan -out 3k.aws_ec2.tfplan
  Task actions 

 Run terraform apply 3k.aws_ec2.tfplan

**Comment by MaxHerrmannSVA** [comment]
Greetings,

I've got the same error today.
I tried to upgrade Terrafrom to Version 1.3.9 and the AWS Provider from 4.55.0 to 4.56.0 but still run into the same error.

root@084f60f45344:/gitlab-environment-toolkit/terraform/environments/3k# /usr/bin/terraform -v
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.56.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
root@084f60f45344:/gitlab-environment-toolkit/terraform/environments/3k#

You can see my config also [here](https://gitlab.com/gitlab-org/professional-services-automation/tools/implementation/get-deployment-workshop/-/issues/530) at the Gitlab GET Deployment Workshop as an Issue

The Container we are using is this one: https://gitlab.com/gitlab-org/gitlab-environment-toolkit
There Terraform gets installed with asdf.

I hope this helps :)

**Comment by jbardin** [comment]
Hi @MaxHerrmannSVA,

If you can reproduce the error please file a new issue with all the requested information. The issue here is not likely to be related, and is using an unpatched version of Terraform with known issues, most likely #30196.

**Comment by xujun6936** [comment]
> 

thank you !
