### ISSUE TITLE
azurerm_windows_web_app.app_service missing remote_debugging_version VS2022

### ISSUE THREAD

**Issue by sven5** [hashicorp/terraform#32764]
Sorry, perhaps this is rather a feature than a bug.

### Terraform Version

```shell
Terraform v1.3.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.45.0
```

### Terraform Configuration Files

```terraform
resource "azurerm_windows_web_app" "app_service" {
  name                         = "app-${var.project}-${var.environment}-001"
  resource_group_name          = azurerm_resource_group.rg_app.name
  location                     = var.location
  tags                         = local.tags
  service_plan_id              = azurerm_service_plan.app_service_plan.id
  app_settings                 = local.app_env_variables
  client_affinity_enabled      = false
  virtual_network_subnet_id    = azurerm_subnet.app_service_subnet.id
  https_only                   = true
  
  site_config {
    scm_type           = null
    
    always_on          = true
    ftps_state         = "FtpsOnly"
    websockets_enabled = true
    health_check_path  = "/api/HealthCheck" # health check required in order that internal app service plan loadbalancer do not loadbalance on instance down
    use_32_bit_worker  = false
    remote_debugging_enabled = true
    remote_debugging_version = "VS2022"
    
    application_stack {
      current_stack = "dotnet"
      dotnet_version = "v6.0"
    }
  }
```

### Debug Output

╷
│ Error: expected site_config.0.remote_debugging_version to be one of [VS2017 VS2019], got VS2022
│
│   with azurerm_windows_web_app.app_service,
│   on main.tf line 103, in resource "azurerm_windows_web_app" "app_service":
│  103:     remote_debugging_version = "VS2022"
│

### Expected Behavior

terraform should accept  VS2022  as valid value

### Actual Behavior

Getting error message above

### Steps to Reproduce

just use `terraform plan`

### Additional Context

In Azure Portal the Value of VS2022 is valid

![image](https://user-images.githubusercontent.com/8734624/222188731-8fd98a2c-7fa9-4beb-8355-9ca91218b8ac.png)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by sven5** [comment]
@jbardin Ok, I'll post my issue there. This seems to be a missing feature rather than a wrong usage.
