### ISSUE TITLE
Terraform crashed when running terraform show with a plan file.

### ISSUE THREAD

**Issue by billcchung** [hashicorp/terraform#32773]
### Terraform Version

```shell
Terraform v1.3.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.56.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/vancluever/acme v2.13.1
```

### Terraform Configuration Files

Company internal config, prefer not to expose.

### Debug Output

```!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

failed to decode plan for module.workspace_sns.aws_sns_topic.workspace while rendering diff: error decoding 'after' value: an object with 30 attributes is required (28 given)
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/distiller/project/project/internal/logging/panic.go:55 +0x153
panic({0x2d4d0e0, 0xc002734640})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/hashicorp/terraform/internal/command/views.decodeChange(0xc00069b6c0, 0xc003b9acf0?)
	/Users/distiller/project/project/internal/command/views/plan.go:547 +0x1cb
github.com/hashicorp/terraform/internal/command/views.renderPlan(0xc00014be10, 0xc0012938d0, 0xc000390620)
	/Users/distiller/project/project/internal/command/views/plan.go:282 +0x16be
github.com/hashicorp/terraform/internal/command/views.(*ShowHuman).Display(0x0?, 0x0?, 0x0?, 0xc0022fda38?, 0x1?)
	/Users/distiller/project/project/internal/command/views/show.go:44 +0x11c
github.com/hashicorp/terraform/internal/command.(*ShowCommand).Run(0xc000682d00, {0xc0000521d0?, 0x1?, 0x1?})
	/Users/distiller/project/project/internal/command/show.go:59 +0x2f3
github.com/mitchellh/cli.(*CLI).Run(0xc000126280)
	/Users/distiller/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
main.realMain()
	/Users/distiller/project/project/main.go:315 +0x15d4
main.main()
	/Users/distiller/project/project/main.go:58 +0x19
```

### Expected Behavior

should show the plan outputs and not have crashed

### Actual Behavior

terraform crashed

### Steps to Reproduce

terraform show <plan file>

### Additional Context

Although it's reproduced with `terraform show`, however we believe it also crashed when running `terraform apply`, and caused a partial apply result, we're seeing some extra diff when doing terraform plan&apply with same configs again.

**Comment by jbardin** [comment]
Hi @billcchung,

Thanks for filing the issue. Can you verify that you are creating the plan with the exact same version of the provider with which you are applying that plan? The AWS provider CHANGELOG show two attributes were added to the `aws_sns_topic` resource in the last release, but it sounds like the plan was created with an earlier version of the provider.

Thanks!

**Comment by billcchung** [comment]
Thanks @jbardin , I believe it's same provider version, the plan file is from a terraform run within a container, and after it initialized we immediately do plan & apply, but we dont have the full logs for it (probably due to it crashed).

**Comment by jbardin** [comment]
If the provider versions were the same, I'm not sure how we got state encoded with a different schema. Were you creating the plan using `-target`?

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
