### ISSUE TITLE
Terraform escape quotes in the string don't work for Datadog Log based monitor query.

### ISSUE THREAD

**Issue by Sravanthicilivaru** [hashicorp/terraform#32774]
### Terraform Version

```shell
Required Terraform Version 0.12.31
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

{"message":"There is error in the log.","name":"error log","options":{"include_tags":true,"new_host_delay":300,"no_data_timeframe":10,"notify_no_data":false,"require_full_window":true,"thresholds":{}},"priority":0,"query":"logs(\\\"Error\\\").index(\\\"*\\\").rollup(\\\"count\\\").last(\\\"5m\\\")\u003e0","tags":[],"type":"metric alert"}:

### Expected Behavior

Tried to use single slash, it failed the same thing. What I expect is running "terraform apply", there is no error, monitor can be created.

### Actual Behavior

It passed when running "terraform validate". But it failed when running "terraform apply" with the following errors.

│ Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/validate: 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid"]}
│
│   with datadog_monitor.monitor_error,
│   on main.tf line 6, in resource "datadog_monitor" "monitor_error":
│    6: resource "datadog_monitor" "monitor_error" {
│

### Steps to Reproduce

This is a simplified Terraform code as below:

resource "datadog_monitor" "monitor_error" {
  name               = "error log"
  type               = "metric alert"
  message            = "There is error in the log."

  query = "logs(\\\"Error\\\").index(\\\"*\\\").rollup(\\\"count\\\").last(\\\"5m\\\")>0"
}

It passed when running "terraform validate". But it failed when running "terraform apply" with the following errors

│ Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/validate: 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid"]}
│
│   with datadog_monitor.monitor_error,
│   on main.tf line 6, in resource "datadog_monitor" "monitor_error":
│    6: resource "datadog_monitor" "monitor_error" {
│
╵

**Comment by jbardin** [comment]
Hi @Sravanthicilivaru,

The output shows that the query string was escaped correctly, and evaluated as `logs("Error").index("*").rollup("count").last("5m")>0` and sent to the provider.  Since this doesn't appear to be a bug in Terraform, I would open an issue with the DataDog provider.

Thanks!
