### ISSUE TITLE
InternalServerError while creating Azure flow logs for NSG

### ISSUE THREAD

**Issue by harsha1163** [hashicorp/terraform#32804]
### Terraform Version

```shell
1.0.1 <2.0
```

### Terraform Configuration Files

resource "azurerm_network_watcher_flow_log" "private" {
  depends_on                = [azurerm_storage_account.this]
  network_watcher_name      = vaau45-private-log
  resource_group_name       = data.azurerm_resource_group.azurerm_network_watcher_rg.name
  network_security_group_id = azurerm_network_security_group.private.id
  storage_account_id        = azurerm_storage_account.this.id
  enabled                   = true
  name                      = "test-flowlog-private"

  retention_policy {
    enabled = "true"
    days    = 10
  }

  traffic_analytics {
    enabled               = true
    workspace_id          = azurerm_log_analytics_workspace.this.workspace_id
    workspace_region      = azurerm_log_analytics_workspace.this.location
    workspace_resource_id = azurerm_log_analytics_workspace.this.id
    interval_in_minutes   = 10
  }
}

### Debug Output

Error: waiting for completion of creating "Flow Log: (Name \"vaau45-private-log\" / Network Watcher Name \"NetworkWatcher_eastus\" / Resource Group \"NetworkWatcherRG\")": Code="InternalServerError" Message="An error occurred."

The above error is frequently occurring now a days when trying to create flow logs.

### Expected Behavior

Flow log should create without error

### Actual Behavior

Error: waiting for completion of creating "Flow Log: (Name \"vaau45-private-log\" / Network Watcher Name \"NetworkWatcher_eastus\" / Resource Group \"NetworkWatcherRG\")": Code="InternalServerError" Message="An error occurred."

The above error is frequently occurring now a days when trying to create flow logs.

### Steps to Reproduce

Apply the above terraform resource.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
