### ISSUE TITLE
provider/openstack: Remove Permissive Security Group Rules

### ISSUE THREAD

**Issue by framctr** [hashicorp/terraform#32829]
### Terraform Version

```shell
Terraform v1.4.0
on linux_amd64
```

### Terraform Configuration Files

none

### Debug Output

none

### Expected Behavior

When creating a security group, by default terraform adds also 2 very permissive egress rules to any protocol, IP and port range.

### Actual Behavior

Do not create egress rules when creating a secgroup with stricter rules.

### Steps to Reproduce

1. create a secgroup and secgroup_rules
2. `terraform apply`
3. egress rules are created

### Additional Context

Openstack Wallaby

### References

- #11466
- #9799

**Comment by kmoe** [comment]
The Openstack provider now has its own repo: please open this issue there. https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues
