### ISSUE TITLE
databricks metastore assignment unity catalog failure

### ISSUE THREAD

**Issue by saiprasadcrown** [hashicorp/terraform#32848]
### Terraform Version

```shell
Terraform v1.3.9
on windows_amd64
+ provider registry.terraform.io/databricks/databricks v1.0.0
+ provider registry.terraform.io/hashicorp/aws v4.58.0       
+ provider registry.terraform.io/hashicorp/random v3.4.3     
+ provider registry.terraform.io/hashicorp/time v0.9.1

Your version of Terraform is out of date! The latest version
is 1.4.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```resource "aws_s3_bucket" "metastore" {
  bucket        = "${local.prefix}-metastore"
  force_destroy = true
  tags = merge(var.tags, {
    Name = "${local.prefix}-metastore"
  })
}

resource "aws_s3_bucket_acl" "metastore_private_acl" {
  bucket = aws_s3_bucket.metastore.id
  acl    = "private"
}

resource "aws_s3_bucket_versioning" "metastore_disable_versioning" {
  bucket = aws_s3_bucket.metastore.id
  versioning_configuration {
    status = "Disabled"
  }
}

resource "aws_s3_bucket_public_access_block" "metastore" {
  bucket                  = aws_s3_bucket.metastore.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
  depends_on              = [aws_s3_bucket.metastore]
}



# Create users and groups


# Create a Unity Catalog metastore and link it to workspaces
resource "databricks_metastore" "this" {
  provider     = databricks.created_workspace
  name         = "primary"
  storage_root = "s3://${aws_s3_bucket.metastore.id}/metastore"
  force_destroy = true
}



resource "databricks_metastore_assignment" "default_metastore" {
  provider             = databricks.created_workspace
  workspace_id         = databricks_mws_workspaces.this.workspace_id
  metastore_id         = databricks_metastore.this.id
#   default_catalog_name = "hive_metastore"
}
```

### Debug Output

NA

### Expected Behavior

metastore assigned to the databricks workspace

### Actual Behavior

Error: cannot create metastore assignment: Workspace is not in the same region as metastore. Workspace region: Unknown, Metastore region: eastus2
│
│   with databricks_metastore_assignment.default_metastore,
│   on unity_catalog.tf line 47, in resource "databricks_metastore_assignment" "default_metastore":
│   47: resource "databricks_metastore_assignment" "default_metastore" {

This error is similar to https://community.databricks.com/s/question/0D58Y00009jctg8SAA/having-an-issue-assigning-databricksmetastore-with-terraform-provider

### Steps to Reproduce

terraform init
terraform apply

**Comment by crw** [comment]
Hello,

This appears to be an issue or question with the Databricks provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/databricks/terraform-provider-databricks/issues. You can find more information on the Databricks provider on its registry page: https://registry.terraform.io/providers/databricks/databricks/latest/docs

Thanks!
