### ISSUE TITLE
fields[] in schema would cause the table to be re-created even without any change

### ISSUE THREAD

**Issue by kickingfish** [hashicorp/terraform#32841]
### Terraform Version

```shell
terraform version 1.0.5
```

### Terraform Configuration Files

terraform-files.zip attached
The code with the schema can be tested.

### Debug Output

not applicable

### Expected Behavior

Terraform should not re-create the table when there is no change on the schema

### Actual Behavior

The terraform will destroy the table and re-create it even there's no changes on the schema.  This should not be done because data will be lost.

This is the Plan.
Terraform will perform the following actions:
  # module.create_table.google_bigquery_table.bq_table["table_gulpreet"] must be replaced
-/+ resource "google_bigquery_table" "bq_table" {
      ~ creation_time       = 1678802441265 -> (known after apply)
      ~ etag                = "WkQG+LstuAC7Y9Ds6eSKhg==" -> (known after apply)
      ~ expiration_time     = 0 -> (known after apply)
      ~ id                  = "projects/ford-d33197dfbf0f1d2df0bc98f6/datasets/tfm_dataset_tbl/tables/table_gulpreet" -> (known after apply)       
      - labels              = {} -> null
      ~ last_modified_time  = 1678802441428 -> (known after apply)
      ~ location            = "US" -> (known after apply)
      ~ num_bytes           = 0 -> (known after apply)
      ~ num_long_term_bytes = 0 -> (known after apply)
      ~ num_rows            = 0 -> (known after apply)
      ~ schema              = jsonencode(
          ~ [ # forces replacement
              ~ {
                  + description = null
                  + fields      = []
                    name        = "col1"
                    # (2 unchanged elements hidden)
                } # forces replacement,
              ~ {
                  + description = null
                  + fields      = []
                    name        = "col2"
                    # (2 unchanged elements hidden)
                } # forces replacement,
            ]
        )
      ~ self_link           = "https://bigquery.googleapis.com/bigquery/v2/projects/ford-d33197dfbf0f1d2df0bc98f6/datasets/tfm_dataset_tbl/tables/table_gulpreet" -> (known after apply)
      ~ type                = "TABLE" -> (known after apply)
        # (5 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy. 

### Steps to Reproduce

[terraform-files.zip](https://github.com/hashicorp/terraform/files/10969673/terraform-files.zip)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
