### ISSUE TITLE
DocumentDB aws_lambda_event_source_mapping

### ISSUE THREAD

**Issue by bneigher** [hashicorp/terraform#32858]
### Terraform Version

```shell
1.4.0
```

### Use Cases

Triggering Lambda from DocumentDB CDC stream

### Attempted Solutions

Alternative architectures... polling from lambda, or AWS DMS

### Proposal

Now that [DocumentDB is supported as a Lambda Trigger](https://aws.amazon.com/about-aws/whats-new/2023/02/aws-lambda-amazon-documentdb-change-streams-event-source/) was hoping that terraform's [lambda_event_source_mapping](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping) could be extended to support this new source?  Eager to clean up some unnecessary components now that this is supported.

### References

https://github.com/serverless/serverless/issues/11820

Additional Resource references:
https://docs.aws.amazon.com/lambda/latest/dg/with-documentdb.html#docdb-prereqs
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-documentdb.html

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by bneigher** [comment]
oh - good to know. thanks
