### ISSUE TITLE
Terraform 1.4.1 breaks older code in local

### ISSUE THREAD

**Issue by arnaudfroidmont** [hashicorp/terraform#32859]
### Terraform Version

```shell
terrform v1.4.1

- Finding oracle/oci versions matching "4.90.0"...
- Installing hashicorp/local v2.4.0...
- Installed hashicorp/local v2.4.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
- Installing oracle/oci v4.90.0...
- Installed oracle/oci v4.90.0 (signed by a HashiCorp partner, key ID ^[[0m^[[1m1533A49284137CEB^[[0m^[[0m)
- Installing hashicorp/null v3.2.1...
- Installed hashicorp/null v3.2.1 (signed by HashiCorp)
- Installing hashicorp/random v3.4.3...
- Installed hashicorp/random v3.4.3 (signed by HashiCorp)
```

### Terraform Configuration Files

We have not pinpointed the part of the code that was breaking, it seems like it is due to local files. 

### Debug Output

│ Error: Provider produced invalid plan
│
│ Provider "[registry.terraform.io/hashicorp/local](https://urldefense.com/v3/__http://registry.terraform.io/hashicorp/local__;!!ACWV5N9M2RV99hQ!KkvQSNXlSJWZ_qhiz85rNC8TacgEfpEFDxN7-7byFo5QpeS7wpvtVykC1as0BHdNqPRIgdTKdVqOnfcW6pck8_cY9tby9rc6$)" planned an invalid value
│ for local_file.hosts.content: planned value cty.UnknownVal(cty.String) does
│ not match config value cty.UnknownVal(cty.String).RefineNotNull().
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Expected Behavior

Plan should go ahead without error

### Actual Behavior

│ Error: Provider produced invalid plan
│
│ Provider "[registry.terraform.io/hashicorp/local](https://urldefense.com/v3/__http://registry.terraform.io/hashicorp/local__;!!ACWV5N9M2RV99hQ!KkvQSNXlSJWZ_qhiz85rNC8TacgEfpEFDxN7-7byFo5QpeS7wpvtVykC1as0BHdNqPRIgdTKdVqOnfcW6pck8_cY9tby9rc6$)" planned an invalid value
│ for local_file.hosts.content: planned value cty.UnknownVal(cty.String) does
│ not match config value cty.UnknownVal(cty.String).RefineNotNull().
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

When replacing the terraform with v1.3.9, it works fine.

**Comment by joliver** [comment]
Came here to post the same issue. We are running v1.4.0 linux-amd64.

**Comment by samsonong** [comment]
Facing the same issue in my pipelines too - no recent pipeline codechange
