### ISSUE TITLE
Fix conflicting information on sensitive outputs

### ISSUE THREAD

**Issue by chloecollins** [hashicorp/terraform#32861]
### Terraform Version

```shell
N/A
```

### Affected Pages

"Command: output" CLI reference

- https://developer.hashicorp.com/terraform/cli/commands/output

"Output Data from Terraform" tutorial
- https://developer.hashicorp.com/terraform/tutorials/configuration-language/outputs

### What is the docs issue?

In the CLI reference page, it is stated that outputs with the sensitive attribute will be redacted when specified by name, with the following example:
```
$ terraform output password
password = <sensitive>
```
However, the tutorial states that Terraform will not redact the value when you specify the output by name, as in:
```
$ terraform output db_password
"notasecurepassword"
```
This contradictory information may confuse readers.

### Proposal

Update the linked CLI reference documentation to reflect expected behaviour

**Comment by kmoe** [comment]
Thanks for this. Yes, the contradictory information is pretty confusing. Running `terraform output` (no positional param) will print all the outputs, with the sensitive one redacted. Running `terraform output password` will print the value of the output, not redacted. This is the intended behaviour, so the CLI docs are wrong. Docs team will fix, thanks.

**Comment by ajoyacharyya** [comment]
Is this issue related to the bug https://github.com/hashicorp/terraform/issues/33055
