### ISSUE TITLE
Support for securestring in azurerm_api_connection

### ISSUE THREAD

**Issue by macingo-technologies** [hashicorp/terraform#32874]
### Terraform Version

```shell
3.1.7
```

### Use Cases

I just need to create an API connection to send emails via logic app.

### Attempted Solutions

Here the code I am using:

```
data "azurerm_managed_api" "smtp_westeu" {
  name     = "smtp"
  location = azurerm_resource_group.rg_imports.location
}

resource "azurerm_api_connection" "noreply_email_api" {
  name                = "${var.env_prefix}-sendemail-con-westeu"
  resource_group_name = azurerm_resource_group.rg_imports.name
  managed_api_id      = data.azurerm_managed_api.smtp_westeu.id 
  display_name        = "NoReply"
  parameter_values = {
    serverAddress: "...",
    userName: "...",
    port: 587,
    enableSSL: true,
    password: "..." <--- That is ignored
  }
  tags = {
    Source = "${var.iac}"
  }
  lifecycle {
    # NOTE: since the connectionString is a secure value it's not returned from the API
    ignore_changes = [ parameter_values ]
  }
}
```

The API connection is correclty created but with password value empty:

![image](https://user-images.githubusercontent.com/80706757/225855097-f08c2bde-4071-425c-9eb0-7e643a7ae62c.png)

### Proposal

Add support for securestring please.

What I read [here](https://learn.microsoft.com/en-us/connectors/smtpconnector/#default), password is a securestring. 

I confirm that, even though I create the api connection by portal azure, the password is not visible in the template of the api connection:

![image](https://user-images.githubusercontent.com/80706757/225856006-7632db39-59c6-4df2-9d75-816a32cd961c.png)

Both I create the API connection via portal or via terraform, the outcome template is the same, but the difference is in the password value that is not valorized by terraform.

Thank you

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
