### ISSUE TITLE
Update "assume_role" to be block instead of argument

### ISSUE THREAD

**Issue by MrGarrett45** [hashicorp/terraform#32873]
### Terraform Version

```shell
1.3.9
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/settings/backends/s3

https://github.com/hashicorp/terraform/blob/main/website/docs/language/settings/backends/s3.mdx

### What is the docs issue?

![image](https://user-images.githubusercontent.com/14838216/225811121-43e7a147-1811-4bc6-ae4b-c2c3a7157132.png)

This section has assume_role as an argument instead of a block which leads to the below error when running "terraform apply":
'An argument named "assume_role" is not expected here. Did you mean to define a block of type "assume_role"?'

### Proposal

Remove the equals sign

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
