### ISSUE TITLE
About GCS Lifecycle Rules: Adding Unexpected Conditions

### ISSUE THREAD

**Issue by heiyohei** [hashicorp/terraform#32885]
### Terraform Version

```shell
1.37
```

### Terraform Configuration Files

# Maximum number of versions per object 
lifecycle_rule {
     action { 
     type = var.gcs_param_con.type
     }
     condition {
       num_newer_versions = each.value.num_newer_versions
       with_state         = var.gcs_param_con.with_state_ver
     }
} 
# Non-Current Version Expiration Date   
lifecycle_rule { 
    action {
       type = var.gcs_param_con.type
     }
     condition { 
      days_since_noncurrent_time = each.value.days_since_noncurrent_time
     }
   }
 # Current Version Expiration Date 
   lifecycle_rule {
     action {
       type = var.gcs_param_con.type
     } 
    condition { 
      age         = each.value.age
     }
   } 

### Debug Output

none

### Expected Behavior

none

### Actual Behavior

The condition "after 0 days since the object was created" is set in the object's conditions, even though it is not specified. Please advise how to delete this condition.

### Steps to Reproduce

none

### Additional Context

none

### References

none

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
