### ISSUE TITLE
provider/aws: Add support for Elasticache Read Replica

### ISSUE THREAD

**Issue by sukritpol** [hashicorp/terraform#3289]
i want to use elasticache  read replica but bot support 
how can i user this resource

**Comment by radeksimko** [comment]
See https://github.com/hashicorp/terraform/pull/2945

**Comment by sukritpol** [comment]
thank radeksimko  
I mean not found official terraform 
I must add code form link and compile  it work

**Comment by stack72** [comment]
Closing this as a duplicate of #4361

I am going to track the progress on this in that ticket going forward.
