### ISSUE TITLE
Syntax highlighting for inline strings (esp EOT)

### ISSUE THREAD

**Issue by fardarter** [hashicorp/terraform#32904]
### Terraform Version

```shell
any
```

### Use Cases

Syntax highlighting for inlines string.

### Attempted Solutions

I've searched for something like it.

### Proposal

 ```
locals { 
web_prep        = <<-EOT
Set-ExecutionPolicy Bypass -Scope Process -Force;
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;

iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
choco config set --name cacheLocation --value "$HOME\chocolatey\cache"
choco feature enable -n allowGlobalConfirmation
choco install git.install -y
choco install vscode -y
}
```

Introduce a syntax highlight for an inline file, perhaps in this example with an `# Syntax: ps1` line at the top of the file? Not committed to any implementation.

```
locals { 
web_prep        = <<-EOT
# Syntax: ps1
Set-ExecutionPolicy Bypass -Scope Process -Force;
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;

iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
choco config set --name cacheLocation --value "$HOME\chocolatey\cache"
choco feature enable -n allowGlobalConfirmation
choco install git.install -y
choco install vscode -y
}
```

**Comment by jbardin** [comment]
Hi @fardarter,

Thanks for filing the issue. Terraform is not involved with the presentation of configuration in any way, so there's highlighting it could do. This sounds like a feature request for your editor of choice, possibly with the help of the [Terraform Language Server](https://github.com/hashicorp/terraform-ls). 

Thanks
