### ISSUE TITLE
plugin_cache_may_break_dependency_lock_file using a docker container to manage dependencies rather than a lock file

### ISSUE THREAD

**Issue by pguinard-public-com** [hashicorp/terraform#32906]
### Terraform Version

```shell
Terraform v1.4.2 (1.4.0 is also effected with the changes to the provider cache)
```

### Use Cases

We currently use the local filesystem mirror as a provider for all packages so that they're included from local caches only and rely on our terraform image to provide dependencies for the following ensuring upgrades by dependabot can be efficiently managed:

* terraform
* terraform providers (to not hit the provider mirrors as heavily when they can be cached locally and for speed)
* tflint
* terraform providers
* security scanning in line

In order to upgrade versions of the above packages we'd like to just bump the container image and nothing else in terms of resources.

```
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"

provider_installation {
  filesystem_mirror {
    path    = "/root/.terraform.d/providers-cache" # Must be an absolute path, not a relative path such as $HOME/.terraform.d/providers-cache
    include = ["registry.terraform.io/*/*"]
  }
  # With direct enabled, fallback to non cached providers happens always. This allows calls to third party providers to fail
  # direct {}
}
```

Current system running terraform init on an empty state with no providers:

```
Terraform has been successfully initialized!

real	0m1.234s
user	0m1.176s
sys	0m0.108s
```
Second init
```
Terraform has been successfully initialized!

real    0m2.409s
user    0m2.318s
sys     0m0.143s
```

Time with network traffic (empty terraformrc) which would allow for :

```
Terraform has been successfully initialized!

real	0m24.685s
user	0m5.162s
sys	0m1.998s
```

Second terraform init with fetching from the network:

```
real	0m5.182s
user	0m2.430s
sys	0m0.219s
```

### Attempted Solutions

As requested by https://developer.hashicorp.com/terraform/cli/config/config-file#allowing-the-provider-plugin-cache-to-break-the-dependency-lock-file we have a use case that falls under the umbrella of not what is currently supported.

We currently are setting the following in our Dockerfile as a workaround:

```
ENV TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE="NONEMPTY_NON_0_STRING_TO_KEEP_FILESYSTEM_CACHE_WORKING"
```

### Proposal

Possible proposals:

1. We would like to continue to use TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE long term.
2. Provide hashes for providers for terraform locks via environmental variables so that we can remove the provider verification from the container image instead of a .terraform.lock.hcl file.

**Comment by apparentlymart** [comment]
Hi @pguinard-public-com! Thanks for sharing this use-case.

I'm not sure I follow why the provider plugin cache is important for what you have configured here. If you are requiring all providers to be in the local filesystem mirror `/root/.terraform.d/providers-cache` anyway, what additional value is the cache directory adding? I would expect that to end up just being a redundant copy of a subset of what was already in `/root/.terraform.d/providers-cache`.

To make that more concrete, I would expect that you'd have _just_ the following in your CLI configuration, and not set the `plugin_cache_dir` option at all:

```
provider_installation {
  filesystem_mirror {
    path = "/root/.terraform.d/providers-cache"
  }
}
```

Then you can place all of your selected provider packages in that `/root/.terraform.d/providers-cache` directory at the time when you are building your Docker image, and Terraform will use that directory exclusively because you have no other installation methods configured.

(Note that despite what you named the directory, a "filesystem mirror" is not _actually_ a cache and so Terraform will only ever read from it during plugin installation, and not write to it. Therefore whatever provider packages you place there during image construction will be the only providers available for use when running in this restricted environment, and if you like you could reinforce that by setting it up to be read-only for whatever user the `terraform` process will be running as.)

Would that approach work for your situation, or am I misunderstanding something about your goal?

Thanks!

**Comment by pguinard-public-com** [comment]
I'm going to try to summarize the reasons for this first then dig into the details below. Our goal is to have a self contained image for terraform that only relies on terraform code. The reasons for this are we've had flaky results with running terraform init failing on gitlab and terraform init performance. To avoid retries we disabled all calls to registry.terraform.io and avoid third party dependencies that are not essential for terraform init to run (disable `direct`). As we don't save the .terraform folder on CI or development environments between runs we must download it from somewhere (docker is a very convenient place to version terraform providers along side terraform). All examples below have the following cleanup and terraform init done.

```
rm -rf .terraform*
terraform init -backend=false
```

> I'm not sure I follow why the provider plugin cache is important for what you have configured here. If you are requiring all providers to be in the local filesystem mirror /root/.terraform.d/providers-cache anyway, what additional value is the cache directory adding?

Plugin cache is required as we have `provider_installation { direct }` disabled. When combined with the local filesystem mirror of the filesystem that's downloaded as a cache this means that we make 0 calls out out our environment. Without also enabling plugin cache we end up getting an error while installing providers for every provider.

> To make that more concrete, I would expect that you'd have just the following in your CLI configuration, and not set the plugin_cache_dir option at all:

Config file for terraform init against an empty directory (removing the plugin_cache_dir).:

```
provider_installation {
  filesystem_mirror {
    path    = "/root/.terraform.d/providers_cache"
    include = ["registry.terraform.io/*/*"]
  }
}
```

We end up with these provider installation errors when that is the case:

```
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/aws: provider registry.terraform.io/hashicorp/aws was not found in any of the search
│ locations
│
│   - /root/.terraform.d/providers_cache
╵
```

Upon further track back to this we're making these calls outbound which sometimes causes terraform init to fail:

Configuration with direct not enabled:

```
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"

provider_installation {
  filesystem_mirror {
    path    = "/root/.terraform.d/providers_cache"
    include = ["registry.terraform.io/*/*"]
  }
  # With direct enabled, fallback to non cached providers happens always. This allows calls to third party providers to fail
  direct {}
}
```

```
- Reusing previous version of hashicorp/aws from the dependency lock file
2023-03-23T10:48:17.298-0600 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2023-03-23T10:48:17.298-0600 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/versions
- Reusing previous version of hashicorp/null from the dependency lock file
```

> Note that despite what you named the directory, a "filesystem mirror" is not actually a cache and so Terraform will only ever read from it during plugin installation.

That is expected as we run terraform init against a CI system, we could move this to another folder as well to read the cache from.

Our build process looks like this (cleaned up a bit):

Dockerfile
```
FROM debian:bullseye-slim

ARG TARGETARCH
ENV TARGETARCH=$TARGETARCH

# https://github.com/hashicorp/terraform/releases
ENV TERRAFORM_VERSION="1.4.2"
# https://registry.terraform.io/providers/DataDog/datadog/latest
ENV TERRAFORM_PROVIDER_DATADOG_DATADOG="3.22.0"
# https://registry.terraform.io/providers/hashicorp/archive/latest
ENV TERRAFORM_PROVIDER_HASHICORP_ARCHIVE="2.3.0"
# https://registry.terraform.io/providers/hashicorp/aws/latest
ENV TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE="NONEMPTY_NON_0_STRING_TO_KEEP_FILESYSTEM_CACHE_WORKING"

RUN DEBIAN_FRONTEND=noninteractive && \
    apt-get update -qq && \
    apt-get upgrade -qq && \
    apt-get install -qq --no-install-recommends \
        ca-certificates \
        curl \
        git \
        jq \
        moreutils \
        unzip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt 

RUN curl --fail --silent --location \
    --output /tmp/terraform.zip \
    https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${TARGETARCH}.zip && \
    unzip -qq /tmp/terraform.zip -d /usr/local/bin

COPY bin/* /usr/local/bin/

RUN chmod +x /usr/local/bin/* && \
    terraform --version && \
    mkdir -p /root/.terraform.d/plugin-cache /root/.terraform.d/providers-cache && \
    /usr/local/bin/provider_local_download

# Must run after terraform init to download modules
COPY terraformrc /root/.terraformrc

# Test terraform working
RUN /usr/local/bin/provider_test
```

bin/provider_local_download

```
#!/usr/bin/env bash

set -euo pipefail

TEMP_PROVIDER_DIRECTORY=/terraformproviders
TEMP_PROVIDER_FILE=${TEMP_PROVIDER_DIRECTORY}/providers.tf

# Generate providers file for installation of plugins
mkdir -p ${TEMP_PROVIDER_DIRECTORY}
echo "terraform {
      required_providers {" > $TEMP_PROVIDER_FILE

for i in $(env | grep TERRAFORM_PROVIDER_) ; do
  # Provider installation
  SHORT_PROVIDER=$(echo ${i} | sed -e 's/TERRAFORM_PROVIDER_//' -e 's&_&/&' | tr 'A-Z' 'a-z')
  PROVIDER_NAME=$(echo ${SHORT_PROVIDER} | cut -f 1 -d=)
  PROVIDER_COMPANY=$(echo ${PROVIDER_NAME} | cut -f 1 -d/)
  PROVIDER_SHORT_NAME=$(echo ${PROVIDER_NAME} | cut -f 2 -d/)
  PROVIDER_VERSION=$(echo ${SHORT_PROVIDER} | cut -f 2 -d=)

  DOWNLOAD_URL="https://github.com/${PROVIDER_COMPANY}/terraform-provider-${PROVIDER_SHORT_NAME}/archive/refs/tags/v${PROVIDER_VERSION}.zip"
  DOWNLOAD_TARGET="${HOME}/.terraform.d/providers-cache/registry.terraform.io/${PROVIDER_COMPANY}/${PROVIDER_SHORT_NAME}/${PROVIDER_VERSION}/linux_${TARGETARCH}"
  mkdir -p ${DOWNLOAD_TARGET}
  echo "Caching ${DOWNLOAD_URL} in ${DOWNLOAD_TARGET}/v${PROVIDER_VERSION}.zip"
  curl -sLo ${DOWNLOAD_TARGET}/v${PROVIDER_VERSION}.zip ${DOWNLOAD_URL}

  # Generate providers file for installation of plugins
  echo "    ${PROVIDER_SHORT_NAME} = {
            source = \"${PROVIDER_COMPANY}/${PROVIDER_SHORT_NAME}\"
            version = \"${PROVIDER_VERSION}\"
            }" >> $TEMP_PROVIDER_FILE
done

# Generate providers file for installation of plugins
echo "  }
     }" >> $TEMP_PROVIDER_FILE

# Dependency installation
TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache terraform -chdir=/${TEMP_PROVIDER_DIRECTORY} init
rm -rf /${TEMP_PROVIDER_DIRECTORY}
```

bin/provider_test
```
#!/usr/bin/env bash

set -euo pipefail

# Expected outcome is a file similar to deployment/src/main/docker/terraformproviders/providers.tf

mkdir temp
cd temp || exit 1

echo 'terraform {
  required_providers {' > providers.tf
env | grep TERRAFORM_PROVIDER | sed -e 's/TERRAFORM_PROVIDER_\(.*\)_\(.*\)=\(.*\)/      \2 = {\n       source = "\1\/\2"\n      }/' -e 's/[A-Z]/\L&/g' >> providers.tf

echo '  }
}' >> providers.tf

terraform init -backend=false

cd .. || exit 1
rm -rf temp
```

**Comment by apparentlymart** [comment]
Hi @pguinard-public-com,

Thanks for sharing all of these details!

I think if you replace the final command in your `provider_local_download` script with the following then you will no longer need the cache directory:

```
terraform providers mirror /root/.terraform.d/providers_cache
```

This will tell Terraform to populate the filesystem mirror directory in `/root/.terraform.d/providers_cache` with packages for all of the providers required by the current configuration, which in your case are the ones you've listed in your generated `required_providers` block. You do not need to set `TF_PLUGIN_CACHE_DIR` when running that command, because the path on the command line directly tells Terraform where to construct the mirror.

This means that the `hashicorp/aws` provider will then be available in your filesystem mirror directory, avoiding the error you reported. You should then be able to use the reduced CLI configuration file I proposed, which only mentions the filesystem mirror directory and does not enable the cache directory.

The cache directory is intended for situations where providers are being installed over the network, so that Terraform can sometimes reuse packages it already downloaded and thus avoid re-downloading them when the cache contents are already sufficient. It doesn't provide any value if all of your installation is from local disk anyway, since you can instead prepopulate your mirror with the providers you need and Terraform can install them directoy from that mirror directory.

**Comment by pguinard-public-com** [comment]
> This means that the hashicorp/aws provider will then be available in your filesystem mirror directory, avoiding the error you reported. You should then be able to use the reduced CLI configuration file I proposed, which only mentions the filesystem mirror directory and does not enable the cache directory.

This appears to be the root problem that lead us to adding `plugin_cache_may_break_dependency_lock_file` to our configuration.

At this point we can't install the plugins with the following files missing (same configuration as above but with this as a diff):

```
diff --git a/bin/provider_local_download b/bin/provider_local_download
index ec205b9..79e3845 100644
--- a/bin/provider_local_download
+++ b/bin/provider_local_download
@@ -36,5 +36,5 @@ echo "  }
      }" >> $TEMP_PROVIDER_FILE

 # Dependency installation
-TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache terraform -chdir=/${TEMP_PROVIDER_DIRECTORY} init
+terraform providers mirror /root/.terraform.d/providers-cache
 rm -rf /${TEMP_PROVIDER_DIRECTORY}
```

```
- Finding latest version of hashicorp/archive...
2023-03-24T20:15:56.977Z [WARN]  ignoring file "registry.terraform.io/datadog/datadog/index.json" as possible package for registry.terraform.io/datadog/datadog: filename lacks expected prefix "terraform-provider-datadog_"
2023-03-24T20:15:56.977Z [WARN]  ignoring file "registry.terraform.io/hashicorp/archive/index.json" as possible package for registry.terraform.io/hashicorp/archive: filename lacks expected prefix "terraform-provider-archive_"
- Finding latest version of datadog/datadog...
2023-03-24T20:15:56.978Z [WARN]  plugin_cache_may_break_dependency_lock_file: Using global cache dir package for registry.terraform.io/hashicorp/archive v2.3.0 even though it doesn't match this configuration's dependency lock file
- Using hashicorp/archive v2.3.0 from the shared cache directory
2023-03-24T20:15:56.978Z [WARN]  plugin_cache_may_break_dependency_lock_file: Using global cache dir package for registry.terraform.io/datadog/datadog v3.22.0 even though it doesn't match this configuration's dependency lock file
- Using datadog/datadog v3.22.0 from the shared cache directory
╷
│ Error: Failed to install provider from shared cache
│
│ Error while importing hashicorp/archive v2.3.0 from the shared cache directory: provider binary not found: could not find executable file starting with
│ terraform-provider-archive.
╵

╷
│ Error: Failed to install provider from shared cache
│
│ Error while importing datadog/datadog v3.22.0 from the shared cache directory: provider binary not found: could not find executable file starting with
│ terraform-provider-datadog.
```

With the plugin cache commented out:

```
diff --git a/bin/provider_local_download b/bin/provider_local_download
index ec205b9..79e3845 100644
--- a/bin/provider_local_download
+++ b/bin/provider_local_download
@@ -36,5 +36,5 @@ echo "  }
      }" >> $TEMP_PROVIDER_FILE

 # Dependency installation
-TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache terraform -chdir=/${TEMP_PROVIDER_DIRECTORY} init
+terraform providers mirror /root/.terraform.d/providers-cache
 rm -rf /${TEMP_PROVIDER_DIRECTORY}
diff --git a/terraformrc b/terraformrc
index 1c616a4..feed47a 100644
--- a/terraformrc
+++ b/terraformrc
@@ -1,4 +1,4 @@
-plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
+#plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"

 provider_installation {
   filesystem_mirror {
```

We run into these errors:

```
2023-03-24T20:21:58.535Z [WARN]  ignoring file "registry.terraform.io/datadog/datadog/index.json" as possible package for registry.terraform.io/datadog/datadog: filename lacks expected prefix "terraform-provider-datadog_"
2023-03-24T20:21:58.535Z [WARN]  ignoring file "registry.terraform.io/hashicorp/archive/index.json" as possible package for registry.terraform.io/hashicorp/archive: filename lacks expected prefix "terraform-provider-archive_"
- Finding latest version of hashicorp/archive...
- Installing datadog/datadog v3.22.0...
- Installing hashicorp/archive v2.3.0...
╷
│ Error: Failed to install provider
│
│ Error while installing datadog/datadog v3.22.0: provider binary not found: could not find executable file starting with terraform-provider-datadog
╵

╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/archive v2.3.0: provider binary not found: could not find executable file starting with terraform-provider-archive
╵
```
Currently working behavior which shows that the lock file doesn't match the local cache so we have to exclude it:

```
2023-03-24T20:30:32.910Z [WARN]  plugin_cache_may_break_dependency_lock_file: Using global cache dir package for registry.terraform.io/hashicorp/archive v2.3.0 even though it doesn't match this configuration's dependency lock file
- Using hashicorp/archive v2.3.0 from the shared cache directory
2023-03-24T20:30:32.947Z [WARN]  plugin_cache_may_break_dependency_lock_file: Using global cache dir package for registry.terraform.io/datadog/datadog v3.22.0 even though it doesn't match this configuration's dependency lock file
- Using datadog/datadog v3.22.0 from the shared cache directory
```

**Comment by pguinard-public-com** [comment]
Here's what I've done in order to resolve the issues with the plugin cache disabled while running `terraform providers mirror /root/.terraform.d/providers-cache`:

```
cp registry.terraform.io/hashicorp/archive/2.3.0/linux_amd64/v2.3.0.zip registry.terraform.io/hashicorp/archive/2.3.0/linux_amd64/terraform-provider-archive_v2.3.0.zip
cp registry.terraform.io/datadog/datadog/3.22.0/linux_amd64/v3.22.0.zip registry.terraform.io/datadog/datadog/3.22.0/linux_amd64/terraform-provider-datadog_v3.22.0.zip
```

**Comment by billyfoss** [comment]
@apparentlymart  
We have also been using a container image to create a snapshot in time of all our terraform modules along with the terraform binary, providers and other tools like terragrunt.  We have been using `terraform providers mirror` to pull providers locally.  I recently experimented with adding `TF_PLUGIN_CACHE_DIR` and discovered there is a significant difference in filesystem size in our use case where terragrunt is executing many terraform configurations in the same image.

Without plugin-cache
```
4.0K	/home/default/.terraform.d/plugin-cache
100M	/home/default/.terraform.d/plugins
1.6G	/tmp/.terragrunt-cache-16d300/
```
With plugin-cache
```
283M	/home/default/.terraform.d/plugin-cache
100M	/home/default/.terraform.d/plugins
199M	/tmp/.terragrunt-cache-16d300/
```

When I investigated why, I saw that the plugins mirror contains the archived files and the plugin-cache has binaries extracted.  

```
$ find /home/default/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/google
/home/default/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/google
/home/default/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/google/4.59.0
/home/default/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/google/4.59.0/linux_amd64
/home/default/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/google/4.59.0/linux_amd64/terraform-provider-google_v4.59.0_x5

$ find /home/default/.terraform.d/plugins/registry.terraform.io/hashicorp/google
/home/default/.terraform.d/plugins/registry.terraform.io/hashicorp/google
/home/default/.terraform.d/plugins/registry.terraform.io/hashicorp/google/terraform-provider-google_4.59.0_linux_amd64.zip
/home/default/.terraform.d/plugins/registry.terraform.io/hashicorp/google/index.json
/home/default/.terraform.d/plugins/registry.terraform.io/hashicorp/google/4.59.0.json
```

Without the plugin-cache, terraform is extracting the archive each time into the .terraform directory.  However, when the plugin-cache is configured, terraform is able to use symlinks instead.



I am adding some test cases with 1.4 where I am using `terraform init -backend=false` and I'm seeing this error which looks related to the original issue. 

```
Initializing provider plugins...
- Finding hashicorp/google versions matching "~> 4.10"...
- Finding hashicorp/google-beta versions matching "~> 4.10"...
- Finding hashicorp/external versions matching "~> 2.1"...
- Finding hashicorp/null versions matching "~> 2.0"...
- Finding hashicorp/random versions matching "~> 2.0"...
- Using hashicorp/google v4.59.0 from the shared cache directory
- Using hashicorp/google-beta v4.59.0 from the shared cache directory
- Using hashicorp/external v2.3.1 from the shared cache directory
- Using hashicorp/null v2.1.2 from the shared cache directory
- Using hashicorp/random v2.3.1 from the shared cache directory

Error: Failed to install provider from shared cache

Error while importing hashicorp/google v4.59.0 from the shared cache directory: the provider cache at .terraform/providers has a copy of registry.terraform.io/hashicorp/google 4.59.0 that
doesn't match any of the checksums recorded in the dependency lock file.


```

I have `plugin_cache_may_break_dependency_lock_file = true` in my .terraformrc

I see there is a difference between a packed and unpacked mirror of the plugins, but I'm not sure how to get the `terraform providers mirror` to generate the unpacked version to avoid extracting the binaries locally in every .terraform folder.

**Comment by pguinard-public-com** [comment]
I think we've got our issues resolved and tracked back to having the providers after finding some strange behavior from using `/root/.terraform.d/providers_cache` as the provider cache moving this to a different folder gets our strange issues resolved!
