### ISSUE TITLE
"text file busy" message when running init with plugin_cache_dir set (sometimes)

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform#32915]
### Terraform Version

```shell
Terraform v1.4.2
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
  }
}
```

### Debug Output

This is intermittent, the next time it occurs I can try a debug.

### Expected Behavior

install/use provider.

### Actual Behavior

```
Error: Failed to install provider

Error while installing hashicorp/kubernetes v2.19.0: open
/home/atlantis/.terraform.d/plugin-cache/registry.terraform.io/hashicorp/kubernetes/2.19.0/linux_amd64/terraform-provider-kubernetes_v2.19.0_x5:
text file busy
```

### Steps to Reproduce

1. `terraform init`

### Additional Context

This is intermittent and the only way I can correct it when it happens it to remove the cached provider.

**Comment by jbardin** [comment]
Hi @grimm26,

The message `text file busy` come from when something is attempting to overwrite the executable for a running process which is using the same data. The plugin cache is not safe for concurrent access, and overwriting running providers can result in unexpected behavior.

We can track the existing issue over in #31964

**Comment by grimm26** [comment]
Interesting, I am using terragrunt like the issue you reference, but am only initializing one directory. Is there some sort of semaphore lock left in place or something? Cuz once that error crops up, it won't stop until I delete the provider plugin file.

**Comment by jbardin** [comment]
There is no mandatory file locking in most filesystems, so there's no way to prevent this entirely, especially if the terraform process is not even running at the time. I would first check for errant provider processes continuing in the background, maybe there's something about how Terragrunt is managing the child processes causing these to linger more frequently.

**Comment by grimm26** [comment]
Yeah that's my feeling as well. I can't seem to force it to happen, though. I'll just hope it fails again 🤣
