### ISSUE TITLE
Error: Failed to load state: Terraform 1.4.2 does not support state version 4, please update.

### ISSUE THREAD

**Issue by MotorCityCobra** [hashicorp/terraform#32917]
### Terraform Version

```shell
Error: Failed to load state: Terraform 1.4.2 does not support state version 4, please update.
```

### Terraform Configuration Files

The most recent in 1.4.2

### Debug Output

Error: Failed to load state: Terraform 1.4.2 does not support state version 4, please update.

### Expected Behavior

No error

### Actual Behavior

Error: Failed to load state: Terraform 1.4.2 does not support state version 4, please update.

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Duplicate of #24168
