### ISSUE TITLE
Error: An argument named "ip_restriction" is not expected here. Did you mean to define a block of type "ip_restriction"

### ISSUE THREAD

**Issue by abragsta** [hashicorp/terraform#32912]
### Terraform Version

```shell
1.4.2
```

### Terraform Configuration Files

 ``` Not relevant ``` 

### Debug Output

on appservice.tf line 45, in resource "azurerm_linux_web_app" "default":
│   45:     ip_restriction =  []
│
│ An argument named "ip_restriction" is not expected here. Did you mean to define a block of type "ip_restriction"?

### Expected Behavior

No error

### Actual Behavior

Getting error: "An argument named "ip_restriction" is not expected here. Did you mean to define a block of type "ip_restriction"?"

### Steps to Reproduce

This is a problem that started to appear after azurerm provider version 3.49.0. When I set the provider version to 3.48.0 it works. I can see no changes in the documentation to suggest any major changes to ip_restriction block, so I assume this is a bug.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
