### ISSUE TITLE
Integer field are not supported beyond 10 digits

### ISSUE THREAD

**Issue by chenzengyao** [hashicorp/terraform#32922]
### Terraform Version

```shell
terraform --version
Terraform v1.4.2
on windows_386
```

### Terraform Configuration Files

resource "databricks_metastore_assignment" "metastore_assignment" {
  workspace_id = locals.workspace_id
}

locals { 
 workspace_id  = 253028773689279
}

### Debug Output

https://gist.github.com/chenzengyao/e22027afe63a3e4bdf597c94b3b5e764

### Expected Behavior

the workspace_id should be recognised and the resource should be added in the plan.

### Actual Behavior

Error: Attribute must be a whole number, got 2.53028773689279e+14
│
│   with module.metastore_assignment.databricks_metastore_assignment.metastore_assignment,
│   on databricks_modules\unity_catalog\metastore_assignment\metastore_assignment.tf line 6, in resource "databricks_metastore_assignment" "metastore_assignment":     
│    6:   workspace_id = local.workspace_id

### Steps to Reproduce

1. terraform init
2. terraform plan

### Additional Context

I tried removing the digits down to 9 digits and the terraform plan works without error, anything above 9 digits and the error will appear.
I only encounter this error when using Terraform v1.4.2. However, when I use Terraform 1.3.9 there aren't any errors.

**Comment by jbardin** [comment]
Hi @chenzengyao,

In general an opaque attribute like `workspace_id` should not be a number if there is no reason to use numeric operations on that value. The error show is an example of why, the value `2.53028773689279e` is identical to `253028773689279`, but is being rejected by the provider's validation. I suspect you are not only switching from v1.3 to v1.4, but you are also switching from a 64bit to a 32bit build, which means that the number `253028773689279` can no longer be stored as an integer and is being converted to a floating point value. While the provider should be responsible for using a more appropriate data type here, in the meantime you can use a 64bit release to ensure that the value can be stored in the default integer size.

You can check existing issues and file a new ones in the provider's project repository, linked from the their registry page. If you have more questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
