### ISSUE TITLE
no matching CloudFront Cache Policy (Managed-CORS-CustomOrigin)

### ISSUE THREAD

**Issue by leonarac** [hashicorp/terraform#32939]
### Terraform Version

```shell
Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.4.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

I have a data to get the id of a cloudfront policy, when the value is set to lookup the id with the name "Managed-CachingOptimized" it correctly returns the id, but when "Managed-CORS-CustomOrigin" is assigned I get the following error : │ Error: no matching CloudFront Cache Policy (Managed-CORS-S3Origin)

```
data.tf
```

```
data "aws_cloudfront_cache_policy" "origin_request_policy_id" {
  name     = "Managed-CORS-S3Origin"
}

output "idpolicy" {
  value = "Managed-CORS-CustomOrigin"
}
```

```
main.tf
```
```
output "idoplicy" {
  value = module.cloudfront.idpolicy
}
```

### Debug Output

```

│ Error: no matching CloudFront Cache Policy (Managed-CORS-CustomOrigin)
│
│   with module.cloudfront.data.aws_cloudfront_cache_policy.origin_request_policy_id,
│   on modules\cloudfront\data.tf line 26, in data "aws_cloudfront_cache_policy" "origin_request_policy_id":
│   26: data "aws_cloudfront_cache_policy" "origin_request_policy_id" {

```

### Expected Behavior

```

 idpolicy = {
      + comment           = "Policy with caching enabled. Supports Gzip and Brotli compression."      + default_ttl                                     = 86400
      + etag              = "E23ZP02F085DFQ"
      + id                = "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf"
}
```

### Actual Behavior

```

│ Error: no matching CloudFront Cache Policy (Managed-CORS-CustomOrigin)
│
│   with module.cloudfront.data.aws_cloudfront_cache_policy.origin_request_policy_id,
│   on modules\cloudfront\data.tf line 26, in data "aws_cloudfront_cache_policy" "origin_request_policy_id":
│   26: data "aws_cloudfront_cache_policy" "origin_request_policy_id" {

```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Additional Context

If we try to find the id from the **Managed-CachingOptimized** policy if it returns the id correctly..

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
