### ISSUE TITLE
New vesions missing on apt repos

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform#32964]
### Terraform Version

```shell
n/a
```

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

The latest version of Terraform (1.4.3 / 1.4.4) should get installed

### Actual Behavior

The terraform package is not installed

### Steps to Reproduce

1. Setup a machine / container / instance following the official docs for installing terraform via apt
1. apt install terraform=1.4.4

### Additional Context

Normally we use the official docker image, but for some of our CI pipelines, we start with an Ubuntu base needed for other things, and install Ubuntu on top of this.

Assuming this is related to the changes in release process mentioned in the 1.4.4 changelog.

### References

https://discuss.hashicorp.com/t/ubuntu-download-not-working-for-1-4-3-1-4-4/52133

**Comment by wyardley** [comment]
FWIW, this worked for us consistently without that prior to 1.4.3.
I can confirm that with the glob, it works; is the change in behavior expected, though?

**Comment by jbardin** [comment]
Yes, technically is was expected, although unfortunately this was a change which slipped through the cracks and was not anticipated at this point to be communicated effectively. The Debian package version should have had a revision by default being a non-native package, which was announced last year, however Terraform is only now migrating to the new release tooling. We'll make sure any related documentation is updated.

Thanks!
