### ISSUE TITLE
Azure Terraform in application gateway

### ISSUE THREAD

**Issue by muralikrishnarokkam** [hashicorp/terraform#32974]
### Terraform Version

```shell
Got an below error while executing terraform in application gateway module. 

Error: ID was missing the `firewallPolicies` element
```

### Terraform Configuration Files

```terraform
...terraform config...
```
  required_providers {
     azurerm = {
      source = "hashicorp/azurerm"
      

### Debug Output

Error: ID was missing the `firewallPolicies` element

  with module.CognosModule.azurerm_application_gateway.iQPR-ApplicationGateway["iQPRAppGW"],
  on Modules\CognosModule\iqprAppGatway.tf line 77, in resource "azurerm_application_gateway" "iQPR-ApplicationGateway":
  77: resource "azurerm_application_gateway" "iQPR-ApplicationGateway" {

Error: ID was missing the `firewallPolicies` element

  with module.CognosModule.azurerm_application_gateway.iQPR-ApplicationGateway["iQPRAppGW"],
  on Modules\CognosModule\iqprAppGatway.tf line 77, in resource "azurerm_application_gateway" "iQPR-ApplicationGateway":
  77: resource "azurerm_application_gateway" "iQPR-ApplicationGateway" {

### Expected Behavior

this firewall policies should not be there in application gateway 

### Actual Behavior

this firewall policies should not be there in application gateway 

### Steps to Reproduce

in terraform plan

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
