### ISSUE TITLE
terraform_1.3.9_darwin_arm64.zip sha has changed

### ISSUE THREAD

**Issue by Ubehebe** [hashicorp/terraform#32978]
### Terraform Version

```shell
1.3.9
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

On 24 February 2023, I recorded the sha256 of             https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_darwin_arm64.zip as `9df6fc8a9264bba1058e6e9383f43af2ee816088e61925e5bc45128ad8b6e9ad`.

### Actual Behavior

On 1 April 2023, I redownloaded https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_darwin_arm64.zip and discovered that its sha256 is now `d8a59a794a7f99b484a07a0ed2aa6520921d146ac5a7f4b1b806dcf5c4af0525`.

### Steps to Reproduce

`curl https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_darwin_arm64.zip | shasum -a256` shows that the current sha256 of the file is `d8a59a794a7f99b484a07a0ed2aa6520921d146ac5a7f4b1b806dcf5c4af0525`.

### Additional Context

Fortunately, I still have a copy of terraform_1.3.9_darwin_arm64.zip with the old sha, so I tried to diff it against the new zip:

```
$ diff <(unzip -l terraform_1.3.9_good.zip) <(unzip -l terraform_1.3.9_bad.zip)
1c1
< Archive:  terraform_1.3.9_good.zip
---
> Archive:  terraform_1.3.9_bad.zip
4c4
<  67273232  02-15-2023 09:23   terraform
---
>  67273232  03-10-2023 12:11   terraform
```

This shows that both zip files contain a single `terraform` executable of exactly the same size, but different timestamps.

I then extracted both executables and ran a bytewise comparison:

```
$ cmp --print-bytes good/terraform bad/terraform
good/terraform bad/terraform differ: char 66739736, line 216976 is 243  242
```

(This prints only the first difference; `cmp --print-bytes --verbose good/terraform bad/terraform | wc -l` shows there are 4403 differences.)

Since `terraform` is a compiled Go binary, I'm not sure what changed. (diffing the `strings` output doesn't turn up anything.)

### References

The Terraform release shas occasionally change, and people occasionally notice. In https://github.com/hashicorp/terraform/issues/20701#issuecomment-473397236, @svanharmelen stated that

>  if a situation like this [sha change] occurs again we plan to issue a new release and not re-issue a previous release.

**Comment by jbardin** [comment]
Hi @Ubehebe,

This was expected as the signature in Darwin binaries was updated, and the signed checksums were concurrently updated to match. As long as the signature authenticates the checksums, the published values can be trusted.

See [Security at HashiCorp](https://www.hashicorp.com/security) for more details about the types of signatures available.

Thanks!

**Comment by Ubehebe** [comment]
Thanks for the clarification and all your work on a great product.
