### ISSUE TITLE
Azure add support for Resource Manager

### ISSUE THREAD

**Issue by spuder** [hashicorp/terraform#3297]
Azure has a new way of creating resources called "Resource Manager". They are moving everything else to "classic" 

https://azure.microsoft.com/en-us/documentation/articles/azure-classic-rm/

Could terraform add support for this new API? 

Related
https://github.com/hashicorp/terraform/issues/3266

**Comment by stack72** [comment]
@spuder this has been requested here #3212 so it's worth keeping an eye on that ticket

**Comment by spuder** [comment]
Thanks
