### ISSUE TITLE
Variable Definition Precedence

### ISSUE THREAD

**Issue by dix** [hashicorp/terraform#32989]
### Terraform Version

```shell
v1.4.0
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/values/variables
https://developer.hashicorp.com/terraform/tutorials/certification-associate-tutorials-003/cloud-vcs-change

### What is the docs issue?

According to the documentation[1], the `*.auto.tfvars` files have the second highest priority to set the value of variables, just after CLI options.

But according to the tutorial[2],  `Note that auto.tfvars files have the lowest precedence in a workspace`.

Did I misunderstood the tutorial or the doc, or both? Or are they stating contradictory information?

[1] : https://github.com/hashicorp/terraform/blob/main/website/docs/language/values/variables.mdx?plain=1#L495
[2]: https://developer.hashicorp.com/terraform/tutorials/certification-associate-tutorials-003/cloud-vcs-change#update-configuration

**Comment by apparentlymart** [comment]
Thanks for reporting this, @dix.

I think the tutorial you linked to as [2] is being a bit simplistic in its explanation, and so it isn't clear to me what scope it's intending when it asserts that the auto files have the "lowest precedence".

One important consideration in comparing these is that your [1] is discussing Terraform CLI while the tutorial [2] is discussing Terraform Cloud where there are some additional considerations.

Terraform Cloud modifies the basic Terraform CLI behavior as follows:

* Before running Terraform CLI, Terraform Cloud generates a `terraform.tfvars` file containing all of the values configured either directly in the workspace settings or in "variable sets" that are applicable to the workspace. Therefore all of those values inherit the precedence described for `terraform.tfvars` in the first docs.
* Terraform Cloud's API allows setting additional variable values as part of creating a run, and those will take precedence over the ones in the workspace settings.

Terraform Cloud has no direct awareness of `.auto.tfvars` files and so those are handled by Terraform CLI only, do their precedence is what documentation [1] describes, if read with the two modifications I described above.

**Comment by dix** [comment]
Hi,

Thank you for the explanations @apparentlymart  and sorry for the time it took me to see it.

I now have a better understanding on what those two separate documents mean.
