### ISSUE TITLE
aws_cognito_user_pool_client bug

### ISSUE THREAD

**Issue by aloftaizzz** [hashicorp/terraform#32998]
### Terraform Version

```shell
Terraform v1.4.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.61.0
```

### Terraform Configuration Files

```

resource "aws_cognito_user_pool_client" "client" {
  user_pool_id = aws_cognito_user_pool.user_pool.id
  access_token_validity = 1
  allowed_oauth_flows = ["code"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes = ["email", "openid"]
  callback_urls = values(var.cognito_callback_urls)
  default_redirect_uri = var.cognito_callback_urls.aircontrol
  enable_propagate_additional_user_context_data = false
  enable_token_revocation = false
  explicit_auth_flows                  = [
    "ALLOW_CUSTOM_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_USER_SRP_AUTH",
  ]
  id_token_validity = 1
  logout_urls                          = values(var.cognito_logout_urls)
  name = local.user-pool.client_name
  read_attributes                      = ["email", "email_verified"]
  refresh_token_validity    = 30
  write_attributes = []
  token_validity_units  {
    access_token  = "days"
    id_token      = "days"
    refresh_token = "days"
  }

 lifecycle {
  ignore_changes = [ enable_token_revocation ]
  }


}

```

### Debug Output

none

### Expected Behavior

Should have created the resource

### Actual Behavior

╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to aws_cognito_user_pool_client.client, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: .write_attributes: was cty.SetValEmpty(cty.String), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by aloftaizzz** [comment]
thank you, sorry for that
