### ISSUE TITLE
Please add an example data structure for the for_each flatten example

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform#33017]
### Terraform Version

```shell
Terraform v1.3.8
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Pages

https://github.com/hashicorp/terraform/blob/main/website/docs/language/functions/flatten.mdx

### What is the docs issue?

I'm trying to understand the "Flattening nested structures for for_each" example on the page.  I'm having trouble getting the example to run because I can't quite figure out a default value for the 'networks' variable.

### Proposal

If you would please add a default value to the 'networks' variable that would allow me to run the example I would really appreciate it.

**Comment by crw** [comment]
Thanks for this request! I put it on the docs queue. If you come up with a working example, please share it here or open a pull request, we would be happy to review it.

**Comment by Dmitry-White** [comment]
@crw @DevopsMercenary
Hey everyone!
I've recently stumbled on this example myself and can definitely related to this issue :sweat_smile:
I must say `HashiCorp Terraform` plugin for VS Code did help a lot, so creating a PR with an extended example variable to share:
https://github.com/hashicorp/terraform/pull/33046
