### ISSUE TITLE
Failure in aws_elb with multiple listeners

### ISSUE THREAD

**Issue by silvamerica** [hashicorp/terraform#3301]
I seem to be getting a failure the first time I try to run apply. If I run it again it, it works. My listener config is:

    listener {
      instance_port = 389
      instance_protocol = "tcp"
      lb_port = 389
      lb_protocol = "tcp"
    }

    listener {
      instance_port = 636
      instance_protocol = "tcp"
      lb_port = 636
      lb_protocol = "tcp"
      ssl_certificate_id = "ssl-cert"
    }

The first error is:

    Failure adding new or updated ELB listeners: DuplicateListener: A listener already exists for terraform-ldap-staging with LoadBalancerPort 636, but with a different InstancePort, Protocol, or SSLCertificateId
    status code: 400

If I re-run apply, everything works.

**Comment by catsby** [comment]
Hey @silvamerica – I believe this is fixed in https://github.com/hashicorp/terraform/pull/3898

Note that `ssl_certificate_id` is only valid for HTTPS, or SSL protocols. Otherwise, AWS will discard the contents of `ssl_certificate_id`.

**Comment by mrwilby** [comment]
Was this fixed? I see the exact same symptoms as reported by the OP...

**Comment by dharmeshpurohit-24** [comment]
Hi, silvamerica
just remove the ssl_certificate_id from the second listener and it will work fine. We can only use "ssl_certificate_id " for either ssl or https protocol.
For more detail please refer this link for ELB
https://www.terraform.io/docs/providers/aws/r/elb.html
