### ISSUE TITLE
Terraform init fails 

### ISSUE THREAD

**Issue by aratim233** [hashicorp/terraform#33014]
### Terraform Version

```shell
Terraform v0.12.31
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Initializing modules...

Initializing the backend...

Error: Error building ARM Config: Error populating Client ID from the Azure CLI: No Authorization Tokens were found - please ensure the Azure CLI is installed and then log-in with `az login`.

### Expected Behavior

To initialize the terraform modules correctly

### Actual Behavior

Initializing modules...

Initializing the backend...

Error: Error building ARM Config: Error populating Client ID from the Azure CLI: No Authorization Tokens were found - please ensure the Azure CLI is installed and then log-in with `az login`.

### Steps to Reproduce

terraform init

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
