### ISSUE TITLE
Invalid URLs in Terraform Associate Certification (003) Study Guide

### ISSUE THREAD

**Issue by keivinonline** [hashicorp/terraform#33010]
### Terraform Version

```shell
Not applicable
```

### Affected Pages

https://developer.hashicorp.com/terraform/tutorials/certification-003/associate-study-003#understand-terraform-cloud

### What is the docs issue?

The following hyperlinks in the documentation section are pointing to invalid pages
- [Terraform Cloud Workspaces](https://developer.hashicorp.com/terraform/docs/cloud/workspaces/index) documentation
- [Sentinel](https://developer.hashicorp.com/terraform/docs/cloud/sentinel/index) documentation

### Proposal

There doesn't seem to be an `overview` for sentinel 
Perhaps the following would be the intended links. 

Teraform Cloud Workspaces - https://developer.hashicorp.com/terraform/cloud-docs/workspaces 
Sentinel - https://developer.hashicorp.com/terraform/cloud-docs/policy-enforcement or https://developer.hashicorp.com/terraform/cloud-docs/policy-enforcement/sentinel

**Comment by StephenDunne97** [comment]
Hello, I would like to work on this PR.

**Comment by ritsok** [comment]
Thanks so much for reporting this! Published a fix.
