### ISSUE TITLE
Write template out as file that can be read

### ISSUE THREAD

**Issue by dbroockman** [hashicorp/terraform#3302]
My use case: I'd like to define a template index.html file that I can then upload to S3.

**Comment by apparentlymart** [comment]
Do you think #3200 would serve your use-case?

Rather than writing the file out to disk and then reading it back in, that change would allow you to just use the template result string directly when defining the S3 object resource.

**Comment by dbroockman** [comment]
Yes.

**Comment by radeksimko** [comment]
#3200 has been merged (it is possible to upload a template to S3).

Is there anything left to implement or we can close this?

**Comment by dbroockman** [comment]
Yes. Thank you!
