### ISSUE TITLE
allow reference from null_resource local-exec provisioner to vars outside of null_resource

### ISSUE THREAD

**Issue by waheedshahani** [hashicorp/terraform#33038]
### Terraform Version

```shell
1.4.5
```

### Use Cases

We create kubernetes CRD (Gardener based k8s cluster) with terraform. However they can not be destroyed with simple terraform destroy. It is requirement for that CRD that we explicitly add a particular annotation to allow the destruction of CRD. For this we have a destroy-time null_resource with local-exec provisioner where shell script is adding annotation to cluster. We need to pass kubeconfig (for authentication against k8s cluster) to shell script so that it can add annotation. This works fine. 
However if we have run "terraform apply" today and do terraform destroy later when kubeconfig token has been roatated then shell script still gets the old kubeconfig because somehow it is stored in the state file and null_resource is not recreated to change the kubeconfig content. 

### Attempted Solutions

Workaround to this is that we apply terraform once again before destroying. This way null_resources gets the fresh kubeconfig and stores it in state file so that terraform destroy again gets the fresh kubeconfig. However this is creating workflow issues and reapply may not always work.

### Proposal

allow local-exec provisioner to refer to content outside of null_resource. As of now it can use variable only available within null_resource (self).

**Comment by jbardin** [comment]
Hi @waheedshahani,

This request is already being tracked in #23679. The ability to reference other values was specifically dis-allowed because it creates invalid orders of operations during destroy, so it's not likely something which will be added back in without other restrictions.
