### ISSUE TITLE
Error: creating EC2 Spot Fleet Request: InvalidSpotFleetRequestConfig: The specified Subnet: subnet-xyz cannot be used with the specified Availability Zone: ca-central-1a.

### ISSUE THREAD

**Issue by trent-abc** [hashicorp/terraform#33040]
### Terraform Version

```shell
Terraform v1.4.3-dev
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.62.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.4.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform

resource "aws_launch_template" "jenkins_agent" {
…
  # instance_type = "t2.large"
  instance_requirements {
    allowed_instance_types = [
        "c5.xlarge",
        "c6i.2xlarge",
        "t2.large",
        "t3.large",
    ]
    memory_mib {
        max = 32768
        min = 8192
      }
    vcpu_count {
        max = 16
        min = 4
    }
  }
  network_interfaces {
    subnet_id = aws_subnet.ca-central-1a-private.id
  }
  placement {
    availability_zone = "ca-central-1a"
  }
…
}
resource "aws_spot_fleet_request" "jenkins_agent_fleet" {
  iam_fleet_role  = "arn:aws:iam::XXXXXXXXXX:role/aws-service-role/spotfleet.amazonaws.com/AWSServiceRoleForEC2SpotFleet"
  target_capacity = 0
  launch_template_config {
    launch_template_specification {
      id = aws_launch_template.jenkins_agent.id
      version = aws_launch_template.jenkins_agent.latest_version
    }
  }
}
```

### Debug Output

unnecessary 

### Expected Behavior

Successfully applied

### Actual Behavior

╷
│ Error: creating EC2 Spot Fleet Request: InvalidSpotFleetRequestConfig: The specified Subnet: subnet-XYZ cannot be used with the specified Availability Zone: ca-central-1a.
│ 	status code: 400, request id: ABC-DEF-GHI-JKL
│
│   with aws_spot_fleet_request.jenkins_agent_fleet_requirements_based,
│   on fleet.tf line 165, in resource "aws_spot_fleet_request" "jenkins_agent_fleet_requirements_based":
│  165: resource "aws_spot_fleet_request" "jenkins_agent_fleet_requirements_based" {
│
╵

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

Ok, inside the aws_launch_template block I have parameter 

instance_requirements

If this is set we get the error as described above.  If instead I comment that block out and use:

 instance_type = "t2.large"

The provisioning is successful.

Notice target_capacity = 0 in the aws_spot_fleet_request block, this is important, and I want a capacity of 0 because Jenkins is managing the fleet, provisioning additional nodes when it needs them.  I tried to provision via AWS UI and import it later into the terraform config, the launch template was successful. but when I try to set 0 instances in the aws_spot_fleet_request I can-not launch it from the UI--the button is greyed out. I'm at a loss here, why does it work when I specify instance_type but I'm getting an availability zone error when I specify instance requirements?

This should be easy enough to reproduce, but just to be clear I'm trying to use ca-central-1 and my instances are provisioned on a private subnet.

### References

https://github.com/hashicorp/terraform/issues/8203

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
