### ISSUE TITLE
The argument "duration" is required, but no definition was found in aws_lb_listener_rule.action.stickiness

### ISSUE THREAD

**Issue by chriswylim** [hashicorp/terraform#33048]
### Terraform Version

```shell
Terraform v1.2.5
```

### Terraform Configuration Files

  # Weighted Forward action
  dynamic "action" {
    for_each = { for k, v in (var.aws_lb_listener_rules_arguments[each.key]["Actions"]): "${k}:-:${v["Type"]}" => v if v["Type"] == "forward" && contains(keys(v), "TargetGroupArn") == false }
    iterator = foobar

    content {
      type            = try(foobar.value.Type, "forward")
      forward {
        target_group {
          arn    = foobar.value["ForwardConfig"]["TargetGroups"][0]["TargetGroupArn"]
          weight = foobar.value["ForwardConfig"]["TargetGroups"][0]["Weight"]
        }

        stickiness {
          enabled  = foobar.value["ForwardConfig"]["TargetGroupStickinessConfig"]["Enabled"]
          **duration = lookup(foobar.value["ForwardConfig"]["TargetGroupStickinessConfig"], "Duration", false) != false ? foobar.value["ForwardConfig"]["TargetGroupStickinessConfig"]["Duration"] : 0**
        }
      }

### Debug Output

│ Error: Missing required argument
│
│   on ../../modules/load_balancer/main.tf line 224, in resource "aws_lb_listener_rule" "clickops":
│  224:         stickiness {
│
│ The argument "duration" is required, but no definition was found.

### Expected Behavior

[duration](https://registry.terraform.io/providers/hashicorp/aws/4.63.0/docs/resources/lb_listener_rule#duration) - **(Optional)** The time period, in seconds, during which requests from a client should be routed to the same target group. The range is 1-604800 seconds (7 days).

### Actual Behavior

│ The argument "duration" is required, but no definition was found.

When it should be "Optional" as mentioned in documentation:
https://registry.terraform.io/providers/hashicorp/aws/4.63.0/docs/resources/lb_listener_rule

### Steps to Reproduce

terraform init
terraform plan

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
