### ISSUE TITLE
import docker container does not show 'forces replacement' for environment variables

### ISSUE THREAD

**Issue by hansbogert** [hashicorp/terraform#33041]
### Terraform Version

```shell
terraform version
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/kreuzwerker/docker v3.0.2
```

### Affected Pages

https://developer.hashicorp.com/terraform/tutorials/certification-associate-tutorials-003/state-import

### What is the docs issue?

There is the code listing which show the following:

![image](https://user-images.githubusercontent.com/2630900/232338309-dc3837f0-91ae-47b3-8e4b-ed8ee44f5868.png)

Note the last line, it shows the 'forces replacement'. Starting with Terraform 1.4, you will not see the 'forces replacement'

Here is my output:

![image](https://user-images.githubusercontent.com/2630900/232338401-a04e83fd-fb5c-499d-8dce-8e36952e934a.png)

### Proposal

I am unsure if this discrepancy is an intended change in Terraform 1.4. If so, the documentation should be changed.

If this is not an intended change, this might need to be converted to a provider or Terraform bug.

**Comment by hansbogert** [comment]
> If the resource is shown as being replaced, then there should be some attribute change marked as the reason for the replacement. Are there no attributes indicating forces replacement in the current plan output?

That is correct, should I create a bug report?

**Comment by jbardin** [comment]
Thanks! I'll just re-label this issue, and we can try to replicate the problem. I don't think there's any more information that would be useful, since the provider must be returning which attribute forced replacement in order to get a replacement plan at all, the change is probably due to the new renderer.

**Comment by liamcervante** [comment]
I've been able to replicate this, thankfully fix is very easy.

The unknown/computed renderer is missing the `forces replacement` display logic, so this affects attributes that are both `computed` and `forceNew`.
