### ISSUE TITLE
Terraform bundler for air-gapped environment

### ISSUE THREAD

**Issue by felixtheflex** [hashicorp/terraform#33061]
### Terraform Version

```shell
Terraform v0.13.0
```

### Terraform Configuration Files

 RUN git clone --single-branch --branch=v0.15 --depth=1 https://github.com/hashicorp/terraform.git
 WORKDIR /terraform
 RUN go build -o ../terraform-bundler ./tools/terraform-bundle && \
     cp ./tools/terraform-bundle/e2etest/testdata/many-providers/terraform-bundle.hcl ../

### Debug Output

Fetching Terraform 0.13.0 core package...
Local plugin directory ".plugins" found; scanning for provider binaries.
No ".plugins" directory found, skipping local provider discovery.
- Finding hashicorp/aws versions matching "~> 2.26.0"...
Could not retrieve the list of available versions for provider hashicorp/aws: could not query provider registry for registry.terraform.io/hashicorp/aws: the request failed after 2 attempts, please try again later: Get "https://registry.terraform.io/v1/providers/hashicorp/aws/versions": context deadline exceeded.
some providers could not be installed:
- registry.terraform.io/hashicorp/aws: could not query provider registry for registry.terraform.io/hashicorp/aws: the request failed after 2 attempts, please try again later: Get "https://registry.terraform.io/v1/providers/hashicorp/aws/versions": context deadline exceeded

### Expected Behavior

A successful terraform bundle

### Actual Behavior

Fetching Terraform 0.13.0 core package...
Local plugin directory ".plugins" found; scanning for provider binaries.
No ".plugins" directory found, skipping local provider discovery.
- Finding hashicorp/aws versions matching "~> 2.26.0"...
Could not retrieve the list of available versions for provider hashicorp/aws: could not query provider registry for registry.terraform.io/hashicorp/aws: the request failed after 2 attempts, please try again later: Get "https://registry.terraform.io/v1/providers/hashicorp/aws/versions": context deadline exceeded.
some providers could not be installed:
- registry.terraform.io/hashicorp/aws: could not query provider registry for registry.terraform.io/hashicorp/aws: the request failed after 2 attempts, please try again later: Get "https://registry.terraform.io/v1/providers/hashicorp/aws/versions": context deadline exceeded

### Steps to Reproduce

add the following to a dockerfille and build. FYI, this used to work and build without any issues..

```
FROM golang:alpine AS terraform-bundler-build

 RUN go install github.com/go-delve/delve/cmd/dlv@latest
 RUN apk --no-cache add git unzip
 WORKDIR /

 RUN git clone --single-branch --branch=v0.12 --depth=1 https://github.com/hashicorp/terraform.git
 WORKDIR /terraform
 RUN go build -o ../terraform-bundler ./tools/terraform-bundle && \
     cp ./tools/terraform-bundle/e2etest/testdata/many-providers/terraform-bundle.hcl ../
 WORKDIR /
 RUN ./terraform-bundler package terraform-bundle.hcl \
     && mkdir -p terraform-bundle \
     && unzip -d terraform-bundle terraform_*.zip
```

### Additional Context

I use docker multi build steps, the `terraform-bundler-build` step used to work without issues.

`RUN git clone --single-branch --branch=v0.15 --depth=1 https://github.com/hashicorp/terraform.git;` but I have had to changed to  `RUN git clone --single-branch --branch=v0.12 --depth=1 https://github.com/hashicorp/terraform.git` for it work.

**Comment by kmoe** [comment]
While terraform-bundler is an old tool, it does look like this would have worked if https://registry.terraform.io/v1/providers/hashicorp/aws/versions were accessible from the build environment. Are you able to curl this url from the build env?

**Comment by kmoe** [comment]
Unfortunately if that doesn't help, we're unable to provide any more support for this deprecated tool here. Please reach out through official HashiCorp support channels or use the [community forum](https://discuss.hashicorp.com/). The [terraform-bundle README](https://github.com/hashicorp/terraform/blob/main/tools/terraform-bundle/README.md) describes ways of migrating away from terraform-bundle.

**Comment by felixtheflex** [comment]
The docker image is built outside of the air-gapped environment and not within. Like I described, using `RUN git clone --single-branch --branch=v0.12` instead of `RUN git clone --single-branch --branch=v0.15` works.  But we would prefer `--branch=v0.15` instead....?
