### ISSUE TITLE
cast a whole list to int before adding each one in formatlist

### ISSUE THREAD

**Issue by glerchundi** [hashicorp/terraform#3306]
I would like to add an offset to a list, how could I do something like this?

```
variable "zones" {
    default = {
        "0" = "us-central1-a"
        "1" = "us-central1-b"
        "2" = "us-central1-c"
    }
}

output "test01" {
    value = "${join(",", formatlist("%d", 10+keys(var.zones))}"
}
```

terraform will fail (`__builtin_StringToInt: strconv.ParseInt: parsing "B780FFEC-B661-4EB8-9236-A01737AD9 [...]`) because it cannot cast to int the whole list, is it possible to cast each element and then add the offset?

I tried to use numbers as map keys but it doesn't work neither.

Is it possible to workaround somehow?

**Comment by mitchellh** [comment]
The error message is much better now, but I don't believe that INT+LIST should result in mapping +INT across the list automatically. I'm not sure if there is a better way to do this at the moment.
