### ISSUE TITLE
terraform lifecycle ignore_changes should not be static or should otherwise support conditional ignore lists

### ISSUE THREAD

**Issue by flebotany** [hashicorp/terraform#33063]
Per https://github.com/hashicorp/terraform/issues/33031#issuecomment-1507532309, this issue as written no longer describes a problem that is fully relevant in modern Terraform (circa 2023). I will quote the full comment here for posterity:

> Thanks for compiling these issues. The original issue https://github.com/hashicorp/terraform/issues/3116 is probably no longer relevant as written -- interpolation is possible and used within lifecycle, but how it's used depends on each individual feature of a resource's lifecycle. Asking for interpolation for lifecycle in general is not going to effectively change anything.
> 
> It seems you are mostly concerned with prevent_destroy specifically, and one reason that has not changed is because it cannot do what the majority of users want it to do regardless of the ability to interpolate the value. Controlling how something is destroyed from the config doesn't work when that configuration can be removed entirely. If better control over the ability to destroy a resource is what you're after, https://github.com/hashicorp/terraform/issues/22544 covers this (and already shows a lot of support), but I think https://github.com/hashicorp/terraform/issues/24658 is probably where users should indicate their support for a more useful feature in general (or with the individual provider issues where that is applicable, since absolute control can only ever be applied outside of Terraform).
> 
> Since there is no specific bug to address here, I'm going to close the issue. If you have other concerns about enhancements which are not addressed by existing issues already, we can handle those individually in separate issues.

To follow up with the modern ancestors of this issue, please see the following:

### References

- https://github.com/hashicorp/terraform/issues/24658
- https://github.com/hashicorp/terraform/issues/22544
- https://github.com/hashicorp/terraform-provider-google/issues/10168
- https://github.com/hashicorp/terraform-provider-google/issues/7868
- https://github.com/hashicorp/terraform-provider-google/issues/2078
- https://github.com/hashicorp/terraform-provider-google/issues/13661

_Originally posted by @crw in https://github.com/hashicorp/terraform/issues/3116#issuecomment-1507612949_
 
This missed the original issue I followed (https://github.com/hashicorp/terraform/issues/22546) which was about variable scope in lifecycle ignore_changes, which was closed as a dupe of this and not apparently reopened.

**Comment by flebotany** [comment]
Use case: I want to lifecycle ignore_changes for ami/image_id attributes in AWS *except* for canary regions/availability-zones without duplicating my module

**Comment by jbardin** [comment]
Hi @flebotany,

Thanks for filing the issue. It is a known limitation that `ignore_changes` isn't going to be able to solve, since it is derived from static references it cannot dynamically alter the plan for a resource. There are a number of related issues already, so I'll link these together for now and we can see about combining them into a more actionable problem statement:

#29394
#29596
#26372
#26359
#24908
#5666

Thanks!
