### ISSUE TITLE
Elasticache output general endpoint

### ISSUE THREAD

**Issue by mboret** [hashicorp/terraform#3307]
Hi,
It would be interesting to add the possibility to retrieve the endpoint(general not for node) because for example if you create a elasticache memcached, you can use the general endpoint with the AWS client Elasticache which give you the feature to automatically discover new node endpoints.

In the terraform document the only output supported seems to be for the node.

Thanks,
Matthieu

**Comment by stack72** [comment]
@mboret I added this recently ( #3250 ) - it will make it into 0.6.4 when it is released :)

**Comment by mboret** [comment]
Good news :) Thanks
