### ISSUE TITLE
Dependency between modules is not inferred properly

### ISSUE THREAD

**Issue by BrianHicks** [hashicorp/terraform#3308]
Using Terraform 0.6.3 on OSX 10.10.5:

When I try to perform operations on the following module, they're performed out of order. `./gce/base` contains a network definition, and `./gce/machine` contains a VM definition. 

`terraform apply` works alright most of the time, but `terraform destroy` tries to destroy the network without destroying the VM first. In GCE, this is an invalid operation.

```hcl
provider "google" {
  account_file = "${file("account.json")}"
  project = "company-mi"
  region = "us-central1"
}

module "bh-test-base" {
  source = "./gce/base"

  name = "bh-mantl"
}

module "bh-test-machine" {
  source = "./gce/machine"

  name = "bh-mantl-test"
  network = "${module.bh-test-base.network-name}"
  ssh_key = "~/.ssh/id_rsa.pub"
}
```

Here's the graph output. Note that the machine and network are not linked.

![graph](https://cloud.githubusercontent.com/assets/355401/10051035/118c21f4-61e5-11e5-9eff-3b681281dba6.png)

[IRC context](https://botbot.me/freenode/terraform-tool/2015-09-23/?msg=50362659&page=2), [gist with all the files](https://gist.github.com/BrianHicks/4bc44be89ef9360e7aac)

**Comment by mitchellh** [comment]
Since then and now, this has been fixed:

![graph](https://cloud.githubusercontent.com/assets/1299/17872950/9750c652-6877-11e6-9229-7297a7bb5285.png)
