### ISSUE TITLE
Add an option in ec2 terraform for the directory id selection 

### ISSUE THREAD

**Issue by Varadgoud45** [hashicorp/terraform#33088]
### Terraform Version

```shell
Terraform v1.4.5
```

### Use Cases

The main use case of this feature is to do a seamless domain join of an ec2 instance with the aws managed directory or on premises directory within seconds.

### Attempted Solutions

Yeah I have tried with the SSM documents but it is not able to do domain join properly.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
