### ISSUE TITLE
Terraform State File not Updating after Removal of Azure Storage Account Path Mappings in App Service

### ISSUE THREAD

**Issue by no-hands-hand** [hashicorp/terraform#33083]
### Terraform Version

```shell
terraform_version: 1.2.0
```

### Terraform Configuration Files

```
  storage_account {
    name = "${var.name-prefix}-adlproc-files-${var.name-suffix}"
    type = "AzureFiles"
    account_name = var.adlproc-storageaccount-name
    share_name = var.adlproc-fileshare-name
    access_key = var.adlproc-storageaccount-access-key
    mount_path = "/home/data/adl_files_processed"
  }
  storage_account {
    name = "${var.name-prefix}-fsm-files-${var.name-suffix}"
    type = "AzureFiles"
    account_name = var.adlproc-storageaccount-name
    share_name = var.fsm-fileshare-name
    access_key = var.adlproc-storageaccount-access-key
    mount_path = "/home/data/adl_files"
  }
  storage_account {
    name = "${var.name-prefix}-adl-exception-files-${var.name-suffix}"
    type = "AzureFiles"
    account_name = var.adlproc-storageaccount-name
    share_name = var.adlproc-exception-fileshare-name
    access_key = var.adlproc-storageaccount-access-key
    mount_path = "/home/data/adl_exception_files"
  }
```

### Debug Output

https://gist.github.com/no-hands-hand/c2286baeb973011e2000dfa8880e4257

### Expected Behavior

After removing these storage account mappings from the TF file, they should be removed from state file and by extension removed from app service.

### Actual Behavior

After I removed these storage account mappings from TF file, the mappings were not removed from the Terraform state file (even after doing a terraform plan) and are still present in the app service without 

### Steps to Reproduce

1. 'terraform init'
2. 'terraform plan'
3. 'terraform init'
4. 'terraform apply'

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
