### ISSUE TITLE
Terraform Import of resource, created in for_each loop, not working

### ISSUE THREAD

**Issue by sjackson0109** [hashicorp/terraform#33114]
### Terraform Version

```shell
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.41.0
```

### Terraform Configuration Files

```
terraform {
  required_version = ">=1.2"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.11.0, <4.0"
    }
  }
}
provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}
variable "fw" {
  default = {}
}

fw = {
  name = "TESTING_FIREWALL"
  sku = {
    name = "AZFW_VNet"
    tier = "Standard"
  }
  private_ip_ranges = null #consider IANA RFV 1918
  // Azure Firewall had a single out-of-band management_ip
  management_ip = {
    name              = "TESTING-FIREWALL-PIP-MGMT"
    allocation_method = "Static"
    sku               = "Standard"
  }
public_ip = {
    0 = {
      name              = "TESTING-FIREWALL-PIP-01"
      allocation_method = "Static"
      sku               = "Standard"
    }
    1 = {
      name              = "TESTING-FIREWALL-PIP-02"
      allocation_method = "Static"
      sku               = "Standard"
    }
   # add more PIPs here if you need more, ACL+DNAT rules could be used on dedicated PIPs etc
}
resource "azurerm_public_ip" "uks_fw" {
  depends_on          = [azurerm_resource_group.uks_hub]
  for_each            = var.fw.public_ip
  name                = each.value.name
  location            = azurerm_resource_group.uks.location
  resource_group_name = azurerm_resource_group.uks_hub.name
  sku                 = try(each.value.sku, "Standard")
  allocation_method   = try(each.value.allocation_method, "Static")
  ip_version          = try(each.value.ip_version, "IPv4")
  zones               = try(each.value.zones, ["1"])
  domain_name_label   = try(replace(lower(each.value.fqdn), ".", "-"), null)
  lifecycle {
    create_before_destroy = true
  }
}

# FIREWALL OBJECT
resource "azurerm_firewall" "uks" {
  depends_on          = [azurerm_resource_group.uks_hub, azurerm_public_ip.uks_fw, azurerm_firewall_policy.uks_hub]
  name                = var.fw.name
  location            = azurerm_resource_group.uks_hub.location
  resource_group_name = azurerm_resource_group.uks_hub.name
  sku_name            = var.fw.sku.name
  sku_tier            = var.fw.sku.tier
  private_ip_ranges   = null
  management_ip_configuration {
    name                 = azurerm_public_ip.fw_public_int_MGMT.name
    subnet_id            = azurerm_subnet.subnets["AzureFirewallManagementSubnet"].id
    public_ip_address_id = azurerm_public_ip.fw_public_int_MGMT.id
  }
  dynamic "ip_configuration" {
    for_each = azurerm_public_ip.uks_fw
    content {
      name                 = ip_configuration.value.name
      public_ip_address_id = ip_configuration.value.id
      subnet_id = contains(["0", 0], ip_configuration.key) ? azurerm_subnet.subnets["AzureFirewallSubnet"].id : null
    }
  }
  firewall_policy_id = azurerm_firewall_policy.uks_hub.id
}
```

### Debug Output

 # azurerm_public_ip.uks_fw["0"] will be created
  + resource "azurerm_public_ip" "uks_fw" {
      + allocation_method       = "Static"
      + ddos_protection_mode    = "VirtualNetworkInherited"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + idle_timeout_in_minutes = 4
      + ip_address              = (known after apply)
      + ip_version              = "IPv4"
      + location                = "uksouth"
      + name                    = "TESTING-FIREWALL-PIP-02"
      + resource_group_name     = "TESTING"
      + sku                     = "Standard"
      + sku_tier                = "Regional"
      + zones                   = [
          + "1",
        ]
    }
# azurerm_public_ip.uks_fw["1"] will be created
  + resource "azurerm_public_ip" "uks_fw" {
      + allocation_method       = "Static"
      + ddos_protection_mode    = "VirtualNetworkInherited"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + idle_timeout_in_minutes = 4
      + ip_address              = (known after apply)
      + ip_version              = "IPv4"
      + location                = "uksouth"
      + name                    = "TESTING-FIREWALL-PIP-02"
      + resource_group_name     = "TESTING"
      + sku                     = "Standard"
      + sku_tier                = "Regional"
      + zones                   = [
          + "1",
        ]
    }

### Expected Behavior

`terraform plan -target azurerm_public_ip.uks_fw["0"]`
```
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
```
followed by 
```
No changes. Your infrastructure matches the configuration. 
```

### Actual Behavior

`terraform plan`
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:
  # azurerm_public_ip.uks_fw["0"] will be created
  + resource "azurerm_public_ip" "uks_fw" {
      + allocation_method       = "Static"
      + ddos_protection_mode    = "VirtualNetworkInherited"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + idle_timeout_in_minutes = 4
      + ip_address              = (known after apply)
      + ip_version              = "IPv4"
      + location                = "uksouth"
      + name                    = "TESTING-FIREWALL-PIP-01"
      + resource_group_name     = "TESTING"
      + sku                     = "Standard"
      + sku_tier                = "Regional"
      + zones                   = [
          + "1",
        ]
    }

  # azurerm_public_ip.uks_fw["1"] will be created
  + resource "azurerm_public_ip" "uks_fw" {
      + allocation_method       = "Static"
      + ddos_protection_mode    = "VirtualNetworkInherited"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + idle_timeout_in_minutes = 4
      + ip_address              = (known after apply)
      + ip_version              = "IPv4"
      + location                = "uksouth"
      + name                    = "TESTING-FIREWALL-PIP-02"
      + resource_group_name     = "TESTING"
      + sku                     = "Standard"
      + sku_tier                = "Regional"
      + zones                   = [
          + "1",
    }
    
    
    Plan: 2 to add, 0 to change, 0 to destroy.
```

## AFTER CHANGING THE TF_LABEL OF A RESOURCE, CREATED USING A FOR_EACH RESOURCE BLOCK

terraform init
terraform state rm <provider_resource_class>.<tf_label>
terraform import  <provider_resource_class>.<tf_label>
terraform plan -target  <provider_resource_class>.<tf_label>
terraform apply -target  <provider_resource_class>.<tf_label>
## NO CHANGES ARE MADE

terraform plan
### Additional Context

Same for azurerm_public_IP, azurerm_firewall, azurerm_network_security_group and azurerm_subnet.

not tried converting everything over to a COUNT loop; but i suspect it's the same across the board.

Note 'terraform state list | grep azurerm_public_ip` (or `terraform state list | findstr ^azurerm_public_ip` in windows) returns:
```
azurerm_public_ip.uks_fw_mgmt_only
azurerm_public_ip.uks_appgw
azurerm_public_ip.uks_hub_bas_pip
azurerm_public_ip.uks_vnet_gateway_pip_01
azurerm_public_ip.uks_vnet_gateway_pip_02
azurerm_public_ip.uks_vnet_gateway_pip_03
```

Clearly `azurerm_public_ip.uks_fw` is missing from my state file, despite importing  ["0"] and ["1"] just 1-2 lines earlier.

Am i missing a fundimental step?

note my init is using an azure storage account for a state-file with the default-file-name `terraform.tfstate`. I don't see a second file created during import (as you do when you use a different filename during `init`).

**Comment by jbardin** [comment]
Hi @sjackson0109,

If the plan is showing that the given resource will be created, it is because it was not imported correctly.
The individual instances must be imported exactly as
```
terraform import 'azurerm_public_ip.uks_fw["0"]'
```

The quoting is important to make sure the shell does not strip quotes when passing the argument to terraform. You can see the arguments as presented to the CLI in the `TF_LOG_CORE=trace` output to verify your command structure.

You can also follow #32329 and #32146 for existing issues related to importing, which should be resolved when a new importing interface is implemented. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by sjackson0109** [comment]
terraform list | findstr ^azurerm_public_ip.uks_fw
> no results

Importing
```
terraform import azurerm_public_ip.uks_fw["0"] /subscriptions/056a4db0-4f00-48fb-97f1-347aa393f980/resourceGroups/TESTING/providers/Microsoft.Network/publicIPAddresses/TESTING-FIREWALL-PIP-01
terraform import azurerm_public_ip.uks_fw["1"] /subscriptions/056a4db0-4f00-48fb-97f1-347aa393f980/resourceGroups/TESTING/providers/Microsoft.Network/publicIPAddresses/TESTING-FIREWALL-PIP-02
```
output:
```
Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

Checking once:
```
terraform list | findstr ^azurerm_public_ip.uks_fw
> no results
```

checking twice:
```
terraform console
> azurerm_public_ip.uks_fw
(known after apply)
```

**Comment by sjackson0109** [comment]
Amending my import to use the suggested apostrophies....
```
terraform import 'azurerm_public_ip.uks_fw["0"]' /subscriptions/056a4db0-4f00-48fb-97f1-347aa393f980/resourceGroups/TESTING/providers/Microsoft.Network/publicIPAddresses/TESTING-FIREWALL-PIP-01
terraform import 'azurerm_public_ip.uks_fw["1"]' /subscriptions/056a4db0-4f00-48fb-97f1-347aa393f980/resourceGroups/TESTING/providers/Microsoft.Network/publicIPAddresses/TESTING-FIREWALL-PIP-02
```

Checking:
```
terraform list | findstr ^azurerm_public_ip.uks_fw
> no results
```

**Comment by jbardin** [comment]
@sjackson0109, the import commands are not escaping the quotes, and will be passed to Terraform as the incorrect indexes. The log output will show the command as terraform receives it, but the escaping needs to be done according to the formats used by your shell. Seeing the use of `findstr` it looks like you are using windows, which will have different escaping rules.

**Comment by jbardin** [comment]
See also this thread in the forums for more suggestions: https://discuss.hashicorp.com/t/cant-import-resources-with-map-values/42036

**Comment by sjackson0109** [comment]
I am not using incorrect key names (the integer vs string debate you bring..

The PLAN command GIVES me the name of the resources with quotes surrounding the numbers...

- the for-each loop process is converting my var.fw.public_ip object into a map of objects. Which is fine. exept for the fact the key created in the map, is a string.


For example
```
fw = {
  public_ip = {
    0 = {
      name              = "TESTING-FIREWALL-PIP-01"
      allocation_method = "Static"
      sku               = "Standard"
      zones             = ["1","2"]
    }
    1 = {
      name              = "TESTING-FIREWALL-PIP-02"
      allocation_method = "Static"
      sku               = "Standard"
      zones             = ["1","2"]
    }
    PROD= {
       name              = "www-domain-com"
       fqdn              = "www.domain.com"
       sku               = "Standard"
       allocation_method = "Static"
       ip_version        = "IPv4"
       zones             = ["1", "2"]
    }
  }
}
```

I would expect the map

**Comment by jbardin** [comment]
If you show the exact output from the trace log for the `CLI args:` line, we can see what the shell is passing into terraform. If you are formatting the command correctly, then you should see:
```
CLI args: []string{"terraform", "import", "azurerm_public_ip.uks_fw[\"0\"]"}
```

However I suspect what you are going to see is 
```
CLI args: []string{"terraform", "import", "azurerm_public_ip.uks_fw[0]"}
```

Which indicates a different address. The first is a map with a string index of `"0"`, and the second is a list with a numeric index of `0`. If the addresses don't match, then the import is not going to target the correct location in the configuration.

**Comment by sjackson0109** [comment]
@jbardin - I really don't feel you should close/dismiss VALID feedback on what is clearly not just a end-user error.  You've annoyed me a little tbh by simply closing this ticket - prior to any form of technical triage. That is a AWFUL practice.

You statement is re the trace log is valid - i'd not configured the trace log, as this was running in a cloud-devops-container, and logs were never kept.  Now am running locally, i see the traces clearly. Your suspicion is correct. The parameter i entered 'azurerm_public_ip_uks_fw["0"]' has indeed been replaced with "azurerm_public_ip.uks_fw[0]"... so my string has somehow become an integer despite encapsulating it within quotes as an input.
This is surely a BUG  in GO
BUG #1- not converting the 'parameter as a string, and replacing quotes with apostrophies.

Moving further on... Why does `Terraform Import` command conclude with the words 'Import Successful'?
BUG #2 - terraform import of a for-each object, failing to match the correct key-value, returns import-successful.

The overall import experienc gave me a false-sense-of-truth.  Without WASTING a good hour or so of my time, checking and re-checking..  the experience was terrible.


addressing this escape character issue...
Why does the documentation NOT include this specific example (importing into a map of resources)?
Perhaps include both scenarios?
- A count over a map of resources [each.key]
- A for-each over a map of resources [count.index)

Happy to work with the newly suggsted escape [\"0\"] parameter and repeat the exercise in the moring.

**Comment by jbardin** [comment]
Hi @sjackson0109,

I'm sorry you feel that way, that was not the intent here. Feedback is never dismissed, but the issues with escaping in Windows have been discussed before, and is not something which Terraform can directly solve, and we prefer to redirect extended discussion to the community forums and only track active issues in GitHub.

Re: #1. The Go runtime cannot fix this either -- the quotation marks are stripped by the shell before being passed to the process, so the data is simply not there at all. It is ambiguous as to how to reconstruct the original quoting, and as this example shows, the given argument is syntactically valid so there is no way to infer what the original may have been either.

#2 is a legitimate bug, which we are tracking in the first issue I linked (#32329). I agree this can make things confusing, and should be resolved with upcoming import improvements.

The `import` command, and import process as a whole, have quite a few problems which trace back to early versions of Terraform. In order to solve the majority if these issues there will soon be a new mechanism for programmatically importing resources (tracked via #26364).
