### ISSUE TITLE
Storing cross-region artifacts in Atlas with Packer results in incorrect "metadata_full"

### ISSUE THREAD

**Issue by maxenglander** [hashicorp/terraform#3312]
I'm using Packer to store AMIs across multiple AWS regions. When I try to use the `ami_id` of `atlas_artifact.<name>.metadata_full` I run into issues. Here's what my metadata looks like (from Atlas).

> ami_id = ami-3185fa54,us-west-1
> region = us-east-1
> region.us-east-1 = ami-3185fa54
> region.us-west-1 = ami-2d509469

Apologies if I'm mistaken, but I assume that `ami_id` ought to have all of the IDs, not a mismatched mix of ID and region.

**Comment by phinze** [comment]
Thanks for the report, @maxenglander. That definitely looks off. We'll take a look and follow up.

**Comment by justincampbell** [comment]
@maxenglander This has been fixed in Atlas. In your example, the metadata should now look like this (for future artifacts):

```
ami_id = ami-3185fa54,ami-2d509469
region = us-east-1,us-west-1
region.us-east-1 = ami-3185fa54
region.us-west-1 = ami-2d509469
```
