### ISSUE TITLE
Bazel: terraform checksum changed

### ISSUE THREAD

**Issue by loeffel-io** [hashicorp/terraform#33121]
### Terraform Version

```shell
v1.3.7
```

### What is the docs issue?

Why does the checksum of the zip files changed? This breaks all builds

**Comment by jbardin** [comment]
Hi @loeffel-io,

The signing keys for binaries were rotated, which necessitated re-publishing some existing releases. You can find more info here: https://support.hashicorp.com/hc/en-us/articles/13177506317203-Security-Alert-HashiCorp-Response-to-CircleCI
