### ISSUE TITLE
Cannot filter out and reuse resources created by for_each in the same script

### ISSUE THREAD

**Issue by rafalkkk** [hashicorp/terraform#33130]
### Terraform Version

```shell
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.0.0
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "Example_RG"
  location = "East US"
}

resource "azurerm_virtual_network" "example" {
  name                = "Example_VNET"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.1.0.0/16"]
}

# this map defines subnets
variable "subnets" {
  type        = map(any)
  description = "Subnets information"
  default = {
    dev_subnet = {
      address = ["10.1.1.0/24"]
    },
    tst_subnet = {
      address = ["10.1.2.0/24"]
    }
  }
}

# here subnets are created
resource "azurerm_subnet" "example" {
  for_each             = var.subnets
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  name                 = each.key
  address_prefixes     = each.value["address"]
}

# here I want to attach a network interface to a newly created subnet
resource "azurerm_network_interface" "example" {
  name                = "Example_nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = [for x in azurerm_virtual_network.example.subnet.* : x.id if x.name == "dev_subnet"][0]
    private_ip_address_allocation = "Dynamic"
  }
}

```

### Debug Output

terraform apply --auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_network_interface.example will be created
  + resource "azurerm_network_interface" "example" {
      + applied_dns_servers           = (known after apply)
      + dns_servers                   = (known after apply)
      + enable_accelerated_networking = false
      + enable_ip_forwarding          = false
      + id                            = (known after apply)
      + internal_dns_name_label       = (known after apply)
      + internal_domain_name_suffix   = (known after apply)
      + location                      = "eastus"
      + mac_address                   = (known after apply)
      + name                          = "Example_nic"
      + private_ip_address            = (known after apply)
      + private_ip_addresses          = (known after apply)
      + resource_group_name           = "Example_RG"
      + virtual_machine_id            = (known after apply)

      + ip_configuration {
          + gateway_load_balancer_frontend_ip_configuration_id = (known after apply)
          + name                                               = "internal"
          + primary                                            = (known after apply)
          + private_ip_address                                 = (known after apply)
          + private_ip_address_allocation                      = "Dynamic"
          + private_ip_address_version                         = "IPv4"
          + subnet_id                                          = (known after apply)
        }
    }

  # azurerm_resource_group.example will be created
  + resource "azurerm_resource_group" "example" {
      + id       = (known after apply)
      + location = "eastus"
      + name     = "Example_RG"
    }

  # azurerm_subnet.example["dev_subnet"] will be created
  + resource "azurerm_subnet" "example" {
      + address_prefixes                               = [
          + "10.1.1.0/24",
        ]
      + enforce_private_link_endpoint_network_policies = false
      + enforce_private_link_service_network_policies  = false
      + id                                             = (known after apply)
      + name                                           = "dev_subnet"
      + resource_group_name                            = "Example_RG"
      + virtual_network_name                           = "Example_VNET"
    }

  # azurerm_subnet.example["tst_subnet"] will be created
  + resource "azurerm_subnet" "example" {
      + address_prefixes                               = [
          + "10.1.2.0/24",
        ]
      + enforce_private_link_endpoint_network_policies = false
      + enforce_private_link_service_network_policies  = false
      + id                                             = (known after apply)
      + name                                           = "tst_subnet"
      + resource_group_name                            = "Example_RG"
      + virtual_network_name                           = "Example_VNET"
    }

  # azurerm_virtual_network.example will be created
  + resource "azurerm_virtual_network" "example" {
      + address_space       = [
          + "10.1.0.0/16",
        ]
      + dns_servers         = (known after apply)
      + guid                = (known after apply)
      + id                  = (known after apply)
      + location            = "eastus"
      + name                = "Example_VNET"
      + resource_group_name = "Example_RG"
      + subnet              = (known after apply)
    }

Plan: 5 to add, 0 to change, 0 to destroy.
azurerm_resource_group.example: Creating...
azurerm_resource_group.example: Creation complete after 3s [id=/subscriptions/b0f2c2f3-c0ba-4f9b-b2ec-462472fdc456/resourceGroups/Example_RG]
azurerm_virtual_network.example: Creating...
azurerm_virtual_network.example: Creation complete after 6s [id=/subscriptions/b0f2c2f3-c0ba-4f9b-b2ec-462472fdc456/resourceGroups/Example_RG/providers/Microsoft.Network/virtualNetworks/Example_VNET]
azurerm_subnet.example["dev_subnet"]: Creating...
azurerm_subnet.example["tst_subnet"]: Creating...
azurerm_subnet.example["dev_subnet"]: Creation complete after 7s [id=/subscriptions/b0f2c2f3-c0ba-4f9b-b2ec-462472fdc456/resourceGroups/Example_RG/providers/Microsoft.Network/virtualNetworks/Example_VNET/subnets/dev_subnet]
azurerm_subnet.example["tst_subnet"]: Still creating... [10s elapsed]
azurerm_subnet.example["tst_subnet"]: Creation complete after 12s [id=/subscriptions/b0f2c2f3-c0ba-4f9b-b2ec-462472fdc456/resourceGroups/Example_RG/providers/Microsoft.Network/virtualNetworks/Example_VNET/subnets/tst_subnet]
╷
│ Error: Invalid index
│
│   on main.tf line 57, in resource "azurerm_network_interface" "example":
│   57:     subnet_id                     = [for x in azurerm_virtual_network.example.subnet.* : x.id if x.name == "dev_subnet"][0]
│     ├────────────────
│     │ azurerm_virtual_network.example.subnet is empty set of object
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵

### Expected Behavior

After creation of the subnets, they should be available for later use in the script. The following instuction should be able to "see" the new subnet:

subnet_id = [for x in azurerm_virtual_network.example.subnet.* : x.id if x.name == "dev_subnet"][0]

### Actual Behavior

The command creating subnets suceedes, so the subnets exist (I have checked it on portal and the virtual network indeed has the subnets). The command creating the network interface should take the newly created subnets form the azurerm_virtual_network object and filter out the id of the dev_subnet. 

Because after creation of the virtual network the state is not refreshed anymore, the command fails complaining the the subnets property is empty (which in not true on azure).

### Steps to Reproduce

terraform init
terraform apply --auto-approve

### Additional Context

windows 11

**Comment by jbardin** [comment]
Hi @rafalkkk,

The expression `azurerm_virtual_network.example.subnet.*` is not valid in this configuration, and I suspect whatever it is you actually have is not doing what you expect. This expression will result in an error like `Missing resource instance key`, because `azurerm_virtual_network.example` is using `for_each`, so you must use an index. 

I suspect you wanted something more like:

```
`[for x in azurerm_virtual_network.example : x.subnet.id if x.subnet.name == "dev_subnet"][0]`
```

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by jbardin** [comment]
Thanks @rafalkkk,

I think I see what you are trying to do here, there was only one "apply" action, and the unusual splat expression kind of threw me off.

You are trying to reference the `subnet` block of `azurerm_virtual_network`, while creating the subnets externally. Because the `azurerm_virtual_network` is created before the individual subnets, there would be no way for the `azurerm_virtual_network` to know about those subnets during apply, which is why there are no values when you try to iterate over the set. In fact, if I look at the [azurerm documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network), there is a callout noting that you cannot mix the use of the inline subnets with the individual resources. The fact that they show up at all in the network resource is a quirk of the provider's implementation.

If you want more information, there are going to be more users familiar with this particular provider under [their community forum topic here](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

Thanks!
