### ISSUE TITLE
The terraform:light docker image is still on 1.4.2

### ISSUE THREAD

**Issue by francescomucio** [hashicorp/terraform#33139]
### Terraform Version

```shell
Using terraform:light in my cicd pipeline. It's dowloading version 1.4.2.


$ terraform --version
Terraform v1.4.2
on linux_amd64
Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

No file needed

### Debug Output

```bash
$ terraform --version
Terraform v1.4.2
on linux_amd64
Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Expected Behavior

I would expect to have version 1.4.6

### Actual Behavior

Instead I get 1.4.2 with a warning message

### Steps to Reproduce

Just try to use `hashicorp/terraform:light` docker image

**Comment by apparentlymart** [comment]
Hi @francescomucio! Thanks for reporting this.

The "light" tag is a legacy thing which we've been continuing to update for a few years now but we've had to finally end support for it as part of switching to a new release pipeline that does not allow us to publish extra tags into docker hub.

Use "latest" to get the effect of always using the latest version of Terraform. "light" will be preserved as-is for the foreseeable future to avoid breaking existing pipelines altogether, but it will be frozen on its current release.

**Comment by francescomucio** [comment]
Hi Martin, thanks for the update. I was not aware. I will update my cicd
pipelines

**Comment by crw** [comment]
As the issue seems to have been answered satisfactorily, I will close. Thanks!
