### ISSUE TITLE
Impossible to debug Terraform errors

### ISSUE THREAD

**Issue by arLevi** [hashicorp/terraform#33146]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/aliyun/alicloud v1.204.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
```

### Use Cases

Trying to create a complex topology, problematic to insert the code here
but, i'll attached the error to make my point - it's impossible to debug w/o values.

```
│ Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_cen_transit_router_vpc_attachment.go:201: Resource alicloud_cen_transit_router_vpc_attachment CreateTransitRouterVpcAttachment Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
│ SDKError:
│    StatusCode: 400
│    Code: IllegalParam.VSwitchId
│    Message: code: 400, VSwitchId is illegal. request id: 3B3DF284-FF73-5BA6-9A70-4DD98CA10463
│    Data: {"Code":"IllegalParam.VSwitchId","HostId":"cbn-openapi-oxs-share.aliyuncs.com","Message":"VSwitchId is illegal.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=IllegalParam.VSwitchId\u0026product=Cbn","RequestId":"3B3DF284-FF73-5BA6-9A70-4DD98CA10463"}
│
│
│   with module.cen_transit_router.alicloud_cen_transit_router_vpc_attachment.created,
│   on ./cen_transit_router/main.tf line 60, in resource "alicloud_cen_transit_router_vpc_attachment" "created":
│   60: resource "alicloud_cen_transit_router_vpc_attachment" "created" {
```

Error is: `Code: IllegalParam.VSwitchId`
Docs says: `The virtual switch is ilegal` (not a surprise)

The above run inside a loop, so I'm trying to understand a very simple thing:
- What is the value inserted inside `VSwitchId` that makes it `illegal`?
- Which region it's using ? ( sometimes it cannot find if the ID is correct but you're on the wrong region )

### Attempted Solutions

I tried running everything i could:
Starting from this
```
$ terraform console -json
```
which doesn't give anything 
( while tfstate has many values and my outputs.tf is correct to fill data when everything is working )

Also tried:
```
export TF_LOG_PROVIDER=TRACE
export TF_LOG_CORE=TRACE
export TF_LOG_PATH=logs.txt
```

Which shows tons of the data - but nothing helpful to understand the issue and doesn't include ANY id values ( even for resources who did pass successfully )

### Proposal

The `TRACE` of either `TF_LOG_CORE` / `TF_LOG_PROVIDER` should include ALL details/ids/region/ everything that you can - so we can understand the issue.

**Comment by arLevi** [comment]
Thanks @crw for the detailed response, I appreciate it.
I agree about:
```
there is an explicit policy not to include configuration values in the trace logs, because other users have the requirement that the logs not include customer-specific values like that so that they can safely store and transmit the logs to third-party systems
```

This is why I suggested the `TRACE` level env variable, this is for debugging purposes, not production.
The issue many times, is to debug things until we get the right configuration that we need - this is where we are stuck.

I'll try to also open an issue at the provider's GitHub as you suggested.
Thanks again.

**Comment by crw** [comment]
Thanks for the issue report, and thanks for reporting this to the provider's repository. I am going to close this issue as there are no further actions for the core team.
