### ISSUE TITLE
RHN persists after user moves to new doc

### ISSUE THREAD

**Issue by skearney-akamai** [hashicorp/terraform#33156]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_arm64
```

### Affected Pages

* https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/resources
* https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/data-sources

### What is the docs issue?

If a user moves from our main landing page or the guide to data sources or resources, the right-hand nav from the previous page persists. A refresh removes it. 

Steps to reproduce:

1. Navigate to our [main landing](https://registry.terraform.io/providers/akamai/akamai/latest/docs). Take note of the right-hand navigation.
2. Click into our [guide page](https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/get-started). Look again at the right-hand nav, it's changed to the current page's content as expected.
3. Click into the [resource](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/resources). Notice the guide's right-hand nav persists.
4. Refresh your page. The right-hand navigation is now gone. 
5. Click into the [data source](https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/data-sources). Notice there is no right-hand navigation as expected.

If you repeated the set of steps and went into the data source at step 3, you get the same results. If you skipped step 2 and went straight from 1 to 3, you get the same results.

Behavior present in these browsers:

* Chrome version 112.0.5615.137
* Safari version 16.4 (18615.1.26.110.1)
* Firefox 112.0.2 (64-bit)

### Proposal

Ensure moving from a page with right-hand navigation to one without produces a page without right-hand navigation without a refresh.

**Comment by crw** [comment]
Thanks for this request. The Registry team does not look at issues in this repository, nor does the core team work on the Registry. That said, I will pass this comment along to the Registry team. Thanks again!

**Comment by opslivia** [comment]
The Registry will be making large changes in the coming months. As such, we will not be addressing this issue now.
