### ISSUE TITLE
Cannot Specify Target VPC when creating RDS Instance 

### ISSUE THREAD

**Issue by rickalm** [hashicorp/terraform#3315]
According to docs https://www.terraform.io/docs/providers/aws/r/db_instance.html there is no way to specify vpc for instance to be created in. 

tried vpc and vpc_id with no success

**Comment by stack72** [comment]
@rickalm I think the db_subnet_group and vpc_security_group_ids determine what VPC the db instance goes into

**Comment by rickalm** [comment]
@stack72 Thanks, Great catch. I had created my subnet group but forgot to specify the subnet group in the instance creation ..
