### ISSUE TITLE
Ability to override a local value in a source module

### ISSUE THREAD

**Issue by azafar212** [hashicorp/terraform#33169]
### Terraform Version

```shell
terraform version
Terraform v1.4.6
on darwin_amd64
```

### Use Cases

Ability to override a locals value in a source module.

### Attempted Solutions

created file `override.tf` but when trying to override the value in a source module it errors 

`override.tf` contents
```
module "karpenter" {
  locals {
    partition = "aws-us-gov"
  }
}
```

terraform plan output with error

```
│ Error: Reserved block type name in module block
│
│   on override.tf line 2, in module "karpenter":
│    2:   locals {
│
│ The block type name "locals" is reserved for use by Terraform in a future
│ version.
```

**Comment by apparentlymart** [comment]
Hi @azafar212,

The typical way to pass data into a child module is using input variables:

```hcl
module "karpenter" {
  source = "..."

  partition = "aws-us-gov"
}
```

The purpose of local values is to allow a module to define its own private set of named values. Therefore it doesn't really make sense to allow reading or writing them from outside of the module.

However, I would like to understand more about what you're ultimately trying to achieve, ignoring the specific design of overriding local values. For example, if you can explain why input variables are not an appropriate solution to the problem you've encountered then that might help to understand what is missing from Terraform and then we can consider other potential designs (other than overriding local values) that would meet your need.

Thanks!

**Comment by crw** [comment]
Howdy! I am cleaning up old `waiting-response` issues. As this issue has not had an update in some time, I am going to close it. Please let us know that if there is an outstanding request by responding to the questions raised in the previous comment. Thanks!
