### ISSUE TITLE
Terraform Import for RDS is not working

### ISSUE THREAD

**Issue by pslath** [hashicorp/terraform#33197]
### Terraform Version

```shell
Terraform V1.3.5
provider registry.terraform.io/hashicorp/archive v2.2.0
provider registry.terraform.io/hashicorp/aws v4.30.0
provider registry.terraform.io/hashicorp/random v3.4.3
provider registry.terraform.io/hashicorp/template v2.2.0
provider registry.terraform.io/hashicorp/vault v3.11.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```
$ terraform import module.domain.aws_db_instance.db <db_instance-identifier>

### Debug Output

debug output

### Expected Behavior

Terraform should have imported the RDS

### Actual Behavior

Import says successful!

State file doesnt show resource nor the terraform state list shows the imported module.

### Steps to Reproduce

terraform plan
terraform apply

Error in Apply

Error Creating RDS DB Instance (db instance name) DBInstanceAlreadyExists: DB Instance already exists

### References

no

**Comment by crw** [comment]
Hello @pslath, this appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues.

I am not positive that this is not a problem in core import functionality, however, so I will leave this open for a maintainer to confirm the source of this issue. Thanks for your submission!

**Comment by jbardin** [comment]
Hi @pslath,

It's not clear here what actually went wrong during the import process, but it could be that import is not implemented correctly by the provider. Can you show the actual config and exact output from the import and plan process?

Thanks!

**Comment by JimmyIL** [comment]
I think this has to do with how it's being imported since your importing it into a module and not a singular resource path.  I would do a 'terraform state list' and see if you can find it because it may wind up indexed as well.  Alternatively,  a work around would be to import it as a generic singular resource (example: terraform import aws_db_instance.domain_db <db_instance-identifier> ) and then after just do <terraform mv aws_db_instance.domain_db module.domain.aws_db_instance.db >

**Comment by jbardin** [comment]
Since we have not heard back with any information I'm going to close this out. If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
