### ISSUE TITLE
Error: Provider produced inconsistent final plan GCP - API Gateway 

### ISSUE THREAD

**Issue by periwinkleFTW** [hashicorp/terraform#33209]
### Terraform Version

```shell
Terraform v1.4.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/google v4.59.0
+ provider registry.terraform.io/hashicorp/google-beta v4.59.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.9.1

Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for google_api_gateway_api_config.api_cfg to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google-beta" produced an invalid new value
│ for .openapi_documents[0].document[0].contents: was
│ cty.StringVal("b3BlbmFwaTogMy4wLjAKaW5mbzoKICB0aXRsZTogQVBJX0lEIG9wdGlvbmFsLXN0cmluZwogIGRlc2NyaXB0aW9uOiBTYW1wbGUgQVBJIG9uIEFQSSBHYXRld2F5IHdpdGggYSBHb29nbGUgQ2xvdWQgRnVuY3Rpb25zIGJhY2tlbmQKICB2ZXJzaW9uOiAxLjAuMApzZXJ2ZXJzOgogIC0gdXJsOiBodHRwczovL2V4YW1wbGUuY29tCnBhdGhzOgogIC9oaWdoVm9sdW1lTVg6CiAgICBnZXQ6CiAgICAgIHN1bW1hcnk6IGhpZ2hWb2x1bWVNWAogICAgICBvcGVyYXRpb25JZDogaGlnaFZvbHVtZU1YCiAgICAgIHgtZ29vZ2xlLWJhY2tlbmQ6CiAgICAgICAgYWRkcmVzczogaHR0cHM6Ly91cy1jZW50cmFsMS0ke0NMT1VEX0ZVTkNUSU9OX1VSTF9ERVZ9LmNsb3VkZnVuY3Rpb25zLm5ldC9nZXQtaGlnaC12b2x1bWUtbXgtZGV2ZWxvcAogICAgICByZXNwb25zZXM6CiAgICAgICAgJzIwMCc6CiAgICAgICAgICBkZXNjcmlwdGlvbjogQSBzdWNjZXNzZnVsIHJlc3BvbnNlCiAgICAgICAgICBjb250ZW50OgogICAgICAgICAgICBhcHBsaWNhdGlvbi9qc29uOgogICAgICAgICAgICAgIHNjaGVtYToKICAgICAgICAgICAgICAgIHR5cGU6IHN0cmluZwogIC9oaWdoVm9sdW1lVVM6CiAgICBnZXQ6CiAgICAgIHN1bW1hcnk6IGhpZ2hWb2x1bWVVUwogICAgICBvcGVyYXRpb25JZDogaGlnaFZvbHVtZVVTCiAgICAgIHgtZ29vZ2xlLWJhY2tlbmQ6CiAgICAgICAgYWRkcmVzczogaHR0cHM6Ly91cy1jZW50cmFsMS0ke0NMT1VEX0ZVTkNUSU9OX1VSTF9ERVZ9LmNsb3VkZnVuY3Rpb25zLm5ldC9nZXQtaGlnaC12b2x1bWUtdXMtZGV2ZWxvcAogICAgICByZXNwb25zZXM6CiAgICAgICAgJzIwMCc6CiAgICAgICAgICBkZXNjcmlwdGlvbjogQSBzdWNjZXNzZnVsIHJlc3BvbnNlCiAgICAgICAgICBjb250ZW50OgogICAgICAgICAgICBhcHBsaWNhdGlvbi9qc29uOgogICAgICAgICAgICAgIHNjaGVtYToKICAgICAgICAgICAgICAgIHR5cGU6IHN0cmluZw=="),
│ but now
│ cty.StringVal("b3BlbmFwaTogMy4wLjAKaW5mbzoKICB0aXRsZTogQVBJX0lEIG9wdGlvbmFsLXN0cmluZwogIGRlc2NyaXB0aW9uOiBTYW1wbGUgQVBJIG9uIEFQSSBHYXRld2F5IHdpdGggYSBHb29nbGUgQ2xvdWQgRnVuY3Rpb25zIGJhY2tlbmQKICB2ZXJzaW9uOiAxLjAuMApzZXJ2ZXJzOgogIC0gdXJsOiBodHRwczovL2V4YW1wbGUuY29tCnBhdGhzOgogIC9oaWdoVm9sdW1lTVg6CiAgICBnZXQ6CiAgICAgIHN1bW1hcnk6IGhpZ2hWb2x1bWVNWAogICAgICBvcGVyYXRpb25JZDogaGlnaFZvbHVtZU1YCiAgICAgIHgtZ29vZ2xlLWJhY2tlbmQ6CiAgICAgICAgYWRkcmVzczogaHR0cHM6Ly91cy1jZW50cmFsMS10cmV2b3ItcHJvamVjdC1kZXYuY2xvdWRmdW5jdGlvbnMubmV0L2dldC1oaWdoLXZvbHVtZS1teC1kZXZlbG9wCiAgICAgIHJlc3BvbnNlczoKICAgICAgICAnMjAwJzoKICAgICAgICAgIGRlc2NyaXB0aW9uOiBBIHN1Y2Nlc3NmdWwgcmVzcG9uc2UKICAgICAgICAgIGNvbnRlbnQ6CiAgICAgICAgICAgIGFwcGxpY2F0aW9uL2pzb[24](https://github.com/trevorproject/health-check-backend/actions/runs/4768151429/jobs/8477146071#step:16:25)6CiAgICAgICAgICAgICAgc2NoZW1hOgogICAgICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgL2hpZ2hWb2x1bWVVUzoKICAgIGdldDoKICAgICAgc3VtbWFyeTogaGlnaFZvbHVtZVVTCiAgICAgIG9wZXJhdGlvbklkOiBoaWdoVm9sdW1lVVMKICAgICAgeC1nb29nbGUtYmFja2VuZDoKICAgICAgICBhZGRyZXNzOiBodHRwczovL3VzLWNlbnRyYWwxLXRyZXZvci1wcm9qZWN0LWRldi5jbG91ZGZ1bmN0aW9ucy5uZXQvZ2V0LWhpZ2gtdm9sdW1lLXVzLWRldmVsb3AKICAgICAgcmVzcG9uc2VzOgogICAgICAgICcyMDAnOgogICAgICAgICAgZGVzY3JpcHRpb246IEEgc3VjY2Vzc2Z1bCByZXNwb[25](https://github.com/trevorproject/health-check-backend/actions/runs/4768151429/jobs/8477146071#step:16:26)zZQogICAgICAgICAgY[29](https://github.com/trevorproject/health-check-backend/actions/runs/4768151429/jobs/8477146071#step:16:30)udGVudDoKICAgICAgICAgICAgYXBwbGljYXRpb24vanNvbjoKICAgICAgICAgICAgICBzY2hlbWE6CiAgICAgICAgICAgICAgICB0eXBlOiBzdHJpbmc=").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

### Expected Behavior

API gateway config should deploy

### Actual Behavior

API gateway config errors out on first apply, goes through on second apply

### Steps to Reproduce

From what I understand this bug happens because terraform checks/evaluates api config yaml file at run time. This error happens if config file is changed between plan and actual apply (which is my case). 

### Additional Context

I have had this bug for a while because my configuration generates api config file dynamically using urls from cloudrun and cloudfunctions. It disappears on second apply because yaml file does not change and apply goes through.

### References

- #33070

**Comment by jbardin** [comment]
Hi @periwinkleFTW,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
