### ISSUE TITLE
Retried failed Terraform destroy retry triggers validation that was not in place for the first destroy

### ISSUE THREAD

**Issue by arbitertl** [hashicorp/terraform#33218]
### Terraform Version

```shell
v1.4.6
```

### Terraform Configuration Files

https://github.com/arbitertl/terraform_destroy_issue/blob/master/main.tf

### Debug Output

https://gist.github.com/arbitertl/ce4bb89eefa8eae7208607afb3b1c5fc

### Expected Behavior

Destruction proceeds without validation, same as for the first time

### Actual Behavior

Second destroy fails with validation which was not triggered on the first destroy

### Steps to Reproduce

1. terraform init
2. terraform destroy

### Additional Context

First destroy failed to destroy one resource (module.ali_vpc.alicloud_vpc.vpc) due to Alibaba Cloud specific issues (which are happening frequently). This is second execution of destroy, after failure. First destroy is not triggering this validation.

**Comment by arbitertl** [comment]
If that helps, issue with destroy was first detected on 1.3.0. It worked fine with any 1.2.x

**Comment by jbardin** [comment]
Thanks @arbitertl,

It looks like some of the internal handling of outputs for dealing with condition checks is interfering with how these were skipped during a partial destroy like you have here. Having the root output always be expanded by #31395 for consistency means it lost some of it's "special case"-ness which allowed it to be skipped when re-running a partial destroy. We restored some of that behavior later, but this case where an output references another temporary value appears to keep them both around for evaluation.

**Comment by arbitertl** [comment]
Is there any chance to get this fix before 1.5 release?

**Comment by crw** [comment]
@arbitertl At this point in the cycle, there will not be another release of 1.4. 1.5 beta / release candidates will continue to be released up to general availability.
