### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by martinhitachi** [hashicorp/terraform#33223]
### Terraform Version

```shell
Documentation v1.4.x and earlier
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/expressions/function-calls#available-functions

### What is the docs issue?

The page says: "For a full list of available functions, see [the function reference](https://developer.hashicorp.com/terraform/language/functions)." but it just links to the overview page for functions rather than a function reference.

### Proposal

Add a function reference page and update the link.

### References

https://github.com/hashicorp/terraform/issues/32119

**Comment by martinhitachi** [comment]
You could probably use "terraform metadata functions -json" mentioned here: https://github.com/hashicorp/terraform/issues/32682

To get all the function descriptions. (I've attached a file with the json output)
[terraform_functions.txt](https://github.com/hashicorp/terraform/files/11518523/terraform_functions.txt)

**Comment by jbardin** [comment]
Hi @martinhitachi,

Thanks for the heads up. That link is to the correct functions overview page, it however does not duplicate the directory of links to the individual sections like some of the other categories (expressions for example). If you are looking for the more specific function docs, the individual pages are listed in the sidebar.

**Comment by martinhitachi** [comment]
@jbardin 
Ah ok. I'm used to oracle docs where it's all one big page: https://docs.oracle.com/javase/8/docs/api/java/lang/String.html
thanks for mentioning the sidebar, it suits my needs.
