### ISSUE TITLE
cwd when using file() builtin in a module is set incorrectly

### ISSUE THREAD

**Issue by garrettheel** [hashicorp/terraform#3322]
When using the `file()` builtin from https://www.terraform.io/docs/configuration/interpolation.html within a module, I'd expect to write paths relative the root of the module, not the root of where I'm running terraform from.

For example, in the following file tree:

```
├── module
│   ├── resources.tf
│   ├── file.txt
```

I'd have to write `${file("module/file.txt")}` from within `resources.tf`. It would be better if I could write `${file("file.txt")}`

**Comment by apparentlymart** [comment]
The ``module.path`` interpolation is intended to address this, but I agree with you that using the module directory as the base for resolution would be a lot more intuitive.

**Comment by phinze** [comment]
Seconding the `path.module` recommendation. The "correct" way to do this today so the module remains portable is: `"${file("${path.module}/file.txt")}"`. But also agreed that the CWD being set would be nicest. Tagged as an enhancement.

**Comment by mitchellh** [comment]
I think we actually need to make clear that paths without using a path variable `${path.X}` are purposely non-specified. We request that everyone using paths always use a path variable explicitly so there is no assumption about cwd!
