### ISSUE TITLE
no schema available for module.Traffic_Manager.azurerm_traffic_manager_endpoint.AppTrafficeManagerEndpoint

### ISSUE THREAD

**Issue by NallamuthuK150691** [hashicorp/terraform#33240]
### Terraform Version

```shell
Terraform v1.3.5
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Error: no schema available for module.Traffic_Manager.azurerm_traffic_manager_endpoint.AppTrafficeManagerEndpoint while reading state; this is a bug in Terraform and should be reported

### Expected Behavior

Need to update my existing azurerm_traffic_manager_endpoint

### Actual Behavior

Error: no schema available for module.Traffic_Manager.azurerm_traffic_manager_endpoint.AppTrafficeManagerEndpoint while reading state; this is a bug in Terraform and should be reported

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Hi @NallamuthuK150691,

Thanks for filing the issue, but without any configuration or steps to reproduce the issue there's not much we can do here. Have you verified this is still a problem with a current Terraform release?

**Comment by jbardin** [comment]
Hello,

Since we have not heard back, and this appears to be a question or an issue with a provider, not with Terraform itself, I'm going to close the issue. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by NallamuthuK150691** [comment]
@jbardin Thanks for your replies. 

AIM : Our Aim is to upgrade the provider azurerm version to 3.54.0.

Actually the issue with Provider Version release. I have created a new issue request #33275.

We are having the existing infra which is provisioned using azurerm provider version 2.74.0.

We are Trying to Upgrade Terraform Provider AzureRM Version to 3.54.0. While we are trying to upgrade the same is throws error like as follows.

Error: no schema available for module.Traffic_Manager.azurerm_traffic_manager_endpoint.AppTrafficeManagerEndpoint while reading state; this is a bug in Terraform and should be reported.

Existing Infra Config file by versio 2.74.0

Existing Terraform Provider AzureRM Version 2.74.0 and Config file as follows,

resource "azurerm_traffic_manager_profile" "AppTrafficeManagerProfile" {
name = var.apptrafficmanagerprofile
resource_group_name = var.resource_group_name
traffic_routing_method = "Priority"

dns_config {
relative_name = "${var.apptrafficmanagerprofile}-dnsconfig"
ttl = 100
}

monitor_config {
protocol = "TCP"
port = 80
path = ""
interval_in_seconds = 30
timeout_in_seconds = 10
tolerated_number_of_failures = 3
}

}
