### ISSUE TITLE
Decouple the main.tf

### ISSUE THREAD

**Issue by Ucmmm** [hashicorp/terraform#33258]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_amd64
```

### Use Cases

Hi, I was wondering if there is a way to decouple the config file `main.tf`? I have a pretty long configurations so I was looking for a way to split them into different parts (or maybe files) for better maintenance. But I couldn't find any documentation about this.

### Attempted Solutions

Different configurations in different files maybe?

**Comment by Ucmmm** [comment]
Also, if there is a way to add a for loop to `main.tf`, like I have 1000 lambda functions, and name them as `name-0` - `name-999`. I'm filling the name manually 1 by 1 in the configurations, if there is a better way to fill their names with for loop?

**Comment by crw** [comment]
Hello @Ucmmm, this sounds like a perfect question for [the community forum](https://discuss.hashicorp.com/c/terraform-core/27)! There should be people there ready to help out. 

GitHub issues are monitored only by a few core maintainers. Thanks!
