### ISSUE TITLE
Upload Buffer Operation Failure

### ISSUE THREAD

**Issue by atb123** [hashicorp/terraform#33269]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.63.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```resource "aws_storagegateway_gateway" "s3_gateway" {
  gateway_name         = "s3-gateway"
  gateway_timezone     = "GMT"
  gateway_type         = "FILE_S3"
  smb_guest_password   = local.secrets.smb_password
  gateway_ip_address   = aws_instance.storage_gateway.public_ip
  gateway_vpc_endpoint = lookup(aws_vpc_endpoint.vpc_endpoint_storagegateway.dns_entry[0], "dns_name")
  depends_on           = [aws_vpc_endpoint.vpc_endpoint_storagegateway, aws_instance.storage_gateway]

}

resource "aws_storagegateway_smb_file_share" "smb_gateway" {
  authentication        = "GuestAccess"
  gateway_arn           = aws_storagegateway_gateway.s3_gateway.arn
  location_arn          = aws_s3_bucket.data_bucket.arn
  role_arn              = aws_iam_role.gateway_role.arn
}

data "aws_storagegateway_local_disk" "storage_gateway_local_disk" {
  disk_node   = aws_volume_attachment.ebs_attach.device_name
  gateway_arn = aws_storagegateway_gateway.s3_gateway.arn
}

resource "aws_storagegateway_cache" "storage_gateway_cache" {
  disk_id     = data.aws_storagegateway_local_disk.storage_gateway_local_disk.id
  gateway_arn = aws_storagegateway_gateway.s3_gateway.arn
}

resource "aws_storagegateway_upload_buffer" "storage_gateway_buffer" {
  disk_path   = data.aws_storagegateway_local_disk.storage_gateway_local_disk.disk_path
  gateway_arn = aws_storagegateway_gateway.s3_gateway.arn
}
```

Trimmed a few items for space

### Debug Output

Error: adding Storage Gateway upload buffer: InvalidGatewayRequestException: The specified operation is not supported.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "6bf6ff53-a451-499e-b5bc-cfea42ad7bf8"
│   },
│   Error_: {
│     ErrorCode: "NotSupported"
│   },
│   Message_: "The specified operation is not supported."
│ }
│ 
│   with aws_storagegateway_upload_buffer.storage_gateway_buffer,
│   on storage_gateway.tf line 140, in resource "aws_storagegateway_upload_buffer" "storage_gateway_buffer":
│  140: resource "aws_storagegateway_upload_buffer" "storage_gateway_buffer" {
│ 

### Expected Behavior

Expecting TF to not error out as the gateway actually works. Taking out the buffer removes the TF failure, but files added into SMB share will not get pushed to S3 bucket.

### Actual Behavior

The storage gateway actually gets built and works, but TF errors out on apply

### Steps to Reproduce

1. terraform apply

Not doing anything special, just trying to apply my TF code...

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
