### ISSUE TITLE
Terraform recreate the same resource with different state file

### ISSUE THREAD

**Issue by Mysilver-cloud** [hashicorp/terraform#33262]
### Terraform Version

```shell
v1.4.6
```

### Terraform Configuration Files

resource "aws_budgets_budget" "example" {
  budget_type = "COST"

  limit_amount = 100
  limit_unit   = "USD"
  time_unit    = "MONTHLY"
  name         = "example"
}

resource "aws_sns_topic" "example" {
  name = "mybudgetnotification"
}

resource "aws_sns_topic_subscription" "example" {
  count     = length(local.emails)
  topic_arn = aws_sns_topic.example.arn
  protocol  = "email"
  endpoint  = local.emails[count.index]

}

data "aws_iam_policy_document" "example" {
  policy_id = "__default_policy_ID"

  statement {
    actions = [
      "SNS:Publish"
    ]

    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["budgets.amazonaws.com"]
    }

    resources = [
      aws_sns_topic.example.arn,
    ]

    sid = "AWSBudgets-notification-1"
  }
}

resource "aws_sns_topic_policy" "example" {
  arn = aws_sns_topic.example.arn

  policy = data.aws_iam_policy_document.example.json
}

### Debug Output

none

### Expected Behavior

Hi. I have an Account factory for Terraform on AWS codepipeline. This pipeline created resources from configuration file above (a budget and sns topic). 

then I signed in to my sso locally on my pc. For testing purpose I ran terraform init, and then terraform plan + apply to create those same resources that been created by the pipeline on AWS. Now what I expect is Terraform should not be able to create those same resources, since they already existed and don't share the same state

### Actual Behavior

What happened is Terraform still created the SNS topic and it's policy. But was not able to create the AWS budget (obviously). What just happened here. Please enlighten me. Thank you in advance!

### Steps to Reproduce

1.  terraform init
2.  terraform plan
3.  terraform apply

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
