### ISSUE TITLE
Error creating databricks token

### ISSUE THREAD

**Issue by juanramon-fernandez** [hashicorp/terraform#33261]
### Terraform Version

```shell
Terraform v1.4.6
on linux_amd64
```

### Terraform Configuration Files

```terraform
resource "azurerm_databricks_workspace" "databricks_ws_eos" {
  name                        = format("example%s", var.environment)
  resource_group_name         = azurerm_resource_group.rg.name
  location                    = azurerm_resource_group.rg.location
  sku                         = "standard"
  managed_resource_group_name = format("databricks-%s",var.environment)
  custom_parameters {
    virtual_network_id  = data.azurerm_virtual_network.vnet.id
    public_subnet_name  = data.azurerm_subnet.subnets_databricks["PUBLICO"].name
    private_subnet_name = data.azurerm_subnet.subnets_databricks["PRIVADO"].name
    public_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.nsg_ass_public.id
    private_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.nsg_ass_private.id
  }
}
```

### Debug Output

databricks_cluster.shared_autoscaling: Creating...
╷
│ Error: cannot create cluster: Post "[https://https:/api/2.0/clusters/create"](https://https/api/2.0/clusters/create%22): dial tcp: lookup https on 127.0.0.53:53: server misbehaving
│ 
│   with databricks_cluster.shared_autoscaling,
│   on main.tf line 481, in resource "databricks_cluster" "shared_autoscaling":
│  481: resource "databricks_cluster" "shared_autoscaling" {

### Expected Behavior

databricks_cluster.shared_autoscaling created

### Actual Behavior
Error only happens in the apply part.
Error: cannot create cluster: Post "[https://https:/api/2.0/clusters/create"](https://https/api/2.0/clusters/create%22): dial tcp: lookup https on 127.0.0.53:53: server misbehaving

### Steps to Reproduce

1. terraform init result OK
2. terraform plan result OK
3. terraform apply result KO

### Additional Context

I'm executing the terraform apply using an Azure Agent in a Azure VM and when it tries to create the databricks workspace gives the error.
It's like if it were duplicating the https:// part of the url.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
