### ISSUE TITLE
health_check_grace_period is NOT optional for ElasticLoadBalancer based health checks

### ISSUE THREAD

**Issue by jasonkuhrt** [hashicorp/terraform#3327]
This error should be caught at the plan stage in the future.

```
aws_autoscaling_group.service:
Error creating Autoscaling Group:
ValidationError:
HealthCheckGracePeriod must be specified for ElasticLoadBalancer based health checks.
	status code: 400, request id: REDACTED
```

So https://terraform.io/docs/providers/aws/r/autoscaling_group.html#health_check_grace_period is ***NOT*** optional if https://terraform.io/docs/providers/aws/r/autoscaling_group.html#health_check_type is `"ELB"`.

**Comment by stack72** [comment]
@jasonkuhrt I have just opened a PR to address this issue - hopefully this will help

<img width="527" alt="screen shot 2015-09-28 at 10 49 29" src="https://cloud.githubusercontent.com/assets/227823/10132513/aa5d0578-65ce-11e5-8c0e-153c6066c361.png">
