### ISSUE TITLE
aws_emr_cluster failed to start. bootstrap action 3 failed with non-zero exit code

### ISSUE THREAD

**Issue by shqlz01** [hashicorp/terraform#33283]
### Terraform Version

```shell
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
```

### Terraform Configuration Files

resource "aws_emr_cluster" "cluster-dev" {
    name                                = var.emr-name
    release_label                       = var.emr-release-label
    applications                        = var.emr-applications
    service_role                        = data.aws_iam_role.emr-role.arn
    autoscaling_role                    = data.aws_iam_role.emr-autoscal-role.arn
    log_uri                             = var.emr-log-uri 
    termination_protection              = false
    scale_down_behavior                 = "TERMINATE_AT_TASK_COMPLETION"
    keep_job_flow_alive_when_no_steps   = true

    ec2_attributes {
        subnet_id                           = data.aws_subnet.emr-subnet.id
        emr_managed_master_security_group   = data.aws_security_group.emr-mn-sg.id
        emr_managed_slave_security_group    = data.aws_security_group.emr-cn-sg.id
        service_access_security_group       = data.aws_security_group.emr-access-sg.id
        instance_profile                    = data.aws_iam_instance_profile.emr-instance-profile.arn
        key_name                            = var.ssh-key
    }

    master_instance_group {
        instance_type = var.emr-m-instance-type
        ebs_config {
            size                    = var.emr-ebs-size
            type                    = var.emr-ebs-type
            volumes_per_instance    = 1
        }
        ebs_config {
            size                    = var.emr-m-ebs-size
            type                    = var.emr-ebs-type
            volumes_per_instance    = 1
        }
    }

    core_instance_group {
        instance_count  = var.core-count
        instance_type   = var.emr-instance-type
        ebs_config {
            size                    = var.emr-ebs-size
            type                    = var.emr-ebs-type
            volumes_per_instance    = 1
        }
    }

    configurations_json = file("dev-conf.json")

    step {
        name = var.step-1-name
        action_on_failure = "CONTINUE"
        hadoop_jar_step {
            jar = var.step-1-jar
            args = var.step-1-args
        }
    }
    ebs_root_volume_size = 100

    bootstrap_action {
        path = "file:/bin/echo"
        name = "Dummy bootstrap action to prevent EMR cluster recreation when configuration_json has parameter javax.jdo.option.ConnectionPassword"
        args = [md5(jsonencode(file("dev-conf.json")))]
    }

    bootstrap_action {
        name = var.bootstrap-name
        path = var.bootstrap-loaction
        args = var.bootstrap-argument
    }

    lifecycle {
        ignore_changes = [ step,configurations_json ]
    }

    tags = {
        Name = var.emr-name
    }
}

resource "aws_emr_instance_group" "task" {
    cluster_id     = aws_emr_cluster.cluster-dev.id
    instance_count = var.task-count
    instance_type  = var.emr-instance-type
    ebs_config {
        size                    = var.emr-ebs-size
        type                    = var.emr-ebs-type
        volumes_per_instance    = 1
    }
}

### Debug Output

2023-05-30 10:48:13,334 INFO i-006bb40232897291e: new instance started
2023-05-30 10:48:13,385 INFO i-006bb40232897291e: bootstrap action 1 completed
2023-05-30 10:48:19,835 INFO i-006bb40232897291e: bootstrap action 2 completed
2023-05-30 10:48:19,837 ERROR i-006bb40232897291e: failed to start. bootstrap action 3 failed with non-zero exit code.
2023-05-30 10:48:26,630 INFO i-0500f686a3da54b9d: new instance started
2023-05-30 10:48:33,030 INFO i-0500f686a3da54b9d: bootstrap action 1 completed
2023-05-30 10:48:33,030 INFO i-0500f686a3da54b9d: bootstrap action 2 completed
2023-05-30 10:48:33,030 INFO i-0500f686a3da54b9d: all bootstrap actions complete and instance ready

### Expected Behavior

After bootstrap action 2 completed, it should be done

### Actual Behavior

it's start to do the bootstrap action 3 that does not exit in my main.tf

### Steps to Reproduce

1.terraform init 
2.terraform apply -var-file .\dev-vars.tfvars

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
