### ISSUE TITLE
Bump to Go version 1.19.9 or 1.20.4

### ISSUE THREAD

**Issue by david2764** [hashicorp/terraform#33306]
### Terraform Version

```shell
version 1.4.6
```

### Terraform Configuration Files

```terraform
...terraform config...
```
I can't install Terraform version 1.4.6 because it is being blocked by our firewall because the version of Go you're using is too old.

### Debug Output

      "status": 403,
      "message": "Artifact download request rejected: terraform/terraform.1.4.6.nupkg was not downloaded due to the download blocking policy configured in Xray 

### Expected Behavior

Download and install Terraform

### Actual Behavior

I can't download and install Terraform because the version of Go you're using is too old

### Steps to Reproduce

1. login to Artifactory configured with xray
2. try to download terraform package

**Comment by jbardin** [comment]
Hi @david2764,

We cannot retroactively build and release prior versions with a new toolchain, so the existing releases will remain as-is. If there were a security issue uncovered in a minor version, it could warrant a new patch release, however none of the updates to the Go toolchain are critical to the operation of the Terraform CLI.

The latest go toolchain patches will be incorporated in an upcoming Terraform release. 

Thanks!
