### ISSUE TITLE
Terraform Agent TFC-Agent allow additional options

### ISSUE THREAD

**Issue by Esity** [hashicorp/terraform#33319]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_arm64
```

### Use Cases

When running worker pools, it would be nice to have additional flags features that we see across all the Hashicorp products. 
Examples of this include

```
  -tls-server-name=<value>
     The server name to use as the SNI host when connecting via
     TLS. This can also be specified via the CONSUL_TLS_SERVER_NAME
     environment variable.

-ca-file=<value>
     Path to a CA file to use for TLS when communicating with Consul.
     This can also be specified via the CONSUL_CACERT environment
     variable.

-ca-path=<value>
     Path to a directory of CA certificates to use for TLS when
     communicating with Consul. This can also be specified via the
     CONSUL_CAPATH environment variable.

  -client-cert=<value>
     Path to a client cert file to use for TLS when 'verify_incoming'
     is enabled. This can also be specified via the CONSUL_CLIENT_CERT
     environment variable.

  -client-key=<value>
     Path to a client key file to use for TLS when 'verify_incoming'
     is enabled. This can also be specified via the CONSUL_CLIENT_KEY
     environment variable.

CONSUL_HTTP_SSL_VERIFY=true|false
```

### Attempted Solutions

Manually pulling the tfc-agent docker image, rebuilding with local certs and then republishing which seems redundant

### Proposal

Add these additional Flags/Configs to be able to customize the ssl settings for tfc-agent images without rebuilding per the docs

https://support.hashicorp.com/hc/en-us/articles/12983877427603-How-to-Add-Custom-Certificates-to-Terraform-Agents-for-use-with-Terraform-Enterprise

**Comment by crw** [comment]
Hi @Esity, thanks for this request! As it relates directly to products of the commercial product not controlled by the open source team, I would ask that you direct your inquiries to [tf-cloud@hashicorp.support](mailto:tf-cloud@hashicorp.support) or [open a new request](https://support.hashicorp.com/hc/en-us/requests/new). Thanks again for this feedback!
