### ISSUE TITLE
APIM external network doesn't have option to supply public IP and therefore deploys broken

### ISSUE THREAD

**Issue by BigFrog-coding** [hashicorp/terraform#33329]
### Terraform Version

```shell
terraform version
Terraform v1.3.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.39.0
+ provider registry.terraform.io/hashicorp/azurerm v3.59.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

### Terraform Configuration Files

```terraform
resource "azurerm_api_management" "apim_network_integrated" {
  name                = local.name
  location            = var.location
  resource_group_name = var.resource_group_name
  publisher_name      = "publisher"
  publisher_email     = "email@email.com"

  sku_name = var.sku
  tags     = var.tags

  policy {
    xml_content = <<XML
      <policies>
        <inbound />
        <backend />
        <outbound />
        <on-error />
      </policies>
    XML
  }
  virtual_network_type = var.virtual_network_type  # this is External
  virtual_network_configuration {
    subnet_id = var.subnet_id
  }

  lifecycle {
    ignore_changes = [
      policy,
      tags
    ]
  }

}
```

### Debug Output

The Terraform deploys fine, it just doesn't do the right things

### Expected Behavior

The networking should work and communicate with the management API

### Actual Behavior

The networking is set without public IP so it is broken and management API cannot be reached

### Steps to Reproduce

terraform init
terraform apply

Navigate to the resource in portal and witness the errors

I have looked through the provider documentation and it does not have an attribute to accept a public IP

**Comment by crw** [comment]
Hello @BigFrog-coding, this appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
