### ISSUE TITLE
‘For Error: Unsupported Argument’ on terraform-aws-rds module v3.5.0

### ISSUE THREAD

**Issue by skwalker624** [hashicorp/terraform#33348]
### Terraform Version

```shell
Terraform v0.13.7
```

### Terraform Configuration Files

```terraform
module "test_db" {
    source = "terraform-aws-modules/rds/aws"
    version = "3.5.0"

    identifier = "test-db"

    create_db_subnet_group = false
    create_db_option_group    = false
    create_db_parameter_group = false

    engine               = "mysql"
    engine_version       = "8.0.28"
    family               = "mysql8.0"
    major_engine_version = "8.0"
    instance_class       = "db.t3.medium"

    allocated_storage = 20
    storage_encrypted = true

    maintenance_window = "Tue:00:00-Tue:03:00"
    backup_window      = "03:00-06:00"
    backup_retention_period = 30

    port                                = 3306
    name                                = "test-db"
    username                            = "admin"
    password                            = var.TEST_DB_PASSWORD
    iam_database_authentication_enabled = true

    multi_az               = false
    db_subnet_group_name   = aws_db_subnet_group.db_subnet_group.name
    vpc_security_group_ids = [aws_security_group.test-access-to-db-sg.id]
    
    deletion_protection             = true
    enabled_cloudwatch_logs_exports = ["audit", "error", "general", "slowquery"]

}
```

### Debug Output

Error: Unsupported argument

  on .terraform/modules/test_db/modules/db_instance/main.tf line 34, in resource "aws_db_instance" "this":
  34:   name                                = var.name

An argument named "name" is not expected here.

Error: Unsupported argument

  on .terraform/modules/test_db/modules/db_instance/main.tf line 140, in resource "aws_db_instance" "this_mssql":
 140:   name                                = var.name

An argument named "name" is not expected here.

### Expected Behavior

No errors during plan

### Actual Behavior

Plan failed with error shown above

### Steps to Reproduce

terraform plan -detailed-exitcode

### References

Solution might be similar to that in https://github.com/hashicorp/terraform/issues/31615
Links to terraform-aws-rds module that might help:
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/v3.5.0/modules/db_instance/main.tf#L34 
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/v3.5.0/modules/db_instance/main.tf#L140 
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/v3.5.0/modules/db_instance/variables.tf#L84

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

In this case the probable cause is that you are using a newer version of the provider than what is supported by the module, where the given attribute no longer exists.

Thanks!
