### ISSUE TITLE
Terraform Cloud CLI runs are stuck in Pending state

### ISSUE THREAD

**Issue by periwinkleFTW** [hashicorp/terraform#33352]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/google v4.59.0
+ provider registry.terraform.io/hashicorp/google-beta v4.59.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1

Your version of Terraform is out of date! The latest version
is 1.5.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

na

### Expected Behavior

Expect the run to proceed

### Actual Behavior

Run is stuck in `Pending` in terraform cloud, cannot cancel the run manually there see 'waiting for run update...'
```
Waiting for the plan to start... (8m30s elapsed)
Waiting for the plan to start... (9m0s elapsed)
Waiting for the plan to start... (9m30s elapsed)
Waiting for the plan to start... (10m0s elapsed)
Waiting for the plan to start... (10m30s elapsed)
Waiting for the plan to start... (11m0s elapsed)
Waiting for the plan to start... (11m30s elapsed)
Waiting for the plan to start... (12m0s elapsed)
```

When i try to cancel through CLI (ctrl-c) it shows this message:
```
^C
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...


The remote operation was successfully cancelled.
```
But run shows `Pending` in the workspace.

### Steps to Reproduce

terraform apply -auto-approve

### Additional Context

I tried unlocking workspace, but it does not change anything

**Comment by radditude** [comment]
Terraform Cloud experienced [an incident](https://status.hashicorp.com/incidents/hclbrjmpvfj4) earlier today with behavior that sounds like what you're describing! That problem has been resolved, so your TFC runs should proceed normally now.

A note for next time: the Terraform Cloud team doesn't monitor issues on this repository, so in the event of a Terraform Cloud outage you'll get more timely assistance if you open a [support ticket](https://support.hashicorp.com/hc/en-us/requests/new) instead. Thanks for reporting!
