### ISSUE TITLE
Expose whether a plan errored or not in the JSON output

### ISSUE THREAD

**Issue by andrewhickman** [hashicorp/terraform#33368]
### Terraform Version

```shell
> /opt/hostedtoolcache/terraform/1.5.0/x64/terraform version
Terraform v1.5.0
on linux_amd64
```

### Use Cases

We are using the JSON format of a terraform plan (`terraform show -json plan.tfplan`) to determine whether a plan is a no-op, or whether it contains resource deletions. This is used in our CI pipelines to determine the scope of a change (for example, whether it needs us to remove azure resource locks). 

In #32395 and related PRs, I see that plans now have an `errored` state for when the plan command failed but it still wrote a plan file. We would like to handle this state in our code to avoid misleading output.

### Attempted Solutions

We can determine if the plan succeeded from the terraform CLI exit code, but our azure devops pipeline step doesn't expose this in a convenient way (since our analysis runs whether or not the terraform step succeeded)

The `terraform show` output without the json flag does indicate whether the plan succeeded, but relying on the exact format of this is undesirable

### Proposal

I think the neatest solution to this would be new field in the JSON output
```json
  "errored": true
```

### References

- #32395

**Comment by crw** [comment]
Thanks for this feature request!
