### ISSUE TITLE
Import block - Import resources with name_prefix

### ISSUE THREAD

**Issue by BornToBeRoot** [hashicorp/terraform#33374]
### Terraform Version

```shell
1.5
```

### Use Cases

Import block should support the import of existing resources that use `name_prefix`.

For e.g.:

Import an IAM role like `EC2Access-<TIMESTAMP>` 

### Attempted Solutions

```
import {
  to       = aws_instance.example
  id       = "EC2Access-"
  prefix = true
}
```

**Comment by devopsrick** [comment]
Unclear, why would the resource prefix impact the import? The existing resource already has a full name that would be used to import.  The prefix is irrelevant to an existing resource.

**Comment by jbardin** [comment]
Hi @BornToBeRoot,

Thanks for mentioning the use case. A `name_prefix` is not a Terraform feature, or part of the provider protocol, it is an attribute used by a few individual resources. Terraform has no way to turn something labeled as `prefix` into a valid import id, that would require some type of lookup into the remote API to find matching identifiers.

We are however looking into other ways to improve overall workflow of discovering the data needed for importing, so while this request isn't something that can be implemented, we are exploring the alternatives.

Thanks!

**Comment by BornToBeRoot** [comment]
@jbardin yeah the main problem is that you can only reference to a static string (can't use interpolation). In my case i have 

1) different names in different environments (like dev & prod)
2) i am using the `name_prefix` for different resources which will append a random string at the end of the name. If someone have to lookup a static string manually (for e.g. in aws) i can't make the import dynamically in case of a recovery. The people who use the stack need more knowledge about it. 
Maybe it would be possible to search by tags (like name=xxx, stack=xxx etc.), but that seems to be more provider specific.
