### ISSUE TITLE
support start-api for sam templates build with terraform

### ISSUE THREAD

**Issue by felicity-cl** [hashicorp/terraform#33387]
### Terraform Version

```shell
v1.3.6
```

### Use Cases

when setting up local development for lambda functions behind api gateway where the infrastructure is created by terraform with sam build --hook-name terraform --beta-features
the aws-sam/build/template doesnt include any reference to the api gateway resources.

It would be great to be able to use sam local start-api together with the terraform hook 

### Attempted Solutions

my workaround now will be to manually add httpApi endpoints to the template file  i guess

**Comment by kmoe** [comment]
This looks like it might be a provider issue, but I'm not sure which provider. If you're using the AWS provider, please open an issue in github.com/hashicorp/terraform-provider-aws with some more details including your Terraform configuration.

If you're sure this is a Terraform Core issue and that something can be done in this repo to fix it, please reopen this and fill in the rest of the bug or feature request issue template.
