### ISSUE TITLE
Template v2.2.0 does not have a package available - Mac M1 

### ISSUE THREAD

**Issue by Rithwik0480** [hashicorp/terraform#33388]
### Terraform Version

```shell
Terraform v1.1.4
on darwin_arm64
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

https://gist.github.com/Rithwik0480

### Expected Behavior

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

### Actual Behavior

<img width="1407" alt="Screenshot 2023-06-19 at 12 39 21 PM" src="https://github.com/hashicorp/terraform/assets/70954228/20e2cc24-a8f4-4bef-af33-4707107cbd6d">

### Steps to Reproduce

1. terraform init

**Comment by kmoe** [comment]
The template provider was archived some time ago, and releases are not available for new platforms. Please migrate your code to use the built-in `templatefile()` function and other features described in https://github.com/hashicorp/terraform-provider-template/issues/85.

**Comment by rctheinventor** [comment]
Is it still the case that the hashicorp template v2.2.0 does not support darwin_arm64?

I am still getting the same error, ie  Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64

I checked the link above wrt to templatfile, but that approach is too complicated for a cross platform codebase and it was not approved.

I'm surprised that this problem still exists after more than a year.  Is there a roadmap for when this will be fixed?

Thanks

**Comment by crw** [comment]
@rctheinventor There will be no further updates to the `template` provider, per the information stated in https://github.com/hashicorp/terraform/issues/33388#issuecomment-1597088557. It is archived, which means "deprecated" in this context.
