### ISSUE TITLE
Adding dry-run functionality 

### ISSUE THREAD

**Issue by ebrahimahmadi** [hashicorp/terraform#33397]
### Terraform Version

```shell
v1.3.9
```

### Use Cases

The enhanced dry run capability would simulate the apply phase more accurately by considering the target resource behavior. For example, if a resource like RDS has restrictions on immediate changes, the dry run apply would reflect this behavior and provide users with the actual result that would occur during the apply phase. This allows users to identify any potential issues or constraints before performing the actual apply, preventing unexpected errors and avoiding time-consuming rollbacks.

### Attempted Solutions

I tried to understand the behavior during the planning phase. But sometimes planning doesn't say too much.

### Proposal

the main idea is to have dry-run sub command added to apply. But it is really hard to say the service behaviours before really applying and see the result.

**Comment by ebrahimahmadi** [comment]
@jbardin @apparentlymart that's a correct point and now I have a new point of view. I need more time (≈ a week) to think about the edge cases I encountered during this time and see if I can relate them to the provider repository or TF. During this time, I try to have a grasp on the provider development and how the overall arch works in more depth. Can we keep this issue open for the next 1-2 weeks?

**Comment by ebrahimahmadi** [comment]
I will take this into aws provider repo, and will update here if required

**Comment by dtcMLOps** [comment]
Hi team, I have a similar use case with the Databricks provider. We can have a plan without error, but sometimes the apply command can fail if there is a misconfiguration regarding RBAC or Compute definition. It makes sense to have more information in the plan from the provider but would be great to have this functionality with the CLI.

https://developer.harness.io/docs/first-gen/continuous-delivery/terraform-category/terraform-dry-run/#step-1-set-terraform-step-as-plan
