### ISSUE TITLE
Missing a function to determine whether a directory exists at a given path.

### ISSUE THREAD

**Issue by minherz** [hashicorp/terraform#33394]
### Terraform Version

```shell
1.4.4
```

### Use Cases

A path to configuration containing templates to be parsed is provided as an input variable. We are looking to validate the provided path _before_ any resources will be created.

### Attempted Solutions

We tried to use [fileexists](https://developer.hashicorp.com/terraform/language/functions/fileexists) but the function returns an error:

```
Call to function "fileexists" failed: "_path-to-directory_" is a directory, not a file.
```

### Proposal

Like it was suggested in #22260, having `direxists` or another function that is dedicated for directory existence check would be a reasonable solution.

**Comment by crw** [comment]
Thanks for this request!

**Comment by crw** [comment]
Thank you for your continued interest in this issue. 

[Terraform version 1.8](https://github.com/hashicorp/terraform/blob/v1.8.0-beta1/CHANGELOG.md) launches with support of provider-defined functions. It is now possible to implement your own functions! We would love to see this implemented as a provider-defined function. 

Please see the [provider-defined functions documentation](https://developer.hashicorp.com/terraform/plugin/framework/functions) to learn how to implement functions in your providers. If you are new to provider development, learn how to [create a new provider](https://developer.hashicorp.com/terraform/plugin/framework) with the Terraform Plugin Framework. If you have any questions, please visit the [Terraform Plugin Development category in our official forum](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). 

We hope this feature unblocks future function development and provides more flexibility for the Terraform community. Thank you for your continued support of Terraform!

**Comment by minherz** [comment]
Thank you for pointing my attention to this new feature. In this particular case, creating a new provider just to implement the single function looks as a serious overhead. You can see that similar FRs were filled later. I believe adding this functionality is very simple and straightforward.

**Comment by austinvalle** [comment]
Hey everyone 👋🏻 ,

The `hashicorp/local` provider has just released a new [`direxists` ](https://registry.terraform.io/providers/hashicorp/local/latest/docs/functions/direxists) function in `v2.5`, which should provide what you're looking for here.

You can test this out now with Terraform [`v1.8.0-beta1`](https://github.com/hashicorp/terraform/releases/tag/v1.8.0-beta1) or wait for the upcoming `v1.8.0` release.

```terraform
# Configuration using provider functions must include required_providers configuration.
terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "2.5.1"
    }
  }
  # Provider functions require Terraform 1.8 and later.
  required_version = ">= 1.8.0"
}

output "exists" {
  value = provider::local::direxists("${path.module}/example-directory")
}

output "does_not_exist" {
  value = provider::local::direxists("${path.module}/fake-directory")
}
```

```bash
 $ tree          
.
├── example-directory
└── main.tf

2 directories, 1 file

 $ terraform plan

Changes to Outputs:
  + does_not_exist = false
  + exists         = true

```

If you run into any problems with the new function, please create an issue over in the [`local` provider issue tracker](https://github.com/hashicorp/terraform-provider-local/issues ), thanks!
