### ISSUE TITLE
Conditional trigger/force redeploy

### ISSUE THREAD

**Issue by szwalkowski** [hashicorp/terraform#33399]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.44.1
+ provider registry.terraform.io/hashicorp/google-beta v4.56.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

Your version of Terraform is out of date! The latest version
is 1.5.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

We have a resource that should be redeployed always for production or for staging.
From time to time, on development environments we want to omit that to speed up process.

### Attempted Solutions

How we force redeploy of resource:

Our resource is having label with evaluated timestamp.
Also we are aware of "null_resource" "triggers" and "lifecyclereplace_triggered_by"

We have very bad way to do this by changing timestamp with static value - but that requires at least one redeploy for static value. But that's just problematic
`    deploy_time   = var.force_deploy ? formatdate("YYYY-MM-DD-hhmm", timestamp()) : "force-deploy-off"
`

We also cannot use 'count' - cause other resources are depending on this resource that should be refreshed on demand

### Proposal

lifecycle {
   forceRedeploy: var.shouldRedeploy ? "true" : "false"
}

**Comment by jbardin** [comment]
Hi @szwalkowski,

Thanks for filing the issue. You say you are aware of `replace_triggered_by`, which is how you can force replacement, but that somehow does not suit your needs. Combining that feature with a `timestamp` will cause a resource to be replaced in every plan, can you explain how what you are trying to do differs from that scenario?

Thanks!

**Comment by szwalkowski** [comment]
@jbardin thanks for the answer :)

As I understand and I've tested.

So I combined 
```
lifecycle {
  replace_triggered_by = [
    null_resource.redeploy_cloud_functions
  ]
}
```
with
```
variable "redeploy" {
  default = true
}

resource "null_resource" "redeploy_cloud_functions" {
  triggers = {
    timestamp = var.redeploy ? "${formatdate("YYYY-MM-DD-hhmm", timestamp())}" : ""
  }
}
```

And that does not help with this empty redeploy, cause timestamp changes to empty string. There's just no way (unless I don't know) to IGNORE changing that timestamp.

Scenario is:
First deploy is setting timestamp
In second deploy you set this redeploy to false and it will redeploy with empty timestamp
and only on third deploy with false, we won't redeploy the resource

**Comment by jbardin** [comment]
Thanks @szwalkowski, 

Yes, if you want to toggle this behavior Terraform will always need one plan+apply cycle to store the prior value so there is something to compare for changes in the next plan. Since Terraform goal is to end up with a stable state where `plan` shows no changes, these continuous replacement plans can be awkward because they are at odds with the operation of Terraform. 

Normally we would recommend creating a stable configuration, and using the `-replace` plan when the immediate replacement of a resource is necessary. If the CLI option does not suit your needs, then I think what you would be looking for is a way to specify `-replace` via configuration, which is not current possible. That is a bit harder to deal with than other configuration based actions like `moved` or `import`, because it's not a one-time action which can be verified by the resulting state, i.e. it could continue to replace the object in every plan.

**Comment by szwalkowski** [comment]
@jbardin 
to understand correctly
like 'terraform apply -replace="aws_instance.example"' so I'd list all elements to replace? or at least one null_resource that would trigger others?

Now I started to wonder (will try this tomorrow and get back to you)
If I use null_resource with trigger timestamp or label or something to change.
But also ignore it with ignore_changes - will that allow combo allow me to get what I want :) 

I know it's chaotic, I'm ooo now. Will get back tomorrow once I try this.

Thanks!

**Comment by jbardin** [comment]
You can use a single resource as the "trigger" (a `null_resource, or now [`terraform_data`](https://developer.hashicorp.com/terraform/language/resources/terraform-data)), and use `replace_triggered_by` on anything you want to ensure is replaced at the same time.

I don't think `ignore_changes` is going to get what you're after, singe that is inherently going to ignore _all_ changes to the attribute, which means you might as well not continually update the timestamp.

**Comment by szwalkowski** [comment]
@jbardin 
Sorry for delay, but production happened ;) 
Well, I made it work but not enteraly as I wanted to.

So previously we had this force redeploy by label, I guess this is involved with provider now.
Cause it wasn't replacing but marked as 'will be updated in-place'.

replace_triggered_by now wants to remove the resource and recreate. I don't want this cause I will have downtime on production. this replace_triggered_by worked perfectly if not that resource now is marked as replaced

**Comment by jbardin** [comment]
Sorry, I'm not sure I understand, can you explain exactly what you originally meant by "redeploy"? Most of the time users take that to mean "replace" or "destroy then create", but if that is not what you are looking for I'm not sure what the alternative would be.

**Comment by szwalkowski** [comment]
@jbardin Now I see I badly named the thread.
I kinda grouped replace and update 'in-place' into one bag.

Also it happened just now that I've learnt little more about terraform and all those phases.

But from all I know now I think it's just impossible to do with how provider is built.

In the end, I don't want to 'redeploy' I want to have update in-place resource (and specific element of the resource that I know will trigger 'redeploy' of the Cloud Function on GCP by editing it, but not by deleting and creating it) to avoid downtime of the system.
Currently we are updating simple label in the Cloud Function resource and that triggers update in-place and function being redeployed with fresh source always. replace_triggered_by force whole resource to be replaced that just want to remove and create function from scratch

**Comment by jbardin** [comment]
Thanks @szwalkowski. That would be something the provider needs to implement (or perhaps already does in some way), but isn't something we can control from Terraform. I would suggest starting a discussion in the provider's community forum, or filing an issue with them directly.

Thanks!
