### ISSUE TITLE
Could not get instance id from the instance resource type while using latest aws provider plugin version

### ISSUE THREAD

**Issue by marieswarank95** [hashicorp/terraform#33402]
### Terraform Version

```shell
Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.4.0
```

### Terraform Configuration Files

```terraform
https://github.com/marieswarank95/terraform_practise.git
```

### Debug Output

│ Error: Unsupported attribute
│ 
│   on alb.tf line 55, in resource "aws_lb_target_group_attachment" "web_tg_attachment":
│   55:   count            = length(aws_instance.web_server[*].id)
│ 
│ This object does not have an attribute named "id".

### Expected Behavior

I need id attribute of instance resource type.

### Actual Behavior

Instance id is required while attaching the instance into target group. But the latest aws provider plugin version is not provided the id attribute of instance resource type.

### Steps to Reproduce

terraform apply -target=aws_vpc.vpc -target=aws_subnet.public_subnet
terraform plan

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by marieswarank95** [comment]
Hi Jbardin,

latest aws provider plugin is not provide id attribute in the instance resource type. But target_group_attachment resource type is expecting id of the instance in the target_id argument while using target type as instance. Can you please check the terraform documentation whether the mentioned statement is correct or not.

The below content is copied from terraform documentation,

**target_id - (Required) The ID of the target. This is the Instance ID for an instance, or the container ID for an ECS container. If the target type is ip, specify an IP address. If the target type is lambda, specify the arn of lambda.**

I have also raised discussion in forum. The below one is response that I got in the forum,

If you refer to the documentation for aws_instance, you’ll see that Terraform is right - they don’t have an id.

Yet the example in the documentation for aws_lb_target_group_attachment says they do.

Since there is apparently a bug in the documentation, I’d suggest you open a GitHub issue to let the provider authors know.

Perhaps there was an id in previous provider versions and it got removed.

Maybe arn is the replacement? I’m not sure but that seems plausible.

**Comment by crw** [comment]
Hi @marieswarank95, if you believe this to be a documentation issue in the AWS provider, please file an issue in the provider's repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. Thanks!

**Comment by marieswarank95** [comment]
Hi crw,

Jbardin has given another way to get id of instance. I followed that now I can get id of instance. But one thing all others know this way then it will be no issue.
