### ISSUE TITLE
No tag on ec2's network interface from nodegroup in eks

### ISSUE THREAD

**Issue by tmpm697** [hashicorp/terraform#33408]
### Terraform Version

```shell
Terraform v1.5.0-dev
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.5.1. You can update by downloading from https://www.terraform.io/downloads.html

aws provider 5.4.0
```

### Terraform Configuration Files

```
resource "aws_launch_template" "test" {
..
  dynamic "tag_specifications" {
    <this block applies tags for three resource_type instance, volume, network-interface>
  }
..
}
resource "aws_eks_node_group" "test" {
..
  launch_template {
    id      = aws_launch_template.test.id
    version = aws_launch_template.test.latest_version
  }
..
}


### Debug Output

none

### Expected Behavior

ec2's instance network interface is tag.

### Actual Behavior

ec2 instance is tagged, volume is tagged but ec2's network interface is not tagged.

### Steps to Reproduce

none

### Additional Context

_No response_

### References

_No response_

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
