### ISSUE TITLE
Event Bridge - Lambda function connection failure

### ISSUE THREAD

**Issue by MichalP574** [hashicorp/terraform#33405]
### Terraform Version

```shell
terragrunt v0.45.8
```

### Terraform Configuration Files

```terraform
data "aws_cloudwatch_event_bus" "GTR-event-bus" {
  name = "example-bus"
}

resource "aws_cloudwatch_event_rule" "GTR-event-rule" {
  name           = "GTR-event-rule"
  event_bus_name = data.aws_cloudwatch_event_bus.GTR-event-bus.name
  is_enabled     = true
  event_pattern = templatefile("${path.module}/eventPatern.json",{})
  role_arn = aws_iam_role.iam_for_eventBridge.arn
}

resource "aws_cloudwatch_event_target" "lambda" {
  rule      = aws_cloudwatch_event_rule.GTR-event-rule.name
  arn       = var.lambda_arn
  event_bus_name = data.aws_cloudwatch_event_bus.GTR-event-bus.name
}

resource "aws_cloudwatch_log_group" "eventbridgeLogs" {
  name = "/aws/events/gtr-eventBridge"

}

resource "aws_cloudwatch_event_target" "logs" {
  rule      = aws_cloudwatch_event_rule.GTR-event-rule.name
  arn       = aws_cloudwatch_log_group.eventbridgeLogs.arn
  event_bus_name = data.aws_cloudwatch_event_bus.GTR-event-bus.name
}
```

### Debug Output

no output

### Expected Behavior

![2023-06-21_13-20](https://github.com/hashicorp/terraform/assets/62249720/81d7396b-ef9e-4475-b90e-c42fd30b7c95)
![image](https://github.com/hashicorp/terraform/assets/62249720/16032f8a-1a9d-4aec-a849-df9c319a30ce)
![image](https://github.com/hashicorp/terraform/assets/62249720/6aa4608d-0695-4611-ba8e-75b1ca3a2ba5)
![image](https://github.com/hashicorp/terraform/assets/62249720/0fb81e05-a4ee-46b2-86c8-768a8a8bba0c)

### Actual Behavior

![image](https://github.com/hashicorp/terraform/assets/62249720/ded84a62-5b4a-42e5-8440-e6ba361b068d)
![image](https://github.com/hashicorp/terraform/assets/62249720/b7bbd6da-afd2-415d-9b38-b20715c58d0c)
![image](https://github.com/hashicorp/terraform/assets/62249720/487a9f72-b2fb-489d-b469-042b27157ff0)

### Steps to Reproduce

.

### Additional Context

Bug description:
- Manual approach (expected behavior):
When Event Bridge is created manually, all targets are visible in the Event Bridge console, and the trigger is attached automatically to the Lambda function. Additionally, an extra permission policy is automatically generated (please see Figure in the expected behavior section)
- 'Terraform' approach (actual behavior)
When Event Bridge is created using Terraform code, all targets are visible (similarly to the manual approach) but the trigger isn't attached to the Lambda function. Even if the aforementioned permission was attached to the lambda rule (additional resource in Terraform), the output didn't change.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
