### ISSUE TITLE
Lifecycle control to orphan a resource on deletion

### ISSUE THREAD

**Issue by jan-g** [hashicorp/terraform#33424]
### Terraform Version

```shell
All versions
```

### Use Cases

Take a look at the egregious nonsense [it's admittedly ingenious] that the EKS cluster provider has to do to work around deletion: https://github.com/cloudposse/terraform-aws-eks-cluster/blob/main/auth.tf#L91-L116

The issue here is that there are two resources that are typically stood up together: an EKS cluster, and an `aws-auth` configmap that's injected into it once it's up.

In order for this to work, the kubernetes provider must be configured with coordinates and credentials to talk to the k8s API server it stands up.

However, on deletion, those coordinates (which are derived from attributes on the EKS cluster resource) are zeroed out, because the resource that is the source of those is *scheduled* for deletion. This means that the attempt to delete the aws-auth certificate will fail, because by default the kubernetes provider attempts to talk to the local host. That attempt fails, and tf craps out.

Workarounds involve state edit - not possible with tfcloud - or manually releting the resource & reconciling state before deleting. Neither of those are particularly satisfactory.

The key here is that one resource (the kubernetes_config_map) is entirely subsumed by another (the cluster). So I don't particularly *want* to delete it explicitly; I'm happy to wait and have it cleaned up by the cluster deletion.

### Attempted Solutions

The only solution I can see here that is "principled" as far as TF's semantics are concerned is to have two workspaces, the second relying on the completion of the first, and to delay the configuration of the configmap until the second. For a single resource that's really lightweight (but critical!), this seems like a lot of overkill.

### Proposal

Some lifecycle option to just drop the object from tf state on deletion would be really useful for cases like this.

```
resource something "foo" {
  # .. etc.
  lifecycle {
    orphan_on_deletion = true
  }
}
```

### References

If you hunt around for this particular thing you'll find a lot of advice that boils down to: tf can't do this, here's a manual process to work around it.

**Comment by jan-g** [comment]
Another alternative - which seems more fiddly - might be to maintain the attributes of resources prior to their deletion, and only zeroing those out as the dependency graph traverses them. This'd let the kubernetes provider work, then clean up the values it was relying on.

**Comment by jbardin** [comment]
Hi @jan-g,

What you have described as using 2 separate configurations to manage the 2 independent layers of your infrastructure is the recommended method for dealing with providers that require preexisting infrastructure like kubernetes. We are working on some ideas for better workflows around those configurations, but within the current architecture some separation of configuration is required.

As for the specific feature request, we can merge that with #27035 which covers the same concept.

Thanks!

**Comment by jan-g** [comment]
Thanks for the rapid response. One question: what's happening to the provider configuraiton on deletion?

That is: is the kubernetes provider in this instance not being configured because its resources are being deleted? Or is it being configured with "anticipated zeroes" from the attributes of the eks resource object?

I *think*, from the way that module code I pointed to looks to work, that it's the latter.

So if there's

resource A
provider P { with configuration from A's attributes }
resource B { using provider P }

then on creation, there's a clear dependency path from A -> P -> B

On deletion, it looks like P is being configured with the wrong values. Surely for deletion the right behaviour here would be:

P { configured with A's saved state } -> B {delete using P} -> A{delete} ?

**Comment by jbardin** [comment]
@jan-g, It would take some time to analyze the entire config (especially since I'm not really familiar with how that provider or its resource work), but in modern Terraform versions a full destroy should generally work as long as the entire configuration is currently working. The overall order of operations is what you have shown, where `A` will be deleted after `B` which is using provider `P`. 

The most common failure scenario for this type of configuration is during resource replacement, where something in the provider's config becomes unknown during a plan and causes it to fail. Others situations include apply or destroy operations where something fails and the `kubernetes` doesn't get some piece of configuration it expects during the plan preventing recovery.
