### ISSUE TITLE
Store remote S3 state with JSON content type

### ISSUE THREAD

**Issue by thegedge** [hashicorp/terraform#3342]
Currently the state gets stored as [`application/octet-stream`](https://github.com/hashicorp/terraform/blob/0c3f2a915c0271c276232b8e2f2b618009fbdecc/state/remote/s3.go#L128). Not sure if there was a reason for that, but if not, perhaps store it as `application/json` so that when browsing in the AWS console, double-clicking won't require you to download the file (if your browser can read `application/json` responses).

If setting this as the default isn't appropriate, maybe another option could be to set it through something like `--backend-config="content-type=application/json"`.

**Comment by radeksimko** [comment]
That is a very good point. :+1: I agree.

**Comment by apparentlymart** [comment]
Yeah, I'm not sure what I was thinking when I set it to application/json. #3385 fixes this.

**Comment by stack72** [comment]
@radeksimko / @apparentlymart this can be closed now since #3385 fixes it
