### ISSUE TITLE
Error: Unsupported Terraform Core version

### ISSUE THREAD

**Issue by spencerchubb** [hashicorp/terraform#33439]
### Terraform Version

```shell
Terraform v1.5.2
on windows_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4"
    }
  }

  required_version = ">= 1.2"
}
```

### Debug Output

│ Error: Unsupported Terraform Core version
│
│   on versions.tf line 9, in terraform:
│    9:   required_version = ">= 1.2"
│
│ This configuration does not support Terraform version 1.1.6. To proceed,
│ either choose another supported Terraform version or update this version
│ constraint. Version constraints are normally set for good reason, so
│ updating the constraint may lead to other errors or unexpected behavior.

### Expected Behavior

I expected `terraform plan` should use v1.5.2 since `terraform version` says I have v1.5.2

### Actual Behavior

`terraform plan` says that I am using v1.1.6

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by jbardin** [comment]
Hi @spencerchubb,

Can you show exactly how you are executing Terraform in this situation? The version being checked is hard-coded and compiled into the binary, so there's no logic around that which could change the result of the comparison.

**Comment by spencerchubb** [comment]
Thanks for the response.

When I run `terraform version` it says 1.5.2. Then when I run `terraform plan` it gives the output I posted above.

**Comment by apparentlymart** [comment]
Hi @spencerchubb,

I think it would help if you could run each of the commands you've mentioned exactly as you did before but with the environment variable `TF_LOG=trace` set. That will cause Terraform to generate very verbose messages about its internals, but in this case the main interesting part will be near the start, where Terraform will announce what command line is being run, which version this executable thinks it is, and some information about some important dependencies that are included into Terraform. If you could share the first ~25 lines of trace for each of the commands I'm hoping that will help to explain why some of the commands seem confused about which version of Terraform they are.

Based on what you've described it seems like the version command and the plan command are the two most interesting here, but any others you might run along the way (such as `terraform init`) would be good to include too, so that if the version information changes we can narrow down exactly which command detected the change first.

Thanks!

**Comment by spencerchubb** [comment]
Here are all the steps I did with verbose logging. I ran `version`, `init`, and `plan`

```
$ terraform version
Terraform v1.5.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/vault v3.17.0

$ terraform init

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...

Initializing provider plugins...
- Finding latest version of hashicorp/vault...
- Finding hashicorp/time versions matching ">= 0.9.1"...
- Finding hashicorp/aws versions matching ">= 3.3.0, >= 4.0.0, < 5.0.0"...
- Installing hashicorp/vault v3.17.0...
- Installed hashicorp/vault v3.17.0 (unauthenticated)
- Installing hashicorp/time v0.9.1...
- Installed hashicorp/time v0.9.1 (unauthenticated)
- Installing hashicorp/aws v4.67.0...
- Installed hashicorp/aws v4.67.0 (unauthenticated)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

│ Warning: Incomplete lock file information for providers
│
│ Due to your customized provider installation methods, Terraform was forced to calculate lock file checksums locally for the following providers:
│   - hashicorp/aws
│   - hashicorp/time
│   - hashicorp/vault
│
│ The current .terraform.lock.hcl file only includes checksums for windows_amd64, so Terraform running on another platform will fail to install these providers.  
│
│ To calculate additional checksums for another platform, run:
│   terraform providers lock -platform=linux_amd64
│ (where linux_amd64 is the platform to generate)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ terraform plan
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

Waiting for the plan to start...

Terraform v1.1.6
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...

Setup failed: Failed terraform init (exit 1): <nil>

Output:
Initializing modules...
│ Error: Unsupported Terraform Core version
│
│   on versions.tf line 9, in terraform:
│    9:   required_version = ">= 1.2"
│
│ This configuration does not support Terraform version 1.1.6. To proceed,
│ either choose another supported Terraform version or update this version
│ constraint. Version constraints are normally set for good reason, so
│ updating the constraint may lead to other errors or unexpected behavior.
```

**Comment by apparentlymart** [comment]
Hi again @spencerchubb!

Thanks for sharing that output. Unfortunately it doesn't seem like you had `TF_LOG=trace` set when you ran those, since that's just the normal Terraform output rather than the internal trace logs.

The kind of output I'm expecting with `TF_LOG=trace` would look like this:

```
2023-06-29T09:13:36.681-0700 [INFO]  Terraform version: 1.6.0 dev
2023-06-29T09:13:36.681-0700 [DEBUG] using github.com/hashicorp/go-tfe v1.28.0
2023-06-29T09:13:36.681-0700 [DEBUG] using github.com/hashicorp/hcl/v2 v2.17.0
2023-06-29T09:13:36.681-0700 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2023-06-29T09:13:36.681-0700 [DEBUG] using github.com/zclconf/go-cty v1.13.2
2023-06-29T09:13:36.681-0700 [INFO]  Go runtime version: go1.20.4
2023-06-29T09:13:36.681-0700 [INFO]  CLI args: []string{"terraform", "version"}
2023-06-29T09:13:36.681-0700 [TRACE] Stdout is a terminal of width 198
2023-06-29T09:13:36.681-0700 [TRACE] Stderr is a terminal of width 198
2023-06-29T09:13:36.681-0700 [TRACE] Stdin is a terminal
2023-06-29T09:13:36.681-0700 [DEBUG] Attempting to open CLI config file: /home/apparentlymart/.terraformrc
2023-06-29T09:13:36.681-0700 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-06-29T09:13:36.682-0700 [INFO]  Loading CLI configuration from /home/apparentlymart/.terraform.d/credentials.tfrc
2023-06-29T09:13:36.682-0700 [INFO]  Loading CLI configuration from /home/apparentlymart/.terraform.d/credentials.tfrc.json
2023-06-29T09:13:36.683-0700 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-06-29T09:13:36.683-0700 [DEBUG] ignoring non-existing provider search directory /home/apparentlymart/.terraform.d/plugins
2023-06-29T09:13:36.683-0700 [DEBUG] ignoring non-existing provider search directory /home/apparentlymart/.local/share/terraform/plugins
2023-06-29T09:13:36.683-0700 [DEBUG] ignoring non-existing provider search directory /usr/share/plasma/terraform/plugins
2023-06-29T09:13:36.683-0700 [DEBUG] ignoring non-existing provider search directory /usr/share/gnome/terraform/plugins
2023-06-29T09:13:36.683-0700 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2023-06-29T09:13:36.683-0700 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2023-06-29T09:13:36.683-0700 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2023-06-29T09:13:36.683-0700 [INFO]  CLI command args: []string{"version"}
```

Most of the commands will produce additional logs as they do their other work, but for our purposes here just the subset I've shown above should be fine to start -- ending with the "CLI command args" line that marks where the specific subcommand starts running -- since that will allow us to confirm that all of these commands are behaving consistently as they start up and that there isn't anything unusual going on, such as a separate version manager program intercepting your calls to `terraform` instead of just running Terraform directly.

**Comment by apparentlymart** [comment]
Oh, actually never mind! Looking at your output I just noticed the crucial thing:

```
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

Waiting for the plan to start...

Terraform v1.1.6
on linux_amd64
```

You are using a remote workspace configured to run Terraform remotely in Terraform Cloud, and so it's the _remote_ Terraform that's returning this error message. You will need to change your Terraform Cloud workspace settings to select the newer version of Terraform.

**Comment by spencerchubb** [comment]
Thank you, that fixed the issue
