### ISSUE TITLE
Terraform fails when rerunning code on a different environment using the same AAD login

### ISSUE THREAD

**Issue by istarbuxs** [hashicorp/terraform#33430]
### Terraform Version

```shell
1.5.1
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output
```
synapse.WorkspacesClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="ValidationFailed" Message="Workspace request validation failed, check error details for more information" Details=[{"code":"AadOnlyAuthenticationIsEnabled","message":"Azure Active Directory Only Authentication is enabled. Please contact workspace administrator."}]
```

### Expected Behavior

Terraform should proceed with no errors

### Actual Behavior

It throws an error saying that AAD is only enabled

### Steps to Reproduce

The usual steps of init, plan and apply that runs successfully on one environment but doesn't run on other environments. Have to untick the  Support only Azure Active Directory authentication for this workspace

### Additional Context

Have this feature enabled in our Synapse: Support only Azure Active Directory authentication for this workspace

And we are able to do successful deployments in one environment but whenever we deploy on other environments, we are getting this error
```
synapse.WorkspacesClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="ValidationFailed" Message="Workspace request validation failed, check error details for more information" Details=[{"code":"AadOnlyAuthenticationIsEnabled","message":"Azure Active Directory Only Authentication is enabled. Please contact workspace administrator."}]
```

As mentioned, we have an environment where this works but whenever it is deployed in another environment, it throws this error

All environments were created using the same terraform scripts and files

**Comment by crw** [comment]
Hi, thanks for filing this issue. It is a little hard to say without the context of the configuration, but it sounds like this is a configuration issue with the AzureRM provider. If you believe this to be the case, you can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help.

I am going to close this under the assumption it is an AzureRM provider issue, but if you believe there to be an issue in core Terraform, please let me know. Including some kind of configuration that helps us reproduce the issue would also be very helpful. Thanks again!
