### ISSUE TITLE
Terraform hangs when attempting to change description on AWS Security Group

### ISSUE THREAD

**Issue by johnhamelink** [hashicorp/terraform#3344]
Hey there,

I seem to have found a bug in terraform with regards to destroying security groups:

I have an AWS launch configuration which is attached to a security group. If I change the description of the security group, terraform decides to destroy then re-create the security group, but it cannot because of the instances in the launch configuration which depend on it.

To me, the expected behaviour should be that the existing security group is edited, not destroyed.

**Comment by paulcdejean** [comment]
This is a duplicate of: #3341

**Comment by phinze** [comment]
Closing as dupe of #3341, thanks!
