### ISSUE TITLE
Error: engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>

### ISSUE THREAD

**Issue by patrickpacifico** [hashicorp/terraform#33440]
### Terraform Version

```shell
Terraform v1.5.0
on windows_386
```

### Terraform Configuration Files

```
resource "aws_elasticache_replication_group" "this" {
  count = module.this.enabled ? 1 : 0

  auth_token                  = var.transit_encryption_enabled ? var.auth_token : null
  replication_group_id        = var.replication_group_id == "" ? module.this.id : var.replication_group_id
  description                 = coalesce(var.description, module.this.id)
  node_type                   = var.instance_type
  num_cache_clusters          = var.cluster_mode_enabled ? null : var.cluster_size
  port                        = var.port
  parameter_group_name        = join("", aws_elasticache_parameter_group.this[*].name)
  preferred_cache_cluster_azs = length(var.availability_zones) == 0 ? null : [for n in range(0, var.cluster_size) : element(var.availability_zones, n)]
  automatic_failover_enabled  = var.cluster_mode_enabled ? true : var.automatic_failover_enabled
  multi_az_enabled            = var.multi_az_enabled
  subnet_group_name           = local.elasticache_subnet_group_name
  security_group_ids         = local.create_security_group ? concat(local.associated_security_group_ids, [module.aws_security_group.id]) : local.associated_security_group_ids
  maintenance_window         = var.maintenance_window
  notification_topic_arn     = var.notification_topic_arn
  engine_version             = var.engine_version
  at_rest_encryption_enabled = var.at_rest_encryption_enabled
  transit_encryption_enabled = var.transit_encryption_enabled || var.auth_token != null
  kms_key_id                 = var.at_rest_encryption_enabled ? var.kms_key_id : null
  snapshot_name              = var.snapshot_name
  snapshot_arns              = var.snapshot_arns
  snapshot_window            = var.snapshot_window
  snapshot_retention_limit   = var.snapshot_retention_limit
  final_snapshot_identifier  = var.final_snapshot_identifier
  apply_immediately          = var.apply_immediately
  data_tiering_enabled       = var.data_tiering_enabled
  auto_minor_version_upgrade = var.auto_minor_version_upgrade

  dynamic "log_delivery_configuration" {
    for_each = var.log_delivery_configuration

    content {
      destination      = lookup(log_delivery_configuration.value, "destination", null)
      destination_type = lookup(log_delivery_configuration.value, "destination_type", null)
      log_format       = lookup(log_delivery_configuration.value, "log_format", null)
      log_type         = lookup(log_delivery_configuration.value, "log_type", null)
    }
  }

  tags = module.this.tags

  num_node_groups         = var.cluster_mode_enabled ? var.cluster_mode_num_node_groups : null
  replicas_per_node_group = var.cluster_mode_enabled ? var.cluster_mode_replicas_per_node_group : null
  user_group_ids          = var.user_group_ids
}

```

### Debug Output

Error: engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>

  with module.redis-insumos-no-cluster.aws_elasticache_replication_group.this,
  on modules/elasticache_redis/main.tf line 12, in resource "aws_elasticache_replication_group" "this":
  12:   engine_version = var.engine_version

### Expected Behavior

I tested the "engine_version" a few times with the following versions:

**7.x
7.0
7.0.5
7.0.7**

In all cases the error is the same.
The parameter_group_name is set to **"default.redis7"**

With the code, I should have created a Redis ElastiCache with the engine_version set as stated above.
If I define the variable as **"null"** the creation is successful and the defined version is **7.0.7**

Using version 6.x the error does not happen.

### Actual Behavior

An error simply occurs and the ElastiCache is not created the way it should be.
Error: engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>

### Steps to Reproduce

1. terraform init
2. terraform plan or terraform apply

### Additional Context

I tested it in other versions of engine_version and the error doesn't happen.
The error only appears when using version 7 and its variations.
I confirmed that the value is passing correctly to the plan/apply
I already did the test passing the variable directly in the module and also as a value defined as default.
In all scenarios, only 7.x.x does the error occur.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
