### ISSUE TITLE
terraform creating terraform-provider file in temp folder, how to remove via build pipeline run

### ISSUE THREAD

**Issue by manishlak** [hashicorp/terraform#33467]
### Terraform Version

```shell
required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }
```

### Terraform Configuration Files

NA

### Debug Output

![image](https://github.com/hashicorp/terraform/assets/100189919/295adba5-f0ed-40f2-9224-25e4e40ab581)

when running the build pipeline terraform create terraform-provider file, how to remove these files via build pipeline run
due to this agent machine disk is getting full

### Expected Behavior

i think these files to be remove

### Actual Behavior

due to this agent machine disk is getting full

### Steps to Reproduce

![image](https://github.com/hashicorp/terraform/assets/100189919/d255d8db-b0e1-4138-b385-d430f1a61cfd)
using tasks to execute the terraform commands

**Comment by kmoe** [comment]
Thanks for the issue. This doesn't look like a bug in Terraform Core, since Terraform is not required to delete provider plugins after use.

Please post your question on https://discuss.hashicorp.com. You may also want to include more information about your build pipeline.
