### ISSUE TITLE
Global cache for terraform providers

### ISSUE THREAD

**Issue by rajuptvs** [hashicorp/terraform#33473]
### Terraform Version

```shell
Terraform v1.5.1
```

### Use Cases

Hey guys, first of all, I am pretty new to Terraform but, I really love it  and thanks for making this wonderful tool, but there is  one feature that I would like to see if that is possible.  Whenever Terraform init is applied for the first time in that folder, it installs the latest or the specified version. in that folder.  And it probably takes 4-5 mins depending on the network speed and other stuff.. don't know if this already happens, but cant the provider installer can be downloaded to one single local space of each used version as a cache and that can be used, this decreases both the time taken to download and also reduces the storage space utilization.

### Attempted Solutions

NA

**Comment by devopsrick** [comment]
I think you are looking for this? https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache

**Comment by kmoe** [comment]
@devopsrick is correct. Please use discuss.hashicorp.com for questions in future, rather than the bug tracker. Thanks!
