### ISSUE TITLE
Type Constraint error in module

### ISSUE THREAD

**Issue by ramankaur172** [hashicorp/terraform#33487]
### Terraform Version

```shell
Terraform version

0.15.5
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Error: Invalid quoted type constraints
│ 
│   on .terraform/modules/CCRSupportFix/variables.tf line 26, in variable "role_policy_arn":
│   26:   type = "list"
│ 
│ Terraform 0.11 and earlier required type constraints to be given in quotes,
│ but that form is now deprecated and will be removed in a future version of
│ Terraform. Remove the quotes around "list" and write list(string) instead
│ to explicitly indicate that the list elements are strings.

### Expected Behavior

Workspace should run successfully

### Actual Behavior

Getting error in module which is not in our control .
Output:
Initializing modules...
Downloading localterraform.com/CTO/sso/aws 0.1.15 for CCRSupport...
- CCRSupport in .terraform/modules/CCRSupport
Downloading localterraform.com/CTO/sso/aws 0.1.15 for CCRSupportFix...
- CCRSupportFix in .terraform/modules/CCRSupportFix

Error: Invalid quoted type constraints
│ 
│   on .terraform/modules/CCRSupportFix/variables.tf line 26, in variable "role_policy_arn":
│   26:   type = "list"
│ 
│ Terraform 0.11 and earlier required type constraints to be given in quotes,
│ but that form is now deprecated and will be removed in a future version of
│ Terraform. Remove the quotes around "list" and write list(string) instead
│ to explicitly indicate that the list elements are strings.

### Steps to Reproduce

terraform init

**Comment by kmoe** [comment]
As indicated by the error message, the module code is invalid. Please ask the module author to update the module. This does not appear to be a bug in Terraform, but please reopen the issue if there has been a misunderstanding.

**Comment by ramankaur172** [comment]
HI Team ,

But the module belongs to the Terraform community as suggested by our IAAS team so we raised this issue on the Terraform community Teams channel<https://teams.microsoft.com/l/team/19%3abKEEvDm_mosziEOteow8Q-Hy6b_QeCY8Yq1R5DCEUAA1%40thread.tacv2/conversations?groupId=04bbb4aa-a6ab-41bd-a9d0-95bf9b2929c8&tenantId=7c917db0-71f2-438e-9554-388ffcab8764>.

I am not able to change that module as that is not accessible to me .

Thanks



[A picture containing drawing  Description automatically generated]

Raman Kaur
Ulster Withdrawal Programme, Technology

__________________________________________________
6th Floor, Tower 1, Candor Space Gurgaon | Haryana | India
Cisco ext: 84791458 | Direct Line +91 124-791458|Mobile +91 9999679953
Zoom id : 761-109-3036
