### ISSUE TITLE
template_file stores sensitive information in cleartext

### ISSUE THREAD

**Issue by arohner** [hashicorp/terraform#3348]
When using a template_file, the contents of the variables are stored in .tfstate. This is a problem when the template contains sensitive information, such as passwords and API keys, because terraform encourages checking in the .tfstate to source control, and source control is not a good place to store credentials.

**Comment by stack72** [comment]
Related #516

**Comment by little-arhat** [comment]
related #1421

**Comment by phinze** [comment]
Thanks for the report, @arohner - closing this to keep things consolidated in #516 since this is a problem for any sensitive state values.
