### ISSUE TITLE
Warn or fail on encountering values in `for_each` that _may_ only be known until apply, but are _currently_ known at plan time

### ISSUE THREAD

**Issue by NiklasRosenstein** [hashicorp/terraform#33496]
### Terraform Version

```shell
1.4.6
```

### Use Cases

This is a mistake that is easy to run into, but particularly if someone hasn't encountered it before. You create a new resource with a `for_each` attribute and depend on some other resource in the key or in the set items. If the resource already exists, Terraform will have no issues computing a plan and go right ahead. However, if the resource is to be created in the same plan, Terraform cannot know keys or set items and thus fail to construct the resource addresses at plan time.

The issues is that Terraform "goes right ahead". Terraform projects are often built iteratively: Create a few components and see if it works, then continue from there. It can easily happen that you don't run into the above issue and get an error, but you might run into it when deploying another instance of your project from scratch. And suddenly you have to go back and rework the architecture of your project, expecting a different format of variables for example to allow passing static keys for resources or find some other method of ensuring the resource addresses can be constructed at plan time.

More often that not, this leads to a painful migration process because the `moved {}` block does not support moving a resource from the same block to a different key.

### Attempted Solutions

No known workaround other than "just not doing it" or finding out the hard way.

### Proposal

It seems to me that Terraform should be aware which attributes of a resource would only be known at plan time, even if the resource already exists. If any such attribute is used in a `for_each` such that the plan would fail if the resource does not already exist, Terraform should produce a warning or even flat-out fail.

**Comment by jbardin** [comment]
Hi @NiklasRosenstein,

Terraform cannot predict which values may become unknown in the future, that is determined by the individual implementation of each resource in response to certain changes in configuration. For now it's probably better to follow any work on the more generalized problem we have outlined in #30937

Thanks
