### ISSUE TITLE
aws_inspector2_enabler support enabling LAMBDACODE as a valid resource type

### ISSUE THREAD

**Issue by robwdux** [hashicorp/terraform#33502]
### Terraform Version

```shell
Terraform v1.5.2
AWS Provider v5.7.0
```

### Use Cases

AWS Inspector V2 is not fully supported.

Terraform seems to be aware of the configuration as LAMBDA_CODE and validates for that however AWS seems to use the value LAMBDACODE, so maybe this is a bugfix however the Terraform docs do not indicate this is supported.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_enabler
> Valid values are EC2, ECR, and LAMBDA. 

### Attempted Solutions

Attempted to configure without LAMBDA_CODE, however AWS expects LAMBDACODE. (previously configured through the console, no import option and attempted to override / bring under Terraform IaC)

```
  # aws_inspector2_enabler.alternate is tainted, so must be replaced
-/+ resource "aws_inspector2_enabler" "xxxx" {
      ~ id             = "xxxxxxxxxxxx-EC2:ECR:LAMBDA" -> (known after apply)
      ~ resource_types = [
          - "LAMBDACODE",
          + "LAMBDA_CODE",
            # (3 unchanged elements hidden)
        ]
        # (1 unchanged attribute hidden)
    }

...
2023-07-10T20:39:49.856-0500 [DEBUG] provider.terraform-provider-aws_v5.7.0_x5: HTTP Response Received: http.status_code=200 @module=aws aws.region=us-east-1 aws.service=Inspector2 http.duration=68 http.response.body="{"accounts":[{"accountId":"xxxxxxxxxxxx","resourceState":{"ec2":{"status":"ENABLING"},"ecr":{"status":"ENABLED"},"lambda":{"status":"ENABLED"},"lambdaCode":{"status":"DISABLED"}},"state":{"status":"ENABLED"}}],"failedAccounts":[]}
" http.response.header.date="Tue, 11 Jul 2023 01:39:49 GMT" http.response.header.x_amzn_requestid=3138b3aa-8d80-46eb-bfb2-63990862c330 @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.31/logging/logger.go:39 tf_resource_type=aws_inspector2_enabler http.response.header.content_type=application/json http.response.header.x_amz_apigw_id=H4Dj9H36oAMFWrw= http.response.header.x_amzn_trace_id=Root=1-64acb2e5-5c125598182faf186c0d38e0 tf_mux_provider=*schema.GRPCProviderServer tf_req_id=382cec12-a1bc-3de8-3882-c114fcec8043 tf_rpc=ApplyResourceChange aws.operation=BatchGetAccountStatus aws.sdk=aws-sdk-go-v2 tf_provider_addr=registry.terraform.io/hashicorp/aws http.response_content_length=230 timestamp=2023-07-10T20:39:49.855-0500
```

>Error: updating Amazon Inspector Enabler (564782605166-EC2:ECR:LAMBDA): operation error Inspector2: Disable, https response error StatusCode: 400, RequestID: 0b77533d-70b5-4cb5-9a83-4f3ee48cfe75, ValidationException: 1 validation error detected: Value at 'resourceTypes' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [LAMBDA_CODE, LAMBDA, ECR, EC2]]

response.body="{"accounts":[{"accountId":"xxxxxxxxxxxx","resourceState":{"ec2":{"status":"ENABLING"},"ecr":{"status":"ENABLED"},"lambda":{"status":"ENABLED"},"**lambdaCode**":{"status":"DISABLED"}},"state":{"status":"ENABLED"}}],"failedAccounts":[]}

### Proposal

Fix Terraform validation and update docs to add "LAMBDACODE" as a valid value for resource_type.

**Comment by kmoe** [comment]
Hi @robwdux - this appears to be an issue with the AWS provider. Please open an issue at that provider's repository: https://github.com/hashicorp/terraform-provider-aws.
