### ISSUE TITLE
Local modules not updated on change

### ISSUE THREAD

**Issue by Nuru** [hashicorp/terraform#33509]
### Terraform Version

```shell
Terraform v1.5.2
on linux_amd64
```

### Terraform Configuration Files

```terraform
module "example" {
  source = "/Users/user/src/terraform/modules/example"

  input = "foo"
}
```

### Debug Output

Not sure what to debug

### Expected Behavior

When using a local module and that module's source changes, I expect Terraform to use the updated module automatically.

### Actual Behavior

Terraform continues to use an outdated cached version of the local module rather than the updated version, even after running `terraform init`.

### Steps to Reproduce

I am not sure of the exact steps required to reproduce the problem. Here is roughly what I did:

```bash
export TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE=true
export TF_PLUGIN_CACHE_DIR=/Users/user/.terraform.d/plugin-cache
export TF_DATA_DIR_PER_NAMESPACE=true # used by local scripts
export TF_DATA_DIR=.terraform/dev
```

- `terraform init`
- `terraform plan`

Plan failed with errors due to a bug in the local module. I edited the local module to fix the bug, and then 

- `terraform plan` still had the same bug
- `terraform init`
- `terraform plan` still had the same bug
- `rm -rf .terraform/dev/`
- `terraform init`
- `terraform plan` succeeded

### Additional Context

I am willing to provide more information, but I am not sure what would be helpful. Please advise.

**Comment by jbardin** [comment]
Hi @Nuru,

A "local" path in the module source must be located relative to the configuration. An absolute path indicates an external source of a module and is copied into the module cache. See https://developer.hashicorp.com/terraform/language/modules/sources#local-paths for details.

Thanks
