### ISSUE TITLE
Error destroying internet gateway

### ISSUE THREAD

**Issue by toddrosner** [hashicorp/terraform#3350]
I have a VPC setup with several layers and all is great with Terraform commands until I try to destroy the stack. When destroying the stack, everything goes except at the end the internet gateway seems to have a race condition with the VPC, and I receive the following error:

```
Error applying plan:

1 error(s) occurred:

* aws_internet_gateway.default: Error waiting for internet gateway (igw-66e5da03) to detach: couldn't find resource
```
When this happens, I simply have to run the destroy command again and it cleans up. I've tried adding a dependency here and there to solve the problem, but no go. Anyone have any ideas?

**Comment by toddrosner** [comment]
This is an ongoing problem that seems to happen after approx. 125 resources exist. There's absolutely no problem with smaller stacks. Still unsure of why this happens.

**Comment by catsby** [comment]
Hey @toddrosner – we do retry deleting the Internet Gateway for up to 5 minutes... do you have any Instances that reference it, or any Elastic IP Addresses? I'm curious if adding an explicit `depends_on` in either of those resources (if you're using them and they use the Internet Gateway) will help here

- https://terraform.io/docs/providers/aws/r/internet_gateway.html

Let me know!

**Comment by toddrosner** [comment]
Hey @catsby. Thanks for getting back to me. The strange thing about the error is that it seems to be saying that it can't find the gateway, which would indicate a race condition.

I only have one resource that's referencing the gateway, and that's the public route table. Most of my instance resources are created using launch configuration and autoscaling group resources, but I will try adding gateway dependencies for the few other instance and EIP resources that I have to see if it makes any difference.

**Comment by toddrosner** [comment]
@catsby This seems to have fixed the problem, although for some reason it only worked when I moved the CloudWatch resources into their own cloudwatch.tf file...previously they were a part of their correlating instance files, i.e. web.tf.

I've ran several tests in multiple regions and haven't run into the issue at all.

**Comment by catsby** [comment]
Thanks for the follow up @toddrosner, sorry for the pain here.

Let's go ahead and close this for now. If anyone runs into this in the future and the `depends_on` doesn't work, or has new information, we can re-open and take another look

**Comment by danshao** [comment]
I have less than 125 resources but am receiving this error.

```
* aws_internet_gateway.cnm_gw: Error waiting for internet gateway (igw-df15dabb) to detach: couldn't find resource
```

The only references to the gateway are in the `aws_route_table` resource.

```
resource "aws_internet_gateway" "cnm_gw" {
    vpc_id = "${aws_vpc.main.id}"
    tags {
        Name = "${var.proj_name}-${var.env_name}_gateway"
    }
    depends_on = ["aws_vpc.main"]
}

resource "aws_route_table" "public" {
  vpc_id = "${aws_vpc.main.id}"
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.cnm_gw.id}"
  }
  tags {
    Name = "${var.proj_name}-${var.env_name}_public"
  }
  depends_on = ["aws_internet_gateway.cnm_gw"]
}
```
