### ISSUE TITLE
azurerm_cosmosdb_account => cors_rule => max_age_in_seconds

### ISSUE THREAD

**Issue by carlo98100** [hashicorp/terraform#33518]
### Terraform Version

```shell
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v3.64.0
```

### Terraform Configuration Files

```terraform
resource "azurerm_cosmosdb_account" "cosmos-account" {
  name                = "cos-test"
  resource_group_name = azurerm_resource_group.robot-rg.name
  location            = azurerm_resource_group.robot-rg.location
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  tags = {
    "defaultExperience"       = "Core (SQL)"
    "hidden-cosmos-mmspecial" = ""
  }

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }

  geo_location {
    location          = azurerm_resource_group.robot-rg.location
    failover_priority = 0
  }

  cors_rule {
          allowed_headers    = []
          allowed_methods    = []
          allowed_origins    = [
             "https://localhost:7001",
             "http://localhost:7001",
            ]
          exposed_headers    = []
          max_age_in_seconds = 0
        }

  timeouts {

  }
}
```

### Debug Output

╷
│ Error: expected cors_rule.0.max_age_in_seconds to be in the range (1 - 2000000000), got 0
│ 
│   with azurerm_cosmosdb_account.cosmos-account,
│   on main.tf line 101, in resource "azurerm_cosmosdb_account" "cosmos-account":
│  101:           max_age_in_seconds = 0
│ 

### Expected Behavior

When im running terraform plan, then im getting this error. But when im removing the cors section. Then im getting that it will change the current cosmos db account since the cors is missing. But when im checking the actual cosmos db account which is already live. Then it says that "max_age_in_seconds" is set to "0". Feels like a bug since I cant set it from my configuration but if I create it from the portal. Then it is 0 by default.

### Actual Behavior

It gives me the error that I've posted :(

### Steps to Reproduce

1. 'terraform init'
2. 'terraform plan'

**Comment by apparentlymart** [comment]
Hi @carlo98100,

What you've described here is a validation rule inside the `hashicorp/azurerm` provider, rather than in Terraform itself. Please report this in [the Azure provider's repository](https://github.com/hashicorp/terraform-provider-azurerm).

Thanks!

**Comment by carlo98100** [comment]
Oh im so sorry then, my bad :)
