### ISSUE TITLE
Code block for performing --replace operations

### ISSUE THREAD

**Issue by trifith** [hashicorp/terraform#33515]
### Terraform Version

```shell
terraform version
Terraform v1.5.2
on linux_amd64
```

### Use Cases

Our team runs all `terraform plan` and `terraform apply` operations inside a gitlab ci pipeline/container. We want a terraform code block that marks a resource for replacement in the next plan. Ideally, this block would be limited, to prevent repeated replacement of a resource. 

### Attempted Solutions

We currently use `terraform taint` to mark resource for replacement, but this is deprecated, and we do not allow `terraform apply` outside of our CI/CD pipeline so the existing --replace  option is not viable for our use cases. 

### Proposal

Create a new block `replace` that takes two arguments, a terraform resource path, and a timestamp. If they system time is before the timestamp, the resource should be destroyed and re-created. If the system time is after the timestamp, there should be no operation from this block. 

Code sample
```
replace {
  source = aws_instance.main
  before = "2023-07-13T10:00:00.000-05:00"
}
```

Alternatively, instead of the timestamp, the newly recreated resouce could be marked as `replaced` in the state until the code block is removed, at which time the `replaced` flag is removed. So a first apply with a replace block in the configuration would replace the named resource, create a new resource, and mark it as `replaced`. A second apply with the replace block in configuration would notice the resource has a `replaced` flag set and no-op. An apply with the `replace` block removed would removed the `replaced` flag.

**Comment by apparentlymart** [comment]
Hi @trifith! Thanks for sharing this use-case.

Terraform already has a language feature called "[replace triggered by](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by)" which allows you to declare that all of the instances of one resource must be replaced if there is any changed planned for any of the instances of another resource.

I feel a little unsure about what your intent is with the timestamp, but certain time-related interactions can be described using [the `hashicorp/time` utility provider](https://registry.terraform.io/providers/hashicorp/time), which has a few different resource types that allow treating spans of time as if they were objects managed by Terraform, with `replace_triggered_by` being one of the key use-cases of that. For example:

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    time = {
      source = "hashicorp/time"
    }
  }
}

resource "time_rotating" "example" {
  rotation_days = 30
}

resource "aws_instance" "example" {
  # ...

  lifecycle {
    replace_triggered_by = [
      time_rotating.example,
    ]
  }
}
```

This `time_rotating` resource type behaves as if it became invalid and therefore needs replacement every 30 days. Combined with `replace_triggered_by` in the second resource, this means that the instances of the second resource will also be planned for replacement at the same time. In this case this means that these EC2 instances effectively have an expiration time after which they must be replaced on the next Terraform run.

Do you think that something like the above could meet your goal with today's Terraform? Thanks!

**Comment by apparentlymart** [comment]
Hi @trifith,

The documentation for `replace_triggered_by` seems to be careful to say that it only applies when "a plan to _update or replace_", and so I wouldn't expect a "create" action alone to be considered, but I must admit that I've not personally tried that particular situation and so I'd suggest trying it in a temporary test configuration first to ensure that it'll behave the way you intend.

Specifically, I'd write a configuration containing one `terraform_data` resource and first apply that alone to make sure it already exists, and then add a second `terraform_data` resource and make the first one `replace_triggered_by` the second one. If you then plan that updated configuration you should hopefully see Terraform only plan to create the second resource and not plan to make any changes to the first.

**Comment by trifith** [comment]
Thanks! I'll be sure to test that out.

I think `replace_triggered_by` can fully meet our needs, so I don't believe we need this feature any longer. Thank you for your time!

**Comment by trifith** [comment]
For reference, replace_triggered_by is NOT activated with a create operation.

**Comment by apparentlymart** [comment]
Great, thanks for confirming! In that case, I'm going to close this issue under the assumption that `replace_triggered_by` is, for now at least, a sufficient building-block.

---

If you are a future reader seeing this response after you've found this issue while researching a similar use-case which `replace_triggered_by` _doesn't_ meet, please open a new issue and let us know what was missing when you tried to use `replace_triggered_by`, and then we can consider that new information while considering your new use-case. Thanks!
