### ISSUE TITLE
Machine-readable Plans

### ISSUE THREAD

**Issue by hany** [hashicorp/terraform#3353]
Hi there,

I'm wondering if there's a way to get some machine-readable `terraform plan` output. We're trying to build some form of automated validation that a `plan` is indeed what we expect it to be, as machines can do this more consistently than humans. The `plan` files appear to be in binary form, so it's not easily parsed. Is there an option available here?

**Comment by phinze** [comment]
This is definitely something we want to do to make plans consumable by external tooling. Tagged as a core enhancement.

**Comment by apparentlymart** [comment]
Seems related to #3170

**Comment by apparentlymart** [comment]
There is now an initial version of a JSON-format representation of plans in the `terraform show` command for the forthcoming Terraform 0.12.0.

```
terraform show -json planfile.tfplan
```

For a first pass this deals with the JSON rendering as a separate step, requiring a saved plan file (`terraform plan -out=planfile.tfplan`). In later releases we may find a way to include this in the main `terraform plan` command, but we want to keep it simple and separated to start.

The format of this for 0.12.0 will be considered experimental: we will avoid gratuitous changes to it, but may need to make changes to it based on feedback or other features in the next few releases. We'll document it as a stable interface in a future major release.
