### ISSUE TITLE
Side bar doesnt show the correct version for Terraform Enterprise v202307-1 (722)

### ISSUE THREAD

**Issue by juicybaba** [hashicorp/terraform#33569]
### Terraform Version

```shell
TFE: v202307-1
```

### Affected Pages

![image](https://github.com/hashicorp/terraform/assets/79539850/9d2cd18e-b63b-4b9b-9401-bdb05bb13536)

https://developer.hashicorp.com/terraform/enterprise/releases/2023/v202307-1

### What is the docs issue?

the version in the side bar is not correct

**Comment by kmoe** [comment]
Thanks, this is a known issue and being fixed now.

**Comment by kmoe** [comment]
This should now be fixed.
