### ISSUE TITLE
Invalid AWS Region: eu-central-2 coming from Terraform CLI

### ISSUE THREAD

**Issue by dosilyoun** [hashicorp/terraform#33575]
### Terraform Version

```shell
Terraform v1.4.6
```

### Terraform Configuration Files

```terraform
backend "s3" {
# Replace this with your bucket name!
bucket = "example"
key = "example/tfstate"
region = "eu-central-2"

# Replace this with your DynamoDB table name!
dynamodb_table = "example"
encrypt        = true

}
```

### Debug Output

Upgrading modules...
- ec2-ami in modules/ec2-ami
- s3 in modules/s3
- vpc in modules/vpc

Initializing the backend...
region
  AWS region of the S3 Bucket and DynamoDB Table (if used).

  Enter a value: eu-central-2

╷
│ Error: Invalid AWS Region: eu-central-2
│ 
│ 
╵

### Expected Behavior

no error message without region_skip_validation

### Actual Behavior

Error: Invalid AWS Region: eu-central-2

### Steps to Reproduce

terraform init

**Comment by apparentlymart** [comment]
Hi @dosilyoun,

The set of valid regions is encoded in the AWS SDK that Terraform uses to interact with S3, and so this region might be available in a newer version of the SDK.

Have you tried with the latest version of Terraform to see if the SDK is updated to know about this region? At the time I'm writing this comment the latest release is v1.5.3.

If even the latest version does not support this region then we may need to upgrade to a newer version of the AWS SDK to get support for it, and then make a new Terraform release with the updated SDK.

In the meantime you can configure the backend to assume all regions are valid using the option you already found.

Thanks!

**Comment by crw** [comment]
Per https://github.com/hashicorp/terraform/pull/33469#issuecomment-1626158408, there is a project to upgrade the aws sdk version underway. Just FYI.

**Comment by sahilsk** [comment]
@apparentlymart  for your responses and thank you @crw  for sharing the update on upgrade progress.

For extra clarity let me add more details here:


Problem is not with with the providers. (It could be with providers if your root module is using those regions, but that's the concern of aws team to resolve). 

As far as terraform is concerned issue is with backend backed by `s3`.

During the terraform `init` stage it initialize aws s3 backed using aws-sdk-go and there the support of zurich and other regions was found missing across all terraform releases including 1.6.x at the time of writing this comment.

Support for zuich was added in aws-sdk-go@v1.44.35 and for Melbourne in aws-sdk-go@v1.44.85.  
I custom compiled the terraform binary with these updated sdk to confirm and it does work


One thing i would like to advise aws folks is to be more verbose about such major release. Nowhere in the changelog it's mentioned that zurich support is added: https://github.com/aws/aws-sdk-go/pull/4619

**Comment by dosilyoun** [comment]
Discussion is going on https://github.com/hashicorp/terraform/pull/33607

**Comment by crw** [comment]
> Problem is not with with the providers. 

The provider teams maintain the backends in their respective domains. The AWS team maintains the S3 backend, Azure team maintains the Azure backend, etc. Just FYI.

**Comment by apparentlymart** [comment]
In the meantime the `s3` backend has switched to AWS SDK v2 and is using v1.25.3 in the `main` branch at the time I'm writing this comment.

I see references to `eu-central-2` in the source code for that release, so it seems like this region should now be supported. Therefore I'm going to close this. The AWS SDK's treatment of regions is somewhat complicated, with some variation between services, so please let me know if I've missed something that means that we should leave this open!
