### ISSUE TITLE
Azure Linux VM build fails using custom image from image gallery

### ISSUE THREAD

**Issue by SameepSB** [hashicorp/terraform#33577]
### Terraform Version

```shell
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.0.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.9.0
+ provider registry.terraform.io/hashicorp/tls v4.0.3
```

### Terraform Configuration Files

```terraform
...terraform config...
```
resource "azurerm_linux_virtual_machine" "vm" {
  name                            = var.servername
  location                        = data.azurerm_resource_group.rgds.location
  resource_group_name             = data.azurerm_resource_group.rgds.name
  source_image_id                 = var.source_image_id
  size                            = var.vm_size
  zone                            = local.avzonesval
  admin_username                  = var.admin_username
  admin_password                  = var.admin_password
  availability_set_id             = local.availsetval
  disable_password_authentication = "true"
  encryption_at_host_enabled      = "true"
  admin_ssh_key {
    username   = var.admin_username
    public_key = tls_private_key.key_ssh.public_key_openssh
  }
  network_interface_ids = [azurerm_network_interface.nic.id]
  os_disk {
    name                 = "${var.servername}-${var.os_disk_name}"
    caching              = var.disk_caching_type
    storage_account_type = var.storage_account_type
    disk_size_gb         = var.os_disk_size_gb
  }
 
 boot_diagnostics {
    storage_account_uri           = null
  }

  tags = var.tags

### Debug Output

 creating Linux Virtual Machine: (Name "XXXXXX606sb2" / Resource Group "XXXXXXXXX-TFTEST"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The value of parameter windowsConfiguration is invalid." Target="windowsConfiguration"
│
│   with module.LinuxVm["XXXXXXX6sb2"].azurerm_linux_virtual_machine.vm,
│   on .terraform/modules/LinuxVm/modules/VirtualMachine/LinuxVm/vm.tf line 56, in resource "azurerm_linux_virtual_machine" "vm":
│   56: resource "azurerm_linux_virtual_machine" "vm" {

### Expected Behavior

Same code with replaced with  **source_image_reference** by commenting **source_image_id** successful , however fails with source_image_id as updated above. 

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-LTS"
    version   = "latest"

### Actual Behavior

VM builds was successful till last 20th July , 

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

linux_private_ips = [
  "XXXXXXXsb2 : XXX.151.232.37",
]
linux_vms = [
  "XXXXXXXsb2",
]
linux_vms_rgs = [
  "XXXXXXX-TFTEST",
]
win_vms = []
windows_private_ips = []

### Steps to Reproduce

terraform init 
 terraform apply

### References

.

**Comment by kmoe** [comment]
This looks like it could be an issue with either the AWS provider or upstream. Please try searching or opening a new issue at the AWS provider issue tracker: https://github.com/hashicorp/terraform-provider-aws/issues.

**Comment by SameepSB** [comment]
I  suspect on upstream  AWS API , as issue got resolved without any change in code , now all the build are executed successfully, thanks for your support.
