### ISSUE TITLE
Terraform Theory

### ISSUE THREAD

**Issue by sparkprime** [hashicorp/terraform#3358]
@phinze @catsby @lwander @radeksimko @svanharmelen 
At dinner last night I mentioned that we could formally represent cloud providers using a transition system and therefore perhaps procedurally generate Terraform plans without needing special code for each resource.  I've quickly written some stuff up to illustrate what I meant by this, you can comment on the doc here https://docs.google.com/document/d/1W0bdfpdsJ3ZtBl6Hrgji8S-H3a3-L3cjnGdaDbm1Z90/edit?usp=sharing

It's pretty raw but I'm hoping it will be some food for thought :)

**Comment by sparkprime** [comment]
@armon

**Comment by josephholsten** [comment]
if you're doing this, you need to have a formalism for operations. it seems like the text is vague about a trivial operation (single state change for a single resource) and an O<sub>n</sub> operation, which looks like it's supposed to represent a set of trivial operations which may occur in parallel.

Of course, then the optimization problem becomes more interesting. Clearly we want to minimize the number of trivial operations total, as well as the number of operation phases. Intuitively, it seems like we want to front-load the operations into the earliest phase that it can fit into.

I'm not entirely sure how the internal state changes happen, but this simple world transition diagram seems like it won't even work with asynchronous changes. Given:

W<sub>0</sub> -> O<sub>0</sub> -> W<sub>1</sub> -> O<sub>1</sub> -> W<sub>2</sub>

Where O<sub>0</sub> contains two trivial operations, only one of which exists to resolve a constraint of O<sub>1</sub>.

We can begin execution of both trivial operations of O<sub>0</sub> at the same time, but if the constraining trivial op completes quickly but the other trivial op takes a while, when is it correct to block waiting for both to complete? When is it correct to allow 0<sub>1</sub> to begin?

Which brings up the problem of "encouraging parallelism" simultaneously with "encouraging create-before-destroy". Clearly naive front-loading of operations seems a simple way to encourage parallelism, but doesn't encourage create-before-destroy. We could front-load all non-destroy operations, and back-load all destroy operations, but then we don't have a simple test for optimization. Thoughts?

**Comment by sparkprime** [comment]
I didn't intend the O_n at the bottom to represent more than one operation, so parallelism is completely missing from the problem statement in the doc.  It's not very common to represent actual parallelism in operational semantics, even the CCS/CSP/Pi calculus represent only concurrency (non-deterministic interleaving) and not actual parallelism (doing several things in one step).  However in that world we typically are concerned with correctness, i.e. what state do you end up in or what intermediate states do you have (for all possible interleavings).  We care about that because of the world well-formedness property.  But we also care about performance (i.e. number of steps / phases).  So I'm not sure what we need here.  What you say about front loading and the tradeoffs with parallelism and create-before-destroy rings very true but I don't have any answers :)

On another note, yesterday @lwander pointed out very quickly that this problem is undecidable, because the operations are completely general.  In reality, cloud APIs are sensible and we can probably define some restrictions on what operations look like.  Like, operations only affect one resource, or one attribute of a resource, obey some sort of CRUD style or something like that.  This may be the key to making the whole problem more tractable.

In that case, I think we probably wouldn't get much benefit from finding some existing theorem prover and dropping it in to build the plan.  We're probably better off defining our own algorithm, perhaps based on some of the concepts used in Terraform already (diffing, etc).  In that case we would benefit from being able to prove it correct.  And typically once you've done formal analysis of a problem, the actual implementation based on that is a lot less complex than an implementation done without the benefit of the formal analysis.

**Comment by josephholsten** [comment]
Are you including the problem of detecting cycles in this problem? Because if we limit ourselves to cycle-free worlds this should be decidable, considering every W<sub>n</sub> -> W<sub>n'</sub> is possible by an operation series which destroy each existing resource, followed by an operation series which create each resource. This is solvable with a brute force naive approach by performing all operations which have no dependencies, and repeat. If any phase of dependency resolution finds all operations have dependencies, then we know that a cycle exists. And the number of possible dependency resolution phases is limited to the number of resources (a -> b -> c: max 3 phases).

Since there's a limited number of operations which can be equivalent to this naively generated operation series, we know that it's decidable. But it's totally plausible that generating and sorting them for optimization is extremely expensive. Of course, this problem then becomes extremely similar to automatic compiler optimization and parallelization research.

**Comment by knope** [comment]
off topic... and unsure of <sub>pro</sub><sup>per</sup> <sup>sub</sup> <sub>sup</sup> logicz... :P

considering:
  - W<sub>n</sub> state is where exists in <sub>n</sub>State through a combination of T<sup>erra</sup>F<sup>orm</sup> runs (tfstates available) and manual interaction.  Is there a way to quickly confirm procedurally which things got to be the way they are via manual interaction? (given aws cli json outputs and tfstates?

  I'm currently writing a lengthy shell script for this... but i would rather give up and push buttons or cry at this point...

**Comment by lwander** [comment]
@josephholsten 

@sparkprime's original idea was to allow arbitrary operations. Say I implement a "cloud provider" that describes a [first order logic](https://en.wikipedia.org/wiki/First-order_logic) with basic arithmetic (either on purpose or accidentally). Now, you have theorems (operations), and proofs (plans), and suddenly Terraform becomes an automated theorem prover. Now there will be invalid infrastructure that Terraform cannot [decide is impossible to create](https://en.wikipedia.org/wiki/Automated_theorem_proving#Decidability_of_the_problem). This doesn't have to do with cycle detection, but is instead a more fundamental problem in mathematics. The problem stems from the fact that we are defining a [recursively enumerable set](https://en.wikipedia.org/wiki/Recursively_enumerable_set) in terms of infrastructure. This means that while we can enumerate all possible plans for creating infrastructure, it can be impossible to decide that a given infrastructure is *not* in this enumerable set. 

As an interesting sidenote, Terraform can already prove basic statements. The `depends_on` attribute defines the logical `and` operator. During destroy, `prevent_destroy`, defines logical `not` (sort of). Now we have [functional completeness](https://en.wikipedia.org/wiki/Functional_completeness). `$\forall` exists in the Kleene Star expansion Terraform provides when referencing other resources. `$\exists` doesn't seem to have an analogue, so it's not a problem right now. But, `terraform plan` as it exists right now, is a theorem prover. For example, 

```
resource "axiom" "a" {
    count = n
}

resource "axiom" "z" {
}

resource "statement" "a" {
    count = n
    depends_on ["axiom.a.${count.index}", "axiom.z"]
}

resource "statement" "forall" {
    depends_on = ["statement.a.*"]
} 
```

Lets you prove, given `n + 1` axioms, `a_1, ..., a_n, z`, that for all `i <= n`, the statement `a_i and z` is true by checking that `terraform plan -target=statement.forall` succeeds. Of course, this isn't expressive enough to define anything undecidable, but with enough metaoperations you might run into interesting problems.

**Comment by teamterraform** [comment]
Hi all!

We're returning to this great old discussion as part of some issue gardening, and while there's some interesting things to think about here we're tending these days towards using GitHub issues to represent mainly bug reports and specific feature requests. Given the theoretical nature of this issue, there isn't any clear sense of when it would be "done", and so we're going to close it.

The ideas that were discussed in this issue did go on to inform and inspire other concrete discussions about Terraform design, though in practice it seems that the world of remote APIs is a little too messy for this sort of generalization and that hand-written planning rules inside provider plugins will continue to be our approach for the foreseeable future.
