### ISSUE TITLE
AWS QuickSight Analysis issue - FILTER_ALL_VALUES should be valid

### ISSUE THREAD

**Issue by merlian2** [hashicorp/terraform#33585]
### Terraform Version

```shell
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.9.0
```

### Terraform Configuration Files

resource "aws_quicksight_analysis" "xxxx" {
  analysis_id = "xxxx"
  name        = "xxxx"
  definition {
    data_set_identifiers_declarations {
      data_set_arn = aws_quicksight_data_set.xxxx.arn
      identifier   = "xxxx"
    }
...
    filter_groups {
      cross_dataset   = "SINGLE_DATASET"
      filter_group_id = "342990d5-0a49-4b2e-ab1d-d8697f668685"
      status          = "ENABLED"
      filters {
        category_filter {
          filter_id = "9507987d-202d-4b7f-aea9-d38c6b0224ae"
          column {
            column_name         = "owner_long_name"
            data_set_identifier = "qs_dashboard_all"
          }
          configuration {
            filter_list_configuration {
              match_operator     = "CONTAINS"
              select_all_options = "FILTER_ALL_VALUES"
            }
          }
        }
      }
   ...
      

### Debug Output

│ Error: expected definition.0.filter_groups.2.filters.0.category_filter.0.configuration.0.filter_list_configuration.0.select_all_options to be one of [ALL_VALUES], got FILTER_ALL_VALUES
│
│   with aws_quicksight_analysis.xxxx,
│   on quicksight.tf line 260, in resource "aws_quicksight_analysis" "xxxx":
│  260:               select_all_options = "FILTER_ALL_VALUES"
│

### Expected Behavior

Create the resource

### Actual Behavior

Problem is that using `select_all_options = "FILTER_ALL_VALUES"` leads to the following:

╷
│ Error: expected definition.0.filter_groups.2.filters.0.category_filter.0.configuration.0.filter_list_configuration.0.select_all_options to be one of [ALL_VALUES], got FILTER_ALL_VALUES
│
│   with aws_quicksight_analysis.xxxx,
│   on quicksight.tf line 260, in resource "aws_quicksight_analysis" "xxxx":
│  260:               select_all_options = "FILTER_ALL_VALUES"
│

If we swap to ALL_VALUES here then we get past the allowing to "apply" yes/no but then get:
an error a change:

Yet if I import the resource where it is set I get:

                      ~ configuration {
                          ~ filter_list_configuration {
                              ~ select_all_options = "FILTER_ALL_VALUES" -> "ALL_VALUES"
                                # (2 unchanged attributes hidden)
                            }
                        }

and then an error:

Error: creating Amazon QuickSight Analysis (xxxx): ValidationException: 6 validation errors detected: Value 'ALL_VALUES' at 'definition.filterGroups.3.member.filters.1.member.categoryFilter.configuration.filterListConfiguration.selectAllOptions' failed to satisfy constraint: Member must satisfy enum value set: [FILTER_ALL_VALUES];

So it looks like "FILTER_ALL_VALUES" should be allowable ?

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
