### ISSUE TITLE
Terraform functions allowed at init

### ISSUE THREAD

**Issue by jakubtrebacz-dev** [hashicorp/terraform#33588]
### Terraform Version

```shell
1.5.2
```

### Use Cases

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.64.0"
    }
  }
  backend "azurerm" {
    resource_group_name  = "xyz"
    storage_account_name = "zyx01"
    container_name       = "tfstate"
    use_azuread_auth     = true
    key                  = "${regex("(?:[^\\/]*\\/*){3}$", replace(path.cwd, "\", "/"))}/terraform.tfstate"
  }
}

My repos look like that
C:\repos\zyx.platfrom\terraform\zyx.platfrom
C:\repos\zyx.platfrom\terraform\zyx.platfrom.network
C:\repos\zyx.platfrom\terraform\zyx.platfrom.sql
etc.

I want the storage account to have same structure as the repos 
tfstate/zyx.platfrom/terraform/zyx.platfrom.sql/terraform.tfstate
Making it consistent and look like one whole set.

This way I can have one backend, and when connected over VPN I can just run terraform locally without need for second local config file

> (Jul 16, 2019) Duplicate of #22088 

### Attempted Solutions

${regex("(?:[^\\/]*\\/*){3}$", replace(path.cwd, "\", "/"))}/terraform.tfstate

### Proposal

Remove terraform function dependency between state file.
There is no reason why any of the functions should need access to state file, if there is then make the few fail with same error. 
If you are concerned about function being used with `data.` or `resource.` object that are in state file then what's the problem? Just throw message that the object doesn't exist in scenario when someone tries to use it before state file is loaded.

These functions should be part of the core terraform app and completely independent from external providers or state files. 

Give me one good reason why regex and replace functions need state file to run!

**Comment by jbardin** [comment]
HI @jakubtrebacz-dev,

Yes you are correct that while evaluation in general requires the state and configuration, a limited subset of expressions can be evaluated without the state. We can track any changes to this in the existing feature request #13022

Thanks!
