### ISSUE TITLE
Do not configure/validate provider when not used

### ISSUE THREAD

**Issue by rubbish** [hashicorp/terraform#3359]
We typically use resource counts to turn on/off different underlying instances for a given provider e.g. we might have devs use aws for their instances, but in production we'll use vSphere (https://github.com/rakutentech/terraform-provider-vsphere) like so:

``` tf
variable "vsphere_count" {
  default = "0"
}

variable "aws_count" {
  default = "1"
}

resource "aws_instance" "default" {
  count = "${var.aws_count}"
  instance_type = "t1.medium"
  ami = "ami-590c493c"
}

resource "vsphere_virtual_machine" "default" {
  count = "${var.vsphere_count}"
  // more config
}
```

And then in our environments, we override the counts to switch it to use vSphere.

However, we don't typically give devs credentials to vSphere. The way that the providers are initialized and configured, they get errors regarding unauthorized access to vSphere while doing even a plan. This is because terraform doesn't care if a provider's resources are used or not, it will always try to configure providers. Almost every provider I've looked at, in the `ConfigureFunc` checks to see if it can actually authenticate successfully. And I believe the providers are constructed in a different graph than resources.

Some of the workarounds I've considered are to:
- Make the vsphere provider lazy in that it won't authenticate until it tries create/modify/delete a resource. However, any validation of that provider would happen later in the apply, when it could have possibly created things into a partial state
- Add an `enabled` flag to the provider config.

My gut feeling is that terraform should not initialize and configure providers if there aren't any resources in the configuration or state (includes those with count=0).

**Comment by sherzberg** [comment]
Has there been any discussion outside of this issue? Lazy eval of the providers would be very handy.

**Comment by jbardin** [comment]
Hello,

Closing out old issues. This should be working as expected in current releases.
