### ISSUE TITLE
TERRAFORM CRASH

### ISSUE THREAD

**Issue by shankarbk** [hashicorp/terraform#33595]
### Terraform Version

```shell
Terraform v1.3.7
```

### Terraform Configuration Files

```
cloud_formation = {
  cft1 = {
    name               = "test-cft"
    template_path      = "data/cft1-template.json"
    policy_path        = "data/cft1-policy.json"
    parameters         = { BucketName = "test-bucket" }
    capabilities       = []
    on_failure         = "ROLLBACK"
    timeout_in_minutes = 30
    policy_body        = ""
    tags               = { "purpose" = "testing" }
  }
}

variable "cloud_formation" {
  type = map(object({
    name               = string
    template_path      = string
    parameters         = optional(map(any))
    capabilities       = optional(list(string))
    on_failure         = optional(string, "ROLLBACK")
    timeout_in_minutes = optional(number, 30)
    policy_path        = optional(string)
    tags               = optional(map(any), {})
  }))
}
resource "aws_cloudformation_stack" "this" {
  for_each           = var.cloud_formation
  name               = each.value.name
  template_body      = file("${each.value.template_path}")
  parameters         = each.value.parameters
  capabilities       = each.value.capabilities
  on_failure         = each.value.on_failure
  timeout_in_minutes = each.value.timeout_in_minutes
  policy_body        = file("${each.value.policy_path}")
  tags               = each.value.tags
}
```

### Debug Output

inconsistent map element types (cty.Object(map[string]cty.Type{"capabilities":cty.List(cty.String), "name":cty.String, "on_failure":cty.String, "parameters":cty.Map(cty.String), "policy_path":cty.String, "tags":cty.Map(cty.DynamicPseudoType), "template_path":cty.String, "timeout_in_minutes":cty.Number}) then cty.Object(map[string]cty.Type{"capabilities":cty.List(cty.String), "name":cty.String, "on_failure":cty.String, "parameters":cty.Map(cty.String), "policy_path":cty.String, "tags":cty.Map(cty.String), "template_path":cty.String, "timeout_in_minutes":cty.Number}))
goroutine 141 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/circleci/project/project/internal/logging/panic.go:55 +0x153
panic({0x2526100, 0xc004db40e0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/zclconf/go-cty/cty.MapVal(0xc0057a0f18)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/value_init.go:221 +0x47f
github.com/zclconf/go-cty/cty.transform({0x0?, 0x0, 0x0}, {{{0x2ec2590?, 0xc0025b74c0?}}, {0x255e5e0?, 0xc006f7f560?}}, {0x2ea9908, 0xc0005d02d8})
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/walk.go:204 +0xc3e
github.com/zclconf/go-cty/cty.TransformWithTransformer(...)
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.12.1/cty/walk.go:130
github.com/hashicorp/hcl/v2/ext/typeexpr.(*Defaults).Apply(0xc0009a2040?, {{{0x2ec2590?, 0xc0025b74c0?}}, {0x255e5e0?, 0xc006f7f560?}})
        /home/circleci/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.15.0/ext/typeexpr/defaults.go:38 +0xa7
github.com/hashicorp/terraform/internal/terraform.prepareFinalInputVariableValue({{0x0, 0x0, 0x0}, {{}, {0xc000520970, 0xf}}}, 0xc0001e6690, 0xc0009961a0)
        /home/circleci/project/project/internal/terraform/eval_variable.go:140 +0xaed
github.com/hashicorp/terraform/internal/terraform.(*NodeRootVariable).Execute(0xc0009a2640, {0x2ed8c98, 0xc0008d3340}, 0x0?)
        /home/circleci/project/project/internal/terraform/node_root_variable.go:82 +0x214
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0006ee4b0, {0x2ed8c98, 0xc0008d3340}, {0x1abe8e6cae0, 0xc0009a2640})
        /home/circleci/project/project/internal/terraform/graph_walk_context.go:136 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x26962a0, 0xc0009a2640})
        /home/circleci/project/project/internal/terraform/graph.go:74 +0x2f0
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000732180, {0x26962a0, 0xc0009a2640}, 0xc000889b40)
        /home/circleci/project/project/internal/dag/walk.go:381 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
        /home/circleci/project/project/internal/dag/walk.go:304 +0xf65

### Expected Behavior

cretes multiple stacks on aws

### Actual Behavior

TERRAFORM CRASH

### Steps to Reproduce

terraform init
terraform apply

**Comment by liamcervante** [comment]
Hi @shankarbk, thanks for filing this!

I was able to replicate this using Terraform v1.3.7, which did mean I was also able to verify that this has been fixed in later versions of Terraform. If you update to any version equal to or after v1.4.0 then you shouldn't see this crash. The most recent version of Terraform is v1.5.4, which is the version I would recommend.

If for any reason you can't update your Terraform version, then you can workaround this crash by removing the `any` type constraints in your variable definitions. If you replace the `tags` and `parameters` definitions with `optional(map(string))` instead of `optional(map(any))` then Terraform will not experience the type confusion that is causing this crash.

I will mark this as closed, but if you update to v1.5.4 and find you are still experiencing the crash, please reopen this issue and I'll investigate. I did try your reproduction in v1.5.4 and found that it worked, so I'm confident you won't need to reopen this.

Thanks again for filing this!
