### ISSUE TITLE
EBS volumes tags

### ISSUE THREAD

**Issue by Maneesankar** [hashicorp/terraform#33593]
### Terraform Version

```shell
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.9.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Terraform will perform the following actions:

  # module.testec2_01.module.ec2_complete.aws_instance.this[0] will be updated in-place
  ~ resource "aws_instance" "this" {
        id                                   = "i-111111"
        tags                                 = {
            "Name"         = "san1111"
            "application"  = "l11111"
            "created"      = "terraform"
            "owner"        = "test"
            "region"       = "singapore"
            "service"      = "na"
            "teleport"     = "xxxxx-11"
            "tier"         = "app"
        }
      ~ volume_tags                          = {
          - "application"  = "test" -> null
          - "created"      = "terraform" -> null
          - "owner"        = "test" -> null
          - "region"       = "singapore" -> null
          - "service"      = "na" -> null
          - "teleport"     = "xxxxx-11" -> null
          - "tier"         = "app" -> null
            # (1 unchanged element hidden)
        }
        # (30 unchanged attributes hidden)

        # (10 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Expected Behavior

When we execute terraform apply it should not show changes for the tags but even without changing the values of tags everytime when we run terraform plan it is showing as "changes"

### Actual Behavior

It is showing as "changes"

### Steps to Reproduce

[init.txt](https://github.com/hashicorp/terraform/files/12179172/init.txt)
Terraform will perform the following actions:

  # module.testec2_01.module.ec2_complete.aws_instance.this[0] will be updated in-place
  ~ resource "aws_instance" "this" {
        id                                   = "i-111111"
        tags                                 = {
            "Name"         = "san1111"
            "application"  = "l11111"
            "created"      = "terraform"
            "owner"        = "test"
            "region"       = "singapore"
            "service"      = "na"
            "teleport"     = "xxxxx-11"
            "tier"         = "app"
        }
      ~ volume_tags                          = {
          - "application"  = "test" -> null
          - "created"      = "terraform" -> null
          - "owner"        = "test" -> null
          - "region"       = "singapore" -> null
          - "service"      = "na" -> null
          - "teleport"     = "xxxxx-11" -> null
          - "tier"         = "app" -> null
            # (1 unchanged element hidden)
        }
        # (30 unchanged attributes hidden)

        # (10 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by kmoe** [comment]
Thanks, please raise this with the AWS provider: https://github.com/hashicorp/terraform-provider-aws/issues.
