### ISSUE TITLE
s3 backend on DigitalOcean Spaces fails to initialize: Error refreshing state: NotImplemented: Server does not support one or more requested headers.

### ISSUE THREAD

**Issue by devurandom** [hashicorp/terraform#33605]
### Terraform Version

```shell
❯ terraform -version
Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.28.1
+ provider registry.terraform.io/hashicorp/helm v2.10.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.21.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {
    region   = "us-east-1"
    endpoint = "ams3.digitaloceanspaces.com"
    bucket                      = "[REDACTED]"
    key                         = "[REDACTED]
    skip_credentials_validation = true
    skip_region_validation	= true
    skip_metadata_api_check     = true
  }
}
```

### Debug Output

https://gist.github.com/devurandom/63090471e7cb6c9ee4a110ba31b3e753

### Expected Behavior

Terraform should be able to read the state from DigitalOcean Spaces.

### Actual Behavior

```
❯ terraform init

Initializing the backend...
Error refreshing state: NotImplemented: Server does not support one or more requested headers. Please see https://developers.digitalocean.com/documentation/spaces/#aws-s3-compatibility
	status code: 501, request id: , host id:
```

### Steps to Reproduce

1. Initialize an s3 backend state with a previous version of Terraform
2. Upgrade to Terraform 1.5.4
3. Have `~/.aws/config` and `~/.aws/credentials` files setup for an actual AWS account
4. Have `$AWS_ACCESS_KEY_ID` and `$AWS_SECRET_ACCESS_KEY` unset
5. `terraform init`

### Additional Context

https://docs.digitalocean.com/reference/api/spaces-api/#aws-s3-compatibility

### References

* https://github.com/hashicorp/terraform/issues/25108

**Comment by devurandom** [comment]
Closing as invalid. I forgot to set `$AWS_ACCESS_KEY_ID` and `$AWS_SECRET_ACCESS_KEY` for DigitalOcean Spaces while having `~/.aws/config` and `~/.aws/credentials` files set up for an actual AWS account.

**Comment by crw** [comment]
Thanks for closing! In the future, you would also want to file these types of issues with the provider itself. You can find their bug tracking information in the provider registry. Thanks!
