### ISSUE TITLE
for_each dynamic statement check isn't working

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform#33609]
### Terraform Version

```shell
Terraform v1.5.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Terraform Configuration Files

# main.tf
```terraform
resource "null_resource" "test" {}

module "mod" {
  source                = "./module"

  test                  = [
    {
      name      = "name1"
    }, {
      name      = "name2"
      attr      = "test2"
    }, {
      name      = "name3"
      attr      = null_resource.test.id
    }
  ]
}
```

# module/main.tf
```terraform
variable "test" {
  type                  = list(object({
    name        = string
    attr        = optional(string, null)
  }))
  default               = null
}

resource "null_resource" "test" {
  for_each              = var.test == null ? {} : { for key, val in var.test : val.name => val if val.attr != null }
}
```

### Debug Output

https://gist.github.com/FransUrbo/bd04d1c8744cd7b48661f6363ae7fe65

### Expected Behavior

Create two `null_resources` - `"name2"` and `"name3"`.

Although I'm using a dynamic value for the `name3` attr value, it is NOT used (or needed) in the key.

As in, TF only needs to know *how many* of the resources to create - and it does know that it needs to create `null_resource.test` before it starts creating the `module.mod.null_resource.test["name3"]`. It should know/be able to figure out, even though it can't know the exact value, that `null_resource.test.id` isn't **null**.

If I comment out the `if val.attr != null` part, it will create the resource. But obviously it will create ALL the resources:
```
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

  # module.mod.null_resource.test["name1"] will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

  # module.mod.null_resource.test["name2"] will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

  # module.mod.null_resource.test["name3"] will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.
```

And if I comment out the `attr = null_resource.test.id` line, then again it will do the right thing (because `attr = null` by default):
```
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

  # module.mod.null_resource.test["name2"] will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

I can understand that you shouldn't be able to use a dynamic value, not known until apply, in the key of a `for_each`, but in this case the number of resources COULD be calculated. It might know exactly WHAT to do, but that's ok, there's plenty of resources that `plan` can't figure out what to do with. The important part of `for_each` (and `count`) is to know *how many* resources to create..

Issues like this with `count` and `for_each` have been around since time began. There's (probably) millions of issues with them, so isn't it time to sit down and maybe redesign this?

### Actual Behavior

Error:
```
The "for_each" map includes keys derived from resource attributes that cannot
be determined until apply, and so Terraform cannot determine the full set of
keys that will identify the instances of this resource.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by FransUrbo** [comment]
In the real world, we are transitioning from ECS/EC2 to ECS/Fargate and I have a load balancer module that tries to cater for both by attaching the EC2 to the load balancer with this code:
```terraform
resource "aws_lb_target_group_attachment" "attachment" {
  for_each                              = var.loadbalancer.targets == null ? {} : { for key, val in var.loadbalancer.targets : val.name => val if val.attachments != null }

  target_group_arn                      = aws_lb_target_group.blue[each.key].arn
  target_id                             = each.value["attachments"]
}
```

Now, ` attachments` are **null** by default - ECS/Fargate is the standard that we're working against and ECS takes care of this instead of TF - but that resource should *only* be created if/when we're running it on EC2s.

But as the code above perfectly illustrates this - TF don't like the `val.attachments != null` check. I also do similar stuff like this in other places, all stemming from the same "base problem" in TF. It doesn't like the `if` statement in the `for_each`.

**Comment by jbardin** [comment]
Hi @FransUrbo,

The statement as shown is working as designed. Because the value of `null_resource.test.id` is unknown, terraform cannot determine whether it is equal to `null` or not, because `null` is a perfectly valid resolution to a value being unknown.

There is a new feature in the language however called refinements, which could allow a provider to declare things like a "value is unknown but will not be `null`", along with other concepts like providing a range of possible lengths for unknown collections, and known string prefixes for unknown string. In fact if you substitute the `null_resource` for the newer `terraform_data` resource type, your example will work as you expected.

This feature will be more useful as providers update to the newer framework and update resources to provide the missing information when necessary. You can see some more details in issue #33237

Thanks!

**Comment by FransUrbo** [comment]
That looks like a step in the right direction. Having "value is unknown but will not be null" will most definitely help. Although, looking at a resource, very few values that TF knows about is actually `null`.

If it is, it's not "in" there (in the TF resource).

For example, I often do this (to dynamically use or not use an attribute in a resource) - `attribute = var.something ? var.something : null`. Which will case `attribute` to not be used at all.

At least, that seems to be the case for AWS.
