### ISSUE TITLE
 Issue: Failure to detect changes in optional/computed field in any resource

### ISSUE THREAD

**Issue by ravinitp** [hashicorp/terraform#33617]
### Terraform Version

```shell
0.12.31
```

### Terraform Configuration Files
```
resource "oci_core_subnet" "test_subnet" {
    #Required
    cidr_block = var.subnet_cidr_block
    compartment_id = var.compartment_id
    vcn_id = oci_core_vcn.test_vcn.id

    #Optional
    availability_domain = var.subnet_availability_domain 
}
```
### Debug Output

NA

### Expected Behavior

On an existing availability domain specific subnet, if the availability_domain setting is omitted or set to null, oci_core_subnet resource should detect the change and terraform plan should advise actions accordingly(either update the subnet or destroy/re-deploy).

### Actual Behavior

Summary

The https://github.com/oracle/terraform-provider-oci/issues/1578 reported involves a field in the Terraform configuration that is marked as optional and computed true.
When a user sets a value for this field, the resource is created and updated correctly upon subsequent changes.
However, if the user removes the value from the configuration or sets it to null, the Terraform plan fails to detect the change, resulting in unexpected behavior.

### Steps to Reproduce

create an availability domain specific subnet with availability_domain = var.subnet_availability_domain set
remove the availability_domain = var.subnet_availability_domain line or set availability_domain = null
terraform plan

### Additional Context

This is not terraform provider related issue.

**Comment by jbardin** [comment]
HI @ravinitp,

If an optional+computed value is removed from the configuration, it is up to the provider to determine how that change should be processed. Terraform sends all the necessary information to the provider during the plan, and must adhere to the changes returned by the provider. If you have questions about provider development, it's better to ask in the [community forums](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). 

Thanks!
