### ISSUE TITLE
Cannot network mirroring github.com

### ISSUE THREAD

**Issue by hoangnguyen92** [hashicorp/terraform#33615]
### Terraform Version

```shell
1.4.5
```

### Terraform Configuration Files

```
{
    "plugin_cache_dir": "/home/user/path",
    "plugin_cache_may_break_dependency_lock_file": true,
    "provider_installation": {
        "network_mirror": [
            {
                "url": "tf-registry-company.com",
                "include": [
                    "company.com/*/*",
                    "registry.terraform.io/*/*",
                    "github.com/*/*"
                ]
            }
        ],
        "direct": [
            {
                "exclude": [
                    "company.com/*/*",
                    "registry.terraform.io/*/*",
                    "github.com/*/*"
                ]
            }
        ]
    },
    "host": [
        {
            "company.com": [
                {
                    "services": [
                        {
                            "modules.v1": "tf-registry-company.com"
                        }
                    ]
                }
            ],
            "registry.terraform.io": [
                {
                    "services": [
                        {
                            
                            "modules.v1": "tf-registry-company.com"
                        }
                    ]
                }
            ],
            "github.com": [
                {
                    "services": [
                        {
                            
                            "modules.v1": "tf-registry-company.com"
                        }
                    ]
                }
            ]
        }
    ]
}
```

### Debug Output

none

### Expected Behavior

go and download module from tf-registry-company.com

### Actual Behavior

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...
Downloading git::https://github.com/terraform-aws-modules/terraform-aws-vpc.git for my_threat_002...
- my_threat_002 in .terraform/modules/my_threat_002

Initializing provider plugins...

### Steps to Reproduce

1. create terraformrc
2. add any module from github.com to main.tf
3. terraform plan

### Additional Context

Because of the company policy I serve only internal modules. At the moment we can go and clone module directly from github so I want instead of going to github directly it should go to our registry service and look for the module there.

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
