### ISSUE TITLE
Generate a list of least permissions required to provision a stack in a cloud

### ISSUE THREAD

**Issue by scardena** [hashicorp/terraform#33619]
### Terraform Version

```shell
Any
```

### Use Cases

When creating a resource like:
```
resource "aws_instance" "example_server" {
  ami           = "ami-1234567890"
  instance_type = "t2.micro"
}
```
we know beforehand, just by looking at it, that we at least will need IAM permissions like:
`ec2:ec2:RunInstances, ec2:DescribeImages` and a bunch others like to create sec groups, or read subnets if we are using a existing subnet.
My impression is that all that can be determined statically, without needing to run a plan/apply to figure out we are missing permissions.

### Attempted Solutions

Here there is an "acceptable" solution: https://stackoverflow.com/questions/51273227/whats-the-most-efficient-way-to-determine-the-minimum-aws-permissions-necessary, which is to run the stack with full permissions, and then collect the operations executed, so that we can create the corresponding policy out of what was executed. but the problem with all the attempted solutions, is that you need to apply the stack first.

### Proposal

Create some sort of static analysis tool that can check for all permissions that a stack will require, so that we can generate a list of permissions (that follow the principle of least privilege) to provision a stack *before* applying it (while also considering upgrades and deletes).
I am not aware if this was tried before, or if it's in the roadmap, and what challenges it might present. But this sounds like a critical feature that I can't really grasp yet why is not supported.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
