### ISSUE TITLE
Destroy infrastructure ignoring specific resources

### ISSUE THREAD

**Issue by akumar-99** [hashicorp/terraform#33640]
### Terraform Version

```shell
Terraform v1.5.4
on linux_amd64
```

### Use Cases

I am destroying my whole infrastructure but I want to retain a few resources. 

### Attempted Solutions

All the attempted solutions are wayarounds:
- Commented code
- playing with tfstate file
- manual deleting resource by resource
- All these solutions are difficult to implement on large infrastructure

### Proposal

Something like terraform destroy -ignore-target=xyz will help. SImilarly terraform apply -ignore-target=xyz can help ignore when testing changes.

**Comment by jbardin** [comment]
Hi @akumar-99,

The described issue would be covered by issue #27035, so we can merge this into that feature request.

If you need to do this now, the method would be to use `terraform state rm` to have terraform stop managing the resource instances before destroying the rest of the configuration.

Thanks!
