### ISSUE TITLE
GCP connector - Allow force_destroy on resources in apply stage

### ISSUE THREAD

**Issue by tenstriker** [hashicorp/terraform#33649]
### Terraform Version

```shell
Latest
```

### Use Cases

Currently terraform doesn't allow to replace a gcs bucket or a bigquery dataset if bucket or dataset is non empty. It raises an error that `force_destroy` must be set in order to delete gcs bucket. This is a nice guard. However, to really delete and create new bucket or bigquery dataset it seems I have to do these steps:
1. first set `force_destory` flag, apply it
2. delete the resources by removing from tf config script 
3. recreate resource with desired new configuration

Above causes me 3 code changes and 3 deployments to replace a resources.
Could this flow a simpler as.
1. set `force_destory` flag to true, apply it (internally first owner the flag and destroy the resource, create a new resource with the new config on new config set `force_destroy` to false again)
(if force_destroy is not set then raise an error just like it raises today)

Above means I can only deliberately (non unknowingly) replace the resource but in one code change and in one deployment. 
### Attempted Solutions

Refer use case

### Proposal

Refer use case

**Comment by jbardin** [comment]
Hi @tenstriker,

Thanks for filing the issue. Terraform cannot change how `force_destroy` is handled, that is an attribute of the resource and the behavior is enforced solely by the provider.

Any general solution to Terraform controlling destroy policies would be covered by issue #24658. There is no clear design yet that is either more flexible than the current `prevent_destroy` mechanism, or could avoid the two-step process you mentioned

Thanks!
