### ISSUE TITLE
Repo description and some doc pages still say Terraform is open-source

### ISSUE THREAD

**Issue by chayleaf** [hashicorp/terraform#33667]
### Terraform Version

```shell
none
```

### Affected Pages

https://github.com/hashicorp/terraform

https://developer.hashicorp.com/terraform/intro/terraform-editions

https://developer.hashicorp.com/terraform/intro/vs/custom

### What is the docs issue?

The repo description says (emphasis mine):

> Terraform enables you to safely and predictably create, change, and improve infrastructure. It is an **open source** tool that codifies APIs into declarative configuration files that can be shared amongst team members, treated as code, edited, reviewed, and versioned.

The "Terraform Editions" page claims there is a "Terraform Open Source" edition

The "Terraform vs. Custom Solutions" page says "Furthermore, Terraform is an open source tool"

### Proposal

"Open source" should be removed from the repo description and docs following the switch to a source-available license

**Comment by MikeGlaw** [comment]
🚀 🚀 🚀 🚀 🚀 🚀

**Comment by alisdair** [comment]
Thanks for reporting this!

**Comment by dan-petty** [comment]
Hashicorp has no integrity. That's a bug...

>### Open Source and HashiCorp
>When Mitchell and Armon created their first automation tool projects, they had no idea they would eventually build a company around their ideas. They learned the theory of computer science through university, but the practice of building software and communities through open source software, so making their projects open source was a natural choice. Over time, however, they found a powerful range of additional benefits. In fact, as they built HashiCorp, open source began impacting huge swaths of enterprise computing, and the first few large, profitable open source companies began to emerge. Over the past few years, major innovation in the industry has shifted to open source becoming the dominant way forward for infrastructure providers. We remain committed that the core of our technology will always remain open source.

https://web.archive.org/web/20230609141450/https://www.hashicorp.com/about/open-source
