### ISSUE TITLE
README still says MPL

### ISSUE THREAD

**Issue by JamesJJ** [hashicorp/terraform#33663]
### Terraform Version

```shell
N/A
```

### Affected Pages

https://github.com/hashicorp/terraform/blob/1f011cbaada5bf9cbddadb58ba7c84b223e99467/README.md?plain=1#L48

### What is the docs issue?

README.md line 48 doesn't match LICENSE following recent change ( https://github.com/hashicorp/terraform/commit/b145fbcaadf0fa7d0e7040eac641d9aef2a26433 )

**Comment by liamcervante** [comment]
Thanks for the heads up! Will fix!
