### ISSUE TITLE
backend/s3: Modernization tracking issue

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform#33687]
### Terraform Version

```shell
N/A
```

### Use Cases

The AWS Provider team is undertaking a project to modernize the S3 remote state backend. This will include:

* Using the [AWS SDK for Go v2](https://github.com/aws/aws-sdk-go-v2) instead of [v1](https://github.com/aws/aws-sdk-go)
* Renaming environment variables specific to the backend to not start with `AWS_`, as that namespace is reserved for AWS
* Updating configuration to mirror the AWS Provider

This issue will be used to track the overall project.

### Attempted Solutions

N/A

#### AWS SDK v2

- [x] #30443
- [x] #31244

#### Expanded Auth Configuration

- [x] #30495
- [x] #30479
- [x] #30493
- [x] #30444
- [x] #33689
- [x] #33690
- [x] #33693

#### Expanded Non-Auth Configuration

- [x] #30496
- [x] #30479

#### Consistency with AWS Provider

- [x] #30492
- [x] #30491
- [x] #33688

#### Enhancements

- [x] #30445
- [x] Address #29254" https://github.com/hashicorp/terraform/issues/29254#issuecomment-1716301639
- [x] ~#33686~ Deferred
- [x] #33692

#### Bugs

- [x] #29557
- [x] #29008

**Comment by lorengordon** [comment]
I don't suppose you'd consider adding `credential_process` as a configuration option as well? Similar to https://github.com/hashicorp/terraform-provider-aws/issues/24885

**Comment by gdavison** [comment]
That's a good catch, @lorengordon. In general, we want to support the same authentication configuration methods across the S3 backend and the AWS provider.

I've created #33838

**Comment by gdavison** [comment]
Tasks completed
