### ISSUE TITLE
BSL/BUSL License

### ISSUE THREAD

**Issue by sknight-edgio** [hashicorp/terraform#33685]
### Terraform Version

```shell
main
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

b145fbcaadf0fa7d0e7040eac641d9aef2a26433

### Expected Behavior

License should have stayed the same.

### Actual Behavior

Rug pulled on license to switch it to BSL/BUSL

### Steps to Reproduce

https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license

### Additional Context

https://blog.gruntwork.io/the-future-of-terraform-must-be-open-ab0b9ba65bca

### References

Thank you for making terraform. I have been using it for almost 10 years, and it has been great. It is a shame that it is coming to an end.

**Comment by julian-alarcon** [comment]
Look here for more arguments:
https://opentf.org/

**Comment by dan-petty** [comment]
Hashicorp has no integrity. That's a bug...

```
Open Source and HashiCorp
When Mitchell and Armon created their first automation tool projects, they had no idea they would eventually build a company around their ideas. They learned the theory of computer science through university, but the practice of building software and communities through open source software, so making their projects open source was a natural choice. Over time, however, they found a powerful range of additional benefits. In fact, as they built HashiCorp, open source began impacting huge swaths of enterprise computing, and the first few large, profitable open source companies began to emerge. Over the past few years, major innovation in the industry has shifted to open source becoming the dominant way forward for infrastructure providers. We remain committed that the core of our technology will always remain open source.
```

https://web.archive.org/web/20230609141450/https://www.hashicorp.com/about/open-source

**Comment by dan-petty** [comment]
Hashicorp has no integrity. That's a bug...

>### Open Source and HashiCorp
>When Mitchell and Armon created their first automation tool projects, they had no idea they would eventually build a company around their ideas. They learned the theory of computer science through university, but the practice of building software and communities through open source software, so making their projects open source was a natural choice. Over time, however, they found a powerful range of additional benefits. In fact, as they built HashiCorp, open source began impacting huge swaths of enterprise computing, and the first few large, profitable open source companies began to emerge. Over the past few years, major innovation in the industry has shifted to open source becoming the dominant way forward for infrastructure providers. We remain committed that the core of our technology will always remain open source.

https://web.archive.org/web/20230609141450/https://www.hashicorp.com/about/open-source

**Comment by crw** [comment]
Thanks for your feedback in this thread. For anyone looking for more clarification, please see the blog posts and FAQ:

- https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license
- https://www.hashicorp.com/blog/hashicorp-updates-licensing-faq-based-on-community-questions
- https://www.hashicorp.com/license-faq

Many very specific use cases and questions were raised and answered in this community thread:
- https://discuss.hashicorp.com/t/hashicorp-projects-changing-license-to-business-source-license-v1-1/57106

Thanks again for your feedback and for your contributions.
