### ISSUE TITLE
terraform tries to destroy resource before removing it from a resource that depends on it

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform#33681]
### Terraform Version

```shell
Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.12.0
```

### Terraform Configuration Files

```terraform
provider "aws" {}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t3.micro"
  subnet_id              = data.aws_subnets.default.ids[0]
  vpc_security_group_ids = [one(aws_security_group.sg2[*]).id]

  tags = {
    Name = "BadThings"
  }
}

data "aws_vpc" "default" {
  default = true
}
data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}
data "aws_security_group" "default" {
  name   = "default"
  vpc_id = data.aws_vpc.default.id
}

resource "aws_security_group" "sg1" {
  count = 0

  name   = "first"
  vpc_id = data.aws_vpc.default.id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port       = "22"
    to_port         = "22"
    protocol        = "tcp"
    security_groups = [data.aws_security_group.default.id]
  }
}
resource "aws_security_group" "sg2" {
  count = 1

  name   = "second"
  vpc_id = data.aws_vpc.default.id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port       = "22"
    to_port         = "22"
    protocol        = "tcp"
    security_groups = [data.aws_security_group.default.id]
  }
}

```

### Debug Output

https://gist.github.com/grimm26/f2d7232ec3c72ffed5fde9365e8c385f

### Expected Behavior

remove the security group reference from the aws_instance resource, then destroy the aws_security_group resource.

### Actual Behavior

terraform tries to remove the aws_security_group resource before removing it from the aws_instance and eventually times out.

### Steps to Reproduce

1. terraform init
2. terraform apply
3. change the count on `aws_security_group.sg1` to 1, change the count on `aws_security_group.sg2` to 0
4. change the parameter value in `aws_instance.web` `vpc_security_group_ids` to refer to sg1 instead of sg2
5. terraform apply

### Additional Context

This is a simplification of what is happening to my actual config to illustrate the problem.

**Comment by jbardin** [comment]
Hi @grimm26,

The default replacement ordering in Terraform is always to destroy then create/update resources. In order for the update to the `aws_instance` before the `aws_security_group` is destroyed, the security group must use the `create_before_destroy` option. If the resource should be able to detect this situation and error out sooner, an issue should be filed with the provider.

See also #31309.

Thanks!

**Comment by grimm26** [comment]
> Hi @grimm26,
> 
> The default replacement ordering in Terraform is always to destroy then create/update resources. In order for the update to the `aws_instance` to happen before the `aws_security_group` is destroyed, the security group must use the `create_before_destroy` option. If the resource should be able to detect this situation and error out sooner, an issue should be filed with the provider.
> 
> See also #31309.
> 
> Thanks!

So I need cut a new release of a module to add the create_before_destroy lifecycle rule to the security group that I want to delete (and never create), push that out and aplpy it everywhere that it is used, and then cut another release to replace the security group as intended? You don't think it is a bug that the graphing algo doesn't pick up that it shouldn't delete an object while a reference to that object still exists? weak.

**Comment by jbardin** [comment]
@grimm26, the graphing algorithm is not involved here, the order of operations is strictly defined based on the configuration and needs to be adhered to for consistency. The fact that the actual `aws_instance` maintains an internal reference to the `aws_security_group` and prevents it's removal is something that Terraform cannot see from the configuration alone. This is called out in the documentation for the [`aws_security_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group):

> Normally, Terraform first deletes the existing security group resource and then creates a new one. When a security group is associated with a resource, the delete won't succeed. You can invert the default behavior using the [create_before_destroy meta argument](https://www.terraform.io/language/meta-arguments/lifecycle#create_before_destroy):

 We have acknowledged that this poses a usability issue, and there are some open issues (like the one linked) explaining the situation and tracking the possibility of future enhancements which may help Terraform adapt to different resource behaviors, or guide users in writing the correct configuration.
