### ISSUE TITLE
Replace function cannot do single backslash

### ISSUE THREAD

**Issue by moontune** [hashicorp/terraform#33708]
### Terraform Version

```shell
Terraform v1.5.5
on linux_amd64
```

### Terraform Configuration Files

```terraform
variable "share_ip" {
  default = "123.123.123.123"
}

variable "share_path" {
  default = "/file-share"
}

output "full_path_no_convert" {
  value = "${var.share_ip}${var.share_path}"
}

output "full_path_no_convert_with_leading_backslashes" {
  value = "\\${var.share_ip}${var.share_path}"
}

output "full_path_convert_backslash" {
  value = "\\\\${var.share_ip}${replace(var.share_path, "/", "\\")}"
}

#Below does not run. attempts to escape quote instead
# output "full_path_backslash_broken" {
#     value = "\\${var.share_ip}${replace(var.share_path, "/", "\")}"
# }
```

### Debug Output

NA

### Expected Behavior

It should be possible to replace a substring within a string, with an individual backslash. 
Output of `full_path_convert_backslash`  should be `"\\123.123.123.123\file-share"` if backslashes were being escaped.
or
Output  of `full_path_backslash_broken` should be `"\\123.123.123.123\file-share"` if backslashes are not to be escaped.

Would expect backslashes to be handled the same as other special characters.

### Actual Behavior

`full_path_no_convert = "123.123.123.123/file-share"`
`full_path_no_convert_with_leading_backslashes = "\\123.123.123.123/file-share"`
`full_path_convert_backslash = "\\\\123.123.123.123\\file-share"`

Running `terraform apply` with `full_path_backslash_broken` Output uncommented results in errors: 

│ Error: Missing argument separator
│ 
│   on replace.tf line 24, in output "full_path_backslash_broken":
│   23:     value = "\\${var.share_ip}${replace(var.share_path, "/", "\")}"
│   24: }
│ 
│ A comma is required to separate each function argument from the next.
╵
╷
│ Error: Invalid multi-line string
│ 
│   on replace.tf line 24, in output "full_path_backslash_broken":
│   24: }
│ 
│ Quoted strings may not be split over multiple lines. To produce a multi-line string, either use the \n escape to represent a newline character or
│ use the "heredoc" multi-line template syntax.

### Steps to Reproduce

1. Save the configuration file as .tf file
2. Run `terraform init`
3. Run `terraform apply`
Outputs will be as described in behaviour.
4. Uncomment `full_path_backslash_broken` Output
5. Run `terraform apply`
Errors for "Missing argument separator" and "Invalid multi-line string" will be returned.

### References

This appears to be linked to the closed issue #8709 
and https://github.com/hashicorp/hcl/pull/150

**Comment by jbardin** [comment]
Hi @moontune,

A backslash is also the escape character within a quoted string, so it itself must be escaped. Your `full_path_convert_backslash` example is replacing the single forward slash with a single backslash. The `full_path_backslash_broken` is invalid because the backslash is escaping the double quote, so the string is not closed. 

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by moontune** [comment]
Hi @jbardin thanks for your reply. Unfortunately, I may not have explained this very well. With my `full_path_convert_backslash` example I would expect, as you say, the single forward slash to be replaced with a single backslash. However, this is not the case, if you run the example you will see that the result is `"\\\\123.123.123.123\\file-share"` and not `"\\123.123.123.123\file-share"` which you would expect if it was being properly escaped. This is not a question per se. but appears to be a bug.

**Comment by jbardin** [comment]
The result of your `replace` call contains exactly 1 backslash. The entire string `"\\\\123.123.123.123\\file-share"` contains a total of 3 backslashes, which all must be properly escaped to be valid within a quoted string, but the underlying data is still `\\123.123.123.123\file-share`.

**Comment by moontune** [comment]
Hi @jbardin. Thanks again for your reply. I can see now that I will have to run `terraform output -raw full_path_convert_backslash` to see my required output.
