### ISSUE TITLE
feature req: allow references to non-computed attributes

### ISSUE THREAD

**Issue by br0ch0n** [hashicorp/terraform#3370]
Use case:
similar to the various tickets that would like to do separate EIP associations, I'd like to be able to reference my private_ip earlier.  For example, I'd like to be able to create a route53 record with the private ip of my aws_instance BEFORE I create the aws_instance.  I however cannot create such a dependency without creating a cycle.  I'm statically assigning the private_ip to the aws_instance so the data is available ahead of time. Perhaps allow direct access to another resources arguments vs just their attributes?  I can of course use a var to store the value and reference it however I like, but I was thinking that it might be nice to be able to skip a step.

**Comment by phinze** [comment]
Interesting idea, @br0ch0n.

Making sure I understand correctly - you can reference these values currently, but that creates a dependency between resources. You're looking for a way to reference the value without creating the dependency link?

**Comment by br0ch0n** [comment]
Yaa, that was the idea.  I mean, it's not a big deal because I should be using an external var for such things anyway, but still there might be some cases where this could be useful.

**Comment by phinze** [comment]
Revisiting this, I believe that it's a better solution to just refactor to use a variable. That's a more correct expression of the reference.

Feel free to follow up if you disagree and we can continue to discuss. :+1:
