### ISSUE TITLE
Feature to change default local route which comes with Route Table.

### ISSUE THREAD

**Issue by ankushpadmawar** [hashicorp/terraform#33709]
### Terraform Version

```shell
Terraform v0.13.7
```

### Use Cases

We want to edit and change default route which comes automatically with route table when we create it using Resource "resource aws_route_table"
default route is ==> VPC CIDR Routing to Local

We want to edit this route and change target to "gateway load balancer endpoint" Which is our AWS Network Firewall endpoint.

### Attempted Solutions

We tried to add new route after the route table creation, but it says Route with VPC CIDR is already available and we cannot modify it.

I also searched for documentation, but I can't find any.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
