### ISSUE TITLE
module import using variables

### ISSUE THREAD

**Issue by medusaalb** [hashicorp/terraform#33727]
### Terraform Version

```shell
1.5.5
```

### Use Cases

using this is a more comfortable than use a "id" in  code

### Attempted Solutions

 using this is a more comfortable than use a "id" in  code

### Proposal

use module import like this (using vars)
import {
    to = aws_subnet.addtags
    id = var.vpc_vpc_id
}
note: vars gets from a variables.tfvars

**Comment by jbardin** [comment]
Duplicate of #33228
