### ISSUE TITLE
not able to unlock terraform state file 

### ISSUE THREAD

**Issue by megha288** [hashicorp/terraform#33725]
### Terraform Version

```shell
Error: Backend initialization required, please run "terraform init"
│
│ Reason: Initial configuration of the requested backend "s3"
│
│ The "backend" is the interface that Terraform uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ Terraform configuration you're using is using a custom configuration for
│ the Terraform backend.
│
│ Changes to backend configurations require reinitialization. This allows
│ Terraform to set up the new configuration, copy existing state, etc. Please run
│ "terraform init" with either the "-reconfigure" or "-migrate-state" flags to
│ use the current configuration.
│
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

terraform force-unlock LOCKID

### Expected Behavior

it should unlock state file using force-unlock 

### Actual Behavior

but its always asking for backend init although I have done it .

### Steps to Reproduce

terraform plan

### Additional Context

no

### References

no

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
