### ISSUE TITLE
azurerm_cosmosdb_postgresql_cluster - polling after Create: unmarshalling response body

### ISSUE THREAD

**Issue by selvaganesh-gopal** [hashicorp/terraform#33728]
### Terraform Version

```shell
terraformVersion: 1.5.5
cdktfVersion: 0.17.1
```

### Terraform Configuration Files

```terraform
...terraform config...
```

        new CosmosdbPostgresqlCluster(this, 'cpsql', {
            name: "psql",
            location: "East US",
            resourceGroupName: "Vennila",
            administratorLoginPassword: "****",
            coordinatorStorageQuotaInMb: "873934",
            coordinatorVcoreCount: 4,
            nodeCount:0,
        });

### Debug Output

polling after Create: unmarshalling response body: parsing time "2023-07-13 06:10:30 +0000" as "2006-01-02T15:04:05Z07:00": cannot parse " 06:10:30 +0000" as "T"

### Expected Behavior

It needs to create the cosmos postgresSQL cluster in Azure 

### Actual Behavior

polling after Create: unmarshalling response body: parsing time "2023-07-13 06:10:30 +0000" as "2006-01-02T15:04:05Z07:00": cannot parse " 06:10:30 +0000" as "T"

### Steps to Reproduce

terraform init
terraform apply

**Comment by apparentlymart** [comment]
Hi @selvaganesh-gopal,

I think you are describing a behavior of [the `azurerm_cosmosdb_postgresql_cluster` resource type](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_postgresql_cluster), which is part of the `hashicorp/azurerm` provider and not implemented in Terraform Core (this codebase).

Please open an issue in [the provider's own repository](https://github.com/hashicorp/terraform-provider-azurerm) to report this. Thanks!
