### ISSUE TITLE
Change the way of how destroy on deletion_protection enabled resources works

### ISSUE THREAD

**Issue by zculek-fb** [hashicorp/terraform#33732]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_amd64
```

### Use Cases

When destroy is applied to a Google Cloud SQL instance that has `deletion_protection` and/or `deletion_protection.enabled` set to `true`, the way it works now is that Terraform first runs a destroy on (child) resources of the Cloud SQL instance, such as user, database, etc., and when the destroy process reaches the instance itself, it fails due to `deletion_protection` being enabled.

I think the database itself is much more worth to be protected from deletion than the instance itself - the instance can easily be recreated, in a matter of minutes, but if the database is deleted and it's hundreds of GBs big, restoring from a backup could take quite some time. Since at the moment there is no way to set deletion_protection on the database itself, I suggest adding some kind of flag or an if condition or a check that would first check if deletion_protection on the instance is enabled or not, and if it is, skip deleting any of the instance resources (database, user) instead and throwing an error immediately. That would actually be much better workflow, because if deletion_protection is enabled on purpose, it was most probably done in an effort to prevent losing the database.

### Attempted Solutions

There is an option to set deletion_policy to ABANDON, but it is not the proper solution to this issue, not even a dirty workaround. If a parent resource has deletion_protection enabled, child resources shouldn't be attempted to be deleted at all in case destroy was called for a parent resource.

### Proposal

How it works now (deleting resources which are part of deletion_protection enabled instance):
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
module.mysql_db.google_sql_user.default[0]: Destroying... [id=csql//csql]
module.mysql_db.google_sql_database.default[0]: Destroying... [id=projects/myproj-staging/instances/csql/databases/csql]
module.mysql_db.google_sql_user.default[0]: Destruction complete after 1s
module.mysql_db.random_password.user-password: Destroying... [id=none]
module.mysql_db.google_sql_database_instance.replicas["csql-replica"]: Destroying... [id=csql-read-replica]
module.mysql_db.random_password.user-password: Destruction complete after 0s
module.mysql_db.google_sql_database.default[0]: Destruction complete after 2s
╷
│ Error: Error, failed to delete instance because deletion_protection is set to true. Set it to false to proceed with instance deletion
│
│
```

Desired (don't delete any of the resources, throw an error immediately):
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
╷
│ Error: Error, failed to delete instance because deletion_protection is set to true. Set it to false to proceed with instance deletion
│
│
```

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by zculek-fb** [comment]
Hello,

Thanks for checking into this.

Is this really a provider issue? Because, Terraform execution is not controlled by providers. And I only gave an example of this being the case with one provider, but this happens with other providers as well, as it's about Terraform execution with all of the parent+child resources. If you take some other provider and a parent resource that has child resources + deletion protection enabled, you will see that the same thing is happening - child resources are being destroyed even though parent has deletion protection, and then at one point destroy fails when Terraform execution hits `deletion_protection = enabled/true`.

Isn't it logical to check for the deletion_protection status before any destroy happens and then not destroy any child resources if deletion_protection is set to true? If someone wants to prevent destruction of the parent resources, they probably also want to prevent the destruction of it's child resources as well (especially in the cases where data is involved, such as SQL databases, etc.).

**Comment by jbardin** [comment]
Hi @zculek-fb,

Terraform cannot control this behavior, because Terraform does not know what `deletion_protection` means. As a human you can read it and take a guess, but to Terraform it is only one of many attributes in the resource configuration, which could mean many things and is handled entirely by the provider implementation. Another aspect of this is that at the point of destroying a resource, there is no configuration to evaluate. Since the configuration declares the desired state of the system, and may not even exist or align with the current state of the system when destroying a resource, destruction must be accomplished entirely without configuration. It is up to the provider to store the necessary information and plan how resources are destroyed. Hidden dependencies between resources in the remote system can be difficult for providers to model at times, but providers are the only ones with access to the APIs to begin to determine what those dependencies might be.

**Comment by zculek-fb** [comment]
Hello James,

Thank you for taking the time and providing a detailed answer.
