### ISSUE TITLE
The terraform-provider-google-beta_v4.79.0_x5 plugin crashed! 

### ISSUE THREAD

**Issue by yaroslavopsguru** [hashicorp/terraform#33759]
### Terraform Version

```shell
Terraform v1.5.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.79.0
+ provider registry.terraform.io/hashicorp/google-beta v4.79.0
```

### Terraform Configuration Files

```

module "composer" {
  source  = "terraform-google-modules/composer/google//modules/create_environment_v2"
  version = "3.4.0"
  composer_env_name                         = var.composer_env_name
  network                                   = var.network
  project_id                                = var.project_id
  network_project_id                        = var.network_project_id
  region                                    = var.region
  subnetwork                                = var.composer_subnet
  airflow_config_overrides                  = var.airflow_config_overrides
  cloud_composer_connection_subnetwork      = var.composer_subnet
  cloud_composer_network_ipv4_cidr_block    = var.cloud_composer_network_ipv4_cidr_block
  cloud_sql_ipv4_cidr                       = var.cloud_sql_ipv4_cidr
  composer_service_account                  = var.composer_service_account
  enable_ip_masq_agent                      = var.enable_ip_masq_agent
  enable_private_endpoint                   = var.enable_private_endpoint
  env_variables                             = var.env_variables
  environment_size                          = var.environment_size
  grant_sa_agent_permission                 = var.grant_sa_agent_permission
  image_version                             = var.image_version
  labels                                    = var.labels
  maintenance_end_time                      = var.maintenance_end_time
  maintenance_recurrence                    = var.maintenance_recurrence
  maintenance_start_time                    = var.maintenance_start_time
  master_authorized_networks                = var.master_authorized_networks
  master_ipv4_cidr                          = var.master_ipv4_cidr
  pod_ip_allocation_range_name              = var.pod_ip_allocation_range_name
  service_ip_allocation_range_name          = var.service_ip_allocation_range_name
  pypi_packages                             = var.pypi_packages
  scheduler                                 = var.scheduler
  web_server                                = var.web_server
  worker                                    = var.worker
  subnetwork_region                         = var.region
  tags                                      = var.tags
  use_private_environment                   = var.use_private_environment
  web_server_allowed_ip_ranges              = var.web_server_allowed_ip_ranges
}
```

### Debug Output

https://gist.github.com/yaroslavopsguru/cf947fe4666655a12670efc5bfc147ea

### Expected Behavior

composer resources created

### Actual Behavior

**Error: Plugin did not respond**
│
│   with module.composer_v2.module.composer.google_composer_environment.composer_env,
│   on .terraform/modules/composer_v2.composer/modules/create_environment_v2/main.tf line 27, in resource "google_composer_environment" "composer_env":
│   27: resource "google_composer_environment" "composer_env" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-google-beta_v4.79.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 29 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/composer.expandComposerEnvironmentConfigMaintenanceWindow({0x3f19be0?, 0xc001a6dcc8?}, 0x4797c82?, 0x12?)
	github.com/hashicorp/terraform-provider-google-beta/google-beta/services/composer/resource_composer_environment.go:1813 +0x1f1
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/composer.expandComposerEnvironmentConfig({0x3f19be0?, 0xc001a6dea8?}, 0xc001224f50?, 0x6d?)
	github.com/hashicorp/terraform-provider-google-beta/google-beta/services/composer/resource_composer_environment.go:1660 +0x5de
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/composer.resourceComposerEnvironmentCreate(0xc001ab4080, {0x47446e0?, 0xc000546000})
	github.com/hashicorp/terraform-provider-google-beta/google-beta/services/composer/resource_composer_environment.go:880 +0xef
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x4ed5338?, {0x4ed5338?, 0xc001466000?}, 0xd?, {0x47446e0?, 0xc000546000?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000d8bce0, {0x4ed5338, 0xc001466000}, 0xc001a48680, 0xc001a33e00, {0x47446e0, 0xc000546000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000f06e40, {0x4ed5338?, 0xc001461ec0?}, 0xc00137e000)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000ea78c0, 0xc000ea7920, {0xc00100e560, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000ef8280, {0x4ed5338?, 0xc001460d20?}, 0xc0019b7960)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x46b2e00?, 0xc000ef8280}, {0x4ed5338, 0xc001460d20}, 0xc0019b78f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00109e000, {0x4ede980, 0xc000d6f040}, 0xc001a1ed80, 0xc000fa6ff0, 0x67f3c60, 0x0)
	google.golang.org/grpc@v1.56.2/server.go:1337 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc00109e000, {0x4ede980, 0xc000d6f040}, 0xc001a1ed80, 0x0)
	google.golang.org/grpc@v1.56.2/server.go:1714 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.2/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.2/server.go:957 +0x18c

Error: The terraform-provider-google-beta_v4.79.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by liamcervante** [comment]
Hi @yaroslavopsguru! Thanks for filing this and sorry for the crash!

Terraform providers are managed within their own dedicated repositories. For this issue I think that would be within https://github.com/hashicorp/terraform-provider-google-beta.

Unfortunately I don't have the required permissions to transfer this automatically. As such, I will close this issue on our board, and would encourage you to reopen it within the google-beta repository.

Thanks again!
