### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by nall1** [hashicorp/terraform#33767]
### Terraform Version

```shell
Terraform v1.3.9
on windows_amd64
```

### Terraform Configuration Files

version: 0.2
env:
  shell: bash
  variables:
    aws_region: us-east-1
    TFENV_TERRAFORM_VERSION: "1.1.9"
    lock_state: true
    TF_INPUT: false
    TF_CLI_ARGS: "-no-color"
    TF_IN_AUTOMATION: true
    # TF_LOG: INFO # TRACE, DEBUG, INFO, WARN or ERROR
    SCRIPTS: ".github/workflows/scripts"
    BACKEND_ROLE: "********"
    PROD_SHARED_ROLE: "*******"
phases:
  install:
    runtime-versions:
        python: "3.7"
    commands:
      - PATH=$PATH:`pwd`
      - git clone ***********
      - export PATH="$HOME/.tfenv/bin:$PATH"
      - tfenv install && tfenv use 
      - wget -q *********
      - mv jq-linux64 jq
      - chmod +x jq
      - aws s3 cp --region=us-east-1 s3*********
      - chmod +x .github/workflows/scripts/parse.py
  pre_build:
    commands:
      - ls -lah
      - pwd
  build:
    commands:
      - bash $SCRIPTS/assumeRole.sh
      - cd terraform/
      
      - terraform init -backend-config='profile=backend'
      - terraform workspace new $ENV_NAME | true
      - terraform workspace select $ENV_NAME
      - terraform workspace list
      - ls -lah
      - terraform fmt -check
      - terraform validate
      - terraform plan -out="$ENV_NAME-tfplan" -var-file="./env/$ENV_NAME.tfvars" 2>&1 | tee -a terraform.plan
      - terraform apply -auto-approve "$ENV_NAME-tfplan" 2>&1 | tee -a terraform.apply
  post_build:
    commands:
      - bash ../$SCRIPTS/parse-tf-output.sh

### Debug Output

Error: Provider produced inconsistent result after apply

When applying changes to
snowflake_procedure_grant.P_PIPELINE_ADMIN,
provider "provider[\"registry.terraform.io/snowflake-labs/snowflake\"]"
produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Expected Behavior

should create proc in snowflake with admin role

### Actual Behavior

Error: Provider produced inconsistent result after apply

When applying changes to
snowflake_procedure_grant.P_GET_SALESFORCE_DATA_TO_PUSH_GRANT_PIPELINE_CRM_ADMIN,
provider "provider[\"registry.terraform.io/snowflake-labs/snowflake\"]"
produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

      - cd terraform
      - terraform init -backend-config='profile=backend'
      - terraform workspace new $ENV_NAME | true
      - terraform workspace select $ENV_NAME
      - terraform workspace list
      - ls -lah
      - terraform fmt -check
      - echo "::endgroup::"
      - terraform validate
      - terraform plan -out="$ENV_NAME-tfplan" -var-file="./env/$ENV_NAME.tfvars" 2>&1 | tee -a terraform.plan
      - terraform apply -auto-approve "$ENV_NAME-tfplan" 2>&1 | tee -a terraform.apply

**Comment by apparentlymart** [comment]
Hi @nall1,

As mentioned in the error message, this error is describing a bug in the `snowflake-labs/snowflake` provider rather than in Terraform Core itself. Please report this issue in [the Snowflake provider's own repository](https://github.com/snowflake-labs/terraform-provider-snowflake) instead, so that the provider maintainers can review it.

What you've described here might be the same problem as discussed in https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/754, but I'm not familiar enough with this provider to know if the `snowflake_database_grant` resource type and the `snowflake_procedure_grant` resource types share the same implementation.
