### ISSUE TITLE
Support for Refactoring

### ISSUE THREAD

**Issue by jasonkuhrt** [hashicorp/terraform#3376]
After using terraform for around ten days and discussing different features/workflows with various people in IRC it has become clear that there is no support for refactoring in Terraform. Quote:

> 09:47 jedineeper: jasonkuhrt: painful :) very painful :)
– @jedineeper

The suggestions I got were:

1. "tear it down and redeploy it in the new module/code"
2. "spent a lot more time on a whiteboard sketching out dependencies"
3. "hacking out some tfstate"

All essentially unacceptable. Even 2 which sounds reasonable is not an admissible replacement for plainly missing refactoring features.

The main issue I have run into is that when I encapsulate (a) resource(s) into a module terraform is unable to resolve the existing state with the new graph.

**Comment by phinze** [comment]
Hi there - totally agreed that the current state of the world is unacceptable. We've been discussing this over in #591 - check out the ideas for features to help support refactoring over there.

Closing this to keep the conversation rooted over there - feel free to join in!

**Comment by jasonkuhrt** [comment]
Ah thanks! Sorry for the dupe.
