### ISSUE TITLE
Post `terraform destroy` errors

### ISSUE THREAD

**Issue by jasonkuhrt** [hashicorp/terraform#3377]
I'm using Atlas to manage state. After running `terraform destroy` locally I finish with the error pasted below. The actual destruction appears to complete so I'm not sure what this error is all about. What's going on? Seems like a bug to me.

```
Error applying plan:

8 error(s) occurred:

* Resource 'aws_elb.service' does not have attribute 'id' for variable 'aws_elb.service.id'
* Resource 'aws_elb.service' does not have attribute 'dns_name' for variable 'aws_elb.service.dns_name'
* Resource 'aws_elb.service' does not have attribute 'id' for variable 'aws_elb.service.id'
* Resource 'aws_elb.service' does not have attribute 'dns_name' for variable 'aws_elb.service.dns_name'
* Resource 'aws_elb.service' does not have attribute 'dns_name' for variable 'aws_elb.service.dns_name'
* Resource 'aws_elb.service' does not have attribute 'id' for variable 'aws_elb.service.id'
* Resource 'template_file.cloud_config' does not have attribute 'rendered' for variable 'template_file.cloud_config.rendered'
* Resource 'template_file.cloud_config' does not have attribute 'rendered' for variable 'template_file.cloud_config.rendered'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by radeksimko** [comment]
Can you provide a config used (minus any secrets), so we can reproduce it?

I think it may be related to https://github.com/hashicorp/terraform/issues/2892

**Comment by jasonkuhrt** [comment]
@radeksimko The config is very large and spans many files. Would be difficult to dump as text here and I do not think I can give you access to our private repo. Is there a subset of the configuration that would be useful?

**Comment by radeksimko** [comment]
@jasonkuhrt I just merged #3393 , would you mind pulling down the latest version, building from source and confirming that it has fixed the issue?

**Comment by jasonkuhrt** [comment]
I will try this Monday.

**Comment by jasonkuhrt** [comment]
@radeksimko To avoid fumbling around can you explain or link me to instructions for building from source.

**Comment by radeksimko** [comment]
@jasonkuhrt Try following this part of the readme: https://github.com/hashicorp/terraform#developing-terraform

**Comment by josephholsten** [comment]
I'd like to mention I've been having this `Resource 'foo' does not have attribute 'id' for variable 'foo.id'` issue quite a bit recently. It's being a complete pain trying to create a minimal reproduction case. At this point, I can only reliably reproduce it with a module which passes a computed variable into a sub-module, and with a tfstate which is inaccurate (by destroying resources or creating conflicting resources). I'm getting closer, but it's going to take a bit.

**Comment by josephholsten** [comment]
oh, I should mention that it not only locks up this way with `terraform destroy` but also with `terraform plan` and `terraform refresh`.

**Comment by jasonkuhrt** [comment]
@radeksimko HEAD seems to have fixed this:

```
❯ ~/go/src/github.com/hashicorp/terraform/bin/terraform destroy
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

[...]

Apply complete! Resources: 0 added, 0 changed, 15 destroyed.
```

**Comment by radeksimko** [comment]
@jasonkuhrt Thanks for testing it! I will close this one then.

@josephholsten Can you please create a new issue and attach a reproduction case?
