### ISSUE TITLE
`terraform test` crash on multiple run blocks in file

### ISSUE THREAD

**Issue by matt-FFFFFF** [hashicorp/terraform#33780]
### Terraform Version

```shell
❯ t version
Terraform v1.6.0-beta1
on linux_amd64
+ provider registry.terraform.io/azure/azapi v1.9.0
+ provider registry.terraform.io/hashicorp/azurerm v3.71.0
```

### Terraform Configuration Files

```terraform
# HINT: make sure to run `terraform init` in this directory before running `terraform test`

# Default variable values (can be overridden inside the `run` block)
variables {
  subscription_alias_enabled = true
  subscription_alias_name    = "my-subscription-alias"
  subscription_billing_scope = "/providers/Microsoft.Billing/billingAccounts/0000000/enrollmentAccounts/000000"
  subscription_display_name  = "test-subscription-alias"
  subscription_workload      = "Production"
}

# Stop Terraform moaning about the provider not being configured
provider "azurerm" {
  features {}
}


# Example of basic test checking resource values against input variables
run "basic_valid" {
  command = plan

  assert {
    condition     = azurerm_subscription.this[0].alias == var.subscription_alias_name
    error_message = "Subscription alias name is not correct"
  }

  assert {
    condition     = azurerm_subscription.this[0].billing_scope_id == var.subscription_billing_scope
    error_message = "Subscription billing scope not correct"
  }

  assert {
    condition     = azurerm_subscription.this[0].subscription_name == var.subscription_display_name
    error_message = "Subscription name is not correct"
  }

  assert {
    condition     = azurerm_subscription.this[0].workload == var.subscription_workload
    error_message = "Subscription workload is not correct"
  }
}

# Example of chekiang failure on variable validation
run "expect_failure_invalid_billing_scope" {
  command = plan

  # Create an invalid billing account scope
  variables {
    subscription_billing_scope = "/providrs/Microft.Billing/billingAccouts/0000000/enrollmencounts/000000"
  }

  expect_failures = [
    var.subscription_billing_scope,
  ]
}
```

### Debug Output

https://gist.github.com/matt-FFFFFF/629b3fa191f3618b07c0d32a628c01c8

### Expected Behavior

Not crash!

### Actual Behavior

Crashed when both run blocks are in the test file.

Either one works on its own.

### Steps to Reproduce

1. terraform init
2. terraform test

### Additional Context

Link to sub-module: https://github.com/Azure/terraform-azurerm-lz-vending/tree/spike/terraformtest/modules/subscription

**Comment by liamcervante** [comment]
Hi @matt-FFFFFF! Thanks for this and sorry for the crash.

Do you have the crash stack trace available to share? I will try and reproduce this as well, but that might speed things up.

Thanks!

**Comment by liamcervante** [comment]
Thanks for that super helpful! 

So the crash is originating here: https://github.com/hashicorp/terraform/blob/main/internal/backend/local/test.go#L1348

It's caused by the outputs you have defined that are returning null. Terraform is just not including them in the set of outputs and the test file is expecting them to be there as it is looking in the config.

This is definitely a bug, so we'll get it fixed for the next beta release. Thanks for finding it.

**Comment by matt-FFFFFF** [comment]
Thanks for confirming. Any idea why it doesn't happen with only one of the `run` blocks?

Appreciate the speedy response :)

**Comment by liamcervante** [comment]
Yes - Terraform attempts to make the outputs of all the previous run block available to each run block as it executes. If there is only a single run block then it never has any previous run blocks to process, and so it never encounters the `null` output values that are causing the crash.

**Comment by liamcervante** [comment]
This should be fixed in the next beta release!
