### ISSUE TITLE
Open up GitHub Discussions, extending the discuss.hashicorp.com

### ISSUE THREAD

**Issue by devjiwonchoi** [hashicorp/terraform#33798]
### Terraform Version

```shell
Feature Request
```

### Use Cases

Since GitHub provides a handy feature Discussion, it would open up a better approach to the users and contributors, with more options to get help.

### Attempted Solutions

Open up a Discussion section on the GitHub repo

**Comment by crw** [comment]
Thanks for this request! We are constantly re-evaluating our use of the various features of GitHub. Before Discussions existed, we created [a community forum](https://discuss.hashicorp.com/c/terraform-core/27) which has been in use for many years. Please use the forum as a place to have discussions. I am going to close this issue as it is not an issue with Terraform the project but more about how we manage the conversations around the project, which is better handled in the discussion forum. Thanks again!
