### ISSUE TITLE
Discrepancy in Provider Schema Json and User Documentation

### ISSUE THREAD

**Issue by Vegas588** [hashicorp/terraform#33808]
### Terraform Version

```shell
Terraform v1.5.6
on linux_amd64
```

### Affected Pages

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/.release/provider-schema.json && https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/image

### What is the docs issue?

In reviewing the latest version (3.71.0) of the azurerm_image resource, I've identified a discrepancy between the provider-schema.json file and the official documentation. Specifically, the documentation indicates that both os_disk and data_disk blocks can have "one or more" instances. This suggests that users can define multiple blocks for each argument.

However, upon examining the provider-schema.json file for azurerm_image, I observed that the JSON configuration specifies maxItems: 1 for os_disk and does not include any item constraints for data_disk. According to the documentation, I would expect to see minItems: 1 for both blocks to reflect the "one or more" guidance.

Could you please confirm whether the maxItems or minItems attributes are indeed intended to set the number of allowable instances for these blocks? Alternatively, are these attributes used for a different purpose altogether?

### Proposal

Please provide clarification or verification of minItems and maxItems elements in provider-schema.json file.

**Comment by apparentlymart** [comment]
Hi @Vegas588,

The schema and documentation you are referring to both belong to the `hashicorp/azurerm` provider rather than to Terraform Core itself, so please report this issue in [the Azure provider repository](https://github.com/hashicorp/terraform-provider-azurerm) instead. That will make the feedback visible to the team which maintains that provider.

Thanks!
