### ISSUE TITLE
Add support for new Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by jasonwilk** [hashicorp/terraform#3381]
Being able to configure AES clusters using terraform would save me a ton of time configuring elasticsearch servers and cluster management.

https://aws.amazon.com/blogs/aws/new-amazon-elasticsearch-service/

**Comment by stack72** [comment]
This hasn't been added to the AWS-Go-SDK yet

https://github.com/aws/aws-sdk-go/tree/master/apis

It is the first thing I thought about when I saw the announcement

**Comment by radeksimko** [comment]
I just opened https://github.com/aws/aws-sdk-go/issues/395

**Comment by stack72** [comment]
Nice one @radeksimko - nice to see the repo starting to get active again after the conference :)

**Comment by rlister** [comment]
Looks like it was added :-)
https://github.com/aws/aws-sdk-go/releases/tag/v0.9.11

**Comment by nickschuch** [comment]
I might give this one a go! Fork!

**Comment by radeksimko** [comment]
@nickschuch You may want to know I started working on this and it's very close to a PR :wink: 
https://github.com/hashicorp/terraform/compare/master...TimeIncOSS:f-aws-es

I will submit that in a few days hopefully.
