### ISSUE TITLE
terraform providers lock should use the plugin cache

### ISSUE THREAD

**Issue by markusheiden** [hashicorp/terraform#33837]
### Terraform Version

```shell
Terraform v1.5.6
```

### Use Cases

Provider maintenance: Regular updates.

We have many workspaces and we use multiple architectures:
- macOS amd64 and arm64 for local development.
- Windows amd64 for local development.
- Linux amd64 for the CI.

Updating the `.terraform.lock.hcl` of a workspace via `terraform providers lock -platform=darwin_arm64 -platform=darwin_amd64 -platform=linux_amd64 -platform=windows_amd64` takes very long.
For all of the workspaces, the hashes (even of the not modified providers) are retrieved over and over from the registry.
So this "penalty" even multiplies.

Recently, the repeated downloads even fail: E.g. 
```
Error: Could not retrieve providers for locking
Terraform failed to fetch the requested providers for darwin_arm64 in order to calculate their checksums: some providers could not be installed:
- registry.terraform.io/gitlabhq/gitlab: github.com: Get "https://github.com/gitlabhq/terraform-provider-gitlab/releases/download/v16.3.0/terraform-provider-gitlab_16.3.0_darwin_arm64.zip": dial tcp 140.82.121.3:443: i/o timeout.
```
Downloading the file with the browser is no problem.

### Attempted Solutions

I configured the plugin cache. But it is not used by `terraform providers lock`.

### Proposal

Let `terraform providers lock` use the plugin cache (read & write). That includes caching plugins of all architectures.

### References

- #29958 is very similar

**Comment by crw** [comment]
Thanks for this feature request! 

If you are viewing this issue and would like to indicate your interest, please use the 👍 reaction on the issue description to upvote this issue. We also welcome additional use case descriptions. Thanks again!

**Comment by jsyrjala** [comment]
Yesterday running `terraform providers lock -platform=darwin_amd64 -platform=darwin_arm64 -platform=linux_amd64 -platform=windows_amd64`  on one terraform stack took 56 minutes, because dowloading aws provider from https://releases.hashicorp.com/  was so slow. I have several stacks, which each have mostly identical plugins and plugin versions. 

So for each of `terraform providers lock` commands is downloading exact same files and takes from 20 minutes 50 minutes per command to do that.

**Comment by jsyrjala** [comment]
Related https://github.com/hashicorp/terraform/issues/27811

**Comment by davidgwps** [comment]
I would love this improvement, we also take a long to regenerate the lock files using the same command as @jsyrjala. I would love to run the `provider locks` command in CI so I can ensure locks are up to date and latest are checked in with pull requests as we get CI failures when people have forgotten. It's too slow to run across the folder structure every time.
