### ISSUE TITLE
CLI dash conventions?

### ISSUE THREAD

**Issue by jasonkuhrt** [hashicorp/terraform#3386]
I'm disconcerted by and perturbed by the CLI's use of single-dashes for long flags such as:

```
terraform plan -destroy
```

I would feel more more at ease if we had:

```
terraform plan --destroy
```

Maybe I'm a black sheep here but I was quite surprised to see this given most modern communities and projects seem to have gone the route of `-a` and `--alpha`.

**Comment by mitchellh** [comment]
This is a very typical reaction of someone new to a Go-based project. :) 

Go standard library uses single hyphen flags. We've done this with all our projects for years and it has never caused any practical issues, just a bit of initial shock. :)

We unfortunately can't fix this without simply rewriting or switching the flag parsing library we're using which isn't something we're interested in. Sorry!

**Comment by jasonkuhrt** [comment]
Ok thanks for clarifying! Haha
