### ISSUE TITLE
Control tower enable terraform

### ISSUE THREAD

**Issue by Raghuveer123** [hashicorp/terraform#33904]
### Terraform Version

```shell
1.0
```

### Use Cases

My use-case I would like to enable the Control tower, Landing zone and Account factory using the terraform. We have the AFT to deploy the AWS Account using the control tower. I'm really looking for this feature where using the tf i would like to enable the control tower.

### Attempted Solutions

There is no resource that supports this

**Comment by liamcervante** [comment]
Hi @Raghuveer123, thanks for the request.

The individual providers and Terraform core are managed in separate repositories. The repository for the AWS provider is [hashicorp/terraform-provder-aws](https://github.com/hashicorp/terraform-provider-aws).

I'm going to close this issue on our repository, but you can feel free to reopen this there. Before you do that, however, you could take a look to see if this issue has already been raised. For example I can see https://github.com/hashicorp/terraform-provider-aws/issues/21674 which is requesting support for adding accounts via AWS Control Tower.

Thanks!
