### ISSUE TITLE
Use self or this in validation rules to reference variable

### ISSUE THREAD

**Issue by lorenzofelletti** [hashicorp/terraform#33903]
### Terraform Version

```shell
1.5.7
```

### Use Cases

When writing validation rules for a variable, one is forced to reference the variable through `var.my_var` which seems a little redundant, since the validation rule can only be written inside a variable block.

### Attempted Solutions

N/A

### Proposal

In my opinion, the code would be more readable if we had the possibility to reference the variable through a keyword like `self` or `this`.

So, for example something like:
```hcl
variable "my_var" {
  type        = string
  description = "An informative desc"
  validation {
    condition     = can(regex("^[a-z-_]+", self))
    error_message = "Variable does not conform to regex [a-z-_]+"
  }
}
```

**Comment by crw** [comment]
Thanks for this feature request! If you are viewing this issue and would like to indicate your interest, please use the 👍 reaction on the issue description to upvote this issue. We also welcome additional use case descriptions. Thanks again!
