### ISSUE TITLE
Terraform version 1.5.7 takes too long

### ISSUE THREAD

**Issue by ayelencasamassa** [hashicorp/terraform#33900]
### Terraform Version

```shell
1.5.7
```

### Terraform Configuration Files

```terraform
...terraform config...
```
-

### Debug Output

-

### Expected Behavior

Plan usually takes less than a minute.

### Actual Behavior

Plan takes more than 30 min and never completes

### Steps to Reproduce

Just create 4 Azure resources

### Additional Context

I have a simple configuration of 4 azure resources. For some reason, after upgrade from 1.5.5 to 1.5.7, plans never completes and it is running for too long.

### References

-

**Comment by crw** [comment]
Thanks for this report. Without more information e.g. following the issue template, we do not have enough information to do any meaningful troubleshooting. Particularly, including a sample config and the `TRACE` level log output would be a good start (see: https://developer.hashicorp.com/terraform/internals/debugging). Thanks!

**Comment by ayelencasamassa** [comment]
The issue is related with azure. You can close this case.
