### ISSUE TITLE
Error creating aws_medialive_channel input attachment failover: setting AWS Elemental MediaLive Channel (*******): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}

### ISSUE THREAD

**Issue by lucas3900** [hashicorp/terraform#33914]
### Terraform Version

```shell
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.17.0
+ provider registry.terraform.io/hashicorp/awscc v0.60.0

But also tested this on Terraformv1.5.0 and provider registry.terraform.io/hashicorp/aws v5.16.0
```

### Terraform Configuration Files

```terraform
resource "aws_medialive_channel" "test_channel" {
  name          = "test_channel"
  channel_class = "SINGLE_PIPELINE"
  role_arn      = aws_iam_role.medialive_iam_role.arn
  tags = {

  }

  destinations {
    id = "dest-full"
    media_package_settings {
      channel_id = aws_media_package_channel.test_channel.id
    }
  }
  destinations {
    id = "dest-ambient"
    settings {
      password_param = aws_ssm_parameter.ssm_ambient.name
      url = aws_media_package_channel.test_channel_ambient.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_ambient.hls_ingest[0].ingest_endpoints[0].username
    }
  }
  destinations {
    id = "dest-pa"
    settings {
      password_param = aws_ssm_parameter.ssm_pa.name
      url = aws_media_package_channel.test_channel_pa.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_pa.hls_ingest[0].ingest_endpoints[0].username
    }
  }
  destinations {
    id = "dest-pa-ambient"
    settings {
      password_param = aws_ssm_parameter.ssm_pa_ambient.name
      url = aws_media_package_channel.test_channel_pa_ambient.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_pa_ambient.hls_ingest[0].ingest_endpoints[0].username
    }
  }


  input_specification {
    codec            = "HEVC"
    input_resolution = "HD"
    maximum_bitrate  = "MAX_20_MBPS"
  }

  # primary input
  input_attachments {
    input_attachment_name = "input_attachment"
    input_id              = aws_medialive_input.test_input.id
    automatic_input_failover_settings {
      secondary_input_id    = aws_medialive_input.test_input_b.id
      input_preference      = "PRIMARY_INPUT_PREFERRED"
      error_clear_time_msec = 30000
      failover_condition {
        failover_condition_settings {
          video_black_settings {
            black_detect_threshold = 0.5
            video_black_threshold_msec = 3000
          }
        }
      }
    } # input failover
....
}
...terraform config...
```

### Debug Output

`ERROR: setting AWS Elemental MediaLive Channel (*****): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}`

### Expected Behavior

Failover should be enabled with black screen failover condition 

### Actual Behavior

`terraform apply` and `terraform plan` both error out with error: `ERROR: setting AWS Elemental MediaLive Channel (*****): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}`

### Steps to Reproduce

1. `terraform apply`
After the `terraform apply`, all main terraform operations (`apply`, `plan`, `init`, `destroy`) error out
### Additional Context

The failover incorrectly gets created in my medialive channel as an input loss failover condition. Only way to resolve this is to manually disable the automatic failover in the AWS UI, and then remove the failover code from the IaC.

Additionally, I tried just enabling the automatic failover without any conditions:
```
automatic_input_failover_settings {
      secondary_input_id    = aws_medialive_input.input_example.id
      input_preference      = "PRIMARY_INPUT_PREFERRED"
      error_clear_time_msec = 3000
      }
    } # input failover
```
Finally, the secondary input I am trying to failover is attached properly. If I take out the automatic failover, everything works as expected

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
