### ISSUE TITLE
[Terraform 1.3.7] Resources are deleted where there is a depends_on check for addition

### ISSUE THREAD

**Issue by sathaiahd** [hashicorp/terraform#33918]
### Terraform Version

```shell
1.3.7
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

none

### Expected Behavior

we have terraform resource creation on aws security group rules and it has depends_on

depends_on check fails in the context of the bug that we are talking, so it should not proceed further and add the resources.

but it deleted the aws security group rules which it supposed to not to do.

### Actual Behavior

it should not delete the aws security group rules

### Steps to Reproduce

none

### Additional Context

none

### References

none

**Comment by sathaiahd** [comment]
The issue happened part of my organisation which I cannot share it here, but i would request you have a conversation with me, understand the issue  either provide the solution or fix the issue if it is an issue from terraform side.

**Comment by crw** [comment]
Hi @sathaiahd, if you are a paying customer, please contact support by emailing [tf-cloud@hashicorp.support](mailto:tf-cloud@hashicorp.support) or [open a new request](https://support.hashicorp.com/hc/en-us/requests/new). 

This GitHub issues forum is used to post issues found in the core Terraform community project, not for direct customer support. Thanks for your understanding.
