### ISSUE TITLE
aws_efs_file _system resource to support elastic mode option in throught put mode

### ISSUE THREAD

**Issue by skkc2** [hashicorp/terraform#33947]
### Terraform Version

```shell
Terraform v1.0.7
```

### Use Cases

Hi All,

At the moment EFS file system resource only supports or take two types of option for throughput mode variable those are Bursting and provisioned. AWS has one more option called elastic which is currently not being supported by the aws_efs_file_system resource module. Please correct me if this option is already available in a different version or else could you please add this feature as well.

Thank you

### Attempted Solutions

I've updated the throughput varaible value to elastic and error out as 
` Error: expected throughput_mode to be one of [bursting provisioned], got elastic`

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
