### ISSUE TITLE
AWS Verified Access Resources created on my Default account

### ISSUE THREAD

**Issue by logansidwell** [hashicorp/terraform#33968]
### Terraform Version

```shell
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/aws v4.45.0
+ provider registry.terraform.io/hashicorp/awscc v0.61.0
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.45.0"
    }
  }

provider "aws" {
  profile = "corp_superadmin"
  region  = "us-east-1"
}

resource "awscc_ec2_verified_access_trust_provider" "okta_trust_provider" {
  policy_reference_name = "okta_provider_policy"
  trust_provider_type   = "user"
  description           = "Okta Provider"
  oidc_options = {
    authorization_endpoint = "https://xyz.okta.com/oauth2/v1/authorize"
    client_id              = "1"
    client_secret          = "1"
    issuer                 = "https://xyz.okta.com"
    scope                  = "openid profile groups"
    token_endpoint         = "https://xyz.okta.com/oauth2/v1/token"
    user_info_endpoint     = "https://xyz.okta.com/oauth2/v1/userinfo"
  }
  user_trust_provider_type = "oidc"
  tags = [{
    key   = "Name"
    value = "okta_provider_xyz"
  }]
  lifecycle {
    ignore_changes = [oidc_options.client_secret, oidc_options.client_id]
  }
}
```

### Debug Output

The request succeeds, but the verified access resource is created in us-west-2 and in my [default] AWS profile.

### Expected Behavior

The verified access resource should be created in us-east-1 using the corp_superadmin profile.

### Actual Behavior

The request succeeds, but the verified access resource is created in us-west-2 and in my [default] AWS profile.

### Steps to Reproduce

1. terraform init
2. terraform apply

### Additional Context

Similar problems are arising for most verified access resources, they are all created on the [default] profile rather than the profile defined in the provider

**Comment by crw** [comment]
Hello @logansidwell, this appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers. Thanks!

**Comment by logansidwell** [comment]
Ah, gotcha, thanks!
