### ISSUE TITLE
`terraform init`, `TF_WORKSPACE` errors after 1.6.0 release

### ISSUE THREAD

**Issue by rileygriffith** [hashicorp/terraform#33976]
### Terraform Version

```shell
Terraform v1.6.0
```

### Terraform Configuration Files

```terraform
terraform {
  cloud {
    organization = "XXXXX"
    workspaces {
      tags = [ "XXXXX" ]
    }
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.28.0"
    }
  }
}
```

### Debug Output

The only thing in the stacktrace that looked somewhat relevant. It appears to be going to the "default" workspace when the TF_WORKSPACE environment variable defines something else
```
2023-10-04T19:00:18.825Z [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-10-04T19:00:18.825Z [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2023-10-04T19:00:18.825Z [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2023-10-04T19:00:18.825Z [TRACE] statemgr.Filesystem: read nil snapshot
2023-10-04T19:00:18.825Z [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
2023-10-04T19:00:18.825Z [TRACE] Meta.Backend: Terraform Cloud mode initialization type: ConfigChangeInPlace
2023-10-04T19:00:18.827Z [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
```

### Expected Behavior

Should have initialized successfully, as it was prior to the release of 1.6.0.

### Actual Behavior

│ Error: Invalid workspaces configuration
│ 
│   on main.tf line 5, in terraform:
│    5:   cloud ***
│ 
│ Only one of workspace "tags" or "name" is allowed.
│ 
│ The 'workspaces' block configures how Terraform CLI maps its workspaces for
│ this single
│ configuration to workspaces within a Terraform Cloud organization. Two
│ strategies are available:
│ 
│ tags - A set of tags used to select remote Terraform Cloud
│ workspaces to be used for this single
│ configuration. New workspaces will automatically be tagged with these tag
│ values. Generally, this
│ is the primary and recommended strategy to use.  This option conflicts with
│ "name".
│ 
│ name - The name of a single Terraform Cloud workspace to be
│ used with this configuration.
│ When configured, only the specified workspace can be used. This option
│ conflicts with "tags".

### Steps to Reproduce

NOTE: I can only reproduce this inside a git action runner, have not been able to replicate it with local commands
1. `terraform init`

### Additional Context

This issue appears to be common across all of our git actions, and it coincides with the release of version 1.6.0, which happened 1-2 hours ago at the time of writing this

**Comment by rileygriffith** [comment]
Turns out I am in fact able to reproduce this locally. With the following steps:

1. run `export TF_WORKSPACE=workspace-name`
2. run `terraform init`

```
╷
│ Error: Invalid workspaces configuration
│ 
│ Only one of workspace "tags" or "name" is allowed.
│ 
│ The 'workspaces' block configures how Terraform CLI maps its workspaces for this single
│ configuration to workspaces within a Terraform Cloud organization. Two strategies are available:
│ 
│ tags - A set of tags used to select remote Terraform Cloud workspaces to be used for this single
│ configuration. New workspaces will automatically be tagged with these tag values. Generally, this
│ is the primary and recommended strategy to use.  This option conflicts with "name".
│ 
│ name - The name of a single Terraform Cloud workspace to be used with this configuration.
│ When configured, only the specified workspace can be used. This option conflicts with "tags".
```

**Comment by asnodgrass-nid** [comment]
I am also impacted. I updated our workflows to pin to 1.5.7 to work around the issue for now.

**Comment by Hecedu** [comment]
Also impacted by this issue, this doesn't seem to affect remote flows but cloud ones.

**Comment by itxasos23** [comment]
Also impacted by this issue.

**Comment by alexandrepatrin** [comment]
Also impacted by this issue.

**Comment by jbacheli** [comment]
Also impacted by this issue using Github actions runner.

**Comment by jackherizsmith** [comment]
> I am also impacted. I updated our workflows to pin to 1.5.7 to work around the issue for now.

This has worked for us, awaiting a better solution 🙏

**Comment by gmoraa** [comment]
Facing the same issue here.

**Comment by crw** [comment]
Thanks for the reports! Confirming that we are aware of this issue.

**Comment by ff-juan-castro** [comment]
It seems like the errors keep happening. Does anyone else have the same problem?
```
Initializing Terraform Cloud...
╷
│ Error: Invalid workspaces configuration
│ 
│   on providers.tf line 1[8](https://github.com/captioncall/ailab_savvy_batch_infrastructure/actions/runs/6471630132/job/17570494071#step:5:9), in terraform:
│   18:   cloud {
│ 
│ Only one of workspace "tags" or "name" is allowed.
│ 
│ The 'workspaces' block configures how Terraform CLI maps its workspaces for
│ this single
│ configuration to workspaces within a Terraform Cloud organization. Two
│ strategies are available:
│ 
│ tags - A set of tags used to select remote Terraform Cloud
│ workspaces to be used for this single
│ configuration. New workspaces will automatically be tagged with these tag
│ values. Generally, this
│ is the primary and recommended strategy to use.  This option conflicts with
│ "name".
│ 
│ name - The name of a single Terraform Cloud workspace to be
│ used with this configuration.
│ When configured, only the specified workspace can be used. This option
│ conflicts with "tags".
╵
```
