### ISSUE TITLE
Terraform ignores skip_credentials_validation flag for s3 backend with custom endpoint.

### ISSUE THREAD

**Issue by mmeintker-tc** [hashicorp/terraform#33983]
### Terraform Version

```shell
Terraform v1.6.0
on linux_amd64
```

### Terraform Configuration Files

Provider config:
```
terraform {
  required_version = ">= 0.13"
  required_providers {
    openstack = {
      source = "terraform-provider-openstack/openstack"
    }
  }
  # will use backend tfvars file
  backend "s3" {}
}
```
tfvars:
```
endpoints = {
  s3 = "https://ceph.mydomain.tld:7480"
}
bucket = "tfstates"
key = "tfstate"
use_path_style = true
region = "us-east-1"
skip_credentials_validation = true
skip_region_validation = true
```

### Debug Output

Initializing the backend...
╷
│ Error: Retrieving AWS account details: AWS account ID not previously found and failed retrieving via all available methods. See https://www.terraform.io/docs/providers/aws/index.html#skip_requesting_account_id for workaround and implications. Errors: 2 errors occurred:
│ 	* retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: XXX, api error InvalidClientTokenId: The security token included in the request is invalid.
│ 	* retrieving account information via iam:ListRoles: operation error IAM: ListRoles, https response error StatusCode: 403, RequestID: XXX, api error InvalidClientTokenId: The security token included in the request is invalid.
│ 
│ 
│ 
│ 
╵

Error: Process completed with exit code 1.

### Expected Behavior

Terraform should just initialize like it did with v1.5.5. 

### Actual Behavior

It tries to retrieve AWS account details, which it cannot becuase I'm not using an AWS backend.

### Steps to Reproduce

1. `export AWS_SECRET_ACCESS_KEY=<your S3 secret key>`
2. `export AWS_ACCESS_KEY_ID=<your S3 access key>`
3. `terraform init -backend-config=backend.tfvars`

### Additional Context

Reverting back to terraform v.1.5.5 fixed this issue.

**Comment by hloeung** [comment]
Does the s3 backend need an option `skip_requesting_account_id` similar to what's in the [aws provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_requesting_account_id)?

**Comment by josephpage** [comment]
This parameter is absolutely necessary if you want to use S3-compatible storage systems such as Ceph, Minio, Digitalocean, OVH or Scaleway as a backend, as they do not implement the STS API.

**Comment by bestrocker221** [comment]
It still does not work in v1.6.2

Tried to set 
```
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
```

but keep getting

```
│ Error: Retrieving AWS account details: AWS account ID not previously found and failed retrieving via all available methods. See https://www.terraform.io/docs/providers/aws/index.html#skip_requesting_account_id for workaround and implications. Errors: 2 errors occurred:
│       * retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.eu-stockholm-1.amazonaws.com/": dial tcp: lookup sts.XXXXX: no such host
│       * retrieving account information via iam:ListRoles: operation error IAM: ListRoles, https response error StatusCode: 403, RequestID: ...... , api error InvalidClientTokenId: The security token included in the request is invalid.
```

**Comment by lotusnoir** [comment]
I got it working replacing

`endpoint = "https://s3.fr-par.scw.cloud"`

by
```
    endpoints = { s3 = "https://s3.fr-par.scw.cloud" }
    skip_requesting_account_id = true
```
then 

terraform init -reconfigure
