### ISSUE TITLE
Feature request: ClusterK like scheduling over AWS spot instances

### ISSUE THREAD

**Issue by gebrits** [hashicorp/terraform#3398]
Not totally sure if this would be core to Terraform but here goes anyway:

Ability to have a scheduler running spot instances and making sure (based on heuristics) that the total fleet of spot instances will meet a certain minimal availability. I.e proactively adding spot instances when the scheduler foresees based on historic pricing that spot instances are going to be killed.

This was the core of ClusterK before it got acquired by Amazon.

Would it make sense to have something like this in Terraform?

**Comment by phinze** [comment]
Hi @gebrits - thanks for the interest!

I don't think this would fit in Terraform's domain, but you might want to have a look at [Nomad](https://nomadproject.io/). :grinning:
