### ISSUE TITLE
Terraform Test: Load terraform.tfvars file from test directory automatically

### ISSUE THREAD

**Issue by liamcervante** [hashicorp/terraform#34008]
### Terraform Version

```shell
Terraform v1.6.0
```

### Use Cases

It would be nice to let users specify a set of Terraform variable values for all the tests at once automatically. We can do this by loading a terraform.tfvars file from the testing directory automatically, like we do for the main configuration directory.

### Attempted Solutions

You can place the variable values in terraform.tfvars file in the main configuration directory, but this might clash with any default variable values you want to specify for plans or applys against the main config.

### Proposal

`terraform test` loads the default variables from this [function](https://github.com/hashicorp/terraform/blob/edb8ea4baa43421a73d7ba50fed957e6be599b45/internal/command/meta_vars.go) [here](https://github.com/hashicorp/terraform/blob/edb8ea4baa43421a73d7ba50fed957e6be599b45/internal/command/test.go#L133).

We could modify, or duplicate, that function so that it accepts a testing directory and will include two sets of variables one for any tests in the testing directory, and one for any tests within the main configuration directory.

**Comment by JKIPIKA** [comment]
Hi, I would like to be new contributor to Terraform project, can I work on this issue ?

**Comment by liamcervante** [comment]
Hi @JKIPIKA, sure thing! I'd be happy to review any PR you raised for this issue.

A caveat / trap to look out for would be that we can execute tests both inside the main configuration directory and within any specified testing directory in the same execution. This means we need to keep track of two sets of variables for the tests, one loaded from the main configuration directory and one loaded for the testing directory.

My approach would be:

- Add a function called `collectVariableValuesForTests()` alongside this [function](https://github.com/hashicorp/terraform/blob/edb8ea4baa43421a73d7ba50fed957e6be599b45/internal/command/meta_vars.go#L33).
  - I'd make it accept the current testing directory as an argument, and it should return two sets of variables. One loaded from the testing directory, and one loaded from the configuration directory.
  - The two functions will largely be the same aside from [these lines](https://github.com/hashicorp/terraform/blob/edb8ea4baa43421a73d7ba50fed957e6be599b45/internal/command/meta_vars.go#L68-L75) so you want to think about the best way to maximise code sharing between them (probably with a shared third function that both call out to).
- You can then call the new function from [command/test.go](https://github.com/hashicorp/terraform/blob/edb8ea4baa43421a73d7ba50fed957e6be599b45/internal/command/test.go#L133) to get both sets of variables for all the tests.
- You then want to pass both sets of variables into the local [TestSuiteRunner](https://github.com/hashicorp/terraform/blob/edb8ea4baa43421a73d7ba50fed957e6be599b45/internal/backend/local/test.go#L40) instead of the current single set.
- Finally, you want to find where that file was referenced and update them so they pick the correct set of variables based on the currently executing file.
  - You could probably make this easier by adding the global variables directly into `TestFileRunner` when that is created, and then have the references look at the file runner instead of the suite runner overall.

Hopefully that makes sense! If you're still interested, feel free to raise a PR and tag me, or link it here, and I can take a look. Let me know any other questions!

**Comment by JKIPIKA** [comment]
Thank you very much for explanation! I will raise a PR when i will have something worth sharing.

**Comment by crw** [comment]
Hi @JKIPIKA, please also make sure to read https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md#contributing-to-terraform. Thanks!

**Comment by JKIPIKA** [comment]
Hi @crw, i have read contribution guide! I have dev environment ready at my local machine, can you please mark me as assignee to this issue ?

**Comment by JKIPIKA** [comment]
Hello, sorry for the delay, the task was actually harder for me than I thought, can you please verify my solution ?

**Comment by crw** [comment]
@JKIPIKA thanks, let's keep that conversation in the PR. We appreciate your contribution!

**Comment by liamcervante** [comment]
Fixed in https://github.com/hashicorp/terraform/pull/34341, thanks @JKIPIKA!
