### ISSUE TITLE
Terraform 1.6.0 s3 backend kms_key_id doesn't work anymore with alias

### ISSUE THREAD

**Issue by dosilyoun** [hashicorp/terraform#34005]
### Terraform Version

```shell
1.6.0
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {
    region = "eu-central-1"
    bucket = "*****"
    key    = "terraform-state/***/***/terraform.tfstate"

    encrypt = true
    kms_key_id = "arn:aws:kms:eu-central-1:*********:alias/k*******"
    dynamodb_table = "****"
    assume_role = {
      role_arn = "arn:aws:iam::****:role/*****"
    }
  }
}
```

### Debug Output

 Error: Invalid KMS Key ARN
│ 
│   on backend.tf line 14, in terraform:
│   14:     kms_key_id = "arn:aws:kms:eu-central-1:*****:alias/*****"
│ 
│ Value must be a valid KMS Key ARN, got "arn:aws:kms:eu-central-1:*****:alias/*****"

### Expected Behavior

terraform init is successful.  
With version 1.5.7, it was worked.
Using key id instead of alias is still working in version 1.6.0

### Actual Behavior

terraform init fails

### Steps to Reproduce

1. 'terraform init'

**Comment by WtfJoke** [comment]
I think thats a duplicate of https://github.com/hashicorp/terraform/issues/34005
