### ISSUE TITLE
Introduction video replaying from start every time tab switch happens. 

### ISSUE THREAD

**Issue by faheemhaider1** [hashicorp/terraform#34003]
### Terraform Version

```shell
Terraform v1.6.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

None needed

### Expected Behavior

The main website should continue playing the video in the background when the tab is switched and when returned to the tab should continue from where it was running in the background. 

### Actual Behavior

The actual behavior going on when the video is being played in the background when tabs are switched. The video starts from the start 0:00 minutes when the tab is brought back into focus or returned to the tab where the video was playing.

### Steps to Reproduce

1. Open Terraform site.
2. Play the introduction video.
3. Open another tab and switch to it. 
4. Video is being played in the background.
5. Switch back to the terraform tab.
6. The video will start playing from the start 0:00 minutes

**Comment by crw** [comment]
Hi @faheemhaider1, what is the "Terraform site" address where you are seeing this? Thanks.

**Comment by faheemhaider1** [comment]
https://developer.hashicorp.com/terraform/intro

Visit this link, scroll down to the video part.

**Comment by crw** [comment]
@faheemhaider1 thanks for this feedback, we really appreciate it! That website is maintained by a different team at HashiCorp, whom I have informed of this issue. As we cannot address it in the files in this repo, or by the team of maintainers on this repo, I am going to close it. Please rest assured that I have passed on the feedback internally. Thanks again!
