### ISSUE TITLE
assign secondary private_ip to instance

### ISSUE THREAD

**Issue by gafaru** [hashicorp/terraform#3401]
I know with aws_network_interface you can use 'private_ips' to assign multiple IPs to the interface. But suppose I don't want to add an extra interface to the aws_instance.  How would I assign a secondary or multiple private IPs to aws_instance.  Currently only private_ip is supported and it doesn't allow for multiple.  Can you make 'private_ips' possible on aws_instance instead of just 'private_ip'?  Thanks

**Comment by gafaru** [comment]
Is it possible with terraform to identify the primary network_interface from aws instance and apply private_ips to it?

**Comment by gafaru** [comment]
https://github.com/hashicorp/terraform/issues/1557 seems to ask for the same.

**Comment by radeksimko** [comment]
Closing in favour of https://github.com/hashicorp/terraform/issues/1557 which is a duplicate issue and has a little bit more traction.
