### ISSUE TITLE
azurerm_app_service_public_certificate: Creation of Public Certificate - couldn't find resource (11 retries)

### ISSUE THREAD

**Issue by vigor-vavan** [hashicorp/terraform#34025]
### Terraform Version

```shell
Terraform v1.5.7
hashicorp/azurerm v3.75.0
```

### Terraform Configuration Files

```
resource "azurerm_app_service_public_certificate" "public_certificate" {
  for_each             = zipmap(range(length(local.certificates)), local.certificates)
  resource_group_name  = local.azure_function_resources.resource_group_name
  app_service_name     = azurerm_windows_function_app.azure_function.name
  certificate_name     = each.value.name
  certificate_location = "CurrentUserMy"
  blob                 = each.value.certificate_location
  provider             = azurerm.azure_functions

  depends_on = [
    azurerm_windows_function_app.azure_function
  ]
}
```

### Debug Output

Error: waiting for creation of Public Certificate: (Name "xxxxx" / Site Name "xxxxx" / Resource Group "xxxxx"): couldn't find resource (11 retries)
│ 
│   with module.derms.azurerm_app_service_public_certificate.public_certificate["0"],
│   on .terraform\modules\derms\AzureFunction.tf line 139, in resource "azurerm_app_service_public_certificate" "public_certificate":
│  139: resource "azurerm_app_service_public_certificate" "public_certificate" {

### Expected Behavior

Public certificates are uploaded and stored in state file 

### Actual Behavior

Public certificates are uploaded but not stored in state file.
On second execution:
"
Error: A resource with the ID "/subscriptions/xxxxxresourceGroups/xxxxxx/providers/Microsoft.Web/sites/axxx/publicCertificates/xxxxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_app_service_public_certificate" for more information.
│ 
│   with module.derms.azurerm_app_service_public_certificate.public_certificate["1"],
│   on .terraform\modules\derms\AzureFunction.tf line 137, in resource "azurerm_app_service_public_certificate" "public_certificate":
│  137: resource "azurerm_app_service_public_certificate" "public_certificate" {
│ 
"

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

Azure funcition successfully deployed. On setting public certificates from local location via filebase64(""), terraform apply fails even though certificates are visible on portal and function works properly.

On second execution terraform again fails with message to import certificate into state file.

Two certificates are imported via list of dictionaries with certificate name and certificate location

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
