### ISSUE TITLE
Splat references and dependency graphing

### ISSUE THREAD

**Issue by bhourigan** [hashicorp/terraform#3404]
I think I'm running into a terraform bug. I'm calling a module and using splat references as part of the modules input. It's not being graphed as a dependency, and fails with an error. I'm also unable to use depends_on in my module declaration but this appears to be a known limitation as pointed out here https://github.com/hashicorp/terraform/issues/1178

Here are some snippets which I think demonstrates my intent and syntax:
https://gist.github.com/bhourigan/05b2cf0677631c3f0219

I stopped by IRC and asked this same question in #terraform-tool and someone pointed me to https://github.com/hashicorp/terraform/issues/580, but this seems to be the opposite use case. I have local resources that have to be provisioned before invoking the module.

**Comment by mitchellh** [comment]
Hey @bhourigan! I wanted to take a look at this [finally!] but your gist is now a 404. If you can post the example again I'll take a look. Sorry! Please help us by just opening a new issue so it pops to the top of the stack.
