### ISSUE TITLE
Crash on re-apply when a check is in a module

### ISSUE THREAD

**Issue by rpadaki** [hashicorp/terraform#34062]
### Terraform Version

```shell
Terraform v1.6.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

### Terraform Configuration Files

https://github.com/rpadaki/tf-bug-sandbox

### Debug Output

First run succeeds: https://gist.github.com/rpadaki/cdb132d787208961f60c7254ca72d28d
Second run panics: https://gist.github.com/rpadaki/2d492b57cb3c1ac46fadc71988efb747

Here is the stacktrace from the second run:
```log
module.module_check_causes_panic.null_resource.inside_module: Refreshing state... [id=4472235122879494048]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

no expansion has been registered for module.module_check_causes_panic
goroutine 165 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x1c
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x164
panic({0x10762a8a0?, 0x140007f1600?})
        /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x26c
github.com/hashicorp/terraform/internal/instances.(*expanderModule).moduleInstances(0x14000ab4ba0, {0x140007f1f30, 0x1, 0x1}, {0x140007b7870, 0x0, 0x4}, 0x0)
        /Users/runner/work/terraform/terraform/internal/instances/expander.go:370 +0x228
github.com/hashicorp/terraform/internal/instances.(*Expander).expandModule(0x0?, {0x140007f1f30?, 0x104ba2ad0?, 0x140000ea7e0?}, 0x30?)
        /Users/runner/work/terraform/terraform/internal/instances/expander.go:126 +0x104
github.com/hashicorp/terraform/internal/instances.(*Expander).ExpandModule(...)
        /Users/runner/work/terraform/terraform/internal/instances/expander.go:105
github.com/hashicorp/terraform/internal/terraform.(*nodeExpandCheck).DynamicExpand(0x14000a123c0, {0x107c72490?, 0x14000846460?})
        /Users/runner/work/terraform/terraform/internal/terraform/node_check.go:84 +0x64
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x107892300, 0x14000a123c0})
        /Users/runner/work/terraform/terraform/internal/terraform/graph.go:88 +0x44c
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0x14000a24f00, {0x107892300, 0x14000a123c0}, 0x14000a12580)
        /Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2a8
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 14
        /Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xb0c
```

### Expected Behavior

The second `terraform apply` should have silently succeeded.

### Actual Behavior

There is a panic: `no expansion has been registered for module.module_check_causes_panic`

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
    - This sometimes panics if the check references a data block instead of a `null_resource`. But for the resource in my example repo, this first run succeeds.
3. `terraform apply`
    - This will cause the panic

### Additional Context

I've confirmed the same behavior on v1.5.7 for what it's worth. My guess is that the node for the resource/data source is not properly connected to the node for the check. But the DAG code is quite hard to navigate as a newcomer so I didn't have much success debugging it.

**Comment by liamcervante** [comment]
Okay, this only happens when the follow up apply has no changes in the module the check is within. The graph attempts to clean up nodes that it doesn't need to save on processing time, and the check blocks are not properly registering themselves as children of the modules they are in. What happens then, is the module doesn't register itself with the graph as it doesn't think it has any relevant children, then the check node attempts to execute and it panics when it can't find the module it is supposed to be a part of.

I think this should be a relatively straightforward fix, and we can add some unit tests to make sure this doesn't regress in the future.
