### ISSUE TITLE
Terraform Test: ability to generate random string on test run

### ISSUE THREAD

**Issue by owlleg6** [hashicorp/terraform#34087]
### Terraform Version

```shell
Terraform v1.6.1
```

### Use Cases

The proposal introduces the development of a mechanism to generate random strings, which will be stored in a variable for each test execution. Within the 'Module', upon applying the configuration, tests are conducted, followed by the eventual teardown of the provisioned infrastructure.

To ensure no naming conflicts, especially when tests are executed within the same Cloud Account of provisioned infrastructure, the recommendation is to append a random prefix to all resources created during the test.

### Attempted Solutions

Currently none

**Comment by liamcervante** [comment]
Hi @owlleg6, if I'm reading this right I think we already have a solution for this.

You can use a setup module that creates a [`random_string`](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string) resource. If your setup module returns that as an output you can then pass the random string into the real module under test as a variable where it can be used as a prefix for the relevant attributes.

Does that solve your use case?

Thanks!

**Comment by owlleg6** [comment]
Hi @liamcervante, i will try later today. Thanks for suggestion!

**Comment by owlleg6** [comment]
Hello @liamcervante, thanks for help, your solution works like charm! I will close this issue.
