### ISSUE TITLE
S3 state storage backend broken for Ceph S3

### ISSUE THREAD

**Issue by mmeier86** [hashicorp/terraform#34086]
### Terraform Version

```shell
Terraform v1.6.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/consul v2.17.0
+ provider registry.terraform.io/hashicorp/nomad v1.4.17
+ provider registry.terraform.io/hashicorp/vault v3.14.0
+ provider registry.terraform.io/pan-net/powerdns v1.5.0
+ provider registry.terraform.io/terraform-lxd/lxd v1.10.1
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {
    bucket = "hn-state"
    key = "hnstate"
    region = "homenet"
    skip_credentials_validation = true
    skip_region_validation = true
    skip_metadata_api_check = true
    skip_requesting_account_id  = true
    shared_credentials_files = ["~/.tf-s3-creds"]
    endpoints = {
      s3 = "https://s3.mei-home.net:7481"
    }
    use_path_style = true
  }
}
```

### Debug Output

https://gist.github.com/mmeier86/9adecc6c5d3f062007a9f690b1b6cbf9

### Expected Behavior

The state gets uploaded to Ceph S3 storage successfully.

### Actual Behavior

An error message is shown:

```
Failed to persist state: failed to upload state: operation error S3: PutObject, https response error StatusCode: 400, RequestID: tx000007e1a13b84ba2e66c-00652c2eac-3b1db5-homenet, HostID: 3b1db5-homenet-default, api error XAmzContentSHA256Mismatch: UnknownError
```

### Steps to Reproduce

1. Update Terraform to v1.6.1
2. Make a state change
3. Observe the error

### Additional Context

This is a Terraform setup which uses an internal Ceph S3 cluster as the backend. The same setup worked without issue with v1.5.7.

### References

#34053 has a comment which reports a similar error but for another non-AWS S3 provider: https://github.com/hashicorp/terraform/issues/34053#issuecomment-1757355754

**Comment by hloeung** [comment]
We're seeing this as well, Ceph / Rados GW via the S3 API. `s3cmd` PUT of the state file doesn't help either.

For now, we've rolled back and pinned to v1.5.7.

**Comment by Firfi** [comment]
I experience the same issue with digitalocean spaces used as a backend. It happened with a terraform update.

**Comment by suckowbiz** [comment]
We also hit the issue with Ceph :(.

**Comment by holms** [comment]
Same issue with digital ocean spaces:

```
terraform {
  backend "s3" {
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    use_path_style              = true
    endpoints = {
      s3 = "https://fra1.digitaloceanspaces.com"
    }
    region                      = "fra1" // needed
    bucket                      = "thorauto-terraform"
    key                         = "terraform.tfstate"
   }
}

│ Error: Failed to save state
│ 
│ Error saving state: failed to upload state: operation error S3: PutObject, https response error StatusCode: 400, RequestID: tx00000b96657e5f692e5d8-00652f2405-bc9d9e44-fra1b, HostID: bc9d9e44-fra1b-fra1-zg02, api error XAmzContentSHA256Mismatch: UnknownError
╵

```

**Comment by grady** [comment]
Observing same `XAmzContentSHA256Mismatch: UnknownError` as OP when using with Openstack Swift s3 api.

**Comment by jar-b** [comment]
Unfortunately we are unable to test changes to the S3 backend against the various S3-compatible storage providers, though it is never our intention to break existing workflows. I would recommend raising this with the upstream providers as the behavior has been confirmed to work correctly with Amazon S3. As part of the S3 Backend maintenance we did move from using [v1](https://github.com/aws/aws-sdk-go) of the AWS Go SDK to [v2](https://github.com/aws/aws-sdk-go-v2), specifically adopting the [S3 Manager](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/feature/s3/manager) feature which improves performance on large state files. It's possible that these providers have not implemented this functionality. We may be able to help resolve these issues with more information from those provider teams, but at this time cannot commit to investigating further.

**Comment by lemiliomoreno** [comment]
Had the same issue with Oracle Object Storage while using `v1.6.1` and `v1.6.2` versions, I was getting this error `api error InvalidArgument: x-amz-content-sha256 must be UNSIGNED-PAYLOAD`, downgraded to v1.5.7 and works fine

**Comment by doubando** [comment]
same issue with oracle cloud s3 backend :Error: failed to upload state: operation error S3: PutObject, https response error StatusCode: 400, RequestID: jed-1:3BrUElxUyNDzMhMYE9PlR_jZJqM3aOTI9zxzHCHXGzmSROKlz4GfE7LihIcJu5UX, HostID: , api error InvalidArgument: x-amz-content-sha256 must be UNSIGNED-PAYLOAD or a valid sha256 value.

**Comment by wezooyuri** [comment]
Same issue experienced with DigitalOcean S3 on version `v1.6.4`:

```
Error: Failed to save state

Error saving state: failed to upload state: operation error S3: PutObject,
https response error StatusCode: 400, RequestID:
<TX_ID>, HostID:
<ID>, api error XAmzContentSHA256Mismatch: UnknownError

Error: Failed to persist state to backend

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate
```

Rolled back to 1.5.7 to fix it. This is not a permanent solution though.

**Comment by doubando** [comment]
> same issue with oracle cloud s3 backend :Error: failed to upload state: operation error S3: PutObject, https response error StatusCode: 400, RequestID: jed-1:3BrUElxUyNDzMhMYE9PlR_jZJqM3aOTI9zxzHCHXGzmSROKlz4GfE7LihIcJu5UX, HostID: , api error InvalidArgument: x-amz-content-sha256 must be UNSIGNED-PAYLOAD or a valid sha256 value.

resolved by using the following parameters
    use_path_style              = true
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    skip_s3_checksum = true

**Comment by suckowbiz** [comment]
We also do use Ceph S3-like backend. Just experienced the issue `XAmzContentSHA256Mismatch` with latest Terraform 1.6.4:

```
│ Error: Failed to save state
│ 
│ Error saving state: failed to upload state: operation error S3: PutObject,
│ https response error StatusCode: 400, RequestID:
│ tx000000000000002259d42-006ddd8d89-172f1be2-s3, HostID: 172f1be2-s3-s3, api
│ error XAmzContentSHA256Mismatch: UnknownError
```

I am having all required skip-checks in place:

```
terraform {
  backend "s3" {
    bucket                      = "obfuscated"
    key                         = "obfuscated"
    use_path_style              = true
    region                      = "required but not applicable - validation skipped below"
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
  }
}
```

I stumbled over another open issue: 
For Ceph S3 like backend this is still broken. See https://github.com/hashicorp/terraform/issues/34053

@gdavison Coud you please re-open this issue to reflect Ceph backend usage is still an isue?

**Comment by voidus** [comment]
Also seeing `The provided 'x-amz-content-sha256' header does not match what was computed.` with minio

**Comment by crw** [comment]
Thanks - I suspect this is resolved. Please let me know if anyone is still having problems.
