### ISSUE TITLE
aws_security_group description change, plans a replacement of the aws_security_group

### ISSUE THREAD

**Issue by good92** [hashicorp/terraform#34092]
### Terraform Version

```shell
1.4.6
```

### Terraform Configuration Files

```
resource "aws_security_group" "canary_sg" {
  name        = "${local.name_prefix}-canary-sg"
  description = "Allow canaries to call the services - egress on DNS HTTP HTTPS"
  #  description = "Allow canaries to call the services they need to call"
  vpc_id      = local.vpc_id
```

### Debug Output

```
  # aws_security_group.canary_sg must be replaced
-/+ resource "aws_security_group" "canary_sg" {
      ~ arn                    = "arn:aws:ec2:XXXXXX:ZZZZZZZ:security-group/sg-YYYYYYYYY" -> (known after apply)
      ~ description            = "Allow canaries to call the services they need to call" -> "Allow canaries to call the services - egress on DNS HTTP HTTPS" # forces replacement
```

### Expected Behavior

change just the attribute aws_security_group.description

### Actual Behavior

ressource is replaced and cause issue due the ENI and preserve_security_group_id no more available.

```
  # https://cloudposse.com/devops/security-and-compliance/the-difficulty-of-managing-aws-security-groups-with-terraform/
  # If the security group is not being created by this module, we need to treat it as needing to be preserved, because we cannot replace it here.
#  preserve_security_group_id = true
#  lifecycle {
#    create_before_destroy = true
#  }
```

### Steps to Reproduce

terraform init
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
