### ISSUE TITLE
ChecksumAlgorithm header invalid with nonAWS s3 backend (backblaze)

### ISSUE THREAD

**Issue by nickcFRU** [hashicorp/terraform#34099]
### Terraform Version

```shell
nick@nick-OEM:~$ terraform version
Terraform v1.6.1
on linux_amd64
```

### Terraform Configuration Files

```terraform {
  backend "s3" {
    bucket                      = "<bucket"
    key                         = "<key>"
    region                      = "<region>"
    endpoint                    = "https://s3.<region>.backblazeb2.com"
    skip_region_validation      = true
    skip_credentials_validation = true
    skip_requesting_account_id  = true
  }
}
```

### Debug Output

https://gist.github.com/nickcFRU/71a25f345ffcf5aff509086a0007dd6b

### Expected Behavior

It should upload state file to s3 backend at backblaze

### Actual Behavior

Error due to `x-amz-sdk-checksum-algorithm` being passed in header

### Steps to Reproduce

1. `terraform apply`

### Additional Context

I believe  this is occuring due to backblaze not supporting checksum in the header.
https://www.backblaze.com/docs/cloud-storage-s3-compatible-api

Specifically, the addition of this line with this PR causes the issue with backblaze.
https://github.com/hashicorp/terraform/pull/33940/files#diff-a1847a2fb965d197bbf606c4211158e30bad04703baef13b9ab5e6cd8459920eR200

Maybe we could add a setting to make sending checksum in the header optional to avoid this for backends that do not support checksum?

**Comment by jar-b** [comment]
Hi @nickcFRU - thanks for the detailed report! 

I would recommend raising this with the upstream storage provider, as the behavior has been confirmed to work correctly with Amazon S3. Our support for S3 compatible storage providers is "best effort", and we only acceptance test against Amazon S3 during development of the `s3` backend.

I'm going to adjust the labels on this issue (`bug` to `enhancement`) as the bug in this case is technically in the compatibility of the upstream provider with the AWS SDK. If you aren't able to get this fixed upstream we can treat this as a feature request and leave it open to prioritize against other outstanding S3 backend issues.
