### ISSUE TITLE
GCE multiple network google_compute_instance not possible?

### ISSUE THREAD

**Issue by sklaus** [hashicorp/terraform#3409]
Hi,

I wanted to create some google_compute_instances which have 2 networks.

For that I specified 2 interfaces like this:

```network_interface {
    network = "${google_compute_network.mi-network.name}"
    access_config {}
  }
  network_interface {
    network = "${google_compute_network.gf-network.name}"
    access_config {}
  } ```

The terraform documentation allow so:
*network_interface - (Required) Networks to attach to the instance. This can be specified multiple times for multiple networks. Structure is documented below.*
https://www.terraform.io/docs/providers/google/r/compute_instance.html

I get this error:
```Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces': ''.  Specifying more than one network interface is not supported., invalid```

Looking into the GCE documentation, it says:
*Every instance is a member of a single network.*
https://cloud.google.com/compute/docs/networking#networks

This means there is an error in the terraform documentation to allow for multiple networks for a GCE instance.

**Comment by phinze** [comment]
Pinging @sparkprime for enlightenment here. :bulb:

**Comment by sparkprime** [comment]
The GCE documentation is not consistent with itself:  The low level API documentation does not say that there is a limit: https://cloud.google.com/compute/docs/reference/latest/instances

It is definitely true that the API as implemented today does not support it, I will try to find out what the plan is.

Maybe we should put a note in the Terraform docs, something along the lines of "GCE currently only supports 1 network interface, but may support more in the future.".

**Comment by sparkprime** [comment]
Note that if you are trying to build a bridge between two networks, you can do that with a VPN tunnel.

**Comment by sparkprime** [comment]
@lwander you have an example of that in Terraform, right?

**Comment by lwander** [comment]
@sparkprime, @sklaus 

Yup, here is a VPN bridging two networks in GCE https://github.com/hashicorp/terraform/tree/master/examples/gce-vpn

**Comment by sparkprime** [comment]
I just updated the docs to say it's not possible yet.

**Comment by gandhams** [comment]
Hi, Any possibility this issue has been fixed. I verified that multiple nics (each nic in different networks) can be added to the same vm using the cli. 

gcloud alpha compute instances create pavm-ssaha-swap-1 --can-ip-forward --network-interface subnet=mgmt-subnet --network-interface subnet=data1-subnet --network-interface subnet=data2-subnet --machine-type=n1-standard-2 --image pavm-guestos-feature-image --zone=us-west1-a --tags=pa-vm

**Comment by twexler** [comment]
@gandhams question actually brings up an even greater question: Which GCP API does terraform actually use? There are `alpha`, `beta` and `naked`(for lack of a better term). What's the decision process behind this?
