### ISSUE TITLE
terraform test parses all global variables for all modules referenced by run blocks

### ISSUE THREAD

**Issue by CodeBehind** [hashicorp/terraform#34106]
### Terraform Version

```shell
Terraform v1.6.1
on windows_amd64
```

### Terraform Configuration Files

[Find the files on my repository](https://github.com/CodeBehind/supreme-parakeet)

### Debug Output

 run "run"... pass
  run "run_module"... fail
test.tftest.hcl... tearing down
test.tftest.hcl... fail

Failure! 1 passed, 1 failed.

╷
│ Error: Variables not allowed
│
│   on <value for var.myvar_b> line 1:
│   (source code not available)
│
│ Variables may not be used here.
╵

### Expected Behavior

It should run the tests without the error above.

### Actual Behavior

As discussed in the [issue #34070](https://github.com/hashicorp/terraform/issues/34070) terraform parses all TF_VAR environment variables to the test, even if they are not needed or defined by the code tested. Now i found out, terraform does the same for every module you define in your tests aswell. So you have to ensure that all modules have the same input structure, otherwise it will generate the error above.

I don't know if @liamcervante fixed this behavior with his [pull request](https://github.com/hashicorp/terraform/pull/34072) or not. 
But i think this case can effect more people, because not every module you define in your tests will have or can have the same input structure. 

### Steps to Reproduce

1. Clone the repository mentioned above
2. Add the Variables from .env to your environment
3. run terraform init 
4. run terraform test <-- this produces the error

### References

- #34072 
- #34070

**Comment by liamcervante** [comment]
Hi @CodeBehind, I think the PR you referenced will fix this as well. 1.6.2 should be releases this week, and if you find this problem with that version please feel free to reopen this issue.

Thanks for filing this!

**Comment by CodeBehind** [comment]
@liamcervante thank you for your time and effort. 
I will test it, as soon as 1.6.2 is out.
