### ISSUE TITLE
jsonencode convert list to string if only one item will be passed in the list

### ISSUE THREAD

**Issue by Tim-herbie** [hashicorp/terraform#34107]
### Terraform Version

```shell
Terraform v1.5.7
```

### Terraform Configuration Files

```terraform
variable "projects" {
  description = "List of projects"
  type = list(object({
    project_name          = optional(string)
    oidc_group_names       = optional(string)
  }))
}

projects = [
  {
    project_name    = "project1"
    oidc_group_names = ["project1-oidc"]
  },
  {
    project_name          = "project2"
    oidc_group_names       = ["project2-oidc","one-additional-role"]
  },
]

resource "elasticstack_elasticsearch_security_role_mapping" "role_mapping" {
  for_each = { for project in var.projects : project.project_name => project}
  enabled  = true
  name     = each.value.project_name
  roles    = ["kibana_admin"]
  rules = jsonencode({
    all: [
      {
        field: {
          "realm.name": "abc"
        }
      },
      {
        field: {
          groups : each.value. oidc_group_names
        }
      }
    ]
  })
}
```

### Debug Output

.

### Expected Behavior

I expect that a terraform apply would add these two resources and passes the value of groups in the jsonencode as List into the .tfstate File.

### Actual Behavior

The terraform plan and apply will be executed correctly, but if I pass the object with the parameter "oidc_group_names" that contains only one item, I see Terraform Changes every time I trigger terraform plan/apply:

```terraform
~ resource "elasticstack_elasticsearch_security_role_mapping" "role_mapping" {
        id       = "abdefghijklmn/project1"
        name     = "project1"
      ~ rules    = jsonencode(
          ~ {
              ~ all = [
                    {
                        field = {
                            "realm.name" = "abc"
                        }
                    },
                  ~ {
                      ~ field = {
                          ~ groups = "project1-oidc" -> [
                              + "project1-oidc",
                            ]
                        }
                    },
                ]
            }
        )
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I took a look in the .tfstate file and saw that the groups value of project1 (project1-oidc) was not saved as a list ["project1-oidc"]. Instead it was saved as a String "project1-oidc", maybe because it contains only one item. And that is the problem. Terraform converts this list into a string for the .tfstate and because of that terraform tries every time to update that.
This is the line of the .tfstate file:
```
"rules": "{\"all\":[{\"field\":{\"realm.name\":\"abc\"}},{\"field\":{\"groups\":\"project1-oidc\"}}]}"
```

The groups value of project2 was saved correctly as a list ["project2-oidc", "one-additional-group"] and after one apply, it does not appear again. Here is the correct line of the .tfstate file
```
"rules": "{\"all\":[{\"field\":{\"realm.name\":\"abc\"}},{\"field\":{\"groups\":[\"project2-oidc\",\"one-additional-group\"]}}]}"
```

### Steps to Reproduce

I don´t know how you could reproduce it simply, because for that you would need a running Elastic + Kibana Stack. 
I hope that I described it good enough to understand and maybe reproduce the issue in another way again.

### References
Not the same, but a similar issue:
https://github.com/hashicorp/terraform/issues/33021

**Comment by jbardin** [comment]
Hi @Tim-herbie,

Thanks for filing the issue. This can be verified directly in the Terraform console:

```
> jsonencode([{"a":"Test"}])
"[{\"a\":\"Test\"}]"
```

where it's apparent that the `jsonencode` function does not change the structure of the argument. What is more likely, is that the provider is modifying the json due to some faulty normalization. This may be visible as warnings in the logs that we must allow the invalid value if the provider is using the legacy SDK, or it could also be a normalization problem during refresh, but that wouldn't be involved if you checked the state immediately after the first apply.

Please file an issue with the provider developers, and they can continue investigating the problem

Thanks!
