### ISSUE TITLE
Ability for AWS Security Group to Associate AWS Prefix List ID

### ISSUE THREAD

**Issue by quater** [hashicorp/terraform#3413]
### AWS VPC Endpoint Enhancement

Terraform allows to create and manage the AWS VPC Endpoint functionality. This is working fine out of the box while being used with instances that come with unrestricted outbound traffic. However if an EC2 instance has no internet connectivity this does not work out of the box any more since the relevant security groups also have to be configured by using the the AWS Prefix List. **The problem** is that Terraform does not currently allow a Prefix List ID to be associated with a security group and neither can Terraform retrieve the ID of such Prefix List ID.

Such Prefix List ID looks like `pl-1a2b3c4d`.

### Use Case
The problem is encountered when AWS VPC Endpoint is used VPC subnets that do not allow outbound traffic on port 443 to be routed to the internet. To enable such EC2 instances located within such VPC to access AWS S3, the associated security group must contain an outbound rule that allows traffic to be sent on port 443 to the IP Range that is defined with the AWS Prefix List item.

See below website for details:
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints.html

As it currently stands, it's not possible with Terraform to associate a Prefix List ID with a security group rule. In contrast, it's possible to do this by using the AWS Console (go to `VPC Dashboard` -> `Security Groups`). In the light of this I am suggesting the following enhancement.

### Enhancement

1. Create a new resource `aws_prefix_list` that allows to retrieve the Prefix List ID by using the Prefix List Name (e.g. `com.amazonaws.eu-west-1.s3`)
http://docs.aws.amazon.com/sdk-for-go/api/service/ec2/EC2.html#DescribePrefixLists-instance_method

2. Enable the `aws_security_group_rule` resource to associate Prefix List IDs.

### Usage Example
Below is a code example on how someone could use this enhancement.

```
resource "aws_security_group" "example" {
    name = "example"
    description = "Shows how it could be possible to associate a prefix list"

    egress {
        from_port = 443
        to_port = 443
        protocol = "tcp"
        prefix_list = ["${aws_prefix_list.s3.id}"]
    }
```

> Note: The `aws_prefix_list.s3` command would look up the current region and constructs the prefix list name accordinly. For example if the VPC is in the region `eu-west-1` then the Prefix List Name would be `com.amazonaws.eu-west-1.s3`. This prefix list name is then used to look up the Prefix List ID.

### Workaround

1. Spin up the AWS VPC with Terraform
2. Use the AWS CLI tool to look up the Prefix List item, for example with this command
` aws ec2 describe-prefix-lists --filters Name="prefix-list-name",Values="com.amazonaws.eu-west-1.s3" --region eu-west-1`
3. Note down the AWS IP Range (CIDR)
4. Alter the relevant security group rules within Terraform by using the CIDR

> Alternatively, the Prefix List ID can be associated with the security group rule manually by using the AWS Console (go to `VPC Dashboard` -> `Security Groups`).

**Comment by phinze** [comment]
Thanks for the detailed writeup, @quater! On first glance this looks like a perfectly reasonable enhancement. :+1:

**Comment by steve-jansen** [comment]
:+1: 

Note to self: seems [expandIPPerms](https://github.com/hashicorp/terraform/blob/v0.6.8/builtin/providers/aws/structure.go#L131-L208) function needs to support the `PrefixListIds` field of  the [IpPermission] (http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html) type, which is used by [CreateSecurityGroup](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSecurityGroup.html).

**Comment by vbichov** [comment]
Hi,
Just stumbled on this issue when trying to define security group for s3.
What are the changes that this enhancement will be implemented in the near future?

**Comment by jszwedko** [comment]
This would be phenomenal.

**Comment by josh-padnick** [comment]
+1 on this. Our use case is that we'd like to use Vault with an S3 backend but that requires that traffic leave the VPC unless we use a VPC Endpoint, but since the Security Groups don't support the Prefix List Id, we can't use the VPC endpoints.

**Comment by chicagobuss** [comment]
+1 for us as well.  VPCs without internet access but still with access to s3 via vpc endpoints are one of the primary reasons we want to use AWS but we would like to terraform this infrastructure!

**Comment by stevehorsfield** [comment]
Hi all,

This is a note to let you know that I'm working on this and nearly complete, in case someone else was going to look at it.

I'm working on this but fairly new to terraform. I have draft changes here: https://github.com/stevehorsfield/terraform/tree/d/stevehorsfield_prefix_list_support but will create a new branch once final and issue a pull request. I hope to do that today.

The code successfully creates a security group linked to a prefix list on an endpoint. There are some failing security group acceptance tests that I'm currently working on as it's quite likely that some of my code broke a couple of them.

I'm recommending a slightly different approach than the suggestion above in that I don't see a prefix list as a resource—there isn't an action you take to create one. Therefore, I've exposed the prefix list ID as an attribute on a `vpc_endpoint`. Comments welcome, of course:

```
resource "aws_vpc" "tf_sg_prefix_list_egress_test" {
    cidr_block = "10.0.0.0/16"
    tags {
            Name = "tf_sg_prefix_list_egress_test"
    }
}

resource "aws_route_table" "default" {
    vpc_id = "${aws_vpc.tf_sg_prefix_list_egress_test.id}"
}

resource "aws_vpc_endpoint" "s3-us-west-2" {
  	vpc_id = "${aws_vpc.tf_sg_prefix_list_egress_test.id}"
  	service_name = "com.amazonaws.us-west-2.s3"
  	route_table_ids = ["${aws_route_table.default.id}"]
  	policy = <<POLICY
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid":"AllowAll",
			"Effect":"Allow",
			"Principal":"*",
			"Action":"*",
			"Resource":"*"
		}
	]
}	
POLICY
}

resource "aws_security_group" "egress" {
    name = "terraform_acceptance_test_prefix_list_egress"
    description = "Used in the terraform acceptance tests"
    vpc_id = "${aws_vpc.tf_sg_prefix_list_egress_test.id}"
  
    egress {
      protocol = "-1"
      from_port = 0
      to_port = 0
      prefix_list_ids = [${aws_vpc_endpoint.s3-us-west-2.prefix_list_id}]
    }
}
```

**Comment by stevehorsfield** [comment]
Pull request submitted (see #6872 above).

**Comment by quater** [comment]
@stevehorsfield Thank you for your pull request! It's very much appreciated!

I will hopefully get around looking into this within the next two weeks and will report back.

**Comment by stevehorsfield** [comment]
Thank you @quater. If I get an opportunity, I'll update the PR to resolve the merge conflicts that have since been introduced, but I may not have the time.

**Comment by quater** [comment]
This appears to be working fine as it is. Please see attached Gist for a minimal use case. [https://gist.github.com/quater/c58448c8796a5eeee736147f5660b75f](https://gist.github.com/quater/c58448c8796a5eeee736147f5660b75f)

Tested with #7319.

@phinze Can this feature be added to the next release?

**Comment by catsby** [comment]
Will be added in #7511, thanks!
