### ISSUE TITLE
Azure access package association 

### ISSUE THREAD

**Issue by muhammadumeruzair** [hashicorp/terraform#34139]
### Terraform Version

```shell
terraform 1.6.0 x64
```

### Terraform Configuration Files

```terraform
resource "azuread_access_package_assignment_policy" "this" {
  depends_on = [
    azuread_access_package.this,
    azuread_access_package_resource_catalog_association.this,
    azuread_access_package_resource_package_association.this

  ]
```

### Debug Output

Error: Retrieving access package assignment policy with object ID: "xxxxxxx-xxxxxxx-xxxxxx-xxxxxx"
│ 
│   with module.az_aad_access_packages[0].azuread_access_package_assignment_policy.this[0],
│   on ..xxxxx/xxxxx/xxxxxx/main.tf line xx, in resource "azuread_access_package_assignment_policy" "this":
│   xx: resource "azuread_access_package_assignment_policy" "this" {
│ 
│ AccessPackageAssignmentPolicyClient.BaseClient.Get(): unexpected status 403
│ with OData error: UnAuthorized: User is not authorized to perform the
│ operation. Reason: Unauthorized

### Expected Behavior

The expected behaviour is to run the Azure Devops pipeline and complete the policy assignment as per below example which shows the full run flow as expected,

module.az_aad_access_packages[0].azuread_access_package_resource_catalog_association.this[0]: Creating...
module.az_aad_access_packages[0].azuread_access_package_resource_catalog_association.this[0]: Creation complete after xs [id=xxx-xxxx-xxxxx-xxxx-xxxxxxx/xxx-xxxx-xxxxx-xxxx-xxxxxxx]
module.az_aad_access_packages[0].azuread_access_package_resource_package_association.this[0]: Creating...
module.az_aad_access_packages[0].azuread_access_package_resource_package_association.this[0]: Creation complete after xs [id=xxx-xxxx-xxxxx-xxxx-xxxxxxx/xxx-xxxx-xxxxx-xxxx-xxxxxxx_xxx-xxxx-xxxxx-xxxx-xxxxxxx/Member]
module.az_aad_access_packages[0].azuread_access_package_assignment_policy.this[0]: Creating...
module.az_aad_access_packages[0].azuread_access_package_assignment_policy.this[0]: Creation complete after xs [id=xxx-xxxx-xxxxx-xxxx-xxxxxxx]

### Actual Behavior

Error: Retrieving access package assignment policy with object ID: "xxxxxxx-xxxxxxx-xxxxxx-xxxxxx"
│ 
│   with module.az_aad_access_packages[0].azuread_access_package_assignment_policy.this[0],
│   on ..xxxxx/xxxxx/xxxxxx/main.tf line xx, in resource "azuread_access_package_assignment_policy" "this":
│   xx: resource "azuread_access_package_assignment_policy" "this" {
│ 
│ AccessPackageAssignmentPolicyClient.BaseClient.Get(): unexpected status 403
│ with OData error: UnAuthorized: User is not authorized to perform the
│ operation. Reason: Unauthorized

### Steps to Reproduce

The Terraform module block has been created as per the details provided under below providers link,

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/access_package_assignment_policy

### Additional Context

We are trying to deploy the Azure access package solution through the Azure Devops pipeline Service role which has the following permissions associate to it,

- Identity Governance Administrator
- Directory.ReadWrite.All

The pipeline is designed to deploy a new Catalogue, a AAD group and then creation of Access Package and Policy association. The flow successfully creates the catalogue and a group but when the flow starts to runs the policy association it fails to deploy it and throws an error indicating that the object id used for policy association is unauthorised. 

Some of the ids and reference has been replaced with "x" instead due to security reasons but further details/clarification can be provided if required. 

### References

None

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
