### ISSUE TITLE
Add "enabled" meta argument 

### ISSUE THREAD

**Issue by kishaningithub** [hashicorp/terraform#34147]
### Terraform Version

```shell
Terraform v1.5.4
on darwin_arm64
```

### Use Cases

Most of the time we use the count meta argument to check whether we need to create a resource or not but the con of this is that this results in creating an address path with `[0]` meaning say in the future we would like to enable this resource or module in all environments if we drop the count meta argument the plan would say we need to recreate the resource since the address path has changed, given a recreate is un-desirable we always leave it as `count = 1` which is a bit ugly in my opinion

### Attempted Solutions

```terraform
resource "aws_s3_bucket" "this" {
  count  = var.require_bucket ? 1 : 0
  <lots of other config parameters>
}
```

but whenever the business use case changes to enable this for all use cases the code changes to
```terraform
resource "aws_s3_bucket" "this" {
  count  = 1
  <lots of other config parameters>
}
```

Given a recreate us un-desirable we always leave the `count` as `1`

### Proposal

Kindly create a new boolean meta argument "enabled" which can allow people to conditionally add or remove resources/modules.

```terraform
resource "aws_s3_bucket" "this" {
  enabled  = var.require_bucket
  <lots of other config parameters>
}
```

So that when business use case demads we create the resource everywhere it becomes

```terraform
resource "aws_s3_bucket" "this" {
  <lots of other config parameters>
}
```

Notice `enabled` is no longer needed

### References

I am not so sure actually

**Comment by liamcervante** [comment]
Hi @kishaningithub, we already have an issue tracking this request at #21953. As such, I will close this issue as a duplicate, and if you want to track any updates you can follow the already existing issue.

Note, you can use the `moved` block to explicitly move resources out of instanced resources without creating them.

For example:

```hcl

// Previous configuration
resource "aws_s3_bucket" "this" {
  count  = var.require_bucket ? 1 : 0
}

// New configuration

resource "aws_s3_bucket" "this" {}

moved {
  from = aws_s3_bucket.this[0]
  to = aws_s3_bucket.this
}

``` 

That workaround should help you remove any `count` arguments you don't need anymore.

Thanks!
