### ISSUE TITLE
Azure Application security Group is being removed.

### ISSUE THREAD

**Issue by kkarballof** [hashicorp/terraform#34156]
### Terraform Version

```shell
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.44.1
+ provider registry.terraform.io/hashicorp/azurerm v3.77.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

Your version of Terraform is out of date! The latest version
is 1.6.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.0, < 4.0"
    }
  }
  required_version = ">= 1.4.0"
}
locals {
  resource_name = var.existing_pep_name == "" ? "${var.source_resource_name}-${var.resource_suffix}" : var.existing_pep_name
  # Assign either resource or data outputs depending on whether an existing private endpoint has been specified
  resource_id                = var.existing_pep_name == "" ? azurerm_private_endpoint.pep[0].id : data.azurerm_private_endpoint_connection.pep[0].id
  private_ip_address         = var.existing_pep_name == "" ? azurerm_private_endpoint.pep[0].private_service_connection[0].private_ip_address : data.azurerm_private_endpoint_connection.pep[0].private_service_connection[0].private_ip_address
  private_service_connection = var.existing_pep_name == "" ? azurerm_private_endpoint.pep[0].private_service_connection : data.azurerm_private_endpoint_connection.pep[0].private_service_connection

}

resource "azurerm_private_endpoint" "pep" {
  count               = var.existing_pep_name == "" ? 1 : 0 # If an existing name has not been specified, create new resource
  name                = local.resource_name
  location            = var.location
  resource_group_name = var.network_rg
  subnet_id           = var.subnet_id
  tags                = var.tags
  private_dns_zone_group {
    name = var.source_resource_name # name of resource that the private endpoint is for

    #private_dns_zone_ids = [data.azurerm_private_dns_zone.dns_zone.id] # specifies the list of Private DNS Zones to include
    private_dns_zone_ids = var.private_dns_zone_ids
  }
  private_service_connection {
    name                           = var.resource_prefix
    private_connection_resource_id = var.resource_id
    subresource_names              = var.subresource_name
    is_manual_connection           = false
  }

  lifecycle {
    ignore_changes = [ip_configuration]
  }

}

resource "azurerm_private_endpoint_application_security_group_association" "asg" {
  count                         = var.existing_pep_name == "" ? 1 : 0 # If an existing name has not been specified, create new resource
  private_endpoint_id           = azurerm_private_endpoint.pep[count.index].id
  application_security_group_id = var.application_security_group_id
  depends_on                    = [azurerm_private_endpoint.pep]
}

data "azurerm_subscription" "current" {}

/*resource "null_resource" "add_asg" {
  count = var.existing_pep_name == "" ? 1 : 0
  triggers = {
    run_always = timestamp()
  }

  provisioner "local-exec" {
    on_failure  = continue
    interpreter = ["/bin/bash", "-c"]
    command     = <<EOT
    az login --identity 
    az network private-endpoint asg add --resource-group ${azurerm_private_endpoint.pep[count.index].resource_group_name} --endpoint-name ${azurerm_private_endpoint.pep[count.index].name} --asg-id ${var.application_security_group_id} --subscription ${data.azurerm_subscription.current.subscription_id}
    EOT
  }
  depends_on = [
    azurerm_private_endpoint_application_security_group_association.asg,
  ]
}*/

data "azurerm_private_endpoint_connection" "pep" {
  count               = var.existing_pep_name == "" ? 0 : 1 # If an existing name has not been specified, create new resource
  name                = var.existing_pep_name
  resource_group_name = var.existing_pep_rg
}

### Debug Output

After a re apply the of this module asgs are removed and TF state has knowledge about it

### Expected Behavior

asg should remain set

### Actual Behavior

asg got removed

### Steps to Reproduce

init
apply
re-apply

### Additional Context

Is there a way we can pass a life cycle block for avoiding this issue? local exec was added to attempt to mitigate the issue.

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by kkarballof** [comment]
Its definitively a bug:
Somehow azurerm_private_endpoint removes application security groups that were associated with azurerm_private_endpoint_application_security_group_association

**Comment by jbardin** [comment]
Hi @kkarballof,

If Terraform has applied your changes successfully, but the remote infrastructure does not reflect those changes, then this may be a [bug in the provider](https://github.com/hashicorp/terraform-provider-azurerm/issues). If you are not sure exactly what might be going on, then the [Azure category](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) in the community forums will help users that may be able to help narrow down the problem.
