### ISSUE TITLE
Support connection block on data sources

### ISSUE THREAD

**Issue by Kralizek** [hashicorp/terraform#34151]
### Terraform Version

```shell
terraform version
Terraform v1.6.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.77.0
+ provider registry.terraform.io/pgssoft/mssql v0.6.0
```

### Use Cases

I need to create a login and a user on a Azure SQL server behind firewall.

I want to use a bastion server rather than open a firewall exception.

Resources support the `connection` block but data resources don't

### Attempted Solutions

No real solution but to keep opening the firewall exception or change the data sources to some script to get the same data by using a remote exec provisioner.

### Proposal

Align data sources with resources and make it possible to use the `connection` block.

```hcl
data "mssql_database" "database" {
  name = var.database_name

  // doesn't work today
  connection {
    host        = var.bastion.host
    type        = var.bastion.type
    user        = var.bastion.user
    private_key = var.bastion.private_key
  }
}

resource "mssql_sql_login" "user" {
  name                = local.login_name
  password            = local.password
  default_database_id = data.mssql_database.database.id

  must_change_password      = var.must_change_password
  check_password_expiration = var.check_password_expiration
  check_password_policy     = var.check_password_policy

  connection {
    host        = var.bastion.host
    type        = var.bastion.type
    user        = var.bastion.user
    private_key = var.bastion.private_key
  }
}
```

**Comment by jbardin** [comment]
Hi @Kralizek,

I think you are misunderstanding what a `connect` block is. It does not apply to a resource, a `connection` block is part of a _provisioner_, which while written in the configuration with a resource block so automatically associated the provisioner with that resource, it is unrelated to the resource itself. The `connection` block in `mssql_sql_login` does nothing in your configuration, and allowing in the data source would also accomplish nothing.

I think what you are asking for is a feature request from the provider, in which case you can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have more questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by Kralizek** [comment]
Thanks you so much and sorry for the waste of time :)
