### ISSUE TITLE
tf plan detects the storage bucket lifecycle change even the code has not changed

### ISSUE THREAD

**Issue by deloittedojo** [hashicorp/terraform#34155]
### Terraform Version

```shell
1.5.0
```

### Terraform Configuration Files

```resource "google_storage_bucket" "bucket" {
  name           = "test1"
  project        = "projectA"
  location       = "us-central1"
  public_access_prevention = "enforced"
  
  ## move the logs to archive after 1 year
  lifecycle_rule {
    condition {
      age = 365
    }
    action {
      type = "SetStorageClass"
      storage_class = "Archive"
    }
  }

  ## delete the logs after 7 year

  lifecycle_rule {
    condition {
      age = 2555
    }
    action {
      type = "Delete"
    }
  }

}
```

### Debug Output

It says 1 to change in a lifecycle block

### Expected Behavior

No change in tf plan

### Actual Behavior

1 to change 

### Steps to Reproduce

terraform init
terraform plan
terraform apply
terraform plan

**Comment by jbardin** [comment]
Hi @deloittedojo

This appears to be a question or an issue with a provider, not with Terraform itself. Your example doesn't specify which provider, but you can check existing issues and file a new one in that provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

I would also suggest when encountering bug, to verify it using the latest release. There have been a number of v1.5 patch releases fixing many known issues already.

Thanks!
