### ISSUE TITLE
Terraform-provider-aws_v3.55.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by jatin-gupta01** [hashicorp/terraform#34166]
### Terraform Version

```shell
Terraform v1.4.6
terragrunt version v0.43.2
```

### Debug Output

Error: The terraform-provider-aws_v3.69.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

time=2023-10-31T04:26:27Z level=error msg=Terraform invocation failed in /root/source_code/terragrunt/prod/authentication/.terragrunt-cache/_2iGjnV0HXcGbYXm7d-gL3qf26Q/tPkjowype6-59Nec1bLCw9R-q9o prefix=[/root/source_code/terragrunt/prod/authentication] 
time=2023-10-31T04:26:27Z level=error msg=1 error occurred:
        * [/root/source_code/terragrunt/prod/authentication/.terragrunt-cache/_2iGjnV0HXcGbYXm7d-gL3qf26Q/tPkjowype6-59Nec1bLCw9R-q9o] exit status 1
Exited with code exit status 1

### Expected Behavior

Terraform plan should work properly as haven't made any changes related to the tf versions.

### Actual Behavior

Getting the error that the terraform plugin crashed during Terraform plan 

### Steps to Reproduce

terragrunt init 
terragrunt plan

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
