### ISSUE TITLE
avi provider - avi_serviceenginegroup

### ISSUE THREAD

**Issue by surendragupta481** [hashicorp/terraform#34160]
### Terraform Version

```shell
Terraform v1.6.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/vsphere v2.5.1
+ provider registry.terraform.io/vmware/avi v22.1.4
```

### Terraform Configuration Files

![image](https://github.com/hashicorp/terraform/assets/72605261/a1662518-2460-469b-b6e1-6dffa6230ca8)

### Debug Output

Output not available 

### Expected Behavior

nsxt datastore value should be assigned. 

![image](https://github.com/hashicorp/terraform/assets/72605261/867f9e00-eca6-4324-bc73-3249dba610bd)

### Actual Behavior

nsxt datastore value is any rather than shared 

![image](https://github.com/hashicorp/terraform/assets/72605261/a6072cde-e3c9-4136-9ca7-10880b89739f)

### Steps to Reproduce

1. terraform init
2. terraform plan 
3. terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
