### ISSUE TITLE
fetch AWS sftp server endpoint configuration IPs to be used in target group attachment 

### ISSUE THREAD

**Issue by johankayati2019** [hashicorp/terraform#34165]
### Terraform Version

```shell
1.6.2
```

### Use Cases

Create SFTP server where we provide Endpoint configuration (subnet IDs). This generates IPs and assign the IPs under endpoint configuration. 

We need to use these IPs which created inside Load balancer target group attachment.

currently the data block of transfer_server does not provide attribute to get the IPs.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/transfer_server

### Attempted Solutions

allow to fetch IPs via data block of aws transfer server 

### Proposal

allow to fetch IPs via data block of aws transfer server

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by johankayati2019** [comment]
How is it issue of aws?
The data block does not give option to fetch ips from endpoint
configuration.

Can you please tell me if there is any alternative way we can get to via
terraform?

**Comment by jbardin** [comment]
Hi @johankayati2019, the `aws_transfer_server` data source is part of the aws provider. If that data source is missing a feature, then it would have to be implemented by that provider. If you have a question about how to use that data source, then the AWS topic in the forum would be a better resource. Terraform core does not interact with AWS on its own.
