### ISSUE TITLE
https://registry.terraform.io/ - cookies "accept" button will not go away

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform#34175]
### Terraform Version

```shell
N/A
```

### Terraform Configuration Files

I am not sure where to post this issue - so hopefully this finds its way to the correct location...

https://registry.terraform.io/

When I go to the above page I see the cookies accept button at the bottom of the page.

However clicking the button does nothing - the button just stays there.

This is extra annoying on a mobile phone page as the accept button sits on top of (and hides) other documentation.

### Debug Output

N/A

### Expected Behavior

Accept button should go away when it is clicked.

### Actual Behavior

Accept button does not go away when it is clicked.

### Steps to Reproduce

N/A

**Comment by crw** [comment]
Hi @scott-doyland-burrows, thanks for this report. The registry does not have a method for the public to report issues. That said, I will pass along this feedback to the team. Thanks again for this report!

**Comment by crw** [comment]
@scott-doyland-burrows Can you please report your OS and browser model and version?

**Comment by scott-doyland-burrows** [comment]
Thanks for the reply.  Details below

Windows 10 19044.3086
Edge 118.0.2088.76
Chrome 118.0.5993.118
And on Firefox

Android 13
Chrome 118.0.5993.111

So seems like the OS/browser makes no difference.

**Comment by crw** [comment]
The good news is the registry team is aware of this issue and working on it.
