### ISSUE TITLE
Resource 'template_file.xxx' does not have attribute 'rendered' for variable 'template_file.xxx.rendered'

### ISSUE THREAD

**Issue by mattsoftware** [hashicorp/terraform#3417]
After modifying the template referenced with new content, terraform does not seem to be able to render my file anymore. I cannot even destroy my infrastructure to fix the issue :/

---

```
matts-air:stage1singapore matt$ terraform plan
Error configuring: 1 error(s) occurred:

* Resource 'template_file.stage_users' does not have attribute 'rendered' for variable 'template_file.stage_users.rendered'
```

---

```
matts-air:stage1singapore matt$ terraform destroy
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

Error configuring: 1 error(s) occurred:

* Resource 'template_file.stage_users' does not have attribute 'rendered' for variable 'template_file.stage_users.rendered'
```

---

**Comment by philp** [comment]
We experience exactly the same issue when running `terraform destroy`.

**Comment by mattsoftware** [comment]
I dont know how to fix this without blowing my infrastructure away, I cannot seem to taint that one resource...

matts-air:stage1singapore matt$ terraform plan -module-depth=2
Error configuring: 1 error(s) occurred:

* Resource 'template_file.stage_users' does not have attribute 'rendered' for variable 'template_file.stage_users.rendered'

matts-air:stage1singapore matt$ terraform taint template_file.stage_users
The resource template_file.stage_users couldn't be found in the module root.

... I thought I could just apply that one resource to hope to get it to refresh, but no...

matts-air:stage1singapore matt$ terraform apply -target=template_file.stage_users
Error configuring: 1 error(s) occurred:

* Resource 'template_file.stage_users' does not have attribute 'rendered' for variable 'template_file.stage_users.rendered'

... I thought I would just copy the config, but if I add a new template_file with the name stage_users_2 now that one is not able to be rendered...

matts-air:stage1singapore matt$ terraform plan -module-depth=2
Error configuring: 1 error(s) occurred:

* Resource 'template_file.stage_users_2' does not have attribute 'rendered' for variable 'template_file.stage_users_2.rendered'

... I am at a loss :/

**Comment by mattsoftware** [comment]
I should mention returning the original file back to what it looked like before the changes, does not make a difference, it still does not have the rendered attribute

**Comment by mattsoftware** [comment]
My solution for the moment involves commenting out the line that uses the rendered template, and replace it with a line with an empty string, run apply, then put the rendered variable back, run apply again. So only the resources that use the template will be touched, but they will be modified twice instead of just the once.

**Comment by shanesveller** [comment]
I wound up bumping into this through user error:

My template had a count, my aws_instance had a count, both based on the same variable, but the instance originally looked for a singular template resource, with the according syntax. I had to switch to using `element(template_file.foo.*.rendered, count.index)` where I was calling it previously.

**Comment by chadgrant** [comment]
Still happening in 0.7.7 and with the new data.template_file. replacing it with empty string still allowing you to destroy it.

**Comment by luisdavim** [comment]
I got this using 0.9.8, the solution was to set the vars to empty string, plan and apply and then revert them back to what it was and plan and apply again, like @mattsoftware mentioned...

**Comment by edward2a** [comment]
I just hit this with google provider referencing resources into module variables from other resources and also from the random module.

Given multiple issues available with similar symptoms, should not this be considered a more central problem to TF rather than provider specific?

Cheers,
Ed

**Comment by teamterraform** [comment]
Hi @edward2a! If you're finding similar issues, please open a new issue with references to the other issues you speak of, if you believe this to be an upstream issue. Closed issues over 30 days old are being locked moving forward, so I'll lock this now to avoid confusion.
