### ISSUE TITLE
Terraform Test: add option to send variables to the init module

### ISSUE THREAD

**Issue by ron-matsliah** [hashicorp/terraform#34179]
### Terraform Version

```shell
Terraform v1.6.3
```

### Use Cases

When running the new Terraform testing framework, we would like to send parameters to the init module so it will be dynamic

### Attempted Solutions

We tried to send vars with the variables block - without success
We tried to pass vars using -var flags - without success

### Proposal

Add the ability to send parameters in the module block, for example:
```
run "init" {
  module {
    source      = "./tests/setup-infra"

    variables {
      vpc_cidr    = "10.8.112.0/24"
    }
  }
}
```

**Comment by liamcervante** [comment]
Hi @ron-matsliah, thanks for filing this.

You can reuse the existing variables block for this, that exists within the scope of the run block itself:

```hcl
run "init" {
  module {
    source = "./tests/setup-infra"
  }

  variables {
    vpc_cidr = "10.8.112.0/24"
  }
}
```

Any variables defined within the `variables` block of the test file are also passed through.

Thanks!
