### ISSUE TITLE
aws_route_table_association cannot take multi ID

### ISSUE THREAD

**Issue by k-nishigaki** [hashicorp/terraform#3418]
"aws_route_table_association" resource is associate route table to subnet.
but it can only one to one association between "route table" and "subnet".
(AWS can associate one to many between "route table" and "subnet".)

Following 

subnets are created yet.

```
resource "aws_subnet" "sn-public-1a" {
	vpc_id = "${aws_vpc.vpc.id}"
	cidr_block = "xxxxxxxxxxx"
	availability_zone = "ap-northeast-1a"
}
resource "aws_subnet" "sn-public-1c" {
	vpc_id = "${aws_vpc.vpc.id}"
	cidr_block = "xxxxxxxxxxx"
	availability_zone = "ap-northeast-1c"
}
```

Success template

```
resource "aws_route_table_association" "public-assoc" {
   subnet_id = "${aws_subnet.sn-public-1a.id}"
   route_table_id = "${aws_route_table.alp-omk-rt-public.id}"
}
```

Failed template

```
resource "aws_route_table_association" "public-assoc" {
    subnet_id = ["${aws_subnet.sn-public-1a.id}","${aws_subnet.public-1c.id}"]
    route_table_id = "${aws_route_table.alp-omk-rt-public.id}"
}
```

**Comment by apparentlymart** [comment]
I believe the intended way to do what you want here is to have more than one association resource, like this:

```js
resource "aws_route_table_association" "public-assoc" {
   subnet_id = "${aws_subnet.sn-public-1a.id}"
   route_table_id = "${aws_route_table.alp-omk-rt-public.id}"
}
resource "aws_route_table_association" "public-assoc" {
   subnet_id = "${aws_subnet.sn-public-1c.id}"
   route_table_id = "${aws_route_table.alp-omk-rt-public.id}"
}
```

**Comment by phinze** [comment]
Hi @k-nishigaki, good question!

Because Terraform must declaratively manage each association as a logical resource, we choose the verbose but straightforward option of fanning everything out as 1:1 declarations, as @apparentlymart's example correctly shows.

We may in the future explore features that help make Terraform config shorter, but our focus at this point is on correctness over conciseness.

**Comment by k-nishigaki** [comment]
Hi @phinze , thank you for answer.

I understand your development policy.
I use @apparentlymart 's example.

thanks.

**Comment by plombardi89** [comment]
+1

It's unfortunate Terraform doesn't support this because it makes adapting different configurations across regions with different subnet counts (due to different numbers of AZ's) difficult.

**Comment by setswei** [comment]
+1 i agreed it would be great if multiple subnet_ids could be supported in one line

**Comment by thompsm** [comment]
With terraform 0.10.4, this seems to work:

```
variable "vpc_subnet_ips" { type="list", default = ["10.99.0.0/27", "10.99.128.0/27", "10.99.192.0/27"] }

resource "aws_subnet" "subnets" {
  count             = "${length(var.vpc_subnet_ips)}"
  vpc_id            = "${aws_vpc.vpc.id}"
  cidr_block        = "${element(var.vpc_subnet_ips, count.index)}"
  availability_zone = "${element(var.vpc_subnet_azs, count.index)}"

  tags {
    Name = "${element(var.vpc_subnet_names, count.index)}"
  }
}

resource "aws_default_route_table" "default_route" {
  default_route_table_id = "${aws_vpc.vpc.default_route_table_id}"
}

resource "aws_route_table_association" "subnets" {
  count          = "${length(var.vpc_subnet_ips)}"
  subnet_id      = "${element(aws_subnet.subnets.*.id, count.index)}"
  route_table_id = "${aws_default_route_table.default_route.id}"
}
```

So you can use the count and element interpolations to get each subnet id in turn.

Hope this helps.

**Comment by rajeev8080** [comment]
Very Nice , It works
resource "aws_route_table_association" "subnets" {
  count          = "${length(var.vpc_subnet_ips)}"
  subnet_id      = "${element(aws_subnet.subnets.*.id, count.index)}"
  route_table_id = "${aws_default_route_table.default_route.id}"
}

**Comment by results-may-vary** [comment]
Hi, I'd like your assistance with a similar problem; I'm trying to count specific subnets labeled "public" and I'm getting with:

data "aws_subnet_ids" "public" {
  vpc_id = "${aws_vpc.main.id}"
  tags {
    Tier = "Public"
  }
}

Then, based on this output I'm trying to count them so I can perform the _aws_route_table_association_: 

resource "aws_route_table_association" "Public_rtb_association" {
  count          = "${length(data.aws_subnet_ids.public.ids)}"
  subnet_id      = "${element(data.aws_subnet_ids.public.id, count.index)}"
  route_table_id = "${aws_route_table.Public_route_table.id}"
}
Finally, when running Plan I'm getting the error "value of 'count' cannot be computed".
Any ideas would be appreciated.
Thanks.

Gabby

**Comment by kylecompassion** [comment]
I'm running into the multi ID error. using TF 0.11.13. I've reviewed what thompsm and rajeev say works and dont see anything significantly different as far as i can tell, yet it doesnt seem to work for me.  subnet_count = 3 in this instance. what am i doing differently that it doesnt work?

resource "aws_route_table_association" "cluster_rta" {
  count          = "${var.subnet_count}"
  subnet_id      = "${aws_subnet.cluster_subnet.*.id[count.index]}"
  route_table_id = "${aws_route_table.cluster_rtb.id}"
}

results in this error:

Error: Error refreshing state: 1 error(s) occurred:
* aws_route_table_association.cluster_rta: 2 error(s) occurred:
* aws_route_table_association.cluster_rta[1]: index 1 out of range for list aws_subnet.cluster_subnet.*.id (max 1) in:
${aws_subnet.cluster_subnet.*.id[count.index]}
* aws_route_table_association.cluster_rta[2]: index 2 out of range for list aws_subnet.cluster_subnet.*.id (max 1) in:
${aws_subnet.cluster_subnet.*.id[count.index]}
