### ISSUE TITLE
Using sensitive values in subsequent run blocks of terraform test not possible: value has marks

### ISSUE THREAD

**Issue by breml** [hashicorp/terraform#34185]
### Terraform Version

```shell
$  terraform version
Terraform v1.6.3
on linux_amd64
```

### Terraform Configuration Files

In my actual scenario I use terraform to create a new deployment in Elastic Cloud. As part of this creation process in the first `run` block of the terraform test, I get (among a lot of other information) the URI, username and password needed to contact the Elasticsearch instance. This information is then used in a subsequent `run` block to access the Elasticsearch instance and to query the clusters health state.

I have created the following minimal example to show case the issue. 

File structure:

```none
.
├── examples
│   └── mymodule
│       ├── main.tf
│       └── tests
│           ├── checkmore
│           │   └── main.tf
│           └── mymodule.tftest.hcl
└── mymodule
    └── outputs.tf
```

Files:

`mymodule/outputs.tf`

```terraform
output "password" {
  value     = "foobar"
  sensitive = true
}
```

`examples/mymodule/main.tf`

```terraform
module "mymodule_example" {
  source = "../../mymodule"
}

output "mymodule_example_password" {
  value     = module.mymodule_example.password
  sensitive = true
}
```

`examples/mymodule/tests/mymodule.tftest.hcl`

```hcl
run "mymodule" {
  command = apply

  assert {
    condition     = output.mymodule_example_password == "foobar"
    error_message = "Unexpected password"
  }
}

run "dependent_test" {
  command = apply

  module {
    source = "./tests/checkmore"
  }

  variables {
    secretvalue = run.mymodule.mymodule_example_password
  }

  assert {
    condition     = output.secretvalue == "foobar"
    error_message = "Unexpected secretvalue"
  }
}
```

`examples/mymodule/tests/checkmore/main.tf`

```terraform
variable "secretvalue" {
  type = string
}

output "secretvalue" {
  value     = var.secretvalue
  sensitive = true
}
```

### Debug Output

not provided

### Expected Behavior

The credentials returned during resource creation in a first `run` step should then be available in the subsequent `run` steps.

### Actual Behavior

I always get the following error from terraform:

```none
│ Error: Failed to prepare variable value for plan
│
│ The value for variable "password" could not be serialized to store in the plan: value has marks, so it cannot be serialized.
```

### Steps to Reproduce

1. `cd examples/mymodule`
2. `terraform init`
3. `terraform test`

**Comment by liamcervante** [comment]
Hi @breml, thanks for filing this! I can replicate this, so I will mark it as confirmed.

Essentially, what's happening here is that Terraform is trying to ensure that we don't accidentally expose any information marked as sensitive. It is being too protective though, as you should be able to do what you're trying to do. This should be a fairly simple fix.

As an aside, I note that you don't have the `secretvalue` input variable marked as sensitive. The fix I have in mind for this means that Terraform would produce a warning in this case, stating that the previous value was sensitive and when applied to a non-sensitive variable then the sensitivity metadata will be lost. I will discuss this with others in the team, as it might be that we should actually explicitly fail in this case, in which case you'd have to mark the input variable as also sensitive in order for it to receive sensitive values.

Thanks!

**Comment by breml** [comment]
@liamcervante Thanks for the response and the confirmation. The missing `sensitive` on `secretvalue` is most likely an oversight while creating the reproducible configuration. But anyway, thanks for the hint.
