### ISSUE TITLE
Sensitive values cause resources that did not have any value changed to be updated on terraform plan and apply due to APPINSIGHTS_INSTRUMENTATIONKEY 

### ISSUE THREAD

**Issue by Hrolgar** [hashicorp/terraform#34191]
### Terraform Version

```shell
Terraform v1.6.3
on windows_amd64
+ provider registry.terraform.io/azure/azapi v1.3.0
+ provider registry.terraform.io/hashicorp/azurerm v3.40.0
```

### Terraform Configuration Files

```terraform
resource "azurerm_windows_function_app" "function_app" {
  for_each                   = {for app in local.function_apps_env : app.name => app}
  name                       = each.key
  resource_group_name        = azurerm_resource_group.resource_group.name
  location                   = azurerm_resource_group.resource_group.location
  service_plan_id            = azurerm_service_plan.app_service_plan.id
  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key

  app_settings = {
    FUNCTIONS_WORKER_RUNTIME       = "dotnet-isolated"
    APPINSIGHTS_INSTRUMENTATIONKEY = azurerm_application_insights.app_insights.instrumentation_key
    WEBSITE_RUN_FROM_PACKAGE       = "1"
  }
}
```

### Debug Output

I have no debug for this

### Expected Behavior

I expected nothing to happen, since nothing changed.

### Actual Behavior
```
  # azurerm_windows_function_app.function_app["name-of-app"] will be updated in-place
  ~ resource "azurerm_windows_function_app" "function_app" {
      ~ app_settings                      = {
          + "APPINSIGHTS_INSTRUMENTATIONKEY" = (sensitive value)
            # (2 unchanged elements hidden)
        }
        id                                = "/subscriptions/secret-not-sharing-on-github"
        name                              = "name-of-app"
        tags                              = {
            "Environment-type" = "PROD"
        }
        # (23 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }

```
### Steps to Reproduce

terraform plan or terraform apply

### Additional Context

I saw there was an old issue that was closed in 2020 about this, here : https://github.com/hashicorp/terraform/issues/26959

**Comment by jbardin** [comment]
Hi @Hrolgar,

Thanks for filing the issue. If the resource is not saving the `APPINSIGHTS_INSTRUMENTATIONKEY` value, causing it to be re-added on the next plan, that would be a bug in the resource provider. There may be something useful in the log warnings (`TF_LOG_CORE=warn`) to help the provider developers track down the issue, but my first guess is that the value is not saved correctly in the remote resource and being read back as `null`.

Thanks!

**Comment by Hrolgar** [comment]
![image](https://github.com/hashicorp/terraform/assets/46829592/d0bbaf62-ec71-42dc-97ac-4b2b03bf154c)
I am getting no warnings, and the providers should be up to date.
As you can see on the image, all the time I do a "terraform plan" or "terraform apply" it updates these values, even if I haven't changed anything in that file or resource.

**Comment by jbardin** [comment]
Hi @Hrolgar, If there's no warnings in the logs, then it's probably as a suspected, the resource is being read back from the provider without that value. If you run `plan -refresh-only` immediately after apply does that show any changes? Does the complete plan output have any section indicating "Objects have changed outside of Terraform"?

**Comment by Hrolgar** [comment]
The ``-refresh-only`` seem to have avoided the plans attempt of changing. But without it, it still tells me that they are changed.

**Comment by jbardin** [comment]
Yes, `-refresh-only` does not plan changes, it only "refreshes" the state to match the remote resource. I'm trying to determine when that value goes missing, and if it's something which Terraform could report better. The fact that it is missing at all is still most likely a bug in the provider.

Are there any warnings when _applying_ the change? If you apply the change then immediately run `terraform plan -refresh-only`, what is the complete output?

**Comment by jbardin** [comment]
Sorry, I'm not sure what the that last image is supposed to show. Perhaps the output of `terraform show 'azurerm_windows_function_app.function_app["INSTANCE_KEY"]'` (with the correct instance key of course) might give you some idea where the data has gone missing.

The previous image however also shows the resource _removing_ an `application_insights_key` value, which seems like it could be related. The provider developers would have more context around what how these resources work to help locate the underlying problem.
