### ISSUE TITLE
Terraform detects changes by changing the position of elements in an array

### ISSUE THREAD

**Issue by fmunozmiranda** [hashicorp/terraform#34210]
### Terraform Version

```shell
Terraform v1.1.7
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.6.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

NA

### Expected Behavior

When receiving elements of an array in a different order or changing its position in the .tf file, terraform recognizes changes even though it should not.

### Actual Behavior

NA

### Steps to Reproduce

NA

### Additional Context

TF File I'm trying to use:
```tcl
resource "dnacenter_wireless_profile" "example" {
  provider = dnacenter

  parameters {
    profile_details {
      name  = "Test22"
      sites = ["Global/CR"]

      ssid_details {
        enable_fabric = "true"
        flex_connect {
          enable_flex_connect = "false"
          local_to_vlan       = 0
        }
        interface_name = "management"
        name           = "Test222"
        type           = "string"
      }
      ssid_details {
        enable_fabric = "true"
        flex_connect {
          enable_flex_connect = "false"
          local_to_vlan       = 0
        }
        interface_name = "management"
        name           = "Test22222"
        type           = "eduroam"
      }
    }
  }
}
```

The problem is with ssid_details, if I change their position, terraform detects changes even if they do not exist.

**Comment by apparentlymart** [comment]
Hi @fmunozmiranda,

What you're describing is behavior produced (indirectly) by how this provider is designed.

If the provider schema says that `ssid_details` should be treated as a list then that implies that the ordering of the blocks is somehow significant and therefore a change in order is something that warrants updating the remote object. A provider can alternatively declare that a block type is an unordered set of objects, in which case the order of blocks would not be considered significant and the blocks would be correlated just by their contents, not by their positions.

Therefore if the behavior you found is not desirable then that would need to be corrected in the provider codebase itself, and not in this codebase. I suggest opening an issue in the provider's own repository.

Terraform Core is behaving as the provider schema says it should in this case, and so there's nothing we could change in this repository to improve the situation for this provider. Therefore I'm going to close this issue. Thanks!
