### ISSUE TITLE
Terraform Documentation. "if order" v "in order"

### ISSUE THREAD

**Issue by drthornt** [hashicorp/terraform#3422]
Small little doc bug guys,
(love your work BTW)

https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

"If order to effectively use a Launch Configuration resource with anAutoScaling Group resource, it's recommend to omit the Launch Configuration name attribute, and specify create_before_destroy in a lifecycle block, as shown:"

Should probably be:

"In order order to effectively use a Launch Configuration resource with anAutoScaling Group resource, it's recommend to omit the Launch Configuration name attribute, and specify create_before_destroy in a lifecycle block, as shown:"

Thanks,
David

**Comment by apparentlymart** [comment]
Thanks for reporting this! It looks like this was fixed in f3f9ffea0b8d292b1cc1911a04c881d939ccc488 and so it'll be updated with the next Terraform release.
