### ISSUE TITLE
Provider configuration not present error message states resources exist in state when they do not

### ISSUE THREAD

**Issue by DeLeneMirouze** [hashicorp/terraform#34226]
### Terraform Version

```shell
Terraform v1.6.0
on windows_386
+ provider registry.terraform.io/hashicorp/azurerm v3.80.0


PS: I reproduced it on 1.6.3 Terraform on another computer
```

### Terraform Configuration Files

root module: ./main.tf
------------------------

module "rg" {
  source      = "./modules/resources_group"
  rg_name_dev = "rg1"
  rg_name_ppd = "rg2"
  providers = {
    azurerm = azurerm.ppd
  }
}

provider "azurerm" {
  skip_provider_registration = true
  subscription_id            = "e538e46e-3771-4830-8d3b-df951f8936d9"
  tenant_id                  = "4252c422-cf2e-4079-9fdd-018c2f92703d"

  features {
  }
}

provider "azurerm" {
  skip_provider_registration = true
  subscription_id            = "XXXX"
  tenant_id                  = "YYYY"
  alias                      = "ppd"

  features {
  }
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.80.0"

      configuration_aliases = [ azurerm.ppd ]
    }
  }

  backend "local" {
  }
}

./modules/resources_group/main.tf
-----------------------------------------------

resource "azurerm_resource_group" "rg-dev" {
  name     = var.rg_name_dev
  location = "West Europe"
}

resource "azurerm_resource_group" "rg-ppd" {
  provider = azurerm.ppd
  name     = var.rg_name_ppd
  location = "West Europe"
}

variable "rg_name_dev" {
  type = string
}

variable "rg_name_ppd" {
  type = string
}

terraform {
  required_providers {
    azurerm = {
      source                = "hashicorp/azurerm"
      version               = "=3.80.0"
    }
  }
}

### Debug Output

terraform validate:

│ Error: Provider configuration not present
│ 
│ To work with module.rg.azurerm_resource_group.rg-ppd its original provider configuration at module.rg.provider["registry.terraform.io/hashicorp/azurerm"].ppd is required, but it has been removed. This occurs
│ when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy module.rg.azurerm_resource_group.rg-ppd, after which you
│ can remove the provider configuration again.

### Expected Behavior

validation should succeede

### Actual Behavior

I receive an error message

│ Error: Provider configuration not present
│ 
│ To work with module.rg.azurerm_resource_group.rg-ppd its original provider configuration at module.rg.provider["registry.terraform.io/hashicorp/azurerm"].ppd is required, but it has been removed. This occurs
│ when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy module.rg.azurerm_resource_group.rg-ppd, after which you
│ can remove the provider configuration again.

### Steps to Reproduce

terraform init
terraform validate

### Additional Context

The message is incoherent. There is no previous deployment and anyway it has no sens on validation

I don't know what happened and what I can do

**Comment by liamcervante** [comment]
Hi @DeLeneMirouze, thanks for filing this. The reason for this is because you are attempting to reference the `azurerm.ppd` provider from within the module where it has packaged up as the main provider:

```hcl
resource "azurerm_resource_group" "rg-ppd" {
  provider = azurerm.ppd # <------- Remove this line
  name = var.rg_name_ppd
  location = "West Europe"
}
```

This is because you are taking the alias away within the context of the module: 

```hcl
providers = {
  azurerm = azurerm.ppd
}
```

Is this the first time you are using this configuration? Or are you refactoring something and have renamed the providers? I'm wondering why the validate command thinks the object has been created previously. There may be a bug in there in that we can make the error message better if that resource has never existed.

Thanks!

**Comment by DeLeneMirouze** [comment]
hello

Thank you. Effectively it solved the issue.

But I need to use the pp provider to deploy rg-ppd and the default one for rg-dev.
The sample here is in fact a simplification of a more complex scenario where I need accessing two different subscriptions in a module

How I can solve this in that case?

**Comment by liamcervante** [comment]
You need to define both the providers in the `resources_group` module in the same way you did in the root module:

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=3.80.0"
      configuration_aliases = [ azurerm.ppd ]
    }
  }
}
```

Then pass both the providers into module in your module call:

```hcl
providers = {
  azurerm = azurerm
  azurerm.ppd = azurerm.ppd
}
```

Then you can refer to both the providers within your root module as your are doing in the original configuration.

Hope that makes sense!

**Comment by DeLeneMirouze** [comment]
it's working now!
Thank you

**Comment by DeLeneMirouze** [comment]
solved
