### ISSUE TITLE
Ignore error for not existing parameter

### ISSUE THREAD

**Issue by saintsinnerr** [hashicorp/terraform#34228]
### Terraform Version

```shell
Terraform v1.5.3
```

### Terraform Configuration Files

```terraform
resource "proxmox_vm_qemu" "main" {
  for_each = var.virtual_machines

  name        = each.value["name"]
  target_node = each.value["target_node"]
  desc        = each.value["desc"]
  clone       = each.value["clone_from"]
  full_clone  = var.full_clone
  # Disk Management
  disk {
    size            = each.value["disk_size"]
    storage         = var.disk_destination
    backup          = var.disk_backup
    type            = var.disk_type
    aio             = var.disk_aio
    cache           = var.disk_cache
    iothread        = var.disk_iothread
    detected_zeroes = 1

  }
  dynamic "disk" {
    for_each = var.additional_disk_enabled ? [1] : []
    content {
      size     = each.value["additional_disk_size"]
      storage  = var.additional_disk_destination
      backup   = var.additional_disk_backup
      type     = var.additional_disk_type
      aio      = var.additional_disk_aio
      cache    = var.additional_disk_cache
      iothread = var.additional_disk_iothread
    }
  }
```

### Debug Output

│ Error: proxmox Provider Error: proxmox API returned new disk parameter 'detect_zeroes' we cannot process

### Expected Behavior

ignore disk_zeroed

### Actual Behavior

│ Error: proxmox Provider Error: proxmox API returned new disk parameter 'detect_zeroes' we cannot process

### Steps to Reproduce

terraform init
terraform plan
terraform apply

### Additional Context

Hi,I have raised virtual machines in proxmox cluster with terraform.
Since when provisioning the virtual machines proxmox provider has no parameter to put “detect_zeroed” on disk options ,so I put it then manually,but then I can’t manipulate the machines anymore because I get the following error
: " Error: proxmox Provider Error: proxmox API returned new disk parameter ‘detect_zeroes’ we cannot process" .
Is there an option how to ignore this error or another solution to the problem ?

**Comment by liamcervante** [comment]
Hi @saintsinnerr, thanks for filing this. My understanding here is that this is either a bug with or a feature request for the proxmox provider rather than Terraform core. The Terraform providers are managed independently of Terraform so I will close the issue here and you should reopen with the proxmox provider directly which I think is managed in [terraform-provider-proxmox](https://github.com/Telmate/terraform-provider-proxmox). Thanks!
