### ISSUE TITLE
vpc flow log policy on website is misconfigured

### ISSUE THREAD

**Issue by todd-dsm** [hashicorp/terraform#34231]
### Terraform Version

```shell
Terraform v1.6.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.25.0
```

### Terraform Configuration Files

I'm going through the docs, updating some old configs and I got stuck on the [vpc flow log policy].

```terraform
data "aws_iam_policy_document" "example" {
  statement {
    effect = "Allow"

    actions = [
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:PutLogEvents",
      "logs:DescribeLogGroups",
      "logs:DescribeLogStreams",
    ]

    resources = ["*"]
  }
}
```

The validate and plan seem to go well but the apply squawks:

> _**Error: creating IAM Role (vpc_network_flow_logs_stage_role): MalformedPolicyDocument: Has prohibited field Resource**_

I've been dorking around with it for about an hour; can't seem to figure out what the issue could be. Lots of suggestions out there but I'm missing some fundamental thing 🤷 

Checked my old config and this works fine:

```tf
resource "aws_iam_role_policy" "vpc_network_flow_logs_policy" {
  name = "vpc_network_flow_logs_${var.envBuild}_policy"
  role = aws_iam_role.vpc_network_flow_logs_role.id

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```

So now I'm confused. 

[vpc flow log policy]:https://github.com/hashicorp/terraform-provider-aws/blob/1afa91e024c9c6e7c3bb07f7df17c7134cfc5d2d/website/docs/r/flow_log.html.markdown?plain=1#L48-L62

### Debug Output

https://gist.github.com/todd-dsm/8d1f28026db9f339d8af2dfbcb418ecc

### Expected Behavior

given the same configuration, expressed in 2 different ways, both configurations should deploy the same.

### Actual Behavior

The build errors because of `Resource`, or rather `resources`:

```tf
Error: creating IAM Role (vpc_network_flow_logs_stage_role): MalformedPolicyDocument: Has prohibited field Resource
	status code: 400, request id: 7c016a55-7612-4bff-9c08-7943eed68ab7
```

### Steps to Reproduce

1. initialize a simple build (just take the whole `networing.tf` file and update it)
2. Only change the flow logs from the [old/working policy] to the [new policy] in the TF docs (my networking branch)
3. tf validate and plan work as expected
4. tf apply fails:

> _**Error: creating IAM Role (vpc_network_flow_logs_stage_role): MalformedPolicyDocument: Has prohibited field Resource**_

[old/working policy]:https://github.com/todd-dsm/dev-infras/blob/main/mods/infras/networking.tf#L120-L142
[new policy]:https://github.com/todd-dsm/dev-infras/blob/networking/mods/infras/networking.tf#L118-L133

### Additional Context

currently going through [aws_iam_policy_document] page to see how I have offended terraform. 

If anyone can show me where I've misstepped I'd appreciate it.
 [aws_iam_policy_document]:https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by todd-dsm** [comment]
I'll head in that direction, thank you; closing.
