### ISSUE TITLE
Terraform does not handled dependencies properly

### ISSUE THREAD

**Issue by voroniys** [hashicorp/terraform#34239]
### Terraform Version

```shell
Terraform v1.6.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.71.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Terraform Configuration Files

```terraform
resource "local_file" "setup_script" {
....
}
module "dev_vm" {
....
}
resource "null_resource" "setup_script" {
  depends_on = [module.dev_vm, local_file.setup_script]
  provisioner "local-exec" {
    ....
  }
}
```

### Debug Output

no debug output

### Expected Behavior

On subsequent runs if due to change in parameters resources local_file or vm created by module forces replacement I would expect  that  null_resource which depends on those 2 resources will be force replaced as well. But this does not happen.

### Actual Behavior

The outputs are filtered to show only relevant info.
terraform state list
module.dev_vm["65a62dc3-7c7b-4eee-84e8-1cec019a32c4"].local_file.setup_script
module.dev_vm["65a62dc3-7c7b-4eee-84e8-1cec019a32c4"].module.dev_vm.module.vm.azurerm_windows_virtual_machine.windows_vm[0]
module.dev_vm["65a62dc3-7c7b-4eee-84e8-1cec019a32c4"].null_resource.setup_script

module.dev_vm["6e6f5676-3832-417f-92d9-767d8e6495b8"].local_file.setup_script
module.dev_vm["6e6f5676-3832-417f-92d9-767d8e6495b8"].module.dev_vm.module.vm.azurerm_windows_virtual_machine.windows_vm[0]
module.dev_vm["6e6f5676-3832-417f-92d9-767d8e6495b8"].null_resource.setup_script

terraform plan
# module.dev_vm["65a62dc3-7c7b-4eee-84e8-1cec019a32c4"].local_file.setup_script will be created
# module.dev_vm["6e6f5676-3832-417f-92d9-767d8e6495b8"].local_file.setup_script will be created
# module.dev_vm["65a62dc3-7c7b-4eee-84e8-1cec019a32c4"].module.dev_vm.module.vm.azurerm_windows_virtual_machine.windows_vm[0] must be replaced
# module.dev_vm["6e6f5676-3832-417f-92d9-767d8e6495b8"].module.dev_vm.module.vm.azurerm_windows_virtual_machine.windows_vm[0] must be replaced
Plan: 4 to add, 0 to change, 2 to destroy.

As seen in this filtered plan output local_file resources will be re-created, windows_vm resorces will be replaced, but null_resource.setup_script which is depend on both of them is not replaced, what delivers as a result unconfigured VMs after redeployment

### Steps to Reproduce

1. create a module with the structure as described above:
2. do terraform apply to deploy the resources
3. change parameters to enforce force replacement of VMs
4. delete files created by local_file to ensure its re-creation
5. do terraform apply once more

On the second apply VMs will be replaced, local files will be created, but depended setup_script will not be re-created

### Additional Context

I've tried it with and without depends_on meta-parameter in the null_resource result is always the same - VMs and local files are changed, the script

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by voroniys** [comment]
@jbardin I'm not asking anything, I'm reporting quite a serious bug

**Comment by voroniys** [comment]
@crw this is not a question, this is a bug report!!! 
Please re-open the issue, or should I unerstand that Hashicorp has no interest in fixing bugs in Terraform?

**Comment by voroniys** [comment]
@jbardin Please re-open the issue or I'll post it again. This is quite a serious bug for me.

**Comment by jbardin** [comment]
@voroniys, Terraform appears to be working as designed in your example. The `depends_on` features allow adding dependencies to a resource when there is no value available to reference directly. This ensures evaluation happens in the correct order, but `depends_on` alone should never cause a change in a managed resource.

If you want to trigger replacement on a change in value, you are looking for the [`replace_triggered_by`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by) feature.

**Comment by voroniys** [comment]
@jbardin unlike depends_on replace_triggered_by does not work with modules. So this is not a solution for my case.

**Comment by jbardin** [comment]
@voroniys, if you want to force a resource's replacement based on other resources within a module, you must fashion an output corresponding to the changes you want to act as the trigger for replacement. The `terraform_data` resource (and less flexibly `null_resource`) then can use a change in that value trigger it's own replacement. You would use `replace_triggered_by` with resource types which don't natively have this ability. If you want someone to help guide you through this type of configuration, I suggest you start a conversation in [the community forum](https://discuss.hashicorp.com/c/terraform-core).

Thanks!
