### ISSUE TITLE
Creating Google Cloud API Gateway resources get error stating project ID is not in required format

### ISSUE THREAD

**Issue by dwschewe10** [hashicorp/terraform#34235]
### Terraform Version

```shell
terraform version
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/google v4.84.0
+ provider registry.terraform.io/hashicorp/google-beta v5.5.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```
## root main.tf 
module "api_gateway" {
  source               = "./modules/api_gateway"

  region               = "us-east4"
  project_id           = "pcgke-base-prod-gke-xxxx"
  service_account      = "123456789012-compute@developer.gserviceaccount.com"
  api_id               = "clickopsapi2"
  api_display_name     = "github_runner_api2"
  api_config_id        = "github_gateway_config2"
  api_config_id_prefix = "prefix"
  gateway_id           = "github_gateway2"

}

~   

## versions.tf
terraform {
  required_version = ">= 1.3"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "< 5.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "= 5.5"
    }
  }
}

## main.tf of api gateway module
locals {
  api_config_id_prefix     = var.api_config_id_prefix 
  api_id                   = var.api_id
  gateway_id               = var.gateway_id
  display_name             = var.api_display_name
}

# Create the API Gateway API
###
resource "google_api_gateway_api" "api_gw" {
  provider     = google-beta
  api_id       = local.api_id
  project      = var.project_id
  display_name = local.display_name
}

## Create the API Gateway config
resource "google_api_gateway_api_config" "api_config" {
  provider             = google-beta
  api                  = google_api_gateway_api.api_gw.api_id
  api_config_id_prefix = local.api_config_id_prefix
  project              = var.project_id
  display_name         = local.display_name

  openapi_documents {
    document {
      path = "${path.root}/terraform/modules/api_gateway/spec.yaml"
      contents = filebase64("${path.module}/spec.yaml")
    }
  }
  lifecycle {
    create_before_destroy = true
  }

  gateway_config {
    backend_config {
      google_service_account = var.service_account
    }
  }
}

## Create the API Gateway gateway
resource "google_api_gateway_gateway" "gw" {
  provider = google-beta
  region   = var.region
  project  = var.project_id

  api_config   = google_api_gateway_api_config.api_config.id

  gateway_id   = local.gateway_id
  display_name = local.display_name

  depends_on   = [google_api_gateway_api_config.api_config]
}

### Debug Output

gist

### Expected Behavior

Expect a Google Cloud API gateway, API Gateway config, and API Gateway API are created.

### Actual Behavior

│ Error: Error creating Gateway: googleapi: Error 400: Resource name "projects/761876872866/locations/us-east4/gateways/github_gateway" did not match the required format ^projects/([a-z0-9-]+)/locations/([a-z0-9-]+)(/([a-z]+)/([a-z0-9-.]+))+$
│ 
│   with module.api_gateway.google_api_gateway_gateway.gw,
│   on modules/api_gateway/main.tf line 43, in resource "google_api_gateway_gateway" "gw":
│   43: resource "google_api_gateway_gateway" "gw" {
│ 

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
