### ISSUE TITLE
Use existing network interface when cloning linux template

### ISSUE THREAD

**Issue by markfaine** [hashicorp/terraform#34241]
### Terraform Version

```shell
Terraform v1.6.1
on linux_amd64
```

### Use Cases

I have a base template that is created with packer in vsphere.  Terraform clones this template vm, however the resulting VM has two network interfaces, I suspect this is due to the MAC address changing.  This can cause issues and I have to manually log into the server to delete the second interface.  

### Attempted Solutions

I have tried to delete the interface as a post provisioner task in packer but that fails due to packer no longer having a network co connection (obviously). 

I am currently trying to see if a local-exec in terraform can delete but the issue is identifying only the unused connection, and only attempting to delete it if exists.  I hate using local-exec for anything but I don't know what else to do.  

### Proposal

I would like for terraform to allow me to set the interface name, for example 'ens192' and then if there is an existing ens192 interface, it can be updated instead of duplicated.

I actually expected it to just work.  I thought that terraform would be smart enough to know that it could reuse the existing interface configuration without any change to the configuration.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
