### ISSUE TITLE
Import block expansion with for_each not working

### ISSUE THREAD

**Issue by AnandSagar06** [hashicorp/terraform#34249]
### Terraform Version

```shell
1.6.3
```

### Terraform Configuration Files

# this code is inside import.tf file
```
import {
  for_each = {
    "bucket1" = "bucket1"
    "bucket2" = "bucket2"
  }
  to = aws_s3_bucket.this[each.key]
  id = each.value
}
```

### Debug Output

╷
│ Error: Unsupported argument
│ 
│   on import-for-each.tf line 8, in import:
│    8:   for_each = {
│ 
│ An argument named "for_each" is not expected here.
╵

### Expected Behavior

I expected both the existing s3 buckets "bucket1" and "bucket2" to be imported at once into our TF workspace.

### Actual Behavior

It resulted in an error saying "An argument named "for_each" is not expected here". 
But I see this feature to support for_each inside an import block is already merged in 
[https://github.com/hashicorp/terraform/pull/33932](url)

### Steps to Reproduce

1. terraform init
2. terraform validate

### Additional Context

We have around 150 s3 buckets that we need to import into workspace. We are trying to use for_each inside an import block to  import all the buckets at once and save a lot of manual work.
Really appreciate your help here

### References

https://github.com/hashicorp/terraform/pull/33932

**Comment by alisdair** [comment]
Hi @AnandSagar06, thanks for the issue.

`for_each` support for `import` blocks is a feature slated for the upcoming 1.7.0 release, and it is not available in the 1.6 series. As a result I'm going to close this issue.

You may want to consider trying out the alpha releases to evaluate the functionality of the new feature. The most recent alpha release is [v1.7.0-alpha20231108](https://github.com/hashicorp/terraform/releases/tag/v1.7.0-alpha20231108).
