### ISSUE TITLE
Host key not getting generated for Function app.

### ISSUE THREAD

**Issue by lijink14** [hashicorp/terraform#34259]
### Terraform Version

```shell
Terraform v1.5.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v3.80.0

Your version of Terraform is out of date! The latest version
is 1.6.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

https://github.com/lijink14/terraform_functionapp

### Debug Output

N/A

### Expected Behavior

The function app should be created with appropriate host keys and should be able to deploy functions to it.

### Actual Behavior

Function app is created but the host is not loading. The function app is not available for deploying functions to it resulting is host runtime not available. 

### Steps to Reproduce

terraform init.
terraform deploy

### Additional Context

Have been working with Microsoft with this issue and got redirected towards terraform as the resource is deployed via tf template.

**Comment by kmoe** [comment]
Thanks for the issue report. It's not clear from this why the resource is not behaving as expected. There could be an issue with the Terraform AzureRM provider, or there could be a config change that would fix the issue.

I recommend you ask on the community forum for the Azure provider (https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) and file an issue with the provider if you believe this is a bug (https://github.com/hashicorp/terraform-provider-azurerm/issues).

In your issue report please include the output from Terraform. I'm assuming Terraform is not printing an error message that indicates Terraform Core could be at fault. If this is in fact the case, please reopen this issue.
