### ISSUE TITLE
Add all API calls into the log files

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [hashicorp/terraform#34267]
### Terraform Version

```shell
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/aws v5.17.0

Your version of Terraform is out of date! The latest version
is 1.6.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Use Cases

I'm building a script to generate least privilege policies for AWS. The script uses the logs from Terraform and then generates the policy from all actions taken. Unfortunately, not all API calls are inside the log, which then is missing in my policy.
I've tried different tools, but none were able to get me a good result, this is why I'm creating my own. The current state gives me at least a lot least cycles of trial and error until I've got my deployment policy correct. Of course, it would be a lot nicer if I could get all actions done by terraform via command, but having them inside the log file would be a great start.

### Attempted Solutions

I didn't try to come up with a solution yet, but this is how I get the log file currently:

`TF_LOG=trace terraform apply --auto-approve &> terraform.log`

EDIT: 
E.g. What is missing is the `ObjectLockConfiguration` on S3 from the log file

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by EduardSchwarzkopf** [comment]
Thanks for the hint! Will check out both resources <3
