### ISSUE TITLE
AWS SSO broken in 1.6.4

### ISSUE THREAD

**Issue by jadeallenx** [hashicorp/terraform#34277]
### Terraform Version

```shell
Terraform v1.6.4
on linux_amd64
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

```AWS_PROFILE=dev aws sts get-caller-identity
{
    "UserId": "AROA54KEOYPRXXXX:YYY@ZZZ.com",
    "Account": "112233",
    "Arn": "arn:aws:sts::112233:assumed-role/AWSReservedSSO_AWSAdministratorAccess_foobar/YYY@ZZZ.com"
}```

Valid SSO session

then 

```
2023-11-20T15:45:32.105-0600 [INFO]  Terraform version: 1.6.4
2023-11-20T15:45:32.106-0600 [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2023-11-20T15:45:32.106-0600 [DEBUG] using github.com/hashicorp/hcl/v2 v2.19.1
2023-11-20T15:45:32.106-0600 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2023-11-20T15:45:32.106-0600 [DEBUG] using github.com/zclconf/go-cty v1.14.1
2023-11-20T15:45:32.106-0600 [INFO]  Go runtime version: go1.21.3
2023-11-20T15:45:32.106-0600 [INFO]  CLI args: []string{"terraform", "init"}
... snip ...

Initializing the backend...
2023-11-20T15:45:32.108-0600 [DEBUG] New state was assigned lineage "84f2e7bc-6514-fe37-fa77-131a5fb9b3ea"
2023-11-20T15:45:32.323-0600 [DEBUG] checking for provisioner in "."
2023-11-20T15:45:32.325-0600 [DEBUG] checking for provisioner in "/usr/bin"
2023-11-20T15:45:32.326-0600 [DEBUG] backend-s3.aws-base: Resolving credentials provider: tf_backend.operation=Configure tf_backend.req_id=df83bd5f-ad02-1434-daff-2ff60273c01d tf_backend.s3.bucket=tf-state-dev-us-west-2 tf_backend.s3.path=ZZZ-tf/stack/vpc/terraform.tfstate

...snip...

2023-11-20T15:45:32.326-0600 [DEBUG] backend-s3.aws-base: Retrieving credentials: tf_backend.operation=Configure tf_backend.req_id=df83bd5f-ad02-1434-daff-2ff60273c01d tf_backend.s3.bucket=tf-state-dev-us-west-2 tf_backend.s3.path=ZZZ-tf/stack/vpc/terraform.tfstate
╷
│ Error: No valid credential sources found
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: failed to refresh cached credentials, the SSO session has expired or
│ is invalid: failed to read cached SSO token file, open
│ /home/YYY/.aws/sso/cache/0xdeadbeefhash.json: no
│ such file or directory
│ 
╵

ERRO[0002] terraform invocation failed in /home/YYY/vpc/.terragrunt-cache/5paRZdxXD4QNH-1k6mjhK42O2cI/B3aa0TQF8DQ9QFMKA1HemARc0x0/modules/vpc_v2  prefix=[directory] 
ERRO[0002] 1 error occurred:
	* [/home/YYY/vpc/.terragrunt-cache/5paRZdxXD4QNH-1k6mjhK42O2cI/B3aa0TQF8DQ9QFMKA1HemARc0x0/modules/vpc_v2] exit status 1
```



### Expected Behavior

using terraform 1.6.3

```
2023-11-20T15:49:30.885-0600 [DEBUG] backend-s3.aws-base: HTTP Request Sent: aws.operation=GetRoleCredentials aws.region=us-west-2 aws.sdk=aws-sdk-go-v2 aws.service=SSO tf_backend.operation=Configure tf_backend.req_id=1ddf2c2c-5900-f4f1-5a69-0e8387964599 tf_backend.s3.bucket=tf-state-dev-us-west-2 tf_backend.s3.path=tf/stack/vpc/terraform.tfstate net.peer.name=portal.sso.us-west-2.amazonaws.com http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.6.3 (+https://www.terraform.io) aws-sdk-go-v2/1.21.0 os/linux lang/go#1.21.3 md/GOOS#linux md/GOARCH#amd64 api/sso#1.13.6" http.request.header.amz_sdk_request="attempt=1; max=3" http.request.header.x_amz_sso_bearer_token="a_token" http.request.header.amz_sdk_invocation_id=222eb4f9-bfa7-4c96-bb67-4d500425a1d2 http.request.body="" http.method=GET http.url="https://portal.sso.us-west-2.amazonaws.com/federation/credentials?account_id=112233&role_name=AWSAdministratorAccess"
2023-11-20T15:49:32.438-0600 [DEBUG] backend-s3.aws-base: HTTP Response Received: aws.operation=GetRoleCredentials aws.region=us-west-2 aws.sdk=aws-sdk-go-v2 aws.service=SSO tf_backend.operation=Configure tf_backend.req_id=1ddf2c2c-5900-f4f1-5a69-0e8387964599 tf_backend.s3.bucket=tf-state-dev-us-west-2 tf_backend.s3.path=tf/stack/vpc/terraform.tfstate http.response.header.content_type=application/json http.response.header.server="AWS SSO" http.response.header.date="Mon, 20 Nov 2023 21:49:32 GMT"
```
init works as expected using SSO credentials

### Actual Behavior

SSO error message in 1.6.4, init does not complete

### Steps to Reproduce

1. Login with AWS SSO credentials
2. Use terraform 1.6.4 and `init` command

### Additional Context

_No response_

### References

_No response_

**Comment by rvodden** [comment]
I am seeing exactly the same issue with 1.6.4 - all works fine with 1.6.3

**Comment by rvodden** [comment]
I have a dev environment set up and can minimally replicate the issue on 1.6.4:

```
vscode@c8de4d29640d:/workspaces/terraform/test_case$ aws sts get-caller-identity 
-----------------------------------------------------------------------------------------------------------------------------
|                                                     GetCallerIdentity                                                     |
+---------+-----------------------------------------------------------------------------------------------------------------+
|  Account|  323745644240                                                                                                   |
|  Arn    |  arn:aws:sts::323745644240:assumed-role/AWSReservedSSO_Landing_de16e1f91390ec6a/richard.vodden@brentso.org.uk   |
|  UserId |  AROAUWYF6P3IIVYIKC6WY:richard.vodden@brentso.org.uk                                                            |
+---------+-----------------------------------------------------------------------------------------------------------------+
```

however from terraform:
```
vscode@c8de4d29640d:/workspaces/terraform/test_case$ ../terraform init

Initializing the backend...
╷
│ Error: No valid credential sources found
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: failed to refresh cached credentials, the SSO session has expired or is invalid: failed to read cached SSO token file, open
│ /home/vscode/.aws/sso/cache/847b79af25e467f1249ad65c90d4e72f361336da.json: no such file or directory
│ 
```

I'm going to have a go at upgrading the AWS SDK now and see if that resolves the issue

**Comment by rvodden** [comment]
Yeah - updating to the latest AWS SDK resolves the problem:

```
vscode@c8de4d29640d:/workspaces/terraform$ git diff go.mod   
diff --git a/go.mod b/go.mod
index 2c4a57f2d9..0929a1bcfb 100644
--- a/go.mod
+++ b/go.mod
@@ -17,12 +17,12 @@ require (
        github.com/apparentlymart/go-userdirs v0.0.0-20200915174352-b0c018a67c13
        github.com/apparentlymart/go-versions v1.0.1
        github.com/armon/circbuf v0.0.0-20190214190532-5111143e8da2
-       github.com/aws/aws-sdk-go-v2 v1.22.2
-       github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.14.3
-       github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.11.83
-       github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.1
-       github.com/aws/aws-sdk-go-v2/service/s3 v1.42.1
-       github.com/aws/smithy-go v1.16.0
+       github.com/aws/aws-sdk-go-v2 v1.23.0
+       github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.14.4
+       github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.13.9
+       github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.2
+       github.com/aws/aws-sdk-go-v2/service/s3 v1.42.2
+       github.com/aws/smithy-go v1.17.0
        github.com/bgentry/speakeasy v0.1.0
        github.com/bmatcuk/doublestar v1.1.5
        github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
@@ -142,23 +142,23 @@ require (
        github.com/armon/go-radix v1.0.0 // indirect
        github.com/asaskevich/govalidator v0.0.0-20200907205600-7a23bdc65eef // indirect
        github.com/aws/aws-sdk-go v1.44.122 // indirect
-       github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.5.0 // indirect
-       github.com/aws/aws-sdk-go-v2/config v1.25.0 // indirect
-       github.com/aws/aws-sdk-go-v2/credentials v1.16.0 // indirect
-       github.com/aws/aws-sdk-go-v2/internal/configsources v1.2.2 // indirect
-       github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.5.2 // indirect
-       github.com/aws/aws-sdk-go-v2/internal/ini v1.7.0 // indirect
-       github.com/aws/aws-sdk-go-v2/internal/v4a v1.2.2 // indirect
+       github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.5.1 // indirect
+       github.com/aws/aws-sdk-go-v2/config v1.25.2 // indirect
+       github.com/aws/aws-sdk-go-v2/credentials v1.16.1 // indirect
+       github.com/aws/aws-sdk-go-v2/internal/configsources v1.2.3 // indirect
+       github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.5.3 // indirect
+       github.com/aws/aws-sdk-go-v2/internal/ini v1.7.1 // indirect
+       github.com/aws/aws-sdk-go-v2/internal/v4a v1.2.3 // indirect
        github.com/aws/aws-sdk-go-v2/service/iam v1.27.1 // indirect
-       github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.10.0 // indirect
-       github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.2.2 // indirect
-       github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.8.2 // indirect
-       github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.10.2 // indirect
-       github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.16.2 // indirect
+       github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.10.1 // indirect
+       github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.2.3 // indirect
+       github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.8.3 // indirect
+       github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.10.3 // indirect
+       github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.16.3 // indirect
        github.com/aws/aws-sdk-go-v2/service/sqs v1.28.0 // indirect
-       github.com/aws/aws-sdk-go-v2/service/sso v1.17.1 // indirect
-       github.com/aws/aws-sdk-go-v2/service/ssooidc v1.19.1 // indirect
-       github.com/aws/aws-sdk-go-v2/service/sts v1.25.1 // indirect
+       github.com/aws/aws-sdk-go-v2/service/sso v1.17.2 // indirect
+       github.com/aws/aws-sdk-go-v2/service/ssooidc v1.19.2 // indirect
+       github.com/aws/aws-sdk-go-v2/service/sts v1.25.2 // indirect
        github.com/baiyubin/aliyun-sts-go-sdk v0.0.0-20180326062324-cfa1a18b161f // indirect
        github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d // indirect
        github.com/bmatcuk/doublestar/v4 v4.6.0 // indirect
```

```
vscode@c8de4d29640d:/workspaces/terraform/test_case$ ../terraform init

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v5.26.0...
- Installed hashicorp/aws v5.26.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by rvodden** [comment]
I've marked that PR as draft as the unit tests are failing, owing to something to do with  `aws-sdk-go-base` that I can't quite fathom. I'm going to have a dig around this afternoon

**Comment by rvodden** [comment]
The tests all pass locally when I used the trunk of aws-sdk-go-base, so as soon as that gets another release, I'll update my PR to that new version and all should pass :-)

**Comment by rvodden** [comment]
There we go - my PR is passing all the unit tests now, and working with SSO Profiles.

**Comment by jadeallenx** [comment]
> There we go - my PR is passing all the unit tests now, and working with SSO Profiles.

Amazing, thanks! Glad you figured it out 💖

**Comment by rvodden** [comment]
Confirmed fixed!

![image](https://github.com/hashicorp/terraform/assets/3389129/a30ed262-efef-4af0-9395-d3b6bb3b8d7e)
