### ISSUE TITLE
terraform validate should validate invalid local names

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/terraform#34272]
### Terraform Version

```shell
Terraform v1.5.0
```

Given:

```terraform
locals {
  l = {
    "foo,": "bar"
  }
}
```

then 

```bash
$ terraform validate
Success! The configuration is valid.
```

however in terraform console:

```bash
$ terraform console
> local.l.foo,
╷
│ Error: Extra characters after expression
│
│   on <console-input> line 1:
│   (source code not available)
│
│ An expression was successfully parsed, but extra characters were found after it.
```

### Proposal

I think terraform validate should also check the validity of locals

**Comment by apparentlymart** [comment]
Hi @paololazzari,

From what you've shared, it seems like Terraform behaved correctly here. The configuration you shared is itself valid, but the expression you entered in `terraform console` is not valid. `terraform console` detected and reported the error.

If you want to refer to an object attribute or map key that isn't a valid identifier, the correct syntax for that would be:

```hcl
local.l["foo,"]
```
