### ISSUE TITLE
GCP IAM diffs obscured with hidden elements

### ISSUE THREAD

**Issue by acaire** [hashicorp/terraform#34278]
### Terraform Version

```shell
Terraform v1.6.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.6.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "5.6.0"
    }
  }
}

variable "bucket" {
  type = string
}

variable "project" {
  type = string
}

variable "initial" {
  type = bool
  description = "Run terraform apply once with this set to true to set up the test, then run a plan with false to demonstrate the diff output"
}

variable "user" {
  type = string
}

resource "google_storage_bucket" "bucket" {
  name          = var.bucket
  location      = "US"
  force_destroy = true
  project       = var.project
}

resource "google_storage_bucket_iam_policy" "policy" {
  bucket = google_storage_bucket.bucket.name

  policy_data = data.google_iam_policy.bucket.policy_data
}

data "google_iam_policy" "bucket" {
  binding {
    role = "roles/storage.admin"

    members = [
      "user:${var.user}",
      "domain:example.com",
    ]
  }

  binding {
    role = "roles/storage.objectCreator"

    members = compact([
      "user:${var.user}",
      "domain:example.com",
    ])
  }

  binding {
    role = "roles/storage.objectViewer"

    members = compact([
      "user:${var.user}",
      var.initial ? "domain:example.com" : null,
    ])
  }
}
```

### Debug Output

https://gist.github.com/acaire/2ec41e396d80d7a774be8ba2b458e5c3

### Expected Behavior

In the plan, I would've expected to be shown enough context to see the role for which a member was being removed from - It's easy to grok with this little number of bindings, but not when there are hundreds.  This doesn't just affect buckets, but project policies and other permissions etc.

### Actual Behavior

The role the member was being removed from was hidden from context

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -auto-approve -var project=your-project -var user=your-user@example.com -var bucket=your-bucket -var initial=true`
3. `terraform plan -var project=your-project -var user=your-user@example.com -var bucket=your-bucket -var initial=false`

### Additional Context

Perhaps to fix this, we would add `role` to `importantAttributes`?
https://github.com/hashicorp/terraform/blob/afc83356ca68dab333400a8a096547966dff6d99/internal/command/jsonformat/computed/renderers/block.go#L19-L23

**Comment by jbardin** [comment]
Hi @acaire,

Thanks for the additional example! There are lots of different resources with varying attributes which users may or may not want to see in the diff. While we may make some more exceptions as a workaround in the short term, I'm going to combine this with the overall feature request in #30753 for more visibility.

Thanks!
