### ISSUE TITLE
[GCP]  Terraform support for `pubsub`  latest feature  `Write to cloud storage` subscription

### ISSUE THREAD

**Issue by gomrinal** [hashicorp/terraform#34282]
### Terraform Version

```shell
N/A
```

### Use Cases

Please add support for pubsub latest feature i.e write to cloud storage from pubsub. This new feature in pubsub helps user to directly write to GCS bucket so no dataflow pipeline is required in between the pubsub <-> cloud storage if no ETL is required in the middle

### Attempted Solutions

This feature is not available in the terraform as of now!

![IMG_4266](https://github.com/hashicorp/terraform/assets/29385581/2eb7e323-1908-4edf-aaf6-c4fb1145518f)

### Proposal

Please add support for latest releases and features of google cloud pubsub!

### References

n/a

**Comment by gomrinal** [comment]
Reference:
https://cloud.google.com/pubsub/docs/create-cloudstorage-subscription

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
