### ISSUE TITLE
[GCP] Terraform support for  `pubsub` latest feature `Write to bigquery` subscription

### ISSUE THREAD

**Issue by gomrinal** [hashicorp/terraform#34281]
### Terraform Version

```shell
N/A

This feature is not present in the `terraform` as of now!
```

### Use Cases

![IMG_4266](https://github.com/hashicorp/terraform/assets/29385581/73b2f708-ec1c-429b-ad44-89e13aafbc7d)

Pubsub supports direct ingestion to Bigquery if one doesn't need any ETL in the message which is being published to the pubsub.  Previously, one had to run their dataflow job to read from pubsub topic and ingest it to BQ.

### Attempted Solutions

Terraform doesn't have this feature as of now for the pubsub

### Proposal

Please add support for latest features pubsub has like direct ingestion to BigQuery table

### References

N/A

**Comment by gomrinal** [comment]
Reference:
https://cloud.google.com/pubsub/docs/create-bigquery-subscription

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
