### ISSUE TITLE
Official page doesn't contain all available options for google_compute_instance_template 

### ISSUE THREAD

**Issue by glerchundi** [hashicorp/terraform#3430]
Although gce allows you to set boot disk size, terraform doesn't.

```
Errors:
  * google_compute_instance_template.my-test-tmpl: disk.0: invalid or unknown key: size
```

**EDIT:**

https://github.com/hashicorp/terraform/blob/v0.6.3/builtin/providers/google/resource_compute_instance_template.go#L82

It seems to be already done, but terraform doc. is not up to date in the official page so I'll rename this issue to reflect that.

**Comment by stack72** [comment]
@glerchundi yes there is another issue that someone raised about the docs site up to date. When the next release of terraform (0.6.4) hits, the documentation should be updated at that point

**Comment by glerchundi** [comment]
Ok, closing this then.
