### ISSUE TITLE
Terraform plan internals

### ISSUE THREAD

**Issue by papiveron** [hashicorp/terraform#3432]
Hi,

Is there a subtility with how terraform manages aws security groups?

I noticed that sometimes just after a **terraform apply** completed, when I run **terraform plan** it shows  me resources to be changed in my security group module, you can see in the screeshot attached here.

My questions are :
 - Why does this always appear?
 - How can I locate the ressources to change when running **terraform plan**
 - How to solve the issue (I mean get my infra up to date with nothing to test when the **apply** is completed)
 - My terraform version is **v0.6.3**. Is there a process to follow terraform releases and update the software?

**module.sg** in the screenshot is my security group module.
![module_sg](https://cloud.githubusercontent.com/assets/5762296/10342336/da9b392a-6d18-11e5-86c2-29b4f5a347a6.png)

Thanks.

**Comment by apparentlymart** [comment]
There have been some quirks with security groups in the past; you can get more details about what exactly Terraform thinks needs to be updated if you run the plan command like this:

* `terraform plan -module-depth=2`

That will make terraform show you the diff of the individual resources inside your ``module.sg`` rather than just telling you that the resource as a whole has changed. If you can share the result of that then it might be easier to see what the bug is here.

**Comment by papiveron** [comment]
Hi @apparentlymart,

This is the output :

```
/home/eugene/projects/morea/template.terraform.vpc.support/main> terraform plan -target=module.sg -module-depth=2
Refreshing Terraform state prior to plan...

module.vpc.aws_vpc.support_vpc: Refreshing state... (ID: vpc-79b0c41c)
module.sg.aws_security_group.sg-bastion: Refreshing state... (ID: sg-ed6ab589)
module.sg.aws_security_group.sg-ghost: Refreshing state... (ID: sg-e86ab58c)
module.sg.aws_security_group.sg-logs: Refreshing state... (ID: sg-ef6ab58b)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

~ module.sg.aws_security_group.sg-bastion
    ingress.#:                            "2" => "3"
    ingress.278824937.cidr_blocks.#:      "2" => "2"
    ingress.278824937.cidr_blocks.0:      "213.2.55.10/32" => "213.2.55.10/32"
    ingress.278824937.cidr_blocks.1:      "193.3.134.16/32" => "193.3.134.16/32"
    ingress.278824937.from_port:          "22" => "22"
    ingress.278824937.protocol:           "tcp" => "tcp"
    ingress.278824937.security_groups.#:  "0" => "0"
    ingress.278824937.self:               "0" => "0"
    ingress.278824937.to_port:            "22" => "22"
    ingress.3252044932.cidr_blocks.#:     "1" => "0"
    ingress.3252044932.cidr_blocks.0:     "31.3.142.1/32" => ""
    ingress.3252044932.from_port:         "10050" => "0"
    ingress.3252044932.protocol:          "tcp" => ""
    ingress.3252044932.security_groups.#: "0" => "0"
    ingress.3252044932.self:              "1" => "0"
    ingress.3252044932.to_port:           "10051" => "0"
    ingress.4051984680.cidr_blocks.#:     "0" => "1"
    ingress.4051984680.cidr_blocks.0:     "" => "213.2.55.10/32"
    ingress.4051984680.from_port:         "" => "10050"
    ingress.4051984680.protocol:          "" => "tcp"
    ingress.4051984680.security_groups.#: "0" => "0"
    ingress.4051984680.self:              "" => "0"
    ingress.4051984680.to_port:           "" => "10051"
    ingress.500361729.cidr_blocks.#:      "0" => "0"
    ingress.500361729.from_port:          "" => "10050"
    ingress.500361729.protocol:           "" => "tcp"
    ingress.500361729.security_groups.#:  "0" => "0"
    ingress.500361729.self:               "" => "1"
    ingress.500361729.to_port:            "" => "10051"


Plan: 0 to add, 1 to change, 0 to destroy.
```

For me it seems like terraform has difficulties to deal with public ip in security groups.
Can you advise by looking the output above please?

I'll be looking by my side.

Thanks.

Regards.

**Comment by scalp42** [comment]
This is related to https://github.com/hashicorp/terraform/issues/2843 I believe

**Comment by papiveron** [comment]
Yes scalp42.

I'll then keep watching the issue you first create, if it changes.

Regards.

**Comment by phinze** [comment]
Hi @papiveron - sorry for the trouble here. Since you agree that @scalp42's issue looks to be the same, I'll close this so we can consolidate the discussion.

If you believe this is a separate issue and should be kept open, you can follow up here - we'd need to look at your Terraform security group config in that case.
