### ISSUE TITLE
0.6.4 Release?

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform#3435]
@phinze,

It seems like TF was in a really good cadence of releasing a new version every month or so. That seems to have slipped (due to reasons of course) but this has meant that the documentation on the TF site is quite a bit out of date.

Can we plan a release of 0.6.4? If there is anything that needs done (docs etc.) before release then just say the word!

Paul

**Comment by phinze** [comment]
Hi @stack72 - it's true that we're past due for a release. But 0.6.4 is definitely on our minds!

We're taking the rest of this week to gain some ground on the backlog, and the plan is to cut a release early next week. Sound like a reasonable plan to you?

**Comment by stack72** [comment]
sounds awesome to me :) Thanks for the response.

**Comment by CpuID** [comment]
@phinze can't wait, being that https://github.com/aws/aws-sdk-go/issues/397 was fixed recently upstream a new build using the latest SDK version will allow Amazon ECS to be more usable :)
