### ISSUE TITLE
Ambiguous reference in Purpose of Terraform State

### ISSUE THREAD

**Issue by kryptoblack** [hashicorp/terraform#34389]
### Terraform Version

```shell
Console Version: Terraform v1.6.4 on linux_amd64

Documentation Version: 1.6.x
```

### Affected Pages

[Purpose of Terraform State](https://developer.hashicorp.com/terraform/language/state/purpose#metadata)

### What is the docs issue?

> Alongside the mappings between resources and remote objects, Terraform must also track metadata such as resource dependencies.
>
> Terraform typically uses the configuration to determine dependency order. However, when you delete a resource from a Terraform configuration, Terraform must know how to delete that resource from the remote system. Terraform can see that a mapping exists in the state file for a resource not in your configuration and plan to destroy. However, since the configuration no longer exists, the order cannot be determined from the configuration alone.
>
> To ensure correct operation, Terraform retains a copy of the most recent set of dependencies within the state. Now Terraform can still determine the correct order for destruction from the state when you delete one or more items from the configuration.
>
> One way to avoid `this` would be for Terraform to know a required ordering between resource types. For example, Terraform could know that servers must be deleted before the subnets they are a part of. The complexity for this approach quickly explodes, however: in addition to Terraform having to understand the ordering semantics of every resource for every provider, Terraform must also understand the ordering across providers.
> ...

The above two paragraphs i.e. paragraph two and paragraph three talks about the issue faced by Terraform and Terraform's solution to that respectively. What the last paragraph talks about is an alternate solution that couldn't be used by Terraform.

The highlighted word `this` in the last paragraph is ambiguous as it does not clearly specify if it is talking about the issue (paragraph two) or Terraform's solution (paragraph three).

### Proposal

There are two scenarios:

1. `this` refers to the issue/problem (paragraph two); change `this` to `the above issue/problem`
2. `this` refers to Terraform's solution (paragraph three); change `one way to avoid this` to `Another way`

The change would look something like:

1. One way to **avoid the above problem** would be for Terraform to know a required ordering between resource types. For example, Terraform could know that servers must be deleted before the subnets they are a part of. The complexity for this approach quickly explodes, however: in addition to Terraform having to understand the ordering semantics of every resource for every provider, Terraform must also understand the ordering across providers.

2. **Another way** would be for Terraform to know a required ordering between resource types. For example, Terraform could know that servers must be deleted before the subnets they are a part of. The complexity for this approach quickly explodes, however: in addition to Terraform having to understand the ordering semantics of every resource for every provider, Terraform must also understand the ordering across providers.

**Comment by Yashrajput7232** [comment]
i want to solve this issue.

**Comment by crw** [comment]
Hi @Yashrajput7232, anyone can make a documentation change. Can you please read https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md and if you feel you have the ability to improve the documentation, feel free to open a pull request. Thanks!
