### ISSUE TITLE
API GW Deployment Issue via terraform

### ISSUE THREAD

**Issue by Alekya999** [hashicorp/terraform#34398]
### Terraform Version

```shell
terraform --version
Terraform v1.6.5
on darwin_amd64
```

### Terraform Configuration Files

[tf_files.zip](https://github.com/hashicorp/terraform/files/13647928/tf_files.zip)

### Debug Output

Data resource (data.template_file.api_swagger) takes user yaml but deployment res (aws_api_gateway_rest_api.api-gateway) takes another yaml (siteservice.yaml)

### Expected Behavior

when deploying a new method(PATCH) to the existing end point (/api/v1/users/{userName}) via terraform It’s not getting deployed in dev API GW . The same setup is working for another environment API GW when deployed via terraform.
**Data resource (data.template_file.api_swagger) and deployment res (aws_api_gateway_rest_api.api-gateway) are expected to pick up same yaml file.**

### Actual Behavior

Data resource (data.template_file.api_swagger) takes user yaml but deployment res (aws_api_gateway_rest_api.api-gateway) takes another yaml (siteservice.yaml)

**What all we have tried**
1. upgraded the terraform to latest version
2. put_rest_api_mode to "merge" is commented from terraform.
3. tfstatefile is not picking up the yaml file which is being passed.
type of API Gateway: REST API

### Steps to Reproduce

terraform init -input=false -backend-config="dev/dev.conf" -reconfigure
terraform plan -input=false -var-file="dev/dev.tfvars" -lock=false -out tfplan
terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
