### ISSUE TITLE
Allow to use predictible keys derivated of unknown values in a for_each

### ISSUE THREAD

**Issue by i2dcarrasco** [hashicorp/terraform#34417]
### Terraform Version

```shell
Terraform v1.6.4
on linux_amd64
+ provider registry.terraform.io/carlpett/sops v0.7.2
+ provider registry.terraform.io/hashicorp/google v5.5.0
+ provider registry.terraform.io/hashicorp/google-beta v5.5.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Use Cases

When you have to dynamically apply a resource with for_each depending of another resource which doesn't exists, for example to create a service account and apply a set of permissions to it located in a "local", the terraform says that the key cannot be detemined and doesn't work. I understand that this is part of the check to avoid conflicts for example, but using some "tricks" can be avoided and then the key can be determined even when the resource doesn't exists yet. The problem is that terraform doesn't try to determine the key when the value is unknown, and then such tricks doesn't work.

### Attempted Solutions

For example, if I have a new service account and I have to apply two roles to it based in a local variable, I have to dynamically generate the map for the for_each:

```
resource "google_service_account" "service_account" {
  account_id = "nice-service-account"
  display_name = "Nice Service Account"
}

locals {
  permissions = [
    {
      service_account = google_service_account.service_account.email
      roles = [
        "role1",
        "role2"
      ]
    }
  ]
}

resource "google_project_iam_member" "accounts_roles" {
  for_each = { for a in chunklist(flatten([for i in local.permissions : setproduct([i["service_account"], i["roles"])]), 2) : "${a[0]}_${a[1]}" => {
    account = a[0],
    role    = a[1]
  } }
  role     = each.value.role
  member   = each.value.account
  project  = local.settings.project.id
}
```

In the above example the terraform will fail saying that the keys cannot be determined until apply. I understand this behaviour because terraform will try to determine conflicts in names and similar before to apply. Which is not able to do the terraform is to avoid it even then the keys can be determined but depends of data that is undetermined yet.

### Proposal

For example, if I convert the above example to this one:

```
resource "google_service_account" "service_account" {
  account_id = "nice-service-account"
  display_name = "Nice Service Account"
}

locals {
  permissions = [
    {
      service_account = google_service_account.service_account.email
      roles = [
        "role1",
        "role2"
      ]
    }
  ]
}

resource "google_project_iam_member" "accounts_roles" {
  for_each = {
    for idx, value in flatten([
        for i in local.permissions : [
            for acc, r in setproduct(i["service_account"], i["roles"]) : {
                account = acc,
                role    = r
            }
        ]
    ]) : idx => value
  }
  role     = each.value.role
  member   = each.value.account
  project  = local.settings.project.id
}
```

The values remains unknown, but the keys can be easily determined because are derivated from the number of entries and not their values. In this case the emails of the service account is unknown, but you know that there are two entries:

```
[
    {
        account = *unknown*
        role = "role1"
    },
    {
        account = *unknown*
        role = "role2"
    },
]
```
So you are able to determine that the idx values are 0 and 1 and thus the resources keys are not unknown anymore.

Will be nice to be able to apply resorces when they are unknown and the keys are predictable like in the above example, because applying it manually is not a problem because you use a target to create the first resource and problem solved, but in a CI/CD is harder to do it.

DISCLAIMER: I made this examples on the fly without testing it and maybe are not correct. This is because my case of use is slightly different, but is based in the same root problem.

In my case the service account is created outside a module, and inside the module I determine the resources to which apply a permission with a for loops. The resources and the service account can not exists, but the way to determine the keys is the same (1 account 2 resources = 1 x 2 = 2 = {0 = x, 1 = x}, 1 account 3 resources = 1 x 3 = 3 = {0 = x, 1 = x, 2 = x}...).

Sorry if I have not explained it clear enough, but english is not my main language and this adds and extra difficulty to me.

**Comment by jbardin** [comment]
Hi @i2dcarrasco,

Thanks for filing the issue. From what I understand of your description, Terraform already allows you to create a mapping with `for_each` with known keys and unknown values. Taking your example, I can successfully plan the both instances which have the keys `"0"` and `"'1"`.

Removing the need for specific cloud credentials, but retaining the exact same expression structure I get:
```
resource "terraform_data" "service_account" {
}

locals {
  permissions = [
    {
      service_account = [terraform_data.service_account.id]
      roles = [
        "role1",
        "role2"
      ]
    }
  ]
}

resource "terraform_data" "accounts_roles" {
  for_each = {
    for idx, value in flatten([
      for i in local.permissions : [
        for acc, r in setproduct(i["service_account"], i["roles"]) : {
          account = acc,
          role    = r
        }
      ]
    ]) : idx => value
  }
}
```

```
Terraform will perform the following actions:

  # terraform_data.accounts_roles["0"] will be created
  + resource "terraform_data" "accounts_roles" {
      + id = (known after apply)
    }

  # terraform_data.accounts_roles["1"] will be created
  + resource "terraform_data" "accounts_roles" {
      + id = (known after apply)
    }

  # terraform_data.service_account will be created
  + resource "terraform_data" "service_account" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

Chances are that you have a function call or expression which removes the ability to determine the keys, hence producing an error about unknown values. Having known keys is required because Terraform must be able to address which instances are associated with each planned change in order to apply those changes correctly.

If you are interested in Terraform being able to progressively apply plans such that it can work around unknown values, then you should follow issue #30937. If there is a specific function which should be able to better handle unknown values, then a new issue more targeted at that function's implementation should be filed.

If you have more questions,  it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by i2dcarrasco** [comment]
> Hi @i2dcarrasco,
> 
> Thanks for filing the issue. From what I understand of your description, Terraform already allows you to create a mapping with `for_each` with known keys and unknown values. Taking your example, I can successfully plan the both instances which have the keys `"0"` and `"1"`.
> 
> Removing the need for specific cloud credentials, but retaining the exact same expression structure I get:
> 
> ```
> resource "terraform_data" "service_account" {
> }
> 
> locals {
>   permissions = [
>     {
>       service_account = [terraform_data.service_account.id]
>       roles = [
>         "role1",
>         "role2"
>       ]
>     }
>   ]
> }
> 
> resource "terraform_data" "accounts_roles" {
>   for_each = {
>     for idx, value in flatten([
>       for i in local.permissions : [
>         for acc, r in setproduct(i["service_account"], i["roles"]) : {
>           account = acc,
>           role    = r
>         }
>       ]
>     ]) : idx => value
>   }
> }
> ```
> 
> ```
> Terraform will perform the following actions:
> 
>   # terraform_data.accounts_roles["0"] will be created
>   + resource "terraform_data" "accounts_roles" {
>       + id = (known after apply)
>     }
> 
>   # terraform_data.accounts_roles["1"] will be created
>   + resource "terraform_data" "accounts_roles" {
>       + id = (known after apply)
>     }
> 
>   # terraform_data.service_account will be created
>   + resource "terraform_data" "service_account" {
>       + id = (known after apply)
>     }
> 
> Plan: 3 to add, 0 to change, 0 to destroy.
> ```
> 
> Chances are that you have a function call or expression which removes the ability to determine the keys, hence producing an error about unknown values. Having known keys is required because Terraform must be able to address which instances are associated with each planned change in order to apply those changes correctly.
> 
> If you are interested in Terraform being able to progressively apply plans such that it can work around unknown values, then you should follow issue #30937. If there is a specific function which should be able to better handle unknown values, then a new issue more targeted at that function's implementation should be filed.
> 
> If you have more questions, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.
> 
> Thanks!

Hello,

Maybe the example is working because I have tried to simplify it considering how complex is the real one, but I am sure that in other cases is not working because is not the first time I get this problem. On my real example I use functions, and maybe that is the problem. Just adding a count or something similar makes it fail because the data is "unknown", and a count can be easily determined without knowing the data.

Best regards.
