### ISSUE TITLE
Terraform Test: Compare Objects / Maps

### ISSUE THREAD

**Issue by deitChi** [hashicorp/terraform#34425]
### Terraform Version

```shell
1.6.6
```

### Terraform Configuration Files

```terraform
run "Apply_Tests" {

  command = apply

  assert {
    condition = module.nsg.rules_intra["intra-subnet-communication-in"] == {
      name     = "intra-subnet-communication-in"
      priority = 100
    }
    error_message = "The Rules Intra In for the nsg is not valid."
  }
```

### Debug Output
```
network_security_group.tftest.hcl... in progress
  run "Apply_Tests"... fail
╷
│ Error: Test assertion failed
│ 
│   on network_security_group.tftest.hcl line 29, in run "Apply_Tests":
│   29:     condition = module.nsg.rules_intra["intra-subnet-communication-in"] == {
│   30:       name     = "intra-subnet-communication-in"
│   31:       priority = 100
│   32:     }
│     ├────────────────
│     │ module.nsg.rules_intra["intra-subnet-communication-in"] is object with 20 attributes
│ 
│ The Rules Intra In for the nsg is not valid.
```

### Expected Behavior

Difference in `module.nsg.rules_intra["intra-subnet-communication-in"]` detected... provide a diff of resource object, to compared object.

### Actual Behavior

Generic ` module.nsg.rules_intra["intra-subnet-communication-in"] is object with 20 attributes`

### Steps to Reproduce

terraform test

### Additional Context

It should be possible to compare all the datatypes that Terraform supports. i.e. Maps, lists, strings, bool etc.

**Comment by jbardin** [comment]
Hi @deitChi,

in Terraform you can compare any types, but they must always be the same type for them to compare as equal. According to the error, the `module.nsg.rules_intra["intra-subnet-communication-in"]` value is an object with 20 attributes, and you are comparing that to an object with 2 attributes, which could never be equal. You would either need to construct an object of the same type, or in this case since you only want to compare a small subset of attributes, you could compare the attributes individually.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by jbardin** [comment]
Sorry, I'm not sure what the proposal is here. The tests are still written for and executed by Terraform, using the same configuration language, so it's not possible to use a different type system for only the tests.

One possibility might be to use some newly defined functions for comparisons using different logic. Given the [breadth of possible functions](https://github.com/hashicorp/terraform/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement+label%3Afunctions) it's not likely that is something which would be added to core, however work is being done on new way to include externally defined functions which could be useful here.

**Comment by deitChi** [comment]
I've done some more testing, namely got the output for the 20 attributes as described above - expecting one of them not to match (id)

```
network_security_group.tftest.hcl... in progress
  run "Apply_Tests"... fail
╷
│ Error: Test assertion failed
│ 
│   on network_security_group.tftest.hcl line 29, in run "Apply_Tests":
│   29:     condition = module.nsg.rules_intra["intra-subnet-communication-in"] == {
│   30:       access                                     = "Allow"
│   31:       description                                = null
│   32:       destination_address_prefix                 = "10.232.9.96/30"
│   33:       destination_address_prefixes               = null
│   34:       destination_application_security_group_ids = null
│   35:       destination_port_range                     = "*"
│   36:       destination_port_ranges                    = null
│   37:       direction                                  = "Inbound"
│   38:       id                                         = "test"
│   39:       name                                       = "intra-subnet-communication-in"
│   40:       network_security_group_name                = "azsu-nsg-netsecsbnsg-customer-test-aks-001"
│   41:       priority                                   = 2000
│   42:       protocol                                   = "*"
│   43:       resource_group_name                        = "azsu-rg-netsecsbnsg-nsg-001"
│   44:       source_address_prefix                      = null
│   45:       source_address_prefixes                    = ["10.232.9.96/30"]
│   46:       source_application_security_group_ids      = null
│   47:       source_port_range                          = "*"
│   48:       source_port_ranges                         = null
│   49:       timeouts                                   = null
│   50:     }
│     ├────────────────
│     │ module.nsg.rules_intra["intra-subnet-communication-in"] is object with 20 attributes
│ 
│ The Rules Intra In for the nsg is not valid.
```

The object/map comparison is still not working as expected.

I think what would be good here, is rather than 'module.nsg.rules_intra["intra-subnet-communication-in"] is object with 20 attributes'

is an output of
```
module.nsg.rules_intra["intra-subnet-communication-in"] is object with 20 attributes:

*exact output of module.nsg.rules_intra["intra-subnet-communication-in"]*
```
kind of like it returns for strings - you expect x, but the output is y.


Apologies, are you saying that Terraform cannot perform this kind of diff?

I'll do some more testing, and see if we get a similar behavior when it comes to arrays too.

Can we re-open this please, as I believe this is a bug?

**Comment by jbardin** [comment]
Terraform appears to be operating as designed, so we wouldn't classify this as a bug, but there may be some improvement to make, because the output does seem to be misleading you somehow. 

From your description the comparison is working correctly, but you would like more detailed output in the error message showing a diff between the objects? We could create a different diagnostic format for this output, but the difficult part is that the `condition` expression can be any arbitrary expression that evaluates to a boolean value, so there often isn't a simple comparison between two objects from which to create a useful diff.

One approach here in constructing the test is that if the expression is too complex to diagnose failures, it can be broken up into smaller expressions and multiple conditions.

**Comment by deitChi** [comment]
I don't believe it needs to be any more complicated than if objects are not equal, dump the user section (as you already do), then dump actual object value, instead of compressing it to count the number of keys.

This could be boiled down to a verbosity setting I believe.

**Comment by jbardin** [comment]
Hi @deitChi, I tried to summarize what we've got here in a new "terraform test" enhancement request #34428

**Comment by deitChi** [comment]
@jbardin 

I've done some more testing
```
test = [
    "10.99.52.0/22",
]

╷
│ Error: Test assertion failed
│ 
│   on virtual_network.tftest.hcl line 21, in run "Apply_Tests":
│   21:     condition = module.vnet.vnet_address_space == [
│   22:       "10.99.52.0/22",
│   23:     ]
│     ├────────────────
│     │ module.vnet.vnet_address_space is list of string with 1 element
│ 
│ The address space for the vnet is not valid.
╵
virtual_network.tftest.hcl... tearing down
virtual_network.tftest.hcl... fail
```

The output of 'test' shown is the output of the exact same value as being tested as incorrect.

Weirdly, this is only happening to arrays of a single item. An array with 2 items is working exactly as expected.

I've tried one line, multiline, comma after first item, no comma.

I believe this may be a bug.

**Comment by jbardin** [comment]
`["10.99.52.0/22"]` is a tuple literal with one element. If you need a `list(string)` you can use the `tolist` type conversion function, `tolist(["10.99.52.0/22"])`. This is one place where new functions may prove useful in the future for easier implicit type conversions.
