### ISSUE TITLE
Required/Recommended IAM linked to each resource source

### ISSUE THREAD

**Issue by mcphersonwhite** [hashicorp/terraform#34445]
### Terraform Version

```shell
latest
```

### Use Cases

I want to tell before I use a resource what IAM policies I will need to execute `terraform apply`. Ideally this would be in the documentation as well as part of the output of the `terraform plan` execution.

### Attempted Solutions

Right now we plan run apply, get a failure due to IAM permissioning, and we open things up a bit, then rinse and repeat.

### Proposal

Add Documentation and output to support showing for which resource creation, update, or deletion  which IAM policies will be required/recommended.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
