### ISSUE TITLE
wrap json data with `jsonencode` when generating configuration

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform#34444]
### Terraform Version

```shell
$ terraform --version
Terraform v1.6.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
```

### Use Cases

```
terraform plan -generate-config-out=billing_policy.tf.import
```

### Attempted Solutions

None

### Proposal

![image](https://github.com/hashicorp/terraform/assets/139780495/738506ee-78f9-4692-b6df-901f339bee0a)

Though `terraform plan` shows pretty printed version.
![image](https://github.com/hashicorp/terraform/assets/139780495/32fed56d-4b1d-4dcc-80ba-adcb1e4cc6a2)

It would be nice if this pretty printed version will be stored into a generated configuration file.

**Comment by crw** [comment]
Thanks for this feature request! If you are viewing this issue and would like to indicate your interest, please use the 👍 reaction on the issue description to upvote this issue. We also welcome additional use case descriptions. Thanks again!

**Comment by kmoe** [comment]
Good idea. This could look really nice. The plan renderer does this for any string attribute value that starts with `{` or `[` and parses as JSON. We could do the same in `genconfig`.

**Comment by EugenKon** [comment]
@kmoe Please, do not forget:

>If you are viewing this issue and would like to indicate your interest, please use the 👍 reaction on the issue description to upvote this issue.
