### ISSUE TITLE
Terraform crashes with exit status 11.

### ISSUE THREAD

**Issue by olanna12** [hashicorp/terraform#34442]
### Terraform Version

```shell
Terraform v1.5.7
on darwin_arm64
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
--
  |  
  | missing manifest record for parent module
  | goroutine 1 [running]:
  | runtime/debug.Stack()
  | /usr/local/go/src/runtime/debug/stack.go:24 +0x65
  | runtime/debug.PrintStack()
  | /usr/local/go/src/runtime/debug/stack.go:16 +0x19
  | github.com/hashicorp/terraform/internal/logging.PanicHandler()
  | /home/circleci/project/project/internal/logging/panic.go:55 +0x153
  | panic({0x2325020, 0xc000d001b0})
  | /usr/local/go/src/runtime/panic.go:890 +0x262
  | github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installLocalModule(0x27b8e82?, 0xc00068e770, {0x0, 0x0}, 0x2475?, {0x2d60eb0, 0xc000d355a8})
  | /home/circleci/project/project/internal/initwd/module_install.go:255 +0xa2e
  | github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installDescendentModules.func1(0xc00068e770)
  | /home/circleci/project/project/internal/initwd/module_install.go:209 +0xf5c
  | github.com/hashicorp/terraform/internal/earlyconfig.ModuleWalkerFunc.LoadModule(0xc000d24ba0?, 0x21?)
  | /home/circleci/project/project/internal/earlyconfig/config_build.go:172 +0x1f
  | github.com/hashicorp/terraform/internal/earlyconfig.buildChildModules(0xc00068e690, {0x2d553a0, 0xc0008c7090})
  | /home/circleci/project/project/internal/earlyconfig/config_build.go:97 +0xa15
  | github.com/hashicorp/terraform/internal/earlyconfig.BuildConfig(0xc000510a00, {0x2d553a0, 0xc0008c7090})
  | /home/circleci/project/project/internal/earlyconfig/config_build.go:22 +0x79
  | github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).installDescendentModules(0xc000891a10, {0x2d72678?, 0xc000cf8a00}, 0x40d63f?, {0x27359be, 0x1}, 0xc000cc24b0, 0x0, {0x2d60eb0, 0xc000d355a8}, ...)
  | /home/circleci/project/project/internal/initwd/module_install.go:122 +0x2aa
  | github.com/hashicorp/terraform/internal/initwd.(*ModuleInstaller).InstallModules(0xc000891a10, {0x2d72678, 0xc000cf8a00}, {0x27359be, 0x1}, 0xc8?, {0x2d60eb0, 0xc000d355a8})
  | /home/circleci/project/project/internal/initwd/module_install.go:101 +0x354
  | github.com/hashicorp/terraform/internal/command.(*Meta).installModules(0xc000a50000, {0xc00006a004?, 0x24?}, 0x6?, {0x2d60eb0, 0xc000d355a8})
  | /home/circleci/project/project/internal/command/meta_config.go:161 +0x1de
  | github.com/hashicorp/terraform/internal/command.(*InitCommand).getModules(0xc000a50000, {0xc00006a004, 0xbc}, 0x27626d6?, 0x0)
  | /home/circleci/project/project/internal/command/init.go:335 +0x374
  | github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc000a50000, {0xc000050050, 0x0, 0x0})
  | /home/circleci/project/project/internal/command/init.go:219 +0x111d
  | github.com/mitchellh/cli.(*CLI).Run(0xc00086e280)
  | /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
  | main.realMain()
  | /home/circleci/project/project/main.go:315 +0x1614
  | main.main()
  | /home/circleci/project/project/main.go:58 +0x19
  | ERRO[0004] Terraform invocation failed in /builds/prod-apse2-i-03b173639d03ecbdb-1/runway/datadog-monitors/root-modules/ap-devinfra/.terragrunt-cache/Dlxh984HwApDhEvCatU0u2H0UFI/Q10xJSoqIi2jIunbwO45OMBXOB0/root-modules/ap-devinfra  prefix=[/builds/prod-apse2-i-03b173639d03ecbdb-1/runway/datadog-monitors/root-modules/ap-devinfra]
  | ERRO[0004] 1 error occurred:
  | * exit status 11
  |  
  | 🚨 Error: The command exited with status 11
  | user command error: exit status 11
  | 📝 Reporting an exit code of the job | 0s
  | Cleaning up 🧹

### Expected Behavior

Exited with status 0

### Actual Behavior

Terraform crashed

### Steps to Reproduce

buildkite step

### Additional Context

n/a

### References

n/a

**Comment by jbardin** [comment]
Hi @olanna12,

Thanks for filing the issue. Can you first verify that this crash still happens with the latest release of Terraform, and hasn't been fixed in the meantime. If there is still a panic, it would help to have a sample configuration which caused that panic to reproduce the issue for troubleshooting.

Thanks!

**Comment by olanna12** [comment]
I upgraded: 

``` ==> Fetching hashicorp/tap/terraform
==> Downloading https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_darwin_arm64.zip
########################################################################################################################################################################################################################################### 100.0%
==> Upgrading hashicorp/tap/terraform
  1.5.7 -> 1.6.6 ```
And I get the result of terraform crashing.

**Comment by olanna12** [comment]
My build ran, so this issue appears resolved!
