### ISSUE TITLE
Terraform crash - source and content cannot both be null

### ISSUE THREAD

**Issue by lindanasredin** [hashicorp/terraform#34454]
### Terraform Version

```shell
Terraform v1.6.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.31.0
+ provider registry.terraform.io/hashicorp/http v3.4.1
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5

Your version of Terraform is out of date! The latest version
is 1.6.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```
Not available
```

### Debug Output

module.agentless_gw_main[0].aws_instance.gw: Creating...
module.agentless_gw_main[0].aws_instance.gw: Still creating... [10s elapsed]
module.agentless_gw_main[0].aws_instance.gw: Creation complete after 20s [id=i-0f7959b2839806334]
module.agentless_gw_main[0].null_resource.gw: Creating...
module.agentless_gw_main[0].null_resource.gw: Provisioning with 'file'...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

source and content cannot both be null
goroutine 9946 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x379e060?, 0x44d57d0?})
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/hashicorp/terraform/internal/builtin/provisioners/file.getSrc({{{0x4512ed0?, 0xc00650f0c0?}}, {0x38b21c0?, 0xc007c0f710?}})
	/Users/runner/work/terraform/terraform/internal/builtin/provisioners/file/resource_provisioner.go:151 +0x1fe
github.com/hashicorp/terraform/internal/builtin/provisioners/file.(*provisioner).ProvisionResource(0xc000a03bc0, {{{{0x4512ed0, 0xc00650f0c0}}, {0x38b21c0, 0xc007c0f710}}, {{{0x4512ed0, 0xc00650f470}}, {0x38b21c0, 0xc007c0f7a0}}, {0x44db7c0, ...}})
	/Users/runner/work/terraform/terraform/internal/builtin/provisioners/file/resource_provisioner.go:101 +0x1c5
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).applyProvisioners(0xc005002000, {0x4530080?, 0xc0024a6fc0}, 0xc0008c4fb0?, 0x1?, {0xc002a74fa8, 0x3, 0x15?})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_abstract_instance.go:2123 +0x99d
github.com/hashicorp/terraform/internal/terraform.(*NodeAbstractResourceInstance).evalApplyProvisioners(0xc005002000, {0x4530080, 0xc0024a6fc0}, 0xc001058420, 0x0?, 0x1)
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_abstract_instance.go:1969 +0x516
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableResourceInstance).managedResourceExecute(0xc0033bd180, {0x4530080, 0xc0024a6fc0})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_apply_instance.go:332 +0x129b
github.com/hashicorp/terraform/internal/terraform.(*NodeApplyableResourceInstance).Execute(0x948b518?, {0x4530080?, 0xc0024a6fc0?}, 0x40?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_apply_instance.go:145 +0x9a
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc004522c60, {0x4530080, 0xc0024a6fc0}, {0x72d0a20, 0xc0033bd180})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x3d58be0, 0xc0033bd180})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc001580de0, {0x3d58be0, 0xc0033bd180}, 0xc00286dd40)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 8605
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8

### Expected Behavior

Terraform should never crash

### Actual Behavior

Terraform crashed

### Steps to Reproduce

Since I didn't provide the terraform configuration files, this is irrelevant.
I will just say that it happened during terraform apply.

**Comment by lindanasredin** [comment]
I found that the 'source' variable I passed a file provisioner was null. Here:
  provisioner "file" {
    source      = var.aaa
    destination = "aaa.jar"

The variable aaa was null.
So this bug is about the fact the Terraform crashed in this case instead of giving an error and exiting gracefully.

**Comment by mariusmagureanu** [comment]
Hey Linda,

The panic you're running into stems from this [line](https://github.com/hashicorp/terraform/blob/main/internal/builtin/provisioners/file/resource_provisioner.go#L151).

The way it looks like - I'd understand it as a situation that should absolutely never occur, hence the panic. Personally, I'd stick with the current implementation. Debatable though if instead an error should have been returned.

On the other hand, there's also this: The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values. (from the go.dev blog).

Curious to see what other more seasoned contributors/maintainers have to say about his topic.

**Comment by lindanasredin** [comment]
Hi Marius,

Thanks for your reply.
Given that the crash message says "This is always indicative of a bug within Terraform" I would think that this is not the desired behavior.
Unless you want to change it to "This is almost always indicative of a bug within Terraform".
Having said that, it's not very important to me that this be fixed, and I only opened this issue due to the above message and before realizing I was passing a null variable value.
