### ISSUE TITLE
MSAL Client Library Support in azurerm_api_management_identity_provider_aad

### ISSUE THREAD

**Issue by navyainturi** [hashicorp/terraform#34459]
### Terraform Version

```shell
Terraform v1.3.6
```

### Use Cases

`azurerm_api_management_identity_provider_aad` resource doesn't have any argument related to Client Library (ADAL & MSAL). By default, the identity provider is configured as ADAL. Need enhancement to support MSAL Application.

### Attempted Solutions

I tried using the terraform resource block `azurerm_api_management_identity_provider_aad` to create Active Directory Integration as Identity Provider in Azure API Management service. 
There is no argument for Client Library, where as Azure now supports ADAL, MSAL.
By default, the identity provider is added as ADAL application.

### Proposal

Add the argument to select ADAL or MSAL as Client Library

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
