### ISSUE TITLE
Local modules do not create a symlink

### ISSUE THREAD

**Issue by kryptoblack** [hashicorp/terraform#34471]
### Terraform Version

```shell
Terraform v1.6.6
on linux_amd64
```

### Affected Pages

[Use registry modules in configuration > Understand how modules work](https://developer.hashicorp.com/terraform/tutorials/modules/module-use#understand-how-modules-work)

### What is the docs issue?

> When using a new module for the first time, you must run either terraform init or terraform get to install the module. When you run these commands, Terraform will install any new modules in the .terraform/modules directory within your configuration's working directory. **For local modules, Terraform will create a symlink to the module's directory.** Because of this, any changes to local modules will be effective immediately, without having to reinitialize or re-run terraform get.

The above paragraph talks about how the modules are installed, and how and where they are stored. With that there is also a comparison with local modules (The line in bold). It says that a symlink is created for local modules, but that is false.

Local modules are directly reference from source with the help of `.terraform/modules/modules.json` file. As also explained below (the note below can be found [here](https://developer.hashicorp.com/terraform/tutorials/modules/module-create#install-the-local-module))

> When installing a remote module, Terraform will download it into the .terraform directory in your configuration's root directory. **When installing a local module, Terraform will instead refer directly to the source directory.** Because of this, Terraform will automatically notice changes to local modules without having to re-run terraform init or terraform get.

Also, as I couldn't find any symlink in `.terraform/modules/`, I came to the conclusion this to be a documentation error.

### Proposal

Make it consistent with the note on the page "Build and use a local module".

> When using a new module for the first time, you must run either terraform init or terraform get to install the module. When you run these commands, Terraform will install any new modules in the .terraform/modules directory within your configuration's working directory. **For local modules, Terraform will instead refer directly to the source directory.** Because of this, any changes to local modules will be effective immediately, without having to reinitialize or re-run terraform get.

**Comment by crw** [comment]
Correct, tutorials are in a private repository. Thanks for this submission!

**Comment by kryptoblack** [comment]
Glad to help!
