### ISSUE TITLE
mock_provider does not work with providers that have required configuration blocks (e.g. azurerm)

### ISSUE THREAD

**Issue by arylatt** [hashicorp/terraform#34489]
### Terraform Version

```shell
Terraform v1.7.0-rc1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.86.0
```

### Terraform Configuration Files

`main.tf`:

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.86.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "test-rg"
  location = "eastus2"
}
```

`main.tftest.hcl`:

```hcl
mock_provider "azurerm" {}

run "main" {
  assert {
    condition     = (azurerm_resource_group.test.name == "test-rg")
    error_message = "name wrong"
  }
}
```

### Debug Output

https://gist.github.com/arylatt/796ee2f5a8576cba2195985c4e7acd33.

### Expected Behavior

Mock provider should initialize and tests should run.

### Actual Behavior

Since the `azurerm` provider requires a `features` block to be defined, the provider initialization fails. There is no way to provide configuration to the mock provider to avoid this error.

### Steps to Reproduce

1. `terraform init`
2. `terraform test`

### Additional Context

https://github.com/hashicorp/terraform/blob/v1.7.0-rc1/internal/configs/mock_provider.go#L35-L36 suggests that there is an expectation that mock providers won't need config. Not sure if this assumption should be changed (since there are providers that require config) or if I should raise this against terraform-providers/terraform-provider-azurerm?

**Comment by arnaudlh** [comment]
It seems we are having the same issue with azuread provider: 
![image](https://github.com/hashicorp/terraform/assets/20535201/9e84b45e-6868-495a-b8d8-8442a1dad29a)

**Comment by liamcervante** [comment]
Hi @arnaudlh, what version of Terraform are you using for this? Or can you share your config? I'm unable to reproduce this as the following is working for me on Terraform v1.7.0.

```hcl
# main.tf

provider "azuread" {}

resource "azuread_group" "example" {
  display_name     = "what"
  security_enabled = true
}
```

```hcl
# main.tftest.hcl

mock_provider "azuread" {}

run "test" {
  assert {
    condition     = azuread_group.example.display_name == "what"
    error_message = "wrong display name"
  }
}
```

```bash
~/terraform/34489 > terraform test
main.tftest.hcl... in progress
  run "test"... pass
main.tftest.hcl... tearing down
main.tftest.hcl... pass

Success! 1 passed, 0 failed.
~/terraform/34489 > terraform version
Terraform v1.7.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azuread v2.47.0
```

**Comment by stusklinar** [comment]
A note on recreation, please use the `azurerm` provider to test, not `azuread`.

This is still an issue on 1.7.1

**Comment by liamcervante** [comment]
Hi @stusklinar, are you able to provide some reproduction config for your error? I am able to get this working on Terraform v1.7.1 with both `azurerm` and `azuread`.

```hcl
# main.tf 

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "main" {
  name     = "example"
  location = "West Europe"
}
```

```hcl
# main.tftest.hcl

mock_provider "azurerm" {}

run "test" {
  assert {
    condition     = azurerm_resource_group.main.name == "example"
    error_message = "wrong name"
  }
}
```

```bash
~/terraform/34489/component > terraform test
main.tftest.hcl... in progress
  run "test"... pass
main.tftest.hcl... tearing down
main.tftest.hcl... pass

Success! 1 passed, 0 failed.
~/terraform/34489/component > terraform version
Terraform v1.7.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v3.89.0
~/terraform/34489/component > 
```

Thanks!
