### ISSUE TITLE
Missing principle_id and tenant_id when use UserAssigned Managed Identity in Azure Linux Function App resource

### ISSUE THREAD

**Issue by bbh111** [hashicorp/terraform#34506]
### Terraform Version

```shell
Terraform v1.4.5
```

### Terraform Configuration Files

```terraform
resource "azurerm_linux_function_app" "this" {
  name                          = sample
  resource_group_name           = sample
  location                      = sample
  service_plan_id               = sample
  virtual_network_subnet_id     = sample
  storage_account_name          = sample
  storage_uses_managed_identity = sample
  functions_extension_version   = "~4"
  https_only                    = true
  public_network_access_enabled = false

  tags = var.tags

  app_settings = {
    xyz

  }

  site_config {
   xyz
  }

  identity {
    type         = "UserAssigned"
    identity_ids = var.identity_ids
  }
}

# Add access policy for function app to access keyvault
resource "azurerm_key_vault_access_policy" "this" {
  key_vault_id = var.automation_key_vault_resource_id
  tenant_id    = azurerm_linux_function_app.this.identity[0].tenant_id
  object_id    = azurerm_linux_function_app.this.identity[0].principal_id

  secret_permissions = [
    "Get",
  ]

  depends_on = [azurerm_linux_function_app.this]
}
```

### Debug Output

```text
│ Error: expected "tenant_id" to be a valid UUID, got 
│ 
│   with module.function_app.azurerm_key_vault_access_policy.this,
│   on modules/function_app/main.tf line 211, in resource "azurerm_key_vault_access_policy" "this":
│  211:   tenant_id    = azurerm_linux_function_app.this.identity[0].tenant_id
│ 
╵
╷
│ Error: expected "object_id" to be a valid UUID, got 
│ 
│   with module.function_app.azurerm_key_vault_access_policy.this,
│   on modules/function_app/main.tf line 212, in resource "azurerm_key_vault_access_policy" "this":
│  212:   object_id    = azurerm_linux_function_app.this.identity[0].principal_id
```

### Expected Behavior

Can be able to retrieve `tenant_id` and `principal_id` from attached MSI

### Actual Behavior

When I investigated the issue, I found in the terraform state file, identity block doesn't contain any value of both `principle_id` and `tenant_id`. FYI, this is a short of my tf.state file.
![Screenshot 2024-01-09 154742](https://github.com/hashicorp/terraform/assets/57821851/fe52b6e1-ed10-4b58-8a94-8fbdcf895357)

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

If I use SystemAssigned MSI, there is no problem, I can still add access policy for function app to access keyvault .

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
