### ISSUE TITLE
AWS DataSync task report does not get removed when task_report_config is removed from terraform config

### ISSUE THREAD

**Issue by jesse-bentz** [hashicorp/terraform#34509]
### Terraform Version

```shell
> terraform --version
Terraform v1.6.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.4.1
+ provider registry.terraform.io/hashicorp/aws v5.31.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
```

### Terraform Configuration Files

```terraform
 dynamic "task_report_config" {
    # BUG: Does not get removed from Task when this evaluates to empty
    for_each = var.report_enabled ? [1] : []
    content {
      s3_destination {
        bucket_access_role_arn = var.task_execution_report_role_arn
        s3_bucket_arn          = "arn:aws:s3:::${var.task_report_bucket}"
        subdirectory           = var.task_report_bucket_prefix
      }
      # SUMMARY_ONLY does not seem to work, bug?
      output_type          = "STANDARD"
      report_level         = "SUCCESSES_AND_ERRORS"
      s3_object_versioning = "NONE"
 }
 ```

### Debug Output

https://gist.github.com/jesse-bentz/b269086cd65c9acaa7e2cbffc3c265c5

### Expected Behavior

Task report should be removed from AWS resource (set to None)

### Actual Behavior

Task report config unchanged. It does not get removed. Terraform plan continues to show that it will get removed.

### Steps to Reproduce

1. Create a task with `task_report_config` defined
2. Run terraform apply
3. Remove `task_report_config`
4. Run terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
