### ISSUE TITLE
Resource change causes its ID and resources dependent on the ID to be evaluated after apply

### ISSUE THREAD

**Issue by stanicek** [hashicorp/terraform#34522]
### Terraform Version

```shell
Tested on 1.4.4, 1.6
```

### Terraform Configuration Files

```
resource "oci_core_vcn" "vcn" {
  compartment_id = local.compartment_id
  cidr_blocks = [local.cidr]
}

resource "oci_core_subnet" "subnet" {
  cidr_block     = local.cidr
  compartment_id = local.compartment_id
  vcn_id         = oci_core_vcn.vcn.id
}

resource "oci_load_balancer" "load_balancer" {
  compartment_id = local.compartment_id
  display_name   = "my-load-balancer"
  shape          = "flexible"
  shape_details {
    maximum_bandwidth_in_mbps = 10
    minimum_bandwidth_in_mbps = 10
  }
  subnet_ids     = [oci_core_subnet.subnet.id]
}

data "oci_core_private_ips" "private_ips" {
  subnet_id = oci_core_subnet.subnet.id
  filter {
    name   = "display_name"
    values = [".*${oci_load_balancer.load_balancer.id}.*"]
    regex  = true
  }
}

output "ips" {
  value = data.oci_core_private_ips.private_ips.private_ips
}
```

### Debug Output

https://gist.github.com/stanicek/1d3b20418ae39e6e82390b66b51e5a4f

### Expected Behavior

When resources fully deployed, additional bandwidth increase should only affect load balancer resource. No additional changes to outputs as load balancer ID is well known and immutable.

```
Changes to Outputs:
  "... None ..."
```

### Actual Behavior

When resources fully deployed, additional bandwidth increase causes output change with an unknown result as Terraform thinks bandwidth change can cause ID change and waits with the output evaluation after apply, which can cause unpredictable results.

```
Changes to Outputs:
  ~ ips = [
      - { ... STH ...},
      - { ... STH ...},
    ] -> (known after apply)

```

### Steps to Reproduce

1. terraform apply
2. increase LB bandwidth
3. terraform plan & check the plan

### Additional Context

Can ID be marked as immutable at provider level (OCI Terraform Provider) / provider schema. Or is it a Terraform thing?

### References

I didn't find similar, might've used a wrong terminology.

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
