### ISSUE TITLE
Issue is RDS Aurora engine version upgrade from 5.7 to 8.0 because  of parameter group issue

### ISSUE THREAD

**Issue by varunkumarmnnit** [hashicorp/terraform#34539]
### Terraform Version

```shell
0.13
```

### Terraform Configuration Files

```resource "aws_rds_cluster" "{service-name}-db" {
  apply_immediately                   = false
  engine                              = local.rds_engine
  engine_version                      = local.rds_engine_aurora8
  cluster_identifier                  = "${var.rds_cluster_name}-db"
  database_name                       = var.rds_name
  master_username                     = var.rds_username
  master_password                     = module.vault_db_password.secret_value
  allow_major_version_upgrade          = true
  backup_retention_period             = 7
  preferred_backup_window             = var.backup_window
  preferred_maintenance_window        = var.maintenance_window
  vpc_security_group_ids              = [aws_security_group.{service-name}-db-sg.id]
  db_subnet_group_name                = aws_db_subnet_group.{service-name}-db.name
  iam_database_authentication_enabled = true
  deletion_protection                 = true
  tags                                = module.{service-name}_tags.tags
  db_cluster_parameter_group_name     = aws_rds_cluster_parameter_group.{service-name}_cluster_parameter_group_updated.id
  db_instance_parameter_group_name    = aws_db_parameter_group.rds_instance_parameter_group_updated.id
  iam_roles                           = [aws_iam_role.rds_role_create_for_s3_snapshot.arn]
  //depends_on                          = [aws_rds_cluster_parameter_group.{service-name}_cluster_parameter_group_updated
  //]
}

resource "aws_rds_cluster_instance" "{service-name}-db_instances" {
  engine             = aws_rds_cluster.{service-name}-db.engine
  engine_version     = aws_rds_cluster.{service-name}-db.engine_version
  identifier         = "${var.rds_cluster_name}-db"
  count              = local.db_instance_count
  cluster_identifier = aws_rds_cluster.{service-name}-db.id
  instance_class     = local.db_instance_size

  tags               = module.{service-name}_tags.tags
  db_parameter_group_name = aws_db_parameter_group.rds_instance_parameter_group_updated.id
}


resource "aws_rds_cluster_parameter_group" "{service-name}_cluster_parameter_group_updated" {
  name        = "${var.app_name}-{service-name}-cluster-parameter-group-updated"
  family      = "aurora-mysql8.0"
  description = "Cluster parameter group for {service-name}"
  tags        = module.{service-name}_tags.tags


  parameter {
    name  = "aws_default_s3_role"
    value = aws_iam_role.rds_role_create_for_s3_snapshot.arn
  }

  # Turn on the event scheduler that will actually do the setup
  parameter {
    name  = "event_scheduler"
    value = "ON"
  }

  parameter {
    name  = "log_bin_trust_function_creators"
    value = 1
  }
  parameter {
    name  = "max_allowed_packet"
    value = "1073741824"
  }
}

resource "aws_db_parameter_group" "rds_instance_parameter_group_updated"{

  name        = "${var.app_name}-{service-name}-db-parameter-group-updated"
  family      = "aurora-mysql8.0"
  description = "Cluster parameter group for {service-name}"
  tags        = module.{service-name}_tags.tags

  # Turn on the event scheduler that will actually do the setup


  parameter {
    name  = "log_bin_trust_function_creators"
    value = 1
  }

  parameter {
    name  = "max_allowed_packet"
    value = "1073741824"
  }
}
...terraform config...
```

### Debug Output

Error: updating RDS Cluster (brands-{service-name}-{service-name}-db): InvalidParameterCombination: The current DB instance parameter group {service-name}-{service-name}-db-parameter-group is custom. You must explicitly specify a new DB instance parameter group, either default or custom, for the engine version upgrade.
        status code: 400, request id: 6cde5aab-59ae-4b98-85ce-cb38915d29ce

  on rds.tf line 2, in resource "aws_rds_cluster" "{service-name}-db":
   2: resource "aws_rds_cluster" "{service-name}-db" {

### Expected Behavior

RDS cluster engine version should be upgraded with 8.0 with new updated parameter grp

### Actual Behavior

Getting error   where rds cluster is referring to older parameter group even though I haven't referred older one in the updated engine version of rds cluster .

InvalidParameterCombination: The current DB instance parameter group {service-name}-{service-name}-db-parameter-group is custom. You must explicitly specify a new DB instance parameter group, either default or custom, for the engine version upgrade

### Steps to Reproduce

terraform apply

### Additional Context

This is the plan output 

# aws_rds_cluster.{service-name}-db will be updated in-place
  ~ resource "aws_rds_cluster" "{service-name}-db" {
        allocated_storage                   = 1
        allow_major_version_upgrade         = true
        apply_immediately                   = false
        arn                                 = #########
        availability_zones                  = [
            "us-east-1b",
            "us-east-1c",
            "us-east-1d",
        ]
        backtrack_window                    = 0
        backup_retention_period             = 7
        cluster_identifier                  = "brands-{service-name}-service-db"
        cluster_members                     = [
            "brands-{service-name}-service-db",
        ]
        cluster_resource_id                 = "cluster-######"
        copy_tags_to_snapshot               = false
        database_name                       = "{service-name}"
      ~ db_cluster_parameter_group_name     = "{service-name}-{service-name}-cluster-parameter-group" -> "{service-name}-{service-name}-cluster-parameter-group-updated"
        db_instance_parameter_group_name    = "{service-name}-{service-name}-db-parameter-group-updated"
        db_subnet_group_name                = "{service-name}-services"
        deletion_protection                 = true
        enable_global_write_forwarding      = false
        enable_http_endpoint                = false
        enabled_cloudwatch_logs_exports     = []
        endpoint                            = ###########
        engine                              = "aurora-mysql"
        engine_mode                         = "provisioned"
      ~ engine_version                      = "5.7.mysql_aurora.2.11.2" -> "8.0.mysql_aurora.3.02.2"
        engine_version_actual               = "5.7.mysql_aurora.2.11.2"
        hosted_zone_id                      = ##################
        iam_database_authentication_enabled = true
        iam_roles                           = [
            #########################
        ]
        id                                  = "brands-{service-name}-service-db"
        iops                                = 0
        master_password                     = (sensitive value)
        master_username                     = "{service-name}db"
        network_type                        = "IPV4"
        port                                = 3306
        preferred_backup_window             = ###############
        preferred_maintenance_window        = ################
        reader_endpoint                     =##########################
        skip_final_snapshot                 = false
        storage_encrypted                   = false
        tags                                = {
            "Application"      = "{service-name}"
            "ApplicationGroup" =#########
            "Compliance"       = "None"
            "Department"       = "Engineering"
            "Environment"      = "stable"
            "IncidentEmail"    = #################
            "Name"             = "{service-name}"
            "ProvisionedBy"    = "infra-registry"
            "Team"             = ########
            "TeamEmail"        = ##########
            "Vertical"         = #############
        }
        tags_all                            = {
            "Application"      = "{service-name}"
            "ApplicationGroup" = ##########
            "Compliance"       = "None"
            "Department"       = "Engineering"
            "Environment"      = "stable"
            "IncidentEmail"    = ##########
            "Name"             = "{service-name}"
            "ProvisionedBy"    = "infra-registry"
            "Team"             = #######
            "TeamEmail"        = ########
            "Vertical"         = "Brands"
        }
        vpc_security_group_ids              = [
          ######################
        ]
    }

  # aws_rds_cluster_instance.{service-name}-db_instances[0] will be updated in-place
  ~ resource "aws_rds_cluster_instance" "{service-name}-db_instances" {
        arn                                   = ###########
        auto_minor_version_upgrade            = true
        availability_zone                     = ############
        ca_cert_identifier                    = ##########
        cluster_identifier                    = "brands-{service-name}-service-db"
        copy_tags_to_snapshot                 = false
      ~ db_parameter_group_name               = "{service-name}-{service-name}-db-parameter-group" -> "{service-name}-{service-name}-db-parameter-group-updated"
        db_subnet_group_name                  = "{service-name}-services"
        dbi_resource_id                       = ###########
        endpoint                              = ########
        engine                                = "aurora-mysql"
      ~ engine_version                        = "5.7.mysql_aurora.2.11.2" -> "8.0.mysql_aurora.3.02.2"
        engine_version_actual                 = "5.7.mysql_aurora.2.11.2"
        id                                    = "brands-{service-name}-service-db"
        identifier                            = "brands-{service-name}-service-db"
        instance_class                        = "db.t4g.medium"
        monitoring_interval                   = 0
        network_type                          = "IPV4"
        performance_insights_enabled          = false
        performance_insights_retention_period = 0
        port                                  = 3306
        preferred_backup_window               =#######
        preferred_maintenance_window          = ########
        promotion_tier                        = 0
        publicly_accessible                   = false
        storage_encrypted                     = false
      ~ tags                                  = {
            "Application"      = "{service-name}"
            "ApplicationGroup" = "brands"
            "Compliance"       = "None"
            "Department"       = "Engineering"
            "Environment"      = "stable"
            "IncidentEmail"    = #########
            "Name"             = "{service-name}"
          - "Owner"            = ##########
            "ProvisionedBy"    = "infra-registry"
            "Team"             = "brands"
            "TeamEmail"        = ################
            "Vertical"         = ######
        }
      ~ tags_all                              = {
            "Application"      = "{service-name}"
            "ApplicationGroup" = "brands"
            "Compliance"       = "None"
            "Department"       = "Engineering"
            "Environment"      = "stable"
            "IncidentEmail"    = #########
            "Name"             = "{service-name}"
          - "Owner"            = ########
            "ProvisionedBy"    = "infra-registry"
            "Team"             = "brands"
            "TeamEmail"        = ########
            "Vertical"         = "Brands"
        }
        writer                                = true
    }

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
