### ISSUE TITLE
terraform plan -refresh-only not updating terraform.tfstate file

### ISSUE THREAD

**Issue by iamhritik** [hashicorp/terraform#34535]
### Terraform Version

```shell
Terraform v1.6.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.32.1
```

### Terraform Configuration Files

```terraform
resource "aws_instance" "instance_poc" {
    ami = "ami-03f4878755434977f"
    instance_type = "t2.micro"
    root_block_device {
      volume_size = 10
      volume_type = "gp3"
      encrypted = true
      delete_on_termination = true
    }

}
```

### Debug Output

[tf-trace-logs.txt](https://github.com/hashicorp/terraform/files/13963874/tf-trace-logs.txt)

### Expected Behavior

It also updates the state file when running `terraform plan -refresh-only` after manually deleting the instance from the aws console.

### Actual Behavior

Not updating terraform.tfstate file when running `terraform plan -refresh-only` after manually deleting the instance from the aws console.

### Steps to Reproduce

Test Scenario:--->

Created an instance (instanceA) using Terraform resource block.
Manually deleted instanceA from the console.

Execution Steps:--
Run terraform plan -refresh=false -> No changes expected.
Run terraform plan -refresh-only -> Note: Objects have changed outside of Terraform, but it will not make any changes in the terraform.tfstate file.
Run terraform refresh -> Removed instanceA from the terraform.tfstate file.
Run terraform plan -refresh=false -> Plan: 1 to add, 0 to change, 0 to destroy.
Run terraform plan -refresh-only -> No changes. Your infrastructure still matches the configuration.

**Comment by apparentlymart** [comment]
Hi @iamhritik,

If you want to commit the detected changes as a new state snapshot, you would need to use `terraform apply -refresh-only` instead. Planning alone only shows what Terraform _would_ do; you need to apply the plan for the changes to persist.

If you are working in a system where plan and apply are separated into separate steps, e.g. so that something can evaluate policies against the saved plan file, then the two-step alternative to the above would be:

* `terraform plan -refresh-only -out=tfplan`
* (check the saved plan as needed)
* `terraform apply tfplan`

However, `terraform apply -refresh-only` is an equivalent shorthand if you don't need to do anything special other than interactively reviewing the plan and approving it.

**Comment by apparentlymart** [comment]
In that tutorial I see this the following text:

> Run `terraform plan -refresh-only` to review how Terraform would update your state file.
>
> [...]
>
> If the modifications to your state file proposed by a `-refresh-only` plan were acceptable, you could run a `terraform apply -refresh-only` and approve the operation to overwrite your state file without modifying your infrastructure. However, in this tutorial, refreshing your state file would drop your resources, so do not run the apply operation.

There's also some notes on that page about the legacy `terraform refresh` command and how it relates to refresh-only plans, which mentions that `-refresh-only` is valid for both the `terraform plan` and `terraform apply` commands.

I can't find anything on that page which suggests that `terraform plan -refresh-only` would immediately create a new state snapshot. Can you quote the specific part that you are referring to? I'd love to pass feedback on to the team which maintains these tutorials to help make this text clearer. Thanks!

**Comment by iamhritik** [comment]
In this line, they mentioned that we can also update our state file without making modifications to your infrastructure using the -refresh-only flag for plan and apply operations.


![Selection_024](https://github.com/hashicorp/terraform/assets/47936485/c3528063-2d87-4f51-af0b-85c642c1f9fd)

**Comment by iamhritik** [comment]
Thanks for your answer. Now, I understand that `terraform plan -refresh-only` will only show the changes it will make to my terraform.tfstate. If I want to apply these changes, then I can use the `terraform apply -refresh-only` command.
