### ISSUE TITLE
Unsupported argument "target_object_key_format" in resource aws_s3_bucket_logging despite using aws-provider v5.31

### ISSUE THREAD

**Issue by dbrat43** [hashicorp/terraform#34544]
### Terraform Version

```shell
$ terraform version
Terraform v1.0.11
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.7.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```
resource "aws_s3_bucket_logging" "example" {
  bucket = "bucket-1"

  target_bucket = "bucket-2"
  target_prefix = "log/"

  target_object_key_format = {
    partitioned_prefix = {
      partition_date_source = "DeliveryTime"
    }
  }
}
```

### Debug Output

 Error: Unsupported argument
│ 
│   on main.tf line 209, in resource "aws_s3_bucket_logging" "example":
│  209:   target_object_key_format = {
│ 
│ An argument named "target_object_key_format" is not expected here. Did you
│ mean to define a block of type "target_object_key_format"?
╵
2024-01-18T19:47:47.127Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2024-01-18T19:47:47.138Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/5.31.0/linux_amd64/terraform-provider-aws_v5.31.0_x5 pid=367
2024-01-18T19:47:47.138Z [DEBUG] provider: plugin exited

### Expected Behavior

The resource should have been able to recognize the target_object_key_format property and configure the partitioned date prefix for server access logs given that this configuration block has been present since aws-provider v5.27 - https://registry.terraform.io/providers/hashicorp/aws/5.31.0/docs/resources/s3_bucket_logging#target_object_key_format 

### Actual Behavior

The apply errored out

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
