### ISSUE TITLE
VARIABLES: Allow skipping nested object key checking if the parent is optional and not passed.

### ISSUE THREAD

**Issue by svaraksin-gd** [hashicorp/terraform#34551]
### Terraform Version

```shell
Terraform v1.6.6
```

### Terraform Configuration Files

```terraform
variable "api_settings" {
  type = map(object({
    backend_name               = string
    protocol                   = string
    url                        = optional(string)
    validate_certificate_chain = optional(bool)
    validate_certificate_name  = optional(bool)
    revision                   = number
    api_type                   = optional(string)
    path                       = optional(string)
    protocols                  = optional(list(string))
    api_operations = list(object({
      method       = string
      url_template = string
      display_name = optional(string)
      operation_id = optional(string)
      template_parameters = optional(list(object({
        name          = string
        required      = bool
        type          = string
        description   = optional(string)
        default_value = optional(string)
        values        = optional(list(string))
        schema_id     = optional(string)
        type_name     = optional(string)
        examples      = optional(list(any), [])
      })), [])
      description = optional(string)
      policy_xml  = optional(any)
      tags        = optional(list(string))
    }))
    policy_xml = optional(any)
  }))
}
```

### Debug Output

-

### Expected Behavior

If "template_parameters" is OPTIONAL and not specified I'm expecting that nested definitions will be ignored in this case

### Actual Behavior

The given value is not suitable for
module.platform.module.infrastructure.module.api_management["01"].var.api_settings
declared at ../../modules/resources/api-management/vars.tf:77,1-24: element
"api": attribute "api_operations": element 1: attribute
"template_parameters": element 0: attribute "type" is required.

### Steps to Reproduce

-

**Comment by jbardin** [comment]
Hi @svaraksin-gd,

Can you explain with an example what you mean by "nested definitions will be ignored"? If `template_parameters` is optional, then you do not need to apply that attribute in the given object. That however does not make required attributes in nested objects optional, so the `type` attribute will be required for any objects in that list. If you want `type` to be optional, you will need to specify it as such.

Thanks!

**Comment by svaraksin-gd** [comment]
Thanks for the quick response! Really appreciate it.

What I'm saying is that if an object is marked as optional, then it should be optional anyway. Even if internal objects require customization.
Behavior I expect:
If an optional element is specified (you pass it through variables), then nested elements must be checked to see if they are required/optional.
If the optional element is not specified, nested dependency checking is skipped.

Answering to @apparentlymar.
This parameter was not passed to the input.
The definition actually contains the default value as an empty list [].
But it is expected that this check will be applied to an object in the list that acts as a map, and not to the list itself.

Are you saying that I can do it like this:
```
variable "api_settings" {
  type = map(object({
    ...
    api_operations = list(object({
      ...
      template_parameters = optional(list(optional(object({
        name          = string
        required      = bool
        type          = string
        ...
      }))), [])
      ...
    }))
    ...
  }))
}
```

?

**Comment by apparentlymart** [comment]
Hi @svaraksin-gd,

The error message you shared mentions "element 0", which suggests that the list that Terraform was checking has at least one element. That seems to conflict with your claim that the attribute was not set when calling the module.

I think to figure out what's going on here it would be best to share the full `module` block that's calling this module, exactly as you tried it when you saw this error (nothing omitted), and then hopefully we can reproduce the problem you observed to understand why this error appeared.

If your real example is too complicated to share or contains information that you'd rather not disclose, then an alternative would be to write a new separate configuration which demonstrates this problem in a more limited way, run it to make sure you see an equivalent error, and then share that simpler configuration.

Thanks!

**Comment by svaraksin-gd** [comment]
@apparentlymart 
Thank you very much for your support!

I'll try to do it. But after reading your message, I recalled (not 100% sure) that maybe you are right, and I missed one small-big detail in my configuration.
But first let me check this again.

Sorry about that. I think this topic can be closed for now, I’ll open it when I have time to check (we’ve gone the other way at the moment).
