### ISSUE TITLE
aws_security_group_rule issue

### ISSUE THREAD

**Issue by jira-zz** [hashicorp/terraform#34553]
### Terraform Version

```shell
Terraform v1.7.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.24.0
```

### Terraform Configuration Files

```
resource "aws_security_group_rule" "ps-production-chr-ssh"        { 
type      = "ingress"
source_security_group_id    = aws_security_group.ps-production.id
description         = "SSH for security group"                                                                                                  
from_port           = 22 
to_port             = 22 
prefix_list_ids     = [] 
protocol            = "tcp"  
security_group_id     = aws_security_group.ps-production-chr.id                                                                                 
}
```

### Debug Output

https://gist.github.com/jira-zz/e8eed7c0e33737fc7f333c091f4ce8d5

### Expected Behavior

When the security group rule exists in aws, terraform will do nothing. When it does not exist it should create it.

### Actual Behavior

When the security group rule exists in aws terraform will delete it. When it does not exist it will create it.

### Steps to Reproduce

    terraform init
    terraform apply

### References

 Every time I run terraform, it wants to delete my existing aws_security_group_rule.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
