### ISSUE TITLE
aws_key_pair: updates AWS keypair unnecessarily

### ISSUE THREAD

**Issue by SpencerBrown** [hashicorp/terraform#3455]
originally had resource:

```
resource "aws_key_pair" "kube_key_pair" {
  key_name = "kube-key"
  public_key = ".... a long string pasted from kube-key-test.pub ..."
}
```

then I changed it to:

```
resource "aws_key_pair" "kube_key_pair" {
  key_name = "kube-key"
  public_key = "${file("kube-key-tst.pub")}"
}
```

Then I ran terraform plan, expecting it to say nothing had changed.

However, it wanted to modify the keypair on AWS.

**Comment by stack72** [comment]
@SpencerBrown this sounds like an issue with whitespace or something formatting related.

**Comment by stack72** [comment]
@SpencerBrown ok, I have definitely confirmed that this is the case.

My Keypair was as follows:

```
resource "aws_key_pair" "digit_terraform" {
  key_name = "digit_terraform"
  public_key = "${file(\"ssh/digit_terraform.pub\")}"*/
}
```

When i changed that to the string itself (by copying and pasting), I got the following:

```
-/+ aws_key_pair.digit_terraform
    fingerprint: "03:e6:00:98:32:98:c8:cd:45:b0:ae:3c:84:34:a5:ce" => "<computed>"
    key_name:    "digit_terraform" => "digit_terraform"
    public_key:  "ssh-rsa ....." (forces new resource)
```

**Comment by catsby** [comment]
Hey @SpencerBrown and @stack72 , thanks for writing in.

Can you confirm/deny for me that the `public_key` from the version using the `file()` function in your plan output contains a `\n` at the end? That's what I'm seeing... Both formats seem to produce a key that I can still use to ssh with...

**Comment by stack72** [comment]
@catsby remove the \n off the end of the string and that's what I believe is the issue. It's forcing a new key. **I do not believe this to be a bug to terraform**

**Comment by catsby** [comment]
@stack72 dunno, I tested 4 of my local keys and they all behave like this. It's possible I suppose that those 4 are malformed with whitespace, but as I mentioned above I can still ssh with the `\n` in it, so that makes me think it's OK as far as SSH is concerned. 

That leads me to think that this is a Terraform thing, or at least a thing Terraform should accommodate. If it's the same key, then swapping `${file()}` for it's contents directly inline should show no change, agree? 

The fix is simple. Backwards compatibility likely requires a migration...

**Comment by catsby** [comment]
I've opened https://github.com/hashicorp/terraform/pull/3470 as a patch to this

**Comment by duttadeep55** [comment]
I coded : (key-pairs.tf)
---------------------------------------------------------
resource "aws_key_pair" "deployer" {
  key_name = "deployer-key"
  public_key = "${file(\"ssh/insecure-deployer.pub\")}"
}
----------------------------------------------------------


Error  : 
----------------------------------------------------------
key-pairs.tf: Error reading config for aws_key_pair[deployer]: parse error: syntax error
----------------------------------------------------------

**Comment by woyczek** [comment]
It may require a '\n' at the end of the key value.
