### ISSUE TITLE
aws_s3_bucket_server_side_encryption_configuration resource asks for kms_master_key_id variable but requests arn

### ISSUE THREAD

**Issue by SteveNadraus** [hashicorp/terraform#34570]
### Terraform Version

```shell
Terraform v1.6.6
on windows_386
+ provider registry.terraform.io/hashicorp/aws v5.33.0
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_server_side_encryption_configuration

### What is the docs issue?

resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
  bucket = aws_s3_bucket.mybucket.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.mykey.arn
      sse_algorithm     = "aws:kms"
    }
  }
}

Resource asks for a kms_master_key_id but requires the arn.

### Proposal

Update the variable kms_master_key_id to kms_master_key_arn

**Comment by apparentlymart** [comment]
Hi @SteveNadraus,

What you've described here seems to be behavior of the `hashicorp/aws` provider, rather than of Terraform itself. Please open this issue in [the provider's own repository](https://github.com/hashicorp/terraform-provider-aws) instead. Thanks!
