### ISSUE TITLE
Removed module from a for_each

### ISSUE THREAD

**Issue by fatbasstard** [hashicorp/terraform#34573]
### Terraform Version

```shell
1.7.1
```

### Terraform Configuration Files

```terraform
locals {
  test_list = ["test1","test2"]
}

module "test" {
  for_each = toset(local.test_list)

  source = "./test"
}

# Remove "test1" from the list and then try to remove it from the state file
removed {
  from = module.test["test1"]

  lifecycle {
    destroy = false
  }
}
```

Step 1:
- Create modules from a list
- Remove item from list

### Debug Output

```cli
│ Error: Module instance keys not allowed
│ 
│   on main.tf line 60, in removed:
│   60:   from = module.test["test1"]
│ 
│ Module address must be a module (e.g. "module.foo"), not a module instance (e.g. "module.foo[1]").
```

### Expected Behavior

Remove the module from the state file

### Actual Behavior

Error that removed cannot be done

### Steps to Reproduce

See above. Remove item from the list and try to remove it from the state file using `removed`

### References

https://github.com/hashicorp/terraform/issues/34439

**Comment by jbardin** [comment]
Hi @fatbasstard,

The behavior shown is intended, so does not represent a bug in the implementation. Work on adding more advanced abilities to the `removed` block is being done however. We have an enhancement request tracking instance support for removal already in #34439

Thanks!

**Comment by fatbasstard** [comment]
Hi @jbardin ,

Thanks for the reply. Saw the other issue but was unsure if it covered exactly the same scenario, so therefor created a ticket as "bug". But I'll keep an eye on the other ticket and hope it will be implemented. Because the `removed` feature is great!
