### ISSUE TITLE
`terraform fmt` does not handle `.tfmock.hcl` files

### ISSUE THREAD

**Issue by HenriBlacksmith** [hashicorp/terraform#34577]
### Terraform Version

```shell
Terraform v1.7.1
```

### Use Cases

When using the Terraform 1.7 mocks feature as suggested in the official tutorial: https://developer.hashicorp.com/terraform/language/tests/mocking#mock-provider-data

Terraform formatting does not apply to the `.tfmock.hcl` files

```shell
terraform fmt tests/aws/data.tfmock.hcl
╷
│ Error: Only .tf, .tfvars, and .tftest.hcl files can be processed with terraform fmt
│ 
│ 
╵
```

### Attempted Solutions

Renaming the file with `.tftest.hcl` extension before formatting is a workaround to get it formatted with:
`terraform fmt tests/aws/data.tftest.hcl`

### Proposal

Extending `fmt` subcommand to `.tfmock.hcl` files

**Comment by liamcervante** [comment]
Thanks @HenriBlacksmith, this seems perfectly reasonable to me. It should be a fairly easy fix, we just need to add the new extension to https://github.com/hashicorp/terraform/blob/main/internal/command/fmt.go#L31-L34 and add some [test cases](https://github.com/hashicorp/terraform/tree/main/internal/command/testdata/tftest-fmt). 

We can launch this in the next minor release. I'll get around to adding this before we release 1.8.0, but will happily review any PRs from willing contributors before then!

**Comment by HenriBlacksmith** [comment]
@liamcervante will see if I can give it a try, except if anyone is faster (suits me too).
