### ISSUE TITLE
Unable to add multiple instance in Target_id field in NLB.

### ISSUE THREAD

**Issue by farooq31325** [hashicorp/terraform#34590]
### Terraform Version

```shell
Latest
```

### Terraform Configuration Files

```resource "aws_lb_target_group_attachment" "this" {
  for_each = { for k, v in var.target_groups : k => v if local.create && lookup(v, "create_attachment", true) }

  target_group_arn  = aws_lb_target_group.this[each.key].arn
  target_id         = each.value.target_id
  port              = try(each.value.target_type, null) == "lambda" ? null : try(each.value.port, var.default_port)
  availability_zone = try(each.value.availability_zone, null)

  depends_on = [aws_lambda_permission.this]
}
```

### Debug Output

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 5.31.0"...
- Using hashicorp/aws v5.33.0 from the shared cache directory

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Incomplete lock file information for providers
│ 
│ Due to your customized provider installation methods, Terraform was forced
│ to calculate lock file checksums locally for the following providers:
│   - hashicorp/aws
│ 
│ The current .terraform.lock.hcl file only includes checksums for
│ linux_amd64, so Terraform running on another platform will fail to install
│ these providers.
│ 
│ To calculate additional checksums for another platform, run:
│   terraform providers lock -platform=linux_amd64
│ (where linux_amd64 is the platform to generate)
╵

Terraform has been successfully initialized!
data.aws_partition.current: Reading...
data.aws_partition.current: Read complete after 0s [id=aws]
2024-01-19T16:31:55.379Z [ERROR] vertex "aws_lb_target_group_attachment.this[\"ex-target-one\"]" error: Incorrect attribute value type
2024-01-19T16:31:55.379Z [ERROR] vertex "aws_lb_target_group_attachment.this (expand)" error: Incorrect attribute value type

Error: Incorrect attribute value type

  on main.tf line 527, in resource "aws_lb_target_group_attachment" "this":
 527:   target_id         = each.value.target_id
    ├────────────────
    │ each.value.target_id is tuple with 2 elements

Inappropriate value for attribute "target_id": string required.
time=2024-01-19T16:31:55Z level=error msg=Hit multiple errors:
Hit multiple errors:
exit status 1

terragrunt version v0.29.7

Terraform v1.3.7
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.7.0. You can update by downloading from https://www.terraform.io/downloads.html

### Expected Behavior

We have passed target_id details as below, but we are getting error as mentioned above. It Is not picking Multiple Instances.

target_groups = {
      ex-target-onee = {
        name_prefix            = "t1-"
        protocol               = "TCP_UDP"
        port                   = 81
        target_type            = "instance"
        targets = [
            {
                    target_id = "******01"
                    #port = 80
            },
            {
                    target_id = "*****02"
            }
          ] 

### Actual Behavior

We have passed target_id details as below, but we are getting error as mentioned below. It Is not picking Multiple Instances.

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 5.31.0"...
- Using hashicorp/aws v5.33.0 from the shared cache directory

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Incomplete lock file information for providers
│ 
│ Due to your customized provider installation methods, Terraform was forced
│ to calculate lock file checksums locally for the following providers:
│   - hashicorp/aws
│ 
│ The current .terraform.lock.hcl file only includes checksums for
│ linux_amd64, so Terraform running on another platform will fail to install
│ these providers.
│ 
│ To calculate additional checksums for another platform, run:
│   terraform providers lock -platform=linux_amd64
│ (where linux_amd64 is the platform to generate)
╵

Terraform has been successfully initialized!
data.aws_partition.current: Reading...
data.aws_partition.current: Read complete after 0s [id=aws]
2024-01-19T16:31:55.379Z [ERROR] vertex "aws_lb_target_group_attachment.this[\"ex-target-one\"]" error: Incorrect attribute value type
2024-01-19T16:31:55.379Z [ERROR] vertex "aws_lb_target_group_attachment.this (expand)" error: Incorrect attribute value type

Error: Incorrect attribute value type

  on main.tf line 527, in resource "aws_lb_target_group_attachment" "this":
 527:   target_id         = each.value.target_id
    ├────────────────
    │ each.value.target_id is tuple with 2 elements

Inappropriate value for attribute "target_id": string required.
time=2024-01-19T16:31:55Z level=error msg=Hit multiple errors:
Hit multiple errors:
exit status 1

terragrunt version v0.29.7

Terraform v1.3.7
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.7.0. You can update by downloading from https://www.terraform.io/downloads.html

### Steps to Reproduce

1. teraform init.
2. terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
