### ISSUE TITLE
CodeCommit is missing a resource that Cloud formation implements

### ISSUE THREAD

**Issue by kbzg4** [hashicorp/terraform#34600]
### Terraform Version

```shell
1.7.1
```

### Use Cases

Creating a new repository from a template

### Attempted Solutions

have to use a null provider 

### Proposal

implement: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codecommit-repository-s3.html

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
