### ISSUE TITLE
The terraform-provider-azurerm_v3.88.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by suraksha-mind** [hashicorp/terraform#34602]
### Terraform Version

```shell
The terraform-provider-azurerm_v3.88.0_x5 plugin crashed!
```

### Terraform Configuration Files

```working on customer code
deploying all azure resource 

It was working fine till yesterday
```

### Debug Output

	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a81e0, {0x9a07ac0, 0xc001764680}, 0xc002bfa5a0, 0xc001c970e0, 0xf5a4908, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002a81e0, {0x9a07ac0, 0xc001764680}, 0xc002bfa5a0, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 28
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.88.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

Azure Plan with details of how many needs to be created

### Actual Behavior

5 resource will be created

### Steps to Reproduce

pipeline

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
