### ISSUE TITLE
App service public certificate upload is getting error like Parameter publicCertificateEnv is null or empty.

### ISSUE THREAD

**Issue by girish-am** [hashicorp/terraform#34613]
### Terraform Version

```shell
v1.6.0
```
azurerm version 3.99.0

### Terraform Configuration Files

azurerm_app_service_public_certificate

### Debug Output

NA

### Expected Behavior

NA

### Actual Behavior

{"Code":"BadRequest","Message":"Parameter publicCertificateEnv is null or empty.","Target":null,"Details":[{"Message":"Parameter publicCertificateEnv is null or empty."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51011","MessageTemplate":"Parameter {0} is null or empty.","Parameters":["publicCertificateEnv"],"Code":"BadRequest","Message":"Parameter publicCertificateEnv is null or empty."}}],"Innererror":null}

### Steps to Reproduce

terraform init
terraform apply

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_public_certificate
_No response_

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
