### ISSUE TITLE
Patch version not supported in go.mod

### ISSUE THREAD

**Issue by briantopping** [hashicorp/terraform#34620]
### Terraform Version

```shell
N/A
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

N/A

### Expected Behavior

No error from `go mod verify`

### Actual Behavior

go: errors parsing go.mod:
~/go/src/github.com/hashicorp/terraform/go.mod:278: invalid go version '1.21.5': must match format 1.23

### Steps to Reproduce

1. Check out project
2. `go mod verify`

**Comment by jbardin** [comment]
Hi @briantopping,

The `go.mod` file is correct for the version of Go we are using (>= go1.21.5). You are probably running a prior release before patch versions were accepted.

Thanks!

**Comment by briantopping** [comment]
Good eye, thank you!
