### ISSUE TITLE
"make test" should fail if any code is inconsistent with "go fmt"

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#3462]
A few times now non-canonical code has slipped in for one reason or another.

In order to reduce the need for followup commits, having the ``make test`` target include a check that all files are canonically formatted would allow contributors and reviewers to catch these things earlier.

This idea was originally discussed in #3439.

**Comment by stack72** [comment]
@apparentlymart should this check be something that the developers themselves run or should it be something that travis runs as part of a build? (or both?)

Right now, travis runs these scripts:
```
  - go test ./...
  - make vet
```

another could easily be for go fmt

Thoughts?

**Comment by apparentlymart** [comment]
I think both would be ideal, so that people aren't surprised when their apparently-working changes fail once they are pushed up and run in Travis. But running it as a separate step in Travis would certainly be a good start, just like how we run `go vet` today.

**Comment by jen20** [comment]
This is now done - https://github.com/hashicorp/terraform/pull/4373.
