### ISSUE TITLE
Migrate easily from count to for-each

### ISSUE THREAD

**Issue by benniehanas** [hashicorp/terraform#34633]
### Terraform Version

```shell
v13
```

### Use Cases

Migrate easily from count to for-each

### Attempted Solutions

Hello we are using remote buildagents (Teamcity) which has the terraform.exe files and which makes the calls to AWS CLI. We only merge in Git from our work laptops. I have an issue that we decom some Accounts that were tied to tgw using RAM shares to share TGW in our core account to remote accounts for use in TGW attachments. I the RAM share currently uses a list for accounts in each region where each region is a var of accounts in that region we would like to share our TGW for each region outbound to them. Well when removing an entry from the list, it messes with the index of the resource that was build and tries to redo them. This will cause manualy RAM acceptance on the remote end for EACH account being shared. So an outage. How do I migrate this to foreach while migrating the index from integer to tag value?

I don't have the state file locally, but can download it and switch the keys for each?

Current:
"index_key": 20,
          "schema_version": 0,
          "attributes": {
            "id": <XYZ>

I can change index_key value to whatever the tag in the map is that I create?

### Proposal

A new type of *.tf file that is input for the very purpose of changing state, as I have no command-line way to do this

### References

#22375

**Comment by benniehanas** [comment]
there's a string of these that would incur the outage:

# aws_ram_principal_association.acct_assoc_east_2[19] must be replaced
...
Then further down:

# aws_ram_principal_association.acct_assoc_east_2[21] will be destroyed

These concern the same Account ID in the same Region...

All I did was remove the decom 2 Accounts from the var:
principal_east_2 = ["Account ID1", "Account ID2", "...", "Account ID22"]

**Comment by crw** [comment]
Thanks for this feature request! If you are viewing this issue and would like to indicate your interest, please use the 👍 reaction on the issue description to upvote this issue. We also welcome additional use case descriptions. Thanks again!

**Comment by crw** [comment]
Howdy @benniehanas, as this appears to be a usage question about Terraform, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers. 

I will leave this open for a time to see if a core maintainer wants to re-word this as an enhancement request. Thanks!

**Comment by jbardin** [comment]
Looks like this was already picked up in the forums.
