### ISSUE TITLE
Set state lock expiration as an option apply command

### ISSUE THREAD

**Issue by oshiro3** [hashicorp/terraform#34654]
### Terraform Version

```shell
1.7.0
```

### Use Cases

I want to set the lock expiration time in advance when apply is executed.
I understand that it is very important for terraform to safely remove the lock.
However, it is not uncommon for software that is supposed to gracefully shutdown to fail to do so.
For example, there are many factors that can interfere with graceful shutdown in terraform, such as OOM Killer, hardware crashes, or the specification of the Management CI service.
And in such cases, especially in a production environment, it is not desirable to manually run the terraform command to release the lock.
The next time terraform (plan | apply) is executed, wouldn't it be a sterile outcome to have this execution process stopped by a lock left in the past that no one needs?

### Attempted Solutions

Search for IDs from failed processes and unlock them with `terraform force-unlock`.
However, in many cases terraform execution is highly automated, and it is likely that you will have to log in to the CI server or request access rights to remote state storage in order to manually unlock terraform.

### Proposal

An example would be `terraform apply -lock-expired=24h` where it would be nice to be able to set the duration optionally, but a timestamp might also work.

I couldn't find this from the issue tracker when I looked for it, but if this is an issue that has been discussed, please introduce it.

**Comment by jbardin** [comment]
Hi @oshiro3,

The interface for state locks in Terraform doesn't currently allow for any expiration, and the implementation is dependent on the individual backend. Not all backends may have the ability to offer lock expiration, and some may already have it builtin by monitoring an active connection. 

You can see existing requests for individual storage services like [azure](#33651) and [s3](#21671), which may be able to implement this feature. If you are using a different backend that could support this, you may want to file an enhancement request for that specifically.
