### ISSUE TITLE
aws_db_instance engine_version should be optional, not required

### ISSUE THREAD

**Issue by ubergeek42** [hashicorp/terraform#3465]
According to the AWS docs, `engine_version` is not a required attribute.
http://docs.aws.amazon.com/AmazonRDS/latest/CommandLineReference/CLIReference-cmd-CreateDBInstance.html

Seems to be this line in the code that's forcing it to be required
https://github.com/hashicorp/terraform/blob/295c9245bbd45f00864b542e4b7abf0ad4cce766/builtin/providers/aws/resource_aws_db_instance.go#L57

**Comment by stack72** [comment]
Just opened PR #3744  that should solve this.
