### ISSUE TITLE
Documented TF_IGNORE environment variable appears to no longer exist

### ISSUE THREAD

**Issue by nwalters512** [hashicorp/terraform#34712]
### Terraform Version

```shell
Terraform v1.7.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.36.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

### Affected Pages

https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_ignore

### What is the docs issue?

The page documents a `TF_IGNORE` environment variable. However, from what I can tell, support for this environment variable was removed in https://github.com/hashicorp/go-slug/pull/42.

### Proposal

Remove documentation of something that doesn't exist. However, this was genuinely a useful feature, and was a reasonable bandaid over the lack of the feature described in https://github.com/hashicorp/terraform/issues/27654. If there's a recommended replacement for `TF_IGNORE`, I'd love for that to be documented.

### References

- https://github.com/hashicorp/terraform/issues/27043
- https://github.com/hashicorp/terraform/issues/27654

**Comment by crw** [comment]
Thanks for this! We looked at the original issue in triage and think it may have something to do with Cloud (versus Core Terraform), but this is correct that within Core, there env var functionally does not exist.
