### ISSUE TITLE
Allow destroy-time provisioners to access variables

### ISSUE THREAD

**Issue by chugh97** [hashicorp/terraform#34748]
### Terraform Version

```shell
Destroy-time provisioners and their connection configurations may only
│ reference attributes of the related resource, via 'self', 'count.index', or
│ 'each.key'.
│ 
│ References to other resources during the destroy phase can cause dependency
│ cycles and interact poorly with create_before_destroy.
╵
```

### Use Cases

When destroying resources in terraform using a provisioner we have to declare variables under a triggers section which can be referenced using self.triggers.variable_name which are inconsistent when we create the resources. When creation of resources, the create provisioner can access the variables using ${var.variable_name} but when destroying we need to self. Also the above error message is not very clear. An example would help

### Attempted Solutions

self.triggers.variable_name

### Proposal

Have a destroy variable block

**Comment by jbardin** [comment]
Duplicate of #23679
