### ISSUE TITLE
How to you create load balanced endpoint in Azure V1 Virtual machine

### ISSUE THREAD

**Issue by chevalpartners** [hashicorp/terraform#3474]
Hi:

Azure service management API, PowerShell, CLI support creating internal and external load balanced endpoints. 

You can see an example here:
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-set-up-endpoints/

Is it possible to create a load balanced end point with Terraform for a virutal machine?

Thanks

**Comment by mitchellh** [comment]
I'm sorry we never responded. It has been a very long time, and we now support LBs for Azure.
