### ISSUE TITLE
Specifying Encryption for aws_s3_bucket_object

### ISSUE THREAD

**Issue by st-isidore-de-seville** [hashicorp/terraform#3475]
Is there a way that encryption can be specified for aws_s3_bucket_object?

**Comment by radeksimko** [comment]
Hi @st-isidore-de-seville 
this is now possible, you can either use the default AES256 by just specifying `encrypt=1` and you can optionally also use your KMS key (via `kms_key_id`), which is a feature that has been introduced in https://github.com/hashicorp/terraform/pull/2903 and will be available in the next release (isn't part of any release yet).

All this was also documented in a new section of the terraform website which should become available along with the next release, until then check the source code:
https://github.com/hashicorp/terraform/blob/master/website/source/docs/state/remote/s3.html.md

Feel free to open a new issue or PR if you discover any bugs or misbehaviours.

**Comment by radeksimko** [comment]
Sorry I misread your original issue, this is not quite supported yet for the `aws_s3_bucket_object` itself.
Keeping open.

**Comment by radeksimko** [comment]
KMS encryption support was merged as part of https://github.com/hashicorp/terraform/pull/5453 and will be in the next release.

I'm keeping this open though, since encryption with customer key isn't supported yet.

**Comment by jason-riddle** [comment]
So this lets you specify a KMS encryption key, but what about the AWS managed "AES256" option?

**Comment by geekifier** [comment]
@jason-riddle That is managed per-object, and not on the bucket level. Every put to an S3 bucket needs to specify for server-side encryption to be used. You can enforce this using a bucket policy (see http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html).

I don't believe it's feasible for TerraForm to have a simple on/off option for the aws_s3_bucket resource to put that policy in place.

**Comment by conorgil** [comment]
@st-isidore-de-seville According to the [aws_s3_bucket_object](https://www.terraform.io/docs/providers/aws/r/s3_bucket_object.html#server_side_encryption) docs, this capability is now supported. If you agree, perhaps you can close this issue?

**Comment by radeksimko** [comment]
@conorgil Thanks for the ping, but we don't actually support SSE via customer provided keys yet. The related attributes seem to be `SSECustomerAlgorithm`, `SSECustomerKey` and `SSECustomerKeyMD5` which we don't use anywhere (yet).

Contributions are welcomed.

**Comment by conorgil** [comment]
@radeksimko Ah, ok. The initial issue description didn't clarify what was included feature wise and I didn't read your comment carefully until just now. Thanks for clarifying.

I am just learning go, so it might be a while before I can contribute on that level, but I'll take a crack at it down the road once I'm up to speed if no one gets to it first.
