### ISSUE TITLE
Specifying Directory Uploads using aws_s3_bucket_object

### ISSUE THREAD

**Issue by st-isidore-de-seville** [hashicorp/terraform#3476]
Is there a way whole directories can be uploaded using aws_s3_bucket_object?

**Comment by apparentlymart** [comment]
That is not currently possible using Terraform alone, but you can use [terraform-s3-dir](https://github.com/saymedia/terraform-s3-dir) to automatically generate a Terraform config file to upload a directory of files.

I wrote up a proposal for how Terraform might address this itself in #3310, but that's still in the exploratory stages.
