### ISSUE TITLE
no schema available for aws_config_resource.conf

### ISSUE THREAD

**Issue by Bipin-dbdigital-in** [hashicorp/terraform#34774]
### Terraform Version

```shell
Terraform v1.7.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.39.1
```

### Terraform Configuration Files

```resource "aws_glue_catalog_database" "mixpanel_dvb" {
  name = "mixpanel_dvb"
  location_uri = "null"
  description = "null"
}
```

### Debug Output

Error: no schema available for aws_config_resource.conf to validate for self-references; this is a bug in Terraform and should be reported

### Expected Behavior

Error: no schema available for aws_config_resource.conf to validate for self-references; this is a bug in Terraform and should be reported

### Actual Behavior

Error: no schema available for aws_config_resource.conf to validate for self-references; this is a bug in Terraform and should be reported

### Steps to Reproduce

terraform import aws_glue_catalog_database.mixpanal_dvb $account_id:$databasename

### Additional Context

terraform import aws_glue_catalog_database.mixpanal_dvb $account_id:$databasename

### References

aws_glue_catalog_database.mixpanel_dvb: Importing from ID "333*******:mixpanel_dvb"...
aws_glue_catalog_database.mixpanel_dvb: Import prepared!
  Prepared aws_glue_catalog_database for import
aws_glue_catalog_database.mixpanel_dvb: Refreshing state... [id=333******:mixpanel_dvb]
╷
│ Error: no schema available for aws_config_resource.conf to validate for self-references; this is a bug in Terraform and should be reported

**Comment by jbardin** [comment]
Hi @Bipin-dbdigital-in,

Thanks for filing the issue. The configuration shown appear to be incomplete, do you have a complete example we can reproduce the issue with? I'm also not sure what an `aws_config_resource` resource is, as that provider doesn't have any resources by that name. How did you end up with that resource type in your Terraform configuration?

**Comment by jbardin** [comment]
Thanks @Bipin-dbdigital-in. There must be some trace of the `aws_config_resource.conf` in you configuration or state. I don't know where it came from, because I don't think there was ever a resource called that, and I also can't replicate the exact error you are seeing with a nonexistent resource. Can you run a normal `terraform plan` and show the output? If you have somehow manually added this resource to your state, you will need to remove it in order to proceed.
