### ISSUE TITLE
Terraform reads context from terraform.tfvars even if it is passed another config as var-file

### ISSUE THREAD

**Issue by avazula** [hashicorp/terraform#34845]
### Terraform Version

```shell
1.7.1
```

### Terraform Configuration Files

```terraform
# variables.tf
variable "region" {
    description = "Region in which to deploy resources"
    type = string
    default = "eu-west-1"
}
```

```terraform 
# terraform.tfvars (used as a example file)
region="eu-west-2"
```

```terraform
# local.terraform.tfvars (file used to actually deploy)
# no definition of region
```

```terraform
# provider.tf
provider "aws" {
  alias   = "target"
  region  = var.region
}
```

### Debug Output

Terraform deploys everything, except that instead of using the default value from `variables.tf` from region, it uses the value defined in `terraform.tfvars` when **I do not call this file** (see steps to reproduce).

### Expected Behavior

Terraform deploys everything using the value defined as default in `variables.tf`.

### Actual Behavior

Terraform deploys everything using the value defined in `terraform.tfvars`.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -out infra.out -var-file=local.terraform.tfvars`

### Additional Context

The behaviour is fixed if I rename `terraform.tfvars` to `example.terraform.tfvars`

**Comment by avazula** [comment]
My colleagues tell me that Terraform is aware of the folder context and will read any `terraform.tfvars` file that's in there, as [stated in the docs](https://developer.hashicorp.com/terraform/language/values/variables#variable-definition-precedence). Seems that it is not a bug then. 

I'm a bit surprised that it's the expected behaviour though, because I specifically pass it a variable file. Arguably, the definition is null from the variables file, but I'd expect that it'd take the default value then... So though expected, is it desirable behaviour?

**Comment by jbardin** [comment]
Hi @avazula,

Yes, the order of precedence is defined in the documentation you linked. For your use case you will need to use a filename which does not match one of the files which is automatically loaded.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
