### ISSUE TITLE
Can not destroy the cluster if SNS topic is not confirmed yet

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform#34868]
### Terraform Version

```shell
terraform version
Terraform v1.7.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.41.0
+ provider registry.terraform.io/hashicorp/external v2.3.3
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
```

### Terraform Configuration Files

```terraform
data "aws_iam_policy_document" "notify-devops" {
  version   = "2012-10-17"
  policy_id = "__default_policy_ID"
  statement {
    sid = "__default_statement_ID"
    actions = [
      "SNS:GetTopicAttributes",
      "SNS:SetTopicAttributes",
      "SNS:AddPermission",
      "SNS:RemovePermission",
      "SNS:DeleteTopic",
      "SNS:Subscribe",
      "SNS:ListSubscriptionsByTopic",
      "SNS:Publish",
      "SNS:Receive"
    ]
    effect    = "Allow"
    resources = [aws_sns_topic.notify-devops.arn]

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceOwner"

      values = [
        "${data.aws_caller_identity.current.account_id}"
      ]
    }

    principals {
      identifiers = ["*"]
      type        = "AWS"
    }
  }
}

...
resource "aws_sns_topic" "notify-devops" {
  name = "${var.project_name}-notify-devops"
}

resource "aws_sns_topic_policy" "notify-devops" {
  arn    = aws_sns_topic.notify-devops.arn
  policy = data.aws_iam_policy_document.notify-devops.json
}

resource "aws_sns_topic_subscription" "notify-devops" {
  topic_arn                       = aws_sns_topic.notify-devops.arn
  protocol                        = "email"
  endpoint                        = "xxxx@xxxx"
  confirmation_timeout_in_minutes = 1
  endpoint_auto_confirms          = false
}

```

### Debug Output

╷
│ Error: reading SNS Topic (arn:aws:sns:us-east-2:315400321086:stg-enterprise-notify-devops): operation error SNS: GetTopicAttributes, https response error StatusCode: 400, RequestID: b8d7e0c7-8c1b-567f-8944-beb37666cb92, InvalidParameter: Invalid parameter: TopicArn
│
│   with module.private-cloud.aws_sns_topic.notify-devops,
│   on modules/private-cloud/sns.tf line 176, in resource "aws_sns_topic" "notify-devops":
│  176: resource "aws_sns_topic" "notify-devops" {
│
╵

### Expected Behavior

If SNS topic does not exists, then terraform should just remove resource from the state instead of failing.

![image](https://github.com/hashicorp/terraform/assets/139780495/ed17cb20-a6ab-4fa4-9f18-6376e48eb6f7)

### Actual Behavior

I can not destroy cluster.

### Steps to Reproduce

In my case some error happened on other step. I suppose SNS topic already was deleted. And when I rerun `destroy` again the terraform failed when tried to remove SNS topic second time.

So steps to reproduce
1. Create SNS topic
2. Create other resource
3. Try to destroy cluster, but change it in a way the terraform fail after deleted SNS topic, eg. SNS topic is deleted but fail on other resource.
4. Fix the problem, try to destroy cluster again to remove resources
5. At this point terraform will try to delete SNS topic second time and fail. And will not try to delete resource which was created on step (2), because of earlier error.

**Comment by EugenKon** [comment]
To workaround this problem I removed this resource from the state:
```
terraform state rm module.private-cloud.aws_sns_topic.notify-devops
terraform state rm module.private-cloud.aws_sns_topic_policy.notify-devops
```

But got then:
```
╷
│ Error: deleting SES Identity Notification Topic (enterprise.****|Complaint): InvalidParameterValue: Identity enterprise.***** is invalid. Must be a verified email address or domain.
│ 	status code: 400, request id: 8c18cb57-6ec8-4e0b-8a0a-****
│
│
╵
```

So I removed also:
```
terraform state rm  module.private-cloud.aws_ses_identity_notification_topic.private-cloud-bounces
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
