### ISSUE TITLE
Terraform Registry cannot get the latest provider verison documentation

### ISSUE THREAD

**Issue by notone0010** [hashicorp/terraform#34864]
### Terraform Version

```shell
Terraform v1.4.6
on darwin_arm64
```

### What is the docs issue?

When I published a new provider version on terraform registry, but [the latest version](https://registry.terraform.io/providers/kingsoftcloud/ksyun/latest) is still the previous version.
The latest version on **Terraform Resgistry** is v1.15.1, but the github repo released the latest version is v1.15.2

### GIthub released version
<img width="608" alt="image" src="https://github.com/hashicorp/terraform/assets/42347556/a8625696-7c4e-4a22-8b94-aa3ed331c387">

### Resgistry version
<img width="747" alt="image" src="https://github.com/hashicorp/terraform/assets/42347556/87b7954a-db52-4f28-b9ec-08d585d77dd9">

**Comment by apparentlymart** [comment]
Hi @notone0010,

Please email [terraform-registry@hashicorp.com](mailto:terraform-registry@hashicorp.com) to discuss problems with publishing providers in Terraform Registry. The Terraform Registry team does not monitor issues in this repository, and [they document that email address as the registry support channel](https://developer.hashicorp.com/terraform/registry/providers/publishing#support).

Thanks!
