### ISSUE TITLE
aws_elb listener ssl_certificate_id unknown resource

### ISSUE THREAD

**Issue by nwalke** [hashicorp/terraform#3486]
I'm trying to define an AWS ELB like so:
```
resource "aws_elb" "app" {
	name = "${var.client}-app"
	availability_zones = ["${var.aws_region}a", "${var.aws_region}b", "${var.aws_region}c"]

	listener {
		instance_port = 80
		instance_protocol = "http"
		lb_port = 443
		lb_protocol = "https"
		ssl_certificate_id = "${aws_iam_server_certificate.app.arn}"
	}

	health_check {
		healthy_threshold = 3
		unhealthy_threshold = 3
		timeout = 15
		target = "HTTP:443/health_check"
		interval = 30
	}

	cross_zone_load_balancing = true
	idle_timeout = 60
	connection_draining = true
	connection_draining_timeout = 60

	tags {
		Name = "${var.client}-app"
	}
}
```

In another `.tf` file I have this:
```
resource "aws_iam_server_certificate" "app" {
	name = "${var.client}_app_cert"
	certificate_body = "${file("wildcard-cert.pem")}"
	certificate_chain = "${file("wildcard-chain.pem")}"
	private_key = "${file("wildcard-key.pem")}"
}
```

When I run `terraform plan --module-depth 2` (both of these are under separate modules), I'm getting this: 
```
Errors:

  * 1 error(s) occurred:

* module load-balancing.root: 1 error(s) occurred:

* resource 'aws_elb.app' config: unknown resource 'aws_iam_server_certificate.app' referenced in variable aws_iam_server_certificate.app.arn
```

Anybody seen this before?  I'm running 0.6.3.

**Comment by phinze** [comment]
Hi @nwalke - thanks for the detailed report.

Modules are designed to be black boxes with explicitly declared inputs and outputs, so you can't directly reference resources between modules. What you'll need to to is declare an [output](http://terraform.io/docs/configuration/outputs.html) in your server certificate module, and a [variable](http://terraform.io/docs/configuration/variables.html) in your load balancing module to accept the input. You then wire them together as you invoke the modules at the top level.

Like this:

```tf
# load-balancing/main.tf
variable "ssl_cert_arn" {}

resource "aws_elb" "app" {
    # ...
    listener {
        # ...
        ssl_certificate_id = "${var.ssl_cert_arn}"
    }
    # ...
}
```

```tf
# cert/main.tf
resource "aws_iam_server_certificate" "app" {
    # ...
}

output "arn" { value = "${aws_iam_server_certificate.app.arn}" }
```

```tf
# main.tf
module "cert" {
  source = "./cert"
}

module "load-balancing" {
  source = "./load-balancing"
  ssl_cert_arn = "${module.cert.arn}"
}
```

Let me know if this gets you pointed in the right direction! :+1:

**Comment by nwalke** [comment]
Definitely helps.  Sorry for the issue spam. I've been going through our set up and trying to get everything in to nice packaged up modules, so we hadn't seen this before.  Thanks for the help!
