### ISSUE TITLE
Azure Plugin crashing

### ISSUE THREAD

**Issue by surendarkaniops** [hashicorp/terraform#34874]
### Terraform Version

```shell
1.6.5
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

Stack trace from the terraform-provider-azurerm_v3.90.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6875771]

goroutine 131 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/eventhub.resourceEventHubNamespaceCustomerManagedKeyRead(0xc004082300, {0x7d947a0?, 0xc001cc2900?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/eventhub/eventhub_namespace_customer_managed_key_resource.go:210 +0x491
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x9592880?, {0x9592880?, 0xc003984fc0?}, 0xd?, {0x7d947a0?, 0xc001cc2900?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000bbe7e0, {0x9592880, 0xc003984fc0}, 0xc001ab2750, {0x7d947a0, 0xc001cc2900})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0007d61f8, {0x9592880?, 0xc003984ed0?}, 0xc0041dc540)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:649 +0x48a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001553c20, {0x9592880?, 0xc0039846f0?}, 0xc0016f6f00)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:789 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x89360e0?, 0xc001553c20}, {0x9592880, 0xc0039846f0}, 0xc0016f80e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002b61e0, {0x95b8fe0, 0xc001a941a0}, 0xc0039a0240, 0xc001a721b0, 0xf12ee28, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002b61e0, {0x95b8fe0, 0xc001a941a0}, 0xc0039a0240, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 24
	google.golang.org/grpc@v1.58.3/server.go:997 +0x145

Error: The terraform-provider-azurerm_v3.90.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

should go through plan output 

### Actual Behavior

Plugin crashing with the error message

### Steps to Reproduce

terraform init 
terraform apply

### Additional Context

We are using the latest version az cli and az provider

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
