### ISSUE TITLE
The usage of environment variable TERRAFORM_CONFIG is not documented anywhere

### ISSUE THREAD

**Issue by arthfl** [hashicorp/terraform#34898]
### Terraform Version

```shell
Terraform v1.7.5
on linux_amd64
```

### What is the docs issue?

This https://github.com/hashicorp/terraform/blob/0fe733acf03768765395a4b510d90e8688c9fe35/internal/command/cliconfig/cliconfig.go#L456 defines a fallback to `TERRAFORM_CONFIG` if `TF_CLI_CONFIG_FILE` is empty. But this is not reflected anywhere in the documentation about `TF_CLI_CONFIG_FILE` https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_cli_config_file

### Proposal

Add the existence of this fallback to the documentation.

### References

* https://github.com/hashicorp/terraform/issues/15849
* https://github.com/hashicorp/terraform/pull/20834

**Comment by crw** [comment]
The name was changed and `TERRAFORM_CONFIG` is considered deprecated. Please see https://github.com/hashicorp/terraform/pull/20834

**Comment by arthfl** [comment]
It's nice that this is deprecated. But since this isn't mentioned anywhere in the documentation it causes very weird and annoying issues if you happen to have your Terraform deployment configuration handed over via a variable called `TERRAFORM_CONFIG` in your automation.
Which is exactly how i stumbled over this. And i only found it because i thought "oh no, they didnt...." and then searched through the source after i couldn't find any mention of this in the documentation.

**Comment by crw** [comment]
Fair point. I've created a PR: https://github.com/hashicorp/terraform/pull/34918.
