### ISSUE TITLE
Rds upgrade 

### ISSUE THREAD

**Issue by ravi334** [hashicorp/terraform#34919]
### Terraform Version

```shell
400 error
```

### What is the docs issue?

After using the rds upgrade module
I am not getting version get updated, it is showing resources exist already

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
