### ISSUE TITLE
aws_securitylake_subscriber supports only one source

### ISSUE THREAD

**Issue by kclinden** [hashicorp/terraform#34927]
### Terraform Version

```shell
Terraform v1.7.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.43.0
```

### Terraform Configuration Files

```terraform
#Subscriber
resource "aws_securitylake_subscriber" "foo" {
  subscriber_name        = "foo"
  access_type            = "S3"
  subscriber_description = "Allow foo to access data"

  source {
    aws_log_source_resource {
      source_name    = "SH_FINDINGS"
      source_version = "2.0"
    }
    aws_log_source_resource {
       source_name    = "ROUTE53"
       source_version = "2.0"
    }
  }
  subscriber_identity {
    external_id = "foo"
    principal   = "000123456789"
  }
}

```

### Debug Output

│ Error: Invalid Attribute Value
│ 
│   with aws_securitylake_subscriber.cribl,
│   on main.tf line 88, in resource "aws_securitylake_subscriber" "foo":
│   88:   source {
│ 
│ Attribute source[0].aws_log_source_resource list must contain at most 1 elements, got: 2

### Expected Behavior

Sources should take an array of LogSourceResource objects.
https://docs.aws.amazon.com/security-lake/latest/APIReference/API_CreateSubscriber.html

### Actual Behavior

provider throws error.

### Steps to Reproduce

terraform init
terraform plan

### Additional Context

Based on the API it looks like sources should be an array of objects. I also tried multiple source blocks but got the same result.

```terraform
sources = [
  aws_log_source_resource {},
  aws_log_source_resource {}
]
```

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
