### ISSUE TITLE
Add security_lake_organization_configuration

### ISSUE THREAD

**Issue by kclinden** [hashicorp/terraform#34928]
### Terraform Version

```shell
Terraform v1.7.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.43.0
```

### Use Cases

When using Security Lake with an organization a user will want to be able to configure an organization configuration to centrally manage sources.

https://docs.aws.amazon.com/security-lake/latest/APIReference/API_CreateDataLakeOrganizationConfiguration.html

### Attempted Solutions

Without this you would need to hardcode account ids.

### Proposal

create new resource for security_lake_organization_configuration to manage config for member accounts using api CreateDataLakeOrganizationConfiguration

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
