### ISSUE TITLE
aws_db_instance final_snapshot_identifier flag to pass tags from source RDS

### ISSUE THREAD

**Issue by geek876** [hashicorp/terraform#3492]
Currently the RDS snapshot taken via the final_snaphot_identifier parameter seems to NOT pass the tags from source RDS. Perhaps there should be a flag to control the tag being passed/not-passed ?

**Comment by catsby** [comment]
Thanks @geek876 – I opened https://github.com/hashicorp/terraform/pull/3529 to address this

**Comment by catsby** [comment]
#3529 has been merged, thanks again :smile:
