### ISSUE TITLE
azurerm_sql_server does not have minimalTlsVersion

### ISSUE THREAD

**Issue by HaruY96** [hashicorp/terraform#34948]
### Terraform Version

```shell
for all terraform version
```

### Use Cases

In Azure Portal or ARM template, minimalTlsVersion is a default parameter with default 1.2 while creating Azure SQL Server. But this property is not included in the Terraform azurerm_sql_server module when create this resource.

### Attempted Solutions

N/A

### Proposal

It will be better if Terraform module can align the same behavior as Azure Platform. Then many other resources may work smoothly, for example, Azure Policy.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server.html

**Comment by liamcervante** [comment]
Hi @HaruY96, I think this enhancement request is better raised within the `azurerm` provider repository directly: https://github.com/hashicorp/terraform-provider-azurerm/issues

Terraform and the Terraform providers are managed in separate repositories and this is something that would be fixed directly by the provider team.

I'm going to close the request here, but I encourage to open a similar request within the provider specific repository.

Thanks!
