### ISSUE TITLE
AWS Account Factory for Terraform RAM Resource Share issues

### ISSUE THREAD

**Issue by jordan-k-gilead** [hashicorp/terraform#34953]
### Terraform Version

```shell
1.3
```

### Terraform Configuration Files

```
terraform {
  required_version = "~> 1.3"

  # AWS provider version pin to 5.30.0 for CORE-340
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 5.30.0"
    }
  }
}
```

### Debug Output

"From the log on the account *xxxxxxxx.
1. GetResourceShareInvitations at 2024-02-02T15:15:06.000Z
2. Another GetResourceShareInvitations at 2024-02-02T15:15:06.000Z
3. Then GetResourceShares at 2024-02-02T15:15:08.000Z encountered "UnknownResourceException".
4. Then AcceptResourceShareInvitation at 2024-02-02T15:15:08.000Z
5. GetResourceShares get successful since 2024-02-02T16:47:28.000Z with exactly the same request parameter as #3.
"requestParameters": {
"resourceShareArns": [
"arn:aws:ram:us-west-2:xxxxxxx:resource-share/xxxxxxxxxxxxxxxxxxxxx"
],
"resourceOwner": "OTHER-ACCOUNTS"
},"

### Expected Behavior

Account Request via AFT is successfully provisioned

### Actual Behavior

Our customer is using AWS Account Factory for Terraform and a few account requests are failing with the following error:

"Error: reading RAM Resource Share (arn:aws:ram:us-west-2:xxxxxxxxxxxx:resource-share/xxxxxxxxxxxxxxxxxxxxx): couldn't find resource

with aws_ram_resource_share_accepter.tgw_vpc_attach[0],

on [vpc_connected_baseline.tf](https://urldefense.com/v3/__http://vpc_connected_baseline.tf__;!!Dq7g1IpY!g_LqDhnptzMlQHX0s8k7Hl-8ceUOhto9x9ngGAof5x_ZNKFVRD_F-kT32cAgtik4H93TBKD_RMG2yqpP9Do6tzM$) line 34, in resource "aws_ram_resource_share_accepter" "tgw_vpc_attach":

34: resource "aws_ram_resource_share_accepter" "tgw_vpc_attach" {"

### Steps to Reproduce

1. Account request is submitted by merging the TF file into the account-request repo
2. The ci/cd pipeline kicks off to create the account
3. This will run a series of checks, as well as terraform init, terraform plan, terraform apply

### Additional Context

This is related to a previously determined issue with timing in processing RAM shares, which requires a code fix to stabilize, or manual TF state manipulations as mitigation (it is possible for the failure to repeat in the future if certain changes are made).

Right now the current workaround is to run the TF init and plan for the pipeline, let it fail, then untaint the resources and run the pipeline again. This was not happening before, but as we scale the number of RAM resource shares it is becoming more frequent. We have already tried adding gaps or “time_sleeps” inbetween the resource creations.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
