### ISSUE TITLE
Define provider in a submodule

### ISSUE THREAD

**Issue by islishude** [hashicorp/terraform#34956]
### Terraform Version

```shell
Terraform v1.7.5
on darwin_arm64
```

### Use Cases

I have a application on aws eks.

It deployed on different region, and each replica has the same resources.

It includes vpc, eks cluster, helm charts.

the file structure like following

```
├── README.md
├── eu-central-1.tf
├── main.tf
├── modules
│   └── replica
│       ├── alb.tf
│       ├── eks.tf
│       ├── https.tf
│       ├── irsa.tf
│       ├── output.tf
│       ├── security_group.tf
│       ├── variables.tf
│       ├── versions.tf
│       ├── vpc.tf
│       └── waf.tf
├── outtput.tf
├── us-east-1.tf
├── variable.tf
└── versions.tf
```

Helm and k8s provider depends on eks.

I can only define the helm and k8s provider in the main module

```terraform
locals {
  euc1_region = "eu-central-1"
}

provider "aws" {
  alias  = "euc1"
  region = local.euc1_region
}

provider "helm" {
  alias = "euc1"

  kubernetes {
    host                   = module.euc1.eks_cluster_endpoint
    cluster_ca_certificate = base64decode(module.euc1.eks_cluster_certificate_authority_data)
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      args        = ["eks", "get-token", "--region", local.euc1_region, "--cluster-name", var.svc_name]
      command     = "aws"
    }
  }
}

provider "kubernetes" {
  alias = "euc1"

  host                   = module.euc1.eks_cluster_endpoint
  cluster_ca_certificate = base64decode(module.euc1.eks_cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--region", local.euc1_region, "--cluster-name", var.svc_name]
    command     = "aws"
  }
}

module "euc1" {
  source = "./modules/replica"

  providers = {
    aws        = aws.euc1
    helm       = helm.euc1
    kubernetes = kubernetes.euc1
  }
}
```

that looks good and works.

but I can't remove the `euc1` module.

If I do this, the terraform will report an error.

```
│ Error: Reference to undeclared module
│ 
│   on eu-central-1.tf line 14, in provider "helm":
│   14:     host                   = module.euc1.eks_cluster_endpoint
│ 
│ No module call named "euc1" is declared in the root module.
╵
╷
│ Error: Reference to undeclared module
│ 
│   on eu-central-1.tf line 15, in provider "helm":
│   15:     cluster_ca_certificate = base64decode(module.euc1.eks_cluster_certificate_authority_data)
│ 
│ No module call named "euc1" is declared in the root module.
╵
╷
│ Error: Reference to undeclared module
│ 
│   on eu-central-1.tf line 27, in provider "kubernetes":
│   27:   host                   = module.euc1.eks_cluster_endpoint
│ 
│ No module call named "euc1" is declared in the root module.
╵
╷
│ Error: Reference to undeclared module
│ 
│   on eu-central-1.tf line 28, in provider "kubernetes":
│   28:   cluster_ca_certificate = base64decode(module.euc1.eks_cluster_certificate_authority_data)
│ 
│ No module call named "euc1" is declared in the root module.
```

and

```
╷
│ Error: Provider configuration not present
│ 
│ To work with module.euc1.kubernetes_namespace.deployment-namespace (orphan) its original provider configuration at provider["registry.terraform.io/hashicorp/kubernetes"].euc1 is required, but it has been removed. This occurs when a provider configuration is removed while objects created by
│ that provider still exist in the state. Re-add the provider configuration to destroy module.euc1.kubernetes_namespace.deployment-namespace (orphan), after which you can remove the provider configuration again.
```

### Attempted Solutions

I have no idea, but I'm willing to see the provider can be defined in a submodule

**Comment by Killpit** [comment]
I think etc_1 doesn't exist in Terraform. What I'd do is that I'd hardcode the region and not have any alias related to it. And according to the error message it's removed. I think you can remove it and work out an alternative solution, but it'd be good to have submodules and not having to write it many times again.

**Comment by jbardin** [comment]
Hi @islishude,

The reason that it's not recommended for providers to be located within a module, is to avoid this same situation when removing any module -- the provider must always outlive the resources it manages, so putting the provider within the module won't improve your result.

If you need to remove part of the infrastructure later, you would need to refactor the the module into multiple such that you can remove only the portion of the infrastructure you are interested in. Having a provider which depends on managed resources from another provider within the same configuration is not recommended, and will take multiple plan and apply steps to remove interdependent ports of the configuration.

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, if you have more questions better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
