### ISSUE TITLE
provider/aws: Troubles destroying large ASGs

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#3495]
https://github.com/hashicorp/terraform/pull/3485 attempted to fix `force_delete`, but @maratoid provided a test config that still yields errors.

Current status with his config is:
- we skip the Terraform-managed drain properly
- we specify ForceDelete on the API call
- AWS still seems to need to churn through terminations of all nodes before the ASG is deleted
- Terraform times out waiting for the ASG to show up as deleted
- The internet gateway also times out... still haven't figured out if that's related or not.

In order to fix, I think we need to:
- parameterize the timeout value for both ASGs and IGWs to allow users to crank that up
- potentially figure out the "not found" issue if it's a separate IGW bug

This is all a bit jargon-y, happy to clarify anything if someone else digs into this before I do.

**Comment by maratoid** [comment]
Hey guys. Just wondering if this is in any kind of a roadmap. We're still having to work around this in all sorts of clunky ways. 

Thanks.

**Comment by phinze** [comment]
Acknowledging that this is still an issue. Been kicking around a core-supported solution for this, let me braindump some notes on that:

Terraform needs support for per-resource user-configurable timeouts. These timeouts should apply to Create, Update, Destroy operations.

Sketch of one possible config (not super sold on it - there might be a nicer spot to drop this):

```tf
resource "aws_autoscaling_group" "foo" {
  # ...
  timeouts {
    create  = "30m"
    destroy = "30m"
    update  = "10m"
  }
}
```

Resource implementations would need to opt-in for support of these config values so that if a user specifies them on an unsupported resource, a validation error is returned.

**Comment by maratoid** [comment]
Any news :) ?

**Comment by maratoid** [comment]
ping
