### ISSUE TITLE
Not able to remove "assignment_review_settings" block in azuread_access_package_assignment_policy

### ISSUE THREAD

**Issue by kumar1708** [hashicorp/terraform#34978]
### Terraform Version

```shell
1.8.0
```

### Terraform Configuration Files

resource "azuread_access_package_assignment_policy" "cloud_ops_stakeholder" {
  access_package_id = azuread_access_package.cloud_ops_stakeholder.id
  display_name      = "cloud-ops-stakeholder-assignment-policy"
  description       = "cloud ops Stakeholder assignment policy"

  requestor_settings {
    scope_type        = "AllExistingDirectorySubjects"
    requests_accepted = true
  }

  approval_settings {
    approval_required = true

    approval_stage {
      approval_timeout_in_days = 14

      primary_approver {
        object_id    = data.azuread_group.cloud_ops_admins.object_id
        subject_type = "groupMembers"
      }
    }
  }

}

### Debug Output

AccessPackageAssignmentPolicyClient.BaseClient.Put(): unexpected status 400
with OData error: AccessReviewWrongDurationForRecurrenceType: The access
review duration entered does not work with the selected review frequency ''.
The duration should be between 1 and 0.
Releasing state lock. This may take a few moments...

### Expected Behavior

assignment_review_settings shoould be removed and access review should be disabled

### Actual Behavior

AccessPackageAssignmentPolicyClient.BaseClient.Put(): unexpected status 400
with OData error: AccessReviewWrongDurationForRecurrenceType: The access
review duration entered does not work with the selected review frequency ''.
The duration should be between 1 and 0.
Releasing state lock. This may take a few moments...

### Steps to Reproduce

Create access package policy using azuread_access_package_assignment_policy then remove assignment_review_settings in next PR

### Additional Context

I am trying to remove the complete assignment_review_settings block but I am getting an error message that says : AccessPackageAssignmentPolicyClient.BaseClient.Put(): unexpected status 400
with OData error: AccessReviewWrongDurationForRecurrenceType: The access
review duration entered does not work with the selected review frequency ''.
The duration should be between 1 and 0.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
