### ISSUE TITLE
aws_dynamodb_table arn attribute not present in apply run after creation

### ISSUE THREAD

**Issue by ubergeek42** [hashicorp/terraform#3497]
I am trying to create a dynamodb table, and then create an IAM instance policy granting access to that table. However, trying to access the arn value of an aws_dynamodb_table that was created during the same apply run results in the error:
```
* Resource 'aws_dynamodb_table.session_table' does not have attribute 'arn' for variable 'aws_dynamodb_table.session_table.arn'
```

Running `terraform apply` a second time without changing anything is successful though.

My terraform config looks something like this:
```terraform
resource "aws_dynamodb_table" "session_table" {
  name = "myprojectid-sessiontable"
  read_capacity   = "1"
  write_capacity  = "1"
  hash_key        = "id"
  attribute {
    name = "id"
    type = "S"
  }
}
resource "aws_iam_role" "webserver_iam_role" {
  name = "iam-web-role"
  path = "/"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": {
    "Effect": "Allow",
    "Principal": {"Service": "ec2.amazonaws.com"},
    "Action": "sts:AssumeRole"
  }
}
EOF
}

resource "aws_iam_role_policy" "webserver_iam_policy" {
  name = "DynamoDB-access"
  role = "${aws_iam_role.webserver_iam_role.id}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "stmt1",
      "Effect": "Allow",
      "Action": [
        "dynamodb:DeleteItem",
        "dynamodb:GetItem",
        "dynamodb:PutItem",
        "dynamodb:UpdateItem"
      ],
      "Resource": "${aws_dynamodb_table.session_table.arn}"
    }
  ]
}
```

My terraform version info:
```
$ terraform --version
Terraform v0.6.3
```

I'm not a go dev and don't have a go dev environment set up, but I would guess you'd need to add the line:
```go
d.Set("arn", *output.TableDescription.TableArn)
```
around here[1], only question is whether the arn is available immediately after creation or if it's only available once the table has been updated. In any case either the function or the docs need to be updated.

[1] - https://github.com/hashicorp/terraform/blob/3721b89010a4d8d39717fb3dd873480657fe29e2/builtin/providers/aws/resource_aws_dynamodb_table.go#L289

**Comment by catsby** [comment]
Fixed in https://github.com/hashicorp/terraform/pull/3500, thanks!
