### ISSUE TITLE
AWS Security Group shouldn't be destroyed and created when we update RDS configuration.

### ISSUE THREAD

**Issue by mynadx** [hashicorp/terraform#34975]
### Terraform Version

```shell
Terraform v1.0.0 on linux_amd64
aws provider version <=3.74.1
```

### Terraform Configuration Files

```terraform
...terraform config[图片]...
```
![rds_tf](https://github.com/hashicorp/terraform/assets/49837189/ec65dfce-d0e2-4e7b-b4da-e6982e4c4eaf)

### Debug Output

![sg_tf](https://github.com/hashicorp/terraform/assets/49837189/435b0853-948d-40e8-8ca2-c316d2cb7035)
![rds_plan](https://github.com/hashicorp/terraform/assets/49837189/a20305d0-210b-47ba-88c6-8dad221e5602)
![sg_plan](https://github.com/hashicorp/terraform/assets/49837189/c430cefb-c3de-48d3-a186-0ac1a1b5ac2d)

### Expected Behavior

our purpose is to update rds CA Cert. But when we try to plan and apply , I found that Security group related RDS action is destroy first then create next.

### Actual Behavior

Error: Error deleting security group: DependenctViolation: resource sg-02a6a9387b076c946(aws_security_group.rds_instance_sg_as4) has a dependent object
status code: 400

### Steps to Reproduce

1 terraform init
2 terraform plan -out shared.tfplan
3 terraform apply shared.tfplan.

### Additional Context

Hi team,
As the company security policy, I can not stick the code in the ticket.
Thanks for your understanding

**Comment by liamcervante** [comment]
Hi @mynadx, the reason the `aws_security_group` is being replaced is because it thinks the `vpc_id` attribute is changing. I think AWS security groups can simply be moved between VPCs but must be destroyed in the old one and created in the new one, hence the behaviour you are seeing here.

I see the VPC being loaded is from a data block, can you share the configuration for that VPC data block? That may be returning unknown during the plan which would lead to the security group assuming the VPC ID will change.

**Comment by mynadx** [comment]
Hi @liamcervante , Thanks for your answer. Sure, I am not expect that behaviour. So it means that I need to change the vpcid as a certain value, right? if it will solve the issue, I will have a try. Below are the data block.
```
data "aws_vpc" main{
   filter{
     name = "tag:Name"
     values = [var.vpc] 
  }
}

and variables
variable "vpc"{
  type = tsring
  default = "fr-vpc-1"
}
```

**Comment by liamcervante** [comment]
Hi @mynadx, thanks for this! 

Just to clarify, you are relying on the default value in the variable and not setting it to anything else dynamically? Can you check the ID of the `fr-vpc-1` VPC matches `vpc-041b2300a2415535f`?

Or if you change the data block to: 

```
data "aws_vpc" "main" {
  id = "vpc-041b2300a2415535f"
}
```

Does that stop the replacement, or change anything about the produced plan? This isn't a long term solution, I'm just trying to see if I can work out where the change in ID is coming from.

**Comment by jbardin** [comment]
One important thing to note here, you mention you are using Terraform `v1.0.0` which has many known issues which have since been fixed. The latest patch for that release is `v1.0.11`, however it may require upgrading to more recent releases to solve some types of issues.

**Comment by mynadx** [comment]
Hi @liamcervante , Thanks for your solution, You are right. I changed the aws_vpc block to set  matched id value. After view the plan result, it will not cause the aws_security_group destory and create action. 
```
data "aws_vpc" "main" {
  id = "vpc-041b2300a2415535f"
}
```

**Comment by mynadx** [comment]
Hi @jbardin , thans for your suggestion. Currently, Terraform v1.0.0 run a long time for our PROD system. We have noticed some problems about it. We will try to upgrade the version in the next release plan. Thanks a lot.

**Comment by liamcervante** [comment]
Thanks @mynadx, I will close this as working as intended. I suspect the data block was simply refreshing during the plan and returning unknown values, which meant the ID became unknown and caused the plan to suggest the replacement. Thanks again!
