### ISSUE TITLE
Error when creating google_service_networking_connection twice in same VPC

### ISSUE THREAD

**Issue by aseem-heg** [hashicorp/terraform#34991]
### Terraform Version

```shell
Terraform v1.8.0
on linux_amd64
```

### Terraform Configuration Files

```terraform
...terraform config...
```
.

### Debug Output

.

### Expected Behavior

Should create multiple `google_service_networking_connection` 

### Actual Behavior

Error

### Steps to Reproduce

```
resource "google_compute_global_address" "peering_range" {
  name          = "${var.vpc_network_name}-peering-range"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 24
  network       = google_compute_network.vpc_network.self_link
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network                 = google_compute_network.vpc_network.self_link
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.peering_range.name]
}

resource "google_project_service" "servicenetworking" {
  service            = "servicenetworking.googleapis.com"
  disable_on_destroy = false
}
resource "google_compute_global_address" "cb_peering_range" {
  name          = "cb-private-id-range"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  prefix_length = 16
  network       = google_compute_network.vpc_network.self_link
}

resource "google_service_networking_connection" "cb_private_vpc_connection" {
  network                 = google_compute_network.vpc_network.id
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.cb_peering_range.name]
  depends_on              = [
    google_project_service.servicenetworking,
    google_compute_global_address.cb_peering_range
  ]
}
```

### Additional Context

Creating 2 peering ranges results in error in terraform GCP 

Error: Error waiting for Create Service Networking Connection: Error code 9, message: Cannot modify allocated ranges in CreateConnection. Please use UpdateConnection.
│ Help Token: ARqICRN0ngda9gPgfJXasdasdx
│ 
│   with module.vpc_connector.google_service_networking_connection.cb_private_vpc_connection,
│   on ../modules/vpc_connector/main.tf line 155, in resource "google_service_networking_connection" "cb_private_vpc_connection":
│  155: resource "google_service_networking_connection" "cb_private_vpc_connection" {

**Comment by liamcervante** [comment]
Hi @aseem-heg, I think this is better filed within the [terraform-provider-google](https://github.com/hashicorp/terraform-provider-google) repository. The individual providers are managed in their own repositories, and the team there will be better placed to look into this for you.

I'll close this issue here, and you should reopen in the linked repository.

Thanks!
