### ISSUE TITLE
Variables in overriden modules cause "value for module.redacted.local.redacted was requested before it was provided" crash

### ISSUE THREAD

**Issue by david1437** [hashicorp/terraform#35019]
### Terraform Version

```shell
Terraform v1.8.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.45.0
+ provider registry.terraform.io/hashicorp/random v3.6.1
```

### Terraform Configuration Files

https://github.com/david1437/terraform-override-module-bug-report

### Debug Output

https://gist.github.com/david1437/233812625b369caecac02a21305181dc

### Expected Behavior

The module should be overridden and just return specified output

### Actual Behavior

terraform test crashes 

### Steps to Reproduce

terraform init
terraform test

**Comment by crw** [comment]
Thanks for filing this issue!
