### ISSUE TITLE
Terraform aws_dynamodb_table_item resource gets tainted in state file if range_key is missing

### ISSUE THREAD

**Issue by dancruciat** [hashicorp/terraform#35023]
### Terraform Version

```shell
1.5.6
```

### Terraform Configuration Files

resource "aws_dynamodb_table" "application_versions" {
  name         = "ApplicationVersions"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "applicationId"
  range_key    = "versionId"

  point_in_time_recovery {
    enabled = true
  }

  attribute {
    name = "applicationId"
    type = "S"
  }

  attribute {
    name = "versionId"
    type = "S"
  }

resource "aws_dynamodb_table_item" "application_version_record" {
  table_name = aws_dynamodb_table.application_versions.name
  hash_key   = aws_dynamodb_table.application_versions.hash_key
  #range_key  = aws_dynamodb_table.application_versions.range_key

   item = jsonencode({

    "applicationId" : {"S": "xxx"},
    "versionId"     : {"S": "1.0.0"},
    "status"        : {"S": "active"},
    "name"          : {"S": "1.0.0"}
})

### Debug Output

**PLAN**

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_dynamodb_table_item.application_version_record will be created
  + resource "aws_dynamodb_table_item" "application_version_record" {
      + hash_key   = "applicationId"
      + id         = (known after apply)
      + item       = jsonencode(
            {
              + applicationId = {
                  + S = "xxx"
                }
              + builtIn       = {
                  + BOOL = true
                }
              + name          = {
                  + S = "xxx"
                }
              + owner         = {
                  + S = "xxx"
                }
              + status        = {
                  + S = "active"
                }
              + type          = {
                  + N = "1"
                }
              + versionId     = {
                  + S = "1.0.0"
                }
            }
        )
      + table_name = "ApplicationVersions"
    }

**APPLY**
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_dynamodb_table_item.application_version_record will be created
  + resource "aws_dynamodb_table_item" "application_version_record" {
      + hash_key   = "applicationId"
      + id         = (known after apply)
      + item       = jsonencode(
            {
              + applicationId = {
                  + S = "xxx"
                }
              + builtIn       = {
                  + BOOL = true
                }
              + name          = {
                  + S = "xxx"
                }
              + owner         = {
                  + S = "xxx"
                }
              + status        = {
                  + S = "active"
                }
              + type          = {
                  + N = "1"
                }
              + versionId     = {
                  + S = "1.0.0"
                }
            }
        )
      + table_name = "ApplicationVersions"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_dynamodb_table_item.application_version_record: Creating...

╷
│ Error: reading DynamoDB Table Item (ApplicationVersions|applicationId||xxx|): ValidationException: The provided key element does not match the schema
│   status code: 400, request id: O6BME04HLPC1NI0VJQP9UANN53VV4KQNSO5AEMVJF66Q9ASUAAJG
│ 
│   with aws_dynamodb_table_item.application_version_record,
│   on main.tf line 92, in resource "aws_dynamodb_table_item" "application_version_record":
│   92: resource "aws_dynamodb_table_item" "application_version_record" {
│ 
╵

### Expected Behavior

Terraform plan should verify in this PLAN phase that there is range_key missing and throw and exception.
Terraform state file should not be updated at APPLY with the dynamodb_table_item resource as shown bellow(especially whan it throws and error):

{
      "mode": "managed",
      "type": "aws_dynamodb_table_item",
      "name": "application_version_record",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "status": "**tainted**",
          "schema_version": 0,
          "attributes": {
            "hash_key": "applicationId",
            "id": "ApplicationVersions|applicationId||xxx|",
            "item": "{\"applicationId\":{\"S\":\"xxx\"},\"builtIn\":{\"BOOL\":true},\"name\":{\"S\":\"xxx\"},\"owner\":{\"S\":\"xxx\"},\"status\":{\"S\":\"active\"},\"type\":{\"N\":\"1\"},\"versionId\":{\"S\":\"1.0.0\"}}",
            "range_key": null,
            "table_name": "ApplicationVersions"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "aws_dynamodb_table.application_versions"
          ]
        }
      ]
    },

### Actual Behavior

Tainted resource in state file. Error at next terraform plan phase:

 Error: reading DynamoDB Table Item (ApplicationVersions|applicationId||xxx|): ValidationException: The provided key element does not match the schema
│   status code: 400, request id: O6BME04HLPC1NI0VJQP9UANN53VV4KQNSO5AEMVJF66Q9ASUAAJG
│ 
│   with aws_dynamodb_table_item.application_version_record,
│   on main.tf line 92, in resource "aws_dynamodb_table_item" "application_version_record":
│   92: resource "aws_dynamodb_table_item" "application_version_record" {

### Steps to Reproduce

1. remove the range_key from terraform config from aws_dynamodb_table_item config
2. run terraform plan and apply
3. run terraform plan again
4. check the terraform state

**Comment by dancruciat** [comment]
Solved by using terraform state rm. Neither terraform refresh or terraform replace didnt work.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
