### ISSUE TITLE
Removed block does not appear in Configuration Language docs section

### ISSUE THREAD

**Issue by alex-shafer-1002** [hashicorp/terraform#35036]
### Terraform Version

```shell
My local terraform version is 1.5.7, however I'm looking at the latest docs
```

### Affected Pages

https://developer.hashicorp.com/terraform/language

### What is the docs issue?

The `removed` block is missing from the Configuration Language reference

### Proposal

I personally went looking for documentation of this feature under the "State" section, then I went looking for a reference of all top-level blocks and couldn't find that either. However the the specifics are not critical to me, I would just like to see this feature documented under "Configuration Language" somewhere.

### References

- #33613 the `moved` block is similarly missing for much longer.

**Comment by crw** [comment]
Thanks for filing this request, and for linking it to the other issue.
