### ISSUE TITLE
feature request: fail for unspecified object keys

### ISSUE THREAD

**Issue by michaele-blend** [hashicorp/terraform#35037]
### Terraform Version

```shell
Terraform v1.6.2
```

### Use Cases

at one point in time, we had a variable definition which looked like this:
```hcl
variable "descheduler" {
  description = "The configuration for `descheduler` addon"
  type = object({
    enabled                            = optional(bool, true)
    force_update                       = optional(bool, false)
    topology_spread_constraint_enabled = optional(bool, false)
    utilizationThresholds = optional(
      object({
        cpu          = number
        memory       = number
        cpuTarget    = number
        memoryTarget = number
      }),
      {
        cpu          = 50
        memory       = 50
        cpuTarget    = 90
        memoryTarget = 90
      }
    )
  })
  default = {}
}
```
later, we refactored the interface to look like this:
```hcl
variable "descheduler" {
  description = "The configuration for `descheduler` addon"
  type = object({
    enabled      = optional(bool, true)
    force_update = optional(bool, false)
    policies = optional(map(object({
      schedule                           = optional(string, "*/10 * * * *")
      nodeSelector                       = optional(string, "role=node")
      topology_spread_constraint_enabled = optional(bool, false)
      utilizationThresholds = optional(
        object({
          cpu          = number
          memory       = number
          cpuTarget    = number
          memoryTarget = number
        }),
        {
          cpu          = 50
          memory       = 50
          cpuTarget    = 90
          memoryTarget = 90
        }
      )
      })), {
      default = {}
    })
  })
  default = {}
}
```
`topology_spread_constraint_enabled` and `utilizationThresholds` were removed, while `policies` was added.
separately, a different member of the team upgraded the module from a version with the first interface, to a version with the second interface. call parameters were not changed, and we did not inspect the resulting plan closely. we ended up applying the changes.
we would have preferred getting a plan error, and being forced to update the call site for this variable, but additional object keys are not an error. they are silently discarded during type conversion:
https://developer.hashicorp.com/terraform/language/expressions/type-constraints#:~:text=Values%20with%20additional%20keys%20can%20still%20match%20an%20object%20type%2C%20but%20the%20extra%20attributes%20are%20discarded%20during%20type%20conversion.
we would like to prevent implicit discard behavior, and instead report an error for any keys which would otherwise be discarded.

### Attempted Solutions

we haven't implemented this, but it seems viable that `keys()` could be used to write a `validation` block and ensure there are no untyped keys present. (this assumes that object keys are not discarded _prior_ to the evaluation of the validation rule).

this solution is suboptimal because we would need one validation block per variable, and the list of accepted keys would need to be specified per variable.

### Proposal

we want the ability to cause unlisted `object` keys to cause an error.
here is a markup of a couple potential ideas:
```hcl
variable "descheduler" {
  description = "The configuration for `descheduler` addon"
  type = strictobject({
    # ...
  })
  default = {}
}
```
or
```hcl
variable "descheduler" {
  description = "The configuration for `descheduler` addon"
  type = strict(object({
    # ...
  }))
  default = {}
}
```

### References

- #28696
- #32015
- #33570

**Comment by crw** [comment]
Thanks for this feature request! If you are viewing this issue and would like to indicate your interest, please use the 👍 reaction on the issue description to upvote this issue. We also welcome additional use case descriptions. Thanks again!
