### ISSUE TITLE
String interpolation not working until resources are created.

### ISSUE THREAD

**Issue by davedash** [hashicorp/terraform#3506]
I have something like this in a `.tf` file:

```
resource "aws_security_group" "rails" {
...
}

module "rails" {
  source = "../instance-west"
  security_groups = "${aws_security_group.environment.id},${aws_security_group.rails.id}"
  env = "${var.env}"
  name = "rails"
  # Remove if we ever upgrade
  user_data = "user_data.ebs2.yaml"
  instance_type = "c4.2xlarge"
  subnets = "${join(",", aws_subnet.main.*.id)}"
}
```

If I run `terraform plan` I get this:

```
* Resource 'aws_security_group.rails' does not have attribute 'id' for variable 'aws_security_group.rails.id'
```

So I end up commenting out the module named `instance` applying, uncommenting and then moving along.  I'd rather the dependency either be implicitly or explicitly determined.

**Comment by mitchellh** [comment]
This has been fixed in the past year. :) Sorry no direct link to a commit, I've been closing a lot of dups like this. Just ran your example though (w/ a fake module) and it worked!
