### ISSUE TITLE
expected a single file: /tmp/getter3359610012/archive: Downloading terraform Version 1.8.2

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform#35075]
### Terraform Version

```shell
terraform version 1.8.2
```

### Terraform Configuration Files

NA

### Debug Output

```
downloading terraform version 1.8.2 at "https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip?checksum=file:https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_SHA256SUMS": expected a single file: /tmp/getter3359610012/archive: Downloading terraform Version 1.8.2
```

### Expected Behavior

for atlantis to pull the correct version of terraform sig

### Actual Behavior

we have a recent version of atlantis.
a newer version of terraform came out today, 1.8.2
and when atlantis pulls that version, the SUM seems to fail

### Steps to Reproduce

atlantis plan

**Comment by FernandoMiguel** [comment]
downstream issue https://github.com/runatlantis/atlantis/issues/4472

**Comment by jbardin** [comment]
Hi @FernandoMiguel,

Thanks for filing the issue. Unfortunately the Terraform project does not have absolute control the packaging and licensing requirements for distribution. The release archives often contain multiple files, and software which fetches the binaries should not expect a single file in the archive. I'm not sure if there's anything we can do from out side, but we can look into it.

**Comment by radeksimko** [comment]
I'm sorry this change has caused issues and I understand this may not be helpful but this is unfortunately one of those changes we did not anticipate to cause enough issues that would warrant additional heads up. It _is_ however [noted in the Changelog](https://github.com/hashicorp/terraform/blob/v1.8.2/CHANGELOG.md#182-april-24-2024) and also called out in [the announcement on Discourse](https://discuss.hashicorp.com/t/terraform-v1-8-2-released/66337).

On a more constructive note, we do maintain a library that can aid with installation of HashiCorp products, including Terraform - [`hc-install`](https://pkg.go.dev/github.com/hashicorp/hc-install) and we use it ourselves in a number of places. Atlantis would be welcomed to use it as well. That library does _not_ make assumptions about the archive having just one file. Our enterprise packages (although not relevant for Terraform here specifically) already have multiple files and [the API accounts for this](https://pkg.go.dev/github.com/hashicorp/hc-install#example-Installer-EnterpriseVersion) too, where the consumers specify a path where the license should be placed.

For Terraform CE, [the API would let you specify `Dir`](https://pkg.go.dev/github.com/hashicorp/hc-install@v0.6.4/releases#InstallationOptions) as a path to the directory where the archive gets unpacked, including `terraform` binary and the license file. What consumers decide to do with those files after the installation would be up to them. The API does not currently make any further assumptions about those files for non-Enterprise versions.

Just for posterity, `go-getter` (which is library Atlantis [appears to be using](https://github.com/runatlantis/atlantis/blob/11d47f3c9fcc2c8bab89931bf4e7935e4911f74f/server/core/terraform/terraform_client.go#L628-L640)) was not designed for this use case of installing products like Terraform, or broadly interacting with `releases.hashicorp.com` and we do not intend to make changes in that library to accommodate that use case.

I will comment in the linked issue also, for visibility.

**Comment by arohter** [comment]
Shame this breaking distribution change was pushed out in a "bugfix" release.

**Comment by thomaschaplin** [comment]
correct downstream issue - https://github.com/runatlantis/atlantis/issues/4471

**Comment by sperts-liveramp** [comment]
Hello Team, what is the status of this issue?

We explicitly set the atlantis version in our atlantis.yaml file like the following:

```
  - name: atlantis-project-example
    dir: dir/foo/bar
    workspace: default
    workflow: core
    terraform_version: v1.9.1
``` 

Currently, we are still unable to use terraform versions 1.8.2 or later with the atlantis version we are using `v0.28.1`.

**Comment by lukemassa** [comment]
The long term fix for this was added to #4494, which was released in `v0.28.2` (https://github.com/runatlantis/atlantis/releases/tag/v0.28.2). Please verify that this fixes your issue.

@FernandoMiguel I believe this issue can be closed now the long term fix is in?

**Comment by lukemassa** [comment]
Atlantis has switched to using hc-install in https://github.com/runatlantis/atlantis/pull/4494, which was released as part of `v0.28.2` (https://github.com/runatlantis/atlantis/releases/tag/v0.28.2).

This issue therefore no longer affects Atlantis and can likely be closed, cc @FernandoMiguel

**Comment by bml1g12** [comment]
@lukemassa I hit this issue today, upgrade server to ghcr.io/runatlantis/atlantis:v0.28.5 but it did not resolve the issue 

```
downloading terraform version 1.9.3 at "https://releases.hashicorp.com/terraform/1.9.3/terraform_1.9.3_linux_amd64.zip?checksum=file:https://releases.hashicorp.com/terraform/1.9.3/terraform_1.9.3_SHA256SUMS": expected a single file: /tmp/getter2511542877/archive: Downloading terraform Version 1.9.3

```
Any suggestions on how we can debug or workaround this issue?

**Comment by bml1g12** [comment]
Update: I fixed this issue by chaning main.tf from  ">= 1.2.0" terraform to "~> 1.4.6" terraform version
