### ISSUE TITLE
The given key does not identify an element in this collection value

### ISSUE THREAD

**Issue by Narayan-Mitra** [hashicorp/terraform#35079]
### Terraform Version

```shell
1.8.2
```

### Terraform Configuration Files

provider.tf
------------------------------------------------------------
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.74.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.52.0"
    }
    azapi = {
      source = "Azure/azapi"
      version = "1.12.1"
    }
    random = {
      source = "hashicorp/random"
      version = "3.6.1"
    }
  }
  required_version = ">= 0.14"
}

provider "azapi" {
  subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
}

provider "azurerm" {
  subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
  features {}
  storage_use_azuread = true
}

provider "azurerm" {
  alias           = "ews-ado"
  subscription_id = ""
  client_id       = ""
  client_secret   = ""
  tenant_id       = ""
  features {}
}

provider "aws" {

  alias  = "cs"
  region = "eu-west-1"
}

storage.tf details
-----------------------------------------
// Diagnostics Logs
locals {
  exception_handling = {
    1 = {
      partition_key        = "1",
      SystemName           = "ais",
      SystemErrorCode      = "401",
      ApplicationErrorCode = "",
      ExceptionType        = "application",
      Impact               = "1",
      Urgency              = "2"
    }

  }
}

resource "azurerm_resource_group" "AzureMonitoring-RG" {
  name     = "AzureMonitoring-RG"
  location = "uksouth"
}

// Shared Storage account for each Project

resource "azurerm_storage_account" "shared_storage_account" {
  name                            = "aissbxsaservices"
  resource_group_name             = azurerm_resource_group.AzureMonitoring-RG.name
  location                        = azurerm_resource_group.AzureMonitoring-RG.location
  account_tier                    = "Standard"
  access_tier                     = "Cool"
  account_replication_type        = "GRS"
  min_tls_version                 = "TLS1_2"
  enable_https_traffic_only       = true
  allow_nested_items_to_be_public = false
  // TODO: Disable this setting:
  // https://github.com/hashicorp/terraform-provider-azurerm/issues/3939
  shared_access_key_enabled         = true
  default_to_oauth_authentication   = true
  infrastructure_encryption_enabled = true
  blob_properties {
    delete_retention_policy {
      days = 365
    }
  }

  queue_properties {
    logging {
      delete                = true
      read                  = true
      write                 = true
      version               = "2.0"
      retention_policy_days = 365
    }
    hour_metrics {
      enabled               = true
      include_apis          = true
      version               = "1.0"
      retention_policy_days = 7
    }
    minute_metrics {
      enabled               = false
      include_apis          = false
      version               = "1.0"
      retention_policy_days = 7
    }
  }

#   network_rules {
#     default_action             = "Deny"
#     ip_rules                   = setunion(var.storage_allowed_ips_services, module.project_logic_apps["dummy-for-outbound-ip"].logic_app_objects.connector_outbound_ip_addresses, module.project_logic_apps["dummy-for-outbound-ip"].logic_app_objects.workflow_outbound_ip_addresses, var.function_app_possible_outbound_ips)
#     bypass                     = ["AzureServices"]
#     virtual_network_subnet_ids = [azurerm_subnet.app_service_subnet.id]
#   }

  identity {
    type = "SystemAssigned"
  }

#   depends_on = [
#     module.project_logic_apps
#   ]
}

resource "azurerm_storage_table_entity" "exception_handling-shared" {
  for_each             = local.exception_handling
  storage_account_name = azurerm_storage_account.shared_storage_account.name
  table_name           = azurerm_storage_table.platform_logic_app_tables-shared["exceptionproperties"].name

  partition_key = each.value["partition_key"]
  row_key       = each.key

  entity = {
    SystemName           = each.value["SystemName"]
    SystemErrorCode      = each.value["SystemErrorCode"]
    ApplicationErrorCode = each.value["ApplicationErrorCode"]
    ExceptionType        = each.value["ExceptionType"]
    Impact               = each.value["Impact"]
    Urgency              = each.value["Urgency"]
  }
}

### Debug Output

Error: Invalid index

  on storage.tf line 3464, in resource "azurerm_storage_table_entity" "exception_handling-shared":
3464:     Impact               = each.value["Impact"]
    ├────────────────
    │ each.value is object with 6 attributes

The given key does not identify an element in this collection value.
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

### Expected Behavior

Code should be provisioned in Azure cloud

### Actual Behavior

Getting error as below
Error: Invalid index

  on storage.tf line 3464, in resource "azurerm_storage_table_entity" "exception_handling-shared":
3464:     Impact               = each.value["Impact"]
    ├────────────────
    │ each.value is object with 6 attributes

The given key does not identify an element in this collection value.
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

### Steps to Reproduce

Run the Terraform code using GitHub action workflow. Workflow file
name: Terraform for AIS

on:
  workflow_call:
    inputs:
      ENV:
        type: string
        default: dev
      DEPLOY_ENVIRONMENT:
        type: string
        default: env/dev

env:

  TF_VAR_ado_id: ${{ secrets.ADO_ID }}
  TF_VAR_ado_secret: ${{ secrets.ADO_SECRET }}

jobs:
  terraform-plan:
    runs-on: pcoe-runner-linux-prod
    environment: ${{ inputs.DEPLOY_ENVIRONMENT }}
    env:
      AWS_SESSION_NAME: cs_SESSION
      ROLE_DURATION: 3600
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      
    permissions:
      id-token: write
      contents: read

    steps:
    - name: GitHub Code Checkout
      uses: actions/checkout@v3

    - name: Terraform Module repository authentication token
      uses: navikt/github-app-token-generator@2d70c12368d1958155af4d283f9f21c9a2a8cb98
      id: get-token
      with:
        app-id: ${{ secrets.TF_MODULES_GITHUB_APP_ID }}
        private-key: ${{ secrets.TF_MODULES_GITHUB_PRIVATE_KEY }}

    - name: Replace GIT config global url
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/KPMG-UK".insteadOf "https://github.com/KPMG-UK"
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}

    - name: AWS IAM role assignment
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::591721420056:role/ais_github_role
        role-session-name: ${{ env.AWS_SESSION_NAME }}

    - name: Terraform Installation
      uses: hashicorp/setup-terraform@v2
      with:
        #terraform_version: 1.3.5
        terraform_version: 1.8.2

    - name: Terraform Backend state Initialization
      shell: bash
      working-directory: terraform/core
      run: >
        terraform init -reconfigure
        -backend-config="bucket=ais-cs-tfstate"  
        -backend-config="key=env/${{ inputs.ENV }}/terraform.tfstate" 
        -backend=true 
        -get=true 
        -input=false 

    - name: Terraform Format and Validate
      shell: bash
      id: validate
      working-directory: terraform/core
      run: |
        terraform fmt --recursive
        terraform validate -no-color

    - name: Terraform Plan 
      shell: bash
      working-directory: terraform/core
      run: |
        az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
        terraform plan -no-color -input=false -var-file=${{ github.workspace }}/terraform/core/vars/${{ inputs.ENV }}.tfvars
 
    - name: Removing Azure CLI login 
      shell: bash
      working-directory: terraform/core
      run: |
        az account clear

  terraform-apply:
    runs-on: pcoe-runner-linux-prod
    needs: terraform-plan
    environment: ${{ inputs.DEPLOY_ENVIRONMENT }}-apply

    env:
      AWS_SESSION_NAME: cs_SESSION
      ROLE_DURATION: 3600
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      
    permissions:
      id-token: write
      contents: read

    outputs:
      terraform: ${{ steps.tf-outputs.outputs.stdout }}

    steps:
    - name: GitHub Code Checkout
      uses: actions/checkout@v3

    - name: Terraform Module repository authentication token
      uses: navikt/github-app-token-generator@2d70c12368d1958155af4d283f9f21c9a2a8cb98
      id: get-token
      with:
        app-id: ${{ secrets.TF_MODULES_GITHUB_APP_ID }}
        private-key: ${{ secrets.TF_MODULES_GITHUB_PRIVATE_KEY }}

    - name: Replace GIT config global url
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/KPMG-UK".insteadOf "https://github.com/KPMG-UK"
      env:
        GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}

    - name: AWS IAM role assignment
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::591721420056:role/ais_github_role
        role-session-name: ${{ env.AWS_SESSION_NAME }}

    - name: Terraform Installation
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.5

    - name: Terraform Backend Initialization
      shell: bash
      working-directory: terraform/core
      run: >
        terraform init 
        -backend-config="bucket=ais-cs-tfstate"  
        -backend-config="key=env/${{ inputs.ENV }}/terraform.tfstate" 
        -backend=true 
        -get=true 
        -input=false 

    - name: Terraform Format and Validate
      shell: bash
      id: validate
      working-directory: terraform/core
      run: |
        terraform fmt --recursive
        terraform validate -no-color

    - name: Terraform Plan 
      shell: bash
      working-directory: terraform/core
      run: |
        az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
        terraform plan -no-color -input=false -var-file=${{ github.workspace }}/terraform/core/vars/${{ inputs.ENV }}.tfvars
        
    - name: Terraform Apply
      shell: bash
      working-directory: terraform/core
      run: |
        terraform apply -no-color -input=false -auto-approve -var-file=${{ github.workspace }}/terraform/core/vars/${{ inputs.ENV }}.tfvars

    - name: Get outputs
      id: tf-outputs
      working-directory: terraform/core
      run: terraform output -json
      
    - name: Removing Azure CLI login 
      shell: bash
      working-directory: terraform/core
      run: |
        az account clear

### Additional Context

If same code is run with local machine following same configuration then there is no issue but issue getting when run through GitHub workflow.

**Comment by liamcervante** [comment]
Hi @Narayan-Mitra, thanks for filing this! Are you able to verify that you still see this issue if you update your `terraform-apply` step to also use  `1.8.2`? Alternatively, can you run your example code locally with `1.3.5` without problem?

Do see this just with the `terraform-apply` action, or with the `terraform-plan` action as well? I see that they seem to be executing with different versions.

Note, that there is no difference between the Terraform binaries when they are executing locally, or via a CI system like Github Actions. Any difference in behaviour I would be more likely to attribute to an issue within the different environments rather than Terraform itself. For example, are you sure the latest config is being made available to the CI system?

**Comment by Narayan-Mitra** [comment]
Hi team,

I have found root cause, there is a code missing in actual environment and hence it is failing. I have updated complete code into the branch and then run the workflow and finally got the sucessess
