### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by TheNilesh** [hashicorp/terraform#35083]
### Terraform Version

```shell
Terraform v1.8.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/external v2.3.3

Your version of Terraform is out of date! The latest version
is 1.8.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform

resource "pf9_cluster" "cluster" {
  name = var.cluster_name
  addons = {
    "kubernetes-dashboard" = null
  }
}
```

### Debug Output

https://gist.github.com/TheNilesh/641b223a094ecc78252c4cd6a675b5f4

### Expected Behavior

No crash

### Actual Behavior

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Steps to Reproduce

1. Find a terraform provider that has been developed using terraform plugin framework
2. The provider should have an attribute of type `map_nested`. [map-nested](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/attributes/map-nested)
3. The practitioner should set the value of the key from the map to `null` and run `terraform apply`

Example terraform configuration to reproduce this error

```terraform
resource "examplecloud_thing" "example" {
  example_attribute = {
    "key1" = {
        attr = "one"
    },
    # The following attribute value will cause panic. 
    # I believe terraform is trying to load the value of the attribute "key2" in map[string]interface{} 
    # before checking if it is nil.
    "key2" = null
  }
}
```

### Additional Context

- I am the author of the terraform provider. Here's the [schema](https://github.com/platform9/terraform-provider-pf9/blob/private/nilesh/migrate-from-sdkv2-to-pfw/internal/provider/resource_cluster/cluster_resource_gen.go#L36)
- The provider is developed using a plugin framework. During debugging this crash happens after calling `ModifyPlan()`
- The issue is associated with the setting value of the `map_nested` element to `null` in the config. In this case `addons` is of type `map_nested` and `kubernetes-dashboard`(key inside the map) was set to null by the practitioner.

**Comment by TheNilesh** [comment]
Here's [schema](https://github.com/platform9/terraform-provider-pf9/blob/private/nilesh/migrate-from-sdkv2-to-pfw/internal/provider/resource_cluster/cluster_resource_gen.go#L36):
```
"addons": schema.MapNestedAttribute{
	NestedObject: schema.NestedAttributeObject{
		Attributes: map[string]schema.Attribute{
			"params": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
			},
			"phase": schema.StringAttribute{
				Computed: true,
			},
			"version": schema.StringAttribute{
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		CustomType: AddonsType{
			ObjectType: types.ObjectType{
				AttrTypes: AddonsValue{}.AttributeTypes(ctx),
			},
		},
	},
	Optional: true,
	Computed: true,
	PlanModifiers: []planmodifier.Map{
		mapplanmodifier.UseStateForUnknown(),
	},
},
```

**Comment by TheNilesh** [comment]
@jbardin Have you been able to reproduce the issue? I have also added **Steps to Reproduce** in the issue description, hope it helps.

**Comment by jbardin** [comment]
Thank you for the extra info @TheNilesh, we will look into this!
