### ISSUE TITLE
Issue while creating the Premium function app 

### ISSUE THREAD

**Issue by manigandanpro** [hashicorp/terraform#35098]
### Terraform Version

```shell
$ ./terraform version
Terraform v1.5.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.89.0

Your version of Terraform is out of date! The latest version
is 1.8.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output
```
{"error":{"code":"RequestDisallowedByPolicy","target":"cpmanistgeussa2","message":"Resource 'cpmanistgeussa2' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"HCE - Cloud Security Baseline - Deny & Modify\",\"id\":\"/providers/Microsoft.Management/managementGroups/CONNECTEDALL-NONPROD/providers/Microsoft.Authorization/policyAssignments/1f772384ba1c48ad851bab07\"},\"policyDefinition\":{\"name\":\"Storage accounts should restrict network access\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/34c877ad-507e-4c82-993e-3452a6e0ad3c\"},\"policySetDefinition\":{\"name\":\"HCE - Cloud Security Baseline - Deny & Modify\",\"id\":\"/providers/Microsoft.Management/managementGroups/CONNECTEDALL-NONPROD/providers/Microsoft.Authorization/policySetDefinitions/7c2a0ac9b84c46fab1260c42\"}}]
```

### Expected Behavior

Elastic premium function app trying to create file share in existing storage account. The storage account have the private endpoint enabled and public access disabled. The function app should be created through private connection not through public.

Note: We do have policy applied where the resources should not have the public access enabled.

### Actual Behavior

While creating using terraform even with outbound network connectivity , the function app at first its trying to create file share and then its trying to configure the outbound vnet connectivity. In this case while its trying to create file share , the network connectivity is pubic , so we are facing the policy issue.

At first it should configure the network configuration and then it should try to create the file share in storage account.

### Steps to Reproduce

terraform init
terraform apply

**Comment by crw** [comment]
Hello @manigandanpro, this appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
