### ISSUE TITLE
Resource "azurerm_monitor_scheduled_query_rules_alert_v2" created but corrupted

### ISSUE THREAD

**Issue by admsallai** [hashicorp/terraform#35134]
### Terraform Version

```shell
Terraform v1.8.1
```

### Terraform Configuration Files

```resource "azurerm_monitor_scheduled_query_rules_alert_v2" "ingestion_alert" {
  name                             = "ingestion-alert"
  location                         = data.azurerm_resource_group.infrastructure_rg.location
  resource_group_name  = data.azurerm_resource_group.infra_rg.name
  scopes                           = [data.azurerm_log_analytics_workspace.law.id]
  severity                          = 2
  evaluation_frequency    = "PT6H"
  window_duration           = "P1D"
  description                     = "n/A"
  action {
    action_groups = [azurerm_monitor_action_group.action_group["actiongroup"].id]
  }
  criteria {
    operator                      = "GreaterThan"
    query                           = "Usage | where TimeGenerated > ago(24h) | summarize TotalIngestionVolGB = sum(Quantity)/1024.0"
    metric_measure_column     = "TotalIngestionVolGB"
    time_aggregation_method = "Total"
    threshold                             = 5
  }
}
```

### Debug Output

Alert is successfully created and visible in Azure Portal. However it is not being fired when criteria are met, and when trying to edit it in the portal this happend:

![Screenshot 2024-04-19 141102](https://github.com/hashicorp/terraform/assets/102801593/b764efa2-e824-4f82-b641-a18802c1c0b9)

No summary is present. Unable to click Review+Save. Next step is Review+Save, even when Review+Save page is already open.

**After contacting Microsoft support, they could not fix the issue, and this is how they described this issue after investigating:** 

"If an alert rule is created without managed identity from portal, we don't see that entry in the export template, whereas the terraform includes a Null value even though managed Identity is not enabled. Kindly ask you to reach out to terraform support and highlight this issue, they should probably fix it from their end."

This alert was working fine when creating 2 months ago, however when I need to recreate it again, with the same terraform code, this issue happened. **This  issue is present for all the alerts of this kind, not only this one.**

### Expected Behavior

Create an alert which is not corrupted.

### Actual Behavior

Alert is created but not working properly.

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
