### ISSUE TITLE
when changing R53 record from ALIAS to CNAME: diffs didn't match during apply

### ISSUE THREAD

**Issue by FlorinAndrei** [hashicorp/terraform#3515]
Terraform v0.6.3 on OS X El Capitan 10.11

1 VPC, bunch of subnets, some ELBs. I'm creating Route53 records for the ELBs. I had a record as an ALIAS, but then I changed my mind and made it a CNAME. When I ran "terraform apply" I got this:

```
Error applying plan:

1 error(s) occurred:

* aws_route53_record.prod2-manage-api: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

The record initially was something like this:

```
resource "aws_route53_record" "prod2-manage-api" {
  zone_id = "XXXXXXXXXXXXXX"
  name = "prod2-manage-api"
  type = "A"
  alias {
    name = "${aws_elb.prod2-manage-api.dns_name}"
    zone_id = "${aws_elb.prod2-manage-api.zone_id}"
    evaluate_target_health = false
  }
}
```

After the switch to CNAME it was something like this:

```
resource "aws_route53_record" "prod2-manage-api" {
  zone_id = "XXXXXXXXXXXXXXX"
  name = "prod2-manage-api"
  type = "CNAME"
  ttl = "300"
  records = ["${aws_elb.prod2-manage-api.dns_name}"]
}
```

If you need more info, ask me. I have saved the directory with all .tf files and the complete output from "terraform apply".

**Comment by FlorinAndrei** [comment]
To add more details:

TF errored out after deleting the old record, but didn't create the new record.

I ran "terraform apply" again and it created the new CNAME without issues.

**Comment by FlorinAndrei** [comment]
The bug is reproducible. I've changed another ALIAS into a CNAME and I got the same error; the ALIAS is deleted but the CNAME is not created. Re-running "terraform apply" after the error creates the new CNAME without issues.

**Comment by sysadmin1139** [comment]
I just had this exact same problem occur with 0.6.9. Moving from `A` (with alias) to `CNAME`.

**Comment by mitchellh** [comment]
This is fixed, just ran with this config and flip flopped the ALIAS/CNAME a few times, always worked:

```# Create a new load balancer
resource "aws_elb" "bar" {
  name = "foo"
  instances = []
  availability_zones = ["us-east-1a"]

  listener {
    instance_port = 8000
    instance_protocol = "http"
    lb_port = 80
    lb_protocol = "http"
  }
}

resource "aws_route53_zone" "zone" {
   name = "terraform-test.com"
}

/*
resource "aws_route53_record" "record" {
  zone_id = "${aws_route53_zone.zone.id}"
  name = "foo"
  type = "A"

  alias {
    name = "${aws_elb.bar.dns_name}"
    zone_id = "${aws_elb.bar.zone_id}"
    evaluate_target_health = false
  }
}
*/

resource "aws_route53_record" "record" {
  zone_id = "${aws_route53_zone.zone.id}"
  name = "foo"
  type = "CNAME"
  ttl = "300"
  records = ["${aws_elb.bar.dns_name}"]
}

```
