### ISSUE TITLE
Attempting to use module outputs in AWS Lambda environment variables fails

### ISSUE THREAD

**Issue by jake-rothwell-uplight** [hashicorp/terraform#35166]
### Terraform Version

```shell
Terraform v1.6.6
on darwin_amd64
```

### Terraform Configuration Files

```terraform
module "lambda_function_gatekeeper" {
  source  = "terraform-aws-modules/lambda/aws"
  version = ">=7.2.6"

  description   = "Lambda function for gatekeeper"
  function_name = "${var.stack_name}gatekeeper"
  handler       = "main.lambda_handler"
  runtime       = local.python_runtime
  publish       = true

  architectures = [
    "x86_64",
  ]
  environment_variables = merge(local.lambda_envs, {
    "ENV_VAR"   = aws_api_gateway_rest_api.api.id,
    "LAMBDA_PROXY_INVOKE_ARN" = module.lambda_function_proxy.lambda_function_qualified_invoke_arn
  })
```

### Debug Output

N/A

### Expected Behavior

Lambda function should be created successfully with environment variables referencing module outputs after running `terraform_apply`

### Actual Behavior

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.lambda_function_gatekeeper.aws_lambda_function.this[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .environment: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce

1. terraform apply

**Comment by liamcervante** [comment]
Hi @jake-rothwell-uplight, thanks for filing this. The AWS provider is actually managed in a separate repository to the Terraform core binary.  This can be found in https://github.com/hashicorp/terraform-provider-aws. I will close the issue here and you should reopen again directly with the AWS provider team. Thanks!
