### ISSUE TITLE
broken link in architecture.md

### ISSUE THREAD

**Issue by jwhitt3r** [hashicorp/terraform#35184]
### Terraform Version

```shell
Terraform v1.8.3
on windows_amd64
```

### Affected Pages

architecture.md

### What is the docs issue?

Abroken link due to spelling mistake within the architecture.md file of the docs.

The link in question that is broken is:
`https://pkg.go.dev/github.com/hashicorp/terraform/internal/erraform#Execute`

### Proposal

`https://pkg.go.dev/github.com/hashicorp/terraform/internal/erraform#Execute`
this is fixed with
`https://pkg.go.dev/github.com/hashicorp/terraform/internal/terraform#Execute`

**Comment by richard-salam** [comment]
I think `'t'` on `terraform` is missing on the paths.

**Comment by jwhitt3r** [comment]
This has been fixed and merged too my knowledge

**Comment by crw** [comment]
The link is fixed, ironically no longer displayed due to license restrictions. :(

**Comment by crw** [comment]
Filed https://github.com/hashicorp/terraform/issues/35394
