### ISSUE TITLE
source_security_group_id errors out with a can't find security group message

### ISSUE THREAD

**Issue by icebourg** [hashicorp/terraform#3518]
Hi,

As an example config:

    resource "aws_security_group" "integration" {
      name = "integration_environment"
      description = "Integration Environment"
    }

    resource "aws_security_group_rule" "allow_from_integration" {
      type = "ingress"
      from_port = 22
      to_port = 22
      protocol = "tcp"
      security_group_id = "sg-123456789"
      source_security_group_id = "${aws_security_group.integration.id}"
    }

What I'm trying to do here is take an existing security group (sg-123456789, not managed by terraform), and add an ingress rule that allows the new security group (aws_security_group.integration) to ssh to instances in the existing security group.

Unfortunately if you try it, you invariably get this error message:

    aws_security_group.integration: Creating...
      description: "" => "Integration Environment"
      egress.#:    "" => "<computed>"
      ingress.#:   "" => "<computed>"
      name:        "" => "integration_environment"
      owner_id:    "" => "<computed>"
      vpc_id:      "" => "<computed>"
    aws_security_group.integration: Creation complete
    aws_security_group_rule. allow_from_integration: Creating...
      from_port:                "" => "22"
      protocol:                 "" => "tcp"
      security_group_id:        "" => "sg-123456789"
      self:                     "" => "0"
      source_security_group_id: "" => "sg-987654321"
      to_port:                  "" => "22"
      type:                     "" => "ingress"
    Error applying plan:

    1 error(s) occurred:

    * aws_security_group_rule. allow_from_integration: Error authorizing security group rule type ingress: InvalidGroup.NotFound: Unable to find group 'sg-987654321'
      status code: 400, request id:

    Terraform does not automatically rollback in the face of errors.
    Instead, your Terraform state file has been partially updated with
    any resources that successfully completed. Please address the error
    above and apply again to incrementally change your infrastructure.

Note that obviously I've redacted the actual security group IDs. But you get the idea that the aws_security_group_rule can't find the group that we just created.

Through experimentation I've tried a few different things like hardcoding existing security groups to make sure it's not some eventual consistency issue with EC2 and through poking around the aws-sdk-go API is that the upstream API takes a security group **name** and not an **id**. Whatever, I thought, terraform should be able map between the two. But it got me curious enough to try something:

    resource "aws_security_group" "integration" {
      name = "integration_environment"
      description = "Integration Environment"
    }

    resource "aws_security_group_rule" "allow_from_integration" {
      type = "ingress"
      from_port = 22
      to_port = 22
      protocol = "tcp"
      security_group_id = "sg-123456789"
      source_security_group_id = "${aws_security_group.integration.name}"
    }

And ... terraform crashes. But what's interesting, is that the security group and the rule I want both get created no problem. (though the state doesn't get saved -- but checking with Amazon, what I wanted happened)

My guess is that terraform is passing `source_security_group_id` as the security group name to aws-sdk-go, instead of converting the id to a name and giving it to the api as a name.

Looks like github won't let me attach a crash log without write permission to this repo, but I believe the config I've given is enough to reproduce this issue in the latest available terraform.

**Comment by icebourg** [comment]
Further troubleshooting shows that setting self=true in the rule results in the same behavior. EG:

    resource "aws_security_group" "integration" {
      name = "integration_environment"
      description = "Integration Environment"
    }

    resource "aws_security_group_rule" "allow_from_integration" {
      type = "ingress"
      from_port = 22
      to_port = 22
      protocol = "tcp"
      security_group_id = "sg-123456789"

Results in this plan:

(note how source_security_group_id automatically becomes name and not id)

    + aws_security_group.integration
        description: "" => "Integration Environment"
        egress.#:    "" => "<computed>"
        ingress.#:   "" => "<computed>"
        name:        "" => "integration_environment"
        owner_id:    "" => "<computed>"
        vpc_id:      "" => "<computed>"

    + aws_security_group_rule.allow_from_integration
        from_port:                "" => "22"
        protocol:                 "" => "tcp"
        security_group_id:        "" => "sg-123456789"
        self:                     "" => "0"
        source_security_group_id: "" => "integration_environment"
        to_port:                  "" => "22"
        type:                     "" => "ingress"

Which results in the same crash as before. Except interestingly more state gets saved this time.

I'm hoping to create a PR to fix this so I can move on but honestly I find the terraform code pretty dense.

**Comment by icebourg** [comment]
Further troubleshooting shows that setting self=true in the rule results in similar behavior. EG:

    resource "aws_security_group" "integration" {
      name = "integration_environment"
      description = "Integration Environment"
    }

    resource "aws_security_group_rule" "allow_from_integration" {
      type = "ingress"
      from_port = 22
      to_port = 22
      protocol = "tcp"
      self = true
    }

Results in this plan:

    + aws_security_group.integration
        description: "" => "Integration Environment"
        egress.#:    "" => "<computed>"
        ingress.#:   "" => "<computed>"
        name:        "" => "integration_environment"
        owner_id:    "" => "<computed>"
        vpc_id:      "" => "<computed>"

    + aws_security_group_rule.allow_from_integration
        from_port:                "" => "22"
        protocol:                 "" => "tcp"
        security_group_id:        "" => "sg-123456789"
        self:                     "" => "0"
        source_security_group_id: "" => "<computed>"
        to_port:                  "" => "22"
        type:                     "" => "ingress"

Which results in the same crash as before. The rule gets created, but terraform crashes. Self isn't the behaviour I want, but it does show that terraform has multiple bugs involving source_security_group_id.

**Comment by catsby** [comment]
Closing as noted in https://github.com/hashicorp/terraform/pull/3520#issuecomment-155198798
