### ISSUE TITLE
tfstate is corrupt when remote-exec provisioner fails

### ISSUE THREAD

**Issue by suxor42** [hashicorp/terraform#352]
Situation:
When terraforms remote-exec provisioner fails the the terraform.tfstate is corrupt.

Effect:
- trying to destroy the vm fails because of the corruption
- consecutive calls of terraform fail (show,apply,plan)
- you have to use the "website" of the provider to destroy the vm(s)
- vm(s) is/are still usable but not with terraform

Details:
- terraform version: Terraform v0.2.3.dev (1759fdeeed480eada9ad4afd1c39cada60a49db9+CHANGES)
- gist to the console output: https://gist.github.com/suxor42/dee2a54a1304e8722f4f
- tfdestroy command: `alias tfdestroy='tf plan -var-file=/Users/suxor/.sec/infrastructurevars --destroy -out=destroy.tfplan && tf apply destroy.tfplan'`

Terraform files to reproduce:
https://github.com/suxor42/tfissue

Sidenote:
with version Terraform v0.2.2.dev (58a482d67742b9bc43d28831b1fe70388101b9c4) there was no corrupt tfstate
I use terraform only with DigitalOcean therefore I don't know if this happens with other providers too.

**Comment by pearkes** [comment]
#1057 fixes this, but note that on master you'll see other issues until #1056 is fixed in this reproduction case. The core issue of tainted resources being properly destroyed is fixed in #1057 though.

**Comment by pearkes** [comment]
Fixed in #1057! Thanks.
