### ISSUE TITLE
vsphere: turn on SSL verification and expose configuration option to disable

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#3521]
As @mkuzmin correctly pointed out in https://github.com/hashicorp/terraform/pull/3419/files#r42080780, the default here is insecure.

Good precent here is an `allow_unverified_ssl` parameter from rundeck:

https://github.com/hashicorp/terraform/blob/master/builtin/providers/rundeck/provider.go#L25-L30

**Comment by phinze** [comment]
Refs https://github.com/hashicorp/terraform/pull/3419

**Comment by chrislovecnm** [comment]
@phinze do we need to make this a config value?  I would say environment variable?  I have seen many installs with self signed certs ..

**Comment by chrislovecnm** [comment]
Added comment to our arch list in https://github.com/hashicorp/terraform/issues/3624

**Comment by phinze** [comment]
@chrislovecnm - yep! I recommended above that we do something like the `allow_unverified_ssl` param in Rundeck.

Should be pretty straightfoward. Tagging this `easy` for that reason. :+1:

**Comment by phinze** [comment]
This is done now!
