### ISSUE TITLE
Unable to remove azurerm batch pool certificate

### ISSUE THREAD

**Issue by abdelalimah** [hashicorp/terraform#35216]
### Terraform Version

```shell
1.1.5
```

### Terraform Configuration Files

My initial configuration azurerm_batch_account file contains a configuration similar to the following :
```terraform
resource "azurerm_batch_account" "example" {
  name                 = "example-batchaccount"
  resource_group_name  = azurerm_resource_group.example.name
  location             = azurerm_resource_group.example.location
  pool_allocation_mode = "BatchService"
  storage_account_id   = azurerm_storage_account.example.id

  certificate {
    thumbprint           = "your-thumbprint"
    thumbprint_algorithm = "SHA1"
    store_location       = "CurrentUser"
    store_name           = "My"
    visibility           = ["StartTask"]
  }

  start_task {
    command_line         = "echo starting"
    max_task_retry_count = 1
    wait_for_success     = true
  }

  auto_scale {
    evaluation_interval = "PT15M"
    formula             = "QUEUE=activeTasks; $TargetDedicatedNodes=min($QUEUE,10);"
  }
}

```
The change made is the deletion of the certificate block

### Debug Output

The following problems may be the cause of any confusing errors from downstream operations:
        - .certificate: block count changed from 0 to 1

### Expected Behavior

Given the plan's output it clearly outlines that the certificate will be deleted on the set of the pools managed by the batch pool module, so the expected behavior would be the removal of the certificate from the batch pools on Azure

### Actual Behavior

Apply of the configuration doesn't throw any error and outputs that the Apply was complete but checking on the pools via the Azure portal the certificate is not removed, and replaying a plan on the same configuration shows that the same certificates will be removed from the pool once again.

### Steps to Reproduce

1. Create batch pool with certificate :

  - `terraform plan`
  - `terraform apply`

2. Remove certificate block from batch pool configuration

- `terraform plan`
- `terraform apply`

### Additional Context

provider version is : azurerm 3.75.0

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
