### ISSUE TITLE
terraform init with latest terraform version (1.8.3) crash on Intel-based MacBook Pro

### ISSUE THREAD

**Issue by ciphero** [hashicorp/terraform#35219]
### Terraform Version

```shell
❯ terraform --version
Terraform v1.8.3
on darwin_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "~> 1.8"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  backend "s3" {....}
```

### Debug Output

❯ terraform init

Initializing the backend...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

panic: runtime error: slice bounds out of range [1:0]
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	github.com/hashicorp/terraform/internal/logging/panic.go:84 +0x18b
panic({0xef97880?, 0xc0008b6660?})
	runtime/panic.go:770 +0x132
github.com/aws/aws-sdk-go-v2/internal/ini.unquote({0xc000271288, 0x1})
	github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:63 +0xf9
github.com/aws/aws-sdk-go-v2/internal/ini.legacyStrconv(...)
	github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/strings.go:71
github.com/aws/aws-sdk-go-v2/internal/ini.asProperty({0xc000271263?, 0xc000875500?})
	github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/tokenize.go:60 +0x91
github.com/aws/aws-sdk-go-v2/internal/ini.tokenize({0xc000875508, 0x31, 0xe8cba90?})
	github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/tokenize.go:16 +0x199
github.com/aws/aws-sdk-go-v2/internal/ini.Parse({0xf1a38b8?, 0xc000548420?}, {0xc0007c1920, 0x26})
	github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/ini.go:50 +0xc5
github.com/aws/aws-sdk-go-v2/internal/ini.OpenFile({0xc0007c1920, 0x26})
	github.com/aws/aws-sdk-go-v2/internal/ini@v1.8.0/ini.go:39 +0x119
github.com/aws/aws-sdk-go-v2/config.loadIniFiles({0x10c3d3b0, 0x1, 0xc000822bb0?})
	github.com/aws/aws-sdk-go-v2/config@v1.27.7/shared_config.go:772 +0x85
github.com/aws/aws-sdk-go-v2/config.LoadSharedConfigProfile({_, _}, {_, _}, {_, _, _})
	github.com/aws/aws-sdk-go-v2/config@v1.27.7/shared_config.go:656 +0x1b4
github.com/aws/aws-sdk-go-v2/config.loadSharedConfig({0xf1e06f8, 0xc000878630}, {0xc00074c860, 0x2, 0x2})
	github.com/aws/aws-sdk-go-v2/config@v1.27.7/shared_config.go:593 +0x391
github.com/aws/aws-sdk-go-v2/config.configs.AppendFromLoaders({0xc00076d250?, 0xc000892a00?, 0x10?}, {0xf1e06f8, 0xc000878630}, {0xc00076d270, 0x2, 0xe06e61b?})
	github.com/aws/aws-sdk-go-v2/config@v1.27.7/config.go:126 +0xb6
github.com/aws/aws-sdk-go-v2/config.LoadDefaultConfig({_, _}, {_, _, _})
	github.com/aws/aws-sdk-go-v2/config@v1.27.7/config.go:194 +0x173
github.com/hashicorp/aws-sdk-go-base/v2.getCredentialsProvider({0xf1e06f8, 0xc000878630}, 0xc000892600)
	github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.45/credentials.go:78 +0x8c5
github.com/hashicorp/aws-sdk-go-base/v2.GetAwsConfig({_, _}, _)
	github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.45/aws_config.go:113 +0x94f
github.com/hashicorp/terraform/internal/backend/remote-state/s3.(*Backend).Configure(0xc000750780, {{{0xf1e0d10?, 0xc000769b70?}}, {0xec30320?, 0xc0008781b0?}})
	github.com/hashicorp/terraform/internal/backend/remote-state/s3/backend.go:1203 +0x404b
github.com/hashicorp/terraform/internal/command.(*Meta).backendInitFromConfig(0xc000580e00, 0xc000899d60)
	github.com/hashicorp/terraform/internal/command/meta_backend.go:1432 +0x7b9
github.com/hashicorp/terraform/internal/command.(*Meta).backend_C_r_s(0xc000580e00, 0xc000899d60, 0x69b17b59, 0xc0007c87e0, 0xc000826de8)
	github.com/hashicorp/terraform/internal/command/meta_backend.go:1000 +0x979
github.com/hashicorp/terraform/internal/command.(*Meta).backendFromConfig(0xc000580e00, 0xc000826de8)
	github.com/hashicorp/terraform/internal/command/meta_backend.go:649 +0x17a5
github.com/hashicorp/terraform/internal/command.(*Meta).Backend(0xc000580e00, 0x0?)
	github.com/hashicorp/terraform/internal/command/meta_backend.go:105 +0x6a
github.com/hashicorp/terraform/internal/command.(*InitCommand).initBackend(0xc000580e00, {0xf1e0730?, 0xc0000fc500?}, 0xc0008ee5a0, {{0xe05bb0e?, 0xe058b4c?}, 0xc000124fc0?})
	github.com/hashicorp/terraform/internal/command/init.go:507 +0x91f
github.com/hashicorp/terraform/internal/command.(*InitCommand).Run(0xc000580e00, {0xc000074050, 0x0, 0x0})
	github.com/hashicorp/terraform/internal/command/init.go:201 +0x137e
github.com/hashicorp/cli.(*CLI).Run(0xc00088c280)
	github.com/hashicorp/cli@v1.1.6/cli.go:265 +0x5b8
main.realMain()
	github.com/hashicorp/terraform/main.go:339 +0x1e6b
main.main()
	github.com/hashicorp/terraform/main.go:64 +0x13

### Expected Behavior

Terraform should complete init phase

### Actual Behavior

Terraform crashes

### Steps to Reproduce

terraform init

### Additional Context

macOs Ventura 13.6.6

**Comment by ciphero** [comment]
Same configuration tested to work with Terraform 1.6.3 and AWS provider plugin 5.25.0.

**Comment by apparentlymart** [comment]
Hi @ciphero! Sorry for this crash and thanks for reporting it. 

Based on the stack trace in this message it appears that the AWS SDK, used by the S3 backend, was attempting to parse your AWS configuration file, but handled something incorrectly.

I expect that this will need to be fixed upstream in the AWS SDK maintained by the AWS team, rather than here in Terraform, but to help with diagnosing the cause so we can report it upstream it would help if you could share the content of your AWS configuration file.

Since these files tend to contain information about your AWS account I recommend replacing any appearances of your account id and other similar personal information with a realistic placeholder, by which I mean replacing numeric account id with placeholder digits and any identifiers with names that use a similar range of characters, just to try to avoid inadvertently fixing the problem by redacting it away.

We can then try to reproduce the issue and hopefully explain the problem enough to start a discussion with the team that maintains the AWS SDK.

Thanks!

**Comment by ciphero** [comment]
Just to clarify, you're asking for the relevant config of ~/.aws/credentials or ~/.aws/config or both?

**Comment by ciphero** [comment]
Based on the information provided here, I cleaned out my ~/.aws/credentials file (it was quite large...) and started from scratch and the issue now seems to be resolved.
