### ISSUE TITLE
vsphere: rename "vcenter_server" config parameter to something clearer

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#3522]
@mkuzmin has suggested "vsphere_server" https://github.com/hashicorp/terraform/pull/3419#discussion_r42081176

**Comment by phinze** [comment]
refs #3419

**Comment by mkuzmin** [comment]
Property name is fine, but I'd change the environment variable name from `VSPHERE_VCENTER` to `VSPHERE_SERVER`.

**Comment by tkak** [comment]
It is ok to change. Thanks!
