### ISSUE TITLE
Fix module object attribute assignment

### ISSUE THREAD

**Issue by dancer1325** [hashicorp/terraform#35243]
### Terraform Version

```shell
~> 1.3
```

### Affected Pages

https://developer.hashicorp.com/terraform/tutorials/modules/module-object-attributes

### What is the docs issue?

More concretely in the section https://developer.hashicorp.com/terraform/tutorials/modules/module-object-attributes#refactor-module-with-object-attribute, you can find

> Use different index and error documents by configuring `index_document_suffix` and `error_document_key`:

```
files = {
    terraform_managed = true
    www_path          = "${path.root}/www"
    Index_document_suffix = “main.html"
            Error_document_key = “error.html"
  }
```

You can see the errors
* identation
* wrong initial double quotes

**Note:** I can guess that these errors are non intended.

### Proposal

```
files = {
    terraform_managed = true
    www_path          = "${path.root}/www"
    Index_document_suffix = "main.html"
    Error_document_key = "error.html"
  }
```

**Comment by crw** [comment]
Thanks for this docs request!
