### ISSUE TITLE
Refactor wrong lifecycle customization description for datasource

### ISSUE THREAD

**Issue by dancer1325** [hashicorp/terraform#35246]
### Terraform Version

```shell
At least v1.7X
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/data-sources#lifecycle-customizations

### What is the docs issue?

You can read

> Data resources do not have any customization settings available for their lifecycle. However, the lifecycle block is reserved for future versions.

and at least from v1.7.x, and as it's indicated also in the tutorial https://developer.hashicorp.com/terraform/tutorials/configuration-language/custom-conditions#add-a-postcondition, you can declare

```
data "aws_vpc" "app" {
  id = var.aws_vpc_id

  lifecycle {
    postcondition {
      condition     = self.enable_dns_support == true
      error_message = "The selected VPC must have DNS support enabled."      
    }
  }
}
```

### Proposal

Make some reference that you can customize as [resource](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle). A proposal could be something like

> Data resources can customize their lifecycle as [resource](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle)

**Comment by crw** [comment]
Thanks for this docs request!
