### ISSUE TITLE
Add missing documentation about the data source argument `filter`

### ISSUE THREAD

**Issue by dancer1325** [hashicorp/terraform#35244]
### Terraform Version

```shell
anything
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/data-sources#data-source-arguments

### What is the docs issue?

I do NOT see any reference / commentary about `filter` for `dataSource` 's arguments.

In the example https://developer.hashicorp.com/terraform/language/data-sources#data-source-arguments, it's indicated the argument as `filter` 

```
# Find the latest available AMI that is tagged with Component = web
data "aws_ami" "web" {
  filter {
    name   = "state"
    values = ["available"]
  }

  filter {
    name   = "tag:Component"
    values = ["web"]
  }

  most_recent = true
}
```

### Proposal

NOT sure in fact where this schema / arguments come from

**Comment by liamcervante** [comment]
Hi @dancer1325, thanks for filing this! The arguments for the specific data sources are documented by the providers directly rather than manually enumerated by the Terraform documentation. Here is the documentation for the `aws_ami` data source from the AWS provider: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami#filter.

**Comment by dancer1325** [comment]
> Hi @dancer1325, thanks for filing this! The arguments for the specific data sources are documented by the providers directly rather than manually enumerated by the Terraform documentation. Here is the documentation for the `aws_ami` data source from the AWS provider: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami#filter.

Then @liamcervante , dataSource's `filter` is an argument provider specific, right? NOT a built-in terraform meta argument, rght?

**Comment by liamcervante** [comment]
Hi @dancer1325, that is correct. The meta-arguments for data blocks are linked from this section of the documentation: https://developer.hashicorp.com/terraform/language/data-sources#meta-arguments. Any argument not listed as meta-argument is a provider-specific argument and will be documented by the relevant provider. Thanks!

**Comment by dancer1325** [comment]
Thank you so much for the clarification!! 🚀 

---

> The meta-arguments for data blocks are linked from this section of the documentation: https://developer.hashicorp.com/terraform/language/data-sources#meta-arguments. 

Then, as I reported https://github.com/hashicorp/terraform/issues/35246, it's properly reported as bug?

**Comment by liamcervante** [comment]
Yes, I think so. I suspect the documentation for that was written before we introduced the preconditions to data sources. The other ticket will be picked up by our tech writers during their usual triage. Thanks for finding and filing these issues!
