### ISSUE TITLE
aws_rds_cluster change in storage_type causes forced replacement

### ISSUE THREAD

**Issue by malatep** [hashicorp/terraform#35255]
### Terraform Version

```shell
terraform --version
Terraform v1.7.5
on linux_arm64
+ provider registry.terraform.io/carlpett/sops v1.0.0
+ provider registry.terraform.io/datadog/datadog v3.33.0
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/aws v4.41.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

n/a

### Expected Behavior

storage_type modifications should be done in place with no replacement

As per the docs https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#storage_type

> For Aurora DB clusters, storage_type modifications can be done in-place

### Actual Behavior

Terraform destroys the existing DB cluster and creates a new one with the specified `storage_type`

`+ storage_type                        = "aurora" # forces replacement`

### Steps to Reproduce

- create an aurora cluster with aws_rds_cluster
- modify the definition of the aws_rds_cluster and add storage_type
- run terraform plan and you will see a forces replacement on the cluster

### Additional Context

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Modifying.html#Aurora.Modifying.Settings

### References

https://github.com/hashicorp/terraform-provider-aws/issues/31431#issuecomment-1572168022

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
