### ISSUE TITLE
Security issue: .tfstate file should have 0600 permissions

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform#35256]
### Terraform Version

```shell
any
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

Because terraform stores secrets at .tfstate file it should have 0600 permission set.

### Actual Behavior

At the moment the .tfstate file has 0644 permission set.

### Steps to Reproduce

1. Deploy some resources onto the cluster
2. ls -la *.tfstate

**Comment by apparentlymart** [comment]
Thanks for this feature request, @EugenKon .

Although not exactly the same, I think this is the same general topic as https://github.com/hashicorp/terraform/issues/34949, so I'm going to close this one just to keep the discussion consolidated.

I did also share a method to control the permissions of files that Terraform creates in a comment in that issue.
