### ISSUE TITLE
Adding same aws_security_group_rule to multiple aws_security _group.

### ISSUE THREAD

**Issue by pradeepchhetri** [hashicorp/terraform#3525]
Hello,

I want to assign the same security group rule to multiple security groups. I am trying the things like this.

```
resource "aws_security_group_rule" "allow_all" {
    count = "${length(split(",", var.security_group_ids))}"
    
    type = "egress"
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]

    security_group_id = "${element(split(",", var.security_group_ids), count.index)}"
}
```
I am setting the variable in env.tfvars file like:

```
security_group_ids="${aws_security_group.sg1.id},${aws_security_group.sg2.id},${aws_security_group.sg3.id},${aws_security_group.sg4.id}"
```

But it fails with the error saying 
```
${aws_security_group.sg1.id}" (expecting "sg-..."
```

When i try to set the variable in resources.tf file, it fails with error saying
```
variable security_group_ids: cannot contain interpolations
```
I don't want to mention the same security_group_rule in multiple security groups. Can someone please help me.

**EDIT**:
I was playing with it and soon realized that the following things works but it looks like some kind of bug to me that above thing doesn't work.

```
resource "aws_security_group_rule" "allow_all" {
    count = "${length(split(",", var.security_group_ids))}"
    
    type = "egress"
    from_port = 0
    to_port = 65535
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]

    security_group_id = "${element(split(",", "${aws_security_group.sg1.id},${aws_security_group.sg2.id},${aws_security_group.sg3.id}"), count.index)}"
}
```
Can someone explain me why i am seeing such behaviour in the two configuration although they are nearly same.

**Comment by phinze** [comment]
Hi @pradeepchhetri - sorry for letting this one fall through the cracks. :disappointed: 

After reviewing the issue, the reason for your reported problem was that you were attempting to use interpolation within a `tfvars` file. The general strategy should work just fine, but interpolation can't work in `tfvars`.

Hope this helps! Feel free to follow up if you're still having troubles. :+1:
