### ISSUE TITLE
[New AWS Feature] aws_codebuild_webhook event trigger

### ISSUE THREAD

**Issue by susana-zhou1** [hashicorp/terraform#35258]
### Terraform Version

```shell
Terraform v1.8.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
```

### Use Cases

AWS has recently pushed a new feature that allows the use of codebuild as github self-hosted runners. 
Currently WORKFLOW_JOB_QUEUED is not supported in the aws_codebuild_webhook filters. 
Enables seamless integration between gihub actions and codebuild for use of private runners. 

### Attempted Solutions

Currently use github actions to trigger a codebuild. Which requires there to be a codebuild per action. This new feature allows codebuild to run what is queued from github actions, hence a single codebuild for all github actions on the repository.

### References

https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html

**Comment by apparentlymart** [comment]
Hi @susana-zhou1! Thanks for this feature request.

Unfortunately from your description it's not clear to me what you are asking for specifically. I understand that AWS Codebuild has this new feature, but I'm not sure what new Terraform feature you are anticipating that would make use of it. 

Can you say some more about what exactly you'd like to achieve with this new feature, and how exactly you'd like Terraform to change to support it? Thanks!
