### ISSUE TITLE
Azure AVD host pool argument update

### ISSUE THREAD

**Issue by wickerman2025** [hashicorp/terraform#35250]
### Terraform Version

```shell
Terraform v1.3.7
```

### Terraform Configuration Files

```terraform
...terraform config...
#Create a new Hostpool
resource "azurerm_virtual_desktop_host_pool" "test-avd-hostpool-preprod" {
  provider                 = azurerm.avd
  name                     = "VDPOOL-TEST-PREPROD-UKSOUTH-1"
  location                 = "uksouth"
  resource_group_name      = data.terraform_remote_state.level3-01-tfstate.outputs.rg-vdpool1-preprod-avd
  preferred_app_group_type = "RailApplications"
  type                     = "Pooled"
  load_balancer_type       = "BreadthFirst"
  maximum_sessions_allowed = 20
  custom_rdp_properties    = "drivestoredirect:s:;audiomode:i:0;videoplaybackmode:i:1;devicestoredirect:s:;camerastoredirect:s:*;usbdevicestoredirect:s:;audiocapturemode:i:1;redirectwebauthn:i:1;use multimon:i:1;redirectclipboard:i:1;redirectcomports:i:0;redirectlocation:i:0;redirectprinters:i:0;redirectsmartcards:i:0;autoreconnection enabled:i:1"
  tags = {
    name        = "avd-test",
    Owner = "WX",
    Managedby = "Terraform",
    environment = "preprod",
    resource    = "hostpool",
    application = "AVD",
    supportteam = "support Team"
  }
}
#generate a new token
resource "time_rotating" "test_avd_preprod_registration_expiration" {
  rotation_hours = 12
}

#manages the Registration Info for a Host Pool
resource "azurerm_virtual_desktop_host_pool_registration_info" "test-avd-preprod-hostpool-reg-info" {
  provider        = azurerm.avd
  hostpool_id     = azurerm_virtual_desktop_host_pool.test-avd-hostpool-preprod.id
  expiration_date = time_rotating.test_avd_preprod_registration_expiration.rotation_rfc3339
}
```

### Debug Output

 Error: expected preferred_app_group_type to be one of [Desktop None RailApplications], got RemoteApp
│ 
│   with azurerm_virtual_desktop_host_pool.test-avd-hostpool-preprod,
│   on test-hostpool-preprod.tf line 7, in resource "azurerm_virtual_desktop_host_pool" "test-avd-hostpool-preprod":
│    7:   preferred_app_group_type = "RemoteApp"

### Expected Behavior

Plan should of run. 

### Actual Behavior

Plan fails as the existing aurgument "RailApplications" no longer exists in Azure.

### Steps to Reproduce

Azure devops

### Additional Context

Pooled host pools have a preferred application group type that dictates whether users see RemoteApp or Desktop.
Microsoft it seems have removed the argument Railapplications and replaces it with Remoteapp. 

Raised an MS support ticket they said replace with Remoteapp. This argument does not exist. Seems others are having similar issues see link.

### References

[https://www.reddit.com/r/AZURE/comments/1cinh8v/avd_terraform_just_broke/](https://url.uk.m.mimecastprotect.com/s/sWFmC14OMUj52W4HktiiX?domain=reddit.com/)

**Comment by liamcervante** [comment]
Hi @wickerman2025, the Terraform providers are managed separately from the main Terraform binary. This appears to be a problem with the `azurerm` provider rather than Terraform itself. I will close this issue here and you should reopen directly within the `azurerm` repository: https://github.com/hashicorp/terraform-provider-azurerm/issues. Thanks!
