### ISSUE TITLE
Case sensitivity issue for azure resources

### ISSUE THREAD

**Issue by hboneta** [hashicorp/terraform#35299]
### Terraform Version

```shell
Terraform v1.8.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.106.1
```

### Terraform Configuration Files

```terraform
resource "azurerm_network_security_rule" "GS-251" {
  access                      = "Allow"
  destination_address_prefix  = "*"
  destination_port_range      = "22"
  direction                   = "Inbound"
  name                        = "SSH"
  network_security_group_name = "***********"
  priority                    = 300
  protocol                    = "TCP"
  resource_group_name         = "********"
  source_address_prefixes     = [*************]
  source_port_range           = "*************"
```

### Debug Output

Error: expected protocol to be one of ["*" "Tcp" "Udp" "Icmp" "Ah" "Esp"], got TCP
│
│   with azurerm_network_security_rule.GS-255,
│   on main.aztfexport.tf line 2083, in resource "azurerm_network_security_rule" "GS-255":
│ 2083:   protocol                    = "TCP"

### Expected Behavior

Should accept the UPPER value for the protocol field as it is the one azure applies when configuring/provisioning through portal or other means.

### Actual Behavior

See Debug Output requiring the value to be changed to Caps ("Tcp") instead of UPPER ("TCP").  If the tf code is changed to Caps to overcome the error, terraform apply would show up as an actual change to the azure resource (security rule) at apply time.  Said change is transparent to functionality, but introduces significant inconvenience in the form of Change Requests and additional testing before applying vs. getting the "No changes. Your infrastructure matches the configuration." message.

### Steps to Reproduce

terraform plan

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
