### ISSUE TITLE
EC2 Instance Size Change with Typo Not Reverting to Running State in Terraform AWS

### ISSUE THREAD

**Issue by Dimopanagos** [hashicorp/terraform#35297]
### Terraform Version

```shell
Terraform v1.8.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.52.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region                   = "us-east-1"
  shared_credentials_files = ["~/.aws/temp_credentials"]
  profile                  = "default"
}

resource "aws_instance" "my_ubuntu" {
  ami           = "ami-04b70fa74e45c3917"
  instance_type = "t3.micro"
  key_name      = "john_mac_os_key_main_key"

  tags = {
    Name    = "My-Ubuntu-Server"
    Owner   = "John"
    Project = "Phoenix"
  }
}

resource "aws_instance" "my_amazon" {
  ami           = "ami-00beae93a2d981137"
  instance_type = "t3.micro"

  tags = {
    Name  = "My-AmazonLinux-Server"
    Owner = "John"
  }
}

```

### Debug Output

│ Error: updating EC2 Instance (i-086443bd9d265611b) type: modifying EC2 Instance (i-086443bd9d265611b) InstanceType (t3.smalle) attribute: InvalidParameterValue: The following supplied instance types do not exist: [t3.smalle]

### Expected Behavior

It should revert and Start the server on "Running" state

### Actual Behavior

Right now, even if you remove the typo and add the previous working size, the server do not start, its remaining "stopped" 

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

When working with Terraform AWS, if you create an EC2 server and later change its size but make a typographical error, for example, entering "t3.smalle" instead of "t3.small", Terraform does not show an error during the plan phase. However, when you apply the changes, it stops the server and then displays the following error:
`│ Error: updating EC2 Instance (i-086443bd9d265611b) type: modifying EC2 Instance (i-086443bd9d265611b) InstanceType (t3.smalle) attribute: InvalidParameterValue: The following supplied instance types do not exist: [t3.smalle]
`
The server remains in a stopped state, and even if you revert to the correct size it had before and apply the changes again, the server continues to stay stopped.
The only way to make terraform to start the server again, is to put another size that exist, not the previous working one, but some another (new).

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by Dimopanagos** [comment]
Thanks added to terraform aws provider github.
https://github.com/hashicorp/terraform-provider-aws/issues/37849
