### ISSUE TITLE
Terraform test does not override variable passed via cli when variable is also statically defined

### ISSUE THREAD

**Issue by manuelvsousa** [hashicorp/terraform#35309]
### Terraform Version

```shell
Terraform v1.8.5
```

### Terraform Configuration Files

```terraform
variables {
  project_id = "inside"
}

run "gcp_test" {
  command = plan

  assert {
    condition = (
      var.project_id == "outside"
    )
    error_message = "wrong project_id"
  }
}

```

### Debug Output

`terraform test -filter="tests/test.tftest.hcl" -var='project_id=outside'`

```
tests/gcp.tftest.hcl... in progress
  run "gcp_test"... fail
╷
│ Error: Test assertion failed
│
│   on tests/gcp.tftest.hcl line 64, in run "gcp_test":
│   64:     condition = (
│   65:       var.project_id == "outside"
│   66:     )
│     ├────────────────
│     │ var.project_id is "inside"
│
│ wrong project_id
╵
tests/gcp.tftest.hcl... tearing down
tests/gcp.tftest.hcl... fail

Failure! 0 passed, 1 failed.
```

### Expected Behavior

When running the test with the -var parameter, project_id should be overridden and observable inside the run blocks.

### Actual Behavior

project_id matched the string "inside" when it should match "outside"

### Steps to Reproduce

`terraform test -filter="tests/test.tftest.hcl" -var='project_id=outside'`

### Additional Context

I observed that the cli argument only gets considered by terraform if the variable project_id is undefined in the test file. This is inconsistent with the behaviour observed when using the -var flag with `terraform plan` and `terraform apply`

**Comment by liamcervante** [comment]
Hi @manuelvsousa, thanks for filing this.

Terraform is behaving as documented here: https://developer.hashicorp.com/terraform/language/values/variables#variable-precedence-within-terraform-tests

There's a distinction between variables defined within Terraform configuration files, and the variable values assigned within Terraform test files. Within the configuration files one is providing default values for variables, and the actual value is always expected to be provided externally hence all external forms of variable value input (including Terraform test files) override the default value. Within Terraform test files the intent is that you are providing an actual concrete value for these variables for the test cases defined within the file. For this reason, the more local values take precedence.
