### ISSUE TITLE
terraform import with for-each is not working as expected

### ISSUE THREAD

**Issue by umamahesh610** [hashicorp/terraform#35316]
### Terraform Version

```shell
Terraform v1.8.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v5.53.0
```

### Terraform Configuration Files

```
import {
   for_each = var.import_list
  to = aws_identitystore_group_membership.tt-AddUsertoGroup [each.key]
  id = each.value
}

resource "aws_identitystore_group_membership" "tt-AddUsertoGroup" {
  for_each = local.yaml_input

  identity_store_id = local.sso_id
  group_id      = lookup(local.group_id_map, each.value.group_name)
    member_id = lookup(local.user_id_map, each.value.user_name)
}

```

### Debug Output

unable to provide the gist file. 

### Expected Behavior

import the resources provided in the inputs. 

Observation: Import block is working fine when resource block doesn't have any for-each i.e for one resource. 

### Actual Behavior

Error : 
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Configuration for import target does not exist
│
│ The configuration for the given import
│ aws_identitystore_group_membership.tt-AddUsertoGroup["group1-user1@gmail.com"]

### Steps to Reproduce

1. terraform init
2. terraform plan
sample inputs
varaibles: 
variable "import_list" {
  type = map(string)
  default = {
    "group1-user1@gmail.com" = "d-9f670df574/a1c37d8a-e0b1-70be-e4b3-3cfefd182e87"
  }

}

yaml file: 
#AWSTemplateFormatVersion: 2010-09-09
#Description: This templates associate the user to the group
 TerraformGroup-user2@gmail.com:
   Type: "Membership"
   group_name: "TerraformGroup"
   user_name: "user2@gmail.com"

**Comment by liamcervante** [comment]
Hi @umamahesh610, are you able to share the exact value of the `local.yaml_input` field? The error message here is Terraform stating that there is no `tt-AddUsertoGroup` resource with the `group1-user1@gmail.com` instance key. Based on the YAML file you provided, it seems like Terraform is correct - I don't see that email address anywhere within the YAML file.

They keys for your import block must match the keys for the resource you want to import.

**Comment by umamahesh610** [comment]
sorry, my bad. thanks for pointing out.  Import is working as expected after configuring the yaml input .

**Comment by umamahesh610** [comment]
closing the issue
