### ISSUE TITLE
Remove reference to tutorial NOT published

### ISSUE THREAD

**Issue by dancer1325** [hashicorp/terraform#35317]
### Terraform Version

```shell
*
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/providers/requirements

### What is the docs issue?

In this page, you can read

> Hands-on: Try the [Perform CRUD Operations with Providers](https://developer.hashicorp.com/terraform/tutorials/providers/provider-use) tutorial.

But that page is NOT published anymore, and there are [discussions in the forum](https://discuss.hashicorp.com/t/tutorial-perform-crud-operations-with-providers/38833), reporting that it's pretty otudated. 
Repo tutorial: https://github.com/hashicorp/learn-terraform-hashicups-provider

### Proposal

Remove directly the commentary at all about that tutorial

~~Hands-on: Try the [Perform CRUD Operations with Providers](https://developer.hashicorp.com/terraform/tutorials/providers/provider-use) tutorial~~

**Comment by crw** [comment]
Thanks for the request! I will pass this on to the docs team for review.
