### ISSUE TITLE
vSphere: Crash on empty disk specification

### ISSUE THREAD

**Issue by mkuzmin** [hashicorp/terraform#3534]
On a minimal configuration with empty disk specification like
```
resource "vsphere_virtual_machine" "vm" {
  name   = "vm1"
  vcpu   = 1
  memory = 512
  network_interface {
    label = "VM Network"
  }
  disk {
// nothing
  }
}
```
Terraform crashes with
```
panic: interface conversion: interface is nil, not map[string]interface {}
2015/10/17 19:07:51 [DEBUG] terraform-provider-vsphere: 
2015/10/17 19:07:51 [DEBUG] terraform-provider-vsphere: goroutine 66 [running]:
2015/10/17 19:07:51 [DEBUG] terraform-provider-vsphere: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineCreate(0xc208174180, 0xc2e020, 0xc2082073b0, 0x0, 0x0)
2015/10/17 19:07:51 [DEBUG] terraform-provider-vsphere:         /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:283 +0x11ab
```
Full log: https://gist.github.com/mkuzmin/ead63726183e3ba072bc

Need checking for `size` parameter presence, or even better - hardcode a default value of 40 Gb, the same as native vSphere client does.

**Comment by mkuzmin** [comment]
So, the whole `disk` section can be optional.

**Comment by chrislovecnm** [comment]
@mkuzmin what is the status on this?

**Comment by mkuzmin** [comment]
This is a bug, and it has to be fixed. But in coming weeks I'm not going to work on this.

**Comment by chrislovecnm** [comment]
@mkuzmin no worries. Blocker / non-blocker?

**Comment by chrislovecnm** [comment]
@mkuzmin what version are you running?  Line numbers are getting messy

**Comment by chrislovecnm** [comment]
@mkuzmin what is the status on this?

**Comment by chrislovecnm** [comment]
@jen20 @catsby Can we close this please??

**Comment by chrislovecnm** [comment]
@stack72 can I get a close 😄

**Comment by stack72** [comment]
Hi @mkuzmin 

Nt sure what the status is on this - this hasn't been able to be recreated. IF you still get the issue, please add a comment here and we can reopen it

Thanks

Paul
