### ISSUE TITLE
Error when applying changes to module  google_bigquery_dataset_access.dset_access

### ISSUE THREAD

**Issue by anandnreddy** [hashicorp/terraform#35340]
### Terraform Version

```shell
Terraform v1.1.6
on windows_amd64
```

### Terraform Configuration Files

```# # see: https://terraform-docs.io/user-guide/configuration/#version
# version: ">= 0.10, < 0.12"

# see: https://terraform-docs.io/user-guide/configuration/#formatters
formatter: markdown table

header-from: description.md
# footer-from: footer.md

# see: https://terraform-docs.io/user-guide/configuration/#sections
sections:
  show:
    - header
    - inputs
    - providers
    - modules
    - footer

# # see: https://terraform-docs.io/user-guide/configuration/#sort
sort:
  enabled: true
  by: required

settings:
  indent: 4
  escape: false
  default: false
  required: false
  type: true
```

### Debug Output

this bug is happening when we run it on tekton pipeline.

### Expected Behavior

changes should have been made to access using the dset_access module.

### Actual Behavior

When applying changes to module.bq-dataset-access["user1"].google_bigquery_dataset_access.dset_access,
provider "provider["registry.terraform.io/hashicorp/google"]" produced an unexpected new value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

terraform apply

### Additional Context

We are trying to run this terraform via tekton pipeline and this is throwing the error.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
