### ISSUE TITLE
vSphere: make 'vcpu' and 'memory' parameters optional

### ISSUE THREAD

**Issue by mkuzmin** [hashicorp/terraform#3535]
`vcpu` and `memory` parameters are mandatory, but it would be better to make them optional.
- In case of cloning from a template - inherit the values from a base VM.
- On new VM creation - hardcode default values of 1 CPU and 4 Gb of RAM - the same way as native vSphere client does.

**Comment by mkuzmin** [comment]
By the way, "vcpu" word looks weird. I'd rename it to `cpu` or `cpu_number`.

**Comment by tkak** [comment]
Thank you for your comments. I think the improvement would be better. And, it's good to rename `vcpu` parameter. I think `cpu_number` is easier to understand.

**Comment by chrislovecnm** [comment]
@mkuzmin vcpu definitely is a vmware thing btw.  If I can be picky how about:

num_cpu or num_of_cpu

**Comment by chrislovecnm** [comment]
@mkuzmin do we need to keep it open??

**Comment by chrislovecnm** [comment]
@jen20 @catsby can we close this??

**Comment by chrislovecnm** [comment]
@stack72 can I get a close 😄

**Comment by chrislovecnm** [comment]
@jen20 @stack72 @phinze please close

**Comment by stack72** [comment]
Closed as PR open for this now
