### ISSUE TITLE
Terraform catchpoint resource not working

### ISSUE THREAD

**Issue by LokhandeLata** [hashicorp/terraform#35374]
### Terraform Version

```shell
Terraform v1.8.5
on linux_amd64
```

### Terraform Configuration Files

```terraform {
  required_providers {
    catchpoint = {
      source  = "catchpoint/catchpoint"
      version = "1.1.0"
    }
  }
  required_version = ">= 1.2.0"
}

provider "catchpoint" {
  api_token = "your_token"
}
resource "ssl_test" "chopper" {
  test_name     = "SSLTF"
  provider      = catchpoint
  division_id   = User_division_id
  product_id    = User_product_id
  folder_id     = User_folder_id
  monitor       = "ssl"
  test_location = "www.google.com"
  end_time      = "2024-10-30T04:59:00Z"
}
```

### Debug Output

╷
│ Error: 400 bad request
│ 
│   with ssl_test.chopper,
│   on main.tf line 14, in resource "ssl_test" "chopper":
│   14: resource "ssl_test" "chopper" {
│ 
╵
2024-06-22T17:56:11.720+0530 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-06-22T17:56:11.728+0530 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/catchpoint/catchpoint/1.1.0/linux_amd64/terraform-provider-catchpoint_v1.1.0 pid=223383
2024-06-22T17:56:11.728+0530 [DEBUG] provider: plugin exited

### Expected Behavior

Config file is vaild, api_token is valid so `terraform apply` cmd should work.

### Actual Behavior

Config file is vaild, api_token is valid but still it is failing at the time of` terraform apply` cmd.

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply

### Additional Context

terraform {
  required_providers {
    catchpoint = {
      source  = "catchpoint/catchpoint"
      version = "1.1.0"
    }
  }
  required_version = ">= 1.2.0"
}

provider "catchpoint" {
  api_token = "User_catchpoint_token"
}
resource "ssl_test" "chopper" {
  test_name     = "SSLTF"
  provider      = catchpoint
  division_id   = User_division_id
  product_id    = User_product_id
  folder_id     = User_folder_id
  monitor       = "ssl"
  test_location = "www.google.com"
  end_time      = "2024-10-30T04:59:00Z"
}

**Comment by liamcervante** [comment]
Hi @LokhandeLata, thanks for filing this! Based on the error message, I think this is likely to be an issue with the `checkpoint` provider rather than Terraform itself. The individual providers are managed separately, I think the checkpoint provider is managed within https://github.com/CheckPointSW/terraform-provider-checkpoint.

I'm going to close the issue here, but I'd encourage you to open an issue directly with the Checkpoint provider team.

Thanks!

**Comment by LokhandeLata** [comment]
Thanks for your email! I checked that link but there is no create issue
option listed in that repo. Is there any other way where I can connect with
that team?

Regards,
Lata

**Comment by liamcervante** [comment]
I think you should be able to file a new issue here: https://github.com/CheckPointSW/terraform-provider-checkpoint/issues/new

**Comment by LokhandeLata** [comment]
Thanks!

**Comment by LokhandeLata** [comment]
Above repo is for `checkpoint repo`, my issue is for https://github.com/catchpoint/terraform-provider-catchpoint

**Comment by liamcervante** [comment]
Ah yeah, apologies! Yeah, I totally misread the provider name!

You're right, they don't seem to allow external users to file issues via the Github repository. Unfortunately they're an entirely external company / provider so I don't have any special access either. You could try raising an issue in the Hashicorp discuss forum and tagging this provider to see if anyone else has been able to get in touch.

Alternatively, if you have an enterprise or support contract with Catchpoint directly, you might be able to get in touch with them that way.

@crw (our community manager), are you aware of any other paths of escalation we have for external / partner providers?

**Comment by crw** [comment]
In this case I do not think there are internal escalations, although I can check with the partnerships team. In any case, @LokhandeLata, if you are a customer of Catchpoint (or even if you are not) I would escalate through their support channels.
