### ISSUE TITLE
Default values in provider functions

### ISSUE THREAD

**Issue by kimdre** [hashicorp/terraform#35375]
### Terraform Version

```shell
Terraform v1.8.5
on linux_amd64
```

### Use Cases

Omit arguments in provider functions when the default is already the correct value.

e.g. My [provider function](https://registry.terraform.io/providers/germanbrew/dotenv/latest/docs/functions/get_by_key#example-usage) has a filename argument that often is the same value: `.env`

### Attempted Solutions

Setting defaults to provider functions in the Plugin Framework does not work or I was not able to.

### Proposal

Provide a additional `Default` key to the function definition to specify a default value to a parameter:

```go
func (r ExampleFunction) Definition(_ context.Context, _ function.DefinitionRequest, resp *function.DefinitionResponse) {
	resp.Definition = function.Definition{
		Summary: "Example function",
		MarkdownDescription: "Foo bar",
		Parameters: []function.Parameter{
			function.StringParameter{
				Name: "filename",
				MarkdownDescription: "Path to the dotenv file",
				// Add this 
				Default: ".env",
			},
		},
		Return: function.StringReturn{},
	}
}
```

**Comment by jbardin** [comment]
Hi @kimdre,

The default values would be handled by the wrapper provided in the plugin framework, not by Terraform. Terraform is only concerned with making the RPC call, and does not know about the actual function implementation. You can find the framework project repository here: https://github.com/hashicorp/terraform-plugin-framework

Thanks!
