### ISSUE TITLE
It was not mentioned that cidr_blocks and security_groups are ORed.

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform#35398]
### Terraform Version

```shell
NA
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#ingress

### What is the docs issue?

It does not mention, that separate rules are created for `security_groups` and `cidr_blocks`

```
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    security_groups = "${var.client_vpn_sg}"
    cidr_blocks = local.allowlist_ip
  }
```
I suppose by mistake that inbound traffic should be from `cidr_blocks` **AND** from `security_groups`. But they are processed separately.

### Proposal

Doc should clarify this.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
