### ISSUE TITLE
Change behaviour of working directory please

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#3540]
When running terraform commands, you specify a directory to search for tf files.

This is fine, but I have hundreds upon hundreds of tf files, and it just does a glob of the directory specified.

It would be much more helpful and manageable for laying out stuff in a sensible way, for terraform to glob all subdirs of the directory specified, and load all tf files it finds.

**Comment by apparentlymart** [comment]
@gtmtech the intent is that complicated configs would get broken down into separate [Terraform modules](https://terraform.io/docs/configuration/modules.html). It is a common pattern for a config to have child modules in subdirectories, so scanning down recursively would break that pattern.

Could you use modules to describe your infrastructure in different parts?

**Comment by gtmtech** [comment]
I guess... but its kind of against the adage "convention over configuration" and has the following disadvantages:

* all other projects seem to use a directory structure just fine (so expected)
* the learning curve is higher for writing module definitions rather than just having a directory structure
* more code lines (waste)
* more directories later = even more module declarations
* makes refactoring even more complicated

I dont know, maybe its the "terraform way", I just think you're making easy things complicated

**Comment by mitchellh** [comment]
We do view a single folder of Terraform files as the correct logical unit of application. "Directories" are viewed as separate modules. However, I also sympathize with your use case and offer a simpler solution: there is an open issue to allow "include" functionality in Terraform configs. If we support that we could presumably support including from other directories and that would allow you to do this.

I think automatically loading subdirs isn't in the plan for Terraform.

**Comment by gtmtech** [comment]
That would be awesome @mitchellh and be very useful. In my role I have seen many companies different terraform configs, and the lack of this IMO promotes ugly codebases and needlessly complicated outputs/inputs using the current modules approach. 👍

**Comment by gtmtech** [comment]
The issue which mitchellh was referring to above is #1478 for future readers of this issue. Sadly the conversation there is locked, and as it is almost 2 years old, It may not be a high priority for the terraform team. So sadly there is no nice way of structuring my 1819 .tf terraform files other than writing my own wrapper for now. (Modules is not the answer). I suspect most other users of terraform dont work on repositories quite so large and so the usecase isnt apparent to them.

**Comment by o6uoq** [comment]
@gtmtech I believe the "Terraform way" is the right way - minimalist and functional.

I think the real question here is - where and what and why do you have 1819 .tf files?! Maybe there is some refactoring which can be applied to your workflow, rather than the silver bullet of `-R`

**Comment by gtmtech** [comment]
@o6uoq . I wrote a wrapper (which is sad, but it works) to allow me to lay out resources in directory structures. It works fine and the code is much more manageable IMO. Its sad that nobody else sees it, but perhaps everyone else is working on a very small number of resources. I use modules as well now to achieve some of it, but modules are not the solution as they just multiply the LOC for no reason in some cases with inputs and outputs that otherwise dont need to exist. 

Some teams and companies I work with suffer from having many disparate resources per terraform file, and then over time because no team discipline is enforced, you end up with no consistency, and lead to wasting time thinking that resources dont exist when they do etc. 

Some other teams mandate one tf file per resource which makes finding things a lot easier, but multiplies the number of files quite enormously. Personally I like this approach with directory structure layering the resources as well - it's a shame this cant be accommodated by default, but hey. 

I have over 10,000 terraform resources, and I dont really find single directory + modules works for me. If anyone is interested in the wrapper which allows a directory structure let me know, I can pop it on pastebin.

**Comment by nniehoff** [comment]
@gtmtech I have the same problem.  I'm starting to write my own wrapper, but would be interested in seeing yours.

**Comment by o6uoq** [comment]
@gtmtech Terraform is a very popular on GitHub by stars, forks and contributors. Have you created an issue which outlines in more granular detail your requirements and proposed solution? It would be a good litmus test to see if your idea and implementation has legs or not.
