### ISSUE TITLE
Terraform state list should use quotes for keys

### ISSUE THREAD

**Issue by jakubgs** [hashicorp/terraform#35415]
### Terraform Version

```shell
v1.8.5
```

### Use Cases

I want to be able to run commands on output from `terraform state list` using `xargs`, for example:
```
 > terraform state list | grep cloudflare_record | xargs -d$'\n' -I{} echo terraform state show '{}'  
terraform state show cloudflare_record.host[node-01.dc-01.app.test]
terraform state show cloudflare_record.host[node-01.dc-02.app.test]
terraform state show cloudflare_record.host[node-01.dc-03.app.test]
```
But since the keys are not quoted I get an error instead:
```
This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify 
the address to reference a specific instance.
Error parsing instance address: cloudflare_record.host[node-01.dc-01.app.test]
```

### Attempted Solutions

One can use regex to fix this, but it's not very ergonomic.
```
 > terraform state list | grep cloudflare_record | sed 's/\[[a-z0-9.-]+\]/\["\\1"\]/' | xargs -d$'\n' -I{} echo terraform state show '{}'  
```

### Proposal

Either quote the keys by default, or add a `--quite-keys`/`-q` flag that allows for automatic quoting of keys.

**Comment by apparentlymart** [comment]
Hi @jakubgs! Thanks for reporting this. 

Could you also share the output of just `terraform state list` (without the subsequent transformations)? I'd like to understand how Terraform is behaving independent of the subsequent commands you are piping its output through, since that's the only part of this we could change in this repository.

Thanks!

**Comment by jakubgs** [comment]
Oh, I see what you mean, the quotes are there:
```
 > terraform state list
cloudflare_record.host["node-01.dc-01.app.test"]
cloudflare_record.host["node-01.dc-02.app.test"]
cloudflare_record.host["node-01.dc-03.app.test"]
```
It's just that using `xargs` strips them:
```
 > terraform state list | xargs -I{} echo {}
cloudflare_record.host[node-01.dc-01.app.test]
cloudflare_record.host[node-01.dc-02.app.test]
cloudflare_record.host[node-01.dc-03.app.test]
```
It appears this is a quirk of `xargs` itself is what removes the quotes, and terraform does have them.

My mistake. It appears this can be remedied by using null character instead of newline:
```
 > terraform state list | tr '\n' '\0' | xargs -0 -I{} echo {}
cloudflare_record.host["node-01.dc-01.app.test"]
cloudflare_record.host["node-01.dc-02.app.test"]
cloudflare_record.host["node-01.dc-03.app.test"]
```
Annoying but workable. Cheers.
