### ISSUE TITLE
Interpolation: convert case functions

### ISSUE THREAD

**Issue by makered** [hashicorp/terraform#3542]
Not mentioned at https://terraform.io/docs/configuration/interpolation.html so thought I'd ask, is there a way to convert variable case at interpolation time?

Thanks

**Comment by sl1pm4t** [comment]
I also looked for this recently and couldn't find it. Would be useful for Google Compute related resource attributes which all have to be in lower case.

**Comment by apparentlymart** [comment]
Nice idea! If someone wants to work on this, adding [interpolation functions](https://github.com/hashicorp/terraform/blob/master/config/interpolate_funcs.go) can make a good "my first Terraform patch".

**Comment by apparentlymart** [comment]
Change from #3558 was merged
