### ISSUE TITLE
aws_launch_template require parameter "user_data_base64" for passing compressed file

### ISSUE THREAD

**Issue by vthelu** [hashicorp/terraform#35438]
### Terraform Version

```shell
n/a
```

### Use Cases

aws_ec2_instance supports
aws_launch_configuration supports

### Attempted Solutions

new feature request

**Comment by crw** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by vthelu** [comment]
Thank you
