### ISSUE TITLE
tf apply fails for an existing mssql resource which is being updated

### ISSUE THREAD

**Issue by sanalkumarp** [hashicorp/terraform#35430]
### Terraform Version

```shell
1.0.8
```

### Terraform Configuration Files

```
resource "azurerm_mssql_server" "sqldatabaseserver_02" {
  name                          = "app-${var.env}-mssql"
  resource_group_name           = azurerm_resource_group.app_rg.name
  location                      = azurerm_resource_group.app_rg.location
  version                       = "12.0"
  public_network_access_enabled = false

  azuread_administrator {
    azuread_authentication_only = true
    login_username              = var.app_mi_name
    object_id                   = var.app_mi_objectid
  }

  identity {
    type         = "SystemAssigned, UserAssigned"
    identity_ids = [data.azurerm_user_assigned_identity.app_mi.id]
  }

  tags = local.app_tags

  primary_user_assigned_identity_id            = data.azurerm_user_assigned_identity.app_mi
  transparent_data_encryption_key_vault_key_id = azurerm_key_vault_key.sql_key.id
}
```

### Debug Output

https://gist.github.com/sanalkumarp/1ff37542d3f73ff275bf438df88ff9a3

### Expected Behavior

The change in tf plan is just to update the tag of the sql instance which should succeed

### Actual Behavior

tf apply fails with the below error:
performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidResource: The resource definition is invalid.

The content length of the PUT request body is 0 and it looks like an empty body is sent in the PUT request to ARM and it rejects the request with 400 Bad Request error.

### Steps to Reproduce

terraform apply

**Comment by crw** [comment]
Hello @sanalkumarp, this appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers. Thanks!
