### ISSUE TITLE
Is there any alternative way to matrix strategy in github action 

### ISSUE THREAD

**Issue by rajammavenkatesh** [hashicorp/terraform#35456]
### Terraform Version

```shell
AWS provider

hashicorp/aws: 5.34.0
hashicorp/awscc: 0.69.0
```

### Use Cases

We are using Terraform as IaC in our organization. I am facing an issue where we need to deploy the same set of resources for multiple groups and divisions. For example, I have 'ABC' as a group, which contains divisions 1, 2, 3, 4, and 5. I need to deploy to all divisions at the same time. Currently, I am using GitHub Actions with a feature called matrix, but it creates separate jobs and the billing cost is high. I want to reduce the cost of running GitHub Actions

### Attempted Solutions

          group=${GROUPS}
          divisions=${DIVISIONS}

          divisions=${divisions#\[}
          divisions=${divisions%\]}
          IFS=',' read -r -a array <<< "$divisions"

          task () {
            
              echo "Starting task for the $2 division"

              cd ./infra/terraform/scheduleQueryStack
              terraform workspace select -or-create "${1}_${2}_schedulequery_stack_test"

              export TF_VAR_environment=${{ inputs.Stage }}
              export TF_VAR_group=$1
              export TF_VAR_region=${{ inputs.Region }}
              export TF_VAR_division=$2

              terraform apply --auto-approve

              echo "Task for the $2 division completed"             
          }
          
          # Array to store PIDs of background tasks
          pids=()
          # Max number of background tasks can be run at a time is 4.
          max_concurrent=4

          remove_empty_pids() {
            local new_pids=()
            for pid in "${pids[@]}"; do
              if [ -n "$pid" ]; then
                new_pids+=("$pid")
              fi
            done
            pids=("${new_pids[@]}")
          }

          # Function to list all running background tasks
          list_background_tasks() {
            echo "PIDs of background running tasks. ${pids[@]}"
            echo "Current total number of PIDs: ${#pids[@]}"
            for pid in "${pids[@]}"; do
              if kill -0 "$pid" 2>/dev/null; then
                echo "Task with PID $pid is running"
              else
                echo "Task with PID $pid has completed"
                # If a background task has completed, it will be removed from the array
                pids=("${pids[@]/$pid}")
                remove_empty_pids
                echo "$pid PID removed from the PIDs array"
              fi
            done
          }

          # Run tasks in parallel using background processes and save their PIDs
          for division in "${array[@]}"; do

            # Check if the number of background tasks has reached the limit
            while [ ${#pids[@]} -ge $max_concurrent ]; do
              list_background_tasks
              sleep 60
              echo "Sleeping for a minute to complete the background tasks"
            done

            # Run the task in the background
            task "$group" "$division" &
            # Get the process ID of the task and add PID of background tasks to array. 
            pids+=($!)
          done

          # Function to wait for all background tasks to complete
          wait_for_background_tasks() {
            for pid in "${pids[@]}"; do
              wait "$pid"
            done
          }

          # Wait for all background tasks to complete
          wait_for_background_tasks

          echo "All tasks completed"

**Comment by kmoe** [comment]
Thanks for writing this up. It would be best as a question in the forums at https://discuss.hashicorp.com/c/terraform-core/27 as this issue tracker is used for bugs and enhancements in Terraform Core itself.

**Comment by rajammavenkatesh** [comment]
@kmoe @hornbeck 
No one responded  from past 8 days 
https://discuss.hashicorp.com/t/we-are-using-terraform-as-iac-in-our-organization-i-am-facing-an-issue-where-we-need-to-deploy-the-same-set-of-resources-for-mu/68656

**Comment by crw** [comment]
This repository is to report issues and feature requests for the Terraform CLI. Unfortunately, the maintainers do not have the bandwidth or even necessarily the expertise in the various types of services available to answer general or specific questions around implementation challenges. You may want to try other forums such as Reddit or StackOverflow and seek answers from a variety of communities including those who are experts in AWS and GitHub Actions or whichever other technologies make sense in this context. Thanks for getting started with Terraform, I am sure there is a solution out there even if you are the first person to discover it!
