### ISSUE TITLE
Difference In Functionality Between Terraform Plan/Apply and Terraform Test for Detecting/Converting JSON Objects in Resource Properties

### ISSUE THREAD

**Issue by Jpk518** [hashicorp/terraform#35451]
### Terraform Version

```shell
1.9.2
```

### Terraform Configuration Files

```terraform
# main.tf
data "aws_iam_policy_document" "test" {
  statement {
    effect = "Allow"
    actions = ["*"]
    resources = ["*"]
  }
}

resource "aws_vpc_endpoint" "test" {
  vpc_id = var.vpc_id
  service_name =  "com.amazonaws.ca-central-1.s3"
  policy = data.aws_iam_policy_document.test.json
}

variable "vpc_id" {}
```

```terraform
# main.tftest.hcl
mock_provider "aws" {}

variables {
  vpc_id = "vpc-123"
}

run "test" {
  command = plan
  assert {
    condition     = length(aws_vpc_endpoint.test) > 0
    error_message = "Test Failure."
  }
}
```

### Debug Output

N/A

### Expected Behavior

> terraform test
```
main.tftest.hcl... in progress
  run "test"... pass
main.tftest.hcl... tearing down
main.tftest.hcl... pass
```

> terraform plan
```hcl
  # aws_vpc_endpoint.test will be created
  + resource "aws_vpc_endpoint" "test" {
      + arn                   = (known after apply)
...
      + policy                = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = "*"
                      + Effect   = "Allow"
                      + Resource = "*"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
...
      + vpc_id                = "vpc-123"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

> terraform test
```
main.tftest.hcl... in progress
  run "test"... fail
╷
│ Error: "policy" contains an invalid JSON: invalid character 'e' looking for beginning of value
│ 
│   with aws_vpc_endpoint.test,
│   on main.tf line 12, in resource "aws_vpc_endpoint" "test":
│   12:   policy            = data.aws_iam_policy_document.test.json
│ 
╵
main.tftest.hcl... tearing down
main.tftest.hcl... fail

Failure! 0 passed, 1 failed.
```

> terraform plan
```hcl
  # aws_vpc_endpoint.test will be created
  + resource "aws_vpc_endpoint" "test" {
      + arn                   = (known after apply)
...
      + policy                = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = "*"
                      + Effect   = "Allow"
                      + Resource = "*"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
...
      + vpc_id                = "vpc-123"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce

1. terraform init
2. terraform test

### Additional Context

When running terraform plan/apply, terraform will automatically detect data structures as JSON object and convert them using jsonencode() as seen in the plan. But when running terraform test, the command fails as it does not do the same conversion on the resource property.

The test will pass if we manually wrap the property in jsonencode() that the terraform plan adds implicitly.

**Comment by liamcervante** [comment]
Hi @Jpk518, as you are using a mock provider the behaviour you are seeing is somewhat expected. Terraform test doesn't know anything about the underlying resources that it is mocking, in this case the fact that the `json` attribute of the `aws_iam_policy_document` returns a JSONisified version of the statement is not something that Terraform itself is actually aware of. The error itself is a result of the validation of the AWS provider (which is still available to the mock) checking that we it is a JSON object being provided.

The default behaviour of the mock provider is to return a simple random string for any computed string resources that are needed within the configuration. You must override this behaviour in cases where a specific value or format is required. In this case either a [`mock_data`](https://developer.hashicorp.com/terraform/language/tests/mocking#mock-provider-data) block or an [`override_data`](https://developer.hashicorp.com/terraform/language/tests/mocking#override_data) block.

The following change to your mock provider should unblock you here:

```
mock_provider "aws" {
    override_data {
        target = data.aws_iam_policy_document.test
        values = {
            json = "{\"Statement\":[{\"Action\":\"*\",\"Effect\":\"Allow\",\"Resource\":\"*\"}]}"
        }
    }
}
```

You can see we are targeting the data source directly, and providing the expected JSON value that data source would be returning if we were actually in contact with the real AWS provider. Unfortunately, we must provide the raw JSON string directly as functions such as `jsonencode` are not yet available to the mocking framework.

Thanks!
