### ISSUE TITLE
Feature request: Allow setting default values for individual object fields (aka nested field definitions)

### ISSUE THREAD

**Issue by ilsaloving** [hashicorp/terraform#35452]
### Terraform Version

```shell
1.8.5
```

### Use Cases

Currently, as part of creating a variable of type Object, your only option for defaults is an entire object with the various fields set. And when instantiating a new object, you _must_ include every field in the object.
eg:
```
variable "config" {
  type = object({
    package  = string,
    freeze   = bool,
    variable = map(string),
    }
  )

<some block>  
 config={package="X", freeze=false, variable={}} # Ok
 config={package="X"} # Error
<EOB>
```

It would be helpful if I could allow default values for the individual fields in that object so not all need to be set

```
variable "config" {
  type = object({
    package  = string
    freeze   = {
      type=bool,
      description="Heck, why not this too while we're at it..."
      default=false
      }
    variable = {
      type=map(string),
      default={}
    }
  )

<some block>  
 config={package="X", freeze=false, variable={}} # Ok
 config={package="X"} # Ok
<EOB>
```

This becomes especially useful if you need to create a list or map of objects, as it can significantly reduce the boilerplate, and can give much more consistently formatted help when working with a module.
```
variable "config" {
  type = map(object({
    package  = string
    freeze   = {
      type=bool,
      description="Heck, why not this too while we're at it..."
      default=false
      }
    variable = {
      type=map(string),
      default={}
    }
  ))

<some block>  
  config={
    pkg1={ package="A", freeze=true },
    pkg2={ package="B" },
    pkg3={ package="C",variables={V="asdf", W="qwer" },
    pkg4={ package="D" },
    pkg5={ package="E" },
  }
<EOB>
```

### Attempted Solutions

The closest I can currently approximate is to have
```
variable "config"{
  type=map(map(string))
}
```
I have logic elsewhere that, when iterating over the map, checks for specific keys and provides a default value if they have not been set. It works, but its ugly and inflexible.  

In the Use Cases example, I have an object property that is another map, and this is impossible with the above definition.

### Proposal

As mentioned in Use Cases, I propose that Object fields support the full syntax of the variable definition.  eg:
```
variable "config" {
  type=map(
    object({
      field1={
        type=string,
        description="this is a field"
        default="oogachaka"
        },
      field2={
        type=bool
        default=false
      },
      field3=number
    })
  )
```

**Comment by jbardin** [comment]
Hi @ilsaloving,

Thanks for filing the issue. I'm not sure I understand what is functionally different here from the current implementation of [optional type attributes](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#optional-object-type-attributes). Can you elaborate further?

For example, your `config` variable would normally be written like so:

```
variable "config" {
  type = map(
    object({
      package  = string
      freeze   = optional(bool, false)
      variable = optional(map(string), {})
    })
  )
}
```

Which would only require the `package` attribute to be explicitly written in each nested object.

**Comment by ilsaloving** [comment]
Oh!  I wasn't aware that even existed.  I find the documentation organization difficult to navigate. Topics are categorized in unexpected ways and there's no option to search from just within the terraform documentation.  This whole article really should be under variables, not expressions.
