### ISSUE TITLE
Web Registry query does not show all results

### ISSUE THREAD

**Issue by bczoma** [hashicorp/terraform#35462]
### Terraform Version

```shell
N/A
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

There are alltogether ten modules that should have been listed, five from each of the `solacebroker` and the `solacebrokerappliance` providers:

1. SolaceProducts/queue-endpoint from solacebroker provider
1. SolaceProducts/rest-delivery from solacebroker provider
1. SolaceProducts/service from solacebroker provider
1. SolaceProducts/jndi from solacebroker provider (missing) - URL: https://registry.terraform.io/modules/SolaceProducts/jndi/solacebroker/latest)
1. SolaceProducts/client from solacebroker provider (missing - URL: https://registry.terraform.io/modules/SolaceProducts/client/solacebroker/latest)

1. SolaceProducts/queue-endpoint from solacebrokerappliance provider
1. SolaceProducts/rest-delivery from solacebrokerappliance provider
1. SolaceProducts/jndi from solacebrokerappliance provider
1. SolaceProducts/service from solacebrokerappliance provider (missing) - URL: https://registry.terraform.io/modules/SolaceProducts/service/solacebrokerappliance/latest)
1. SolaceProducts/client from solacebrokerappliance provider (missing) - URL: https://registry.terraform.io/modules/SolaceProducts/client/solacebrokerappliance/latest)

### Actual Behavior

Query returns six results, which is incomplete and there is no indication of the list continuing on a next page:
```
1. SolaceProducts/queue-endpoint from solacebroker provider
1. SolaceProducts/rest-delivery from solacebrokerappliance provider
1. SolaceProducts/queue-endpoint from solacebrokerappliance provider
1. SolaceProducts/jndi from solacebrokerappliance provider
1. SolaceProducts/rest-delivery from solacebroker provider
1. SolaceProducts/service from solacebroker provider

(1 - 6 of 6)
```

### Steps to Reproduce

Open query in Terraform registry, searching for all modules from "SolaceProducts"
https://registry.terraform.io/search/modules?q=solaceproducts

### Additional Context

Tried in FireFox, Chrome and Edge

**Comment by bczoma** [comment]
This query correctly shows that there are ten modules. Even though only six are listed here too and "view more" will not show more.
https://registry.terraform.io/namespaces/SolaceProducts

**Comment by crw** [comment]
Thanks for this report! The channel for filing issues with the registry is to please email [terraform-registry@hashicorp.com](mailto:terraform-registry@hashicorp.com). Thanks!
