### ISSUE TITLE
Support labels for google cloud resources

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#3546]
According to http://googlecloudplatform.blogspot.nl/2015/10/using-labels-to-organize-Google-Cloud-Platform-resources.html you can now use key/value pairs to label your resources.

It seem to be tags that have key=value format, but if I try that I get the following error, so apparently it's handled differently through the gcloud api.

```
Reason: invalid, Message: Invalid value for field 'tags.items[0]': 'environment=prod'.  Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
```

Please add support for this as it will allow us to use this to label our resources for better cost reporting.

**Comment by JorritSalverda** [comment]
Judging from the info in the article it's a replacement for tags, but tags that previously existed are shown as value-less keys, which first led me to believe it used the tags system, but it's separately set with

```
curl --request POST --header "Authorization: Bearer your-oauth-token" --header 'Content-Type: application/json' --data '{"labels": {"env": "canary"}, "labelFingerprint": "abcdefghij="}' https://www.googleapis.com/compute/alpha/projects/your-project-id/zones/your-zone/instances/your-instance/setLabels
```

**Comment by lwander** [comment]
Unfortunately this seems to only be available in the [beta API](https://cloud.google.com/compute/docs/reference/beta/instances/setLabels). I'll have to see what might break if we move from v1 to beta. 

Have you considered using the `metadata` instance attribute? It supports key value pairs and is documented [here](https://www.terraform.io/docs/providers/google/r/compute_instance.html#metadata)

**Comment by JorritSalverda** [comment]
I've tested using metadata for it, but it's not what they use below the covers and doesn't unlock the new features. I can wait for the feature to go out of beta though.

**Comment by lwander** [comment]
I'm asking the SetLabel team internally to see if they have an estimate for when it will leave beta.

**Comment by devth** [comment]
1. Any update on when this will reach GA?
1. Will labels be available on all resource types?

**Comment by dvianello** [comment]
Hey!

Any update on this? It would be a brilliant way for us to track costs across different deployments...

**Comment by zbikmarc** [comment]
Regarding to official documentation of Google Cloud Platform labels are no more in beta
https://cloud.google.com/compute/docs/labeling-resources (see URL in example)

**Comment by tpoindessous** [comment]
Hi

@lwander , can you remove the upstream label please ?

Labels update on resource need to provide right fingerprint. It would be great to have common functions, that we could use in resource and datasource files.

Thanks !
