### ISSUE TITLE
.vmdk path system not found in ubuntu Esxi

### ISSUE THREAD

**Issue by Omar2788** [hashicorp/terraform#35472]
### Terraform Version

```shell
Terraform v1.9.2
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

![systemnotfoud](https://github.com/user-attachments/assets/1457d187-6904-41d0-bf20-6995bbe72574)

### Expected Behavior

the vm should display the linux interface directly,
i have used a iso file in the cdrom but when i open this vm, i should do all the steps of the installation so i change the image to another linux image

### Actual Behavior

when i apply this main.tf, the vm created in the Esxi show : system not found 

### Steps to Reproduce

terraform apply

### Additional Context

when i apply this main.tf, the vm created in the Esxi show : system not found 

### References

provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_user
  password             = var.vsphere_password
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "ha-datacenter"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {}

data "vsphere_network" "mgmt_lan" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "test2" {
  name             = "vm2"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus                   = 1
  memory                     = 2048
  wait_for_guest_net_timeout = 0
  guest_id                   = "ubuntu64Guest"
  nested_hv_enabled          = true
  network_interface {
    network_id   = data.vsphere_network.mgmt_lan.id
    adapter_type = "vmxnet3"
  }

  disk {
    label            = "disk0"
    size             = 20
    eagerly_scrub    = false
    thin_provisioned = true
    datastore_id     = "${data.vsphere_datastore.datastore.id}"
    **path             = "Ubuntu-24.04.vmdk"**
  }
    
}

**Comment by Omar2788** [comment]
![image](https://github.com/user-attachments/assets/3d8f6301-fcf4-41d9-bd9c-4ae8699c3394)

**Comment by crw** [comment]
Hello @Omar2788, this appears to be a question or an issue with the vsphere provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by Omar2788** [comment]
> Hello @Omar2788, this appears to be a question or an issue with the vsphere provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.
> 
> Thanks!



> Hello @Omar2788, this appears to be a question or an issue with the vsphere provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.
> 
> Thanks!

Thank you Sir, i will check the provider repo.
