### ISSUE TITLE
error while using terraform

### ISSUE THREAD

**Issue by Abhishek123-max** [hashicorp/terraform#35483]
### Terraform Version

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: configuring Terraform AWS Provider: failed to get shared config profile, jack.roper
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on tf.tf line 12, in provider "aws":
│   12: provider "aws" {
│
╵
```

### Terraform Configuration Files

```terraform
...terraform config...
```
terraform validate is successful

### Debug Output

terraform should run 

### Expected Behavior

run terraform plan

### Actual Behavior

the terraform plan should be run after terraform validate and init success

### Steps to Reproduce

terraform plan 

### Additional Context

xx

### References

xx

**Comment by crw** [comment]
Hello @Abhishek123-max, this appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by 6525146** [comment]
> ### Terraform Version
> ```shell
> Planning failed. Terraform encountered an error while generating this plan.
> 
> ╷
> │ Error: configuring Terraform AWS Provider: failed to get shared config profile, jack.roper
> │
> │   with provider["registry.terraform.io/hashicorp/aws"],
> │   on tf.tf line 12, in provider "aws":
> │   12: provider "aws" {
> │
> ╵
> ```
> 
> ### Terraform Configuration Files
> ```hcl
> ...terraform config...
> ```
> 
> terraform validate is successful
> 
> ### Debug Output
> terraform should run
> 
> ### Expected Behavior
> run terraform plan
> 
> ### Actual Behavior
> the terraform plan should be run after terraform validate and init success
> 
> ### Steps to Reproduce
> terraform plan
> 
> ### Additional Context
> xx
> 
> ### References
> xx

https://github.com/hashicorp/terraform/issues/35483#issue-2421256730

**Comment by 6525146** [comment]
[](url)

**Comment by 6525146** [comment]
Alla is grate

**Comment by 6525146** [comment]
#36483

**Comment by 6525146** [comment]
#35002

**Comment by 6525146** [comment]
#35483

**Comment by 6525146** [comment]
lines (3 loc) · 214 Bytes
