### ISSUE TITLE
SOLUTION_TYPE_RECOMMENDATION for google_discovery_engine_search_engine Engines

### ISSUE THREAD

**Issue by lbalvarenga** [hashicorp/terraform#35480]
### Terraform Version

```shell
Terraform v1.9.2
on linux_amd64
```

### Use Cases

Creation of Agent Builder Apps that deliver recommendations to users, in addition to search.

![image](https://github.com/user-attachments/assets/26ce9aed-19e6-42da-baee-12f9a2bb20e1)

### Attempted Solutions

There are no parameters that allow me to modify the engine's solution type directly. I've tried importing a recommendations app into my Terraform state, but every apply a replacement gets triggered.

### Proposal

Have a `solution_type` field with value choices allowed by the [API](https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1/SolutionType). [More information](https://cloud.google.com/generative-ai-app-builder/docs/reference/rest/v1/projects.locations.collections.engines).

| Solution Type | Description |
| --------------- | -------------|
SOLUTION_TYPE_UNSPECIFIED | Default value.
SOLUTION_TYPE_RECOMMENDATION | Used for Recommendations AI.
SOLUTION_TYPE_SEARCH | Used for Discovery Search.
SOLUTION_TYPE_CHAT | Used for use cases related to the Generative AI agent.
SOLUTION_TYPE_GENERATIVE_CHAT | Used for use cases related to the Generative Chat agent. It's used for Generative chat engine only, the associated data stores must enrolled with SOLUTION_TYPE_CHAT solution.

### References

[Terraform Docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/discovery_engine_search_engine)

**Comment by crw** [comment]
Hello @ lbalvarenga, this appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use the community forum where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
