### ISSUE TITLE
registry.terraform.io │ does not have a provider named registry.terraform.io/hashicorp/sd

### ISSUE THREAD

**Issue by sycflash** [hashicorp/terraform#35491]
### Terraform Version

```shell
Terraform v1.9.2
on darwin_arm64
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

<img width="871" alt="image" src="https://github.com/user-attachments/assets/cf4c0b2c-26be-4096-93b3-ec8c40a46024">
<img width="610" alt="image" src="https://github.com/user-attachments/assets/9b1f0dfe-2848-4a2e-8982-ff8ee6bcb81a">

### Expected Behavior

finished and initialized

### Actual Behavior

shows an error

### Steps to Reproduce

terraform init

**Comment by apparentlymart** [comment]
Hi @sycflash,

There is no provider called `hashicorp/sd`, so this error is correct.

It seems like you have a missing or incorrect `required_providers` declaration in one of your modules to tell Terraform which provider you intend to use for the name "sd". You can use the `terraform providers` command to find out which module is implicitly causing this dependency; that is the module where you would need to add a `required_providers` entry to declare which provider source address "sd" is short for.

**Comment by sycflash** [comment]
> Hi @sycflash,
> 
> There is no provider called `hashicorp/sd`, so this error is correct.
> 
> It seems like you have a missing or incorrect `required_providers` declaration in one of your modules to tell Terraform which provider you intend to use for the name "sd". You can use the `terraform providers` command to find out which module is implicitly causing this dependency; that is the module where you would need to add a `required_providers` entry to declare which provider source address "sd" is short for.

Thanks so much. I made a mistake on data source: data "sdxxx".
