### ISSUE TITLE
Undocumented Provider Registry Protocol API

### ISSUE THREAD

**Issue by zliang-akamai** [hashicorp/terraform#35492]
### Terraform Version

```shell
N/A
```

### Affected Pages

https://developer.hashicorp.com/terraform/internals/provider-registry-protocol

### What is the docs issue?

There is an undocumented API:
- **GET** `registry.terraform.io/v1/providers/:namespace/:type/:version`
  - Example: https://registry.terraform.io/v1/providers/linode/linode/2.24.0

Also, the description of the `type` path parameter seems to be confusing because it appears as the provider name in those APIs, but [it's described as](https://developer.hashicorp.com/terraform/internals/provider-registry-protocol#type-1):

> the type portion of the address of the requested provider.

### Proposal

- Add documentation of the API mentioned above.
- Rephrase the description of `type` if needed.

**Comment by apparentlymart** [comment]
Hi @zliang-akamai,

The "Provider Registry Protocol" page is intended to document only what Terraform CLI uses to install providers, with the goal of helping those who want to implement their own provider registry with the smallest possible API surface.

The public Terraform Registry may offer other endpoints beyond what Terraform CLI uses, but those are not part of the "providers.v1" protocol that this documentation is discussing.

It might make sense to document this additional endpoint as part of the public registry's own API documentation, but that will depend on whether the registry team intends to offer this endpoint as something others can depend on or if it's there only as an implementation detail of the public registry application. Therefore I'm going to label this to make it visible to the registry team, so they can decide whether and how to document this endpoint.

In the meantime I would suggest not making any use of this endpoint unless you are willing to adjust your strategy if the conclusion is that this endpoint is an implementation detail only.

**Comment by crw** [comment]
Given that this is now an issue for the registry team, you can file the request using their public request channel: please email [terraform-registry@hashicorp.com](mailto:terraform-registry@hashicorp.com). Thanks!
