### ISSUE TITLE
provider/aws: source_dest_check is causes ModifyInstanceAttribute every run

### ISSUE THREAD

**Issue by dwradcliffe** [hashicorp/terraform#3550]
This is a follow up from #3384

Unfortunately the solution for the source_dest_check issue causes terraform to make a ModifyInstanceAttribute call for every single instance, every single time. Even if the source_dest_check is already set and doesn't need to change, and doesn't show in the diff. My cloudtrail log should not show ModifyInstanceAttribute when I change something else for an instance (e.g. tags or monitoring).

@phinze

**Comment by stack72** [comment]
Hi @dwradcliffe

I just opened a PR that seems to solve your issue - I think I want this to soak in our acceptance testing framework for a few days before merging it. If you are able to build Terraform from source and test it out for solving your issue then that would be even easier ;)

Thanks

Paul
