### ISSUE TITLE
Terraform test crashes with `length` function when module length is 0

### ISSUE THREAD

**Issue by UyumazHakan** [hashicorp/terraform#35510]
### Terraform Version

> terraform version
Terraform v1.8.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/null v3.2.2

Your version of Terraform is out of date! The latest version
is 1.9.3. You can update by downloading from https://www.terraform.io/downloads.html

### Terraform Configuration Files

```terraform
# /modules/test/main.tf
resource "null_resource" "test" {
  triggers = {
    always_run = timestamp()
  }

}
```

```terraform
# /main.tf
variable "exists" {
  type    = bool
  default = true
}

module "test_module" {
  source = "./modules/test"
  count  = var.exists ? 1 : 0
}
```

```terraform
# /crash-test.tftest.hcl
run "test" {
  command = apply

  variables {
    exists = false
  }

  assert {
    condition     = length(module.test_module) == 0
    error_message = "The storage account has a key vault reference"
  }
}
```

### Debug Output

https://gist.github.com/UyumazHakan/b1b145a929a40c9f6bde2dce13623649

### Expected Behavior

Run tests successfully

### Actual Behavior

Terraform crashes with error. However, this is not case for 1.6.x and 1.7.x.

### Steps to Reproduce

1. terraform init
2. terraform test

### Additional Context

We are already testing a resuable module in our CI with TF 1.6 and 1.7 versions. It has no problems. When we want to extra test it with 1.8, it started to crash with only 1.8 version.

The issue persists in `1.8.5` version. 

The given files are simplified version of our files that we can reproduce the exact same error. It basically crashes if a module has 0 length and use `length` function on it.

**Comment by jbardin** [comment]
Hi @UyumazHakan,

Thanks for filing the issue. This was fixed as part of #35182, and will be patched in the next minor release.
