### ISSUE TITLE
When `replace_triggered_by` on resource referring to another resource `create_before_destroy` is ignored on that referred resource

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform#35519]
### Terraform Version

```shell
Terraform v1.9.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.2
+ provider registry.terraform.io/hashicorp/google v5.39.0
+ provider registry.terraform.io/hashicorp/google-beta v5.39.0
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

### Terraform Configuration Files

```terraform
resource "google_compute_instance" "vm" {
  lifecycle {
    create_before_destroy = false
  }
}

resource "google_compute_instance_group" "vm" {
  lifecycle {
    replace_triggered_by = [
      create_before_destroy = true
      google_compute_instance.vm.instance_id,
    ]
  }
}
```

### Debug Output

N/a

### Expected Behavior

I'd expect the following to happen in order:
1. Old instance of resource `google_compute_instance.vm` should be destroyed.
2. New instance of resource `google_compute_instance.vm` should be created.
3. New instance of resource `google_compute_instance_group.vm` should be created.
4. Old instance of resource `google_compute_instance_group.vm` should be destroyed.

### Actual Behavior

1. Terraform starts with creating new instance of resource `google_compute_instance.vm`, even though the `create_before_destroy` is set to `false`.
2. This causes deployment to fail if the `google_compute_instance` has fixed instance name (because the instance with the same name already exists).

The error message:
```
│ Error: Error creating instance: googleapi: Error 409: The resource 'projects/[MASKED]/zones/europe-west3-b/instances/[MASKED_FIXED_INSTANCE_NAME]' already exists, alreadyExists
│
│   with module.elasticsearch_cluster.module.vm_master["MASKED_FIXED_INSTANCE_NAME"].google_compute_instance.vm,
│   on ../../modules/elasticsearch_cluster/vm/main.tf line 48, in resource "google_compute_instance" "vm":
│   48: resource "google_compute_instance" "vm" {
│
╵
╷
│ Error: Error creating instance: googleapi: Error 409: The resource 'projects/[MASKED]/zones/europe-west3-a/instances/gcp-it-els001-u' already exists, alreadyExists
│
│   with module.elasticsearch_cluster.module.vm_master["MASKED_FIXED_INSTANCE_NAME"].google_compute_instance.vm,
│   on ../../modules/elasticsearch_cluster/vm/main.tf line 48, in resource "google_compute_instance" "vm":
│   48: resource "google_compute_instance" "vm" {
```

### Steps to Reproduce

1. `terraform init`
2. Deploy initial setup with `terraform apply`
3. Change something in `google_compute_instance.vm` resource that will cause recreation of the resource. E.g. VM Image version.
4. Re-deploy with `terraform apply`
5. Observe how `google_compute_instance.vm` is being created without destroying it first.

### Additional Context

I stumbled upon this issue when I was desperately trying to find a workaround for https://github.com/hashicorp/terraform-provider-google/issues/18800, which is a GCP related issue, but ignoring `create_before_destroy = false` when `replace_triggered_by` is specified on a dependent resource clearly isn't.

**Comment by jbardin** [comment]
Hi @mkielar,

You cannot override `create_before_destroy` in the `google_compute_instance`, because that would a cycle with no correct order. The replacement order is forced by the replacement order of `google_compute_instance_group`, and since `create_before_destroy = false` it is overridden without any notice. We do have issue #33449 open to try and find a way to detect and raise a warning to the user if this is attempted.

Thanks!
