### ISSUE TITLE
Terraform does not remove all types of resources not defined in the config 

### ISSUE THREAD

**Issue by SanMasood** [hashicorp/terraform#35520]
### Terraform Version

```shell
Terraform v1.8.2
on darwin_amd64
+ provider registry.terraform.io/ibm-cloud/ibm v1.61.0

Your version of Terraform is out of date! The latest version
is 1.9.3.
```

### Terraform Configuration Files

Following is the definition for an access group:
```
access_groups = {
  admin = {
    name        = "sample-admin"
    description = "Access group for sample admin maintained by Terraform"
  },
```

Following is the definition for the access policy, the associated service and roles that I've created for an access group:

```
 access_groups_policies = {
  "sample-admin" = [
    {
      policy_name = "ContainerRegistry-Admin" # Container Registry
      roles       = ["Viewer", "Reader", "Writer"]
      resources = {
        service = "container-registry"
      }
    },
]
```

### Debug Output

The above access policy for service container-registry gets applied onto the access group sample-admin seamlessly. There are no issues to that part. 
I can go into the IBM Cloud account UI and view the policy created by terraform:

![Screenshot 2024-07-31 at 11 52 34](https://github.com/user-attachments/assets/33a3888f-73a3-4a2e-bb6f-41279bff272e)

After running `terraform plan`:
```
# module.iam_access_policies.ibm_iam_access_group_policy.access_groups_policies["ContainerRegistry-Admin"] will be created
  + resource "ibm_iam_access_group_policy" "access_groups_policies" {
      + access_group_id    = (known after apply)
      + account_management = false
      + id                 = (known after apply)
      + roles              = [
          + "Viewer",
          + "Reader",
          + "Writer",
        ]
      + transaction_id     = (known after apply)
      + version            = (known after apply)

      + resources {
          + service = "container-registry"
        }
    }
```
Logs after running terraform apply:

```
module.iam_access_group.ibm_iam_access_group.access_groups["sample-admin"]: Creating...
module.iam_access_group.ibm_iam_access_group.access_groups["sample-admin"]: Creation complete after 1s [id=AccessGroupId-6bd69a11-34c7-41e2-b4a4-39cef7e28b75]
module.iam_access_policies.data.ibm_iam_access_group.access_groups["sample-admin"]: Reading...
module.iam_access_policies.data.ibm_resource_group.default_resource_group["ContainerRegistry-Admin"]: Reading...
module.iam_access_policies.data.ibm_resource_group.default_resource_group["ContainerRegistry-Admin"]: Read complete after 2s [id=4b2a3bb0387e4a98a2022f2e1f65b3c0]
module.iam_access_policies.data.ibm_iam_access_group.access_groups["sample-admin"]: Read complete after 2s [id=ec1e17c9667a4fd9b57df70ba3a9bea2]
module.iam_access_policies.ibm_iam_access_group_policy.access_groups_policies["ContainerRegistry-Admin"]: Creating...
module.iam_access_policies.ibm_iam_access_group_policy.access_groups_policies["ContainerRegistry-Admin"]: Creation complete after 2s [id=AccessGroupId-6bd69a11-34c7-41e2-b4a4-39cef7e28b75/42b49761-9a36-4740-b8ad-052d51dba2e1]
```

### Expected Behavior

If I go into the UI (as in the screenshot above) and add an extra access policy to a service for the same access group, and run terraform plan and apply again, I expect Terraform to recognise the additional resource that is NOT defined in the Terraform configuration. I would then also expect Terraform to remove this additional access policy.

### Actual Behavior

When I ran terraform plan and apply for the second time, terraform did not 'read' that there was an additional policy assigned to an access group whose configuration is already written. Hence Terraform does not remove this resource which was added via other means (such as the Cloud account UI). 

### Steps to Reproduce

1. Define an access group in the Terraform config (as I've pasted above)
2. Define an access policy for the above group.
3. Define modules with for loops (or whatever approach feasible) to attach the access policies in step 2 into the access group in Step 1. 
4. Run terraform plan and apply to deploy the above config.
5. Review terraform output, and go into Cloud UI to confirm whether access policy has been applied to access group. 
6. From within the UI, add another access policy (to another service) for the same access group. 
7. Run terraform plan and apply again to redeploy (this is when I was expecting terraform to recognise and remove the additional policy I created in Step 6)

It is also worth noting that for an access policy with roles defined in my terraform config, if I add an additional role via the UI and then run terraform apply, that additional role does get removed. So I'm confused as to why Terraform can identify an additional role and remove it, but not an additional policy.

**Comment by jbardin** [comment]
Hi @SanMasood,

Terraform can only remove resources which it actively manages already (otherwise there would be no limit to what it tried to destroy within the purview of the provider). If there is a resource type which is logically part of an already managed resource, then it would be up to the provider to detect the change and create the appropriate plan. In this case however it seems you have create what is effectively an independent instance of a resource type is exists in the configuration, but since it's not defined in the configuration Terraform has no knowledge of this extra instance.

If this is a situation which is resolvable, you would need to file an issue with the provider developers, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
