### ISSUE TITLE
Regarding the release_channel target with the addition of the Extended channel

### ISSUE THREAD

**Issue by mkasuya009** [hashicorp/terraform#35523]
### Terraform Version

```shell
Terraform v1.7.4
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_release_channel

### What is the docs issue?

https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels?hl=ja#extended
Google has provided the Extended channel.
As a result, when will Extended be added to the release_channel target when creating GKE with Terraform?

### Proposal

I would like to add Extended to the release_channel target.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the Goole provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues. If you have questions about Terraform or the Google provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-google/32) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
