### ISSUE TITLE
dynamodb sse change doesn't get planned when from customer managed kms to aws managed kms

### ISSUE THREAD

**Issue by cchentyro** [hashicorp/terraform#35540]
### Terraform Version

```shell
hashicorp/aws v5.61.0
Terraform v1.5.7
```

### Terraform Configuration Files

```terraform
change from 
resource "aws_dynamodb_table" "xxxx-table" {

  server_side_encryption {
    enabled = true
    kms_arn= xxxx
  }
}
to
resource "aws_dynamodb_table" "xxxx-table" {

  server_side_encryption {
    enabled = true
  }
}
```

### Debug Output

inside of the state,
```
    "server_side_encryption": [
              {
                "enabled": true,
                "kms_key_arn": "xxxxxx"
              }
            ]
```
but the plan is no change.

### Expected Behavior

should change to aws managed key
aws/kms/dynamodb

### Actual Behavior

no change, still use customer managed key, and since the key is deleted, the dynamodb get corrupted with status
```
Encryption credentials inaccessible
```

### Steps to Reproduce

terraform init
terraform plan
terraform apply

**Comment by liamcervante** [comment]
Hi @cchentyro, can you share the output of the `terraform plan` command? Is Terraform proposing a change that then doesn't get applied, or does it just not plan the change at all?

**Comment by cchentyro** [comment]
it's no change, that's the reason why we can't update it from customer managed kms sse back to aws managed..
the workaround is i change the sse to false and back to true.

**Comment by liamcervante** [comment]
Thanks! Given the plan isn't even showing the change, I think this is more likely an issue with the AWS provider specifically than Terraform Core. I'm going to close this issue here, but you should reopen with the AWS provider team over at https://github.com/hashicorp/terraform-provider-aws. Thanks!
