### ISSUE TITLE
Documentation is missing links - at least

### ISSUE THREAD

**Issue by tf42src** [hashicorp/terraform#35545]
### Terraform Version

```shell
E.g. go here: https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=inputs

None of the entries on the page has a clickable link or any further information. Why?
```

### Affected Pages

https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=inputs

### What is the docs issue?

No info, no links. I have no idea how to use the module.

### Proposal

Add more info :) At least at links to the next layer.

**Comment by tf42src** [comment]
![Screenshot from 2024-08-09 15-54-37](https://github.com/user-attachments/assets/5f9e5ba3-8e02-455b-a8d7-9e2e00944faa)

**Comment by crw** [comment]
Hello @tf42src, this appears to be an issue or question with the AWS provider, not with Terraform itself. AWS Provider documentation is generated from the provider itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues.  Thanks!

**Comment by tf42src** [comment]
Thanks @crw !

Done. https://github.com/terraform-aws-modules/terraform-aws-eks/issues/3117
