### ISSUE TITLE
Terraform Crash only on Container Apps

### ISSUE THREAD

**Issue by przemykk** [hashicorp/terraform#35563]
### Terraform Version

```shell
Terraform v0.12.31
```

### Terraform Configuration Files

```terraform
terraform {
  backend "azurerm" {
    subscription_id      = "XXX"
    tenant_id            = "XXX"
    resource_group_name  = "XXX"
    storage_account_name = "XXX"
    container_name       = "terraform-governance-rbac"
    key                  = "governance-rbac-test.tfstate"
    client_id            = "XXX"
  }
}
```

### Debug Output

https://gist.github.com/przemykk/e31f72b8152134abfdd69db02a51a57a

### Expected Behavior

Terraform should initialize with storage account as backend

### Actual Behavior

Terraform crashes when running terraform init

### Steps to Reproduce

terraform init -input=false

### Additional Context

Hello,
I'm trying to use azure container apps as self-hosted agent and to do that I need to run terraform on the containers.
A lot of environments and pipelines are using old terraform versions before **0.15.0**. After running terraform init with backend initialization (backend as storage account) terraform crashes. It only happens with terraform versions below **0.15.0** (example is from **0.12.31** version) Unfortunately I can't upgrade terraform versions so I need this solution to work. After doing some testing on the local environment and local docker it appears that the issue only exists when using azure container apps.
Terraform with version **0.12.31** on local container (same dockerbuild file) run init completely without any crash. I have tested this solution on different base images on container apps (this test was on **ubuntu:22.04**) but with no luck. Ticket to MS support is also created but I get the recommendation to create an issue also here.
 
 I'm connecting to backend using Service Principal using below command:
 ``` 
export ARM_SUBSCRIPTION_ID=XXX
export ARM_CLIENT_ID=XXX
export ARM_CLIENT_SECRET=XXX
export ARM_TENANT_ID=XXX
export TF_LOG=trace
az account set --subscription "XXX"
terraform version
terraform init -input=false
  ```
  
As I mentioned this connection with same commands forks without any issues on terraform version 0.15.0 and above.

**Comment by jbardin** [comment]
Hi @przemykk,

What you're showing here is a crash in the provider, not in Terraform, so any change would have to be made in the provider codebase. It's not possible for us to retroactively alter the v0.12 release to accommodate the provider in whatever way was changed in later releases, and since this is a very old provider version it's likely to have already been fixed in following releases as well. 

Unfortunately upgrading Terraform and/or the provider is the only way to avoid this entirely.
