### ISSUE TITLE
terraform -v not reporting 1.9.4 as current, 1.9.3 as out-of-date. Still reportin 1.9.3 as current

### ISSUE THREAD

**Issue by jaffel-lc** [hashicorp/terraform#35612]
### Terraform Version

```shell
1.9.3:
$ terraform version
Terraform v1.9.3
on linux_amd64

1.3.10:
$ terraform version
Terraform v1.3.10
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.9.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

N/a

### Debug Output

n/a

### Expected Behavior

- Expect terraform (all versions) to report 1.9.4 as the latest version.
- Expect 1.9.3 to report itself as out-of-date

### Actual Behavior

- 1.9.3 is not reporting that it is out-of-date
- 1.3.10 (and 1.8.5) are reporting that 1.9.3 is the latest version

### Steps to Reproduce

1. execute 'terraform version' using version 1.9.3  - we use symbolic links
2. execute 'terraform version' using version 1.3.10, 1.8.5, etc. - we use symbolic links

In all cases you will see that it thinks that 1.9.3 is latest despite 1.9.4 having been releases on 2024-08-07 

### Additional Context

https://releases.hashicorp.com/terraform/ - shows that terrafrom_1.9.4 is available

https://github.com/hashicorp/terraform/blob/v1.9/CHANGELOG.md - shows that Terraform 1.9.4 was released on 2024-08-07

### References

- https://github.com/hashicorp/terraform-provider-aws/issues/38922

A commented in here says that the API is providing outdated info:
{"product":"terraform","current_version":"1.9.3","current_release":1721850049,"current_download_url":"https://releases.hashicorp.com/terraform/1.9.3","current_changelog_url":"https://github.com/hashicorp/terraform/blob/v1.9.3/CHANGELOG.md","project_website":"https://www.terraform.io","alerts":[]}

**Comment by liamcervante** [comment]
Thanks for the report! This should be fixed now!

**Comment by jaffel-lc** [comment]
I can confirm that 'terraform version' is reporting 1.9.,4 is the latest version.
Thank you.
