### ISSUE TITLE
S3 remote backend without DynamoDB

### ISSUE THREAD

**Issue by stevehipwell** [hashicorp/terraform#35625]
### Terraform Version

```shell
n/a
```

### Use Cases

I'd like to be able to use a S3 remote backend without requiring DynamoDB to handle the state locking. This should now be possible given the [announcement](https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/) that S3 now supports conditional writes.

### Attempted Solutions

n/a

### Proposal

Terraform should support locking the remote state directly on S3 if DynamoDB isn't configured via the if-none-match header.

### References

- https://github.com/hashicorp/terraform/issues/27070

**Comment by crw** [comment]
Thanks for this feature request! If you are viewing this issue and would like to indicate your interest, please use the 👍 reaction on the issue description to upvote this issue. We also welcome additional use case descriptions. Thanks again!

**Comment by bschaatsbergen** [comment]
Happy to pick this up 👍🏼, working on a draft.

**Comment by bschaatsbergen** [comment]
Prototyping of S3-native state locking: https://github.com/hashicorp/terraform/pull/35661

**Comment by bschaatsbergen** [comment]
We aim to release support for S3-native state locking  in v1.10. See #35661 for reference.
