### ISSUE TITLE
@dbrat43 Thanks for raising this issue 👏.

### ISSUE THREAD

**Issue by prashantnagure89** [hashicorp/terraform#35621]
@dbrat43 Thanks for raising this issue 👏.
The correct syntax is

```hcl
  target_object_key_format {
    partitioned_prefix {
      partition_date_source = "DeliveryTime"
    }
  }
```

_Originally posted by @ewbankkit in https://github.com/hashicorp/terraform-provider-aws/issues/35396#issuecomment-1900776233_

I am using below code and tried random aws providers from 5.27.0 to 5.56.0

resource "aws_s3_bucket" "log_bucket" {  
  bucket        = "bucket_name"  
  acl           = "log-delivery-write"  
  force_destroy = false  
  
  tags = {  
    "app:name"        = "nameofapp"  
  }  
  
  logging {  
    target_bucket = "logging_bucket"
    target_prefix = "target_prefix_value"  
  
    target_object_key_format {
      partitioned_prefix {
        partition_date_source = "EventTime"
      }
    }  
  }  
 
I am receiving an error indicating that the block is not supported.

 "aws_s3_bucket" "log_bucket":
  17:     target_object_key_format {
Blocks of type "target_object_key_format" are not expected here.

**Comment by liamcervante** [comment]
Hi @prashantnagure89, I think you haven't properly closed the `logging` block:

```
resource "aws_s3_bucket" "log_bucket" {
  bucket = "bucket_name"
  acl = "log-delivery-write"
  force_destroy = false

  tags = {
    "app:name" = "nameofapp"
  }

  logging {
    target_bucket = "logging_bucket"
    target_prefix = "target_prefix_value"
  }

  target_object_key_format {
    partitioned_prefix {
      partition_date_source = "EventTime"
    }
  }  
}
``` 

However, the recommended approach is to define the logging data in a separate resource as documented here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_logging
