### ISSUE TITLE
azurerm_cognitive_account kind = "OpenAI" BringOwnFeatureNotEnabled deployment failure

### ISSUE THREAD

**Issue by npalmer1452** [hashicorp/terraform#35635]
### Terraform Version

```shell
Terraform v1.7.5
on windows_386
+ provider registry.terraform.io/azure/azapi v1.15.0
+ provider registry.terraform.io/hashicorp/azurerm v4.0.0
```

### Terraform Configuration Files

terraform {
  backend "remote" {
    organization = ""
    workspaces {
      name = ""
    }
  }
  required_providers {
    azapi = {
      source = "azure/azapi"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0.0"
    }
  }
}

### Debug Output

N/A

### Expected Behavior

deploys azurerm_cognitive_account 

### Actual Behavior

Error: creating Account 
│ Resource Group Name: "NP-OPENAI-RGP"
│ Account Name: "np-openai"): unexpected status 400 (400 Bad Request) with error: BringOwnFeatureNotEnabled: Bring your own feature is not enabled for Subscription/SKU/Kind.
│
│   with azurerm_cognitive_account.openai,
│   on openai.tf line 14, in resource "azurerm_cognitive_account" "openai":
│   14: resource "azurerm_cognitive_account" "openai" {
│

### Steps to Reproduce

terraform apply

### Additional Context

Looks like this feature is not needed for azurerm_cognitive_accout with kind = "openai", not sure why its checking.  Feel like this feature check is not need, if the subscription did not have a feature enabled and the resource required it, the deployment would still fail by azure on the deployment api call.  Terraform pre-checks are annoying.  

### References

https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR65c5WORsv5NtSDPjRrSCMhUNDZJUERRVVVDME4xNDVNRjEwMTNZV1dHSSQlQCN0PWcu

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
