### ISSUE TITLE
Feature req: Data source for aws_api_gateway_stage

### ISSUE THREAD

**Issue by courtneygreif** [hashicorp/terraform#35637]
### Terraform Version

```shell
N/A
```

### Use Cases

Reiterating an old issue https://github.com/hashicorp/terraform-provider-aws/issues/19306

It would be very helpful to have a data source for aws_api_gateway_stage.

It looks like there was already a Pull Request (https://github.com/hashicorp/terraform-provider-aws/pull/8890) opened to add this exact feature but was closed and locked due to inactivity.

### Attempted Solutions

https://github.com/hashicorp/terraform-provider-aws/pull/8890

### Proposal

https://github.com/hashicorp/terraform-provider-aws/pull/8890

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
