### ISSUE TITLE
aws_route53_record resources not working when mixed case is used in name

### ISSUE THREAD

**Issue by kxseven** [hashicorp/terraform#3564]
## Summary

 - AWS Route53 resource getting created **every** time `terraform apply` is run
 - no resource gets added to the terraform.tfstate file, even after successfully reporting that the resource gets created (it does get created in Route53)

## To Reproduce

 - This is an SRV required for MS Active Directory

        resource "aws_route53_record" "ldap_tcp_DefaultFirstSiteSame_sites_domainDnsZones" {
            zone_id = "ABCDEFGHIJKLMNOP"
            name = "_ldap._tcp.default-First-Site-Name._sites.domainDnsZones"
            type = "SRV"
            ttl = "600"
            records = [ "0 100 389 msad-pdc.test.mydomain.com." ]
        }

 - This version of it works however;

        resource "aws_route53_record" "ldap_tcp_defaultfirstsitename_sites_domaindnszones" {
            zone_id = "ABCDEFGHIJKLMNOP"
            name = "_ldap._tcp.default-first-site-name._sites.domaindnszones"
            type = "SRV"
            ttl = "600"
            records = [ "0 100 389 msad-pdc.test.mydomain.com." ]
        }

## Suggestions

 - Have the code always function in lowercase
 - Update the docs to highlight that mixed-case name and name properties are not supported

**Comment by catsby** [comment]
Thanks @kxseven – I opened #3574 to address this

**Comment by kxseven** [comment]
Duplicate of issue #3246 it seems. Closing this dupe.
