### ISSUE TITLE
[Bug]: Single sensitive value causes all Elastic Beanstalk settings to be interpreted as sensitive

### ISSUE THREAD

**Issue by hdodov** [hashicorp/terraform#35686]
### Terraform Version

```shell
Terraform v1.9.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.65.0
```

### Terraform Configuration Files

variables.tf:

```terraform
variable "db_password" {
  type      = string
  sensitive = true
}
```

main.tf:

```terraform
terraform {
  required_version = ">= 1.2.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.65"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

resource "aws_elastic_beanstalk_application" "default" {
  name        = "my-app"
}

resource "aws_elastic_beanstalk_environment" "default" {
  name        = "my-env"
  application = aws_elastic_beanstalk_application.default.name
  solution_stack_name = "64bit Amazon Linux 2023 v4.3.6 running Docker"

  setting {
    namespace = "aws:autoscaling:asg"
    name      = "MaxSize"
    value     = "4"
  }

  setting {
    namespace = "aws:elasticbeanstalk:sns:topics"
    name      = "Notification Endpoint"
    value     = "email@example.com"
  }

  setting {
    namespace = "aws:elasticbeanstalk:application:environment"
    name      = "DATABASE_PASSWORD"
    value     = var.db_password
  }
}
```

### Debug Output

```shell
Terraform will perform the following actions:

  # aws_elastic_beanstalk_environment.default will be updated in-place
  ~ resource "aws_elastic_beanstalk_environment" "default" {
        id                     = "XXXXXXXXXXXX"
        name                   = "XXXXXXXXXXXXXX"
        tags                   = {}
        # (19 unchanged attributes hidden)

      # Warning: this block will be marked as sensitive and will not
      # display in UI output after applying this change.
      ~ setting {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      # Warning: this block will be marked as sensitive and will not
      # display in UI output after applying this change.
      ~ setting {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      # Warning: this block will be marked as sensitive and will not
      # display in UI output after applying this change.
      ~ setting {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

Single Elastic Beanstalk `setting` block should be obfuscated (the one containing `var.db_password`).

### Actual Behavior

**All** `setting` blocks are getting obfuscated, even the ones that are hardcoded as plain strings.

### Steps to Reproduce

1. Create an `aws_elastic_beanstalk_environment`
2. Add a few `setting` blocks
3. Use a sensitive value in one of them

### References

- It's probably related to the weird diff behavior in https://github.com/hashicorp/terraform-provider-aws/issues/1471.
- I first opened this issue in the AWS provider repo (https://github.com/hashicorp/terraform-provider-aws/issues/39189), but they told me to open one here instead.

**Comment by jbardin** [comment]
Hi @hdodov,

The behavior you see here is expected because the `setting` block is a "set" type. The elements of a set are identified by their entire value, so the sensitivity mark needs to be applied to the entire set to avoid disclosing sensitive values.

**Comment by hdodov** [comment]
@jbardin I see. So if I want the other values to be visible, I just have to mark the sensitive ones as not sensitive? And the alternative is to just have *all* values obfuscated, which can be more confusing. Are those the only two options? Which one would you pick?

**Comment by jbardin** [comment]
@hdodov, yes, the only way to show all the values in the set in the human readable CLI output is to ensure it contains no sensitive values. While these are formatted in the configuration as separate lexical blocks for convenience, the actual data structure for `setting` is a single `set(object(...))` value and is operated on as a whole.

How you want to approach this is up to you. Often the operator of Terraform has sufficient privileges where hiding many sensitive fields has no real benefit. The output is also not obscured in the machine readable json format, so you could inspect the plan from the json output too.
