### ISSUE TITLE
aws and awscc _fis_experiment_template having issues with ASG parameters (availabilityzoneIdentifiers)

### ISSUE THREAD

**Issue by junkeiro** [hashicorp/terraform#35696]
### Terraform Version

```shell
1.9.0
```

### Terraform Configuration Files

```terraform
resource "awscc_fis_experiment_template" "fis_ec2Fis" {
  description = "Dynamic FIS EC2"
  role_arn    = aws_iam_role.iam_ec2Fis.arn

  actions = {
    "TEAM-EC2-action" = {
      name        = "TEAM-EC2-action"
      action_id   = "aws:ec2:asg-insufficient-instance-capacity-error"
      description = "EC2 Dynamic FIS by tf-fis-modules"

      targets = {
        AutoScalingGroups = "TEAM-EC2-target"
      }

      parameters = {
        "availabilityzoneIdentifiers" = "usw2-az1"
        "duration"                    = "PT10M"
        "percentage"                  = "100"
      }
    }
  }
...
...
```

### Debug Output

Terraform Plan:

resource "awscc_fis_experiment_template" "fis_ec2Fis" {
      + actions                = {
          + "TEAM-EC2-action" = {
              + action_id   = "aws:ec2:asg-insufficient-instance-capacity-error"
              + description = "EC2 Dynamic FIS"
              + parameters  = {
                  + "availabilityzoneIdentifiers" = "usw2-az1"
                  + "duration"                              = "PT10M"
                  + "percentage"                         = "100"
                }
              + start_after = (known after apply)
            }
............

Terraform Apply:

│ Error: AWS SDK Go Service Operation Incomplete
│ 
│   with awscc_fis_experiment_template.fis_ec2Fis,
│   on main.tf line 13, in resource "awscc_fis_experiment_template" "fis_ec2Fis":
│   13: resource "awscc_fis_experiment_template" "fis_ec2Fis" {
│ 
│ Waiting for Cloud Control API service CreateResource operation completion
│ returned: waiter state transitioned to FAILED. StatusMessage: Missing value
│ for required parameter "availabilityZoneIdentifiers" in action
│ "TEAM-EC2-action". (Service: AWSFIS; Status Code: 400; Error Code:
│ ValidationException; Request ID: xxxxxx-xxxxxxxxxxxx-xxxxxx;
│ Proxy: null). ErrorCode: InvalidRequest

### Expected Behavior

Terraform apply not having issues with the parameter: availabilityzoneIdentifiers

### Actual Behavior

Terraform apply phase isn't including the value of availabilityzoneIdentifiers parameter

### Steps to Reproduce

1. `terraform init`
2.  Use the provider either 'aws' or 'awscc' to create the resource `aws_fis_experiment_template` or `awscc_fis_experiment_template`
3.  Have in `action_id` the value `'aws:ec2:asg-insufficient-instance-capacity-error'`
4.  Provide at least the parameters `availabilityzoneIdentifiers` and `duration` (use reference links)
5. `terraform apply`

### Additional Context

As mentioned before, terraform plan is passing successfully showing the parameters correctly. Terraform apply seems to be ignoring `availabilityzoneIdentifiers` parameter thus throws error.

### References

[FIS ASG Action](https://docs.aws.amazon.com/fis/latest/userguide/fis-actions-reference.html#asg-ice)
[Terraform AWSCC fis_experiment_template](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/fis_experiment_template)
[Terraform AWS fis_experiment_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fis_experiment_template)

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider, not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by junkeiro** [comment]
Got it. Pardon my ignorance. I'll raise the ticket for both providers, aws and awscc.
