### ISSUE TITLE
[feature request] [terraform-provisioner-local-exec] Add no echo option

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#3571]
It would be really nice if the `terraform-provisioner-local-exec` had an option to not echo out the execution of the provisioner. We are doing something similar to

```
resource "null_resource" "chef-validator-setup" {
  provisioner "local-exec" {
    command = "echo \"${var.chef-validator-pem}\" > ${path.module}/validator.pem"
  }
}
```

and it would be nice to not have the output of the `var.chef-validator-pem` echo'd to screen.

**Comment by pkolyvas** [comment]
I think we might have a PR open that resolves this: https://github.com/hashicorp/terraform/pull/26611

I'm going to close it out.
