### ISSUE TITLE
hashicorp/aws version 5.67.0 breaks compatibility with role_arn for dynamic naming of AWS accounts

### ISSUE THREAD

**Issue by domijana** [hashicorp/terraform#35730]
### Terraform Version

```shell
Terraform v1.9.5
on windows_386
+ provider registry.terraform.io/hashicorp/aws v5.66.0 
+ provider registry.terraform.io/hashicorp/local v2.5.2
+ provider registry.terraform.io/hashicorp/null v3.2.3
```

### Terraform Configuration Files

The below code does NOT work as is.

provider.tf

```
provider "aws" {
  alias  = "management"
  region = "us-east-1"
  profile = "commercial"
}

provider "aws" {
  alias = "new_account"
  region = "us-east-1"
  profile = "commercial"
  assume_role {
    role_arn = "arn:aws:iam::${aws_organizations_account.new_account.id}:role/OrganizationAccountAccessRole"
  }
}
```

account.tf

```
# Create a new AWS account
resource "aws_organizations_account" "new_account" {
  provider  = aws.management
  email     = "new-account-email@example.com"
  name      = "NewCommercialAccount"
  role_name = "OrganizationAccountAccessRole"
}

# Output the new account ID
output "new_account_id" {
  value = aws_organizations_account.new_account.id
}
```

vpc.tf

```
resource "aws_vpc" "my_vpc" {
  provider   = aws.new_account
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "MyVPC"
  }
}

resource "aws_subnet" "my_subnet" {
  provider   = aws.new_account
  vpc_id     = aws_vpc.my_vpc.id
  cidr_block = "10.0.1.0/24"

  tags = {
    Name = "MySubnet"
  }
}
```

### Debug Output

https://gist.github.com/domijana/8220eb9a1040d2d03a57279764f601c3

### Expected Behavior

Terraform plan should show the following

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + new_account_id = (known after apply)

### Actual Behavior

│ Error: Missing required argument
│
│   with provider["registry.terraform.io/hashicorp/aws"].new_account,
│   on provider.tf line 7, in provider "aws":
│    7: provider "aws" {
│
│ The argument "role_arn" is required, but no definition was found.

### Steps to Reproduce

1. terraform init
2. terraform plan

### Additional Context

In order to fix this issue, I specified version 5.66.0 in my provider file. I then deleted the terraform and terraform.lock.hcl files. Then I did terraform init, terraform plan, and it works.

Below code was added to the provider.tf file to fix it.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.66.0"  # Specify the desired AWS provider version
    }
  }
}

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
