### ISSUE TITLE
Possibility to move aws_dms_event_subscription to EventBridge

### ISSUE THREAD

**Issue by rossbush** [hashicorp/terraform#35749]
### Terraform Version

```shell
According to the documentation below, all DMS event subscriptions can be converted to EventtBridge when using DMS Version 3.45 and above. If I convert the SNS subscriptions to EventBridge as outlined in the article, I am afraid it will impact terraform plans or applies. Are there any plans to move aws_dms_event_subscription to the new DMS event model outlined below?

https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Events.html
```

### Use Cases

This upgrade would allow the creation of the DMS events to be migrated from DMS to Amazon EventBridge. This is the recommendation from AWS

### Attempted Solutions

None

### Proposal

None

### References

https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Events.html

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
