### ISSUE TITLE
Wrong ARN for AWS Amplify Webhooks

### ISSUE THREAD

**Issue by AriannaLanz** [hashicorp/terraform#35751]
### Terraform Version

```shell
Terraform v1.9.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  required_version = "~> 1.9.0"
}
```

### Debug Output

N/A

### Expected Behavior

The output of `aws_amplify_webhook.example_webhook.arn` should be `arn:aws:amplify:<region>:<account-id>:webhooks/<webhook-id>`

### Actual Behavior

The actual output of `aws_amplify_webhook.example_webhook.arn` is `arn:aws:amplify:<region>:<account-id>:apps/<app-id>/webhooks/<webhook-id>`

### Steps to Reproduce

1. Create an AWS Amplify app and webhook: 

```
resource "aws_amplify_app" "example" {
  name = "app"
}

resource "aws_amplify_branch" "master" {
  app_id      = aws_amplify_app.example.id
  branch_name = "master"
}

resource "aws_amplify_webhook" "master" {
  app_id      = aws_amplify_app.example.id
  branch_name = aws_amplify_branch.master.branch_name
  description = "triggermaster"
}
```

2. `terraform state show aws_amplify_webhook.master`

### Additional Context

I need to add an `amplify:GetWebhook` IAM permission for this specific webhook, but I was getting the error: 

```
Error: reading Amplify Webhook (<webhook-id>): operation error Amplify: GetWebhook, https response error StatusCode: 403, RequestID: <request-id id>, api error AccessDeniedException: User: arn:aws:sts::<account-id>:assumed-role/<role> is not authorized to perform: amplify:GetWebhook on resource: arn:aws:amplify:<region>:<account-id>:webhooks/<webhook-id>

```

and I noticed the discrepancy in that Terraform outputs the ARN as  `arn:aws:amplify:<region>:<account-id>:apps/<app-id>/webhooks/<webhook-id>` when AWS expects `arn:aws:amplify:<region>:<account-id>:webhooks/<webhook-id>` (without the `apps/<app-id>` part). 

When I fixed this manually in the IAM console, I no longer saw the 403 error.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
