### ISSUE TITLE
Maintenance schedule for dedicated sql pool azurerm

### ISSUE THREAD

**Issue by Mohamednourr** [hashicorp/terraform#35756]
### Terraform Version

```shell
Terraform v1.9.5
```

### Use Cases

I would like to configure Maintenance schedule for dedicated sql pool in synapse workspace using azurerm

### Attempted Solutions

It's already not possible with current azurerm

**Comment by liamcervante** [comment]
Hi @Mohamednourr, the individual providers for Terraform are now managed in dedicated repositories. For Azure this is https://github.com/hashicorp/terraform-provider-azurerm. I'm going to close this issue here but you should reopen it directly with the Azure team. Thanks!
