### ISSUE TITLE
Terraform does not handle dependencies on resources by providers correctly

### ISSUE THREAD

**Issue by lwander** [hashicorp/terraform#3575]
For example:

```
provider "google" {
    ...
}

resource "google_container_cluster" "primary" {
    ...
}

provider "kubernetes" {
    endpoint = "${google_container_cluster.primary.endpoint}"
}
```

The `kubernetes` provider will be created with an empty `endpoint` field before the `google_container_cluster.primary` resource finishes being created. This would not be an issue if the `kubernetes` item was a resource rather than a provider.

**Comment by apparentlymart** [comment]
Thanks for reporting this... I think it is the same issue discussed in #2976.
