### ISSUE TITLE
Terraform Script Filed Data Type Hover issue

### ISSUE THREAD

**Issue by vynalavamshi** [hashicorp/terraform#35770]
Thanks for reporting this issue, @Rabattkarte!

Hi All,

While I am working with Terraform script in VS Code, when I Hover on any Terraform script filed it should show me that particular data type of the field, but it is loading infinitely, can you please me on this issue

**Comment by jbardin** [comment]
Hello,

This repo is used for development of the Terraform CLI, not for VSCode or the plugins. I think you may be looking for https://github.com/hashicorp/vscode-terraform, or the  [the community forums](https://discuss.hashicorp.com/c/terraform-core)

Thanks!
