### ISSUE TITLE
Create a cloud resource according its availability some resources in a region : for instance GPU

### ISSUE THREAD

**Issue by mldmld68** [hashicorp/terraform#35787]
### Terraform Version

```shell
Hello there,
We are experiencing issue to get resources with GPU. 
I would like to know if there could be a way to ask terraform to create a ressource in the first region of a list, sorted by preference ? 

Thx
```

### Use Cases

GPU are rare in Cloud providers

### Attempted Solutions

Terraform is crashing if the targeted region is stock out 

### Proposal

Add a data source or a way to make terraform trying creating a resource without crashing according the error code for instance

### References

No

**Comment by jbardin** [comment]
Hello,

This appears to be a question or an issue with a provider you have not mentioned, but not with Terraform itself. You can check existing issues and file a new one in the provider's project repository, linked from the their registry page. If you have questions about Terraform or the provider, it's better to use [the community forum](https://discuss.hashicorp.com/) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
