### ISSUE TITLE
Add Include Directive

### ISSUE THREAD

**Issue by jlongo62** [hashicorp/terraform#35786]
### Terraform Version

```shell
terraform version
Terraform v1.9.6
on linux_amd64
```

### Use Cases

Please add an Include directive to terraform.
I work on many projects, often in the same repo.
I often have files like variables common to each project that must be duplicated into each project or module. This leads to deviation among the different versions. In higher languages like .Net we often use a link to include a file in a project or multiple projects to address this problem. HTML also uses this approach to reinforce consistency.

This would also solve the tags issue in Azure provider - one tag file could be included in each resource, at least until that is addressed in the provider

### Attempted Solutions

n/a

### Proposal

Add an Include directive to terraform.

### References

n/a

**Comment by jbardin** [comment]
Hi @jlongo62,

You can see the rationale for closing the original request here: https://github.com/hashicorp/terraform/issues/1478#issuecomment-513059932
