### ISSUE TITLE
Vsphere：hardDisk type need to be  configurable.

### ISSUE THREAD

**Issue by guanglinlv** [hashicorp/terraform#3578]
Hi,

there are two potential configure for hardDisk type in [createVirtualMachineand](https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L870)  and [deployVirtualMachine](https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L1055). actually we need specify hardDisk type(`thin` or `eager_zeroed`) manually.

Thanks.

**Comment by chrislovecnm** [comment]
@guanglinlv can you add more details? Would you like to have a configuration option for hd type?

**Comment by chrislovecnm** [comment]
@guanglinlv added notes on https://github.com/hashicorp/terraform/issues/3624 about this ...

**Comment by chrislovecnm** [comment]
@catsby can we add enhancement label instead of bug?

**Comment by matt-deboer** [comment]
+1: just created a quick test impl of  this by adding a "init_type" param to hd, and specified "thin" provisioning--> my total provision time on a cluster of 10 went from 25 mins to 2.5 minutes! (and "storage usage" went way down, as expected); it seems strange that "thin" provisioning wasn't chosen as the default, but anyway, I should have a PR soon where we can review this.

**Comment by chrislovecnm** [comment]
@matt-deboer go matt ... go matt :+1:

**Comment by chrislovecnm** [comment]
@catsby please close the PR is in

**Comment by catsby** [comment]
Thanks for following up
