### ISSUE TITLE
Missing documentation on ternary operator

### ISSUE THREAD

**Issue by Lucas-C** [hashicorp/terraform#35799]
### Terraform Version

```shell
v1.9.X (latest)
```

### Affected Pages

https://developer.hashicorp.com/terraform/language/expressions/operators

### What is the docs issue?

The ternary operator is effectively supported in Terraform configuration language but it is not mentioned on the documentation page about operators

### Proposal

Add a mention of the ternary operator (`a ? b : c`) and specify its precedence

**Comment by Lucas-C** [comment]
Oh great, thank you for pointing me to that documentation page 👍

Still, isn't `?` an operator ?
Is its precedence documented somewhere?
I guess that i should come 8th in the list of logical operators there: https://developer.hashicorp.com/terraform/language/expressions/operators#arithmetic-and-logical-operators

**Comment by jbardin** [comment]
I think it's probably due the fact that `?` can only exist in a complete conditional expression, and can't stand alone as an independent operator. Maybe there could be a separate callout for `?` +`:` in that list to link to the expression page.

**Comment by Lucas-C** [comment]
> Maybe there could be a separate callout for `?` +`:` in that list to link to the expression page.

Good idea, I agree 👍
