### ISSUE TITLE
Trouble passing an aliased provider to a module

### ISSUE THREAD

**Issue by lousyd** [hashicorp/terraform#35795]
### Terraform Version

```shell
Terraform v1.5.7
on linux_amd64
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.0.1"
    }
  }
}

provider "azurerm" {
  alias = "myapp-dev"

  features {}

  client_id       = var.ARM_CLIENT_ID
  client_secret   = var.ARM_CLIENT_SECRET
  tenant_id       = var.ARM_TENANT_ID
  subscription_id = "539bce32-blah-blah-blah-00155de4b11a"

  resource_provider_registrations = "none"
}

module "deploy_dev_app_service" {
  source    = "./app-service"
  providers = { azurerm = azurerm.myapp-dev }

  [...variables...]
}
```
and in the child module:
```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "4.0.1"
    }
  }
}
```

### Debug Output

no gist

### Expected Behavior

I believe I should have been able to successfully run plan and apply on this code.

### Actual Behavior

But when I run plan, I get this error:
│
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/hashicorp/azurerm" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│ 
│
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on <empty> line 0:
│   (source code not available)
│ 
│ The argument "features" is required, but no definition was found.
│
This makes me think that the module is using the inherited default "azurerm" provider (which I haven't defined). But I am explicitly calling the module with providers = { azurerm = azurerm.myapp-dev }.

Shouldn't the module be using my "myapp-dev" provider configuration? 

### Steps to Reproduce

`terraform init`
`terraform plan`

**Comment by jbardin** [comment]
Hello,

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!

**Comment by lousyd** [comment]
Oh. Well this seems like a bug to me. I'm following the documentation and it's not doing what it's supposed to be doing.

**Comment by crw** [comment]
Possibly a documentation bug, if this does get resolved in the community forum and the documentation turns out to be incorrect. Let us know here, I can re-open it as a documentation issue.
