### ISSUE TITLE
DigitalOcean: support floating IPs

### ISSUE THREAD

**Issue by rmoriz** [hashicorp/terraform#3580]
Please support DigitialOcean's Floating IPs, as described on https://www.digitalocean.com/company/blog/floating-ips-start-architecting-your-applications-for-high-availability/

API:
- https://developers.digitalocean.com/documentation/v2/#floating-ips
- https://developers.digitalocean.com/documentation/v2/#floating-ip-actions

**Comment by nekinie** [comment]
:+1:

**Comment by reinoudk** [comment]
I'm working on a PR and wanted to check if it's correct to put Floating IP assignment under the update function? That way you can unassign a Floating IP by leaving out the droplet_id and vise versa.

**Comment by pierrebeaucamp** [comment]
+1

**Comment by catsby** [comment]
@reinoudk That sounds reasonable, yes. Once you have the code working send a PR and we can review and discuss further 

Thanks!

**Comment by reinoudk** [comment]
Just updated the PR, fixing some typos. As it currently stands you can create a Floating IP specifying a droplet_id or region. If you specify both, the DO API automatically assigns the IP to the droplet. This also works if you omit the region.
 
The update function only checks if the droplet_id has changed and consequently (re)assigns or unassigns the IP. The latter creates a bit of an odd situation if you didn't specify a region though. You'd have an IP you can assign, but no indication from your config in which region the IP is available. 

Also, how should a change in region be handled? Floating IP's can't be tranfered and the resource would actually need to be deleted and recreated, changing the ID..

**Comment by patrickheeney** [comment]
It looks like this is implemented in #3748 . Is there anything stopping a merge?

**Comment by jen20** [comment]
@patrickheeney I merged #3748 the other day, but didn't spot this as related in order to close it as well. Closing now!

**Comment by reinoudk** [comment]
@jen20 I think PR #3597 can be closed then as well.

**Comment by jen20** [comment]
Thanks - sorry I didn't spot that one when I merged #3748!
