### ISSUE TITLE
Plan/Apply Azure DevOps Service Connection Issue

### ISSUE THREAD

**Issue by waynejnicklin** [hashicorp/terraform#35814]
### Terraform Version

```shell
1.7.5
```

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

We intend to use an Azure DevOps service connection with read only access to the Azure resources, for our "plan" stage, and then a different Azure DevOps service connection with full write permissions for our "apply" stage. So in the pipeline tasks, we specify this, however, this doesn't seem to work, as it seems to embed the service connection details in the plan file, and then the apply stage fails with insufficient privileges, ignoring the service connection specified in the apply stage.

### Actual Behavior

We intend to use an Azure DevOps service connection with read only access to the Azure resources, for our "plan" stage, and then a different Azure DevOps service connection with full write permissions for our "apply" stage. So in the pipeline tasks, we specify this, however, this doesn't seem to work, as it seems to embed the service connection details in the plan file, and then the apply stage fails with insufficient privileges, ignoring the service connection specified in the apply stage.

### Steps to Reproduce

n/a

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
