### ISSUE TITLE
override_resource scope behavior in tests

### ISSUE THREAD

**Issue by wyardley** [hashicorp/terraform#35813]
### Terraform Version

```shell
Terraform v1.9.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random v3.6.3
```

### Terraform Configuration Files

Given the following terraform code:
```terraform
resource "random_integer" "count" {
  count = 2

  min = 3
  max = 11
}
```

and either of these tests as `main.tftest.hcl`:
```hcl
mock_provider "random" {
  override_resource {
    target = random_integer.count
    values = {
      result = 58
    }
  }
  alias = "fake"
}

override_resource {
  target = random_integer.count
  values = {
    result = 999
  }
} 

run "check_random_integer_parent_override" {
  assert {
    condition     = random_integer.count[0].result == 999
    error_message = "Mocked random integer should be 999"
  }
}

run "check_random_integer_aliased_override" {
  providers = {
    random = random.fake
  }

  assert {
    condition     = random_integer.count[0].result == 58
    error_message = "Mocked random integer should be 58"
  }
}

run "check_random_integer_run_override" {
  override_resource {
    target = random_integer.count
    values = {
      result = 55
    }
  }

  assert {
    condition     = random_integer.count[0].result == 55
    error_message = "Mocked random integer should be 55"
  }
}
```

```hcl
mock_provider "random" {
  override_resource {
    target = random_integer.count
    values = {
      result = 58
    }
  }
  alias = "fake"
}

run "check_random_integer_aliased_override" {
  providers = {
    random = random.fake
  }

  assert {
    condition     = random_integer.count[0].result == 58
    error_message = "Mocked random integer should be 58"
  }
}

run "check_random_integer_run_override" {
  override_resource {
    target = random_integer.count
    values = {
      result = 55
    }
  }

  assert {
    condition     = random_integer.count[0].result == 55
    error_message = "Mocked random integer should be 55"
  }
}
```

### Debug Output

https://gist.github.com/wyardley/83ed2fb691405710b8fc913ddfac3baf

### Expected Behavior

Based on the docs at https://developer.hashicorp.com/terraform/language/tests/mocking, it seems as if `override_resource` should work at different scopes.

### Actual Behavior

It seems that instead, the highest scoped resource override is taking precedence, at least in this case?

```
main.tftest.hcl... in progress
  run "check_random_integer_parent_override"... pass
  run "check_random_integer_aliased_override"... fail
╷
│ Error: Test assertion failed
│ 
│   on main.tftest.hcl line 31, in run "check_random_integer_aliased_override":
│   31:     condition     = random_integer.count[0].result == 58
│     ├────────────────
│     │ random_integer.count[0].result is 999
│ 
│ Mocked random integer should be 58
╵
  run "check_random_integer_run_override"... fail
╷
│ Error: Test assertion failed
│ 
│   on main.tftest.hcl line 46, in run "check_random_integer_run_override":
│   46:     condition     = random_integer.count[0].result == 55
│     ├────────────────
│     │ random_integer.count[0].result is 999
│ 
│ Mocked random integer should be 55
╵
main.tftest.hcl... tearing down
main.tftest.hcl... fail

Failure! 1 passed, 2 failed.
```
### Steps to Reproduce

1. `terraform init`
2. `terraform test`

**Comment by liamcervante** [comment]
Hi @wyardley, thanks for filing this! I can confirm the behaviour you are seeing and I also don't think it's behaving as it should be.

The second run block `check_random_integer_aliased_override` is correctly failing, but the other two failing ones are incorrect.

For the one that is correctly behaving, the overrides defined within the test file take precedence over the overrides defined within the providers. The reason for this is that it possible for mock providers to be defined in dedicated mock files (`.tfmock.hcl`), so the override blocks within the test files are considered the more local definitions for any consideration of precedence.

The remaining failing run blocks are misbehaving though, the run-block defined overrides are definitely more local than the file level definitions and so should be taking precedence when they are apparently not.

**Comment by liamcervante** [comment]
Hi @wyardley - apologies. I now think this is working as intended.

The reason for the apparent misbehaviour of the follow up run blocks is because the resources already exist at this point. The resource overrides and the mock providers only provide values for computed attributes, as in they are replacing the values that would normally be provided by the providers. In the first run block `check_random_integer_aliased_override` the resource is being created, and the computed value is being generated based on the override available to that run block. In the second run block `check_random_integer_run_override`, the resource already exists and so the computed attribute is not being re-evaluated and just keeps the value already in the state, hence the behaviour you are seeing.

If you order the resource to be recreated by the run block you will see the expected behaviour:

```
run "check_random_integer_run_override" {
  override_resource {
    target = random_integer.count
    values = {
      result = 55
    }
  }

  plan_options {
    replace = [
        random_integer.count[0]
    ]
  }

  assert {
    condition     = random_integer.count[0].result == 55
    error_message = "Mocked random integer should be 55"
  }
}
```

Hopefully that makes sense to you - I'm happy to answer any follow up questions!

**Comment by wyardley** [comment]
Thanks, yeah, didn’t realize each run block wasn’t sandboxed / state was retained.

I will play with a couple more realistic examples -- when a module is called in a run block with different variables passed in, is it the same behavior too?

**Comment by liamcervante** [comment]
Each run block attempts to simulate a plan/apply cycle, so ideally a single test file should be the same as you repeatedly running `terraform plan` and `terraform apply` against your configuration for each run block.

So, modules should receive the changed input variables and act as they would if they had changed between a normal cycle.

**Comment by wyardley** [comment]
I see, makes sense, especially in a more integration test focused lifecycle. So in plan-only mode (which won't work in this case), the behavior would line up more with what I've usually seen, since you'd get a totally new plan every time.

According to the test docs, each `tftest.hcl` file will also destroy, so I guess better isolation could also be achieved by putting each tests in its own files. There isn't some top level setting to influence this behavior today, right?

**Comment by liamcervante** [comment]
What you've described isn't currently supported. 

We do have an open feature request for parallelism: https://github.com/hashicorp/terraform/issues/34180. This one is quite popular, and our product team is actively researching it I think.

I think adding a flag or mode for destroy after each run block hasn't been requested before, so filing that as a feature request would get the ball rolling there.

We have a specific label for Terraform Test feature requests if you wanted to view what others have requested and give a 👍 anywhere: https://github.com/hashicorp/terraform/issues?q=is%3Aopen+is%3Aissue+label%3A%22terraform+test%22
