### ISSUE TITLE
Azure APIM polling fails when updating/creating API Object

### ISSUE THREAD

**Issue by darentwh** [hashicorp/terraform#35815]
### Terraform Version

```shell
terraform-version: 1.8.4
azurerm-version: 3.114.0
```

### Terraform Configuration Files

module "apim_api" {
  source                = "<module source>"
  api_name              = var.api_name
  resource_group_name   = var.apim_resource_group_name
  api_management_name   = var.api_management_name
  revision              = var.revision
  display_name          = var.display_name
  path                  = var.path
  protocols             = var.protocols
  service_url           = var.service_url
  content_file          = file(var.content_file)
  content_policy        = var.content_policy
  product_id            = var.product_id
  subscription_required = var.subscription_required
  subscription_key_parameter_names = {
    "header" = var.subscription_key_parameter_names.header
    "query" = var.subscription_key_parameter_names.query
  }
}

### Debug Output

Command execute --> terraform apply -auto-approve -no-color -input=false tfplan 

----------------------------------------------------------------------------------------------------------- 

Error: creating/updating Api 
Service Name: "APIM"
Api: "API NAME;rev=1"): polling after CreateOrUpdate: polling failed

  with module.apim_api.azurerm_api_management_api.apim_api_obj,
  on .terraform/modules/apim_api/module.tf line 1, in resource "azurerm_api_management_api" "apim_api_obj":
   1: resource "azurerm_api_management_api" "apim_api_obj" {

### Expected Behavior

API object to be successfully created as per Swagger JSON

### Actual Behavior

polling fail halfway
> causing the api object to not be created in the portal
> but terraform state file takes it as per swagger that the respective API objects have been created
> causing subsequent applies to fail as terraform cannot find the supposed created API object

### Steps to Reproduce

terraform apply the above

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
