### ISSUE TITLE
Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded │ │   with azurerm_key_vault.global, │   on akv.tf line 50, in resource "azurerm_key_vault" "global": │   50: resource "azurerm_key_vault" "global" { │ 

### ISSUE THREAD

**Issue by NagaSwamy473** [hashicorp/terraform#35823]
### Terraform Version

```shell
1.2.6
```

### Terraform Configuration Files

data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "main" {
  name                        = var.kv_name
  location                    = azurerm_resource_group.main.location
  resource_group_name         = azurerm_resource_group.main.name
  enabled_for_disk_encryption = false
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = true #Cannot be disabled once enabled

  sku_name = "premium"

  #As this is only used for the encryption keys on these VMs, we are only allowing access from the v-subnet
  network_acls {
    bypass                     = "AzureServices"
    default_action             = "Deny"
    virtual_network_subnet_ids = [data.azurerm_subnet.v-subnet.id]
  }
}

# Uses the principal ID (system assigned identity) from these servers to add an access policy to create, wrap and unwrap keys

resource "azurerm_key_vault_access_policy" "server-1" {
  key_vault_id = azurerm_key_vault.main.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = module.windows-servers-image["Server-1"].principal_id

  key_permissions = [
    "Create", "WrapKey", "UnwrapKey"
  ]
  depends_on = [
    module.windows-servers-image
  ]
}

# Uses the principal ID (system assigned identity) from these servers to add an access policy to creat, wrap and unwrap keys

resource "azurerm_key_vault_access_policy" "server-2" {
  key_vault_id = azurerm_key_vault.main.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = module.windows-servers-image["Server-2"].principal_id

  key_permissions = [
    "Create", "WrapKey", "UnwrapKey"
  ]
  depends_on = [
    module.windows-servers-image
  ]
}

#Creates private endpoint for the keyvault
resource "azurerm_private_endpoint" "main" {
  name                = format("pep-%s", var.kv_name)
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  subnet_id           = data.azurerm_subnet.v-subnet.id

  private_service_connection {
    name                           = format("pep-connection-%s", var.kv_name)
    is_manual_connection           = false
    private_connection_resource_id = azurerm_key_vault.main.id
    # sub resource of 'file'
    subresource_names = ["vault"]
  }
}

### Debug Output

azurerm_key_vault.main: Refreshing state... [id=/subscriptions/<_subscription_>/resourceGroups/rg-prod/providers/Microsoft.KeyVault/vaults/kv-prod]

╷
│ Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│ 
│   with azurerm_key_vault.main,
│   on kv.tf line 5, in resource "azurerm_key_vault" "main":

### Expected Behavior

It should append the latest changes on Azure Key Vault during 2nd or 3rd pipeline triggers.

### Actual Behavior

Terraform fails with 'Error: retrieving contact for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded

### Steps to Reproduce

terraform plan and terraform apply

### Additional Context

NA

**Comment by liamcervante** [comment]
Hi @NagaSwamy473, thanks for filing this.

This appears to be an issue with the Azure provider specifically rather than Terraform itself. Could you refile the issue directly with the azure provider team? They can be found here: https://github.com/hashicorp/terraform-provider-azurerm

Thanks!
