### ISSUE TITLE
Crashes on plan when passing a list to cloudflare_record's value

### ISSUE THREAD

**Issue by ema** [hashicorp/terraform#3583]
Hi,
terraform crashes on plan when passing a list to cloudflare_record's value. See https://github.com/hashicorp/terraform/issues/2984 for a similar issue.

Example config follows.

```js
resource "cloudflare_record" "api" {
    domain = "example.org"
    name = "www.example.org"
    value = [ "127.0.0.1" ]
    type = "A"
    ttl = 1
}
```

**Comment by catsby** [comment]
Hey @ema – thanks for opening this. This issue has been fixed by https://github.com/hashicorp/terraform/pull/3009; it now reports a validation error:

```console
Errors:

  * cloudflare_record.api: value must be a single value, not a list
```
