### ISSUE TITLE
when r.ProviderMeta is not set in internal/plugin/grpc_provider.go, the program occurred panic. Should the code be added r.ProviderMeta is not nil in line 418

### ISSUE THREAD

**Issue by dangyy0626** [hashicorp/terraform#35830]
### Terraform Version

```shell
branch main
```

### Terraform Configuration Files

```terraform
...terraform config...
```

### Debug Output

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xa041dc]

goroutine 79 [running]:
github.com/zclconf/go-cty/cty.Type.FriendlyName(...)
        C:/Users/go/pkg/mod/github.com/zclconf/go-cty@v1.12.2/cty/type.go:47
github.com/zclconf/go-cty/cty.testConformance({{0x0?, 0x0?}}, {{0x1bbc330?, 0xc000f0a640?}}, {0xc000051af8, 0x0, 0x0}, 0xc000051b00)
        C:/Users/go/pkg/mod/github.com/zclconf/go-cty@v1.12.2/cty/type_conform.go:137 +0xc5c
github.com/zclconf/go-cty/cty.Type.TestConformance(...)
        C:/Users/go/pkg/mod/github.com/zclconf/go-cty@v1.12.2/cty/type_conform.go:27
github.com/zclconf/go-cty/cty/msgpack.Marshal({{{0x0?, 0x0?}}, {0x0?, 0x0?}}, {{0x1bbc330?, 0xc000f0a640?}})
        C:/Users/go/pkg/mod/github.com/zclconf/go-cty@v1.12.2/cty/msgpack/marshal.go:19 +0x9b
github.com/hashicorp/terraform/internal/plugin.(*GRPCProvider).ReadResource(0xc000434120, {{0x16f7a52, 0xf}, {{{0x1bbc330, 0xc000f0a2c0}}, {0x1554ba0, 0xc00105f3b0}}, {0x25aa080, 0x0, 0x0}, ...})
        D:/work_space/terraform/internal/plugin/grpc_provider.go:379 +0x385

### Expected Behavior

no panic

### Actual Behavior

nil pointer panic

### Steps to Reproduce

run the following codes

`resp = p.provider.ReadResource(providers.ReadResourceRequest{

			TypeName:     info.Type,

			PriorState:   priorState,

			Private:      []byte{},

		})
`

**Comment by jbardin** [comment]
Hi @dangyy0626,

Thanks for filing the issue. The line numbers in your stack trace don't match up to current versions, are you certain this was pulled from `main`? Your example code also doesn't match the structure of `internal/plugin/grpc_provider.go`, can you show exactly what you are looking at? 

Thanks!

**Comment by dangyy0626** [comment]
> Hi @dangyy0626,
> 
> Thanks for filing the issue. The line numbers in your stack trace don't match up to current versions, are you certain this was pulled from `main`? Your example code also doesn't match the structure of `internal/plugin/grpc_provider.go`, can you show exactly what you are looking at?
> 
> Thanks!

**Comment by dangyy0626** [comment]
> Hi @dangyy0626,
> 
> Thanks for filing the issue. The line numbers in your stack trace don't match up to current versions, are you certain this was pulled from `main`? Your example code also doesn't match the structure of `internal/plugin/grpc_provider.go`, can you show exactly what you are looking at?
> 
> Thanks!

Thanks for your reply!

in the line number 418-425
`
	if metaSchema.Block != nil {
		metaMP, err := msgpack.Marshal(r.ProviderMeta, metaSchema.Block.ImpliedType())
		if err != nil {
			resp.Diagnostics = resp.Diagnostics.Append(err)
			return resp
		}
		protoReq.ProviderMeta = &proto.DynamicValue{Msgpack: metaMP}
	}

`


should  "r.ProviderMeta" be validated?   I guess it should be this:



`
	if metaSchema.Block != nil && !r.ProviderMeta.IsNull(){
		metaMP, err := msgpack.Marshal(r.ProviderMeta, metaSchema.Block.ImpliedType())
		if err != nil {
			resp.Diagnostics = resp.Diagnostics.Append(err)
			return resp
		}
		protoReq.ProviderMeta = &proto.DynamicValue{Msgpack: metaMP}
	}

`

**Comment by jbardin** [comment]
No, a null cty value is perfectly valid, and `r.ProviderMeta` is allowed to be null there. Terraform core sets that to be `null` most of the time, so that is not going to be causing a panic. 

Can you show the actual problem which is causing the panic for you?

**Comment by jbardin** [comment]
Since we have not heard back in a while I'm going to close the issue. If you have any updates regarding the issue, feel free to open a new issue with the requested information. If you have more questions, you can also use [the community forum](https://discuss.hashicorp.com/c/terraform-core) where there are more people ready to help.

Thanks!
