### ISSUE TITLE
api resource policy issue

### ISSUE THREAD

**Issue by Mohamed-Eleraki** [hashicorp/terraform#35852]
### Terraform Version

```shell
Terraform v1.9.7
```

### Terraform Configuration Files

```terraform
resource "aws_api_gateway_rest_api_policy" "api_uat_policy_01" {
  rest_api_id = aws_api_gateway_rest_api.rest_api_01.id

  policy = file("${path.module}/scripts/api_resource_policy.json")
}

```

### Debug Output

Not an API changes

### Expected Behavior

update the aws farm with no require to redeploy the api

### Actual Behavior

by using the 1.9.7 version, while making any updates into my code _(i.e. any update not related to the api)_ requires redeploying the API in order to reflect the API resource policy.
Therefore, my main issue lies in the API resource policy not working after any terraform apply, even if the change does not relate to the API. To fix this I must after each apply redeploy the API manually from the AWS console.

### Steps to Reproduce

terraform init
terraform apply --auto-approve

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by Mohamed-Eleraki** [comment]
Thank you Jbardin for your quick response.
