### ISSUE TITLE
Issue with AWS Glue Job script_location Not Recognizing S3 Path in Terraform

### ISSUE THREAD

**Issue by Prashanteppalpalli** [hashicorp/terraform#35861]
### Terraform Version

```shell
Terraform v1.5.7
+ provider registry.terraform.io/hashicorp/aws v5.70.0
```

### Terraform Configuration Files
```
resource "aws_glue_job" "example" {
  name     = "example-job"
  role_arn = aws_iam_role.example.arn
  command {
    name            = "glueetl"
    script_location = "s3://your-bucket-name/path/to/your-script.py"
    python_version  = "3"
  }
  # other configurations
}
```

### Debug Output

Troubleshooting Steps Taken:

Verified the S3 path and file existence.
Ensured the IAM role has the necessary permissions (s3:GetObject, s3:ListBucket).
Compared the manually added script path with the Terraform configuration.
Enabled detailed logging in Terraform (TF_LOG=DEBUG).
Checked for hidden characters or typos in the S3 path.

### Expected Behavior

The AWS Glue job should recognize the script_location specified in the Terraform configuration and successfully create the job without errors.

### Actual Behavior

The Terraform apply process successfully but when I go to the AWS console --> Glue console --> ETL jobs --> My job --> Script section, it shows error and says [s3.<region>.amazonaws.com] getObject: NoSuchKey: The specified key does not exist.

Manual intervention from AWS console works fine and creates that script file in s3 location but via terraform it give above error. 

### Steps to Reproduce

terraform init
terraform apply

### Additional Context

NA

### References

NA

**Comment by crw** [comment]
Hello @Prashanteppalpalli,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use the [community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
