### ISSUE TITLE
aws_instance tag does not get updated.

### ISSUE THREAD

**Issue by kriziavelciu** [hashicorp/terraform#35869]
### Terraform Version

```shell
required_version = "~> 1.9.4"
```

### Terraform Configuration Files

resource "aws_instance" "instance" {
    ami                         = local.ami_id[var.os_type]
    instance_type               = var.instance_type
    key_name                    = var.key_name
    subnet_id                   = var.subnet_id
    associate_public_ip_address = var.associate_public_ip_address
    iam_instance_profile        = var.iam_instance_profile
    credit_specification {
        cpu_credits             = "standard"
    }

    vpc_security_group_ids      = var.security_groups

    metadata_options {
        instance_metadata_tags  = "enabled"
        http_endpoint           = "enabled"
        http_tokens             = "required"
    }
    root_block_device {
        volume_type             = var.volume_type
        volume_size             = var.root_volume_size
        delete_on_termination   = var.root_delete_on_termination
        encrypted               = var.volume_encryption
        tags = {
            Name        = local.instance_name
            # Customer    = "${var.customer}"
            # Project     = "${var.project}"
            # Version     = "${var.swversion}"
            # Cloud       = "${var.cloud}"
            # Deployment  = "${var.deploy}"
            # Environment = "${var.environment}"
        }
    }
    lifecycle {
        prevent_destroy = false
        ignore_changes  = [user_data, ami, key_name, tags, metadata_options]
    }
    tags = {
        Name = "${local.instance_name}"
        
    }
}

### Debug Output

-

### Expected Behavior

 ~ resource "aws_instance" "instance" {
     
        tags                                 = {
            **_"Name" = "AWWS-INTWEBB01" -> "AWWS-INTWEB01"_**
        }
        # (39 unchanged attributes hidden)

      ~ root_block_device {
          ~ tags                  = {
              ~ "Name" = "AWWS-INTWEBB01" -> "AWWS-INTWEB01"
            }
            # (10 unchanged attributes hidden)
        }

        # (8 unchanged blocks hidden)
    }

### Actual Behavior

 ~ resource "aws_instance" "instance" {
      
        tags                                 = {
            "Name" = "AWWS-INTWEBB01"
        }
        # (39 unchanged attributes hidden)

      ~ root_block_device {
          ~ tags                  = {
              ~ "Name" = "AWWS-INTWEBB01" -> "AWWS-INTWEB01"
            }
            # (10 unchanged attributes hidden)
        }

        # (8 unchanged blocks hidden)
    }

### Steps to Reproduce

terraform plan
terraform apply

### Additional Context

Tags for both Root Device  Volume and Instance Tag (Name) is referencing the same local variable instance_name :

**instance_name = "${var.client_name}-${var.environment_name}${var.instance_name}"**

But the Name tag for the instance is not getting updated.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
