### ISSUE TITLE
IAM Data Source causes deletion/recreation of AWS Cognito IAM Role

### ISSUE THREAD

**Issue by moberlander08** [hashicorp/terraform#35871]
### Terraform Version

```shell
Terraform v1.8.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.72.1
```

### Terraform Configuration Files

```terraform
data "aws_iam_policy_document" "authenticated" {
  statement {
    effect = "Allow"

    principals {
      type        = "Federated"
      identifiers = ["cognito-identity.amazonaws.com"]
    }

    actions = ["sts:AssumeRoleWithWebIdentity"]

    condition {
      test     = "StringEquals"
      variable = "cognito-identity.amazonaws.com:aud"
      values   = [aws_cognito_identity_pool.this.id]
    }

    condition {
      test     = "ForAnyValue:StringLike"
      variable = "cognito-identity.amazonaws.com:amr"
      values   = ["authenticated"]
    }
  }
}

resource "aws_iam_role" "authenticated" {
  name               = "${var.identity_pool_name}-iam-role"
  assume_role_policy = data.aws_iam_policy_document.authenticated.json

  tags = var.tags
}

```

```
### Debug Output

 # aws_iam_role.authenticated will be updated in-place
  ~ resource "aws_iam_role" "authenticated" {
      ~ assume_role_policy    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRoleWithWebIdentity"
                      - Condition = {
                          - "ForAnyValue:StringLike" = {
                              - "cognito-identity.amazonaws.com:amr" = "authenticated"
                            }
                          - StringEquals             = {
                              - "cognito-identity.amazonaws.com:aud" = "REDACTED-POOLID"
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - Federated = "cognito-identity.amazonaws.com"
                        }
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
```
### Expected Behavior

The IAM Assume Role policy should not be updating after a successfully apply/creation

### Actual Behavior

the assume_role_policy is getting flip back and forth, from apply and removal on each successfully run. 

### Steps to Reproduce

Unable to supply due to sensitive ids.

### Additional Context

Can confirm that removing the data block and supplying a "static" policy block/eof for the assume_role_policy is allowing the resource to not be recreated/destroyed on each terraform run.  Additionally the same output of the terraform plan/apply was occurring on our gitlab pipelines. 

![Screenshot 2024-10-17 at 10 52 26 AM](https://github.com/user-attachments/assets/37fa03b6-bc83-4a1d-83fa-41ad4d02d08f)

### References

#29716, appears to be similar behavior.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
