### ISSUE TITLE
Dynamic subnet block in azurerm_virtual_network complaining about address_prefix

### ISSUE THREAD

**Issue by mahikasanwal** [hashicorp/terraform#35879]
### Terraform Version

```shell
terraform -version
Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/azure/azapi v1.15.0
+ provider registry.terraform.io/hashicorp/azurerm v4.4.0
+ provider registry.terraform.io/hashicorp/null v3.2.3
+ provider registry.terraform.io/hashicorp/random v3.6.3
+ provider registry.terraform.io/hashicorp/time v0.12.1
```

### Terraform Configuration Files

resource "azurerm_virtual_network" "vnet" {
  for_each            = { for vnet in var.vnets : vnet.name => vnet }
  name                = "${var.environment}-${var.name_prefix}-${each.key}"
  location            = azurerm_resource_group.ntwk_rg.location
  resource_group_name = azurerm_resource_group.ntwk_rg.name
  address_space       = [each.value.cidr]
  dns_servers         = length(var.vnet-dns) > 0 ? var.vnet-dns : null

  dynamic "subnet" {
    for_each = each.value.subnets
    content {
      name           = "${var.environment}-${var.name_prefix}-${subnet.value.name}"
      address_prefix = subnet.value.cidr

### Debug Output

Unsupported argument
│ 
│   on ../../modules/ntwk/network/main.tf line 24, in resource "azurerm_virtual_network" "vnet":
│   24:       address_prefix = subnet.value.cidr
│ 
│ An argument named "address_prefix" is not expected here. Did you mean "address_prefixes"?

### Expected Behavior

it should support address_prefix as it is working fine with terraform version 1.9.4 

### Actual Behavior

it should support address_prefix as it is working fine with terraform version 1.9.4 

### Steps to Reproduce

terraform validate

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
