### ISSUE TITLE
Terraform does not update complete chain of dependencies for a given `-target`.

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform#35874]
### Terraform Version

```shell
terraform --version
Terraform v1.9.7
on darwin_arm64
```
```


### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    # 3rd party provider should be defined inside module
    acme = {
      source  = "vancluever/acme"
      version = "~> 2.26"
    }
  }
}

provider "acme" {
  # server_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
  server_url = "https://acme-v02.api.letsencrypt.org/directory"
}

data "aws_route53_zone" "base_domain" {
  name = var.domain_name
}

resource "tls_private_key" "acme" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P384"
}

resource "acme_registration" "certbot" {
  account_key_pem = tls_private_key.acme.private_key_pem
  email_address   = "xxx"
}

resource "acme_certificate" "ssl" {
  account_key_pem           = acme_registration.certbot.account_key_pem
  key_type                  = "P384"
  common_name               = data.aws_route53_zone.base_domain.name
  subject_alternative_names = ["*.${data.aws_route53_zone.base_domain.name}"]

  dns_challenge {
    provider = "route53"

    config = {
      AWS_HOSTED_ZONE_ID = data.aws_route53_zone.base_domain.zone_id
    }
  }

  depends_on = [acme_registration.certbot]
}

resource "aws_acm_certificate" "ssl" {
  certificate_body  = acme_certificate.ssl.certificate_pem
  private_key       = acme_certificate.ssl.private_key_pem
  certificate_chain = acme_certificate.ssl.issuer_pem
  depends_on        = [acme_certificate.ssl]
}
```

### Debug Output

2024-10-17T13:05:56.325-0400 [TRACE] AttachDependenciesTransformer: module.private-cloud.aws_acm_certificate.ssl depends on [data.external.env module.private-cloud.acme_certificate.ssl module.private-cloud.acme_registration.certbot module.private-cloud.data.aws_route53_zone.base_domain module.private-cloud.tls_private_key.acme]

### Expected Behavior

I expect that `aws_acm_certificate.ssl` resource4 will be updated if `acme_certificate.ssl` resource was changed even if I use target only for `acme_certificate_ssl`
Like this:
```
  # module.private-cloud.acme_certificate.ssl will be created
  + resource "acme_certificate" "ssl" {
      + account_key_pem               = (sensitive value)
      + cert_timeout                  = 30
      + certificate_domain            = (known after apply)
      + certificate_not_after         = (known after apply)
      + certificate_p12               = (sensitive value)
      + certificate_pem               = (known after apply)
      + certificate_serial            = (known after apply)
      + certificate_url               = (known after apply)
      + common_name                   = "XXX"
      + disable_complete_propagation  = false
      + id                            = (known after apply)
      + issuer_pem                    = (known after apply)
      + key_type                      = "P384"
      + min_days_remaining            = 30
      + must_staple                   = false
      + pre_check_delay               = 0
      + private_key_pem               = (sensitive value)
      + revoke_certificate_on_destroy = true
      + subject_alternative_names     = [
          + "*.xxx",
        ]

      + dns_challenge {
          + config   = (sensitive value)
          + provider = "route53"
        }
    }

  # module.private-cloud.aws_acm_certificate.ssl will be updated in-place
  ~ resource "aws_acm_certificate" "ssl" {
      ~ certificate_body          = <<-EOT
 ....
```
This is how terraform designed to work:
>Hi @EugenKon, I'm going to close this issue as I believe this is a case of Terraform behaving as expected in terms of applying changes to the complete chain of dependencies for a given target.

https://github.com/hashicorp/terraform/issues/34962 @liamcervante 

### Actual Behavior

Terraform does **not** update the complete chain of dependencies.
```
terraform plan -state ../../state.d/terraform.tfstate -out ../../state.d/terraform.plan -target module.private-cloud.acme_certificate.ssl
...
Terraform used the selected providers to generate the following execution plan. Resource actions
are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.private-cloud.acme_certificate.ssl will be created
  + resource "acme_certificate" "ssl" {
      + account_key_pem               = (sensitive value)
      + cert_timeout                  = 30
      + certificate_domain            = (known after apply)
      + certificate_not_after         = (known after apply)
      + certificate_p12               = (sensitive value)
      + certificate_pem               = (known after apply)
      + certificate_serial            = (known after apply)
      + certificate_url               = (known after apply)
      + common_name                   = "xxx"
      + disable_complete_propagation  = false
      + id                            = (known after apply)
      + issuer_pem                    = (known after apply)
      + key_type                      = "P384"
      + min_days_remaining            = 30
      + must_staple                   = false
      + pre_check_delay               = 0
      + private_key_pem               = (sensitive value)
      + revoke_certificate_on_destroy = true
      + subject_alternative_names     = [
          + "*.xxx",
        ]

      + dns_challenge {
          + config   = (sensitive value)
          + provider = "route53"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce

1. Create the resources above
2. Change the resource `module.private-cloud.acme_certificate.ssl`. eg. remove it from the state
3. terraform plan -target module.private-cloud.acme_certificate.ssl
4. terraform apply

**Comment by jbardin** [comment]
Hi @EugenKon,

> I expect that aws_acm_certificate.ssl resource4 will be updated if acme_certificate.ssl resource was changed even if I use target only for acme_certificate_ssl

That expectation is incorrect. If you target `acme_certificate.ssl` Terraform will only include the resources required update the target. The `aws_acm_certificate.ssl` resource is not required for that operation, so it won't be included. If you want all dependencies up to `aws_acm_certificate.ssl` to be included in the plan, then that is the resource you need to target.

**Comment by EugenKon** [comment]
@jbardin In the PR I mentioned here there was different situation: the dependant resource is updated automatically.
I complained that only resources that I list for `-target` should be updated, but terraform updated other depended resources.
If terraform was designed to work in a way you described here, then https://github.com/hashicorp/terraform/issues/34962 PR should be re-opened.

**Comment by jbardin** [comment]
@EugenKon, I don't see a linked PR, was there another PR you meant to reference?

The behavior in #34962 is the same as here, and both result in the expected plan output. The named targets and all their required dependencies are planned in both cases. In this example the `aws_acm_certificate.ssl` resource is neither targeted, nor required to plan the targeted resources.

The `-target` CLI flag is not something typically used in the normal workflow, and is usually only a way to temporarily workaround a problem when something went wrong. It's not designed to cherry-pick changes to apply from a complete plan, rather it reduces as much as possible what gets planned in the first place.
