### ISSUE TITLE
The values of sku_name for the azurerm_powerbi_embedded resource are not complete.

### ISSUE THREAD

**Issue by dd8zc** [hashicorp/terraform#35875]
### Terraform Version

```shell
Terraform v1.9.7
```

### Use Cases

Power BI Embedded is available in SKUs from A1 to A8. However, Terraform only supports A1 to A6.

### Attempted Solutions

Ugly workaround where we scale via shell after deployment.

### Proposal

A7 and A8 should be valid values.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AzureRM provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/terraform-providers/terraform-provider-azurerm/issues. If you have questions about Terraform or the AzureRM provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
