### ISSUE TITLE
Incorrect resource graph and order of operations

### ISSUE THREAD

**Issue by dhrkumar** [hashicorp/terraform#35881]
### Terraform Version

```shell
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.72.1
```

### Terraform Configuration Files

```terraform
resource "aws_vpc" "vpc" {
  cidr_block           = "10.0.0.0/16"
}

resource "aws_security_group" "sg_1" {
  name        = "sg1"
  vpc_id      = aws_vpc.vpc.id
}

# Comment or remove this resource to reproduce the issue
resource "aws_security_group" "sg_2" {
  name        = "sg2"
  vpc_id      = aws_vpc.vpc.id
}

resource "aws_subnet" "private" {
  vpc_id     = aws_vpc.vpc.id
  cidr_block = "10.0.1.0/24"
  tags = {
    Name = "Main"
  }
}

resource "aws_network_interface" "eni" {
  subnet_id       = aws_subnet.private.id
  private_ips     = ["10.0.1.50"]
  security_groups = [aws_security_group.sg_1.id, aws_security_group.sg_2.id] # remove sg2 reference from here
}
```

### Debug Output

Initial apply - https://gist.github.com/dhrkumar/86b2607fa86ca1840ef8fa32a965d0c5
Update apply - https://gist.github.com/dhrkumar/732767e8d3d864c72e13276070228acd

### Expected Behavior

Security group named _sg2_ should have been removed from elastic network interface and the security group should have been destroyed.

### Actual Behavior

Fails to destroy security group named _sg2_ as Elastic Network Interface is not updated to remove the security group usages before destroying the security group.

### Steps to Reproduce

1. terraform apply
2. comment/remove security group named _sg2_ and its references from configuration file
3. terraform apply

### References

https://github.com/hashicorp/terraform-provider-aws/issues/38444

**Comment by usmanovbf** [comment]
bug is not reproducible for me. tested with  Localstack

```
$ terraform --version            
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.72.1
```

Logs after removing from the code these resources:

```
 terraform apply  -auto-approve 
aws_security_group.sg_2: Refreshing state... [id=sg-91be9a636307c4454]
aws_vpc.vpc: Refreshing state... [id=vpc-21b1982d]
aws_security_group.sg_1: Refreshing state... [id=sg-39b216f6237082b8b]
aws_subnet.private: Refreshing state... [id=subnet-0d075df2]
aws_network_interface.eni: Refreshing state... [id=eni-329ad234]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  # aws_network_interface.eni will be updated in-place
  ~ resource "aws_network_interface" "eni" {
        id                        = "eni-329ad234"
      ~ security_groups           = [
          - "sg-91be9a636307c4454",
            # (1 unchanged element hidden)
        ]
        tags                      = {}
        # (21 unchanged attributes hidden)
    }

  # aws_security_group.sg_2 will be destroyed
  # (because aws_security_group.sg_2 is not in configuration)
  - resource "aws_security_group" "sg_2" {
      - arn                    = "arn:aws:ec2:us-east-1:000000000000:security-group/sg-91be9a636307c4454" -> null
      - description            = "Managed by Terraform" -> null
      - egress                 = [] -> null
      - id                     = "sg-91be9a636307c4454" -> null
      - ingress                = [] -> null
      - name                   = "sg2" -> null
      - owner_id               = "000000000000" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {} -> null
      - tags_all               = {} -> null
      - vpc_id                 = "vpc-21b1982d" -> null
    }

Plan: 0 to add, 1 to change, 1 to destroy.
aws_security_group.sg_2: Destroying... [id=sg-91be9a636307c4454]
aws_security_group.sg_2: Destruction complete after 0s
aws_network_interface.eni: Modifying... [id=eni-329ad234]
aws_network_interface.eni: Modifications complete after 0s [id=eni-329ad234]
╷
│ Warning: AWS account ID not found for provider
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on test.tf line 1, in provider "aws":
│    1: provider "aws" {
│ 
│ See https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_requesting_account_id for implications.
│ 
│ (and one more similar warning elsewhere)
╵

Apply complete! Resources: 0 added, 1 changed, 1 destroyed.
```

**Comment by jbardin** [comment]
@dhrkumar,

The order of operations applied is exactly that which is defined in the configuration. If you need the `aws_network_interface` resource to be updated before the `aws_security_group` is destroyed, them that must be created with the `create_before_destroy` `lifecycle` option.

@usmanovbf, The failure would depend on the specific behavior of the resources in AWS, so if it does fail it seems that LocalStack does not exactly replicate the behavioral details of the `aws_network_interface` and `aws_security_group`.

Thanks!

**Comment by dhrkumar** [comment]
@jbardin Terraform should determine the order of operation(implicit dependency) based on references. Since the resource `aws_security_group` is being referenced in `aws_network_interface`, update to `aws_network_interface` has to be performed before destroying `aws_security_group` to remove references. Dependency graph generated by Terraform `graph` command is also not correct as it doesn't show `aws_security_group` `sg2` being referenced by `aws_network_interface`.
![graph](https://github.com/user-attachments/assets/5d5a7740-f347-4d8a-84d0-a22f4bd7d9cd)


As per [Terraform documentation Resource Dependencies](https://developer.hashicorp.com/terraform/language/resources/behavior#resource-dependencies)
> Most resource dependencies are handled automatically. Terraform analyses any [expressions](https://developer.hashicorp.com/terraform/language/expressions) within a resource block to find references to other objects, and treats those references as implicit ordering requirements when creating, updating, or destroying resources. Since most resources with behavioral dependencies on other resources also refer to those resources' data, it's usually not necessary to manually specify dependencies between resources.

About the suggestion to use `create_before_destroy` `lifecycle` option for resources have been a challenge for us specially if resources are in a module, setting  `create_before_destroy` `lifecycle`  to `true` make it impossible to apply change any non-identifier attribute value which forces the resource replacement. I have added `create_before_destroy` `lifecycle`  to `true` which makes impossible to change description and apply.
```terraform
resource "aws_vpc" "vpc" {
  cidr_block           = "10.0.0.0/16"
}

resource "aws_security_group" "sg_1" {
  name        = "sg1"
  vpc_id      = aws_vpc.vpc.id
}

resource "aws_security_group" "sg_2" {
  name        = "sg2"
  description = "sg2" # update description
  vpc_id      = aws_vpc.vpc.id
  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_subnet" "private" {
  vpc_id     = aws_vpc.vpc.id
  cidr_block = "10.0.1.0/24"
  tags = {
    Name = "Main"
  }
}

resource "aws_network_interface" "eni" {
  subnet_id       = aws_subnet.private.id
  private_ips     = ["10.0.1.50"]
  security_groups = [aws_security_group.sg_1.id, aws_security_group.sg_2.id]
}
```

I was able to make a small change to fix the issue and can raise a PR for review.

**Comment by jbardin** [comment]
@dhrkumar,

Please see https://github.com/hashicorp/terraform/blob/main/docs/destroying.md for some more details around the the order of operations. Because the default ordering is to destroy before create, and the creation must happen before dependencies can be updated, the destroy or `aws_security_group` will happen first. Changing that order will either break other established use cases, create cycles, or simply make the apply operations inconsistent.

**Comment by dhrkumar** [comment]
@jbardin,
Thanks for sharing document detailing various scenarios and expected order of operations. The order of operation for resource replacement is not considering a scenario where if a resource like  `aws_security_group` with a specific attribute `name` value should be unique and also "registered" by other resources like `aws_network_interface` goes replacement.
```terraform
resource "aws_vpc" "vpc" {
  cidr_block           = "10.0.0.0/16"
}

resource "aws_subnet" "private" {
  vpc_id     = aws_vpc.vpc.id
  cidr_block = "10.0.1.0/24"
}


resource "aws_security_group" "sg_1" {
  name        = "sg1"
  description = "sg1" # update description to force replacement
  vpc_id      = aws_vpc.vpc.id
  timeouts {
    delete = "1m"
  }
}

resource "aws_network_interface" "eni" {
  subnet_id       = aws_subnet.private.id
  private_ips     = ["10.0.1.50"]
  security_groups = [aws_security_group.sg_1.id]
  lifecycle {
    create_before_destroy = true
  }
}
```
Flipping `create_before_destroy` `lifecycle`  also doesn't help to apply the change.

**Comment by jbardin** [comment]
The scenario with `aws_security_group` you describe is actually something I commonly refer to as the "registration pattern". That pattern requires `create_before_destroy` and [should  be documented](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group) by the provider, which it seems to be in this case.

The resource should be applied first using `create_before_destroy`, because it's the instance that is being removed which dictates the destroy order. If you are keeping the resource in the configuration then changing the `create_before_destroy` can often be used to override the stored state, which there are tests to confirm. If you can show otherwise, that might be something to fix, but the requirement for `create_before_destroy` to set the order of operations is not something which can be changed.

**Comment by dhrkumar** [comment]
Following guidance provided on [the provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group), I had to use `replace_triggered_by` `lifecycle` to apply the change which forces replacement.
```terraform
resource "aws_vpc" "vpc" {
  cidr_block           = "10.0.0.0/16"
}

resource "aws_subnet" "private" {
  vpc_id     = aws_vpc.vpc.id
  cidr_block = "10.0.1.0/24"
}


resource "aws_security_group" "sg_1" {
  name        = "sg1"
  description = "sg"
  vpc_id      = aws_vpc.vpc.id
  timeouts {
    delete = "1m"
  }
}

resource "aws_network_interface" "eni" {
  subnet_id       = aws_subnet.private.id
  private_ips     = ["10.0.1.50"]
  security_groups = [aws_security_group.sg_1.id]
  lifecycle {
    replace_triggered_by = [aws_security_group.sg_1.id]
  }
}
```
One of the suggestions will be to introduce a new attribute in Terraform plugin SDK to flag the attribute which follows "registration pattern" to indicate that the resource will need replacement if a registered resource is marked for replacement.
Thank you for explaining intricacies involved in ordering destroy of resources.
