### ISSUE TITLE
ignore_changes does not work for ec2 tags.

### ISSUE THREAD

**Issue by djaboxx** [hashicorp/terraform#3589]
I'm seeing an issue with regards to tags. We use Ansible to configure our ec2 instances. Ansible targets the correct new hosts (we dont want to touch the previously configured hosts) by the presence of a tag. I'd like Terraform to be able to initially create a tag on an ec2 instance, let Ansible remove the tag, and then have Terraform ignore the tag when it's not longer present.

**Comment by phinze** [comment]
Hi @djaboxx - working on `ignore_changes` fixes over in #5627 - head there for updates! :+1:
