### ISSUE TITLE
Template rendering isn't used in plan

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/terraform#3592]
When using a template for setting metadata on a gce instance with following code

```
resource "template_file" "template" {
    filename = "google-container-manifest.yml"
    vars {
        ...
    }
}

resource "google_compute_instance" "instance" {
    metadata {
        google-container-manifest = "${template_file.google_container_manifest.rendered}"
    }   
}    
```

The plan shows it will change the metadata to an empty string

```
~ google_compute_instance.instance
    metadata.#:                         "" => "<computed>"
    metadata.google-container-manifest: "current content" => ""

+ template_file.manifest
    filename:                "" => "google-container-manifest.yml"
    rendered:                "" => "<computed>"
    vars.#:                  "" => "x"
```

This seems incorrect, I expect the metadata not to change when I'm replacing a ${file(...)} interpolation with a template.

**Comment by lwander** [comment]
Is this problem unique to the `metadata` attribute, or does it happen with other updateable attributes as well?

**Comment by mitchellh** [comment]
This is fixed in that the plan now says "computed" but still isn't prerendered which is in #8669
