### ISSUE TITLE
vSphere: Why creating machines from scratch?

### ISSUE THREAD

**Issue by mkuzmin** [hashicorp/terraform#3593]
@tkak, your vSphere plugin provides two modes of launching new virtual machines:
1) Clone a machine from a template,
2) Create a new machine from scratch, add an empty disk, and configure all hardware settings explicitly.

The second feature confuses me. What was a reason for it? Do you use it yourself? If so, why do you prefer setting up machines by PXE at runtime, instead of preparing static templates by Packer?

Terraform is a tool for *launching* infrastructure, not creating it. This feature complicates codebase, and confuses people. Do you think we can drop it?

@rubbish, I'm also interested to hear your opinion on this.

**Comment by rubbish** [comment]
We currently only clone from template that are built from packer using https://github.com/Banno/packer-post-processor-vsphere-ova. 

However, in the future we might have a mix of metal and vsphere which we would use PXE to set those up. And in a way of simplifying things, we might just change our vsphere to just do PXE boot as well.

That said, it might be a possible case to boot up a blank VM and attach an ISO to install things.

My vote is for keeping the vSphere provisioner to launch both from template and blank.

**Comment by chrislovecnm** [comment]
@mkuzmin does that answer your question?  If so, can we close this??

**Comment by chrislovecnm** [comment]
@mkuzmin can we close this??

**Comment by chrislovecnm** [comment]
@catsby please close
