### ISSUE TITLE
Terraform does not output though it is planned

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform#35932]
### Terraform Version

```shell
terraform version
Terraform v1.9.8
on darwin_arm64
```

### Terraform Configuration Files

details are here: https://github.com/hashicorp/terraform-provider-aws/issues/39969

### Debug Output

see above

### Expected Behavior

When values does not exists, but it is planned to be as output it should be in output.
In this case I expect that terraform will warn that value does not exists and why it suppress output. So I do not expect it is suppressed, because on that output another custom tool relies.

### Actual Behavior

The output suppressed when value does not exists

### Steps to Reproduce

1. Create Redis cluster with  the next options
```
  cluster_mode               = "disabled"
  automatic_failover_enabled = false
  num_cache_clusters         = 1

```
2. Create output 
```

output "redisEndpoint" {
  value = module.private-cloud.redisEndpoint
}
output "redisEndpoint" {
  description = "Redis endpoint"
  value       = aws_elasticache_replication_group.redis.configuration_endpoint_address
}

```
3. Plan/apply

### Additional Context

If I do the next change: 
![image](https://github.com/user-attachments/assets/655ba828-2c8e-48d0-b5dd-6e636abef3a4)
It ouitputs again.

**Comment by jbardin** [comment]
Hi @EugenKon,

Terraform is working as intended here. Terraform considers the assignment of `null` to be equivalent of not being set at all. For root module outputs, `null` is used to indicate that there is no output value and it is not recoded in the state, so in practice the lack of output can be considered equal to a `null` value.

**Comment by EugenKon** [comment]
Here two cases which should be distinguished:
1. Key is defined, but value is null
2. Key is not defined, value is null

**Comment by jbardin** [comment]
Unfortunately the design of root module output was not created with that distinction in mind.
For an enhancement request to implement something like that, you can follow #34080.

Thanks!

**Comment by EugenKon** [comment]
Thanks for the link. It is helpful.
If that will not be implemented or when running without `--json-null`. Could it be possible to warn about hidden options from output? This could save a lot of time. @jbardin

**Comment by jbardin** [comment]
Given that this is the established behavior for outputs, I suspect adding a warning for users that null outputs won't be shown may not be accepted (even if it doesn't violate the v1 compatibility promises). Since null outputs are not recorded in state at all, given the limitations of the command there's no way currently to determine if it is actually null without running a plan and/or apply to reevaluate the output.

If this is something you often encounter, one workaround might be to put the reference in a collection of some type, like
```
value = [aws_elasticache_replication_group.redis.configuration_endpoint_address]
```
so that the output value is never completely null.

**Comment by EugenKon** [comment]
This is not a problem, that the key was hidden. I could understand reasoning for that. I can implement workaround to bring that output visible always, eg `coalesce`.
The problem is to understand what happened when I faced the issue **first time** with this output: it was planned to be there, but then **silently** disappears. It would be nice to warn users about this behaviour during `terraform apply`.
