### ISSUE TITLE
aws_docdb_cluster - AZ issue with force recreation action that is not needed

### ISSUE THREAD

**Issue by fabiobeoni** [hashicorp/terraform#35934]
Issue closed but the problem is still there:

_Originally posted by @ghost in https://github.com/hashicorp/terraform-provider-aws/issues/19451#issuecomment-1031570501_

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
