### ISSUE TITLE
using terraform output and count > 1

### ISSUE THREAD

**Issue by sramakr** [hashicorp/terraform#3594]
I want use terraform output when provisioning multiple servers ( using count > 1 ) on openstack.

i believe it's looking for hardcoded name , and it's not working correctly. Is there any option to specify regex or any other ways ?

My config files

resource "openstack_compute_instance_v2" "test_server2" {
  name = "tf-test3"
  region = "${var.region}"
  image_id = "${var.image_id}"
  flavor_id = "${var.flavor_id}"
  metadata {
    this = "that"
    }
  key_pair = "${var.key_pair}"
  security_groups = ["daas_ssh"]
  count="${var.count}"
  }

output "ip" {
    value = "${openstack_compute_instance_v2.test_server2.access_ip_v4}"
}

Appreciate any help.

Thanks
Sriram

**Comment by lwander** [comment]
Someone was having a similar issue here #3362, let me know if my explanation there helps.

**Comment by sramakr** [comment]
perfect works.


for reference,

resource "openstack_compute_instance_v2" "test_server2" {
  name = "tf-test3"
  region = "${var.region}"
  image_id = "${var.image_id}"
  flavor_id = "${var.flavor_id}"
  metadata {
        this = "that"
        }
  key_pair = "${var.key_pair}"
  security_groups = ["daas_ssh"]
  count="${var.count}"
  }

output "ip" {
    value = "${join(",",openstack_compute_instance_v2.test_server2.*.access_ip_v4)}"
}

**Comment by apparentlymart** [comment]
Seems like the question is answered here, but I wonder if there's something to be added to the docs here given that two different people were tripped up by this already.

**Comment by lwander** [comment]
There is documentation [here](https://www.terraform.io/docs/configuration/interpolation.html)

**Comment by lwander** [comment]
Maybe adding another example along these lines would be nice.

**Comment by mitchellh** [comment]
Closing this since its been over a year and this is a working feature.
