### ISSUE TITLE
Propagated `create_before_destroy` removed from dependent resource in state file when resource is updated or recreated.

### ISSUE THREAD

**Issue by JohannesMoersch** [hashicorp/terraform#35959]
### Terraform Version

```shell
Terraform v1.9.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.3
```

### Configuration 1
```terraform
resource "null_resource" "base" {
  triggers = {
    version = 0
  }
}

resource "null_resource" "depends_on_base" {
  triggers = {
    base = null_resource.base.id
    version = 0
  }
}

resource "null_resource" "depends_on_both" {
  depends_on = [ null_resource.depends_on_base ]

  lifecycle {
    create_before_destroy = true
  }
}
```

### Configuration 2 
* `null_resource.depends_on_base.triggers.version` updated to `1`
```terraform
resource "null_resource" "base" {
  triggers = {
    version = 0
  }
}

resource "null_resource" "depends_on_base" {
  triggers = {
    base = null_resource.base.id
    version = 1
  }
}

resource "null_resource" "depends_on_both" {
  depends_on = [ null_resource.depends_on_base ]

  lifecycle {
    create_before_destroy = true
  }
}
```

### Configuration 3
* `null_resource.base.triggers.version` updated to `1`
* `null_resource.depends_on_base.triggers.version` removed
* null_resource.depends_on_both.triggers.version
```terraform
resource "null_resource" "base" {
  triggers = {
    version = 1
  }
}
```

### Debug Output

[Configuration 1 Apply](https://gist.github.com/JohannesMoersch/7d1c7a064290dafdd7dce273300784ef)
[Configuration 2 Apply (Bug occurs here)](https://gist.github.com/JohannesMoersch/9f8f2476f4d29dcdaee23eddaa4d9a11)
[Configuration 3 Apply](https://gist.github.com/JohannesMoersch/4c0a97ff6d88ffba00ff77ecb23f1771)

### Configuration 1
* `null_resource.base` is created with `create_before_destroy` set to true in the state file. 
* `null_resource.depends_on_base` is created with `create_before_destroy` set to true in the state file. 
* `null_resource.depends_on_both` is created with `create_before_destroy` set to true in the state file. 

### Configuration 2
* `null_resource.depends_on_base` is recreated with `create_before_destroy` set to true in the state file.

### Configuration 3
* `null_resource.base` is recreated with `create_before_destroy` not set in the state file. 
* `null_resource.depends_on_base` is destroyed 
* `null_resource.depends_on_both` is destroyed. 

### Configuration 1
* `null_resource.base` is created with `create_before_destroy` set to true in the state file. 
* `null_resource.depends_on_base` is created with `create_before_destroy` set to true in the state file. 
* `null_resource.depends_on_both` is created with `create_before_destroy` set to true in the state file. 

### Configuration 2
* `null_resource.depends_on_base` is recreated with `create_before_destroy` **not set** in the state file.

### Configuration 3
* `Error: Cycle: null_resource.depends_on_base (destroy), null_resource.base (destroy), null_resource.base, null_resource.depends_on_both (destroy)`

### Steps to Reproduce

1. Set configuration to "Configuration 1"
2. `terraform init`
3. `terraform apply`
4. Set configuration to "Configuration 2"
5. `terraform apply`
   * **The bug occurs at this stage.** `null_resource.depends_on_base` in the state file no longer has `create_before_destroy` set.
7. Set configuration to "Configuration 3"
8. `terraform apply`
   * `terraform apply` fails with an error about a cycle, which is the correct behaviour given the state file resulting from step 5.

### Additional Context

The bug that occurs when applying configuration 2 with `create_before_destroy` being incorrectly calculated for `null_resource.depends_on_base` will happen both on recreates and on updates (which I tested using a different set of configurations).

**Comment by jbardin** [comment]
Thanks for the excellent example @JohannesMoersch!

Slightly simplifying the problem here, `depends_on` is not involved (that would be very strange). The `create_before_destroy` status isn't recovered until the next plan, but like your example, if you update then immediately remove a resource, the order is lost.

**Comment by JohannesMoersch** [comment]
The scenario is actually slightly different when you using a direct reference (like using `triggers` instead of `depends_on`), but the cycle error does still occur. I actually just had this realization moments before you responded.

If you use `triggers` with a direct reference to the base resource, then after the recreate of the resource in configuration 2, the state file still has the `create_before_destroy` value set to true. With `depends_on`, it does not, so I think there is still a bug there.

Turns out you can replicate the cycle error pretty easily with just the following:
``` terraform
resource "null_resource" "base" {
  triggers = {
    version = 0
  }
}

resource "null_resource" "depends_on_both" {
  triggers = {
    base = null_resource.base.id
  }

  lifecycle {
    create_before_destroy = true
  }
}
```
followed by:
```terraform
resource "null_resource" "base" {
  triggers = {
    version = 1
  }
}
```

If you recreate a resource that previously inherited `create_before_destroy`, but no longer does in the current configuration due to that resource being removed from the configuration, you get the cycle error.

However, I think the issue of `create_before_destroy` disappearing from the state on updates only when referenced using `depends_on` feels distinct and also like a real issue.

**Comment by jbardin** [comment]
Thanks @JohannesMoersch, I'm going to go through all the combinations here to make sure they are covered anyway. I already confirmed the same behavior with no use of `depends_on` internally within Terraform. `depends_on` should work just like any other reference from the config, so it will be interesting to see if that really is involved somehow.

**Comment by JohannesMoersch** [comment]
I actually just found a scenario that results in the cycle error only when using `depends_on`. The exact same series of configurations using `triggers` to create the dependencies works without any errors.

### Using `triggers` for reference works as expected
### Configuration 1
``` terraform
resource "null_resource" "base" {
  triggers = {
    version = 0
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "null_resource" "depends_on_base" {
  triggers = {
    base = null_resource.base.id
    version = 0
  }
}

resource "null_resource" "depends_on_both" {
  triggers = {
    base = null_resource.depends_on_base.id
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Configuration 2
``` terraform
resource "null_resource" "base" {
  triggers = {
    version = 0
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "null_resource" "depends_on_base" {
  triggers = {
    base = null_resource.base.id
    version = 1
  }
}

resource "null_resource" "depends_on_both" {
  triggers = {
    base = null_resource.depends_on_base.id
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Configuration 3
``` terraform
resource "null_resource" "base" {
  triggers = {
    version = 1
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Using `depends_on` for reference fails with cycle error
### Configuration 1
``` terraform
resource "null_resource" "base" {
  triggers = {
    version = 0
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "null_resource" "depends_on_base" {
  triggers = {
    base = null_resource.base.id
    version = 0
  }
}

resource "null_resource" "depends_on_both" {
  depends_on = [ null_resource.depends_on_base ]

  lifecycle {
    create_before_destroy = true
  }
}
```

### Configuration 2
``` terraform
resource "null_resource" "base" {
  triggers = {
    version = 0
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "null_resource" "depends_on_base" {
  triggers = {
    base = null_resource.base.id
    version = 1
  }
}

resource "null_resource" "depends_on_both" {
  depends_on = [ null_resource.depends_on_base ]

  lifecycle {
    create_before_destroy = true
  }
}
```

### Configuration 3
``` terraform
resource "null_resource" "base" {
  triggers = {
    version = 1
  }

  lifecycle {
    create_before_destroy = true
  }
}
```
