### ISSUE TITLE
Feature Request: Naming standard for AWS "tags"

### ISSUE THREAD

**Issue by xsmaster** [hashicorp/terraform#3596]
I would just like to see if we could get a standard for "tag" or "tags".

Example: 

https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html
"tag" is used.

https://www.terraform.io/docs/providers/aws/r/elb.html

"tags" is used.

So I did not see this and was doing come clean up and found this nice error message:

There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:
- aws_elb.web-e_load_balancer: : invalid or unknown key: tag

I feel dumb now as the error message seems correct but it would be nice to have the same "tag" keyword used for all aws tags.

**Comment by apparentlymart** [comment]
The difference for autoscaling groups is that the tags are not just a simple mapping but rather each tag has an attribute `propagate_at_launch`. Supporting that extra attribute requires a different structure than is used on other resources, where a simple map from name to value is the standard.

It is in fact the autoscaling group resource that is the odd one here. Perhaps this could be resolved by a more obvious warning in the autoscaling group documentation that the tag structire is different than for other resources?

**Comment by xsmaster** [comment]
That would be killer to make the doc's more clear. I was not sure if there was a way to get the ELB's to use what the ASG's are using. do some behind the seen magic. Or at minimum provide a better error message like "Hey dummy you need to use "tags" and not "tag..." :p
