### ISSUE TITLE
docs: install: fedora: incorrect instructions for `dnf`

### ISSUE THREAD

**Issue by johnstcn** [hashicorp/terraform#35979]
### Terraform Version

```shell
Terraform v1.9.8
on linux_amd64
```

### Affected Pages

https://developer.hashicorp.com/terraform/install#linux

subsection "Fedora"

### What is the docs issue?

Current Terraform install command referenced on https://developer.hashicorp.com/terraform/install#linux is:

```shell
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
sudo dnf -y install terraform
```

Line 2 returns the following output:

```shell
sudo dnf config-manager --add-repo
Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.
```

What does work for me:

```shell
sudo dnf config-manager addrepo --from-repofile=https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
```

Looks like this was changed between dnf v3 and v5.

The Fedora project docs [1] are inconsistent on this subject and appear to reference both `dnf config-manager --add-repo` and `dnf config-manager addrepo --repo-url`

[1] https://docs.fedoraproject.org/en-US/quick-docs/adding-or-removing-software-repositories-in-fedora/#_adding_repositories

Additional information: 

```
Linux 6.11.6-300.fc41.x86_64

$ cat /etc/fedora-release
Fedora release 41 (Forty One)

$ dnf --version
dnf5 version 5.2.6.2
dnf5 plugin API version 2.0
libdnf5 version 5.2.6.2
libdnf5 plugin API version 2.0

Loaded dnf5 plugins:
  name: builddep
  version: 1.0.0
  API version: 2.0

  name: changelog
  version: 1.0.0
  API version: 2.0

  name: config-manager
  version: 0.1.0
  API version: 2.0

  name: copr
  version: 0.1.0
  API version: 2.0

  name: needs_restarting
  version: 1.0.0
  API version: 2.0

  name: repoclosure
  version: 1.0.0
  API version: 2.0
```

### Proposal

```shell
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager addrepo --from-repofile=https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
sudo dnf -y install terraform
```

### References

https://github.com/rpm-software-management/dnf5/issues/1537

**Comment by bschaatsbergen** [comment]
Hi @johnstcn,

Thank you for raising this issue and suggesting a potential solution.

I can indeed replicate the behavior on Fedora Linux 41. Since it works on Fedora Linux 40, it seems that backward compatibility was intentionally broken (see https://github.com/rpm-software-management/dnf5/issues/405).

Regarding that change, the documentation on [adding a repository](https://docs.fedoraproject.org/en-US/quick-docs/adding-or-removing-software-repositories-in-fedora/#_adding_repositories) appears only partially updated. I’ll submit a pull request to address this.

Added, we'll make sure to get this fixed on our side too. Thanks!

**Comment by bschaatsbergen** [comment]
Cross-reference for a documentation update in the Fedora docs: https://pagure.io/fedora-docs/quick-docs/pull-request/783#

**Comment by johnstcn** [comment]
Thanks for the upstream PRs @bschaatsbergen !

**Comment by bschaatsbergen** [comment]
> Thanks for the upstream PRs @bschaatsbergen ! 

Thanks for being awesome and letting us know about this!

**Comment by drewmullen** [comment]
Thanks for the documented fix @bschaatsbergen 

@radeksimko Hi - any chance the docs will be updated sometime soon? this has bit me twice now and i keep having to come back and find this PR to resolve -- cant we just update the website docs? 
![image](https://github.com/user-attachments/assets/893e24c0-0a58-4b4a-b672-e8fb485919d1)

**Comment by Kerwood** [comment]
This should also be changed in these docs here: https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
