### ISSUE TITLE
Config generation wraps numbers and booleans in jsonencode

### ISSUE THREAD

**Issue by bplotnick** [hashicorp/terraform#35983]
### Terraform Version

```shell
HEAD
```

### Terraform Configuration Files

```terraform
import {
  to = test_resource.foo
  id = "someresourceid"
}
```

### Debug Output

N/A

### Expected Behavior

When running with `-generate-config-out=generate.tf`, if the returned resource has is a string type, but contains a number or a bool, the output attribute should be a string. e.g.

```terraform
resource "test_resource" "foo" {
  some_string_attribute = "1234"
}
```

### Actual Behavior

```terraform
resource "test_resource" "foo" {
  some_string_attribute = jsonencode(1234)
}
```

### Steps to Reproduce

Create an `import` block for a resource with a string attribute, but with a value that is a primitive, deserializable json type (number or bool) and run ` terraform plan -generate-config-out=generated.tf` 

### Additional Context

I have a fix for this. I am just opening the issue for posterity

**Comment by crw** [comment]
Thanks for filing this in conjunction with the pull request!
