### ISSUE TITLE
error when applying plan when undeclared variables exist

### ISSUE THREAD

**Issue by jbardin** [hashicorp/terraform#36017]
#35903 doesn't take into account the presence of undeclared variables, so when any automatically applied variable files exist in the configuration directory, apply can't proceed. 

Reproduction: apply any configuration which has a `terraform.tfvars` or `*.auto.tfvars*` file with a variable assignment not declared in the configuration.

**Comment by bschaatsbergen** [comment]
In addition to automatically applied variable files, a ‘Value for undeclared variable’ error diagnostic is also thrown when a named file is used. This occurs now when any set variable evaluation does not match a variable declaration in the root module configuration: https://github.com/hashicorp/terraform/blob/main/internal/backend/local/backend_apply.go#L272-L285.
