### ISSUE TITLE
Where is the repository for Terraform Tutorials?

### ISSUE THREAD

**Issue by hsnabszhdn** [hashicorp/terraform#36018]
### Terraform Version

N/A

### Affected Pages

General question about all "Tutorials" pages: https://developer.hashicorp.com/terraform/tutorials

### What is the docs issue?

Where is the repository for "Tutorials" docs? I couldn't find anything in [hashicorp/terraform](https://github.com/hashicorp/terraform) and there is no "Edit this page on GitHub" button on these pages either.

### Proposal

There are some trivial issues—like grammatical errors, punctuation, duplicate verbs, etc.—in a few tutorials which are not worth opening an issue for, but wanted to raise PRs myself.

I was wondering if the source code is publicly available.

### References

N/A

**Comment by bschaatsbergen** [comment]
Hi @hsnabszhdn,

Thank you for bringing this to our attention and for your interest in contributing to the Terraform tutorials. We appreciate your attention to detail and your efforts in identifying the grammatical errors and other minor issues.

At this time, the tutorial documentation is not currently editable by external contributors. However, if you come across any specific issues or areas that could be improved, please don’t hesitate to reach out. We’ll make sure to pass your feedback on to our education team for review.

Thank you once again for your understanding and for your enthusiasm to contribute.

**Comment by hsnabszhdn** [comment]
I see...

All good then. Most of the things that I found weren't issue-worthy and I'm sure if I open issues, they will never be addressed as they'll be considered super low priority 😅

But, if I do find anything that could have wrong information or cause confusion, I'll make sure to open an issue.

Thanks a lot for monitoring the issues and the quick turnaround; really appreciate it 🙏
