### ISSUE TITLE
For Google Cloud Pub/Sub subscription, Retry policy defaulted to "retry with exponential backoff" with latest module

### ISSUE THREAD

**Issue by MadhuSurya-Git** [hashicorp/terraform#36078]
### Terraform Version

```shell
Terraform v1.5.7
```

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {}
}

provider "google" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
  region       = "us-east1"
}

provider "google-beta" {
  access_token = data.google_service_account_access_token.sa.access_token
  project      = var.project_id
  region       = "us-east1"
}

provider "google" {
  credentials = file(var.gcp_credential_path)
  alias       = "impersonated"
}

data "google_service_account_access_token" "sa" {
  provider               = google.impersonated
  target_service_account = "sa-${substr(var.project_id, 0, min(length(var.project_id), 27))}@${var.project_id}.iam.gserviceaccount.com"
  lifetime               = "3600s"
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
  ]
}

module "gcp_pubsub" {
  source                      = "acnciotfregistry.accenture.com/accenture-cio/pubsub/google"
  version                     = "2.1.0"
  project_id                  = var.project_id
  topic_name                  = "NewTopic-us-east1"
  subscription_name           = "NewSubscription-us-east1"
  intended_event_type         = "Application"
  resources_to_create         = "BOTH"
  delivery_type               = "Push"
  endpoint_url                = "https://www.testendpointurl.com"
  push_auth_service_account   = "sa-103879-big-data@${var.project_id}.iam.gserviceaccount.com"
  labels = {
    examplenum = "gcp_pubsub_test"
    creates    = "subscription"
  }
}
```

### Debug Output

NA

### Expected Behavior

NA

### Actual Behavior

Problem:

The latest version of the Terraform Google Cloud provider has introduced a change in the default retry policy for Pub/Sub subscriptions. Previously, the default was "retry immediately," but now it defaults to "retry with exponential backoff" with a default backoff configuration (retry_policy_time = {minimum_backoff = "10s" maximum_backoff = "600s"}). This unexpected behavior is causing issues for our application teams, who require the "retry immediately" policy.

When we hardcode version 6.0 of the Google Cloud provider in our latest terraform module, it automatically applied the "retry immediately" policy (no backoff was provided), it has worked as expected.
Currently we have provided this workaround for most of our application teams. 
But we don't recommend to hardcode Google Cloud provider version in our modules as per our process standards.

Impact:

The default exponential backoff policy is causing delays in message delivery, impacting the performance and responsiveness of our applications.

Requirement:

We need to ensure that the default retry policy for Pub/Sub subscriptions reverts to "retry immediately" when using the latest version of the Terraform Google Cloud provider.
Our Application teams requirement is "retry immediately"

Please resolve this bug immediately

### Steps to Reproduce

NA

**Comment by bschaatsbergen** [comment]
Hey @MadhuSurya-Git,

This appears to be an issue or question with the Google provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-google/issues.

According to the [Google Pub/Sub subscription documentation](https://cloud.google.com/pubsub/docs/handling-failures#:~:text=By%20default%2C%20subscriptions%20use%20immediate%20redelivery), the default retry policy is immediate retry. However, the API specification seems to conflict a little with that described behavior, as it reflects exponential backoff: [RetryPolicy](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#RetryPolicy).

Based on the retry policy implementation in the resource: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/pubsub/Subscription.yaml#L460-L483, it makes me believe that if you set an empty `retry_policy` block in your resource, the `minimum_backoff` and `maximum_backoff` arguments of that block should default to `"0s"`, which enforces immediate retry behavior (?)

```hcl
resource "google_pubsub_subscription" "example" {
  retry_policy {
  }
}
```

That said, I’m not a subject matter expert on Google Cloud, so I’d recommend reaching out to my wonderful colleagues working on the Google provider if this warrants a follow-up.

Thanks!
