### ISSUE TITLE
Stateless Inspection with a Custom Action does not support IPv6

### ISSUE THREAD

**Issue by dniald** [hashicorp/terraform#36077]
### Terraform Version

```shell
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.77.0
```

### Use Cases

I attempt to add inbound rule for networkfirewall_rule_group using IPv6, bit the error below. Seem like in the documentation also doesnt mentioned about IPv6. Hope this can be support soon! thanks!

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_rule_group#stateless-inspection-with-a-custom-action

```
resource "aws_networkfirewall_rule_group" "inbound_ipv6" {
  capacity    = 100
  description = "Permits HTTP traffic from IPv6 ranges"
  name        = "inbound-ipv6"
  type        = "STATELESS"

  rule_group {
    rules_source {
      stateless_rules_and_custom_actions {
        dynamic "stateless_rule" {
          for_each = var.ipv6_ranges
          content {
            priority = 200 + index(var.ipv6_ranges, stateless_rule.value)
            rule_definition {
              actions = ["aws:pass"]
              match_attributes {
                source {
                  address_definition = stateless_rule.value
                }
                destination {
                  address_definition = "::/0"  #  IPv6 "any" destination
                }
                protocols = [6]  # TCP
                source_port {
                  from_port = 0
                  to_port   = 65535
                }
                destination_port {
                  from_port = 80
                  to_port   = 80
                }
              }
            }
          }
        }
      }
    }
  }

  tags =
    {
      Name = "Allow HTTP IPv6"
    }
}
```

│ Error: "2c0f:f248::/32" is not a valid IPv4 CIDR block
│
│ with module.vpc.aws_networkfirewall_rule_group.inbound_ipv6,
│ on modules/firewall/main.tf line 130, in resource "aws_networkfirewall_rule_group" "inbound_ipv6":
│ 130: stateless_rules_and_custom_actions {

### Attempted Solutions

Support IPv6 cidr in networkfirewall_rule_group

**Comment by bschaatsbergen** [comment]
Hey @dniald,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues.

Looking at the [API specification](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_Address.html) for AWS Network Firewall, it indeed seems the AWS provider should be able to support IPv6 CIDR blocks with a minor tweak in the validation: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/networkfirewall/rule_group.go#L255 

Thanks!
