### ISSUE TITLE
Vsphere_virtual_machine PXE boot

### ISSUE THREAD

**Issue by dung2k1deptrai1** [hashicorp/terraform#36084]
### Terraform Version

```shell
1.9.8
```

### Use Cases

I’m trying create VM with possibility to boot by PXE, but I need to know when this machine is really booted by PXE and get IP by DHCP. After this I must create resource which depends from this VM.
It is possible do something like this?

### Attempted Solutions

I tried on vsphere environment but only run to boot option but can not boot into network

**Comment by bschaatsbergen** [comment]
Hi @dung2k1deptrai1, thanks for this question. We use GitHub Issues to track bugs and feature requests in the product. If you have a usage question, please use our [Discuss forum](https://discuss.hashicorp.com/c/terraform-providers/31) to get answers from the broader community. GitHub Issues is only seen by a small group of core contributors. Thanks again!
