### ISSUE TITLE
DBInstanceIdentifier Doesn't Allow Valid Identifiers

### ISSUE THREAD

**Issue by jamescarr** [hashicorp/terraform#3610]
SQL Server RDS instances have somewhat ridiculously long parameter group names. However it seems that attempting to create an RDS instance with terraform results in an error because it's expecting the name to 15 characters. 

From `awscli` we can get the valid names:

```
$ aws rds describe-db-parameter-groups  | grep sqlserver | grep DBParameterGroupName                   
            "DBParameterGroupName": "default.sqlserver-ex-10.5",
            "DBParameterGroupName": "default.sqlserver-ex-11.0",
```

However attempting to use either of these results in 

```
Error creating DB Instance: InvalidParameterValue: The parameter DBInstanceIdentifier is not a valid identifier because it is longer than 15 characters.
	status code: 400, request id: 23d4b50c-7938-11e5-b178-ddec8ffe3c1c

```

**Comment by jamescarr** [comment]
Sorry I'm stupid. I misread the error.

**Comment by Nareshkg** [comment]
I got below error when I am trying to delete the instance
InvalidParameterValue: The parameter FinalDBSnapshotIdentifier is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
	status code: 400, request id: a32125c4-6e6b-4f1c-aeb0-ba3171094144
