### ISSUE TITLE
1.10.0 breaks assume role for AWS provider

### ISSUE THREAD

**Issue by cmmarslender** [hashicorp/terraform#36124]
### Terraform Version

```shell
Terraform v1.10.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.45.0
+ provider registry.terraform.io/hashicorp/vault v3.11.0
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = var.region
  assume_role {
    role_arn = "arn:aws:iam::xxxxxxxxxxxx:role/OrganizationAccountAccessRole"
  }
}
```

### Debug Output

https://gist.github.com/cmmarslender/98a7f7dac6b6b80a4192ee1f5f03e72b

### Expected Behavior

Terraform init should not complain about the role_arn being unexpected. This worked fine on previous versions of terraform and is still the way the aws provider documents this should be done.

### Actual Behavior

```╷
│ Error: Unsupported argument
│ 
│   on main.tf line 33, in terraform:
│   33:     role_arn = "arn:aws:iam::xxxxxxxxxxxx:role/OrganizationAccountAccessRole"
│ 
│ An argument named "role_arn" is not expected here.
╵
```

### Steps to Reproduce

1. `terraform init` with the provided aws config using assume_role

**Comment by jbardin** [comment]
Hi @cmmarslender,

Thanks for filing the issue. I don't see any reason that Terraform would interpret the provider configuration differently in v1.10, and I can validate the given provider config with all recent versions. Can you show the exact, complete config file and error that you receive that file? Perhaps there's some preceding syntax which is causing an error.

**Comment by cmmarslender** [comment]
Looking further at the config, I realized we have another instance of `role_arn`, and I was possibly looking at the wrong instance, assuming we only had to assume a role once.

The problem is probably with the `role_arn` in the s3 backend configuration:

```terraform {
  backend "s3" {
    bucket   = "bucket-name"
    key      = "prefix/terraform.state"
    region   = "us-west-2"
    role_arn = "arn:aws:iam::xxxxxxxxxxxx:role/OrganizationAccountAccessRole"
  }
}```

Looking at docs for that, seems like at some point that was supposed to be moved into an `assume_role` block. I have a PR open against our infra repo and will close this issue once I can confirm that is the problem.

**Comment by cmmarslender** [comment]
Ok yeah - wrapping the role_arn in the s3 backend in the `assume_role = { ... }` block solved the problem.
I think the docs still show the `role_arn` as supported but deprecated, so may need to remove it completely from docs.

**Comment by sean6bucks** [comment]
Our company ran into this same problem, stalling pipelines in tons of services due to a shared module. I think the larger issue here is that "planned to be deprecated" values were removed in a minor update, thus a Breaking Change. Since 1.x I would expect this to be more stable and for minor releases not to break our code if we are using a `< 2.0` version range.

https://developer.hashicorp.com/terraform/language/v1-compatibility-promises

To me this seems like a Breaking Change that does not follow semantic version best practices https://github.com/hashicorp/terraform/pull/35721/files

**Comment by Indigenuity** [comment]
Aside from the breaking change, did the deprecation itself even follow the compatibility promises? Running plan and apply with 1.9.x terraform yielded zero deprecation warnings on our hundreds of terraform roots with s3 backends declared in the `terraform` block. It's interesting that the `terraform` block was ignored when `data "terraform_remote_state"` with s3 backend caused plenty of deprecation warnings in the same terraform versions.
