### ISSUE TITLE
Can't thumbs up locked issue despite direction to do so

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform#36126]
### Terraform Version

```shell
N/A
```

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

I should have been able to upvote https://github.com/hashicorp/terraform/issues/27547 as requested by @crw in https://github.com/hashicorp/terraform/issues/27547#issuecomment-1081237940.

### Actual Behavior

Because the issue is locked, it is not possible to upvote it. Per [GitHub docs](https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations):

> Reactions and votes in a locked conversation are disabled for all users. 

This means that all locked issues may be undervalued in terms of their popularity.

### Steps to Reproduce

1. Navigate to https://github.com/hashicorp/terraform/issues/27547
2. Attempt to upvote it.

**Comment by crw** [comment]
Thanks for this report, I was honestly unaware of that consequence of locking issues.
