### ISSUE TITLE
Proposal: store sensitive values in state as a hash rather than the value itself

### ISSUE THREAD

**Issue by jamesla** [hashicorp/terraform#36133]
### Terraform Version

```shell
n/a
```

### Use Cases

simplifying secret management by allowing us to store in state

### Attempted Solutions

n/a

### Proposal

Terraform obviously stores all values (including sensitive values) in state which is not secure.

My suggestion is to store a hash of sensitive values in state rather than the value itself, that way sensitive values could be stored in state and terraform would still know if it needs to replace resources without violating security principals or requiring a seperate solution to manage secrets independently of the stack.

Thoughts?

**Comment by jbardin** [comment]
Hi @jamesla,

The provider plugin protocol requires the values saved by the provider are always returned to the provider unchanged, they cannot be changed in the state. The new [Ephemeral Values](https://www.hashicorp.com/blog/terraform-1-10-improves-handling-secrets-in-state-with-ephemeral-values) project is working towards a new system for avoiding stored secrets in the state.
