### ISSUE TITLE
Terraform 1.10 - Error: Can't change variable when applying a saved plan

### ISSUE THREAD

**Issue by pauldtill** [hashicorp/terraform#36130]
### Terraform Version

```shell
Terraform v1.10.0
```

### Terraform Configuration Files

```terraform
variable "this_is_a_list_variable" {
  type    = list(string)
  default = []
}
```

### Debug Output

https://gist.github.com/pauldtill/693a77980b7409e91d8c506eecb23085

### Expected Behavior

Terraform apply is successful.

### Actual Behavior

Terraform plan works OK - terraform apply fails with -
```
│ Error: Can't change variable when applying a saved plan
```

### Steps to Reproduce

```
export TF_VAR_this_is_a_list_variable='["stuff"]'
terraform plan -input=false -out=plan.tfplan
terraform apply plan.tfplan
```

### Additional Context

This seems to be an issue with the way a TF_VAR list environment variable is stored in the plan compared to how it is seen at runtime for apply - confirmed this does not occur at v1.9.8 with the same basic config / environment variable.

**Comment by radeksimko** [comment]
Hi @pauldtill 
Thank you for the report. I believe this is the same issue as reported in https://github.com/hashicorp/terraform/issues/36106

It will be fixed as part of https://github.com/hashicorp/terraform/pull/36121 - I ran the attached config/steps through and can confirm the PR fixes it.
