### ISSUE TITLE
terraform 1.10.1 takes terraform.tfvars when applying planned file

### ISSUE THREAD

**Issue by DorisEckel8412** [hashicorp/terraform#36177]
### Terraform Version

```shell
1.10.1
```

### Terraform Configuration Files

```terraform
variable this_is_variable {
   type = string
}

// in terraform-<env>.tfvars 
this_is_variable = "foo"

// in terraform.tfvars 
this_is_variable = "bar"
```

### Debug Output

https://gist.github.com/DorisEckel8412/3bc826f64ad9702739ef7d252aa28947

### Expected Behavior

Use only the values already in the planned file and not tries to override them.

### Actual Behavior

It tries to override with entries from terraform.tfvars 

### Steps to Reproduce

1. terraform plan -var-file=terraform-<env>.tfvars  -out plan.output
2. terraform apply  plan.output

### Additional Context

From the documentation and until 1.9.x it was taking the planned file and ignoring the default terraform.tfvars file. Other stuff about variables was mentioned as fixed in 1.10.1 but this still appears.

**Comment by jkritzen** [comment]
The same on our side. This is breaking our whole module test workflows.

**Comment by ashithajo** [comment]
I am still seeing this error with v1.10.3

**Comment by crw** [comment]
@ashithajo please open a new bug issue following the template, as usually there is a new or different cause for the same error message after a fix such as this. Thanks!
