### ISSUE TITLE
ssm_association parameters - list of strings broken

### ISSUE THREAD

**Issue by Bonny1997** [hashicorp/terraform#36170]
### Terraform Version

```shell
1.10.1
```

### Terraform Configuration Files

```
resource "aws_ssm_association" "disable_alarms" {
  count                       = length(var.cloudwatch_alarms) > 0 ? 1 : 0
  association_name            = "${module.label.name}-disable-rds-alarms-ssm-association"
  name                        = local.cw_alarm_ssm_document_name
  schedule_expression         = var.stop_schedule
  apply_only_at_cron_interval = true

  parameters = {
    AutomationAssumeRole = aws_iam_role.ssm_cloudwatch_alarm[0].arn
    CloudWatchAlarms     = join(", ", var.cloudwatch_alarms)
    Action               = "Disable"
  }

  depends_on = [
    aws_iam_role.ssm_cloudwatch_alarm
  ]
}
```

### Debug Output

module.jd_rds_scheduler[0].aws_ssm_association.disable_alarms[0] - *terraform.NodeApplyableResourceInstance
    module.jd_rds_scheduler (expand) - *terraform.nodeExpandModule
    module.jd_rds_scheduler.aws_iam_role.ssm_cloudwatch_alarm (expand) - *terraform.nodeExpandApplyableResource
    module.jd_rds_scheduler.aws_ssm_association.disable_alarms (expand) - *terraform.nodeExpandApplyableResource
    module.jd_rds_scheduler.local.cw_alarm_ssm_document_name (expand) - *terraform.nodeExpandLocal
    module.jd_rds_scheduler.module.label.output.name (expand) - *terraform.nodeExpandOutput
    module.jd_rds_scheduler.var.cloudwatch_alarms (expand) - *terraform.nodeExpandModuleVariable
    module.jd_rds_scheduler.var.stop_schedule (expand) - *terraform.nodeExpandModuleVariable
    module.jd_rds_scheduler[0].aws_iam_role.ssm_cloudwatch_alarm[0] - *terraform.NodeApplyableResourceInstance
    provider["registry.terraform.io/hashicorp/aws"] - *terraform.NodeApplyableProvider

### Expected Behavior

The terraform is applying the list for the parameter "CloudWatchAlarms", which in the AWS console when you enter the edit option for the ssm association, looks like alarm_1, alarm_2

This is correct and expected and it is the same way you would save the list if doing it manually via the console

![Screenshot 2024-12-06 at 14 53 29](https://github.com/user-attachments/assets/98156401-87eb-40a4-9b6b-7a71d60db3c6)

### Actual Behavior

After applying via terraform, when you are in the AWS console and navigate to the ssm association, under the parameters tab, the "CloudWatchAlarms" parameter looks like alarm_1, alarm_2. Executing this association does not work. (see screenshot below)

![Screenshot 2024-12-06 at 15 08 35](https://github.com/user-attachments/assets/2471674d-64c2-4fc0-a56f-2643ac51f308)

Although, when creating the association manually in the AWS console, when the alarms are saved as expected saved like alarm_1, alarm_2. When saved and navigate to the parameters tab, the "CloudWatchAlarms" parameter looks like alarm_1alarm_2. This association does work. (See screenshots below)

![Screenshot 2024-12-06 at 14 55 25](https://github.com/user-attachments/assets/7422c7b4-c56b-4917-ad9c-d292cec4dccb)

Essentially Terraform is saving the final list as alarm_1, alarm_2 when AWS saves it like alarm_1alarm_2.

### Steps to Reproduce

1. Terraform init
2. Terraform plan
3. Terraform apply
4. In the console, click the edit tab of the ssm association (list of alarms is supplied)
5. In the console, click the parameters tab of the ssm association (AWS and terraform save the final list differently)

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!

**Comment by Bonny1997** [comment]
Much appreciated for this, thanks for letting me know!

Thanks
