### ISSUE TITLE
Feature: file backend for remote state

### ISSUE THREAD

**Issue by pgray** [hashicorp/terraform#3618]
It would be nice to have the same idea of remote state implemented with `file` as a backend.

Bringing `_local` in as a first-class form of remote state would probably suffice.

https://github.com/hashicorp/terraform/blob/master/state/remote/remote.go#L47
```
resource "terraform_remote_state" "vpc" {
    backend = "file"
    
    config {
        path = "./vpc/terraform.tfstate"
    }
}
```

**Comment by thegedge** [comment]
Agreed, this should probably be a first-class citizen. My argument for this would be that https://terraform.io/intro/getting-started/build.html suggests storing state in git, which would imply one needs a way of reading said state. Arguably, you could likely use the `http` backend to read from your git host.

**Comment by anners** [comment]
+1

**Comment by packplusplus** [comment]
+1

**Comment by MikeSchuette** [comment]
+1

**Comment by grosendorf** [comment]
:+1:

**Comment by ckelner** [comment]
:+1:

**Comment by apparentlymart** [comment]
This would also imply supporting a "file" remote state storage:

```
terraform remote config -backend=file -backend-config="path=/path/to/some/state"
```

At first glance that seems rather weird, but in the presence of network filesystems it could actually make some sense, as long as the network filesystem is mounted in a consistent location on all systems where Terraform might run. This seems pretty plausible in an environment where Terraform runs are being orchestrated by something like Jenkins, where the Terraform configs are kept on some NFS filesystem shared across the whole Jenkins cluster.

**Comment by bsingr** [comment]
+1

**Comment by GrzegorzWild** [comment]
+1

**Comment by stumyp** [comment]
+1 
any idea why `_local` as-is would be bad decision as remote state backend ?

**Comment by GrayCoder** [comment]
@stumyp we actually use this all the time at my company. Hasn't caused any problems (yet :smile: ). I think renaming it would actually just make it seem more legit.

**Comment by joshuaspence** [comment]
Would the upstream accept a pull-request to simply rename `_local` to `local` and add documentation? Is there anything blocking this?

**Comment by cornfeedhobo** [comment]
@joshuaspence can you open a Pull Request for your branch?

**Comment by bfgoodrich** [comment]
For those that have _local working as a remote state backend, was there any kind of issue referencing another "_local" remote_state as a 'terraform_remote_state' resource?
