### ISSUE TITLE
Terraform 1.10.1 - Error: Can't change variable when applying a saved plan

### ISSUE THREAD

**Issue by pauldtill** [hashicorp/terraform#36181]
### Terraform Version

```shell
Terraform v1.10.1
on linux_amd64
```

### Terraform Configuration Files

```terraform
See additional context
```

### Debug Output

Plan - https://gist.github.com/pauldtill/274ebddf7098a8e0d081eea465ed53ec
Apply - https://gist.github.com/pauldtill/f3c729bdbc565a21325b9b2b8787f542

### Expected Behavior

Terraform apply is successful.

### Actual Behavior

Terraform plan works OK - terraform apply fails with -

```
│ Error: Can't change variable when applying a saved plan
│ 
│ The variable scada_license_template cannot be set using the -var and
│ -var-file options when applying a saved plan file, because a saved plan
│ includes the variable values that were set when it was created. The saved
│ plan specifies
```

### Steps to Reproduce

See additional context

### Additional Context

The issue is happening on an internal TF pipeline we have which is complex and does not exist in github. I've tried to replicate the issue using the same variable, value and usage of the variable, but failed. I'm hoping the debug output from our pipeline will be sufficient here, as it seems as though a test case will be difficult to provide. We raised similar bug (36130) on this same error, but this was closed as fixed in 1.10.1 - and indeed for that specific list variable issue, it is resolved, but even on 1.10.1 we are still hitting the issue with this module. The issue does **not** happen at 1.9.8.

### References

- #36130

**Comment by jbardin** [comment]
Hi @pauldtill,

Thanks for filing the issue. Without a complete example it's hard to determine what might be happening. Are you perhaps encountering #36177?

**Comment by pauldtill** [comment]
@jbardin  - you are spot on, we are passing a custom tfvars file in the plan stage but not apply - I've added this to the apply stage and all has worked Ok now. Guess we close this related to #36177
