### ISSUE TITLE
Terraform plans should show set members that will be retained post-apply

### ISSUE THREAD

**Issue by ktham** [hashicorp/terraform#36221]
### Terraform Version

```shell
1.7.5
```

### Use Cases

Terraform defers rendering set comparisons until apply-time when there are new unknown elements adding to a resource attributes of `TypeSet`

For example, we might have configuration that initially looks like this:

```
resource "aws_security_group" "example" {
  # ...
}

resource "aws_db_instance" "example" {
  vpc_security_group_ids = [
    aws_security_group.example.id,
  ]
  # ...
}
```

And then we update the configuration to be this:
```
resource "aws_security_group" "example" {
  # ...
}

resource "aws_security_group" "additional" {
  # ...
}

resource "aws_db_instance" "example" {
  vpc_security_group_ids = [
    aws_security_group.example.id,
    aws_security_group.additional.id,
  ]
  # ...
}
```

Because `aws_security_group.additional.id` is not known until apply-time, and because `aws_db_instance.example.vpc_security_group_ids` is an attribute of `TypeSet`, we'd see Terraform Plan output that looks something like this:

```
      ~ vpc_security_group_ids                = [
          - "sg-46c08c0f",
        ] -> (known after apply)
```

This isn't a real or complete Terraform configuration, but is meant to highlight in brevity the UX issue we're facing.

Removal of security groups on an AWS resource like `aws_db_instance` could potentially be dangerous and it would give the Terraform practitioner more peace of mind if we can be assured from the Terraform Plan that the change above is either additive, or a no-op.

Here is desired Terraform Plan output that we'd like to see:
```
      ~ vpc_security_group_ids                = [
          "sg-46c08c0f",
          # (additional elements possible, but not known until after apply)
        ]
```

### Attempted Solutions

The workaround is a targeted apply of the resources that are unknown, in order to avoid the scenario of adding unknown elements to an existing set attribute, but that is not a feasible or scalable solution.

### Proposal

Terraform plans should show set members that are known to persist during the situation where new set members could be introduced (but is not yet known if they will be until apply-time).

This is important so that the practitioner can have assurance that certain set members are _not_ expected to be removed. This is particularly important when modifying configuration that impacts network connectivity.

However, Terraform today doesn't show anything at all, other than the TypeSet attribute will be assigned a new Set and the new Set will be "known after apply."

**Comment by jbardin** [comment]
Hi @ktham,

Terraform current does exactly what you are asking:
```
resource "terraform_data" "a" {
}

resource "terraform_data" "b" {
  input = toset([
    "known value",
    terraform_data.a.id,
  ])
}
```

Results in the plan:
``` 
  # terraform_data.b will be created
  + resource "terraform_data" "b" {
      + id     = (known after apply)
      + input  = [
          + "known value",
          + (known after apply),
        ]
      + output = (known after apply)
    }
```

Since you are providing the configuration for the `vpc_security_group_ids` attribute, it seems the provider is incorrectly changing the configured value during the plan, but as a legacy provider can can get away with the behavior for compatibility reasons (there should be a corresponding warning in the logs about `Provider "aws" produced an invalid plan for aws_db_instance...`). 

It would be up to the provider to fix the resource implementation, which involves upgrading the SDK to use the newer Terraform provider framework.

Thanks!
