### ISSUE TITLE
Question: Reassign existing EIP to new Instance in AWS

### ISSUE THREAD

**Issue by bscott** [hashicorp/terraform#3622]
Is there a way to assigned a pre-existing EIP to a new aws_instance that Terraform creates?

**Comment by stack72** [comment]
@bscott From what I can see, there is no way that you can assign a public_ip address to an AWS instance created by terraform. The way around this could be to create an aws_network_interface and assign the EIP to that network_interface

Then, in your AWS instance, pass the network_interface in to the user_data script and get the instance to attach itself to the correct instance. This is *really* hacky though. A sample of this style of code is here:

```
resource "template_file" "nat_provision" {
  filename = "scripts/nat_provision.sh"

  vars {
      eni_id = "eni-1234567"
  }
}

resource "aws_launch_configuration" "nat_launch_config" {
  ami = "ami-1234"
   instance_type = "m1.small"
  user_data = "${template_file.nat_provision.rendered}"
}
```

The contents of the nat_provision.sh script would look as follows:

```
######################################################
############## ATTACH THE NAT ENI-ID #################
######################################################

cat <<EOF > /etc/network/interfaces.d/eth1.cfg
# The EIP network interface
auto eth1
iface eth1 inet dhcp
EOF
echo $?

/usr/local/bin/aws ec2 attach-network-interface --network-interface-id $ENI_ID --instance-id $INSTANCE_ID --device-index 1 --region $ZONE
retcode=$?

[ "$retcode" -eq 0 ] && { echo "eni attachment successful" ; exit 0 ; } || { echo "eni attachment failed" ; exit 1 ; }

#This is necessary otherwise there are identical routes to the public subnet via two separate interfaces!
sleep 60
ifdown eth0
```

**Comment by stack72** [comment]
Hi @bscott 

Just coming back to this one, we merged a new resource that does this:

https://www.terraform.io/docs/providers/aws/r/eip_association.html

Paul

**Comment by ppreyas** [comment]
Hi guys,
I'm getting the below error when i try to associate an EIP to a new AWS EC2 Instance. Could you guys help me with this:

* aws_eip_association.eip_assoc: Error associating EIP: Gateway.NotAttached: Network vpc-0d4cfd79fb3c54f58 is not attached to any internet gateway
	status code: 400, request id: 1c350eca-cdb6-463d-a42e-d1d8ab42f145



Code Snippet: 

provider "aws" {
  access_key = ""
  secret_key = ""
  region     = ""
}

resource "aws_eip" "bastion" {
  vpc = true
}


output "eip_id" {
  value = "${aws_eip.bastion.id}"
}

resource "aws_eip_association" "eip_assoc" {
  instance_id   = "${aws_instance.bastion.id}"
  allocation_id = "${aws_eip.bastion.id}"
}

resource "aws_instance" "bastion" {
  ami           = "ami-xxxxx"
  instance_type = "t2.micro"
  vpc_security_group_ids = ["${aws_security_group.bastion.id}"]
  key_name               = "terraform-xxxxx-example"
  subnet_id = "${aws_subnet.bastion.id}"
  availability_zone = "eu-west-2a"



  tags {
    Name = "Bastion Server - Proxy"
  }
}

resource "aws_vpc" "main" {
  cidr_block       = "172.2.0.0/16"
  instance_tenancy = "default"
  #azs = "eu-west-2"

  tags {
    Name = "VPC  - Overall"
  }
}

resource "aws_subnet" "bastion" {
  vpc_id     = "${aws_vpc.main.id}"
  cidr_block = "172.2.2.0/24"
  availability_zone = "eu-west-2a"

  tags {
    Name = "Subnet for Bastion"
  }
}




- Preyas
