### ISSUE TITLE
terraform destroy not deleting aws glue development endpoints

### ISSUE THREAD

**Issue by pranoti-ramteke** [hashicorp/terraform#36242]
### Terraform Version

```shell
Terraform v1.7.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.67.0
```

### Terraform Configuration Files

```hcl
resource "aws_glue_dev_endpoint" "test" {
  name                   = "test-dev-endpoint"
  role_arn               = aws_iam_role.test.arn
  security_configuration = aws_glue_security_configuration.test.id 
}
```

### Debug Output

terraform deleted other aws glue resources on the script except for aws glue dev endpoints

### Expected Behavior

Terraform destroy command should have deleted the glue dev-endpoint

### Actual Behavior

Created a simple terraform script which created few other resources like aws-glue-connection, aws-glue-trigger, aws-glue-job etc 
Terraform destroy deleted the remaining resources from the .tf file and didn't delete the devendpoint.

Due to this the dev-endpoint kept running in AWS and incurred costs. 

### Steps to Reproduce

```console
$ terraform init
$ terraform apply
$ terraform destroy
```

### Additional Context

Also, in AWS Glue portal, their is no direct option on the UI to check the glue development endpoints. Since Terraform destroy didn't work hence the resource was deleted manually using AWS CLI delete-glue-endpoint command.

**Comment by jbardin** [comment]
Hello,

This appears to be an issue or question with the AWS provider, not with Terraform itself. You can see existing issues and file a new one in their repository here: https://github.com/hashicorp/terraform-provider-aws/issues. If you have questions about Terraform or the AWS provider, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) where there are more people ready to help. The GitHub issues here are monitored only by a few core maintainers.

Thanks!
