### ISSUE TITLE
root_block_device tags support?

### ISSUE THREAD

**Issue by ernoaapa** [hashicorp/terraform#3629]
Hi,
is it possible to add a tags to AWS instance `root_block_device`? If not, any plans to support?

**Comment by jimmystewpot** [comment]
having an option that will inherit the tags from the instance would also be useful

**Comment by FransUrbo** [comment]
+1

**Comment by jfarschman** [comment]
+1

**Comment by RyanBowlby-Reflektion** [comment]
+1

**Comment by slobodyanyuk** [comment]
+1

**Comment by stack72** [comment]
Hi @ernoaapa 

Apologies for the late response here - this has already been requested in #3531 - I am going to close this as a duplicate of that so we can track all of the information in a central issue

Thanks again

Paul
