### ISSUE TITLE
Supply extra config attributes to /etc/chef/client.rb

### ISSUE THREAD

**Issue by AVVS** [hashicorp/terraform#3630]
It's impossible to pass in extra vars that could be defined in the configuration (ref: https://docs.chef.io/config_rb_client.html). There is a dirty hack that would allow this right now:

```tf
  #
  # Chef provisioner doesn't support extra configuration variables
  # We will do a dirty hack similar to SQL injection here in order to obtain what we want
  # ssl_ca_file = "/usr/share/ca-certificates/cloud-init-ca-certs.crt"
  #
  provisioner "chef" {
    environment = "${var.env}"
    node_name = "${self.name}\"\nssl_ca_file             \"/usr/share/ca-certificates/cloud-init-ca-certs.crt"
    server_url = "${module.common.chef_hostname}"
    version = "${module.common.chef_client_version}"
    secret_key_path = "${module.common.chef_encrypted_data_bag_path}"
    validation_client_name = "${module.common.chef_validation_client_name}"
    validation_key_path = "${module.common.chef_validation_key_path}"
    run_list = [ "${split(",", var.run_list)}" ]
  }
```

But obviously some straightforward solution would be much better

**Comment by partamonov** [comment]
@svanharmelen, @AVVS the question here if we want just set required variables or also place files(if applicable), as it happened for validation key?

Also there are really many options, I do not think that we need to expose all, because in this case it's better to place client.rb as template, I mean rendered template_file.

**Comment by AVVS** [comment]
well, ideally you would want to allow free input for detailed configuration, so it should be somewhat of a combination, from the already supported options and extra ones from the template_file

**Comment by svanharmelen** [comment]
@AVVS I think this (PR #4590) would fix your request right? Personally I think this is a good way to enable adding custom config to the `client.rb` file, but let me know if it also fits/fixes your use case.

**Comment by AVVS** [comment]
looks pretty good to me
