### ISSUE TITLE
lifecycle prevent destroy can't be variablized?

### ISSUE THREAD

**Issue by sherabi** [hashicorp/terraform#3640]
Hi,
I have a simple problem. I have created a module for my WAF ELB and in that module I try to pass a variable that will set the prevent destroy lifecycle value to either true or false. However I get the following error. I tried passing true with an without the quotes.
What am I possible doing wrong or it is even possible to set the boolean as a variable?
Thanks in advance!

```
Error loading Terraform: Error downloading modules: module QAWAFELB: Error loading .terraform/modules/3543e816b9ffba31f9c1cf593d8c72cd/main.tf: Error parsing lifecycle for aws_elb[WAFELB]: 1 error(s) decoding:

* cannot parse 'prevent_destroy' as bool: strconv.ParseBool: parsing "${var.waf_elb_lifecycle_prevent_destroy}": invalid syntax
```

**Comment by thegedge** [comment]
https://github.com/hashicorp/terraform/issues/3116

**Comment by catsby** [comment]
Hey @sherabi – thanks for opening this. Looks like we're tracking it over in https://github.com/hashicorp/terraform/issues/3116 (thanks @thegedge) so I'm going to close this. 

Thanks again!
