### ISSUE TITLE
Need_To_Copy_httpd_conf_file_to_aws_launch_config_Instances

### ISSUE THREAD

**Issue by kumarsarath588** [hashicorp/terraform#3649]
Hi,

I have a scenario wherein i am creating aws launch configuration which has to copy a specific httpd.conf template replacing ${elb} as a variable to all current and future auto scaled instances. i am using aws_elb also to create elb in same config and giving aws_elb.test.dns_name as vars to template resource.

Now i have template rendered. There is no provisioner to aws launch configuration resource. so how to copy the rendered template to all current and future instances.

**Comment by clstokes** [comment]
Hi @kumarsarath588, I believe you can achieve this by passing the rendered template into your launch configuration's [user_data](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#user_data) argument.

Here's an example configuration showing this - https://gist.github.com/clstokes/759b4d05c91efc216bdb#file-main-tf-L24.

Does this solve your problem?

**Comment by kumarsarath588** [comment]
Yes, yesterday after going through all the attributes in auto scaling launch configuration i got the same idea and implemented. Its working. 
Thanks a lot for help. 

https://github.com/kumarsarath588/terraform-templates/tree/master/guacamole

**Comment by clstokes** [comment]
Glad to hear it! You're welcome!
