### ISSUE TITLE
[feature request] Allow depends_on for providers

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#3657]
It would be nice if I could use a provider's resource to use as variables/params for other providers. For example, I'd like to use the `terraform-vault-provider` to provide the credentials for the `openstack` provider. e.g.,

```
provider "vault" {
  address = "https://my-vault-url:8200"
  token = "${file("${var.vault-token-path}")}"
}

resource "vault_secret" "openstack-helper-credentials" {
  path = "/terraform/openstack-helper-credentials"
}

provider "openstack" {
  user_name = "${vault_secret.openstack-helper-credentials.data.user_name}"
  password = "${vault_secret.openstack-helper-credentials.data.password}"
}
```

When I try running this, it still goes to the environment variables `OS_USERNAME` and `OS_PASSWORD` and if those are not set, it prompts for them.

**Comment by lwander** [comment]
This is currently being worked on here in #2976, I believe.

**Comment by mtougeron** [comment]
You are correct. This is a dup of #2976 I didn't catch that when I searched for existing tickets. Thanks!
