### ISSUE TITLE
AWS SNS always planned to be changed

### ISSUE THREAD

**Issue by maxbeatty** [hashicorp/terraform#3660]
I have, what I think is, a straightforward AWS SNS resource definition that includes a `Version`, `Id`, and `Sid`, but it always reports as changed in `terraform plan` (v0.6.4 - latest from brew on OS X).

```
resource "aws_sns_topic" "example" {
  depends_on = ["aws_iam_role.example"]
  name = "example"
  policy = <<EOF
{
  "Version": "2008-10-17",
  "Id": "Policy1445931846145",
  "Statement": [
    {
      "Action": "sns:Publish",
      "Principal": {
        "AWS": "${aws_iam_role.example.arn}"
      },
      "Effect": "Allow",
      "Resource": "arn:aws:sns:${var.region}::example",
      "Sid": "Stmt1445931846145"
    }
  ]
}
EOF
}
```

Is it because of the variables inside the `EOF`? I see the [s3 bucket policy argument](https://terraform.io/docs/providers/aws/r/s3_bucket.html) mentions making "sure you use the verbose/specific version of the policy." How can I make this policy more specific?

Thanks in advance!

**Comment by catsby** [comment]
Hey @maxbeatty – I've found 2 issues here, and have a fix for both. 
The first is an encoding issue with the policy, the second is an IAM issue that you may or may not have hit. 

Posting a fix soon

**Comment by catsby** [comment]
#3700 should fix this

**Comment by maxbeatty** [comment]
@catsby thanks for looking into this and adding a fix. As my project evolved, I ended up moving the permission to the role policy and out of the SNS resource so I can't test this fix for my previous situation. Hope this helps someone else down the line!

**Comment by catsby** [comment]
Thanks for the update @maxbeatty , glad you had a workaround in place. Sorry for the trouble!

**Comment by mattupstate** [comment]
I seem to be experiencing this issue with 0.6.11, my SNS resource looks like this:

```
resource "aws_sns_topic" "scribe" {
  name = "my-topic"
  display_name = "my-topic"
  policy = <<EOF
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "s3.amazonaws.com"
            },
            "Action": [
                "SNS:Publish"
            ],
            "Resource": "arn:aws:sns:${var.region}:${var.account_id}:my-topic",
            "Condition": {
                "ArnLike": {
                    "aws:SourceArn": "${aws_s3_bucket.scribe.arn}"
                }
            }
        }
    ]
}
EOF
}
```

**Comment by boxrick** [comment]
In your case the cause is the following:
