### ISSUE TITLE
Dependency cycle on destroy

### ISSUE THREAD

**Issue by kumarsarath588** [hashicorp/terraform#3664]
Hi,

My template creates a multi-tier application which consists of application server and webserver. i need to copy elb dns name for my application servers to webserver. for which i am rendering a template and adding this as user_data.

But if apply and destroy the env without changing single letter its giving error.

Error :
root@centos-test:/root/terraform-templates/guacamole$terraform destroy
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes
aws_elb.elb-guacamole-app: Refreshing state... (ID: elb-guacamole-app)
aws_elb.elb-guacamole-web: Refreshing state... (ID: elb-guacamole-web)
aws_lb_cookie_stickiness_policy.elb-stickness-guacamole-web: Refreshing state... (ID: elb-guacamole-web:80:elb-stickness-guaca
mole-web)
aws_lb_cookie_stickiness_policy.elb-stickness-guacamole-app: Refreshing state... (ID: elb-guacamole-app:80:elb-stickness-guaca
mole-app)
template_file.guacamole_sh: Refreshing state... (ID: 21b0928298fbf277f25761d2ca725136f503b5060e5421037b6e8ba8a322e081)
aws_launch_configuration.as-conf-guacamole-web: Refreshing state... (ID: as-conf-guacamole-web)
aws_autoscaling_group.asg-guacamole-web: Refreshing state... (ID: asg-guacamole-web)
Error creating plan: 1 error(s) occurred:

* Cycle: aws_autoscaling_group.asg-guacamole-web, template_file.guacamole_sh, aws_launch_configuration.as-conf-guacamole-web, 
aws_launch_configuration.as-conf-guacamole-web (destroy), template_file.guacamole_sh (destroy), aws_elb.elb-guacamole-app (destroy), aws_elb.elb-guacamole-app

if i change any letter or give space in my template file then environment is getting destroyed. and also reapply after changing any line.

my template file :

#!/bin/bash

echo "<VirtualHost *:80>
        ServerName ${elb}
        ProxyPass /guacamole/ http://${elb}:8080/guacamole/
        ProxyPassReverse /guacamole/ http://${elb}:8080/guacamole/
        ProxyRequests Off
        ProxyPreserveHost on
        ProxyBadHeader Ignore
        <Proxy http://${elb}:8080/*>
        Order deny,allow
        Allow from all
        </Proxy>
</VirtualHost>" >> /etc/httpd/conf.d/guacamole

service httpd restart

Template file : 
https://github.com/kumarsarath588/terraform-templates/tree/master/guacamole

**Comment by rodlogic** [comment]
I am hitting something similar. Expanded the cycle looks like:
```
* Cycle: 

module.VPC.aws_subnet.DMZ_AZ2, 
  module.VPC.aws_security_group.BASTION (destroy), 
    module.VPC.aws_security_group.BASTION, 
      module.VPC.aws_iam_role.NAT (destroy), 
        module.VPC.aws_iam_role.NAT, 
          module.VPC.aws_launch_configuration.NAT (destroy), 
            module.VPC.aws_iam_instance_profile.NAT (destroy), 
              module.VPC.aws_iam_instance_profile.NAT, 
                module.VPC.aws_launch_configuration.NAT, 
                  module.VPC.aws_subnet.DMZ_AZ1 (destroy), 
                    module.VPC.aws_subnet.DMZ_AZ1,
                      module.VPC.aws_network_interface.NAT_AZ1, 
                        module.VPC.aws_autoscaling_group.NAT_AZ1, 
                          module.VPC.aws_autoscaling_group.NAT_AZ1 (destroy), 
                            module.VPC.aws_network_interface.NAT_AZ1 (destroy), 
                              module.VPC.aws_network_interface.NAT_AZ2 (destroy), 
                                module.VPC.aws_security_group.NAT (destroy), 
                                  module.VPC.aws_security_group.NAT, 
                                    module.VPC.aws_network_interface.NAT_AZ2, 
                                      module.VPC.aws_autoscaling_group.NAT_AZ2, 
                                        module.VPC.aws_autoscaling_group.NAT_AZ2 (destroy), 
                                          module.VPC.aws_subnet.DMZ_AZ2 (destroy),  
                                            module.VPC.aws_vpc.VPC (destroy), 
                                              module.VPC.aws_vpc.VPC
```

I am not sure what the dependency direction is here since, for instance, I don't see how ```module.VPC.aws_subnet.DMZ_AZ2``` and ```module.VPC.aws_security_group.BASTION (destroy)``` are directly related.

**Comment by rodlogic** [comment]
If I remove the ```module.VPC.aws_launch_configuration.NAT``` manually (including the 2 aws_autoscaling_groups) I only then can destroy again.

**Comment by rodlogic** [comment]
Even if I duplicate the module.VPC.aws_launch_configuration.NAT, one for each AZ, the cycle is still there. The only way to destroy is to manually delete the two autoscaling groups and the launch configuration, then continue with terraform destroy.

**Comment by catsby** [comment]
Hello all – are you using the `create_before_destroy` lifecycle hook by chance? There is a caveat with using that hook at the moment, regarding it's dependencies. In short, if a resource using `create_before_destroy` depends on another resource, then that dependency must also have `create_before_destroy` specified. 

- https://terraform.io/docs/configuration/resources.html

If you have a sample configuration to share (omitting any secrets) I can confirm or investigate more. Thanks!

**Comment by kumarsarath588** [comment]
Hi,

Removing the following configuration from all of my aws launch configurations resolved the error.

lifecycle {
    create_before_destroy = true
}
Thank you.
