### ISSUE TITLE
Add an "arn" attribute for aws_s3_bucket

### ISSUE THREAD

**Issue by yawn** [hashicorp/terraform#3666]
* Tested against v0.6.5.
* Needed for referencing buckets in policies.
* Implementation: just prefix the bucket name with `arn:aws:s3:::`

**Comment by stack72** [comment]
This is very straightforward and follows the rules as per the [docs](http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-s3)

Just opened #3666 for this

**Comment by catsby** [comment]
We merged #3685, so I'm going to close this. Thanks all!

**Comment by yawn** [comment]
That was pretty fast - thx!
