### ISSUE TITLE
RDS aws_db_security_group resource consistency with aws_security_group

### ISSUE THREAD

**Issue by pmoust** [hashicorp/terraform#367]
Perhaps mock `aws_security_group`'s `cidr_blocks` and `security_groups` to be used for resource `aws_db_security_group` as well, in place of `cidr` and `security_group_id`.

**Comment by catsby** [comment]
Hey @pmoust – I realize this issue is really old by now, but do you think it's still valid? It looks like we have an [ingress block][1] now

[1]: https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_security_group.go#L37
