### ISSUE TITLE
DigitalOcean destroy does not handle 404 on droplet

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#3670]
If I create a DigitalOcean droplet with Terraform, then remove the droplet via the DigitalOcean web console, a `terraform destroy` fails with a 404 error and won't continue. Other Terraform providers seem to handle this case by handling the 404 as a successful destroy and continuing on.

Tested with Terraform **v0.6.6**. 

Terraform config:
```
provider "digitalocean" {
}

resource "digitalocean_droplet" "example" {
  image  = "ubuntu-14-04-x64"
  name   = "example"
  region = "nyc2"
  size   = "512mb"
}
```

Abridged Terraform output...
```
$ terraform apply terraform

digitalocean_droplet.example: Creating...
  image:                "" => "ubuntu-14-04-x64"
  ipv4_address:         "" => "<computed>"
  ipv4_address_private: "" => "<computed>"
  ipv6_address:         "" => "<computed>"
  ipv6_address_private: "" => "<computed>"
  locked:               "" => "<computed>"
  name:                 "" => "example"
  region:               "" => "nyc2"
  size:                 "" => "512mb"
  status:               "" => "<computed>"
digitalocean_droplet.example: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

...

$ 
$ # Droplet removed via DO console
$ 
$ terraform destroy terraform

...

digitalocean_droplet.example: Refreshing state... (ID: 8457342)
Error refreshing state: 1 error(s) occurred:

* digitalocean_droplet.example: Error retrieving droplet: GET https://api.digitalocean.com/v2/droplets/8457342: 404 The resource you were accessing could not be found.
$
```

**Comment by stack72** [comment]
@clstokes this is because the DigitalOceanDropletRead has the following logic

```
// Retrieve the droplet properties for updating the state
	droplet, _, err := client.Droplets.Get(id)
	if err != nil {
		// check if the droplet no longer exists.
		if err.Error() == "Error retrieving droplet: API Error: 404 Not Found" {
			d.SetId("")
			return nil
		}

		return fmt.Errorf("Error retrieving droplet: %s", err)
	}
```

The string is hard coded and may have changed when we moved to the Official DigitalOcean Goclient

I will submit a PR not to fix this

**Comment by clstokes** [comment]
@stack72, ah, that makes sense. Is the response code (404) available on the `err`? It seems that'd be the most future-proof way to fix it, yea?

**Comment by stack72** [comment]
@clstokes tried with a string (which was not future proof) and @catsby suggested to use the 404 as well :)

PR is currently re-building

**Comment by clstokes** [comment]
That Clint is a clever one. 😉

**Comment by catsby** [comment]
![helping](https://cloud.githubusercontent.com/assets/61721/10976259/7372072a-83b0-11e5-8b1d-4a6a67fe6be7.gif)

**Comment by catsby** [comment]
Merged #3768

**Comment by omarabid** [comment]
I'm still getting this error.

**Comment by omarabid** [comment]
Terraform version 0.6.8
