### ISSUE TITLE
Support "tags" for CloudStack resources

### ISSUE THREAD

**Issue by hany** [hashicorp/terraform#3678]
Similar to AWS, CloudStack supports the use of [resource tags](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Resource+Tags). Terraform should allow one to edit such tags, in the same way this can be done with the AWS provider.

**Comment by svanharmelen** [comment]
@hany I think the basic support for tags is now landed with PR #4742, so I'll be closing this issue and will of course be happy to review and merge any PR's updating specific resources to use the new tag functionality.
