### ISSUE TITLE
Cannot exorcise resource.

### ISSUE THREAD

**Issue by tvaughan** [hashicorp/terraform#3680]
I'm trying to work around #3670 . I'm trying to build a terraform.tfstate that matches what's in the DigitalOcean dashboard. I had a DigitalOcean DNS TXT record that was deleted in the DigitalOcean dashboard. So I deleted it from terraform.tfstate and terraform.tfstate.backup. I deleted the appropriate environment in the Atlas dashboard. And I deleted `~/.terraform.d`. Finally I deleted the TXT record from my Terraform configuration. Yet somehow terraform still knows about this resource. How?

    $ terraform plan
    Refreshing Terraform state prior to plan...

    digitalocean_record.spf1: Refreshing state... (ID: 7947055)
    digitalocean_ssh_key.tvaughan: Refreshing state... (ID: 1057394)
    digitalocean_domain.sumario: Refreshing state... (ID: sumar.io)
    digitalocean_record.www: Refreshing state... (ID: 7947056)
    digitalocean_record.mx2: Refreshing state... (ID: 9829365)
    digitalocean_record.mx1: Refreshing state... (ID: 9829366)
    digitalocean_record.mandrill_domainkey: Refreshing state... (ID: 7947054)
    digitalocean_droplet.app: Refreshing state... (ID: 6970246)
    digitalocean_record.app: Refreshing state... (ID: 8483882)
    Error refreshing state: 1 error(s) occurred:

    * digitalocean_record.spf1: GET https://api.digitalocean.com/v2/domains/sumar.io/records/7947055: 404 The resource you were accessing could not be found.

`$ find . -type f | xargs grep -n spf` has no output. What did I miss? Thanks.

    $ terraform --version
    Terraform v0.6.6

**Comment by tvaughan** [comment]
OK. It looks like I didn't delete the appropriate environment from Atlas (despite clicking the delete button and the ok button to confirm). Problem solved.

**Comment by catsby** [comment]
Thank you for following up! Sorry we didn't get around to this sooner, please let us know if you run into anything else
