### ISSUE TITLE
Support to configure buildpack on heroku applications

### ISSUE THREAD

**Issue by sobrinho** [hashicorp/terraform#3698]
Would be nice to have it on terraform like this:

``` terraform
resource "heroku_app" "staging" {
    name = "app-staging"
    region = "us"
    buildpack = "https://github.com/ddollar/heroku-buildpack-multi.git"
}
```

Makes sense?

**Comment by stack72** [comment]
@sobrinho this ability doesn't even exist on the heroku app itself

<img width="907" alt="screen shot 2015-10-30 at 14 35 58" src="https://cloud.githubusercontent.com/assets/227823/10848361/913feb10-7f13-11e5-8270-101cc5ec92b4.png">

Isn't the buildpack determined by the system?

**Comment by catsby** [comment]
Build packs are a valid API resource: 

- https://devcenter.heroku.com/articles/platform-api-reference#buildpack-installations

It's not part of the app create though, so you'd need to `create` and then update the buildpack(s) in the `update` method. 

The attribute should be a set too, since you can have more than 1, and the order matters:

```hcl
buildpacks = [
  "nginx",
  "ruby",
]
```

**Comment by catsby** [comment]
> Isn't the buildpack determined by the system?

Typically, yes, if omitted Heroku attempts detection. Otherwise you can specify your own list

**Comment by sobrinho** [comment]
@catsby you can only have one build pack per app.

Although you can use heroku-buildpack-multi to use multiple build packs but this feature is a build pack you configure and in your application you specify which build packs do you want.

**Comment by catsby** [comment]
Heroku has expanded their multi buildpack support, it's a first class feature now: 

- https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

We can use the buildpacks API I mentioned to manage them :smile:

**Comment by sobrinho** [comment]
Well done, I didn't know that, thanks for the link!

**Comment by fgrehm** [comment]
If someone is looking for a workaround, it is as easy as setting the `BUILDPACK_URL` environmental variable:

```tf
resource "heroku_app" "app" {
  config_vars {
    BUILDPACK_URL = "..."
  }
}
```

That is going to be [eventually deprecated](https://devcenter.heroku.com/articles/buildpacks#setting-a-buildpack-on-an-application) but does the job now :beers:

**Comment by benschwarz** [comment]
@catsby, being that his is part of the provisioning of an app, would it be accepted as an extension to the existing heroku_app provider?

**Comment by felipesere** [comment]
I'd be interested in this. I have not yet contributed to Terraform (and have barely done any Go), but I'd be up for giving it a stab if someone can mentor me.
