### ISSUE TITLE
add placement_group as an option for autoscaling groups

### ISSUE THREAD

**Issue by dayer4b** [hashicorp/terraform#3703]
I believe this should accept the name of the placement group in question:

http://docs.aws.amazon.com/cli/latest/reference/autoscaling/create-auto-scaling-group.html
> --placement-group (string)
> 
>     The name of the placement group into which you'll launch your instances, if any. For more information, see Placement Groups in the Amazon Elastic Compute Cloud User Guide .

I'll try to make a pull request

**Comment by stack72** [comment]
ah @dayer4b, my apologies. I just opened a PR for this before I saw you had done so too. I will close mine and add some comments to yours

**Comment by stack72** [comment]
This was merged in #3704
