### ISSUE TITLE
OpenStack v3 Support

### ISSUE THREAD

**Issue by afritzler** [hashicorp/terraform#3711]
Hi,

I was wondering if there any plans to support the v3 APIs of OpenStack any time soon?

Regards,
Andreas

**Comment by jtopjian** [comment]
Hello,

Which v3 services are you referring to? Keystone is the only service at the moment that has a v3 API. There aren't any Keystone resources for Terraform since authentication is done prior to using Terraform.

Let me know if that helps or if you need any more info :)

**Comment by afritzler** [comment]
I am asking, because the provider configuration is tailored towards v2.0.
```
provider "openstack" {
    user_name  = "admin"
    tenant_name = "admin"
    password  = "pwd"
    auth_url  = "http://myauthurl:5000/v2.0"
}
```
Will it also work with `domain_name` and a v3 endpoint as the `auth_url`?

**Comment by jtopjian** [comment]
Ah, right. Sorry about that - I overlooked the actual provider block. :smile:  

That should work, yes. There's nothing in Terraform restricting provider authentication to only Keystone v2. It defers everything to Gophercloud, which supports both v2 and v3. 

You're able to specify a `domain_name` or a `domain_id` in the provider block, so adding that along with the v3 URL _should_ work. Let me know if you run into problems, though.

**Comment by afritzler** [comment]
Thanks @jtopjian for the clarification!
