### ISSUE TITLE
Vsphere plugin error: ServerFaultCode: Permission to perform this operation was denied.

### ISSUE THREAD

**Issue by kc11381** [hashicorp/terraform#3720]
Hi,

I am getting following error with vsphere provider even though the user can create vm's manually.:

Error applying plan:
2015/11/01 21:08:02 [DEBUG] root: eval: *terraform.EvalWriteState
2015/11/01 21:08:02 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2015/11/01 21:08:02 [DEBUG] root: eval: *terraform.EvalIf
2015/11/01 21:08:02 [DEBUG] root: eval: *terraform.EvalWriteDiff
2015/11/01 21:08:02 [DEBUG] root: eval: *terraform.EvalIf
2015/11/01 21:08:02 [DEBUG] root: eval: *terraform.EvalWriteState
2015/11/01 21:08:02 [DEBUG] root: eval: *terraform.EvalApplyPost
2015/11/01 21:08:02 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.X: ServerFaultCode: Permission to perform this operation was denied.
2015/11/01 21:08:02 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.X: ServerFaultCode: Permission to perform this operation was denied.
2015/11/01 21:08:02 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* vsphere_virtual_machine.X: ServerFaultCode: Permission to perform this operation was denied.
2015/11/01 21:08:02 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.X ServerFaultCode: Permission to perform this operation was denied.
2015/11/01 21:08:02 [DEBUG] vertex provider.vsphere (close), got dep: vsphere_virtual_machine.X
2015/11/01 21:08:02 [DEBUG] vertex root, got dep: provider.vsphere (close)
2015/11/01 21:08:02 [DEBUG] waiting for all plugin processes to complete...

1 error(s) occurred:

* vsphere_virtual_machine.esa-X: ServerFaultCode: Permission to perform this operation was denied.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Please let me know how to fix this.

Regards,
Kanhaiya

**Comment by chrislovecnm** [comment]
What role(s) does the user have, and have you tried a full admin account?  Either there is an api specific role, or you need admin ... I unfortunately cannot recall.

**Comment by kc11381** [comment]
Hi chrislovecnm,

Thank you for the reply. You guessed it correct. User was having permission issues on VC itself.

**Comment by chrislovecnm** [comment]
@kc11381 glad we could help!

**Comment by mauryarr** [comment]
Hey kc11381:
I am having same issue. How did you resolve it?

**Comment by kc11381** [comment]
@mauryarr : User was having permission issues on VC.

**Comment by mauryarr** [comment]
Hey, VC as in?
