### ISSUE TITLE
Error when downloading sub-modules from the same source

### ISSUE THREAD

**Issue by mechastorm** [hashicorp/terraform#3733]
I am not too sure if it is a bug or is it perhaps my use case is not the norm.

My terraform stack calls in two modules (Module A and B). Both modules (A & B) in turn call in a Common module. Both modules are calling Common module via the Git protocol.

Problem I encountered was that terraform does not seem to like to redownload the same module twice over Git.

```
Get: file:///..._modules/A
Get: file:///..._modules/C
Get: git::ssh://git@github.hootops.com/terraform/hsc-common.git?ref=0.2.0
Error loading Terraform: Error downloading modules: error downloading 'ssh://git@github.com/common.git?ref=0.2.0': /usr/bin/git exited with 128: fatal: could not create work tree dir '.terraform/modules/3cc4408039cce1cab31588bb33b54fc5'.: File exists
```

My guess is that it needs file permission to write and is unable to overwrite it.?
My workaround was to remove the Common module from Git and add it instead as a local module instead. That seems to get Terraform to be happy.

```
$ terraform get
Get: file:///.../_modules/A
Get: file:///.../_modules/B
Get: file:///.../_module/common
Get: file:///.../_module/common
```

**Comment by antonbabenko** [comment]
Have you tried `$ terraform get -update` ?

**Comment by mechastorm** [comment]
The issue seems to have resolved itself after I purged the `.terraform` folder and redid terraform get

**Comment by mitchellh** [comment]
Hm, I think that it shouldn't be attempting to download it. This is definitely a bug that I'll have to take a look at.

**Comment by mitchellh** [comment]
I can't reproduce this in master. I think due to changes we made this no longer collides. However, it will download twice [for now].
