### ISSUE TITLE
DigitalOcean provider should replace a droplet when the userdata is changed

### ISSUE THREAD

**Issue by nekinie** [hashicorp/terraform#3734]
I think the DigitalOcean provider should replace a droplet when the userdata is changed, currently it just updates but the userdata is normally only run during first boot, so this change will never be applied to the droplet.

**Comment by stack72** [comment]
@nekinie I would tend to agree. PR on way :)

**Comment by nekinie** [comment]
well that was fast

**Comment by stack72** [comment]
@nekinie well let's hope that the contributors / owners like it :)
