### ISSUE TITLE
Issue with changing aws_instance and "diffs didn't match during apply"

### ISSUE THREAD

**Issue by colinmutter** [hashicorp/terraform#3738]
After changing the user_data on an aws_instance resource, and subsequently adding ignore_changes = ["user_data"], the resource was forced to be created (another problem in itself) but once it was deleted it would fail to re-create with error:

```
2015/11/03 13:55:55 [ERROR] aws_instance.test: diffs didn't match
2015/11/03 13:55:55 [ERROR] aws_instance.test: reason: extra attributes: user_data
2015/11/03 13:55:55 [ERROR] root: eval: *terraform.EvalCompareDiff, err: aws_instance.test: diffs didn't match during apply. This is a bug with Terraform and should be reported.
2015/11/03 13:55:55 [ERROR] root: eval: *terraform.EvalSequence, err: aws_instance.test: diffs didn't match during apply. This is a bug with Terraform and should be reported.
2015/11/03 13:55:55 [ERROR] root: eval: *terraform.EvalOpFilter, err: aws_instance.test: diffs didn't match during apply. This is a bug with Terraform and should be reported.
2015/11/03 13:55:55 [ERROR] root: eval: *terraform.EvalSequence, err: aws_instance.test: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

Repeated attempts to terraform plan would show the creation of a new resource:

```
+ aws_instance.test
    ami:                               "" => "ami-123456"
    source_dest_check:                 "" => "1"
    subnet_id:                         "" => "subnet-123456"
    tags.#:                            "" => "4"
    ... bits removed for security ...
    user_data:                         "" => "hash-here"
```

But running it would produce the same error.

```
* aws_instance.test: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

Once this lifecycle clause was *removed* from the config...

```
  lifecycle {
    ignore_changes = ["user_data"]
  }
```

The resources were created just fine.  The big problem here is that we need to be able to ignore changes on attributes like user_data without causing the tfstate to be corrupted (er, out of sync).

**Comment by pdecat** [comment]
Got the same issue: commenting the `lifecycle { ignore_changes = ["user_data"] }` directive during instance creation worked.

Thanks @colinmutter!

**Comment by phinze** [comment]
Hi folks, rolling up `ignore_changes` problems into #5627 and tackling fixes today. Head there for updates!
