### ISSUE TITLE
terraform destroy fails with "Resource X no longer exists"

### ISSUE THREAD

**Issue by sl1pm4t** [hashicorp/terraform#3742]
A Google Compute Instance was manually deleted (outside of terraform control), and subsequent attempts to run `terraform destroy` to clean up other resources in that envronment resulted in the following error:
```
Error refreshing state: 1 error(s) occurred:

* google_compute_instance.instance: Resource <project> no longer exists
```

First, the error is confusing in that it gives the project name instead of the instance name, and second, IMO this shouldn't prevent the `destroy` operation from completing.

I have tested a fix and will be submitting a PR soon.

**Comment by lwander** [comment]
I'm a little hesitant to allow `destroy` to succeed silently if a machine was destroyed outside of Terraform's control, given that any other stage would fail. Although it does seem silly to block a user from cleaning up other resources because Terraform can't destroy a resource that's already gone. I'd prefer to have Terraform at least let the user know that their destroy due to a missing resource in the form of a warning message. Is there a precedent for this, @phinze, @catsby?

**Comment by apparentlymart** [comment]
@iwander the usual behavior is for `Read` to detect the "not found" case, produce a `[WARN]` log about it, and then called `d.SetId("")` to let Terraform know the resource is gone.

By doing this, `plan` will run from the position of the resource not existing at all, and so in the `destroy` case it will be a no-op and in the `apply` case it will create a fresh instance to replace the now-missing one.

A very similar change was recently made for AWS ElastiCache clusters in #3767.

**Comment by lwander** [comment]
@apparentlymart, looks like this is already the behavior [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/resource_compute_instance.go#L288). @sl1pm4t, could you try running `plan`, then `destroy` on your example to see if it works as expected?

**Comment by apparentlymart** [comment]
@iwander I think the problem is the following line, where it returns an error. Not sure how the rest of this code is structured, but ultimately you want `Read` to return `nil` having set the id to `""`, so maybe what's needed here is `return nil, nil`? Seems weird, but...... :grinning:

**Comment by catsby** [comment]
That is the precedent. We can open a separate issue to discuss if that _should_ be the behavior if you'd like

**Comment by lwander** [comment]
@catsby, no I think what @apparentlymart pointed as the default sounds much better. 

btw, @apparentlymart, my ID is lwander with an 'L', not an 'I' - just pointing it out so we don't keep pinging iwander.

**Comment by apparentlymart** [comment]
@lwander oh whoops... sorry. That's much clearer now I'm at work and on a screen with a decent pixel density. :blush:

**Comment by sl1pm4t** [comment]
I added WARN logging for the case where the instance no longer exists (although this is only seen if TF_LOG is set).
 
Also @lwander  I tested `terraform plan` and `terraform destroy` as requested and did not hit any errors. I replaced the `terraform.tfstate` with the backup between `plan` and `destroy` steps that both operations expect the instance still exists.

```
mmorrison@orca-2:~$ gcloud compute instances delete gce-inst-to-destroy
The following instances will be deleted. Attached disks configured to 
be auto-deleted will be deleted unless they are attached to any other 
instances. Deleting a disk is irreversible and any data on the disk 
will be lost.
 - [gce-inst-to-destroy] in [us-central1-f]

Do you want to continue (Y/n)?  y

Deleted [https://www.googleapis.com/compute/v1/projects/t3-lab-us/zones/us-central1-f/instances/gce-inst-to-destroy].

mmorrison@orca-2:~$ terraform plan
Refreshing Terraform state prior to plan...

module.gce-inst-to-destroy.consul_keys.user: Refreshing state... (ID: consul)
module.gce-inst-to-destroy.consul_keys.globals: Refreshing state... (ID: consul)
module.gce-inst-to-destroy.google_compute_instance.instance: Refreshing state... (ID: gce-inst-to-destroy)

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ module.gce-inst-to-destroy.google_compute_instance.instance
    can_ip_forward:                             "" => "0"
    disk.#:                                     "" => "1"
    disk.0.auto_delete:                         "" => "1"
    disk.0.image:                               "" => "bw-base-centos-6"
    disk.0.size:                                "" => "200"
    machine_type:                               "" => "n1-standard-2"
    metadata_fingerprint:                       "" => "<computed>"
    name:                                       "" => "gce-inst-to-destroy"
    network_interface.#:                        "" => "1"
    network_interface.0.access_config.#:        "" => "1"
    network_interface.0.access_config.0.nat_ip: "" => "<computed>"
    network_interface.0.address:                "" => "<computed>"
    network_interface.0.name:                   "" => "<computed>"
    network_interface.0.network:                "" => "default"
    self_link:                                  "" => "<computed>"
    service_account.#:                          "" => "1"
    service_account.0.email:                    "" => "<computed>"
    service_account.0.scopes.#:                 "" => "3"
    service_account.0.scopes.1328717722:        "" => "https://www.googleapis.com/auth/devstorage.read_write"
    service_account.0.scopes.2428168921:        "" => "https://www.googleapis.com/auth/userinfo.email"
    service_account.0.scopes.2862113455:        "" => "https://www.googleapis.com/auth/compute.readonly"
    tags.#:                                     "" => "1"
    tags.435184474:                             "" => "terraformed"
    tags_fingerprint:                           "" => "<computed>"
    zone:                                       "" => "us-central1-f"


Plan: 1 to add, 0 to change, 0 to destroy.

mmorrison@orca-2:~$ cp terraform.tfstate.backup terraform.tfstate

mmorrison@orca-2:~$ terraform destroy
Do you really want to destroy?
  Terraform will delete all your managed infrastructure.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

module.gce-inst-to-destroy.consul_keys.user: Refreshing state... (ID: consul)
module.gce-inst-to-destroy.consul_keys.globals: Refreshing state... (ID: consul)
module.gce-inst-to-destroy.google_compute_instance.instance: Refreshing state... (ID: gce-inst-to-destroy)
consul_keys.user: Destroying...
consul_keys.globals: Destroying...
consul_keys.globals: Destruction complete
consul_keys.user: Destruction complete

Apply complete! Resources: 0 added, 0 changed, 2 destroyed.
```

**Comment by lwander** [comment]
@sl1pm4t, I would rather stick with the precedent outlined by @apparentlymart where we rely on `plan` to get us out of situations where we try to remove infrastructure that's been destroyed outside of Terraform. 

This has two benefits:
  1. It keeps the Google provider's behavior in line with that of the rest of the Terraform providers. 
  2. It makes infrastructure failures more explicit. If we can't run `destroy`, it enforces running `plan` to see what's going on (which is good practice anyhow).

This should be how the `google_compute_instance` resource handles these failures right now, unless something strange is going on by returning `nil, fmt.Errorf(...)`.

**Comment by sl1pm4t** [comment]
Sorry - I misunderstood @apparentlymart comment and thought he was describing what I had implemented. I will take another look.

**Comment by lwander** [comment]
No worries! Sorry to have you change this back and forth.

**Comment by sparkprime** [comment]
I think the approach laid out by @apparentlymart is pretty elegant and we should do it for all the other resources as well :)

**Comment by lwander** [comment]
I'll take inventory of which resources are missing this approach and hopefully have a PR soon.

**Comment by sl1pm4t** [comment]
@lwander I took another look at this, and stand by what I've done as achieving what @apparentlymart described. On `Read` if the compute instance no longer exists, the resources ID is [cleared](https://github.com/sl1pm4t/terraform/blob/5f90a4bc7e96ca0715629d769889357db42088a3/builtin/providers/google/resource_compute_instance.go#L290) and `Read` will [return nil](https://github.com/sl1pm4t/terraform/blob/5f90a4bc7e96ca0715629d769889357db42088a3/builtin/providers/google/resource_compute_instance.go#L555) without an error.

Perhaps the reason my change looks different than other resources, is because the call to Google API to retrieve instance data is done in the `getInstance()` func that is used by both `Read` and `Update`. I left generation of the error in `getInstance()` so that it will be propagated in the `Update` case.

If I'm missing @apparentlymart's point, please let me know. :)

**Comment by lwander** [comment]
@sl1pm4t sorry for the delay. Do you mean this [here](https://github.com/sl1pm4t/terraform/commit/5f90a4bc7e96ca0715629d769889357db42088a3)? That LGTM!

**Comment by sl1pm4t** [comment]
@lwander yes and in the [second commit](https://github.com/hashicorp/terraform/commit/ede5ebb368bdf0a07e3ce57d1af6fb89332f0cb7) I added logging, as requested earlier in this thread.

**Comment by lwander** [comment]
Looks good, do you have a PR open for this?

**Comment by sl1pm4t** [comment]
@lwander PR is #3763
