### ISSUE TITLE
Syntax for variables requiring lookups and not using defaults?

### ISSUE THREAD

**Issue by nathanielks** [hashicorp/terraform#3745]
Happy Tuesday, Hashicorp!

I just realized I'm not sure I've seen it documented anywhere how to define vars requiring lookups in the tfvars file? Context in case this isn't clear:

```
variable "some_var" {
    default = {
        "varA" = "flip"
        "varB" = "flop"
    }
}
```

How would I override this in my `terraform.tfvars" file using the ini syntax? Dot notation?

**Comment by phinze** [comment]
Hi @nathanielks - good question!

You can find this documentation under "Assigning Mappings" here: https://terraform.io/intro/getting-started/variables.html

Basically, you need the `default` to be at least `{}` to declare the variable as a mapping, then you can use dot notation in `tfvars` to set keys.

**Comment by nathanielks** [comment]
Thanks @phinze, you're awesome :+1:
