### ISSUE TITLE
Support AWS Redshift

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#3753]
Amazon Redshift is a fully managed, petabyte-scale data warehouse. It consists of **nodes** in a **cluster**, similar to RDS Cluster and RDS Cluster Instance

Getting started:
- http://docs.aws.amazon.com/fr_fr/redshift/latest/gsg/getting-started.html

API guide:
- http://docs.aws.amazon.com/fr_fr/redshift/latest/APIReference/Welcome.html

**Comment by stack72** [comment]
@catsby @phinze @radeksimko have any of you started this work? If not then I will get cracking with it as it goes hand in hand with part 2 of my Kinesis Firehouse stuff

**Comment by catsby** [comment]
I have not, by all means have at it! Thanks!

**Comment by stack72** [comment]
OK @catsby this can probably be closed then. I will open a WIP PR for the redshirt stuff now to replace it

**Comment by apparentlymart** [comment]
Closing this in favor of #3862
