### ISSUE TITLE
aws_rds_cluster: backup_retention_period is not actually supported

### ISSUE THREAD

**Issue by maxim** [hashicorp/terraform#3755]
Docs claim that `backup_retention_period` can be set on `aws_rds_cluster`, but it's not implemented.

    Errors:

      * aws_rds_cluster.default: : invalid or unknown key: backup_retention_period

**Comment by stack72** [comment]
@maxim PR incoming :)

**Comment by maxim** [comment]
:+1:

**Comment by stack72** [comment]
@maxim PR is now open #3757
