### ISSUE TITLE
aws_db_instance: InvalidParameterCombination: Both storage size and iops need to be specified

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#3760]
> _Sorry for the long bug report but it's a relatively complicated one._

### Original Problem

When managing an AWS RDS instance with `aws_db_instance`, AWS requires changes to `allocated_storage` or `iops` to include both parameters in the API request. When changing one or the other with Terraform, Terraform seems to only send the one changed parameter and the request fails with the _InvalidParameterCombination_ error below.

### Second Problem

Furthermore, it seems when changing just `iops`, Terraform will exit with an error, but the state file is updated as if the change were successful so subsequent _plans_ or _applies_ don't attempt changes.

```
$ terraform apply
aws_db_instance.default: Refreshing state... (ID: mydb-rds)
aws_db_instance.default: Modifying...
  iops: "2000" => "3000"
Error applying plan:

1 error(s) occurred:

* aws_db_instance.default: Error modifying DB Instance mydb-rds: InvalidParameterCombination: Both storage size and iops need to be specified when modifying storage size or iops on an DB Instance that has iops
	status code: 400, request id: ed0f3540-832a-11e5-8790-d54abb152884

...
$ terraform apply
aws_db_instance.default: Refreshing state... (ID: mydb-rds)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
$
```

This does not occur when changing just `allocated_storage`. `allocated_storage` does get updated in the state file as if it were successful, **but**, it seems the refresh is what's triggering future change attempts.

```
$ terraform apply
aws_db_instance.default: Refreshing state... (ID: mydb-rds)
aws_db_instance.default: Modifying...
  allocated_storage: "400" => "500"
Error applying plan:

1 error(s) occurred:

* aws_db_instance.default: Error modifying DB Instance mydb-rds: InvalidParameterCombination: Both storage size and iops need to be specified when modifying storage size or iops on an DB Instance that has iops
	status code: 400, request id: 082d0a59-832b-11e5-831e-1104c2a60b4d

...
$ terraform apply
aws_db_instance.default: Refreshing state... (ID: mydb-rds)
aws_db_instance.default: Modifying...
  allocated_storage: "400" => "500"
Error applying plan:

1 error(s) occurred:

* aws_db_instance.default: Error modifying DB Instance mydb-rds: InvalidParameterCombination: Both storage size and iops need to be specified when modifying storage size or iops on an DB Instance that has iops
	status code: 400, request id: 0b2b085b-832b-11e5-831e-1104c2a60b4d

...
$
```

### Third Problem

Lastly, when doing a `terraform refresh` (or when it's performed by a _plan_ or _apply), `allocated_storage` gets updated correctly in the state file, but `iops` does not.

### Config to Reproduce
```
resource "aws_db_instance" "default" {
  identifier = "mydb-rds"
  engine = "mysql"
  engine_version = "5.6.23"
  instance_class = "db.t2.large"
  name = "mydb"
  username = "foo"
  password = "barbarbar"
  parameter_group_name = "default.mysql5.6"

  apply_immediately = true

  storage_type = "io1"
  allocated_storage = 500
  iops = 2000

  lifecycle {
    #ignore_changes = ["allocated_storage","iops"]
  }

}
```

### Recap

There's potentially three inter-related bugs here:

1. Both `allocated_storage` and `iops` parameters must be sent to AWS when changing either of them.
2. An error when changing just `iops` updates Terraform's state as if it were successful.
3. `terraform refresh` does not update the `iops` property.

### Temporary Workaround

A temporary workaround is to manage `allocated_storage` and `iops` via the AWS console and uncomment the `ignore_changes` property in the config so Terraform will ignore these until this issue is resolved.

**Comment by woodhull** [comment]
I'm also running into this problem. It's not possible to change a db instance's storage_type from standard magnetic to iops. The error message from AWS says:

```
* aws_db_instance.default: Error modifying DB Instance agra-aws-production-rds: InvalidParameterCombination: The storage type io1 requires iops to be specified.
	status code: 400, request id: b2c8c201-99f0-11e5-b164-03677e7ce1fd
```

The change to the iops parameter from blank -> to "1000" doesn't seem to get picked up by terraform in either the plan or apply steps, so the change from standard to iops storage fails.

**Comment by phinze** [comment]
(Just double checked and noted that this seems to still be a problem in the current implementation.)

**Comment by catsby** [comment]
Opened #7203 to patch this
