### ISSUE TITLE
provider/aws: unable to bootstrap a spot instance (connection data is not set)

### ISSUE THREAD

**Issue by jwmarshall** [hashicorp/terraform#3762]
Maybe I'm missing something silly here, but I cannot seem to bootstrap a spot instance with terraform.

My terraform file:

```
provider "aws" {
    region = "us-east-1"
}

resource "aws_spot_instance_request" "staging" {
    availability_zone = "us-east-1c"
    instance_type = "m4.xlarge"
    spot_price = "0.25"
    ami = "ami-9eaa1cf6"
    key_name = "chef-client"
    subnet_id = "subnet-*****"
    security_groups = ["sg-*****","sg-*****","sg-*****"]
    wait_for_fulfillment = true
    associate_public_ip_address = true
    ebs_optimized = true
    root_block_device = {
        volume_size = 64
        volume_type = "gp2"
        delete_on_termination = false
    }
    tags {
        Name = "staging"
    }
    provisioner "chef" {
      version = "11.18.6"
      validation_client_name = "chef-validator"
      validation_key_path = "~/.chef/chef-validator.pem"
      secret_key_path = "~/.chef/encrypted_data_bag_secret"
      server_url = "http://chef.*****.com"
      environment = "staging"
      node_name = "*****"
      run_list = ["role[bootstrap_ec2]"]
    }
    connection {
        type = "ssh"
        user = "ubuntu"
        key_file = "~/.ssh/chef-client.pem"
    }
}
```

The spot instance is requested, fulfilled, but never bootstrapped. Once the instance exists terraform simply displays the following lines over and over until it a timeout is reached.

```
aws_spot_instance_request.staging (chef): Connecting to remote host via SSH...
aws_spot_instance_request.staging (chef):   Host:
aws_spot_instance_request.staging (chef):   User: ubuntu
aws_spot_instance_request.staging (chef):   Password: false
aws_spot_instance_request.staging (chef):   Private key: true
aws_spot_instance_request.staging (chef):   SSH Agent: true
```

**Comment by svanharmelen** [comment]
I don't see a value for the host attribute in the connection logging, so maybe add a reference to the associated IP in the connection block (probably using an interpolated value)?

**Comment by jwmarshall** [comment]
No luck. The resulting attribute should exist as aws_spot_instance_request bases itself on the aws_instance schema. 
```
Resource 'aws_spot_instance_request.staging' does not have attribute 'private_ip' for variable 'aws_spot_instance_request.staging.private_ip'
```

According to the docs this should be provided automatically. (https://terraform.io/docs/provisioners/connection.html) 

`host - The address of the resource to connect to. This is provided by the provider.`

**Comment by svanharmelen** [comment]
@jwmarshall I just had a look at the code and noticed that the connection data is not set in the spot resource. So I guess (based on the docs) this should be labeled as a bug and needs to be fixed...

**Comment by jwmarshall** [comment]
Makes sense. Thanks for your help! If I have some time this weekend and the local development setup isnt too difficult I can look at bringing the relevant lines out of aws_instance.

**Comment by jmreicha** [comment]
+1 I just ran in to this as well.

**Comment by jwmarshall** [comment]
Yea haven't had anytime to try and tackle this one myself. Maybe I can find a few hours on the weekend.

**Comment by catsby** [comment]
I have a patch for this, once I get a test confirming I'll open a PR

**Comment by jwmarshall** [comment]
:+1:

**Comment by catsby** [comment]
Fix is in https://github.com/hashicorp/terraform/pull/3940 , if you can, take it for a spin, otherwise it is under review. I was able to get this to work:

```hcl
resource "aws_spot_instance_request" "cheap_worker" {
  ami                         = "ami-6f6d635f"
  spot_price                  = "0.04"
  instance_type               = "t1.micro"
  wait_for_fulfillment        = true
  subnet_id                   = "${aws_subnet.tf_test_subnet.id}"
  vpc_security_group_ids      = ["${aws_security_group.tf_test_sg_ssh.id}"]
  key_name                    = "${aws_key_pair.ssh_thing.key_name}"
  associate_public_ip_address = true

  provisioner "remote-exec" {
    connection {
      user     = "ubuntu"
      key_file = "/Users/clint/.ssh/id_rsa2"
      agent    = "false"
    }

    inline = [
      "echo 'hello world'",
    ]
  }
}
```

Where the subnet and Sg are configured to all SSH
