### ISSUE TITLE
Cycle error on destroy

### ISSUE THREAD

**Issue by rodlogic** [hashicorp/terraform#3766]
I got the following error while executing ```terraform destroy```:
```
* Cycle: provider.aws.OPS, aws_iam_group_policy.QA-ADMIN-ASSUMEROLE (destroy), terraform_remote_state.OPS (destroy), terraform_remote_state.OPS
```

I have two layers of terraform: a layer QA that depends on layer OPS through terraform.tfstate remote state. ```OPS``` creates an ```ops-admin``` group and with one policy in account a. When ```QA``` is created, it adds a ```qa-admin-assumerole``` policy on the existing ```ops-admin``` group in ```OPS```.
These are the relevant resources in ```OPS```:
```
resource "aws_iam_group" "OPS-ADMIN" {
  name = "ops-admin"
  path = "/ops/"
}
resource "aws_iam_group_policy" "OPS-ADMIN" {
  name = "ops-admin"
  group = "${aws_iam_group.OPS-ADMIN.id}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
EOF
}
```

These are the relevant resources in ```QA``` (note that ```QA``` is adding a new policy to ```OPS``` ```ops-admin``` group):
```
resource "terraform_remote_state" "OPS" {
    backend = "_local"
    config {
        path = "../terraform.tfstate"
    }
}

provider "aws" {
    # alias = "PROD"
    region = "us-east-1"
    access_key = "${var.QA_ACCESS_KEY}"
    secret_key = "${var.QA_SECRET_KEY}"
    allowed_account_ids = ["${var.QA_ACCOUNT_ID}"]
}

provider "aws" {
    alias = "OPS"
    region = "us-east-1"
    access_key = "${var.OPS_ACCESS_KEY}"
    secret_key = "${var.OPS_SECRET_KEY}"
    allowed_account_ids = ["${terraform_remote_state.OPS.output.OPS-ACCOUNT-ID}"]
}

resource "aws_iam_group_policy" "QA-ADMIN-ASSUMEROLE" {
  provider = "aws.OPS"
  name = "qa-admin-assumerole"
  group = "${terraform_remote_state.OPS.output.OPS-ADMIN-GROUP}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": "sts:AssumeRole",
    "Resource": [
      "arn:aws:iam::${var.QA_ACCOUNT_ID}:role/${aws_iam_group.QA-ADMIN.id}"
    ]
  }]
}
EOF
}
```

**Comment by rodlogic** [comment]
I found the culprit. It is the ```allowed_account_ids``` in the ```QA``` layer. Since I am separating the accounts (i.e. ```OPS``` lives in a separate account than ```QA```) I need a second aws provider in ```QA```. In order to make sure that the access keys are in fact from the ```OPS``` layer, I added ```allowed_account_ids```.

Here is the ```aws``` resource:
```
provider "aws" {
    alias = "OPS"
    region = "us-east-1"
    access_key = "${var.OPS_ACCESS_KEY}"
    secret_key = "${var.OPS_SECRET_KEY}"
    allowed_account_ids = ["${terraform_remote_state.OPS.output.OPS-ACCOUNT-ID}"]
}
```

Now, the are no cycles between ```OPS``` and ```QA``` layers (the dependency is strictly from ```QA``` to ```OPS```), so why do I get a cycle error?

**Comment by catsby** [comment]
Hey @rodlogic – can you clarify what error you're getting now? You mention that you're not getting a cycle anymore, between OPS and QA, but there's another cycle?

**Comment by rodlogic** [comment]
The cycle is gone after I removed ```allowed_account_ids``` from my aws provider. So I am good for now.
