### ISSUE TITLE
Error rerunning terraform configuration in openstack

### ISSUE THREAD

**Issue by dddigitalglobe** [hashicorp/terraform#3770]
I'm trying to spin up similar test boxes in aws and openstack. Running the configuration against aws successive times works but in open stack a second run produces an error.

Error applying plan:

1 error(s) occurred:

* openstack_compute_instance_v2.test-server: Error removing security group from OpenStack server (9881e8cf-b2bb-48b3-ada1-31cc67cb99c1): EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by jtopjian** [comment]
Are you able to supply the Terraform configuration that is causing this error?

**Comment by dddigitalglobe** [comment]
Sure. I’ve changed the ip and the user name and password but otherwise, this is a very simple config.

Thanks,

Dave

# Configure the OpenStack Provider
provider "openstack" {
    user_name  = "XXX"
    tenant_name = "PDL"
    password  = "XXX"
    auth_url  = "http://10.52.xx.xxx:5000/v2.0"
}

# Create some Openstack Floating IP's for our VM's
#
resource "openstack_compute_floatingip_v2" "fip_1" {
    region = ""
    pool = "floatip-net1"
}
resource "openstack_compute_instance_v2" "test-server" {
  region=""
  name = "jenkins-terraform"
  image_name = "CentOS-7.0-Server-x86_64"
  key_pair = "ditstack"
  flavor_id = "3"
  network {
    uuid = "89215bc6-10b3-4991-8233-76ca83dcb609"
  }
  floating_ip = "${openstack_compute_floatingip_v2.fip_1.address}"
}

**Comment by jtopjian** [comment]
Thanks! I was able to reproduce the issue.

#3801 should fix this.

**Comment by Fodoj** [comment]
I am having the same issue in a setup with single security group and two servers referencing it. See https://github.com/hashicorp/terraform/issues/3816
