### ISSUE TITLE
Errors during renaming aws security groups

### ISSUE THREAD

**Issue by rajinders** [hashicorp/terraform#3775]
I was creating many aws security groups. I had an error where I had the same security group declared twice. I got an error telling me that security group test_nat_sg already exists.
I fixed my configuration and ran terraform apply again.

I am reporting it as it asked me to report it. If you need to view my script I can create a private repo on git hub and give you access to it.

I got the following error:
* aws_security_group.test_nat_sg: Error creating Security Group: InvalidGroup.Du
plicate: The security group 'test_nat_sg' already exists for VPC 'vpc-b7d965d3'
        status code: 400, request id: []
* aws_security_group.test_bastion_sg: diffs didn't match during apply. This is a
 bug with Terraform and should be reported.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.←[0m←[0m

**Comment by catsby** [comment]
Hey @rajinders thanks for writing in – if you have a sample config, minus any secrets, that you could share that would be great. 

I've managed to reproduce the duplicate issue by simply trying to create two security groups with the same `name` attribute, however I haven't been able to reproduce the `diffs didn't match during apply` part, so I'm curious what version of Terraform you're using and would love to see a config. 

Thanks!

**Comment by catsby** [comment]
Hello – I'm going to close this for now as we haven't heard back in a while. Please let us know if you're still having this issue
