### ISSUE TITLE
Support attaching RDS or ELB to an aws opsworks layer

### ISSUE THREAD

**Issue by wstaples** [hashicorp/terraform#3778]
Now that opsworks stacks are supported I noticed there is no way to attach an ELB or RDS instance to a layer. I searched the source code and did not see anything. Is this a missing feature or am I missing something?

**Comment by catsby** [comment]
Hello – sorry for the delay, but I recently merged this feature into `master`, and it should be available in the next release! Until then, if you'd like you an build from master and start using it now :smile:

**Comment by iroller** [comment]
@catsby thanks for adding ELB support for opswords. Is RDS in opsworks also planned?
