### ISSUE TITLE
diffs didn't match during apply for aws_ecs_service

### ISSUE THREAD

**Issue by davedash** [hashicorp/terraform#3779]
```
Error applying plan:

3 error(s) occurred:

* aws_ecs_service.REDACTED-poller-service: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* aws_ecs_service.REDACTED-poller-service: diffs didn't match during apply. This is a bug with Terraform and should be reported.
* aws_ecs_service.REDACTED-poller-service: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

This is inside a module that's being called three times (three different environments).

/cc @hahuang65

**Comment by radeksimko** [comment]
Thanks for the report, isn't this a duplicate to https://github.com/hashicorp/terraform/issues/3787#issuecomment-154725494 ? Providing a full debug log (minus any secrets) would help here.

**Comment by davedash** [comment]
@radeksimko I can't tell if it's a duplicate or not.  Can I email this to you?  I scrubbed the log, but just in case I missed something, I'd rather just limit it's exposure.

**Comment by radeksimko** [comment]
@daveadams feel free to use the email from my Github profile. If you want, you can also GPG-encrypt the message using my pubkey from https://keybase.io/radeksimko

**Comment by radeksimko** [comment]
@davedash friendly ping

It would be helpful if we knew more details behind these errors, so we can more easily figure out how to fix it.

**Comment by davedash** [comment]
Thanks for keeping this open.  I was hoping that I'd be able to reproduce
it since I did some workaround to fix it this time.  If it reoccurs I'll
recreate the issue, or reopen this if you decide to close it.

**Comment by catsby** [comment]
Thanks for the report @davedash and thanks for the triage/work @radeksimko – let's close this for now. If you can reproduce this still we'll take another look. I'm also on keybase.io, should you need to email me https://keybase.io/catsby

**Comment by davedash** [comment]
@catsby of course just after closing it does it reoccur.  Sent you an email

**Comment by davedash** [comment]
So I think it has to do with:

```
  lifecycle {
    ignore_changes =["task_definition"]
  }
```

**Comment by davedash** [comment]
Removing it seemed to be a-ok

**Comment by scalp42** [comment]
Same issue on autoscaling groups here, if you try to ignore changes for `desired` for example, you get the same error.
