### ISSUE TITLE
Add VMware vCloud Director (vcd) provider

### ISSUE THREAD

**Issue by nickithewatt** [hashicorp/terraform#3784]
Hi,

As part of some recent work done on a project, we came across the need to have a terraform VMware vCloud Director (vcd) provider. As part of this project we have developed a working version (in our setup) of such a terraform-vcd provider and are now looking to contribute it back, as well as gain further input and updates from the community on this. 

The issue tracking general vmware support https://github.com/hashicorp/terraform/issues/102, of which a vSphere implementation was contributed via https://github.com/hashicorp/terraform/pull/3419 is now closed, so creating this issue here to specifically track the new VMware vcd provider functionality (which is different from vSphere), where a PR from @devopsbrett is due very shortly :)

**Comment by phinze** [comment]
Merged - thanks!
