### ISSUE TITLE
Encryption Not Supported on ebs_block_device Within a AWS_LAUNCH_CONFIGURATION

### ISSUE THREAD

**Issue by AlJaMa** [hashicorp/terraform#3792]
While on a ebs_block_device on a AWS_INSTANCE supports the flag "encrypted", ebs_block_device under an AWS_LAUNCH_CONFIGURATION does not. 

Suggestions?

**Comment by catsby** [comment]
Hey @AlJaMa sorry for the silence here. This looks like a thing we can add support for without too much trouble, I just haven't had a chance to focus on it. We'll try to get to it soon, or hopefully a community member can pick it up.

Thanks for bringing it to our attention!

**Comment by xsmaster** [comment]
Seems that Amazon just enabled this feature on 10/22/15

https://aws.amazon.com/about-aws/whats-new/2015/10/create-auto-scaling-launch-configurations-that-include-encrypted-ebs-volumes/

**Comment by catsby** [comment]
This was added in #4481
