### ISSUE TITLE
Support S3 files in Lambda Function AWS resource

### ISSUE THREAD

**Issue by robzienert** [hashicorp/terraform#3793]
The Lambda Function resource currently only supports local zip files, but the API supports (and many workflows require) S3 files as the function code source.

I'm actively working on this, but wanted to create an issue as a placeholder in case anyone is looking for this functionality as well.

**Comment by ddub** [comment]
Awesome, just what I was looking for!

**Comment by catsby** [comment]
Just merged https://github.com/hashicorp/terraform/pull/3794 , thanks!
