### ISSUE TITLE
aws_instance security_groups when provide id throwing error

### ISSUE THREAD

**Issue by pawelsawicz** [hashicorp/terraform#3798]
Hey all

* [Working branch](https://github.com/pawelsawicz/terraform-dontstarve/)
* [Broken branch](https://github.com/pawelsawicz/terraform-dontstarve/tree/not-working-security-group-id)

According to this [documentation](https://www.terraform.io/docs/providers/aws/r/instance.html#security_groups) in security_group should be only name of security groups. But I came up with that after big confusion because when I tried to provide [ID](https://github.com/pawelsawicz/terraform-dontstarve/blob/not-working-security-group-id/vm-dontstarve.tf#L11) I got that kind of error :

![Error during applying](http://s24.postimg.org/hjtiyj2l1/Screen_Shot_2015_11_06_at_21_09_45.png)

Which in my opinion is misleading, and if it's possible it should throw a syntax error.

Another misleading is that originally I looked up [eventstore-terraform](https://github.com/Connect-Develop/eventstore-terraform/blob/dae3c4718ca0b3eda7e5f4607b6410ae93e04150/vpc-evs-node.tf#L8-L12) and here it seems working when you pass id

This issue is more about understanding and to clarify it might be helpful for other that struggling with that error/problem.

Thanks,
Pawel

**Comment by catsby** [comment]
Hey @pawelsawicz – are you creating this security group inside a default VPC? I checked out your example repos (thanks, by the way!) and I don't see a VPC declared. This leads me to believe you're inside a default VPC, which allows the `name` usage but not `id`. Is my understanding correct?

Regarding the misleading error, that's the error we're getting back from the AWS API, and is certainly not helping anyone figure out the root case here :smile: 

Regarding throwing a syntax error, I don't believe Terraform has the context to make that kind of validation here. The resource is simply receiving a value. It's valid it certain situations. That said, do you think if we attempted to capture that error [around here][1] and provide additional warning logs, that would be sufficient? Let me know if I'm missing something here, and thanks again 

[1]: https://github.com/hashicorp/terraform/blob/b-aws-ecs-cluster-read/builtin/providers/aws/resource_aws_instance.go#L359

**Comment by pawelsawicz** [comment]
Ah yes I should mention that, I don't create VPC, I am using default one. Yes your understanding is correct. Does it mean that if you define VPC then you can use `id` ?

Yes we could try to capture error, which is "Value () for parameter groupId is invalid. The value cannot be empty" and maybe modify that error a little bit to 

1. "Value () for parameter groupId is invalid. The value cannot be empty, check https://goo.gl/BwlZnp"
2. "Value () for parameter groupId is invalid. The value cannot be empty, if you use default VPC security groups have to contain names instead of id"

on the other hand I don't think so that terraform should overwrite/modify errors that AWS returns, maybe it's something that we could open a ticket at AWS to make this error message better ?
