### ISSUE TITLE
SMS SNS subscriptions require topic Display Name

### ISSUE THREAD

**Issue by coen-hyde** [hashicorp/terraform#3799]
SMS SNS subscriptions require a topic Display Name but Terraform does not allow Display Name as a option when declaring a SNS topic. See: http://docs.aws.amazon.com/sns/latest/dg/SMSMessages.html

**Comment by coen-hyde** [comment]
Closing. My mistake. It does allow display_name, the functionality just isn't documented.

**Comment by djmitche** [comment]
IMHO this should be opened -- it needs to be documented (I tried "displayname")

**Comment by coen-hyde** [comment]
Reopening.
