### ISSUE TITLE
terraform.WriteState should not increment the Serial

### ISSUE THREAD

**Issue by armon** [hashicorp/terraform#380]
Lots of code relies on WriteState just to serialize out without actually modifying things.

**Comment by mitchellh** [comment]
Lets close this out until its actually an issue.

**Comment by armon** [comment]
@mitchellh It causes remote state to upload more than necessary. Also this by-passes some of the conflict resolution logic (since no collision on serial when there should be)

**Comment by mitchellh** [comment]
Good point, I forgot about that.
