### ISSUE TITLE
Updating lambda functions.

### ISSUE THREAD

**Issue by dansowter** [hashicorp/terraform#3806]
Hello,

I'm keen to update (using the versioning feature) rather than replace lambda functions. I can see that a suitable method exists on the GO SDK, but that the update method for the lambda provider is currently a no-op.

http://docs.aws.amazon.com/sdk-for-go/api/service/lambda/Lambda.html#UpdateFunctionCode-instance_method

@cbednarski I can see you added Lambda support. Any chance you can provide me some pointers before I set off in the wrong direction?

**Comment by stack72** [comment]
Looks like #3825 fixes this - right @dansowter ?

**Comment by dansowter** [comment]
Amazing! Thanks @stack72 and @robzienert 

I'll close this now, and comment here when I've successfully used a build incorporating #3825
