### ISSUE TITLE
Chef Provisioner: ssl_verify_mode not working

### ISSUE THREAD

**Issue by kumarsarath588** [hashicorp/terraform#3807]
Hi,

I want to use ssl_verify_mode :verify_none but its not getting reflected in client.rb file of created instance. Can some one tell me what i am missing.

# Create a web server
resource "aws_instance" "web" {
    ami = "ami-52978200"
    instance_type = "t2.micro"
    tags {
        Name = "test1"
    }
    key_name = "tst"
    provisioner "chef"  {
        attributes {
                "java" {
                   "jdk_version" = 7
                   "install_flavor" = "oracle"
                   "oracle" {
                       "accept_oracle_download_terms" = true
                   }
                }
        }
        environment = "_default"
        run_list = ["java"]
        node_name = "${aws_instance.web.private_dns}"
        server_url = "https://ip-172-31-23-211.ap-southeast-1.compute.internal/organizations/test-dev"
        validation_client_name = "test-dev-validator"
        validation_key_path = "test-dev-validator.pem"
        version = "12.4.1"
        connection {
        user = "ec2-user"
        ssl_verify_mode = "verify_none"
        key_file = "/etc/ansible/309342.pem"
        }
    }
}

and client.rb file in created server is:

[root@ip-172-31-22-195 ~]# cat /etc/chef/client.rb

log_location            STDOUT
chef_server_url         "https://ip-172-31-23-211.ap-southeast-1.compute.internal/organizations/test-dev"
validation_client_name  "test-dev-validator"
node_name               "ip-172-31-22-195.ap-southeast-1.compute.internal"

**Comment by kumarsarath588** [comment]
Hi,

I did a mistake..

I used ssl_verify_mode in connection instead of provision block...
i changed it and it worked.

provisioner "chef" {
attributes {
"java" {
"jdk_version" = 7
"install_flavor" = "oracle"
"oracle" {
"accept_oracle_download_terms" = true
}
}
}
environment = "_default"
run_list = ["java"]
node_name = "${aws_instance.web.private_dns}"
server_url = "https://ip-172-31-23-211.ap-southeast-1.compute.internal/organizations/test-dev"
validation_client_name = "test-dev-validator"
validation_key_path = "test-dev-validator.pem"
version = "12.4.1"
ssl_verify_mode = "verify_none"
connection {
user = "ec2-user"
key_file = "/etc/ansible/309342.pem"
}
}

**Comment by svanharmelen** [comment]
@kumarsarath588 cool, so this issue can be closed right?

**Comment by kumarsarath588** [comment]
yes
