### ISSUE TITLE
AWS Instance Addressing not working when there is more than one instance

### ISSUE THREAD

**Issue by quater** [hashicorp/terraform#3819]
Resource Addressing [https://terraform.io/docs/internals/resource-addressing.html](https://terraform.io/docs/internals/resource-addressing.html) is not working in conjunction with `aws_eip`.

### Working with one instance

```
resource "aws_instance" "web" {
    ami = "ami-bff32ccc"
    count = "1"
    instance_type = "m1.small"
    tags {
        Name = "web"
    }
}

resource "aws_eip" "eip_web" {
    instance = "${aws_instance.web.id}"
    vpc = true
}
```

### Not working with multiple instances

```
resource "aws_instance" "web" {
    ami = "ami-bff32ccc"
    count = "2"
    instance_type = "m1.small"
    tags {
        Name = "web"
    }
}

resource "aws_eip" "eip_web" {
    instance = "${aws_instance.web[0].id}"
    vpc = true
}
```
#### Error Message
```
$ terraform plan --out deployPlan1
Error reading config for aws_eip[eip_web]: parse error: syntax error
```

**Comment by quater** [comment]
The problem is observed with

**Terraform v0.6.6**
**3.19.0-32-generic Ubuntu x86_64 GNU/Linux**

I have not tested with other versions.

**Comment by arthurschreiber** [comment]
From the documentation at https://terraform.io/docs/configuration/interpolation.html

> If the resource has a count attribute set, you can access individual attributes with a zero-based index, such as ${aws_instance.web.0.id}

Changing `instance = "${aws_instance.web[0].id}"` to `instance = "${aws_instance.web.0.id}"` should do the trick.

**Comment by mitchellh** [comment]
Correct from @arthurschreiber.

We need to improve the error output but this will come as we rewrite HIL into pure Go (rather than a YACC-generated parser).
