### ISSUE TITLE
provider/aws: support Kinesis Firehose

### ISSUE THREAD

**Issue by samuel** [hashicorp/terraform#3830]
AWS Kinesis Firehose makes it easy to stream data from Kinesis into S3 and RedShift.

Product description: https://aws.amazon.com/kinesis/firehose/
Getting started: https://aws.amazon.com/kinesis/firehose/getting-started/
API: https://docs.aws.amazon.com/firehose/latest/APIReference/Welcome.html

**Comment by stack72** [comment]
FYI I started the work on this. I will open a WIP PR now

**Comment by catsby** [comment]
#3833 was merged, closing this, thanks!
