### ISSUE TITLE
vSphere provider - question about acceptance tests

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#3836]
I know that the `resourceVSphereVirtualMachineRead` function is returned by the functions that create virtual machines. I need to test the read function specifically.  I have added a new acceptance test which is passing, but I don't believe that it should be.  The values for the new variables 'seem' to be returning from vsphere, but I don't think that they are.

How would one just test that method?

Code reference: https://github.com/chrislovecnm/terraform/blob/725a735c0d2c398bc7432a3adfbeadd76df55c4a/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L360

**Comment by jen20** [comment]
Hi @chrislovecnm! There isn't a straightforward way to unit test the CRUD methods of a provider - to do this would likely involve mocking out API endpoints. The typical approach taken here is to try to use acceptance tests to replicate the issue. I realise this probably isn't the answer you were hoping for! If you can describe what you're seeing in a bit more detail (perhaps an example) of how variables may be being set we may be able to make an alternative suggestion.

**Comment by chrislovecnm** [comment]
@jen20 we have stock acceptance tests for the vsphere provider, but I need to do more debugging.  Should I put in a request for an enhancement to the acceptance test framework to support read?  I am thinking that I am just going to write an api level test outside of terraform.

**Comment by chrislovecnm** [comment]
@tkak can you provide any wisdom?  Adding a new feature to the our read method and trying to ensure that the data is being set correctly.
