### ISSUE TITLE
allow AWS_DB_INSTANCE  final_snapshot_identifier to accept empty string as omitted.

### ISSUE THREAD

**Issue by cthomaspdx** [hashicorp/terraform#3848]
Omitting final_snapshot_identifier will result in one not being created. Passing an empty string currently results in 
`   Errors: * aws_db_instance.admin-interface: only alphanumeric characters and hyphens allowed in "final_snapshot_identifier" `

It would be great if passing final_snapshot_identifier a empty string resulted in not creating a final snapshot. 

I would like to not have to create a snapshot in my staging environments, as of now I can't find a work around.

**Comment by stack72** [comment]
@cthomaspdx This should already be the case:

```
finalSnapshot := d.Get("final_snapshot_identifier").(string)
	if finalSnapshot == "" {
		opts.SkipFinalSnapshot = aws.Bool(true)
	} else {
		opts.FinalDBSnapshotIdentifier = aws.String(finalSnapshot)
	}

```

this is currently in master. What version of TF are you using?

**Comment by cthomaspdx** [comment]
terraform -v
Terraform v0.6.6

**Comment by stack72** [comment]
@cthomaspdx Ok, I removed that last comment. It seems that the schema validates the final_snapshot_identifier as follows:

```
"final_snapshot_identifier": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				ValidateFunc: func(v interface{}, k string) (ws []string, es []error) {
					value := v.(string)
					if !regexp.MustCompile(`^[0-9A-Za-z-]+$`).MatchString(value) {
						es = append(es, fmt.Errorf(
							"only alphanumeric characters and hyphens allowed in %q", k))
					}
					if regexp.MustCompile(`--`).MatchString(value) {
						es = append(es, fmt.Errorf("%q cannot contain two consecutive hyphens", k))
					}
					if regexp.MustCompile(`-$`).MatchString(value) {
						es = append(es, fmt.Errorf("%q cannot end in a hyphen", k))
					}
					return
				},
			},
```

I am not sure if it is acceptable to bypass this validation as per the http://docs.aws.amazon.com/cli/latest/reference/rds/delete-db-instance.html. I guess that `skip_final_snapshot` could be added if @phinze / @catsby / @jen20 would agree

This would effectively be able to resign that functionality

**Comment by jen20** [comment]
@cthomaspdx Thanks for bringing this up. Am I correct in assuming that the reason you'd rather use an empty string than something like `skip_final_snapshot=true` is because you're using this as part of a module which is reused across environments?

I'm not sure offhand whether there is precedent for how to approach this, but we should probably look for other resources with similar behaviour to determine this.

**Comment by cthomaspdx** [comment]
Hey guys! Great response time! I found this article https://groups.google.com/forum/m/#!msg/terraform-tool/xA3QPNX84Bg/SEeBCEt5MQAJ where they override a variable "snapshot" {default = ""}. But I am not partial to a resolution either should fix my dilemma.

**Comment by cthomaspdx** [comment]
Now that I have thought about it more. I think it may be best to add skip_final_snapshot as my final_snapshot_identifier uses a nice little interpolated string`final_snapshot_identifier = "${var.name}-${var.env}-final"` which I can't seem to set inside of the module block  or as a variable. Variables can't interpolate and module block doesn't seem have access to the variable set with in it. I may be wrong about this as it is my first week using terraform.  Also, is their any reason that both solutions can't play well?

**Comment by stack72** [comment]
I personally think that skip_final_snapshot works best as it means you can disable snapshots without having to change the identifier strings :)

**Comment by stack72** [comment]
Opened PR #3853 to see if this works
