### ISSUE TITLE
vsphere_virtual_machine.web: unexpected EOF

### ISSUE THREAD

**Issue by ryanl-ee** [hashicorp/terraform#3855]
Hi all, I'm getting the above error when running "terraform apply".

crash.log: https://gist.github.com/ryanl-ee/347df1c256cb096b59e2
vsphere.tf: https://gist.github.com/ryanl-ee/23bc048027efddb8c98e

I have been having problem after problem but finally hit a wall here. I've been using Packer to create the image but could never get that to work. I eventually manually created a VM. I had to delete its NIC because I was getting NicMismatch errors with the VM terraform creates, so I deleted the NIC from the source VM. Now I am getting the above error. Any help is appreciated!

**Comment by chrislovecnm** [comment]
Which version of the provider and govmomi are you running?  Can you run the acceptance tests?

**Comment by ryanl-ee** [comment]
```
C:\bin\terraform> terraform -v
Terraform v0.6.6
```
I don't know what specific version of each I'm using, but it is all whatever is included in the 0.6.6 binary release (I did not compile Terraform).

**Comment by chrislovecnm** [comment]
I see the bug

https://github.com/hashicorp/terraform/blob/v0.6.6/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L425

Is not checking to see if we have an ip address.  We should by then but we cannot assume.

@ryanl-ee do you have a network in vsphere that is called "VM Network"?  That label must match a network name that is defined in vsphere.  It is defined here:

https://gist.github.com/ryanl-ee/23bc048027efddb8c98e#file-vsphere-tf-L15

@ryanl-ee are you getting nics on your virtual machines?  Are the custom and reconfigure tasks running successfully on the vm's?

@jen20 you want me to put this fix in my ipv6 fix? Or separate pull request?

@tkak I am thinking we should do a 'warning' logging when we don't have a nic on the box.

**Comment by ryanl-ee** [comment]
@chrislovecnm Thanks for the help! I have tried running "terraform apply" both with and without a preexisting NIC attached. When I have no NIC, I get the EOF error. When I do have a NIC, I get this error:
```
Clone virtual machine
win2012r2-datacenter
fault.NicSettingMismatch.summary
Customizing the new Virtual Machine
VSPHERE.LOCAL\Administrator
vcsa1.int.swyro.org
11/19/2015 4:05:36 PM
11/19/2015 4:05:36 PM
11/19/2015 4:32:46 PM
```

According to VMware, that error means the number of NICs in the customization spec don't match the existing number. It doesn't matter which template I use - the error seems to only depend on the presence of a NIC. I do have a "VM Network" network which I believe was set up by 

I will pull master, compile, & test again (likely tomorrow) and let you know how far it gets into provisioning and what the failed VM looks like as I have deleted it.

**Comment by chrislovecnm** [comment]
There is a bug that has been fixed that you are hitting :) Test drive master or don't have nics on your template.  You can have them in you tf file, just not your vm template ... It has been fixed

https://github.com/hashicorp/terraform/pull/3652

FYI ipv6 is not supported yet.

**Comment by ryanl-ee** [comment]
Just as an update, I'm trying to run master but can't get it to compile locally or using the vagrant box :) I'll keep trying.

**Comment by chrislovecnm** [comment]
@ryanl-ee what version of go are you using?  What errors are you getting?

**Comment by ryanl-ee** [comment]
I was trying to follow the guide in the README.md (make dev doesn't exist as a target?) and I followed the one in BUILDING.md instead which worked.

I am now getting this error whether or not I have a NIC attached to the VM:
```
Customize virtual machine guest OS
web
A specified parameter was not correct: spec.identity
VSPHERE.LOCAL\Administrator
vcsa1.int.swyro.org
11/20/2015 2:36:54 PM
11/20/2015 2:36:54 PM
11/20/2015 2:36:54 PM
```

The VM properties are correctly modified (CPU and RAM) and it fails while customizing the VM before booting it.

**Comment by chrislovecnm** [comment]
What does the task say on the vm itself?  Can you do a debug log for me?

**Comment by ryanl-ee** [comment]
That is the task I copied from vSphere. Here's the debug log:

https://gist.github.com/ryanl-ee/470c152d6589592eb291

I regenerated my templates using VMX hardware version 11 and post-processed them directly to vSphere. The Ubuntu template works, but I have the same issue with the generated Windows Server 2012 R2 Datacenter.

**Comment by chrislovecnm** [comment]
Windows is not supported yet ;)

@tkak is that correct?

**Comment by chrislovecnm** [comment]
Is lack of windows support not documented??

**Comment by chrislovecnm** [comment]
Windows template support was a comment on the roadmap by @tkak. I will double check that it is documented, and put in a case for it.

**Comment by tkak** [comment]
@chrislovecnm Yes, sorry, current version does not support Windows template yet.

**Comment by chrislovecnm** [comment]
@tkak it is not documented.  I will get a PR with documentation update.

@ryanl-ee  Please files a bug if you would like support added.  I know it is on our todo list, but I am uncertain of timeline.

**Comment by ryanl-ee** [comment]
Thanks for the clarification and for the fix for Linux!
