### ISSUE TITLE
template_file not compatible with fields with a StateFunc

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/terraform#3864]
It seems currently (terraform 6.6) not possible to use the content of a `template_file` (or any terraform reference for that matter) in a field with a `StateFunc`.

This causes #3076 has attempted to be fixed in #3331

My gut feeling is that the StateFunc is applied too early and there is no type for the terraform reference to be processed:
https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L922

The issue mentioned above is with the policy of an S3 bucket, but it also applies to the `user_data` of a `aws_launch_configuration` (processed into a sha1 before the content of the file has been imported)

**Comment by Fodoj** [comment]
@ColinHebert this PR introduced this bug https://github.com/hashicorp/terraform/pull/2788 If you roll it back and recompile terraform then everything should be fine

**Comment by ColinHebert** [comment]
@mitchellh Can you check the PR @Fodoj mentioned above, is reverting it the way forward?

**Comment by ColinHebert** [comment]
@jen20 @mitchellh any news regarding this?

**Comment by ColinHebert** [comment]
@catsby @jen20 @radeksimko any update in this issue?

**Comment by dferrantelli** [comment]
Any update at all? I am running into this as well, and am now getting serious pressure to fix it or stop using terraform as we need to increase instances and that changes user-data

**Comment by ColinHebert** [comment]
I can't reproduce this problem anymore on my side.
