### ISSUE TITLE
vsphere additional disk datastore selection

### ISSUE THREAD

**Issue by leonkyneur** [hashicorp/terraform#3870]
I'm trying to create a machine in vsphere - so far all works however I then went to add additional disks (vmdk) to the machine and set a specific datastore to target this new disk on. 

Result was it created the new disk in the first assign disks (where template was deployed).

e.g.

```
resource "vsphere_virtual_machine" "oss-mailstore02" {
   name = "mailstore02"
   datacenter = "DSS"
   cluster = "ALT/Apps"
   disk {
      datastore = "datastore-01"
      template = "CentOS 7.1-x86_64 - Min"
   }
   disk {
       datastore = "datastore-02"
       size = 20
   }
   vcpu = 2
   time_zone = "Australia/Sydney"
   memory = 8196
   dns_servers = ["8.8.8.8","8.8.4.4"]
   dns_suffixes = ["mydomain.com"]
   domain = "mydomain.com"
   network_interface {
     label = "serverfarm"
     ip_address = "10.99.1.2"
     subnet_mask = "255.255.224.0"  
   }
}
```

The result is disk I targeted to datastore-02 is created on datastore-01, nothing is hinted in apply / plan that this will happen.

```
vsphere_virtual_machine.oss-mailstore02
cluster:                         "" => "ALT/Apps"
datacenter:                      "" => "DSS"
disk.#:                          "" => "3"
disk.0.datastore:                "" => "datastore-01"
disk.0.template:                 "" => "Templates/CentOS 7.1-x86_64 - Min"
disk.1.datastore:                "" => "datastore-02"
disk.1.size:                     "" => "20"
dns_servers.#:                   "" => "2"
dns_servers.0:                   "" => "8.8.8.8"
dns_servers.1:                   "" => "8.8.4.4"
dns_suffixes.#:                  "" => "1"
dns_suffixes.0:                  "" => "mydomain.com"
domain:                          "" => "mydomain.com"
gateway:                         "" => "203.24.100.1"
memory:                          "" => "8196"
name:                            "" => "mailstore02"
network_interface.#:             "" => "1"
network_interface.0.ip_address:  "" => "10.99.1.2"
network_interface.0.label:       "" => "serverfarm"
network_interface.0.subnet_mask: "" => "255.255.224.0"
time_zone:                       "" => "Australia/Sydney"
```

using vsphere provider from 0.6.6:
    $ terraform version
    Terraform v0.6.6

Also noted when I also just wanted to add a new disk - it destroyed the entire machine and re-created it with the disk - desired would be just to add the disk.

**Comment by jen20** [comment]
Hi @leonkyneur! I'm not terribly familiar with the underlying API for vSphere to know offhand whether the destroy and create is necessary to add a disk, though it sounds unlikely that this is the case.

The disk order here is interesting though - given the current schema, the ordering is non-deterministic as the disks are a set rather than an array or a list. In the AWS provider the root device (which sounds like the first one in this case) is called out explicitly via a separate block. It may be worth investigating whether that approach is necessary here.

I've tagged this as a bug for now though - thanks for reporting!

**Comment by chrislovecnm** [comment]
@jen20 A dev needs to look at it :)

**Comment by chrislovecnm** [comment]
@leonkyneur this should be addressed in the dev HEAD branch.  If you are able to test, please let me know.
