### ISSUE TITLE
'content' argument on google_storage_bucket_object

### ISSUE THREAD

**Issue by premist** [hashicorp/terraform#3873]
On [aws_s3_bucket_object](https://terraform.io/docs/providers/aws/r/s3_bucket_object.html#content) resource,  you can specify `content` argument for creating an object from string. However on [google_storage_bucket_object](https://terraform.io/docs/providers/google/r/storage_bucket_object.html) resource, there is a `source` argument but not `content`. Unlike **aws_s3_bucket_object**, I can't easily create an S3 object based on rendered `template_file`. 

I'm using a workaround by adding a `local-exec` provisioner on **template_file** provider that exports terraform variable to temp file. It'll be really useful if there is a `content`argument on **google_storage_bucket_object**.

**Comment by jen20** [comment]
Hi @premist! Thanks for bringing this up. I think this should be considered in the light of #3846 - we've been trying to move to specifying content for exactly this reason, and then having people make use of the `file()` interpolation in order to load a file from disk.

**Comment by lwander** [comment]
@premist, It's been added #3893

**Comment by premist** [comment]
Thank you @lwander, I'll close this issue once PR is closed!
