### ISSUE TITLE
attaching existing vpn gateway to vpc

### ISSUE THREAD

**Issue by stankeB** [hashicorp/terraform#3876]
terraform: v0.6.6
provider: aws
resource: aws_vpn_gateway

Hi guys,

today get stuck on attaching an existing vpn connection to a terraformed vpc.

Because of our company structure and size, we are not able to add new vpn connections on short term. So we are dependent on attaching existing vpn gateways to a new vpc.

I hope, i'm not the only one with this issue.

Thanks a lot for your great work!

**Comment by kwilczynski** [comment]
@stankeB you will be delighted to know, that this was resolved via #7870.

**Comment by stack72** [comment]
<3 that this can be closed! Thanks @kwilczynski
