### ISSUE TITLE
Support "description" and arbitrary meta-data on variables & outputs

### ISSUE THREAD

**Issue by mrwilby** [hashicorp/terraform#3878]
We have a collection of higher-level wrapper scripts around Terraform that we use to manage bindings of secrets/sensitive info to terraform inputs & outputs.

At the moment, for "variables" (inputs) we abuse the "description" property:

variable "secret-..." {
    description = "... special tagging/encoding syntax which our tool looks for..."
}

This works okay, as a workaround, for now. The documentation for "outputs" doesn't seem to mention the description property, however.

Anyway, in an ideal world, we'd be able to generically tag any resource with annotations that are completely ignored by terraform itself, e.g.:

variable "secret-..." {
    metadata {  // this keyword (pick a better one) and all contents are ignored by the terraform runtime!
      "key": "value",
      "embedded map": {
         "key": "value",
      }
    }
    ...
}

It would even be nice to apply this same annotation mechanism to any resource that is handled by a provisioner. 

Just a suggestion that would help with our workflows.

**Comment by apparentlymart** [comment]
This is really interesting... can you talk a little more about how your wrapper scripts work? e.g. are you parsing the Terraform config in those scripts? If so, are you doing that with Terraform's help somehow, or are you implementing that separately?

Would this feature be improved by adding a Terraform command to output (for example) a JSON serialization of all of the variables and outputs, including their descriptions and the arbitrary metadata you're describing?

**Comment by mrwilby** [comment]
hi, yes. Basically we parse the terraform DSL and hunt for our annotations (discover inputs that need binding to our secrets) and then dynamically resolve those bindings, injecting the binding value as a "-var ..." command line argument.

And yes, definitely a structured JSON document output (which emits our annotations as well) would be even better and avoid the parsing. Thanks for thinking about this!

**Comment by mitchellh** [comment]
For output descriptions we have #9678 

There is another issue for arbitrary metadata/tags on resources which we should just extend to just about anything in Terraform. I'm going to close this as a dup. Thanks!
