### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by hutchic** [hashicorp/terraform#3879]
Terraform plan crashed and in the crash notes it asked me to create an issue so here I am :)

[crash.txt](https://github.com/hashicorp/terraform/files/32906/crash.txt)

**Comment by hutchic** [comment]
re-exported my AWS credentials and now it's happier

**Comment by jen20** [comment]
HI @hutchic! Thanks for reporting the issue. Looking through your logs, a crash like that is definitely a bug. Is there a possibility you had AWS credentials in your environment for *another* AWS account which did not have any ECS clusters?

**Comment by hutchic** [comment]
That's definitely a possibility

**Comment by radeksimko** [comment]
Interesting part of the crash log:

```
2015/11/12 08:45:05 terraform-provider-aws: 2015/11/12 08:45:05 [DEBUG] Received ECS clusters: []
2015/11/12 08:45:05 terraform-provider-aws: panic: runtime error: index out of range
2015/11/12 08:45:05 terraform-provider-aws: 
2015/11/12 08:45:05 terraform-provider-aws: goroutine 47 [running]:
2015/11/12 08:45:05 terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsEcsClusterRead(0xc208063500, 0x6befe0, 0xc20806c360, 0x0, 0x0)
2015/11/12 08:45:05 terraform-provider-aws: 	/private/tmp/terraform20150812-1536-1wacuhp/terraform-0.6.3/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_ecs_cluster.go:62 +0x55f
```

I'm going to close this as this exact bug was fixed a few days ago via https://github.com/hashicorp/terraform/pull/3829 and will be part of the next release.

Thank you for the report @hutchic though.
