### ISSUE TITLE
Changing count of instances destroys all of them

### ISSUE THREAD

**Issue by Fodoj** [hashicorp/terraform#3885]
Title says it all: I _increased_ the count and _all_ of previously created instances were destroyed. Doesn't seem like an expected behavior to me.

**Comment by Fodoj** [comment]
Using `prevent_destroy` flag doesnt help neither:

```
* openstack_compute_instance_v2.my_little_server: the plan would destroy this resource, but it currently has lifecycle.prevent_destroy set to true. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or adjust the scope of the plan using the -target flag.
````

**Comment by jtopjian** [comment]
Ouch. This wouldn't be good and definitely not what should happen.

What does your TF configuration look like? I created a basic instance with a `count` attribute set to 1, then increased it to 3. The original stayed online and accessible the entire time.

**Comment by Fodoj** [comment]
I am using user_data with tempalte_file renderer. Is that related to this issue? https://groups.google.com/forum/#!topic/terraform-tool/kvaaUlT6cg4

**Comment by Fodoj** [comment]
@jtopjian https://github.com/hashicorp/terraform/issues/2627

**Comment by jtopjian** [comment]
Ah, that's quite possible. I've only had a chance to skim those two -- I'll look deeper later today.

**Comment by jtopjian** [comment]
Do you mind providing the config you're using to cause this?

Any change to `user_data` will cause the instance to recreate. My guess is that your `user_data` isn't changing for existing resources, but for some reason Terraform thinks so. I think this may be a bug outside of the OpenStack provider, but if you can provide a config, I can take a look and see if it's fixable or if there's a workaround.

**Comment by Fodoj** [comment]
It behaves exactly the same way as described in this comment https://github.com/hashicorp/terraform/issues/2627#issuecomment-150900430

**Comment by Fodoj** [comment]
It is indeed a bug with terraform. I am trying to figure what it is exactly, but basically the problem is that after increasing count hash of a string is calculated not from the _result of rendered template_ but of a string like `"${element(..., count.index)}". And then the hash of this string is always the same for _all_ elements and changing it forces recreation.

**Comment by Fodoj** [comment]
Most likely related to https://github.com/hashicorp/terraform/issues/3864

**Comment by Fodoj** [comment]
After debugging and trying to find the source of the issue for 5 hours I can confirm that destruction of all instances happens exactly same reasons as here https://github.com/hashicorp/terraform/issues/3662 and here https://github.com/hashicorp/terraform/issues/2627#issuecomment-150900430.

Seems like there is a fatal bug in the implementation of `èlement()` function that leads to it being not interpolated at all.

It happens not only for `user_data` together with `template_file`, but also for block volumes, ip addresses etc (just like in #3864 ), so the only common piece is `element()` function and `count` variable.

I tried to fix it myself, but so far I just spent lots of time learning internals of terraform. Even though I feel like I know it much (much much) better now, it's still not enough to track down the source of the bug.

I would highly appreciate any tips on how to fix it or at least to which part of the source code I should stare at and debug longer, because this bug basically destroys not only instances, but the whole range of use cases for Terraform (most important one being the generation of user data with template_file).

My current suspects are `config/interpolate_walk.go` and `config/raw_config.go` but I might be absolutely wrong with this assumption.

**Comment by jtopjian** [comment]
@Fodoj Thanks so much for digging into this. It sounds like this is a bug with core, so I'm going to label it as such.

**Comment by Fodoj** [comment]
@jtopjian so any tips on where to search for bug? I have some hours this weekend to work on this.

**Comment by Fodoj** [comment]
Fastests way to reproduce the bug:

```
variable node_count {} 

resource "template_file" "test_file" {
  filename = "test_1.yml"
  count = "${var.node_count}"
}

resource "template_file" "another_test_file" {
  filename = "test_2.yml"
  count = "${var.node_count}"
  vars {
    var1 = "${element(template_file.test_file.*.rendered, count.index)}"
  }
}
```

Increasing count by 1 leads to `template_file.another_test_file.0` destruction.

**Comment by jtopjian** [comment]
@Fodoj Off of the top of my head, I have no idea how to approach this one. If I have some time, I'll venture outside of the OpenStack provider in Terraform. At the moment, it's uncharted territory for me :smile:

**Comment by Fodoj** [comment]
Seems to be the same issue https://github.com/hashicorp/terraform/issues/3449

**Comment by Fodoj** [comment]
Rolling this https://github.com/hashicorp/terraform/pull/2788 back solves the issue, no more total destruction of previous resources. @mitchellh any idea for better fix that won't lead to this bug?

**Comment by jgross206** [comment]
+1 I am also running into this issue.  As @Fodoj suggested, rolling back #2788 and recompiling solves it (it's a 3 line change + tests) but I don't know enough about Terraform internals to know if that's the solution or just a workaround.

**Comment by Fodoj** [comment]
@jgross206 it is _not_ a sustainable solution because rolling #2788 back re-introduces the other bug, that was fixed by this PR. For now I don't have time to go even deeper into TF internals to fix both of these bugs and still using own compiled version.

I wish @mitchellh or someone else from core contributors would pay more attention to this bug, because, as I mentioned already, it leads to _a lot_ of different bugs across many _important_ use cases of terraform.

**Comment by Fodoj** [comment]
Any update on this bug?

**Comment by justinclayton** [comment]
+1. This severely limits us from using terraform to manage and mutate an existing stack in production.

**Comment by justinclayton** [comment]
Also, we should remove the `provider/openstack` label for this issue based on the fact that @Fodoj 's template example is definitely reproducible.

**Comment by jtopjian** [comment]
@phinze Thoughts?

**Comment by hingstarne** [comment]
If it matters, i could reproduce it as well

**Comment by rgabo** [comment]
The same issue triggers recreation of `aws_volume_attachment`, `aws_route53_record` resources when using `count` and `element` in a cluster of instances where a single instance is supposed to be recreated.

Aggressive `-target`-ing of resources with explicit indexes often helps in similar cases but not this time. Example in our case would be:

```
script/plan/mongodb -target='aws_volume_attachment.mongodb-data[1]' -target='aws_instance.mongodb[1]'
```

Results in:

```
-/+ aws_volume_attachment.mongodb-data.0
    device_name:  "/dev/xvdf" => "/dev/xvdf"

    force_detach: "" => "<computed>"
    instance_id:  "i-deadbeef" => "${element(aws_instance.mongodb.*.id, count.index)}" (forces new resource)
    volume_id:    "vol-shelloil" => "vol-shelloil"
```

**Comment by cleung2010** [comment]
I am also encountering this issue, more specifically with `template_file` and `count`.

**Comment by phinze** [comment]
Hey folks - sorry for the trouble here and many apologies for the delay on response. This is definitely an important core bug that I'd like to get fixed soon. There is a great summarizing write up in #4528 that walks through the shape of the problem and shows why a simple revert of #2788 won't work as a solution. This is indeed an expression of #3449, so I'm going to close this thread to consolidate the discussion over there. I'll follow up with a plan of action on that thread.

**Comment by jzampieron** [comment]
I'm still seeing this problem with v0.11.1.
