### ISSUE TITLE
Spot request for "aws_instance"

### ISSUE THREAD

**Issue by salehsedighi-ck** [hashicorp/terraform#3889]
Is there any plan to add support to "aws_instance" ?

**Comment by jen20** [comment]
Hi @salehsedighi-ck! The APIs used between spot market instances and on-demand instances is quite different, so it's implemented as a different resource, `spot_instance_request`. Is this suitable for your needs?

**Comment by salehsedighi-ck** [comment]
Is there any example to start spot instance and after that provision it file provisioner ?

**Comment by jen20** [comment]
There is no example in the documentation at the moment, but you can use provisioners in exactly the same way as for the `aws_instance` resource type - everything available to that is available to spot instances also.

**Comment by baskaran-md** [comment]
@salehsedighi-ck  - You can find `terraform-community-modules` for `aws_spot_instance_request` @ https://github.com/baskaran-md/tf_aws_spot_instance_request

**Comment by salehsedighi-ck** [comment]
thanks
