### ISSUE TITLE
Provisioner for resources spun up using launch configuration

### ISSUE THREAD

**Issue by tadanki** [hashicorp/terraform#3890]
Hi, 
I cant seem to get the remote-exec provisioner to work with the aws_launch_configuation (ALC).
I realized that the exec is going up against the ALC and not the instances spun up using it.
```javascript()
resource "aws_launch_configuration" "service-lc" {
    image_id = "${var.service_ami}"
    instance_type = "m3.xlarge"
    key_name = "${var.remote_key}"    
    security_groups = ["${aws_security_group.server-sg.id}"]
    iam_instance_profile = "${var.iam_role}"
    associate_public_ip_address = "${var.add_public_ip}"

    ephemeral_block_device {
       device_name = "/dev/xvdb"
       virtual_name = "ephemeral0"
    }
    provisioner "remote-exec" {
        connection {
            type = "ssh"
            user = "ubuntu"
            key_file = "${var.local_pem_file}"
        }
        inline = [
          "sleep 30",
          "sudo mkdir -p  /mnt/work/tomcat-access-logs/service-logs",
          "sudo chown -R ${var.app_username} /opt/service/",
        ]
    }
}
```
What is the current way to execute a remote-exec block against the instances ?
Thanks !

**Comment by tadanki** [comment]
user_data  and cloud-init to the rescue I guess...

**Comment by codepushr** [comment]
Is this still true? Can't we use file and remote-exec provisioners on launch configurations?

**Comment by mfacenet** [comment]
I'm not sure how that would work, launch configurations don't actually spin up resources but are consumed by auto scaling groups.  For that matter, the provisioner is a one time step, it won't run when new instances are spun up by autoscaling groups.  This truly falls under the guise of user-data and any internal orchestration tooling (puppet/chef/etc)

**Comment by codepushr** [comment]
@mfacenet Makes sense! Thanks for pointing that out.

**Comment by kwach** [comment]
+1

**Comment by ebertbm** [comment]
+1

**Comment by ktraister** [comment]
+1

**Comment by simplypost** [comment]
+1

**Comment by thiagolsfortunato** [comment]
+1
