### ISSUE TITLE
Add Kinesis streams as Lambda event sources

### ISSUE THREAD

**Issue by nick-nz** [hashicorp/terraform#3897]
Feature request to be able to do this in Terraform:

![aws lambda](https://cloud.githubusercontent.com/assets/1883789/11132375/79765064-89f4-11e5-99a8-57e060d9a634.png)

Instructions for doing this via the AWS CLI are in step 3.2 of the docs here: http://docs.aws.amazon.com/lambda/latest/dg/wt-kinesis-configure-kinesis.html

**Comment by mrwilby** [comment]
+1

**Comment by nick-nz** [comment]
My current workaroud is to use local-exec. eg.

```
resource "aws_lambda_function" "my-lambda" {
    .....
    provisioner "local-exec" {
      command = "aws lambda create-event-source-mapping --function-name ${self.function_name} --event-source  ${aws_kinesis_stream.kinesis-mystream.arn} --batch-size 500 --starting-position TRIM_HORIZON"
    }
}
```

**Comment by vancluever** [comment]
+1 and thanks for the workaround @nick-nz!

**Comment by vancluever** [comment]
I have submitted the above referenced issue (#4089) as the event mapping workaround here seems to not work if IAM access exists between the role and the Lambda function. It bails saying that the mapping is a duplicate, and upon inspection on the console, the mapping is there, albeit disabled with an error.

**Comment by vancluever** [comment]
Correction to the above, it might be a stale mapping due to the need for a workaround. Check out the issue for more details.

**Comment by vancluever** [comment]
Submitted PR to add `aws_lambda_event_source_mapping` (referenced back to here)

**Comment by jen20** [comment]
#4093 has now been merged, so I'll go ahead and close this issue. It will be in the 0.6.8 release of Terraform. Thanks for bringing this up @nick-nz, and implementing it @vancluever!

**Comment by nick-nz** [comment]
Awesome. Thanks @vancluever!
