### ISSUE TITLE
Can't interpolate multi resources for nested fields 

### ISSUE THREAD

**Issue by calvinfo** [hashicorp/terraform#3902]
We're attempting to create an elasticache cluster, but unfortunately the interpolation doesn't work for splats of nested fields. 

```
resource "aws_elasticache_cluster" "cache" {
  cluster_id = "api-dedupe-memcached"
  engine = "memcached"
  node_type = "cache.r3.8xlarge"
  port = 11211
  num_cache_nodes = 2
  parameter_group_name = "default.memcached1.4"
  subnet_group_name = "${aws_elasticache_subnet_group.default.name}"
  security_group_ids = ["${aws_security_group.memcached.id}"]
}

# and then elsewhere...

value = "${join(",", aws_elasticache_cluster.cache.cache_nodes.*.address)}"

```

It could be fixed [in the config/interpolation](https://github.com/hashicorp/terraform/blob/master/config/interpolate.go#L176-L192), to mark it as a multi, but that'd require changing around the field name behavior as well. Is that behavior which you're willing to support? Otherwise it might be worth changing the cache resource.

**Comment by erkolson** [comment]
I'm seeing the same issue with the `element` interpolation.

```
value = ["${elements(aws_elasticache_cluster.cache.cache_nodes.*.address, count.index}"]
```

**Comment by calvinfo** [comment]
FWIW, the workaround we ended up using was this:

```
resource "aws_elasticache_cluster" "main" {
  cluster_id = "${var.cluster_id}"
  engine = "${var.engine}"
  node_type = "${var.node_type}"
  port = "${lookup(var.port, var.engine)}"
  num_cache_nodes = "${var.node_count}"
  parameter_group_name = "default.memcached1.4"
  subnet_group_name = "${aws_elasticache_subnet_group.main.name}"
  security_group_ids = ["${aws_security_group.main.id}"]
}

resource "template_file" "hosts" {
  count = "${var.node_count}"
  template = "${file("${path.module}/template.tpl")}"

  vars {
    endpoint = "${aws_elasticache_cluster.main.configuration_endpoint}"
    count = "${format("%04d", count.index + 1)}"
  }
}

/**
 * Outputs.
 */

output "node_endpoints" { value = "${join(",", template_file.hosts.*.rendered)}" }
```

We created a module for booting up an elasticache, which gets passed a node_count. And then we create multiple `template_files` that look like this:

```
${replace("${endpoint}", "cfg", "${count}")}
```

It's admittedly hacky, since it just relies on how AWS formats their configuration endpoint and then replaces the string to find the addresses of individual nodes. But, it does work, and outputs a list of individual nodes from the module.

**Comment by erkolson** [comment]
Thanks, that is clever.  For my needs, this is dirty but will work:
```
resource "aws_route53_record" "cache_nodes" {
  count = "${var.number_o_cache_nodes}"
  name = "a-predictable-name-cache-node-${format("%04d", count.index + 1)}"
  type = "CNAME"
  records = ["${replace(replace(aws_elasticache_cluster.cache.configuration_endpoint, "cfg", format("%04d", count.index + 1)), ":11211", "")}"]
  ttl = "60"
  zone_id = "${var.my_zone}"
}
```

**Comment by svenwltr** [comment]
This issue is open for more than a year now. Any updates or plans to fix it?

**Comment by phillbaker** [comment]
Not sure if this is exactly the same underlying issue but it looks like splats for lists of nested fields _were_ working in `0.7.x`, for example:

```hcl
output "url" {
  value = "${aws_elasticache_cluster.redis.cache_nodes.*.address}"
}
```

There are quite a few references to this on github, [1](https://github.com/intercom/terraform-modules/blob/bbe3d9415599fc1dcb426a56fe380230aef6f65c/memcached/outputs.tf#L3) and [2](https://github.com/rossedman/aws-terraform-laravel/blob/9794648ee2f70bef3145166cbcbdd1db163c0f51/terraform/modules/memcached/main.tf#L49) for example.

However, at some point in `0.8.x` it looks like this has stopped working and the outputs return nothing now.
