### ISSUE TITLE
remote-exec provisioner  finishes OK if ssh connection terminates

### ISSUE THREAD

**Issue by ronpanto** [hashicorp/terraform#391]
I have a remote-exec provisioning block for an amazon instance. I ran the infrastructure and everything ended successfully and showed green. Later when I looked at the instance I saw that the script ended abruptly. The server disconnected ssh because of timeout (from the server side), but I would have expected the provisioner to fail on any connection drop.

I ran a command in an "inline" block.

**Comment by phinze** [comment]
I'm fairly certain this bug has been long fixed. If anybody can provide steps to reproduce feel free to jump in here and we can reopen.
