### ISSUE TITLE
provider/aws: Why is throughput part of a DynamoDB table GSI ID?

### ISSUE THREAD

**Issue by garrettheel** [hashicorp/terraform#3911]
Changing the throughput on a GSI is a common operation in DynamoDB and including the read/write throughput in the ID makes the plan output misleading.

Here's an example of the output after changing _only_ the throughput.

```
global_secondary_index.1009255369.hash_key:             "" => "hash_key"
global_secondary_index.1009255369.name:                 "" => "name"
global_secondary_index.1009255369.non_key_attributes.#: "0" => "1"
global_secondary_index.1009255369.non_key_attributes.0: "" => "attr"
global_secondary_index.1009255369.projection_type:      "" => "INCLUDE"
global_secondary_index.1009255369.range_key:            "" => "range_key"
global_secondary_index.1009255369.read_capacity:        "" => "100"
global_secondary_index.1009255369.write_capacity:       "" => "300"

global_secondary_index.921504464.hash_key:              "hash_key" => ""
global_secondary_index.921504464.name:                  "name" => ""
global_secondary_index.921504464.non_key_attributes.#:  "1" => "0"
global_secondary_index.921504464.non_key_attributes.0:  "attr" => ""
global_secondary_index.921504464.projection_type:       "INCLUDE" => ""
global_secondary_index.921504464.range_key:             "range_key" => ""
global_secondary_index.921504464.read_capacity:         "100" => "0"
global_secondary_index.921504464.write_capacity:        "400" => "0"
```

Is there a good reason for the ID to be calculated this way or is it something we can look at changing?

Thanks

**Comment by soulcutter** [comment]
I agree this output is misleading. It scared me off from applying a capacity change until I verified the behavior on an unimportant asset. The actual behavior "does the right thing", but I wasted my time verifying it because the plan was unclear to me.

**Comment by sp-ruben-simon** [comment]
I have the same issue, i updated only the read/write capacity but terraform shows like I changed the entire global secondary index. If applies, the behavior is as expected (only updates the read/write capacity) but it is confusing apply a plan without known what its going to happen.

**Comment by lbernail** [comment]
:+1:
Not really an issue but really misleading when reading plan

**Comment by Ninir** [comment]
Hi folks,

The way `global_secondary_indexes` are made into DynamoDB forces the diff when any of the `global_secondary_indexes` options changes. 
As of now, even if the diff may be huge, it is only recalculating the hash, based on the whole `global_secondary_indexes` definition.

We'll try to figure out a way to better handle such UX.

Thanks!
