### ISSUE TITLE
"No ingress rules ..." warning causes Terraform to fail unnecessarily.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#3918]
I'm not able to reproduce this reliably, but occasionally on initial `terraform apply` runs or subsequent ones that are performing updates, Terraform will exit with the error below. A subsequent run completes successfully.

```
...
Error applying plan:

1 error(s) occurred:

* aws_security_group_rule.nat: [WARN] No ingress rules were found for Security Group (nat) looking for Security Group Rule (sgrule-3747846238)
...
```
_Full log output of an update failing is [here](https://gist.github.com/clstokes/07ad4202a3fa6c627df4)._

I believe this is an internal warning in Terraform; not an actual error messages being returned from AWS. My guess is this is due some eventual consistency timing issues in the AWS API responses and that this warning could either be ignored or retried until successful (or `tries > N`) rather than failing the run.

This is occurring with **Terraform v0.6.6** and can be reproduced (again, only occasionally) with the configuration at [hashicorp/atlas-examples](https://github.com/hashicorp/atlas-examples/tree/master/consul-cluster/aws-intermediate-consul-cluster/terraform).

**Comment by clstokes** [comment]
I found https://github.com/hashicorp/terraform/issues/3691 which mentions this warning, but believe the focus of it is the _DependencyViolation_ error as opposed to this warning, so wanted to document this separately.

**Comment by catsby** [comment]
Hey @clstokes  I think we fixed this in https://github.com/hashicorp/terraform/pull/3965
