### ISSUE TITLE
builtin vsphere provider missing concept of "vm_folder"

### ISSUE THREAD

**Issue by matt-deboer** [hashicorp/terraform#3921]
It seems that the vsphere provider does not account for the vsphere concept of vm folder, and thus, all machines are created at the root level.

Attempts to include path information in the name (similarly to how the template is described) results in vms created at the root level with slashes in the name.

This is occurring on esxi 5.5, terraform 0.6.6

On a side note, it appears that the alternate provider from **mkuzmin/terraform-vsphere** seems to account for this concept as a separate parameter using the same govmomi library.

**Comment by chrislovecnm** [comment]
@matt-deboer can we close this??

**Comment by matt-deboer** [comment]
Yeah, we're good.
