### ISSUE TITLE
Ability to use AMI name as well as ID for AWS instances

### ISSUE THREAD

**Issue by nickithewatt** [hashicorp/terraform#3923]
When creating a new instance within AWS, the AMI referenced (via the `ami` field is specifically to the ID to be used i.e.
```
# Create a new instance of the ami-1234 on an m1.small node
resource "aws_instance" "web" {
    ami = "ami-1234"
    instance_type = "m1.small"
}
```

We are currently uploading / creating our own custom AMIs, which have been given more human friendly logical names. It would be nice to be able to reference this AMI by name instead of just the ID, perhaps an option to have an `ami_name` as an alternative to the current `ami` field which honours just the AMI ID? i.e.

```
# Create a new instance using the AMI with name my-logical-ami-name-v1 and 
# backed by ID ami-1234 on an m1.small node
resource "aws_instance" "web" {
    ami_name = "my-logical-ami-name-v1"
    instance_type = "m1.small"
}
```

**Comment by stack72** [comment]
@nickithewatt what would you expect to be able to input for this? Would it be the ami_name always or would you want to be able to select the ami based on tag?

If it is *always* the ami_name then this can be done easily

**Comment by nickithewatt** [comment]
@stack72 For our use case we would simply need to specify the ami_name, no need for tags at this stage :)

**Comment by stack72** [comment]
Thanks @nickithewatt - I am just working on a PR for this now :)

**Comment by stack72** [comment]
@nickithewatt so the functionality I proposed in #3935 allows you to do as follows:

```
resource "aws_security_group" "tf_test_foo" {
	name = "tf_test_foo"
	description = "foo"

	ingress {
		protocol = "icmp"
		from_port = -1
		to_port = -1
		cidr_blocks = ["0.0.0.0/0"]
	}
}

resource "aws_instance" "foo" {
    ami_name = "BOSH-04e04008-85a5-4f5d-9f37-5eda69f57f81"
    instance_type = "m1.small"
    availability_zone = "us-west-2a"
    security_groups = ["${aws_security_group.tf_test_foo.name}"]
}
```

This will use the Describe-Images API to get the correct AMI Id for that image

**Comment by catsby** [comment]
Hey all – the problem I see with this (and noted in #3935) is that without the ID in the configuration, Terraform won't know to make any changes to your infrastructure if the ID changes. Terraform will impose your configuration on your infrastructure; if the AMI name is still the same, no action regarding the ID will be taken; it will simply make note (store in state file) that the ID changed. 

Does this make sense? Am I missing something that could make this work?

**Comment by stack72** [comment]
So I have been giving this great thought and I am actually doing the same style of functionality you are asking for, but in a slightly different way:

in main.tf, I have the following:
```
module "base_ami" {
  source = "github.com/DreamItGetIT/tf_digit_base_amis"
  region = "${var.aws_region}
}
```

In a nutshell, this script goes to AWS and grabs the latest of my AMI's (using tags) and get's it's AMI. It produces an output similar to as follows:

```

  "variable": {
    "digit_base_ami_id": {
      "description": "The DIGIT base ami",
      "default": {
        "eu-west-1": "ami-19734d6e",
        "us-west-2": "ami-cf6c79ff"
      }
    }
  }
}
```

Then, in my instance declaration, I do as follows:

```
resource "aws_instance" "jenkins_slave_instance" {
  ami = "${module.base_ami.base_ami_id}"
  instance_type = "m3.medium"
  iam_instance_profile = "app-server"
  key_name = "digit-terraform"
  associate_public_ip_address = "false"
}
```

I top this off with a makefile that sits in the root of my repo. 

```
default: .tf-update .tf-clean .vars-generate

.tf-clean:
	for i in $$(ls .terraform/modules/); do make clean -C ".terraform/modules/$$i"; done

.vars-generate:
	for i in $$(ls .terraform/modules/); do make -C ".terraform/modules/$$i"; done

.tf-update:
	terraform get -update=true

```

Therefore, running the command `make`, means my terraform scripts go off and get the latest AMI ID before any terraform plans / apply's are run

I suggest that this style of approach will help

**Comment by nickithewatt** [comment]
@catsby @stack72 For this use case, we never intend to actually change the name of the AMI, rather just want to use it as an alias to refer to the underlying AMI. If for whatever reason the name of the AMI lands up referring to a different AMI ID, it would be reasonable to expect the associated resource to register a change and need to be rebuilt. However as you say, as the name itself has not changed, terraform would not necessarily register a change.

We can certainly work around this, however was thinking that something like the consul example (noted below)

```
# Access a key in Consul
resource "consul_keys" "app" {
    key {
        name = "ami"
        path = "service/app/launch_ami"
        default = "ami-1234"
    }
}

# Use our variable from Consul
resource "aws_instance" "app" {
    ami = "${consul_keys.app.var.ami}"
}
```
with a bit of @stack72's approach thrown in might be an option, but not sure if this is fully feasible or not. It would require a an aws_ami_lookup type resource which would always need to make a lookup call before being used as input anywhere else, i.e.

```
# Lookup AMI ID in AWS
resource "aws_ami_lookup" "base_ami" {
  ami_name = "my-logical-ami-name-v1"
  region = "eu-west-1"
}

# Use our variable from AWS Lookup
resource "aws_instance" "app" {
    ami = "${aws_ami_lookup.base_ami.id}"
}
```

**Comment by nickithewatt** [comment]
Also just wanted to say thanks @stack72 for jumping on this so soon whatever the outcome!

**Comment by stack72** [comment]
Hi @nickithewatt 

Now that we have data_sources in place for AMIs, I am going to go ahead and close this. 

https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/aws/d/ami.html.markdown

You can now declare a datasource for the ami and pass the id into the instance - much like the consul example

Paul

**Comment by nickithewatt** [comment]
Thanks @stack72 !
