### ISSUE TITLE
Output in resource file is broken 

### ISSUE THREAD

**Issue by saswatp** [hashicorp/terraform#3932]
I have a module "aws-dc" that sources a resource file. Resource file has a output like the following : 

output "control_ips" {
  value = "${join(\",\", aws_instance.mi-control-nodes.*.private_ip)}"
}

root module output refers the output of the module aws-dc 

output "control_ips" {
  value = "${module.aws-dc.control_ips}"
}

When I do terraform plan or apply , I get the following error 

Error downloading modules: module aws-dc: Error loading .terraform/modules/594ef152745435b924453a45684a1fb0/aws.tf: Error reading config for output control_ips: parse error: syntax error

The same code works fine with an older version with no syntax error.

**Comment by jen20** [comment]
Hi @saswatp! That output working with previous versions was an accident of the old HCL parser - with newer versions you need to remove the quoting on the `"` inside the interpolated string - so your output should read:

```hcl
output "control_ips" {
    value = "${join(",", aws_instance.mi-control-nodes.*.private_ip)}"
}
```

**Comment by saswatp** [comment]
Thanks , removing the "\" works. Looks to be a non-issue then .
