### ISSUE TITLE
Changing root volume size does not register as a change.

### ISSUE THREAD

**Issue by CorbanR** [hashicorp/terraform#3941]
OS: Ubuntu 15.10
Terraform v0.6.6

I create an instance with the following configuration 

```
resource "aws_instance" "app1" {
  instance_type     = "m3.xlarge"
  ami               = "${var.trusty-ami}"
  security_groups   = ["${aws_security_group.ap.id}"]
  subnet_id = "${element(split(",",module.metadata.region_public_subnets), 0)}"
  user_data         = "${template_file.cloudinit.rendered}"
  associate_public_ip_address = "true"
  key_name          = "${var.key-name}"
  tags {
    Name        = "blah"
  }
}
```

The above configuration created an instance with an 8gig root volume.
After the instance was created I updated the configuration to 

```
resource "aws_instance" "app1" {
  instance_type     = "m3.xlarge"
  ami               = "${var.trusty-ami}"
  security_groups   = ["${aws_security_group.app.id}"]
  subnet_id = "${element(split(",",module.metadata.region_public_subnets), 0)}"
  user_data         = "${template_file.cloudinit.rendered}"
  associate_public_ip_address = "true"
  key_name          = "${var.key-name}"
  tags {
    Name        = "blah"
  }
  root_block_device {
    volume_type = "gp2"
    volume_size = "16"
  }
}
```

I then ran `terraform plan` and `terraform apply` and terraform did NOT register any changes. I would have expected terraform to require a new instance. Is this expected behavior?

**Comment by robertfirek** [comment]
OS: Mac
Terraform v0.6.11

I've noticed that changing any parameter of block devices doesn't trigger any changes in plan. According to plan nothing has been changed.

**Comment by fazy** [comment]
Seeing the same issue:

```
    ebs_block_device {
        device_name = "/dev/xvdb"
        volume_type = "gp2"
        volume_size = "${var.app_volume_size}"
    }
```

I changed the value of `var.app_volume_size` and no change was registered.

Worked around by commenting out the volume, applying, uncommenting and then applying again.

**Comment by Qilinee** [comment]
Also seeing this 
Terraform v0.6.11
Linux version 4.1.10-17.31.amzn1.x86_64 

`resource "aws_instance" "ec2_instance" {
    ami = "${var.instmod_ami_id}"
    count = "${var.instmod_number_of_instances}"
    subnet_id = "${var.instmod_subnet_id}"
    instance_type = "${var.instmod_instance_type}"
    user_data = "${file(var.instmod_user_data)}"
    vpc_security_group_ids = [ "${var.instmod_vpc_security_group_ids}" ]
    key_name = "${var.instmod_key_name}"
    root_block_device {
      volume_size = "10"
    }
    tags {
        Name                 = "${var.instmod_instance_name}-${count.index}"
    }
}
`

The server will spin with its initial 10 however changing the number gives nothing, commenting out, get/plan/apply and re-adding in the root_block_device (and another get/plan/apply) code block makes no change it seems for the root device.

**Comment by jonhatalla** [comment]
With Terraform 0.6.13 also seeing this.  

Using `taint` to recreate the instance

**Comment by mengesb** [comment]
Does this issue persist with terraform v0.7.5 ?

**Comment by Jwpe** [comment]
Seeing this behaviour with Terraform v0.7.6 @mengesb

**Comment by Hashfyre** [comment]
Seeing this behavior in Terraform v0.7.10 too.

**Comment by rafaelfc-olx** [comment]
Seeing this behavior in Terraform 0.8.4 too.
