### ISSUE TITLE
Encourage use of version instead of build for Atlas Artifacts

### ISSUE THREAD

**Issue by pearkes** [hashicorp/terraform#3944]
Currently we [document build number](https://terraform.io/docs/providers/atlas/r/artifact.html#build) as a specifier alongside version number for accessing artifacts in Atlas.

Because Atlas acts as an artifact registry, but may not always be building said artifacts, it's generally less sound to rely on the build number as an identifier. It has UIs for viewing versions and version numbers, and enforces their presence. Build numbers are not strictly validated in the same way.

I'd recommend updating the documentation to point this out, and possible deprecate build numbers altogether. We won't be eliminating this filter from Atlas anytime soon to preserve backwards compatibility, but would want to encourage best practices going forward.

**Comment by teamterraform** [comment]
The feature this issue related to is no longer present, so we're going to close this out now.
