### ISSUE TITLE
`terraform version` hangs when piping to `head`

### ISSUE THREAD

**Issue by kvz** [hashicorp/terraform#3949]
This is on version 0.6.3 when typing

```
$ ./bin/terraform/terraform version |head -n1
```

Nothing happens after this:

<img width="526" alt="screen shot 2015-11-17 at 11 07 05" src="https://cloud.githubusercontent.com/assets/26752/11208445/7cb6c2b6-8d1b-11e5-8262-b62628c84075.png">

When using without `head` it says:

```bash
$ ./bin/terraform/terraform version
Terraform v0.6.3

Your version of Terraform is out of date! The latest version
is 0.6.6. You can update by downloading from www.terraform.io
```

After upgrading to 0.6.6, it no longer hangs. That's good, but the hang might be triggered by the update warning, and resurface when there's an update to 0.6.6? Something to double-check maybe.

**Comment by jen20** [comment]
Hi @kvz! Thanks for opening this. I can reproduce it on Mac OS X using Terraform 0.6.3. I've marked it down as a "core" bug, and will investigate it at some point in the future. I suspect you are right about the update check causing this.

**Comment by apparentlymart** [comment]
I think we have an open bug for this somewhere already where I dug into it a bit but I can't seem to find it now... :(

**Comment by apparentlymart** [comment]
Okay, I found it eventually: #3523

**Comment by osterman** [comment]
My workaround is to run `nohup terraform -v | head -1` which fools it into thinking there's no attached tty.

**Comment by apparentlymart** [comment]
Let's consolidate this into #3523, since it seems to be the same thing.
