### ISSUE TITLE
Cloning a vm using vsphere provider takes an hour

### ISSUE THREAD

**Issue by kc11381** [hashicorp/terraform#3952]
Hi,

Cloning a vm using vsphere provider takes an hour or more. 
Is it a known issue with the provider? Do we need to specify any parameters here?

**Comment by chrislovecnm** [comment]
Need more information from you to help diagnose.  What is your tf file?  Can you run the acceptance tests?

**Comment by chrislovecnm** [comment]
@kc11381 any more information? Or please close the bug.

**Comment by kc11381** [comment]
Hi Chris,

Sorry for late reply. 
Actually the reason for cloning process taking an hour was due to thik provisioning. I changed the code to Thin provisioning and it takes around 2 mins now.
Thanks for looking into it. I will close it now.

**Comment by chrislovecnm** [comment]
Out of curiousity @kc11381 which did you change?

**Comment by kc11381** [comment]
Hi Chris,

Inside the function:  func createVMRelocateSpec
I changed 
ThinProvisioned: types.NewBool(true), and
EagerlyScrub:    types.NewBool(false),

Thats the only change I did for my use case.
