### ISSUE TITLE
vSphere provider ipv6 support

### ISSUE THREAD

**Issue by chrislovecnm** [hashicorp/terraform#3957]
Two things need to be done.   

* Update the documentation that ipv6 is not supported at this time. 
* https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L384 needs to be updated with ipv6 support.

@tkak if you can point me in the right direction I have an environment up that can test it.  I am a bit lost in ipv6 and golang land :)

Outlined my lack of knowledge here: http://stackoverflow.com/questions/33769800/getting-ipv6-subnet-mask-from-net-cidrmask

@jen20 might you add 'bug' 'enhancement' and correct provider labels?  This is a bug because the provider assumes ipv4, and it goes boom with ipv6 addresses.

**Comment by chrislovecnm** [comment]
https://github.com/hashicorp/terraform/pull/3959 submitted to update docs, till this is fixed.

**Comment by chrislovecnm** [comment]
@jen20 thanks

Docs are updated, at a min we need to test for ipv6 ip address and fail.

**Comment by chrislovecnm** [comment]
Here is design for the fix:

Current code: 
    // string of ip address
    networkInterface["ip_address"] = v.IpAddress[0]
    m := net.CIDRMask(v.IpConfig.IpAddress[0].PrefixLength, 32)
    subnetMask := net.IPv4(m[0], m[1], m[2], m[3])
    networkInterface["subnet_mask"] = subnetMask.String()

design code:
    if v.IpAddress[0] != nil {
        networkInterface["ip_address"] = v.IpAddress[0]
        testip := net.ParseIP(v.IpAddress[0])
        subnetMask := nil
        if testInput.To4() != nil {
          if v.IpConfig.IpAddress[0].PrefixLength != nil {
              mask := net.CIDRMask(v.IpConfig.IpAddress[0].PrefixLength, 32)
              subnetMask := net.IPv4(m[0], m[1], m[2], m[3])
              networkInterface["subnet_mask"] = subnetMask.String()
          }
        } else if testInput.To16() != nil {
          if v.IpConfig.IpAddress[0].PrefixLength != nil {
              mask := net.CIDRMask(v.IpConfig.IpAddress[0].PrefixLength, 128)
              // TODO figure this out
              // net.mask?? func (ip IP) Mask(mask IPMask) IP
              // subnetMask := net.IP()
              networkInterface["subnet_mask"] = subnetMask.String()
          } 
       }
}

This is what is comming back from the api:

$ govc vm.info -json vcsa | jq .VirtualMachines[0].Guest.Net[0].IpConfig.IpAddress [   {
    "IpAddress": "10.20.128.218",
    "PrefixLength": 22,
    "Origin": "",
    "State": "preferred",
    "Lifetime": null   } ]

**Comment by tkak** [comment]
@chrislovecnm Thank you for investigation. That design code looks good to me. 

Anyway, I'm thinking about that we sould change `subnet_mask` parameter to `prefix_length` in order to meet the specification of VMware vSphere API. Because `subnet_mask` paremeter is long to input in case of IPv6. What do you think of this idea?

**Comment by chrislovecnm** [comment]
@tkak that makes more sense to me frankly, and is less code.  Less code is always better :grinning: 

Do we ever need to send the subnet mask, or does the api alway take the prefix length?

**Comment by tkak** [comment]
@chrislovecnm I tried to make a proposal PR to support ipv6 address. Can you check that?
