### ISSUE TITLE
provider/openstack: Add Trove / DBaaS Support

### ISSUE THREAD

**Issue by jtopjian** [hashicorp/terraform#3958]
I recently noticed that Gophercloud added support for [Trove/DBaaS](http://docs.openstack.org/developer/trove/):

https://github.com/rackspace/gophercloud/tree/master/openstack/db/v1

It should be possible to create the relevant resources in Terraform.

**Comment by stack72** [comment]
@jtopjian is this still something you think needs added? Or can we close this out?

**Comment by jtopjian** [comment]
Yeah, I think we can close this out. There's a long list of other more wanted features ahead of this.

**Comment by tomasquith** [comment]
+1

**Comment by ronaldtse** [comment]
Very happy to report that this feature is now implemented in the openstack provider as a contribution from [Ribose Inc.](https://github.com/riboseinc):

https://github.com/terraform-providers/terraform-provider-openstack/pull/169

A big thank you to @eugenetaranov and @jtopjian!
