### ISSUE TITLE
v0.6.7 Release Process

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#3964]
v0.6.7 Release Process

cc @hashicorp/terraform-committers

We’re beginning the Release Process for Terraform v0.6.7. Part of this process is validating the `master` branch passes all of our current unit and acceptance tests. To better facilitate this, we’re temporarily suspending commit privilege for our team of core-committers. We’ll re-enable this as soon as the process concludes and v0.6.7 is out. 

The [CHANGELOG][1] documents the changes that will be going out (0.6.7 Unreleased). 

Core committers can highlight @catsby / @phinze / @jen20 for anything they feel needs immediate attention, otherwise we’re proceeding with minimal changes to the `master` branch as is.

Thanks!

[1]: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md

**Comment by svanharmelen** [comment]
@catsby  @phinze @jen20 I believe there is a bug in the new HCL related code... Hold on while I get you some more details...

**Comment by svanharmelen** [comment]
Yes, I can confirm there is a bug when you feed JSON configs to Terraform. You can test yourself by using the following config:

```json
{
    "provider": {
        "cloudstack": {
            "api_url": "bla",
            "api_key": "bla",
            "secret_key": "bla"
        }
    },
    "resource": {
        "cloudstack_firewall": {
            "test": {
                "ipaddress": "192.168.0.1",
                "rule": [
                    {
                        "source_cidr": "10.0.0.0/8",
                        "protocol": "tcp",
                        "ports": [
                            "80",
                            "1000-2000"
                        ]
                    }
                ]
            }
        }
    }
}
```

Which will result in this output:

![image](https://cloud.githubusercontent.com/assets/4171547/11248809/7850e428-8e23-11e5-8b11-c08955c7241c.png)

While if I run this (the HCL equivalent) it runs without any errors:

```json
provider "cloudstack" {
  api_url = "bla"
  api_key = "bla"
  secret_key = "bla"
}

resource "cloudstack_firewall" "test" {
  ipaddress = "192.168.0.1"
  rule {
    source_cidr = "10.0.0.0/8"
    protocol = "tcp"
    ports = ["80", "1000-2000"]
  }
}
```

I need to go home now, but can try to fix/troubleshoot this after dinner later tonight if needed...

**Comment by mitchellh** [comment]
@svanharmelen Nice. Thanks for finding this. Let's turn this into a failing test (we can do it) and get it fixed prior to release.

**Comment by mitchellh** [comment]
@catsby Let's keep this open until we do the release! :)

**Comment by svanharmelen** [comment]
@mitchellh @catsby I just fixed the problem, but need to go to a (nasty) dentist appointment right now. Will put in a PR when I get back (within a few hours that is)...

**Comment by jen20** [comment]
@svanharmelen I just added tests reproducing the issue on this branch: https://github.com/hashicorp/terraform/tree/b-json-hcl

**Comment by svanharmelen** [comment]
@jen20 yeah just notice the commit coming in :+1: Good to have this test in so we can verify the PR with the fix in Terraform as well.

The root cause was actually in the new/updated HCL code, so my PR will be on the HCL repo (with it's own test in the PR). But still a good thing to cover this issue here as well!

Be back in a few...

**Comment by svanharmelen** [comment]
The PR to fix this is in: https://github.com/hashicorp/hcl/pull/61

**Comment by svanharmelen** [comment]
Seems there is still an issue with the new HCL code and JSON, as reported by @pikeas:  https://github.com/hashicorp/terraform/issues/3988

Will have a look first thing tomorrow morning. We have some services talking (pretty complex) JSON to TF, so will run some additional tests with those tomorrow as well to make sure there are no other issues after fixing this new one.

**Comment by phinze** [comment]
Thanks for the heads up @svanharmelen. We'll make sure that gets addressed before release. :+1:

**Comment by svanharmelen** [comment]
Have a fix, fixing up the PR as we speak...

**Comment by svanharmelen** [comment]
@phinze https://github.com/hashicorp/hcl/pull/64 fixes the issue raised in #3988 

Unfortunately I don't have time today to do some brute force testing against master in order to see if we have missed more/other use cases with the new HCL code in combination with JSON configs.

I think it's still wise to first do this, but I leave that decision with you guys. I will do these tests Monday morning so you'll have the results/feedback when your Monday morning begins :wink:

**Comment by phinze** [comment]
Thanks @svanharmelen! Agreed on more JSON testing. I'll see what I can put together today, but we're likely looking at holding the release for Monday anyways, so you'll get your chance to do your thing as well. :grinning:

**Comment by svanharmelen** [comment]
:+1:

**Comment by svanharmelen** [comment]
@phinze just got around to testing some configs and as far as I can tell we are goid to go :smiley:

**Comment by radeksimko** [comment]
I wanted to avoid merging changes at this time before release, there's just one I merged - https://github.com/hashicorp/terraform/pull/4010

This was to avoid breaking changes after the release. Full explanation inside the PR. Hopefully it won't cause any troubles - I double checked the code & tests.

**Comment by phinze** [comment]
Sounds good, @radeksimko, looks like a good call to me. :+1:

**Comment by catsby** [comment]
v0.6.7 was released! Thank you all who contributed :smile:
