### ISSUE TITLE
terraform refresh of AES domain fails with RecordNotFoundException - stuck

### ISSUE THREAD

**Issue by gmorpheme** [hashicorp/terraform#3967]
After having been experimenting with AES and terraform I've ended up in a situation where I can't plan, apply or destroy:

```shell
greg$ terraform plan -destroy -target=aws_elasticsearch_domain.curvelogic_es
Refreshing Terraform state prior to plan...

aws_elasticsearch_domain.curvelogic_es: Refreshing state... (ID: arn:aws:es:eu-west-1:xxxxxxxxxxx:domain/curvelogic-es)
Error refreshing state: 1 error(s) occurred:

* aws_elasticsearch_domain.curvelogic_es: ResourceNotFoundException: Domain not found: curvelogic-es
	status code: 409, request id: 6e4b2371-8e1a-11e5-bd07-7741b705d65c
```

The resource doesn't exist in my account. It does exist in my tfstate:

```json
                "aws_elasticsearch_domain.curvelogic_es": {
                    "type": "aws_elasticsearch_domain",
                    "primary": null,
                    "tainted": [
                        {
                            "id": "arn:aws:es:eu-west-1:xxxxxxxxxx:domain/curvelogic-es",
                            "attributes": {
                                "access_policies": "{\"Statement\":[{\"Action\":[\"es:*\"],\"Effect\":\"Allow\",\"Principal\":{\"AWS\":[\"xxxxxxxxxx\"]},\"Resource\":\"arn:aws:es:eu-west-1:xxxxxxxxxx:domain/curvelogic-es/*\"}],\"Version\":\"2012-10-17\"}",
                                "advanced_options.#": "1",
                                "advanced_options.rest.action.multi.allow_explicit_index": "",
                                "cluster_config.#": "1",
                                "cluster_config.0.dedicated_master_count": "0",
                                "cluster_config.0.dedicated_master_enabled": "false",
                                "cluster_config.0.dedicated_master_type": "",
                                "cluster_config.0.instance_count": "3",
                                "cluster_config.0.instance_type": "t2.micro.elasticsearch",
                                "cluster_config.0.zone_awareness_enabled": "true",
                                "domain_name": "curvelogic-es",
                                "ebs_options.#": "1",
                                "ebs_options.0.ebs_enabled": "true",
                                "ebs_options.0.iops": "0",
                                "ebs_options.0.volume_size": "20",
                                "ebs_options.0.volume_type": "gp2",
                                "id": "arn:aws:es:eu-west-1:xxxxxxxxxxx:domain/curvelogic-es",
                                "snapshot_options.#": "1",
                                "snapshot_options.0.automated_snapshot_start_hour": "23"
                            }
                        }
                    ]
                },
```

I tainted it at some point trying to fix this. The problem originated during a brief network outage when an apply failed.

Suggestion of my colleague @BSick7 is that this is an exception that should be understood by the provider. https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_elasticsearch_domain.go#L236-L278

**Comment by steve-jansen** [comment]
Not sure if this applies here... AWS ElasticSearch domains seem to need several minutes to commit changes.  Perhaps the last AWS API action to create the domain had not completed yet when you asked to destroy it?

**Comment by rbdixon** [comment]
This is a bug. Same behavior here. You can test it by creating a AES domain using terraform, deleting it in the console, and then waiting until it is all the way shut down. Run `terraform apply` and you'll see this error. I had to implement the same workaround.

**Comment by abevoelker** [comment]
I hate to effectively just "+1" an issue, but I also ran into this when I moved my elasticsearch.tf configuration into its own separate module. The simplest fix for me, since I was working in a test environment, was to create the ES domain Terraform was expecting in the AWS console then destroy+apply it from Terraform.

**Comment by osterman** [comment]
Encountering this as well. 

![image](https://cloud.githubusercontent.com/assets/52489/15296311/bce7b19e-1b49-11e6-9faf-70a46feffb8b.png)

**Comment by stack72** [comment]
Hi Terraformers, I have just opened PR #8643 that fixes this

Sorry it has taken so long to get to! It will be part of the 0.7.3 release

Paul
