### ISSUE TITLE
Feature request: support for Amazon Elastic Transcoder

### ISSUE THREAD

**Issue by farridav** [hashicorp/terraform#3968]
I would love to see support for [Amazon Elastic Transcoder](https://aws.amazon.com/elastictranscoder/)...

Specifically creating/editing pipelines and presets [API docs here](http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/api-reference.html)

I'm not quite proficient enough (at all) with `go` to tackle this feature, but if there's more info/assistance i can give, please shout..

I have nearly all of my resources managed by Terraform now, this addition would really help to bring the remaining bits in..

Keep up the good work :+1:

**Comment by antonbabenko** [comment]
Please make sure that you put your name on spreadsheet mentioned in #28

**Comment by farridav** [comment]
done! thanks

**Comment by donaldguy** [comment]
I have beginnings of a branch over here: https://github.com/donaldguy/terraform/tree/aws_elastictranscoder_pipeline

I will hopefully get through more of it today; I have to deal with the nested structures still.

**Comment by kkacsh321** [comment]
+1 would love to see Elastic Transcoder supported

**Comment by jbardin** [comment]
We will have Elastic Transcoder support in the next release.
Sorry, this should have been linked to PR #6965 and closed.
