### ISSUE TITLE
Terraform "aws_spot_instance_request" to support "block-duration-minutes"

### ISSUE THREAD

**Issue by baskaran-md** [hashicorp/terraform#3969]
Amazon introduced "block-duration-minutes" to block spot instance for specific time duration, for which the instances is guaranteed to be up. Terraform need to support this param.

Expected Param on terraform [aws_spot_instance_request](https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html#spot_instance_id):
`block_duration_minutes` - Optional. It will take value in minutes for any finite duration from 1 to 6 hours.

More details @ [new-ec2-spot-blocks-for-defined-duration-workloads](https://aws.amazon.com/blogs/aws/new-ec2-spot-blocks-for-defined-duration-workloads/)

**Comment by stack72** [comment]
@baskaran-md what do you think is the intended behaviour for Terraform after this duration has passed? If the instance get's destroyed, then then next terraform plan / apply will show there are changes pending

Thoughts?

**Comment by stack72** [comment]
@baskaran-md I believe I have added the expected behaviour as part of #4074

**Comment by baskaran-md** [comment]
@stack72 I think you are right. After the expiration time, the next terraform plan / apply should show these as addition of new nodes.
