### ISSUE TITLE
Add support for configuring Docker logging drivers

### ISSUE THREAD

**Issue by jantman** [hashicorp/terraform#3972]
Docker 1.6 introduced support for configurable [logging drivers](https://docs.docker.com/v1.8/reference/logging/overview/) that can take a container's STDOUT and STDERR and send them somewhere other than a file on disk - i.e. syslog, a GELF endpoint, fluentd, or journald. This can be configured per-container using the `--log-driver` and `--log-opt` options to `docker run`. This is a massive step forward in management of logging from containers. It would be very helpful if terraform supported these.

**Comment by mkuzmin** [comment]
Related PR: https://github.com/hashicorp/terraform/pull/3761

**Comment by danielbcorreia** [comment]
Hey guys, I belive this was already solved, according to your docs:

https://www.terraform.io/docs/providers/docker/r/container.html

You may want to close this issue :)
