### ISSUE TITLE
Dynamic values for variable

### ISSUE THREAD

**Issue by uruddarraju** [hashicorp/terraform#3979]
I am trying to derive the value of a variable through some logic written in a shell script.

I have a shell script that generates a random mac:

```bash
RANGE=255
#set integer ceiling

number=$RANDOM
numbera=$RANDOM
numberb=$RANDOM
#generate random numbers

let "number %= $RANGE"
let "numbera %= $RANGE"
let "numberb %= $RANGE"
#ensure they are less than ceiling

octets='00:60:2F'
#set mac stem

octeta=`echo "obase=16;$number" | bc`
octetb=`echo "obase=16;$numbera" | bc`
octetc=`echo "obase=16;$numberb" | bc`
#use a command line tool to change int to hex(bc is pretty standard)
#they're not really octets.  just sections.
export TESSROUTER_MAC="${octets}:${octeta}:${octetb}:${octetc}"
#concatenate values and add dashes
echo $TESSROUTER_MAC
```

I want to set this MAC value to a variable. So I can use it for a template file and also a local-exec operation. The only ways I know to generate the value of a variable is through interpolation and builtin functions. Is there a way I can plugin my logic (the shell script here) to set a variable ?

**Comment by jen20** [comment]
Hi @uruddarraju! You can create a variable in Terraform HCL using this syntax:

```hcl
variable "my_custom_var" {
    default = "thisisoptional"
}
```

Then, you can either set the variable in a file named `terraform.tfvars`, or on the command line via `terraform plan -var "my_custom_var=value"`. You can then interpolate this variable using the syntax `${var.my_custom_variable}`.

There is more information about this in the documentation for Terraform [here](https://terraform.io/docs/configuration/variables.html).

**Comment by uruddarraju** [comment]
Hey @jen20. Thanks for reponding on the issue. I know the 2 ways of setting the values of a variable, but what if there is a variable that cannot be set and has to be computed. Please see my issue description. I want to set the value of a variable to the output of the shell script, how do i do that ?

**Comment by thegedge** [comment]
This feels like a `template_file` resource, but instead capturing the output of a script. I could see two possibilities here: a new resource similar to `template_file` that spawns an external process and captures its output, or an interpolation function that does the same thing.

If the latter, seems like something that would make sense in core, but would love to see https://github.com/hashicorp/terraform/issues/2771 added so people could quickly get their own functions into the mix. If the former, again would make sense in core, but you could create a plugin to do this.

**Comment by uruddarraju** [comment]
@thegedge https://github.com/hashicorp/terraform/issues/2771 is the one that I am looking for. For now, I have worked around by creating a plugin. Thanks, I would follow #2771 and would close this for now.

Thanks again.
