### ISSUE TITLE
Accessing resource computed variables within the resource scope

### ISSUE THREAD

**Issue by ronpanto** [hashicorp/terraform#398]
I want to be able to access a specific resource variable within that resource.
For example : run a provisioner  for an instance and supply it with the instance private ip (or id or anything else).

**Comment by mitchellh** [comment]
Fixed in master with self variables! `${self.foo}`

**Comment by c4milo** [comment]
@mitchellh does this work within the resource scope. I tried in master and it seems to only work within provisioners.

**Comment by narun4sk** [comment]
Why is `self.ATTRIBUTE` syntax only valid within provisioners?

I would like to do something like the following:
```
resource "aws_ami_copy" "base_img" {
  name              = "deb9-base-img"
  source_ami_id     = "${var.aws_amis["deb9_base"]}"
  source_ami_region = "${var.aws_regions["pro"]}"

  tags = {
    Name = "${self.name}"
  }
}
```
At present I have to repeat the name in the resource scope and the tags.
