### ISSUE TITLE
Final error output should indicate which resource failed.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#3982]
> tldr; In Terraform's error output, each error message should have the associated resource ID printed with it.

In Terraform configurations more with more than a few resources, it can be hard to troubleshoot which resource failed in a sea of many other changes. Terraform will output the error message that occurred but it does not indicate which resource triggered the error. The resource ID should accompany the error message to help troubleshoot errors.
#### Example Configuration

```
resource "null_resource" "main" {
  provisioner "local-exec" {
    command = "if [[ ${count.index} -lt 1 ]]; then echo FAILURE; exit 127; fi"
  }
  count = 5
}
```
#### Output

```
$ terraform apply
null_resource.main.1: Creating...
null_resource.main.2: Creating...
null_resource.main.0: Creating...
null_resource.main.2: Provisioning with 'local-exec'...
null_resource.main.0: Provisioning with 'local-exec'...
null_resource.main.1: Provisioning with 'local-exec'...
null_resource.main.1 (local-exec): Executing: /bin/sh -c "if [[ 1 -lt 1 ]]; then echo FAILURE; exit 127; fi"
null_resource.main.0 (local-exec): Executing: /bin/sh -c "if [[ 0 -lt 1 ]]; then echo FAILURE; exit 127; fi"
null_resource.main.2 (local-exec): Executing: /bin/sh -c "if [[ 2 -lt 1 ]]; then echo FAILURE; exit 127; fi"
null_resource.main.0 (local-exec): FAILURE
null_resource.main.1: Creation complete
null_resource.main.2: Creation complete
Error applying plan:

1 error(s) occurred:

* Error running command 'if [[ 0 -lt 1 ]]; then echo FAILURE; exit 127; fi': exit status 127. Output: FAILURE
...
```

In this output, if `echo FAILURE;` were not present it would be impossible to know what failed without additional fiddling with the provisioner command.
#### Proposed Output

The error output should indicate which resource failed:

```
...
1 error(s) occurred:

* null_resource.main.0: Error running command 'if [[ 0 -lt 1 ]]; then echo FAILURE; exit 127; fi': exit status 127. Output: FAILURE
```

**Comment by clstokes** [comment]
The error output includes the resource ID in some cases, but maybe not for provisioners? Or maybe only on a `refresh`?

```
...
google_compute_firewall.ssh: Refreshing state... (ID: ssh)
google_compute_instance.main.0: Refreshing state... (ID: main-0)
Error refreshing state: 1 error(s) occurred:

* google_compute_instance.main.0: Resource hashicorp-clstokes no longer exists
$
```

**Comment by teamterraform** [comment]
Sorry for the long silence here!

Terraform 0.12 introduced an entirely redesigned approach to error reporting, and now all errors stemming from configuration should be reported with at least enough context to know which configuration construct they relate to, if not the specific expression.

With that said, there are a lot of error messages in Terraform and so it's inevitable that some of them are still not as complete as they ought to be. If anyone should find an error message that is lacking sufficient context to understand what caused it in Terraform 0.12 or later, please do open a new issue about it and we'll see what we can do to improve it.
