### ISSUE TITLE
Librato Provider

### ISSUE THREAD

**Issue by carl-youngblood** [hashicorp/terraform#3983]
Hello, I made a [Librato](https://www.librato.com/) provider for my team. What's the best way to contribute it back to the built in providers?

https://github.com/underarmour/terraform-provider-librato

**Comment by jen20** [comment]
Hi @carl-youngblood! Thanks for this contribution. There is an open pull request here https://github.com/hashicorp/terraform/pull/3371 which contributes a built-in Librato provider which we were intending to merge after the release of 0.6.7. We'll check to ensure that the same range of features are supported.

**Comment by carl-youngblood** [comment]
Thanks!

**Comment by stack72** [comment]
Closed via #3371
