### ISSUE TITLE
JSON variables still broken

### ISSUE THREAD

**Issue by pikeas** [hashicorp/terraform#3988]
Following up on https://github.com/hashicorp/terraform/issues/3964 (comment-locked) and https://github.com/hashicorp/hcl/pull/61, hopefully @svanharmelen or @catsby sees this.

The example on #3964 passes with Terraform compiled from master (after a `make updatedeps` to grab the latest HCL) @ 75d056c878b651931a85e3ad7e41a5d8ddc4583f. But add a variable to the mix and we're still broken:

```
{
    "variable": {
      "foo": {}
    },
    "provider": {
        "cloudstack": {
            "api_url": "bla",
            "api_key": "bla",
            "secret_key": "bla"
        }
    },
    "resource": {
        "cloudstack_firewall": {
            "test": {
                "ipaddress": "${var.foo}",
                "rule": [
                    {
                        "source_cidr": "10.0.0.0/8",
                        "protocol": "tcp",
                        "ports": [
                            "80",
                            "1000-2000"
                        ]
                    }
                ]
            }
        }
    }
}
```

```
$ TF_VAR_foo=a terraform plan -refresh=false                                                                                                                                                               Error configuring: 1 error(s) occurred:

* cloudstack_firewall.test: missing dependency: var.foo
```

Works under 0.6.6, so this is a regression.

**Comment by svanharmelen** [comment]
@pikeas thanks for the report! Will have a closer look at it when behind a desk again...

**Comment by mitchellh** [comment]
For whoever tackles this, let's make sure to add a test to the `config` package for this as well as HCL.

**Comment by svanharmelen** [comment]
@mitchellh @jen20 PR https://github.com/hashicorp/hcl/pull/64 fixes this issue. As with the other issue I added a test in the PR so from a HCL package point of view we're covered :wink:

**Comment by jen20** [comment]
Thanks @svanharmelen! Since hashicorp/hcl#64 is now merged I'll go ahead and close this issue.
