### ISSUE TITLE
Add uuid function to unique names

### ISSUE THREAD

**Issue by rtyler** [hashicorp/terraform#400]
When trying to re-use the consul module already.

```
aws_security_group.consul: Creating...
  description:             "" => "Consul internal traffic + maintenance."
  ingress.#:               "" => "3"
  ingress.0.cidr_blocks.#: "" => "1"
  ingress.0.cidr_blocks.0: "" => "0.0.0.0/0"
  ingress.0.from_port:     "" => "22"
  ingress.0.protocol:      "" => "tcp"
  ingress.0.to_port:       "" => "22"
  ingress.1.from_port:     "" => "0"
  ingress.1.protocol:      "" => "udp"
  ingress.1.self:          "" => "1"
  ingress.1.to_port:       "" => "65535"
  ingress.2.from_port:     "" => "0"
  ingress.2.protocol:      "" => "tcp"
  ingress.2.self:          "" => "1"
  ingress.2.to_port:       "" => "65535"
  name:                    "" => "consul"
  owner_id:                "" => "<computed>"
  vpc_id:                  "" => "<computed>"
aws_security_group.consul: Error: Error creating Security Group: The security group 'consul' already exists (InvalidGroup.Duplicate)
Error applying plan:

1 error(s) occurred:

* Error creating Security Group: The security group 'consul' already exists (InvalidGroup.Duplicate)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
[13:31:23] tyler:testaform $ 

```

**Comment by saulshanabrook** [comment]
Unsure if i should open another issue for this, but also just randomly creating text in general would be helpful. I would use it to create random database passwords.

**Comment by catsby** [comment]
Closing this. `resource` now has a `UniqueId` method, you can see it used AWS KeyPair, or AWS Launch Configurations:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_key_pair.go#L45
- https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_launch_configuration.go#L369

**Comment by phinze** [comment]
Oh and also -> I have an incoming PR that adds `uuid("prefix")` so users can stick a uuid wherever they like. :+1:

Will link it to this issue once I push.

**Comment by saulshanabrook** [comment]
@phinze So if I wanted to create a random password when creating an RDS, could I use this `uuid` function?

**Comment by luhkevin** [comment]
Any progress on this uuid function?

**Comment by catsby** [comment]
@luhkevin `ResourceData` types have a `UniqueId()` , is this what you need?

**Comment by luhkevin** [comment]
To be honest, I can't remember exactly what I needed a generalized uuid function for, but I imagine it would be useful.

I'm assuming `ResourceData` types are any sort of resource that you would provision? E.g. aws_elb, aws_instance, etc...? How do I access or call this `UniqueId()` from these resources? Let's say I wanted to give my aws_instance a random name or tag?

Thanks in advance.

**Comment by catsby** [comment]
Ah, you mean a uuid function exposed to the HCL configuration, not in the code? If so, I misunderstood you, sorry :smile:

**Comment by luhkevin** [comment]
Yes, that's what I meant :)

**Comment by gozer** [comment]
To throw my opinion into this thread, the only safe and reproducible way I could think of dealing with Amazon S3 buckets has been with using UUID-named bucket, to avoid name collisions, since the S3 namespace is global.

Having access to a UUID primitive in Terraform would make my life much easier!
