### ISSUE TITLE
Interpolation escaping only rendered as expected inside template files

### ISSUE THREAD

**Issue by sethp-jive** [hashicorp/terraform#4001]
With the following terraform config:

```hcl
// Doesn't need to be an output, but it's harder to build a cheap example with a resource
output "foo" { 
  value = "$${foo}"
}
```

I would expect `terraform apply` to yield `${foo}`, but instead my output "foo" has the value `$${foo}`. Changing the output to use a single dollar sign fails with the expected "resource variables must be three parts: type.name.attr" error. 

I've tried quite a few ways around, and it is definitely possible to escape "${" but not as easily as "$${":

```hcl
output "foo" {
  // this is the only rendered output whose value is not "${foo}"
  value = "$${foo}"
  // -> $${foo}
}

output "bar" {
  // simplest I've found
  value = "${"$"}${"{"}foo${"}"}"
}

output "baz" {
  // longer, but arguably more readable 
  // any non-empty delimiter, like, spaces also works
  value = "${join("", split(",", "$,{,f,o,o,}"))}"
}

output "fizz" {
  // DOES NOT WORK
  value = "${"$" + "{foo}"}"
  // -> silently fails, no output or error messages at all
}

output "buzz" {
  // only touches the left hand side of the string, so no need for e.g. capturing groups if doing automated escaping
  value = "${join("", split(",", "$,{"))}foo}"
}

resource "template_file" "foo" {
  filename = "foo.tpl"
  // where foo.tpl is $${foo} 
}

output "tpl" {
  value = "${template_file.foo.rendered}"
}
```

Also of note is that output "fizz" gave me neither an output nor an error message; it just vanished into the great beyond. I can file a separate issue about that if you'd prefer – whether `+` is supposed to work for string concatenation or not, I would've expected an error message.

For my case using `string.replace('${', '${join("", split(",", "$,{"))}')` was easiest to perform the escaping, but the others are here in case they're useful workarounds for someone else.

**Comment by mitchellh** [comment]
This was fixed at some point since this was opened, it works on master fine!
