### ISSUE TITLE
aws_elasticache_cluster maintenance_window always wants to reapply if value is not lowercase

### ISSUE THREAD

**Issue by abevoelker** [hashicorp/terraform#4014]
I have this in my `main.tf`:

```
resource "aws_elasticache_cluster" "foo" {
    // ...
    maintenance_window = "Tue:09:00-Tue:10:00"
}
```

which causes `terraform plan` to always want to change it every time I run it:

```
~ aws_elasticache_cluster.foo
    maintenance_window: "tue:09:00-tue:10:00" => "Tue:09:00-Tue:10:00"
```

When I change the value in `main.tf` to be lowercase (`maintenance_window = "tue:09:00-tue:10:00"`) the problem is resolved.

The `aws_elasticache_cluster` docs do use [a lowercase example for `maintenance_window`](https://www.terraform.io/docs/providers/aws/r/elasticache_cluster.html#maintenance_window), however the [`aws_db_instance` (RDS) example](https://www.terraform.io/docs/providers/aws/r/db_instance.html) does not (which is what I had implemented first so I cribbed from that). However, this issue doesn't occur with `aws_db_instance`; that seems to be because it was fixed in #2719.

**Comment by stack72** [comment]
@jen20 @abevoelker fixed in #4020
