### ISSUE TITLE
documentation on templates needs updating

### ISSUE THREAD

**Issue by antonosmond** [hashicorp/terraform#4025]
Awesome job getting the new version out. I've been desperately waiting for the aws_route resource!
Just updated to 0.6.7 and ran a terraform plan & apply.
I get the following warning:
`template_file.my_template: "filename": [DEPRECATED] Use the 'template' attribute instead.`
I checked the docs to see what had changed with templates and there's no mention of it. The examples are using "filename".
https://www.terraform.io/docs/configuration/interpolation.html
https://www.terraform.io/docs/providers/template/

**Comment by shamil** [comment]
Look [here](https://www.terraform.io/docs/providers/template/r/file.html)

**Comment by antonosmond** [comment]
Thanks - I obviously didn't look hard enough.

**Comment by phinze** [comment]
Ah I didn't notice we had examples in those two other places. Fixing those now!
