### ISSUE TITLE
"EDIT THIS PAGE" is not clickable

### ISSUE THREAD

**Issue by f440** [hashicorp/terraform#4026]
CC: @captainill

"EDIT THIS PAGE" is not clickable.

![edit this page](https://cloud.githubusercontent.com/assets/9423/11356350/59c58abe-92a0-11e5-908a-d69d02e01393.png)

related commit: ebec7e2bc

**Comment by captainill** [comment]
thanks @f440 open a pull request with the fix.

**Comment by jen20** [comment]
Fixed in #4026. Thanks @f440!
