### ISSUE TITLE
Deprecated google.account_file still necessary for google_compute_project_metadata?

### ISSUE THREAD

**Issue by Beldur** [hashicorp/terraform#4033]
After updating to the new Terraform Version 0.6.7 and replacing the account_file property with credentials, I get the following warning:

    provider.google.account_file
    Enter a value: 

    There are warnings and/or errors related to your configuration. Please fix these before continuing.

    Warnings:
    * provider.google: "account_file": [DEPRECATED] Use the credentials field instead

I tracked it down to the `google_compute_project_metadata` resource. The following code is my `tf` file. And as soon as the `google_compute_project_metadata` is commented out, the warning disappears.

    provider "google" {
        credentials = "${file("path/to/file.json")}"
        project = "myproject"
        region = "europe-west1"
    }

    resource "google_compute_project_metadata" "default" {
        metadata { foo = "bar" }
    }

**Comment by ajcrowe** [comment]
This is also affecting me, I've not got the metadata resource like @Beldur, I see it a module with just `google_compute_firewall` resources. This appears to be mentioned in #3901 as a potential problem, which appears it is.

**Comment by acondrat** [comment]
I'm having the same problem but I'm using it with google_dns_managed_zone and google_dns_record_set resources.

**Comment by coreone** [comment]
I have seen this bug as well.  To get around it, I just keep `account_file` in there set to nothing:

```
provider "google" {
    account_file = ""
    credentials = "${file("path/to/file.json")}"
    project = "myproject"
    region = "europe-west1"
}
```

Still throws a warning, but it prevents the **Enter a value:** prompt, and allows Atlas to keep working.

**Comment by lwander** [comment]
Both credentials and account file are marked as `optional` [here](https://github.com/hashicorp/terraform/blob/master/builtin/providers/google/provider.go#L16). @phinze, @jen20, any idea why Terraform would prompt you to enter an optional value?

**Comment by phinze** [comment]
@coreone Atlas should be setting `-input=false`, were you still seeing prompts there?

@lwander hm, I'm not sure offhand. Will have to dig in and get back to you.

**Comment by phinze** [comment]
Yep looks like providers are [dumber about Input() than I thought](https://github.com/hashicorp/terraform/blob/7e2c8d21181c8319caa5872037747453d5350226/helper/schema/schema.go#L383-L434).

Enhancements to input are being discussed over in https://github.com/hashicorp/terraform/issues/1255, but for this I'll just PR to always skip input on `Deprecated` fields.
