### ISSUE TITLE
Crash on terraform apply (0.6.7)

### ISSUE THREAD

**Issue by Vlatombe** [hashicorp/terraform#4036]
Hello,

Updating from 0.6.3 to 0.6.7, I'm now getting a crash on apply.

[Config.tf](https://gist.github.com/52c87854ee0cb006de24)
[crash.log](https://gist.github.com/26a1d66ced11ec6a3f8e)

**Comment by jen20** [comment]
Hi @Vlatombe. Thanks for reporting this. The relevant section of the crash log is here:

```
2015/11/24 09:26:03 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2015/11/24 09:26:03 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0xb08940]
2015/11/24 09:26:03 [DEBUG] terraform-provider-aws: 
2015/11/24 09:26:03 [DEBUG] terraform-provider-aws: goroutine 18 [running]:
2015/11/24 09:26:03 [DEBUG] terraform-provider-aws: github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0x13555e0, 0x19, 0x0, 0x0, 0x0, 0x0)
2015/11/24 09:26:03 [DEBUG] terraform-provider-aws: 	/opt/gopath/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:18 +0x1b0
```

I think there's an open PR which may address this issue.

**Comment by jen20** [comment]
@Vlatombe I think the PR I just reference may have fixed this. Do you currently have facilities to build Terraform from source to verify whether that is indeed the case?

**Comment by phinze** [comment]
Just re-ran the repro config and got a clean run. Looks like #4024 solves this, though it'd be great to heard confirmation from you as well @Vlatombe.

**Comment by Vlatombe** [comment]
I'll take some time to test from master.

**Comment by Vlatombe** [comment]
@phinze @jen20 Looks good on my end.

**Comment by JensRantil** [comment]
Maybe add `crash` label to this issue, too?

**Comment by catsby** [comment]
Looks like we've confirmed #4024 has fixed this, and we've labeled it `crash` for good measure. Thanks all!
