### ISSUE TITLE
Adding multiple Ephemeral Volumes to Compute Instance on OpenStack

### ISSUE THREAD

**Issue by afritzler** [hashicorp/terraform#4042]
Hi guys,

is there a way to add multiple ephemeral volumes to a given instance?

```
nova boot <vm-name> --image <image-id> --flavor <flaovr-id> \ 
--nic net-id=<net-id> --availability-zone <availability-zone-name> \
--ephemeral size=<size>,format=<format_type> \
--ephemeral size=<size>,format=<format_type> \
... and so on
```

Of course your flavor has to have a big enough ephemeral size configured.

http://docs.openstack.org/cli-reference/content/novaclient_commands.html#novaclient_subcommand_boot

Regards,
Andreas

**Comment by jtopjian** [comment]
Hi there,

I didn't know you could do this. :smile: 

It looks like this works by passing the ephemeral disks to the `block_device_mapping` parameter of the Nova API:

```json
"block_device_mapping_v2": [
    {
        "boot_index": 0,
        "delete_on_termination": true,
        "destination_type": "local",
        "source_type": "image",
        "uuid": "036fa6c1-b9c1-435c-9d70-83de40d4af96"
    },
    {
        "boot_index": -1,
        "delete_on_termination": true,
        "destination_type": "local",
        "guest_format": "ext4",
        "source_type": "blank",
        "volume_size": "1"
    },
    {
        "boot_index": -1,
        "delete_on_termination": true,
        "destination_type": "local",
        "guest_format": "ext4",
        "source_type": "blank",
        "volume_size": "1"
    }
],
```

This should be supported in Gophercloud, under the `bootfromvolume` extension. If this is true, then the Terraform OpenStack provider will need modified to allow more than one `block_device` block (right now it enforces only one under the assumption that it's a single bootable volume).

Thanks for reporting this. Hopefully we'll be able to get this enabled soon.

**Comment by afritzler** [comment]
Thanks for the update @jtopjian. Looking forward to the multiple `block_device` support.

**Comment by jtopjian** [comment]
Just a quick update: I have this working but need to get a few small changes into Gophercloud. If you're interested, here is the working code:

https://github.com/jtopjian/terraform/tree/jtopjian-openstack-multi-ephemeral
https://github.com/jtopjian/gophercloud/tree/jtopjian-multi-ephemeral

There might be minor changes to those two branches over time.

**Comment by afritzler** [comment]
Thanks a lot for the update @jtopjian!

**Comment by justinclayton** [comment]
@jtopjian I feel like my timing is very fortunate, as it looks like this is really close to being done. If I am reading this right, you merged #4288 yesterday, which was a prerequisite for you creating a PR for your jtopjian-openstack-multi-ephemeral branch (jtopjian/terraform@d681c25)?

**Comment by jtopjian** [comment]
@justinclayton Yep, all correct. :smile: 

The next step is to get https://github.com/rackspace/gophercloud/pull/515 merged and then I'll be able to open a PR for https://github.com/jtopjian/terraform/commit/d681c25.

**Comment by jtopjian** [comment]
@afritzler @justinclayton Hey guys, just a heads up that I opened #5131. If you can, please test and let me know if you have any problems or comments!
