### ISSUE TITLE
azure: error parsing settings_file as XML: EOF

### ISSUE THREAD

**Issue by ravbaba** [hashicorp/terraform#4054]
Hi,
I get the error with azure provider:

```
[ERROR] root: eval: *terraform.EvalSequence, err: Warnings: ["settings_file": [DEPRECATED] Use the publish_settings field instead]. Errors: [error parsing settings_file as XML: EOF]
```

I changed settings_file to publish_settings and I still get the same issue.

```
provider "azure" {
  publish_settings = "${file(var.azure_settings_file)}"
}
```

**Comment by jen20** [comment]
Hi @ravbaba, thanks for opening the issue. Can you confirm that the file you're referencing is in fact valid XML? Do you have the `azure_settings_file` variable set anywhere?

**Comment by ravbaba** [comment]
Hi @jen20, yes, I have a valid XML file and azure_settings_file variable is set in a different file. All my configuration worked before I changed terraform version to 0.6.7.

I tested it on two different machines (mac and ubuntu) and I got the same error. I tried to use those two arguments instead of publish_settings or settings_file:

```
subscription_id
certificate
```

but I got the same error.

Please let me know if you need more details.

**Comment by xied75** [comment]
Related to avoid a new issue I'll put it here.

It seems although the warning information is about settings_file is DEPRECATED, yet if I don't specify this in tf and use publish_settings, I still get the same warning (plus a prompt for settings_file value, if I just enter I'll get the warning). If I set both, I no longer got prompt but the warning will still display.

Might be in the source code settings_file is NOT optional, thus the required status.

**Comment by progre55** [comment]
I can confirm the failures. Was using tf 0.6.6, with `settings_file` and everything was fine. Upgraded to tf 0.6.8, now nothing works. I have renamed `settings_file` to `publish_settings`, but still get a prompt for settings_file, and then it fails with `EOF` as follows
```
terraform plan -target=module.azure-instance-01

provider.azure.publish_settings
  Enter a value: azure.publishsettings

There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Warnings:

  * module.azure-instance-01.provider.azure: "settings_file": [DEPRECATED] Use the publish_settings field instead

Errors:

  * module.azure-instance-01.provider.azure: error parsing publish_settings as XML: EOF
```
Here is my provider declaration:
```tf
provider "azure" {
  publish_settings = "${file(var.azure_publish_settings)}"
}
```

I am sure that the file is a valid XML file. Used to work well with 0.6.6.

**Comment by davehodgson** [comment]
I have exactly the same behaviour after upgrading 0.6.6 to 0.6.8, it worked with no issues before - the only change I made was in response to the warning about deprecation and that was to change settings_file to publish_settings as above

**Comment by joaocc** [comment]
+1

**Comment by bdelamotte** [comment]
Hi, is this still broken in 0.6.11?

**Comment by joaocc** [comment]
Yeap.
I have since moved to ARM, which is the "new and recommended thing" and, most importantly, works :)

**Comment by BigCheeze45** [comment]
@joaocc could you be so kind as to share a sample Terraform file using ARM. I've been trying to move over to ARM but haven't had much success on that front. Thanks in advance!

**Comment by joaocc** [comment]
Hi @BigCheeze45. 
What problem are you facing? 
I managed to get it working by setting auth as environment variables:
```
export ARM_SUBSCRIPTION_ID=xxxxxxxx-xxx-xxx-xxx-xxxxxxx
export ARM_CLIENT_ID=
export ARM_CLIENT_SECRET=
export ARM_TENANT_ID=
```
and defining and empty provider
```
provider "azurerm" {
}
```

**Comment by BigCheeze45** [comment]
@joaocc,
I get this error message:
Error refreshing state: 1 error(s) occurred:

* 3 error(s) occurred:

* Client ID must be configured for the AzureRM provider
* Client Secret must be configured for the AzureRM provider
* Tenant ID must be configured for the AzureRM provider

The subscription id I have no problem finding but it's the other ones I'm on quite confused on. And I've looked at resources online to see how to generate those (Client and Tenant ID and Client Secret) but nothing seems to be working. I'm on version 0.6.11. Will tryout your solution and see if it works on my end. Again, thanks for the help.

**Comment by joaocc** [comment]
@BigCheeze45, pls check the nstructions [here](https://groups.google.com/forum/#!searchin/terraform-tool/azure/terraform-tool/4EqqbQFk0M0/G1Vb3H0mCAAJ).
This is how I was able to generate those keys.
J

**Comment by BigCheeze45** [comment]
Just wanted to say thanks for the help @joaocc. I was able to generate all the necessary key. I'm getting a 403 (Forbidden) error but I think I can tinker with it from here. Thanks again :+1: :+1:  :smile:
