### ISSUE TITLE
Google Cloud: Missing google_compute_instance_group resource

### ISSUE THREAD

**Issue by ajcrowe** [hashicorp/terraform#4060]
It appears that currently you can only create a `google_instance_group_manager` and not just a regular unmanaged instance group.

Am I missing something or is this simply not implemented currently?

**Comment by ajcrowe** [comment]
I've implemented this in #4087

**Comment by thecodeassassin** [comment]
@ajcrowe is it possible to use this with the compute_backend_service? It currently requires a manager i believe i am wondering if your implementation also works. By the way do you know when they will create a version that has your merged PR?

**Comment by ajcrowe** [comment]
Hi @thecodeassassin, yes I believe it should work, you'll need to use the `self_link` attribute from the `compute_instance_group` in the `backend` block in your `compute_backend_service`.

They released `0.6.13` which contains this addition.

**Comment by radeksimko** [comment]
Can we close this now since #4087 was merged?

**Comment by thecodeassassin** [comment]
@radeksimko @ajcrowe any chance the documentation on this can be updated? https://www.terraform.io/docs/providers/google/index.html

**Comment by thecodeassassin** [comment]
Never mind i see it was since added, thanks guys!

**Comment by ajcrowe** [comment]
Closing as this is all merged and documented
