### ISSUE TITLE
ELB output crash - panic: runtime error: index out of range

### ISSUE THREAD

**Issue by xsmaster** [hashicorp/terraform#4063]
Just got this crash. Below is the report.

Terraform version: 0.6.6 from homebrew
[crash.log.txt](https://github.com/hashicorp/terraform/files/44045/crash.log.txt)

Repro steps:

1. Create any ELB on AWS.
2. setup an outputs value with the below.

output "ELB Instances:" {
  value = "${aws_elb.load-balancer.instances}"
}

ELB Instances:       = B780FFEC-B661-4EB8-9236-A01737AD98B6

Now change the value to.

output "ELB Instances:" {
  value = ["${aws_elb.load-balancer.instances}"]
}

CRASH!

2015/11/25 09:49:52 [DEBUG] vertex provider.aws (close), got dep: aws_elb.load-balancer
2015/11/25 09:49:52 [DEBUG] vertex root.provider.aws (close): walking
2015/11/25 09:49:52 [DEBUG] vertex root.provider.aws (close): evaluating
2015/11/25 09:49:52 [DEBUG] root: eval: *terraform.EvalCloseProvider
2015/11/25 09:49:52 [DEBUG] root: eval: *terraform.EvalSequence
2015/11/25 09:49:52 [DEBUG] root: eval: *terraform.EvalWriteOutput
panic: runtime error: index out of range

goroutine 155 [running]:
github.com/hashicorp/terraform/terraform.(*EvalWriteOutput).Eval(0xc8203c8060, 0x1084a18, 0xc820592270, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform20151027-12984-1engydp/terraform-0.6.6/src/github.com/hashicorp/terraform/terraform/eval_output.go:81 +0x69f
github.com/hashicorp/terraform/terraform.EvalRaw(0x10858c8, 0xc8203c8060, 0x1084a18, 0xc820592270, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform20151027-12984-1engydp/terraform-0.6.6/src/github.com/hashicorp/terraform/terraform/eval.go:53 +0x25b
github.com/hashicorp/terraform/terraform.(*EvalSequence).Eval(0xc8203c84a0, 0x1084a18, 0xc820592270, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/terraform20151027-12984-1engydp/terraform-0.6.6/src/github.com/hashicorp/terraform/terraform/eval_sequence.go:10 +0xea
github.com/hashicorp/terraform/terraform.EvalRaw(0x2300118, 0xc8203c84a0, 0x1084a18, 0xc820592270, 0x0, 0x0, 0x0, 0x0)

Using the [] around other outputs seems work fine like this:

output "ELB Security Groups#:" {
  value = ["${aws_elb.load-balancer.source_security_group}"]
}

you get the group names but only one.

**Comment by xsmaster** [comment]
So this is because the ELB has zero instances. So I hit a null pointer issue.

**Comment by mitchellh** [comment]
Tried this on master and it has been fixed. No direct link to commit since it was probably in a dup issue somewhere, sorry!
