### ISSUE TITLE
Terraform crash 0.6.7 using aws modules

### ISSUE THREAD

**Issue by stevendborrelli** [hashicorp/terraform#4064]
Configuration works on 0.6.6, `terraform plan` crashes 0.6.7. We were able to do a full apply on 0.6.6. 

crash.log is attached.

[crash.txt](https://github.com/hashicorp/terraform/files/44056/crash.txt)

**Comment by jen20** [comment]
Hi @stevendborrelli. Thanks for reporting this. I think this is the issue fixed in #4024 - are you running Terraform in an EC2 instance?

**Comment by stevendborrelli** [comment]
We're running tf on a vm in openstack.

**Comment by catsby** [comment]
Closing for now, please let us know if you're still experiencing this

**Comment by stevendborrelli** [comment]
Sorry, yes this is good to close. Thanks!
