### ISSUE TITLE
can we support folders?

### ISSUE THREAD

**Issue by cordoval** [hashicorp/terraform#4067]
i am organizing my .tf files trying to find a way to scan .tf under deeper folders

i think this is a pretty common use case so not sure if i am missing something, i noticed the [dir] argument but i am trying to see if i can pass at least multiple directories as arguments

any hints?

**Comment by cordoval** [comment]
I am having a script that looks like this so far

```bash
#!/usr/bin/env bash
terraform plan \
    ecs
    output
    providers
    registry
    security
    -var-file="secret_vars.tfvars" \
    -var-file="ecs/public_vars.tfvars"
```

**Comment by jen20** [comment]
Hi @cordoval! Currently this isn't supported - though you may be able to make use of the module system to organise your code in the manner you'd like?

**Comment by cordoval** [comment]
@jen20 the problem with modules is that they require to be pulled out from the web or registries, i don't like that, i want everything in subfolders.

**Comment by jen20** [comment]
They don't need to be pulled out of the web or registries: you can specify the source as a subdirectory of the file system - for example:

```hcl
module "iam" {
     source = "${path.module}/modules/iam"
}
```

Does that make them more palatable?

**Comment by cordoval** [comment]
you rock @jen20

**Comment by cordoval** [comment]
it still stores them with ```terraform get``` into under .terraform/modules right? so i always have to run terraform get whenever i do any change in them

**Comment by jen20** [comment]
Hi @cordoval, actually no you don't need to run `terraform get` unless you add a new module, or you have a fresh clone of the repository. This is because `terraform get` uses symlinks in the `.terraform/modules` directory:

```
.
├── .terraform
│   └── modules
│       └── de20b4a64fe2fcc6b3b57b2c0e1e2b01 -> /Users/James/Code/terraform/mods/module
├── main.tf
├── module
│   └── main.tf
```

Hopefully this provides a solution - feel free to reopen if not!
