### ISSUE TITLE
Request: CloudFormation-like psuedo-parameters (provider variables?)

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#4068]
I'm moving some of our templates from CloudFormation to Terraform and am probably going to miss some of the functionality that CloudFormation has (ie: using `"Ref": "AWS::AccountId"` to get the account ID the stack is being run in).

Are there any plans or anything underway to implement something like this, maybe like a certain set of  variables that can be looked up on for a specific provider?

**Comment by jen20** [comment]
I like this idea, especially for the purposes of things like account IDs. Offhand I'm not sure how easy or otherwise these are to implement, but I will investigate. Perhaps @phinze knows if there are reasons this has not been considered before (or indeed if it has)?

**Comment by radeksimko** [comment]
I think this is very closely related to https://github.com/hashicorp/terraform/issues/1199

**Comment by vancluever** [comment]
Just a quick gander at the source - if we can set computed variables in the schema for providers, this should be just as easy as it would be for setting it in a resoruce.

Now the trick is to figure out a way to reliably get the account ID, which has always been trouble.

**Comment by vancluever** [comment]
One possible way for account ID that may be consistent across everything:

http://docs.aws.amazon.com/sdk-for-go/api/service/iam/IAM.html#ListAccountAliases-instance_method

This grabs a single alias, which is either the account ID if an alias has not been set, or the alias that you have set. It might be a good stand-in until a way to get the full account ID is found, depending on its availability.

**Comment by phinze** [comment]
Yep this would be great to have - let's merge this down with #1199 to keep things tidy.

@vancluever I feel your pain on the AccountID lookup. Elsewhere in the codebase we've just [eaten the caveats of `GetUser`](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_instance.go#L843-L849) and used it.
