### ISSUE TITLE
Syntax error with heredoc's on Windows in TF v0.6.7

### ISSUE THREAD

**Issue by bensojona** [hashicorp/terraform#4069]
`terraform get` fails with the error `Error loading Terraform: Error loading config: Error parsing C:\Users\Steve\Documents\RubymineProjects\best-practices\terraform\providers\aws\us_west_1_staging\main.tf: At 231:9: illegal char` anywhere a heredoc used. 

v0.6.6 works fine, but 0.6.7 fails with this syntax error. Seems to work fine on OS X, but Windows not so much.

Example of where it's failing for the error mentioned above (L231:9)...

```
output "configuration" {
  value = <<CONFIGURATION
CONFIGURATION
}
```

**Comment by partamonov** [comment]
I saw same behavior. 0.6.7 looks like more sensitive to line endings. I solved similar issue with converting your.tf file to linux line endings

**Comment by bensojona** [comment]
@partamonov will give it a shot, thanks!

**Comment by jen20** [comment]
Seems there are indeed some issues upstream with HCL and Windows line ending support. I'll work on getting them fixed tomorrow.
