### ISSUE TITLE
Issue with EC2-Classic ELBs in v0.6.7

### ISSUE THREAD

**Issue by elblivion** [hashicorp/terraform#4073]
Hello folks,

It seems like https://github.com/hashicorp/terraform/pull/3780 broke v0.6.7 for me. I have a production AWS account with EC2-Classic, in the process of migrating to VPC. I have an ELB in EC2-Classic managed by terraform, and since I upgraded to v0.6.7 I get this error on a `terraform plan`:

```
Error refreshing state: 1 error(s) occurred:

* aws_elb.cdn_elb: [WARN] Error looking up ELB Security Group ID: No security groups found for name amazon-elb-sg and vpc id
```

I will try to debug the issue later but my guess is something is up with the logic [here](https://github.com/hashicorp/terraform/blob/7152674f9b9f1dc20fa9f655d363d42719988d48/builtin/providers/aws/resource_aws_elb.go#L307-L321) since it shouldn't even have to worry about that in EC2-Classic, the source security group is always the above.

Thanks in advance

**Comment by jen20** [comment]
Hi @elblivion, thanks for reporting this. I've marked this as a bug, @catsby is probably the best person to pick this up.

**Comment by elblivion** [comment]
Sorry for not providing a full config & output right now. I can say that this is the value of `lb.SourceSecurityGroup` (and should be so for any EC2-Classic ELB):

```
      "SourceSecurityGroup": {
        "OwnerAlias": "amazon-elb",
        "GroupName": "amazon-elb-sg"
      }
```

Maybe it's enough to put [this bit](https://github.com/hashicorp/terraform/blob/7152674f9b9f1dc20fa9f655d363d42719988d48/builtin/providers/aws/resource_aws_elb.go#L315-L320) in the preceding `if` statement.

**Comment by little-arhat** [comment]
@catsby can you please release a bugfix with this?
