### ISSUE TITLE
Support AWS Data Pipeline

### ISSUE THREAD

**Issue by danielcompton** [hashicorp/terraform#4077]
It would be nice to be able to use AWS Data Pipeline with Terraform, especially for things like updating the AMI id when Packer builds a new one.

http://docs.aws.amazon.com/datapipeline/latest/APIReference/Welcome.html

**Comment by pawelsawicz** [comment]
Hey,

I am looking at it, will try to implement this, as I am new in Go it can take a while.

**Comment by stack72** [comment]
@pawelsawicz are you still working on this? If so, how is the progress? :)

**Comment by desmondmorris** [comment]
+1 This would be great.

**Comment by jamescarr** [comment]
Just checking in again on this. We'd benefit from it as well.

**Comment by pawelsawicz** [comment]
I am changing jobs now so I had to do a break on it.

**Comment by jamescarr** [comment]
That's fine... I'm curious if hashicorp has this on their roadmap?

**Comment by radeksimko** [comment]
@jamescarr I can't talk on behalf of Hashicorp, but as for myself, it is somewhere on my to-do list, below Lambda related resources, CloudWatch Events and API Gateway. Possibly fixing a few reported RDS & CloudFormation & ECS bugs may also take priority. I can't say when I will get to it, I'm merely expressing the interest in getting it done.

If you really need it and don't want to wait, it's probably best to send a PR. Here are some hints on what can you do to speed things up when sending the PR (i.e. what makes a good PR that has higher chance of being merged sooner): https://github.com/hashicorp/terraform/blob/master/CONTRIBUTING.md#pull-requests

**Comment by ApsOps** [comment]
+1 It would be nice, for taking/updating dynamodb backups as well. Any updates on this?

**Comment by pawelsawicz** [comment]
After a while, I get back to that. I just want to double check if it's still free to pick up. I assume that nobody send PR yet ?

**Comment by stack72** [comment]
Hi @pawelsawicz 

Feel free to pick this up still :)

Paul

**Comment by pawelsawicz** [comment]
@stack72 yes I am working on this at my fork

**Comment by stack72** [comment]
Nice :)

**Comment by rchibiscus** [comment]
looking forward to this feature!!!

**Comment by razic** [comment]
oh sad face :(

**Comment by apparentlymart** [comment]
Hi all,

Thanks for opening this request and to @pawelsawicz for taking a stab at implementing it.

We (the Terraform team) would love to support AWS Data Pipeline, but it's a bit of a beast to implement and we don't have any plans to work on it in the short term. We're trying to prune enhancement requests that are stale and likely to remain that way for the foreseeable future, so I'm going to close this.

However, if a motivated person were interested in working on this we'd be happy to provide guidance and review a PR.

**Comment by howdoicomputer** [comment]
@pawelsawicz @apparentlymart My company has a need for data pipeline support. As of right now, we're wrapping a cloud formation template but I would love it if there was native support. If nobody is chucking code at this, would a pull request be welcome?

**Comment by apparentlymart** [comment]
Hi @howdoicomputer!

A PR would indeed be welcome. It would be nice to have data pipeline support.

Given that data pipeline is a pretty complex service, I'd suggest trying to attack it in several smaller steps if possible. Usually we try to start with one or two most important resources, or a useful subset there of, and then build up from there. If there are particular subsets of functionality you need then staring there seems reasonable! Just need to do our best to leave room in the design for other functionality to be added later.

Thanks for your interest!

**Comment by howdoicomputer** [comment]
@apparentlymart Hooray! It'll take me a bit between work responsibilities and [terrashovel](https://github.com/howdoicomputer/terrashovel) but I'd be super happy to help.

**Comment by apparentlymart** [comment]
Sorry, forgot to mention this yesterday: since this issue was opened the AWS provider development has moved into [a separate repo](https://github.com/terraform-providers/terraform-provider-aws), any new issues or PRs for this will need to be opened there in future. This is part of [the provider/core split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/).

**Comment by arevell89** [comment]
any update on this?

**Comment by eugenejen** [comment]
I haven't seen any one raises the issue regarding data pipeline in [terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws)

**Comment by SorJEF** [comment]
Hi there! 

I had a similar problem and I've come up with a script to convert data pipelines templates to CloudFormation templates and a Terraform module to help integrate it into the configuration.

The script is written on node.js, so it might not work for everybody, but still, I hope it helps somebody.

I've added more context in terms of my setup and the link to the solution in [this StackOverflow  post](https://stackoverflow.com/questions/45164614/exporting-aws-data-pipeline-as-cloudformation-template-to-use-it-in-terraform/46044120#46044120).

**Comment by iamShantanu101** [comment]
+1 This would be great. It's Oct, 2017 and still waiting for the support.

**Comment by melbourne2991** [comment]
+1 would be really helpful to have this

**Comment by radeksimko** [comment]
As mentioned above AWS provider now has its own repository, please follow https://github.com/terraform-providers/terraform-provider-aws/issues/1538
Thanks.
