### ISSUE TITLE
Total vCpu's allocated to all vm's on a esxi host

### ISSUE THREAD

**Issue by kc11381** [hashicorp/terraform#4086]
How to know total vCpu's allocated to all vm's on a esxi host?
Do we have to traverse through all the connected vm's?

**Comment by jen20** [comment]
Hi @kc11381. Although I've not tried much with the vsphere provider, I don't think there is support in the core for this kind of roll-up reporting. I can see some uses for it in other providers as well (for example, account totals in AWS). I'll give it some thought as to how we might be able to implement it.

In the meantime, if you can find the number of vCPUs via the host resource, you might be able to make use of an output and the [interpolation syntax](https://terraform.io/docs/configuration/interpolation.html) for a crude method of reporting this.

**Comment by chrislovecnm** [comment]
@kc11381 what is your use case? What are you trying to do?

**Comment by kc11381** [comment]
Hi Jen20,

I think I will have to iterate over each vm on a esxi host and get this value. There is no direct property of HostSystems to get it. Please correct me here.

**Comment by kc11381** [comment]
Hi Chris,

Actually I want to select a esxi host for creating a vm based on pCpu:vCpu ratio.

**Comment by chrislovecnm** [comment]
@kc11381 govc, the command line util of govomi, has a cpu usage.  I would look at the host object and see if there is that type of information.  Otherwise you will have eto go through each vm, and each host.

Here is the code ref that I am seeing https://github.com/vmware/govmomi/blob/master/govc/host/info.go#L134

**Comment by kc11381** [comment]
Hi Chris,

Thank you for looking at it. CPU usage does not talk about vcpu. So it will not solve my purpose. I think iterating over vms is the only option left now.

**Comment by kc11381** [comment]
Hi Chris,

Can you please look at: https://github.com/vmware/govmomi/issues/389
Thank you.

**Comment by kc11381** [comment]
Hi Chris,
I have iterated over all the vm's to get the count of cCPU.
I will submit my code here once I am done with my changes. 
Thank you for very much for looking here.
