### ISSUE TITLE
Question: Potential Restructure of IAM Role and Managed Policies

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform#4088]
I propose the way that IAM Role and Managed Policies work are restructured. Right now I have to do the following:

``` hcl
resource "aws_iam_role" "my-rrole" {
    name               = "my-role"
    path               = "/"
    assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy" "All-Access-MyBucket" {
    name   = "All-Access-MyBucket"
    role = "${aws_iam_role.my-role.id}"
    policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::my-bucket"
      ]
    }
  ]
}
POLICY
}
```

There is a 1:1 mapping between IAM role policy and IAM role. This means to attach the same managed policies to different roles, I need to copy the iam_role_policy. 

I suggest something like this:

``` hcl
/* template file for actual policy */
/* template file for assume role policy */

resource "aws_iam_policy" "policy" {
    document = "${template_file.policy.rendered}"
    name = "whatever"
    path = "/policies/"
}

resource "aws_iam_role" "some_role" {
    name = "whatever"
    path = "whatever"
    assume_role_policy = "${template_file.assume_role_policy.rendered}"
    managed_policy_attachments = [
        "${aws_iam_policy.policy.id}"
    ]
}
```

Anyone have any thoughts on this? This would be backwards compatible because the only change to the IAM Role resource would be the addition of the managed_policy_attachments field

**Comment by stack72** [comment]
*bump*

**Comment by hngkr** [comment]
I agree.

aws_iam_policy_attachment makes it possible to attach a number of roles to a policy (also a Managed policy), but if you don't know the name or number of roles to attach at runtime, then that won't be of any help.

The other way around (defining a list of managed policy attachments as described above) also makes more sense in from my point of view.
