### ISSUE TITLE
AWS VPC resource does not support 'InstanceTenancy'

### ISSUE THREAD

**Issue by olbrich** [hashicorp/terraform#409]
I would expect this

    resource "aws_vpc" "main" {
        cidr_block = "10.0.0.0/16"
        instance_tenancy = "dedicated"
        tags {
            Name = "main"
        }
    }

To create a VPC with InstanceTenancy set to "dedicated", but instead a parse error is thrown.  Inspection of the code suggests that this parameter is just not passed onto the ec2 library, which does seem to support it.

**Comment by phinze** [comment]
Done in #637

I just so happened to be searching for "tenancy" and the PR and issue came up right next to each other.  :grinning:
