### ISSUE TITLE
Using lists for list parameter types

### ISSUE THREAD

**Issue by ipsq** [hashicorp/terraform#4091]
I want to create a Route 53 record containing all my EC2 instance IP's like so:

```
resource "aws_instance" "web" {
    ami = "ami-47a23a30"
    instance_type = "t2.micro"
    subnet_id = "${aws_subnet.main.id}"
    vpc_security_group_ids = ["${aws_security_group.web.id}"]
    availability_zone = "${aws_subnet.main.availability_zone}"
    associate_public_ip_address = true
    count = 5
}

resource "aws_route53_record" "individual" {
   zone_id = "${var.aws_route53_zone_id}"
   name = "all.example.com"
   type = "A"
   ttl = "60"
   records = "${aws_instance.web.*.public_ip}"
}
```

This (`records = "${aws_instance.web.*.public_ip}"`) is the failing part but I've tried almost everything (`records = ["${element(aws_instance.web.*.public_ip, count.index)}"]`, `records = ["${aws_instance.web.*.public_ip}"]` and `records = "[${join(", ", aws_instance.web.*.public_ip)}]"`) but nothing seems to give the desired result. Logically speaking, the answer would be `records = ${aws_instance.web.*.public_ip}` without quotes or brackets but that also doesn't seem to work and produces a syntax error.

**Comment by jen20** [comment]
Hi @ipsq - the correct syntax to use is:

```hcl
   records = ["${aws_instance.web.*.public_ip}"]
```

This is because `records` expects a list, even if there is only one element, and the interpolation inside will expand to multiple items.
