### ISSUE TITLE
Proposal: require certain version of Terraform

### ISSUE THREAD

**Issue by yawn** [hashicorp/terraform#4092]
Proposal: add an optional version selector to the Terraform configuration syntax, e.g.

```
version {
  minimum = "0.6.7" # implicitly: or higher
}
```

Use case: enforce that infrastructure that relies on certain features or bug-fixes in Terraform cannot be run by buggy versions.

**Comment by CpuID** [comment]
+1 we effectively do this via a rake wrapper currently.

**Comment by jen20** [comment]
@phinze I think this might be a good idea. We should probably discuss which part of the config this should go in, though.

**Comment by jen20** [comment]
I've started implementing this, with a new `terraform` configuration block. Currently it looks like this:

```hcl
terraform {
    min_version = "0.6.7"
}
```

I'm still working on some tests etc and will push it later today.

**Comment by yawn** [comment]
:+1:

**Comment by ghempton** [comment]
@jen20 Any update on this?

**Comment by pdecat** [comment]
Hi,

I somewhat managed to implement this using the following terraform configuration.

```
variable "terraform_version" {
  default = "v0.6.12"
}

resource "null_resource" "tfversion" {
  provisioner "local-exec" {
    command = "terraform --version | grep ${var.terraform_version}"
  }
  triggers {
    TFVERSION = "${var.terraform_version}"
  }
}
```

It will warn during plan:

```
-/+ null_resource.tfversion
    triggers.#:         "" => "1"
    triggers.TFVERSION: "" => "v0.6.12"


Plan: 1 to add, 0 to change, 0 to destroy.
```

And fail during apply:

```
Error applying plan:

1 error(s) occurred:

* Error running command 'terraform --version | grep v0.6.12': exit status 1. Output: 2016/03/22 10:36:27 [INFO] Terraform version: 0.6.13  1f627a8a0b3e9db464fa186fec053d1f7f002e9a
```

I acknowledge this is not perfect.
For once, the local-exec command makes it not portable.
Also, I'm not sure it fails before applying any other changes to the state, even if placed at the beggining. Adding dependencies to this resource everywhere may help but would be a PITA.
Still, I believe it is better than nothing.

So, I'll also add a +1 to the resolution of this issue.

**Comment by radeksimko** [comment]
Not exactly a flag that a user can specify, but something interesting in regards to this issue is in https://github.com/hashicorp/terraform/pull/5597

**Comment by pdecat** [comment]
Indeed! Thanks for the pointer.

**Comment by mitchellh** [comment]
Dup of #1400 which I agree with!
