### ISSUE TITLE
Documentation: new aws_route resource under Route 53 in contents list instead of VPC

### ISSUE THREAD

**Issue by SpencerBrown** [hashicorp/terraform#4096]
see https://terraform.io/docs/providers/aws/index.html and scroll down to Route 53. 

You'll see that the `aws_route` resource is listed there, instead of under VPC where it should be.

**Comment by stack72** [comment]
@SpencerBrown there is a PR open to fix this now - #4101

**Comment by SpencerBrown** [comment]
Ok great, closing this issue. Thanks!
