### ISSUE TITLE
How to set a esxi host for deploying a vm

### ISSUE THREAD

**Issue by kc11381** [hashicorp/terraform#4104]
Hi,

We have multiple compute clusters. I want to choose a specific esxi host. Is it possible?
From:
https://github.com/mkuzmin/terraform-vsphere/blob/master/resource_virtual_machine.go line:187
I can see he has done it. But I am not able to do it here.
Thank you.

**Comment by kc11381** [comment]
Also,

How can I get associated datastore on the chosen esxi host and how to set datastore too.
Thank you.

**Comment by chrislovecnm** [comment]
Environment variables or you can list in your tf file. All is documented: https://terraform.io/docs/providers/vsphere/index.html

**Comment by kc11381** [comment]
Hi Chris,

But it does not talk about a specific esxi host. Am I missing something here?
Thank you.

**Comment by chrislovecnm** [comment]
The 'VSPHERE_CLUSTER' environment variable or 'cluster' terraform variable should do the trick. I need to verify, but I am on my phone right now.

**Comment by chrislovecnm** [comment]
@kc11381 help with updating documentation is always appreciated. Having a new users perspective on the documentation is invaluable.

**Comment by kc11381** [comment]
Hi Chris,

To me VSPHERE_CLUSTER means a ComputeCluster and not a specific esxi host.
I will submit my code here once I am done with my changes. 
Thank you.

**Comment by chrislovecnm** [comment]
@kc11381 I understand what you are saying, and feel free to submit a bug and a pr ... the 'cluster' option in your tf file will work with the ip address, and I have not tried dns.

**Comment by chrislovecnm** [comment]
@catsby this is a question not a bug btw ...

**Comment by chrislovecnm** [comment]
@jen20 @catsby please close
