### ISSUE TITLE
aws_security_group_rule schema

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [hashicorp/terraform#4109]
Currently, source_security_group_id conflicts with cidr_blocks and self, self conflicts with cidr_blocks. Also, source_security_group_id can only have a single value. It would be useful to be able to write:

```
resource "aws_security_group_rule" "tcp-80" {
  type = "ingress"
  security_group_id = "${aws_security_group.some_group.id}"
  from_port = 80
  to_port = 80
  protocol = "tcp"
  cidr_blocks = ["1.2.3.4/24", "5.6.7.8/32"]
  source_security_group_id = ["${aws_security_group.other_group.id}", "sg-abcdef"]
  self = true
}
```

It doesn't look like source_security_group_id needs to conflict with self - this look like it is already supported in the code.

I'm not sure if source_security_group_id and self needs to conflict with cidr_blocks. The API reference (http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html_) doesn't mention IpRanges and UserIdGroupPairs conflicting, but I don't know how this is in practice. In worst case it would mean creating 2 separate ec2.IpPermission's.

Finally the inline ingress block for aws_security_group already support multiple source security groups in the security_groups argument. It would be good if source_security_group_id did the same (or if source_security_group_ids could be added to take a list).

Happy to write a pull request if this is wanted.

**Comment by johananl** [comment]
Hi,

Any news on this one? I'm facing the same problem at the moment.

From my experience there is no problem to add both non-self security group IDs and the self security group ID on AWS. The API allows it and it works fine on the functional level, too.
Same for CIDR blocks - you can combine them with both self and non-self security group IDs.

Do you need assistance with fixing this?
