### ISSUE TITLE
TERRAFORM CRASH 

### ISSUE THREAD

**Issue by gherlein** [hashicorp/terraform#4114]
[crash.log.txt](https://github.com/hashicorp/terraform/files/47682/crash.log.txt)

**Comment by gherlein** [comment]
ran terraform on AWS t2.micro

Linux ip-172-31-42-102 4.1.10-17.31.amzn1.x86_64 #1 SMP Sat Oct 24 01:31:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gherlein** [comment]
BTW, the same example.tf file works fine from Mac OSX

**Comment by phinze** [comment]
Hi @gherlein - thanks for the report! This crash was fixed in https://github.com/hashicorp/terraform/pull/4024, which will be released in v0.6.8. We're planning to publish the release tomorrow.
