### ISSUE TITLE
Azure - possible to add Virtual Network Gateway resource

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#4116]
Hi,

As part of putting together an Azure infrastructure I've noticed that while Virtual Network, Subnets and Security Groups exists, that a Virtual Network Gateway isn't possible, this is needed if you want to set up a Point-to-Site VPN, I can create it on the GUI after or via powershell/REST but it would be handy if I could do it via Terraform.

If it gets implemented then the ability to also upload a cert and download the configuration files that the GUI allows would be very handy.

A REST version of it is visible here: https://msdn.microsoft.com/en-us/library/azure/jj154119.aspx

I posted this on google groups originally: https://groups.google.com/forum/#!topic/terraform-tool/deNB8BWpRZ0

Cheers
Dave

**Comment by davehodgson** [comment]
FYI - until this resource is added, the suggestion on https://github.com/hashicorp/terraform/issues/4141 @jen20 works well.

I expanded it a little to suite my needs - I put the null_resource into a separate file so I can essentially remove the file and run apply (destroys it) and put it back and re-run apply (re-creates it) to re-run the script. I will also in time add a second file which calls a powershell script to destroy the network gateway.

resource "azure_virtual_network" "mynetwork" {
   // arguments
}

resource "null_resource" "makevpngateway" {
    provisioner "local-exec" {
        command = "run provisioning script here"
    }
    depends_on = ["azure_virtual_network.mynetwork"]
}

Cheers
Dave

**Comment by tasquith** [comment]
+1

**Comment by aleksandrov** [comment]
+1

**Comment by wwwlicious** [comment]
+1

**Comment by eerms** [comment]
+1

**Comment by gloverc** [comment]
+1
