### ISSUE TITLE
Question: Configurable timeout for terraform apply on OpenStack

### ISSUE THREAD

**Issue by afritzler** [hashicorp/terraform#4129]
Hi,

is there a way to specify a timeout when running terraform apply against the OpenStack provider (or any other providers)?

Regards,
Andreas

**Comment by jtopjian** [comment]
Almost all OpenStack resources have a timeout, though the timeout is set pretty high. It's not configurable, at the moment, either. AFAIK, this is how other resources in other providers are configured, too.

Are you running into a resource that does not have a timeout yet? Or are you running into a situation where the timeout should be customizable?

**Comment by afritzler** [comment]
Since I'm trying to create/delete pretty big instances on OpenStack, I am sometimes running into timeout situations. So I was wondering if there is a way to overwrite the default settings. Btw. what are the default timeouts for creating/deleting instances?

**Comment by jtopjian** [comment]
Instance creation and deletion are set to 10 minutes. If the state does not change to `ACTIVE` within 10 minutes, Terraform will error / timeout.

Would you say the instances you're creating are taking longer than that? If not, you might be running into a different issue.

**Comment by nicgrayson** [comment]
I would also like this timeout to be configurable. I have some image copying that takes almost 20 minutes to run.

**Comment by jtopjian** [comment]
I'm going to go ahead and close this ticket. Per comments in #4223, configuring the timeout is probably much larger in scope than just OpenStack. If there is a specific area where you're hitting the timeout, please let me know where and I'll increase it (or submit a PR similar to #4223).

**Comment by tjlee0909** [comment]
This is slightly embarassing, but at Box we actually have an image that is so large that it takes close to an hour to provision, depending on network traffic and whether or not that particular KVM host has a cached version of the image or not.

Do you know if there are any immediate plans to support timeouts? We are currently evaluating terraform to see if it fits out requirements.

**Comment by jtopjian** [comment]
@tjlee0909 I'm going to re-open this question and investigate options.

**Comment by ZZelle** [comment]
I have exactly the same trouble: i need to import large images (>300Go) and start them on VMware and 30min is not enough to copy the VM image or to boot the 1st VM instance with this image (during 1st boot the image is copied from image service backend to compute storage)

**Comment by Fodoj** [comment]
Timeout for resising instance is also too low now.

**Comment by mattsoftware** [comment]
The timeout is also too low for me, trying to create an aws aurora cluster from a large snapshot, takes more than the 40 minutes hardcoded into the binary.

**Comment by pat610** [comment]
I have the same issue.  I'm using a custom image that takes around 25 minutes to deploy.

**Comment by fosskers** [comment]
Had this happen today with `aws_emr_cluster`. Bootstrapping my cluster takes around 45 minutes, and it seemed to hit a timeout at 40.

**Comment by mitchellh** [comment]
There is a core enhancement issue asking for configurable timeouts that we're working on. Closing this for that.

**Comment by mattsoftware** [comment]
@mitchellh does the configurable timeouts task have a github issue number we can track?

**Comment by ddelnano** [comment]
@mitchellh sorry to be annoying but would be nice to know what to follow if another issue exists.

**Comment by gburson** [comment]
I've got this problem too. Creating an Aurora cluster from a snapshot takes longer than 40 min (unfortunately!). So it times out and the whole build fails. Did anyone find a workaround?

**Comment by twelcome** [comment]
launching the larger instances on aws (r4.16xlarge, for example) also results in timeouts sometimes as these boxes take a long time to come up. Please can we have this feature?

**Comment by fosskers** [comment]
I believe this was implemented in Terraform 0.9. Resources now have `timeout { ... }` blocks.

**Comment by mitchellh** [comment]
@fosskers They have to be implemented on a per resource basis but the new APIs make it a lot easier for resource devs to do that. So it likely doesn't work yet, but its not a lot of work at all to make work now.

**Comment by twelcome** [comment]
Just got this testing with latest terraform:


Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error running plan: 4 error(s) occurred:

  * aws_instance.workstations: 1 error(s) occurred:
  * aws_instance.workstations: [ERR] Error decoding timeout: Timeout Key (create) is not supported
  * aws_instance.masters: 5 error(s) occurred:

but the documentation says:

https://www.terraform.io/docs/configuration/resources.html

**Comment by pixelicous** [comment]
I have the same issue on azurerm provider with custom script extension..

**Comment by movergan** [comment]
Need the same for vSphere. 30m is not enough for VM creation.
