### ISSUE TITLE
Switching ECS service cluster while removing previous cluster results in exception

### ISSUE THREAD

**Issue by yissachar** [hashicorp/terraform#4135]
In my Terraform file I defined an ECS cluster. I also defined an ECS service linked to that cluster. I applied the changes, and the cluster and service were created. For various reasons, at that point I decided against using my own cluster and decided to use the default ECS cluster. So I removed my cluster definition, and also removed the link from my ECS service. Trying to apply these changes resulted in the following: 

> ClusterContainsServicesException: The Cluster cannot be deleted while Services are active.

It seems the previous service was not deleted even though the cluster changed. I would have expected the following steps to take place:
1. Delete old service
2. Delete old cluster
3. Create new service on default cluster

But it seems that it jumped directly to step 2 for some reason. 

I was able to workaround this by completely removing the service definition from my Terraform file, and applying the changes, which now successfully deleted the old service and cluster. After that I re-added the service and applied again, creating the new service linked to the default ECS cluster.

**Comment by catsby** [comment]
Hello – I believe this to be fixed with fixes for detecting change in optional fields (such as `cluster` in `aws_ecs_service`
