### ISSUE TITLE
[feature request] Provisioner local-exec - allow to not wait for completion of command

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#4141]
Hi,

I'm trying to work around a requirement I have which generated: https://github.com/hashicorp/terraform/issues/4116

Essentially I am using a provisioner on the azure_virtual_network resource to call out to a batch file which runs some powershell scripts to create virtual network gateway and uploads a vpn cert to it, they work fine but it takes ages. Azure takes a very long time to create the gateway (they say 15 but it is often 30-45 mins).

The problem I have is that nothing else in my terraform scripts is dependent on the the gateway+cert creation and the terraform process could very well carry on to create the rest of the environment and leave the powershell scripts to run. Except that I cannot get the provisioner command to call the bat or ps scripts in such a way that the terraform apply command will continue.

When I look at the terminal output I can see why (I think):

azure_virtual_network.network_name: Provisioning with 'local-exec'...
azure_virtual_network.ir-virtual-network (local-exec): Executing: cmd /C "PowerShell -File ..\script_name.ps1 network-name"

The local-exec call seems to use CMD /C which as I understand it means run this command then close the window when it completes. However if the provisioner could use the START cmd /C then it would open a new window to run the command - essentially starting the bootstrap process and then carrying on with building the infrastructure.

I imagine this is a concious design decision but the request is to add a config paramer to provisioner to allow it to not wait for the command to complete if possible.

For the time being I have worked around this by creating a VM which is dependent on the virtual network and generally the last resource to be created - and used a provisioner on the VM to call the script (in case someone stumbles over this and wants a workaround)

Thanks
Dave

**Comment by davehodgson** [comment]
I came up with another way to workaround this - in the terraform provisioner I call the batch script. From the batch script I call powershell with the start command so that the batch script opens powershell then closes, the closure seems to make terraform think everything is finished and it carries on (I think).

The command from the bat file is below

START PowerShell -File "..\scriptname.ps1" <parameters here>

It would still be preferable not to have to have a bat file being called to do the above though

**Comment by jen20** [comment]
Hi @davehodgson! I'm interested in ways we could resolve this that don't involve adding things to the core of Terraform or to the provisioners. Probably in this case the best solution is to add a resource for `azure_virtual_network_gateway`, and then rely on the parallel resource creation (up to 10 at once by default I believe) to stop blocking.

There is lots of work going on to convert the Azure resources to use the newer Resource Manager API - you can track the work here: https://github.com/hashicorp/terraform/pull/3808

There is one other option you might be able to try, though it is hacky and completely unverified!

Since provisioners can apply to *any* resource, not just ones where they make sense, you could declare a `null_resource`, and make that depend on your network:

```hcl
resource "azure_virtual_network" "mynetwork" {
   // arguments
}

resource "null_resource" "makevpngateway" {
    provisioner "local-exec" {
        command = "run provisioning script here"
    }
    depends_on = ["${azure_virtual_network.mynetwork}"]
}
```

That way the creation of the VPN gateway should not block resources which are further dependent on just the network.

**Comment by davehodgson** [comment]
Hi @jen20 

The above sounds fine, I have a way around it now anyway by doing something similar to you what you suggested, I just added the provisioner to different resource that I know has to wait for various bits and pieces to build, it is always the last one to build so it now kicks off my powershell script.

I agree, the best solution to my specific issue  #4116 would be to have the azure_network_gateway as a resource in its own right, if doing that, then also having the azure_network_root_certificate resource would be handy as well (you can have multiple per single gateway).

This suggestion is really that it would be nice to kick off a process from a provisioner without it waiting but I managed to get it to do that with a batch file running a start command to powershell.

I have no strong (or experience based) preference for how it is best to achieve it as I am still new to the product, just that I would like the option personally so thought I'd flag it.

Cheers

Dave

**Comment by pkolyvas** [comment]
I’m doing a clean-up of older issues that haven’t gained traction but also don’t coincide with our current focus and near term plans. While provisioners, as a whole, aren’t a top priority for the team, when some time is available to focus on them we’re going to use that attention to tackle some long-standing defects.

We are also thinking about how to evolve provisioning for many of our community’s use cases but have yet to take a firm decision on the direction that work will take.

We appreciate every idea and contribution to Terraform, even if we can't get to them all. My door is always open to talk about Terraform both present and future.
