### ISSUE TITLE
Better error message when VPC can't be created due to permissions

### ISSUE THREAD

**Issue by alex** [hashicorp/terraform#4142]
```
* aws_vpc.main: Error creating VPC: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id:
* aws_launch_configuration.ecs: Error creating launch configuration: AccessDenied: User: arn:aws:iam::REDACTED is not authorized to perform: autoscaling:CreateLaunchConfiguration
```

The `aws_launch_configuration.ecs` error message is great, the `aws_vpc.main` is less great, if it mentioned the missing permission, that would be huge.

**Comment by jen20** [comment]
Hi @alex! Thanks for opening the issue. Unfortunately we're somewhat beholden to the error messages returned by the AWS API itself, which are better or worse depending on the service in question. Currently we don't have any plans to go through and re-write them, as this would be a huge undertaking. I'll close this issue for now as a "can't fix", but if we decide to come back to it at some point in the future I'll be sure to make a note here.

Another option which might be more viable at this stage is to report this to the `aws-sdk-go` project to see if it's an issue they're interested in tackling.

**Comment by alex** [comment]
Welp. That's sort of what I was afraid of. Thanks for taking a look.

**Comment by ephemeral** [comment]
I share your pain @alex
