### ISSUE TITLE
Make Tainted destroys show up in plan and applies as such

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#4156]
We had a heck of a time figuring out what happened over in https://github.com/hashicorp/terraform/issues/4040 because Terraform's current behavior in cleaning up Tainted resources is nearly silent.

It showed up as just a stray destroy in a subsequent apply. We should output tainted resource destroys in plans and notate them in applies.

**Comment by joslynesser** [comment]
Nice find :+1: We're having to run apply without using a plan file to destroy manually tainted resources, which is definitely scary (as we prefer to apply a guaranteed, reviewed plan file)

**Comment by dangerp** [comment]
+1 there is a lot of confusion and some subtle bugs that pop up when terraform is taking actions that weren't specified in the plan file.

**Comment by ashb** [comment]
This bit me just now - i ran:

```
terraform taint aws_autoscaling_group.nginx_fe_green
terraform taint aws_autoscaling_group.nginx_fe_blue
terraform plan -out plan-file -target aws_autoscaling_group.nginx_fe_blue
```

At this point the plan showed nothing to the green ASG, so I went ahead and `terraform apply plan-file` -- and was quite surprised when it destroyed the green ASG as well as the blue one shown in the plan!

**Comment by ashb** [comment]
A possible related issue here is that `plan -target` doesn't limit things to targeted resource or their dependencies. Should I raise a separate issue for that?

**Comment by phinze** [comment]
This is done in #6600! Tainted resources will behave much more predictably in 0.7. 👍
