### ISSUE TITLE
null-resource provisioner fails with "diffs didn't match during apply."

### ISSUE THREAD

**Issue by satvidh** [hashicorp/terraform#4164]
I removed a trigger that existed in dw-generate-redshift-json.tf(.txt to allow github to attach the file), which I created as a test of the null_resource. I generated the plan with the new configuration. Then the following command failed with the "diffs didn't match during apply" error.

terraform apply aws.plan 

[dw-generate-redshift-json.tf.txt](https://github.com/hashicorp/terraform/files/51992/dw-generate-redshift-json.tf.txt)
[trace.txt](https://github.com/hashicorp/terraform/files/51988/trace.txt)

**Comment by mitchellh** [comment]
I can't reproduce this anymore so I think it was fixed at some point. If you can still reproduce this please open a new issue with repro steps. Thanks!
