### ISSUE TITLE
PowerDNS provider

### ISSUE THREAD

**Issue by alkersan** [hashicorp/terraform#4171]
Terraform includes `DNSimple` and `DNSMadeEasy` providers, along with those available from PaaS operators (AWS Route53, DO, etc...), but all those are paid services. I think that provider for self-hosted DNS server will be a good option for teams and organizations that by some reasons operate solely on in-house platforms, like `Openstack`

PowerDNS has [HTTP API](https://doc.powerdns.com/md/httpapi/api_spec/), which allows CRUD on `Zones` and `Records`. I have a simple terraform provider for records manipulation. Is there any interest for making such provider a part of terraform? I would gladly made a contribution to terraform development.

**Comment by jen20** [comment]
Hi @alkersan! Thanks for opening this issue! We would definitely be interested in having built-in support for PowerDNS, and if already have a provider then that's even better. Please feel free to open a pull request with your work, or if you have questions prior to that please drop them here and one of the Terraform team will try to help with it.

**Comment by stack72** [comment]
There is a Go client for PowerDNS - https://github.com/waynz0r/powerdns - but there is no documentation on it :(

**Comment by jen20** [comment]
Merged in #4885. Thanks @alkersan!
