### ISSUE TITLE
[azure] Parameterised name in 0.6.6 results in a warning about error in version 0.4 for azure_storage_service

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#4172]
I'm trying to build a scripted environment I can run up several times using a different prefix on the resources.

It appears to work ok, except that I get a warning when I run terraform plan that an error will be generated in terraform 0.4 (and I presume later versions) but no error is generated. Not sure if it should error or the warning shouldn't appear.

I've split the script out into three files, I haven't uploaded the tfvars due it having some sensitive config in it, but I do have the line below in that file:

azure_prefix="CLIENTNAME"

[0.3_Terraform.zip.txt](https://github.com/hashicorp/terraform/files/52920/0.3_Terraform.zip.txt)

Zip file is giving an error so the file upload has an extension of txt but is a zip.

There message I get when I run terraform plan is:

Warnings:
- azure_storage_service.${var.azure_prefix}Store01: ${var.azure_prefix}Store01: resource name can only contain letters, numbers, dashes, and underscores.
  This will be an error in Terraform 0.4

No errors found. Continuing with 1 warning(s).

However when I look at what would be created the name is interpolated correctly.

**Comment by davehodgson** [comment]
I note that by design terraform resource names are not meant to be parameterised so when I leave to parameter in the name field of the resource but the resource name itself just changed to store01 it completes fine.

So this issue is only that the warning message is misleading, its either and error or it doesn't need to be displayed given the version is higher than 0.4

**Comment by jen20** [comment]
Hi @davehodgson! Thanks for opening the issue. If I'm following correctly, you have something like this:

```hcl
resource "azure_something" "${var.prefix}_restofresourcename" {
    //arguments
}
```

Am I following correctly?

**Comment by davehodgson** [comment]
Hi @jen20 ,

Yep - sorry I realised after I logged it that I had:

1: resource "azure_something" "${var.prefix}_restofresourcename" {
2:    name="${var.prefix}_restofname" 
3: }

I mistook the error message for being in relation to line 2 rather than the terraform resource name in line 1.

After I realised that I found another issue stating that is a design decision, so the issue is only that it I generates a warning that is misleading and probably should generate an error instead
