### ISSUE TITLE
Trying to create multiple azure_instance inside the same cloud service fails

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#4175]
If I try and create three azure_instance resources with the same azure_hosted_service (cloud service in Azure) the first one creates ok and the next two fail:
- azure_instance.adds01: Error creating instance PREFIX-adds01: Error response from Azure. Code: ConflictError, Message: The specified deployment slot Production is occupied.
- azure_instance.rdsh01: Error creating instance PREFIX-rdsh01: Error response from Azure. Code: ConflictError, Message: The specified deployment slot Production is occupied.

I think this behaviour appears to be the same as below:
- https://github.com/Azure/azure-sdk-for-python/issues/362

I can create a second VM through the portal with the same cloud service so it looks like a bug, reasonably well explained in the link above

**Comment by elmalto** [comment]
Is there a fix for this? I saw a pull request which does not compile and after fixing the compile bugs unfortunately does not fix the issue.
