### ISSUE TITLE
Google Cloud DNS, can't set up MX record

### ISSUE THREAD

**Issue by vorlock** [hashicorp/terraform#4187]
In current version (0.6.8) google_dns_record_set is not capable of setting up MX record.

**Comment by lwander** [comment]
Could you elaborate? I'm pretty sure you can set the [type](https://www.terraform.io/docs/providers/google/r/dns_record_set.html#type) attribute to `MX`.

**Comment by vorlock** [comment]
Hi @lwander ,

did you actually try it?
My tries failed, so can you please explain to me what did you put into `name` and `rrdatas` fields?

**Comment by lwander** [comment]
What do you mean by fail? I used the following definition

```

resource "google_dns_managed_zone" "default" {
    name = "terraform-zone-1"
    dns_name = "mail.example.com."
    description = "hi" 
}

resource "google_dns_record_set" "mail" {
    managed_zone = "${google_dns_managed_zone.default.name}"
    name = "${google_dns_managed_zone.default.dns_name}"
    type = "MX"
    ttl = 86400
    rrdatas = ["10 ${google_dns_managed_zone.default.dns_name}"]
}
```

**Comment by vorlock** [comment]
@lwander thx a lof for your example which highlighted to me where I made an error.

There is nothing wrong with terraform in relation to this issue, thus I'm closing it.

**Comment by lwander** [comment]
@vorlock, no problem, good luck!
