### ISSUE TITLE
Support streams attributes on aws_dynamodb_table

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#4188]
From a [mailinglist thread](https://groups.google.com/d/msgid/terraform-tool/c2e2979c-bf43-49c5-b36f-208719e60ecb%40googlegroups.com), we learned that Terraform cannot yet enable streams on DynamoDB tables.

Should be pretty straightforward to add - it's the two fields under `StreamSpecification` here:

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html

In Terraform it could probably just be `stream_enabled` and `stream_view_type`.

**Comment by stack72** [comment]
@phinze I have a PR in the making for this right now. Just about to get on a flight so will open the PR in the morning when i arrive in London again

**Comment by phinze** [comment]
Just merged - thanks @stack72!
