### ISSUE TITLE
Scheduling Hints Examples for Instances on Open Stack

### ISSUE THREAD

**Issue by afritzler** [hashicorp/terraform#4191]
Hi,

are there any examples out there on how to use the scheduling hints block for the OpenStack provider? https://terraform.io/docs/providers/openstack/r/compute_instance_v2.html#scheduler_hints

e.g. how to use the `target_cell` attribute etc.

Regards,
Andreas

**Comment by jtopjian** [comment]
The `scheduling_hints` block is configured just like any other block. A common pattern is:

```hcl
resource "openstack_compute_servergroup_v2" "my_servergroup" {
  name = "my_servergroup"
  policies = ["anti-affinity"]
}

resource "openstack_compute_instance_v2" "my_instance" {
  ...
    scheduler_hints {
    group = "${openstack_compute_servergroup_v2.my_servergroup.id}"
  }
}
```

The target cell attribute, AFAIK, just takes the name of a Cell:

```hcl
scheduler_hints {
  target_cell = "cell_name"
}
```

In order for that to work, though, I'd imagine the Cell Filter would need enabled in Nova. It looks to be [undocumented](http://docs.openstack.org/developer/nova/filter_scheduler.html), but the code [references](https://github.com/openstack/nova/blob/master/nova/cells/filters/target_cell.py) it.

Hope that helps!

**Comment by afritzler** [comment]
@jtopjian that was very helpful! Thanks a lot!
