### ISSUE TITLE
Should complain about duplicate assignments in an overrides file

### ISSUE THREAD

**Issue by ericpromislow** [hashicorp/terraform#4201]
In an overrides file I had two assignments to a variable called "openstack_keypair"

The second one was correct, but there was an earlier assignment to the same
variable name with an invalid value due to copy-and-paste.  TF errored out
with a message "Invalid key_name provided".  There is no variable called "key_name",
which is probably a second issue.  Instead, it would be better if TF at least
gave warnings when it encounters multiple assignments *in override files*.  (It totally
makes sense to allow multiple assignments in variable values, with, you hope,the last
assignment winning.)

**Comment by mitchellh** [comment]
Hm, I'm actually not sure if this is something we want. I absolutely understand your reasoning, and it is sound, but I also have realistic counterpoints: some people _append_ to an override file (with code) specifically to override previously set values in the override file. 

I think this might make sense for a future `terraform lint` style command. That isn't under development nor is it planned short term. It might make sense as a 3rd party thing for now. 

Given this, I'm going to reject this change for now. We can rethink it one day but I think the behavior right now is okay.
