### ISSUE TITLE
Update terraform docs for hidden `aws_db_instance` parameters

### ISSUE THREAD

**Issue by sahilsk** [hashicorp/terraform#4205]
Hi,
i had a hard time finding following two parameters in the docs. Can you guys add them on your official docs?

- auto_minor_version_upgrade
- allow_major_version_upgrade

source: https://github.com/hashicorp/terraform/blob/c262bc72ea7df450e295f4c14a86760b1f67770b/builtin/providers/aws/resource_aws_db_instance.go#L247-L253

```

			"auto_minor_version_upgrade": &schema.Schema{
				Type:     schema.TypeBool,
				Optional: true,
				Default:  true,
			},

			"allow_major_version_upgrade": &schema.Schema{
				Type:     schema.TypeBool,
				Computed: false,
				Optional: true,
			},
```

I don't know what's the right place to update those docs. Perhaps this: 

docs:
https://github.com/hashicorp/terraform/blob/c262bc72ea7df450e295f4c14a86760b1f67770b/website/source/docs/providers/aws/r/db_instance.html.markdown

**Comment by catsby** [comment]
Hey @sahilsk sorry for the trouble; a patch has been sent and merged, I'll get those docs updated!

**Comment by sahilsk** [comment]
Please don't be sorry. 
Immense thanks for writing this wonderful tool. 

Also, many thanks for your prompt action. (:

**Comment by catsby** [comment]
The website has been updated, thanks for notifying us :)
