### ISSUE TITLE
Crash when Terraform receives an EC2 GetUser response to a RunInstances request

### ISSUE THREAD

**Issue by michaelstorm** [hashicorp/terraform#4206]
Version: 0.6.8
[crash.log](https://github.com/hashicorp/terraform/files/55171/crash.txt) is attached.
Looks similar to #562.

I'm creating a proxy server for the AWS API that I'm testing by running Terraform against it. I accidentally left code in the proxy that makes a `GetUser` request to AWS when it receives a `RunInstances` request. As it turns out, feeding Terraform a `GetUser` response when it's expecting a `RunInstances` response causes a hard crash.

This is a pretty weird edge case, but the crash message said, "This is always indicative of a bug within Terraform," and asks the user to report it. So I figured I'd let you know.

.tf file:
```
provider "aws" {
    access_key = "<REMOVED>"
    secret_key = "<REMOVED>"
    region = "us-east-1"
}

resource "aws_instance" "example" {
    ami = "ami-408c7f28"
    instance_type = "t1.micro"
}
```

`GetUser` response erroneously returned to `RunInstances` request:
```
<GetUserResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/"><GetUserResult><User><PasswordLastUsed>2015-12-08T08:24:34Z</PasswordLastUsed><Arn>arn:aws:iam::671861320306:root</Arn><CreateDate>2011-05-12T17:51:24Z</CreateDate><UserId>671861320306</UserId></User></GetUserResult><ResponseMetadata><RequestId>b894d528-9d89-11e5-975f-83c19f09b1ae</RequestId></ResponseMetadata></GetUserResponse>
```

*EDIT:* Looks like simply returning an empty HTTP response body causes the same crash.

Steps to reproduce are, broadly, "Have Terraform make `RunInstances` request. Return `GetUser` response instead." It's probably a bit easier to accomplish within the test framework than it would be to actually stand up a proxy server, but if it isn't, let me know.

**Comment by catsby** [comment]
Thanks @michaelstorm – I've patched this by checking the length of the `Instances` that we're expecting.
