### ISSUE TITLE
Split terraform state when storing in Consul

### ISSUE THREAD

**Issue by hexedpackets** [hashicorp/terraform#4213]
Currently a Consul key is limited to 512KB. It seems reasonable to have state files grow much larger than that - mine is currently 740KB and I don't consider it particularly large or complex. This makes Consul unusable for remote configuration storage of any larger projects.

One possible solution would be to split the state across multiple keys under a common prefix. This could be done in such a way that each key could be independently updated without recombining everything and would allow storing arbitrarily large terraform states in Consul.

**Comment by mitchellh** [comment]
I'm open to this idea if someone wants to implement it, but it isn't something that we're planning at the moment.

**Comment by dejonghe** [comment]
If anyone finds this and is looking to patch the issue for now make sure you're gziping your backend state: https://github.com/hashicorp/terraform/issues/8491
