### ISSUE TITLE
Crash while applying plan

### ISSUE THREAD

**Issue by samprakos** [hashicorp/terraform#4219]
![image](https://cloud.githubusercontent.com/assets/10929689/11664719/52ad3a12-9db1-11e5-991a-0c8ef495ab21.png)

See attached crash log.  This is with the latest terraform version from github.  I will add (not sure it applies) that every time I apply, I get a bunch of these type messages:

* aws_security_group_rule.inbound_nginx_consului: [WARN] A duplicate Security Group rule was found. This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: 24.97.254.210/32, TCP, from port: 8500, to port: 8500, ALLOW" already exists
2015/12/08 13:38:16 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

**Comment by jen20** [comment]
Hi @samprakos! It looks like the attachment here is the icon for the file rather than the file itself? :-)

**Comment by samprakos** [comment]
Let's try this again :)

[crash.txt](https://github.com/hashicorp/terraform/files/56827/crash.txt)

**Comment by catsby** [comment]
Hey @samprakos – can you give me some background on how you hit this bug? An example configuration that demonstrates the problem would be super helpful as well. From the crashlog it _seems_ related to a `cidr_block` (or missing `cidr_block`).

**Comment by catsby** [comment]
(maybe related to https://github.com/hashicorp/terraform/issues/2310 where `cidr_blocks` has a trailing empty item `""`)

**Comment by catsby** [comment]
The duplicate warning indicates you may need to manually clean up a record, due to an old bug that has since been patched, but requires manual clean up :frowning: 

Some details on that here:

- https://github.com/hashicorp/terraform/pull/2376

**Comment by samprakos** [comment]
Ah...yes I had a variable that wasn't populated....so with rules like below, the cidr_block ended up being blank:

```json
resource "aws_security_group_rule" "inbound_api_encompass" {
  security_group_id = "${aws_security_group.api.id}"

  type = "ingress"
  from_port = 8001
  to_port = 8001
  protocol = "tcp"
  cidr_blocks = [
    "${split(",", var.encompass_vpn)}"
  ]
}

```

**Comment by catsby** [comment]
Sorry for the trouble @samprakos, thanks for following up :smile:
