### ISSUE TITLE
Unable to determine Google CloudSQL IP address

### ISSUE THREAD

**Issue by coreone** [hashicorp/terraform#4220]
I am trying to use the new Google CloudSQL resource in Terraform, and one of the things I would like to be able to do is use its IP to generate a DNS record (using Terraform).  I attempted to do this using something like:

```
resource "google_dns_record_set" "mysql" {
    managed_zone = "${google_dns_managed_zone.zone.name}"
    name = "consent.${google_dns_managed_zone.zone.dns_name}"
    type = "A"
    ttl = "${var.dns_ttl}"
    rrdatas = ["${google_sql_database_instance.mysql.0.address}"]
}
```

However, I could not find an `address` field, or any other field that could potentially be its IPv4 address.  I even looked through the `terraform.tfstate` file to see if I could find anything, but nothing seemed to be in there either.  Is there a field in there that `google_sql_database_instance` resource record that has the IP address, or is this information not retrieved from the Google API?  If it's not included in the record, is there a way that it **could** be included, since it would be very helpful for use in other parts of the project (firewall rules, DNS, etc.)

Thank you!

**Comment by lwander** [comment]
@coreone, looks like the [v1beta4 API](https://cloud.google.com/sql/docs/admin-api/v1beta4/instances#ipAddresses) changed since I added this resource. It now supports an ipAddress field which I'll add once I get the chance.

**Comment by lwander** [comment]
See #5245
