### ISSUE TITLE
Terraform errors with directory space. 

### ISSUE THREAD

**Issue by Btlyons1** [hashicorp/terraform#4224]
I experienced problems with terraform commands due to a space in my parent directory name. Terraform get took 15-20 mins to run, while switching back and forth between hosts and keypair. Additionally, the terraform plan command outputted an error that stated it could not locate keypair_name. 

<img width="575" alt="screen shot 2015-12-08 at 2 27 30 pm" src="https://cloud.githubusercontent.com/assets/9876419/11670639/f82aa050-9db7-11e5-97ea-04a843b7311c.png">

**Comment by jen20** [comment]
Hi @Btlyons1 - could you post a configuration demonstrating this? I have tried replicating it with a variety of resource with spaces in the paths, but couldn't.

**Comment by kenjones-cisco** [comment]
He was using the Openstack version within https://github.com/CiscoCloud/microservices-infrastructure/tree/0.5.0/terraform to stand up an instance of Mantl.

**Comment by mitchellh** [comment]
This should be fixed now!

**Comment by mitchellh** [comment]
For reference it was #8462 that fixed this
