### ISSUE TITLE
Cloud-init multipart template resource

### ISSUE THREAD

**Issue by grepnull** [hashicorp/terraform#4225]
For complex cloud-init setups, its multipart [support](https://help.ubuntu.com/community/CloudInit) comes in handy. They have an example [write-mime-multipart](http://bazaar.launchpad.net/~cloud-utils-dev/cloud-utils/trunk/view/head:/bin/write-mime-multipart) script that takes a list of cloud-init files and merges them appropriately into multipart mime format.

It would be great to add a resource to so that you could something along the lines of
```
resource "cloud_init_multipart" "multipart" {
  contents = ["${template_file.foo.rendered}","${template_file.bar.rendered}"]
}
```
This would take the rendered output of the 2 different cloud-init files, foo and bar, and equivalently to the write-mime-multipart script above would detect their mime-types and render multipart mime content. It could then be referenced as `${cloud_init_multipart.multipart.rendered}` to be passed on to `user_data`

I think it would make the most sense to add this to the template provider.

**Comment by apparentlymart** [comment]
Thanks for the suggestion... this is already being worked on in #4095! :grinning:

**Comment by grepnull** [comment]
Great! I missed that in my search, thanks!
