### ISSUE TITLE
Change on port does not follow lifecycle of services

### ISSUE THREAD

**Issue by cordoval** [hashicorp/terraform#4227]
after updating the port mappings on my task definition and changed the port for my elb then i get this error after a terraform apply even though terraform plan passed.

```bash
* aws_ecs_service.test-http: InvalidParameterException: The container test-http did not have a container port 3333 defined.
	status code: 400, request id: 31637559-9e1d-11e5-af18-8d60ba3f3e52
```

**Comment by catsby** [comment]
Hey @cordoval – do you by chance have an example config that I could use to reproduce this? What did the `plan` phase show, did it correctly show a change in both the ELB and the Task Definition?

**Comment by cordoval** [comment]
@catsby I grabbed https://github.com/alex/ecs-terraform and just change the port mappings on the .json file for the task definition

**Comment by yissachar** [comment]
I am seeing this issue as well. I'm forced to create a new service if I want to change the port numbers on the container.

**Comment by radeksimko** [comment]
Reproduced, see #4366
