### ISSUE TITLE
Aliyun provider

### ISSUE THREAD

**Issue by flozano** [hashicorp/terraform#423]
It would be great to have an aliyun (alibaba's cloud) provider.

**Comment by phinze** [comment]
We'd happily review a PR w/ Aliyun support, but I'm going to close this issue for now since we have no plans to pick up this work internally.

**Comment by Ehekatl** [comment]
@phinze @mitchellh Aliyun now have global version and growing very fast, since it's the only cloud provider which truly connected worldwide ( the only one can directly connect China and other with other region) It would be great if you could consider reopen this issue

**Comment by flozano** [comment]
Maybe it should be aliyun who provided a PR for this, if they're interested?

**Comment by steve-mushero** [comment]
We at ChinaNetCloud here in Shanghai are willing to build this as we are a big Aliyun partner, though we are new to Terraform (and Go) and may need some help, though it looks straightforward enough and Aliyun's APIs are very close to AWS in most cases.  Anyone who has any experience adding IaaS providers please message us or drop a note to me and we can provide docs and developers (as Aliyun mostly in Chinese).

**Comment by bittopaz** [comment]
Aliyun officially creates a repo for this. https://github.com/alibaba/terraform-provider
