### ISSUE TITLE
Reduce TF release binaries size (UPX compression)

### ISSUE THREAD

**Issue by mtekel** [hashicorp/terraform#4233]
Hi,

current (0.6.8) TF release size is about 120MB zip and about 500MB after decompression (linux x64 release). This is quite a lot, especially when you want to, for example, create some lean container that contains terraform. The go binaries are statically linked and are quite big in size. 

To reduce this size, we used  [goupx](https://github.com/pwaller/goupx) + [upx](http://upx.sourceforge.net/). The average compression ratio is same as zip. The compressed binaries together were ~110MB. The zipped release then around 100MB. This is considerable reduction. We have not had any issues with the compressed binaries yet. UPX supports compression for many other binary formats, like windows. The compression is also fast, only ~2-3 times slower than zip.

Could you perhaps make this default and start distributing releases that contain UPX compressed binaries? The size reduction is really considerable and it enables to run terraform on various constrained platforms like containers.

**Comment by jen20** [comment]
Hi @mtekel. Thanks for the suggestion and for validating the idea - I'll experiment over the coming days. Another thing we have considered is merging some of the built in providers into a single binary in a similar manner to [the work done in Packer](https://github.com/mitchellh/packer/pull/2608).

**Comment by mtekel** [comment]
That would be great as well. And the both approaches can be combined...

**Comment by MaikuMori** [comment]
Why is the binary so huge in the first place? It's a command-line tool after all. There are plenty full blown graphical games with assets which are smaller than terraform binary. Heck at 500mb you can get fully working OS image.

**Comment by tiaguin12342** [comment]
+1
is there some plan when this enhancement will be implemented?
we want to use terraform in our images but, terraform make them so huge.

**Comment by stack72** [comment]
hi @mtekel 

Apologies for not getting back to you in a long time on this. For 0.7, we have made a change and have packaged all binaries together for terraform and also reduced it's size

the size of the binary is now approx 143MB uncompressed. This is a drastic improvement

Hope this helps

Paul

**Comment by mtekel** [comment]
Hi @stack72,

indeed it is an improvement, but in our container we are [only including the providers that we use](https://github.com/alphagov/paas-docker-cloudfoundry-tools/blob/e133b3f5762adb5cae14f023e521aa4cc1c8231d/terraform/Dockerfile). That reduced size to 134MB already. If we now have to use 143MB file, that's a regression for us. Nevertheless, UPX can still be used against this new binary. In our previous test we have seen compression ratio of around 70%, which is quite a lot...

I am not sure what's the community stance to UPX - if there are use cases where it would be undesirable or breaking anything. I think it should be OK to use though. Then this git issue would be only about adding UPX compression step to your release pipeline...

And as such, perhaps it could be re-opened?

**Comment by stack72** [comment]
Hi @mtekel - reopening as requested :)

**Comment by mtekel** [comment]
I see that TF 0.7.3 release is now 65MB, which is nice reduction from what it originally was. Perhaps UPX could still be applied to this, but it's not as necessary as before...

**Comment by jen20** [comment]
@mtekel Terraform 0.7.3 is compiled using Go 1.7.0, so benefited from reduced binary size without any work on our part. Sadly applying UPX compression does not look like it would be so straightforward - not least, it doesn't have releases for all of the platforms we support, so we would have divergence in the build pipeline. If this comes as a (portable) pull request we could consider merging it, but I think it's safe to say the core team is unlikely to be spending any time here. Consequently it's probably time to close this issue again - thanks for the interesting idea though!
