### ISSUE TITLE
Dyn provider docs exist but aren't on the website

### ISSUE THREAD

**Issue by daveadams** [hashicorp/terraform#4237]
Dyn provider docs exist (https://github.com/hashicorp/terraform/tree/master/website/source/docs/providers/dyn) and are even rendered (https://terraform.io/docs/providers/dyn/) but they aren't linked in the sidebar of the providers docs (and the rendered version looks like it has some bad CSS or something).

**Comment by catsby** [comment]
Fixed in #4238 , sorry about that!

**Comment by catsby** [comment]
Deployed, docs are live not https://terraform.io/docs/providers/index.html
