### ISSUE TITLE
Lookup of AMIs by region in atlas_artifact ?

### ISSUE THREAD

**Issue by steve-jansen** [hashicorp/terraform#4239]
Hi Hashicorp,

Following up on #2731, how does one lookup an atlas_artifact AMI by AWS region?  

@ravbaba posted in #732:

```
ami = "${lookup(atlas_artifact.mesos-master.metadata_full, concat("region-", var.region))}"
```

But this raises an error like:

```
Error running plan: 1 error(s) occurred:

* lookup: lookup in 'B780EEEC-B661-4EB8-8236-A01737AD98B6' failed to find 'region.us-east-1' in:

${lookup(atlas_artifact.mesos-master.metadata_full, concat("region.", var.region))}
```

Is Atlas/AMI lookup possible via some other means now?

Cheers,
Steve

**Comment by pstengel** [comment]
This is the work-around I'm using currently:

```
resource "aws_instance" "controller" {
  ami = "${element(split(",", atlas_artifact.controller.metadata_full.ami_id), index(split(",", atlas_artifact.controller.metadata_full.region), var.region))}"
  ...
```

It's long and ugly and we definitely need a better way, but it works for now. :smile:

**Comment by stack72** [comment]
Hi @steve-jansen 

Sorry this has taken so long to reply to - there is a backlog of issues that I am working my way through right now. Can you have a look and tell me if the new `data_sources` work will help here?

https://github.com/hashicorp/terraform/blob/master/website/source/docs/providers/atlas/d/artifact.html.markdown

This is already available in [0.7.0-RC3](https://releases.hashicorp.com/terraform/0.7.0-rc3/)

thanks

Paul

**Comment by steve-jansen** [comment]
Hi @stack72 

No worries, we found ways to workaround the challenge here, which includes #7365.

The `data_sources` are great.  Not sure they solve this specific issue here, which is that `metadata_full` doesn't seem to behave like a proper map, which breaks the `lookup` function when trying to lookup an AMI by region.

Cheers,
Steve

**Comment by mootpt** [comment]
@steve-jansen 

I have some success with:


```
variable "region" { default = "us-east-1" }

data "atlas_artifact" "foo" {
        name          = "ptr/foo"
        type          = "amazon.ami"
}

output "ami_id" {
        value = "${lookup(data.atlas_artifact.foo.metadata_full, "region-${var.region}")}"
}
```

but maybe I am missing the requirements? Why the use of concat? Concat no longer works with strings, just lists.

**Comment by steve-jansen** [comment]
@mootpt looks great!  Thanks for sharing.  Closing this issue.

🍻
