### ISSUE TITLE
Tags not set when recreating aws_instance

### ISSUE THREAD

**Issue by mahnve** [hashicorp/terraform#424]
When creating an aws_instance, tags gets set as specified. However, when the plan calls for destruction and recreation, tags aren't set. 
```
resource "aws_instance" "cyclops-1a" {
  count=2
  ami="ami-xxx"
  instance_type="t2.medium"
  subnet_id="${aws_subnet.app-1a.id}"
  security_groups=["..."]
  key_name="..."
  associate_public_ip_address="true"
  tags {
    app="dryleaf"
    role="cyclops"
    Name="dryleaf-cyclops-1a"
  }
}
```

**Comment by catsby** [comment]
Thanks again for reporting this; sorry for the silence! 
This is fixed in the master branch (and maybe fixed in 0.3.7 for that matter :smile: )
