### ISSUE TITLE
Terraform crashed when there was network outage during installation

### ISSUE THREAD

**Issue by subbu05** [hashicorp/terraform#4248]
During installation when network outage happened
[log.gz](https://github.com/hashicorp/terraform/files/58660/log.gz)

 terraform crashed.

version: Tried with 0.5.3 and 0.6.6

**Comment by catsby** [comment]
Hey @subbu05 – forgive me for being hesitant to open gzipped files from the internet, could you please let me know that if this was a `panic`, what the information in the preceding and following few lines had? Typically it gives a clue to the nature of the panic, and the file where it likely hit.

Thanks!

**Comment by phinze** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
2015/12/09 17:48:47 terraform-provider-aws: [signal 0xb code=0x1 addr=0x10 pc=0x1330f6]
2015/12/09 17:48:47 terraform-provider-aws: 
2015/12/09 17:48:47 terraform-provider-aws: goroutine 58 [running]:
2015/12/09 17:48:47 terraform-provider-aws: github.com/awslabs/aws-sdk-go/aws.ValidateResponseHandler(0xc20815e000)
2015/12/09 17:48:47 terraform-provider-aws: 	/opt/gopath/src/github.com/awslabs/aws-sdk-go/aws/handler_functions.go:91 +0x26
2015/12/09 17:48:47 terraform-provider-aws: github.com/awslabs/aws-sdk-go/aws.(*HandlerList).Run(0xc20815e068, 0xc20815e000)
```

Re-filed this upstream w/ aws-sdk-go https://github.com/aws/aws-sdk-go/issues/468, thanks!

**Comment by phinze** [comment]
@subbu05 based on conversation in upstream issue - it looks like you hit an issue with aws-sdk-go which should no longer be a problem - feel free to follow up if you can reproduce this with Terraform 0.6.8, which should have a version of aws-sdk-go with the fix! :+1:
