### ISSUE TITLE
Failed to using template_file for building dynamic members

### ISSUE THREAD

**Issue by sifizeng** [hashicorp/terraform#4252]
Guys, we all know that the openstack_lb_pool_v1 can not dynamic creating  member  depends on the number of instance, so I try to use template file to build the member.
Here is my code 

```
resource "openstack_lb_pool_v1" "pool_1" {
count="${var.count}"
name="test_testing_lb_pool"
 region = "${lookup(var.defaults, "region")}"
protocol="HTTP"
subnet_id="${lookup(var.defaults,"lbaas_subnet")}"
lb_method = "ROUND_ROBIN"

  member {"${element(template_file.members.*.rendered,count.index)}"}
}

resource "template_file" "members" {
count ="${var.count}"
template = "${file("templates/members.tpl")}"

vars {
region = "${lookup(var.defaults, "region")}"
address="${element(openstack_compute_instance_v2.compute_worker.*.access_ip_v4, count.index)}"
port = 80
admin_state_up = "true"
}
}
```

but when I run terraform plan, the output is like 

>←[31mErrors:
←[0m←[0m
←[31m  * openstack_lb_pool_v1.pool_1 #0: "member.0.address": required field is not set←[0m←[0m
←[31m  * openstack_lb_pool_v1.pool_1 #0: "member.0.port": required field is not set←[0m←[0m
←[31m  * openstack_lb_pool_v1.pool_1 #0: "member.0.admin_state_up": required field is not set←[0m←[0m
←[31m  * openstack_lb_pool_v1.pool_1 #1: "member.0.address": required field is not set←[0m←[0m
←[31m  * openstack_lb_pool_v1.pool_1 #1: "member.0.port": required field is not set←[0m←[0m
←[31m  * openstack_lb_pool_v1.pool_1 #1: "member.0.admin_state_up": required field is not set←[0m←[0m

Any ideas?

**Comment by jen20** [comment]
Hi @sifizeng. I think the issue here is that the template is producing a string, but the load balancer wants a structure. I don't think it will be a suitable solution to use templates here. Is there a known issue you are referring to with no being able to refer to a resource with a count in the load balancer configuration? This seems like the underlying issue to fix there.

**Comment by jtopjian** [comment]
@jen20 ah, I think @sifizeng is referring to #3197. This is something I'll be working on shortly.

**Comment by sifizeng** [comment]
Hi @jtopjian   I saw your comment in #3197  That`s why I thought I should use template_file  to build a thing like your rough example shows.

**Comment by sifizeng** [comment]
@jen20   you are right. seems like template_file only can be injected to the string.

**Comment by jtopjian** [comment]
@sifizeng Check out #4359 - it has a draft of the `openstack_lb_member_v1` resource. :smile:

**Comment by jtopjian** [comment]
@sifizeng Would you consider this issue "resolved"?

**Comment by catsby** [comment]
Hey all – I'm going to go ahead and close this issue for now. Please let me know if there's more work required here.

Thanks!
