### ISSUE TITLE
Subsequent run of chef provisioner on a converged instance fails

### ISSUE THREAD

**Issue by lhagemann** [hashicorp/terraform#4262]
Terraform v0.6.8

Attempting to update the chef run_list on a node which has already had the first run of a chef client fails with `* Uploading validation.pem failed: scp: /etc/chef/validation.pem: Permission denied`

I have an aws_instance which was provisioned by terraform_chef_provisioner, if I want to update the run_list, and have that applied to the chef client, I receive the failure above. 

Terraform module is defined with an `aws_instance` resource & a `null_resource` for the chef provisioner which is triggered off `aws_instance.NAME.id`.

First attempt I tried tainting the `aws_resource` and running `apply` again, this triggered issue #649, as the instance was destroyed, and the subesquent run failed due to the node & client already existing on the chef server.

Second attempt: I tainted the `null_resource` followed by `plan` and `apply` which fails with the error above. 
[example.lhagemann.tf.tar.zip](https://github.com/hashicorp/terraform/files/59541/example.lhagemann.tf.tar.zip)

Full Output

```
$ tf apply
null_resource.NAME: Refreshing state... (ID: 5285253368098350675)
module.NAME.template_file.SUBDOMAIN: Refreshing state... (ID: b1f262b04baf550a9951c9b8ff9858d315ab1637b100b729b4c538963f27d904)
module.our_aws_subnet.aws_subnet.test: Refreshing state... (ID: subnet-f2b3a1d9)
aws_instance.NAME: Refreshing state... (ID: i-029d6bb3)
module.gpg_keys.null_resource.key_upload: Refreshing state... (ID: 6481417946640352673)
null_resource.NAME: Destroying...
null_resource.NAME: Creating...
  triggers.#:                    "" => "1"
  triggers.cluster_instance_ids: "" => "i-029d6bb3"
null_resource.NAME: Provisioning with 'chef'...
null_resource.NAME (chef): Connecting to remote host via SSH...
null_resource.NAME (chef):   Host: 100.88.9.127
null_resource.NAME (chef):   User: ubuntu
null_resource.NAME (chef):   Password: false
null_resource.NAME (chef):   Private key: true
null_resource.NAME (chef):   SSH Agent: true
null_resource.NAME (chef): Connected!
null_resource.NAME (chef):   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
null_resource.NAME (chef):                                  Dload  Upload   Total   Spent    Left  Speed
null_resource.NAME (chef):   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
null_resource.NAME (chef):   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
null_resource.NAME (chef): 100 18716  100 18716    0     0  35614      0 --:--:-- --:--:-- --:--:-- 35581
null_resource.NAME (chef): Downloading Chef 11.12.8 for ubuntu...
null_resource.NAME (chef): downloading https://www.chef.io/chef/metadata?v=11.12.8&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
null_resource.NAME (chef):   to file /tmp/install.sh.1599/metadata.txt
null_resource.NAME (chef): trying wget...
null_resource.NAME (chef): url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_11.12.8-2_amd64.deb
null_resource.NAME (chef): md5	708874f3a14484376ec3ab19ae9703f6
null_resource.NAME (chef): sha256	0e6a2f89d4231782d72a5cd5fbf9609a1e5a3ee38c7fccbebe6707dd86ac271e
null_resource.NAME (chef): downloaded metadata file looks valid...
null_resource.NAME (chef): downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_11.12.8-2_amd64.deb
null_resource.NAME (chef):   to file /tmp/install.sh.1599/chef_11.12.8-2_amd64.deb
null_resource.NAME (chef): trying wget...
null_resource.NAME (chef): Comparing checksum with sha256sum...
null_resource.NAME (chef): Installing Chef 11.12.8
null_resource.NAME (chef): installing with dpkg...
null_resource.NAME (chef): (Reading database ...
null_resource.NAME (chef): (Reading database ... 5%
null_resource.NAME (chef): (Reading database ... 10%
null_resource.NAME (chef): (Reading database ... 15%
null_resource.NAME (chef): (Reading database ... 20%
null_resource.NAME (chef): (Reading database ... 25%
null_resource.NAME (chef): (Reading database ... 30%
null_resource.NAME (chef): (Reading database ... 35%
null_resource.NAME (chef): (Reading database ... 40%
null_resource.NAME (chef): (Reading database ... 45%
null_resource.NAME (chef): (Reading database ... 50%
null_resource.NAME (chef): (Reading database ... 55%
null_resource.NAME (chef): (Reading database ... 60%
null_resource.NAME (chef): (Reading database ... 65%
null_resource.NAME (chef): (Reading database ... 70%
null_resource.NAME (chef): (Reading database ... 75%
null_resource.NAME (chef): (Reading database ... 80%
null_resource.NAME (chef): (Reading database ... 85%
null_resource.NAME (chef): (Reading database ... 90%
null_resource.NAME (chef): (Reading database ... 95%
null_resource.NAME (chef): (Reading database ... 100%
null_resource.NAME (chef): (Reading database ... 101558 files and directories currently installed.)
null_resource.NAME (chef): Preparing to unpack .../chef_11.12.8-2_amd64.deb ...
null_resource.NAME (chef): Unpacking chef (11.12.8-2) over (11.12.8-2) ...
null_resource.NAME (chef): Setting up chef (11.12.8-2) ...
null_resource.NAME (chef): Thank you for installing Chef!
null_resource.NAME (chef): Creating configuration files...
Error applying plan:

1 error(s) occurred:

* Uploading validation.pem failed: scp: /etc/chef/validation.pem: Permission denied
```

**Comment by svanharmelen** [comment]
@lhagemann without looking at any code (not behind a desk at the moment) I would like to stress that the Chef provisioner is meant to be used only once on a newly created resource. After this initial provisioning you should manage the node from Chef using the normal tools like `knife` for example.

There is another resource in the works (a Chef provider instead of provisioner) that (once released) you could also use to do this kind of Chef management using Terraform: https://github.com/hashicorp/terraform/pull/3084 These 2 resources together should enable all use cases and Chef management using Terraform.

**Comment by lhagemann** [comment]
@svanharmelen that sounds reasonable; I'll leave this open for review, in case there is something related to #649 that might be interesting, but your analysis sounds appropriate. 

Thanks for the response.

**Comment by miguelaferreira** [comment]
I'm experiencing the same issue, when using the chef provisioner in a null resource.
I need to do this because the (first) chef-client run needs to setup a LVM logical volume (then mount it, etc), and for that I need a disk to be attached to the instance. Since I'm using cloudstack provider, I need to declare the instance, the disk, and then the null resource with the chef provisioner to kickoff the first chef run on the instance.

If that's not the way to do it, please advise on another strategy

**Comment by svanharmelen** [comment]
Of course we could easily fix the `Permission denied` error, but that would not fix your problem. It would likely make it even worse...

As the provisioner is *only* designed for doing the initial Chef run, it uses a few additional `chef-client` parameters that specify (among other things) the `run_list` and  `attributes` that the client must use for it's initial run.

If this would be run again while the node already exists (for weeks or maybe even months already), it would mean that all node `attributes` and the `run_list` will be reset to the data configured for the initial run in your Terraform plan. So any changes to the `run_list` and/or the `attributes` made on the Chef server after the initial run, would be lost when this was to run again.

In Terraform v0.6.9 (which is just released) there now also is a Chef provider that can make changes to your Chef server from a Terraform plan. So if you would want to make config changes after the initial run, you should use that new provider instead.

@lhagemann are you OK with closing this issue now as the Chef provider is now released?

**Comment by miguelaferreira** [comment]
Let me provide a bit more context.

In my case, the permission denied error comes from the fact that terraform is trying to upload the wrong file. I have a variable set like this:
```
validation_key         = "${file("${var.validation_key_path}")}"
```
which points to a file in my home dir. However terraform tries to upload the system default file in `/etc/chef/validation.pem`, for which it does not have permission.

Furthermore, I'm seeing this already in the initial terraform run.

**Comment by svanharmelen** [comment]
Just discussed this with Miguel and his assumptions where slightly off. This was indeed due to running the provisioner against the same node for a second time.

But in his case the initial run failed and so it makes sense that you would want to run it again with an updated config to see if it works now. So I created a fix for that which he tested and confirmed to fis this issue.

So going to put in a fix for this one after all :wink: PR will be up in a few...

**Comment by miguelaferreira** [comment]
Thanks Sander!

**Comment by lhagemann** [comment]
sounds like this is addressed.
