### ISSUE TITLE
question about terraform init & .gitignore

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#4269]
When you run a `terraform init` on a git repo it doesn't pull in the `.gitignore` file(s). The docs say "[Version control information from the module (such as Git history) will not be copied](https://terraform.io/docs/commands/init.html)" but, IMO, something like .gitignore shouldn't be excluded. Having `init` copy the .gitignore file(s) would be extremely useful for us so that our developers don't need to remember to setup a new one in the repo they are adding the terraform files to. We've already run into a few cases where developers new to Terraform have done this.

```
$> terraform init github.com/mtougeron/tf-gitignore-example

$> ls -la
total 24
drwxr-xr-x   5 michael.tougeron  admin  170 Dec 11 10:12 .
drwxr-xr-x  17 michael.tougeron  admin  578 Dec 11 10:10 ..
-rw-r--r--   1 michael.tougeron  admin  493 Dec 11 10:12 main.tf
-rw-r--r--   1 michael.tougeron  admin  187 Dec 11 10:12 outputs.tf
-rw-r--r--   1 michael.tougeron  admin  409 Dec 11 10:12 variables.tf
```

What are your thoughts about allowing that file to be copied?

**Comment by nwalke** [comment]
I think this is due to go-getter ignoring dotfiles on copy...

https://github.com/hashicorp/go-getter/blob/master/copy_dir.go
