### ISSUE TITLE
Splats expanding improperly in provisioner

### ISSUE THREAD

**Issue by pushingice** [hashicorp/terraform#427]
I'm trying to run a provisioner script against each instance in a count block. I would like to be able to send the list of all the DNS names in the block to each instance. It looks like what is happening is that instead of expanding the splat fully for every iteration (e.g. producing the list [0, 1]), it accumulates the list as it goes (e.g. [0], [0,1]). Sample config:

resource "aws_instance" "zookeeper" {
  ami = "${var.amis}"
  instance_type = "m3.large"
  key_name = "daalt-experimental"
  subnet_id = "subnet-ef5def86"
  security_groups = ["${aws_security_group.dev-zookeeper.id}"]
  availability_zone = "us-west-2b"
  count = 2

  tags {
    Name = "daalt-zookeeper-dev-${count.index}"
  }

  provisioner "local-exec" {
    command = "echo ${join(",",aws_instance.zookeeper.*.private_dns)} "
  }
}

Here's the output:

aws_instance.zookeeper.0: Provisioning with 'local-exec'...
aws_instance.zookeeper.0 (local-exec): Executing: /bin/sh -c "echo ip-10-252-3-52.us-west-2.compute.internal "
aws_instance.zookeeper.0 (local-exec): ip-10-252-3-52.us-west-2.compute.internal
aws_instance.zookeeper.0: Creation complete
aws_instance.zookeeper.1: Provisioning with 'local-exec'...
aws_instance.zookeeper.1 (local-exec): Executing: /bin/sh -c "echo ip-10-252-3-52.us-west-2.compute.internal,ip-10-252-3-154.us-west-2.compute.internal "
aws_instance.zookeeper.1 (local-exec): ip-10-252-3-52.us-west-2.compute.internal,ip-10-252-3-154.us-west-2.compute.internal
aws_instance.zookeeper.1: Creation complete

**Comment by mitchellh** [comment]
This is fixed by #1016
