### ISSUE TITLE
Terraform doesn't detect changes to template_file resource

### ISSUE THREAD

**Issue by yogin** [hashicorp/terraform#4274]
I have a template file outside of the module I'm using it in, and terraform doesn't detect changes made to that file

This is my resource for the file, it is then used as `user_data` on AWS instances.
```
resource "template_file" "service_init" {
  template = "../init/service.sh"
  count = "${var.instance_count}"

  vars {
    hostname = "${var.host_basename}${count.index}.${var.internal_domain_name}"
    environment = "${var.environment_name}"
    role = "${var.role}"
  }
}
```

Strangely, if I replace `template` with the deprecated `filename`, terraform detects the changes correctly

Currently using `v0.6.8`, I was initially running `v0.6.7` and had the same issue

This is the first time I have this issue, and the only difference is that the template file is sitting outside the module.

**Comment by yogin** [comment]
Could be related to https://github.com/hashicorp/terraform/issues/3732 although that seems to be other way around

**Comment by yogin** [comment]
My current workaround is to duplicate the template file into the modules, not ideal but it works as intended for now

**Comment by jen20** [comment]
Hi @yogin - thanks for reporting this. When you switched from `filename` to `template`, did you also change the contents of that argument to use a file interpolation? The syntax should look something like this:

```hcl
resource "template_file" "service_init" {
  template = "${file("${path.root}/init/service.sh")}"
  count = "${var.instance_count}"

  vars {
    hostname = "${var.host_basename}${count.index}.${var.internal_domain_name}"
    environment = "${var.environment_name}"
    role = "${var.role}"
  }
}
```

Note the use of `${path.root}` to refer to the root directory - you may need to adjust that path depending on your directory layout.

**Comment by yogin** [comment]
Sorry for the delay, for some reason I missed the notification.

So currently my resource with the file inside the module looks like this:
```
resource "template_file" "service_init" {
  template = "${path.module}/init/service.sh"
  count = "${var.instance_count}"

  vars {
    hostname = "${var.host_basename}${count.index}.${var.internal_domain_name}"
    environment = "${var.environment_name}"
    role = "${var.role}"
  }
}
```

What does `path.root` point to exactly? the directory I'm running terraform from?
I didn't try with `file()` but I will give it a shot tomorrow.

**Comment by yogin** [comment]
So I just tried using `file()` with `template` and it seems to work fine with the file outside the module.
I guess I upgraded too fast from `filename` to `template`, I guess I should have double checked the documentation.

Thanks!
