### ISSUE TITLE
Crash Report with v0.6.8

### ISSUE THREAD

**Issue by pll** [hashicorp/terraform#4279]
Not sure what happened, but here's a crash log.

[crashlog.zip](https://github.com/hashicorp/terraform/files/60005/crashlog.zip)

**Comment by catsby** [comment]
Hey @pll – could you please post the relevant bits regarding the `panic` to either a gist, or including the ~20 some surrounding lines here?

**Comment by pll** [comment]
@catsby - not sure what I was doing at the time this happened.  And I've moved forward quite a bit since then, and only encountered the crash that one time. Have't seen it since.  You can probably close this out.   The crash log doesn't tell me enough to remember what I may have fixed since then.

**Comment by catsby** [comment]
Ok, thanks for following up @pll – let me know if you hit something similar again

**Comment by pll** [comment]
@catsby - Will do!
