### ISSUE TITLE
Terraform template crashes if the first server (aws_instance.server.0) dies unexpectedly

### ISSUE THREAD

**Issue by armon** [hashicorp/terraform#428]
See: https://github.com/hashicorp/consul/issues/402

The Terraform configuration currently does not handle if the first server created unexpectedly dies. To recreate you can run:
terraform apply github.com/hashicorp/consul/terraform/aws 
After this command finishes, terminate the first instance that was created as shown by "terraform plan", aws_instance.server.0.
Then try to run "terraform plan" after this instance terminates and you will receive following error:
"Error refreshing state: Resource 'aws_instance.server.0' does not have attribute 'public_dns' for variable 'aws_instance.server.0.public_dns"

**Comment by mitchellh** [comment]
This might be fixed, but needs to be verified.

**Comment by mitchellh** [comment]
This is fixed now.
