### ISSUE TITLE
openstack: terraform plan/refresh fails if an image has been removed

### ISSUE THREAD

**Issue by stevendborrelli** [hashicorp/terraform#4287]
The folks running our openstack cloud updated the centos image, and the old one is no longer available. When I now do a plan/refresh, I get the following: 

```
* openstack_compute_instance_v2.control.0: Expected HTTP response code [200] when accessing [GET https://example.com:8774/v2/55c1ad1a57064bc89b59e8bb117e6ece/images/1bbd1f1f-d32c-43ca-a727-3b2b075c3e28], but got 404 instead
{"itemNotFound": {"message": "Image not found.", "code": 404}}
```

I don't know what the right behavior here is. I'm probably going to have to manually update my .tfstate file and see what it does.

**Comment by jtopjian** [comment]
Are you using the latest release of Terraform? This type of issue was resolved a while back.

Rather than failing, Terraform should just update the Image information with "Image not found".

**Comment by stevendborrelli** [comment]
That was it! 

Issue is not present in 0.6.8.
