### ISSUE TITLE
aws_instance: documentation unclear on default values.

### ISSUE THREAD

**Issue by kitsunde** [hashicorp/terraform#4292]
`associate_public_ip_address` is market as optional, but it's not clear weather or not the default behavior is to give it a public IP address or not. https://terraform.io/docs/providers/aws/r/instance.html#associate_public_ip_address It's also not clear what value it expects. true, false or an ip address?

**Comment by jianhuawuchn** [comment]
I believe the default value is based on a definition in VPC. which sets whether to assign public IP to instances launched within VPC by default or not. This is an AWS behavior

**Comment by stack72** [comment]
Hi @kitsunde 

There is no default value on `associate_public_ip_address` as @jianhuawuchn correctly points out. When in a VPC, you can specify a value for this but any configuration in your subnet declaration can override this

E.g

A Private Subnet has the following config:

```
resource "aws_subnet" "primary-private" {
  vpc_id = "${aws_vpc.default.id}"
  cidr_block = "10.50.0.0/21"
  availability_zone = "us-west-2a"
  map_public_ip_on_launch = false
}
```

This will mean that you will not get a public ip regardless of specifying `associate_public_ip_address = true` in an instance launched in that subnet

Hopefully this makes sense. 

Any further information, please do let me know

Paul

**Comment by dene14** [comment]
@stack72 I would reopen this. This attribute require default value which will behave from terraform stands point as if no attribute provided.

Why do we need this:
- We encourage modular structure
- We do avoid conditions (if value is set then add this attribute, if value isn't set then don't mention attribute at all --- that's not possible)
- Modules should provide reasonable (and safe) defaults

So, there is no "safe default" could be set for a module for this particular key
