### ISSUE TITLE
aws_instance: Change m1.small example to type that supports HVM

### ISSUE THREAD

**Issue by kitsunde** [hashicorp/terraform#4293]
If you pick a default AMI today it will complain that hvm isn't supported for the instance type. It's a bit confusing when trying to wrap my head around Terraform since I won't know if it's something I did or if it's a limitation of Terraform.

I'd suggest changing all the instance types to t2.small. https://www.terraform.io/docs/configuration/resources.html

**Comment by catsby** [comment]
Thanks @kitsunde – we're cleaning these up in https://github.com/hashicorp/terraform/pull/4330
