### ISSUE TITLE
Header extends beyond the content area in the docs.

### ISSUE THREAD

**Issue by kitsunde** [hashicorp/terraform#4296]
https://terraform.io/docs/providers/aws/r/lambda_event_source_mapping.html

<img width="1680" alt="screenshot 2015-12-13 21 58 22" src="https://cloud.githubusercontent.com/assets/48965/11768924/44b891b8-a1e4-11e5-867e-5d0fbf96e081.png">

**Comment by jen20** [comment]
Hi @kitsunde! Thanks for opening this issue. We've been aware of this for a while and need to find a solution - it's actually being tracked in #3406. I'll close this one and we'll continue to track this at #3406!
