### ISSUE TITLE
Crash Report on terraform destroy

### ISSUE THREAD

**Issue by igoratencompass** [hashicorp/terraform#4303]
Hi,

I've got a crash report on terraform destroy run with TF 0.6.8. Any chance to upload or attach the compressed crash log?

Thanks,
Igor

**Comment by stack72** [comment]
@igoratencompass if you use gist.github.com - you can then add the link to the issue

**Comment by phinze** [comment]
Alternatively, if you can pick out the `panic: ` line and the stack trace directly following it we can use that for diagnosis here.

**Comment by catsby** [comment]
Closing for now as we've not heard back. If you're still hitting this please let us know!
