### ISSUE TITLE
DigitalOcean : can't use snapshot created with Packer

### ISSUE THREAD

**Issue by nlamirault** [hashicorp/terraform#4309]
I creates an image using Packer with  Digitalocean Provider  : 

```bash
$ packer build -var-file=packer-do.json hyperion.json
[...]
==> Builds finished. The artifacts of successful builds are:
--> digitalocean: A snapshot was created: 'hyperion-nomad-0-1-0-1450107509' in region 'nyc2'
``` 

I try to use it in a terraform configuration : 

```bash
$ terraform apply --var-file=terraform-do.tfvars
[...]
digitalocean_droplet.hyperion-nodes.0: Creating...
  image:                "" => "hyperion-nomad-0-1-0-1450107509"
[...]
Error applying plan:

2 error(s) occurred:

* digitalocean_droplet.hyperion-nodes.1: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.
* digitalocean_droplet.hyperion-nodes.0: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.

```

Using the DigitalOcean UI [1], i can create a droptlet using the snapshot "hyperion-nomad-0-1-0-1450107509".
If i choose *ubuntu-15-04-x64* for the image, Terraform creation is valid.
Any idea ?
Thanks.

[1] : https://cloud.digitalocean.com/droplets

**Comment by andrewsomething** [comment]
@nlamirault How are you referring to the image in your Terraform template. The first thing that occurs to me is that it you might be using its name for the "image" attribute when it [needs to be an ID or slug](https://terraform.io/docs/providers/do/r/droplet.html#image). On DO, currently only public images have slugs. So the only way to refer to a snapshot in an API call is to use its ID. I don't believe Terraform attempts to do a ID look up based on the name since there is no guarantee that the name is unique.

**Comment by nlamirault** [comment]
OK.
With Packer i create an image|snapshot named "hyperion-nomad-0-1-0-1450107509", and i try to use it in Terraform. So this is the mistake.
How can i know the ID of this image ?
Thanks.

**Comment by andrewsomething** [comment]
You can find it with the DO API by querying the `/images` endpoint, but it would probably be useful to include the image's ID in the output of successful Packer builds. I opened a PR in https://github.com/mitchellh/packer/pull/3000

**Comment by nlamirault** [comment]
Thanks !

**Comment by Jalle19** [comment]
Referring to the generated artifact using `image = "${atlas_artifact.foo.id}"` worked last Friday, now it doesn't anymore (hence this bug report). What has changed?

**Comment by Jalle19** [comment]
I compared the Packer build output from when this worked and now that it didn't, can't find anything that has seemingly changed. The Packer version used was 0.9.0rc1 on both occasions.

This bug basically renders the DigitalOcean provider useless so it'd be great if you could come up with a swift solution.

**Comment by Jalle19** [comment]
https://developers.digitalocean.com/documentation/changelog/ apparently they introduced "multiple droplet creation" on December 14, maybe that's what broke it?

**Comment by nlamirault** [comment]
Do you know if a new version is planned soon ? (with this Merge embedded)

**Comment by Jalle19** [comment]
For the record it turns out my issue was either a temporary glitch or me using different API tokens for Packer and Terraform.

**Comment by andrewsomething** [comment]
@nathanielks I'm not on the packer team myself, so I couldn't say. Maybe someone from Hashicorp can shed some light on that?

@Jalle19 Glad to hear you got it working!

**Comment by catsby** [comment]
Hey all, thanks for digging in and figuring this out, sorry for the silence here. 
Looks like this issue can now be resolved largely in part to https://github.com/mitchellh/packer/issues/3000 by @andrewsomething (thanks for that!)

The snapshot ID is now showing the the Packer output, and you can use that as the image id in Terraform.

If you're still having issues, let us know! 
Thanks all!
