### ISSUE TITLE
Terraform can't find some resources when they are created using resource count parameter

### ISSUE THREAD

**Issue by albertsj1** [hashicorp/terraform#431]
This is somewhat related to #430.  The dependency order was incorrect, so I modified many of the resources to specify directly the dependencies using the 'depends_on' resource parameter.  Terraform started creating things in the expected order; however, it was unable to locate some resources it had just created that needed to be used in later resources.  For example, it was unable to determine the subnet id for a subnet that it had just created.
```
aws_subnet.public.1: Creating...
  availability_zone: "" => "us-west-2b"
  cidr_block:        "" => "10.20.1.0/24"
  vpc_id:            "" => "vpc-122fe577"
aws_subnet.public.1: Creation complete
--- snip ---
aws_instance.nat.1: Creating...
  ami:                         "" => "ami-bb69128b"
  associate_public_ip_address: "" => "1"
  availability_zone:           "" => "us-west-2b"
  instance_type:               "" => "m1.small"
  key_name:                    "" => "john"
  private_dns:                 "" => "<computed>"
  private_ip:                  "" => "<computed>"
  public_dns:                  "" => "<computed>"
  public_ip:                   "" => "<computed>"
  security_groups.#:           "" => "1"
  security_groups.0:           "" => "${aws_security_group.nat.1.id}"
  source_dest_check:           "" => "0"
  subnet_id:                   "" => "${aws_subnet.public.1.id}"
--- snip ---
aws_instance.nat.1: Error: Error launching source instance: The subnet ID '${aws_subnet.public.1.id}' does not exist (InvalidSubnetID.NotFound)
```

The full configuration as well as output is available in [this gist][1].

[1]: https://gist.github.com/albertsj1/d71a964ac26bd032046e

**Comment by mitchellh** [comment]
Done

**Comment by albertsj1** [comment]
By 'done' do you mean Terraform now generates an error message, or you've added the ability to use double interpolation?

**Comment by mitchellh** [comment]
Heh, sorry. It generates a proper error message. There are a couple issues you might want to track to get the behavior you wanted: #219 and... I can't find another. But that would help.

**Comment by albertsj1** [comment]
I'm glad it generates an error now. That greatly helps with learning and
debugging.   Thanks for adding the error messages.
