### ISSUE TITLE
aws_s3_bucket doesn't support region

### ISSUE THREAD

**Issue by failshell** [hashicorp/terraform#4310]
When creating an S3 bucket manually, it's possible to specify in which region you want the bucket to be in.

Although not in the doc, Terraform seems to accept the region parameter.

Code example:

~~~ text
resource "aws_s3_bucket" "logs_us_west_2" {
  bucket = "logs.uswest2"
  acl = "private"
  region = "us-west-2"

  tags { Name = "logs.uswest2" }
}
~~~

`terraform plan` seems to understand `region` though:

~~~ text
+ aws_s3_bucket.logs_us_west_1
    acl:              "" => "private"
    bucket:           "" => "logs.uswest1"
    force_destroy:    "" => "0"
    hosted_zone_id:   "" => "<computed>"
    region:           "" => "us-west-1"
    tags.#:           "" => "1"
    tags.Name:        "" => "logs.uswest1"
    website_domain:   "" => "<computed>"
    website_endpoint: "" => "<computed>"
~~~

So does `terraform apply`:

~~~ text
aws_s3_bucket.logs_us_west_1: Creating...
  acl:              "" => "private"
  bucket:           "" => "logs.uswest1"
  force_destroy:    "" => "0"
  hosted_zone_id:   "" => "<computed>"
  region:           "" => "us-west-1"
  tags.#:           "" => "1"
  tags.Name:        "" => "logs.uswest1"
  website_domain:   "" => "<computed>"
  website_endpoint: "" => "<computed>"
aws_s3_bucket.logs_us_west_1: Creation complete
~~~

But then, if you run `terraform plan` again, it tries to reconfigure the bucket to the proper region, as it was created in us-east-1 (us standard):

~~~ text
~ aws_s3_bucket.logs_us_west_1
    region: "us-east-1" => "us-west-1"
~~~

Would be great if aws_s3_bucket supported regions.

Note: this is with 0.6.3.

**Comment by failshell** [comment]
Also, my provider is set to use us-east-1 (variable) as it's default region.

~~~ text
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}
~~~

**Comment by stack72** [comment]
@failshell for this to work, you would have to do the following:

```
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}
provider "aws" {
  alias = "usw2"
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}
```

Then to create a bucket in us-west-2, it would be as follows:

```
resource "aws_s3_bucket" "logs_us_west_2" {
  bucket = "logs.uswest2"
  acl = "private"
  provider = "aws.usw2"

  tags { Name = "logs.uswest2" }
}
```

**Comment by stack72** [comment]
Hi @failshell 

I am going to close this as a duplicate. #6051 was opened and has a little more explanation of what seems to be the issue.

We are going to track the issue there

Thanks for opening the issue

Paul

**Comment by apremalal** [comment]
@stack72  suggested fix doesn't seems to work with existing buckets. I tried to import a s3 bucket from  a different region and  then executed `terraform plan which resulted in a bad request error.
