### ISSUE TITLE
Terraform crash - unexpected EOF (AWS provider)

### ISSUE THREAD

**Issue by thadimulyono** [hashicorp/terraform#4320]
Hi,

I've got terraform crash when executing `terraform plan`. Version 0.6.6 for linux 64-bit, but tried upgrading to 0.6.8 and get the same error. Like the other thread I am not 100% comfortable with posting our crash log online but here's the lines containing "panic" and some lines after that. Please let me know if additional information is needed.
Thanks

2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: panic: runtime error: invalid memory address or nil pointer dereference
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x5cd7ec]
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: goroutine 145 [running]:
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.flattenParameters(0xc8203c1420, 0x4, 0x4, 0x0, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/structure.go:404 +0x11c
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsDbParameterGroupRead(0xc8201cb680, 0xcb6260, 0xc8200821c0, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_db_parameter_group.go:137 +0x687
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc8204c80c0, 0xc8203882a0, 0xcb6260, 0xc8200821c0, 0xc82033ad48, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:209 +0x430
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc820502810, 0xc82017d840, 0xc8203882a0, 0xc82ca87701, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:187 +0x1da
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0xc82049d600, 0xc820203cb0, 0xc82017e010, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/gopath/src/github.com/hashicorp/terraform/rpc/resource_provider.go:345 +0x6a
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: reflect.Value.call(0xef1d40, 0x10f9220, 0x13, 0x1189660, 0x4, 0xc820589ed8, 0x3, 0x3, 0x0, 0x0, ...)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /usr/local/go/src/reflect/value.go:432 +0x120a
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: reflect.Value.Call(0xef1d40, 0x10f9220, 0x13, 0xc820589ed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /usr/local/go/src/reflect/value.go:300 +0xb1
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: net/rpc.(*service).call(0xc8205122c0, 0xc820512280, 0xc8204c1cf0, 0xc82043a600, 0xc82049d620, 0xcb76a0, 0xc820203cb0, 0x16, 0xcb7700, 0xc82017e010, ...)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/go/src/net/rpc/server.go:383 +0x1c1
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: created by net/rpc.(*Server).ServeCodec
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/go/src/net/rpc/server.go:477 +0x4ac
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: goroutine 1 [IO wait]:
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: net.runtime_pollWait(0x7fc254582ea0, 0x72, 0xc82000a190)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /usr/local/go/src/runtime/netpoll.go:157 +0x60
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: net.(*pollDesc).Wait(0xc8200c4140, 0x72, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/go/src/net/fd_poll_runtime.go:73 +0x3a
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: net.(*pollDesc).WaitRead(0xc8200c4140, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/go/src/net/fd_poll_runtime.go:78 +0x36
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: net.(*netFD).accept(0xc8200c40e0, 0x0, 0x7fc254582f60, 0xc8200ca4a0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/go/src/net/fd_unix.go:408 +0x27c
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: net.(*UnixListener).AcceptUnix(0xc8200ca3a0, 0xc8200f5cc0, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/go/src/net/unixsock_posix.go:304 +0x53
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: net.(*UnixListener).Accept(0xc8200ca3a0, 0x0, 0x0, 0x0, 0x0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/go/src/net/unixsock_posix.go:314 +0x41
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/rpc.(*Server).Accept(0xc8200c2bd0, 0x7fc254581ef8, 0xc8200ca3a0)
2015/12/15 03:38:00 [DEBUG] terraform-provider-aws:     /opt/gopath/src/github.com/hashicorp/terraform/rpc/server.go:33 +0x34

**Comment by thadimulyono** [comment]
Just want to add that this seems to have been fixed by commit a82183f

I compiled terraform from source and using the resulting dev binaries it in our environment fixes the issue.

I think I just have to wait for the next version after 0.6.8, correct me if I am wrong. I'll close this.

Thanks

**Comment by catsby** [comment]
Hey @thadimulyono – yes this is a duplicate of https://github.com/hashicorp/terraform/issues/4294 that was patched in #4318. Apparently it was a [bug in the RDS API][1]. Thanks for opening (and closing) the issue! 

[1]: https://github.com/hashicorp/terraform/issues/4294#issuecomment-164704466
