### ISSUE TITLE
How to know exact error message

### ISSUE THREAD

**Issue by kc11381** [hashicorp/terraform#4322]
Hi,

Is there a way we get the exact error message in a variable or any command which can give us this message?

Note: I am using terraform vsphere provider.

Thank you.

**Comment by jen20** [comment]
Hi @kc11381. I'm not sure I follow the question here, but let me suggest two things which may be of use - perhaps you could clarify?

1) Error messages generated by Terraform can all be found by using `grep` on the source code - they tend to be descriptive, and if they cannot be understood without additional context we would likely consider that a bug.

2) Error messages generated by upstream providers cannot easily be enumerated unless that provider publishes a list of their error messages.

**Comment by kc11381** [comment]
Hi @jen20 : While running terraform apply you can get n number of errors because of any reason say low disk space, resource pool not found and so on. We see this error also. What I want to know is if there is a way I can get this error message in a variable or any command while can tell me what was the error message for last command executed.

**Comment by phinze** [comment]
Hi @kc11381 - Terraform does not store previously output error messages, so we don't have any way of reporting on recent errors. The output of the Terraform command that fails is the place to look for all error messages.
