### ISSUE TITLE
Order of operations not respected for security groups and instances

### ISSUE THREAD

**Issue by nickm4062** [hashicorp/terraform#4324]
I didn't see an open issue for this..

when an instance and security group are created and the instance references the security group you will get {"badRequest": {"message": "Security group is still in use", "code": 400}} using terraform destroy

terraform version
Terraform v0.6.8

openstack_compute_secgroup_v2

is there a way to to set resource precedence?

**Comment by nickm4062** [comment]
resolved this with https://www.terraform.io/intro/getting-started/dependencies.html
commenting for others

**Comment by jtopjian** [comment]
There are two ways to do this:

The first is to reference the security group from within the instance. This is the more "natural" / intuitive way when you're defining both resources. For example:

```hcl
resource "openstack_compute_secgroup_v2" "my_sg" {
  name = "my_sg"
  description = "my_sg"

  rule {
 ...
  }
}

resource "openstack_compute_instance_v2" "my_instance" {
  name = "my_instance"
  image_name = "Ubuntu 14.04"
  flavor_name = "m1.medium"
  security_groups = ["${openstack_compute_secgroup_v2.my_sg.name}"]
  ...
}
```

The second way is to explicitly define a relationship:

```
resource "openstack_compute_secgroup_v2" "my_sg" {
  name = "my_sg"
  description = "my_sg"

  rule {
 ...
  }
}

resource "openstack_compute_instance_v2" "my_instance" {
  name = "my_instance"
  image_name = "Ubuntu 14.04"
  flavor_name = "m1.medium"
  security_groups = ["my_sg"]
  ...
  depends_on = ["openstack_compute_secgroup_v1.my_sg"]
}
```

Let me know if this helps. Also let me know if you've used both of the above methods and you're still seeing the `400` error.

Thanks,
Joe

**Comment by jtopjian** [comment]
@nickm4062 Just wanted to touch base on this. Are you still seeing this issue?

**Comment by nickm4062** [comment]
This worked, thank you!
