### ISSUE TITLE
adding an aws_instance tears down and restarted other sibling aws_instances

### ISSUE THREAD

**Issue by cordoval** [hashicorp/terraform#4331]
i just added an instance

```
resource "aws_instance" "consul_server4" {
  ami = "${lookup(var.amis, var.region)}"
  instance_type = "${var.server_instance_type}"
  availability_zone = "${var.availability_zone}"
  key_name = "${aws_key_pair.alex.key_name}"
  iam_instance_profile = "${aws_iam_instance_profile.ecs.name}"
  user_data = "${file("./files/consul-server-cloud-config")}"
  subnet_id = "${aws_subnet.main.id}"
  vpc_security_group_ids = ["${aws_security_group.ecs.id}"]
  associate_public_ip_address = true
  private_ip = "10.0.1.74"
}
```

and it tore down my other 3 consul servers! is this how it is supposed to work?

**Comment by jen20** [comment]
Hi @cordoval. Thanks for opening an issue. With the configuration you describe, there should be no reason for any other instances to change, assuming no dependent variables had changed. Do you have the output of `plan` for your run (or the output of the `apply` if no plan was made) that we could look at?

**Comment by cordoval** [comment]
it was yesterday for a demo, my project is big but that part is just the server 1 - 3 replicating the same template above.same everything except ip address and name.

**Comment by catsby** [comment]
I'm curious, is your `user_data` changing?

**Comment by catsby** [comment]
Going to close this for now, please let us know if you have any more information.

**Comment by cordoval** [comment]
yes user_data was changing

**Comment by cordoval** [comment]
sorry i just was distracted and did not see this until now
