### ISSUE TITLE
aws_cloudformation_stack indefinitely reapplies changes in NoEcho parameters

### ISSUE THREAD

**Issue by mtb-xt** [hashicorp/terraform#4335]
If a cloudformation template contains a parameter with NoEcho set to true (like a password), the parameter value is shown as asterisks  "****".

Terraform 0.6.8 detects this as a parameter change and tries to reapply it on every 'plan' or 'apply':

```
aws_cloudformation_stack.redshift-prod: Modifying...
  parameters.MasterUserPassword: "****" => "lolmegapassword"

```

**Comment by radeksimko** [comment]
Thanks for this report too. :smiley: 

A solution could be ignoring changes in `NoEcho` parameters coming from AWS, the only difficult part is in decoding the whole template as this attribute isn't available from [the API directly](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Parameter.html).

**Comment by radeksimko** [comment]
This project may be helpful here:
https://github.com/awslabs/aws-cfn-go-template

**Comment by bobzoller** [comment]
Perhaps this is silly but it might also save someone from a headache:  _Don't_ be like me and try to work around this by adding:

```
lifecycle {
  ignore_changes = ["parameters.Password"]
}
```

All it means is that the next `apply` will write the `****` value back to AWS (instead of your secret).

**Comment by dylanvaughn** [comment]
Maybe if the parameter name ends in ```NoEcho``` then that tells Terraform to ignore it?  i.e. ```MasterDbPasswordNoEcho```

I could implement this in a PR if it seems like an acceptable solution.

**Comment by dylanvaughn** [comment]
I ended up doing a slightly different approach of just checking if the old value of the parameter coming from AWS is ```****``` - see https://github.com/hashicorp/terraform/pull/11707

**Comment by jsierles** [comment]
This issue still exists today, and the fix in the PR was never addressed. Does anyone have a workaround?
