### ISSUE TITLE
Packet Provider Project does not dedupe

### ISSUE THREAD

**Issue by pshima** [hashicorp/terraform#4346]
In my travels of the packet provider I found the following would create a new object on every run.

```
variable "auth_token" {
  default = "asdf1234asdf1234asdf1234asdf1234asdf1234"
}

variable "payment_method" {
  default = "asdf123-asdf123-1234-1234-asdf1234"
}

provider "packet" {
  auth_token = "${var.auth_token}"
}

resource "packet_project" "testing" {
  name           = "mycorp.testing"
  payment_method = "${var.payment_method}"
}
```

This seems counter to how the provider should work, that if the project name exists it should use the existing instead of creating a duplicate.  Packet itself allows projects with duplicate names(as they have different IDs).

**Comment by phinze** [comment]
I gave the resource code a quick once over but didn't find anything obviously wrong.

@crunchywelch any chance you could take a look at this?

**Comment by betawaffle** [comment]
This is more a question of state. The project name is currently not considered unique, it's just a human-friendly description. What behavior would you expect if you have two projects with the same name?

We also don't de-dup devices based on the hostname. If we decide that projects should be de-duplicated by name, we may want to do the same for devices by hostname. All that said, both project name and hostname can be changed at will (even through Terraform, if you created the object through Terraform), so using that as a unique identifier could cause different behavior depending on whether the object already existed in the Terraform state.

On a related note, we *do* de-dup SSH public keys by the key itself, but probably don't support it correctly in Terraform. If you try to create a pre-existing public key with Terraform, you'll probably get confusing behavior.

**Comment by crunchywelch** [comment]
I wonder then for folks who want to create a project with terraform with a manifest and not have to retrieve and edit it after creation with the project uuid how this would be possible. For now maybe this is an issue of documenting behavior? I do see how it could be a bit confusing.

**Comment by betawaffle** [comment]
I can certainly understand the use-case, but we'd either need to add another concept to the API (that of a user-controlled unique slug), or change the contract of names.

As long as your `.tfstate` sticks around (or is shared through Atlas), Projects, Devices, and SSH keys shouldn't be duplicated by multiple runs. If that's not the case, I **definitely** want to hear about it, because it's a bug for sure.

**Comment by crunchywelch** [comment]
Yeah, that's more or less what I recall, that dupes didn't happen, but the user is reporting that they do. @pshima can you confirm you get duplicate projects created on multiple runs of terraform when not specifying a project id? are you wiping state, or   executing on different hosts?

**Comment by pshima** [comment]
This occurred when I was testing out the modules and ended up with about 5 or 6 projects with the same names.  It could have been a state issue though as you mention above now that I think about it.  I would apply a plan, it would fail but then the resources would still be created.  Another apply would create another project with new resources.  From the testing I was also doing a lot of destroys so something could have gone awry.

I just tried to reproduce this with a basic configuration but was not able to, I am not sure how this happened before but it not occuring now.

Apologies for the false alarm here folks.  Everything looks to be working correctly!

**Comment by crunchywelch** [comment]
ok awesome, let us know if you do run into any issues!
