### ISSUE TITLE
moving around same resources in files is not supported

### ISSUE THREAD

**Issue by cordoval** [hashicorp/terraform#4347]
When one refactors tf files and move resources around, terraform apply don't follow up on those and tries to create duplicate resources as new and fails because some of these already exist.

**Comment by cordoval** [comment]
```
Error applying plan:

6 error(s) occurred:

* aws_iam_role.ecs_host_role: Error creating IAM Role ecs_host_role: EntityAlreadyExists: Role with name ecs_host_role already exists.
	status code: 409, request id: ae881a62-a41d-11e5-8386-d3391e1d709e
* aws_iam_role.ecs_service_role: Error creating IAM Role ecs_service_role: EntityAlreadyExists: Role with name ecs_service_role already exists.
	status code: 409, request id: aea0f92a-a41d-11e5-a392-d5ea3c3fc695
* aws_key_pair.alex: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'alex-key' already exists.
	status code: 400, request id:
* aws_elb.test-http: DuplicateLoadBalancerName: Load Balancer named test-http-elb already exists and it is configured with different parameters.
	status code: 400, request id: b26aab45-a41d-11e5-bb8a-9f2fcb6aeaa0
```

**Comment by phinze** [comment]
Hi @cordoval, this is due to the fact that Terraform's state file tracks known resources on a per-module basis.

Check out #591 for a bunch of discussion around this as well as a proposed solution.

**Comment by cordoval** [comment]
ok but those files were not modules, i guess moving lines below a resource causes the same thing.

**Comment by phinze** [comment]
Ah okay, thanks for the clarification!

Terraform should not lose track of resources moved around between different files within the same module. One way this could have happened to you is if the resource names are changed.

So given:

```tf
resource "aws_iam_role" "foo" {
  # ...
}
```

Once that resource is created, it's tracked in the state under: "root module, `aws_iam_role.foo`".

So if you change "foo" that will cause Terraform to see the config as a new resource that needs to be created.

You can check out the `terraform.tfstate` file to understand more about how Terraform tracks current resources - it's in JSON format so it's human readable.

**Comment by cordoval** [comment]
i did not change any name though. I believe you :+1:
