### ISSUE TITLE
Crash with missing braces

### ISSUE THREAD

**Issue by mmell** [hashicorp/terraform#4350]
This trivial code causes a Terraform (v 0.6.8) crash on `terraform plan`.

    resource "template_file" "cloud_config" {
      template = "$file("${path.module}/some/path")"
    }

The outer `${file...}` braces are missing. The inner `${path.module}` is required to cause the crash.

Crash log in https://gist.github.com/mmell/de322231ff976cf900eb

**Comment by phinze** [comment]
Thanks for the report! We'll get this parser bug fixed.

**Comment by phinze** [comment]
This crash has been fixed upstream, and the fix will be included in the next release. :+1:
