### ISSUE TITLE
Example in getting started guide fails because t2.micro requires a VPC

### ISSUE THREAD

**Issue by WillAbides** [hashicorp/terraform#4367]
The example in the getting started guide fails because the t2.micro instance requires a VPC and no VPC is specified in the example.  I worked around by reverting to t1.micro and the ami listed in [this version](https://github.com/hashicorp/terraform/blob/28d39cd0bc7e9212eeea77f871cf4d4c7df0da73/website/source/intro/getting-started/build.html.md#configuration) of the doc.

```
 ~/hack/terraform-test    terraform apply
aws_instance.example: Creating...
  ami:                      "" => "ami-d05e75b8"
  availability_zone:        "" => "<computed>"
  ebs_block_device.#:       "" => "<computed>"
  ephemeral_block_device.#: "" => "<computed>"
  instance_type:            "" => "t2.micro"
  key_name:                 "" => "<computed>"
  placement_group:          "" => "<computed>"
  private_dns:              "" => "<computed>"
  private_ip:               "" => "<computed>"
  public_dns:               "" => "<computed>"
  public_ip:                "" => "<computed>"
  root_block_device.#:      "" => "<computed>"
  security_groups.#:        "" => "<computed>"
  source_dest_check:        "" => "1"
  subnet_id:                "" => "<computed>"
  tenancy:                  "" => "<computed>"
  vpc_security_group_ids.#: "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* aws_instance.example: Error launching source instance: VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
	status code: 400, request id:

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by stack72** [comment]
@WillAbides do you mean on this page? https://terraform.io/intro/getting-started/build.html

**Comment by WillAbides** [comment]
@stack72 Yes, that's the page I meant.  Although after going through the rest of the getting started documentation I had to keep substituting the old images for the ones on the current page.

**Comment by catsby** [comment]
Hey @WillAbides sorry for that, I changed them all recently in https://github.com/hashicorp/terraform/pull/4330 to try and update the docs, but I clearly overlooked this situation (my account has a default VPC). I'll get this cleaned up

**Comment by donwb** [comment]
interesting that we're hitting this at almost the exact same time.  I checked the PR above, but it seemed to be changing things to use `ami-d05e75b8` with `t2.micro`, which doesn't work for me.  I switched to `m3.large` and didn't have any problems.  What is the suggested way to launch a `t2.micro`?

**Comment by jhovell** [comment]
@donwb as the subject of this issue states t2 instances must be launched into a VPC. So, to launch one you need to create or specify a VPC, Subnet, etc which isn't included in the tutorial. I think you're just running into this issue now because the docs recently changed. Maybe the old m1.small instance types will work for you...

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-instances.html

**Comment by jhovell** [comment]
I tried to launch into an existing VPC and I think there might be another problem with the AMI provided
```
Error applying plan:

1 error(s) occurred:

* aws_instance.example: Error launching source instance: InvalidParameterCombination: Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.
	status code: 400, request id: 
```
You can look up a list of Ubuntu AMIs here.

http://cloud-images.ubuntu.com/releases/14.04/release-20150325/

I was able to get the example to work by launching into an existing VPC I had created in us-west-2 using ami-6989a659. It would appear ami-d85e75b0 might be the right choice for us-east-1 as in the example but I haven't tested it.

**Comment by drusellers** [comment]
Just hit this today

**Comment by samirspatel** [comment]
I ran into this exact same issue while trying to get started with terraform 
```
Error applying plan:

1 error(s) occurred:

* aws_instance.example: Error launching source instance: VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
        status code: 400, request id: 38266bc0-f95d-4fc3-a0bf-ebd9a11b0623

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by djandruczyk** [comment]
Attempting to use the above:

# Example Resource
resource "aws_instance" "example" {
  ami = "ami-408c7f28"
  instance_type = "m3.medium"
}
fails for me...
terraform apply
aws_instance.example: Creating...
  ami:                         "" => "ami-408c7f28"
  associate_public_ip_address: "" => "<computed>"
  availability_zone:           "" => "<computed>"
  ebs_block_device.#:          "" => "<computed>"
  ephemeral_block_device.#:    "" => "<computed>"
  instance_state:              "" => "<computed>"
  instance_type:               "" => "m3.medium"
  key_name:                    "" => "<computed>"
  network_interface_id:        "" => "<computed>"
  placement_group:             "" => "<computed>"
  private_dns:                 "" => "<computed>"
  private_ip:                  "" => "<computed>"
  public_dns:                  "" => "<computed>"
  public_ip:                   "" => "<computed>"
  root_block_device.#:         "" => "<computed>"
  security_groups.#:           "" => "<computed>"
  source_dest_check:           "" => "true"
  subnet_id:                   "" => "<computed>"
  tenancy:                     "" => "<computed>"
  vpc_security_group_ids.#:    "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* aws_instance.example: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-408c7f28]' does not exist
        status code: 400, request id: 22a474f8-47e9-4a9a-8740-8e745c77f2da

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by nielsonsantana** [comment]
Images have different _iam_ codes for each region. Per example, Ubuntu 16.04 in São Paulo-BR has code _ami-7379e31f_ and on Virgina-US has code _ami-6edd3078_ for the same image. The if you try launch a image from São Paulo(_ami-7379e31f_) in Virginia, won't work.

**Comment by anibalsanchez** [comment]
Same issue. The tutorial is not clear.

**Comment by pulyankote** [comment]
any resolution to this? I have the same problem.

**Comment by jamtur01** [comment]
There's no easy to fix this - it's a moving target of instance types and AMIs - is the existing note not sufficient? I think it's pretty clear but open to ideas to make it clearer.

**Comment by pulyankote** [comment]
sorry, am new to this, but which existing note are you referring to? This link gives  404 error
https://github.com/hashicorp/terraform/blob/28d39cd0bc7e9212eeea77f871cf4d4c7df0da73/docs/providers/index.html

**Comment by anibalsanchez** [comment]
This is the example that works for aws: https://github.com/hashicorp/terraform/tree/master/examples/aws-two-tier

**Comment by jamtur01** [comment]
![screenshot 2017-03-19 10 20 40](https://cloud.githubusercontent.com/assets/4365/24081620/c2a395d6-0c8d-11e7-8702-7bccbaada754.jpg)

From: https://www.terraform.io/intro/getting-started/build.html

**Comment by RodrigoJimmy** [comment]
Or, because old aws accounts doesn't have a default VPC, just use the `subnet_id` inside aws_instance resource:

```
resource "aws_instance" "example" {
    ami           = "ami-2757f631"
    instance_type = "t2.micro"
    subnet_id     = "subnet-123abc12"
}
```

**Comment by RodrigoJimmy** [comment]
Oh, and use `vpc = true` on the next page:

```
resource "aws_eip" "ip" {
    vpc      = true
    instance = "${aws_instance.example.id}"
}
```

**Comment by MarkusKramer** [comment]
It is really sad when the first example in a getting started guide doesn't work.

**Comment by MadOtis** [comment]
I was able to work around the issue by adding a security group ID and subnet ID.  Basically, this:
````
provider "aws" {
  region = "us-west-2"
}

resource "aws_instance" "bogus1" {
  ami = "ami-04c14c64"
  instance_type = "t2.micro"
}
````

becomes this:
````
provider "aws" {
  region = "us-west-2"
}

resource "aws_instance" "example" {
  ami = "ami-04c14c64"
  instance_type = "t2.micro"
  vpc_security_group_ids = ["<my_security_group_id>"]
  subnet_id = "<my_subnet_id>"
}
````

...obviously, replacing my_xxxxxx values with your actual subnet and security group ids

**Comment by Adron** [comment]
This is still... not really working. I've run into this myself just now. The AMI listed in the example doesn't work and reports back the whole...

    ==> amazon-ebs: Error launching source instance: VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
    ==> amazon-ebs:         status code: 400, request id: bdad1b26-c82b-4e13-8c1d-2053dc523c25
    ==> amazon-ebs: No volumes to clean up, skipping
    ==> amazon-ebs: Deleting temporary security group...
    ==> amazon-ebs: Deleting temporary keypair...
    Build 'amazon-ebs' errored: Error launching source instance: VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
            status code: 400, request id: bdad1b26-c82b-4e13-8c1d-2053dc523c25

**Comment by sinzin91** [comment]
The below worked for me, but requires creating a VPC and subnet:

```
provider "aws" {
  access_key = "ACCESS_KEY_HERE"
  secret_key = "SECRET_KEY_HERE"
  region = "us-east-1"
}

resource "aws_instance" "example" {
  ami = "ami-2757f631"
  instance_type = "t2.micro"
  subnet_id = "${aws_subnet.us-east-1a-public.id}"
}

resource "aws_vpc" "example" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support = true
}

resource "aws_subnet" "us-east-1a-public" {
  vpc_id = "${aws_vpc.example.id}"
  cidr_block = "10.0.1.0/25"
  availability_zone = "us-east-1a"
}
```

**Comment by NinoSkopac** [comment]
@sinzin91's comment fixed it for me. Really not great when the very first example fails, eh?

**Comment by reyou** [comment]
I just hit today, and I believe docs needs to be updated for non VPC users with;

```
resource "aws_instance" "example" {
  ami           = "ami-408c7f28"
  instance_type = "t1.micro"
}
```

**Comment by shuqichen** [comment]
Hi here, can you help to check why I aways get below error when I create ec2 instance by terraform:
aws_instance.aws_cli: Error launching source instance: InvalidSubnetID.NotFound: The subnet ID 'subnet-f4c696af' does not exist
	status code: 400, request id: 84472e95-1619-4727-a25b-e652bf2971fd
My terraform code:
provider "aws" {
  region = "${var.aws_region}"
}

resource "aws_instance" "aws_cli" {
  ami           = "${var.ami}"
  instance_type = "${var.aws_instance_type}"
  iam_instance_profile = "${var.chef_profile}"
  # availability_zone = "us-east-1a"

  tags {
    Name = "awsclitest"
  }

  vpc_security_group_ids = [
    "${var.base_sg_id}",
    "${var.tr_web_sg_id}",
  ]

  subnet_id = "${var.web_subnet_1}"
}

The running result info:
module.ec2.aws_instance.aws_cli: Creating...
  ami:                               "" => "ami-46e1073b"
  associate_public_ip_address:       "" => "<computed>"
  availability_zone:                 "" => "<computed>"
  ebs_block_device.#:                "" => "<computed>"
  ephemeral_block_device.#:          "" => "<computed>"
  instance_state:                    "" => "<computed>"
  instance_type:                     "" => "t2.micro"
  ipv6_address_count:                "" => "<computed>"
  ipv6_addresses.#:                  "" => "<computed>"
  key_name:                          "" => "<computed>"
  network_interface.#:               "" => "<computed>"
  network_interface_id:              "" => "<computed>"
  placement_group:                   "" => "<computed>"
  primary_network_interface_id:      "" => "<computed>"
  private_dns:                       "" => "<computed>"
  private_ip:                        "" => "<computed>"
  public_dns:                        "" => "<computed>"
  public_ip:                         "" => "<computed>"
  root_block_device.#:               "" => "<computed>"
  security_groups.#:                 "" => "<computed>"
  source_dest_check:                 "" => "true"
  subnet_id:                         "" => "subnet-f4c696af"
  tags.%:                            "" => "1"
  tags.Name:                         "" => "awsclitest"
  tenancy:                           "" => "<computed>"
  volume_tags.%:                     "" => "<computed>"
  vpc_security_group_ids.#:          "" => "2"
  vpc_security_group_ids.3409589747: "" => "sg-4949b536"
  vpc_security_group_ids.3882987815: "" => "sg-55b6ea29"

Error: Error applying plan:

1 error(s) occurred:

* module.ec2.aws_instance.aws_cli: 1 error(s) occurred:

* aws_instance.aws_cli: Error launching source instance: InvalidSubnetID.NotFound: The subnet ID 'subnet-f4c696af' does not exist
	status code: 400, request id: 5a4e6b48-c427-4b05-9b5f-23d9b5df986c

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by nnathan** [comment]
I also just hit this issue today. I changed instance type to `t1.micro` and everything worked as usual. Docs still need updating.

**Comment by KjetilM** [comment]
MadOtis comment helped med get past this. But someone should really have a look at the getting starting docs.
I get that learning by failing is a thing, but maybe let people get started before we start failing and flailing? ;)

**Comment by jonathan-schmieg** [comment]
the issue is more than 3 years old and it still has not been fixed :-1:

**Comment by 8wgremlin** [comment]
I'm in region ap-southeast2 and I had to change it to 

> resource "aws_instance" "example" {
>   ami           = "ami-0c9d48b5db609ad6e"
>   instance_type = "t2.micro"
> }

might be good to get this info right, for first-time users.

**Comment by marcellanz** [comment]
that issue just hit me

**Comment by danielpacker** [comment]
> that issue just hit me

Same, just hit me June 29, 2019. 3.5 years after issue opened. Granted, it forced me to learn about VPC dependencies, but as others have said, this example should be updated in the documentation.

@jamtur01 As @MadOtis and others suggested, a gentle reminder that you may need to create the VPC/subnet/security group before the example works would be nice, perhaps with a link to an example like the one @sinzin91 posted that creates said resources. I think people are still getting stuck on this point... not sure why my default VPC wasn't already up to par, but I had to do manual steps. Thanks for otherwise great docs.

**Comment by MatthewBracewell** [comment]
Hitting this exact problem mid 2019 - why is this issue closed??
(t2 -> t2.micro was the sole fix required here)

**Comment by ArtemChekunov** [comment]
I think the best solution is: aws-console -> new support issue ->  "Regarding: Account and Billing Support" -> "Service: Account" -> "Category: Convert EC2 Classic to VPC".
