### ISSUE TITLE
AWS RDS provisioning times out

### ISSUE THREAD

**Issue by wilb** [hashicorp/terraform#438]
I have a config block like:

<pre>
resource "aws_db_instance" "test" {
    identifier = "test"
    db_subnet_group_name = "test"
    engine = "mysql"
    engine_version = "5.6.19"
    instance_class = "db.t2.small"
    multi_az  = true
    allocated_storage = "50"
    name = "test"
    username = "root"
    password = "password"
    vpc_security_group_ids  = [ "${aws_security_group.test-db-servers.id}", "${aws_security_group.test-app-servers.id}" ]
    backup_retention_period = 7
}
</pre>
The provisioning will stall for a while (the instance creation does happen as expected) and eventually bail with:

<pre>
aws_db_instance.test: Error: timeout while waiting for state to become 'available'
Error applying plan:

1 error(s) occurred:

 * timeout while waiting for state to become 'available'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
</pre>

I've tried creating this with publicly_accessible = "true" set but this doesn't help. The instance is created as expected, but in the AWS console it is still at the modifying stage for a good while after creation has timed out at the console. Is this just simply a need to increase the timeout,?

Obviously this leaves terraform in a state of inconsistency; I'm having to comment out my db instance provisioning after initial creation otherwise terraform then tries to recreate an already existing host.

**Comment by pearkes** [comment]
Should be less frequent, increased the DB instance timeout to 40 minutes in https://github.com/hashicorp/terraform/commit/6f27f90ae12cdf0654f4d245e625c42e68b8625b

**Comment by geekmuse** [comment]
Still seeing this behavior even at the 40 minute threshold, particularly with SQL Server RDS instances

**Comment by JonRoma** [comment]
Seeing this with Terraform v0.7.2 and Oracle SE2 12.1.0.2.v4 RDS in a db.t2.micro instance type.

**Comment by ossareh** [comment]
@pearkes it's not so much the timeout that is the issue, it's that any treatment to the RDS instance is then delayed until the next run. The timeout itself feels like it should be a variable; is that reasonable?

**Comment by mattsoftware** [comment]
I am seeing this too. Trying to restore an aurora instance with a large snapshot, takes over 40 minutes to do, but does complete. After the cluster is created, and terraform is re-run, it first destroys the cluster and then tries to create it again.

**Comment by ff-pspiess** [comment]
I am seeing this too, it takes more than 40 minutes for the cluster to come online.  Is there a workaround?

**Comment by clearly** [comment]
+1

**Comment by jpriebe** [comment]
Seeing 40+ minutes to stand up RDS Aurora with a 30GB database deployed across two AZs.  Please fix this issue; I'm not sure how I'm going to be able to use Terraform unless I either exclude RDS from the config or I fork terraform and compile my own version.

**Comment by Hashfyre** [comment]
Seeing this with `terraform v0.8.2`, RDS, Postgres
```
Error applying plan:

1 error(s) occurred:

* aws_db_instance.test-postgres: timeout while waiting for state to become 'available' (last state: 'modifying', timeout: 40m0s)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by wilb** [comment]
I suspect no one is picking this up as it's a closed bug... Pinging @pearkes who upped the timeout originally?

**Comment by joseph-wortmann** [comment]
We just started having this with Postgres instances. DB created in AWS after about 15 minutes, TF waits for ~40 minutes and then times out. Rerun of TF shows no changes required.
