### ISSUE TITLE
aws_security_group fails silently in specific scenario

### ISSUE THREAD

**Issue by ascendantlogic** [hashicorp/terraform#4384]
In this scenario, I have created an `aws_security_group` without a `self = true` or `cidr_block` attribute. The plan shows the following (there are other security groups with the same flaw in this situation, hence the `4 changed` in the success message):

```
~ aws_security_group.dev_secure_email
    egress.#:                            "0" => "1"
    egress.2430724239.cidr_blocks.#:     "0" => "0"
    egress.2430724239.from_port:         "" => "587"
    egress.2430724239.protocol:          "" => "tcp"
    egress.2430724239.security_groups.#: "0" => "0"
    egress.2430724239.self:              "" => "0"
    egress.2430724239.to_port:           "" => "587"
```

Running `terraform apply` then shows success:

```
aws_security_group.prod_secure_email: Modifying...
  egress.#:                            "0" => "1"
  egress.2430724239.cidr_blocks.#:     "0" => "0"
  egress.2430724239.from_port:         "" => "587"
  egress.2430724239.protocol:          "" => "tcp"
  egress.2430724239.security_groups.#: "0" => "0"
  egress.2430724239.self:              "" => "0"
  egress.2430724239.to_port:           "" => "587"
...
...
Apply complete! Resources: 0 added, 4 changed, 0 destroyed.
```

Re-running the plan then shows the same security group changes again, resulting in an endless loop. Adding a `self` or `cidr_block` to the offending security group records causes the apply step to work, so it seems like one or both of those should be required in a validation step for a `plan` and/or `apply` to succeed.

**Comment by ascendantlogic** [comment]
Version used was 0.6.8

**Comment by catsby** [comment]
Hello – it's been quite some time and I apologize for not getting back to you. If you're still hitting this error on the latest version of Terraform (v0.7.8 at time of writing) please let us know! Sorry for the silence :(
