### ISSUE TITLE
RDS provisioning - no option for "Storage Type"

### ISSUE THREAD

**Issue by wilb** [hashicorp/terraform#439]
The default storage type for RDS is now "General Purpose (SSD)" when provisioning through the web interface but there is currently no ability to select this through the aws_db_instance provisioner. Instances created through Terraform default to magnetic storage. 

Whilst an option to choose between the two would be nice, maybe it would be better for terraform to default to General Purpose (SSD) to match current AWS behaviour?

**Comment by bitglue** [comment]
I've implemented a means to select the storage type, but I did not change the default behavior. Usually when an optional parameter is omitted in Terraform, Terraform omits that parameter to the API request, in this case to RDS. Although the web interface has changed its default, the RDS API still defaults to magnetic storage, unless `iops` is specified in which case it defaults to provisioned IOPS SSD storage.
