### ISSUE TITLE
Don't try to recreate things which are not allowed to edit on Google Cloud

### ISSUE THREAD

**Issue by phanect** [hashicorp/terraform#4394]
Problem
------------

For example, when you try to run following .tf.json file twice, you will get error message.

.tf.json file:

```json
"google_dns_managed_zone": {
  "test": {
    "name":        "${ var.app_name }",
    "dns_name":    "test.example.io.",
    "description": "test"
  }
}
```

error message:

```
* google_dns_managed_zone.notel: Error creating DNS ManagedZone: googleapi: Error 409: The resource 'entity.managedZone' named 'notel' already exists, alreadyExists
```

This happens `google_dns_managed_zone`, `google_compute_network`, `google_compute_http_health_check`, and some other resources.

I can't apply the same .tf.json file more than 2 times.

Suggestion
---------------
How about following improvements?:

- If the configuration is exactly the same as current GCP config, do nothing and no error message is shown.
- If the configuration is different from current GCP config, delete and recreate current resource.
  - Before deletion, I think terraform should ask user if you really recreate the resource because it causes downtime.

I'm really appreciate if those improvements, especially first one, are implemented.

**Comment by jen20** [comment]
Hi @phanect - I'd actually say that this is a bug which needs to be investigated. Terraform is designed to operate in the the manner you effectively described: if there is no difference between the configuration at the provider and the configuration given to Terraform, nothing should happen. Could you post the output of `terraform plan` for the config you included in the issue?

**Comment by phanect** [comment]
Hi @jen20, sorry for late reply.
I will send it tomorrow. I forgot to push latest code to Git repo and I don't have it now.

And let me email `terraform plan` output directly. It's company's infra and I want to avoid to paste it on publicly visible place.

**Comment by jen20** [comment]
Hi @phanect, that's fine, you can email me on james.nugent at hashicorp.com with the plan output if you would like.

**Comment by phanect** [comment]
@jen20 Thanks, I've sent files via email.

**Comment by phanect** [comment]
BTW my Terraform version is v0.6.8.

I also tried with development version (`master` branch) and get same result.
I'm not sure which was the latest commit. (I've deleted source code by mistake…)

**Comment by lwander** [comment]
@phanect, when you say 

> run following .tf.json file twice

do you mean that you run

```
$ terraform apply
$ terraform apply
```

in the same directory without making any changes to the TF file? Or do you have two copies of that file, and `apply` once to each file in separate directories?

**Comment by phanect** [comment]
> do you mean that you run
> $ terraform apply
> $ terraform apply
> in the same directory without making any changes to the TF file?

Yes, I did so.

**Comment by lwander** [comment]
Is `terraform plan` non-empty? When I run your example as you described above I don't see any errors. Could you produce a minimal failing example? I understand you don't want to share details of your application architecture.

**Comment by phanect** [comment]
@lwander I will send you my .tf.json file to your email address.

**Comment by phanect** [comment]
@lwander I will send you my .tf.json files via email too.

**Comment by lwander** [comment]
@phanect, got it, will look now.

**Comment by phanect** [comment]
Found the cause.
I didn't know .tfstate file is required and should be saved.
I have created shell script to run `terraform apply` to run several preprocesses such as JSON5 compilation, and I always delete .tfstate file before running `terraform apply`.

Sorry... :sweat:
