### ISSUE TITLE
question: why no interpolations in variables?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/terraform#4397]
When I try to define something like:

```
variable "extra_pillar" {
    description = "extra pillar that is shared across init templates for worker clusters"
    default = <<EOF
worker:
  redis: ${module.jobq-a.redis_url}
  image: ${var.worker_image}
  tag: ${var.worker_tag}
EOF
}
```

I get `variable 'extra_pillar': cannot contain interpolations`. I am surprised, in a way.

Obviously, one could get into circular deps with interpolation in variables, but then there are also times when it seems valid / sensible to leverage interpolation in variables. Is there a better way to achieve similar functionality?

**Comment by jen20** [comment]
Hi @ketzacoatl. Currently we require variables to be known up front prior to interpolation - it would be a reasonably large change to adjust this.

In this particular case your best bet is to use the `template_file` resource, and you can then use the `rendered` argument to get the output:

```hcl
resource "template_file" "extra_pillar" {
    template = <<EOF
worker:
  redis: ${redis_url}
  image: ${image}
  tag: ${tag}
EOF

    vars {
        redis_url = "${module.jobq-a.redis_url}"
        image = "${var.worker_image}"
        tag = "${var.worker_tag}"
    }
}

output "template" {
    value = "${template_file.extra_pillar.rendered}"
}
```

If this doesn't work for you, please feel free to reopen!

**Comment by ketzacoatl** [comment]
thanks @jen20, I will see how far I push the limits of `template_file` :)
