### ISSUE TITLE
Add support for AWS RDS DB Options Group

### ISSUE THREAD

**Issue by chevalpartners** [hashicorp/terraform#4399]
options groups are required to create AWS Multi AZ SQL Server. 
They can be created in the AWS console

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithOptionGroups.html

I have provided a specific example here:
https://groups.google.com/forum/#!topic/terraform-tool/uJDQetTRov0

It will be nice to have an ability create create options groups and being able to pass them when create new aws rds db instances.

**Comment by stack72** [comment]
@chevalpartners FYI, WIP is here https://github.com/hashicorp/terraform/pull/4401

Will finish it over the next day or 2

**Comment by PurrBiscuit** [comment]
any update on this?  I'm stuck on the same issue that chevalpartners was having as well:

`* aws_db_instance.rds: Error creating DB Instance: InvalidParameterCombination: To configure Multi-AZ for SQL Server DB Instances please apply or remove the "Mirroring" option using Option Groups.`

**Comment by stack72** [comment]
@PurrBiscuit this is on final review - I expect it to be merged within the week

**Comment by PurrBiscuit** [comment]
nice, thanks for your working on this.  much appreciated!

**Comment by bigkraig** [comment]
+1!

**Comment by chadgrant** [comment]
so many gotchas in terraform :(

**Comment by jbruettcva** [comment]
@stack72 there have been multiple production releases since you mentioned you expected this to be released.  considering multi-az support is a core tenant of RDS and this is a long supported function from the API can you provide an update as to when it's expected for this to be released or what problems were found with it that it hasn't been released yet?

**Comment by stack72** [comment]
My apologies for not getting back to this sooner. Between having a fulltime job, being a conference speaker and working ont eh Terraform AzureRM provider, this slipped through my radar. I will get back to addressing the points @phinze made on code review for #4401

**Comment by stack72** [comment]
This is closed by #4401
