### ISSUE TITLE
Unable to 'make updatedeps'

### ISSUE THREAD

**Issue by worldspawn** [hashicorp/terraform#4408]
Hi i'm trying to build this on osx so I can use the new nat gateway resource. I'm not a golang programmer.

There seems to be... some problem :D

```
github.com/sthulb/mime (download)
import "mime/quotedprintable": import path does not begin with hostname
package github.com/Azure/azure-sdk-for-go/Godeps/_workspace/src/github.com/Azure/go-autorest/autorest
```

and then a little later:

```
imports github.com/sthulb/mime/multipart
	imports mime/quotedprintable: unrecognized import path "mime/quotedprintable"
github.com/vmware/govmomi (download)
```

Is there something I need to install?

**Comment by worldspawn** [comment]
I updated go (from 1.4.2 to latest) and somehow... someway... it worked.

**Comment by solarkennedy** [comment]
I'm hitting this too. it looks like that package is part of golang 1.5: https://golang.org/doc/go1.5 (search for 'mime/quotedprintable')

If this is not a bug, then maybe the README.md should be updated to reflect that?
