### ISSUE TITLE
Expose storage_encrypted for RDS Cluster (Aurora)

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform#4414]
Add support for `storage_encrypted` for creating / modifying RDS Clusters (Aurora). 

- [x] `storage_encrypted` attribute
- [ ] `KmsKeyId` attribute 

Docs:
- http://docs.aws.amazon.com/fr_fr/AmazonRDS/latest/APIReference/API_CreateDBCluster.html

**Comment by bsiegel** [comment]
+1 for this issue. I would suggest that adding support for KMS parameters like `KmsKeyId` could be done separately, since `aws_db_instance` doesn’t currently support them either.

**Comment by stack72** [comment]
@catsby `storage_encryped` has been added in #5520

**Comment by catsby** [comment]
Thanks @stack72 and @bsiegel – going to close this for now, I think KmsKeyId things will come in a separate PR
