### ISSUE TITLE
[Openstack] Terraform should automatically taint compute instances which are in error state

### ISSUE THREAD

**Issue by kamaltherocky** [hashicorp/terraform#4429]
[Terraform Openstack Provider]
when an instance state is in error, terraform tries to update the metadata and fails. when we run terraform apply (on a retry), it should check for the instance state and if it is in error state, then it should destroy and recreate (taint) the instance.

**Comment by jtopjian** [comment]
Sorry for the late reply with this.

At this time, it's not possible for Terraform to automatically taint a resource. It must be done by the user. Since this would be a core feature, I'm going to close this issue for now.
