### ISSUE TITLE
aws_elasticache_cluster does not support AZMode

### ISSUE THREAD

**Issue by silvamerica** [hashicorp/terraform#4438]
Per http://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html, you can create an Elasticache cluster in a single AZ or "cross-az", where nodes will be scattered across availability zones.

**Comment by kamatama41** [comment]
:+1: I had same problem.

**Comment by radeksimko** [comment]
Hi @silvamerica 
isn't this a duplicate of https://github.com/hashicorp/terraform/issues/4361 ?

**Comment by silvamerica** [comment]
@radeksimko No it is not. Replication groups are only supported for Redis, not for Memcache. Creating a Replication Group with automatic failover will automatically enable Multi-AZ mode for Redis Elasticache clusters. However for Memcache Clusters (or if you are not doing a Replication Group), you have to set Multi-AZ manually.

**Comment by catsby** [comment]
I merged #4631 which should address this, let us know if you need anything else!
