### ISSUE TITLE
link to issues in changelog

### ISSUE THREAD

**Issue by blalor** [hashicorp/terraform#4439]
Would it be possible to update `CHANGELOG.md` with clickable links to GitHub issues?

**Comment by mitchellh** [comment]
We'd rather not to keep the CL format simple. It is easy enough to get to issues by doing: `https://github.com/hashicorp/terraform/issues/NUMBER` where NUMBER can be either an issue or PR and it'll work.

If this continues to be an annoyance I recommend setting up a browser or editor plugin. Maybe someone in the community can to it and we'd be happy to add it to the README of our projects.

**Comment by conorgil** [comment]
I actually did not know that this issue even existed before I came to the same conclusion that the links should be clickable and asked for feedback in IRC.

@mitchellh I understand the desire to keep the CHANGELOG format simple, but I agree with @blalor that clickable links would be a nice improvement in terms of usability. Each time a new release of Terraform comes out, I have to manually look up most of the issues to get full context on the changes and determine how they will impact my use of Terraform in the new release. Obviously, it is straight forward for me to do this, but I think putting a small additional burden on the CHANGELOG maintainers would make sense to save the entire community a bit of time and hassle when reviewing the CHANGELOG. Analogous to the "write once, read many times" saying.

There are several syntaxes we could utilize to make the issue links clickable; perhaps one might be simple enough to adopt?

My attempt was to leave the current syntax for the bullet items exactly the same and then add link targets under each section to turn the issue numbers into links. What are your thoughts?

For example:

```markdown
## 0.6.12 (Unreleased)

FEATURES:

  * **New resource:** `azurerm_dns_zone` [GH-4979]
  * **New resource:** `azurerm_dns_a_record` [GH-5013]
  * **New resource:** `azurerm_dns_aaaa_record` [GH-5013]
  * **New resource:** `azurerm_dns_cname_record` [GH-5013]
  * **New resource:** `azurerm_dns_mx_record` [GH-5041]
  * **New resource:** `azurerm_dns_ns_record` [GH-5041]
  * **New resource:** `azurerm_dns_srv_record` [GH-5041]
  * **New resource:** `azurerm_dns_txt_record` [GH-5041]
  * **New resource:** `azurerm_sql_database` [GH-5003]
  * **New resource:** `azurerm_sql_server` [GH-4991]
  * **New resource:** `azurerm_sql_firewall_rule` [GH-5057]
  * **New interpolation function:** `signum` [GH-4854]
  * **New command:** `validate` to perform syntax validation [GH-3783]

[GH-4979]: https://github.com/hashicorp/terraform/issues/4979
[GH-5013]: https://github.com/hashicorp/terraform/issues/5013
[GH-5013]: https://github.com/hashicorp/terraform/issues/5013
[GH-5013]: https://github.com/hashicorp/terraform/issues/5013
[GH-5041]: https://github.com/hashicorp/terraform/issues/5041
[GH-5041]: https://github.com/hashicorp/terraform/issues/5041
[GH-5041]: https://github.com/hashicorp/terraform/issues/5041
[GH-5041]: https://github.com/hashicorp/terraform/issues/5041
[GH-5003]: https://github.com/hashicorp/terraform/issues/5003
[GH-4991]: https://github.com/hashicorp/terraform/issues/4991
[GH-5057]: https://github.com/hashicorp/terraform/issues/5057
[GH-4854]: https://github.com/hashicorp/terraform/issues/4854
[GH-3783]: https://github.com/hashicorp/terraform/issues/3783

IMPROVEMENTS:

  * core: Backend names are now down cased during `init` in the same manner as `remote config` [GH-5012]
  * provider/aws: Add `is_multi_region_trail` option to CloudTrail [GH-4939]
  * provider/aws: Add support for log validation + KMS encryption to `aws_cloudtrail` [GH-5051]
  * provider/aws: Support custom endpoints for AWS EC2 ELB and IAM [GH-5114]
  * provider/aws: Expose additional VPN Connection attributes [GH-5032]

[GH-5012]: https://github.com/hashicorp/terraform/issues/5012
[GH-4939]: https://github.com/hashicorp/terraform/issues/4939
[GH-5051]: https://github.com/hashicorp/terraform/issues/5051
[GH-5114]: https://github.com/hashicorp/terraform/issues/5114
[GH-5032]: https://github.com/hashicorp/terraform/issues/5032

BUG FIXES:

  * core: Fix bug where `ignore_changes` could produce "diffs didn't match during apply" errors [GH-4965]
  * core: Improve handling of Provisioners in the graph, fixing "Provisioner already initialized" errors [GH-4877]
  * core: Fix bug detecting deeply nested module orphans [GH-5022]
  * core: Fix race condition when handling tainted resource destroys [GH-5026]
  * provider/openstack: Fix crash when `access_network` was not defined in instances [GH-4966]
  * provider/aws: Fix DynamoDB Table Refresh to ensure deleted tables are removed from state [GH-4943]
  * provider/aws: Fix issue applying security group changes in EC2 Classic RDS for aws_db_instance [GH-4969]
  * provider/cloudflare: `ttl` no longer shows a change on each plan on `cloudflare_record` resources [GH-5042]
  * provider/aws: Fix reading auto scaling group load balancers [GH-5045]
  * provider/aws: Fix reading auto scaling group availability zones [GH-5044]
  * provider/docker: Fix the default docker_host value [GH-5088]

[GH-4965]: https://github.com/hashicorp/terraform/issues/4965
[GH-4877]: https://github.com/hashicorp/terraform/issues/4877
[GH-5022]: https://github.com/hashicorp/terraform/issues/5022
[GH-5026]: https://github.com/hashicorp/terraform/issues/5026
[GH-4966]: https://github.com/hashicorp/terraform/issues/4966
[GH-4943]: https://github.com/hashicorp/terraform/issues/4943
[GH-4969]: https://github.com/hashicorp/terraform/issues/4969
[GH-5042]: https://github.com/hashicorp/terraform/issues/5042
[GH-5045]: https://github.com/hashicorp/terraform/issues/5045
[GH-5044]: https://github.com/hashicorp/terraform/issues/5044
[GH-5088]: https://github.com/hashicorp/terraform/issues/5088
```

**Comment by conorgil** [comment]
@mitchellh I'm excited to see Terraform `0.6.12` released, but I am feeling this pain again as I review the change log. Any thoughts on changing your current position on the matter? Adding links would really make reviewing the change log easier.

**Comment by alfonso-cabrera** [comment]
+1 on links in the changelog.

**Comment by apparentlymart** [comment]
Hi all,

After some discussion within the Terraform committers team we decided to try the following compromise:

When adding new things to the "unreleased" version we'll continue to use the `[GH-nnn]` notation because it's quick and easy for us to do when merging lots of changes.

However, we now have a script added in #5313 that allows us to bulk-change all of the issue references in the changelog into Markdown links. We'll run this script as part of the release process when tagging a new release, so all of the items under the *released* versions should be links.

Hopefully this compromise works well for everyone; we'll try this for a while and see how it works out.

**Comment by conorgil** [comment]
Woo! This is a totally reasonable compromise. Thanks!

**Comment by blalor** [comment]
I'm so happy to see these links in the changelog. It's a little thing, but it makes looking up the details of a change so much easier (especially on a touch device).
