### ISSUE TITLE
aws_lambda_event_source_mapping doesn't work with SNS

### ISSUE THREAD

**Issue by smotovilovets** [hashicorp/terraform#4454]
**aws_lambda_event_source_mapping** resource doesn't seem to work with SNS.
My use-case presumes SNS-triggered Lambda invocation.
Creating **aws_sns_topic_subscription** doesn't work either, as discussed in https://github.com/hashicorp/terraform/issues/2885

**Comment by maxbeatty** [comment]
Based on the [AWS CLI documentation](http://docs.aws.amazon.com/cli/latest/reference/lambda/create-event-source-mapping.html), I don't believe SNS is a valid source (yet)

> The Amazon Resource Name (ARN) of the Amazon Kinesis or the Amazon DynamoDB stream that is the event source.

I'm hoping SNS becomes an event source some day, too.

**Comment by stack72** [comment]
Hi, this should now be closed by #4826
