### ISSUE TITLE
Support for ECS service deploymentConfiguration

### ISSUE THREAD

**Issue by brentonannan** [hashicorp/terraform#4456]
Are there plans to support `deploymentConfiguration` for ECS service definitions as described on the [documentation](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_paramters.html), and supported on the ECS console?

**Comment by maheshpec** [comment]
+1

**Comment by aldarund** [comment]
+1. Need this :(

**Comment by anosulchik** [comment]
+1

**Comment by nhuray** [comment]
+1

**Comment by maescomua** [comment]
+1

**Comment by benzimmer** [comment]
I think this is pretty essential because currently it takes down the whole service when doing a `terraform apply`. Defining the options in `deploymentConfiguration` would allow to do rolling restarts without downtime of the service.

**Comment by anosulchik** [comment]
@benzimmer Just a quick observation: it's still possible to change minimumHealthyPercent and maximumPercent for ECS service in AWS console to prevent downtimes, "terraform apply" won't reset those settings.

**Comment by benzimmer** [comment]
@anosulchik Nice, thanks for the hint!

I was thinking about using [null_resource](https://www.terraform.io/docs/provisioners/null_resource.html) together with the [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html) provisioner to have a script update the settings after creation of the service.

**Comment by dquiles-handy** [comment]
:+1:

**Comment by stack72** [comment]
Resolved in #5220

**Comment by brentonannan** [comment]
:+1: thanks!
