### ISSUE TITLE
terraform destroy -target=module.xxx

### ISSUE THREAD

**Issue by AVVS** [hashicorp/terraform#4462]
it doesn't destroy instances that are referenced in the nested modules, ie:

* module.xxx:

    module "chef-machine" {

    }

   some_ipaddress_resource ...

* module.chef-machine:

  some_instance_resource

When doing `terraform destroy -target=module.xxx` it will destroy `some_ipaddress_resource` only,
leaving module.chef-machine resources up

When doing `terraform destroy -target=module.xxx.module.chef-machine` it will destroy chef-machine resources, leaving other module.xxx resources up, which is correct behaviour

**Comment by jen20** [comment]
@AVVS Thanks of reporting this. I will investigate this and try to reproduce - it certainly sounds like a core bug to me.

**Comment by stvnwrgs** [comment]
We see the same issue when we tried to destroy a single instance.

`terraform plan -destroy -target=module.xxx.module.machine_id`
it says nothing.

If we fuck up the machine id, it tries to destroy the whole xxx module!? I dont know if this is correlating or not, but it is definitly a bad behavior!
