### ISSUE TITLE
[Docker] Add support for docker volumes

### ISSUE THREAD

**Issue by ColinHebert** [hashicorp/terraform#4479]
Docker is able to manage volumes independently of containers. Terraform should manage those volumes (akin to EBS volumes for AWS)

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#2-4-volumes
https://docs.docker.com/engine/reference/commandline/volume_create/
https://github.com/fsouza/go-dockerclient/blob/master/volume.go

**Comment by jen20** [comment]
This is now supported on `master` - thanks for opening the issue and doing the work @ColinHebert!
