### ISSUE TITLE
 diffs didn't match during apply when adding security group in aws_launch_configuration

### ISSUE THREAD

**Issue by aldarund** [hashicorp/terraform#4488]
I was having an aws_launch_configuration without a security group.

``` hcl
resource "aws_launch_configuration" "ecs" {
  name_prefix          = "ecs-rentapp-launch-"
  image_id             = "${lookup(var.ecs_amis, var.AWS_REGION)}"
  instance_type        = "${var.ecs_instance_type}"
  key_name             = "${aws_key_pair.deployer.key_name}"
  iam_instance_profile = "${aws_iam_instance_profile.ecs.id}"
  user_data            = "#!/bin/bash\necho ECS_CLUSTER=rentapp-cluster >> /etc/ecs/ecs.config"
  lifecycle {
      create_before_destroy = true
  }
}
```

Then i added it 

``` hcl
  security_groups      = ["${aws_security_group.ecs_node.id}"]
```

And then when apply i get following:

```
Error applying plan:

1 error(s) occurred:

* aws_launch_configuration.ecs: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

**Comment by aldarund** [comment]
On the second run ( im running it using atlas) it worked fine.

**Comment by cleung2010** [comment]
I have also encountered this, though it was with `aws_instance` that contained `user_data`. Running it the first time would give me a `diffs didn't match during apply` error, but re-running it worked.

**Comment by aldarund** [comment]
Run into this today again.
* aws_iam_role_policy.ecs_service_role_policy: diffs didn't match during apply. This is a bug with Terraform and should be reported.
What i changed was replace deprecated use of filename= 
with 
template = "${file
and that triggered this error. On second run it completed again successfully

**Comment by rkulagowski** [comment]
Also running into this issue:

```
Error applying plan:

1 error(s) occurred:

* aws_security_group.InternalSecurity: diffs didn't match during apply. 
This is a bug with Terraform and should be reported.
```

This is the group

```
# Security group to access the instances over SSH and HTTP.
# Internal instances can only be reached from the bastion host and from the ELB.

resource "aws_security_group" "InternalSecurity" {
  name = "testApp default security group"
  description = "Allows SSH and HTTP only"

  # SSH access from the bastion host.
  ingress {
    from_port = 22
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["${aws_instance.bastionHost.private_ip}/32"]
  }

  # HTTP access from internal only
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    security_groups = ["${aws_elb.web-elb.source_security_group_id}"]
  }

  # HTTP access from internal only
  ingress {
    from_port = 80
    to_port = 80
    protocol = "tcp"
    cidr_blocks = ["${aws_instance.bastionHost.private_ip}/32"]
  }

  # outbound internet access
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Owner = "rkulagowski" Application = "testApp" Name = "testApp internal hosts SG"}
}

```

**Comment by aldarund** [comment]
Have again this today.
Was having:
resource "template_file" "ecs_fabio_task_template" {
  // here we expand multiple template_files - the same number as we have instances
  template = "${file("ecs-tasks/ecs-fabio.json")}"
  vars {
    // that gives us access to use count.index to do the lookup
    image_revision = "${var.image_revision}"
    celery_worker_beat_cpu = "${var.celery_worker_beat_cpu}"
    celery_worker_beat_mem = "${var.celery_worker_beat_mem}"
  }
}

Removed vars section and that triggered diffs not match error.

**Comment by brainsik** [comment]
Just ran into this problem doing something similar as the original poster. I'm able to reliably reproduce this issue by updating a launch configuration to use a security group that's also being created.

Here's an example configuration:

```hcl
provider "aws" {
    region = "us-east-1"
}

resource "aws_security_group" "red" {}

resource "aws_security_group_rule" "red" {
    security_group_id = "${aws_security_group.red.id}"
    type              = "egress"
    protocol          = "-1"
    from_port         = 0
    to_port           = 0
}

resource "aws_launch_configuration" "ubuntus" {
    image_id = "ami-20d3fc4a"
    instance_type = "t2.micro"
    security_groups = ["${aws_security_group.red.id}"]
}
```

To reproduce:

1. Create `main.tf` with above configuration.
1. `terraform apply`
1. `perl -i -pe 's/blue/red/g' main.tf`
1. `terraform apply`

See [a gist of the output showing the error](https://gist.github.com/brainsik/e173701638403828ab6d).

**Comment by mitchellh** [comment]
@brainsik Tried your repro (thanks!) and this works with the latest Terraform version. I had to make minor modifications but I think I got the spirit of it. Going to believe this has been fixed!
