### ISSUE TITLE
pass parameter to resource

### ISSUE THREAD

**Issue by dbist83** [hashicorp/terraform#4489]
Hi,

I'm looking to create a volume with respected hostname. The problem is I'm not sure how to pass the hostname to the volume resource:

```hcl
resource "openstack_compute_instance_v2" "test-server" {
  
  count = "${var.count}" 
  name = "${format("test-server-%02d", count.index + 1)}"  
  depends_on = ["openstack_blockstorage_volume_v1.${var.name}-app-volume"]
..
..
}

resource "openstack_blockstorage_volume_v1" "${var.name}-app-volume" {
  
  region = "${var.region}"
  availability_zone = "${var.av_zone}"

  name = "${var.name}-app-disk"
    
  description = "app volume"
  size = "${var.app_disk_size}"
}
```

Thanks!

**Comment by phinze** [comment]
Hi @dbist83 - we don't support interpolation in resource names. Instead, we recommend using [modules](https://www.terraform.io/docs/modules/usage.html) to organize resources. Each module gets a custom name and acts as its own namespace.

So in your example, I'd organize things something like this:

```tf
# ./mymodule/main.tf
variable "name" { }
variable "count" { }
variable "app_disk_size" { } 

resource "openstack_compute_instance_v2" "test-server" {
  count      = "${var.count}" 
  name       = "${format("test-server-%02d", count.index + 1)}"  
  depends_on = ["openstack_blockstorage_volume_v1.app-volume"]
}

resource "openstack_blockstorage_volume_v1" "app-volume" {
  region            = "${var.region}"
  availability_zone = "${var.av_zone}"

  name = "${var.name}-app-disk"

  description = "app volume"
  size        = "${var.app_disk_size}"
}
```

Then you invoke the module like so:

```tf
# main.tf
module "moduleinstance" {
  source        = "./mymodule"
  name          = "myname"
  count         = 2
  app_disk_size = 123
}
```

Hope this helps! Let me know if you have further questions.

**Comment by dbist83** [comment]
Thanks phinze! I will look into it.

**Comment by dbist83** [comment]
Hi phinze,

I followed you suggestion and broke my flow to different files with different resources.
When I tried calling them from the main.tf with:

module "moduleinstance" {
  source        = "C:\\Tools\\teraform\\server_templates\\node"
  name          = "test-node"
  count         = 2
  app_disk_size = 100
}

I get the following error:

c:\Tools\teraform\env\mdaas>terraform.exe apply
←[31mError downloading modules: module moduleinstance: not found, may need to be
 downloaded←[0m←[0m

Can you pls assist?

**Comment by phinze** [comment]
Hi @dbist83, modules are initialized via `terraform get`, if you run that you should be on your way!

**Comment by dbist83** [comment]
looking good phinze!
when I ran the plan I got the following:
Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

Where should I add it?

**Comment by phinze** [comment]
The `-out` parameter is documented here:

https://www.terraform.io/docs/commands/plan.html#_out_path

The plan file that is output is passed as an argument to `terraform apply`:

https://www.terraform.io/docs/commands/apply.html

So putting that together, the commands would look something like this:

```
terraform plan -out=plan.tfplan
terraform apply plan.tfplan
```

**Comment by dbist83** [comment]
Great stuff! 
I applied the plan and it worked like magic. 
When I tried to run destroy I saw that the -plan is not supported and I should manually supply the parameters I originally provided.

I basically want to run: terraform destroy -plan myplan.tfplan (that includes all the original parameters I uses when applying)

Thanks!

**Comment by phinze** [comment]
That functionality is available as a flag on `plan`:

https://www.terraform.io/docs/commands/plan.html#_destroy

So the two commands would look like this:

```
terraform plan -destroy -out=destroy.tfplan
terraform apply destroy.tfplan
```
