### ISSUE TITLE
aws_cloudwatch_metric_alarm resource does not get attached to ELB

### ISSUE THREAD

**Issue by reid-harrison2** [hashicorp/terraform#4496]
This example aws_cloudwatch_metric_alarm resource successfully creates an alarm but that alarm is not correctly attached to the desired ELB and remains in an "INSUFFICIENT_DATA" state.

    resource "aws_cloudwatch_metric_alarm" "test-metric-elb" {
        alarm_name = "test-metric-elb"
        alarm_description = "This alarm will be created but not attached to an ELB."
        metric_name = "HealthyHostCount"
        comparison_operator = "LessThanOrEqualToThreshold"
        threshold = "1"
        statistic = "Minimum"
        evaluation_periods = "1"
        period = "300"
        namespace = "AWS/EC2"
        dimensions = { "LoadBalancerName"="reid-test-rmq-admin-elb" }
        actions_enabled = "true"
        alarm_actions = [ "arn:aws:sns:us-east-1:############:Test" ]
        ok_actions = [ ]
        insufficient_data_actions = []
    }

I also tried 

    dimensions = { 
        Name="LoadBalancerName"
        Value="reid-test-rmq-admin-elb"
    }

<img width="1077" alt="tf_elb" src="https://cloud.githubusercontent.com/assets/16409006/12098866/cea776c2-b2f2-11e5-9582-0e14d3e987ce.png">
<img width="1460" alt="tf_alarm" src="https://cloud.githubusercontent.com/assets/16409006/12098867/d2e673b4-b2f2-11e5-91e2-ef167e998c2c.png">
<img width="1461" alt="tf_alarm2" src="https://cloud.githubusercontent.com/assets/16409006/12098868/d2f0e36c-b2f2-11e5-9dd0-f5793a675e02.png">

Resulting CloudFormation template as displayed in the alarm's history:

    {
      "version": "1.0",
      "type": "Update",
      "updatedAlarm": {
        "namespace": "AWS/EC2",
        "alarmArn": "arn:aws:cloudwatch:us-east-1::############::alarm:test-metric-elb",
        "alarmConfigurationUpdatedTimestamp": "2016-01-04T19:48:20.072+0000",
        "stateUpdatedTimestamp": "2016-01-04T19:40:17.484+0000",
        "insufficientDataActions": [],
        "alarmDescription": "This alarm will be created but not attached to an ELB.",
        "statistic": "Minimum",
        "evaluationPeriods": 1,
        "comparisonOperator": "LessThanOrEqualToThreshold",
        "alarmName": "test-metric-elb",
        "threshold": 1,
        "okactions": [],
        "alarmActions": [
          "arn:aws:sns:us-east-1:############:Test"
        ],
        "actionsEnabled": true,
        "stateValue": "INSUFFICIENT_DATA",
        "metricName": "HealthyHostCount",
        "period": 300,
        "dimensions": [
          {
            "name": "LoadBalancerName",
            "value": "reid-test-rmq-admin-elb"
          }
        ]
      },
      "originalUpdatedFields": {
        "alarmConfigurationUpdatedTimestamp": "2016-01-04T19:40:17.484+0000",
        "dimensions": [
          {
            "name": "Name",
            "value": "LoadBalancerName"
          },
          {
            "name": "Value",
            "value": "reid-test-rmq-admin-elb"
          }
        ]
      }
    }

As far as I've been able to find, my dimensions syntax is valid so at this point I'm assuming this is an issue with Terraform.

**Comment by wata727** [comment]
Hi @reid-harrison2, perhaps, you should use "AWS/ELB" to namespace.
You could try to the following:

```
namespace = "AWS/ELB"
```

**Comment by reid-harrison2** [comment]
That did the trick, thanks @wata727! It was easy to overlook but the metric's namespace has to correspond to the table found here: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/aws-namespaces.html

**Comment by reid-harrison2** [comment]
That did the trick, thanks @wata727! It was easy to overlook but the metric's namespace has to correspond to the table found here: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/aws-namespaces.html
