### ISSUE TITLE
Provider: Openstack - VPNaaS

### ISSUE THREAD

**Issue by sandywater** [hashicorp/terraform#4503]
I would like to request support for VPNaaS in Terraform.  Please !!! :smile:

**Comment by nicoaina** [comment]
:+1:

**Comment by jsecchiero** [comment]
:+1:

**Comment by kessenza** [comment]
👍

**Comment by fnzv** [comment]
:+1:

**Comment by jtopjian** [comment]
Hi all,

I appreciate the enthusiasm of all the :+1: 's, however I think it's preferable to simply use the "Add a reaction" button.

In order for VPNaaS to be added, it first needs to be added to https://github.com/gophercloud/gophercloud. New extensions are added to Gophercloud as time permits for the contributors. If someone would like to start there, it would certainly help expedite this.

I understand that official support for VPNaaS was in question for the past year or so, but there has been a renewed interest in continuing to support it. That's also very promising and helps with prioritizing of new features. :)
