### ISSUE TITLE
Audit of Google Acceptance Tests for Potential Resource Name Collisions

### ISSUE THREAD

**Issue by phinze** [hashicorp/terraform#4514]
As we are starting to run the acceptance tests regularly, we're noticing a number of places where two tests can collide because they both attempt to interact with resources of the same name.

I've been making tweaks like these to fix these scenarios:

 * https://github.com/hashicorp/terraform/commit/8677f8eea7d8fe3355bd75df372519c22d3a0ae2
 * https://github.com/hashicorp/terraform/commit/c4aff4a585d85a22e40b7cba38b091d2fa04dffe

I'm being pulled away at the moment - @lwander might you have bandwidth to be able to make a pass through the other tests to make similar changes so they can be run in parallel on Travis?

I know at least we have seen the `ComputeGlobalForwardingRule` tests collide with health check `"tf-test-zero"`, but there are probably more examples hiding in there.

**Comment by phinze** [comment]
BTW - Just kicked off a rerun to work around the forwarding rule health check collision - I believe this will be our first green Travis execution of the full Google Acceptance Test suite!

https://travis-ci.org/hashicorp/terraform/builds/100413007

**Comment by lwander** [comment]
I'm happy to look into this! Do you mean that tests being run in parallel are conflicting due to names being reused?

If the travis run is all green, are we all set?

**Comment by phinze** [comment]
> Do you mean that tests being run in parallel are conflicting due to names being reused?

Yep exactly.

> If the travis run is all green, are we all set?

The travis run is green because I manually re-kicked one of the jobs that failed from a collision.

I'm guessing any fixture in the tests with `name = "foo"` where `foo` is not an interpolated `%s` could use a look, so perhaps you can fly through the output of a command like:

```
git grep 'name \+= \+"[^%]' builtin/providers/google
```

Not that they'll all need to be changed, but they could probably all use a double check. Once we get all the current tests up to snuff, I'll make sure to keep and eye on this concept in PR reviews going forward. :+1:

**Comment by lwander** [comment]
SGTM!

**Comment by phinze** [comment]
<3 @lwander
