### ISSUE TITLE
Parsing crash on lookup

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#4519]
**EDIT:** the lookup of course, needs to have `var.` on `invertbool`, and the map needs to be `"0"`, and `"1"`. But I would imagine that this needs to still give a real error and not panic.

-----

I'm thinking I'm not necessarily doing something that I should be here, still tinkering with it, but this caused a panic:

```
panic: Error reading level config: strconv.ParseBool: parsing "${lookup(invertbool, var.egress)}": invalid syntax
2016/01/05 16:28:27 [DEBUG] terraform-provider-aws:
2016/01/05 16:28:27 [DEBUG] terraform-provider-aws: goroutine 456 [running]:
2016/01/05 16:28:27 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0x822881080, 0x822bde680, 0x1, 0x1, 0x822bde602, 0x0, 0x0, 0x0, 0x0, 0x1090000, ...)
```

I have a map I'm trying to use to flip bool values around:

```
variable invertbool {
  default = {
    "true" = false
    "false" = true
  }
}
```

Here is the first code line in the trace:

```
2016/01/05 16:28:27 [DEBUG] terraform-provider-aws: 	src/github.com/hashicorp/terraform/helper/schema/resource_data.go:385 +0x20a
```

**Comment by phinze** [comment]
Thanks for the report, @vancluever - it definitely should not be panic-ing. We'll take a look!

**Comment by phinze** [comment]
Just confirmed that this is fixed via some other parser improvements that made their way onto master. The crash should be taken care of in 0.6.9! :+1:

**Comment by vancluever** [comment]
Thanks @phinze!
