### ISSUE TITLE
Mathematical order in expressions

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#4521]
The following expression:

```
"${1000 + var.index*100 + count.index + 1}"
```

With various values, was producing values of `100001` and up, depending on specific values of `var.index` and `count.index`.

I had to enclose `var.index*100` in parentheses to get it to yield the correct value.

**Comment by mitchellh** [comment]
We don't support order of operations and it is purely left-to-right at this point. This is as designed but we should probably document it. Adding it now.

**Comment by vancluever** [comment]
Thanks for the clarification @mitchellh!
