### ISSUE TITLE
terraform-provider-azure: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Rammohanrmc** [hashicorp/terraform#4525]
Because of above subject line error(found in crash.log) I am getting 
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1](https://github.com/hashicorp/terraform/issues) so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

P.S: I did executed some operations like Network creation, VM Creation, Storage Service etc... successfully a week back with out any errors. Now I just tried to create on more VM with new script but it is giving above error. even I removed new script and did terraform apply on old scripts but its giving same error.
Please help me out to fix this error.

**Comment by Rammohanrmc** [comment]
After Some Research, I did realized that this issue is occurring because, the terraform is referring to previously created LinuxVM which was closed. I did restarted the that VM, Terraform refresh, apply solved my problem.

**Comment by jen20** [comment]
Hi @Rammohanrmc. Thanks for opening an issue here. To confirm, were the steps you took:

- create instance via Terraform
- stop the instance
- try to apply other changes
- observe the crash?

Could you post the contents of `crash.log` as a gist, making sure you give it a scan for any information which might be considered sensitive?
