### ISSUE TITLE
terraform-provider-aws: "ValidationError: You cannot specify both Template URL and Template Body" when only URL was specified

### ISSUE THREAD

**Issue by tangentspace** [hashicorp/terraform#4534]
I'm trying to deploy a CloudFormation stack using a build of terraform from revision 88c3933356db8161558a720080df937e5d9f0d90 (the release binaries didn't work for me due to https://github.com/hashicorp/terraform/issues/4332).

When attempting to apply an update to the parameters of an aws_cloudformation_stack resource, it fails with the following error:
```
* aws_cloudformation_stack.api: ValidationError: You cannot specify both Template URL and Template Body.
	status code: 400, request id: 6666775e-b4cb-11e5-a916-3fb3780c8e2f
```
My template only specifies the template_url parameter, so this seems like a bug. Here is the definition of the resource that fails to update:

```
resource "aws_cloudformation_stack" "api" {
    name = "${var.environment}-api"
    template_url = "https://s3.amazonaws.com/${var.template_bucket}/${var.environment}/ApplicationStack.json"
    capabilities = ["CAPABILITY_IAM"]
    on_failure = "DELETE"
    parameters {
        ApplicationName = "api"
        Environment = "${var.environment}"
        ChefRunList = "role[api_app]"
        ELBHealthCheckTarget = "HTTP:8081/thread_status_check"
        ELBListener1 = "HTTP, 443, HTTP, 8080"
        InstanceType = "m3.large"
        VPCName = "${var.vpc_name}"
    }
}
```

**Comment by radeksimko** [comment]
Hi @tangentspace 
thanks for the report, I just reproduced this. Bugfix on the way.

**Comment by radeksimko** [comment]
See https://github.com/hashicorp/terraform/pull/4540
