### ISSUE TITLE
[feature request] [remote state] Configure via .tf files instead of separate cli command

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#4546]
It would be extremely helpful for us to be able to configure the remote state in the terraform config files instead of managing it via an additional cli command. While this is similar to #4389 I think it is different enough to warrant its own issue.

This would allow us to do something like below where the remote state storage location changes based on the variables that are defined for this project. This way if the user deploys with `terraform apply -var environment=dev` and later with `terraform apply -var environment=qa` but forgets to run `terraform remote config` it won't get mixed up.

```
remote_state {
  backend = "consul"
  backend-config = {
    address = "consul.service.dev.consul:8500"
    path = "terraform/my-app/${var.environment}"
  }
  pull = true
}
```

**Comment by jen20** [comment]
Hi @mtougeron. Thanks for opening this issue. My first instinct here is to agree with the reasoning behind this. @phinze, @catsby and @mitchellh, any thoughts on this?

**Comment by mitchellh** [comment]
Yeah this has been brought up a few times. I think its a good idea, there might be a dup issue somewhere.

For the future, when we do this, we should put it in a `terraform` block that can be used for meta-configurations to configure Terraform itself rather than what Terraform is doing. I'd prefer this:

```
terraform {
    remote_state { ... }
}
```

I can imagine other things that would go in there some day (minimum version, required plugins, etc.)

**Comment by mtougeron** [comment]
Love the required plugin possibility! Totally agree with having it in a `terraform {}` block.

**Comment by apparentlymart** [comment]
Yeah I think the original ticket for this is #1964. I'm going to close this and copy @mitchellh comment into  the other one.

**Comment by advincze** [comment]
i have this script checked in in my projects: https://gist.github.com/advincze/b33501e726707011e55fe6fa4e9adc39

it reads a .tfremote file which looks like this:
```
backend=s3
backend-config="bucket=mybucket"
backend-config="key=myproject/terraform.tfstate"
backend-config="region=eu-west-1"
```

it writes a `lock.tf` with an uninitialized variable to prevent you from accidentaly typing `terrafrom apply` 

to have this wrapper is kindof what gradle does for builds with the gradle wrapper (thus the name terraformw)
