### ISSUE TITLE
[feature request] Looping for inner resources

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#4547]
As @armon & I discussed yesterday at Lithium, we would like to be able to do looping of inner resource blocks.

For example, we would like to be able to define a `openstack_compute_secgroup_v2` like this (ignore syntax). Terraform would be executed like `terraform apply -var web-ports=80,443`

```
resource "openstack_compute_secgroup_v2" "web" {
  name = "${var.server-name}-web"
  description = "${var.server-name} security group"
  for port in ${split(",", var.web-ports)} {
    rule {
      from_port = $port
      to_port = $port
      ip_protocol = "tcp"
      cidr = "10.0.0.0/8"
    }
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

This would allow us to move more resource definitions into a module to reduce code duplication. For example, right now, without the looping, we cannot put the security group definition into a module that someone can include and pass in just a few parameters. If looping is allowed, each application would work more like this which is a lot easier to maintain across dozens of applications.

```
module "secgroup" {
  source = "git::ssh://REDACTED/terraform.git//modules/openstack/security-group"
  name = "${var.server-name}-web"
  ports = "80,443"
  create_before_destroy = true
}
```

**Comment by jen20** [comment]
Hi @mtougeron! This is definitely not on the roadmap for the foreseeable future - it would require fairly extensive changes to the definition of HCL apart from anything else. There is a broader discussion about this going on here: https://github.com/hashicorp/terraform/issues/2275 and here: https://github.com/hashicorp/terraform/pull/4343, so I'm going to close this issue and track this at #2275 for now.

I think a better pattern in this specific case might be to separate out the rules in the OpenStack security group into their own top-level resources in the same manner as the AWS Security group allows. That way you could use a resource count and element selection to index into your list. Does that sound like a workable solution?
