### ISSUE TITLE
[feature request] Conditional statements

### ISSUE THREAD

**Issue by mtougeron** [hashicorp/terraform#4548]
As @armon & I discussed yesterday at Lithium, we would like to be able to do basic conditionals for resources. We deploy to both AWS & internal OpenStack. Right now, for some of our applications, we need to maintain two sets of terraform configs for an application in order to deploy to both providers. This obviously is not desired.

We would like to be able to create a single module called "secgroups" to manage security groups for our app servers. The calling of the module would look like:

```
module "secgroup" {
  source = "git::ssh://REDACTED/terraform.git//modules/security-group"
  name = "${var.server-name}-web"
  ports = "80,443"
  create_before_destroy = true
  provider = "${var.provider}"
}
```

The module would then look something like:

```
resource "openstack_compute_secgroup_v2" "web" {
  name = "${var.name}"
  description = "${var.name} security group"
  rule {
    from_port = ${var.port}
    to_port = ${var.port}
    ip_protocol = "tcp"
    cidr = "10.0.0.0/8"
  }

  lifecycle {
    create_before_destroy = ${var.create_before_destroy}
  }

  only_if ${var.provider} = "openstack"
}

resource "aws_security_group" "web" {
  name        = "${var.name}"
  vpc_id      = "${module.aws.vpc_id}"
  description = "Security group for ${var.name}"

  ingress {
    protocol    = "tcp"
    from_port   = ${var.port}
    to_port     = ${var.port}
    cidr_blocks = ["10.0.0.0/8"]
  }

  egress {
    protocol    = -1
    from_port   = 0
    to_port     = 0
    cidr_blocks = ["0.0.0.0/0"]
  }

  lifecycle {
    create_before_destroy = ${var.create_before_destroy}
  }

  only_if ${var.provider} = "aws"
}
```

If this style of conditional is allowed then the inner attribute would need to consider it as well in the event of this example.

```
resource "openstack_compute_floatingip_v2" "floatip" {
  region = ""
  pool = "public"
  only_if ${var.create-floating-ip} = "true"
}

resource "openstack_compute_instance_v2" "server" {
  floating_ip = "${openstack_compute_floatingip_v2.floatip.address}"
}
```

Lastly, the inner attributes of a resource would also need a conditional as well.

```
resource "aws_autoscaling_group" "asg" {
  tag {
    key = "Name"
    value = "${var.server-name}"
    propagate_at_launch = true
  }
  tag {
    key = "TeamID"
    value = "${var.TeamID}"
    propagate_at_launch = true
    only_if ${var.TeamID} != ""
  }
}
```

**Comment by vancluever** [comment]
+1 on this, I am really starting to hit walls with some of the modules that I want to write because of the lack of conditional logic in the language. `only_if` sounds like a great start and, and even if it was only boolean at first it would be a great start.

**Comment by cbarbour** [comment]
I use count fairly heavily as a workaround.

```hcl
variable "openstack" {
  default = "0"
}

variable "aws" {
  default = "0"
}
```

```hcl
module "secgroup" {
  source = "git::ssh://REDACTED/terraform.git//modules/security-group"
  name = "${var.server-name}-web"
  ports = "80,443"
  create_before_destroy = true
  openstack = 1
}
```

```hcl
resource "openstack_compute_secgroup_v2" "web" {
  count="${signum(var.openstack)}"
  name = "${var.name}"
  description = "${var.name} security group"
  rule {
    from_port = ${var.port}
    to_port = ${var.port}
    ip_protocol = "tcp"
    cidr = "10.0.0.0/8"
  }

  lifecycle {
    create_before_destroy = ${var.create_before_destroy}
  }
}
```

Not the most elegant solution, but functional.

In fact, this example doesn't really require signum. You could reference the variable directly. signum is useful when testing for resource counts (E.g. `count = "${signum(5)}"`) or the presence of a string `count = "${signum(length(var.foo))}"`

One issue I've run into with this approach, is that the parser is not sensitive to the `count` argument. E.g. A reference to an undefined or invalid variable will cause the parser to throw an error, even if the actual count of the resource referencing that variable is 0.

**Comment by apparentlymart** [comment]
This seems to overlap with #1604... @mtougeron, would you mind posting your use-cases over there to consolidate the discussion?

Thanks!

**Comment by mtougeron** [comment]
@apparentlymart Thanks. I think my use case has been described by others in that thread. I've also used counts like @cbarbour suggested for the most part.
