### ISSUE TITLE
Google Cloud provisioner lacks Second Generation Cloud SQL Support

### ISSUE THREAD

**Issue by gtaylor** [hashicorp/terraform#4555]
Cloud SQL now has two flavors: First Generation and Second Generation.

Second Generation is still in beta, but is faster and a bit more flexible. I'd imagine they'll eventually phase out First Generation, since it seems like Second is a wholesale improvement over the first. More details on that on the Google Cloud blog:

http://googlecloudplatform.blogspot.com/2015/12/the-next-generation-of-managed-MySQL-offerings-on-Cloud-SQL.html

The way that disk space and hardware specs are requested have changed a bit in second generation. This can be seen on the pricing page: https://cloud.google.com/sql/pricing

You can also do neat stuff like set up a Cloud SQL proxy: https://cloud.google.com/sql/docs/sql-proxy

Needless to say, this is something that we'd find value in having!

**Comment by tphummel** [comment]
i just successfully launched a Second Generation Cloud SQL instance using TF 0.6.9:
```
resource "google_sql_database_instance" "my-db" {
  name = "my-db"
  region = "us-central"
  database_version = "MYSQL_5_6"

  settings {
    tier = "db-f1-micro"
    backup_configuration {
      enabled = true
      start_time = "17:00"
      binary_log_enabled = true
    }
    ip_configuration {
      ipv4_enabled = true
    }
  }
}
```

I think the `settings.tier` value is the key as First and Second Generation tiers have different values. 

@gtaylor have you seen different behavior to indicate TF 0.6.9 doesn't support Second Generation Cloud SQL?

**Comment by gtaylor** [comment]
I kept getting 4xx errors, but it could have been due to the name reuse
issue. I'll try again this week and report back.

Would it be worth me sending a PR with some explicit examples of both for
the docs?

**Comment by tphummel** [comment]
I'm not familiar with the name reuse issue. I'm pretty new to Google Cloud. I'd be curious to see any snippets you could provide in this thread.

**Comment by lwander** [comment]
The name reuse issue was fixed here #4577. If I understand correctly, you just need to select a different [tier](https://cloud.google.com/sql/pricing#v2-pricing) to indicate what cloud SQL generation you want to use.

**Comment by tphummel** [comment]
@lwander i agree. what you said matches my experience

**Comment by lwander** [comment]
Cool, In that case I'll close this for now.
