### ISSUE TITLE
depends_on when resouce count is more than 1

### ISSUE THREAD

**Issue by scottrobertson** [hashicorp/terraform#456]
Hey,

I have an issue with the following:

```javascript
resource "digitalocean_droplet" "app" {
  count = 2
  image = "ubuntu-14-04-x64"
  name = "app${count.index}.example.com"
  region = "lon1"
  size = "2gb"
}

resource "cloudflare_record" "app" {
  depends_on = ["digitalocean_droplet.app"]
  domain = "example.com"
  name = "${digitalocean_droplet.app.name}"
  value = "${digitalocean_droplet.app.ipv4_address}"
  type = "A"
}
```

This works perfectly fine if `digitalocean_droplet.count` = 1, but does not work if it's more than 1. I am assuming this is because it needs to depend_on `digitalocean_droplet.app.0` instead of `digitalocean_droplet.app`. Is there a way to do this without having to have a lot of strings of text in the cloud_flare record for each count.

**Comment by mitchellh** [comment]
This has been fixed for awhile. I'm not sure when a fix came in, but I tested it now and it works.
