### ISSUE TITLE
aws_cloudformation_stack parameters of type CommaDelimitedList cause stack updates to fail when list contains spaces

### ISSUE THREAD

**Issue by tangentspace** [hashicorp/terraform#4561]
Passing a list containing spaces to a CommaDelimitedList parameter in a aws_cloudformation_stack causes stack updates to fail when the parameter has not been modified.

For example, the following stack is created fine on the first apply operation, but further attempts to run apply fail because terraform always thinks the ELBListener1 parameter has changed:

``` hcl
resource "aws_cloudformation_stack" "api" {
    name = "${var.environment}-api"
    template_url = "https://s3.amazonaws.com/${var.template_bucket}/${var.environment}/ApplicationStack.json"
    parameters {
        ApplicationName = "api"
        ELBListener1 = "HTTP, 443, HTTP, 8080"
    }
}
```

The error message is:

```
* aws_cloudformation_stack.api: ValidationError: No updates are to be performed.
    status code: 400, request id: 2f0d2349-b571-11e5-86b1-d56736d214fa
```

I believe what is happening is that the AWS API returns the string with the spaces removed when terraform queries it for the current value, so terraform always thinks the parameter has changed. For the time being I am able to work around this issue by simply removing the spaces from the list.

**Comment by radeksimko** [comment]
Reproduced, thanks for the report.

Similarly to https://github.com/hashicorp/terraform/issues/4335 I think we'll have to start parsing the template itself to find out how to treat each parameter.
