### ISSUE TITLE
provider/aws: Failing acceptance ECS tests - manual intervention

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#4568]
I don't know which one of @hashicorp/terraform can do this, I just wanted to give you heads up that the reason behind [failing ECS acceptance tests in Travis](https://travis-ci.org/hashicorp/terraform/jobs/100697439#L538) is because there's a dangling ECS service & cluster. This should be just a leftover from a bug that was fixed last night by merging #4366 , specifically [this line](https://github.com/hashicorp/terraform/pull/4366/files#diff-541cd13c0077eb59a7e6688908a5cc8eR234).

The way to fix this is to go to the AWS Console:
https://us-west-2.console.aws.amazon.com/ecs/home?region=us-west-2#/clusters/terraform-acc-test/services
and remove the service (`tf-acc-ecs-svc`) and then the cluster (`terraform-acc-test`) itself.

The next run should be green, unless the damn IAM gets in the way - something I'm trying to address in https://github.com/hashicorp/terraform/pull/4447

**Comment by phinze** [comment]
Thanks for the ping! Removed the colliding resources and re-kicked the build here:

https://travis-ci.org/hashicorp/terraform/jobs/100989751

Fingers crossed for good IAM juju :wink:

**Comment by phinze** [comment]
Green! Thanks @radeksimko :grinning:
