### ISSUE TITLE
aws_autoscaling_lifecycle_hook: omitting optional param always results in diff

### ISSUE THREAD

**Issue by elblivion** [hashicorp/terraform#4572]
Hi folks,

Leaving out the optional `default_result` attribute of the `aws_autoscaling_lifecycle_hook` will make `plan` always see a difference after the first `apply`, since the AWS API will fill this in on creation with the value `ABANDON`:

```
~ aws_autoscaling_lifecycle_hook.foobar
    default_result: "ABANDON" => ""
```

I tried adding an `else` here to set the default value the AWS API uses in case there is no input, but no luck, I guess this is only read on apply and not when diffing:

https://github.com/hashicorp/terraform/blob/45773184c476d85c8c177eabce2aa68bd484db92/builtin/providers/aws/resource_aws_autoscaling_lifecycle_hook.go#L142

Expected behaviour is that Terraform is aware of the default value and does not produce a diff.

I've worked around this by making the default_result explicit, if there is a standard way to deal with this pattern (Cloud service API adding default values when omitted) I'd be happy to work on this myself.

Thanks!

**Comment by stack72** [comment]
Hi @elblivion this needed to be changed to a computed value. There is a PR just about to hit for this with a test to prove that it's now working as expected

I also updated the docs to note that the default is ABANDON

**Comment by elblivion** [comment]
Awesome, thanks @stack72!
