### ISSUE TITLE
Remote state: A successful 'apply' or 'destroy' should imply 'remote push'

### ISSUE THREAD

**Issue by MikeSchuette** [hashicorp/terraform#4580]
I can't think of a use case where you wouldn't want to push state as soon as it's been successfully updated.  It seems to open an unnecessary window of opportunity for desynchronization, especially in a data-driven workflow as discussed in #4169 .

Hoping to solicit opinions as to whether or not these should remain atomic operations.

**Comment by hansnqyr** [comment]
:+1:  would love this to be the default with a switch/env variable to disable

**Comment by apparentlymart** [comment]
Hmm... Isn't this already the case? I don't think I have ever run "terraform remote push" explicitly... I always just let it happen automatically.

It also happens after a refresh.

**Comment by phinze** [comment]
Yep this is currently the case! :+1:

When remote state is configured, any updated state as seen by a refresh will be automatically pushed.

Currently this happens on `plan`, `apply`, and `destroy`, but we're planning to update the behavior of `plan` to make it easier to run it safely without accidentally colliding with another running apply. But in the `apply` and `destroy` case, this is how it works today!
