### ISSUE TITLE
Remote state: If enabled have a checked in tfstate file

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/terraform#4584]
If remote config has been set, create a tfstate file that can be checked into version control containing details regarding details on the type and remote config that it used. An alternate approach would be to use the existing terraform.tfstate (placed in `.terraform/` by default) that contains that information, but exclude the "modules" JSON object which might contain sensitive output information and rename it to terraform.rtfstate or the like to avoid having it ignored. When `terraform plan/apply` is called and that file exists it should tell the user that there is an existing remote tfstate and let the user setup the remote config to pull it down.

Something in the essence of:
```json
{
    "version": 1,
    "serial": 0,
    "remote": {
        "type": "s3",
        "config": {
            "bucket": "my-terraform-states",
            "key": "consul/tst/terraform.tfstate"
        }
    }
}
```

This is important when multiple developers are working on the same terraform project. If a developer forgets to `terraform remote config` and `terraform remote pull` after cloning, he might have a clean (i.e. non-existing) tfstate in his environment, and thus encounter issues when doing a `terraform apply` if he is not aware that the infrastructure already exists. These issues can be duplicate resource creation, destruction and recreation of resources, or straight up errors of not being able to create already-existing resources.

**Comment by phinze** [comment]
Thanks for the solid explanation of this use case, @cleung2010. Getting a remote state config that can be checked in without the state being checked in is definitely something we'd like to solve. See #3538 for another discussion around the topic and #1964 for a proposed solution. I'm going to consolidate this issue with that one so we can keep the discussion focused.
