### ISSUE TITLE
Variables not passed to module

### ISSUE THREAD

**Issue by aburnett** [hashicorp/terraform#4585]
This is a feature request to change the behavior described in #2648. I have a module that requires a username and password. With the current behavior I have to add variables to every definition where this module is used so that I can pass this information along. This results in a lot of copy & paste.

There would be less duplication of code required if the variables in the root could be made available to the modules.

**Comment by cleung2010** [comment]
+1 I was going to open an issue addressing exacting this. I really like the concept of modules, but the way it's handling variables right now can make modules quite cumbersome to use, especially if that module contains more than a few variables.

**Comment by roderickrandolph** [comment]
:+1:

**Comment by phinze** [comment]
Hey folks, thanks for the feature request. I totally understand the desire for less copy/paste. However, making top-level variables available to the entire module tree would break the encapsulation that's important to the design of modules. Giving each module clearly defined inputs and outputs, while it does result in more verbose configs, makes composing modules consistent.

If we were to allow the full tree of nested modules access to top-level variables without passing them in (in other words, if we were to make all config variables global), tracing the source of a given variable becomes much harder.

For these reasons, we're unlikely to make this change, so I'm going to close this thread to indicate that.

I'm happy to discuss further if there's any way I can help explain better or if you have any further questions.
