### ISSUE TITLE
Support AWS ELB Backend Authentication

### ISSUE THREAD

**Issue by ewdurbin** [hashicorp/terraform#4587]
I tried to swing this in #3276 but it seemed to die on the vine. Let me know if filling out more details here would be helpful or if copying explanation from the PR is the right move.

**Comment by astoltz** [comment]
If it helps, here's how to create the policy using the CLI:

```bash
# Create a public key policy for the accepted public keys the backends can use
aws elb create-load-balancer-policy --load-balancer-name load-balancer-name --policy-name policy-1-name --policy-type-name PublicKeyPolicyType --policy-attributes AttributeName=PublicKey,AttributeValue=PUBLICKEYHERE

# Create a backend policy that uses the Public Key policy
aws elb create-load-balancer-policy --load-balancer-name load-balancer-name --policy-name policy-1-name-enforce --policy-type-name BackendServerAuthenticationPolicyType --policy-attributes AttributeName=PublicKeyPolicyName,AttributeValue=policy-1-name

# Tell the load balancer to use the Backend Authentication Policy
aws elb set-load-balancer-policies-for-backend-server --load-balancer-name load-balancer-name --instance-port 443 --policy-names policy-1-name-enforce
```

"policy-1-name" is what shows up in the web console as the certificate name. The enforcement policy name doesn't matter.

The Public key is the public certificate with newlines stripped. It does not contain the "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----" markers.

**Comment by ewdurbin** [comment]
now this is an issue i haven't thought about for a long time, but now that we are starting to *really* use terraform it would be great to have this as a security primitive in our infrastructure.

**Comment by ewdurbin** [comment]
🎉
