### ISSUE TITLE
DynECT provider?

### ISSUE THREAD

**Issue by solarce** [hashicorp/terraform#459]
I didn't see another issue for this yet, so I wanted to file it. While I don't know much Go, I may take a stab at it.

One of my coworkers added basic support to 'knife ec2' in ruby, so it's not terribly difficult to get going, https://github.com/jeremyd/knife-ec2/commit/e273e51759b9882fe98bda6b782111a3756885ce

**Comment by phinze** [comment]
Hey hey we landed this in #2807. :+1: :grinning:

**Comment by solarce** [comment]
sweeeeet
