### ISSUE TITLE
aws_route invalid CIDR crash

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform#4591]
I tried to cheat on providing CIDR blocks and got a crash for my efforts ;)

```
...
InvalidParameter: Parameter route=10.1.1.0/23 fails its validation function
    status code: 400, request id:
...
* connection is shut down

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: runtime error: invalid memory address or nil pointer dereference
2016/01/08 16:02:31 [DEBUG] terraform-provider-aws: [signal 0xb code=0x1 addr=0x0 pc=0x18c7e3]
2016/01/08 16:02:31 [DEBUG] terraform-provider-aws:
2016/01/08 16:02:31 [DEBUG] terraform-provider-aws: goroutine 1120 [running]:
2016/01/08 16:02:31 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.routeIDHash(0x822fbbc80, 0x0, 0x0, 0x0)
2016/01/08 16:02:31 [DEBUG] terraform-provider-aws:     /src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:303 +0xa3
2016/01/08 16:02:31 [DEBUG] terraform-provider-aws: github.com/hashicorp/terraform/builtin/providers/aws.resourceAwsRouteCreate(0x822fbbc80, 0x8f4aa0, 0x822cbc2d0, 0x0, 0x0)
2016/01/08 16:02:31 [DEBUG] terraform-provider-aws: /src/github.com/hashicorp/terraform/builtin/providers/aws/resource_aws_route.go:161 +0x9bd
```

**Comment by jen20** [comment]
Hi @vancluever! I think I've fixed this, but do you have an example of the configuration which caused this?

**Comment by vancluever** [comment]
Hey James,

Unfortunately the config is abstracted thru probably half a dozen Terraform
modules (not nested in each other, heh, but just all a part of setting up a
full VPC) so it's hard for me to rip a single config out of it
specifically, but I think it's either the VPN route or the regular route
resource that could possibly be doing it. It was for sure something in my
VPN module doing it though - when I fixed the bad CIDR and just
re-configured it to take two correctly divided subnets instead, there was
no crash.

Early next week I'll dig into the config a bit to find what route resources
that module is consuming.

**Comment by catsby** [comment]
Hey Friends – I believe this issue to be resolved. Please let us know if you're still hitting it.
