### ISSUE TITLE
Website updates cause pretty hilarious no-CSS rendering

### ISSUE THREAD

**Issue by apparentlymart** [hashicorp/terraform#4593]
Each time the Terraform website is rebuilt, the HTML is updated so that it references the CSS using what I assume is a hash of the content of the CSS.

My browser seems to cache the old HTML for some time, but for some reason doesn't have the old CSS cached, so it ends up trying to load the CSS at the old URL until I force-refresh, with rather hilarious consequences:

![terraform-site-after-release](https://cloud.githubusercontent.com/assets/20180/12217465/7239ac9e-b6b6-11e5-971c-f0d1e942d062.png)

This seems to happen separately for the home page and the docs pages, I guess because they use different CSS.

Unfortunately by the time I've loaded it once it's too late to open the Network tab in my browser to try to understand what exactly is going on here. I don't *think* there's anything weird about how my browser is configured that would make this unique to me, but then I'm kinda surprised nobody else reported this so maybe this is just something strange on my end...

**Comment by partamonov** [comment]
Saw same.

**Comment by radeksimko** [comment]
I remember always having some assets related issues after almost each release. I think @phinze was mentioning the other day it has something to do with CloudFront or another CDN `terraform.io` uses.

**Comment by phinze** [comment]
Yep this has definitely been an funky issue we've had for a while now. Luckily it should soon be solved! All HashiCorp static website hosting is in the process of being re-vamped to be S3+fastly-based. This work is underway so expect updates soon! (Guessing within the next few weeks.)

**Comment by phinze** [comment]
We're [switched over to Fastly+S3](https://www.hashicorp.com/blog/serving-static-sites-with-fastly.html) now. Website updates sometimes take a minute to show up, but CSS rendering should be consistent.
