### ISSUE TITLE
Crash after destroy and apply

### ISSUE THREAD

**Issue by Timer** [hashicorp/terraform#4601]
Per request of the CLI, here is the error log.

https://gist.github.com/Timer/d115f8e61e42b7b6f663

tfstate and tfstate.backup are both
```json
{
    "version": 1,
    "serial": 4,
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {}
        }
    ]
}
```

Provider left in dirty state with resources created but not logged.

**Comment by catsby** [comment]
Hey @Timer – do you by chance have an example config that demonstrates this (minus any secrets)? Your error log suggests the `resp`, or `resp.StatusCode ` here is nil:

- https://github.com/hashicorp/terraform/blob/master/builtin/providers/digitalocean/resource_digitalocean_droplet.go#L189-L192

a config would help a bunch, but no worries if you don't have one handy, we'll take a look when we can

**Comment by Timer** [comment]
I do not have the exact configuration I used, @catsby however it was very much a one-off it seemed. I deleted the resources created on DO and ran `terraform apply` again on the same **exact** config, and it worked fine. The only thing out of the ordinary on the run that crashed is that the droplet was taking longer than average to provision.

**Comment by catsby** [comment]
That's strange @Timer , thanks for following up.

I'm going to go ahead and close this then. If you hit it again please let us know.

Thanks!
