### ISSUE TITLE
Confusing docs regarding aws elb ssl_certificate_id

### ISSUE THREAD

**Issue by aldarund** [hashicorp/terraform#4612]
https://www.terraform.io/docs/providers/aws/r/iam_server_certificate.html
Have 
   instance_port = 8000
    instance_protocol = "http"
    lb_port = 443
    lb_protocol = "https"

Instance protocol http  and lb_protocol https.  And have ssl_certificate_id  attribute.
While in
https://www.terraform.io/docs/providers/aws/r/elb.html
stated that ssl_certificate_id is :+1: 
Only valid when instance_protocol and lb_protocol are either HTTPS or SSL

So in first page only one protocol is https and on second page its said that both should be https.

**Comment by tcsiwula** [comment]
I also found this documentation confusing.
