### ISSUE TITLE
winrm file provisioner seems to perform inconsistently

### ISSUE THREAD

**Issue by astrally2000** [hashicorp/terraform#4615]
Hi all,
Apologies, I'm a bit of a noob with terraform, but I've been playing around with terraform and impressed by the potential. 
Sadly it seems most of the resources are focused on linux workloads with limited examples of bootstrapping for windows clients. 
I'm looking at using prebaked AMIs (so I know WinRM is configured and I have a defined admin/password combo) and trying to perform DomainJoin as part of the bootstrap, so that I can pass in domain join password from command line as opposed to saving it within the configuration (although these attached examples have it within the commented out user_data)

I'm having some issues with the file copy process executing consistently, in the two attached logs and configurations I have one with a file provisioner and remote-exec which copies all the files, whilst crashing at the inline provisioner (windows.tf_with_file_provisioner) as the period isn't recognised.
Meanwhile the other terraform file copy fails (some of the files copy but not all of them) despite having the inline provioner commented out.
How can I get more detailed information describing what is happening during the file copy? 
Are there more references around syntax of remote-exec for  windows, I've searched the terraform google-group for some limited references. 
ie if I want to call a powershell command, do I need to call it from cmd, or simply call the script directly? 

```js
   provisioner "remote-exec" {
       inline = [
        "powershell someps.ps1",		]
    }
```

What about slashes on windows? 
Do I need to reverse them, as per file provisioner
ie         destination = "c:\\tools"
What about different arguments passed after a powershell script, what's their syntax?
I look forward to your response,
Thanks
Andrew

**Comment by svanharmelen** [comment]
@astrally2000 I just edited your post as I noticed the `.tf` files contain your AWS access and security keys... So I removed the links to those zipfiles and asked GitHub to remove the files from their cache (which they did). So people no longer have access to the files, yet I still strongly advice you to change your keys asap.

As for your issue/questions... Does the `c:\tools` directory exist? As I think it will not be created automatically when moving a file into the non-existing dir.

> ie if I want to call a powershell command, do I need to call it from cmd, or simply call the script directly?

You will need to call this from cmd.

**Comment by partamonov** [comment]
@svanharmelen it should create dir, if it's not in place

> If the source is /foo (no trailing slash), and the destination is /tmp, then the contents of /foo on the local machine will be uploaded to /tmp/foo on the remote machine. *The foo directory on the remote machine will be created by Terraform*.

> If the source, however, is /foo/ (a trailing slash is present), and the destination is /tmp, then the contents of /foo will be uploaded directly into /tmp directly.

About syntax question.
I'm running `C:/opscode/chef/bin/chef-client -j c:/chef/first-boot.json` in inline.

But if you want to run `powershell.exe -ExecutionPolicy RemoteSigned -Command` make sure you escaped it correctly.

Example:
```
"powershell.exe -ExecutionPolicy RemoteSigned -Command ^& '${path.cwd}\\templates\\Database\\mssql\\Install database.ps1' -NonInteractive -DatabaseServer ${aws_db_instance.db.address} -AdministratorUserName ${var.instance_admin} -AdministratorUserPassword ${var.instance_password"
```

**Comment by astrally2000** [comment]
Thanks guys - @svanharmelen I seemed to have removed the creds from one of the files but not the other, so thanks for that. Have cycled my creds and spent the morning re-familiarising myself with elements of Cloudtrail to ensure no new resources/backdoors had been created :).
Back to terraform issue, the folder existed, however the issue I was experiencing was that not all files were being copied. I'm trying again with DEBUG level enabled to see if I can get more information. 
Thanks also for your assistance with the syntax and escaping. Will report back after more testing. Cheers!

**Comment by astrally2000** [comment]
I've tried repeating a few times now and getting consistent copying of files. 
Closing
Thanks again.

**Comment by amsharm** [comment]
Hi, I know this topic is closed, but I have a question relevant to this, and I can't find the answer elsewhere. I'm trying to use Chef Provisioner with AWS Windows instances but Terraform keeps timing out due to winRM issues. astrally2000, you mentioned in your post that you are using pre-baked AMIs with winRM already configured. How did you do this? Could you point me towards a guide that might help me with this?

I tried configuring winRM through user data, but that hasn't helped. Thanks for your help

**Comment by astrally2000** [comment]
@armsharm I used this project to create a packer AMI for a windows instance which was already configured to have WinRM configured, https://github.com/packer-community/packer-windows-plugins
From memory I don't think you can do it through user-data without having initially configured winrm on Windows servers as they don't have it enabled by default.

**Comment by stephensmalls** [comment]
It seems to me that terraform uses CMD to run inline remote-exec commands. I use about 95% powershell and 5% CMD when configuring a Windows Instance. I think you would get more users if you made configuring windows with powershell a bit easier.
