### ISSUE TITLE
Contributing to vCloud provider needs clarification on underlying driver

### ISSUE THREAD

**Issue by jkinred** [hashicorp/terraform#4619]
Pretty cool to see this functionality land in a release.

I want to contribute some enhancements but I'm a bit concerned about the underlying vCloud library.

The vCloud provider references:
https://github.com/hmrc/vmware-govcd

Which is a fork of:
https://github.com/vmware/govcloudair

The hmrc fork has diverged quite significantly from the vmware repo.

Specifically, I want to add the ability for IP addresses to come from a static pool. It's easy to do in the hmrc repo but it's hard to see how they will end up back in the vmware repo.

Could @phinze @devopsbrett please weigh in on where they see this going as the underlying library is crucial for the functionality and stability of the vcd provider.

**Comment by devopsbrett** [comment]
Hi Jonathan,

The changes from vmware/govcloudair were significant enough for us to fear backwards compatibility issues. We commented on one of the issues on that repo https://github.com/vmware/govcloudair/issues/2  saying that it may be worth creating a new repo on their side but have not heard back from them as yet (Hopefully this will change as they see more people using this provider). In the mean time we would love to have you fork from https://github.com/hmrc/vmware-govcd and issue a pull request back to that. We welcome any contributions and would love to see the functionality of this project grow.

Regards,

Brett

**Comment by jkinred** [comment]
Thanks for pointing me at that issue. I wasn't aware that the two libraries are targeting different products (vCloud Director and vCloud Air).

My target is actually vCloud Air Subscription and without realising the issue above I have successfully provisioned a vApp there using your vcd provider.

It seems then, that this issue is more complex.

Should the future see:
* Separate vcd and vca providers each based off their respective libraries
* A single vcloud provider in Terraform hiding the respective libraries under the hood (and perhaps a merged library should that eventuate)

I've asked on that thread where this is headed. Either way it seems like there is potential for a lot of duplicated effort at both the Go library level and within Terraform.

In the short term I see myself (and other vCloud Air users) with two options:
* Keep using the vcd provider, submitting pull requests into https://github.com/hmrc/vmware-govcd and hope it keeps working with vCloud Air (and doesn't break vCloud Director)
* Duplicate your vcd provider into a vca provider and base it off https://github.com/vmware/govcloudair

What are your thoughts @devopsbrett?

**Comment by robcoward** [comment]
Hi @jkinred. At Skyscape we have a vested interest in both the library and the terraform vcd provider and are also in the process of chasing down VMWare through our account management team to establish if they plan to keep the vmware/govcloudair library dedicated to vCloud Air or if they are prepared to accept PRs for vCloud Director support as well. 

Personally I'm hoping for the latter, and plan to work with @devopsbrett to get the 2 forks merged and update the vcd provider to just use vmware's library. I have a number of enhancements to the vcd provider in the planning and would rather get a merge done sooner rather than later before the forks diverge too much further.

My recommendation for the short-term is to carry on working with hmrc/vmware-govcd and submit your PRs there.

I'll update this issue as I learn more.

**Comment by robcoward** [comment]
@jkinred the hmrc fork has been merged back upstream into the vmware/govcloudair repo and I about to start making changes to all the references throughout the terraform code to make use of the govcloudair library. Hope to raise a PR in the next week or so.

**Comment by mrjcleaver** [comment]
Cross ref: https://github.com/hashicorp/terraform/issues/9076

**Comment by anilybba** [comment]
In case anyone digs up these dinosaur tracks when looking into the vcd provider, it looks like Rob and team forked the official vmware library and are supporting it directly, hence the references to ukcloud/govcloudair in the code now. See #11535
