### ISSUE TITLE
vcloud director provider needs a allow_unverified_ssl argument

### ISSUE THREAD

**Issue by trodemaster** [hashicorp/terraform#4620]
I built out a simple test .tf config file to deploy a single vm with vCloud provider. As soon as it attempts to connect I get a SSL error. 

"Something went wrong: error finding LoginUrl: Get https:/vcloud.company.com/versions: x509: certificate signed by unknown authority"

Looking at the vSphere provider it has the allow_unverified_ssl argument. Please add this capability to the vCloud provider as well. 

debug log https://gist.github.com/trodemaster/8f3a1a2122704e81bc92
config file https://gist.github.com/trodemaster/c646f7e49acee7779623

**Comment by devopsbrett** [comment]
Hi @trodemaster 

Thank you for pointing out this omission. I will try and have a pull request to address this issue as soon as possible.

Regards,

Brett

**Comment by tsugliani** [comment]
+1 for this feature.

Thanks @devopsbrett !

**Comment by superseb** [comment]
I used the following to make it work, can help with the pull request if you want @devopsbrett 
```
+        "crypto/tls"
-                       Http:       http.Client{Transport: &http.Transport{TLSHandshakeTimeout: 120 * time.Second}},
+                       Http:       http.Client{Transport: &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, TLSHandshakeTimeout: 120 * time.Second}},

```
