### ISSUE TITLE
provider/azure: support for custom data

### ISSUE THREAD

**Issue by gosuri** [hashicorp/terraform#4624]
I was wondering if there are any plans for adding support for custom data when creating vm. The API seems to support it https://msdn.microsoft.com/en-us/library/azure/mt163591.aspx

I could also send a patch if you'd like.

**Comment by xied75** [comment]
@gosuri I suggest you make the PR if you got time, seems everything under azure take ages to get pulled.

**Comment by stack72** [comment]
Closed via #8158
