### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by WillAbides** [hashicorp/terraform#4633]
The configuration below intermittently crashes on `terraform apply`.

[crash.log](https://gist.github.com/WillAbides/36d3fe9157e699718954)

```hcl
variable "app_hosts_count" {
  default = 6
}

variable "cluster_name" {
  default = "foo"
}

resource "template_file" "app_instance_names" {
  count = "${var.app_hosts_count}"
  template = "${var.cluster_name}-app-${count.index}"
}

output "foo" {
  value = "${join(",", template_file.app_instance_names.*.rendered)}"
}
```

**Comment by phinze** [comment]
Hi @WillAbides, thanks for the report - we'll get this looked at.

**Comment by phinze** [comment]
Hi @WillAbides - I believe this PR should fix the underlying issue here: https://github.com/hashicorp/terraform/pull/4694

**Comment by WillAbides** [comment]
Thanks.  I don't have time to check it today, but this looks like exactly the same issue.

**Comment by phinze** [comment]
Sounds good - I'm fairly certain the issue should be solved with that PR, so I'm going to close this, feel free to follow up if not and we can swing back around. :+1:
