### ISSUE TITLE
new AWS region ap-northeast-2 (Seoul) not supported

### ISSUE THREAD

**Issue by danielnbarbosa** [hashicorp/terraform#4635]
AWS just launched a new region and I like to block access to all unused regions.  I get this error when I try to use `ap-northeast-2`:

Error refreshing state: 1 error(s) occurred:

* 1 error(s) occurred:

* Not a valid region: ap-northeast-2

**Comment by discogestalt** [comment]
+1

Was just about to open this issue myself :-)

**Comment by phinze** [comment]
Done in #4637 - thanks @discogestalt!
