### ISSUE TITLE
aws_route53 cannot destroy records

### ISSUE THREAD

**Issue by chadgrant** [hashicorp/terraform#4641]
after a recent pull / build, I can no longer destroy existing route 53 records.

Error applying plan:

4 error(s) occurred:

* aws_route53_record.zks: InvalidInput: Invalid request
        status code: 400, request id: 2cd5168e-b8b2-11e5-831b-eff1008a6e60
* aws_route53_record.zk.1: InvalidInput: Invalid request
        status code: 400, request id: 2cd564af-b8b2-11e5-831b-eff1008a6e60
* aws_route53_record.zk.0: InvalidInput: Invalid request
        status code: 400, request id: 2cdc1b2e-b8b2-11e5-87f0-afa219da1fa5
* aws_route53_record.zk.2: InvalidInput: Invalid request
        status code: 400, request id: 2cdc432a-b8b2-11e5-a084-f7f3c04e7250

**Comment by catsby** [comment]
Hey @chadgrant – do you have any configuration that reproduces this issue? I'm not having any issue creating/destroying Route 53 records

**Comment by rvangundy** [comment]
I recently had this issue as well. This is a total hunch as I don't have a configuration set up right now to test this, but I wonder if this occurs when attempting to destroy a Route53 record that was created with a previous version of Terraform?

**Comment by chadgrant** [comment]
Yes, it was a previous version, luckily I am not in production yet so I was able to manually destroy everything, delete state and it works again.

I was just getting private_ip from ec2 instances in config, very simple.

**Comment by catsby** [comment]
Does anyone know what previous build of Terraform they were using? 
I'm not currently aware of any changes in the resource that would trigger this, but if I knew an approximate version I could dig in more

**Comment by mavin** [comment]
I'm seeing something similar. I can't be sure since multiple people were working on this config but judging from our commit history and the release timeline, I believe records created with 0.6.6 are not able to be destroyed by 0.6.9.

**Comment by sriddell** [comment]
We're seeing the same thing.  Records that were created with terraform 0.6.6 cannot be destroyed by terraform 0.6.9.

**Comment by catsby** [comment]
Hello – sorry for the delay, I'm actively working on this. 
I need some more information, specifically, are any of you who have hit this problem using `weight`?

**Comment by mavin** [comment]
No, we're just letting TF use its defaults.

**Comment by catsby** [comment]
Can anyone share a type of record that they are using? CNAMEs, alias, etc? I've reproduced this, and even had a patch for it, but now I'm not sure I have all the edge cases covered so I'm looking for more information. 
Thanks!

**Comment by catsby** [comment]
I've opened https://github.com/hashicorp/terraform/pull/4892 to fix this. It should cover all the bases, but I would appreciate if anyone could take it for a spin and confirm, or provide other info.

Thanks!
