### ISSUE TITLE
Use Travis API for build triggering for acceptance tests

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#4646]
How about using the API instead of pushing to each branch?
https://docs.travis-ci.com/user/triggering-builds/

I think (288) people watching this project and their Github timelines would appreciate it :)

![screen shot 2016-01-12 at 10 52 33](https://cloud.githubusercontent.com/assets/287584/12261698/b73453ce-b91a-11e5-8d9a-18dceb415359.png)

**Comment by stack72** [comment]
Closed as we no longer use Travis for acceptance testing
