### ISSUE TITLE
Interpolation docs hotlink generation error

### ISSUE THREAD

**Issue by jedineeper** [hashicorp/terraform#4647]
Sorry, I'd normally put in a PR to fix these trivial issues, but I can't see why certain commands don't generate a hotlink when the other commands do?

On https://www.terraform.io/docs/configuration/interpolation.html the commands format, length and replace don't get hotlinks when others are fine. I can't see any common elements that might block the link being generated...

**Comment by stack72** [comment]
Hi @jedineeper 

This seems to be working as expected on the website right now:
* https://www.terraform.io/docs/configuration/interpolation.html#length_list_
* https://www.terraform.io/docs/configuration/interpolation.html#replace_string_search_replace_
* https://www.terraform.io/docs/configuration/interpolation.html#format_format_args_

I am going to close this - please let me know if you can still see hte issue

Paul
