### ISSUE TITLE
AWS directory_service - doco update and subnet number coiunt

### ISSUE THREAD

**Issue by davehodgson** [hashicorp/terraform#4648]
The document at https://www.terraform.io/docs/providers/aws/r/directory_service_directory.html states

"subnet_ids - (Required) The identifiers of the subnets for the directory servers (min. 2 subnets in 2 different AZs)."

Which I read to mean that I need to supply AT LEAST 2 subnets, but can supply more. When I tried with 3 subnets it threw an error 

"aws_directory_service_directory.directory-service: InvalidParameterException: Invalid subnet ID(s). They must correspond to two subnets in different Availability Zones."

Admittedly 2 of the subnets are in Us-West-2b and one is in US-West-2a availability zones so I have two subnets in the same and one in a different one which I thought met the statement in the documentation. I haven't tried it with 3 in seperate AZs

When I create one manually via the AWS console I see I can only add 2 - as in 2 is the MIN and MAX required. 

So I suggest the following:

1. Update documentation to state it needs to have exactly 2 subnets, in different AZs

2. Add a check to the code to throw an error if provided with more than 2 subnets, or perhaps change the attributes to access 2 subnets (subnet1 and subnet2) instead of a list of subnets.

**Comment by stack72** [comment]
Hi @davehodgson 

this will be fixed via #7529 - i will get this merged when the build goes green

Thanks

Paul
