### ISSUE TITLE
Terraform destroy fails with cycle error.

### ISSUE THREAD

**Issue by aldarund** [hashicorp/terraform#4649]
When i try to destroy terraform gives me a cycle error. And the error message gives zero insights about what is wrong. 
```
creating plan: 1 error(s) occurred:

* Cycle: aws_iam_server_certificate.rent_cert (destroy), aws_iam_server_certificate.rent_cert, aws_security_group.elb_with_ssl (destroy), aws_security_group.elb_with_ssl, aws_elb.rentapp_service, aws_security_group.ecs_node (destroy), aws_security_group.ecs_node, aws_iam_instance_profile.ecs (destroy), aws_iam_role.ecs_role (destroy), aws_iam_role.ecs_role, aws_iam_instance_profile.ecs, aws_launch_configuration.ecs (destroy), aws_key_pair.deployer (destroy), aws_key_pair.deployer, aws_launch_configuration.ecs, aws_autoscaling_group.ecs, aws_autoscaling_group.ecs (destroy), aws_elb.rentapp_service (destroy)
````

And the order of items in cycle every time is different.
Is there a way to see what is wrong and how to fix it?

**Comment by catsby** [comment]
Hey @aldarund – do you have a configuration file that demonstrates this? If you could share one (minus any secrets) that would be helpful.

**Comment by aldarund** [comment]
Well, there a lot of conf but yes i have it. Will provide it tomorrow

**Comment by aldarund** [comment]
https://dl.dropboxusercontent.com/u/597502/bhfgh.zip

**Comment by salizzar** [comment]
I have the same issue here. Code available at https://github.com/salizzar/zadni

**Comment by catsby** [comment]
I took a look at both projects, thanks for providing them! 

The issue I see is likely specifying a resource with `create_before_destroy` which depends on another resource which **does not** also specify `create_before_destroy`. 

Both examples provided have a launch configuration with `create_before_destroy` (which is recommended) referencing a security group which does not have that lifecycle block.

The limitation is documented here:

- https://www.terraform.io/docs/configuration/resources.html

I'm terribly sorry you've hit this. It's a known issue and we're aware the the error message you receive is not very helpful at all, as well as the limitation to begin with... 

We're doing our best to improve this, sorry for the poor experience :frowning: 

Unfortunately there's not a lot more I can do here. If you're using `create_before_destroy`, any referenced resource needs to also have that lifecycle block. 

Please let us know if there's anything else
