### ISSUE TITLE
Crash after adding identifiers to aws_rds_cluster_instance (unexpected EOF)

### ISSUE THREAD

**Issue by sheeley** [hashicorp/terraform#4651]
Terraform version: v0.6.9

Steps to reproduce:
- Create aws_rds_cluster
- Create aws_rds_cluster_instance without identifier 
```
resource "aws_rds_cluster_instance" "cluster_instances" {
  count = 2
  cluster_identifier = "${aws_rds_cluster.default.id}"
  instance_class = "${var.rds_instance_type}"
  db_subnet_group_name = "${aws_db_subnet_group.default.name}"
}
```
- Update aws_rds_cluster_instance to have an identifier
```
resource "aws_rds_cluster_instance" "cluster_instances" {
  count = 2
  identifier = "lumen-${count.index}"
  cluster_identifier = "${aws_rds_cluster.default.id}"
  instance_class = "${var.rds_instance_type}"
  db_subnet_group_name = "${aws_db_subnet_group.default.name}"
}
```

*Additional hairy piece: as I was running `terraform apply`, I had to close my laptop, so the crash could be caused by that. `apply`, `destroy`, `refresh` all fail.*

Errors:
```
Error refreshing state: 3 error(s) occurred:

* aws_elb.ui: unexpected EOF
* aws_rds_cluster_instance.cluster_instances.1: unexpected EOF
* aws_rds_cluster_instance.cluster_instances.0: unexpected EOF
```

[output and .tf gist here](https://gist.github.com/sheeley/1645ea3ed476de21f5e1)

**Comment by sheeley** [comment]
@catsby any additional information I can provide? I'm about to start fresh and manually delete the resources that were created, but happy to keep things around that could be useful.

**Comment by catsby** [comment]
I believe what you've provided is sufficient, I just haven't been able to get to this, I'm sorry :frowning:

**Comment by sheeley** [comment]
No worries! I just wanted to be sure to provide enough information. :+1:

**Comment by catsby** [comment]
Hey @sheeley sorry for the long, long delay here.

I've spent some time trying to reproduce this and so far cannot. This specific issue is likely from _something_ related to the laptop closing... The line that your gist shows the panic is from reading the `db.DBClusterIdentifier`, which should have a value. 

I realize this reply comes months later, and you have likely moved on, but if you do by chance have more information e.g. a reliable way to reproduce, I'll take another look.

Thanks! And I apologize again for the long silence here :/

**Comment by sheeley** [comment]
No worries - I haven't run into it in ages, and I know it's silly to expect success after closing the laptop. Thanks for looking into it!
