### ISSUE TITLE
How could I extract plugin schemas?

### ISSUE THREAD

**Issue by wholroyd** [hashicorp/terraform#4652]
I am trying to write some tooling that would make writing Terraform definitions easier by trying to provide an intellisense of what the available providers and provisioners take for input and provide for output. It looks like from the code, there is a schema that keeps track of what goes in and out. Is there a way to expose this data somehow to tools that want to know?

It seems like the bins for those just output to the console that "i'm a plugin for terraform, so please go use terraform itself". Would it be feasible to add something to whatever creates the bins to hook up that default message to take a hidden argument on the command line that outputs the schema for the plugin?

What are some other options?

**Comment by jen20** [comment]
Hi @wholroyd! This is a great idea, and coincidentally something I was working on as a side project, though I never got very far with it. My idea was to add resource completion as a top level CLI command to Terraform, and then provide some kind of equivalent to GoCode etc. Is this something you're interested in working on?

**Comment by wholroyd** [comment]
I'm useless with Golang, although I'm trying to learn in my spare time. So while I have no problem helping out, it will be some time before I get acquainted enough with it to know what I'm doing.

In the larger scope of things, the tooling I'm writing deals with HCL itself, so if there is a method that whatever model is chosen could be used for Otto and Nomad as well would be awesome. Nomad and Otto doesn't seem to use a "schema" like Terraform does to dictate expected input/output and appear to use more of a object of objects hierarchy with different types.

**Comment by apparentlymart** [comment]
Hi all!

This is covering similar ground as #17018, and there's some more recent discussion there, so I'm going to close this one to consolidate the discussion even though this is the older of the two. Sorry for the long silence here.
