### ISSUE TITLE
aws_db_instance.skip_final_snapshot defaults to false as of 0.6.9

### ISSUE THREAD

**Issue by joescii** [hashicorp/terraform#4655]
Removing an `aws_db_instance` fails on `terraform apply` with the following error even though `skip_final_snapshot` is NOT specified:

```
 Error applying plan:
 
 1 error(s) occurred:
 
 * aws_db_instance.db_instance: DB Instance FinalSnapshotIdentifier is required when a final snapshot is required
```

This change was introduced in `0.6.9`.  I have confirmed that I do not get this behavior in `0.6.8`.  

Explicitly setting `skip_final_snapshot = true` allows the instance to be successfully removed.

[Documentation](https://terraform.io/docs/providers/aws/r/db_instance.html#skip_final_snapshot) states that the default is true.  If this change was intentional, then the documentation needs an update.  

Also, it seems terraform could provide a message letting the user know when `skip_final_snapshot` is `false`, but `final_snapshot_identifier` is unspecified.  As it is, I am able to go about my merry way until I try to remove the RDS resource and I'm left to decipher the AWS API message.

**Comment by catsby** [comment]
Hey @joescii – sorry for the very, very late response here. We're already on Terraform v0.6.16 (v0.7.0 soon!) and I believe the issue has been addressed. I was able to plan -> apply -> destroy the below config with no trouble.

```
resource "aws_db_instance" "default" {
  identifier           = "mydb-rds-new"
  engine               = "mysql"
  engine_version       = "5.6.23"
  instance_class       = "db.t2.micro"
  name                 = "mydb"
  username             = "foo"
  password             = "barbarbar"
  parameter_group_name = "default.mysql5.6"

  apply_immediately = true

  allocated_storage = 10
}
```

If you feel I've made a mistake in closing this, please let me know! I apologize again for the silence here

**Comment by joescii** [comment]
No problem, thanks for checking it out!
