### ISSUE TITLE
Openstack: Ability to assign floating IP to specific network interface 

### ISSUE THREAD

**Issue by aunraza** [hashicorp/terraform#4677]
Hi, when trying to associate a floating IP to a compute instance with multiple networks, it is only possible to assign it to the first interface. Is it possible to change the functionality where it can be used to assign it to a specific fixed IP, similar to how it's mentioned in the Openstack docs:
> If an instance is connected to multiple networks, you can associate a floating IP address with a specific fixed IP address using the optional --fixed-address parameter:
> 
>` $ nova floating-ip-associate --fixed-address FIXED_IP_ADDRESS \`
>  ` INSTANCE_NAME_OR_ID FLOATING_IP_ADDRESS`

Thanks.

**Comment by jtopjian** [comment]
Soon!

Thank you for the reminder. Support for this was just [recently merged](https://github.com/rackspace/gophercloud/pull/403) into Gophercloud, so now I can work on getting it done in Terraform.

**Comment by aunraza** [comment]
Great news! Thanks!

On Fri, 15 Jan 2016 1:17 am Joe Topjian <notifications@github.com> wrote:

> Soon!
>
> Thank you for the reminder. Support for this was just recently merged
> <https://github.com/rackspace/gophercloud/pull/403> into Gophercloud, so
> now I can work on getting it done in Terraform.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/terraform/issues/4677#issuecomment-171782292>
> .
>
-- 

-Aun

**Comment by aunraza** [comment]
Hi Joe, when do you think we will be able to get this feature into terraform?

**Comment by jtopjian** [comment]
Sorry for the delay -- although it sounds like a simple change, it required a significant reconfiguration.

#4812 has the proposed change. Would you be able to test it out similar to testing the Personalities feature?

**Comment by aunraza** [comment]
Thanks Joe! Definitely can test it out.

**Comment by aunraza** [comment]
Joe, it works! :+1:

**Comment by jtopjian** [comment]
Awesome, thank you very much for testing!

I'll leave this open for a few days to give other people a chance to comment. Although this patch doesn't break backwards compatibility, there are a lot of changes.
