### ISSUE TITLE
Request: AWS Autoscaling metrics

### ISSUE THREAD

**Issue by gwilym** [hashicorp/terraform#4683]
On top of detailed per-instance metrics, AWS supports cloudwatch metrics at the autoscaling group level, such as counts of instances in various states.

I'm unsure if this can be enabled when the resource is created, it appears as though it must be enabled with a secondary API call.

The related documentation is here: http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/as-metricscollected.html

Collection can be enabled (and disabled) via the AWS CLI like so:

```
aws autoscaling enable-metrics-collection --granularity 1Minute --auto-scaling-group-name GROUPNAME
```

**Comment by stack72** [comment]
@gwilym so I have worked on this and have sort of thought it would be better to be specific on the metrics we want to collect rather than just letting it use the default of **all** metrics

What are your thoughts on that?

**Comment by gwilym** [comment]
I would err on the side of any Terraform standards or precedences that might exist for things similar to this since, regardless of the AWS APIs default behaviour, consistency in the Terraform config is important as users may not be familiar with the underlying API.

If there's no precedence in Terraform, then I'd probably let the API default of "unspecified" equals "all metrics" stand.

I don't have a personal preference, I'll just be happy to move a few manual API calls into Terraform, so thanks for working on this!

**Comment by vancluever** [comment]
@stack72, I would say if in doubt, let's go with the way that CloudFormation does it, see [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-metricscollection).

I haven't looked, but if this is supported in API, I think it's a good precedent.

Going to give your code a go too :)

**Comment by radeksimko** [comment]
Can we close this now, when https://github.com/hashicorp/terraform/pull/4688 is merged?

**Comment by stack72** [comment]
@radeksimko apologies for not closing this sooner - didn't realise it was still linked

**Comment by gwilym** [comment]
:bow:
