### ISSUE TITLE
Ignore Changes to ASG desired/min/max size

### ISSUE THREAD

**Issue by ElliotG** [hashicorp/terraform#4696]
This is either a bug, a misunderstanding of the feature, or a feature request. I'm attempting to set up an ASG via terraform. The capacity is managed by an external source, which then blocks all Terraform applys until someone updates the terraform plan manually:

Repro:
1. Create an ASG of size 1 via Terraform
2. Modify the ASG in the console to size 2
3. Modify the launch configuration of the ASG
4. Run a terraform plan (note that this looks correct)
5. Run a terraform apply

Barf:

```
* aws_autoscaling_group.sweet-servers: diffs didn't match during apply. This is a bug with Terraform and should be reported.
```

It seems like terraform plan correctly respects the "ignore changes", but Terraform apply does not.

Any advice? Is this known?

Terraform snippet because why not:

```js
resource "aws_autoscaling_group" "sweet-servers" {
    desired_capacity          = 1
    max_size                  = 1
    min_size                  = 1
    }

    lifecycle {
        ignore_changes = [ "desired_capacity", "max_size", "min_size" ]
    }
}
```

**Comment by phinze** [comment]
Hi @ElliotG - this is definitely a bug in Terraform. I'm rolling up `ignore_changes` issues in #5627 and tackling fixes today.
