### ISSUE TITLE
Documentation of the (close) Transformers

### ISSUE THREAD

**Issue by knuckolls** [hashicorp/terraform#4707]
Spelunking in the terraform code to find the right place to add functionality to terraform. Is there any existing documentation or better tooling surrounding debugging the graph traversal? I can go by the output of TF_LOG=1 terraform apply and see the graph as the transforms happen, but I do not understand what the (close) nodes are in the graph.

Does anyone know the function of these nodes, why they are added and what happens when the graph traversal reaches them?

**Comment by phinze** [comment]
Hi @knuckolls!

You can find more detail on the "close" nodes in the PR that added them: https://github.com/hashicorp/terraform/pull/2406

Happy to chat more about specifics if you want to outline the functionality you're trying to add.

**Comment by mitchellh** [comment]
Closing due to lack of response. I do think better documentation of the internals is in order soon!
