### ISSUE TITLE
provider/aws: Error assigning new user in new role assume_role_policy

### ISSUE THREAD

**Issue by wamonite** [hashicorp/terraform#4709]
Similar to #1885, when creating a new iam user and new role with the user ARN in the assume_role_policy trust relationship, Terraform returns the error `MalformedPolicyDocument: Invalid principal in policy`. Reapplying the plan after a delay or including a sleep as a local-exec provisioner will succeed.

This behaviour is reproducable in Terraform v0.6.9 with the following statements:-

    resource "aws_iam_user" "test_user" {
      name = "test_user"
    
    //  provisioner "local-exec" {
    //    command = "sleep 5"
    //  }
    }
    
    resource "aws_iam_role" "test_role" {
      name = "test_role"
      assume_role_policy = <<EOF
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "AWS": "${aws_iam_user.test_user.arn}"
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }
    EOF
    }

Produces the following logs:-

    aws_iam_user.test_user: Creating...
      arn:       "" => "<computed>"
      name:      "" => "test_user"
      path:      "" => "/"
      unique_id: "" => "<computed>"
    aws_iam_user.test_user: Creation complete
    aws_iam_role.test_role: Creating...
      arn:                "" => "<computed>"
      assume_role_policy: "" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"AWS\": \"arn:aws:iam::<aws_account>:user/test_user\"\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}\n"
      name:               "" => "test_role"
      path:               "" => "/"
      unique_id:          "" => "<computed>"
    Error applying plan:
    
    1 error(s) occurred:
    
    * aws_iam_role.test_role: Error creating IAM Role test_role: MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::<aws_account>:user/test_user"
        status code: 400, request id: 1d75a8d8-bd0e-11e5-bd58-3f23872fa8da

Suggest adding backoff/retry of the role creation on that error condition if the element is a known dependency (and will have a look at doing a PR myself if I get a chance).

**Comment by dmfenton** [comment]
adding a depends_on block resolved this for me

**Comment by dtolnay** [comment]
I have a fix in #7324 which does a 10-second retry.
