### ISSUE TITLE
aws_autoscaling_group > vpc_zone_identifier documentation error

### ISSUE THREAD

**Issue by frntn** [hashicorp/terraform#471]
The documentation says : 
- `vpc_zone_identifier` : (Optional) A list of vpc IDs to launch resources in.

But I get the following error using an **existing** vpc :

    * Error creating Autoscaling Group: ValidationError: The subnet ID 'vpc-198e497c' does not exist

The error says the **subnet ID** doesn't not exist  ....because I didn't provide any subnet id :)

The `terraform apply` was successfull after giving the list of subnet (id instead of the list of vpc_id) : 

    vpc_zone_identifier = ["${aws_subnet.public-a.id}","${aws_subnet.public-b.id}"]

**Comment by mitchellh** [comment]
Fixed.

**Comment by ryanmaclean** [comment]
The original error has reared its head again when applying a VPC ID here:

`aws_autoscaling_group.asg: Error creating Autoscaling Group: ValidationError: The subnet ID 'vpc-b9cc6fgf' does not exist`

I'm assuming the docs should state that a list of VPC subnet IDs are needed, not the VPC ID.
