### ISSUE TITLE
provider/openstack: ICMP type 0 can't be referenced in secgroup configuration

### ISSUE THREAD

**Issue by deniszh** [hashicorp/terraform#4716]
According to documentation https://www.terraform.io/docs/providers/openstack/r/compute_secgroup_v2.html 
```
ICMP Rules

When using ICMP as the ip_protocol, the from_port sets the ICMP type and the to_port sets the ICMP code. To allow all ICMP types, set each value to -1, like so:

rule {
  from_port = -1
  to_port = -1
  ip_protocol = "icmp"
  cidr = "0.0.0.0/0"
}
A list of ICMP types and codes can be found here.
``` 
and ICMP rules list https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Control_messages
I should be able to set  "from_port = 0" to allow "Echo reply" ICMP message. But in fact 0 is not allowed:
```
1 error(s) occurred:

* openstack_compute_secgroup_v2.test_secgroup: Error creating OpenStack security group rule: A FromPort must be set
```
- it triggers error in [gophercloub library](https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/extensions/defsecrules/requests.go#L45-L47)

**Comment by jtopjian** [comment]
Ah - nice find! 

I'll open an issue in the Gophercloud repo for this. If I have time soon, I'll submit a patch as well. I'll keep this issue opened here since it affects Terraform.
