### ISSUE TITLE
Value "0" interpreted as empty

### ISSUE THREAD

**Issue by jangrewe** [hashicorp/terraform#4718]
I'm trying to use a AutoScaling Schedule to shut down a couple of instances during the night, but setting
```
resource "aws_autoscaling_schedule" "infra-down" {
[...]
    min_size = "0"
    max_size = "0"
    desired_capacity = "0"
}
```
gives me an error that i need to set at least one of the values. If i then set max_size to 1, it is also used as desired_capacity, which results in 1 instance staying up.
So it doesn't matter if i use "0" or 0 (without quotes), it's always "empty".

**Comment by stack72** [comment]
hi @jangrewe this has been reported in #4690 so we should track the issue there and avoid the duplicate if that's ok?

**Comment by jangrewe** [comment]
sure, sorry! =)

**Comment by stack72** [comment]
Nothing to apologise for at all :) Just wanted to make you aware of the issue already being tracked so that you don't feel your issue is being over looked :+1:
