### ISSUE TITLE
provider/vsphere: Crash when creating "vsphere_virtual_machine"

### ISSUE THREAD

**Issue by mehlert** [hashicorp/terraform#4727]
Running terraform v0.6.9

Panic due to type issues? In vsphere our datastore is nested within a folder:

```
2016/01/18 16:14:11 [DEBUG] terraform-provider-vsphere: panic: reflect.Set: value of type mo.Folder is not assignable to type mo.Datastore
```

gist of crash.log

https://gist.github.com/mehlert/746b13d7881081528b7d

**Comment by chrislovecnm** [comment]
@mehleet there are two problems here. First we do not support this feature yet, secondly we need to fail gracefully.
