### ISSUE TITLE
aws_ecr_repository creation from loop throws error about missing name attribute

### ISSUE THREAD

**Issue by fromonesrc** [hashicorp/terraform#4744]
I'm running into some trouble using a workaround for the lack of array/list support from https://github.com/hashicorp/terraform/issues/57. I'm trying to create a bunch of ECR repos from a comma delimited string:

```
variable "ecr_repos" {
    default = "jenkins-master,jenkins-slave"
}

resource "aws_ecr_repository" "repo" {
    count = "${length(split(",", var.ecr_repos))}"
    name = "${element(split(",", var.ecr_repos), count.index)}"
}

resource "aws_ecr_repository_policy" "policy" {
    policy = "${file("iam/policies/default_ecr.json")}"
    repository = "${aws_ecr_repository.repo.name}"
}
```
but I get this error:

`* Resource 'aws_ecr_repository.repo' does not have attribute 'name' for variable 'aws_ecr_repository.repo.name'`

Should this work or is there a better way to accomplish this without repeating the repo and policy blocks for each repo name?

**Comment by stack72** [comment]
Hi @fromonesrc 

this will work in 0.7 as we can use lists as variables

Paul
