### ISSUE TITLE
availability_zone getting cleared on aws vpn gateway in statefile

### ISSUE THREAD

**Issue by qgriffith** [hashicorp/terraform#4752]
Using terraform 0.6.9 the availability_zone is getting cleared from the state file and terraform is trying to re-create the vpn becasue the state file contains a blank availability_zone when the vpn has a availability_zone attached to it.  When manually editing the state file to put the availability_zone back, the next plan will clear the availability_zone and try to re-build the vpn.

State file

```
               "aws_vpn_gateway.vpn_gateway": {
                    "type": "aws_vpn_gateway",
                    "depends_on": [
                        "aws_vpc.main"
                    ],
                    "primary": {
                        "id": "vgw-xxxx",
                        "attributes": {
                            "availability_zone": "",
                            "id": "vgw-xxxx",
                            "tags.#": "1",
                            "tags.Name": "xxx",
                            "vpc_id": "vpc-xxx"
                        }
                    }
                }
            }
        },
```

We are setting the avalability_zone on the resource config for the vpn. The root cause could be that AWS API may not be returning the avalabilty_zone and terafform is blanking it out. Instead if AWS returns a blank value the current value should be kept. 

```
resource "aws_vpn_gateway" "vpn_gateway" {
    vpc_id = "${aws_vpc.main.id}"
    availability_zone = "us-west-2a"

    tags {
        Name = "vpn-us-west-2"
    }
}
```

**Comment by stack72** [comment]
Hi @qgriffith 

Apologies for the issue here and how long it has taken to get this worked on. I have just opened PR #8645 to solve the issue

Paul
