### ISSUE TITLE
vSphere Provider: Windows guest error: A specified parameter was not correct

### ISSUE THREAD

**Issue by gitmayor** [hashicorp/terraform#4755]
Hi Guys,
Thanks you for your amazing tool. I am evaluating TF 0.6.9 and so far have good impressions, however some of the scenarios I tried were not successful. I tried to provision Windows box in vSphere, but it failed with error: “A specified parameter was not correct. spec.identity”. Looks like vm was created but customization failed. I saw some comments related to similar issues, but I am not sure if you support Windows guests not on vSphere provider.
I would be grateful for any sensible explanation. I attached TF output.
Thanks,
GM
[windows.error.txt](https://github.com/hashicorp/terraform/files/97482/windows.error.txt)

**Comment by jen20** [comment]
Hi @gitmayor! Thanks for opening the issue. Looking at the output you attached, this looks like a bug in the vsphere provider. Vsphere is community-maintained, and I personally don't have much knowledge of it, but I'll try to route this to someone who can address it.

**Comment by daryn-kerr** [comment]
Morning all, has there been any updates on this bug?

**Comment by ryanl-ee** [comment]
+1, the vSphere provider is Hashicorp-maintained in Terraform as of October 5th, 2015

**Comment by p-prakash** [comment]
+1, this issue still persists in version v0.6.14

**Comment by chrislovecnm** [comment]
@gitmayor @p-prakash @ryanl-ee we have an merged PR from windows support https://github.com/hashicorp/terraform/pull/6087

Does this resolve this problem?

**Comment by p-prakash** [comment]
@chrislovecnm Yes, it worked for me. Thanks!

**Comment by chrislovecnm** [comment]
@gitmayor can we close this? Will keep it open a couple of more days

**Comment by gitmayor** [comment]
Thanks. Let me look and back to you.

Dnia 16 kwi 2016 o godz. 19:54 Chris Love <notifications@github.com> napisał(a):

**Comment by chrislovecnm** [comment]
@gitmayor ping ... will leave this open a bit longer, or you can reopen 😄

**Comment by gitmayor** [comment]
Thank You


Dnia 19 kwi 2016 o godz. 19:59 Chris Love <notifications@github.com> napisał(a):

**Comment by chrislovecnm** [comment]
@gitmayor any updates?

**Comment by chrislovecnm** [comment]
@gitmayor ping ...

**Comment by gitmayor** [comment]
Hi Chris,
Thank you for ping message. I have some issues with vsphere environment. So, give me few days to test.
Cheers,
Tomek

Dnia 8 maj 2016 o godz. 16:49 Chris Love <notifications@github.com> napisał(a):

**Comment by chrislovecnm** [comment]
@gitmayor knudge 😄

**Comment by chrislovecnm** [comment]
@gitmayor please let me know if we can close. We will close in a couple of days if, and you can reopen at your convenience

**Comment by gitmayor** [comment]
Thanks Chris. Please close. I will test en reopen uf needed. Im still waiting for environment.

Dnia 23 maj 2016 o godz. 21:41 Chris Love <notifications@github.com> napisał(a):

**Comment by chrislovecnm** [comment]
@stack72 @jen20 @catsby can we close?
