### ISSUE TITLE
Tags are not applied, instances are not placed in ELB

### ISSUE THREAD

**Issue by levinotik** [hashicorp/terraform#477]
I'm using binaries built directly from master and it seems that at random times, tags are not applied to AWS instances and instances are not placed in ELBs. I experienced this same behavior with 0.2.2 as well as 0.3.0

**Comment by joescii** [comment]
I encountered this exact issue while mimicking some of @levinotik's work.  I managed a workaround by always renaming the ELB to force it to rebuild.  For anyone in need, this is how I did it:

In my shell script, I create a timestamp to append to the name and pass it in as a var:

```bash
timestamp=`date +"%Y%m%d%H%M%S"`
ELB_NAME=elb-${timestamp}
./terraform/terraform apply  \
  -var "elb_name=${ELB_NAME}" 
```

Then of course, I add it to my variables `tr` file and reference it accordingly:

```
// variables.tr
variable "elb_name" {}
```

```
// infra.tr
resource "aws_elb" "my-elb" {
  name = "${var.elb_name}"
  // ...
}
```

**Comment by phinze** [comment]
Hey folks - I'm making a sweep of old issues. We change up tags and ELB instance registration on a near-daily basis in our own environments, and we've seen no troubles in recent versions of Terraform.

If any of you are still experiencing issues, would you mind filing a fresh issue w/ repro steps? Thanks!
