### ISSUE TITLE
aws_nat_gateway should accept a count parameter

### ISSUE THREAD

**Issue by ryanking** [hashicorp/terraform#4771]
In order to have a multi-AZ deployment I use a variable with an AZ count to build my network. To have a nat_gateway in each AZ easily this resource needs to support that.

**Comment by apparentlymart** [comment]
In principle `count` should work for this resource just as it does for any other resource, but I assume you tried this and ran into some issues.

Would you mind sharing the relevant parts of your attempted config, with any sensitive information removed? I'd like to better understand what aspect of this isn't working for you.

**Comment by jen20** [comment]
Hi @ryanking - as @apparentlymart, `aws_nat_gateway` does already support counts - for example:

```hcl
resource "aws_nat_gateway" "private" {
    count = "${length(split(",", var.private_subnets))}"

    allocation_id = "${element(aws_eip.nat_eip.*.id, count.index)}"
    subnet_id = "${element(aws_subnet.private.*.id, count.index)}"
}
```

If you can post the relevant part of your configuration we can hopefully figure out what is going on here.

**Comment by ryanking** [comment]
Not sure what I was doing wrong (I had backed that attempt out). I tried
again and it appears to be working.

-ryan

**Comment by jen20** [comment]
:+1: Good news!
