### ISSUE TITLE
Rapidly recreating aws_vpc_peering connection fails 

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform#4781]
I had a vpc peering connection called "foo", which I decided to rename to "bar"

ie.:

```
"resource "aws_vpc_peering_connection" "foo" {
```

to

```
"resource "aws_vpc_peering_connection" "bar" {
```

Firstly, terraform 0.6.9 incorrectly identified that this resource required DESTROYING then CREATING. But we could live with that so we proceeded anyway (bug 1)

Secondly, after a succesful destroy and recreate, a subsequent terraform show showed that the new resource had the ID of the OLD vpc_peering_connection. In AWS console, there was no vpc_peering_connection named "bar" at all (was not created) - and ... as the OLD one was marked as deleted, the setting up of any routes connected with this terraform resource failed with a "you dont own the pgw resource".

I suspect a bug on TF side, AND a bug on AWS side if you rapidly destroy/create the same peering connection.

Solution was to do a TF plan-destroy of the vpc_peering_connection, AND all the routes associated with it , apply this, and then replan the resources back

Bizarre.!

**Comment by jen20** [comment]
Hi @gtmtech! Thanks for opening an issue. Renaming the resource _will_ require a destroy/create unless you manually modify the state - since we have no real rename refactoring at the moment. This is a long standing request being tracked in #591. However, I think you may have identified a bug in the `aws_vpc_peering_connection` resource here, which we will need to investigate.

**Comment by stack72** [comment]
Hi @gtmtech 

Apologies we haven't gotten back to you on this in a while - I believe this has been fixed. We now refresh the peering connection from state on these status':

```
		status := map[string]bool{
			"deleted":  true,
			"deleting": true,
			"expired":  true,
			"failed":   true,
			"rejected": true,
                    }
```

Please let us know if this is still an issue

Thanks

Paul

**Comment by stack72** [comment]
Hi @gtmtech 

I am going to go ahead and close this out as I haven't heard back from you on the issue. I believe this is now fixed :) Please do let me know if it is still causing you issues

Paul
