### ISSUE TITLE
`wait_for_elb_capacity` vs. `min_elb_capacity`

### ISSUE THREAD

**Issue by chiefy** [hashicorp/terraform#4792]
We just upgraded to TF `0.6.9` and I changed over to using `wait_for_elb_capacity` from the deprecated `min_elb_capacity` which I had hard-coded as `1` in my template (because all our deploys have at least one instance on the ELB). 

Started seeing stuff like this:
```
14:18:06 Error applying plan:
14:18:06 
14:18:06 1 error(s) occurred:
14:18:06 
14:18:06 * aws_autoscaling_group.main_asg: Still waiting for "xxxx-1453413312-asg" instances. Current/Desired: 4/4 ASG, 4/1 ELB
```

I think I understand why the change was made, but it's a little confusing with the above `4/1` output. 

If you set your `health_check_type` to ELB and don't specify a `wait_for_elb_capacity` could it default to your ASG min?

Again, not really sure if this is a bug, but maybe something that could be better explained in the docs?

**Comment by phinze** [comment]
Hi @chiefy, thanks for reporting this.

I think this change in behavior didn't consider use cases like yours, where you were setting the `min_capacity` to something less than desired.

Now that I see your scenario, I think we should treat this as a regression. So I will un-deprecate and restore the original behavior of `min_elb_capacity`. PR to follow!

**Comment by chiefy** [comment]
thanks @phinze :+1:
