### ISSUE TITLE
aws_ecs_task_definition fails to decode container_definitions JSON with numeric strings

### ISSUE THREAD

**Issue by reidab** [hashicorp/terraform#4797]
This is somewhat of a minor quibble, but since it represents a potentially-common use case, I thought I should raise it. When defining an AWS ECS Task Definition, I'll often use the [AWS console tool](https://console.aws.amazon.com/ecs/home?region=us-east-1#/taskDefinitions/create) to generate initial JSON, then paste it into a local file for Terraform to manage.

The JSON generated by this tool serializes numeric fields (such as `memory` and `portMappings[hostPort]`) as strings instead of integers, like so:

``` json
{
    "containerDefinitions": [
        {
            "name": "terraform-issue-example",
            "image": "terraform-issue-example",
            "memory": "123",
            "portMappings": [
                {
                    "hostPort": "123",
                    "containerPort": "123",
                    "protocol": "tcp"
                }
            ],
            "environment": null,
            "mountPoints": null,
            "volumesFrom": null,
            "extraHosts": null,
            "logConfiguration": null,
            "ulimits": null,
            "dockerLabels": null
        }
    ],
    "volumes": []
}
```

When I copy the `container_definitions` array from this JSON and define an `aws_ecs_task_definition` to load it, running `terraform apply` results in:

```
Error decoding JSON: json: cannot unmarshal string into Go value of type int64
```

Once I edit the JSON to remove all the quotes around integer values, `terraform apply` succeeds.

**Comment by bilal-fazlani** [comment]
+1. It would be great to have this enhancement

**Comment by mvisonneau** [comment]
👍 

I couldn't manage to parametrize the configuration of some elements using a template. That would be really cool if we could do it :

```json
[
  {
    "name": "busybox",
    "image": "${docker_image}",
    "cpu": "${cpu}",
    "memory": "${memory}"
  }
]
```

**Comment by ekowcharles** [comment]
Interestingly you can actually interpolate the memory value but without the quotes.

Something like:
```
[
  {
    "name": "busybox",
    "image": "${docker_image}",
    "cpu": ${cpu},
    "memory": ${memory}
  }
]
```

**Comment by xsmaster** [comment]
Thanks to @ekowcharles for pointing out you can interpolate with out quotes.

I think this should be an enhancement to the docs. I'm able to pram the my task definitions file like so.

```json
[
  {
    "name": "${container_name}",
    "image": "${format("%s/%s:%s", url, docker_image, docker_tag)}",
    "cpu": ${container_cpu},
    "memory": ${container_memory},
    "essential": true,
    "portMappings": [
      {
        "containerPort": ${container_port},
        "hostPort": ${container_host_port}
      }
    ],
    "dockerLabels": {
      "app": "${container_app_label}"
    }
  }
]
```

And the above works just fine. 


Looking at the ECS Task Definitions prams [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)

memory - int
cpu - int
containerPort - int
hostPort - int

If you try and put them as strings you will get the following message

```
Error applying plan:

1 error(s) occurred:

* aws_ecs_task_definition.node: Error decoding JSON: json: cannot unmarshal string into Go value of type int64
```

I hope this helps others.

J

**Comment by aledalgrande** [comment]
Well isn't that interesting. Now the opposite generates an error:
```
...
      {
        "name": "PORT",
        "value": 80
      },
...
```

**Comment by mboudreau** [comment]
I don't think that not having the quotation marks around the interpolation is adequate, as now my IDE cannot parse the JSON properly and can't tell me of any issues I might have. We need terraform to be able to figure out that a variable is a number being injected and remove the quotation marks automatically like it does for everything else within tf files.
