### ISSUE TITLE
Terraform thinks aws_route_table changes have not been applied

### ISSUE THREAD

**Issue by ascendantlogic** [hashicorp/terraform#4799]
I created a series of `aws_route_table` resources and recently have added more route entries to these tables. My initial `plan` and `apply` commands worked as expected but subsequent `plans` show that TF does not believe the changes have been applied, leading TF to repeatedly apply the same changes over and over.

Here is the relevant TF code:
```HCL
resource "aws_route_table" "monitor_public" {
  vpc_id = "${aws_vpc.monitoring.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.monitoring.id}"
  }

  route {
    cidr_block = "${var.dev_vpc_cidr}"
    gateway_id = "${aws_vpc_peering_connection.development.id}"
  }

  route {
    cidr_block = "${var.prod_vpc_cidr}"
    gateway_id = "${aws_vpc_peering_connection.production.id}"
  }

  tags { Name = "${var.monitor_vpc_name}-public" }
}
```

Originally I just had the default route sending traffic out over the IGW, but have recently added the bottom two routes.

I have spoken with @catsby about this and he feels he knows what the issue is.

**Comment by catsby** [comment]
A full config file that reproduces this:

- https://gist.github.com/catsby/7c4427854cf565ee32a5

**Comment by ascendantlogic** [comment]
@catsby built off your PR branch, ran a plan and everything looks clean.

**Comment by ascendantlogic** [comment]
![](http://33.media.tumblr.com/0cc1168d686a73990a3982193392889b/tumblr_n41f73NSti1sg002wo1_500.gif)

**Comment by catsby** [comment]
whoops... this is because we're using `gateway_id` instead of `vpc_peering_connection_id`... why the AWS API is OK with this (and even sorts it out in the background), is a mystery 

![iiam](https://cloud.githubusercontent.com/assets/61721/12522007/bc824556-c113-11e5-93ee-d4e657999950.gif)
