### ISSUE TITLE
Cannot apply/destroy if CodeDeploy resources are removed out-of-band.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#4802]
Terraform is unable to proceed with an `apply` or `destroy` if CodeDeploy applications and deployment groups are removed outside of Terraform (via the AWS console or API). 

This is with Terraform v0.6.9. 

Full config and log are at https://gist.github.com/clstokes/2a93f8a915de464367b8.

```
$ terraform destroy -force
aws_iam_role.example: Refreshing state... (ID: codedeploy-404-name)
aws_codedeploy_app.example: Refreshing state... (ID: a28dbd3e-2041-4e05-be28-b6e6f4df226f:codedeploy-404-name)
aws_codedeploy_deployment_group.example: Refreshing state... (ID: 79bc3c2c-eb27-47fa-9200-945200450b8b)
Error refreshing state: 1 error(s) occurred:

* aws_codedeploy_deployment_group.example: DeploymentGroupDoesNotExistException: No Deployment Group found for name: codedeploy-404-name
	status code: 400, request id: 1f7e97de-c12c-11e5-9729-6d2c7b1a7698
```

**Comment by arsdehnel** [comment]
This doesn't seem to be limited to just out-of-band removals.  I have changed the name of my deploy group in my codedeploy module (https://github.com/arsdehnel/recipe-box-infra/blob/master/module-codedeploy/main.tf) and TF doesn't seem to be able to apply those changes properly.  If I change the name of my codedeploy app then TF creates a new setup for the pair of them but it does not recognize it as a change but rather a new one (and never destroys the old).

Attempting to `terraform destroy -force` the whole thing isn't working either, same error as indicated above.

**Comment by JagoMar** [comment]
I am experiencing this exact issue with terraform V0.11.11.

**Comment by gurre** [comment]
Same here. I triggered it when changing the name of a `aws_codedeploy_deployment_group`.

```
$ terraform apply -auto-approve
...
aws_codedeploy_app.ec2: Creating...
  compute_platform: "" => "Server"
  name:             "" => "ec2"
  unique_id:        "" => "<computed>"
aws_codedeploy_app.lambdas: Creating...
  compute_platform: "" => "Lambda"
  name:             "" => "lambdas"
  unique_id:        "" => "<computed>"
aws_codedeploy_app.lambdas: Destruction complete after 0s
aws_codedeploy_app.ec2: Destruction complete after 0s

...

Error: Error applying plan:

* aws_codedeploy_app.ec2: 1 error(s) occurred:

* aws_codedeploy_app.ec2: ApplicationAlreadyExistsException: ec2 already exists.
	status code: 400, request id: ***

* aws_codedeploy_app.lambdas: 1 error(s) occurred:

* aws_codedeploy_app.lambdas: ApplicationAlreadyExistsException: lambdas already exists.
	status code: 400, request id: ***
```

Retrying `terraform apply -auto-approve`

```
* aws_codedeploy_deployment_group.ec2: 1 error(s) occurred:

* aws_codedeploy_deployment_group.ec2: aws_codedeploy_deployment_group.ec2: ApplicationDoesNotExistException: No application found for name: ec2
	status code: 400, request id: ***
* aws_codedeploy_deployment_group.lambda: 1 error(s) occurred:

* aws_codedeploy_deployment_group.lambda: aws_codedeploy_deployment_group.lambda: ApplicationDoesNotExistException: No application found for name: lambda
	status code: 400, request id: ***
```

**Comment by JagoMar** [comment]
@gurre I did the same thing, however is a little tedious process if you have a large stack. Not the end of the world.

**Comment by merwinlin** [comment]
try to modify your terraform.state , delete the old deployment group in json and re-build
