### ISSUE TITLE
Crash when aws_security_group_rule cidr_blocks value is empty.

### ISSUE THREAD

**Issue by clstokes** [hashicorp/terraform#4804]
If I do an `apply` with an `aws_security_group_rule` with a `cidr_blocks` array that has an empty value, Terraform crashes. This happens if the `cidr_blocks` array has a single empty value or any value that is empty - e.g. `["123.123.123.123/32",""]`. I'm not expecting an empty value to be valid here, but it can happen relatively easily if provided by a variable that isn't set correctly.

This is with Terraform v0.6.9. 

Full config, output log, and crash log are at https://gist.github.com/clstokes/4ba09036f080a3497be9#file-main-tf.

```
tf-bug $ terraform apply
aws_security_group.default_egress: Creating...
  description: "" => "Default Egress"
  egress.#:    "" => "<computed>"
  ingress.#:   "" => "<computed>"
  name:        "" => "default_egress"
  owner_id:    "" => "<computed>"
  vpc_id:      "" => "<computed>"
aws_security_group.default_egress: Creation complete
aws_security_group_rule.default_egress: Creating...
  cidr_blocks.#:            "" => "1"
  from_port:                "" => "0"
  protocol:                 "" => "-1"
  security_group_id:        "" => "sg-3ac08f43"
  self:                     "" => "0"
  source_security_group_id: "" => "<computed>"
  to_port:                  "" => "0"
  type:                     "" => "egress"
Error applying plan:

1 error(s) occurred:

* aws_security_group_rule.default_egress: unexpected EOF

...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

...
```

**Comment by catsby** [comment]
Thanks @clstokes – looks like @jen20 addressed this in https://github.com/hashicorp/terraform/pull/4140. It no longer crashes, but gives an error message:

```
Error applying plan:

1 error(s) occurred:

* aws_security_group_rule.ingress_1: empty element found in cidr_blocks - consider using the compact function
```
