### ISSUE TITLE
digitalocean_image artifact ID doesn't match what the DO API expects

### ISSUE THREAD

**Issue by Jalle19** [hashicorp/terraform#4807]
If you use `image = "${atlas_artifact.foo.id}"` on a `digitalocean_droplet` resource, applying changes will fail with `POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation`. This is because `atlas_artifact.foo.id` resolves to something like `fra1:123123` when it should resolve to `123123`. Changing the Terraform template to use a hardcoded number makes the apply go through normally.

This makes it cumbersome to use DigitalOcean snapshot artifacts. I've tried both 0.6.9 and 0.6.8 and the issue is the same in both.

**Comment by Jalle19** [comment]
Apparently the region prefix was added as hack to workaround an issue in the Vagrant post-processor for Packer. Either that work around should be reverted or the Terraform provider will need to strip the region prefix before using the ID.

**Comment by lminaudier** [comment]
Hi there,

Indeed I faced a similar issue. As a workaround I used `elem` and `split` functions like so.

```
resource "digitalocean_droplet" "web" {
  name = "web"
  image = "${element(split(":", atlas_artifact.web.id), 1)}"
  region = "lon1"
  size = "512mb"
}
```
