### ISSUE TITLE
Raw string and string looked up from a map behave differently

### ISSUE THREAD

**Issue by dlanger** [hashicorp/terraform#4809]
Terraform `0.6.9`

This generates a plan when I `terraform plan`:
```
module "public_subnets" {
  source = "github.com/terraform-community-modules/tf_aws_public_subnet"
  cidrs = "10.0.0.0/27,10.0.0.32/27"
  [...]
}
```

But when I run the same `terraform plan` with this:
```
variable "lut" {
  default {
    test-one = "10.0.0.0/27,10.0.0.32/27"
  }
}

module "public_subnets" {
  source = "github.com/terraform-community-modules/tf_aws_public_subnet"
  cidrs = "${lookup(var.lut, test-one)}"
  [...]
}
```
I get this:
```
Error configuring: 2 error(s) occurred:

* strconv.ParseInt: parsing "${length(split(\",\", var.cidrs))}": invalid syntax
* strconv.ParseInt: parsing "${length(split(\",\", var.cidrs))}": invalid syntax
```
Which suggests that something in the process is treating the two strings differently. 

Any ideas or work-arounds known?

**Comment by apparentlymart** [comment]
Hi @dlanger. Sorry that you are seeing this issue.

I am a little confused about your situation since your config example shows a variable lookup but your error is about a string split. Is there more config elsewhere that uses that interpolation expression?

However in your cidrs example I would note that you need to put "test-one" in quotes.

**Comment by dlanger** [comment]
Hi @apparentlymart - thanks for getting back to me. I shouldn't be writing bug reports at 1:30am, because problems seem clearer in the light of day. 

In trying to come up with a better reduced test case, it looks like an underlying cause is https://github.com/hashicorp/terraform/issues/1336, possibly combined with an error being eaten (but I can't reduce that part down to a more specific example to bring up here).

Sorry about the issue-noise.
