### ISSUE TITLE
TF_VAR_ style environment variables not being used

### ISSUE THREAD

**Issue by chris-hailstorm** [hashicorp/terraform#4815]
Attempted a `terraform get`. Received this error:

> Error loading Terraform: Error initializing remote driver 'atlas': missing 'access_token' configuration or ATLAS_TOKEN environmental variable

However when I look at `env | grep -i atlas`, I have line like this:

> TF_VAR_atlas_token=Hydtv...

If I then do `export ATLAS_TOKEN=jshjshjsd...` and try `terraform get`, no such error.

Shouldn't any `TF_VAR_x` environment variables take the place of Terraform variable x?

**Comment by phinze** [comment]
Hi @chris-hailstorm, the `TF_VAR_` env var pattern will set a value for a Terraform variable that has been declared like this:

```tf
variable "foo" { }
```

Separately, providers and remote state drivers document specific env vars that can be used to configure them. These are not Terraform Variables, so they don't get set with the `TF_VAR_` style env vars.

I hope this helps to clarify! I'm going to close this issue for now, but feel free to follow up if you have further questions on this. :+1:
