### ISSUE TITLE
Bucket Policy in example Cloudtrail Code allows global write access

### ISSUE THREAD

**Issue by eyj** [hashicorp/terraform#4817]
Hi,

It appears to me that the example bucket policy given at 
https://www.terraform.io/docs/providers/aws/r/cloudtrail.html
allows anyone (Principal: *) to write to the given bucket. In the corresponding AWS docs
http://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html
the principal is given as {"Service": "cloudtrail.amazonaws.com"}

I'd suggest changing this in the example, since people might not check the permission too carefully.

**Comment by radeksimko** [comment]
Hi @eyj 
thanks for the report, this has been already fixed and will be visible on the linked page along with the next release:
https://github.com/hashicorp/terraform/pull/4730
