### ISSUE TITLE
aws_instance: diffs didn't match during apply 

### ISSUE THREAD

**Issue by jfromaniello** [hashicorp/terraform#4819]
I am getting a  **diffs didn't match during apply** if I apply a configuration that needs to create an `aws_instance`. The resource has this lifecycle:

```
    lifecycle {
        ignore_changes          = ["ami", "key_name"]
    }
```

If I remove this part it works as expected and does create the instance.

**Comment by phinze** [comment]
Hi @jfromaniello - thanks for the report, I'm consolidating the active `ignore_changes` issues in #5627 and working on fixes today. :+1:
