### ISSUE TITLE
provisioner remote-exec > uploaded commands should be wiped out after exec

### ISSUE THREAD

**Issue by frntn** [hashicorp/terraform#482]
When provisioning a server using `remote-exec` provisioner there is a remaining `/tmp/script.sh` which contains either : 
- for `inline` argument : *all the executed commands*
- for `script` argument : *the full script*
- for `scripts` argument : *the last script of the array*

This can lead to security issue. 
This file should be deleted by default.

**Comment by kaelumania** [comment]
What about appending a script as last component that deletes itself?

**Comment by frntn** [comment]
**LGTM**

Considering the following user provided script
```bash
$ cat <<EOF >/tmp/script.sh
#!/bin/bash
echo "provisioner remote-exec script : I do something..."
EOF

$ chmod +x /tmp/script.sh

$ ls -l /tmp/script.sh
-rwxrwxr-x 1 frntn frntn 70 Apr 22 14:11 /tmp/script.sh
```

Terraform can append a autodelete command (try shred / fallback to rm)  
```bash
$ cat <<EOF >>/tmp/script.sh
command -v shred >/dev/null && shred -uxz \$(readlink -f \$0) || rm -f \$(readlink -f \$0)
EOF

$ sh -c '/tmp/script.sh'
provisioner remote-exec script : I do something...

$ ls -l /tmp/script.sh
ls: cannot access /tmp/script.sh: No such file or directory
```
