### ISSUE TITLE
core: Add support for "terraform untaint" command (undo taint)

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#4820]
When user taints a resource, it is very difficult (from user's point of view basically impossible) to undo that step.

Therefore I think that having either `terraform untaint` or `terraform taint -undo` (final syntax is not really the concern) to undo what user has done via `terraform taint` would be useful.

**Comment by phinze** [comment]
Yep definitely. The lack of this feature is just an oversight. Should be relatively easy to implement as well.

**Comment by apparentlymart** [comment]
Don't we support multiple tainted instances for the same resource?

In which case this would presumably need some way for the user to inspect all of the possible tainted resources and choose which one to restore.

I'm not sure if there are any real cases where a user can end up with multiple tainted instances of the same resource, though. I guess you could end up in this state if you have a tainted instance and you then somehow(?) end up creating a new primary instance without destroying the tainted instance, and then you explicitly `terraform taint` that new primary leaving you with two tainted instances. But AFAIK Terraform always disposes of tainted instances ASAP during apply so I'm not really sure how that could happen...

**Comment by danielnbarbosa** [comment]
+1 for untaint feature!

**Comment by ryanmcmichael** [comment]
+1 !

**Comment by anarcher** [comment]
+1

**Comment by wsh** [comment]
This would make my life easier. :)

**Comment by brikis98** [comment]
+1

Also, what's the "manual" way to untaint until such a feature is added?

**Comment by phinze** [comment]
> Also, what's the "manual" way to untaint until such a feature is added?

If you crack open the `terraform.tfstate` file and make your way to the resource in question, it's got a `"primary"` key and a `"tainted"` array. Move the object out of the `"tainted"` array and under `"primary".

![zsh](https://cloud.githubusercontent.com/assets/37534/13576394/2093481c-e453-11e5-9df3-a0ce08a81c78.png)

We'll get this feature done soon - hope this helps in the meantime! :+1:

**Comment by brikis98** [comment]
@phinze: Got it, thank you!
