### ISSUE TITLE
aws_db_instance resource to include argument for non default encryption key 

### ISSUE THREAD

**Issue by rmldsky** [hashicorp/terraform#4822]
Currently one can set `storage_encrypted` argument to `true` and expect to have encryption at rest enabled on RDS instance. This uses the default encryption key (from AWS KMS service). It would be useful to have ie. `encryption_key` argument which takes an ARN of a key which already exists (created from AWS console or maybe in the future from `aws_kms` resources) to encrypt with.

**Comment by stack72** [comment]
Hi @rmldsky 

I have finally gotten around to adding a PR for this - sorry it took so long!

Paul

**Comment by krushi90** [comment]
@stack72 Thanks for addressing this. I have been waiting for this. Do you know when will be the next release that includes this feature?

**Comment by stack72** [comment]
Hi @krushi90 

This feature won't hit until 0.7 (which will be a little while yet) - but at least you know it's in there and scheduled for release 

P.

**Comment by stack72** [comment]
merged to master :)

**Comment by krushi90** [comment]
Thanks @stack72 . Waiting for 0.7 release

**Comment by xatnys** [comment]
@stack72 Does this also apply for a `aws_rds_cluster` and related resources?

**Comment by stack72** [comment]
Hi @xatnys 

Unfortunately this specific PR was only for db_instance. If you need it added to the others, please can you open an issue with what resources need it?

thanks 

Paul
