### ISSUE TITLE
provider/aws: add support for (Cloudwatch) Events

### ISSUE THREAD

**Issue by qivers** [hashicorp/terraform#4827]
http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/WhatIsCloudWatchEvents.html
http://docs.aws.amazon.com/cli/latest/reference/events/index.html

I've no idea if this is already in the pipeline, or seen whether this has been requested elsewhere, but being able to Terraform this would be massively useful.

**Comment by radeksimko** [comment]
Thanks for creating this issue @qivers .

I do plan to work on this in the upcoming week(s). It's in my pipeline after making Lambda work correctly, i.e. after https://github.com/hashicorp/terraform/pull/4826 & https://github.com/hashicorp/terraform/pull/3825 & https://github.com/hashicorp/terraform/pull/4770

The `aws_lambda_permission` will make CloudWatch Events actually useful for Lambda users so it IMO makes sense to do that first.

**Comment by qivers** [comment]
That's awesome, thanks @radeksimko

**Comment by anosulchik** [comment]
+1 That would be great to have this functionality in terraform.

**Comment by radeksimko** [comment]
WIP in #4986

**Comment by radeksimko** [comment]
The mentioned PR has been merged and CW Events will be part of the next release.
