### ISSUE TITLE
Azure ARM resource parity with Azure ASM

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#4836]
In order to get the newer Azure Resource Manager provider to feature parity with the Azure Service Management API provider, we need to make the following resources (or their newer equivalents) work with ARM:

- [x] Data Disk
- [x] DNS Zone
- [x] DNS RecordSets
- [x] Virtual Machine ("instance")
- [x] Local Network Connection
- [x] Network Security Group
- [x] Network Security Group Rule
- [x] SQL Database Server
- [x] SQL Database Server Firewall Rule
- [x] SQL Database Service
- [x] Storage Blob
- [x] Storage Container (is this the same as account?)
- [x] Storage Queue
- [x] Storage Account
- [x] Virtual Network

Once we have resource parity we can consider deprecating the ASM API, and potentially moving it into a separate repository as an unsupported API for continuity only.

**Comment by stack72** [comment]
Storage blob, container and queue are in PR #4842

**Comment by xied75** [comment]
@jen20 Is the idea is that we focus on getting the new thing work and leave the old rot even it's not working correctly? Would there be an estimate of how long will this take?

**Comment by jen20** [comment]
@xied75 The idea is eventually to remove the ASM API provider from the Terraform distribution, and leave it available as a separately distributed "as-is" provider for those who depend on it, but without any continuing work.

The message from Microsoft is clear that ASM is out and ARM is in. Unfortunately the Microsoft-generated Go client for Azure has a _lot_ of bugs and missing features (see issues opened by myself and @stack72), so it is rather slow going. Because it is generated, we can't fix bugs directly, and the needs of internal Microsoft teams get prioritised over external users. I have something in the works to resolve this though - I'll update here when more work has been done.

I'm expecting 0.7 will have resource parity and that the ASM provider will be gone by then, though.

**Comment by jen20** [comment]
Affinity Groups no longer exist in ARM by the look of it - it seems their functionality is subsumed into virtual networks, which are already supported: https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-migrate-to-regional-vnet/

**Comment by jen20** [comment]
Looks like Hosted Services are no more in the ARM API as well, so I'm going to remove that.

**Comment by joaocc** [comment]
Hi.
Any idea on when we can test Virtual Machine ("instance") in the AzureRM provider?
We are migrating from Azure's Templates, so VM is kindof important :)
Thx!

**Comment by stack72** [comment]
Hi @joaocc, we are working on this right now

Paul

**Comment by joaocc** [comment]
Great! Thx!

**Comment by colemickens** [comment]
Are there plans to support service principal management via AzureRM with Terraform?

**Comment by joaocc** [comment]
Hi @stack72. Can you share something on the progress on AzureRM? Thx!

**Comment by elmalto** [comment]
Really interested in the progress!

**Comment by stack72** [comment]
Hi @joaocc & @elmalto 

I have opened #5514 as a WIP. Just a FYI, I have been able to build basic linux and windows images using pre-defined images

I need to write a few more tests to make sure that everything works as expected

**Comment by BigCheeze45** [comment]
Really excited to hear this :+1:  :+1:

**Comment by avdhoot** [comment]
+1 it will be great,  if we get this feature ( Virtual Machine ) in next release.

**Comment by jen20** [comment]
Virtual Machine is now merged, which I believe brings us to resource parity with the ASM provider! :confetti_ball: :confetti_ball: :confetti_ball:

**Comment by avdhoot** [comment]
thanks @stack72 for all effort
