### ISSUE TITLE
Unable to build master

### ISSUE THREAD

**Issue by wr0ngway** [hashicorp/terraform#4837]
Tried to build master this am from a clean git clone of the terraform repo.  Looks like a problem with updatedeps for the azure-sdk-for-go package?

```
export XC_OS=${XC_OS:-darwin}
export XC_ARCH=${XC_ARCH:-amd64}
tfsrc="/opt/gopath/src/github.com/hashicorp/terraform"
vagrant ssh -c "make -C $tfsrc updatedeps"
vagrant ssh -c "XC_OS='$XC_OS' XC_ARCH='$XC_ARCH' make -C $tfsrc bin"
```

```
make: Entering directory `/opt/gopath/src/github.com/hashicorp/terraform'
go get -u github.com/mitchellh/gox
go get -u golang.org/x/tools/cmd/stringer
go list ./... \
		| xargs go list -f '{{join .Deps "\n"}}' \
		| grep -v github.com/hashicorp/terraform \
		| grep -v '/internal/' \
		| sort -u \
		| xargs go get -f -u -v
github.com/apparentlymart/go-cidr (download)
github.com/apparentlymart/go-rundeck-api (download)
github.com/armon/circbuf (download)
github.com/armon/go-radix (download)
github.com/aws/aws-sdk-go (download)
github.com/go-ini/ini (download)
github.com/jmespath/go-jmespath (download)
github.com/Azure/azure-sdk-for-go (download)
package github.com/Azure/azure-sdk-for-go/arm/resources: no buildable Go source files in /opt/gopath/src/github.com/Azure/azure-sdk-for-go/arm/resources
github.com/Azure/go-autorest (download)
<snipped>
google.golang.org/api (download)
make: *** [updatedeps] Error 123
make: Leaving directory `/opt/gopath/src/github.com/hashicorp/terraform'
```

**Comment by jen20** [comment]
Hi @wr0ngway! Thanks for opening an issue. I'm not able to replicate this though - from a fresh checkout in an empty gopath, I can `make updatedeps` and `make dev` fine (on OS X), and the build history on Travis (Linux) seems to agree: https://travis-ci.org/hashicorp/terraform/builds/104828097.

That said - I recall that error appearing a while back when Microsoft moved all the code around in their SDK. Could you ensure you are on master and not a branch which may be tracking the old import paths, and if so try removing the Azure SDK from your gopath and allowing `go get` to update it?

**Comment by wr0ngway** [comment]
Thanks for the quick response @jen20 - I'm definitely on master, and I'm actually building in vagrant on osx, so everything is as clean as I can make it.  Did you try duplicating using vagrant?

```
vagrant destroy
vagrant up
export XC_OS=${XC_OS:-darwin}
export XC_ARCH=${XC_ARCH:-amd64}
tfsrc="/opt/gopath/src/github.com/hashicorp/terraform"
vagrant ssh -c "make -C $tfsrc updatedeps"
vagrant ssh -c "XC_OS='$XC_OS' XC_ARCH='$XC_ARCH' make -C $tfsrc bin"
```

**Comment by jen20** [comment]
I didn't try in Vagrant directly (which base box etc?), but Travis builds from a complete checkout every time on a container roughly equivalent to Ubuntu 14.04 with Go 1.5.2, so that shouldn't be an issue. Can you let me know the SHA of the commit you are building, and the SHA of `azure/azure-sdk-for-go`?

**Comment by wr0ngway** [comment]
I'm was using the Vagrantfile supplied in the terraform repo, but nevermind, I'm an idiot, I was hitting a fork not the hashicorp repo :)  Sorry about that, closing...
