### ISSUE TITLE
provider/aws: add support for ecs_service deployment configuration

### ISSUE THREAD

**Issue by nemski** [hashicorp/terraform#4847]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_paramters.html

Specifically the `maximumPercent` and `minimumHealthyPercent` values

**Comment by aldarund** [comment]
ye, need that too. But there already ticket for this - https://github.com/hashicorp/terraform/issues/4456

**Comment by radeksimko** [comment]
Hi @nemski ,
@aldarund is right, I will close this as a duplicate of the mentioned issue.
