### ISSUE TITLE
support signum function on interpolation

### ISSUE THREAD

**Issue by jfromaniello** [hashicorp/terraform#4853]
I have found that most of my cases where I need iterators can be solve with `count.index` and some math function given a length (modulo is quite useful!). 

signum can be useful in the following scenario:

```
variable "r53_failover_policy" {
    value = "PRIMARY,FAILOVER"
}

resource "aws_route53_record" "rec" {
    count    = "${var.servers}"
    ...
    failover = "%{element(split(",", var.r53_failover_policy), signum(count.index))}"
}
```

Given than signum returns 0 for 0 and 1 for every positive number, this means that the first one will have `PRIMARY` the rest will be `FAILOVER`. This pattern is quite useful for other resources as well.

**Comment by radeksimko** [comment]
Implemented in https://github.com/hashicorp/terraform/pull/4854
