### ISSUE TITLE
provider/aws: db_instance - username & name may conflict w/ snapshot_identifier

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform#4857]
The snapshot identifier is one I found publicly available in the AWS Console - I don't know who owns it or what data is in that snapshot, but it helps reproducing this without having to create a fresh RDS instance and creating snapshot (basically takes double the time and time is expensive, especially when it comes to RDS).

``` hcl
provider "aws" {
    region = "us-west-2"
}

resource "aws_db_instance" "example" {
    identifier = "example-master"
    allocated_storage = 5
    engine = "mysql"
    instance_class = "db.t2.small"
    name = "example"
    username = "username"
    password = "secretPassword"
    snapshot_identifier = "arn:aws:rds:us-west-2:169582328751:snapshot:test"
    final_snapshot_identifier = "example-final-snapshot"
}
```

```
$ terraform apply
```

```
$ terraform plan
```

```
-/+ aws_db_instance.example
    address:                    "example-master.REDACTED.us-west-2.rds.amazonaws.com" => "<computed>"
    allocated_storage:          "5" => "5"
    apply_immediately:          "" => "<computed>"
    arn:                        "arn:aws:rds:us-west-2:0_REDACTED_0:db:example-master" => "<computed>"
    auto_minor_version_upgrade: "true" => "1"
    availability_zone:          "us-west-2a" => "<computed>"
    backup_retention_period:    "7" => "<computed>"
    backup_window:              "08:15-08:45" => "<computed>"
    copy_tags_to_snapshot:      "false" => "0"
    db_subnet_group_name:       "default" => "<computed>"
    endpoint:                   "example-master.REDACTED.us-west-2.rds.amazonaws.com:3306" => "<computed>"
    engine:                     "mysql" => "mysql"
    engine_version:             "5.6.23" => "<computed>"
    final_snapshot_identifier:  "example-final-snapshot" => "example-final-snapshot"
    identifier:                 "example-master" => "example-master"
    instance_class:             "db.t2.small" => "db.t2.small"
    license_model:              "general-public-license" => "<computed>"
    maintenance_window:         "mon:06:27-mon:06:57" => "<computed>"
    multi_az:                   "false" => "<computed>"
    name:                       "staging" => "example" (forces new resource)
    parameter_group_name:       "default.mysql5.6" => "<computed>"
    password:                   "secretPassword" => "secretPassword"
    port:                       "3306" => "<computed>"
    publicly_accessible:        "" => "<computed>"
    replicas.#:                 "0" => "<computed>"
    skip_final_snapshot:        "true" => "1"
    snapshot_identifier:        "arn:aws:rds:us-west-2:169582328751:snapshot:test" => "arn:aws:rds:us-west-2:169582328751:snapshot:test"
    status:                     "available" => "<computed>"
    storage_type:               "gp2" => "<computed>"
    username:                   "thekey1" => "username" (forces new resource)
    vpc_security_group_ids.#:   "1" => "<computed>"
```

If there was no initial `name` (db name) used when creating the initial RDS instance and then snapshot was used as `snapshot_identifier` for a fresh `db_instance`, then you'd see `"" => "example"` in the diff above.

This is a follow up to https://github.com/hashicorp/terraform/issues/4671 and explanation of what I meant in https://github.com/hashicorp/terraform/issues/4671#issuecomment-175126610 @catsby 

After all it looks like it may not be a genuine bug, but it definitely is confusing.

Snapshot restore is [an operation which happens in a separate API call](https://github.com/hashicorp/terraform/blob/master/builtin/providers/aws/resource_aws_db_instance.go#L319-L326) - i.e. it's not really a builtin AWS' feature to create a new DB instance and take the data from an existing backup, it's an extra value brought by Terraform.

Since restoring RDS snapshot will restore all the data including the initial user & database, I'm coming to a conclusion that we should just mark `username` & `name` as conflicting with `snapshot_identifier` in the schema.

How to deal with password is another question. That would need to be tested. I would assume that after restoring snapshot, you will be able to reset the password, but originally the snapshot is restored with the original password (it would make sense).

The other option is just to expect users to know exactly what's in the snapshot they're restoring data from (db name + username + password).

**Comment by catsby** [comment]
Interesting ... 

> it's not really a builtin AWS' feature to create a new DB instance and take the data from an existing backup

You can restore a snapshot into a new DB from the console, unless I misunderstand what you mean here..

> Since restoring RDS snapshot will restore all the data including the initial user & database, I'm coming to a conclusion that we should just mark username & name as conflicting with snapshot_identifier in the schema.

This makes sense. They are all optional/computed anyway, I don't believe they make sense to specify when you know you're restoring from a snapshot. 

> How to deal with password is another question. That would need to be tested. I would assume that after restoring snapshot, you will be able to reset the password

This... seems tricky. The API never returns the password, so, we'll never know if they don't match up. The work around would be to restore with a password (or none), and after successfully restoring then change the password. We'd have to document this, I suppose. I don't know a way around it :unamused:

**Comment by radeksimko** [comment]
> You can restore a snapshot into a new DB from the console, unless I misunderstand what you mean here..

Yeah, I misread that piece of code I linked to, you're right. I blame the lengthy conditions with multiple levels of indentation and somewhat duplicated logic. :stuck_out_tongue: :smiley: 

Interestingly AWS allows you to define all of those _potentially conflicting_ parameters in the API (or at least the CLI does).
http://docs.aws.amazon.com/cli/latest/reference/rds/restore-db-instance-from-db-snapshot.html
