### ISSUE TITLE
Optimal way to perform following operations

### ISSUE THREAD

**Issue by madhurranjan** [hashicorp/terraform#4858]
I've been able to setup a k8s cluster on coreos with 2 files - `master.tf` and `minion.tf`. Its a highly available k8s master setup with 3 nodes frontended by an elb and route53 entry. I want to be able to , on the fly, setup either a 1 node , 3 node or 5 node etcd cluster which is not possible with the way I've done it now because of the following 2 reasons. 

a. When I need to setup the initial `ETCD_INITIAL_CLUSTER`, I've used the below as I couldn't think of a better way. I tried using `count` in here but it generates 3 templates , with all values being `etcd0` or `etcd1` or `etcd2`.

```
etcd_servers_cluster = "etcdinfra0=http://${aws_instance.kube_master.0.private_ip}:2380,etcdinfra1=http://${aws_instance.kube_master.1.private_ip}:2380,etcdinfra2=http://${aws_instance.kube_master.2.private_ip}:2380"
```

How can the above statement be more generic?

b. I've had to copy 3 files after generating them separately as below.

``` hcl
 provisioner "local-exec" {
        command = "/bin/cat > rendered/kubelet_cloudinit_0 <<EOL  \n${template_file.kubelet_cloudinit.0.rendered}" 
    }  -> kubelet_cloudinit_0 -> this has ETCD_NAME=etcdinfra0
    provisioner "local-exec" {
        command = "/bin/cat > rendered/kubelet_cloudinit_1 <<EOL \n${template_file.kubelet_cloudinit.1.rendered}" -> this has ETCD_NAME=etcdinfra1
    }
    provisioner "local-exec" {
        command = "/bin/cat > rendered/kubelet_cloudinit_2 <<EOL \n${template_file.kubelet_cloudinit.2.rendered}"  -> this has ETCD_NAME=etcdinfra2
    }
```

Can I use templates and transfer them to remote locations without writing to a localfile and copying them over ? Also, how can I generate 3 templates with only 1 value differing, `ETCD_NAME` in this case ?

Can you provide suggestions as to how I can improve this ? I did quite a bit of searching online but couldn't find a better way.

**Comment by iMoses** [comment]
I came across a similar situation, what works best for me is creating a simple bash script which excepts a space separated list  to execute my logic.

Consider something such as this:

my_script.sh
```
#!/bin/bash -x

count=0

for var in "$@"
do
    /bin/cat > rendered/kubelet_cloudinit_$count <<EOL  \n$var
    count=$((count + 1))
done
```

```
provisioner "local-exec" {
    command = "my_script.sh ${join(" ", template_file.kubelet_cloudinit.*.rendered)}" 
}
```

**Comment by mitchellh** [comment]
Please ask general usage questions on our mailing list or gitter, we try to reserve issues for bugs and feature requests. Thanks!
