### ISSUE TITLE
Improve the "Diffs didn't match" error message

### ISSUE THREAD

**Issue by jen20** [hashicorp/terraform#4859]
Following up from a question in one of the public IRC rooms that @phinze and I were in, it seems there is scope to improve the "diff's don't match" error message with the additional information captured in the log to describe which attributes do not match.

Example: https://gist.github.com/nwalke/358d13e9e8520bc15276 (the relevant info is actually on the line preceeding the contents of this gist).

**Comment by phinze** [comment]
Done in https://github.com/hashicorp/terraform/pull/5276 :+1:
