### ISSUE TITLE
dyn_record creation returns "404 Not Found"

### ISSUE THREAD

**Issue by anero** [hashicorp/terraform#4862]
When attempting to create a DNS A record on a non-root zone we get a _dyn_record.sentry: Failed to create Dyn record: Bad response, got "404 Not Found"_

Our template file looks like this:

```
provider "dyn" {
    customer_name = "${var.dyn_customer_name}"
    username = "${var.dyn_username}"
    password = "${var.dyn_password}"
}

...

resource "dyn_record" "sentry" {
    zone = "whatever.example.com"
    name = "server"
    value = "${aws_instance.server.public_ip}"
    type = "A"
    ttl = 600
}
```

We've verified using Dynect's ruby SDK that the credentials set on the provider work on the REST API.

**Comment by kevinlondon** [comment]
@anero: I hit the same thing just now but there's a workaround. I think Dyn wants to use the TLDs as the primary Zones, so you have to arrange it like this:

```
resource "dyn_record" "sentry" {
    zone = "example.com"
    name = "server.whatever"
    value = "${aws_instance.server.public_ip}"
    type = "A"
    ttl = 600
}
```

**Comment by anero** [comment]
@kevinlondon That did the trick, thanks for the workaround!

**Comment by kevinlondon** [comment]
One unfortunate side-effect of this is that you can't limit a user to a certain zone. E.g. if you create a user that can only modify `whatever.example.com` and subnodes, they'll get a 400 if they try to use the workaround I suggested.

**Comment by stack72** [comment]
Hi @anero / @kevinlondon 

I am going to close this. It seems to be an error with Dyn rather than terraform. Please comment if you feel otherwise

Thanks

Paul
