### ISSUE TITLE
`terraform plan` should complain when using more than one of gatewayId, natGatewayId, networkInterfaceId, vpcPeeringConnectionId or instanceId

### ISSUE THREAD

**Issue by adamtheturtle** [hashicorp/terraform#4863]
`terraform plan` did not complain when setting `instance_id` and `network_interface_id` for an AWS route table. However, `terraform apply` gave the following error:

```
Error applying plan:                                                                                                        

1 error(s) occurred:                                                                                                        

* aws_route_table.r: InvalidParameterCombination: The request must contain exactly one of gatewayId, natGatewayId, networkInterfaceId, vpcPeeringConnectionId or instanceId                                                                             
        status code: 400, request id:                                                                                       

Terraform does not automatically rollback in the face of errors.                                                            
Instead, your Terraform state file has been partially updated with                                                          
any resources that successfully completed. Please address the error                                                         
above and apply again to incrementally change your infrastructure.
```

**Comment by zccollad** [comment]
Having somewhat the same issue her... I am running on a Mac OS

packet_device.virl (remote-exec): + /usr/local/bin/vinstall salt
packet_device.virl (remote-exec): /tmp/terraform_14271347.sh: 16: /tmp/terraform_14271347.sh: /usr/local/bin/vinstall: not found
Error applying plan:

1 error(s) occurred:

* Script exited with non-zero exit status: 127

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by enkaskal** [comment]
IMO, this should just be handled in the `apply`. Therefore, I've written a fix and will attack the PR momentarily. Not sure if it's up to standards, but it works for me, I will be moving it into production in the near future, and the `make test` as well as `make testacc` fail in the same places.

Further, I have written a 0.10.x fix that I will submitting shortly.

HTH & Just my $0.02 :)
