### ISSUE TITLE
Providers are not inherited by grandchildren

### ISSUE THREAD

**Issue by orclev** [hashicorp/terraform#4865]
When you declare a provider and then import a module, the child module has access to the provider declared in the parent. If the imported child module in turn imports a module the grandchild module does not have access to the provider declared in the grandparent.

[terraform-bug-repro.zip](https://github.com/hashicorp/terraform/files/107158/terraform-bug-repro.zip)

In the reproduction sample provided there is a root TF file, and 3 modules. The root calls module 1, which calls module 2, which calls module 3, all 3 modules instantiate a resource. In order for this to execute without error a provider must be declared in the root and module 2. Module 1 inherits its provider from the root, and module 3 inherits its provider from module 2. If the provider is left out of module 2 it will attempt to instantiate a new provider rather than use the one that module one has inherited from the root.

The following issues appear to be relevant to this issue: 
#3285
#1819

**Comment by scottcunningham** [comment]
Any word on this? This has stung me too recently.

**Comment by Bowbaq** [comment]
@phinze running into this today, trying to adapt some scripts from https://github.com/hashicorp/best-practices/tree/master/terraform. Somehow, on the first run it worked fine, but then I must have changed something, and now it's completely ignoring the `aws` provider declared in the root module. Any ETA on a fix?

**Comment by phinze** [comment]
@Bowbaq I was just reviewing issues today and this made it onto a short list to look into - you can work around it by switching to environment variable based config, but I agree it's annoying. Will see if I can get this sorted out before the 0.6.13 release. :+1:

**Comment by Bowbaq** [comment]
@phinze any updates on this?

**Comment by phinze** [comment]
Sorry I haven't been able to get to this yet - just noting that this is still on my (ever-shuffling) stack! :ok_hand:
