### ISSUE TITLE
Terraform 0.6.10 is not passing network uuid to OpenStack provider

### ISSUE THREAD

**Issue by bartekrutkowski** [hashicorp/terraform#4871]
Seems like this is the issue that was already reported and fixed here: https://github.com/hashicorp/terraform/issues/2031

With resource defined this way:

```
resource "openstack_compute_instance_v2" "syslog" {
    name = "vm-01.example.com"
    image_id = "573b1803-4c4a-4d60-91a2-d621da4bd2e5"
    flavor_name = "m1.large"
    network {
        uuid = "a2361803-4c4b-4d64-91a2-d621da4662e6"
        fixed_ip_v4 = "192.168.10.11"
    }
}
```

the application fails with:
> {"badRequest": {"message": "Bad network format: missing 'uuid'", "code": 400}}

and in the log, I can see uuid being empty when executing apply:

```
2016/01/28 10:08:28 [DEBUG] terraform-provider-openstack: 2016/01/28 10:08:28 [DEBUG] Create Options: &servers.CreateOpts{Name:"vm-01.example.com", ImageRef:"a2361803-4c4b-4d64-91a2-d621da4662e6", ImageName:"", FlavorRef:"4", FlavorName:"", SecurityGroups:[]string{}, UserData:[]uint8{}, AvailabilityZone:"", Networks:[]servers.Network{servers.Network{UUID:"", Port:"", FixedIP:"192.168.10.11"}}, Metadata:map[string]string{}, Personality:servers.Personality(nil), ConfigDrive:false, AdminPass:"", AccessIPv4:"", AccessIPv6:""}
```

**Comment by jtopjian** [comment]
Hi there,

Sorry to hear that you're running into this. 

Can you let me know a few details about your OpenStack environment? Is it a vanilla OpenStack install or are you using a vendor-modified version? What is the version of OpenStack?

**Comment by bartekrutkowski** [comment]
Seems like the problem is gone with 0.6.11, but to answer your question, the OpenStack version was Kilo, and unfortunately I dont know if its vanilla or vendor modified.
