### ISSUE TITLE
DuplicateListener when creating ELB with new certificate

### ISSUE THREAD

**Issue by saliceti** [hashicorp/terraform#4880]
This is happening on Terraform `0.6.9`.

When uploading a new certificate to IAM and creating a new ELB using this certificate in a listener, terraform fails with the error:

```
* aws_elb.concourse: Failure adding new or updated ELB listeners: DuplicateListener: A listener already exists for colin-cert-concourse with LoadBalancerPort 443, but with a different InstancePort, Protocol, or SSLCertificateId
status code: 400, request id: 3a2ed326-c5ce-11e5-9f46-a5c7d320375f
```

Code:

```
resource "aws_iam_server_certificate" "ELB name" {
  name = "ELB name"
  certificate_body = "${file("concourse.crt")}"
  private_key = "${file("concourse.key")}"

#  provisioner "local-exec" {
#    command = "sleep 10"
#  }
}

resource "aws_elb" "concourse" {
  name            = "${var.env}-concourse"
  subnets         = ["${split(",", var.infra_subnet_ids)}"]
  security_groups = ["${aws_security_group.concourse-elb.id}"]

  health_check {
    target              = "TCP:8080"
    interval            = 5
    timeout             = 2
    healthy_threshold   = 2
    unhealthy_threshold = 2
  }

  listener {
    instance_port       = 8080
    instance_protocol   = "tcp"
    lb_port             = 443
    lb_protocol         = "ssl"
    ssl_certificate_id  = "${aws_iam_server_certificate.concourse.arn}"
  }

  tags {
    Name = "${var.env}-concourse-elb"
  }
}
```

It looks like a race condition because it succeeds consistently if I add the above `sleep` in the local provisioner. It also works every time when I use `TF_LOG` `trace` or `debug` (which I assume makes terraform slightly slower).

**Comment by catsby** [comment]
Hey @saliceti – I _believe_ I fixed this with a retry in https://github.com/hashicorp/terraform/pull/4825 , are you able to build from master or try out the new Terraform v0.6.10? 

Let me know!

**Comment by saliceti** [comment]
I've tested successfully twice with 0.6.10. I think you can close the issue.
Thanks!

**Comment by catsby** [comment]
Awesome, thank you for getting back @saliceti (sorry it took me 2 weeks to reply :frowning:)
