### ISSUE TITLE
Chef Provisioner - certificate verify failed

### ISSUE THREAD

**Issue by popopanda** [hashicorp/terraform#4881]
I'm having some issues with the chef provisioner.  

```
  provisioner "chef" {
    run_list = [""]
    node_name = "${aws_instance.servera.private_dns}"
    secret_key = "${file("~/encrypted_data_bag_secret")}"
    server_url = "chef-serverURL"
    validation_client_name = "terraform-validator"
    validation_key = "${file("./terraform-validator.pem")}"
    ssl_verify_mode = "verify_none"

    connection {
      user = "centos"
      private_key = "${file("./keyfile.pem")}"
      host = "${aws_instance.servera.private_ip}"
      agent = "false"
    }
```

It goes through the chef bootstrap, but fails on the SSL Validation:

Starting Chef Client, version 12.6.0
aws_instance.servera (chef): Creating a new client identity for *removed* using the validator key.
aws_instance.servera (chef): [2016-01-28T00:28:46+00:00] ERROR: SSL Validation failure connecting to host: *removed* - SSL_connect returned=1 errno=0 state=error: certificate verify failed
aws_instance.servera (chef):
aws_instance.servera (chef): ================================================================================
aws_instance.servera (chef): Chef encountered an error attempting to create the client "*removed*"
aws_instance.servera (chef): ================================================================================

aws_instance.servera (chef):
aws_instance.servera (chef): Running handlers:
aws_instance.servera (chef): [2016-01-28T00:28:46+00:00] ERROR: Running exception handlers

Error applying plan:

1 error(s) occurred:

* Command "sudo chef-client -j \"/etc/chef/first-boot.json\" -E \"_default\"" exited with non-zero exit status: 1

I've tried using different validator keys including the one I use on my workstation to bootstrap nodes with knife.  I've set ssl_verify_mode to verify_none, and tried changing permissions on my validator key file.  Also tried with:

validation_key = "${file("terraform-validator.pem")}"
validation_key = "terraform-validator.pem"

 I am not sure what I configured incorrectly.

**Comment by svanharmelen** [comment]
@popopanda could you test this with this line:

```
 ssl_verify_mode = "verify_none"
```

changed to this:

```
 ssl_verify_mode = ":verify_none"
```

Notice the added colon. This would make Ruby read this as a symbol instead of a string from the `client.rb`.

**Comment by popopanda** [comment]
Ah that did it.  Is there a way to have ssl verification enabled?  I noticed when I do a manual knife bootstrap, it creates a /etc/chef/trusted_certs directory with the cert from my chef server, where as the chef provisioner doesn't create that

Thanks!
