### ISSUE TITLE
[azurerm] Provider doesn't support resource: azurerm_route_table

### ISSUE THREAD

**Issue by mlapida** [hashicorp/terraform#4886]
When attempting to create a route table and link the route table to a subnet in the azurerm provider, the following errors are thrown:

```
  * azurerm_route_table.main: Provider doesn't support resource: azurerm_route_table
  * azurerm_virtual_network.primary: subnet.3: invalid or unknown key: route_table_id
```

The resource block:
```
resource "azurerm_route_table" "main" {
    name = "${concat(var.prefix,"PRTBX001 - Main")}"
    location = "${var.region}"
    resource_group_name = "${azurerm_resource_group.vnet.name}"

    route {
        name = "route1"
        address_prefix = "*"
        next_hop_type = "internet"
    }
}
```

**Comment by stack72** [comment]
Hi @mlapida - what version of Terraform are you currently using?

**Comment by mlapida** [comment]
0.6.9 - was this fixed in yesterdays release?

**Comment by stack72** [comment]
@mlapida the azurerm additions were only made in 0.6.10 I'm afraid so you will need to upgrade to take advantage of them :)

**Comment by mlapida** [comment]
Worked like a charm! Thank you! :)

**Comment by stack72** [comment]
Excellent - let us know if there are any issues with it
