### ISSUE TITLE
Module fetch over Git converts line endings

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/terraform#4889]
This might be a go-getter problem, but it is confusing nonetheless. When pulling a module from a git source, line endings are converting to CRLF on windows, despite what is specified in msysgit or the gitconfig. This results in upstart or other UNIX tools getting really confused for Windows users.

Steps to reproduce:

1. Boot Windows

2. Example TF config:

    ```terraform
    module "consul" {
      source = "github.com/sethvargo/tf-consul-atlas-join"
      # ...
    }
    ```

3. `terraform get`

4. `terraform apply`

Then look and upstart will fail because LF is converted to CRLF on `terraform get` :frowning: 

/cc @phinze @mitchellh

**Comment by mitchellh** [comment]
I think the correct behavior here is likely keeping whatever the line endings are in the repo (never do any conversion). You're also correct that this is likely a go-getter thing.

**Comment by mitchellh** [comment]
So I've changed my stance on this and think that it is up to the user to specify this properly using a standard `gitattributes` file: https://git-scm.com/docs/gitattributes

go-getter and thus Terraform just uses Git under the covers and doesn't request any file ending changes so your system settings will pick up those changes and do what you configured. The best way to avoid this is to specify explicitly by repository what/where you want line endings touched.
