### ISSUE TITLE
Can't use region as a variable

### ISSUE THREAD

**Issue by ronpanto** [hashicorp/terraform#489]
I am working on a master build from two hours ago.
Inside a module, I have the following code:

variable "region" {
    default = "us-east-1"
}

provider "aws" {
        access_key = "${module.globals.aws_access_key}"
        secret_key = "${module.globals.aws_secret_key}"
        region = "${var.region}"
}

and i am getting Not a valid region: ${var.region}

**Comment by mitchellh** [comment]
With #1010 coming in, this is fixed now.
