### ISSUE TITLE
nat_ip doesn't resolve

### ISSUE THREAD

**Issue by bensojona** [hashicorp/terraform#4896]
It appears that the merging [#4265](https://github.com/hashicorp/terraform/pull/4265/files#diff-940768d5a52dcf5d59e61543f4556b4aR639) - `Split Instance network interface into two fields` for the `0.6.10` release breaks backwards compatibility (using `nat_ip`).

`google_compute_instance.example.0.network_interface.0.access_config.0.nat_ip`

Updating to `assigned_nat_ip` works fine, but again, breaks BC as `nat_ip` never seems to resolve (which may actually be a bug).

`google_compute_instance.example.0.network_interface.0.access_config.0.assigned_nat_ip`

**Comment by superseb** [comment]
Also curious how this should work it, the docs state that nat_ip could be empty. Is this a breaking change, and should we convert tooling to use assigned_nat_ip?

**Comment by superseb** [comment]
ping @lwander

**Comment by lwander** [comment]
Hey, you can read the reasoning for the change here: #3841. You will need to read from `assigned_nat_ip` from now on. Sorry that this has caused you trouble.
